### ISSUE TITLE
[Regression] When selecting a folder in the project import window, the first file\folder is selected

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#100077]
### Tested versions

Happens in 4.4 dev6
Does not happen in 4.4 dev5

### System information

Godot v4.4.dev6 - Windows 10.0.19045 - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 threads)

### Issue description

When navigating through folders, in the window for selecting an imported project, or in the window for selecting a directory for a new project, the first folder or file is selected.
_Looks like we need dev7_.

### Steps to reproduce

1. Open the project manager
2. Click the Create a new project or import button
3. Navigate through the folders
4. The first file or folder is selected

### Minimal reproduction project (MRP)

N/A

**Comment by JekSun97** [comment]
Is anyone else experiencing this new bug?

**Comment by AThousandShips** [comment]
Looks like a consequence from:
* https://github.com/godotengine/godot/pull/98022

CC @vPumpking

**Comment by vPumpking** [comment]
Oh yeah
guess that can be fixed with 1 line

**Comment by vPumpking** [comment]
this is done in this method https://github.com/vPumpking/godot/blob/editor_file_dialog_filter_master/editor%2Fgui%2Feditor_file_dialog.cpp#L1151
adding a condition for it to work only when the filter field is visible might be the key

**Comment by vPumpking** [comment]
⚠️ fileDialog might have the same issue

**Comment by JekSun97** [comment]
the problem can be reopened, because it remains in dev7.

**Comment by akien-mga** [comment]
The fix was merged after dev7 was released, so that's normal, you'd need to test the `master` branch or wait for beta1.

**Comment by JekSun97** [comment]
> The fix was merged after dev7 was released, so that's normal, you'd need to test the `master` branch or wait for beta1.

Thanks for the explanation, I thought the fix was merged into dev7.
