### ISSUE TITLE
TabContainer - get_tab_under_cursor() method that returns the tab index (int) under mouse cursor

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#10001]
Basically I want to have a way to mid-click close the tab under the mouse cursor - even if it is not the current one.

Godot doesnt seem to have a way to determine what the tab index under the mouse cursor is when you hover over it with the mouse

**Comment by Noshyaar** [comment]
TabContainer isn't design for tab closing, unlike Tabs.
Tabs control already has "tab_hover" signal. Are you sure you don't want to use that instead?

**Comment by blurymind** [comment]
@Noshyaar  like close_tab_under_cursor() ? 
Sounds good :)

**Comment by blurymind** [comment]
@Noshyaar where is that tab_hover signal? I cant seem to find it in the stable version :o

**Comment by Noshyaar** [comment]
Sorry, it's in the master branch ("latest").
http://docs.godotengine.org/en/latest/classes/class_tabs.html?highlight=tab_hover

**Comment by blurymind** [comment]
@Noshyaar is there any particular reason the TabContainer node wouldnt also get the tab_hover signal?

**Comment by KoBeWi** [comment]
So basically this should've been resolved now?
@blurymind

**Comment by KoBeWi** [comment]
I'll just assume it is. The signal was added in 3.0.
