### ISSUE TITLE
Changing the window title doesn't affect FileDialog node

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#10007]
**Ubuntu 17.04 - Godot version: Both 3 and 2.1.4**

**Issue description:**
Changing the window title option in the FileDialog node doesn't do anything, showing the default title instead.

**Comment by bruvzg** [comment]
`window_title` works from code, but it is overwritten by `mode` when scene is loaded.

> [node name="FileDialog" type="FileDialog" parent="."]
> ...
> window_title = "TEST"
> resizable = false
> dialog_hide_on_ok = false
> mode = 4 :exclamation:

**Comment by akien-mga** [comment]
Fixed by #13847.
