### ISSUE TITLE
Image loader fails to import JPEG containing non-standard sampling methods

### ISSUE THREAD

**Issue by Lexpeartha** [godotengine/godot#100051]
### Tested versions

Noticed in 4.4.dev4

- Can be reproduced in: 4.3.stable, 4.4.dev4

### System information

Godot v4.3.stable - Pop!_OS 22.04 LTS - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1650 Ti (nvidia; 560.35.03) - AMD Ryzen 5 4600H with Radeon Graphics (12 Threads)

### Issue description

Image importer fails to import certain `.jpeg` images. Tried deleting cache, changing bunch of different versions of import settings, but importer still breaks and on stratup it throws:
```
  core/io/image_loader.cpp:101 - Error loading image: res://ginko.jpeg
  Error importing 'res://ginko.jpeg'.
```

This seems to only affect certain images from the project I am working on, while not the others. One of the such images has been provided in reproduction. Inspecting that specific code, it is possibly caused by 3b6705a641d9dfd2fcee24cbbdfa88efca79a840 - although not likely since it is also present in `v4.3` maybe suggesting a more fundamental problem with the image loader.

### Steps to reproduce

- Add (specific type of?) jpeg

Result is that importer fails

### Minimal reproduction project (MRP)

[Reproduction project from v4.3](https://github.com/user-attachments/files/18024694/image-importing.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/45523 and https://github.com/godotengine/godot/issues/75349.

**Comment by Vovkiv** [comment]
I actually experience something like that from time to time, but with webp images. I use Krita to draw something and then export to webp and from time to time, image fails to load in Godot. Workaround in this case to remove that image, re-export and sometimes it works, sometimes doesn't.

**Comment by adamscott** [comment]
From my debugging, `gingo.jpeg` fails importing here:

https://github.com/godotengine/godot/blob/eb5103093c1bfd4d527ec1255d28e9bc8d3625b5/thirdparty/jpeg-compressor/jpgd.cpp#L2570-L2571

`m_comp_h_samp == {2, 0, 0, 0}` and `m_comp_v_samp == {2, 0, 0, 0}`.

---

Here's ginko.jpeg in all it's glory.

<details markdown=1>
<summary>ginko.jpeg</summary>

![Image](https://github.com/user-attachments/assets/341533b9-09fb-4233-a8d1-2e324d3c5b00)

</details>
