### ISSUE TITLE
ANN: Making the bug tracker use 5-digit identifiers

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#10000]
If we want to be taken seriously as a modern and industry-relevant game engine, we need to start upgrading our issue tracker to show that we have had a lot more bugs than what it currently suggests.

Lots of bugs means we have a lot of experience, and that our product is, if not bug free, at least way less buggy than it used to be. That's a must have to appear as a stable solution to potential users.

Literally *everybody* is doing it, so we should follow the trend and start having *at least* 5-digit identifiers for our bug reports - we may eventually move to 6 digits, but let's not rush things. Some examples:
- Unity3D: 6 digits - https://issuetracker.unity3d.com/issues/modifiers-are-discarded-when-pressing-hotkey
- Unreal: 5 digits - https://issues.unrealengine.com/issue/UE-47815
- Blender: 5 digits - https://developer.blender.org/T52233
- Game Maker: Studio: 5 digits - http://bugs.yoyogames.com/view.php?id=27218
- Cocos2D: 5 digits - https://github.com/cocos2d/cocos2d-x/issues/18120

The only game-related tools with less than 5-digit identifiers are the ones without bug tracker at all, such as Lumberyard – those are obviously way out of our league, we can't compete: they are virtually bug free.

So as of today, all Godot Engine bug reports will also have 5-digit identifiers. We still have a long way to go to catch up with Unity3D which is nearing the 7-digit milestone... but with the combined efforts of our regression-inducing developers and unforgiving testers, it should be within our reach!

To [#∞](https://github.com/godotengine/godot/issues) and beyond!

**Comment by akien-mga** [comment]
Achievement unlocked!

**Comment by MagicDippyEgg** [comment]
this is the 10000th issue
