### ISSUE TITLE
Default value of `CollisionShape3D`'s property `debug_color` should not be saved in .tscn file

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#100088]
### Tested versions

- Reproducible in 4.4.dev6

### System information

Godot v4.4.dev6 - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 threads)

### Issue description

The default value of `CollisionShape3D`'s property `debug_color` (introduced in 4.4.dev6) should not be saved in `.tscn` file.
Not friendly to Version Control.

![Image](https://github.com/user-attachments/assets/9662f71a-7784-409e-b37a-b9b2c865c4a4)

### Steps to reproduce

NA

### Minimal reproduction project (MRP)

NA

**Comment by AThousandShips** [comment]
The default is configured differently, as an empty `Color`, I think there's an inconsistency between the default value and the revert here that breaks this

**Comment by dalexeev** [comment]
* See #39072.

`_validate_property()` is missing. I'll take a look.
