### ISSUE TITLE
in Inherited_scene use NOTIFICATION_SCENE_INSTANTIATED get_node() error

### ISSUE THREAD

**Issue by zedrun00** [godotengine/godot#100082]
### Tested versions

version 4.2.stable

### System information

win10, Vulkan

### Issue description

look debugger
![Image](https://github.com/user-attachments/assets/27f86e5c-591b-41e0-9782-3fa88599a24a)

### Steps to reproduce

look at up

### Minimal reproduction project (MRP)

[test_instantiated.zip](https://github.com/user-attachments/files/18032478/test_instantiated.zip)

**Comment by Rindbee** [comment]
The script is attached to the base scene, so it will receive `NOTIFICATION_SCENE_INSTANTIATED` notification **twice** when instantiating the extend scene. As the node does not exist in the base scene, so it is expected that the node cannot be obtained when the notification is received for the **first** time.

**Comment by zedrun00** [comment]
@Rindbee THX, How distinguish whether the notification from base or inherited. I not found a method.

**Comment by Rindbee** [comment]
> How distinguish whether the notification from base or inherited. I not found a method.

This is a question of determining when the script starts working, not distinguishing whether the notification is from base or inherited.

**Comment by zedrun00** [comment]
> > How distinguish whether the notification from base or inherited. I not found a method.
> 
> This is a question of determining when the script starts working, not distinguishing whether the notification is from base or inherited.
@Rindbee 
![Image](https://github.com/user-attachments/assets/6770488c-b514-400f-b5bb-70803270c9a1)
When trying to get it for the first time, it throws error. How can eliminate this error

**Comment by Rindbee** [comment]
Perhaps you could try using an exported variable and then assigning the value in inherited scene in the Inspector instead of hard-coding it to a node path that doesn't exist in the current scene.

**Comment by zedrun00** [comment]
thx

**Comment by Rindbee** [comment]
Well, looking at your method naming, you may have mistaken the order in which the methods are called.

**Comment by zedrun00** [comment]
> Well, looking at your method naming, you may have mistaken the order in which the methods are called.

俺是命名没改. 主要在onready的时候赋值太晚了, 因为有些地方要"scn.instantiate()" 之后"call子节点方法"或"set属性".
如果用onready, 都得加await ready, 巨蠢.
