### ISSUE TITLE
[D3D12] Spam of "WARNING: Returning maximum value for unknown limit 12"

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#100055]
### Tested versions

- Reproducible in master
- Not reproducible in 4.3

### System information

Godot v4.4.dev (1f47e4c4e) - Windows 10.0.22631 - Multi-window, 1 monitor - Direct3D 12 (Forward+) - integrated Microsoft Basic Render Driver (Microsoft; 10.0.22621.2506) - virt-7.2 (12 threads)

### Issue description

```plain
WARNING: Returning maximum value for unknown limit 12.
     at: RenderingDeviceDriverD3D12::limit_get (drivers\d3d12\rendering_device_driver_d3d12.cpp:6184)
```

### Steps to reproduce

1. Open Godot
2. See that the warning is spammed.

### Minimal reproduction project (MRP)

n/a

**Comment by akien-mga** [comment]
CC @RandomShaper @DarioSamo

**Comment by DarioSamo** [comment]
https://github.com/godotengine/godot/commit/16ee2f22ebcee95e0263bc00a1b785f425f8e5b3 added a check for texture size, but D3D12 driver does not implement the limits it requests.

**Comment by akien-mga** [comment]
CC @Carbonyte

**Comment by DarioSamo** [comment]
I'll do a PR implementing the limits properly.
