### ISSUE TITLE
Regression: Typing directory in the file open dialog does not work

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot#100029]
### Tested versions

Broken in 4.4-dev5, not broken in 4.3.

### System information

Windows 10

### Issue description

When typing a path in the directory of an "Open a File or Directory" dialog and pressing enter, the path goes back to what it was before.

### Steps to reproduce

Open project browser, click [Import]:
![Image](https://github.com/user-attachments/assets/79d85e37-1700-4994-b5e5-d4013ed18fba)

Type a different path in the path box:
![Image](https://github.com/user-attachments/assets/413055e9-1b32-4924-bfb7-e206515d1cd8)

Press enter, and note that it goes back to the original path:
![Image](https://github.com/user-attachments/assets/79d85e37-1700-4994-b5e5-d4013ed18fba)

In 4.3, it goes to the path typed in.

### Minimal reproduction project (MRP)

n/a - happens in project browser.

**Comment by dudemelo** [comment]
I didn't manage to reproduce it on Linux.

**Comment by JekSun97** [comment]
I can confirm that this is indeed happening in 4.4 dev5
