### ISSUE TITLE
`FileDialog` shows no files on Android

### ISSUE THREAD

**Issue by Barugon** [godotengine/godot#100034]
### Tested versions

v4.3.stable.official [77dcf97d8]
v4.4.dev5.official [9e6098432]

### System information

Godot v4.3.stable - Fedora Linux 41 (Workstation Edition) - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 7800 XT (RADV NAVI32) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

Using a `FileDialog` set to `/storage/emulated/0` shows no files, only folders. Navigating into any folder also shows no files. Setting permissions like `READ_EXTERNAL_STORAGE` or `MANAGE_EXTERNAL_STORAGE` have no effect.

### Steps to reproduce

Use the minimal project below.

### Minimal reproduction project (MRP)

Open this project, export to a device, run it and click the Open File button. A `FileDialog` will be shown pointing to `/storage/emulated/0` but you will not be able to select any file as there are none visible.

[issue.zip](https://github.com/user-attachments/files/18018653/issue.zip)

**Comment by syntaxerror247** [comment]
You need to request permission too.
See, https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-request-permission

Or, to request all permissions, see https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-request-permissions

**Comment by adamscott** [comment]
@Barugon Can you confirm that it was the issue?

**Comment by Barugon** [comment]
> You need to request permission too.
> See, https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-request-permission

What would I need to pass to this? I tried "READ_EXTERNAL_STORAGE" but that did nothing (and the return value is `false`). Also, I thought that shared storage was supposed to just be accessible without having to ask for permission now?

**Comment by Barugon** [comment]
> On Android 13+ READ_EXTERNAL_STORAGE has been replaced by granular permissions: READ_MEDIA_IMAGES, READ_MEDIA_VIDEO, and READ_MEDIA_AUDIO. These new permissions are available in 4.4.

I'm trying to read zip files that have been downloaded to the Download folder.

**Comment by Barugon** [comment]
`MANAGE_EXTERNAL_STORAGE` used with `OS.request_permissions()` works. I guess that's good enough, although I don't need to write.
