### ISSUE TITLE
Returning typed arrays created using the Array constructor fails with a typing error at runtime for inner classes

### ISSUE THREAD

**Issue by phkeese** [godotengine/godot#100096]
### Tested versions

- Reproducible in v4.3.stable.official [77dcf97d8]
No other versions were tested.

### System information

macOS Sonoma 14.4, M3 Processor

### Issue description

When returning typed arrays for inner classes from a function by way of the `Array Array(base: Array, type: int, class_name: StringName, script: Variant)` constructor, a runtime error occurs. The example only contains the case for inner classes, but in my testing it also seemed to fail when trying to return an array of typed nodes (`class_name` at start of file).

I came across this behaviour when I tried filtering child nodes (`get_children()`) and returning only those of a specific class.
The result of the filtering step is an untyped array I tried turning into a typed array using the above constructor.

**Example Code:**
```gdscript
class_name MyNode
extends Node


class Data:
	var value
	pass


func _ready() -> void:
	var typed_array := create_array()


func create_array() -> Array[Data]:
	var untyped_array := [Data.new()]
	var data := untyped_array[0] as Data
	# Fails with error:
	# Trying to return an array of type "Array[RefCounted]" where expected return type is "Array[Data]".
	#return Array(untyped_array, TYPE_OBJECT, StringName(data.get_class()), null)
	
	# Even weirder: 
	# Trying to return an array of type "Array[Data]" where expected return type is "Array[Data]".
	#return Array(untyped_array, TYPE_OBJECT, "Data", null)
	
	# Also fails:
	# Trying to return an array of type "Array[MyNode.Data]" where expected return type is "Array[Data]".
	#return Array(untyped_array, TYPE_OBJECT, "MyNode.Data", null)
	
	var typed_array : Array[Data] = []
	for val in untyped_array:
		typed_array.push_back(val)
		
	# This prints "RefCounted" which is weird because type hints actually work and suggest `value`
	# when accessing an element of this array.
	print(typed_array.get_typed_class_name())
	return typed_array
```

### Steps to reproduce

1. Write a typed function returning a typed array
2. Try to use the typed array constructor with an inner class or a node class (from `class_name`)
3. Run project, fail when the function tries to return

### Minimal reproduction project (MRP)

[array_type_error.zip](https://github.com/user-attachments/files/18038157/array_type_error.zip)

**Comment by AThousandShips** [comment]
Class names of custom types are not returned as such, see:
* #21789 

In all the construction cases you are missing the script argument, I think this is necessary for this, so try:
```gdscript
return Array(untyped_array, TYPE_OBJECT, "Data", get_script())
```

**Comment by phkeese** [comment]
Oops, it is even right there in the documentation for the constructor.
User error 🤦
