### ISSUE TITLE
Project freezes/crashes when trying to open it in 4.4dev6

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#100090]
### Tested versions

- Reproducible in 4.4dev6
- Still working in 4.4dev5

### System information

Godot v4.4.dev6 - Windows 10.0.19045 - Single-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 3700X 8-Core Processor (16 threads)

### Issue description

When trying to open my project, the editor completely freezes at this point:
![Image](https://github.com/user-attachments/assets/72aeda55-39ff-4b2d-9438-f0af46cf7425)

In the console there is no error being printed, not even in verbose mode 😥
I don't have any more information - if someone knows anything else I could do to pin this problem down I gladly do so to make this report a bit more helpful

### Steps to reproduce

- Open my project Engraving...

### Minimal reproduction project (MRP)

As I can't find out anything about the problem, it is virtually impossible to make a MRP.

**Comment by dudemelo** [comment]
Does that happen to any project or a specific projet?

**Comment by rburing** [comment]
> I don't have any more information - if someone knows anything else I could do to pin this problem down I gladly do so to make this report a bit more helpful

If you run the editor in a debugger you can interrupt (pause) the process to see where it's at (call stack).

**Comment by RPicster** [comment]
> Does that happen to any project or a specific projet?
I tested it on my hobby project Engraving, there it happens. On a new project it doesn't happen.

> > I don't have any more information - if someone knows anything else I could do to pin this problem down I gladly do so to make this report a bit more helpful
> 
> If you run the editor in a debugger you can interrupt (pause) the process to see where it's at (call stack).

I will do so on Monday, I'm away for the weekend...

**Comment by akien-mga** [comment]
@quietbytes Could you open a new bug report for this? There can be many reasons for Godot to crash and since it's not clear what's the problem in @RPicster's case, we can't really expect that your crash has the same root cause.

Your crash seems to have to do with the new CSG internals using the Manifold library.

**Comment by fire** [comment]
I want to see if the csg manifold crash has the root cause as https://github.com/godotengine/godot/issues/100073 and is fixed in master. So it should result in an empty mesh and fully works after the mend pr

**Comment by produno** [comment]
@RPicster Ensure you are not loading on a scene that has particles. Could be related to #100098 . You can check by opening the project in an earlier dev build.

**Comment by jordanlis** [comment]
Hi, same issue with dev5 and 6 on my side. It takes a very long time to load the project and then, impossible to launch it.

**Comment by MarkoGrbec** [comment]
it happened to me that CSG were made with before dev 6 and when I wanted to open scene it crashes
cylinders to be exact
the boxes were opening fine

**Comment by akien-mga** [comment]
@RPicster Do you spot any change in the 4.4-dev6 changelog that relates to features you're using?
https://godotengine.github.io/godot-interactive-changelog/#4.4-dev6

Are you using CSG maybe?

**Comment by MarkoGrbec** [comment]
> [@MarkoGrbec](https://github.com/MarkoGrbec) Can you try Godot Engine master? https://nightly.link/godotengine/godot/workflows/runner/master?preview Remember to backup etc.

hmmm, ... I cannot even open editor let alone to try to open scene with CSG
I even tried with deleting .godot folder

**Comment by MarkoGrbec** [comment]
> [@RPicster](https://github.com/RPicster) Do you spot any change in the 4.4-dev6 changelog that relates to features you're using? https://godotengine.github.io/godot-interactive-changelog/#4.4-dev6
> 
> Are you using CSG maybe?

I have no idea but I can give you MRP[testing-csg.zip](https://github.com/user-attachments/files/18100061/testing-csg.zip)

with CSG that crashes the dev-6

**Comment by akien-mga** [comment]
> > [@RPicster](https://github.com/RPicster) Do you spot any change in the 4.4-dev6 changelog that relates to features you're using? https://godotengine.github.io/godot-interactive-changelog/#4.4-dev6
> > Are you using CSG maybe?
> 
> I have no idea but I can give you MRP[testing-csg.zip](https://github.com/user-attachments/files/18100061/testing-csg.zip)
> 
> with CSG that crashes the dev-6

Thanks for the MRP!

I tested it and confirm the crash in 4.4-dev6, and that the crash is fixed in the `master` branch already.

**Comment by Saul2022** [comment]
I Guess this happens to me too but already did since dev 3 in the tps demo on the Android editor, aside from it crashing too upon loading game(as proved here  https://github.com/godotengine/godot/issues/98330 )

**Comment by RPicster** [comment]
I wanted to dig a bit deeper today and found out that it works on master.
So as I didn't really provide any detailed information for the bug: this is good enough for me - I will close this issue 🌟

**Comment by stesproject** [comment]
I noticed that my project on 4.4dev6 crashes every time I call:
`get_tree().paused = false`

Calling 
`get_tree().paused = true`
is fine.

**Comment by Saul2022** [comment]
> I noticed that my project on 4.4dev6 crashes every time I call: `get_tree().paused = false`

That´s weird,  i do have crashes too, but on an android small project that it´s not empty( kinda like since 4.4 dev 1 i think, though only reported  since dev 3 in my issue  that i posted below.

About your crash, it might be because there are many things in the tree that had to be unpaused and as such caused the crash(ram/vram related?)

**Comment by stesproject** [comment]
> > I noticed that my project on 4.4dev6 crashes every time I call: `get_tree().paused = false`
> 
> That´s weird, i do have crashes too, but on an android small project that it´s not empty( kinda like since 4.4 dev 1 i think, though only reported since dev 3 in my issue that i posted below.
> 
> About your crash, it might be because there are many things in the tree that had to be unpaused and as such caused the crash(ram/vram related?)

I just tested opening the same project with version 4.4dev5 and it doesn't happen there.
I don't know what the problem could be: the game crashes and the window closes by itself, without any errors in the console.
I am very sure the cause is the get_tree().paused = false, because I tried to call the same command from different scripts and the result is the same.
However it does not happen in a new project created with version 4.4dev6.
