### ISSUE TITLE
HMACContext falha ao inicializar no Windows 11 com Godot 4.2.2

### ISSUE THREAD

**Issue by vinicius1770** [godotengine/godot#100184]
### Tested versions

Godot Engine v4.2.2.stable.official.15073afe3

### System information

Sistema Operacional: Windows 11 Versão do Godot: Godot Engine v4.2.2.stable.official.15073afe3 Placa Gráfica: AMD Radeon(TM) Graphics (OpenGL 3.3 Core Profile Context 22.20.44.62.230414 - Compatibility) Driver da GPU: Atualizado para a versão mais recente disponível.

### Issue description

Estou enfrentando um problema ao tentar usar o HMACContext no Godot Engine 4.2.2 em um projeto no Windows 11. Sempre que tento inicializar o contexto HMAC, recebo o seguinte erro no console:

css

Falha ao inicializar o HMACContext.
Erro ao inicializar o contexto HMAC.
Erro ao criptografar a senha! 

Isso ocorre mesmo ao usar um código básico que segue o exemplo fornecido na documentação oficial do HMACContext. Testei em um projeto separado e limpo, mas o problema persiste.

### Steps to reproduce

Crie um novo projeto no Godot 4.2.2.
Adicione o seguinte script a um nó básico, como Control:

gdscript

extends Control

func hash_password(password: String) -> String:
    var hmac_context = HMACContext.new()
    var key = PackedByteArray("secure_key".to_utf8_buffer())
    
    if not hmac_context.start(HashingContext.HASH_SHA256, key):
        print("Falha ao inicializar o HMACContext.")
        return ""
    
    hmac_context.update(PackedByteArray(password.to_utf8_buffer()))
    var hashed = hmac_context.finish()
    return hashed.hex_encode()

func _ready():
    var password = "12324545"
    var hashed_password = hash_password(password)
    print("Senha criptografada: ", hashed_password)

Execute o projeto.
Verifique o console.

### Minimal reproduction project (MRP)

[HMACcontest.zip.zip](https://github.com/user-attachments/files/18054663/HMACcontest.zip.zip)
[HMACcontest.zip.zip](https://github.com/user-attachments/files/18054664/HMACcontest.zip.zip)

**Comment by vinicius1770** [comment]
Esse é um problema conhecido no Godot 4.2.2?
Existe uma solução alternativa para o HMACContext neste caso?

**Comment by AThousandShips** [comment]
The official language of these channels is English, please make any reports or comments in English, if you do not know English please use some translation software or ask for help.

**Comment by matheusmdx** [comment]
He's talking in portuguese, i can translate that


System information
Operational System: Windows 11, Godot version: Godot Engine v4.2.2.stable.official.15073afe3, GPU: AMD Radeon(TM) Graphics (OpenGL 3.3 Core Profile Context 22.20.44.62.230414 - Compatibility), GPU Driver: Updated to the most recent version.

<br>

Issue description:

I'm having an issue when i try to use HMACContext in Godot 4.2.2 in a project in windows 11. When i try to initializate the HMAC context i receive the following error:

css

Failed to initialize the HMACContext.
Error to initialize the context HMAC.
Error to encrypt the password!

<br>

Steps to reproduce:

Create a new project in Godot 4.2.2
Add the following script in a node, like Control:

```
extends Control

func hash_password(password: String) -> String:
	var hmac_context = HMACContext.new()
	var key = PackedByteArray("secure_key".to_utf8_buffer())

	if not hmac_context.start(HashingContext.HASH_SHA256, key):
		# Print translation: Failed to initialize the HMACContext.
   		 print("Falha ao inicializar o HMACContext.")
   		 return ""

	hmac_context.update(PackedByteArray(password.to_utf8_buffer()))
	var hashed = hmac_context.finish()
	return hashed.hex_encode()


func _ready():
	var password = "12324545"
	var hashed_password = hash_password(password)
	# Print translation: Encrypted password
	print("Senha criptografada: ", hashed_password)
```

Start the project
Look the console

--------------------------------------------------

@vinicius1770 A lingua oficial falada aqui é o inglês, tudo que você escrever aqui precisa ser em ingles para que todos possam entender. Use o google tradutor caso não saiba falar em inglês.

vinicius1770 The offcial language speak here is the english, everything you write here needs to be in english for everyone understand. Use the google translator if you don't know how to speak in english.

**Comment by matheusmdx** [comment]
@AThousandShips This issue can be closed, he just checked the error incorrectly


@vinicius1770 Não tem nenhum bug no `HMACContext`, na verdade o problema é um erro de logica no seu codigo:

```
func hash_password(password: String) -> String:
	var hmac_context = HMACContext.new()
	var key = PackedByteArray("secure_key".to_utf8_buffer())

	# HMACContext.start() vai retornar um número do enumerador Error 
	# (veja mais em: https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#enum-globalscope-error).
	# Esse numero vai ser 0 em caso de sucesso/nenhum erro ou algum outro numero relacionado a um erro
	# caso algo dê errado. Seu codigo está checando o erro de forma errada, if not quer dizer que se a condição
	# a seguir resultar em falso, o codigo dentro desse bloco vai ser executado, e 0 que é o numero retornado
	# em caso de sucesso vai ser considerado como falso, o que vai fazer seu codigo falhar
	#if not hmac_context.start(HashingContext.HASH_SHA256, key):


	# Para checar por errors corretamente você pode usar:

	# Se o erro retornado for diferente de OK = 0 = Sucesso
	if hmac_context.start(HashingContext.HASH_SHA256, key) != OK:

	# Ou

	# Se o erro é qualquer numero diferente de 0 (que vai ser tratado como verdadeiro)
	if hmac_context.start(HashingContext.HASH_SHA256, key):
		# Print translation: Failed to initialize the HMACContext.
   		 print("Falha ao inicializar o HMACContext.")
   		 return ""
```

--------------------------------------------

vinicius1770, There is no bug in `HMACContext`, actually the problem is a logic flaw in your code:

```
func hash_password(password: String) -> String:
	var hmac_context = HMACContext.new()
	var key = PackedByteArray("secure_key".to_utf8_buffer())

	# HMACContext.start() will return an number from the Error enum 
	# (see more in: https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#enum-globalscope-error).
	# This number will be 0 if the code executes without problem or any other number from the Error enum
	# if something go wrong. Your code is checking the error in the wrong way, `if not` means if the condition
	# evalutes to false, the code inside this block will be executed and 0, the number returned if no error happens,
	# will be evaluted to false, what makes your code fail.
	#if not hmac_context.start(HashingContext.HASH_SHA256, key):


	# To proper check the error you can do:

	# If the error received is different from OK = 0 = Success
	if hmac_context.start(HashingContext.HASH_SHA256, key) != OK:

	# Or

	# If the error received is a number different from 0 (which will be evaluted to true)
	if hmac_context.start(HashingContext.HASH_SHA256, key):
		# Print translation: Failed to initialize the HMACContext.
   		 print("Falha ao inicializar o HMACContext.")
   		 return ""
```
