### ISSUE TITLE
32-bit builds of Godot do not work with LLVM MinGW

### ISSUE THREAD

**Issue by MBCX** [godotengine/godot#100163]
### Tested versions

- Latest master (aa8d9b83f66488dbb2c9c918e9016ef80f821fb4)
- all versions after 4.4dev5

### System information

Godot v4.3.rc (322e93592) - Windows 10.0.26100 - GLES3 (Compatibility) - Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21921.1000) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 Threads)

### Issue description

Any attempt at building Godot for 32-bit Windows will _succeed_, but then actually trying to run will crash with this

```
================================================================
CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.4.dev.custom_build (55e55b4879f7ad89086aa26f2e53882cf85077f9)
Dumping the backtrace.
-- END OF BACKTRACE --
================================================================
```

And just stop. And for some bizarre reason, it _does not_ crash if its a dev build with debug symbols? (`dev_mode="yes" dev_build="yes"`)
~~I'm still not sure if this is a Godot issue or a compiler issue.~~ This is a Godot issue, see next comment.

### Steps to reproduce

1. Use the [latest](https://github.com/mstorsjo/llvm-mingw/releases/tag/20241203) LLVM MinGW (can be older too, I tested [20231128](https://github.com/mstorsjo/llvm-mingw/releases/tag/20231128)
2. Compile for windows with `arch="x86_32"`
3. Wait for compilation and try to run the executable.
4. (extra) re-compile with `dev_mode="yes" dev_build="yes"` and see how it does not crash.

### Minimal reproduction project (MRP)

Use this link to get [the builds](https://drive.google.com/drive/folders/1JScMvI4kSS9Bes-v7gVCgdHIF3ObBGKa?usp=sharing) and test it yourself:

**Comment by MBCX** [comment]
Did a git bisect, I confirm this is _a Godot bug_, and the culprit is #85167.

**Comment by akien-mga** [comment]
#99168 was merged yesterday and fixes some issues from #85167, could you check whether that fixes the 32-bit support too?

**Comment by MBCX** [comment]
Built latest master (a372214a4a047ccf63d23c4406337b30e55ff60b) with LLVM 19.1.5, and it ran just fine!

RandomShaper thought ahead then 👌!

I'll do a production build (but with `thin` lto) to see if the issue is truly fixed.

**Comment by MBCX** [comment]
Yes! it built and ran, and here's the final proof!

![Image](https://github.com/user-attachments/assets/48573f83-b15f-4016-ba52-e6e1196a4adb)

So, I can close this issue then as a false alarm from my part.👍

**Comment by akien-mga** [comment]
Awesome, thanks for confirming the fix!
