### ISSUE TITLE
Undoing creating point in Path2d curve causes freeze out

### ISSUE THREAD

**Issue by middlepattern** [godotengine/godot#100178]
### Tested versions

- Reproducible in 4.3 stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1050 Ti (NVIDIA; 30.0.14.9613) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

I'm still nailing down what causes the problem (edit: I think I found it, try steps to reproduce below), but 'undo' after adding a point (and moving the point) on a curve will freeze out acces and I'll get the following error message:

" core/object/undo_redo.cpp:471 - Condition "action_level > 0" is true. Returning: ""
  core/object/undo_redo.cpp:426 - Condition "action_level > 0" is true. Returning: false"

Only an engine restart will clear the error. This doesn't seem to be a problem on the first few add/delete of points, it seems to happen only when working with it for a while. This is a blank project with only a curve2d on it and playing around with points.

### Steps to reproduce

-Create a 2D scene and add a path2D
-Start drawing a random curve
-Add a point using add point from the tool bar, as you add it, drag the point around rapidly.
-Then 'undo'.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Sounds like:
* https://github.com/godotengine/godot/issues/96636
* https://github.com/godotengine/godot/issues/99578

Can you confirm in [`4.4.dev6`](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-6/)? This should have been fixed and a fix should be in a future 4.3.x version

**Comment by middlepattern** [comment]
Thanks, yes no issues in 4.4, thanks.
