### ISSUE TITLE
`Godot-4.4`, `FileSystem` with user-defined menu items shows error on selection

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#100190]
### Tested versions

- Reproducible since v4.4.dev3.mono.official [f4af8201b]

### System information

windows 11

### Issue description

I extend the standard filesystem context menu to show context based two menu items.
Since version `v4.4.dev3` there are popup an error when selecting the items.
`editor/filesystem_dock.cpp:2632 - Index selected_conversion_id = 0 is out of bounds ((int)cached_valid_conversion_targets.size() = 0).`

### Steps to reproduce

Here the code snipped I used to build the extended context menu.

The menu items are build dynamic when `about_to_popup` is emitted.

```
@tool
extends Control

var _context_menus := Dictionary()


func _init(context_menus: Array[GdUnitContextMenuItem]) -> void:
	set_name("EditorFileSystemContextMenuHandler")
	for menu in context_menus:
		_context_menus[menu.id] = menu
	var popup := _menu_popup()
	var file_tree := _file_tree()
	@warning_ignore("return_value_discarded")
	popup.about_to_popup.connect(on_context_menu_show.bind(popup, file_tree))
	@warning_ignore("return_value_discarded")
	popup.id_pressed.connect(on_context_menu_pressed.bind(file_tree))


func on_context_menu_show(context_menu: PopupMenu, file_tree: Tree) -> void:
	context_menu.add_separator()
	var current_index := context_menu.get_item_count()
	var selected_test_suites := collect_testsuites(_context_menus.values()[0] as GdUnitContextMenuItem, file_tree)

	for menu_id: int in _context_menus.keys():
		var menu_item: GdUnitContextMenuItem = _context_menus[menu_id]
		if selected_test_suites.size() != 0:
			context_menu.add_item(menu_item.name, menu_id)
			#context_menu.set_item_icon_modulate(current_index, Color.MEDIUM_PURPLE)
			context_menu.set_item_disabled(current_index, !menu_item.is_enabled(null))
			context_menu.set_item_icon(current_index, GdUnitUiTools.get_icon(menu_item.icon))
			current_index += 1
			prints("on_context_menu_show", current_index, menu_item.id, menu_item.name)


func on_context_menu_pressed(id: int, file_tree: Tree) -> void:
	prints("on_context_menu_pressed", id)
	if !_context_menus.has(id):
		return
	var menu_item: GdUnitContextMenuItem = _context_menus[id]
	var selected_test_suites := collect_testsuites(menu_item, file_tree)
	menu_item.execute([selected_test_suites])


func collect_testsuites(_menu_item: GdUnitContextMenuItem, file_tree: Tree) -> PackedStringArray:
	var file_system := EditorInterface.get_resource_filesystem()
	var selected_item := file_tree.get_selected()
	var selected_test_suites := PackedStringArray()

	while selected_item:
		var resource_path: String = selected_item.get_metadata(0)
		var file_type := file_system.get_file_type(resource_path)
		var is_dir := DirAccess.dir_exists_absolute(resource_path)
		if is_dir:
			@warning_ignore("return_value_discarded")
			selected_test_suites.append(resource_path)
		elif is_dir or file_type == "GDScript" or file_type == "CSharpScript":
			# find a performant way to check if the selected item a testsuite
			var resource := ResourceLoader.load(resource_path, "Script", ResourceLoader.CACHE_MODE_REUSE)
			if _menu_item.is_visible(resource):
				@warning_ignore("return_value_discarded")
				selected_test_suites.append(resource_path)
		selected_item = file_tree.get_next_selected(selected_item)
	return selected_test_suites


func _file_tree() -> Tree:
	return GdObjects.find_nodes_by_class(EditorInterface.get_file_system_dock(), "Tree", true)[-1]


func _menu_popup() -> PopupMenu:
	return GdObjects.find_nodes_by_class(EditorInterface.get_file_system_dock(), "PopupMenu")[-1]

```

The output on pressing `Run Testsuites` are:
![Image](https://github.com/user-attachments/assets/8529f0f1-4cea-473e-8e01-11625f9fd679)
```
on_context_menu_show 21 1000 Run Testsuites
on_context_menu_show 22 1001 Debug Testsuites
  editor/filesystem_dock.cpp:2632 - Index selected_conversion_id = 0 is out of bounds ((int)cached_valid_conversion_targets.size() = 0).
on_context_menu_pressed 1000
```

### Minimal reproduction project (MRP)

n/a

**Comment by MikeSchulze** [comment]
I guess it is introduced by https://github.com/godotengine/godot/commit/5901a7a3d13c29480cc61a9706cf456211af049a

**Comment by KoBeWi** [comment]
> Reproducible since v4.4.dev3.mono.official [https://github.com/godotengine/godot/commit/f4af8201bac157b9d47e336203d3e8a8ef729de2]

And what about dev6?
Can you provide a minimal project? I can't reproduce it.

**Comment by MikeSchulze** [comment]
same issue on dev6
![Image](https://github.com/user-attachments/assets/8616f56b-a295-4dad-95aa-f1a9c57a0304)

I will prepare a minimal project to reproduce.

**Comment by KoBeWi** [comment]
That's not how you add custom menu options. Use EditorContextMenuPlugin instead.
Your addon hacks into editor's popup menu, which is not guaranteed to work. If you still want to do it this way, use an ID that doesn't conflict with plugin options, e.g. 500.

**Comment by MikeSchulze** [comment]
> That's not how you add custom menu options. Use EditorContextMenuPlugin instead. Your addon hacks into editor's popup menu, which is not guaranteed to work. If you still want to do it this way, use an ID that doesn't conflict with plugin options, e.g. 500.

Thanks for your answer, I will take a look on `EditorContextMenuPlugin`.
The code was based on Godot3 and never updated to Godot4 API.

**Comment by MikeSchulze** [comment]
@KoBeWi using the suggested `EditorContextMenuPlugin` has some limitations.
There is no option to control the enable/disable state of a context menu item.

**Comment by KoBeWi** [comment]
Well as I said, you can use your old method, just change the used ID to avoid errors. 200-999 is a safe range. Note however that these values are not documented and can change at any moment.

> There is no option to control the enable/disable state of a context menu item.

We could add `disabled` argument to `add_context_` methods.

**Comment by MikeSchulze** [comment]
Ok fine, it will be supported in the upcoming versions 👍 
![Image](https://github.com/user-attachments/assets/d47bff10-253c-420a-b210-06e20db3d3ed)


And this new `EditorContextMenuPlugin` is only available on Godot 4.4.x, but I need to be downwards compatible.

Will result into custom implementation for 4,4.x and lower than 4.4 ;/
And use a hack to be downwards compatible, otherwise I have compiling issues in Godot 4.3

just Godot 4.4.x code
```
   _gd_filesystem_context_menu = EditorFileSystemContextMenuHandler.new()
   add_context_menu_plugin(EditorContextMenuPlugin.CONTEXT_SLOT_FILESYSTEM, _gd_filesystem_context_menu)
```


But need to convert to be downwards compatible and prevent compile issues.
```
# we need to define manually the slot id, to be downwards compatible
const CONTEXT_SLOT_FILESYSTEM = 1 # EditorContextMenuPlugin.CONTEXT_SLOT_FILESYSTEM

...

if Engine.get_version_info().hex >= 0x40400:
		var context_menue_script := GDScript.new()
		context_menue_script.source_code = FileAccess.get_file_as_string("res://addons/gdUnit4/src/ui/menu/EditorFileSystemContextMenuHandlerV44.gdx")
		context_menue_script.reload()
		_gd_filesystem_context_menu = context_menue_script.new()
		call_deferred("add_context_menu_plugin", CONTEXT_SLOT_FILESYSTEM, _gd_filesystem_context_menu)
```
I need to store the GDScript with a different extension to be not parsed at editor startup to prevent loading errors ;(

**Comment by KoBeWi** [comment]
Eh, I think it deserves a proposal. Adding a disabled state means you might want tooltips and whatever else PopupMenu supports.
Adding more arguments might become unwieldy, maybe it could be a new method, like `customize_last_item()`.

**Comment by MikeSchulze** [comment]
> Eh, I think it deserves a proposal. Adding a disabled state means you might want tooltips and whatever else PopupMenu supports. Adding more arguments might become unwieldy, maybe it could be a new method, like `customize_last_item()`.

Yes, like the `add_menu_shortcut`  should have `add_menu_state(<menu_item_name>, <callback(MenuItem)>)`

**Comment by MikeSchulze** [comment]
@KoBeWi I miss the support of adding context menu to the active script editor.
There is a `CONTEXT_SLOT_SCRIPT_EDITOR` but it adds the context menu, not to the script editor as the name suggest.

Using this command adds the context menu to the script panel and not to the script editor
`add_context_menu_plugin(EditorContextMenuPlugin.CONTEXT_SLOT_SCRIPT_EDITOR, _gd_scripteditor_context_menu)`

![Image](https://github.com/user-attachments/assets/a6e92776-bb42-454d-aef0-afcb81ef8a07)

Should i open a bug?

**Comment by KoBeWi** [comment]
#100556
