### ISSUE TITLE
Edit on Inspector an exported Dictionary.

### ISSUE THREAD

**Issue by gcivicodev** [godotengine/godot#10018]
**Operating system or device - Godot version:**
Windows 10 Pro - Godot 2.1.3.stable.official

**Issue description:**

When I export a Dictionary, the inspector show it but I can't edit it. 

**Steps to reproduce:**
I do this:
```
export(Dictionary) var Configuration = {
    Time = 1.5
}
```
But Inspector is not showing Dictionary keys:
![Inspector is not showing Dictionary keys](https://drive.google.com/uc?id=0B5TMH6WQzwybdmJmWWFRMTFXSHc)

If I use an Array export `export (Array) var Test`, the inspector show the Dictionary option to be selected: 
![Inspector is not showing Dictionary keys](https://drive.google.com/uc?id=0B5TMH6WQzwybU2h5SnlSVnNYclU)

But I can't set any key/value to the Dictionary:
![Inspector is not showing Dictionary keys](https://drive.google.com/uc?id=0B5TMH6WQzwybM1FuUnhsRVFydXM)

**Comment by akien-mga** [comment]
Fixed by #11940.
