### ISSUE TITLE
When removing a node with a skeleton, the console always writes an error (Godot 3.0 alpha 1)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#10012]
**Operating system or device - Godot version:**
Ubuntu 16.04, Godot 3.0 alpha 1

**Issue description:**
Hey. This error was in the old versions of the year, then it was fixed, now it appeared again.
When removing a node with a skeleton (game character), the console always writes an error.

**Steps to reproduce:**
Add a node with a skeleton,
get_node('test_obj').queue_free()

**Link to minimal example project:**
[Bug skeleton.zip](https://github.com/godotengine/godot/files/1190772/Bug.skeleton.zip)

**Comment by qbradq** [comment]
Confirmed

**Steps**
Open attached project
Run

**Result**
This is spammed in the console:

> ERROR: instance_remove_skeleton: Condition ' !skeleton ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5728.

**Build Information**
OS: OSX 10.12
Build Type: bin/godot.osx.tools.64
Commit: daad16b

**Comment by reduz** [comment]
fixed this, closing
