### ISSUE TITLE
Reimport 3D models doesn't update assets in opened scene

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#10017]
**Operating system or device - Godot version:**
Godot alpha1 3.0

Export asset from blender, then godot autoimports it as it should (tried with dae & obj). Instantiate object in scene. Modify object in blender & reexport. Godot apparently re-autoimports (cause I can see the progress bar for a split second). But object isn't updated in scene. Even if deleted, reimported (manually) and reinstantiated it still doesn't update it. You have to close the scene and reopen it for the object to update its properties. This should probably go in #8000?

**Comment by kubecz3k** [comment]
Confirming since other users were opening similar issues

**Comment by BrainBlasted** [comment]
I found that certain changes to the model do in fact change. For example, if you join meshes and re-export from blender, parts of the mesh may disappear until you reload. Another instance is if you change origin within blender, the origin of the mesh shifts incorrectly in Godot until the scene is re-opened.

**Comment by kubecz3k** [comment]
Would be nice if someone could check if it's still viable after: https://github.com/godotengine/godot/commit/33c1d25517050470689924c60414feaf295ce05f

**Comment by BrainBlasted** [comment]
Yes, this is still viable.

**Comment by TheConceptBoy** [comment]
2019, this is till an issue.

**Comment by frederico4d** [comment]
yeah is it pretty boring :(

**Comment by Calinou** [comment]
@frederico4d Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by WickedInsignia** [comment]
Still an issue in 2021. Not sure why the issue was closed. Exact same situation, and mesh will not update in Godot 3.3.2. Using GLTF exports from Blender into Godot and although reimport is recognized, mesh won't update. I have to delete the inherited scene and make a new one....very time consuming.
