### ISSUE TITLE
Focused LineEdit Passing Unhandled Key Releases

### ISSUE THREAD

**Issue by RobertBColton** [godotengine/godot#100118]
### Tested versions

Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 32.0.15.6070) - Intel(R) Core(TM) Ultra 7 155H (22 Threads)

### Issue description

LineEdit doesn't consume keyboard input when focused like it should.

I have a game with a HUD with LineEdit and a camera that moves with WASD in `_unhandled_input`. When I type into the LineEdit the camera still moves because the line edit is not consuming the released events, only the down/pressed events.

When an element like LineEdit is focused, it should probably just consume ALL keyboard input like in all other GUI frameworks.

### Steps to reproduce

1. Create a HUD with a focusable LineEdit
2. Create a game object/camera with WASD movement in `_unhandled_input`
3. Run game and type WASD into LineEdit, the player/camera will move on mouse released events

### Minimal reproduction project (MRP)

I gave steps above, it's very simple to repro.

**Comment by Sauermann** [comment]
Thank you for submitting this report. This has already been reported in #43701, so I'm going to close this issue as a duplicate and consolidate it with the other one. If you have additional information, I would like to invite you to continue the discussion there.
