### ISSUE TITLE
FileAccess store calls don't work after 4.4dev5 to 4.4.dev6 upgrade

### ISSUE THREAD

**Issue by danielglx** [godotengine/godot#100115]
### Tested versions

- Not Reproducible on godot_v4.4-dev5_mono_win64
- Reproducible on godot_v4.4-dev6_mono_win64

Simple calls to FileObject.Store functions in C# will throw the following error:

ERROR: System.MissingMethodException: Method not found: 'Boolean Godot.FileAccess.Store16(UInt16)'.

I also tried StoreVar(), same result. Otherwise, game works normally. Perhaps something got broken in the C# libraries when we made this change:

https://github.com/godotengine/godot/pull/78289

### System information

Windows 11 - Godot 4.4-dev6_mono_win64

### Issue description

Godot v4.4.dev5.mono - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 32.0.15.6094) - 12th Gen Intel(R) Core(TM) i7-12700K (20 threads)

### Steps to reproduce

1. Create an application in C# that involves the FileAccess call, for instance:

```
using var saveFile = FileAccess.Open(filename, FileAccess.ModeFlags.Write);
if (saveFile == null) {
    OS.Alert("Error saving game: " + saveFile.GetError());
} else {
    saveFile.Store16(0);
}
```

You will see a ERROR: System.MissingMethodException: Method not found: 'Boolean Godot.FileAccess.Store16(UInt16)'.

### Minimal reproduction project (MRP)

```
using var saveFile = FileAccess.Open(filename, FileAccess.ModeFlags.Write);
if (saveFile == null) {
    OS.Alert("Error saving game: " + saveFile.GetError());
} else {
    saveFile.Store16(0);
}
```

**Comment by bruvzg** [comment]
I can't reproduce it with a fresh project. The project probably have some assemblies from a previous version, and need full solution rebuild. As far as I know, there's no way to provide compatibility methods.

**Comment by danielglx** [comment]
I had done that, but that wasn't the problem. I forgot to update my launch.json on vscode so it was pointing to an older Godot version for building the project. Interestingly, this was the only issue that happened due to this oversight - the game otherwise works. I'm sorry for the noise.
