### ISSUE TITLE
The project crashes when the CSG becomes very thin

### ISSUE THREAD

**Issue by viidinc** [godotengine/godot#100201]
### Tested versions

4.4 dev6 .NET

### System information

Window 10, AMD ryzen 7 4700U

### Issue description

When you create a very thin CSG editor it crashes

### Steps to reproduce

1. Create CSG node
2. Set the size of one of the sides to 0

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting. This is a duplicate of a previously reported issue. We prefer to track issues in one place, so I am consolidating this with:
* https://github.com/godotengine/godot/issues/100095

See the linked issue for details. If you think it may not be the same and something was missed, please comment here and this issue can be reopened.
