### ISSUE TITLE
Can't debug Clang build on Windows anymore

### ISSUE THREAD

**Issue by AeioMuch** [godotengine/godot#100268]
### Tested versions

v4.4.dev.custom_build [cf038deb1]

### System information

Godot v4.4.dev (cf038deb1) - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6636) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 threads)

### Issue description

Can't debug clang build on Windows compiled with `scons use_mingw=yes use_llvm=yes dev_build=yes`. Will not allow debug anymore with lldb-dap.
This is caused by https://github.com/godotengine/godot/pull/100207 cc @bruvzg

I guess if `platform=windows` but `use_llvm=yes` we should still use `-gdwarf-4` or something like this ? Or am I missing a package ?

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
> I guess if use_llvm=yes we should still use -gdwarf-4 or something like this ?

No, it was changed to dwarf-5 for libbacktrace, it does not matter which compiler was used.

clang should default to dwarf-5 since llvm-14, it's possible you are using old version of lldb.

**Comment by AeioMuch** [comment]
I use https://packages.msys2.org/groups/mingw-w64-clang-x86_64-toolchain which provided lldb version 19.1.4-1
I tried with https://github.com/mstorsjo/llvm-mingw and that was the same.

Using drawrf-4 it make it work again, what should I do then ?

**Comment by AeioMuch** [comment]
It may be because of lldb-dap https://github.com/mfussenegger/nvim-dap/issues/186#issuecomment-852382434

**Comment by bruvzg** [comment]
Tested various configs:

---

## `drawf-4` symbols produces by `gcc`:

- Doesn't work with `libbacktrace`.

## `drawf-5` symbols produces by `gcc`:

- Work in `gdb`:
![Image](https://github.com/user-attachments/assets/60e2ed5a-0774-469d-9008-ae015ddefdfa)
- Kinda work in `lldb`, but seems to have some issues, it's spamming a lot of `Failed to extract range list table at offset` error and does not show source lines (function names are shown).
- Work with `libbacktrace`.

---

## `drawf-5` symbols produced by `clang`:

- Doesn't work in `gdb`.
- Work in the same half-broken way in `lldb`.
- Doesn't work with `libbacktrace`.

---

## `drawf-4` symbols produced by `clang`:

- Work in `gdb`.
- Work in `lldb`, no error spam lines are show correctly:
![Image](https://github.com/user-attachments/assets/7a9a3071-cac0-49d2-9248-e2c72027c762)
- Work with `libbacktrace`.

---

So we should switch `clang` builds back to `drawf-4`.

**Comment by AeioMuch** [comment]
Thank you for your tests!

**Comment by akien-mga** [comment]
> Kinda work in `lldb`, but seems to have some issues, it's spamming a lot of `Failed to extract range list table at offset` error and does not show source lines (function names are shown).

Sounds like this from the [GCC 11 release notes](https://gcc.gnu.org/gcc-11/changes.html):

> To take full advantage of DWARF version 5 GCC needs to be built against binutils version 2.35.2 or higher. When GCC is built against earlier versions of binutils GCC will still emit DWARF version 5 for most debuginfo data, but will generate version 4 debug line tables (even when explicitly given `-gdwarf-5`). 

There must be a mismatch between the debuginfo data and the debug line tables versions.

Looking at libbacktrace's `dwarf.c` is seems to have code to support earlier dwarf versions than 5. Maybe we could revert back to dwarf-4 for all platforms and just find how to use libbacktrace to process dwarf-4 data explicitly?
