### ISSUE TITLE
ImmediateGeometry Node doesnt color the vertices

### ISSUE THREAD

**Issue by scayze** [godotengine/godot#10024]
**Operating system or device - Godot version:**
Ubuntu 16.04 x86_64. 
Godot version: 2.1.4 and below. Not tested on 3.0 alpha
GPU: rx480 4GB
Driver: AMDGPU-PRO 17.30

**Issue description:**
Drawing colored vertices's with the ImmediateGeometry Node doesn't work properly. set_color() doesn't seem to affect the output at all, it will always appear pitch-black,
Edit: It does work in tool mode in the editor though, and setting the material to 'unshaded' makes the color appear in the game aswell

**Steps to reproduce:**
- New Scene with an ImmediateGeometry Node
- Add a Script and some code that draw some vertices eg.

```
func _ready():
        begin(Mesh.PRIMITIVE_TRIANGLES)
	set_color(Color(1,0,0))
	add_vertex(get_translation() + Vector3(-1.0,-1.0, 1.0)) 
	add_vertex(get_translation() + Vector3(-1.0, 1.0, 1.0)) 
	add_vertex(get_translation() + Vector3(-1.0,-1.0,-1.0)) 
	end()
```
**Link to minimal example project:**
[Minimal.zip](https://github.com/godotengine/godot/files/1191628/Minimal.zip)

**Comment by eon-s** [comment]
If your material has "use color array" enabled, it will be painted the color you assigned to the mesh vertices.

**Comment by scayze** [comment]
Oh. Thanks! My bad then.
It might be usefull to add that information to the docs though.

**Comment by scayze** [comment]
So Apparently it still doesn't quite work yet. Well, it does in the editor. ImmediateGeometry draws colored vertexes using GDscript and the "tool" keyword. But in-game it appears pitch-black

**Comment by eon-s** [comment]
Do you have a light on the scene? 
Normally the editor has a "default light" active but when running you need a real one.

**Comment by scayze** [comment]
yes i do. A Mesh right beside it is visible and well.

**Comment by eon-s** [comment]
@scayze that reminds me of another issue with AMDGPU (not PRO), regular meshes work fine?

**Comment by scayze** [comment]
Yeah. Regular meshes work just fine. I Also just tested it on a Windows System, and the issue remained. It doesnt seem to be OS/Driver related.

**Comment by RandomShaper** [comment]
@scayze, does that other mesh have unshaded, emission, or the like? I'm asking because for me the project works and I can see the red color as long as I add a light that hits the mesh.

![imagen](https://user-images.githubusercontent.com/11797174/28950248-9b1ed5f6-78c2-11e7-8938-9c3679cfba52.png)

Well, I've also added a camera, but that shouldn't matter.

**Comment by scayze** [comment]
Ok turns my light source didnt reach the geometry.  stupid me. Turns out the Mesh was lighted because of Ambient light. Which apperently doesnt affect stuff drawn using the ImmediateGeometry Node. Im not sure wether this is a bug or not.

**Comment by akien-mga** [comment]
I guess this needs at least some more details in the documentation?

**Comment by bojidar-bg** [comment]
Ambient light not affecting ImmediateGeometry sounds like a bug to me.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
