### ISSUE TITLE
Viewport with ViewportTexture causes OpenGL error messages

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#10020]
**Operating system or device - Godot version:**
Linux 64 bit (Xubuntu 17.04) - Godot 3.0 alpha1

**Issue description:**
When I create a Viewport with 3D elements and display the Viewport through a ViewportTexture, the engine spams the debugger with the following error:

> GL ERROR: Source: OpenGL	Type: Undefined behaviorID: 131222	Severity: Medium	Message: Program undefined behavior warning: Sampler object 0 is bound to non-depth texture 0, yet it is used with a program that uses a shadow sampler. This is undefined behavior.

**Steps to reproduce:**
Create a 3D viewport and a Sprite or TextureRect with a ViewportTexture. Start the scene and watch the debug output.

**Link to minimal example project:**
[ViewportTexture.zip](https://github.com/godotengine/godot/files/1191456/ViewportTexture.zip)

**Comment by akien-mga** [comment]
What's your GPU and drivers?

**Comment by ProbDenis** [comment]
GeForce GTX 750 Ti with proprietary Nvidia drivers (version 384.47)

**Comment by reduz** [comment]
This was fixed some weeks ago, also minimal example project works, so safely closing this
