### ISSUE TITLE
CSGCombiner3D crashes Godot when made visible in the inspector

### ISSUE THREAD

**Issue by Wiechciu** [godotengine/godot#100261]
### Tested versions

- Reproducible in 4.4dev6 only
- Not reproducible in 4.4dev5, 4.3stable

### System information

Windows 10, GeForce GTX 1660 Super, AMD Ryzen 5 2600

### Issue description

When unhiding a complex CSGCombiner3D node that is a child of another CSGCombiner3D, Godot crashes. See attached the scene that causes the crash on my end every time - usually the node called "Window" (which is the most complex) will cause a crash when made visible.
[wall_window_test.zip](https://github.com/user-attachments/files/18087521/wall_window_test.zip)
I tried recording, but now my project can't be opened at all in 4.4dev6, only in 4.4dev5. Even with this scene removed from the project I can't open it.
I was able to record the following short video, where it crashed on unhiding a different node, not even the one I got issues with before.
https://github.com/user-attachments/assets/da5ae778-c903-4510-9f80-2dc2a726d577

This potentially could be related to the recent changes in CSG implemented with https://github.com/godotengine/godot/pull/94321

### Steps to reproduce

1. Make 3 CSGCombiner3D nodes.
2. Inside the 2 of these nodes, create a couple of complex CSG shape nodes.
3. Turn the visibility off for the original CSGCombiner3D parent node.
4. Put these 2 CSGCombiner3D nodes as children of the third CSGCombiner3D node.
5. Turn visibility on for the children CSGCombiner3D nodes. It will crash Godot.
I'm not sure if this will exactly reproduce the crash every time, but at least that's how I got to that point in my case with this scene:
[wall_window_test.zip](https://github.com/user-attachments/files/18087521/wall_window_test.zip)

### Minimal reproduction project (MRP)

I can't open any project in 4.4dev6 anymore, it crashes every time. Can't recreate it as a project.

**Comment by fire** [comment]
Can you try https://nightly.link/godotengine/godot/workflows/runner/master?preview and see if it still fails?

There is a crash bug with csg that is in dev6 and not master.

**Comment by Wiechciu** [comment]
> Can you try https://nightly.link/godotengine/godot/workflows/runner/master?preview and see if it still fails?
> 
> A crash bug with CSG is in dev6 and not master with the camera and previews.

It doesn't crash, I can't replicate the issue with this build.
