### ISSUE TITLE
Mesh upgrade tool triggers error and doesn't restart.

### ISSUE THREAD

**Issue by tdaven** [godotengine/godot#100232]
### Tested versions

Current master, a372214a4a047ccf63d23c4406337b30e55ff60b in my case.

### System information

Godot v4.4.dev (a372214a4) - Fedora Linux 41 (Workstation Edition) on Wayland - Wayland display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) - 13th Gen Intel(R) Core(TM) i7-13700K (24 threads)

### Issue description

```
ERROR: Error calling deferred method: 'EditorNode::EditorNode::restart_editor': Method expected 1 arguments, but called with 0.
   at: _call_function (core/object/message_queue.cpp:222)
```
Presumably introduced by 2470eedd614c7a902c8ff0d6d013da014f4267bb when an argument was added.  Though there is a default value which should be false, that seems to not work through the Callable.  Easy enough to just pass false to match the default.  I'll open a PR shortly.  

### Steps to reproduce

Open new project.  Try run Project -> Tools -> Upgrade Mesh Surfaces

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, this was already reported in:
* https://github.com/godotengine/godot/issues/99571

Closing this and tracking this in that report
