### ISSUE TITLE
ViewportTexture doesn't work if Viewport is below the texture node in tree order.

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#10022]
**Operating system or device - Godot version:**
Linux 64 bit (Xubuntu 17.04) - Godot 3.0 alpha1

**Issue description:**
Same setup as in #10020. We have a 3D Viewport and a TextureRect showing the ViewportTexture like this:

![tree_order](https://user-images.githubusercontent.com/15891496/28839316-81b4c100-76f3-11e7-81f6-af88097eed06.png)

The left setup works, the right setup doesn't show the texture.
This is probably an expected behaviour in that the Viewport must be updated before the ViewportTexture - but if it's not a bug it should at least be documented.

**Comment by reduz** [comment]
I fixed this some weeks ago, so closing
