### ISSUE TITLE
up to 100% GPU usage when VSync is disabled

### ISSUE THREAD

**Issue by MatthiasBae** [godotengine/godot#100254]
### Tested versions

Reproducable in 4.4 dev 4 and dev 6

### System information

Godot v4.4.dev6.mono - Windows 10.0.26100 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 32.0.15.6636) - 13th Gen Intel(R) Core(TM) i9-13900KF (32 threads)

### Issue description

Disabling the VSync option leads to 100% GPU usage in my project. 

With VSync
![Image](https://github.com/user-attachments/assets/8bc64e32-367e-49ca-9a58-a08ff730939a)

Without VSync
![Image](https://github.com/user-attachments/assets/d8ff92a0-a911-4f00-bd0a-2cef515a8bf8)

Also a completely new project causes up to 50%-70% usage
![Image](https://github.com/user-attachments/assets/6397233a-3f4a-46ce-9e8f-2ca6bc400b18)

### Steps to reproduce

- Create a project
- Disable VSync
- Run the project

### Minimal reproduction project (MRP)

-

**Comment by mrjustaguy** [comment]
This is expected. It's drawing as many frames as the cpu and gpu possibly can.

**Comment by clayjohn** [comment]
As mrjustaguys says, this is exactly what should happen when vsync is disabled. The purpose of vsync is both to synchronize when you display frames to the monitor to avoid tearing _and_ to ensure you aren't rendering more frames than you can display in order to keep GPU utilization down.
