### ISSUE TITLE
area2d's wrong work about monitorable,monitoring and area_enter when overlap

### ISSUE THREAD

**Issue by wQAQw1** [godotengine/godot#100311]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 31.0.15.2887) - 13th Gen Intel(R) Core(TM) i7-13700H (20 Threads)

### Issue description

两个area2d节点（称为a和b），使得a可以检测b，a的area_enter信号绑定函数后，在a和b重叠时，将b的monitorable关闭再开启不会触发a的函数（而将a的monitoring关闭再开启则会触发函数），此外对b的monitoring每一次修改（设置为true或者false）均会触发a的函数。

我希望能够对area_enter判断进行修改使得b的monitorable关闭再开启能够触发a的函数，且monitoring的修改不会触发（是他们符合描述）

### Steps to reproduce

1.在调试中开启“显示碰撞区域”，按住“D”使得两个区域重叠/碰撞，此时将会触发函数，输出“A IS COLLIDE!!!”
2.再 远程 中对Node2D-B的monitorable和monitoring进行变动

可以看到修改monitorable不会触发函数，而monitoring的每次修改都会触发

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/18111187/test.zip)

**Comment by AThousandShips** [comment]
The official language of these channels is English, please make any reports or comments in English, if you do not know English please use some translation software or ask for help.

**Comment by Sauermann** [comment]
Closing as duplicate / superseded by #100346
