### ISSUE TITLE
Play project window closes without warning due to missing dependency.

### ISSUE THREAD

**Issue by phyffer** [godotengine/godot#10035]
**Operating system or device - Godot version:**
Linux Mint (Ubuntu) x64
For Godot v3.0 build 18e23ad

**Issue description:**
Upon playing the project, if there is a missing dependency (renamed material), the project play window will simply start up then exit.  **No errors are shown in the output nor the debugger.**

I found that this error is caused by a broken dependency.

**Steps to reproduce:**
1.) Import your model
2.) Create and save your spacial material.
3.) Rename that spacial material.
4.) Play the project, then no luck :(
**NOTE: This bug will not appear when you close and reopen your project.**

*Perhaps this bug can be fixed from tackling issue https://github.com/godotengine/godot/issues/9685?*

**Link to minimal example project:**
[10035.tar.gz](https://github.com/godotengine/godot/files/1192721/10035.tar.gz)

**Comment by reduz** [comment]
i cant really reproduce and the example project seems to work..  #9685 is fixed so please try again

**Comment by akien-mga** [comment]
No answer and by now I think we would have had more comments/duplicate issues if the bug was still valid, so I'll assume it's fixed. Please comment if you can still reproduce and we'll reopen the issue.
