### ISSUE TITLE
Can't access resource details on ScriptEditorDebugger

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#10030]
**Ubuntu 17.04 - Godot version: 2.1.4 beta 2**

**Issue description:**
Trying to access details of resources brings you back to the node display on the resource.

![resourcedatadebuggerbug](https://user-images.githubusercontent.com/10215987/28850694-9f44f360-76f4-11e7-80b0-1408ed6e8916.gif)

**Steps to reproduce:**
Use the Remote inspector and try to get details on resources used by nodes on the Inspector.

**Comment by akien-mga** [comment]
CC @Geequlim

**Comment by Geequlim** [comment]
Strange bug. I'll give it a check when I'm free.

**Comment by Geequlim** [comment]
Should be fixed with #10044

**Comment by eon-s** [comment]
Fixed
