### ISSUE TITLE
Editor completely freezes when switching scenes

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#10033]
**Operating system or device - Godot version:** Linux Mint XFCE 18.2 (x64_86), commit ee3530b
**Issue description:** The editor completely freezes when switching scenes.
**Steps to reproduce:** Open the scene and try to open the child node-scene or try to open several scenes.

**Comment by ISylvox** [comment]
I believe https://github.com/godotengine/godot/commit/66a7763b0ef242f2c2a93b5e974e57bbd793408a was not the problem, as it's only touching gdnative module. From my test, this issue was triggered before this commit https://github.com/godotengine/godot/commit/ee3530bdc29c5015f276e3c44a68fbf4db5daf6e

**Comment by djrm** [comment]
im unable to reproduce this, any particular scene, or hardware/driver description.

**Comment by kubecz3k** [comment]
I can't reproduce this, can you upload reproduction project? Thanks.

**Comment by toby3d** [comment]
@kubecz3k In one of the projects, one of the scenes simply refuses to open (and switch to it) due to the presence of AudioStream2D inside the node. In another project, trying to switch to the node **only with the character's skeleton** (sprites + points) the editor has been freeze: https://youtu.be/591nUFenc9M

**Comment by toby3d** [comment]
It seems that the problem has disappeared.
