### ISSUE TITLE
Cannot build template on Windows

### ISSUE THREAD

**Issue by fredlim** [godotengine/godot#1003]
gd_script.cpp
c:\users\flim\documents\github\godot\modules\gdscript\gd_script.cpp(1759) : error C4716: 'GDScript::_update_exports' : must return a value
scons: *** [modules\gdscript\gd_script.windows.opt.64.obj] Error 2
scons: building terminated because of errors.

**Comment by fredlim** [comment]
It seems not working now after sync today.

LINK : fatal error LNK1181: cannot open input file 'tools\tool.windows.opt.64.lib'
scons: *** [bin\godot.windows.opt.64.exe] Error 1181
scons: building terminated because of errors.

**Comment by UsernameIsAReservedWord** [comment]
same here.

normal compilation using :

    scons p=windows bits=64 -j 4

is OK.

But :

    scons p=windows tools=no target=release bits=64

ends up with the same fatal error copypasted by @fredlim

**Comment by akien-mga** [comment]
This issue is quite old and there haven't been new comments in a while, so I'll assume it has been fixed (at least we do have nightly builds of the 64bit release export templates, so I guess building them works).
