### ISSUE TITLE
OGV video files no longer supported on Godot 3.0

### ISSUE THREAD

**Issue by pakchano** [godotengine/godot#10031]
**Operating system or device - Godot version:**
- Device: MacBook Pro (Retina, 15-inch, Mid 2014)
- OS: macOS Sierra 10.12.5 (16F73)
- Godot version: v3.0 alpha

**Issue description:**

Exported OGV Video file but it doesn't recognize the format anymore.

```python
var stream = preload("res://video.ogv")
```
throws an error: `Parser Error: Can't preload resource at path: res://video.ogv`

Please help!

I've used the version 2.1.4.beta.2017.06.25 and works well there.

![ogv-no-longer-supported-godot3](https://user-images.githubusercontent.com/9617583/28852397-c390a956-76f6-11e7-9c71-e65d00f1dcbb.jpg)

**Steps to reproduce:**
1. Add OGV video file to the `res://` directory
2. Preload it from a script as described above.

**Link to minimal example project:**

- Video Example for Testing: [video.ogv.zip (2.5mb)](https://github.com/godotengine/godot/files/1192271/video.ogv.zip)

**Comment by argylelabcoat** [comment]
The core video playback mechanism is still functional. Playback of audio is not currently working.

**Comment by reduz** [comment]
@argylelabcoat any progress on this? worst case I can give you a hand on getting audio to work again

**Comment by argylelabcoat** [comment]
I got so far as the ring-buffer passing audio to the server but it seemed to overwrite existing audio faster than playback speed resulting in what sounded like short 1/4s blips of audio from across the video timeline condensed into a short window. (somewhat like fast-forwarding a dvd with the audio still enabled) Followed by the video finishing playing in silence.

Sadly I haven't had an abundance of time to investigate this further.

**Comment by argylelabcoat** [comment]
My current status can be summed up with this pull req: https://github.com/godotengine/godot/pull/11278

**Comment by dodgyville** [comment]
I have the same problem with godot3 tip on linux

`Parser Error: Can't preload resource at path: res://video.ogv`

**Comment by HummusSamurai** [comment]
Fixed by https://github.com/godotengine/godot/pull/12014 ?

**Comment by akien-mga** [comment]
Yes.
