### ISSUE TITLE
Type inference fails on Array.map()

### ISSUE THREAD

**Issue by hk0i** [godotengine/godot#100377]
### Tested versions

1. Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - macOS 14.2.1 - Vulkan (Mobile) - integrated Apple M3 Max - Apple M3 Max (16 Threads)

### Issue description

1. Reproducible in v4.3.stable.official [77dcf97d8]
2. Similar issue to https://github.com/godotengine/godot/issues/73309 which was closed as **Not Planned**

## Expected Behavior

1. `Array.map()` should be able to infer return types
2. At the very least `Array.map()` should provide a way that typed arrays can be returned

## Actual Behavior:

1. Mapping an array of `Vector2i` after summing another `Vector2i` returns an array of no type
2. Error is output:

> Trying to return an array of type "Array" where expected return type is "Array[Vector2i]".

## Sample Code

```gdscript
const NEIGHBOR_OFFSETS: Array[Vector2i] = [
	Vector2i(0, -1),
	Vector2i(1, -1),
	Vector2i(1, 0),
	Vector2i(1, 1),
	Vector2i(0, 1),
	Vector2i(-1, 1),
	Vector2i(-1, 0),
	Vector2i(-1, -1),
]


func surrounding_cells(map_coordinates: Vector2i) -> Array[Vector2i]:
	return NEIGHBOR_OFFSETS.map(
		func(coordinate):
			return coordinate + map_coordinates
	)
```

I also tried specifying the return type in the callback method itself:

```gdscript
func surrounding_cells(map_coordinates: Vector2i) -> Array[Vector2i]:
	return NEIGHBOR_OFFSETS.map(
		func(coordinate) -> Vector2i:
			return coordinate + map_coordinates
	)
```

this also fails with the same message

## Alternatives / What *does* work?

1. Removing types completely seems to work:

```gdscript
func surrounding_cells(map_coordinates: Vector2i):
	return NEIGHBOR_OFFSETS.map(
		func(coordinate):
			return coordinate + map_coordinates
	)
```

### Minimal reproduction project (MRP)

1. See code snippet
2. If this is not enough I will create and attach a sample project later today

**Comment by AThousandShips** [comment]
Thank you for reporting, this is already tracked in:
* https://github.com/godotengine/godot/issues/72566

Closing as we prefer to have things tracked in one place.

**Comment by hk0i** [comment]
Thank you! sorry for the duplicate I only found the close ticket when I searched.
