### ISSUE TITLE
Add handling of touch events in _gui_input_event

### ISSUE THREAD

**Issue by MednauN** [godotengine/godot#10039]
Right now `_gui_input_event` function of `Viewport` is processing mouse events, but ignores touch events (`InputEventScreenTouch` and `InputEventScreenDrag`). As effect of that, there are two problems:

1. `_gui_input(event)` doesn't receive touch events, which makes difficult to create controls that can use multi-touch. Sure, you can use `_input(event)` as workaround, but it leaves some problems like "input fighting" between overlapping controls.

2. `mouse_filter` property of controls doesn't work for touch events. As a result, events "fall through" all controls and go into `_unhandled_input(event)`. And this may be bad if you're trying to handle touch events inside the world (like, for pinch-zoom).

I'm not sure if this was made this way intentionally, but to me it makes more sense if both mouse events and touch events are handled the same way.

So, I propose to add processing of `InputEventScreenTouch` and `InputEventScreenDrag` inside `_gui_input_event` similarly to mouse events.

Well, actually, I already implemented this feature in my local fork of repository, but I'm unsure if I should create PR or leave it like that, since it changes behavior of input system.

PS. I use master branch of engine, so it's all about upcoming Godot 3.0

**Comment by eon-s** [comment]
Related #9981 

As a user, I don't see a reason for Controls to ignore touch while CollisionObjects don't, but maybe there is one; also there is a special TouchScreenButton node that is Node2D instead of Control which is weird.
