### ISSUE TITLE
Changing syntax highlight setting does not update text highlighting

### ISSUE THREAD

**Issue by Lunarexxy** [godotengine/godot#100431]
### Tested versions

Reproducible in v4.4.dev6.official [1f47e4c4e]
Reproducible in v4.4.dev2.official [97ef3c837]
Not reproducible in v4.4.dev1.official [28a72fa43]
Not reproducible in Godot 4.3

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.6590) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

A very minor regression. When a text or script file is open, changing the syntax highlighting setting under `Edit -> Syntax Highlighter -> [any setting]` does not cause the text to use the new syntax highlighting, until some change in the text is made or the file is closed and reopened.

May be considered a duplicate of #98367, though that one is related to changing editor theme, while this one is about changing a script editor setting. Feel free to close if tracking one issue is easier.

Possibly caused by #92865.

### Steps to reproduce

Create a text or script file and write something in it.
Open it in the built-in script editor.
Change Edit -> Syntax Highlighter to any option.
Notice no immediate change to syntax highlighting.
(if you edit the text, it will properly update)

### Minimal reproduction project (MRP)

This project includes two text files, one .txt and one .gd, with mostly identical contents. File type doesn't seem to matter, though.

[syntax_highlight_bug.zip](https://github.com/user-attachments/files/18140642/syntax_highlight_bug.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.4.dev 9e6098432.
