### ISSUE TITLE
Undeferred calls in Area(2d/3d) that should be deferred give wrong information output to debugger error.

### ISSUE THREAD

**Issue by Dharhix** [godotengine/godot#100421]
### Tested versions

This applies to Godot 4.3.Stable and possibly more recent versions.

### System information

Unimportant

### Issue description

If user try to change states: monitorable and monitoring in Area2D or Area3D undeferred when it should be, Godot will output an error with the wrong information.

If code is called undeferred (like this) when it should be:
```gdscript
$SomeArea2d.monitoring = false
```

Godot might output with this error:
`"Function blocked during in/out signal. Use set_deferred(\"monitoring\", true/false)."`
Proper error message should be:
`"Function blocked during in/out signal. Use set_deferred(\"set_monitoring\", true/false)."`

This also applies to `monitorable`.
Both the above also applie to area_3d

Line 426 in area_2d.cpp says:

```C++
ERR_FAIL_COND_MSG(locked, "Function blocked during in/out signal. Use set_deferred(\"monitoring\", true/false).");
```

instead it should say:
```C++
ERR_FAIL_COND_MSG(locked, "Function blocked during in/out signal. Use set_deferred(\"set_monitoring\", true/false).");
```
Same with line 445 in area_2d.cpp:

Proper message should be ("set_monitorable" instead of "monitorable"):
```C++
ERR_FAIL_COND_MSG(locked || (is_inside_tree() && PhysicsServer2D::get_singleton()->is_flushing_queries()), "Function blocked during in/out signal. Use set_deferred(\"set_monitorable\", true/false).");
```

It is the same exact issue in area_3d.cpp.

String in lines for monitoring and monitorable should be prepended with "set_" (as above). They are at 379 & 535 in area_3d.cpp.

### Steps to reproduce

No need.

### Minimal reproduction project (MRP)

Unnecessary.

**Comment by AThousandShips** [comment]
This is not true, `set_deferred` use the property name, not the setter, what are you basing this on? Please upload a test project to show how you are solving this with these calls

**Comment by Dharhix** [comment]
It's the ERROR MESSAGE in the line numbers I wrotoe. It says to use
"monitoring" in the deferred call, but it should say to use
"set_monitoring".

**Comment by AThousandShips** [comment]
It doesn't say `call_deferred` it says `set_deferred`, there's no `set_monitoring` property, so this would not work

**Comment by matheusmdx** [comment]
@Dharhix You're mixing the `set_monitoring` function with the `set_deferred`. `set_monitoring` is the setter function to change the `monitoring` property and exclusive from `Area2D` node and you just pass the new value (ex: `set_monitoring(false)`), but this one is not deferred so doesn't work for this case. `set_deferred` is a function from the `Object` class that allows to you change a property in the idle time, in this case you need to specifity the PROPERTY first and after the new value (ex: `set_deferred("monitoring", false)`).

**Comment by AThousandShips** [comment]
Thank you for rephrasing what I said

**Comment by Dharhix** [comment]
I was very tired, very snappy and I'm sorry for that.

For an unknown reason I used call_deferred instead of set_deferred. Hence this whole non-thing thing. My bad.

Closed.
