### ISSUE TITLE
Text selection in editors and text fields

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#1004]
Please fix, very annoying ;)

* Place cursor, hold shift, click somewhere else: Should select all text between. Doesnt work properly. Often forgets starting point. Behaves strangely when text is already selected. Should add/subtract from that selection, instad starts a new one.
* Holding control: Jumping or selecting (in combination with shift) whole words. Doesn't always work.

Thanks!

**Comment by reduz** [comment]
I just fixed adding and subtracting from selection, the second item i'm not exactly sure how it's supposed to work, could you add a little more detail?

**Comment by ScyDev** [comment]
If you go to any textfield or textarea of your choosing (not Godot, another program, like your browser) you can try this: 
Hold Ctrl and then left or right arrow. This jumps words.
Hold Ctrl and Shift and then left or right arrow. This jumps and selects/de-selects words.

This is standard keyboard text editing behaviour in pretty much every programm I know.

And should also work for up and down arrow, accross lines. However then it selects to the same cursor position on the next line, not respecting word boundaries.

**Comment by reduz** [comment]
i'm trying what you mention in Godot editor window and it seems to work as
you describe

**Comment by ScyDev** [comment]
But not in text fields. For example node names in tree or file names when saving, etc.

**Comment by reduz** [comment]
oh line edit, i didn't think of it, ok leave this open, will make sure to
fix it then

**Comment by akien-mga** [comment]
See also #284 for further text editing feature requests.

**Comment by akien-mga** [comment]
@neikeq IIRC you were the one to do quite some usability improvements to text selection, could you check if this issue is still valid?

**Comment by neikeq** [comment]
@akien-mga If we are talking about _LineEdit_, then yes, it's still valid. Both points should be easy to implement. Gonna check today.

**Comment by vnen** [comment]
@neikeq any luck with this?

**Comment by neikeq** [comment]
I completely forgot I self-assigned myself to this. I'll try to make a PR today.

**Comment by neikeq** [comment]
Wow, I remember when I checked this in March <kbd>Shift+Click</kbd> selection was working, weirdly but working. Now it doesn't even seem to work and I don't see any recent changes to it...

**Comment by neikeq** [comment]
The first point is done. I am confused about the second point. Jumping words is not implemented at all in LineEdit, but OP says:

> Doesn't _**always**_ work.

Was this point only related only to TextEdit, or do you want word jumping in LineEdit too?
