### ISSUE TITLE
FileDialog file_selected signal does not work when exported on Android

### ISSUE THREAD

**Issue by ArtinGaming** [godotengine/godot#100493]
### Tested versions

- Reproducible in 4.4.dev4

### System information

Android 13 - Godot 4.4 dev 4 Motorola G 5g 2022

### Issue description

My issue is when I use the Native FileDialog and select any file on my phone. The signal that checks if you selected any files never gets called. I doubled check to see if the signal is connected and it is, and on my windows it works perfectly fine. 

The signal I'm talking about:
![Image](https://github.com/user-attachments/assets/bb481f56-0c31-4d46-828d-ae0fca0e31e3)

My code:
![Image](https://github.com/user-attachments/assets/554dcc1d-9ae5-4a30-bb9d-8b0d8340efcf)

### Steps to reproduce

1. Create a FileDialog
2. Check the "Use Native Dialog" to be on
3. Connect the file_selected signal to your script
4. Print the "path" parameter
5. Make sure "File Mode" is on "Open any"
6. Lastly, "Access" is ony FileSystem

That's it when you export your project to android and select any file it will not print anything.   

### Minimal reproduction project (MRP)
(https://github.com/ArtinGaming/Godot-4.4.dev4-FileDialog-Issue)

**Comment by syntaxerror247** [comment]
Make sure you have enabled Storage permissions in export settings and requested it in your app using `OS.request_permissions()`.
From your screenshot, it looks like you are trying to open images, you should enable `READ_MEDIA_IMAGES`.

**Comment by ArtinGaming** [comment]
Thanks a lot! That fixed it! Here is the code I used `func _ready(): await OS.request_permissions()` Have a great day!
