### ISSUE TITLE
Empty popup window in Node / Signal view

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#100479]
### Tested versions

Reproducible in:  
- v4.4.dev6.mono.official [1f47e4c4e]
- v4.4.dev5.mono.official [9e6098432]
- v4.4.dev4.mono.official [36e6207bb]

NOT reproducible in:  
- v4.4.dev3.mono.official [f4af8201b]

### System information

Godot v4.4.dev6.mono - Windows 10.0.19045 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 threads)

### Issue description

You get an empty popup window when hovering in Node / Signal view's empty area:
![Image](https://github.com/user-attachments/assets/a9930a0e-897a-4fcc-a7b6-d28f3015e449)
(The green outline is caused by the Window's Step Recorder.)

### Steps to reproduce

1. Open Node view
2. Move mouse to the empty area at the bottom of the view
3. Wait for the empty popup to pop up

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting! This was reported before and solved, please see:
* https://github.com/godotengine/godot/issues/99945
