### ISSUE TITLE
Collision shape gizmos do not update after changing node transform

### ISSUE THREAD

**Issue by ApachOC** [godotengine/godot#10049]
**Operating system or device - Godot version:**
Tested 3.0 alpha snapshot, as well as latest build.

PC:
*  GPU: Nvidia GTX 660
*  CPU: Intel i5 3570k at 4.2GHz
*  RAM: 12GB DDR3
*  OS: Win 8.1 Embedded x64

Laptop:
*  GPU: Intel HD4000
*  CPU: Intel i5 3250M
*  RAM: 8GB DDR3
*  OS: Fedora 25

I have the issue on both my configs.

**Issue description:**
While moving collision shapes around I have noticed, that the gizmo does not update its transform accordingly. I have observed the issue with every type of shape resource, and it also manifests if you change the transform of any one of parent nodes.

In order to fix the issue, I have to select some other node, and then select the collision shape node again.
I have not noticed any issues with other gizmos.

**Steps to reproduce:**
1. Create Collision Shape node and assign it a new shape
1. Try to move/rotate/scale said node, or its parent node
1. Observe the issue

**Example:**

![test](https://user-images.githubusercontent.com/26769454/28886574-46a1fd72-77ba-11e7-8f9c-c005a3498fec.gif)

Please note, that the perceived movement of the gizmo is caused by moving cursor over shape handles, which causes the gizmo to update its transform.

**Comment by kubecz3k** [comment]
Hello, I think it's a duplicate of https://github.com/godotengine/godot/issues/8910

**Comment by ApachOC** [comment]
Yes, yes it is.
Sorry, I did not see that issue.
Closing now.

**Comment by kubecz3k** [comment]
@ApachOC No problem, but good work with git and description. I think you should add that gif and maybe couple of words from here to #8910

**Comment by kubecz3k** [comment]
Especially that note to the gif, I dont think anyone noticed this before: _Please note, that the perceived movement of the gizmo is caused by moving cursor over shape handles, which causes the gizmo to update its transform._
