### ISSUE TITLE
Using the rendering modes: Mobile and Forward, Godot crashes

### ISSUE THREAD

**Issue by NishimotoDev** [godotengine/godot#100461]
### Tested versions

v4.4.dev2.official [97ef3c837]
and previous versions of this version of godot 4

### System information

Godot v4.4.dev2 - Android - OpenGL ES 3 (Compatibility) - Adreno (TM) 540 -  (8 Threads)

### Issue description

Godot crashes when I use the other rendering modes, I use the compatibility mode as it is the only one that works for me.

### Steps to reproduce

https://streamable.com/fcnt9p

### Minimal reproduction project (MRP)

https://streamable.com/1p4md2?src=player-page-share

[bug-sobs.zip](https://github.com/user-attachments/files/18147559/bug-sobs.zip)

**Comment by mrjustaguy** [comment]
That is expected, you only support OpenGL, whereas Mobile and Forward+ Renderers use Vulkan or DX12
