### ISSUE TITLE
Cant disable this error "causing RenderingServer synchronizations on every frame. This significantly affects performance."

### ISSUE THREAD

**Issue by PeterMarques** [godotengine/godot#100411]
> The error message in question no longer exists in 4.3.beta1 (likely as the result of refactoring such as #84976). The issue should be (indirectly) fixed there already; can someone test?
> 
> 
> 
> The warning message will be replaced with this one: https://github.com/godotengine/godot/blob/e2fc6d38cb240ea23bd5700514f8a8ce7011e89c/servers/rendering/rendering_server_default.h#L122 

 _Originally posted by @clayjohn in [#83046](https://github.com/godotengine/godot/issues/83046#issuecomment-2179543314)_

I need to iterate over several viewports every frame:

for key in vpdic.keys():
		var ima = vpdic[key].get_texture().get_image()

So this error naturaly triggers;

How to disable as its buid-up slows and clutter the logger.

(Only happens if rendering/driver/threads/thread_model is set to multi-threaded)

**Comment by clayjohn** [comment]
In this case you should disable the multi threaded thread model. The warning is correctly showing you that you are synchronizing the rendering thread with the main thread every frame, so you get no benefit from multithreading.
