### ISSUE TITLE
move function does not update on_floor on_ceiling on_wall

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#10047]
**Operating system or device - Godot version:**

Any- Godot 3.0

**Issue description:**

**Happened:** In KinematicBody2D the function move does not set variables for querying the is_on_floor(), is_on_wall(), is_on ceiling.
**Expected:** Both move and move_and_slide should work with is is_on_floor(), is_on_wall(), is_on ceiling.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by djrm** [comment]
the problem is that the move function does not have enough parameters, like the max floor slope, so it cant distinguish between them. but i think move is equivalent to move_and_slide with bounces = 1.

**Comment by QbieShay** [comment]
I think that should be considered making a setter for floor, slope, and using these properties for both move and move and slide functions.
So the code would be something like: 
set_floor_properties(normal,slope)
move(speed*delta)
if(is_on_floor()): 
 #do stuff

**Comment by reduz** [comment]
I thought about this for a while, whether it should be moved to a KinematicCharacter3D function and, honestly, I think it's probably good as is. I'm sure eventually you will be able to find more complete implementations on the asset library.
