### ISSUE TITLE
Inconsistent behaviour between InputEvent.is_action* methods

### ISSUE THREAD

**Issue by em-s-h** [godotengine/godot#100495]
### Tested versions

- Reproducible in: Godot v4.3.stable

### System information

Godot v4.3.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000 - Wayland - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 Threads)

### Issue description

In the [documentation](https://docs.godotengine.org/en/stable/classes/class_inputevent.html#class-inputevent-method-is-action) page for `InputEvent` it says that `is_action*` methods will ignore input modifiers if `exact_match` is `false`.

The methods `is_action()` and `is_action_released()` follow this description, but `is_action_pressed()` does not ignore input modifiers even if the value of `exact_match` is `false`.

I'm not sure if this is a mistake in the documentation or an error in the implementation of these methods.

### Steps to reproduce

- Create an action with an input modifier, Ex.: 'Ctrl+s';
- Paste this code in a script:
```gdscript
func _input(event: InputEvent) -> void:
    prints("")
    if event.is_action("special_action"):
        prints("According to 'is_action' Ctrl+s has been pressed/released.")

    if event.is_action_pressed("special_action"):
        prints("According to 'is_action_pressed' Ctrl+s has been pressed.")

    if event.is_action_released("special_action"):
        prints("According to 'is_action_released' Ctrl+s has been released.")
```
- Press 's', in the console it'll show that `is_action()` and `is_action_released()` returned true;
- Press 'Ctrl+s', in the console it'll show the previous messages plus the `is_action_pressed()` message

### Minimal reproduction project (MRP)

N/A

**Comment by Rindbee** [comment]
See https://github.com/godotengine/godot/issues/57943#issuecomment-1073191623.

**Comment by em-s-h** [comment]
I see, I was confused since they all have the same description, yet `is_match_pressed()` behaved differently.
