### ISSUE TITLE
Text looks bad in sub-windows on Android

### ISSUE THREAD

**Issue by Barugon** [godotengine/godot#100537]
### Tested versions

v4.3.stable.official [77dcf97d8]
v4.4.dev6.official [1f47e4c4e]

### System information

Godot v4.3.stable - Fedora Linux 41 (Workstation Edition) - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 7800 XT (RADV NAVI32) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

I'm writing a GUI app using Godot. When I run the app on Android, I have to call `set_content_scale_factor` on the main window in order to not have the GUI elements look microscopic (in this case, the scale factor is 3.0). The text of UI items in the main window and the titles of sub-windows look great but the UI text of items in the sub-windows looks terrible.

![Image](https://github.com/user-attachments/assets/7686d193-1046-48cb-a827-7f493f6bf1f6)

I can use multi-channel SDF, which gives better results, but the text is still rendered at a lower resolution and scaled up for sub-windows, so it looks blurry.

![Image](https://github.com/user-attachments/assets/16a7408f-cd8f-48bb-871b-4e4873bad9ed)

### Steps to reproduce

See description above.

### Minimal reproduction project (MRP)

Project is available [here](https://github.com/Barugon/aviate).

**Comment by fire** [comment]
Are you aware of the Godot Engine MSDF feature?  https://docs.godotengine.org/en/stable/tutorials/ui/gui_using_fonts.html#msdf-font-rendering

**Comment by Barugon** [comment]
> Are you aware of the Godot Engine MSDF feature? https://docs.godotengine.org/en/stable/tutorials/ui/gui_using_fonts.html#msdf-font-rendering

MSDF is enabled in the project settings (second example image).

> It seems like the entire output is not hi-dpi.

Hi-dpi setting has no effect.

**Comment by Barugon** [comment]
Re-enabled hi-DPI in the project settings. Same result.

**Comment by syntaxerror247** [comment]
@Barugon, does this issue occur only on Android?

**Comment by Barugon** [comment]
> [@Barugon](https://github.com/Barugon), does this issue occur only on Android?

Any scaling greater than 1.0. Here I called `set_content_scale_factor` on the main window with 2.0 on Linux desktop (Fedora 41).

![Image](https://github.com/user-attachments/assets/363ffd3f-c3b4-4f30-bf19-c798f9472a10)

**Comment by Summersay415** [comment]
May be fixed by https://github.com/godotengine/godot/pull/97745

**Comment by Barugon** [comment]
> May be fixed by [#97745](https://github.com/godotengine/godot/pull/97745)

That change looks like it didn't make it into v4.4-dev7 but I built from the main github branch and it appears to be fixed. Closing.
