### ISSUE TITLE
Not starts on Debian

### ISSUE THREAD

**Issue by al-shayda** [godotengine/godot#100507]
### Tested versions

- Reproducible in Godot v. 4.3
- Not Reproducible in Godot v. 3.6

### System information

Debian 12 (bookworm), nouveau video driver, old NVidia card

### Issue description

# Bug Found in Godot v.4.3 on Debian (Short)
Godot Project Manager on Debian starts OK. 
Godot Editor crashes.

# Description of a Bug (Full)
i downloaded binaries with 4.3, i'm on Debian. i do not have llvm toolchain. 
godot starts, opens Project Manager, i choose to edit project, Godot crashes. 
The following messages from a bug, can be clearly seen in console:  
ERROR: Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.
   at: propagate_notification (scene/main/node.cpp:2422)
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.3.stable.official (77dcf97d82cbfe4e4615475fa52ca03da645dbd8)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3c050) [0x7f014a383050] (??:0)
[2] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --
### Steps to reproduce

install Debian bookworm
run godot 4.3
click on create new project
it'll crash, and thus reproduce bug

### Minimal reproduction project (MRP)

n/a can't create project

**Comment by bruvzg** [comment]
Most likely this Mesa bug - https://gitlab.freedesktop.org/mesa/mesa/-/issues/5699 (should be fixed in Mesa 24).

> Godot Project Manager on Debian starts OK.
> Godot Editor crashes.

Project Manager always use OpenGL. Editor is using whatever you have selected in the project settings (Vulkan by default).

**Comment by akien-mga** [comment]
Sadly nouveau is also notoriously broken, especially in older mesa versions. I'm afraid you're out of luck for running Godot on this device with Debian 12. Using a more recent distro or finding out a way to update Mesa on Debian might give better results.
