### ISSUE TITLE
[Suggestion] "Export Selected Node to GDScript" Feature! 

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#10052]
Cannot believe I just finally thought of this!

Basically, the option ("Export Node to GDScript") could be listed in the context menu when right clicking a node:
![](https://i.gyazo.com/e94c39167865dd6f07de8847f6275b04.png)

This would generate the GDScript, then show it in a selectable text Popup menu. 

![untitled-1](https://user-images.githubusercontent.com/10387670/28899529-780d2dce-77a0-11e7-949b-9b863fd2b5be.png)

For example, the c_player -> label is a marker for the minimap. I have to generate that node dynamically when players join the world anyway. So instead of just copying all those inspector field values (texture region for sprite, etc) manually, the developer can just click on "Export Node to GDScript", then use the code his `AddPlayerToMiniMap` method. 

You might be wondering... well just export it as a scene and instance it. You're not wrong... however I still think this would be something really unique & useful! :D :D

**Comment by Dillybob92** [comment]
Eh, fuck it lol. Too many issues I think the devs better off to work on tbh :X I'm just being silly hehe.

**Comment by Hinsbart** [comment]
You could make this as a plugin and put it in the AssetLib :)
