### ISSUE TITLE
Failed to build on Windows

### ISSUE THREAD

**Issue by JiahuiCai** [godotengine/godot#10053]
**Operating system or device - Godot version:**
Windows 10 Pro x64
Godot 3.0
**Issue description:**

trying to build godot source on windows with scons -j10 platform=windows.
get the error:
c:\z_development\godot_source\drivers\gles3\rasterizer_storage_gles3.h(39): fatal error C1083: Cannot open include file: 'shaders/canvas.glsl.gen.h': No such file or directory
scons: *** [platform\windows\os_windows.windows.tools.32.obj] Error 2
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\exception(366): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
scons: building terminated because of errors.

**Steps to reproduce:**
cloned godot source,
install py2.7 32bit, pywin32 32bit, scons
install vs2017 with desktop c++ component
add python folder to PATH
run developer command prompt
run  command scons -j10 platform=windows

**Link to minimal example project:**

**Comment by marcelofg55** [comment]
I had this too today, moving the `#include "core/variant.h"` before `#include "core/io/json.h"` on modules/gdnative/godot/dictionary.cpp fixed the issue for me.

**Comment by JiahuiCai** [comment]
@marcelofg55 
Yes it worked, thank you for the quick reply, but I keep getting other errors like " Cannot open include file: 'certs_compressed.gen.h': No such file or directory"

**Comment by JiahuiCai** [comment]
@marcelofg55 After running the scons script multiple times, I managed to get a working exe file. Thank you again.

**Comment by viktor-ferenczi** [comment]
**Random build failures do happen on Windows with 64 bit native build with current head [68f2774] of master.** 

Tested both with -j1 and -j16 multiple times.
The point of failure is often different, so these runs are not reproducible.
Running scons multiple times eventually results in a successful build.

**I suggest reopening this ticket, since this has not been fixed.**

**Comment by viktor-ferenczi** [comment]
It seems to be a duplicate of [#5042](https://github.com/godotengine/godot/issues/5042)
