### ISSUE TITLE
iOS lighting issues

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#10057]
**Operating system or device - Godot version:**
Tested on iOS 11 (beta4), Godot master build 2nd of August 

**Issue description:**
Lighting goes all weird, probably something to do with ambient lighting or something. Problem goes away when you use an HDR for the background so using say the material tester scene rendering is spot on.

See for instance my primitive test scene:
![img_6438](https://user-images.githubusercontent.com/1945449/28902274-410bc5f0-7841-11e7-9b37-eef7a1b06e37.jpg)

It almost looks like the normal vector is used for colors, note how upward facing surfaces are greenish while vertical faces are red/blue?

It should look something like this:
![primitives in godot 3](https://user-images.githubusercontent.com/1945449/28902328-8bb0ca7e-7841-11e7-82bd-75307a50ad1e.png)

**Steps to reproduce:**
Easiest and best way to reproduce:
- create a new scene
- add a cube, set the material to a simple white material
- add a camera and a directional light, you'll see in the godot editor it all renders just fine there
- export to iOS and run, you'll see the cube is all purple and red

**Comment by BastiaanOlij** [comment]
@reduz any idea?

**Comment by henkz1** [comment]
I think this might have been fixed in https://github.com/godotengine/godot/commit/e192c1a7d3414129fb9e41d91bc7bbbe66e58f14 ?

**Comment by BastiaanOlij** [comment]
Yes this was fixed some time back
