### ISSUE TITLE
MenuBar node's get_menu_title method is confusing

### ISSUE THREAD

**Issue by jan-kapoli** [godotengine/godot#100660]
### Tested versions

Godot version: 4.3.stable

### System information

Debian 12 Bookworm

### Issue description

Given a scene with a `MenuBar` node and a `PopupMenu` child node the method `get_menu_title` returns the child node's _name_. This is confusing, since a `PopupMenu` has a property called _title_ (inherited from the `Window` node).

This is also problematic, because when running the project, the menu items' labels reflect their respective node's name, not title. Thus it is impossible to create the following menu bar from the editor:
[File] [Edit] [View] [View]
since names have to be unique.
It is generally undesired for node names to have an effect on the game.

### Steps to reproduce

Create a scene with a `MenuBar` node as root. Create a `PopupMenu` child node and name it "NAME". In the editor (under the window category) set the `title` property to "TITLE".

Run `get_menu_title(0)` on the root node. Notice the result is "NAME" instead of the expected "TITLE".

### Minimal reproduction project (MRP)

[Minimal reproduction project.zip](https://github.com/user-attachments/files/18214030/Minimal.reproduction.project.zip)

**Comment by bruvzg** [comment]
> Thus it is impossible to create the following menu bar from the editor

You can use `set_menu_title` method to set custom titles.

But since `title` exist in all `Window`s and is not doing anything for the borderless `PopupMenu` window, we probably should support it as a menu title as well.
