### ISSUE TITLE
ui_accept source InputEvent passed to _unhandled_input when button has focus

### ISSUE THREAD

**Issue by glenfletcher** [godotengine/godot#100630]
### Tested versions

Godot v4.3.stable (77dcf97d8)

### System information

Godot v4.3.stable (77dcf97d8) - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Wed Dec 11 22:24:04 UTC 2024 - X11 - GLES3 (Compatibility) - AMD Radeon RX Vega (radeonsi, vega10, LLVM 18.1.8, DRM 3.54, 6.6.65-1-MANJARO) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

When a scene contains one or more button controls and one of these button controls has focus, and the button is pressed using one of the Input Events (tested with `InputEventKey` and `InputEventJoypadButton`) bound to the `ui_accept` input action. The script attached to the scene containing the button receives these inputs as Input Events in _unhandled_input.

While the documentation is unclear on this, saying that `_unhandled_input` doesn't receive input events handled by the GUI. My interpretation of this is that Input Events bound to an input action which is handled should not be received by `_unhandled_input` according to the documentation.

Similar behaviour occurs with the tab and arrow keys used by the UI for focus selection when there are multiple controls. However, I found myself uncertain on what I would consider the correct behaviour in the context of a game engine here and concluded that it is likely context-dependent, and possibly should be a node-specific setting.

### Steps to reproduce

- Create a new Godot project
- Create a Control scene
- attach a script to the scene
- add the function `_unhandled_input(event)` and print the event
- add one or more buttons to the scene
- run the scene
- use the mouse to select a button to acquire focus
- use the keyboard to navigate between and select (`ui_accept`) different buttons

output will include the events bound to `ui_accept` and those used to navigate the focused button

this can also be done using a game pad however a button needs to be bound to the `ui_accept` action for this test.

### Minimal reproduction project (MRP)

See steps to reproduce

**Comment by Sauermann** [comment]
Thank you for this issue. This has already been reported in #44314. I would like to consolidate your report with the other one and close it.
