### ISSUE TITLE
Crash in editor when zooming/rotating

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#10064]
**Operating system or device - Godot version:**
Win 7 x64
Godot 2.1.4 beta (both June and August builds)

**Issue description:**
Godot engine crashes when zooming/rotating the editor camera.

The project attached is the exact same project I'm using in 2.1.3 stable so this is a regression.

**Steps to reproduce:**
1) Load the project
2) open a 3d scene (Main.scn or Navigation.tscn), try to move the camera around e.g to see the road bend from up close.
3) Crash (sometimes takes more movements, but generally trying to zoom far out is a nearly sure bet)

Note: I am using modo navigation, pan is shift and zoom is ctrl.

**Link to minimal example project:**
https://www.dropbox.com/s/jb5izxr90i4zfa1/FreeRoamRacer%20-%20Kopia%20beta.zip?dl=0

(Had to dropbox because GH complains about the file being too big)

**Comment by marcelofg55** [comment]
Do you know where it crashes? (a crash log / stacktrace would be great)

**Comment by Zireael07** [comment]
I wish I did, I can't get gdb to cooperate with Windows/Godot...

**Comment by Zireael07** [comment]
Checked and the same crash happens with the June 2.1.4 beta. So it's something done between 2.1.3 and June.

**Comment by Zireael07** [comment]
Updated the issue description to reflect the fact that it's present in both 2.1.4 betas.

**Comment by marcelofg55** [comment]
I think I found the problem here, could you try this branch that includes the fix: https://github.com/marcelofg55/godot/tree/fixeditor_crash

**Comment by Zireael07** [comment]
@marcelofg55: The compile process is the same as for master/2.1 branches? (not sure because I haven't compiled in quite some time)

I'll give this a try but I'm not sure how quickly I'll be able to compile and check.

**Comment by marcelofg55** [comment]
Yes, the compile process is the same, I could attach an .exe if you thats easier

**Comment by Zireael07** [comment]
Yes that would be welcome (an 64 bit exe is preferable but obviously I can also run the 32 bit one) :)

**Comment by marcelofg55** [comment]
Here you go: https://www.dropbox.com/s/ubgdstavst7kni9/godot.windows.tools.32.exe?dl=0

**Comment by Zireael07** [comment]
@marcelofg55: I tried to make it crash (rotating/zooming at once, zooming far out etc.) and it didn't! Looks like it's fixed, thank you so much? PR please?

**Comment by akien-mga** [comment]
Fixed by #10125.
