### ISSUE TITLE
Weird PointLight2D LightOccluder2D behavior and crash

### ISSUE THREAD

**Issue by pmoosi** [godotengine/godot#100664]
### Tested versions

- Reproducible in v4.4-dev7 and current master [89001f9]
- Not reproducible in v4.4-dev6

### System information

Godot v4.4.dev7 - Ubuntu 24.04.1 LTS 24.04 on Wayland - X11 display driver, Multi-window, 3 monitors - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 5800H with Radeon Graphics (16 threads)

### Issue description

I encountered a strange problem where some `LightOccluder2D create shadow while others don't. It seems to be somehow related to the polygon. If I change the shape of the polygon it switches between occluding and not occluding. Interestingly, this does not seem to be true for all occluders and I'm not sure when it is the case.

Additionally, I'm also getting a crash on some scenes with 

```
ERROR: FATAL: Index p_index = 16 is out of bounds (count = 16).
   at: operator[] (./core/templates/local_vector.h:177)
```

when creating a new `LightOccluder2D`.

Maybe somebody can have a look at the mrp and make more sense of it.

### Steps to reproduce

The mrp contains two scenes. `light1.tscn` and `light2.tsnc` have 2 `LightOccluder2D` where one is creating a shadow and the other is not. Try changing the shape of the polygons.  One always creates shadows while the other does only sometimes.
Adding a new `LightOccluder2D` in `light1.tscn` crashes the editor. 

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/18214889/mrp.zip)

**Comment by pmoosi** [comment]
I also found that when creating a polygon for the light occluder the warning that a polygon is required is shown until the scene is reloaded. Maybe it's related?

**Comment by clayjohn** [comment]
> I also found that when creating a polygon for the light occluder the warning that a polygon is required is shown until the scene is reloaded. Maybe it's related?

No, this is a problem with how the editor warnings work. 

I tested the MRP with dev 7 and a version of master from 2 days ago. I could reproduce the shadows not appearing issue with dev 7, but not with the 2 day old master. I couldn't reproduce the crash in either version. 

I'm building latest master now to test further and will update if I find anything

**Comment by pmoosi** [comment]
After some testing it seems to be related to the polygons position relative to the the occluder node.
When the relative position is greater then the lights radius, it won't occlude. 

In the mrp the circular light has a radius of 128, If all occluder points are greater than that, it won't occlude.

**Comment by clayjohn** [comment]
@pmoosi Thank you! That aligns with my finding so far. I suspected the problem lied in how we cull occluders relative to lights. I think I already have a solution as well. Just need to test it out

**Comment by clayjohn** [comment]
Thank you for the report! https://github.com/godotengine/godot/pull/100677 should fix both bugs reported here and it comes with a nice little speed boost as well!

**Comment by pmoosi** [comment]
Very nice, thank you. I just tested it and #100677 fixes both the occluding and the crash in my projects.
