### ISSUE TITLE
Not possible to drag and drop textures into Material slots (Godot 3.0)

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#10061]
**Operating system or device - Godot version:**
Windows 10, Godot 3.0, alpha 1

**Issue description:**
Drag and drop a texture from file system to a material slot is not allowed.
![godot3draganddrop](https://user-images.githubusercontent.com/24936603/28913992-4dc00308-783a-11e7-831c-b60683d5822f.jpg)

**Steps to reproduce:**
Try drag and drop a texture from file system to a texture slot in a material

**Comment by Corruptinator** [comment]
I happen to notice this as well.

**Comment by akien-mga** [comment]
Same bug as #8676?
