### ISSUE TITLE
When monitorable property of Area2D is true, the area does not detect when monitorable property of second overlapping Area2D is toggled

### ISSUE THREAD

**Issue by AaronWizard** [godotengine/godot#100687]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - macOS 15.1.1 - GLES3 (Compatibility) - Intel(R) UHD Graphics 630 - Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 Threads)

### Issue description

I have an Area2D - lets call it "Hurtbox" - set to detect other Area2Ds on a given layer - lets call this other Area2D "Hitbox".

When the `monitorable` property of "Hurtbox" is false, it is able to detect collisions with "Hitbox" even when the `monitorable` property of "Hitbox" is toggled while the two Area2Ds are overlapping.

However when the `monitorable` property of "Hurtbox" is true, it is only able to detect collisions with "Hitbox" if the `monitorable` property of "Hitbox" is set to true before the two Area2Ds collide. I would expect this to work the same as when the `monitorable` property of "Hurtbox" is false.

https://github.com/user-attachments/assets/caa3873c-300b-406a-b934-6ffa3be5149e

Additionally when the `monitorable` property of both "Hurtbox" and "Hitbox" are true and the two are overlapping, if the `monitorable` property of "Hitbox" is set to false this is not detected by "Hurtbox" until it is moved to no longer overlap.

This may be related to #100346, #71489, and #17238.

### Steps to reproduce

1. Create an Area2D. Set its `monitoring` to true, `monitorable` to true, and Bit 0 of `collision_mask` to 1. Connect methods to its `area_entered` and `area_exited` signals to detect collisions. This is the "Hurtbox".
2. Create a second Area2D. Set its `monitoring` to false, `monitorable` to false, and Bit 0 of `collision_layer` to 1. _Do not_ connect anything to its `area_entered` nor `area_exited` signals. This is the "Hitbox".
3. Have the two Area2Ds overlap.
4. While the game is running, set `monitoring` of "Hitbox" to true.

Expected: "Hurtbox" detects the collision.
Actual: "Hurtbox" does not detect the collision.

### Minimal reproduction project (MRP)

[collisiontest.zip](https://github.com/user-attachments/files/18216961/collisiontest.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting! We prefer to have one report tracking each issue so I am closing this and consolidating in:
* https://github.com/godotengine/godot/issues/71489

Please see there for more details
