### ISSUE TITLE
Editor setting `editors/grid_map/editor_side` is no longer used and has no effect

### ISSUE THREAD

**Issue by spoxii** [godotengine/godot#100699]
### Tested versions

- Reproducible in 4.4-dev.7
- Affects all versions after https://github.com/godotengine/godot/pull/96922 was merged

### System information

Godot 4.4 dev 7 - all platforms

### Issue description

PR https://github.com/godotengine/godot/pull/96922 moved the MeshLibrary palette for GridMaps to the bottom panel.
However, you can still find the `editors/grid_map/editor_side` option in the editor settings. 

This option no longer has an effect and can be removed. 
![Image](https://github.com/user-attachments/assets/9b3d3a3d-3c4d-4f69-b350-88ca99638274)

When looking at the diff of the PR, you can see that all occurrences of this editor setting were removed. It is not used anywhere else, so it's a pointless option now.

### Steps to reproduce

In Godot 4.4 Dev 7, navigate to the Editor Settings and look for the "Editor Side" option.

- Editor > Editor Settings 
- Editors > Grid Map > Editor Side

### Minimal reproduction project (MRP)

N/A

**Comment by Nodragem** [comment]
I still see it on Godot v4.4 master

![Image](https://github.com/user-attachments/assets/a5e57fae-32c5-4c3e-9274-0ad7f2145026)

While I can see it was deleted in the code (editor/editor_settings.cpp):

![Image](https://github.com/user-attachments/assets/ad581239-8964-45b7-9cf6-fbeb1ac7d5b8)

Not sure why this is happening?

Also note that `minimum palette width` could also be deleted?
