### ISSUE TITLE
Exported variables are reseted to default upon saving

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10063]
**Operating system or device - Godot version:**
Linux, aef974e7a8577f857be8cf89f02844575d0839bb

**Issue description:**
Some types of exported variables seems to be reseted when saving scene. I can tell for sure that's a case for exported int types. (including enum style int hints(int, "Val1", "Val2")).
![exportedintreset](https://user-images.githubusercontent.com/6129594/28914272-5f7d8c7c-783b-11e7-99aa-1f20d7522e77.gif)

**Steps to reproduce:**
1. Download sample project
2. Open "res://Issues/ExportedVariablesSaveIssue/ExportedVariablesSaveIssue.tscn"
3. Change values in inspector
4. Save scene with ctrl+s or from File menu.
5. Observe that changes made in exported int values are gone.

**Link to minimal example project:**
[ExportIntResetIssue.zip](https://github.com/godotengine/godot/files/1196633/ExportIntResetIssue.zip)

**Comment by kubecz3k** [comment]
From my tests it seems 0b11062d9360080f6861c51097c551b4ea485550 is the first bad commit 
cc @Geequlim

**Comment by Geequlim** [comment]
I can't believe 0b11062d9360080f6861c51097c551b4ea485550 can cause this issue

**Comment by kubecz3k** [comment]
well I can recheck tomorrow, but git bisection tells me it's that one...

**Comment by Geequlim** [comment]
@kubecz3k But it does!
The `round` operation may break the enumeration convertion?
But why I change the `int()` to `rand()` is that I do input `3` but the value is `2.99999999999999997` then I got a `2` value while input integers.
So I have no idea with that :(

**Comment by bojidar-bg** [comment]
int(round(..)) maybe?

**Comment by kubecz3k** [comment]
@Geequlim  @bojidar-bg you are right, it's working with `int`. I created quick pr with quick fix already.

**Comment by akien-mga** [comment]
Fixed by 475e8b28.
