### ISSUE TITLE
Godot.NET.Sdk Nuget package out of date

### ISSUE THREAD

**Issue by warent** [godotengine/godot#100623]
### Tested versions

Godot v4.4.dev7.mono

### System information

- Windows 11 (build 22631) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 32.0.15.5613) - 12th Gen Intel(R) Core(TM) i7-12650H (16 threads)

### Issue description

The Nuget package hasn't been updated for Dev7 yet, so us plebs can't use it

![Image](https://github.com/user-attachments/assets/01251f20-bf45-4034-b4d8-ef245712fd1f)

### Steps to reproduce

https://www.nuget.org/packages/Godot.NET.Sdk/4.4.0-dev.6
https://www.nuget.org/packages/Godot.NET.Sdk/4.4.0-dev.7

![Image](https://github.com/user-attachments/assets/aa15f191-fb47-4e09-b189-fb5271218c54)

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
There was an issue uploading the dev7 NuGet package yesterday. It should now be fixed.
