### ISSUE TITLE
Android AAB export results in no file being created

### ISSUE THREAD

**Issue by Bryce-Dixon** [godotengine/godot#100689]
### Tested versions

I've tried exporting the same project with the same settings on the same machine with various recent engine builds:
- 4.3 stable works as expected
- 4.4 dev1 and 4.4 dev2 work as expected
- 4.4 dev3 onward produce no errors (Gradle window reports "all tasks successful"), but no "game.aab" file is created

### System information

Godot v4.4.dev7 - Linux Mint 22 (Wilma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (nvidia; 535.183.01) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Trying to perform an Android AAB export (for the Google Play store) on recent development builds does not result in an exported file being created despite no errors being reported.

### Steps to reproduce

1. Create a new project
2. [Ensure computer is prepared for an Android export](https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html)
3. Install Android Build Template
4. Select Project -> Export... from the Main Menu Bar
5. Select Add... -> Android
6. Check "Use Gradle Build" and switch Export Format to "Export AAB"
7. Click "Export Project..."
8. Set file name to "game.aab" and wait for build to complete (Debug/Release setting does not matter)

On 4.4 dev2 and earlier "game.aab" will be created, but on 4.4 dev3 and later "game.aab" will not be created despite no errors being reported.

### Minimal reproduction project (MRP)

Attached MRP has no Android build template; that must be installed with Project -> Install Android Build Template... before attempting to export.
[no-aab-mrp.zip](https://github.com/user-attachments/files/18217697/no-aab-mrp.zip)

**Comment by matheusmdx** [comment]
Bisected to #88803, @raulsntos

![Image](https://github.com/user-attachments/assets/672fe8bc-b47a-4de2-a69c-32521d0e9051)
