### ISSUE TITLE
Linked GradientTexture2d properties for sprite2Ds created by copy and paste.

### ISSUE THREAD

**Issue by atmosfaere** [godotengine/godot#100705]
### Tested versions

4.3 Stable

### System information

Windows 10 - 4.3 stable - compatibility - Nvidia rtx 3090

### Issue description

Editing GradientTexture2D properties in the inspector on a sprite 2d changes the gradient properties of any sprite2Ds previously created by copy and paste as well.

### Steps to reproduce

Create a sprite2D and set the texture to GradientTexture2d. Create another sprite2d by copy and paste. Editing the gradient properties of one sprite will change the gradient properties of the other sprite.

### Minimal reproduction project (MRP)

[reproductiontest.zip](https://github.com/user-attachments/files/18219451/reproductiontest.zip)

**Comment by atmosfaere** [comment]
This may apply to all textures and may have been a design decision in order to reuse the same texture.  I personally found the behavior unexpected and undesirable. It is inconsistent compared to changing the rest of the properties in the inspector which are all unique to each individual node. It is also inconsistent in that if you change the texture type of one linked sprite, then change it back, it now has its own unique properties.

**Comment by atmosfaere** [comment]
This is just a suggestion but if it was up to me, a new texture would be created once the parameters are edited and the sprite2ds would no longer be linked.

**Comment by AThousandShips** [comment]
Resources are shared by default, you need to use "Make Unique" to unlink them, please see [the documentation](https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html#editing-scenes-and-instances)

**Comment by atmosfaere** [comment]
As I mentioned, it seems like creating a new "unlinked" texture when the user edits the properties would bring the inspector behavior inline with the rest of the node's properties which are unique to each node. Is there a good reason not to do this?

**Comment by AThousandShips** [comment]
The design is to keep things linked, for many reasons, if you want to change this behavior you would need to open a [proposal](https://github.com/godotengine/godot-proposals) instead as this is intended behavior

**Comment by atmosfaere** [comment]
Thanks for the comments, I'll go ahead and close this. I do think it would be convenient to keep the resources shared until one is edited, causing a new texture to be created. I might submit a proposal in the future if I still think this is a good idea after some more thinking about it. 

Things work the way they are now, but maybe the interface design could be improved to be more intuitive (not having to select make unique which is somewhat hidden) and the behavior of sprites created by copy and paste having "hidden" linking of resources. This is something I definitely didn't expect for a simple gradient.
