### ISSUE TITLE
GD 4.4dev7 E 0:00:31:0634   invert: Condition "0.0 == r3[3]" is true.   <C++ 源文件>      core/math/projection.cpp:758 @ invert()

### ISSUE THREAD

**Issue by yythlj** [godotengine/godot#100789]
### Tested versions

E 0:00:31:0634   invert: Condition "0.0 == r3[3]" is true.
  <C++ 源文件>      core/math/projection.cpp:758 @ invert()

### System information

win10 gd4.4dev7

### Issue description

E 0:00:31:0634   invert: Condition "0.0 == r3[3]" is true.
  <C++ 源文件>      core/math/projection.cpp:758 @ invert()

### Steps to reproduce

E 0:00:31:0634   invert: Condition "0.0 == r3[3]" is true.
  <C++ 源文件>      core/math/projection.cpp:758 @ invert()

### Minimal reproduction project (MRP)

E 0:00:31:0634   invert: Condition "0.0 == r3[3]" is true.
  <C++ 源文件>      core/math/projection.cpp:758 @ invert()

**Comment by matheusmdx** [comment]
Please follow the issue guideline and provide the steps to reproduce and/or a minimal reproduction project, otherwise we can't help.

**Comment by Chaosus** [comment]
Sorry, we can't help you if you're not provide a required information.

**Comment by Chaosus** [comment]
This issue has been properly re-created in https://github.com/godotengine/godot/issues/100850
