### ISSUE TITLE
Copying SpotLight3D and OmniLight3D causes editor crash

### ISSUE THREAD

**Issue by lethiandev** [godotengine/godot#100734]
### Tested versions

Crashes on **4.4.dev7** and works fine for **4.4.dev6**

### System information

Godot v4.4.dev7 - Windows 11 (build 22631) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 XT (Advanced Micro Devices, Inc.; 32.0.12019.1028) - AMD Ryzen 5 5600X 6-Core Processor (12 threads)

### Issue description

I tried to copy over some OmniLight3D, but the same issue happens when trying to copy SpotLight3D, but DirectionalLight3D works fine though.

![Image](https://github.com/user-attachments/assets/dd3b2f20-8dbe-4500-a490-f4e2ede0cae9)

Crashes on Forward+, Mobile and Compatibility rendering mode.

### Steps to reproduce

- Create a scene
- Add OmniLight3D or SpotLight3D node
- Try to copy Ctrl+C or by context menu
- ???
- no profit

### Minimal reproduction project (MRP)

[light-copy-crash.zip](https://github.com/user-attachments/files/18221527/light-copy-crash.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, this has been solved already, please see:
* https://github.com/godotengine/godot/issues/100629
