### ISSUE TITLE
[4.4dev7] Engine crashes when copying an OmniLight3D node

### ISSUE THREAD

**Issue by cj0oste** [godotengine/godot#100744]
### Tested versions

- Reproducible in 4.4dev7
- Not Reproducible in 4.4dev6

### System information

Godot v4.4.dev7 - Ubuntu 22.04.5 LTS 22.04 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 Super with Max-Q Design - Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 threads)

### Issue description

When copying an OmniLight3D or SpotLight3D node, the engine crashes

### Steps to reproduce

Add an OmniLight3D or SpotLight3D to scene and copy it
 - Crashes either using the Ctrl-C hotkey or right clicking and using the context menu

Does **not** crash when copying the following related nodes:
- DirectionalLight3D
- DirectionalLight2D
- PointLight2D

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This has already been solved, please see the pinned issues
