### ISSUE TITLE
Compile error with MSVC

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#10071]
Godot 3.0 fails to compile with MSVC because of its rules for searching include files. Specifically, when compiling __`modules\gdnative\godot\dictionary.cpp`__ you get this error:

> [...]\core/io/json.h(62): error C2079: 'JSON::Token::value' uses undefined class 'Variant'

The problem is that although you'd expect `#include "variant.h"` in __`core/io/json.h`__ to include __`core/variant.h`__, since MSVC doesn't find it right where __`json.h`__ is, it looks for it according to this:

> In the directories of the currently opened include files, in the reverse order in which they were opened. The search begins in the directory of the parent include file and continues upward through the directories of any grandparent include files.

That is, it seems to go up in the include chain until it reaches the directory of the main file being compiled (__`modules/gdnative/godot`__), which happens to contain a __`variant.h`__ file itself, and that is taken.

I'm not sure how to deal with this. Happens at least with MSVC 2017.

@vnen, have you seen this issue? Any ideas on how to fix?

**Comment by Tyler-Yocolano** [comment]
Someone suggested going into the modules\gdnative\godot\dictionary.cpp file and putting #include "core/variant.h" above #include "core/io/json.h"

It worked for me.

**Comment by RandomShaper** [comment]
Well, that serves as a workaround, but the rules about include paths should be consistent across the whole codebase.

We have to find an universal solution; I mean, it might be inserting full paths like that _in every `#include`_, but let's hope someone can think of something better.

**Comment by marcelofg55** [comment]
Perhaps a better solution for this would be to change the `#include "variant.h"` to `#include "core/variant.h"` in json.h?

**Comment by RandomShaper** [comment]
@Tyler-Yocolano, sorry, I misread you. I thought you were suggesting the same @marcelofg55 has said now.

**Comment by karroffel** [comment]
I agree that more absolute paths should be used everywhere. I never even considered this kind of problem because it's hidden in `core/io`.

The sad thing is that it would work just fine if `clang-format` wouldn't move the `#include "core/variant.h"`  below the line for JSON.

I'll make a PR to fix this in GDNative, but I think in the long run we should use less ambiguous paths.
