### ISSUE TITLE
Navigation regression from 4.4-dev6 to 4.4-dev7 allows for climbing heights which should not be possible

### ISSUE THREAD

**Issue by SmialyKot** [godotengine/godot#100716]
### Tested versions

Reproducible in 4.4.dev-7
Not reproducible in 4.4.dev-6

### System information

Godot v4.4.dev7.mono - CachyOS Linux, Wayland display driver, Single-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (RADV NAVI31) - AMD Ryzen 9 7950X 16-Core Processor (32 threads)

### Issue description

There seems to be a regression in path finding which allows the character to "walk in the air" to reach high ground position which should not be reachable to him based on navigation settings.

### Steps to reproduce

1. Run MRP on 4.4.dev-6
2. Click on the high ground to move - character cannot get on the wall
3. Run MRP again on 4.4.dev-7
4. Repeat the experiment - character walks in the air

https://github.com/user-attachments/assets/a211dc61-5a4a-4b79-98b8-27fc999ff3fd

https://github.com/user-attachments/assets/a87fee80-51b7-4bf4-adf3-df5cbec6ed8c

### Minimal reproduction project (MRP)

[Click-To-Move-Godot-4-Tutorial.zip](https://github.com/user-attachments/files/18219941/Click-To-Move-Godot-4-Tutorial.zip)

**Comment by smix8** [comment]
Likely from https://github.com/godotengine/godot/pull/100129 but it does not happen for me with PR https://github.com/godotengine/godot/pull/100497 that is a followup.

Although I though all the "just-fixes" were added with PR https://github.com/godotengine/godot/pull/100587 but maybe not.

**Comment by SmialyKot** [comment]
I can confirm that issue is fixed in https://github.com/godotengine/godot/pull/100497
