### ISSUE TITLE
Importing some textures crashes Godot 3

### ISSUE THREAD

**Issue by TeddyDD** [godotengine/godot#10070]
**Operating system or device - Godot version:**
Linux Arch, Godot 3 from master, commit 95da12212beb6ab947de5ebbb0d12ffba3d2006c

**Issue description:**
Godot crashes when importing some textures. When I remove texture, project loads just fine. Format of texture does not matter, I tried to convert it to png, scale down, it still crashes.

**Steps to reproduce:**
- download [earth_normal_map.zip](https://github.com/godotengine/godot/files/1198791/earth_normal_map.zip)
- create project and try to add this image

Godot stdout/err
```
ERROR: environment_set_tonemap: Condition ' !env ' is true.                      7.2s  pią, 4 sie 2017, 00:53:27
   At: drivers/gles3/rasterizer_scene_gles3.cpp:914.
ERROR: environment_set_adjustment: Condition ' !env ' is true.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:929.
REIMPORT BECAUSE: modified resource time 0 vs 1501106391
ERROR: _render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6244.
REIMPORTING: res://textures/earth_normal_map.jpeg
saving: res://.import/earth_normal_map.jpeg-40089d7282bc42d6bbb80ce6707c5f82.s3tc.stex
to gen mipmaps w 8192 h 4096 format RGBA8 mipmaps 13 new size is: 178956972
saving: res://.import/earth_normal_map.jpeg-40089d7282bc42d6bbb80ce6707c5f82.etc2.stex
to gen mipmaps w 8192 h 4096 format RGBA8 mipmaps 13 new size is: 178956972
begin encoding, format: ETC2_RG11
godot.x11.opt.tools.64: thirdparty/etc2comp/EtcBlock4x4Encoding.h:77: float Etc::Block4x4Encoding::GetError(): Assertion `m_fError >= 0.0f' failed.
```

**Comment by Rubonnek** [comment]
I'm not able to reproduce this in Arch Linux with a `release_debug` build from the master branch commit 19e12424fc1786e24b372c2b62d9fbf262bfc227

**Comment by TeddyDD** [comment]
It's some issue with Etc compression
@Rubonnek could you check if `Import Etc 2` in enabled in project settings? 
It still affects me on 294e912a843cde241f9abf619f5d40df9ef6ef9f

**Comment by Rubonnek** [comment]
@TeddyDD `Import Etc 2` was enabled. I also enabled everything else under Vram Compression and I still can't reproduce this crash.

Are you building from the AUR? Any chance you could give me the exact `scons` command line you are using for building Godot?

**Comment by TeddyDD** [comment]
I'm not using AUR for Godot, here is the command:
`scons platform=x11 target=release_debug CXX=clang++ builtin_openssl=yes -j 4`

**Comment by Rubonnek** [comment]
I'm still not able to reproduce this even when building Godot ( 294e912 ) using that command.

Could you rebuild Godot adding `debug_release=yes` to that `scons` command and post a backtrace?

**Comment by TeddyDD** [comment]
I built with `debug_release=yes`, how to get the backtrace?

**Comment by Rubonnek** [comment]
```
gdb --args godot -e --path /path/to/project/that/crashes
run
# make godot crash
bt full
```

**Comment by TeddyDD** [comment]
I can't reproduce it with debug build, or any build ruining under `gdb`. It crashes consistently otherwise.

**Comment by dankjank91** [comment]
I was able to get my textures to import after crashing. 

At first, I was using a very high 8k res .jpg file. This I swapped out for a lower 2k res file and it works. So, I didn't try say a 4k res file but I would assume that this has to do with the resolution of the files I was using.

Below, you will find the log dump of the error I received: 

Godot Engine Editor

Description
Faulting Application Path:	 C:\Users\cp852\Desktop\Godot_v3.1.1-stable_win64.exe
Creation Time:			 9/30/2019 1:03:34 AM
Problem:			 Stopped responding and was closed
Status:				 Report sent

Problem signature
Problem Event Name:           AppHangB1
Application Name:             Godot_v3.1.1-stable_win64.exe
Application Version:          3.1.1.0
Application Timestamp:        00000000
Hang Signature:               8ef9
Hang Type:                    134217728

+---+

From my understanding the "Hang Type: 134217728" would have to do with file creation. I'm thinking that the files having issues being delivered to the repository.

**Comment by dankjank91** [comment]
Okay, so this was just being done wrong. Which, the right way IMO, isn't very intuitive. 

Instead of clicking on the arrow and selecting the image from the explorer menu, just drag and drop. 

Done, it imports doesn't crash and I can continue adjusting the parameters to get the look and resolution needed.

PM me if you have issues. Yes, I realize this is a closed post, but there was no resolution.

**Comment by Rubonnek** [comment]
@dankjank91, could you provide a godot project or some files that made Godot crash?
 
I want to take a look at the backtrace.

**Comment by dankjank91** [comment]
@Rubonnek

Yes, I've gone ahead and attached this here. 
So, to reproduce you'll need to use a drill down method for adding the images into the texture slot. 
It works beautifully when you drag and drop it to the slot, however. That is how I have gotten these in there so far.

Find picture and textures below:
[[2K]TactilePaving02 (1).zip](https://github.com/godotengine/godot/files/3685191/2K.TactilePaving02.1.zip)

![drilldown](https://user-images.githubusercontent.com/55620059/66113817-c67f7480-e58a-11e9-9aa5-f74e4551d4f8.PNG)
