### ISSUE TITLE
Fail to generate MSVS project for VS2017

### ISSUE THREAD

**Issue by JiahuiCai** [godotengine/godot#10084]
**Operating system or device - Godot version:**
Windows 10 Pro
Godot 3
python2.7
scons 2.5.0

**Issue description:**

trying to build the Godot source with scons -j10 p=windows vsproj=yes
received an error that says, 

"AttributeError: 'SConsEnvironment' object has no attribute 'MSVSProject':
  File "C:\Z_Development\Godot_Source\SConstruct", line 443:
    msvproj = env.MSVSProject(target=['#godot' + env['MSVSPROJECTSUFFIX']],"
![image](https://user-images.githubusercontent.com/16479286/28972194-b3dc189e-78fc-11e7-92ce-54260fc4d45e.png)

In the Scons' User guide, it says that this builder should be included by default.

**Steps to reproduce:**
Using Developer command prompt for VS2017
successfully build the binary with scons p=windows
then build with scons -j10 p=windows vsproj=yes
receive an error.

**I also received errors related to VsDevCmd.bat. But I don't think it relates to my problem.
![image](https://user-images.githubusercontent.com/16479286/28972049-394eb7a8-78fc-11e7-95cc-5bd218fb4146.png)

**Link to minimal example project:**

**Comment by vnen** [comment]
SCons wasn't updated to support VS 2017. You can notice that by the first warnings by SCons. There's nothing we can do in Godot to alleviate that AFAIK.

**Comment by Tyler-Yocolano** [comment]
You can go into the VS2017 Installer, modify your installation to include VC++ 2015.3 v140 toolset. Then still use the Dev Console for VS2017.  My system never completes the initial build when I use the -j tag so maybe try without that too.

**Comment by vnen** [comment]
> My system never completes the initial build when I use the -j tag so maybe try without that too.

This is and old and hard to fix issue (#5042), not related to the toolset. You just need to restart the build when it fails a few times until all generated files are built.

**Comment by JiahuiCai** [comment]
@vnen @Tyler-Yocolano 
Thanks for the explanations. Btw like I mentioned I did manage to compile a functioning executable with the latest vc compiler tho. XD magic. As vnen said ,you do have to run the build multiple times. That -j seems to be for parallel compilation. Anyway, I guess I have to get another ide for the lovely godotgodot

**Comment by vnen** [comment]
You can use VS 2017 to compile, because SCons will use whatever compiler is set up in the prompt. The issue with SCons not supporting VS 2017 is those warnings and the fact that you can't generate a project.

**Comment by JiahuiCai** [comment]
Got it
