### ISSUE TITLE
Attempting to populate MultiMeshInstance3D surface in version 4.4.dev7 crashes the engine

### ISSUE THREAD

**Issue by SolsticeMage** [godotengine/godot#100840]
### Tested versions

- Reproducible in: v4.4.dev7.official [46c8f8c5c]
- Not Reproducible in: v4.3.stable.official [77dcf97d8], v4.4.dev1.official [28a72fa43], v4.4.dev4.official [36e6207bb], v4.4.dev5.official [9e6098432], v4.4.dev6.official [1f47e4c4e]

### System information

Godot v4.4.dev7 - Windows 11 (build 22621) - Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) HD Graphics 520 (Intel Corporation; 30.0.101.1338) - Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 threads)

### Issue description

When attempting to select a target surface or a source mesh I get a white box and then the engine crashes.

In every version I tested prior to 4.4.dev7 it displays the scene tree, from which I can select the target surface and source mesh.
![Image](https://github.com/user-attachments/assets/9041bf0b-1b08-4600-bbc3-ce297a784a10)

### Steps to reproduce

1. Add a MultiMeshInstance3D node
2. Click "MultiMesh" in the viewport
3. Click "Populate Mesh" in the dropdown
4. Click the "..." to select a mesh instance
5. Watch all your hopes and dreams disintegrate (white window; engine crashes)

### Minimal reproduction project (MRP)

[project.zip](https://github.com/user-attachments/files/18257195/project.zip)

**Comment by matheusmdx** [comment]
This issue was fixed by pr #100670, the fix will come in the next release.
