### ISSUE TITLE
Duplicating a SpotLight3D Node crashes the editor (macOS)

### ISSUE THREAD

**Issue by quietbytes** [godotengine/godot#100833]
### Tested versions

Reproducible in Godot v4.4.dev7.official [46c8f8c5c]
Not Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.4.dev7 - macOS Sequoia (15.2.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

When duplicating a SpotLight3D node in Godot v4.4 dev7, the editor loads for a few seconds and crashes.
I'm able to duplicate other Nodes, but not tested all Nodes.

Happens on a newer MacBook Pro with an M3 Max as well.

### Steps to reproduce

1. Create a new project in Godot 4.4 dev7
2. Create a 3D Scene
3. Add SpotLight3D Node
4. Duplicate node
5. Godot crashes

### Minimal reproduction project (MRP)

[Test 2.zip](https://github.com/user-attachments/files/18255668/Test.2.zip)

**Comment by novemberist** [comment]
I think this was already fixed with https://github.com/godotengine/godot/pull/100639
