### ISSUE TITLE
Godot 3.0 iOS ignores button presses

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#10080]
**Operating system or device - Godot version:**
Godot 3.0 master 4 Aug 2017
iOS 11 Beta 4

**Issue description:**
Buttons in the interface can't be pressed. I first noticed this with the material tester demo, I couldn't tap the buttons to move from one sample object to the next or use the drop down to select a different background image.

Just found out it doesn't work in another test project I have either so seems something isn't implemented correctly yet in the platform code.

I'll have a closer look tomorrow when I have more time.

**Steps to reproduce:**
Place a button within a scene and hook up the pressed signal to a visible action.
Run the project, press the button, nothing happens.

**Link to minimal example project:**
Use material tester demo

**Comment by BastiaanOlij** [comment]
Ok, found the cause and it looks like someone already ran into this at some point but never fixed it properly. I actually had similar problems when implement the accelerometer and gyro.

As you rotate your device, even though we don't reorientate the render output (it always stays landscape) Apple changes the coordinate system according to the rotation. 

We can probably change this behaviour by forcing the return value of shouldAutorotateToInterfaceOrientation and adding supportedInterfaceOrientation and shouldAutoRotate to the view controller.

Alternatively as described in:
https://developer.apple.com/documentation/uikit/uiviewcontroller

We can use statusBarOrientation to determine the device orientation and adjust the coordinate system properly in all the touch events. This is what I did as a solution for the accelerometer data.

I'll submit a PR with some changes later today, probably using statusBarOrientation but seeing rendering is always done in landscape I think forcing the device orientation to always be "LandscapeLeft" seems like a much better approach.

**Comment by akien-mga** [comment]
Fixed by #10106.
