### ISSUE TITLE
"Ctrl + click" broken in script text editor for script functions

### ISSUE THREAD

**Issue by SeremTitus** [godotengine/godot#100869]
### Tested versions

- Reproducible in 4.4dev7
- Not reproducible in 4.3.rc3

### System information

Windows 11

### Issue description

Ctrl + click on a method call that is declared in a script lead to a go to  script documentation, similar to native method calls.
Issue also occurs on other members... Which is redundant since doc is already accessible on cursor hover as a tooltip

However, the same ctrl + click should go to where the code is implemented  for script methods

Current behaviour :

https://github.com/user-attachments/assets/06230af3-8d20-4fb4-bcee-3d33f974dda3

Expected behaviour as from 4.3.rc3:

https://github.com/user-attachments/assets/de3f5838-4ce0-401a-a6ce-245d453cc898

### Steps to reproduce

ctrl + click on accessed/called members

### Minimal reproduction project (MRP)

N/A

**Comment by arkology** [comment]
Fixed in https://github.com/godotengine/godot/pull/100707

**Comment by SeremTitus** [comment]
> Fixed in [#100707](https://github.com/godotengine/godot/pull/100707)

Thanks

**Comment by alanenggb** [comment]
So, this will come in 4.4 dev 8 build?
