### ISSUE TITLE
CSGPolygon3D - Certain numbers of Spin Sides always result in empty shape

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#100817]
### Tested versions

- reproducible in Godot v4.4.dev (0f95e9f8e) 

### System information

Arch Linux 20240101.0.204074 on Wayland - Wayland display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated Intel(R) Graphics (BMG G21) - AMD Ryzen 7 5700X3D 8-Core Processor (16 threads)

### Issue description

When using Spin Mode with CSGPolygon3D, certain numbers of Spin Sides (6,7,11,13,14,16,18,20 etc.) always result in an empty shape when using 360° Spin:

![Image](https://github.com/user-attachments/assets/ec3343b2-7c7a-44f2-a96f-bc0895396ce1)

You can use a lower value for Spin Degrees (like 359.9) but this is not ideal:

![Image](https://github.com/user-attachments/assets/237fb4d9-3419-44ab-b2ea-84eef71af3da)

### Steps to reproduce

- create a CSGPolygon3D
- switch Mode to "Spin", and keep Spin Degrees at 360
- change Spin Sides to a value like 6,7,11,13,14,16,18,20 ...

### Minimal reproduction project (MRP)

see steps to reproduce

**Comment by fire** [comment]
Does 0 degrees also fail? If it doesn't, then changing the limit from 0 to 359.999999 would solve this without too much breakage.

**Comment by Lielay9** [comment]
@fire Sounds similar to #100020, I may have missed one.

**Comment by novemberist** [comment]
> Does 0 degrees also fail? If it doesn't, then changing the limit from 0 to 359.999999 would solve this without too much breakage.

The editor only allows values between 1.0 und 360.0 for degrees, so I cannot test this.
