### ISSUE TITLE
Clicking mesh property inside MeshInstance will result in editor graphic artifacts 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10090]
**Operating system or device - Godot version:**
Ubuntu 17.04, 7ac50b523b8cb313245e2fbdd16b5561c88b3aeb, GTX 1060

**Issue description:**
After opening dae model in editor, navigating to `MeshInstance` node and clicking on 'Mesh` property in inspector, graphic artifact will appear in 3d view part of the editor.
![brokenmaterialpreview](https://user-images.githubusercontent.com/6129594/28978757-836a47da-7947-11e7-85eb-3894dba3cfe8.gif)

**Steps to reproduce:**
1. Download sample project
2. Open res://Issues/BrokenMaterialPreview/diamond1.dae
3. Click MeshInstance node in scene tree
4. Find `Mesh` property and click on it

**Link to minimal example project:**
[Issues3:Broken Material Preview.zip](https://github.com/godotengine/godot/files/1201075/Issues3.Broken.Material.Preview.zip)

**Comment by vnen** [comment]
I've seen this. Resizing the editor window makes it go back to normal.

**Comment by reduz** [comment]
Can you still reproduce this? I have same exact setup as you ( I'm using binary nvidia drivers) and it works fine.

**Comment by kubecz3k** [comment]
Cant reproduce with attached project anymore. But I'm able to reproduce with this one:
[Issues3.zip](https://github.com/godotengine/godot/files/1271482/Issues3.zip)
Reproduction steps are the same (Open res://Issues/BrokenMaterialPreview/diamond1.dae, Find Mesh property and click on it) (it's basically the same scene, don't know why it's reproducible in this project)
But I observed that issue behaves differently now:
+ The issue is reproducible only once per editor run (you need to have fresh run each time when you want to reproduce). 
+ Also when changing window from full-screen to window it sometimes behave slightly differently.
+ As far as I can tell material preview is black all the time.

**Comment by kubecz3k** [comment]
Ok, I must say, to be sure I downloaded zip which I uploaded couple minutes ago, imported to godot and I noticed Godot has re-imported all the assets (I assume). After that I'm unable to reproduce issue (so once again it's impossible to reproduce with provided project it seems).

But the thing that can be easily reproduced is corrupted preview, just have resize Godot window when looking at it:
![preview_artifacts](https://user-images.githubusercontent.com/6129594/29987767-000d5f10-8f6a-11e7-9683-d2eee0c7eddb.gif)

**Comment by kubecz3k** [comment]
I haven't seen this since some time. So I tried to reproduce, but it seems this is fixed.
