### ISSUE TITLE
PointLight2D doesn't work properly with an AtlasTexture

### ISSUE THREAD

**Issue by HatAndTie** [godotengine/godot#100981]
### Tested versions

found in 4.3

### System information

Ubuntu 20.04

### Issue description

When using an AtlasTexture on a PointLight2D, it will completly ignore the specified region and still use the whole Atlas as the light texture.
The Region is still correctly shown by the editor.
![Image](https://github.com/user-attachments/assets/bf0178f7-0c17-4e43-8bc7-132eae71f228)

The light also doesn't work right away inside the editor, while still working properly when testing the Project. Duplicating the node will make it work with the described issues.

### Steps to reproduce

The MRP shows 2 PointLights that are supposed to use the same Texture. The left uses an individual texture, while the right uses an atlas.

### Minimal reproduction project (MRP)

[point-light-atlas.zip](https://github.com/user-attachments/files/18282772/point-light-atlas.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, this is already tracked in:
* https://github.com/godotengine/godot/issues/95507

Closing as we prefer to have things in one place
