### ISSUE TITLE
Setting color on a hidden CanvasModulate node modulates all open scenes

### ISSUE THREAD

**Issue by Asmageddon** [godotengine/godot#10098]
**Operating system or device - Godot version:**
Windows 7, both Godot 2.1.3 and 3.x have this problem

**Steps to reproduce:**
Have multiple 2D scenes open(not mandatory), create a CanvasModulate node, tick visibility off, change the color.

**Expected result:**
Hidden CanvasModulate has no effect

**Actual result:**
All open scenes are modulated with the chosen color, unless they have their own, non-hidden CanvasModulate node.

EDIT: Should have clarified, this only has effect inside of editor.

**Comment by eon-s** [comment]
CanvasModulate should work that way, I presume (modulating the whole canvas layer).

If you have different CanvasLayers, it affects only where it is placed.

**Comment by Asmageddon** [comment]
@eon-s Did you read the issue? The problem is that if you change the color of a hidden CanvasModulate, it tints every single open scene.

**Comment by eon-s** [comment]
Oh, sorry, missed the "hidden" part.

So, is like if it turns on the visibility, and toggling on-off again does not return the original modulation if there is another active.

Also happens if color is changed by a script while running.
