### ISSUE TITLE
The get_children function does not get a correct result if the argument include_internal is true

### ISSUE THREAD

**Issue by chamer-vati** [godotengine/godot#100967]
### Tested versions

Reproducible in: v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.6614) - AMD Ryzen 7 6800H with Radeon Graphics (16 Threads)

### Issue description

When the parameter is true, all nodes under this node should be obtained

### Steps to reproduce

Direct run.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/18279034/test.zip)

**Comment by matheusmdx** [comment]
You misunderstand the `include_internal` parameter, when we say internal child that means nodes automaticly created by the engine for internal use of another node, you can easily see this with `ScrollContainer` node:

![Image](https://github.com/user-attachments/assets/686071ff-dc26-418c-a58f-e14842e2dcd2)

```
extends Control

func _ready() -> void:
	print($ScrollContainer.get_children())
	print($ScrollContainer.get_children(true))
```

This will print:

```
[]
[_h_scroll:<HScrollBar#24477959432>, _v_scroll:<VScrollBar#24511513866>]
```

<br>

In your mrp, `TestNode3` isn't child of `TestNode`, is a child of `TestNode2` so this won't be printed as result of `TestNode.get_children()`.
