### ISSUE TITLE
[v4.4dev7] Godot crash when selecting Skeleton property on MeshInstance3D

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#100924]
### Tested versions

 reproducible in 4.4dev7

### System information

Godot v4.4.dev7 - Windows 10 (build 19045) - Multi-window, 2 monitors - OpenGL ES 3/ANGLE (Compatibility) - ANGLE (AMD, AMD Radeon HD 5570 (0x000068D9) Direct3D11 vs_5_0 ps_5_0, D3D11-8.17.10.1433) - Intel(R) Pentium(R) CPU G2030 @ 3.00GHz (2 threads)

### Issue description

After adding a Node3D and MeshInstance3D as children, the Skeleton property shows Node3D as the picked one, and clicking on it makes Godot crash
![Image](https://github.com/user-attachments/assets/41706263-44a9-4e84-bf03-8b1f3a5e78b6)

![Image](https://github.com/user-attachments/assets/c23c3b59-bc15-4b15-8b57-e97bf30564f8)

### Steps to reproduce

1. create new 3d scene with root Node3D
2. add a MeshInstance3D
![Image](https://github.com/user-attachments/assets/f10f3e1d-b5be-45d3-8fba-c2df7af01458)
3. in inspector click on Skeleton value
![Image](https://github.com/user-attachments/assets/ec402e1c-732c-4378-8657-5fe4ab72ba4b)
4. crashed
https://github.com/user-attachments/assets/b915fa5b-6c19-463f-88cd-6bf1e5f572cd

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
This issue was a regression from https://github.com/godotengine/godot/pull/99700 and was fixed by pr https://github.com/godotengine/godot/pull/100670, the fix will come in the next release.
