### ISSUE TITLE
Problem loading scenes from a certain directory on Android device

### ISSUE THREAD

**Issue by isumaeru-ruzu** [godotengine/godot#100941]
### Tested versions

Godot v4.3 stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated Intel(R) HD Graphics 620 (Intel Corporation; 31.0.101.2127) - Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 Threads)

### Issue description

Good morning, how are you?

First of all, sorry for bothering you, but I'm having a problem here that I can't solve.
I'm creating a game called Broken Hearts, but I'm having a problem when loading scenes from a certain directory. Since my game has several stages, it's not worth creating a scene for each stage since it wouldn't change much from one to the next.

So I'm using a controller generic node  (e.g. level1Controller.gd) to do the "GameScreen" scene manipulations. My problem is when loading the heart fitting parts that are stored in a project directory:

_level1Controller.gd_

```
extends Node

func _create_all_heartparts() -> void:
	var directory_path:String
	var heartparts_array:Array
	var dir:DirAccess
	
	var number_level = Global.find_number_in_string(self.name)
	directory_path = "res://componets/lvls/level" + str(number_level) + "/"
	dir = DirAccess.open(directory_path)
	
	
	#Load each HeartPart scene and add it to an array
	print("Directory level " + str(number_level))
	if not dir.list_dir_begin() == OK:
		printerr("Error listing files in this directory.")
		return
	
	if dir:
		while true:
			var file_name = dir.get_next()
			
			if not file_name == "": print("File found: ", file_name)
			else: print("End of directory."); break
			
			if file_name.find("heartpart") != -1 && not dir.current_is_dir() && (file_name.ends_with(".tscn") || file_name.ends_with(".tscn.remap")):
				var file_path = directory_path + file_name
				var scene = ResourceLoader.load(file_path)
				heartparts_array.append(scene)
			
			
			if file_name.find("areas_collision") != -1 && not dir.current_is_dir() && (file_name.ends_with(".tscn") || file_name.ends_with(".tscn.remap")):
				var file_path = directory_path + file_name
				print(file_path)
				var scene = ResourceLoader.load(file_path)
				var data_component = scene.instantiate()
				heartarea_node.add_child(data_component)
	
	dir.list_dir_end()
	
	print("\n", "Array with all heart parts loaded: ",heartparts_array, "\n")
	
	#Create each HeartPart inside the Game scene
	for heartpart_scene in heartparts_array:
		var random_pos_x = randf_range(0.0, 1080.0)
		var random_pos_y = randf_range(1128.0, 1698.0)
		
		var new_hp = heartpart_scene.instantiate()
		new_hp.position = Vector2(random_pos_x, random_pos_y)
		heartparts_node.add_child(new_hp)
```

This code works here on my computer, however, it does not work on my cell phone. I noticed that the scenes within the application are ".tscn.remap". I tried to add this check within my code but they do not load.

![Image](https://github.com/user-attachments/assets/9019376a-ed8b-4ddc-a559-38a6073345f0)

Can someone who understands the Android side help me, please?
I really want to continue with this project.

### Steps to reproduce

Just open the project and then click on the "remote debug" button (With the Android phone connected to the computer). The game will open on your phone on the "task information" screen. Click the x button to close the screen, which will then display an error in your logcat.

To open logcat, you have to have Android Studio installed and then look for the "platform-tools" folder. Then open the console inside this folder and type this command: _adb.exe logcat | findstr "godot"_

### Minimal reproduction project (MRP)

Here is the link to the MRP version of my project:
https://www.dropbox.com/scl/fi/jtwggtoow8e2tjkz93g06/broken-hearts-mrp.rar?rlkey=chzzhlhkdj4bankuex2an1uwj&st=nb8frhyu&dl=0

The .rar file has the Android resources, so I couldn't add it here directly on github, so I left it hosted on Dropbox. Just download and unzip!

**Comment by syntaxerror247** [comment]
> This code works here on my computer, however, it does not work on my cell phone. I noticed that the scenes within the application are ".tscn.remap". I tried to add this check within my code but they do not load.

@isumaeru-ruzu You don't need to include `.tscn.remap`, you can load `.tscn` on Android.

Also, please include the MRP without `android` and `.godot` folder.

**Comment by isumaeru-ruzu** [comment]
I'm still unable to load a scene within my android device. My logcat always returns this error:
> 12-31 08:08:51.266 21951 22033 I godot   : File found: areas_collision.tscn.remap
12-31 08:08:51.267 21951 22033 E godot   : USER ERROR: No loader found for resource: res://componets/lvls/level1/areas_collision.tscn.remap (expected type: )
12-31 08:08:51.267 21951 22033 E godot   :    at: _load (core/io/resource_loader.cpp:291)
12-31 08:08:51.267 21951 22033 E godot   : USER SCRIPT ERROR: Attempt to call function 'instantiate' in base 'null instance' on a null instance.
12-31 08:08:51.267 21951 22033 E godot   :    at: _create_all_heartparts (res://scripts/leveis-controllers/level1_controller.gd:136)

Also I removed this condition "file_name.ends_with(".tscn")" for the code that is inside the "find" condition execute.

**Comment by isumaeru-ruzu** [comment]
> > This code works here on my computer, however, it does not work on my cell phone. I noticed that the scenes within the application are ".tscn.remap". I tried to add this check within my code but they do not load.
> 
> [@isumaeru-ruzu](https://github.com/isumaeru-ruzu) You don't need to include `.tscn.remap`, you can load `.tscn` on Android.
> 
> Also, please attach MRP without `android` and `.godot` folder.

I updated the dropbox link and now it is without the "Android" and ".Godot" folders. I find it very strange that this is happening, not wanting to load the scenes on Android. Now that I removed the check for the ".tscn" extension, godot finds the files but does not load them.

**Comment by Zireael07** [comment]
Can you load the files on your computer NOT from editor (from an exported build)?

Judging from the lines you quoted the issue is with tscn.remap which is a thing that only occurs in exported builds

**Comment by syntaxerror247** [comment]
@isumaeru-ruzu Use this line before loading resource, `var fine_name = file_name.trim_suffix(".remap")`. It will just remove the `.remap` and then would work with `ResourceLoader.load(...)`

In context of your code:
```
	if dir:
		while true:
			var file_name = dir.get_next()
			
			file_name = file_name.trim_suffix(".remap")
			
			if not file_name == "": print("File found: ", file_name)
			else: print("End of directory."); break
```

**Comment by isumaeru-ruzu** [comment]
> [@isumaeru-ruzu](https://github.com/isumaeru-ruzu) Use this line before loading resource, `var fine_name = file_name.trim_suffix(".remap")`. It will just remove the `.remap` and then would work with `ResourceLoader.load(...)`
> 
> In context of your code:
> 
> ```
> 	if dir:
> 		while true:
> 			var file_name = dir.get_next()
> 			
> 			file_name = file_name.trim_suffix(".remap")
> 			
> 			if not file_name == "": print("File found: ", file_name)
> 			else: print("End of directory."); break
> ```

@syntaxerror247 Thanks, it worked here! The scenes representing the parts of the heart loaded here!

I also really liked the explanation that user uwumacaronitime wrote on discord:

> uwumacaronitime — Hoje às 09:06
When godot packs a project, files in the virtual directory become .remap files of what they previously were
This isn't a bug, it's just a thing
To load a file, literally just remove .remap from the string
Via string.replace(".remap", "")
This isn't exclusive to android

**Comment by isumaeru-ruzu** [comment]
> Can you load the files on your computer NOT from editor (from an exported build)?
> 
> Judging from the lines you quoted the issue is with tscn.remap which is a thing that only occurs in exported builds

@Zireael07 Yes, I could load the ".tscn" files on my computer but not on my cell phone. I'm using remote debug to test my application on my cell phone, but I haven't created an exported build to test. Indeed, the problem was in the ".remap" suffix.

Well, thank you very much to you! @Zireael07 @syntaxerror247
