### ISSUE TITLE
Incorrect behaviour of InputEventMouseButton while holding mouse button

### ISSUE THREAD

**Issue by hlebchekkk** [godotengine/godot#100959]
### Tested versions

- Reproducible in: 4.3.stable, 4.2.1.stable

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 Threads)

### Issue description

There is big difference between behaviour of two quite similar classes which is responsible for input. In this particular case I'm talking about `InputEventKey `and `InputEventMouseButton`. If you hold the key on keyboard and catch the key being pressed by script, then you will see that the fact that the key is being held is well-detected by engine and its output. Example of the code:

```
func _input(event):
	if event is InputEventKey:
		if event.pressed:
			print("Key on keyboard pressed!")
```

Output:

```
Key on keyboard pressed!
Key on keyboard pressed!
Key on keyboard pressed!
Key on keyboard pressed!
Key on keyboard pressed!
Key on keyboard pressed!
Key on keyboard pressed!
...
```

But if you press and hold the mouse button and try to catch the key being held by script, you will see that there is only one message in output which means that the engine doesn't catch the fact that the mouse button is held which can provide different sufficient problems while coding. Example of the code:

```
func _input(event):	
	if event is InputEventMouseButton:
		if event.pressed:
			print("Key on mouse pressed!")
```

Output:

```
Key on mouse pressed!
```

### Steps to reproduce

Pretty sure that everything is already shown in **Issue description** quite understandable and fully.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/18278115/test.zip)

**Comment by Sauermann** [comment]
The fact that `InputEventKey` is triggered multiple times, is based on how operating systems (Windows/Linux/Mac/...) work: they send the key-pressed state once every few frames.
So Godot provides an additional functionality to check whether `InputEventKey` was pressed just now or if it is beeing held down:
``` gdscript
	if event is InputEventKey:
		if event.pressed and not event.echo:
			print("Key on keyboard pressed!")
```
This by checking this `echo` property you can achieve the same functionality as with `InputEventMouseButton`.

On the other hand, the operating systems don't send mouse-button held down events, so Godot provides a different way to check for the state of the mouse-button:
``` gdscript
func _process(delta: float) -> void:
	if Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT):
		print("Process: mouse button pressed!")
```

So from a historical point of view, operating systems send multiple key-down events and only a single mouse-button-down event.
Godot just follows this decision, but also provides functionality to check the state of the mouse-button. I'm not seeing any need for changing this approach.

Also be aware that changing `InputEventMouseButton` to include an `echo`-property and sending it like keys once every few frames, would very likely break many existing projects, which depend on the current behavior: The current behavior is that Mouse-button-down is always followed by a Mouse-button-up and never by a second Mouse-button-down.

**Comment by hlebchekkk** [comment]
Interesting. Really didn't know it is because of operating systems. I still find it quite strange because intuitively this classes should have similar behaviour but your arguments seem legit. And now I agree that leaving everything as it is now is a right approach. Thanks for your explanation.
