### ISSUE TITLE
2D lighting shaders are severely limited by their inability to affect the final color.

### ISSUE THREAD

**Issue by Asmageddon** [godotengine/godot#10091]
*Bugsquad edit:* Version 2.1.3-stable

By which I mean: There is no way to affect the actual final color, and setting either `SHADOW.a` or `LIGHT.a` produces no result if the area isn't already lit/shadowed.

The reason why this is a problem is simple: With CanvasModulate, it is possible for unshadowed areas to be dark, and set the equivalent of ambient light, but there is no way to mask some areas to always be fully lit, or have different ambient from within a shader.

This might be something of a corner case(though IMO, not really), but I'm sure that it is possible to find other issues with the system as well.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
