### ISSUE TITLE
Combining "Autowrap" with "Clip Text" only clips the text

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10103]
**Ubuntu 17.04 - Godot version: 3.0.alpha1**

**Issue description:**
When using a LineEdit, if both "Autowrap" and "Clip Text" options are selected, only the text clipping will happen.

**Comment by Noshyaar** [comment]
Did you mean Label? LineEdit has no such options.

**Comment by YeldhamDev** [comment]
Yes, I meant Label, and appears that the problem was how I was organizing it within my containers, sorry for wasting your time.

**Comment by Noshyaar** [comment]
No problem! :)

Did you resolve your issue?

**Comment by YeldhamDev** [comment]
Yep, the container made the label a little shorter than I imagined, that's why it was not wrapping.
