### ISSUE TITLE
Cannot create a MeshLibrary for GridMap, either using ArrayMesh or procedural meshes

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10118]
Godot 3.0 alpha1

I was trying to get a MeshLibrary setup quickly to prototype something, but noticed CubeMesh for example doesn't work when used in a scene that I convert to a MeshLibrary. 
Then I tried regular ArrayMesh from Blender, it still generated an empty MeshLibrary. I don't see errors at conversion time.

Here is the scene I used for the mesh library:
![image](https://user-images.githubusercontent.com/1311555/28999852-5865bb48-7a58-11e7-8312-c1af447b11bf.png)

Note: I also can't figure out how to make one without the "Convert to MeshLibrary". The platformer demo is the only gridmap I know of that works, but its MeshLibrary is a binary .res (so I can't remake one from it) and trying to convert `tiles.scn` also ends up in an empty MeshLibrary.

**Comment by zedutchgandalf** [comment]
I had this problem too before, but it seems to be fixed in the current master build.

**Comment by kubecz3k** [comment]
I think cb0e357d0b8565fcba6f2cf0ec5ea8e795e3fc2a fixed it
