### ISSUE TITLE
apply_impulse Function on a RigidBody node applies random angular velocity on it.

### ISSUE THREAD

**Issue by HoucineChelbi** [godotengine/godot#10111]
**OS:** Windows 8.1-64bits
**Version:** 2.1.3

**Issue description:**
Applying impulse to a RigidBody or Rigidbody2D node when it's mode i set to Rigid not only applies impulse but also applies a random angular velocity on it, which makes it goes crazy in different directions.

**Steps to reproduce:**
Create a RigidBody or RigidBody2D node, add a script to it, and call the apply_impulse() function in any other function( _ready(), _fixed_process()... ).

**Link to minimal example project:**
[Impulse Issue.zip](https://github.com/godotengine/godot/files/1202437/Impulse.Issue.zip)

**Comment by toger5** [comment]
If impulse is not applied to the center of mass it also results in a rotation.

**Comment by HoucineChelbi** [comment]
oh, you're totaly right, my bad.
I was applying it to it's position thinking that it was asking for a global position to apply on without even realising that the argument says offset, which makes alot of sense. thank you!
