### ISSUE TITLE
Console flooded with blank spaces when using Interpolated Camera

### ISSUE THREAD

**Issue by pcvonz** [godotengine/godot#10129]
**Operating system or device - Godot version:**
Ubuntu 17.04 -- Godot Alpha built 5th August.

**Issue description:**

Set up an interpolated camera, ran the scene and the Output was flooded with blank spaces. Every time the scene is opened up from now on the Ouput is flooded with blank spaces. 

**Steps to reproduce:**
Changed the following Interpolated Camera settings:

* Under **Interpolated Camera** 
  * I ticked enable
  * Assigned it to a target
* Under Camera I checked **current**

**Link to minimal example project:**

[test_ipo.zip](https://github.com/godotengine/godot/files/1203482/test_ipo.zip)

**Comment by akien-mga** [comment]
Is this still reproducible it in Godot 3.0 RC1?

**Comment by DualMatrix** [comment]
Tested in Master, no blank spaces in output.

**Comment by akien-mga** [comment]
Thanks, closing as fixed.
