### ISSUE TITLE
Gridmap editor doesn't respects cell scale

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10128]
Godot 2.1.4 beta2
Windows 10 64 bits

Repro steps:
1) Create a MeshLibrary with a cube inside
2) Create a GridMap using the MeshLibrary, place a few cubes: they are placed normally
3) Set Cell size to 1 and scale to 0.5: notice the cubes you placed already are wrongly positionned and don't appear scaled
5) Set Cell size to 2, then back to 1: notice cubes you placed already get correctly positionned and scaled. However, the edition cursor still shows a preview at original scale. Reloading the scene doesn't fix it.

![image](https://user-images.githubusercontent.com/1311555/29006786-e967d786-7af6-11e7-915e-f4bd78a99add.png)

Project: 
[Gridmap3.zip](https://github.com/godotengine/godot/files/1203410/Gridmap3.zip)

**Comment by kubecz3k** [comment]
in 1a92906b681735a5a2acfd98e3d6a4c75a7f6115  after closing and reopening the scene changes are applied: 
![screen](https://user-images.githubusercontent.com/6129594/29456989-5dd7d330-8418-11e7-9a7f-e790d927f4d0.png)

**Comment by Zylann** [comment]
You should also check the cursor showing a preview of the pieces before placing them

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by Zylann** [comment]
Reproducing with 3.1 alpha 1:

1) Create a MeshLibrary with a cube inside
2) Create a GridMap using the MeshLibrary, place a few cubes: they are placed normally
3) Set Cell size X, Y and Z to 1: positions are correctly shrunk, *however the orange grid isn't*
4) Set scale to 0.5: cubes you already drawn are correctly scaled, *but the orange grid and the cube preview under your cursor still isn't*, which prevents accurate painting:
![image](https://user-images.githubusercontent.com/1311555/45709591-456e5e80-bb7c-11e8-84b1-ee326a9ed9fb.png)
5) Reloading the scene appears to fix the grid, but the cube preview is now invisible.
![image](https://user-images.githubusercontent.com/1311555/45709708-8fefdb00-bb7c-11e8-92c8-768d1f71522a.png)

[GridmapTest.zip](https://github.com/godotengine/godot/files/2394151/GridmapTest.zip)

**Comment by menip** [comment]
Is this still issue in master?

**Comment by capnm** [comment]
> Is this still issue in master?

Good question. The cell entries in the editor now look like unusable garbage, when I tried to change something Godot crashed, so I gave up.
