### ISSUE TITLE
Action Numpad keys 2,4,6,8 not working

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#10122]
![image](https://user-images.githubusercontent.com/4741886/29003399-a72a05a0-7ab6-11e7-8946-e38fc900fe83.png)

Run the game -> Key not working

After Godot restart

![image](https://user-images.githubusercontent.com/4741886/29003437-1d5a5554-7ab7-11e7-8def-5687bd5815d5.png)

Ubuntu 16.04
kubuntu 17.04
Master branch

**Comment by Noshyaar** [comment]
I think `ui_*` stuff can't be modified.

**Comment by bojidar-bg** [comment]
Duplicate/Symptom of #3793?

**Comment by AlexHolly** [comment]
When it is not possible to change it why is it possible to change it? Maybe simply remove the + Button too like suggested with remove button.

Thanks I will use another action then.
