### ISSUE TITLE
[Suggestion] Extra options for child node/object to "Inherit" transform or global transform from the parent node/object?

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#10138]
**Operating system or device - Godot version:**
Godot 3.0 Alpha

I'm not certain of this is an interesting idea to implement in Godot or not but when sometimes I parent a child object to the main object (Whether its is a 2D or 3D Spatial Node) it forces the child to rotate and move with the parent. However, an idea made me think: If a node becomes a child to a parent, should there be an extra option that shows up at the bottom or within the transform submenu of the Inspector Panel that shows a checkmark(boolean) if you want the child to inherit the Translation, Rotation, and Scale of the Parent?

Say I want to make one part of the child node not rotate with the parent, I could easily uncheck the "Inherit Parent Rotation" to make it rotate in its own local/global transform rather than imitating the parent rotation.

Or leave the child scale small while the parent grows big by unchecking the "Inherit Parent Scale" to the child node.

Just a simple idea for Godot that could open up more simpler creative ways to modify nodes/objects.

**Comment by Noshyaar** [comment]
Have you tried RemoteTransform(2D)?

**Comment by Corruptinator** [comment]
Would it work in 3D? As in Spatial?

**Comment by bojidar-bg** [comment]
Well, there is RemoteTransform and RemoteTransform2D...

**Comment by Corruptinator** [comment]
Hmmm... I'm going to have to look into this. If this works then I feel foolish for making the suggestion on Github issues. Just some of the things I was never aware of.

**Comment by kubecz3k** [comment]
Well I dont think we need to bloat gui with such option. The feature is present currently, just do in ready `set_as_toplevel(true)`

**Comment by kubecz3k** [comment]
mean, we can push every possible setting to the gui but I think it will be unusable then :P For cases where scene always will be in global coords, its good to have this in ready, for those rare scenes where you will want to have choice, just use additional exported var to set this.

**Comment by Corruptinator** [comment]
Ok, so the Remote Transform is completely different than what I had in mind but it may work with what I planned to do next. Sorry for raising this issue for nothing.

**Comment by chanon** [comment]
I am trying to write a basic importer for Spine and since Spine has this kind of setting (you can uncheck inherit rotate or scale) , it is pretty hard to make Godot work to support that setting.

Using RemoteTransform2D would completely break up the skeleton hierarchy so isn't a good solution.
