### ISSUE TITLE
Allow documentation of exported script properties

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#10137]
Often script properties are supposed to be edited by artists (or, in general, not by the author of the script) and a tooltip explaining their meaning would be helpful. But it seems currently Godot only supports tooltips for builtin properties documented in `classes.xml`. It should be easy to expand `PropertyInfo` with documentation field which could be settable from GDScript or other bindings.

**Comment by Zylann** [comment]
Duplicate of https://github.com/godotengine/godot/issues/6204
