### ISSUE TITLE
3D platformer code is overly complex

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#1013]
Can't the 3D platformer be simplified? (or a simpler one can't be added?)

The corresponding Unity tutorial project is much simpler (and works a lot better and smoother):

http://unity3d.com/learn/tutorials/projects/stealth/player-movement
vs
https://github.com/okamstudio/godot/blob/master/demos/3d/platformer/player.gd

http://unity3d.com/learn/tutorials/projects/stealth/camera-movement
vs
https://github.com/okamstudio/godot/blob/master/demos/3d/platformer/follow_camera.gd

I'm also trying to understand: with godot, many stuff have to be done manually, but the corresponding Unity code feels like a breeze.

Is the 3d platformer demo a badly written godot code (in which case I was hoping a simpler re-write), or that's just the way things get done in godot?

I know, it's not exactly apples-to-apples comparison, but I'm referring to the things aside from jump/shots. In comparison, the way facing, movement or camera is handled, manual physics, manually checking if there is stuff there or not etc. is bloated code with godot (and Unity version has a very smooth transitions with quaternion lerps).

Camera code is also seriously complicate (and buggy); Unity camera code is quite simple and smooth.

Please please tell me that that is just a non-idiomatic, badly written godot code :)

Oh, and I think godo would benefit from a similar demo (you know, without jumps and bullets, just to demonstrate basic 3D stuff, maybe with light baking)

**Comment by seadra** [comment]
This blog post explains it better:

https://meshist.wordpress.com/2015/01/10/getting-started-gotchas-in-godot-engine/

> The platformer example code uses a boolean switch to check whether the player is currently shooting and toggle the state at the end of the update function. This is pretty confusing, and would only get worse the more actions are available. A much better way is to respond to events when they happen. To enable this, in your node’s _ready function call
```
set_process_input(true)
```
You’ll need an  _input(event) function to handle the events. There’s a bit of a trick to handling a single keypress. You’ll need to check the name of the event against your input map, make sure it’s pressed rather than released, and make sure it’s not the result of a key being held down
```
func _input(event):
    if (event.is_action(get_action('shoot')) 
        and not event.is_echo() 
        and event.is_pressed()):
        shoot_bullet()
```

**Comment by akien-mga** [comment]
This issue is a bit too unspecific, so let's archive it. Please open a more focused issue or PR if you have precise ideas about how to implement the 3D platformer demo (which has stated previously is already a complex game and the kinematic char demo is likely easier to get started learning Godot).
