### ISSUE TITLE
Support of custom render sort order in 3D

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#10135]
Currently Godot 3.0 supports render sorting based on various characteristics of materials, but sometimes games need to sort objects within same material group using a custom value. In our game specifically, ground meshes beneath buildings have alpha, and special effects (particles and meshes, always above ground level) also have alpha. The engine is not able to decide in which order to render them without additional information, which we cannot provide to it at the moment, so it renders them in arbitrary order.

A related problem is that for some reason [Godot assumes](https://github.com/godotengine/godot/blob/d9a97aae04b947517c286f019ce7cd8abd3745fe/drivers/gles3/rasterizer_scene_gles3.cpp#L2185) that all Unshaded materials have alpha, which is actually rarely the case. This prevents from properly sorting materials that actually have or don't have alpha.

**Comment by endragor** [comment]
Here is what happens with the current rendering algorithm, no matter if Shaded or Unshaded materials are used:
![Broken Order](https://i.imgur.com/zFf2Q3n.gif)

Pretty sure this needs to be resolved before 3.0, unless there is already a solution.

**Comment by reduz** [comment]
this should be pretty easy to implement, but the index to do the sorting
will probably be a bit limited (-128 - 127 or something like that, with
default at 0)

**Comment by endragor** [comment]
Thanks, that's more than enough for our use cases for sure.
