### ISSUE TITLE
Dropdown button with 'three dots' in the UI is unusable

### ISSUE THREAD

**Issue by drtwisted** [godotengine/godot#10144]
The dropdown button in the UI is unusable to it's tiny width. To open a dropdown menu you need to 'put a thread through a needles hole'.
The arrows in version 2.0 were just about right size, I never experienced any issues with them, why do the have to be replaced?

**Comment by Noshyaar** [comment]
What exact commit are you using? It was fixed recently.

**Comment by djrm** [comment]
i still think that the menu options should also be available by RIGHT click.

**Comment by reduz** [comment]
@djrm I want to rewrite the property editor in 3.1 and make it more like blender/unity, so for now don't want to touch it a lot, but I guess RMB could work too

**Comment by toger5** [comment]
@reduz Really excited for the rewrite!!

**Comment by drtwisted** [comment]
I tested on the most recent build. Indeed the button is much more usable then the in the build I had before. But the rewrite sounds terrific!

**Comment by akien-mga** [comment]
Fixed then.
