### ISSUE TITLE
Graphic artifacts in 3d scenes.

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10149]
**Operating system or device - Godot version:**
Linux, e12b422c90f3f866d133ea5ab797fb37f675e019, gpu: GTX 1060

**Issue description:**
After opening materials 3d demo artifacts can be observed: 
![artifacts](https://user-images.githubusercontent.com/6129594/29039927-8e4891d0-7bad-11e7-9218-d15eaae935d2.png)

**VIDEO:** https://www.youtube.com/watch?v=lT_s3C1VNxc

Also platformer 3d looks weird: 
![platfromer_artifacts2](https://user-images.githubusercontent.com/6129594/29039975-af3bae18-7bad-11e7-885e-0818c8b8d92c.gif)

**Steps to reproduce:**
1. Open materials demo
2. Check Platformer 3d demo

**Link to minimal example project:**
Use `Material demo` and eventually `Platformer 3D` demo

**Comment by eon-s** [comment]
Same on Master, nvidia proprietary drivers, demo with default settings.

I see excessive light too, lower sky energy results in a new set of amazing glitches.

Some tonemaps are totally broken too (on the demo at least).


On the terminal got many

> ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Performance	ID: 131186	Severity: Medium	Message: Buffer performance warning: Buffer object 34 (bound to NONE, usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.
>    At: drivers/gles3/rasterizer_gles3.cpp:122.

And

> ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Performance	ID: 131218	Severity: Medium	Message: Program/shader state performance warning: Vertex shader in program 67 is being recompiled based on GL state.
>    At: drivers/gles3/rasterizer_gles3.cpp:122.

And

> ERROR: shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
>    At: drivers/gles3/rasterizer_scene_gles3.cpp:145.
> ERROR: getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
>    At: core/rid.h:164.


And this at the end

> [PropertyValueEvaluator]: Error eval! Error code: 1

**Comment by JiahuiCai** [comment]
Same issues on Window with GTX1070

**Comment by eon-s** [comment]
Same glitches on AMDGPU (R5).

**Comment by HummusSamurai** [comment]
I have similar problems with the 3D Platformer, haven't checked the materials demo.

Fedora 26, Nouveau drivers, GT930M.

**Comment by gamergamesz** [comment]
yes it looks like .5 is full metal in  latest

**Comment by Listwon** [comment]
Same glitches on Intel® HD Graphics 530, Windows 10 Pro x64

**Comment by reduz** [comment]
do you know when this started? It used to work, did it not?

**Comment by akien-mga** [comment]
It's likely a regression from a couple weeks ago, since it was first reported 10 days ago and then there were many duplicates and confirmations.

That's a job for bisect-master @kubecz3k ;)

**Comment by reduz** [comment]
any bisecting appreciated!

**Comment by kubecz3k** [comment]
With help from @Calinou we did a bisection and it seems that 5c361485db9cb2c6d9f9fb8906ee283ee220aa00 is the first bad commit

**Comment by Zireael07** [comment]
Why would GLTF support lead to those bugs?

**Comment by Calinou** [comment]
> Why would GLTF support lead to those bugs?

Some shader changes were done in that commit, which can led to 3D rendering regressions like the one in the issue.
