### ISSUE TITLE
Inherited Models don't hold information about textures/mappings

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10147]
**Operating system or device - Godot version:**
Linux, e12b422c90f3f866d133ea5ab797fb37f675e019

**Issue description:**
After creating inherited scene for dae model, it's impossible to setup mapping and textures, because the information will be lost after closing the scene:
![inheritedmaterial](https://user-images.githubusercontent.com/6129594/29033022-e8ba3624-7b93-11e7-8a9c-b7b3f1af71c7.gif)

**Steps to reproduce:**
1. Download reproduction project.
2. Open stone.tscn
3. Setup albedo texture
4. Save and close
5. Open stone.tscn again

**Link to minimal example project:**
[Inherited Material Issue.zip](https://github.com/godotengine/godot/files/1205262/Inherited.Material.Issue.zip)

**Comment by bojidar-bg** [comment]
Using "Override Material" work, right?

**Comment by reduz** [comment]
This needs to be more user friendly.. the inherited materials belong to the
original scene, so they need to be made unique in the local one to be
edited. This is not straightforward and has to be presented better

**Comment by Zireael07** [comment]
@reduz: Related to #9037 then.

**Comment by kubecz3k** [comment]
Actually in that case it would be quite bad to use "Override Material". Our 3d asset workflow assumes we will create inherited scenes for assets/dae files. And setting material inside dae is not a good idea since it will be lost after re-import.

**Comment by reduz** [comment]
I changed the default behavior so materials are imported as separate resources and kept, so you can edit them. I will leave this open so I remember to make the property editor read-only if the resource belongs to an inherited scene.

**Comment by kubecz3k** [comment]
@reduz if I understand you correctly then you are suggesting to setup material inside dae file. This is not helpful since Godot is unable to save dae files:
![alert](https://user-images.githubusercontent.com/6129594/29968563-82b46830-8f1c-11e7-85aa-1f4bf482d123.png)
also as I said every time when user is opening dae scene he is dealing with alert information that scene can't be modified. 
Am I understanding something wrong?

**Comment by kubecz3k** [comment]
Checked today with aa4694b7b4717d7b43e0fb9a037d07cd20ad14cd. It seems this is fixed now. Thanks!

**Comment by kubecz3k** [comment]
In the end it seems the issue is not fixed yet in 78423320d78235a5b2fde05e7816f79de729f317. It's working for me with one model (don't know why). Also some other models (like the one on the vid) will have correctly predefined some mappings (also dont know why), but I still can't change other mappings or values. I'm not sure maybe I'm doing something wrong here? Recorded a vid on which I'm creating fresh project and I'm importing a model: https://www.youtube.com/watch?v=WW0QKTXtDOw&feature=youtu.be
(you can start watching it from  40s, first 40s is project creation)

**Comment by ThomasMorley-T3D** [comment]
This appears to still be broken. 
[Make Unique.zip](https://github.com/godotengine/godot/files/1544533/Make.Unique.zip)

**Comment by kubecz3k** [comment]
I'm no longer able to reproduce in 3fd1c0c76b61173c5d611b14b5b137fb61654f08 
Keep in mind you need to import models with import preset `Import with separate materials` which I think was default back then. 
Also if anyone would like to be able to enhance animations the best preset is `Import with separate materials + animations`

**Comment by kubecz3k** [comment]
@ThomasMorley-T3D The ball is changing directly to yellow because of some bug in the script. I used couple prints and I can see that the code that's changing color to red is never fired.

**Comment by ThomasMorley-T3D** [comment]
I you change the ball spawn time to 31 you will see that the scrtpt appears to be correct. The ball will go from gree to yellow and then red. The problem is when you reduce the ball spawn time 5 seconds and have multiple balls the call to an individual ball changes the material of all the balls in the scene. Setting the material to unique makes no difference. The script could be wrong but I don't see the problem.

**Comment by kubecz3k** [comment]
If that's the problem then as far as I know you should set 'local to scene' inside material resource.
