### ISSUE TITLE
Add RTL Support in Godot 3

### ISSUE THREAD

**Issue by Shahsavarzade** [godotengine/godot#10153]
##**Operating system or device - Godot version:**
ZubunTU GNU/LINUX

**Issue description:**
Please Add RTL Support in Godot 3 Official.
Godot has a lot Users in iran

Because Persian language not supported by Godot official version, Iranian users are getting less every day

:-(((((((((((((((((((

**Comment by volzhs** [comment]
duplicated with #982

**Comment by reduz** [comment]
Dear users in Iran, i know you are not Buddhist, but Gandhi once said "Be the change you want to see in the world". Our main devs do not understand RTL, so any help implementing and testing this functionality will be very appreciated.

Closing as duplicate
