### ISSUE TITLE
Project Manager is crashing

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10150]
**Operating system or device - Godot version:**
Linux, f035e4a24abf9e7c8e72ffdf3c5e6c2968c4393c

**Issue description:**
It's impossible to open project manager. It's still possible open editor by running the project with -e parameter. 
From my bisection it seems f035e4a24abf9e7c8e72ffdf3c5e6c2968c4393c is the first bad commit

**Steps to reproduce:**
1. Try to run the editor without any project. 
Alternatively:
1. Exit from project with `Quit to project list` option.

**Link to minimal example project:**

**Comment by kubecz3k** [comment]
cc @toger5

**Comment by vnen** [comment]
Duplicate of #10146

**Comment by kubecz3k** [comment]
Ah, sorry for that! :)
