### ISSUE TITLE
OSX Can't compile

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#10167]
**Operating system or device - Godot version:**
5e1116da4ce052acc64f45ba4bd71310b4826aea
on macOS

**Issue description:**

getting those issues:
<img width="351" alt="screen shot 2017-08-08 at 13 14 06" src="https://user-images.githubusercontent.com/16718859/29069624-f0daf30e-7c3b-11e7-9f90-f7d1f7d38dae.png">

**Comment by volzhs** [comment]
`cursor_set_visible` was remove at 539fbad

**Comment by toger5** [comment]
@volzhs really helpful! Ill try just removing it from the os_osx than too...
