### ISSUE TITLE
Visual scripting Wait node does't work after a condition node

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#10175]
**Operating system or device - Godot version:**
Godot 3.0 Alpha 1

**Issue description:**

Wait node works perfectly but if you place a wait node after a condition node it does't work anymore.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by vnen** [comment]
Can you attach a sample project?

**Comment by samvila** [comment]
[test.zip](https://github.com/godotengine/godot/files/1209346/test.zip)

**Comment by samvila** [comment]
I just notice that I already submitted this issue long time ago:

https://github.com/godotengine/godot/issues/6583

Nothing new since 2016, hope this gets sorted eventually. Can someone merge both threads or should I just close this ticket and add the example file on the old ticket?

**Comment by vnen** [comment]
Then I'll close this as duplicate of #6583. Will also add the old issue to the 3.0 milestone so it's not forgotten.

**Comment by samvila** [comment]
Thanks!
