### ISSUE TITLE
Editor Help duplicated and no line breaks

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#10171]
**Issue description:**

sometimes the editor help is buggy.
Here is a screenshot:
<img width="861" alt="screen shot 2017-08-08 at 19 00 36" src="https://user-images.githubusercontent.com/16718859/29084598-d43e6452-7c6c-11e7-9442-d4434e66fb26.png">

I can't tell when it happens. 

**Issues are:**
 - missing newLines, indents
 - duplicate entries of property and method description list

### It is formatted like this:

WORKING inheritance/class section
WORKING property list
WORKING method list
WORKING description
BROKEN property description list
BROKEN method description list
WORKING property description list
WORKING method description list

BROKEN: no tabs, no indents, no newline

**Comment by vnen** [comment]
IME it happens when there's a code block in the class description.

**Comment by toger5** [comment]
for a quick fix should I remove the Code block or look into whatever is causing the duplication?

**Comment by toger5** [comment]
I was looking into that and it is pretty hard.
The rtl code hard material to work with ;) But I understand most of the parts now. Finally...

 - I'm pretty sure the issue is caused in the rtl not in editor_help.cpp which builds up the rtl.

 - It is only one line which is broken
<img width="1674" alt="screen shot 2017-09-03 at 03 01 50" src="https://user-images.githubusercontent.com/16718859/29999741-48d00082-9054-11e7-9e60-265b8941cbcf.png">

 - this line is of type ITEM_NEWLINE
```
static_cast<ItemText *>(main->lines[24].from)

   RichTextLabel::Item:{...}
   index:122
   parent:0x0000000153e25760
   type:ITEM_NEWLINE
   subitems:{...}
   E:0x0000000153e25b30
   line:24
      line:25
```
but it has 
```
main->lines[24].char_count
234
```
characters

which seems like there is something wrong...

@reduz if this information gives you an idea would be great if you share it!
