### ISSUE TITLE
3D particles blink when set a velocity of 0

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10183]
Godot 3.0 alpha1
Windows 10 64 bits
nVidia geforce 940M

When I set a velocity of 0 for particles in the process material, particles spawn and disappear one frame after, though lifetime is set to 1 second.

**Comment by kubecz3k** [comment]
I was able to reproduce

**Comment by kubecz3k** [comment]
It looks like this:
![0_vel_particles](https://user-images.githubusercontent.com/6129594/29180839-56bb93b8-7df9-11e7-9878-ec4c2f234cae.gif)
