### ISSUE TITLE
There is no way to import BitmapFont in Godot 3

### ISSUE THREAD

**Issue by TeddyDD** [godotengine/godot#10184]
**Operating system or device - Godot version:**
Godot 3 form master, commit df573f5c3a76155842e43ea0dbab594e3944b114

**Issue description:**
While BitmapFont resource exist, there is no way to import TTF as BitmapFont 

There is one more use case I'd like to mention: importing image as BitmapFont. 
You can find a lot of bitmap fonts in form of textures in the internet. 
It could be nice to have way to import them. It's also easier to draw pixel font for your game than create vector ttf file. 

From what I see in the BitmapFont API, it could be done as plugin.

Example bitmap fonts from Playscii project: 
image:
![pico8](https://user-images.githubusercontent.com/4397533/29097786-f66ad1c6-7c9b-11e7-86f3-3782c37674b6.png)
and character set definition:
[pico8.txt](https://github.com/godotengine/godot/files/1209768/pico8.txt)

**Comment by reduz** [comment]
The idea was to add BMFont support at some point, since there already is
support for it in the bitmap font class..

**Comment by TeddyDD** [comment]
Good to know. Personally I use DynamicFonts but that use case with png -> font seems nice especially for writing rouge-likes ;)

**Comment by Dillybob92** [comment]
I'm using the font Orbitron https://fonts.google.com/specimen/Orbitron

and bitmap is ideal for it, however, dynamic works fine but not as "crispier" if you will

would really love to see bitmap fonts make a comeback for 3.0!

**Comment by Zylann** [comment]
It's also the only way to change the script editor font, and I don't know how to do it properly at the moment^^"
An issue was open about it though https://github.com/godotengine/godot/issues/10866

**Comment by reduz** [comment]
The old bitmap font importer will not come back due to it being really complex and hacky.
I suggest implementing BMFont support (Godot can parse thos files, there are methods for that in BitmapFont):

https://github.com/godotengine/godot/blob/master/scene/resources/font.h#L122

either as a resource type or importer (resource type may make more sense).

**Comment by mrcdk** [comment]
Doesn't this PR https://github.com/godotengine/godot/pull/12619 fix this?

**Comment by Dillybob92** [comment]
It seems like we can use 2.xx and import the bitmapfont, then change its filename to .font and use it in 3.0.  I saw a facebook post of someone mentioning this, however, I imagine this might cause problems in the future? If not, I mean I guess we should be fine for now if #12619 gets merged

**Comment by mhilbrunner** [comment]
Should #12619 be re-opened/merged? Seems it is the most feasible way currently.

**Comment by reduz** [comment]
I will kick this to 3.1, I think bitmap fonts are still of limited use and BMFont support partly covers this.

**Comment by akien-mga** [comment]
But there is no BMFont support, is there?

**Comment by reduz** [comment]
yes, there is

**Comment by akien-mga** [comment]
How? I have a .fnt file in my project, it's not shown in the file system dock and I can't use it as font resource.

**Comment by mrcdk** [comment]
It somewhat there, you need to create a `BitmapFont` and then via code:
```gdscript
$Label.get_font("font").create_from_fnt(fnt_path)
```
![https://i.imgur.com/On5vY83.png](https://i.imgur.com/On5vY83.png)

**Comment by mrcdk** [comment]
This is now working since https://github.com/godotengine/godot/commit/4de84f4c0a53fdaf72e16715b77b8a93bc8f220a

**Comment by reduz** [comment]
great, closing then
