### ISSUE TITLE
3D particles are extremely laggy when seen close

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10185]
Godot 3.0 alpha1
Windows 10 64 bits
nVidia geforce 940M

I made a failed attempt to generate a cloud using particles, but I noticed that if I watch them from a close distance, it starts to lag a lot, even with only 200 particles.
(I'd like to see how Godot perform to recreate a project I made with Unity 4 years ago: https://www.youtube.com/watch?v=vJgZz31GIWg)

Project: 
[ParticlesTest.zip](https://github.com/godotengine/godot/files/1209774/ParticlesTest.zip)

**Comment by eon-s** [comment]
The same on Ubuntu.
Removing the "transparent" flag on the spatial material, the speed returns to normal.

**Comment by reduz** [comment]
This is normal, because there is a lot of overdraw involved (particles are lit per pixel). Set the particle material to unshaded or enable vertex shading to improve performance.

**Comment by reduz** [comment]
should probably be in a tutorial eventually, if you want we can leave this open as a reminder to document how to make particles fast in this situation

**Comment by eon-s** [comment]
Yes, the new particles system will need a special section on documentation because is pretty big and complex, in particular for people used to regular particle systems.

I think it will need a plugin on a panel just to edit particle effects with presets and a full view of emitter and materials.

**Comment by Zylann** [comment]
Oh... yeah I was suspecting that, I was not sure. It's purely the cost of the pixel shader then, because in opaque mode it runs smoothly even though there is still a lot of overdraw.
