### ISSUE TITLE
can delete text in readonly TextEdit

### ISSUE THREAD

**Issue by bitwes** [godotengine/godot#1018]
If you select the text (shift + home/end/arrow keys) you can delete the selected text from a read only TextEdit control.  It doesn't appear to be accepting any other keystrokes.  Backspace and delete do nothing (as expected) unless there is selected text.

**Comment by reduz** [comment]
should be fixed, please test

**Comment by akien-mga** [comment]
Assuming it has been fixed as per above comment.
