### ISSUE TITLE
3D particles emission gets chunky if framerate is slowed down

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10186]
Godot 3.0 alpha1
Windows 10 64 bits
nVidia geforce 940M

I noticed 3D particles emission became less random if the framerate isn't 60fps, giving this kind of artifact with 5000:
https://www.youtube.com/watch?v=yEKJqWV1z-0&feature=youtu.be
If I reduce to something lower like 1000, the spawn pattern is back to random.

**Comment by reduz** [comment]
This is intended, randomness only happen in the slice assigned to the particle. Due to how particles works, it's impossible to do otherwise. That said, eventually you should probably be able to modify the particle shader soon to make the changes you might want for your specific case.
