### ISSUE TITLE
Wireframe mode doesn't work with particles

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10187]
Godot 3.0 alpha1
Windows 10 64 bits
nVidia geforce 940M

I noticed wireframe mode does't turn particles into wireframe, are they supposed to be able to render this way?

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by Zylann** [comment]
Went a bit further, and curiously, wireframe works with SphereMesh, but NOT with QuadMesh:

![image](https://user-images.githubusercontent.com/1311555/34959847-970dc3c6-fa38-11e7-8992-af0ed439db66.png)
