### ISSUE TITLE
Particles don't fire again when unmarking "One Shot"

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10181]
**Ubuntu 17.04 - Godot version: 3.0.alpha1**

**Issue description:**
When unmarking the "One Shot" option in a Particles/Particles2D node, it will not start firing again unless either the scene is restarted, or setting off and on the Emitting opition.

**Comment by ISylvox** [comment]
I think it's expected. That is the point of One Shot.

Emitting ON + OneShot ON will play the particle only once during its Time/Lifetime and then Stopped. To play the particle again, need to restart Emitting.

**Comment by kubecz3k** [comment]
I think it could be fixed, there is no reason why this should not happen transparently for the user. Presentation from the actual issue: 
![one_shot](https://user-images.githubusercontent.com/6129594/29185027-546259d0-7e08-11e7-9e57-ef6093d48117.gif)

**Comment by kubecz3k** [comment]
I'm not sure but this probably should not be hard to (hence `junior job`)
