### ISSUE TITLE
minor UI: prevent resetting pinned animation editor

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#1019]
If you have a pinned animation editor, and you click somewhere in the timeline where you want to insert a keyframe, then click on another animation editor (to keyframe playing of another animation, for instance), it will reset back to the 0 position. It should only do this if there is no animation editor currently pinned.

**Comment by reduz** [comment]
i´m not sure if i understand this, pinning is just so if you open other animationplayer, it will keep using the editor for the previous animation player

**Comment by adolson** [comment]
Yes, but it resets the position to 0 in the timeline when you click on the other animationplayer. if you click on any other kind of node, it doesn't reset to 0, it stays where you want

**Comment by akien-mga** [comment]
I can confirm that this is still valid in the current master branch.
