### ISSUE TITLE
ImmediateGeometry does not work in 3.0

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10197]
**Operating system or device - Godot version:**
windows, latest build

**Issue description:**
i'm using this code:
```
    var imm = get_node("ImmediateGeometry")
    imm.clear()
    imm.begin(Mesh.PRIMITIVE_LINE_STRIP, null)
    imm.add_vertex(Vector3(0,0,0))
    imm.add_vertex(Vector3(0,10,0))
    imm.end()
```
but it produces nothing on screen
am i using it wrong or it is broken?

**Link to minimal example project:**
https://www.dropbox.com/s/f473mkcuq20yc2y/imm.zip?dl=0

**Comment by kubecz3k** [comment]
It looks ok for me at the first glance. Are you sure you are using latest master? ImmediateGeometry fix was fixed 2 days ago (it's now working in my project, but haven't check your sample yet).

**Comment by kubecz3k** [comment]
Oh also, I think you should use `Mesh.PRIMITIVE_LINES`  like: `imm.begin(Mesh.PRIMITIVE_LINES, null)`

**Comment by curly-brace** [comment]
i already don't know what am i using, i've downloaded it from Calinou's repo and it is marked as from 07 August but commit is de6b972, but i faile to find it tho in the tree...

**Comment by kubecz3k** [comment]
it was merged at 7 august but very late in night, I think you need build at least from the 8 :)

**Comment by curly-brace** [comment]
ok thanks

**Comment by kubecz3k** [comment]
here is the commit with fix for the reference: https://github.com/godotengine/godot/pull/10055
