### ISSUE TITLE
ScrollContainer doesn't react to its child's "sort_children()" naturally

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10207]
**Ubuntu 17.04 - Godot version: 3.0.alpha1**

**Issue description:**
When the size of the child of a ScrollContainer node changes, the container will not update its scrollbars unless interacted with. The developer needs to use signals and manually call "queue_sort()" for the container.

**Link to minimal example project:**
[Test.tar.gz](https://github.com/godotengine/godot/files/1211935/Test.tar.gz)

**Comment by Paluth** [comment]
I also ran into this problem. Using the proposed work around fixes it but there should be no need for using it.

**Comment by YeldhamDev** [comment]
@akien-mga I have only now seen that you labeled the duplicate of this issue as "archived", could you put this one in the 3.0 milestone then?

**Comment by reduz** [comment]
This may be related to scroll container or not: 
https://github.com/godotengine/godot/blob/master/scene/gui/scroll_container.cpp

Technically when nodes are removed or minimum size changed, the containers will re-sort them. Possible solution may be to call update_scrollbars on NOTIFICATION_SORT_CHILDREN

**Comment by YeldhamDev** [comment]
@reduz So the fix is literally one line away... May I have a go then?

**Comment by YeldhamDev** [comment]
Closing as this is not the real issue.
