### ISSUE TITLE
blue circle at the bottom of the default environment

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#10204]
**Operating system or device - Godot version:**
Arch Linux, Godot master
Intel HD4000
Mesa 17.1.6

**Issue description:**
There is this light blue dot/circle at the bottom of the 3d scene with the default environment enabled, which looks like a very distant reflection of the sky. Is it supposed to be there?

**Steps to reproduce:**
Look into the abyss.

**Link to minimal example project:**

![blue_circle](https://user-images.githubusercontent.com/7927471/29120168-6546d7ee-7d09-11e7-8dce-91c023de5222.png)

**Comment by Noshyaar** [comment]
I had seen this weeks ago, then it disappeared. I think it's fixed. What is the exact commit you're using?

**Comment by novemberist** [comment]
The latest commit, from about 30 minutes ago. This thing has been there for ages, i first thought it was a new gizmo or something to lock the y axis ;)

**Comment by reduz** [comment]
Thay say it's a portal to a parallel dimension that opens up at the
eleventh hour of the Equinox. It may be a floating point precission error
too.

**Comment by Noshyaar** [comment]
Can't reproduce. But I think it's an issue with ProceduralSky. Try looking up too.
![image](https://user-images.githubusercontent.com/26753932/29120519-c8aa3d3c-7d34-11e7-840e-c7b5557cc02e.png)

Is it an older project by any chance? Does it happen in a newly created project?

**Comment by novemberist** [comment]
That thought crossed my mind, too. But it also happens with newly created projects. Maybe it's another driver issue, so I'll add my device and graphics driver to the issue.

**Comment by novemberist** [comment]
And yes, there is also one at the other end of the y-Axis
![blue_circle_top](https://user-images.githubusercontent.com/7927471/29121063-478aedea-7d0d-11e7-99fc-f55185e7fd4b.png)

**Comment by Noshyaar** [comment]
That's exactly the same issue I've had long ago... 🤔

**Comment by novemberist** [comment]
The color of the one on the top is affected by "Sky/Horizon Color" and the one on the bottom by "Ground/Horizon Color" by the way. Don't know if this helps to trace the source of this issue.

**Comment by BrainBlasted** [comment]
Could I get some of your project files? Also on Arch Linux, Godot master, Intel HD4000, Mesa 17.1.6

**Comment by novemberist** [comment]
I can no longer reproduce this.

**Comment by reduz** [comment]
This portal may be either
a) A floating point precision error in the panorama shader
https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/copy.glsl#L82
b) A floating point precision error or similar in the procedural sky code:
https://github.com/godotengine/godot/blob/master/scene/resources/sky_box.cpp#L131

**Comment by Zylann** [comment]
It still happens in Godot 3.2 beta2:

![image](https://user-images.githubusercontent.com/1311555/70384020-00486f00-1970-11ea-8959-622eeaaf7dc2.png)

![image](https://user-images.githubusercontent.com/1311555/70384021-050d2300-1970-11ea-904a-1fee71604e34.png)

**Comment by nathanfranke** [comment]
Still reproducible in 3.2.3.stable, re-open?

**Comment by akien-mga** [comment]
@nathanfranke #37192.
