### ISSUE TITLE
iOS simulator build is broken

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#1020]
To reproduce the issue clone the repo and run SCons to build the simulator executable

	scons p=isim bin/godot.isim.tools

A workaround is to run SCons to build the arm executable first

	scons p=iphone bin/godot.iphone.debug

...then run the SCons again to build the simulator executable

**Comment by akien-mga** [comment]
Assuming this issue is no longer valid, as there has been a similar fix in f7b00960 for 1.1-stable.
