### ISSUE TITLE
Node class provides signal for when moved in the node hierarchy

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#10208]
There is already `enter_tree()` and `exit_tree()` signals, but there isn't any signal sent out when a node's position in the hierarchy is changed. This could be a useful feature for tools and procedural generation.

This might be something more for 3.1 or later seeing as how it would appear low on priority and involves modifications to a couple different places in main/node.h, and main/node.cpp (all the different cases where a node would be moving...have to do emit_signal(...) and creating / registering the signal, etc.).

EDIT:
I did notice that there are _notifications related to the situation such as NOTIFICATION_PATH_CHANGED. Perhaps it would be easier than I thought, just emitting the signal whenever that notification is sent out?

**Comment by Zylann** [comment]
note that position change notification is one of the bottlenecks in medium/big games made with Unity (lots of objects involved when transform is modified), so if the same thing is made into a signal too in Godot it should preferably cost only for scripts that use it :3

**Comment by willnationsdev** [comment]
@Zylann This shouldn't be anything affected by a transform of some kind, right? This would be more if a child or parent was moved in the hierarchy to have a different relationship to its node-neighbors. Would that somehow be triggered on simple transformation operations like move/rotate/scale?

**Comment by Zylann** [comment]
ah if you meant reparenting, then ignore me because it's not the same thing.

note that when a node is reparented, its _enter_tree and _exit_tree are called again.

**Comment by willnationsdev** [comment]
oh really? Well then, that simplifies this issue plenty. XD I suspect that means the corresponding signals also get fired? If so, then this can be closed.

**Comment by Zylann** [comment]
that's because changing the parent of a tree in godot just removes the node (exit tree) then adds it back under the new parent (enter tree). not sure about signals though.

**Comment by bojidar-bg** [comment]
There is `NOTIFICATION_MOVED_IN_PARENT`, no signal for that though.

**Comment by akien-mga** [comment]
With both `_exit_tree` and `_enter_tree` being emitted + `NOTIFICATION_MOVED_IN_PARENT`, I get we got things covered here.
