### ISSUE TITLE
Documentation on how to use NOTIFICATION_TRANSFORM_* 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10200]
**bugsquad edit:** it turns out it's a documentation issue, in 3.0 we need to enable those notifications. More details here: https://github.com/godotengine/godot/issues/10200#issuecomment-321216920

-----------

**Operating system or device - Godot version:**
1536cc438128fe4036fa7da5ec305513a781d3c8 (3.0 alpha)

**Issue description:**
NOTIFICATION_TRANSFORM_CHANGED and NOTIFICATION_TRANSLATION_CHANGED are not working for Spatial nodes. The bug was not present in 2.1 version

**Steps to reproduce:**
1. Download sample project
2. Open res://Issues/TransformChangedIssue/TransformChangedIssue.tscn
3. Run it
4. Translate object with `A` and `D` keys
5. Observe that there is no message in the console

**Link to minimal example project:**
[TransformChangedIssue.zip](https://github.com/godotengine/godot/files/1210916/TransformChangedIssue.zip)

**Comment by reduz** [comment]
you have to enable it manually now

**Comment by kubecz3k** [comment]
@reduz oh cool, thanks for letting me know. In meantime I noticed that for `MeshInstance` it's working even if not enabled by user, but I guess it's enabled on the c++ site. Will leave this issue as a documentation reference.

**Comment by kubecz3k** [comment]
The method that need to be used to get those notifications working is `set_notify_transform(true);` There are also others: `set_notify_local_transform` and `set_ignore_transform_notification`

**Comment by reduz** [comment]
It works on meshinstance because it needs to update the mesh on the
server.. i wonder if this should also have an internal notification too...

**Comment by KoBeWi** [comment]
This is already clarified since 3.0.
