### ISSUE TITLE
OptionButton selected value always set to 0 when run

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#10213]
OS: Windows 8.1
2.1.3 (Found it here first)
3 alpha (Also found here, used in my screenshot)

**Issue description:**
So, I set the selected value of the option button (say it is 2), and when run the value reset to 0, the value should be 2 right? But when I run the project the value become 0 and the item showed is the 0th item text.

**Steps to reproduce:**
Add OptionButton to scene,
Add some items,
Change the selected value,
And run the project.

**Link to minimal example project:**
Here is the screenshot, i use the 3.0 version, the same thing happen in 2.1.3 too.
In Editor:
![optionerroreditor](https://user-images.githubusercontent.com/8316851/29151458-7dffb1be-7dab-11e7-832a-c8a787ed0cbd.JPG)
When Run:
![optionerrorrun](https://user-images.githubusercontent.com/8316851/29151462-86b1386e-7dab-11e7-91f1-45c9179614ed.JPG)

**Comment by Noshyaar** [comment]
Can confirm that it's present in recent master df5d01f

Scene file contains correct index.
```
[node name="OptionButton" type="OptionButton" parent="."]
selected = 2
```

Workaround: `select(idx)` in `_ready`

**Comment by bojidar-bg** [comment]
Potentially, related to the fact that `popup` might be still empty when `selected` is being set at https://github.com/godotengine/godot/blob/3121b3a4f4c01744184e952d79f9a56e01bdba41/scene/gui/option_button.cpp#L210-L215

**Comment by Alexander-Alekseev** [comment]
@earlroxas13,
Could you please provide a few more details: what do you mean by 'Add some items'? How do you add them?
According to your screenshot, your OptionButton control doesn't contain any child items. If you add them in a code, then the described behaviour is predictable: you can't set selected item in GUI if you don't have items at all. In this case "workaround" provided by @ghost is a solution.

**Comment by earlroxas13** [comment]
@Alexander-Alekseev 
Yes, the workaround is working. But it mean that you have to attach script whenever you use OptionButton, it's not suppose to be that way right?

I tested on the 3.0 stable and this issue still there.
![ob](https://user-images.githubusercontent.com/8316851/36291943-f63046f4-1300-11e8-8345-f8e3dd251f8d.JPG)
So, if you select the OptionButton in the scene tab, there will be items button on the top of GUI/2D Editor (right after the layout button). If you press the items button, Item List Editor window will appear (like in the screenshot above). in this window you can Add Item to the OptionButton, that's what I mean by 'Add some items'.
So, here is the problem. In my screenshot I add 3 items for the OptionButton, 
index 0: asd
index 1: asda
index 2: dgfgf
and then, I change the Selected property in the Inspector to 2, so the OptionButton in 2D/GUI Editor change its text to the 2nd index text that is dgfgf. It working as expected.
But, if you run the scene, the OptionButton shows the 0th index text, that is asd, it should be showing the 2nd: dgfgf like the one in the 2D/GUI Editor,right? And this is the problem.

**Comment by Alexander-Alekseev** [comment]
@earlroxas13,
OK, now I see, thank you.
I've managed to debug and fix the bug.

Description:
What we want to see is:
- Create OptionButton;
- Add items;
- Select desired item.
Till you are in GUI, the logic flow is correct. When you click Save Scene and/or Run Project the logic flow is:
- Create OptionButton (yes, save/run option creates a new one);
- Select desired item; <-- it fails because there are no items in popup as @bojidar-bg mentioned
- Add items. <-- when you have more than 1 item, this one selects item with index == 0

The root cause is that properties in OptionButton class placed in the order:
1. selected (_select_int method);
2. items (_set_items method).

Engine executes properties in this order once we save scene/run project.

My fix is to change the order. I'll create a pull request.

**Comment by Gibbz** [comment]
Im still hitting this bug on 3.1. 
Has the change made it into 3.1?

**Comment by earlroxas13** [comment]
I test with 3.1 the bug is not happened.
@Gibbz Maybe you change the value with script?
Or anyone can confirm this? @Alexander-Alekseev

**Comment by Gibbz** [comment]
I found I was accessing it wrong.
The issue im having with this is that when I delete an entry, the indexes dont look to get updated. And it keeps the deleted object in the selected field.
Is there a way to return the selection to be blank? And also a way for the user to select nothing?

Ill have to look into it more later, I may just be doing something wrong...
