### ISSUE TITLE
The size of the file after import of Godot 3.0 is 5 times the size of the original file

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#10218]
**Operating system or device - Godot version:**
godot 3.0   windows

The size of the file after import of Godot 3.0 is 5 times the size of the original file

**Comment by Hinsbart** [comment]
What File? ^^
A Texture? Could be expected, due to change of compression algorithm.

**Comment by cjmxp** [comment]
Yes, it's texture. The import panel opens and no arguments can be set
