### ISSUE TITLE
Sound sample not audible in AnimationPlayer editor

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#1021]
Concerns: 1.0 stable

I have keyframed play on a SpatialSamplePlayer in my Animation.
It works when the game is running, but during editing of the animation, when I press play there is no sound. This makes timing a bit difficult.

**Comment by akien-mga** [comment]
Is this bug still valid in the current master branch?

**Comment by akien-mga** [comment]
Closing as there has not been any activity on this issue since 1.0, and Godot has evolved a lot since then.
