### ISSUE TITLE
Audio Mixer Usability Improvement

### ISSUE THREAD

**Issue by vinod8990** [godotengine/godot#10215]
This is a suggestion for AudioMixer UI improvement.

Right now the mixer is like this.
![audio_bus_layout](https://user-images.githubusercontent.com/434987/29155630-f71099e2-7dba-11e7-83ff-d88a5de5a5fc.png)

On a first glance, there are several buttons on the top which don't make a good sense of what they will do.
Of course, after playing with those for some time the developer will realize what they do and be ok with it. However, I propose a new interface which is as shown below.

1. Remove all those not-so-informatory buttons on the top.
![1](https://user-images.githubusercontent.com/434987/29155731-81ca41f0-7dbb-11e7-9db7-ec9198ac3ce6.png)
Why?
Load, Save As, Default, Create. These button functions can be invoked by several actions from the developer who is used to Godot interface.
![2](https://user-images.githubusercontent.com/434987/29155823-f66e5d16-7dbb-11e7-8a34-2b14cd9f4c57.png)

Load - Double click on an Audio Bus resource in the File browser
Save As - Use the Save button in the Resource's Inspector
Default - Not needed because the developer can create a default bus and double click on that to open it.
Create - Use the New Resource button in the Inspector
(If problems with Resource-Save for Audio Bus Layout, then a bug report is required to fix that before this)

2. Add Bus buttons should be like a big button to the right side, like this.
![3](https://user-images.githubusercontent.com/434987/29155890-60a0fb44-7dbc-11e7-9519-584c90873023.png)
c1. Bus name editing text focus and defocus should be distinguishable.
c2. Add a 3-dot button and use this for a popup menu
c3. The popup menu should contain Duplicate and Delete buttons. Right-clicking on a bus is not user-friendly because the bus does not look like it has a right click menu.
c4. The big Add bus button

**Comment by djrm** [comment]
I dont understand c1, to me they look perfectly distinguishable, c2 and c3 are basically the same, and c4 is not really necessary, since even if you remove the top buttons, removing the current bus layout name, does not seem to be a good idea, so i think the only valid point is c2

**Comment by vinod8990** [comment]
C1 does not behave like a text field in other places like property inspector. Typing and hitting enter does not seem to defocus.
C4 when adding the big add bus button, we have space for the current bus layout name on the top left?
