### ISSUE TITLE
Make sprite Alt + drag-drop window to a better looking one.

### ISSUE THREAD

**Issue by vinod8990** [godotengine/godot#10226]
**Operating system or device - Godot version:**
Linux Mint 18 Sarah

**Issue description:**
Popup window for Alt+drag drop sprite is not looking good.

**Steps to reproduce:**
Drag a texture from the FileSystem panel to the 2D Scene while holding Alt.
You can see the popup like this.
![1](https://user-images.githubusercontent.com/434987/29174467-0d1457f8-7e04-11e7-9397-be7a8d1f505b.png)

The interface should have proper margin, padding and size alignments.

**Comment by djrm** [comment]
ugh, let me check this one.
