### ISSUE TITLE
Tree node, wrong row selection display when rmb selection is active and column title is shown

### ISSUE THREAD

**Issue by penguinroad** [godotengine/godot#10229]
**Operating system or device - Godot version:**
Ubuntu 16.04 64 Bit, 
Godot_v2.1.4-beta_20170731_x11.64

**Issue description:**

I create a tree, set it up, enable set_allow_rmb_select(true), display column titles, then run the project
I right click to select a cell. The selection is in wrong place (one row below) but return correct data
**Steps to reproduce:**
just run the example and try to choose a cell by right clicking it

**Link to minimal example project:**

[tree.tar.gz](https://github.com/godotengine/godot/files/1215291/tree.tar.gz)

**Comment by kubecz3k** [comment]
@penguinroad would be really nice if you could test this on main branch as well

**Comment by KoBeWi** [comment]
Fixed in 3.0
