### ISSUE TITLE
Multimesh glitches

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10220]
**Operating system or device - Godot version:**
windows, e8192d4

**Issue description:**
i can't even formulate the title, because i don't understand what causes this

i'm trying to create a field of tiles with multimesh, but it fails
i don't understand really whether multimesh just renders only a part of instances or transformations are applied in a wrong way.

**Steps to reproduce:**
open sample project
1. try running as is
2. try setting count to only "size" (not square size)
3. try changing Y coordinate from zero to one
4. try running several times

for me everytime it can display different results even without changing the code

**Link to minimal example project:**
https://www.dropbox.com/s/dsnm2r4bomv23gy/multimesh%20field.zip?dl=0

**Comment by kubecz3k** [comment]
Hello, downloaded your sample and you have bug in your code. Version that works:
```
	for x in range(size):
		for y in range(size):
			print("(x*size)+y: ", (x*size)+y)
			var t = Transform(); # = mm.get_instance_transform((x*size)+y)
			mm.set_instance_transform((x*size)+y, t.translated(Vector3(x*cell_size, 0, y*cell_size)))
```
