### ISSUE TITLE
Particles 3D, Shape mode "points": points can be defined only in distance from 0 to 1 from the origin

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10235]
**Operating system or device - Godot version:**
e93ce33 Gpu: Gtx1060

**Issue description:**
With R/G/B color pixels we can code position of emission points in `points' and 'directed points` emission shapes. But it's impossible to move them They can have position values only from 0 to 1 in local world coords. 
Take a look at the screen:
![part_pos](https://user-images.githubusercontent.com/6129594/29184204-b37cea28-7e05-11e7-933d-923c493a9ac5.png)

Yellow box visibility is not very big (radius around 2 I think), lets say I have some bigger object in the game like boss and I wanted to use one particle emitter to have some nice effect. Unfortunately distance from the center cant be more than 1 (but only in positive directions). 
Maybe we could have additional factor to scale this distance?

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by BrainBlasted** [comment]
The image linked under part_pos isn't properly formatted, and seems to not point to a proper image.

**Comment by kubecz3k** [comment]
@BrainBlasted oh sorry about that. It's a result of editing/opening multiple issues at once :)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/815, as feature proposals are now tracked in the Godot proposals repository.
