### ISSUE TITLE
Particles 3D: emission shape "directed points" is broken

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10232]
**Operating system or device - Godot version:**
e93ce339dcdf4e9ade63286cfa04cdd4b5a8ecd4 Gpu: Gtx1060

**Issue description:**
EmissionShape `directed points` inside particles process material don't seems to behave correctly. I have set number of particles points to 3 and this texture as an input for positions as well as directions: 
![input](https://user-images.githubusercontent.com/6129594/29181656-42f15ee6-7dfc-11e7-9702-09d40012fdda.png)
Result:
![directedparticles](https://user-images.githubusercontent.com/6129594/29181699-693d8b38-7dfc-11e7-9ff1-c96330372179.gif)

There are two problems:
1. One of the emitters is emitting very short living particles (~=1 frame)
2. This is visible the most in EmissionShape `points` (the more without normal texture). Emission is very unbalanced/unregular. Sometimes one from emission points is not emitting anything for second or half while other is emitting more particles

**Steps to reproduce:**
1. Open sample project.
2. Open res://Tests/Particles/DirectedParticles.tscn scene

**Link to minimal example project:**
[IssueDirectedParticle.zip](https://github.com/godotengine/godot/files/1215723/IssueDirectedParticle.zip)

**Comment by gamergamesz** [comment]
plus align and rotation is also broken
plus transparency is also seems to be broken

**Comment by gamergamesz** [comment]
![screenshot 75](https://user-images.githubusercontent.com/13883739/29182840-07237684-7e1e-11e7-9ff6-9efaece43c0d.png)
plus color and hue variation and animation doesn't seems to have any effect in particle material

**Comment by kubecz3k** [comment]
@gamergamesz please stop. This issue is about different subject, you can open new issues, (they are already issues for those things). I'm bugtriaging particle issues right now, I will also create tracker so if you know any not submitted issues please open new ones as soon as possible.

**Comment by reduz** [comment]
This seems to be an issue (or not, I dont know) in the default particles material.
This material is generated as shader code and the relevant bit is here:
https://github.com/godotengine/godot/blob/master/scene/3d/particles.cpp#L619

**Comment by matrem** [comment]
The only bug I see on this one is this one : 
https://github.com/godotengine/godot/issues/14333

**Comment by akien-mga** [comment]
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by reduz** [comment]
will leave as hero wanted, since does not seem too serious or difficult to me

**Comment by pgruenbacher** [comment]
Current master does not replicate this issue anymore.

![fix](https://user-images.githubusercontent.com/3332598/45580582-cc5fc600-b860-11e8-9814-2c51e0ef3a76.gif)

**Comment by akien-mga** [comment]
There still seems to be more particles on the blue axis than on the other ones, is that expected or should it be 1/3 on each?

**Comment by pgruenbacher** [comment]
![ezgif-4-d27fb45307](https://user-images.githubusercontent.com/3332598/45581323-ddf99b80-b869-11e8-9fd6-c5302c65f6cc.gif)

not it's just the timing of the gif

**Comment by akien-mga** [comment]
Thanks, closing as fixed then.
