### ISSUE TITLE
range type/method does not accept negative values or count down.

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#10248]
**Operating system or device - Godot version:**
Windows 10x 64 Godot Alpha 1

**Issue description:**
the "range" type/method does not accept a negative value. It also cannot count down only upwards

**Steps to reproduce:**
create a for loop using the rage method. input negative value or a higher start value and a lower final value.

**Link to minimal example project:**
example. for num in range ( 0, -10 ) or for num in range ( 10, 5 ).

**Comment by Noshyaar** [comment]
Use the third param? `range(0, -10, -1)`

**Comment by vonflyhighace2** [comment]
so it defaults to a positive increment?

**Comment by Noshyaar** [comment]
Yes. I think that's how it is in Python too.

**Comment by vonflyhighace2** [comment]
OK so i think I found the real issue. It seems that floats that are not whole numbers are not supported as values. range( 10, 5,0.5) don't seem to work.

**Comment by Noshyaar** [comment]
You mean `range(10, 5, -0.5)`? I don't think using non-integer in `step` is possible.

**Comment by akien-mga** [comment]
Indeed, non integer steps are not supported.
