### ISSUE TITLE
TryAcquireSRWLockShared in RWLockWindows is not available on Windows Vista

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#10243]
Win Vista x32  Godot v3.0 Alpha1

When I run "Godot 3.0 alpha 1", a window appears. With the message (The entry point to TryAcquireSRWLockShared procedure and not found in library DLL KERNEL32.dll) and nothing works.

**Comment by kubecz3k** [comment]
Also let us know what's your gpu

**Comment by bruvzg** [comment]
[TryAcquireSRWLockShared](https://msdn.microsoft.com/en-us/library/windows/desktop/dd405524(v=vs.85).aspx) is Windows 7+
https://github.com/godotengine/godot/blob/df61dc4b2bd54a5a40c515493c76f5a458e5b541/drivers/windows/rw_lock_windows.cpp#L50

**Comment by akien-mga** [comment]
That code was added by @reduz in 263d5fcf.

If it's Windows 7+ and we want to keep supporting Vista, we'd need an `#ifdef _WIN32_WINNT >= 0x0601 // Windows 7+` and `#else` with equivalent Vista code (or noop if none is available).

**Comment by vnen** [comment]
A preprocessor condition is kind of pointless since we always compile with `_WIN32_WINNT = 0x0600`

I wonder if it's worth the trouble to still support Vista. It's a 10-year old OS, used [less than XP nowadays](https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers). Microsoft has [ended the support for it](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet) in April this year.

**Comment by reduz** [comment]
If Microsoft support has ended, I suggest we drop it. Read/Write locks are
a great optimization for our use case

**Comment by OlexiyKravchuk** [comment]
The lack of support for Vista, makes me completely overboard. I do not have the resources to buy a new one. It's too bad ...

**Comment by reduz** [comment]
@OlexiyKravchuk We will keep supporting it in 2.x, but Vista is dangerous to run now, given Microsoft has ceased all support for it. You won't get any security updates...

**Comment by akien-mga** [comment]
I had a quick look at what other projects using TryAcquireSRWLockShared did, most threads date back to 2015 and end up with developers deciding to drop support for Vista, so I guess we're not alone.

So I agree about dropping support for Vista in Godot 3.0, though it saddens me as I expect @OlexiyKravchuk is not our only Vista user. We just need to bump the number to `0x0601` here: https://github.com/godotengine/godot/blob/master/platform/windows/detect.py#L114-L115
