### ISSUE TITLE
Project manager UI displaced when minimized because of long project paths 

### ISSUE THREAD

**Issue by rayosdev** [godotengine/godot#10245]
**Operating system or device - Godot version:**
Windows10 64 - Godot 2.1.2 stable

**Issue description:**
- Opened up godot, 
- it opens project manager in minimized mode, and button on the right are off the screen. 
- have to maximaze project to access the buttons

**Steps to reproduce:**
Make a project with a long path name and open project manager

**Link to minimal example project:**
<its the project manager - no project to opne>

**Comment by bojidar-bg** [comment]
Can confirm on master/3.0 as well:
![image](https://user-images.githubusercontent.com/5276727/29202873-de24950e-7e74-11e7-94d2-d58d17f7a566.png)
