### ISSUE TITLE
No specularity coming from a Directional Light

### ISSUE THREAD

**Issue by Guillaume201** [godotengine/godot#10250]
Godot 3.0 alpha1
Windows 10 64 bits
NVIDIA GTX 980

An object lit by a directional light do not display any specular highlight, only diffuse. Changing the value "Specular" in the directional light settings has no effects.

EXEMPLE:
On the following screenshot, a directional light shine a red light with specular set at 1 while a OmniLight shine a blue light and as you can see, the object receive specularity only from the OmniLight.

![image](https://user-images.githubusercontent.com/1441602/29201473-cde9938a-7e5e-11e7-9cea-c68ca5740811.png)

**Comment by HummusSamurai** [comment]
Closed by https://github.com/godotengine/godot/pull/12169?

**Comment by bojidar-bg** [comment]
Yes, marking as closed as per #12169's description.
