### ISSUE TITLE
Multimesh rendering issues in grid like setup

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10253]
godot version: e8192d4

here is pbr materials (toon settings, because default looked way to dark)
![pbr](https://www.dropbox.com/s/d5jeqsfrwdgmp7h/pbr.png?raw=1)
and here is simple diffuse shader (just aplying texture color)
![diffuse](https://www.dropbox.com/s/c6qcduaas89gthe/diffuse.png?raw=1)

second looks much better, but still has that brown halo. also creates sort of growing seams between tiles

turning on 'unshaded' creates more interesting stuff
![unshaded](https://www.dropbox.com/s/0wgbxn5po2tbixt/unshaded.png?raw=1)
seems like back faces render over the top

the color of that halo is set by the color of side faces (altering texture color here, changes halo color)

**Comment by akien-mga** [comment]
OS, GPU, driver?

**Comment by curly-brace** [comment]
well. may be i should add here a sample project. windows, gt710, latest driver (updated yesterday). i will post a project just in a minute

**Comment by kubecz3k** [comment]
related (maybe even duplicate) issue: https://github.com/godotengine/godot/issues/10149

**Comment by curly-brace** [comment]
here is a sample
https://www.dropbox.com/s/outbjwqr6vxkb0p/render_sample.zip?dl=0

**Comment by curly-brace** [comment]
that's not GridMap, that is MultiMesh. but i think this is not related

**Comment by curly-brace** [comment]
@akien-mga i don't think that this is windows/nvidia only bug

**Comment by akien-mga** [comment]
Well until someone confirms the bug on another OS or another driver, that's our best guess. Most rendering issues are driver-related, and drivers are OS-specific.

**Comment by akien-mga** [comment]
You can very well imagine that "rendering is broken" is a false statement when it works great for most users (check the recent video showcasing rendering features). You can trust bug triagers to do their job as it should be done, we have experience :)

**Comment by curly-brace** [comment]
i indeed do not insist 😃 but there are some very recent bugreports about rendering issues. but they are concerned pbr. and in my case there is something deeper (because custom shaders do not work either), so i assume that this is very general issue, but it may be treated wrong because of those tags 🙄

**Comment by eon-s** [comment]
Here is on Ubuntu and AMDGPU, 2a6cdfaf9
![exampleonamdgpu](https://user-images.githubusercontent.com/10215987/29243759-6851dd78-7f7d-11e7-8132-e8518ca3703a.png)

**Comment by volzhs** [comment]
Ubuntu 16.04 / NVIDIA GeForce GTX 670 with 376.66 proprietary driver ff2cb35b90f5661d1bb5fb00fa657a9539449be0

![image](https://user-images.githubusercontent.com/8281454/29243924-6d2a6766-7fe6-11e7-9d91-c2cf39c3f2c6.png)

**Comment by curly-brace** [comment]
i've just were experimenting with shaders. and found out the same behaviour, back faces were rendered over the front with culling disabled. but when i've placed another sphere inside the sphere that used a shader, everything was fixed.

**Comment by Calinou** [comment]
The texture artifacting issue is being tracked in https://github.com/godotengine/godot/issues/27837. The rest is likely not relevant anymore in Godot 3.2. Please create a new issue if you can still reproduce this.
