### ISSUE TITLE
CubeMap cause crash when non-valid file assigned to its side

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#10251]
Godot 3.0.alpha.custom_build.81dde26

Is not possible to use samplerCube because a cubemap resource can't open any image.

cubemaps are discouraged at now, but it is useful to remain compatibility with many shader code.
thanks

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by marcosbitetti** [comment]
Test in Godot 3.0 RC3....
Add resource CubeMap and try to assign a png file in any side: Godot crash!

**Comment by reduz** [comment]
Given you can import images as resources now, this bug is no longer relevant
