### ISSUE TITLE
Changing .cpp files to .mm files for the iphone and osx platform

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#10263]
Just something that came up today and raising this to have a discussion, see if there are any unwarranted side effects to this and seeing if we could make this change.

For the OSX platform this is mostly already the case but for iPhone many of the classes are implemented as pure C++ classes, especially os_iphone.cpp. This makes it harder to mix objective-c code into the mix which you can't get around on OSX/iOS.
Even where .mm files are used you can't add objective C classes as member variables of the class as the header file is likely to be included in os_iphone.cpp which won't understand the syntax. 

In fact some of the code in the iphone platform in some parts is pretty horrid as a result.

It makes sense to only use objective-c++ files within the platform code. We can subclass Godots C++ classes without issue but add in objective-c member variables and start cleaning up some of the code here.

**Comment by lexum0** [comment]
@BastiaanOlij When this implementation starts can you let me know so I can help with it?
I can even help with cleaning the code, I just don't know how to make the change to include Obj-C code.

**Comment by akien-mga** [comment]
CC @punto- to know if there was a specific reason to use C++ in the first place, or if switch to Obj-C is fine.

**Comment by samgreen** [comment]
@BastiaanOlij I'm curious if I'm headed in the right direction with my Objective-C++ over [here](https://github.com/godotengine/godot/pull/22784).

**Comment by BastiaanOlij** [comment]
@samgreen I'm currently traveling abroad so only had a quick look. Looks like you are heading in the right direction :)

**Comment by Calinou** [comment]
Current status as of `master` https://github.com/godotengine/godot/commit/18c0f0b3ba46caf3f6dda401362bc5993eaf7f8d: 

### `platform/osx` (macOS)

![Filesystem tree](https://user-images.githubusercontent.com/180032/132069152-ca609aa6-fc78-4696-a7ca-f7eeb1ad5898.png)

### `platform/iphone` (iOS)

![Filesystem tree](https://user-images.githubusercontent.com/180032/132069196-07791a4c-5fa1-4510-b54f-2e7acfd32269.png)

@BastiaanOlij Are there more files we can convert to Objective-C(++)?

**Comment by BastiaanOlij** [comment]
Maybe joypad.cpp? I'm not sure how likely it is we'd need to add Obj-C++ code in there. I agree leaving export alone, that's an editor feature.

**Comment by BastiaanOlij** [comment]
Closing this issue as outdated.
