### ISSUE TITLE
[Meta] Site hosted in GitHub

### ISSUE THREAD

**Issue by Plasmmer** [godotengine/godot#10267]

**Comment by reduz** [comment]
no, we are hosting in tuxfamily which is much better, thank you

**Comment by Plasmmer** [comment]
Much better or the team don't want users contributing to the site?

**Comment by bojidar-bg** [comment]
@Plasmmer We are hosting a Q2A instance and an instance of our asset-library there as well. If you really, really want to contribute to the site, you might just get in contact with the community using the other channels, mainly IRC.

**Comment by Calinou** [comment]
The site uses [October CMS](http://octobercms.com/). Unfortunately, websites requiring databases to function are very hard to "open source" (but it is possible, see [nextcloud.com](https://github.com/nextcloud/nextcloud.com); it might not be worth the effort though).
