### ISSUE TITLE
Godot freezes Ubuntu Gnome during startup

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#1028]
Concerns: Godot 1.0 stable, Ubuntu 12.04

It happens about every 10th time I start Godot.
The Godot window displays the Godot face on white background and doesn't continue. Gnome is then frozen and won't react to any input. I can switch to another terminal, kill Godot, but that doesn't help.
I have to kill gnome-session and restart all applications to get back to work.

Is there a log I can attach or activate?

Btw. this has always happened, since I started using Godot. Not a new problem.

**Comment by ScyDev** [comment]
The freeze just happened again. Here is the log:

opening pack /opt/Godot/godot_x11-1.0stable.32, -1, -1
opening pack /home/olo/data.pck, -1, -1
[1;31;40mERROR: _load_recent_projects: [1;37;40mCondition ' err!=OK ' is true. Continuing..:
[0;31;40m   At: tools/editor/project_manager.cpp:523.[0;0;37m
[1;31;40mERROR: _load_recent_projects: [1;37;40mCondition ' err!=OK ' is true. Continuing..:
[0;31;40m   At: tools/editor/project_manager.cpp:523.[0;0;37m
OPENING: /home/olo/Godot Projects/No Rest for the Wicked Ones/Godot Project (::home::olo::Godot Projects::No Rest for the Wicked Ones::Godot Project)
[1;31;40mERROR: add_signal: [1;37;40mType Sprite3D already has signal: frame_changed
[0;31;40m   At: core/object_type_db.cpp:494.[0;0;37m
[1;31;40mERROR: add_signal: [1;37;40mType Sprite3D already has signal: frame_changed
[0;31;40m   At: core/object_type_db.cpp:494.[0;0;37m
[1;31;40mERROR: add_signal: [1;37;40mType Sprite3D already has signal: frame_changed
[0;31;40m   At: core/object_type_db.cpp:494.[0;0;37m
[1;31;40mERROR: add_signal: [1;37;40mType Sprite3D already has signal: frame_changed
[0;31;40m   At: core/object_type_db.cpp:494.[0;0;37m
...
[1;31;40mERROR: add_signal: [1;37;40mType Sprite3D already has signal: frame_changed
[0;31;40m   At: core/object_type_db.cpp:494.[0;0;37m
[1;31;40mERROR: add_signal: [1;37;40mType Sprite3D already has signal: frame_changed
[0;31;40m   At: core/object_type_db.cpp:494.[0;0;37m
attempt set state: (current:3), (sources:res://hero.gd, res://level.gd, res://norest_character.gd, res://zombie.gd, res://zombie_normal.gd, res://zombie_fat.gd, res://zombie_jumper.gd, res://gui_zombie_buttons.gd, res://Control.gd)

**Comment by akien-mga** [comment]
Do you still get this issue in the current master branch @ScyDev?

**Comment by mohaalak** [comment]
@akien-mga : I have ubuntu and I don't have any problem with intel graphics running godot. I think it was fixed with 1.1
