### ISSUE TITLE
[3.0] glTF Import Crash on Armatures

### ISSUE THREAD

**Issue by pcvonz** [godotengine/godot#10291]
**Operating system or device - Godot version:**
Ubuntu - Godot built 11th August

**Issue description:**

Godot crashes, expected it to import a glTF2 model. 

**Steps to reproduce:**
Download the attached blend file, export glTF2, import it into Godot.

**Link to minimal example project:**

[legs.zip](https://github.com/godotengine/godot/files/1219454/legs.zip) ( Ugly model, just learning how to rig stuff ;) )

**Comment by BrainBlasted** [comment]
@pcvonz Can you export from blender making sure export camera is unchecked? I've found godot often chokes on cameras

**Comment by BrainBlasted** [comment]
This seems to be an issue with armatures - without the armature the file imports correctly. Could you test this on your machine? Also, I got a SIGSILL stacktrace out of it: https://hastebin.com/zabezefuqi.coffeescript

**Comment by kubecz3k** [comment]
closing as a duplicate of https://github.com/godotengine/godot/issues/10130. @pcvonz can you share your model and nodes there? Thanks!
