### ISSUE TITLE
Something about physics. But what? "least_deep == -1" (Godot 3.0 alpha1)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#10302]
**Operating system or device - Godot version:**
Ubuntu 16.04, Godot 3.0 Alpha1

**Issue description:**
There is a random hang of the game, due to the fact that the console instantly reports such a mistake 10120 times.
Tell me what this error means?
The release of large spam into the console occurs a couple of minutes after the game starts.
![2017-08-11 22-15-52](https://user-images.githubusercontent.com/11325733/29240835-8df8620a-7f9f-11e7-8728-45c3bff17444.png)

**Steps to reproduce:**
It is not known why this happens.

**Link to minimal example project:**
https://drive.google.com/file/d/0Byzq8eVQ6u1fUDNlRUpSX21uNmM/view?usp=sharing

**Comment by H4kor** [comment]
Was not able to reproduce the bug.
Ubuntu 16.04, Master-Branch (5052cb2).

**Comment by mhilbrunner** [comment]
Can't reproduce this either. Please retry with a recent version (beta build or master branch) and report to reopen this issue if this still occurs.

Bugsquad: This can be closed. :)

**Comment by DimaKiva** [comment]
The beta version does not have this problem.
