### ISSUE TITLE
Debugger gets broken when reading large files

### ISSUE THREAD

**Issue by samuelpedrajas** [godotengine/godot#10308]
**Operating system or device - Godot version:**
Ubuntu 17.04
Godot 2.1.3 & Godot 3 (commit a75623f436c215e107ede321afa08a1897552deb)

**Issue description:**
When I try to read a large file using the File class in GDScript the execution seems to work fine. However, if I set a breakpoint after the line `file.get_as_text()` the debugger gets closed and the next message is shown in the console:

`ERROR: put_packet: Condition ' p_buffer_size + 4 > temp_buffer.size() ' is true. returned: ERR_INVALID_PARAMETER
   At: core/io/packet_peer.cpp:220.
ERROR: _notification: Condition ' cmd.get_type() != Variant::STRING ' is true.
   At: editor/script_editor_debugger.cpp:970.`

Note: this output is from Godot 2.1.3. In Godot 3 the output is the same but the highlighted line in `script_editor_debugger.cpp` is 991 rather than 970.

I noticed this when trying to read a large JSON file (see the attached project `test.zip`). I also tried to remove keys from the JSON file (`tile_info.json` in the project) to check if at some point the debugger stops getting broken. And it does. So I assumed the size of the file has something to do with this issue.

I also tried to avoid the conversion from JSON to Dictionary (this isn't the cause of the issue, but I needed a temporal solution to keep working) by creating a Dictionary object straight away in a GDScript file and pasting the content of the JSON there. The behavior is exactly the same: the debugger keeps getting broken. This is not included in the minimal example project and I have tested it only in Godot 2.1.3.

**Steps to reproduce:**
1. Open the attached project (`test.zip`) with Godot 3.
2. Run the project to check that `tile_info.json` content is printed out correctly.
3. Comment out the line `# breakpoint` and run the project again
4. The debugger doesn't work anymore and the buttons stop responding.

Note: if you remove lines from `tile_info.json` until you've got around 4000 lines everything starts to work fine.

**Link to minimal example project:**
[test.zip](https://github.com/godotengine/godot/files/1219975/test.zip)

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by akien-mga** [comment]
Thanks, closing as fixed then.
