### ISSUE TITLE
minor UI polish: should be able to click and drag to re-order tabs

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#1030]
you should be able to click and drag to re-order tabs.

**Comment by akien-mga** [comment]
Related to #570. We should probably do a tracker for all drag and drop use cases.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
Just confirming that this is still not implemented in the current master branch (but I think @kubecz3k wanted to look into it).

**Comment by kubecz3k** [comment]
@akien-mga yeah it's high on my pr-todo list. I haven't looked into it much yet, but if anyone have any tips/starting points for me I would be obligated.

**Comment by kubecz3k** [comment]
solved by #9510
