### ISSUE TITLE
Cant get pixel-perfect on [Godot 3.0 Alpha1]

### ISSUE THREAD

**Issue by xLordDaniel** [godotengine/godot#10313]
**Operating system or device - Godot version:**
Windows 7 64bit - 3.0 Alpha1

**Issue description:**

![godot alpha1 error](https://user-images.githubusercontent.com/23245138/29244146-d1c9c086-7fb9-11e7-9391-6874e89a01d9.png)

Well, the picture pretty much says everything. 
The problem is the blurry effect created on low res sprite ( as pixel arts), it isnt sharp as it is suppose to be.
I guess it is happens when sprite's X or Y isnt an integer, i tried setting non-integer ( as 20.3 or 108.6) in the X axis, and the effect happened, while it didnt happen when i set it to interger number ( as 50 or 120).
I tried diffrents project settings, and couldn't fix it. I looked for answer in internet, nope.
I did created the same project on the stable version ( the one on Steam), and it worked as wanted.

**Steps to reproduce:**
In Project Settings, Display -> Window -> [ enter low width and height ( in my project it is 240x160)]
Stretch mode -> 'viewport'
Aspect -> 'Keep'

**Link to minimal example project:**

[Pixel blur bug - godot 3.0 alpha1 project.zip](https://github.com/godotengine/godot/files/1220066/Pixel.blur.bug.-.godot.3.0.alpha1.project.zip)

**Comment by Kwarf** [comment]
Try selecting your spritesheet in the FileSystem view, then go to the Import-tab and uncheck Filter, then hit Reimport.
![tex_filter](https://user-images.githubusercontent.com/4023218/29244411-b065ba46-7fb7-11e7-8ed5-a73de86a28d0.png)

**Comment by xLordDaniel** [comment]
And it is working now. 
I did heard that there is something called Filter somewhere in the engine, but couldn't find it ( the UI is diffrent from old versions).
Thank you.
