### ISSUE TITLE
Graphic artifacts in Linux with an NVIDIA Optimus setup

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#10311]
**Operating system or device - Godot version:**
Godot master branch 3bea3256f5def126b2b6d639ed70c4ddc3990344

**Issue description:**
Running the [material_testers](https://github.com/godotengine/godot-demo-projects/tree/master/3d/material_testers) demo in Arch Linux will show the following artifacts:

Using the Intel video card:

```
00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09)
        Subsystem: Lenovo Device [17aa:3977]
        Kernel driver in use: i915

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 17.1.6
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.1.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.1.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

![godotartifacts](https://user-images.githubusercontent.com/8337880/29243742-9ccc0942-7f74-11e7-8f0d-c523c0c2a64d.png)

Using the discrete video card with proprietary driver:
```
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF108M [GeForce GT 630M] [10de:0de9] (rev ff)
        Kernel modules: nouveau, nvidia_drm, nvidia

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 640M LE/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 384.59
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.0 NVIDIA 384.59
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
```

![godotnvidiaartifacts](https://user-images.githubusercontent.com/8337880/29243762-0dbcff4e-7f75-11e7-8468-75b4a981419d.png)

I expected to see what's shown in the [patreon video](https://www.patreon.com/godotengine)

**Steps to reproduce:**
Run the [material_testers](https://github.com/godotengine/godot-demo-projects/tree/master/3d/material_testers) demo

**Comment by HummusSamurai** [comment]
#10149, #10292, #10253 It's been confirmed, but the lead dev is currently going through the bugs from oldest to newest, so might need a couple more days.

**Comment by Rubonnek** [comment]
@HummusSamurai Thanks for pointing it out. I was just searching now and stumbled upon some of those issues you mentioned. This seems like a duplicate now. The only difference being the hardware and the fact that I'm getting the grid-like artifact plus the metallic texture not getting rendered properly like in #10292 but both at the same time as can be seen in the first picture above. I have not been able to find a screenshot with those two problems at the same time in a previous issue so far.

**Comment by maxim-sheronov** [comment]
Hi. I want to just confirm this issue. On Arch linux with Nvidia Gtx-970 and on Windows 10 with Gtx-660-Ti

**Comment by vnen** [comment]
This is the same issue as #9525. Closing as duplicate.
