### ISSUE TITLE
Mesh's color is incorrect with rough material

### ISSUE THREAD

**Issue by cutepig49** [godotengine/godot#10316]
**Operating system or device - Godot version:**
Windows7 64bit
https://bintray.com/calinou/godot/editor/2017-08-12.b034c4e#files

**Issue description:**

It's the same scene, but it looks different in nightly build (above) and alpha1 build (below).

![nightly](https://user-images.githubusercontent.com/3340057/29245841-17ad4da2-8019-11e7-9d80-63848ed82d7d.PNG)
![alpha1](https://user-images.githubusercontent.com/3340057/29245842-1d1c1674-8019-11e7-8cf7-79eb0015c5cb.PNG)

**Steps to reproduce:**
Create a MeshInstance with CubeMesh, give it a SpatialMaterial, and set the material's roughness to 1.0.

**Comment by cutepig49** [comment]
I think the bug is fixed in today's(2017-08-18) build (https://bintray.com/calinou/godot/editor/2017-08-18.445b0ab#files)
I guess it's time to close the issue.
Thanks and good job guys!

![08-16](https://user-images.githubusercontent.com/3340057/29460599-27217060-845b-11e7-8633-97a0fa0890f3.PNG)
2017-08-16 build

![08-18](https://user-images.githubusercontent.com/3340057/29460604-2ad52e90-845b-11e7-8d52-7f1e6f0cecd6.PNG)
2017-08-18 build

**Comment by akien-mga** [comment]
Probably fixed by 3a4ff34.
