### ISSUE TITLE
KinematicBody2D.get_collision_count() is not working correctly

### ISSUE THREAD

**Issue by xLordDaniel** [godotengine/godot#10314]
**_bugsquadedit:_** It seems `KinematicBody2D.get_collision_count()` is not working for some reason. It might be somehow related to the fact there is no `KinematicBody2D.is_colliding()` method in 3.0 (not sure why?). Uploading reproduction project below, since original one is not compiling:
[Issue: KinematicBody2D_collision_count().zip](https://github.com/godotengine/godot/files/1234371/Issue.KinematicBody2D_collision_count.zip)
Tested on 1a92906b681735a5a2acfd98e3d6a4c75a7f6115
edit2: from @novemberist comment it seems it's not working only when used together with `move` (and working with `move_and_slide`)

-----

**Operating system or device - Godot version:**
Windows 7 64bit - Godot 3.0 alpha1

**Issue description:**

This video shows the bug:
https://www.youtube.com/watch?v=hZOAgQEiuYA
If i press right arrow key, it suppose to make the sprite move right, at the same speed.
but for some reason, the sprite keeps slowing down.
The same code is running fine on the stable ( steam ) version of Godot engine.

**Steps to reproduce:**
Make KinematicBody2D, add a Sprite and a CollisionShape2D as childs.
add to the KinematicBody2D this code: 
``` GDScript
extends KinematicBody2D

const GRAVITY = 16.0
const WALK_SPEED = 20
var velocity = Vector2()
func _ready():
	set_process(true)
	set_fixed_process(true)
	pass
func _process(delta):
	if (Input.is_action_pressed("ui_left")):
		velocity.x = - WALK_SPEED
	elif (Input.is_action_pressed("ui_right")):
		velocity.x =   WALK_SPEED
	else:
		velocity.x = 0
	
func _fixed_process(delta):
	velocity.y += delta * GRAVITY
	var motion = velocity * delta
	motion = move(motion)
	
	if (is_colliding()):
		var n = get_collision_normal()
		motion = n.slide(motion)
		velocity = n.slide(velocity)
		move(motion)
	
```
Save that object. Create new scene, add a new node, and than add this object as his child.
To the root node ( the new node of the scene) add StaticBody2D and add it a CollisionShape2D. 
Than run the scene and press left arrow key or right arrow key and see the sprite slowing down after a while.
**Link to minimal example project:**

[Slowdown movement bug - godot 3.0 alpha1 project.zip](https://github.com/godotengine/godot/files/1220084/Slowdown.movement.bug.-.godot.3.0.alpha1.project.zip)

**Comment by timoschwarzer** [comment]
Can you please reformat your code? Makes it easier to read it. ;-)

**Comment by novemberist** [comment]
You might want to consider using move_and_slide() for your use case, by the way. Not sure if this issue is due to a bug or a problem with your code, though.

**Comment by xLordDaniel** [comment]
Tried changing to move_and_slide(). The bug doesnt appear.
Hmm. I think that the move() function is bugged, as from what i read online, there are no diffrents between move() and move_and_slide() when the there is no slope.
And my code is from here : http://docs.godotengine.org/en/stable/learning/features/physics/kinematic_character_2d.html
It does work fine on the stable ( steam) version of the engine.

about the API changes, I got no idea. I'm new to Godot engine.

**Comment by novemberist** [comment]
I changed (is_colliding()) to (get_collision_count() > 0) so I could run the example project on the latest build and the movement on the floor seems to work fine. there are sone other issues though.

I think the examples from the documentation apply mostly to Godot 2 and will be updated once Godot 3 is be released. So there's not necessarily a bug if code from older versions doesn't run properly.

**Comment by xLordDaniel** [comment]
Well maybe (cant test it right now) , but if i even remove the part of  'if(is_colliding())' from the code, the bug stays.
like that:
`
func _fixed_process(delta):
	velocity.y += delta * GRAVITY
	var motion = velocity * delta
	motion = move(motion)
`
if i change the move() to move_and_slide() it works right.
it seems like something wrong with move(). i would check later the projects the engine came with, to see if the bug exists there.

**Comment by kubecz3k** [comment]
The issue is in your code. You are increasing gravity each frame, but you never reset it:
![gravity](https://user-images.githubusercontent.com/6129594/29458154-01140744-841e-11e7-86cf-8b1cf21a4c8a.gif)

**Comment by kubecz3k** [comment]
Oh actually it's not, sorry! It seems `(get_collision_count()>0)` is never true for some case.

**Comment by kubecz3k** [comment]
Uploaded updated reproduction project to the first issue together with brief description

**Comment by novemberist** [comment]
get_collision_count() somehow only reports collisions when using move_and_slide(), but not when using move()

**Comment by djrm** [comment]
@novemberist, @xLordDaniel this is the expected behavior, the new method, which by the way no is called move_and_collide, puts the collision data in the specified collision object, and actually stops on collision, if you want to get that kind of behavior with the benefits of move_and_slide, please use move_and_slide with bounces = 1.

I think this can be closed now

**Comment by novemberist** [comment]
@djrm Not sure I understand you correctly, but get_collision_count() not reporting collisions when using move_and_collide() is expected behavior? I con't get the logic behind that...you say it stops on collision, which means it should at least report 1 collision at some point (which it doesn't)

**Comment by djrm** [comment]
@novemberist Thats because the move_and_collide returns such collision, the collisions list is only used by move_and_slide, actually the name of the function is now called get_slide_collision, but yeah this is not currently implemented in kinematicBody2D, but will be soon.

**Comment by toger5** [comment]
I think there is a similar issue with kinematicBody (not 2d)
I cant get collusion... And is_of_floor() returns false even when it obviously is.
So i can't really reset speed on -y axis.

If this is expected behaviour i think i dont really understand how you are supposed to use kinematic bodies

**Comment by reduz** [comment]
Have not ported new API to 2D

**Comment by djrm** [comment]
@reduz i have a PR for that. #11133

**Comment by reduz** [comment]
Awesome
