### ISSUE TITLE
Per tile z-index in tilemap 

### ISSUE THREAD

**Issue by ducklin5** [godotengine/godot#10321]
Can we add a z-index option to the tileset? so it wont be necessary to make 2 separate tilesets for floor and walls in 2d.

**Comment by reduz** [comment]
that's a pretty good idea, wonder why we didn't do this before..

**Comment by elvircrn** [comment]
Hi, I saw the junior job tag and would be interested in implementing this feature. I've never actually done any open source work and I'm wondering if have to wait for somebody to assign this feature request or something like before getting started.

**Comment by vnen** [comment]
@elvircrn each project has its own guidelines. Here we just ask you to comment on the issue saying you are working on it, to avoid potential duplicate work (also comment if you stop working on it for some reason). We don't use GitHub assignments since those can be used only by members.

**Comment by blurymind** [comment]
Hi, z-indexing could also help for making isometric games with platforming action and jumping

for example equinox:
https://youtu.be/HBswql-rS7I?t=2m12s

Another such great game is Landstalker:
https://youtu.be/2PRFSPWmneE?t=51m36s

This was discussed here
https://www.facebook.com/groups/godotengine/permalink/1091205531016040/?comment_id=1091524017650858&ref=notif&notif_t=group_comment&notif_id=1503811786830103

and also 
https://godotengine.org/qa/17637/isometric-game-with-platform-height-and-jumping-platforming

**Comment by Zylann** [comment]
Can you show an example screenshot where you need this? I was able to do walls and floor without problem by making two tilemaps, but only ONE tileset, so I'm curious why you would need TWO tilesets...

**Comment by vnen** [comment]
Yeah, this looks like something better fitted in the TileMap, not the TileSet. Still, maybe only useful if the map cell size doesn't match the tile size perfectly so you can have overlapping tiles.
