### ISSUE TITLE
Navigation2D returns same point twice in get_simple_path()

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#10324]
**Operating system or device - Godot version:** 
Linux x64, happens on 2.1.3 **and** latest 3.0.

@godotengine/pr-mergers please cherry picked to 2.1 in case of a PR 

**Issue description:**

When using `Navigation2D.get_simple_path()` (with the `optimized` argument set to false) the points returned sometimes contains *two* identical points, requiring a workaround to make simple path follow scripts work.

The first position returned is *always* the starting position, but sometimes when the starting position is the same a *previously returned position*, this position will be in the returned point-list **twice**.

A theoretical 1-dimensional example:
You want to go from 0 to 3, the returned points are `[0, 1, 2, 3]`.
Then if you are at **exactly 1** the returned points sometimes are `[1, 1, 2, 3]`.

**Steps to reproduce:**
I included an example project down below with many comments.
The example project is using **3.0**, but I know that this problem exists in 2.1.3 too.

The example projects lets the sprite find the mouse position. <kbd>enter</kbd> toggles the following of the path.

To reproduce without the example project:
 - set up a Navigation2D with NavigationPolygonInstance
 - use `get_simple_path()` on every frame (in practice needed for moving enemies, for example)
 - move along the returned path, only moving towards the next position returned earlier.
 - observe that some points occur multiple times

**Link to minimal example project:**

[nav_demo.zip](https://github.com/godotengine/godot/files/1221052/nav_demo.zip)

**Comment by plucian** [comment]
is this the same as this:
https://github.com/godotengine/godot/issues/8184 ?

**Comment by karroffel** [comment]
@plucian seems like it. For me this workaround works, but I think it shouldn't be there in the first place 😄

**Comment by RandomShaper** [comment]
I'm checking this.
