### ISSUE TITLE
[2.1.4] Inspector doesn't update when updating selection from plugin

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#10323]
**Operating system or device - Godot version:**
Linux, 2.1.4-beta (July 31)

**Issue description:**
When selecting a 2D node with `get_selection().add_node()` from an EditorPlugin, the inspector doesn't update and show the properties of the newly selected node. Additionally, if the new node has some special editor controls, they don't show up. (for example Polygon2D doesn't show its verticies).

**Comment by ricpelo** [comment]
Maybe related to #9408?

**Comment by KoBeWi** [comment]
Fixed with the inspector upgrade in 3.1.
