### ISSUE TITLE
GDNative api.json does not provide additional arguments of getters/setters

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#10329]
ClassDB supports registering properties as procedures that are called with additional (bound) parameters. For example, for `GeometryInstance` we have:
```cpp
ADD_PROPERTYI(PropertyInfo(Variant::BOOL, "visible_in_all_rooms"), "set_flag", "get_flag", FLAG_VISIBLE_IN_ALL_ROOMS);
ADD_PROPERTYI(PropertyInfo(Variant::BOOL, "use_in_baked_light"), "set_flag", "get_flag", FLAG_USE_BAKED_LIGHT);
```
This means set_flag and get_flag should be called with additional parameters to get/set the properties. However, api.json generated with `--gdnative-generate-json-api` switch doesn't include this information:
```json
{
  "name": "visible_in_all_rooms",
  "type": "bool",
  "getter": "get_flag",
  "setter": "set_flag"
},
{
  "name": "use_in_baked_light",
  "type": "bool",
  "getter": "get_flag",
  "setter": "set_flag"
}
```

**Comment by neikeq** [comment]
You can get the additional parameter via `ClassDB::get_property_index` (see #10117)

**Comment by karroffel** [comment]
... *passive-aggressive "pr welcome" label added*....
