### ISSUE TITLE
Vertex shader failed to compile [AMD, Windows 10, Regression from #9b9a723]

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#10332]
**Operating system or device - Godot version:**
Windows 10 (AMD FirePro D300); master https://github.com/godotengine/godot/commit/9575dbdf788e8a5154b3ec2f66913e731ac02850

**Issue description:**
Displays nothing but a white screen and following errors:
```
ERROR: _gl_debug_print: GL ERROR: Source: Shader Compiler	Type: Error	ID: 2000	Severity: High	Message: glCompileShader failed to compile a GLSL shader with the following shader info log: 'Vertex shader failed to compile with the following errors:
ERROR: 22:1: error(#228) Type should be float or int
ERROR: 23:1: error(#228) Type should be float or int
ERROR: 24:1: error(#228) Type should be float or int
ERROR: error(#273) 3 compilation errors.  No code generated
At: drivers\gles3\rasterizer_gles3.cpp:122
...
```

Default precision qualifiers for samplers (added in https://github.com/godotengine/godot/commit/9b9a723c771a0146cb16e23c3dac744af312bad7) only allowed in GLSL 4.40+, and Godot shaders are `#version 330`.

Replacing version with `#version 440` or removing `precision highp sampler*` lines fixes the problem, looks like AMD driver has too strict GLSL validation.

[GLSL 3.30 spec](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.3.30.pdf#page=49)
[GLSL 4.40 spec](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.40.pdf#page=95)

**Comment by bojidar-bg** [comment]
CC @Faless (yes, you managed to break it :wink:)

**Comment by Faless** [comment]
> yes, you managed to break it :wink:)

:tada: .
If I remember correctly that was for the non webassembly version of the export.
I'll double check, thanks for reporting

**Comment by Faless** [comment]
> for the non webassembly version

No, actually also the webassembly version complains:

`ERROR: 0:17: '' : No precision specified (sampler)`

**Comment by Faless** [comment]
We could simply use `#ifdef`s to check if it's an HTML5 export.
@reduz ?

**Comment by bruvzg** [comment]
@Faless precision qualifiers are required for WebGL; useful, but not required for OpenGL-ES; and useless for desktop OpenGL.
Putting this inside an `#ifdef GL_ES` should work for all platforms.
