### ISSUE TITLE
Endless error messages apparently caused by playing an .ogg file as a sound effect

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#10330]
**Operating system or device - Godot version:**
Ubuntu Linux 17.04 64bit
Godot master branch pull 9575dbd.

**Issue description:**
Initially, I'd been having issues where imported non-looping .ogg files used as sound effects would stop looping .ogg files from playing. So I'd attempted to recreate something to use to demonstrate this issue.

That *seems* to have been fixed. *However*, what happens with this is that:
1 - Music plays. A timer is set, when it times out it plays a .wav sound effect, then is restarted.
2 - When the timer times out the second time it plays a .ogg sound effect.

At 2 is when the debugger tab fills up with endless "0:00:24:0077 - Condition '!active' is true." error messages.

"ERROR: _mix_internal: Condition ' !active ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:38." appears on the terminal.

**Steps to reproduce:**
See attached.

**Link to minimal example project:**
[10330_Demonstrator.zip](https://github.com/godotengine/godot/files/1221993/10330_Demonstrator.zip)

**Comment by Sslaxx** [comment]
Appears not to be reproducible with 8951403 so closing.

**Comment by Sslaxx** [comment]
This appears to have resurfaced as of a few commits ago.

**Comment by coppolaemilio** [comment]
I have the same issue

**Comment by Sslaxx** [comment]
Fixed by 139daf0 and 045f810.
