### ISSUE TITLE
Console floods with error when changing scenes with a omni light with shadows enabled

### ISSUE THREAD

**Issue by TwistedTwigleg** [godotengine/godot#10346]
**Linux Ubuntu 16.04 LTS  - Godot alpha 1:**

**Issue description:**

If you have a scene with a Omni light that has shadows enabled the console floods with these two errors:
```
Condition '!id_map.has(p_rid.get_data()) ' is true. returned: __null
Condition '!sli' is true. Continuing..:
```
The error continues endlessly prints when you return to the scene.

**Steps to reproduce:**
Create a scene with a Omni light that is casting a shadow and change scenes. Then change back to the original scene.

**Link to minimal example project:**

[Example_Project.zip](https://github.com/godotengine/godot/files/1223870/Example_Project.zip)

Edit: changed point light to Omni light in both the title and description. (Got Godot's and Unity's light names mixed up 😜 )

**Comment by TwistedTwigleg** [comment]
The first error is coming from rid.h at line 154 or 164.

The second error seems to be coming from rasterizer_scene_gles3.cpp at line 269

**Comment by Rubonnek** [comment]
I can also replicate this in Arch Linux.

**Comment by groud** [comment]
Is this fixed now ?

**Comment by TwistedTwigleg** [comment]
Yup, all fixed!
