### ISSUE TITLE
extremal cpu usage, when model have bones

### ISSUE THREAD

**Issue by v0van1981** [godotengine/godot#1034]
model have no bones - 1% cpu usage
add bone to model (without animation) - 100% cpu usage

(when exported from bleder)

**Comment by akien-mga** [comment]
I believed this is also something @slapin has been looking into recently?

**Comment by slapin** [comment]
Even though I can confirm that skeletal transform consume more CPU than
expected even comparing to
different engines (especially seen on android/ARMv7, as any skeleton mesh
reduces frame rate up to 10x),
I have no idea yet where the problem is. Farther research is needed to
optimize this routine.

**Comment by akien-mga** [comment]
@reduz wrote:
> skeletal transform is running on CPU right now, will be reverted back to
GPU shortly (unless blend shapes are used)

What's the status on this?

**Comment by slapin** [comment]
There are bugs in some common cases, need to investigate farther to report
something. At least the case of multiple material planes + morph target,
and some variations around this produce distorted output.

**Comment by reduz** [comment]
Godot 3.0 now fully uses GPU for everything from bones to blend shapes, so closing this issue..
