### ISSUE TITLE
Particles 3D initial velocity always random

### ISSUE THREAD

**Issue by maxim-sheronov** [godotengine/godot#10348]
**Operating system or device - Godot version:**
Arch linux, Godot 3.0 - last build from master branch

**Issue description:**
If I set initial velocity for particles to 1, and velocity random to 0, as I understant, particles' velocity should be constant 1. 
But it is random from 0 to 1. And changing of "velocity random" does not make any effect.

**Comment by reduz** [comment]
I try to see if i can reproduce but it seems to work well. I think someone might have fixed this recently in a PR. The current code looks ok, so closing this issue.
