### ISSUE TITLE
Ability to translate and scale 3D nodes on two axes at once, locking the remaining axis

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#10355]
In Blender, it is possible to translate and scale 3D nodes on two axes at once (XY, YZ, or XZ) while locking the remaining axis (it is done by holding <kbd>Shift</kbd> while pressing an axis modifier key). This makes it easier and quicker to move or scale 3D geometry along a flat surface, for example.

Supporting this in Godot would make the 3D workflow more convenient.

**Comment by toger5** [comment]
Totally agree!
Is it even supported tu use x,y,z as modifier for translation?

**Comment by djrm** [comment]
blender 2.8 also has these handlers which are really cool
![screenshot from 2017-08-15 14-30-55](https://user-images.githubusercontent.com/1103897/29332669-71aacf88-81c6-11e7-9589-b9dfa0b0f466.png)

**Comment by homer666** [comment]
Either this or modified gizmos a la Unity / 3ds Max (hell, even both) would be really great.
