### ISSUE TITLE
KinematicBody2D::Move doesn't detect certain collisions

### ISSUE THREAD

**Issue by abe-noll** [godotengine/godot#10358]
**Operating system or device - Godot version:**
- Windows 10, Godot Steam (2.1?)
- Haven't tested version 3.0

**Issue description:** I am moving a KinematicBody2D towards another collision body. The collision body has a complex and dense polygon shape inside. When you use KinematicBody2D::move near a dense number of polygon vertices, the KinematicBody2D does not register a collision _but_ it get's immediately shoved outside of the other body.

**Expected:** KinematicBody2D will move (from within another polygon2d) and if pushed back register a collision.
**Actual:** KinematicBody2D gets wildly thrown somewhere and does not register a collision.

**Steps to reproduce:**
_Probably better to just skip to the project._
1.  Create a kinematic character you will move around 
2.  Create a collision body (_any_) and give it a collision polygon which has as many polygon fragments as you can fit in
3. Add code to move around for your character
4. If there was a collision in your move, revert it, temporarily ignore and move again (yes through the obstacle )
5. If there was not a collision, compare the distance travelled to the vector used for move. If it is vastly different, you've found the glitch.

_Notes:_ This happens in areas I believe with vertices that 2 or 3 or more polygons connect to in a shape.

**Link to minimal example project:**[gd_bug_example.zip](https://github.com/godotengine/godot/files/1226287/gd_bug_example.zip)

This project will demonstrate it best. There will be instructional labels. 
**enable visible collision shapes**

**Comment by bojidar-bg** [comment]
Testing with the supplied project, I could confirm on 2.1.x.
It works fine for 3.0 though (using the 3.0 exporter)

**Comment by RandomShaper** [comment]
@reduz, any clue about what to backport to fix this?

**Comment by plucian** [comment]
is_colliding(), very unreliable, tried the example on a fresh built (2.1 branch) and I can see the glitches.

**Comment by forgotten-king** [comment]
Probably not too helpful, but I believe I've found the start of the problem here: 
https://github.com/godotengine/godot/blob/2.1/servers/physics_2d/space_2d_sw.cpp#L533

This is what the kinematic::move functions rely on, which is the back-end for all related problems. 

I'll report back if I've found anything that doesn't add up in the code. I won't be working with it directly for the time being as I haven't gone through any of the steps for building godot yet and suspect it would take me a while being that I'm new to C++.

**Comment by bojidar-bg** [comment]
Potentially related to 5fc084c28e912c54bf64645df3e6cf2cd2c30be6, b4129df96c455b0657712b8f6a772265a22e2265.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
