### ISSUE TITLE
move_and_slide() "sensitivity"

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#10350]
**Operating system or device - Godot version:**
Arch Linux, Godot 3 master

**Issue description:**
I'm trying to get into the KinematicBody2D API and just realized that move() and move_and_slide() behave very differently, when used with the same values. In the simple example project, using move() the body moves pretty fast whereas with move_and_slide() it hardly moves at all. For move_and_slide() this means, that i would need very high speed values (10000+) to get an appropriate movement speed, which seems kind of odd. Is this normal behavior or is there something wrong with the "sensitivity" of the move_and_slide() function?

**Steps to reproduce:**
![slide](https://user-images.githubusercontent.com/7927471/29315181-11680be4-81c2-11e7-9a57-fa3c32c03b86.gif)

```
extends Node2D

var direction = Vector2(0,0)
const SPEED = 1000
onready var player1 = $player1
onready var player2 = $player2


func _fixed_process(delta):
	direction.x = Input.is_action_pressed("ui_right") - Input.is_action_pressed("ui_left")
	player1.move_and_slide(direction * delta * SPEED)
	player2.move(direction * delta * SPEED)

```
**Link to minimal example project:**
[move_slide.tar.gz](https://github.com/godotengine/godot/files/1224945/move_slide.tar.gz)

**Comment by reduz** [comment]
move_and_slide() uses and returns linear velocity, while move() is just a
motion vector

**Comment by novemberist** [comment]
Ok, my bad. Actually move_and_slide() behaves exactly like setting the linear velocity of a RigidBody. I guess i was just confused by how big a factor i would have to use to get a good movement speed. This can be closed.
