### ISSUE TITLE
Commented rows do not respect text indent when inserting a new line below them.

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#10354]
**Operating system or device - Godot version:**
Windows - Godot 2+

**Issue description:**
There is an annoying usability issue in the code editor:

```
func example():
	var answer = 42
#	var foobar = make_foobar()
	var baz = foobar.baz
```

Imagine that the caret is located at the end of the commented line.

Now, create a new line, and the caret jumps back to the very beginning of the new line - which is quite impractical and annoying.

So, I'd suggest to make the caret respect the previous row's indent - whether the row is commented out or not.

**Comment by RandomShaper** [comment]
Unless you arw writing a multiline comment. Maybe we could add a setting to enable that behavior and enable/disable it by default according to the best consensus.

**Comment by akien-mga** [comment]
Having such comment style breaks the python-like indentation based block though, so personally I would avoid it and use instead:
```
func example():
	var answer = 42
	#var foobar = make_foobar()
	var baz = foobar.baz
```
Then there is no problem ;)

**Comment by TX256** [comment]
@akien-mga That sounds good to me. However, the "Toggle Comment"-shortcut uses the style in my original post.

Perhaps it'd make sense to simply change this action to use the style that you suggested?

PS. While we're discussing the Toggle Comment action... If someone is going to change this behavior, I sneak in another small feature suggestion for this action: When a line is commented/uncommented, the caret also jumps to the next row. (configurable via settings)

**Comment by RandomShaper** [comment]
The setting could be about comment style: left-margin vs. indent level. The later would be the default as it's the most pythonic. Better names are welcome.

Then the current caret behavior could be kept. That way, the auto-return setting would not be needed as much. You can just hit return manually and the caret will be at the column where the # would have been inserted.

**Comment by Calinou** [comment]
I'll close this in favor of #22177, which is more detailed.
