### ISSUE TITLE
Editor fades from black with "Dim Editor On Dialog Popup" disabled

### ISSUE THREAD

**Issue by AWKgamedev** [godotengine/godot#10353]
**Operating system or device - Godot version:**
Windows 10 - Godot 3.0alpha1

**Issue description:**
Disabling the "Dim Editor On Dialog Popup" option in Editor Settings -> Interface causes the editor to still fade from black when closing a dialog.

I set the Dim Amount and Transition Time to 1 in the gif example for clarity.

![2017-08-15-1436-33 1](https://user-images.githubusercontent.com/10258315/29328194-193b8426-81c8-11e7-9a3c-fb29e216a437.gif)

**Comment by bojidar-bg** [comment]
CC @Hinsbart
