### ISSUE TITLE
Warped panning interacts badly with drag & drop

### ISSUE THREAD

**Issue by WolfAtNight** [godotengine/godot#10364]
i Am using a windows 10 computer and Godot 2.1.3

Sometimes, mostly when i am working with tiles (only when i work with drag and drop) and creating my tilemap something strange happens. somehow godot trys to catch my mouse. you cnow like in 3D games where the mouse is held in the middle of the screen. its exacly that only that it is also flashing. i mean i get it out of that if i go full speed to one of my other screens but as soon as i go near the godot window again it snaps back in to the middle.

i would lke to se this fixed because it is annoying and costs a lot of time

**Comment by puppetmaster-** [comment]
I have had the same problem yesterday after accidental drag and drop sound sample from the open samplePlayer2d resource to my open 2d scene. Godot has show me an icon on the mouse pointer and after releasing, my mouse was invisible and trap on the release coordinates.

**Comment by RandomShaper** [comment]
I'm trying to reproduce to no avail. Can you try to reproduce it and share more explicit instructions?
What screen resolution?

**Comment by WolfAtNight** [comment]
first:
i am using csual mouse no mousepad or something like that
second:
the only thing that could respond to my mouse is the clock itself 
third:
i am using it on a 180x1920 screen 

and for now i can say that i turned of the warped mouse panning setting of and i wasn't able to recreate the bug but i will report if something like that happens again until then thanks for the help

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
