### ISSUE TITLE
Particles3D: trail divisor is not very good

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10363]
**Operating system or device - Godot version:**
3.0 alpha

**Issue description:**
Adding this issue as a reminder for @reduz (after irc meeting). Not sure however what idea exactly @reduz have on mind for replacement.

**Comment by kubecz3k** [comment]
Also: 

> Reduz: I think i will shuffle the particles so old particle gets next position. Problem with trail method is that if emissor moves, all screws up

**Comment by reduz** [comment]
This is unfortunately too much work and potential breaking, so will leave for 3.1 when more particle work will be done (Attractors, collision, force fields, etc).. even if compat is broken a bit (the feature kind of sucks anyway..)

**Comment by jedStevens** [comment]
I think it would be good to have some sort of mesh generation for trails, I think some engines call them ribbons. This could be done with ImmediateGeometry but I almost think exposing the compute shader would be a better option for fixing this. I'll have a crack at this when I get home from work.

**Comment by Calinou** [comment]
The ribbon feature request is probably better described in #22217, so I'll close this.
