### ISSUE TITLE
The script editor caret isn't blinking

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10360]
Godot 3.0 9575dbdf788e8a5154b3ec2f66913e731ac02850
Windows 10 64 bits

I just noticed the cursor doesn't blink in the script editor, although the "redraw" spinner indicates a redraw every second.

**Comment by Calinou** [comment]
Did you enable the Caret Blink option in the editor settings? It is disabled by default.

**Comment by reduz** [comment]
I am ok with having it disabled by default, less redraws and less cpu used :P
in any case, this is not a bug as it works fine, open a PR changing the default if you want a discussion on what is better.
