### ISSUE TITLE
Qt Embedding

### ISSUE THREAD

**Issue by k0105** [godotengine/godot#10369]
Hello,

I'm interested in embedding Godot into a Qt application. It seems like this might have been solved in https://github.com/godotengine/godot/pull/9435 which seems to use a [QOpenGLWindow](http://doc.qt.io/qt-5/qopenglwindow.html) to display Godot content.

Is it possible to embed Godot into Qt5 and if so, how? This functionality would be extremely useful for interactive 3D content in Qt and thus a big USP for Godot, since both Unity and UE4 cannot be embedded into Qt without extensive hacks.

Thank you in advance.

Best wishes,
k0105

**Comment by mhilbrunner** [comment]
Hey! Such questions are usually better suited for the various Godot [communities](https://godotengine.org/community). If this is still something you're interested in or working and you still need help, I'd suggest heading to the IRC (#godotengine-devel on Freenode), Discord or [Q&A](https://godotengine.org/qa/). Thank you!

**Comment by neikeq** [comment]
This could also be considered a feature request, IMO
