### ISSUE TITLE
How to convert variants to byte arrays in Godot 3.0

### ISSUE THREAD

**Issue by maxim-sheronov** [godotengine/godot#10370]
Question about Godot 3.0

In "Binary serialization API" section of documentation I found, that in File and PacketPeer engine uses simple serialization. Is it possible to call serialization or conversion methods from my GDScript?

For example, I want to get array of 4 bytes from 1 float.
Maybe it can be added to some Pool*Array. Because I did not find any way to write floats to PoolRealArray and get correct converted PoolByteArray from it.

Maybe there exists some other way to convert built in types to byte arrays.

**Comment by volzhs** [comment]
use Q&A site, facebook, discord, irc, reddit, etc for question.

**Comment by maxim-sheronov** [comment]
Ok, will close it

**Comment by Noshyaar** [comment]
(offtopic) tbf the [contact page](https://godotengine.org/contact) of the official site encourages filing  issues for questions. I think it should be removed as there are more appropriate ways as mentioned above.

**Comment by akien-mga** [comment]
> (offtopic) tbf the contact page of the official site encourages filing issues for questions. I think it should be removed as there are more appropriate ways as mentioned above.

Thanks, fixed.
