### ISSUE TITLE
Control anchor positioning is sometimes wrong

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10374]
**Operating system or device - Godot version:**
Linux, 1ecb48b8c275f8c895ed34ac7e267871859daf1e

**Issue description:**
In this versions some UI controls are sometimes shifted out of their original places.

_pic1, good:_
![ui_pos_good](https://user-images.githubusercontent.com/6129594/29360975-b2661716-8285-11e7-8a48-7614f8c7173b.png)

_pic2:bad (the same scene)_
![ui_pos_bad](https://user-images.githubusercontent.com/6129594/29360984-c01db60c-8285-11e7-9088-bb6b7fd629ce.png)

I assume the pr that introduces this behavior is https://github.com/godotengine/godot/pull/9889

**Steps to reproduce:**
1. Download sample project
2. Open it with pre 129ebca41d8ed85830580c593eafa2a8637cb5be  version of godot
3. Open Stones.tscn scene and take a look.
4. Do three above steps once again but in current main
5. Observe that Stones.tscn has shifted elements

**Link to minimal example project:**
[Issue: ShiftedUI.zip](https://github.com/godotengine/godot/files/1227990/Issue.ShiftedUI.zip)

**Comment by kubecz3k** [comment]
@groud sorry for not being able to investigate more at the moment, could you take a look?

**Comment by groud** [comment]
The anchor API has changed, now the margin sign is no more dependent on the anchor value.
That means that a node having an anchor set at 0.5 (old ANCHOR_CENTER) or ANCHOR_END, have usually margins with negative values.
This probably has to be modified into the sample project. :)

**Comment by kubecz3k** [comment]
So to be sure, the pr is breaking compatibility with old projects?

**Comment by groud** [comment]
Yes. But mainly for controls that had an anchor set at ANCHOR_END or ANCHOR_CENTER.
I changed them in the editor code but not in the sample projects.
