### ISSUE TITLE
iOS: shader_material demo with wrong screen size when the device orientation changes

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#1037]
When the device orientation changes the image on the screen is scaled up on and iPod touch 5g running iOS 7.1.2

Then it gets back to the right size, but each time the camera passes in from of the object with the shader material the image is scaled up again, just to return to the right size after those objects are no longer in front of the camera

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch? If yes could you do a pull request of your changes if they are still working?

**Comment by akien-mga** [comment]
Can anyone confirm this issue?

**Comment by akien-mga** [comment]
Seems not. Feel free to comment if you can still reproduce the issue, so that I can reopen it.
