### ISSUE TITLE
Request-Editor's connection editor - Ability to pass parameters from a signal to a method in node via the gui

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#10384]
So imagine this scenario : 

I want to call a file dialog when a button is pressed, I use the pop up method like this:
![godotvisprogramconnections](https://user-images.githubusercontent.com/6495061/29387582-86aeba80-82d8-11e7-9cce-7b0abf892613.PNG)

This will actually work, without any need to attach a script anywhere! In the screenshot example we dont need to pass anything to the popup method, because it doesnt take any parameters.

Then however, if we want to do the same thing when the user selects a file in that dialog.
So we use another signal!
the file_selected ( String path ) signal- which emits a string of the path to the selected file.
We want to feed that string to a label or to an edit box.

So we emit the signal to the edit box. At this point however we can not pass the emited string variable from the signal without creating a script and attach it to the edit box. We are forced to create a script and attach it - for such a simple thing with very few lines of code.

Here comes my feature request - for the connecting signal gui in godot's editor:
1.Please add the ability to feed emited signal variables values to methods in nodes that the user sets to receive
2.Please add the ability to receive emited signal variable values 
Like this:
![signalsrequest](https://user-images.githubusercontent.com/6495061/29388089-31cc3eb8-82db-11e7-93dc-b15de318e78a.PNG)

btw when I try this,I get the following error:
![signaltryerror](https://user-images.githubusercontent.com/6495061/29388663-e61aabbe-82dd-11e7-89a2-737e1ad6d7d3.PNG)

We can do that stuff in gdscript and it is fairly well documented. My request is to also be able to do it in the connection editor.

**Comment by blurymind** [comment]
Here is a mockup of how it could work:
![signalsrequest2](https://user-images.githubusercontent.com/6495061/29388314-18b8c256-82dc-11e7-8658-db21e6106031.png)

**Comment by toger5** [comment]
Hm I don't know. I don't see how this would save you that much time. since adding the connection immediately brings you to the script so you just type the set_function.

even if it seems redundant it makes it easier to understand for another coder. If I checkout someones project. and the text changes I can be sure I will find it in the code somewhere. with that I have to search all the files + all the nodes and their connections ...

**Comment by blurymind** [comment]
We can already call methods in a node's class without attaching a script to the receiving node. Why cant we pass any of the information emited by the signal to that class in the connection editor?

It seems like a half finished functionality.

In my example my argument is that I dont want to create another setTextScript.gd file, whose solepurpose is to set the emited string to the edit box. 
Having these scripts everywhere is starting to make my app structure fractured- I want to keep the number of script files lower in the editor

**Comment by blurymind** [comment]
Oh wait,
Godot already has this functionality.

By default the emited signal's value is fed to the target method.
I wasnt sure how to do it, as it is very badly documented feature.

Sorry for wasting your time. I am closing this

**Comment by toger5** [comment]
Im still not an advvocat of having the option to make things work without a script...
But you dont seem to be the only one who wants that so i might need to rethink that.
