### ISSUE TITLE
Very different file sizes when saving the same scene multiple times

### ISSUE THREAD

**Issue by shinyclaw** [godotengine/godot#1038]
I have found a strange issue. When I do: Import->3D Scene->Import&Open and then Save Scene the file size of the .scn is about 115kB (in this sample case). Now, doing the same again: (Import->3D Scene->Import&Open then Save Scene) gives the .scn with size ~14MB. And again: 115kB... So every save I got small or big file...

**Comment by akien-mga** [comment]
Can this still be reproduced in the current master branch?

**Comment by akien-mga** [comment]
I can't reproduce in the current master branch, using the given .dae file, each time I reimport the scene I always get a ``plane.scn`` file of 5431 bytes.
