### ISSUE TITLE
Crash on Startup on Android Devices [Godot 3.0 Alpha 1]

### ISSUE THREAD

**Issue by DualLayer** [godotengine/godot#10394]
**Operating system or device - Godot version:**
- Godot 3.0 Alpha 1
- Device 1: LG K-220 (Android 6.0.1)
- Device 2: Samsung GT-N5110 (Android 4.1.2)
- Java: jdk1.8.0_77
- Templates and Godot.exe are used from this [Link](https://downloads.tuxfamily.org/godotengine/3.0/alpha1/)

**Issue description:**
- LG Device: Only shows White screen directy after startup
- Samsung Device: shows "Unfortunately,Godot Engine has stopped." message directly after startup

**Steps to reproduce:**
- Connecting Android Devices via USB Cable with PC
- Enable USB Debugging on both devices
- Exporting project by klicking on the Android icon in the top right corner of the Editor window.

**Additional description:**
- I Installed the templates via: Editor > Manage Export Templates >Install from File
- Configured Adb, jarsigner and Debug Keystore path manually

**Link to minimal example project:**

[MinimalExample.zip](https://github.com/godotengine/godot/files/1231016/MinimalExample.zip)

**Comment by akien-mga** [comment]
The Android templates in the Alpha 1 .tpz were broken. Can you try to install those manually instead:
- https://downloads.tuxfamily.org/godotengine/3.0/alpha1/android_debug.apk
- https://downloads.tuxfamily.org/godotengine/3.0/alpha1/android_release.apk

You should put them in `%APPDATA%\Godot Engine\templates\3.0-alpha\`  or something like that.

**Comment by DualLayer** [comment]
I've replaced the Android Templated, unfortunately this didn't solve the issues.
Maybe some problem with the java version I use?

**Comment by RandomShaper** [comment]
For a quick test to be really sure Godot is picking the new templates, you
can specify the paths to the APKs in the project settings as custom
templates.

**Comment by DualLayer** [comment]
Thx, specifying the APK's in the project settings solved the problem.
Is this worth a new issue thread?

**Comment by akien-mga** [comment]
I guess that means that you did not properly replace the broken templates, maybe the path I gave above is not exactly how it is on Windows.

At any rate, it was a packing bug for 3.0 alpha1, it will be fixed in alpha2 without a need to change something in Godot itself, so it should be all good :)

**Comment by DualLayer** [comment]
On my Machine (win 10) the path for the templates is %APPDATA%\Roaming\Godot\templates. It's still strange, that the Engine didn't recognize the replaced APKs.
