### ISSUE TITLE
Several visual issues

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#10390]
**Operating system or device - Godot version:**

**Issue description:**

There are several visual issues
![screenshot from 2017-08-16 23-09-03](https://user-images.githubusercontent.com/1103897/29395677-268a7c98-82d8-11e7-8d2c-065db1e8da87.png)
![screenshot from 2017-08-16 23-08-39](https://user-images.githubusercontent.com/1103897/29395678-28045aee-82d8-11e7-9186-9ec7cab1521f.png)
![screenshot from 2017-08-16 23-08-29](https://user-images.githubusercontent.com/1103897/29395679-2b7ca4ba-82d8-11e7-92b3-2cf06380b0cd.png)
![screenshot from 2017-08-16 23-06-23](https://user-images.githubusercontent.com/1103897/29395681-302871a6-82d8-11e7-87f6-4cf178461d0c.png)

Ping @toger5 

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by groud** [comment]
Probably due to #9889, there probably a right margin set somewhere anchored at the end with a positive value. Should be changed to negative.

**Comment by toger5** [comment]
The first one is probably caused by the new style box flat. Looks like there is a corner radius.
Seems i forgot to remove it

**Comment by groud** [comment]
Last one has been addressed by #10393

**Comment by toger5** [comment]
I just found out why there are rounded corners in the visual script editor.
will make a pr soon.

**Comment by toger5** [comment]
ping @djrm 
are they all fixed now?

**Comment by toger5** [comment]
Im also pretty sure the line is fixed. 
I changed sth recently which also could ahve been the reason for that

**Comment by djrm** [comment]
everything has been fixed
