### ISSUE TITLE
Separate user data directory for Godot 3

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#10397]
We already have config and layouts files named differently for 3.0, but I wonder if it would be better to have a separate folder for Godot 3.

Reason: to prevent possible conflicts (future or present but not already noticed, like maybe export templates) and to add the ability to uninstall or clean Godot 2 and 3 user data separately.

Now the folder is pretty confusing regarding what files/subdirectories belong to each branch.

**Comment by Calinou** [comment]
Blender uses a folder per version, so you have `(Blender user data directory)/2.77` and `(Blender user data directory)/2.78`, for example. We could do the same, I guess.

**Comment by reduz** [comment]
which kind of user data?

**Comment by Calinou** [comment]
I was refering to the editor user data (settings, export templates, text editor themes, …). Game user data would, of course, go to a different directory chosen in the project settings (or the export settings).

**Comment by reduz** [comment]
editor data is usually ok, because project info is saved as a directory in
both 2.x and 3.x

**Comment by reduz** [comment]
err i mean, unique directory hash

**Comment by akien-mga** [comment]
I'm fine with switching to a `.godot/3.0/` folder if you guys think it's better.

The main drawback of such splitting is that you either lose config, or need to provide a way to import it, whenever you move to a new version. Godot 3.0 broke compatibility with everything that came before it, but I expect that 3.1 will stay compatible and will use the same formats. But if done right, we can have Godot 3.1 import (and if need be, convert) existing 3.0 settings, and then they can diverge as needed by the constraints of the two versions.

**Comment by Zireael07** [comment]
I think the idea is for 2.1. branch to save to 2.1 folder and master to save to 3.0 folder, so 3.1 etc. would save to 3.0?

**Comment by reduz** [comment]
I would not do it by version, I have no idea if 4.0 will be compatible with
3.0. Current way is probably best.

**Comment by RandomShaper** [comment]
> The main drawback of such splitting is that you either lose config, or need to provide a way to import it, 

As long as the switch is done per major release, losing them is what already happens now. Settings for 2.x are incompatible with those for 3.x.

We may think about config importing as independent feature.

> I'm fine with switching to a .godot/3.0/ folder if you guys think it's better.

I'd be more in favor of `.godot3` (with no subdirectory), to keep 2.x's and 3.x's side by side at the same level.

**Comment by akien-mga** [comment]
> I'd be more in favor of .godot3 (with no subdirectory), to keep 2.x's and 3.x's side by side at the same level.

If we went this way, I'd strongly prefer `.godot/3` or `.godot/3.x` to avoid cluttering users' $HOME with `.godot{,3,4,5,6,7}` over the years.

**Comment by RandomShaper** [comment]
Makes sense.

**Comment by reduz** [comment]
guys, as I mentioned, I have no idea why you are wasting time on this.
~/.godot consists of

1) general settings file, which can be changed in the world case by version. 2 and 3 use a different file
2) Project cache directories, which are hashed, so nothing from 2 and can 3 coexist anyway
3) Export templates. From Godot 3.0 they are already versioned, so past and future versions will not conflict
4) A general cache directory that is not used much nowadays and might be replaced by the host OS cache directory.

Let's not add unnecessary features, this is not needed.

**Comment by reduz** [comment]
We also discussed this before on IRC and decided against it.

**Comment by RandomShaper** [comment]
Hmmm. So there is not possible conflict.

I'd still prefer separate storage, but if this is already discussed, I'm ready to have this closed.

**Comment by hpvb** [comment]
I'd like to add that if we're changing anything about the setting locations of Godot we really should also move the files in the correct XDG dir on Linux at least. We really shouldn't be making a ~/.godot as a hardcoded location.

The common way to do this is to still read the old location if it exists but always create files in the correct location if no ~/.godot existed at all.

**Comment by reduz** [comment]
I will close this, currently this is designed so versions dont clash, this is not really a problem.
Also we discussed against XDG, current way should work good enough.
