### ISSUE TITLE
Possibility to cherry-pick #8974 "Added script overview" to 2.1.4 ?

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#10392]
https://github.com/godotengine/godot/pull/8974

It could be great to have this in 2.1.4 too. This is a code text editor "must have" and a very visible feature.

**Comment by akien-mga** [comment]
It's not trivial as the code base is quite different for the script editor in 2.1 and master (a big part of the script editor code was split into its own file in master), so unless @Paulb23 or someone else is interested in porting the feature, it likely won't be cherry-picked.

**Comment by davarrcal** [comment]
If it is too difficult, any chance to "expose" to EditorPlugin the name of the script that is open in editor and give hability to scroll to any line of the opened script? With this two things it can be accomplished by a plugin.

**Comment by Ranoller** [comment]
Ok, I close this.... thanks a lot!!!
