### ISSUE TITLE
Joy Axis in Input Mappin

### ISSUE THREAD

**Issue by louisVottero** [godotengine/godot#10391]
**Operating system or device - Godot version:**
Windows 10, Godot 3.0 Alpha Build 1

**Issue description:**
I tried mapping Joy Axis Device 0 Axis 0 - Left Stick Left to "ui_left"
However it wasn't reading the mapping when using Input.is_action_pressed("ui_left")
Also when I reopened the project the mapping I added was gone

**Steps to reproduce:**
in Project Settings > Input Mapping > "ui_left" add Joy Axis Device 0 Axis 0 - Left Stick Left
If you reopen the project it won't be mapped anymore.
If you create a script and do if Input.is_action_pressed("ui_left"): print('here')  , "here" won't show up because it doesn't read the Joy Axis has being mapped.  

**Link to minimal example project:**

**Comment by HummusSamurai** [comment]
This was fixed in the master branch in https://github.com/godotengine/godot/commit/5052cb2b9104f57d0ff38d80da50bbeceb926e6f (I know because I reported the bug) and is now working on my machine.

Try using one of the [latest builds](https://bintray.com/calinou/godot/editor/2017-08-16.95f5470#files) as this should solve your problem.

**Comment by akien-mga** [comment]
Fixed by 5052cb2.

**Comment by HummusSamurai** [comment]
Also OP, just wanted to throw some advice: Keep in mind that this does not take into account "how much" the axis has been moved, only that it has been moved.

This is fine for character movement, and in my project I use "Input.is_action_pressed()" for character movement using left stick, but I use "Input.get_joy_axis(0,2)", which returns the axis value, for controlling the camera with the right stick. 

This allows for more sensitivity in camera rotation (which you definitely want, trust me, or else the controls will be physically painful).

**Comment by louisVottero** [comment]
I'm looking at dolson's Joystick Project and just trying to build stuff from scratch to understand how it works.   I think he uses Input.get_joy_axis as well.
