### ISSUE TITLE
[GridMap] Cannot edit grids in the 3D viewport

### ISSUE THREAD

**Issue by HummusSamurai** [godotengine/godot#10395]
**Operating system or device - Godot version:**
Fedora 26 - Godot 3 master.

**Issue description:**

I am unable to edit the gridmap tiles.  
When I click on the GridMap node, the side menu for the tiles shows up properly and I can select them, but clicking on the world does not place tiles.

**Steps to reproduce:**
Try to edit the grid cells.

**Link to minimal example project:**

The platformer 3D demo.

**Comment by akien-mga** [comment]
Just a hunch, but it might be related to @kubecz3k's recent changes to improve the usability of selecting spatial objects in the viewport.

**Comment by HummusSamurai** [comment]
Note that this bug is also present on the godot 3 alpha, so it is not related to the recent changes related to @kubecz3k

**Comment by reduz** [comment]
this should be fixed now, closing
