### ISSUE TITLE
Error importing large textures with .tex extension target

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#10408]
**Ubuntu 17.04 - Godot version: 2.1.3/2.1.4 beta 3**

**Issue description:**
When importing a large texture, the extension options are `.tex` (first) and `.ltex` (second), if the chosen extension is `.tex`, the editor shows 2 error windows saying that could not import the texture.

If have conflicts with `.tex` extensions, it should let import as `.ltex` only.

**Steps to reproduce:**
Try to import a large texture with `.tex` extension.

Some pictures:
Trying to import as `.tex`.

![ltexbug0](https://user-images.githubusercontent.com/10215987/29436258-16d1f08e-8381-11e7-8ff7-a9ba09fba8a9.png)

![ltexbug1](https://user-images.githubusercontent.com/10215987/29436171-c0f577d0-8380-11e7-8704-66289e3a36f0.png)

![ltexbug2](https://user-images.githubusercontent.com/10215987/29436181-c5c694b0-8380-11e7-93bf-bde44249b097.png)

![ltexbug3](https://user-images.githubusercontent.com/10215987/29436186-cbbb42c6-8380-11e7-8e63-eb36c141fff2.png)

Work as expected with `.ltex` extension.

![ltexbug4](https://user-images.githubusercontent.com/10215987/29436190-d1cabebc-8380-11e7-8c91-c05652e1e108.png)

![ltexbug5](https://user-images.githubusercontent.com/10215987/29436197-d683c656-8380-11e7-85ce-7d7a053e2f0d.png)

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by eon-s** [comment]
I have no idea of how to import a texture in large texture format in Godot 3, the format is on the dropdown for new texture but there are no import option for it.

The formats to which a large texture can be saved are tres, largetex, res, but the importer does not show anything.

--------------

I guess this file format issue can be ignored for master.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
