### ISSUE TITLE
Jumping words with CTRL + Left / Right could be improved

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#10403]
**Operating system or device - Godot version:**
Windows - Godot 2-3

**Issue description:**
Here's another little usability issue in the code editor that still bugs me all the time:

Navigating with CTRL + Left/Right stops at the beginning/end of the row. I can't think of any reason as of why not to proceed to previous / next row.

**Comment by reduz** [comment]
feel free to try your hand at text_edit.cpp

**Comment by TX256** [comment]
It's been around 15 years since my last contact with C++. However, Godot has been the very first project during that time that has almost gotten me back to it, several times. I shall install Visual Studio, and see where it gets me.
