### ISSUE TITLE
line edit and other edit nodes- please add ability to limit what characters can be entered via a regex string

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#10416]
Please add ability to limit what characters can be entered via a regex string in the line edit and other edit nodes.
It would be a nice addition to the edit box class in general.
This is a very basic and commonly used requirement to building interfaces, as more often than not some inputs should allow only numeric input without spaces or only text

Bellow is an example code that adds it via gdscript.
```
extends LineEdit

export var regexLimitString = '[0-9]'
func _on_LineEdit_text_changed( text ):
        if regexLimitString.length() != 0:
	         var cursorPos = get_cursor_pos()
	         set_text(returnSpecificSymbolsOnly(text,regexLimitString))
	         set_cursor_pos(cursorPos)

func returnSpecificSymbolsOnly(enteredText,regex):
	var word = ''
	for letter in enteredText:
		var resultingText = RegEx.new()
		resultingText.compile(regex,9) #search pattern
		if resultingText.find(letter,0,-1) != -1 : word = word+letter
	return word
```

I also wrote a plugin that does it and will upload it soon

However it would be nicer to have it built into godot!

**Comment by RandomShaper** [comment]
I don't know how many people is using or intends to use Godot to build non-game UIs, but if it was found to be a widespread use case, we'd need to think carefully about this.

I mean, adding nodes/APIs/properties, etc. to provide a nice experience when building such, with validators and that kind of stuff.

The GUI system is already rich and maybe that would be too out of scope, a feature bloat, but making Godot a proper front-end dev tool to build creative UIs for the web looks amazing, doesn't it?

**Comment by blurymind** [comment]
Here is my addon btw:
https://github.com/blurymind/Godot-Addons/tree/master/lineEditPlus

it also has the option to limit how many characters can be entered

**Comment by blurymind** [comment]
@RandomShaper I think that is a bad excuse not to have this feature as it is an extremely common case scenario - even inside Game GUIs to require to limit what input goes into an edit box.

Heck, even godot's own editor has that feature practically everywhere

**Comment by akien-mga** [comment]
I don't think this needs to be supported out of the box. When you do need to restrict valid characters, you'll typically want to provide some feedback to the user when they input an invalid character, so it's much simpler to catch the `text_entered` signal, run your regex, and react accordingly (update an error label, etc.).

**Comment by akien-mga** [comment]
Note that with #29347 LineEdit will automatically strip non-printable control characters, so some basic input validation is provided to remove things that LineEdit cannot handle.

For further game-specific input validation, connecting to `_text_entered` is the right way to apply a regex or custom validation to the given input.

**Comment by girng** [comment]
> I don't think this needs to be supported out of the box. When you do need to restrict valid characters, you'll typically want to provide some feedback to the user when they input an invalid character, so it's much simpler to catch the `text_entered` signal, run your regex, and react accordingly (update an error label, etc.).

agree 100%, nice post. i think a regex filtering thing would be awesome and be a solution for this, and 296000 and allow for even greater filtering.
