### ISSUE TITLE
should be able to duplicate root node

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#1041]
We should be able to duplicate the root node, and have it added as a direct child of the root.

**Comment by akien-mga** [comment]
It would be somewhat confusing no? Duplicate non-root nodes produce sister nodes, so having a duplicate root node become a children sounds a bit strange.

But if there's a use case, why not. I don't really see it though, could you give an example of a situation where duplicating a root node and have the duplicate become a child of this node would be useful?

**Comment by adolson** [comment]
I don't remember why I wanted this. It was almost a year ago, and I haven't had much time to work on games since January. Close it if nobody else wants it.

**Comment by akien-mga** [comment]
Archiving then, we'll likely get a new issue if someone is interested in this.
