### ISSUE TITLE
[TRACKER] GridMap related issues

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10418]
- [x] #10118
- [x] #9111
- [x] #10395
- [x] #907
- [x] #11857
- [x] #10128 
- [x] #8812
- [x] #6515
- [x] #11722
- [x] #11888
- [x] #10697
- [x] #6207 
- [x] #3829
- [x] #3284
- [x] #11856
- [x] #11855
- [ ] #18836
- [ ] #17118
- [x] #24130
- [ ] #23104
- [x] #6639
- [ ] #5526
- [x] #10005

**Comment by Giacom** [comment]
I've also been having issues adding collisions to the gridmap. It doesn't import any shapes and it does not let you change the number of shapes, in the shapes array, so I cannot add them manually.

**Comment by reduz** [comment]
@Giacom That seems to work correctly now

**Comment by Giacom** [comment]
Still having the same issue. Collision boxes aren't being imported and I can't change the shapes array, trying to resize it immediately puts it back to 0.

**Comment by kubecz3k** [comment]
@Giacom this deserves it's own issue. Please open new one, include detailed reproduction steps and sample project. Thank you

**Comment by Giacom** [comment]
https://github.com/godotengine/godot/issues/11888

Done.

**Comment by mhilbrunner** [comment]
#907 is done, too.

**Comment by pwab** [comment]
#10697 and #11856 were fixed.

**Comment by Wiadomy** [comment]
About `More obvious way to rotate GridMap tiles` I think the current rotating is okay, but we need one more thing - flipping tiles, along with rotating.

**Comment by EzraT** [comment]
#18836 should probably also be added to this.

**Comment by Toshiwoz** [comment]
#17118 probably should be part of this tracker.

**Comment by aaronfranke** [comment]
#22205 top, as Vector3i would be very useful for GridMap.

**Comment by Xenoamor** [comment]
Has there been any discussion about mirroring items in the GridMap? Is there enough free data in the structure for this, I imagine we'd only need a few bits

**Comment by qarlosh** [comment]
If the parent or some ancestor of a `GridMap` has `visible = false`, the `GridMap`is still shown. It only hides when setting its own `visible`property to false. Maybe this is related to #907 .

**Comment by tustin2121** [comment]
Add #23104 to this tracker (and probably the already closed #24130 as well, for completeness' sake).
