### ISSUE TITLE
Script editor font size zoom gets stuck at maximum

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#10413]
**Operating system or device - Godot version:** MacOS 10.12.6 - Godot 3.0a1

**Issue description:**
When using zoom keys (Meta+Equal, Meta+Minus) in the Script Editor, font size zooms once and then jumps bigger on its own. After 2 or 3 zooms (in either direction) font becomes very large and will no longer change. 

**Steps to reproduce:**
See attached gif:

1. open script
1. press Command+Equal , font zooms in once, then jumps bigger on its own
1. press Command+Minus, font zooms out once, then jumps to a huge value 
1. after this, no further zoom commands work and setting persists after restart

![screen grab](https://user-images.githubusercontent.com/3812514/29441298-26f2ef9c-837f-11e7-904c-760b83f6dacd.gif)

Only way I found to fix is to edit the `editor_settings-3.tres` and change  `interface/source_font_size` to a reasonable value.

**Comment by carlosmarti** [comment]
This might just be a Mac only issue since i just tried replicating this on windows and cannot get the same bug to happen.

**Comment by Tanjoodo** [comment]
I attempted to replicate the issue on a mac mini but was not able to reproduce it.

**Comment by Rubonnek** [comment]
I'm not able to reproduce this in Linux either with a91d12ab945222b0fc89d4634e3e781ba8941f33

**Comment by cbscribe** [comment]
After some further testing with SwitchResX, this only happens in HiDPI video modes. Does not occur when in non-HiDPI modes.

**Comment by cbscribe** [comment]
Following up: I haven't been able to reproduce this in recent builds, so I think we can probably close.
