### ISSUE TITLE
ETC2 texture appears to be corrupt

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#10421]
**Operating system or device - Godot version:**
Android, Godot e61d547ed08924d75e18469fe648463dee3bd5a3

**Issue description:**
There is a problem on Android with the texture in this project: https://github.com/endragor/etc2bug

The project runs fine on macOS, but on Android you get:
```
ERROR: _load_data: Method/Function Failed, returning: ERR_FILE_CORRUPT
ERROR: load: Failed loading resource: res://.import/digits.png-70b94ee7ddf27fdf79aee97efbcacfe1.etc2.stex
ERROR: load: Failed loading resource: res://digits.png
ERROR: poll: res://main.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://digits.png
ERROR: load: Condition ' err != OK ' is true. returned: RES()
ERROR: load: Failed loading resource: res://main.tscn
ERROR: start: Failed loading scene: res://main.tscn
```

To reproduce simply export the project to Android and launch it there.

**Comment by RandomShaper** [comment]
In macOS are you running it as an exported project?

**Comment by endragor** [comment]
No, last Godot crashes for me during macOS export. I think the key difference here is that desktop platforms use s3tc textures, while mobiles use etc2. But, of course, it can be something else.

**Comment by endragor** [comment]
This is the error that occurs when exporting the texture:
```
REIMPORTING: res://T_Digits.png
to gen mipmaps w 512 h 512 format RGBA8 mipmaps 9 new size is: 1398100
to gen mipmaps w 512 h 512 format RGBA8 mipmaps 9 new size is: 1398100
ERROR: _get_etc2_mode: Condition ' true ' is true. returned: Image::FORMAT_MAX
   At: modules/etc/image_etc.cpp:56.
ERROR: _image_format_to_etc2comp_format: Condition ' true ' is true. returned: Etc::Image::Format::UNKNOWN
   At: modules/etc/image_etc.cpp:86.
ERROR: get_format_name: Index p_format out of size (FORMAT_MAX).
   At: core/image.cpp:2495.
begin encoding, format:
time encoding: 11
```

**Comment by endragor** [comment]
Adding a blue-colored square to the texture fixes the issue. So it looks like there is a problem with textures which use only 1 color (white, in the example texture) with alpha.

**Comment by reduz** [comment]
Sorry, I forgot to ask, could you attach a texture that fails here? that would be really useful

**Comment by reduz** [comment]
on nevermind, you attached a project
