### ISSUE TITLE
Onion skinning for AnimationPlayer

### ISSUE THREAD

**Issue by genaside** [godotengine/godot#10425]
I  want to propose a feature for animation player that allows onion skinning.
The reason for this is to properly position my 2d sprites to get that flawless animation.

**Comment by RandomShaper** [comment]
I'm not familiar with that concept. Could you elaborate, please?

**Comment by YeldhamDev** [comment]
@RandomShaper

![](http://docs.toonboom.com/help/animate/Content/Resources/Images/HAR/Stage/Cut-out/an_animateon.png)

**Comment by genaside** [comment]
thanks @YeldhamDev , that's it. 
I want this cause my sprites are not all in the right position, so trying to fix them by switching between keyframes gets tedious. At times I put put my finger on the screen to find where the next sprite should be,
Having a "ghost" of the last keyframe will help greatly.

**Comment by reduz** [comment]
I thought about doing something like this by doing a viewport capture and
blending previous frames with decreasing transparency.. but not quite sure
what the best way would be

**Comment by reduz** [comment]
if you guys can discuss a good implementation idea, i have noted for 3.1 to
do a lot of improvements for animation code so it might go well there

**Comment by RebelliousX** [comment]
It would be cool when this gets implemented, to have an option to allow for the faded frames to remain in the same position where the main sprite was. Words may betray me to describe this, but the closest thing I can remember right now would be Ryu from Street Fighter series, when he is doing his combos, a silhouette of him is shown in different frames while moving, his silhouette remains in the old position.

![sfa3metsushoryuken](https://user-images.githubusercontent.com/1888186/29490239-9b063204-84fb-11e7-9ebc-6280a106cf02.gif)

**Comment by genaside** [comment]
If you use Krita for animations, you'll know what I am taking about. You can set how far the "skinning" goes and what color+opacity of the layers.

To be honest just one layer(previous) with a 50% opacity under the current keyframe will do. :)

**Comment by hpvb** [comment]
Ah yeah, krita's onion skinning system is fantastic, getting that in godot would be great!

**Comment by RandomShaper** [comment]
I'm working on this. The first implementation will be simple yet useful.

**Comment by RandomShaper** [comment]
Just an update. I've been doing a log of R&D and now I believe I'm on the right track. I expect to be releasing some results very soon!

I'll submit a WIP PR as soon as possible so @reduz and others can assess.

**Comment by volzhs** [comment]
https://docs.krita.org/Animation#Expanding_upon_your_rough_walkcycle
krita has nice onion skinning shows previous and next frames.

![image](https://user-images.githubusercontent.com/8281454/32202345-60087ba0-be1f-11e7-9b68-e2c32b500a22.png)

**Comment by reduz** [comment]
My suggestion was to use the new viewport API to capture frames, then
overlay them

**Comment by RandomShaper** [comment]
That's what I'm trying, but I can't find a good way to capture frames. I can create a copy of the ViewportTexture, but I'm doing so by getting the image data and creating a new texture from it. Needless to say that's painfully slow. 

How can I copy a texture from VRAM to VRAM? 

Regarding overlaying, I've extended the EditorPlugin API to allow overlaying on top of 3D viewports  as well. 

I think I'm pretty close to success! :)

**Comment by RandomShaper** [comment]
I've submit a WIP PR for this: #12572.
