### ISSUE TITLE
WM_CLASS is set too late on Linux

### ISSUE THREAD

**Issue by radenling** [godotengine/godot#10429]
**Operating system or device - Godot version:**
ArchLinux x64 - Godot 2.1.3 and master

**Issue description:**
The `WM_CLASS` property is set after the window has been mapped. This prevents the window manager bspwm from applying its rules for how the window should be displayed (tiling, floating, which desktop, etc) since it checks `WM_CLASS` before the window has been mapped. The ICCCM spec requires `WM_CLASS` to be set when the window is mapped so Godot should set this before mapping the window to play nice with the window managers that uses `WM_CLASS`.

This probably affects a few other tiling window managers as well.

**Comment by reduz** [comment]
PR welcome to fix this
