### ISSUE TITLE
Auto-indent destroy undo history

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#10420]
Everything is in the title ^^
Basically if you use auto-indent, your editing history gets destroyed, meaning if you're unhappy with the auto-indent result, you have to close the file without saving it, then reopen it :'-(

I've experienced this behavior with Godot 3 alpha but I think it is a much older issue: I believe this is due to 389d6ca0c7ad6d0609731b279f30df011c6bf40a, but I don't get the reason of this patch in the first place...

**Comment by RandomShaper** [comment]
Working on this.
