### ISSUE TITLE
Visual issues in 3D platformer demo (regression from 72be887)

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#10434]
**Operating system or device - Godot version:**
Fedora 26 Nvidia Proprietary drivers, Godot bf1f83ed29a3cc2833a1ad7b5080b2d162ed0a88

**Issue description:**

The 3D platformer demo has visual issues

![screenshot from 2017-08-18 23-32-41](https://user-images.githubusercontent.com/1103897/29483520-e2c8df3a-846d-11e7-8047-662aa636fbe5.png)

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by HummusSamurai** [comment]
The bad commit is https://github.com/godotengine/godot/commit/72be8876ea40984532d283c598dfcc267d30c829

**Comment by HummusSamurai** [comment]
The bad commit also causes a lot of errors to be thrown in the console.
These happen as soon as I open a project in the editor. They happen as much as 70 times in one go.

> ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Performance	ID: 131218	Severity: Medium	Message: Program/shader state performance warning: Vertex shader in program 1 is being recompiled based on GL state.
>    At: drivers/gles3/rasterizer_gles3.cpp:122.
>

**Comment by akien-mga** [comment]
Confirmed on Mageia 6, NVIDIA 384.59. Would be good to have a confirmation from a non-Linux and non-NVIDIA user.

**Comment by akien-mga** [comment]
I confirm that reverting 72be887 fixes the bug.
