### ISSUE TITLE
Exit button cropped on project manager

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#10450]
**Operating system or device - Godot version:**
Linux x86_64, Godot master 5d85108f9.

**Issue description:**
The "Exit" button is cropped to the bottom in the project manager:
![spectacle lw6940](https://user-images.githubusercontent.com/4701338/29488144-fba9867a-8504-11e7-986b-fc05aae8ba1d.png)

**Comment by Calinou** [comment]
I can confirm this on Windows 10:

**Project manager window at the default size:**
![godot_pm_exit_button_small](https://user-images.githubusercontent.com/180032/29488336-e27e373c-8508-11e7-8112-37d6711af25c.png)

**Project manager window maximized on a 2560×1440 monitor:**
![godot_pm_exit_button_large](https://user-images.githubusercontent.com/180032/29488335-e25d04c2-8508-11e7-92ca-241b3f1dc323.png)

**Comment by groud** [comment]
Probably due to #9889 once again. I have to take a look at it :)
