### ISSUE TITLE
Godot is unable to run game from editor

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#10457]
**Godot version: 588ffbc08aaf7d1fa30163f46702d56e032de04a**

**Issue description:**

Can't run game from Editor. It works from Project select window tho.

**Comment by n-pigeon** [comment]
'git bisect' suspects this commit: 27fc96f3c8528f0f9cc6e42d8e64934ba1b48d6d

**Comment by novemberist** [comment]
I think this has been fixed by https://github.com/godotengine/godot/pull/10464

**Comment by n-pigeon** [comment]
Works, closing.

**Comment by akien-mga** [comment]
Weird, it worked fine in my tests... Back to work..

**Comment by akien-mga** [comment]
I can't reproduce it, clicking the "Run" button works fine, and the command printed in the terminal is correct:
```
Running: /home/akien/Projects/godot/godot.git/bin/godot.x11.tools.64 --path /home/akien/Projects/godot/godot-demo-projects/3d/platformer --remote-debug 127.0.0.1:6007 --editor-pid 30312 --position 448,240
```
Can you try to reproduce it back on 588ffbc and give me the corresponding terminal output?

**Comment by n-pigeon** [comment]
@akien-mga Sure:
`Running: /home/pigeon/Devel/Godot/godot/bin/godot.x11.tools.64 --path /home/pigeon/Work/Pitch/Game/hero_prototype --remote-debug 127.0.0.1:6007 --editor-pid 12771 --debug-collisions --position 0x0
Invalid position '0x0', it should be e.g. '80,128'.`

**Comment by akien-mga** [comment]
> Can you try to reproduce it back on 588ffbc and give me the corresponding terminal output?

Alternatively, please test #10471 locally. You can fetch the patch with https://github.com/godotengine/godot/pull/10471.patch and apply it with `git apply`.

**Comment by n-pigeon** [comment]
@akien-mga 
Fast. You want me to test patch localy or test above was enough?

**Comment by akien-mga** [comment]
The above test was enough, thanks. I don't know why your position is `0x0` when it should be `0,0`.

**Comment by akien-mga** [comment]
Ok I could reproduce, it happens when using Editor Settings > Run > Window Placement > Rect: Default. I was using Centered, which does not trigger the bug.

**Comment by akien-mga** [comment]
Will amend my commit with:
```diff
diff --git a/editor/editor_run.cpp b/editor/editor_run.cpp
index 28907ccf5..55f168ed0 100644
--- a/editor/editor_run.cpp
+++ b/editor/editor_run.cpp
@@ -94,7 +94,7 @@ Error EditorRun::run(const String &p_scene, const String p_custom_args, const Li
                case 0: { // default
 
                        args.push_back("--position");
-                       args.push_back(itos(screen_rect.position.x) + "x" + itos(screen_rect.position.y));
+                       args.push_back(itos(screen_rect.position.x) + "," + itos(screen_rect.position.y));
                } break;
                case 1: { // centered
                        Vector2 pos = screen_rect.position + ((screen_rect.size - desired_size) / 2).floor();
```
