### ISSUE TITLE
Crash on Wake Windows 10

### ISSUE THREAD

**Issue by whendricso** [godotengine/godot#10465]
**Operating system or device - Godot version:**
Godot 2.1.3
Windows 10
ASUS ZenBook Pro UX501VW-US71 15.6-Inch 4K Touchscreen Laptop (Core i7-6700HQ CPU, 16 GB DDR4, 512 GB NVMe SSD, GTX960M GPU

**Issue description:**
Godot crashes when the system wakes up from sleep!

**Steps to reproduce:**
Put your Windows 10 i7 machine to sleep with Godot running. It will crash when the computer wakes up

**Comment by Listwon** [comment]
Cannot reproduce.

Windows 10 Pro
Lenovo T510 (Core i5 M 540 CPU, 8 GB DDR3, 256 GB SSD, Quadro NVS 3100M GPU)

**Comment by whendricso** [comment]
Perhaps it has to do with the architectural difference between the i5 and
i7 cache?

**Comment by marcelofg55** [comment]
I tested this and couldn't reproduce it, maybe it was fixed already?

**Comment by TomDobbelaere** [comment]
I have this issue, i7 as well but in Godot 3.0.2 x64

**Comment by bojidar-bg** [comment]
Can someone reproduce this on 3.1? Would be nice if someone manages to debug it with gdb or some other debugger.

**Comment by akien-mga** [comment]
That's a pretty old issue and we haven't seen new reports since over a year, so closing. It's likely a fault in the OS / drivers and not in Godot, given how few users can reproduce it.
