### ISSUE TITLE
Improvements to camera movement and freelook in 3D editor

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#10463]
**Operating system or device - Godot version:**
Arch Linux, Godot 3 master

**Issue description:**
I've been playing around a bit with UE4 lately, solely to investigate what small things it has, that I'd really like to see in Godot, too. One of the things that I noticed I liked most is how smooth and satisfying the camera movement in the 3D editor feels as opposed to Godot (especially when using freelook). 

It's hard to explain, but there seems to be some sort of intertia or weight to the camera (similar to stabilizers in graphics programs) that allows for much more precise and less abrupt camera movement than in Godot. I played around with some of the editor settings in Godot but couldn't achieve the same effect. 

Unfortunately, I can't provide a gif for comparison, but maybe people who have used UE4 before (or possibly also Unity) can comment on this. Would it be possible to implement something like camera inertia for the camera in the 3D editor? I think this would greatly improve its usability.

**Comment by homer666** [comment]
Yeah, I've also noticed that freelook in Godot is pretty jerky. Unity's freelook mouse sensitivity is a lot lower which results in it feeling a lot less "jumpy" than Godot's. I haven't noticed any mouselook acceleration in Unity and don't have Unreal to test this out with, but I think I understand what you're referring to.

Camera rotation speed is slow when the mouse is being moved slowly, and accelerates when the mouse is moved quickly. I think this is what gives the Unreal freelook that "weighty" feeling.

**Comment by novemberist** [comment]
I just tested Unity's freelook for comparison and while it certainly feels much better than Godot's, it somehow doesn't feel quite as satisfying and "weighty" as the one in UE4 (which has some very slight delay, hence me referring to it as "intertia")

**Comment by Hinsbart** [comment]
CC @Zylann 

The problem of not being able to adjust mouse sensitivity is already addressed by #10460.

**Comment by Calinou** [comment]
Inertia should definitely be added to the freelook camera, but it should remain subtle by default.

**Comment by toger5** [comment]
I was thinking about that too. would be a beautiful feature.
For the normal orbit look too.
I wanted to post another application which has well executed 3d navigation.

https://sketchfab.com/models/3658a1d21013448eab56ac27818d9858

It maybe is too "soft" for a working environment (this level of smoothness fits better for observing... but at least the effect is really obvious)

**Comment by reduz** [comment]
SptialEditorViewport needs transform smoothing. Most 3d editors have it
nowadays. This will fix most problems.. maybe should implement it, it's
pretty easy.

**Comment by toger5** [comment]
@reduz that would be great and would make it feel sooo much better!!

**Comment by Zylann** [comment]
I don't see how useful smoothing is, to be honest, apart from it looking good (if it's added, I'll disable it :p). In a development process I mostly expect reactiveness, which actually is more noticeable in Godot than other engines:
Try to make the editor "update always", and you'll realize camera navigation feels better, just because the framerate gets higher.

**Comment by reduz** [comment]
Smoothing is very useful. It makes focusing on a objects or changing axis
aligned views a lot less confusing

**Comment by Zylann** [comment]
I definitely see the advantage for focusing or axis-aligned change, but not so much for mouse orbit/look.

**Comment by novemberist** [comment]
I suppose there will be an editor setiting to tweak the smoothing, so people who don't like it can turn it down or off. So I don't see any harm in having this feature.

**Comment by DjPale** [comment]
Started playing around with Godot 3.0 Alpha 1 build and the jerkiness of the 3D navigation really threw me off - so I would  say that this is a rather important tweak - especially if this is easy to fix.

**Comment by Zylann** [comment]
@DjPale there are currently (on master) three ways to reduce jerkiness:
- set your FoV higher, like 70 (45 is quite small, it zooms all things and reduces sight width),
- reduce orbit sensitivity (I added the option recently, but default is 0.7, I later proposed to reduce it to 0.4 in a PR),
- try "update always" mode (the "update changes" mode doesn't run at 60 fps for some reason).

**Comment by toger5** [comment]
@Zylann Tweens might be perfect. since that would be little additional code and they are built for things like that!

**Comment by novemberist** [comment]
I made a new issue, because this is not strictly related, but this possibly also contributes to the jerkiness of the current freelook mode: https://github.com/godotengine/godot/issues/10516

**Comment by novemberist** [comment]
As of this commit https://github.com/godotengine/godot/commit/1894157c9fab05984428d83a743b0fe1d720c80c zooming and orbiting feels much smoother now. However, this doesn't seem to affect freelook yet.

**Comment by reduz** [comment]
I added general camera interpolation yesterday, but noticed that for
regular editing it's kind of annoying, so i just disable if a mouse button
is pressed. It works nicely for changing views or focusing on objects,
though.

**Comment by novemberist** [comment]
@reduz So combining camera interpolation and freelook is out of the question for now? I don't know if this will cause issues, because freelook and zoom are so closely linked as mentioned in: https://github.com/godotengine/godot/issues/10516

**Comment by reduz** [comment]
it's not out of the question, though my feeling was that it was laggy with
camera interpolation, which made me disable it for most cases

**Comment by novemberist** [comment]
woud you mind making enabling it optional via an editor setting?

**Comment by reduz** [comment]
no.. it just doesn't feel good. You might be having a different problem,
though

**Comment by novemberist** [comment]
Too bad. Well, my issue is that freelook still feels kind of jerky compared to the orbit/zoom camera, which is even more apparent now. But I can certainly live with the way it works now, so I think this issue could be closed unless there are other opinions.

**Comment by Zylann** [comment]
I am working on smoothing camera translation in freelook mode, if it doesn't conflict with @reduz changes I will make a PR

**Comment by Zylann** [comment]
@reduz just tried the latest build with matrix interpolation, here are some notes:
- MMB orbit wiggles around focus point
- No way to turn it off or even configure its inertia (I find it annoying)
- Doesn't affect freelook orbit (I don't want it enabled here personally, but did you expect it to also work there?)
- Doesn't affect any kind of translation (I don't want it enabled in pan, but was it intented to not affect translation?) => the work I have locally affects inertia in freelook only and works so far, I'm about to make the PR

**Comment by novemberist** [comment]
@Zylann What you show in the Video is exactly what I was hoping for. I don't really understand why anyone would not like this smooth movement over the way freelook camera moves right now, but since you created a settinting for it, there shouldn't really be a problem...

**Comment by erwincoumans** [comment]
I just tried Godot 3 for the first time. Holding the right mouse button to maintain freelook gets very tiring on the mouse finger. Is there any way to just use ASWD free look without having to hold the mouse button? Some kind of toggle to enter/leave freelook?

**Comment by Zylann** [comment]
@erwincoumans that could be added easily, but which shortcut would be the default? (knowing that toggle mode would then ignore right-click mode)

**Comment by erwincoumans** [comment]
@Zylann Blender uses <SHIFT>F to go into free fly mode, and <ESC> to exit it. I'm new to Godot, so I don't know what keys are mapped etc. Another option is, once you are free flying, keep doing it until you hit <ESC>, as an option?

**Comment by Zylann** [comment]
@erwincoumans just F? No modifier? (I just tried in 2.78 but it doesn't do anything, that's the shortcut for making faces/edges) I wonder if that would conflict with other input in the editor, I remember issues about this, like https://github.com/godotengine/godot/issues/11997

**Comment by erwincoumans** [comment]
Blender uses SHIFT+F to enter free fly, and ESC to leave it. The < and > was removed by the github GUI.

Again, I would love to see the option to hit ESC to leave free fly in Godot, instead of holding the mouse all the time (increasing the chances for RSI)

**Comment by Zylann** [comment]
@erwincoumans I'll add these to give it a try

**Comment by akien-mga** [comment]
I'd say add SHIFT+F as a toggle (both to enter and leave freelook) + also ESC to leave it as a panic button :) (so two ways to leave it).

**Comment by erwincoumans** [comment]
Yes @akien-mga 
There is one more subtle issue: in Blender, you have the option to return to the original camera location if you press ESC or click right-mouse while in free-fly. Only if you click LEFT mouse button, you exit free-fly AND update the camera to the new position.
![image](https://user-images.githubusercontent.com/725468/32147887-887e4daa-bcab-11e7-9486-c5a1468cd689.png)

Of course you don't need to mimic Blender at all, but the option to return to original location may be nice.

**Comment by Zylann** [comment]
@erwincoumans I was going to just leave the camera where it is for now.

Also I found someone requested this option before, which got implemented:
`editors/3d/freelook/freelook_activation_modifier`
It basically adds an optional modifier to press in order to activate freelook, but implementing toggle mode would make it quite redundant (though it applies to the right-click mode).

**Comment by Zylann** [comment]
I got it to work!
But I found this super-weird issue https://github.com/godotengine/godot/issues/12497

**Comment by djrm** [comment]
i think godot is quite good in this regard now, so i guess this is fixed.
