### ISSUE TITLE
Control border visual issue due to antialiasing

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#10461]
**Operating system or device - Godot version:**
3.0 - https://github.com/godotengine/godot/commit/8fc6bb8f771c520c15320c3b4be561abc648d65d, macOS 10.12.6

**Issue description:**
Control borders sometimes are broken.
![button](https://user-images.githubusercontent.com/7645683/29489902-5a033106-8534-11e7-8fb9-e76785015bac.png)

**Steps to reproduce:**
Select and unselect control multiple times.

**Comment by bruvzg** [comment]
**Update:**
Similar on Windows 10, but I can't reproduce it on linux (Debian stable).
![win](https://user-images.githubusercontent.com/7645683/29494600-68c5832e-85b6-11e7-8216-dd5b9ce7b2fb.png)

**Comment by bruvzg** [comment]
**Update 2:**
This and #10459 are caused by: https://github.com/godotengine/godot/blob/8fc6bb8f771c520c15320c3b4be561abc648d65d/drivers/gles3/rasterizer_canvas_gles3.cpp#L695-L699

Removing `glEnable(GL_LINE_SMOOTH)` result in extra lines like in #10459 (Tabs) and broken borders (Name field left side).
![aaline](https://user-images.githubusercontent.com/7645683/29496571-e7fcc108-85dd-11e7-8436-c74bd037b826.png)

**Comment by bruvzg** [comment]
Looks like `_draw_generic(GL_LINE_LOOP...` intended to draw smooth polygon outline, but `polygon->points` actually contains triangulated mesh points instead of outline points. StyleBox use `canvas_item_add_triangle_array` to create polygons.

**Comment by groud** [comment]
ping @toger5 for #8899

**Comment by akien-mga** [comment]
I think it's more ping @reduz for 8fc6bb8f77 :)

**Comment by toger5** [comment]
this is caused by the new antialiasing. since style box flat has it's own antialiasing removed this one for now until it works.
