### ISSUE TITLE
improvement suggestions for AnimatedSprite

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#10468]
**Operating system or device - Godot version:**
Windows 7, Godot Engine v2.1.3.stable.official

**Issue description:**
I worked a lot with animatedSprite in my last project and this has bothered me all the time:

1) not having the possibility to flip a frame horizontally/vertically
![image](https://user-images.githubusercontent.com/10463138/29490584-f8a15dcc-8540-11e7-8ae7-055e92a3a974.png)
2) could not delete a frame with [delete] key (node get deleted)
3) after pressing on new animation button the animation text (New Anim) is not selected and cant be directly renamed
![animatedsprite_improvments](https://user-images.githubusercontent.com/10463138/29490676-7507386c-8543-11e7-9a58-89c5d293bcdc.gif)

4) selecting a AnimatedSprite node in tree doesn't show automatically SpriteFrames gui on the bottom when node has a SpriteFrames ressources (slow down the flow to quick edit an animation) (#10923)

What I'm not sure:

5. when animation only has one frame do I need to turn loop off or does the engine handle this automatically?

6. does it has an old discussion on having [Insert Empty (Before)] and [Insert Empty (After)]?
Its confusing and I need to consider with button I need to press.
Having only an [Insert Empty] and move the frame with [Up] or [Down] would be enough.

7. Is it possible to have button from animationPlayer?
![image](https://user-images.githubusercontent.com/10463138/29490866-08bc8020-854a-11e7-9a2e-92ee7fc70cf7.png)

**Comment by homer666** [comment]
No. 4 is something I run into a lot, and I also find it pretty distracting! However, I think this problem goes beyond AnimatedSprite, as I've seen this also happen with shaders. The relevant menus in the bottom panel don't appear at all unless you have the resource loaded in the inspector. I think a proper solution for this would involve some heavy modification to the editor's functionality and overall workflow, and I have no ideas as to what could be done.

**Comment by groud** [comment]
I's say I am ok with all those changes. But still, in my opinion, I think we should someday find a way to fusion the AnimationPlayerEditor with the AnimatedSpriteEditor. They serve quite a same purpose...

**Comment by Zylann** [comment]
I believe there is a reason for them to be separated, which is to give a specialized, uncluttered animation editor for sprites. Remember AnimationPlayerEditor has to deal with anything, properties, transforms, funcalls, interpolation modes, in 2D and 3D. So I wonder how a "merge" of the two would lool like, since AnimatedSpriteEditor was added after (I don't remember when though)

**Comment by groud** [comment]
> I believe there is a reason for them to be separated`

So do I, but they do share a lot in common anyway. In terms of usability, having two separate ways to animate things is a little bit counter-intuitive. But probably that the AnimatedSprite is a good compromise for now, as merging the two systems would probably need a huge refactoring of the animation system.

> So I wonder how a "merge" of the two would lool like, since AnimatedSpriteEditor was added after (I don't remember when though)

Something like what Unity does I guess.

**Comment by puppetmaster-** [comment]
I'm OK with the AnimatedSprite node. It helps a lot speed up my workflow.
I think point 1 - 3 should not be a big change and would help even more.

I agree with @homer666 that point 4 will need some larger changes. 

What about point 5 - 7?

**Comment by reduz** [comment]
No 4 I'm waiting for the inspector rewrite after 3.0 to re-think how these
should work..

**Comment by Rubonnek** [comment]
I want to work on this and I've been looking at `sprite_frames_editor_plugin.cpp` but I'm not sure where to start. I've been poking `SpriteFramesEditor::_animation_add` for a while to try and implement no. 3, but I can't seem to bring up the animation name editing box.

I'm still rather new to the editor source code.

**Comment by puppetmaster-** [comment]
I will close this issue, it is already very old and if there is still a demand I will apply for it again at the new dedicated Godot Improvement Proposals (GIP) (godotengine/godot-proposals) issue tracker.
