### ISSUE TITLE
Folder should be created automatically upon creating a project

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#10462]
Godot will create your project in whatever directory you have set, meaning that you must create the directory you want your project to reside in beforehand. Unity, on the other hand, creates a directory named after your project for you, and creates your project inside of that. You merely have to choose where you want the folder to reside (e.g. a common "Projects" folder.)

This is a lot more convenient, and I think this is expected behaviour. Also, I can imagine new Unity users will be taken by surprise when their project files are spewed all over the wrong directory. For this reason, I hope this behaviour is implemented before 3.0 goes stable.

**Comment by toger5** [comment]
Another idea would be to split the create project panel. 
on the right there would be a Folder tree on the left all the settings (basically just project name)
when selecting a folder it would show in green what the projects adds. thatn it is obvious if the projects adds another folder or expects you to create a folder.
all files which would be affected by that godot project could also be highlighted in blue or something else

**Comment by djrm** [comment]
@homer666 might be fixed by #10796

**Comment by homer666** [comment]
Yeah, that's close enough. Closing.
