### ISSUE TITLE
No easy way to restore default editor settings

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#10470]
**Operating system or device - Godot version:**
Arch Linux, Godot 3 master

**Issue description:**
I noticed there is currently no easy way to restore the default settings (per setting or globally) within the editor and project settings other than deleting config files and reloading the editor. I think this might become especially problematic for new users, because it's easy to mess things up and get confused or lost when playing around with certain values without any way of telling what the original sane settings were.

**Comment by Zylann** [comment]
Isn't there supposed to be "reload" arrows next to modified settings?

**Comment by novemberist** [comment]
I don't know. I've only seen those "reload" arrows when changing properties of instanced scenes so far, but they don't appear when changing project or editor settings, nor does there seem to be any other obvious way to reset those settings.

**Comment by novemberist** [comment]
Am I the only one who thinks this is a major issue in terms of usability or am I just too stupid to find the restore button(s) somewhere?

**Comment by reduz** [comment]
@novemberist In 3.0, besides the settings being a lot better organized, you can revert individual settings with a special button:
![image](https://user-images.githubusercontent.com/6265307/29527083-0dc027fa-866e-11e7-8ca1-1b79bdac0bbe.png)

**Comment by novemberist** [comment]
@reduz 
Problem is, this button is only there for project settings (despite me claiming otherwise, sorry about that) but not for editor settings. those can apparently not be reset to default values...

**Comment by reduz** [comment]
@novemberist Good point, it should be relatively easy to do the same for editor settings

**Comment by groud** [comment]
> I also think it would be a good idea to be able to restore all settings at once (in case one has changed many settings and just wants to reset everything to vanilla)
I don't know for that, I mean at a given point you rarely have all editor settings changed. And if you do, you probably know what you are doing. For me, having the possibility to revert values one by one is enough, as if you want a "fresh copy" you can just delete the .godot folder. :)

That being said, reverting settings one by one definitely is needed ! ;)

**Comment by reduz** [comment]
if you want to restore all settings at once, just edit project.godot and
delete all lines :)

**Comment by novemberist** [comment]
I may have played around with many settings but realized that I want to restore the "factory settings", maybe because for example something is messed up and I don't exactly know which setting may have caused this. It is then a little tedious to have to go through each category and click on each setting seperately to restore its default value.

Yeah, sure I can mess around with or delete hidden config files/folders, but can the average user (or the completely new user) do that? I'm not only considering my own use case here.

**Comment by groud** [comment]
Hum, I don't know... For me the settings are pretty well organised, and it is not like if a little change could prevent the editor from working fine.
In fact it is just that I can't find a reason why you would need to mess around with the editor configuration. usually when you change an option, you do it on purpose because you understand what it does.

Nonetheless, I think a reset button would be very useful for the keyboard shortcuts configuration.

**Comment by novemberist** [comment]
Yeah, maybe I'm overselling the issue a bit here, but I still felt like it would be something I would instintively expect to be there and it wasn't. Also something that doesn't sound like it requires a massive amount of work to implement and would be nice to have (especially for newbies, not only for edge cases)

That being said, I could live without it, though. If we get the ability to revert editor settings (and keyboard shortcuts) individually.

**Comment by groud** [comment]
> Also something that doesn't sound like it requires a massive amount of work to implement and would be nice to have (especially for newbies, not only for edge cases)

I totally agree on that.

> That being said, I could live without it, though.

And if it gets implemented, I wont complain either ^^. Provided we take care to add at least a confirmation dialog. I guess that if a developper also 

> would instinctively expect it to be there 

he could make a PR about that :)

**Comment by akien-mga** [comment]
Fixed by @djrm in the master branch.

**Comment by hoskope** [comment]
Problem i'm facing is that fonts in the editor were too small, so i edited fonts, which then became even smaller and now i can't reset settings. Every time i open editor i can't even see menu items and popup windows are also unreadable.
![whatsapp image 2018-04-05 at 11 15 33](https://user-images.githubusercontent.com/2360633/38356741-396ed53c-38c9-11e8-95c9-7c5f60b9424b.jpeg)

**Comment by DiweshThakur** [comment]
> Problem i'm facing is that fonts in the editor were too small, so i edited fonts, which then became even smaller and now i can't reset settings. Every time i open editor i can't even see menu items and popup windows are also unreadable.
> ![whatsapp image 2018-04-05 at 11 15 33](https://user-images.githubusercontent.com/2360633/38356741-396ed53c-38c9-11e8-95c9-7c5f60b9424b.jpeg)
>

**Comment by DiweshThakur** [comment]
> Problem i'm facing is that fonts in the editor were too small, so i edited fonts, which then became even smaller and now i can't reset settings. Every time i open editor i can't even see menu items and popup windows are also unreadable.
> ![whatsapp image 2018-04-05 at 11 15 33](https://user-images.githubusercontent.com/2360633/38356741-396ed53c-38c9-11e8-95c9-7c5f60b9424b.jpeg)
> 

Did You Find Any Solution?
