### ISSUE TITLE
Transparency on self-intersecting meshes not working (3.0)

### ISSUE THREAD

**Issue by stfnk** [godotengine/godot#10472]
**Operating system or device - Godot version:**
Windows 10 64bit, Nvidia Geforce GT 730M
Godot alpha1, master  7e5890d

**Issue description:**
Transparency on self intersecting meshes is not working in 3.0. I tried various combinations of texture import settings and depth draw modes, Opaque Prepass ignores transparency completely.
![transparency_bug](https://user-images.githubusercontent.com/29168665/29494391-af1e720c-85a9-11e7-81ea-453a23d18136.jpg)

**Link to minimal example project:**
[transparency_test.zip](https://github.com/godotengine/godot/files/1237029/transparency_test.zip)

**Comment by MrJustreborn** [comment]
I have the same problem with one of my scenes:
**Operating system or device - Godot version:**
Linux Manjaro 17.0.2 64bit, Nvidia Geforce GTX 550Ti
Godot alpha1

![bildschirmfoto_2017-08-25_17-30-03](https://user-images.githubusercontent.com/11594586/29761608-5148cb1a-8bca-11e7-9158-ce5403c369c3.png)
