### ISSUE TITLE
Changing the gizmos display behaviour in wireframe mode 

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#10478]
**Operating system or device - Godot version:**
linux mint, 2.1

**Issue description:**

it is weird to have the gizmos to display in wireframe
![2017-08-20 21 04 50](https://user-images.githubusercontent.com/10883749/29495158-a5cdc512-85eb-11e7-9bb9-f1c72e939524.png)
![2017-08-20 21 05 22](https://user-images.githubusercontent.com/10883749/29495157-a58c7634-85eb-11e7-8a41-34df30bd5643.png)

I think it is better to display the gizmos as normal.

**Steps to reproduce:**
display in wireframe

**Comment by nunodonato** [comment]
@akien-mga perhaps kicking this to a milestone a bit further down the road? :D

**Comment by akien-mga** [comment]
That's likely the same kind of issue as #8485. This will need render layers (likely in the Vulkan release) to fix it.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2138, as feature proposals are now tracked on the Godot proposals repository.
