### ISSUE TITLE
overloaded functions do not work in shader

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10474]
you can not write two functions with the same name like:
```glsl
vec2 some_func(vec2) {}
vec3 some_func(vec3) {}
```
they are supposed to do the same, but with different types, but you need to write two functions with separate names like some_func_2 and some_func_3.

this is not hinted by the editor, shader just fails and draws white shape on the screen.

is it intended or it needs fixing? in glsl you can overload functions.

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by Bauxitedev** [comment]
@akien-mga Yes, it is. 
E.g. take this shader:
```
shader_type canvas_item;

float saturate(float value) //Try commenting this function and observe it works
{
	return clamp(value,0.0,1.0);
}

vec4 saturate(vec4 value)
{
	return clamp(value,0.0,1.0);
}

void fragment()
{
	COLOR = saturate(vec4(1,0,0,1));
}
```

There's no error, just the shape is drawn pure white and wrongly transformed. Comment the first overload and you'll observe it works.

**Reproduction project:**
[shader_overload_bug.zip](https://github.com/godotengine/godot/files/2214366/shader_overload_bug.zip)

**Comment by CptPotato** [comment]
I ran into the same issue just now and it seems like trying to overload functions even breaks other shaders.

**Comment by clayjohn** [comment]
In 3.2 there is now an error when you try to overload a function (I don't know which version it was added in).

Accordingly, I think it is best if this continues as a proposal in the proposals repository https://github.com/godotengine/godot-proposals as we are now tracking all feature proposals there.
