### ISSUE TITLE
Smooth scrolling in the script editor is too slow and not responsive enough

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#10489]
The smooth scrolling that was recently added (and enabled) by default in the script editor is *way* too slow and makes it much harder to use; it seems to ignore mouse wheel events while scrolling (which is not instant when smooth scrolling is enabled), which can make scrolling feel less responsive as well (if you try scrolling in the opposite direction while it is scrolling, you might have to wait up to a second for it to react).

Also, if you scroll a lot in a short time frame (which is doable with mice having "freewheel" modes), it will keep scrolling for several seconds after you stopped the mouse wheel.

**Comment by toger5** [comment]
It works pretty well with trackpads. (just as an additional information for the one who wants to fix it. So that the trackpad behaviour does not get hurt.)

**Comment by Zylann** [comment]
I gave a try to the script editor, and scrolling is still not as responsive as a normal text editor. But the culprit is again the "update only changes" vs "update always". When I select "update always", the experience is a lot better, while "update changes" seems to miss updates, and requires me to scroll more.

https://www.youtube.com/watch?v=pO3j4KdqEhQ&feature=youtu.be

**Comment by Ark2000** [comment]
![OF065@S9D2Z`{} MPEM{ 9S](https://github.com/godotengine/godot/assets/21126555/e7d427e2-9a95-4c58-b3a0-72d780534731)

Smooth scrolling should be disabled by default, I have no idea why this feature even exists.

**Comment by Zylann** [comment]
I use smooth scroll in VSCode, which behaves better. In Godot 4 smooth scrolling feels like speed is getting clamped too soon when scrolling fast but somehow keeps some kind of confusing momentum, while in VSCode it just accelerates properly and behaves like you'd expect.
