### ISSUE TITLE
Clear script does not work for manually duplicated scenes

### ISSUE THREAD

**Issue by zinkkrysty** [godotengine/godot#10486]
**Operating system or device - Godot version:**
macOS 10.12.6
Godot 3.0.alpha (build from 3bea3256f5def126b2b6d639ed70c4ddc3990344)

**Issue description:**
I wanted to duplicate a scene. I couldn't find a way to do it from the editor so I did it from the file manager. But then I couldn't replace or clear the script file for the new scene.

**Steps to reproduce:**
1. I copied the .tscn file and gave it a new name. 
2. Then I opened it inside Godot and saw that the script attached was from the original scene. 
3. I wanted to clear the script and replace it with a new .gd file (for the new scene), so I pressed clear script button in the Scene panel. 
4. Nothing happened (script is still attached). There is no way right now that I can say it should use a new script instead of the one from the original scene. "Attach script" is not working either (just opens the existing script, from the original scene)

**Comment by auztec** [comment]
If I am not getting this wrong or it's on a old version of Godot. You should able to copy " a scene" with "Meta+D" on mac, or if that does not work you can try "instancing another Scene." 

Here is the docs for that : 
https://godot.readthedocs.io/en/latest/learning/step_by_step/instancing.html

ref:
https://godotengine.org/qa/3942/how-can-i-duplicate-a-node-including-all-its-children

**Comment by zinkkrysty** [comment]
@auztec I was trying to completely copy a scene, not just make another instance of it. So if I have a label inside that scene, I want to copy it to the other scene (same position, same properties) , but where I can modify the text and node name (without affecting the first scene). 

I know I could restructure my project so I don't have "nearly the same scenes with tiny differences", but it strikes me if Godot does not have simple functionality of copy and paste scenes and nodes in the editor. 

And by the way I am using an alpha version of Godot 3, I just thought the functionality of clearing script was broken, hence the issue.

**Comment by Zireael07** [comment]
Instancing != copying a scene.

@zinkkrysty Have you tried opening the scene and doing save as? And then see if clear script is broken for your second (saved as) scenee?

**Comment by zinkkrysty** [comment]
@Zireael07, thanks, that worked! I didn't think of using the "Save as.." to duplicate a scene. 

Could it be an idea to add "Duplicate" perhaps to the context menu in the FileSystem?

![image](https://user-images.githubusercontent.com/570771/29578611-1d119966-8770-11e7-81cc-9c63dfafa384.png)

Also, I would expect copy and paste to work with almost everything in the editor. Is that in the plan somehow?

**Comment by Zireael07** [comment]
@zinkkrysty Glad to hear that save as worked. Now back to the mystery of why copy and paste broke some functionality... (as effectively copying, pasting and renaming should be the same as save as...)

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by DualMatrix** [comment]
Clearing the script works in master
