### ISSUE TITLE
Ctrl + C inside the script editor should copy current line if there is no selection

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#10485]
**Operating system or device - Godot version:**
Godot 2.1.3
Godot 3 (built from master)

**Issue description:**

Ctrl + C only works if something is selected
Ctrl + C should work just like Ctrl + X, if there is no selection it should copy the whole line

**Steps to reproduce:**
Open a script file
go to any line that has something written
press Ctrl + C (without having text selected)
press Ctrl + V
see that the line was not copied to the clipboard

**Comment by reduz** [comment]
Is this standard behavior?

**Comment by Calinou** [comment]
> Is this standard behavior?

It looks like it is – both Atom and Visual Studio Code support this by default. JetBrains IDEs (like IntelliJ) have similar functionality: pressing <kbd>Ctrl+C</kbd> without any selection will select the line the cursor is on, then copy it (unlike Atom and Visual Studio Code, which don't perform any selection in the process).

**Comment by HummusSamurai** [comment]
It is also standard behaviour for `Ctrl+X` to cut the current line.
