### ISSUE TITLE
Light emission on spatial materials works strange in Unshaded mode

### ISSUE THREAD

**Issue by maxim-sheronov** [godotengine/godot#10480]
**Operating system or device - Godot version:**
Arch linux - master branch

**Issue description:**
If Unshaded flag is set, light emission uses Albedo instead of Emission. And emission options does nothing in this case.
Without Unshaded flag all works as expected.

That can be reproduced if enable Glow effect on camera and set color values to more than 1.0 to have HDR effect.

If Unshaded mode assumes to not use Emission, maybe Emission group should be hidden.

**Comment by reduz** [comment]
This is not a bug, and agreed i suppose everything related to shading could be hidden..

**Comment by reduz** [comment]
kicking to 3.1 anyway, not urgent

**Comment by reduz** [comment]
this is rather easy, check the SpatialMaterial::_validate_property and hide stuff that is irrelevant (metal, rough, ao, etc) when unshaded is set by setting property usage to 0:

https://github.com/godotengine/godot/blob/master/scene/resources/material.cpp#L1345
