### ISSUE TITLE
Can not compile godot in MacOS

### ISSUE THREAD

**Issue by heibor** [godotengine/godot#10495]
**Operating system or device - Godot version:**

MacOS Sierra

**Issue description:**

can not compile Godot engine.

**Steps to reproduce:**

Use scons platform=osx to compile, got these errors:

[ 86%] Compiling ==> core/global_defaults.cpp
core/global_defaults.cpp:1:10: fatal error: 'global_config.h' file not found
#include "global_config.h"
         ^
1 error generated.
scons: *** [core/global_defaults.osx.tools.64.o] Error 1
scons: building terminated because of errors.

**Comment by akien-mga** [comment]
`core/global_defaults.cpp` is an obsolete file from a previous build, you can delete it and that will fix the build (if not, also delete the next file that will trigger a similar error, etc.).

**Comment by Rubonnek** [comment]
You can also open a terminal window and do:

```shell
cd $godot_repo_root
git clean -xdf
```
And run `scons` again for a brand new build.

**Comment by akien-mga** [comment]
Indeed. At any rate, it's not a bug, just a transient issue when updating from an old build.
