### ISSUE TITLE
Max floor angle as parameter on move_and_slide 

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#10491]
**Godot version: 2.1.4 beta 3**

**Issue description:**
`move_and_slide` was added on 2.1 but it has a fixed value for slopes to be considered floor (~45 degrees), making it as a parameter like on Godot 3 could be better for a more flexible floor and wall detection.

That floor angle affects ceiling detection too on 3, and the value is fixed on 2.1 too.

**Comment by tagcup** [comment]
There was a separate ceiling parameter at some point (see #8395 #8259) but apparently it disappeared recently (not sure why)

**Comment by tagcup** [comment]
OK so it was removed in 2e73be9 by @reduz with the explanation "Fixed KinematicBody API to make it the same as 2D." I guess it should've been the other way around, the 2D API had to be fixed to make it the same as the recently-updated-3D one.

**Comment by eon-s** [comment]
@tagcup I remember a discussion about that, but this thing is for 2.1 which have the angle hardcoded on the recently added method (for 2D only).

**Comment by tagcup** [comment]
Yeah, but wasn't it ported back from 3.0 code?

**Comment by eon-s** [comment]
The PR says "ported from 3.0" but the code says "ported from 2.2" to me.

**Comment by eon-s** [comment]
Fixed by #10744
