### ISSUE TITLE
Java(JVM)&Kotlin as Script Language.

### ISSUE THREAD

**Issue by keito940** [godotengine/godot#10498]
Since the native language was already supported,
Java and Kotlin are used in various environments, Android and others.
Even Godot does not it only have to support Java and Kotlin as a split language?
D programming language and C# seem to be already supported.
Answer plz.

**Comment by akien-mga** [comment]
Apart from C#, all script language bindings are out of scope of this repository and the work of the core developers, so no need to open issues requesting all of them. With 3.0, we already have covered the main languages that we want to support - all further bindings are very welcome but should be handled in their own repositories. Feel free to open a topic on [reddit](reddit.com/r/godot/) or the [Godot forums](https://godotdevelopers.org/forum/) to see if you can gather like-minded developers to work on Kotlin bindings with you.

**Comment by keito940** [comment]
Forum Discusion Create Now.
