### ISSUE TITLE
D Programming Language as Script Language.

### ISSUE THREAD

**Issue by keito940** [godotengine/godot#10494]
Hello, I am a Japanese user.
Do you know the D programming language?
You do not need to know. If you look at the site called https://dlang.org/, it will be easy to understand.
The basic syntax is the C language itself, but I am dealing with C++, Java, Python (which was the base of GDScript) and C# which I plan to support in 3.0.
The D language itself is a native compiler, but if you prepare a compiler infrastructure that is compatible with Godot's multi-platform (it is OK with LLVM-based LDCs), you can leave portability, Godot's strength, Let's see. What do you think?

**Comment by akien-mga** [comment]
There's already someone working of D support via GDNative bindings.

**Comment by keito940** [comment]
So, do you mean that Rust and Go languages ​​and Swift also support GDNative?

**Comment by volzhs** [comment]
@keito940 I guess this article will help.
https://godotengine.org/article/dlscript-here

**Comment by keito940** [comment]
tnx.

**Comment by ISylvox** [comment]
1.) C#/Mono bindings :
https://github.com/neikeq/GodotSharp

2.) D language bindings : 
https://github.com/GodotNativeTools/d_bindings

3.) Go language bindings : 
https://github.com/ShadowApex/go-godot

4.) Nim language bindings : 
https://github.com/pragmagic/godot-nim

5.) Rust language bindings : 
https://github.com/GodotNativeTools/rust_bindings

**Comment by akien-mga** [comment]
As mentioned in #10498, apart from C# support all other language bindings are outside the scope of this repository, so closing this issue. Specifics of the D bindings can be discussed at https://github.com/GodotNativeTools/d_bindings

**Comment by 221V** [comment]
hello !
how i can use haskell with godot?
