### ISSUE TITLE
Debugger fails on master -error code 3

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#10503]
**Operating system or device - Godot version:**
Win x64 bit
Godot 3.0 master (d8cd849)

**Issue description:**
Cannot run project from editor because debugger fails to connect.

In editor console:
 platform\windows\stream_peer_winsock.cpp:202 - Server disconnected!

The console behind the editor window is slightly more informative:
Remote Debugger: Connection failed with error status '3', retrying in 1 sec. x2
Remote Debugger: unable to connect
shit?:invalid argument

**Steps to reproduce:**
Try to run a project from editor.

**Link to minimal example project:**

**Comment by RandomShaper** [comment]
Compiled with MSVC?

**Comment by Zireael07** [comment]
I used scons, I have no idea what it uses at the backend.

**Comment by akien-mga** [comment]
Well you should know what development environment you installed, Windows is far from coming pre-installed with a shell having scons and a C++ compiler out of the box ;)

**Comment by Zireael07** [comment]
I just followed this tutorial: http://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html (I already had VS 2015 so the only thing I had to add was scons)

**Comment by akien-mga** [comment]
> I already had VS 2015

That's the information @RandomShaper was looking for ;) MSVC = Microsoft Visual C++, which is the compiler of Visual Studio.

**Comment by RandomShaper** [comment]
Too little sleep last night. XP

**Comment by RandomShaper** [comment]
Just to be sure, have you allowed Godot through the Windows firewall when asked?

**Comment by Zireael07** [comment]
I don't have a Windows firewall and the firewall that I do have was never triggered by Godot (it lets everything through unless it's suspicious or I explicitly tell it to block this thing)

**Comment by RandomShaper** [comment]
Sorry if I have insulted your intelligence. :)

Could you try disabling or even uninstalling your current firewall software and try again? I know it's pretty painful, but I hope you can keep your settings so you can reinstall in a breeze.

The reason for suggesting that is that network-related software may add stuff to the Winsock stack and maybe that's confusing the Godot TCP implementation somehow. Maybe certain non-actually-error codes are being returned and they are not being properly handled.

Now I think of it, near the code line you mentioned, there's the very check I'm talking about. You could debug and report what error code `WSAGetLastError()` is returning (instead of uninstalling your firewall).

**Comment by Zireael07** [comment]
I can't get gdb to cooperate, but I noticed one more thing: the project this is happening to was originally exported from 2.1.4. alpha. The issue is not happening to my very much testing project that was started from scratch in 3.0.

Something not getting exported right?

**Comment by Faless** [comment]
@Zireael07 can you check what is the value you see in `Settings -> Editor Settings -> Network -> Debug -> Remote Host`, and `Settings -> Editor Settings -> Network -> Debug -> Remote Port` and report them here?

**Comment by Zireael07** [comment]
host is fe80:0:0:0:44d5:1e7c:365a:3631, port 6007

And btw when I went to check those today, the project ran fine with no errors, ugh unreliable debugger connections in Godot seem to be a thing. It doesn't work, then it works, then it doesn't....

**Comment by Faless** [comment]
Try setting it to 127.0.0.1 (leave the port as it is) and check if the
connection is still unreliable

**Comment by Zireael07** [comment]
Haven't had time to check, but I assume fixed by #11378.
