### ISSUE TITLE
Adding/changing inputs for default actions does not save them.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#10502]
**Operating system or device - Godot version:**
Ubuntu Linux 17.04 64-bit.
Godot 3.0 pull 1be30f3.

**Issue description:**
As detailed per #9472 - custom actions and their inputs can be added and saved. However, adding (or changing) default actions (for example ui_down) does not save them. They are added to the project until you quit out of it. The next time you enter the project they are not there, because they were not saved.

**Steps to reproduce:**
Add or change any input to any default action in the project settings "Input Map" tab.

**Comment by reduz** [comment]
thanks! :D

**Comment by leezh** [comment]
I've tracked down the problem here:
https://github.com/godotengine/godot/blob/77ec304966436405e2975f7da480846cc074f838/core/project_settings.cpp#L676-L677

As the arrays are always copied by reference, modified arrays will always be true.

**Comment by HummusSamurai** [comment]
Should I post a tracker for all the issues related to Input Map?
