### ISSUE TITLE
Shadow problems!

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#10504]
Win10, Nvidia 960m godot 3

When i tested my old project some problems were like spotlight didn't worked when shadow was turned on and omni were showing some holes and directional light shadow was far from contact.

But when i build new scene some problems disappeared like spotlight one and omni hole yet i can see see some problems like spotlight have some stripy line at the side of cube, directional light contact problem omni spike line and non gradient shadow as i think omni should have gradient shadow!

![screenshot 86](https://user-images.githubusercontent.com/13883739/29524892-b12b4786-86ae-11e7-8d8c-3fb45c3598b8.png)
![screenshot 82](https://user-images.githubusercontent.com/13883739/29524890-b122fbb2-86ae-11e7-9ed2-4453ab439bc3.png)
![screenshot 83](https://user-images.githubusercontent.com/13883739/29524894-b14e2918-86ae-11e7-9d94-100084a297af.png)
![screenshot 84](https://user-images.githubusercontent.com/13883739/29524891-b128de88-86ae-11e7-84d8-d37643c9a40c.png)
![screenshot 85](https://user-images.githubusercontent.com/13883739/29524893-b1328528-86ae-11e7-83db-34443892e221.png)

OLD PROJECT in new editor
![screenshot 88](https://user-images.githubusercontent.com/13883739/29524925-c43ac9c8-86ae-11e7-919e-820719af1001.png)
![screenshot 89](https://user-images.githubusercontent.com/13883739/29524927-c4f90d5c-86ae-11e7-9af6-c35ee5a433ff.png)
![screenshot 87](https://user-images.githubusercontent.com/13883739/29524926-c49afcb2-86ae-11e7-90a1-097e238d851f.png)
[shadow.zip](https://github.com/godotengine/godot/files/1239168/shadow.zip)

**Comment by reduz** [comment]
This is not a bug, this is how shadow mapping works. for the self shadowing
you can adjust the bias or invert face culling to get something you like.
For less jaggy outlines you can either increase shadow resolution or
enhance the filter to PCF13

**Comment by reduz** [comment]
there is a shadow mapping tutorial in the godot docs, i suggets you check
that.. it needs to be updated to 3.0 though

**Comment by gamergamesz** [comment]
okz finally i got what i was doing wrong ! still a bit trouble with directional but i am trying the settings ! thank you!
