### ISSUE TITLE
ViewportTexture sampling artifacts

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10500]
there are already bugreports about ViewportTexture, but this one is more interesting.
i failed to sample ViewportTexture directly, because it returns 0 for every pixel. I think this is related with other issues. But when i assigned ViewportTexture to anothe Sprite on the scene, i was able to sample it. But with artifacts. This is when Viewport was set in 2d mode (which i assume is correct when it is used with Sprite node). But in 3d mode there aren't any artifacts.

Setting Viewport to unsahded does not fixes this issue. Only 3d mode does.

please have a look here https://github.com/curly-brace/Godot-Simplex
first screenshot demonstrates what artifacts look like. compare the image on the sprite in the corner, with actual values returned by get_pixel and value applied as Y coord of a tile. there are some sort of steps (like on light artifacts or shadows)
scene named 'test_3d', set Viewport mode to 2d and run the demo.
you can edit the script on the root node to set scale of noise (to see artifacts more clearly) and setup the script to update only once (there is a commented flag)

also. using sign() on the sampled value shows that some of them are even negative

**Comment by curly-brace** [comment]
Scott on discord did quite a good research on this issues
```
You're right. i think its a bug. if you have the viewport in  2D mode; even though its a black and white image, the red / blue / green values aren't even similar. i think it might be some sort of issue in the get_pixel() function, where maybe the pixels are stored in r8g8b8, and are poured into float values, which i think maybe be 16-bit (not sure if thats the actual issue, but thats really what it seems)

in your original example, if you sample the green channel instead of the red channel, you just get garbage. with the blue channel, you get something of a blend between garbage and simplex.
```

**Comment by Calinou** [comment]
Closing due to lack of response (see Akien's comment above).
