### ISSUE TITLE
Crash when script tab is opened with no scripts

### ISSUE THREAD

**Issue by Dizeeee** [godotengine/godot#10517]
**Operating system or device - Godot version:**

Solus 3 Stable - Github latest

**Issue description:**

Godot crashes when script tab is opened without any script in the current project

**Steps to reproduce:**

Create a new project and open the script tab without making any changes to the project

**Comment by akien-mga** [comment]
Can't reproduce it on Mageia 6 x86_64 with bb41e142, compiled with GCC 5.4.0.

What's your compiler?

**Comment by Dizeeee** [comment]
I followed all instructions listed [here](http://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html)

**Comment by akien-mga** [comment]
That doesn't tell me what compiler you are using :)

**Comment by novemberist** [comment]
I can reproduce this on Arch Linux, when using gcc 7.2.0 to compile (clang 4.0.1 works fine)

**Comment by Dizeeee** [comment]
I'm using gcc 6.4.0

**Comment by hpvb** [comment]
This is the same problem as #10515 working on a PR.
