### ISSUE TITLE
There are no buttons nor a label at the bottom of the screen in the Material Tester demo

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#10513]
**Operating system or device - Godot version:**
Arch Linux - Godot Master Branch 4717d37bfa867d8cdcd4805967324978da6701b7

**Issue description:**
Take a look at the bottom of the screen:
![nobuttonsnorlabel](https://user-images.githubusercontent.com/8337880/29534920-eb490c10-8685-11e7-99c6-42a9f780e321.png)

There are no buttons on either side,  nor a label in the middle. I expected to see the same label and buttons I saw at the bottom back on #10311.

This issue was introduced between the 3bea3256f5def126b2b6d639ed70c4ddc3990344 and 4717d37bfa867d8cdcd4805967324978da6701b7 commits. I'll run a `git bisect` at some point to pinpoint the commit that introduced this problem.

**Steps to reproduce:**
Run the [material_testers](https://github.com/godotengine/godot-demo-projects/tree/master/3d/material_testers) demo.

**Comment by Rubonnek** [comment]
I'm still bisecting, but the label position started going downhill at 26137f37ebb4ddf005950b1ebd0c153738bd7fed

![downhill](https://user-images.githubusercontent.com/8337880/29544184-56c842a2-86b4-11e7-84bb-fac45e8236bd.png)

**Comment by akien-mga** [comment]
It might be another regression from @groud's anchoring changes ;)

**Comment by groud** [comment]
I haven't checked the demo yet, put probably, yes.

**Comment by groud** [comment]
Opened a PR in the demo repository.
Please open the issue in the demo repository next time. ;)

**Comment by Rubonnek** [comment]
@groud Please test your changes next time :P

**Comment by groud** [comment]
What do you mean ? The PR in the demo repository does not work ?

Or you mean for the anchoring system changes ? ^^

**Comment by Rubonnek** [comment]
I mean, the anchoring changes. It's impossible for anyone to open up an issue in the right repository when they don't know where the bug lies.

**Comment by groud** [comment]
> I mean, the anchoring changes. It's impossible for anyone to open up an issue in the right repository when they don't know where the bug lies.

That's quite true :)

The fact is that when you open the demo project with the editor, you could have seen that the buttons were just moved a little it down, a problem which is not a bug reproducible in another project. That's why I forgot that you could have think it's related to the engine. Anyway, that's not important ^^

> @groud Please test your changes next time with the demos :P

I comply with the test-in-production great methodology, sometimes used by Godot. 
But actually, that was a good move: as my changes were easily visible, I let people like you spot the missing bugs instead. All of this was part of my machiavellian plan to make other people freely work for me. :p

**Comment by Rubonnek** [comment]
> The fact is that when you open the demo project with the editor, you could have seen that the buttons were just moved a little it down, a problem which is not a bug reproducible in another project.

Good to know. Turns out I haven't tested any other project with buttons.

> I comply with the test-in-production great methodology, sometimes used by Godot.

Can't argue with that. That's the best methodology out there to get some serious testing.

> All of this was part of my machiavellian plan to make other people freely work for me. :p

Can't argue with that either. I would do the same. :p
