### ISSUE TITLE
Can't open script if it's not using the default script template

### ISSUE THREAD

**Issue by ezefran** [godotengine/godot#10522]
**Operating system or device - Godot version:**
Elementary OS 0.4.1 - Latest version (compiled from github's files)

**Issue description:**
If you attach a new script with any template other than the default to a node, then that script cannot be opened and the console throws the following error:
 _editor/plugins/script_editor_plugin.cpp:1699 - Condition ' !se ' is true. returned: false_

**Steps to reproduce:**
Attach a new script to a node with any template different than the default and try to open it.

**Link to minimal example project:**
It can be reproduced with a new project.

**Comment by ezefran** [comment]
I fixed it by deleting the _"script_templates"_ folder in _"~/.godot"_ and running Godot afterwards.

The template files were empty. They weren't written when they were created the first time for some reason.

**Comment by mhilbrunner** [comment]
Works fine for me in Godot 3.0 beta 2. Close and reopen if it still happens for someone?
