### ISSUE TITLE
[Forum] Faulty e-mail address validation.

### ISSUE THREAD

**Issue by Evi1M4chine** [godotengine/godot#1052]
phpBB’s address validation is faulty. The specification for e-mail addresses does not limit the name part (before the @) in any way.

Google supports “+” in e-mail addresses, to add anything one likes to the name. E.g. as a marker, to use a different address on every login, and see where senders got the address from.

But phpBB blocks this, and probably limits the allowed characters in other pointless ways.

Could you just change the regular expression in there to allow any character before the “@”?

**Comment by vnen** [comment]
This does not happen anymore in the new website.
