### ISSUE TITLE
Empty segment in the Script Editor's Debug menu

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10528]
**Ubuntu 17.04 - Build: fc8abf7**

**Issue description:**
Self-explanatory:

![screenshot at 2017-08-21 21-28-05](https://user-images.githubusercontent.com/30739239/29543640-e64bf73a-86b8-11e7-9c14-17d315d3eb38.png)

**Comment by akien-mga** [comment]
@groud @toger5 @djrm

**Comment by groud** [comment]
I'm on it
