### ISSUE TITLE
Deleting a portion of text in the Script Editor results in visual glitches with the text above it

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10529]
**Ubuntu 17.04 - Build: fc8abf7**

**Issue description:**
This will probably explain it better:

![bug](https://user-images.githubusercontent.com/30739239/29544053-f366de96-86bb-11e7-9a6a-167b2dccbfdb.gif)

**Comment by akien-mga** [comment]
@Paulb23

**Comment by Paulb23** [comment]
Going to leave some notes here if someone else wants to tackle this as I won't be able to until the weekend.

This occurs when scrolled to the bottom (or maybe when enough text is removed to make it the bottom?) and `scroll_past_end_of_file` is disabled.

When the text is deleted with `smooth_scroll` off the text is "pushed up", making the scroll out of bound  and creating a empty space underneath the text. When clicking a line to place the cursor it thinks the scroll bar is in bounds so end up selecting a line miles above your click.

When `smooth_scroll` is enabled the text is "pushed down" creating the empty space at the top. When clicking a line to place the cursor it updates the `cursor.line_ofs`. making it draw the text.

I think the change need to be made in [text_edit.cpp, adjust_viewport_to_cursor()](https://github.com/godotengine/godot/blob/916fd473431f4672262ae1eb84f1aa6b68e25915/scene/gui/text_edit.cpp#L3162) To make sure the scroll is not out of bounds and update `cursor.line_ofs` so it will draw the text.

Enabling `scroll_past_end_of_file` will fix it.
