### ISSUE TITLE
editor fails to compile and run on windows and may be mac

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10537]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 x64 c2346b92b285a50bb85fe935763d25e043fa3e5c

**Issue description:**
I saw that svg support was merged 8 hours ago and was very agitated to test it, went to Calinou's repo and found out that there is only linux executable. Then i've downloaded latest master and launched compilation (vs2017) and it finished, but gave me only 32 bit exe. So i've launched it, created a new project and.... it crashed while opening the main editor window with:
Unhandled exception at 0x77569AAA (ntdll.dll) in godot.windows.tools.32.exe: 0xC0000374: A heap has been corrupted (parameters: 0x775A58E8)

**Comment by curly-brace** [comment]
seems like it is fixed

**Comment by MasonAsh** [comment]
@curly-brace The PR I made fixes the build system for Visual Studio, however, it does seem that there is still a runtime crash when compiled with Visual Studio related to memory issues with the SVG image loader.
