### ISSUE TITLE
Hidden lights and meshes still contribute to the GIProbe solution

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#10535]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10 and LinuxMint...current Godot3 builds

**Issue description:**
When using lights, meshes and meshes with emission materials and the giprobe, if they are set as non-visible in the scene tree, they still are seen by the GIProbe calculations.

In the following image, the hidden objects(light, cube and mesh emitter) on the right still contribute to the gi solution, when they are expected not to. This is problematic when setting up the lighting for a scene, as you often want to toggle objects/lights on and off when assembling a scene. 

Currently you have to delete an object(or constantly fiddle with material or light settings) to know exactly what the result will be. Note that you can also see the hidden objects in the giprobe reflections (reverse vampire effect!)

![hidden_objects_gi](https://user-images.githubusercontent.com/7741669/29546686-20b02a06-8739-11e7-8577-51843962a001.jpg)

**Steps to reproduce:**
- hide objects(mesh, light, mesh light) within a giprobe setup.

**Link to minimal example project:**

[hidden_emission_test.tar.gz](https://github.com/godotengine/godot/files/1240650/hidden_emission_test.tar.gz)

**Comment by reduz** [comment]
Err eeps, sorry this is fixed

**Comment by bojidar-bg** [comment]
Reopening as not fully fixes as per above comment.

**Comment by reduz** [comment]
This reminds me i should restore the bias as default and remove normal bias

**Comment by groud** [comment]
This should be fixed now, can you confirm @fracteed ?

**Comment by fracteed** [comment]
@groud yes it all works as expected now :) Thanks @hi-ogawa for fixing this!
