### ISSUE TITLE
Texture mapping emission does not work with GIProbe

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#10534]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10 and Linux Mint...current master build of Godot3

**Issue description:**
When using a texture map in the emission channel, there is no contribution to the GIProbe calculation.

In the following image, the mesh on the left has 3 separate materials (as polygroup selections). It has no maps, just color in the emission channel. It is working as expected.

The mesh on the right has one single material with a texture map in the emission channel. It should give a similar result to the mesh on the left but contributes nothing to the gi solution. The emission color is black which overrides the map color.

![emitters1](https://user-images.githubusercontent.com/7741669/29546117-a30bfd58-8735-11e7-9ed5-5bde5da83f11.jpg)

**Steps to reproduce:**
- add an image in the emission channel of a spatial material. 
- add this material to a mesh
- add a giprobe

**Link to minimal example project:**

[map_emission_test.tar.gz](https://github.com/godotengine/godot/files/1240608/map_emission_test.tar.gz)

**Comment by tagcup** [comment]
This is actually still not fixed, because the emission texture is always invalid due to wrong reference type, thus still doesn't contribute to GI at all.
Anyway I'm resubmitting my previous changes in #12938 as a new PR #12960 to actually close this.

**Comment by fracteed** [comment]
Great to have this working correctly now...cheers!

**Comment by kakoeimon** [comment]
This was not properly fixed.
If I use small uv with many colors I get wrong output. (White emission on the GIProbe)
![emission_problem](https://user-images.githubusercontent.com/13662414/34148857-b0f4063a-e4ab-11e7-9366-753e77c91654.png)

Here is the modified version of the example project with two new objects. One uses a png with colors as columns (this is the problematic one) and the othe uses a png with only one color.

**Comment by kakoeimon** [comment]
OK I found the problem. GIProbe and BakedLightmap resizes the texture at 128x128 size. As it looks like even changing the the Subdiv to a higher value from 128, it is going to be scaled again to 128.
So the solution is to use a texture 128x128.
