### ISSUE TITLE
Fatal Error: Cannot open include file 'editor_icons.h' and 'Error 1136'

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#10532]
**Operating system or device - Godot version:**

Godot Alpha 3.0, Windows 10

**Issue description:**

Frequently I update the Godot Engine by the source code and recently around 51% of the compiling process, it ran into this fatal error:

```
editor_icons.gen.cpp
editor\editor_icons.gen.cpp(1): fatal error C1083: Cannot open include file: 'editor_icons.h': No such file or directory
scons: *** [editor\editor_icons.gen.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```
So I checked the 'editor_icons.gen.cpp' file and see that the `#include editor_icons.h` is written in the code but discovered that the file it needs could not be found at all. Is the editor_icons.h missing from the source code or somehow accidentally deleted?

So I tried to redownload the source code from Github again, but this time the fatal error code generated this message instead:

```
[Initial build] Linking Static Library ==> editor\editor.windows.tools.64.lib
editor\editor_icons.gen.h : fatal error LNK1136: invalid or corrupt file
scons: *** [editor\editor.windows.tools.64.lib] Error 1136
scons: building terminated because of errors.
```

At the moment, I can't compile the latest Godot Engine from the source code. Hopefully what I have explained can help figure out how to solve this issue.

**Steps to reproduce:**
Compile the source code, using any native build command prompts provided by Visual Studio.

**Comment by djrm** [comment]
just delete that file: editor_icons.gen.cpp thats the old icons file

**Comment by Corruptinator** [comment]
I'll check it out.

**Comment by Corruptinator** [comment]
I have deleted the editor_icons.gen.cpp, but now the other error shows up:

```
[Initial build] [91mLinking Static Library [95m==> [93meditor\editor.windows.tools.64.lib[0m
editor\editor_icons.gen.h : fatal error LNK1136: invalid or corrupt file
scons: *** [editor\editor.windows.tools.64.lib] Error 1136
scons: building terminated because of errors.
```
what happened is that during the compilation, it generated a new file: "editors_icons.gen.h" and the fatal error message says that it is invalid or corrupt. So I deleted that file and tried compiling it again for the second time and the same error message is shown again, along with generating the same editors_icons.gen.h file.

Compiling source can be complicated sometimes...

**Comment by djrm** [comment]
the editor_icons.gen.h is autogenerated and necessary, i really dont know what is causing your problem (im not faminiliar with windows compilation), but you can open that file and see if it is actually corrupt.

**Comment by MasonAsh** [comment]
Can confirm I'm facing the same issue right now. Additionally I did not receive this error on a slightly older version of the master branch.

**Comment by Rubonnek** [comment]
If you have the code in a git repository, have you tried this?

```shell
$ cd $godot_repo_root
$ git clean -xdf
```

And run your `scons` command again. The commands above will clean all the unnecessary files in the repository and give you a brand new build.

**Comment by MasonAsh** [comment]
Just tried that and still getting the same error. I can open the file in a text editor and it appears fine. When using the file in another project it appears to compile fine. 

I think for some reason this file is being interpreted as an object file, because I get the same error when passing the file directly to cl.exe directly, but this time with more detail: 

```
C:\Users\masonjash\Documents\dev\godot>cl editor/editor_icons.gen.h
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9024 : unrecognized source file type 'editor/editor_icons.gen.h', object file assumed
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:editor_icons.gen.exe
editor/editor_icons.gen.h
editor/editor_icons.gen.h : fatal error LNK1136: invalid or corrupt file
```

**Comment by MasonAsh** [comment]
Ok, I found the source of this issue.

In editor/icons/SCsub the on line 91:

`env.editor_sources.append("#editor/editor_icons.gen.h")`

is unnecessary and for whatever reason visual studio thinks .gen.h extension should be interpreted as an object file. Working on a PR as we speak.

**Comment by Corruptinator** [comment]
Nice! Hope that this gets resolved.
