### ISSUE TITLE
Reindhart tonemapping is broken

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#10533]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Win10 and Linux Mint

**Issue description:**
When Reindhart tonemapping is selected in the environment node, the result is a pure white screen. It doesn't matter what is in the scene or what settings are used. The 3 other tone mapping options work correctly.

**Steps to reproduce:**
- add environment node
- select tone mapping option Reindhart

**Link to minimal example project:**

**Comment by reduz** [comment]
Would appreciate GPU model and driver

**Comment by fracteed** [comment]
current drivers for gtx560ti(Linux Mint) and 960m(Windows). Note this must have broken fairly recently (past couple of weeks)

**Comment by tagcup** [comment]
Can reproduce this on 4770K Haswell on Arch Linux with current master. Repeatedly getting the following error in shell:

> ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 131 Severity: High  Message: GL_INVALID_OPERATION in glUniform(program not linked)
   At: drivers/gles3/rasterizer_gles3.cpp:122.

**Comment by eon-s** [comment]
Ubuntu, AMDGPU on R5 (Carrizo)

Fails in a shader, the first messages are:

```
ERROR: _display_error_with_code: TonemapShaderGLES3: Fragment Program Compilation Failed:
0:226(14): error: no matching function for call to `tonemap_reindhart(vec3, float)'; candidates are:
0:226(14): error:    vec3 tonemap_reindhart(vec3, vec3)
0:229(9): error: no matching function for call to `tonemap_reindhart(vec3, float)'; candidates are:
0:229(9): error:    vec3 tonemap_reindhart(vec3, vec3)

   At: drivers/gles3/shader_gles3.cpp:167.
ERROR: get_current_version: TonemapShaderGLES3: Fragment Program Compilation Failed:
0:226(14): error: no matching function for call to `tonemap_reindhart(vec3, float)'; candidates are:
0:226(14): error:    vec3 tonemap_reindhart(vec3, vec3)
0:229(9): error: no matching function for call to `tonemap_reindhart(vec3, float)'; candidates are:
0:229(9): error:    vec3 tonemap_reindhart(vec3, vec3)

   At: drivers/gles3/shader_gles3.cpp:470.
ERROR: get_current_version: Method/Function Failed, returning: __null
   At: drivers/gles3/shader_gles3.cpp:478.
ERROR: bind: Condition ' !version ' is true. returned: false
   At: drivers/gles3/shader_gles3.cpp:122.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:376.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:376.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:376.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:376.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 7	Severity: High	Message: GL_INVALID_OPERATION in glUniform(program not linked)
   At: drivers/gles3/rasterizer_gles3.cpp:122.
```

then repeats the last one.

**Comment by akien-mga** [comment]
Nice debug info @eon-s, that makes it easy to narrow down:
```
$ rg tonemap_reindhart
drivers/gles3/shaders/tonemap.glsl
173:vec3 tonemap_reindhart(vec3 color,vec3 white) {
236:    color.rgb = tonemap_reindhart(color.rgb,white);
239:    glow = tonemap_reindhart(glow,white);
```
All those were added in f5277e347d, and I guess the proper signature should be `vec3 tonemap_reindhart(vec3 color,float white)`.

**Comment by akien-mga** [comment]
Bug and fixed confirmed.
