### ISSUE TITLE
minizip fails building on Gentoo because they broke the upstream API for dubious reasons (error: expected initializer before 'OF')

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#10539]
Opening the issue for @Zatsuwar based on https://github.com/godotengine/godot/pull/10428#issuecomment-323783105

----

**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Gentoo, master branch

GCC - gcc (Gentoo 4.9.4 p1.0, pie-0.6.4) 4.9.4
Clan - clang version 3.9.1

Both clang and gcc give-me error.

**Issue description:**
I`m getting errors to compile in my Gentoo, this fallowing errors:

[Initial build] Compiling ==> main/main.cpp In file included from ./thirdparty/minizip/unzip.h:55:0, from ./core/io/file_access_zip.h:38, from main/main.cpp:68: ./thirdparty/minizip/ioapi.h:127:51: error: expected initializer before 'OF' typedef voidpf (ZCALLBACK open_file_func) OF((voidpf opaque, const char filename, int mode)); .....

Complete log: https://ghostbin.com/paste/2kh96

I also tried "minizip=no" but still don't work.

**Steps to reproduce:**
I am running:
```
scons platform=x11 
```
and
```
scons platform=x11 bits=64 tools=no target=release_debug -j 9 use_llvm=yes
```

**Comment by akien-mga** [comment]
For the reference, this issue is not reproducible on Mageia, Fedora, Arch or Ubuntu.

I found this thread about the same error affecting a Gentoo user when building a quazip project (which also has a `ioapi.h` likely derived from minizip): https://sourceforge.net/p/chessx/mailman/message/31984352/

Looking at the Gentoo ebuild for zlib/minizip, they seem to remove the upstream `OF()` macro: https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/zlib/zlib-1.2.11.ebuild#n87

And this for relatively discutable reasons: https://bugs.gentoo.org/show_bug.cgi?id=383179
This is a good read, and the summary is basically: the Gentoo zlib maintainer knows better, broke the upstream API and doesn't care.

So I'd be tempted to say "I don't care" either and leave things as broken on Gentoo. Then maybe Gentoo users can file bug reports against their distro's zlib and in a few years we might see a change in Gentoo - it's 2017 and zlib still uses `OF()`...

**Comment by akien-mga** [comment]
Alternatively, since I'm a nice guy and I care more about Godot users than autocratic Gentoo maintainers, I'll likely duplicate this `<zconf.h>` code in our copy of `ioapi.h`, together with a handful of swear words: https://github.com/godotengine/godot/blob/2ca0337/thirdparty/zlib/zconf.h#L288-L294

**Comment by Zireael07** [comment]
> together with a handful of swear words: 

Swear words which look well deserved from my perspective.

**Comment by akien-mga** [comment]
Well the alternative is to strip `OF()` everywhere as they recommend, and as we had before #10428, since this macro is meant to support pre-ANSI code and we don't care about it in 2017.

Still, I don't want to have to hack minizip each time I sync it with upstream, with the risk of breaking stuff while not really knowing what I'm doing. There are plenty of other legacy macros in this code that could be removed, the whole minizip could be reduced in code size by 2... but if upstream is not doing it, it's their call and I prefer to trust them than an angry Gentoo dev (that triggered quite a shitstorm on their [dev mailing list](https://lists.gt.net/gentoo/dev/239361)).

**Comment by groud** [comment]
Where do you get the minizip version from ?

**Comment by akien-mga** [comment]
Sadly the upstream zlib thread where this had been discussed is unreachable (all Zlib-devel mailing list archives seem to be missing), so I can't see what were upstream's reasons to reject the Gentoo change: http://mail.madler.net/pipermail/zlib-devel_madler.net/2011-September/002621.html

> Where do you get the minizip version from ?

libpng: https://sourceforge.net/projects/libpng/files/

Our current minizip version is synced from zlib 1.2.4, I plan to upgrade it to 1.2.11 soon after confirming that there are no regressions from the sync (this issue being the first - and so far only - one).

**Comment by akien-mga** [comment]
I found an actually useful upstream bug report from a GDAL contributor: https://github.com/madler/zlib/issues/117

Apparently the Zlib developers now agree about the removal, but don't particularly feel the need to hurry up. It's planned for removal in Zlib 2.0, though for now I don't see any development branch where it would appear to be worked on.

So I'll just use the workaround mentioned above to ease syncing with upstream 1.2.x, and when they publish 2.0, we can switch to it and get rid of our workaround.

**Comment by groud** [comment]
> So I'll just use the workaround mentioned above to ease syncing with upstream 1.2.x, and when they publish 2.0, we can switch to it and get rid of our workaround.

LGTM.
Don't forget to add the swear words !

**Comment by punto-** [comment]
I think our original minizip was taken from the Quake 1 source

**Comment by akien-mga** [comment]
Nice :D
