### ISSUE TITLE
Duplicate if-else branches found

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#10549]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot Master branch 294e912a843cde241f9abf619f5d40df9ef6ef9f

**Issue description:**
`cppcheck` found duplicate branches for the following if-else statements:
 
```
[drivers/gles2/rasterizer_gles2.cpp:10330] -> [drivers/gles2/rasterizer_gles2.cpp:10325]: (style, inconclusive) Found duplicate branches for 'if' and 'else'.
[drivers/gles3/rasterizer_scene_gles3.cpp:2992] -> [drivers/gles3/rasterizer_scene_gles3.cpp:2989]: (style, inconclusive) Found duplicate branches for 'if' and 'else'.
[editor/property_editor.cpp:2255] -> [editor/property_editor.cpp:2252]: (style, inconclusive) Found duplicate branches for 'if' and 'else'.
```

**Comment by akien-mga** [comment]
Are those fixed? (sorry, had missed this issue)

**Comment by Rubonnek** [comment]
Yeah, these seem to have been fixed at some point. There are some new ones, but I'll open a new issue for those.
