### ISSUE TITLE
Strongly requested to cancel.Import

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#10540]
The.Import 3.0 resource import is strongly requested to cause the editor to be very slow, and no global settings, and can not load external resources, greatly limiting the scalability of the engine

No global settings, resulting in many resources requiring manual settings

 Why do you want to import in advance? Some resources are only for reference, or why do you need to import the tests automatically? What the engine needs most is the excellent packaging tools to update the game version

**Comment by Zylann** [comment]
Your issue is a a bit hard to understand as a whole, it seems you request several things at once. Consider opening a separate issue for each.

**Comment by reduz** [comment]
As explained in the other issue, the main problem is that importing images is very slow. This will be fixed by doing background import eventually
