### ISSUE TITLE
OS X & iOS: fixed_materials demo issue with mesh texture and color

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#1054]
The diffuse texture in the mesh material doesn’t show up on the spheres in both the editor and the desktop player, but it’s showing ok on the device

The diffuse color in the mesh material is showing on the editor but not on the desktop player nor the device

The desktop runs OS X Yosemite (version 10.10.1) and the device runs iOS 7 (version 7.1.2)

![screen-shot-2014-12-26-at-6 18 24-am](https://cloud.githubusercontent.com/assets/1840524/5557483/bfdcd3e6-8cd1-11e4-9d91-8f7be620e7f1.jpg)

**Comment by akien-mga** [comment]
OP proposed a PR and deleted their Godot fork shortly after so...
