### ISSUE TITLE
EditorHelp::_scroll_changed does not make sense

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#10553]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot Master branch

**Issue description:**
I saw this `cppcheck` message:

```
[editor/editor_help.cpp:639]: (style) Assignment of function parameter has no effect outside the function.
```

And the body of `EditorHelp::_scroll_changed` does not make sense to me at all.

https://github.com/godotengine/godot/blob/294e912a843cde241f9abf619f5d40df9ef6ef9f/editor/editor_help.cpp#L633-L642

From what I can tell, it might as well be empty and does the same thing. Am I missing something?

**Comment by reduz** [comment]
I think the funtion is unused and a leftover, and scroll is actually read when the page changes.. shoukd probably be erased

**Comment by Rubonnek** [comment]
Thanks for the feedback.

Yeah, I thought that too. I also noticed some other unused code I think should be removed and I thought it was better to leave all this unused code alone until 3.0 is released which is why I previously closed this issue, but it seems like this change is actually encouraged.

I'll work on this then.
