### ISSUE TITLE
Fragment shader that uses TIME runs at 1 fps in the editor

### ISSUE THREAD

**Issue by Smellyhobo101** [godotengine/godot#10554]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7, Godot 3 alpha 1, GTX 770, Driver version 378.49

**Issue description:**
This fragment shader creates vertical bands that scroll to the left:

```
shader_type canvas_item;
void fragment() {
	COLOR.rgb = vec3(sin(UV.x*10.0 + TIME));
}
```
When in game it runs at full speed and scrolls smoothly, but in the editor it looks like it only updates once per second.

**Steps to reproduce:**
Create a Sprite2D with any texture, and give it a ShaderMaterial with the shader code above.

**Link to minimal example project:**
[time_shader_bug.zip](https://github.com/godotengine/godot/files/1242776/time_shader_bug.zip)

**Comment by eon-s** [comment]
Try changing "update changes" to "update always" on the spinning thing on the top right of the editor.

**Comment by Smellyhobo101** [comment]
That fixed it. Thanks.

**Comment by reduz** [comment]
Hm. Editor should detect this and redraw automatically.. please mark as a
bug and 3.0 as milestone (am away and on the phone).
