### ISSUE TITLE
Some UX notes about creating project folder

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10567]
Godot 3.0 master
Windows 10 64 bits

I went through a bit of confusion while trying to create a project:

1) Open project manager
2) Create new project
3) Click "Browse" to pick a folder
4) On Windows, it opens by default in C:/Users/name, I want it to be in D:/something/uuhSomething/IDontRemember, so I try to click "/..", but it doesn't do anything, unlike any file explorer on Windows.
5) I decide to edit the path just to show the files in D:/ then:

![image](https://user-images.githubusercontent.com/1311555/29586530-3f8e1576-878b-11e7-9750-42b07a995b21.png)

At this point, the file list doesn't update, so I intuitively think that pressing "Enter" in the field would update the list...
Wrong! The dialog closes and the project ends up being created in D:/ while i didn't finish to find my folder.

Then I noticed that small drop down, which does what I wanted:
![image](https://user-images.githubusercontent.com/1311555/29586604-98f4063e-878b-11e7-991b-e7a9aa1707c8.png)

When I think about it, I understand the top URL textbox is the prompted directory and pressing enter will choose it, but for some reason I thought of it like a URL only used to show the file list below, like any other file explorer and browsers, and I thought the actual input field was the one at the bottom.

![image](https://user-images.githubusercontent.com/1311555/29586884-80a14c8a-878c-11e7-804e-d5170369b2f5.png)

That one is completely useless when looking for a folder.

Wouldn't it be more consistent if the top path was only "where you are" with no "Enter closes dialog", and the bottom path was the actual folder you want to choose/create?

**Comment by akien-mga** [comment]
Is this still relevant in the current master branch?

**Comment by akien-mga** [comment]
Seems partly fixed, `.` and `..` are now hidden and there's a `↑` arrow button to go to parent folder.

The drive selector could probably go to the left of the path instead of the right, to be clearer.

The "File:" LineEdit is still there and not used.

**Comment by volzhs** [comment]
i don't have a issue on ubuntu.
is it for windows only?

**Comment by Zylann** [comment]
@volzhs this issue has some Windows-specific details, but others are about the GUI itself.

**Comment by KoBeWi** [comment]
The steps provided at the beginning now behave correctly. When you write a different drive letter and press Enter, it correctly goes there.

So only this is left:
> The drive selector could probably go to the left of the path instead of the right, to be clearer.
The "File:" LineEdit is still there and not used.

(like Akien said actually)
