### ISSUE TITLE
add a "mute" button to temporarily disable a track into the AnimationPlayer editor

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1056]
Hi!

It would be cool if it was possible to mute (temporarily disable) tracks into the AnimationPlayer editor.

**Comment by UsernameIsAReservedWord** [comment]
A workaround for this is to rename the track by adding an "_off" or "_mute" at the end.

**Comment by akien-mga** [comment]
Sounds like an interesting feature indeed. I'd go for the mute button, having to change the track name with a fixed suffix is too much of a hack, and would be bad UX.

**Comment by vnen** [comment]
This was solved by #13371.
