### ISSUE TITLE
For loop does not work in 3.0 shaders

### ISSUE THREAD

**Issue by Smellyhobo101** [godotengine/godot#10560]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7, Godot 3 alpha 1, GTX 770, Driver version 378.49

**Issue description:**
Attempting to use a for loop in a shader:
```
shader_type canvas_item;

void fragment() {
	for (i = 0; i < 10; i++) {
		
	}
}
```

Gives the error: `error(4): Expected expression, found: CF_FOR`

Unsure if I'm doing something wrong, if this is a bug, or for loops just aren't implemented yet?

**Comment by eon-s** [comment]
Others, like while, seem to work (and is really easy to do infinite loops while writing conditions).

**Comment by reduz** [comment]
infinite loops are fine, opengl allows it.
but i think for is missing, will add it as soon as i'm done documenting the
language

**Comment by eon-s** [comment]
@reduz an accidental while(true) kills the system :upside_down_face:

**Comment by reduz** [comment]
@eon-s Unfortunately detecting this is way too difficult, so you will have to be careful :)

**Comment by eon-s** [comment]
Can't it use an optional manual compilation? (this may be for another issue, I guess).

**Comment by reduz** [comment]
@eon-s what is an optional manual compilation?

**Comment by eon-s** [comment]
@reduz something to toggle off the instant shader compilation while writing it, or at least compile but let apply it manually to avoid system locks while constructing one.

**Comment by reduz** [comment]
@eon-s I'm not really sure if it's worth it, and i don't like the idea of having to spend time working around problems that won't happen in real use cases. I can easily detect whle(true) without a break, but if you make a while that depends on a uniform (very common case) and that in some cases it can go infinite, there's nothing that can be done. It's better to just wait and see if anyone has real problems with this.

**Comment by bojidar-bg** [comment]
@reduz Can't we generate something like this __in debug mode__? (psuedocode)
```
int counter = 0
while(<condition>) {
  if (counter > 100) break
  // or 1000, or 1e5, or any other value that won't be reached without lag anyway
  counter++
  <code>
}
```
This way, no shader would accidentally break the editor.

**Comment by reduz** [comment]
@bojidar-bg I thought exactly about that, but it's going to make the shader slower pointlessly
