### ISSUE TITLE
Enum values can't be used as match patterns

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#10571]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10. Godot 3.0alpha1

**Issue description:**

Enum values can't be used as match patterns. The error is: `Parse Error: Only constant expressions or variables allowed in a pattern`

The [`match` documentation](http://docs.godotengine.org/en/latest/learning/scripting/gdscript/gdscript_basics.html#match) says that it should be possible under the variable pattern: `matches the contents of a variable/enum`

**Steps to reproduce:**
```gdscript
extends Node

enum Action { Up, Down }
var current_action = Action.Up

func something():
	match current_action:
		Action.Up: # Error here
			pass
		_:
			pass
```

**Comment by akien-mga** [comment]
There's actually a PR already to fix that :) #10542
