### ISSUE TITLE
3.0 Shader Language: Implement constants

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10577]
i see no 'const' word anywhere, so the best way to implement const is 'uniform' but it is too heavy for such small things. i think it is important to be able to declare constants, because shader compilers can optimize shaders very well using this knowledge.

may be godot detects constants itself and outputs them as const into glsl (variables that are declared but never changed)? if so, please confirm.

**Comment by RandomShaper** [comment]
I agree. I missed them in 2.x but I was expecting to have them in 3.0.

**Comment by Chaosus** [comment]
Damn, constants are very useful in shaders, I miss them !

**Comment by DynasoulStudio** [comment]
Constants would be great! Very useful for those of us learning shaders for the first time and learning GLSL.
