### ISSUE TITLE
3.0 Shader Language: Implement function inlining

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10578]
ability to declare inline functions can drastically speed up some shaders

**Comment by akien-mga** [comment]
What's your take on this @reduz? Wanted for 3.1?

**Comment by reduz** [comment]
GLSL does not support inlining

**Comment by akien-mga** [comment]
Right, then we can't do it either.

**Comment by reduz** [comment]
we could do it in our shader compiler, but i dont think it would be much gain.
I like the idea from @hpvb of using GLSLOptimizer, not sure if it will really improve performance any more, but worth giving it a try.
