### ISSUE TITLE
Background (threaded) import of resources to allow using the editor while during import

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#10583]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
All systems, current master branch.

**Issue description:**
Importing and re-import assets for the new 3.0 workflow can take quite some time, and the project can't be edited while the import process is running.

Moving the import logic to a thread could alleviate this inconvenience. This should likely be implemented for 3.0 Beta, so that users can test thew new features with a better workflow.

**Comment by Zylann** [comment]
Could we have a progress bar / spinner with text somewhere in a corner so that we know the editor does some background work?

**Comment by Dillybob92** [comment]
+1 this.. the only thing that irritates me to no end in 3.0 is editing a .png and saving it then alt-tabbing to Godot and having to wait for that 100-500ms

It's fast now because i'm editing tiny little 5kb images, however when I edit an atlas or whatnot I'm sure it'll be even more annoying. I liked how it was before i have no idea why i have .import files all over my damn directories as well lol

![](https://i.gyazo.com/53bd6c3ca7b7fadf16d80625d7bb5706.png)

Thought they'd all stay in .import and i don't have to deal with them but now there just all over >_<

**Comment by Zylann** [comment]
@Dillybob92 ever worked with Unity? ^^

**Comment by Dillybob92** [comment]
@Zylann I see, yeah I guess it's similar to the old `.flags` file we had in 2.xx. I just found out that when deleting images in the Godot FileSystem tab, it also deletes the corresponding import files/etc, which is nice.

I originally thought we had to manually delete all corresponding .import files. Looks like the new 3.0 is now moving us towards to managing files inside the FileSystem tab for max efficiency.

**Comment by toger5** [comment]
Could we maie those files hidden ? `.filename.jpeg.import`? Or would that ibroduce other issues?

**Comment by Zylann** [comment]
@toger5 might help browsing files, but again, you still need to remember they are here and required.
In Unity I think they have an option to put meta files in the import folder, but it makes versionning a bit harder.

**Comment by reduz** [comment]
Background import in itself is not worth it, as ensuring thread safety of
the import process is to much work. What we need to do is for textures

**Comment by Zylann** [comment]
I'm curious to know why this import is so slow. I understand there is a compression optimization thingy at work, but the speed of it is currenly ridiculous, is it really supposed to be that slow? Isn't there something wrong going on?

**Comment by Zireael07** [comment]
Etc2 is making it slow AFAIK

**Comment by Zylann** [comment]
Well, yeah, my question is why^^

**Comment by akien-mga** [comment]
Kicking to 3.1, the import system has already been made more forgiving and a bit faster; multithreading can be done later on.

**Comment by Calinou** [comment]
**Bugsquad note:** This issue is still relevant as of commit https://github.com/godotengine/godot/commit/d87307d850186d27d2c27c5916ec8c4744c14979.

**Comment by Calinou** [comment]
To make reimporting feel faster (if you can spare the increased CPU usage), we could have an option to reimport files continuously, even if the editor isn't focused. This would require listening for changes on the filesystem to avoid polling.

**Comment by Calinou** [comment]
Resource importing is now multi-threaded (and ETC2 importing was sped up), closing. See https://github.com/godotengine/godot/issues/10583#issuecomment-328358729 as for why background importing is not viable for Godot's use cases.
