### ISSUE TITLE
Regression - RayCast2D arrow not drawn correctly

### ISSUE THREAD

**Issue by thebricco** [godotengine/godot#10588]
**Operating system or device, Godot version**
Win 10, Godot 2.1.4-beta

**Issue description:**
RayCast2D line is drawn correctly, while the arrowhead looks rotated 90°. An example in the following image:

![senza nome](https://user-images.githubusercontent.com/30623265/29625494-2d236796-882c-11e7-8cf8-ad6532925e5c.png)

**Comment by eon-s** [comment]
I can't reproduce on latest beta (20170817).

**Comment by akien-mga** [comment]
Yes, that's supposed to be fixed. Please try the most recent build: http://download.tuxfamily.org/godotengine/2.1.4/beta/20170817/
