### ISSUE TITLE
Dev Blog Navigation is Broken

### ISSUE THREAD

**Issue by Alan-FGR** [godotengine/godot#10584]
Sorry to be reporting this here guys, but I couldn't find a repo for the website and don't have the time to find out the most appropriate place to report this:
Navigation in https://godotengine.org/devblog is broken... the links at the bottom they all point to https://godotengine.org/devblog while I believe it should be https://godotengine.org/devblog?page=2 for example.

**Comment by akien-mga** [comment]
Ping @alketii.

**Comment by mhilbrunner** [comment]
Fixed. Not sure when it was fixed, but probably with the new website.
