### ISSUE TITLE
RigidBody(2D) needs a function to apply torque and force to a specific point.

### ISSUE THREAD

**Issue by Evi1M4chine** [godotengine/godot#1058]
There should be a function that takes:
- a point relative to the RigidBody’s local transform and
- a force vector,
  and applies the force at that point, as if a rocket was attached there, pushing it.

This should result in not just movement, but correct rotation for force at that point relative to the center of the gravity.

It should be possible to easily add and remove forces that way, so one can toggle them with the input controls.

I think this could become the most-used function, as it frees people inexperienced with vector math from doing it manually. :)
(It’s also essential for turning on and off separate rockets on the back of my car :)

**Comment by akien-mga** [comment]
What's the status on this topic? @Evi1M4chine did you get to implementing something for a potential pull request?

**Comment by bojidar-bg** [comment]
Pretty bump (hopefully prettier than @akien-mga's above :wink:), what is the status on this issue?

**Comment by akien-mga** [comment]
This is fixed in 3D by #16060.

Still missing from RigidBody2D AFAICT.

**Comment by aaronfranke** [comment]
See also https://github.com/godotengine/godot/issues/16863#issuecomment-416791048

**Comment by Anutrix** [comment]
Isn't https://github.com/godotengine/godot/pull/20404 related?

**Comment by Anutrix** [comment]
Any updates?

**Comment by aaronfranke** [comment]
I suggest 4.0 milestone due to my comment above, might be best to look at all of these methods at once.

**Comment by madmiraal** [comment]
Fixed with #20404.
