### ISSUE TITLE
Error on build Server Platform

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#10594]
**Godot version, platform:**
2.1/HEAD, Linux

![screenshot_20170823_215901](https://user-images.githubusercontent.com/4741886/29637800-8f53d170-8855-11e7-91c6-376b9a8255a4.png)

`scons p=server bits=64 tools=no`

My current solution

**servers/visual/rasterizer_dummy.h**
```
virtual void set_time_scale(float p_scale);
```

**servers/visual/rasterizer_dummy.cpp**
```
void RasterizerDummy::set_time_scale(float p_scale) {
    
}
```

Is it supposed to do something?

**Comment by akien-mga** [comment]
It would be good to mention your Godot version..

**Comment by akien-mga** [comment]
That's a bug introduced by #7912, assigning to @RandomShaper.

**Comment by RandomShaper** [comment]
I'll check it ASAP.

**Comment by RandomShaper** [comment]
@AlexHolly, your solution is actually _the_ solution.

I forgot to override that function in the dummy rasterizer.

If you'd like to, you can submit a PR with just those changes. If you'd rather not, I can do it for you.

**Comment by RandomShaper** [comment]
Closing via #10606.

**Comment by RandomShaper** [comment]
Closing via #10606.
