### ISSUE TITLE
Can't run demos with --path with relative paths

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#10599]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot master branch 21d53f29f392f4a33095de75c478da345a362555

**Issue description:**
Opening a project with the `--path` flag does not work anymore

**Steps to reproduce:**

**Link to minimal example project:**
Try any of the [demo projects](https://github.com/godotengine/godot-demo-projects).

**Comment by akien-mga** [comment]
Works fine for me on Mageia 6 x86_64:
- `godot-git -e --path Projects/godot/godot-demo-projects/2d/platformer/` loads the demo in the editor
- `godot-git --path Projects/godot/godot-demo-projects/2d/platformer/` runs it

Note that to be able to run a project, you need to have edited it once to get its assets imported.

**Comment by Rubonnek** [comment]
For some reason it's still broken in Arch Linux and it's not a segmentation fault.

**Comment by akien-mga** [comment]
Again:
> Please give the exact command you are using.

**Comment by Rubonnek** [comment]
It requires the full path.

Inside the 2d folder of the demos:
```shell
# This doesn't work
godot -e --path ./hdr

#This works:
godot -e --path $(pwd)/hdr
```

**Comment by Rubonnek** [comment]
@akien-mga Previously I used the same commands you posted.

**Comment by Rubonnek** [comment]
I was using a wrong fork build. Relative paths are, indeed, working.
