### ISSUE TITLE
Support for mobile IAPs and Ads.

### ISSUE THREAD

**Issue by philiplb** [godotengine/godot#1059]
I'm currently playing around with Godot for a small mobile game. But the support for IAPs could be crucial.
My platform is Android at the moment.

**Comment by silverkorn** [comment]
@philiplb For ads on Android, see this repository: https://github.com/punto-/godot_modules
Otherwise, I guess searching for an ad provider having a HTTP(S) REST API would be a good choice (as stated in documentation: https://github.com/okamstudio/godot/wiki/tutorial_android_module)

**Comment by philiplb** [comment]
This looks usefull, thanks. :)
More important for me would be to support Android IAPs though.

**Comment by akien-mga** [comment]
I believe there is no intent to add direct support for this in the engine, but there are already many third-party Godot modules for that.
