### ISSUE TITLE
Auto completion improvement: type-checked scope.

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#10603]
**Issue description:**
It would be great if the auto completion adapt to type checked scope:
```gdscript
if event is InputEventMouseButton:
    #in this indentation we know that type of event is not InputEvent but InputEvenMouseButton
    event.   #should now give auto completion for InpotEventMouseButton like button_index.

```
This also would be cool in many other cases when there is an undefined variable and you want to get auto complete. And u as a user know what it probably will be most of the time.

It also would be nice to have swift like syntax augar:
`(my_node is Button)?.set_visisble(false)`
For
```
if my_node is Button:
    my_node.set_visible(false)
```

**Comment by Hinsbart** [comment]
I agree, this kind of completion would be great for InputEvents.
For a start (or if this is too difficult) we could also just show the properties of all the InputEvent types in the completion, like it was in 2.1

**Comment by HummusSamurai** [comment]
> the auto completion adapt to type checked scope

This would be amazing! And very useful for InputEvents _(and AudioBusEffects!)_ at least.

I agree with @Hinsbart that we could at least show properties of all types, since having to google the documentation (which does not yet exist for 3.0!) is much harder than simply reading an error that says `InputJoystickButton does not have property pos`

I don't know about the other syntactic sugar though, I haven't come across it before.

**Comment by Zylann** [comment]
What if:
```gdscript
if obj is Class:
    print(obj.attrib)
    obj = other_var
    # and now?
```

**Comment by reduz** [comment]
hmm that would work pretty nice for _input_event yeah.. I can imagine it could be easy to do too..

**Comment by reduz** [comment]
also it can work great in a lot of cases, you are brilliant Mr. Zylann

**Comment by HummusSamurai** [comment]
@Zylann I feel silly but I don't get it. What does the snippet show?

**Comment by Hinsbart** [comment]
@HummusSamurai I think it's meant to ask the question of how the completion should behave in case you reassign the variable after type-checking it, since then it's type might have changed.

**Comment by reduz** [comment]
@Zylann that's not a problem, completion goes backwards and checks lines of code for reassignments
