### ISSUE TITLE
Scaling colliders in 3d not working properly

### ISSUE THREAD

**Issue by das-shadow** [godotengine/godot#1060]
Scaling colliders in 3d is not reporting any collision:
![](https://cloud.githubusercontent.com/assets/10323520/5561451/3ef31412-8d8e-11e4-8152-b7e488650ef0.png)

**Comment by akien-mga** [comment]
Could you be more specific? What is the expected result, and what do you get instead? Could you provide a test project that showcases the bug?

Also, is it still valid in the current master branch?

**Comment by akien-mga** [comment]
Closing as there has not been any activity since Dec 2014. It's probably the same issue as in 2D that Colliders behave in a strange way when scaled.
