### ISSUE TITLE
Compiling for Windows: scons error

### ISSUE THREAD

**Issue by hamad-almamari** [godotengine/godot#10607]
Operating system:
**Windows 10**

Device:
**Dell Inspiron 11 3000 Series** 

Issue description:
I was trying to Compiling godot for Windows.
I follow the instruction on the docs, but i can't make scons work i keep getting errors when I try test scons by useing scons --version.

`Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights

PS C:\Users\dell> python --version
Python 3.6.2
PS C:\Users\dell> scons --version
Fatal Python error: Py_Initialize: unable to load th
ModuleNotFoundError: No module named 'encodings'
Current thread 0x000019a0 (most recent call first):`

I Know this is not godot issue.
but is there any solution for this or other build tool can i use to Compiling godot for Windows.

Also i cant find the batch file which called “scons.bat” any where in scons path.
[http://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#setting-up-scons](url)

any help??

**Comment by akien-mga** [comment]
>PS C:\Users\dell> python --version
Python 3.6.2

You need Python 2.7, Scons is not compatible with Python 3. See http://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#requirements

**Comment by hamad-almamari** [comment]
Thank u now it work

`PS C:\Users\dell> python --version
Python 2.7.13
PS C:\Users\dell> scons --version
SCons by Steven Knight et al.:
        script: v2.5.1.rel_2.5.1:3735:9dc6cee5c168[MODIFIED], 2016/11/03 14:02:02, by bdbaddog on mongodog
        engine: v2.5.1.rel_2.5.1:3735:9dc6cee5c168[MODIFIED], 2016/11/03 14:02:02, by bdbaddog on mongodog
        engine path: ['C:\\Python27\\Scripts\\..\\Lib\\site-packages\\scons-2.5.1\\SCons']
Copyright (c) 2001 - 2016 The SCons Foundation
PS C:\Users\dell>`
