### ISSUE TITLE
New SVG UI glitches sometimes

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10602]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows 64, nvidia, 50a0e3f (it started to appear from the very first version with svg tho)

**Issue description:**
![screen](https://www.dropbox.com/s/1mdzbsjyuwob5zs/svg_glitches.png?raw=1)
I have border=2 setting in editor settings. Look at the border of Edit, Run, Import buttons (left and bottom sides). It is thinner then others. And this is constantly changing. I mean if i move mouse over some other UI elements, this glitch will move somewhere else (totally randomly in the whole window)

**Comment by akien-mga** [comment]
That's likely a duplicate of #10461.

**Comment by curly-brace** [comment]
not sure. for me it starting appearing right on 22 August (99% sure). and it looks different to the other issue

**Comment by toger5** [comment]
#10523 try this branch and see if it worka.
The svg's probably have nothing to do with that.
In general there is vo svg used in the editor. Svg aupport imports svg files to textures.
Than those textures are displayed.
So this has to be casued by the styleboxes. And for them the borders worked.
So the polygon aa could be the case.
As i said just compile the brqnch of my pr and test again. Or wait ubtil it ia merged and than update this issue if it changed.

**Comment by curly-brace** [comment]
@toger5 it failed to compile
```
[Initial build] Linking Static Library ==> editor\editor.windows.tools.32.lib
editor\editor_icons.gen.h : fatal error LNK1136: invalid or corrupt file
scons: *** [editor\editor.windows.tools.32.lib] Error 1136
scons: building terminated because of errors.
```
i will wait for the merge. thank you.

**Comment by toger5** [comment]
@curly-brace have you removed editor_icons.gen.cpp ?

**Comment by toger5** [comment]
@curly-brace I just recoiled on windows and checks how it looks. item now really sure that #10523 would fix it.

**Comment by curly-brace** [comment]
@toger5 i'm not very good at c++, so i don't know why this happened. but i've just took source from your repo and put it in clean folder and launched compilation.. whatever, hope merge will succeed 👍

**Comment by toger5** [comment]
hm... okay than my tip is useless... lets see if it gets fixed with a merge.

**Comment by djrm** [comment]
it is a duplicate of #10461, also there is no such thing as an SVG UI (yet)

**Comment by toger5** [comment]
@akien-mga @curly-brace this can be closed.

**Comment by curly-brace** [comment]
just compiled efcafab6255ea78365e519ca3a13e9bf8b2a81d4 and this glitch is gone. awesome!
