### ISSUE TITLE
can't run project with command line on Mac (EXC_BAD_ACCESS in EditorFileSystem::_save_filesystem_cache)

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#10605]
I can't run a godot project directly current master on Mac.
90c7ee38

stack:
```
godot.osx.tools.64!EditorFileSystem::_save_filesystem_cache(EditorFileSystemDirectory*, FileAccess*) (/Users/timo/Documents/Godot/_GodotDev/godot/editor/editor_file_system.cpp:1035)
godot.osx.tools.64!EditorFileSystem::_scan_filesystem() (/Users/timo/Documents/Godot/_GodotDev/godot/editor/editor_file_system.cpp:277)
godot.osx.tools.64!EditorFileSystem::_thread_func(void*) (/Users/timo/Documents/Godot/_GodotDev/godot/editor/editor_file_system.cpp:296)
godot.osx.tools.64!ThreadPosix::thread_callback(void*) (/Users/timo/Documents/Godot/_GodotDev/godot/drivers/unix/thread_posix.cpp:58)
libsystem_pthread.dylib!_pthread_body (/Unknown Source:0)
libsystem_pthread.dylib!_pthread_start (/Unknown Source:0)
libsystem_pthread.dylib!thread_start (/Unknown Source:0)
```

It works to start the project manager and I also can open projects.
I just cannot start it via command line:

`${workspaceRoot}/bin/godot.osx.tools.64 --editor --path /Users/timo/Documents/Godot/DalyMini1_ballJumpAndRun`

**Comment by akien-mga** [comment]
There's a stacktrace but no error?

**Comment by toger5** [comment]
@akien-mga 
the debugger tells me:
EXC_BAD_ACCESS (code=1, address=0x0)
in:   editor_file_system.cpp:1035

**Comment by toger5** [comment]
```c++
void EditorFileSystem::_save_filesystem_cache(EditorFileSystemDirectory *p_dir, FileAccess *p_file) {

	if (!p_dir)
		return; //none
	p_file->store_line("::" + p_dir->get_path() + "::" + String::num(p_dir->modified_time));
```
p_file x0000000000 I think... (currently am recompiling to test another branch for that error so I'm not sure)

**Comment by toger5** [comment]
I still was not able to get godot started form the command line... (with a project)

**Comment by toger5** [comment]
The issue somehow changed:
It crashes at a different point now:
the problem is, that it executes:
https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L5034
although `accept` is not defined yet.

 ... 

oh

during searching for the links to I saw this was already fixed.
so I need to check on current master

**Comment by toger5** [comment]
I tested again and it seems to be fixed.
Although it is a mystery for me why I was always able to start the editor over the project manager...

Seems like 89fbc54
fixed the issue I had today. and probably another commit fixed the issue I had some time ago.
If someone has an which would explain why I was not able to start form command line. But from Project Manager I would be interested!
