### ISSUE TITLE
Clicking connection or group icon only half-selects node

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#10617]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64-bit, Godot 3.0 Alpha1, NVIDIA GTX 1060

**Issue description:** **Steps to reproduce:**
Clicking on a node's connection or group icon in the Scene panel highlights the node as selected, and is visibly selected in the editor, but the Inspector and Node panels still show properties and options for the previously selected node.

**Comment by Hinsbart** [comment]
This was fixed in a80371ce0.
