### ISSUE TITLE
Tileset pallet

### ISSUE THREAD

**Issue by TheCosmicGoat** [godotengine/godot#1061]
The pallet tilebar for the currently selected tileset remains visible when switching to 'help' mode in the interface. This makes the help screen un-useable.

To reproduce:
a) Set up a 2d tilemap in a scene with a suitable tileset.
b) With the tilemap selected, click on the help tab.

**Comment by reduz** [comment]
merged it, is it fixed?

**Comment by akien-mga** [comment]
Assuming it has been fixed by #1074.
