### ISSUE TITLE
Dynamic Font doesn't appear at default size 16

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#10616]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64-bit, Godot Alpha1 3.0, NVIDIA GTX 1060

**Issue description:**
At least for Roboto.ttf (in attached project), a label with Custom Dynamic Font does not appear if 16 is the value in the Dynamic Font field. Each other size worked as expected. Editor crashed twice just switching between the different font sizes, which may or may not be related.

**Steps to reproduce:**
Create a label, check the Custom Font checkbox, set it to Dynamic Font, set Roboto.ttf to be the Dynamic Font Data for it. Set size property in Dynamic Font to be 16.

**Link to minimal example
[godot3Alpha1_fontsize_bug.zip](https://github.com/godotengine/godot/files/1249792/godot3Alpha1_fontsize_bug.zip)
 project:**

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by Oranjoose** [comment]
It seems to be working normally in RC1. Thank you.

**Comment by vnen** [comment]
Closing this as solved then.
