### ISSUE TITLE
Omni and Spotlight shadow contact problem

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#10629]
Win10, nvidia 960m,

shadow is projecting at long distance i mean away from where it supposed to be and when i try to correct in with bias and contact is become weird, with omni and spotlight.

**Comment by raymoo** [comment]
That first image looks fine to me, the head should have a large shadow because the light is very close to it.

**Comment by gamergamesz** [comment]
did i forgot to edit it it's look like well there is only one problem rests are my fault

**Comment by gamergamesz** [comment]
there seems to be problem with my system i hope you can underatand the issue or i will update it with pic tomorrow, So so so sorry for the trouble i cause it was all my fault
