### ISSUE TITLE
Triplanar mapping does not work if s3tc compression is disabled

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#10626]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Win10 (960m and gtx560ti)

**Issue description:**
If s3tc texture compression is disabled in the project settings>rendering>vram compression>Import s3tc, triplanar mapping in a spatial material no longer works.

Not sure if this is a requirement for triplanar mapping for some reason, but it seems like a bug? Note that standard UV mapping works fine without  the s3tc option. Also triplanar works fine without Etc2.

The first image shows the result of turning off s3tc compression and trying to use triplanar mapping:
![triplanar_bug1](https://user-images.githubusercontent.com/7741669/29698581-d8f9d4c4-8999-11e7-9421-474b289fe528.jpg)

If the 3tc option is turned on in the project settings (and the import folder updates with a 3tc texture) the triplanar now works:
![triplanar_bug2](https://user-images.githubusercontent.com/7741669/29698629-5343d28e-899a-11e7-809b-2d3d357056e9.jpg)

**Steps to reproduce:**

- start a new project
- disable the s3tc and Etc2 compression settings
- create a cube mesh
- create a new spatial material, import an image into the albedo and switch the uv1 to use triplanar mapping

**Link to minimal example project:**

[triplanar_bug.zip](https://github.com/godotengine/godot/files/1250766/triplanar_bug.zip)

**Comment by reduz** [comment]
This is not a bug, you disabled all vram compressed formats from project settings. I added a warning so next time you know this must be corrected.

**Comment by fracteed** [comment]
@reduz I wasn't sure if this was a bug or not, as non-tiling textures work fine with the s3tc disabled. So for desktop only, only Etc2 can be disabled...is this correct?

**Comment by reduz** [comment]
No, the bug is that the texture simply wasn't reimported
