### ISSUE TITLE
Linux export exported as DOS/Windows executable

### ISSUE THREAD

**Issue by DASchechtman** [godotengine/godot#10623]
[export_test.zip](https://github.com/godotengine/godot/files/1250378/export_test.zip)
Windows 10, Godot v2.1.3 stable.offical

I installed the export templetes for my version of godot from the godot download page. Exported an empty project to linux, tried to open in Ubuntu 64bit VM and duel boot. file wasn't opened. looked at it's properties, says its a DOS/Windows executable

**Steps to reproduce:**
Tried to export in the standard way

**Link to minimal example project:**

**Comment by akien-mga** [comment]
That's super weird... Can you check the type of your installed templates in `%AppData%\Godot\templates\`?

**Comment by akien-mga** [comment]
Also, if you still have your export templates .tpz file, can you get its md5sum?

**Comment by akien-mga** [comment]
Checked the binaries in the templates .tpz, they seem fine. It looks like you got the Windows 64-bit debug binary when you exported for Linux somehow:
```
$ file export_test
export_test: PE32+ executable (console) x86-64, for MS Windows
$ file templates/*
templates/android_debug.apk:      Java archive data (JAR)
templates/android_release.apk:    Java archive data (JAR)
templates/GodotiOSXCode.zip:      Zip archive data, at least v1.0 to extract
templates/javascript_debug.zip:   Zip archive data, at least v2.0 to extract
templates/javascript_release.zip: Zip archive data, at least v2.0 to extract
templates/linux_x11_32_debug:     ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=70dc6573e349488ae2905469d6b86b74a8178815, not stripped
templates/linux_x11_32_release:   ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=4744ae644898720e1cbccc9f8623116bd32bdb31, not stripped
templates/linux_x11_64_debug:     ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=93fd41596c512cba3a0bd0c28ccf2323368e0cad, not stripped
templates/linux_x11_64_release:   ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=001e4cdfbc319bbb30a20cfce9a746df45a54627, not stripped
templates/osx.zip:                Zip archive data, at least v1.0 to extract
templates/windows_32_debug.exe:   PE32 executable (console) Intel 80386, for MS Windows
templates/windows_32_release.exe: PE32 executable (GUI) Intel 80386, for MS Windows
templates/windows_64_debug.exe:   PE32+ executable (console) x86-64, for MS Windows
templates/windows_64_release.exe: PE32+ executable (GUI) x86-64, for MS Windows
```

Can you reproduce the bug?

**Comment by DASchechtman** [comment]
sure @akien-mga I can reproduce the bug, and get the hash sum too. Sorry about the delay, life happened an I forgot about it

**Comment by DASchechtman** [comment]
@akien-mga  here's the reproduction of the bug 
[Bug.zip](https://github.com/godotengine/godot/files/1257838/Bug.zip)

and here is the hash sum (sha256)
BCDFC720EA27F0705B42189E4924612A7C5D8ECDFB8D2294C5C1EFCB9C1BEF4E

and here is the hash sum (MD5)
95C0A3C0081A14473F87FEA0CBB30A5A

**Comment by akien-mga** [comment]
Renaming the `Bug` binary to `Bug.exe` allows to run it with WINE, so it's indeed the 64-bit Windows debug binary.

Could you describe the exact steps that you are using to export the Linux binary?
Also, to be sure, do you confirm that you did *not* define a custom binary in this screen pointing to the Windows template? 
![spectacle m18021](https://user-images.githubusercontent.com/4701338/29788916-96b7f6d4-8c34-11e7-8cdd-9399b785d8d8.png)

**Comment by DASchechtman** [comment]
Ok I see what I did.
First I opened a project
![screenshot 13](https://user-images.githubusercontent.com/16565772/29790042-d937d376-8bfd-11e7-9b4c-70e1359e2c58.png)

Then I would open the export tab
![screenshot 14](https://user-images.githubusercontent.com/16565772/29790049-e3232b42-8bfd-11e7-91d1-a2c140d1ae6b.png)

Then I would set a path for custom binaries because I thought that was necessary for exportation
![screenshot 15](https://user-images.githubusercontent.com/16565772/29790078-017d8ef2-8bfe-11e7-8683-303d83247f70.png)

after undoing that last step, I find that my project runs just fine on linux

**Comment by akien-mga** [comment]
Great :)

The custom binary options are for when you build your own export templates (for example with a C++ module) and want to use them for export, without having to replace the original templates manually. So yeah, in general you don't need to define those.
