### ISSUE TITLE
Regression: drag and drop image to canvas crashes godot

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#10638]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux, Godot3 master commit https://github.com/godotengine/godot/commit/f75678a94f35bfdf177f1e13ba0f5824fec20e92

**Issue description:**
Using drag and drop to to e.g. add icon.png from the FileSystem docker to the canvas crashes Godot.
This issue must be a relatively new regession, since I don't remember it being present a couple of days ago.

**Steps to reproduce:**
1. Create a new project
2. Add a root node (e.g. Node2D) and select it
3. try to drag icon.png to the canvas

console output is not very helpfull in this case, I think:

```
SVG_GENERATION TIME: 0.094089
try to see fs update2
ERROR: _render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6264.
ERROR: add_child: Can't add child, already has a parent
   At: scene/main/node.cpp:1362.
from file: res://default_env.tres
from file: res://icon.png
cached: res://default_env.tres
cached: res://icon.png
allowed type ShaderMaterial,CanvasItemMaterial
fileS: [res://icon.png]
file: res://icon.png
type: StreamTexture
FILE vs ShaderMaterial
FILE vs CanvasItemMaterial
allowed type Script
fileS: [res://icon.png]
file: res://icon.png
type: StreamTexture
FILE vs Script
ERROR: cast_to: Condition ' p_object == __null ' is true. returned: __null
   At: core/object.h:567.
```

Tested with: clang 4.0.1 and  gcc 7.2.0

**Comment by novemberist** [comment]
Or is this possibly related to https://github.com/godotengine/godot/commit/cacced7e507f7603bacc03ae2616e58f0ede122a ?

**Comment by Rubonnek** [comment]
Thanks for reporting. This was, indeed, introduced by #10581.

I just pushed a commit that fixes this issue on #10591. Could you test that pull request?

**Comment by novemberist** [comment]
@Rubonnek I can confirm that this PR fixes the crash for me (compiled with gcc 7.2.0)

**Comment by Rubonnek** [comment]
@novemberist Thanks for testing.

**Comment by novemberist** [comment]
I think this is fixed now.
