### ISSUE TITLE
color picker and dimming

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#10634]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux, Godot 3 master

**Issue description:**
I know this might be an edge case and more of a minor issue, but I realized that trying to pick a color with the eyedropper from an area that is currently dimmed will not pick the original color, but the "dimmed color". This might happen when you are e.g. in the editor or project settings dialog and try to pick a color from your canvas. As a workaround one could of course disable dimming (temporarily), but this is still a little annoying.

**Comment by LeonardMeagher2** [comment]
Might be nice to just have a hot key for a color picker that puts the output in your clipboard

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by novemberist** [comment]
In fact, the color picker(eyedropper) doesn't seem to work at all now. It just selects seemingly random colors.

**Comment by akien-mga** [comment]
Yeah but that's a different issue (#15487). This one here is specific to dimming messing things up.

**Comment by novemberist** [comment]
True, but this one here is hard to test/reproduce if the wrong colors are retreived anyways.

**Comment by akien-mga** [comment]
Fair enough :)

**Comment by Perrottacooking** [comment]
v3.1.1 Stable -  Still with the same problem? yes? Then can send me any print?

**Comment by Perrottacooking** [comment]
hi mr.novemberist  
v3.1.1 Stable - Still with the same problem?
 yes? 
Then can send me any print?
did you try do same steps again and still with the same problem?

**Comment by novemberist** [comment]
@Perrottacooking Yes, it is still present in 3.1.1 stable and even latest 3.2 master. See screenshots below.

Steps to reproduce:

1. white rectangle in viewport 
![Screenshot_20190927_165909](https://user-images.githubusercontent.com/7927471/65779923-f83aaa80-e148-11e9-9d27-6c60596312a0.png)

2. open e.g. Project Settings, areas around it will get dimmed (white rectangle is now grey)
![Screenshot_20190927_165945](https://user-images.githubusercontent.com/7927471/65780008-1e604a80-e149-11e9-9191-572d958c5d49.png)

3. pick color from dimmed area
![Uploading Screenshot_20190927_170214.png…]()

4. color picker picks color after dimming, not original one (grey instead of white)
![Screenshot_20190927_170233](https://user-images.githubusercontent.com/7927471/65780139-64b5a980-e149-11e9-9c1a-0fdf3e947272.png)

**Comment by Calinou** [comment]
We could solve this by temporarily disabling dimming while using the ColorPicker's "pick color" feature.

**Comment by Calinou** [comment]
This has been resolved in the `master` branch, closing. If you're on 3.2.x, you can disable dimming in the Editor Settings.
