### ISSUE TITLE
Tabbed Container's children's Y position should account for TabHeight.

### ISSUE THREAD

**Issue by Brickcaster** [godotengine/godot#10633]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.3

**Issue description:**
I created a Tabbed Container and then created a panel child node.  Setting the panel's position to x,0 causes it to overlap the tab display.

**Expected behavior:**
Tabbed containers' children account for the offset of the tabs, similar to how children of Window Dialog use x,0 as the bottom of the title bar rather than cover it.

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by bojidar-bg** [comment]
Duplicate of #20750, thus fixed.
Fox the record, the problem was that the Y position could be changed, not that the TabsContainer didn't take it into account.
