### ISSUE TITLE
Reset audio bus volume

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#10631]
There should be a way to reset the volume of an audio bus back to 0 dB. It's not SUPER IMPORTANT or anything, but it would be nice to be able to bring a bus' volume back to an even 100% instead of having to guess visually. Something like a menu option when right-clicking the volume knob.

**Comment by vnen** [comment]
A few common shortcuts for this in DAWs is Ctrl + Click (Cubase), Alt + Click (Pro Tools) and Double-Click (all that on the volume slider itself).

In any case, a contextual menu option + a standard(ish) shortcut would be ideal.
