### ISSUE TITLE
alpha border issue

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#10632]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

**Issue description:**

Sprites alpha border seems to be bit strange:
![image](https://user-images.githubusercontent.com/1177508/29711629-036432bc-8996-11e7-8252-0631a56e2f3c.png)

I used a completely white sprite in the example, there shouldn't be any gray outline.

**Comment by novemberist** [comment]
Is "Fix Alpha Border" turned on in your import settings?

**Comment by razvanc-r** [comment]
Yes I tried all options in the import docker, nothing fixes the issue

**Comment by Sslaxx** [comment]
Don't forget to click on "Re-import"?

**Comment by razvanc-r** [comment]
I don't think I'm that stupid :)

**Comment by novemberist** [comment]
Would you mind sharing your sprite? or example project?

**Comment by razvanc-r** [comment]
Oh right, in game it seems there's no problem, it's only the editor, just checked, still needs to be fixed.
[godot-dbg.zip](https://github.com/godotengine/godot/files/1252057/godot-dbg.zip)

**Comment by novemberist** [comment]
I can confirm this issue.

**Comment by gamergamesz** [comment]
me too

**Comment by razvanc-r** [comment]
So, I am that stupid, sort of. So turns out I forgot about the stroke (in inkscape) so that's why there was the dark border. That being said, after fixing the images there still seems to be a problem here.

See attached project; both in editor & running game (for the complete solid white sprite - no blur):
[godot-dbg.zip](https://github.com/godotengine/godot/files/1252492/godot-dbg.zip)

**Comment by HummusSamurai** [comment]
FIxed by https://github.com/godotengine/godot/pull/12072?

**Comment by akien-mga** [comment]
Fixed by #12072.
