### ISSUE TITLE
Add to In-Engine Scripting API Documentation with a Plugin

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#10635]
Motivation:

1. I write a plugin.
2. I define an API for it.
3. I want people to be able to look up those classes and their associated properties, methods, and signals.

Ideal Features:

1. This information would show up in the API documentation in the engine.
2. People would be (ideally) able to look up this information on the Asset Library web page while perusing the plugin.
3. Clicking on a new class name in the Script Editor could let you jump to that class's documentation.

Something where we supply our own XML file to be read in and incorporated?

**Comment by Zireael07** [comment]
Have you tried actually using a module? This is what already happens with e.g. Zylann's terrain module or the fast_noise module

**Comment by willnationsdev** [comment]
I'm trying to look in those modules, but I don't see anywhere that this documentation is outlined. What file actually provides the documentation to the engine / how does it get connected?

Also, I'm looking specifically for something that would work with plugins, that way it can be handled with GDNative on the AssetLib.

**Comment by reduz** [comment]
This needs to be properly done when 3.0 comes out and people starts doing
plugins,but as the API is not stable yet, this is not done

**Comment by willnationsdev** [comment]
@reduz Can you elaborate on what you mean by "not stable"? What are the criteria that need to be met for the above features to be doable? What needs to be fixed / improved in order to reach those criteria? It'd be better if we can get a head start on it now before the 3.0 release.

**Comment by Zireael07** [comment]
3.0 needs to be released - right now the API is constantly being changed in preparation for 3.0.

**Comment by willnationsdev** [comment]
Ah, I see what you mean now. But that doesn't seem related to the methodology people use for integrating content into that API with plugins. That sounds like a perpendicular task. Can people just write up their own similar XML API document for a plugin and then get it rendered somehow? That's the methodology that I'm not familiar with.

**Comment by reduz** [comment]
@willnationsdev most probably will be via writing an XML, but writing it youself from scratch kind of sucks, so I want to think of ways to ease it up

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/177, closing.
