### ISSUE TITLE
Color replace modulation option

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#10646]
Modulation multiplies each pixels color of a canvas item.
I would like to have the option to replace each pixels color.

`color = vec4(replace_color.r, replace_color.g, replace_color.b, color.a);`

This is useful to recolour darker textures.
I'm particularly thinking about the dark editor icons. where modulation does nothing (multiply by 0...)

But I also can see other use cases. for example for a multicolour texture which should become singe color...

## implementation:
add a enum how to use the modulation color
```
modulation
    color
    modulation_type (replace, multiply...)
```

Add another value for modulation color and apply them after each other...

**Comment by groud** [comment]
This can be easily done with a shader, not sure it is that interesting.

**Comment by KoBeWi** [comment]
Yeah, the standard modulation is much more often used. Maybe there could be some set of built-in shaders to choose from, including the one requested in this issue.

**Comment by pycbouh** [comment]
From the replies above it seems like shaders are the way to do it. If you think that there is still some enhancement that can be done on the engine's side, feel free to [open a proposal](https://github.com/godotengine/godot-proposals) with your use case and a proposed solution.
