### ISSUE TITLE
CollisionPolygon Uses PoolVector2Array

### ISSUE THREAD

**Issue by cwook** [godotengine/godot#10640]
Windows 10, Godot 3.0 alpha1

**Issue description:**

The CollisionPolygon node uses a PoolVector2Array instead of a PoolVector3Array, completely breaking functionality.

**Steps to reproduce:**
Create a new CollisionPolygon node. Problem is also present when trying to make a CollisionPolygon from code.

**Comment by reduz** [comment]
it makes total sense that it's a 2D array, it's a 2D polygon aligned to the
z axis, is it not?

**Comment by cwook** [comment]
I wasn't aware that was it's intended function. Issue closed.
