### ISSUE TITLE
The `warnings=no` SCons option has no effect when building with MSVC on Windows

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#10651]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):** Windows 10 Creators Update, Godot Git https://github.com/godotengine/godot/commit/dd7145b778ea4884fd52f5efaf79dc55375c8465, MSVC 2017

**Issue description:** The `warnings=no` SCons option has no effect when building with MSVC on Windows (on the screenshot below, it is used in conjunction with `verbose=no` and `progress=no`):

![scons_msvc_warnings](https://user-images.githubusercontent.com/180032/29741972-1df22166-8a77-11e7-8e81-b6362ed1f779.png)

**Steps to reproduce:** Perform a Windows build using MSVC, passing `warnings=no` to the SCons command line.

**Comment by akien-mga** [comment]
Is this still reproducible?

**Comment by Calinou** [comment]
I just did a fresh build with MSVC 2017 and didn't notice any warnings being thrown by `cl.exe`. The linker still throws a few warnings like those, but I'm not sure if those can easily be fixed:

```
delaunay.windows.tools.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
```

I guess this can be closed for now.
