### ISSUE TITLE
Script editor crashing when performing autocomplete

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#10654]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):** Windows 10, Godot Git https://github.com/godotengine/godot/commit/dd7145b778ea4884fd52f5efaf79dc55375c8465 compiled with MSVC 2017

**Issue description:**
The script editor always crashes when performing autocomplete, which is usually done by editing characters in a script.

**Steps to reproduce:** In the example project (see below), edit the `autoload/console.gd` script at line 55. Specifically, try editing the string that is passed to the `append_bbcode()` function there. Editing the script in other places (such as comments, or variable declarations) does not seem to cause a crash.

Stack trace:

![script_editor_backtrace](https://user-images.githubusercontent.com/180032/29742508-dbb35a36-8a80-11e7-8aea-36d6a5c0c8d8.png)

**Link to minimal example project:** [godot-console.zip](https://github.com/godotengine/godot/files/1253751/godot-console.zip)

**Comment by hpvb** [comment]
I found the issue, making a PR.
