### ISSUE TITLE
Particles2d random initial velocity doesn't seem to do anything

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#10668]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

**Issue description:**
1. ~~Particles2D has a texture property with horizontal/vertical divisions. It implies it can use a picture, split it in tiles and randomly choose from those tiles. This does not happen, only first tile is used.~~ (done by ddadc78)
2. random initial velocity doesn't seem to do anything

See attached project: [godot-dbg.zip](https://github.com/godotengine/godot/files/1253958/godot-dbg.zip)

*edit:* Oh, and:
~3. if particles system isn't inside screen area it doesn't seem to work, particles should be emitted even if particle system outside of the rendering region (screen), like in the example above, you want the clouds to form before entering the picture, just try moving the particle system outside of the screen and run the project~

nevermind 3... I guess it has to do with the visibility rect setting

**Comment by razvanc-r** [comment]
@reduz, the commit seems to fix 1. but what about 2.? The random initial velocity...

**Comment by bojidar-bg** [comment]
Reopening as not fully fixed, as per above comment (would edit OP accordingly)

**Comment by reduz** [comment]
Particle code is the same for 2D and 3D (with a toggle to use them in 2D). Something may be working funny with the restart code, which is here:

https://github.com/godotengine/godot/blob/master/scene/3d/particles.cpp#L624
