### ISSUE TITLE
Shadows don't show by default, or are lower quality

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10672]
Godot 3.0 master
Windows 10 64 bits
nVidia 940M

I noticed shadows weren't visible with default DirectionalLight setup. I can only see them when I reduce bias from 1 to 0.1, or reduce distance considerably (from 200 to 10) and it shows very low quality shadows:

![image](https://user-images.githubusercontent.com/1311555/29745343-668cd24a-8ab8-11e7-99f7-8456a78c41e3.png)

Even though shadows still work, something might have changed recently that made shadows lower quality by default? Or is it my imagination?

**Comment by hpvb** [comment]
Would you mind setting up an example project with this? I'll run a bisect to see if it was recent. How long ago would you say it looked good?

**Comment by Zylann** [comment]
I'm not sure to be honest, I just remember that when checking shadows on a directional light I would see shadows right immediately, not having to setup anything to see them with good quality.

Here is the project, in the state it was just after I created a DirectionalLight, oriented it and enabled shadows:
[GizmoTransparency.zip](https://github.com/godotengine/godot/files/1253997/GizmoTransparency.zip)

**Comment by hpvb** [comment]
The problem was at least already present on Aug 22, can I ask you to try some of @Calinou's older builds and see if you can find a time where this looks as you expect? A bisect without any information would take a very, very long time :)

**Comment by Zylann** [comment]
Hmm I think I'll close the ticket, because in alpha1 the same creation steps yielded the same results. So it might just be my imagination, the fact I used spheres maybe.
