### ISSUE TITLE
Vertex color "use as albedo" is ignored when emission is white

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10679]
Godot 3.0 master
Windows 10 64 bits
nVidia 940M

I created a mesh with PRIMITIVE_LINES, but I am unable to make it output vertex color as emission. I enabled "use vertex color as albedo", but then it's shaded. If I set emission to white, it becomes white and ignores vertex color.
Related? https://github.com/godotengine/godot/pull/10441

Workaround: set the mesh as unshaded.

**Comment by reduz** [comment]
you cant emit a vertex color as emission, write a custom shader. In 3.1 you will probably get back visual shader graph for more customization
