### ISSUE TITLE
Script editor background is too clear / doesn't apply

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10674]
Godot 3.0 master
Windows 10 64 bits

I know this is subjective, but maybe it wasn't intented: the script editor background recently became brighter, same color as all other docks. As a result, text contrast became lower, it think it doesn't look good when coding.

![image](https://user-images.githubusercontent.com/1311555/29745602-8f515ad2-8abf-11e7-939a-dd8c484a745f.png)

Maybe it's related to this, when I open the picker for "background color", I see it's supposed to be black with some alpha:
![image](https://user-images.githubusercontent.com/1311555/29745620-1c369d36-8ac0-11e7-967a-0b2b2d57cf21.png)

If people prefer it to stay like this I'll probably crank down my background setting anyways... but maybe it's a bug?
Edit: I tried to change background color and I confirm it just doesn't apply.

**Comment by djrm** [comment]
@toger5 added an option to set the text editor background color to the base color (Text Editor / Theme / Adapted code editor background color), i think you have to uncheck that, also, i think thats not very obvious.

**Comment by Zylann** [comment]
I think the background of the text editor should just be the one set in Background Color, and if it has some alpha, blend with the background color set by the main editor's theme.

**Comment by Zylann** [comment]
It does apply on docs though
![image](https://user-images.githubusercontent.com/1311555/29745694-65bdb49c-8ac2-11e7-97f3-06228d6a69ea.png)

**Comment by toger5** [comment]
as djrm mentioned this is intended as a feature. I just think it looks much better if the code editor bg is the same than the rest of the theme.
although your poin, that having a transparent bg color for that perpus is really good! (haven't thought about that)
I also didn't really like that the highlight color background had not effect anymore...
So maybe we should revert the commit where I added the setting (it's always nice to get rid of settings)
And I make another pr that changes the background color of the script editor to fit the theme. and make the highlight bg color transparent. which would be the same result but it would be really easy to make it a little bit darker with the transparent value. That also gives custom text themes the option to override or keep the bg color by just adapting the transparency.
@Zylann so your concern is really good!

**Comment by Zylann** [comment]
Also, the console (which is a text field too) still has the darker background. I prefer text fields to have such a darker background tbh, but I note this in case you didn't see^^
![image](https://user-images.githubusercontent.com/1311555/29749873-f229699e-8b35-11e7-88a5-24940eb01ec1.png)

**Comment by toger5** [comment]
@Zylann so maybe we should change all the text fields: output, shader, codeEditor, docs to use the text editor color theme.
So than adding a 0.5 alpha black to the background color all the fields get adapted and look similar?
(and the ways you and maybe a lot of other ppl prefer it.)

**Comment by Calinou** [comment]
This issue doesn't seem to be present anymore as of 3.1.1 (the background is now opaque by default):

![image](https://user-images.githubusercontent.com/180032/59152333-1c5f6800-8a42-11e9-81b5-73a7a4c1bcff.png)
