### ISSUE TITLE
audio panning doesn't work

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#10689]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
godot 2.1.3
sound: 
AMD High Definition Audio Device
Realtek High Definition Audio 

**Issue description:**

Changed panning of a voice playing on a sample player. Sound stays the same in both ears. 
Sometimes it works, if I leave my PC for an hour and come back and hit play, panning works. The next time I run it it won't work.
 Restarting godot editor doesn't fix it, and neither does exporting it as a build and running the exe.
I've run several audio tests on youtube and the panning works in my headphones.

**Steps to reproduce:**
create a project with a sample player playing a track on loop, add some controls to change the panning in real time.

**Link to minimal example project:**

Use left and right arrows to adjust panning
[audiopantest.zip](https://github.com/godotengine/godot/files/1254498/audiopantest.zip)

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
