### ISSUE TITLE
next pass shaders don't work in 2D

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#10686]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

See attached project, the rectangle should be green, but it's red.... unless I'm misunderstanding something about the next pass, but I don't think so.
[godot-dbg.zip](https://github.com/godotengine/godot/files/1254427/godot-dbg.zip)

**Comment by akien-mga** [comment]
Is it still broken now? There were some shader issues the last few days due to a PR which was just reverted.

**Comment by razvanc-r** [comment]
I'll have to check, didn't use the latest builds because of the broken 2d particle system :D

**Comment by reduz** [comment]
they are not implemented because i really have no idea how to implement it..

**Comment by razvanc-r** [comment]
Well it makes sense it doesn't work then. @reduz I'm guessing this will be easier (or same as 3D) once 2D starts using meshes in v3.1?! Until then how about removing `Next Pass` for 2D in the inspector?
