### ISSUE TITLE
Adapt docs background to Highlight theme.

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#10685]
It would be great if the docs would be coloured based on the code editor theme.
#10674 mentions that.
@djrm @Zylann

**Comment by Calinou** [comment]
This seems to already be the case, see the Panel documentation when using the [Darcula theme](https://github.com/Calinou/godot-syntax-themes):

![Panel documentation in Darcula theme](https://user-images.githubusercontent.com/180032/29749833-4ce7f6a8-8b35-11e7-9de8-c7e3c5cc5584.png)

**Comment by toger5** [comment]
Oh...
Nice
I still keep the issue open since the background currently is handled differently. (see: #10674)
Will close when background behaviour fixes.
