### ISSUE TITLE
Autocomplete behaviour

### ISSUE THREAD

**Issue by tuga3d** [godotengine/godot#10695]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux 64 bits Godot [bd282ff](https://github.com/godotengine/godot/commit/bd282ff43f23fe845f29a3e25c8efc01bd65ffb0)

**Issue description:**

if you delete a line and the cursor lands on a word in the next line, if you delete characters in the middle of a word and if you uncomment a line while your cursor is on a word the autocomplete popup will show.

**Steps to reproduce:**
little animated GIFs that demonstrates the behaviour:

- deleting a line
![deleting a line](https://user-images.githubusercontent.com/410751/29797093-1b5d62d0-8c4d-11e7-94f0-43a6cc2b5ba8.gif)

- uncomment a line
![uncommenting a line](https://user-images.githubusercontent.com/410751/29797107-37461b9a-8c4d-11e7-8af3-64f49e1a9c12.gif)

- editing middle of word
![middle of word](https://user-images.githubusercontent.com/410751/29797115-45f7afbe-8c4d-11e7-8763-e6b3241d19c0.gif)

What other editors do is something like (using qtcreator as an example):

- deleting a line
![deleting a line](https://user-images.githubusercontent.com/410751/29797622-2f33a442-8c50-11e7-8a2a-389f1e74e67b.gif)

- uncomment a line
![uncommenting a line](https://user-images.githubusercontent.com/410751/29797629-35e5ced2-8c50-11e7-9896-78472f5e93d4.gif)

- editing middle of word
![middle of word](https://user-images.githubusercontent.com/410751/29797640-4afa8f9c-8c50-11e7-9cdf-ca12a3242262.gif)

**Link to minimal example project:**

**Comment by hpvb** [comment]
I think a 'generalized' way of putting the problem would be "Don't open autocomplete if the editor forces a cursor location change, only if the user instigated the move"

Does that sound about correct? This could help find a proper solution for #10691

**Comment by tuga3d** [comment]
I like it, but i don't know if it will work always, for example, in the case of moving lines up and down, is the user forcing a move, and the autocomplete will pop up.

**Comment by hpvb** [comment]
You mean at the end of a pasted line? That wouldn't be an explicit cursor move I think. It'd be the editor pushing the cursor due to the paste. Was that what you meant?

**Comment by tuga3d** [comment]
with (alt + arrow keys) you can move lines of code up and down and that will also trigger autocomplete.

**Comment by hubbyist** [comment]
What about "Open autocomplete only when the user instigated the cursor move or inserting new text over white space or inserting text just after deleting text." by using white list approach?

**Comment by tuga3d** [comment]
@hubbyist i have a different approach in my computer, i'll upload to github.
