### ISSUE TITLE
shader parameters accessible from shader inspector instead of material

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#10694]
Usability discussion.

Doesn't it make more sense to have the shader parameters accessible when the shader tab is open? At the moment you're forced to go back and forth between shader and and material to set the parameters. If you have factors to play with it's a pain to go back an forth like that, since the shader code editor closes.

So we have 2 options:
1. move the shader parameters under shader in inspector
2. don't automatically close the shader code editor when moving in the inspector & scene from shader to other resources/objects

I'd be happy with either, but I don't know the implications here.

**Comment by Zylann** [comment]
I'd go for keeping shader editor open, as done in several other cases (curve or gradient textures). Also because it doesn't make much sense to set uniforms directly on a shader, since shaders are used by materials, never directly

**Comment by razvanc-r** [comment]
I'd say I prefer that as well if I think about it

**Comment by KoBeWi** [comment]
With the new inspector in 3.1, which allows you to open resources without going to different inspector, can this be considered as fixed?

**Comment by akien-mga** [comment]
I think this can be considered fixed in 3.1 indeed.
