### ISSUE TITLE
Freelook mode does not play well with Gridmap editor

### ISSUE THREAD

**Issue by HummusSamurai** [godotengine/godot#10697]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 26 - Godot master HEAD

**Issue description:**

The RMB shortcut for freelook is conflicting with the delete action in the Gridmap editor.
More importantly, I sometimes get stuck in freelook mode which makes the WASD keys both move me around as well as rotate the object. One time I couldn't get into freelook at all so there's variation in the bug.

**Steps to reproduce:**
Use freelook in gridmap editor.

**Link to minimal example project:**

3D platformer demo

**Comment by Zylann** [comment]
Although it's possible to assign a modifier to trigger freelook, I wonder how this could be fixed. One should override the other.

**Comment by djrm** [comment]
i think freelook is more important than grid map shortcuts, so WASD could be replaced for 1234 or something close and delete tile to SHIFT + LMB . navigation should be consistent across all the 3d modes, also freelook is really useful when building maps.

**Comment by HummusSamurai** [comment]
@Zylann and @djrm : @reduz said that the WASD shortcuts can be fixed if we disable the gridmap rotation when RMB is pressed (so there is no need to disable one over the other).

As for delete tile being on RMB, @reduz did not suggest a solution on irc, IIRC, but Shift +Lmb should work fine.

**Comment by akien-mga** [comment]
> As for delete tile being on RMB, @reduz did not suggest a solution on irc, but Shift +Lmb should work fine and would be a smooth workflow.

I think he did mention Shift+LMB too, so go with that.

**Comment by djrm** [comment]
im solving this.
