### ISSUE TITLE
[3D view] selected object is not obvious 

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#10702]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3

**Issue description:**

While working with 3d models it is quite hard to distinguish selected object from the rest, because currently only bounding box is showed; I suggest showing outline for the selected 3d object.

As an addition, I also propose adding functionality to set mimap level for the background, so that in viewport the user can see blurred version- that helps to focus on the 3d objects by reducing visual noise in the scene.

![godot_3d_original](https://user-images.githubusercontent.com/9309589/29755933-1cfaccd8-8b97-11e7-9484-271be9d34ca2.jpg)
![godot_3d_suggestion](https://user-images.githubusercontent.com/9309589/29755934-1cfc4d06-8b97-11e7-85b5-87f0cdf261e0.jpg)

**Comment by reduz** [comment]
This will have to wait a while until stencil and render passes are
supported in the renderer

**Comment by akien-mga** [comment]
Jim, is that you? :O

**Comment by Calinou** [comment]
Selected objects could be highlighted in the scene, by increasing the "emissive" property of their materials. This should work and perform well, even on large objects (where you don't see any outlines in your view).

**Comment by Calinou** [comment]
Note that the selection box was made more visible in https://github.com/godotengine/godot/pull/40106. We should eventually try to have a proper outline, but I don't see a reliable way to implement it yet.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2795, as feature proposals are now tracked on the Godot proposals repository.
