### ISSUE TITLE
Some variables not shown in debugger

### ISSUE THREAD

**Issue by hoelzl** [godotengine/godot#10703]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Windows 10, Godot 2.1.4 stable, i7, GeForce GTX 1080

**Issue description:**

After setting a breakpoint in the debugger, only one of two variables in a script is shown. Which variable is shown changes between different runs of the script, but one of them is always missing.

**Steps to reproduce:**

Create a new project. Add a panel and a button as child of the panel. Attach the following script to the panel:

```
extends Panel

var _foo = null
var _bar = null

func _handle_button_press():
	if _foo == null:
		_foo = "foo"
		_bar = "bar"
	else:
		_foo = null
		_bar = null

func _ready():
	get_node("Button").connect("pressed", self, "_handle_button_press")
```
Set a breakpoint on the line `if foo == null:` and run the project. The debugger shows either `_foo` or `_bar`, not both.

**Link to minimal example project:**

[DebuggerTest01.zip](https://github.com/godotengine/godot/files/1255006/DebuggerTest01.zip)

**Comment by akien-mga** [comment]
CC @Geequlim

**Comment by Geequlim** [comment]
I know this bug and I have no idea with this.
The problem may stayed more than one years.

**Comment by Geequlim** [comment]
The bug may something wrong within implementations of  `GDScriptLanguage ::debug_get_stack_level_locals` or `GDScriptLanguage ::debug_get_stack_level_members`

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Comment by Reneator** [comment]
I currently have this problem, not showing variables that are instanced within an if-clause, if i set a breakpoint within the if-clause after the variable gets set:
![image](https://user-images.githubusercontent.com/24807557/56056793-75ba5c00-5d5d-11e9-8759-1cf432b1c44b.png)

With prints i made sure, that the spriteNode is not empty at this place, but i have no possibility to check how the spriteNode variable looks in godot itself, without manually adding a print for the spriteNode and restarting the game.

**Comment by Reneator** [comment]
Interestingly enough:
When i debug and put a breakpoint direclty on the line where the spriteNode gets instanciated i get a boolean value:

![image](https://user-images.githubusercontent.com/24807557/56076861-fddc4800-5dd5-11e9-8f9d-d51a2d767ca7.png)
