### ISSUE TITLE
When indenting code, Godot crashes because of expected indentation

### ISSUE THREAD

**Issue by LisacPisac** [godotengine/godot#10717]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.3 stable official, Antergos Linux x86_64, 4.12.8-2-ARCH

**Issue description:**
I added an inbuilt script to a viewport node and copied over the size and stretch override code example from [Godot's docs](https://godot.readthedocs.io/en/stable/learning/features/viewports/viewports.html#doc-viewports) inside the _ready()

It would be copied over unindented as so:
```
extends Viewport

func _ready():
viewport.set_size_override(w,h) #custom size for 2D
viewport.set_size_override_stretch(true/false) #enable stretch for custom size
```

And then, if I indented both lines of code as such:

```
extends Viewport

func _ready():
    viewport.set_size_override(w,h) #custom size for 2D
    viewport.set_size_override_stretch(true/false) #enable stretch for custom size
```

Godot will crash. This does not just apply to the viewport node, but to any node, it seems, as I tried it out on a panel node as well and it led to a crash.

P.S: For some reason, Godot's editor didn't allow code to be copied from it :/

**Steps to reproduce:**
Create a node. Attach a script. Copy/paste the aforementioned code from the Godot docs into the _ready() function and, sometimes without saving, Godot will crash.

THIS DOES NOT HAPPEN IF THE CODE IS WRITTEN BY HAND. (Edit: ok nvm this bit - it's because when writing by hand I didn't include the true/false division argument to the size_override_stretch function...)

**Comment by LisacPisac** [comment]
Well, when I look more closely... it happens because after I fix the indentation of the first line and the error parser gets to the second line where the supplied argument is (true/false), which isn't possible and that's what probably crashes the engine.

**Comment by akien-mga** [comment]
Please fill in:

> Godot version

**Comment by neikeq** [comment]
> THIS DOES NOT HAPPEN IF THE CODE IS WRITTEN BY HAND.

WHY NOT.

**Comment by neikeq** [comment]
The crash happens here

https://github.com/godotengine/godot/blob/bd282ff43f23fe845f29a3e25c8efc01bd65ffb0/core/variant_op.cpp#L673

because `true/false` is a division by zero.

**Comment by LisacPisac** [comment]
False resolves to 0, doesn't it? `true/false` is then `1/0`. Doesn't this mean that this isn't actually a bug?

**Comment by neikeq** [comment]
It's a big. The editor should have a check for this instead of crashing. Same for games in debug mode, for proper error reporting.
The crash is ok on release builds.

**Comment by groud** [comment]
Closing this issue, as #11291 is more explicit about the problem :)
