### ISSUE TITLE
Dragging an image from the resource pane to the 2d workspace results in a bad resource link

### ISSUE THREAD

**Issue by kurikaesu** [godotengine/godot#10713]
In the current revision in the repo, dragging any image from the resource pane to the 2d workspace (possibly any workspace) results in a resource path of for example; "res://some_image.png". 
It should be automatically be setting the resource to the "res://.import/some_image-8234823498234.stex" file behind the scenes but it doesn't.

Manually creating a Sprite->Adding a streaming texture->Loading the "some_image.png" will create the right links on the scene.

**Comment by kurikaesu** [comment]
Thinking about this further, this might not actually be a bug as the issue only happens when attempting to use the tscn files on the iphone platform.

I'm assuming that when a proper project export is done, the tscn files get compiled into .scn files and the paths should be updated to reflect .stex instead of the original source .png files.

**Comment by reduz** [comment]
No, It's ok that it does not use the .import folder. Nothing should ever reference the .import folder directly

**Comment by kurikaesu** [comment]
Looks like this was fixed recently, I'm going to close this issue!
