### ISSUE TITLE
Android custom build debugging failed

### ISSUE THREAD

**Issue by s0ra** [godotengine/godot#10711]
Windows 7 Gotdot 3.0 Aplha (committed around 8/26-8/27)

Android template has no errors while compiling. The debug version of game fail to be opened. I found that I missed a brace in the .java, and it shew no errors. After compiling again, it still stopped working on my phone.

**Steps to reproduce:**
1. Create an Android modules (may not required).
2. Compile the Android template. (no errors)
3. Debug the game and it will stop working.

*Not project specific.

**Crash report:**
https://pastebin.com/QceruiYN

**Comment by RandomShaper** [comment]
It seems you have built an ARMv6 variant. It's expected to work, but please try building for ARMv7.

Also I see no native symbols. If it's the debug version, something is wrong in the build system.

Can you show your commands for building the template?

**Comment by s0ra** [comment]
I used the same command as in the document.
scons platform=android target=release
cd platform/android/java
gradlew build

**Comment by s0ra** [comment]
I tried
scons platform=android target=debug android_arch=armv7
and it still crashed.

**Comment by s0ra** [comment]
My fault. I put the wrong directory into the config.py.
