### ISSUE TITLE
Godot freezes with "Interface -> Custom Font" set

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#10710]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.

**Issue description:**
A daily build of Godot from around a week ago broke the custom fonts (the global UI font - NOT the text editor font).

This seems to be related to the script editor, because the Godot window freezes (not responding) as soon as I open any script - while having a custom font for the UI.

**Comment by reduz** [comment]
This would probably need bisecting to find when and why it broke

**Comment by djrm** [comment]
this might be fixed by #12794

**Comment by vnen** [comment]
Was this solved?

**Comment by mhilbrunner** [comment]
I can no longer reproduce this as of most recent master, but there is something weird.

I set the font, save, reload the editor. The project manager then shows up correctly using the custom font, as does the editor after loading a project.

However, after a few seconds the editor switches back to using the default font everywhere.

**Comment by mhilbrunner** [comment]
Seems something after Godot 3 beta2 caused the issue above. With beta2, custom fonts work correctly. No hangs.

**Comment by akien-mga** [comment]
Should now be fully fixed with #15073.
