### ISSUE TITLE
Cannot import a PNG as an Image

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10719]
Godot 3.0 master
Windows 10 64 bits

I am trying to import an image in my project to be used in GDScript, not in rendering.
However, I can't figure out how to make Godot import it as an `Image`, there doesn't seem to be any choice in the import settings:

![image](https://user-images.githubusercontent.com/1311555/29776987-c0c1bb2e-8c0a-11e7-9299-aadc876e7d53.png)

**Comment by Zylann** [comment]
I'm having the same blocking problem in another situation:
I have an image I used on a Sprite, and I wish to access it as an Image to do some processing on it in GDScript.
Problem: it's a StreamTexture, the importer gives no choice on it, and nothing I tried let me simply get an `Image`...

**Comment by ElfEars** [comment]
+1 for this My stats are the same as @Zylann (although I'm using beta 1 instead of the master)

**Comment by KoBeWi** [comment]
Seems like it's possible in 3.1
