### ISSUE TITLE
List of scripts in editor lacks min width, can be fully hidden

### ISSUE THREAD

**Issue by WaterPower** [godotengine/godot#10722]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot v2.1.3

**Issue description:**

I could not see my script even if I open one. Picture https://www.reddit.com/r/godot/comments/6wify4/i_cant_access_any_script_what_did_i_do_wrong/

**Steps to reproduce:**

You have to push the "wall" between the list of script and the script all the way to the left 

**Link to minimal example project:**

**Comment by saltares** [comment]
This no longer seems possible with Godot 3.0 (master) 4bde108d89113fb520ecfd4961d9fb3e7882e59f. Has it been fixed?

**Comment by mhilbrunner** [comment]
Yup, seems to be fixed. Has a min-width now for me.
@akien-mga This can be closed, I think?
