### ISSUE TITLE
There's no way to set stream loop on/off from inspector

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#10726]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

I used `.ogg` by loading the stream from disk. I see the 3D demo has loop options for the imported `.wav`s. Maybe I didn't set it up correctly? I just loaded the `.ogg` directly from disk

**Comment by akien-mga** [comment]
What Godot version? 3.0-alpha has been around since 2 Jan 2017 :) 45c5c89de961357a7042d9e1f063e288d7a510cf

**Comment by Noshyaar** [comment]
IIRC looping is set from Import dock. Latest master has no loop option in AudioStreamPlayer.

**Comment by razvanc-r** [comment]
There is an option in the sub-resource, the stream (for WAV, not OGG).

Also the audio stream player should have some signals like "start", "stop" playback. And it also returns playing == true even after the playback finishes. @akien-mga should I open separate issues for that? :D

**Comment by akien-mga** [comment]
> should I open separate issues for that? :D

Yeah that would be clearer.

**Comment by akien-mga** [comment]
When I played with this a couple days ago, I think I saw loop options in the Import tabs for OGG streams, do you confirm? If so this issue is fixed (but #11231 is still valid: there's no loop option exposed in the AudioStreamPlayer itself).

**Comment by burstina** [comment]
Acutally, if you load an OGG file directly from AudioStreamPlayer, you cannot set loop on/ff, it is just enabled by default

**Comment by Calinou** [comment]
Duplicate of #35314, which has more information about the issue at hand.
