### ISSUE TITLE
Basis(Vector3 euler) constructor is not recognized by the parser

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#10721]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 8.1
Godot 3.0 alpha1

**Issue description:**

According to the documentation, the Basis class has a constructor which takes a single Vector3 to create a basis from euler angles. In practice, however, using this constructor results in a parser error:
>Parser Error: Invalid arguments for 'Basis'' constructor.

**Steps to reproduce:**
1. Create a new project with an empty scene
2. Create a new script attached to the scene and put the following code inside it:

```
extends Spatial

func _ready():
   var test = Basis(Vector3(1,2,3))
```

You'll notice the game crashes with the error mentioned above.

**Comment by tagcup** [comment]
I attempted to add that function in #8277 but I'm not really familiar with GDScript bindings, apparently I didn't do doing something correctly

**Comment by hpvb** [comment]
@tagcup I believe you added the binding correctly, I think this is a bug with the parser. It seems that it doesn't understand that the euler constructor is not an incomplete 'axis' constructor. I'm looking into it.

**Comment by reduz** [comment]
This is implemented in Variant::construct and Variant::can_convert functions
