### ISSUE TITLE
Toggle comment could be smarter

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10720]
Godot 3.0 master

I have a very big function that doesn't compile but I want to keep it around. So I tried to comment it, which is only possible line by line, so I used the Ctrl+K shortcut to batch-comment all of the lines.
Unfortunately, any lines in the function that were already commented with Ctrl+K were left uncommented, breaking compilation.
QtCreator is able to deal with this, but Godot steps on its own toes:

Short example:
```gdscript
func _init():
#	_noise.set_seed(131183)
#	_noise2.set_seed(_noise.get_seed() + 1)
	_image = _image.get_data()
```
Expected:
```gdscript
#func _init():
##	_noise.set_seed(131183)
##	_noise2.set_seed(_noise.get_seed() + 1)
#	_image = _image.get_data()
```
Obtained:
```gdscript
#func _init():
	_noise.set_seed(131183)
	_noise2.set_seed(_noise.get_seed() + 1)
#	_image = _image.get_data()
```

So the behavior could become: after whitespace is stripped, if all selected lines start with `#`, remove them. If not all lines start with `#`, add one to each.

**Comment by curly-brace** [comment]
also if you have
```
func _init():
	#_noise.set_seed(131183)
	#_noise2.set_seed(_noise.get_seed() + 1)
```
it won't be uncommented, but it could be commented out once more (`#     #_noise.set_seed(131183)`)

**Comment by anakimluke** [comment]
Should it add/remove comments from all selected lines based on the first line, or based on the amount of lines that are already commented?

**Comment by curly-brace** [comment]
i think first line should be counted, like if it is not commented, everything selected should be commented out

**Comment by Zylann** [comment]
@anakimluke not even the amount, the rule I propose fits in one sentence at the end of my post:
If the concerned lines are all commented out, it removes one `#` from each. Otherwise, it adds one.

**Comment by curly-brace** [comment]
i think if user selects first line, that is not commented, he wishes comment the whole block. if he selects that first line is commented, he wishes to uncomment the whole block. i hardly imagine situations where someone plays logic puzzles with blocks that have partial comments, that he wants to be switched.

**Comment by Zylann** [comment]
@curly-brace the feature I propose doesn't care about blocks, it's litterally line-based, and should only deal with lines that you have selected. So if you select the first line in the example and use the feature, only that line will be commented / uncommented. This is litterally the exact same logic QtCreator and Sublime Text have.

**Comment by tuga3d** [comment]
I agree with Zylann here, because if you have a block of code with comments in it, and you wish to comment it, is all good, but when you later go to uncomment the block all the previous comments become uncommented, breaking your code.

ex:
```gdscript
func _init():
        # A real comment, not commented code.
        _noise.set_seed(131183)
        _noise2.set_seed(_noise.get_seed() + 1)
```
when commenting should become:
```gdscript
#func _init():
        ## A real comment, not commented code.
        #_noise.set_seed(131183)
        #_noise2.set_seed(_noise.get_seed() + 1)
```
so when you uncomment the original comment is retain.

**Comment by anakimluke** [comment]
@tuga3d, I think with this code there is still the problem that it is not ignoring empty lines, isn't it?

**Comment by Zylann** [comment]
Empty lines can eventually be ignored

**Comment by tuga3d** [comment]
yep forgot about that :p
