### ISSUE TITLE
Particle system shouldn't clear already emitted particles if amount property is changed

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#10732]
Operating system or device, Godot version, GPU Model and driver (if graphics related):
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

The rationale behind this is simple, if you want to start a fire or start anything really, smoke density etc. there's no easy way to do it because if you change the amount via animation player for example, the particle system will clear/reset every frame.

**Comment by razvanc-r** [comment]
Also goes for emitting, it shouldn't just turn off all the particles at once, they should be left alone until their lifetime expires.

**Comment by bojidar-bg** [comment]
Related to / Duplicate of #4294.

**Comment by razvanc-r** [comment]
closing this in favor of #4294
