### ISSUE TITLE
build godot with vs 2017 Cannot open include file: 'globals.h'

### ISSUE THREAD

**Issue by trommlbomml** [godotengine/godot#10736]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Microsoftt Windows 10 x64, Godot Master commit d664469ec72337c2ec31c2e0d5a3d82c30305b7c, Intel HD graphics 5000/geforce gtx 840m

**Issue description:**

I have followed the documentation and [this guide](https://godotengine.org/qa/13282/visual-studio-2017-vsproj-yes-did-not-work) to try to build godot under vs 2017 with the developer command prompt (so win32). Unfortunatly the build breaks with the following error:

> core\global_defaults.cpp(1): fatal error C1083: Cannot open include file: 'globals.h': No such file or directory

I looked into the directory, the file is not present as the error describes.

**Steps to reproduce:**

Follow default build for windows documentation, install latest python tools and current source from scons because of vs 2017 support.

**Link to minimal example project:**

Unneeded.

**Comment by akien-mga** [comment]
It's a transient issue, remove the `core\globals_default.cpp` file. I you get other similar issues, remove the corresponding files too. Or alternatively, clean your git repo with `git clean -fX` or make a clean git clone.

**Comment by trommlbomml** [comment]
ok thx :)
