### ISSUE TITLE
Collapse / expand child nodes in scene tree by using left- / right-arrow keys

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#10737]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.3
Godot 3

**Issue description:**

When navigating inside the scene tree using the keyboard, only the up-arrow and the down-arrow keys are working to select other nodes.

It would be helpful to be able to collapse all children nodes by pressing the left-arrow-key.
If there are no child-nodes, the selection should jump to the parent of the currently selected node.

If there are child-nodes, the right-arrow-key should expand these children.

Edit:
If the child-nodes are already expanded, the right-arrow-key should jump to the first child.
if there are no-child nodes, the right-arrow-key should jump to the next sibling

This way the tree could easily be traversed by holding the right-arrow-key.

Edit 2: 
As mentioned below, pressing the alt-key additionally could be used to expand/collapse all sub-nodes up to the scene-tree-leaves.

**Comment by groud** [comment]
Is that a common behaviour with other editors ?

**Comment by BeayemX** [comment]
It is that way in unity and also in the windows file-editor in the side bar this works.

I'm not sure if it is common, but it's definitely something I'm missing and also it would not interfere with other keybindings.

**Comment by groud** [comment]
Ok. I've got no problem with the proposal, I just wanted to know ^^

**Comment by BeayemX** [comment]
Btw in unity you can hold the alt-key in addition to the arrow-keys to collapse / expand all sub-children (up to the scene-tree-leaves). 

I'm not sure if this should go into a separate issue or if it belongs to this one

**Comment by groud** [comment]
Keep it in this one, this should not be hard to implement I think.
