### ISSUE TITLE
EGL error: 0x3005 on Android deployment

### ISSUE THREAD

**Issue by Myran** [godotengine/godot#10735]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS 10.12.26
 
built from commit: d664469ec72337c2ec31c2e0d5a3d82c30305b7c

Android Device:
Huawei P8 Lite , Android version 5.0.1

**Issue description:**

Built godot and android templates successfully
Deploys to device successfully however it crashes immediately

adb Logcat shows:

I/godot   (30744): **INIT EVENT! - 0xab8c4508
I/godot   (30744): ***************** HELLO FROM JNI!!!!!!!!
I/godot   (30744): *******CLASS FOUND!!!
I/godot   (30744): STEP2, 0x1003ea
I/godot   (30744): STEP3 1968521024
I/godot   (30744): STEP4, 0xe070001d
I/godot   (30744): STEP4.5, 0x1003ee
I/godot   (30744): STEP7
I/godot   (30744): STEP8
I/godot   (30744): *******GOT METHOD _dir_open ok!!
I/godot   (30744): *******GOT METHOD _dir_next ok!!
I/godot   (30744): *******GOT METHOD _dir_close ok!!
I/godot   (30744): *******GOT METHOD _dir_is_dir ok!!
I/godot   (30744): starting to attempt get methods
I/godot   (30744): *******GOT METHOD _init_audio ok!!
I/godot   (30744): *******GOT METHOD _write_buffer ok!!
I/godot   (30744): *******GOT METHOD _quit ok!!
I/godot   (30744): *******GOT METHOD _pause ok!!
I/godot   (30744): CMDLINE LEN 2 - APK EXPANSION I
I/godot   (30744): ERROR: create: Condition ' !create_func ' is true. returned: 0
I/godot   (30744):    At: core/os/mutex.cpp:38.
I/godot   (30744): test construction 5
I/godot   (30744): running from dir /
I/godot   (30744): **SETUP
W/PGApi_client( 3565): recv actoionId = 10000, action = com.huawei.pgmng.PGAction@3597c615 actionId =10000 pkg =org.godotengine.test2 extend1 =91 extend2 = flag =3 type =1
W/PGMiddleWare jhh( 3565): in handleAction method, action = 10000
W/PGMiddleWare jhh( 3565): in handleAction, invoke client = com.huawei.pgmng.middleware.AudioEffectLowPowerImpl@3f0ae547, action = com.huawei.pgmng.PGAction@3597c615 actionId =10000 pkg =org.godotengine.test2 extend1 =91 extend2 = flag =3 type =1
I/AudioEffectLowPowerImpl jhh( 3565): jhh handle default mActionId = 10000, action = com.huawei.pgmng.PGAction@3597c615 actionId =10000 pkg =org.godotengine.test2 extend1 =91 extend2 = flag =3 type =1
W/AudioEffectLowPowerImpl jhh( 3565): enter into DEFAULT_FRONT Scene.
W/AudioEffectLowPowerImpl jhh( 3565): m2DGameFront = false, m3DGameFront = false, mMediaPerceptible = false, mMusicPerceptible = false
W/AudioEffectLowPowerImpl jhh( 3565): mAudioActive = false, mMusicPerceptible = false
W/AudioEffectLowPowerImpl jhh( 3565): return for smartPAOn and mLowAudioEffectEnable both = false
I/godot   (30744): *****SETUP OK
I/godot   (30744): WARNING: not found: display/driver
I/PanelView( 3283): Configuration orientation changed
I/HwCust  (30744): Constructor found for class android.widget.HwCustTextViewImpl
I/PhoneStatusBar( 3283): shouldTranslucent:true
I/PhoneStatusBar( 3283): hw_status_bar_operators = true, setSystemUIVisibily(SHOW_OPERATOR = false)
E/textview(30744): initAddtionalStyle default
I/godot   (30744): WARNING: not found: display/driver/keep_screen_on
I/godot   (30744): **START
I/PG Utils( 3283): acquire_providerpkg:[com.android.providers.contacts] pid:[]  maybe timeout , send to PG
I/TimeManager( 3283): receiver action = android.intent.action.CONFIGURATION_CHANGED
E/SensorManager(30744): sensor or listener is null
E/SensorManager(30744): sensor or listener is null
W/View    ( 3283): requestLayout() improperly called by com.android.systemui.statusbar.phone.IconMerger{11d20ce6 V.E..... ......I. 0,0-72,50 #7f0d0086 app:id/notificationIcons} during layout: running second layout pass
I/TimeManager( 3283): hand message 1
I/TimeManager( 3283): notify time change. size = 2
I/TimeLayout( 3283): time = 19:07
I/TimeLayout( 3283): updateDate date = 28/08/2017
I/TimeLayout( 3283): weekDay = Monday
W/View    ( 3283): requestLayout() improperly called by com.android.systemui.statusbar.phone.IconMerger{11d20ce6 V.E..... ........ 0,0-72,50 #7f0d0086 app:id/notificationIcons} during second layout pass: posting in next frame
I/PhoneStatusBar( 3283): hw_status_bar_operators = true, setSystemUIVisibily(SHOW_OPERATOR = false)
I/OpenGLRenderer(30744): Initialized EGL, version 1.4
W/GodotView(30744): creating OpenGL ES 3.0 context :
E/GodotView(30744): After eglCreateContext: EGL error: 0x3005
E/AndroidRuntime(30744): FATAL EXCEPTION: GLThread 268
E/AndroidRuntime(30744): Process: org.godotengine.test2, PID: 30744
E/AndroidRuntime(30744): java.lang.RuntimeException: createContext failed: EGL_SUCCESS
E/AndroidRuntime(30744): 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1201)
E/AndroidRuntime(30744): 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1192)
E/AndroidRuntime(30744): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1042)
E/AndroidRuntime(30744): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1409)
E/AndroidRuntime(30744): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by RandomShaper** [comment]
I'll check this. I can test on the same phone model and try to get Godot finding a suitable EGL config.

**Comment by Myran** [comment]
Apparantly there is 2 versions of the Huawei P8 lite. I tested with  ALE-L21 which does not support OpenGL ES 3.0.

**Comment by RandomShaper** [comment]
What a pity! But that explains the problem.
