### ISSUE TITLE
Script editor show text over the lower part when debugger is opened

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#10738]
**Operating system Ubuntu, Godot version 2.1.4 pre release**

**Issue description:**
Script editor show text over the lower part when debugger is opened.

![214scripteditorbug](https://user-images.githubusercontent.com/10215987/29795998-44ad71f2-8c25-11e7-9558-a21cf9e647f9.png)

**Steps to reproduce:**
Open the debugger with a script opened, extend up the debugger to see when the lines appear.

The screen resolution is 1366x768, no hidpi, if that matters.

**Comment by eon-s** [comment]
I don't see this issue on any previous 2.1.4 release (including the RC).

**Comment by akien-mga** [comment]
I guess one of those cherry-picks was too much: 802fab11e4d63851ed36fc4e2a54a000c3c4ee18 or e41b44747cc62783436304911906e12d59cc6c78

**Comment by akien-mga** [comment]
@eon-s 
![cat release day](https://user-images.githubusercontent.com/4701338/29825476-d2d58e42-8cd4-11e7-9622-5c907682abad.jpg)

**Comment by akien-mga** [comment]
Fixed in f48f6cea. I don't want to retag 2.1.4-stable and redo binaries for it though, so we'll have to live with it. Doesn't look very professional but it's a minor issue, I guess it's ok.

**Comment by eon-s** [comment]
We will have to wait for 2.1.5 then :see_no_evil:
