### ISSUE TITLE
AnimationTreePlayer mix node has unintuitive behavior

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#10753]
Operating system or device, Godot version, GPU Model and driver (if graphics related):
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

I used this exclusively in 2D.

The mix node mixes between... a "default" state of the parameters to the ones in the animation. Take for example a simple rotation. If you make an animation of 360 deg. rotation, but having the first keyframe (at T0) be 90 deg. instead of 0. And say you have a second animation of horizontal looping motion, doesn't really matter. Now say we want to mix the horizontal movement with the rotation. The horizontal animation has no track for rotation. Then the mix node mixes from "default" state of the object (0 deg.) to the animation rotation.

I think a more useful mix node would have targets for each track of the mixed in animation. Or at least have a target animation for beginning and another for the mixed in. Or there should be a way to define the global "default" state to transition from with the mix node instead of assuming every parameter should mix in from 0 to the animation set parameters.

It's hard to explain but check the attached project, play with the edit slider on the mix node in animationtreeplayer and check the rotation animation in animationplayer. It's definitely not intuitive.

[godot-dbg.zip](https://github.com/godotengine/godot/files/1260079/godot-dbg.zip)

**Comment by razvanc-r** [comment]
Hm, I guess the problem is a bit more deep than this, most blend/mix nodes behave unintuitivley since there's no way to add target blend/mix to them to interpolate from.

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
