### ISSUE TITLE
AnimationPlayer usability & improvements discussion

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#10752]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

I feel like the animation player is not intuitive at all. I propose to make it work like blender. Eg, things I found that don't make sense (some might be bugs):

1. some properties are modified even if the play cursors hasn't reached the keyframe. For example, take canvas modulate, and insert only one keyframe say at second 3 and change the color to something other than white (say red). Start the game with canvas modulate color at pure white. It turns out that the canvas modulate will be red immediately, even though there's no key to change it to red at 0! The position on the other hand behaves correctly, that is if you insert a key at second 3 and there's no other keyframe before that, then the object won't move until second 3 is reached. I've only tried a handful of properties but so far the only reasonable behavior is on position

2. if loop is turned on don't try to interpolate between last keyframe (before the animation finishes) and the first keyframe. Instead let's follow the blender way, so if I have a sprite that moves from left to right and only 2 keyframes, one at T0 and one at T1 and animation length of 2 seconds with loop turned on, I expect sprite to move only between T0 and T1. How it's implemented at the moment is, if loop is on, then there will be an interpolation between T1 and T0 as well (from second 1 and second 2). I think this isn't intuitive. Blender has some pretty good standards, if they do it that way they probably have a good reason why.

3. would be great if we could be able to type a number in the `Transition` panel instead of just relying on the mouse to move the easing around.

If you guys can think of anything else let the discussion begin :)

**Comment by RandomShaper** [comment]
1. Yes, that shouldn't happen. I think I know why it does and maybe I can fix it.
2. Interpolation between cycles is interesting, but indeed not always desirable. Looping mode could be changed from on/off to off/on/on-interp-cycle.
3. Yes, sometimes it takes a while to get the exact value you want. Improving that would benefit every place an easing editor is present.

**Comment by razvanc-r** [comment]
Actually if I think about it, blender has a way to modify the loop behavior (extrapolate). So in the F-Curves editor for example, the animation can be set between:
- constant extrapolation
- linear extrapolation
- make cyclic (what godot is doing by default)
- and clear cyclic (what blender does by default)

**Comment by RandomShaper** [comment]
1. Addressed by me (#12107).
2. Already done (don't know by whom nor when).
3. Addressed by me (#12113).

**Comment by fracteed** [comment]
One of the main issues I keep running into is the inflexibility of the step value. Currently it can only be set to 2 decimal points which makes it impossible to set for 30 fps. You could set it to animate at 20fps(0.05) or 25fps(0,04) but these are not good values when your target game fps is likely 60fps.

Not sure what a good solution for this is, as how many decimal points to approximate 1/30 is needed. Maybe a mode where you can use a fps value and animate on frames would be ideal.

**Comment by reduz** [comment]
1. Agreed, this should only work as you describe if interpolated loop is
enabled.
2. You can choose this behavior per track
3. Yeah makes sense

Regarding step, i think we should have a button to switch between step and
fps, since they are pretty much the same.. and edit the animations in both
modes.

I have a long list of usability improvements for this, but was waiting for
after 3.0 to work on them..

**Comment by cwook** [comment]
Here's another issue talking about Animations: #11359

My suggestion to improve AnimationPlayers is an additional transition curve known as spring/elastic. It's helpful for animating natural movements with few keyframes, as it's a fairly realistic interpretation of how living things move.

A good demonstration of using spring/elastic easing to speed up procedural animation: [David Rosen Procedural Animation GDC](https://youtu.be/LNidsMesxSE?t=7m39s) (See also 17:42)
There's an interactive comparison of easing functions [here](http://easings.net/)
This issue discusses the ease function, which is related: #10572

**Comment by reduz** [comment]
I will be working on this the next weeks, so any feedback will be very
welcome.

**Comment by aaronmzn** [comment]
for frame by frame animations I prefer changing the Frames per second (fps) value like in AnimatedSprite or the animation speed with a Duration per frame (milliseconds) value like in Aseprite (even better)

AnimationPlayer is not meant to be used for frame by frame animations. Even if you give the option to change the speed with a single value, you will be dealing with moving keyframes through the timeline and that's not needed for sprite animations

AnimatedSprite node is better for that job but its lacks features (like the keyframing feature or sprite sheet support)

I suggest separating **AnimationPlayer** node to be focused only for what is made for, cutouts animations / tweening  and leaving **AnimatedSprites** node for frame by frame animations adding it keyframing feature

this way AnimationPlayer wont be overflowed with features that some people may never use (like me with sprite animations)

I opened an issue about this here it is #12469

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by samdze** [comment]
A few more suggestions:

1. I think it should be clear from where every animation of an AnimationPlayer come from. Right now the animation list only displays animation names, but I'm never sure if they are built-in, from another scene or saved in the filesystem. I often end up modifing an animation in one AnimationPlayer and get another AnimationPlayer broken.
2. In support of point 1 I would like better copy/paste capabilities, like being able to choose between a shallow or deep copy.
3. Right now assigning an Object as a parameter in a callback in a Call Func Track doesn't work, drag and dropping a resource there locks the mouse in the middle of the window and a restart of Godot is required.

**Comment by akien-mga** [comment]
AnimationPlayer was rewritten from scratch for 3.1 and has tons of UX improvements. I'll close this issue as it's no longer relevant as is, but if some of its points are still relevant in the current master branch, feel free to open new issues specific to each of them.
