### ISSUE TITLE
Windows 64bit release template crashing

### ISSUE THREAD

**Issue by Kermer** [godotengine/godot#1076]
Only happens when exporting on Windows 64bit with debug mode OFF:
App crashes instantly when mouse enters it's window. With debug mode on everything works fine as well as 32bit.
Even 1 scene with just empty Control node crashes.

Exception code: c0000005

**Comment by lekoder** [comment]
I can confirm it on `godot_win64-1.0stable.exe` with `export_templates-1.0stable.tpz`.

**Comment by Murii** [comment]
As you can see in the source code the debug mode is something very complex and seen a lot in many different files.So there could be many approches,very hard to fix.So there are two possible fixes: 
1)leave it as a debug release(I cant see a reason to not let it so) 
2)Perhaps the admins changed something recently and only they know how to fix this issue.

**Comment by macramole** [comment]
I can confirm this issue too

**Comment by And-0** [comment]
Can confirm this as well :/

**Comment by Heybye44** [comment]
Mine crashing on start up and I'm getting DEP warnings. I'm running Windows XP Media Center Edition on a Gateway GT4026E.

**Comment by akien-mga** [comment]
I believe this issue has been fixed as we no longer get reports about it. Feel free to reopen if it can still be reproduced with 1.1-stable templates or with daily builds of 2.0.
