### ISSUE TITLE
Simple project crashes on startup

### ISSUE THREAD

**Issue by Kinerius** [godotengine/godot#10777]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):** 
Os = Windows 10
build = v3.0.alpha.custom_build.8fce79a

**Issue description:**
Im just trying to spawn a child scene with a visual script. No Tutorials / Documentation used for this. 

**Steps to reproduce:**
- Create a new scene with a Spatial > Rigidbody > MeshRenderer + CollisionShape nodes
- Save scene
- Drag and drop the scene on the visual script and attach to the add_child ( on the _ready func )

**Link to minimal example project:**
[TestProyect.zip](https://github.com/godotengine/godot/files/1262159/TestProyect.zip)

**Comment by Kinerius** [comment]
Update:
 - It seems the Preload asset reference goes back to empty, on SpawnPoint.vs, after closing godot
 - if its empty, drag and drop the CharacterController.scn to the visual script editor and connect it to the add_child

**Comment by hpvb** [comment]
Does this project still crash on master for you? I get an error about a missing resource, but no crash.

**Comment by reduz** [comment]
It may be fixed, but if anyone can give a check it's still welcome

**Comment by Kinerius** [comment]
Checked out with 3.0 alpha 2, game wont crash, you will get a null ref instead.
