### ISSUE TITLE
Networking tutorial is bad

### ISSUE THREAD

**Issue by bkeys** [godotengine/godot#10773]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 26, Godot master branch

**Issue description:**
I followed this tutorial
https://godot.readthedocs.io/en/latest/learning/features/networking/high_level_multiplayer.html?highlight=networking
And I get a scripting error

**Steps to reproduce:**
You can run my project and it will report a scripting error

**Link to minimal example project:**
https://my.mixtape.moe/dtwrzn.zip

**Comment by akien-mga** [comment]
Please open documentation issues on the documentation repo: http://github.com/godotengine/godot-docs

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/godot-docs/issues/450.
