### ISSUE TITLE
RigidBody2D strange behavior when working with _integrate_forces

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#10783]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

I try applying a force to the rigid body based on the position of another node, but only if the distance between them is above a certain value. The other node is tied to the mouse position.

If I move the node quickly (immediately after the game starts) then the rigid body moves as expected (the if statement passes and all is right).

If I wait a bit (> 1 sec) before I move the other node with the mouse, rigid body doesn't do anything, it's like the `if` statement inside the `_integrate_foces` breaks stuff. Tried without `if` and works as expected.

Check project.
[godot-dbg.zip](https://github.com/godotengine/godot/files/1263321/godot-dbg.zip)

**Comment by eon-s** [comment]
Sounds like the body is sleeping, try disabling sleep by property or adding `sleeping = false;` in the integrator.

**Comment by razvanc-r** [comment]
You're right, I forgot about sleeping behavior, closing this.
