### ISSUE TITLE
Input is not working

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#10789]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
linux mint 2.1.4 stable

**Issue description:**

I try to export my game in linux and the input is not working but it works in the editor.
I tried two project and one of it works, the difference in the code are the use of _Input(event) + event.is_action_pressed() and Input.is_action_pressed(), only the later one works.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
Can you reproduce the issue in 2.1.3-stable too? Could you provide an example project that shows the problem?

**Comment by akien-mga** [comment]
I can't reproduce the issue, this works fine for me both in the editor and in the exported binary:
```
extends Node

var is_echo = false

func _input(event):
	if event.is_action_pressed("test"):
		print("Action 'test' pressed in _input(event).")
	elif event.is_action_released("test"):
		print("Action 'test' released in _input(event).")

func _process(delta):
	var is_pressed = Input.is_action_pressed("test")
	if is_pressed and not is_echo:
		print("Action 'test' pressed in _process(delta).")
	is_echo = is_pressed

func _ready():
	set_process_input(true)
	set_process(true)
```

The "test" action is bound to the <kbd>T</kbd> key. Pressing it properly shows the expected output:
```
Action 'test' pressed in _input(event).
Action 'test' pressed in _process(delta).
Action 'test' released in _input(event).
```

**Comment by akien-mga** [comment]
Obligatory question... did you update your export templates?

**Comment by ZX-WT** [comment]
yes, I did update the export templates. I will try to reproduce it in 2.1.3

**Comment by ZX-WT** [comment]
ok it doesn't work on 2.1.3 stable as well, can the problem be platform specific? I export it to X11.
[bug_test.zip](https://github.com/godotengine/godot/files/1264074/bug_test.zip)

**Comment by akien-mga** [comment]
You forgot to define a main scene, so the script is not loaded :)

When defining the main scene as it should be, it all works fine on X11 for me (Mageia 6 x86_64).

**Comment by ZX-WT** [comment]
ok, after some testing, the input does work. My bad in using instance(), after removing the true, it works as expected.
