### ISSUE TITLE
Move everything from .godot/config into corresponding project folders like .tmp

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10781]
today i was tinkering with shaders and again made editor crash (i have no source because editor crashed and code was not saved). but after i've tried loading the project again, it crashed on splash again.
i tried reviewing what i had in project folder, even deleted the tscn file. but i was only able to load, after i've deleted `project_metadata.cfg` that i've found using process monitor application.

but if all this stuff was in project_filder/.tmp i could just delete that folder and proceed with the work.
why keep development data outside the project folder anyway?

UPD: in project_metadata.cfg there was only one setting - update_always=true. so this is just a part of my problem, bugged shader is still somewhere, but is not touched by the editor upon loading

**Comment by mhilbrunner** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
The request itself would still be relevant, but I don't think it's worth changing how project metadata work now. The metadata gets written to `~/.config/godot/projects/<project-slug>`, so as long as it's properly documented it's not too complex to find out when needed. On the other hand, forcing a `.tmp` folder in all project folders would be a bother (especially on Windows where a leading dot does not denote a hidden folder, so it would be visible - and people would version it in git).
