### ISSUE TITLE
Can't see certain controls on HiDPI Editor

### ISSUE THREAD

**Issue by alvaromunoz** [godotengine/godot#10794]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOS Sierra
Godot 2.1.4
Macbook Pro 2015 13"

**Issue description:**
I wanted to edit a global script for my project, but since I'm using a retina screen and a HiDPI config, the options seem to be broken:
<img width="208" alt="screen shot 2017-08-30 at 21 49 22" src="https://user-images.githubusercontent.com/2722773/29901516-bbc453e6-8dce-11e7-8f86-ff5d3dfb2907.png">

Also happens with SamplePlayer2D:
<img width="308" alt="screen shot 2017-08-30 at 21 49 44" src="https://user-images.githubusercontent.com/2722773/29901469-7f14c106-8dce-11e7-81ea-269b4411d595.png">

As a temporary fix I can set the Editor DPI to LoDPI, but the font is so small it's unusable so I have to go back to HiDPI after the setting is done.

**Steps to reproduce:**
Configure HiDPI Editor:
add a global script.
Add a sound to a soundbank2d

**Link to minimal example project:**

**Comment by arthurferrai** [comment]
Just want to report that it still happens on 3.0 stable.

**Comment by alvaromunoz** [comment]
Seems to be fixed in 3.0.5
<img width="193" alt="screen shot 2018-07-10 at 20 41 08" src="https://user-images.githubusercontent.com/2722773/42544783-cdb9d1e8-8481-11e8-898d-705c1b9b265f.png">

**Comment by Calinou** [comment]
Closing, as this was reported as fixed.
