### ISSUE TITLE
Stop print annoying errors with cast_to with null

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#10797]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 with latest master branch

**Issue description:**

The red errors is full my console. I don't really  know why I cause them from the scripts.

The editor complain with my script as following code
```
if a != null:
```
I don't think this way to check an instance is null has any problem.

Maybe we should remove this from here?
https://github.com/godotengine/godot/blob/master/core/object.h#L570~L575

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/6964556/29902969-e29b5db0-8e33-11e7-8122-4b9bf3a9c959.png)

**Comment by reduz** [comment]
If i'm not mistaken, @hpvb fixed this already, right?

**Comment by hpvb** [comment]
@reduz this is correct, #10975

**Comment by volzhs** [comment]
closing as fixed by #10975
