### ISSUE TITLE
import font with custom character set do not work any more (regression in 2.1.4)

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#10808]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2.1.4 stable

**Issue description:**

it works well before the 2.1.4 stable.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
> Steps to reproduce:
> Link to minimal example project:

**Comment by alexzheng** [comment]
[Archive.zip](https://github.com/godotengine/godot/files/1266818/Archive.zip)

Import->Font->
Source Font:choose simhei.ttf 
Character Set:
Mode: Custom&Latin
Custom:choose 1.txt

That can work well on 2.1.3 and 2.1.4 beta.

**Comment by Listwon** [comment]
Tested on custom 2.1 build, Linux Mint 18.2 and it's working now.
