### ISSUE TITLE
Failure to load some png images because of bug in libpng 1.6.32

### ISSUE THREAD

**Issue by baekdahl** [godotengine/godot#10809]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux x64
Godot 2.1.4-stable (libpng 1.6.32)

**Issue description:**
The following error is reported in console.
> ERROR: _png_error_function: IDAT: chunk data is too large
>    At: drivers/png/image_loader_png.cpp:61.
> libpng error: IDAT: chunk data is too large
> ERROR: _load_image: PNG Corrupted
>    At: drivers/png/image_loader_png.cpp:93.

**Steps to reproduce:**
Include the following image in a scene:
[ChunkDataTooLarge.png.zip](https://github.com/godotengine/godot/files/1266887/ChunkDataTooLarge.png.zip)

Link to upstream bug: https://sourceforge.net/p/libpng/bugs/270/

**Comment by akien-mga** [comment]
Neat, I was looking for a good enough reason to make a 2.1.4.1 hotfix, looks like we have it :P

**Comment by eon-s** [comment]
There is a libpng 1.6.33 now that is supposed to have this fixed.

**Comment by green-coder** [comment]
I just compiled the master branch today and gave it a try. About 40% of my png files cannot be read, probably that issue.

**Comment by Listwon** [comment]
Looks like it is fixed. Tested on custom 2.1.x build. Linux Mint 18.2

**Comment by eon-s** [comment]
Yes, fixed with #12050 and may be ready for the hotfix (unless there is something important broken).
