### ISSUE TITLE
Input with IME

### ISSUE THREAD

**Issue by sdhr7314** [godotengine/godot#10805]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 ,  Godot 2.1.3

**Issue description:**

This issue is related to every kind of text input to the editor and some nodes which accept text edit at runtime, say, TextEdit LineEdit and TreeItem.
With IME, typing Japanese characters shows small popup at left top of the screen.
It's different from the behavior of usual text editor and not useful for typing CJK.

Expected :
![2017y08m31d_083010831](https://user-images.githubusercontent.com/25213070/29911506-0e481cac-8e69-11e7-8dc3-d3813356c9eb.png)

Godot :
![2017y08m31d_080128363](https://user-images.githubusercontent.com/25213070/29911491-00ebc522-8e69-11e7-8dfd-5b0651782134.png)

**Link to minimal example project:**

[IME_issue.zip](https://github.com/godotengine/godot/files/1266173/IME_issue.zip)

**Comment by Zireael07** [comment]
2.1.4 is already out, try it? With 2.1.4, I get the IME popup roughly in top middle.

**Comment by sdhr7314** [comment]
I've just tried with 2.1.4 and it's the same.

**Comment by alexzheng** [comment]
I can not input Chinese characters, is it supposed?

**Comment by bruvzg** [comment]
IME support is implemented on Linux (#9350/#9366/#9396) and macOS (#10142) for **3.0** branch, but not on Windows.

**Comment by Zireael07** [comment]
That's weird @bruvzg, I am on Windows 7 and 2.1.4 and can input Japanese characters from IME fine.

**Comment by bruvzg** [comment]
@Zireael07 input can work without IME specific code, but functions for candidate list popup position (`OS::set_ime_position`) and in-line editing (`OS::set_ime_intermediate_text_callback`) are not implemented.
