### ISSUE TITLE
ESM shadow filter bugous apperance

### ISSUE THREAD

**Issue by trsh** [godotengine/godot#1080]
Something werd with the ESM shadow filter:

Project can be downloaded here: https://drive.google.com/file/d/0BwDtvsC8_NUGN0FKbHhQcXJIcWc/view?pli=1

Select camera and press preview in bottom view.

1) First - shadows look werd.
2) Do I see a anti-shadow on the floor, under the cube?
3) Press for ex. fastly ctrl+s (save) and see the animated shadows (??)
4) Re-open the project and move the camera along the coridor - the shadows ar jiggeling and flipping.
5) Re-open the project and RUN ir - see again animated shadows
6) Re-open project and move the cube around- shadows move very werd

**Comment by akien-mga** [comment]
Can you still reproduce this issue in the current master branch?

**Comment by trsh** [comment]
yes!

**Comment by akien-mga** [comment]
What about now? :P

**Comment by trsh** [comment]
@akien-mga not working with godot currently, and won't be for a longer time. So maybe someone else can re-test.

**Comment by reduz** [comment]
No ESM in master, it was removed
