### ISSUE TITLE
LINK/UNLINK console spam with navmeshes

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#10804]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.4

**Issue description:**
When I have navmeshes in my scene, the console log gets full of LINK or UNLINK lines. Made worse by the fact that I use groups to toggle some of them on/off.

Those should be removed or at the very least tell me which navmesh (instance/polygon) they mean. Preferably removed (and optionally toggled on by visible navigation debug option, if they are expanded to actually mean something)

**Steps to reproduce:**
Slap a navmesh into your scene, run.

**Link to minimal example project:**

**Comment by Listwon** [comment]
@Zireael07 Could you please attach the minimal example project? Because I can't reproduce it following your steps.

**Comment by Zireael07** [comment]
I forgot about the fact that you need a navigation node for the navigation to actually work.

I can't make an example project but I think adding a 2nd navmesh to the 2.1. navmesh demo would be enough (I'm not sure if it happens with 1 navmesh instance only)
