### ISSUE TITLE
Nodes added via EditorPlugin should have more direct file path access

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#10800]
It seems to make more sense for nodes that are added as a new node type to have an easier way of retrieving their script resource.

Currently, if I had a node at `res://addons/my_plugin/path/to/my/node.gd`, I have to actually supply the entire path to the node in the plugin just to extend its functionality with a script (seems pretty extreme). I'm not sure how possible it would be to get syntax highlighting / compilation off of the node's name in GDScript (does adding it to the ClassDB allow for that at all?). However, even if that weren't possible, there's gotta be something we can do. Even if it's just adding a Globals method (or adding a class to the Globals) that takes a string and returns the corresponding path to the script file. Something like...?

    # Given a 'MyNode' new node type
    extends script("MyNode")
    var MyNode = preload(script("MyNode"))

**Comment by DualMatrix** [comment]
This is fixed with the introduction of class_name
