### ISSUE TITLE
Instance properties not showing up in debugging area

### ISSUE THREAD

**Issue by gitnob** [godotengine/godot#10807]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux 64bit - debian stable
Godot 2.1.4

**Issue description:**
Trying to debug with the remote inspector, the properties of the node are not been shown in the properties area of the debugger. Although a snapshot of the properties are shown in the inspector area of the editor.

This is a severe problem, because debugging with the built-in debugger is not possible anymore.

Expected: Properties showing up in the debugger area, not in the editor area, like in 2.1.3.

**Steps to reproduce:**
Only in version 2.1.4, with old projects, demo projects and new projects...

**Link to minimal example project:**
just take any project of the demo container

**Comment by RandomShaper** [comment]
What does that make impossible to use the debugger?

**Comment by Zireael07** [comment]
No, the debugger can still be used, you just have to look in a different place. 
PS. It makes the debugger panel look weird with the right side unused, though.

**Comment by gitnob** [comment]
_-> RandomShaper_
I only get snapshots of the values of the node. only when I click on it.
With the 2.1.3 debugger I could follow the actual properties while they change during game play.

It is nearly impossible now to use the debugger for example in a mouse controlled game.

**Example:** 
A spatial is controlled by mouse events in the game window. If this spatial changes it's translation value, I could only see the changing values after clicking on the instanced spatial in the debugger - first before and second after the spatial's movement. And in between I must use the mouse in the game window to let the spatial change it's value. This is more than annoying and makes it impossible for me to use the debugger in a quite fast game play to observe the changing of values.

Expected behaviour: like in 2.1.3
With 2.1.3 I could just choose the instanced spatial with the debugger and then controlled the game with the mouse while observing the properties values changing in the debugger window.

_-> Zireael07:_
Yes, the debugger can be used with above mentioned restrictions, but is totally unpractical compared to 2.1.3, for watching changing values.
And on top of it it's totally weired to observe the same area, where you normally change the initial values of the node properties.

I don't know why this behaviour was changed.... :-(

**Suggestions:**
1. IMO, the properties view should go back into the debugger area (two panel window). 
2. The old 2.1.3 behaviour of continous observing properties instead of only getting snapshot values of the properties should be reimplemented. 

Meanwhile - unfortunately - I am not able to use 2.1.4 debugger, sniff, and must thus stay with 2.1.3.

**Comment by akien-mga** [comment]
CC @Geequlim

**Comment by Geequlim** [comment]
> This is a severe problem, because debugging with the built-in debugger is not possible anymore.

@gitnob  I don't really understand all of the probems with you.

The properties of instance now is updated after we click it from the debug client
This problem should be related to #10044 and #10030

**Comment by Geequlim** [comment]
@gitnob Could you give me an example project?
The properties updated fine with my project in the inspector.

**Comment by Geequlim** [comment]
Here is a gif with my game
![474b49d8-c6b2-4bee-87ba-3bc4a6ab7a34](https://user-images.githubusercontent.com/6964556/29928771-4987d95a-8e9c-11e7-8123-40c26bdb66a4.gif)

**Comment by jandrewlong** [comment]
In 2.1.3, it was possible to change values in the Properties pane of the Remote Inspector tab, and they would change in the running game.

In 2.1.4, when I click on a node in the Live Scene Tree, it shows a ScriptEditorDebuggerInspectedObject in the Inspector, but changing value there are not reflected in the running game.

**Comment by gitnob** [comment]
-> Geequlim:
>>The old 2.1.3 behaviour of continous observing properties instead of only getting snapshot values
>> of the properties should be reimplemented.
>This would be reimplemented :)
Does this mean, there is a problem of continous update???

Definitely it's not working on my system. No continous observable changing of values without clicking again and again and again.

I've attached a file: just run the "game" and debug on Spatial. On my system no continous rise of the value in counter property without clicking!
[debuggertest.zip](https://github.com/godotengine/godot/files/1267563/debuggertest.zip)

And second question:
> How about just remove the right panel in the debugger?
One (GUI design)
IMO, the debugger "inspector" should be a separate window from the editor's "inspector" belonging to the debugger. Thus in the visible area of the debugger. What is the reason for using the editor's insepctor for both - the debugger and the editor.
Although they have the same name, they have different tasks and should though be represented within different panels.

Two (usability)
2.1.3: While a user starts debugging and observing the values and seeing some problems, he/she could adjust the initial values of the properties in the editor's inspector, while on the same time still debugging the game.
2.1.4: If I want to adjust the wrong initial parameter, I must remember the parameter's location, must switch to the editor's parameter panel, change the initial parameter, switching back to the debugging parameter, .... only because there are no more two inspector panels visible during debugging.
This is annoying and IMO is a decline in usability and rapid development possibility.

**Suggestion and wish:**
If it is necessary to have the debugger's inspector panel "outside" the debugger area, please make it possible to have TWO panels (ediotr inspector AND debugger inspector) which could be placed anywhere the user likes, like with other panels.

**Comment by Geequlim** [comment]
Maybe you don’t use the breakpoint and expore stack data quit often. It is
really bad to switch debugger tabs to browse objects in the breakpoint
stack.

2017年8月31日 23:41，"gitnob" <notifications@github.com>写道：

**Comment by Geequlim** [comment]
Please reopen this issue as a bug related is not fixed yet.

**Comment by akien-mga** [comment]
It's still open :)

**Comment by gitnob** [comment]
-> Geequlim
I understand what your problem while breakpoint debugging is. It's related to the GUI.
Anyway, I think editor's property panel and debugger's property channel should be two different panels.
And as I said. Maybe, it could be implement as another free placable panel in the editor's area, like node panel, inspector panel, scene panel, etc.

But the continous update of the debugger properties is another issue.

BTW, occasionally I closed the bug, but 2 seconds later re-opened it. Sorry for that.

**Comment by Geequlim** [comment]
@gitnob 
> Anyway, I think editor's property panel and debugger's property channel should be two different panels.

I don't think the debugger property panel should be sepatrated with normal property panel as following reason:

1. It is not convinient to explore instance data in the breakpoint stack while debugging to switch debugger tabs again and again.
2. With new debugger all kind of vairable in the stack or scene tree can be explored including nodes, arrays, dictionarys, script instances. So the inspector is the proper place to show all kind of the data as it does with arrays before.
3. The inspector has implemented some functionalities like `go next` and `go back` that is really useful for exploring complex data. But the origin debugger property panel didn't  provide such things.

> Maybe, it could be implement as another free placable panel in the editor's area, like node panel, inspector panel, scene panel, etc.

Yes but the godot editor seem has few space to add such panel and there are too much works to do with that. Maybe we could try that with 3.0 instead of too much work with 2.1.

BTW, Unity use their inspector to show properties of game objects when debugging game.

The continous update of the debugger properties will be fixed in this weekend.

**Comment by gitnob** [comment]
thanks Geequlim for taking your time to answer,

ad 1.) agree
ad 2.) agree
ad 3.) agree

Maybe the headline was a little bit missleading, because actually it was two issues - continous update and panel location.

>BTW, Unity use their inspector to show properties of game objects when debugging game.

This is not an argument in respect to a free world of thinking :-)  And.... Unity is not running on Linux...

> The continous update of the debugger properties will be fixed in this weekend.

Yepeah... will it be in the prospected 2.1.5 or will there be another 2.1.4b, like with Blender releases sometimes?

**Comment by akien-mga** [comment]
There will soon be a 2.1.4.1 release due to a bug in libpng, so I'll make sure to include any improvement to the workflow in it.

**Comment by Zireael07** [comment]
Speaking of debuggers, I noticed that in all Godot versions (2.1.3, 2.1.4., 3.0 alpha 1) there is a lag of several seconds (with increased CPU usage) before I can actually see the properties of the node I clicked on. Other editors, such as Unity, have no such lag. Are we serializing the data only when clicked or what?

**Comment by gitnob** [comment]
@akien-mga

improvements to the workflow?? Would this be another discussion thread, like:
"suggested improvements for the debugger".
So everybody can take part in that?

And close the discussion/issue about "panel location" and "continous update" now?

**Comment by akien-mga** [comment]
Why close it? I thought @Geequlim wanted to make improvements?

**Comment by Geequlim** [comment]
@jandrewlong  It should work again with #10891
![peek 2017-09-02 23-48](https://user-images.githubusercontent.com/6964556/29996877-797a284a-9039-11e7-92a7-8366f807fafe.gif)

**Comment by lmjk** [comment]
Is this one fixed or not? If it is, could anyone give advice how one can obtain the fixed 2.1.4 source in git and not the latest 3.0+?

That is, I believe I am experiencing the exact same bug in Linux system in Godot 2.1.4 (and not in 2.1.2 which I happened to have lying around on my disk).

Remote Inspector does not show anything in Remote Object Properties list when clicking on nodes. However, the regular Inspector will show *non-updating* properties (except for flashing very quickly a few times). Curiously, the clicked node in the Live Scene Tree also gets highlighted only temporarily, for a duration less than a second. 

![godot_2 1 2_ri](https://user-images.githubusercontent.com/25223253/34014365-8d6b07e4-e123-11e7-9407-688fa854b7fc.png)

![godot_2 1 4_ri](https://user-images.githubusercontent.com/25223253/34014416-b69a21e0-e123-11e7-9351-59e5d9c4c4bd.png)

**Comment by Geequlim** [comment]
You can get the latest code from the 2.1 branch.
Remote Object Properties are shown in the inspector now.

**Comment by lmjk** [comment]
Ok, thanks for clarification!

**Comment by bojidar-bg** [comment]
Is this still an issue in 3.0/3.1?

**Comment by gitnob** [comment]
I'm using 3.0.6 and here you can see updating properties. Works good in my cases.
So for me this issue isn't there anymore in 3.0.
For me it's fixed and I can close it.
