### ISSUE TITLE
Incomplete "for" loop does not trigger compilation error

### ISSUE THREAD

**Issue by Murii** [godotengine/godot#1081]
To understand better the problem i`ll show you two images.

![image](https://cloud.githubusercontent.com/assets/7363306/5587657/100f6cbc-90fa-11e4-90fa-2c821e83b3c7.png)

This is what I get when i run the game.The cannon in the left should be moving but since the for loop is not finised or whatever it wont move.The interesting fact is that I can move the player and collect the gem.

![image](https://cloud.githubusercontent.com/assets/7363306/5587668/66d56d76-90fa-11e4-813c-48452be7ea62.png)

**Comment by Murii** [comment]
@Juan any ideas how to fix this?

**Comment by akien-mga** [comment]
Hi @Murii and sorry for the delay. Are you still able to reproduce this bug in the current master branch?

**Comment by vnen** [comment]
This is likely related to #2570.

**Comment by Murii** [comment]
@akien-mga The issue is related to what @vnen said. I identificated this problem a long time ago and tried to fix it, I even sent a commit for it but that was some time ago...

**Comment by Murii** [comment]
If I remember correctly before a statement the compiler does not check if there's actually something to execute that's why it lets you do all kind of crazy stuff. Basically I forced the compiler to throw an error if there's nothing to execute but this did not allow to have code like this: 
if something: 
 //comment
 x += x; 
so you were forced to do instead:
if something: //comment
  x+=x;

**Comment by vnen** [comment]
This is already fixed.
