### ISSUE TITLE
3.0 Shader Language: render_mode specular_* all look the same

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10813]
windows, 8ed1a28, nvidia (i doubt that it is driver related tho)

IDK, may be they aren't implemented yet, but may be it is also a bug.

**Comment by akien-mga** [comment]
Please follow the issue template.

**Comment by curly-brace** [comment]
well. it does not look like a driver issue.

**Comment by akien-mga** [comment]
> well. it does not look like a driver issue.

Maybe you can let developers judge that. :)

**Comment by reduz** [comment]
this is properly implemented now, closing.
