### ISSUE TITLE
3.0 Shader Language: render_mode diffuse_burley is broken

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10812]
windows, 8ed1a28, nvidia (i doubt that it is driver related tho)
(two screens below)
![img1](https://www.dropbox.com/s/67sue3pj54qbmp6/burley1.png?raw=1)

![img2](https://www.dropbox.com/s/cgn28slkjbmccu8/burley2.png?raw=1)

**Comment by akien-mga** [comment]
How is that part of the issue template not relevant enough for you to keep it?

> **Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Comment by reduz** [comment]
Oh, this was fixed by tagcup some weeks ago, closing.
