### ISSUE TITLE
Chinese characters can not typed in any editable text field

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#10810]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OS:Mac OS
Godot: 2.X and 3.X

**Issue description:**

**Steps to reproduce:**
add A Label
Change the input source to Pinyin-Simplified
Chinese characters can't typed into the Text property box.

**Link to minimal example project:**

**Comment by Chaosus** [comment]
Godot default font does not support non-latin letters. It sounds like #6404 but im not sure

**Comment by dingdalong** [comment]
OS: windows10
Godot: 3.1.stable

![QQ截图20190427145809](https://user-images.githubusercontent.com/6268385/56846220-3a905f00-68ff-11e9-9290-53e981abfcf5.png)
Editor and script can show and input chinese characters, but label cannot.

@akien-mga

**Comment by Calinou** [comment]
@dingdalong This is because the default *project* font doesn't contain CJK characters. Try loading one of the [Noto fonts](https://www.google.com/get/noto/) as a DynamicFont in your project, and specify it as the default font of the root Control node's Theme resource.

**Comment by ryancheung** [comment]
This is absolutely not a bug. Godot TextEdit works with CJK characters 100% sure. If you haven't see any CJK characters, just set a CJK font to custom font property. 

Please close this issue. It's not an issue.

**Comment by Calinou** [comment]
I'll close this issue then. I still think we should find a way to document this better (or make missing characters more obvious), but I remember seeing other issues about that.
