### ISSUE TITLE
Regression: Crash when importing textures

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#10815]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux, Godot 3 master  https://github.com/godotengine/godot/commit/caf1447befba37e87bfef31192b98b9fbe2306b1

compiled with gcc 7.2.0

**Issue description:**
As of the latest commits, Godot crashes when (re-)importing any graphic (tested with png and svg). This issue was not present with any of the builds I did yesterday. 

```
REIMPORT: file was not found before, reimport
at dir: res:// file: evil_godot.png
0: class.gd
1: default_env.tres
2: icon.png
3: room.obj
4: test.tscn
5: test.vs
REIMPORTING: res://evil_godot.png
WARNING: not found: importer_defaults/texture
ERROR: operator[]: FATAL: Condition ' !e ' is true.
   At: core/map.h:604.
```

**Comment by hurikhan** [comment]
I also just stumbled across this issue.
On my side it has happened after creating a new project.
```
...
REIMPORTING: res://icon.png
WARNING: not found: importer_defaults/texture
ERROR: operator[]: FATAL: Condition ' !e ' is true.
   At: core/map.h:604.
```
After reverting c8448cb0ac7ca6562e2fc539ee2f791ccd3547c6 it works for me.

**Comment by akien-mga** [comment]
@toger5

**Comment by toger5** [comment]
I think I found the issue.

It is caused by the importer looking at the wrong path to each for scale (since it's now svgs/scale)

**Comment by rosshadden** [comment]
I had the issue, but in trying to `git bisect` to find the culprit commit, I found that the issue went away when rebuilding.  Even the same version that initially had the issue.

**Comment by akien-mga** [comment]
Yes it was fixed one hour ago by #10824 :)

**Comment by novemberist** [comment]
I'm not sure if this is related or possibly a new issue, but when I try to import svgs with mipmaps enabled, I get the following output in the console:

```
to gen mipmaps w 349 h 665 format RGBA8 mipmaps 9 new size is: 1235952
libpng warning: Image width is zero in IHDR
libpng error: Invalid IHDR data
ERROR: _lossless_pack_png: Method/Function Failed, returning: PoolVector<uint8_t>()
   At: drivers/png/image_loader_png.cpp:311.
success
ERROR: _lossless_unpack_png: Condition ' len < 4 ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:259.
ERROR: _load_data: Condition ' img.is_null() || img->empty() ' is true. returned: ERR_FILE_CORRUPT
   At: scene/resources/texture.cpp:526.
```

The game window closes immediately, when I try to run the project after this. Should I open a new issue for this?

**Comment by akien-mga** [comment]
Yes, please open a new issue.
