### ISSUE TITLE
Crash when selecting New DynamicFontData and disabling Use Mipmaps

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#10839]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7, Godot 3.0

**Issue description:**

Godot crashed when I tried to set up a custom font and testing some options (Mipmaps, Filter).

**Steps to reproduce:**
Make a Button -> Custom Fonts -> New DynamicFont -> New DynamicFontData.
Settings -> Enable and then disable Use Mipmaps.

**Link to minimal example project:**

**Comment by reduz** [comment]
@volzhs I remember you were working on this stuff (if I am right), would appreciate if you can take a look

**Comment by volzhs** [comment]
well... I have no remembered or idea about this.

**Comment by hpvb** [comment]
I can't reproduce this on current master. Does this still happen for you @Boothand?

**Comment by Boothand** [comment]
Sorry, can't look into building from current master just these days, as I have limited time and a veery old PC and slow internet (for getting VS community etc). Could always test given a build though.

**Comment by akien-mga** [comment]
@Calinou makes almost daily builds of the editor for all platforms: https://bintray.com/calinou/godot/editor/_latestVersion#files

**Comment by Boothand** [comment]
OK, can't reproduce either on Godot-Windows-x86_64-2017-09-12.ed531d5.

**Comment by akien-mga** [comment]
It was likely due to another bug and was fixed since then.
