### ISSUE TITLE
Alignment issues caused by new font (and something else...)

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#10833]
<img width="229" alt="screen shot 2017-08-31 at 20 49 30" src="https://user-images.githubusercontent.com/16718859/29939949-efcb86a4-8e8d-11e7-9f74-cf04db6b6518.png">
<img width="233" alt="screen shot 2017-08-31 at 20 49 35" src="https://user-images.githubusercontent.com/16718859/29939951-f008d108-8e8d-11e7-983b-08b775fc7a0f.png">
<img width="235" alt="screen shot 2017-08-31 at 20 49 41" src="https://user-images.githubusercontent.com/16718859/29939952-f009f510-8e8d-11e7-9a7b-4a3263bedc0e.png">

 - [ ] the labels are too close to the bottom.
 - [ ] the search icon is misaligned (@djrm volunteered to fix it (+1) )

**Comment by djrm** [comment]
@toger5 can this be closed now?

**Comment by akien-mga** [comment]
Yeah those are fixed AFAICT.
