### ISSUE TITLE
Color.to_html() Produces odd results.

### ISSUE THREAD

**Issue by saarantras** [godotengine/godot#10843]
Any RGB value >0 turns into FF. So for example `Color(255,100,0).to_html()` produces `ffffff00`.

I'm pretty sure the problem is in `String _to_hex(float p_val)` in `core/color.cpp`. I'd mess with it myself, but I can't get godot to compile :(

Tested in 2.1.4 x64, Ubuntu Linux

**Comment by Noshyaar** [comment]
Color needs args in 0 to 1 range.

**Comment by saarantras** [comment]
Oh oops!
