### ISSUE TITLE
2D selection box not being draw correctly when not dragging toward right/bottom

### ISSUE THREAD

**Issue by groud** [godotengine/godot#10849]
Spot on godot facebook page. Master branch.

I can handle this in #10437, as I am still working on the canvas_editor_plugin.

*Bugsquad edit:* GIF from @tuga3d 

![godot-issue](https://user-images.githubusercontent.com/410751/29983725-1a940cfa-8f4f-11e7-908e-f670fd668227.gif)

**Comment by akien-mga** [comment]
This is a recent regression btw, I can't reproduce it on 1894157.

**Comment by groud** [comment]
Seems like it comes from the gles3 rasterizer. I haven't found any other places where the bug vcould be.

**Comment by groud** [comment]
LOL. Might have found something:
![2017-09-02-112119_813x288_scrot](https://user-images.githubusercontent.com/6093119/29994498-ec0d8456-8fd0-11e7-9e24-d42b8c2e1b0c.png)
@bojidar-bg ?

**Comment by groud** [comment]
Ok. I've just checked, this is definitely a regression from #10417

**Comment by mrcdk** [comment]
Probably related issue. It's just the normal mouse selection rect.

![https://i.imgur.com/F0bDqot.gif](https://i.imgur.com/F0bDqot.gif)

**Comment by bojidar-bg** [comment]
Ah, reduz said it was good to encode it as negative dst_rect. Sorry for the bug.
