### ISSUE TITLE
Poor editor font rendering when using MiDPI scaling

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#10847]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):** Windows 10, Godot Git https://github.com/godotengine/godot/commit/a717083235b3369aef9a3846b5071fac023a60b2, NVIDIA

**Issue description:** Font rendering is poor-looking when using the MiDPI editor scaling setting. Note that this only happens on some texts, but not all.

![godot_midpi_font_rendering](https://user-images.githubusercontent.com/180032/29958782-bc5d46ba-8ef4-11e7-9c16-bf51c7be8686.png)

**Steps to reproduce:** Set the editor scaling to MiDPI, then restart the editor. This issue also is visible in the project manager.

**Comment by volzhs** [comment]
tested with MiDPI

![image](https://user-images.githubusercontent.com/8281454/29961341-507333c4-8f3a-11e7-8086-6e02c5864960.png)

**Comment by reduz** [comment]
this may be more related to allowing floating point values as control positions.. I don't really see how to fix this, so it may probably be better to re-add this constraint somehow..
