### ISSUE TITLE
Deleting export preset clears a name of an item below

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#10842]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot master branch 77ec304

**Issue description:**

Deleting an export preset clears a name of an item below. Just the next one. Not above. Not further below. Probably other settings stay, just the name that is cleared.
It's a very old issue (earlier than May 2017) but I can't find any reports.

**Steps to reproduce:**
1. Create two export presets of any platforms.
2. Delete the one above.
3. Notice that another one has a blank name.

**Comment by Kibouo** [comment]
Issue can be closed.

**Comment by Noshyaar** [comment]
Fixed by #10842

Note: if you put "Fixes #xxxx" or "Closes #xxxx" before merging, it will close that issue automatically.
