### ISSUE TITLE
'Condition '!monitoring ' is true.returned: Array()' in Godot_v2.1.4-stable_win64 crashes program

### ISSUE THREAD

**Issue by Troutpack** [godotengine/godot#10852]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 Home Premium 64, Godot_v2.1.4-stable_win64, GeForce GTX 970, driver version 10.18.13.5362

**Issue description:**
When testing shooting mechanic (instancing child scenes of bullets and shell casing objects) in game, debug screen is filled with errors of type 'Condition '!monitoring ' is true.returned: Array()' and game slows down considerably from 60 FPS to single-digit FPS in a matter of seconds and keeps slowing down even when new instances are no longer created. When the process is stopped, Godot is also sluggish and slow. No such issues in Godot_v2.1.3-rc1_win64.

**Steps to reproduce:**
Unknown. Probably linked to instancing of child scenes and collision detection. Attempts to replicate problem in simpler test project with similar script and scene setup did not work. 

**Link to minimal example project:**

**Comment by akien-mga** [comment]
CC @RandomShaper.

As debugged by @MarianoGnu on Facebook:

> for what i can read in the error log, you are trying to get an array of objects colliding with another object, but this one is not checking for collisions (monitoring) you should neighter enable monitoring or check if monitoring depending of what you need.

And indeed enabling contact monitoring fixed @Troutpack's issue.

Still, we should show a helpful warning or error. I guess the crash is due to an infinite loop, so I don't think we can prevent it as it's a user logic bug, but we should make it easier to understand.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
