### ISSUE TITLE
Failure to deploy .appx to Windows 10 Mobile

### ISSUE THREAD

**Issue by 648trindade** [godotengine/godot#10857]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
PC OS: Debian Buster
Godot version: 2.1.4
Phone: Microsoft Lumia 532
Phone OS: Windows 10 Mobile Build 10.0.14393.1066

**Issue description:**
When deploying .appx generated by export tool, Get the following failure:
_Failure reason: Failed to start deployment. Failure text: No signature was present in the subject.
 (0x800b0100)_
![Imgur](http://i.imgur.com/BqGTr6U.png)

**Steps to reproduce:**
1. Export > Windows Universal > Export...
2. Go to Device Portal on PC browser (hosted from phone) > Apps > Install App
3. Select .appx App package and click on 'Go'

I tried some things:
* change apps storage location to internal memory (it was first on SD Card)
* placed my _Windows Phone Publisher ID_ on 'Publisher Guid' field, placed a random guid on 'Product Guid' field (generated with some guid generator) and placed my _Window Publisher ID_ with "CN=" prefix on 'Publisher' field

**Comment by vnen** [comment]
You need to create a signing certificate and then sign your package (check the [documentation](http://docs.godotengine.org/en/stable/learning/workflow/export/exporting_for_uwp.html#creating-a-signing-certificate)). For now Godot is not able to do it in the exporter, so you have to do it manually.

**Comment by akien-mga** [comment]
Fixed by #15342.
