### ISSUE TITLE
Addon system - ability to load an instanced scene as a custom type or have a custom type with children nodes that are exposed to editor

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#10855]
Either I am doing something wrong or it seems not possible to do.

The goal is to create a custom type game object addon that consists of a node that contains a number of children nodes that are all exposed to the editor

I know I can make children nodes via the runtime, but that happens only while the game is running. I want to have these children nodes be created and available in the editor when the custom type is added to the scene

Is there a way to do this in godot? If so I can't seem to find any examples or documentation on how to do it

**Comment by vnen** [comment]
Related to #3895

**Comment by Zylann** [comment]
@blurymind workaround is to set the owner of the child nodes to be the edited scene, then they will appear in the editor.

I would use normal scenes for this tbh, not sure what is the point of having a custom way of doing what a scene already does in the first place. It's like defining new nodes that always have children, there can be a lot of ways to break this as well.

**Comment by blurymind** [comment]
I came up with a hacky setget solution :) 

I guess I want to save a few steps of creating the child nodes for the user

```
extends KinematicBody2D
tool

export (bool) var enable = false setget initialize
func initialize(value):
	if get_tree().is_editor_hint():
		if value == true:
			if get_child_count() == 0: # initialize helper nodes
				var root =  get_tree().get_edited_scene_root()
				
				var SpriteNode = Sprite.new()
				add_child(SpriteNode)
				SpriteNode.set_owner(root)

		else: print("behavior disabled")
	enable = value
```
This will add a tick box to enable the behavior. If the user hasn't added any custom children to it, my code will do that for him/her. So the option is there to be custom, but you can also have my addon do the work

**Comment by Zylann** [comment]
Beware, as I said it can be broken in multiple ways, what if the user adds unrelated children to the nodes you add dynamically? What if the user decides to delete these nodes?

**Comment by blurymind** [comment]
@Zylann  yes I know =) thats why I exposed all the resource variables in the addon's master script like this:

```
export var animationNodePath = NodePath()
onready var animationNode = get_node(animationNodePath)
export var idleAnimation = "idle"
export var idleWaitAnimation = "idleWait"
export var walkAnimation = "walk"
export var jumpUpAnimation = "jumpUp"
export var jumpDownAnimation = "jumpDown"
```

If the user deletes these nodes, they will also disappear from the exposed variables. The user will then get a message that the nodes are missing and need to be set.

If the user adds new children, it wont affect it, unless they rename the current nodes - at which point they will have to reconnect the nodes via the exposed nodepaths in the editor.

A nice side effect to this init method is that the user can go custom, but can also go automagic. Because the addon is not enabled when added to the scene, the user can take the manual root before enabling it. If they enable it before adding any children,the script will do some of the work and create the nodes.
If they want to reset the behavior, they can delete all of it's children and re-enable it

**Comment by Calinou** [comment]
Closing due to lack of support. If you still have a need for this, please open a proposal on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository.
