### ISSUE TITLE
Cannot set a DynamicFont as the editor or script editor font

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#10866]
The editor and script editor font settings (eg. **Editor Settings → Interface → Custom Font**) expect a file with a `.font` extension (probably a BitMapFont). If you display all files and select a `.ttf` or `.otf` font file (DynamicFont), it will not be used, even after restarting the editor.

**Comment by Geequlim** [comment]
So how can I make a `.font` ? The default font of editor in 3.0 kill my eyes so long!

**Comment by Zylann** [comment]
How were these fonts even made or changed several times then? There must be a way xD While waiting for proper easy to use way

**Comment by Zylann** [comment]
Ok, just to test I added the "*.tres" extension to the editor setting, and surprisingly, it worked!

I am now using Consolas, without modifying the engine:
![image](https://user-images.githubusercontent.com/1311555/30773712-71a166d6-a076-11e7-9001-a065b8a501f8.png)
