### ISSUE TITLE
get_tree().set_debug_collisions_hint(true) doesn't work in tool mode

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#10867]
When using the get_tree().set_debug_collisions_hint(true) function in tool mode, nothing happens.

Example:
```
tool
export (bool) var Enabled = false setget initialize
func initialize(value):
	Enabled = value
	if get_tree().is_editor_hint():
		if value == true:
			get_tree().set_debug_collisions_hint(true)
```
Enable the exposed variable from above in the editor,
then check debug options in the editor - the collision hint is not enabled

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by Calinou** [comment]
Closing due to lack of response (see Akien's comment above). Please comment if you can still reproduce this issue.
