### ISSUE TITLE
camera smoothing choppy when following player

### ISSUE THREAD

**Issue by rayosdev** [godotengine/godot#10878]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows 10, Godot 2.1.4, Intel(R) Celeron(R) N2940, 

**Issue description:**

Camera is child of player and smoothing is on, when moving player the movement seams choppy or jittery, swing back an forth while moving in intended direction.

**Steps to reproduce:**
move player while camera is attached as child and enable smoothing (tested with speed on 5)

**Link to minimal example project:**

example project
https://filebin.ca/3Yy9thBGbvVc/camrea_follow_test-bugversion.tscn

example workaround using lerp:
https://filebin.ca/3Yy0y8IejjmJ/camrea_follow_test.tscn

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by DualMatrix** [comment]
Seems to work fine in master
