### ISSUE TITLE
Script Editor top menu is thicker than the 2D/3D ones

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10876]
**Ubuntu 17.04, Godot Build: 8ed1a28**

**Issue description:**
The Script Editor top menu is unnecessarily thicker than it needs to be in comparison with the 2D/3D ones.

![screenshot at 2017-09-01 20-22-31](https://user-images.githubusercontent.com/30739239/29990835-da7fe2d2-8f54-11e7-97b2-de9555c3f7fc.png)

**Comment by akien-mga** [comment]
Could be due to recent the font change.

**Comment by YeldhamDev** [comment]
I remember it being that way before the font change.

**Comment by volzhs** [comment]
I confirmed it's still thicker 0b8fa1e01068af9924742ade2625e021ccd2c5a8
