### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by Brickcaster** [godotengine/godot#10873]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows, Godot 2.1.4

**Issue description:**
Godot does not render many emojis.  I attempted to use a RichTextLabel containing the text:

`te😊x🌐t🔼ᴥ♻🚀❂☮☯🚀🎡🚢🍭💦🔻`

And instead what renders is:

![image](https://user-images.githubusercontent.com/13324089/29986552-e950dbea-8f31-11e7-9578-4da28913e3ba.png)

I did this using a dynamic font for the node and I tried loading EmojiOneColor-SVGinOT.ttf, OpenSansEmoji.ttf, and unifont-10.0.06.ttf all with very limited success.  The EmojiOneColor comes with a demo which, when opened in Chrome, renders just fine in B&W including many of the symbols I'm looking to use.  Finding an adequate demo of the other fonts is a bit more difficult than I imagined.

**Comment by eon-s** [comment]
Maybe duplicated of #6834 , 3 have better support of fonts with special characters.

**Comment by curly-brace** [comment]
allow using them in code editor too like variables 🔨

**Comment by eon-s** [comment]
@curly-brace well, if you manage to get a font with emoji in the format supported by the editor it should be possible (settings uses a `.font`, I have no idea what is that).

**Comment by akien-mga** [comment]
You can now use any TTF font in the editor itself (code editor included) and in games, so this should work fine.

If a TTF font contains glyphs and Godot doesn't render them, that needs to be investigated.

**Comment by Calinou** [comment]
> You can now use any TTF font in the editor itself (code editor included) and in games, so this should work fine.

Note that colored fonts aren't currently supported, though (most Emoji fonts make use of colors).

**Comment by eon-s** [comment]
Is working in editor, labels, node names, gdscript, debugger, terminal output.

Tested with https://github.com/eosrei/twemoji-color-font (of course, color does not work).

**Comment by reduz** [comment]
I did not even know color fonts existed, I suppose we could detect this
somehow and render to color?

**Comment by volzhs** [comment]
I'm trying on this.
I don't know why but it works only with Google Noto Emoji font... :cry: 

![screenshot from 2018-01-16 09-43-34](https://user-images.githubusercontent.com/8281454/34966795-d05abee0-faa1-11e7-8648-bbf41bf5a0f0.png)

**Comment by reduz** [comment]
I'm amazed, how are you detecting that the font needs to use a RGB texture
and raster to it?

**Comment by volzhs** [comment]
detecting color
```cpp
bool has_color = FT_HAS_COLOR(face);
int error = FT_Load_Char(face, p_char, has_color ? FT_LOAD_COLOR : FT_LOAD_DEFAULT);
```

to raster
```cpp
case FT_PIXEL_MODE_BGRA:
	wr[ofs + 2] = slot->bitmap.buffer[i * slot->bitmap.pitch + (j << 2) + 0];
	wr[ofs + 1] = slot->bitmap.buffer[i * slot->bitmap.pitch + (j << 2) + 1];
	wr[ofs + 0] = slot->bitmap.buffer[i * slot->bitmap.pitch + (j << 2) + 2];
	wr[ofs + 3] = slot->bitmap.buffer[i * slot->bitmap.pitch + (j << 2) + 3];
	break;
```

need to take care of `DynamicFontAtSize::textures` though...

**Comment by volzhs** [comment]
I'm not sure that fonts downloaded from internet is really colored font beside google noto color emoji...
or I missed something to do with freetype to render rest colored fonts.

**Comment by reduz** [comment]
ah yeah, you need to find out if at least one of the chars uses color so
you create a color texture... either that or use a separate texture for
chars with colors, not sure.

**Comment by volzhs** [comment]
yeah. i've done that too so far.
problem is checking and loading colored font correctly.

**Comment by volzhs** [comment]
![screenshot from 2018-01-16 11-45-06](https://user-images.githubusercontent.com/8281454/34969574-c15cc33c-fab2-11e7-9b1c-507786374f9a.png)

as my research, freetype supports only CBDT format color font which Google supports also.
if font is CBDT format, it works fine.
now need to handle size of font rendering.

**Comment by volzhs** [comment]
![screenshot from 2018-01-16 15-56-04](https://user-images.githubusercontent.com/8281454/34975585-d80b27ae-fad5-11e7-83e7-b12172d8f5ea.png)
:sunglasses: finally....
need to clean up codes, but also need to go to bed...
will make a PR, maybe tomorrow
