### ISSUE TITLE
Scroll bar jitters when scrolling up in the script editor

### ISSUE THREAD

**Issue by Smellyhobo101** [godotengine/godot#10881]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win7,  [Godot-Windows-x86_64-2017-08-31.f9eec5c](https://bintray.com/calinou/godot/editor/2017-08-31.f9eec5c#files). Doesn't occur on the official godot 3 alpha 1 build.

**Issue description:**

[Video](https://streamable.com/jf7ha) 

When scrolling up in the script editor, the scroll bar will flicker up and down. This only happens when scrolling up. Scrolling down is completely smooth. 

I don't have this issue anywhere else so I don't think it's a problem with my mouse.

**Comment by Paulb23** [comment]
Don't worry it's not your mouse! This was also spotted by @Zylann in #10489
