### ISSUE TITLE
node.remove_and_skip() stops process without any error

### ISSUE THREAD

**Issue by maxim-sheronov** [godotengine/godot#10886]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch linux; Godot 3.0 master branch

**Issue description:**
I am trying to remove rigid body when it collides with other.
It stops the process if I use node.free() or node.remove_and_skip() or node.get_parent().remove_child(node)
I understand, that I should use node.queue_free(), but process should not stops without any error. But it does.

When I tried to debug process, I found an issue:
in file space_2d_sw.cpp (I added comments on lines):

	void Space2DSW::call_queries() {
		while (state_query_list.first()) {

			Body2DSW *b = state_query_list.first()->self();
			b->call_queries(); // as I understand from this callback body will be freed
			state_query_list.remove(state_query_list.first()); // and here state_query_list.first() is null and it fails in remove() method
		}

		while (monitor_query_list.first()) {

			Area2DSW *a = monitor_query_list.first()->self();
			a->call_queries();
			monitor_query_list.remove(monitor_query_list.first());
		}
	}

I think, that it is better to store state_query_list.first() in variable to remove it correctly after b->call_queries()

And other problem, that process stops without any error. So it was pretty hard to find root of the problem. So maybe it should write an error to the output.

**Example project:**
[bug_example.zip](https://github.com/godotengine/godot/files/1272126/bug_example.zip)

**Comment by RandomShaper** [comment]
Confirmed.

But I think the fix would be just to swap the two lower lines in the loop:

```
	while (state_query_list.first()) {

		Body2DSW *b = state_query_list.first()->self();
		state_query_list.remove(state_query_list.first());
		b->call_queries();
	}
```

Of course, it would be nice to do it for other similar loops and for 2.1 as well.

**Comment by RandomShaper** [comment]
And adding a comment about these subtleties for future maintainers.

**Comment by maxim-sheronov** [comment]
@RandomShaper this solution can be wrong. Because when you get signal, your rigidbody will be removed from the list. And maybe this can involve some undesirable consequences. And maybe not.

Other problem. and this was mentioned, that engine does not write error log for Segmentation fault exception. I don't know if it possible to fix this.

**Comment by RandomShaper** [comment]
As far as I can see, the problem with the current code is that the call to `remove()` assumes there's at least one element in the list and, moreover, that such item is the same just fetched. That is wrong because if the body is destroyed during `call_queries()`, it will be removed from the list and the next call to `first()` will be unreliable either because there are no more entries or because it will return an entry for another body and that one will get removed instead.

I think my approach, by removing before doing the queries, is free from the pointed problems.

If you still think I'm wrong, please elaborate so I can get your point.

**Comment by maxim-sheronov** [comment]
@RandomShaper it was just suppose, that something bad can happen.

**Comment by reduz** [comment]
Did what @RandomShaper suggested and it seems to work fine
