### ISSUE TITLE
DocData / MethodInfo issues

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#10884]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Any OS, master branch (4d580d76)

**Issue description:**
There are several issues left with the new DocData / MethodInfo which are visible in the diff of my recent doctool sync, 4d580d76.
Complete diff (850 KB): [godot-classref-diff.txt](https://github.com/godotengine/godot/files/1272066/godot-classref-diff.txt)

- [x] `DEFVAL` arguments are still incorrectly registered, see e.g.:
```diff
                <method name="draw_polygon">
+                       <return type="void">
+                       </return>
                        <argument index="0" name="points" type="PoolVector2Array">
                        </argument>
                        <argument index="1" name="colors" type="PoolColorArray">
                        </argument>
-                       <argument index="2" name="uvs" type="PoolVector2Array" default="PoolVector2Array([])">
+                       <argument index="2" name="uvs" type="PoolVector2Array" default="null">
+                       </argument>
+                       <argument index="3" name="texture" type="Texture" default="PoolVector2Array(  )">
                        </argument>
-                       <argument index="3" name="texture" type="Texture" default="NULL">
+                       <argument index="4" name="normal_map" type="Texture" default="null">
                        </argument>
-                       <argument index="4" name="normal_map" type="Texture" default="NULL">
+                       <argument index="5" name="antialiased" type="bool" default="null">
                        </argument>
                        <description>
-                               Draw a polygon of any amount of points, convex or concave.
                        </description>
                </method>
```

- [x] Related, many default arguments for `String`, `int` or `bool` end up as `null` instead of `""`, `true`/`false` or a number:
```diff
-                       <argument index="3" name="body" type="String" default="&quot;&quot;">
+                       <argument index="3" name="body" type="String" default="null">
[...]
-                       <argument index="3" name="flags" type="int" default="7">
+                       <argument index="3" name="flags" type="int" default="null">
```

- [x] `Error` enum as return type is not properly inferred (or any enum as return type maybe?):
```diff
@@ -13483,7 +15289,7 @@
                        </description>
                </method>
                <method name="make_dir_recursive">
-                       <return type="Error">
+                       <return type="int">
                        </return>
                        <argument index="0" name="path" type="String">
                        </argument>
```

- [x] Some `Object` types seem incorrectly inferred:
```diff
@@ -28286,10 +31436,11 @@
                        </description>
                </method>
                <method name="set_script">
-                       <argument index="0" name="script" type="Script">
+                       <return type="void">
+                       </return>
+                       <argument index="0" name="script" type="Reference">
                        </argument>
                        <description>
-                               Set a script into the object, scripts extend the object functionality.
                        </description>
                </method>
                <method name="tr" qualifiers="const">

[...]

                <method name="set_stream_peer">
-                       <argument index="0" name="peer" type="StreamPeer">
+                       <return type="void">
+                       </return>
+                       <argument index="0" name="peer" type="Reference">
                        </argument>
                        <description>
-                               Set the StreamPeer object to be wrapped
                        </description>
                </method>

[...]

                <method name="set_shape">
-                       <argument index="0" name="shape" type="Shape2D">
+                       <return type="void">
+                       </return>
+                       <argument index="0" name="shape" type="Resource">
                        </argument>
                        <description>
-                               Set the [Shape2D] that will be used for collision/intersection queries.
                        </description>
                </method>

[...]

                <method name="add_collision_exception_with">
-                       <argument index="0" name="body" type="PhysicsBody">
+                       <return type="void">
+                       </return>
+                       <argument index="0" name="body" type="Node">
                        </argument>
                        <description>
                        </description>
@@ -32170,18 +35687,24 @@
                        </description>
                </method>
                <method name="remove_collision_exception_with">
-                       <argument index="0" name="body" type="PhysicsBody">
+                       <return type="void">
+                       </return>
+                       <argument index="0" name="body" type="Node">
                        </argument>
                        <description>
                        </description>
                </method>

[...]

                <method name="create_item">
-                       <return type="TreeItem">
+                       <return type="Object">
                        </return>
-                       <argument index="0" name="parent" type="TreeItem" default="NULL">
+                       <argument index="0" name="parent" type="Object" default="null">
                        </argument>
                        <description>
-                               Create an item in the tree and add it as the last child of [code]parent[/code]. If parent is not given, it will be added as the last child of the root, or it
'll the be the root itself if the tree is empty.
                        </description>
                </method>
```

CC @reduz @neikeq

**Comment by neikeq** [comment]
1. #10903
2. This is because of @reduz's changes to the way `DocData` converts the default arguments to string. I didn't change anything regarding this in my bindings generator and the output is fine.
3. This is a weird one. I'll have to investigate this further.
4. This is because those are the actual types in the method declaration. The old hints were fake ones used to make documentation clearer. I'm not sure what's the best way to tackle this one (cc @reduz):
    - Should we change declaration of the methods?
    - Should we use `PROPERTY_HINT_RESOURCE_TYPE` and `hint_string` instead? This would be fine as long as it doesn't cause bugs with `ptrcall`.

**Comment by reduz** [comment]
@neikeq This is because I could not find a way to cast arguments such as TreeItem* to cast to Variant when using bind method arguments, but maybe this can be solved somehow.

**Comment by reduz** [comment]
@neikeq if those functions could be made to accept their actual types, this would work better..

**Comment by neikeq** [comment]
@akien-mga Regarding 4., are those all the affected methods?

**Comment by akien-mga** [comment]
>  Regarding 4., are those all the affected methods?

There might be a few more, I was not very thorough in my listing. If could have another in-depth look at the diff if you want.

**Comment by neikeq** [comment]
Don't worry, just wondering what all the cases are so we can have a better look at what to do. I'll check the diff when I have time.

**Comment by akien-mga** [comment]
#10903 seems to have fixed 2. too.

**Comment by neikeq** [comment]
Regarding 4. and the methods in the diff above:
- `void Object::set_script(const RefPtr &p_script)` -> `void Object::set_script(const Ref<Script> &p_script)`
  - Used in several places, but I don't see any reason for it not to be `Ref<Script>`. cc @reduz

The following methods are not used anywhere:
- `void PacketPeerStream::_set_stream_peer(Ref<Reference> p_peer)` -> `void PacketPeerStream::_set_stream_peer(Ref<StreamPeer> p_peer)`
- `void Physics2DShapeQueryParameters::set_shape(const RES &p_shape)` -> `void Physics2DShapeQueryParameters::set_shape(const Ref<Shape2D> &p_shape)`
- `void PhysicsShapeQueryParameters::set_shape(const RES &p_shape)` -> `void PhysicsShapeQueryParameters::set_shape(const Ref<Shape> &p_shape)`
- `void PhysicsBody2D::add_collision_exception_with(Node *p_node)` -> `void PhysicsBody2D::add_collision_exception_with(PhysicsBody2D *p_node)`
- `void PhysicsBody::add_collision_exception_with(Node *p_node)` -> `void PhysicsBody::add_collision_exception_with(PhysicsBody *p_node)`
- `void PhysicsBody2D::remove_collision_exception_with(Node *p_node)` -> `void PhysicsBody2D::remove_collision_exception_with(PhysicsBody2D *p_node)`
- `void PhysicsBody::remove_collision_exception_with(Node *p_node)` -> `void PhysicsBody::remove_collision_exception_with(PhysicsBody *p_node)`
- `Object *_create_item(Object *p_parent)` -> `TreeItem *_create_item(TreeItem *p_parent)`

**Comment by akien-mga** [comment]
I think it's all fixed by now.
