### ISSUE TITLE
2D shader parser bug?

### ISSUE THREAD

**Issue by vetoed** [godotengine/godot#10893]
Windows 10 x64 - tested in Godot v2.1.3 and v2.1.4 x64 - GeForce 560Ti - 384.94

I happened to write a shader that sometimes works fine and sometimes fails to compile. Included in example project. If compilation fails, the screen goes completely white.
`ERROR: ShaderGLES2::get_current_version: CanvasShaderGLES2: Fragment Program Compilation Failed:
0(276) : error C1008: undefined variable "_lightmult"
At: drivers\gles2\shader_gles2.cpp:471`
   
Error message from 2.1.3. It was working fine before I added a couple of additional parameters. There is a uniform variable called "lightmult" in the shader, without an underscore...

To reproduce, open the example project. If shader compiled correctly, close the editor and open it and the project again.

[shader_compilation_bug.zip](https://github.com/godotengine/godot/files/1272243/shader_compilation_bug.zip)

**Comment by vetoed** [comment]
`ERROR: ShaderGLES2::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles2/shader_gles2.h:345
found bug?
misplaced token: OP_MUL
found bug?
misplaced token: OP_MUL
***Error precompiling shader: Error parsing expression, misplaced: OP_MUL
error 13:1
ERROR: ShaderGLES2::get_current_version: CanvasShaderGLES2: Fragment Program Compilation Failed:
0(284) : error C1008: undefined variable "_lgtmult"

   At: drivers\gles2\shader_gles2.cpp:471
ERROR: ShaderGLES2::get_current_version: Method/Function Failed, returning: 0
   At: drivers\gles2\shader_gles2.cpp:479
ERROR: ShaderGLES2::bind: Condition ' !version ' is true. returned: false
   At: drivers\gles2\shader_gles2.cpp:123
ERROR: ShaderGLES2::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles2/shader_gles2.h:345`

more console log

**Comment by vetoed** [comment]
Variable names:
lightmult -> bugs
lgtmult -> bugs
brtmult -> no bugs

Maybe i can save myself editing all materials by changing the multiplication order...

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
