### ISSUE TITLE
HTML not showing Image created with "ImageTexture.create_from_image"

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#10905]
Godot 2.1.4
X11

Example
```
extends Node2D


func _ready():
	
	var texture = ImageTexture.new()
	texture.load("res://icon.png")
	texture.set_flags(2)
	
	var image = texture.get_data()
	
	var texture2 = ImageTexture.new()
	texture2.create_from_image(image.get_rect(Rect2(0,0,64,64)),2)
	
	get_node("Sprite").set_texture(texture2)
```

**ERROR**: At: core/image.cpp:2175:blit_rect() - Condition ' srcdsize == 0 ' is true.

**Comment by rdominick** [comment]
I am having this problem as well; the map in my RPG is drawn onto an image offscreen and then part of that image is blitted over the visible TextureRect. This works well in the Windows run-time, but does not work at all in the HTML 5 version of the game, nor does the texture setting for the player's sprite.

**Comment by AlexHolly** [comment]
game.js:4    At: core/io/image_loader.cpp:55:load_image() - Error opening file: res://sprites/title.png

Also a thing in 3.0 https://github.com/godotengine/godot/commit/6c569c90b666c7fb773eca3948fc76ba7a160a27

**Comment by AlexHolly** [comment]
Any reason why the project size is not set in the index.html?

`/misc/dist/html/default.html`

```
</head> 
<body> 
  <div id="container"> 
 <canvas id="canvas" width="$GODOT_WIDTH" height="$GODOT_HEIGHT"> 
```
