### ISSUE TITLE
Xbox Controller D-PAD is_echo() is not working on HTML export

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#10904]
Godot 2.1.4
X11 - Kubuntu 17.04
Chrome Browser 60.0.3112.113 (Official Build) (64-bit)

```
extends Node2D


func _ready():
	set_process_input(true)


func _input(ev):
	if !ev.is_echo() && Input.is_action_pressed("left"):
		print("left")
```

This code has a different behavior on HTML. It prints 4 times "left" on other platforms it only prints once.
The action "left" is Xbox D-Pad Left.

**Comment by eska014** [comment]
`Input.is_action_pressed("left")` doesn't check the event currently processed in the `_input()` callback, it checks if the given action is pressed at all.

The sample code prints `"left"` whenever any non-echo input event is received while the D-Pad Left button is held down.
