### ISSUE TITLE
Animation from AnimationPlayer Disappeared

### ISSUE THREAD

**Issue by jscheel** [godotengine/godot#10909]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOS 10.12.5, Godot 2.1.4

**Issue description:**
I duplicated an animation in an animation player. After going back to the player node at a later time, the animation was not in the dropdown, but it still worked when playing the game. After a restart of Godot, the animation was completely gone, both in the editor and in the game.

**Steps to reproduce:**
Not sure, duplicate animation, rename, edit, switch away from node, come back later :)

**Comment by hpvb** [comment]
Does this happen for you in 2.1.3?

**Comment by jscheel** [comment]
@hpvb I haven't been able to reproduce :( The only thing I notice that was weird was that the animation did not have a name in the scene file (even though it had an id).

**Comment by jscheel** [comment]
I still have not been able to reproduce. Any objections to closing this to keep the issue queue clean?

**Comment by akien-mga** [comment]
Sounds good to me. :)
