### ISSUE TITLE
Sub-drop menus sometimes don't work correctly

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10911]
**Ubuntu 17.04, Godot Build: 6b99950**

**Issue description:**

- [x] Sometimes hovering is not enough, you have to click them for their drop menu to open.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30739239/29999176-faf6e838-9014-11e7-93b8-8790af861ac9.gif)

- [x] If you move the mouse to the previous drop menu, opening it again will show the last option highlighted.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/30739239/29999178-0167d5f6-9015-11e7-95d6-5b0bcbd6a5ac.gif)

**Comment by coppolaemilio** [comment]
Same happening in Windows 10

**Comment by AlexHolly** [comment]
Is it intended to click twice for closing a Menu?

![peek 2017-10-18 17-48](https://user-images.githubusercontent.com/4741886/31728414-8edfdef2-b42c-11e7-8212-de0f53b31b3d.gif)

**Comment by homer666** [comment]
@AlexHolly That's been bugging me too. Removing [this line](https://github.com/godotengine/godot/blob/f52ab8d86418a67ddee247ed7765e72935b0c57f/scene/gui/menu_button.cpp#L58) fixes it, but there's probably a good reason why it's there, and I don't know of a way to remove it for just those instances.
