### ISSUE TITLE
Error messages when importing the export templates

### ISSUE THREAD

**Issue by philiplb** [godotengine/godot#1091]
On importing the export templates, you get this error message:

  Can't open export templates zip

This happens on trying to import the freshly downloaded export_templates.tpz into Godot 1.0. Renaming the file extension to .zip is a workaround.

**Comment by akien-mga** [comment]
On what platform did this happen? Can you reproduce it in Godot 1.1 or a current nightly build of 2.0?

**Comment by akien-mga** [comment]
Assuming this is no longer an issue as we didn't get confirmations from other users.

**Comment by roman2861** [comment]
I can confirm it. Ubuntu 15.10, Godot 2.0 - last build from official site.

**Comment by akien-mga** [comment]
What is the error message? Does the above-mentioned workaround solve it (change tpz extension to zip)?

Is there a non-ascii character in the path where you downloaded the export templates?

**Comment by roman2861** [comment]
I understood the reason why it's happened. I am from Russia and i had this file in Documents directory (in Russian "Документы"). So, in my case that's happened because of Cyrillic symbols in directory.

**Comment by akien-mga** [comment]
Ok, it was this issue then: https://github.com/godotengine/godot/issues/1708
