### ISSUE TITLE
Negative modulus returns a negative rather than 0 to modulus value

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#10915]
Godot 3.0, Windows x64

`print(str(-1 % 3))` prints `-1` to Output when it should be `2`. Positive numbers are modded properly.
I'm confused exactly how this is happening since I traced it, but found perfectly reasonable stuff (line numbers might be a bit off since my version is a few days old).

    gd_tokenizer.cpp: 758: _make_token(TK_OP_MOD)
    gd_parser.cpp: 1063: op = OperatorNode::OP_MOD
    gd_parser.cpp: 1695: _REDUCE_BINARY(Variant::OP_MODULE)
    gd_parser.cpp: 1629: Variant::evaluate(m_vop, static_cast<ConstantNode *>(op->arguments[0])->value, static_cast<ConstantNode *>(op->arguments[1])->value, res, valid); \
    variant_op.cpp: 829: _RETURN(p_a._data._int % p_b._data._int);

Having confirmed that both _int values would've been `int64_t` types, it's strange.
Two integers running `%` between them should yield a non-negative answer, so I'm very confused.

**Comment by fire** [comment]
Are you familiar with the standard use of % which means remainder? https://en.wikipedia.org/wiki/Modulo_operation#Remainder_calculation_for_the_modulo_operation

**Comment by willnationsdev** [comment]
Oh, I didn't realize it was doing something like that. I guess I'll close this if it's intentional and in line with math principles like that.
