### ISSUE TITLE
doc double line spacing

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#10919]
the docs convert '\n' to '\n\n'
which makes spacings really big.
what is the idea behind it?
and wouldn't it be better to add two new lines in the classes.xml where it actually makes sense?

**Comment by akien-mga** [comment]
One line == one paragraph. Just use long lines in the XML.
reST doesn't really support `<br>`, so it's better to assume that the feature doesn't exist and to keep sentences on the same line == same paragraph, unless something warrants opening a new paragraph for clarity.

**Comment by toger5** [comment]
But is it still necassary to double ALL newlines in inline docs.
I totally see the point for consitency with the web version with normal paragraphs. But at least for codblocks it should be removed.
(lists are not supported are they? If they are there also should be no double <br> i think.

**Comment by djrm** [comment]
@toger5 this has been fixed, now there is not newline insertion.
