### ISSUE TITLE
Custom editor font doesn't save between sessions

### ISSUE THREAD

**Issue by aegarpyke** [godotengine/godot#1092]
I can't really reproduce this bug on demand but it has happened to me at least 5 times since I started playing around with custom editor fonts two days ago. Basically, I set the font for the script editor and it looks fine. I exit out. After a while, I boot up Godot again and the font is back to Source Code Pro even though the settings still show that my custom font is set.

**Comment by akien-mga** [comment]
Can you still reproduce this bug with Godot 1.1 or a current nightly build of 2.0? If so, on which platform? Did it happen while using different versions of Godot, e.g. switching from 1.1-stable to a dev snapshot?

**Comment by akien-mga** [comment]
Closing as there has not been any activity, and was reported against an old Godot version. Feel free to reopen or open a new issue with more details if the bug is still valid.
