### ISSUE TITLE
Add SpriteFrames editor automatically to bottom panel when selecting AnimatedSprite

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#10923]
Every time the user wants to edit the sprite frames of an animated sprite node, he/she has to find the sprite frames resource in the inspector, then click once to bring up the resource menu and again to bring up the sprite frames window opening it , then adding it to the bottom panel.

My suggestion is to have godot editor automatically check the AnimatedSprite node upon selection -if it has a spriteframes resource, then add the sprite  frames button to the bottom panel - without any need from the user to click and dig to get to it.

I know that this can be done with the addon system and I have already done it for myself- but I strongly believe that it should be a part of godot's design.

The sprite frames editor is a pain in the arse to get to, considering that it will disappear,along with its button in the bottom panel every time you click on any other node in the scene.

Lets reduce the number of clicks required by the user to get to it - they really add up

**Comment by puppetmaster-** [comment]
point 4 on this list :)
