### ISSUE TITLE
Center point of the 3D editor has visual glitches

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10928]
**Ubuntu 17.04, Godot Build: 6b99950**

**Issue description:**
The light blue center point of the 3D editor (I'm quite sure there is a actual name for it, but hell if I know) has visual glitches, and it seems to be fighting with the red and dark blue lines.

![screenshot at 2017-09-03 01-00-09](https://user-images.githubusercontent.com/30739239/30004730-15f63620-90ab-11e7-9be5-51eff8d4516f.png)

**Comment by Calinou** [comment]
This could possibly be fixed by turning the origin into a mesh, which would display a similar shape, but slightly thicker, so that it overlaps the grid lines.

**Comment by YeldhamDev** [comment]
It seems that there is no origin representation anymore now. So I suppose this should be closed.
