### ISSUE TITLE
RichTextLabel does not perform well 'out of the box'

### ISSUE THREAD

**Issue by Brickcaster** [godotengine/godot#10924]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.4

**Issue description:**
The behavior of RichTextLabel is unsatisfactory.  One cannot simply do:  
```#self is GridContainer  
var node = RichTextLabel.new()  
node.set_bbcode("Some Text")  
add_child(node)
```
 
And have it work.

Instead, one must do:  
```#self is GridContainer  
var node = RichTextLabel.new()  
init_richtextlabel(node)  
node.set_bbcode("Some Text")  
add_child(node)  
...  
func init_richtextlabel(node):  
	node.set_use_bbcode(true) #Not strictly necessary, but otherwise we would use Label. 
	node.set_scroll_active(false) #Not strictly necessary, but this behavior is distinctly different from Label.  
	node.set_custom_minimum_size(Vector2(50, 16)) #This or the next two lines, depending on desired behavior  
	#node.set_h_size_flags(SIZE_EXPAND_FILL)  
	#node.set_v_size_flags(SIZE_EXPAND_FILL)  
```

A side note is that `node.set_v_size_flags(SIZE_EXPAND)` does not work as expected to make the node size match the text size and using SIZE_EXPAND_FILL can be undesirable.

**Expected Behavior:**
RichTextLabel nodes behave more comparable to Label nodes, automatically sizing them to match their contents and use_bbcode flag by default is set to true.

**Comment by toger5** [comment]
So basically you want the default values to be changed?

I thubk that makes sense

**Comment by Brickcaster** [comment]
Not just the default values, but also the set_v_size_flags(SIZE_EXPAND) behavior does not seem to match the behavior of Label nodes.

**Comment by Paluth** [comment]
Just to note. I'm new to godot. I tried using richtextlabel and it didn't work as expected. I didn't know I had to set options for it to work. I ended up giving up on using it.
I also feel it should work out of the box, without setting any options or it makes learning godot harder than it should.
That being said, I know changing the behavior of richtextlabel can cause problem for people already using it. But for 3.0 there is no such concern as it already breaks compatibility in several places. So this is an opportunity to fixes it.

**Comment by Brickcaster** [comment]
I got 3.0 to compile and I verified that this also occurs in 3.0

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by mjtorn** [comment]
As a Godot n00b who's involved in the Escoria framework, I can confirm having an automatically scaled `RichTextLabel` is infuriatingly painful as opposed to just using a `Label`.

For historical reasons, I assume, the node is a child of a `Container` that's a child of another `Container` with `SIZE_EXPAND` set. Neither that nor `SIZE_EXPAND_FILL` work as well as they'd work with a simple `Label`. So I don't think the containers are at fault here, as also attested by the previous comments.

Unfortunately the framework assumes that it's a `RichTextLabel` although I tested hacking around the code to enable the use of a `Label` for testing, so this really should be better, by eg. behaving like a `Label`.

Is there a technical reason why this isn't so?

Version 3.0.2.

**Comment by Calinou** [comment]
`use_bbcode` is most likely `false` by default for "security" reasons. There are many cases where you want to use RichTextLabel for styling but want to prevent players from adding their own formatting (or worse, clickable links that could lead to phishing sites or similar).

**Comment by akien-mga** [comment]
This should likely be rewritten as a proposal on https://github.com/godotengine/godot-proposals to assess what potential changes should be made to default values, and what the community at large thinks about it.
