### ISSUE TITLE
ScrollContainer problem with dynamic content

### ISSUE THREAD

**Issue by Paluth** [godotengine/godot#10938]
Hello,

I'm on windows 10 64bits, with godot 2.1.4.

I have a VBoxContainer inside a ScrollContainer. I add and remove items to the VBox dynamically though code. When I do this, the scrollbar gets messed up. Either it too large for the content or it shows up when it shouldn't.
As soon as you try to move the scrollbar it automatically fixes it self. To see the bug just open the attached project, run it, and click the button a few times. You will quickly see how the scrollbar is wrong, especially if you try to move it and see it disappear or resize.

[ScrollTest.zip](https://github.com/godotengine/godot/files/1273116/ScrollTest.zip)

**Comment by YeldhamDev** [comment]
I have already reported this: https://github.com/godotengine/godot/issues/10207

There is also a temporary solution for it as well

**Comment by Paluth** [comment]
Sorry I will close the issue, but what is the temporary solution you mention?

**Comment by YeldhamDev** [comment]
@Paluth On the issue I just linked.

> The developer needs to use signals and manually call "queue_sort()" for the container.

**Comment by Paluth** [comment]
@YeldhamDev 
I added this two lines to my sample project:
```
   var scroll = get_node("ScrollContainer")
   scroll.queue_sort()
```

It doesn't solve the problem in my case.

**Comment by YeldhamDev** [comment]
@Paluth It has to be called from the VBox's "sort_children()" signal.

**Comment by Paluth** [comment]
@YeldhamDev That seams to work, so I'm closing this thread. Thanks for the help.
