### ISSUE TITLE
Dragging a category into VS graph crashes the editor

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#10935]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 26, ce28452109676d55e4d1fbb7158c8bf1fa8db406

**Issue description:**

Dragging a category from the list into the VS graph crashes the editor.

**Steps to reproduce:**
Drag a category (like "data") into the VS graph

**Link to minimal example project:**

**Comment by gamergamesz** [comment]
i can confirm that

**Comment by gamergamesz** [comment]
If someone is fixing then it would be great to have a look at this #10440
