### ISSUE TITLE
The selection rectangle doesn't update

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#10936]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10. Godot 3.0 29db531fc8360b1e6d5e23008b208517b6d8c627

**Issue description:**

The selection rectangle isn't being updated when the sprite is moved/scaled or when undoing the transformation:

![https://i.imgur.com/qTPzaBN.gif](https://i.imgur.com/qTPzaBN.gif)

**Steps to reproduce:**
Add a sprite to a scene and do stuff with it

**Comment by toby3d** [comment]
Same effect on Linux

**Comment by Zephilinox** [comment]
It would be nice to keep the old bounding rectangle in a different colour while showing the new one, just so you can see what you've done.

**Comment by toger5** [comment]
@poke1024 seems like something you could do pretty quickly?

**Comment by olejr** [comment]
Reverting changes made to [editor/plugins/canvas_item_editor_plugin.cpp](https://github.com/godotengine/godot/commit/437fb12e1aa3135dc7fa336bd0a53036be649ce8#diff-3910e354cfb3848e417581c47035e5c5), line 2260 and on, seem to fix this issue.
