### ISSUE TITLE
Previews for scenes

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#10945]
Do you think it would make sense to have some kind of preview for tscn files without having to open the scene?

e.g. I have a project with many different trees. Every tree has its own scene. When I'm looking for a specific tree I have to open every scene until I find the one I'm looking for and then close every other scene I have opened this way. 

I thought of two possible solutions: 

1. The preview could show inside the inspector.

2. Or maybe it could open the scene as a temporary tab, like in Atom or visual studio code when single-clicking on a text file from the folder-tree. And when you select another scene, the temporary tab closes automatically. When you change something inside the scene, the temporary tab turns into a normal scene tab.

What do you think?

**Comment by Calinou** [comment]
Binary (`.scn`) scenes already have a preview, `.tscn` scenes also have one (it's stored in a cache directory of the Godot user data directory). You can see these when browsing files using the built-in file browser in Godot, but it may not always show up.

**Comment by BeayemX** [comment]
Thanks for the info, I didn't know that. I usually open the scenes via the filesystem-tree-area or by using the quick-open functionality.

But I was also looking for something a bit more interactive, like being able to rotate the camera inside the preview to get a better view of the scene (would only make sense for 3d scenes). But the more I think about it, the less I'm convinced that this a necessary feature. It's probably better to just open the scene...

**Comment by toger5** [comment]
@BeayemX interesting idea.
But I think the 3d preview would take quite a lot of resources. than it might be better to just open it.

I think the current image is a good compromise of getting enough information about the scene and not taking o much work to develop + easy to compute.

**Comment by NathanWarden** [comment]
I like your idea number 2 for Godot to have a tabbed interface... Godot 4.0 FTW! :)

**Comment by akien-mga** [comment]
All scenes have previews now AFAIK.
