### ISSUE TITLE
empty Inspector after playing the project

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#10943]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7, Godot_v2.1.4-stable_win64.exe

**Issue description:**
happens only on 2.1.4
![bug_2 1 4](https://user-images.githubusercontent.com/10463138/30006412-07c6c0a4-90f8-11e7-9700-3bcaeb894653.gif)

**Comment by vnen** [comment]
It's the same as #9408, but it was fixed only in master.

**Comment by akien-mga** [comment]
Fixed by 73d855d.
