### ISSUE TITLE
"Condition ' p_axis.is_normalized() == false ' is true."

### ISSUE THREAD

**Issue by dracc** [godotengine/godot#10956]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Debian Testing ("Buster")
Godot v3.0.alpha.custom_build.3873362
Asus Radeon R9 290X, amdgpu driver (Not graphics related issue though..)

**Issue description:**
I get about 3-4 thousand lines per second stating that the
`Condition ' p_axis.is_normalized() == false ' is true.`
cluttering my error log. Also, about every 10th line, the message
`Condition ' determinant() == 0 ' is true.`
pops up. Also, a little more sparsely,
`Condition ' det == 0 ' is true.`
is given. No idea why.

**Steps to reproduce:**
Create new 3D project. Import two COLLADA files.
Create VehicleBody and VehicleWheels for first of said imported files.
Try to run the game through the "play" button in the top right corner.

**Link to minimal example project:**

[second_godot.zip](https://github.com/godotengine/godot/files/1274268/second_godot.zip)

**Comment by dracc** [comment]
After adding a CollisionShape to the VehicleBody in the provided example, the errors were gone.

**Comment by Zireael07** [comment]
So you were trying to make a shapeless vehicle body? :D

**Comment by dracc** [comment]
@Zireael07 : Seems like it. :joy: Close issue? Or, maybe, someone could do something about the somewhat cryptic error messages? 😛

**Comment by Zylann** [comment]
The message shouldn't be logging every frame like this, something more meaningful should be shown

**Comment by cbscribe** [comment]
This also happens if you have a RigidBody with no assigned shape.

**Comment by Chaosus** [comment]
These errors are not detectable(3.1 stable) in the provided project, and in empty scene with shapeless RigidBody, closed by bugsquad.
