### ISSUE TITLE
Section highlighting in Scene Editor

### ISSUE THREAD

**Issue by aegarpyke** [godotengine/godot#1095]
I like that the mouse-scroll is contextual to which section the mouse is currently hovering over (whether it's the Node list, the Inspector, the Scene View, etc). However, I think it would be more intuitive if the currently-hovered section was highlighted on hover.

For example, right now, if you click in the Inspector section of the editor, the whole Inspector section gets highlighted. If you move your mouse to hover over the Node list, the mouse-scroll affects the Node list but the Inspector stays highlighted. This is unintuitive. Instead, once the mouse hovers over the Node list, the Node list should be highlighted.

**Comment by akien-mga** [comment]
I confirm that the above-described behaviour is still the same in the current master branch, apart from the main viewport which gets highlighted on hover. Personally I find the current behaviour fine, but if we want to make highlighting on hover for all docks, I wouldn't be opposed either.

**Comment by akien-mga** [comment]
2 and a half years later, I think it would still be an OK enhancement, but not really high priority. As this issue did not generate much interest over the years, I'll close it for now to reduce the backlog and help focus on important bug fixes.

Feel free to comment if you would still be interested in this enhancement or would work on it, this issue could be reopened.
