### ISSUE TITLE
emission_stopped signal for particles2d node 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#10954]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot 2.*

**Issue description:**

For example, I need to spawn a explosion effect when a bullet hit some object, I set the particles2d as following:
LifeTime = 1
Emit Timeout = 1

When the particles2d stop emitting and all the particles becomes invisible, I want the free the particles2d node. But I can not find an easy way to do this, since no Notification or signal is emitted for this event, I can not  determine when the particles2d node is ready for free.

Is it possible to add a Notification when the particles2d is not emitting and no particles in the node?

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by HummusSamurai** [comment]
Ping @reduz who had been saying on IRC how particles in general do not have signal bindings yet to the editor which would have to be added.

**Comment by kubecz3k** [comment]
Wondering how this can be implemented now when particles are implemented via shader and are working on GPU. Would we need an ability to emit signal from inside of particle material?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/649, as feature proposals are now tracked on the Godot proposals repository.
