### ISSUE TITLE
can't scale the font size in the built-In script editor.

### ISSUE THREAD

**Issue by casd82** [godotengine/godot#10957]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS 10.12.6, Godot 2.1.4 stable

**Issue description:**
In Godot 2.1.4 beta and the previous versions, you can press <kbd>Cmd</kbd> + <kbd>=</kbd> and <kbd>Cmd</kbd> + <kbd>-</kbd> to scale up and down the font size. However, in Godot 2.1.4 stable, this functionality is gone.

**Steps to reproduce:**
Open up the built-in script editor on Godot 2.1.4 on macOS. Press <kbd>Cmd</kbd> + <kbd>=</kbd>.

**Comment by Zylann** [comment]
Is it working with Ctrl+Mouse wheel?

**Comment by casd82** [comment]
No it doesn't work either.

**Comment by Listwon** [comment]
Godot 2.1.4 stable
Tested on macOS Sierra 10.12.6 
Shortcuts work (<kbd>Cmd</kbd> + <kbd>=</kbd>, <kbd>Cmd</kbd> + <kbd>-</kbd> and <kbd>Cmd</kbd> + <kbd>0</kbd>)
Only <kbd>CMD</kbd> + scroll on Magic Mouse doesn't work.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
