### ISSUE TITLE
Custom node types are created with their script attached to them

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#10951]
Godot 2.1.4 and Godot 3.0 both make it so that custom node types, when added to the node hierarchy, have their internal script attached to them when they SHOULD have NO script attached by default, just like any other node.

Godot 2.1.4:
![2017-09-03 1](https://user-images.githubusercontent.com/16217563/30008484-c986fa32-90e5-11e7-880c-7b1b1cd97c4c.png)
![2017-09-03 4](https://user-images.githubusercontent.com/16217563/30008486-cf83b8d0-90e5-11e7-9acd-e3d9f6548ff1.png)

**Comment by Zylann** [comment]
But that's how custom nodes defined by plugin always worked (contrary to modules and engine nodes). They have a script attached to them because they are defined by scripting rather than modifying the engine. In Godot, all objects can have only one script on them.

**Comment by willnationsdev** [comment]
My mistake. I was misunderstanding things about how custom types work. Closing.
