### ISSUE TITLE
[Godot 3.0] Vector3 slide

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#10967]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
All OS, Godot 3.0

**Issue description:**
Slide formular is wrong?
From [commit](https://github.com/godotengine/godot/commit/1a620bd5faebd83015182ea032f40936a9916af6)

Formular was changed from:
`p_vec - *this * this->dot(p_vec)`
to:
`*this - p_normal * this->dot(p_normal)`

**Comment by toger5** [comment]
@tagcup

**Comment by mhilbrunner** [comment]
cc @tagcup Is this correct or should this be closed? :)

**Comment by akien-mga** [comment]
That's correct, the new API makes a lot more sense (`base_vec.slide(normal)` and no longer a weird `normal.slide(base_var)`).
