### ISSUE TITLE
EditorPlugin/addon api - A way to access the currently selected frame in the SpriteFrames editor and get its path

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#10960]
I am trying to write an addon that lets the user open an image file from the spritesheet editor with an external app - directly from godot.

to do that I have to get the name of the currently selected animation in the spritesheet editor, and also get the currently selected frame.

`get_selection().get_selected_nodes()[0].get_animation()) `
will always return the first animation, or whatever is set in the inspector, and not what I need - what the user has selected in the sprite sheet editor

There seems to be no way to access that information from the spritesheet editor via gdscript.

Is this possible to do at all, or is it a missing feature?

My end goal is to make an addon that lets godot create new image files and open them in any external editor - with a single command - as well as open existing images in sprites, spritesheets and any node that has them as a resource

I tried writing a pixel art tool addon, but abandoned it for now , since I got stuck at the eraser tool -godot is missing a blending mode that would allow me to implement an eraser tool in a clean way.
https://github.com/godotengine/godot/issues/10255

So I decided to make an addon that would at least let me create and open images in an external editor by calling it from within godot - I want to make a way to have better integration of external tools with the resources within godot that are assigned to nodes -mainly png and other type of images.
I want to reduce the number of clicks required to get to them in an editing app to one or two

**Comment by Calinou** [comment]
This seems to have been implemented closely enough by #19087, closing. If you still need something different, create a proposal on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.
