### ISSUE TITLE
One Way Collisions in Tilemap

### ISSUE THREAD

**Issue by daskrs** [godotengine/godot#10966]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Manjaro Linux , Godot 2.1.4 stable

**Issue description:**
When you set Oneway collision in a tile it works well inside Godot, but when u export the game to any plataform, like linux, windows, mac, android the collision change to normal.

**Steps to reproduce:**
Make a new scene, make your tiles, add a StaticBody2D and a CollisionShape2D or CollisionPolygon2D in your tiles. Set the StaticBody2D One Way Collisior to Direction (0,1) and Max Depth (1) , export your tiles to .tres, .res or .xml. Add a TileMap node in your main scene, draw your tilemap scene put a player int he scene, export the project to any plataform. 

**Link to minimal example project:**
https://drive.google.com/file/d/0By9n8Akl7DQ4OFBDMUNPc1Rtb00/view?usp=sharing

**Comment by akien-mga** [comment]
Did you update your export templates too?

**Comment by daskrs** [comment]
i swear i did it before, but i try update the exports again and all work fine now.

**Comment by akien-mga** [comment]
Perfect, closing then :)
