### ISSUE TITLE
[3.0 alpha] Animation ui issue

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#10964]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 Build from 03.09.2017

**Issue description:**
When i try add new track in Animation player (track with call func). This what happened :3
![ui](https://user-images.githubusercontent.com/6241034/30033846-84faabea-91a6-11e7-8e99-2b82bd97d3f5.png)

**Steps to reproduce:**
1. Create animation.
2. Add track with call functions.

**Comment by akien-mga** [comment]
Fixed by #11052.
