### ISSUE TITLE
Multithreaded instancing performance (RID caching needs to be completed)

### ISSUE THREAD

**Issue by kerskuchen** [godotengine/godot#10970]
Because of the recommendation from Zylann in the [Q&A Topic](https://godotengine.org/qa/17821/instancing-in-another-thread?show=17832#c17832)  I want to open the following issue:

**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64Bit, Godot 3.0 master-branch

**Issue description:**
Instancing (not counting loading the resource) Levelchunks from PackedScenes on another thread takes (dependent on the scene size) up to half a minute, while instancing them from the main-thread takes 10ms-ish. This makes level streaming in Godot not practical at 60fps without visible frame stutters. 

Chunking levels even smaller makes the overhead of loading too many small scenes not feasible. The only alternative way right now is to save scenes into a binary file manually storing only it's properties. Then when parsing the file again, applying the properties to a pre-instanced pool of nodes. 
But this defeats the purpose of the whole Godot nodes&scenes concept and Editor tooling. 

**Steps to reproduce:**

Start a thread and instance any scene and time it, compare to instancing with main thread.

**Comment by Zylann** [comment]
Would be nice if you had a minimal project and code where you noticed the slowdown :)

**Comment by kerskuchen** [comment]
Here is a minimal example. It would just be nice if Godot could load that scene in another thread at least in under 5 seconds. That would be more that enough :D
[threaded_instancing.zip](https://github.com/godotengine/godot/files/1275376/threaded_instancing.zip)

**Comment by Zylann** [comment]
Result on Windows 10 64 bits:

```
Main thread:
Preparing to load chunk
Resource load time = 87
Instancing time = 54
Adding child time = 12
Loading time = 156
Finished loading chunk
=============:
Helper thread:
Preparing to load chunk
Resource load time = 13
Instancing time = 43624
Adding child time = 84
Loading time = 43725
Finished loading chunk
ERROR: _Thread::~_Thread: Condition ' active == true ' is true.
   At: core\bind\core_bind.cpp:2304
```

It takes indeed a very long time to instance, while the same scene opens in less than a second in the editor...

**Comment by kerskuchen** [comment]
Even when quartering the level chunk (delete 3/4 of all entities and only have a 16x16 tilemap) I get
Main thread:
Preparing to load chunk
Resource load time = 19
Instancing time = 5
Adding child time = 2
Loading time = 27
Finished loading chunk
=============:
Helper thread:
Preparing to load chunk
Resource load time = 7
Instancing time = 12627
Adding child time = 67
Loading time = 12705
Finished loading chunk

Apart from the practicality/feasibility-question of chunking levels into such small pieces. An Instancing time = 5 in the main thread can already lead to frame hiccups if a lot is going on in the game. If we add Resource load time = 19 into the equation we get a bad frame situation or unneeded complexity when we load the resource in the helper thread - then instance it in the main thread - then process/add it to the tree in the helper thread.

**Comment by reduz** [comment]
The reason is RID caching.. its half done, needs to be completed. Please
leave this as reference for doing that fix

**Comment by reduz** [comment]
When I get home I will add more detail on this

**Comment by jtaart** [comment]
I also noticed this, is it possible for RID caching to be finish for 2.1 branch?

**Comment by reduz** [comment]
OK This should be fixed, or at least improved, please give it a try! Otherwise let me know and I will continue looking for it.

**Comment by kerskuchen** [comment]
It works beautifully and is at least one order of magnitude faster now! Thank you reduz! This is very usable now for the background-streaming of level chunks!

Preparing to load chunk
Resource load time = 33
Instancing time = 58
Adding child time = 29
Loading time = 120
Finished loading chunk
=============:
Helper thread:
Preparing to load chunk
Resource load time = 31
Instancing time = 3253
Adding child time = 95
Loading time = 3379
Finished loading chunk

**Comment by reduz** [comment]
I'm still surprised the instancing time is big, I wonder if I missed something..

**Comment by reduz** [comment]
Oh no It's ok. If you tweak the RID pool prealloc it takes even less, so it should be fine

**Comment by JustusPan** [comment]
@reduz 
hi reduz, what do you mean by "RID pool prealloc" here? Is it possible to get similar performance in thread helper as that in main thread? The performance gap is too surprising...
