### ISSUE TITLE
Shadeless materials are now shaded

### ISSUE THREAD

**Issue by cart** [godotengine/godot#10987]
As the title suggests, materials that should be unshaded are now shaded:
1) ShaderMaterial with the "unshaded" render_mode
2) SpatialMaterials with the unshaded flag
3) Sprite3Ds with shaded unchecked
4) gizmos

This was introduced in the last day or two.  My money is on: e611ff5f0110210221a6f90250bdd65f5fb3ff2d but I haven't looked into it.

**Comment by reduz** [comment]
yeah that is indeed the culprit, will check tomorrow

**Comment by akien-mga** [comment]
See #10990 which should fix it.
