### ISSUE TITLE
In 2.1.4, can't pause a debugged game, and the debugger seems to believe it still runs after closing

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10980]
Godot 2.1.4 stable
Windows 10 64 bits

Unlike 2.1.3, when I play a game, I cannot pause it:
![image](https://user-images.githubusercontent.com/1311555/30038829-4b3b56b6-91c9-11e7-8c28-2fb35533f190.png)

Unlike 2.1.3, when I stop the game, the editor believes it still run, if I close with window close button or the ingame Exit button:
![image](https://user-images.githubusercontent.com/1311555/30038843-784b1b28-91c9-11e7-9755-f61a1f4d2ebe.png)

The game also takes longer to start (about 3 seconds delay, while in 2.1.3 it's close to 1 second only).

**Comment by akien-mga** [comment]
@Geequlim

**Comment by Geequlim** [comment]
@Zylann How can I reproduct that?

**Comment by Zylann** [comment]
I just start any project, make an empty scene and run it. I did the test on my own game though.

**Comment by Geequlim** [comment]
I can't reproduct that with my game projects or an empty one :confused:

**Comment by Zylann** [comment]
Did you close the game with the close button of the window?
I'll try again when I get back home

**Comment by Geequlim** [comment]
![peek 2017-09-05 23-20](https://user-images.githubusercontent.com/6964556/30068686-189d94c6-9291-11e7-8408-a8eb1a388d5c.gif)

**Comment by Zylann** [comment]
Can you test on Windows?

**Comment by Zylann** [comment]
I tested with the joysticks official demo, and it has the same issue on Windows.

**Comment by Zireael07** [comment]
I'm on windows 7 x64, seeing the same thing on both my projects (the working copy and the repo)

**Comment by plucian** [comment]
try setting the debug host to 127.0.0.1: Settings/Network/Debug Host.

**Comment by varkatope** [comment]
@plucian Yes, that did it. It was set to something completely different before, and the console window was complaining about failing and retrying to connect to the debugger.

**Comment by Zylann** [comment]
What is the status on this?

**Comment by Geequlim** [comment]
Is the problem still exsit after #10891?
I can't reprodut it on my laptop (Arch Linux).

**Comment by Dillybob92** [comment]
@Geequlim Thank you.

Do you have a nvidia card you could test this on linux to see if the start up delay is there? (or anyone)

**Comment by Zylann** [comment]
@Geequlim I can't test it yet, but so far it seems like a Windows-only issue (because you couldn't repro any of this on Linux). Or, maybe it's nVidia specific... but I don't have a GTX 950 though

**Comment by Dillybob92** [comment]
Yes, I remember changing the debug host to 127.0.0.1 when testing the GTX 950, the delay was still there, unfortunately. The [delay looks different](https://camo.githubusercontent.com/b4160e85e96c318f0e2ff863d46b840b9563ea95/68747470733a2f2f692e6779617a6f2e636f6d2f33356134333763613363376362313561353831363364633331633164353232652e676966), see how after the window pops up, there is a blank screen and delay.

With the debug issue, it just took a while for the window to open but when it opened, there is no delay in rendering the screen.

**Comment by RoryMcMaster** [comment]
Related to #13381, PR #13383 fixes white screen. However, delay is still there. Must dig, deeper. Stay strong.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
