### ISSUE TITLE
slope_stop_min_velocity unimplemented in KinematicBody (3D)

### ISSUE THREAD

**Issue by louisVottero** [godotengine/godot#10981]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
built from github today.

**Issue description:**
in the kinematic character demo (2D) the kinematic body does not slide down slopes.   In the kinematic character 3D demo if you rotate the tilemap slightly the character slides down the slope.   I was expecting that there would be some simple solution to sliding on slopes or maybe that the move_and_slide command would not allow for sliding by default. 

**Steps to reproduce:**
take the kinematic character 3D demo. Rotate the tilemap slightly. Run the game.  Cubio slides down the slope. 

**Link to minimal example project:**

**Comment by eon-s** [comment]
It is supposed to be the `slope_stop_min_velocity` parameter, right?

**Comment by louisVottero** [comment]
I think so, but that doesn't seem to change anything.  I set slope_stop_min_velocity to 10000000 and things still behave the same as at 0.05

**Comment by eon-s** [comment]
Is because the part supposed to use it is commented out (I don't know the reason)
https://github.com/godotengine/godot/blob/master/scene/3d/physics_body.cpp#L986

**Comment by louisVottero** [comment]
It would be great to have this.  Godot 3 has much improved 3D graphics, makes sense that the kinematic body be working to explore it.
