### ISSUE TITLE
assigning hotkey

### ISSUE THREAD

**Issue by louisVottero** [godotengine/godot#10982]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
latest godot built today, 
**Issue description:**
I assigned w,s,a,d to ui_left, ui_right, ui_up and ui down, but when I ran the game the keys were not working. 

**Steps to reproduce:**
go to project settings, assign D key to ui_left.  close the project reopen. D is no longer assigned. 
Also when you run a project that uses ui_left to trigger an event, it does not pick up. 

**Link to minimal example project:**

**Comment by Noshyaar** [comment]
Duplicate of #10502
