### ISSUE TITLE
Shortcuts for hex colors

### ISSUE THREAD

**Issue by Soaku** [godotengine/godot#10997]
Currently, when specifying colors, we must give 6 or 8 digits (in rrggbb[aa] form).

I suggest that there should be added the shortcut form, just like in html:

- `#abc` is the same as `#aabbcc`
- `#abcd` is the same as `#aabbccdd`

This will make it easier, mostly for grey colors made of the same hex digit, like `#777777`, it's hard to notice if you actually specified 5, 6 or 7 digits. 

Would be really nice if it was added in the next version of Godot Engine.

Thanks!

**Comment by mrawlingst** [comment]
While I might agree with you that it might be difficult to tell how many digits you have entered, I think this isn't really needed. I feel this would cause more inconsistency in the code and less readable (in term of skimming over the code).

It doesn't take too long to count how many digits/letters you typed in or even started over.

**Comment by Soaku** [comment]
@mrawlingst Why would make the code less readable? The 3 digits colors are really easy to read.

Alternatively, you could make Godot color picker automatically convert 3 digit input to 6.

See:

- User types in "abc".
- User clicks "enter"
- Godot counts amount of characters. There are 3, so it just converts it to 6-digit number

I know it is easy to count digits, but still, would make it a bit easier.

**Comment by Soaku** [comment]
oops, closed by accident

**Comment by kitsune** [comment]
Oops I thought I had stated that I would work on this.  Sorry.  Anyway I'm working on it
