### ISSUE TITLE
Idea: Add support for a global event bus [Edit]

### ISSUE THREAD

**Issue by DjPale** [godotengine/godot#10991]
## Signals / Notifications
While the signal-system in Godot works very well in many cases, there is one pattern that I'm personally missing and that is to be able to subscribe globally to signals to receive information without knowing if it will occur or which objects that are emitting it up front. This is more akin to an event system. Godot has some internal notifications that would work - but as far as I know these are predefined and mostly not for use by normal developers.

The idea that you can only connect signals explicitly through object and using 1 slot means that it is not as useful as it could be. I miss a mechanism where you can emit some signals globally and you can connect to a global queue without knowledge of objects - just events.

## Example
An example - I have a set of objects detecting various objects passing through it (like `Area`-triggers) in one scene. I want to know whenever one of the triggers were firing - both passing through them and also as part of general accumulation and updating of UI.

Currently, I see the following solutions to this problem:
1. To iterate through the scene, and connect to these explicitly. But then I consume the signal slot and block it from further access for other objects.
2. In the actual trigger detection - check if the target has a predefined method (`has_method()`) and call it if they have it. But this will imply that you need an object to enter the trigger and possibly route the fnction call further.
3. Other stuff I missed? As mentioned - the notification systems seems mostly like an internal mechanism.

## Solution suggestions
1. Create a special global queue object that everyone connect and emit to - might be messy.
2. Create new functions for this and call them something else - like *Event* or similar.
3. Expand the existing notification functionality to allow user-defined notifications.

## Edit
As pointed out by @Zylann an event bus is more descriptive of what I'm trying to achieve.
* http://timnew.me/blog/2014/12/06/typical-eventbus-design-patterns/
* http://gameprogrammingpatterns.com/event-queue.html

**Comment by BeayemX** [comment]
Sounds like all this could be accomplished by using an AutoLoad. There you could define all the signals you want. 

And regarding 'consume the signal slot', you can connect multiple objects to one signal.

**Comment by Zylann** [comment]
That can also be accomplished with groups, and using `scene_tree.call_group("group", "function", args)`

**Comment by DjPale** [comment]
@BeayemX Does this mean that in 3.0 the signal slots can be connected to by different objects? The 2.1 docs at least states that this is not the case like desribed in the  [API docs](http://docs.godotengine.org/en/stable/classes/class_object.html#class-object-connect), and I've received error messages in 2.1-builds that I'm already connected to signal slot.

I know that you can create custom signals of course - I don't know if I'm explaining my pattern in a bad way, but the pattern you describe would mean that you would need to _find_ each object that emits a given signal in a scene and then connect to each of them - as opposed to subscribing to _one_ global signal / event that all of the object instances would emit.

@Zylann yeah I've thought about groups as well - that could work also. In my case, I would need to register any object that would be interested in notifications in a special group for each scene (and the objects calling the group would need to know this group name also). It would work of course, but it doesn't feel as good as the one I'm describing.

I was not indicating that I would listen to any event / notification, but a custom queue for global events - not sure why that would be a terrible performance sink. 

One example of a game engine that has implemented this exactly the way I'm thinking of is [luxe](https://luxeengine.com/docs/api/luxe/Events.html)

I was looking for this kind of functionality both in Unity3D and Godot, and was a bit surprised I couldn't find a good way to solve this pattern which I thought was common - as it is enabling dependency decoupling without explicitinly connect known objects together. This is of course not a must-have, but just a suggestion. But I might explain this badly as I'm quite sure that this would be a common pattern encountered.

**Comment by kubecz3k** [comment]
Well I think we just should add more tooling around groups. They fit very well to this use case, and there are many ways how you can use them to achieve what you want. 
1. You can combine them with signals, (so emitters are in group), and just connect from listeners like (pseudocode )  `for player in playerGroup: player.connect("signal", self, "method");   `
2. You can use it Zylanns way so you would need to call from inside emitter itself additional stuf via call_group interface like `call_group("PlayerEventListeners" "onPlayerEvent", eventParams")` 

What I think is missing is some tooling around groups, it's hard in bigger project to have better picture on your project groups. I made plugin for that, it's very rough but it's more or less usable  https://youtu.be/inBR5-071ko  However I believe a lot better ideas for such tooling would be welcome.

**Comment by HummusSamurai** [comment]
Perhaps we could have `connect_group("signal","group","method")`

**Comment by kubecz3k** [comment]
Well maybe that's not so bad idea, that kind of  'api sugar' would tell in a very explicit way to the users on how to use groups to achieve what they need...

**Comment by HummusSamurai** [comment]
@kubecz3k We could also allow for connecting to something other than `self`, but this would require something more messy to implement such as `get_group("group_name").connect("signal", self, "method")`.

This brings up the questions of what does the get_group() return? Which is why I against it; the aforementioned 'api sugar' is good enough.

P.S. I also edited the previous post in case you were looking at an older version.

**Comment by groud** [comment]
I don't get why not using a "global" node within your scene that you can register to. 
This node can act as a redirection of other signals.

Breaking the observer pattern looks like a bad idea to me...

**Comment by HummusSamurai** [comment]
@groud I agree that breaking the observer pattern is a messy idea, and a global node is one way to do that.

Yet this is not directly obvious to newcomers (and even I haven't thought of it before) so there should probably be more docs or tutorials about doing this.

**Comment by HummusSamurai** [comment]
So it would go something like this I assume:
`global_emitter.emit()` and `node.connect("signal","method")` (Excuse my bad pseudo-code)

**Comment by Zylann** [comment]
`connect_group` would be bloat because you can do the same with a simple for loop and `scene.get_nodes_in_group()` :/

**Comment by Zireael07** [comment]
@Zylann: I can see the connect_group being used a lot, and the current gdscript approach would be a loop, therefore slower than if we did the loop from c++ side.

**Comment by BeayemX** [comment]
@DjPale You can already connect multiple objects to one signal in 2.1. You can event connect multiple methods within one object to the same signal. The only thing you can't do is connect the same object AND the same method multiple times to one signal.

**Comment by BeayemX** [comment]
@Zireael07 I think `connect_group` is not a good idea because you can only call it once. What if there are different enemies that spawn later in the game but you already called `connect_group` for your enemy group. You can't connect the enemies that are already in the game. So you would have to check for every enemy if it is already connected.

Or what if one enemy wants to stop listening for a short period of time or disconnect? You would have to manage this by the enemy class itself any way.

**Comment by BeayemX** [comment]
Here is a simple code example how I would solve this by simply using a messenger class as AutoLoad:
use this class as Autoload (MenuBar / Scene / ProjectSettings / Autoloads (tab))
```
extends Node
signal message

func send_message(messagetext):
	# here you can do some evaluation
	emit_signal("message", messagetext)
```

and attach this script to any node to be able to communicate with the Messenger

```
extends Node

func _ready():
	Messenger.connect("message", self, "_handle_message")

func _handle_message(messagetext):
	print(get_name(), " received:", messagetext)
	
# trigger this whenever necessary to 
func foo():
	Messenger.send_message("alarm")
```

**Comment by DjPale** [comment]
@BeayemX ok I stand corrected - but I think the docs should be updated:
> A signal can only be connected once to a method, and it will throw an error if already connected. If you want to avoid this, use is_connected to check.

@kubecz3k The problem with `call_group` is that I have to administer groups solely to listen to some events. So it feels a bit redundant. First I have to put my objects in x groups and then connect them as an additional step. 

The `connect_group` also doesn't solve this in a good way as @BeayemX is describing regarding enemies - and the fact that you explicitly connect to object instances. That should be avoided.

The point is that the *broadcasting* entities _should not_ know anything about the objects connecting to them. The *receiving* entity would _only_ announce that it is interested in receiving messages from _any_ entity without explicitly connecting to each one.

So in a proposed solution there would be one line of code from the broadcaster objects:
```broadcast('_portal_object_contact',self,params...)```
Further - the only thing you need in a receiving class would be 
```connect('_portal_object_contact','handler')```

A solution proposed by @BeayemX would work, but there you need to manage explicit connections in the broadcaster object which should be oblivious to any receiving end.

**Comment by BeayemX** [comment]
I think I still don't understand the problem entirely.

Approach 1:
Let's say you want to know exactly which event has happened, you could just define multiple signals inside the global messenger class.
```
signal alarm_triggered
signal enemy_spawned
signal damage_taken
signal season_changed
```
Then you can emit these without an argument `emit_signal("alarm_triggered")`.
Inside your listener class you just connect to the signals you would like to react to.

Approach 2:
You just want one signal and basically listen to every message and choose inside the listener class to react or to ignore it. You can use the code sample from above and use the type as argument

`emit_signal("alarm_triggered")` or 
`emit_signal("enemy_spawned")` or
`emit_signal("damage_taken")` and so on

inside your listener class you would have to check for yourself if you want to react to this signal
```
_handle_message(msg):
    if msg == "alarm_triggered":
        shoot()
    elif msg == "season_changed":
        sleep()
    else:
        print("Unhandled message: ", msg)
```

From what I understand it seems like you want something like approach 2. If not maybe you could give some more concrete examples?

**Comment by DjPale** [comment]
Not really sure what to add here, I think the case is pretty clear. I wan't a complete object instance decoupling and avoid any explicit connection to a custom global class which you are suggesting. In your case the broadcasting objects needs to connect to a predefined global singleton which I'm trying to avoid completely.

I'm basically trying to propose an alternative for creating an intermediate object and `if-else` checks completely. I have also linked to API docs from another engine that support this pattern, so not sure what is unclear. This is a feature proposal, and as I said, I can solve this with very few lines of code if I had an event mechanism like this.

If this is too exotic or if it still doesn't make sense - feel free to close the request.

**Comment by Zylann** [comment]
So if the broadcasting object isn't calling a global instance... where do you think this call will end up?
`broadcast("message", 42)`
There must be an intermediate, a context, a hierarchy, even if you don't see it. There is just no way for this message to go anywhere otherwise. Also, proposals using auto-load or groups aren't using if-else at all.

The three solutions you proposed on your first post are all more or less automated variants of the same thing:  [an event bus](http://timnew.me/blog/2014/12/06/typical-eventbus-design-patterns/) (if we ignore the hierarchical aspect of notifications), which can be done in various ways without having to include it directly in engine imo. If it's still not that... then I don't know :/

**Comment by DjPale** [comment]
@Zylann Yeah, an event bus is a good description actually. I might have messed up the initial discussion a little bit by mixing in signals here. I'll change the original title / description.

In this case, if no one subscribes to an event - it is ignored. So the engine would facility an event bus. Again - it was a suggestion - and a thing that I miss sometimes. But maybe this is not a common pattern that people want to use.

**Comment by mhilbrunner** [comment]
This doesn't need any integration into the engine.

Just implement a pubsub bus as a singleton.

This could be done as example code or a plugin or something, but doesn't need to be in core.

**Comment by mhilbrunner** [comment]
@kubecz3k Vote for closing this.

**Comment by kubecz3k** [comment]
Well it's mostly a discussion... but @DjPale have you resolved your issue?
Also I personally think this would be a great feature for a plugin, maybe someone could volunteer and create one?

**Comment by mhilbrunner** [comment]
Agreed that this would be a great plugin on the AssetLib, but for things in core, the signal and group systems should be enough to build on top of unless there are a lot of people wanting such a feature. Closing for now, as there hasn't been any discussion since november.

**Comment by silkentrance** [comment]
There is an event bus implementation over at https://github.com/Naata/godot-event-bus
