### ISSUE TITLE
Plugin extensibility without having to recompile the engine

### ISSUE THREAD

**Issue by aegarpyke** [godotengine/godot#1099]
I don't know if this is even possible with the infrastructure of Godot but I think it could be a great addition. For example, integrating third-party plugins for ads and IAP without having to modify and rebuild the engine would ease the learning curve a lot. Plus, it would probably accelerate plugin development by community members who aren't skilled with C++ (such as me).

**Comment by Nulifier** [comment]
I was thinking a bit about this and it would be doable to create a plugin system that would for for PC/Mac/Linux using a module that loads dlls and calls a function to register the types. The only complication with this would be requiring the same compiler version.

The major issue arises when dealing with all the other platforms that godot supports; I don't have any experience trying to load dlls on iphone or android and I can imagine this would greatly complicate any attempt at this.

**Comment by reduz** [comment]
yeah it's not that simple with C++ plugins, and the API for GDScript
plugins. Also binary compatibility would be broken quite often in C++.

**Comment by akien-mga** [comment]
I guess this is not happening in the near future.
