### ISSUE TITLE
Broken imported .DAE meshes.

### ISSUE THREAD

**Issue by thewilfen** [godotengine/godot#11004]
**Windows 10, Godot 3.0 master build (54e81c795529a9c35cc045acfb941417cf2b5008), Nvidia GeForce GTX 1050**

**Issue description:**
Imported Collada (from Blender 2.78c) meshes are broken (or just their rendering), everything worked alright in alpha 1 release. If triangulation on export is enabled things look even worse. Sometimes it gets to work properly after reimporting but not always, closing and opening editor again doesn't always help either.

**Screenshot:**
![untitled](https://user-images.githubusercontent.com/1448623/30077350-dc769a84-927b-11e7-929d-aad09400dd7e.png)

**Steps to reproduce:**
1. Export some model in DAE format.
2. Import it as a scene and open it.

**Link to minimal example project:**
[collada.zip](https://github.com/godotengine/godot/files/1278539/collada.zip)

**Comment by reduz** [comment]
I cant reproduce, model looks perfect to me..

**Comment by reduz** [comment]
![image](https://user-images.githubusercontent.com/6265307/32617732-8a322a66-c554-11e7-990b-2d75c10fcc58.png)
