### ISSUE TITLE
Opening a new 3D scene makes the editor camera move to the default position instead of snapping to it

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11008]
**Ubuntu 17.04, Godot build: 6b99950**

**Issue description:**
When opening a scene (be it just created or loading an existent one) in the 3D editor, the editor camera will visibly move to the default position instead of snapping to it. This does not happen when switching to already loaded scenes.

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by YeldhamDev** [comment]
@akien-mga I'm not able to reproduce this anymore, closing it.
