### ISSUE TITLE
[vote]Lines under top menue (theme)

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#11006]
In a recent commit I added/fixed the colored lines under the menu items in the top left.
Sonce there were still code fragments existent for them i though it is a but -> fixed it.
@djrm mentioned that they might not even be that good. I kind of agree. (Because they are kind of unecassary)
**Should i remove them properly in another pr.**

(thums up: YES REMOVE THE LINES, thumbs down: NO, KEEP THE LINES)

**Comment by volzhs** [comment]
what about changing YES -> REMOVE / NO -> KEEP not to confuse :)

**Comment by NathanWarden** [comment]
I personally like the look of the lines.

**Comment by Zylann** [comment]
My subjective experience made me think these lines are useful to show that they are not just labels sitting there, since the uniform background doesn't tell any info (no rectangular shape, it's just the background of the whole editor).

**Comment by djrm** [comment]
@toger5 i dont mind them, but they should respect the border_width setting (something im already doing).

**Comment by toger5** [comment]
@djrm I preferred the look when they were a little bigger. and I think they also should be present all the time, independent if it is turned on or of.
`MIN(border_width, EDSCALE)`

**Comment by mhilbrunner** [comment]
Seems there is no consensus for removing the lines. Closing for now, as there wasn't any discussion since last year. :)
