### ISSUE TITLE
Bouncing/Jittering/Teleporting Collision of KinematicBody2D and StaticBody2D

### ISSUE THREAD

**Issue by Eagle-Faulkner** [godotengine/godot#11018]
**Windows 10 64-bit, Godot version 2.1.3 and 2.1.4, Nvidia GEFORCE 940M**

**Issue description:**
I downloaded a project file, imported it into Godot, and the player kinematicBody2D began to bounce and jitter any time it came into collision with a staticBody2D object.  I expected it to just collide as it normally would on my other computer(which is a Windows 8.1 machine with Godot 2.1.3 and has an Nvidia GEFORCE 640M gaphics card)
The file I used was this:
https://github.com/NathanLovato/Godot-simple-platformer
Here is a recording of the results I get on my Windows 10 machine:
https://drive.google.com/open?id=0B-KAIOlp6xrhNzdUVm5Nb0lmQnc

**Steps to reproduce:**
1)Download the project provided in a link above
2)Import it into Godot
3)Run it to test
4)Flip a coin to see if it'll work on your machine or if your machine will have the same issues as mine

**Link to minimal example project:**
https://github.com/NathanLovato/Godot-simple-platformer

**Comment by Eagle-Faulkner** [comment]
Adjusting the frame rate changes how bad the bounce is.  at 30fps you can bounce out of bounds without even jumping.  at 60fps you get the results I initially had.  at 120fps you start getting more of a vibration than a bounce.  The lower the frame rate the worse the issue.

**Comment by mrcdk** [comment]
Confirmed with lower framerates on my machine: Windows 10 64-bit, Godot 2.1.4, Nvidia GeForce GTX 1070, i7 4770k @ 3.5ghz. At 60 fps is fine.

https://i.imgur.com/gq71mzV.gifv

and it get worse the lower the framerate is

**Comment by Eagle-Faulkner** [comment]
Found a fix!
Project Settings > Physics 2D > Motion Fix(check the box)

**Comment by mrcdk** [comment]
Okay, yeah, it looks like it's enabled by default on new projects now https://github.com/godotengine/godot/pull/9866

**Comment by akien-mga** [comment]
You could make a pull request on https://github.com/NathanLovato/Godot-simple-platformer to enable that parameter :)
Also cc @NathanLovato in case he wants to do it himself.
