### ISSUE TITLE
Editor freeze on importing wav file

### ISSUE THREAD

**Issue by maxim-sheronov** [godotengine/godot#11022]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch linux, master branch

**Issue description:**
If you add some *.wav file to project, engine will reimport it. And stops on it. Only killing of the process can help.

In debug I see, that it take Segmentation fault exception in object.cpp in _predelete() method because of "this" is NULL.
Stacktrace:
Object::_predelete object.cpp:384 at
predelete_handler object.cpp:1774 at
memdelete<GDNativeSingletonDiscover> memory.h:107 at
unregister_gdnative_types register_types.cpp:252 at
unregister_module_types register_module_types.gen.cpp:147 at
Main::cleanup cami.cpp:1714 at
main godot_x11.cpp:55

I think. that something in process of importing wav file brake the engine and it tries to finish process.

**Comment by marcelofg55** [comment]
Happens to you with any wave file? Even a really small one?

**Comment by maxim-sheronov** [comment]
@marcelofg55 Yes, I tried on sound_coin.wav from platformer demo project. It is only 63Kb. And on other files from jsfxr.

**Comment by Sslaxx** [comment]
This has been happening to me too, both on importing and trying to re-import .wav files.
