### ISSUE TITLE
Highlight tabs not working with scene tabs

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11035]
**Ubuntu 17.04, Godot Build: 5666857**

**Issue description:**
Self-explanatory:

![screenshot at 2017-09-06 22-19-13](https://user-images.githubusercontent.com/30739239/30141425-c5df8d72-9351-11e7-8941-3b8152a744b6.png)

**Comment by reduz** [comment]
@djrm

**Comment by toger5** [comment]
fixed with #10900

**Comment by djrm** [comment]
@akien-mga, @groud, @Noshyaar this has been fixed

**Comment by Noshyaar** [comment]
Fixed by #10900
