### ISSUE TITLE
Shader Language 3.0: built-ins question

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#11039]
i'm talking about spatial type vertex shaders here.
there are declared built-ins such as SRC_VERTEX, POSITION, etc. but when i try to read them in the shader, it draws white circle, meaning something went wrong. and i failed to find any usage of those variables in source code (but i'm not very good in c++ tho), so i assume either there is a bug, or they are outputs, but SRC_ means input, right?

and i don't understand in which space VERTEX built-in is. is it camera space or world or may be even model?

i was trying to implement (and last attempts were actually to use working implementations) of atmospheric scattering, and i need to use different positions and directions there, and it always fails (even with working code) drawing pitch black, so i assumed i'm using some vectors in wrong way, because i don't understand what they mean in godot 🙄

**Comment by curly-brace** [comment]
i've decided to try to understand this all myself, but it actually added more questions...
here is the project that i've used. there are comments in shader code, that i don't understand.
https://www.dropbox.com/s/2835wb3rm4qtv65/shader_sides.zip?dl=0

**Comment by curly-brace** [comment]
and also doing `(vec4(0.0, 0.0, 1.0, 1.0) * INV_CAMERA_MATRIX).xyz;` should give a world space camera position, but seems like it gives something alse, because doing `ALBEDO = vec3(dot(that_cam_vec, NORMAL));` in fragment shader produces some strange results

**Comment by curly-brace** [comment]
i've came to a decision that INV_CAMERA_MATRIX only inverts CAMERA_MATRIX but not transposes it, so getting the camera position fails with it.

i've tried using `transpose(inverse(CAMERA_MATRIX))` to multiply zero vector above and it returned a vector containing world camera position.

so i think that may be it is a bug? what this INV_CAMERA_MATRIX can be used for without being transposed first? you can't translate from view space back to world using it.

**Comment by Calinou** [comment]
Is this still an issue in 3.2beta3 or later?

**Comment by Calinou** [comment]
Closing due to lack of response.
