### ISSUE TITLE
Light passes through meshes if another mesh is close

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11034]
**Ubuntu 17.04 Godot Build: 5666857, GeForce 820M**

**Issue description:**
If there is a mesh very close behind the one receiving the light, it will pass through it.

![screenshot at 2017-09-06 22-12-39](https://user-images.githubusercontent.com/30739239/30141264-ad60b5d8-9350-11e7-88d1-3aea8a9da74f.png)

**Comment by Zylann** [comment]
Is this happening with a smaller bias?

**Comment by YeldhamDev** [comment]
The light has the default bias of 0.15.

**Comment by reduz** [comment]
This is normal in shadow mapping, change bias to something that works for you
