### ISSUE TITLE
Script Editor's small spacing issue

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11037]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**
The spacing between the editor and the script/function list is overly thick than it needs to. The editor top also doesn't align with the script list top.

Here is comparison between a few days old build, and a recent one, respectively:

![screenshot at 2017-09-06 22-57-04](https://user-images.githubusercontent.com/30739239/30142990-f4904ef6-9359-11e7-81fb-4d2290b760fc.png)

**Comment by toger5** [comment]
Does anyone know how and when the error got introduced (just curious)

**Comment by Noshyaar** [comment]
Bisection says b606285.

**Comment by djrm** [comment]
yeah, i remember fixing this

**Comment by toger5** [comment]
That makes sense. Yea i though i could get rid of those because they were only for color... My bad there was kore to those styleboxes...

**Comment by volzhs** [comment]
fixed by #11025
