### ISSUE TITLE
"Find next" shortcut in code editor not  working now that F3 is also used to "Open 3D editor

### ISSUE THREAD

**Issue by brunosxs** [godotengine/godot#11042]
**Issue description:**
After the reorganization of the F-Keys shortcuts in godot 2.1.4, F3 for "find next" in code editor doesn't work. Seems like "Open 3D Editor" has priority over it.
When F3 used to open the code editor, "find next" worked fine.

edit: 

Yes you can change the shortcuts, but since F3 is kinda like the "universal" shortcut to "find next" (if we're not talking about vim and other terminal exclusive editors), this seems counter-intuitive.

**Comment by akien-mga** [comment]
Fixed in master already by re-changing the shortcuts..

**Comment by akien-mga** [comment]
Fixed in d47a9a4984.
