### ISSUE TITLE
Crash when create/load project.

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#11043]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 x64 build from 06.09.2017

**Issue description:**
When in project manager create new project windows says that program crashes but editor work fine, and project manager still visible. Its looks like project start twice.
![error](https://user-images.githubusercontent.com/6241034/30153859-abeefbea-93c0-11e7-983e-cfce5edef70e.png)

**Comment by Calinou** [comment]
I can confirm this with a `debug` (or `release_debug`) editor build of commit https://github.com/godotengine/godot/commit/5f0d367fef25b30742ba71f12e339137e02c59ab. Note that here, the project manager doesn't crash with this commit, it just freezes indefinitely.

Backtrace:

![Backtrace from Visual Studio](https://user-images.githubusercontent.com/180032/30155942-88218270-93be-11e7-99a5-bb97e48fe54b.png)

**Comment by mrawlingst** [comment]
I can also confirm this issue. It happened to me twice with same build as sezit's.

**Comment by s0ra** [comment]
Windows 7 also experience this with commit current build d1cb73b.
