### ISSUE TITLE
Can't open (on mac)

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11055]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mac OS X El capitan v10.11.5
GPU: AMD Radeon R9 M390 2048 MB

Same problem on both v2.1.4 and v3.0 alpha1

**Issue description:**
When trying to open Godot, the apps move across on the dock as if allowing a new program on, but then immediately move back again (and nothing further happens). I have gatekeeper to allow applications from anywhere (not just signed devs and app store).

**Steps to reproduce:**
1. Open Godot (or at least try to).

**Comment by Zylann** [comment]
Can you try to open it using the command line and see if any particular message shows?

**Comment by Andev08** [comment]
Ok so I started by following this tutorial:
http://docs.godotengine.org/en/stable/learning/editor/command_line_tutorial.html

I put Godot in a folder in my downloads, and did what the instructions said. 

but I got stuck at the "Running the editor" bit, because nothing was happening when I tried to enter "godot -e"

So I tried this tutorial:
http://www.wikihow.com/Open-Applications-Using-Terminal-on-Mac
and put: open Godot.app -e
_I will just point out here that it doesn't specify that you need to put ".app' at the end, which might be worth adding to the tutorials for people who don't use terminal much like myself?_ 

But it kept trying to open Godot with Textedit, so I tried it without the -e. And it opened Godot? What? And now whenever I open Godot, it's fine. No messages in the command line either.

I haven't restarted since I created this issue, so I have no idea why this fixed it.

Thanks for fixing my problem (for the moment?)! I've no idea what that was about.

**Comment by Zylann** [comment]
`godot -e` won't do anything if you don't have a project yet. You should have used just `godot` to launch it.

**Comment by toger5** [comment]
just as an addition . you also can combine `-e` with `--path` to pass a path to the project directory

**Comment by Andev08** [comment]
Thanks again for the help!
