### ISSUE TITLE
Can't open (Cannot get Proc Address for CreateContextAttribs)

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11054]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7
Godot 3.0 Alpha1

**Issue description:**
It simply doesn't open, I only get the error: "Cannot get Proc Address for CreateContextAttribs"
Screenshot: http://i.imgur.com/T2XqWn4.png 

**Steps to reproduce:**
1. Downloaded "Godot_v3.0-alpha1_win64"
2. Run

**Comment by Calinou** [comment]
What graphics card do you have, and what is the graphics driver version? You can determine your graphics card by pressing <kbd>Windows + R</kbd>, typing in **dxdiag**, accepting the dialog that appears, then switching to the Display tab of the DxDiag window. On laptops with hybrid graphics systems (such as Intel + NVIDIA Optimus), his will display your integrated GPU, not the dedicated GPU. If you are on such a laptop, you can force Godot to run on the dedicated GPU by right-clicking the executable, then choosing the dedicated GPU in the "Run with graphics processor" menu.

**Comment by Andev08** [comment]
Here's what that window shows me:
http://i.imgur.com/awFN9yx.png

It's not an old computer (maybe about a few years or so?), so I hope it would be able to support OpenGL 3.3 (if it's not already installed).

I don't have a "Run with graphics processor" option on the drop down

**Comment by Zireael07** [comment]
Googling seems to suggest the integrated card in a Parallels Display Adapter is a Intel HD 3000, so definitely a sub-par card. No idea how you'd switch cards in such a thing (the exact way to switch to dedicated card depends on the manufacturer)

**Comment by Andev08** [comment]
Parallels is OS virtualising software, so basically it should be half capacity of my mac's card which is:
AMD Radeon R9 M390 2048 MB

I can find that card on the "high end GPUs of 2017" chart of this benchmarking website: https://www.videocardbenchmark.net/high_end_gpus.html so it should be capable of running Godot, even if it is bottlenecked at half capacity.

Although I am noticing it says "32 bit" in the graphics card section, could that be the problem given that this .exe is 64bit? My virtual computer should be running on 64 bit because it has 16gb of RAM.

**Comment by Calinou** [comment]
Virtual machines aren't made to run 3D software at all. Also, you can download Godot builds for macOS, or compile it yourself.

**Comment by Andev08** [comment]
Ah fair enough then. I had a previous topic about the mac version not working for me either but that has been resolved now, so there's no reason to try and use the virtual machine!

Should I mark this as closed then?

**Comment by Calinou** [comment]
> Should I mark this as closed?

I'll mark this as closed. Thanks for your report, it can help other users who might have run into a similar problem. :)

**Comment by dodgyville** [comment]
Running a windows build on linux using wine also gives an error, so I guess the only way to test a windows build is with a windows machine.

```
ARVR: Registered interface: Native mobile
ERROR: ResourceInteractiveLoaderText::open: res://default_bus_layout.tres:1 - Parse Error: Expected '['
   At: scene\resources\scene_format_text.cpp:838
ERROR: ResourceFormatLoader::load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:149
ERROR: ResourceLoader::_load: Method/Function Failed, returning: RES()
   At: core\io\resource_loader.cpp:186
^C0034:fixme:console:CONSOLE_DefaultHandler Terminating process 8 on event 0


```

**Comment by vnen** [comment]
@dodgyville this doesn't seem related to this issue at all. It looks more like you have a corrupted file in the project. If it's really an engine issue you can open a new ticket.

**Comment by hiulit** [comment]
Just passing by to add a possible solution because I also wanted to run Godot 3.5 on a Virtual Box running Windows and I ended up using this DLL https://fdossena.com/?p=mesa/index.frag. You just have to copy it next to your Godot.exe and it works for me :)
