### ISSUE TITLE
"addons" folder should be renamed to "plugins"

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#11065]
**Issue description:**
I know it's quite late for such suggestion, but plugins from 2.x need to be converted by developer to 3.x anyway so maybe it's not too late to consider such change. My reasoning is very subjective so I don't expect for this change to happen, however maybe more users feel similar?

**reasoning:**
 1. "plugins" name seems to better explain function of this folder.
 2. I think 'addons' is very graceful name for very specific usecase:
       + third party loose scenes and scripts
       + scenes and scripts that are used by studio internally across multiple projects

**Comment by razvanc-r** [comment]
I know what you mean but from my point of view there's no difference between addon & plugin. You know what the blender "plugins" folder is called? Yeah addon, not that this is a good argument, but really I'd doubt anyone would put any scene on the addon/plugin "market" without it being customization from the editor, basically making the difference between plugin & addon as you explain it meaningless.

**Comment by toger5** [comment]
I think that blender uses the name addons for those kind of editor extensien in scripting language is a good reason to also use the name addons in godot. I actually would prefer if the common name for plugins chnages to addons...

In general i think there is a little confusion on my side what extension like things there are in godot.
Moduls (obvious: c++ engine code in a seperate directory of the godot source)
Plugins (gd script editor extensions which also allow to crete assets which than can be used in game. But cant modify the exported game. Just simplify the creation of it)
GdNative which is not really an extension. Its just a script. In c++ and c++ has a lot of libraries so its crazy poweful.

Than i heard of some gdnative extension which i dont really know what they do. Extend engine source i think. So like a module without recompiling??

And there was a discussion about a system for modding existing godot exported executables. At least i think i heard of that...

Sry that might not be the perfect place. But i would be very greatfult if someone could summarize all the differnt godot extendibility ideas there are currently. This also might help finding good names for all of them. (although i think there was already spend a lot of thinking on the naming)

**Comment by RodeoMcCabe** [comment]
It makes sense to me. Everything in Godot calls them plugins, except that folder. All the documentation and API uses the word "plugin". So for consistency the folder should also be called plugins.

Just my two cents.

**Comment by levilindsey** [comment]
I agree. Regardless of whether the two words are supposed to mean the same thing, that requires the user knowing that they mean the same thing. Naming these with two different makes it hard for new developers to figure out what's going on, and more likely to give up on using plugins.

**Comment by Calinou** [comment]
> I agree. Regardless of whether the two words are supposed to mean the same thing, that requires the user knowing that they mean the same thing. Naming these with two different words makes it hard for new developers to figure out what's going on, and more likely to give up on using plugins.

The discussion should be continued here: https://github.com/godotengine/godot-proposals/issues/118
