### ISSUE TITLE
Viewport lock and child-select lock buttons should be toggles

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#11079]
It is more conventional and intuitive that the viewport buttons for locking/unlocking nodes and child-selection locking/unlocking nodes are singular toggleable buttons than independent buttons.

This is the current layout:
<img width="317" alt="godot_viewport_icons_current" src="https://user-images.githubusercontent.com/15862731/30234245-5906e712-94c9-11e7-9a39-fa57e1e170c2.PNG">

And this is an example of what it could look like by what I mean by toggleable:
![godot_viewport_icons_modified](https://user-images.githubusercontent.com/15862731/30234273-87e31fa6-94c9-11e7-9038-43b1d1b6c289.png)
(pardon my mediocre graphics skills)

Toggling lock state by clicking the button is also more consistent with toggling lock state by clicking on node lock icons in the Scene panel:
![unlocking_node_from_scene_panel](https://user-images.githubusercontent.com/15862731/30234378-99177b68-94ca-11e7-95f8-930abb7c63ed.gif)

Glancing at the current layout makes it appear as if there are more functions than there actually are, and as we know about good UX, the fewer unnecessary buttons, the more approachable the UI.

**Comment by fracteed** [comment]
+1 Agreed! This same thought occurred to me, the first few times I ever used Godot, and then I just got used to it. Would be a nice little improvement.

**Comment by fracteed** [comment]
@Oranjoose @akien-mga this feature has already been implemented, so this issue can be closed.
