### ISSUE TITLE
SurfaceTool tangent generation

### ISSUE THREAD

**Issue by louisVottero** [godotengine/godot#1108]
Import - 3D Mesh 

turning on generate tangent, normal or smooth shading causes seams at the uv seams.
Work around is to turn off options for tangent, normal, or smooth shading when importing an obj.

**Comment by reduz** [comment]
oooh i think there is a bug in SurfaceTool tangent generation, can you add
hee the broken OBJ file so i can check it and fix it?

**Comment by louisVottero** [comment]
here is a linke to the files

sphere is the default sphere in maya 
https://www.dropbox.com/s/5tipl97xfqalxer/sphere.obj?dl=0

sphere2 is a subdivided cube with more uvs seams.
https://www.dropbox.com/s/7ddca17txlhk4nd/sphere2.obj?dl=0

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?
@reduz The obj files linked above are still available if you want to try to reproduce the bug.

**Comment by reduz** [comment]
good question, I think I fixed it, leave it open so i can test

**Comment by akien-mga** [comment]
Assigning to @reduz who wanted to check with the obj files if the bug is properly fixed.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by bojidar-bg** [comment]
Given that almost a year of "testing" has passed, maybe it is fixed?

**Comment by akien-mga** [comment]
Assuming it's fixed as there were no other reports of issues. Please comment if you can still reproduce it.
