### ISSUE TITLE
Dragging sprite doesn't move bounding rectangle

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#11091]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 latest, RX 480, W7 64-bit

**Issue description:**
![](https://i.gyazo.com/2ac2425f9d1a576f79e0dc560ede4e09.gif)

**Comment by Noshyaar** [comment]
Duplicate of #10936

**Comment by Dillybob92** [comment]
ty @Noshyaar
