### ISSUE TITLE
File heat names in Script Editor are very hard to read.

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#11095]
![selection_010](https://user-images.githubusercontent.com/6152134/30239242-74b7afac-9558-11e7-8d32-e87883271efb.png)

**Comment by Noshyaar** [comment]
Duplicate of #11059

**Comment by n-pigeon** [comment]
Ups.

**Comment by n-pigeon** [comment]
Opening again. Deleted editor settings tres and created new project with new .godot file and colors didn't changed.

**Comment by Noshyaar** [comment]
Can't reproduce. Deleting ~/.godot/editor_settings-3.tres is sufficient for me. Is the engine open while you delete the file?

**Comment by n-pigeon** [comment]
@Noshyaar 
Derp. <(^___^)" Thx. I probably had opened Editor...
