### ISSUE TITLE
Axis caption in spatial editor

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#11094]
**Issue description:**
Maybe this is not a big issue for people with a lot of experience in 3d applications but when working
in the spatial editor, I still often get confused/disoriented about which axis is which and from what direction exactly I'm looking.

When working in blender, I find the little widget in the bottom left corner very helpful to quickly orient myself and know where in 3d space I am positioned and on which axes (an in what direction) i'm currently working.

![axis](https://user-images.githubusercontent.com/7927471/30238750-adcc03ac-954d-11e7-9967-b5c05eeac7b8.png)

I think something similar would be very nice to have in godot's viewport as well.

**Comment by Noshyaar** [comment]
Usually it's R, G, B for X, Y, Z respectively, but I'd also like an arrow or something directional to tell which way is positive/negative.

**Comment by novemberist** [comment]
This is probably a little too non-standard for most people, but how about a gradient on the axis color from light(positive) to dark(negative) color or something similar as a visual helper?

**Comment by toger5** [comment]
@Noshyaar I think the arrow is not necessary since it is already pretty obvious that positive is the direction where the axis is drawn to.

**Comment by Noshyaar** [comment]
@toger5 From the screenshot, yes. But I meant currently in the engine.
