### ISSUE TITLE
Does CollisionShape::resource_changed need to be available in GDScript?

### ISSUE THREAD

**Issue by NathanWarden** [godotengine/godot#11104]
While documenting CollisionShape I noticed this method has a parameter of "RES res" but then it doesn't use it for anything. Should the parameter be removed?

Here is the entire method definition:

```
void CollisionShape::resource_changed(RES res) {

	update_gizmo();
}
```

**Comment by Noshyaar** [comment]
I don't think so. It might be a GDScript binding and if number of parameters doesn't match, it'll print an error message and the method won't be called.

**Comment by NathanWarden** [comment]
Okay, so this particular case isn't a call from C++ into GDScript, but from GDScript into C++. It doesn't make sense for the user to pass in a resource that's then completely ignored. In this case it's seems to make much more sense to remove the binding altogether and just have them call 'update_gizmo' which is also a binding for GDScript.

If this was a call into the user's script it would make sense, but it doesn't look like it is. I'm quite sure 

API breakage is acceptable for Godot 3.0, especially on a method that is likely not used in most cases, right?

GridMap does the exact same thing, but it looks like no other classes in all of Godot do this.

**Comment by Noshyaar** [comment]
In core/resource.cpp:
`obj->call("resource_changed", RES(this));`

I'm not sure. AFAIK, currently nothing uses the given parameter, but in the future things might change. The implementation is very odd however. It'd make more sense if it were a virtual method.

**Comment by NathanWarden** [comment]
After doing some testing, it calls "resource_changed" internally whenever the 'Shape' resource is modified, as expected. If two nodes share the same resource they are both called internally, as expected.

I'm now puzzled as to why this is user API facing?

It seems:

A) Redundant, since it's already called internally when a resource changes
B) Confusing, since the argument passed does nothing in this nor the GridMap node, and effectively does nothing because of point A
C) Something the user should never have to worry about anyway since any change notifications should be recognized internally... which they currently are.

**Comment by Noshyaar** [comment]
Could be useful for making an EditorPlugin? It should be a notification, a signal, or a virtual method though.

**Comment by NathanWarden** [comment]
Thanks for helping me to work through this issue. I'm still getting used to some things about Godot.

I made a pr making these methods virtual in both C++ and the documentation. Even before this pr, if the 'resource_changed' function is added to GDScript it overrides the C++ version, thus acting as if it were virtual. I left the binding so the user can still call back into the C++ version.
