### ISSUE TITLE
Area2D's `get_audio_bus()` is a misnomer

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#11109]
Godot 3.0

Was reviewing documentation for Area2D, and I found the following:

- A C++ property exists called `audio_bus` that holds the StringName of an audio bus associated with the AudioServer singleton.

- C++ methods `get_audio_bus` and `set_audio_bus` act as getter/setter for this C++ property.

- A GDScript property is bound by the name `audio_bus_name` and is given the above getter/setter as its own getter/setter.

This results in `get_audio_bus()` becoming a misnomer since it deals with an audio bus's *name* rather than an audio bus *object*. These methods should probably be renamed to `get_audio_bus_name()` and `set_audio_bus_name(...)`.

**Comment by paezao** [comment]
Hey people should I change the documentation as well?

**Comment by bojidar-bg** [comment]
@paezao Yes, all instances of that function should be renamed 😃 .

**Comment by paezao** [comment]
@bojidar-bg Do I also need to change the docs? How?

**Comment by bojidar-bg** [comment]
@paezao If you don't know, you don't have to bother with the docs. If you really want, you can check the [docs about it](http://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html).

**Comment by Noshyaar** [comment]
Fixed by #11497
