### ISSUE TITLE
get_global_mouse_position() offset when in tool mode

### ISSUE THREAD

**Issue by jansul** [godotengine/godot#11116]
![godotmouse](https://user-images.githubusercontent.com/1927518/30243403-39754286-95a0-11e7-970b-6b7a0f36c3ae.gif)

**Issue description:**
It seems as if the mouse position as reported by get_global_mouse_position() is incorrect when in tool mode. It seems to be offset the same amount regardless of zoom level.

This only happens when in tool mode. When running in game mode the mouse position is correct.
It seems to be related to the position of the game viewport, if you increase the width of the sidebar, the mouse offset also increases.

This is with the Godot_v3.0-alpha1_win64 build. 2.x does not seem to have the same issue.

**Link to minimal example project:**
```python
tool

extends Node2D

func _process(delta):
	update()

func _draw():
	draw_line(Vector2(), get_global_mouse_position() - get_global_position(), Color(1,0,0), 1, true)
```

**Comment by kubecz3k** [comment]
Havent used draw() to much, but I assume it expect points in local cord system (in that case everything seems to work ok when looking at your code and gif).

**Comment by groud** [comment]
This code wont work, draw_line uses the canvas coordinate system while get_global_mouse_position() return the mouse position relative to the viewport. 

Maybe use something like `get_viewport_transform().xform(get_global_mouse_position())` or `get_viewport_transform().affine_inverse().xform(get_global_mouse_position())`

**Comment by jansul** [comment]
Appreciate it might be the intended behavior! However it seems to be different to how Godot 2.x handles it (which tracks the mouse)

![godotmousetool2](https://user-images.githubusercontent.com/1927518/30268173-ca776ed4-96dc-11e7-835f-10be9e44828d.gif)

```python
tool

extends Node2D

func _ready():
	set_process(true)

func _process(delta):
	update()

func _draw():
	draw_line(Vector2(), get_global_mouse_pos() - get_global_pos(), Color(1,0,0), 1)
```

I'll try what you mentioned @groud  :)

**Comment by groud** [comment]
Yes, the API changed. I'm pretty sure this is intended. ;)

**Comment by puppetmaster-** [comment]
Can this be changed back to the 2.x behavior? It seems we losing simplicity.

**Comment by bojidar-bg** [comment]
Well, shouldn't the viewport offset the global_mouse_pos and the positions of the various events using its transform?

**Comment by groud** [comment]
I don't think so, the global_mouse_pos is in the viewport space, thus the camera space.
And I think it makes a lot more sense to have the global mouse position in the camera space, especially in the 3D space. And to me, having two different behaviour for global_mouse_pos in 3D and 2D looks also like a bad idea to me.

**Comment by bojidar-bg** [comment]
1) `get_global_mouse_pos` is a method of CanvasItem. In 3D it just makes no sense.

2. 
    * `get_global_mouse_pos` should result in global coordinates, i.e. coordinates relative to the world's origin.
    * Thus, using `get_global_transform().affine_inverse() * get_global_mouse_pos()` should result in valid local coordinates to the mouse from the given node. Note that in the above example, the node has no transformation applied, so the above expression is equivalent to `get_global_mouse_pos()`.
    * In the example above, it worked well in 2.1.x, but in 3.0 it includes some offset from the viewport's top-left corner.

    IMO, nodes inside a viewport shouldn't care that they are in one, and thus the new behaviour is buggy.

    Note that while it might seem that the global position of the mouse should be counted from the origin of the main viewport, the sub-viewport has its own transform and a separate origin. Everything inside that sub-viewport uses global coordinates relative to that viewport, not to the main viewport.

**Comment by groud** [comment]
Ok why not. Seems like this function is not used often in the code, so changing its behaviour should not break everything.

So I guess Input::get_mouse_position() should return the screen space mouse position then ?

**Comment by bojidar-bg** [comment]
@groud That's correct, since the Input class knows nothing of viewports.

**Comment by groud** [comment]
Ok then it makes sense then, can be marked as a bug ^^

**Comment by Chaosus** [comment]
I have a non-ellegant solution, add this to get_mouse_position
```
	if(Engine::get_singleton()->is_editor_hint())
		return (get_final_transform().affine_inverse() * _get_input_pre_xform()).xform(Input::get_singleton()->get_mouse_position() - _get_window_offset() - Vector2(248, 105));
```
I afraid it is not acceptable, because constant vector offset is not desirable, and I dont know the method which retrieve exact offset from edge of the screen to actual viewport. In 2.1 the _get_window_offset do all the work around it...

**Comment by photex** [comment]
I started to look into this but I'm still getting to know my way around. If I understand correctly, the current behavior is that in the editor the global mouse position is being transformed relative to the viewport bounds in the 2d view. Instead what should happen is that they are *not* transformed in this way when TOOL_MODE is defined.
Is this correct?
At first I thought perhaps that _get_window_offset needs to be reimplemented. It currently just returns an empty transform.

**Comment by bojidar-bg** [comment]
This issue shouldn't be related to tool-mode scripts, but rather to viewports only.
A badly implemented _get_window_offset sounds like a potential culprit indeed.
