### ISSUE TITLE
Spotlight gizmo forward vector is the same as editor camera forward vector

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#11110]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux, d1cb73b47a17de830d9474026ffa7b3587cfbc68

**Issue description:**
I noticed that gizmo of spotlight acts in a very weird fashion, it looks like spotlight gizmo is mimicking editor camera:
![spotlight_gizmo](https://user-images.githubusercontent.com/6129594/30241712-26663144-9589-11e7-9db1-60feadb00536.gif)

**Steps to reproduce:**
1. Open new scene
2. Add `SpotLight` node to the scene
3. Ensure `SpotLight` node is selected
4. Rotate camera

**Comment by djrm** [comment]
duplicate of #10706

**Comment by bojidar-bg** [comment]
Yes indeed. Closing as duplicate of #10706.
