### ISSUE TITLE
UX: don't offset the whole script editor when search just opens

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11114]
Godot 3.0 master

When I use Ctrl+F to use incremental search, it makes this panel appear on top:

![image](https://user-images.githubusercontent.com/1311555/30243105-06290d06-95a3-11e7-9a2a-5b8db58761f9.png)

But this offsets all lines down, and sometimes also searches first occurrence immediately, which I didn't expect:
https://www.youtube.com/watch?v=mTwckJRsin0&feature=youtu.be
(all I do in this video is pressing Ctrl+F)

Would it be possible to keep lines where they are when this opens, treat this panel like an "overlay"?
Also start the search only when the Enter key is pressed? It would be a good UX improvement.

**Comment by toger5** [comment]
the panel is in a vBoxContainer WITH the code_editor... So hiding it and showing it resizes both of them. It would be possible to overlay... BUT than it would be impossible to scroll to the top.
maybe it could scroll up by the height of that panel (taking EDSCALE into account)

**Comment by Zylann** [comment]
For reference, here is how it looks like in other editors. None of them scroll until Enter is pressed:

QtCreator:
![image](https://user-images.githubusercontent.com/1311555/30243252-0f63ee42-95a6-11e7-92c3-a0d6866cc3f2.png)

Notepad++:
![image](https://user-images.githubusercontent.com/1311555/30243255-150d4438-95a6-11e7-8a36-0e7d865fbdde.png)

Sublime Text:
![image](https://user-images.githubusercontent.com/1311555/30243260-3d4fec16-95a6-11e7-8c1a-a53280a994cd.png)

Visual Studio:
![image](https://user-images.githubusercontent.com/1311555/30243264-41d037dc-95a6-11e7-918f-f58e64887734.png)

Visual Studio Code:
![image](https://user-images.githubusercontent.com/1311555/30243285-9f9bad9c-95a6-11e7-9e48-581f8976672f.png)

**Comment by toger5** [comment]
Putting it at the bottom would be the simplest solution i think!
Top right would not fit with the overall godot design IMO.
