### ISSUE TITLE
Color has no math operators

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11129]
Godot 3.0 master

In GDScript, adding two colors together results in an erorr:
![image](https://user-images.githubusercontent.com/1311555/30244664-dea6cd02-95c2-11e7-9eb3-b32a1672d970.png)

It also doesn't have operators for `-`, `*` and `/`.

I think there should be the same operators for colors as if they were vectors, simply doing components memberwise. my current workaround is to do all components manually...
I know there is `blend`, but my current use case really is about adding or multiplying colors.

**Comment by SolarLune** [comment]
Agreed 100%.

**Comment by rcmz** [comment]
Is somebody working on it ? I may give it a try

**Comment by bojidar-bg** [comment]
@rcmz As far as I can tell, nobody is working on it. Feel free to ask for pointers on the #godotengine-devel channel on freenode (IRC), or on the Godot Engine Discord server.

**Comment by bncastle** [comment]
Sorry @rcmz I didn't see your comment until after I'd already started. I've implemented a first stab at it and am testing the changes now.

**Comment by rcmz** [comment]
Nice ! I'm struggling  x)

**Comment by bncastle** [comment]
Yeah I hear you. I have a first cut at the class functions done, but now I'm trying to figure out how to get GDScript to "see" them.

**Comment by rcmz** [comment]
Keep on the good work ;p

**Comment by toger5** [comment]
@bncastle i looked at your pr. looks good ;)
are you also doing gdnative support ? im not sure how that works anyways? seems like the color class is jst reimplemented in the cpp bindings on the gd native repo. so maybe need to do a pr there...

**Comment by bncastle** [comment]
@toger5 Thanks :) This PR adds support for GDScript only. I'm not sure how GDNative works myself. I agree it should probably be in another PR.

**Comment by Kibouo** [comment]
If not a PR in GDNative, at least an issue might help so it doesn't go forgotten?

**Comment by Elinvention** [comment]
I think this issue can be closed because the PR was merged.

**Comment by akien-mga** [comment]
Fixed by #11176.
