### ISSUE TITLE
Mouse-over variable values are still shown after debugging session finished

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11128]
Godot 3.0 master
Windows 10 64 bits

I started a debugging session and once on an error or breakpoint I was able to see the values in variables by moving my mouse over them in the script editor, which is expected.

However, when I stopped the debugger and moved my mouse over variables, these tooltips are still shown, which isn't expected.

**Comment by bojidar-bg** [comment]
Can confirm since before 2.1 😃

**Comment by DualMatrix** [comment]
Could not reproduce in master

**Comment by akien-mga** [comment]
Closing as fixed.
