### ISSUE TITLE
Cannot pause script debugger in an infinite loop

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11126]
Godot 3.0 master
Windows 10 64 bits

I found it's not possible to pause a debugging session if the game is in an infinite loop. It was possible in 2.1.3, but in 3.0 it just hangs forever.

Tested on this:
```gdscript
extends Node

func _process(delta):
    while true:
        pass
```

**Comment by poke1024** [comment]
I cannot reproduce this, in fact it works fine for me with current master:

<img width="743" alt="pause" src="https://user-images.githubusercontent.com/11859538/34649232-05db693c-f3ab-11e7-8493-150fe0c55529.png">


However, I came upon a different problem that randomly broke debugger pause. Maybe that was the cause of this issue.
