### ISSUE TITLE
Script editor: Ctrl+click doesn't work on static functions

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11124]
Godot 3.0 master

Ctrl+click on a function call makes the script editor go to that function. It works on member functions, but as soon as the function is declared as `static`, it doesn't work and nothing happen.

Works:
```gdscript
func foo():
    pass

func bar():
    foo() # Ctrl+click leads to foo
```

Doesn't work:
```gdscript
static func foo():
    pass

func bar():
    foo() # Ctrl+click doesn't do anything
```

**Comment by HummusSamurai** [comment]
I did not Ctrl + Click did that! TIL!

**Comment by KoBeWi** [comment]
Seems to work in 3.1.1, even across scripts.

**Comment by akien-mga** [comment]
Closing as fixed.
