### ISSUE TITLE
Submenu size in animation editor

### ISSUE THREAD

**Issue by Jbat1Jumper** [godotengine/godot#1112]
There is a small UI issue on the Call Func Track keyframe editor. It doesn't scale well when you have 2 arguments. It seems that the threshold of the scroll bar it's missed by some pixels.

![godotissue](https://cloud.githubusercontent.com/assets/2244403/5606234/2b1cf54e-9404-11e4-96a4-92de4d15b4b7.PNG)

It's only a little detail but the greatest things are made of little details :)

**Comment by akien-mga** [comment]
There has been some rework done on the animation editor for 1.1 or 2.0 I'm not sure, but at any rate I don't manage to reproduce this issue in the current master branch (commit dde6396).
