### ISSUE TITLE
Compiling under OS X 10.10 fails

### ISSUE THREAD

**Issue by philiplb** [godotengine/godot#1113]
Hi,

I freshly forked Godot at commit f39473ae7adf11e16b2a7aae2f84764a3225752b, cloned and tried to compile via
scons platform=osx

scons is installed via Brew and has the version 2.3.4, OS X is at 10.10.

This is the error I get:

g++ -o bin/godot.osx.tools.32 -arch i386 -framework Cocoa -framework OpenGL -framework AGL -framework AudioUnit -lz platform/osx/os_osx.osx.tools.32.o platform/osx/godot_main_osx.osx.tools.32.o platform/osx/audio_driver_osx.osx.tools.32.o platform/osx/sem_osx.osx.tools.32.o main/libmain.osx.tools.32.a modules/libmodules.osx.tools.32.a bin/tests/libtests.osx.tools.32.a drivers/libdrivers.osx.tools.32.a drivers/libdrivers0.osx.tools.32.a drivers/libdrivers1.osx.tools.32.a drivers/libdrivers2.osx.tools.32.a drivers/libdrivers3.osx.tools.32.a tools/libtool.osx.tools.32.a tools/freetype/libfreetype_builtin2.osx.tools.32.a tools/freetype/libfreetype_builtin1.osx.tools.32.a scene/libscene.osx.tools.32.a servers/libservers.osx.tools.32.a core/libcore.osx.tools.32.a -lpthread
Undefined symbols for architecture i386:
  "_ABGRToUVRow_NEON", referenced from:
      _ABGRToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ABGRToYRow_NEON", referenced from:
      _ABGRToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGB1555ToARGBRow_NEON", referenced from:
      _ARGB1555ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGB1555ToUVRow_NEON", referenced from:
      _ARGB1555ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _ARGB1555ToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGB1555ToYRow_NEON", referenced from:
      _ARGB1555ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _ARGB1555ToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGB4444ToARGBRow_NEON", referenced from:
      _ARGB4444ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGB4444ToUVRow_NEON", referenced from:
      _ARGB4444ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _ARGB4444ToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGB4444ToYRow_NEON", referenced from:
      _ARGB4444ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _ARGB4444ToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBAddRow_NEON", referenced from:
      _ARGBAdd in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _ARGBAddRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBAttenuateRow_NEON", referenced from:
      _ARGBAttenuate in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _ARGBAttenuateRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBBlendRow_NEON", referenced from:
      _GetARGBBlend in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
  "_ARGBMirrorRow_NEON", referenced from:
      _ARGBMirror in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
  "_ARGBMultiplyRow_NEON", referenced from:
      _ARGBMultiply in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _ARGBMultiplyRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBSetRows_NEON", referenced from:
      _ARGBRect in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
  "_ARGBSubtractRow_NEON", referenced from:
      _ARGBSubtract in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _ARGBSubtractRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToARGB1555Row_NEON", referenced from:
      _ARGBToARGB1555Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToARGB4444Row_NEON", referenced from:
      _ARGBToARGB4444Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToBayerGGRow_NEON", referenced from:
      libyuv::ARGBSobelize(unsigned char const*, int, unsigned char*, int, int, int, void (*)(unsigned char const*, unsigned char const*, unsigned char*, int)) in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _ARGBToBayerGGRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToBayerRow_NEON", referenced from:
      _ARGBToBayerRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToRAWRow_NEON", referenced from:
      _ARGBToRAWRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToRGB24Row_NEON", referenced from:
      _ARGBToRGB24Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToRGB565Row_NEON", referenced from:
      _ARGBToRGB565Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToUV411Row_NEON", referenced from:
      _ARGBToUV411Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToUV422Row_NEON", referenced from:
      _ARGBToUV422Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToUV444Row_NEON", referenced from:
      _ARGBToUV444Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToUVJRow_NEON", referenced from:
      _ARGBToUVJRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToUVRow_NEON", referenced from:
      _ARGBToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _ARGBToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToYJRow_NEON", referenced from:
      _ARGBToYJRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ARGBToYRow_NEON", referenced from:
      _ARGBToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _ARGBToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_BGRAToUVRow_NEON", referenced from:
      _BGRAToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_BGRAToYRow_NEON", referenced from:
      _BGRAToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_CopyRow_NEON", referenced from:
      _CopyPlane in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _Q420ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      libyuv::CopyPlane2(unsigned char const*, int, int, unsigned char*, int, int, int) in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _CopyPlane in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _Q420ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      libyuv::CopyPlane2(unsigned char const*, int, int, unsigned char*, int, int, int) in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
  "_I400ToARGBRow_NEON", referenced from:
      _I400ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I411ToARGBRow_NEON", referenced from:
      _I411ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToABGRRow_NEON", referenced from:
      _I422ToABGR in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _I422ToABGRRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToARGB1555Row_NEON", referenced from:
      _I422ToARGB1555Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToARGB4444Row_NEON", referenced from:
      _I422ToARGB4444Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToARGBRow_NEON", referenced from:
      _I420ToARGB in libdrivers2.osx.tools.32.a(convert_from.osx.tools.32.o)
      _I420ToBayer in libdrivers2.osx.tools.32.a(format_conversion.osx.tools.32.o)
      _I420ToARGB in libdrivers2.osx.tools.32.a(convert_from.osx.tools.32.o)
      _I420ToBayer in libdrivers2.osx.tools.32.a(format_conversion.osx.tools.32.o)
      _I422ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToBGRARow_NEON", referenced from:
      _I422ToBGRA in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _I422ToBGRARow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToRAWRow_NEON", referenced from:
      _I422ToRAWRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToRGB24Row_NEON", referenced from:
      _I422ToRGB24Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToRGB565Row_NEON", referenced from:
      _I422ToRGB565Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToRGBARow_NEON", referenced from:
      _I422ToRGBA in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _I422ToRGBARow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToUYVYRow_NEON", referenced from:
      _I422ToUYVYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I422ToYUY2Row_NEON", referenced from:
      _I422ToYUY2Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_I444ToARGBRow_NEON", referenced from:
      _I444ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_InterpolateRow_NEON", referenced from:
      _ARGBInterpolate in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _ScalePlaneBilinearDown in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
      _ScalePlaneBilinearUp in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
      _ScalePlaneVertical in libdrivers2.osx.tools.32.a(scale_common.osx.tools.32.o)
      _InterpolateRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
      _ARGBInterpolate in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _ScalePlaneBilinearDown in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
      _ScalePlaneBilinearUp in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
      _ScalePlaneVertical in libdrivers2.osx.tools.32.a(scale_common.osx.tools.32.o)
      _ARGBInterpolate in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _ScalePlaneBilinearDown in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
      _ScalePlaneBilinearUp in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
      _ScalePlaneVertical in libdrivers2.osx.tools.32.a(scale_common.osx.tools.32.o)
  "_MergeUVRow_NEON", referenced from:
      _I420ToNV12 in libdrivers2.osx.tools.32.a(convert_from.osx.tools.32.o)
      _MergeUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_MirrorRow_NEON", referenced from:
      _MirrorPlane in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
  "_NV12ToARGBRow_NEON", referenced from:
      _NV12ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_NV12ToRGB565Row_NEON", referenced from:
      _NV12ToRGB565Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_NV21ToARGBRow_NEON", referenced from:
      _NV21ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_NV21ToRGB565Row_NEON", referenced from:
      _NV21ToRGB565Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RAWToARGBRow_NEON", referenced from:
      _RAWToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RAWToUVRow_NEON", referenced from:
      _RAWToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _RAWToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RAWToYRow_NEON", referenced from:
      _RAWToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _RAWToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RGB24ToARGBRow_NEON", referenced from:
      _RGB24ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RGB24ToUVRow_NEON", referenced from:
      _RGB24ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _RGB24ToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RGB24ToYRow_NEON", referenced from:
      _RGB24ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _RGB24ToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RGB565ToARGBRow_NEON", referenced from:
      _RGB565ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RGB565ToUVRow_NEON", referenced from:
      _RGB565ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _RGB565ToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RGB565ToYRow_NEON", referenced from:
      _RGB565ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _RGB565ToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RGBAToUVRow_NEON", referenced from:
      _RGBAToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_RGBAToYRow_NEON", referenced from:
      _RGBAToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_ScaleRowDown2Box_NEON", referenced from:
      libyuv::ScalePlaneDown2(int, int, int, int, int, int, unsigned char const*, unsigned char*, libyuv::FilterMode) in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
  "_ScaleRowDown2_NEON", referenced from:
      libyuv::ScalePlaneDown2(int, int, int, int, int, int, unsigned char const*, unsigned char*, libyuv::FilterMode) in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
  "_ScaleRowDown34_0_Box_NEON", referenced from:
      libyuv::ScalePlaneDown34(int, int, int, int, int, int, unsigned char const*, unsigned char*, libyuv::FilterMode) in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
  "_ScaleRowDown34_1_Box_NEON", referenced from:
      libyuv::ScalePlaneDown34(int, int, int, int, int, int, unsigned char const*, unsigned char*, libyuv::FilterMode) in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
  "_ScaleRowDown34_NEON", referenced from:
      libyuv::ScalePlaneDown34(int, int, int, int, int, int, unsigned char const*, unsigned char*, libyuv::FilterMode) in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
  "_ScaleRowDown38_2_Box_NEON", referenced from:
      libyuv::ScalePlaneDown38(int, int, int, int, int, int, unsigned char const*, unsigned char*, libyuv::FilterMode) in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
  "_ScaleRowDown38_3_Box_NEON", referenced from:
      libyuv::ScalePlaneDown38(int, int, int, int, int, int, unsigned char const*, unsigned char*, libyuv::FilterMode) in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
  "_ScaleRowDown38_NEON", referenced from:
      libyuv::ScalePlaneDown38(int, int, int, int, int, int, unsigned char const*, unsigned char*, libyuv::FilterMode) in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
  "_ScaleRowDown4Box_NEON", referenced from:
      libyuv::ScalePlaneDown4(int, int, int, int, int, int, unsigned char const*, unsigned char*, libyuv::FilterMode) in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
  "_ScaleRowDown4_NEON", referenced from:
      libyuv::ScalePlaneDown4(int, int, int, int, int, int, unsigned char const*, unsigned char*, libyuv::FilterMode) in libdrivers2.osx.tools.32.a(scale.osx.tools.32.o)
  "_SetRow_NEON", referenced from:
      _SetPlane in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
  "_SobelRow_NEON", referenced from:
      _ARGBSobel in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
  "_SobelToPlaneRow_NEON", referenced from:
      _ARGBSobelToPlane in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
  "_SobelXRow_NEON", referenced from:
      libyuv::ARGBSobelize(unsigned char const*, int, unsigned char*, int, int, int, void (*)(unsigned char const*, unsigned char const*, unsigned char*, int)) in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
  "_SobelXYRow_NEON", referenced from:
      _ARGBSobelXY in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
  "_SobelYRow_NEON", referenced from:
      libyuv::ARGBSobelize(unsigned char const*, int, unsigned char*, int, int, int, void (*)(unsigned char const*, unsigned char const*, unsigned char*, int)) in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
  "_SplitUVRow_NEON", referenced from:
      libyuv::X420ToI420(unsigned char const*, int, int, unsigned char const*, int, unsigned char*, int, unsigned char*, int, unsigned char*, int, int, int) in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _SplitUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_UYVYToARGBRow_NEON", referenced from:
      _UYVYToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_UYVYToUV422Row_NEON", referenced from:
      _UYVYToI422 in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _UYVYToUV422Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_UYVYToUVRow_NEON", referenced from:
      _UYVYToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _UYVYToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_UYVYToYRow_NEON", referenced from:
      _UYVYToI422 in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _UYVYToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _UYVYToI422 in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _UYVYToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _UYVYToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_YToARGBRow_NEON", referenced from:
      _YToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_YUY2ToARGBRow_NEON", referenced from:
      _YUY2ToARGBRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_YUY2ToUV422Row_NEON", referenced from:
      _YUY2ToI422 in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _Q420ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _YUY2ToI422 in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _Q420ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _YUY2ToUV422Row_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_YUY2ToUVRow_NEON", referenced from:
      _YUY2ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _YUY2ToUVRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
  "_YUY2ToYRow_NEON", referenced from:
      _YUY2ToI422 in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _Q420ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _YUY2ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _YUY2ToI422 in libdrivers2.osx.tools.32.a(planar_functions.osx.tools.32.o)
      _Q420ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _YUY2ToI420 in libdrivers2.osx.tools.32.a(convert.osx.tools.32.o)
      _YUY2ToYRow_Any_NEON in libdrivers2.osx.tools.32.a(row_any.osx.tools.32.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.osx.tools.32] Error 1
scons: building terminated because of errors.

**Comment by rraallvv** [comment]
What is the output of 'g++ --version' on the terminal?

**Comment by philiplb** [comment]
g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

**Comment by philiplb** [comment]
XCode is 6.1.1

**Comment by rraallvv** [comment]
I've send a PR with this

**Comment by philiplb** [comment]
Confirming that the fix in the PR works for me. :) Successfully compiled.

**Comment by reduz** [comment]
need to ask the port author (ariel) about the PR, then merging

**Comment by tonymtbird** [comment]
confirm: the above pull request seems to fix this issue.

**Comment by tonymtbird** [comment]
Seems to be fixed with current build, can close this and related issues as far as I am concerned.
