### ISSUE TITLE
Error log becomes unusable when it has many lines

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11132]
Godot 3.0 master

One of my projects produced a lot of errors (1428), and I noticed the error list becomes extremely slow when I scroll down, even though only a few entries (10) are drawn.

Clicking items in it also becomes very slow, I have to wait a few seconds before I can see the call stack.

![image](https://user-images.githubusercontent.com/1311555/30244807-fbf99b7a-95c5-11e7-9712-a87ba6af0b89.png)

**Comment by bojidar-bg** [comment]
Can confirm.

**Comment by qarmin** [comment]
Seems like this is fixed in master because with 3000 errors, opening script or call  stack take max 0.5s on my computer

**Comment by Calinou** [comment]
Closing per @qarmin's comment.
