### ISSUE TITLE
Generic6DOFJoint broken

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#11131]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot since merge https://github.com/godotengine/godot/pull/7426

**Issue description:**

 I was trying to port a project from 2.1 to 3 and I realized that the generic 6DOF joint isn't working, everything gets unstable, so I started tracking down the regression.
In this branch (https://github.com/m4nu3lf/godot/tree/bugfix/physics) it was working, so by rebuilding tons of different commits I've been able to find where things broke, and it is... just after the merge of the branch (https://github.com/godotengine/godot/pull/7426)!
Diffing the physics server I couldn't see any major change before and after the merge so... long story short, the bug is in the Matrix3 and/or Transform classes. Not sure if the conventions have been changed without updating the physics engine, but if I revert just those 2 files to before the merge (fixing just a few compilation errors) everything works again

**Steps to reproduce:**
Create 2 rigid bodies and join them with a Generic6DOFJoint with angular constraints

**Comment by m4nu3lf** [comment]
I think I've found the problem, angular velocities are integrated in the opposite direction in the body_sw.cpp file!
This is because the convention for creating a rotation matrix has changed from rotating the frame to rotating the object
`	if (ang_vel!=0.0) {
		Vector3 ang_vel_axis = total_angular_velocity / ang_vel;
		Matrix3 rot( ang_vel_axis, -ang_vel*p_step ); // here there shouldn't be any negative sign
		Matrix3 identity3(1, 0, 0, 0, 1, 0, 0, 0, 1);
		transform.origin += ((identity3 - rot) * transform.basis).xform(center_of_mass_local);
		transform.basis = rot * transform.basis;
		transform.orthonormalize();
	}
`

**Comment by m4nu3lf** [comment]
I've been able to trace the problem to this line in this PR (https://github.com/godotengine/godot/pull/7802/files#diff-0ea026dad30555eee252062a9a5bd5bcL300)
It looks like the function to get the Euler angles is not quite the same, by reverting it the Generic6DOFJoint is working again

**Comment by Zireael07** [comment]
Thinking, maybe this is the ultimate cause of #9254? (Bullet physics PR changed nothing in the vehicle implementation itself and using Bullet fixes the issue, and the vehicle uses a joint, too)

**Comment by m4nu3lf** [comment]
@Zireael07 if it uses the same tipe of joint it is very likely
