### ISSUE TITLE
[3.0] Using extends as an operator no longer works

### ISSUE THREAD

**Issue by Smellyhobo101** [godotengine/godot#11143]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Bug exists on [Godot-Windows-x86_64-2017-09-08.519b933](https://bintray.com/calinou/godot/editor/2017-09-08.519b933#files) and 3.0 alpha 1. 

**Issue description:**
The code `self extends Node` will give the error `Expected end of statement after expression.`. This worked in 2.1.3

**Comment by Noshyaar** [comment]
Use `is`.

`if self is Node:`

**Comment by Smellyhobo101** [comment]
Thanks.

**Comment by Noshyaar** [comment]
Please close the issue if it is resolved.
