### ISSUE TITLE
unable to update "Export Template is missing" 

### ISSUE THREAD

**Issue by karthikthanikai** [godotengine/godot#11157]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu, 3.0-alpha

**Issue description:**

i try to update the export template for android, even after i update the custom build android apk i am getting the message 'export template missing' and Export button is not activated

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Calinou** [comment]
Export templates downloading (from the editor) is not yet implemented (in 3.0 alphas, that is).

**Comment by willt** [comment]
@karthikthanikai When @Calinou  gets the export templates automagically building for android development snapshot builds will be available here https://bintray.com/calinou/godot/editor
Until then you can download them from here: https://downloads.tuxfamily.org/godotengine/3.0/alpha1/

**Comment by akien-mga** [comment]
See #6687.
