### ISSUE TITLE
Color has no HSV / HSL Capabilities

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#11156]
The Color class is lacking in Hue, Saturation, and Brightness / Value controls. It's not a huge deal, but controlling HSV is (in my opinion) way more intuitive and usable when compared to directly dealing with RGB values.

**Comment by djrm** [comment]
color actually has HSV mode, using set_hsv and get_h, get_s, and get_v

**Comment by SolarLune** [comment]
Eh? It's not there in the docs:

http://docs.godotengine.org/en/stable/classes/class_color.html?highlight=Color

Are you talking about 3.0, or was it added after the last release?

**Comment by djrm** [comment]
@SolarLune at least the parameters are there, h,s,v, read carefully the Member variables section

**Comment by SolarLune** [comment]
Ah, OK, I must have missed that looking for a method to create a Color with HSV. Thanks!
