### ISSUE TITLE
Some resource_queue.gd issues in 3.0

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#11169]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 latest compiled

**Issue description:**
I'm using the latest resource_queue.gd from the latest docs: 
http://docs.godotengine.org/en/latest/learning/features/misc/background_loading.html

W/o touching anything and following the step by step guide, you get:
![](https://images-ext-1.discordapp.net/external/RCerHoVwlrc0vcEvZcvm5P46WxvYQ9TAbUKRR6QIQ4s/https/i.gyazo.com/2c8f23c7acb9bc4988e7c0a2ef9d8da1.png)

`Parser Error: Identifier not found: VS`

However, if you remove that line, the thing actually works. Except..when you do `get_progress` it will return:
`-nan(ind)`

So prob not a good idea to do that lol, and I don't know if that line is a correlation to the `-nan(ind)` issue

**Comment by Noshyaar** [comment]
Previously, Godot had shortcuts for servers. `AS` for AudioServer. `VS` for VisualServer. etc. This is deprecated. `VS.flush()` probably is an obsolete version of `VisualServer.force_draw()`?

BTW, that tutorial is very old and not up to date. New tutorials are being written.

**Comment by Zireael07** [comment]
@Noshyaar do you have an up-to-date tutorial on background loading, then?

**Comment by Noshyaar** [comment]
No. I think @NathanLovato is working on the new tutorials. Not sure if Background Loading is in the list.

**Comment by Dillybob92** [comment]
Tutorial was re-written and the newly modified resources_queue.gd was updated in July though, so I figured it'd be okay to follow (they changed `extends` to `is`) in the if conditions

 
I used `VisualServer.flush()` and it works but the `-nan(ind)` is still there

Also. What's the difference between this and the 3.0 thread example? This resource_queue.gd gives us the ability to use `get_progress` is the only main difference? I think there should be a doc about maybe the differentiality between this if I'm mistaken, not really sure

**Comment by NathanLovato** [comment]
Background Loading's not on the list for now - it'd make for a short tut, maybe somebody else can take care of it in an upcoming sprint. Here's what we're working on with Chris: https://trello.com/b/BxdbFCzL/godot-30-docs

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
