### ISSUE TITLE
Expand Margin for StyleBoxTexture clips box, but only with a Tree node?

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#11166]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot_v3.0-alpha1_win64.exe.zip 
and
Godot 2.1.4

**Issue description:**
![tree](https://user-images.githubusercontent.com/10387670/30261565-1b25b832-9682-11e7-9c19-7d1d6d9f67d4.PNG)

For some reason when using the `Bottom` property under Expand Margin in a StyleBoxTexture, it cuts off the bottom part of the StyleBox. And what's even more odd, it only happens when using a `Tree` node. It works perfectly fine under a Panel node and other nodes that let you use a custom `StyleBoxTexture`

In the image, the left is the tree and the right is the panel. Both using the same StyleBoxTexture.

I dug a bit deeper but got lost in the C++ code
# Tree.cpp
https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L2774

This line looks like it's using almost  the same code as panel.cpp.

However it has this before the actual draw method is called:
```
Point2 draw_ofs;
draw_ofs += bg->get_offset();
Size2 draw_size = get_size() - bg->get_minimum_size();
```

**_Except_**  --- `draw_ofs` and `draw_size` is not being used in:
`bg->draw(ci, Rect2(Point2(), get_size()));` 

# Panel.cpp
https://github.com/godotengine/godot/blob/master/scene/gui/panel.cpp#L35

It looks like the same code is used the only difference I see is it's using the word "bg" instead  "panel", but that doesn't matter, right?

Why is the clip happening and where is it coming from? I'm stumped :(

**Comment by bojidar-bg** [comment]
Maybe, it happens because of this line?
https://github.com/godotengine/godot/blob/c1b31aeb942efda33b1ae9617d89d9275e9f6fd6/scene/gui/tree.cpp#L3730

**Comment by Dillybob92** [comment]
Nice catch!! I disabled it, but now the contents don't get clipped when scrolling
![](https://i.gyazo.com/31f95942622108dadaee2048bdbde648.png)

However, it's enabled by default for good reason it's just the stylebox margins get clipped too, maybe that's not intended / root cause?

**Comment by Dillybob92** [comment]
Okay so the issue is basically when enabling the clip contents property, it overrides and clips your StyleBoxTexture Expand Margin values

That is not intended, right?

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
