### ISSUE TITLE
Edit render priority

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#11162]
`Render Priority` functionality was introduced some time ago, but currently it can not be edited or set from UI
It just displays `<null>` for any values and dont allows set values

![image](https://user-images.githubusercontent.com/3992195/30258929-aa09a3e6-96e7-11e7-8741-3c90ac239fb1.png)

**Comment by bojidar-bg** [comment]
Guess someone should change `Variant::OBJECT` to `Variant::INT` here?

https://github.com/godotengine/godot/blob/308a6f4f99a5204682a2612d097e5c066f88196f/scene/resources/material.cpp#L83
