### ISSUE TITLE
FileSystem tiny click space bug

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#11165]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 latest compiled

**Issue description:**
There is a tiny little space between the items where if you click it doesn't register
![](https://i.gyazo.com/07babe4d8d386a1e1b8efaea597c5bfd.gif)

It actually misses the adjacent ones and deselects the item

how it should be:
![](https://i.gyazo.com/7c631d4683399be722c0f8eb635f7c3e.gif)

notice the no deselection (i'm spam clicking in the gifs)

win 7, 64-bit if that matters :D

**Comment by AlexHolly** [comment]
Can you try again on master? I can't reproduce it.

**Comment by Dillybob92** [comment]
@AlexHolly Tested on master right now

![](https://i.gyazo.com/73256a0fbebe0b76cef5e0b8e95f91ed.gif)

Seems like it's fixed!!
