### ISSUE TITLE
Restore previously opened scenes when opening a project

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#11179]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
win7 x64 godot 2.1.3 editor

**Proposal:**
When I close the editor and reopen it,the window of the scenes or script editor will be reset.
Can you fix it to resume the window since I last quit.
That feels better and quick access to work.
![00](https://user-images.githubusercontent.com/24988459/30305263-74904a86-97a4-11e7-9e68-d93265a9dd1c.PNG)

**Comment by vnen** [comment]
Wasn't there an old issue about this? IIRC the problem is that this would increase the load time when opening the editor, especially if you have many heavy scenes.

**Comment by sersoong** [comment]
This should be a problem for the user to select and consider, and the default can be a closed state.
However, users should be allowed to choose whether to open them themselves.
In other words, this feature should be implemented, allowing users to choose their own.

**Comment by bojidar-bg** [comment]
@vnen Indeed, there is #2385. Funny how all the comments are duplicate..

Note that adding up the 👍 -s on both issues, we got a +6 already.

**Comment by sersoong** [comment]
Has this feature been available yet?

**Comment by akien-mga** [comment]
> Has this feature been available yet?

No, but there's already an older issue where it is being discussed: #2385.
