### ISSUE TITLE
GDScript Editor red font hard to read

### ISSUE THREAD

**Issue by rminderhoud** [godotengine/godot#11174]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot d1cb73b47a17de830d9474026ffa7b3587cfbc68

**Issue description:**
The red/purple fonts used in the code editor are very difficult to read. 

![godot_red_font](https://user-images.githubusercontent.com/1752584/30289979-888ab8de-96f3-11e7-8a09-328e2de60219.png)

**Comment by Noshyaar** [comment]
#11059 #11095

**Comment by rminderhoud** [comment]
Thanks @Noshyaar -- I searched but didn't find those entries.
