### ISSUE TITLE
arabic

### ISSUE THREAD

**Issue by Omaranwa** [godotengine/godot#11171]
what about arabic?

**Comment by Sslaxx** [comment]
Er, what? What, exactly, do you mean?

Do you mean RTL support? I think that's being worked on.

Translations? Supply some and they'll be used.

Fonts/display? No idea.

**Comment by Omaranwa** [comment]
i will try but where i can the very lasetest bulid?

**Comment by NathanWarden** [comment]
The latest is 3.0 alpha 1:
https://godotengine.org/article/dev-snapshot-godot-3-0-alpha-1

If you're even somewhat familiar with compiling software you can also try building from source. In my opinion, it's one of the easiest large projects to compile.
http://docs.godotengine.org/en/latest/development/compiling/

**Comment by trollworkout** [comment]
i don't know if you can input directly in arabic but  you can copy paste into textboxes in any language including arabic. just write it in another program then select copy and paste into godot will work !

also this should not be on issues. please post this next time on discord or questions on main godot page. github issues are only for bugs or suggestions not questions.

**Comment by akien-mga** [comment]
See #10546 for WIP support for BiDi and #3081 for various i18n-related issues.
