### ISSUE TITLE
gdnative-generate-json-api produces wrong json.api file

### ISSUE THREAD

**Issue by maxim-sheronov** [godotengine/godot#11170]
If you run engine with --gdnative-generate-json-api flag it produces api.json file
And it contains this:
`"return_type": "enum.Error",`

that fails compilation of header file:
`class enum.Error;`

**Comment by karroffel** [comment]
This is a problem with the bindings, not the API file itself, please open an issue on the [binding repository instead](https://github.com/GodotNativeTools/godot-cpp).
