### ISSUE TITLE
For a scene inherited from a model, when I change the root node's type, the scene loses its reference to ext_resource

### ISSUE THREAD

**Issue by MadIcecream** [godotengine/godot#11172]
And the mesh becomes a built-in resource.

**Comment by Noshyaar** [comment]
Version?

**Comment by cutepig49** [comment]
What I used is calinou's build, I don't know the exactly version.
https://bintray.com/calinou/godot/editor/2017-09-08.519b933

**Comment by bojidar-bg** [comment]
Duplicate of #6215?

**Comment by mhilbrunner** [comment]
Closing as a duplicate of #6215.
