### ISSUE TITLE
Return move_to method to KinematicBody2D in Godot 3.0

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#11184]
This method is now not available in Godot 3.0, replacing this method with move(end_pos-init_pos) involve overhead in scripting system that previously was supported by c ++, from 1 API call in move_to, we have now 2 API call (move and get_position) an one aritmetic subtraction.

**Comment by kerskuchen** [comment]
I agree that this is a useful addition as sometimes one does not care about "move-velocities" and just wants to move an object from point A to point B and stop if there was a collision.

**Comment by reduz** [comment]
just use set_position ...

**Comment by kerskuchen** [comment]
But AFAIK set_position does does not detect/stop on possible collisions between point A and B. Or has the KinematicBody2D an overloaded set_position function now?

**Comment by davarrcal** [comment]
Don´t think set_position was overloaded and you are right, is not the same that move_to, move_to is teleporting with collision stop, set_position is teleporting no mathers collision, there wasn´t redundant at all.

**Comment by KoBeWi** [comment]
So it's like `move_and_collide(target_position - position)`?

**Comment by kerskuchen** [comment]
@KoBeWi Your example seems to be equivalent to `move_to`. With `move_and_collide` we even get the `remainder` vector plus a ton of extra information from the resulting `KinematicCollision2D` object. `move_to` only returned `remainder` vector as far as I remember (its been three years).

**Comment by Ranoller** [comment]
Well, maybe maintain this three years is nonsense... if some-one need that can add that to kinematicbody2D in c++ and compile their own version of godot, or do a module that extends kinematicbody2d .., that was only an idea, if nobody ask for that it's better to close.
