### ISSUE TITLE
Project settings tooltips improvement

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#11186]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
any godot version

**Issue description:**
I would like to ask whether the tooltips in project settings can be modified or not. I would like to add some simple description for the properties. If not, I may carry this discussion to the godot documentation and try to create a page about the settings.

![2017-09-12 20 55 46](https://user-images.githubusercontent.com/10883749/30327100-6f834ec2-97fd-11e7-83f7-6aad2b1c72de.png)

**Comment by NathanLovato** [comment]
There's an issue up to create a reference in the docs, and help would be much welcome! https://github.com/godotengine/godot-docs/issues/395
It seems there's no system in place for in-editor tooltips. If we build the reference for the online manual though, we'll have the content ready to add back to the editor when someone can work on this.

**Comment by NathanLovato** [comment]
The files aren't 100% up to date but pwab shared his project and editor settings templates

https://gist.github.com/pwab/78672798589591c37da4f49d3a08bc6c
https://gist.github.com/pwab/e6497658cd3021e725611e2fc30335da

I'd probably be best to have a tool similar to the doctool (or make it part of doctool) to re-generate the list if it changes

**Comment by DevinPentecost** [comment]
I briefly looked through the C++ code and it looks like most settings are defined and referenced directly by string ([example](https://github.com/godotengine/godot/blob/a31735ad3608c9ec3a93db3ba294a7ad096fe453/editor/editor_settings.cpp#L444)). This seems like any changes to one would require the string reference to be updated in multiple places. Should there be a class that defines the settings and their paths/types/defaults/descriptions so that it can be referenced? I'm not an expert at C++ so forgive me if this is an antipattern of some sort.

I tried perusing the codebase to investigate adding the tooltips but I'm having a hard time finding where to start. Any ideas?

**Comment by vnen** [comment]
@DevinPentecost this should use a tool similar to doctool, writing/reading a XML file for the tooltips based on the full setting name. This way we can use the same source to make the documentation page and have tooltips in-editor.

Then the [Project Settings dialog](https://github.com/godotengine/godot/blob/master/editor/project_settings_editor.cpp) would read this file and add the tooltip accordingly. Same applies to the [Editor Settings dialog](https://github.com/godotengine/godot/blob/master/editor/settings_config_dialog.cpp). 

For the import panel I mentioned in #13370, this would be a bit more complicated and I understand if it's left for later.

**Comment by Calinou** [comment]
As many of the project settings may have a long description, it could be a better idea to display tooltips at the bottom of the Project Settings window, rather in a floating tooltip (which may have to span over several lines).

**Comment by DevinPentecost** [comment]
I was thinking it might be best to have two descriptions - a 'brief' description that is appropriate for tooltips, and a full/rich description that could have markup and such applied to it.

@Calinou I agree that having the majority of the details presented at the bottom of the settings window, but I still think it would be pretty helpful to have _something_ more useful in the tooltip than just the setting_name.

**Comment by akien-mga** [comment]
Indeed.
