### ISSUE TITLE
Expose CanvasItemEditor.snap_point() and CanvasItemEditor.snap_angle() to GDscript to use in EditorPlugins.

### ISSUE THREAD

**Issue by efirdc** [godotengine/godot#11180]
I would like to make an EditorPlugin that has draggable points that snap to the 2d canvas grid. Plugins like [Path2DEditor](https://github.com/godotengine/godot/blob/9e0fbb49c12a4bb12c275194b0599fdfa0b1aabf/editor/plugins/path_2d_editor_plugin.cpp#L81), [CollisionPolygon2DEditor](https://github.com/godotengine/godot/blob/fbda0cc45c2f50b9b30175c4f2398b8a73d7bf4a/editor/plugins/collision_polygon_2d_editor_plugin.cpp#L109), [Line2DEditor](https://github.com/godotengine/godot/blob/dac150108ab3c1f41d5fd86cc6853f883064caaf/editor/plugins/line_2d_editor_plugin.cpp#L59), ect, all use CanvasItemEditor.snap_point() to snap to the grid. I don't think there is a good way to even get the snap settings alone in gdscript. Right now I use `get_editor_interface().get_base_control()`, then I recursively search through all the child nodes to find the SnapDialog and the MenuButton with "Edit" text. Then I read all the snap settings directly from the UI so I can make my own snap_point(). Would be very convenient if these functions were available in some way to GDscript.

**Comment by groud** [comment]
I'm currently working on improving this function to perform smart snapping. I can make it available to gdscript on the way.

**Comment by groud** [comment]
This ended up more diffcult than I though to implement. It needs the editor classes to be available to GDscript which is not the case yet. Should be done but only when 'tool' is set in a script.

**Comment by MCrafterzz** [comment]
@groud Have you figured it out?

**Comment by groud** [comment]
Well I'm not sure it is clear enough for it to be exposed. I'll have a look someday.

**Comment by DualMatrix** [comment]
I'm having this issue as well, the lack of these functions makes creating custom nodes with editable settings really annoying.

**Comment by Takanu** [comment]
+1, this is pretty crucial to both 2D and 3D tools.

**Comment by KarlWerf** [comment]
I would like to make custom snap settings (for a hex grid) would that be covered in what you're doing here @groud, or should I create a new issue?

**Comment by groud** [comment]
Handling a hex grid requires a rework of the grid system, it's unrelated to this issue.

**Comment by akien-mga** [comment]
@groud What's the status on this issue?

**Comment by groud** [comment]
> @groud What's the status on this issue?

Not done yet ^^. However, I'd like to have a simple way to declare functions as editor (or tool scripts) only, I am not sure it can be done in a clean way for now.

**Comment by mechPenSketch** [comment]
@efirdc Did you find the function/variable that gets the snap settings by any chance? I'm looking for a way for my plugin such that when Configure Snap > Grid Step is step, it'll then set the snap settings in, say, a TileMap in the process.

**Comment by takaturre** [comment]
Anyone wondering about the last missing steps for this mentioned hack - how to *apply* the values - the key is to set the values to the **SpinBox** controls and then press the OK button of the **SnapDialog** virtually (no need to popup): 

For example, horizontal grid size to 100:  `spin_boxes[2].set_value(100)`, and to apply: `snap_dialog.get_ok().emit_signal("pressed")`.

Documented the stuff here:
https://godotengine.org/qa/39440/can-i-get-snap-settings-in-a-script?show=79083#a79083

**Comment by erayzesen** [comment]
Hi all. Is there any improvement? I need to this feature.

**Comment by mechPenSketch** [comment]
^ @groud is most likely too busy with godot 4.0's tilemap update. However, since I've done a PR on this before, I could give it a shot here.

Theoretically, I could expose few methods in EditorPlugin (editor/editor_plugins.cpp) to set and get some snaps. For these methods, I could get_singleton() from CanvasItem (editor/plugins/canvas_item_editor_plugin.cpp) to set_state(dict) and get_state().

**Comment by mechPenSketch** [comment]
I have made the above PR to expose snap settings; however, it does not close this issue as I thought, now that I've read the title carefully.

**Comment by KoBeWi** [comment]
This is old and has a workaround, so it should be reopened as a [proposal](https://github.com/godotengine/godot-proposals).

**Comment by hsandt** [comment]
For people landing here, this proposal to "Implement a way for EditorPlugins to get 2D Editor Grid Snap" was opened:
https://github.com/godotengine/godot-proposals/issues/10529

However it's getter only, not setter.
