### ISSUE TITLE
Remove duplicate code for node duplications

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#11182]
<sub>_\<!-- not using regular template, as this is about the code quality --\>_</sub>
**Godot version:** ebee989 (master)

While coding #11167, it became apparent that there are 3 or more functions with nearly-equivalent code which just duplicate nodes. We should review them, and centralise them if possible.

For clarity, those are the functions found so far:
* Node::_duplicate()
* Node::_duplicate_and_reown()
* ~~SceneTreeDock::_duplicate()~~ fixed by @RandomShaper 
* Node::duplicate_from_editor()  as noted by @DualMatrix

**Comment by RandomShaper** [comment]
With #13041, I've been able to remove the duplication logic from `SceneTreeDock`. The next step would be to rework `Node::duplicate_and_reown`.

It's been pretty hard and the next step will be even harder. @akien-mga, I suggest you to remove the _Junion job_ tag.

@bojidar-bg, will you update the description of this issue?

**Comment by DualMatrix** [comment]
There is `Node::duplicate_from_editor()` now as well.

**Comment by YuriSizov** [comment]
We no longer have `Node::_duplicate_and_reown`, and `Node::duplicate_from_editor` reuses `Node::_duplicate` internally. So this can be closed.
