### ISSUE TITLE
Move global constants to enums

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#11188]
**Godot version:**
3.0 - master

**Issue description:**
Various input methods rely on values like `BUTTON_XY`, for mouse buttons or `JOY_BUTTON_XY`, for gamepad buttons. Currently they are constants in the global scope and methods using them take `int` parameters.
Now that we have proper enum support, it would be nice to move them to named enums.

**Comment by ranjian0** [comment]
I am new here, but this seems straightforward. I've had a look at core/global_constants.hpp. Should I just rename the bind functions.

**Comment by akien-mga** [comment]
Fixed by #12341.
