### ISSUE TITLE
Node "Change Type" not working because nothing is selected

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#11193]
Godot2.1.4 stable(I think I had the same issue on master)
Kubuntu 17.04

It looks like there are 2 type of selections 

In this case the Node is selected and change type works fine
![image](https://user-images.githubusercontent.com/4741886/30336528-baa96534-97e5-11e7-814d-9e1a0f012d96.png)

and in this case when you right click on the node it is not selecting the Node correctly so "Change Type" will have no effect.

![image](https://user-images.githubusercontent.com/4741886/30336543-c7bae2de-97e5-11e7-8c58-5cba08af3685.png)

Steps:
1. Select Node(Left click)
2. Run project
3. Stop Project
4. Right Click on Node "Change Type"
5. Choose new Type
6. See Node didn't change.

**Comment by eon-s** [comment]
This happens a lot lately (2.1.4 and master), affects the action to "add script" too (and maybe others).

**Comment by AlexHolly** [comment]
Looks fixed on master, can anyone test on 2.1?

**Comment by eon-s** [comment]
Still valid for 2.1.5, an easy way to reproduce it is adding and immediately clearing a script.

**Comment by akien-mga** [comment]
I think such usability enhancements are unlikely to happen for the 2.1 branch at this point, so I agree with closing it as fixed in 3.0.
