### ISSUE TITLE
[3.0] set_translation (and others) not in the suggestions

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11202]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 

**Issue description:**
In the code editor, "set_translation" and all other similar functions don't come up in the auto complete.

**Examples:**
set_translation
get_translation
set_rotation
get_rotation
set_scale
get_scale

And probably more that I haven't learned yet

**Comment by bojidar-bg** [comment]
@Andev08 This is not a bug, it is because in 3.0 it is deemed more correct to use properties instead.
So, `x.get_transform()` becomes `x.transform`, `x.set_transform(y)` becomes `x.transform = y`.

**Comment by Andev08** [comment]
That absolutely makes more sense, thank you for sharing! Is this written in documentation somewhere, and if so, where can I find it?

**Comment by mhilbrunner** [comment]
Not sure if it is pointed out somewhere, but yeah, as bojidar said, use members now, setters/getters are mostly dropped. :)
