### ISSUE TITLE
Godot Crash - can't kill even with Task Manager

### ISSUE THREAD

**Issue by louisVottero** [godotengine/godot#1121]
I'm not sure if it's this error exactly that is causing the crash, but it's the last info in the shell...

ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true
At: core/io/packet_peer.cpp:228

**Comment by louisVottero** [comment]
Any new Godot sessions started after the crash never finish loading, and cannot be killed in the task manager.

This is in windows 8.1

**Comment by akien-mga** [comment]
Were you able to reproduce this crash or was it a one time issue?

**Comment by akien-mga** [comment]
Closing as old.
