### ISSUE TITLE
Input map broken

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11214]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0

**Issue description:**
The input map doesn't allow any keyboard input other than the command keys (alt, shift, tab etc). The "Please Confirm" dialog shows the key that's pressed, but when you press ok, the slot is empty, and it doesn't respond in game.

shift+a turns into shift+
character keys don't show either (backslash, apostrophe, braceleft/right etc)

Also the mouse input shows correctly in the gui, but doesn't trigger ingame.

**Steps to reproduce:**
Open a new project
Project > Project settings > Input map
Create / edit a keybind for the keyboard.
You'll see it doesn't show the bind after you press OK
write some code that does something for that keybind and compile
nothing will happen when you press it.

---------
or for mouse, create a bind for say left mouse input 0.
The GUI will show correctly in this case
Create some code that does something when you trigger that bind
nothing will happen,

**Comment by Hinsbart** [comment]
I can reproduce this only with the default actions (`ui_*`). With custom actions the event bindings work as expected.

**Comment by Andev08** [comment]
![broken](https://user-images.githubusercontent.com/31744099/30490200-30ba44e4-9a31-11e7-95a6-6349f1765538.gif)

**Comment by reduz** [comment]
This code resides in:
https://github.com/godotengine/godot/blob/master/editor/project_settings_editor.cpp
It may be a bit messed up as it's mixed with other stuff, but not so difficult to understand

**Comment by vnen** [comment]
I can't reproduce this on Windows. It might be related to the [`get_scancode_string`](http://docs.godotengine.org/en/latest/classes/class_os.html#class-os-get-scancode-string) function from the OS singleton.

**Comment by Nibodhika** [comment]
I can't reproduce it on Linux either, it works fine for both custom and default actions.

**Comment by mijo-gracanin** [comment]
Can't reproduce on macOS

**Comment by akien-mga** [comment]
Assumed fixed since nobody seem able to reproduce it anymore.

**Comment by Andev08** [comment]
Yup, can confirm this is fixed as of alpha2!
