### ISSUE TITLE
3D objects should have "previews" in the filesystem

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11218]
**Issue description:**
PNG files have a preview, so it would be fitting for models to get one too. It would be better than a blank piece of paper with the corner folded, especially since the file name is often split over 2 lines. 

![image](https://user-images.githubusercontent.com/31744099/30352870-818721da-981a-11e7-9971-206f42711e91.png)

It would also make the gui look friendlier (in my opinion at least!), which is definitely important for attracting new users
![image](https://user-images.githubusercontent.com/31744099/30352989-3926ef82-981b-11e7-98e8-5ebcf5ab1443.png)

**Comment by rminderhoud** [comment]
I can confirm I get previews for meshes (custom format) and scenes in 6ec93837067521dcf10493dcddd27d60a92376aa

![model_preview](https://user-images.githubusercontent.com/1752584/30400256-e652f5d6-989b-11e7-9ae4-bd193b5182ad.png)
![scene_preview](https://user-images.githubusercontent.com/1752584/30400259-e8c6812a-989b-11e7-8f92-3b919c076d81.png)

**Comment by fracteed** [comment]
As rminderhoud has stated, there is already a thumbnail image for .mesh format which is what all imported obj/collada files must be converted to.

**Comment by Andev08** [comment]
> .mesh format which is what all imported obj/collada files must be converted to

Can I ask why?

**Comment by fracteed** [comment]
.mesh format is the native format that Godot uses, presumably for the sake of speed. If you look in the .import folder you see that all obj/collada/gtf files have been converted into a corresponding .mesh file. In Godot 2, the only workflow was to manually import an obj/dae and convert it to a mesh. 

Admittedly, I did prefer that kind of workflow, but it now is an auto process ala Unity. As soon as Godot detects a new file has been added it converts it into the import folder(which is acting a as a cache) , so even though you can see your original obj file, it is using the converted .mesh file. The advantage of this is that if you update your obj file by copying over it(keeping the same file name), Godot will automatically reconvert for you. This allows you to keep updating your obj and not worry about manually conversion each time. The disadvantage is that you have more files cluttering up your project structure and the obj/dae files have to been reconverted each time you do a cleanup of your .import folder(which can get massively cluttered over time, especially if you are experimenting with meshes/textures that don't end up being used). 

My workflow of manually converting to .mesh and then deleting the original obj is only viable for static objects. If you have animated meshes that are imported with collada/gltf2 then you need to keep the original files in the project directory.

**Comment by Andev08** [comment]
Thank you for the explanation!

> manually converting to .mesh and then deleting the original obj is only viable for static objects. If you have animated meshes that are imported with collada/gltf2 then you need to keep the original files in the project directory.

So how does Godot handle animated objects? Does it convert out a mesh format for them, but just retain the .obj for reading the animation data when necessary? Or does it forgo the converted format entirely and just use the original file?

**Comment by rminderhoud** [comment]
@Andev08 -- It creates separate .anim files for the animations.

**Comment by Andev08** [comment]
Is there other stuff it needs from the .obj file too then? What is the reason for still requiring it?

**Comment by fracteed** [comment]
There will still be a reference to the obj file, so you will need to keep it if you are using the standard workflow (even though internally it is using the converted .mesh file). Likewise, any textures will have been converted to .stex files in the import folder, but you can't delete the original texture. Agreed that this is all somewhat confusing, hence why I use the workflow i outlined above, as when using a .mesh file directly there is no need for godot to convert it..

**Comment by djrm** [comment]
closable?

**Comment by Andev08** [comment]
Well I still think it would be nice if .obj files had previews too

**Comment by djrm** [comment]
they have

**Comment by Andev08** [comment]
In Godot alpha 2, there is no preview
![image](https://user-images.githubusercontent.com/31744099/32701606-bc76ffbe-c7d0-11e7-8179-82c3351164b7.png)

**Comment by djrm** [comment]
the have when imported as mesh, some tscn lack preview

**Comment by Andev08** [comment]
Maybe this stays open until whatever is going on above doesn't happen anymore?

**Comment by rminderhoud** [comment]
This can be closed. `.obj` have previews:

![image](https://user-images.githubusercontent.com/1752584/33797802-df77a672-dcd3-11e7-9134-a35f3e37862e.png)
