### ISSUE TITLE
Hysteresis (delay) in hierarchical dropdown menus

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11219]
I brought this up with @djrm on IRC, and he mentioned it would be easier to track here.

One thing that has bugged me for a while is the lack of a delay when hovering away from a dropdown's sub-menu option. This phenomenon is usually referred to as _hysteresis_, and this page explains it a lot better than I can: http://www.mackido.com/Interface/hysteresis.html

There aren't many places where you'll run into this problem, as there aren't many dropdown menus like this in Godot to begin with (I run into it all the time when choosing an editor layout, but that's only because Godot doesn't load the default layout correctly), but I think it's a necessary facet of UX design for desktops.

Tested with 5cb90ad (but this has affected all versions up to this point) on Linux Mint 18.2 Cinnamon x64

**Comment by YeldhamDev** [comment]
Just taking the opportunity to reference this, as it might be related: https://github.com/godotengine/godot/issues/10911

**Comment by puppetmaster-** [comment]
I also want to reference this #12179 issue. Perhaps there are some more places which need a _hysteresis_ implementation.

**Comment by Calinou** [comment]
This is still not implemented as of commit https://github.com/godotengine/godot/commit/d711c57d767734887fbf0955a7b9902c54498a0d.
