### ISSUE TITLE
debug area no visible tabs anymore

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#11212]
I think there were tabs visible before the nice editor_theme "refactor" (update)
<img width="1149" alt="screen shot 2017-09-13 at 00 33 09" src="https://user-images.githubusercontent.com/16718859/30351362-513deef4-981b-11e7-9f0c-f06ab412753d.png">

If they were there before, I really liked them. although that made the bg really dark.

**Comment by djrm** [comment]
@toger5 yeah that was intended, everything inside those tabs looked horrible. the only acceptable solution for this would be to have actual tabs in there (i mean as if those tabs were like docks tabs)

**Comment by djrm** [comment]
also i tried with several things, like a bit more dark, border container and none of them were actually good

**Comment by toger5** [comment]
@djrm okay. I haven't tested anything but I believe you immediately that it didn't look good enough...
I like you proposal of actual tabs!

**Comment by djrm** [comment]
@toger5 the problem here is that, thats everything is inside the container that has the context buttons (output, debuger etc...) so even if you manage to make the panel transparent you will make the context buttons transparent, so i dont really know if there is a workaround for this.

**Comment by toger5** [comment]
@djrm thats what I was thinking... 
but with he negative top expand margin it could still work... kind of hacky though...
and the margin than would need to change if there are no tabs...

**Comment by djrm** [comment]
@toger5 yeah, that could work, want to see a PR to believe

**Comment by toger5** [comment]
@djrm here is the proof ;)

<img width="1128" alt="screen shot 2017-09-13 at 02 32 34" src="https://user-images.githubusercontent.com/16718859/30354270-e19193f6-982b-11e7-9ae9-2aba25a5378e.png">

I was working on another pr... so I have to some git to separate the changes... but pr will come soon
