### ISSUE TITLE
Skeleton doc page looks messed up.

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#11228]
![image](https://user-images.githubusercontent.com/6152134/30364786-f1c69f5c-9865-11e7-975d-18b2524cefd8.png)

**Comment by akien-mga** [comment]
I may have broken it with 4e392517dab9b0ba137533a3d381ea1fa32cf77b, though not sure.

**Comment by onur** [comment]
It was working fine yesterday, today doc browser is broken.

**Comment by djrm** [comment]
this has been solved

**Comment by groud** [comment]
OK, closing then :)
