### ISSUE TITLE
Give GUI input fields a "reset" option

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11234]
**Issue description:**
When you're messing around with settings, sometimes you just want to put something back to its default value, but you can't undo because you made some changes elsewhere that you don't want to revert.

I'd imagine it be like right clicking on the option, and clicking "default" from a dropdown, Blender is a good example:
![image](https://user-images.githubusercontent.com/31744099/30380035-560fc0f4-9890-11e7-8d7b-046e390080b1.png)

**Comment by Zireael07** [comment]
There should be an arrow next to the box where you input the value?

**Comment by Andev08** [comment]
![image](https://user-images.githubusercontent.com/31744099/30380802-77a7d02e-9892-11e7-8552-04d1f8cde001.png)
The only arrows I see are ones that change the value?

**Comment by Noshyaar** [comment]
@Zireael07 That's for instanced scenes?

**Comment by Andev08** [comment]
2 years ago... :(

**Comment by GrayJacketStudios** [comment]
I think this should be closed as Godot 3.0 already has this option with the revert button

**Comment by dreamsComeTrue** [comment]
Confirming, @akien-mga - we do have now circular "rest to factory settings" button :)
