### ISSUE TITLE
Android filesystem doesn't seem to create directory or text file

### ISSUE THREAD

**Issue by ChickenScratch** [godotengine/godot#11241]
Samsung Galaxy Tab A SM-T350 Android 6.0.1, Godot 2.1.3 or 2.1.4rc

Trying to write out data to a file, preferred to be in the Documents folder. However, I cannot figure out how to gain access to it. 
Using OS.get_system_dir(2) I get:
User directory: /storage/emulated/0/Download/ test_folder doesn't exist. /storage/emulated/0/Download/test_folder/test_file.txt opened.
fp_user error code: 12
/storage/emulated/0/Download/test_folder/test_file.txt written.

Yet there is clearly nothing written to the Download folder or the Documents folder.
According to the documentation I should be using 2 as the reference to Documents, but it doesn't return Documents, it returns Downloads. And 3 also returns Downloads. https://godot.readthedocs.io/en/stable/classes/class_os.html

Then I used 'user://' with no directory creation and I get:
User directory: user://
user://test_file.txt opened.
fp_user error code: 0
user://test_file.txt written

Yet I cannot find any test_file.txt anywhere.

All using code snip as I found it: https://godotengine.org/qa/6285/how-to-write-to-user-directory-in-android 

var dir = Directory.new()
var dir_name = "test_dir"
var filename = "test_file.txt"
var user_dir = "user://"
dir.open(user_dir)
print( "User directory: " + user_dir )
var fp_user = File.new()
var f_name = user_dir + filename;
var err = fp_user.open( f_name, File.WRITE )
print( f_name + " opened." )
print( "fp_user error code: " + str(err) )
fp_user.store_line( "This is a test file." )
print( f_name + " written." )
fp_user.close()

**Comment by volzhs** [comment]
`user://` is a hidden directory for each app.
generally, you can't find files under `user://` with other file browsing app.

but you can find it with a special way.
see this https://stackoverflow.com/questions/15558353/how-can-one-pull-the-private-data-of-ones-own-android-app

if you want somewhere else, not `user://`, you need a permission `Write External Storage`

And it's not a Godot bug.

**Comment by superpotatofudge** [comment]
OK, I'm aware of the WriteExternalStorage and yes it is checked, along with every other file output/access related permission I see in the export settings. Yet I cannot get a file to write anywhere visible.

So if user:// is incorrect for this usage, what access method then should be used to place the file in a user accessible directory? That special workaround is not feasible for the end use case.

**Comment by volzhs** [comment]
did you try to save it under `/storage/emulated/0/Download/`?
you need to create directory by `dir.make_dir(path)` or `dir.make_dir_recursive(path)` if not exists.

you'd better use QA site for this kind of problem.
https://godotengine.org/qa/

**Comment by superpotatofudge** [comment]
Yup I tried that with no success and yes I utilized
if( !dir.dir_exists( dir_name ) ):
		print( dir_name + " doesn't exist." )
		dir.make_dir_recursive( dir_name )
	else:
		print( dir_name + " exists." )

And I got fp_user error 12 and that was WITH the external storage permission checked.
User directory: /storage/emulated/0/Download/
test_dir doesn't exist.
/storage/emulated/0/Download/test_file.txt opened.
fp_user error code: 12
/storage/emulated/0/Download/test_file.txt written.

**Comment by volzhs** [comment]
@ChickenScratch 
In that case, you need to grant permission on application setting manually.
go to setting > application, find your test app, and grant write permission.
then restart your app.

don't worry about manual permission while you are developing.
it will be fine to general users installing from play store.

here is my test result with Android 7.0 (Galaxy s8+)

Test code
```gdscript
extends Node

func _ready():
	write_test()
	pass

func write_test():
	var dir = Directory.new()
	var dir_name = "test_dir"
	var filename = "test_file.txt"
	var user_dir = "/storage/emulated/0/Download/"
	
	var err = dir.open(user_dir)
	
	if err != 0:
		print("open directory fail - " + user_dir)
		print("error code = %d" % err)
		return
	
	print("open directory success - " + user_dir)
	
	var f_name = user_dir + filename;
	var fp_user = File.new()
	var err = fp_user.open( f_name, File.WRITE )
	
	if err != 0:
		print("open file fail - " + f_name)
		print("error code = %d" % err)
		return
	
	print("open directory success - " + f_name)
	
	fp_user.store_line( "This is a test file." )
	fp_user.close()
	
	print( f_name + " written." )
```

adb logcat output
```
09-14 17:07:23.563: I/godot(16108): open directory success - /storage/emulated/0/Download/
09-14 17:07:23.564: I/godot(16108): open directory success - /storage/emulated/0/Download/test_file.txt
09-14 17:07:23.564: I/godot(16108): /storage/emulated/0/Download/test_file.txt written.
```

**Comment by ChickenScratch** [comment]
Ok so the manual granting fixes it completely. Now the problem is that I will not be deploying this via the Play store. This is a side load only project for work. So anytime I use the One-click deploy/debug from Godot the permissions go away and I'm back to error 12 failed to open file. What's the fix for this problem?

**Comment by volzhs** [comment]
I think unchecking "Clear Previous Install" on export setting will help for that.

**Comment by ChickenScratch** [comment]
Thanks for helping with a very aggravating problem! I'm gtg now.
