### ISSUE TITLE
Select Gridmap or Tilemap Tiles

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#1125]
Hey, there. So, I think it'd be really helpful to be able to select and manipulate tiles in Tilemaps or Gridmaps. Currently, you have to manually replace any tiles that you want to alter. Having a method to select multiple of them to be able to rotate, delete, move, or even replace all of a specific kind of tile with another one would be really nice.

**Comment by reduz** [comment]
there are many keyboard shorcuts for this, but they are not visible
anywhere, I guess i should make them visible in some menu

**Comment by SolarLune** [comment]
Oh, really? Wow, yeah, please do. That'd help a lot, I think.

**Comment by akien-mga** [comment]
Indeed there seems to be shortcuts, e.g. you can select several tiles by holding Shift, and Ctrl+Left click on a tile will change your brush to the same tile from what I could find. I could not find how to actually _use_ a group of selected tiles to mass apply a change to them like a new tile or rotation.

**Comment by akien-mga** [comment]
Fixed by #4006.
