### ISSUE TITLE
Can't reselect bus effect if only one effect per bus

### ISSUE THREAD

**Issue by Jerome67000** [godotengine/godot#11262]
**Versions**
Windows 8 64 bits, Godot 3.0alpha1

**Issue description:**
Can't reselect bus effect if only one effect per bus

**Steps to reproduce:**
Add one bus or more
Add one effect in each bus
Select effect in bus 1, select effect in bus 2 (the effect in bus 1 isn't deselected), impossible to select the effect of bus 1 anymore and tweak it in inspector

![image](https://user-images.githubusercontent.com/7358899/30427545-7dc1a764-9950-11e7-9f09-51ad84c76887.png)

**Comment by ISylvox** [comment]
I think I can't reproduce it in Godot 3.0 https://github.com/godotengine/godot/commit/8c08f2380d30e300f4f80dd292e9ff83f7bb84fd (using the same binary as contained in this archive: https://github.com/godotengine/godot/files/1303179/Godot_v3.0.alpha.8c08f23_x64.zip)

**Comment by djrm** [comment]
oh yes i solved this, i dont remember if it was after the alpha

**Comment by groud** [comment]
> oh yes i solved this, i dont remember if it was after the alpha

Perfect then :)

Closing.

**Comment by Jerome67000** [comment]
Hi,

I just have tried with the last linux build and for me this isn't totally solved. If you reselect bus 1, I can again tweak it in inspector, but visually effect of the other bus still selected.

Now :
![image](https://user-images.githubusercontent.com/7358899/30510415-b192ceaa-9ac3-11e7-9300-5a3c1bc7fc6e.png)

Excepted :
![image](https://user-images.githubusercontent.com/7358899/30510422-d40c9db2-9ac3-11e7-9091-9ae9797029a9.png)

**Comment by Noshyaar** [comment]
Rereading it, this might be a separate issue. Please open a new issue for visual bug. If the bus effect can be reselected this one may be closed.

**Comment by Jerome67000** [comment]
Done : #11355
