### ISSUE TITLE
Add an "added_child" signal to Node

### ISSUE THREAD

**Issue by ObaniGemini** [godotengine/godot#11260]
I think it would be good idea to have an `added_child(child)` signal to `Node`
I also don't think it would be very hard to implement, but in term of performances ? You guys are the knowledge owners on that point :)

Also, if this gets added, could it be merged for 2.1.5 ? 🙏

**Comment by Zireael07** [comment]
Not sure on the performance end, but I can see tons of uses for the signal already :)

**Comment by Zylann** [comment]
While I see usages too, I never really needed such a thing. I mainly don't like the fact that not using it still makes you pay the cost of sending this signal for every node (also think about scene loading, which also adds nodes)

**Comment by eon-s** [comment]
I don't see the usage of that.
I mean, the node that adds children to a specific node can call a group/notify the addition to interested nodes instead of every single node emitting signals, I think this workflow makes more sense.

Inserting a scene will result in the emission of many signals too like was mentioned before.

**Comment by akien-mga** [comment]
Indeed, I think this would go against the signals philosophy of Godot.

Built-in signals are meant to notify about stuff which was not triggered directly by the developer; child nodes are only added when the developer requests it, by instancing and adding a scene/node, reparenting stuff, etc. Apart from some internal things like tooltip timers which shouldn't be used for game logic anyway, the engine would not add children without you requesting it.

As soon as an action is triggered by the developer, you can emit your own signal if that's relevant for your game logic (including from the animation player, which can also emit signals).

**Comment by akien-mga** [comment]
You can use `SceneTree.node_added` for this use case now (#12224).
