### ISSUE TITLE
Sliders texture missing before grabber

### ISSUE THREAD

**Issue by hickop** [godotengine/godot#11261]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux, Godot 3.0 at 3f4062c7083d51c2d5375baee3a7e42bcd591e16

**Issue description:**
Probably related to #11191 
![sliders](https://user-images.githubusercontent.com/1115700/30424949-ce1649b2-9947-11e7-988a-327cc4242c7d.png)

**Comment by akien-mga** [comment]
CC @toger5
