### ISSUE TITLE
Compile error with get_drive function for android template

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#11270]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04.3, master branch 3f4062c

**Issue description:**

it's from #11160.
I got compile error for building android template.

```
drivers/unix/dir_access_unix.cpp:209:15: error: use of undeclared identifier 'setmntent'
        FILE *mtab = setmntent("/etc/mtab", "r");
                     ^
drivers/unix/dir_access_unix.cpp:214:10: error: use of undeclared identifier 'getmntent_r'
                while (getmntent_r(mtab, &mnt, strings, sizeof(strings))) {
                       ^
drivers/unix/dir_access_unix.cpp:223:3: error: use of undeclared identifier 'endmntent'; did you mean 'getmntent'?
                endmntent(mtab);
                ^~~~~~~~~
                getmntent
/mnt/2TB/Development/NVPACK/android-ndk-r15c-linux/platforms/android-18/arch-arm/usr/include/mntent.h:49:16: note: 
      'getmntent' declared here
struct mntent* getmntent(FILE*);
               ^
3 errors generated.
scons: *** [drivers/unix/dir_access_unix.android.opt.armv7.neon.o] Error 1
```

this is what `/android-ndk-r15c-linux/platforms/android-18/arch-arm/usr/include/mntent.h` has inside
```cpp
#ifndef _MNTENT_H_
#define _MNTENT_H_

#include <stdio.h>

#define MNTTYPE_IGNORE "ignore"

struct mntent
{
    char* mnt_fsname;
    char* mnt_dir;
    char* mnt_type;
    char* mnt_opts;
    int mnt_freq;
    int mnt_passno;
};

__BEGIN_DECLS
struct mntent* getmntent(FILE*);
__END_DECLS

#endif
```

I found `/android-ndk-r15c-linux/platforms/android-21/arch-arm/usr/include/mntent.h` has those functions.
```cpp
int endmntent(FILE*);
struct mntent* getmntent(FILE*);
struct mntent* getmntent_r(FILE*, struct mntent*, char*, int);
FILE* setmntent(const char*, const char*);
```

**Steps to reproduce:**
`scons platform=android tools=no`

**Link to minimal example project:**

**Comment by hpvb** [comment]
This passed Travis so I assume this is some incompatibility between NDK versions. Can you please provide some details as to where the NDK you're using came from? We may have to have a discussion about what we need to support for 3.0.

**Comment by volzhs** [comment]
https://travis-ci.org/godotengine/godot/builds/274869395?utm_source=github_status&utm_medium=notification
travis doesn't have for android now.

**Comment by hpvb** [comment]
@volzhs right you are...

**Comment by volzhs** [comment]
I got NDK from the official site. https://developer.android.com/ndk/downloads/index.html

**Comment by hpvb** [comment]
We should ifdef out this implementation for Android, it actually doesn't make much sense for that platform, at least not the way this was done. I'll make a PR.

**Comment by volzhs** [comment]
I compiled `drivers/unix/dir_access_unix.cpp` successfully with `scons platform=android tools=no ndk_platform=android-21`
maybe we should raise default version from here?
https://github.com/godotengine/godot/blob/master/platform/android/detect.py#L24
@RandomShaper what do you think?

it's out of this issue, but I got another error. :(
```
thirdparty/recastnavigation/Recast/Source/Recast.cpp:26:10: fatal error: 'new' file not found
#include <new>
         ^~~~~
1 error generated.
```

**Comment by volzhs** [comment]
@hpvb I agree android doesn't need this function.

**Comment by hpvb** [comment]
Na'h the whole way the 'drives' work for Unix makes no sense for Android at all.
