### ISSUE TITLE
Godot won't compile Android Export templates.

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#11271]
Fedora, on Godot 2.1 branch.

**Issue description:**
Scons simply won't build the the export templates using `scons platform=android target=release`; the message I get is 

`No valid target platform selected.
The following were detected:
	server
	haiku
	x11
`
althought I have all the export variables setted up and everything installed correctly. Is there any other env variable besides "JAVA_HOME", "ANDROID_HOME" and "ANDROID_NDK_ROOT" that is not documented?

**Comment by volzhs** [comment]
not that I know of.
This is what my `.bashrc` has for compiling android template.
```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
export ANDROID_NDK_ROOT=/mnt/2TB/android-ndk-r15c-linux
export ANDROID_HOME=/mnt/2TB/android-sdk-linux
```

**Comment by henriquelalves** [comment]
I'm feeling so stupid right now.

I was actually setting the variables without `export` (`ANDROID_NDK_ROOT=/....`), and just adding them to path. I added `export` and now everything works but my dignity after cracking my head for 4+ hours on this problem.

Thanks @volzhs, your `.bashrc` saved what is left of my soul. I'll close this issue and return to my shameful existence.
