### ISSUE TITLE
2.1 Missing translation template

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#11286]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
win64 godot2.13

**Issue description:**
Missing translation template "Make Unique".
This phrase cannot be translated automatically.

**Comment by sersoong** [comment]
Can't be fixed by #11285.
editor/translation/editor.pot and all *.po files missing "Make Unique" msgid

**Comment by Noshyaar** [comment]
Translation template will be updated eventually.
