### ISSUE TITLE
Removed alpha from color converted icons

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#11289]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
57516a447395223e56e93e05994a5bf69ee3bcac

**Issue description:**

Icons that are color converted have no alpha.

ping @toger5 

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by toger5** [comment]
Yea that is because the convert colors are 6 digit hex in editor_themes. (so alpha =1)
But i think you are asking to copy the old alpha value and overriding for the replace color?

**Comment by toger5** [comment]
I can do that. Its a good faeture/fix

**Comment by djrm** [comment]
@toger5 yeah, there is no much utility in transforming alpha, also as far as i can tell NSVG uses an opactity attribute?, alpha value is very important for the icons so it should be preserved.

**Comment by reduz** [comment]
what do we do with this?

**Comment by djrm** [comment]
@toger5 are you still planning to fix this, or should i give it a try?

**Comment by toger5** [comment]
Looking into it I'm not even sure if this is the case.
every shape has a opacity values (as you wrote before)
and a 3 channel color. 
the opacity value of the shapes is never touched during the conversion phase and there is also no instancing of the NSVGShape class. they are all kept and only the two color values are changed (fill, stroke)
maybe Nsvg is still using the alpha value of the colors although it only registers them as 3 channel?

**Comment by toger5** [comment]
Yea I'm pretty sure it is just taking the color alpha + opacity...
So the color needs to be adapted
