### ISSUE TITLE
boolean divided by 0 kills godot

### ISSUE THREAD

**Issue by 0ttoman** [godotengine/godot#11291]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux 64 bit Fedora 26, Godot 2.1.4

**Issue description:**
when the editor tries to interpret a function which divides true (or false) and 0 (or false) the whole godot process is killed.

this is a problem when copying examples from the documentation. [example](http://docs.godotengine.org/en/stable/learning/features/viewports/viewports.html#scale-stretching)

**Steps to reproduce:**
open the script editor and insert the following lines:
```
func test():
#    true/0
```
then delete the # character

note: dividing 1/0 inside the function doesn't kill the process

**Comment by hpvb** [comment]
There is already as PR to fix this #11078
