### ISSUE TITLE
Shader is not affecting instanced scenes

### ISSUE THREAD

**Issue by Kubees** [godotengine/godot#11303]
Hello!

I have a problem with shader. I am using [Godojo's water one](https://www.youtube.com/watch?v=1XcB46hN5Pg&t=4s), but once I put it into base scene, it only applies to scenes, which are not pre-made scenes instanced into the base one.

![19](https://user-images.githubusercontent.com/20991844/30500587-46307824-9a5f-11e7-8a16-fdec60693b37.png)

As you can see, the big plant and the elephant are not mirrored in water down below. I think, it is because the nodes, children ones of those, cannot be seen in base scene, therefore shader script is not using them and drawing them. Even the terrain made from polygon is actually visible in the mirrored image. Or maybe it is because they, the plant thing and the elephant nodes, are using Node2D as root. I might be wrong, so I will be grateful for any ideas, how to fix this!

I am using Godot v2.1.4.

Here is a shader script for anyone interested:
```
uniform float height = 1;

uniform texture displace_1;
uniform float speed_1 = 1;
uniform float displace_factor_1 = 0.01;

uniform texture displace_2;
uniform float speed_2 = 1;
uniform float displace_factor_2 = 0.01;

vec2 offset_1 = vec2(TIME * speed_1,0);
vec2 d_1 = tex(displace_1, UV + offset_1).rg;

vec2 offset_2 = vec2(TIME * speed_2,0);
vec2 d_2 = tex(displace_2, UV + offset_2).rg;

vec2 r_uv = vec2(SCREEN_UV.x, SCREEN_UV.y + UV.y*height) + (d_1 * displace_factor_1 - d_2 * displace_factor_2);

vec3 r_col = texscreen(r_uv);

COLOR.rgb = vec3(0,0,0);

COLOR.rgb += r_col + vec3(d_1 * d_2, 0) * 0.1 - vec3(0.4,0.2,0.1) * (1-UV.y + 0.1);
COLOR.rgb += vec3(0.3,0.2,0.1) * (1 - dot(d_1, d_2));

COLOR.a = 1 - (UV.y*UV.y);
```

**Comment by Noshyaar** [comment]
Version?

**Comment by Kubees** [comment]
Oops, I am using Godot v2.1.4, one that is currently on Steam.

**Comment by eon-s** [comment]
Can you reproduce it with a minimal example project?

Maybe the setup is affecting the shader (it may need another order, a viewport sprite or a backbuffer copy).

**Comment by Kubees** [comment]
I found solution, it's just my mistake. In nodes, I do update Z factor of node and that node was basically not above the water shader, even though it was in editor. So I just decreased Z value for like 50 points and there we go, it's working.

Thanks for replies by the way, consider this one as close. See you!
