### ISSUE TITLE
Compiled windows 64bit version does not work.

### ISSUE THREAD

**Issue by nobnob2015** [godotengine/godot#11302]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10. HD6000 Integrated Intel 

**Issue description:**
After compiling the 64 version, the application would not run.
Debug window gave an error of:
Couldn't open C:\godot\bin/godot.windows.tools.64.exe.pck
Couldn't open godot.windows.tools.64.exe.pck
Couldn't load/find C:/godot/bin/project.godot or project.binary
Couldn't load/find C:/godot/project.godot or project.binary
Couldn't load/find C://project.godot or project.binary

There is also a popup:
Can't Create An OPenGL 3.3 Rendering Context.

NB: If I run the downloaded windows 64bit version (2.1.4) it all works perfectly.

**Steps to reproduce:**
Compile according to instructions and execute the exe.

**Link to minimal example project:**

**Comment by marcelofg55** [comment]
Seems like your GPU doesn't supports OpenGL 3.3.
Godot 2.1.4 uses OpenGL 2.0.

**Comment by Calinou** [comment]
The [Intel HD Graphics 6000](https://en.wikipedia.org/wiki/Intel_HD_and_Iris_Graphics#Capabilities) graphics processors support OpenGL 4.4 on Windows, and OpenGL 4.5 on Linux – both of them warrant OpenGL ES 3.0 compatibility.

Make sure your drivers are up-to-date; if they are, then this is a probably bug in Godot (since it definitely should run on a Broadwell IGP).

**Comment by BastiaanOlij** [comment]
Is this the editor or runtime version?

Note the messages at the startup about opening the project file are just informational. There is an issue on windows that has been fixed (and now merged in master) where .exe is still part of the pck file name (my bad) so if this is a runtime that will prevent it from loading your project.

But indeed, if it is the OpenGL 3.3 context not being created then I have no idea whats going on.

Note that you compiled Godot 3 (master), not Godot 2.1.4 and as Marcelo mentioned, Godot 2 only uses OpenGL 2

**Comment by nobnob2015** [comment]
Apologies for the late reply.

It was my graphics card, it had OpenGL 3.1, I bought a new cheap Nvidia and it has OpenGL 4.1, all works fine.
