### ISSUE TITLE
Display of color in debugger

### ISSUE THREAD

**Issue by RaTi17** [godotengine/godot#11318]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04 LTS, Godot 3.0, Intel HD Graphics 5500

**Issue description:**
Display of color in debugger gets text "ERROR" repeated put on top of it.
Expected was display of that color without transparency

**Steps to reproduce:**

```
var red = Color8(255, 0, 0, 0)

func _ready():
    pass
```

Set a breakpoint at the 'pass' statement and look at the member 'red' in the debugger when running the scene.
The color itself is 'shown' (transparency is 100% in this example), but it also gets the text "ERROR" displayed on top of that.
Maybe alpha should be 1.0 (or 255) for drawing a color in the debugger, what would it actually show behind the debugger itself ?

![screenshot from 2017-09-16 12-25-51](https://user-images.githubusercontent.com/2351444/30511457-df7f3d7e-9ad9-11e7-8a00-0e73fc65a4ec.png)

**Comment by Noshyaar** [comment]
Can confirm. Nodes with color property like CanvasItem also have this issue in Inspector.

**Comment by toger5** [comment]
This is caused by not having a texture for transparency background and the default used when not finding a texture is "error"...
The texture got added recently and implented for color button and color picker. Maybe ITA not merged yet or it does not support tree class...

**Comment by djrm** [comment]
The result you are expecting is not very logical since it simply displays the color you specified. but yeah, the error background is already solved by #11288

**Comment by RaTi17** [comment]
You're right @djrm , the color is displayed, got confused by the error text. It's not really an error then.
I'll close this cheers.
