### ISSUE TITLE
Discussion about the new default script editor font

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#11321]
I was trying out the latest editor changes, when I noticed the new default script editor font, Mononoki (the screenshot was taken on Windows):

![Mononoki on Windows](https://user-images.githubusercontent.com/180032/30511862-5ffc98a4-9ae2-11e7-96c8-4e1cd58b55e1.png)

*(Note: click on the images to display them in a new tab, at 1:1 size)*

It looks less readable to me, compared to the previous script editor font (Source Code Pro). I've found Hack to be a very nice programming font, so I may be biased, but I feel like it's still important to start a discussion on this – readability of the default fonts used in the editor is essential to a good user experience.

@djrm sent me this screenshot of the Mononoki font on Linux, it looks better, but it's still less readable than most of the fixed-width fonts I'm used to:

![Mononoki on Linux](https://user-images.githubusercontent.com/180032/30511864-6002c8f0-9ae2-11e7-9864-be31931ca0ea.png)

He tried out the [Hack](https://sourcefoundry.org/hack/) font, and it looks much more readable. On this screenshot, it's a bit large, but its size could be lowered a bit and it still could be very readable:

![Hack on Linux](https://user-images.githubusercontent.com/180032/30511915-490c4698-9ae3-11e7-9261-de3c6cd360ae.png)

(The license of Hack is a custom one, it's similar to the SIL OFL, but it still is [DFSG-compatible](https://packages.debian.org/sid/fonts-hack-ttf) so it should be good.)

Feel free to voice your opinion below :)

**Comment by fire** [comment]
I'm also familiar with Fira Mono (which Fira Code is based on, but ligatures are very weird..)

https://fonts.google.com/specimen/Fira+Mono

**Comment by Noshyaar** [comment]
Related: #11253 #11309

**Comment by guilhermefelipecgs** [comment]
I agree, I dont liked the new font too, less readable in my opinion. I usually use dejavu but maybe hack could be good. I need test.

**Comment by Arjan219** [comment]
Personally i'm very biased towards Deja-Vu Sans Mono. It's very clear and pleasant on the eyes.

![](https://spin.atomicobject.com/wp-content/uploads/20160627195755/dejavu-sans-mono-ss-590x360.png)
[The licence](https://dejavu-fonts.github.io/License.html) says Deja-vu is public domain right in the first sentence. So i'm sure that's compatible.

**Comment by guilhermefelipecgs** [comment]
Comparasion of HackRegular and DejaVuSansMono inside godot with 14px:

Hack:
![2017-09-16-115857_667x703_scrot](https://user-images.githubusercontent.com/1387165/30513237-734e4f30-9ad6-11e7-8da9-bd7b53485199.png)

DejaVu Sans Mono:
![2017-09-16-115650_658x700_scrot](https://user-images.githubusercontent.com/1387165/30513221-364cc0b2-9ad6-11e7-8543-2a87a03750cf.png)

I prefer DejaVu, Hack IMO don't work very well in small sizes, number 0 is very strange in Hack.

**Comment by guilhermefelipecgs** [comment]
Complementing:
Monoki:
![2017-09-16-122916_395x161_scrot](https://user-images.githubusercontent.com/1387165/30513516-f7fd798c-9ada-11e7-91c3-ebe689a1edc4.png)
DejaVuSansMono:
![2017-09-16-123024_398x148_scrot](https://user-images.githubusercontent.com/1387165/30513518-090e9e18-9adb-11e7-9e8e-a8d2362fb5c6.png)
HackRegular:
![2017-09-16-123040_400x157_scrot](https://user-images.githubusercontent.com/1387165/30513520-109d9436-9adb-11e7-86b5-c5286262a74f.png)

**Comment by Calinou** [comment]
DejaVu Sans Mono looks good as well (and pretty close to Hack, in fact, it seems to render better in Godot than Hack, which I haven't tried in Godot).

**Comment by djrm** [comment]
You guys have to admit that symbols in mononoki are great, perfectly identifiable, like * % -, also the 0 (zero)

**Comment by eon-s** [comment]
DejaVuSansMono looks better to me.

**Comment by guilhermefelipecgs** [comment]
I think I find a bug in Godot, when I use DejaVu and Hack with 13px and 14px they has the same size, this affects how DejaVu render the symbol minus "-". Normally dejavu is well aligned.

Dejavu 13px size (with minus aligned with equal):
![2017-09-16-144450_404x135_scrot](https://user-images.githubusercontent.com/1387165/30514589-76ad80f2-9aee-11e7-9fb2-abeaa509722e.png)

DejaVu 14px size (desaligned):
![](https://user-images.githubusercontent.com/1387165/30513518-090e9e18-9adb-11e7-9e8e-a8d2362fb5c6.png)

**Comment by NathanWarden** [comment]
DejaVuSansMono is my vote. Hack is a very close second. I like that Hack looks a bit more vibrant. Monoki is a nice looking font, but as far as code goes makes it much less readable (IE the font seems to become more important than the code). So, while it looks nice, my vote is no for Mononoki.

If DejavuSansMono would look like it does in Arjan219's screenshot, my vote is a definite no, as it's very overbearing (I'm guessing he's using bold?). As long as it looks like it does in guilhermefelipecgs's screenshots above, my vote is yes to DejavuSansMono!

**Comment by djrm** [comment]
what about noto mono, it goes well with godot, since it uses noto sans

![screenshot from 2017-09-16 21-47-34](https://user-images.githubusercontent.com/1103897/30517552-1422fe40-9b29-11e7-86c5-2e7074a30d35.png)

**Comment by fire** [comment]
+1 for noto mono. It matches noto sans.

**Comment by hickop** [comment]
Would be great to have choice. I personnaly like Inconsolata: https://fonts.google.com/specimen/Inconsolata

**Comment by Calinou** [comment]
Noto Mono also is a good choice, but it lacks bold and italic variants (which Godot currently can't make use of, but if support for making syntax highlighting themes use font variants is added, then this would become a problem).

**Comment by djrm** [comment]
@hickop you will be able to choose the font you like best, but we are discussing the default godot font.

**Comment by reduz** [comment]
any agreeement so far? :)

**Comment by guilhermefelipecgs** [comment]
Apparently Hack wins.

**Comment by guilhermefelipecgs** [comment]
I think we can close this discussion, right?

**Comment by djrm** [comment]
Hack is the new font now.

**Comment by Calinou** [comment]
I guess this can be closed then :)
