### ISSUE TITLE
Cannot load GDNative library

### ISSUE THREAD

**Issue by maxim-sheronov** [godotengine/godot#11335]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch linux, godot 3.0 master branch

**Issue description:**
I am trying to get working GDNative library.
When I do `gdn.initialize()` I get an error:
Can't open dynamic library: [...]/libextensions.so. Error: [...]/libextensions.so: undefined symbol: _ZN5godot14_RegisterState19nativescript_handleE

I am afraid, that it can be problem on linux. Yesterday I was trying the same on Windows, and library was loaded. But I was getting error when try to call some methods. But it was yesterday's master, so I don't know if some changes in master branch could cause it. And I can't check it on windows right now.

I could try to find some solution if someone can give me a direction to search, because for this moment I don't know what can be wrong.

**Comment by maxim-sheronov** [comment]
@karroffel could you look at this? Maybe something wrong with cpp_bindings?

**Comment by karroffel** [comment]
Ah yes, I still need to work on that stuff, it's far from optimal yet, also there's a PR pending that will change some non-user facing stuff too soon.

**Comment by maxim-sheronov** [comment]
@karroffel can I do something with it? Maybe there is some workaround? Because for now I can't use it. Maybe you can give me some direction to find solution of this problem?

**Comment by karroffel** [comment]
@maxim-sheronov take a look at the GodotGlobals.cpp I think, it has the actual C callbacks which in turn call C++ callbacks. The `godot_nativescript_init` is actually not needed if you're just using GDNative and `.initialize()`, that probably is the root of the problem.

**Comment by maxim-sheronov** [comment]
I think not. You can see in error message symbol _ZN5godot14_RegisterState19nativescript_handleE. And it is undefined. I found this `void *_RegisterState::nativescript_handle;` in GodotGlobals.cpp
So it is in cpp_binding library, but it isn't in my own library (because it uses only headers, and linker don't use it from cpp, so it us undefined)
I tried to move it from cpp to hpp, and it helps, now this symbol is defined.

But after that I get other error. `undefined symbol: _ZN5godot6StringC1Ev`
And this is harder, so I don't know what is it.

But from all of this I think, that there are some linking problems. Because my library has undefined symbols.
Maybe you know (I don't have much experience here) why on Windows you should pass cpp_bindings library and engine's to linker to get working dll. But on Linux you shouldn't. So on Linux you got builded shared library but with undefined symbols.

**Comment by maxim-sheronov** [comment]
There is output of `ld bin/libextensions.so`

bin/libextensions.so: undefined reference to `godot::String::String()'
bin/libextensions.so: undefined reference to `godot::Variant::operator godot::Object*() const'
bin/libextensions.so: undefined reference to `godot_alloc'
bin/libextensions.so: undefined reference to `godot::Variant::~Variant()'
bin/libextensions.so: undefined reference to `godot::Variant::Variant(godot::String const&)'
bin/libextensions.so: undefined reference to `godot_free'
bin/libextensions.so: undefined reference to `godot::Variant::operator godot::String() const'
bin/libextensions.so: undefined reference to `godot_nativescript_register_property'
bin/libextensions.so: undefined reference to `godot::Godot::print(godot::String const&)'
bin/libextensions.so: undefined reference to `godot_nativescript_register_method'
bin/libextensions.so: undefined reference to `godot::String::~String()'
bin/libextensions.so: undefined reference to `godot_variant_new_nil'
bin/libextensions.so: undefined reference to `godot::String::operator=(godot::String const&)'
bin/libextensions.so: undefined reference to `godot::Variant::Variant(godot::Variant const&)'
bin/libextensions.so: undefined reference to `godot_nativescript_register_class'
bin/libextensions.so: undefined reference to `godot::Variant::get_type() const'
bin/libextensions.so: undefined reference to `godot::Variant::operator=(godot::Variant const&)'
bin/libextensions.so: undefined reference to `godot::Object::get_class() const'
bin/libextensions.so: undefined reference to `godot::Object::is_class(godot::String) const'
bin/libextensions.so: undefined reference to `godot::Variant::Variant()'
bin/libextensions.so: undefined reference to `godot::String::String(char const*)'

**Comment by karroffel** [comment]
> because it uses only headers

Those things defined in the headers are implemented in the .cpp files, you need to link to those, that stuff is not part of Godot.

**Comment by maxim-sheronov** [comment]
@karroffel Really it was my fault again. Sorry for that :smile: 
I didn't pass godot_cpp_bindings to linker, that's why I got this errors.
