### ISSUE TITLE
Mouse right click on filesystem's panel (feature)

### ISSUE THREAD

**Issue by gmarais** [godotengine/godot#11336]
This is more a suggestion than a real issue it would apply to any OS.
I am currently working with Godot 2.1.4.

Basically to add a faster and handier way to move around/create/rename files and directories directly from godot's FileSystem panel.
Right clicking on the background would give us option to create a new directory or file.
Right clicking of a directory/file would allow us to rename/delete/copy it.
etc...

An other benefit would be that creating directories, renaming and moving files outside of Godot does loose dependencies  but in Godot we might be able to do all that with additional look ups.

When working on a large project I often find myself wanting to sort my files differently or move things from growing directories to keep things dry for the eyes and organized.
These changes would allow large projects to be easily managed all from the Godot engine without having to open an explorer window, 3rd party editor or terminal aside.

**Comment by toger5** [comment]
Is move by drag and drop supported. If not that also would make things faster

**Comment by puppetmaster-** [comment]
Someone should make a suggestion/feature request list for the filesystem's panel.
I have also some suggestion in my mind. 😄

**Comment by mhilbrunner** [comment]
Fixed in Godot 3/master (partly https://github.com/godotengine/godot/pull/11428 but other PRs too I think)
