### ISSUE TITLE
Any way to disable backtrace Dumping?

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#11347]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0

**Issue description:**

I cannot debug the editor with my debugger with crash breakpoint anymore.  As the exceptions are *handled* by the backtrace dumping.

**Comment by marcelofg55** [comment]
Yeah, use --disable-crash-handler

**Comment by fire** [comment]
Can someone add this to a document somewhere?

**Comment by akien-mga** [comment]
I thought the crash handler was supposed not to be conflicting with external debuggers?

**Comment by marcelofg55** [comment]
It wasn't conflicting with gdb when I tested it. @Geequlim is this with visual studio?

**Comment by hpvb** [comment]
I can confirm it does not conflict with gdb (neither crashes nor breakpoints).

**Comment by Geequlim** [comment]
@marcelofg55 
I use C++ debugger for VSCode on Windows for my working machine.
The godot editor crashed but the debugger cann't give me a breakpoint with that as the exception is *handled* by backtrace dumping.
