### ISSUE TITLE
Search and replace's close button error in Script Editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11341]
**Ubuntu 17.04 - Godot Build: f9f5838**

**Issue description:**
Self-explanatory:

![screenshot at 2017-09-16 20-57-33](https://user-images.githubusercontent.com/30739239/30517066-f3c1d932-9b28-11e7-9eae-dc969d245adb.png)

**Comment by Noshyaar** [comment]
Can confirm for latest master 1679baf.
However, for me it only happens when mouse-hovered.

**Comment by Noshyaar** [comment]
CC @djrm
