### ISSUE TITLE
Godot 3 - issue with project file on Windows

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#11344]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot master 17 September 2017
Windows 10 
Don't know if other platforms are effected

**Issue description:**
Project file is loaded incompletely after export on windows, see errors pasted below:
```
ERROR: decode_variant: Condition ' (type & 0xFF) >= Variant::VARIANT_MAX ' is true. returned: ERR_INVALID_DATA
   At: core\io\marshalls.cpp:98
ERROR: decode_variant: Condition ' err ' is true. returned: err
   At: core\io\marshalls.cpp:542
ERROR: Error decoding property: input/move_left
   At: core\project_settings.cpp:471
ERROR: decode_variant: Condition ' len < 4 ' is true. returned: ERR_INVALID_DATA
   At: core\io\marshalls.cpp:93
ERROR: Error decoding property: ight4
   At: core\project_settings.cpp:471
ERROR: decode_variant: Condition ' len < 4 ' is true. returned: ERR_INVALID_DATA
   At: core\io\marshalls.cpp:93
ERROR: Error decoding property:
   At: core\project_settings.cpp:471
ERROR: decode_variant: Condition ' len < 4 ' is true. returned: ERR_INVALID_DATA
   At: core\io\marshalls.cpp:93
ERROR: Error decoding property:
   At: core\project_settings.cpp:471
```
Looks like there is some corruption in exporting the input map

**Steps to reproduce:**
Configure a project with input mapping, export to a pck file, run pck file, input mapping doesn't get setup

**Link to minimal example project:**

**Comment by BastiaanOlij** [comment]
It loads the project file for me now, must have had a typo in the filename. Ran into a different issue but I think this part of it is working. If someone can verify creating and loading pck files on other platforms that be cool :)

**Comment by reduz** [comment]
that was broken and i fixed it recently, so its probably fixed now

**Comment by reduz** [comment]
this looks like broken actions issue (which was fixed long ago) using an old template.. should still test, though
