### ISSUE TITLE
More one-way collision issues

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#11357]
**Operating system or device, Godot version**
Linux Mint 18.2 Cinnamon x64, Godot master d22ceee

**Issue description:**
@reduz on IRC asked that I create this issue for him to keep track with. It covers two problems:
1. The "falling through floor" bug still persists
2. `is_on_floor()` seems to return `true` prematurely when jumping through a one-way collision under certain conditions

**Steps to reproduce:**
You should be able to reproduce these problems with [this sample project I created](https://github.com/godotengine/godot/files/1309114/onewaycollisionproblem.zip)

For the "falling through floor" bug:
1. Jump a lot (Z or up arrow to jump)
2. You'll eventually fall through the platform
3. It could take up to a few dozen or so jumps for it to happen, or you might get lucky and fall through after three or so.

For the `is_on_floor()` issue:
1. Head left towards the first wall you encounter
2. While holding left arrow against the wall, attempt to jump to the platform right above you
3. The player should get stuck there until left arrow is released. This is due to my code setting vertical velocity to something very low when on the floor.

**Comment by toger5** [comment]
Is that 2d or 3d.
In 3d this is also the case I think.
Also it is referring to Kinematic body? (is_on_floor() )

**Comment by reduz** [comment]
@toger5 there is no one way collision in 3D... (and probably won't ever be)

**Comment by toger5** [comment]
Okay than its unrelated...

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by justinluk** [comment]
Hi @akien-mga - this is a block for me now. I'm using one way platforms with a character that has a capsule collider. I think it's related to this issue #10971. Seems like a fix was made for rectangular collisions shapes but not circular or capsule.
