### ISSUE TITLE
Filesystem right menu not localized to mouse/file icon when populated with many files

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#11354]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64 bit
Radeon 390 8GB
Godot 3.0 https://bintray.com/calinou/godot/editor/2017-09-13.b9fddc5

**Issue description:**
_What happened:_
I imported  around 17 dae files to a folder in godot. Godot made it's files so there was a total of 52 files. as you scroll down the list the right click menu moves further away from the mouse/file icon
_What was expected:_
The right click menu to open next to the mouse icon
**Steps to reproduce:**
Put alot of files in the godot project directly.
Scroll down as far as possible.
Click the top few rows of file list.

**Link to minimal example project:**
https://i.imgur.com/Rfaxapv.png

**Comment by groud** [comment]
Fixed in #12211
