### ISSUE TITLE
CPU usage 20-30% higher in HTML export when compared to ran from editor. 

### ISSUE THREAD

**Issue by stubbsy345** [godotengine/godot#11358]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.4 and HTML5 export. 

**Issue description:**
My game runs very well from the editor and indeed runs well in html5 export. However, in the html5 export about 20% - 30% on average more cpu is used. I have `OS.set_low_processor_usage_mode(true)` in my singleton code but doesn't seem to be improving the export. I also have `enable_run` in my export unchecked to attempt to improve performance. Any advice on how to improve performance further. Currently the game runs well but sets the fan going very quickly which is affecting user experience when playing the game.

**Comment by fliar** [comment]
in my case, I'm using a lot of ui items ( about 6 hundreds buttons ), which should update only when it is changed, so OS.set_low_processor_usage_mode(true) worked well for me, this is not related to #424 

but enable_run is another problem, which made the editor always updating it self, not the game

**Comment by stubbsy345** [comment]
Did this also work for your HTML export? OS.set_low_processor_usage_mode(true) works well locally but i don't know if this translates for HTML5. I am also using a lot of UI items, including line edits for searches which also create a lot of buttons within a scroll container.

**Comment by fliar** [comment]
i didn't test cpu performanxe on html export, and i'm not suprised if it is higher.
maybe it is better for you to test it on your own machine to clearify your problem ?
i've uploaded to itch.io, just a simple mine-sweeping game
https://fliar.itch.io/mine

**Comment by mhilbrunner** [comment]
Would be helpful to have numbers on what expected (and acceptable) overhead would look like, as there always is going to be *some* when exporting for the web, as the are more layers between your code and the hardware.

Have comparable engines less than 20% overhead when exporting to HTML5 targets?

**Comment by mhilbrunner** [comment]
Closing this, as it's too vague to debug. Please try to pin down what is causing the issue or provide and example project. Things to test:

- Is the performance fine with an empty scene?
- If yes, which part of your setup tanks the performance? Audio? Certain nodes? 2D? 3D?

Feel free to open a new issue and provide details for us to help you improve the performance of either your project or Godot.
