### ISSUE TITLE
Visual bug : AudioEffect don't deselect if only one effect per bus

### ISSUE THREAD

**Issue by Nutriz** [godotengine/godot#11355]
**Versions**
Windows 8 64 bits, Godot 3.0alpha1

**Issue description:**
Visual bug : AudioEffect don't deselect if only one effect per bus

**Steps to reproduce:**
Add one bus or more
Add one AudioEffect in each bus
Select AudioEffect in bus 1, select AudioEffect in bus 2
The AudioEffect in bus 1 is steel highlighted

![image](https://user-images.githubusercontent.com/7358899/30427545-7dc1a764-9950-11e7-9f09-51ad84c76887.png)

**Comment by djrm** [comment]
this is not critical, it is just a minor annoyance, also this has to be solved for most of the GUI elements, so i think should be moved to another milestone.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by akien-mga** [comment]
This is still reproducible in 3.2.3 RC 1. It's only a cosmetic issue.

**Comment by DashCell** [comment]
I create a Pull request:  #42032  for this issue, i don't know how to  attach it here.

**Comment by DashCell** [comment]
#42035

**Comment by BlueCube3310** [comment]
Fixed by #85879
