### ISSUE TITLE
RichTextLabel gets clipped on window resize

### ISSUE THREAD

**Issue by aaronkuchma** [godotengine/godot#1136]
I've got a 2D game I'm building, and everything seems to be going well, however the windows (not sure if other platforms are affected) binary exhibits problematic behavior.

The project settings are 470x320 width, stretch mode 2d, stretch aspect keep, resizable.

One of the popups I create is a TextureFrame with a RichTextLabel positioned inside it.

Everything is fine when you start the game, or when you stretch it proportionally (e.g. 940x640).

However, there is a problem when you stretch the screen too tall or too wide (so that black bars are created e.g. 1280 x 640).

When this happens, the RichTextLabel is clipped proportionate to the extra black bar space. The wider you make it, the more clipping on the left/right. The taller you make it, the more clipping top/bottom.

Is there something I've missed in terms of settings, or is this a bug with the engine?

I have confirmed that the problem exists on Android and Windows.

**Comment by UsernameIsAReservedWord** [comment]
got a similar clipping bug with the Tree node.

you can reproduce it directly into the 2D editor by zooming-in and zooming-out with the mouse.

tested with recent custom build of yesterday, with official 1.0stable and even with the old RC2, all win64.

**Comment by UsernameIsAReservedWord** [comment]
PS : more precisions : into Project Settings : display `width=800`, `height=480`, `stretch_mode=2d`, `strech_aspect=keep`

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by mohaalak** [comment]
@akien-mga I test it with 2.0.1 , you can close it.
