### ISSUE TITLE
Missing color for help dialog in Light Theme

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#11366]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master branch

**Issue description:**
![2017-09-17-151136_359x107_scrot](https://user-images.githubusercontent.com/1387165/30523600-8b5ec8e0-9bba-11e7-8a30-774f6bac2f38.png)

**Comment by toger5** [comment]
@djrm should be relativly easy to fix. Probably introduced in the cleanup?

**Comment by djrm** [comment]
maybe thats not updating, the code seems fine.

**Comment by toger5** [comment]
@guilhermefelipecgs can you restart godot with the setting white theme active and check if it is still dark

**Comment by guilhermefelipecgs** [comment]
Tested, nothing change when I restart.
I also execute `rm -rf ~/.godot/` to reset all the settings.
