### ISSUE TITLE
Can't compile Android-Export-Template

### ISSUE THREAD

**Issue by yuyoDev** [godotengine/godot#11377]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Archlinux64b AMDFX8350 GodotMaster-Repository

**Issue description:**

Error compiling
[ 77%] Compiling ==> thirdparty/nanosvg/nanosvg.cc
[ 77%] Compiling ==> thirdparty/recastnavigation/Recast/Source/Recast.cpp
[ 77%] Compiling ==> thirdparty/recastnavigation/Recast/Source/RecastAlloc.cpp
thirdparty/recastnavigation/Recast/Source/Recast.cpp:26:10: fatal error: 'new' file not found
#include <new>
         ^~~~~
1 error generated.
scons: *** [thirdparty/recastnavigation/Recast/Source/Recast.android.opt.armv7.neon.o] Error 1
scons: building terminated because of errors.

**Steps to reproduce:**
used:
scons platform=android target=release builtin_openssl=yes -j 7

**Comment by henkz1** [comment]
you can use builtin_recast=no until its fixed

**Comment by yuyoDev** [comment]
Tanks henkz1 but dont work :(

[Initial build] Compiling ==> editor/editor_fonts.cpp
In file included from editor/editor_node.cpp:87:
In file included from ./editor/plugins/navigation_mesh_editor_plugin.h:37:
./editor/plugins/navigation_mesh_generator.h:45:10: fatal error: 'Recast.h' file not found
#include <Recast.h>
         ^~~~~~~~~~
[Initial build] Compiling ==> editor/run_settings_dialog.cpp
1 error generated.
scons: *** [editor/editor_node.x11.opt.tools.64.llvm.o] Error 1
scons: building terminated because of errors.

**Comment by henkz1** [comment]
looks like you tried to build with tools for x11
did you add it to the other options? like: "scons platform=android target=release builtin_openssl=yes -j7 builtin_recast=no"

**Comment by yuyoDev** [comment]
Thank you henkz1 ;), I made a typo.
Works with: builtin_recast=no

**Comment by volzhs** [comment]
isn't it same issue with #11273?

**Comment by akien-mga** [comment]
Duplicate of #11273.
