### ISSUE TITLE
Rotation of tiles in tilemap should also rotate collision shape

### ISSUE THREAD

**Issue by Vega-KH** [godotengine/godot#11374]
**Issue description:**
When you add a rotated or mirrored tile to a tile map, the collision shape is not rotated with it. 

**Steps to reproduce:**
1. Open the isometric example from the official examples.
2. Run the game in the simulator.
3. Try to collide with the doors that were added with the mirror / rotate option. 
4. Notice that the collision doesn't match because only the visual element was rotated, not the collision.

I haven't tested this yet with gridmaps, but I suspect the same issue may be present.

**Comment by bojidar-bg** [comment]
Cannot confirm on master branch, probably 2.1-only

**Comment by Listwon** [comment]
@Vega-KH Please provide the minimal example project, because I can't reproduce your bug in the isometric example (Godot 2.1.4-stable_win64).

**Comment by Vega-KH** [comment]
Closing as this issue was a duplicate and fixed by #13216 .
