### ISSUE TITLE
Just pressed and released info for Input Actions

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#1137]
Hey, there. So, there's no "Just Pressed" or "Released" functions for input Actions; I think they would be really useful to assist in programming in input. Interestingly, there's isEcho() for InputEvents which could help, but there's no tutorial or help on using them.

**Comment by SolarLune** [comment]
Yeah, but there's no tutorials on using them - when and how would I get a non-generated input event?

**Comment by reduz** [comment]
https://github.com/okamstudio/godot/wiki/tutorial_input_events

**Comment by ndee85** [comment]
SolarLune,
for that exact same reason I have written my own input class, which just uses the actions.
Take a look at this example project. This is exactly what you need :D
I have mapped it to 0,1,2,3. So its the same as in the bge.

Here is an example how to is it later:
if (btn.check() in [1,2]):
    do stuff

https://www.dropbox.com/s/x5trykq1t4t6mp0/input_states.zip?dl=0

**Comment by mamarilmanson** [comment]
:+1: for this feature... I also am trying to implement this to pause the game and go to the menu if I "just realeased" the ESC button... but (let's say 1 is pressed and 0 is not pressed) when I tap escape for as fast as I could the function I made to check if it is pressed returns 101 or 11101 in just milliseconcs apart which is frustrating... 

hope it gets implemented... 

:)

**Comment by ndee85** [comment]
Here is also a link to a github project where I use my input states:
https://github.com/ndee85/gBot/blob/master/projectfolder/scripts/input_states.gd

**Comment by mamarilmanson** [comment]
uhm... can you explain how the script works? not how to integrate it but why this line works and that line works... :)

**Comment by ndee85** [comment]
I don't want to spam that topic here. But in short it works that way:
You create to variables. One which stores the old button state, and a second which stores the current state. That is done in the check() function. (line 18 and 19)
Once you have the old button state and the current button state you just need to compare both.
From there you can conclude if you just pressed or just the released the button. And that showed with the digits 0,1,2,3. (from line 23)
So you just have to see what the check() functions returns. Thats it.
In the gbot project you can see how to use that class in your project. Fairly simple.

**Comment by punto-** [comment]
What is a "non-generated" input event?

to do what you need, you need to call "set_process_input(true)" on your
"_ready()" method (or whenever you're ready to start receiving input). Then
create a _input(event) method with something like this:

func _input(event):
  if event.is_action("pause") && event.is_pressed() && !event.is_echo():
    # show pause menu here

Create an input event called "pause", assign "esc" key to it (also the
joystick start button :p ). This will show pause menu even if you press and
release the key between 2 frames.

**Comment by SolarLune** [comment]
^ OK, I think that's what I was missing. I meant "non-user-generated input event"; it seemed like only user-created input events were outlined in the docs (how to make the game think a key was pressed). Thanks for the example, @punto-.

**Comment by akien-mga** [comment]
It looks to me like ```is_echo()``` is all that is needed to address this feature request, or am I missing something?
