### ISSUE TITLE
Copy the viewport camera's transform to a selected node

### ISSUE THREAD

**Issue by ScottMakesGames** [godotengine/godot#11385]
Please add the ability for me to set a selected node's transform to match the current viewport camera's transform.

This could be a shortcut that works universally for any node activated by:
- A default keyboard shortcut (could be **ctrl+t** for transform? appears to be currently unused)
- A button in the toolbar above the viewport

Expected usage:

- Select any node in the scene tree
- Position your viewport camera (using the already implemented free-look features) to where you want the node's new transform
- Activate the shortcut to copy the transform from the viewport camera to the selected node

Result:
- The selected node would now be in the same position, with the same rotation as the viewport camera.
- Any geometry associated with the selected node would now be encasing the viewport camera.
- Scale should probably be left untouched. _Edit: Perhaps the wording of this issue should use Translation and Rotation instead of Transform._

Use case:
- Positioning a Camera node above and looking at a character
- Compositing scene objects to face one another

**Comment by homer666** [comment]
Unless I'm mistaken, you can already do this with Ctrl-Alt-F, or by selecting the last option in the viewport menu (accessed by clicking the grey `[ Perspective ]` text on the top-left of the viewport)

**Comment by ScottMakesGames** [comment]
@homer666 You're right, that does exactly what I was describing. Thank you for pointing it out!
