### ISSUE TITLE
Textures in shaders do not use the correct color space

### ISSUE THREAD

**Issue by cart** [godotengine/godot#11381]
It looks like the wrong color space is being used in custom shaders

Texture (PNG / SRGB):
![image](https://user-images.githubusercontent.com/2694663/30525909-3cae1d44-9bc5-11e7-9851-8674a2bb6b33.png)

Spatial Material (shadeless, colors look correct):
![screenshot from 2017-09-17 16-24-18](https://user-images.githubusercontent.com/2694663/30525915-60d0516a-9bc5-11e7-8385-12cd91e6fd36.png)

Shader (```render_mode unshaded;```, ```ALBEDO = texture(albedo_texture, vUv);```, png texture loaded using a sampler2D uniform, colors are wrong):
![screenshot from 2017-09-17 16-23-03](https://user-images.githubusercontent.com/2694663/30525917-7daebc22-9bc5-11e7-8aba-8f2c735fab2a.png)

Import Settings:
![screenshot from 2017-09-17 16-27-02](https://user-images.githubusercontent.com/2694663/30525932-d502c5c2-9bc5-11e7-970b-b06d6a9bd5e2.png)

**Comment by cart** [comment]
There is a way around it: you need to use the "hint_albedo" hint when declaring the texture uniform to get the right colors.

```uniform sampler2D color_texture : hint_albedo;```

It feels like using the correct colors should be the default and not something hidden behind a flag.

**Comment by akien-mga** [comment]
That seems a confusion due to the sRGB / linear conversion in GLES3, so I'll close as duplicate of #24992 (which is partially fixed by docs improvements). CC @clayjohn in case I misinterpreted.
