### ISSUE TITLE
Misplaced and glitchy shadows for all lights

### ISSUE THREAD

**Issue by soloparatolos** [godotengine/godot#11390]
Windows 10, Godot 3.0 master 09/17/2017, AMD Radeon HD 7770
Antergos (Arch), Godot 3.0 master 09/17/2017, Intel HD 4000

**Issue description:**
Godot aims to have an state of the art renderer on par with other actual engines and at the same time become an "easy to use" tool. We have a problem with the shadows for quite a long time  that goes against that goals.

All the lights produce shadows out of place (out of the box) and adjusting the bias to right place creates glitches.

**1. Omni Light** 

- Cube : 
The default bias is [0.1](https://imgur.com/ntcF9DS)5 but the shadows are on place with bias around [0.02-0.04](https://imgur.com/EGZ70OO).  The position of the shadows between editor and ingame are different. The shadows in the correct position show glitches in both editor and in game.

- Paraboloid:
The default bias is [0.15](https://imgur.com/S4qxxic) but the shadows are _almost_ on place with bias
[around 0](https://imgur.com/T4xFy6W). With this value glitches are shown both editor and in game. The position of the shadows between editor and ingame are different. With paraboloid it's imposible to get the shadows exactly in its correct place.

**2. Spot Light**

The default [bias is 0.15](https://imgur.com/8ZyOp5T) but the shadows are on place with bias [around 0](https://imgur.com/IkssMVV). With this bias, artifacts show up in the editor but look fine in game.

**3. Directional Light**

The default [shadow bias is 0.1 and the light default normal bias is 0.8](https://imgur.com/8ZyOp5T) but the shadows are _almost_ on place with bias [around 0 and light normal bias <= 0.20](https://imgur.com/8kkRiOG).  This values get artifacts on the editor and in game. In this type of light the amount of gliches in game change depending of the [resizing of the window](https://imgur.com/JgXn0Qj). It's imposible to get the shadows exactly in its correct place without big amounts of artifacts.

_For the "ease to use" aproach we cant just force the user to search the value of the shadow bias to put the shadow where it should be from the begining._

_From the "state of the art renderer" perspective, we need to have shadows that look ok, with an aceptable resolution out of the box and the users should be able to get the correct place for shadows without artifacts._

**Steps to reproduce:**
Just loading an asset and putting any king of light shows this issue, but you can activate/deactivate the types of lights in the demo attached to see the bias behaviour.

**Link to minimal example project:**
[lightBiasTests.zip](https://github.com/godotengine/godot/files/1310515/lightBiasTests.zip)

**Comment by reduz** [comment]
the problem here, from what you describe, is that shadows look different in
editor than when running in-game, that definitely sounds like a bug to me

**Comment by soloparatolos** [comment]
The shadows looking different in editor and in-game is one of the things, yes. But I think that the big problem here is that adjusting the bias to get the shadows in their place creates artifacts in almost every case. And sorry for the big report... I can try to break down this in multiple issues if it's better for you.

**Comment by reduz** [comment]
Shadow mapping itself is a very simple algorithm, there really is no more
we can do than already are doing. Besides changing defaults and fixing
potential bugs (like what you describe where editor and in-game look
different), nothing else can be done.

**Comment by reduz** [comment]
I will close, as I don't think this is a bug
