### ISSUE TITLE
Property custom_image for "Mouse Cursor" seems to be not working

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#11393]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master branch

**Issue description:**
I setted "custom_image" with godot's logo and when I play, the icon doesn't appear.

@reduz Any chance of seeing the hardware-accelerated mouse cursor in 3.0?

**Comment by reduz** [comment]
Not unless anyone wants to work on it

**Comment by reduz** [comment]
Still waiting on the true ultimate hero to implement hardware custom cursor support, will that hero ever arrive and be worthy of Princess Godotina's grace?

![image](https://user-images.githubusercontent.com/6265307/32464542-27b3e578-c31f-11e7-838e-6b2e9cf9e1fb.png)

**Comment by guilhermefelipecgs** [comment]
I think I may implement this for linux and windows, not for mac (because I don't have one).
I'll give a try this week to see what can I do.
Maybe I'll need add thirdparty libs to convert png to cursor format for x11 and windows. It's ok?

**Comment by akien-mga** [comment]
Fixed by #12814 for 3.0 and #13437 for 2.1.
