### ISSUE TITLE
Subsurface scattering does not support transmittance.

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#11398]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 26, Nvidia Proprietary 384.69  bc005a57d38137b062e0ccc26467353f53556930

**Issue description:**

SSS does not support transmittance, here is the SSS demo from sketchfab

![screenshot from 2017-09-18 14-57-13](https://user-images.githubusercontent.com/1103897/30561878-2c5865fe-9c82-11e7-8749-704953d81abe.png)
does not look really nice, but it lets light through thinner parts of the object,

here is how it looks in godot
![screenshot from 2017-09-18 15-04-57](https://user-images.githubusercontent.com/1103897/30562079-e5a8410a-9c82-11e7-8a63-3fed996617f5.png)
![screenshot from 2017-09-18 15-05-43](https://user-images.githubusercontent.com/1103897/30562086-e9295210-9c82-11e7-8d83-87da2c36e478.png)

ping @reduz 

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by reduz** [comment]
What you are looking for is transmittance, which is unsupported. It needs
to be added eventually (still thinking how to do it)

**Comment by djrm** [comment]
@reduz oh, nice, will  change the title then

**Comment by reduz** [comment]
The problem is that, for transmittance to work, shadow mapping needs to be
enabled and objects recieving it need to have culling set in reverse (which
could be automatized I guess). As the effect happens by measuring the
object thickness via shadow map..

**Comment by djrm** [comment]
@reduz yeah i remember reading something like that once, so i was wondering why godot does not ask for a cusom SSS texture, but yeah also saw techniques for generating it.

**Comment by reduz** [comment]
Maybe saketchfab uses a transmittance map?

**Comment by djrm** [comment]
reduz the gltf i downloaded does not have any texture, here it is.

[stanford_dragon_sss_test.zip](https://github.com/godotengine/godot/files/1312365/stanford_dragon_sss_test.zip)

**Comment by Pseudopode** [comment]
Isn't it possible to use the old trick of dual pass rendering ?
**First pass** = render backfaces, largest distance from the camera
**Second Pass** = render frontfaces, closest to the camera
_Distance_ = 2nd Pass - 1st Pass

It's not true for concave objects, but it's a close approximation for real-time
