### ISSUE TITLE
Error running basic html5 build in chrome: 'sampler2DArray' : No precision specified

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#11397]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Mint 18 Sarah
Godot_v3.0-alpha1_x11.64
GPU: Nvidia GeForce GTX 750 Ti
GPU driver: nvidia-375.74-0ubuntu1

**Issue description:**
Game doesn't run in html5 (tried both WebAssembly and asm.js) because an error appears.

> **ERROR**: At: drivers/gles3/shader_gles3.cpp:167:_display_error_with_code() - SceneShaderGLES3: Fragment Program Compilation Failed:
> test-export.html:278 ERROR: 0:78: 'sampler2DArray' : No precision specified

[Full stack trace](https://pastebin.com/96m1vMvg)

**Steps to reproduce:**
1. Create a basic scene with a MeshInstance (cube), Camera and OmniLight
2. Compile to Html5 with WebAssembly or asm.js option selected
3. Run a php local webserver in the exported folder with php -S localhost:8000
4. Open localhost:8000 in Chrome
5. Loading appears, then an error in the console

![screenshot_20170918_144825](https://user-images.githubusercontent.com/2841740/30561405-89ec3760-9c80-11e7-94d5-f0aec2b6b762.png)

**Link to minimal example project:**
[3d-test.tar.gz](https://github.com/godotengine/godot/files/1311999/3d-test.tar.gz)

**Comment by eska014** [comment]
This was already fixed after alpha1 in #10257

**Comment by jahd2602** [comment]
Thanks a lot. How many days should I expect to wait for the next alpha release?
