### ISSUE TITLE
Array variable shared between instances

### ISSUE THREAD

**Issue by santouits** [godotengine/godot#11400]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master, linux 

**Issue description:**
I have a script that I load and then instance it with .new().
Its only job is to initialize an array with Array() and then append to it the number 1.
When I instance the script many times, the array just keeps growing in size, like it is a static variable and is shared between the instances.

**Link to minimal example project:**
[array_test.zip](https://github.com/godotengine/godot/files/1312194/array_test.zip)

**Comment by henkz1** [comment]
I can confirm this, using [] instead of Array() makes it work as expected.
Also it's the same with Dictionary() and {}

**Comment by Noshyaar** [comment]
Probably related: #4114

**Comment by bojidar-bg** [comment]
@Noshyaar Not related, this is actually the opposite issue. The other issues had problems with COW-mode Array(), this issue is something deeper...

**Comment by reduz** [comment]
I guess it could be hacked to be interpreted as a construct

**Comment by reduz** [comment]
The easiest way to fix this is to tweak GDParser and look for assignment of a TK_PR_VAR with a ConstantNode. If it's an array or dictionary, change it for ArrayNode and DictionaryNode:

Relevant code sections:
https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_parser.cpp#L2421
https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_parser.cpp#L3179

Alternatively (and this is probably simpler), we could just forbid Array or Dictionary constructors, relevant code here:

https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_parser.cpp#L592

**Comment by remorse107** [comment]
I think I have the fix.  I just ran a test project with an version before my fix and I am able to recreate the problem.  After my fix it works as you would expect.

**Comment by akien-mga** [comment]
Fixed by #12845.
