### ISSUE TITLE
VSE Bug - Crash on removing Graph Resource

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#1140]
Reproduce:
Simple scene:
> Spatial
>> Test Cube

Add Shader Resource to Cube
Add Graph Resource to Shader Resource
In Shader Resource click Clear the recently added Graph Resource

Crash

**Comment by akien-mga** [comment]
Can you still reproduce this in the current master branch?

**Comment by akien-mga** [comment]
Followed the above steps but couldn't reproduce the crash, so I guess it has been fixed.
