### ISSUE TITLE
Code in worker thread suddenly starts executing on the main thread

### ISSUE THREAD

**Issue by radicaled** [godotengine/godot#11406]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04, Godot 2.1.4.

**Issue description:**

It seems that accessing variables through an array shared between the main thread and a worker thread somehow causes code in the worker thread to start executing on the main thread...? I'm not sure exactly what's going on under the hood; I just see that the result is that my worker thread code is now operating on the main thread, causing jank when intensive calculations are run.

```gdscript
extends Node


var calc_thread = Thread.new()
var mutex = Mutex.new()

var request_queue = []

class PathRequest:
	var start_pos
	var end_pos

func _ready():
	calc_thread.start(self, "_process_requests")
	set_process(true)

func request_path(pathfinder, start_pos, end_pos):
	var pr = PathRequest.new()
	pr.start_pos = start_pos
	pr.end_pos = end_pos

	mutex.lock()
	request_queue.append(pr)
	mutex.unlock()

func _process_requests(parameters):
	while true:
		mutex.lock()
		var request
		var request_count = request_queue.size()
		if request_count > 0:
			request = request_queue[0]
			request_queue.pop_front()
		mutex.unlock()
                # The following loop was used to verify that the thread was running independently;
                # eg, does not lock up the main thread. An infinite loop does not lock up the main thread
                # at this point:
                # while true:
                #    pass

		if request != null:
			print("Processing request: ", request)
                        # This code used to be pathfinding resolution code
                        # But has been removed to simplify the scenario.
                        # The following two lines freezes the main thread:
			while true:
				pass
```

If I never interrogate an object from `request_queue`, then the thread continues on its way merrily.

**Steps to reproduce:**

- Create node
- Add array to node as member variable
- Add thread to node as member variable
- Start thread in `_ready()`
- From the main thread, push items into array (use mutex)
- From the "worker" thread, read an item from that array (use mutex)
- Use item in an if statement (checking to see if one if its members is not null, etc)
- Experience jank, because code following the if statement is now executing(?) on main thread

**Comment by vnen** [comment]
I can't reproduce this. Do you have a sample project?

**Comment by radicaled** [comment]
Afraid not. Can't reproduce it on a clean 2.1.4 build, nor in the original project.

I did upgrade from Ubuntu 16.04 to 17.10 between submitting this bug report and now, so it may have been related to something on my system at that point in time. Feel free to close.

**Comment by vnen** [comment]
Alright. If anyone can reproduce it, attach a sample project in a comment and we'll reopen.
