### ISSUE TITLE
Viewports with Transparent Bg=false and Usage=2D dither alpha

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#11416]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux (Arch), 3.0 62cb43bb8dec8f5078012b58ff06a2077078565f, Intel integrated

**Issue description:**

When Transparent Bg is not checked, viewports with Usage=2D will dither alpha, even on non-transparent backgrounds:
![https://cdn.pbrd.co/images/GL5WXZP.png](https://cdn.pbrd.co/images/GL5WXZP.png)
Left is without Transparent Bg, Right is with Transparent Bg.

Note: Thinking about it, it might be somewhat intended, but the fact that it happens only with usage = 2D is strange..

**Steps to reproduce:**
1. Add a ViewportContainer with a Viewport as an only child.
2. Resize the viewport container so that it takes the whole screen (adjust anchor and margins).
3. Set the viewport to usage = 2D
4. Add some mostly-opaque sprite in the viewport.
5. Add something semi-transparent on top of the sprite.
6. Run the project.

**Link to minimal example project:**
Example using Polygon2D with transparent color: [transparent-bg-viewport.zip](https://github.com/godotengine/godot/files/1314491/transparent-bg-viewport.zip)

**Comment by reduz** [comment]
I would look in drivers/gles3 for any usage of glEnable(GL_DITHER) and remove it. Not sure why this may be enabled.

**Comment by Rycerzyk** [comment]
There are no usages of glEnable(GL_DITHER) in drivers/gles3 but according to [this](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glEnable.xml) GL_DITHER is set by default. Adding glDisable(GL_DITHER) to reset_canvas() method fixed this issue for me.
