### ISSUE TITLE
Change the default GUI nodes theme to match main Godot GUI theme

### ISSUE THREAD

**Issue by jay3d** [godotengine/godot#11413]
![clipboard image](https://user-images.githubusercontent.com/2527637/30589920-00397ae2-9d6f-11e7-8a3e-a6d583b5af84.jpg)

I think it's more consistent and much better to make the default theme of nodes GUI to match main Godot 3.0 theme which is much more elegant and streamlined.

**Comment by volzhs** [comment]
https://github.com/godotengine/godot/issues/7294#issuecomment-297999038
This is why the default theme is different with editor theme.
but yes, we can make fancy default theme too.

**Comment by jay3d** [comment]
I really like the new theme! It's brilliant and refreshing and glad that it became the default.
I would suggest a very basic theme for the "Design time GUI" (for a lack of a better expression :) ), not necessarily similar to Godot's main GUI theme, but made of simple lines in the way of how GUI wire-frame mock-ups are made, which would give it a more WIP look and base graphics to start designing custom themes.
I will work on something if I have some time this weekend.
