### ISSUE TITLE
string.split and string.split_floats writes a 0 on the first entry in the resulting array, instead of the correct value

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#11419]
Consider the following code:
```
func _ready():
	var myVec2String = "(93, 87)"
	var strArr = str(myVec2String).split_floats(',')
	print("vector2 string:",myVec2String," and after split, -->",strArr, " as you can see the first is a zero, instead of 93")
```

This is the resulting print out:
`vector2 string:(93, 87) and after split, -->[0, 87] as you can see the first is a zero, instead of 93`

I am running the stable version of Godot btw

This is particularly bad when you need to read a vector2 from a json file

**Comment by groud** [comment]
When you apply `split_floats(',')` to `"(93, 87)"`, the function intends to transform two strings into floats: "(93" and " 87)", which can't be transformed into valid integers anyway.
Remove the parenthesis and it should work.

**Comment by akien-mga** [comment]
BTW, you can do `str2var("(93, 87)")` if what you're looking for is getting a `Vector2(93, 87)`.

**Comment by blurymind** [comment]
ooooh! Thank you guys! This totally got me
Sorry for the confusion. Feel free to close this issue

**Comment by groud** [comment]
No problem :)

**Comment by blurymind** [comment]
@akien-mga ,the following doesn't work
`str2var("(93, 87)")`
The "(" and ")" still break it.
I get this error:
`calling built-in function 'str2var': Parse error at line 120945184: Expected value, got '('. `
would you like me to open another issue for it?

**Comment by groud** [comment]
I think the proper syntax is the following:
`str2var("Vector2(93, 87)")`

**Comment by blurymind** [comment]
@groud Thank you :)

I have noticed that this has confused others:
https://www.reddit.com/r/godot/comments/4t25y1/string_to_vector2/+&cd=1&hl=en&ct=clnk&gl=uk
In the link, the reply that the guy gets has broken code as a result
