### ISSUE TITLE
Shader paramater types don't get updated in the inspector tab once set

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11429]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Master https://github.com/godotengine/godot/commit/cd2ffdc6725aa6f7a9a4af6fd5abcc4cafae61b4

**Issue description:**

When updating the shader uniforms type the inspector won't update the type if there was already a value in the param.

[Video](https://streamable.com/agoya)

**Steps to reproduce:**
1. Create a shader.
2. Add an uniform.
3. Go to the inspector and give a value to that uniform.
4. Change the uniform type and save the shader.
5. The inspector will still hold the old type.

---

EDIT:
I feel this problem is the same or pretty much related to this issue so I'm appending it to this.

**Issue description:**

When removing an uniform from the shader the inspector tab will get updated BUT if you add the uniform back the inspector tab will show the old value of that uniform

[Video](https://streamable.com/hk1kh)

**Steps to reproduce:**
1. Create a shader.
2. Add an uniform.
3. Go to the inspector and give a value to that uniform.
4. Remove the uniform.
5. The inspector will get updated removing the param from the list.
6. Add the uniform again.
6. The inspector will show the old value of the "new" uniform.

**Comment by mhilbrunner** [comment]
Could you verify this still happens with current master?

**Comment by KoBeWi** [comment]
As of 3.1.1, the first issue is fixed.

Second one still exists. Uniform value is somehow remembered even if it's removed or has changed type. I guess it deserves creating a separate issue now.

**Comment by KoBeWi** [comment]
Seems to still be happening in 3.2.2, but I don't think it's really a bug. It does no harm and can prevent loss of data if you remove the uniform accidentally (also the "cached" value is not saved in the scene and disappears on reload). You can reopen if you want, but in a new issue as I said in the previous comment.
