### ISSUE TITLE
UI preserve interaction context

### ISSUE THREAD

**Issue by etisdew** [godotengine/godot#11425]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7, vesion_2.1.4-stable_win64, not graphic related.

**Issue description:**
It is very inconvenient to lose the menu upon clicking outside of a modal.

**Steps to reproduce:**
Click elsewhere when using a menu modal.

**Comment by JoseMcMaster** [comment]
if you set to exclusive, still same?

**Comment by JoseMcMaster** [comment]
just tested, if you enabled exclusive on the modal window it doesn't close if you click outside of it, no issue here :)

**Comment by Noshyaar** [comment]
Related: #6453

**Comment by etisdew** [comment]
Thank you for the response and solution. Sorry for the misunderstanding.

**Comment by etisdew** [comment]
I had believed it to be the same sort of issue as #6453
