### ISSUE TITLE
VSE request - pinning for graph editor

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#1142]
So it wont dissapear when I select something in 3D view :)

**Comment by reduz** [comment]
fair

**Comment by akien-mga** [comment]
Given that the Visual Shader Editor was temporarily removed in 3.0, and will come back with improvements in 3.1, I'll close this issue for now, as we'll likely never think to look in 2015 issues for feature requests :)

Feel free to open a new issue if this is still valid when the new VSE is implemented (or make a PR to fix it, should be a junior job :)).
