### ISSUE TITLE
Crash on startup if there is no audio device connected

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#11423]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64 bits

**Issue description:**

If there is no audio device connected, Godot will crash on startup with the following error:

```
ERROR: init_device: Condition ' hr != ((HRESULT)0x00000000) ' is true. returned: ERR_CANT_OPEN
   At: drivers\wasapi\audio_driver_wasapi.cpp:54
ERROR: init: Condition ' err != OK ' is true. returned: err
   At: drivers\wasapi\audio_driver_wasapi.cpp:155
ERROR: initialize: Initializing audio failed.
   At: platform\windows\os_windows.cpp:1088
Segmentation fault
```

**Steps to reproduce:**

- Remove all your playback devices until there is none activated.
- Run Godot.
- Observe crash.
- Ask yourself how can you live without some damn headphones.

**Comment by akien-mga** [comment]
CC @marcelofg55

**Comment by marcelofg55** [comment]
@neikeq This is with latest master?

**Comment by neikeq** [comment]
I updated today and it's no longer crashing. Instead I get this errors:

```
ERROR: init_device: Condition ' hr != ((HRESULT)0x00000000) ' is true. returned: ERR_CANT_OPEN
   At: drivers\wasapi\audio_driver_wasapi.cpp:54
ERROR: init: Condition ' err != OK ' is true. returned: err
   At: drivers\wasapi\audio_driver_wasapi.cpp:155
ERROR: Cannot initialize RtAudio audio driver: No devices present.
   At: drivers\rtaudio\audio_driver_rtaudio.cpp:86
ERROR: initialize: AudioDriverManager: all drivers failed, falling back to dummy driver
   At: servers\audio_server.cpp:153
ERROR: Class AudioStreamPlayer2D already has a method get_position
   At: core\class_db.cpp:1182
```

Not sure if that's fine.

**Comment by reduz** [comment]
closing as no longer bug then

**Comment by Chicopatata45** [comment]
El error desapareció cuando conecte mis auriculares bluetooth, al parecer es un problema con la entrada/salida de audio de la computadora
