### ISSUE TITLE
Option to disable human-readable property names in Project/Editor Settings

### ISSUE THREAD

**Issue by YuChaoGithub** [godotengine/godot#11442]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS, Godot 2.1.4

**Issue description:**
Whenever a Global property is added in the Project Settings window. The underscores of the property name will automatically be changed to white spaces. For example, "global_property" will be changed to "Global Property". And while the property appears to be "Global Property", you have to  refer to it in the script as `Globals.get("global_property")` instead of `Global.get("Global Property")`. You also can't delete the property unless you type in the original underscore version of the name in Project Settings' panel.

**Steps to reproduce:**
Open the Project Settings window. Go to the Global tag. Add a global property with underscores in the name. The underscores would appear to be white spaces. Click on the newly created property. Press the delete button. You can't delete it unless you retype the original underscore version of the name in the text field. Also, you have to refer to the variable as its original underscore name instead of the whitespace name.

<img width="1259" alt="1" src="https://user-images.githubusercontent.com/12479866/30655421-6eec244a-9e63-11e7-8bb3-2e5dc6518119.png">

**Comment by akien-mga** [comment]
That's not a bug, it's a feature :)

But I agree that for the delete route, it's not super convenient. The UX of this panel is pretty bad anyway, I think it would be better to replace the top bar with a search bar, and just add a button to add new properties that would show a dedicated dialog. For deletion, there could be a delete icon next to each custom property.

**Comment by neikeq** [comment]
If you hover the property it will display a tooltip with the name `global_variable`. Maybe we could add a message like: _"Did you mean `global_variable`?"_

**Comment by casd82** [comment]
Thanks for the explanation!

I also agree with @akien-mga's idea to make the panel with better UX.

**Comment by mhilbrunner** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
It's still valid, though as mentioned not a bug but a feature. An option could be added (directly with a checkbox in the Project and Editor Settings) to toggle the human-readable name conversion I guess.

**Comment by akien-mga** [comment]
The original name of the property appears on the tooltip now, so IMO there's no need to disable the pretty print.
