### ISSUE TITLE
Unicode errors (invalid skip)

### ISSUE THREAD

**Issue by TBDEV** [godotengine/godot#11440]
Windows 10 64-bit
Geforce GTX 1050 Ti
Nvidia drivers 385.41
Godot 3.0 alpha build 1

 Errors appear in console on startup.

```
DETECTED MONITORS: 1
Activated GL 3.3 contextERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core\project_settings.cpp:841
ERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core\project_settings.cpp:841
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
WARNING: not found: rendering/quality/anisotropic_filter_level
WARNING: not found: rendering/quality/anisotropic_filter_level
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
WARNING: not found: locale/translation_remaps
OPENING: D:/Software/Godot3.0/Projects/HyperRace (D:::Software::Godot3.0::Projects::HyperRace)
running cmdline: "D:\Software\Godot3.0\Godot_v3.0-alpha1_win64.exe" "-path" "D:/Software/Godot3.0/Projects/HyperRace" "-editor"
DETECTED MONITORS: 1
Activated GL 3.3 contextERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core\project_settings.cpp:841
ERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core\project_settings.cpp:841
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
WARNING: not found: rendering/quality/anisotropic_filter_level
WARNING: not found: rendering/quality/anisotropic_filter_level
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
WARNING: not found: locale/translation_remaps
ERROR: RasterizerSceneGLES3::environment_set_tonemap: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:914
ERROR: RasterizerSceneGLES3::environment_set_adjustment: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:929
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
ERROR: RasterizerSceneGLES3::environment_set_tonemap: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:914
ERROR: RasterizerSceneGLES3::environment_set_adjustment: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:929
ERROR: RasterizerStorageGLES3::_render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers\gles3\rasterizer_storage_gles3.cpp:6237
ERROR: RasterizerSceneGLES3::environment_set_tonemap: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:914
ERROR: RasterizerSceneGLES3::environment_set_adjustment: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:929
WARNING: AudioDriverRtAudio::callback: RtAudio output underflow!
     At: drivers\rtaudio\audio_driver_rtaudio.cpp:57
WARNING: AudioDriverRtAudio::callback: RtAudio output underflow!
     At: drivers\rtaudio\audio_driver_rtaudio.cpp:57
WARNING: AudioDriverRtAudio::callback: RtAudio output underflow!
     At: drivers\rtaudio\audio_driver_rtaudio.cpp:57
```

**Comment by Einlander** [comment]
What language is your OS?

**Comment by MrMaidx** [comment]
I'm getting this error too. Windows 10 64bit, NVidia GT620m, 381.65 driver.
The OS is in Czech language so there might be problems with that.

**Comment by TotCac** [comment]
Getting too, windows 10 64bits, french os, nvidia 1060

**Comment by xsellier** [comment]
I have the very same issue guys, any news ?

**Comment by mhilbrunner** [comment]
Same on Windows x64, en-us locale, NVIDIA 980 Ti, current master (`4396712`)

**Comment by akien-mga** [comment]
It appears to be a Windows-specific issue so far (and maybe only Windows 10?).

**Comment by akien-mga** [comment]
To help debug, the error is triggered here: https://github.com/godotengine/godot/blob/9906aeb2f8b492e6662e68aafe11e62524a87cc8/core/ustring.cpp#L1302

That code hasn't changed since the open sourcing of Godot, so the regression doesn't come from here, but the error is likely triggered by a call to `String::parse_utf8` using an invalid parameter. I'd advise to print the output of `p_utf8` before that error is triggered to see what it chokes on.

**Comment by Zireael07** [comment]
I *might* have seen it once but I'm not sure - haven't used G3 built from master in quite some time.

Win 7 x64, Polish language OS.

**Comment by mhilbrunner** [comment]
I'll try to debug this, not sure if I'll find anything out though. Definitely not only Windows 10, getting this on Windows 7 too.

**Comment by mhilbrunner** [comment]
This is what output looks like replacing the error message with the contents of `p_utf8`:

![unicode_error](https://user-images.githubusercontent.com/1654763/31943680-bc2a1cdc-b8c9-11e7-8b7f-1305d1ffdab1.PNG)

**Comment by mhilbrunner** [comment]
So all of these seem to be triggered while the code for parsing the stuff in `Help -> About -> Thirdparty License` runs.

This is the output for logging the content of every ``String::parse_utf8()`` invocation after the `invalid skip` occurs:
<details>
 <summary>Output</summary>

```plain
unicode error: 
? 2007-2017 Juan Linietsky, Ariel Manzur.
? 2014-2017 
unicode error: invalid skip
NEXT: Juan Linietsky (reduz)
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2007-2017, Juan Linietsky, Ariel Manzur.
2014-2017, Godot Engine contributors.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2017, Andrea Calabr??
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2008-2013, The Android Open Source Project
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2010, The Android Open Source Project
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2012-2013, Google Inc.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2002, Google Inc.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 1997-2017, Sam Lantinga
2007-2017, Juan Linietsky, Ariel Manzur.
2014-2017, Godot Engine contributors.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2003-2008, Erwin Coumans
2007-2017, Juan Linietsky, Ariel Manzur.
2014-2017, Godot Engine contributors.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2007, Starbreeze Studios
2007-2017, Juan Linietsky, Ariel Manzur.
2014-2017, Godot Engine contributors.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2006-2009, Erin Catto
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: FIXME
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2002-2016, Lee Salzman
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2015, Etc2Comp Authors
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2008, The Android Open Source Project
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2012, Google Inc.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2015-2017, Christopher Simpkins (with Reserved Font Name Hack).
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 1996-2017, David Turner, Robert Wilhelm, and Werner Lemberg.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2013, David Herberth
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2012, Rich Geldreich
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2002, Xiph.org Foundation
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2002-2015, Xiph.org Foundation
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 1995-1996, Guy Eric Schalnat, Group 42, Inc.
1996-1997, Andreas Dilger
1998-2016, Glenn Randers-Pehrson
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2016, B??a??ej Szczygie??
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2010, Google Inc.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2010, The WebM Project authors.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2002-2009, Xiph.org Foundation
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2010, Google Inc.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 1998-2010, Gilles Vollant
2007-2008, Even Rouault
2009-2010, Mathias Svensson
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2007-2011, Ilya O. Levin
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: Ari Edelkind
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 1998-2012, Daniel Stenberg et al.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2005-2007, Ariya Hidayat
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2016, Bruno Ribeiro
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 1990, RSA Data Security, Inc.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2011, Morten S. Mikkelsen
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2014, M.E. O'Neill
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2006-2009, Salvatore Sanfilippo
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2007-2017, Sean Barrett
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2011, Ivan Fratric
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2008-2011, Robin Watts
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 1998-2016, The OpenSSL Project.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2001-2011, Xiph.Org, Skype Limited, Octasic,
Jean-Marc Valin, Timothy B. Terriberry,
CSIRO, Gregory Maxwell, Mark Borgerding,
Erik de Castro Lopo
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2013-2014, Mikko Mononen
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2014, Jeffrey Lim.
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2009, Mikko Mononen
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2001-2016, Gary P. Scavone
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2006, Simon Brown
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2014-2017, Syoyo Fujita
2002, Industrial Light & Magic, a division of Lucas Digital Ltd. LLC
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 1995-2017, Jean-loup Gailly and Mark Adler
unicode error:     ? 
unicode error: invalid skip
NEXT: 
    ? 
unicode error: 
    ? 
unicode error: invalid skip
NEXT: 2016-2017, Facebook, Inc.
unicode error:     ? 
unicode error: invalid skip
NEXT: ::res://::1508856569
```
</details>

**Comment by akien-mga** [comment]
Related: #11592

**Comment by akien-mga** [comment]
CC @Noshyaar.

**Comment by mhilbrunner** [comment]
Okay, the first line triggering this seems to be [editor_about.cpp:120](https://github.com/godotengine/godot/blob/847c55bcb11337bd2d386347b299863f82a1be02/editor/editor_about.cpp#L120).

I reduced it down to `String::utf8("\n\u00A9 2007-2017 Juan Linietsky, Ariel Manzur.\n\u00A9 2014-2017 ")` and that still seems to produce a `unicode error: invalid skip` message.

**Comment by akien-mga** [comment]
Yeah that's to be expected, `\u00A9` is ©. It's valid Unicode though, but maybe the parser chokes on it. It comes from here:
```
editor/editor_about.cpp
120:    about_text->set_text(VERSION_FULL_NAME + hash + String::utf8("\n\u00A9 2007-2017 Juan Linietsky, Ariel Manzur.\n\u00A9 2014-2017 ") +
204:                    String copyright = String::utf8("    \u00A9 ") + String::utf8(about_tp_copyright[read_idx]).replace("\n", String::utf8("\n    \u00A9 "));
```

**Comment by mhilbrunner** [comment]
Reduced it further, a simple `String::utf8("\u00A9")` triggers the message. @akien-mga seems to be correct, String::utf8() seems to dislike that, for whatever reason. Maybe it just dislikes copyright, Stallman-style? Probably something to do with all unicode escape sequences, though.

**Comment by akien-mga** [comment]
Does it choke on `print("©")` in a test project? It works fine on Linux, and the © characters in the about box (thirdparty licenses tab) are displayed fine without error message.

**Comment by mhilbrunner** [comment]
`String::utf8("©")` in C++ works without error.
`print("©")` in a GDScript works too.

And the output seems kind of broken (if I don't misremember how it *should* look):
![screenshot](https://i.imgur.com/XZTqtbU.png)

Note the missing copyright symbols (and maybe the `Files: *` stuff?

Which is probably to be expected, as that just is ASCII code 184, not Unicode (U+00A9), and the problem seems to be triggered while parsing Unicode in [ustring.cpp#1256](https://github.com/godotengine/godot/blob/847c55bcb11337bd2d386347b299863f82a1be02/core/ustring.cpp#L1256) - the String::parse_utf8() method.

(Still all on Windows 7 x64)

**Comment by mhilbrunner** [comment]
Interestingly, `print("\u00A9")` in GDScript seems to work fine, it prints the copyright symbol and doesn't produce the error message.

**Comment by volzhs** [comment]
![image](https://user-images.githubusercontent.com/8281454/31959515-db4a4e0a-b92f-11e7-81d4-5ea8c0851dc0.png)
This is captured on Ubuntu 16.04.
I can see some differences.

* no indent before `2007-2017...`
* `©` is not printed.
* no line break

**Comment by mhilbrunner** [comment]
String test case 13 fails silently, by the way. No output besides "pass", which is definitely wrong.

**Comment by mhilbrunner** [comment]
Okay, I got... something.

So, above you got String::utf8("\u00A9").
That calls String's `parse_utf8()` internally, which tries to decode the given text as UTF8.

That, however, seems to produce this error.

``"\u00A9"`` is Unicode, not UTF8. UTF8 would be C2A9, not 00A9. The 0 byte at the beginning is lost somewhere along the way, and parse_utf8() only gets A9 as input.

A9 in binary is 10101001. Trying to interpret that as UTF8 fails, as it is only valid as one of the later bytes in a multi-byte sequence. (The first bit being 1 always implies multi-byte, and the first byte in a multi-byte UTF8 string always is 1 too, which it isn't here; so it would have to be the `n`th byte... except there isn't anything preceding A9) This leads to the "invalid skip" message, I believe: the parser tries to determine which bytes to skip because this seems to be a multi-byte UTF8 sequence... but it isn't. It's Unicode A9.

I'm not entirely sure yet what is cause and what is effect; in short:
`String s = String::utf8("\u00A9")` = error
`String s =  "\u00A9"` = fine, as the latter gets handled as a wchar and works properly, without being parsed as UTF8.

This even works for non-ASCII-compatible Unicode, like the Euro sign:
`String s = String::utf8("\u20AC")` = error
`String s =  "\u20AC"` = fine
`String s =  "€"` = also fine
`String s =  L"€"` = fine too

Maybe this has something to do with the system or compiler locale? That could be the reason it works fine on Linux. Not sure.

FWIW, I replaced the UTF8 decoder with this one: http://bjoern.hoehrmann.de/utf-8/decoder/dfa/
With that at least the Strings test case number 13 fails as it should.

Any ideas?

**Comment by mhilbrunner** [comment]
Another update:

If you include `#pragma execution_character_set("utf-8")` to tell MSVC that your source .h/.cpp files are UTF8 encoded, it just works without escapes at all:

```c++
#pragma execution_character_set("utf-8")
String s;
s = String::utf8("©");
s = String::utf8("€");
s = L"€"
s = L"©"
s = String(L("€")
```

All of those work without errors.

**Comment by Noshyaar** [comment]
Try removing call to String::utf8 from line 120, 159, 204 (except the middle one), don't include `#pragma` yet, see if it errors or displays any issues.

**Comment by mhilbrunner** [comment]
@Noshyaar: That fixes the "Invalid skip" spam, but leads to this (without changing anything from master besides replacing those lines' String:utf() calls with String()):

![uc1](https://user-images.githubusercontent.com/1654763/32118444-07c5eca4-bb52-11e7-8418-6bff880baedc.PNG)

**Comment by reduz** [comment]
I guess another way to include the file would be desired?

**Comment by Chaosus** [comment]
I found the solution - rename all 4 references in editor_about.cpp from "\u00A9" to "\xc2\xa9" - and all worked fine, including license docs.

**Comment by Zireael07** [comment]
That's interesting, those are equivalent ways of encoding the symbol, so why does one throw errors and the other not?

**Comment by mhilbrunner** [comment]
Well, the strings are parsed as UTF8 (by String::utf8()), and C2A9 (`\xc2\xa9`) is valid UTF8, while 00A9 (`\u00A9`) is Unicode?

**Comment by Chaosus** [comment]
Yep, they are multibyte utf8 symbols

**Comment by Chaosus** [comment]
You can read more here - http://en.cppreference.com/w/cpp/string/multibyte

**Comment by mhilbrunner** [comment]
@Chaosus Your pull doesn't fix everything wrt/ Unicode handling, I think. Still figuring stuff out, however.

**Comment by Chaosus** [comment]
Well, this fix this bug from spam... and dont break license, so I guess its ok

**Comment by mhilbrunner** [comment]
My bad, that really solves the spam.
This is fixed, then :)

I'll send a separate PR for the fixes for #12462.
Turns out that is a differen issue.

**Comment by amirea** [comment]
Getting this kind of error again. Lots of `invalid skip`, `invalid utf8`, `overlong rejected`, and `no space left`.

**Comment by Torguen** [comment]
I get this error in 3.3.2 stable mono when I hit "build".
Because of this, my exported variables do not appear in the editor.

**Comment by anisc** [comment]
I'm getting this error and some time Unicode error: no space left on a macos big sur v11.6.4
godot 3.4

**Comment by Calinou** [comment]
> I'm getting this error and some time Unicode error: no space left on a macos big sur v11.6.4 godot 3.4

Please open a new issue with a minimal reproduction project attached. Also, upgrade to Godot 3.4.3 first (as only the latest patch release is actively supported).

**Comment by anisc** [comment]
@Calinou I'm not sure if it's the same issue;
What happen to me is when I change something on the translation sheet(csv) I get 90% of the time "Unicode error: no space left" and the other 10% "Unicode errors (invalid skip)" I'm using excel v16.58 on mac. 
These error start after a certain point, so when I create the file and add line one at a time it work until it hits a point and it's not working anymore, even when I deleted the added line I keep getting the same error. 
My work around is to recreate a new csv file and paste all the changes, reload it into the engine and choose the needed translations.

**Comment by Calinou** [comment]
> What happen to me is when I change something on the translation sheet(csv) I get 90% of the time "Unicode error: no space left" and the other 10% "Unicode errors (invalid skip)" I'm using excel v16.58 on mac.

This occurs because Excel saves spreadsheets with BOM, which is not supported by Godot. This is now documented since https://github.com/godotengine/godot-docs/pull/3211 was merged.
