### ISSUE TITLE
Exports crashing in some machines in Win64 and Mac

### ISSUE THREAD

**Issue by macramole** [godotengine/godot#1145]
In Mac I think exports aren't working for Maverick (the latest version of OSX)

In Win it usually works well except for some machines.. for example a user pasted this log:

----------------------------------------------------------
Firma con problemas:
Nombre del evento de problema: APPCRASH
Nombre de la aplicación: JesusChristOurLordREBORN_win_64.exe
Versión de la aplicación: 0.0.0.0
Marca de tiempo de la aplicación: 547e241e
Nombre del módulo con errores: StackHash_0a9e
Versión del módulo con errores: 0.0.0.0
Marca de tiempo del módulo con errores: 00000000
Código de excepción: c0000005
Desplazamiento de excepción: 00000000
Versión del sistema operativo: 6.1.7601.2.1.0.256.1
Id. de configuración regional: 11274
Información adicional 1: 0a9e
Información adicional 2: 0a9e372d3b4ad19135b953a78882e789
Información adicional 3: 0a9e
Información adicional 4: 0a9e372d3b4ad19135b953a78882e789

-------------------------------------------------------------

I have a HP G60 dual core 2.10 GHz, 4Gb de RAM, WIN 7 x64, onboard video card
I have DirectX 10 installed (this is not important since engine uses OpenGL)

I tried x32 version
I tried compatibility mode and lowering the resolution
I tried executing as admin

**Comment by akien-mga** [comment]
Since 1.1 was released in the meantime, I'll assume this was an issue with the export templates you were using back then, or a hardware issue. Feel free to reopen if you still experience this bug in 1.1 or the current master branch/nightly builds.
