### ISSUE TITLE
Import panel contents dissapears after changing panel location

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#11451]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7
Godot 3.0 built from master today
Geforce 760 GTX

**Issue description:**
Upon loading Godot the import panel works fine, but as soon as you move it to a different part of the screen, the properties dissapear, even if you move the panel back or select a different resource

example GIF:

![bug](https://user-images.githubusercontent.com/10464013/30670661-23b3a76c-9e5b-11e7-9967-02d13b0815de.gif)

**Steps to reproduce:**
Change the position of the import panel and it will stop working until godot is restarted

**Link to minimal example project:**

**Comment by reduz** [comment]
probably should check for ENTER_TREE notification and re-update the options.
this panel code is here:

https://github.com/godotengine/godot/blob/master/editor/import_dock.cpp
