### ISSUE TITLE
Errors when CanvasItemEditor updates

### ISSUE THREAD

**Issue by groud** [godotengine/godot#11460]
Master branch.

Godot sprays errors on the CanvasItemEditor, when updating:
![2017-09-21-140659_630x260_scrot](https://user-images.githubusercontent.com/6093119/30694926-6c7c9500-9ed6-11e7-81f7-6e6c84e92863.png)

Probably here since #11446.

**Comment by marcelofg55** [comment]
I'm guessing that we should add another NULL check at line 2696 `_draw_locks_and_groups(editor->get_edited_scene(), transform);` to prevent the error spamming thing. Can you try this:
```
if (editor->get_edited_scene()) {
    _draw_locks_and_groups(editor->get_edited_scene(), transform);
}
```
