### ISSUE TITLE
Small "pop" noise when looping .ogg file

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#11468]
**Operating system or device, Godot version**
Linux Mint 18.2 Cinnamon x64, Godot master d7468fe

**Issue description:**
Upon looping, a .ogg stream will produce a small "pop" noise, which doesn't seem to be preventable by the user. A way to solve this problem (according to @reduz) is to add in a small crossfade at the end of a loop, removing the pop and making loops seamless.

**Comment by mrcdk** [comment]
can you upload the ogg that causes the issue?

**Comment by homer666** [comment]
@mrcdk I've tested a few different songs of mine, and they all exhibit the problem. [Here's one of them](https://github.com/godotengine/godot/files/1322442/j.ogg.zip), it loops at 1.93s.

**Comment by Zylann** [comment]
@homer666 I think a looping point specified in samples would be more accurate since you should ideally loop between samples that have the same values

**Comment by homer666** [comment]
@Zylann From what I can tell, AudioStreamOGGVorbis containers only accept a `loop_offset` in seconds.

**Comment by marcelofg55** [comment]
I usually use the zero-crossing technique to create seamlessly looping ogg files, these should loop correctly on every game engine, try this steps:
1. Open the project in your DAW, add a mark at the end of the section you what to export.
2. Export the section as a wave file (include its tail).
3. Open the exported file in your audio editor.
4. Go to the position of the ending mark and adjust the selection to the closest zero-crossing.
5. Remove from the zero-crossing until the end.
6. Save the file as ogg and now you have a seamlessly looping ogg file.

With Godot you can also use oamlGodotModule to handle the music loops of the project: https://github.com/oamldev/oamlGodotModule.

**Comment by homer666** [comment]
@marcelofg55 That oamlGodotModule looks really neat! Unfortunately I'm getting errors when building it, guess it isn't compatible with master anymore... let's hope the dev ports it over to 3.0 sometime.

Gonna try out the zero-crossing technique now, thanks for the instructions.

**Comment by marcelofg55** [comment]
Yeah, forgot to mention that oamlGodotModule is 2.1 only for now, I'm the dev btw :P, I'll port it to master sometime soon.

You're welcome, hope it helps!

**Comment by mrcdk** [comment]
@homer666  Uhm, 1.93s isn't precise enough for that sample, I tried it in audacity and the "pop" was also there . Using 1.933s removed that pop in audacity, but not in godot.

I think I've fixed the issue but I'm not a c++ developer and my code is pretty bad:

Use this code in this file https://github.com/godotengine/godot/blob/master/modules/stb_vorbis/audio_stream_ogg_vorbis.cpp#L44-L70:

```cpp
	int start_buffer = 0;

	while (todo > 0 && active) {
		float *buffer = (float *)p_buffer;
		if (start_buffer > 0) {
			buffer = (buffer + start_buffer * 2);
		}
		int mixed = stb_vorbis_get_samples_float_interleaved(ogg_stream, 2, buffer, todo * 2);
		if (vorbis_stream->channels == 1 && mixed > 0) {
			//mix mono to stereo
			for (int i = start_buffer; i < mixed; i++) {
				p_buffer[i].r = p_buffer[i].l;
			}
		}
		todo -= mixed;
		frames_mixed += mixed;

		if (todo > 0) {
			//end of file!
			if (vorbis_stream->loop) {
				//loop
				seek_pos(vorbis_stream->loop_offset);
				loops++;
				// we still have buffer to fill, start from this element in the next iteration.
				start_buffer = p_frames - todo;
			} else {
				for (int i = p_frames - todo; i < p_frames; i++) {
					p_buffer[i] = AudioFrame(0, 0);
				}
				active = false;
				todo = 0;
			}
		}
	}
```

**Comment by homer666** [comment]
>Uhm, 1.93s isn't precise enough for that sample

Yeah, sorry about that. FL Studio only displays a timestamp to the nearest **centisecond** for some reason, so I couldn't really get anything accurate without eyeing down the waveforms visually in Audacity... 

I compiled Godot with your code added and I can't make out much of a difference, possibly because I'm still using these inaccurate loop offsets given by FL. 

Also, the zero-crossing technique hasn't given me any success yet, popping still occurs in both master and the modified build. I'll keep trying but I'm afraid I'm doing something horribly wrong here...

**Comment by mrcdk** [comment]
did you click on reimport after changing the loop offset? 

The problem is that stb_vorbis will decode the requested frames or less if there aren't enough frames to decode but the current code doesn't take that into account and will override the already decoded frames with the rest of the frames. My changes just give the correct offset to the buffer to be decoded the second time so it won't get overriden

**Comment by homer666** [comment]
>did you click on reimport after changing the loop offset?

Yeah, I reimported them, swapped them out with something else and reimported them, swapped them out, restarted Godot, reimported them and swapped them back in, etc. It made no difference as far as I could tell. Hopefully reduz will come back to this soon and check out your changes, I feel like you've got the right idea but I'm really not knowledgeable enough about this to give any meaningful input.

**Comment by marcelofg55** [comment]
I tested your j.ogg file and didn't get any pop when looping, tried it on godot and on my sound editor and no pop at all, kinda weird that you're getting one.

**Comment by homer666** [comment]
I guess I should've clarified; I've also been testing other tracks of mine, with the bogus loop offsets given by FL's time display. Just tried the file I uploaded, with the loop offset given by @mrcdk, using his modified build, and it is indeed looping seamlessly. Trying this with b51180c still gives a pop, so his code definitely did fix things. The weakest link was my incorrect loop offsets. Sorry for confusing you both.

It seems like the rest of the issue stems from my inability to reliably create seamless loops of my songs, which extends beyond Godot.

**Comment by akien-mga** [comment]
Reopening as #12644 was reverted.

**Comment by reduz** [comment]
I also think loop in these files needs a XFade setting to avoid pops, just
setting custom loop/end will not do.
