### ISSUE TITLE
Allow conversion of FixedMaterial to ShaderMaterial

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1146]
Allow conversion of FixedMaterial to ShaderMaterial

This should allow easier pipeline for shaders from imported assets

**Comment by bojidar-bg** [comment]
I heard that this was planned for 3.0/3.1, so tagging accordingly.

**Comment by reduz** [comment]
This should be really easy to do now that we rewrote how materials work, but will kick to 3.1 unless someone volunteers to do it..

**Comment by akien-mga** [comment]
This was implemented in 3.0 in the end: https://twitter.com/reduzio/status/911203331485392896
