### ISSUE TITLE
Script Editor: Ctrl + Left / Right is "inconsistent"

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#11467]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0 Alpha

**Issue description:**
If one jumps from the end of a row to the very beginning of the same row via consecutive Ctrl + Left strokes, the behavior is different when going to the opposite direction (I don't seem to get the logic of it).

I think this has been so since 2.x (at least), and I've always thought that this was buggy behavior. However, I decided to (quickly) test this with some other text editors / IDEs:

- Intellij Products
- Visual Studio 2017
- Visual Studio Code
- Sublime Text

Out of these, only Intellij IDEs seemed to have 100% consistent word jump behavior. VS 2017 seemed to come very close to 100%, and VS Code & Sublime were quite close to Godot (with some nuances).

Personally, I find it is nearly impossible to get used to this "inconsistent" behaviour, particularly from the perspective of a "Java developer".

Adding a "Consistent Word Jumping" or somesuch option for people who are used to it, might be something to consider.

(Also: Treating underscores as stops might also be a good idea in a pythonic language)

**Comment by vnen** [comment]
I don't think this is exactly a "bug", as it was likely designed that way, if I understand what is the "inconsistency" you're talking about (I would like for you to be more clear about that).

Essentially (with the current behavior): <kbd>Ctrl</kbd>+<kbd>←</kbd> jumps to the beginnings of the words, while <kbd>Ctrl</kbd>+<kbd>→</kbd> goes to the end of the words.

And treating underscores as stops is a good idea, at least as an option (also changing of case, for PascalCase names too).

**Comment by TX256** [comment]
> Essentially (with the current behavior): Ctrl+← jumps to the beginnings of the words, while Ctrl+→ goes to the end of the words.

Ah! Now I at least make sense of the logic behind it. It just jumps **to the end of whatever direction you are going**.

Here's an example of the current behavior (the Black Monolith marks the caret position), and what I want:

**Step 0:** The caret is now at the end of the line:
`Gui.screen = preload("res://game.tscn").instance()█`

**Step 1:** first jump left
`Gui.screen = preload("res://game.tscn").█instance()`

**Step 2:** second jump left
`Gui.screen = preload("res://game.█tscn").instance()`

**Step 3:** OK. Now let's go once to right, and you can see that we are **NOT** at the same position as in Step 1. This is what I mean by "consistent" (feel free to invent a better name).
`Gui.screen = preload("res://game.tscn█").instance()`

**Step 4:** Second time to the right. I would've expected it to be at the end of the line - as in Step 0.
`Gui.screen = preload("res://game.tscn").instance█()`

**Comment by TX256** [comment]
Sooo... by the looks of it, essentially just use the same algorithm, but ignore the other direction.

**Comment by bojidar-bg** [comment]
IMHO, the current behavior is fine, but that might be just me getting used to it in Chrome, Atom and Godot.
So, if this is implemented, please keep it as an option in the settings 😃 .

**Comment by Hinsbart** [comment]
I personally like the way Visual Studio handles this, but also I don't think it's really worth it to add an option for it.

**Comment by Calinou** [comment]
Closing, as this appears to be more of a feature proposal than a bug (judging by the comments). If you still need this feature, please open a proposal on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.
