### ISSUE TITLE
Input not handling joystick axis

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#11465]
Windows 10, Godot pre-alpha 3.0

**Issue description:**
Input singleton not handling axis related events, at least not on my Xbox360 controller

**Steps to reproduce:**
Create a simple Input Handler
Add any axis related event
Try
```GDScript
func _fixed_process(delta):
	if Input.is_action_pressed("game_up"):
		print("up")
```

**Comment by Hinsbart** [comment]
Mhh, probably a duplicate of #10391 which has been fixed already. What does `pre-alpha 3.0` mean exactly? I can reproduce this with alpha1 but not with the latest master (on Linux).
I currently don't have access to a windows machine to test this, so if you're using an older version, could you try it again with an up-to-date version please?

**Comment by Hinsbart** [comment]
This has just been tested by @AndreaCatania on windows and it's working apparently, so closing for now.
