### ISSUE TITLE
GDScript Bug Invalid operands 'PoolByteArray' and 'Nil' in operator '!='

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#11466]
godot 3.0
var db = PoolByteArray([0,1,2,3,4,5])
	if db!=null:
		print("not null")
	else:
		print("is null")
Invalid operands 'PoolByteArray' annnd 'Nil' in operator '!='

var db = PoolByteArray([0,1,2,3,4,5])
	if db :
		print("not null")
	else:
		print("is null")

**Comment by hpvb** [comment]
The Pool* can only be compared positively to nil, the != operator isn't defined on them at all. This is a little inconsistent I'll fix it.
