### ISSUE TITLE
Rotation with middle mouse button dont work by default

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#11462]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
4664d03a0e39be6dc8f5ba8154e1d6b776fa2293

**Issue description:**
In 4664d03a0e39be6dc8f5ba8154e1d6b776fa2293 build default for orbit modifier is set to 'meta' button. So middle mouse button will not rotate camera around objects anymore. Not sure if this was desired or made by accident. 

**Steps to reproduce:**
1. Create project
2. Create new scene
3. Add spatial
4. Try to rotate around spatial with middle mouse button

**Comment by kubecz3k** [comment]
Change was made by this pr: https://github.com/godotengine/godot/pull/11222

**Comment by kubecz3k** [comment]
cc @toger5

**Comment by NathanWarden** [comment]
I can confirm this as well. Middle mouse orbit no longer works in the main viewport.

**Comment by akien-mga** [comment]
Fixed by #11463.

**Comment by toger5** [comment]
Oh my bad. I thought the modifier only is used when checking emulte 3 button mouse...
Ao i though a default value would be a good idea.

**Comment by toger5** [comment]
Ty for fixing it !!
