### ISSUE TITLE
The ground seems to have disappeared in the 3D view

### ISSUE THREAD

**Issue by hpvb** [godotengine/godot#11464]
Linux/Fedora 26
godot 4664d03a0e39be6dc8f5ba8154e1d6b776fa2293
Intel/Mesa 17.1.7

**Issue description:**
Opened the 3D editor, did not see the 3D grid

**Steps to reproduce:**
Open the 3D editor

![screenshot from 2017-09-21 19-05-00](https://user-images.githubusercontent.com/2591099/30708677-feb83ae0-9eff-11e7-8a90-854b378f6b8b.png)

**Comment by reduz** [comment]
i cant reproduce, if anyone can let me know

**Comment by hpvb** [comment]
I can't reproduce this anymore either... I guess this got fixed somehow.
