### ISSUE TITLE
Graphical Errors on Older Hardware

### ISSUE THREAD

**Issue by doctorcrimson** [godotengine/godot#11470]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7, Intel Inspiron 560, Godot 2.1.4, integrated graphics 43/45 chipset

**Issue description:**

I am experiencing graphical bugs and errors, involving buffering and image_loader.cpp

I think the problem is there isn't any compatability for an older 43/45 Intel Chipset.  I understand you shouldn't be expected to fix errors for obsolete hardware, but it would be a nice gesture if you did.

**Steps to reproduce:**
Start new project.  Import an image as a sprite.  Errors will show in Prompt and sprite will be black if hardware conditions are met.

**Link to minimal example project:**

**Comment by Calinou** [comment]
This is really old hardware, it's completely unsuitable for gaming (even 2D). It's not going to be supported in Godot 3.0 at all (modern Intel IGPs will be, starting from Ivy Bridge or Haswell), but even 2.1.4 has a lot of trouble on these old Intel IGPs. Note that the Linux driver is slightly better, and may be less problematic than the Windows one.

**Comment by doctorcrimson** [comment]
Totally understandable, thanks for the fast response.

**Comment by akien-mga** [comment]
It looks like with a recent enough driver (at least 14.39 on Vista, not sure about Windows 7) you might be able to get OpenGL 2.1 support, which is mandatory to run Godot 2.x: https://software.intel.com/en-us/articles/opengl-extensions-supported-in-intel-4-series-express-chipsets-and-beyond

But it does look like it really "barely" makes it, so I wouldn't expect great performance. A quick google search shows many users struggling with this model to run both modern and old (CounterStrike 1.6!) games with decent performance.

You could give a Linux distro a try, as the MESA Intel drivers are often more up to date than the ones available on Windows. According to [this page](http://addons.supertuxkart.net:8080/opengl/device/Intel(R)%20Q45/Q43), you could get OpenGL 2.1 support with MESA.
