### ISSUE TITLE
3D grid divisions should be made more distinct

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11475]
Godot 3.0 master

The newly added grid divisions aren't easily noticeable because their color is bleeding on regular grid subdivisions:

![image](https://user-images.githubusercontent.com/1311555/30717505-57ffc5b0-9f1d-11e7-8888-992112221b6e.png)

Ideally it should look more like this, as I already proposed in https://github.com/godotengine/godot/pull/11081:

![image](https://user-images.githubusercontent.com/1311555/30717542-75310e3c-9f1d-11e7-9782-866bdfda8aa1.png)
(colors are different but you can see lines are distinct)

**Comment by jedStevens** [comment]
Can we have custom thickness for those lines?

**Comment by groud** [comment]
Maybe cc @djrm ?

**Comment by Calinou** [comment]
As far as I remember, not all OpenGL implementations support drawing lines thicker than one pixel. If this is to be done, then I guess the grid would have to be rendered as transparent polygons (transparency being required for the distance fade).

**Comment by groud** [comment]
In 2D, the draw_line function uses polygons when thinker than 1px. Don't know for 3D.

**Comment by Zylann** [comment]
@Calinou or stretched quads ;)
