### ISSUE TITLE
Default `freelook_base_speed` is too fast

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11474]
Godot 3.0 master

I tried the new default settings for freelook, and I think it's too fast. It is currently set to a base speed of 0.5, it should be 0.1 maybe. It used to roughly match panning speed in the past, but got modified since.
It can be changed by users of course, but it was a bit confusing when I built latest.

Video showing orbit navigation, followed by freelook:
https://www.youtube.com/watch?v=pwxmiXW4gmI&feature=youtu.be

**Comment by toger5** [comment]
Agreed 0.1 is a good value!

**Comment by kubecz3k** [comment]
Another problem is the lowest possible value that we can set is 0.1 which is still to high for me to use comfortable in my project (with 1 game unit ~= 1m).
