### ISSUE TITLE
Doc: Adapt makerst.py script to the new split classes XML

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#11488]
Since the monolithic classes.xml was split into one XML per class, the `doc/tools/makerst.py` won't be able to process the docs and convert them to reST for https://github.com/godotengine/godot-docs anymore.

The script should be adapted to work on a bunch of single-class XML files instead of the monolithic `doc/base/classes.xml`.

The files to parse are:
- `doc/classes/*.xml`
- `modules/*/doc_classes/*.xml` (when present - so far only in the `gridmap` module)

**Comment by paezao** [comment]
Hey im up for this.

**Comment by paezao** [comment]
@akien-mga Should I remove the argument or ask for a folder?

**Comment by paezao** [comment]
Ah okay. Cheers

**Comment by akien-mga** [comment]
Fixed by #11495.
