### ISSUE TITLE
Dragging Polygon2D points is misaligned when rulers are enabled.

### ISSUE THREAD

**Issue by Smellyhobo101** [godotengine/godot#11484]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win7, [Godot-Windows-x86-2017-09-21.1481a1b.zip](https://bintray.com/calinou/godot/editor/2017-09-21.1481a1b#files)

**Issue description:**
You have to click to the upper left of a point to move it when rulers are on:

https://streamable.com/d6qo9

Same behavior occurs with Path2D's and other similar Nodes.

**Comment by groud** [comment]
I'll fix it.
