### ISSUE TITLE
VSE request - bigger or "unlimited" span of working area

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#1148]
This one will be a bit hard to explain, but is important.

We pan view in VS Editor with middle mouse, but user is limited to area of visible nodes, he can't move more than that.

It creates problem when user wants to move to clean area to add some new nodes.

Currently to workaround this problem I would create some node and moved it little by little to right beyond Editor Canvas until I will create big enough working area to fiddle with nodes. Problem is that it would be needles hassle.

Good example is Blender Node Editor. User can freely move his view to emptier part of canvas where he can work on new nodes.

I hope I explained it well, if not I can make some illustrations to visualize problem.

**Comment by akien-mga** [comment]
Should have been fixed by 78f4b93.
