### ISSUE TITLE
Proposal: Move third party libraries to another repo

### ISSUE THREAD

**Issue by mrezai** [godotengine/godot#11490]
It seems a good idea to move third party libraries to another repo and prepare them as prebuild to download for all supported platforms like what Cocos2d-x project done. They have two repo, one for engine and one for dependencies. Before engine compilation, dependencies downloaded by a python script:
Engine repo: https://github.com/cocos2d/cocos2d-x
Dependencies repo: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src

Advantages:
Faster engine compilation(Only linking to prebuild libraries)
Less fear and stress for core developers to add big libraries like ICU and Harfbuzz. :)
Simpler source management to update libraries?!
@reduz @akien-mga

**Comment by groud** [comment]
> Faster engine compilation(Only linking to prebuild libraries)

This is not possible, we don't use pre-built libraries as we should pre-built all possible devices Godot might run on. This is complicated and do not worth it.

> Less fear and stress for core developers to add big libraries like ICU and Harfbuzz. :)

I don't think core developers are afraid of adding big libraries, it's a design choice to keep the engine light and independent. Big additional libraries, specific to a platform, can be added through GDnative now, and I think it is the right approach.

> Simpler source management to update libraries?!

We have few thirdparty libraries, I don't think this is worth to move it elsewhere.


In fact I see few advantages in doing that, it only spread the work on the engine on two places. And as thirdparty libraries in the "core" should be maintained along with the engine code, this does not make much sense.

**Comment by mrezai** [comment]
> This is not possible, we don't use pre-built libraries as we should pre-build all possible devices Godot might run on. This is complicated and do not worth it.

The binaries in download page are built somehow then it's possible to build libraries that used by them in the same way. We don't need build for all platforms like Haiku or Raspberry, only for official ones. Other less common platforms can do it like before but in two pass: first build libraries then link to them. Even it's possible to support previous workflow by using git submodule and one environment variable.

> I don't think core developers are afraid of adding big libraries, it's a design choice to keep the engine light and independent. Big additional libraries, specific to a platform, can be added through GDnative now, and I think it is the right approach.

You can review issues that propose adding big libraries to support some features for example adding ICU and Harfbuzz to support text rendering. In most of them core developers requested to extract only needed part of the library. It's possible but maintenance of that library will be too harder. By separating libraries we can add all files of one library and build it. The needed part will be selected by linker not by developer! Simpler to add libraries and maintenance them.
I think GDNative can't be used on all platform at least on iOS because iOS need one fat binary and it's impossible to load libraries at runtime.

> In fact I see few advantages in doing that, it only spread the work on the engine on two places. And as thirdparty libraries in the "core" should be maintained along with the engine code, this does not make much sense.

I think it's worth it:
- One time built and packaged by some scripts like how binaries in download page built.
- Faster engine compilation. This will be obvious when someone want to compile engine for multiple platforms.
- The repo can have some specific maintainers.
- The repo Maintainers can work on enable optimizations. Some of libraries now compiled without optimizations like OpenSSL and libpng.
- Simpler to add libraries. Add all files of library and let compiler and linker do their jobs later. They will select the related parts. Check this : #10546 . More than 500 files will be added if this PR merged. All of them needed? Of course not.
- Core libraries can't be added by GDNative for all platforms.

**Comment by groud** [comment]
It does not make sense, you are confusing linkage and repositories. We could provided pre-built files, and accelerated build with a single repository. You don't need another repository to do that.

The equation is simple here:
- If the library is mandatory, it should be in the main repository, and the "bindings" are maintained by the core developers (there are no other people to do that). So as this is part of the engine it make no sense to move this elsewhere.
- If the library is not mandatory, it **should** be added using gdnative, and added to the assets store.

The only difference it makes is that if you don't need the included libraries (as they are allready in your system), it may allow you not to download them. But we actually don't care... This make the download faster but would split the code into two repository (issues, etc...), which is not acceptable here for that little gain.

**Comment by mrezai** [comment]
I know it's not necessary to separate external libraries  and move them to new repository to support prebuilt libraries. The separation is for simpler maintenance. See Cocos2d-x above and Ogre3D here : http://www.ogre3d.org/tikiwiki/CMake+Quick+Start+Guide
They have two repositories, one for engine and one for dependencies(external libraries).
If you check Cocos2d-x for an example, you will see there are 3000 issue in main repo and 30 issue in dependencies repo. The dependencies repo maybe change in monthly basis not like main repo evrey hour. I had upgraded Godot's OpenSSL multiple times. I think library upgraded after two years!
If others libraries like ICU, Harfbuzz, Bullet, VRs libs and ... added to engine source, and someone want to compile engine for multiple platforms then prebuilt libs can help a lot. Why new engine developers must compile all external libraries themselves and don't download prebuilts?!

**Comment by groud** [comment]
Well, sure we could provide pre-built libraries. As @akien-mga mentioned in IIRC,

**Comment by groud** [comment]
Sure, we could update the libraries more often, but I don't get why putting them in another repository would help that. We could provide pre-built libraries, but the problem is more about making a better build system than moving them to another repository.

**Comment by hpvb** [comment]
I'm don't love with this idea for several reasons:
* The amount of prebuild libraries we have to support is non-trivial to support all supported Linux configurations for example we'd need at least 24 permutations. If we want to support LTO on both clang and GCC 48. (gcc5, 6+) * (release, debug_release, debug) * (lto, non-lto) * (x86_64, i686) = 24, more if we want to support clang LTO also.
* On Windows this number could be even higher as we'd may end up having to support 4 different compilers with various flags.

While it's hard to hide a potential intentional vulnerability in the sources as git will protect us from adding nefarious code to the repo without a commit message, having some blobs on a repo somewhere would be a much easier thing to do, especially since the repo 'tip' would most likely not change all that often. To combat that we'd _have_ to setup a fully reproducible build environment for this third party library repository. Not doing this would just be laughably irresponsible.

We can do all of this, but it is a LOT more work to do right than the comments on this issue are leading the reader to believe.

**Comment by mrezai** [comment]
Fair enough, It seems with consideration of all compilers, archs, etc, it's too hard to build libraries for all possibilities.
It seems we should prepare ourselves for too long compilation like Unreal Engine. Somewhere I read it will take longer than two hours to compile, only for one platform!

**Comment by akien-mga** [comment]
>  It seems we should prepare ourselves for too long compilation like Unreal Engine. Somewhere I read it will take longer than two hours to compile, only for one platform!

Well that's not the case, and I don't see why that should change :)
Instead, I think we should be able to reduce the compilation time a lot by optimizing the buildsystem.

**Comment by groud** [comment]
For me the compilation is something like 15 minutes long for the first time, not 2h yet.
I run that on a laptop with a SSD, not the high end kind of device but I guess it's still ok.

That being said I don't know how longer will it take if we merge #10546.

As said by @akien-mga, we should first focus on improving the buildsystem :)

**Comment by hpvb** [comment]
Most of the time our cpp files don't actually need the full definitions of all the classes, particularly in the editor. Just replacing many of the headers with versions that just have forward declarations would probably already cut our build time in half.

**Comment by mrezai** [comment]
Sometimes long compilation time is good!

![](https://imgs.xkcd.com/comics/compiling.png)

I Close this and waiting for godot!
