### ISSUE TITLE
Some odd-looking symbols in script editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11499]
Godot 3.0 master

Minor in general,  noticed a few characters look a bit odd with the new Hack font / icons:

- My main concern is indentation marks look out of place. I liked to code with them as they were fine, discrete enough and improved readability for me and made indents visible (they matter :p), but now I find them too noticeable (alternating shape, size and different thickness). I preferred the old ones, is it coming from the font though?
- Minor: already noted earlier, but the zeroes look weird. I understand it's to differentiate with O and I like this, but filling the whole oval isn't common.
- Minor: more personal note, but I got used to wider angled brackets. Hack ones are more tight compared to Consolas, for example.

New:
![image](https://user-images.githubusercontent.com/1311555/30766491-caeec610-9ff5-11e7-926b-5ed01bed2a8f.png)
Old:
![image](https://user-images.githubusercontent.com/1311555/30766678-07ed8b22-9ff7-11e7-834b-b32662f4a5ea.png)

(other than that the font looks fine so far)

Edit: Github shows no images anywhere on my end, I hope you can see them...?

Edit 2: At the moment I'll most likely try another font myself and stick with it. I'm trying to test a TTF but I see no way of setting it up easily in Godot...

**Comment by bruvzg** [comment]
Indentation marks are icons.
https://github.com/godotengine/godot/blob/master/scene/gui/text_edit.cpp#L1078

**Comment by toger5** [comment]
I also noted folling issues with them beeing icons:
 - Scaling text does jot scale them (meta + scroll)
 - color adaption for white theme does not work
 - color cant be set when usojg coustom thext color theme. So they can look even more out of place

Isnt there a really good font icons that could be used?

**Comment by toger5** [comment]
@Zylann i think the two minor ones are very personal.
I like the braces. But since there is still the option for a coustom font im fine with any default. (but i think it is not worth to start another discussion about default code font. There was one recently,if im not mistaking, so the overall opinion seems to what this as the default.

**Comment by djrm** [comment]
@toger5 , using a character might be a really good idea, i think it should be this one `⇥`, it never cossed my mind, also yeah its clear that the icon wont scale and thats a bad thing.

**Comment by pwab** [comment]
I really like these `|` indentation marks used in Notepad++ or VSCode.

![indentation_mark_vscode](https://user-images.githubusercontent.com/19271185/30941482-ed074292-a3e5-11e7-88c3-364ea36f8811.PNG)

Problem here is that using a 'line'-character could lead to little spaces in between:

|
|
|

**Comment by Zylann** [comment]
@toger5 I managed to get my favourite font setup so I don't really mind anymore about the two minor points :)

So yeah... I think we could find more discrete and regular indentation marks, like the old Godot ones, or the verticals from Sublime (but in ST verticals are procedural, they aren't icons or even characters)

**Comment by toger5** [comment]
I like both proposals:
The character @djrm posted (i will tri it fith the current code font in godot)
And the line (@pwab)
Maybe it even would be worth to implement the line drawing? Not sure how to do it... So i cant really tell how much work it is.

**Comment by Zylann** [comment]
Not a fan of the ⇥, because it stands out too much for something that is shown all the time (unless the font happens to have a discrete indicator by pure luck...). I know it really is supposed to represent a tab, but I never see it used as indentation *guide*, but more likely shown to stand out in diff tools or "show non-printed characters" modes.

In ST it is shown only on selection (with spaces too):
![image](https://user-images.githubusercontent.com/1311555/30965207-6de10888-a44c-11e7-958e-4bb06e18bc6a.png)

**Comment by toger5** [comment]
just another idea. Could we adda custom character to the current default font so that it looks like it does right not but it is not an icon?

**Comment by toger5** [comment]
Best solution by far is the vertical line (imo)
but that is also most work.

**Comment by bruvzg** [comment]
Vertical lines for indentation **and** arrows for all other tabs (to highlight excessive tabs at the end of line).
![tabs](https://user-images.githubusercontent.com/7645683/30966550-f63708a8-a461-11e7-8e6a-956e8e7af441.png)

**Comment by Zylann** [comment]
What's wrong about the icon though? You could also draw it with a scaling rectangle based on line height, or draw a line instead (or have a line in the icon heheh), which isn't much work, just different drawing.

**Comment by toger5** [comment]
Or just draw an appropritaly scaled line instead of the icon...
Maybe the line approach is easier to inpmement than i thought.

**Comment by bojidar-bg** [comment]
There is:
⎸U+23B8 LEFT VERTICAL BOX LINE
│U+2502 BOX DRAWINGS LIGHT VERTICAL

**Comment by Zylann** [comment]
@bojidar-bg character-based lines leave spaces in between rows

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by akien-mga** [comment]
I think by now, most users are either fine with the new font, or using a custom one, so I think we can close this. The only thing that is likely to be fixed is added more subtle indentation guides when #20725 is revisited for 3.2.
