### ISSUE TITLE
Undo performs both on popup and script editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#1149]
I was editing a script, then I opened the ProjectProperties window to set up some key mappings. But I made mistakes, and wondered if I could undo.
It actually worked, but every time I pressed CTRL+Z, the script editor behind was undoing too, at the same time. It seems like the event is not well focused on the ProjectProperties window.
PS: difficult to find a meaningful short title, I hope it's clear enough :)

**Comment by akien-mga** [comment]
To solve this the input event propagation must be stopped once it has been handled in the popup, so that it does not reach the script editor. Somewhat related to #1094 and #1123.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

@MarianoGnu You assigned yourself to this issue a while ago, do you still plan to work on it?

**Comment by MarianoGnu** [comment]
I failed miserably when trying to fix it, but since input api has been changed i should try again
