### ISSUE TITLE
confused about collision position and world_to_map

### ISSUE THREAD

**Issue by RaTi17** [godotengine/godot#11506]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04, Godot 2.1.4 stable

**Issue description:**
Collisions with tilemap should return which tile there was a collision with (through world_to_map and get_cellv, given the collision_pos
For collisions to the right everything seems to work that way, collisions to the left return the tile -1

**Steps to reproduce:**
See included sample project

**Link to minimal example project:**
[TilemapCollision.zip](https://github.com/godotengine/godot/files/1326394/TilemapCollision.zip)

Edit:
Adapted the title, it actually has nothing inconsistent about it, that was a bit rush but the results look confusing (to me, anyway).

An example in a more descriptive form:
The ball (circular collision shape) moves straight to the left, and eventually hits a tile of a tilemap, detected via is_colliding(), giving a collision position with an x value of 64.
The tile being hit (with x=0 for position) is 64 pixels wide (as is its matching rectangular collision shape), ranging from 0 to 63. 
Using world_to_map with that collision position then (correctly) returns [1, 7], but the tile that was hit is actually at [0,7], just left beside of it.

Moving the ball to the right works as expected, i get the right tile, there lies my confusion i guess.
To me it appears the collision position is slightly off, if it were to happen with an x value of 63 then the correct tile would be returned from world_to_map on that position.

Uncomment line 21 in main.gd to allow a small (simplistic) addition to the position to correct the ''straight left example', it does not solve all cases/angles though.

Perhaps i'm not completely completely understanding the inner workings and looked at it too long and missed it. I'm not getting the logic here. 

I can imagine to correct for some occurrences but that feels like not the way to go, perhaps it's a rounding issue that i'm not seeing.

This is from a gdscript point of view btw.

P.S.
Previous comment is obsolete

**Comment by RaTi17** [comment]
Forgot to mention, in the main.gd (line 21) there is a commented line which adds a small bit to the position with the direction, the collision to the left then returns the tile (0) correctly, but that does not solve it for a diagonal collision.

**Comment by akien-mga** [comment]
Your tile [1, 7] starts at `Vector2(1*64, 7*64)`, so it's normal that calling `world_to_map` with an `x` of 64 will give you the second tile (1 instead of 0).

When you use `world_to_map`, you should subtract the half tile size on X and Y to ensure that you're asking for something within the tile, and not at its border.

**Comment by RaTi17** [comment]
I see, 
Thanks for the clarification.

**Comment by akien-mga** [comment]
Actually I was wrong, it's when using `map_to_world` that you should add the half tile size as offset to the center of the tile, as done e.g. here: https://github.com/akien-mga/dynadungeons/blob/master/scripts/level.gd#L55-L67

From a quick look at your script I don't see any issue, so I just wonder if your expectations on the actual tile being hit are correct? If it tells you that it's hitting in x = 64, then it's effectively the second tile, as tile 1 goes from 0 to 63, and tile 2 starts at 64.

I can't try the demo right now, but I'll try to have a look later on to confirm.

**Comment by RaTi17** [comment]
My thoughts are that the collision x position should be 63, from 64 and on it is indeed another column of tiles. I fixed in in my code some time ago, it is not hard to correct for this but it seems a bit illogical (just one pixel off from where i expected the collision to happen)

Thanks for looking into this.
