### ISSUE TITLE
Selection color makes documentation unreadable

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11501]
Godot 3.0 master

Selecting text in a documentation file makes it unreadable. In comparison, script files are fine because text takes a dark color instead.
![image](https://user-images.githubusercontent.com/1311555/30767692-4234bf82-9fff-11e7-9f3c-87c389747f34.png)

Note: this other issue could become related https://github.com/godotengine/godot/issues/11502

**Comment by toger5** [comment]
there is a setting for selection color. and since we have the generated code theme it is only used in help.
I think this option should get removed an help just uses the same than the generated theme.

**Comment by toger5** [comment]
also #11407 would make it look better...
