### ISSUE TITLE
Selecting a sprite with big texture on it is very slow

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11503]
Godot 2.1.3, Godot 3.0 master
Windows 10 64 bits

I just noticed that selecting a sprite having a big texture on it in the viewport freezes the editor for a second or two. On comparison, selecting a smaller sprite is instant, scaled or not. Selecting in the tree doesn't have this issue.
It's unclear to me why this would be so slow?

Repro:
1) Create a big PNG, like 4000x4000 or above
2) Assign it on a sprite (notice first freeze as you assign it, but it's because of a `load`)
3) Deselect anything
4) Now click on the sprite in the viewport: notice short freeze

**Comment by MarianoGnu** [comment]
PR #15012 tries to solve this in a different way than #12312 
I dont know wich one is better since i sincerely dont understand how #12312 works
