### ISSUE TITLE
Add an option to not override selected text color

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11502]
Godot 3.0 master

I just found it would be useful to be able to NOT change text color to black when selecting it, because it would allow customizing a dark selection color without alterating initial text color and syntax highlighting.

Example of this in Sublime Text:
![image](https://user-images.githubusercontent.com/1311555/30767740-bb7df53e-9fff-11e7-9f4c-91fe8c2c125c.png)

The result in current Godot:
![image](https://user-images.githubusercontent.com/1311555/30767766-1a8c74ce-a000-11e7-84e6-d5f778a44b0b.png)

**Comment by mhilbrunner** [comment]
Fixed by https://github.com/godotengine/godot/pull/11407
