### ISSUE TITLE
False positive on error trying to connect to peer (Condition ' p_peer.is_null() ' is true)

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#1150]
When Godot complains with error:

	ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true
	At: core/io/packet_peer.cpp:228

..it's because `ScriptEditorDebugger` is trying to stop the connection, but `PacketPeerStream` doesn't allow to clear it's peer reference. Since `PacketPeerStream` already checks that peer is a valid reference before trying to do something with it, the peer's reference can be cleared safely.

***tools/editor/script_editor_debugger.cpp***

	void ScriptEditorDebugger::stop(){
	
		set_process(false);
	
		server->stop();
	
		ppeer->set_stream_peer(Ref<StreamPeer>());   // <--- this is what is thorwing an error

		if (connection.is_valid()) {
			EditorNode::get_log()->add_message("** Debug Process Stopped **");
			connection.unref();
		}

		pending_in_queue=0;
		message.clear();

		if (log_forced_visible) {
			EditorNode::get_log()->hide();
			log_forced_visible=false;
		}

		hide();
		emit_signal("show_debugger",false);
		
	}

***core/io/packet_peer.cpp***

	void PacketPeerStream::_set_stream_peer(REF p_peer) {

		ERR_FAIL_COND(p_peer.is_null());  <---- not nedded
		set_stream_peer(p_peer);
	}

	void PacketPeerStream::set_stream_peer(const Ref<StreamPeer> &p_peer) {

		ERR_FAIL_COND(p_peer.is_null());	<---- not needed

		if (p_peer.ptr() != peer.ptr()) {
			ring_buffer.advance_read(ring_buffer.data_left()); // reset the ring buffer
		};

		peer=p_peer;
	}

**Comment by akien-mga** [comment]
This one is all debugged @reduz, so it should be relatively easy to fix for you.
