### ISSUE TITLE
Type icons are corrupted

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11505]
**Ubuntu 17.04, Godot Build: 1481a1b**

**Issue description:**
Self-explanatory:
![screenshot at 2017-09-22 23-51-43](https://user-images.githubusercontent.com/30739239/30769665-1f7b8666-9ff4-11e7-8088-9c4154029c54.png)

**Comment by djrm** [comment]
as far as i can tell there are no type icons right now, and probably will not be in a long time, so i would say that the option to enable type icons should be removed until we have all the type icons.

**Comment by YeldhamDev** [comment]
@djrm Aren't those it?

![screenshot at 2017-09-23 01-20-17](https://user-images.githubusercontent.com/30739239/30770066-63a11140-9ffd-11e7-8ada-cec06f1fd45e.png)

**Comment by djrm** [comment]
@YeldhamDev yes, but there are only some of them, not all the types are covered, also i removed those icons since they might need to be redone once the visual shader editor returns.

**Comment by reduz** [comment]
Type icons option should be removed. I have no idea where this option is. I suggest looking for it (based on the editor settings name), and remove the EDITOR_DEF line.
