### ISSUE TITLE
Transparency turns off screen space reflections

### ISSUE THREAD

**Issue by GiantBlargg** [godotengine/godot#11523]
*Godot commit d3ea922

If I have a material that is set to be transparent, ss reflections aren't drawn on it.

[Example Project](https://github.com/godotengine/godot/files/1326947/reflectionTransparency.zip)
![screenshot](https://user-images.githubusercontent.com/1700581/30778023-f211ba40-a086-11e7-949c-34e21c10f6a1.png)
The materials used on both sides of the plane are identical except that one side has the Transparent Flag set.

**Comment by reduz** [comment]
This is by design, Godot needs a depth reference to make a screen space reflection. Transparent materials generally don't write depth so they won't be visible.

**Comment by reduz** [comment]
Keep in mind this is the same for most screen space effects, such as SSAO or Subsurface Scattering,
and it's a limitation in most (if not all) game engines.
