### ISSUE TITLE
KinematicBody keeps "jumping" with move_and_slide

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#11520]
**Godot 3 master 18e453baf**

**Issue description:**
Using `move_and_slide` a KinematicBody will make it jump constantly even at the smallest separation margin, and a bit bigger safe margins do not seem to be working right, like if small are still too big.

This affects `is_on_floor` and also is noticeable on the visual nodes attached to the body (like meshes).

**Steps to reproduce:**
Use `move_and_slide` and watch the body little jumps.
Or use `is_on_floor` and look at the intermittent true/false values.

![buggymove](https://user-images.githubusercontent.com/10215987/30777176-79179632-a08b-11e7-8b37-29c289caad22.gif)

**Link to minimal example project:**
Can be seen in the Kinematic Character 3D demo.

**Comment by jedStevens** [comment]
I am getting the boolean flickering without the jumping. Maybe its because I'm using a capsule collider and not a cube, but when asked to print `AIR` or `FLOOR` based on KinematicBody's return value of `is_on_floor()`, I get output such as:
 
        AIR
        FLOOR
        AIR
        FLOOR
        AIR
There are points on ramps and when falling where I get a chain of the same value back again, but in an idle state I too get this flickering of the function `is_on_floor()`

**Comment by jedStevens** [comment]
After some fiddling around I had the idea to check the potential of falling for two frames. If it thinks the player can fall it will start applying gravity. This small check before I apply gravity solved my issue, as well as let me detect ramps for stairs, so I stop applying gravity so he doesn't slide.

I know this isn't the optimal fix but I have yet to dive into the physics portion of the engine.

Here is my snippet that solved things for me:

    if not is_on_floor() and not test_move(global_transform, Vector3(0,GRAVITY*delta*2, 0)):
		    velocity.y += GRAVITY * delta
		    print("AIR")
	    else:
		    print("FLOOR")

**Comment by eon-s** [comment]
I think the issue is related to the separation, the same can be made with a big margin (in relation to the body and speeds) on 2D, but 3D seems to have bad separation values (maybe too big for the 3D units).

**Comment by jedStevens** [comment]
Yeah I boiled it down to "the physics engine must be separating the bodies for one frame; in turn being enough to be off the floor".

Is the intention of `is_on_floor()` to detect if it hit the floor this frame? Or should it be is this body standing on a floor. I feel like intuition points to the latter.

**Comment by eon-s** [comment]
Well, I have thought that the safe margin values were caped at 0.001 minimum (like in the inspector), the problem gets solved if manually set the safe margin to 0.0001 (it does not have a setter so I had to use `set`).

@reduz could be possible to increase the minimum (allow smaller) values for the inspector? in case the extreme low values needed for this are not related to a separation bug.

**Comment by jedStevens** [comment]
I ended up just doing a check based on the gravity I was applying, I know its not the best but it also fixed my issues. I did `if test_move(GRAVITY * delta * 1.25)` and only applying gravity if it will hit nothing 1.25 frames in the future. It also fixed my ramps because now I no longer apply gravity when on any surface I would hit going downwards. Good for my game so far, but I can see issues of doing this in more complex scenarios with more bodies in the scene.

**Comment by kubecz3k** [comment]
probably it's worth to recheck now (#12641)

**Comment by jedStevens** [comment]
Weird, after bullet some of the issues I've been having have "reversed".

I was getting this popping effect on the Plane shape previous to bullet, so I switched my prototype to Cube collisions and that stopped the jumping. Now after bullet I get popping on the Cube collisions and perfect collisions against the Plane. Hmm. I'm sure this will be buffed out eventually, as changing the safe margin didn't have much effect either.

However this could just be old code not wanting to port, but I thought that there shouldn't have to have been changes on the dev side. I'll clean it up and try to discover more this week.

**Comment by eon-s** [comment]
There is no noticeable bouncing using bullet with any separation but there is a weird issue.

Using the Kinematic Character demo with bullet and a safe margin of 1 on the kinematic, I have noticed some bouncing on the initial contacts after falling (some false after true on `is_on_floor` ) , the strange thing (tm) is higher and lower separations work as expected.

I wonder if big safe margin with bullet does something too, with godot physics, high margins make bodies literally jump at low speeds but bullet keeps the bodies in place.

cc @AndreaCatania

**Comment by jedStevens** [comment]
Yeah I was going to say that I noticed some issues on the GridMap mostly, when walking over transitions made my walking man jump. I'm sure this is an easy fix for someone who understands bullet.

**Comment by eon-s** [comment]
Jumping in between meshes may be another issue, if you can make a simple working sample project with that problem open another one (if you think is not the same as this, of course).

**Comment by AndreaCatania** [comment]
I'll check it soon

**Comment by eon-s** [comment]
Something common for godot and bullet, while hitting a wall AND floor with a good separation, it does a true-false on floor.
Looks like sliding is clearing the floor hit when hitting wall when both should be true.

cc'ing @randomshaper too.

**Comment by MarianoGnu** [comment]
i have the same issue on 2D physics both with move_and_slide and move_and_collide :/

**Comment by AndreaCatania** [comment]
I've fixed it, Now I'm trying to improve the code.

**Comment by reduz** [comment]
let me guys remind you that safe margin should be a really small value,
like 0.001 which is invisible

**Comment by AndreaCatania** [comment]
Fixed: #12713

Now the kinematic body should be perfectly stick with floor, even with margin equal to 1.

**Comment by kubecz3k** [comment]
(closed to quickly, pr is not merged yet)
