### ISSUE TITLE
VSE Bug - Scalar Uniform of Vertex Shader resets Name if you hit Enter while editing it

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#1152]
Uniforms in Visual Shader Editor don't allow to use spacebar in their param name. They reset to default if spacebar is used.

CamelCase is also reset to Camelcase, now I'm not sure if it is a bug or a feature :D

**Comment by akien-mga** [comment]
Can you still reproduce this in the current master branch?

**Comment by n-pigeon** [comment]
Outdated, works now. Closing.
