### ISSUE TITLE
3.0 Shading Language: Editor crashes when you enter letter as index

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#11534]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows, nvidia, c71ee77 

**Issue description:**
if you type character as index like `blah[x] editor will crash`
i know that it is wrong, i made a misstype, but crashing the editor is too much for a punishment

**Comment by reduz** [comment]
This should technically work as it's being checked, but here's the code in case anyone wants to inquiry more about it:
https://github.com/godotengine/godot/blob/master/servers/visual/shader_language.cpp#L2586

**Comment by MarcusSvensson81** [comment]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows, nvidia, 50a9bd4e23e62579e2249de3c27624d6c56df1d0

**Issue description:**
Unable to recreate, and there seems to be an fix for this in 7764640f2241b5972a48665ff2e0d001aff0993c

**Comment by akien-mga** [comment]
Closing as fixed then.
