### ISSUE TITLE
3.0 Particles Shader: impossible to calculate current lifetime

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#11538]
i mean the value that increases over lifetime

for example it could be used to calculate color over lifetime using gradient texture

but there is no values that change themselves

LIFETIME just holds the lifetime max

**Comment by curly-brace** [comment]
but i could be wrong tho. because now i've understood that CUSTOM vector is persistent during particle lifetime and could be updated with DELTA

but it is not very intuitive solution, may be it would be better to add some variable that is [0..1] range and updates automagically.

**Comment by eon-s** [comment]
LIFETIME is the emitter parameter, not the time-of-life of the particle, is not too clear and not very useful (but INDEX is worse because it gets reset making harder to do complex effects).

And yes, you can store deltas in CUSTOM (vec4), is limited but may be enough for most uses, I guess.

**Comment by curly-brace** [comment]
yeah i understand what LIFETIME is, but using CUSTOM is a bit strange imo

**Comment by KoBeWi** [comment]
Somewhere since 3.0, `CUSTOM.y` is the automatically updated 0...1 value for current lifetime. It is even stated so in [Shading Language doc](https://docs.godotengine.org/en/3.0/tutorials/shading/shading_language.html#id3).

Closing as resolved.
