### ISSUE TITLE
VSE Crash - wierd crash after using Scalar Op with Pow and 0.5 value (test file)

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#1153]
TEST FILE: https://dl.dropboxusercontent.com/u/31390469/bug%20bin/scalar_op_bug.zip

Instructions: go to objects shader graph and change present there Scalar Const to 0.5.

From what I tested occurs only with this test file, I tried to make simpler example and it didn't crashed there.

**Comment by akien-mga** [comment]
Can you still reproduce it in the current master branch? If so, could you reupload a test file that reproduces the issue?

**Comment by n-pigeon** [comment]
Hmm, I lost file and don't remember what it was all about. Closing.
