### ISSUE TITLE
Incorrect default UV map on CubeMesh

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#11540]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):** Windows 10, Godot Git https://github.com/godotengine/godot/commit/d3ea92257dc48dece18ae142fa2739601b711137, NVIDIA

**Issue description:** The default UV map of the CubeMesh (as part of MeshInstance) does not fit the mesh (the texture also is stretched in a non-uniform manner). See below for an example with `icon.png` applied to a CubeMesh:

![Incorrect UV on CubeMesh](https://user-images.githubusercontent.com/180032/30781723-a554796a-a124-11e7-9250-4d8e67e19c49.png)

**Steps to reproduce:** Create a CubeMesh from a MeshInstance, then create a SpatialMaterial and apply an albedo texture to it.

___

**Workaround:** To obtain a correct UV mapping, set the Uv1 scale to `(3, 2, 1)`. It will then look like this:

![Correct UV on CubeMesh](https://user-images.githubusercontent.com/180032/30781791-d49b9afe-a125-11e7-9281-726dd8904d0c.png)

**Comment by BastiaanOlij** [comment]
@Calinou it's designed so each face has its own part of the texture, all primitive shapes are like that.  So this map would work perfect with the cube:

![cube_6](https://user-images.githubusercontent.com/1945449/30782555-d467263c-a177-11e7-9c66-c9f3c585f87d.PNG)

See https://github.com/BastiaanOlij/godot3_test_projects/tree/master/TestPrimitives

**Comment by Calinou** [comment]
> @Calinou it's designed so each face has its own part of the texture, all primitive shapes are like that.

That makes sense, I'll close this then. It should be noted in the documentation that an UV scale of `(3, 2, 1)` should be used, if one wants to display the same texture on all faces.

**Comment by BastiaanOlij** [comment]
@Calinou I think updating the documentation is a good idea :)

**Comment by randompast** [comment]
In the fragment shader, this is done by multiplying the UV values by the corresponding vec2.  Note that the 1 isn't used since UV doesn't have a third component. 
`ALBEDO = texture(tex, UV * vec2(3.0,2.0)).xyz;`

**Comment by Calinou** [comment]
> Note that the 1 isn't used since UV doesn't have a third component.

UV's third component is used for triplanar materials :slightly_smiling_face:
