### ISSUE TITLE
Invalid set index 'index'(on base:'Dictionary')

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#11543]
godot 3.0
func _ready():
	var test = {}
	test.index=0

error  Invalid set index 'index'(on base:'Dictionary')

**Comment by Noshyaar** [comment]
3c857033df954b481fb6ba9545b074588b1aee02 is the first bad commit

**Comment by hpvb** [comment]
Looks like reduz forgot to add a couple of indexed getters. Let's have a look :)

**Comment by hpvb** [comment]
It looks like Dictionaries don't have set_named at all any longer. I think it used to.

**Comment by gamergamesz** [comment]
Same with visual script i mean that 'Invalid set'
