### ISSUE TITLE
Removing viewport world causes get_frustum() to fail and spatial audio playback to crash in the editor

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#11544]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7
Godot 3.0 from master
GTX 760

**Issue description:**
Kind of two issues here, but they are related and one lead to me finding the other. I've noticed this problem (get_frustum errors) with 2.x before, but the editor crash was a new one in 3.0

I'll try and explain it as best I can.

Basically, the problem happens when you set the world parameter on a viewport (which has a child camera), clear it, save and then close the scene.

When the scene is re-opened, everything will appear fine, but if you then create a new blank scene or open up any other scene, you'll get the following error every time the editor camera updates:

scene/3d/camera.cpp:601 - Condition ' !is_inside_world() ' is true. Returned: Vector<Plane>()

This was annoying as it slowed down the editor a bit, but it didn't usually stop me working. Unfortunately that changed when I found that if you try to play a spatial sound by clicking the 'playing' checkbox on an AudioStreamPlayer3D the editor will crash. I suspect this is because the 3D audio relies on the camera position and whatever's causing the previous error has probably caused a null reference to something 

**Steps to reproduce:**

- Load the project I've attached
- Select the viewport node and then clear the world it currently has set (You might start seeing 'scene/resources/world.cpp:125 - ' Condition !E ' is true.' errors)
- Save the scene and close it
- Load the scene
- create a new blank scene and move the camera around, you should see lots of this error: 
scene/3d/camera.cpp:601 - Condition ' !is_inside_world() ' is true. Returned: Vector<Plane>()

The issue with audio is that spatial play back in a scene where this error is happening will cause godot to crash

**Link to minimal example project:**
[viewport_bug.zip](https://github.com/godotengine/godot/files/1327398/viewport_bug.zip)

**Comment by reduz** [comment]
This is really complex to fix and will require some internal refactoring that I don't want to do now. Will kick to 3.1

**Comment by reduz** [comment]
Can no longer reproduce, I think this was probably fixed at some point, closing.
