### ISSUE TITLE
Image Preview from "Resources" or "FileSystem"

### ISSUE THREAD

**Issue by BodhiPeace** [godotengine/godot#1154]
I would like to submit a request to preview images when clicking on the name from the Resources Tab or the FileSystem Tab down below.

Currently, when you double-click on a PNG image under FileSystem, it opens highlights the name of the file under Resources. Maybe when you double-click on the file name under Resources it could force the Inspector Tab to show a small preview of what the image looks like. The current implementation changes the Inspector Window, but does not select the tab and make it visible. A PNG image is described by it's dimensions, compression, mipmaps, quality, etc.

**Comment by reduz** [comment]
this feature is planned for 1.1!

**Comment by akien-mga** [comment]
> this feature is planned for 1.1!

And it was implemented :)
