### ISSUE TITLE
AnimationPlayer doesn't update material parameter if material is changed at runtime

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#11548]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7
Godot 3.0 from master
Geforce GTX 760

**Issue description:**
Since materials/shaders are shared across instances (I believe? or at least the mesh they're on) when instancing scenes that use materials that have parameters you want to animate using an AnimationPlayer, I've found you have to duplicate the material so that it's unique. If you don't do this, then the other instances end up being affected. 

In 2.x I got around this issue by duplicating the material so that it was unique, but the same method doesn't seem to work in 3.0. Even though the path to the parameter the animation player is animating exists, it doesn't seem to affect the newly applied (at runtime) material. Perhaps it's still referencing the original material and updating that instead?

**Steps to reproduce:**
Download and run the project I've attached
Click the 'Duplicate Material' button on the screen, the ball on the right should stop pulsing red.

**Link to minimal example project:**
[animation_material_bug.zip](https://github.com/godotengine/godot/files/1327478/animation_material_bug.zip)

**Comment by mhilbrunner** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by sketchyfun** [comment]
Welp, I just ran the project I attached 7 months ago and the material does stop pulsing when I duplicate the material, so it looks like it's been fixed :)

**Comment by mhilbrunner** [comment]
Good to know, thanks for checking! :)
