### ISSUE TITLE
Add scale parameter for some draw methods?

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#11559]
Example:
```
void draw_string( Font font, Vector2 pos, String text, Color modulate=Color(1,1,1,1), int clip_w=-1, Vector2 scale)
Draw a string using a custom font.
```

Could also be added for other draw methods (draw_style_box, draw_texture)

For example, implementing damage numbers, the developer shouldn't really be using hundreds of cached sprites, or duplicating node2d just to take advantage of the scaling.

Instead, creating a `damage_numbers` array and simply populating it and using `draw_string` is far better on performance in comparison. Especially when hundreds of numbers are being dynamically generated while in combat / 6 + players in map

And with the scale parameter, it would let developers create cool pop in number effects

**Comment by sketchyfun** [comment]
You can call draw_set_transform - http://docs.godotengine.org/en/stable/classes/class_canvasitem.html#class-canvasitem-draw-set-transform

This will affect any draw methods that are called afterwards

**Comment by Calinou** [comment]
> You can call draw_set_transform

The problem with this method is that text scaling will be blurry or pixelated (depending on what kind of style you are going for). This is fine for pixel-art games, but not for games which should not make use of nearest-neighbor filtering.

**Comment by sketchyfun** [comment]
The only way you can avoid pixelating or blurring is to use signed distance field fonts, bitmap fonts will always have this issue (unless you had multiple font sizes stored)

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
