### ISSUE TITLE
glTF importer fails to import models with armatures

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11557]
Same as #10130.
I haven't succeeded in importing any animated models with armatures, be with with khronos gltf exporter (mostly results in segfaults), blendergltf or a gltf model downloaded from sketchfab.

**Comment by tagcup** [comment]
For the sake of argument, [here](https://www.blendswap.com/blends/view/3960) is a simpler model which also crashes godot when importing the gltf file generated by khronos gltf exporter.

**Comment by phyffer** [comment]
I can confirm this, I hope this stacktrace helps:

> ...
> type float component type: Float stride: 4 amount 1
> accessor offset0 view offset: 2000752 total buffer len: 2000768 view len 4
> type vec3 component type: Float stride: 12 amount 1
> accessor offset0 view offset: 2000756 total buffer len: 2000768 view len 12
> total animations: 1
> ERROR: Vector<class Skeleton *>::operator []: FATAL: Index p_index out of size (size()).
>    At: e:\godot\core\vector.h:137
> CrashHandlerException: Program crashed
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/
> godot/issues
> [0] Vector<Skeleton * __ptr64>::operator[] (e:\godot\core\vector.h:137)
> [1] Vector<Skeleton * __ptr64>::operator[] (e:\godot\core\vector.h:137)
> [2] EditorSceneImporterGLTF::_generate_node (e:\godot\editor\import\editor_scene_importer_gltf.cpp:1
> 635)
> [3] EditorSceneImporterGLTF::_generate_scene (e:\godot\editor\import\editor_scene_importer_gltf.cpp:
> 1988)
> [4] EditorSceneImporterGLTF::import_scene (e:\godot\editor\import\editor_scene_importer_gltf.cpp:210
> 0)
> [5] ResourceImporterScene::import (e:\godot\editor\import\resource_importer_scene.cpp:1048)
> [6] EditorFileSystem::_reimport_file (e:\godot\editor\editor_file_system.cpp:1403)
> [7] EditorFileSystem::reimport_files (e:\godot\editor\editor_file_system.cpp:1517)
> [8] EditorFileSystem::_update_scan_actions (e:\godot\editor\editor_file_system.cpp:395)
> [9] EditorFileSystem::_notification (e:\godot\editor\editor_file_system.cpp:1018)
> [10] EditorFileSystem::_notificationv (e:\godot\editor\editor_file_system.h:100)
> [11] Object::notification (e:\godot\core\object.cpp:851)
> [12] SceneTree::_notify_group_pause (e:\godot\scene\main\scene_tree.cpp:913)
> [13] SceneTree::idle (e:\godot\scene\main\scene_tree.cpp:488)
> [14] Main::iteration (e:\godot\main\main.cpp:1670)
> [15] OS_Windows::run (e:\godot\platform\windows\os_windows.cpp:2138)
> [16] widechar_main (e:\godot\platform\windows\godot_win.cpp:149)
> [17] _main (e:\godot\platform\windows\godot_win.cpp:171)
> [18] main (e:\godot\platform\windows\godot_win.cpp:183)
> [19] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)
> [20] BaseThreadInitThunk
> -- END OF BACKTRACE --

Kupoman's gltf exporter is able to import the model, but not the skeleton

**Comment by jedStevens** [comment]
Can confirm this.

My baseman's foot is apparently also many parts of his body.
![baseman_gltf_error](https://user-images.githubusercontent.com/6509081/31957249-27b478de-b8bc-11e7-925a-16075ba21bde.png)

**Comment by reduz** [comment]
I'm kind of fed up of these formats,  will convert skeletons to global coordinates..

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by jedStevens** [comment]
No

On Jan 8, 2018 5:41 AM, "Rémi Verschelde" <notifications@github.com> wrote:

Is this still valid in the current master branch?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/11557#issuecomment-355932746>,
or mute the thread
