### ISSUE TITLE
F12 to screenshot

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#1155]
I think it'd be good for Godot to have a built-in ability to screenshot the running project. It could be saved into a single filename under res:// so pressing F12 multiple times would overwrite one image. And this same image could be used in a revamped Project Manager window, like ndee's mockup with the Brave Bran picture.

**Comment by akien-mga** [comment]
It should likely be saved in user:// with a timestamp in the name instead of res://, if it's saved in a single filename in res:// it's usefulness would be pretty limited. A general ability to save screenshots in the user dir would be good and useable also for exported games; it should probably be defined to override the OS PrintScreen instead of a custom hotkey.

**Comment by adolson** [comment]
The limited usefulness was actually desired - this was a request specifically for use with a new project manager as per ndee's mockup. If the screenshot is present in a project directory (res://) then the project manager loads it, otherwise I'm not sure how it's going to know where to find the image for each project. The ability to set the screenshot with F12 makes it easy - and as written, was a feature of the editor, not the exported game.

That being said, if the new project manager is not happening, and this becomes a basic built-in feature, so be it... But I don't find that to be all that useful, since the OS has the feature already, as does Steam, and other tools. In light of that, it had best be a toggle option - I don't want my games overriding expected behavior from the OS or Steam.

**Comment by MarianoGnu** [comment]
I dont find any uses for this, it's already posible to make a short script to do this if you want to, if you override res://icon.png you can use the screenshot as tumbnail in the open project dialog.

**Comment by adolson** [comment]
Clearly nobody understands what my request was for. That's what happens when these things sit dormant for almost a year. I'll close it.
