### ISSUE TITLE
Shader editor triggers viewport shortcuts on macOS

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#11556]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

When typinginthe shader editor the `R` key triggers the rulers in the viewport.

@groud maybe it is not checking the viewport is the active window?
(i didnt test if that is also the case for `Q W E R` keys. But i dont think so.)

**Steps to reproduce:**
Create shader -> type in "color" -> see the ruler appear/ disapper when pressing `R`

**Link to minimal example project:**

**Comment by groud** [comment]
I can't produce :/
Could you give me a more detailed way to reproduce ? How do you create the shader ?

**Comment by toger5** [comment]
os is macOS.
the shader is created with the inspector.
click on canvas item -> new shader material -> new shader -> shader code editor appears.
Ill create a short video.

**Comment by toger5** [comment]
@groud https://youtu.be/tP9kJFaWO6w
this is a short demonstration.

**Comment by groud** [comment]
> Ill create a short video.

That would be cool. I did exactly what you are describing, so a video could help understanding the problem.

**Comment by groud** [comment]
Weird, it seems like your shader editor does not grab focus like mine does.

**Comment by toger5** [comment]
this is because I use border size 0.
same godot instance than the video just changed the border size in editor settings:
<img width="1680" alt="screen shot 2017-09-25 at 11 49 54" src="https://user-images.githubusercontent.com/16718859/30802726-bf1803b2-a1e7-11e7-8cf6-f15f4518aeda.png">

**Comment by groud** [comment]
Ok I definitely can't reproduce on linux.
Can any other OSX / Windows user try that ?

**Comment by toger5** [comment]
Maybe ill find some time debugging it myself.
It is weird that it is platform specific though...

**Comment by Jerome67000** [comment]
On Windows 8.1 I can't reproduce that

**Comment by reduz** [comment]
@groud just making sure, does this work for you ?

**Comment by groud** [comment]
> @groud just making sure, does this work for you ?

Yeah, I still can't reproduce on my computer.

**Comment by cbscribe** [comment]
I noticed this happening today (also MacOS) build f5c513c

When typing in shader editor, 'r' triggers rulers.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by Jerome67000** [comment]
Working fine on windows 10 with current master build.

**Comment by akien-mga** [comment]
Any macOS user to test it? @bruvzg @BastiaanOlij @endragor

**Comment by bruvzg** [comment]
@akien-mga Yes `F`, `G`, `H`, `R` and `Y` entered in shader editor changes viewport view options.

**Comment by akien-mga** [comment]
Thanks, so that confirms that there is an input propagation issue on macOS.
