### ISSUE TITLE
Editor's viewport doesn't redraw on Node2D deletion leaving icons, helpers, the selection rectangle,...

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11560]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/1f4685375f2d2e36a2e19e67ac9f614b8c99ea28

**Issue description:**

![2017-11-02_18-55-06](https://user-images.githubusercontent.com/483531/32342027-7d7454e8-bfff-11e7-9281-0912f691b5b8.gif)

**Steps to reproduce:**
1. Add a Node2D
2. Select it
3. (optional) toggle the lock or the grouping modes
4. Delete it
5. Icons, helpers, selection rectangle,... are still in the editor viewport

**Link to minimal example project:**

**Comment by groud** [comment]
As @YeldhamDev mentionned, the problem il also here for lock icons and helpers.
The viewport probably need are redraw on delete.

**Comment by reduz** [comment]
@groud (or anyone else) check SceneTreeDock and, worst case, just force redraw to CanvasItemEditorPlugin from there. I may have added similar code for other circumsatances there.

**Comment by groud** [comment]
Well I wanted to finish reworking the gui inputs in the canvas item editor but it might take a while. I'll probably fix this sooner to avoid other issues to be opened.
