### ISSUE TITLE
editor help spacing. Space at beginning of line + bigger paragraph spacing.

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#11572]
**Issue description:**

basically the screenshot tells everything.
When there is a newline it has a space at the beginning which makes it look misaligned. (maybe that is even intended but I would prefer a straight vertical line for the line beginning)

<img width="974" alt="screen shot 2017-09-25 at 12 26 28" src="https://user-images.githubusercontent.com/16718859/30804198-ca307234-a1ec-11e7-9ace-4399e8fa9b9c.png">

**Comment by akien-mga** [comment]
I think the indent could indeed be removed, and there should be more spacing between each paragraphs.

**Comment by toger5** [comment]
@akien-mga yea a little more spacing would be great too. I edited the issue name.

**Comment by Jerome67000** [comment]
Yep I talked about that in #documentation Discord chan and agree that indent is a little bit weird. In addition, most documentation text is with one line or one line + one return.

**Comment by poke1024** [comment]
This has been fixed in the meantime:

<img width="249" alt="docs" src="https://user-images.githubusercontent.com/11859538/34651542-d021ef74-f3d1-11e7-8c94-731c25a6ccac.png">
