### ISSUE TITLE
GDScript Function call performance is very low

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#11578]
GDScript Function call performance is very low

**Comment by hpvb** [comment]
Can you please provide us with a piece of gdscript code that we can benchmark and optimize for your case? There is no information in this issue report at all and this is very difficult for us to act upon.

**Comment by cjmxp** [comment]
func _input(event):
	if event is InputEventMouseMotion:
                gui_find_control(event.position)

func _input(event):
        if event is InputEventMouseMotion:
                get_viewport().find_control_at_pos(event.position)

**Comment by cjmxp** [comment]
When will C# be supported?

**Comment by hpvb** [comment]
OK, you say the above is slow, what makes you think it is slow and how fast do you expect it to be?

**Comment by cjmxp** [comment]
After the GD version of the find_control_at_pos call, FPS can reduce the 7fps, of course, and the movement speed of the mouse

**Comment by hpvb** [comment]
OK, that probably means that find_control_at_pos is actually the culprit, c# wouldn't help you there then. I'll see if it can be made faster.

**Comment by NathanWarden** [comment]
@cjmxp You can make a build of Godot 3 with C# support now and it's working pretty nicely so far :) The repo with the C# module is in the GodotSharp repo: https://github.com/neikeq/GodotSharp

**Comment by akien-mga** [comment]
>  gd_find_control_at_pos(event.position)

Where does that method come from?

**Comment by cjmxp** [comment]
I use gdscript to achieve the scene within 200 NPC to do the mouse movement, select the mouse movement too fast, FPS reduce a lot

**Comment by cjmxp** [comment]
@akien-mga   I didn't upload the code. You can do gdscript calls. The test performance should be below JS. I'll upload my code tomorrow

**Comment by hpvb** [comment]
There's are some functions in viewport that correspond to the reporters' function. I don't see the gdscript binding for it though, I'm not sure what OP is doing exactly now.

**Comment by cjmxp** [comment]
You don't understand what I mean. I'll close this issue first. I'll upload demo tomorrow

**Comment by groud** [comment]
find_control_at_pos() needs to recursively go across all nodes of the tree, It is normal that it's slow.
However I don't think this is the right way to go, usually such behaviour should be implemented in the control node itself, as Input event are already processed and sent to hovered nodes. There are not a lot of reason to use this function I mean.

That being said, there are probably some optimization that could be done thus.

**Comment by groud** [comment]
Please don't close this issue yet, you can add your demo in this issue.

**Comment by groud** [comment]
What Godot version are you using ?

**Comment by cjmxp** [comment]
The problem is not find_control_at_pos in the gdscript function is a function of the internal CPP did not open, but I think the execution efficiency is very poor with gdscript to achieve a similar function, this function so I open to the GD call FPS normal stable at 60

**Comment by cjmxp** [comment]
@groud 3.0

**Comment by groud** [comment]
I am sorry but it's really hard to understand the problem.
Where if `find_control_at_pos` defined ? Is that a function you wrote yourself ?

**Comment by cjmxp** [comment]
Please restore the title. This issue header is incorrect. It is not what I want to say

**Comment by cjmxp** [comment]
@groud  gd_find_control_at_pos, I wrote it in gdscript

**Comment by groud** [comment]
Aaaaaah I think I get it! 

So you're juste saying GDscript is slower that CPP ? 
Yes it is, GDscript is interpreted while CPP code is native code. If you are trying to implement computational intensive code with GDScript you'll end up with bad performances.

**Comment by cjmxp** [comment]
@groud That's great. You finally got it. I can't speak English. I'm sorry. Gdscript's performance is so bad, FPS is down to 7, CPP is 60, and it's crazy to play with gdscript

**Comment by reduz** [comment]
Gdnative C++ or C# might help.. but maybe the function itself is dealing
with too much? You can use Area2D to efficiently find a node in a specific
position in space.

**Comment by akien-mga** [comment]
You could also use the available built-in method and not try to reinvent the wheel. There's a reason why we provide builtin methods: they're more efficient.

Anyway, without seeing your custom code there's not much that can be said. Maybe the bottleneck is in your logic, maybe it's in API calls, maybe it's in the control flow. We can't know.

**Comment by groud** [comment]
> @groud That's great. You finally got it. I can't speak English. I'm sorry. Gdscript's performance is so bad, FPS is down to 7, CPP is 60, and it's crazy to play with gdscript

No problem, we understand. 
But the fact is this is not an issue, we can't do much about it as GDscript will always be slower than native code. You can use GDnative for performance needing stuff, or built-in functions when they are available. ;)

Consequently, I close this issue.

**Comment by cjmxp** [comment]
I suggest doing a gdscriot related performance test that might help optimize and improve the efficiency of gdscriot

**Comment by groud** [comment]
We're already working on improving GDscript performances: see #11518

**Comment by cjmxp** [comment]
@NathanWarden Can you help me build C#? How much is the mono version? 2 .0?

**Comment by cjmxp** [comment]
@NathanWarden https://github.com/neikeq/GodotSharp/issues/48

**Comment by rpxomi** [comment]
I think this is more related to a personal taste and not so much with performance.
