### ISSUE TITLE
The name of the target is fixed to godot.windows.tools.exe?

### ISSUE THREAD

**Issue by RobertinoValue** [godotengine/godot#1157]
In the [compile instructions for Windows](https://github.com/okamstudio/godot/wiki/compiling_windows), under the heading ```Compiling``` :
> If all goes well, the resulting binary executable will be placed in ```C:\godot\bin\godot_win.exe```

It's actually ```godot.windows.tools.exe```.

On the same page, under the heading ```Development in Visual Studio or other IDEs``` :
> To build the whole engine from a single command outside the command prompt, the following should be called in a .bat file:
```C:\path_to_sdk\vcvarsall.bat &&  scons bin/godot_win.exe```

Specifying ```godot_win.exe```, or any name other than ```godot.windows.tools.exe```, results in this error.
A successful compilation is only achieved by specifying ```bin/godot.windows.tools.exe``` or omitting the target. :

```Text
C:\home\robert\game-engines\godot> "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64 && "C:\Python27\Scripts\scons.bat" platform=windows bin\godot.win.exe
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: *** Do not know how to make File target `bin\godot.win.exe' (C:\home\robert\game-engines\godot\bin\godot.win.exe).  Stop.
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
Will fix this when porting the page from GH to the OpenProject wiki.

**Comment by akien-mga** [comment]
It's now fixed: http://godotengine.org/projects/godot-engine/wiki/Compiling_for_Windows

Thanks for the report :)
