### ISSUE TITLE
Inspector param can't be set

### ISSUE THREAD

**Issue by Jerome67000** [godotengine/godot#11573]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 8.1, Godot 3.0 master branch from 2017-09-23

**Issue description:**
Can set **Soft Clip Ratio** of the AudioEffectLimiter in the inspector

![image](https://user-images.githubusercontent.com/7358899/30805612-6a3422d0-a1f2-11e7-9a19-c81b989eb0b3.png)

When I type a value or try to shift up or down with mouse, the value don't change.
I have the same bug with the **Voice Count** of the AudioEffectChorus.

**Steps to reproduce:**
* Open the Audio pannel
* Add a Limiter effect to the master bus
* Try to change **Soft Clip Ratio** value

**Comment by bojidar-bg** [comment]
Soft clip ratio has a wrong getter: (which gets to return 0, but the property's range is 3..20, so it becomes a 3)
https://github.com/godotengine/godot/blob/aabbd00284640a4789f96702c134ea40b11b402e/servers/audio/effects/audio_effect_limiter.cpp#L107-L114
I can't see a similar problem in the code for voice count though..

**Comment by Noshyaar** [comment]
Soft clip ratio issue is fixed in 09800ac65079599c568679b53962a313182885ea.
I don't have issue with voice count either.

**Comment by Jerome67000** [comment]
You can set voice count from 1 to 4 in the inspector ?  with keyboard or mouse ?
If I type 80 I get 2 or the maximum is 4.

**Comment by ISylvox** [comment]
Indeed, we have two issues related to Voice Count in AudioEffectChorus. I'm trying to fix it right now.

**Comment by ISylvox** [comment]
Submitted PR for Voice Count issues: https://github.com/godotengine/godot/pull/11577

**Comment by Jerome67000** [comment]
It's OK for me, all 2 issues are fixed in this build.

But in the other hand i have this, but maybe it's about the current master modifications :

![image](https://user-images.githubusercontent.com/7358899/30815850-aac25e80-a214-11e7-9d2d-0fc37018a15b.png)

**Comment by ISylvox** [comment]
If you click that yellow triangle icon, you will get a popup message. Afaik, it's a feature.
