### ISSUE TITLE
"Error" appears on SpriteFrames buttons

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#11584]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOS 10.12.6, 3.0master (latest build 06ce436)

Two of the buttons in the SpriteFrames dock are showing "Error":
![screen shot 2017-09-25 at 12 50 19 pm](https://user-images.githubusercontent.com/3812514/30827889-8d95cd5c-a1f0-11e7-8725-2e490cf371ac.png)

**Comment by Jerome67000** [comment]
Hi, i got the same this day : https://github.com/godotengine/godot/issues/11573#issuecomment-331912974

But I have built master tonight, and it seems it's solved, try to build with last commit

**Comment by cbscribe** [comment]
I just built with the latest commit, and the "error" buttons are still there.

**Comment by Jerome67000** [comment]
Indeed, it's still here in the SpriteFrames view, it's looks like the icons are missing

**Comment by AlexHolly** [comment]
Is this only a MacOS issue?

Godot master
Linux
![image](https://user-images.githubusercontent.com/4741886/31736933-5a6f7dfc-b446-11e7-87b9-8eeff3a96c5d.png)

**Comment by cbscribe** [comment]
May have been fixed in a subsequent commit. I'm not seeing the problem in a fresh build.

**Comment by Noshyaar** [comment]
Fixed by #12057
