### ISSUE TITLE
Mixing back slashes with forward slashes, in the same path.

### ISSUE THREAD

**Issue by RobertinoValue** [godotengine/godot#1158]
Sometimes, you're mixing back and foward slahes in the same path.
```  File "./platform/windows\detect.py", line 109:``` (See in context below.)
To reproduce : The error was caused because I didn't issue the command after first calling ```vcvarsall.bat```.

```Text
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Robert>cd C:\home\robert\game-engines\godot

C:\home\robert\game-engines\godot>C:\Python27\Scripts\scons platform=windows
scons: Reading SConscript files ...
TypeError: cannot concatenate 'str' and 'NoneType' objects:
  File "C:\home\robert\game-engines\godot\SConstruct", line 190:
    detect.configure(env)
  File "./platform/windows\detect.py", line 109:
    env.Append(CCFLAGS=['/I'+os.getenv("WindowsSdkDir")+"/Include"])

C:\home\robert\game-engines\godot>
```

**Comment by UsernameIsAReservedWord** [comment]
6.3.9600 commandline terminal accepts mixed / with \ into path.

So, what is the problem ?

**Comment by UsernameIsAReservedWord** [comment]
also, how does it come that you call :

    C:\Python27\Scripts\scons p=windows

instead of just :

    scons p=windows

???

isn't there a pythons path into the system env path if you type this below ?

    echo %PATH%

**Comment by reduz** [comment]
no, scons is inside scripts and that inst in the path, I usually just copy
the .bat to c:\python27

**Comment by UsernameIsAReservedWord** [comment]
( strange ... I have C:\Python27\Scripts into my PATH .... maybe I added it manually and forgot about it ... Oh, anyway, as long as it works ... )

**Comment by RobertinoValue** [comment]
@UsernameIsAReservedWord 
> 6.3.9600 commandline terminal accepts mixed / with \ into path.
So, what is the problem ?

That's a public secret.
Even in the DOS days a forward slash as path separator was allowed, **in scripts only**.
**On the command line** it was initially not allowed because a forward slash was used as switch/argument delimiter.
But there was a ```SWITCHAR``` option in ```config.sys``` to allow forward slashes (mainly for network paths) on the command line. But that turned into a big fail (or whatever) and MS removed the forward slash restriction from the command line, and replaced it with code to accept forward slashes on the command line. I believe since XP.

Anyway, the issue is in the script. Not the on command line.
Each platform has a ```detect.py``` script. So the issue is not limited to the Windows platform.
Apparently the path to the script ```detect.py``` was fed with mixed slashes.
There could be issues where the script ```script.py``` could not be found on the file system.
The back slash on Linux, etc will be treated as an Escape character.
Try "./platform/x11\detect.py" on Linux. (```\d```)

Also if the path is in an unquoted variable and contains one or more spaces in the file name, the forward slashes will be treated as switch/argument delimiters (Windows only issue).

@reduz Has already responded to your other question.

**Comment by UsernameIsAReservedWord** [comment]
@RobertinoValue : oh thanks for these complementary info ! very enlighting. now I understand your point.

**Comment by RobertinoValue** [comment]
The initial issue description is concise and didn't need further clarification.
But under certain circumstances that's not possible.

**Comment by UsernameIsAReservedWord** [comment]
I know github issues are not a knwoledege database, but the link you removed from your previous post was very informative too. You could have left it just in case someone else would have been interested ...

**Comment by akien-mga** [comment]
The above mentioned issue is at line 109 of ```platform/windows/detect.py```, so there doesn't seem to be an issue *reading* the file, I'd assume the path is fine.
