### ISSUE TITLE
MeshInstance.set_mesh(MeshInstance) doesn't fail when not using static typing

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11588]
Godot 2.1.3, Godot 3.0 master
Windows 10 64 bits

After 30 minutes of headbanging, I found the following code runs without producing any error:

```gdscript
var mi = MeshInstance.new()
mi.set_mesh(mi)
```

It should throw a type error.

**Comment by Calinou** [comment]
I can still reproduce this in Godot 3.2.2beta4. Note that using static typing for the MeshInstance variable will prevent this snippet from working. It'll throw an error about types mismatching as expected.
