### ISSUE TITLE
Impossible to set a custom editor font when it is outside of the project

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11589]
Godot 3.0 master

I successfully set a custom text editor dynamic font by simply creating one in a project, then assigning it in the editor settings, showing a full path.

Then I opened a new project, and suddenly Godot was unable to load the font. The script editor went empty, showing only small "spaces", and this error:

```
ERROR: FileAccessWindows::_get_modified_time: Method/Function Failed, returning: 0
   At: drivers\windows\file_access_windows.cpp:248
ERROR: DynamicFontAtSize::_load: Condition ' !f ' is true. returned: ERR_CANT_OPEN
   At: scene\resources\dynamic_font.cpp:137
```

I dragged the font resource in my new project, and it worked again.

I expected the font to work from anywhere, since the path to this resource is global.

**Comment by eon-s** [comment]
The PR added the possibility to add an editor font but not a script editor font, that affects the script editor if special characters are used in places like node names (the script editor can't "find" the nodes).

**Comment by akien-mga** [comment]
It should be easy enough to add the same logic for a custom source font, cc @volzhs. BTW the option exists already but it's in another category, it should likely be moved for consistency.

**Comment by volzhs** [comment]
The editor using a custom font as primary and embedded default fonts as fallbacks.
so, it should work in general cases.
@eon-s I guess you used a really special character. :)

I will take a look at setting a custom font for source code.

**Comment by eon-s** [comment]
@volzhs Mmmmaaaaybe?
![emojitree](https://user-images.githubusercontent.com/10215987/34652864-ce21e4cc-f3c2-11e7-8ff3-3eb24a42da66.png)

**Comment by volzhs** [comment]
@eon-s what an impressive name it is!!
