### ISSUE TITLE
Some placement issues

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#11591]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
f577efd47ed2f0aa801155756e4ba5d5ea2d5f2b

**Issue description:**

there are some placement issues.
ive seen them in EditorSetting dialog, Project settings dialog, and the editor
![screenshot from 2017-09-25 18-49-19](https://user-images.githubusercontent.com/1103897/30836262-a0f631ac-a222-11e7-9db4-1cd8e9287b70.png)
![screenshot from 2017-09-25 18-49-59](https://user-images.githubusercontent.com/1103897/30836265-a5de7198-a222-11e7-9971-651c22d60d7f.png)

ping @groud 

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by groud** [comment]
What's the proble on the editor screenshot ?

**Comment by djrm** [comment]
@groud there used to be a margin, no its gone. the docks reach the limit of the window

**Comment by groud** [comment]
Ok. Is that since #11424 ?

**Comment by djrm** [comment]
@groud, yes

**Comment by groud** [comment]
Oooh. I know what's happening. 
Actually the bug is not really my fault, here the problem is because some children of a container use the anchor/margin system while it should not. (The margin are determined by the parent in this case.

I know how to fix that anyway, I'll make a PR.

**Comment by groud** [comment]
Looks like it was my fault after all. The PR is ready :)
