### ISSUE TITLE
"Changes will be lost!" when editing a shader bundled in a material

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11594]
Godot 3.0 master

I saved a shader in a material, and then saved this material for re-use on multiple objects. But when I edit the shader, the editor stops saving my changes and shows me this:

![image](https://user-images.githubusercontent.com/1311555/30837058-90291be2-a262-11e7-8605-c5cc6e045737.png)

The result of this is that the shader can't be saved anymore.
My expectation here was that editing the same shader reference would update the material resource where it is saved.

Repro:
1) Create a ShaderMaterial
2) Create a Shader within this material
3) Save the material as a file
4) Load the material on a MeshInstance or two
5) Click the material property, then the shader property
6) Notice you can edit the shader, but the editor warns you changes will be lost (and they are)

**Comment by djrm** [comment]
maybe you need to save it with the resource save option, and the message points out that saving the scene will not save that resource, since its not part of the scene.

**Comment by groud** [comment]
Oh, I think I faced the same problem yesterday.

**Comment by Zylann** [comment]
@djrm problem is, shaders are 99% of the time saved with Ctrl+S from the shader editor, it's counter-intuitive to go fetch another save option. Also yeah, my resource is not embedded in a scene, that's the point of it being in a standalone file. I think Reduz even mentionned this as a Godot advantage when he posted about the rendering system in a recent news.

**Comment by KoBeWi** [comment]
I tried to reproduce it and seems like it was fixed somewhere at 3.0 stable.
