### ISSUE TITLE
Instantiating custom class extending another custom class fails

### ISSUE THREAD

**Issue by henkz1** [godotengine/godot#11595]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04, gcc (Ubuntu 6.3.0-12ubuntu2, Godot master f577efd47ed2f0aa801155756e4ba5d5ea2d5f2b

**Issue description:**
Instantiating custom class inheriting another custom class fails with: ``Internal Script Error - opcode #18``

**Steps to reproduce:**
```
class ClassA:
	var x

class ClassB extends ClassA:
	var y

func _ready():
	ClassB.new()

```
@hpvb https://github.com/godotengine/godot/pull/11518

**Comment by scayze** [comment]
can confirm. Also happens when inheriting a script:
ie `extends "res://Entities/Entity.gd"`
