### ISSUE TITLE
Gizmos can't be seen above shader outputting colors > 1

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11593]
Godot 3.0 master
Windows 10 64 bits nVidia 940M

I was fiddling with shaders and noted that in a particular case, gizmos are not visible.
For example here, I get a blue mesh in which gizmos fade completely:
*=> This is because that blue is > 1*
![image](https://user-images.githubusercontent.com/1311555/30837018-37562c44-a262-11e7-807a-f9cde936e7b4.png)

While if I output just the normal blue with different code, gizmos appear on top:
![image](https://user-images.githubusercontent.com/1311555/30837032-4eaef560-a262-11e7-9739-ec3e78bda6ef.png)

**Comment by Calinou** [comment]
@Zylann Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Zylann** [comment]
No longer happens with that specific test, however my point that gizmos must be drawn with a technique making them usable *at all times* still stands:

![image](https://user-images.githubusercontent.com/1311555/83973311-6e4cff00-a8dd-11ea-8aee-2d8c9e953d19.png)

**Comment by Zylann** [comment]
I think https://github.com/godotengine/godot/issues/16154 explains it better

**Comment by Calinou** [comment]
Thanks for replying :slightly_smiling_face: I'll close this in favor of #16154 then.

**Comment by Zylann** [comment]
Today I just got again a variant of this
![image](https://user-images.githubusercontent.com/1311555/116474911-04c93c80-a871-11eb-8a4e-05a93b47ba66.png)
