### ISSUE TITLE
Can't use `node is load(script_path)` construct, worked in 2.1 with `extends`

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#11596]
This is valid in Godot 2.1

    var a = get_node("child")
    if a and a extends load("class1.gd"):
        print("hi")

The same cannot currently be done in Godot 3.0. You get end-of-statement errors where it is expecting a colon or (if assigned to a variable) expecting the end of the statement.

**Comment by willnationsdev** [comment]
Found out you can do it with the following:

    var a = $child
    if a and a.get_script() == load("lass1.gd"):
        print("hi")

**Comment by willnationsdev** [comment]
Rather than closing this outright, I would like to receive verification that this is a correction on 3.0 and not a bug that needs fixing.

**Comment by Zireael07** [comment]
I believe "a extends blah.gd" is now "a is blah.gd" in 3.0.

**Comment by akien-mga** [comment]
Indeed, the new syntax is `a is load("class1.gd")`.

**Comment by akien-mga** [comment]
Well, checking reddit I found out that there's more to it that meet the eye: https://www.reddit.com/r/godot/comments/72grky/godot_30_how_to_test_whether_node_extends_script/

Please *always* include all relevant debugging information in issues, here the most important bit was missing: @willnationsdev is already aware that the new syntax is `is`, but it apparently doesn't work with `load(script)`.

**Comment by willnationsdev** [comment]
@akien-mga lol, I actually was NOT aware the new syntax was "is" at the time (that's convenient though). I just knew that `is` used to be used only for in-engine type evaluation and `extends` used to be for script evaluation. Good to know the interface has been simplified.

**Comment by akien-mga** [comment]
> I just knew that is used to be used only for in-engine type evaluation and extends used to be for script evaluation.

No, it has always be `extends` for everything in 2.1, and `is` for everything in 3.0. There is no difference between checking against a built-in type or a custom class/script - or at least there should not be any, which is why this seems to be a bug.

**Comment by Hinsbart** [comment]
`a is load("some_script.gd")` works fine for me (f5201d44a).

Minimal test project:
[11596.zip](https://github.com/godotengine/godot/files/1334690/11596.zip)

**Comment by kubecz3k** [comment]
Compiled 78423320d78235a5b2fde05e7816f79de729f317, on my project it's crashing in line:
`a is preload("b.gd")`, with error code `opcode #25 (report please)`

**Comment by willnationsdev** [comment]
In a project with only one script and two nodes having the same script attached...

![loadfailurescriptgodot](https://user-images.githubusercontent.com/16217563/30972541-731d6d80-a430-11e7-96ed-fee348d694c6.PNG)

**Comment by Sslaxx** [comment]
If `if child is preload ("a.gd")` isn't supposed to work, then it'd be nice if it consistently gave an error. Having issues viz #11643 at the moment. It's giving an Internal Script Error when it sounds like it should be giving an error (using a line `if (!ring_taken && (body is preload ("res://Scripts/player.gd"))):`). Possibly the same error as the usage given above?

**Comment by willnationsdev** [comment]
Oh, I left out something important (again! whoops). My particular use case is...

Parent node with Base.gd
Child node with some Derived.gd
Parent node does the check for

    const Base = preload("Base.gd") # this fails in the parent
    const Base = get_script() # this works in the parent, but would be incorrect in the child's evaluation of ITS children
    for child in get_children():
        if child is Base:
            pass # do something

If I used `get_script()` is suggested, then derived children executing the same operation would only trigger if their children were the derived type, not the base type. At least, I think so. That's why I would need the ability to preload("Base.gd").

**Comment by reduz** [comment]
i don't understand if this is fixed or not

**Comment by willnationsdev** [comment]
No it is not. I have just re-tested this in a fresh pull / compilation.

    # base.gd
    # Goal: to create a constant that references the base type's script INSIDE the base class
    # Attempt 1: preloading a constant
    const Base = preload("base.gd") # error, Can't preload itself (use 'get_script()').
    # Attempt 2: get_script()-ing a constant
    const Base = get_script() # error on the following line, Expected constant expression
    # Attempt 3: get_script()-ing a var
    var Base = get_script() # Works! but now if a derived class references it, it will return the derived script rather than the base type's script. Not what we want.
    # Attempt 4: preloading a var
    var Base = preload("base.gd") # same problem as with const. Expected.
    # Attempt 5: loading a var
    var Base = load("base.gd") # this is the only version that ACTUALLY does what we want. It compiles, it works, and it allows derived types to access the base.gd script simply by referencing their Base property.

It would be preferable if this could be handled with a const and if preloading the same script were permitted.

**Comment by willnationsdev** [comment]
@reduz

**Comment by Sslaxx** [comment]
If this isn't fixed, why did you close this?

**Comment by Zireael07** [comment]
@Sslaxx he opened a separate issue about his latest comments

**Comment by Sslaxx** [comment]
#12719 I take it?

**Comment by Zireael07** [comment]
Yeah, that's the one.
