### ISSUE TITLE
Input.warp_mouse_pos moves the mouse when the game window doesn't have focus

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#11608]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0, Windows 10

**Issue description:**

Alt-tabbing from the game did not allow me to move my cursor freely.

**Steps to reproduce:**
Input.warp_mouse_pos(Vector2()) in any script and alt tab, try to move mouse.

**Comment by bojidar-bg** [comment]
Assuming platform-specific, tagging as platform:windows using information from #10839.

**Comment by Boothand** [comment]
My bad, forgot to specify this was on Windows 10. Haven't tested on windows 7

**Comment by Zylann** [comment]
I noticed this as well, when I start the game but focus something else while it is loading, the game starts in background but my cursor gets trapped into the area virtually occupied by the window.

**Comment by JuKilg** [comment]
This bug is not platform specific. I tested it on MAC_OS (10.12.6) with this line of code in process:
Input.warp_mouse_pos(size / 2)

where size is the size of the viewport. 

the cursor is repeatedly warped back to the position in the middle of the game window, even if It looses focus.

**Comment by AnchoDotto** [comment]
I just got this working by capturing the focus in and focus out of the application.  Beware that it's not thoroughly tested.

```
var hasFocus = false

func _ready():
	hasFocus = true

func _notification(what):
	if (what == MainLoop.NOTIFICATION_WM_FOCUS_IN):
		hasFocus = true
	if (what == MainLoop.NOTIFICATION_WM_FOCUS_OUT):
		hasFocus = false

func _process(delta):
	if (hasFocus):
		Input.warp_mouse_position(newPosition)
```

I hope this helps.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
