### ISSUE TITLE
$1500 offers a reward for increasing the performance of scripte in Godot and can reach the standard of normal game production

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#11609]
$1500 offers a reward for increasing the performance of scripte in Godot and can reach the standard of normal game production.

js v8?
c# ?
luajit ?

**Comment by reduz** [comment]
Nice,. so you will donate $1500 to the project once Godot 3.0 is out? I take your word for it :)

**Comment by cjmxp** [comment]
godot 我非常喜欢也是一直坚持的原因,可是我用了太多时间在godot的问题上,而不是在我的游戏上,目前最大的问题GDScript性能,导致无法正常开发一个游戏产品.我并不是诋毁GDScript,我用了3天时间去找性能瓶颈. 如果这个问题可以得到解决$1500并不算多,我很乐意捐献

The reason Godot I love is always insist, but I spent too much time in Godot, but not in my game, the biggest problem GDScript performance, lead to the normal development of a game. I'm not discredit GDScript, I spent 3 days to find the performance bottleneck if. This problem can be solved in $1500 is not too much, I am willing to donate

**Comment by vurpo** [comment]
The upcoming Godot 3.0 has support for more programming languages and runtimes alongside GDScript.

**Comment by cjmxp** [comment]
@reduz Is it possible to give priority to solving GDScript problems or to increase the performance of better Script bindings, at least so that we can use gdoot to do our own games?

**Comment by cjmxp** [comment]
@reduz Please open the Alipay https://www.alipay.com/ may get more donations

**Comment by cjmxp** [comment]
@vurpo 
https://github.com/neikeq/GodotSharp/issues/48
C# is cumbersome and poorly compiled

**Comment by groud** [comment]
As we already told you, GDScript is not about performances. GDscript is easy to use, but not provides high performances, and will never do. If you need performances, use GDnative.

That being said, if you want to donate, use the patreon page. You can vote for the features you would want to be added.

**Comment by reduz** [comment]
@cjmxp We have been trying to answer you this for days, but it seems translator is not working for you. 

If anyone who understands chinese is reading this, please explain cjmxp that:

For 3.0: 
1) GDScript will be faster (but not by a lot). Improving it further is planned, but will wait after 3.0
2) You will be able to use C++ without recompiling Godot and for all platforms
3) You will be able to use C#

Also, I suggested to use Area2D to detect clicks more efficiently for your specific use case.

**Comment by cjmxp** [comment]
Area2D is not for my project. The boundaries of Area2D are static,Hope 3 can release soon..

**Comment by Zireael07** [comment]
Summoning @Geequlim who is Chinese as far as I know

**Comment by cjmxp** [comment]
@Zireael07  Yes, I am Chinese, and there are many game developers like me who like Godot but are unable to invest in it

**Comment by Zylann** [comment]
I think I read the original issue was that GDScript is too slow to get which control is under the mouse, among 200 of them.
I profiled *1000* rectangle intersections in pure GDScript and was barely able to reach 1ms of elapsed time. This is relatively big, but still 1/16 of a frame, and I'm talking about 5 times more items, using pure GDScript, in 2.1.3.
So I don't know how 200 controls get that slow, but finding which is under the mouse isn't the problem even without Area2D^^

**Comment by Noshyaar** [comment]
Related: #11578

**Comment by akien-mga** [comment]
Without seeing the code that causes @cjmxp performance issues, talking about GDScript's "performance" is pointless and a waste of time.

For all we know, @cjmxp's code is bad and the bottlenecks are in his logic (@Zylann above shows that complex operations can be fast in GDScript when done right).

Finally, if you really want a high performance scripting language for your logic, just make a C++ module and be done with it. That will cost you far less than $1,500, and should even take less time than the discussions of the past 2 days have wasted.

**Comment by akien-mga** [comment]
And reminder: we have a **mandatory** (which means, **you have to follow it**) issue template:
```
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**


**Issue description:**


**Steps to reproduce:**


**Link to minimal example project:**
```

Next time that you open issues without respecting the template, I'll close and lock them. It's fine to have difficulties expressing yourself in English, but it's not OK to waste our contributor's time with complains which lack any kind of technical information on what the issue is, how to reproduce it, what's the expected behaviour...

**Comment by hpvb** [comment]
Also for the record, I've been spending a lot of time profiling various gdscript use cases and trying to improve their performance. In 3.0 pure arithmetic is about on par with Python 3 now. 

If you want me to spend time on your use case please either:
* create a small project that only shows what's slow for you now
* Post your entire current project on github
* send me your project privately and I promise I won't share it

But a generic 'make it faster' really is not enough information for me to work on your issue.

Thanks!

**Comment by cjmxp** [comment]
@hpvb 
OK, I'll make demo

**Comment by hpvb** [comment]
Thanks! Looking forwards to it.

**Comment by cjmxp** [comment]
I'm sorry I re wrote the demo did not show great differences between GD and c++ in 500 NPC, I found a print in my project ("FTP") no longer appear to reduce the problem of the deletion of the print function, very sorry....

**Comment by hpvb** [comment]
No problem! I'm just glad that your problem is solved. If you have another problem like this you know what to do now! Happy godotting.
