### ISSUE TITLE
Add mouse delta?

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#11605]
There is no way that I'm aware of that you can get the mouse delta, for moving things according to mouse motion. Using current_mouse_pos - last_mouse_pos is problematic once the mouse is captured or hits the screen edges. This is how I had to solve it, which is a bit weird: https://www.reddit.com/r/godot/comments/72j6vu/getting_mouse_delta/?st=j81hx23v&sh=fbffabee

Example:
global_position.x += Input.get_mouse_delta().x

**Comment by toger5** [comment]
you cannot ask for the mouse delta in _process. That would lead to confusion how it behaves when called multiple times per process iteration: should it keep the value or should it return the delate since it was called last time...

But there is The inputEvent class.

an example:
``` gdscript

func _input(event):
	if event is InputEventMouseMotion:
		position += event.relative

```

**Comment by Boothand** [comment]
Marvelous, thanks!
