### ISSUE TITLE
Selecting a Tilemap node and then creating a new scene causes editor to crash

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#11604]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7
Godot 3.0
Geforce GTX 760

**Issue description:**
When a tilemap is currently selected in the scene tree, attempting to create a new scene, either from the menu or by double clicking a blank area in the scene tabs section, causes the editor to crash without errors.

**Steps to reproduce:**
Download and load attached project
Select the tilemap node
Try to create a new blank scene, editor should crash

**Link to minimal example project:**
[tilemap_bug.zip](https://github.com/godotengine/godot/files/1332796/tilemap_bug.zip)

**Comment by marcelofg55** [comment]
Just tested this with latest master, didn't crash for me.

**Comment by sketchyfun** [comment]
I'll update and give it another try tonight then

**Comment by akien-mga** [comment]
How did it go? :)

**Comment by sketchyfun** [comment]
Sorry, completely forgot to actually test it again, I've made a note on my phone this time :D

**Comment by sketchyfun** [comment]
Doesn't seem to crash now :+1:
