### ISSUE TITLE
improvement suggestions: treeItem should behave the same in editor

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#11601]
This is a sub-Issue from #9931 to discussion point 5 as proposed

![tree_points](https://user-images.githubusercontent.com/10463138/28691921-db18b2e8-731e-11e7-9467-ccb6c05cdbce.gif)

suggestion: clicking on treeItem with ![image](https://user-images.githubusercontent.com/10463138/30847634-88f1849c-a29c-11e7-8dac-801280538181.png) should everywhere fold/unfold

**Comment by toger5** [comment]
@puppetmaster- so ONLY pressing the arrow should fold unfold? and pressing the name label has no folding effect. (only activates that item, for example in settings it shows the content?)

**Comment by toger5** [comment]
If you mean ONLY the arrow should fold/unfold that would be to cumbersome in the inspector...

I think this is more a discussion, if it is a good idea, that the settings tree can have settings in the section root. (I'm referring to: `Interface`, `File System`, `Text Editor` ...)
If we remove the settings from the sections, and only have them in items that have no children this would be solved. than we also could color the sections the same way they are coloured in `Input Map` 
tab of the project settings.

We could just put them in other sections.

I also just noticed, that interface is the only section that has properties in it.
I created a visualisation what I'm thinking of:
<img width="1157" alt="screen shot 2017-09-26 at 10 51 28 bearbeitet" src="https://user-images.githubusercontent.com/16718859/30852305-a147c81c-a2ab-11e7-924f-45a5742194a3.png">

for the three items marked with ? I don't know where to put them..

**Comment by puppetmaster-** [comment]
@toger5 
> so ONLY pressing the arrow should fold unfold?

No, you misunderstood.
Clicking on whole sections should fold unfold. In general section should not have settings.
In the animated gif the section **Filesystem** behave correctly.

> And since it is the only tree item which behaved weirdly it would solve the issue I think.

Don't forget the sections in Input Map. They only fold unfold when clicking on the arrow.

I hope is it now more understandable and when you change it please test also the search if the result look and behave correctly.

**Comment by toger5** [comment]
@puppetmaster- yea I misunderstood the last line of your post.
> suggestion: clicking on treeItem **with** ![image](https://user-images.githubusercontent.com/10463138/30847634-88f1849c-a29c-11e7-8dac-801280538181.png) should everywhere fold/unfold
Thank you for clarification!

> Don't forget the sections in Input Map
And I also didn't see that you were clicking on input map tabs.
So they definitely have to get fixed. there is no reason why they should not collapse when pressing on the item itself!!

Those two things I got wrong aside... What do you guys think about moving the settings items in `Interface` to other/new categories?

and where would we than put the 3 remaining ones?

**Comment by puppetmaster-** [comment]
What about
changing **Filesystem --> On Save** to **Filesystem --> Save**
and then put "Save Each Scene On Quit" there?

**Comment by toger5** [comment]
@puppetmaster- I like that.
quit conformation can go into global to I think?
So only `separate distraction Mode` left.
I would put it into `Interface/distraction-free/separate_distraction_mode` adds another section just for that but that is the easiest to find I think...

**Comment by puppetmaster-** [comment]
I'm OK with you suggestion.

Anyway better than in Eclipse Editor 😄 
![image](https://user-images.githubusercontent.com/10463138/30859110-91dc0dcc-a2c2-11e7-9f0c-9215e6b989cc.png)

**Comment by reduz** [comment]
Keep in mind default actiona cant be renamed, but custom ones cant..  so
clicking on custom action will open the rename dialog

**Comment by djrm** [comment]
@toger5 why dont you put them in a new section called "other"

**Comment by toger5** [comment]
@djrm that is also a good idea...
For the ones I coloured it seemed there were already good/fitting sections available.
But the 3 uncoloured ones would fit into a `other` section (or `general`).

**Comment by bojidar-bg** [comment]
What is the status of this issue?

**Comment by puppetmaster-** [comment]
I will close this issue, it is already very old and if there is still a demand I will apply for it again at the new dedicated Godot Improvement Proposals (GIP) (godotengine/godot-proposals) issue tracker.
