### ISSUE TITLE
Edited shaders don't always update

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11613]
Godot 3.0 master
Windows 10 64 bits nVidia 940M

When editing shaders, I noticed that very often, when I hit Ctrl+S after modifying a shader, nothing happens as if I didn't change it. In these cases I almost always try to write an extra ";", then delete it and re-save with Ctrl+S... and tadaaa, the shader updates.
Did anyone experienced this?

PS: similarly, I see the script editor sometimes gets stuck showing an error with a red highlight even though I corrected the error. Same thing, when I write a character then delete it and re-save to kinda "kick the machine", it updates and the lingering highlight goes away. Would it be the same issue? If not I could open another (https://github.com/godotengine/godot/issues/11616)

**Comment by Corruptinator** [comment]
I noticed this as well. At certain parts of the script I am forced to retype something that is the same or similar to make the shader do something.

**Comment by eon-s** [comment]
I have seen this recently when testing particles shaders, I don't remember being this way (kind of laggy) a couple of months ago.

**Comment by reduz** [comment]
This logic shouldn't be too difficult. Relevant code is in:
https://github.com/godotengine/godot/blob/master/editor/plugins/shader_editor_plugin.cpp

Basically after a few seconds of not inputting text, the shader is recompiled, tested and updated. For some reason this may not be happening, so checking these functions should be easy.

**Comment by ianb96** [comment]
I wasn't able to replicate this. I'm on 045bf2320
From what I can tell, Ctrl+S doesn't do anything in the shader editor, it just saves the scene. The shader will update by itself in a couple of seconds.

**Comment by akien-mga** [comment]
Closing as fixed as per @ianb96's comment. Please comment if you can still reproduce this issue.
