### ISSUE TITLE
Errors in the script editor don't go away

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#11616]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 - Godot 3.0 from a day ago.

**Issue description:**
Make an error somewhere and then fix the error. The line highlight and the error text will stay and not go away until another error happens.

![](https://i.imgur.com/j56VrNI.png)

![](https://i.imgur.com/xQC6y7p.png)

**Comment by Zylann** [comment]
Did you try writing non-changes, like writing a `#` and then saving to see if it goes away?

**Comment by CowThing** [comment]
Yeah after typing some other code the error will go away. Just not when removing or adding new lines.

I think the problem is with deleting. When deleting characters, errors will not show up even if there is an error. For example if you have this in the code:
```GDScript
array.append(test)
```
There wont be an error, but if you delete the end parenthesis, it will still show no error, even though there is one.
The errors only start showing up as you type, not as you delete.

**Comment by mhilbrunner** [comment]
At first glance, validation seems to be triggered in `_text_changed_idle_timeout`, which is called by the `idle` timer, which is started in `:_text_changed()` but only on `text_editor->is_insert_text_operation()`, which probably does match a delete:

https://github.com/godotengine/godot/blob/4f39ce32b9195405f934445b20059e86632b47f9/editor/code_editor.cpp#L1024-L1030
