### ISSUE TITLE
Spatial Editor: Camera Y rotation unbounded - causes unnecessary spinning when switching to top/bottom view

### ISSUE THREAD

**Issue by Nappael** [godotengine/godot#11619]
Using the latest version I have on Windows ( 3.0 Alpha, build from a couple of days ago, build from earlier today had compilation issues but as far as I can tell it's not been changed yet)

**Issue description:**
In editor/plugins/spatial_editor_plugin.cpp, the cursor.x_rot has an enforced bound of Pi and -Pi, but y_rot is allowed to take any value (so it can orbit properly).

As far as I can tell though, no attempt is then made to keep the value between Pi and -Pi after the lerp to the new camera angle has been made. This causes the y_rot to take large values (unbounded). When the perspective is then changed with the top view button or by pressing 7, it then tries to lerp from this large value back down to 0, causing the whole thing to spin like crazy instead of just making the small needed movement.

I tried to make a fix but it's very late here and I figured I would post here before I sleep.

**Steps to reproduce:**
Open any 3D scene
Spin around a few times with middle mouse button + move.
Use the top view button/hit 7.

**Comment by reduz** [comment]
This has been fixed, so closing.

**Comment by akien-mga** [comment]
Hm no that's still valid.

**Comment by akien-mga** [comment]
It looks like another symptom of #11764, so closing as duplicate.
