### ISSUE TITLE
Editor display problem while switching between perspective and ortho modes

### ISSUE THREAD

**Issue by zarsystem** [godotengine/godot#11627]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Opensuse tumbleweed, Godot v3.0.alpha.custom_build

**Issue description:**
Check following video, please

**Steps to reproduce:**
1- Create a new project
2- add a node and select it
3- try to switch between ortho/perspective view modes using num 5 key shortcut

**Link to minimal example project:**
![ezgif com-resize](https://user-images.githubusercontent.com/3175411/30902096-eb15b3de-a376-11e7-9614-c534a14de5bb.gif)

**Comment by groud** [comment]
Can you try with the last master ?

**Comment by zarsystem** [comment]
I build godot just some minutes before sending that issue

**Comment by groud** [comment]
So your Godot version is not alpha but last master, I was mislead by "Godot v3.0.alpha.custom_build" :)

**Comment by akien-mga** [comment]
Well latest master is still in alpha: https://github.com/godotengine/godot/blob/master/version.py
Not to confuse with the "Alpha 1" official build 2 months ago.

**Comment by reduz** [comment]
This is now fixed.
