### ISSUE TITLE
Opening a Visualscript file opens 2 files in the editor 

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11638]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/da144fed4c49133a93b3b83cfc665352c0af351a

**Issue description:**

I don't know what happened but after opening and closing the file a couple times when I opened it two files were open the script itself and the same one but with no name:
![https://i.imgur.com/84bKdCN.gifv](https://i.imgur.com/84bKdCN.gif)

(the broken editor problem is here https://github.com/godotengine/godot/issues/11636)

**Steps to reproduce:**
I'm not really sure. I noticed that the opened script was marked with a `(*)` when opening it and when closing the editor it doesn't complain that it's not saved. There were no new modifications in that script so it shouldn't show the `(*)`.

**Comment by reduz** [comment]
I can't reproduce, would be nice if anyone can try to reproduce or confirm that this does not happen any longer

**Comment by carlosfvieira** [comment]
Can't reproduce - used b08735f20987a6188fd54c5e2dcd072dc316b413.

**Comment by mrcdk** [comment]
Yeah, I can't reproduce it either, closing this then.
