### ISSUE TITLE
Clearing TileMap "Tile Set" property also clears cells

### ISSUE THREAD

**Issue by not-surt** [godotengine/godot#1164]
Clearing "Tile Set" property in a TileMap and all of the TileMap's cell will be cleared too, so if you load a TileSet again the TileMap is now empty and all your map work is lost.

**Comment by akien-mga** [comment]
Well the tiles in your TileMap are referenced based on the TileSet, so I think it's normal that you lose the tile definitions if your remove the TileSet. On the other hand it would be nice if *changing* the TileSet (without clearing it first) would preserve tile indexes. Do you know if this works?

**Comment by akien-mga** [comment]
Changing the tileset without clearing it seems to preserve indexes, so there's not much to fix here. If you clear the tileset completely, then it doesn't make much sense for the tilemap to keep track of indexes to null tiles :)
