### ISSUE TITLE
There is no "parent folder" button in project manager browser

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11644]
Godot 3.0 master

There is no way to go to the parent folder when browsing for a folder to create a project. The only way I found is to edit the path. There should be a button like any other filesystem dialog. (the circle arrow button doesn't do this)

![image](https://user-images.githubusercontent.com/1311555/30943472-775fa50a-a3f1-11e7-983f-c07c8ec4307e.png)

**Comment by akien-mga** [comment]
Scroll up, there's `../`.

**Comment by Zylann** [comment]
Oh... well I still think there should be a button for that^^

**Comment by AlexHolly** [comment]
Something like this? 
Maybe add the "Path:" Label to the same row like the (Editor)Filedialog has?

1. :+1: 
![image](https://user-images.githubusercontent.com/4741886/31734589-73ac80dc-b43f-11e7-9a9b-dba8efa4d975.png)
2.:-1: 
![image](https://user-images.githubusercontent.com/4741886/31734440-02e13064-b43f-11e7-9eff-f6a25632a3ca.png)

**Comment by akien-mga** [comment]
This is fixed in 3.0.
