### ISSUE TITLE
Strange scrolling behaviour when using the function shortcut list in script editor

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#11648]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10, current build.

**Issue description:**

When using the functions shortcut list in the script editor, the editor is not scrolling to the correct location much of the time. It seems that as you go down the function list, the highlighted portion scrolls to the bottom of the editor. As you go up the function list the editor is scrolled correctly with the highlighted function being at the top of the script editor.

The following gif illustrates this behaviour:
![cam1](https://user-images.githubusercontent.com/7741669/30949593-b0691980-a45a-11e7-85ea-b7122ab5c024.gif)

**Steps to reproduce:**
- successively go down the functions shortcut list, and then go back up the list and note the scrolling function 

**Link to minimal example project:**

**Comment by groud** [comment]
Yes, that's a correct behaviour. The editor scrolls until finding the correct line.
So when you go down the lien appears at the bottom, and when you go up it is at the top.

That being said this behaviour could be changed, il you can find how it's done in other editors that could be interesting.

**Comment by fracteed** [comment]
I assumed this was a bug. I would have thought having it scroll so that the start of the function is the first line of the editor. Otherwise each time you have to manually scroll the editor after hitting the shortcut, which does defeat the purpose somewhat.

**Comment by groud** [comment]
That makes sense I guess :)

**Comment by bmollot** [comment]
If this functionality is added, should it be optional?

**Comment by groud** [comment]
> If this functionality is added, should it be optional?

No, we try to avoid bloating the editor settings when we can :)

**Comment by fracteed** [comment]
@Paulb23 this behaviour is broken again in Godot stable release. Would appreciate if you could take a look at this. Not sure when it broke.
