### ISSUE TITLE
transform.x, transform.basis_xform are wrong when parented

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#11651]
Godot version 3.0 alpha

**Issue description:**

If a parent object is rotated so it looks straight upwards, and you are parented to this object so you look straight upwards (but have local rotation zeroed out), transform.x and so on returns a value as if the parent had not rotated you.
So transform.x returns Vector2(1,0), even though the 'right' local axis points in another direction visually.
Expectation: transform.x is local2world Vector2(1,0), and transform.basis_xform(..) is local2world any vector.

**Steps to reproduce:**
Root: Node
Object1: Node2D     <--- give some rotation
    child: Object2: Node2D       <--- give some other rotation
         child: Object3: Node2D <-- attach script.

func _process(delta):
    global_position += transform.x

Also try:
   global_position += get_node("../").transform.x

This is also an issue for instance when shooting a bullet from a rotated gun, that gets parented to the root and gets the local2world right vector from the gun as the direction to travel.
See attached test_scene2 for an example.
[Local transforms issue 3.0.zip](https://github.com/godotengine/godot/files/1340183/Local.transforms.issue.3.0.zip)

**Link to minimal example project:**

**Comment by groud** [comment]
Not sure this is a bug or a misunderstanding of the transform usage.
The transform is always relative to it's direct parent. Also basis_xform is rarely used.

**Comment by Boothand** [comment]
Hmm, indeed. global_transform.x seems to be what I was looking for. So it makes sense that transform.x is without the parent's transformations, still a bit unexpected that there was one for local and one for global.
Not sure what would be the clearest way to teach new users this stuff. Unity users will be accustomed to transform.right as an equivalent. I'm sure having both is a little more flexible though.

**Comment by groud** [comment]
Note that you can combine transformation by multiplying them. So you can multiply the parent transform with the child one to have a Transform relative to the parent.   

Anyway you are right, this needs maybe more documentation :)

**Comment by groud** [comment]
Anyway, if your problem is solved I'll close this issue then, as it is not related to the engine. :)
If you need more help, please ask on the forum/IRC/facebook pages. ;)
