### ISSUE TITLE
Godot 3.0 RayShape does not work properly.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#11652]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Operating system Windows 7 -64bit
Build 3.0 from Master

**Issue description:**
RayShape does not work properly.
For example it is jumpy and it stucks on floor.

**Steps to reproduce:**
Add a RayShape rotated to x 90 deg in a KinematicBody

**Link to minimal example project:**
[RasyShape.zip](https://github.com/godotengine/godot/files/1340229/RasyShape.zip)

**Comment by groud** [comment]
Can you describe a little bit more what's the problem ?
I don't get what you mean by "jumpy" or "stucking on the floor". Maybe you could make a gif ?

**Comment by kakoeimon** [comment]
I mean that you can stack in collisions and that the KinematicBody always jumps in and out from the collision.
Please check the example project.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch? I checked the example project but it seems a bit outdated, it doesn't show anything meaningful when playing.

**Comment by kakoeimon** [comment]
@akien-mga Yes this is outdated. It was fixed. Sorry for not taking track of this one. I close it.
