### ISSUE TITLE
Filtering occurs when downscaling sprites though filtering is disabled

### ISSUE THREAD

**Issue by not-surt** [godotengine/godot#1165]
As discovered by Zyllan in the forums here: http://www.godotengine.org/forum/viewtopic.php?f=11&t=1331

Filtering still occurs when downscaling sprites though filtering is disabled.
In the demo project all sprites are instances from the same base sprite using the same texture, with filtering and mip maps turned off in flags and in project settings.
At 1X scale the static one looks fine but the rotating one filtering flickers on and off.
At less than 1X both are always filtered.
At greater than 1X both are never filtered as expected.
It looks like magnification filter is turned off but minification filter isn't.
Demo project: https://docs.google.com/uc?export=download&id=0B7Mva4UEh5kxWW9wcnB4Nm1zQlk
![](http://img.uninhabitant.com/filtering_bug.png)

**Comment by akien-mga** [comment]
There was a proposed fix in #1501, but in the end @reduz fixed it with 650e13f IINM.
