### ISSUE TITLE
Android crash when I try to type with my cell phone keypad.

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#11664]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
LG G3 (d855), 4f39ce3

**Issue description:**
Godot crash when I try insert anything in LineEdit component without any log.

**Comment by volzhs** [comment]
godot version?

**Comment by guilhermefelipecgs** [comment]
Master branch


Em 28 de set de 2017 16:22, "volzhs" <notifications@github.com> escreveu:

**Comment by volzhs** [comment]
then, revision number?

**Comment by guilhermefelipecgs** [comment]
4f39ce3

**Comment by Calinou** [comment]
I can reproduce this on commit https://github.com/godotengine/godot/commit/18d3ba0c50ac073a4588388a6bdc71cfee44ea1f, on a Samsung Galaxy S7 edge running Android 7.0. Selecting text works, but typing or erasing anything will cause the app to crash.

**Exemple project:** [android_lineedit_bug.zip](https://github.com/godotengine/godot/files/1370090/android_lineedit_bug.zip)

**Comment by jaggzh** [comment]
Confirmed on Nexus 5x with build from Oct 8 (commit e4dc1f93).

**Comment by volzhs** [comment]
related PR was merged.
@guilhermefelipecgs can you test it with the latest commit?

**Comment by akien-mga** [comment]
Fixed by #11775 according to the PR author; please comment so that we reopen it if you can't confirm it.
