### ISSUE TITLE
Relationship between Oren-Nayar σ and Burley roughness

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11663]
Is the current Oren-Nayar implementation a particular approximation valid for certain range of parameters? I found it deviates a lot from the original [Oren-Nayar](http://www1.cs.columbia.edu/CAVE/publications/pdfs/Oren_SIGGRAPH94.pdf), when for example the diffuse gets small partially due to the color-independent contribution to A.

Also it might be nice to add a note somewhere (in godot-docs maybe?) that roughness in Oren-Nayar is a standard deviation which can exceed 1 whereas it should be between 0 and 1 for Burley.

**Comment by tagcup** [comment]
Although I'm not sure if there are other parts of the shader (rim, maybe?) which assume that roughness is between 0 and 1. If that is the case, sigma in Oren-Burley probably needs renormalization such that [0,1] range for roughness in Oren-Nayar roughly maps to Burley [0,1].

**Comment by reduz** [comment]
Oh, roughness is always 0-1. I dont remember where did I find this
oren-nayar implementation, but it seemed like it was adapted to use
roughness.

**Comment by tagcup** [comment]
In original Oren-Nayar, σ is angular standard deviation between [0,π/2], although not all of this range makes sense physically.

Relation between σ and roughness aside, it looks like this implementation deviates, ranging from tiny to a lot, from Oren-Nayar when changing albedo, *at constant roughness*.

**Comment by tagcup** [comment]
So there are some optimizations for the \cos(\phi_l - \phi_v) term, you can evaluate it by projecting l and v onto n, but the best optimization for the sin\alpha tan\beta term is apparently to use a 2D lookup texture, assuming that you want to avoid using trigonometric function calls in the shader.

**Comment by clayjohn** [comment]
Closing as the Oren-Nayar implementation has been revised multiple times since this issue was made.
