### ISSUE TITLE
Control previous rectangle doesn't show or is mirrored while resizing

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11671]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/4f39ce32b9195405f934445b20059e86632b47f9

**Issue description:**

![https://i.imgur.com/U4baGlF.gifv](https://i.imgur.com/U4baGlF.gif)

It doesn't show if the affected properties are the margin right/bottom.
It's get drawn mirrored (and updates each change) if the affected properties are the margin top/left.

**Steps to reproduce:**
1. Add a control
2. Resize

**Comment by groud** [comment]
Definitely reproducible :)
