### ISSUE TITLE
BackBufferCopy Rect copy mode isn't transformed inside the editor's viewport

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11670]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/4f39ce32b9195405f934445b20059e86632b47f9

**Issue description:**

![https://i.imgur.com/V3oTSs7.gifv](https://i.imgur.com/V3oTSs7.gif)

I understand that BackBufferCopy works in screen space won't take any camera transform because of it but I'm reporting this because it's still an issue.

**Steps to reproduce:**
1. Create a BackBufferCopy node
2. Set it to Rect copy mode
3. Zoom in and out or move the editor's viewport

**Comment by Calinou** [comment]
@mrcdk Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by mrcdk** [comment]
Nope! Tested in 3.2.2beta4 and it seems to be fixed! Closing this issue.
