### ISSUE TITLE
proper plain-text resource format needed

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#1167]
We need a good plain-text resource format that is more readable, more friendly to version control systems, and doesn't change with every press of Ctrl+S even if nothing has been actually edited. 

Open Data Description Language (http://www.openddl.org) syntax would be ideal for this (not using their library, if licensing is an issue, just copy the format). It looks very simple and human-readable. 

Everything needs to be sorted in a reproducible manner so that files only change when something has actually been changed.

The need for a new format had been mentioned by Juan in the past, but I didn't find an open issue about it in my quick search, so I opened this one.

NOTE: I tried my hand at fixing the order that the current XML resource saver is writing out files. While I was able to get the changes to be less dramatic between saves, it still changed every time due to a few properties still not ordering correctly, and the external resources being a set means they can't easily be sorted like a list can (supposed to just sort itself, but that's not exactly happening in a predictable way). Maybe someone better at C++ than me can fix it in the meantime, but a better format would still be ideal in the long run, and much appreciated.

**Comment by rraallvv** [comment]
I've found something but I'm not sure if it's a bug or feature, it could be related to this issue too.
For instance in the demo fixed_materials, I tried modifying the material that is included in the file ***s.xml*** using Godot, then when I run the scene those modifications are not updated to the resource files.

![screen shot 2015-01-10 at 11 29 13 am](https://cloud.githubusercontent.com/assets/1840524/5692174/7fb5e5a4-98bc-11e4-9073-4995ccf2ac00.png)
 
So, what one has to do is firstly to save the material, but for that Godot asks a new name, in order to save it as a new file, but I just want the material updated in the file where it was originally loaded from, i.e. ***s.xml***

**Comment by rraallvv** [comment]
Looking closer at the way Godot works with XML files, maybe it's not a good idea to save every modification to the resource files automatically as I mentioned in the previous post, but only when the user saves the scene.
In that case while in editor mode Godot could save all the changes to a temporary file with some indicator that tells Godot that this file is temporary. Like ***~myresource.xml*** to indicate that this is the temporary file of ***myresource.xml***.
Then, when in running the scene, from the editor Godot could load the temporary files, for the user to see how the latest changes look like.
That way, the user would have the the option to undo all the changes made to ***~myresource.xml*** with some option in the UI, like ***revert changes***, and also to make the changes permanent by saving the scene, making Godot to save the changes in ***~myresource.xml*** by renaming the file or something like that.

**Comment by rraallvv** [comment]
I think, there are a few things that could be changed to make the XML-formal handling more friendly toward text based revision control systems, without the need to add support for other formats.

1) The class [ResourceFormatSaverXMLInstance](https://github.com/okamstudio/godot/blob/9ff6d55822647c87eef392147ea15641d0922d47/core/io/resource_format_xml.h#L114) could be rewritten to use the [XMLParser](https://github.com/okamstudio/godot/blob/0c3f14087cfc2ac10af62aac7cae9b12fd501b9a/core/io/xml_parser.h#L41), to remove duplicated code.

2) Then we could rewrite the XMLParser to work more like a XML DOM Tree, with support for replacing nodes or its data.

3) Also, when saving an XML file we could open the XML DOM Tree, in read/write mode, then look for those nodes that need to be updated, and replaces the nodes in place.

Could we give this a try @reduz, I’ve just skimmed through the code, but it seems doable.

**Comment by tonymtbird** [comment]
http://opengex.org/

**Comment by adolson** [comment]
OpenGEX uses OpenDDL...

**Comment by reduz** [comment]
OpenGEX is OK for import, but yeah I guess a more proper format for scenes
should be added.

**Comment by reduz** [comment]
I honestly want to get rid of the XML format alltogether and use something
easier and simpler. XML parsing is slow.

**Comment by reduz** [comment]
For DOM though you could add an extra node on top of XMLParser called
XMLDom that is fed an XMLParser to read, in order to keep the original
parser simple.

**Comment by erlend-sh** [comment]
@kimkulling from @assimp/assimp is actively developing an OpenDDL parser in C++. I hope Godot and other C++ projects will strive to maintain it together.

https://github.com/kimkulling/openddl-parser/

**Comment by kimkulling** [comment]
Asset Importer Lib supports now base static meshes with materials in OpenGEX-format.

**Comment by akien-mga** [comment]
There is ongoing work on this feature by @reduz, and I guess it's planned to be final for 2.1 (currently resources can be saved in human-readable text format, but not loaded).

**Comment by neikeq** [comment]
What's the status on this? AFAIK, the tres format that was introduced in 2.0 is working properly. Are there more changes planned for 2.1?

**Comment by akien-mga** [comment]
I think it was pretty much fixes by the addition of the tscn/tres format. Back when I wrote my above comment I guess the format was not working perfectly yet, but now it's done :)

**Comment by adolson** [comment]
Yep, I am very happy with the new format so far!
