### ISSUE TITLE
Anisotropy direction

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#11686]
Current implementation treats allow anisotropy along with x or y axis only, and furthermore treats x and y axis differently. Adding a rotation angle parameter would solve both issues.

**Comment by reduz** [comment]
This is OK, Artists prefer to do it this way because they can use flowmaps. The anisotropy direction is specified by flowmap and UV.

**Comment by tagcup** [comment]
You can't change the angle that way though, it'll be baked. I had a plan to implement this actually...

**Comment by reduz** [comment]
It is ok that it's baked, that's how it works in real life. Also you can change the angle if you modify tangent and binormal.

**Comment by tagcup** [comment]
You actually don't even need a texture for a real life example: consider an aluminum like base color, you can just add a constant value of anisotropy to it, without baking any texture. Since neither UV not anisotropy can't be rotated however, it's direction is going to be fixed.

**Comment by tagcup** [comment]
Also in real life, I see no reason you can't rotate the anisotropy direction separately from roughness, base color, normal map etc. It's independent.

**Comment by tagcup** [comment]
You can check Blender's Principled BSDF to see how it works nicely

**Comment by tagcup** [comment]
It won't be tied to normal map roughness etc when you're baking it as a texture either, BSDF anisotropy physically doesn't depend on the macroscopic geometry or the density of microfacets

**Comment by tagcup** [comment]
Also the anisotropy angle can be position depent, which is something impossible to achieve by baking current parameters

https://i.ytimg.com/vi/t4MTnpnahu0/maxresdefault.jpg

**Comment by tagcup** [comment]
To clarify, by baking current parameters, you can make it aligned with X or Y and change it's intensity at different positions, meaning you only can choose from two angles. But you can't have circular anisotropy contours as in that picture for example.

**Comment by reduz** [comment]
I understand what you want to do, but I prefer to wait until more users try
tonuse this feature to see if it's worth improving it

**Comment by tagcup** [comment]
Do you mean you're not sure anisotropy as a whole is worth having?

Surely, there's not much point in having anisotropy restricted to only X- and Y- axis but it's useful in general for aluminium, vinyl, etc and stuff with micro-scratches.

Anyway my plan was to implement "Non Axis-Aligned Stretching" from [this paper](http://jcgt.org/published/0003/02/03/paper.pdf), which is just rotating the anistropy tensor. That's the same paper we got the anisotropic GGX from BTW.

If you're saying you're not going to accept a PR for that, there isn't any point for me to implement that I guess.

**Comment by tagcup** [comment]
> I understand what you want to do,

I was just responding to your earlier comment "that's how it works in real life" which isn't the case

**Comment by reduz** [comment]
As I mentioned, all the cases you mention are very easy to implememt with a
flowmap or the right UVs, this is how it's often used in games. Im 3D DCCs
i can undertand there are more options.

Because of this, I don't want to change this for now. Let's see what
happens after more people uses the feature.

**Comment by tagcup** [comment]
>  all the cases you mention are very easy to implememt with a flowmap or the right UVs

I don't agree.
1) That comes at the cost of complicating geometry and increasing the number of vertices
2. It would require having to bake textures where you don't even one (like a constant value)
3. There are cases you can't emulate this though cartesian UV mapping (or triplanar mapping, which are the only options you have in Godot, and Godot doesn't have built-in support for flowmaps) smoothly like the radial case, where your UV resolution depends on how far you're from the origin
4. Makes it practically impossible to generate anisotropy programmatically in a shader

**Comment by tagcup** [comment]
Ah wait, there *is* flowmap support for anisotropy. Still requires a baked texture though.
