### ISSUE TITLE
AnimatedSprite distort pixels

### ISSUE THREAD

**Issue by Phenomen** [godotengine/godot#11688]
![2017-09-29_15-48-22](https://user-images.githubusercontent.com/138311/31014779-d385f810-a52d-11e7-892c-64c9f847b72a.png)

Left is Sprite and right is AnimatedSprite. Both use same source file and 1,1 scale.

**Comment by Zylann** [comment]
Are they exactly placed at integer positions?

**Comment by groud** [comment]
I think this is a duplicate but I can't find the previous issue.

**Comment by Turbito** [comment]
Similar happens for me in https://github.com/godotengine/godot/issues/11417

**Comment by groud** [comment]
> Similar happens for me in #11417

That's the one I was looking for ^^

**Comment by akien-mga** [comment]
Closing as duplicate of #11417 then.
