### ISSUE TITLE
TCP_Server has no function "listen"

### ISSUE THREAD

**Issue by jedStevens** [godotengine/godot#11683]
2.1.4 branch

**Issue description:**
Trying to use the TCP_Server class only to find out there is an error trying to access the function `listen`. It has to do with the GDNativeBase Class not having the listen function or something.

`Invalid call. Nonexistent function 'listen' in base 'GDNativeClass'.`

**Steps to reproduce:**

Try to listen using a TCP_Server, do you get a different outcome?

I know this will may not get attention because of new multiplayer stuff, but if its just a GDNative acess error, would someone be able to help me?

**Comment by karroffel** [comment]
It has nothing to do with GDNative, the naming is a little confusing. It seems like you're trying to do `TCP_Server.listen(...)`.

You probably need to instance a TCP_Server first.

```gdscript
var server = TCP_Server.new()
server.listen(...)
```

**Comment by jedStevens** [comment]
Well don't I feel dumb, fixed for me

**Comment by groud** [comment]
Closing then :)
