### ISSUE TITLE
Crash when activating/disabling CollisionShape2D in various cases

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#11695]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0, recent Calinou build from 27/09

**Issue description:**

Using move_and_slide on a KinematicBody2D in combination with disabling a CollisionShape2D and enabling another crashes when the KinematicBody2D hits the a surface.

**Steps to reproduce:**
1. Put KinematicBody2D in a scene, give it two CollisionShape2D capsule shapes.
2. Use move_and_slide to move it down towards a static collider.
3. Click a button to disable the first collider and activate the other. It crashes when there is collision.

**Link to minimal example project:**

Use button 'space' to activate/disable the colliders.
[Crash with colliders.zip](https://github.com/godotengine/godot/files/1344432/Crash.with.colliders.zip)

**Comment by Boothand** [comment]
Would be interested to know workarounds. Needed for stuff like having a smaller collision box when crouched.

**Comment by summerblind** [comment]
Can you live with using a single collider? As a workaround you might try simply set the extents of your collider to match what you want it to be on crouch, and then revert the extents once you leave the crouch state.

You can even use the animator for this to synchronize the colliders with your sprite frame by frame.

**Comment by Boothand** [comment]
Hmm, forgot how much you can animate in Godot. I didn't find a way of changing the extents in the [API](http://docs.godotengine.org/en/stable/classes/class_collisionshape2d.html), but I'll give it a try animating it!

**Comment by summerblind** [comment]
Assuming you are working with a RectangleShape2D you should be able to do the following from the script (though I do find the animator nicer to work with since its intuitive to overlay over your sprites):

myCollisionShape2D.get_shape().set_extents(my_new_extents)

https://godot.readthedocs.io/en/latest/classes/class_rectangleshape2d.html#class-rectangleshape2d

**Comment by MateusMP** [comment]
Hey! I'm trying to fix this one, I'll comment again if I find anything useful.
(Not sure if you guys have any standard on how to assign this, I'm ~~hero~~ here to help!)

**Comment by akien-mga** [comment]
Fixed by #12757.
