### ISSUE TITLE
Hovering over drop menus after clicking should open them

### ISSUE THREAD

**Issue by stephdin** [godotengine/godot#11692]
When the user is searching for an entry its cumbersome to click every time to open the drop menu.
I think it would be better if every menu opens upon hovering after one was clicked.
This behavior is seen in Godot 2.1 and 3.0

Here is a comparison with blender:
![im_color_dither_32_ezgif-1-4e9083bfdd](https://user-images.githubusercontent.com/13117706/31016318-79f2f608-a524-11e7-886f-794b9f073a14.gif)

edit: This issue could be related: #10911

**Comment by mhilbrunner** [comment]
I agree, didn't find this issue when reporting #15939. but yeah: this feels very alien. I expect this to work as shown above, and I think that that is the normal behaviour of menus on most cursor/pointer based UIs?

**Comment by keyframer** [comment]
I definitely agree, it makes it really hard to explore menus when you have to click each one.  No other window manager works this way.
