### ISSUE TITLE
Toon specular mode and Clearcoat display glitch

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#11698]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04.03 LTS
Godot 3.0 master (2c5fa0947d724c0dcb24643f692f7a9d686a5490)
Nvidia GTX 660, driver 375.66

**Issue description:**
Setting material Specular Mode to Toon and enabling Clearcoat causes a display glitch (screenshots attached). I've attached screenshots before and after Clearcoat was enabled with the Toon Specular Mode. I've also attached the console output that appeared immediately after enabling Clearcoat.

BEFORE
![screenshot-20170929-07 08 07](https://user-images.githubusercontent.com/1168026/31019953-4ea8cad8-a4e6-11e7-8838-08f29f234ef0.png)

AFTER
![screenshot-20170929-07 08 12](https://user-images.githubusercontent.com/1168026/31019956-51a93182-a4e6-11e7-8343-53028b68fa1e.png)

[toon-clearcoat-bug-log.txt](https://github.com/godotengine/godot/files/1344669/toon-clearcoat-bug-log.txt)

**Steps to reproduce:**
- Create new scene
- Add Spatial node
- Add MeshInstance
- Change Mesh property to New SphereMesh
- Add SpatialMaterial to mesh
- Change material Specular Mode to Toon
- Enable material Clearcoat

**Link to minimal example project:**
[toon-clearcoat-bug.tscn.zip](https://github.com/godotengine/godot/files/1344632/toon-clearcoat-bug.tscn.zip)

**Comment by groud** [comment]
Weird, it look a little bit like #10650
