### ISSUE TITLE
Lock/unlock and selectable/not selectable children aren't working

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11709]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/2c5fa0947d724c0dcb24643f692f7a9d686a5490

**Issue description:**

![https://i.imgur.com/svBKXTd.gifv](https://i.imgur.com/svBKXTd.gif)

**Comment by groud** [comment]
It works for control nodes but not for Node2d ones.
