### ISSUE TITLE
(2.1.4) Debug mouse-over variable value popup not working

### ISSUE THREAD

**Issue by jtaart** [godotengine/godot#11708]
Operating system: Windows 8.1 64-bit
Godot version: Godot_v2.1.4-stable_win64

**Issue description:**
When I breakpoint a script, then try to hover over a variable, the value does not popup. It still works fine for me in 2.1.3 .

I get this error which may have something to do with it:
ERROR: ScriptEditorDebugger::_notification: Condition ' cmd.get_type<> != Variant::STRING ' is true
	AT: editor\script_editor_debugger.cpp:1126

**Steps to reproduce:**
Never works in 2.1.4 for me.
(I did just have to set debug host, which got randomly set to something else to get the debugger to work again. Not sure if its connected to the issue or not)

**Comment by DualMatrix** [comment]
This works in master

**Comment by akien-mga** [comment]
Thanks, closing.
