### ISSUE TITLE
Grid color property in editor settings ignores alpha, doesn't update

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#11703]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04.03 LTS
Godot 3.0 master (2c5fa0947d724c0dcb24643f692f7a9d686a5490)
GTX 660 driver 375.66

**Issue description:**
Grid color property in editor settings doesn't allow alpha. If an alpha value is set other than 255 then the grid color widget shows ERROR.

The grid color in the 3D view does not change after changing the grid color. You have to exit the editor and restart for the change to take effect.

![screenshot-20170929-08 30 53](https://user-images.githubusercontent.com/1168026/31023587-2d32a15c-a4f1-11e7-8c0a-c2f9778c59dc.png)

Maybe related to e2861a3b7cbf92ab018b75e330b10abc42463a6e?

**Steps to reproduce:**
- Open Editor settings
- Change Grid color
- Set alpha (A) to some value other than 255

**Comment by mrcdk** [comment]
Yes, it's related to that commit, it was causing issues with other things so it had to be disabled.

The error thing will be solved once this is merged https://github.com/godotengine/godot/pull/11646

The "it doesn't update and you have to restart" may be a bug.

**Comment by Zylann** [comment]
Is there actually a way to listen for config changes? As far as I know the grid mesh or material must be updated

**Comment by djrm** [comment]
@Zylann there is a way to listen to those changes, however the grid is constructed only once, we might reconstruct the grid or the at least the colors array when such change is detected.

**Comment by djrm** [comment]
The alpha thing should be fixed now (the current grid does not support alpha).

**Comment by reduz** [comment]
Alpha on grid is not supported because it generally leads to glitches due to how alpha is treated in game engines. We tried it supporting but it just glitches when Z ordering changes, so it's gone now.
