### ISSUE TITLE
Access to normal buffer in shading language

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11714]
Currently shading language allows access to screen space depth texture. It'd be nice if we had access to the normal buffer as well.

**Comment by reduz** [comment]
it should be possible I guess, I was planning to add mid and post
processing steps with access to it eventually.

**Comment by n-pigeon** [comment]
I want this :D

**Comment by TheDriller** [comment]
Is this possible in 3.0 now or will it be in a future release?

**Comment by reduz** [comment]
in 3.1 as postprocess most likely

**Comment by leiget** [comment]
@reduz I was wondering, will the depth buffer be available in a canvas_item shader?

**Comment by reduz** [comment]
no.. will add a special postprocess shader, but delaying this to 3.1 as
need to implement layered rendering

**Comment by scayze** [comment]
Whats the status of this? are postprocess shaders still planned for 3.1?

**Comment by akien-mga** [comment]
No, all big rendering features are now planned for Godot 3.2 with the Vulkan renderer (which may end up being named 4.0 if it turns out that we need some small compatibility breakage - much less than between 2 and 3 though).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/798, as feature proposals are now tracked on the Godot proposals repository.
