### ISSUE TITLE
2.1 branch can not built

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#11711]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2.1
Mac OS

**Issue description:**

can't  build for osx and iOS now.
I can built them yesterday. after updated, it can not build now.

scons platform=osx target=release_debug
scons: Reading SConscript files ...
ImportError: No module named config:
  File "/Users/yizheng/Github/godot/SConstruct", line 364:
    import config
YIs-MacBook-Pro:godot yizheng$ scons p=iphone tools=no bits=64 target=debug arch=arm64
scons: Reading SConscript files ...
ImportError: No module named config:
  File "/Users/yizheng/Github/godot/SConstruct", line 364:
    import config
YIs-MacBook-Pro:godot yizheng$ 

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by marcelofg55** [comment]
What version of python are you using?

**Comment by alexzheng** [comment]
2.7, I can always build  it in the past.

**Comment by marcelofg55** [comment]
It's building fine for me, with latest 2.1 and python 2.7 as well:
marcelo$ python --version
Python 2.7.10
marcelo$ scons platform=osx target=release_debug
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
[  2%] Compiling ==> platform/osx/crash_handler_osx.mm
[  2%] Compiling ==> platform/osx/os_osx.mm

**Comment by alexzheng** [comment]
I tried to build it just now, it succeed now.

**Comment by groud** [comment]
Closing then :)

**Comment by alexzheng** [comment]
Get this weird error again.
