### ISSUE TITLE
ShaderMaterial VIEWPORT_SIZE causes rendering glitch

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#11710]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04.03 LTS
Godot 3.0 master (2c5fa0947d724c0dcb24643f692f7a9d686a5490)
Nvidia GTX 660 driver 375.66

**Issue description:**
Accessing VIEWPORT_SIZE in a spatial shader program causes a glitch in the rendering. Visually the glitch looks similar to https://github.com/godotengine/godot/issues/11698. I suspect they're related but I don't know if the fix for that bug also fixes this one. This is a minimal shader program that demonstrates the problem:

```
shader_type spatial;

void fragment() {
	float a = VIEWPORT_SIZE.x;
}
```

WITHOUT SHADER:
![screenshot-20170929-17 00 35](https://user-images.githubusercontent.com/1168026/31040160-ba0d2e5c-a538-11e7-8815-1c6057e41fdf.png)

WITH SHADER:
![screenshot-20170929-17 00 58](https://user-images.githubusercontent.com/1168026/31040163-c12b9fe8-a538-11e7-8238-6494485bd075.png)

**Steps to reproduce:**
- Add a shader material that uses VIEWPORT_SIZE to a mesh

**Link to minimal example project:**
[shader-viewport-size-bug.tscn.zip](https://github.com/godotengine/godot/files/1345942/shader-viewport-size-bug.tscn.zip)

**Comment by sketchyfun** [comment]
I get a huge amount of slow down when I try and use VIEWPORT_SIZE in a shader, and the console is spammed with this error:
![image](https://user-images.githubusercontent.com/10464013/31576143-ff22ffca-b0ec-11e7-9f75-6d25546d54b4.png)
(sorry it's an image, I couldn't select the text in the console)
