### ISSUE TITLE
looking_at and look_at in 3D does not rotate around only to the up-vector.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#11717]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64-bit
Godot 3.0 master-build

**Issue description:**
looking_at is a method in Transform and look_at a method in any Spatial node. 
By using up vector Vector3(0,1,0) to make the rotation around the y-axis the result is to rotate the object and in x - axis.
What was expected was to use only the y axis (the up vector)

**Steps to reproduce:**
Create a camera and move it up or down and away from the origin of the world.
Create a script in the camera and put in the _ready method this line:
`transform = transform.looking_at(Vector3(), Vector3(0,1,0))`
or this
`look_at(Vector3(), Vector3(0,1,0))`

When you run it you can see that the camera was rotated in two different axis. 
e.g. y and x

**Link to minimal example project:**

[lookin_at.zip](https://github.com/godotengine/godot/files/1346271/lookin_at.zip).

**Comment by m4nu3lf** [comment]
No, the camera should not rotate only around the up vector. The camera should point to the target with the up being the first axis of rotation, then the camera should be rotated around another axis perpendicular to both the up and the vector pointing to the target

**Comment by Zylann** [comment]
I though the up vector could be specified?

**Comment by m4nu3lf** [comment]
Yes, it can be specified, but it is not the only axis of rotation, it is the *first* axis of rotation, like when you turn around, then there is a second rotation around another axis, just like when you move your head up and down to look at an object

**Comment by tagcup** [comment]
That doesn't make any sense, look_at just calls looking_at after some checks, they do the same thing.

This is your example which also runs fine:

```gdscript
	transform = transform.looking_at(Vector3(), Vector3(0,1,0))
	print(transform)
	look_at(Vector3(), Vector3(0,1,0))
	print(transform)
```

```
1, 0, 0, 0, 0.888211, 0.459436, 0, -0.459436, 0.888211 - 0, 2.5603, 4.94973
1, 0, 0, 0, 0.888211, 0.459436, 0, -0.459436, 0.888211 - 0, 2.5603, 4.94973
```

There is no bug here

**Comment by tagcup** [comment]
Also looking_at doesn't rotate around the up vector at all. It entirely discards the old transformation and replaces it a new one. It just ensures that you'll be facing to target, and your orientation will be in a plane spanned by the up vector you provide and the vector target-source.

**Comment by tagcup** [comment]
Documentation should be improved I guess

**Comment by groud** [comment]
I close this issue by now, as it is more due to a misunderstanding of the API than an implementation issue.

**Comment by m4nu3lf** [comment]
@tagcup yes, you're right, it discards the old transform, but assuming that the old y of the object was the same of the up vector the result should be the same of what I described. I was trying to explain it simple :P

**Comment by kakoeimon** [comment]
@groud @tagcup @m4nu3lf yes it looks like I missunderstood the api cause the explanation is 

> Rotate the transform around the up vector to face the target.

@m4nu3lf explanation was fine.

It seems to me that it rotates first to the up vector and then rotates the x in local to face the target.

@tagcup I haven't said that looking_at and look_at are acting differently, but the same way.
