### ISSUE TITLE
Nodes which blend mode set to Add will show through semitransparent editor layers

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11728]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/42e2821d04a5efd434fffa090e817905d30a0c73

**Issue description:**

![https://i.imgur.com/YzeFlTR.gifv](https://i.imgur.com/YzeFlTR.gif)
![https://i.imgur.com/tg3C5nB.gifv](https://i.imgur.com/tg3C5nB.gif)

Both particles and the red sprite have their blend mode set to Add.

I don't think this is a must fix issue because that's the expected behavior of the add blend mode. The only way I can think of to fix this would be to render the preview viewport to a texture first but I'm not sure if this should be done because 99.98% of the time this issue won't be a problem. I'm still opening it to discuss if it'll be fixed and what can be done.

**Steps to reproduce:**
1. Add a sprite
2. Set the blend mode to Add
3. Open a window and move it so the sprite can be seen

**Comment by Calinou** [comment]
This is most likely fixed in `master` since modal windows are now actual windows, closing.
