### ISSUE TITLE
Feature Request: Anchor drop down updates margins

### ISSUE THREAD

**Issue by Brickcaster** [godotengine/godot#11723]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.4

**Issue description:**
Changing a node's anchor settings via the dropdown does not move the node.  This seems counter-intuitive and unsatisfying.  For example, selecting "full rect" should expand the node (setting all margins to 0) to fill its parent.

**Comment by Noshyaar** [comment]
In 2.1.x, my workaround is to use Ctrl+P shortcut.
In 3.0 there's 'Full Rect and Fit Parent' already.

**Comment by groud** [comment]
This is on my planned improvements for the 2D editor.

**Comment by groud** [comment]
Done for 3.0, but I don't think it will be backported to 2.1
