### ISSUE TITLE
Visual Scripting - no PackedScene var type

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#11736]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0master build 42e2821

I would like to add a `PackedScene` var for instancing as we do in GDScript:

    export (PackedScene) var Mob

but `PackedScene` does not appear in "Edit Variable" -> "Type" list.

**Comment by reduz** [comment]
you can drag the scene from filesystem dock to the visual script and it
becomes a PackedScene

**Comment by cbscribe** [comment]
Thanks! That was the one thing I was stuck on!
