### ISSUE TITLE
Can't use anisotropic filtering

### ISSUE THREAD

**Issue by glhrmfrts** [godotengine/godot#11731]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64-bit
Godot 3.0 alpha 1
AMD Radeon HD 7660D + HD 6670 Dual Graphics

**Issue description:**
I wanted to use anisotropic filtering for textures, because I have a really large plane in the scene, but I got this instead:
![Image](https://imgur.com/download/jpBBX0p)

And the console output says:
![Image](https://imgur.com/download/QwB1FMd)

The **Project Settings** seems to have a `filters/anisotropic_filter_level` but apparently makes no difference. I also tried to manually create a `rendering/quality/anisotropic_filter_level` but to no effect.

I know it's not my drivers because I can use anisotropic filtering when coding directly in C++ with OpenGL.

**Steps to reproduce:**
The scene layout is:
```
- Node
  - MeshInstance (with a Plane Mesh)
  - Camera
```

I then created a material for the MeshInstance with an albedo texture. The texture has `Anisotropic` and all others flag checked.

**Link to minimal example project:**
[godot3-blastoide.zip](https://github.com/godotengine/godot/files/1346767/godot3-blastoide.zip)

**Comment by marcelofg55** [comment]
I just tried with latest master and I don't get that warning and the filter seems to change okay, can you compile and test with latest master?

**Comment by glhrmfrts** [comment]
@marcelofg55 You're right, it doesn't give a warning anymore with the latest master but it's still not as good as what I get when using OpenGL directly, and setting the `anisotropic_filter_level` option still does nothing.

**Comment by reduz** [comment]
Anisotropy is set in the import settings of the texture. As far as I can see, itś working fine.

**Comment by mhilbrunner** [comment]
This can probably be closed
