### ISSUE TITLE
UI: LineEdit signal not firing issue

### ISSUE THREAD

**Issue by mastermarkus** [godotengine/godot#11744]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows10 64bit

**Issue description:**

PROBLEM: When i try to use the focus_exit() signal under "LineEdit" guielement it never seems to fire, but the focus_enter() works just fine. NB: I tried all focus modes (ALL, NONE, CLICK).

It would also be nice if there were 2 methods like ReleaseFocus(), CaptureFocus() so we can set hotkeys when to capture focus on LineEdit guielement, im trying to make chat and and set hotkey for my chat, but there's no CaptureFocus() or equivelant method.

**Steps to reproduce:**
Click on "LineEdit" ttextbox and try to click away or press enter, it never looses focus and is stuck focused forever. NB: Changing Focus Mode between "All" and "Click" didn't change a thing. 

**Link to minimal example project:**

**Comment by Noshyaar** [comment]
Version?

**Comment by mastermarkus** [comment]
Godot Engine v2.1.4.stable.officialGodot

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
