### ISSUE TITLE
Default diffuse BRDF should be Burley's

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#11740]
I think, assuming that we want who use Blender, Substance Painter etc. to get a familiar look by default using spatial material.

**Comment by n-pigeon** [comment]
I'm also with that.

**Comment by reduz** [comment]
No.. Burley BRDF is a pain for lighting due to the added light. It's good
for some objects maybe, but not environment. Unreal does not use it either.

**Comment by reduz** [comment]
I should make an example showing why burley is not good for environment so
it's clearler why..

**Comment by reduz** [comment]
Actually i take it back, I realized it should work fine due to backlight
not present due to shadow mapping anyway. I'm ok with switching lambert and
burley.

**Comment by reduz** [comment]
Nevermind, I thought my test was not breaking but it is.. hereś light passing through an object due to how Burley works... 

![image](https://user-images.githubusercontent.com/6265307/31053969-accb6dd4-a67e-11e7-9f2c-f29d19b94d3c.png)

In an ideal world it should work but, in this case, due to how shadow mapping works (culling is reversed) it fails, as object gets light anyway.

**Comment by reduz** [comment]
Here's another example of Burley not working.. as Light is added in directions it does not come from, shadow mapping breaks..

![image](https://user-images.githubusercontent.com/6265307/31054015-98227f0c-a67f-11e7-814e-eebbd48cb01d.png)

I think it probably makes sense for a path tracer (what Burley uses at Disney), as shadows dont exist, but for regular real time rendering its not that suitable. I would use it for standalone objects mostly when they dont break.

**Comment by tagcup** [comment]
Wait this can't be true... Right now, Lambert adds N.L (should be 1/pi BTW, I submitted a fix for that) to light whereas Burley adds f(L,V,N) N.L where f is a finite (between ~0 and ~2) symmetric function of f. You can interpret this as Burley just *modulates* Lambert, in a gentle way.

So when Lambert gives no or small contribution, Burley would do the same

**Comment by tagcup** [comment]
And that would hold for any BRDF function f which doesn't start diverging at grazing angles

**Comment by tagcup** [comment]
Oh wait I apparently missed that when checking the code, Burley code is missing the N.L factor, will submit a PR for that right away

**Comment by tagcup** [comment]
Submitted #11748 to fix that

**Comment by reduz** [comment]
Ok, now it makes sense to make Burley the default, please submit a PR for
this :)

**Comment by reduz** [comment]
or actually, I will just shuffle them myself, give me a bit..

**Comment by tagcup** [comment]
Oh great! In the sense that it's that just I imagine artists (who are the ones mostly likely to notice subtle differences) would typically use Blender or Substance Painter and Godot defaults would probably surprise them

**Comment by reduz** [comment]
Blender is not PBR and I think substance is probably normalized. We might
fix this by changing how lights work to lumens, though.. which is what
Unreal does.

I never fully understood the scale, but if you want to do this research, we
could do that switch.

**Comment by tagcup** [comment]
Ah yeah, I meant for people who do their PBR work in Blender using the [Principled PBR node](https://docs.blender.org/manual/de/dev/render/cycles/nodes/types/shaders/principled.html) which uses Burley BSDF although not sure about D and G functions. Also need to check Eevee in the future I guess.

I haven't gone through the light code yet, but I agree, it's better if we use proper SI units for flux (power per unit area) (which is the "energy" setting in lights?). It's just dimensional analysis so it's trivial, but I need to get familiar with the light code in scene.glsl first...

**Comment by reduz** [comment]
Godot is more similar to Unity, in the sense where 0 is black and 1 is
white, energy is just a multiplier.

This kind of makes simpler things work without having to deal with exposure.

It also makes sure rendering works in low bit depths such as 8 bits.. as
for a different scale a float buffer does not have much incidence.

For this, tonemappers generally work with a white value, so everything can
be scaled back to visible range.

**Comment by reduz** [comment]
Currently, white is 1. This needs more research before implementing

**Comment by tagcup** [comment]
I don't think there is anything to research here, I can tell you about the physical picture right away.

The power spectral density function of the light in computer PBR approximation (see the two paragraphs above Eq. (1) in [here](http://blog.selfshadow.com/publications/s2012-shading-course/hoffman/s2012_pbs_physics_math_notes.pdf) for example) is just summation of 3 delta functions at 3 colors (R, G and B, tailored for human vision) but their coefficients will be different. Photons at R, G and B have different energies, and those 3 coefficients of each delta function needs to tell you how much photons per time the light source emits.

The question is, how do you want to relate these coefficients to the "color" and "energy" settings? That is to say, what do you want the "color" and "energy" mean? Should the RGB components of color mean the number of photons per time, or the power at that channel? And should the "energy" mean the total power of the light source, of should it be a 3D vector such that you can set the power of each color?

**Comment by tagcup** [comment]
Tonemapping etc happens after physics calculations to relate the physical light to computer screen

**Comment by tagcup** [comment]
Err what I mean is if we"re going to make light sources physical, determining the physical meaning of "color" and "energy" settings of light sources wouldn't involve tonemapping at all as it's just a workaround for computer limitations and should happen after physical light calculations in PBR pipeline

**Comment by tagcup** [comment]
About the meaning of color, back to white example, it's like when you set the color to white, do you want equal number of R,G,B photons, or equal energy from R, G, B photons?

**Comment by reduz** [comment]
Oh I meant it in a more scale relative way, as wheter to use lumens or not. I still think it's not worth it and the range from 0 to 1 might still be better.

**Comment by tagcup** [comment]
Ah I see. Well, I guess we still need to set what 1 means in terms of watts or lumens, because 1 corresponds to *some* amount of power already, and we can add a hard-coded coefficient in the glsl code such that 1 corresponds to a reasonable (meaning something similar to Eevee/substance) amount of maximum power.

**Comment by reduz** [comment]
I was reading more about it. It seems the common case is to just remove the
PI division to make this more artist friendly, even incorrect.
https://seblagarde.wordpress.com/2012/01/08/pi-or-not-to-pi-in-game-lighting-equation/

By checking Eevee and Unreal, it seems that is the case too..

**Comment by reduz** [comment]
No.. actually Unreal divides by PI, nevermind.

**Comment by reduz** [comment]
Unity actually does not do division by PI

**Comment by tagcup** [comment]
Ah yes, he's just renormalizing the light such that Lambertian BRDF doesn't have a 1/pi but it doesn't make sense in general. I mean you can do the same thing with Oren-Nayar or Burley for example, but each of those will give a different renormalization, and the question becomes which renormalization is the most artist-friendly? And I think the answer is none because it'll just be an ad hoc reparametrization based on a random choice which will confuse artists when they try to use other software such as blender or substance or other game engines with the same assets.

So I think the best thing would be to stick with dimensionful physical parameters (SI, rather than inventing an engine specific unit of power) and use either watts or lumens for the power parameter of lights. This way, it'll be unambiguous.

**Comment by reduz** [comment]
The reason behind "inventing" an engine specific unit of power _is_ artist
friendliness. I guess this is why Unity goes this way too.
If light energy is "1" and color is white, you expect to see that white
color on the light, or the color you select in the picker, or the texture
you edited in Photoshop.

It has it's merit. Everything is then built around it. I am still not sure
myself which way is the best, will ask other engine developers what their
views are. I will always want to prioritize something artist friendly than
physically correct. In Unreal, for example, dealing with Lumens is kind of
a hassle as the values are in the thousands.

**Comment by reduz** [comment]
For now I restored the range to 0-1, or else existing projects will break
(and also made Burley default).

**Comment by tagcup** [comment]
OK, [0,1] then but still engine-specific units of power can lead to confusion if it's made arbitrarily. Like, choosing a unit based on "I don't like the pi factor in Lambert BRDF isn't good to me.

A good choice is probably to match 1 to a realistic situation, like a sunny day or a 100W lightbulb.
Unreal probably has a guiding document about this, listing the lumen equivalent of various situations, which probably requires an account

**Comment by reduz** [comment]
It's not a "I don't like the pi factor in Lambert BRDF", It actually solves
quite a few problems:

* It's artist friendly, just put "1" instead of the watts on a lightbulb. I
have worked with artists many times and they just dont get this well, and
just ended up putting in there what looks good to them.
* It's friendlier to mobile, where you don't have float framebuffers and
the 0-1 range is harcoded by the 8-bit framebuffer (and converting to this
unit from something else would be pretty hacky). We can make a low-specs
mobile renderer that looks decent.

As mentioned, Unity does the same and most likely due to the same reasons.
Most tools i've seen are pretty split on this issue, so it's not just a
whim. I would simply wait for now, as it's too late in the 3.0 development
process and too many things require attention..

**Comment by tagcup** [comment]
Ah no no you misunderstood what I said...

I was referring to the unit choice in that WordPress link you gave, and the way he chose it.

And yes, I'm saying OK let's keep the energy parameter between [0,1] in the UI, but let's make sure we know what 1 corresponds to by adding a constant conversion factor in tbe light shader which converts from 1 UI enegy parameter to a particular and more meaningful amoint of lumens (which could be something like a 100W bluk or a sunny day) in the unitful reflection equation we have in scene.glsl.

**Comment by tagcup** [comment]
Like let's define a unitful (in lumens) const in scene.glsl and multiply it the normalized "energy" parameter in the UI (which is dimensionless and  between 0 and 1) before we feed it to reflectance calculations etc

And we can tune that dimensionful const whenever we want.

His case would correspond to having a conversion const "pi lumens" BTW

**Comment by reduz** [comment]
This is the part where I'm still not sure. As I mentioned, Unreal uses
lumens, while Unity uses 0-1 (no lumens or anything).
I personally like lumens more because most papers use this unit, but
artists dont really get them and the 0-1 range for them is very clear,
because:  "0 is black and 1 is the color I assigned in photoshop". As I
mentioned, I would probably wait this out for 3.0 and leave as is, as
people seems to be fine with it.. then research it more (from the usability
standpoint) for later.

**Comment by tagcup** [comment]
Yeah, totally agree, and exactly for that reason, I'm saying let's keep that conversion factor as a hardcoded const in scene.glsl, hidden from artist's eyes, just for us, but let's have it there so that we exactly know what our choice in units mean and also we can tune it later based on physical considerations

**Comment by reduz** [comment]
I was asking Matias from Ogre. They also prefer the 0-1 range instead of
lumens.
I think his suggestion is the best, though, we can do the division by PI,
and then internally multiply lights by 3.14 in the renderer

**Comment by reduz** [comment]
Probably the best we can do is use the 0-1 range for LDR, and if setting a
specific value in the project settings, make godot use lumens instead for
HDR.. but this needs to be tweakeable, so we can use both modes depending
on the need.

**Comment by reduz** [comment]
but, as I mentioned, I prefer to leave implementing lumens for later, after
3.0 is out.

**Comment by tagcup** [comment]
Great!

Yeah, let's keep the UI parameter between [0,1], and add a dimensionful conversion factor from that parameter to the L_i term in the reflectance equation in scene.glsl, with the current value set to be 3.14.

With that change, I can also rename some variables in a meaningful way! (like light_amount -> diffuse_brdf_NL to mean fdiffuse times N.L)

Although let me work out the dimensionality of the factor (it's probably not 3.14 watts) so that I can add it as a comment, and maybe mention a comparison between that value and something familiar like 100W light bulb. Is the unit of length in Godot meters?

**Comment by reduz** [comment]
I just multipled the light energy for 3.14 for now.
Still, wait for the dimensionality factor as I don't think that's how it's
normally handled.
LDR has no dimensionality, It's always 0-1 and it needs to stay at that. No
watts, lumens or anything.
My plan is different, which is to be able to change a setting in the
project settings to make lighting lumen based.. This way the LDR value is
hidden and a lumen value appears when editing lights and environments. Then
all math actually happens in that scale. I think trying to handle both
things with a single use case is too hacky.

**Comment by reduz** [comment]
I might need to write a proposal as I'm afraid this is not clear enough

**Comment by tagcup** [comment]
> LDR has no dimensionality, It's always 0-1

I know, which is exactly why we need to multiply it with something in units of energy flux per solid angle before we plug it as the L_i term in the radiance equation (which is what light_compute implements), which is Eq. (1) [here](http://blog.selfshadow.com/publications/s2012-shading-course/hoffman/s2012_pbs_physics_math_notes.pdf).

> My plan is different, which is to be able to change a setting in the
project settings to make lighting lumen based.. 

> I might need to write a proposal as I'm afraid this is not clear enough

Yeah that'd be great

**Comment by tagcup** [comment]
We can close this I guess since Burley is default now
