### ISSUE TITLE
OBJ import not working due to wrong importer being used

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#11749]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7
Godot 3.0 built from master (today)

**Issue description:**
I was trying to import an OBJ into my project, but the imported version had no mesh data, and when it was selected, the import panel was displaying import options for "scene" not "OBJ"

I threw some print outs into the code to see what was happening, and it looks like when an OBJ is found without a .import file, it tries to find what importer to use based on it's extension. Since the scene importer plugin also returns .obj as an accepted file type, this is the importer that ends up being used instead of the OBJ importer. I'm guessing it's finding the scene importer and accepting it before it comes across the OBJ importer, so it might be a matter of re-ordering the list of importers. 

I commented out the following on line 4639 of editor_node.cpp:

`Ref<EditorOBJImporter> import_obj;`
`import_obj.instance();`
`import_scene->add_importer(import_obj);`

and it solved the problem for me, although I doubt this is the correct way to do it since the scene importer probably still needs to be able to handle obj stuff. I did try re-ordering the importers, but it didn't seem to make any difference, which surprised me. Still, I think commenting out the above code proves the area where the problem is occurring.

**Steps to reproduce:**
Save an OBJ file into your project folder
Once Godot has imported it, check the .import file it produced for it in the project directory
The .import file contains type="scene" instead of type="mesh" (a correctly imported OBJ import file should contain "importer="wavefront_obj")

**Link to minimal example project:**

**Comment by fracteed** [comment]
Can confirm that this is an issue. I have also been unable to import any obj files since the change to the importer. Have tried all sorts of settings on the importer, but to no avail. Have been keeping an old build around just to import obj and and saving out .mesh files.

**Comment by djrm** [comment]
since now OBJs are imported as .mesh, this might be solved.

**Comment by fracteed** [comment]
Does this fix the problem of obj's not being able to be imported as a scene?
