### ISSUE TITLE
3-D Platformer Demo: Internal Script Error - opcode #31 (report please)

### ISSUE THREAD

**Issue by gbutler69** [godotengine/godot#11750]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

- Ubuntu Linux 17.04
- Godot 3.0 - (Latest Build from Git Head Master)
- NVIDIA Corporation GK106M [GeForce GTX 765M] (rev a1)

**Issue description:**

- running the 3-D Platformer Demo from https://github.com/godotengine/godot-demo-projects.git
- When player collides with coin receive the "opcode #31" error

**Steps to reproduce:**

- git clone  https://github.com/godotengine/godot-demo-projects.git/master
- git clone latest Godot 3.0 (commit d3345121ccf12eb5f11f4200b3b4ddc92823817c)
- build Godot 3.0 (`git pull upstream master; git clean -f; scons platform=x11 --clean; git push origin master; scons platform=x11`)
- open the godot-demo-projects/3d/platformer
- run it
- play until player hits a coin
- debugger activates and displays the opcode #31 error

![screenshot from 2017-10-01 10-35-50](https://user-images.githubusercontent.com/1789892/31055879-b9ef3446-a697-11e7-8088-e63feed948e4.png)
![screenshot from 2017-10-01 10-36-16](https://user-images.githubusercontent.com/1789892/31055878-b9ee5af8-a697-11e7-802f-be465ccd4431.png)

**Comment by Noshyaar** [comment]
Should be fixed by 6c15c23. Please rebuild.

cc @hpvb

**Comment by gbutler69** [comment]
NOTE: I forgot to mention. In order to get the 3d/platformer to work at all I had to make a couple of edits to the scripts:

- follow_camer.gd : line 61 from `look_at_from_pos(pos, target, up)` to `look_at_from_position(pos, target, up)`
- player.gd : line 123 from `facing_mesh = adjust_facing(facing_mesh, target_dir, delta, 1.0/hspeed*turn_speed, up)` to `if ( hspeed*turn_speed != 0 ): facing_mesh = adjust_facing(facing_mesh, target_dir, delta, 1.0/hspeed*turn_speed, up)`

**Comment by hpvb** [comment]
the look_at_from and adjust_facing stuff wasn't affected by that error though. platformer3d needs some fixes due to recent api changes.

**Comment by gbutler69** [comment]
Yep. Looks good now. Opcode #31 issue is resolved. The changes I did to follow_camera.gd and player.gd *seem* to be correct. I'll see about doing a PR or filing a bug against the demo project when I have a few.
