### ISSUE TITLE
PBR hair shader

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11759]
[Karis](http://blog.selfshadow.com/publications/s2016-shading-course/karis/s2016_pbs_epic_hair.pdf) describes a real-time PBR hair shader in SIGGRAPH 2016 which we can adapt to Godot.

**Comment by toger5** [comment]
Looks really cool.
Would be amazing to have that in godot too.

**Comment by reduz** [comment]
I added anisotropy for this stuff, but that shared seems pretty cool.
I also just fixed light shaders, so it's now possible to write a custom
shader for a material, may not be necessary to add it as built-in.

**Comment by tagcup** [comment]
With anisotropy it looks like a nice shader for toon/anime style hair but their is actually physically based, with terms for R, TRT, and TT (multiple transmissions and reflections), so I really think it'd be a nice addition complimenting subsurface scattering to get a physically-correct looking humans and animals

**Comment by tagcup** [comment]
Anisotropy essentially just gives something similar to the R term for single reflection

**Comment by tagcup** [comment]
Not to mention they refer to mobile so it's probably fast enough to fit in Godot's overall choices

**Comment by reduz** [comment]
Heh "mobile" for Unreal is relative, they mostly focus on the high end
section of it.
In any case, it should be interesting, if you want to test it, to use the
new light shader feature.. I wonder how that could work and if exposes
enough for something like this..

**Comment by tagcup** [comment]
Ah didn't know that!

We should be able to add a HQ setting for it like as in ssurf code, which would turn off, let's say TRT for exampe.

Yeah I'd like to test it on mobile once I prepare the code although might take me a while I'm still trying to get an overall sense of scene.glsl while reading literature

**Comment by tagcup** [comment]
This guy (Karis) is super sloppy in slides and presentation. In N_R, I have no idea what h in attenuation function is, and it doesn't even appear on the right hand side. In the remainder, no idea what Φ(p,h), μa, p are.
His [talk](https://www.youtube.com/watch?v=zs0oYjwjNEo) is equally unhelpful because he's just basically saying "just see the slides".

I'll check references sometime in the future, hoping that he used their notation for those.

**Comment by Calinou** [comment]
I'll close this as an hair shader can be provided by a third party on the [asset library](https://godotengine.org/asset-library/). The Anisotropy property in SpatialMaterial can be helpful here.
