### ISSUE TITLE
Line2D Tile Texture mode not tiling correctly

### ISSUE THREAD

**Issue by Xgor** [godotengine/godot#11751]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
On LinuxMint 
NVIDIA CORPORATION GK104 [GeForce GTX 770]
Driver nvidia-375.66
Built from Master

**Issue description:**

I've been experimenting with Line2D and noticed that applying texture with tiling didn't tile it at all. Instead it renders the texture shown once and then it renders the left side of the line like it does with  the None Texture Mode.

![skarmbild fran 2017-10-01 16-20-45](https://user-images.githubusercontent.com/7757419/31055531-8f6b7806-a6c4-11e7-9be3-ec408d9757c7.png)

Considering that you can do a lot more with tiled textures I would love to see it fixed.

**Steps to reproduce:**
1. Create a Line2D with some points
2. Add texture to a Line2D
3. Set Texture Mode to Tiled

**Link to minimal example project:**

[Line2DProblem.zip](https://github.com/godotengine/godot/files/1347204/Line2DProblem.zip)

**Comment by mrcdk** [comment]
You need to import your texture with Repeat enabled for it to work

**Comment by Xgor** [comment]
Ah thanks. Totally missed that. I'm currently trying to write the docs in Line2D so I'll make sure to add that info.

**Comment by groud** [comment]
Ok closing then :)
