### ISSUE TITLE
Selectable Children toggle for 3D

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#11756]
**Godot version:** 3.0-alpha 99a464c

As mentioned in #11655, it would be great to have the Selectable Children toggle ported over to the 3D side. Right now you can sorta replicate this functionality in 3D by saving the branch to a scene and having it be instanced (with "Editable Children" disabled). This lets you click on any child element in the viewport to select the parent, as the Selectable Children does in 2D. It does the job, but having the toggle would be more convenient, and would make sense alongside plans to implement the Lock toggle in 3D (#4447).

**Comment by Tachekentya** [comment]
It would be nice to have the "not selectable children" button for the 3D editor. Still does not exist for the Godot_v3.1-beta8

**Comment by JFonS** [comment]
It's planned for 3.2

We are too close to release for 3.1 but I will assign this issue to me, so I don't forget it for 3.2.
