### ISSUE TITLE
Engine.is_editor_hint() non-existant when exporting project

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#11758]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0, Calinou 27/09

**Issue description:**

One of my scripts use Engine.is_editor_hint() to make a part of it only run in tool mode.
When exporting to Windows using Templates found [here](https://downloads.tuxfamily.org/godotengine/3.0/alpha1/), it says the function is non-existant.

Image: https://puu.sh/xNBHx/c4e55fef04.png

Is there a way to test if something is built?

**Comment by neikeq** [comment]
The commit, commit fd69604, that made these changes dates to Aug 13. It was not yet there when alpha1 was released.

> Is there a way to test if something is built?

You could use `Engine.has_method("is_editor_hint")`. I wouldn't do this though, this is alpha after all and you shouldn't use it for production.
