### ISSUE TITLE
Borderless maximized window ("windowed" fullscreen)

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#11762]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2.1.4

![](https://i.gyazo.com/7e0c73441ca84a87a231c9458673a1d7.png)

You can do:
`OS.set_window_maximized(true)`, and then `OS.set_borderless_window(true)` however... the windows taskbar is still on top.

Which Zylann said is legal behavior, so my suggestion is the ability to hide the taskbar, or if possible.. make godot fullscreen and render the main OS display as well.

Regular fullscreen works, but when you alt-tab out of it, it flickers black (leaving the gpu to OS). My suggestion is the ability to render both the game in fullscreen and the OS display, so when a person alt-tabs it's a seamless transition. 

Path of Exile has this [here](https://i.ytimg.com/vi/i5l97ZTM1x8/maxresdefault.jpg), see how it's windowed fullscreen, but no borders?

**Comment by Calinou** [comment]
This is supported on Linux (in fact, it's the only kind of fullscreen supported there), but not yet on Windows.

**Comment by Einlander** [comment]
Most people call it borderless fullscreens.

**Comment by marcelofg55** [comment]
This is already implemented actually on Windows and Mac, use this script:
```
OS.set_borderless_window(true)
OS.set_window_size(OS.get_screen_size())
OS.set_window_position(Vector2(0, 0))
```
I think it's just not documented.

**Comment by Dillybob92** [comment]
@marcelofg55 Thanks

i tried that already,  but when you alt-tab it still causes the black ficker from gpu to os render

when you are in windowed mode and alt-tab, it's a smooth transition no black flickering at all, that same experience should work in fullscreen borderless

**Comment by Dillybob92** [comment]
Example:

Windowed:
![](https://i.gyazo.com/68f136a94c48516a1f6061e70b6251b2.gif)

and @marcelofg55's code: 

![](https://i.gyazo.com/2851c8f4f987699d24dc05f0d6811a0c.gif)

Marcelofg55's code should act smoothly like the windowed one, but it doesn't, bcz that freeze u see in the gif = gpu render to os render, and that is what causes the black screen flicker. (can't see the black screen in gif, but it happens when you see the freeze)

**Comment by marcelofg55** [comment]
I just tested it and I noticed the black screen flicker, it's really minimal here, I think it's windows bringing back the taskbar. Do other games alt-tab without this black screen flicker? (I don't use windows much lately)

**Comment by Einlander** [comment]
On windows borderless fullscreen is basically the window ignoring that the taskbar is there. Games that are fullscreen will have this pause, some longer then others. 3d games have the biggest pause.

This might be of some help. https://gaming.stackexchange.com/questions/107028/is-there-a-difference-between-running-games-in-windowed-or-fullscreen-mode

All the answers have a good insight to this issue. On windows, fullscreen and windowed fullscreen are not even remotely the same. One draws direct to hardware, the other draws to a window controlled by the windows manager.

**Comment by Einlander** [comment]
So is it working? Has it changed at all? Does it actually behave properly in windows?

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
