### ISSUE TITLE
Freelook WASD doesn't override Animation panel hotkeys

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#11763]
**Operating system or device, Godot version**
Linux Mint 18.2 Cinnamon x64, Godot master c9a925c

**Issue description:**
When using freelook with the Animation panel open, the WASD keys will interact with it and cause the loaded animation to start/stop playback, or even play in reverse. 

**Steps to reproduce:**
1. Create/open an animation via the AnimationPlayer node
2. With the Animation panel open, navigate around using Freelook

**Comment by groud** [comment]
Maybe related ? #11556

**Comment by mhilbrunner** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by homer666** [comment]
Just tested this on 3.0.2, it has been fixed. Closing.
