### ISSUE TITLE
Leak when reference member property is part of binary operation

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#11761]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 64bit, master c9a925c

**Issue description:**

If the property `TextureRect.texture` is part of an binary operation, the `ImageTexture` instance will leak:

```
WARNING: cleanup: ObjectDB Instances still exist!
At: core/object.cpp:1858.
Leaked Instance: ImageTexture:930 - Resource Name:  Path: 
Orphan StringName: ImageTexture
StringName: 1 unclaimed string names at exit.
```

**Steps to reproduce:**

Commenting both asserts fixes it:

```
extends TextureRect

func _ready():
    var imageTexture = ImageTexture.new()
    var dynImage = Image.new()

    dynImage.create(256,256,false,Image.FORMAT_RGB8)
    dynImage.fill(Color(1,0,0,1))

    imageTexture.create_from_image(dynImage)
    self.texture = imageTexture
    
    # if self.texture is part of a binary operation, the leak happens
    assert(self.texture != null)
    #assert(self.texture == imageTexture)
```

**Comment by reduz** [comment]
@neikeq is this still an issue?

**Comment by mhilbrunner** [comment]
Can't reproduce it with above code on current master. Close and reopen if someone can still reproduce it?

**Comment by neikeq** [comment]
I can't reproduce this on current master either. I wonder what fixed it...
