### ISSUE TITLE
Opengl Context 3.3 creation failed in godot 3.0

### ISSUE THREAD

**Issue by msmshazan** [godotengine/godot#11779]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 , Gotdot 3.0 ,Intel HD graphics.

**Issue description:**

Opengl Context 3.3 creation failed. 
![image](https://user-images.githubusercontent.com/20334207/31076321-363ce624-a797-11e7-9db9-e8b3849f2f78.png)
**Steps to reproduce:**
Run godot binary compiled from source.

**Link to minimal example project:**

**Comment by reduz** [comment]
I don't think this is a bug.. it seems it's just not supported by your
hardware..

**Comment by msmshazan** [comment]
So that mean I can't use godot 3.0 . 😢

**Comment by msmshazan** [comment]
@reduz So what are options available for me now?

**Comment by reduz** [comment]
It may work on Linux for your GPU, depending on your model..

**Comment by reduz** [comment]
3.1 will support GLES2 again, so that version will work

**Comment by reduz** [comment]
I guess keep using 2.1 until 3.1 is out

**Comment by msmshazan** [comment]
Anyways Thanks

**Comment by reduz** [comment]
you are welcome!

**Comment by msmshazan** [comment]
@reduz But still is there a way by maybe editing the source code to use legacy opengl ? I see  a flag called LEGACYGL_ENABLED .So i was just wondering?

**Comment by reduz** [comment]
no, there is no way. The new renderer is written for OpenGL 3.3. The old
renderer is no longer compatible and cant be enabled.
A new OpenGL 2.1 / GLES2 renderer will be written for Godot 3.1
