### ISSUE TITLE
Linux 32bit client and export behaves strangely

### ISSUE THREAD

**Issue by DarkRoastStudio** [godotengine/godot#11787]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Mint KDE 32 and 64bit; Godot version 2.1.4 Stable

**Issue description:**
Running the Linux 32bit client gets strange results from physics bodies. For example if you apply the transform() function, the gravity no longer effects the body. As well as generally less accurate collisions.

**Steps to reproduce:**
Download the Linux 32bit Godot client onto a system running Linux Mint KDE 64 or 32bit OS. Setup a test project with a static body and rigid body, apply a script to the rigid body that calls its transform() function (no variables need to be passed in), and you should see the results.

**Link to minimal example project:**

**Comment by akien-mga** [comment]
Indeed, that's unfortunate but normal behaviour in 2.1, collision objects can be translated and rotated but should not be scaled.

Luckily, it's finally fixed in the master branch as collision objects and collision shapes were rewritten to handle scaling.
