### ISSUE TITLE
PNG transparent colour is ignored/discarded

### ISSUE THREAD

**Issue by not-surt** [godotengine/godot#1178]
When opening a PNG image file in the editor it is rendered without transparency of the chroma key colour and the rewritten file has no transparency (chroma key or alpha).
Possibly related to #494.

**Comment by Spooner** [comment]
I believe that is the default behaviour for loading images directly from PNG files, so the you don't bleed rgb values when filtering resized sprites. You can disable this behaviour if you manually Import the file in the editor.

**Comment by reduz** [comment]
chroma key is not supported in godot, use alpha channel

**Comment by not-surt** [comment]
I don't expect Godot to use key transparency internally but converting it to alpha on loading (and not overwriting the original file) would be much more user friendly.

**Comment by reduz** [comment]
convert on load is pretty slow, does PNG even support this?

**Comment by not-surt** [comment]
Well Godot is already converting indexed to RGBA, just not setting the alpha meaningfully, so I don't see why it should be significantly slower if it were to set the alpha at the same time.

Apparently libpng has high-level functions png_set_palette_to_rgb and png_set_tRNS_to_alpha (http://www.libpng.org/pub/png/libpng-1.2.5-manual.html#section-3.7) to do just this.

**Comment by akien-mga** [comment]
Archiving as per above comment.

**Comment by reduz** [comment]
this was closed via #3097
