### ISSUE TITLE
Godot3: high level networking. set_network_slave() missing?

### ISSUE THREAD

**Issue by satyries** [godotengine/godot#11784]
Not sure if this qualify as bug, but it seems like I am unable to find any reference about.

In the previous unofficial builds here: http://fixnum.org/godot/ there were Godot version with high level network functionality which was removed (latest build working is the "January 2, 2017 at 16:07" one).
Those functionalities are now under development in Godot 3, and few things are chanced (and probably it will be).
In the unofficial builds to set a node master or slave you'll had to use
node.set_network_mode(NETWORK_MODE_MASTER) or node.set_network_mode(NETWORK_MODE_SLAVE). Now it seems to me that this function is being replaced by the command **set_network_master( int id, bool recursive=true )**
But I wasn't able to find a counter-part to set a node as slave (ie: something like set_network_slave); now I was wondering: it is missing or there's new paradigm on how slave nodes are set?

**Comment by reduz** [comment]
It is considered to be slave if master id is not peer id, so calling this
function is not needed. By default the master is the server (id 1 i think).

**Comment by satyries** [comment]
Great, I am using networking/simple_multiplayer demo and things are now finally get lot more sense to me; was afraid thing could be already unmanageable so fast.
