### ISSUE TITLE
Game for android load all default theme textures

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#11795]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 build 6dc1025e6313d711939269e1578fff5ffc0cd30a

**Issue description:**
Game for android load all standard theme textures (around 140) even if they are not used
![image](https://user-images.githubusercontent.com/3992195/31110742-5d73e6ba-a833-11e7-9dc5-41590fe344ea.png)

**Link to minimal example project:**
Empty project with one `Label`

**Comment by toger5** [comment]
This might bw hard to change. There is only a theme recource which can be loaded by a control. And generating the theme puts everything... (the whole theme) also the textures are not stored in individual files but are part of the godot binary.
This maybe could be volved by giving the theme stylebox only a reference to the texture file. Than the texture could be loaded on first access.
Or each theme has optional texture objects for each texture used. They only load when accessed for the first time, and than buffer te texture. Letting the theme handle it would have the advantage that multiple styleboxes using the same texture still would only load it once.

**Comment by djrm** [comment]
I think the correct way to solve this (if theme resources are an issue) is to create an empty theme and simply add styling for a button.

**Comment by kosz78** [comment]
@djrm  thank you, it works
