### ISSUE TITLE
UI performance is too slow on Android

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#11797]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 build 6dc1025

**Issue description:**
When open UI, performance droped to 10 fps from 30

D3 scene with minimum UI elements:
![image](https://user-images.githubusercontent.com/3992195/31112162-4dcfd35a-a83c-11e7-8f68-11c3156d33a5.png)

Complex UI window:
![image](https://user-images.githubusercontent.com/3992195/31112126-29b8e560-a83c-11e7-891f-54849608ea89.png)

I dont use UI atlas in game

**Comment by toger5** [comment]
What styleboxes are u using?

**Comment by kosz78** [comment]
@toger5 mostly not defined, in some panel it specified as custom StyleBoxTexture

**Comment by kosz78** [comment]
BTW, `glDrawArrays` are performed for each symbol of rendered text, may be here can be some points for optimization

**Comment by reduz** [comment]
guess it really depends on how the UI looks and the device

On Tue, Oct 3, 2017 at 8:17 AM, Konstantin Zaitcev <notifications@github.com

**Comment by toger5** [comment]
I only can say for style box flat that it does an immediate draw call (sending a vertex array) for each draw iteration. + for each sb...
I m sure that this is not the most performant approach but it seems okay enough for the editor atm...
Sb texture also does immediate draw calls afak but it uses only 16verts i think?

**Comment by reduz** [comment]
I don't think that's the problem, Godot 2 uses the same approach (and in
fact it uses a lot more draw calls) and it's not slow.
If you are using a lot of styleboxes, I think the problem may have to do
with how the fragment shaders work in 3.0, which is not that
friendly to low end mobile devices.

Most likely, this will be fixed in 3.1 when the GLES2 renderer is
reintroduced..

On Tue, Oct 3, 2017 at 8:20 AM, Konstantin Zaitcev <notifications@github.com

**Comment by kosz78** [comment]
We use [Sony Xperia E5](http://www.gsmarena.com/sony_xperia_e5-8113.php) and IPhone 6, for both devices UI performance is slow, I will remove style boxes and test again

**Comment by Zylann** [comment]
Do we know for sure it's due to pixel shaders? Wouldn't an atlas and batching improve the situation?

**Comment by reduz** [comment]
It's not nearly an amount of calls that would slow someting down to 10fps and, as I mentioned before, this works fine in Godot 2 which uses a lot more calls to render this stuff.

I think it's probably pixel performance. For styleboxes, godot does some computations in the fragment shader that are probably not nice in mobile, where all texture reads are expected to go via prefetch in most chipsets.

**Comment by reduz** [comment]
Kicking this to 3.1, as it will be fixed in the upcoming GLES2 backend

**Comment by akien-mga** [comment]
How is the performance with the GLES2 backend? It's still not batched, but it might perform better than GLES3 nevertheless.

**Comment by akien-mga** [comment]
No answer, and in my tests UI performance on Android GLES2 seems good, so closing.
