### ISSUE TITLE
Mono Glue Generation Fails

### ISSUE THREAD

**Issue by BrainBlasted** [godotengine/godot#11808]
**Operating system:** Arch Linux, Godot 3.0 custom build.
**Issue description:** Mono glue no longer being generated by --generate-mono-glue. The output that should appear when glue is generated is absent, and godot builds without the mono module. Found when testing after #11739. [`9b8376e`](https://github.com/BrainBlasted/Godot-Updater/commit/9b8376ef9276f3e27ddc3b0638baa9a08682b407) of my update script was working before. When trying manually, I produced [this](https://hastebin.com/raw/fagudemote) hastebin. Typing the commands to compile manually yielded no difference.
**Steps to reproduce:** Run godot --generate-mono-glue modules/mono/glue as detailed in the [GodotSharp building instructions](https://github.com/neikeq/GodotSharp/wiki/Building#generating-the-glue).

**Comment by neikeq** [comment]
Are you building with `module_mono_enabled=yes`? Those instructions need to be updated to include this, and moved to the docs.

**Comment by BrainBlasted** [comment]
Is this done in both the initial build and after generating glue?

**Comment by toger5** [comment]
I also ran into the exact same issue when trying it today.

**Comment by toger5** [comment]
so `mono_glue=no` got renamed to `module_mono_enable`
OR 
is `module_mono_enabled` needed on the initial build to enable it. only a binary with enabled mono can than execute `--generate-mono-glue` ?

**Comment by toger5** [comment]
is this what is needed for creating a binary that is able to create the bindings:
`scons p=osx target=debug tools=yes mono_glue=no module_mono_enabled=yes`

**Comment by BrainBlasted** [comment]
Well, attempted rebuilding with module_mono_enabled and got this: https://hastebin.com/raw/ulefufaban

**Comment by NathanWarden** [comment]
You can ignore the "target=debug tools=yes" portion as these are the defaults.

So:

scons p=x11 builtin_openssl=yes module_mono_enabled=yes mono_glue=no
bin/godot.x11.tools.64 --generate-mono-glue modules/mono/glue
scons p=x11 builtin_openssl=yes module_mono_enabled=yes

In other words, module_mono_enabled=yes only tells Godot to include Mono, not whether to use the glue or not.

**Comment by toger5** [comment]
@NathanWarden Thank you! that makes sense!
but I still don't get it to work because of `Could not detect MinGW`
any idea?

**Comment by toger5** [comment]
by the way what is `builtin_openssl=yes` used for?

**Comment by BrainBlasted** [comment]
Using the Xamarin msbuild 15, will try with msbuild-bin. builtin_openssl=yes is in case the installed version of openssl on your system is above what is supported by Godot.

**Comment by NathanWarden** [comment]
@toger5 If you're only trying to build for Linux or OSX you can ignore this as it's only used for Windows.

Sorry, I removed "builtin_openssl=yes" above as it's something you only need for certain Linux distros. :)

**Comment by NathanWarden** [comment]
@toger5 If you are trying to make a Windows build you'll need to install mingw. If you are trying to build for Windows which OS are you on?

**Comment by neikeq** [comment]
Yes, the `mono_glue=no` argument is still required when building that binary that generates the glue. Additionally, you need the `module_mono_enabled=yes` command to tell scons to build the mono module itself, because it's disabled by default.

**Comment by BrainBlasted** [comment]
Other than a brief warning, looks like things are working now.

**Comment by toger5** [comment]
Although it just got closed, I would like to answer @NathanWarden question and maybe we get it working for me too.
I'm on macOS.

**Comment by BrainBlasted** [comment]
Not a problem at all, just don't want to bother others by keeping the 
issue marked as open.

**Comment by toger5** [comment]
this is the full output
https://gist.github.com/toger5/315b7e45a0726303c2d16c219c39b490

**Comment by neikeq** [comment]
@BrainBlasted The [msbuild-15-bin](https://aur.archlinux.org/packages/msbuild-15-bin/) package on Arch Linux is defective (both @karroffel and @tagcup had problems with it as well). I think [msbuild-bin](https://aur.archlinux.org/packages/msbuild-bin/) should work.

**Comment by NathanWarden** [comment]
@toger5 Yeah, the MinGW printed is just a warning and you can either ignore it or install MinGW.

Your real error is that you don't have Mono installed. Did you install the Mono from here?
http://www.mono-project.com/download/

You may need to restart before it will be included in your environment variables. If that doesn't work I'll try and help you further as I did get this to work on macOS about a week ago :)

**Comment by BrainBlasted** [comment]
It does now. The reason msbuild-15-bin has issues seems to be because 
it is now unmaintained.

**Comment by NathanWarden** [comment]
@neikeq @BrainBlasted Same here. msbuild-bin works msbuild-15-bin is broken.

**Comment by NathanWarden** [comment]
@toger5 If you have mono installed you might want to see if you can install it using macports.

**Comment by BrainBlasted** [comment]
There's also `brew install mono` if you use homebrew.

**Comment by toger5** [comment]
@BrainBlasted oh nice. that might be better than the installer since the installer is pretty big and has a lot of libs I don't really need.

**Comment by BrainBlasted** [comment]
@neikeq Using msbuild-bin [prevents building solutions](https://hastebin.com/raw/ihogecejop), since godot looks for msbuild, yet msbuild-bin provides xbuild. How does the compilation process handle it?

**Comment by toger5** [comment]
I indeed just didn't had mono installed properly (`mono -V` was giving me an error)
I installed it using the brew formula which seems to work.

@neikeq also mentioned that adding mono to the path could work.
` appending "/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig/" (if mono-2.pc was found there) to PKG_CONFIG_PATH`

for any other desperate OS X person ;)

**Comment by NathanWarden** [comment]
@BrainBlasted I may be missing something you're trying to do in your particular case, but you can change the "Mono > Builds" setting in EditorSettings to use xbuild. Last I tried you have to restart the editor in order for the setting to take affect.

**Comment by novemberist** [comment]
@BrainBlasted This is very much off-topic, but since you mentioned it here, afaik "builtin_openssl=yes" is no longer required for godot to build e.g. on ArchLinux (i think this was fixed a while ago)

**Comment by neikeq** [comment]
> ... change the "Mono > Builds" setting in EditorSettings to use xbuild. Last I tried you have to restart the editor in order for the setting to take affect.

You don't need to restart anymore.

**Comment by BrainBlasted** [comment]
Thanks for letting me know. Also, does Godot produce logs for when 
Proejct solutions fail to build? Nothing shows up in the editor.

**Comment by NathanWarden** [comment]
@novemberist @neikeq Thanks for letting me know on both accounts. :)

**Comment by neikeq** [comment]
@BrainBlasted yes, if there are warning or errors, they will popup on screen (in the bottom panel). If you want to see the logs, you can find them in _user://mono/build_logs/<solution_dir>/msbuild_log.txt_. The solution directory name is not friendly though, it's `<MD5PathToSolution>_<BuildConfiguration>`, but don't worry, I will add a button to open the logs from the editor.
