### ISSUE TITLE
No sound in HTML5 WebAssembly export

### ISSUE THREAD

**Issue by nylnook** [godotengine/godot#11804]
My config: Linux 64bits (Antergos distrib, Arch based, Godot compiled yesterday (3.0.r9756.66987d687-1), and the WebAssembly templates compiled on September the 19th.

I integrated a music to a test game, it works as expected launching from Godot and exported to Linux/X11 binary, but there is no sound in the WebAssembly export. I tried with the .ogg vorbis format and .wav format but no difference.

Here is the link to the exported project:
https://nylnook.art/godot-webassembly/turbo-argument.html
I can share the source files if needed.

And a test project, minimal example (with a sample from Minilens):
[test-sound.zip](https://github.com/godotengine/godot/files/1352700/test-sound.zip)

Thanks for your work !

**Comment by reduz** [comment]
yes its not working, it will be fixed after alpha2

**Comment by nylnook** [comment]
ok, you seem to know what to do ;p

**Comment by reduz** [comment]
This was fixed recently by @eska014 . It is buggy, but there is a separate issue for that now, so closing this.

**Comment by nylnook** [comment]
I still can't test : #13078 ...

**Comment by nylnook** [comment]
I finally tested... and for my project, this is indeed working ! 
thanks a lot ;)
