### ISSUE TITLE
Failed building a windows desktop template on linux (mingw-w64 segfault)

### ISSUE THREAD

**Issue by vopi181** [godotengine/godot#11800]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux
Ubuntu 17.04
Intel(R) Core(TM) i7-4702HQ

Using the default mingw-w64 package in the repos. 

**Issue description:**

I tried to build a windows template from source with:
`scons platform=windows tools=no target=release bits=64
`

It fails on the last compiling scene/3d/audio_stream_player_3d.cpp
`scons: Reading SConscript files ...
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[100%] Compiling ==> scene/3d/audio_stream_player_3d.cpp
scene/3d/audio_stream_player_3d.cpp: In member function 'void AudioStreamPlayer3D::_notification(int)': scene/3d/audio_stream_player_3d.cpp:195:6: internal compiler error: Segmentation fault
 void AudioStreamPlayer3D::_notification(int p_what) {
      ^~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
scons: *** [scene/3d/audio_stream_player_3d.windows.opt.64.o] Error 1
scons: building terminated because of errors.
`

**Steps to reproduce:**
Everytime I build it does. 

**Link to minimal example project:**

**Comment by Calinou** [comment]
Does this happen when cross-compiling other C++ programs? Also, can you try cross-compiling Godot on another Linux distribution (such as Fedora) in a chroot/systemd container or virtual machine?

**Comment by vopi181** [comment]
Just tried with a simple hello world and it seemed to work. Although wine says its a bad EXE, it still produced it.

**Comment by volzhs** [comment]
@vopi181 what do you use for mingw64?

http://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html#cross-compiling-for-windows-from-other-operating-systems
this document says using `export MINGW64_PREFIX="/path/to/i686-w64-mingw32-"` for compiling 64bit windows template, but I had an issue exported game crashes.

so I'm using this instead, and no problem anymore.
```
export MINGW64_PREFIX=/usr/bin/x86_64-w64-mingw32-
```

@Calinou I'm not expert on this and found solution on internet. maybe should document be updated?

**Comment by akien-mga** [comment]
@volzhs That doc is outdated (and wrong):
```
export MINGW32_PREFIX="/path/to/i586-mingw32msvc-"    // that's the old 32-bit only MinGW which we don't support
export MINGW64_PREFIX="/path/to/i686-w64-mingw32-"    // that's the 32-bit version (i686) or the new MinGW-w64 (w64)
```

So it should be:
```
export MINGW32_PREFIX="/path/to/i686-w64-mingw32-"
export MINGW64_PREFIX="/path/to/x86_64-w64-mingw32-"
```

But even then, this is completely unnecessary if mingw is in your PATH already.

**Comment by enthus1ast** [comment]
i was able to fix this on ubuntu zesty by 
adding "artful" repos in "/etc/apt/sources.list" :

`deb http://cz.archive.ubuntu.com/ubuntu artful main universe`

creating apt pinning file "/etc/apt/preferences.d/artful":

```
  Package: *
  Pin: release a=artful
  Pin-Priority: 100
```

updateing repos:

`  apt update`

and installing:

`  apt install -t artful g++-mingw-w64-i686    `

**Comment by mhilbrunner** [comment]
Closing, as this seems to be fixed with the comment above. If this is still a problem with the current master, please ping us so we can reopen.
