### ISSUE TITLE
Self contained mode doesn't work perfectly

### ISSUE THREAD

**Issue by Valentactive** [godotengine/godot#11813]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Tested it under Linux, with latest build from master

**Issue description:**

**UPDATE: The self contained mode works as expected, the problem was located inside the mono module. So no need to read the wall of text anymore :)** 

So the "self contained mode" is a mode to start Godot without touching the system wide configuration of a previous started Godot session. It's very useful if you test different versions of Godot on your system and want to avoid to interfere with other versions. 
Here the description from the docs:  
http://docs.godotengine.org/en/latest/development/compiling/packaging_godot.html?highlight=self-contained#self-contained-mode

Now I already had the impression that it didn't work perfectly in Godot 3.0, but to really be sure about it I removed all files (also the invisible ones) from both the system wide path where Godot per default saves its configuration(s) and the one in my folder from where I test Godot with the self contained mode.
Here the before picture:  
![issue_self-contained-mode_before](https://user-images.githubusercontent.com/16520617/31145393-f04fd2d2-a883-11e7-8f88-889c9b414911.png)

As you can see, everything is deleted in this picture.  
Now to clarify: The folder on the top is the one where Godot saves its default configuration(s), so in this case under Linux it's **"~/.godot/"**. While at the bottom you find two views from the same empty folder where I test Godot starting in self contained mode. Before I started I did as usual, so copied the clean built binaries, in this case godot.x11.opt.tools.64, godot.x11.opt.tools.64.debug and GodotSharpTools.dll (because testing the newly added Mono support and to prove the point) and created a new empty "._sc_" file like I always do since Godot 2.x.  Now when starting Godot in this mode normally it should create a **"editor_data"** folder in which it will then put all the configuration stuff (and also templates etc. if you import any). The problem is not that it doesn't work, indeed it works, but just not perfectly. As you can see as soon as I started it, it also created two folders in the system wide Godot configuration folder (which should not happen in this mode):  
![issue_self-contained-mode_after](https://user-images.githubusercontent.com/16520617/31145915-522bf552-a885-11e7-9119-63de026ee5b3.png)  

Now it created the two folders: "app_userdata" and "mono". In case of app_userdata, it held a folder inside of a game project that I quickly created to test (you can see at the bottom that I also created a "GameProjects" folder in which it has been saved. Now that "Test_Game" folder inside "app_userdata" was empty. But in case of "mono" it wasn't indeed it held the folders for mono's building logs and two folder for the solution files of GodotSharp and GodotSharpEditor. Now most of the stuff got into "editor_data" but the mono folder didn't. Talking with @neikeq he said it could be an issue with the "**get_settings_path()**" function in "**EditorSettings**", as it should return exe_path + "editor_data" for the self-contained mode. On a second note other folders are as expected within the "editor_data" folder in the self contained folder.

**Steps to reproduce:**

1. Delete all the content in the default configuration folder of Godot (~/.godot/ or equivalent for Windows and OS X)  

2. choose a empty folder where you want to test Godot in self contained mode and create a empty file called "**._sc_**" in it. 

3. make a clean build of Godot with the targets set as you please (but consider trying it with module_mono_enabled=yes so you can test the behavior)

4. copy the binarie(s) to the folder where you have created the "**._sc_**" file and execute Godot. Maybe create also a simple project (1 node is enough and save the scene), so you can also see that it still creates the "**app_userdata**" (and the mono folder) where Godot would per default save them when **not** run in self contained mode.

**Comment by J08nY** [comment]
The `app_userdata` comes from [drivers/unix/os_unix.cpp#L505](https://github.com/godotengine/godot/blob/0c82d113edc4f7cc1bef11c2e03b2a1b39de90fb/drivers/unix/os_unix.cpp#L505) and [platform/windows/os_windows.cpp#L2322](https://github.com/godotengine/godot/blob/0c82d113edc4f7cc1bef11c2e03b2a1b39de90fb/platform/windows/os_windows.cpp#L2322) where self-contained mode is not considered.

The self-contained mode however only concerns config data (as per the docs), so if this is changed to be completely self-contained (as in no file write outside of the folder with `._sc_`) that needs to be reflected in docs.

Not yet sure where the `mono` folder comes from. Will search and do a PR, along with the docs change.

**Comment by Valentactive** [comment]
You're right just took a look at it some minutes ago. But I think both the os_unix.cpp and os_windows.cpp are fine as they are. Indeed the rest seems to work ("config", "script_templates", "templates", "text_editor_themse" and editor_settings-3.tres are created and saved where expected. I suspect that the folder inside "app_userdata" of a game project created in self contained mode is still triggered by the Mono module, as I tested a build without Mono and it didn't create the folder.

**Comment by neikeq** [comment]
> **Edit**: `mono` comes from [modules/mono/godotsharp_dirs.cpp#L71](https://github.com/godotengine/godot/blob/b759d1416f574e5b642413edd623b04f2a1d20ad/modules/mono/godotsharp_dirs.cpp#L71).

Ah, yes... That's because ProjectSettings is not initialized yet by the time I need it. I'll probably have to add the self contained condition there.

**Comment by Valentactive** [comment]
Yes neikeq I think that must be it

**Comment by akien-mga** [comment]
Note that `app_userdata` is not meant to be local in the self-contained mode, that mode is for Godot itself but does not impact Godot games. You should be able to access the same game data from a system-installed Godot and a self-contained one.

**Comment by Valentactive** [comment]
You're right @akien-mga it does not impact the games. I already made an update to the description in this issue saying 9 days ago: 

> UPDATE: The self contained mode works as expected, the problem was located inside the mono module. So no need to read the wall of text anymore :)  

Should I change also the title of this issue?
