### ISSUE TITLE
Shader blend mode MUL and MIX is equals

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#11822]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master build b2046836401fe5cdaf4ae6ae32ad3323511b956d

**Issue description:**
In spatial shader material `blend_mix` and `blend_mul` produce the same result.

According the implementation https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_scene_gles3.cpp#L2061 it contains identically code.

**Comment by groud** [comment]
Do you have any screenshots ? Cause those enums are used elsewhere, I'd like to be sure this is a real issue.

**Comment by kosz78** [comment]
I have attached the sample project
[test-blend.zip](https://github.com/godotengine/godot/files/1355683/test-blend.zip)

In the project it displays three materials that used different blend types, `blend_add`, `blend_mix` and `blend_mul`:
![image](https://user-images.githubusercontent.com/3992195/31174746-cc4e5526-a936-11e7-9d93-fac3d5bc5a41.png)

**Comment by hi-ogawa** [comment]
I don't know if this helps in anyway, but I found they behave differently regarding depth pass.
Relevant code is `RasterizerSceneGLES3::_add_geometry_with_material` https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_scene_gles3.cpp#L2207 and it seems this function decides whether given geometry should join depth rendering pass based on blend_mode and some other material parameters.
So, as an example, blend_mix casts shadow but blend_mul doesn't. In the below screenshot, the left cube is blend_mix and the right cube is blend_mul.

![blend_mix_vs_mul](https://user-images.githubusercontent.com/4232207/31584064-ba0fc88c-b1e1-11e7-82fc-8c86a7f0e877.png)

**Comment by reduz** [comment]
will take a look in 3.1, as this is not critical
