### ISSUE TITLE
Focus on selected node...

### ISSUE THREAD

**Issue by mamarilmanson** [godotengine/godot#1182]
this is actually a link from marynate's thread that I think I might need right now... :)

http://www.godotengine.org/forum/viewtopic.php?f=8&t=546&hilit=ux+improvements&start=40#p2475

**Comment by not-surt** [comment]
In 2D Editor there's Frame Selected (Ctrl+F)?

**Comment by mamarilmanson** [comment]
I mean on the 3D side and to focus on the nodes...

**Comment by akien-mga** [comment]
See #437.

**Comment by akien-mga** [comment]
This could be done with a hotkey.

**Comment by neikeq** [comment]
I am adding the 3.0 milestone, since the renderer will improved and probably the 3D tools too.

**Comment by reduz** [comment]
404 page not found, so I have no idea what this is. You can do it with F in 3D now, so will close this
