### ISSUE TITLE
Opening a folder with .cs files crashes Godot (Mono related?)

### ISSUE THREAD

**Issue by NathanWarden** [godotengine/godot#11834]
Godot 3.0 git HEAD 64 bit

Manjaro Linux 64 bit
Ubuntu 17.10b2
Windows 10

**Issue description:**

When navigating into a CSharp scripts folder Godot crashes if there's a .mono folder and if there are no icons of the scripts in the ~/.godot/tmp folder.

@neikeq I believe this is Mono related as a lot of Mono items are in the crash log, deleting the .mono folder fixes the crash, or if I simply rename files from having .cs to .gd (and leave the .mono folder there) it no longer crashes.

**Steps to reproduce:**

edit: Okay, I've narrowed it down a bit more. I tried it on Ubuntu 17.10b2 and I was able to navigate to the folder as long as I didn't first make a build.

I was then able to cause it to break again by:

1) Deleting the ~/.godot/tmp folder
2) Make a build (F5/F6)
3) Restart the editor
4) Navigate to the Scripts folder
Crash

I was able to navigate again to the folder by:

1) Deleting the .mono folder for the project
2) Restart the editor
3) Navigate to the folder
No crash

So, it seems somehow related to failing to generate icons when there's a successful build in the .mono folder?

I've made a video: [DirectoryOpenCrash.zip](https://github.com/godotengine/godot/files/1356420/DirectoryOpenCrash.zip)

**Link to minimal example project:**

edit: Here's a simple project:

[Test_Proj_CS.zip](https://github.com/godotengine/godot/files/1357254/Test_Proj_CS.zip)

edit: Removed the crash dump as you should now be able to get your own now that the bug is reproducible.

**Comment by NathanWarden** [comment]
Okay, I've narrowed it down a bit more. I tried it on Ubuntu 17.10b2 and I was able to navigate to the folder as long as I didn't first make a build.

I was then able to cause it to break again by:

1) Deleting the ~/.godot/tmp folder
2) Make a build (F5/F6)
3) Restart the editor
4) Navigate to the Scripts folder
Crash

I was able to navigate again to the folder by:

1) Deleting the .mono folder for the project
2) Switch the build system from xbuild to MSBuild
3) Restart editor
4) Navigate to the folder
No crash

So, it seems somehow related to failing to generate icons when there's a successful build in the .mono folder?

Okay, time to try it on Windows again since I didn't try these steps before.

**Comment by NathanWarden** [comment]
Yep, happens on Windows too.

**Comment by NathanWarden** [comment]
Okay, I was able to reproduce the problem with the steps above in a simple project. :)

[Test_Proj_CS.zip](https://github.com/godotengine/godot/files/1357254/Test_Proj_CS.zip)

**Comment by neikeq** [comment]
Does this still happen after #11845?

**Comment by NathanWarden** [comment]
Unfortunately it's still doing it.

**Comment by neikeq** [comment]
All right, just wanted to make sure it was not related to the assembly loading error at startup. I'll test tomorrow.

**Comment by NathanWarden** [comment]
Awesome, thanks :)
