### ISSUE TITLE
Build mono (C#) script macOS. msbuild not found xbuild can't build with godot api.

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#11839]
I cannot build a c# script (start the game) with msbuild selected in the editor settings.

<img width="265" alt="screen shot 2017-10-04 at 21 20 42" src="https://user-images.githubusercontent.com/16718859/31195309-2853c62c-a94a-11e7-8a72-6651b52adfed.png">
<img width="789" alt="screen shot 2017-10-04 at 21 20 55" src="https://user-images.githubusercontent.com/16718859/31195310-287b5e26-a94a-11e7-9800-11ff2a28bfa9.png">

If I change to xbuild I can start the project but only if the script does not interact with the godot api.
Calling set_postion, declaring a Vector2 or using get_node. Or I think any other godot api function.
getting the same error.
<img width="265" alt="screen shot 2017-10-04 at 21 20 42" src="https://user-images.githubusercontent.com/16718859/31195309-2853c62c-a94a-11e7-8a72-6651b52adfed.png">

**Comment by neikeq** [comment]
Can you check if it can find MSBuild after #11845 is merged?

**Comment by neikeq** [comment]
IINW you were using the homebrew package, which I think does not include MSBuild (I'm not sure). If it still can't find MSBuild after the mentioned PR is merged, you could try with the package from [mono's page](http://www.mono-project.com/download/#download-mac).

**Comment by neikeq** [comment]
@Tommel1234 What version of mono do you have?

**Comment by Tommel1234** [comment]
5.0.0.1.. I think it don't come with msbuild .. maybe It doesnt install msbuild with this version..

**Comment by Tommel1234** [comment]
I get some error when i generate the glue too
![screenshot from 2017-10-05 00-23-20](https://user-images.githubusercontent.com/18587154/31210953-a9fffe20-a963-11e7-9cfd-d7bdaf55f5c6.png)

**Comment by piever** [comment]
I'm afraid that the solution is somehow not working: even after #11845 (I'm on today's master) I still get msbuild not found error which on my machine gets fixed by adding 

`msbuild_path = '/Library/Frameworks/Mono.framework/Versions/Current/bin/msbuild'`

at [this line](https://github.com/godotengine/godot/blob/master/modules/mono/SCsub#L82).

I'm just not sure why that's needed as the folder  '/Library/Frameworks/Mono.framework/Versions/Current/bin/' was added in the #11845 PR.

**Comment by neikeq** [comment]
@piever Oh, I forgot to add that hint path to the build system as well. I will make a PR tonight.

>Generating _Thread...
ERROR: _load: No loader found for resource: res://modules/mono/glue
   At: core/io/resource_loader.cpp:184.
ERROR: start: Failed loading scene: res://modules/mono/glue
   At: main/main.cpp:1546.
Mono: Runtime cleanup...
debugger-agent: Unable to listen on 42
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1858.

That error is not related to glue generation. After generating the glue, Godot will continue with initialization, it will think you want to open the path you passed via cmd as a scene, and fail. I'll check if we can make it exit before that.

**Comment by piever** [comment]
Thanks for looking into this! 
I'm still not sure whether I got a successful mono build or not, because in the end, despite the error, the glue had already been generated, but after I open the Godot app I have the .cs script option but it's broken: it doesn't accept any name as valid class name.

<img width="381" alt="screen shot 2017-10-23 at 19 24 06" src="https://user-images.githubusercontent.com/6333339/31906012-d2307faa-b827-11e7-99a2-937f49030471.png">

**Comment by przmkg** [comment]
You need to type in the Class Name as well.

**Comment by piever** [comment]
Wow, that was silly... But the problem persists: after giving it a name I still get a:

`Failed to build GodotSharp solution`

so it seems like there are still some issues (not sure if related with `msbuild` or glue generation: I'll check again after @neikeq 's PR

**Comment by neikeq** [comment]
@przmkg What version of Mono do you have installed? Where is MSBuild located in your filesystem?

@piever Is there any error in the bottom panel (`Mono -> Builds`, although it's made visible on errors)? If not, try running from the terminal to see the output.

**Comment by przmkg** [comment]
@neikeq The version is 5.4 but I can't seem to find any sort of MSBuild binary on my system. I'm using the `mono-stable` from the AUR on Manjaro.
I will try to compile it from the official source by myself and will report the result.

**Comment by przmkg** [comment]
Okay, now when I'm creating  a C# script, I have:
`ERROR: save: Cannot add res://Character.cs to the C# project because it could not be created.
   At: modules/mono/csharp_script.cpp:1927.`

Don't know if my mono installation and msbuild is well done. Maybe it would be better to wait and see if someone else has this issue.

**Comment by piever** [comment]
@neikeq I hadn't noticed it at first but I get two errors:

<img width="764" alt="screen shot 2017-10-23 at 22 15 47" src="https://user-images.githubusercontent.com/6333339/31913708-e584fa8c-b83f-11e7-96ed-b4f902760a77.png">

Surprisingly enough, the first seems to happen even if there's no cs script at all...

**Comment by neikeq** [comment]
@przmkg try with https://aur.archlinux.org/packages/msbuild-bin/

@piever Do you see something like this?

![img](https://user-images.githubusercontent.com/7718100/31915989-f84022b2-b850-11e7-9e97-4874440cb094.png)

**Comment by przmkg** [comment]
@neikeq This is the one I tried with and I got the error mentioned in my previous post.

**Comment by piever** [comment]
I see this if I hover on the error:

![screen shot 2017-10-24 at 11 08 05](https://user-images.githubusercontent.com/6333339/31937250-c05bb78e-b8ab-11e7-8ff9-12589ec15367.png)

**Comment by piever** [comment]
UPDATE: I rebuilt after @neikeq PRs and it's working now!

**Comment by neikeq** [comment]
@przmkg is msbuild's directory in the PATH variable? If not, what's the location?

**Comment by przmkg** [comment]
@neikeq Okay, everything is working now.
So basically, I've compiled a recent version of mono 5.4 by myself (though `mono-stable` from the AUR should work).
After that, I took the latest deb file from [here](http://download.mono-project.com/repo/ubuntu/pool/main/m/msbuild/) (in this case msbuild_15.4+xamarinxplat.2017.09.14.16.14-0xamarin1+ubuntu1404b1_all.deb) and I've extracted it manually into `/usr`. Now it works wonderfully.

Thanks again!

**Comment by neikeq** [comment]
Any issues with MSBuild on OSX after #12535?

**Comment by piever** [comment]
Working fine on my machine, thanks a lot for fixing this!

**Comment by rodrigofbm** [comment]
![selectionshot_2018-02-17_23 15 21](https://user-images.githubusercontent.com/14153439/36347554-7d0dadbe-1438-11e8-9f3d-dc24b8a09f7b.png)
I got thie errors. I'm using latest mono stable version. Can anyone help me, pls?

**Comment by neikeq** [comment]
@rodrigofbm You can check the workarounds in #16327, until that is fixed.
