### ISSUE TITLE
Relocating the "local coords" option

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#11831]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0

**Issue description:**
I think the "local coords" option should be more accessible than hiding it in the transform menu, I think it should be enable by just one click, thus, the option should be locate somewhere in the viewport.

Now:
![2017-10-04 21 30 37](https://user-images.githubusercontent.com/10883749/31178679-63a46856-a94c-11e7-8f09-9bca001958af.png)

Idea:
![2017-10-04 21 30](https://user-images.githubusercontent.com/10883749/31178707-7552a518-a94c-11e7-9b76-b868c515a14e.png)
The gizmos in the corner may not be necessary, that's just a idea where the "local coords" option should be.
Another idea would be placing the checkbox next to the "view"

**Comment by n-pigeon** [comment]
I plan to move "Local Coords" next to Transform Gizmo buttons, also as a button that changes icon based on type - world or local.

Snapping also should be there I think.

**Comment by mhilbrunner** [comment]
When I started using the 3D editor, that was one the first pain points I had :) Are there already icons for this? If not, where do we get them from?

And yeah, snapping should be in the toolbar too, if possible.

**Comment by ZX-WT** [comment]
This is solved. Closing it.
