### ISSUE TITLE
Multiple locks on web thread not allowed! Please file a bug. Crashing now

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#11830]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2.1
iOS

**Issue description:**
When load a banner and a interstitial, then show the banner and interstitial, all the methods are called on the main thread, the app will crash when close the interstitial.
However, if I only load  and show a interstitial, it will work without any problem.

2017-10-04 20:52:56.354364+0800 godot_opt.iphone[8656:3238154] bool _WebTryThreadLock(bool), 0x1c401fc10: Multiple locks on web thread not allowed! Please file a bug. Crashing now...

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
I don't see any call to `_WebTryThreadLock` in Godot, so the problem likely comes from the module that you are using to load and display ads (it's not supported in Godot out of the box, so it's not in the scope of this issue tracker). If you can debug the module-specific issue and track it down to a reproducible engine bug, then please file an issue with detailed steps to reproduce.

**Comment by sersoong** [comment]
This is a problem caused by the misuse of admob ads.
@alexzheng I've seen your admob's module code.
That is to say,your had some bugs.

**Comment by alexzheng** [comment]
Can you point out what is the bug in my admob module?

**Comment by samuelpedrajas** [comment]
@alexzheng did you find a solution to this? I'm having the same issue when closing rewarded video ads on iOS.
