### ISSUE TITLE
Screen space reflections behaving strangely when used with an orthographic Camera

### ISSUE THREAD

**Issue by Nappael** [godotengine/godot#11841]
Currently using a Windows build of Godot 3.0 from a few days ago.

**Issue description:**
When using an orthographic camera in combination with screen space reflections, the reflections act differently to what can be expected when using the editor in orthographic mode. Using a simple scene with a plane and a cube with reflective materials:

![godot3ortho](https://user-images.githubusercontent.com/3076277/31198275-88b03f18-a94b-11e7-9999-a13bb03a5204.png)

Perspective mode on the other hand, looks exactly the same in editor vs the camera.

**Steps to reproduce:**
Create any scene with reflective materials.
Add a camera and set it to orthographic mode
view scene in editor (in orthographic mode), compare it to camera preview or build.

Not sure if this is an actual issue, or something simple that I'm missing. If it is the latter then I apologize.

**Comment by reduz** [comment]
I fixed this recently, tested again and it seems to be working fine.
