### ISSUE TITLE
Mono missing ProjectSettings.Get

### ISSUE THREAD

**Issue by NathanWarden** [godotengine/godot#11844]
For instance, there's no way to get the project's name (or any other setting) as you can in GDScript.

C#:

    string projectName = ProjectSettings.Get("application/config/name"); // Doesn't exist in C#

GDScript:

    var project_name = ProjectSettings.get("application/config/name") # Exists in GDScript

Thanks!

**Comment by neikeq** [comment]
Damn... didn't notice this when making singletons. We decided to make them static classes with static methods instead to give a better feel, instead of `ProjectSettings.Instance.Get(...)`. I'll have to discuss this on IRC.

**Comment by neikeq** [comment]
Two possible solutions:
- Make those classes singletons, so you need `.Instance` for all of its methods.
- Make those classes singletons, but the methods of the class are static. This way you can do `ProjectSettings.SaveCustom(...)` and for the inherited members: `ProjectSettings.Instance.Get(...)`.

**Comment by reduz** [comment]
No need to go for something so far fetched, just hack it and expose set and
get imo in those classes.

On Thu, Oct 5, 2017 at 2:53 PM, Ignacio Etcheverry <notifications@github.com

**Comment by reduz** [comment]
we could even expose them from Godot, as set_setting and get_setting,
because its not obvious to gdscript either

**Comment by neikeq** [comment]
@reduz If we are going to hack it to include those methods, we need a full list of all the methods that like this that are required for this. Are `get` and `set` in `ProjectSettings` and `EditorSettings` the only cases?

**Comment by reduz** [comment]
yes, i dont think any others are needed

On Thu, Oct 5, 2017 at 3:03 PM, Ignacio Etcheverry <notifications@github.com

**Comment by neikeq** [comment]
Then, indeed, hard-coding it may be the best solution.
