### ISSUE TITLE
2 shadow map issues

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#11848]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10 current build of Godot3

**Issue description:**

Issue 1: When a scene with a shadow mapped spotlight is run, it sometimes exhibits artifacts. The image on the left shows a sample scene when run the first time. There is a cutout part of the shadow directly under the sphere. If the scene is reloaded using get_tree().reload_current_scene() it then looks correct as can be seen on the right. 

![shadow_map_bug](https://user-images.githubusercontent.com/7741669/31212266-4b1b9f12-a9eb-11e7-9691-9ab2a79bd238.jpg)

Similarly, when the test scene is first loaded, the shadow artifact can be seen under the sphere, but if the spotlight is toggled off and on, it looks correct(as is illustrated in the second image)

![shadow_map_bug2](https://user-images.githubusercontent.com/7741669/31212528-ca0493fa-a9ec-11e7-8373-9b18b2c7505b.jpg)

Issue 2: When a scene is reloaded using get_tree().reload_current_scene() and has a shadow mapped spotlight or omni, the console gets spammed with an opengl error message stating:

ERROR: _shadow_atlas_find_shadow: Condition ' !sli ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:270
ERROR: getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
   At: core/rid.h:164

This will happen with any scene containing either an omni or spotlight with shadow enabled. The error only ever happens upon reload and slows down the game severely!

**Steps to reproduce:**
- run the following test scene and hit spacebar to reload the scene. This scene will demonstrate the 2 bugs described.

**Link to minimal example project:**

[shadow_map_bug.zip](https://github.com/godotengine/godot/files/1358154/shadow_map_bug.zip)

**Comment by hi-ogawa** [comment]
The second issue (endless error messages when changing scene) might be a duplicate of https://github.com/godotengine/godot/issues/10346.

**Comment by fracteed** [comment]
@hi-ogawa yes this is indeed the same bug! I have gotten around it for the moment by changing the debugger port no. I also am noticing that sometimes the shadow mode looks noticeably grainier(maybe a lower res than the default 4096) after the scene has reloaded several times.

When I do a test export of my game in release mode(debug mode is ok though), it will crash when a scene changes, so it is a serious issue.

**Comment by groud** [comment]
Probably fixed by #11958, can you confirm ?

**Comment by fracteed** [comment]
@groud , yes all is good. Thanks again to @hi-ogawa !
