### ISSUE TITLE
GridMap enhancement - Convert an arbitrary point in world space, to GridMap cell coordinates

### ISSUE THREAD

**Issue by ScottMakesGames** [godotengine/godot#11856]
Add a method to GridMap that would convert an arbitrary point to a grid cell coordinate. This is relatively simple to do in GDScript, but it would be a good addition to the base GridMap class.

something like `get_cell_at(Vector3)`

the basic logic for this method would be:
```
var translated_pos = provided_pos / grid_map.get_cell_size()  # convert to cell space
var rounded_pos = Vector3(round(translated_pos.x), round(translated_pos.y), round(translated_pos.z)) # flatten to nearest discrete cell  
return rounded_pos
```
This might need adjustments for coordinates in negative portions along the x, y or z axes, I'm not sure.

**Comment by saltares** [comment]
Taking a look
