### ISSUE TITLE
Visual Scripting: "Invalid returns count" error on `CallInstance`

### ISSUE THREAD

**Issue by netcell** [godotengine/godot#11851]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3 built on commit 454dec2f2

**Issue description:**
`Call` node on `Instance` mode throws this error on some functions:

```
Invalid returns count for call_mode == CALL_MODE_INSTANCE
```

This doesn't happen with `Node` mode on `Call` node

**Steps to reproduce:**
Drag in a reference of `Node`
Instance a reference of another `Node`
Drag in a `Call` node
Set `Call Mode` to `Instance`
Set `Base Type` to `Node`
Set `Function` to `add_child`
Plug the first `Node` into `instance` port
Plug the second `Node` into `node` port
Run

![image](https://user-images.githubusercontent.com/3048558/31213937-33c9835a-a9d3-11e7-8244-acec3d47a671.png)

**Comment by reduz** [comment]
@bojidar-bg want to give it a try?
