### ISSUE TITLE
"Help Font Size" affects popup's title and other stuff

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11865]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor/2017-10-05.8b52d53#files) 8b52d53

**Issue description:**
The setting "Text Editor/Help/Help Font Size" affects all popup's titles, the projects names in the project manager, and the "Godot Engine - Project Manager" label in the top-left.

**Comment by reduz** [comment]
@djrm @toger5
