### ISSUE TITLE
Issue with Navmesh character is not visible in some points

### ISSUE THREAD

**Issue by gerardogc2378** [godotengine/godot#11862]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
ArchLinux OS 
Godot 2.1.4 Stable

**Issue description:**

Someone have this issue with a navmesh, the character is not visible in some points.

**Steps to reproduce:**
Just click anywhere of the navmesh some times the character is visible some times not.

**Link to minimal example project:**

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
