### ISSUE TITLE
[Documentation] RichTextLabel newline function does exist

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#11861]
**Issue description:**
Tried to call the function `new_line` on a RichTextLabel node and got an exception

```
Invalid call. Nonexistent function 'new_line' in base 'RichTextLabel'.
```

Accordingly to [the documentation](http://docs.godotengine.org/en/stable/classes/class_richtextlabel.html#class-richtextlabel-newline) this function should exists.

**Steps to reproduce:**
* Create a **new scene**
* Add a **RichTextLabel** node
* Attach a script and in the function **ready** put this

```python
extends RichTextLabel

func _ready():
  new_line()
```

**Comment by djrm** [comment]
isnt it `newline()`

**Comment by xsellier** [comment]
Nope, I've just read the code and it is `add_newline` (https://github.com/godotengine/godot/blob/b61462268e9a8a2c86c1abd5bc65cd96659fa979/scene/gui/rich_text_label.h#L290)

**Comment by djrm** [comment]
but you are not using c++, you are using GDScript, and the documentation for GDScript clearly says its `newline()`

**Comment by xsellier** [comment]
Thank you @djrm but none of `newline` or `add_newline` is working.

**Comment by djrm** [comment]
im unable to replicate this issue

**Comment by cbscribe** [comment]
This works fine for me:

    get_node("RichTextLabel").newline()

**Comment by xsellier** [comment]
Yup, my bad, I've written `new_line`, and not `newline`, sorry
