### ISSUE TITLE
Ctrl + clicking "File"/"Directory" in the text editor opens empty docs.

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11867]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor/2017-10-05.8b52d53#files) 8b52d53

**Issue description:**
Self-explanatory.

**Comment by reduz** [comment]
any more detail appreciated, which text editor?

**Comment by YeldhamDev** [comment]
@reduz 
![bug](https://user-images.githubusercontent.com/30739239/32497323-55db861a-c3b3-11e7-8d6d-5a6715f6df43.gif)

**Comment by Paulb23** [comment]
This seems to be caused as some classes are prefixed with underscores, namely the ones in `core_bind.cpp` causing it to search for "_file" rather then "file". It finds the docs correctly when the underscore is removed.
