### ISSUE TITLE
 Repeated "Using glBufferSubData to update a GL_STATIC_DRAW buffer" error on Haswell/Linux

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11872]
(Mesa 17.2.2 on Arch Linux)

I keep getting this error on Intel (4770K) using current master:

```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Performance       ID: 108 Severity: Medium        Message: using glBufferSubData(buffer 43, offset 0, size 32) to update a GL_STATIC_DRAW buffer
   At: drivers/gles3/rasterizer_gles3.cpp:122.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Performance       ID: 108 Severity: Medium        Message: using glBufferSubData(buffer 43, offset 0, size 32) to update a GL_STATIC_DRAW buffer
   At: drivers/gles3/rasterizer_gles3.cpp:122.
FPS: 6
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Performance       ID: 108 Severity: Medium        Message: using glBufferSubData(buffer 43, offset 0, size 32) to update a GL_STATIC_DRAW buffer
   At: drivers/gles3/rasterizer_gles3.cpp:122.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Performance       ID: 108 Severity: Medium        Message: using glBufferSubData(buffer 43, offset 0, size 32) to update a GL_STATIC_DRAW buffer
   At: drivers/gles3/rasterizer_gles3.cpp:122.
FPS: 6
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Performance       ID: 108 Severity: Medium        Message: using glBufferSubData(buffer 43, offset 0, size 32) to update a GL_STATIC_DRAW buffer
   At: drivers/gles3/rasterizer_gles3.cpp:122.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Performance       ID: 108 Severity: Medium        Message: using glBufferSubData(buffer 43, offset 0, size 32) to update a GL_STATIC_DRAW buffer
   At: drivers/gles3/rasterizer_gles3.cpp:122.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Performance       ID: 108 Severity: Medium        Message: using glBufferSubData(buffer 43, offset 0, size 32) to update a GL_STATIC_DRAW buffer
   At: drivers/gles3/rasterizer_gles3.cpp:122.
UNLINK
```

The performance has been quite bad on 3.0 from the beginning (see #9725), but it's now it's worse at 6 FPS.

**Comment by tagcup** [comment]
BTW the performance has also gone really bad on an old nvidia (gt 425m), it's also around 6FPS.

**Comment by tagcup** [comment]
This is also a regression from alpha1, and I think it'd be nice to fix.

Well, ideally, it'd be nice it Godot properly worked on Intel HD 4k in general...

**Comment by tagcup** [comment]
This only happens when I modulate the parameters of a shader material using an animation node.

@reduz is this supposed to be avoided?

**Comment by PerduGames** [comment]
I'm also getting the error:
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Performance	ID: 2	Severity: Medium	Message: using glBufferSubData(buffer 20, offset 0, size 48) to update a GL_STATIC_DRAW buffer
   At: drivers/gles3/rasterizer_gles3.cpp:122.
```
the fps dropped a bit too, and sometimes has very low peaks.

**Comment by reduz** [comment]
i removed performance warnings, i'm fed up of them

**Comment by tagcup** [comment]
The performance drop is the real issue here, not the warning (which is just a symptom, not the underlying reason) so can we reopen this?

**Comment by akien-mga** [comment]
Yeah I don't think ignoring warnings would solve the issue, unless the log spam is so intense that it causes performance issues itself..

**Comment by Zireael07** [comment]
The log spam WAS so intense that it was rendering stuff totally unusable (3-4 fps). So at least that part of the problem is gone.

**Comment by tagcup** [comment]
That warning wasn't there before, for the same scene. It appeared after a change in Godot, and probably for a real reason.

It's still slow BTW.

**Comment by tagcup** [comment]
There's a new feature to halve the viewport BTW, with that, it runs pretty fast only looks pretty low-res.

**Comment by reduz** [comment]
I will give it a check as soon as I get back

**Comment by akien-mga** [comment]
Is this still valid in the current master branch? (I mean the original error message - the overall bad Intel performance is tracked in #9725 and AFAIK still valid).

**Comment by poke1024** [comment]
This might be off topic or just plain uninformed of me, but out of curiosity, it would be interesting to replace those `glBufferSubData` calls with `glBufferData` and see if that makes any difference; this guy claims that `glBufferSubData` causes stalls in some drivers that `glBufferData` doesn't: http://thothonegan.tumblr.com/post/135193767243/glbuffersubdata-vs-glbufferdata

**Comment by reduz** [comment]
i hay have fixed this already, and i cant reproduce it anymore
