### ISSUE TITLE
EditorAbout: quotations have additional backspace prefix

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#11874]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64 | d938de6

**Issue description:**

![image](https://user-images.githubusercontent.com/26753932/31261959-ef89dae6-aa81-11e7-85fe-2e560138e1b8.png)

Related: #11592

**Comment by Toizi** [comment]
I have fixed this issue and created a PR #11922

**Comment by Noshyaar** [comment]
Fixed by #11922 

Please include 'Fixes #xxxxx' in the PR description so that it's closed automatically.
