### ISSUE TITLE
C++ Module: AudioStreamSample  return data seems to be corrupted

### ISSUE THREAD

**Issue by hungrymonkey** [godotengine/godot#11873]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Godot master

**Issue description:**

I am serializing int16_t to an PoolByteArray then to AudioStreamSample

When I call AudioStreamSample.set_data on the resulting PoolByteArray, i cannot get the same data out when I call AudioStreamSample.get_data

**Steps to reproduce:**

Make an PoolByteArray d with values

Call AudioStreamSample.set_data(d)

AudioStreamSample.get_data() returns a different PoolByteArray I put in.

Expected: The values should be the same

**Link to minimal example project:**

I have a minimal example project to reproduce the issue. 

https://github.com/hungrymonkey/godot/tree/issue11873

here is the code i am testing the issue with

```
void Summator::reset() {
    
    int s = 960;
    PoolByteArray d;
    d.resize(2 * s);
    for( int i = 0; i < s; i++ ){
       float p =  Math::sin((((float) i)*2.0*3.14 * 1000.0) / (44100.0)) * 32767;
       int32_t l = p;
       uint32_t a = (uint32_t) l;
       d.set(i*2, a & 0xFF);
       d.set(i*2+1, (a >> 8) & 0xFF);
    }
    Ref<AudioStreamSample> sam = memnew(AudioStreamSample);
    sam->set_data(d);
    sam->set_format(AudioStreamSample::FORMAT_16_BITS);
    sam->set_loop_mode(AudioStreamSample::LOOP_DISABLED);
    const PoolByteArray dat = sam->get_data();
    bool same = true;
    for( int i = 0; i < s * 2; i++){
        if( d[i] != dat[i]){
          print_line("at " + itos(i) + " : array,sample: " + itos(d[i]) + " : " + rtos(dat[i]));
          same = false;
          break;
        }
    }
    if( same)
       print_line("both the get_data and d are the same");
    else
       print_line("both the get_data and d are not the same");
    print_line("at " + itos(100) + " : array,sample: " + itos(d[100]) + " : " + itos(dat[100]));
    count = 0;
}

```

use the gdscript below

```
extends MainLoop
func _init():
        var s = Summator.new()
        s.reset()
```

it outputs
```
at 2 : array,sample: 42 : 0
both the get_data and d are not the same
at 100 : array,sample: 13 : 231

```
As a time of writing, DATA_PAD should be 16

**Comment by hi-ogawa** [comment]
I might be wrong since I haven't even used `AudioStreamSample`, but after briefly checking the code, I found that `DATA_PAD` in `AudioStreamSample::set_data` is not applied for `AudioStreamSample::get_data`.

Here is relevant code from current master:

- https://github.com/godotengine/godot/blob/master/scene/resources/audio_stream_sample.cpp#L474
- https://github.com/godotengine/godot/blob/master/scene/resources/audio_stream_sample.cpp#L489

maybe small fix like this will work?

```
PoolVector<uint8_t> AudioStreamSample::get_data() const {

	PoolVector<uint8_t> pv;

	if (data) {
		pv.resize(data_bytes);
		{
			PoolVector<uint8_t>::Write w = pv.write();
			uint8_t *dataptr = (uint8_t *)data;
			copymem(w.ptr(), dataptr + DATA_PAD, data_bytes); // <= DATA_PAD is added here
		}
	}

	return pv;
}
```

**Comment by hungrymonkey** [comment]
```
utils: pcm value at 500: -324
utils: pcm value at 700: 184
utils: pcm value at 500: 188 254
before audiostreamsample-set_data: pcm value at 700: 184 0
after audiostreamsample-set_data: pcm value at 500: 188 254
pcm_data1 size :1920
sendaudio: pcm value at 500: 188 254
pcm value at 500: -324

```

Since I am kinda a newbie, I am not really sure how to play sound in godot. I just using classes as I integrate stuff. It seems to work but I cannot confirm it through playing pcm.

**Comment by hungrymonkey** [comment]
i figure manage to get sound to work in my application. I am going to write a pull request soon. The audio works either way but the pointer off set issue seem to give garbled data.

**Comment by hungrymonkey** [comment]
btw, thanks for the code snippet. I would not thought of it

**Comment by hi-ogawa** [comment]
Hi @hungrymonkey, to tell you the truth, I'm also a noob here and even in gaming program in general.
I hope someone who did audio work in godot can review your PR.
anyway, I'm glad you figure out audio playback!

**Comment by hungrymonkey** [comment]
https://github.com/godotengine/godot/commit/98718ecd63476352f0a6299b2af2dd046ed9d5e3

**Comment by hungrymonkey** [comment]
@akien-mga I am reviewing the code again. I realize I should had not created this pull request. 

I made a mistake. AudiostreamSamplePlayback requires a datapad to work. 

https://github.com/godotengine/godot/blob/98718ecd63476352f0a6299b2af2dd046ed9d5e3/scene/resources/audio_stream_sample.cpp#L124

Can we just document the behavior that get_data() is padded on both sides.
