### ISSUE TITLE
Tilemap rotation and mirror broke the collision

### ISSUE THREAD

**Issue by damarindra** [godotengine/godot#11876]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Master branch

**Issue description:**
Open isometric example project, run it with debug collision visible, go into the door which is mirrored, the collision is not in right place. This bug only on master branch (v3), I've tried with v2.x and everything is fine

![image](https://user-images.githubusercontent.com/8519218/31264758-5a6baf8e-aa95-11e7-9eea-91ae49386a9e.png)

**Comment by reduz** [comment]
I have no idea what this is, but code for tilemap is her:
https://github.com/godotengine/godot/blob/master/scene/2d/tile_map.cpp

**Comment by Nibodhika** [comment]
Since I was just about to try to make an isometric prototype for fun this seems a great issue to tackle. I'll take a deeper look this weekend, but in case anyone is affected a quick review of the code and some tests show me that it happens on center oriented tilesets, so for anyone wanting to use the demo until the fix simply changing the tile orientation for the floor and wall objects from center to top left produces the correct rotation of tiles and collisions.

**Comment by akien-mga** [comment]
We now have two PRs for this one from @viprip and @Nibodhika. Can you each check both and see which one is better?

**Comment by Nibodhika** [comment]
As they are they're both very similar, however mine supposes the knowledge of the second parameter to ```tile_get_shape_transform```, also I removed a line that @viprip only commented. I'll readd it and add a function ```tile_get_shape_offset``` to mantain the same code format as the other stuff, i.e ```tile_get_navigation_polygon_offset```, also closer to what whas in 2.0 and contains the knowledge of how the offset is stored to ```TileSet```

**Comment by Nibodhika** [comment]
Done, now at least there's a reason to choose one branch or the other even if both do the same.

@viprip branch is more punctual and only fixes this issue, if the way maps are read will be changed in the future (as it seems to be implied by his commit message), then his branch is the best choice.

Mine reverts the existence of ```tile_get_shape_offset``` and ```tile_set_shape_offset``` to TileSet, if this functions shouldn't exist in later versions then this shouldn't be merged. However I feel that the knowledge that the offset is stored in the origin of the first shape's transform for a given id should be containd in only one place, unless of course as stated below if these way of storing it is only temporary and that would change in a later version.

**Comment by viprip** [comment]
Good Morning, everybody,

I tested @Nibodhika's work today and it is working as expected. You are free to close my MR in favour to @Nibodhika's MR, @akien-mga.

Best regards,
William
