### ISSUE TITLE
Not work rotated transform (Godot 3.0)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#11889]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04, Godot 3.0 Alpha 1

**Issue description:**
Not work rotated transform
```
	var transf = get_node('MeshInstance').get_global_transform()
	transf.rotated(Vector3(0, 1, 0), 45.0)
	get_node('MeshInstance').set_global_transform(transf)
```

**Link to minimal example project:**
[Bug transform rotated.zip](https://github.com/godotengine/godot/files/1363759/Bug.transform.rotated.zip)

**Comment by tagcup** [comment]
Rotated returns the rotated transform, it doesn't modify itself. Docs could be improved I guess

**Comment by groud** [comment]
you should do:
`transf = transf.rotated(Vector3(0, 1, 0), 45.0)`

Closing as this is more due to a misinterpretation of the API than an engine bug.

**Comment by DimaKiva** [comment]
Ok. Thanks
