### ISSUE TITLE
Signal connection editor - include signals parameters in the function when creating a new function

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#11880]
Some signals in godot can emit values when they are emitted. Those values are fed to the function that they can trigger in other nodes.

If those are not included in the parameters of the function that is triggered, the signal doesnt seem to trigger the function at all.

The signal connection editor can automatically create a function in a script. When it creates it however, it doesn't include any of the parameter values of the signal that emits it.

It would be a nice user friendly addition to godot's editor and gdscript if it could:
1. establish the signal's parameters when initializing it in gdscript
`signal mySignal ["param1","param2","param3"]`
or if you dont want to , you can still do:
`signal mySignal `
2. When the signal connection editor creates a new function, include those parameters in the function
`func _on_mySignal(param1,param2,param3):`

Apologies if this is in godot already, i cant seem to find it.

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by creikey** [comment]
@akien-mga Yes, just had this same issue. It seems like even if I add the extra argument to the function it auto generates, it still doesn't get called at all

**Comment by bojidar-bg** [comment]
Doesn't this work for point one?
```gdscript
signal x(a, b, c)
```

**Comment by DualMatrix** [comment]
Both of those things are currently present in master.

**Comment by akien-mga** [comment]
Fixed by #22163.
