### ISSUE TITLE
Mono commit crashes on build

### ISSUE THREAD

**Issue by NathanWarden** [godotengine/godot#11891]
@neikeq Starting with this commit, it seems to cause Godot to crash when trying to build b4d758e067f65de2f10d116efe0dbf682671317d

This is on Linux. I haven't checked Windows or macOS.

Here's a minimal project:
[NewGameProject.zip](https://github.com/godotengine/godot/files/1364020/NewGameProject.zip)

**Comment by neikeq** [comment]
Can you share the crash report?

**Comment by NathanWarden** [comment]
Sure :)

Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) GodotSharpTools.Build.BuildInstance.godot_icall_BuildInstance_get_MSBuildPath () [0x00006] in <bedcd693365c4526835d86783244de88>:0
  at GodotSharpTools.Build.BuildInstance.get_MSBuildPath () [0x00000] in /home/nathan/data/home_data/Projects/OpenSource/godot/modules/mono/editor/GodotSharpTools/Build/BuildSystem.cs:22
  at GodotSharpTools.Build.BuildInstance.Build (string,string,string[]) [0x0000a] in /home/nathan/data/home_data/Projects/OpenSource/godot/modules/mono/editor/GodotSharpTools/Build/BuildSystem.cs:45
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool__this___object_object_object (object,intptr,intptr,intptr) [0x0002c] in <bedcd693365c4526835d86783244de88>:0
/proc/self/maps:
40aaf000-40ab1000 r-xs 00000000 00:2c 96                                 /tmp/.gltjZelJ (deleted)
40d19000-40dba000 rw-p 00000000 00:00 0 
40dba000-40e2f000 rwxp 00000000 00:00 0 
412df000-412ef000 rwxp 00000000 00:00 0 
41a13000-41a23000 rwxp 00000000 00:00 0 
[... more useless stuff like this ...]
7ffe2f4e7000-7ffe2f4e9000 r--p 00000000 00:00 0                          [vvar]
7ffe2f4e9000-7ffe2f4eb000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Native stacktrace:

	/usr/lib/libmonosgen-2.0.so.1(+0xd3ed0) [0x7f0cfae85ed0]
	/usr/lib/libmonosgen-2.0.so.1(+0x13db01) [0x7f0cfaeefb01]
	/home/nathan/data/home_data/Projects/OpenSource/godot_no_mono/bin/godot.x11.tools.64(_ZN6String9copy_fromEPKc+0x48) [0x55c963b363b0]
	/home/nathan/data/home_data/Projects/OpenSource/godot_no_mono/bin/godot.x11.tools.64(_ZN6StringC1EPKc+0x30) [0x55c963b3a552]
	/home/nathan/data/home_data/Projects/OpenSource/godot_no_mono/bin/godot.x11.tools.64(_Z26_find_build_engine_on_unixRK6String+0x9a) [0x55c96264a678]
	/home/nathan/data/home_data/Projects/OpenSource/godot_no_mono/bin/godot.x11.tools.64(_Z41godot_icall_BuildInstance_get_MSBuildPathv+0xc8) [0x55c96264a824]
	[0x40e2590a]

Debug info from gdb:

(lldb) command source -s 0 '/tmp/mono-gdb-commands.2ILpGp'
Executing commands in '/tmp/mono-gdb-commands.2ILpGp'.
(lldb) process attach --pid 14619
Process 14619 stopped
* thread #1, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa799687 libpthread.so.0`__waitpid + 87
libpthread.so.0`__waitpid:
->  0x7f0cfa799687 <+87>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cfa79968d <+93>: ja     0x7f0cfa7996ba            ; <+138>
    0x7f0cfa79968f <+95>: movl   %r8d, %edi
    0x7f0cfa799692 <+98>: movl   %eax, (%rsp)
  thread #2, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54
libpthread.so.0`do_futex_wait.constprop.1:
->  0x7f0cfa797cc6 <+54>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cfa797ccc <+60>: ja     0x7f0cfa797ce0            ; <+80>
    0x7f0cfa797cce <+62>: movl   %ebp, %edi
    0x7f0cfa797cd0 <+64>: callq  0x7f0cfa798660            ; __pthread_disable_asynccancel
  thread #3, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54
libpthread.so.0`do_futex_wait.constprop.1:
->  0x7f0cfa797cc6 <+54>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cfa797ccc <+60>: ja     0x7f0cfa797ce0            ; <+80>
    0x7f0cfa797cce <+62>: movl   %ebp, %edi
    0x7f0cfa797cd0 <+64>: callq  0x7f0cfa798660            ; __pthread_disable_asynccancel
  thread #4, name = 'threaded-ml', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cf9bd2cbb libc.so.6`__GI___poll + 75
libc.so.6`__GI___poll:
->  0x7f0cf9bd2cbb <+75>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cf9bd2cc1 <+81>: ja     0x7f0cf9bd2cf2            ; <+130>
    0x7f0cf9bd2cc3 <+83>: movl   %r8d, %edi
    0x7f0cf9bd2cc6 <+86>: movl   %eax, 0x8(%rsp)
  thread #5, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa79538d libpthread.so.0`__pthread_cond_wait + 509
libpthread.so.0`__pthread_cond_wait:
->  0x7f0cfa79538d <+509>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cfa795393 <+515>: ja     0x7f0cfa7953e8            ; <+600>
    0x7f0cfa795395 <+517>: movl   %r8d, %edi
    0x7f0cfa795398 <+520>: callq  0x7f0cfa798660            ; __pthread_disable_asynccancel
  thread #6, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cf9bab190 libc.so.6`__GI___nanosleep + 64
libc.so.6`__GI___nanosleep:
->  0x7f0cf9bab190 <+64>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cf9bab196 <+70>: ja     0x7f0cf9bab1c2            ; <+114>
    0x7f0cf9bab198 <+72>: movl   %edx, %edi
    0x7f0cf9bab19a <+74>: movl   %eax, 0xc(%rsp)
  thread #7, name = 'SGen worker', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa79538d libpthread.so.0`__pthread_cond_wait + 509
libpthread.so.0`__pthread_cond_wait:
->  0x7f0cfa79538d <+509>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cfa795393 <+515>: ja     0x7f0cfa7953e8            ; <+600>
    0x7f0cfa795395 <+517>: movl   %r8d, %edi
    0x7f0cfa795398 <+520>: callq  0x7f0cfa798660            ; __pthread_disable_asynccancel
  thread #8, name = 'Finalizer', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54
libpthread.so.0`do_futex_wait.constprop.1:
->  0x7f0cfa797cc6 <+54>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cfa797ccc <+60>: ja     0x7f0cfa797ce0            ; <+80>
    0x7f0cfa797cce <+62>: movl   %ebp, %edi
    0x7f0cfa797cd0 <+64>: callq  0x7f0cfa798660            ; __pthread_disable_asynccancel
  thread #9, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa799230 libpthread.so.0`__GI___nanosleep + 64
libpthread.so.0`__GI___nanosleep:
->  0x7f0cfa799230 <+64>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cfa799236 <+70>: ja     0x7f0cfa799262            ; <+114>
    0x7f0cfa799238 <+72>: movl   %edx, %edi
    0x7f0cfa79923a <+74>: movl   %eax, 0xc(%rsp)
  thread #10, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54
libpthread.so.0`do_futex_wait.constprop.1:
->  0x7f0cfa797cc6 <+54>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cfa797ccc <+60>: ja     0x7f0cfa797ce0            ; <+80>
    0x7f0cfa797cce <+62>: movl   %ebp, %edi
    0x7f0cfa797cd0 <+64>: callq  0x7f0cfa798660            ; __pthread_disable_asynccancel
  thread #11, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa799230 libpthread.so.0`__GI___nanosleep + 64
libpthread.so.0`__GI___nanosleep:
->  0x7f0cfa799230 <+64>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7f0cfa799236 <+70>: ja     0x7f0cfa799262            ; <+114>
    0x7f0cfa799238 <+72>: movl   %edx, %edi
    0x7f0cfa79923a <+74>: movl   %eax, 0xc(%rsp)

Executable module set to "/home/nathan/data/home_data/Projects/OpenSource/godot_no_mono/bin/godot.x11.tools.64".
Architecture set to: x86_64--linux.
(lldb) thread list
Process 14619 stopped
* thread #1: tid = 14619, 0x00007f0cfa799687 libpthread.so.0`__waitpid + 87, name = 'godot.x11.tools', stop reason = signal SIGSTOP
  thread #2: tid = 14620, 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54, name = 'godot.x11.tools', stop reason = signal SIGSTOP
  thread #3: tid = 14622, 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54, name = 'godot.x11.tools', stop reason = signal SIGSTOP
  thread #4: tid = 14623, 0x00007f0cf9bd2cbb libc.so.6`__GI___poll + 75, name = 'threaded-ml', stop reason = signal SIGSTOP
  thread #5: tid = 14624, 0x00007f0cfa79538d libpthread.so.0`__pthread_cond_wait + 509, name = 'godot.x11.tools', stop reason = signal SIGSTOP
  thread #6: tid = 14625, 0x00007f0cf9bab190 libc.so.6`__GI___nanosleep + 64, name = 'godot.x11.tools', stop reason = signal SIGSTOP
  thread #7: tid = 14626, 0x00007f0cfa79538d libpthread.so.0`__pthread_cond_wait + 509, name = 'SGen worker', stop reason = signal SIGSTOP
  thread #8: tid = 14627, 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54, name = 'Finalizer', stop reason = signal SIGSTOP
  thread #9: tid = 14629, 0x00007f0cfa799230 libpthread.so.0`__GI___nanosleep + 64, name = 'godot.x11.tools', stop reason = signal SIGSTOP
  thread #10: tid = 14630, 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54, name = 'godot.x11.tools', stop reason = signal SIGSTOP
  thread #11: tid = 14631, 0x00007f0cfa799230 libpthread.so.0`__GI___nanosleep + 64, name = 'godot.x11.tools', stop reason = signal SIGSTOP
(lldb) thread backtrace all
* thread #1, name = 'godot.x11.tools', stop reason = signal SIGSTOP
  * frame #0: 0x00007f0cfa799687 libpthread.so.0`__waitpid + 87
    frame #1: 0x00007f0cfae85f87 libmonosgen-2.0.so.1`___lldb_unnamed_symbol748$$libmonosgen-2.0.so.1 + 615
    frame #2: 0x00007f0cfaeefb01 libmonosgen-2.0.so.1`___lldb_unnamed_symbol1284$$libmonosgen-2.0.so.1 + 209
    frame #3: 0x000055c963b363b0 godot.x11.tools.64`String::copy_from(this=0x00007ffe2f427750, p_cstr="") at ustring.cpp:107
    frame #4: 0x000055c963b3a552 godot.x11.tools.64`String::String(this=0x00007ffe2f427750, p_str="") at ustring.cpp:1500
    frame #5: 0x000055c96264a678 godot.x11.tools.64`_find_build_engine_on_unix(p_name=0x00007ffe2f427798) at godotsharp_builds.cpp:63
    frame #6: 0x000055c96264a824 godot.x11.tools.64`godot_icall_BuildInstance_get_MSBuildPath() at godotsharp_builds.cpp:115
    frame #7: 0x0000000040e2590a
    frame #8: 0x0000000040e2407d
    frame #9: 0x00007f0cfadedae7 libmonosgen-2.0.so.1`___lldb_unnamed_symbol244$$libmonosgen-2.0.so.1 + 1399
    frame #10: 0x00007f0cfafd8d90 libmonosgen-2.0.so.1`___lldb_unnamed_symbol3698$$libmonosgen-2.0.so.1 + 80
    frame #11: 0x00007f0cfafe3f31 libmonosgen-2.0.so.1`___lldb_unnamed_symbol3821$$libmonosgen-2.0.so.1 + 897
    frame #12: 0x00007f0cfafe43eb libmonosgen-2.0.so.1`mono_runtime_invoke_array + 43
    frame #13: 0x000055c96261d3b9 godot.x11.tools.64`GDMonoMethod::invoke(this=0x000055c969a132c0, p_object=0x00007f0cdb853fd0, p_params=0x00007ffe2f428020, r_exc=0x00007ffe2f427f10) at gd_mono_method.cpp:86
    frame #14: 0x000055c96264d308 godot.x11.tools.64`GodotSharpBuilds::BuildProcess::start(this=0x00007ffe2f428080, p_blocking=true) at godotsharp_builds.cpp:451
    frame #15: 0x000055c96264c57e godot.x11.tools.64`GodotSharpBuilds::build(this=0x000055c96c7bee40, p_build_info=0x00007ffe2f428130) at godotsharp_builds.cpp:325
    frame #16: 0x000055c96264acae godot.x11.tools.64`GodotSharpBuilds::build_api_sln(p_name=0x00007ffe2f428190, p_api_sln_dir=0x00007ffe2f4281b8, p_config=0x00007ffe2f428198) at godotsharp_builds.cpp:158
    frame #17: 0x000055c96264bac5 godot.x11.tools.64`GodotSharpBuilds::make_api_sln(p_api_type=API_CORE) at godotsharp_builds.cpp:243
    frame #18: 0x000055c96264c1b0 godot.x11.tools.64`godotsharp_build_callback() at godotsharp_builds.cpp:277
    frame #19: 0x000055c962ba1c3a godot.x11.tools.64`EditorNode::_call_build(this=0x000055c96811c970) at editor_node.cpp:4368
    frame #20: 0x000055c962b8b4fb godot.x11.tools.64`EditorNode::_run(this=0x000055c96811c970, p_current=true, p_custom=0x00007ffe2f428520) at editor_node.cpp:1708
    frame #21: 0x000055c962b8f7ee godot.x11.tools.64`EditorNode::_menu_option_confirm(this=0x000055c96811c970, p_option=40, p_confirmed=false) at editor_node.cpp:2216
    frame #22: 0x000055c962b82395 godot.x11.tools.64`EditorNode::_menu_option(this=0x000055c96811c970, p_option=40) at editor_node.cpp:627
    frame #23: 0x000055c9625f0236 godot.x11.tools.64`MethodBind1<int>::call(this=0x000055c96c7c5b90, p_object=0x000055c96811c970, p_args=0x000055c96eb3a6f0, p_arg_count=1, r_error=0x00007ffe2f428850) at method_bind.gen.inc:729
    frame #24: 0x000055c963af14e1 godot.x11.tools.64`Object::call(this=0x000055c96811c970, p_method=0x000055c967f383c8, p_args=0x000055c96eb3a6f0, p_argcount=1, r_error=0x00007ffe2f428850) at object.cpp:839
    frame #25: 0x000055c963af2e87 godot.x11.tools.64`Object::emit_signal(this=0x000055c96a1b0b80, p_name=0x00007ffe2f428968, p_args=0x00007ffe2f428900, p_argcount=0) at object.cpp:1120
    frame #26: 0x000055c963af341a godot.x11.tools.64`Object::emit_signal(this=0x000055c96a1b0b80, p_name=0x00007ffe2f428968, p_arg1=0x00007ffe2f428970, p_arg2=0x00007ffe2f428990, p_arg3=0x00007ffe2f4289b0, p_arg4=0x00007ffe2f4289d0, p_arg5=0x00007ffe2f4289f0) at object.cpp:1165
    frame #27: 0x000055c96312efe1 godot.x11.tools.64`BaseButton::_unhandled_input(this=0x000055c96a1b0b80, p_event=Ref<InputEvent> @ 0x00007ffe2f428a70) at base_button.cpp:445
    frame #28: 0x000055c962b29aec godot.x11.tools.64`MethodBind1<Ref<InputEvent> >::call(this=0x000055c9662b5160, p_object=0x000055c96a1b0b80, p_args=0x00007ffe2f428ba8, p_arg_count=1, r_error=0x00007ffe2f428b00) at method_bind.gen.inc:729
    frame #29: 0x000055c963af07ad godot.x11.tools.64`Object::call_multilevel(this=0x000055c96a1b0b80, p_method=0x00007ffe2f428c00, p_args=0x00007ffe2f428ba8, p_argcount=1) at object.cpp:673
    frame #30: 0x000055c9630dabd6 godot.x11.tools.64`SceneTree::_call_input_pause(this=0x000055c9668b2b90, p_group=0x000055c9668d1538, p_method=0x00007ffe2f428c00, p_input=0x00007ffe2f428c40) at scene_tree.cpp:873
    frame #31: 0x000055c96310b38c godot.x11.tools.64`Viewport::unhandled_input(this=0x000055c9668d11c0, p_event=0x00007ffe2f428c40) at viewport.cpp:2383
    frame #32: 0x000055c96310594d godot.x11.tools.64`Viewport::_vp_unhandled_input(this=0x000055c9668d11c0, p_ev=0x00007ffe2f428cc0) at viewport.cpp:1331
    frame #33: 0x000055c962782db8 godot.x11.tools.64`MethodBind1<Ref<InputEvent> const&>::call(this=0x000055c96627a030, p_object=0x000055c9668d11c0, p_args=0x00007ffe2f428e30, p_arg_count=1, r_error=0x00007ffe2f428e24) at method_bind.gen.inc:729
    frame #34: 0x000055c963af14e1 godot.x11.tools.64`Object::call(this=0x000055c9668d11c0, p_method=0x00007ffe2f428fc8, p_args=0x00007ffe2f428e30, p_argcount=1, r_error=0x00007ffe2f428e24) at object.cpp:839
    frame #35: 0x000055c963af0fe2 godot.x11.tools.64`Object::call(this=0x000055c9668d11c0, p_name=0x00007ffe2f428fc8, p_arg1=0x00007ffe2f428fd0, p_arg2=0x00007ffe2f428ff0, p_arg3=0x00007ffe2f429010, p_arg4=0x00007ffe2f429030, p_arg5=0x00007ffe2f429050) at object.cpp:763
    frame #36: 0x000055c9630d7121 godot.x11.tools.64`SceneTree::call_group_flags(this=0x000055c9668b2b90, p_call_flags=2, p_group=0x00007ffe2f428fc0, p_function=0x00007ffe2f428fc8, p_arg1=0x00007ffe2f428fd0, p_arg2=0x00007ffe2f428ff0, p_arg3=0x00007ffe2f429010, p_arg4=0x00007ffe2f429030, p_arg5=0x00007ffe2f429050) at scene_tree.cpp:241
    frame #37: 0x000055c9630d8163 godot.x11.tools.64`SceneTree::input_event(this=0x000055c9668b2b90, p_event=0x00007ffe2f429190) at scene_tree.cpp:415
    frame #38: 0x000055c9624e7087 godot.x11.tools.64`InputDefault::parse_input_event(this=0x000055c9656ea350, p_event=0x00007ffe2f429190) at input_default.cpp:336
    frame #39: 0x000055c9624d8d42 godot.x11.tools.64`OS_X11::handle_key_event(this=0x00007ffe2f4297c0, p_event=0x00007ffe2f429510, p_echo=false) at os_x11.cpp:1366
    frame #40: 0x000055c9624da197 godot.x11.tools.64`OS_X11::process_xevents(this=0x00007ffe2f4297c0) at os_x11.cpp:1662
    frame #41: 0x000055c9624dc4a1 godot.x11.tools.64`OS_X11::run(this=0x00007ffe2f4297c0) at os_x11.cpp:2112
    frame #42: 0x000055c9624d237f godot.x11.tools.64`main(argc=4, argv=0x00007ffe2f429c98) at godot_x11.cpp:54
    frame #43: 0x00007f0cf9b07f6a libc.so.6`__libc_start_main + 234
    frame #44: 0x000055c9624d21ca godot.x11.tools.64`_start + 42
  thread #2, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54
    frame #1: 0x00007f0cfa797db8 libpthread.so.0`__new_sem_wait_slow.constprop.0 + 152
    frame #2: 0x000055c962a3d7a0 godot.x11.tools.64`SemaphorePosix::wait(this=0x000055c9652702c0) at semaphore_posix.cpp:40
    frame #3: 0x000055c963c40c1c godot.x11.tools.64`_IP_ResolverPrivate::_thread_function(self=0x000055c96526fd20) at ip.cpp:99
    frame #4: 0x000055c962a41236 godot.x11.tools.64`ThreadPosix::thread_callback(userdata=0x000055c965270300) at thread_posix.cpp:69
    frame #5: 0x00007f0cfa78f08a libpthread.so.0`start_thread + 218
    frame #6: 0x00007f0cf9bdd1bf libc.so.6`__GI___clone + 63
  thread #3, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54
    frame #1: 0x00007f0cfa797db8 libpthread.so.0`__new_sem_wait_slow.constprop.0 + 152
    frame #2: 0x000055c962a3d7a0 godot.x11.tools.64`SemaphorePosix::wait(this=0x000055c9655ecba0) at semaphore_posix.cpp:40
    frame #3: 0x000055c96394608d godot.x11.tools.64`VisualServerScene::_gi_probe_bake_thread(this=0x00007f0cf2e46020) at visual_server_scene.cpp:2001
    frame #4: 0x000055c963944ca0 godot.x11.tools.64`VisualServerScene::_gi_probe_bake_threads(self=0x00007f0cf2e46020) at visual_server_scene.cpp:1786
    frame #5: 0x000055c962a41236 godot.x11.tools.64`ThreadPosix::thread_callback(userdata=0x000055c9652b6dc0) at thread_posix.cpp:69
    frame #6: 0x00007f0cfa78f08a libpthread.so.0`start_thread + 218
    frame #7: 0x00007f0cf9bdd1bf libc.so.6`__GI___clone + 63
  thread #4, name = 'threaded-ml', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cf9bd2cbb libc.so.6`__GI___poll + 75
    frame #1: 0x00007f0cfb893773 libpulse.so.0`___lldb_unnamed_symbol111$$libpulse.so.0 + 51
    frame #2: 0x00007f0cfb884bd0 libpulse.so.0`pa_mainloop_poll + 224
    frame #3: 0x00007f0cfb885271 libpulse.so.0`pa_mainloop_iterate + 81
    frame #4: 0x00007f0cfb885301 libpulse.so.0`pa_mainloop_run + 33
    frame #5: 0x00007f0cfb8936ae libpulse.so.0`___lldb_unnamed_symbol110$$libpulse.so.0 + 110
    frame #6: 0x00007f0cf8bc481c libpulsecommon-11.1.so`___lldb_unnamed_symbol133$$libpulsecommon-11.1.so + 92
    frame #7: 0x00007f0cfa78f08a libpthread.so.0`start_thread + 218
    frame #8: 0x00007f0cf9bdd1bf libc.so.6`__GI___clone + 63
  thread #5, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa79538d libpthread.so.0`__pthread_cond_wait + 509
    frame #1: 0x00007f0cfb893d89 libpulse.so.0`pa_threaded_mainloop_wait + 41
    frame #2: 0x00007f0cfbab2ae7 libpulse-simple.so.0`pa_simple_write + 199
    frame #3: 0x000055c9629cc52d godot.x11.tools.64`AudioDriverPulseAudio::thread_func(p_udata=0x00007ffe2f429b00) at audio_driver_pulseaudio.cpp:257
    frame #4: 0x000055c962a41236 godot.x11.tools.64`ThreadPosix::thread_callback(userdata=0x000055c9656b4a40) at thread_posix.cpp:69
    frame #5: 0x00007f0cfa78f08a libpthread.so.0`start_thread + 218
    frame #6: 0x00007f0cf9bdd1bf libc.so.6`__GI___clone + 63
  thread #6, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cf9bab190 libc.so.6`__GI___nanosleep + 64
    frame #1: 0x00007f0cf9bd5404 libc.so.6`usleep + 68
    frame #2: 0x000055c9624e0a90 godot.x11.tools.64`JoypadLinux::monitor_joypads(this=0x000055c9660e6310) at joypad_linux.cpp:217
    frame #3: 0x000055c9624e09b4 godot.x11.tools.64`JoypadLinux::run_joypad_thread(this=0x000055c9660e6310) at joypad_linux.cpp:115
    frame #4: 0x000055c9624e0997 godot.x11.tools.64`JoypadLinux::joy_thread_func(p_user=0x000055c9660e6310) at joypad_linux.cpp:102
    frame #5: 0x000055c962a41236 godot.x11.tools.64`ThreadPosix::thread_callback(userdata=0x000055c9660b40d0) at thread_posix.cpp:69
    frame #6: 0x00007f0cfa78f08a libpthread.so.0`start_thread + 218
    frame #7: 0x00007f0cf9bdd1bf libc.so.6`__GI___clone + 63
  thread #7, name = 'SGen worker', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa79538d libpthread.so.0`__pthread_cond_wait + 509
    frame #1: 0x00007f0cfb046964 libmonosgen-2.0.so.1`___lldb_unnamed_symbol4818$$libmonosgen-2.0.so.1 + 900
    frame #2: 0x00007f0cfa78f08a libpthread.so.0`start_thread + 218
    frame #3: 0x00007f0cf9bdd1bf libc.so.6`__GI___clone + 63
  thread #8, name = 'Finalizer', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54
    frame #1: 0x00007f0cfa797db8 libpthread.so.0`__new_sem_wait_slow.constprop.0 + 152
    frame #2: 0x00007f0cfafce601 libmonosgen-2.0.so.1`___lldb_unnamed_symbol3638$$libmonosgen-2.0.so.1 + 833
    frame #3: 0x00007f0cfafa4469 libmonosgen-2.0.so.1`___lldb_unnamed_symbol3271$$libmonosgen-2.0.so.1 + 345
    frame #4: 0x00007f0cfb05d3e9 libmonosgen-2.0.so.1`___lldb_unnamed_symbol5076$$libmonosgen-2.0.so.1 + 201
    frame #5: 0x00007f0cfa78f08a libpthread.so.0`start_thread + 218
    frame #6: 0x00007f0cf9bdd1bf libc.so.6`__GI___clone + 63
  thread #9, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa799230 libpthread.so.0`__GI___nanosleep + 64
    frame #1: 0x000055c9629c643b godot.x11.tools.64`OS_Unix::delay_usec(this=0x00007ffe2f4297c0, p_usec=1000) const at os_unix.cpp:274
    frame #2: 0x000055c963015a69 godot.x11.tools.64`EditorExportAndroid::_device_poll_thread(ud=0x000055c9689c66d0) at export.cpp:346
    frame #3: 0x000055c962a41236 godot.x11.tools.64`ThreadPosix::thread_callback(userdata=0x000055c968991650) at thread_posix.cpp:69
    frame #4: 0x00007f0cfa78f08a libpthread.so.0`start_thread + 218
    frame #5: 0x00007f0cf9bdd1bf libc.so.6`__GI___clone + 63
  thread #10, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa797cc6 libpthread.so.0`do_futex_wait.constprop.1 + 54
    frame #1: 0x00007f0cfa797db8 libpthread.so.0`__new_sem_wait_slow.constprop.0 + 152
    frame #2: 0x000055c962a3d7a0 godot.x11.tools.64`SemaphorePosix::wait(this=0x000055c969ae1ce0) at semaphore_posix.cpp:40
    frame #3: 0x000055c962aa9d03 godot.x11.tools.64`EditorResourcePreview::_thread(this=0x000055c968bd4ca0) at editor_resource_preview.cpp:171
    frame #4: 0x000055c962aa9274 godot.x11.tools.64`EditorResourcePreview::_thread_func(ud=0x000055c968bd4ca0) at editor_resource_preview.cpp:84
    frame #5: 0x000055c962a41236 godot.x11.tools.64`ThreadPosix::thread_callback(userdata=0x000055c9689bc2a0) at thread_posix.cpp:69
    frame #6: 0x00007f0cfa78f08a libpthread.so.0`start_thread + 218
    frame #7: 0x00007f0cf9bdd1bf libc.so.6`__GI___clone + 63
  thread #11, name = 'godot.x11.tools', stop reason = signal SIGSTOP
    frame #0: 0x00007f0cfa799230 libpthread.so.0`__GI___nanosleep + 64
    frame #1: 0x000055c9629c643b godot.x11.tools.64`OS_Unix::delay_usec(this=0x00007ffe2f4297c0, p_usec=100000) const at os_unix.cpp:274
    frame #2: 0x000055c962c7254c godot.x11.tools.64`EditorFileServer::_thread_start(s=0x000055c969a34560) at editor_file_server.cpp:309
    frame #3: 0x000055c962a41236 godot.x11.tools.64`ThreadPosix::thread_callback(userdata=0x000055c96aa63c50) at thread_posix.cpp:69
    frame #4: 0x00007f0cfa78f08a libpthread.so.0`start_thread + 218
    frame #5: 0x00007f0cf9bdd1bf libc.so.6`__GI___clone + 63
(lldb) detach
(lldb) quit
Process 14619 detached

Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

**Comment by NathanWarden** [comment]
@neikeq Thanks, everything seems to be working great again.
