### ISSUE TITLE
"Frame" option in AnimatedSprite's Inspector draws a line in the entire editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11898]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor/2017-10-06.bb9f4b5) bb9f4b5

**Issue description:**
When selecting the "Frame" option in the AnimatedSprite's Inspector, a line covering the entire editor is drawn:

![screenshot at 2017-10-06 20-03-31](https://user-images.githubusercontent.com/30739239/31303010-55228f28-aadd-11e7-9221-ec4f13ea1bc9.png)

**Comment by hi-ogawa** [comment]
This seems because of `HSlider` with minimum 0 and maximum 0 causing `Range::get_as_ratio` to be NAN from division by zero. This happens when selected animation consists of only single frame.
I'll provide a PR for fixing this.
