### ISSUE TITLE
Scons w/ Python3 fails in osx's detect.py

### ISSUE THREAD

**Issue by N0hbdy** [godotengine/godot#11903]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OSX, Godot version master (195b122)

**Issue description:**
Running the compile for osx runs into an error due to legacy usage of `has_key` which no longer exists in python3.

**Steps to reproduce:**
Using python 3.X (I used `Python 3.6.0 :: Anaconda 4.3.1 (x86_64)`)
`scons platform=osx`

**Link to minimal example project:**
N/A

**Comment by akien-mga** [comment]
Fixed by #11904.
