### ISSUE TITLE
Shader language supports only two custom varying types

### ISSUE THREAD

**Issue by sanikoyes** [godotengine/godot#1191]
Current builtin shader language does not support varying types, custom varying types is very useful for some complex shader effect, likes blur/shadow/ etc...
Whether there are plans to add support for varying types support in shader language?

**Comment by okamstudio** [comment]
there are 2 built-in varyings, VAR1 and VAR2, more will likely be added
since it's not much. Limitation was because GLES2 hardware is pretty shitty

On Mon, Jan 12, 2015 at 12:42 PM, Saniko <notifications@github.com> wrote:

> Current builtin shader language does not support varying types, custom
> varying types is very useful for some complex shader effect, likes
> blur/shadow/ etc...
> Whether there are plans to add support for varying types support in shader
> language?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1191>.
>



-- 

*OkamStudio*

**Comment by sanikoyes** [comment]
In this case:
uniform float u_radius;
varying vec2 v_blurTexCoords[14];

void main()
{
    gl_Position = CC_MVPMatrix * a_position;
	v_fragmentColor = a_color;
	v_texCoord = a_texCoord;
	for (int i = 0; i < 7; ++i) {
		vec2 c = vec2(u_radius / 7.0*(7.0 - float(i)), 0.0);
		v_blurTexCoords[i] = v_texCoord - c;
		v_blurTexCoords[13 - i] = v_texCoord + c;
	}
}
i don't know how to share v_blurTexCoords to frag shader, if move these code to frag shader would be very low benchmarks...

**Comment by marcosbitetti** [comment]
vertex shader:
VAR1 = vec4( val 1, val2, 0 /* if not used */, 0 );

in fragmente just use VAR1

The shader can have texture coords in UV and UV2, why you use 14 samples?

**Comment by okamstudio** [comment]
the probably is that this will not work in most mobile devices or low end
PCs, which limit varyings to 8, 12 or at much 16.

When the GLES3 renderer is implemented, a new shader profile will be added
raising the limits and adding new datatypes, but will only work on devices
that support it

On Mon, Jan 12, 2015 at 12:52 PM, Saniko <notifications@github.com> wrote:

> In this case:
> uniform float u_radius;
> varying vec2 v_blurTexCoords[14];
>
> void main()
> {
> gl_Position = CC_MVPMatrix * a_position;
> v_fragmentColor = a_color;
> v_texCoord = a_texCoord;
> for (int i = 0; i < 7; ++i) {
> vec2 c = vec2(u_radius / 7.0*(7.0 - float(i)), 0.0);
> v_blurTexCoords[i] = v_texCoord - c;
> v_blurTexCoords[13 - i] = v_texCoord + c;
> }
> }
> i don't know how to share v_blurTexCoords to frag shader, if move these
> code to frag shader would be very low benchmarks...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1191#issuecomment-69590741>.
>



-- 

*OkamStudio*

**Comment by okamstudio** [comment]
using many varyings is also really inefficient on mobile devices, because
it forces them to use more temporal memory (due to the TBDR architecture)
for every triangle. In general, this stuff will work best on the fragment
program directly, as the main limiting factor for their performance is
bandwidth anyway, not execution time


On Mon, Jan 12, 2015 at 1:01 PM, Juan Linietsky <juan@okamstudio.com> wrote:

> the probably is that this will not work in most mobile devices or low end
> PCs, which limit varyings to 8, 12 or at much 16.
>
> When the GLES3 renderer is implemented, a new shader profile will be added
> raising the limits and adding new datatypes, but will only work on devices
> that support it
>
> On Mon, Jan 12, 2015 at 12:52 PM, Saniko <notifications@github.com> wrote:
>
>> In this case:
>> uniform float u_radius;
>> varying vec2 v_blurTexCoords[14];
>>
>> void main()
>> {
>> gl_Position = CC_MVPMatrix * a_position;
>> v_fragmentColor = a_color;
>> v_texCoord = a_texCoord;
>> for (int i = 0; i < 7; ++i) {
>> vec2 c = vec2(u_radius / 7.0*(7.0 - float(i)), 0.0);
>> v_blurTexCoords[i] = v_texCoord - c;
>> v_blurTexCoords[13 - i] = v_texCoord + c;
>> }
>> }
>> i don't know how to share v_blurTexCoords to frag shader, if move these
>> code to frag shader would be very low benchmarks...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/okamstudio/godot/issues/1191#issuecomment-69590741>.
>>
>
>
>
> --
>
> *OkamStudio*
>



-- 

*OkamStudio*

**Comment by sanikoyes** [comment]
Ok,  i would trying to rewrite this shader.

**Comment by akien-mga** [comment]
Fixed in 3.0 AFAIK.
