### ISSUE TITLE
Tutorial scene needs updating or there is a bug in the editor

### ISSUE THREAD

**Issue by Tiger-Coding** [godotengine/godot#1193]
I was working on a Mac for the page /wiki/tutorial_scene page.  After the hello.scn is saved, and play is pressed, it gives me an error saying I must select the main scene first.  So I searched and selected the main scene from the scene->project settings dialog to make it run.  But then farther down the page it says to do this, implying that the main scene selection isn't needed.

This is confusing and needs to be updated because many new users may quit at this error.  I was going to make the change in the wiki myself, but I'm not sure if there is a bug in the build I have.

I'm using v1.0.stable.custom_build

**Comment by akien-mga** [comment]
The "tutorial scene" mentions first the "Play Scene" button and not the main "Run" button:

![playscene](https://cloud.githubusercontent.com/assets/4701338/10994975/eabe0cce-8479-11e5-9b2a-957d3b5e88c2.png)

It's only the latter which requires main scene configuration as described later on in the tutorial.
