### ISSUE TITLE
Mono: GetNode() yields "Deleted object"

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#11931]
Calling GetNode() on the instance of an existing object (with a C# script attached) yields a null object.

[monotest.zip](https://github.com/godotengine/godot/files/1366626/monotest.zip)

**Comment by khairul169** [comment]
Don't know why, but although printing the player variable print [Deleted Object].. it is not null and the method can be accessed from other script..

![screenshot 5](https://user-images.githubusercontent.com/10296472/31314094-a0f3625c-ac21-11e7-919c-00cba3293b93.png)

**Comment by tagcup** [comment]
Interesting, it seems the real reason this crash is happening is due to a call to Navigation::GetSimplePath().

Whenever I have this line, it crashes:
`Vector3[] path = nav.GetSimplePath(player.GlobalTransform.origin, target);`
