### ISSUE TITLE
No specularity from any type of light, material roughness seems like 100% regardless of parameter or texture map

### ISSUE THREAD

**Issue by phyffer** [godotengine/godot#11935]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot v3 0fb221b
Tested on Windows 7 Radeon 5500, Windows 7 Gtx 970M and Linux Mint Gtx 970M

**Issue description:**
Doing a quick visdev and my model was showing great prior to a pull on October 6th 2017. But afterwards it's as if the roughness just scaled up to 100% all the time. Values from parameter and texture channels have little effect.
 
Changing the roughness only affects reflectivity of environment on the object, but not how the light bounces off the material.

My apologies, I do not know in what specific commit this began to happen.

![godot_1](https://user-images.githubusercontent.com/17959437/31315984-a9204ac4-abd8-11e7-9d27-94b5b43155f6.jpg)

In the screenshot below, I changed the diffuse to lambert and specular to blinn, and played around with the settings on roughness, and specularity a bit to see if I did anything wrong. I got a close result, but notice the parameter of roughness at 1.0, also the distribution of roughness is even on the model despite the roughness texture:
![godot_2](https://user-images.githubusercontent.com/17959437/31315914-6a2f63a0-abd7-11e7-9bc4-397498021ef9.jpg)

I am noticing this with other models. It might just be a fools error :( 

Possibly related to issue : https://github.com/godotengine/godot/issues/10250

**Steps to reproduce:**
I did an empty scene with a meshinstance->sphere
Material with Roughness parameter at 0
Happens to all lights OmniLight, Directional and spot. 

**Link to minimal example project:**
[specularityroughness.zip](https://github.com/godotengine/godot/files/1366780/specularityroughness.zip) <- Basic project
The Human character project size is quite big if .imports are included, if you would like the zip just respond here~
[SpecularityIssue.zip](https://github.com/godotengine/godot/files/1366811/SpecularityIssue.zip)

Thank you! :)

**Comment by akien-mga** [comment]
CC @tagcup @hi-ogawa who did changes around that time + @reduz.

**Comment by hi-ogawa** [comment]
I think I found the reason.
This changes https://github.com/godotengine/godot/pull/11700/files assumed conditional `SPECULAR_SCHLICK_GGX` will be turned on when render_mode is specular_schlick_ggx, but it seems this conditional SPECULAR_SCHLICK_GGX wasn't even existed before that.
So, at this point now, render_mode specular_schlick_ggx does nothing in shader.
I made up PR for fix. Please take a look at it.

**Comment by tagcup** [comment]
Ah yeah it was in a else statement and just rearranged stuff at last minute. Thanks fir spotting this!

**Comment by rubenjavier** [comment]
@akien-mga @hi-ogawa 
This is maked as fixed, but is still happening on the directional light as of commit 4fb5b1a21186bfc96aaa724e8e19afb44332dd8b

**Comment by phyffer** [comment]
Can also confirm this issue for the directional lights
