### ISSUE TITLE
It's not possible to move text back with the cursor in LineEdit

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11948]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor) 7eecfcb

**Issue description:**
While you can make the text move forward, you have to use the keyboard to move it backwards:
![video](https://user-images.githubusercontent.com/30739239/31341685-a57979d2-ace0-11e7-874e-c5ef5ba52b1f.gif)

**Comment by bojidar-bg** [comment]
`.gif` URL is "invalid or expired", can you try uploading the image to GitHub directly?

**Comment by YeldhamDev** [comment]
@bojidar-bg Sorry, fixed.
