### ISSUE TITLE
Let node set the Z Values of its children

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#1194]
After testing the z_value of nodes I think it would make sense to offer a checkbox which lets 
a node also set the z value of its children.
I think at that same point maybe a checkbox for child nodes ignore the parents z value.
This will give a quick opportunity to set the z values of many nodes whithout going through each single node.

So in conclusion. I think 2 checkboxes would be nice.
- set child z
- ignore parent z

**Comment by mamarilmanson** [comment]
why not a checkbox that says "inherit parent z"?

**Comment by reduz** [comment]
added that today

**Comment by adolson** [comment]
So this can be closed
