### ISSUE TITLE
Unable to end script file with function that only has pass.

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot#1195]
Unable to have a placeholder function that just has pass in it as the last line of a script file. Adding an enter to the end of the file makes the invalid error message go away.

**Comment by akien-mga** [comment]
It seems to work fine in the current master branch. I made sure to have no newline at the end of the a file in my project, and had no issue:

```
@@ -92,3 +92,8 @@ func _ready():
        
        get_node("Settings/NbLives/Slider").set_value(global.nb_lives)
        get_node("Settings/NbLives/Label").set_text("Lives: " + str(global.nb_lives))
+       
+       empty()
+
+func empty():
+       pass
\ No newline at end of file
```
