### ISSUE TITLE
Mono: Provide a friendly way to declare custom signals

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11956]
To mirror [this issue](https://github.com/neikeq/GodotSharp/issues/5) here, ~~at some point this was possible through `add_user_signal` but that function has been removed, and AFAIK there is no alternative way to define a signal.~~

**Comment by neikeq** [comment]
IINW `add_user_signal` is still there. I have in mind an idea for declaring signals in a more friendly way, I'll try to implement it after alpha2.

**Comment by tagcup** [comment]
Ah, sorry, I missed that because grepping add_user_signal on a freshly cloned repo doesn't give anything, but that's apparently because this is generated.

**Comment by neikeq** [comment]
I'll re-open this issue and rename it.

**Comment by akien-mga** [comment]
@neikeq Do you want to keep this on the 3.0 milestone or move to 3.1?

**Comment by neikeq** [comment]
Moving to 3.1. I still couldn't come up with a solution that I like.

**Comment by neikeq** [comment]
Yeah, not 2.1...

**Comment by exts** [comment]
@akien-mga we can close this. C# uses `[Signal]` annotation now.
