### ISSUE TITLE
VisualScript: editor hangs using "In" operator

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#11969]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mac OS, 3.0 build bf12b45

**Issue description:**
Adding or selecting the "In" operator node hangs the editor and results in the following node:

![screen shot 2017-10-09 at 8 58 49 am](https://user-images.githubusercontent.com/3812514/31347133-2acc5d68-acd0-11e7-8659-8304a6de1933.png)

**Steps to reproduce:**
Drag an "In" node from the "Available Nodes" tab or select an existing VisualScriptOperator node and choose "In" in the Operator field of the Inspector. 

The pictured node appears and the editor becomes slow and/or unresponsive.

**Comment by Adinimys** [comment]
Ok I found the issue. There was no string to name what this node does. It should be "A in B", right ?

**Comment by Adinimys** [comment]
So I'm not sure about the way github works but shouldn't this issue be closed now that the fix has been merged to the master branch ?

**Comment by Noshyaar** [comment]
Fixed by #12100
