### ISSUE TITLE
export (float,min,max) clamps float to int

### ISSUE THREAD

**Issue by unbu** [godotengine/godot#11964]
This issue: #539 still happens in godot 2.1.4.

Code that I am using is:
export(float, -100, 100) var variable = 0.0
in inspector any number given is then rounded to int.

In future should I comment on closed issue instead opening new one?

**Comment by Zylann** [comment]
Is it because the min and max are specified without `.0` ?

**Comment by unbu** [comment]
Good idea, however it didn't work.
But even if it did, that would still be unexpected behaviour since I used float as the variable type.

**Comment by bojidar-bg** [comment]
I guess it is because the default step is somehow "1" when using just a range?
Try giving a third number (around `0.01`) to specify the step.

**Comment by unbu** [comment]
Yeah that was the issue, it's just the interface that has wrong step. Maybe this could be default step in range when using float.

**Comment by bojidar-bg** [comment]
Sounds like an easy thing to do, here are some lines that would have to be changed:
https://github.com/godotengine/godot/blob/bf12b459864f89d056588c67cd90d0578681146b/editor/property_editor.cpp#L373-L379
https://github.com/godotengine/godot/blob/bf12b459864f89d056588c67cd90d0578681146b/editor/property_editor.cpp#L3032-L3035

**Comment by minifigmaster125** [comment]
anybody mind if I take this one? Would be my first venture into godot. Is there a way I'm suppose to "reserve" this bug, or is just getting the PR up and referencing this issue enough?

**Comment by bojidar-bg** [comment]
No, GitHub does not allow us to "assign" people outside the organisation for a given issue, sadly. Commenting or even making a PR is enough to "reserve" it though.
