### ISSUE TITLE
Editor Settings -> Mono is very broken in a non-Mono-enabled build

### ISSUE THREAD

**Issue by RiverMesa** [godotengine/godot#11976]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux 64-bit, latest @Calinou build (https://bintray.com/calinou/godot/editor/_latestVersion#files), specifically without Mono support.

**Issue description:**
In a Godot version that's built without Mono support, the Editor Settings section for Mono (Builds & Editor) is very...broken. The fields are plain numerical counters instead of proper drop-down menus, and sometimes just straight up disappear (see screenshots).

This may be obvious, that you can't do anything Mono-related if the engine isn't built with support for it, but those settings tabs should either be entirely absent while working in a non-Mono build, or "look like it works", but with a warning that it will have no effect because of lack of Mono support for one's current build.

(I'd also argue that said settings should be in a bit more easily-accessible location since right now it's a bit non-obvious, but that's beyond the scope of this issue.)

**Steps to reproduce:**
1. Download or build a version of Godot 3.0 that does not have the Mono module enabled.
2. Create a new/Open existing project.
3. Go to Editor -> Editor Settings -> Mono -> Builds/Editor.
4. Enjoy the madness trying to adjust the settings.

![image](https://user-images.githubusercontent.com/14968217/31357682-075edfea-ad43-11e7-9568-7fbd39734472.png)
![image](https://user-images.githubusercontent.com/14968217/31357686-0c05c46e-ad43-11e7-8cb6-63f232950a34.png)

**Comment by neikeq** [comment]
I don't think this is possible right now. The hint to display it as an enum is a runtime thing. hence it needs the module, and IINW the editor settings will display all the saved settings.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by neikeq** [comment]
Not sure if there can be any solution to this...

**Comment by akien-mga** [comment]
There's indeed no proper solution to this, but #22099 could be a good UX improvement. Closing as #22099 is more generic but also covers this case.
