### ISSUE TITLE
NavigationPolygonInstance crash with Sprite parent (Godot 3)

### ISSUE THREAD

**Issue by davismiculis** [godotengine/godot#11975]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS Sierra 10.12.6
Godot v3.0.alpha.custom_build.ae94758

**Issue description:**
Adding `NavigationPolygonInstance` node without a parent `Navigation2D` under `Sprite` freezes Godot (only force quit works).

I've only seen this behaviour if its under `Sprite` node, maybe other nodes crash it too.

**Steps to reproduce:**
Create blank Godot 3 project. Add following nodes:

Non-working:
```
Sprite
 - NavigationPolygonInstance (crashes)
```

Working:
```
Sprite
- Navigation2D
- - NavigationPolygonInstance
```

**Link to minimal example project:**
[TEST.zip](https://github.com/godotengine/godot/files/1369661/TEST.zip)

**Comment by vnen** [comment]
Doesn't need to be a Sprite, I got this with a Node2D.

**Comment by Adinimys** [comment]
Oh shit I didn't noticed that there was already a fix for this.
But I don't get what happened because the bug is still here for me...

**Comment by akien-mga** [comment]
The fix was incomplete, there were two locations with the same broken loop.

**Comment by Adinimys** [comment]
Oh yeah right, I missed that it was not in the same place ^^ Well let's hope there is no third mistake now :P

**Comment by akien-mga** [comment]
> Well let's hope there is no third mistake now :P

I checked when I saw your fix, in that file at least it seems to be good now :)
