### ISSUE TITLE
Lock icons, handles, and helpers don't go away as the node/scene is deleted/closed in 2D editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11986]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor) fcd0398 

**Issue description:**
When deleting a node or closing a scene, lock icons, handles, helpers, and probably some other stuff doesn't automatically go away in the 2D editor, only when doing something that makes it redraw (moving, zooming...).

**Comment by groud** [comment]
I'll mark that as a dupplicate of #11560. But add acomment about the other problems.
