### ISSUE TITLE
Mono: Can't get a node as it's actual type unless the script derives from that type

### ISSUE THREAD

**Issue by NathanWarden** [godotengine/godot#11980]
When trying to make a general "Node" class that can be used on all nodes there seems to be no way to do specific functions for specific types of nodes as you can in GDScript.

I'm assuming this will also be an issue in C++ and any other strongly typed languages.

Here's a very crude example:

In GDScript, if the following script were placed on a Spatial node it would still translate it even though the script itself derives from Node instead of Spatial.

``` Python
extends Node

func _ready():
	self.translation = Vector3(2,2,2)
	pass
```

In C#, there's no way to get the node as Spatial unless the script derives from Node
``` C#
using Godot;

public class TypeCheckTest : Node
{
	public override void _Ready()
	{
		Node node = GetParent().GetChild(GetIndex());

		GD.print(node == null ? "Null" : "Not Null"); // This is "Not Null"
		GD.print((node as Spatial) == null ? "Null" : "Not Null"); // This is "Null"
	}
}
```

It would be nice we had some sort of conversion function that would give the node as whatever type it actually is, as if no script is on it.

IE.

``` C#
// If the node is a Spatial it returns Spatial (or whatever it is) even if the script derives from Node
Spatial mySpatial = node.AsRawType() as Spatial;
```

or something like that?

**Comment by NathanWarden** [comment]
So that it doesn't sound crazy what I'm talking about, I'm trying to make a very generalized script for a Unity compatibility Library I'm writing that will have quite a few things going on that are independent of the node type, but then just needs to do a very few specific things if it's a Node2D, CanvasItem, or Spatial.

I want to, *as much as possible*, make it so a developer can just bring their Unity code over and it'll just work. Right now, instead of just MonoBehaviour (for Spatial), I also have to have MonoBehaviour2D and MonoBehaviourUI which means a lot of code will need to be duplicated in all three scripts. Being able to get the node by it's actual type (Spatial, Control, Node2D) will allow me to just have a single MonoBehaviour that derives from Node.

https://github.com/NathanWarden/UnityGodotCompat

**Comment by groud** [comment]
This is impossible. C# uses static typing, calling a function without it defined in the class is not possible in C#. 

Also, Unity's design supports multiple inheritance, while godot does not. So many script won't be able to be translated into godot's C#.

Anyway, for me it will be impossible to translate scripts from Unity to Godot, they both have different design in a lot of situations: unity use components while godot only has nodes, the API is not the same at all... Pardon my rudeness, but this doesn't make any sense...

**Comment by Zylann** [comment]
Just to clear up something, Unity doesn't have multiple inheritance at all, and components can be translated if you use child Nodes where GetComponent becomes get_node.

**Comment by groud** [comment]
> Unity doesn't have multiple inheritance at all

Yes you're right, I was thinking about Interfaces. But well, it's a similar concept :)

>  and components can be translated if you use child Nodes where GetComponent becomes get_node.

Yeah, maybe you could figure some workarounds, but that's still a single part of the problem.

**Comment by reduz** [comment]
You can effectively translate components as empty child Nodes in Godot (For
behaviors, Node class lacks any kind of spatial information, they are
empty).. that is not a hack or workaround, it's effectively the same.

**Comment by neikeq** [comment]
You're basically asking for dynamic typing. The closest thing you have is calling `set`, `get` and `call` methods in Object, which will result in the same behavior as GDScript (as well as the same performance penalty). You could try with DynamicMetaObject to dispatch to those methods automatically if you can control the type ([this is a test](https://gist.github.com/neikeq/079e78bc3fded058e14ea8786d25ca7d) I made some time ago), but it's not allowed on iOS.

**Comment by neikeq** [comment]
Don't get me wrong. It's possible to do hack it to use an instance of type `Godot.Spatial` if the node is actually `Spatial` even though it inherits `Godot.Node`. But check this code:

``` C#
using Godot;

public class MySpatial : Node // This script is actually attached to a Spatial node
{
    public override void _Ready()
    {
        // This would work
        Node n = this;
        if (n is Spatial)
        {
            (n as Spatial).Translation = new Vector3(2, 2, 2);
        }

        // This would not work
        MySpatial n2 = this;
        if (n2 is Spatial) // Warning: The given expression is never of the provided ('Spatial') type
        {
            // Error: "Cannot convert type 'MySpatial' to 'Godot.Spatial' via a reference conversion, ..."
            (n2 as Spatial).Translation = new Vector3(2, 2, 2);
        }
    }
}

```

The problem is this is a horribly bad practice (not even sure if this may even cause errors later), and the warning and error in the second example can tell you that. There is no way to downcast `MySpatial` to `Spatial`. It's not like a downcast of `Node` to `Spatial`, which is perfectly possible. I would even argue this inheritance mismatch shouldn't be allowed in `GDScript` in the first place.

**Comment by NathanWarden** [comment]
> Yes you're right, I was thinking about Interfaces. But well, it's a similar concept :)

@groud Fortunately we'll be able to use interfaces in Godot as well :) Actually, to help myself get around this problem I'll probably resort to using them.

> and components can be translated if you use child Nodes where GetComponent becomes get_node

@Zylann I already have some of these implemented. :) GetComponent just grabs the same node and hands it back. Kind of useless, I know, but I don't want it to try and do something unfamiliar :) But, GetComponent(s)InChildren still makes a lot of sense :)

> It's possible to do hack it to use an instance of type Godot.Spatial if the node is actually Spatial even though its script inherits Godot.Node

@neikeq Unfortunately this doesn't work either. My code at the top is doing essentially the same thing. I put your code in and it still doesn't see it as Spatial. It's almost as if having a C# script on there is completely overriding the node as if the Spatial part of it doesn't exist.

Even the following code doesn't work when I try a node that's Spatial in the editor:

``` C#
Node node = Call("get_node", GetPath()) as Node;

if ( node is Spatial )
{
     GD.print("Spatial"); // This isn't printed
}
else
{
     GD.print("Not Spatial"); // This is what's printed
}
```

For now it's all good. Having 3 or 4 types of MonoBehaviours is fine as I can just have the user add a different namespace to the beginning of it (as I have it now).

I've been converting one of my personal projects over and most of the hard conversion work would have been the data classes like Vector3, Texture2D, Mathf, WWW, etc, which are all mostly done and work very well with translating from Godot to Unity.

Regardless, I suppose this is more of a specific issue related to me and won't affect too many people in the future. Maybe I'll dig around in the source and see if I can find a solution to this as there are more important things for you all to be concerned about :)

I'll leave this issue open for now unless one of you thinks it ought to be closed.

**Comment by groud** [comment]
Well, if you think there is an enhancement to be done or a bug to fix to the engine, we might keep this issue. Else I guess we can close :)

**Comment by neikeq** [comment]
@NathanWarden I said that would work if I made it create a Spatial instance instead of Node one. I'm not going to do that though because of the reasons I mentioned above.

**Comment by NathanWarden** [comment]
@neikeq Ah got ya, I missed that :)

@groud I just thought of something and might have a reasonable solution. If it works, then I'll post it and then close this issue.

**Comment by NathanWarden** [comment]
Okay, that solution didn't work, but I think I have another one that's similar but too complex to post the actual code here, but here's the general idea. Basically, I'm going to setup three classes: MonoBehaviour<T> where T : Node, MonoBehaviour : MonoBehaviour<Node> and an autoload.

MonoBehaviour<T> will register itself with the autoload and then the autoload will handle calling functions on the registered MonoBehaviours. MonoBehaviour : MonoBehaviour<Node> will print a warning telling the programmer they need to specify a type. So if they specify a type like Spatial, Node2D, etc they'll be able to have all of the specifics of each class.
