### ISSUE TITLE
Scene previews showing garbage

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11981]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04, GeForce 820M

**Issue description:**
Majority of times, the scene preview just shows indecipherable garbage:
![screenshot at 2017-10-09 21-15-09](https://user-images.githubusercontent.com/30739239/31363806-61f0ed4c-ad37-11e7-9755-16e7377d12ed.png)

**Comment by mhilbrunner** [comment]
Can't reproduce this on Godot 3 beta 2. Should this be closed and reopened if it still occurs in a current version?

**Comment by akien-mga** [comment]
Yeah there were other issues about this which got fixed recently.
