### ISSUE TITLE
Compiling Godot3 on Arch Linux gives MinGW error

### ISSUE THREAD

**Issue by TomWor** [godotengine/godot#11985]
On Arch Linux, Godot 3 compilation gives this:

    ➜  godot3 git:(master) scons platform=x11
    scons: Reading SConscript files ...
    Could not detect MinGW. Ensure its binaries are in your PATH or that MINGW32_PREFIX or MINGW64_PREFIX are properly defined.
    ImportError: bad magic number in 'config': b'\x03\xf3\r\n':
        File "/home/tom/Projects/godotengine/godot3/SConstruct", line 197:
        import config

**Comment by groud** [comment]
Had the same problem yesterday. You can run `git clean -d -x -f` to remove untracked files and fix the problem.

The problem is due to remaining files into a module folder.

**Comment by TomWor** [comment]
You're right. It's the second time I wish for a "scons clean" to take care of all that.
