### ISSUE TITLE
Suggestion: default node script has _process(delta) already

### ISSUE THREAD

**Issue by donkeybonks** [godotengine/godot#11994]
Hi,

Polish on Godot 3 is great so far. When I created a new script, however, I got this default:

```
extends Sprite3D

# class member variables go here, for example:
# var a = 2
# var b = "textvar"

func _ready():
	# Called every time the node is added to the scene.
	# Initialization here
	pass

```

I just think it would be nice if a new script contained along the lines of this instead (perhaps clearer):

```
extends Sprite3D

# Class member variables go here, for example:
# var a = 2
# var b = "textvar"

func _ready():
	# Called when this node is added to the scene.
        # Perform any initialization here:
	# self.set_process(true)
	pass
	
func _process(delta):
        # Called once on each frame if self.set_process(true) is used.
        # You could perform some game logic here:
	pass

```

This would have given me something to search for in the docs rather than kind of *all* the docs. It's also really similar to what Unity3D does, so might help with any transitioners ... 

![unity3d-template-1](https://user-images.githubusercontent.com/1356959/31386772-b8687852-ae13-11e7-864b-4f15689541c5.png)

**Comment by Noshyaar** [comment]
Related #5711

**Comment by mhilbrunner** [comment]
I agree that _process() should be there by default. Opinions?
I can send a PR if there is agreement. :)

**Comment by eska014** [comment]
In 3.x, `set_process(true)` is called automatically when the `_process()` function is defined in a script, so this will cause useless overhead

**Comment by diowonderland** [comment]
You could leave it uncommented in the template?

In related news, maybe there should be a warning if you add a "process()" function without the "delta" argument. Took me some time when I first used Godot to find out why my method wasn't called.

**Comment by vnen** [comment]
> You could leave it commented out in the template?

I believe this is a good compromise. You can have it saying "uncomment this if you need to process every frame" or something.
