### ISSUE TITLE
Grid Map Enhancement: Option to see cell data in inspector 

### ISSUE THREAD

**Issue by ScottMakesGames** [godotengine/godot#11993]
I would like to be able to see the data associated with a GridMap node in the inspector window in the standard way used by other nodes that hold arrays of data. 

Currently looks like this:
![image](https://user-images.githubusercontent.com/1318345/31386457-95fd6eae-ae12-11e7-8a4b-7efcdffbe105.png)
 But i would like an ArrayPropertyEdit section like this:
![image](https://user-images.githubusercontent.com/1318345/31386556-e10b37aa-ae12-11e7-8e23-f2bfa79eaeae.png)

Clicking Array[6] in the screenshot above expands to this:
![image](https://user-images.githubusercontent.com/1318345/31386590-00fb34e8-ae13-11e7-8fe5-bf0f9f8acdb9.png)

It would be convenient to be able to see and manipulate this data manually. Specifically however, I would like to be able to clear just this data, without having to reset all of the other properties on the GridMap node (currently to clear the data, I have to delete the node and re-add it, select the theme, and tweak the cell sizes all over again, with the standard ArrayPropertyEdit section, I could just clear the data and start again)

**Comment by Zylann** [comment]
So to clarify, you're not talking about the cells, right?
Which data are you talking about then? 
If all you want is just to reset Tilemap properties to default without touching inherited properties (such as Node2D stuff), then all you want might just be a right-click category/class header and "reset to defaults", which would reset to defaults all properties under the category or class.

**Comment by ScottMakesGames** [comment]
I am talking about the cells, and also this is specifically for GridMap, not TileMap (although maybe they would both benefit from this same feature request?)

I would like to be able to see at least a reference to the actual cell data array in the inspector.

**Comment by Zylann** [comment]
There is a big problem with this.
That data is very large and complex to be shown in an inspector.
Say you have 32x16x32 gridmap, a typical level. You would need to show 16,384 elements. This is huge to handle by the inspector, so if you really want to see that, the inspector would need an optimization.
Not to mention this data is not just a big array, it's a grid of octants of cells that probably wouldn't make sense when shown raw in the inspector.

Think about your use case though. You want to delete this data, so the solution is not to really about messing with the inspector. I mean, a simple menu item "clear all cells" with confirmation would do the job.

**Comment by ScottMakesGames** [comment]
You're right, for my use case a simple "Clear all cells" button would do the job. I just try to think as much about _a possible implementation_ that would solve my issues before I post about them. Looks like I vastly over complicated this one.

Should I close this issue and create another one with the more simple feature request fit for my use case?

**Comment by Zylann** [comment]
@ScottMakesGames yeah explain your use case in the title rather than one of the solutions (unless you have more use cases :p)
