### ISSUE TITLE
Viewport reacts to input in other docks/tools

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#11997]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 x64, [master@18d3ha0c](https://github.com/godotengine/godot/commit/18d3ba0c50ac073a4588388a6bdc71cfee44ea1f)

**Issue description:**
Pressing `W`, `A`, `S`, `D` is always registered in the viewport, even if other docks or tools are focused and used. (Example: Renaming things, filtering the scene node list or saving.)

**Steps to reproduce:**
1. Open Godot and create a new scene
1. Move view in viewport with `W`, `A`, `S`, `D` shortcuts
1. Enter something using those same keys somewhere else (e.g. filtering, or in the save dialog)
1. Observe that the viewport still reacts to those keypresses

**Link to minimal example project:**
GIF of the issue:
https://i.imgur.com/nvVzETr.gif

**Comment by Zylann** [comment]
Is it WASD in particular? These are polled differently with direct input when freelook is active. However, freelook can only be active when RMB is pressed and the viewport has focus, which both shouldn't be the case in this save dialog...

**Comment by mhilbrunner** [comment]
Only found it working (or rather, not working) with WASD, so that may be the case.

**Comment by toger5** [comment]
duplicated of  #11556 ?
I think they are definitely related.

**Comment by akien-mga** [comment]
I just tried it but couldn't reproduce the issue, can you confirm that it's fixed?

I found another nice issue though :P
![peek 07-01-2018 00-18](https://user-images.githubusercontent.com/4701338/34644909-b806ef7a-f340-11e7-8f60-2cf1a320718d.gif)

**Comment by brainsick** [comment]
Is this possibly related to #15199 ?

**Comment by mhilbrunner** [comment]
Can confirm this no longer happens with current master. Fixed.
