### ISSUE TITLE
Expose the documentation shortcut as a context menu

### ISSUE THREAD

**Issue by donkeybonks** [godotengine/godot#11996]
On OSX w/ Godot 3-master, if you hover a class in the code editor and press CMD + click, it launches the documentation for that class instantly in a new tab. It's really useful, but not exposed at all in the context menu.

It would be easier to find if it was.

<img width="654" alt="screen shot 2017-10-10 at 11 52 12 pm" src="https://user-images.githubusercontent.com/1356959/31387580-9d9fa4ac-ae16-11e7-932f-00f7c9f1074e.png">

**Comment by Hinsbart** [comment]
This should be easy to do.
How should that menu option be named though, since this feature is used both for "open docs" and "go to declaration"?

**Comment by Zylann** [comment]
Well, "go to definition"? For builtin classes it's the only thing to do, unless you wanna have your browser open at the Cpp file that contain the class^^ just suggesting

**Comment by kukiric** [comment]
Maybe have it be context sensitive? Show "Go to definition..." for user-defined functions and variables, and "Open docs..." for engine functions.

**Comment by donkeybonks** [comment]
I would agree it should be context sensitive

**Comment by groud** [comment]
"open reference" maybe?

**Comment by donkeybonks** [comment]
It would be nice if *eventually* it were possible to
* Show Documentation
* Show Source Code

And if you hit the second one on an engine function, it would open the c++ source in the godot editor in read-only mode.

**Comment by Zylann** [comment]
> it would open the c++ source in the godot editor in read-only mode

Oh... I was kinda joking about this one... but how would it even do that?

**Comment by donkeybonks** [comment]
Honestly I came to that thought independently and didn't even notice you suggested it ! 

But I already did some digging in the source and I don't think that's even possible .. way outside scope of this tickets title anyway . Just go to doc is easy and welcomed improvement

**Comment by secondwind21** [comment]
If this issue is still open I'd like to take a look at it. Seems relatively easy for a first time contributor.

**Comment by Hinsbart** [comment]
@secondwind21 Sure, feel free to have a go at it :)
