### ISSUE TITLE
"Group & Signal" icon uses the old signal design

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#12008]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor) 3453bf5

**Issue description:**
Self-explanatory:
![screenshot at 2017-10-10 19-04-46](https://user-images.githubusercontent.com/30739239/31413564-3ee9fbb8-adf0-11e7-9108-d82a1c5ccedf.png)

**Comment by groud** [comment]
Maybe you can open an issue on the design repo. @djrm, can you give us a link ?

**Comment by djrm** [comment]
oh yeah, need to update that one.
