### ISSUE TITLE
Script Editor over expanding when using "Search & Replace"

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#12012]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor) 3453bf5

**Issue description:**
When using the "Search & Replace" tool, if no matches are found, the editor will over expand to the side:
![screenshot at 2017-10-10 21-30-07](https://user-images.githubusercontent.com/30739239/31416978-1ebd9058-ae03-11e7-9fad-3292f2d0ccec.png)

This is likely due to lack of space, my max resolution is 1366x768 but I think if the "No Matches" warning was moved down, this could be easily fixed, here is my complete window:
![screenshot at 2017-10-10 21-37-39](https://user-images.githubusercontent.com/30739239/31417006-4e9c032c-ae03-11e7-8d3d-9f784f0a6793.png)

**Comment by jagt** [comment]
I tried to look at this issue and found that this seems to be the default behavior when text is clipped. For example in the screenshot below the long code is clipping out of the editor box.

![image](https://user-images.githubusercontent.com/241128/31435372-e505f210-aeb1-11e7-9816-aaa9ed2aa3af.png)

**Comment by reduz** [comment]
I think i might have fixed this, could you test again?

**Comment by YeldhamDev** [comment]
@reduz Nope, fresh build, still happens.

**Comment by YeldhamDev** [comment]
This seems to have been fixed now. Closing it.
