### ISSUE TITLE
How to pack godot game(s) into a native android/ios app and start it?

### ISSUE THREAD

**Issue by CloudTsang** [godotengine/godot#12016]
I need to add a game to my app(used for some math learning) to make it funnier for kids so I start to learn godot.
But firstly I must figure out how to export a godot game as not a single app but a part of my app like a plugin and can be started by pressing a button in my native android/ios app. 
Since the exported-pck file contents all data of a godot game , and I see the export template of IOS and Html seems to be some file to call the pck file(?) , is it possible to do this with our own java/objc code?

Sorry for my poor English and hope for your responses!

**Comment by CloudTsang** [comment]
No response after a week.T_T
Was my issue not clear enough or being wrong somewhere?

**Comment by vnen** [comment]
AFAIK nobody ever tried this. If no one answered is likely that no one knows. Godot wasn't made to be embedded in other apps, so while it may be possible, you won't get much help here unless it's a more specific issue.

**Comment by CloudTsang** [comment]
I'm trying to use "Custom Packge" to set my own packaged apk as export template.

So far, it  is successful to export a apk but fail to start the Godot activity and throw an exception of invalid reference in call to  “GetLongField”（called  from GodotLib.initiaize()?）. Maybe  somthing wrong in manifest or build.gradle configuration .

**Comment by CloudTsang** [comment]
emmm...
This way(Custom Packge) works.
I can boot godot game from my app ....................... only once.
I change the code in Godot.java and GodotView.java about  back button so that when I press back button in godot game , it will just finish the activity not quit the whole app.

But it seems not enough to quit the godot part safely just simply adding some "this.finish()". 
When i next boot godo game from my app , it throws these err:

E/godot   (16992): **ERROR**: Condition ' configured ' is true.
E/godot   (16992):    At: core\string_db.cpp:55:setup() - Condition ' configured ' is true.
E/godot   (16992): **ERROR**: Condition ' singleton ' is true. returned: __null
E/godot   (16992):    At: core\io\ip.cpp:270:create() - Condition ' singleton ' is true. returned: __null
E/godot   (16992): **ERROR**: Condition ' singleton ' is true.
E/godot   (16992):    At: core\input_map.cpp:289:InputMap() - Condition ' singleton ' is true.
E/godot   (16992): **ERROR**: Condition ' singleton != __null ' is true.
E/godot   (16992):    At: core\message_queue.cpp:339:MessageQueue() - Condition ' singleton != __null ' is true.
I/godot   (16992): *****SETUP OK
I/godot   (16992): ANDROID MODULES: Nothing to load, aborting


Maybe some properties should be initialized or some method should be call and I haven't figured it out so far.Hoping for help==.

**Comment by akien-mga** [comment]
This is out of the scope of this issue tracker as it's not something that should be implemented in Godot itself. Exported Godot games are apps that can be run normally - whether a native iOS or Android app can trigger launching another app is not really related to Godot (and it's likely possible, but better to ask on iOS or Android forums).

**Comment by kazman1** [comment]
Is it easy to convert gdscript to react native?

**Comment by Calinou** [comment]
@kazman1 GDScript and React Native are entirely unrelated to each other. There's no way to "convert" from one to another.

**Comment by First-AI** [comment]
I'm also looking for the same thing.

**Comment by Calinou** [comment]
@First-AI Android subview embedding is supported since 3.2.3, see https://github.com/godotengine/godot-proposals/issues/1064.

iOS subview embedding isn't implemented yet, see https://github.com/godotengine/godot-proposals/issues/1473.
