### ISSUE TITLE
Godot cannot create folder

### ISSUE THREAD

**Issue by cutepig49** [godotengine/godot#12019]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
45c878e3803c06361dfcad9d7a329ba12fc01570
win7 x64

**Issue description:**
Godot failed to create folder when I save a scene.
And if I make the scene importer store external files in a subdir, the importing will be failed.

![default](https://user-images.githubusercontent.com/3340057/31433090-db915ba4-aeaa-11e7-931f-d927697e7bb4.PNG)
![2](https://user-images.githubusercontent.com/3340057/31433095-dccb42a0-aeaa-11e7-9d73-c98261edfbd4.PNG)

**Comment by mutato** [comment]
The problem is that a wrong path is given to the native CreateDirectoryW function. This occurs not only when reimporting and creating sub directories, but when creating a new folder in the "Save scene as..." dialogue. 
I issued https://github.com/godotengine/godot/pull/12060 which fixes that.
