### ISSUE TITLE
"Separation" custom constant of Separator-Nodes does nothing

### ISSUE THREAD

**Issue by dalton5000** [godotengine/godot#12020]
Version 2.1.4 and 3.0-alpha

"Separation" custom constant of Separator nodes does not affect minimum-size of the node. Always stays at 3.

Happens always.

**Comment by bojidar-bg** [comment]
Looking at the code, it should work:
https://github.com/godotengine/godot/blob/45c878e3803c06361dfcad9d7a329ba12fc01570/scene/gui/separator.cpp#L32-L37

Unfortunatelly, it seems to set the wrong minimum size, thus a HSeperator with `Seperation = 5` would get a minimum size of (5,3), and look like this:
![image](https://user-images.githubusercontent.com/5276727/31437639-9cf6d818-ae8e-11e7-9560-1a77452e6a25.png)
