### ISSUE TITLE
Godot games do not set windowing hints

### ISSUE THREAD

**Issue by thePalindrome** [godotengine/godot#12023]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux, Godot 2.1.4

**Issue description:**
Certain window managers such as i3 default to "tiling" mode, where they set the width,height, and position of windows. In order for applications to set their own width and height, they must enter "floating" mode, which can be done by setting _NET_WM_WINDOW_TYPE to DIALOG, UTILITY, SPLASH, or TOOLBAR. There are a few other ways to specify a floating mode, but those are what I'd imagine to be the most supported ways.

Godot games do not set _NET_WM_WINDOW_TYPE, thus default to NORMAL. Tiling window managers will force the window larger, exposing more of the scene than would ever be expected.

Based on https://standards.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472629520, I would suggest UTILITY as being the most relevant and having the least side effects.

**Steps to reproduce:**
Use a tiling window manager (such as i3wm)
Run a godot game
Running the xprop utility on the window shows a lack of WINDOW_TYPE

**Comment by AntiSC2** [comment]
Setting it to UTILITY does not work well at all. Only tested this quickly under Budgie (Mutter WM) but you could no longer minimize nor maximize the window anymore. It also does not show up on the taskbar anymore.

SPLASH removes the window decorations and makes the windows unmovable. DIALOG is like UTILITY but the windows show up in the taskbar. TOOLBAR is like SPLASH but also removes it from the taskbar.

Not anyone of them seems like a good candidate and this feels like a hackish solution. Does tiling wm:s not set the size to the WM_SIZE_HINTS if both min and max values have been set?

**Comment by thePalindrome** [comment]
As far as i3 goes, here's the block that specifies this:

https://github.com/i3/i3/blob/55bc6741796e8b179b6111a721a3e9631934bb86/src/manage.c#L435

It *seems* that setting max and min will work, but I'm not sure about anything else.

**Comment by AntiSC2** [comment]
Can you try going in to project settings and setting the game window to not resizeable. It worls by setting min & max to the same value

**Comment by thePalindrome** [comment]
Turning "Resizable" off means that the window is still tiled, but when set to floating does not snap back to it's normal width/height

**Comment by Web-eWorks** [comment]
i3 does not expose a cross-platform way to enable floating for the window beyond the above, nor is it in the scope of Godot to include WM-specific code to enable such a function, or to set the WM_TYPE to an incorrect value.

If i3 users want a resizable Godot window to start out floating, then they may add a rule in their i3 config; it's simple (I've done it myself) and well within the minimum technical knowledge required to use i3.

Can you confirm with the latest Godot 3 / master that setting resizable off does not result in the window becoming floating?

**Comment by thePalindrome** [comment]
Confirming continued behaviour with 3.0.6.stable.official.8314054, both the lack of auto-floating, and turning resizing off still causes the window size to be set at what i3 initialized it to. (I will admit, Web's comment makes enough sense that they may have the correct answer here)

**Comment by Web-eWorks** [comment]
Will attempt to track down the resizing issue. It may be an issue in i3 (at which point I am unable to resolve the issue), or it may be an issue in Godot's platform initialization.

Regarding auto-floating, I must reaffirm my original stance - it is not achievable without engine changes specific to a WM, (and the changes are arguably incorrect with regards to the scope and purpose of the WM_TYPE hints) and thus is outside of the scope of Godot.

If/when Godot gains multi-window support, setting the window's type hint may well be possible for developers to do without recompiling the engine; it will then be up to individual Godot users to determine what type hint they set on windows they create.

**Comment by Calinou** [comment]
Is this still an issue with the recent DisplayServer merge?

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
