### ISSUE TITLE
Fix Alpha Border doesn't work in the latest code

### ISSUE THREAD

**Issue by art-kandy** [godotengine/godot#12033]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10. Latest code.

**Issue description:**

Fix Alpha Border doesn't have some influence on the imported texture. It doesn't fix white border of PNG exported from Photoshop

**Steps to reproduce:**
Import PNG with transparency

**Link to minimal example project:**

[TESTPROJECT.zip](https://github.com/godotengine/godot/files/1376645/TESTPROJECT.zip)

**Comment by groud** [comment]
Godot 3.0 or 2.1 ?

**Comment by art-kandy** [comment]
Issue occurs on 3.0. As I see in the code, the reason is in the absence of the next line in **core/Image.cpp** file (_Image::fix_alpha_edges()_ method):

**closest_dist = dist;**

before image data modifying:

_closest_color[0] = rp[0];
closest_color[1] = rp[1];
closest_color[2] = rp[2];_

I've tested and it fixes the issue.

**Comment by bojidar-bg** [comment]
@art-kandy Mind if you make a PR with your change?
We have some docs about [making a PR](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) if you need them.

**Comment by art-kandy** [comment]
Sorry, I'm not sure I can do it soon. Quite busy.

**Comment by HummusSamurai** [comment]
Fixed by https://github.com/godotengine/godot/pull/12072?

**Comment by groud** [comment]
Yep. Closing.
