### ISSUE TITLE
AnimationTree dock has all nodes stacked together in a corner

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#12036]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10 64bit, 2017-10-11.aecbc15 build

**Issue description:**
in platformer 3D animation tree window stacks all nodes in the upper left corner and they cannot be repositioned 

**Steps to reproduce:**
open player's animation tree window in platformer 3d

**Link to minimal example project:**

**Comment by groud** [comment]
Do you have a screenshot ?

**Comment by abaky** [comment]
![2017 10 11-23 41](https://user-images.githubusercontent.com/9384421/31468537-68b3af7c-aede-11e7-909c-90cfc760e3ec.png)

**Comment by akien-mga** [comment]
I can confirm this issue in the current master branch, it looks quite bad. Needs a fix for 3.0.

**Comment by bfloch** [comment]
I am not sure this is a godotengine issue.
The nodes are simply stored like this in the demo project. You can move them if you carefully click the header. Once saved it looks ok again.

Since no-one would create nodes like this I guess this is a no issue.
Still it would be great if godot would rearrange the graph automatically, but this is not a trivial task.

Any graph theory nerds aboard? :-)

**Comment by eon-s** [comment]
A 2.1 exporter bug in this case?

An arrange tool for GraphEdit could be nice to have but won't automatically fix this, also may need an extensible GraphEdit to be useful (to set sorting rules, etc.).

**Comment by vnen** [comment]
> An arrange tool for GraphEdit could be nice to have but won't automatically fix this, also may need an extensible GraphEdit to be useful (to set sorting rules, etc.).

And make AnimationTreePlayer actually *use* GraphEdit, since currently it is just using an ad-hoc implementation.

**Comment by akien-mga** [comment]
> The nodes are simply stored like this in the demo project. You can move them if you carefully click the header. Once saved it looks ok again.

Thanks, moved to https://github.com/godotengine/godot-demo-projects/issues/196 then.

> A 2.1 exporter bug in this case?

It might be worth investigating.
