### ISSUE TITLE
C++ Modules: Linking system libraries to godot/bin/godot fails unless libraries are added to #modules/SCsub

### ISSUE THREAD

**Issue by hungrymonkey** [godotengine/godot#12034]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

KDE Neon User Edition: "Ubuntu 16.04 derivative"

godot master

**Issue description:**

Even thou, I barely started using godot. I realize that in order to use system libraries on my system. I have to include them in godot/module/SCsub. I found it strange because I tried using the same flags as an example linked here, but the compile fails. It seems like a godot 3.0 regression since the author never mentions editing modules/SCsub

https://github.com/antarktikali/godot-opencv-gpu-perspective/blob/master/cvperspective/SCsub

Obviously, module/mymodule/SCsub can find find the required libraries because it would had not pass that stage during compiling. I wonder why godot/bin cannot find the system library after it was found in module/mymodule/SCsub

Here is an random example

 If added to godot/module/mymodule/SCsub, the module source will compile but the module will fail during linking the program as such

```
[ 24%] Compiling ==> thirdparty/dlib/dlib/all/source.cpp
[ 28%] Compiling ==> modules/motion_sense/facial_landmark.cpp
[ 28%] Compiling ==> modules/motion_sense/register_types.cpp
[ 97%] Linking Program        ==> bin/godot.x11.tools.64
modules/libmodules.x11.tools.64.a(facial_landmark.x11.tools.64.o): In function `FacialLandmark::FacialLandmark()':
/home/cheeseburger/godot/modules/motion_sense/facial_landmark.cpp:12: undefined reference to `cv::VideoCapture::VideoCapture(int)'
modules/libmodules.x11.tools.64.a(facial_landmark.x11.tools.64.o): In function `FacialLandmark::~FacialLandmark()':
/home/cheeseburger/godot/modules/motion_sense/facial_landmark.h:9: undefined reference to `cv::VideoCapture::~VideoCapture()'
modules/libmodules.x11.tools.64.a(facial_landmark.x11.tools.64.o): In function `FacialLandmark::~FacialLandmark()':
/home/cheeseburger/godot/modules/motion_sense/facial_landmark.h:9: undefined reference to `cv::VideoCapture::~VideoCapture()'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.
```

It compiles my module, but it cannot link it.

**Steps to reproduce:**
In godot/module/mymodule/SCsub

add a line like this
```
module_env.Append(LIBS=["any_system_lib"])
```
use it in the library in the source files.

it fails at the linking program stage

Expected Result: I should not have to add the libraries to #modules/SCsub in order to link the program

Edit: I want to clarify. In order for linking to work, I have to add it to godot/modules/SCsub, not godot/modules/mymodule/SCsub

If this is the desired behavior, I would close the issue report

**Link to minimal example project:**

**Comment by akien-mga** [comment]
> `module_env.Append(LIB=["any_system_lib"])`

It's `LIBS`:
```
$ rg Append\\\(LIB
modules/freetype/SCsub
83:        env.Append(LIBS=[lib])

platform/android/detect.py
220:        env.Append(LIBPATH=[env["ANDROID_NDK_ROOT"] + "/sources/cxx-stl/gnu-libstdc++/4.9/libs/" + arch_subpath])
221:        env.Append(LIBS=["gnustl_static"])
237:    env.Append(LIBPATH=[env["ANDROID_NDK_ROOT"] + '/toolchains/arm-linux-androideabi-4.9/prebuilt/' +
239:    env.Append(LIBPATH=[env["ANDROID_NDK_ROOT"] +
244:    env.Append(LIBS=['OpenSLES', 'EGL', 'GLESv3', 'android', 'log', 'z', 'dl'])

modules/recast/SCsub
28:    env.Append(LIBS=[lib])

platform/haiku/detect.py
74:    env.Append(LIBS=['be', 'game', 'media', 'network', 'bnetapi', 'z', 'GL'])

modules/svg/SCsub
27:    env.Append(LIBS=[lib])

platform/osx/detect.py
108:    env.Append(LIBS=['pthread'])

platform/uwp/detect.py
94:        env.Append(LIBPATH=[vc_base_path + 'lib/store/arm'])
98:        env.Append(LIBPATH=[angle_root + '/winrt/10/src/Release_ARM/lib'])
119:            env.Append(LIBPATH=[vc_base_path + 'lib/store'])
120:            env.Append(LIBPATH=[angle_root + '/winrt/10/src/Release_Win32/lib'])
128:            env.Append(LIBPATH=[os.environ['VCINSTALLDIR'] + 'lib/store/amd64'])
129:            env.Append(LIBPATH=[angle_root + '/winrt/10/src/Release_x64/lib'])

platform/x11/detect.py
237:    env.Append(LIBS=['GL', 'pthread'])
240:        env.Append(LIBS=['dl'])

platform/server/detect.py
125:    env.Append(LIBS=['pthread'])

platform/windows/detect.py
187:        env.Append(LIBPATH=[os.getenv("WindowsSdkDir") + "/Lib"])
195:        env.Append(LIBPATH=[p for p in os.getenv("LIB").split(";")])
280:        env.Append(LIBS=['mingw32', 'opengl32', 'dsound', 'ole32', 'd3d9', 'winmm', 'gdi32', 'iphlpapi', 'shlwapi', 'wsock32', 'ws2_32', 'kernel32', 'oleaut32', 'dinput8', 'dxguid', 'ksuser'])

modules/mono/config.py
65:        env.Append(LIBPATH=mono_lib_path)
76:            env.Append(LIBS=mono_lib_name)
106:            env.Append(LIBPATH=mono_lib_path)
126:                env.Append(LIBS=[mono_lib])
128:            env.Append(LIBS=['m', 'rt', 'dl', 'pthread'])
```

**Comment by akien-mga** [comment]
> Expected Result: I should not have to add the libraries to #modules/SCsub in order to link the program

Yes, you do. Linking is always manual, you have to tell the compiler what library will resolve the symbols it's looking for. The compilation step only uses the headers, it's the linking that uses the libraries.

**Comment by hungrymonkey** [comment]
my bad

**Comment by hungrymonkey** [comment]
maybe i should add to the docs d'oh

**Comment by hungrymonkey** [comment]
@akien-mga 

the issue i am having is that I have to add it #modules/SCsub

not modules/mymodules/SCsub

I wonder if it that is intentional

**Comment by hungrymonkey** [comment]
@akien-mga I am adding libraries to a directory not contain my modules, I read your comment, I realize I wanted some more clearification. I look that godot 2.1 example above, the author did not need to add it to modules/SCsub.

**Comment by hungrymonkey** [comment]
@akien-mga  I actually used the keyword libs in mymodule/SCsub and it did not work

**Comment by hungrymonkey** [comment]
I am bit too tired today, I spend hours dealing with build errors and I cannot collect my thoughts

**Comment by hungrymonkey** [comment]
@akien-mga Do we have to set configure(env) to find system library as in the module/mono/config.py ?

I am thinking that module maybe searching a different path so it cannot find the same system libraries as godot/modules/SCsub

**Comment by hungrymonkey** [comment]
Closing bug, I was supposed to add it to godot/module/mymodule/config.py to get system libraries. That file seems to work

I would probably write a features request to godot-doc
