### ISSUE TITLE
Android install issue INSTALL_FAILED_CONFLICTING_PROVIDER (2.1)

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#12047]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOSX 10.12.6 (16G29), Android 4.4.2, Godot 2.1.4 (commit 8122d943c)

**Issue description:**

I buit two game apks with two different package name. I can install the first one. But when I try to install the second one I get an error message:
```
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER]
```
I think that the root of issue is the package name of android template `com.godot.game`. But if I change it to something else in `AndroidManifest.xml.template` I get during compiling another error:
```
/Users/vasya/projects/godotframework/godot/platform/android/java/src/com/google/android/vending/expansion/downloader/Helpers.java:19: error: package com.godot.game does not exist
import com.godot.game.R;
                     ^
/Users/vasya/projects/godotframework/godot/platform/android/java/src/com/google/android/vending/expansion/downloader/impl/DownloadNotification.java:19: error: package com.godot.game does not exist
import com.godot.game.R;
                     ^
/Users/vasya/projects/godotframework/godot/platform/android/java/src/com/google/android/vending/expansion/downloader/impl/V14CustomNotification.java:19: error: package com.godot.game does not exist
import com.godot.game.R;
                     ^
< a lot of messages like this ones>
```

Should I change all godot java sources to use the different package name or there is another way to fix this issue?

**Steps to reproduce:**
Build two apks with different package ID and try to install on the same device.

**Link to minimal example project:**

I uploaded both my apks: 

https://www.dropbox.com/s/ouhqimd0s44b1kb/space-cute.apk?dl=0
```
package: name='org.asmstudio.spacecute' versionCode='25' versionName='0.0.25' platformBuildVersionName=''
```
https://www.dropbox.com/s/5bgehhkq0vvesih/galaxy-adventure.apk?dl=0
```
package: name='free.line.games.match.three.puzzle.galaxy.adventure.android' versionCode='10000' versionName='1.0.0' platformBuildVersionName=''
```

**Comment by volzhs** [comment]
your android template has many android modules including `com.google.android.gms`
I guess it's firebase.
did you make 2 different templates with 2 different `google-services.json` and `env.android_add_default_config("applicationId 'org.asmstudio.****")`?

**Comment by DrMoriarty** [comment]
@volzhs Thank you very much! Actually android_add_default_config did the trick!
I use many modules, some of them have dependencies to firebase and other google services.
