### ISSUE TITLE
Reorder nodes in "Create New Node" dialog.

### ISSUE THREAD

**Issue by gregersn** [godotengine/godot#12041]
This is just a minor annoyance/suggestion, but one that in the long run takes up a lot of time

If I want to add a "Sprite" node to a 2d scene, and I start searching for it in the "Create New Node" window, I type "Sprite", and then I will have to press the down button four times before I can choose "Sprite". If I would want to add a "Sprite3D" then I could just press enter after typing "Sprite", or type out "Sprite3D", but there is no way to specify, in search (that I know of) that I want the 2d sprite. 

This could either be fixed by sorting the "Sprite" node before the "Sprite3D" in the list, or by renaming "Sprite" to "Sprite2D", both would save lots of times, and make it easier to select when using the keyboard. 

The same goes for "AnimatedSprite".

**Comment by Zylann** [comment]
Could be fixed by considering the absence of letter to be sorted first rather than last

**Comment by AyeTbk** [comment]
It looks like a solution to this has already been merged: PR #11706

**Comment by akien-mga** [comment]
Seems to work fine in the current master branch, searching "sprite" selects Sprite by default.
