### ISSUE TITLE
Alpha Pre-Pass with transparent material doesn't cast shadows

### ISSUE THREAD

**Issue by ComancheAk** [godotengine/godot#12058]
**OS: macOS 10.12 Sierra, 
Godot version: 3.0.alpha.custom_build.b759d14 
GPU: Intel Iris 6100**

**I want to make a shadow from 3d sprite:**
I've tried to make this with Alpha Pre-pass of depth draw mode with custom material and get this

<img width="1280" alt="2017-10-12 23 16 56" src="https://user-images.githubusercontent.com/6551114/31517091-7d236fea-afa3-11e7-955d-6c20c5511c39.png">

**Steps to reproduce:**
Just try to add sprite3d with custom material or open example project

**Link to minimal example project:**
[thibronepa1.zip](https://github.com/godotengine/godot/files/1380562/thibronepa1.zip)

**Comment by djrm** [comment]
i didnt know if this was a bug or just a restriction, but i would like to see it working.

**Comment by ComancheAk** [comment]
Godot 2.1 allows this thing
![material_depth_draw](https://user-images.githubusercontent.com/6551114/31519413-0a1b120c-afab-11e7-98df-6009887e1b41.png)

**Comment by gamergamesz** [comment]
3.0 too

**Comment by djrm** [comment]
@reduz is this still posible in 3.0

**Comment by ComancheAk** [comment]
I'm think it's not because I've checked 2.1 with the same settings and it have been worked there but 3.0 doesn't allow this thing, maybe it's in render part because render has changed a lot.

**Comment by reduz** [comment]
I remember testing this recently and it worked.. just make a demo project..

**Comment by djrm** [comment]
@reduz it might not be a bug, but if there is a way to make it work is super hard to find it. here is a demo, also notice that the interaction with other transparent materials

[depth_draw_test.zip](https://github.com/godotengine/godot/files/1388912/depth_draw_test.zip)
