### ISSUE TITLE
AnimatedSprite Animation Frames editor shows "ERROR" on delete buttons

### ISSUE THREAD

**Issue by kerskuchen** [godotengine/godot#12051]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win64, Godot 3.0 current master

**Issue description:**

![error](https://user-images.githubusercontent.com/2393859/31485370-dadf3774-af33-11e7-9574-b750d57ef448.png)

**Steps to reproduce:**
Create an AnimatedSprite Node, create a new SpriteFrames resource and click on it

**Comment by StraToN** [comment]
Confirmed. I already saw this a few time ago, but I wasn't sure I was the only one affected, thus didn't file an issue myself.

**Comment by akien-mga** [comment]
cc @djrm @toger5

**Comment by djrm** [comment]
ok i will fix this in my upcoming icons / interface PR.
