### ISSUE TITLE
Display wrong when viewport over size screen window

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#12062]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux, Godot 2.1

**Issue description:**
Example, I set Window size 1280x720 and viewport 1280x960, and add WorldEnvironment then it show worng (see example project).

https://photos.app.goo.gl/woKxgOHAovhd4ODy1
![untitled](https://user-images.githubusercontent.com/8281454/31577462-f4ca59d0-b149-11e7-9c0f-027540f3bacb.png)

**Steps to reproduce:**

**Link to minimal example project:**
https://www.dropbox.com/s/yjmg7d92s2zdlmi/bugViewport.zip?dl=0

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
