### ISSUE TITLE
Godot 2.1 build from 12/10/17 crashes in preview if any node has script attached

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#12066]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot version 2.1.4 custom build compiled at 12/10/2017 32 bit version platform=windows target=debug_release.

**Issue description:**
Engine shows error on preview play and don´t execute scene:

Stack Underflow (Engine Bug):

C error: condition 'is_inside_tree()'is true.
returned: NodePath()
C Fuente: scene/main/node.cpp: 1163
C Función: Node::get_path

Error only happend if project have any script attached.

Edit, more test done:

Error only happend in editor preview, exported binary executes, but if try to close the game, game crash (I don´t know if this crash is releated with the issue)

(Edit2, more more test done:

I can´t see the console. If I select 127.0.0.1 in network the problem appears. Problem seems to be the debugger. Changing "Debug Host" fix the problem but no output in editor (console is missing no matter what you do).

I think that it can be releated to #10891

**Steps to reproduce:**
Open any demo with Godot 2.1.4 32bit (64bit tested and same problem) compiled after oficial release (don´t know exactly date) and execute in preview.  If demo have scripts, it doesn´t preview, if don´t have, nothing happend (You must have valid IP in network to reproduce the problem). Note that console is missing.

**Link to minimal example project:**
Oficial demos.

**Comment by akien-mga** [comment]
> Godot version 2.14

Note that it's 2.1 **.** 4, we haven't had 14 releases in the 2.1 branch.

**Comment by Zireael07** [comment]
Multi thread compiling is broken for 3.0 too as it's not a Godot issue, it's a scons issue.

**Comment by akien-mga** [comment]
What? That makes no sense.

Single- and multithreading compilation should produce the exact same binary, otherwise the whole C/C++ world would break apart if you get incompatibilities in software based on how it was built physically.

**Comment by akien-mga** [comment]
> Multi thread compiling is broken for 3.0 too as it's not a Godot issue, it's a scons issue.

That's unrelated.

**Comment by Ranoller** [comment]
I don't know If it make no sense. Tomorrow will do more test.... But i think that compiled executable is not the same with and without -j

**Comment by Ranoller** [comment]
Ok, i can´t reproduce now, i think that the issue was asociated to autogenerated files being created by one thread and trying used simultaneously by other thread (some build errors in first-times trying to compile), but i don´t understand well the compiling process of godot and i can´t reproduce error. Issue is closed to not bloat issue system with no-sense fails, if this error return to my buid´s (I´m using modules) i report that. Probably all was made by my mistake, for now I stop this investigation :) :) :)
