### ISSUE TITLE
VisualScript: untouched value is null instead of 0

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#12065]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64, Master e97ada6

**Issue description:**
![image](https://user-images.githubusercontent.com/26753932/31538912-3e4d893e-b031-11e7-9452-fecc86f904c2.png)
Expected: no error
Happened: error in arg2, alpha is null

**Steps to reproduce:**
1. add VS and nodes as in the image, don't set any value
2. set 1st arg to "red"
3. save and run -> error
4. stop, click in the 2nd arg and press enter without changing value
5. save and run -> ok

**Comment by Adinimys** [comment]
If I'm not mistaken this issue arises with all BuiltinFunc with 2 arguments or more. Not if they have only one argument

**Comment by rcurtis** [comment]
Pull request to fix: https://github.com/godotengine/godot/pull/12097
