### ISSUE TITLE
Built-in CubeMap render

### ISSUE THREAD

**Issue by dronhacker666** [godotengine/godot#1207]
How about adding functionality for realtime render cubeMap textures (use for reflections etc)

Sorry, i am use translate.google.com for write this message.

**Comment by reduz** [comment]
this functionality will all be added after 1.1 (or 1.2 not sure yet), when
focus moves on improving the 3D renderer.

**Comment by dronhacker666** [comment]
Ok, thanks. I'll be wait)

**Comment by akien-mga** [comment]
FYI, according to the new roadmap the work on the 3d renderer will be done for 3.0.

**Comment by bojidar-bg** [comment]
Kind reminder, since 3.0 is coming "soon"

**Comment by reduz** [comment]
@bojidar-bg sooner than you expect it seems. This is implemented now in the new renderer, so closing this issue.
