### ISSUE TITLE
GraphEdit: icon for grid snapping is missing

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#12077]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Master 4585239

**Issue description:**

![image](https://user-images.githubusercontent.com/26753932/31555741-6d4578b0-b06c-11e7-9ac7-ad52bdb0f624.png)

**Comment by groud** [comment]
Confirmed :)

**Comment by Hinsbart** [comment]
CC @djrm, the master of icons ;)
