### ISSUE TITLE
Visual scripts editor cannot be zoomed using CTRL+mouse wheel combo

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#12076]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
all

**Issue description:**
Please make CTRL+mouse wheel combo possible in Visual Scripts editor.. I looked through code myself but didnt find where I can change it and PR..

**Comment by noxarivis** [comment]
1+
would be awesome

**Comment by Noshyaar** [comment]
Actually, this is not yet implemented to GraphEdit node, not related to VisualScript. (VisualScript uses GraphEdit for its interface.)

https://github.com/godotengine/godot/blob/master/scene/gui/graph_edit.cpp

**Comment by Chaosus** [comment]
Ah, and Im looked to editor folder... :)

**Comment by Noshyaar** [comment]
Btw, VisualScript stuff is in modules/visual_script folder as it is an editor's module.

**Comment by vnen** [comment]
Almost the same as #6168

**Comment by Noshyaar** [comment]
Then it's disabled on purpose: #6317

**Comment by Noshyaar** [comment]
Closing as duplicate of #6168
