### ISSUE TITLE
Additive glow is very strong.

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#12082]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 64 bits, Nvidia GTX prorietary drivers v. 384.90 ,  Godot a931f905f

**Issue description:**

The additive glow is very strong, even with default parameters, i dont remember it being so strong

here is a comparison between current master and alpha 1

MASTER
![screenshot from 2017-10-13 17-52-52](https://user-images.githubusercontent.com/1103897/31569314-84439b6e-b03f-11e7-9167-e2af882c325b.png)

ALPHA 1
![screenshot from 2017-10-13 17-53-36](https://user-images.githubusercontent.com/1103897/31569316-8a911dca-b03f-11e7-90ca-904d8e4545c8.png)

**Steps to reproduce:**
use additive glow

**Link to minimal example project:**

**Comment by reduz** [comment]
Not sure if something was fixed, but in general it is meant to be strong

**Comment by djrm** [comment]
@reduz but it is really strong, at the point of being unusable with most parameters, befora it was nice, here is another example

![screenshot from 2017-10-13 17-51-10](https://user-images.githubusercontent.com/1103897/31569779-5960fce4-b043-11e7-8e56-4666f88e41e7.png), with this parameters
![screenshot from 2017-10-13 17-51-04](https://user-images.githubusercontent.com/1103897/31569792-670279f4-b043-11e7-9592-9db3bc00c822.png)

it used to be more controlable, and switching between modes wasnt that drastic.

**Comment by reduz** [comment]
I did a fix recently because it was done in linear space, while it should have been done in SRGB. It's more correct now, and it's expected to be like that, Decreasing stength should help for this mode.
