### ISSUE TITLE
Bullet PR: Area collision shapes are not accurate (transforms are not taken into account)

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12095]
**THIS ISSUE APPLIES TO BULLET PHYSICS PR** (it's not related to godot physics engine, or godot main branch at the time of creating this issue)

**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Bullet PR,  https://github.com/godotengine/godot/pull/10013/commits/e6655f46e2cb9c4ec0681a2c227476fc55608cfc

**Issue description:**
It seems like for some reason multiple shapes in area will not report body collision in an accurate way. This probably is related to the fact that collision shapes are translated in my case. 
I recorded a video  that presents this issue:
https://www.youtube.com/watch?v=035OjCd6IyI&feature=youtu.be

**Steps to reproduce:**
1. Download sample project
2. Enable `visible debug shapes` option in editor 'Debug' menu
3. Run TestLevel2 scene
4. Use  `a` and `d` keys to move body towards area.
5. When collision will be detected body will jump a little and camera will reposition to better illustrate the problem
6. (optionally) Check `ObjWithArea.tscn` scene / script.

**Link to minimal example project:**
[AreaBodyCollisionTest.zip](https://github.com/godotengine/godot/files/1384836/AreaBodyCollisionTest.zip)

**Comment by kubecz3k** [comment]
cc @AndreaCatania

**Comment by AndreaCatania** [comment]
Fixed: 59ac299

**Comment by groud** [comment]
> Fixed: 59ac299

Closing then. :)
