### ISSUE TITLE
Roughness slow

### ISSUE THREAD

**Issue by louisVottero** [godotengine/godot#12106]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Intel i7-6700 CPU @ 3.4GHz, 16 GB Ram NVIDIA GeForce GTX 960

**Issue description:**
Turning roughness on a shader to anything but zero causes drastic frame drop.

**Steps to reproduce:**
Scene can run at 40 frames a second.  There is one shader in the scene and one piece of geo.  Geo is about 13,000 tris.   Two 4k textures applied to the geo.  One map is color and one map is a normal map.   If I turn up roughness, the frames per second drops to 10.   If I turn roughness to 0 performance goes back up to 40.

**Link to minimal example project:**

**Comment by tagcup** [comment]
Does this happen only with GGX specular?

**Comment by louisVottero** [comment]
Yes, I had GGX spec on

**Comment by tagcup** [comment]
OK, but does the slowdown happen *only* with GGX specular? Does it happen with other specular modes?

**Comment by reduz** [comment]
I have never seen this, so an example scene is welcome

**Comment by reduz** [comment]
Please understand that we set the issue submission guidelines for a reason.

You are assuming that anyone can reproduce you issue by changing roughness
and it seems this is not the case.

**Comment by louisVottero** [comment]
I'm unable to reproduce it this morning.   Here is the example file.   Sorry for taking your time on this.   I will wait until I experience the issue more before starting an issue in the future. 

example:
https://www.dropbox.com/s/wkn2bd0qnwijtv6/slow_glossiness.zip?dl=0

**Comment by louisVottero** [comment]
Actually in the example above if you set roughness to 1 the game runs faster, if you set it to 0 the game runs slower, by about +- 5-10 frame a second.

**Comment by louisVottero** [comment]
I'm just recompiling the game over and over with out changing roughness and I get different frame rates.   So this is a none issue.
