### ISSUE TITLE
Retina display not utilized on OS X when selecting files (3.0a)

### ISSUE THREAD

**Issue by mcclure** [godotengine/godot#12111]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

OS X 10.12.6 (16G29) on a MacBookPro12,1 (retina).
Cloned git deefc2a63d36b6659630df703a9b98adffb893e9 (3.0, master). Built with `scons platform=osx -j4` and executed with `./bin/godot.osx.tools.64`.

**Issue description:**

On opening, a "project manager" opens that lets me open files. It does not use the os x retina ability, even on things like text.

I open a project. the "project manager" seems to close and a new program appears to open. The other program uses retina ability.

Attached are two screenshots. As you can see, the text is rendered at a higher dpi in the second screenshot than the first.

<img width="1280" alt="screen shot 2017-10-14 at 8 12 48 pm" src="https://user-images.githubusercontent.com/277318/31580411-f22cb6dc-b11c-11e7-83c7-ea090ef176cc.png">

<img width="1280" alt="screen shot 2017-10-14 at 8 14 32 pm" src="https://user-images.githubusercontent.com/277318/31580393-b774bcba-b11c-11e7-92ad-a2545392534a.png">

Expected behavior: The project manager should use the same high-dpi rendering that the editor itself uses.

**Comment by akien-mga** [comment]
I'm not sure I see the issue, the font and UI scale seems to be the same in both cases. Is the font rendering maybe slightly less crisp on the project manager?

**Comment by Calinou** [comment]
This is a regression coming from d938de67fff288bf7f0a92fd51a2e890a1b5f245, as this commit treats the project manager as a non-editor process.

**Comment by mcclure** [comment]
@akien-mga The scale is the same but the DPI is different. In the first image it is being rendered at half size and nearest-neighbor upscaled.

**Comment by BigZaphod** [comment]
I see this same issue with version 3.0 (which I just downloaded today). I almost closed Godot and gave up even messing around with it because of the incorrect DPI. I'm glad I clicked my way into a project to see that the main editor seems to be properly supporting retina and started messing around with it, but this was a very bad/shoddy initial first impression!
