### ISSUE TITLE
3D-demo-projects crash on android device and emulator

### ISSUE THREAD

**Issue by yuyoDev** [godotengine/godot#12117]
Compiled in adm-fx8350, godot3.0a, card graphics AMD-R9-270X

Demos works well in Godot but in android-device(xiaomi-redmi-note-3) crash at start, also in emulator of android-studio

Test demos 3d on real-device

**Comment by RandomShaper** [comment]
Could you provide a _logcat_?

**Comment by henkz1** [comment]
@yuyoDev Is this the Note 3 with Helio X10 or Snapdragon 650 ? There are problems with adreno 510.. Not sure if anything is supposed to work on the emulator.

**Comment by yuyoDev** [comment]
@henkz1 Is Hexa-Core isnt Snapdragon, but te 2d examples works fine. The 3d demos they do not even start. :(
@RandomShaper I will upload a cat log soon. :)

**Comment by guilhermefelipecgs** [comment]
Maybe related to #11693

**Comment by Calinou** [comment]
Closing, as Godot 3.1 and later offer a GLES2 renderer which is better suited to mobile devices. Please report another issue if you're having trouble running Godot with the GLES2 renderer on a physical device or emulator.
