### ISSUE TITLE
One-time crash on quit (3.0a)

### ISSUE THREAD

**Issue by mcclure** [godotengine/godot#12112]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

OS X 10.12.6 (16G29) on a MacBookPro12,1 (retina).
Cloned git deefc2a63d36b6659630df703a9b98adffb893e9 (3.0, master). Built with `scons platform=osx -j4` and executed with `./bin/godot.osx.tools.64`.

**Issue description:**

On my second run, when I quit the editor it crashed (I opened the project manager, selected a project, opened the editor, made some changes, ran both normally and via F5, then quit by clicking the close button, I don't remember if I got the "quit?" dialogue or not). I got a stack trace and the message:

```ERROR: operator[]: FATAL: Index p_index out of size (size()).
   At: core/vector.h:137.
```

Attached is the STDOUT and the stack trace.

[crashreport.txt](https://github.com/godotengine/godot/files/1385109/crashreport.txt)
[stdout.txt](https://github.com/godotengine/godot/files/1385110/stdout.txt)

**Comment by poke1024** [comment]
Had the same crash today. First time I saw this.

**Godot version:**
a663dbfdd8465d45a03e4880c0d907334236b260

**OS/device including version:**
macOS 10.13.2

**Issue description:**
During quit Godot crashed. Happened only once, not reproducible.


**Steps to reproduce:**
n/a

**Minimal reproduction project:**
n/a

[crash-audio.txt](https://github.com/godotengine/godot/files/1592928/crash-audio.txt)

**Comment by Noshyaar** [comment]
Should be fixed by #15153
