### ISSUE TITLE
Viewport::_gui_find_control  May cause performance degradation

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#12137]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot 3.0 osx

**Issue description:**
main.gd

extends Control
func _ready():
	for i in range(0,4000):
		var img = TextureRect.new()
		img.texture=load("res://icon.png")
		add_child(img)

Moving the mouse quickly to observe FPS in the game window.

**Comment by Dillybob92** [comment]
if you spread them out   it'll only render whats on the canvas and no performance degradation is lost. i don't think there any use cases where a dev would need 4000 + images on the screen. can use a tilemap instead would prob be better :)

**Comment by cjmxp** [comment]
The 4000 one might be exaggerated. If it's a complicated scene, maybe this number

**Comment by cjmxp** [comment]
Mouse event processing may need to be optimized

**Comment by cjmxp** [comment]
In addition, Sprite also has this problem, not just the subclass of Control

**Comment by mhilbrunner** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*
