### ISSUE TITLE
duplicating node AND its resources (by making them all unique)

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1213]
Hi,

It would be cool if in addition to the "duplicate node" button (or Ctrl+D) of the editor, there was a "duplicate node and make all its resources uniques" button.

Because, currently, if I duplicate a branch containing many resources and want the copy not to share the resources with its source, i have to make each resource unique manually ...

**Comment by vichug** [comment]
it's the same if you use the "Sub-Scene" from the "Import menu" : the nodes are instanciated in current scene, even not linked to original scene's nodes, but the ressources are still linked to the original scene... and the "make resource unique" button does crash my godot a lot when not used correctly so i still didn't find how to make it work correctly :/

**Comment by vichug** [comment]
wait, now it seems that the resources are made local automatically......

**Comment by okamstudio** [comment]
resources and nodes will not reference the original scene (if they are
built-in) if you want this behavior you have to use the instance option


On Mon, May 11, 2015 at 8:37 AM, vichug <notifications@github.com> wrote:

> wait, now it seems that the resources are made local automatically......
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1213#issuecomment-100878865>.
>



-- 

*OkamStudio*

**Comment by vichug** [comment]
@okamstudio the original feature request remains however ; when a node is duplicated its contained resources are not made unique. This might be desirable for like external textures ; but for ie a collision shape it might be useful to have an option to make them unique by default imho

**Comment by reduz** [comment]
There is an option in the resource property menu to make it unique

**Comment by akien-mga** [comment]
> There is an option in the resource property menu to make it unique

Indeed. The feature request here would be to have a possibility *before* duplicating to ensure that all resources are made unique, and not having to do it manually for each resource. I personally don't need it but I see why it might be interesting to have.

I'm not sure about adding a new button for that though, that might add more bloat than anything. Maybe a modifier could handle that? e.g. Ctrl+D to dupliacte, Ctrl+Shift+D to duplicate and make resources unique. Or a way to specify the current duplication behaviour in a menu (i.e. tick either "Duplicate and link resources" or "Duplicate and make resources unique").

**Comment by MarianoGnu** [comment]
what about an option on inspector to make all resources unique? would be 3 clicks instead of 1 but usefull anyway...

**Comment by MarianoGnu** [comment]
the button is already there

https://i.gyazo.com/23dfc2c9473ddbe4f36a6886a5a4f63b.png

**Comment by akien-mga** [comment]
Yes but again, this feature request is for a way to duplicate AND make resources unique at the same time, without having to fix every duplicated node manually.

I could very see this done via the contextual menu, and an editor hotkey like <kbd>Ctrl+Shift+D</kbd>.

**Comment by SuperUserNameMan** [comment]
( just as contextual note : this feature request was formerly about Godot 1.0 or 1.1. )

**Comment by bojidar-bg** [comment]
What is the status on this issue though?

**Comment by PLyczkowski** [comment]
@SuperUserNameMan You can achive this via a plugin, like this: https://pastebin.com/P0BJD1aZ (the Duplicate With Script button).

**Comment by SuperUserNameMan** [comment]
Thank you @PLyczkowski.

**Comment by akien-mga** [comment]
Maybe another flag could be added for that as was done for signals, groups, etc. in #7856 by @RandomShaper?

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment]
There is something to take into account here: this request would mean ALL resources would be duplicated. You almost always dont want `Mesh`, `Texture`, `Video`, `Sound`, `GIProbeData` or `WhateverCustomTerrainData` to be duplicated, because that would be an insane waste to embed copies of these resources in the scene (or even in files). However these have something in common: they are almost always never embedded in a scene, they have a file of their own. Having a file also often means it's either a large resource, or *a resource meant to be re-used* (since you can't easily do that anyways if you embed them). With this considered, we could have the option to duplicate embedded resources only.

**Comment by akien-mga** [comment]
I agree with @Zylann, it's a dangerous operation to make "easy" and could lead to bad practices. I don't think there are many use cases for duplicating everything and making all resources unique, thus doubling their VRAM usage.

**Comment by 2blackbar** [comment]
Whta thhe hell you guys are talking about its not used that often? I make templates all the time as i dont want to start from 0 everytime and I NEED IT BADLY to be able to close all resources and everything in a scene, naming it player2 when original is player1 etc. this is very important and yet after a couple of years still nothing, is this a joke ?

**Comment by bojidar-bg** [comment]
@2blackbar This issue has not been updated in almost 2 years now. Nowadays, feature requests should be done as proposals on the https://github.com/godotengine/godot-proposals/ repository -- that way they can be discussed, workarounds can be considered, and a wider community consensus can be reached. In addition, filling out its issue template allows us to better see the root cause of users needing a thing, and thus address it better than just blindly adding features.
