### ISSUE TITLE
Godot 3.0: Particle trails don't work well with high 'explode' values.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#12133]
As I was starting to work using a daily build of Godot 3.0, I noticed with the particle object that the _explode_ value, when you move it to 1, actually makes it impossible to create clear and visible particle trails. The trails start showing up with values below 1, but only work fully when the value is 0.

One thing I noticed in all this is that the issue appears to be due to how the trails are constructed out of the total amount of particles to be emitted (so when all of the particle come out at once, so do all the ones that would otherwise be in the trails.

My idea anyway, the trails should be an **after-effect** of each particle emitted (with controls for length and resolution), that means it would be independent of the user-defined number of particles and the user defined timing (so even with _explode_ set to 1, a trail forms anyway. If you made 100 particles emit at once, there would be 100 trails).

------------------
Does this make sense as a behavior Godot should have, it would make it much easier to create things like fireworks (without having to resort to clunky workarounds using objects and GDscript)?

What do you think?

**Comment by reduz** [comment]
Trails are pretty broken, will rewrite how they work after 3.0

**Comment by reduz** [comment]
Did not have the possibility to work more on this for 3.1, will rewrite this for Vulkan for 3.2 and work on it by then.

**Comment by KoBeWi** [comment]
This was probably fixed with particles the recent rewrite. Comment if you can still reproduce the issue in 4.0-dev (you can try a [nightly build](https://hugo.pro/projects/godot-builds/), but keep in mind that only 3D particles are usable right now) and provide a minimal reproduction project.

**Comment by AceIsAwful** [comment]
@Ace-Dragon Death to you Ace, you cheap loser shill. Death to you for openly promoting the dumpster of society, AKA "universities" [more like DUMPSTERversities]. Death to you and death to all "universities" and every moron who supports those trashpits. death to you for praising those clowns who boast about their stupidity using the disgusting & childish & daft "titles". Death to every loser donkey who uses that disgusting & racist 2/6 letter donkey "title". Death to you for being such stupid mainstream shills and praising those daft morons. Death to you for commenting (and potentially supporting or have watched) that disgusting and racist movie, which starts with a disgusting 6-letter monkey word and is followed by "Strange" (I'm referring to that garbage thread you commented on in blenderartists, which was started by that inferior animal ARandomHowdy). Death to you for promoting those stupid childish ego pigs who use that disgusting clownish 6 letter word.

You're all nothing but useless shills. Your projects are nothing but utter trash, and You have no potential, and are a complete and utter laughable failure, Ace. Death to every idiot who uses the stupid 6-letter clownish "prefixes/titles" when mentioning first names. Death to "universities" [DUMPSTERversities]. Death to you Ace. Have a sad life and painful death, Ace.
And one other thing.There is no such thing as "software" "engineering". That is the stupidest and most pathetic lie ever. Shame on you for mentioning the word "engineering" when talking about development of game "framework". Stop being disrespectful to Engineering. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with scriptkiddies like you monkey game/software devs sitting behind a keyboard and writing code. Software/game dev is easy and for kids. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Quit making false claims against engineering. And stop being disrespectful to real Engineers (Mechanical Engineering is the ONLY Engineering).
Hope your dirty and cheap throats get slit, silly Ace.
