### ISSUE TITLE
Implement is_echo() for joypad button input

### ISSUE THREAD

**Issue by MoustafaC** [godotengine/godot#12145]
Ubuntu 17.04
x86_64
NVIDIA GeForce 750GTX, 378.13
Logitech F310 set to Xinput

According to the docs, the if_echo() function
> Returns true if this input event is an echo event (only for events of type KEY, it will return false for other types).

Is it possible to have button inputs return true as well?

For example, if I write a jump function as such:
```
	if ev.is_action_pressed("jump"):
		jump_attempt = true
	elif ev.is_action_released("jump") or ev.is_echo():
		jump_attempt = false

```
The character will jump only once when using a keyboard, but will keep hopping when using a joystick, making the behavior inconsistent between input types.

**Comment by akien-mga** [comment]
CC @Hinsbart

**Comment by Hinsbart** [comment]
I'm not in favor of adding echo events for joypad input.
For gamepad events, `ev.is_action_pressed()` will return true just once anyway so you should be able to achieve what you want without needing `is_echo()`

**Comment by MoustafaC** [comment]
I had added the ev.is_echo() function after the fact, because the character would take the jump input repeatedly while holding down the button. It worked for keyboard input, but not for the gamepad.

If it had been working as designed, I wouldn't have made the feature request. :/

**Comment by reduz** [comment]
I am noy sure if actions should be valid in echo characters...

**Comment by MoustafaC** [comment]
If there are technical reasons for not wanting to do this, or if there are better ways around it, I'm all ears.

In 2.0, I had to write this to get the desired result:
```
	if (ev.is_action("jump") && ev.is_pressed() && !ev.is_echo()):
		jump_attempt = true
	elif (ev.is_action("jump") && ev.is_pressed() && ev.is_echo()):
		jump_attempt = false
	else:
		jump_attempt = false
```
Now it's simpler, but it only works on one of two input devices. I'm just asking for consistency.

**Comment by reduz** [comment]
Maybe we could add in actions if they are supposed to support echo

**Comment by HummusSamurai** [comment]
@MoustafaC  Have you checked out the "is_action_just_pressed" function?

This works for joystick buttons and so you don't need the is_echo function for the required case example.

**Comment by MoustafaC** [comment]
@reduz If that's a possibility: great
@HummusSamurai it's not available under the _input() function, so I wouldn't be able to call it from there.

**Comment by MoustafaC** [comment]
Update: I tried using "is_action_just_pressed" and it doesn't seem to work as expected.

Expected results of "press and hold button" = jump once
Actual results = repeat jumps

**Comment by MoustafaC** [comment]
I think I just realized what I was doing incorrectly. I must have been calling a jump_attempt at two different and conflicting places, which lead to the issue at hand.

I now confirm that "is_action_just_pressed" works as intended in this instance.

My apologies.
