### ISSUE TITLE
Bullet PR: dynamic body property interpolation will freeze physic simulation for this body

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12146]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04, This issue is related to bullet pr, it's present in: https://github.com/godotengine/godot/pull/10013/commits/e6655f46e2cb9c4ec0681a2c227476fc55608cfc 
tested on release_debug build

**Issue description:**
With bullet it's impossible to interpolate property of dynamic body with physic simulation at the same time. I recorded very short vid that presents this issue:
https://www.youtube.com/watch?v=2xOa8tlY9zc&feature=youtu.be

**Steps to reproduce:**
Short way:
1. Download reproduction project.
2. Run `DynamicBodyTweener.tscn`

Long way:
1. Create new scene with proper rigidbody setup.
2. Ensure body is above the ground.
3. Add Tween node that operates in fixed step mode, interpolate rigidbody rotation with it.

**Link to minimal example project:**
[BulletInterpolationFreezeSimulation.zip](https://github.com/godotengine/godot/files/1386687/BulletInterpolationFreezeSimulation.zip)

**Comment by kubecz3k** [comment]
cc @AndreaCatania

**Comment by kubecz3k** [comment]
Also it would be worth to mention that I don't know if this is working in Godot physics engine by aware choice or just by some lucky 'coincedance'. So it might be worth if @reduz could share his thoughts.

**Comment by AndreaCatania** [comment]
Here your algorithm is not correct because to move a physics body (rigid body) you must apply forces or change its velocity.

In Godot physics it works but is not intend to work.

So if you want set its position use a kinematic body.

**Comment by kubecz3k** [comment]
I see that's what I though, but in fact I never used interpolation to move dynamic body, but to rotate it.

**Comment by AndreaCatania** [comment]
A rotation is a motion, so add a force or the linear velocity to translate the body, add a torque or the angular velocity to rotate it.
