### ISSUE TITLE
Cant import texture/bitmask on mac OS

### ISSUE THREAD

**Issue by peroman86** [godotengine/godot#12143]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

** Import -> Texture -> select the source path -> select the target path <res://> -> select 2D texture -> import -> get confirm message -> Accept -> nothing happens **

![image](https://user-images.githubusercontent.com/7108070/31597355-960305ac-b250-11e7-9613-516df9cda6bd.png)

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
