### ISSUE TITLE
Color.r8/g8/b8/a8 are floats rather than ints and don't compare as equal to integers

### ISSUE THREAD

**Issue by Nallebeorn** [godotengine/godot#12155]
**Operating system or device, Godot version:**
Windows 10, Godot master (8de1dc7)

**Issue description:**
According to the docs, Color.r8 and the other *8 members should be integers – this also makes perfect sense. However, turns out they're actually floats?

But what is even weirder, is that when comparing one of those values to an integer literal, the result is _not equal_. Even though a float and an int of the same value normally _are_ considered equal in GDscript.

**Steps to reproduce:**
Run this code (or check the example project):
```
var n = 4
var r8 = Color8(n, n, n, n).r8
prints("r8:", r8, "n:", n)
prints("type of r8:", typeof(r8), "type of n:", typeof(n))
print("(TYPE_REAL: ", TYPE_REAL, " TYPE_INT: ", TYPE_INT, ")")
prints("r8 == n?", r8 == n)
prints("float == int?", float(4) == int(4))
```

You will see that `typeof(r8)` is 3 (i.e. `TYPE_REAL`), rather than, like `n`,  2 (`TYPE_INT`).
You will also see that, even though `r8` and `n` are both 4, the boolean expression evaluates to `false`. However, the second boolean expression evaluates to `true` as is expected.

**Link to minimal example project:**
[Weird Color.r8 behaviour.zip](https://github.com/godotengine/godot/files/1388348/Weird.Color.r8.behaviour.zip)
The example project is just the above code. It prints to the console and then closes down immediately.

**Comment by Zylann** [comment]
Note: print() might crop the error margin that makes the comparison fail, so you can't find out if float numbers are really equal by printing them

**Comment by Nallebeorn** [comment]
Oh, that's a good point. I tried printing with decimal places using format strings, and the real value appears to be  4.000000236556 rather than 4.

So I suppose the comparison thing isn't so weird after all – although the type is still wrong.
