### ISSUE TITLE
Theme button does not look like a button

### ISSUE THREAD

**Issue by zinkkrysty** [godotengine/godot#12151]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOS 10.12.6, Godot 3.0 deefc2a

**Issue description:**

I was looking for how to edit the theme, and I didn't get it intuitively after poking around the interface. Only got a hint from [docs with screenshots of old UI](http://docs.godotengine.org/en/latest/learning/features/gui/gui_skinning.html).

![image](https://user-images.githubusercontent.com/570771/31614573-1d96b820-b287-11e7-9d7a-9407c3f59c5b.png)

The text "Theme" looks more like a label than a button/menu. Given that it's the only item on the whole row, I would expand it and have icon buttons for the submenus.

Intuitively, I was looking for something either in the Inspector panel or something in the toolbar of the scene:
![image](https://user-images.githubusercontent.com/570771/31614837-f5597432-b287-11e7-8366-1a3d99155825.png)

**Comment by volzhs** [comment]
yeap. it looks like a title label to me too.

**Comment by groud** [comment]
An Icon in front of it should do it I guess. :)

**Comment by zinkkrysty** [comment]
May I suggest we also change the wording to "Edit theme" or something like that? Currently it doesn't have an actionable name, it's more likely that people confuse it with a static label.

**Comment by djrm** [comment]
this has been solved.
