### ISSUE TITLE
Bullet PR: Ray shape logic is different than in Godot

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12156]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04, This issue is related to bullet pr, it's present in: e6655f4
tested on release_debug build

**Issue description:**
As far as I know ray shapes in Godot are a special kind of shapes ~that propagate/receives forces only along the ray normal~ (might be wrong, hope @reduz will clarify). Those are very handful in dynamic controller scenario, to deal with slopes or create hovers in a very easy way.
Quick Video: https://www.youtube.com/watch?v=Ff0qlG55t_E&feature=youtu.be

**Steps to reproduce:**
1. Download sample project
2. Run RayShapeTest.tscn

**Link to minimal example project:**
[BulletRayShapeSlopes.zip](https://github.com/godotengine/godot/files/1388488/BulletRayShapeSlopes.zip)

**Comment by kubecz3k** [comment]
@reduz can you give some details on how ray shape should exactly behave?
cc @AndreaCatania

**Comment by reduz** [comment]
Rayshape just pushes away the object in the ray direction

**Comment by AndreaCatania** [comment]
I can change it. @reduz the ray shape should receive forces only along its axis?

**Comment by reduz** [comment]
The ray shape just generates a contact pair between the cast intersection
and the endpoint. That needs to be fed to the manifold

**Comment by AndreaCatania** [comment]
@reduz So in this moment the shape behaviour is wrong and must be addressed?

**Comment by reduz** [comment]
@AndreaCatania I have no idea, as @kubecz3k mentions it doesn't work for him.
I was just explaining how it's implemented in the Godot physics. Basically it uses a custom narrowphase where it shoots a ray towrds the opposite shape. If a ray hits into somehting, it puts both the hit position and the ray endpoint (position + direction * length) as a contact pair and adds it to the manifold between both shapes.

**Comment by AndreaCatania** [comment]
In bullet it does the same thing, with the exception that it reacts to the floor shape that  in this case slide along the downhill. I should implement narrowphase algorithms to change this behavior.
I'll ask to Erwien if this is possible in an easier way.

**Comment by reduz** [comment]
Ah yeah, it should not slide downhill

**Comment by AndreaCatania** [comment]
Fixed: ce367016f4d1d97d998049287e70fe694377c061

**Comment by reduz** [comment]
Wow, amazing work

**Comment by kubecz3k** [comment]
Just tested! It works so beautifully now! You are truly awesome!!
