### ISSUE TITLE
Assign a nodepath in get_node() throw long name

### ISSUE THREAD

**Issue by JordanMotta** [godotengine/godot#12152]
**Operating system or device, Godot version:**
Debian 9.2, Godot v3.0.alpha.custom_build.8de1dc7

**Issue description:**
when i assign a NodePath in visual script, it throw a long name

**Steps to reproduce:**
![screenshot from 2017-10-16 10-04-10](https://user-images.githubusercontent.com/11588333/31616343-75d4b8e8-b25a-11e7-996d-9d14dd44f444.png)
![screenshot from 2017-10-16 10-11-16](https://user-images.githubusercontent.com/11588333/31616344-75eb1ebc-b25a-11e7-9bdc-e2d394ab4947.png)

- CallSelf get_node().
- Click in path.
- Assign a node.
- wow!

**Comment by akien-mga** [comment]
I'm almost sure it was reported already a couple days ago, but can't find it, so it might have been on another platform :)

**Comment by JordanMotta** [comment]
I thought that too.
