### ISSUE TITLE
Line highlighting seems inconsistent

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#12166]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor) cc7f224

**Issue description:**
When the line has nothing:
![screenshot at 2017-10-16 20-48-58](https://user-images.githubusercontent.com/30739239/31639848-d0519f8e-b2b9-11e7-90c7-d43d6770afed.png)
When it has only one character:
![screenshot at 2017-10-16 20-50-20](https://user-images.githubusercontent.com/30739239/31639854-d918165c-b2b9-11e7-9d13-7d1dc50b09bd.png)
More than that:
![screenshot at 2017-10-16 20-50-47](https://user-images.githubusercontent.com/30739239/31639855-de3eec50-b2b9-11e7-8a05-d4fadc333515.png)

**Comment by Zylann** [comment]
@toger5 ?
