### ISSUE TITLE
ceil() function seems not correct

### ISSUE THREAD

**Issue by fredlim** [godotengine/godot#1216]
Both ceil(3/2) and floor(3/2) return 1, seems weird.

In Excel =CEILING(3/2, 1) will return 2.

**Comment by reduz** [comment]
3/2 is 1 , remember they are both integers. maybe you meant ceil(3.0/2)

**Comment by fredlim** [comment]
In my case I increment the number using a for loop
[code]
for i in range(5):
    print(ceil(i/2))
[/code]

In that case it will not return my desire result. Is there any way to type casting the i to float?

**Comment by Sipaha** [comment]
You can write something like this:
print(ceil(i/2.0))
or use function "convert":
print(ceil(convert(i, TYPE_REAL)/2))

**Comment by fredlim** [comment]
I see, ceil(i/2.0) is more straightforward. Thank you.

**Comment by SolarLune** [comment]
@fredlim - If that solved your issue, feel free to close it.

**Comment by eska014** [comment]
Closing as user error.
