### ISSUE TITLE
Problem with AudioDriverManager

### ISSUE THREAD

**Issue by Tommel1234** [godotengine/godot#12162]
On fresh linux project-solus 3 and a build of godot 3.0 on the master branch from today

I have an error with the audioDriverManager when i run a fresh new project. It look like a can't play any sounds (I dont hear anything when I start the project)

I don't have any problem with the sounds with others apps! I have a Asus zenbook 305ca

**ERROR**: Index p_driver out of size (driver_count).
   At: servers/audio_server.cpp:162:get_driver() - Index p_driver out of size (driver_count).
**ERROR**: Condition ' !driver ' is true. returned: ""
   At: platform/x11/os_x11.cpp:93:get_audio_driver_name() - Condition ' !driver ' is true. returned: ""
**ERROR**: AudioDriverManager: all drivers failed, falling back to dummy driver
   At: servers/audio_server.cpp:153:initialize() - AudioDriverManager: all drivers failed, falling back to dummy driver
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 515 (Skylake GT2)

**Comment by akien-mga** [comment]
CC @marcelofg55

**Comment by marcelofg55** [comment]
Are you running godot with any arguments? Do you have pulseaudio installed and running?

**Comment by Tommel1234** [comment]
Nop without any arguments!  And yes pulseaudio is already installed with a fresh solus distro! I will try to build Godot again with and without mono to see if it still happening!

**Comment by Tommel1234** [comment]
So I have try to rebuild and I got the same issue without mono too.. I have done more test and I have try the Alpha 1... and surprise, I have no problem with this one, sound and music work with the old alpha 1 !

**Comment by Tommel1234** [comment]
Finally It was my fault, I had installed pulseaudio-devel but I needed pulseaudio-32bits-devel.. so I rebuild after installed it, and It work now !

**Comment by akien-mga** [comment]
Were you building the 32-bit version of Godot, with `scons p=x11 bits=32`? Otherwise there's no reason you'd need 32-bit devel packages on a 64-bit system.

**Comment by Tommel1234** [comment]
No, I dont know why.. I have run the recommends commands lines in the Godot doc to install ..  I can tell that I have try with pulseaudio-devel installed without success.. And finally succeed with pulseaudio 32.. It is strange because my computer use a 64bits platforms and I have not try to compile for 32bit!

**Comment by swipis** [comment]
you need pulseaudio-devel package. when you installed pulseaudio-devel32 also was installed and pulseaudio-devel. I build 64bit godot and had same problem however for me was enough to install pulseaudio-devel.

**Comment by nonunknown** [comment]
I'm using godot 3.2.2 beta 2 mono official  on ubuntu 20.04 and get this error

![Screenshot from 2020-05-24 14-32-11](https://user-images.githubusercontent.com/58845030/82760675-96137180-9dcb-11ea-838a-9b70d715cc9d.png)

ps: using godot 3.2.2 beta 2 or 3 stable (not-mono) the audio works fine

**Comment by akien-mga** [comment]
> I'm almost sure this problem is not related to the driver itself but with OS Permissions, since I am obligated to run Godot Mono as SUDO

Running Godot as root is not supported (and definitely a very bad idea). Why do you need to do it for the Mono version?

**Comment by nonunknown** [comment]
well I didnt need to do this under ubuntu 19.10 , but I'm having a lot of issues with permissions since installed ubuntu 20.04, for example in godot mono it cant even load the scripts

![Screenshot from 2020-05-25 07-56-44](https://user-images.githubusercontent.com/58845030/82806989-4d0bfd80-9e5d-11ea-95d7-b8711da42be5.png)

**Comment by akien-mga** [comment]
> Even GIMP cant open some project's folder....

That's not a Godot issue then, you should review the permissions of folders in your `$HOME`, and especially hidden folders like `~/.config` and `~/.local/share`.

Did you install Ubuntu 20.04 by keeping your `/home` partition, but creating a new user account with a different UID? If so you would indeed get such permission issues.

In any case, it's not related to this old issue.
