### ISSUE TITLE
Text selection behaves strangely

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12179]
Godot 2.1.4
Windows 10 64 bits

I don't know yet how I reproduced this, but it happened to me a few times:
When I double-click on a name or word, it gets selected as expected, but immediately changes to select only the part on the left of the cursor (it takes about 1 frame or 0):

![image](https://user-images.githubusercontent.com/1311555/31666338-c13ec8f2-b343-11e7-98be-e99f2bd9427b.png)

I expected the whole word to be selected.

**Comment by bojidar-bg** [comment]
I remember seeing this as well.

**Comment by Listwon** [comment]
2.1.4 stable build, right? I tried to reproduce it and the only thing that comes to my mind (and worked) is when you slightly move your mouse while double clicking. But I don't think that it's a bug, so we need more info.

**Comment by Zylann** [comment]
Well unfortunately I have no idea how it happened, but I can tell it wasn't just potentally the mouse slightly moving, it just started to behave wrong no matter what I tried.

**Comment by Zylann** [comment]
Update: I tried again on the other PC and it happened straight away. I just opened the project, opened a script, double-clicked on a word, and it selected only the left-hand of it.

**Comment by bojidar-bg** [comment]
Not sure completely, I just observed it "indirectly", by double-clicking then pasting (for manual renaming of variables), and sometimes only the left half of the variable would be replaced.
I still think it had something to do with how I selected the string, who knows...

**Comment by bojidar-bg** [comment]
Aha, just reproduced it!
It happens when you move the mouse slightly after the second click.

Happens on 3.0 as well.

**Comment by Zylann** [comment]
@bojidar-bg you mean, during the double-click? I'm pretty sure my mouse wasn't moving when I reproduced it last time.

**Comment by bojidar-bg** [comment]
@Zylann No, not during the double click, but while you are still holding the mouse after the second click.

**Comment by lmjk** [comment]
This is still reproducible in 2.1 as of 74a8a91da3e71ccb2e56e477aff104a5fbcee155.

**Comment by bojidar-bg** [comment]
It still hasn't been backported, but would probably be before 2.1.5.

**Comment by Zylann** [comment]
On the same computer on which I reproduced this issue first, I found this #20086
It could have been related.
