### ISSUE TITLE
Bullet PR: ray shape falling inside and bouncing from conclave collision shape triangles. 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12177]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
This issue is relate to Bullet pr: 59ac299
Tested on ubuntu 17.04 release_debug build

**Issue description:**
Ray collision shape don't cooperate well with conclave collision shapes of static bodies, especially in a scenario where conclave collision shape is level floor and ray shape is used to be a base of dynamic body.
Please look at video that presents how this is behaving currently(godot physic engine), and how the same project is behaving in Bullet: 
https://youtu.be/Fd-ge51ZTT8

**Steps to reproduce:**
1. Download sample project
2. Run RayShapeTest.tscn
3. Try to navigate a character a little through the level with arrow keys.
4. Observe that character sometimes bounces from floor triangles
5. Observe that character ray shape sometimes is falling into level geometry. 

**Link to minimal example project:**
[BulletRayBounceAndFall.zip](https://github.com/godotengine/godot/files/1390913/BulletRayBounceAndFall.zip)

here is a source blend file for this level, just in case: 
[Level_test.blend.zip](https://github.com/godotengine/godot/files/1390920/Level_test.blend.zip)

**Comment by kubecz3k** [comment]
@AndreaCatania very sorry! But looking at this from the bright site, I think this one is the last one that is related to dynamic character controller :)

**Comment by kubecz3k** [comment]
related issue #12156

**Comment by AndreaCatania** [comment]
Fixed ce367016f4d1d97d998049287e70fe694377c061

I can give you an advice, if you intersec a bit the ray with capsule in your character you can avoid some problems
![untitled](https://user-images.githubusercontent.com/8342599/32173516-9115cc66-bd7f-11e7-95e4-418cd5078c29.png)

**Comment by AndreaCatania** [comment]
It's fine, let me know if this commit resolve it even in your side

**Comment by kubecz3k** [comment]
@AndreaCatania Tested! It works beautifully! Thank you so much! :heart:
