### ISSUE TITLE
Visual Script Node Path Buttons Overlap Each Other

### ISSUE THREAD

**Issue by LucasKA** [godotengine/godot#12176]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OSX v3.0.alpha.custom_buildcc7224

**Issue description:**
Tried to assign a node path to VisualScriptSceneNode and the Buttons overlap, making it difficult

**Steps to reproduce:**
- Drag a scene node into the Canvas.
- Click on the Node in Canvas
- Go to the inspector, and click the file icon in VisualScriptSceneNode
- Notice the overlapped buttons

<img width="675" alt="screenshot 2017-10-16 04 51 08" src="https://user-images.githubusercontent.com/1824267/31664793-d1428232-b381-11e7-8b14-ba705f1e3a69.png">

**Comment by LucasKA** [comment]
Actually this seems to be affected anywhere that the Assign/Clear Button ste is used. Not just in the visual scripting.

**Comment by akien-mga** [comment]
Seems fixed in the current master branch:
![spectacle h32490](https://user-images.githubusercontent.com/4701338/34644829-6a28b128-f33e-11e7-97cb-c2b6e96a6da9.png)
