### ISSUE TITLE
unclear InputEventMouse positions values

### ISSUE THREAD

**Issue by Jerome67000** [godotengine/godot#12175]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 master from 16/10/2017

**Issue description:**
`position` and `global_position` have unclear values / behaviors.
`global_position` is always at 0,0 when used in `_input`.

Clearer solution can be to have same value for `position` and `global_position` when used in `_input()` and different ones when used in `_gui_input()` with `global_position` always with the position relative to the viewport and `position` relative to the current Control node.

Hello @groud and @reduz 

![image](https://user-images.githubusercontent.com/7358899/31663431-69c79078-b342-11e7-9bf3-129234b5ba8d.png)

![image](https://user-images.githubusercontent.com/7358899/31663487-915ee5a0-b342-11e7-9760-5f3b740cdce7.png)

**Steps to reproduce:**
print event.position and event.global_position in _input and _gui_input

**Link to minimal example project:**
[doc.zip](https://github.com/godotengine/godot/files/1390885/doc.zip)

**Comment by reduz** [comment]
This can be done in SceneTree::input method I guess, in case anyone cares.

**Comment by leiget** [comment]
Seems to be working now. I just compiled the newest master update as of 12:19 pm CST on Nov. 8.
![mouse_input_prob](https://user-images.githubusercontent.com/20325471/32567301-7689b5a8-c480-11e7-90cc-da8f4b40e560.jpg)

**Comment by Jerome67000** [comment]
Seems to be good :)

**Comment by bojidar-bg** [comment]
@Jerome67000 So, this can be closed now?

**Comment by Jerome67000** [comment]
Yes
