### ISSUE TITLE
Backport color arithmetic 

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#12180]
**Issue description:**
Currently there is no way to make sum, subtractions, multiplications and such with `Color`

**Steps to reproduce:**
Try this
```GDScript
extends ColorFrame

onready var init_modulation = get_modulate()

func _ready():
    set_modulate(init_modulation + Color(0.3, 0.3, 0.3, 0.0))
```
Currently it is returning an error: *Invalid operands 'Color' and 'Color' in operator '+'*

**Comment by Sslaxx** [comment]
Note that this is for Godot 2.1.4.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
