### ISSUE TITLE
shell_open with is_action_pressed causes a multitude of issues

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#12188]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2.1.4, 3.0

**Issue description:**

Whe using `OS.shell_open` via a link button, or a `button_down` signal, causes:

- The game window will become unmovable when alt-tabbing back and clicking somewhere
- The hand cursor doesn't revert back to the normal icon 
- Other signals do not get emitted when you return to the window... (after clicking, hover your mouse over the label, nothing will print bcz the mouse_enter signal gets blocked)

**Link to minimal example project:**
[button shell_openbug.zip](https://github.com/godotengine/godot/files/1392414/button.shell_openbug.zip)

 
This is on windows 64-bit btw... so i bet it's prob a windows issue tbh :P

**Comment by Dillybob92** [comment]
Did some more testing and changed the title. This occurs not just for BaseButtons or LinkButtons or whatever. It happens whenever OS.shell_open is called after a `event.is_action_pressed("lmb")`

**Comment by Dillybob92** [comment]
Ok, so I found a temporary solution for this if anyone stumbles on this before the lead devs :)

Use "pressed" if using BaseButton or `event.is_action_released("lmb")` (if using a ` input_event` signal).

Seems like the mouse has to be released before OS.shell_open gets called, or bad.. bad things happen!

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
