### ISSUE TITLE
Option to startup Godot in fullscreen

### ISSUE THREAD

**Issue by mamarilmanson** [godotengine/godot#1218]
I sometimes find it frustrating that everytime I open the editor it just covers more or less 3/4 of my screen... I hope the editor can start and is already in fullscreen or whatever the last sate I left it the last time I opened it or a project...

:)

**Comment by UsernameIsAReservedWord** [comment]
if you mean "maximized windows", i agree and i +1.

if you actually mean "fullscreen", you can activate it into the project settings of the Scene menu.

**Comment by UsernameIsAReservedWord** [comment]
PS : about the second sentence i wrote, i was wrong. so you can ignore it. however, there is command line argument that allow you to run the editor fullscreen : `godot.exe -f` or in a specified size `godot.exe -r WIDTHxHEIGHT`. so you can create .bat or .sh script to lauch the editor the prefered way

**Comment by reduz** [comment]
some guys are working on proper window handling functions, so this feature
should appear when they are done

**Comment by mamarilmanson** [comment]
I'm sorry, I really meant "maximized windows..."

thanks for clarifying... :D

**Comment by mamarilmanson** [comment]
So that means there is something like the "UI department of 
development???" what do they have planned to release next? can you tell us?

**Comment by adolson** [comment]
No. There are just contributors filling a gap. Next, they will hopefully find another gap and fill that. And then another.

**Comment by mamarilmanson** [comment]
so this might be another little gap to fill in? :)

**Comment by akien-mga** [comment]
Related to #2291 on X11.

**Comment by vnen** [comment]
@akien-mga I'm closing this since the editor now opens maximized by default. If some on wants an option to _not_ start maximized, they may open another issue.
