### ISSUE TITLE
ERROR: get_child: Index p_index out of size (data.children.size()).

### ISSUE THREAD

**Issue by Listwon** [godotengine/godot#12189]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.x editor, custom build, target=release_debug (no errors in 2.1.4 stable build)
Linux Mint 18.2

**Issue description:**
ERROR: connect: Condition ' s->slot_map.has(target) ' is true. returned: ERR_INVALID_PARAMETER
   At: core/object.cpp:1367.
ERROR: get_child: Index p_index out of size (data.children.size()).
   At: scene/main/node.cpp:821.

Second error repeats "randomly". Every time I move editor window or do something like adding new nodes, it is printed two times.

**Steps to reproduce:**
Just create new empty project.

**Comment by Listwon** [comment]
I've just tested and it's working properly :)

**Comment by akien-mga** [comment]
You reopened because it's not fixed in the end, or by mistake?

**Comment by Listwon** [comment]
#12197 fixed s->slot_map, but ERROR: get_child: Index p_index out of size (data.children.size()) is still present in empty projects.

I found another clue. Errors (get_child: Index p_index out of size) appear as long as the scene tree contain only Node2D nodes. Adding ie. one Sprite node stops raising errors.

**Comment by Listwon** [comment]
Ok, I was wrong. I reproduced it many times (as I said, empty project) and the actual thing which stops the errors is not the Sprite node, but any, even empty *.gd file in project directory.

**Comment by akien-mga** [comment]
Fixed by #16726.
