### ISSUE TITLE
Audiostream does not play in webassembly export?

### ISSUE THREAD

**Issue by stubbsy345** [godotengine/godot#12182]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OSX, godot 3.0

**Issue description:**
Audio plays fine locally. But fails to play when played in webassembly export and no errors appear in the debugger so nothing to indicate what is going wrong. *.wav are set to export.

**Comment by marcelofg55** [comment]
Audio is not yet implemented in webassembly.

**Comment by eska014** [comment]
Duplicate of #11804
