### ISSUE TITLE
Error exporting to android in godot version 3.0

### ISSUE THREAD

**Issue by Saikol** [godotengine/godot#12192]
SO: Ubuntu 16.04, Version: Godot 3.0

I HAVE HAD A PROBLEM WHEN EXPORTING A PROJECT FROM THE VERSION GODOT 3.0 TO ANDROID. IT DOES NOT WORK AND LAUNCH THE MESSAGE "HAS BEEN STOPPED" WITH DIFFERENT MOBILE DEVICES HAPPENS THE SAME SITUATION

http://www.mediafire.com/file/eadchr4df1vj541/vr_godot3.tar.gz

**Comment by akien-mga** [comment]
WHAT VERSION 3.0 ARE YOU REFERRING TO?

**Comment by Saikol** [comment]
Godot version 3.0.alpha.custom_build.8de1dc7

**Comment by akien-mga** [comment]
Did you build Android export templates from the same commit? Keep in mind that you can't use templates from Godot 2.1.x or even 3.0-alpha1 if you're using a self-compiled editor binary.

**Comment by rraallvv** [comment]
I compiled Godot and the Android template both from the same commit and copied the apk file to **~/.godot/templates** but the editor is not showing anything in the manager. I'm running Godot directly from `$./bin/godot.osx.tools.64`, is there something else I need for the editor to pick find the exporters?

Any help or comment is appreciated.

![screen shot 2017-10-30 at 3 35 10 pm](https://user-images.githubusercontent.com/1840524/32191595-041980f6-bd88-11e7-841f-e29c15a8914d.png)

**Comment by akien-mga** [comment]
The layout changed a bit in the master branch, you now need to put your templates in: `~/.godot/templates/3.0-alpha/`, and you should also add a `version.txt` file in `~/.godot/templates/3.0-alpha/` the string "3.0-alpha" in it. It's a bit convoluted but it will allow us to propose automatic downloads of the right version for your editor in the future.

**Comment by rraallvv** [comment]
@akien-mga thanks a lot!

**Comment by fabricadegame** [comment]
That happens to me as well. Can anyone explain why?

**Comment by vnen** [comment]
@fabricadegame there are many things that could cause this. Please refer to other [community channels](https://godotengine.org/community) to ask for help. If you find it's indeed an engine bug then you can open a new issue here.
