### ISSUE TITLE
Exported NodePath reverts to string "Null" in undefined niche case.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#12205]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0

**Issue description:**
Somehow, attempting to reset an edited export variable for a NodePath was setting it to the string value "Null" rather than ACTUALLY setting it to `null` or clearing it properly. I know this because evaluating `if node_path` was returning true and evaluating `if node_path.is_empty()` was returning false. Printing it would print "Null" to the screen, and doing `get_node(node_path)` would result in a "Condition '!node' is true" error. (Edit: I just tested using typeof() on it, and it returns 15 even though it's printing "Null" and getting through the conditions described above). If I specifically "Clear" the field, then the `if node_path` if statement properly blocks it.

This same script was attached to 4 different nodes (two nodes per instanced scene, the same scene instanced twice in a larger scene) and only 1 of them was malfunctioning in this manner (the last one in the node hierarchy - don't think that's relevant though). 

**Steps to reproduce:**
I have not been able to reproduce this bug in smaller example scenes, so I'm not yet entirely sure what causes it. I attempted to put two child nodes with a script with an exported NodePath underneath a parent, and then instance that scene twice in another scene, altering the values for all four nodes' scripts from the default `null` value. None of them exhibited the abnormal behavior.

**Link to minimal example project:**
[Here is a link to my GitHub project at the relevant commit](https://github.com/willnationsdev/godot-skills/tree/4936d52faaeca86b6d58e8f3aac063e857f7b167) where the bug was happening. The scene file I was testing was `test.tscn`. Node at `/root/world/SkillUser2/skills/print_user_skill/targeters/npt2` was the erroring one.

Here is a GIF of the bug in action. The "Null" content showing up here is the state it was in when I was still getting through if statements and such. You'll notice that clicking the "revert" button doesn't actually make the "revert" icon go away like it normally would, even though the default value IS `null`.

![ice_video_20171017-225655](https://user-images.githubusercontent.com/16217563/31700799-6130a28e-b391-11e7-8853-38cf62113056.gif)

**Comment by reduz** [comment]
@bojidar-bg

**Comment by bojidar-bg** [comment]
Not sure how you got to this state, but the problem is in `demo/scenes/SkillUsers/test_skill_user.tscn`, which has `Null` written out as a string (and not the value null).
Can't reproduce from clean state either, and I can't say it is a bug anymore.

**Comment by willnationsdev** [comment]
@bojidar-bg Wait what? Did I seriously do that and miss it during debugging? Ugh...well then...fancy that. Sorry to have wasted your time on this. Yeah, I'll just close this.
