### ISSUE TITLE
'area_enter' signal of Area 3D is unreliable.

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#12210]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64 - master f52ab8d

**Issue description:**

Expected: all areas entered triggers area_enter.
Happened: some areas entered don't trigger area_enter.

**Steps:**
1. Create Areas with Cube-shape CollisionShape
2. Move one into another during physics_process. Maybe script them to `queue_free` when collided.
3. Observe that some of them ignore the collision entirely.

**Link to minimal example project:**

[sandbox.zip](https://github.com/godotengine/godot/files/1394538/sandbox.zip)

**Comment by Phobos1337** [comment]
I think you should disable the area monitorable parameter before "queue_free" the element :
`what.get_child(0).set_monitorable(false)`

**Comment by sketchyfun** [comment]
Related to this I believe https://github.com/godotengine/godot/issues/8856

**Comment by kubecz3k** [comment]
would be worth to recheck now (after #12641)

**Comment by Noshyaar** [comment]
Fixed by bullet. 🎉  Should I close this or leave it open until it also works with GodotPhysics?

**Comment by kubecz3k** [comment]
@Noshyaar the only planned physic engine for 3.0 is the one from bullet. For now there is ability to change them in project settings only to allow people compare easier

**Comment by Noshyaar** [comment]
Then R.I.P. GodotPhysics

**Comment by kubecz3k** [comment]
Also migration to bullet should be really smooth. As far as I know the only thing that is different is that there is no need to apply gravity during the manual integration.
