### ISSUE TITLE
Bug? Particles2D.one_shot = true does not set emitting to false like in 2.1.4

### ISSUE THREAD

**Issue by Stratos695** [godotengine/godot#12218]
I'm not sure if this is intended or a bug.

As the title says, when using Particles2D.one_shot=true the emission gets stopped (visually), but the emitting bool stays true.

**Comment by cbscribe** [comment]
I noticed this is labeled "discussion", so I'll chime in. 

"One_shot" is useful for limited emissions you want to trigger at a certain time.  You may want to `queue_free()` upon completion, or trigger another emission but only if one isn't currently occurring.

Without "one_shot" setting `emitting` to `false` upon completion of the emission cycle, and no "emission_finished()" signal, we can't tell if a one-shot emission has ended.

**Comment by reduz** [comment]
it does, but it's not visualized in the editor. It's kind of a hassle if you want to animate it. 
I will prefer we wait until 3.1 when the property editor is reworked to fix this properly, so kicking
