### ISSUE TITLE
Disabling button in handler derails button logic

### ISSUE THREAD

**Issue by rcurtis** [godotengine/godot#12217]
**Issue description:**
Disabling a button in a 'button_down' handler will cause the button to return to the pressed state, not the normal state.

**Steps to reproduce:**
Add a TextureButton and Timer to a scene.  Make a new script on the root of the scene.  Connect the 'button_down' event to a listener.  In this listener, set the button to disabled (button.set_disabled(true)).  And start the timer.  When the timer expires, set the button to enabled (button.set_disabled(false)).  The button will now be in the pressed state forever.

You can get it out of the pressed state if you hold the mouse down over the button through the entire time the timer is counting down, only releasing after the button has returned to 'pressed' state.

**Link to minimal example project:**
[ButtonTest.zip](https://github.com/godotengine/godot/files/1395731/ButtonTest.zip)

**Comment by Noshyaar** [comment]
Version?

**Comment by rcurtis** [comment]
Version's I've found it on:  2.1.3, 2.1.4, and 2.1 HEAD. It probably affects the 3.0 line as well.

**Comment by mhilbrunner** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by EveAwesome** [comment]
I have found this to also be the case in version 3.0.

In my case, the button is a toggle which is part of a button group.  I would like to be able to disable the group or the buttons during gameplay, and have the player's current choice remain visible as a down button but prevent them from making adjustments during the disabled time.

It's not necessarily a bug, but it seems that the disabled state has overrides the down state of my button group, and sense I don't have a disabled state set it reverts to the up state.

**Comment by EveAwesome** [comment]
I found a dumb work around.  It wasn't working well and taking way too much code to solve a similar problem.  I want the user to be able to adjust settings with controls, but while they play out the a short game those controls are visible but not editable until they start a new game. Part of this UI includes a group of toggle buttons.  If I simply disable the branch with my UI, then the selected (down toggled button) is no longer visually pressed.

So my easy but dumb work around was to put a ColorRect over the buttons and set the opacity to 0. The color rect masks the part of the UI I don't want to change, and I simply show/hide this node which is invisible, but doesn't allow clicks to register with the buttons underneath.  I just wanted to post this out-of-the-box solution in case anyone else was having trouble with the limitations of pause and disable.

**Comment by reduz** [comment]
This should be more or less easy to fix, may need some logic in the set_disabled() function, check:

https://github.com/godotengine/godot/blob/master/scene/gui/base_button.cpp#L313

**Comment by CosineP** [comment]
Working on this one. What's the desired behaviour in this case:

1. I press button, button is disabled
3. I continue holding
4. Button is enabled while holding

Should it be pressed or not?

**Comment by CosineP** [comment]
As for your *specific* issue of displaying toggle value while disabled. This doesn't jive with what I'm seeing in the code, the button can only be `DISABLED`, `HOVER`, `PRESSED`, or `NORMAL`, no "`DISABLED_PRESSED`" / "`DISABLED_NORMAL`". Do you think maybe if you believe that functionality should be in Godot, you could put that part into a separate issue for its own discussion?

**Comment by akien-mga** [comment]
See #22062.
