### ISSUE TITLE
Implement a new TubeMesh primitive

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#12239]
Read Bastiaan comment.

**Comment by BastiaanOlij** [comment]
Just to add this before I forget. After discussing this on IRC it seems a nice addition would be to create a new primitive called TubeMesh which is basically a hollow cylinder based on the CylinderMesh code but with:
top_outer_radius
top_inner_radius
bottom_outer_radius
bottom_inner_radius

**Comment by YeldhamDev** [comment]
@BastiaanOlij Changing the title to accommodate the new suggestion.
