### ISSUE TITLE
Can't properly run godot from terminal on macOS

### ISSUE THREAD

**Issue by ericdsw** [godotengine/godot#12235]
Operating system: macOS High Sierra

I've been trying to run Godot directly from the terminal, but no matter what I try, all commands lead me to the project selection screen rather than what's on the documentation.

I've been trying to do the following actions via the terminal:
- Opening godot directly in my project (using the command ```godot -e```)
- Running a scene directly (command: ```godot path/to/scene.tscn```)
- Running a script directly (command: ```godot -s path/to/script.gd```)

However, calling any of them only leads me to godot's initial project selection screen.

To give a little more context on my setup, I've created an alias called ```godot``` which points directly to ```Applications/Godot.app/Contents/MacOS/Godot```.

I don't know if this behavior is related directly to the executable, to the process where the generated binary is packed inside a .app or if it's an OS limitation (I doubt it's the last one, as Sublime Text also allows you to invoke it directly from the terminal in the same way and everything works fine); but I have also tried to do the following steps:
- Cloning and compiling the repo directly from https://github.com/godotengine/godot/commit/b61462268e9a8a2c86c1abd5bc65cd96659fa979 (followed the instructions in [Compiling for OSX](http://docs.godotengine.org/en/stable/development/compiling/compiling_for_osx.html))
- Running the generated executable with the same 3 commands listed above: **it works**
- Packing the executable inside a .app (again, following Compiling for OSX)
- Running the executable ```/Content/MacOS/Godot``` that is inside the .app: **same behavior described above (doesn't work as expected)**

**Comment by donkeybonks** [comment]
This isn't practical anyway, there is a window focus issue with godot when run from the terminal on OS X. It needs to be packed inside and run from the app to integrate properly.

**Comment by bruvzg** [comment]
When executable is inside .app bundle it's working directory is set to "/Contents/Resources" regardless whether you run it as bundle or from terminal, bundle is detected by [looking for "Info.plist" file](https://github.com/godotengine/godot/blob/master/platform/osx/godot_main_osx.mm#L68).

**Comment by akien-mga** [comment]
> When executable is inside .app bundle it's working directory is set to "/Contents/Resources" regardless whether you run it as bundle or from terminal, bundle is detected by looking for "Info.plist" file.

That explains the issues. If you run the above commands with `--path $(pwd)` it should work.

Closing as there's nothing we can fix as far as I understand; though it might be worth adding to the macOS-related documentation.
