### ISSUE TITLE
Settings sometimes don't register when clicking enter

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#12233]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04, [Build](https://bintray.com/calinou/godot/editor) fe08257

**Issue description:**
When setting something by clicking enter, it will sometimes go back to the previous value:
![bug](https://user-images.githubusercontent.com/30739239/31778304-0caf3344-b4cf-11e7-97d5-3d519b0424e4.gif)

**Comment by akien-mga** [comment]
Can you still reproduce this in the current master branch?

**Comment by vnen** [comment]
I experienced this recently.

**Comment by akien-mga** [comment]
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by YeldhamDev** [comment]
It seems that the new property editor has fixed this, as it doesn't happen to me anymore. Closing it.
