### ISSUE TITLE
bad message when no main scene has been set

### ISSUE THREAD

**Issue by elisha464** [godotengine/godot#12237]
![image](https://user-images.githubusercontent.com/1371635/31785815-09064698-b50f-11e7-9fac-a716676be3ba.png)

**Comment by kriw** [comment]
It seems it's been already fixed at master branch, but the binary from ![the home page](https://godotengine.org/download) has the bug.

I built the latest commit at master branch (last commit is 6a363ad4704cbfa916b0e10491855221a4680b8e).
The platform is x11.

![screenshot from 2017-10-19 23-10-32](https://user-images.githubusercontent.com/13299299/31794611-2ce7ebf2-b523-11e7-8e6d-06ad3ca4479e.png)

**Comment by Noshyaar** [comment]
Fixed by #12244
