### ISSUE TITLE
[3.0] Members of InputEventMouseMotion give error.

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#12231]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 3.0 Alpha

**Issue description:**
InputEventMouseMotion.speed or InputEventMouseMotion.relative give error "Invalid get index "speed/relative (on base "GDNativeClass")".
I try rotate camera by use relative position (FPS).

**Comment by volzhs** [comment]
it would be better if you add your codes.

it works fine with this codes to me.
```gdscript
func _unhandled_input(event):
    if event is InputEventMouseMotion:
        print(event.speed)
```

**Comment by sezit** [comment]
Hmm... It is necessary to get used to the changes in GD. All works.
