### ISSUE TITLE
get.pixel always returns zero (black)

### ISSUE THREAD

**Issue by monotonehell** [godotengine/godot#12245]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows64 3.0 alpha (from calinou's build cc7f224) OpenGL ES 3.0 Renderer: AMD RADEON HD 6350

**Issue description:**
Requesting a pixel colour from a TextureFrame works in V2.1.4 however the same operation attempted in V3.0 on the TextureRect always returns 000000.

**Steps to reproduce:**
New project, add a home node, add a button to home, add a TextureFrame/Rect to home.
Attach a script to the button's onPressed event.
V2.1.4

	var myimage = load("res://icon.png")
	var myicon = get_node("/root/home/TextureFrame")
	myicon.set_texture(myimage)
	print("Should be #ffffff: ",myicon.get_texture().get_data().get_pixel(32,32).to_html(false))
	print("Should be #5e88a8: ",myicon.get_texture().get_data().get_pixel(32,18).to_html(false))

V3.0

	var myimage = load("res://icon.png")
	var myicon = get_node("/root/home/TextureRect")
	myicon.set_texture(myimage)
	print("Should be #ffffff: ",myicon.get_texture().get_data().get_pixel(32,32).to_html(false))
	print("Should be #478cbf: ",myicon.get_texture().get_data().get_pixel(32,18).to_html(false))
	
Save, run and press button
V2.1.4 outputs:
    Should be #ffffff: ffffff
    Should be #5e88a8: 5e88a8

V3.0 outputs:
    Should be #ffffff: 000000
    Should be #478cbf: 000000

**Link to minimal example project:**
[testGetPixel.zip](https://github.com/godotengine/godot/files/1400544/testGetPixel.zip)

**Comment by Zylann** [comment]
I had a similar issue on different use case. It's because in 3.0 textures are imported as StreamTextures by default (instead of ImageTexture), and they don't support download of pixels from the graphics card yet, AFAIK. Last time I tried I also saw there is no choice on the import dock #10719

**Comment by monotonehell** [comment]
After a bit more experimentation, I'm unsure if this is an actual 'bug', but instead a 'breaking change'.
The following works in V3.0
	var myimage = load("res://icon.png")
	var myicon = get_node("/root/home/TextureRect")
	myicon.set_texture(myimage)
	var theimage = myicon.get_texture().get_data()
	theimage.lock()
	print("Should be #ffffff: ",theimage.get_pixel(32,32).to_html(false))
	print("Should be #478cbf: ",theimage.get_pixel(32,18).to_html(false))
	theimage.unlock()
	
It seems that locking is mandatory now and the syntax...
`myicon.get_texture().get_data().get_pixel(32,32).to_html(false)`
...is no longer valid, even with locking.

Not sure if this should be closed, or if it needs to be looked at further?

**Comment by Zylann** [comment]
Oh... I didn't expect lock() to be mandatory here... I know it is for setting pixels, but for reading them? Is this new?

**Comment by reduz** [comment]
yes locking is required now, so closing this issue.

**Comment by arcanis** [comment]
Lock doesn't seem to exist in Godot 4, what should we do now? I still get black pixel when using get_pixel.

**Comment by rolevax** [comment]
> Lock doesn't seem to exist in Godot 4, what should we do now? I still get black pixel when using get_pixel.

Worked by calling decompress() before get_pixel()
