### ISSUE TITLE
Official Wiki is not accesible for everyone.

### ISSUE THREAD

**Issue by genete** [godotengine/godot#1224]
It is highly frustrating to not allow the community to edit the official wiki. I know that there is one *community wiki* (1) but I think that duplicates efforts unnecessary.

Please open the wiki write rights to the community (2). Maybe first to a small group of confident people, and later to everyone by invitation. It is ready for group collaboration (3) 

As Github wiki is a git repository, it is not a big deal to handle with mistakes or vandalism is case it appear. Just reset to stable version and that's all. (4) 

(1) http://godot.azurewebsites.net/
(2) https://help.github.com/articles/changing-access-permissions-for-wikis/
(3) https://help.github.com/articles/adding-and-editing-wiki-pages-locally/
(4) https://help.github.com/articles/viewing-a-wiki-s-history-of-changes/

**Comment by genete** [comment]
Moreover it is a detailed permission levels for collaborators in one organization repository. 
https://help.github.com/articles/permission-levels-for-an-organization-repository/

**Comment by Nulifier** [comment]
I personally think that the simplest solution is to start really using the community wiki. I have had a lot of experience working with wikis for other projects and I don't think a github wiki really has the tools needed to make the documentation what it needs to be, like templates and moderating.

I noticed one of the big issues with the community wiki is that it was missing most of the API documentation so I started added the documentation of the classes similar to what is available on the github wiki. I would have continued this but the community wiki is down....

I think the proper solution is to port the information that is in the github wiki over and then have just one official wiki based on a mediawiki setup.

**Comment by slapin** [comment]
I'd prefer openning github wiki in organized way/premoderation.

**Comment by slapin** [comment]
Github wiki contains everything needed to write documentation and it is already there and thrilling.

**Comment by adolson** [comment]
I asked for write access to the official wiki a year ago. It's not happening, so just like begging for Lua support, it's time to give it up. :P

And so, I agree with Nulifier. However, if we're looking at moving everything to OpenProject or similar, we may as well just keep the status quo for now, and hope the migration happens sooner than later.

**Comment by reduz** [comment]
The problem with official wiki is that it's affiliated with Okam at this
point. This will eventually change and we are looking forward to a more
open for contributions platform such as openproject in a self hosted azure
server. This will likely happen in March after GDC as currently both Ariel
and I are too busy to plan and do all the move.

The plan is to move the wiki, forum and issue tracking, to something
separate.

**Comment by nicolas33** [comment]
Since the wiki is usual git repository, isn't it possible to just send git pull requests?

**Comment by adolson** [comment]
Not unless they changed something recently.

**Comment by nicolas33** [comment]
On Thu, Feb 19, 2015 at 04:34:10AM -0800, adolson wrote:
>    Not unless they changed something recently.

I guess they don't have to. Anyone could:

1. Clone the wiki repository.
2. Push it to another github repository, like any other Git repo.

The wiki has markdown backend, so it should not be too much hard to work
with the sources.

-- 
Nicolas Sebrecht

**Comment by adolson** [comment]
Cloning the wiki locally is easy. But how do you send a pull request so
that Juan or Ariel could merge it back into the official wiki?

**Comment by nicolas33** [comment]
On Thu, Feb 19, 2015 at 01:07:36PM -0800, adolson wrote:
>    Cloning the wiki locally is easy. But how do you send a pull request so
>    that Juan or Ariel could merge it back into the official wiki?

`git request-pull`. It's not github but it should work fine.

-- 
Nicolas Sebrecht

**Comment by akien-mga** [comment]
Official wiki has been moved over to the OpenProject website: godotengine.org
It's currently not world-writable, but you can ask for write permissions in a dedicated forum thread.
