### ISSUE TITLE
Render and export PNGs from AnimationPlayer

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#12240]
I'd love to export an animation to a series of PNGs for creating animated gifs and videos. 

Alternatively, is there a way in gdscript to force a frame perfect function call that ignores speed so as to avoid frame skips? ie a non-realtime render.

This is what I'm using but it's unreliable.

```
extends Spatial

var images = []

func _ready():
    set_process(true)

func _process(delta):
    var image = get_viewport().get_texture().get_data()
    images.append(image)

func _on_AnimationPlayer_animation_finished( name ):
   var frame = 0
    for image in images:
        frame += 1
        image.save_png("res://images/output%04d.png"%frame)
~                                
```                                                                               
~

**Comment by Zylann** [comment]
You could slow down the animation (or FPS) to increase the reliability of saving each frame ;)

**Comment by dodgyville** [comment]
Thanks for the suggestion Zylann. I will give it a go.

**Comment by eon-s** [comment]
AnimationPlayer can run on fixed mode while you get pictures on idle (process), I don't know if that will be fast enough, though.

**Comment by fire** [comment]
Some other software also renders to a size bigger than the screen and then stitch the pieces together.

**Comment by Zylann** [comment]
If you want bigger than screen you can also render offscreen with a viewport I guess, no need to stitch

**Comment by fire** [comment]
Some other software also does panoramas, but that's a different goal. That in particular requires stitching and out of scope of this issue. Well, animated 3d gifs anyone :)

**Comment by vnen** [comment]
I fail to see the point of this request. What would you gain with such feature, in respect of game development?

**Comment by dodgyville** [comment]
Game development encompasses a lot of tasks.

Being able to have full size, frame perfect, uncompressed renders of a particular scene and animation sequence is important for commercial game makers and also experimental artists as the quality can not be faked.

For example, I would use it for HD trailers and animated gifs on social media. I know people who use game engines to make short interactive artworks for display in galleries who would use it to make high quality compilations of their work.

Hope that helps,
Luke

**Comment by vnen** [comment]
> Game development encompasses a lot of tasks.

**Comment by dodgyville** [comment]
I meant it's not just about the playable game itself. There's sharing development, promotion/marketing, archiving and experimentation. IMO having a render and export feature for AnimationPlayer would be an extremely useful tool for the engine.

**Comment by eon-s** [comment]
Can be useful for small video captures that now are common, but maybe need something else and not animation player dependant, an external process perhaps...

**Comment by dodgyville** [comment]
Would love to be able to run the animation manually step by step in gdscript. That would give me control over the snapshot of get_viewport().get_texture().get_data()

**Comment by NathanWarden** [comment]
I definitely see a need for this type of functionality, but it seems *much* more suited for a plugin.

**Comment by mhilbrunner** [comment]
Closing this for now, as it seems conensus is overwhelmingly that this should be in a plugin, not core functionality.
