### ISSUE TITLE
Bullet: RayCast nodes are ignoring 'collision types'

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12257]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
59ac299 

**Issue description:**
RayCast node is ignoring 'type mask' property in Bullet. Collision is always detected.
![raycast_typemask](https://user-images.githubusercontent.com/6129594/31818873-4337371a-b59a-11e7-8271-9320e07722d9.png)

**Steps to reproduce:**
1. Create raycast node
2. Uncheck everything in `type mask`
3. Create body with collision node
4. Put raycast in the way so it will intersect with the body collision
5. Observe that collision is detected 

**Link to minimal example project:**
[RayCastCollisionTypeTest.zip](https://github.com/godotengine/godot/files/1401748/RayCastCollisionTypeTest.zip)

**Comment by kubecz3k** [comment]
cc @AndreaCatania

**Comment by AndreaCatania** [comment]
I saw the differences between Godot and Bullet physics, and probably I'm missing something.

But stand to layer and mask of ray and body, The Bullet implementation seems correct to me.

We have ray in layer 1 and body that mask the layer 1. This mean a collision.

@reduz What do you think about?

![untitled2](https://user-images.githubusercontent.com/8342599/31824254-c88d0656-b5ae-11e7-88f8-79221bd19b52.png)

![untitled](https://user-images.githubusercontent.com/8342599/31824379-1b34dfb4-b5af-11e7-97ff-a85889914aec.png)

**Comment by kubecz3k** [comment]
@AndreaCatania but this issue is about Type Masks... This is Godot feature, raycast node can be configured to ignore all static bodies, or all areas. Take a look at screen from the first post.

**Comment by AndreaCatania** [comment]
This Node has a custom way to filter collisions and I think that is not a good thing in order of usage.

Probably this node should work with layer and mask as all other physics nodes does in Godot.

@reduz What do you think about unify the way how this node collision are filtered in order to match all the others?

**Comment by kubecz3k** [comment]
@reduz I'm sorry but #12464 is blocking my work a little, and Odino says he need to know what to do with `Mask Types` before fixing. Could you answer @AndreaCatania question? Thank you!
