### ISSUE TITLE
`godot_basis_get_elements` needlessly requires `this` pointer to be mutable

### ISSUE THREAD

**Issue by Evrey** [godotengine/godot#12250]
https://github.com/godotengine/godot/blob/3971bd41bb274c7f999801d74863746cd4546128/modules/gdnative/gdnative/basis.cpp#L174-L181

Noticed this when building my Rust binding, but totally forgot about it. The GDNative headers accept a mutable `godot_basis*` as `this` pointer for this function, whereas the documentation, the function's name, and its actual implementation tell that it should be `const godot_basis*` instead.

A small change, but a change that will make `borrowck` of Rust very happy. =)

Currently I am `mem::transmute`-ing my immutable `&Basis` reference into a mutable `*mut godot_basis` pointer, because I know that the underlying data won't be mutated. However, this is very, very bad Rust.

**Comment by Noshyaar** [comment]
cc @karroffel

**Comment by karroffel** [comment]
Oh yes, most likely an error made by spending too much time wrapping code all day, that was a horrible stage of development 😄 

You're right, it should be const. I'll change it once I'm home again, until then `unsafe` is your friend.
