### ISSUE TITLE
Custom script for import doesn't work

### ISSUE THREAD

**Issue by satyries** [godotengine/godot#12256]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Godot on *buntu 17.04

**Issue description:**
Whatever script.gd (even an empty one) you put in the "[Custom Script](https://i.imgur.com/NkEJmez.jpg)" gives generic error ( *Error running post-import script* ) without telling anything about what's wrong. The[ official Wiki says](http://docs.godotengine.org/en/latest/learning/workflow/assets/importing_scenes.html#custom-script) you're supposed to use this code to make it work

`tool # needed so it runs in editor`
`extends EditorScenePostImport`

`func post_import(scene):`

`  return scene # remember to return the imported scene`

This code works with Godot2, but both class EditorScenePostImport and function post_import are not present in Godot3

**Steps to reproduce:**
- While in Godot Editor select the item you want to import.
- Select **Import** on the left box then put a script in **[Custom Script](https://i.imgur.com/NkEJmez.jpg)**
- Click Re-import
= generic error appear, item cannot be imported anymore until you don't remove that script file

**Link to minimal example project:**

[minidemo.zip](https://github.com/godotengine/godot/files/1401729/minidemo.zip)
demo: while in editor try to reimport the box.dae

**Comment by volzhs** [comment]
`post_import` is actually here.
https://github.com/godotengine/godot/blob/0899b5029cba7aebedce809f8e401878978c95c1/editor/import/resource_importer_scene.cpp#L55-L61

but not binded
https://github.com/godotengine/godot/blob/9f7887837a04f52ebd04249342dc6b668a6b99be/editor/editor_node.cpp#L3268-L3270

@reduz @akien-mga is it really obsolete?

**Comment by volzhs** [comment]
I just uncommented `//ClassDB::register_class<EditorScenePostImport>();`
This code works really well.
```gdscript
tool # needed so it runs in editor
extends EditorScenePostImport

func post_import(scene):
    # do your stuff here
    for child in scene.get_children():
        if child is MeshInstance:
            child.set_surface_material(0, preload("res://materials/my.material"))
    return scene # remember to return the imported scene
```

**Comment by satyries** [comment]
I can confirm what @volzhs said, by uncommenting that line and compiling I was able to use the post_import again.

I guess this feature is not supported atm if there's looking for new API so I won't report if any bug/issue is found while using... but still it's something nice to have: saves lot of manual work which even onto unstable testing can come handy.
