### ISSUE TITLE
Bullet PR: Axis lock dont lock the rotation

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12259]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
This is a bullet related issue: 59ac299
debug_release build

**Issue description:**
In Godot axis lock should also lock rotation of a body, in bullet only position is locked. 

Godot:
![axis_lock_godot](https://user-images.githubusercontent.com/6129594/31824019-2545b088-b5ae-11e7-9d2e-c0382f5acb7a.gif)

Bullet:
![axis_lock_bullet](https://user-images.githubusercontent.com/6129594/31824028-2862168a-b5ae-11e7-97c3-2e33f74b4bc3.gif)

**Steps to reproduce:**
1. Download sample project and run BodyAxisLockTest.tscn

**Link to minimal example project:**
[BulletBodyAxisLockTest.zip](https://github.com/godotengine/godot/files/1402143/BulletBodyAxisLockTest.zip)

**Comment by kubecz3k** [comment]
cc @AndreaCatania

**Comment by kubecz3k** [comment]
I think this could be solved  by improving the workflow by introducing separate 'rotation axis lock' next to `translation axis lock`.

**Comment by slapin** [comment]
Actually having separate rotation lock is important, i.e. when implementing
character controller and many other uses.
Bullet uses separate locks.

**Comment by AndreaCatania** [comment]
Fixed with new commit: 4b192ea

**Comment by kubecz3k** [comment]
Will test asap

**Comment by kubecz3k** [comment]
I can confirm it's fixed now, the behavior is the same as in Godot.
