### ISSUE TITLE
PathFollow abnormal rotation 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12258]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04, 0e8db63009fdbc586829565d86f0974b95b1cd9e

**Issue description:**
Rotations are very strong for path follow in 3.0, `PathFollow` will very often make multiple 360 degree rotations in points where it should do slight 20 degree rotation.

Godot 2.1.3 (how it should look):
![godot2_path_follow](https://user-images.githubusercontent.com/6129594/31822190-33f7cdd8-b5a8-11e7-916e-06ecb9dfbc4a.gif)

Godot 3.0 (how it looks now):
![godot3_path_follow](https://user-images.githubusercontent.com/6129594/31822199-3a845716-b5a8-11e7-9526-1f4649474061.gif)

This issue is a regression in relation to 2.x (tested in 2.1.3). 
Not sure but it reminds me a little like how it could look if rotation is applied in degrees to the method that uses radians. 

**Steps to reproduce:**
1. Add Path node to the scene.
2. Add PathFollow node as a PathNode child
3. Create some path with curves in Path node
4. Add mesh instance to PathFollow, to visualise it
5. Animate PathFollow 'Unit offset' property to see how it behaves.

**Link to minimal example project:**
[PathFollowRotation.zip](https://github.com/godotengine/godot/files/1402000/PathFollowRotation.zip) (run PathFollowRotation.tscn)

**Comment by tagcup** [comment]
Thanks for the test case, I'll check it during the weekend.
There were a couple of things I noticed as well and it has been on my todo list for a while.

For now you can try replacing angle > CMP_EPSILON with Math::abs(angle) > CMP_EPSILON in path.cpp and try lowering lookahead value.

**Comment by kubecz3k** [comment]
@tagcup thank you!

**Comment by tagcup** [comment]
Loop behavior also needs to be fixed, and also fposmod silently reverses the direction of time which should flip the sign of angular velocity when traversing the path backwards.
