### ISSUE TITLE
Bullet PR: bodies instanced in runtime are putted at 0,0,0 position for one game tick

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12267]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Bullet PR 4b192ea4f9b5334525d55679cd3e48f9c422b15e Ubuntu 17.04
relase_debug build

**Issue description:**
This is a recent regression, when instancing a body it will be placed for very short time (one game tick?) at world 0,0,0 position. Not sure why but some bodies are staying on this position when they were putted in the scene via editor (was unable to reproduce this part of the issue).
video (best to watch at 0.25 speed): https://www.youtube.com/watch?v=JBz0XORLYf4&feature=youtu.be

This issue is a recent regression, I'm sure it was introduced in last couple of days. Will test which commit introduced it very soon. 

**Steps to reproduce:**
1. Download sample project and run BodyInstanceIssue.tscn

**Link to minimal example project:**
[BodyInstanceIssue.zip](https://github.com/godotengine/godot/files/1402916/BodyInstanceIssue.zip)

**Comment by kubecz3k** [comment]
I completed a bisection and it tells me that 8fd726dad0cf9588a6316efa3bbee6e68006f508 is the first bad commit (Renamed FI callback)
cc @AndreaCatania

**Comment by AndreaCatania** [comment]
@kubecz3k Fixed 2152ca7

**Comment by kubecz3k** [comment]
@AndreaCatania thank you! This is working beautifully now. 
There is one more issue related to that commit (I think), will create new issue when I will manage to create reproduction project :)

**Comment by AndreaCatania** [comment]
ok good
