### ISSUE TITLE
Sprite offset/center is using integer values

### ISSUE THREAD

**Issue by scupizzaboy** [godotengine/godot#1226]
![centering](https://cloud.githubusercontent.com/assets/898005/5754672/948eb4bc-9c61-11e4-9240-f49f06301fc0.png)
I have a Sprite that is 3 pixels wide. When "centered" is on, or when trying to center it using "offset", it is converting the values to integer, causing the Sprite to not actually be centered. A work-around to correctly center the Sprite is to make it a child of a Node2D and change the Sprite's position relative to the Node2D.

(Snapping is on in the image to show pixels, the behavior does not change with snapping on or off.)

**Comment by akien-mga** [comment]
I muss be missing something, but how would you center a 3px wide sprite? You can have a finer resolution than 1px, so you can't center it at 1.5px. Or did I misunderstand?

**Comment by akien-mga** [comment]
As per the above, I believe there is no bug here but just a misunderstanding about what pixels are. You can't cut a pixel in something smaller, or it would be quantum display :)

**Comment by reduz** [comment]
yes this now uses float values. Also there is an option to snap everything
to pixels that makes it snap to integer in the project settings

**Comment by Banderi** [comment]
This still uses integers as far as I can see in the editor. Am I missing something?
