### ISSUE TITLE
I can't move tiles in tilemap

### ISSUE THREAD

**Issue by MatiasVME** [godotengine/godot#12265]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux, KDE Neon, Godot Master commit 0e9f81a40bfb64aef242cc801aabb97a620b178e (last for the moment)

**Issue description:**
sorry for my english. but i did pull of master and i have that problem:
![image](https://user-images.githubusercontent.com/342117/31835633-ba559734-b5a8-11e7-8692-8f72c145d965.gif)

**Steps to reproduce:**

1. You can see the bug in this project -->
[TestBug.zip](https://github.com/godotengine/godot/files/1402890/TestBug.zip)
2. Import the project in godot and see the Test scene.

**Comment by mrcdk** [comment]
cc @groud

**Comment by akien-mga** [comment]
I need this fixed asap for alpha2.
