### ISSUE TITLE
clear_shapes then add_shape not functioning as expected

### ISSUE THREAD

**Issue by nanodeath** [godotengine/godot#12272]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Win10, Godot 2.1.4 stable.

**Issue description:**

I have an object that I want to be one of two possible states, each with its own collision shape. Basically either the player is standing and has a standing shape, or is crawling and has a crawling shape. I'm trying to model this as a KinematicBody2D that has two CollisionShape2D children, and then on startup calling `clear_shapes` and then re-adding just the shape I want, and again on crawl/stand clearing and readding shapes.

Clearing the shapes works fine, however the subsequent adding of shapes does not.

**Steps to reproduce:**

Clear, then add shapes. The example project is really simple...probably easier to check that out.

There's just one script -- shape_changer.gd:

```gdscript
extends RigidBody2D

export(String, "Add Shape", "Set Shape") var shapeMode

func _ready():
	var shape = get_node("CollisionShape2D").get_shape()
	# expected behavior: these two branches should function the same
	if (shapeMode == "Add Shape"):
		clear_shapes()
		add_shape(shape)
	elif (shapeMode == "Set Shape"):
		# can't call clear_shapes here because then there will be
		# no 0 index to update
		set_shape(0, shape)
	else:
		printerr("??? shapeMode was " + str(shapeMode))
```

**Link to minimal example project:**

[clear_add_shape_bug.zip](https://github.com/godotengine/godot/files/1403751/clear_add_shape_bug.zip)

**Comment by RandomShaper** [comment]
The problem is that in the _Add Shape_ case, you are not setting the transform of the shape. Try with
`add_shape(shape, get_node("CollisionShape2D").get_transform())`

In the _Set Shape_ case, it works because the shape transform at index 0 is already set.

**Comment by nanodeath** [comment]
Indeed, that was exactly the problem. Thanks @RandomShaper.

**Comment by RandomShaper** [comment]
You're welcome!
