### ISSUE TITLE
Editor crash when replace Path2D by PathFollow2D

### ISSUE THREAD

**Issue by quabug** [godotengine/godot#1228]
step:
1. open or create a scene in editor.
2. add a path2d node into scene.
3. replace path2d node by pathfollow2d node.

**Comment by akien-mga** [comment]
Can you still reproduce this in the current master branch?

**Comment by vnen** [comment]
This doesn't happen to me. I can replace the mentioned nodes just fine. Can be reopened if the OP still have the issue.
