### ISSUE TITLE
Build error: "undefined reference to function" while linking with mono enabled

### ISSUE THREAD

**Issue by GiantBlargg** [godotengine/godot#12298]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OS: Arch Linux
Godot 5030604
gcc 7.2.0
mono 5.4.0.201

When attempting to build with `scons -j4 platform=x11 module_mono_enabled=yes` I recieve the following errors during the final linking:
```
Linking Program ==> bin/godot.x11.tools.64
modules/libmodules.x11.tools.64.a(gd_mono.x11.tools.64.o): In function `GDMono::_register_internal_calls()':
/home/daniel/Projects/c/godot/modules/mono/mono_gd/gd_mono.cpp:232: undefined reference to `GodotSharpBindings::register_generated_icalls()'
modules/libmodules.x11.tools.64.a(gd_mono.x11.tools.64.o): In function `GDMono::_initialize_and_check_api_hashes()':
/home/daniel/Projects/c/godot/modules/mono/mono_gd/gd_mono.cpp:246: undefined reference to `GodotSharpBindings::get_core_api_hash()'
/home/daniel/Projects/c/godot/modules/mono/mono_gd/gd_mono.cpp:255: undefined reference to `GodotSharpBindings::get_editor_api_hash()'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.
```
With `scons -j4 platform=x11` I am able to build with no problems

**Comment by neikeq** [comment]
You must first build with `mono_glue=no`, generate the glue, and then build again normally, as described here: http://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html

This is a bit cumbersome, yes. The plan is to add a dummy glue, so that you don't have to do this when building binaries for testing purposes.

**Comment by GiantBlargg** [comment]
Well that worked, I need to remember to read the whole page before attempting to build. Will I have to rebuild the glue for each new version? Will the glue generated on Linux work when cross compiling with mingw?

**Comment by neikeq** [comment]
@GiantBlargg You will have to rebuild the glue every time the API exposed to scripts changes. That's why I want to add the dummy glue fallback so it's not annoying for non-production binaries. The glue generated is portable.
