### ISSUE TITLE
Graphic artifacts 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12309]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
GTX 1060, ubuntu 17.04

**Issue description:**
In recent Godot build, there are some dark squares on bright objects in my game.
Additionally there is also black border around one of the objects:
![artifact](https://user-images.githubusercontent.com/6129594/31862387-6faf5efe-b73d-11e7-9ad6-503d4635a062.png)

I performed the bisection and I needed to skip couple of times because the only thing that was rendered on my screen was white color. Result of the bisection:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of: 
 ```
a2a4f9a62a2ca0de3d8c44137177b4ef4b0f3e7b
932455599861d5a80272e99ad012a8867ac5ba16
f002e4cb82844083edb8a825160582d00f42bb21
68902453214c580e8c3ec9e4247c3a3cad73079e

Sorry for not providing more details, will work on it as soon as I will have some time!

**Steps to reproduce:**
Open our materials demo

**Link to minimal example project:**
https://github.com/godotengine/godot-demo-projects/tree/master/3d/material_testers

**Comment by akien-mga** [comment]
CC @tagcup

**Comment by kubecz3k** [comment]
I think I will be able to provide sample project, but I want to report couple also other issues today (its unlikely I will have today time to look at it in more detail today, but will do this tomorrow)

**Comment by kubecz3k** [comment]
I checked materials demo and it's visible on two models from there:
![artifacts_material](https://user-images.githubusercontent.com/6129594/31862346-ae07dd3a-b73c-11e7-815b-f3fd5e4ca172.png)

**Comment by tagcup** [comment]
Sure, will check in a couple of hours.
Do you happen to remember which material was that on the right?

**Comment by kubecz3k** [comment]
well the black maetrial is ice. Not sure if this helps but reduz said on irc "that issue is generally a nan or division by zero operation in a shader"

**Comment by tagcup** [comment]
I didn't notice anything like that in my test scene. I'm thinking it must be somehow related to alpha...

**Comment by kubecz3k** [comment]
You tested on material demo? I probably have a little outdated demo, should I upload?

**Comment by akien-mga** [comment]
I can reproduce it on the current material testers demo: 
![image](https://user-images.githubusercontent.com/4701338/31863836-969fc254-b753-11e7-9a8a-ff3e5f484f6a.png)

It flickers between the ice material and this black surface.

**Comment by reduz** [comment]
I am not sure if the ice is the same problem. The original problem happens
when a shader does division by zero or results in an inf/nan value. The
blur spreads it around so you see the blocky blackness. In the ice, it may
be something else but I would try bisecting..

**Comment by eon-s** [comment]
Worked fine a week ago (just too bright), now the black on the ice appears and dissapears/changes with zooming and camera angle, do not seem the same as the other which is constant black.

Using nvidia proprietary drivers.

**Comment by kubecz3k** [comment]
Yes, it was still working yesterday with in a4e7985dabb1456f33a2a9f6ae4e9667dc0bc475

**Comment by tagcup** [comment]
Ah, no I mean I have a test scene of my own which was clearly too simplistic.

I narrowed down the problem to GGX functions: special care is needed for grazing angles and at roughness = 0. I'm looking into it.

**Comment by tagcup** [comment]
@reduz When roughness is equal to 0, some specular functions (not just GGX) are ill defined (like we can have pow(0,0) in phong and blinn).

So I have two questions:

1. I overlooked the fact that you're doing this the other way around: the specular and diffuse contributions are weighted by metalness and 1-metalness, rather than 1-roughness and roughness. Don't you think we should use roughness?
2. At roughness = 0, what do you expect the specular to be?

**Comment by kubecz3k** [comment]
Works nicely after the fix :) Thank you
