### ISSUE TITLE
Audio pops in 2.1.2 onward

### ISSUE THREAD

**Issue by aozasori** [godotengine/godot#12307]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64-bit, Godot 2.1.2 onward

**Issue description:**
Starting with Godot 2.1.2, certain sounds repeatedly played in rapid succession will pop/crackle periodically. The issue persists into 2.1.4 and similarly in 3.0. The last version without crackling was 2.1.1.
(This problem affects the typing noises in my dialog box.)

**Steps to reproduce:**
Play a sine wave sound from a SamplePlayer many consecutive times in a loop.

**Link to minimal example project:**
2.1.x example project: 
[SoundCracklingExampleProject_2.1.x.zip](https://github.com/godotengine/godot/files/1404772/SoundCracklingExampleProject_2.1.x.zip)

3.0 example project:
[SoundCrackleExampleProject_3.0.zip](https://github.com/godotengine/godot/files/1404773/SoundCrackleExampleProject_3.0.zip)

Recordings showing the difference between versions: 
[SoundExamples.zip](https://github.com/godotengine/godot/files/1404774/SoundExamples.zip)

**Comment by akien-mga** [comment]
Try to change the value of Audio > Output Latency in the project settings to see if things improve.

cc @marcelofg55 for further debugging :)

**Comment by aozasori** [comment]
Increasing latency from 10 to around 25 or 30 seems to stop the popping in 2.1.4. In 3.0 i can't seem to find the setting for latency. Audio category in project settings doesn't seem to have it. (just Driver, Channel Disable Threshold Db, Channel Disable Time)

**Comment by marcelofg55** [comment]
I was just checking this, I don't think its a latency issue actually. I tried adding some silence to the whistle.wav and the popping stopped, without the silence I could listen to a very small crack when I played the wav one time on the editor too.
Can you test it with this wave file too? [whistle.wav.zip](https://github.com/godotengine/godot/files/1404996/whistle.wav.zip)

**Comment by aozasori** [comment]
It still pops even with the silence for me.

**Comment by marcelofg55** [comment]
What PC specs do you have? Can you test with latest 2.1 from github?

**Comment by aozasori** [comment]
Sorry for disappearing - something came up.
I'll test when i have the time. For now:

OS: Microsoft Windows 10 Home
Version: 10.0.16299 Build 16299
System Manufacturer: LENOVO
System Model 90B00004US
System Type x64-based PC
Processor: AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G, 3100 Mhz, 2 Cores, 4 Logical Processors
RAM: 8 GB
GPU: AMD Radeon R9 255
Sound Device: Realtek High Definition Audio

**Comment by reduz** [comment]
This is fixed in 3.0 (if you want, open an other issue for 2.1).

That mentioned, this is probably not the best way to do this effect, I would just do a single looping sample that you turn on an off.
