### ISSUE TITLE
InputEventMouseButton.factor only working on macOS

### ISSUE THREAD

**Issue by dploeger** [godotengine/godot#12313]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows, Linux

**Issue description:**
Over at the Discord documentation group we found, that InputEventMouseButton.factor only seems to be working for macOS, although it seems to be implemented for [Windows as well](https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L516). However, on macOS we get a real typed value, while on other platforms the value always is the default value 1.

The property is about the speed that the scroll wheel was turned at.

This [MSDN document](https://msdn.microsoft.com/de-de/library/windows/desktop/ms645617(v=vs.85).aspx) said that the current implementation is wrong or not optimal at least. However, over at engine_dev a developer tried to use `GET_WHEEL_DELTA_WPARAM(wParam)` instead of `HIWORD(wParam)`, but that didn't solve the error.

**Steps to reproduce:**
Create a scene and attach a script with this content:

```swift
func _input(event):
    if event is InputEventMouseButton:
        print(event.factor)
```

Start the scene and use the scroll wheel on the mouse (or another way of scrolling, i.e. with a trackpad)

**Expected result:**

When scrolling, the output shows real values according to the speed of the scroll. This should be working on macOS, Windows and Linux.

**Actual result:**

This only works on macOS.

**Link to minimal example project:**
[Test.zip](https://github.com/godotengine/godot/files/1405168/Test.zip)

**Comment by mhilbrunner** [comment]
Still always returns `1` as of current master near 3.0.3 release.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
