### ISSUE TITLE
Icons drawn at non-integer positions look buggy

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12317]
Godot 3.0 Windows 10 64 bits nVidia 940M

Already shown here: https://github.com/godotengine/godot/pull/12128

When the editor window is maximized, icons drawn in the viewport have artifacts:

![image](https://user-images.githubusercontent.com/1311555/31864872-7db52204-b765-11e7-9137-19c20daf8730.png)

But when the editor is windowed, icons are fine, even if the window is nearly as big as its maximized state:

![image](https://user-images.githubusercontent.com/1311555/31864882-a54025a8-b765-11e7-9bad-ae6150f844e2.png)

Edit: drawing them at integer positions seems to fix it. ~~Not sure why it affects only maximized state though.~~ It's definitely due to drawing at non-integer positions.

**Comment by groud** [comment]
Oh ! This reminds me #11417.
So rendering with floating point position might be the reason why it does not work correctly. :)

**Comment by reduz** [comment]
closed by #12828
