### ISSUE TITLE
Gridmap grid floor is flickering

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12321]
Godot 3.0 Windows 10 64 bits nVidia 940M

The floor grid of Gridmap is z-fighting and flickering with the normal grid. Any way to make it drawn over it but not above everything?

![image](https://user-images.githubusercontent.com/1311555/31865482-dfa32312-b76f-11e7-8ebc-f8dcb8da2e65.png)

**Comment by djrm** [comment]
one quick and dirty solution would be to add a small offset to the gridmap points.

**Comment by qarmin** [comment]
Still happens with 3.1 72db300
![qwgasg](https://user-images.githubusercontent.com/41945903/47497978-22f6f180-d85c-11e8-9714-ca87332b1350.png)

**Comment by KoBeWi** [comment]
The flickering still happens in 3.2.2 beta4, but it's fixed in 84abf5a97

**Comment by Calinou** [comment]
This could be worked around in the `3.2` branch by slightly offsetting the GridMap grid so it's always 0.01 units above or something.
