### ISSUE TITLE
A way to request Android permissions from the user

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#12323]
Currently Godot allows specifying permissions the game may require on Android, but it provides no way to request these permissions from the user. Enabling permissions requires the user to go into their Android settings and enable permissions for the app.

Typically if an Android app that requires a disabled permission is run, it will request the permission and Android will show a dialog to the user allowing them to approve or deny the request. Godot apps do not do this, and Godot does not provide a way for games to request the permission (short of calling into some module).

Godot should do one or both of:
  - Automatically request all permissions that were listed by the developer in the project settings
  - Expose an API in GDScript for checking the enable status of permissions and requesting permissions.

**Comment by raymoo** [comment]
If that label is directed at me, I unfortunately don't have Android dev experience outside exporting from Godot, only experience as a user. It might take some time for me to learn what is necessary, as opposed to someone who already has experience. I'm sorry if my description of the problem gave the impression that I would know how to implement this. It may even already be possible through a shell command or something, but I wouldn't know.

A concrete effect this has had is that I can't have my users select a file from their SD card or internal storage without first entering their Android settings.

**Comment by raymoo** [comment]
By the way, permissions being requested at runtime is a new feature of Android 6.0+, so this issue will not affect older versions, I think.

**Comment by raymoo** [comment]
I remember there being some way to set the Android API version when exporting the game, and was thinking to try messing with the setting to see if I can get permissions working that way. Did this option actually exist? I can't find it anywhere now.

**Comment by raymoo** [comment]
Seems like  #26756 solves this.

**Comment by raymoo** [comment]
Actually nevermind, that method is hardcoded to only work with the audio permission.

**Comment by cagdasc** [comment]
@raymoo maybe you can checkout my pr #31583

**Comment by Calinou** [comment]
This feature has apparently been vetoed in https://github.com/godotengine/godot/pull/32246#issuecomment-538422392, so I'll close this.
