### ISSUE TITLE
Editor: FileSystem drawer UI improvements

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#12322]
This issue is to collect (and discuss) suggestions for improvements of the FileSystem drawer UI, making it (hopefully) even more useful and intuitive.

![filesystem_drawer](https://user-images.githubusercontent.com/1654763/31865366-514ce928-b76e-11e7-834b-4f79c719cf33.PNG)

Suggested improvements:
- Dragging a folder onto itself in the directory tree view at the top yields a big `Cannot move a folder into itself` error dialog ([Screenshot](https://i.imgur.com/xCppekp.png)). Suggestion: Remove this error and do nothing or just log it.
- The context menu for both the top and the bottom part is only available when right clicking existing items. So you have to right click an existing folder or file to create a new folder. Suggestion: Add a default context menu when right clicking the background that allows creating folders and `Show In File manager`.
- The `Create New Resource` dialog is currently only available via the inspector, not via the FileSystem drawer. Suggestion: Add `New resource..` option to the context menu(s), next to `New folder`.
- In addition to the above, add a new icon next to the list icon and search bar which allows to create new folders and resources.

What do you think? Other suggestions?

**Comment by MillionOstrich** [comment]
Regarding dragging onto itself this should probably be tested for in the drag & drop logic and not accept the drag if it would move a folder into itself.

**Comment by mhilbrunner** [comment]
Thanks @MillionOstrich for working on this :)

**Comment by mhilbrunner** [comment]
Seeing everything but the resource thing got implemented, I'll close this and open a separate issue for that later. Thanks for working on this, MillionOstrich!
