### ISSUE TITLE
Repeated countless times: ERROR: add_signal: Type Sprite3D already has signal: frame_changed

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#1234]
This error is repeated every frame. Is that normal? Or how can it be prevented?
I have not used the "frame_changed" signal anywhere, this must be something internal.

ERROR: add_signal: Type Sprite3D already has signal: frame_changed
   At: core/object_type_db.cpp:494.

**Comment by reduz** [comment]
i think this is fixed in github

**Comment by reduz** [comment]
I think i fixed this issue a while ago on github, I also fixed yield() issues recently, maybe they are related?

**Comment by akien-mga** [comment]
Assuming this has been fixed already as per above comments.
