### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by MrMaidx** [godotengine/godot#12356]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
![yeswecan](https://user-images.githubusercontent.com/4701338/31902170-2f66da2e-b824-11e7-800a-3d81701b85b2.gif)

**Comment by MrMaidx** [comment]
Sorry for this. :D It seems I accidentally hit enter on my new keyboard and didn't notice it posted. :D
Here is the issue I wanted to post: https://github.com/godotengine/godot/issues/12357
