### ISSUE TITLE
Editor UI: Popup for entering values (e.g. transform/position) needs text margins

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#12352]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 x64, Godot 3.0 master@804cab3, NVIDIA GTX 980 Ti

**Issue description:**
The popup for entering values into properties (for example for transform/position/scale) has too small a margin between the labels and inputs. The labels are squished into the input fields. See attached screenshots.

**Steps to reproduce:**
Create project, add Node2D, select it and enter values in the inspector.

**Link to minimal example project:**
![godotoffset](https://user-images.githubusercontent.com/1654763/31893684-70660206-b80c-11e7-9689-ecf3a2e9237e.PNG)

**Comment by akien-mga** [comment]
BTW in that screenshot, the edit box with `(0, 0)` also needs some left margin to look better.

**Comment by zedutchgandalf** [comment]
I'd like to tackle this if no-one else is already looking at it :)

**Comment by AntiSC2** [comment]
Have an upcoming PR already @zedutchgandalf

**Comment by zedutchgandalf** [comment]
@AntiSC2 Wait, why didn't you post anything here first? I also just pushed a PR :(
Did you also fix the margin in the edit box? I've been looking for that for quite a while but I couldn't find the code that draws those

**Comment by AntiSC2** [comment]
@zedutchgandalf Sorry should have posted here first, it seems that @groud also has a pr for this issue so this was a great example of bad communications. My PR is now only about edit box. The code for the edit box is in scene/gui/tree.cpp where the drawing for everything is happening.

**Comment by groud** [comment]
Yeah, I worked on that this afternoon, should have pushed earlier... ^^ Sorry.
