### ISSUE TITLE
Center of mass for RigidBody2D

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#12353]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0, 3.1, 3.2, 4.0, ~~4.1~~

**Issue description:**
The center of mass is always at the Node's origin apparently. If the shapes are offset by either transformation matrix or simply shifted by coordinates away from origin, the new center of mass formed by shapes is not taken into account. So the only way to fix this is by moving shapes to the RigidBody2D's origin and repositioning of RigidBody2D whenever shapes are changed (which is not recommended AFAIK in terms of collision checking). Here's an example:

![broken-center](https://user-images.githubusercontent.com/17108460/31893414-237e6566-b814-11e7-9f4d-44183726b33f.gif)

EDIT: these three shapes are actually individual ConvexPolygon2D shapes

Now, inspired by PR #7426 by @m4nu3lf (3D case), I've made some progress computing center of mass successfully based on shapes transformations, but my knowledge of physics is basic, here's a better result that I've made (compare middle box):

![somewhat-broken-center](https://user-images.githubusercontent.com/17108460/31893542-7a661338-b814-11e7-93f2-a7e5f24169f4.gif)

This feature/bug was proposed/described here several times, but for some reason or another it was mistakenly ignored or issues were closed as fixed, see #7136 and #8638.

**Steps to reproduce:**
1. Create RigidBody2D.
2. Attach any collision shape to it.
3. Set transform for collision shape so it's visually away from the RigidBody2D's origin.
4. See how it behaves.

**Link to minimal example project:**
[center-of-mass-2d.zip](https://github.com/godotengine/godot/files/1407211/center-of-mass-2d.zip)

**Comment by raymoo** [comment]
Center of mass cannot be determined from just the shapes because the density of an object may vary. For example, the center of mass of a front-engine car is typically not in the middle of the car but closer to the front.

If we assume that density is positive though (like in models of real life), the center of mass should be somewhere (and could be anywhere) inside the convex hull of the shapes.

**Comment by raymoo** [comment]
I forgot to mention that my point is that sometimes you would want the center of mass to not just assume  constant density. If this feature is added at all, it should be optional.

**Comment by Xrayez** [comment]
@raymoo Yeah, and having the ability to set center of mass manually would be a partial solution to simulate variable density I suppose.

**Comment by razvanc-r** [comment]
The better option is to assume uniform density + have an input option for a texture density. I may look at this center of mass issue later, at least calculating the center of mass

**Comment by akien-mga** [comment]
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by Xrayez** [comment]
Is this issue going to be moved to 3.2 again? I need this issue to be fixed eventually so I might start digging through code and physics more thoroughly...

Does it only depend on the center of mass or something else as well? I imagine the different center of mass affects angular velocity/inertia for each point of the rigid body that needs some fancy matrix calculation... 

I'll appreciate any help/pointers regarding where I should start looking at this.

**Comment by akien-mga** [comment]
> Is this issue going to be moved to 3.2 again?

Sadly yes, we're running out of time for such issues. I'd suggest you try to discuss it with @reduz on IRC to have pointers on where to look into.

**Comment by Zylann** [comment]
Adding my voice to this, I would like to be able to set the center of mass manually, at least from a script. The use case for that is a game where you can build an object using blocks of variable mass, and that affects where you want the center of mass would be.

**Comment by Xrayez** [comment]
@Zylann yeah, having an ability to manually set center of mass is another feature, the current problem is actually trying to resolve proper impulse response between rigid bodies with different distribution of mass as it seems, whatever the center of mass.

I mean, I think this could be solved by finding proper geometric center of mass (centroid) whenever shapes are changed first (I think I've managed to do this [here](https://github.com/Xrayez/godot/commit/207ea7d5be3c32df9055b341aeec8c278bc9543e#diff-6748046cf4580adf2ea8b3ea9a47d806L45) similarly to how 3D version does it), and only then apply additional offset relative to actual center of mass. That way you can always revert the center of mass to shapes' centroid offset anytime (if this is the right way to simulate distribution of mass at all)

**Comment by abakobo** [comment]
Yes, center of mass and origin could definitely be different so the center of mass can be modified/recomputed without changing the origin.
Beign alble to compute the center of mass/moment of inertia for the combination of one body's shapes (with different densities) is how things are usually done in physics simulation.

**Comment by Maveyyl** [comment]
3.2 has been out, any news about this? :) being able to just offset it manually would already do wonders.

**Comment by Xrayez** [comment]
@Maveyyl #29867 is there to fix it and I've tested it myself in my own project, but unfortunately it wasn't merged for 3.2. Expect this issue to be here for as long as 4.1 comes out I guess (because allegedly that's when @reduz plans to rework the 2D physics engine).

**Comment by Maveyyl** [comment]
@Xrayez Nice! I'll stick to my dirty hacks and wait patiently for 4.1. :)
