### ISSUE TITLE
--generate-mono-glue ERROR (Windows 7, VS 2017)

### ISSUE THREAD

**Issue by KGI-John** [godotengine/godot#12361]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7

>python --version
Python 2.7.8

>scons --version
SCons by Steven Knight et al.:
        script: v3.0.0.rel_3.0.0:4395:8972f6a2f699, 2017/09/18 12:59:24, by bdbaddog on ubuntu-16
        engine: v3.0.0.rel_3.0.0:4395:8972f6a2f699, 2017/09/18 12:59:24, by bdbaddog on ubuntu-16
        engine path: ['C:\\Python27\\Lib\\site-packages\\scons-3.0.0\\SCons']
Copyright (c) 2001 - 2017 The SCons Foundation

>mono --version
Mono JIT compiler version 5.4.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-proj
ect.com
        TLS:           normal
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**Issue description:**

http://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html

Following the above document, running "godot --generate-mono-glue modules/mono/glue" results in the below errors:

ERROR: No loader found for resource: res://modules/mono/glue
   At: core\io\resource_loader.cpp:184
ERROR: Failed loading scene: res://modules/mono/glue
   At: main\main.cpp:1546

**Steps to reproduce:**

Using the x64 Native Tools Command Prompt for VS 2017, run the following commands:

>scons -j6 platform=windows tools=yes module_mono_enabled=yes mono_glue=no
>.\bin\godot.windows.tools.64.exe --generate-mono-glue modules/mono/glue

**Link to minimal example project:**

**Comment by akien-mga** [comment]
```
ERROR: No loader found for resource: res://modules/mono/glue
At: core\io\resource_loader.cpp:184
ERROR: Failed loading scene: res://modules/mono/glue
At: main\main.cpp:1546
```
Those are false positives, it's just Godot trying to parse the path as if it were the path to a scene that should be run. Does the glue get generated as expected?

**Comment by KGI-John** [comment]
The glue cpp is generated. I thought it failed to build because when I attach the below script, I get an error saying "'GD' does not contain a definition for 'Print'"

using Godot;
using System;

public class MyNode : Node
{
    // Member variables here, example:
    // private int a = 2;
    // private string b = "textvar";

    public override void _Ready()
    {
        // Called every time the node is added to the scene.
        // Initialization here
        GD.Print("Hello C#");
    }
}

**Comment by akien-mga** [comment]
Did you build with `mono_glue=yes` after generating the glue?

**Comment by heikytr** [comment]
The **P** in the`GD.Print()` method should be using lowercase **p**

https://github.com/godotengine/godot/blob/b0194a33f65970948ef66819913bf3034a3a22e8/modules/mono/glue/cs_files/GD.cs#L62

**Comment by neikeq** [comment]
Ah, I forgot `print` was one of the few methods that are still not in PascalCase.

**Comment by akien-mga** [comment]
Would that be easy to fix before alpha2, or is it more involved than just changing the case in `GD.cs`?

**Comment by neikeq** [comment]
It's trivial to change, but I would prefer to rename all the remaining methods to PascalCase once I update all the manual bindings.

**Comment by spinda** [comment]
I'm in the same situation, except it doens't look like the .cpp file is getting generated (it's not showing up in `modules/mono/glue`).

**Comment by akien-mga** [comment]
The issue initially reported here is fixed. Could you open a new issue with details about the terminal log, how you built Godot and how you're generating the glue?
