### ISSUE TITLE
it's impossible to disconnect signals in inherited scene.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#12373]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1

**Issue description:**

If I have a base scene and connect a method to a signal, 
And in the inherited scene, I do not need this connect, I can disconnect the signal in the editor, but when open the scene again, the signal is still connected to that method.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by kubecz3k** [comment]
@alexzheng are you be able to check if this issue is present in 3.0 as well?

**Comment by alexzheng** [comment]
certainly it is the same in 3.0.
the connection is read from the base scene file, it needs to implemented a new solution to tag "remove" something in the base scene file.

Also it would be possible to remove nodes  in inherited scene.

**Comment by willnationsdev** [comment]
I can confirm also that this fails in 3.0. Reloading the scene will re-instate the visual display of the signal in the Node signals dock, but it also will continue to execute the defined signal, despite removal from the Node signals dock, if you remove it, save the scene, and then run the current scene without re-loading it. Ergo, it's not necessarily just a serialization issue, but rather likely an issue with the function callback of the "Disconnect" button for the Node signals dock just not taking into account base-scene signals when searching for the signal to remove.

**Comment by DualMatrix** [comment]
Still relevant in master.

**Comment by svendixon** [comment]
I've attached some GIF's to show whats happening. In my example, **Player** is the base scene, **Bob** inherits from **Player**, and **Game** has instances of **Bob**.

**GIF 1:** If you disconnect the signal from **Player** then reload **Game**, it's fine.
**GIF 2:** If you disconnect the signal from **Player** then run the project, before you reload **Game**, you're screwed.

![2019-01-09 06-58-22](https://user-images.githubusercontent.com/14341036/50899000-d349b000-13de-11e9-8594-117724bb9f6e.gif)
![2019-01-09 06-59-52](https://user-images.githubusercontent.com/14341036/50899010-da70be00-13de-11e9-9366-7183ddecaa98.gif)

**Comment by KoBeWi** [comment]
Still relevant in 58034f3

**Comment by Mickeon** [comment]
This is still an issue as of b9a64c77366361a0d45dcdd2b330911efd1eb3f4

**Comment by KoBeWi** [comment]
I'm thinking that this should just be blocked completely. Like you can't edit foreign resources, you also shouldn't be able to edit foreign connections.

Fixing this "properly" would require implementing serialization for "disconnections".
