### ISSUE TITLE
[macOS] Colemak keyboard not correctly used (switches to QWERTY)

### ISSUE THREAD

**Issue by N0hbdy** [godotengine/godot#12379]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS (10.12.6 (16G29))

Godot version: tip: 0268a95828bd0690aedadf0e2503f1e1f67bf81f

**Issue description:**

Colemak bindings don't work; meta keys revert to old QWERTY (US).

**Steps to reproduce:**

Make a change and attempt to save; Instead you'll duplicate something most likely (:D)

**Link to minimal example project:**

N/A

Logging the issue, will have a PR up shortly for Macs.  As a side note, I believe this affects Windows users as well, but I'm unable to figure out what hex code Colemak is since Google failed me (shocking) and I don't have a windows machine.

**Comment by akien-mga** [comment]
Fixed by #12380.
