### ISSUE TITLE
GridMap Editor: shift + A S D buttons should rotate tile in reverse direction

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#1237]
Hey, there. So, the flipped Gridmap rotation controls (Shift+A, Shift+S, and Shift+D) are broken; they just rotate the tile in the same direction as the normal Gridmap rotation controls instead of the opposite direction, like they should.

**Comment by kubecz3k** [comment]
@SolarLune are you sure it was implemented in the first place? I'm trying to classify this issue and I'm not sure if this is a bug or a feature request.

**Comment by SolarLune** [comment]
I haven't used Godot in awhile now, but if the rotation controls are mentioned in the editor and they don't work, then I'd classify that as a bug.

**Comment by kubecz3k** [comment]
Indeed I was able to found mention of 'cursor back rotate' in grid menu, so it's a bug after all.  Thanks!

**Comment by akien-mga** [comment]
Likely an easy one to fix, marking as junior job.
