### ISSUE TITLE
Scenes Bleeding Over Into Each Other

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#1238]
Hey, there. This doesn't seem to be a major bug, but it appears that scenes are bleeding over into each other at times.

![godotbleedingscenes](https://cloud.githubusercontent.com/assets/4733521/5783484/502c407e-9d78-11e4-94c4-4b469d3528f8.png)

In the attached screenshot, you can see that nowhere in my scene do I have a light or WorldEnvironment, and the default light is off, but the scene isn't dark. You can also see a tile from a GridMap that doesn't exist in the scene. These are both nodes missing from this scene, but present in the previous scene I opened in Godot.

While this may not be a big deal, I imagine it could cause crashing and problems (as I can fairly easily get Godot to crash just messing around with GridMaps; maybe this is part of the reason or something). Anyway, that's it.

P.S. That tile is most likely the cursor tile of the gridmap; it never disappears when you go from GridMap to another node.

**Comment by reduz** [comment]
maybe gridmap doesn't free part of the data, should check that

**Comment by akien-mga** [comment]
Would it be an editor-specific issue (i.e. data not cleared correctly when switching scenes in the editor), or would it also affect games when switching scenes?

**Comment by akien-mga** [comment]
Can you still reproduce this issue? If yes, please provide steps to reproduce and/or a test project that exhibits the issue.

**Comment by akien-mga** [comment]
Will be hard to fix without any steps to reproduce, so closing. Feel free to comment and give more details if you can still reproduce it, so that I reopen the issue.
