### ISSUE TITLE
Default editor font a bit smaller?

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#12381]
I was thinking about changing default Editor and Source text font from 14 to 12.
Change is small but visually Editor looks much slicker and modern.

Probably there is some room for discussion. Any objections? :)

**OLD**

![godot engine - playground - spatial tscn - _019](https://user-images.githubusercontent.com/6152134/31961011-d5519476-b8f9-11e7-8531-f8ca114837b6.png)

![selection_020](https://user-images.githubusercontent.com/6152134/31961101-09b70b24-b8fa-11e7-9b2d-b0667475a4da.png)

**NEW**

![godot engine - playground - spatial tscn - _018](https://user-images.githubusercontent.com/6152134/31961022-de3959fc-b8f9-11e7-8307-e44f22527bd6.png)

![selection_021](https://user-images.githubusercontent.com/6152134/31961109-0d153b10-b8fa-11e7-809c-5169094164ae.png)

**Comment by Zylann** [comment]
Turns out it's been a while I reduced font size to 12 too^^ (I also set it to 13 in 2.1.x, instead of 14).

**Comment by zedutchgandalf** [comment]
Is 12px still easy readable on 4K screens though? I think it's safer to have a slightly larger font size by default with the option to make it smaller (as it is now) than the other way around. I quickly checked a couple of websites and they generally seem to use 14px for the main text.

**Comment by Zylann** [comment]
@zedutchgandalf the proposal of 12px doesn't make sense if you think about upscaled modes that likely run in 4K. If it were ported to be ported here, that would just mean the font would be *proportionally* smaller.

**Comment by djrm** [comment]
I prefer the current font, small fonts tend to be less readable on standard (loDPI) displays, also is there any benefit besides the opinion that it looks more modern?

**Comment by Zylann** [comment]
@djrm as I said, simply space gain, "homogeneity" towards system font sizes, and better subjective feeling :D

On my system:
Before: 
![image](https://user-images.githubusercontent.com/1311555/31972651-ef1fe42a-b921-11e7-95af-7939a911dc78.png)
After:
![image](https://user-images.githubusercontent.com/1311555/31972656-f537dcfa-b921-11e7-8aaf-fbee265325d1.png)

**Comment by djrm** [comment]
@Zylann funny but on the linux side it seems to be consistent already, i also have 1080p display, which godot considers LoDPI.
![screenshot from 2017-10-24 18-22-18](https://user-images.githubusercontent.com/1103897/31972844-5500e490-b8e8-11e7-9956-2d38050b74d5.png)

**Comment by Zylann** [comment]
¯\_(ツ)_/¯
Beware that not all apps are comparable (an IRC client might not have the same sizings as an IDE, file explorer or painting program^^ example: Discord font size xD)
Do you imply Godot wrongly detected my system as being midDPI?

**Comment by djrm** [comment]
@Zylann that IRC client uses GTK so it has the system settings, also about your settings it might be, maybe thats the reason why the icons for you look worse, since they are rendered to non power of 2 on those settings and they get distorted.

**Comment by Zylann** [comment]
@djrm I changed from `Auto` to `LoDPI` but it didn't have any effect.

**Comment by eon-s** [comment]
I use it at 12 too, that makes the minimum size of panels too wide, though.

**Comment by n-pigeon** [comment]
As @Zylann said change will be more about proportions, not fixed size for all resolutions. :)
It is more about first impression look.

More voices? @groud @toger5 @akien-mga @reduz (someone more?)

**Comment by groud** [comment]
I've got no strong opinion on that, I like the current font size but I agree it's slightly bigger than other softwares.

**Comment by Hinsbart** [comment]
I like the smaller font size.

**Comment by groud** [comment]
@Zylann = cookie clicker player spotted.

**Comment by Calinou** [comment]
I propose setting the default font size to 13 (which is small, but still readable on a loDPI display), and keep the default script editor font size to 14 (12 is too small, and 13 doesn't make it save any vertical space compared to 14).

Some screenshots follow:

**Gray project manager, font size 13:**
![godot_pm_gray_font_13](https://user-images.githubusercontent.com/180032/32002500-fa411b28-b99c-11e7-8e78-5cd5b90fbba7.png)

**Gray editor settings, font size 13:**
![godot_settings_gray_font_13](https://user-images.githubusercontent.com/180032/32002502-fa60998a-b99c-11e7-93c8-f8d982c0c338.png)

**Default editor, font size 13:**
![godot_editor_default_font_13](https://user-images.githubusercontent.com/180032/32002503-fa8c8ae0-b99c-11e7-98d5-3fb6c4ddab47.png)

**Default editor, font size 14:**
![godot_editor_default_font_14](https://user-images.githubusercontent.com/180032/32002504-fab4e09e-b99c-11e7-97aa-97e081ef0f48.png)

**Light editor, font size 13:**
![godot_editor_light_font_13](https://user-images.githubusercontent.com/180032/32002505-fae29458-b99c-11e7-841a-30a962a854c8.png)

**Light editor, font size 14:**
![godot_editor_light_font_14](https://user-images.githubusercontent.com/180032/32002506-fb0398ec-b99c-11e7-822d-437aedd42e42.png)

**Comment by volzhs** [comment]
I vote for 13.

**Comment by djrm** [comment]
i notice a worse font resolution on font 13. even with HiDPI (or medium i dont know what that is) i could say it will be worse on loDPI, but i mean 1px difference in my opinion this is pointless

**Comment by toger5** [comment]
I also don't prefer one specific size. as long as it is readable. generally I prefer bigger fonts. 
So my vote is to keep it. (but just I'm fine with everything. as you can see I also don't have good points...)

**Comment by zedutchgandalf** [comment]
Ultimately this is all just user preference. So imo the question should be about which font size is the most accessible for the largest amount of users (so they can at least see enough to be able to change the font size to one more appropriate for their monitor). And I think with that in mind it is safer to choose a default font size that might look slightly too big on certain monitors than one that might look too small, ie. might be unreadable.
I don't know if this is possible, but you might also be able to set the default based on the user's dpi to try to offer everyone the most optimal experience...

**Comment by n-pigeon** [comment]
@zedutchgandalf yup, we already change GUI size based on auto-detected resolution. Fonts are automatically adjusted also.

**Comment by volzhs** [comment]
I've been using with font size 13 for 2.1.4 for a couple of days.
and now I prefer 14.

**Comment by mhilbrunner** [comment]
Closing this, as the discussed seems to have reached its end half a year ago without a clear consensus and because this seems mostly be subjective.
