### ISSUE TITLE
Tiles in gridmaps ignore material properties

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#1239]
Hey, there. It would appear that tiles placed by GridMap don't have the source objects' material properties. For example, all tiles in a GridMap tileset will always be double-sided, regardless of the material setting of the materials the tiles use.

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by SolarLune** [comment]
I'm not sure; it's been quite awhile since I last used Godot. It's safe to just close this - someone else can re-open it or open a new issue if they observe it.

Let me know if you want me to close it.

**Comment by blakeearth** [comment]
I think am having this issue in the current Steam release.
Steps to reproduce:
1. Import .OBJ file and create a material for it using the Inspector (I saved it as a .tres)
2. Create mesh library scene with Spatial-->MeshInstance of OBJ-->StaticBody-->CollisionShape
3. Convert to a MeshLibrary with or without "Merge With Existing" enabled.
4. Create a GridMap that uses the mesh. For me, the preview images and editor showed the material rather sporadically depending on seemingly nothing in particular.
5. Attempt to "play." The material is not visible.
[material-grid-map.zip](https://github.com/godotengine/godot/files/2019500/material-grid-map.zip)

I'm about to try using a .DAE (with existing materials) and get back to this.

**Comment by blakeearth** [comment]
Update: the same workflow (but with saving the mesh with material from a .DAE file from the inspector) works as expected; materials display properly.

**Comment by akien-mga** [comment]
It would be better to open a new issue, as this one was closed over 3 years ago and was experienced on a very different version of Godot, so if symptoms are similar, the cause might be quite different.
