### ISSUE TITLE
Material Override data not freed if set from script

### ISSUE THREAD

**Issue by hickop** [godotengine/godot#12401]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Godot 3.0@4396712

**Steps to reproduce:**
- Create quad mesh with SpatialMaterial in Material Override
- Set texture via script (tried albedo_texture and normal_texture)
- Runing outside of editor, when exiting it produces:
```
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1858.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:388.
```

This issue does not occur with surface Material.

EDIT: Seems to affect every data passed to material_override with script

**Link to minimal example project:**
[leak_tests.zip](https://github.com/godotengine/godot/files/1415010/leak_tests.zip)

**Comment by hpvb** [comment]
The noted PR seems to fix this issue
```
[hp@lola leak_tests]$ ~/Projects/workspace/godot/bin/godot.x11.opt.tools.64 --path .
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
[hp@lola leak_tests]$ ~/Projects/workspace/godot/bin/godot.x11.opt.tools.64 
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
[hp@lola leak_tests]$ ~/Projects/workspace/godot/bin/godot.x11.opt.tools.64 
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
```

No more warning! :)
