### ISSUE TITLE
3.0 Cannot compile by MinGW-W64

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#12417]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 commit 2987e6ce4ffc69da5efc0903cc00ce12e72d2125
Windows7 64
MinGW-W64 gcc 6.3.0 g++ 6.3.0

**Issue description:**
Cannot compiled
see log below:
[log.txt](https://github.com/godotengine/godot/files/1418525/log.txt)

**Steps to reproduce:**
run "scons platform=windows" at project directory.

**Comment by sersoong** [comment]
thirdparty\etc2comp\EtcImage.cpp: In member function 'Etc::Image::EncodingStatus Etc::Image::Encode(Etc::Image::Format, Etc::ErrorMetric, float, unsigned int, unsigned int)':

thirdparty\etc2comp\EtcImage.cpp:259:64: error: invalid use of incomplete type 'class std::future<void>'

   std::future<void> *handle = new std::future<void>[a_uiMaxJobs];

                                                                ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<void>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:268:12: error: invalid use of incomplete type 'class std::future<void>'

    handle[i] = async(std::launch::async, &Image::RunFirstPass, this, i, uiNumThreadsNeeded);

            ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<void>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:268:91: error: invalid use of incomplete type 'class std::future<void>'

    handle[i] = async(std::launch::async, &Image::RunFirstPass, this, i, uiNumThreadsNeeded);

                                                                                           ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<void>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:275:12: error: invalid use of incomplete type 'class std::future<void>'

    handle[i].get();

            ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<void>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:275:13: error: invalid use of incomplete type 'class std::future<void>'

    handle[i].get();

             ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<void>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:330:107: error: invalid use of incomplete type 'class std::future<unsigned int>'

      std::future<unsigned int> *handleToBlockEncoders = new std::future<unsigned int>[uiNumThreadsNeeded-1];

                                                                                                           ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<unsigned int>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:334:30: error: invalid use of incomplete type 'class std::future<unsigned int>'

       handleToBlockEncoders[i] = async(std::launch::async, &Image::IterateThroughWorstBlocks, this, blocksToIterateThisPass, i, uiNumThreadsNeeded);

                              ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<unsigned int>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:334:147: error: invalid use of incomplete type 'class std::future<unsigned int>'

       handleToBlockEncoders[i] = async(std::launch::async, &Image::IterateThroughWorstBlocks, this, blocksToIterateThisPass, i, uiNumThreadsNeeded);

                                                                                                                                                   ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<unsigned int>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:340:50: error: invalid use of incomplete type 'class std::future<unsigned int>'

       uiIteratedBlocks += handleToBlockEncoders[i].get();

                                                  ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<unsigned int>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:340:51: error: invalid use of incomplete type 'class std::future<unsigned int>'

       uiIteratedBlocks += handleToBlockEncoders[i].get();

                                                   ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<unsigned int>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:356:12: error: invalid use of incomplete type 'class std::future<void>'

    handle[i] = async(std::launch::async, &Image::SetEncodingBits, this, i, a_uiJobs);

            ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<void>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:356:84: error: invalid use of incomplete type 'class std::future<void>'

    handle[i] = async(std::launch::async, &Image::SetEncodingBits, this, i, a_uiJobs);

                                                                                    ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<void>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:362:12: error: invalid use of incomplete type 'class std::future<void>'

    handle[i].get();

            ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<void>'

     class future;

           ^~~~~~

thirdparty\etc2comp\EtcImage.cpp:362:13: error: invalid use of incomplete type 'class std::future<void>'

    handle[i].get();

             ^

In file included from thirdparty\etc2comp\EtcImage.cpp:40:0:

C:/Program Files/mingw-w64/x86_64-6.3.0-win32-seh-rt_v5-rev2/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/future:115:11: note: declaration of 'class std::future<void>'

     class future;

           ^~~~~~

**Comment by akien-mga** [comment]
Looks like #9258. There's a workaround in https://github.com/godotengine/godot/issues/9258#issuecomment-315612079 but it's for Ubuntu. You should check if there's a way to specifiy that you want to use the POSIX mode mingw instead of the win32 one.

**Comment by Calinou** [comment]
[MSYS2](http://www.msys2.org/) is a MinGW distribution that uses POSIX threads by default, and works well for compiling Godot.

**Comment by sersoong** [comment]
MSVC 2015 also compile failed

**Comment by fire** [comment]
choco install mingw -y -params "/exception:seh /threads:posix"  I would try doing that via chocolatey.

**Comment by sersoong** [comment]
I've solved this problem.
Just reinstall MinGW by posix threads model.
