### ISSUE TITLE
Godot expects EMSCRIPTEN_ROOT for web export compilation, not provided by emsdk_env.bat

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#12414]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64 bit, Godot 1063ddf, Emscripten 1.37.21

**Issue description:**
Emscripten's `emsdk_env.bat` doesn't provide `EMSCRIPTEN_ROOT` environment variable as of now, but it provides `EMSCRIPTEN` one which points to the same location. Yet it provides `EMSCRIPTEN_ROOT` entry inside `.emscripten` config file.
Would be nice to search for `EMSCRIPTEN` environment variable as well.

```
D:\build\emscripten>emsdk_env.bat
Adding directories to PATH:
PATH += D:\build\emscripten
PATH += D:\build\emscripten\clang\e1.37.21_64bit
PATH += D:\build\emscripten\node\4.1.1_64bit\bin
PATH += D:\build\emscripten\python\2.7.5.3_64bit
PATH += D:\build\emscripten\java\7.45_64bit\bin
PATH += D:\build\emscripten\emscripten\1.37.21

Setting environment variables:
EMSDK = D:/build/emscripten
EM_CONFIG = C:\Users\abyss\.emscripten
BINARYEN_ROOT = D:\build\emscripten\clang\e1.37.21_64bit\binaryen
JAVA_HOME = D:\build\emscripten\java\7.45_64bit
EMSCRIPTEN = D:\build\emscripten\emscripten\1.37.21

```

**Steps to reproduce:**
1. emscripten installation: https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#sdk-installation-instructions
2. run `emsdk_env.bat` generated by emscripten
3. go to godot source directory in the same terminal session
4. `scons platform=javascript tools=no target=release`

**Comment by akien-mga** [comment]
CC @eska014

**Comment by eska014** [comment]
Issue is that the `LLVM_ROOT` variable as defined in `~/.emscripten` determines how WASM templates are built. We should prefer reading `EMSCRIPTEN_ROOT` since both are defined in the config file, but fall back to `EMSCRIPTEN`.

By the way, `emsdk_env.bat` adds `em-config` to path, so you can call `em-config EMSCRIPTEN_ROOT` to get the value.
