### ISSUE TITLE
Get rid of huge functions

### ISSUE THREAD

**Issue by leonkrause** [godotengine/godot#12419]
Godot has at least 2 functions that are very big when compiled:

- [`match()`](https://github.com/godotengine/godot/blob/2987e6ce4ffc69da5efc0903cc00ce12e72d2125/thirdparty/pcre2/src/pcre2_match.c#L575-L6327) from PCRE2
- [`hq2x_resize`](https://github.com/godotengine/godot/blob/master/thirdparty/misc/hq2x.cpp#L199-L2636) (which inlines the local `isDifferent()` almost 200 times)

This increases the size of our binaries, so we should see what we can do about these. The code base should also be checked for more huge functions.

**Comment by akien-mga** [comment]
Both are from thirdparty components, we should try to get changes done upstream in priority (we can patch our copies in parallel as long as we keep track of changes with actual patch files):
- PCRE2: https://sourceforge.net/projects/pcre/ https://vcs.pcre.org/pcre2/code/trunk/
- hq2x: https://github.com/brunexgeek/hqx

**Comment by tagcup** [comment]
Have you tried optimizing for size with -Os and replacing force-inlines with ordinary inline?

**Comment by eska014** [comment]
This is about dealing with single overly large functions. `-Os` affects the whole code base, that's not the goal here (though we  should evaluate usage of `-Os` or `-Oz` for HTML5 builds).

**Comment by tagcup** [comment]
I don't understand how size can be concern for certain functions while not for others

**Comment by tagcup** [comment]
-Os can be specified for per-file BTW (by overriding optimization option) after isolate those functions in a file, it doesn't have to affect the whole code base

**Comment by Calinou** [comment]
Should we keep `hq2x_resize`, since we have a vector-based theme now? (The games still use the old image-based theme, but hiDPI isn't used there by default.)

**Comment by Dillybob92** [comment]
https://en.wikipedia.org/wiki/Hqx

This is very important to the engine isn't it? Especially for pixel games?

**Comment by akien-mga** [comment]
Closing as HQ2X was removed, and for PCRE2, I'm not sure what we could do.
