### ISSUE TITLE
Failure to build C# scripts in a app with no name.

### ISSUE THREAD

**Issue by ArtursKadikis** [godotengine/godot#12427]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7, 64 bit, Used the pre release version of 3.0 alpha2

**Issue description:**
When building a c# script in a application with no name, the following error is received:
"File name '.dll' is empty, contains invalid characters, has a drive specification without an absolute path, or is too long"

It also links to a ".csproj" file with no name.

**Steps to reproduce:**
Create new project, delete application name with the clear button, build a scene with a attached c# script.

**Link to minimal example project:**
[t2.zip](https://github.com/godotengine/godot/files/1420384/t2.zip)

**Comment by ArtursKadikis** [comment]
I can't really pin it down, but a big part of the problem seems to be that the empty project was exported from 2.14 to a 3.0 project with the button from the UI.

**Comment by akien-mga** [comment]
Most likely the mono logic relies on `application/config/name` and doesn't check that it's actually a non-empty string. If should default to something like `UnnamedProject` when it is.
