### ISSUE TITLE
3.0 Cannot build 

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#12428]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows7
scons 2.5.0
MinGW-W64 gcc 7.2.0 g++ 7.2.0

**Steps to reproduce:**
scons platform=windows

**Issue description:**
see log below:
[log.txt](https://github.com/godotengine/godot/files/1420679/log.txt)

**error info:**
editor\editor_icons.gen.cpp:1:10: fatal error: editor_icons.h: No such file or directory

 #include "editor_icons.h"

          ^~~~~~~~~~~~~~~~

compilation terminated.

**It looks like scons make a wrong file: editor_icons.gen.cpp**
I don't know what happen.
I guess it should be editor_icons.gen.h
Attach the editor_icons.gen.cpp file
[editor_icons.gen.zip](https://github.com/godotengine/godot/files/1420689/editor_icons.gen.zip)

**Comment by akien-mga** [comment]
Delete `editor\editor_icons.gen.cpp`, it's an obsolete file from a 2.1 build or a very old master build.
