### ISSUE TITLE
Fatal Error on Running Project with a C# Solution from attempting to load mscorlib.dll

### ISSUE THREAD

**Issue by Xydium** [godotengine/godot#12424]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 amd64, Godot 3.0 alpha2 and custom builds from master. Mono 5.4 installed.

**Issue description:**
Running a project with a C# solution crashes.

Additionally, the editor crashes on startup unless the ```mscorlib.dll``` file in the editor directory is renamed to ```mscorlib.dll.dll```.

Mono log file:
```
Config attempting to parse: 'C:\Program Files\Mono\etc\mono\config'. (in domain Mono, info)
Assembly Loader probing location: 'C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll'. (in domain Mono, info)
Image addref mscorlib[0000016E00F9F8F0] -> C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll[0000016E00FCE7A0]: 2 (in domain Mono, info)
Image addref mscorlib[0000016E00F9FF20] -> res://.mono/temp/bin/Tools/mscorlib.dll[0000016E122A98E0]: 2 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (res://.mono/temp/bin/Tools/mscorlib.dll) (in domain Mono, info)
AOT: image 'res://.mono/temp/bin/Tools/mscorlib.dll.dll' not found: The filename, directory name, or volume label syntax is incorrect.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/mscorlib.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly Loader loaded assembly from location: 'C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll'. (in domain Mono, info)
Config attempting to parse: 'res://.mono/temp/bin/Tools/mscorlib.dll.config'. (in domain Mono, info)
Config attempting to parse: 'C:\Program Files\Mono\etc\mono\assemblies\mscorlib\mscorlib.config'. (in domain Mono, info)
Config attempting to parse: 'C:\Users\Name\.mono\assemblies\mscorlib\mscorlib.config'. (in domain Mono, info)
Unloading image C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll [0000016E00FCE7A0]. (in domain Mono, info)
```

**Comment by Xydium** [comment]
The crash seems to be a different result of a similar cause to that in #12357. Instead of being unable to generate mono glue, it fails at the project execution step.

**Comment by neikeq** [comment]
Does this still happen after #12388? Make sure to remove the `.mono` directory in your project before trying.

**Comment by olejr** [comment]
Windows 10, clean build 3.0alpha cb5f2b2.
C# was working up until 452313f for me.
But now I when I create a new project with only a Node2D in it,
and (try to) attach a script to it I get a dialog box saying:
`Build error, Failed to build GodotSharp solution.`

And Mono warnings/errors display
`C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB6004: The specified task executable location "\\csc.exe" is invalid.`

So somewhere between 452313f and now somethingstopped working for me atleast.

**Comment by akien-mga** [comment]
Can you try again with 619e4eb23df037d152bf7776c5447d46293aadff? @neikeq just pushed new fixes.

**Comment by olejr** [comment]
Just tried 619e4eb, and same errors. Tested with a simple new project as described above.

**Comment by neikeq** [comment]
@olejr What build tool is selected in editor settings? If you run Godot in verbose mode (`-v`) do you see any other message in the console?

**Comment by olejr** [comment]
MSBuild (Mono). Same I was using pre 12388.
Console spits out: 
```
ERROR: ResourceFormatSaverCSharpScript::save: Cannot add res://Node2D.cs to the C# project because it could not be created. At: modules\mono\csharp_script.cpp:1943
running cmdline: "C:/Program Files/Microsoft VS Code/Code.exe"
```
It does create Nnode2D.cs though..

And then I tried MSBuild (System). And it does ehm, work..?,
None of the above errors, but it doesn't open the *.cs file in my external editor, just starting VS code with the welcome screen.  But dissabling external editor, adding a simple print in _ready does work..

Time for bed me think, to late for testing it seem.

**Comment by neikeq** [comment]
This is a bug with mono's msbuild installation. Setting CscToolsPath fixes it but results in another one. I think this was fixed by a recent PR on mono, but there are no binaries yet to test and I can't manage to build Mono on Windows... You will have to stick with `MSBuild (System)` option for now.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by neikeq** [comment]
Is the issue described by OP still happening? Also, this was reported when the logger had a bug not flushing before quiting the application, so could you share an updated log?

**Comment by aaronfranke** [comment]
Same question, is this still a problem? @Xydium @olejr ?

**Comment by olejr** [comment]
Haven't used the mono version for ages, but a quick test as I described above is working with v3.0.4 atleast.

**Comment by akien-mga** [comment]
Assuming fixed then.
