### ISSUE TITLE
Error when building on Windows with MinGW with LTO enabled

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#12433]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):** Windows 10 Fall Creators Update, Godot Git https://github.com/godotengine/godot/commit/ad85224ebcf7bbad5565457d355c429b02190c58

**Issue description:** Using MinGW-w64 from [MSYS2](http://www.msys2.org/), the build fails when `use_lto=yes` is used. However, it works when using `use_lto=no` (or when leaving it out, which defaults to `no`).

See the error log below (using Python 2.7.13):

```
scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\Users\hugol\Documents\Git\godotengine\godot\SConstruct", line 4, in <module>
MSVC not detected (no VCINSTALLDIR environment variable), attempting MinGW.
KeyError: 'use_llvm':
  File "C:\Users\hugol\Documents\Git\godotengine\godot\SConstruct", line 300:
    detect.configure(env)
  File "./platform/windows\detect.py", line 267:
    if not env['use_llvm'] and env.GetOption("num_jobs") > 1:
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.5.1\SCons\Environment.py", line 410:
    return self._dict[key]
```

**Steps to reproduce:** Build Godot with `use_lto=yes` with a MinGW-w64 compiler in the `PATH`.

**Comment by akien-mga** [comment]
I'm sure you can fix that yourself with a little nudge in the right direction: https://github.com/godotengine/godot/blob/master/platform/windows/detect.py#L265-L270

**Comment by akien-mga** [comment]
Hint: We don't support clang on Windows for now.
