### ISSUE TITLE
Open Godot with doubleclick/open file with... and etc.

### ISSUE THREAD

**Issue by gerchicov-bp** [godotengine/godot#12436]
I open with Godot on OSX. And it becomes a hell to work with its file explorer - it always opens the concrete inner folder and I should perform a lot of actions to open and import folder I need for the first time. Or I need to somehow copy a path and insert it into Godot window.

You could add something like ".project" file and allow to open it with Godot. Or maybe could you save/load the last used folder?

Anyways the current behaviour is not user-friendly.

**Comment by Hinsbart** [comment]
This is already the case with godot 3. Project files are named project.godot now so they can be associated with the godot editor (however this is not done automatically yet, but it only takes a few seconds)

**Comment by bruvzg** [comment]
>they can be associated with the godot editor

It doesn't work on macOS.

![nop](https://user-images.githubusercontent.com/7645683/32117571-92753864-bb57-11e7-8afc-b1fc3a3aea44.png)

- macOS looks for file associations in the application's `Info.plist` (there is no key for `project.godot`).
- macOS apps handle double-clicking a file via `NSApplicationDelegate application:openFile:` not command line arguments. (not implemented)
