### ISSUE TITLE
iOS export missing?

### ISSUE THREAD

**Issue by gerchicov-bp** [godotengine/godot#12431]
You write everywhere that it is possible to export to iOS...
Read this manual:
http://docs.godotengine.org/en/stable/learning/workflow/export/exporting_for_ios.html
```
Since there is no automatic deployer yet, unzip export_templates.tpz manually and extract GodotiOSXCode.zip from it.
```
where to get this zip? And as I understand ```godot -> ios``` is not possible and I should use ```godot -> html5 -> ios```, shouldn't I?

**Comment by akien-mga** [comment]
> where to get this zip?

http://downloads.tuxfamily.org/godotengine/2.1.4/Godot_v2.1.4-stable_export_templates.tpz

But if you installed the export templates already, it will be in your templates folder already.

> And as I understand godot -> ios is not possible and I should use godot -> html5 -> ios, shouldn't I?

No, iOS is supported natively.

**Comment by gerchicov-bp** [comment]
@akien-mga maybe can you also add a link to a page with this template? I mean, for example, what if godot 2.1.5 will be released?

**Comment by akien-mga** [comment]
![image](https://user-images.githubusercontent.com/4701338/32095467-9288e4bc-bb03-11e7-927c-682c7bf6f5d3.png)

**Comment by gerchicov-bp** [comment]
thanks
