### ISSUE TITLE
Change weight at the point in AStar 

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#12434]
Please add the weight change to a previously created point at AStar.
Something like this
```
// AStar node
void AStar::set_point_weight(int p_id, float p_weight_scale)  
{
     points[p_id]->weight_scale = p_weight_scale;
}
```
```
# GDscript code
AStar.set_point_weight(id, weight)
```

**Comment by mhilbrunner** [comment]
I'll sent a PR for this later today if nobody else did it by then.

Note that currently, you could use AStar:add_point() for this. If the point you give to add_point() already exists, it just updates it's position and weight_scale. This doesn't seem to be documented yet, however, so I'll include that. :)

**Comment by Noshyaar** [comment]
Is this #6531?

**Comment by mhilbrunner** [comment]
@Noshyaar As far as I can see, no. To quote that issue:

```
1. have a set_weight_scale(int point_id) function
2. have a set_custom_weigth_calculator(object, string function_name)
   func function_name(int point_from, int_point_to)
```

The PR only added the second one, while this is asking for the first one again, like that issue :)
Not hard to implement however, if I'm not missing anything.
