### ISSUE TITLE
AnimationPlayer playhead Step to scale with zoom level

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#12444]
EDIT: this issue has pivoted to instead suggest that the Step parameter of an animation track to automatically scale with the zoom level of the track, at least as an option.

In order to put a key on an animation track at a time value between a tenth of a second, you appear to have to manually type the value into the individual key editor.

You cannot drag the playhead there or even manually type in a playhead time, no matter how zoomed in the track is:

![animationplayheadsubdivisions](https://user-images.githubusercontent.com/15862731/32125887-0020746c-bb3c-11e7-9035-f18d7326852c.gif)

Perhaps the precision of dragging the playhead should be determined by the zoom level of the track? No matter how far zoomed out the track is, however, I think that the user should be able to manually type in a specific playhead time, without it auto-rounding.

PS: I know that there's currently an AnimationPlayer UX general discussion, but I felt that subdividing these into separate issues makes them easier to close individually.

**Comment by djrm** [comment]
thats determined by the step parameter

**Comment by Oranjoose** [comment]
@djrm So it is! Thanks for pointing that out.

It would still be kind of nice to have the Steps parameter automatically scale with the zoom scale on the track. I think that some non-linear video editors do this naturally.

**Comment by aaronfranke** [comment]
In Godot 3.1, you can manually specify the snap size, so this issue probably isn't relevant anymore:

![1](https://user-images.githubusercontent.com/1646875/59138916-e2b53100-895d-11e9-94d9-7bded85184a7.png)

> PS: I know that there's currently an AnimationPlayer UX general discussion, but I felt that subdividing these into separate issues makes them easier to close individually.

Still, could you link the parent issue then?

**Comment by Calinou** [comment]
I think a more intuitive way to handle this would be to add keyboard shortcuts to quickly halve or double the animation editor's step size. We already have similar shortcuts in the 2D editor – in fact, we could reuse the same shortcuts as long as the focus is currently on the animation editor.

**Comment by KoBeWi** [comment]
Given the low interest for this issue, it's fine to close it already.
