### ISSUE TITLE
In LineEdit, expand_to_len is ignored if set in the inspector

### ISSUE THREAD

**Issue by MattUV** [godotengine/godot#12447]
**Godot 3.0 build from 27 of October 2017**

**Issue description:**
In the LineEdit node, the inspector's property `expand_to_len` does not work until its value is updated in-game.

**Steps to reproduce:**
- Create a LineEdit and set `expand_to_len` to `true` **in the inspector** (There is no problem if it is set by code)
- Start the game, and the LineEdit won't expand.
- Do not quit the game , and by script or via the inspector (and Sync scene change), set `expand_to_len` to `true`.
- Now it works
 

**Link to minimal example project:**
[LineEdit expand_to_len.zip](https://github.com/godotengine/godot/files/1423650/LineEdit.expand_to_len.zip)

**Off topic**

1. What about renaming `expand_to_len` to `expand_to_text_length`, imho it is clearer...
2. If the text was longer than the LineEdit's width, when it expands, the left part of the text remains hidden and there is an equally large blank space on the right-hand side. Maybe it should worth another issue?

**Comment by akien-mga** [comment]
> What about renaming expand_to_len to expand_to_text_length, imho it is clearer...

I agree about that part, and should ideally be done for 3.0.
