### ISSUE TITLE
Drop-down menus not closing when clicked again

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#12451]
Godot 3.0, 10-27-17 build, Win x86-64, GTX 1060

After opening a drop-down menu (as in the menus at the top-left corner, or ones in the Inspector panel/dock), clicking the menu button again sometimes doesn't close the menu. This can be seen here:

![dropdownmenuissue](https://user-images.githubusercontent.com/15862731/32131804-5d4afe84-bb85-11e7-86e0-0b10f1d79daa.gif)

It more consistently closes if the button is clicked in rapid succession, and more consistently doesn't close if the click is held down for a slightly longer than normal time.

**Comment by starry-abyss** [comment]
Bothered by this too for any drop-down menus in Godot editor. Too used to having them closed on click in any other Windows software.

**Comment by dejaime** [comment]
It feels like single clicks never close the dropdown, but double clicks do. Maybe something to do with focus?

**Comment by reduz** [comment]
we would probably need to add a mode in Control or flag in popup() so, for some types of controls, clicking outside the area eats the event. This is per control (MenuButton would not want this, for example)

**Comment by poke1024** [comment]
@reduz https://github.com/godotengine/godot/pull/13351

I don't understand why MenuButton does not want this.

**Comment by akien-mga** [comment]
Fixed by #13351.
