### ISSUE TITLE
Issue adding nodes to a scene from an editor script 

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#12456]
Godot3.0 Alpha, Linux 64

When adding nodes to a scene for within a script that is run as an EditorScript (by using the add_child() method), nodes do appear in the 3D view, but they do not appear in the Scene Tree inspector and saving the scene doesn't save the added nodes.

Is this a bug or is this intended?

**[EDIT]**
Example:
[GodotSceneAdd.zip](https://github.com/godotengine/godot/files/1895587/GodotSceneAdd.zip)

**Comment by Zireael07** [comment]
They need to have the owner set to show in the scene tree.

**Comment by m4nu3lf** [comment]
@Zireael07 like this?
`	scene = get_scene()
	var spatial = Spatial.new()
	spatial.set_owner(scene.get_tree())
	scene.add_child(spatial, true)`
Still not working

**Comment by Zylann** [comment]
@m4nu3lf no, `get_scene_tree()` is the default ingame owner. You should set the editor tree owner:
`get_tree().get_edited_scene_root()`

**Comment by m4nu3lf** [comment]
@Zylann Can you provide a snippet in the above context?

**Comment by Zylann** [comment]
Same snippet as yours:
```gdscript
scene = get_scene()
var spatial = Spatial.new()
spatial.set_owner(scene.get_edited_scene_root())
scene.add_child(spatial, true)
```

**Comment by m4nu3lf** [comment]
It desn't work for me. set_owner() is expecting a SceneTree not a Node and get_edited_scene_root() returns a Node. Also get_edited_scene_root() has to be called on a SceneTree so I'm doing set_owner(scene.get_tree().get_edited_scene_root())

**Comment by Zylann** [comment]
Ah sorry I mistyped, I meant `get_tree().get_edited_scene_root()`. I edited the post

**Comment by m4nu3lf** [comment]
@Zylann With that code I get an assertion
`Condition ' !owner_valid ' is true` and still no nodes visible in the scene inspector

**Comment by Zylann** [comment]
@m4nu3lf when are you doing this? Keep in mind that nodes must be in the tree, so for example if you do this in a setter, setters can be called before the node to be added to the tree.

**Comment by m4nu3lf** [comment]
inside _run() in a script derived from EditorScript they I hit 'Run' from the script editor menu

**Comment by bojidar-bg** [comment]
What about using `set_owner(scene)` or `set_owner(scene.get_owner())`?

**Comment by mhilbrunner** [comment]
Closing this, as there was no more feedback. If this is still an issue for you, please let us know so we can reopen this issue.

**Comment by m4nu3lf** [comment]
Here is an example: https://www.dropbox.com/sh/lsvrxz5hx0wnhs3/AADFtLfCxhTC5AHEtt7kpZMKa?dl=0 
If you run the 'add_to_scene.gd' script on the main scene you can see an OmniLight has been added but it is not visible in the editor nor it is persisted.

**Comment by Noshyaar** [comment]
Would you mind uploading to Github by dropping the file directly on reply box so that it can be reference when you move it?

**Comment by mhilbrunner** [comment]
Reopening then. And yeah, uploading directly to GH here would be ideal. Thank you!

**Comment by vnen** [comment]
Didn't check the projects, but not that you need to call `set_owner` **after** `add_child`. The owner must be a parent of the node.

**Comment by bojidar-bg** [comment]
I gave a quick check of the project, note that set_owner(scene) is the correct one, set_owner(scene.get_owner()) won't work, since the current scene's root's owner is `null`, bacause no scene owns it.

**Comment by m4nu3lf** [comment]
@vnen Unfortunately it doesn't seem to change anything.
@bojidar-bg `set_onwer(scene)` raises an error (`scene/main/node.cpp:1685 - Condition ' !owner_valid ' is true.`)

**Comment by vnen** [comment]
>  `set_onwer(scene)` raises an error (`scene/main/node.cpp:1685 - Condition ' !owner_valid ' is true.`)

This happens if the owner you're trying to set is not a parent of the node. It can be an indirect parent, but must be above in the same tree.

**Comment by vnen** [comment]
Actually, your test project works for me (after making @bojidar-bg's suggested change):

![2018-04-12_23-57-31](https://user-images.githubusercontent.com/5599796/38714594-5ec1fafa-3ead-11e8-9853-356d610b43a3.gif)

**Comment by m4nu3lf** [comment]
@vnen I tried again and it worked for me too, dunno what I was doing wrong. Thanks @bojidar-bg!
I think the issue can be closed

**Comment by aftamat4ik** [comment]
i do it this way (c#)
```cs
var newPart = new Node();
newPart.Name = "TestName";

GetParent().AddChild(newPart, true);
newPart.Owner = (Engine.IsEditorHint()) ? GetTree().EditedSceneRoot : GetTree().Root;
```
and it works
![image](https://github.com/godotengine/godot/assets/4356170/9fb13208-314c-4581-a17b-1aea4f00740f)
