### ISSUE TITLE
Option to set a node as editor only

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#12453]
Godot 3.0, build 10-27-2017

There should be an option to let a node remain visible in editor, but be invisible in game. Clicking the eye icon in the Scene panel just sets true and false on the node's Visible property, making it invisible in the editor as well.

It would be nice if this feature could be toggled per node, rather than a View menu setting which makes all invisible nodes visible or not in the editor. Maybe a Visible In Editor checkbox in the Inspector dock (next to the Visible property checkbox) that doesn't represent a property in the code?

**Comment by Zylann** [comment]
Like the "editor only" flag available on lights?
Because there is no point in hiding a node ingame if it's just in editor anyways, the real use case would be to have the scene loader ignore it when playing the game, and strip it on export.

**Comment by kubecz3k** [comment]
Just do in ready something like
`if(Engine.is_editor_hint()): node.hide; #or node.queue_free()`

**Comment by Zireael07** [comment]
Scene loader ignoring when loading/exporting would be a great idea. I often have "editor only" stuff such as debugging lines using ImmediateGeometry.

**Comment by Oranjoose** [comment]
@zylann I feel that people are misunderstanding what I'm requesting. Editor-only nodes are def useful, such as with level design sketches as overlays for laying out a level in editor.

But I also believe that it is useful to have a visible in game flag, for objects you only want only visible in editor but still *exist* in the game. For example, you could have a bunch of different types of invsible trigger zones or invisible walls color-coded for different events and purposes.

I suppose you could put an editor only flag on just the graphical element, maintaining the functionality of the collisionshape.

**Comment by Calinou** [comment]
I think this would be useful to have. In fact, I'd also like to see a "Game Only" option (which hides the node in the editor).

This way, you won't need to script the node hiding.

**Comment by Oranjoose** [comment]
@Calinou Yes, I agree that would be useful as well. A lot of set decoration in levels get in the way of editing the level, and it would be annoying to have to group them all together and hide them temporarily just to have to unhide them every time you wanted to test the game.

**Comment by kubecz3k** [comment]
Hmm sounds a little like 'load scene as placeholder' option

**Comment by puppetmaster-** [comment]
I use group to handle visibility:
```
for _debugNode in get_tree().get_nodes_in_group("debug"):
	_debugNode.hide()

for _decorationNode in get_tree().get_nodes_in_group("decoration"):
	if get_tree().is_editor_hint():
		_decorationNode.hide()
	else:
		_decorationNode.show()
```

**Comment by hubbyist** [comment]
I had a similar need #9029 some time ago. May be these two can be merged in a single solution by the way. WDYT?

**Comment by kubecz3k** [comment]
I think it should be implemented by allowing to set 'load as placeholder' flag for every node, not only subscene ones. When any subscene has load_as_placeholder flag set, it will not load in runtime, and instead blank empty node is used, but there still is possibility to instance it with `replace_with_instance` function. 

That way it would be useful not only for 'editor only' gizmos but also in scenarios like game settings, where I for example would like to choose if node should be loaded based on [condition] / [graphic_settings] (like for example GiProbe or ReflectionProbes which take while to load or even unload so it's not really practical to freed them after loading).

**Comment by kubecz3k** [comment]
What I meant was basically that we can use the fact that placeholder nodes are available in the editor (don't think any modifications in the editor are even necessary), but they are not loaded in runtime by default. 
Not sure what would be the best way to implement "placeholder" mode for not instanced nodes.

**Comment by vnen** [comment]
There are two issues with placeholder:

1. It must be loaded via code.
2. It's a node, so it's occupying a place in memory and in the tree.

Also, I don't think it allows to make an game-only node.

**Comment by kubecz3k** [comment]
@vnen about second point, as long as you don't instance it will take neglectable amount of memory. And yes it would not be possible to create game-only nodes this way, but can't find use case for that one (keep in mind that if node is not working in tool mode it's logic won't be performed in Editor).

**Comment by willnationsdev** [comment]
Are tool scripts not compiled into the release of a game though? Or does a tool script still show up in the node hierarchy upon exporting to a platform (I thought they still did)?

**Comment by volzhs** [comment]
`tool` makes script can be executed **in editor also**.
it's not tool only.

**Comment by vnen** [comment]
Well, if game-only nodes aren't needed then my first point is moot, because you won't load the placeholder in game.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Zireael07** [comment]
I think we have a similar proposal already on godot-proposals?

**Comment by Calinou** [comment]
@Zireael07 Indeed, I edited my message accordingly.

**Comment by Calinou** [comment]
> It doesn't seem like the proposal and the followup to that proposal are really the same as this issue. And I think it would be very useful to have as a base feature.
> 
> Do you know of some other proposal? I couldn't find any.

I just opened a proposal: https://github.com/godotengine/godot-proposals/issues/3433
