### ISSUE TITLE
Particles and Particles2D preprocess property doesn't do anything

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#12460]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64bit - Godot 3.0 master

**Issue description:**
I added a Particle node to the scene and I set the particle lifetime to 5, and the preprocess time to 5. But when I play the scene the particle system start from the beginning, and doesn't have 5 seconds worth of preprocessing. This happens to both 3D and 2D particles.

**Comment by jesperkondrup** [comment]
This is the same issue in 2.1.4, the "Preprocess" variable does not seem to do anything.
