### ISSUE TITLE
Unchanged EditorSettings properties appear as revertable, and disappear when reverted (regression from 5676c42ae)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#12463]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mageia 6 x86_64, current master (87dbb716)

**Issue description:**
When browsing the Editor Settings, many properties appear as revertable, even though I know that I never modified them. Reverting them either does nothing or reverts to Null, and in some cases the property disappears from the list with a corresponding console warning, e.g. `EditorSettings::_get - Warning, not found: filesystem/file_server/password`.

![spectacle m19962](https://user-images.githubusercontent.com/4701338/32136071-5a596b3c-bc09-11e7-93b3-d753bd690142.png)

It's obviously a regression, but I can't tell from when for now. Bisect welcome :)

**Steps to reproduce:**
- Delete/rename your `editor_settings-3.tres` for a clean testing environment
- Start Godot once to get the file generated
- Restart Godot (easier to reproduce this way in my experience, though maybe not mandatory)
- Check the Editor Settings, e.g. in the `filesystem/file_server` category: both the `port` and `password` properties should be shown as changed. If you revert `password`, its values goes from 0 to Null and it then disappears.

**Comment by akien-mga** [comment]
The regression was already there in 3d87b70f7, which looks like a potential culprit. Currently building its parent to confirm.

**Comment by akien-mga** [comment]
The commit introducing the bug is 5676c42ae, cc @djrm.

**Comment by djrm** [comment]
@akien-mga when they dissapear it means that those settings no longer exists, so i think thats ok (well i think they should be discarded by the editor before showing them), previously they were simply ignored, if there are options that are still used but are dissapearing then maybe there is a problem with the definition of those.
