### ISSUE TITLE
Special character display issue in Locale filter and Language option

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#12462]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64 - Godot Master feb30bf 

**Issue description:**

In Project Settings > Localization > Locale filter
![image](https://user-images.githubusercontent.com/26753932/32135937-12c63d36-bc31-11e7-8880-8cd8b6853917.png)

In Project Manager > Language option
![image](https://user-images.githubusercontent.com/26753932/32135945-2c371f24-bc31-11e7-8290-ced64c0b0d2d.png)

**Comment by mhilbrunner** [comment]
Can reproduce this on current master on Windows 7 x64. Probably the same Unicode strings issue as discussed in #11440. Fixing that should fix this too.
