### ISSUE TITLE
Invalid parsing of Windows Norwegian Bokmål locale (no)

### ISSUE THREAD

**Issue by ThalesDavidsen** [godotengine/godot#12479]
Windows 10 - 64 bit, Godot v3.0.alpha.custom_build.87dbb71,

Trying to run a project

Run a project

![error_message](https://user-images.githubusercontent.com/32776982/32143403-f8aa5fae-bca8-11e7-9c92-287aebb39447.jpg)

**Comment by akien-mga** [comment]
Can you run `systeminfo.exe` and check the identifier of your locale? It seems to be Norwegian Bokmål but I'd need to know its identifier, e.g. `nb_NO` or similar.

**Comment by ThalesDavidsen** [comment]
Attached are the systeminfo output, is says:
`no; Norsk (bokmål)`
![systeminfo](https://user-images.githubusercontent.com/32776982/32148417-fccbcc82-bcf6-11e7-846b-206d03eb622a.jpg)

**Comment by akien-mga** [comment]
Could you test the patch in #12492?
(You can download it as https://github.com/godotengine/godot/pull/12492.patch and apply it with `git apply`)

**Comment by akien-mga** [comment]
Well now it's merged, so you can just update your local master branch (`git pull --rebase`) and compile.

**Comment by ThalesDavidsen** [comment]
Yes the issue is now gone :)

**Comment by akien-mga** [comment]
Awesome, thanks for checking.
