### ISSUE TITLE
Resizing window creates font tearing/artifacts

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#12477]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2.1.4, W7 64-bit

**Issue description:**
When resizing the window (do it very slowly to catch an odd number), the font becomes out of line and cracks.

 - Only happens if the window size is a odd number.
 - Only happens if the anchor is set to anything other than `Full Rect`
 - Happens with `BitMap`, and regular TTF fonts

[FontArtifacts.zip](https://github.com/godotengine/godot/files/1424981/FontArtifacts.zip)

**Comment by Zylann** [comment]
Similar issue #12317

**Comment by Dillybob92** [comment]
@Zylann Lol, that's odd (pun intended), my artifacts are created from odd integers, while yours happen from non-regular integers.

A better love story than twilight

**Comment by Zylann** [comment]
@Dillybob92 I linked the issue because my repro was the same as yours^^ (resizing the window to get odd numbers)

**Comment by Dillybob92** [comment]
@Zylann Yes, but mine happens with odd integer numbers, not just non-integers

**Comment by Zylann** [comment]
@Dillybob92 and that could be the hint that stuff you see artifacts on may be drawn at non-integer position due to these odd numbers ;)

**Comment by Dillybob92** [comment]
@Zylann Yeah. Btw, I know a temporary solution to this if anyone comes across these issues and is about to publish their game.


connect signal:
`get_viewport().connect("size_changed", self, "resizeScreen")`

```
func resizeScreen():
	var size = OS.get_window_size()
	var nW = size.width
	var nH = size.height
	
	if int(size.width) % 2 == 1:
		nW = size.width + 1
	if int(size.height) % 2 == 1:
		nH = size.height + 1
	
	OS.set_window_size(Vector2(nW, nH))
```

**Comment by Zylann** [comment]
Ouch dirty workaround^^
But I think that won't work if any window or container has an odd size.

**Comment by Dillybob92** [comment]
@Zylann well, that makes it so it will never end up with an odd size, lol so it works

but yes it's nasty

**Comment by Zylann** [comment]
@Dillybob92 What I meant is, say you have 3 panels of equal size anchored to the window. They can end up with an odd size even if the window is even ;D

**Comment by Dillybob92** [comment]
@Zylann, hmm can u give me a little example project of what u mean so i can test this?  I'm not sure what u mean, I understand the 3 panels anchored, but if they are all the equal size, i'm not sure how odd number will flourish from that. 

I did try with panels with odd numbers of position and size and my code worked but you do have a point and want to test that, it could be a nasty bug later :P

**Comment by Zylann** [comment]
@Dillybob92 if you have a layout where all 3 panels have equal size, their width for example, will be constrained to be a third of their container. So divide by 3, here you have your odd numbers :p
But the real point I think is about non-integer drawing, odd number on its own doesn't harm.

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
