### ISSUE TITLE
Feature request : 3D camera free look option while scene's running (for academics, archi., etc)

### ISSUE THREAD

**Issue by metadirective** [godotengine/godot#12478]
Hi,

In Godot it's easy to import a dae file with its 3D objects, Lamp and Camera.
Godot is light, have many builds/export options, doesn't require authentication or specific rights.   

With a camera free look option it could also be ideal for 3D modelers, academics, architects, artists, etc, to rapidly share their projects to the world without being developers yet.  Having the power of scripting and the great Godot community could convince some to go further. 

Currently academics I know use SecondLife/OpenSim (full persistent 3D and social space) and/or Sketchfab (more suited for a single object viewing and external); something is missing in between, Godot could be also ideal there.

Anyway thanks for the great work, looking forward to 3.0 :)

**Comment by akien-mga** [comment]
Godot 3.0 has a freelook option already, implemented by @Zylann.

**Comment by metadirective** [comment]
Yes I know but from those answers it's only in edit mode?
https://www.reddit.com/r/godot/comments/793d60/camera_free_look_when_scene_is_running/
Can you confirm it runs also when the game is running ? (the way people will share their work), thanks!

**Comment by Zylann** [comment]
If you want this to run in the game window you can add a script to the camera that does this.

**Comment by Calinou** [comment]
> If you want this to run in the game window you can add a script to the camera that does this.

This is indeed easy to do. Here's a freelook camera script:

https://gist.github.com/Calinou/820ca6211eef32f531d26e89c4262de9

Be sure to create input actions in the project's Input Map. Note that there's an issue with precision errors, which can make your camera steer where it shouldn't while moving diagonally upwards or downwards.

**Comment by metadirective** [comment]
Thanks all, sounds great 👍 

@Calinou I'm not familiar with GDscript yet.
When I import the Blender cube .dae as a scene I have those nodes under the root node (Camera, Lamp, Cube, AnimationPlayer)
I take your raw script and attach it to the Camera node.
If I run the scene I have an error in debugger tab,
Parser Error: ':' expected at end of line.
and if i select and then copy/paste the entry in Errors tab, 
"""
	if event is InputEventMouseMotion and
 Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:
"""
Additionally I also added some inputmap keys for ui_left, ui_right, ui_up, ui_down, ui_page_up, ui_page_down (didn't see forward / backward)
I also tried this at the beginning of your script but without effect (something I've seen in a Youtube video),
"""
func _ready():
	set_process(true)
	set_process_input(true)
"""
What should i do ? Any good tutorial I could follow in order to achieve this ?  Thanks.

**Comment by Hinsbart** [comment]
That script is meant to be used with Godot 3 and would need some modifications to run on 2.1

**Comment by metadirective** [comment]
Ha yes, sorry. Just installed Godot3 alpha2 build. Mouse works great, couldn't make my Input Map key binding  work though ("Request for nonexistent InputMap action : toggle_hud" at each key press)

**Comment by mhilbrunner** [comment]
@metadirective Godot 3.0 Alpha 2 should be released soon (next few days?), maybe wait until then

**Comment by metadirective** [comment]
@mhilbrunner Ok, was using the alpha2 build mon-testing,
http://op.godotengine.org:81/downloads/3.0/alpha2/mono-testing/

**Comment by akien-mga** [comment]
Closing as this wouldn't be implemented as a feature in exported games for the reasons mentioned above. Godot can do any type of games and embedding a default FPS/freelook-like character controller in all games would be out of the scope of what the engine offers.

Feel free to continue discussing here though, I think have a couple ready-made controllers in the asset library for this use case would be very welcome.
