### ISSUE TITLE
Doctool doesn't fix invalid setters/getters in <member> tags

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#12476]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Any, current master (d4d12eba5)

**Issue description:**
When running `godot --doctool .`, the setters and getters documented in `<member>` tags don't seem to be validated, so if they were manually changed, or changed in the source, they keep their old value.

Example from `Image.xml`:
- Correct tag: `<member name="data" type="Dictionary" setter="_set_data" getter="_get_data">`
- If you change things in the `setter` and `getter` parts, doctool won't fix them and the modified values are kept
- If you remove the tag altogether, then it's properly recreated with the expected setters/getters.

**Steps to reproduce:**
- Modify some `<member>` tags and run `godot --doctool .`.

**Comment by reduz** [comment]
i still dont get the problem, afaik these will be recreated with doctool since one is not supposed to modify them

**Comment by akien-mga** [comment]
Well the problem is as described above, if one *does* change the setter/getter manually, doctool does not perform any kind of validation and keeps the wrongly modified value.

I haven't checked what happens if we change the setter in code and run doctool, but it might have the same issue.

**Comment by reduz** [comment]
This may have to do with the merge_from function in docdata that is copying setter and getter(when it should not, code is here:
https://github.com/godotengine/godot/blob/master/editor/doc/doc_data.cpp#L43

**Comment by akien-mga** [comment]
Fixed by #29428.
