### ISSUE TITLE
Mono: prevent circular base class dependencies at script creation

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#12483]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Any, current master (f327fba62)

**Issue description:**
C# scripts must be named the same as their class, so the choice of the script name is quite important when creating a new script. Renaming scripts is not super convenient, so for a good UX we should aim for a good first name.

So far the name will be inherited from the Node name, which is cool for GDScript, but causes circular base class dependencies in C#. For example if my node a Sprite with its default name ("Sprite"), the new script dialog will propose "Sprite.cs" as script name, and I'll end up with `public class Sprite : Sprite` which is invalid.

I've also had a case where it proposed `class.cs` by default, and `public class class : Sprite` was also bogus as `class` is a reserved identifier.

Not sure how best to improve the UX without overloading the script creation dialog. Maybe script languages could register a list of reserved tokens which are not allowed as class/script names?

**Comment by thomak-dev** [comment]
Btw, you can just fully qualify the base class name. E.g. public class Sprite : Godot.Sprite. You don't need to rename your class. And you shouldn't be forced to by the engine, imho. That's what namespaces are for.

**Comment by NathanWarden** [comment]
That's a really good point. I think detecting the word "class" and replacing it with something else is a good idea when C# is selected, which I think "class" is a default GDScript name right?

For things like Sprite, Spatial, Node2D, etc maybe just prefixing or giving a suffix to it with something would be good. Something like "ScriptedSprite", "ScriptedSpatial", "ScriptedNode2D". I'm not sold on the prefix "Scripted", but just as an example...

**Comment by Hinsbart** [comment]
I like @thomak-dev's approach.
We could just check if the class name is registered in ClassDB and prefix the base class with `Godot.` if needed.

**Comment by thomak-dev** [comment]
@Hinsbart 
Or even simpler, always prefix it? A potentially redundant namespace qualifier doesn't hurt anyone, and it can always be removed by hand.

**Comment by neikeq** [comment]
No need to always prefix, we can just use reflection to check if it's needed.

In the case of class, we shouldn't allow it in the first place
