### ISSUE TITLE
2D Marquee selection selects child nodes that shouldn't be editable

### ISSUE THREAD

**Issue by bluepandion** [godotengine/godot#12487]
Godot 2.14, Windows 10 64bit

If a tool script creates any child nodes for itself they are normally not selectable, but instead direct clicks to select the parent that created them.

A marquee selection does select those child nodes and exposes them in the inspector view, showing any common editable variables:
 - It is possible to corrupt the child nodes through the inspector view.
 - It's also possible to move the child nodes with arrow keys.
 - Pressing delete correctly pops up an alert saying "Can't operate on nodes from a foreign scene!", implying they should not even be selectable.

**Steps to reproduce:**
In the example scene, marquee select the red rectangles. If the marquee only has them inside, you've selected child nodes created by a tool script and not the nodes shown in the scene tree-view.

**Link to minimal example project:**
[bug_marquee_2d.zip](https://github.com/godotengine/godot/files/1425458/bug_marquee_2d.zip)

**Comment by Zylann** [comment]
If your tool script creates child nodes that shouldn't be editable, why not make them not visible in the tree in the first place? That's easily done by not setting their owner to be the edited scene root.

**Comment by bluepandion** [comment]
@Zylann Yes, exactly.
It's very useful to use child nodes to render complex things and still be able to select the actual parent through them. This bug just makes it a hazardous way of doing things.

There was a similiar bug about scene-instances and marquee selections that was fixed a while ago.

**Comment by bojidar-bg** [comment]
Is this still an issue after @groud's refactor of the cavansitem editor? (e.g. on master)

**Comment by groud** [comment]
I guess "marquee" selection is the "non-selectable children" option.
This should be fixed on master.

**Comment by groud** [comment]
Closing as supposed fixed on master. If you find a similar problem, please open a new issue.
