### ISSUE TITLE
MeshLibrary items preview are displayed upsidedown

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1248]
Hi, 

Godot 1.0stable official, win64.

preview images of the items displayed into a MeshLibrary pannel are displayed upsidedown.

**Comment by reduz** [comment]
hehe nice bug

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment]
Ping :)

**Comment by neikeq** [comment]
I cannot reproduce it on current master branch. A quick way to check it is with the Platformer 3D demo in the _stage.xml_ scene.

**Comment by akien-mga** [comment]
Closing then.
