### ISSUE TITLE
Failed loading file 'projectname.wasm': Not found. 

### ISSUE THREAD

**Issue by jjgriff93** [godotengine/godot#12498]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 webassembly export. Azure ASP.NET Core webapp (IIS Server)

**Issue description:**

We're currently using the Godot 3.0 webassembly exporter for our web game project. We've been testing it on a standalone Azure server using the default html page as the homepage and have been having no issues. However, we now need to integrate it into our website, which is on a separate server, and to do so, I merged the html code that's produced by the webassembly export into the webapp's Play.cshtml page and added the other webassembly files into the same folder as the cshtml, to replicate the structure of the standard export.

When loading the page we're getting either "Failed loading file 'projectname.wasm': Not found." or "Failed loading file 'projectname.pck': Not found.", and it appears to be random as to which message appears. I believe this is being caused by the fact that webapps in Azure use relative paths ( ~/ ) and I had to change the projectname.js reference in the html to have a relative filepath as it wasn't finding it initially. I tried to do the same for the .pck reference in the html, however that seems to affect the .wasm filename as well - and by putting ~/ before projectname.pck, all it does it produce this error message instead: "Failed loading file '~/projectname.wasm': Not found." as it's recognising it as the file name instead of a trigger to treat it as a relative path.

Is there any way around this? I've had a look through the .pck file but can't find where the .wasm name is created and any way of changing this seems inaccessible, so may require a code change to get the export to work in Azure webapps and other hosting providers that force relative paths. Thanks in advance!

**Steps to reproduce:**
Merge the webassembly export into a standard ASP.NET Core Azure webapp project in the index.cshtml page.

**Link to minimal example project:**

**Comment by akien-mga** [comment]
CC @eska014

**Comment by eska014** [comment]
The HTML5 platform's infrastructure changed a lot during Godot 3.0, so please specify either a commit hash or a tag like 3.0-alpha1

Currently if you use e.g. `game.start('../test/projectname.pck')`, the `.wasm` and `.pck` will be expected to be in the same directory with the same basename, so the `.wasm` file would be expected at `../test/projectname.wasm`.
I you want to load the `.wasm` file from another directory, call `Engine.initEngine('path/to/godot.wasm')` before calling `game.start('path/to/godot.pck')`.

But unless you're hosting many Godot games, it probably makes more sense to just put the `.wasm` and `.pck` file in the same directory.

**Comment by jjgriff93** [comment]
Thanks for your reply @eska014 , appreciate your help. Apologies will make sure to specify in future.

So the issue wasn't actually that the .pck and .wasm files being in separate directories as they're both located in the /wwwroot folder, which is where ASP.NET serves static files from. It was just that because the operator for specifying a relative file path in .NET is '~/' - when I was using this to specify a relative path in the JavaScript script, it wasn't understanding the operator in the same way. Turns out the solution was modifying the static files middleware in the webapp and then simply using '/' in JavaScript and not '~/' :)

All working fine now, thanks again for your help and absolutely loving Godot 3.0 so far!
