### ISSUE TITLE
Pressing Enter with text selected doesn't erase the text in script editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12494]
Godot 2.1.4, not tested yet in 3.0
Windows 10 64 bits

Repro:
1) Select some text in the script editor
2) Press enter
3) Notice a newline is added but the selected text isn't deleted.

I expected the code to be removed.

**Comment by laspencer91** [comment]
Not sure if this helps. I am only about 10 minutes into looking at the Godot source, but the console did print this error out. Selected some text and hit enter.

![image](https://user-images.githubusercontent.com/26290454/32236287-bc8687e0-be2f-11e7-8e65-f04e39b342c3.png)

**Comment by lmjk** [comment]
This is still reproducible in 2.1 as of 74a8a91da3e71ccb2e56e477aff104a5fbcee155.
