### ISSUE TITLE
GridMap editor doesn't paint anything

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12501]
Godot 3.0 Windows 10 64 bits
nVidia geForce 940M

I noticed quite recently that the GridMap editor is showing nothing when I try to paint stuff with it. The same project used to work fine a week ago (as I was experimenting this in another branch https://github.com/godotengine/godot/issues/12338)
I put a breakpoint near `set_cell_item`, and the editor does set cells that are valid, but nothing gets shown, not even the cursor. I can only see the orange grid.

Video:
https://www.youtube.com/watch?v=EC3UquGKxoU

When Ioad the scene containing the gridmap, this error gets logged:
```
ERROR: PopupMenu::set_item_checked: Indexp_idx=-1163005939 out of size (items.size()=4)
   At: scene\gui\popup_menu.cpp:644
```
When I select the gridmap, these errors get logged:
```
ERROR: Object::get_meta: Condition ' !metadata.has(p_name) ' is true. returned: Variant()
   At: core\object.cpp:950
ERROR: RID_Owner<struct VisualServerScene::Instance>::get: Condition ' !p_rid.is_valid() ' is true. returned: 0
   At: d:\projets\info\godot\engine\godot_fork\core\rid.h:153
ERROR: VisualServerScene::instance_set_visible: Condition ' !instance ' is true.
   At: servers\visual\visual_server_scene.cpp:561
ERROR: Object::get_meta: Condition ' !metadata.has(p_name) ' is true. returned: Variant()
   At: core\object.cpp:950
```
No errors when selecting the cube or painting.

Project:
[GridMap.zip](https://github.com/godotengine/godot/files/1425679/GridMap.zip)

**Comment by tofuhead** [comment]
looking at your meshlibrary it doesn't actually contain any meshes, just preview image. I think something went wrong with creating the library?   I opened the mesh_library.tscn, added the cube mesh, and exportet it again to tres... then it shows just fine.


.b

**Comment by Zylann** [comment]
Weird, I havent touched this library since the day I created it a week ago Oo

**Comment by Zylann** [comment]
Ok you were right... the resource contained a big PoolArray of integers, not sure why. I re-exported the MeshLibrary and now it works.
