### ISSUE TITLE
Physics improvement: Add the ability to constrain bodies along a given axis.

### ISSUE THREAD

**Issue by ScottMakesGames** [godotengine/godot#12500]
When making side scrolling game with 3D assets, the objects can push each other in any direction, including forwards and backwards off the level (along the Z axis).
![image](https://user-images.githubusercontent.com/1318345/32150471-7501ff94-bd67-11e7-8454-aa084bfb87a1.png)

I've solved this for my project by creating a scene with a single Node and script that constrains objects on a set axis:
![image](https://user-images.githubusercontent.com/1318345/32150482-a7b3c800-bd67-11e7-9472-9b60ab2b4a96.png)
and script:
![image](https://user-images.githubusercontent.com/1318345/32150486-b86e29c4-bd67-11e7-9037-de25ddb8745e.png)

I just instance this node as a child of every single physics object I create. It would be great to have an in-engine solution for this however, similar to Unity where a RigidBody has a series of checkboxes for constraining objects on specific axes.

Ideally it would be available on KinematicBody and RigidBody in Godot, so it would be implemented for PhysicsBody i guess?

A screenshot from the Unity docs for reference:
![image](https://user-images.githubusercontent.com/1318345/32150528-6b28242a-bd68-11e7-9b37-99e60e01e17d.png)

**Comment by bojidar-bg** [comment]
RigidBody has it, under the name of "axis lock":
![image](https://user-images.githubusercontent.com/5276727/32167037-60107774-bd70-11e7-96e6-5153dd3eec5a.png)
(Screenshot is from 3.0, but I remember it being there in 2.1 as well)

**Comment by ScottMakesGames** [comment]
That's really interesting, I had no idea. It would still be great to have in KinematicBody too.

**Comment by fracteed** [comment]
Agreed, I would really like to have this for the kinematic body! In my 2.5d game I am finding that even though I am not using any y value for move_and_slide ,that kinematic bodies can randomly start floating in the y direction after collisions. I have solved this by resetting the y position after each move_and_slide command, but it would be nicer to just apply an axis lock and avoid any potential weird behaviour.

**Comment by nhydock** [comment]
Could axis lock also be a set of checkboxes, in case someone wants to lock along more than one axis?
