### ISSUE TITLE
Adding a Group in editor should offer drop-down or autocomplete

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#12502]
Godot 3.0

When adding a node to a group from the Node dock in the editor, it would be nice if the engine could survey the other groups that have been created in the game, and list them in a drop-down in the field next to the "Add" button.

For that matter, it would be nice if calling the `is_in_group ` function could do the same thing, listing all the groups that have been added to the game.

**Comment by willnationsdev** [comment]
Related to #5744.

**Comment by akien-mga** [comment]
Fixed by #16502.
