### ISSUE TITLE
Forwarding of keyboard events for CanvasItemEditor plugins

### ISSUE THREAD

**Issue by poke1024** [godotengine/godot#12505]
The forwarding of keyboard events got broken with fc02605.

The problem seems to be that this code inside `CanvasItemEditor::_gui_input_viewport` no longer gets called when input events come in as they now arrive at `CanvasItemEditor::_gui_input_viewport_base`:

```
		EditorNode *en = editor;
		EditorPluginList *over_plugin_list = en->get_editor_plugins_over();

		if (!over_plugin_list->empty()) {
			bool discard = over_plugin_list->forward_gui_input(p_event);
			if (discard) {
				accept_event();
				return;
			}
		}
```

**Comment by reduz** [comment]
is this still an issue? @groud ?

**Comment by groud** [comment]
Yes, I am working on a big rework of how the canvas item editor handles input, but it takes a lot of time.

**Comment by mhilbrunner** [comment]
Also an issue with viewport input handling: https://github.com/godotengine/godot/issues/15488

**Comment by akien-mga** [comment]
At this stage it would be too late to try to fix this and potentially introduce regressions in 3.0, so it will have to wait for 3.0.x / 3.1.

**Comment by groud** [comment]
Note, this is fixed in my reworking of the 2D editor. 
I still have some work to do, but it should be ready before 3.1 :)
