### ISSUE TITLE
Build failure when compiling using MinGW with LTO enabled (with more than 1 thread)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#12516]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
- Windows 10 Fall Creators Update / Fedora 26 (both using MinGW-w64, with GCC 7.2.0)
- Godot Git https://github.com/godotengine/godot/commit/fd89924ea55209ff4b1353d2b91bd019cbbbcb11

**Issue description:** Godot fails to build with link-time optimization (LTO) enabled, but only when using more than 1 thread.

Fedora 26 build log:

```
[100%] Linking Program        ==> bin/godot.windows.opt.32.exe
/usr/lib/gcc/i686-w64-mingw32/7.2.0/../../../../i686-w64-mingw32/bin/ld: hq2x.windows.opt.32.o (symbol from plugin): warning: No symbol for section '__ZZN4Math9fast_ftoiEfE1b' found
/usr/lib/gcc/i686-w64-mingw32/7.2.0/../../../../i686-w64-mingw32/bin/ld: cannot find -lpthread
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.32.exe] Error 1
scons: building terminated because of errors.
```

Windows (MSYS2) also has an undefined reference on the same file.

**Steps to reproduce:** Build Godot using `scons p=windows tools=yes target=release_debug use_lto=yes -j$(nproc)`.

**Comment by Calinou** [comment]
Note: the `pthread` issue is solved by using `dnf install mingw64-winpthreads-static mingw32-winpthreads-static`. The other issue remains when using more than 1 thread.

**Comment by fcobos** [comment]
Weird...
I just did a clean install of Fedora 26 on a VM and it's working for me.
Tested both 64 and 32 bits builds.
I haven't tested on windows.

**Comment by Calinou** [comment]
I just tested this again, it works on Fedora 27 but not on Windows 10 with MinGW.

Error (with several CPU threads):

```
C:\Users\Hugo\Documents\Git\godotengine\godot>scons p=windows tools=yes target=release_debug use_lto=yes progress=no -j12
scons: Reading SConscript files ...
MSVC not detected (no VCINSTALLDIR environment variable), attempting MinGW.
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.

scons: warning: you do not seem to have the pywin32 extensions installed;
        parallel (-j) builds may not work reliably with open Python files.
File "C:\Apps\SCons\scons-local-3.0.1\SCons\Script\Main.py", line 607, in _scons_internal_warning
scons: Building targets ...
Linking Program        ==> bin\godot.windows.opt.tools.64.exe
progress_finish(["progress_finish"], [])
=====
b'lto-wrapper.exe: fatal error: CreateProcess: No such file or directory\r\ncompilation terminated.\r\nC:/Users/Hugo/scoop/apps/gcc/current/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: lto-wrapper failed\r\ncollect2.exe: error: ld returned 1 exit status\n'
=====
scons: *** [bin\godot.windows.opt.tools.64.exe] Error 1
scons: building terminated because of errors.
```

Success (with one CPU thread):

```
C:\Users\Hugo\Documents\Git\godotengine\godot>scons p=windows tools=yes target=release_debug use_lto=yes progress=no
scons: Reading SConscript files ...
MSVC not detected (no VCINSTALLDIR environment variable), attempting MinGW.
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
Linking Program        ==> bin\godot.windows.opt.tools.64.exe
progress_finish(["progress_finish"], [])
scons: done building targets.
```

**Comment by hpvb** [comment]
It seems Scons is actually giving a warning about this:
```
scons: warning: you do not seem to have the pywin32 extensions installed;
        parallel (-j) builds may not work reliably with open Python files.
```
It appears that 'may not work reliably' in fact means 'not reliably' in Godot's case. Is this a Godot bug?

**Comment by Zireael07** [comment]
Parallel builds on Windows being very wonky is a Scons issue.

**Comment by Calinou** [comment]
I can still reproduce this as of https://github.com/godotengine/godot/commit/5b00cd89d318a92e7970fbdf80d9fca424e15224:

```
C:/Users/Hugo/scoop/apps/gcc/current/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: hq2x.windows.opt.tools.64.o (symbol from plugin): warning: No symbol for section '_ZZN4Math9fast_ftoiEfE1b' found
lto-wrapper.exe: fatal error: CreateProcess: No such file or directory
ompilation terminated.
C:/Users/Hugo/scoop/apps/gcc/current/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
```

**Comment by tinmanjuggernaut** [comment]
Can confirm this issue is present on 791d7f78b w/ mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0

And not just to say #metoo, but I'm experimenting with optimized builds:
`scons.py platform=windows use_mingw=yes target=release tools=no use_lto=yes verbose=yes CCFLAGS="-O3 -march=native" -j12`

I didn't know it was a multithreaded issue, so restarting without the -j12 to finalize the linking is an acceptable workaround for now. Thanks for the info.

I've had zero other issues with multithreaded compiling, so I haven't seen any behavior I would describe as wonky or unreliable on windows/gcc, windows/msvc, or linux/gcc.


_Side note:_ multithreaded compiling with -jN where N = 2x the number of cores gives me much better performance than 1x. I have a 6 core processor and recompiled Godot with everything from -j6 to -j18.  -j12 was the fastest. Anything less than 12 doesn't peg my CPU to 100%. And even at 12, my system is still usable for other tasks. Anything more than 12 doesn't provide any further compiling speed.

**Comment by YRTV** [comment]
Could be related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88422. Is debug information present in godot even when building with `target=release debug_symbols=no`?

**Comment by YRTV** [comment]
-flto=n depends on make see  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90443 in case of scoop `scoop install make` will fix this.

**Comment by Calinou** [comment]
I can confirm installing make using `scoop install make` solves the issue.

@YRTV Thanks for contributing to the documentation :slightly_smiling_face:

**Comment by joaops** [comment]
### Setup:

- [Godot 3.3.2-stable](https://github.com/godotengine/godot/releases/tag/3.3.2-stable)

- Python 3.9.0

- SCons: v4.2.0

- Module [spine-runtime-for-godot](https://github.com/rayxuln/spine-runtime-for-godot), Branch [spine3.8](https://github.com/rayxuln/spine-runtime-for-godot/tree/spine3.8)

### MinGW64 Configuration:
On Windows 10 I installed [WinGW-W64](http://mingw-w64.org/doku.php) `8.1.0` using the `x86_64-posix-seh` file from the Source Forge [page](https://sourceforge.net/projects/mingw-w64/files/)
I just downloaded the zip, extracted it into a folder and set the `Path` Environment Variable by adding the path: `C:/MinGW/MinGW64/bin`.

### Issue description:
When executing the command:
```bash
scons platform=windows use_mingw=yes target=release_debug use_lto=yes -j12
```
Same as above, source code was compiled using 12 threads but failed Linking. If you run the command without the -j12 flag, it worked.

### Solution:
On Windows 10, there is no executable `make.exe`, it is called `mingw32-make.exe` and it is located inside the bin directory of MinGW64 (in my case, inside the directory `C:/MinGW/MinGW64/bin`).
To solve the problem, I simply created a copy of the `mingw32-make.exe` file and renamed it to `make.exe`.
Just by doing that, the command came back to work.
