### ISSUE TITLE
Add support for Android NDK unified headers (Android NDK r15)

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#12514]
More information here:
https://android.googlesource.com/platform/ndk/+/ndk-r15-release/docs/UnifiedHeaders.md

**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS Sierra 10.12.6 (16G29)
Godot v3.0.alpha.custom_build.b8ac700
Android Studio 3.0 Beta 6 (171.4333198)

**Issue description:**
Can't compile Android exporters 

**Steps to reproduce:**
```
$ scons platform=android target=release
scons: Reading SConscript files ...
Building for Android (armv7) (with NEON)
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  3%] Compiling shared ==> platform/android/os_android.cpp
In file included from platform/android/os_android.cpp:30:
In file included from platform/android/os_android.h:33:
In file included from platform/android/audio_driver_jandroid.h:33:
In file included from ./servers/audio_server.h:33:
In file included from core/math/audio_frame.h:33:
In file included from core/typedefs.h:38:
In file included from platform/android/platform_config.h:30:
In file included from /usr/include/alloca.h:27:
/usr/include/sys/cdefs.h:761:2: error: Unsupported architecture
#error Unsupported architecture
...
```

**Comment by akien-mga** [comment]
CC @RandomShaper @volzhs

**Comment by volzhs** [comment]
I'm not sure about this.
I have compiled android templates with ndk r15, r15b, r15c on ubuntu for 2.1.x.
there has been no problem.
I will try master soon or later.

**Comment by rraallvv** [comment]
@volzhs I installed Android NDK directly from Android Studio beta on a clean system installation after installing Xcode and everything. [This patch](https://github.com/rraallvv/godot/commit/5f035a4b84a800673521825b156819dda9740046) solved the issue but since they are planing to add some features to clang to support detecting the headers some of those workarounds won't be needed.

**Comment by rraallvv** [comment]
I have [this branch](https://github.com/rraallvv/godot/commit/9a1d353c0606577aa18a2bfc605165135511eadc) ready for a PR to 2.1, the changes can be seen [here](https://github.com/rraallvv/godot/commit/b8945259ca2b71cd703589c97cb4601762dd1f78).

Maybe someone could give it a try with Android Studio beta, preferably on a clean install.

I'll add a fix for version 3 too.

Also I need to include `malloc.h` in `platform/android/platform_config.h`, I'm not sure why it wasn't included before since `malloc` it's needed everywhere. Maybe a conditional include only for macOS could work too.

Please let me know if you wan't me to change something.
