### ISSUE TITLE
Godot opening/play crashes when a DAW is opened

### ISSUE THREAD

**Issue by Rabocop** [godotengine/godot#12524]
Windows 10 , Asio4all audio server

Godot crashes when a digital audio workstation is open. Surely it's a conflict with the audio devices. It happened with Tracktion 6, with Reaper it runs normally, but it can happen with any other audio software:

Terminal gets me this:
Activated GL 3.3 contextOpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ERROR: init_device: Condition ' hr != ((HRESULT)0x00000000) ' is true. returned: ERR_CANT_OPEN
   At: drivers/wasapi/audio_driver_wasapi.cpp:100
ERROR: init: Condition ' err != OK ' is true. returned: err
   At: drivers/wasapi/audio_driver_wasapi.cpp:155
terminate called after throwing an instance of 'RtAudioError'
  what():  RtApiDs::startStream: error (DirectSound unknown error) starting output buffer!

Steps to reproduce : 
-Open a DAW
-Open or run game in Godot

**Comment by marcelofg55** [comment]
Godot version? This shouldn't happen to latest master.

**Comment by Rabocop** [comment]
Hum...just downloaded the today's build ( http://godot3builds.digitecnology.com/index.php ) and still happening . Also noticed that crashes with Ardour as well

**Comment by eon-s** [comment]
@Rabocop can you check a recent 2.1 build? because uses wasapi too and may be affected by the bug.
