### ISSUE TITLE
StaticBody does not generate mouse signals when its CollisionShape is added at runtime.

### ISSUE THREAD

**Issue by Web-eWorks** [godotengine/godot#12527]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Solus Linux, Godot 2.1.4

**Issue description:**
Static Bodies (and Areas, and anything else deriving from CollisionObject, I think) do not generate `mouse_enter` and `mouse_exit` events when their CollisionShape is added at runtime.

**Steps to reproduce:**
Add a `StaticBody` to the scene. Add a script to it that (in the `_ready()` function) makes a new `CollisionShape`, sets its shape to a new `BoxShape`, and adds the `CollisionShape` to the `StaticBody`. Link the `mouse_enter` signal to a function printing any message, and play with 'Show Collision Shapes'. Move the mouse over the shape outline and observe as no message is printed.

Repeat the same steps manually in the editor (add a `CollisionShape` as a child node, set its shape to a new `BoxShape`) and observe as the message is printed when the mouse is moved into the shape.

This issue does not present itself on Godot 3.0.

**Comment by raymoo** [comment]
CollisionShape is just an editor helper, adding them at runtime has no effect (as you observed).
You have to use some functions in the collidable object to manipulate its collision shape. I'm on my phone though so can't check what the functions are.

**Comment by Web-eWorks** [comment]
Ahh, that was what I was missing.  However, in 3.0, the method I was describing above does work - I would suggest back-porting this feature.

**Comment by kubecz3k** [comment]
In 3.0 collision shapes are no longer only a helpers. Its a breakable change, porting it would destroy existing 2.x projects.

**Comment by kubecz3k** [comment]
All you need to do is use `add_shape` on the body (and push your shape resource as parameter) (if you have shape node than you will get resource with something like `get_node("shape").get_shape()))`
