### ISSUE TITLE
Content View in FileSystem Tab Drawn Incorrectly

### ISSUE THREAD

**Issue by ISylvox** [godotengine/godot#12529]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win 10 Pro x64, 3.0.alpha.custom_build.https://github.com/godotengine/godot/commit/d582cab2079863ce31864ba1382bf955b10ba69c

**Issue description:**

![filesystem scrolling view issue](https://user-images.githubusercontent.com/20697655/32216530-d55dd408-be57-11e7-9a7f-1ece7b2fd9d1.gif)

**Steps to reproduce:**
--> Run the Editor --> Open Platformer 2D demo --> On FileSystem tab, Do Scrolling up or down

**Link to minimal example project:**
-

**Comment by akien-mga** [comment]
@groud ...

**Comment by groud** [comment]
Agree, this seems to be my fault ^^

**Comment by akien-mga** [comment]
Reverting for now as I have a release to make. We can work on a better fix afterwards.
