### ISSUE TITLE
Screenshot in the README.md

### ISSUE THREAD

**Issue by brunurd** [godotengine/godot#12528]
Crazy idea, why not use a editor screenshot image in README.md? like that: 
https://img.itch.zone/aW1hZ2UvMTg4OTU1Lzg4Mzg4NS5qcGc=/original/cURxY8.jpg

I believe it will attrach developers who don't make any idea what is godot and possibly give to the repo some new 'star'.

**Comment by akien-mga** [comment]
Sure, why not.

**Comment by akien-mga** [comment]
Fixed by 91adb58d3de1cb22196203d0184374ff034bf950.
