### ISSUE TITLE
Import sub-scene/merge nodes from scene from outside of res://

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1253]
Hi,

It seems not possible to import sub-scenes from other projects. (I tried to replace `res://` by `c:/` without success)

It would be cool if it was possible, as it would allow having a 'custom database' of scenes that could be easily reused into several projects.

**Comment by mamarilmanson** [comment]
+1

**Comment by akien-mga** [comment]
I guess that would make sense yes, provided you talk about the "Import > Sub-Scene" which copies nodes into the current scene (if you talk about instancing sub-scenes on the other hand, this should stay at the res:// level as the dependency on the scene is kept).

**Comment by akien-mga** [comment]
I've had a look, but it's actually not as simple as it would seem.

Making it possible to access the full filesystem instead of being limited to `res://` is simple:
```
diff --git a/tools/editor/editor_sub_scene.cpp b/tools/editor/editor_sub_scene.cpp
index d32dbcd..30c8e84 100644
--- a/tools/editor/editor_sub_scene.cpp
+++ b/tools/editor/editor_sub_scene.cpp
@@ -231,6 +227,7 @@ EditorSubScene::EditorSubScene() {
        }
 
        file_dialog->set_mode(EditorFileDialog::MODE_OPEN_FILE);
+       file_dialog->set_access(EditorFileDialog::ACCESS_FILESYSTEM);
        add_child(file_dialog);
        file_dialog->connect("file_selected",this,"_path_selected");
```

Which works, but then comes another issue: if you import nodes from an external scene that have dependencies, those get broken, e.g.:
```
ERROR: load_source_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gd_script.cpp:750.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: modules/gdscript/gd_script.cpp:1853.
ERROR: load: Failed loading resource: res://scripts/collectible.gd
   At: core/io/resource_loader.cpp:218.
WARNING: _parse_ext_resource: Couldn't load external resource: res://scripts/collectible.gd
   At: scene/resources/scene_format_text.cpp:122.
ERROR OPENING FILE: res://sprites/pickups/bomb_increase.png
ERROR: load: Failed loading image: res://sprites/pickups/bomb_increase.png
   At: scene/io/resource_format_image.cpp:118.
ERROR: load: Failed loading resource: res://sprites/pickups/bomb_increase.png
   At: core/io/resource_loader.cpp:218.
WARNING: _parse_ext_resource: Couldn't load external resource: res://sprites/pickups/bomb_increase.png
```

So the EditorSubScene would have to be modified a bit more to allow importing dependencies together with nodes... but then where should those be placed? When importing a scene from another project, you don't necessarily want to reuse the exact same structure to put your scripts, textures, and there might even be naming conflicts.

So, I'm no longer sure this is a feature worth working on, as it poses more problems than it solves.

**Comment by SuperUserNameMan** [comment]
Well, since i posted this feature request 552 days ago, i have to admit that i got myself used to work around by copying/pasting/duplicating manually my subscenes ...

If i had to reformulate this feature request today, I think it would be about some sort of local "asset store" where we could store our reusable subscenes (with a copy of their resources) and instance them into the tree like any other node.

**Comment by vnen** [comment]
>  I think it would be about some sort of local "asset store" 

Note that there's an "Import" button in the AssetLib, which can already import ZIP assets from the hard drive.

**Comment by SuperUserNameMan** [comment]
Note : 

Under Windows with NTFS partition, a workaround to reuse scenes/assets/resources from other projects without copying/pasting/importing anything is to create a "[junctions point](https://en.wikipedia.org/wiki/NTFS_junction_point)" (some sort of link to a directory).

Into your main project directory :
``mklink /J <new_sub_directory_name> <path_to_subdirectory_of_external_project>``

If you link to a directory that contains an `engine.cfg` file, the Editor will not let you access its content.
That's why you must link to a subdirectory of an external project.

I've made some tests, and the Project Exporter seems compatible with junction points.

**Comment by akien-mga** [comment]
I think this feature proposal still has some merit, but given its age and the lack of interest from users or contributors, I'll close it for now as old.

Feel free to comment if you think this is a very needed feature, or if you intend to work on it and want to discuss its design, the issue could be reopened.
