### ISSUE TITLE
Regression: Debugger tab contents are rendered outside of its UI 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12532]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2b82997052ad0c37cdae53ecaf2ca9dab85b5244 Ubuntu 17.04

**Issue description:**
![debug_contents](https://user-images.githubusercontent.com/6129594/32220178-17c8f79a-be31-11e7-97fe-2525dbf713e1.png)

**Steps to reproduce:**
1. Create a project which contains non critical errors. 
2. Run it from editor
3. Take a look at errors tab in debugger

**Comment by akien-mga** [comment]
Duplicate of #12529.

**Comment by kubecz3k** [comment]
Ok it seems it was already fixed when I was posting the issue. That's a true bugfix speed :) https://github.com/godotengine/godot/pull/12530 I guess
