### ISSUE TITLE
Arrow keys doesn't select objects on the scene hierarchy 

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#12544]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 Alpha 2, Windows 10 64 bit

**Issue description:**
Arrow keys doesn't select objects on the scene hierarchy, please see this video as reference:
https://youtu.be/lRbefcsYDi4?t=99

Notice how by using the arrow keys doesn't really select the items, only changes the property window information but doesn't have any effect on the viewport.

**Comment by TheSofox** [comment]
Taking a look at this now....

**Comment by TheSofox** [comment]
I have been told "current behavior is fine" and my bug fix pull request that I spent time and effort making has been closed without committing.

**Comment by samvila** [comment]
Wow, that's a real shame @TheSofox , I think the video on the description shows a common workflows expected from users coming from others engines and their possibly disappointment which I think is a great user case in my opinion.

**Comment by Zireael07** [comment]
The PR has been reopened and akien said the behavior is not fine.

**Comment by DualMatrix** [comment]
This seems fixed in master.

**Comment by akien-mga** [comment]
Indeed, this was likely fixed by @Faless' refactor in #16947.

**Comment by akien-mga** [comment]
Reopening as it appears to be specific to some 3D nodes like `Area` or `RigidBody`. Nodes with other gizmos like `ReflectionProbe` are properly highlighted.

CC @JFonS

**Comment by samvila** [comment]
On my tests it fails when the structure is a 3D node and the childs are meshinstances. Just for your reference.

**Comment by KoBeWi** [comment]
This is a bug. When you change nodes using arrows, seems like only the focus changes. There's also `selection_changed` signal sent and for some nodes, the editor will select the element. The selecting seems to happen only for 2D nodes:
![Mhdn4el1lE](https://user-images.githubusercontent.com/2223172/147925233-ff7e24b9-3f4d-4b8b-96b4-422dc546891f.gif)
