### ISSUE TITLE
[2D] ImageTexture (PNG) of 832x3200px appears all black!

### ISSUE THREAD

**Issue by shackra** [godotengine/godot#1254]
Everything was working fine before I compiled the commit 2b22aba39e5dc449ab1f50cd497a1a39358ce84a, but in this commit my large PNG file appears all black. This don't happen with tiny PNG images.

![godot1](https://cloud.githubusercontent.com/assets/1055216/5790878/4028d780-9e74-11e4-884f-9784a51123eb.png)

This may be relevant: I'm using a modified IBM thinkpad T60 laptop.

**Comment by reduz** [comment]
how large was the png?

**Comment by shackra** [comment]
3200px tall:

![godot2](https://cloud.githubusercontent.com/assets/1055216/5790900/4e82371c-9e75-11e4-8be8-5dd66436f195.png)

**Comment by adolson** [comment]
I thought that 2048x2048 was the maximum size or am I mistaken?

**Comment by reduz** [comment]
in mobile, not sure what it is in his hardware.. what's your hardware btw?

**Comment by shackra** [comment]
I have this integrated video card:

```
00:02.0 VGA compatible controller: Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)
```

Juan Linietsky writes:

> in mobile, not sure what it is in his hardware.. what's your hardware btw?
>
> On Sat, Jan 17, 2015 at 5:38 PM, adolson <notifications@github.com> wrote:
>
>> I thought that 2048x2048 was the maximum size or am I mistaken?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/okamstudio/godot/issues/1254#issuecomment-70392791>.
>>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/okamstudio/godot/issues/1254#issuecomment-70392880

-- 
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by shackra** [comment]
is this not a bug but something expected with older hardware? Tiny images show just fine

**Comment by UsernameIsAReservedWord** [comment]
@shackra : under Windows, your GPU must be limited to 2048x2048.
You can use GLviewer to see the OpenGL limitations of your GPU : http://www.realtech-vr.com/glview/download.php

**Comment by shackra** [comment]
Well, I don't use Windows but GNU/Linux...

UsernameIsAReservedWord writes:

> @shackra : under Windows, your GPU must be limited to 2048x2048.
> You can use GLviewer to see the OpenGL limitations of your GPU : http://www.realtech-vr.com/glview/download.php
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/okamstudio/godot/issues/1254#issuecomment-77139769

-- 
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by akien-mga** [comment]
This is likely a hardware limitation so there's not much we can do.
