### ISSUE TITLE
Box Selection doesn't work properly

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#12545]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 Alpha 2, Windows 10 64 bit

Box Selection doesn't work properly, please see this video as a reference:
https://youtu.be/lRbefcsYDi4?t=55

When trying to select object using the box selection functionality on Godot I get some objects selected in the best case, usually I get no objects selected whatsoever.

**Comment by Zylann** [comment]
Related #10979

**Comment by akien-mga** [comment]
Let's close as duplicate of #10979 then, I'll add a link to the video there.
