### ISSUE TITLE
C# project generation crash

### ISSUE THREAD

**Issue by tomascw** [godotengine/godot#12550]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
64bit Ubuntu 17.04, Godot alpha 2 snapshot

**Issue description:**
When trying to create the _first_ C# script for any node in a Godot 3.0, alpha 2 snapshot, project, it crashes at 100% as tries to create the C# project files as well. However, the project and source files are never created. It's also impossible - as far I'm aware - to reopen the project after it crashes without having to restart Godot itself. So far I have only tested this is in newly created projects and not existing ones based on 3.0.

I hope what I said makes sense. Forgive me if this has already been reported. ~~And sorry for the lack of crash logs - I'll get that in ASAP - just thought I'd report it also ASAP.~~

**Steps to reproduce:**
- Create the first C# script in an empty Godot project.

**Comment by tomascw** [comment]
[Debug log](https://pastebin.com/EEwvJADU)

**Comment by akien-mga** [comment]
From the log:
```
Your mono runtime and class libraries are out of sync.
The out of sync library is: /usr/lib/mono/4.5/mscorlib.dll
 
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
 
Your mono runtime and class libraries are out of sync.
The out of sync library is: /usr/lib/mono/4.5/mscorlib.dll
 
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
ERROR: gdmono_MonoLogCallback: Mono: FALTAL ERROR, ABORTING! Logfile: /home/tomascw/.godot/mono/mono_logs/1509507719.txt
 
   At: modules/mono/mono_gd/gd_mono_log.cpp:73.
```
What version of Mono do you have installed?

**Comment by tomascw** [comment]
4.6.2 - I assumed Ubuntu would be up to speed on Mono by now.

**Comment by akien-mga** [comment]
That's too old, you need 5.2 or later. But you're lucky, Mono provides Ubuntu repositories for the latest version: http://www.mono-project.com/download/#download-lin

**Comment by tomascw** [comment]
Thanks. I thought because they only releases up to 16.04 that the 17.x versions were up to date.
