### ISSUE TITLE
Very different light in Editor VS GameView

### ISSUE THREAD

**Issue by MangelMaxime** [godotengine/godot#1255]
In the next screenshot, you will see that the lights result are really different between the editor view and the game view.

I am using a WorldEnvironment and an Omnilight.

![screen shot 2015-01-18 at 01 48 41](https://cloud.githubusercontent.com/assets/4760796/5791003/cdee5298-9eb5-11e4-9e89-fbd60fc11d08.png)

Is this normal ?

**Comment by reduz** [comment]
disable the default light in the 3D editor viewport

**Comment by MangelMaxime** [comment]
Oh. Thanks
