### ISSUE TITLE
Missing functions for binary searches

### ISSUE THREAD

**Issue by poke1024** [godotengine/godot#12558]
I'm missing some function for doing binary searches on arrays in GDScript.

Now, I'd add one, only there needs to be some discussion how and where. Should it be:

(1) a builtin GDScript function like `clamp` and `max`?
(2) an extension of `Array`? But that's a core extension and the core must stay minimal.
(3) some kind of utils package that people can use, like Python's `bisect` package

My personal favorite would be adding a `bisect_left` and `bisect_right` to `Array`.

**Comment by akien-mga** [comment]
I think it should be added to `Array`.

**Comment by poke1024** [comment]
Merged now.
