### ISSUE TITLE
Client crashes when clicking on Project Settings [MSVC only]

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#12551]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Alpha 2, 3.0. Windows 7

**Issue description:**
Create a new blank project, click on Project Settings. Editor crashes

Here are some screenshots:

![image](https://user-images.githubusercontent.com/10387670/32258744-994f2bb6-be79-11e7-87c4-39b554d1bd2e.png)

and

![image](https://user-images.githubusercontent.com/10387670/32258749-a4d2be3a-be79-11e7-880c-e892e4644dd0.png)

Sorry if this has been reported already :P I just got to the alpha now

**Comment by marcelofg55** [comment]
I've just tested with latest master and couldn't reproduce this.

**Comment by Dillybob92** [comment]
@marcelofg55 Thank you. Looks like it's only happening on the alpha build.  Should I close this?

**Comment by Zireael07** [comment]
I am having the same issue on Windows 7 x64 in alpha 2. Didn't see a backtrace, though.

**Comment by Zireael07** [comment]
Update: compiled today's master and can't reproduce this either anymore.

**Comment by Dillybob92** [comment]
@Zireael07 Hmm. I'm on W7 64-bit too, and just compiled today's master and same exact problem is occurring in my screenshot above.

I'm using this scons argument
`scons platform=windows tools=yes target=release_debug -j8`

**Comment by Zireael07** [comment]
The crash seems to be quite random on 9a78efc. I didn't get it yesterday at all only to get it twice in a row today when trying to get into settings.

**Comment by marcelofg55** [comment]
So this is kinda random, did you get a backtrace?

**Comment by Zireael07** [comment]
Nope, as I said I didn't see a backtrace at all (everything just crashed, both the console window and the editor itself, and I can't see anywhere that the backtrace could be saved)

**Comment by Dillybob92** [comment]
@marcelofg55 No stacktrace was really available unfortunately :P, it just error'd out at this line:

https://github.com/godotengine/godot/blob/b279f641c0b9e7af711d857917353905b48c6913/core/vector.h#L137

```

ERROR: Vector<class TreeItem *>::operator []: FATAL: Indexp_index=0 out of size (size()=0)
   At: c:\godot builds\godot-master\core\vector.h:137
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] <couldn't map PC to fn name>
[25] TranslateMessageEx
[26] CallWindowProcW
[27] CallWindowProcW
[28] glDebugEntry
[29] TranslateMessageEx
[30] TranslateMessage
[31] <couldn't map PC to fn name>
[32] <couldn't map PC to fn name>
[33] <couldn't map PC to fn name>
[34] <couldn't map PC to fn name>
[35] <couldn't map PC to fn name>
[36] BaseThreadInitThunk
-- END OF BACKTRACE --
```

If anyone was curious how  I copied that, I used ConsoleZ (as CMD.exe freezes and won't let you copy or do anything)

**Comment by Dillybob92** [comment]
This is unfortunately a inherit compiler issue:

I just tested both under MSVC and MinGW w/ MSYS2. More info [here](https://github.com/godotengine/godot/issues/11391#issuecomment-342866998). Cannot replicate this issue if you use MinGW. This issue only is replicated if compiled with MSVC under Windows.

I recommend everyone to follow this guide https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2 to install MinGW on Windows. Don't need to install VC Tools, or have to open the cmd prompt inside ` Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"` before compiling, etc. Much easier and doesn't throw errors even if you build with -j8.

**Comment by Zireael07** [comment]
I should have MinGW somewhere on my Windows, so how does one use it to build Godot?

**Comment by Dillybob92** [comment]
@Zireael07 

What I did:

- Download 64-bit version http://www.msys2.org/
- Went to C:\msys64 and ran `mingw64.exe`
- Followed steps 2, 3, 4, 5, 6: https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2 
- Then, enter the `godot-master` folder, hold shift+right click -- click open command prompt here, and I used this for scons: `scons platform=windows tools=yes target=release_debug bits=64 -j8`
- I personally then run `strip ./bin/godot.windows.opt.tools.64.exe`

 Hope that helps. We also don't have to worry about -j8 causing the occasional "missing file error" and re-running the command. It's reallly nice

**Comment by akien-mga** [comment]
> I personally then run strip ./bin/godot.windows.opt.tools.64.exe

It would be nice if you could not do that, as it removes all relevant debugging information that you could put in your bug reports when having crashes. You can strip binaries you want to distribute, but when building from git to test and make bug reports, better keep the debug info.

**Comment by Dillybob92** [comment]
<deleted>

Compile however you want, I don't care

**Comment by Zireael07** [comment]
@Dillybob92: removing info about the bug and your helpful comment about how to build Godot with MinGW is just... not cool.

**Comment by Dillybob92** [comment]
Well, obviously it's the wrong way, it's always the wrong way I can never do anything right with Godot it seems. I am removing everything.

**Comment by Zireael07** [comment]
Your mingw comment was very helpful, absolutely not the wrong way.

**Comment by akien-mga** [comment]
What the heck?..

**Comment by akien-mga** [comment]
> Well, obviously it's the wrong way, it's always the wrong way I can never do anything right with Godot it seems. I am removing everything.

Well thanks for wasting our time by mass closing all your issues (most of which were relevant and useful). I don't intend to spend 3 hours reopening them and readding your comments based on my email notifications, so I'll just wait for other contributors to open new issues for the bug that affect them.

I don't know why you freaked out so much just because I told you to avoid stripping binaries of debug info... If you have an issue with something I say, write me an email, don't go berserk editing your issues, mass closing them and deleting your account.

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
