### ISSUE TITLE
New theme button hover and click colours hard to distinguish

### ISSUE THREAD

**Issue by not-surt** [godotengine/godot#1256]
In the new theme the colours for button hover and click are very close and so hard to distinguish, giving poor visual feedback on button click.

**Comment by okamstudio** [comment]
good point, will be working with ndee on improving this the coming weeks

On Sat, Jan 17, 2015 at 5:17 PM, surt <notifications@github.com> wrote:

> In the new theme the colours for button hover and click are very close and
> so hard to distinguish, giving poor visual feedback on button click.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1256>.
>



-- 

*OkamStudio*

**Comment by TheoXD** [comment]
It's also hard to see a difference between input field and unnamed button

**Comment by UsernameIsAReservedWord** [comment]
+1 for not-surt and TheoXD remarks (which makes a total of +2)

**Comment by akien-mga** [comment]
I think this has been fixed, for me the default hover and click visuals are quite different for Buttons.
