### ISSUE TITLE
ability to typecast unknown objects in order to to use autocomplete feature

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#12562]
Nodes from outside the scope of the current scene are not known  by the script editor so autocomplete will not work . The scripts however will work when running the game.

See the following image
![image](https://user-images.githubusercontent.com/6987027/32285979-6755faa2-bf02-11e7-8c13-bc349ec373fb.png)

My script is accessing the camera node from outside the scope of the current scene. When running the script will work but when writing the script the Script Editor will not know the camera variant is a Camera object so autocomplete feature will fail. I need to tell it to turn it into a Camera object by casting it. 

I did not find anything regarding casting in the Godot 3.0 docs so I assume this is not a feature that is currently implemented or perhaps not desired.  I could not find any other issues that were similar although I may be wrong here too. 

I am asking for the ability to type cast objects so the autocomplete feature works for unknown object types as well by telling the editor what object it is.

In the example above  this should turn the camera variant into a Camera object making autocomplete functional

var camera
camera = (Camera)get_node("/root/main/player/camera")
camera.rotation_deg

or 

((Camera)camera).rotation_deg

Obviously this type of casting should not work for objects that are known or found and should not work for converting a variant type into another variant type or objects into other objects. SO perhaps is more like telling the editor what the unknown/not found object is rather than casting.

Could be something like [Object] or {Object} so is not confused with type casting in typed languages I am not sure. 

I leave it up to you to decide if is a feature that is desired or not.

**Comment by Zylann** [comment]
I remember there was a similar issue with input events, where autocompletion cannot guess the type of what you are getting, unless the following code structure is found:

```gdscript
# Completion not available
if event is InputEventMouseButton:
    # Completion available
    print(event.position)
```

Not exactly what you ask, but does a similar job. I don't remember which issue it is though...

**Comment by trollworkout** [comment]
@Zylann  I will try this. Thank you for sharing.  If this method works it should pretty much do what I am asking and no casting required. 

In my case it should be more like

```
if node is Camera 
  ....
```

Should I close this?

**Comment by icnikerazah** [comment]
The solution of the problem mentioned by Zylann should be clearly explained in the documents.
I spent 15 minutes trying to find this. Does event have a position variable?
```gdscript
if (event is InputEventMouseButton and event.is_pressed():
    # Completion not available
    print(event.position)
```

```gdscript
if (event is InputEventMouseButton):
    # Completion available
    print(event.position)
```

**Comment by Zylann** [comment]
@icnikerazah you probably found an issue about completion, because your first `if` has two checks. Maybe the smart auto-complete doesn't get past composed expressions.
