### ISSUE TITLE
Selecting multiple files in the FileSystem dock is slow the more files you select

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#12576]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/79f81b77e2160fd4fb490b9e8e05636de70174bf

**Issue description:**

Selecting multiple files in the FileSystem dock is slow the more files you select. And the file type also seems to be an issue.

Videos:
[*.gltf and *.material](https://streamable.com/ehgrv)
[*.png](https://streamable.com/tri4q)

I didn't try to select all the *.gltf and *.material because it basically freezes the editor.

**Steps to reproduce:**
1. Select multiple files in the filesystem dock
2. Stare at the screen

**Link to minimal example project:**

[test.zip](https://github.com/godotengine/godot/files/1436539/test.zip)
Tiles and models from https://kenney.nl/

**Comment by akien-mga** [comment]
Confirmed. Just to rule out a potential recent regression, I've tried with a revert of 2aef4ce0fe and the bug still happens.

**Comment by volzhs** [comment]
this seems to be related to import panel.
