### ISSUE TITLE
Undefined behaviour bug in GDNative string API function `godot_string_get_data`

### ISSUE THREAD

**Issue by Evrey** [godotengine/godot#12574]
https://github.com/godotengine/godot/blob/93a3d1714ee9b1535ac8f902bd7b2b3135712b90/modules/gdnative/gdnative/string.cpp#L66-L74

`p_size` is not checked against `nullptr` again, after assigning the string's current length to it. This code will do horrible things if called like this:

```c++
godot_string_get_data(&my_gdstring, &my_buf, nullptr);
```

Should be this instead:

```c++
void GDAPI godot_string_get_data(const godot_string *p_self, char *p_dest, int *p_size) {
    String *self = (String *)p_self;
    int len = self->utf8().length();

    if (p_size != NULL) {
        *p_size = len;
    }
    if (p_dest != NULL) {
        memcpy(p_dest, self->utf8().get_data(), len);
    }
}
```

It would also be nice to have some documentation indicating that the length of the buffer behind `p_dest` is *not* checked and that `p_size` is solely used to return the string's length. At least I would have assumed that `p_size` takes the buffer length when calling this function and receives the actual string length after returning.

In that sense, an alternative implementation might be to use `p_size` on entry as the buffer length. Fail if the buffer is too small, otherwise fill it and override `p_size` with the string's length. Come to think about it... why not take `p_size` as an `int` and return the string's size instead? However, this is very different from what this implementation tries to accomplish.

The main point of this issue is fixing that bug.

**Comment by karroffel** [comment]
on my TODO
