### ISSUE TITLE
Inverted light colors in alpha2

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#12579]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win7 x64
Radeon HD 6630M (ATI Catalyst drivers)

**Issue description:**
The light colors are inverted (white gives black light, black gives white light etc.)

https://i.imgur.com/RUrWdm2.gifv

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by mrcdk** [comment]
Are you sure you don't have the light Negative property enabled?

**Comment by Zireael07** [comment]
Fairly sure.

Ticking the negative property makes light go back to... almost normal.

https://i.imgur.com/QuucTxP.jpg

Note the color of the light on the buildings! It's unnegated.

Also this is almost the same shot with shadows off: https://i.imgur.com/qJkqioi.jpg

Note the buildings lost the shadow (to be expected) but the fugly ground color patches are revealed to be shadow. (Changing shadow color only appears to affect the shadow on the buildings, not the ground shadow)

**Comment by Zireael07** [comment]
I will try to provide a minimum project today, as it seems it's something to do with ambient light. Trying to nail down what is happening.

**Comment by Zireael07** [comment]
Update: can't reproduce on a fresh project from scratch. I will export a fresh project from 2.1.4 to see if it's the exporter at fault, or the fact that I opened a project originally exported from 2.1.4 to 3.0alpha 1. I'm really hoping it's NOT the exporter...

**Comment by Zireael07** [comment]
Can't reproduce in a project freshly exported from 2.1.4 to 3.0 alpha 2, so closing.

Guess it'll teach me not to copy projects from alpha 1 to alpha 2.
