### ISSUE TITLE
[Build] Editor help generation fails if .DS_Store file is present in doc/classes/

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#12584]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS (any version), master branch 

**Issue description:**
If `.DS_Store` file is present in `doc/classes` (`.DS_Store` stores extended attributes, it is created when directory is accessed by the Finder), `make_doc_header` fails to generate valid documentation and all descriptions in editor help are missing. No errors are displayed during build.

**Steps to reproduce:**

1. Open `doc/classes/` in Finder.
2. Build Godot.

**Comment by reduz** [comment]
look for DocData::load_classes function, and I guess just ignore anything not a class

**Comment by mhilbrunner** [comment]
Should be fixed by #12731. Can you test this @bruvzg?

`DocData::load_classes` as mentioned above shouldn't be at fault as it already checks if the path ends with `.xml`.

**Comment by bruvzg** [comment]
@mhilbrunner #12731 works, but wouldn't it be better to use `endswith('.xml')` to match `load_classes`?

**Comment by mhilbrunner** [comment]
You're right. I updated it to check for '.xml' instead. :)
