### ISSUE TITLE
Better documentation for MultiMeshInstance

### ISSUE THREAD

**Issue by abhaskumarsinha** [godotengine/godot#12582]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

How to use multi mesh instance to generate a large number of straight and upright tree spraid randomly.....?
**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Zylann** [comment]
See QA https://godotengine.org/qa/19366/how-to-use-multimeshinstance?show=19395#a19395

**Comment by abhaskumarsinha** [comment]
@zylann I want to do that in my editor of 2.1.4 stable. Anyways your method does't works

**Comment by Zylann** [comment]
@abhaskumarsinha I tested it and works for me, though there is an issue about it https://github.com/godotengine/godot/issues/12595

But I agree there should be something in editor to place the instances, currently there isn't even inspector properties

**Comment by ZX-WT** [comment]
Am I misunderstanding something here, isn't that what the populate surface option for? The button next to view in the editor.

**Comment by Zylann** [comment]
@ZX-WT oh... indeed there is that. Needs documentation I guess.

**Comment by akien-mga** [comment]
PR welcome to improve https://github.com/godotengine/godot/blob/master/doc/classes/MultiMeshInstance.xml

**Comment by KoBeWi** [comment]
There's a [tutorial linked there](http://docs.godotengine.org/en/latest/classes/class_multimeshinstance.html#tutorials) now. Does it solve this issue?

**Comment by clayjohn** [comment]
I would say so. All those docs and tutorials have been added since this issue was created.
