### ISSUE TITLE
Viewport "Disable Input" property not working

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#12581]
On godot 3.0 alpha 2 on linux64 (ubuntu 16.04)

- Create a simple project with a Viewport
- Enable "Disable Input" property for the viewport
- Run an see the input propagate to the child nodes of the viewport :'-(

![image](https://user-images.githubusercontent.com/3187637/32321619-ff8c0fd6-bfc1-11e7-954f-d6e2202b9296.png)

**Comment by akien-mga** [comment]
Maybe it's meant to disable input in `_gui_input(event)` and not in `_process(delta)`?

**Comment by touilleMan** [comment]
Well first `_gui_input(event)` seems to do nothing, I have to use `_input(event)`... (not sure if it's a naming convention failure... I think to remember it used to be called `_input_event(event)` back in Godot 2)

Second, the `_input(event)` is processed fine when the node belongs to the root viewport, and not at all when in a sub viewport (no matter if the "Disable Input" property is set or not)

**Comment by eska014** [comment]
The `Input` singleton has no notion of viewports, it just reports input state as reported by the OS.
Disabling input for a viewport will simply not propagate InputEvents to it and its children per callbacks.

**Comment by touilleMan** [comment]
@eska014 thanks a lot for pointing this out. So my trouble initial issue is solved ("it's not a bug, it a feature !" ^^).
However remains the second test I did with `_input()` function not beeing called if it part of a node within a viewport.

**Comment by reduz** [comment]
This is not a bug, the viewport will not get any input called unless it's the root viewport or child of a ViewportContainer.
