### ISSUE TITLE
InputEvent cannot be created from GDscript

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#12580]
Using Godot 3 alpha 2 on linux64 (ubuntu 16.04).
Having a script with:
```gdscript
var event = InputEvent()
```
Cause a crash with error `Invalid call. Nonexistant function "InputEvent()" in base 'Node (Node.gd)'.`
Same thing with any type of `InputEvent` like `InputEventKey` for instance.

**Comment by eska014** [comment]
InputEvents are no longer built-in types, so use `InputEventKey.new()`

**Comment by akien-mga** [comment]
Indeed, that's a feature(tm).
