### ISSUE TITLE
Unresponsive buttons and parts of the interface hidden in a HiDPi screen

### ISSUE THREAD

**Issue by Samitier** [godotengine/godot#12594]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Windows 10
Godot v2.1.4
Intel HD Graphics 520

**Issue description:**

I have a laptop with a HiDPi screen (1080p in a 13 inch screen).

I open godot engine, and the top part of the interface is missing. The buttons do not react to the correct position of the mouse and the interface is completely unusable.

I tried disabling the "display scaling on high DPI devices" in the executable, resizing the godot window, setting the scaling of the laptop down to 100%, changing the resolution of the laptop, but nothing seems to work.

**Steps to reproduce:**

Open godot engine.

**Screenshots of the problem**

<img width="544" alt="captura" src="https://user-images.githubusercontent.com/4160121/32346838-075f5acc-c00f-11e7-9fe3-70e9312ea3d1.PNG">
<img width="529" alt="captura" src="https://user-images.githubusercontent.com/4160121/32347098-e08bf4ea-c00f-11e7-8d1b-57fe3119d684.PNG">

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by Samitier** [comment]
Hi @akien-mga. It is happening exactly the same in RC1, there are parts of the interface that are not showing and the mouse coordinates inside the screen are moved, which makes clicking buttons impossible. Here's a screenshot:

![image](https://user-images.githubusercontent.com/4160121/34967053-50787eec-fa60-11e7-9315-c451641990e4.png)

In my case it is only affecting in this particular laptop (Dell XPS 13), every other pc I tried works perfectly.

**Comment by eon-s** [comment]
Looks like #8902 , try with the driver version mentioned in that issue.

**Comment by Samitier** [comment]
That was it! It is working perfectly with the latest drivers. Thanks a lot guys!
