### ISSUE TITLE
GL context errors on OpenGL 3.3-able hardware [Windows 7, Radeon HD 3650 and 3200]

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#12596]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[![3 0](https://user-images.githubusercontent.com/10380658/32355427-78a90b26-c026-11e7-87ee-95d44c06e0d4.png)](url)

**Issue description:**
I just uploaded Godot Alfa2 Win x64 and tried running, demo projects, it happens everywhere! The simplest 3D projects, such as the (GUI in 3D). are imported about 15 minutes. and then load about 10 minutes look nightmarish, and do not react either. And projects as a (platformer 3D) even worse they are just starting and freezing. A demonstration of new (materials TESTER) does not load at all, even can not be imported in the editor. 3d scenes are terribly slow if you add at least one 3D object.

**Steps to reproduce:**
In the first snapshot, the indicators taken from the (OpenGL Extensions Viewer) in the morning are what happens when you start (project manager). On the third of what happens when I try to run a demo project - (Material Tester). on the fourth already running demo project (platformer 3d).

[![3 0](https://user-images.githubusercontent.com/10380658/32355755-9a4a8712-c028-11e7-9ff5-7d2a7663a4ea.png)](url)

[![3 0](https://user-images.githubusercontent.com/10380658/32355777-c1a8be82-c028-11e7-8084-cb5a10f28125.png)](url)

[![3 0](https://user-images.githubusercontent.com/10380658/32355787-d1c36ba0-c028-11e7-8c41-5a4aea5986de.png)](url)

**Link to minimal example project:**
Official demo projects.

**Comment by eon-s** [comment]
#9027 was "solved" at some point then?

**Comment by OlexiyKravchuk** [comment]
@eon-s 
No. they said that they would not solve such a problem, because they will not support Vista. It's really very sad, but I can not influence this decision in any way.

**Comment by reduz** [comment]
I may have some of this hardware to test, need to set up in one of the computers..

**Comment by brainsick** [comment]
I believe that #14861 is probably related.  I get many of the same errors.

**Comment by reduz** [comment]
I will not get test hardware to test this before 3.0, so moving to 3.1 unless anyone wants to give it a try

**Comment by brainsick** [comment]
If you just need someone to test, I can do so.  If you want remote access to the box, we can arrange something; it's just sitting idle.

**Comment by reduz** [comment]
Kicking to 3.2, where it will probably be closed, given this hardware does not support Vulkan and will likely have to use the GLES2 backend.

**Comment by spikestheraccon** [comment]
Well, I have same issue on my radeon hd 4650. It will be fixed on 3.2?

**Comment by Calinou** [comment]
@spikestheraccon The GLES3 renderer is no longer really maintained, so you'll have to switch to the GLES2 renderer. (Your graphics card doesn't support Vulkan, so the Vulkan renderer in Godot 4.0 won't be an option.)

**Comment by spikestheraccon** [comment]
> 
> 
> @spikestheraccon The GLES3 renderer is no longer really maintained, so you'll have to switch to the GLES2 renderer. (Your graphics card doesn't support Vulkan, so the Vulkan renderer in Godot 4.0 won't be an option.)

On GLES2 Godot gives me same errors. Projects still opening and lauching on GLES2 and GLES3, but much slower than on linux.
![изображение](https://user-images.githubusercontent.com/56189267/66255441-df5f7400-e79c-11e9-9d46-fd2f3133bb2b.png)

**Comment by Calinou** [comment]
@spikestheraccon Do you get the same errors when using a binary compiled from the `master` branch or using a [daily build](https://hugo.pro/projects/godot-builds/)?

**Comment by spikestheraccon** [comment]
> 
> 
> @spikestheraccon Do you get the same errors when using a binary compiled from the `master` branch or using a [daily build](https://hugo.pro/projects/godot-builds/)?

 I use Stable 3.1.1

**Comment by Calinou** [comment]
@spikestheraccon I wanted to know whether this was fixed in more recent versions :slightly_smiling_face:

**Comment by spikestheraccon** [comment]
> 
> 
> @spikestheraccon I'd like to know whether this is fixed in more recent pre-release versions 🙂

So, I tried to open my project on last build and errors on GLES2 is gone. But it still running and launching slowly, and I think there is another bug on the console. I also tried to disable 3d editor(my project is 2d), but result is same.
![изображение](https://user-images.githubusercontent.com/56189267/66256577-a4633d80-e7a8-11e9-9897-b8be9acdc1ad.png)

**Comment by Calinou** [comment]
> But it still running and launching slowly

Unfortunately, this is kind of expected on such an old, low-end GPU :slightly_frowning_face: 

You can speed up rendering in 2D projects by setting **Rendering > Quality > Intended Usage > Framebuffer Allocation** to **2D** in the Project Settings. Also, try removing the `default_env.tres` file from your project – this will remove the default environment, which is mostly used in 3D only.

> and I think there is another bug on the console

This is unrelated to the rendering issue. It was introduced by the overflow checks added in #31513, which exposed some underlying issues in the editor.

**Comment by akien-mga** [comment]
I'll close this issue because we're unlikely to be able to fix issues for those old GPUs. The Windows drivers are notoriously bad for those cards and while they claim OpenGL 3.3 support, the above shows that they even struggle with OpenGL 2.1.

If you have one of these cards, your best shot is to use the GLES2 version of Godot, and if that's not working well enough, try Linux as the Mesa drivers should have much better support for this hardware.

**Comment by OlexiyKravchuk** [comment]
Since raising this issue, Godot has received many fixes. and the GLES2 moment in 3.2. beta 2 works with almost the same efficiency as on versions 2.1.5, which I used before.
But GLES3, although it started to run better than before, but even on a more powerful computer, still too raw for comfortable working with it, it literally turned out to be utterly useless for me.
