### ISSUE TITLE
Godot 3.0 Alpha 2 GLES continuous errors

### ISSUE THREAD

**Issue by MarcosRRM** [godotengine/godot#12609]
## Operating system or device, Godot version, GPU Model and driver (if graphics related):
Win 7 Ultimate 64
i5-4210U @ 1.7 GNz
8GB DDR3
820M 2GB (most recent driver to this issue creation date)
Godot 3.0 Alpha 2 win 64, no mono version

## Issue description:

When using Godot 3.0 Alpha 2 on my laptop I get a lot of errors related to GLES. It happens every time the app has to update, being changing a button outline color when hovering the mouse over or, when inside the editor, just moving the view around. But every time I get this stream of error, the app stops for about a second or so, rendering it unusable.

![godoterror](https://user-images.githubusercontent.com/30786247/32376307-93c7bb9a-c08b-11e7-980c-d212c90829df.png)

So I remembered that I could output the log to a file through the cmd, and so I did. I opened throught cmd, outputed to a log text file, opened the app and then a clear scene, moved the 3D view around a little and closed.
To my surprise tho, when opening through this method **the engine didn't lag AT ALL**. but still outputed a bunch of errors to the log file, here it is:

[log.txt](https://github.com/godotengine/godot/files/1441222/log.txt)

I wish I'd know C++ to help fix the error, but bug reporting is all I can do for now.

**Comment by OlexiyKravchuk** [comment]
https://github.com/godotengine/godot/issues/12596#issuecomment-341710029

**Comment by MarcosRRM** [comment]
The problem was solved(somehow) on the build I got today(11/6/17) on http://godot3builds.digitecnology.com/

**Comment by MarcosRRM** [comment]
Ok, I will reopen this because I finally discovered the root(sort of) the problem, and it's called Rivatuner Statistics! Whenever it's open and I try to open Godot it goes like the OP!

**Comment by reduz** [comment]
This is probably unrelated to Godot, and likely a driver problem or something. The GL commands shown in that window are not even used by Godot, it seems they are sent from another application which is really weird. I will close this though.
