### ISSUE TITLE
Cannot find MSBuild executable on Arch Linux

### ISSUE THREAD

**Issue by TeddyDD** [godotengine/godot#12613]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Arch 64bit, Godot 8e145fa1a80bcd860dd8e16d7db684f9905865e8

**Issue description:**
Scons fails to build Godot with `module_mono_enabled=yes`
```
scons p=x11 tools=yes module_mono_enabled=yes mono_glue=no -j 4
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[  0%] mono_build_solution(["bin/GodotSharpTools.dll"], ["modules/mono/editor/GodotSharpTools/GodotSharpTools.sln"])
[  7%] Compiling ==> main/tests/test_gui.cpp
[  7%] Compiling ==> main/tests/test_gdscript.cpp
[  7%] scons: *** [bin/GodotSharpTools.dll] RuntimeError : Cannot find MSBuild executable
Compiling ==> main/tests/test_oa_hash_map.cpp
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/SCons/Action.py", line 1197, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/home/teddy/Kod/godot/modules/mono/SCsub", line 160, in mono_build_solution
    raise RuntimeError('Cannot find MSBuild executable')
RuntimeError: Cannot find MSBuild executable
scons: building terminated because of errors.

```
I have mono and msbuild installed. 
```
whereis msbuild.exe                                                                                                          pią, 3 lis 2017, 
msbuild: /usr/bin/msbuild.exe /usr/share/msbuild
```
**Steps to reproduce:**
- install `msbuild-bin` from AUR
- scons p=x11 tools=yes module_mono_enabled=yes mono_glue=no -j 4

## AUR issue. Workaround
` sudo ln -s /usr/bin/msbuild.exe /usr/bin/msbuild  `

**Comment by akien-mga** [comment]
Make a bug report on AUR against `msbuild-bin`, they should provide `/usr/bin/msbuild`. A symlink to their `/usr/bin/msbuild.exe` shell script should do the trick, or just rename that shell script since I'm not sure what the point is to have it with a .exe extension.

**Comment by TeddyDD** [comment]
As I thought. I wasn't sure if this is AUR or Godot thing. 
I'd leave this open until AUR issue is resolved but you can close it if you want.

**Comment by akien-mga** [comment]
Well I guess we could add a fallback `msbuild.exe` search in the PATH. @neikeq WDYT?

**Comment by neikeq** [comment]
@akien-mga Yes, I guess that's fine.

**Comment by novemberist** [comment]
btw, feel free to join the discussion on https://aur.archlinux.org/packages/godot-git/ to improve how the godot-git package (with mono-support) and some of its apparently orphaned dependencies should be built. there are currently some issues on ArchLinux including an outdated version of mono on the official repos and an outdated version of msbuild-15-bin on the aur.
