### ISSUE TITLE
Cannot use get_script() to make nested static function calls

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#12617]
Godot 3.0
Windows 10

What happened:
I tried to do the following:

    static func a():
        return 1
    
    static func b():
        return 1 + get_script().a()

This fails because get_script() returns null when I expected it to return the script.
Attempting to use a preloaded constant won't work as it expects me to use get_script() if accessing the same script.
I would also have accepted being able to just call a() directly from within b(), but that doesn't work since it then thinks I'm trying to access the nonexistent 'self'.

**Steps to reproduce:**
Attempt to call static function from another static function where both functions belong to the same script.

**Comment by mrcdk** [comment]
Which commit? I just tested on 25c38c75425e3ccfcaed53ebd38fc588d6f35764 and it's working correctly

`get_script()` won't work on a static function because it's not static

**Comment by akien-mga** [comment]
> `get_script()` won't work in a static function because it's not static

Not a bug then, just use `a()`.

**Comment by willnationsdev** [comment]
This should still be a bug as far as I am aware. You cannot directly call a() either, hence the need for something to use. The only thing I have found to work is loading (not preloading) the exact same file within itself.

**Comment by akien-mga** [comment]
Well, @mrcdk said that this works just fine:
```
static func a():
    return 1

static func b():
    return 1 + a()
```
