### ISSUE TITLE
Put the completion tooltip under the edited line

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1261]
Hi,

It happens frequently that the previous line of code contains information that I need to write the new line, but I can't see it because the tooltip hides it.

So, it would be cool if the tooltip was displayed UNDER the line being written.

**Comment by reduz** [comment]
problem is that below it the autocompletion appears
maybe it could be made transparent?

**Comment by UsernameIsAReservedWord** [comment]
as the autocompletion box appears a shorter time than the tooltip, maybe the autocompletion box could be displayed over the tooltip, and both under the the line ?

if not possible, or not usable, transparent tooltip sounds ok.

**Comment by UsernameIsAReservedWord** [comment]
ps : and if transparent tooltip looks ugly, then, I'll adapt myself and play with the Escape key since the tooltip reappears when I resume typing.

**Comment by akien-mga** [comment]
Also related. #1257

**Comment by nunodonato** [comment]
how about having the tooltip after the cursor?

**Comment by satscape** [comment]
+1 Having the tooltip under the line you're typing would be lovely, as this > http://i.imgur.com/u2BXq7L.png is really annoying :-)
If the tooltip is long, there might not be room to the left/right?

**Comment by KioriSun** [comment]
"Code completion should be showed bellow the line", all the cool people are doing it ;) :
![completion](https://cloud.githubusercontent.com/assets/10463922/13146211/c2abfbec-d63b-11e5-8bfe-bfddc3ab56eb.png)

This is from latest VS btw.

**Comment by akien-mga** [comment]
Well code completion *is* shown below the line. AFAIK the problem is the tooltip hint that tells you what are the argument names and types for the function you are writing.

**Comment by KioriSun** [comment]
Yes, but this illustrated it better i think. In VS its all the same:
![tooltip](https://cloud.githubusercontent.com/assets/10463922/13146451/0a5b6eb8-d63d-11e5-84b5-f9edd5ef098e.png)

**Comment by chuckeles** [comment]
I would love to fix this, but I can't find any relevant code... Any idea where to look?

**Comment by reduz** [comment]
scene/gui/text_edit.cpp

remember also that there is a calltip popup besides the completion tooltip
which should go somewhere

**Comment by chuckeles** [comment]
How about this?

![it1](https://cloud.githubusercontent.com/assets/4700122/13506599/25643c24-e17f-11e5-8277-15631f7f9c67.png)

**Comment by reduz** [comment]
so you mean that tooltip will only appear on positions like:

print(<here>
print(somearg,<here>

etc?

and while you are writing an identifier, it will complete the identifier?

If this works I'm cool with it, can you guys test it?

**Comment by chuckeles** [comment]
Exactly

![hint1](https://cloud.githubusercontent.com/assets/4700122/13507330/6ba95a90-e182-11e5-9adc-7a5fe6660c41.png)
![hint2](https://cloud.githubusercontent.com/assets/4700122/13507328/6ba31aa4-e182-11e5-9876-24fa6bd8acfe.png)
![hint3](https://cloud.githubusercontent.com/assets/4700122/13507329/6ba40aae-e182-11e5-904c-e6931b9d7d6b.png)

**Comment by chuckeles** [comment]
The only real issue is that you can't explicitly show the hint (say with CTRL+SHIFT+SPACE as in the Visual Studio) once it's lost.

**Comment by reduz** [comment]
makes sense to me, if everyone else feels this change is for the better
let's merge it.

**Comment by akien-mga** [comment]
Looks good to me :)

**Comment by reduz** [comment]
oh ok, we can add that

**Comment by reduz** [comment]
let's wait for any objection and if nothing comes up then merge it i guess
