### ISSUE TITLE
setting tile NavigationPolygon by code doesnt work

### ISSUE THREAD

**Issue by rilpires** [godotengine/godot#12626]
Godot 2.14

If I use tile_set_navigation_polygon( tile_id , nav_poly ) it never works properly.

Even if it is a preloaded NavigationPolygon resource!

![image](https://user-images.githubusercontent.com/12648211/32403025-9d053650-c118-11e7-8d18-62e14b384831.png)

In this case, the Navigation2D doesn't works properly (I setted a simple scene with _draw to render the points)

Now if I set the tile navigation polygon by editor using the same navpoly I saved with ResourceSaver("res://nav.tres" ) it works fine, the _draw render the points properly.

Maybe It has something to do with Navigation2D pre compute stuff when parent of a Tilemap?

**Comment by rilpires** [comment]
Also, even if set the navigation polygon by the editor and use

`tile_set_navigation_polygon(0,null)
`
the Navigation2D still works, and using remote inspector I can see that the tileset still has a NavigationPolygon attached to tile 0.

**Comment by rilpires** [comment]
The scene I wrote that code
[tilemap_nav.zip](https://github.com/godotengine/godot/files/1443004/tilemap_nav.zip)

**Comment by Zireael07** [comment]
Probably related, I haven't been able to find a configuration in which the bake button actually results in a navmesh.

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by EvilPyro** [comment]
@akien-mga not sure but it didn't work in 3.1 and it doesn't work as of today's latest master branch. (3.2)

**Comment by tom-jk** [comment]
This appears to be working in 3.2.2.stable.

Here is a minimal project that includes an expansion of the script in the first post: [12626.zip](https://github.com/godotengine/godot/files/4925982/12626.zip)

![Godot12626_Screen](https://user-images.githubusercontent.com/64640811/87560816-c254bb80-c6b3-11ea-84a1-ccbaf5ef9629.png)

The script in the project makes navigation polygons of different shapes for different tiles (to check that they aren't all just sharing one or something). It also shows how the vertices around the edge of tiles must align to allow finding paths between them, and how the found paths can be a bit jank, but those are seperate issues.

Below is a simpler script which just makes square navigation for tiles:

```gdscript
extends Node2D

var navpoly = NavigationPolygon
var vertices = PoolVector2Array()

onready var tilemap = get_node("Navigation2D/TileMap")

func _ready():
	vertices.push_back(Vector2( 0,  0))
	vertices.push_back(Vector2( 0, 32))
	vertices.push_back(Vector2(32, 32))
	vertices.push_back(Vector2(32,  0))
	
	navpoly = NavigationPolygon.new()
	navpoly.add_outline(vertices)
	navpoly.make_polygons_from_outlines()
	
	#print(ResourceSaver.save("res://nav.tres", navpoly, 0 ))
	
	var tileset = tilemap.tile_set
	
	for t in tileset.get_tiles_ids().size():
		tileset.tile_set_navigation_polygon(t, navpoly)
		
		# nothing shows up until have done this, even though should
		# be a no-op (setting itself to what it already is)?
		tileset.tile_set_region(t, tileset.tile_get_region(t))
```

Note the comment at the end there - I guess _that_ is a bug.

**Comment by akien-mga** [comment]
Thanks for testing and the in-depth example! Closing.
