### ISSUE TITLE
Compositing/Blending in Godot darkens partially transparent areas

### ISSUE THREAD

**Issue by simon-budig** [godotengine/godot#12629]
This is on Linux Debian unstable, Intel graphics:
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.4
OpenGL core profile shading language version string: 4.50

Using a daily build of Godot (from yesterday):
$ ./godot-v3.0-x11.64 --version
3.0.alpha.custom_build.c880302

I am trying to seamlessly blend two images on top of each other, tweaking the facial expression in a photograph. For that I am compositing a partially transparent PNG (created in GIMP) on top of a base sprite. The top layer has partially transparent areas, that get rendered with a prominent darkening in Godot.

At first I assumed that it somewhat is related to premultiplied alpha, but that doesn't seem to be the case: toggeling the premultiplied-alpha button only makes matters worse.

I have attached a minimal sample project.

[testcase.zip](https://github.com/godotengine/godot/files/1443164/testcase.zip)

This is how it is supposed to look like (compositing from GIMP):
![sample-compositing-in-gimp](https://user-images.githubusercontent.com/8409200/32404853-90d33918-c159-11e7-9307-45b6a7f530cb.png)

and this is how it looks like in Godot:
![sample-compositing-in-godot](https://user-images.githubusercontent.com/8409200/32404856-9bbcad14-c159-11e7-9507-6c05dc033bb8.png)

Any help would be greatly appreciated.

**Comment by reduz** [comment]
This is normal, the way to fix it is importing your images as premultiplied
alpha and then set the blend mode to that.

**Comment by simon-budig** [comment]
Ok, I am clearly missing something. I have applied https://github.com/maxme/PNG-Alpha-Premultiplier to the PNG in question and reimported it, with the "premultiplied" toggle set.

That made matters worse.

Premultiplying by definition makes the pixel values darker. Since the effect with the un-premultiplied version of the PNG alreads a darkening (in different strength depending on the premul-toggle) I don't see how actually premultiplying the pixel values in the PNG is supposed to help.

**Comment by reduz** [comment]
you don't need to do this, just check the import options of the image where you can set a checkbox to make it premultiplied alpha on import.

The sprite or whathever you are using needs a special material with this blend mode enabled. Just add a CanvasItemMaterial to the node and set blend mode to premultiplied.

**Comment by simon-budig** [comment]
Ok, I was missing that I need a Material definition for the sprite before the blend mode becomes available.

Ok, thanks for the help.
