### ISSUE TITLE
mouse_exited signals when hovered over another control inside its Rect

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#12624]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0, w7 64-bit

 
For example:
> mouse_exited() Emitted when the mouse **leaves the control's Rect area**.

However, in the example linked below, the signal is called even if you hover over a control that is inside its Rect2. That shouldn't be happening, right?  Maybe am missing something ^^

**Link to minimal example project:**

[mouse_exited_bug.zip](https://github.com/godotengine/godot/files/1442832/mouse_exited_bug.zip)

**Comment by Dillybob92** [comment]
So, I'm not really a C++ expert (only javascript dev here w/ nodejs )

I decided to dive into the code a bit more because I mean, I do use the engine a lot. But would much rather have the professionals take a whack at it. 

However, I think the culprit relies somewhere here:

https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1880

I think it's calling `mouse_exited` whenever the `gui.mouse_over` is true and if it's hovering over a new control compared to the last one? Except it's not taking into account the bounding Rect2? Not entirely

**Comment by akien-mga** [comment]
Note: The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
