### ISSUE TITLE
Can't open Project Manager if run with -e

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#12623]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64, Master 25c38c7

**Issue description:**

Expected: Project Manager open when clicking the respective menu option.
Happened: It quits.

**Steps to reproduce:**
~~1. Go to project root, run Godot with `godot -e`
2. Choose "Quit to Project Manager"~~

1. Create a .sh that `cd` to the project root and `godot -e`
2. Execute it by double-click on the icon
3. Choose "Quit to Project Manager"

edit: forgot to mention that it's shell script.

**Comment by akien-mga** [comment]
Can't reproduce it on Mageia 6 with c8803027543, so if it's a regression it's quite recent.

**Comment by Noshyaar** [comment]
My mistake. I updated the reproduction steps.

**Comment by akien-mga** [comment]
What's in your shell script?

**Comment by Noshyaar** [comment]
```

**Comment by akien-mga** [comment]
Try with:
```
#!/bin/sh

cd ~/path/to/project
godot -e "$@"
```

**Comment by Noshyaar** [comment]
It still closes.

**Comment by akien-mga** [comment]
Still can't reproduce with this script:
```
$ cat ~/test.sh 
#!/bin/sh

cd tmp/godot/v3_test1
godot-git -e "$@"
```
Whether starting it using the script from the command line, or by double-clicking it in Dolphin, I can get back to the project manager without any issue.

**Comment by Noshyaar** [comment]
This is how it looks for me. I'm using Cinnamon, Nemo, and gnome-terminal.
![img](https://user-images.githubusercontent.com/26753932/32410755-e2752cda-c1fa-11e7-9c96-25ae66d578ba.gif)

**Comment by akien-mga** [comment]
Well that's probably a Cinnamon/Nemo specific issue, the "Run in Terminal" feature you use is probably meant to kill the terminal when the process exits. Not much we can do to prevent that.

**Comment by Noshyaar** [comment]
It's just me then. It's not really critical for me. If anyone else finds it breaking their workflow, feel free to comment here or open a new issue.
