### ISSUE TITLE
Can't click on clickable anchors inside the documentation

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#12625]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/7715a261d5f387b7769bb8149735e4131ea97757

**Issue description:**

![https://i.imgur.com/U6ijuIt.gifv](https://i.imgur.com/U6ijuIt.gif)
It seems to only happen inside the Members and Public Methods blocks
This doesn't happen in Godot 3.0 alpha2 so it must be something new

**Steps to reproduce:**
1. Open some documentation
2. Try to click any anchor inside Members or Public Methods

**Comment by poke1024** [comment]
Can't reproduce this with a current 08e6590fd625bc3b592b7398ec2825f3758ab6e8 build.

**Comment by volzhs** [comment]
I couldn't reproduce it neither 640856f

**Comment by mrcdk** [comment]
Yep, seems some commit fixed it. Closing this issue then.
