### ISSUE TITLE
Crash in shader_graph_editor_plugin.cpp during editor launching.

### ISSUE THREAD

**Issue by quabug** [godotengine/godot#1263]
Crashed [here](https://github.com/okamstudio/godot/blob/master/tools/editor/plugins/shader_graph_editor_plugin.cpp#L1409)

Because of ShaderGraphEditor::node_names is not updated since more enum values were added into ShaderGraphic::NodeType.

And I suggest to modify this piece of code like [this](https://github.com/quabug/godot/commit/197749f9770fd5494dd8f2f8e7a7e11acb1c26b4), which avoid(warn, at least) further mistake by slightly increase CPU usage during construct a new instance of ShaderGraphEditor. This modification is more a code style changing rather than a bug fixing, so I will not pull this patch to master branch until you guys approve it(or you can modify it by yourself).

**Comment by okamstudio** [comment]
working on it, didn' t realize it was broken when pushed

On Sun, Jan 18, 2015 at 1:37 PM, quabug <notifications@github.com> wrote:

> Crashed here
> <https://github.com/okamstudio/godot/blob/master/tools/editor/plugins/shader_graph_editor_plugin.cpp#L1409>
>
> Because of ShaderGraphEditor::node_names is not updated since more enum
> values were added into ShaderGraphic::NodeType.
>
> And I suggest to modify this piece of code like this
> <https://github.com/quabug/godot/commit/197749f9770fd5494dd8f2f8e7a7e11acb1c26b4>,
> which avoid(warn, at least) further mistake by slightly increase CPU usage
> during construct a new instance of ShaderGraphEditor. This modification is
> more a code style rather than a bug fixing, so I will not pull this patch
> to master branch until you guys approve it(or you can modify it by
> yourself).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1263>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment]
Assuming this has been fixed.
