### ISSUE TITLE
Tons of "note: see reference to function template instantiation" when building [scons +vs2015]

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#12654]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win 7 x64

**Issue description:**
Compiling with scons gets pretty slow due to tons of that note printed to console.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
Log excerpts would be useful. We can't do anything about a note without any code reference.

**Comment by volzhs** [comment]
yeap. printing logs on windows terminal is terrible by the way.

**Comment by Zireael07** [comment]
Most if not all of the notes referred to bind_method function.

I closed the terminal once it finished building, so I have no way of telling you what exactly it printed without rebuilding again.

**Comment by volzhs** [comment]
so, I switched to linux as my main OS after I met Godot. yeah~
