### ISSUE TITLE
Improve DynamicFont outlines by using 8 shadows instead of 4

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#12655]
The DynamicFont's outline (which is enabled when "Shadow as Outline" is set to a non-zero value on a Label node) could be improved. Right now, it only uses 4 shadows, which makes it look mediocre when used with wider outlines (even as low as 2 pixels).

Here's a quality comparison (in Serious Sam 3, which allows you to change the font outline thickness and quality):

**High quality:**

![font_outline_high_quality](https://user-images.githubusercontent.com/180032/32415052-48f8b6c4-c233-11e7-80c9-57d43d680376.png)

**Low quality:**

![font_outline_low_quality](https://user-images.githubusercontent.com/180032/32415053-491bb408-c233-11e7-909a-50c951aa8645.png)

Notice the "gaps" around the corners of glyphs.

Here's some screenshots (also from Serious Sam 3) with the outline thickness set to a very high value, so you can see how it works:

**Low quality:**

![font_outline_huge_low_quality](https://user-images.githubusercontent.com/180032/32415060-7f907f64-c233-11e7-8345-e0dd52bd7dfe.png)

**High quality:**

![font_outline_huge_high_quality](https://user-images.githubusercontent.com/180032/32415061-7fb5696e-c233-11e7-92e5-7f609f66feb5.png)

**Comment by volzhs** [comment]
I like the result but this seems to drop performance.
I used outline (even it uses 4 shadows to make outline) label on mobile, and I found performance issue.
so I avoid using outline as possible now.

**Comment by Zylann** [comment]
Can't we bake outlines to avoid drawing the text 8 times more?

**Comment by volzhs** [comment]
I not expert about this but I found something related outline with freetype.
https://stackoverflow.com/questions/20874056/draw-text-outline-with-freetype
does this improve outline quality maybe? because we are using freetype for dynamic font.

**Comment by viktor-ferenczi** [comment]
Adding the following shader material to the label node renders something similar:

```
shader_type canvas_item;

uniform vec4 outline_color : hint_color;
uniform float border_width = 2.0;

void fragment() {
	vec2 ps = TEXTURE_PIXEL_SIZE;	
	float dx = ps.x*border_width;
	float dy = ps.y*border_width;
	float zz = 0.0;
	float h = 0.70711; // sqrt(2) / 2
	float a = (
		texture(TEXTURE, UV + vec2(dx, zz)).a +
		texture(TEXTURE, UV + vec2(-dx, zz)).a +
		texture(TEXTURE, UV + vec2(zz, dy)).a +
		texture(TEXTURE, UV + vec2(zz, -dy)).a +
		texture(TEXTURE, UV + vec2(dx*h, dy*h)).a +
		texture(TEXTURE, UV + vec2(-dx*h, dy*h)).a +
		texture(TEXTURE, UV + vec2(dx*h, -dy*h)).a +
		texture(TEXTURE, UV + vec2(-dy*h, -dy*h)).a);
	vec4 texel = texture(TEXTURE, UV);
	a = max(0.0, a - 7.0);
	texel.r = min(a, texel.r);
	texel.g = min(a, texel.g);
	texel.b = min(a, texel.b);
	float alpha = texel.a;	
	texel = mix(outline_color, texel, a);
	texel.a = alpha;
	COLOR = texel;
}
```

Please bear with me, this was the very first shader I wrote. It could be done better, likely.

**Comment by Calinou** [comment]
I'm closing this issue since https://github.com/godotengine/godot/commit/5cd12f6649387f91d08fd17bf3c70e732798ab58 was recently merged into the `master` branch. (FreeType-based outlines look and perform better than *ad hoc* outlines created using several shadows.)
