### ISSUE TITLE
Dangling pointer bug in `godot_string_cstr`

### ISSUE THREAD

**Issue by Evrey** [godotengine/godot#12650]
https://github.com/godotengine/godot/blob/a89fa34c21103430b1d140ee04c3ae6a433d77ce/modules/gdnative/gdnative/string.cpp#L95-L98

What happens here is this call chain:

- `godot_string_cstr`
- [`auto String::utf8() const -> CharString`](https://github.com/godotengine/godot/blob/a89fa34c21103430b1d140ee04c3ae6a433d77ce/core/ustring.cpp#L1409-L1488)
- [`auto CharString::get_data() const -> *const char`](https://github.com/godotengine/godot/blob/a89fa34c21103430b1d140ee04c3ae6a433d77ce/core/ustring.cpp#L89-L95)
- `return`
- `CharString::~CharString()`
- [`Vector<char>::~Vector()`](https://github.com/godotengine/godot/blob/a89fa34c21103430b1d140ee04c3ae6a433d77ce/core/vector.h#L422-L426)
- [`void Vector<char>::_unref(void*)`](https://github.com/godotengine/godot/blob/master/core/vector.h#L188-L210) <== Memory deleted here, because `CharString` went out of scope and only had a ref count of 1.

So, `String` parses its UTF-32 data into a UTF-8 buffer, returns a pointer to the UTF-8 buffer's data, and as the function `godot_string_cstr` returns, that buffer is deleted, resulting in a dangling pointer.

I currently see only four solutions to that bug, one being less elegant than the previous one:

- Cache the created `CharString`, which keeps the reference count above 1. The problem with this is that the created UTF-8 data will be kept until the corresponding `String` dies, increasing memory consumption by a bit. Shouldn't be a huge problem, though, unless someone `godot_string_cstr`s mebibytes of text all the time. After all, UTF-8 data is on average only 1/4th to 1/2th the size of UTF-32 data.
- `memcpy` the buffer into one that the user has to de-allocate himself with a call to `godot_free`. `memcpy` cannot be avoided here, instead of just stealing a `Vector<T>`'s `_ptr`, as `godot_free` doesn't have the boolean flag for de-allocating ref counted buffers.
- Remove that function entirely *(We don't want that to happen, do we?)*
- Expose `CharString` to GDNative *(I don't think that we want that, either)*

**Comment by akien-mga** [comment]
cc @karroffel

**Comment by karroffel** [comment]
Yes, that is indeed a problem... The cleanest solution would be to have a small API for CharString to call the destructor manually.

Option 1: don't like that really.
Option 2: You can already do that using `godot_string_get_data`
Option 3: Wouldn't mind that as it's basically just doing the same as `godot_string_get_data` but with RAII on top of it
Option 4: We could do a small subset just enough to destroy and get pointer. But I don't think it's worth it.

So all in all I'm for removing that function entirely. The CharString just allocates memory for the UTF-8 data and then hands you the pointer. You can easily just allocate it yourself by using `godot_string_get_data`, so I'd just remove it completely.

**Comment by Evrey** [comment]
Sounds good to me.
