### ISSUE TITLE
ScrollContainer adds extra space beyond bounds of child

### ISSUE THREAD

**Issue by AaronWizard** [godotengine/godot#12666]
Godot 2.1.4.stable.official
Mac OS X 10.10.5

When I have a ScrollContainer with a child container, the ScrollContainer will add more space to the left or bottom of the child than is necessary.

![screen shot 2017-11-05 at 1 09 45 pm](https://user-images.githubusercontent.com/33398493/32417116-ad51af44-c22a-11e7-9495-0aac7a66fb24.png)
![screen shot 2017-11-05 at 1 09 52 pm](https://user-images.githubusercontent.com/33398493/32417117-afa02938-c22a-11e7-90ba-73a8bef3cde7.png)

I suspect this extra space would be used by the other currently hidden scroll bar.

**Steps to reproduce:**

* Add a PanelContainer to the scene, and resize it as necessary
* Add a ScrollContainer to the PanelContainer
* Add a VBoxContainer to the ScrollContainer
* Add multiple Buttons to the VBoxContainer until there are more buttons than may be visible
* When running the scene, you will see extra space to the bottom of the buttons when you scroll down in the panel

**Link to minimal example project:**

[ScrollContainerSpace.zip](https://github.com/godotengine/godot/files/1444254/ScrollContainerSpace.zip)

**Comment by groud** [comment]
This looks still valid on master.
