### ISSUE TITLE
Bullet seems to ignore constraint softness

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#12663]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot build 9a78efc, Linux 64

**Issue description:**

For the G6DOF Joint the softness parameter seems to be ignored for both angular and linear constraints preventing the creation of elastic joints.

**Steps to reproduce:**
Create 2 rigid bodies (one static) and a G6DOF. Join the bodies with the joint and set all the softness parameters to 0.01. Try and switch between Bullet and The original GD Physics Engine.

**Link to minimal example project:**

https://www.dropbox.com/s/tds110ejxlkj6wi/bullet_test_softness.zip?dl=0

**Comment by akien-mga** [comment]
cc @AndreaCatania

**Comment by AndreaCatania** [comment]
Hi @m4nu3lf, I was testing it but your project zip is void. Can you please fix it?

**Comment by m4nu3lf** [comment]
@AndreaCatania Sorry, Can you try now?

**Comment by m4nu3lf** [comment]
After some investigation now I can tell that bullet is not using the `m_limitSoftness` parameter.
Not anymore at least. It seems that m_limitSoftness is only used in dead code. This is also true for `m_maxForceLimit`.
You can still use the m_stopCFM or m_normalCFM parameters that seems to act exactly like `m_limitSoftness` but in reverse (0= max stiffness, 1 = no stiffness). The actual difference between normalCFM and stopCFM is not clear to me yet.
Also note that these CFM and the ERP related parameters despite being public must be set trough the setParam() method on the constraint or they will be overwritten by the global values.
Unfortunately it seems to me that there is no m_maxForceLimit equivalent for the current version of Bullet, which surprises me

**Comment by reduz** [comment]
You can try askin @ErwinCoumans but I have the feelinf this is related to abandoning the sequential impulse solver

**Comment by erwincoumans** [comment]
First, I suggest moving to use btGeneric6DofSpring2Constraint. Then try reproducing it in the Bullet example browser and file an issue in http://github.com/bulletphysics/bullet3 (there is an existing example for constraints)

@reduz We didn't abandon the sequential impulse solver at all: even btMultiBody uses it for contacts, constraint limits etc. When you want higher quality joints for articulated characters, robots etc, it is worth using btMultiBody.

**Comment by m4nu3lf** [comment]
@erwincoumans Is it possible to use it to create very stiff constraints?

**Comment by erwincoumans** [comment]
btMultiBody has perfectly stiff joints (hinge, slider). btGeneric6DofSpring2Constraint joints can also very stiff: you need to be carefull using enough solver iterations etc. Again, I cannot start supporting godot users, unless you find a bug: then first recreate it in the Bullet as in my previous comment. Thanks!

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by erwincoumans** [comment]
@AndreaCatania I strongly suggest to use btGeneric6DofSpring2Constraint, I consider removing the btGeneric6DofSpringConstraint and btGeneric6DofConstraint from Bullet. With some tuning of solver iterations and avoid large mass ratios, the btGeneric6DofSpring2Constraint should be able to solve stiff joints. Again, for perfect stiff joints, btMultiBody is the way to go, but that will take some effort to add to Godot, in case someone is interested doing so.

**Comment by AndreaCatania** [comment]
Yes I did it

**Comment by akien-mga** [comment]
Closing as fixed then.
