### ISSUE TITLE
Add button to close the output panel

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#12665]
Since adding a bunch of use cases and options to automatically open/close the output panel would be overkill, it'd be handy to have a button to close the output panel instead.

For instance if one is not interested in all the output but only errors and warnings, that option could be added too, but there will be always a situation when one needs to close the output panel for whatever reason despite having errors, warnings and whatnot.

**Comment by akien-mga** [comment]
I think this was improved recently, what's the status in 3.0 RC1?

**Comment by rraallvv** [comment]
@akien-mga I updated to the latest build (05b1843818fd07f084816ec506ec505e24f8f02c) and the panels at the bottom look and feel so much better now. Maybe we could add those to the View menu too and add the Close button at the bottom where the toolbar is, or next to the Clear button. Something like this:
![Imgur](https://i.imgur.com/L0CiSBN.png)

**Comment by akien-mga** [comment]
Those panels are based on the context (node selected in the SceneTree), and it would be pretty weird to put them in the View menu of the 3D viewport, as it's fully unrelated.

But there's no need to put them anywhere; a "Close" button should just unroll the panel, just like when you press on the tab itself - but then it would do the same as pressing on the tab, so I'm not sure if it's useful at all.

**Comment by rraallvv** [comment]
@akien-mga I see, it's just that since other IDEs allow to get rid of the negative space for some toolbars by allowing to close them, I was thinking a button to close the tool bar at the bottom could do the same thing for the Godot UI. But now I'm of the opinion that we can get away with having that negative space, thanks to minimalistic approach in the UI for Godot.

I'm going to close this issue now, but feel free to open it maybe to support smaller screen sizes or something like that.

**Comment by rraallvv** [comment]
Just in case anyone is interested in the difference between non-minimalistic vs minimalistic design  in UI check out [this blog post](https://uxplanet.org/lean-and-mean-power-of-minimalism-in-ui-design-5ca37eb32ac8)
