### ISSUE TITLE
Sound does not play when exporting a project (Windows/Linux)

### ISSUE THREAD

**Issue by zorgsoft** [godotengine/godot#12667]
**Linux Mint 18.2 x64/Windows 10 x64, Godot 3.0 alpha 2**

**Sound does not play when exporting a project:**
When exporting a project for Linux or WIndows, sound / sound files are not played.

Checked the export under Linux Mint 18.2 and Windows 10.
Exported projects do not work, there are no errors.

Work in 2D mode, used both AudioStreamPlayer and AudioStreamPlayer2D.

In the Godot editor, everything works fine, the sound is there and working.

I'm trying to play ordinary wav files.

**Steps to reproduce:**
Add to the project AudioStreamPlayer, make an event to play the sound file, work in the editor, then do the export.

**Link to minimal example project:**
[Example project](https://github.com/zorgsoft/Breakout-z)

**Comment by zorgsoft** [comment]
Hi again, are there any changes? I would like to start using the third version but without working sound when exporting I can not start the project.

**Comment by reduz** [comment]
@m4nu3lf think you could give a check to this?

**Comment by zorgsoft** [comment]
It seems that in version 3.0-beta everything worked. Checked in Windows 10, Linux Mint 18.3.

But maybe it's just me, when AudioStreamPlayer or AudioStreamPlayer2D is bound to the root node, it does not work. If attached to any other object, then everything works fine.

**Comment by m4nu3lf** [comment]
@reduz I'll give a check, but I have zero familiarity with the Godot Sound server so far. Let's see what I can do

**Comment by m4nu3lf** [comment]
@zorgsoft I can't load the example project. I get and 'unexpected end of file' error when loading the main scene. Can you check if this is still and issue? I can't reproduce it on my project

**Comment by akien-mga** [comment]
The example project provided is for 2.1.4, so indeed it can't be used to showcase a potential bug in 3.0... Since @m4nu3lf couldn't reproduce it and @zorgsoft hints that it seems to work in 3.0-beta, let's close.
