### ISSUE TITLE
Godot Should Take Advantage of Indexed Color Images

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#12669]
I am working on NES style games that feature low color graphics. I would like my games to take advantage of the benefits of [indexed color images](https://en.wikipedia.org/wiki/Indexed_color). I this in Godot's roadmap?

**Comment by Calinou** [comment]
Modern hardware and rendering APIs don't reason in indexed colors anymore, so I'm not sure what this is supposed to mean. If this is about palette swapping, see #12670. I'll close this issue for the time being.

PS: Godot is already able to import PNGs with indexed colors (which can be generated using tools like [oxipng](https://github.com/shssoichiro/oxipng)).
