### ISSUE TITLE
Allow AnimationPlayer To Be Put On a Separate Window

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#12677]
The AnimationPlayer would benefit from having more space. Can we make it occupy its own window by itself?

**Comment by ArisKallergis** [comment]
I think it is better to use the Q&A for questions. https://godotengine.org/qa/

**Comment by Boothand** [comment]
It's a usability issue though in my opinion. It's way too small for anything other than very simple animation graphs.

**Comment by ArisKallergis** [comment]
I'm saying this because davidpgil opened about 6 issues in a row, most of which are questions (at least in their title).

**Comment by davidpgil** [comment]
I am asking these questions so they can spur issues that need resolving. Shall I change the wording and titles of my posts so they appear as suggestions or requests? I can do that. All of these issues I posted come from my post-mortem notes of a project I already completed.

**Comment by eon-s** [comment]
Currently Godot do not support separate windows. 
You can do live editing with the scene running, though.

And try to add more details to your idea, like a mockup of how it may look better since animation player may be modified on future versions, a single line does not say much.

**Comment by davidpgil** [comment]
@eon-s , yes I know Godot doesn't support this yet. This is why I am requesting it. Right now the only interface support allows reorganizing of the windows with the intention to occupy one screen. Right now, software like Adobe After Effects, Maya, etc already allows to make UI elements to be "tirn off" so their window can exist independently of the main interface window. If that isn't an obvious enough description, I can surely take the time to illustrate it with a mockup. @eon-s would you be the one implementing this in code?

**Comment by eon-s** [comment]
No, I try to not break things around here :p 
But after 3.0 the animation player may be renewed or with more options, I'm sure some ideas will be welcome by those who work on the UI part of the engine.

**Comment by davidpgil** [comment]
If someone asks for a detailed example of what this will look like I will do it. I know of the animation overhaul coming in 3.1 ... I think my suggestions would be more useful after the 3.0 release.

**Comment by KoBeWi** [comment]
Closing in favor of related proposal: https://github.com/godotengine/godot-proposals/issues/28
