### ISSUE TITLE
Project Manager spits errors after deleting projects

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#1267]
If a project has moved or been deleted from disk, launching the Project Manager will spit this out:

ERROR: _load_recent_projects:  Condition ' err!=OK ' is true. Continuing..:
At:  tools/editor/project_manager.cpp:523

It's a hassle to clear out old projects that don't exist anymore from the editor_settings.xml file, due to the XML saver's complete lack of sorting, but this is the only way (Editor Settings doesn't seem to allow removal there, either). This is another case where a more friendly format (OpenDDL-based) would be called for. See also #1167.

Ideally, old projects that no longer exist on disk should be removed automatically from the editor_settings.xml file, along with the recently-opened scenes stuff. I see no really compelling reason to hang onto it. And the errors might scare or confuse newbies, too.

**Comment by akien-mga** [comment]
Fixed by #2640.
