### ISSUE TITLE
Physics process performance

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#12671]
#**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
9a78efc7c270211e49fd7b2f071b61c706febffc

**Issue description:**

Physics process time is higher with bullet than with godot i could think that its because bullets is more complex, but still, i only have one kinematic character in the scene with some raycasts and areas no more that 10 of them combined, and static bodies, and the monitors show this:

bullet:
![screenshot from 2017-11-05 12-34-33](https://user-images.githubusercontent.com/1103897/32418046-46a109d6-c228-11e7-94c5-15354b3f86d1.png)

godot:
![screenshot from 2017-11-05 12-30-34](https://user-images.githubusercontent.com/1103897/32418052-4af73b18-c228-11e7-8bb9-8a6df3e44a6d.png)

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Noshyaar** [comment]
Btw, the commit hash is invalid?

**Comment by djrm** [comment]
oh sorry i pasted my version hash

**Comment by akien-mga** [comment]
cc @AndreaCatania @reduz

**Comment by Zireael07** [comment]
Confirming that I'm seeing 2-3 less fps with Bullet than with Godot physics in 9a78efc

**Comment by nhydock** [comment]
How does the performance scale?  I could see this being an acceptable drop if the performance degrades significantly less than Godot's physics at higher loads.

**Comment by AndreaCatania** [comment]
This is an interesting discussion, however I didn't setup Godot profiling on bullet, so these that could be not 100% correct

I'll check it soon

**Comment by djrm** [comment]
this seems to be fixed now

godot
![screenshot from 2017-11-22 18-55-49](https://user-images.githubusercontent.com/1103897/33155533-e3e34970-cfb6-11e7-9056-96e000c0c0c6.png)

bullet
![screenshot from 2017-11-22 18-58-15](https://user-images.githubusercontent.com/1103897/33155576-2946f944-cfb7-11e7-9bc7-490fac4ea905.png)
