### ISSUE TITLE
Implement Palette Swap Effect Tool In Godot

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#12670]
I am working on NES style games that feature low color graphics. I would like my games to take advantage of palette based effects such as palette swapping. [This is an example](https://gamedev.stackexchange.com/questions/43294/creating-a-retro-style-palette-swapping-effect-in-opengl) Is this on Godot's roadmap?

This is also a [GDC talk](https://www.youtube.com/watch?v=aMcJ1Jvtef0&feature=share) where the Mark Ferrari of Monkey Island fame discusses why palette based animation/swapping is so awesome and needs to be still exist.

**Comment by KoBeWi** [comment]
There's already a related proposal: https://github.com/godotengine/godot-proposals/issues/429
