### ISSUE TITLE
Allow Godot To Make Animation Values That Interpolate With Whole Numbers or Integers

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#12674]
I want to create a NES style game that uses only integer values for all transformations (position, rotation, scale, tweening). I would also  like this to be represented in the GUI as well. Is this on Godot's roadmap?

**Comment by kubecz3k** [comment]
Something different than discrete mode for animation track? https://i.imgur.com/7IDzLLU.png

**Comment by davidpgil** [comment]
I have be able to animate frame by frame by keying the frame I want to display.  have never used the animation modes before. I am guessing Discrete/Continuous modes are for motion curves during animation transformations.

I want the actual values calculated to not produce decimal/floating point values at all. I believe I have been able to do this using GDScript but for some reason, in the GUI, still appears as a decimal/floating point number. Which makes me believe it wasn’t actually converted to an integer.

**Comment by kubecz3k** [comment]
As far as I know you should just use discrete mode to achieve what you want.

**Comment by davidpgil** [comment]
I’ll check it out today and let you know if it does what I want it to do. To clarify, in the NES days, no animation was done using flosting point values. My goal is to replicate that look.

**Comment by davidpgil** [comment]
... Actually it's almost 5 am where I am, but I decided to have a quick look. No, `discrete` does not do what I want. I want to be able to benefit from transformation interpolation, but I want the interpolated frames to be only integer based and fall on a whole pixel. `continuous` mode allows for some pixels to not fall on a whole pixel.

I want to make my game pixel-perfect. I have seen games that don't do what I am asking and it creates a high resolution look that does not match the NES-like games that I want to create.

**Comment by Faless** [comment]
I second this.
It would be useful when animating GUI elements as, at least in my case, the animation shake when interpolating margins like `0 -> 150 --[time pass]--> 150 -> 0` due to floating point error.

**Comment by KoBeWi** [comment]
What about pixel snap? It makes float positions irrelevant.

**Comment by KoBeWi** [comment]
Another ghosted issue 👻👻
If someone still wants this, make a new proposal on the [official proposals repository](https://github.com/godotengine/godot-proposals/).
