### ISSUE TITLE
Add Chroma-Key or "Green Screen" Keying-Out of a Color Range

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#12676]
The idea is to be able to use green screen footage in a game. The user would select a range of colors to be considered transparent. I understand this is probably doable via shaders. I am suggesting this a feature in Godot, since it is a media industry standard workflow.

I found an example of someones [implementation](https://www.youtube.com/watch?v=lTmvkf_Ydzs) of this in Godot, but I think it should be a built-in feature.

**Comment by GiveMeAnthony** [comment]
Since this is achievable with shaders, it might be better to simply implement a shader preset library of commonly used shaders (such as chroma key).

**Comment by davidpgil** [comment]
@GiveMeAnthony yes basically I am asking for a UI menu or something very similar that will apply this "Chroma-Key" shader. Like I said, its a very common industry standard thing that gets done in and outside of gaming. This should be built in. For myself, I did this with coding a little shader.

**Comment by KoBeWi** [comment]
We are moving proposals to [official Godot proposals repository](https://github.com/godotengine/godot-proposals), so closing this. The OP is a 👻, but if someone is interested in this feature, make a new proposal over there.

**Comment by BenLore** [comment]
That is a very interesting idea I think! However, I think it will take a lot of effort to make something so good in the game, such as these videos https://greenscreenstock.com/, that they can then be edited.
