### ISSUE TITLE
AnimationPlayer Time line Size Hard To See

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#12673]
The AnimationPlayer time line is gray. The length of the animation is indicated by a slightly reddish gray hue. The contrast of these two colors needs to be increased for visibility. I can barely see the difference. If you would like me to suggest a color, I am glad to do so.

**Comment by djrm** [comment]
godot version?

**Comment by davidpgil** [comment]
I am using version 2.1.4 stable.

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by supragya** [comment]
![deepinscreenshot_hexchat_20180222194710](https://user-images.githubusercontent.com/24278306/36543274-4ed3e452-1809-11e8-98da-42c9e152f119.png)
Seems differentiable to me, should it be closed?

**Comment by vnen** [comment]
In 3.0 it's much better, but still a problem in 2.1.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
