### ISSUE TITLE
Bullet cast_motion missing null check

### ISSUE THREAD

**Issue by muiroc** [godotengine/godot#12683]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot 9a78efc7c270211e49fd7b2f071b61c706febffc

**Issue description:**
Crash when calling PhysicsDirectSpaceState::cast_motion with Bullet backend
This only happens when a collision occurs

BulletPhysicsDirectSpaceState::cast_motion is missing a null check before writing to the parameter r_info

The write occurs inside the block "if (btResult.hasHit()) { ... }"

**Steps to reproduce:**
- Empty project, add StaticBody with any CollisionShape
- Move the shape vertically under the XZ plane
- Attach this script to any node:
func _ready():
	var sphere = SphereShape.new()
	sphere.radius = 1.0
	var ps = PhysicsShapeQueryParameters.new()
	ps.set_shape(sphere)
	var ds = get_world().get_direct_space_state()
	ds.cast_motion(ps, Vector3(0,-10000,0))
- Run project

ps:
Great work and congratulations on the merged PR!

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by AndreaCatania** [comment]
Fixed: https://github.com/godotengine/godot/pull/13046
