### ISSUE TITLE
Feature proposal - Navie stock based fluid simulator

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#12680]
Ok, I try to describe what I really wanted to see in Godot - a navie-stock based fluid simulator realized on shaders (for 2D first) and the core of suggestion is implementation of Fluid2D node and VectorField2D(for particles). This will make possibility to create photorealistic flame and smoke effects.

I cannot write such a complex thing(I not even have a math graduate), but Im experimenting with ready solutions from the internet, based on CPU(without shaders). I also read(dont remember where) that its possible to implement on GPU without latest opengl(or compute shaders). 
here is my flamethrower demo video - https://www.youtube.com/watch?v=6G9LkXIWBVI
the algorithm behind it(using SFML lib) - https://github.com/Chaosus/Fluid2D

base description -
 http://www.dgp.utoronto.ca/~stam/reality/Talks/FluidsTalk/FluidsTalkNotes.pdf

PS I dont know about UE but Unity have this as paid user-maked extension. - https://www.assetstore.unity3d.com/en/#!/content/33564 How cool if Godot will have it from box, Unity will suck a ball. This may refresh the view of many Godot games, especially on desktop..

**Comment by Chaosus** [comment]
If @reduz commented about this it would be awesome..

**Comment by reduz** [comment]
I don't think it's a good idea simply for the fact it's not a very common case. 
Still, this is what we have GDNative for, you guys can do it and put it on the asset library for anyone to use, that would be ideal
