### ISSUE TITLE
M_PI undeclared identifier

### ISSUE THREAD

**Issue by bitbionic** [godotengine/godot#12688]
Windows 10 64-bit, Godot 3 (master), VS 2017

**Issue description:**
I just setup a new Windows 10 computer with VS 2017, and all the build tools for Godot per http://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html

When trying to compile I receive the following error:
```

drivers\gles3\rasterizer_scene_gles3.cpp(2542): error C2065: 'M_PI': undeclared identifier
drivers\gles3\rasterizer_scene_gles3.cpp(2543): error C2065: 'M_PI': undeclared identifier
drivers\gles3\rasterizer_scene_gles3.cpp(2544): error C2065: 'M_PI': undeclared identifier
drivers\gles3\rasterizer_scene_gles3.cpp(2682): error C2065: 'M_PI': undeclared identifier
drivers\gles3\rasterizer_scene_gles3.cpp(2683): error C2065: 'M_PI': undeclared identifier
drivers\gles3\rasterizer_scene_gles3.cpp(2684): error C2065: 'M_PI': undeclared identifier
drivers\gles3\rasterizer_scene_gles3.cpp(2768): error C2065: 'M_PI': undeclared identifier
drivers\gles3\rasterizer_scene_gles3.cpp(2769): error C2065: 'M_PI': undeclared identifier
drivers\gles3\rasterizer_scene_gles3.cpp(2770): error C2065: 'M_PI': undeclared identifier
scons: *** [drivers\gles3\rasterizer_scene_gles3.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

I was able to mitigate the issue by placing the following code within rasterizer_scene_gles3.cpp and complete the build. I will commit to a branch and open a pull request.

```

#ifndef M_PI
#define M_PI (3.14159265358979323846)
#endif
```

**Comment by ISylvox** [comment]
Just compiling Godot master using Win 10 x64 + VS2015, works great and no issue so far.

**Comment by ISylvox** [comment]
Just compiling Godot master on Win 10 x64 using VS2015, works great and no issue so far.

**Comment by bitbionic** [comment]
idk - maybe it's a VS2017 issue? I had both installed on my old windows box and didn't run into this, but on this one, it's a fresh install of everything and I ran into the errors.

**Comment by ISylvox** [comment]
Not sure if it's a VS2017 issue, I don't have it installed on my Win 10 x64 laptop. I've just done fresh compiling Godot master using VS2015 successfully.

**Comment by RandomShaper** [comment]
It compiles fine for me with VS 2017.

**Comment by akien-mga** [comment]
Yeah it was actually due to an outdated fork branch: #12690.
