### ISSUE TITLE
Thread is not working in WebAssembly export

### ISSUE THREAD

**Issue by stubbsy345** [godotengine/godot#12699]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot alpha 2 Webassembly export.

Thread does not work in WebAssembly, I am conscious that may be because it is not possible to thread on this medium. But can't find anything stating that. 

```
var thread = Thread.new()
func start_order(ord):
	thread.start(self, "add_order", ord)
	
func add_order(ord):
	ordered = {"ReturnTime": ord["returnTime"], "WaitLeft": ord["returnTime"]}
	print(ordered)
	thread.wait_to_finish()
```

Works fine when not using a thread in webassembly.

**Comment by akien-mga** [comment]
cc @eska014

**Comment by eska014** [comment]
Threads are not in the WASM spec yet, work is ongoing here: https://github.com/webassembly/threads

**Comment by stubbsy345** [comment]
Is there any way of getting similar functionality to threading. I'm trying to avoid HTTP requests from blocking the main thread?

**Comment by reduz** [comment]
you could write a module that uses a javascript worker natively

**Comment by Zylann** [comment]
I'm pretty sure I've seen a way to use `HttpClient` without blocking the main thread. Then you woudln't need to use a thread.

**Comment by blockspacer** [comment]
Modern **Chrome supports threads** & "Shared Array Buffer" by default ( https://developers.google.com/web/updates/2018/10/wasm-threads )
For other browsers: you can enable threads with flags / browser settings. See also "Shared Array Buffer" support ( https://caniuse.com/#feat=sharedarraybuffer )
You can enable threads with USE_PTHREADS emscripten flag ( https://emscripten.org/docs/porting/pthreads.html ) and detect threads support at runtime (need to add 2 separate build modes: with and without threads, as fallback).

NOTE: when using USE_PTHREADS don`t block main loop, prefer emscripten_run_in_main_loop/thread https://github.com/emscripten-core/emscripten/issues/7535
**Very usefull to read**: https://github.com/emscripten-core/emscripten/issues/7535 and https://github.com/emscripten-core/emscripten/issues/8325
```
  # avoid having main thread synchronously block on a pthread
  # (the ".. sync blocking on main thread is bad.." mantra),
  # so dropping the pthread_join()
  # (and ensuring NO_EXIT_RUNTIME so runtime stays alive)
  # should also avoid the hang
  # DOM operations can only be done on the main thread
  # That includes things like printing to the console (!!!),
  # and even things like XMLHttpRequests!
```

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Calinou** [comment]
@KoBeWi Yes, as thread support isn't implemented in a stable Godot release yet. This will likely be in 4.0 as it requires browsers to get better support for WebAssembly threads.

**Comment by akien-mga** [comment]
Well this is fixed, threads are supported and working in HTML5 with a custom build (`threads=yes`).

3.2.4 will probably ship with both thread and no-thread templates to select at export.

**Comment by lenscas** [comment]
I just gave https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-3 a try to see how it works and I'm not sure how to enable threads?

I don't see an option for it in the export though. Do I need to do something special, am I blind or something else?
![image](https://user-images.githubusercontent.com/8694039/100693969-520eb400-338e-11eb-9bc7-f6785788ac72.png)

**Comment by Faless** [comment]
@lenscas as @akien-mga mentioned, thread support requires a custom build for now.
The option has not yet been added to the export UI, but assuming you compiled a template with `threads_enabled=yes` and you use that as a custom template it will work.
The stable 3.2.4 will likely ship both templates, and add the option to the export dialog

**Comment by blackears** [comment]
I'm using stable 3.4 and still running into the same issue.  Threads for web are not enabled automatically and I cannot find any option for it in the export options either.

**Comment by Calinou** [comment]
> I'm using stable 3.4 and still running into the same issue. Threads for web are not enabled automatically and I cannot find any option for it in the export options either.

Threads still need to be enabled on export by changing **Export Type** in the HTML5 export preset:

![image](https://user-images.githubusercontent.com/180032/176276593-66f0826c-6a3c-4c56-bc92-54e35a0813e4.png)

See [Exporting for the web](https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_web.html#threads) for rationale as to why threads are disabled by default.

**Comment by blackears** [comment]
When I select that option, I am given an error that a necessary export template is not available.  I opened the Manage Export Templates window, but the webassembly_threads is not there.  I did download what was presented, but it did not make this error message go away.

![image](https://user-images.githubusercontent.com/6724608/176280137-4cb70318-0b34-45d5-bc3c-97d4d7858bae.png)

**Comment by akien-mga** [comment]
Mono templates can't be build with threading support sadly. It's available for non-Mono builds. Likewise for GDNative support.

**Comment by blackears** [comment]
I came to this thread from https://github.com/godotengine/godot/issues/34506 which was referencing this as a solution for C# threading issues.  I'm basically just looking for a way to use async/await in C# and export something that works for web.

**Comment by Faless** [comment]
@blackears as I mentioned in https://github.com/godotengine/godot/issues/34506#issuecomment-743200985 the mono version do not support thread, because the mono version we use do not support modern emscripten versions.
Godot 4 should should come with donet6 which **should** support modern emscripten versions (and thus threading).

**Comment by ashelleyPurdue** [comment]
> @blackears as I mentioned in [#34506 (comment)](https://github.com/godotengine/godot/issues/34506#issuecomment-743200985) the mono version do not support threads, because the mono version we use do not support modern emscripten versions. Godot 4 should should come with donet6 which **should** support modern emscripten versions (and thus threading).

Why does Godot offer an option if that option isn't real?

**Comment by Zireael07** [comment]
@ashelleyPurdue There are a LOT of things that do NOT work in some combination of export platform/renderers
