### ISSUE TITLE
Instancing an EditorFileSystem object breaks the FileSystem dock

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#12693]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot 3.0 7376798

**Issue description:**
I created an instance of `EditorFileSystem` in a `Control` node that was instanced during the `_enter_tree` function of an `EditorPlugin`. I wanted to connect to the `filesystem_changed` signal on it, but before I could even do that, it seems that merely creating an instance of the `EditorFileSystem` object just one time results in...

1. all of the files except for the res:// and Favorites: folders disappearing.
2. both remaining folders becoming completely unresponsive.

A sample script:

    tool
    extends EditorPlugin
    func _enter_tree():
        print(EditorFileSystem) # results in perfectly normal behavior
        print(EditorFileSystem.new()) # results in FileSystem dock non-responsiveness

**Steps to reproduce:**
1. Create a plugin (`EditorPlugin` + plugin.cfg).
2. Create an instance of `EditorFileSystem` during the `_enter_tree` for the `EditorPlugin`.
3. Activate the plugin in the Project Settings > Plugins page (this actually causes the error in my currently running editor as well).
4. Re-launch the editor, and you will see the FileSystem dock is now completely unresponsive and largely empty.

I'm guessing you could trigger the same bug by executing an `EditorScript`, but I'm not 100% sure.

**Comment by djrm** [comment]
As far as i can tell EditorFileSystem exposes a singleton, so new should not be allowed.

**Comment by willnationsdev** [comment]
@djrm Well if that's the case, then there's a different problem because if I do...

    EditorFileSystem.connect("filesystem_changed", self, "my_method")

It results in an error saying that the "filesystem_changed" signal doesn't exist on the `GDNativeClass` object.

**Comment by djrm** [comment]
yeah because currently its exposed as class not as singleton, the singleton has to be exposed somehow (if this is desired).

**Comment by djrm** [comment]
@willnationsdev apparently when using editor plugins you have to this
```

# inside your editor plugin
var fs = get_edtitor_interface().get_resource_file_system()

```

that will give you the EditorFileSystem singleton

**Comment by willnationsdev** [comment]
oh interesting. I suppose it's more of a documentation issue than anything else then. I'll go ahead and leave this issue open then? Until documentation for the file is written up.

**Comment by djrm** [comment]
yeah plugins need a lot of tutorials, and also that class should be declared as abstract or something.
