### ISSUE TITLE
saving json file does not appear to be working when game is exported (on OSX and WebAssembly at least)

### ISSUE THREAD

**Issue by stubbsy345** [godotengine/godot#12695]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Tested issue on OSX and WebAssembly, Godot 3.0 alpha 2

**Issue description:**
During my game I track performance data and save it as a JSON when it changes. The data from this JSON is parsed when the player enters the menu screen and is able to view there performance data. Much like a save game to be honest. This is working when ran from the editor but when exported (on mac and webassembly, these are the only mediums I have to test on) the data does not update and is stuck as the json that is loaded with the initial game (i.e. blank with some formatting for the various keys). Below is the code I use to save the JSON: 

```
func save_JSON(saveFile):
    var performance = File.new()
    performance.open("res://JSON_files/performance.json", File.WRITE)
    performance.store_line(to_json(saveFile))
    performance.close()
```

As I say works fine from godot editor, but does not appear to work when exported. I seem to get the following error on exported version when the above code is intended to be ran as well:

`**ERROR**: **ERROR**: Condition ' !f ' is true.
**ERROR**:    At: core/bind/core_bind.cpp:1680:store_line() - Condition ' !f ' is true.`

**Comment by akien-mga** [comment]
That's not a bug, `res://` is read only in an exported game (it's your data.pck). You should write files to `user://`.

**Comment by stubbsy345** [comment]
Oh sorry. Thanks!

**Comment by stubbsy345** [comment]
So my code just has to be: 

```
func save_JSON(saveFile):
    var performance = File.new()
    performance.open("user://JSON_files/performance.json", File.WRITE)
    performance.store_line(to_json(saveFile))
    performance.close()
```

can the code still access the JSON_files folder?

**Comment by akien-mga** [comment]
No, `user://` is a platform specific folder for your game unrelated to your project files. So if you have a `JSON_files` folder in your project data pack that you want to modify, you could copy it to `user://` on the first launch of the game and do modifications there.

**Comment by stubbsy345** [comment]
Awesome thanks I understand now!
