### ISSUE TITLE
Bullet: Very Odd Results with BoxShape, StaticBody and KinematicBody

### ISSUE THREAD

**Issue by jedStevens** [godotengine/godot#12692]
manjaro, bullet update 

Here is a video of my current character, he used to be able to climb on all edges but now I'm getting strange results with the collisions. Basically there is a little bit of enabling/disabling on the upper shape, it should only be active when one of the raycasts near it are red and the one on the ground is not. It seems that I can only grab half of this box; the half pointing in Z-. I'm not sure what this is about but here is a video explaining where it falls off.
 
https://youtu.be/93pF3gMBmsc

I'm not sure how to exactly reproduce this, but it only show up when the bullet update happened. Here is footage of the same code, just better animations and different proportions on the shape, but before the bullet update.

https://www.youtube.com/watch?v=wD4wjEfEeo4

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by kubecz3k** [comment]
@jedStevens for the beginning test your project with exactly the same setup but on Godot physics. You can change it in `Project settings -> Physics -> 3d` there is `Physics Engine` property

**Comment by AndreaCatania** [comment]
@jedStevens I think the real problem is the raycast node that in this moment has a "problem" with bullet physics.

https://github.com/godotengine/godot/issues/12257

However to check this bug is necessary that you update a sample project, it's impossible for me to check it without it.

**Comment by AndreaCatania** [comment]
@jedStevens can you please recheck it? it should be fixed now

**Comment by jedStevens** [comment]
I can check later today I'm in travel at the moment.

**Comment by akien-mga** [comment]
Assuming fixed as mentioned above. Please comment if it's not the case so that we can reopen it.
