### ISSUE TITLE
Problem with project manager

### ISSUE THREAD

**Issue by JulioYagami** [godotengine/godot#12701]
Windows 10, Godot 3.0 Alpha 2

I downloaded godot 3.0 alpha 2 and found a problem in the project manager. I just created a test project, after testing a few things I closed the engine, deleted the project folder and when I opened the engine again, the project was still there. I do not think it would interfere with game development but solving it would be cool.

![capturar](https://user-images.githubusercontent.com/33421921/32442977-8cb8a00c-c2e4-11e7-8ae9-15ecc09fd312.PNG)

**Comment by akien-mga** [comment]
That's actually a feature implemented in #11163 (@marcelofg55).

Ideas to improve the usability further are welcome :)

**Comment by marcelofg55** [comment]
Maybe we could add an option on the Project Manager, something like "Remove deleted projects"?

**Comment by Hinsbart** [comment]
Or maybe a delete/"trash bin" icon next to greyed out items.

**Comment by groud** [comment]
Can't you just select the grayed item and push "remove" ?

**Comment by akien-mga** [comment]
Yeah I think what @groud mentioned is already good enough.
