### ISSUE TITLE
normal map import

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#12700]
would it be possible to add flip green channel in the import settings for textures. a lot of models grabbed from net have normals encoded in opengl format (like unity), but godot uses directx like ue4, so it would be really handy to have this option in the importer instead of having to flip green channel in ps or gimp.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/785, as feature proposals are now tracked on the Godot proposals repository. (This is implemented by https://github.com/godotengine/godot/pull/39202.)
