### ISSUE TITLE
Shader editor ignores "comment line" shortcut while script editor picks it up even when not in focus.

### ISSUE THREAD

**Issue by zedutchgandalf** [godotengine/godot#12702]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot Alpha 2 on Windows 8.1

**Issue description:**
When pressing Ctrl+K while typing in the shader editor, with the script editor visible, the script editor will comment out its current line and the shader editor won't do anything, even though the shader editor has focus and the script editor doesn't.

Ideally, I'd prefer if the built-in script editor could also be used for shaders, as right now I have to either work in a very small screen to edit a shader, or I have to constantly resize the bottom dock.

**Comment by groud** [comment]
Maybe related to #11556 ?
