### ISSUE TITLE
MacOS export failing on MacOS: godot_osx_release.64 not found

### ISSUE THREAD

**Issue by piever** [godotengine/godot#12704]
I'm on macOS Sierra (x86_64-apple-darwin14.5.0) and Godot 3.0 alpha 2 (downloaded the build).

When exporting a project to MacOS (using the downloaded export templates) I get 

![screen shot 2017-11-06 at 14 54 42](https://user-images.githubusercontent.com/6333339/32446962-7acf5b06-c302-11e7-9d55-417e363cf7fc.png)

Other exports seem to work fine.

To reproduce, simply download build and templates from [here](https://downloads.tuxfamily.org/godotengine/3.0/alpha2/) and export a project to MacOS.

**Comment by akien-mga** [comment]
I guess there are changes in the way OSX binaries are meant to be packed in the template now, but nobody made sure yet that the buildsystem for release binaries was adapated.

**Comment by BastiaanOlij** [comment]
@akien-mga problem lies here:
https://github.com/godotengine/godot/blob/master/platform/iphone/export/export.cpp#L447

```
String binary_to_use = "godot.iphone." + String(p_debug ? "debug" : "release") + ".";
int bits_mode = p_preset->get("application/bits_mode");
binary_to_use += String(bits_mode == 0 ? "fat" : bits_mode == 1 ? "arm64" : "armv7");
```
Weird though, it should be either adding .arm64 or .armv7, not .64, it used to be .fat. I don't know why I changed that though, I'll have a look how this was on Godot 2 and probably will change it back the way it was.

**Comment by akien-mga** [comment]
Well I'm fine with it changing, I just need to adapt my scripts.

**Comment by piever** [comment]
Just to make sure, I was trying to export to MacOS computer, not iphone (though maybe the two things are linked, I don't know).

There's one more piece of information which may be related. I tried compiling from source following the instruction for Mac (as explained [here](http://docs.godotengine.org/en/latest/development/compiling/compiling_for_osx.html)):

```
user@host:~/godot$ scons platform=osx
user@host:~/godot$ cp -r misc/dist/osx_tools.app ./Godot.app
user@host:~/godot$ mkdir -p Godot.app/Contents/MacOS
user@host:~/godot$ cp bin/godot.osx.opt.tools.fat Godot.app/Contents/MacOS/Godot
user@host:~/godot$ chmod +x Godot.app/Contents/MacOS/Godot
```

The docs assume that I would get a godot.osx.opt.tools.fat binary but I actually got a godot.osx.opt.tools.64. I'm not sure if that's linked with the change that broke the export for Mac.

Thanks a lot for looking into this!

**Comment by BastiaanOlij** [comment]
Ugh, sorry for some reason I have iOS in mind. That explains why it's .64 and not .arm64 :)

The code here is indeed very similar. I'm just going to tag @endragor in this as well. He's done a lot of work on this code as well.

**Comment by reduz** [comment]
any progress in this?

**Comment by akien-mga** [comment]
Yeah I fixed this in 3.0 beta 1 I think.

**Comment by PJB3005** [comment]
This still seems broken for me, using the non-mono official 3.0 build exporting to macOS from macOS.

**Comment by akien-mga** [comment]
Please open another bug report, it's not possible that you're experiencing this exact issue, that string doesn't appear anywhere in the engine.

**Comment by akien-mga** [comment]
>  it's not possible that you're experiencing this exact issue, that string doesn't appear anywhere in the engine

Actually the GitHub search failed me, this string indeed comes from the macOS export code. Sorry about that.

**Comment by akien-mga** [comment]
This error happens because we only ship fat binaries (32-bit + 64-bit), which is the default export option (`"application/bits_mode"`), but you likely changed it to 64-bit. So export 64-bit only, currently you need to build your own template as we don't provide it.

**Comment by akien-mga** [comment]
So it's not a bug but a badly exposed feature. Eventually, I think the fix might be to just get rid of the fat architecture and support only 64-bit on macOS, since I think all supported macOS versions are 64-bit only by now?

**Comment by Calinou** [comment]
@akien-mga That's true, 32-bit macOS is no longer supported since 10.8 or so.
