### ISSUE TITLE
NuGet and xamarin and netstandard support?

### ISSUE THREAD

**Issue by Thaina** [godotengine/godot#12716]
Hello. I am C# developer experienced in unity3D and very interesting in godot since it support C#

I wonder that is it already support nuget, xamarin and netstandard library?

Is it not, when it?

And if it is, where is the document about it?

If godot would build mobile with xamarin it would be easy to write native wrapper and reuse all native library with it so I could start working on godot soon

**Comment by exts** [comment]
@neikeq this can be closed right? Nuget support exists now iirc. Not sure about xamarin but I believe that discussion could be added to #20268 and #20267

**Comment by Thaina** [comment]
@exts It was a little bit difference

godot could theoretically implement both android and ios in the same way as unity, I mean implement it with its own IL to android/ios compiler independently from xamarin. But the result is that godot would not compatible with xamarin and cannot reuse xamarin code base. So what I propose here is godot should use xamarin specifically, not just export to ios and android

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/339, as feature proposals are now tracked in the Godot proposals repository.
