### ISSUE TITLE
put_utf8_string unwanted characters?

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#12712]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0, but was working fine on 2.1

See 3.0 `put_utf8_string`:
https://github.com/godotengine/godot/blob/372cdc20705dab7c2227b89d8bc4d425ffd3e8a4/core/io/stream_peer.cpp#L210

2.1 `put_utf8_string`:
https://github.com/godotengine/godot/blob/2.1/core/io/stream_peer.cpp#L210

**Issue description:**
In the 3.0 `put_utf8_string` function there is a new  `put_u32(cs.length());` line now. Which creates unwanted results when reading the string

Example using `put_utf8_string` in 3.0:
![image](https://user-images.githubusercontent.com/10387670/32471898-83aeecf2-c314-11e7-815a-1f2f8d886bd8.png)

And using `put_utf8_string` in 2.1: it will just display "rofl"

`\u0004\u0000\u0000\u` is coming from `put_u32(cs.length());`, but why exactly?

**Comment by raymoo** [comment]
So that the reader on the other end can tell how long the string is.

**Comment by Dillybob92** [comment]
Shouldn't the size only be sent when it's a buffer? Now, the reader needs to implement some kind of string replace/extraction code to get the exact text of "rofl"

**Comment by raymoo** [comment]
It's a stream, so a reader won't know where data starts or ends without being known beforehand, and also possibly requiring the information be encoded in the stream. For example, if you put two strings back to back, there is no way to know where one starts or ends unless you give a size (or do something else, like place a separator). You could put raw strings with put_data and get_data, but they will not do UTF8-encoding.

There are still problems with the change though. There is no method of StreamPeer that is the "reader version" of put_utf8_string, which is an obvious helper if people are going to use put_utf8_string (I am too busy right now to want to submit a PR for this).

I think that `get_utf8_string` should be just made into the reverse of `put_utf8_string` and read in a string size. Or at least add a zero-argument overload that does this.

**Comment by Dillybob92** [comment]
Yeah, I used `+"\n"` to separate them out as messages, used to work perfect >_<
