### ISSUE TITLE
Can't resize Tree node into a ScrollContainer

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1272]
hi,

I tried with 1.0stable, recent build and RC2, all win64.

If I put a populated Tree node into a ScrollContainer, it is not possible to set the size of the Tree node, and the Tree node is not displayed at all.

I tried with several other nodes, and ScrollContainer "squeeze" most of them.

might be related to #218

**Comment by UsernameIsAReservedWord** [comment]
PS : as I replied into the IRC to you @reduz, if I wanted to put my Tree node into the ScrollContainer, it was to try to workaround the strange clipping bug similar to #1136.

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by akien-mga** [comment]
Ping.

**Comment by neikeq** [comment]
This is still valid in the current master branch. EXPAND size flags won't work either.

**Comment by akien-mga** [comment]
Still valid in the current master branch.

**Comment by Chaosus** [comment]
@akien-mga Does it still exist ? - I checked but seems like everything looks ok (at least for me)
eg :
![image](https://user-images.githubusercontent.com/3036176/55391178-7d018e80-5541-11e9-957f-6522984281db.png)

I've attached this small example here - [TreeBug.zip](https://github.com/godotengine/godot/files/3033188/TreeBug.zip)

**Comment by akien-mga** [comment]
Seems fine yeah, closing as fixed.
