### ISSUE TITLE
whenever I import a texture with anisotropy I get a GL_ERROR

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#12722]
This is Windows 10 
Windows 64 build  November 6
GTX 1050Ti

Activated GL 3.3 contextOpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile

This seems to be a new error in the last 1-2 weeks  because I haven't seen this before.

Whenever I import a texture with Anisotropic ticked I trigger the error

ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1281        Severity: High  Message: GL_INVALID_VALUE error generated.
   At: drivers/gles3/rasterizer_gles3.cpp:122

![a](https://user-images.githubusercontent.com/6987027/32497806-c325bcb2-c39b-11e7-8e69-10a33e63ccc2.gif)

Might be related to another issue whenever I tick Direct3D and reimport the texture the Engine crashes 
![unknown](https://user-images.githubusercontent.com/6987027/32497828-d4bf9f2e-c39b-11e7-8ae9-a63f5baac7b2.png)

Both issues appear around the same time

**Comment by Sslaxx** [comment]
Possibly related to #11585 and #11872.

**Comment by trollworkout** [comment]
this issue begins with -06 build on http://godot3builds.digitecnology.com/  and incidentally it also coincides with #12809 crashing randomly on opening scenes

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by trollworkout** [comment]
@akien-mga i have tried the latest nightly from godot3builds.digitecnology windows 64 a8a3d5c and this issue is solved

**Comment by akien-mga** [comment]
Great news :)
