### ISSUE TITLE
Contact Shadows problems

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#12726]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
git master faf21d8

**Issue description:**

Contact Shadows have artifacts in most of viewing angles. They are not really useful at that state :<
![selection_031](https://user-images.githubusercontent.com/6152134/32508079-743c2ade-c3e9-11e7-8d59-a2ec36c82ff5.png)
![selection_032](https://user-images.githubusercontent.com/6152134/32508139-a62caf46-c3e9-11e7-94f0-06cce7e80b10.png)

**Steps to reproduce:**
Turn on Contact Shadows for Directional Light.

**Link to minimal example project:**

[Shadows.zip](https://github.com/godotengine/godot/files/1451001/Shadows.zip)

**Comment by Calinou** [comment]
Contact shadows are also pretty slow in my testing (especially when viewed up close), but I'm not sure if much can be done about this.

**Comment by capnm** [comment]
Another (editor) buglet is a weird shadow on the xyz-axes :

![bildschirmfoto](https://user-images.githubusercontent.com/4047289/32533953-abac05a6-c453-11e7-82d2-04fe4c5a8ef3.png)

**Comment by reduz** [comment]
Contact shadows are not really meant for biases as high as as in the images above.
You have to fix shadows adjusting the bias as best possible, then you mitigate the small remaining bit with it. 

The arctifacts shown in the picture are normal, there is just not enough information in the depth buffer to guess how shadow has to look. In any case I added a small workaround so bias appears a bit more fatty but does not dissapear as easily.
