### ISSUE TITLE
Unhandled exception after extensive idle time

### ISSUE THREAD

**Issue by bennbollay** [godotengine/godot#12728]
Win10 64-bit

**Issue description:**
Unhandled exception at 0x00007FF7C6AE9EFC in Godot_v2.1.4-stable_win64.exe: Fatal program exit requested. occurred

>	Godot_v2.1.4-stable_win64.exe!00007ff7c6ae9efc()	Unknown	No symbols loaded.
 	Godot_v2.1.4-stable_win64.exe!00007ff7c6af4327()	Unknown	No symbols loaded.
 	Godot_v2.1.4-stable_win64.exe!00007ff7c6ad1ae3()	Unknown	No symbols loaded.
 	[External Code]		Annotated Frame
 	Godot_v2.1.4-stable_win64.exe!00007ff7c6ad5e32()	Unknown	No symbols loaded.
 	Godot_v2.1.4-stable_win64.exe!00007ff7c5da73e5()	Unknown	No symbols loaded.
 	Godot_v2.1.4-stable_win64.exe!00007ff7c5da39c8()	Unknown	No symbols loaded.
 	Godot_v2.1.4-stable_win64.exe!00007ff7c5da402e()	Unknown	No symbols loaded.
 	Godot_v2.1.4-stable_win64.exe!00007ff7c6aeda08()	Unknown	No symbols loaded.
 	[External Code]		Annotated Frame

**Steps to reproduce:**
Leave the editor sitting idle for an extended period of time (>24 hrs).  When I returned to my desk, the program had crashed.

**A simple example project:**
[game.zip](https://github.com/godotengine/godot/files/1451184/game.zip)

**Link to core dump, split into multiple files:**

Rename the files .001, .002, .003 etc and open with 7z (or any zip tool) to extract the Godot_v2.1.4-stable_win64.zip file in the package.

[Godot_v2.1.4-stable_win64.dump.zip.001.zip](https://github.com/godotengine/godot/files/1451212/Godot_v2.1.4-stable_win64.dump.zip.001.zip)
[Godot_v2.1.4-stable_win64.dump.zip.002.zip](https://github.com/godotengine/godot/files/1451215/Godot_v2.1.4-stable_win64.dump.zip.002.zip)
[Godot_v2.1.4-stable_win64.dump.zip.003.zip](https://github.com/godotengine/godot/files/1451216/Godot_v2.1.4-stable_win64.dump.zip.003.zip)
[Godot_v2.1.4-stable_win64.dump.zip.004.zip](https://github.com/godotengine/godot/files/1451217/Godot_v2.1.4-stable_win64.dump.zip.004.zip)
[Godot_v2.1.4-stable_win64.dump.zip.005.zip](https://github.com/godotengine/godot/files/1451218/Godot_v2.1.4-stable_win64.dump.zip.005.zip)
[Godot_v2.1.4-stable_win64.dump.zip.006.zip](https://github.com/godotengine/godot/files/1451219/Godot_v2.1.4-stable_win64.dump.zip.006.zip)
[Godot_v2.1.4-stable_win64.dump.zip.007.zip](https://github.com/godotengine/godot/files/1451220/Godot_v2.1.4-stable_win64.dump.zip.007.zip)
[Godot_v2.1.4-stable_win64.dump.zip.008.zip](https://github.com/godotengine/godot/files/1451221/Godot_v2.1.4-stable_win64.dump.zip.008.zip)
[Godot_v2.1.4-stable_win64.dump.zip.009.zip](https://github.com/godotengine/godot/files/1451222/Godot_v2.1.4-stable_win64.dump.zip.009.zip)

```
3a84fb7e76c18830fc705aa9d7918101 *Godot_v2.1.4-stable_win64.dmp
99235a905569092a30e45ce8007897d8 *Godot_v2.1.4-stable_win64.zip
```

**Comment by Zylann** [comment]
Memory leak?

**Comment by bennbollay** [comment]
Nothing obvious, and no, the computer was still alive (as far as I could tell).

I'm running a locally built binary now and will update the issue the next time it occurs, if I can extract out a good backtrace.

**Comment by bennbollay** [comment]
Unable to reproduce on 2.1 head; closing.
