### ISSUE TITLE
Easy way to access exported variables from script editor

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#12721]
If I'm working on the script editor sometimes I need to jump back and forth between a section of code and the top where all exported variables are declared.

I can click on the node from the hierarchy of nodes (Scene panel) which will also bring the 3D scene editor, then make the changes to the exported variables and open the script editor again, although that's a bit complicated. 

Also from the script editor if one clicks on the script button to the right of the current node on the Scene panel, it'll show the script's attributes with the resource and reference attributes, so that won't show the exported variables fro the attributes inspector.

What do you think guys?

By the way, I decided to post these kind of suggestions here, before adding features is closed, but I can post them at the forums instead, the thing is that I'm still not familiar with how adding features is handled.

Any suggestion or comment is appreciated,

Cheers!

**Comment by Zylann** [comment]
There is the "outline" list of functions on the left panel to jump back and forth, maybe a "top" item could be added, like docs?

**Comment by rraallvv** [comment]
@Zylann, there are couple of issues with the way the exported vars work, maybe it's just me, but I stopped using those to quickly update changes in order to test some piece of code. A "top" item would help too, although I'm using the keyboard shortcut CMD+UP for that, thanks.
