### ISSUE TITLE
Add context help search (Shift+F1) to script editor context menu

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#12738]
Probably a Junior job?

Was briefly discussed in #4516.

**Comment by TheSofox** [comment]
Don't know who fixed it, but I can very clearly see "Contextual Help Shift+F1" in the search menu when editing a script in the latest master build. Seems to work too.

**Comment by akien-mga** [comment]
Yeah I think it was implemented a while ago actually.
