### ISSUE TITLE
Keep existing, merge with new import mode doesn't work

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1273]
Keep existing, merge with new mode doesn't work. It behaves like Keep existing, ignore new,
not doing anything.

To reproduce:
1. Import simple scene, 5-7 cubes is ok. For my tests I've parented it (parent to child - 1 2 3 4 5) in Blender. Set import option first time to overwrite existing, next - merge wit new.
2. In imported scene, rename first Spatial to something interesting, then add StaticBody as parent
to first spatial, and set Cube1 as parent to it.
3. Add another StaticBody  as a child to first StaticBody and parent Cube2 to it.
4. Save the scene and go back to Blender. Add Cube6 as a child to Cube5. Export scene again.
5. On the upper right corner you will see red marker, press it and select Save & Re-import.
Observe nothing is updated. Try Import 3D scene again, but select Keep existing, merge with new for both choises now - observe nothing again.
Delete Cube5. Select Import 3D scene with the same options - observe that Cube5 is not added back.

**Comment by reduz** [comment]
this piece of code is actually pretty complex and I'm not sure many of the
decisions it takes are correct, I will check it as soon as I have a bit of
time, but if you are interested, the actual code that does the merging is a
single function and can be found here:

https://github.com/okamstudio/godot/blob/master/tools/editor/io_plugins/editor_scene_import_plugin.cpp#L2175

**Comment by TheoXD** [comment]
Let me summarize the issue with a few words: "new objects in .dae are not being added with merge option"

**Comment by akien-mga** [comment]
Is this issue still valid in recent Godot versions?

**Comment by akien-mga** [comment]
Ping :)

**Comment by TheoXD** [comment]
@akien-mga, yes close it, merging functionality is long gone.
