### ISSUE TITLE
TileMap undo misses a large amount of tiles

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#12747]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 (x64), Godot 3 Alpha 2

**Issue description:**
When using Undo (both Ctrl-Z and through the menu) to undo the placing of multiple tiles with a single mouse click (hold and drag the mouse around), random tiles are missed and stay in the scene.

Example:
![undofailsoptimized](https://user-images.githubusercontent.com/20242421/32556892-f3ee8698-c4a0-11e7-910a-5e9e536c0fa8.gif)

**Steps to reproduce:**
* Select any TileMap node
* Place multiple tiles by clicking and holding down the left mouse button
* Undo

**Comment by Noshyaar** [comment]
cc: @Zylann 
I suspect this is because of #12334, not confirmed though.

**Comment by Zylann** [comment]
Weird, I read my own diff and I see the modified tiles are correctly all set into the `paint_undo` variable... Why would they be missed?

**Comment by Noshyaar** [comment]
https://github.com/godotengine/godot/blob/5fb359d8b1d58061af2d64b304dc0e62c9228efc/editor/plugins/tile_map_editor_plugin.cpp#L976-L978

Are you sure you don't want `has(pos)` instead? I don't know. I could be wrong.

**Comment by Zylann** [comment]
@Noshyaar ooooh you're right. Simple fix then :D
