### ISSUE TITLE
Can't install export templates when engine is already installed (itch.io)

### ISSUE THREAD

**Issue by varkatope** [godotengine/godot#12741]
I love that Godot is now available on itch.io, but there's a problem with the way the files have been made available there. When you install Godot from itch.io, it asks you whether you want to install two files: the current engine version for your OS, and the export templates. The problem is that if you install the engine first, there's no way to install the templates file through itch.io. All you get is a Launch button to launch the engine. Vice versa, if you install the export templates file first, you can't then install the engine.

I don't know what the itch distribution system looks like, but is there a way to add the templates as a DLC of sorts? Or as another separate "game"? In a pinch, even just a link on the project page to download the templates from godotengine.org would be a workaround.

**Comment by akien-mga** [comment]
Now fixed for 3.0, as we don't provide the export templates for manual download on itch.io. Instead, you can install them directly from within Godot by letting it download them. (In 3.0-stable it's relatively slow, but it will be much faster in 3.0.1 and 3.1).

Once itch.io adds support for shared depots, I'll consider bundling the templates with the itch.io downloads directly to avoid this two-step process.
