### ISSUE TITLE
Spatial axis scale does not respect snapping

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#12762]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 26 64 bits, b279f641c0b9e7af711d857917353905b48c6913

**Issue description:**

Spatial editor scale gizmo does not respect the use snap setting.

Edit: here is how it behaves in my system
![peek 2017-11-09 10-28](https://user-images.githubusercontent.com/1103897/32616859-09d7a2d0-c539-11e7-97b3-b99a554f3bde.gif)

notice how axis scale does not snap

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by n-pigeon** [comment]
Hmm. Works for me.

Can you be more specific how exactly it's not working? :)

**Comment by groud** [comment]
I assume this is for master ?
Please fill in at least this field in the issue template the next time. ^^

**Comment by djrm** [comment]
updated with an example and system info

**Comment by groud** [comment]
> updated with an example and system info

My comment was for the Godot version, 3.0 or 2.1. :D

**Comment by djrm** [comment]
it has the hash so its not a problem, also the gif is and the feature already tells you!

**Comment by Zireael07** [comment]
The gizmo you mean, the little boxes? Definitely 3.0.

**Comment by n-pigeon** [comment]
@djrm 
Check your Snap settings. Default is silly small I think (5%?) then it looks like it's not working even if it works :D 
Set it to 50% or something.

**Comment by groud** [comment]
> it has the hash so its not a problem, also the gif is and the feature already tells you!

Sorry, you're right, I didn't see the hash. But mentioning the version as 2.1 or 3.0 helps (a lot) setting the issue's milestone.  :)

**Comment by djrm** [comment]
oh sh!t, my bad, i didnt expect a setting for scale snap, i thought it would snap to the next snap boundary (which kinda makes sense).

**Comment by n-pigeon** [comment]
We should change defaults.

I will add a numerical output on the bottom, so user can see by numbers what he is doing, just like it works when rotating.
Will add it for translation too.

**Comment by groud** [comment]
> Check your Snap settings. Default is silly small I think (5%?) then it looks like it's not working even if it works :D

Maybe it's a little bit low then. :)

> We should change defaults.

Probably ^^

**Comment by n-pigeon** [comment]
I would also change default rotation from 5* to 15*.

**Comment by djrm** [comment]
i would like to see scaling working with increments of 'translation snap' steps, but that has to be discused, maybe its just me, that expect this feature to be more used in 'blocking out' levels.
