### ISSUE TITLE
Can't select more then one anchor point

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1276]
When editing some polygon - like Polygon2D or CollisionPolygon2D and using box selection tool, the only thing that can be selected are whole objects, but can't select just a couple of anchor points to move them simultaneously.

It should be done in this way:
- drag a selection box to select anchors
- click on one of them and drag or use arrow keys to move them
  like in Adobe Illustrator or any other vector graphics editor

**Comment by akien-mga** [comment]
That would be a nice feature indeed.

**Comment by MarianoGnu** [comment]
Polygon2D would be likely to be changed to allow best edition workflow and bone deformation, but afaik this need some 3.0 (GLES3) features...

**Comment by groud** [comment]
I think it is still valid.

**Comment by EricEzaM** [comment]
I've had a look at this and it would need a pretty significant rewrite of the polygon editors, including `abstract_polygon_2d_editor`.

**Comment by Krzycho666** [comment]
I've been playing with that some time ago, and I've got it almost production ready. I need to make just a few small adjustments. I'll try to finish it somewhere in upcomming weeks. It's working pretty well now.

**Comment by Anutrix** [comment]
@Krzycho666 Been waiting for this. Do share your progress.

**Comment by Calinou** [comment]
@Krzycho666 Bump :slightly_smiling_face:

**Comment by Calinou** [comment]
@Krzycho666 Bump :slightly_smiling_face: 

Please look into publishing your work, even if it's not completed. This way, someone else can bring it to completion and get this merged into Godot.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/5729, as feature proposals are now tracked on the Godot proposals repository.
