### ISSUE TITLE
Add create object menu for meshes

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#12767]
May be godot can add some menu like blender's create menu.
Click to create cube , plane,etc...
![menu](https://user-images.githubusercontent.com/24988459/32588923-b2a73d22-c54c-11e7-9d46-d5e73b15326f.jpg)

**Comment by n-pigeon** [comment]
Sounds like a good candidate for a Plugin in AssetLib.

**Comment by groud** [comment]
Well, Godot is not Blender, you don't need basic shapes really often.
That being said, it might be useful to create placeholders.

> Sounds like a good candidate for a Plugin in AssetLib.

Probably. :)

**Comment by sersoong** [comment]
But ...u3d and ue4 have it.
Maybe some testers will like it.
Test materials or lights? sometimes.

**Comment by groud** [comment]
> But ...u3d and ue4 have it.

Do you have any screenshot ? 
I'm not again a more generic menu, with a list of appropriate nodes or scenes. But if it's only for basic shapes like spheres, cubes... it doesn't worth it to be built-in.

**Comment by n-pigeon** [comment]
@sersoong 
It is very useful! I totally agree!

Although.
We should think to make official plugins in AssetLib for stuff like that.
Plugins would be easier to maintain end extend, more than C++ module and most of tools like that don't need native code to run fast. :)
It would be two side win.

**Comment by Zireael07** [comment]
Guys, in master you can create basic placeholder meshes like spheres, quads and cubes by creating a mesh instance and assigning it a QuadMesh or a SphereMesh or a CubeMesh.

Similarly for 2.1. we have a plane mesh and a quad mesh as separate node types.

Unless I'm completely misunderstanding the request this is something we already have in Godot?

**Comment by sersoong** [comment]
We should make it easier to use, don't we?

**Comment by n-pigeon** [comment]
@Zireael07 
@sersoong is asking for tool to do this fast :D

**Comment by sersoong** [comment]
This is what the editor should do.
More simple, easier, more suitable for stupid designers.

**Comment by n-pigeon** [comment]
I know many designers. They are not stupid :D 
They always have shit load of work tho...

**Comment by Zireael07** [comment]
Ok, I get the point now.

3.0 is already much more user friendly in this respect than 2.x. I'm not so sure we can find a way to make it even easier in 3.0 without cluttering up the editor itself?

**Comment by groud** [comment]
> Guys, in master you can create basic placeholder meshes like spheres, quads and cubes by creating a mesh instance and assigning it a QuadMesh or a SphereMesh or a CubeMesh.

I think the request is to have a context menu that pops-up where you click on the screen.

**Comment by n-pigeon** [comment]
I would do this as a Plugin and in form of palette with drag n drop + on Viewport gizmo to just draw it instead editing properties.
First version could be only Palette with drag n drop that creates MeshInstance with right Mesh assigned and snaped to surface you drag.

**Comment by sersoong** [comment]
When we train new people, we can tell them click + click, or drag n drop.
Not add....blah blah blah node and then add blah blah blah res..
In a word, thank you very much for your work. @n-pigeon

**Comment by n-pigeon** [comment]
Too early to thank me. :P 

I wanted to work on set of tools like that but for now I'm fighting Spatial Tranform Gizmo math. :< And I'm loosing! xD

**Comment by Malkverbena** [comment]
Maybe this plugin caoulb be interesting someway.

https://github.com/TheHX/add_primitives

**Comment by akien-mga** [comment]
This was implemented by @BastiaanOlij in #8661 already.
![screenshot_20180315_084658](https://user-images.githubusercontent.com/4701338/37450242-74bca9f4-282d-11e8-9d41-14c55418d677.png)
