### ISSUE TITLE
A Gridmaps navmesh doesnt account for the position

### ISSUE THREAD

**Issue by scayze** [godotengine/godot#12766]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Win 10, Godot Alpha 2

**Issue description:**

The Navmesh the gridmap node generates doesnt account for the position of the gridmap node itself

**steps to reproducs:**
- Create new scene with a Navigation node as root
- Add Gridmap as child
- Draw a grid which utilizes the navigation meshes in any way,
- and try to use the navigation node in any way

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by smix8** [comment]
@KoBeWi 

I looked at source and the GridMap adds its own global_transform + grid-offset to each navmesh region. This is done when the GridMap enters the world and also when the GridMap transform changes.

While there are other issues with GridMap navmesh bakes this old issue is no longer valid in Godot 4.0 and 3.5 and can be closed.
