### ISSUE TITLE
Crashes on clicking on Project Settings [windows]

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#12769]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win 7 x64 
Godot 9a78efc

**Issue description:**
Intermittent crashes when clicking on Project Settings.
Seems to be limited to Windows platform as far as we saw in #12551. Also could be related to using MSVC for compiling, but I can't check out minGW compiling since a certain person deleted their helpful comment in the linked issue.

**Steps to reproduce:**
Open a project, click on project settings. Sometimes you can go a whole day without crashes, other times you get two or three in a row.

**Link to minimal example project:**

**Comment by hpvb** [comment]
Can you run from the command line and provide a backtrace when this happens please?

**Comment by Zireael07** [comment]
Ah-ha, THAT's how you get a backtrace.

It won't be very helpful though:

F:\downloads\Godot\3.0alpha2>Godot_v3.0-alpha2_win64.exe
Activated GL 3.3 contextOpenGL ES 3.0 Renderer: AMD Radeon 6600M and 6700M Serie
s
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
OPENING: F:/downloads/Godot/3.0alpha2/export (F:::downloads::Godot::3.0alpha2::e
xport)
running cmdline: "F:\downloads\Godot\3.0alpha2\Godot_v3.0-alpha2_win64.exe" "--p
ath" "F:/downloads/Godot/3.0alpha2/export" "--editor"

AF:\downloads\Godot\3.0alpha2>ctivated GL 3.3 contextOpenGL ES 3.0 Renderer: AMD
 Radeon 6600M and 6700M Series
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
[...] (snipped irrelevant stuff, including my own project's logging and a lot of unicode invalid skip errors, and two update_camera: Condition ' !E ' is true 's

ERROR: Vector<class TreeItem *>::operator []: FATAL: Indexp_index=0 out of size
(size()=0)
   At: c:\projects\godot-builds\godot\core\vector.h:137
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://git
hub.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] <couldn't map PC to fn name>
[25] TranslateMessageEx
[26] CallWindowProcW
[27] CallWindowProcW
[28] glDebugEntry
[29] TranslateMessageEx
[30] TranslateMessage
[31] <couldn't map PC to fn name>
[32] <couldn't map PC to fn name>
[33] <couldn't map PC to fn name>
[34] <couldn't map PC to fn name>
[35] <couldn't map PC to fn name>
[36] BaseThreadInitThunk
-- END OF BACKTRACE --

**Comment by akien-mga** [comment]
For the reference, here are the nice instructions that Dillybob92 wrote on #12551 before deleting their account :/

> What I did:
>
> - Download 64-bit version http://www.msys2.org/
> - Went to C:\msys64 and ran mingw64.exe
> - Followed steps 2, 3, 4, 5, 6: https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2
> - Then, enter the godot-master folder, hold shift+right click -- click open command prompt here, and I used this for scons: scons platform=windows tools=yes target=release_debug bits=64 -j8
> - I personally then run strip ./bin/godot.windows.opt.tools.64.exe
>
> Hope that helps. We also don't have to worry about -j8 causing the occasional "missing file error" and re-running the command. It's reallly nice

And what I mentioned there too as an addition (which was visibly interpreted as a rebuke, which of course was not my intention): When building your own binaries to test and report issue, please skip the "strip the binary" step mentioned above. It removes all debug information and makes debugging backtraces much more limited (such as the one above this comment). On the other hand, you can strip the binary before distributing it as it reduces the size a lot (typically by 60-75%).
