### ISSUE TITLE
RigidBody falling slightly with Gravity Scale set to 0

### ISSUE THREAD

**Issue by hickop** [godotengine/godot#12770]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Godot 3 master 5f805de6cbfe8a3afc8c5453317fc843b7228c73

**Steps to reproduce:**
- Create RigidBody with CollisionShape
- Set Gravity Scale to 0
- Run and see RigidBody falling before stopping

**Link to minimal example project:**
[physics.zip](https://github.com/godotengine/godot/files/1457066/physics.zip)

**Comment by CowThing** [comment]
Only happens with Bullet physics.

**Comment by akien-mga** [comment]
cc @AndreaCatania

**Comment by AndreaCatania** [comment]
Fixed: https://github.com/godotengine/godot/pull/13046
