### ISSUE TITLE
Hold Shift to draw anchor perpendicularly

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1277]
Holding shift key to draw new anchor point only in n*45 degrees ( also perpendicularly ) according to the last one, would be a big adventage. So as snaping not only to grid but also ie. to other anchor points.

**Comment by bojidar-bg** [comment]
Note, it can use angle snapping from snapping options, not 45°.

**Comment by akien-mga** [comment]
+1

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
