### ISSUE TITLE
StreamPeer UDP and TCP 

### ISSUE THREAD

**Issue by Tilican** [godotengine/godot#12788]
Create a TCP or UDP client and send data to a nodeJs server.
With TCP i got the 4 bytes paddes but not in UDP ?!?
Ref: http://docs.godotengine.org/en/stable/learning/features/misc/binary_serialization_api.html

**Comment by reduz** [comment]
UDP has an implicit packet size, while TCP has to specify the packet, still
no idea what you are trying to do

**Comment by Tilican** [comment]
But in UDP packet there is already the ID from binary_serialization_api (like 20 => dictionnary)
Use tcp / udp with nodejs backend : https://www.npmjs.com/package/gd-com
