### ISSUE TITLE
ViewportTexture errors when loading a scene.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#12781]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Window 10 64bit - Godot 3.0 9a78efc7c

**Issue description:**
When a scene is opened with a Viewport and a Sprite that uses the ViewportTexture, these errors show up. `Node not found: Viewport` and `ViewportTexture: Path to node is invalid`. The other error about `There is another space` I think is related to the Viewport using "own_world".

![Errors](https://i.imgur.com/rhUlmoC.png)

Even though these errors show up, everything still seems to work correctly. The viewport texture still shows up just fine in-game.

**Link to minimal example project:**
[viewport_errors.zip](https://github.com/godotengine/godot/files/1458175/viewport_errors.zip)

**Comment by Web-eWorks** [comment]
This issue is due to `ViewportTexture::setup_local_to_scene()` being called _before_ the node the viewport texture is attached to is added to the tree. Thus the `get_node()` call ([viewport.cpp:62](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L62)) is not finding the node it's looking for.

Additionally, setting the Viewport Path in the editor picks up the entire node tree, including the editor's nodes.

**Comment by akien-mga** [comment]
Can this still be reproduced in the current master branch?

**Comment by CowThing** [comment]
Using the latest build from http://godot3builds.digitecnology.com/ ( da4edf83d ) it still happens. Although the "There is another space" error doesn't happen anymore. The first two errors do still happen.

It seems the problem got worse. If I close the project and reopen it, the viewport texture doesn't show up in the editor anymore, but it does still show up in-game.

The console is being spammed with this
![](https://i.imgur.com/qkB2wLn.png)

**Comment by AndreaCatania** [comment]
The problem was because in the editor the parameters was not filled. This #15521 fix the errors

**Comment by AndreaCatania** [comment]
Finally I fix it with: #15528

**Comment by EmeraldSlash** [comment]
I'm getting this issue again in Godot 3.1.
<img width="399" alt="Screenshot_72" src="https://user-images.githubusercontent.com/25362339/55365768-48420700-5542-11e9-97c2-e943207a3dab.png">

**Comment by SubSage** [comment]
I can confirm as well this issue exists on 3.1 for me as well on linux.

**Comment by indutny** [comment]
I'm still getting this too.

**Comment by katp32** [comment]
This issue is definitely still present, using Godot 3.2 stable on Gentoo Linux

**Comment by arigbs** [comment]
Getting it too on Godot 3.2
