### ISSUE TITLE
Limit ammount of Sub-resources showed in context menu

### ISSUE THREAD

**Issue by TeddyDD** [godotengine/godot#12790]
Godot 3 5f805de6cbfe8a3afc8c5453317fc843b7228c73
**Issue description:**
Godot has this new cool feature - it shows sub-resources of node when you right click it in inspector.
Problem starts when you have **a lot** of Sub-resources...

![zrzut ekranu z 2017-11-09 23-06-30](https://user-images.githubusercontent.com/4397533/32632221-0f5aab66-c5a3-11e7-97d4-858b7ea3352c.png)

**Steps to reproduce:**
- create node with big amount of sub-resources. Easiest way: create theme using #12718 and assign it to node
- right click on node

**Comment by leoddd** [comment]
It would be nice to move this to the bottom, below the other options.
