### ISSUE TITLE
Impossible to modify DAE animation from file storage

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12801]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
186f0dffdfd9d9d92679d9f38267a99e930b8806 Ubuntu 17.04

**Issue description:**
When setting import options of dae model, the location of animations can be chosen. After setting it to file storage, it should be possible to modify and save the animation by adding `func call` tracks for example. 
Unfortunately this don't seems to work for me.
**SHORT 40S VIDEO:** https://youtu.be/7lWTLsLDiGI

**Steps to reproduce:**
1. Select Blue_spike_gun_lvl2.dae in godot file explorer (or use any other model)
2. Set save location for animation as 'file'
3. Reimport model.
4. Open model
5. Add new function track in fire_1, add keyframe and some function call
6. Save animation via 'save' icon in animation player
7. Close and open editor.
8. Open Blue_spike_gun_lvl2.dae model and check there is no 'call function' track in the animation

**Link to minimal example project:**
[ExternalAnimModification.zip](https://github.com/godotengine/godot/files/1460756/ExternalAnimModification.zip)

**Comment by kubecz3k** [comment]
@reduz Sorry to tell but it seems I still have problem with adding function call tracks to the animation. From the title of the commit "ability to keep user tracks when importing animations". The problem is I never have get so far with those animations to worry about loosing them on reimport. 
I literally can't keep function tracks after closing and opening godot again, despite the fact they should be saved and loaded from the file. 

**From what I have just tested it seems the animations from files are simply not linked with AnimationPlayer** (I can load given animation manually from the file and the tracks will be there)

Please take a look at the really short video from the first post.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment]
I think this should be working now (I fixed it some months ago), so closing.
