### ISSUE TITLE
Skeletal mesh is not render on latest 6s+ iOS devices

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#12804]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
IPhone 6s, Ipad (2017). *Bugsquad edit:* master branch.

**Issue description:**
On IPhone 6s, iPad Pro (1st generation) and i guess all `Apple A9` devices skeletal mesh dont draw.
In output log it displays the following error message:
```
skel_test.iphone[583:171369] GLDDevice failed to build pipeline state: Cannot convert attribute from MTLAttributeFormatUChar4 to a signed integer type
```
I try to debug and found that it failed on  https://github.com/godotengine/godot/blob/efe9a6ff5a55e1533a223dbaf43e7b7c20810b33/drivers/gles3/rasterizer_scene_gles3.cpp#L1486

**Comment by akien-mga** [comment]
CC @BastiaanOlij

**Comment by kosz78** [comment]
I have attached screenshot of GPU trace on step that draw a skeletal mesh: 
![screen shot 2017-11-10 at 7 28 23 pm_cr](https://user-images.githubusercontent.com/3992195/32658688-c98844bc-c64d-11e7-9a64-8ad95437a1ff.png)

**Comment by kosz78** [comment]
Additional details, this errors produced by line https://github.com/godotengine/godot/blob/efe9a6ff5a55e1533a223dbaf43e7b7c20810b33/drivers/gles3/shaders/scene.glsl#L45 , when I changed attribute type to:
```
layout(location=6) in ivec4 bone_indices; // attrib:6
```
cast errors was eliminated

**Comment by kosz78** [comment]
I have added workaround PR that solve the issue.

**Comment by akien-mga** [comment]
There has to be a better way to fix it, changing to `vec4` and casting everywhere these are used is a hack. I don't see mentions about iOS not support `ivec4`, so there should be a way to use it as it should be.
