### ISSUE TITLE
I have 2 tscn  that are identical in the engine but one crashes the editor the other does not

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#12809]
Diff here:
https://www.diffchecker.com/ak6GkFiZ

- The one on the left (red called archer.tscn) crashes the editor  when opening the file but the file works fine when I use it in game
- The one on the right (green called archer2.tscn) works fine
- Both tscn files were created inside the editor and to the editor they appear identical however looking at the diff they are slightly different.
- In other words they DO NOT crash the game (ONLY the editor)
- I did not edit these files at all. Is all what Godot editor thought appropriate. The 2nd file I simply added it to a new scene expanded it in the scene copied all its components out and pretty much duplicated all the settings since I did them last night I remember everything I did 

Makes zero sense to me

I think it somehow adds a new "hidden" animation and might something to do with autoplay next animation. That feature instead of working as intended it simply produces a new hidden anim

![b](https://user-images.githubusercontent.com/6987027/32659728-12f83bc6-c5ee-11e7-97d1-329452814767.gif)

This is what windows tells me 
![image](https://user-images.githubusercontent.com/6987027/32660404-b2d17340-c5f0-11e7-9026-8949c04518ea.png)

And this weird crash thing is started happening starting with the 7th  around same time the GL_ERROR appears too (not sure if related at all)
![image](https://user-images.githubusercontent.com/6987027/32659909-ab71a072-c5ee-11e7-8985-9ee3475e043f.png)

**Comment by Zireael07** [comment]
If you make a copy of the red scene and edit line 204 to be frame = 0, does it still crash?

**Comment by trollworkout** [comment]
@Zireael07  yes

Also note both these files were edited by Godot Editor so the values there I did not change manually at all

**Comment by trollworkout** [comment]
@Zireael07 I added this comment

I think it somehow adds a new "hidden" animation and might something to do with autoplay next animation. That feature instead of working as intended it simply produces a new hidden anim so it increments all animation refs by 1

**Comment by akien-mga** [comment]
What's your Godot version, and where does it come from?

**Comment by trollworkout** [comment]
@akien-mga  http://godot3builds.digitecnology.com/ 64 bit windows version

**Comment by trollworkout** [comment]
@akien-mga  just reverted to   2017-11-05  and no more crashes  . somehow after -05 it acts very strangely with certain files sometimes they work sometimes they don't . i don't think is the files to be honest . because that archer2.tscn file that used to work now no longer works. i changed nothing.

**Comment by trollworkout** [comment]
incidentally -05 version does not have the GL_ERROR anymore either

**Comment by akien-mga** [comment]
It's possibly a duplicate of #12715, if so it should be fixed since yesterday. Please try again as soon as a new daily build is available.

**Comment by trollworkout** [comment]
@akien-mga  ill try again as soon as possible when next build is available at the end of the night and I will report back here  thank you

**Comment by trollworkout** [comment]
this appears to be fixed in the lastest nightly akien is correct thus closing
