### ISSUE TITLE
EventStreamChibi: doesn't play classic MOD files

### ISSUE THREAD

**Issue by Domarius** [godotengine/godot#12805]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7, Godot Engine v2.1.4.stable.official

**Issue description:**
EventPlayerChibi won't play any regular MOD files.  Other types (eg. S3M) work fine.

Don't get me wrong, I'm thrilled that I can play tracker music with this, and I can easily work around the bug by just re-saving the MOD files as S3M or IT using OpenMPT.  But I just thought the bug should be reported anyway.

**Steps to reproduce:**
* Add an EventPlayer node
* set the Stream type to EventPlayerChibi, load a MOD file (.MOD extension)
* Create script in the EventPlayer node
* under `func _ready():`, add the line `self.play()`

**Link to minimal example project:**
[Godot test.zip](https://github.com/godotengine/godot/files/1461171/Godot.test.zip)

**Comment by tagcup** [comment]
I seems this is removed in 3.0. Will it come back for 3.1?

**Comment by akien-mga** [comment]
> I seems this is removed in 3.0. Will it come back for 3.1?

There are no plans for it yet AFAIK.

**Comment by Redsandro** [comment]
> There are no plans for it yet AFAIK.

Is there a roadmap or plan or popularity-contest somewhere? I'd like to know which (other) classes are unavailable, are worked on, or are dropped in 3.x.

**Comment by Calinou** [comment]
@Redsandro Check out https://github.com/godotengine/godot-roadmap

**Comment by xphere** [comment]
From what I understand from [2018 GSOC Roadmap](https://github.com/godotengine/godot-roadmap/blob/master/GSOC-2018.md#plugins-for-midi-and-mod-support), MOD/S3M/XM support should be back again soon. Is it?

**Comment by Redsandro** [comment]
@xphere that is a [Google Summer of Code](https://en.wikipedia.org/wiki/Google_Summer_of_Code) ideas list; suggestions for student volunteers. There are no asignees or guarantees, just hopes and dreams. :wink: 

Either way, GSoC ends on August 22nd.

**Comment by Domarius** [comment]
As I said above, it was only MOD files that didn't play, all the other formats I tried worked fine (S3M, XM, and IT) and you can re-save a MOD as an IT file easily with OpenMPT.  
Unless things have gotten worse since I posted?

**Comment by xphere** [comment]
@Domarius maybe it still works in 2.* but not in 3.0 anymore, due to [full rewriting of the sound system.](http://docs.godotengine.org/en/3.0/tutorials/audio/audio_streams.html)

**Comment by Domarius** [comment]
Ah I just got caught up, and I see that we should stick with version 2 if we want things to be stable, and 3 will be improved over time.  I love Godot because of the authenticity with which you can make retro games, It has really good pixel perfect support - mod support goes right along with that!  Keeps the game size small too...

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
