### ISSUE TITLE
Add a way to set a tile sprite scale

### ISSUE THREAD

**Issue by lisacvuk** [godotengine/godot#12812]
... to allow pixel art tile-based games.
Of course one can still just upscale the sprite, but that feels hacky.

**Comment by Zylann** [comment]
I don't understand what you are asking for.
It's already possible to upscale stuff using one of these existing solutions:

- Upscale the texture (a bit naive though)
- Scale the sprite in engine using the `scale` property
- Use camera zoom (no need to scale all objects one by one)

**Comment by lisacvuk** [comment]
It would be nice if tilesets respected tile's sprite's scale

**Comment by Zylann** [comment]
@lisacvuk so.... scale the tilemap? Otherwise you would end up scaling all sprites in your tileset manually, which isn't convenient either.

**Comment by lisacvuk** [comment]
Hmm scaling the tilemap seems to work, thanks. I'll close this.
