### ISSUE TITLE
Theme -> Add item -> Type Icons does not work because p_icon.is_null()

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1282]
hi,

custom build of few days ago, win64.

i'm trying to add custom icons to my theme. But when I `Theme -> Add item -> Type Icons`, the console says : 
**ERROR: Theme::set_icon: Condition ' p_icon.is_null() ' is true.**
**At : scene\resources\theme.cpp:212**

and no icon is added into the Inspector, not even after I `Theme -> Add Class Items -> Type Icons` to try to refresh the Icons list.

**Comment by akien-mga** [comment]
Can you still reproduce this issue in the current master branch / nightly builds?

**Comment by akien-mga** [comment]
Ping :)

**Comment by SuperUserNameMan** [comment]
Yes, issue still present into 2.0.2.stable official release.

**Comment by akien-mga** [comment]
Tested in 2.1-beta / the current master branch and I don't see this error message anymore. I have no clue how to use the theme editor though so I can't confirm if the bug is fixed :)

**Comment by akien-mga** [comment]
Assuming this got fixed with the 2.1 changes to the theme editor.

**Comment by Sslaxx** [comment]
Not able to replicate this, myself.
