### ISSUE TITLE
A concept: Include scons-local in the repo

### ISSUE THREAD

**Issue by NullConstant** [godotengine/godot#12835]
From SCons' website:
>The `scons-local` package is one that you can execute standalone, out of a local directory. It's intended to be dropped in to and shipped with packages of other software that want to build with SCons, but which don't want to have to require that their users install SCons.

Granted, this would only *really* benefit Windows users (though I imagine those make up at least *a* chunk of Godot users), since installing SCons is trivial everywhere where an actual Unix shell & package manager is available, but it would help, and not bloat the repository itself by that much either (the zipped `scons-local` package is about ~640kB, and SCons itself is MIT-licensed so there wouldn't be an issue with including it that way either).

**Comment by akien-mga** [comment]
I think it's a bad idea, see https://github.com/godotengine/godot/pull/12843#issuecomment-343761752 for details.
