### ISSUE TITLE
3.0 - Attach Script Dialog has a GUI display error.

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#12833]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows7 x64 gtx750ti

**Issue description:**

see the image below:
![capture](https://user-images.githubusercontent.com/24988459/32686257-73402f18-c6dc-11e7-9792-394a0fc62a08.png)

**Steps to reproduce:**
open attach script dialog.

**Comment by mrcdk** [comment]
Yeah, it seems there are some tiny issues with the UI here and there like (build from commit https://github.com/godotengine/godot/commit/19b1ff0fc5f7acce23176ad6c8752604357472f0):

![https://i.imgur.com/kTebzLT.png](https://i.imgur.com/kTebzLT.png)

![https://i.imgur.com/SbCC8o2.png](https://i.imgur.com/SbCC8o2.png)
The ON/OFF toggle is always selected

And probably more... I guess @djrm would know what the issues are

**Comment by djrm** [comment]
the checkbutton is fixed by  #12827, will look at the rest.
