### ISSUE TITLE
Godot3 uses significantly more GPU memory

### ISSUE THREAD

**Issue by organicpencil** [godotengine/godot#12831]
This affects both the editor and exported games. I have tested a blank project with debugging disabled to remove any confusion.

To replicate:
1. Make a new project with a blank 2D scene.
2. Export in release mode
3. Launch the exported game and take note of GPU memory usage

Godot 2.1.4: 45MB
Godot 3 alpha 2: 315MB (also confirmed in master)

The above result was on Linux64 with an NVIDIA GTX 1060.

Similarly on a Windows 10 machine with Intel HD4000 (~932 MB set aside for the GPU) any attempts to open a second instance of the editor will print errors to the console about lack of GPU memory, then crash the system. With godot2 I am able to open many instances.

**Comment by Zylann** [comment]
This can also be a problem when developping multiplayer games...

**Comment by reduz** [comment]
How are you measuring GPU memory usage?

**Comment by organicpencil** [comment]
On Linux with nvidia:
`watch nvidia-smi`

The following was after opening a blank project in the editor:

```
Sun Nov 12 11:33:28 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                 Driver Version: 384.98                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
| 25%   35C    P8     6W / 120W |    806MiB /  3013MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1114      G   /usr/libexec/Xorg                            244MiB |
|    0      2246      G   ...er/Downloads/Godot_v2.1.4-stable_x11.64    54MiB |
|    0      2268      G   ...user/Downloads/Godot_v3.0-alpha2_x11.64   505MiB |
+-----------------------------------------------------------------------------+
```

**Comment by akien-mga** [comment]
Didn't know about `nvidia-smi`, it's a nice tool. I can confirm the issue, on my system Godot 2.1.4 uses ~100 MiB or VRAM, while 3.0-master goes up to 700 MiB for a very simple project (scene with a Sprite using the Godot logo).

**Comment by djrm** [comment]
In my case thousands of objects and thousands of vertices and i get 541MiB (the running game is 361 MiB) from nvidia-smi, but godot reports 3.12 MB of video RAM

**Comment by reduz** [comment]
Godot 3 uses considerably more memory by default than 2. You can still change, for your game, settings to use less if you need to:

![image](https://user-images.githubusercontent.com/6265307/33691534-76f923ea-dac7-11e7-9803-a57672f8c667.png)

In any case, reduced some memory by reducing quality of some viewports that will not display 3D.

**Comment by djrm** [comment]
also there is this
https://devtalk.nvidia.com/default/topic/1026874/linux/huge-performance-losses-with-newer-nvidia-drivers/post/5223375/#5223375

if thats not the problem the increase in memory usage is a bit extreme

**Comment by organicpencil** [comment]
Alrighty - by going through the rendering settings and knocking down everything (it's a simple 2D game) I was able to get it down to 119MB. Still 2x-3x more than I hoped for, but it's low enough that my target minimum hardware is functional again.

Something that might improve UX: A 2D preset that automatically disables things you don't need. But I'm happy enough just to have a workaround.

Some final test results before signing off:
Godot3: 119MB
Godot2:	44MB
Urho3D:	27MB

**Comment by reduz** [comment]
Hopefully the GLES2 backend of Godot will use a lot less mem.

**Comment by reduz** [comment]
oh I forgot, if you also turn off HDR in the quality settings, the memory usage should come down even further

**Comment by kb173** [comment]
This is currently very much an issue for me... the editor with a simple scene open takes about 700MB, the running game with that same scene (just 2 images at HD resolution and a ListView) takes over 700MB as well. That can't be normal, right? I'm hitting the limit of my 2GB of VRAM very quickly.

**Comment by clayjohn** [comment]
@kb173 That sounds like a bug. Can you create a new bug report with a minimal reproduction project so other users can reproduce your issue?

**Comment by kb173** [comment]
@clayjohn Just to make sure there's really something wrong before opening the issue: How much VRAM do your editor and running game use with a small project?

**Comment by Calinou** [comment]
If you don't use 3D in your project, you can decrease RAM usage by setting **Rendering > Quality > Intended Usage > Framebuffer Allocation** to **2D** in the Project Settings.

**Comment by clayjohn** [comment]
@kb173 Rather small, under 200mb for sure.

**Comment by kb173** [comment]
@clayjohn So, after a lot of testing with my whole driver setup, I got bumblebee working - I thought by only offloading Godot to the GPU, I'd have more spare VRAM. Now, as it turns out, when using bumblebee's `optirun`, Godot is suddenly using as much VRAM as it should! (The editor is at 139MB)

So to summarize, it seems like statically using the Nvidia GPU on a laptop which also has integrated graphics, instead of Nvidia's Optirun, can cause the VRAM usage to go way up.

I don't know if I should open a Godot issue for this, or rather report it to the Nvidia driver people or something? This whole thing is a mess.

**Comment by clayjohn** [comment]
That sounds like a NVidia driver bug. Probably best to figure it out on that end. I doubt that anything can be changed in Godot to alleviate that issue unfortunately :(
