### ISSUE TITLE
[GODOT3] Bug Packet TCP/UDP

### ISSUE THREAD

**Issue by Tilican** [godotengine/godot#12848]
Hi
I use this [Godot API](http://docs.godotengine.org/en/latest/learning/features/misc/binary_serialization_api.html)

When i run this script :

```python
#tcp.gd
extends SceneTree

var connection = null
var peerstream = null
var test = null

func _init():
	print("Start client TCP")
	# Connect
	connection = StreamPeerTCP.new()
	connection.connect_to_host("127.0.0.1", 8080)
	peerstream = PacketPeerStream.new()
	peerstream.set_stream_peer(connection)
	peerstream.put_var([12,13,14,15])

	while(true):
	    if connection.is_connected_to_host() && connection.get_available_bytes() >0:
            test = connection.get_var()
            print(typeof(test))
            print(test)
            quit()
```

I get a packetId 19 (input event) but normally packetId 21

And with
```python
peerstream.put_var({'test': 3})
```

I get a packetId 18 => object (unsupported) but normally packetId 20

**Comment by Noshyaar** [comment]
That page is outdated. See http://docs.godotengine.org/en/latest/classes/class_@global%20scope.html for variant type constants.

```
TYPE_DICTIONARY = 18 — Variable is of type Dictionary.
TYPE_ARRAY = 19 — Variable is of type Array.
TYPE_RAW_ARRAY = 20 — Variable is of type PoolByteArray.
TYPE_INT_ARRAY = 21 — Variable is of type PoolIntArray.
```

**Comment by Tilican** [comment]
Thx, but where i can see the encoding method for godot 3 ?

**Comment by Noshyaar** [comment]
Probably the same page for now. I don't think there're significant changes to the encoding. It's that the type constants changed a bit.

**Comment by Tilican** [comment]
i'll add it on [gd-com](https://www.npmjs.com/package/gd-com)
thx 👍

**Comment by Noshyaar** [comment]
I've filed an [issue](https://github.com/godotengine/godot-docs/issues/585) in docs repo.
