### ISSUE TITLE
3.0 Unable to generate Mono glue.

### ISSUE THREAD

**Issue by olejr** [godotengine/godot#12849]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 x64, Godot 3.0 master.

**Issue description:**
Unless there's a new undocumented way to build godot with C# support, doing this:
`scons p=windows tools=yes module_mono_enabled=yes mono_glue=no`
`bin\godot.windows.tools.64.mono.exe --generate-mono-glue modules/mono/glue`
Doesn't generate the glue code anymore.
Last commit that worked was ed57f0a as far as I can see.

**Comment by DillonHemphill** [comment]
Working fine on x11 with 
scons p=x11 tools=yes module_mono_enabled=yes mono_glue=no
bin/godot.x11.tools.64 --generate-mono-glue modules/mono/glue

**Comment by nextdimension** [comment]
Im on win10 x64 godot 3.0 master and its working fine.

**Comment by olejr** [comment]
Well then it might be something very wrong with my setup.
Because I'm one _mono_glue.gen.cpp_ file short inside the mono/glue folder.
And if/when, after those two above, I do:
`scons p=windows target=release_debug tools=yes module_mono_enabled=yes`
It ends with a big:
```
Creating library bin\godot.windows.opt.tools.64.mono.lib and object bin\godot.windows.opt.tools.64.mono.exp
modules.windows.opt.tools.64.mono.lib(gd_mono.windows.opt.tools.64.mono.obj) : error LNK2019: unresolved external symbol "unsigned __int64 __cdecl GodotSharpBindings::get_core_api_hash(void)" (?get_core_api_hash@GodotSharpBindings@@YA_KXZ) referenced in function "private: void __cdecl GDMono::_initialize_and_check_api_hashes(void)" (?_initialize_and_check_api_hashes@GDMono@@AEAAXXZ)
modules.windows.opt.tools.64.mono.lib(gd_mono.windows.opt.tools.64.mono.obj) : error LNK2019: unresolved external symbol "unsigned __int64 __cdecl GodotSharpBindings::get_editor_api_hash(void)" (?get_editor_api_hash@GodotSharpBindings@@YA_KXZ) referenced in function "private: void __cdecl GDMono::_initialize_and_check_api_hashes(void)" (?_initialize_and_check_api_hashes@GDMono@@AEAAXXZ)
modules.windows.opt.tools.64.mono.lib(gd_mono.windows.opt.tools.64.mono.obj) : error LNK2019: unresolved external symbol "void __cdecl GodotSharpBindings::register_generated_icalls(void)" (?register_generated_icalls@GodotSharpBindings@@YAXXZ) referenced in function "private: void __cdecl GDMono::_register_internal_calls(void)" (?_register_internal_calls@GDMono@@AEAAXXZ)
bin\godot.windows.opt.tools.64.mono.exe : fatal error LNK1120: 3 unresolved externals
scons: *** [bin\godot.windows.opt.tools.64.mono.exe] Error 1120
scons: building terminated because of errors.
```

**Comment by nextdimension** [comment]
Do you have the proper windows .net build tools and mono installed? I was getting the same error at first until i rectified this irc.

**Comment by olejr** [comment]
Well I've been building and using godot with C# up until november 7.
But when I updated the repo to head earlier this evening, and tried to build it failed.
And going back to commit  ed57f0a atleast generate the required files in the mono/glue folder..

Anyway, to late for further testing tonight..
