### ISSUE TITLE
move_and_slide() sliding does not work on Trimesh collision shapes in Bullet physics mode.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#12847]
Xubuntu 17.10 64bit, Godot v3.0.alpha.custom_build.35e7f99.

Issue description:
As the title says, when using the new Bullet physics engine, sliding fails to work when colliding with a Trimesh collision shape.
Switching back to GodotPhysics restores the expected behavior.

Steps to reproduce:
1 - Make sure to set 3D physics mode to Bullet in project settings.
2 - Move a KinematicBody node using move_and_slide against a Trimesh collision shape.

I do not have an example project to share, but an easy way to reproduce this is to test it in the Kinematic Character 3D demo.
Just add a new Trimesh collider to the scene, and try to slide against it.

**Comment by leiget** [comment]
Yeah, same problem here, but they are probably working on it.

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by leiget** [comment]
Yes. Here's a test project: 
[3D_MoveAndSlide_On_RigidBody.zip](https://github.com/godotengine/godot/files/1632014/3D_MoveAndSlide_On_RigidBody.zip)

**Comment by EzraT** [comment]
This issue does not seem to be present anymore in Godot 3.0 stable, I think this can be closed.
