### ISSUE TITLE
Function is_on_floor() in KinematicBody no longer working

### ISSUE THREAD

**Issue by HummusSamurai** [godotengine/godot#12853]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 25, master branch

**Issue description:**
Using is_on_floor() in KinematicBody always reports false.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by timoschwarzer** [comment]
May be related to the recent migration to the Bullet physics engine. Does the method still not work if you set the physics engine to Godot internal in the project settings?

**Comment by HummusSamurai** [comment]
Yes the method works properly when using old Godot physics.

**Comment by AndreaCatania** [comment]
I noticed it, but in my tests the problem was the shadow of cube, the cube
was attached perfectly to the floor.

I'll test it soon, in the meanwhile can you assert it please?

**Comment by HummusSamurai** [comment]
@AndreaCatania I don't mean that the cube is not touching the floor visually, I mean that I cannot use the function on_floor() for collision detection e.g. for moving the cube only when it is on the floor.

**Comment by AndreaCatania** [comment]
Oh.. I'll fix it soon. Thanks for report

**Comment by HummusSamurai** [comment]
@AndreaCatania I added a print() function and I can confirm that is_on_floor() is always reporting false.

**Comment by AndreaCatania** [comment]
Fixed: https://github.com/godotengine/godot/pull/13046

**Comment by HummusSamurai** [comment]
Thank you!
