### ISSUE TITLE
OBJ mesh does not receive updates when it must

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#12866]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
(tested on linux), latest master

**Issue description:**
 The OBJ mesh resources does not receive update when re-export from Blender happen. After first automatic import, it cannot be updated even by using reimport button. Only after complete delete asset and export from Blender again, mesh gets its update.

**Comment by Chaosus** [comment]
I afraid not, it still an issue

**Comment by djrm** [comment]
The case where they dont work, is when you have multiple materials, somehow, it produces crashes or unexpected results, i will have to dig deeper.

**Comment by djrm** [comment]
if you still have problems with this please attach your model, thanks.
