### ISSUE TITLE
Changing a color's transparency will change the color in the editor.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#12877]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64bit, GeForce GTX 960 - Godot 3.0 19b1ff0

**Issue description:**
This only happens inside the editor, in game the colors are correct. When changing the alpha value of a color it also visually changes the color itself. In the gif and project below both the square and the background are the same color, except that the square's alpha value is being changed. While the alpha value is below 100% and above 0% it's not the correct color. There should be no visible square during the animation, just like it is in game.

![](https://i.imgur.com/6pxoFNE.gif)

**Link to minimal example project:**
[alpha_problems.zip](https://github.com/godotengine/godot/files/1465227/alpha_problems.zip)

**Comment by akien-mga** [comment]
Can this still be reproduced in the current master branch?

**Comment by CowThing** [comment]
This still happens in da4edf8

**Comment by volzhs** [comment]
@CowThing would you check it again with current head? it seems fixed.

**Comment by akien-mga** [comment]
Fixed by 2cde466ebdb.
