### ISSUE TITLE
Ctrl+S to save a shader

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12878]
After loosing all work I did on a shader, I realized that if i don't save a scene, the shader I was writing would not be saved, even if I made it a .tres resource separated from the scene.

Just like scripts, I think it would be great if Ctrl+S could save an edited shader when the shader editor has focus, especially if this shader already has a file where it can be saved to. (note that this shader can also be not referenced in any open scene).

I know that Ctrl+S is supposed to save the scene and everything, but in my workflow I've set Ctrl+S to save contextually, so I replaced the Ctrl+Alt+S of the script editor by Ctrl+S, and removed it for scene saving, while I now use click menus to save scenes. The shader looks like a script editor, but for some reason only saving the scene makes it saved...

**Comment by Chaosus** [comment]
CTRL + S now worked correctly and you can save the shader by using it. _Closed by bugsquad._

**Comment by Zylann** [comment]
This is not fixed, read the issue again :)

**Comment by Chaosus** [comment]
Sorry @Zylann

**Comment by vmedea** [comment]
It would be nice if the Ctrl-Alt-S shortcut that works in the script editor also worked for the shader editor. I'm a big proponent of saving every little change (and committing it to git for good measure), it's faster than saving the entire scene. And it's slightly irking that it prints a literal "S" if you try :smile:

**Comment by KoBeWi** [comment]
Resolved in the new shader editor.
