### ISSUE TITLE
Signal connection dialog ignore indentation settings when creating function

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#12872]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 alpha

**Issue description:**
When you use the signal connection dialog to create a function, it will always create a function using tab as indentation for the `pass` keyword. This is troublesome if you don't delete the keyword or if you delete it without clearing the blank space before it.

**Steps to reproduce:**
1. Change the indent to spaces in the Editor Settings.
2. Create a new function with the signal connection dialog from the Node dock.

**Comment by YeldhamDev** [comment]
Just fixed it, will pull later when I'm back home.
