### ISSUE TITLE
Need a way to teleport editor camera to selected node.

### ISSUE THREAD

**Issue by dunyakilavuz** [godotengine/godot#12871]
A simple double click on a node under the scene view should teleport the editor camera to the node. It would be way simpler to navigate in 3D.

Like in the images below.

-Before double click-
![before](https://user-images.githubusercontent.com/9383042/32703880-66347306-c80d-11e7-9e07-60f88b2816e1.jpg)

-After double click-
![after](https://user-images.githubusercontent.com/9383042/32703879-6612bfd6-c80d-11e7-94d5-b5be1d91a85c.jpg)

**Comment by mrcdk** [comment]
A `Node` doesn't hold any transform information so it won't work. Anything that has transform information (anything inheriting from or being a `Spatial`, `Control` or `Node2D`) will focus when double clicking on the icon.

**Comment by dunyakilavuz** [comment]
I guess that makes sense, thanks for your reply @mrcdk
