### ISSUE TITLE
Editor camera, right click & drag - rotation is unpredictable.

### ISSUE THREAD

**Issue by dunyakilavuz** [godotengine/godot#12873]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 x64, Godot 3.0 alpha 2

**Issue description:**
A right click and drag to rotate the editor camera, rotates the camera to unpredictable directions,

**Steps to reproduce:**
Right click on your scene to rotate editor camera, while mouse is moving.

**Comment by Calinou** [comment]
When you hold the right mouse button, freelook mouse is enabled (use <kbd>W/A/S/D/Q/E</kbd> to move). To pan the camera, hold the middle mouse button and move the mouse.
