### ISSUE TITLE
Speeding up travis a bit

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#12887]
I was trying to see if I could speed up things a bit with travis, and also to find a workaround or something to enable the slot for Android.

Basically what I ended up doing was writing scripts to install the Android SDK/NDK, Scons and ccache "by hand" on macOS, so that the jobs wouldn't have to wait for homebrew to get updated, and then download the formulas, etc.

Also enabled ccache for iOS and Android, and wrote a script for linux to download the same Android SDK/NDK, then changed the platform to build the Android exporter to linux.

Now the two slots available for macOS are occupied with the editor and the iOS export template, and the remaining slots are for the static analysis, the linux X11 editor, and the Android export template.

The results can be seen [here](https://travis-ci.org/rraallvv/godot/branches) for the branches osx_android_travis ([#164](https://travis-ci.org/rraallvv/godot/builds/301192757)) and osx_android_travis_2.1 ([#165](https://travis-ci.org/rraallvv/godot/builds/301192775))

I'd love feedback on the matters to see if this can be merged.

Cheers!

**Comment by akien-mga** [comment]
Fixed by #12885.
