### ISSUE TITLE
RichTextLabel tag stack overwritten by bbcode_text manipulation.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#12881]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot 3.0 master

**Issue description:**
If you use `append_bbcode(...)`, any `push_*` function, or the `pop` function to manipulate the internal tag stack of `RichTextLabel`, all of those changes are currently being cleared whenever someone directly edits the `bbcode_text` property

**Steps to reproduce:**
Create project with `RichTextLabel` root node. Add a script to it:

    # RichTextLabel.gd
    func _ready():
        push_image(load("res://icon.png")
        # bbcode_text += "hi"

Run the scene with and without the second line commented and you'll find that the image is missing (removed) when you manipulate `bbcode_text`.

**Comment by theoway** [comment]
From the documentation:
It is unadvised to use += operator with bbcode_text (e.g. bbcode_text += "some string") as it replaces the whole text and can cause slowdowns. Use append_bbcode for adding text instead.

**Comment by willnationsdev** [comment]
@theoway Is that an intended design choice though? Or would it make sense for the `+=` operator to execute the same logic as `append_bbcode`?

**Comment by theoway** [comment]
> @theoway Is that an intended design choice though? Or would it make sense for the `+=` operator to execute the same logic as `append_bbcode`?

It does make sense for the `+=` operator to work as `append_bbcode()` but the current design doesn't allow that. I don't think there's a use case for that as there's already `append_bbcode()`.
