### ISSUE TITLE
Limit visibility of lights

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1288]
In scenario, when we need to hide geometry to show what's inside, in case, when we assume geometry is still there (character enters house and we remove wall of the house to show what happens inside, but the wall is physically assumed here, we just get it out of the way of our sight), but
light is get away.
Example:. Darkness outside. Character enters lit house. When he (lets tame our RigidBody) opens the door, we see some light getting through. He closes door behind, and everything is dark again. But now we want to see what happens in house, and it is not first-person game. So we do only thing we can - remove house wall to see what happens inside, and all surrounded darkness becomes lit, which is wrong, as we really did not remove wall, we just showing what happens inside house.

**Comment by bojidar-bg** [comment]
If you make the wall with so that its normals are pointed to the inside, then you wil be able to see through it (the material should not be double-sided) and the lamp inside will see the wall, making a shadow.

**Comment by slapin** [comment]
Ah, thanks! Is it possible to dynamically swap normals? Or can I replace mesh for another for time being?

**Comment by bojidar-bg** [comment]
I can think of two ways to do this:
1. Have two meshes (maybe different objects) and swap them.
2. Use a double-sided material while the player is out, otherwise one-sided (Untested).

**Comment by bojidar-bg** [comment]
@slapin maybe you should close this issue?

**Comment by okamstudio** [comment]
i want to add it, but didn't have time to do this yet

On Mon, Mar 16, 2015 at 5:40 PM, Bojidar Marinov <notifications@github.com>
wrote:

> @slapin <https://github.com/slapin> maybe you should close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1288#issuecomment-81926201>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment]
Is this still relevant in the current master branch?

**Comment by reduz** [comment]
This is fully implemented in current master branch, so closing this. Please test it well anyway.
