### ISSUE TITLE
Float uniform parameters not applied to shaders

### ISSUE THREAD

**Issue by Ohmnivore** [godotengine/godot#12888]
**Setup**
* Windows 10 64-bit
* Godot 2.1.4
* DUAL-GTX 1060
* NVIDIA GeForce GameReady 388.13 driver

**Issue description:**
I'm trying to make an impact bounce vertex shader. Some float uniforms don't seem to update, and always remain 0.

**Steps to reproduce:**
This is my vertex shader:
```
uniform vec3 impact_point;
uniform vec3 impact_direction;
uniform float impact_radius;
uniform float impact_strength;

float dist = distance(SRC_VERTEX, impact_point);
dist = clamp(dist, 0.0, 1.2);
dist = 1.2 - dist;
vec3 offset = dist * 1.0 * normalize(impact_direction);

vec4 new_vertex = vec4(SRC_VERTEX.xyz, 1.0);
new_vertex.xyz += offset;
VERTEX = (MODELVIEW_MATRIX * new_vertex).xyz;
```

If I replace **1.0** by **impact_strength** or **1.2** by **impact_radius** then they will be 0 and the bounce shader will have no effect.

The uniforms are set as follows during **func _process**:
```
mat.set_shader_param("impact_point", Vector3(1.0, 0.0, 0.0))
mat.set_shader_param("impact_direction", Vector3(1.0, 0.0, 0.0))
mat.set_shader_param("impact_radius", 1.2)
mat.set_shader_param("impact_stength", 6.0)
print(mat.get_shader_param("impact_stength"))
```

It prints **6.0**, and the vectors are correctly set and read by the shader at runtime. Only the floats seem to be missing.

**Link to minimal example project:**
[GODOT.zip](https://github.com/godotengine/godot/files/1465618/GODOT.zip)

**Comment by Ohmnivore** [comment]
Here are the project files where I replaced **1.0** by **impact_strength** and **1.2** by **impact_radius** in the vertex shader.
[GODOT.zip](https://github.com/godotengine/godot/files/1465628/GODOT.zip)

Hardcoded:
![image](https://user-images.githubusercontent.com/3769354/32710185-4005d408-c804-11e7-8d3c-ae52d936fab1.png)

Using uniforms, with bug:
![image](https://user-images.githubusercontent.com/3769354/32710230-84411c7c-c804-11e7-8328-53331edc8292.png)

The reason why the red surface is curved in the last image is because I've set that one through the editor, the other materials are set through a script.

**Comment by Ohmnivore** [comment]
Correction: it looks like the only uniform not being updated is **impact_strength**, **impact_radius** is fine. **impact_strength** is also the last declared uniform, might be related.

**Comment by Ohmnivore** [comment]
Actually, I can't change **impact_strength** in the editor either. Curiously, it seems to be stuck at a prior value I assigned and doesn't change (irrespective of the value displayed in the editor).

**Comment by Ohmnivore** [comment]
I renamed **impact_strength** to **impact_intensity**, and now everything works well. My immediate issue is resolved, but I'll leave it open in case you would like to dig deeper.

**Comment by Tugsav** [comment]
> uniform float impact_strength;

> mat.set_shader_param("impact_stength", 6.0)

You seem to have written impact_stength instead of impact_strength.
not sure if this is only present in the issue description, but this typo would definately be the cause of the issue

**Comment by Ohmnivore** [comment]
Wow you're right. What a typo.
