### ISSUE TITLE
Adding a uniform starting by '_' in a shader breaks rendering

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12880]
Godot 3.0 alpha2
Windows 10 64 bits
nVidia 940M

Repro:
1) Create a scene with a sprite in it and a texture on it (the default icon will do)
2) Create a ShaderMaterial, save it to a file
3) Cretae a Shader, save it to a file
4) Write this code into the shader:
```glsl
shader_type canvas_item;

uniform sampler2D _indices;

void fragment() {
	COLOR = vec4(1,0,0,1);
}
```
5) Assign the material on the Sprite
6) Notice rendering is broken:
![image](https://user-images.githubusercontent.com/1311555/32705495-61a40cae-c815-11e7-9ea5-7ea2a65d4d14.png)

The log is spammed by this:
```
ERROR: _display_error_with_code: CanvasShaderGLES3: Vertex Program Compilation Failed:
0(107) : error C7528: OpenGL reserves names containing '__'

   At: drivers\gles3\shader_gles3.cpp:167
ERROR: ShaderGLES3::get_current_version: Method/Function Failed, returning: 0
   At: drivers\gles3\shader_gles3.cpp:368
ERROR: ShaderGLES3::bind: Condition ' !version ' is true. returned: false
   At: drivers\gles3\shader_gles3.cpp:122
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles3/shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles3/shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles3/shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles3/shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles3/shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles3/shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles3/shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles3/shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: .\drivers/gles3/shader_gles3.h:376
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: GL_INVALID_OPERATION error generated. No active program.
   At: drivers\gles3\rasterizer_gles3.cpp:122
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: GL_INVALID_OPERATION error generated. No active program.
   At: drivers\gles3\rasterizer_gles3.cpp:122
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: GL_INVALID_OPERATION error generated. No active program.
   At: drivers\gles3\rasterizer_gles3.cpp:122
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: GL_INVALID_OPERATION error generated. No active program.
   At: drivers\gles3\rasterizer_gles3.cpp:122
```

It took me some lucky scrolling to find out that the issue was only caused by the '_' at the beginning of my uniform.

**Comment by eon-s** [comment]
If `_` is so problematic (even in 2.x) the shader variables should be renamed in other way, like `v_`.

**Comment by BastiaanOlij** [comment]
Looks to me your problem start here:
```error C7528: OpenGL reserves names containing '__'```

Thats hardly a Godot issue, seems OpenGL itself doesn't like you starting variable names with an underscore. I guess Godot could automatically rename things that are reserved or maybe detect them in editor an already highlight that you can't use that name...

**Comment by eon-s** [comment]
Is because Godot adds a `_` to the names, that was affecting some variable names (on android) on 2.1 and here adds a second `_` making it use the reserved characters.

**Comment by Zylann** [comment]
My shader is valid GLSL, Godot made it wrong, and didn't highlight it to me anyways, so I think it's either a bug or at least bad UX :p

**Comment by BastiaanOlij** [comment]
Ah, now the double _ makes sense. So the first _ is your code and the second is added by Godot.

Yeah its not something people will grasp. I never used snake case before I started working in Godot so I never ran into this :)

**Comment by 648trindade** [comment]
Still reproducible in 3.0 stable version

Apparently Godot renames variables adding `m_` prefix, making variable names that contain one underscore at beggining contain two underscores

I don't know which GLSL version the editor uses, but this is on GLSL 4.3 specification ([page 18](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.30.pdf)): 

> All macro names containing two consecutive underscores ( __ ) are reserved for future use as predefined macro names.

And from 4.4 ([page 22](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.40.pdf)) to latest (4.6)

> [...] In addition, all identifiers containing two consecutive underscores ( __ ) are reserved for use by underlying software layers.  Defining such a name in a shader does not itself result in an error, but may result in unintended behaviors that stem from having multiple definitions of the same name.

I think that godot should add just `m` as prefix, or replace underscore at beggining of variable names with other character, but this is a problematic aproach, since there can possible be another variable with such name. 
Godot should correct variable with two underscores at the middle of variable name too. It's a terrible practice to add two underscores at the middle of name, i know, but always there someone that do this.

**Comment by DavidSichma** [comment]
This issue also affects VisualShaders as some variables in the auto-generated code have a leading underscore.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
