### ISSUE TITLE
Can not build for iPhone X simulator

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#12890]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1 
maxOS High Sierra 10.13.1

**Issue description:**

**Steps to reproduce:**
$ scons p=iphone arch=x86 target=debug
 get the godot.iphone.debug.x86 into the Xcode project
Modify the executable file  to godot.iphone.debug.x86
When tried to run in the simulator in Xcode 9, it failed with 
godot.iphone.debug.x86 does not have an architecture that Simulator iPhone X can execute.

If I modified the detect.py file, change the i386 to x86_64, change 32 to 64, it can run without error, but, nothing was displayed.

**Link to minimal example project:**

**Comment by alexzheng** [comment]
I think not just iPhone X simulator.

**Comment by akien-mga** [comment]
Well that's what your message mentions, and I know that it works/worked fine on earlier versions with a 32-bit binary.

**Comment by alexzheng** [comment]
Yes, 64-bits is missed.

**Comment by alexzheng** [comment]
For simulator iPhone 7 and lower, this error message is 
dyld: dyld_sim is not compatible with the loaded process, likely due to architecture mismatch

**Comment by samgreen** [comment]
I don't think is an issue any longer.

**Comment by pst123** [comment]
怎么解决

**Comment by samgreen** [comment]
更新到3.1
