### ISSUE TITLE
 GDNative: missing symbols (mono disabled)

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#12897]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
linux, godot3 tip

**Issue description:**

The godot binary is missing Variant? symbols, when compiled
without mono.

**Steps to reproduce:**
Attach the `libgodot.so` to a Node. Works with mono enabled binary,
but is broken otherwise:
```
ERROR: open_dynamic_library: Can't open dynamic library: libgodot.so. Error: libgodot.so: undefined symbol: godot_rect3_get_shortest_axis_size
   At: drivers/unix/os_unix.cpp:407.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:346.
ERROR: init_library: No godot_nativescript_init in "res://libgodot.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1016.
ERROR: init_library:  does not have a library for the current platform
   At: modules/gdnative/nativescript/nativescript.cpp:993.
```

@karroffelI I could not find the place where the GDNative symbols are discarded,
 ```
platform/x11/SCsub:
-    os.system('strip --strip-debug --strip-unneeded %s' % (target[0]))
+    os.system('strip --strip-debug %s' % (target[0]))
```
didn't help.

**Link to minimal example project:**

[libgodot.so.zip](https://github.com/godotengine/godot/files/1466609/libgodot.so.zip)

**Comment by karroffel** [comment]
Your libgodot.so should use the API struct handed in the `godot_gdnative_init_options *` from the `godot_gdnative_init` function. 

This is because classic linking causes problems on Windows, so we changed it that the API should get accessed using that struct of pointers.

**Comment by capnm** [comment]
Had no luck with that too (and it's hard to debug).

Does https://github.com/GodotNativeTools/GDNative-demos/tree/master/c/SimpleDemo
work for you? Could you craft some c Example that uses this api, compiles and does not crash in runtime? Thanks.
