### ISSUE TITLE
Having a plus sign next to the scene tab for creating new scene

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#12900]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0

**Issue description:**
I think it is more direct to have a plus sign for adding new scene which is not creating a more crowded UI. It is just so natural that I want to click at that spot and find nothing there.

![2017-11-13 20 00 22](https://user-images.githubusercontent.com/10883749/32726129-cbfc1e6e-c8b2-11e7-8fd4-22f60690848b.png)

![add](https://user-images.githubusercontent.com/10883749/32726105-b0aceab2-c8b2-11e7-9b37-44c8fbaafa67.png)

**Comment by Noshyaar** [comment]
Although it is currently possible to double-click on the empty space at the tab header to create new scene, this would be a nice visual cue.

**Comment by ZX-WT** [comment]
you can double-click it? I didn't know that, good to know.(I should know that someone would have implemented it already, I love godot :) ) Then, there definitely should be a sign for indication.

**Comment by CowThing** [comment]
It would be nice if there was a way to quickly make a new inherited scene too.

**Comment by HummusSamurai** [comment]
@CowThing What do you mean?

**Comment by Zireael07** [comment]
Probably something like right click on scene tab title -> Inherit this scene?

**Comment by HummusSamurai** [comment]
@Zireael07 I get that part but I can't wrap my head around what is an "inherited scene".

**Comment by CowThing** [comment]
An inherited scene is a new scene that inherits from another scene. Right now I think the only way to create a new inherited scene is to go to the scene menu and select it, then select the base scene to inherit from. But right clicking on an open scene tab and being able to instantly create an inherited scene from it, or right clicking on a scene in the file system panel and inheriting that way would be useful.

Should this inherited scene suggestion be in its own issue?

**Comment by vnen** [comment]
@CowThing better open a separate issue, it's not directly related to this.

**Comment by HummusSamurai** [comment]
@CowThing Oh I didn't even know that was possible. :b 

I just tried it and I think "inherited" is confusing, it's more like a "new duplicate" scene. Inheritance implies having a reference to the parent.
