### ISSUE TITLE
Comment line hotkey doesn't work in script editor, when shader editor opened

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#12916]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
all, latest master

**Issue description:**
Comment line (CTRL+K) hotkey in script editor doesn't work when shader editor opened. Instead shader edtior have priority and push comment to itself, regardless of focus.

**Comment by capnm** [comment]
FYI, this is still broken in current rc1 and master 86d6a72c9745bd15e3217d63b2cc5ba73fe4ad34

**Comment by KoBeWi** [comment]
Closing in favor of #17591, which has more details.
