### ISSUE TITLE
Android builds on a 100% free software stack

### ISSUE THREAD

**Issue by fluffrabbit** [godotengine/godot#12914]
Recently I have become rather disturbed by the proliferation of components that do not meet the [GNU definition of free software](https://www.gnu.org/philosophy/free-sw.html). Even the Android SDK, which is in service of a (mostly) free software platform, forces users to agree to a non-free EULA and install it in a way that is reminiscent of the proprietary age. The desktop is fine (if you use Linux/BSD) but mobile platforms seem to be tied to a lot of proprietary parties.

In the future, iOS and UWP will be FLOSS just like Linux. Win32 will no longer exist. Proprietary software such as Xcode will be a thing of the past. Until then, I feel that it would be best to gradually move away from offending components.

My current focus under this broader goal is on Android builds. Godot seems to depend on several mysterious codes for this platform that come from Google's official Android SDK, and to break away from that a free software version should be used. Two come to mind: the somewhat outdated [Replicant SDK](https://redmine.replicant.us/projects/replicant/wiki/SDK) and the [Debian android-sdk](https://bits.debian.org/2017/03/build-android-apps-with-debian.html) which currently does not ship a version of the NDK (that is downloaded separately from Google).

I'll come back for the technical discussion as it can be a source of frustration. Neither free SDK is yet building Godot out-of-the-box though AFAIK there is no reason why both couldn't work, it's just a question of time investment.

**Comment by groud** [comment]
> Neither free SDK is yet building Godot out-of-the-box though AFAIK there is no reason why both couldn't work, it's just a question of time investment.

Yes, feel free to contribute :)

**Comment by davidpgil** [comment]
Is FSF.org [page](https://directory.fsf.org/wiki/Godot) for Godot still accurate? I was under the assumption that Godot was fully free (as in free speech/ as a human right) software? If it's not I think I need to chuck this software. Would anyone help clarify this for me?

**Comment by groud** [comment]
> Is FSF.org page for Godot still accurate? I was under the assumption that Godot was fully free (as in free speech/ as a human right) software? If it's not I think I need to chuck this software. Would anyone help clarify this for me?

You don't have to install Android's SDK or anything else to use Godot, it's only mandatory if you want to export to Android. If you don't want Android export, don't install it.
Everything which is on Godot's repository is fully under MIT license. So, yes, it's a free software.

**Comment by akien-mga** [comment]
> Is FSF.org page for Godot still accurate? I was under the assumption that Godot was fully free (as in free speech/ as a human right) software? If it's not I think I need to chuck this software. Would anyone help clarify this for me?

Godot is as free as it can be - it can't make thirdparty toolchains necessary to build its code free if their distributors (Google, Microsoft) decided to make those toolchains proprietary.

So yes, if you want to export your Godot game to the nonfree Android platform, you need the nonfree Android toolchains from Google (SDK and NDK). This issue is about seeing whether the free version of the Android SDK provided by Debian devs could be used in the build process - but since there is no free NDK, there would still be nonfree components.

Same goes if you build Godot binaries using Visual Studio / MSVC for Windows or UWP. Or iOS binaries with XCode.

**Comment by davidpgil** [comment]
Sorry I overreacted purely out of emotion upon seeing this post. It says this clearly in the description of Godot.

![image](https://user-images.githubusercontent.com/1891288/32784629-5f3687e0-c91d-11e7-947a-ffa6fe79523b.png)

However, I wish the LICENSE.txt file said something about the MIT license in it. Thats where I looked and all I saw was copyright info.

![image](https://user-images.githubusercontent.com/1891288/32784669-743ac7c8-c91d-11e7-94f2-f93e46fa4fc1.png)

**Comment by groud** [comment]
Well, the text just under the copyright notice **IS** the [MIT licence](https://opensource.org/licenses/MIT) .

**Comment by davidpgil** [comment]
Haha, I am definitely not familiar with these things apparently. Sorry if my concern is highjacking this thread. On that note - YEAH! **Android builds on a 100% free software stack**! Let's goooooo!!!

**Comment by n-pigeon** [comment]
Godot is fully FLOSS and even more L than GPL software. :)

**Comment by fluffrabbit** [comment]
>if you want to export your Godot game to the nonfree Android platform, you need the nonfree Android toolchains from Google

Not technically true AFAIK. You need `ant`, `jarsigner`, `adb`, and maybe a couple tools I'm forgetting, all of them FLOSS, if you are a Godot Android end user/developer. If you want to build Godot Android from source you must use the Google tools, which is how the Android export templates are currently built.

I feel like an idiot for not fully understanding the Gradle build system, and understanding it is necessary for the sorcery involved in adding this functionality. Even ignoring that the official NDK is over 700 MB in size and not entirely free, just telling Gradle where the softwares are and how to use them is a process.

Long story short, `build.gradle.template` is the main file that tells Gradle how to build the APK.

[Debian specifies](https://bits.debian.org/2017/03/build-android-apps-with-debian.html) SDK platform 23 and build tools 24.0.0. However, they do not specify much else. Through trial and error I have deduced a working value of 2.2.0 for the Gradle gizmos, which seems to work fine with build tools 24. However, the Android Support dependency is nonfree and Godot's `build.gradle.template` has this to say about it:

>can be removed if minSdkVersion 16 and modify DownloadNotification.java & V14CustomNotification.java

I tried that, but it's still complaining about Android Support. It's not used anymore as you will see in the attached diff (which you can apply to your local master). The only hitch with removing Android Support libs (Google's *Compat classes) is it breaks Godot on Android 4.0 and earlier, requiring 4.1+. Godot 3 currently requires Android 4.3+ due to GLES 3.

Anyhow, it's probably close to working.

On Debian or Ubuntu, `sudo apt install android-sdk android-sdk-platform-23 google-android-ndk-installer`

Add this to your `.profile` or enter it into the terminal every time:

`
export ANDROID_HOME=/usr/lib/android-sdk
export ANDROID_NDK_ROOT=/usr/lib/android-ndk
export ANDROID_NDK_HOME=$ANDROID_NDK_ROOT
`

Make sure your system is set up such that you can export for Android using the Godot GUI, which means that in conjunction with the above packages and the standard build tools you have everything you need. Clone the Godot source repo, copy the attached diff into the folder and `git apply ugh.diff`, then try to compile:

`scons platform=android target=release`

The above line can take about an hour to execute, so it's a chance to have a snack or take a nap.

`
cd platform/android/java
./gradlew build
`

Then get this error:

`FAILURE: Build failed with an exception.`
` What went wrong:`
`A problem occurred configuring root project 'java'.`
`> You have not accepted the license agreements of the following SDK components:`
`  [Android Support Repository].`
`  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
`

This message [can also mean](https://discuss.circleci.com/t/need-to-accept-license-agreement-for-android-tools/6181) that a library simply isn't there, and indeed Debian doesn't ship Android Support. Question is, why is it included at all? I thought I removed it from the dependencies.


[deband1.diff.zip](https://github.com/godotengine/godot/files/1476882/deband1.diff.zip)

**Comment by fluffrabbit** [comment]
Another update. Attached is a diff to be applied to the virgin godot/master source tree.

If you followed the dev environment setup steps above you should be good to go for testing out this new diff so you can see it error. Also it's now using a Czeck external dependency (automatically downloaded via Gradle, hoping nobody minds).

A problem here is a disparity in components between Java 1.7 and Java 1.8. You wouldn't think it would be an issue but of course it is. Either builds with Debian's `android-sdk` are infeasible as OpenJDK 7 is no longer available, or my diff needs further improvement. (More likely the latter.)
[deband2.diff.zip](https://github.com/godotengine/godot/files/1485382/deband2.diff.zip)

**Comment by fluffrabbit** [comment]
A recent commit bumped the Android SDK version from 23 to 24, so here is the same diff as before plus it bumps it back one (Debian's SDK version is 23).

Still not building. I was unable to find any jar which was compiled for Java 1.8, which is puzzling in light of the error messages indicating otherwise. When hacking around with the 1.7 and 1.8 values in `build.gradle.template`, `NullPointerException`s are common. Not sure what it means.

[deband2.5.diff.zip](https://github.com/godotengine/godot/files/1488536/deband2.5.diff.zip)

**Comment by fluffrabbit** [comment]
I can't work on this anymore. Sorry.

Here are my conclusions:

Godot builds are currently made on Ubuntu 14, which does not have the necessary packages to make this possible. Debian (not Ubuntu) seems like the best bet, but even so the Godot build system was not designed for anything other than the tools that are currently documented via readthedocs.

I'd bet a pile of cash that the Replicant SDK builds it just fine, but discussions I had with Godot devs lead me to believe that Replicant is not desired and it should be either Google SDKs or Debian SDKs, and that's tough (as you can see in my posts above).

Godot is free software, but if Android isn't (which is debatable) then I guess nobody really needs to develop for it. Gripes aside, I'm not bitter, I'm just worn out. Sorry. Feel free to re-open if there is a way to do this.
