### ISSUE TITLE
Exported game crashes but not in editor

### ISSUE THREAD

**Issue by StianTheDark** [godotengine/godot#1291]
In my current project, the exported Windows executable crashes. It works completely fine in the editor, but when exported only the "boot image" appears and then a "Test.exe has stopped working".

PROJECT: https://www.dropbox.com/s/caiujrc668pcpdm/BuggyProject.7z
EXPORTED EXECUTABLE: https://www.dropbox.com/s/f6oae4i3o5ydyaw/Executable.exe

I use the stable release (1.0) hosted on godotengine.org, and I've used the export templates provided on the website the 17th of January. Everything has been done on Windows 8.1, and previous projects have been exported without trouble.

**Comment by the-mech** [comment]
did you export with 64bits on or off, mine projects only work when i export them in 32bit mode

**Comment by StianTheDark** [comment]
64-bit on, has worked before.

**Comment by UsernameIsAReservedWord** [comment]
export templates provided on the website the 17th of january ? I don't find such date release on the download page.
could you please provide a link of where you found them ?

**Comment by StianTheDark** [comment]
I meant, I downloaded them from the website on the 17th of January. I have no idea when they were originally released.

**Comment by kubecz3k** [comment]
This issue looks like problem with templates or eventually it's related to: https://github.com/godotengine/godot/issues/1926#issuecomment-156389673 (but didn't tested if it work the same way on windows export). I'm archiving this one.
