### ISSUE TITLE
Shader errors are still highlighted after being fixed in the shader editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12910]
Godot 3.0 alpha2
Windows 10 64 bits
nVidia 940M

When I write a shader, I often stop midway to think, or simply make mistakes. This produces compilation errors, which I fix quickly, but they stay highlighted in red in the shader editor until I fix all of them in a single edit. As long as at least one remains, every other stay shown even though they are fixed.
This one is bugging me for a while, and it can get pretty uncomfortable:

![image](https://user-images.githubusercontent.com/1311555/32752323-0c4bd0a2-c8c9-11e7-9cb1-d06f69663b51.png)

**Comment by ianb96** [comment]
pull request #12842 fixes this issue

**Comment by akien-mga** [comment]
Fixed by #12842.
