### ISSUE TITLE
Regression: Unable to modify default values of some options in Editor Settings

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12921]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
468567438974ccfea11bcd5525cdeece3e1e546a Ubuntu 17.04

**Issue description:**
I'm unable to modify any boolean value of options in `EditorSettings->Text Editor->Files`  

**Steps to reproduce:**
1. Open any project
2. Go to  `EditorSettings->Text Editor->Files`  
3. Change value in `Open dominant script on scene changes` option
4. Restart the editor and check if the value is still changed.

**Link to minimal example project:**

**Comment by akien-mga** [comment]
CC @djrm

**Comment by kubecz3k** [comment]
I removed  folder with godot config `~/.godot` and it seems to work for me now.. will test a little but if that's all that need to be done than I guess it's ok

**Comment by kubecz3k** [comment]
OK it seems the problem is probably quite user specific and it is workaround-able by resetting global settings (I removed editor_settings-3.tres).  At current moment I don't think that anyone who comes from 2.x at the time of beta/final will experience this issue (they will have fresh editor config file) . Also I assume it's not really reproducible for most of the people with provided reproduction steps - but that's only an assumption.
In any case I'm closing for now, if more people experience that issue please leave a comment
