### ISSUE TITLE
Segfault when scanning directories containing symlinks on Linux

### ISSUE THREAD

**Issue by erbridge** [godotengine/godot#1292]
I set `global/autoscan_project_path` to `"/home/user/devel"` and godot crashed with a segfault. Resetting it to `""` fixed the issue and it started normally.

**Comment by adolson** [comment]
Any errors in the console other than segfault? I use this feature all the time and never had a crash.

**Comment by erbridge** [comment]
I wasn't running from the console, and my WM didn't catch any output. I'll see if I can get any more info when I get a moment.

**Comment by erbridge** [comment]
Running from `master`:
```
bin/godot.x11.tools.64
opening pack /home/felix/devel/godot/bin/godot.x11.tools.64, -1, -1
opening pack /home/felix/devel/godot/data.pck, -1, -1
SCAN PROJECTS AT: /home/felix/devel
[1]    12826 segmentation fault (core dumped)  bin/godot.x11.tools.64
```

**Comment by adolson** [comment]
If you disable autoscan from your settings file and then manually scan that
directory, does it do the same thing?

**Comment by erbridge** [comment]
Yes it does, but it finds the demos fine if I scan the `godot` subdirectory instead. I'll see if I can find what's causing it to crash.

**Comment by erbridge** [comment]
So I think the problem is likely to be symlinks. Two of the subdirectories caused `godot` to crash. One was `browserify-shim`, which I traced to this particular directory: https://github.com/erbridge/browserify-shim/tree/master/examples/expose-jquery/node_modules. The other was an abandoned `cocos2d-x` project which also contains symlinks.

Sure enough, if I create an empty directory containing a symlink and scan it, `godot` crashes.

**Comment by akien-mga** [comment]
I just tried in the current master branch and could not reproduce the issue by scanning a directory that contains only a symlink to another directory with Godot projects. It kind of froze for half a second, but then succeeded to retrieve all projects from the symlink.
