### ISSUE TITLE
3.0 -  Too many files lead to slower opening

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#12939]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows7 x64 godot3.0a2

**Issue description:**
My project has more than 1000 sprites.
When I open editor,it reimport files very long time.
Can it just re import the changing files?
Or optimize the import steps?

**Comment by reduz** [comment]
Reimport happens only once. We will optimize it after 3.0, though

**Comment by capnm** [comment]
@reduz IMO it would help to not generate zillion useless `*.*.import` files for default settings …

**Comment by reduz** [comment]
@capnm these files are the only way to mark that the file was imported, so it's ok to generate them. They are parsed in a thread, so they don't affect times for opening the engine.

@sersoong This process will be throughly optimized after 3.0 is out.

**Comment by vnen** [comment]
I assume this was solved by bb83c7d.
