### ISSUE TITLE
move_to does not take into account scaling and parent position 

### ISSUE THREAD

**Issue by adfaure** [godotengine/godot#12933]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows (I think the behavior would be the same in Linux).
In godot 2.4.1 (last stable at this hour)

**Issue description:**
The function move_to from kinematicbody2d does not take into account
the scale and the current position of the 2D. 

For example, into my code in order to make move_to works as expected, it should work I add to 
call it like this: 

```gdscript
	if velocity.length() > left_dist:
		#bug move_to seems to ignore scaling
		pac.move_to(target_pos * get_scale() + self.get_pos())
	else:
		pac.move(velocity * get_scale())
```

**Steps to reproduce:**
Scale and move the scene, the move_to will not take it into account.

**Link to minimal example project:**
The scene from https://github.com/adfaure/gameoff/blob/master/minigames/pacman/Game.tscn
illustrates the issue. And the snippet I show above is from https://github.com/adfaure/gameoff/blob/master/minigames/pacman/Game.gd.

**Comment by eon-s** [comment]
Godot 2 I suppose?
What about using global position of the target?

ps: try to be more descriptive on the title and add the godot version.

**Comment by adfaure** [comment]
Oh, I think I understand, the issue may come from the call to map_to_world from the tileset.
This is my bad, I will close the issue.

@eon-s: You pointed the right thing, target_pos is relative to the position of the tilemap. Thanks!

**Comment by bojidar-bg** [comment]
Is this a bug, or was it a misunderstanding?

**Comment by adfaure** [comment]
A misunderstanding. I will close the issue. Sorry for the inconvenience.
