### ISSUE TITLE
2D Render issue

### ISSUE THREAD

**Issue by damarindra** [godotengine/godot#12943]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot master branch (v3, 6277e6d40a0f0e8c84470482400959fca4ff5ad8)

**Issue description:**
Look this gif, focus on the eye
![render_issue](https://user-images.githubusercontent.com/8519218/32818817-1825f292-c9f8-11e7-891f-15ff5c0d50f1.gif)
This only happens when the window size is high. The pixel is not consistent.

But when I try to low the window size by changing Shrink = 2, the pixel stay consistent
![render_perfect](https://user-images.githubusercontent.com/8519218/32818883-93dda97a-c9f8-11e7-8e1e-39cb7ec31c1b.gif)

Maybe I'm missing something? I included the project, so you can test it. Don't forget to play with Shrink

**Link to minimal example project:**
[GameOffJam.zip](https://github.com/godotengine/godot/files/1473413/GameOffJam.zip)

**Comment by damarindra** [comment]
For more info, I've tried and nothing happens:
- changing the stretch mode.
- Image Import setting
- Vsync
- pixel snap

**Comment by groud** [comment]
I would say this is normal, as the pixels of your sprite have to be drawn on the pixel of your screen. If your screen size is not an exact multiple of your game size, some lines of your game should have a little bit different amount of pixels to be drawn.

**Comment by damarindra** [comment]
@groud yes you are right, I've tried it and completely fine, thanks. Do we need to close this issue?
