### ISSUE TITLE
Crash on iOS 5.1.1 device.

### ISSUE THREAD

**Issue by umxprime** [godotengine/godot#1294]
I have a crash when running a simple scene on my iPad 1st gen with iOS 5.1.1

Here is the crash log :
Incident Identifier: EB91F81D-31D8-421B-9810-FD8697AEF54A
CrashReporter Key:   edc2e657e4ee50b933d8bcbd51e608e93660ad4a
Hardware Model:      iPad1,1
Process:         godot_opt.iphone [9221]
Path:            /var/mobile/Applications/5D36225E-E72B-4C78-9DF1-A40B62DB003B/godot_ios.app/godot_opt.iphone
Identifier:      godot_opt.iphone
Version:         ??? (???)
Code Type:       ARM (Native)
Parent Process:  launchd [1]

Date/Time:       2015-01-22 18:07:04.121 +0100
OS Version:      iPhone OS 5.1.1 (9B206)
Report Version:  104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00000000
Crashed Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   godot_opt.iphone              	0x00053314 0x47000 + 49940
1   UIKit                         	0x333a6c2a -[UIApplication _stopDeactivatingForReason:] + 182
2   UIKit                         	0x3339490e -[UIApplication _runWithURL:payload:launchOrientation:statusBarStyle:statusBarHidden:] + 714
3   UIKit                         	0x33362abc -[UIApplication handleEvent:withNewEvent:] + 1004
4   UIKit                         	0x33362560 -[UIApplication sendEvent:] + 48
5   UIKit                         	0x33361f34 _UIApplicationHandleEvent + 5820
6   GraphicsServices              	0x33954224 PurpleEventCallback + 876
7   CoreFoundation                	0x35c3651c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 32
8   CoreFoundation                	0x35c364be __CFRunLoopDoSource1 + 134
9   CoreFoundation                	0x35c3530c __CFRunLoopRun + 1364
10  CoreFoundation                	0x35bb849e CFRunLoopRunSpecific + 294
11  CoreFoundation                	0x35bb8366 CFRunLoopRunInMode + 98
12  UIKit                         	0x33393864 -[UIApplication _run] + 544
13  UIKit                         	0x33390cce UIApplicationMain + 1074
14  godot_opt.iphone              	0x0005288c 0x47000 + 47244
15  godot_opt.iphone              	0x0004d5d0 0x47000 + 26064

Thread 1 name:  Dispatch queue: com.apple.libdispatch-manager
Thread 1:
0   libsystem_kernel.dylib        	0x35cc83a8 kevent + 24
1   libdispatch.dylib             	0x33ffbea4 _dispatch_mgr_invoke + 708
2   libdispatch.dylib             	0x33ffbbc2 _dispatch_mgr_thread + 30

Thread 2:
0   libsystem_kernel.dylib        	0x35cd8cd4 __workq_kernreturn + 8
1   libsystem_c.dylib             	0x34e7bf36 _pthread_wqthread + 610
2   libsystem_c.dylib             	0x34e7bcc8 start_wqthread + 0

Thread 3:
0   libsystem_kernel.dylib        	0x35cd8cd4 __workq_kernreturn + 8
1   libsystem_c.dylib             	0x34e7bf36 _pthread_wqthread + 610
2   libsystem_c.dylib             	0x34e7bcc8 start_wqthread + 0

Thread 4 name:  WebThread
Thread 4:
0   libsystem_kernel.dylib        	0x35cc8004 mach_msg_trap + 20
1   libsystem_kernel.dylib        	0x35cc81fa mach_msg + 50
2   CoreFoundation                	0x35c363ec __CFRunLoopServiceMachPort + 120
3   CoreFoundation                	0x35c35124 __CFRunLoopRun + 876
4   CoreFoundation                	0x35bb849e CFRunLoopRunSpecific + 294
5   CoreFoundation                	0x35bb8366 CFRunLoopRunInMode + 98
6   WebCore                       	0x378fec9c RunWebThread(void*) + 396
7   libsystem_c.dylib             	0x34e8172e _pthread_start + 314
8   libsystem_c.dylib             	0x34e815e8 thread_start + 0

Thread 0 crashed with ARM Thread State:
    r0: 0x00000000    r1: 0x00000b00      r2: 0x2fe415f4      r3: 0x00000000
    r4: 0x0143a9e0    r5: 0x00000004      r6: 0x3f01d188      r7: 0x2fe4165c
    r8: 0x00000000    r9: 0x0000001a     r10: 0x00000000     r11: 0x00000000
    ip: 0x3f5801b8    sp: 0x2fe41658      lr: 0x00053315      pc: 0x00053314
  cpsr: 0x60000030

**Comment by umxprime** [comment]
Here is a xcode screenshot
![Uploading Capture d’écran 2015-01-22 à 18.19.20.png . . .]()

**Comment by umxprime** [comment]
![godotissue](https://cloud.githubusercontent.com/assets/611795/5860709/97cfb010-a263-11e4-8e3f-74408db113ea.png)

**Comment by umxprime** [comment]
I submitted a pull request that solve this issue https://github.com/okamstudio/godot/pull/1300

**Comment by vnen** [comment]
I'll close this as fixed since #1300 was merged.
