### ISSUE TITLE
Directional Light bleeds through planes

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#12953]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
fedora 26 64bit, Nvidia proprietary drivers 384.90

**Issue description:**

Directional (im not sure if other lights do this too) lights plane back face completely, using contact shadow or bias could solve the problem but causes problems in the rest of the environment, im not sure if thats not supposed to work, i tried setting shadow double sided and double sided material, but nothing seems to work.

here is an example

![peek 2017-11-14 22-13](https://user-images.githubusercontent.com/1103897/32855650-f607a218-ca07-11e7-8608-d2bc597666b1.gif)

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by reduz** [comment]
This is perfectly expected from Shadow Mapping

**Comment by djrm** [comment]
is there a way to solve this problem, or do i have to use two faces.

**Comment by Zylann** [comment]
You can mitigate this with a compromise of the following options:

- Tweak bias or normal bias (should usually be quite small)
- Give thickness to your plane
- Checking reverse face culling
- Verify if shadow distance and blend splits are correctly chosen given the size of your level
- Use contact shadows (though I honestly never used them, they aren't that nice given their price/quality ratio)

**Comment by djrm** [comment]
@Zylann as i said i tried almost all the options, some create more artifacts, specially contact and bias and reverse culling face, so i guess the only alternative here is to use two planes (or pseudo-box), the proble arises because i want to recycle a directional light from exterior to use it in interiors, so the sun matches lights interiors too, since interiors are loaded separately, i could create a special variation of the directional light for interior though, but i though this could work, but if it is not supposed to work, its fine, i will figure something out.

**Comment by reduz** [comment]
Generally, super thin walls never work well with shadow mapping, so games
try to avoid them
