### ISSUE TITLE
LinkButton show ERROR texture after click

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#12959]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**  custom build based on c7f7dd3 commit from master branch, Linux Mint Mate 18.2 x86_64

**Issue description:**
![default](https://user-images.githubusercontent.com/5412322/32860746-61f1f584-ca74-11e7-8be2-c372b92bf98c.png)

**Steps to reproduce:**
1) Add `Node2D` or `Control` on new scene
2) Add `LinkButton` node
3) Change option `Enabled Focus Mode` from `None` to any other
4) Run scene and click on button

**Comment by toby3d** [comment]
Commit 889d262, still happening.

**Comment by reduz** [comment]
for those interested, there may be a missing theme definition in default_theme.cpp
