### ISSUE TITLE
2D Shader Editor nodes problem

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1295]
Not everything seem to work about 2D Shader Editor:
1. When using uniforms, and setting it's values from inspector of object that uses this shader, they seem to not apply on the shader at all... Values seem to stay unchanged.default.
2. When using Uniforms I get this error after pluging everything up and saving the shader:
 core/io/resource_format_binary.cpp:1417 - Can't save RIDs - with a red square on the left
( don't know what that means here ).
3. It happened to me once, that the RGB constant was giving me totaly wrong output ( B was not working at all, G was setting G and B thesame value (?!?!!), and R was ok ). I happened very single time, and I cant reproduce it now... It wasn't my fault for sure. 
4. I've also included 2 proposals about shader editor's gui to UI Rewrite Plan.

It works great anyways. Love to see the output in realtime on the preview! =]

**Comment by reduz** [comment]
does this still happen? (there were a few recent fixes to that)

**Comment by akien-mga** [comment]
reduz wrote:
> does this still happen? (there were a few recent fixes to that)

@Krzycho666 Ping :)

**Comment by akien-mga** [comment]
Assuming it was fixed.
