### ISSUE TITLE
Drag-and-drop file to viewport: new node name is not informative

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#12956]
As of latest master, when one drags-and-drops a .dae mesh from filesystem to viewport, a new node is created with name "Scene Root", next time it's "Scene Root2" and so on.
I think it would make sense to call the new node based on the file name instead (cube.dae -> "cube", "cube2", "cube3", etc).

**Comment by KoBeWi** [comment]
Fixed by #27453
