### ISSUE TITLE
Fail to assign the same material more then one time

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#1296]
*bugSquad edit: probably seen in 1.0*
In my environment I have two particles of some type, a smoke with more elements to see close and a duplicate one with minus particles to see to far. On assign material in first one all right, but to assign to children particles with the same material nothing appears in editor. And worst: on play the game it crashes!

![captura de tela - 19012015 - 22 29 28](https://cloud.githubusercontent.com/assets/85936/5868192/6a81531e-a28d-11e4-8e61-799a83402890.jpg)

**Comment by reduz** [comment]
I think i fixed a bug related to that recently, does it still crash?

**Comment by marcosbitetti** [comment]
I try to open the same scene, add new particle, slect same material... and editor crash!

**Comment by kubecz3k** [comment]
Trying to triage the issue:
@marcosbitetti could you check what is current status of this issue?

**Comment by akien-mga** [comment]
@marcosbitetti Ping. Is this issue still valid in Godot 2.x?

**Comment by marcosbitetti** [comment]
At moment I not observe it on 2.x;
