### ISSUE TITLE
Can not compile godot on OS X with gdnative_wrapper

### ISSUE THREAD

**Issue by Yakud** [godotengine/godot#12968]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OS X, godot 3

**Issue description:**
I tried to compile godot 3 on OS X with param gdnative_wrapper=yes and have a error:

> [ 97%] Linking Program        ==> bin/godot.osx.debug.64
make_debug(["bin/godot.osx.debug.64"], ["platform/osx/crash_handler_osx.osx.debug.64.o", "platform/osx/os_osx.osx.debug.64.o", "platform/osx/godot_main_osx.osx.debug.64.o", "platform/osx/sem_osx.osx.debug.64.o", "platform/osx/dir_access_osx.osx.debug.64.o", "platform/osx/joypad_osx.osx.debug.64.o", "platform/osx/power_osx.osx.debug.64.o"])
warning: (x86_64)  could not find object file symbol for symbol __Z18register_jpg_typesv
warning: (x86_64)  could not find object file symbol for symbol __Z20unregister_jpg_typesv
warning: (x86_64)  could not find object file symbol for symbol __Z9memdeleteI14ImageLoaderJPGEvPT_
warning: (x86_64)  could not find object file symbol for symbol __ZL16image_loader_jpg
warning: (x86_64)  could not find object file symbol for symbol __Z18register_ogg_typesv
warning: (x86_64)  could not find object file symbol for symbol __Z20unregister_ogg_typesv
warning: (x86_64)  could not find object file symbol for symbol __Z21register_recast_typesv
warning: (x86_64)  could not find object file symbol for symbol __Z23unregister_recast_typesv
[ 97%] build_gdnative_wrapper_code(["modules/gdnative/gdnative_wrapper_code.gen.cpp"], ["modules/gdnative/gdnative_api.json"])
scons: *** [modules/gdnative/gdnative_wrapper_code.gen.cpp] KeyError : 'api'
Traceback (most recent call last):
  File "/usr/local/Cellar/scons/3.0.0_1/libexec/scons-local/SCons/Action.py", line 1197, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/Users/yakud/godot-yakud/godot-python/godot/modules/gdnative/SCsub", line 209, in build_gdnative_wrapper_code
    fd.write(_build_gdnative_wrapper_code(api))
  File "/Users/yakud/godot-yakud/godot-python/godot/modules/gdnative/SCsub", line 180, in _build_gdnative_wrapper_code
    for funcdef in api['api']:
KeyError: 'api'
scons: building terminated because of errors.

What I doing wrong?
I need a godot with gdnative_wrapper for a make GDNative python. 

**Steps to reproduce:**
```
git clone  https://github.com/godotengine/godot.git
scons platform=osx gdnative_wrapper=yes target=debug tools=no
```

**Comment by akien-mga** [comment]
CC @karroffel

**Comment by karroffel** [comment]
The wrapper doesn't work yet with the new API struct management, I need to fix that.

**Comment by rraallvv** [comment]
@karroffel is there a way to get rid those warnings with some flags:

	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: scene/libscene.osx.tools.32.a(spatial_indexer.osx.tools.32.o) has no symbols
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: scene/libscene.osx.tools.32.a(audio_stream_resampled.osx.tools.32.o) has no symbols
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: scene/libscene.osx.tools.32.a(dynamic_font_stb.osx.tools.32.o) has no symbols
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: scene/libscene.osx.tools.32.a(gibberish_stream.osx.tools.32.o) has no symbols
	Ranlib Library         ==> scene/libscene.osx.tools.32.a
	[ 85%] Linking Static Library ==> servers/libservers.osx.tools.32.a
	Ranlib Library         ==> servers/libservers.osx.tools.32.a
	[ 90%] Linking Static Library ==> core/libcore.osx.tools.32.a
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: core/libcore.osx.tools.32.a(safe_refcount.osx.tools.32.o) has no symbols
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: core/libcore.osx.tools.32.a(export_data.osx.tools.32.o) has no symbols
	Ranlib Library         ==> core/libcore.osx.tools.32.a
	[ 97%] Linking Static Library ==> modules/freetype/libfreetype_builtin.osx.tools.32.a
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: modules/freetype/libfreetype_builtin.osx.tools.	32.a(ftpic.osx.tools.32.o) has no symbols
	Ranlib Library         ==> modules/freetype/libfreetype_builtin.osx.tools.32.a
	[ 97%] Linking Program        ==> bin/godot.osx.tools.32
	dsymutil bin/godot.osx.tools.32 -o bin/godot.osx.tools.32.dSYM
	warning: (i386)  could not find object file symbol for symbol __Z22register_cscript_typesv
	warning: (i386)  could not find object file symbol for symbol __Z24unregister_cscript_typesv
	warning: (i386)  could not find object file symbol for symbol __Z18register_dds_typesv
	warning: (i386)  could not find object file symbol for symbol __ZN17ResourceFormatDDSC1Ev
	warning: (i386)  could not find object file symbol for symbol __Z20unregister_dds_typesv

**Comment by akien-mga** [comment]
```
warning: (i386)  could not find object file symbol for symbol __Z22register_cscript_typesv
warning: (i386)  could not find object file symbol for symbol __Z24unregister_cscript_typesv
warning: (i386)  could not find object file symbol for symbol __Z18register_dds_typesv
warning: (i386)  could not find object file symbol for symbol __ZN17ResourceFormatDDSC1Ev
warning: (i386)  could not find object file symbol for symbol __Z20unregister_dds_typesv
```
All those are obsolete symbols which are no longer in the master branch, you should make clean your build tree and rebuild from scratch.

**Comment by rraallvv** [comment]
@akien-mga thanks, it did the trick for "...could not find object file symbol..."

**Comment by rraallvv** [comment]
@akien-mg adding this to `platform/osx/detect.py` silences **'has no symbols'** warnings

    # silence "has no symbols" warnings on Mac OS X
    if env["verbose"] == "no":
        env.Append(RANLIBFLAGS=["-no_warning_for_no_symbols"])
        env.Append(ARFLAGS=["-S"])

**'could not find object file symbol for symbol'** is popping up again, maybe is **ccache**, but cleaning it would make the build process to take too long, and it seems there isn't a flag to silence those.

I'll check later if there is something else that could be done, if I find something I'll post it here, thanks.

**Comment by akien-mga** [comment]
Well there's no reason to silence those warnings. They indicate that you're actually linking obsolete code, so that's a bug, not something to hide.

**Comment by rraallvv** [comment]
@akien-mga I see, thanks for the info.
