### ISSUE TITLE
Useless blank space on the inspector property names

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#12963]
**Godot master**

**Issue description:**
The left side of the properties names have a big blank space (24 pixels aprox.) that does not shrink with the inspector making it a wasted space in particular on small screens.

If that does not have any use it should be reduced to zero or close zero, giving more space to property values.

![hugeblankborder](https://user-images.githubusercontent.com/10215987/32887085-7a04766a-caa1-11e7-8a1a-eed774d7370b.png)
_the red rectangle shows the empty space that takes a big portion of the inspector_

**Comment by akien-mga** [comment]
If we want to change that, it should be done before beta ideally.

**Comment by Chaosus** [comment]
This requires to modify Tree class, the field which controls it called - draw_ofs

**Comment by eon-s** [comment]
@Chaosus the offset is fixed? can't be exposed to use in particular cases? (because trying to modify that will affect all other trees in the editor).

**Comment by Chaosus** [comment]
It looks like so, You need to introduce new controllable property to Tree to do that task

**Comment by reduz** [comment]
@djrm , @toger5 ?

**Comment by djrm** [comment]
discussion is here https://github.com/godotengine/godot/pull/13352
i dont see much beneffit in removing but the last implementation in that PR looks kinda ok, im not that sure myself.

**Comment by akien-mga** [comment]
In the end we did not reach a consensus, so I think it will stay as is.
