### ISSUE TITLE
Add smooth scrolling to all scrollable controls

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#12965]
All kinds of controls that feature scrolling (like TextEdit or ScrollContainer) should feature optional smooth scrolling, both in the editor and games. The script editor already features "smooth" scrolling, but it doesn't really feel good to use (I personally disable it, as I find it hinders me more than anything).

Here's a lengthy, well-written article on the subject (and why it's important): [Scrolling with pleasure](https://pavelfatin.com/scrolling-with-pleasure/)

**Comment by reduz** [comment]
This is more work and no gain, so I would prefer not.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/5386, as feature proposals are now tracked on the Godot proposals repository.
