### ISSUE TITLE
Control clip_contents doesn't work when playing the scene

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12975]
Godot 3.0 alpha2
Windows 10 64 bits
nVidia 940M

When a Control is configured to clip its content, it works in the editor, but when the scene its played it doesn't.

![image](https://user-images.githubusercontent.com/1311555/32916814-7c85e6a4-cb1d-11e7-8aa5-d6d54ee067cd.png)

Repro steps:
1) Create a Panel
2) Create a ColorRect as child of it and move it so it crosses boundaries of its parent
3) Check `clip_contents` in the parent control, notice it correctly clips the ColorRect
4) Run the scene: notice the ColorRect isn't clipped

**Comment by Keetz** [comment]
I cannot reproduce this in 3.0.2-stable

**Comment by volzhs** [comment]
can't either with 3.1.dev
