### ISSUE TITLE
Bullet rigid body in character mode can't be rotated

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#12979]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux amd64, Godot build 9a78efc

**Issue description:**
A body in character mode shouldn't rotate because forces act on it, bu itt should still be able to rotate if a non zero angular velocity is set. However using bullet and character mode seems to lock the object and prevent it to rotate in any way.

**Steps to reproduce:**
Create a rigid body, set it to character mode and set the angular velocity to (0, 10, 0). Switch between Bullet and GodotPhysics.

**Comment by m4nu3lf** [comment]
A possible solution could be to just set the inertia along the axes to infinity if that is supported by Bullet

**Comment by reduz** [comment]
I think it should be expected that it cant rotate.. not sure why it should

**Comment by m4nu3lf** [comment]
@reduz not even by changing the transform? (it is overwritten by the physics engine I think at every frame). If that is the case what is the purpose of this mode?
In GodotPhysics the body character mode can rotate if the angular velocity is set or by changing transform. Is this a bug in the GodotPhysics engine?

**Comment by reduz** [comment]
Probably a bug on the Godot side and no, it should not rotate..

**Comment by m4nu3lf** [comment]
OK, but how is it meant to be used? is it the armature that should rotate?

**Comment by reduz** [comment]
Yeah, just rotate the mesh

**Comment by eon-s** [comment]
It was always possible to rotate the body, which is useful for capsules and other type of irregular shapes, in 3 the shape should be rotated instead then?

And if the rotation is a bug, affects 2D bodies...

**Comment by puppetmaster-** [comment]
@reduz Are there any plans to remove node2d properties from physic nodes or replace it with (physic working) one.
It's very confusing and also not beginner friendly and the quote in [documentation](http://docs.godotengine.org/en/stable/learning/features/animation/introduction_2d.html)
"**In Godot you can animate anything you find in the Inspector.**" does not count anymore (very sad).
I'm not angry if it sound so.

**Comment by reduz** [comment]
@puppetmaster- I don't have the slightest clue about the meaning of what you just wrote

**Comment by puppetmaster-** [comment]
@reduz I try to explain . . .
RigidBody2D, KinematicBody2D . . . inherit from node2d, but when you use node2d function or animate the node2d properties you get a lot of problem or it didn't work. In godot 2.1 some of them worked but no more in godot 3. I attached some issues where describe it better.

some Issues:
https://github.com/godotengine/godot/issues/12335
https://github.com/godotengine/godot/issues/5734
https://github.com/godotengine/godot/issues/2129
https://github.com/godotengine/godot/issues/11050

I hope is clear now.

**Comment by reduz** [comment]
@puppetmaster- this has always worked like this, and it's super easy to work around. I don't really see the problem. Most of these issues should be closed, save for applying scale to rigid bodies, which will be done, but after 3.0 is out

**Comment by puppetmaster-** [comment]
@reduz Great! So animating position, scale and rotation will work again in a future release after 3.0 is out.

**Comment by reduz** [comment]
@puppetmaster- there really is no point in animating those things, you can animate the shapes or meshes though and that works fine.

**Comment by m4nu3lf** [comment]
I think the discussion is a bit OT now, but @eon-s had a very fair point. I personally think it would be good to have a behavior like in the old engine, so you can rotate the body with the collision shapes (e.g. on user input) but without having it rolling, or rotating in any way because of physics interactions.
This is my opinion but in any case I'm not sure this is supported by Bullet.

**Comment by reduz** [comment]
@m4nu3lf Of course it should be good, but it makes supporting it in a physic engine more work, for something that can be very easily worked around. I would have expected it to not even work in Godot physics

**Comment by m4nu3lf** [comment]
Yes, it basically behaves like if the inertia has some infinite values. So it all boils down if you can set the inverse inertia to zero in Bullet. I agree that it can be worked around as I already did in one project, (so it is not a major issue for me), but it is not immediate if you want to keep the physics interactions for the linear part and you have an irregular shape.

**Comment by kakoeimon** [comment]
After some discussion on irc I found out that:
Bullet physics RigidBodies in Character mode cannot use angular velocity to rotate, but it is possible to manipulate the transform.
The problem can be bypassed by using Axis Lock and not the Character mode.
For example lock Angular X and Z to be able to rotate in Y.
I believe this issue can be closed.
