### ISSUE TITLE
== operator not working on references to arrays/dictionary with recursive references

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#1297]
Made a demo to show this:
https://github.com/ScyDev/godot/tree/master/demos/crashes/recursive_reference_compare_fail

Godot should handle recursive references better. Cut them off when necessary, during print() or a comparision.

PHP does this well.

**Comment by Grass-H0PEr** [comment]
Your project `recursive_reference_compare_fail` now passes (in both 2.1.4 + 3.0)

But I'm _guessing_ this is from comparing the array address the vars point at
rather than evaluating.

Your project `recursive_reference_print_crash` still creates an infinite operation
(in both 2.1.4 + 3.0)

---

Condensed + combined both examples, 
commented out the `print(poly)` line that leads to infinite recursive evaluation

```
func _ready():
	var poly = []
	
	var line1 = {}	
	var line2 = {}
	
	line1["intersects"] = [line2]
	line2["intersects"] = [line1]
	
	var poly2 = poly
	var poly3 = poly

	poly.push_back(line1)
	poly.push_back(line2)

	## ---------------------------- 
	##  now passes in 2.1.4 + 3.0 
	## ----------------------------
	if (poly2 == poly3):
		print("SAME SAME")

	## --------------------------------- 
	##  still creates infinite recursion 	
	## --------------------------------- 
	print("before poly")
	#print(poly)
	print("after poly")
```

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by DualMatrix** [comment]
According to @Grass-H0PEr comparing now works. Printing is still broken but has a separate issue, see #8693

**Comment by akien-mga** [comment]
Thanks, closing.
