### ISSUE TITLE
Expose further compression options

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#12972]
Following up from #9274, I'd like to complete this before beta.

What needs to be done is: expose compression levels, as well as zstd's long range compression options.

**Comment by tagcup** [comment]
Probably needs a bit of refactoring to do the things I listed [here](https://github.com/godotengine/godot/pull/9125#issuecomment-308192876) earlier

**Comment by tagcup** [comment]
Just as a heads up, this can be done by adding additional optional parameters, making it backward-compatible with the current API, and I'll submit a PR in the coming days

**Comment by Calinou** [comment]
> What needs to be done is: expose compression levels, as well as zstd's long range compression options.

This was exposed a while ago (in either 3.0 or 3.1), closing.
