### ISSUE TITLE
Error instaling export templates: version.txt not find inside the models

### ISSUE THREAD

**Issue by Elmapul** [godotengine/godot#12981]
Ubuntu 14.04
Godot 3.0 Alpha 2

my godot is in portuguese so the title is an translation of the error.
"não foi encontrado  um version.txt dentro dos modelos"

**Comment by eon-s** [comment]
With "modelos" I think that refers to the templates.
You have to add manually the templates to `(godot config folder/)editor_data/templates/3.0-alpha`.

That version file should be in the template file on beta release, I guess...

**Comment by akien-mga** [comment]
How did you install the templates? The version.txt is included in the alpha2 templates AFAIK.

**Comment by Elmapul** [comment]
Ok, sorry, my mistake.

i had godot 2 and godot 3 alpha 1 instaled already.
then i dowloaded godot 3 alpha 2, but instead of clicking to install:
 "Godot_v3.0-alpha2_export_templates.tpz"
i instaled:
"Godot_v2.1.3-stable_export_templates.tpz"
to make the things worse, i saw that there was something wrong, and tried to manualy extract it to 
(godot config folder/)editor_data/templates/3.0-alpha

 its working now!
thanks for the quick reply!
