### ISSUE TITLE
scons: *** [drivers\libdrivers1.windows.tools.32.a] Wrong parameters

### ISSUE THREAD

**Issue by GiantCrocodile** [godotengine/godot#1298]
Hello,

I tried to compile Godot Engine under Windows 8 with Python 2.7.9, openssl 1.0.1L and Scons 2.3.4 with the command `scons platform=windows`.

This is the error message I get when it aborts the compilation:
`scons: *** [drivers\libdrivers1.windows.tools.32.a] Wrong parameters
scons: building terminated because of errors.`

Is it a bug or is it my fault?

**Comment by UsernameIsAReservedWord** [comment]
Hi @GiantCrocodile,

I'm a working on a fix for this issue and some others related to windows compilation.

If you want, you can test the work-in-progress script by you replacing `platform/windows/detect.py` with this one :
https://github.com/UsernameIsAReservedWord/godot/blob/master/platform/windows/detect.py

this current version should make work compiling under windows using mingw.
if it does not work, please tell me.

**Comment by GiantCrocodile** [comment]
I tried your fix @UsernameIsAReservedWord and it does work for me on this computer. Thanks!
