### ISSUE TITLE
Viewport cannot be passed events from GDScript’s _input function

### ISSUE THREAD

**Issue by TwistedTwigleg** [godotengine/godot#12991]
**Issue description:**

The GUI in 3D demo stopped working with commit #12149. Previously you could send input events from GDScript using _input and pass it to the viewport using the viewport’s input function.

In godotengine/godot-demo-projects#84 I preposed adding a force_input function to viewport, which would basically be the same as input but without checking whether or not the event has been handled. Is there a better way to send inputs to a viewport from GDScript? Or maybe a way to make a new event and copy the values?

I’ve tried finding a way to fix this from GDScript, but to no avail.

**Steps to reproduce:**
Create a viewport and a node (not a child of the viewport). Send the viewport the event recieved from GDScript’s _input function.

**Link to minimal example project:**

GUI in 3D from the demo repository shows the issue

**Comment by TwistedTwigleg** [comment]
@reduz this is fixed now, right?

**Comment by reduz** [comment]
yes this should not work
