### ISSUE TITLE
Ctrl and Shift key events masked when one already pressed

### ISSUE THREAD

**Issue by Knuckl3head** [godotengine/godot#12993]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 Pro Build 15063 x86_64
Godot v2.1.4.stable.official 64-bit

_Update_
I just confirmed masking to be present on Ubuntu Mate 16.04 w/ Linux 4.10.0-35-generic

**Issue description:**
When either control or shift are mapped to an action and pressed, pressing one key will mask all events of the other key. I believe this is due to their property as modifier keys.

To workaround, don't use both control and shift in player controls.

**Steps to reproduce:**
With the inputs of shift and control monitored in some fashion in _input:
1. Press Shift (The keypress will register)
2. Press Ctrl (The keypress will not register)
3. Release Shift (The release won't register)
4. Release Ctrl (The release will register)

**Link to minimal example project:**
[input_bug_test.zip](https://github.com/godotengine/godot/files/1483418/input_bug_test.zip)

Just open the test scene and run it.
I have m_ctrl mapped to Control and m_shift mapped to Shift, and the events of either being pressed or released printing to the debug console.

**Comment by Noshyaar** [comment]
Works as expected on master ca19403
```
Shift has been pressed!
Ctrl has been pressed!
Shift has been released!
Ctrl has been released!
```

**Comment by rosshadden** [comment]
I get a very similar but much less straightforward issue. It's easiest to sum it up as "if I map an action to shift or use `input.is_key_pressed(KEY_SHIFT), everything goes absolutely haywire". It's like from the moment I hit shift, no other controls work properly.

**Comment by akien-mga** [comment]
Since #18020 claims to fix this issue, I assume it's still reproducible in the master branch so changing milestone :)

**Comment by akien-mga** [comment]
Well I just tested and I also can't reproduce the bug in OP (on Linux/X11), I have the same results as https://github.com/godotengine/godot/issues/12993#issuecomment-345438585

Updated test project: 
[input_bug_test_3.1.zip](https://github.com/godotengine/godot/files/2391882/input_bug_test_3.1.zip)

@bruvzg Is #18020 still addressing this issue, and if so what part of it?

**Comment by bojidar-bg** [comment]
I am also unable to reproduce the bug on Arch Linux, eb70999ffa41d36f3b7227780b878b8dc64efdd0, using the example project.
Could it be a Windows-specific bug?
