### ISSUE TITLE
Regression: running current scene (unsaved) will ask for main scene

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#13009]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64 | Godot Master 63283ec

**Issue description:**

Expected: editor running current scene right away after saving
Happened: editor asking that main scene should be specified
Related: #12967 #12971

**Steps to reproduce:**
1. new scene, don't save, it should say `[unsaved](*)` as tab header
2. run current scene (F6)
3. save when prompted
4. editor asks that you select a main scene

**Comment by Sslaxx** [comment]
Does selecting a different main scene to the one the project already have change it?

**Comment by Noshyaar** [comment]
@Sslaxx I guess not. I think the dialog isn't actually doing anything.
