### ISSUE TITLE
Exported Android game with GLES2 API does not work (obsolete setting)

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#13004]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot version: Godot 3 Alpha 2
Development OS: Windows 8.1
Test Device: Android Kitkat (with 512MB RAM)

**Issue description:**
The game exported, and installed on the test device with no problem. But when I try to run it, it open briefly, and "Unfortunately app has stopped" appear, and the game Quit. 
It's not happenning with my other game, made with Godot 2.
Oh, and I use OpenGLES 2 API, because my test device OpenGLES version is OpenGLES 2.
I attach my project and Exported APK.

**Steps to reproduce:**
1. Make something
2. Export to Android with OpenGLES 2 API.

**Link to minimal example project:**

[Try2D.zip](https://github.com/godotengine/godot/files/1484357/Try2D.zip)
[coba3ogl22d.zip](https://github.com/godotengine/godot/files/1484359/coba3ogl22d.zip)

**Comment by mrcdk** [comment]
Godot 3.0 is only compatible with OpenGL ES 3.0

**Comment by volzhs** [comment]
AFAIK, it will work again on Godot 3.1

**Comment by earlroxas13** [comment]
Oh, sorry, I didn't know that. There is an option to choose OpenGL ES 2.0 or 3.0 API in Android Export option, so I thought that OpenGL ES 2.0 API is usable.
I'll keep using Godot 2 for my Android game then, until 3.1.

And maybe you should hide the option for OpenGL ES 2.0 until it actually usable, just my opinion, tho.

Thank you for the information.
