### ISSUE TITLE
KinetmaticBody not moving with Bullet

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#13002]
Calling in `MoveAndSlide()` in `_PhysicsProcess` of a KinematicBody doesn't seem to be doing anything with Bullet although it does work when I switch back to Godot.

I can change the orientation just fine though.

**Comment by eon-s** [comment]
Is `move_and_collide` now, I guess that you are using C#, `move` should be removed there.

**Comment by tagcup** [comment]
Oops, that was typo, sorry, I meant `MoveAndSlide`

**Comment by eon-s** [comment]
Ok, move and slide works fine here on the kinematic char demo (GDScript, 9a78efc).

**Comment by tagcup** [comment]
It may work in that case but it sure isn't working in my test case: I have a kinematicbody with a capsule collision shape on a terrain mesh with convex collider and it simply doesn't move with Bullet whereas everything works just fine when I switch to GodotPhysics.

I'm certain that there's a problem with Bullet. I'll try to prepare a simple test demo but I can for sure reproduce this all the time.

**Comment by tagcup** [comment]
Oops closed by accident

**Comment by HummusSamurai** [comment]
This is similar to my issue in https://github.com/godotengine/godot/issues/12853

In my case the character is not moving partly because Bullet always returns false for on_floor() even when the body is clearly "on the floor".

**Comment by AndreaCatania** [comment]
Fixed: https://github.com/godotengine/godot/pull/13046

**Comment by tagcup** [comment]
I just confirmed that #13046 fixes this
