### ISSUE TITLE
Easier ways to create a new inherited scene

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#13013]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0

**Issue description:**
Currently the only way to create a new inherited scene is by going to the "Scene" menu, selecting "New inherited scene", and then navigating to the scene you want to inherit.

Two ways that would make this easier, I think, is the ability to right click on an open scene tab, which will show an option to create a new inherited scene from that open scene. And right clicking on a scene in the file system panel, then selecting to create a new inherited scene from that scene.

**Comment by kubecz3k** [comment]
related issue: https://github.com/godotengine/godot/issues/4585

**Comment by DualMatrix** [comment]
Isn't this fixed in master with the ability to instance a node as the root of a scene, making it an inherited scene?

**Comment by CowThing** [comment]
No. There could still be more ways of creating inherited scenes. Honestly I don't think that using the `instance a scene` button to create an inherited scene should even exist. It's weird that a button like that has two different functionalities. And it's not any easier than using the `Scene -> New Inherited Scene` menu option, which is a better option because that menu option will by default select the scene you currently have open. The `instance a scene` button requires you to navigate to whatever scene you want to inherit whether it's already open or not.

**Comment by homer666** [comment]
Another potential method I saw brought up but forgot where, was just dragging a scene from Filesystem right into an empty Scene dock. I thought it was interesting, just something to consider I guess.

**Comment by Anutrix** [comment]
Any updates?

**Comment by CowThing** [comment]
In 3.2 it's now possible to right click on a scene in the FileSystem panel and create a new inherited scene from that menu, which is very useful.
Right clicking on an open scene tab doesn't give an option to inherit from it, but that one isn't as important I think.

**Comment by akien-mga** [comment]
Let's close as fixed then.
