### ISSUE TITLE
Add key button in AnimationPlayer is not entirely clickable.

### ISSUE THREAD

**Issue by remorse107** [godotengine/godot#13012]
Windows 10 Home Edition
Nvidia GTX 950
Godot 3.0 Alpha

**Issue description:**
Only the extreme right side of the add key marker is clickable.  I almost thought the add key was not working at all.  But I am able to consistently repeat the action.

**Steps to reproduce:**
Just give it a go.

![animationplayer](https://user-images.githubusercontent.com/7462993/32981882-6bcb2c56-cc40-11e7-89e3-bbb458208aa9.png)

**Comment by Noshyaar** [comment]
Fixed by #13014
