### ISSUE TITLE
Godot 3 with Mono compilation error: expected type-specifier before 'AABB'

### ISSUE THREAD

**Issue by zedrian** [godotengine/godot#13011]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 x64
g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406

**Issue description:**
I'm trying to compile Godot 3 with Mono support (calling scons with flags `module_mono_enabled=yes` and `mono_glue=no`) and compilation fails with next error:

> modules/mono/mono_gd/gd_mono_marshal.cpp: In function 'MonoObject* GDMonoMarshal::variant_to_mono_object(const Variant*, const ManagedType&)':
> modules/mono/mono_gd/gd_mono_marshal.cpp:301:25: error: expected type-specifier before 'AABB'
>      RETURN_BOXED_STRUCT(AABB, p_var);
>                          ^
> modules/mono/mono_gd/gd_mono_marshal.cpp:39:40: note: in definition of macro 'RETURN_BOXED_STRUCT'
>    const m_t &m_in = m_var_in->operator m_t();                           \
>                                         ^~~
> modules/mono/mono_gd/gd_mono_marshal.cpp:398:26: error: expected type-specifier before 'AABB'
>       RETURN_BOXED_STRUCT(AABB, p_var);
>                           ^
> modules/mono/mono_gd/gd_mono_marshal.cpp:39:40: note: in definition of macro 'RETURN_BOXED_STRUCT'
>    const m_t &m_in = m_var_in->operator m_t();                           \
>                                         ^~~
> scons: *** [modules/mono/mono_gd/gd_mono_marshal.x11.tools.64.mono.o] Error 1
> scons: building terminated because of errors.
> 

**Steps to reproduce:**
1. Clone this repository at branch `master` (reproduced at commit 63283eca5542314ea5b71afa1fe39bd48c202a4d)
2. Go to `godot` folder and call
`scons platform=x11 tools=yes module_mono_enabled=yes mono_glue=no`
3. Notice that compilation fails.

What can I do with that?

**Comment by tagcup** [comment]
Can you tell about your compiler and version?

I can't reproduce this with clang 5.0.0.

**Comment by tagcup** [comment]
Ah nevermind, you already did.
