### ISSUE TITLE
Godot 2.1.4 auto-crash on launch.

### ISSUE THREAD

**Issue by MrTaron** [godotengine/godot#13020]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

Godot 2.1.4 auto-crashes when opening.
Perhaps unrelated, but seems to be happening following a Windows update 2 days ago. (I hadn't used it yesterday, so I can't confirm the direct correlation)

**Steps to reproduce:**
1. Double-click the Godot software. Wait 3s. Crash.

**Link to minimal example project:**

![godot crash](https://user-images.githubusercontent.com/18179942/32984028-46da9856-cc6c-11e7-97ee-93800d7f4af0.png)

**Comment by Calinou** [comment]
What graphics card do you havel? If you don't know, press <kbd>Windows+R</kbd then type in `dxdiag`, then go to the **Display** section of the window that just opened (after accepting the prompt about driver verification).

**Comment by akien-mga** [comment]
Looks like your drivers are broken, check if they are properly installed/up-to-date.

**Comment by Chaosus** [comment]
Closed as its purely driver-related issue(and TC does not provide enough information about his video card and Godot's version)
