### ISSUE TITLE
Main screen plugins can't set their icon

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#13028]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 (63283eca5)

**Issue description:**
If you create a main screen plugin, you have no way to set its icon, leaving it as "Error" instead.

![godot_2017-11-18_23-29-14](https://user-images.githubusercontent.com/5599796/32986466-0fb17a46-ccb9-11e7-89bb-d35f3feac709.png)

I also noticed that if the name is recognized, it'll use its icon:

![godot_2017-11-18_23-35-52](https://user-images.githubusercontent.com/5599796/32986470-4ca124b0-ccb9-11e7-82a4-af20fd093c78.png)

**Link to minimal example project:**

[main_screen.zip](https://github.com/godotengine/godot/files/1485216/main_screen.zip)

**Comment by reduz** [comment]
All logic for this is in editor_node.cpp
