### ISSUE TITLE
OBJ files can't be imported as a scene

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#13032]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10 and Linux Mint

**Issue description:**
When using the menu option Scene>open scene , it is no longer possible to open an OBJ file. The scene does open, but the mesh instance nodes are empty and do not reference any mesh files.
This function broke when the "OBJ as mesh" option was made as the default in the importer. Even when changing the importer option to "import as scene" and reimporting, it makes no difference.

Importing a scene still works correctly for dae and gltf files. 

**Steps to reproduce:**
- Use Scene>open scene and try to open an obj file

**Comment by groud** [comment]
Confirmed in live at the Capitole Du Libre :D

**Comment by Zylann** [comment]
Isn't it a choice in the import dock?
