### ISSUE TITLE
Mac OS High Sierra // OS.get_window_size() => doubled resolution

### ISSUE THREAD

**Issue by ChrisOKay** [godotengine/godot#13034]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacBook Pro, Mac OS High Sierra 10.13.1
Godot 2.1.4
Intel Iris Graphics 6100
 

**Issue description:**
I wanted to get the window size of the screen resolution via OS.get_window_size(), but the resulting resolution is twice as high as the actual project settings (Globals.get("display/width") and Globals.get("display/height")).
Example: Project resolution is 640x360, OS.get_window_size() returns 1280x720

This unexpected behaviour only happens on my Macbook, on Windows 7 everything works as expected. So I believe it is either connected to Mac in general or to High Sierra in particular. Worst case it is some weird special configuration on my machine.

**Steps to reproduce:**
(Mac OS High Sierra)
Create new project, single 2dNode with script
```godot
print(OS.get_window_size())
```

=> double x and y resolution compared to Globals.get("display/width") and Globals.get("display/height")

**Comment by Calinou** [comment]
You probably have an hiDPI display, and Godot returns the actual size in pixels. if you want "device-independent pixels", you will need to divide this value by the display scaling option. (I've looked at the `OS`class and while you can get the display DPI, you cannot get the DPI scaling used by the system.)

**Comment by ChrisOKay** [comment]
Thanks for the insight @Calinou, that explains the behaviour - so I will work around this by reading the project settings directly via Globals.
