### ISSUE TITLE
Add Travis CI build for Mono

### ISSUE THREAD

**Issue by NathanWarden** [godotengine/godot#13038]
The current Mono build as of commit d28763a4c1792dc00fde3d151eaea54f9cf2b8a9 is broken. This is because, understandably, neither the person who made the commit nor Travis CI made a Mono build to ensure this doesn't break the Mono version. My proposal is simply that a Mono build be added to Travis CI for at least one platform, IE Linux or macOS. I'm not convinced we need a Mono build for each platform Linux, Mac, and Windows at this point, although it wouldn't hurt to have all platforms.

**Comment by tagcup** [comment]
I actually did build with mono.
That build was broken presumably due to a gcc bug and was working with perfectly fine with clang.

So it's probably better to have this for all builds because these things depend on compiler versions as well, and mingw is ancient and msvc is a totally different compiler.

**Comment by akien-mga** [comment]
Installing a recent enough Mono version on the CI images would take a while (we'd have to download mono and install it again for *each* PR), so I prefer not to add it for now. I'll reconsider if we get a lot more mono-specific build issues.

**Comment by NathanWarden** [comment]
@akien-mga I agree, that sounds a bit overkill for now.

**Comment by akien-mga** [comment]
Closing for now to bring the issue count down :P
If Mono builds start being problematic this will eventually present itself as something we'll want to do anyway.

**Comment by NathanWarden** [comment]
@akien-mga Sounds good, thanks for all your hard work Remí
