### ISSUE TITLE
The TextEdit component ignores the run-time apply of the skin (theme)!

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#13037]
**All OS, All GPU, Godot Engine 2.1.4-stable**

The TextEdit component ignores the run-time apply of the skin (theme)!
If the script call:

`TextEdit.set_theme(load("res://NewTheme.thm"))`

Nothing will happen, this method the component does not work! I attach a demo.
[TestTheme.zip](https://github.com/godotengine/godot/files/1485588/TestTheme.zip)

**Comment by DimitriyPS** [comment]
Maybe I wrote unclear? (sorry my English)
If I have written and the demo does not convey the essence - let me know, I will try to describe the problem differently.

**Comment by bojidar-bg** [comment]
Does it work for other Control nodes? For example, does it work if you use a Button?

**Comment by DimitriyPS** [comment]
Yes. It works with all components (with whom I already worked before). Not works with only TextEdit component. This can be seen in the demo. I apply a theme to a parent "Panel":

Panel (apply the theme)
|-Label (apply the theme)
|-TextEdit (not apply the theme)

You can apply a theme directly to the component TextEdit. It is also not working.

>>Milestone 2.1 

У меня нет его под рукой, но стоит проверить его в Godot 3.0.

**Comment by DimitriyPS** [comment]
This is fixed in 3.0 Godot.
