### ISSUE TITLE
[3.0 Alpha] No access to data via SRC_... in shaders.

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#13035]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 Alpha build from 18.11.2017 Windows 10

**Issue description:**
No access to data via SRC_... in shaders. + in mat4()  i cant get "sub data" like .xyz.

**Steps to reproduce:**
Try access to any SRC_ data in vertex shader.

**Comment by reduz** [comment]
That stuff is no longer supported, please check the docs for 3.0 shaders

http://docs.godotengine.org/en/latest/learning/features/shading/shading_language.html
