### ISSUE TITLE
KinematicBody2D move_and_collide can't return KinematicCollision2D when target shape is ConcavePolygonShape and KB2D shape is RectangleShape2D

### ISSUE THREAD

**Issue by damarindra** [godotengine/godot#13047]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot V3 f5e85c61039f8ff17805172c7a417747070bbc98

**Issue description:**
KinematicBody2D (Collider : RectangleShape2D) will stuck at the center of ConcavePolygonShape

Open project below, and test it

**Link to minimal example project:**
[KBxConcave.zip](https://github.com/godotengine/godot/files/1485785/KBxConcave.zip)

**Comment by eon-s** [comment]
Maybe related to #10110 (problem with segment based shapes).

If using a CollisionPolygon2D in segment mode, capsule gets stuck in a bad position too (with nulls also).

**Comment by MarianoGnu** [comment]
@reduz this is the "bounciness" issue i mentioned earlier

**Comment by damarindra** [comment]
Minimal project will not show the bounciness, because there is no slide collision normal. Simply just use move_and_slide will make it bouncy

**Comment by MarianoGnu** [comment]
Oh right, i'm using a handmade collision shape, as player (didn't bother to set the snapping to do it) so a non Axis Aligned polygon should make the same effect than the capsule

**Comment by Calinou** [comment]
@damarindra Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by damarindra** [comment]
Just test with project above, It is fixed, but jittering. I kind of forget how it is exactly, but as the title says, now it is working fine.
