### ISSUE TITLE
Godot: can't create buffer for vd 

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#1304]
Engine version: 1.0stable
OS: Windows 7 SP1
Videocard: ATI Radeon x1250 (for laptops, pretty old but still runs unity3d etc. smoothly) 

`At: drivers/gles2/rasterizer_gles2.cpp:3920`
`WARNING: viewport_data_create: Can't create framebuffer for vd` 
` At: drivers/gles2/rasterizer_gles2.cpp:8963 `
`ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Contunuing`

Each time I resize window a bunch of 
` At: drivers/gles2/rasterizer_gles2.cpp:8963 `
`ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Contunuing`
pops up in the console.

What project select looks like:
![Bugged project select window](http://postimg.org/image/ys3tjxi4n/Untitled.jpg)

**Comment by shackra** [comment]
related #1260

**Comment by reduz** [comment]
wish i had hardware to test this, but x1250 is reaaaaally old..

**Comment by eVoLuTiVeMEDIA** [comment]
My Radeon X1550 runs unity as well. 
The problem seems ATI specific though. 
¿r u using SDL? No time to check code but, anyway, congrats for the great work.

**Comment by reduz** [comment]
Unity runs fine in this old hardware because it uses DirectX9. Godot uses
OpenGL 2.1 which is not well supported so nothing to do about it.

**Comment by reduz** [comment]
ATI and NVidia decided to improve OpenGL support in later hardware but by
the time this hardware was already obsolete.

**Comment by vnen** [comment]
Closing this as duplicate of #1260.
