### ISSUE TITLE
RayCast2D "Exclude Parent" doesn't work with Area2D parent

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#13057]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 63283ec

**Issue description:**
RayCast2D's "Exclude Parent" property is ignored if the parent is an Area2D. It still reports collisions with the parent node.

Only applies to Areas; PhysicsBody2D nodes work as expected.

**Steps to reproduce:**
Add a RayCast2D child to an Area2D with CollisionShape2D.
Enable "Area" in RayCast2D's "Type Mask".

`RayCast2D.is_colliding()` reports `true` and `RayCast2D.get_collider()` reports the parent node.

**Comment by eon-s** [comment]
I think in https://github.com/godotengine/godot/blob/master/scene/2d/ray_cast_2d.cpp#L133

```
if (Object::cast_to<PhysicsBody2D>(get_parent())) {
	if (exclude_parent_body)
		exclude.insert(Object::cast_to<PhysicsBody2D>(get_parent())->get_rid());
	else
		exclude.erase(Object::cast_to<PhysicsBody2D>(get_parent())->get_rid());
}
```

Should be `CollisionObject2D`.

**Comment by cbscribe** [comment]
@eon-s I tried making your suggested change but it didn't seem to have any effect.

**Comment by eon-s** [comment]
Oh, there is another place with the same logic (in notification, enter tree), try replacing both (these are the only parts that restricts exceptions to PhysicsBody2D).

**Comment by cbscribe** [comment]
Thanks - I'll try that out asap.

**Comment by cbscribe** [comment]
That seems to have fixed it!
