### ISSUE TITLE
Problems with setting then playing consecutive OGG streams

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#13058]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.10 64-bit, Godot 3.0 build d2bc961.

**Issue description:**
I have a scene that is set to play a piece of looped music, until certain conditions are met at which point it is supposed to stop, load another OGG file (non-looped) and then play that instead.
```        $"/root/World/AudioStreamPlayer".stop ()
        $"/root/World/AudioStreamPlayer".set_stream (preload ("res://Assets/Audio/Music/63_-_Game_Over.ogg"))
        print ($"/root/World/AudioStreamPlayer".stream)
        $"/root/World/AudioStreamPlayer".play ()
```

However, it does not play. Adding a `print ($"/root/World/AudioStreamPlayer".playing)` statement below the play statement shows true.

This seems to share some similarities to #9793.

**Steps to reproduce:**
Have an AudioStreamPlayer set up to play an OGG file, then later change the stream to another OGG file.

**Link to minimal example project:**
https://www.dropbox.com/s/utf3ybl0682phy4/13058_demonstrator.7z?dl=0

**Comment by Sslaxx** [comment]
Definitely related to #9793 - the OGG file was a valid one, but apparently not valid enough for Godot. Resaving the file appears to work!

**Comment by Sslaxx** [comment]
Also just noticed this in the 2D Dynamic Character Control platformer demo; music.ogg does not play (valid file, just not valid enough for Godot's OGG/Vorbis implementation).

**Comment by reduz** [comment]
May be a result of us using stb_vorbis instead of regular OGG. Might need to recompress the files for this, not sure if it can be fixed.

**Comment by reduz** [comment]
will kick for 3.1 in any case

**Comment by Sslaxx** [comment]
Yeah, resaving them solves the problem. It's not unique to Godot either - Rhythmbox also has issues with some OGG files (it also uses STB_Vorbis).

**Comment by reduz** [comment]
Nothing changes so far, and stb_vorbis is still there. We were thinking of adding mp3 support now that it's patent free, which can be an alternative. In any case, kicking to 3.2

**Comment by Sslaxx** [comment]
Closing as it wasn't really a Godot issue (more STB_Vorbis).
