### ISSUE TITLE
Missing `#include <gdnative/rect3.h>` causing binding generators to fail

### ISSUE THREAD

**Issue by Evrey** [godotengine/godot#13050]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Doesn't really matter here.

**Issue description:**

Old code using `godot_rect3` fails to compile with the latest Git version of Godot, due to the renaming to `godot_aabb`. I.e. this issue can be closed.

**Steps to reproduce:**

Include the `gdnative_api_struct.gen.h` in older binding projects expecting `godot_rect3`.

**Link to minimal example project:**

N/A

-----

https://github.com/godotengine/godot/blob/f5e85c61039f8ff17805172c7a417747070bbc98/modules/gdnative/include/gdnative/gdnative.h#L140-L211

Nothing more to say about that, so... yeah. That's a thing lately. D:

**Comment by akien-mga** [comment]
There shouldn't be a `gdnative/rect3.h`, it has been renamed to `aabb.h`.

Would be good if you were a bit more explicit in your issues and respected the issue template though :)

**Comment by Evrey** [comment]
Oh yes, sure, sorry. So it is AABB now...
