### ISSUE TITLE
Radio-button-looking entries for PopupMenu

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#13055]
Currently you can add checkable items to `PopupMenu`s. They'll be displayed with a checkbox-like graphic before the text.

The problem is see is in some menus, options in certain groups are presented like checkable, yet they are mutually exclusive, so the convention about individually checkable items break,

For instance, in the 3D editor, the _View_ dropdown has some options you can enable/disable individually while it also has entries for different numbers of viewports and, yet only one of them can be active at a time, they are presented as checkboxes:
![check-items](https://user-images.githubusercontent.com/11797174/32995443-9f56f62e-cd74-11e7-81e5-fb92bf286d65.png)

It would be nice to be able to add items that look like radio buttons to add more clarity to the UI.

I can add the code and update menus that are displayed as checkable but treated as radios, but I'd need the graphics.

**Comment by djrm** [comment]
we already have radio buttons, but im not sure how they are created, i think you have to put them in a button group, but CheckBox has is_radio flag, and some menus already use it. (like dragging a sprite from the FS dock to the canvas)

**Comment by RandomShaper** [comment]
I think those are true radio button controls in a dialog. I've updated the issue description with an image to make more clear what I'm talking about.

**Comment by djrm** [comment]
radio buttons are CheckBoxes, but they look different because they are have a button group attached, i dont understand why we dont simply add groups where needed., like in that view dialog for example

**Comment by RandomShaper** [comment]
The problem is that it's not a dialog, but a `PopupMenu` (have a look at __scene/gui/popup_menu.*__).

That doesn't create a panel with controls but rather uses custom draw to render the items with their labels, etc. For items set as checkable it's using the *checked* and *unchecked* icons according to whether the item is actually checked or not.

**Comment by djrm** [comment]
oh, i see, in that case the graphics are there `GuiRadioChecked` and `GuiRadioUnchecked` theme wise the only thing needed would be add them to the custom theme icons like `radio_checked` and `radio_unchecked` for `PopupMenu`.
