### ISSUE TITLE
Some editor settings (e.g. mono settings) are not saved

### ISSUE THREAD

**Issue by BrainBlasted** [godotengine/godot#13069]
**OS:** Arch Linux
**Godot Version:** 3.0 Custom build, commit a5939c2

**Issue description:**

Settings under **Editor Settings** for the Mono module do not persist. Discovered with the External Editor settings, but also relevant for the Build Tool setting.

**Steps to reproduce:**

1. Open **Editor Settings**
2. Scroll to Mono
3. Choose a setting to change
4. Restart Godot and check settings

**Comment by akien-mga** [comment]
Likely related to #12988, I'll check it out.

**Comment by akien-mga** [comment]
Hm, it's not only Mono settings, I also get the same issue e.g. for `editors/gridmap/preview_size` and `editors/tilemap/preview_size`. On the other hand stuff in `interface/editor` like the language or hidpi mode seem to be saved fine.

CC @djrm in case it's related to the initial set logic, though I haven't ruled out #12988 fully yet.

**Comment by djrm** [comment]
@akien can you test #13102, i dont have the mono settings.
