### ISSUE TITLE
Mono compilation fails

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#13068]
Using current master, trying to compile any mono project fails with the error `ObjectType/TextEdit.cs(349,77): Unexpected symbol '='`. I tried removing the .local/share/godot/mono directory entirely but I'm getting the same error.
Line 349 is
```cs
public void CursorSetLine(int line, bool adjustViewport, canBeHidden = true, bool arg2 = true)
```
so `canBeHidden` doesn't have type

**Comment by neikeq** [comment]
It's because the second and third parameter is registered as a single one: `"adjust_viewport, can_be_hidden"`.
