### ISSUE TITLE
INFO: Godot's settings/project metadata have moved, migration is manual

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#13064]
Hi there,

Just some info for users of the *master* branch: the location where Godot puts its editor settings and project-specific metadata (as well as the templates) has changed in #12988 for some platforms (Linux and macOS - Windows should be mostly unchanged).

That means that if you're on Linux or macOS, you'll lose your editor settings, list of projects in the project manager, etc. If you want to port them, you can copy the relevant files from the old location to the new one - but it might also be a good idea to start afresh with a brand new config file, as your previous one might have had obsolete stuff.

The new locations:
- Linux: `~/.config/godot` for all settings stuff, `~/.local/share/godot` for data (templates, app_userdata)
- macOS: `~/Library/Application Support/Godot` for everything (you could move the contents of your `~/.godot` there if you want)

Sorry for the breakage, it's one of the last for 3.0 ;)

**Comment by tagcup** [comment]
Are cached non-essential files (stuff that can be generated from project files) also included under `.local/share/godot` too? (like the stuff that does into `.cache`)

**Comment by vnen** [comment]
@akien-mga you changed `editor_settings-$VERSION_MAJOR.tres` to just `editor_settings.tres` so now it conflicts with the 2.1 settings (especially on Windows, where the path is the same). Is there a reason for it? Check #13072.

**Comment by akien-mga** [comment]
> Are cached non-essential files (stuff that can be generated from project files) also included under .local/share/godot too? (like the stuff that does into .cache)

Cached stuff that was in `.godot/tmp` goes in `.cache/godot` now. There is still some project-specific cache in `.config/godot/projects/<name>-<md5sum>/` though, together with project-specific metadata and whatnot - this could maybe be moved to `.cache/godot` I guess.

> you changed editor_settings-$VERSION_MAJOR.tres to just editor_settings.tres so now it conflicts with the 2.1 settings (especially on Windows, where the path is the same). Is there a reason for it? 

Just forgot that Windows was not changing paths and it seemed like a good idea to drop the hardcoded version number, as reduz had also suggested. But obviously it wasn't :)

**Comment by akien-mga** [comment]
Linux and macOS users, you'll probably have to delete one generated file to build properly: https://github.com/godotengine/godot/issues/13076#issuecomment-345606035

**Comment by capnm** [comment]
Can we use .config/godot$VERSION_MAJOR etc. directory, so that the future Godot2 … GodotX versions do not conflict with each other?

**Comment by akien-mga** [comment]
No, nothing predicts that Godot 4 would conflict with Godot 3. All projects I know who used versioned directories end up stuck because they don't know how to port their compatible config from version x.y to version x.(y+1) or (x+1).0.

**Comment by Calinou** [comment]
> All projects I know who used versioned directories end up stuck because they don't know how to port their compatible config from version x.y to version x.(y+1) or (x+1).0.

JetBrains IDEs use versioned directories, and the software features an update assistant that detects older versions (and asks for importing the old settings).

However, versioned directories can make automation (scripting) harder, so it's a trade-off.

**Comment by capnm** [comment]
For example, currently, the script_templates and text_editor_themes are not compatible anyway. If you than need to use/install both Godot versions, it wont work and all distributions need workarounds.

IMHO it would be enough to manage the configs between the minor versions. It's to be expected that the major Godot versions would be in use for a long time at the same time, so the configuration should be independent in my opinion.

**Comment by akien-mga** [comment]
Closing as this issue was just a heads-up, but feel free to continue discussing :)
