### ISSUE TITLE
RemoteTransform2D's docs have it the wrong way around.

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#13066]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 Alpha 2 and current master

**Issue description:**
The [documentation](http://docs.godotengine.org/en/latest/classes/class_remotetransform2d.html) for the RemoteTransform2D node claims that the RemoteTransform2D will copy the transform of the set remote_path and apply it onto itself.
What it actually does is apply its own transformation onto the node at the given remote_path, forcing it to follow along.

I actually think that it might be useful to have a toggle for this, or a counterpart node that does what the docs say, instead of what it actually does.
That way you can set up structures that follow another node's transforms in the scene more easily, without having to dig into the scene tree and add a RemoteTransform2D node into it just to get a temporary particle emitter to emit particles in the right places, when it could be set up so you just pass the path to the node you want it to follow to a RemoteTransform2D and make the emitter a child to that, as the docs say it would work.
But that's just wishful thinking and probably way too situational, point is the docs are confusing!

**Comment by TwistedTwigleg** [comment]
Adding a new node or option should be easy enough to add. I can give it a go if everyone’s okay with it.
(though there’s no way I can get it finished before the feature freeze, so the docs will probably have to be changed)

**Comment by leoddd** [comment]
If it's deemed useful enough, sure! Looking at RemoteTransform2D's source that is probably a really simple addition, too.

**Comment by TwistedTwigleg** [comment]
Yeah, I already have RemoteTransform2D done, so now all that’s left to do is add the same functionality to RemoteTransform.

(And I’ve started working on the docs for both RemoteTranform and RemoteTransfom2D too 😄 )
