### ISSUE TITLE
Signal method gets called within the editor and returns "not found" error

### ISSUE THREAD

**Issue by mthreis** [godotengine/godot#13070]
By adding a signal method to a C# script (such as Control's _resized()), Godot calls it on the editor and returns the error:

core\object.cpp:1127 - Error calling method from signal 'resized': Control(Window.cs)::OnWindowResized': Method not found.

Script:

```
public class Window : Control
{
    void OnWindowResized()
    {
        var size = OS.GetWindowSize();
        OS.SetWindowSize(new Vector2(Mathf.floor(size.x / 2) * 2, Mathf.floor(size.y / 2) * 2));
    }
}
```

![rrh](https://user-images.githubusercontent.com/31781227/32999747-ea68b63c-cd8a-11e7-8e70-6df992e81245.gif)

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by akien-mga** [comment]
Can this still be reproduced in the current master branch?

**Comment by paulloz** [comment]
Yes, but this is not specific to C#. The same error occur with connections GDScript.

**Comment by akien-mga** [comment]
Here's a minimal reproduction project from #19826: [Example Project.zip](https://github.com/godotengine/godot/files/2145875/Example.Project.zip)

**Comment by Skaruts** [comment]
I have this issue but it's not related to C#, but to the `tree_entered` signal. I give a node that signal and connect it, and then each time I switch to another scene and back to the scene where I did this, the editor throws that error in the output. 

 core/object.cpp:1261 - Error calling method from signal 'tree_entered': 'Control::_on_Control_tree_entered': Method not found.

Seems to happen with any kind of node, and both if the signal is connected to the node or the parent. 

To reproduce it I just give a node that signal and connect it, and then each time I switch to another scene and back to the scene where I did this, the editor throws this error in the output. (I also tried it in a blank project, and it behaved the same way.)

I tested this just now using a 3.1 nightly build from [Hugo Lucurcio's site](https://hugo.pro/projects/godot-builds/) that I just downloaded.

**Comment by neikeq** [comment]
@reduz Not a mono issue.

**Comment by DualMatrix** [comment]
This would have to be solved in a way that it still allows for tool scripts to connect to those signals in the editor.

**Comment by akien-mga** [comment]
> This would have to be solved in a way that it still allows for tool scripts to connect to those signals in the editor.

This is not specific to tool scripts, but to any node with a signal attached that can be called by the editor, when the editor itself uses this node (e.g. AnimationPlayer's `animation_finished`). See https://github.com/godotengine/godot/issues/13070#issuecomment-402206704

**Comment by Poobslag** [comment]
I'm still encountering this error in Godot v3.2.2. If a setter/getter emits a signal, and is invoked in a tool script which connects to non-tool scripts, the console will log 'Method not found' errors.

```
tool
extends LineEdit

# Setting this 'melodic' value in the editor causes console errors.
export (String) var melodic: String setget set_melodic

signal melodic_changed

func set_melodic(new_melodic: String) -> void:
	emit_signal("melodic_changed")
```

Here's a simple reproduction project: [signal-errors.zip](https://github.com/godotengine/godot/files/4853159/signal-errors.zip)

Editing the LineEdit's 'melodic' property in the editor throws errors as it tries to send a signal to a non-tool node. I'd expect the signals to just be tossed into the void.

**Comment by akien-mga** [comment]
Please open a new issue, this was fixed two years ago.
