### ISSUE TITLE
Control Constant Properties disappear in Inspector when a Theme is defined

### ISSUE THREAD

**Issue by YeOldeDM** [godotengine/godot#13071]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7. Godot v3.0 0aa476590

**Issue description:**
When setting a Theme for a Control-based node, any Custom Contstant Properties (such as Seperation for V/HBoxContainers) disappears from the inspector. Any value set in these properties seems to still function properly, and the Property returns once the node's Theme is Cleared (often having to "click off" the node and re-select it for the changes to apply).

**Steps to reproduce:**
Add a node which contains Custom Constants. Give it a new Theme. Witness the Custom Constants not displaying in the inspector tab. Clear the Theme and watch it come back.

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by jtaart** [comment]
Yes it is, tested on Godot_v3.0-rc2_win64.
[https://i.imgur.com/P8XvsUV.gifv](https://i.imgur.com/P8XvsUV.gifv)

**Comment by Kobrar** [comment]
Unfortunately I am able to reproduce this error in 3.1 and 3.1.1
1. Add global custom theme
2. Restart engine
3. Custom Constraints disappear
4. Remove global custom theme
5. Restart engine
6. Constraints reappear
