### ISSUE TITLE
Space key is ignored when Shift+W keys pressed

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#13086]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
all

**Link to minimal example project:**
[SpaceBug.zip](https://github.com/godotengine/godot/files/1487304/SpaceBug.zip)

**Comment by Noshyaar** [comment]
Not reproducible here.  Are you certain this is not a hardware issue?

**Comment by Chaosus** [comment]
Oh, I pressed SHIFT+W in notepad and trying to space and its also ignored... Maybe its just my keyboard issue ?

**Comment by Chaosus** [comment]
Yeah, probably not a Godot issue..

**Comment by Sslaxx** [comment]
Keyboard hardware can be very inconsistent, unfortunately.
