### ISSUE TITLE
Project icon as favicon in HTML5 WebAssembly export

### ISSUE THREAD

**Issue by nylnook** [godotengine/godot#13083]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Firefox 57 and Chromium 62 under Archlinux 64bits, Godot compiled today 33ffdba553e90471150bd84067c88a79e874a2aa and WebAssembly template idem

**Issue description:**
This can be done manually, but it would be great if Godot could export automatically the project icon as a favicon in HTML5.
I know this was partially answered in #12543:

> We need ability for users to add a custom icon for their executable, not have to rely on resource hacker

> Problem with this is that it seems to be only doable when exporting from Windows. Cant be done from other platforms. All libraries we tried to do this ended up corrupting the executable.

but as far as I understand this do not apply to HTML5 because it's not about writing it to an executable, but a matter of copying the .png file, renaming to favicon.png, and linking in the HTML file.

For now, the debug console in the browser is complaining about icon missing:
```
**ERROR**: Error opening file: res://icon.png
**ERROR**:    At: core/io/image_loader.cpp:54:load_image() - Error opening file: res://icon.png
```

Thanks for your answer and work !

**Comment by akien-mga** [comment]
Sounds good to me, and shouldn't be too hard to implement. cc @eska014
