### ISSUE TITLE
Add SCons option to delete generated files

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#13089]
As issues like #13088 and #13076 exist (and there's more than that), and this appears to be an issue with auto-generated (*.gen.*) files, then maybe the build system should delete them every time something is compiled.

**Comment by akien-mga** [comment]
I thought about that, but I fear that it would force a rebuild of most of the engine, since there are many generated files used all over the place, so SCons might consider that most of the code changed, even if the generated files are the same (different timestamps). Might be worth testing though.

**Comment by akien-mga** [comment]
Let's change the proposal to be about adding a SCons option to delete generated files instead, or extend the existing `scons -c` so that it takes care of it.

**Comment by romeojulietthotel** [comment]
The side effect feature of SCons might be the right one for this. 

https://bitbucket.org/scons/scons/wiki/SConsMethods/SideEffect

Also as a easy work-around you can always use 

`git clean -fdx`

- f == force removals
- d == dirs too
- x == ignore anything in .gitignore
 
If you aren't sure what that will do try:

`git clean -idx`

- i == interactive and waits for your response

**Comment by Calinou** [comment]
This is already covered by `git clean -dfxi` (see the above comment), closing. You can use `git clean -dfXi` (note the uppercase `X`) to remove only ignored files and not untracked files.

**Comment by akien-mga** [comment]
Note that `scons -c` works fine too, but you need to use the same build arguments as for a build (e.g. `scons p=x11 target=release_debug -c`.
