### ISSUE TITLE
SurfaceTool/MeshDataTool creates unexpected weight values

### ISSUE THREAD

**Issue by rminderhoud** [godotengine/godot#13081]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
4.10.0-38-generic #42-Ubuntu SMP Tue Oct 10 13:24:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
__Godot__: 63283ec

**Issue description:**
Creating a mesh with bones indices and bone weights with `SurfaceTool` and then later checking the data with `MeshDataTool` reveals that weight values are modified. Negative values appear and weights no longer add up to 1.

**Steps to reproduce:**
- Create a mesh using `SurfaceTool`
- Apply a weight to each vertex during ceation
- Load mesh data using `MeshDataTool`
- Read weights data

**Link to minimal example project:**

```gdscript
tool
extends MeshInstance

func _ready():
	var vertices = [
		Vector3(0, 0, 0),
		Vector3(1, 0, 0),
		Vector3(2, 1, 0),
	]
	
	var bones = [
		[1,2,3,4],
		[4,5,6,7],
		[8,9,10,11],
	]
	var weights = [
		[0.1, 0.2, 0.3, 0.4],
		[0.25, 0.25, 0.25, 0.25],
		[0.25, 0.25, 0.25, 0.25],
	]
	
	# assert(vertices.size() == bones.size() == weights.size())
	
	var st = SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	
	for i in range(vertices.size()):
		st.add_bones(bones[i])
		st.add_weights(weights[i])
		st.add_vertex(vertices[i])
	
	st.index()
	var m = st.commit()
	
	var mesh_data = MeshDataTool.new()
	if OK == mesh_data.create_from_surface(m, 0):
		for i in range(mesh_data.get_vertex_count()):
			var b = mesh_data.get_vertex_bones(i)
			var w = mesh_data.get_vertex_weights(i)
			
			print(b)
			print(w)
			
			assert(b == PoolIntArray(bones[i]))
			assert(w == PoolRealArray(bones[i]))
```

__Output__:
```
[1, 2, 3, 4]
[-0.800015, -0.6, -0.400015, -0.2]
[4, 5, 6, 7]
[-0.500023, -0.500023, -0.500023, -0.500023]
[8, 9, 10, 11]
[-0.500023, -0.500023, -0.500023, -0.500023]
```

**Comment by akien-mga** [comment]
Looks like the weights you pass end up as `-1 + 2 * orig_weight`.

**Comment by bojidar-bg** [comment]
Potentially found the culprit,
https://github.com/godotengine/godot/blob/0968c8d2f65f7ac6e0d6b3718ee1028b229b3353/servers/visual_server.cpp#L1343-L1353
https://github.com/godotengine/godot/blob/0968c8d2f65f7ac6e0d6b3718ee1028b229b3353/servers/visual_server.cpp#L607-L618

**Comment by gad-o** [comment]
> Potentially found the culprit,

I tried chage :
`
w[j * 4 + k] = float(v[k] / 65535.0) * 2.0 - 1.0; 
`
to:
`
w[j * 4 + k] = float(v[k] / 65535.0); 
`
output :
[1, 2, 3, 4]
[0.099992, 0.2, 0.299992, 0.4]

**Comment by bojidar-bg** [comment]
I feel it might be better to fix it on line 613 instead.

**Comment by rminderhoud** [comment]
@bojidar-bg I'm happy to try and fix it but I must confess I don't understand the compression that well. What is the issue with @gad-o's solution?

**Comment by bojidar-bg** [comment]
There is no issue -- it must be tested, and if it works.. well, it works! I just didn't really __feel__ that would be the actual solution, but that can be ignored.
