### ISSUE TITLE
Shaders work in editor but not in the game itself

### ISSUE THREAD

**Issue by abhaskumarsinha** [godotengine/godot#13091]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux 64 bit, Kali Linux (Derived from Linux Debain)
4GB RAM
INTEL (R) HD GRAPHICS
*Bugsquad edit:* Godot 2.1.4

**Issue description:**

Shaders were written to produce reflection effect. Unfortunately, they run fine in editor and go absolute black in the time of preview, There are lights, single camera and very simple scene.

Please don't say to to move to Godot 3, because My GPU Doesn't supports that.
[reflection.zip](https://github.com/godotengine/godot/files/1487687/reflection.zip)

**Comment by akien-mga** [comment]
What number of Intel HD graphics do you have? What drivers and their version? (Both should be mentioned by `glxinfo | grep -i opengl`)

**Comment by eon-s** [comment]
Can you show a picture of what you see in editor and running? To know better what is expected from the shader.

**Comment by eon-s** [comment]
Just some things I have noted on the example project:
- Both cubemaps are missing images (there are errors on the debugger that refers to it)
- The water custom node does not have a WorldEnvironment assigned (I do not know if this adds issues)
- One of the cubemap is embedded in the tscn file making it huge (100+ MB file, mostly in 4 lines) and may be breaking the scene.

**Comment by abhaskumarsinha** [comment]
I get the world, I've added cubemap in testcube > material > shader > Cubemap, but when I run it, its black, but works fine in editor. i suspected that it must be due to insufficient light in the scene, so I turned one the unshaded one, still I get nothing. 
World is normal, but cube is also becoming black... @eon-s @akien-mga @bojidar-bg

**Comment by abhaskumarsinha** [comment]
@eon-s  @akien-mga  @bojidar-bg want to know, do you also have same problem when you are using the project?
I've uploaded a small and potable project file, for your ease.

[reflection 2.zip](https://github.com/godotengine/godot/files/1487886/reflection.2.zip)

If you don't have that problem, then I'll install a different OS To test it :)

**Comment by abhaskumarsinha** [comment]
@eon-s @akien-mga @bojidar-bg  I'm definitely sure that its a **BUG IN GODOT**.
Problem is not in renderer.

When I add images in cubemap of the Shader of the Test Cube, it shows that it has been added and also works great in editor.

**but, when I save the project and re-open it, Woh!! Cube again turns to black, fully black.**

**Comment by eon-s** [comment]
Is sure a bug but I don't think is a bug in shaders, is the resource, for some reason it put the images inside the cubemap resource breaking the scene and sometimes the resource too (it does not get saved/loaded correctly):

![brokenscene1](https://user-images.githubusercontent.com/10215987/33023019-ac74560a-cde5-11e7-94bd-7470cc27c714.png)
_one image, the rest empty_

Which is this on the file:
![brokenscene2](https://user-images.githubusercontent.com/10215987/33023045-c5a324b2-cde5-11e7-9c3a-7b2498eef969.png)
_that is a single line that never ends_

I have tried with other resource formats, cbm and xcbm work but only in lossy format, uncompressed breaks them too.

Check this, there is a tres, cbm and xcbm, saved as lossy but the inspector says uncompressed (?):

[reflection-manycubemaps.zip](https://github.com/godotengine/godot/files/1488022/reflection-manycubemaps.zip)

**Comment by abhaskumarsinha** [comment]
@eon-s I think that there is a bug in render too because even if loads perfectly for the first time, it doesn't runs in game. 
Not sure what solution you gave  to me.

**Comment by abhaskumarsinha** [comment]
@eon-s mine same too,  only first one loads,  rest Doesn't...

**Comment by eon-s** [comment]
No solution, just exposed the problem on the cubemap resource, check the project and you should have no issues seeing it unless it is uncompressed or in tres format.

**Comment by abhaskumarsinha** [comment]
How to get it into tres format?  @eon-s

**Comment by eon-s** [comment]
First try to clean the scene removing manually the resource, once broken it can remove the resource, it seems.
Then create a new cubemap and save it as tres or another cubemap format with the disk icon on the inspector (inside the cubemap).

**Comment by OGMP-Gyrth** [comment]
Got some help from eon-s in the Discord channel. Seems like the tscn format has a problem where it doesn't save the cubemap images correctly. So when you reopen the project the cubemap images is all empty again. And when setting them back to the correct images, the cubemap only shows up in the editor. Not while running the game. 

**As a temporary workaround make a new scene and save as .scn in stead of .tscn.** 

I've included an example project to reproduce. 
[Godot_testing.zip](https://github.com/godotengine/godot/files/1516648/Godot_testing.zip)

**Comment by eon-s** [comment]
This may be related to the resource saver and (at least) the cubemap resource, probably never worked for the tscn/tres formats (3D demos are in scn format).

**Comment by abhaskumarsinha** [comment]
@eon-s  can you tell how to do it, step by step, i'm not able to get it working

**Comment by jrc03c** [comment]
@abhaskumarsinha: I ran into the same problem until I noticed that there's a little "save" icon at the top of the inspector. Saving the scene wasn't enough; I had to save the materials via that icon. Once I had done that, my material changes showed up in the editor *and* the game.

![](https://i.imgur.com/2RuPBc3.png)

**Comment by akien-mga** [comment]
There were indeed issues saving CubeMaps in TSCN/TRES in Godot 2.1, but those should be fixed in 3.0+.

As we're no longer actively developing the 2.1 branch, closing this issue.
