### ISSUE TITLE
Code folding not always works for whole functions

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13107]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**
When folding a function, would be good to check for comments and white characters that can break indentation. Currently when I try to fold such function:
```
func someCode():
	some();
#	this is a comment
	otherFunc()
``` 
Only first line folds:
![func_folding](https://user-images.githubusercontent.com/6129594/33035910-117f0800-ce2d-11e7-8889-b2c31f2d3b62.gif)

**Comment by kubecz3k** [comment]
cc @ianb96

**Comment by ianb96** [comment]
Ah, This used to work, but I had to remove it because comments at col 0 outside of functions were able to be folded where they shouldn't be. I'll try to figure out a solution that solves both problems.
