### ISSUE TITLE
Double-click selection recently stopped working (bisected)

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#13109]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0, 82ad05a20ef4420122b18eadf3835c4a8a49ba19, Arch Linux (weekend-ish), GCC

**Issue description:**

When double clicking a word in the script editor, it would select a word on the same colon but on the next line.
When using triple-click selection, it would not select the whole line in the majority of the cases.

Here is a gif (I start by clicking around randomly, and afterwards double clicking)
![peek 2017-11-20 20-37](https://user-images.githubusercontent.com/5276727/33036780-22d57ee4-ce38-11e7-8b00-034927e67f8f.gif)

I ran a bisect, and it turned out the bad commit is 1e59169d2d62edc25d5c046ff119cdd9bc991a18, cc @ianb96

**Steps to reproduce:**
1. Open a script
2. Write two consecutive lines of code, with no blank line inbetween
3. Try to select a word on the first of those two lines
4. See that the word on the next line is selected instead.
5. Profit by making a PR.

**Link to minimal example project:**

This isn't project-specific.

**Comment by kubecz3k** [comment]
I was able to reproduce with provided reproduction steps

**Comment by Valentactive** [comment]
Can confirm to have the same issues. In my case it happens a little more random when it works and when not. Also on Linux but Ubuntu 16.04.3 and my build is compiled with Clang. Tested with both the normal mode and self contained mode (so with new editor settings and with old ones).

**Comment by bojidar-bg** [comment]
Update: Seems to happen only when there is no scrollbar in the script editor.

**Comment by Valentactive** [comment]
Yes I can confirm, when scrollbar's are available everything returns to normal behavior.
