### ISSUE TITLE
Filesystem dock acting weird on resize

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13103]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
d413f372be9dac1bdd9ae6a709de910d8691b58f

**Issue description:**
When FileSystem is added below another dock it acts weird on resize. I quite often want to increase it's Y size to see more folders/files. Currently instead of seeing more files in a folder, tree view is activated at some size point. To make things worse, decreasing the size hides folder view completely:
![filesystemdock](https://user-images.githubusercontent.com/6129594/33033226-ff6f0326-ce23-11e7-8142-e8e81e710a88.gif)

I think the tree view should not be activated in such automagical way :)

**Comment by YeldhamDev** [comment]
Can't reproduce this. Probably has been fixed.

**Comment by akien-mga** [comment]
Yeah I think some changes were made to this behaviour even before 3.0 was released. Feel free to reopen if it's not the case :)

**Comment by kubecz3k** [comment]
Yes it works well in 3.0.3 rc2 :)
