### ISSUE TITLE
Kinematic Character 3D and Platformer 3D not working

### ISSUE THREAD

**Issue by louisVottero** [godotengine/godot#13118]
**Issue description:**
I'm using the latest off of Github as of the time writing this message. 
Wasn't sure if I should submit this.  I figure you guys are already aware, but thought I should just in case. 
I think after the last update to move_and_slide for KinematicBody the Kinematic Character 3D and Platformer 3D demos are not working.  I also noticed that is_on_floor()  command doesn't seem to be working.

**Steps to reproduce:**
Open Kinematic Character 3D and try moving the character. Nothing happens. 

**Link to minimal example project:**
Should just need to open Kinematic Character 3D or Platformer 3D demos to test.  They both do not work.  You can't move the character.

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by djrm** [comment]
might be  a problem with the demos since fixed_process was changed, but im not sure.

**Comment by djrm** [comment]
it was changed to `physics_process` in case you dont know.

**Comment by AndreaCatania** [comment]
As said by @djrm you have to change fixed_process to physics_process. I have to fix the demos

**Comment by djrm** [comment]
@AndreaCatania the demos seem to be alright.

**Comment by louisVottero** [comment]
I think this solved some of my issues

https://github.com/godotengine/godot/issues/13002

**Comment by kubecz3k** [comment]
Tested platformer and kinematic demo on c846e49a7d3439d9aef5d499ad403304d89a3b3c They are working now. Probably as @louisVottero said it was the same issue as #13002
