### ISSUE TITLE
VisibilityNotifier enter & exit camera signals are triggered in the editor

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#13115]
I'm mostly raising this to check if this is the expected behaviour? I noticed when I set this up on a scene, it was triggering in the editor as I moved the editor camera about. Sometimes it causes errors in trying to call the script function it's connected to (I guess if the script doesn't have tool enabled?) and it can also disconnect the connection if one shot is enabled. 

I was about to fix it, but just wanted to check if anything in the editor relies on the camera_enter & camera_exit signals, or if VisibilityNotifier is used at all in the editor, @reduz ?

**Comment by Toshiwoz** [comment]
I know it was 2 years ago but, where you using the tool mode?
Also, was it in version 2.1?

**Comment by Toshiwoz** [comment]
@akien-mga, I think it can be closed(?)

I have tried like 3 months ago, and I don't recall any problem with this.
It can be that it was triggered because the script was in tool mode.

**Comment by akien-mga** [comment]
Thanks, closing for now.
