### ISSUE TITLE
Export attribute don't work

### ISSUE THREAD

**Issue by Tommel1234** [godotengine/godot#13110]
Windows 10 with a fresh build with mono from today

**Issue description:**
[Export] attribute don't work... I can't made it appear in the editor. It used to work with oldest build.
I don't know if I am the only one.. :/ I had try to reboot godot , build the project with visual studio.

[Project-GQ.zip](https://github.com/godotengine/godot/files/1488880/Project-GQ.zip)

**Comment by kubecz3k** [comment]
cc @neikeq, when issue was open the newest commit was 82ad05a20ef4420122b18eadf3835c4a8a49ba19

**Comment by Tommel1234** [comment]
I rebuild the source again, and now it's working ! I don't know how but.. resolve now ! work fine !
