### ISSUE TITLE
[3.0 Alpha2] Funny rotation editor's camera around object.

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#13114]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 Alpha2 Windows 10

**Issue description:**
When rotate around selected object, editor camera remember rotation and if press num1(front view) or another button. Camera repeat all rotation backward, even if you make 3-5 turn around.

**Comment by Calinou** [comment]
@sezit Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by sezit** [comment]
@Calinou No, everything fine.

**Comment by Calinou** [comment]
@sezit Thanks for replying :slightly_smiling_face: I'll close this then.
