### ISSUE TITLE
Code folding always scroll to 2nd line when first line of code get focus

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#13111]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
all

**Issue description:**
First line of code always scroll back to 2nd line when mouse click on it(or even keyboard focus), problem in Code folding(disabling it solves the problem)

![Alt Text](https://thumbs.gfycat.com/VerifiableMenacingHumpbackwhale-size_restricted.gif)

**Comment by Chaosus** [comment]
cc @ianb96

**Comment by gad-o** [comment]
https://github.com/godotengine/godot/blob/5ff84070ca3604b43e86562a3d000ed924a604a2/scene/gui/text_edit.cpp#L3469-L3470
