### ISSUE TITLE
Animation bug

### ISSUE THREAD

**Issue by Khyzan** [godotengine/godot#13125]
Windows 8.1. Godot version 2.1.4

Animation delay
I have made the ability to ledge grab for my character with a set_pos command and an animation technique. The character touches the ledge, then it teleported to the top of it with the set_pos command, and at the same time an animation is supposed to play to simulate climbing. **The animation itself doesn't play until 1 frame AFTER the teleportation. It isn't game breaking, but it is noticeable and awkward.**

If you don't want to duplicate my issue, or if the tutorial doesn't work on your end, there is a video of my issue at the end of the tutorial. Maybe just seeing it can help.

**Steps to reproduce:**
What you will need from the start:
A character capable of walking and jumping.
2 noticeably separate animations. One for movement, one for the ledge grab itself.
A capable "floor" or "ledge.

Make an area2D with a collision for an "activation" spot.
![tutorial pic 1](https://user-images.githubusercontent.com/33849097/33047958-490b6a86-ce0d-11e7-8798-4c25bd5f7b27.PNG)
![tutorial pic 2](https://user-images.githubusercontent.com/33849097/33047961-4f320d16-ce0d-11e7-9f18-87c56511e89e.PNG)

Next, add an area_enter( object_area ) signal to the activation spot.
![tutorial pic 3](https://user-images.githubusercontent.com/33849097/33048222-a28e9ac8-ce0e-11e7-918d-ed3898953694.PNG)
This should be attached to the character node that has the script. 
Mine is called _front_activation( area )
Let it "Make_func" then we will get back to it later.

Make a completely separate area2D outside of the playable character. Create a collision_shape for it, but place it lower down and to one of it's sides. The collision_shape will detect the character activation area. The origin of the Area2D is where your character will be brought to for a "ledge grab".
It would be best to have "floor" or "ledge" to know where to place the collision_shape.

![tutorial pic 5](https://user-images.githubusercontent.com/33849097/33048521-30991694-ce10-11e7-820d-1d1b2d8a7092.PNG)

Next to the "signals" window, there is a window for "groups". Create a group for the "Ledge grab" node and let's call it "Ledge".

Now, lets go back to the playable character script.
Write down the following into the script in the Area_enter script that was added earlier.
if area.get_groups(). has("Ledge"):
set_pos(area.get_pos())

Should look something like this.
![tutorial pic 4](https://user-images.githubusercontent.com/33849097/33049040-0a24c8ac-ce13-11e7-97a8-fdf293bb0169.PNG)

You character should teleport to the origin of the "ledge grab" node.

Now to add an animation
Add the following into the "var" area in the beginning of the script.
![anim tutorial 1](https://user-images.githubusercontent.com/33849097/33049231-e18fecea-ce13-11e7-83d1-937ce96c4e5a.PNG)

Next, add the following into the "func _process(delta)" area
![anim tutorial 2](https://user-images.githubusercontent.com/33849097/33049322-5be02b04-ce14-11e7-8b6c-ead0d07e49e4.PNG)

Now add an "anim" command with the title of the ledge grab animation. Mine is called "Ledge_cycle"
![anim tutorial 3](https://user-images.githubusercontent.com/33849097/33049462-13a1bd70-ce15-11e7-92c5-4e265ecc76b5.PNG)

Depending on how the character was made, it may have left-over momentum after the "teleportation" happens. You may use a different technique for moving your character, but I use the following to fix my issue.
![anim tutorial 4](https://user-images.githubusercontent.com/33849097/33049611-d0d7c95c-ce15-11e7-8c25-dcf1f1456a40.PNG)
This will stop the character from having unwanted movement or momentum after the set_pos has happened.

**Tutorial done**

**Example video**
The first 2 ledge grabs you see will be how I want it. The third ledge grab is where my issue is. The character doesn't start the ledge grab animation until 1 frame after the "teleport". I want the animation to ALWAYS be in sync with the teleport. 
Sometimes it works, but sometimes it doesn't, so it's pretty difficult to code around it.

[GLITCH Example.zip](https://github.com/godotengine/godot/files/1489675/GLITCH.Example.zip)

Is there a way to fix my issue?

**Comment by sketchyfun** [comment]
Not sure if this is the case, but you might be having this issue as you're setting the position when the collision happens but the animation is being set sometime afterwards (basically when _process() is executed again, which could be a frame or more later). Have you tried playing the animation at the same time as doing the set_pos? I see you have some logic to check that the new animation is different from the one currently being played, you could move this to it's own function like so:

`func play_animation(anim):
    if anim_player.get_current_animation != anim:
        anim_player.play(anim)`

and then call that immediately after your set_pos call. Not sure if it'll help, but you could also try setting your animation player to use the fixed processing mode rather than idle.

**Comment by Khyzan** [comment]
The animation is set to activate at the same time as the set_pos. One activation with two functions, that is what the Area_Enter signal was supposed to do. :c

**Comment by sketchyfun** [comment]
You're setting the anim variable at the same time, but anim_player.play() isn't being called until _process() is called next frame.

**Comment by Khyzan** [comment]
it works half of the time, mostly when the character is still in upward momentum. Should I add the anim_player.play() into a different process? like, Fixed_process or something? I'm still getting used to the engine.

**Comment by sketchyfun** [comment]
Well first I'd try what I suggested and move your anim play code into it's own function which you can then call just after your set_pos call. You could try using fixed_process instead since that happens every physics frame, but it might still happen. The issue is because set_pos and the animation play() aren't happening at the same time.

**Comment by Khyzan** [comment]
The first suggestion hasn't worked yet, but I could experiment with it.

**Comment by sketchyfun** [comment]
Setting your animation player's process mode to 'fixed' might help too

**Comment by eon-s** [comment]
You can call the "teleport" from the animation to sync things better (apart from the fixed mode).

**Comment by Dillybob92** [comment]
If you don't mind (sensitive code, or whatnot), but could you please post an example project of this. I asked on Discord couple days ago but seems like it got lost in messages :)

**Comment by Khyzan** [comment]
post an example project? You want to try the game itself?

PS. making the animation a function hasn't worked, there is still a delay.

**Comment by Dillybob92** [comment]
Yes please, I want to see if I can find the bug or solution

**Comment by Khyzan** [comment]
I will if other experimental solutions don't work, i don't want to give my work to just anyone ;P

**Comment by Dillybob92** [comment]
Yeah,  if you have "sensitive code or whatnot" you can just create the issue in a separate scene with just the animation/movement code and send that over. It is understandable, however :)

**Comment by Khyzan** [comment]
My issue has been fixed, I used a method similar to a call func track in the animation area. It didn't work at first, but I eventually got it. Thank you for trying to help at least 👍
