### ISSUE TITLE
"Triangulate" option of Better Collada Exporter not compatible with "Shape-Keys" (morph) animations.

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1312]
Hi,

With recent custom build.

The "Triangulate" option of the Better Collada Exporter is not really compatible with "Shape-Keys" (morph) animations.

If the "shape-key" animated mesh contains polygons other than triangles, and if it is exported with "triangulate" option set to ON, then, once imported into Godot, the vertices of each morph targets won't match. (I tried with a simple deformed cube)

If you re-export it with "triangulate" to OFF, then, Godot will warn you about "Primitive polygon not well supported (concave shape may fail)".

The only workaround i've found is to triangulate the mesh using a modifier into Blender, just before creating the Shape-keys.

**Comment by akien-mga** [comment]
@ndee85 @slapin As you have some experience with Blender and the BCE, can you check if the above is still valid, and/or give ideas on what should be improved?

**Comment by bojidar-bg** [comment]
Pretty bump... Also, shouldn't this be moved to better-collada repo?

**Comment by Jubjub** [comment]
I can confirm this, unless the mesh is triangulated from Blender itself, shapekeys will mess it up on godot.

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/collada-exporter/issues/69.
