### ISSUE TITLE
Heap Corruption when baking Global Illumination Probe.

### ISSUE THREAD

**Issue by antonyjones67** [godotengine/godot#13128]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Microsoft Windows Home. Micro-Star I7. Geforce GTX 1060.
Godot Engine 3.0.alpha.custom_build.6fd1b94.

**Issue description:**

Baking Global Illumination Probe crashes. Should not crash. Things get in bad state.

Critical error detected c0000374. Heap corruption.
This call stack is a red herring. Since it is a heap corruption.

Callstack:
 	ntdll.dll!00007fffca69771e()	Unknown
 	ntdll.dll!00007fffca69df0a()	Unknown
 	ntdll.dll!00007fffca644f22()	Unknown
 	ntdll.dll!00007fffca657d69()	Unknown
 	ntdll.dll!00007fffca5caf7e()	Unknown
>	godot.windows.tools.64.exe!_malloc_base(unsigned __int64 size) Line 34	C++
 	godot.windows.tools.64.exe!Memory::alloc_static(unsigned __int64 p_bytes, bool p_pad_align) Line 62	C++
 	godot.windows.tools.64.exe!Vector<wchar_t>::_copy_on_write() Line 224	C++
 	godot.windows.tools.64.exe!Vector<wchar_t>::resize(int p_size) Line 280	C++
 	godot.windows.tools.64.exe!String::operator+=(const String & p_str) Line 222	C++
 	godot.windows.tools.64.exe!String::operator+(const String & p_str) Line 197	C++
 	godot.windows.tools.64.exe!ProgressBar::_notification(int p_what) Line 63	C++
 	godot.windows.tools.64.exe!ProgressBar::_notificationv(int p_notification, bool p_reversed) Line 37	C++
 	godot.windows.tools.64.exe!Object::notification(int p_notification, bool p_reversed) Line 851	C++
 	godot.windows.tools.64.exe!CanvasItem::_update_callback() Line 345	C++
 	godot.windows.tools.64.exe!MethodBind0<CanvasItem>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 139	C++
 	godot.windows.tools.64.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 839	C++
 	godot.windows.tools.64.exe!MessageQueue::_call_function(Object * p_target, const StringName & p_func, const Variant * p_args, int p_argcount, bool p_show_error) Line 259	C++
 	godot.windows.tools.64.exe!MessageQueue::flush() Line 306	C++
 	godot.windows.tools.64.exe!SceneTree::iteration(float p_time) Line 462	C++
 	godot.windows.tools.64.exe!Main::iteration() Line 1682	C++
 	godot.windows.tools.64.exe!ProgressDialog::task_step(const String & p_task, const String & p_state, int p_step, bool p_force_redraw) Line 205	C++
 	godot.windows.tools.64.exe!EditorNode::progress_task_step(const String & p_task, const String & p_state, int p_step, bool p_force_refresh) Line 3299	C++
 	godot.windows.tools.64.exe!EditorProgress::step(const String & p_state, int p_step, bool p_force_refresh) Line 795	C++
 	godot.windows.tools.64.exe!GIProbeEditorPlugin::bake_func_step(int p_step, const String & p_description) Line 76	C++
 	godot.windows.tools.64.exe!GIProbe::bake(Node * p_from_node, bool p_create_visual_debug) Line 1196	C++
 	godot.windows.tools.64.exe!GIProbeEditorPlugin::_bake() Line 37	C++
 	godot.windows.tools.64.exe!MethodBind0<GIProbeEditorPlugin>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 139	C++
 	godot.windows.tools.64.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 839	C++
 	godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1120	C++
 	godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1166	C++
 	godot.windows.tools.64.exe!BaseButton::_gui_input(Ref<InputEvent> p_event) Line 138	C++
 	godot.windows.tools.64.exe!MethodBind1<BaseButton,Ref<InputEvent> >::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 815	C++
 	godot.windows.tools.64.exe!Object::call_multilevel(const StringName & p_method, const Variant * * p_args, int p_argcount) Line 673	C++
 	godot.windows.tools.64.exe!Object::call_multilevel(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 780	C++
 	godot.windows.tools.64.exe!Viewport::_gui_call_input(Control * p_control, const Ref<InputEvent> & p_input) Line 1461	C++
 	godot.windows.tools.64.exe!Viewport::_gui_input_event(Ref<InputEvent> p_event) Line 1795	C++
 	godot.windows.tools.64.exe!Viewport::input(const Ref<InputEvent> & p_event) Line 2382	C++
 	godot.windows.tools.64.exe!Viewport::_vp_input(const Ref<InputEvent> & p_ev) Line 1306	C++
 	godot.windows.tools.64.exe!MethodBind1<Viewport,Ref<InputEvent> const & __ptr64>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 815	C++
 	godot.windows.tools.64.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 839	C++
 	godot.windows.tools.64.exe!Object::call(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 763	C++
 	godot.windows.tools.64.exe!SceneTree::call_group_flags(unsigned int p_call_flags, const StringName & p_group, const StringName & p_function, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 246	C++
 	godot.windows.tools.64.exe!SceneTree::input_event(const Ref<InputEvent> & p_event) Line 403	C++
 	godot.windows.tools.64.exe!InputDefault::parse_input_event(const Ref<InputEvent> & p_event) Line 336	C++
 	godot.windows.tools.64.exe!OS_Windows::WndProc(HWND__ * hWnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam) Line 577	C++
 	godot.windows.tools.64.exe!WndProc(HWND__ * hWnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam) Line 762	C++
 	[External Code]	
 	godot.windows.tools.64.exe!OS_Windows::process_events() Line 1763	C++
 	godot.windows.tools.64.exe!OS_Windows::run() Line 2122	C++
 	godot.windows.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 149	C++
 	godot.windows.tools.64.exe!_main() Line 171	C++
 	godot.windows.tools.64.exe!main(int _argc, char * * _argv) Line 183	C++

**Steps to reproduce:**
This bug does not always happen. I have an Asset that has been fairly reliable, but it is an Unreal Asset that I converted to work with Godot. It is quite large. It is a 286k zip file. Is it safe to add here? Since it is an Unreal Sample?

**Link to minimal example project:**

**Comment by antonyjones67** [comment]
It is missing. Notice under steps to reproduce. "I have an Asset that has been breaking fairly reliably, but it is an Unreal Asset that I converted to work with Godot. It is quite large. It is a 286k zip file. Is it safe to add here? Since it is an Unreal Sample?"

**Comment by dragmz** [comment]
@antonyjones67 Can you share the example project, please?

**Comment by reduz** [comment]
I tried your asset and it also does not freeze. I wonder how it could be reproduced..
if you can manage a simpler project that would be great

**Comment by reduz** [comment]
i couldn't reproduce. also the baker was rewritten so this may no longer be a bug. Please reopen if you can reproduce again.
