### ISSUE TITLE
[GDNative] SpatialMaterial::set_emission_operator function breaks godot-cpp compilation

### ISSUE THREAD

**Issue by opcon** [godotengine/godot#13126]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

godot: master, commit 5ff84070ca3604b43e86562a3d000ed924a604a2
godot-cpp: master, commit GodotNativeTools/godot-cpp@e72f4beec1b091edf6f16a0fe27d5ed13ca450c2
godot_headers: master, commit GodotNativeTools/godot_headers@884b3f90a58b0951d23c6625a3295f44b5ae5a1b

**Issue description:**

Commit 7010ee3cb980fca18248fa168a4dabd78cf51e9d introduced the `SpatialMaterial::set_emission_operator` method which is bound in GDScript as 

```c++
ClassDB::bind_method(D_METHOD("set_emission_operator", "operator"), &SpatialMaterial::set_emission_operator);
```

This change breaks the compilation of godot_cpp as `operator` is a reserved keyword in c++ and so can't be used as an argument name.

**Comment by sheepandshepherd** [comment]
There are other illegal identifiers like this elsewhere, but godot-cpp's binding generator already has an `escape_cpp` function to rename them. `operator` just needs to be added to the list of keywords [here in binding_generator.py](https://github.com/GodotNativeTools/godot-cpp/blob/master/binding_generator.py#L704).

**Comment by jahndis** [comment]
Can confirm adding the following patch in https://github.com/GodotNativeTools/godot-cpp gets past that compile error. However, it looks like the cpp_bindings repo is having other compilation issues? I specifically ran into src/VisualServer.cpp:13:20: fatal error: AABB.hpp: No such file or directory
 #include <AABB.hpp>. Would it still be good to create a PR for this?

```
diff --git a/binding_generator.py b/binding_generator.py
index d770f29..9853a5d 100644
--- a/binding_generator.py
+++ b/binding_generator.py
@@ -713,6 +713,7 @@ def escape_cpp(name):
         "switch":   "_switch",
         "export":   "_export",
         "template": "_template",
+        "operator": "_operator",
         "new":      "new_"
     }
     if name in escapes:
```

**Comment by opcon** [comment]
Yeah the cpp bindings also need to be updated for the `Rect3 -> AABB` rename, the `godot_gdnative_api_struct` split/rename and the removal of the `godot_string_c_str()` function.

I have fixed the cpp bindings compilation with the latest master, and can create a PR to the godot-cpp repo with the fixes? But @karroffel might have already fixed these issues locally

**Comment by karroffel** [comment]
The C++ bindings need an update anyway, so I'll look into this!

**Comment by karroffel** [comment]
Should be fixed
