### ISSUE TITLE
Exported NodePath behavior in the Inspector

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#13127]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 x64, Godot Master build 0aa4765

**Issue description:**

When clicking on the resource menu button for an exported NodePath variable in the Inspector (the little rectangle icon), it does not behave as expected in every case where the value is not currently Null.
If the variable was initialized as an empty string instead of Null, then opening the menu will show a LineEdit labelled "string:" instead of the expected button menu, which simply copies its contents to the value field when you hit enter.
Even if you change the variable's value through this misfit LineEdit, the resource icon will only bring up this LineEdit again on click, UNLESS you select the value field itself with your mouse before clicking on the icon, in which case it brings up the expected button menu with `Assign`, `Clear` and a third option named `Select Node` that does not seem to do anything and extends out of the box.

This third option always appears, no matter how the node was initialized, if the value is anything other than Null when clicking the menu icon. The only time it does not is when it is set to Null.

Lastly, if the Node *is* initialized as Null (eg by doing `export(NodePath) var test`, then clicking on the `Clear` button in the icon menu will reset it to an empty string instead of setting it back to Null. Oddly enough the behavior I described above won't show for this variable, even though it's now set to an empty string just like that one.

Visuals to make it easier to wrap your head around:
![reducedsize](https://user-images.githubusercontent.com/20242421/33052107-8ea50042-ce6d-11e7-913b-f84ac1fbde00.gif)

**Steps to reproduce:**
Either:
1. Export a NodePath variable and initialize it as an empty string (`Test` in the GIF above).
2. Click on its menu button. Instead of buttons, the "string:" LineEdit opens.
2. Select the value field, then click on the menu button. The button menu opens, but there will now be a third option, `Select Node`, that does nothing as far as I can tell.

Or:
1. Export a NodePath variable without initialization (`Test 2` in the GIF above).
2. Click on "Clear" in its menu. The value will be set to an empty string instead of Null.
3. When clicking on its menu again, `Select Node` appears again.

**Comment by sketchyfun** [comment]
Just a note: 'Select Node' is supposed to highlight the currently assigned node in the scene tree I believe, it's not doing anything because it's not a valid node path

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment]
This code no longer exists in Godot, inspector was re-written, so this issue can be safely closed.
