### ISSUE TITLE
3D Editor slows down every 60 seconds

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#13124]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7
GeForce GTX 760
Godot built from master (commit 3962181)

**Issue description:**
I've noticed that roughly every 60 seconds the 3D editor will slow down for about 5-6 seconds before returning to normal. If I switch the new editor FPS counter on, it averages around 26 fps (which already seems kinda low? maybe it's the editor updating less frequently to save resources, this is on an empty scene)  but when the slow down occurs, it drops to around 10 fps.

There's no errors in the output window or the console when this happens, and I don't notice a spike in CPU from any other program on my PC, so I don't think it's something else slowing my system down. It's definitely a new thing, it didn't happen on a build from a few days ago as far as I can remember.

**Steps to reproduce:**
Open empty 3D scene, turn on the new fps counter by clicking the [perspective] label in top left corner of the viewport and enabling 'View FPS'

Wait a minute or so and see if the FPS drops. It's definitely happening at a fixed interval for me, roughly every minute or so.

**Link to minimal example project:**

**Comment by Krakean** [comment]
1. Is it happens to you only when View FPS enabled? 
2. Have you checked your issue using Project Settings->Debug->Settings - "Print FPS" option (that print fps just to output window)?
3. Have you checked not empty scene, with some repeating animations for example? Just to check whether it happens for you in real-time while you actually doing something in viewport, not just sitting and wait.

Tested for my self (using debug build), didn't noticed any fps drops.

**Comment by sketchyfun** [comment]
Hmm, I've just loaded up Godot again after taking a short break and I don't seem to be able to replicate the problem any more.. the general FPS seems to be higher this time too (around 30+)

I guess it's either something to do with my project or something in the background was causing it to stutter every 60 seconds. I'll keep an eye out for it happening again and try and dig a bit deeper. I'll close this issue for now since it doesn't appear to be an issue within Godot after all.
