### ISSUE TITLE
Input missing mouse clicks (Godot 2 and 3)

### ISSUE THREAD

**Issue by jhonatanoliveira** [godotengine/godot#13131]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OS: MacOS 0.13.1 (17B48)
Godot version: 2.1.4 and 3.0 alpha2

**Issue description:**

When trying to detect mouse clicks in a `_process` function, Godot can randomly miss some clicks.

**Steps to reproduce:**
The bug can be easily reproduced in both versions of Godot 2 and 3.
First, set up a _mouse left button_ in  the _Input Map_ to, say _lmb_click_.
Next, create a node, say _Node2D_, and attach a script to it.
In the `_ready` function, `set_process(true)`.
In the `_process(delta)` function, check `if Input.is_action_pressed("lmb_click")` then `print(">>> Click")`.
I suggest creating an incremental `var counter` variable, in order to make it clear when a new click is issued. That is, `print(">>> Click: "+String(counter))`.
Now, run the project and click in the game window multiple times. The clicks seem to be detected almost always, but few of them are dropped. This is specially clear after clicking often and fast, with multiple double clicks.
**Note**: the bug takes some time to show up. Insit by clicking for a couple of seconds. Also, try removing the focus of the game window (by clicking somewhere else in the desktop) and coming back. This seems to make `Input` drop more clicks.

**Link to minimal example project:**

[godot_2.zip](https://github.com/godotengine/godot/files/1490333/godot_2.zip)
[godot_3.zip](https://github.com/godotengine/godot/files/1490335/godot_3.zip)

**Comment by Dillybob92** [comment]
better to detect mouse clicks in _input or _input_event or _gui_event (3.0)

**Comment by jhonatanoliveira** [comment]
Correct! Indeed, inside `_input` there is no click dropping. If this is the expected behaviour, then I am sorry for opening a bug. I will close this thread. Maybe should add a note in the documentation not recommending the use of `Input` for mouse clicks in `_process`? Thank you.
