### ISSUE TITLE
Documentation for building godot on all the platforms uses single threaded build

### ISSUE THREAD

**Issue by donkeybonks** [godotengine/godot#13137]
ie for OSX the documentation shows:
```
scons platform=osx
```
But this takes ~20 minutes to build.

The build goes an order of magnitude faster if you put scons -j 8 so the documentation should probably show that command by default for all the platforms.

**Comment by NullConstant** [comment]
[Tihs section](http://docs.godotengine.org/en/latest/development/compiling/introduction_to_the_buildsystem.html#platform-selection) section of the Introduction article talks about the usage of multiple cores for compilation, though.

**Comment by Zireael07** [comment]
Multiple cores ARE wonky on Windows.

**Comment by donkeybonks** [comment]
The README links right to this page ( http://docs.godotengine.org/en/latest/development/compiling/index.html ). I'm thinking people are probably just going to click their platform.

-j builds seem to work fine under OS X fwiw.

**Comment by bojidar-bg** [comment]
Well, it is wonky only on windows, so, I guess it might be extended with `-j $(sysctl -n hw.ncpu)` (untested).

**Comment by NullConstant** [comment]
I thought that it's usually `-j $(nproc)` (unless that's a Linux-specific command)?

**Comment by donkeybonks** [comment]
Yeah.
```
-bash: nproc: command not found
```
`$(sysctl -n hw.ncpu) ` works though.

**Comment by akien-mga** [comment]
People should read http://docs.godotengine.org/en/latest/development/compiling/introduction_to_the_buildsystem.html which describes it. We can add a `.. seealso::` link to the top of each platform-specific page if need be, but I prefer we don't make the instructions more complex for each platform by cluttering with machine and OS-specific instructions about `-j`. The point of those commands is to show the *important* options, not the more advanced ones that will indeed be used by people who compile daily, and who should read the docs fully :)

**Comment by akien-mga** [comment]
Closing as per the above :)
