### ISSUE TITLE
Gridmap : Mesh Size Changes

### ISSUE THREAD

**Issue by Supatier** [godotengine/godot#13138]
Godot 3, Manjaro Linux x64

I'm trying to make a gridmap using a bunch of not uniformed meshes : 

![screenshot from 2017-11-21 18-19-39](https://user-images.githubusercontent.com/19777767/33069913-abe795ea-cee8-11e7-9d7e-02ee488fabbc.png)

And size changes : 

![screenshot from 2017-11-21 18-23-45](https://user-images.githubusercontent.com/19777767/33070042-35a9898c-cee9-11e7-8e70-1a8ddaa2480d.png)

Here's the asset in question : 
[trunks.zip](https://github.com/godotengine/godot/files/1491110/trunks.zip)
Thanks

**Comment by sketchyfun** [comment]
Are you scaling the meshes when setting up the mesh library?

**Comment by Supatier** [comment]
@sketchyfun No, I didn't.

**Comment by sketchyfun** [comment]
hmm, okay. It's probably unrelated, but why do you have a rigidbody as the top node in the mesh library?

**Comment by bojidar-bg** [comment]
Have you scaled the meshes in the mesh creation software (e.g. blender), without applying the transformation? (e.g. by doing Ctrl-A -> Scale in blender)

**Comment by Supatier** [comment]
@sketchyfun So what should it be?

@bojidar-bg I didn't change anything. I just combine all meshes into one scene.

**Comment by sketchyfun** [comment]
It probably won't affect anything negatively, but I think a regular Spatial node is usually used as the base. @bojidar-bg 's idea or something similar is more likely to be the culprit.. I can't check your example at the moment as I'm at work, but I'll take a look later if it hasn't been solved before then.

**Comment by bojidar-bg** [comment]
You have some scale set on those trunks...
![image](https://user-images.githubusercontent.com/5276727/33078262-cdc9042c-ceda-11e7-887e-7914c85da0b8.png)

Use this menu to fix it:
![image](https://user-images.githubusercontent.com/5276727/33078351-14b279ae-cedb-11e7-82d3-a97e6bbf3f57.png)

**Comment by kubecz3k** [comment]
Not a single model from this asset file has the proper scale:
![peek 2017-11-21 21-10](https://user-images.githubusercontent.com/6129594/33094572-efbd8fa0-cf00-11e7-970a-69039eb11fd5.gif)

**Comment by kubecz3k** [comment]
also worth to mention, that @bojidar-bg tip should be enough, but you need to apply it for every single object. You should also be able to see exactly the same scales inside the blender.

**Comment by kubecz3k** [comment]
Uh damn, haven't seen that @bojidar-bg already took screens from blender and explained the issue... Sorry for repetition!

**Comment by Supatier** [comment]
I'll check when I get home. Thanks

**Comment by Supatier** [comment]
I have fixed the scale, but still no luck.
The fixed meshes : [trunksmesh.zip](https://github.com/godotengine/godot/files/1495579/trunksmesh.zip)

**Comment by kubecz3k** [comment]
Are you sure you generated new mesh library? I generated and it's ok. You should however set better pivot points for those meshes since some of the trees are having pivot in the middle of the mesh (you probably will want on the xz center and y bottom)

**Comment by Supatier** [comment]
After creating a new project, everything went well as expected : 
![screenshot from 2017-11-22 20-10-05](https://user-images.githubusercontent.com/19777767/33129058-4d1f3a3e-cfc1-11e7-88eb-a23a659cdac8.png) (except that one trunk) 

Thanks
