### ISSUE TITLE
Kinematic bodies should wakeup rigidbodies/characters on contact

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13148]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
c846e49a7d3439d9aef5d499ad403304d89a3b3c

**Issue description:**
Currently when 3D rigid body is sleeping, and kinematic body collide it, the body will not wake up. 
Not sure what was the behavior in 2.x. 

Opening this issue as a kindly reminder for @AndreaCatania  :) 
It was discussed very slightly in https://github.com/godotengine/godot/issues/13140

**Comment by AndreaCatania** [comment]
Fixed #16757
