### ISSUE TITLE
Absolute path in .res file

### ISSUE THREAD

**Issue by fredlim** [godotengine/godot#1314]
I would like to confirm is Godot store absolute path in .res file, I found that because my main PC's Document folder is store in drive E: (because OS is store in SSD C:, others like Documents, Pictures, Music, Videos are store in E:)

My Godot project folder is store in E:, after copy the project to another PC, which has only 1 hard drive C:, Godot cannot load the image because it cannot find image in E:\ drive.

When I open the .res file, although it is not a plain text file, I found the absolute path "E:/Users/flim/Documents/" inside.

**Comment by reduz** [comment]
Nope, it stores project relative paths

**Comment by fredlim** [comment]
I modified MrGeenTea TiledMap import plugin to import TexturePacker json.
The plugin use FileDialog control, argument pass to the connection function is absolute path, the file path will store in the scene and the converted tile set.

**Comment by fredlim** [comment]
I know this is not a bug, but is there a way to get relative path from the file dialog?

**Comment by akien-mga** [comment]
Closing as it's apparently not a Godot bug but an issue with a custom plugin. The following question is still interesting though, so if anyone knows the answer, I'm sure it could be useful to some :)

> I know this is not a bug, but is there a way to get relative path from the file dialog?
