### ISSUE TITLE
Regression: 3D RigidBody have no visible gravity after returning from kinematic physic mode

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13140]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
1c2782a7c7456b4a473e519ebb40968c521911e7

**Issue description:**
After putting a body in a kinematic mode, and returning to rigid mode, it seems like gravity force is not working anymore on that body. 
![return_kinematoc_grav](https://user-images.githubusercontent.com/6129594/33072686-ca2a3698-cec0-11e7-9eea-23f568251166.gif)

**Steps to reproduce:**
1. Check sample project 

or alternatively:

1. Put a body in kinematic mode
2. Wait 0.1s 
3. Change mode of body to back to rigid

**Link to minimal example project:**
[Kinematic2RigidModeGravityIssue.zip](https://github.com/godotengine/godot/files/1491310/Kinematic2RigidModeGravityIssue.zip)

**Comment by kubecz3k** [comment]
cc @AndreaCatania

**Comment by akien-mga** [comment]
Cutest bug demo ever :)

**Comment by AndreaCatania** [comment]
I fixed it. Anyway the kinematic body is like a static body and can't wakeup a rigidbody, the result is an overlapping between kinematic and sleeper rigid body.

I'll add a code to the function Move that add a force in case of kin touches the rigidbody so you will be able to push rigidbody even if they are sleeping.

If you create an issue with this feature request is better, I can't forgot it.

**Comment by kubecz3k** [comment]
@AndreaCatania I will, but you need to know it was putted inside reproduction project by total accident... Wanted to record nice gif with zerro-g floating bodies :)
