### ISSUE TITLE
[Solved] Export build for Windows 10, 64 bits crashes

### ISSUE THREAD

**Issue by radubolovan** [godotengine/godot#13156]
**This is no longer an issue**
After I downloaded again the export templates, everything is working fine.

**Windows 10, Godot 2.1.4 official stable release, official release export templates**

**Issue description:**
Build crashes when I export for Windows 10, 64 bits.

**Steps to reproduce:**
1) Take the sources of the project from Github (link below)
2) Load the project in 2.1.4 official stable release
3) Setup official 2.1.4 export templates within the editor
4) Export the project for 64 bits (with or without 'Debugging enabled')
5) Run ".exe" file
6) Project crashes

Expecting results: the program should not crash.

**OBS:**
The project does not crush if it runs within the editor. Only the export crashes.
Here's a screenshot with the Debug Log:
https://imgur.com/a/Dxq2a

**Link to minimal example project:**
https://github.com/radubolovan/Godot-HTTPClient-sample

**Comment by radubolovan** [comment]
**Further information:**
The export for 32 bits, Windows 10 crashes as well.

**Comment by volzhs** [comment]
can you attach reproducible project?

**Comment by akien-mga** [comment]
> can you attach reproducible project?

It's in https://github.com/radubolovan/Godot-HTTPClient-sample

**Comment by radubolovan** [comment]
Hello,
Can I have an ETA, please?
Don't understand me wrong. I'm not rushing you guys. I just need to know.
This project is open source with MIT license that I wanted to share, but it's part of one of my personal project that I need to show someone in mid December. I just need to know if I can do that or I need to delay the presentation.

Best regards,
Radu

**Comment by akien-mga** [comment]
I can't reproduce the issue with 2.1.4 when exporting for Windows 64 on Linux and running the binary in WINE. The Linux 64-bit export also works fine.

The error in your screenshot hints that the compiled script is broken, so either the compilation did something weird, or that export was done using an invalid script (namely one with `extends` and no qualifier afterwards).

Can you try again with the project in your GitHub repo, and detail the exact options you are using to export? If it still crashes, can you attach the exported project? (.exe and .pck).

**Comment by vnen** [comment]
Can't reproduce this on Windows 10. Tried both 32- and 64-bit export, with and without debugging enabled. Have you tried to re-download the editor and/or the templates?

Note: I edited the original post to fix the image link.

**Comment by eon-s** [comment]
I can't reproduce either, even tried without internet connection, I'm still missing some windows updates too but would be better if @radubolovan check templates first.

Since is a program that uses the network could be a firewall/AV software also.

**Comment by radubolovan** [comment]
Thanks a lot for your reply and sorry for delay.
I'll do what you guys said as soon as I can (I don't feel ell at the moment) and I'll be back to you with news.
Thanks again!

**Comment by radubolovan** [comment]
I confirm that I can't reproduce this after I follow the instructions.
Thanks again. This can be closed.
