### ISSUE TITLE
Allow arrays in shaders

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#1315]
Not sure if this even needs a justification, but here is why I just needed them.
There is a huge class of shaders that use lookup tables, in the form of arrays.

Ordered dithering, color quantization, noise, many others to count...
Seriously, no arrays? :D

And it shouldn't be difficult to implement, right? (other than the fact that godot seems to have a hand-written lexer) After all, you don't really need to implement any language feature, godot just transpiles it to GLSL.

**Comment by reduz** [comment]
Gles 2 does not support integers properly so for current renderer this is a
little pointless. You can always use textures as lookups though. For gles3
backend this will be addes.

**Comment by seadra** [comment]
Which, according to the roadmap, is going to happen around September (and OMG, I just realized post-process shaders won't be in 1.1!).

I was thinking of passing float arrays as uniforms.
Out of curiosity but, is there are way of creating a texture from GDScript programmatically BTW?

**Comment by reduz** [comment]
Sure, you can create anything from gdscript. Check ImageTexture

**Comment by seadra** [comment]
Cool! Thanks!

**Comment by akien-mga** [comment]
Closing as duplicate of #1191 (not exactly the same, but it's on a similar topic and both will likely be addressed at the same time when working on the new renderer).
