### ISSUE TITLE
Mesh animation distortion when importing Collada (from blender export) 

### ISSUE THREAD

**Issue by Razzlegames** [godotengine/godot#1316]
### Issue

After importing an animated mesh, and accessing the animation player, the mesh is fine for the first frame on any animation strip. When moving to another frame (or playing) then moving back to the first frame, the mesh is suddenly distorted and cannot be restored until the scene is reloaded.
### Steps to reproduce:
- In Blender, pose the armature in a transformed state (move it around etc).
- Export it using the "Better collada exporter"
- Import in Godot using Import->"3D Scene"
- Open the scene's Animation player in Godot.
- Push play or just move to another frame.
  - Notice the distortion
- Move back to frame 0 and it still remains etc.
- You can now repopen the scene and the distortion will be gone.

This is after first importing the mesh.

![showing_ok_mesh_first_frame](https://cloud.githubusercontent.com/assets/8754559/5971677/361dd2c0-a808-11e4-9e14-088b0e34d0a6.png)

After moving away from frame 0 in the animation player (by playing etc). Moving back to frame zero retains distortion, as seen here:

![messed_up_first_frame](https://cloud.githubusercontent.com/assets/8754559/5971661/d36dc874-a807-11e4-92c7-bebe08b2d4b3.png)

If you reopen the scene it will look normal again, until you animate.  The same behavior is seen if you animate in code, by referencing any animation name (even if they just contain the rest pose).
### Workaround

The issue appears to be when exporting if you leave the armature in a transformed state (not in the rest identity transform, pose).  As seen here:

![default_pose_blender](https://cloud.githubusercontent.com/assets/8754559/5971694/79758b44-a808-11e4-81cb-e1174d008b20.png)

The solution is to clear all rotations, scale and translations in pose mode before exporting.  Additionally I made a "default" animation strip as the first animation and have 1 frame with just the rest pose.

Shown here:

![rest_pose](https://cloud.githubusercontent.com/assets/8754559/5971714/ea9254b0-a808-11e4-84d5-d20c6ff899da.png)

The project is here: 
https://drive.google.com/file/d/0By6FH_3O43IRWnBtWWhUYXhuQVU/view?usp=sharing
- The blender file located under RawAssets->3d_santa.blend
- The Collada file is under RawAssets->3d_santa.dae

**Comment by reduz** [comment]
Thanks! I will give it a test asap,sorry I could check before as I was on vacation.

**Comment by Razzlegames** [comment]
No worries.  It's easy to work around.  Thanks!

**Comment by akien-mga** [comment]
I just checked and the above linked blend is still available, if someone could give it a try and see if it's reproducible in the current master branch.

**Comment by Razzlegames** [comment]
I was able to reproduce it just a few months ago.  I should be able to get
a test together and just upload the whole project.

**Comment by Razzlegames** [comment]
Here's a simple example project that shows the issue.  

https://github.com/Razzlegames/MeshTestGodot

You only need to export the model to Animated collada using the "Better collada" Godot exporter plugin.  The model needs to be not in a rest post when exporting and the issue will show itself.  If you reset back to rest post and export it will not happen.

BTW, after Godot notifies you that the model changes and you select to reimport the model, you will have to close the 3D scene and repopen it, to see the issue.  

Here's my exporter settings:

![collada_export_settings](https://cloud.githubusercontent.com/assets/8754559/12218223/b6ba2a40-b6d6-11e5-864d-abd1757e674c.png)

**Comment by Razzlegames** [comment]
This are the hilarious results LOL.  Santa is trying out for a spot in Resident Evil:
![santa_horror_bug](https://cloud.githubusercontent.com/assets/8754559/12218246/4ea60306-b6d7-11e5-99de-5b8ce6f594a3.png)

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.

**Comment by jitspoe** [comment]
This issue is actually an exporter issue with the better collada exporter.  It can be fixed by adding the following 2 lines:

```
                arm.update_tag()
                bpy.context.scene.frame_set(bpy.context.scene.frame_current)
```

after this:

```
        if(armature_modifier):
            #doing this per object is inefficient, should be improved, maybe?
            armature_poses = [arm.pose_position for arm in bpy.data.armatures]
            for arm in bpy.data.armatures:
                print(arm.pose_position)
                arm.pose_position = "REST"
```

in exporte_dae.py

Better collada issue here: https://github.com/godotengine/collada-exporter/issues/99
