### ISSUE TITLE
 handle_crash: Program crashed with signal 11

### ISSUE THREAD

**Issue by skarmiglione** [godotengine/godot#13163]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
optirun 520m
intelhd
Compiled yesterday

**Issue description:**

Opening a project with a bunch of assets. 

current material library  has 0
current material  has 0
Added surface :
ERROR: store_8: Condition ' fwrite(&p_dest, 1, 1, f) != 1 ' is true.
   At: drivers/unix/file_access_unix.cpp:235.
ERROR: store_8: Condition ' fwrite(&p_dest, 1, 1, f) != 1 ' is true.
   At: drivers/unix/file_access_unix.cpp:235.
ERROR: store_8: Condition ' fwrite(&p_dest, 1, 1, f) != 1 ' is true.
   At: drivers/unix/file_access_unix.cpp:235.
ERROR: store_8: Condition ' fwrite(&p_dest, 1, 1, f) != 1 ' is true.
   At: drivers/unix/file_access_unix.cpp:235.
ERROR: store_8: Condition ' fwrite(&p_dest, 1, 1, f) != 1 ' is true.
   At: drivers/unix/file_access_unix.cpp:235.
ERROR: store_8: Condition ' fwrite(&p_dest, 1, 1, f) != 1 ' is true.
   At: drivers/unix/file_access_unix.cpp:235.
ERROR: store_8: Condition ' fwrite(&p_dest, 1, 1, f) != 1 ' is true.
   At: drivers/unix/file_access_unix.cpp:235.
ERROR: store_8: Condition ' fwrite(&p_dest, 1, 1, f) != 1 ' is true.
   At: drivers/unix/file_access_unix.cpp:235.
ERROR: store_8: Condition ' fwrite(&p_dest, 1, 1, f) != 1 ' is true.
   At: drivers/unix/file_access_unix.cpp:235.
ERROR: store_8: Condition ' fwrite(&p_dest, 1, 1, f) != 1 ' is true.
   At: drivers/unix/file_access_unix.cpp:235.

handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6() [0x30004354b0] (??:0)
[2] godot/godot-v3.0-x11.64() [0xd746c6] (??:0)
[3] /godot/godot-v3.0-x11.64() [0xd755c5] (??:0)
[4] s/godot/godot-v3.0-x11.64() [0xc7a20b] (??:0)
[5] /godot/godot-v3.0-x11.64() [0xc7f842] (??:0)
[6] /s/godot/godot-v3.0-x11.64() [0xc80253] (??:0)
[7] /godot/godot-v3.0-x11.64() [0xc8155e] (??:0)
[8] /godot/godot-v3.0-x11.64() [0xc88b49] (??:0)
[9] /godot/godot-v3.0-x11.64() [0x1a12094] (??:0)
[10] /godot/godot-v3.0-x11.64() [0x10c0025] (??:0)
[11] /godot/godot-v3.0-x11.64() [0x10c1173] (??:0/godot/godot-v3.0-x11.64() [0x4348c7] (??:0)
[13] godot/godot-v3.0-x11.64() [0x42f541] (??:0)
[14] /hgodot-v3.0-x11.64() [0x423c5f] (??:0)
[15] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x3000420830] (??:0)
[16] /home/cmkat/cosmogatokat/Herramientas/creacion_de_juegos/godot/godot-v3.0-x11.64() [0x426f80] (??:0)
-- END OF BACKTRACE --

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
What distro are you compiling on?

Can you build a debug binary (default `target`) and keep it in place (in Godot's `bin/` directory) next to its debug symbols (the `.debug` file with the same name as the binary), so that the backtrace gives useful info?

**Comment by skarmiglione** [comment]
is from the http://godot3builds.digitecnology.com/ this happen when it is scaning the assets, there are a lot of plants from opengameart.org cc-0 just it, i download all with 3TD tag and yughues

**Comment by akien-mga** [comment]
Please provided a zipped project that reproduces the issue then, so that someone else can try to reproduce it and retrieve a debug backtrace.

**Comment by skarmiglione** [comment]
I am using linux mint, with optimus, i did not try it without optirun.

**Comment by skarmiglione** [comment]
It is almost a 400mb, but you can reproduce it with the files i say up, all the trees, grass and plants  from here https://opengameart.org/users/yughues and all this assets from this page https://opengameart.org/users/hreikin?page=2

**Comment by skarmiglione** [comment]
oh and i forget this, https://opengameart.org/content/forest-monster i was just trying to make a enviroment test, without any script yet.

**Comment by akien-mga** [comment]
Did your home folder run out of disk space?

**Comment by akien-mga** [comment]
You'd have to find a way to reproduce this issue without needing to download half of OGA though, I doubt any developer will want to do that to maybe reproduce a bug without clear steps to reproduce.

**Comment by skarmiglione** [comment]
but i really dont know how help with godot engine to no have this kind of bugs, is not half the oga, but i only  use those 3 links, and yes with only trees and vegetals... is big folder but no more than a gb thats why i cant upload a zip right now, anyway maybe can be only the las forest monster cause it have animations... but i really dont know... it just happen later of a big "reimport" session... maybe later will start to delete some of that files to see where is this happening, anyway for me is just testing natural enviroments ... with a character.

**Comment by akien-mga** [comment]
Can you still reproduce it in the current master branch? If yes, is it better after deleting the `.import/` folder to force reimporting everything?

**Comment by akien-mga** [comment]
Removing from 3.0 milestone for now as there is not enough details to reproduce the issue, and the errors listed above seem to hint at a user specific problem (lack of disk space, or corrupted partition table, or something similar).

**Comment by qarmin** [comment]
I still have similar issue, when I open with GLES 2 3D FPS project from docs, then open health_pickup.tscn and change with arrows in scene view nodes Godot crash itself with this backtrace:

rafal@rafalKomp:~/Pulpit/godot/bin$ ./godot.x11.tools.64
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
Editing project: /home/rafal/Pobrane/Godot_FPS_Finished (::home::rafal::Pobrane::Godot_FPS_Finished)
OpenGL ES 2.0 Renderer: GeForce GTX 970/PCIe/SSE2
rafal@rafalKomp:~/Pulpit/godot/bin$ handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fe37e873f20] (??:0)
[2] [0x40bd9c41] (??:0)
-- END OF BACKTRACE --

I using Ubuntu 18.04 with Nvidia 970 - 396.54

Here is video, crash is around 0:39
https://streamable.com/jzhkx

**Comment by Zireael07** [comment]
@qarmin: If it's only on GLES2 mode, then it's probably related to GLES 2 code and thus not related to this older issue?

**Comment by KoBeWi** [comment]
This issue is very vague and the OP haven't responded in 2 years, so it should be fine to close it.
(also qarmin's stack trace is different, so probably unrelated)
