### ISSUE TITLE
Tweens have stopped animating.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#13174]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.10 64-bit, Godot 3 beta build 7f022a3.

**Issue description:**
Until a few builds ago, these tweens would animate properly:
```
$"Tweens/Tween_Rings".set_tween_process_mode (Tween.TWEEN_PROCESS_IDLE)
$"Tweens/Tween_Lives".set_tween_process_mode (Tween.TWEEN_PROCESS_IDLE)
$"Tweens/Tween_Rings".interpolate_property ($"Ring_Count", "custom_colors/font_color", Color ("#ff0000"), Color ("#ffff00"), 1.75, Tween.TRANS_LINEAR, Tween.EASE_OUT_IN, 0.25)
$"Tweens/Tween_Lives".interpolate_property ($"Lives_Counter", "custom_colors/font_color", Color ("#ff0000"), Color ("#ffff00"), 1.75, Tween.TRANS_LINEAR, Tween.EASE_OUT_IN, 0.25)
$"Tweens/Tween_Rings".set_repeat (true)
$"Tweens/Tween_Lives".set_repeat (true)
```

Where Lives_Counter and Ring_Count are text labels. The following code snippet would stop/start the tweens as required:

```
func _process (delta):
	# Make sure that the ring counter is flashing if the player has no rings, otherwise have it normal.
	if ($"../Sonic".rings == 0):
		if (!rings_zero):
			$"Tweens/Tween_Rings".reset ($"Ring_Count", "custom_colors/font_color")
			$"Tweens/Tween_Rings".resume ($"Ring_Count", "custom_colors/font_color")
			rings_zero = true
	else:
		rings_zero = false
		$"Tweens/Tween_Rings".stop ($"Ring_Count")
		# If the animation is stopped, you need to reset the property to normal otherwise it'll stay wherever the tween had got to!
		$"Ring_Count".set ("custom_colors/font_color", Color ("#ffffff"))
	# Make the lives count flash if it is zero.
	if ($"../Sonic".lives < 1):
		if (!lives_zero):
			$"Tweens/Tween_Lives".reset ($"Lives_Counter", "custom_colors/font_color")
			$"Tweens/Tween_Lives".resume ($"Lives_Counter", "custom_colors/font_color")
			lives_zero = true
	else:
		lives_zero = false
		$"Tweens/Tween_Lives".stop ($"Lives_Counter")
		# If the animation is stopped, you need to reset the property to normal otherwise it'll stay wherever the tween had got to!
		$"Lives_Counter".set ("custom_colors/font_color", Color ("#ffffff"))
	return
```

Another tween, set up later, still works. `$Tween.interpolate_property (get_node ("."), "position", position, Vector2 (position.x, position.y+290), 1.50, Tween.TRANS_LINEAR, Tween.EASE_IN)`

I understand there've been recent commits to do with tweens and colours.

**Steps to reproduce:**
Try using a tween to animate certain properties of items.

**Link to minimal example project:**
https://www.dropbox.com/s/qs9cnytri6192v7/13174_demonstrator.7z?dl=0

**Comment by akien-mga** [comment]
Likely related to #12284, cc @bojidar-bg.

**Comment by bojidar-bg** [comment]
The issue is that `"custom_colors/font_color"` is now parsed as a NodePath, and then converted to a "property" NodePath... which fails because of the slash (it thinks you mean the font_color node in the custom_colors node). It should be written as `":custom_colors/font_color"` now, in order to refer to the property (or even better, `@":custom_colors/font_color"`).

I think I might work around this, but it might introduce some regressions, lemme test.
