### ISSUE TITLE
Replace shader language with GLSL

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#1317]
(split this off from #1315)

Since godot is using GLSL only for shaders, what is the point of having an in-house shader language? It's not that I mind learning a new language (like GDScript, for example), the problem is, it's a hugely crippled subset of GLSL that doesn't even have arrays or structs and simply put a HUGE pain to work with.

*It's nothing more than a toy language, lacking features preventing to write real-world programs that try go beyond simple shaders. Period.*

I wish you saved us trouble of this toy "shader language" and just let use write in GLSL --you know, like real programmers do. Just wishing :)

I mean, given that it compiles into and only into GLSL and "shader language" is just a hugely crippled subset of GLSL except for the mul -> * syntactic sugar, why not? Is it even necessary?

Pre-defined variables/structs like in Unity should work just fine to pass certain things between engine and shader. In fact, it's already what you're doing with things like "SRC_VERTEX" or "DIFFUSE", except that they're not in a struct.

Please consider this seriously.
Unless this is changed in the future, for anyone using shaders seriously (practically any non-indie game), I can't see much of a future in godot.

**Comment by reduz** [comment]
You certainly don't want to write GLSL directly as it is a lot of work and
it will not pay off.

The limitations of the current shader language are because it targets
GLES2. When GLES3 support is added, the missing language features will be
added too.

If instead you just want to program something more low level, then Godot is
not for you.

**Comment by adolson** [comment]
I don't want to write GLSL directly, but is there any reason it can't be an option somehow? Kinda like you can write all of your game code in GDScript or (if you're crazy) C++?

**Comment by reduz** [comment]
The problem is that godot does a lot of stuff in the shader, that you would
have to write yourself if you were writing glsl and expected everything to
keep working

**Comment by seadra** [comment]
I wasn't trying to say that "leave 100% shader code to us". Godot still can do stuff in underhood.
What I meant was, let us write essentially the same portion of the ultimate GLSL code, but let us write that portion in GLSL, as functions.

So yep, what I'm proposing is, let us provide 3 GLSL functions (vertex, fragment, lighting). Godot can call them from it's own GLSL code, code whatever necessary before & after the call.

I just want a proper C-like language GLSL is, it's not that I'm trying to go super low-level --how low level can you go with GLSL anyway.

(I'm sorry about my shader-related tantrums BTW :D We're using Unity at work, and the lack of proper shader support is why I failed a switch to godot this time. I'm hoping to succeed next time!)

**Comment by reduz** [comment]
What specifically would you like to see supported in godot shaders that is
not now, feature wise? GLSL for GLES2 does not really support much more..

**Comment by seadra** [comment]
As far as I noticed, the essential features we need on top my head are:
* FBO/g-buffers
* post-process
* array uniforms (can get around until arrays land)
* half and fixed data types (mainly for android)
* now I'm stretching it, but something along [Unity's surface shaders maybe](http://docs.unity3d.com/Manual/SL-SurfaceShaders.html)? they're time savers by allowing us to modify the standard pipeline a bit
I'll expand this list when I remember other stuff.

Other than post-process shaders, I understand that I'll have to wait for GLES3 migration, so fingers crossed for 2016 :)

**Comment by reduz** [comment]
Everything you mention is unrelated to the shader language.. Save for
uniform arrays, which is generally a bad idea anyway on mobile (passimg
textures makes more sense)

On mobile, floating point datatypes are half by default since most hardware
does not support actual floats in fp, on PC half is not faster than float
nowadays so full float is used.

Shaders currently work in a similar way to surface shaders.

So this leaves us at the point where, as I understand the only features you
lack are post process and custom buffer writes, both of which are
impossible to get to work on mobile hardware that supports gles2 anyway..

You will have to wait towards the end of the year for this...

**Comment by reduz** [comment]
In other words, even if full GLSL was supported, you would not be able to
do what you want due to GLES2 restrictions.

**Comment by seadra** [comment]
Something like surface shaders can be done GLES2 I guess, but overall, yeah, you're right :)
Good news is, according to the roadmap, GLES3 isn't so far ahead (Sep 2015).

**Comment by reduz** [comment]
As I said before, I can't wait to implement a gles3 backend :( but
usability is still the main concern of most users, so nees to work on that
first

**Comment by seadra** [comment]
Sure, and I know you've got many other items in your roadmap. I'm grateful you're going to be working on it all all :)

**Comment by kubecz3k** [comment]
Godot Shader language capability will be improved in Godot 3.0 release. It will focus on implementing Vulcan or OpenglEs 3.x... Archiving this thread.
