### ISSUE TITLE
Use system save/load dialog on OS X and Windows

### ISSUE THREAD

**Issue by donkeybonks** [godotengine/godot#13177]
I dislike the godot save/load window. It feels inconsistent with all the other apps running. You lose all your keyboard shortcuts and not all your OS-specific favorite locations are mirrored across.

It would be nice if the save and open dialogs could use the OS X and Windows default save/open dialogs on those systems so that they benefit from the familiar feel of the system specific UX and help users to find their files quicker.

**Comment by donkeybonks** [comment]
Here is a comparison of how they appear on my machine.

<img width="512" alt="screen shot 2017-11-22 at 11 00 25 pm" src="https://user-images.githubusercontent.com/1356959/33126567-1239c44e-cfd9-11e7-804e-e391c54e1a90.png">
![Uploading Screen Shot 2017-11-22 at 11.00.56 pm.png…]()

**Comment by donkeybonks** [comment]
<img width="512" alt="screen shot 2017-11-22 at 11 00 56 pm" src="https://user-images.githubusercontent.com/1356959/33126602-2e24da72-cfd9-11e7-9cf8-d76bb0525609.png">

**Comment by donkeybonks** [comment]
<img width="512" alt="screen shot 2017-11-22 at 11 03 03 pm" src="https://user-images.githubusercontent.com/1356959/33126641-51405748-cfd9-11e7-84e8-2ef6fc0482d0.png">

**Comment by Calinou** [comment]
Godot does not rely on any system dialogs, and I think it should stay this way by default. Consistency across the application can also be a virtue.

I would welcome this as an option, though. But Linux support does matter as well 😄

**Comment by reduz** [comment]
Sorry, this is not going to happen. The UI may look nicer, but this road was not taken because users preferred to have better previews for resources instead of consistency with the OS. Closing.

**Comment by reduz** [comment]
in any case, if you would like the built-in filedialog to support something to make your life easier, feel free to request it

**Comment by donkeybonks** [comment]
Thank you for addressing this @reduz.

Whilst I respect the reasons that this was done, it's probably not practical for me to flood the issue tracker with feature requests. People obviously value things differently, so what one person values (as a power user) in a Linux environment is probably very different to what another person values in an OS X or Windows environment.

Things that you might take for granted, for example navigating from the root of your file system to your home directory or from the file system root into a removable storage device, are not very straightforward for your average artist or high school student. It is more likely that they will become frustrated and blame it on godot. Familiarity is the strongest UX you can provide here and I urge you to reconsider whether it could be possible to mux the current implementation for Linux and offer a more uniform solution for OS X and Windows.

**Comment by gingerbeardman** [comment]
Here we are a few years alter, and I wondered about the current opinion on this? Has anything changed?

Personally I find the Godot file picker to be a barrier and hurdle to the Pixelorama app that I am using. 

The "better previews for resources" as mentioned above is not something I am familiar with, can somebody please clarify? 

This is what I see when I choose File/Open:

![Screen shot 2020-06-26 at 13 32 57](https://user-images.githubusercontent.com/49612/85857339-9085be80-b7b1-11ea-88a1-898644744ced.png)

**Comment by bruvzg** [comment]
Also, if you export for macOS with the sandbox entitlement enabled (AFAIK, currently it's not hard requirement for the App Store distribution, but eventually it will be), native dialog is the only option to select files outside the app container. For the sandboxed app, Godot file dialog is completely broken and useless (and probably there's no fix for this, it's done deliberately for security reasons).

**Comment by gingerbeardman** [comment]
@bruvzg this is by far the most important point for allowing use of the native system file picker, thank you

**Comment by bruvzg** [comment]
There's native dialog module for Godot https://github.com/GodotExplorer/NativeDialogs for macOS, Windows, and Linux, but it's not updated for the long time (probably incompatible with the Godot 4.x), and I have uploaded my own module implementation (macOS File and Alert panels only, works with both 4.x and 3.x) - https://github.com/bruvzg/mac_file_panels

**Comment by Calinou** [comment]
> The "better previews for resources" as mentioned above is not something I am familiar with, can somebody please clarify?

Resource previews are only available in the editor-only EditorFileDialog, not in the FileDialog which is used in Godot projects.

See also https://github.com/godotengine/godot/pull/36053.

**Comment by gingerbeardman** [comment]
#36053 seems to be reinventing the wheel, and desire its good intentions will never able to please some Linux/Mac/Windows users who expect their system file picker.

So, I'll open a proposal. Thanks

**Comment by gingerbeardman** [comment]
Proposal filed! https://github.com/godotengine/godot-proposals/issues/1123
