### ISSUE TITLE
Unused volume_db property in AudioStreamPlayer

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#13185]
**Issue description:**
The volume_db in AudioStreamPlayer is visible in editor, but does not have any visible effects after change
I think the volume is controlled by bus, and this property has no meaning now...

**Comment by kubecz3k** [comment]
Probably it was orphaned after audio engine rewriting...

**Comment by vnen** [comment]
I think it's still good to have it, since many stream players can use the same audio bus.

**Comment by Sslaxx** [comment]
In that case @vnen it should have the value of the bus's volume, and not be directly settable (or change the volume level of the bus in question).

**Comment by Chaosus** [comment]
I just dont understand how to use it ?

**Comment by vnen** [comment]
@Sslaxx I think you misunderstood me, my point is that it's useful to set the player volume independently of the bus volume, since multiple players may use the same bus. Although it's possible to have many buses and set each player to a bus, that might become difficult to manage.

**Comment by Chaosus** [comment]
I set it before play to 0.0 but sound play normally, is it expected ?

**Comment by vnen** [comment]
@Chaosus I'm pretty sure 0.0 means "no change to the volume", positive values will make it louder and negative values will make it quieter.

**Comment by CowThing** [comment]
volume_db on AudioStreamPlayer nodes is working correctly for me. 0 = no change, -6 = half volume, 6 = twice as loud. Just as it should be.

**Comment by Chaosus** [comment]
Ah, I just misunderstood how it works
