### ISSUE TITLE
Shadow quality is dependent on the maximal distance beetween models on the scene

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13183]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
9ebc6ab45a375310f650bf3afd31f076215ac52c Ubuntu 17.04, Gtx 1060

**Issue description:**
It seems that shadow quality is dependent on the distance between the objects (or maybe light) on the scene.
I haven't investigated this issue a lot since I'm not sure if this is expected or not.
 @reduz could you elaborate? (take  a look at gif please)
![shadow_quality](https://user-images.githubusercontent.com/6129594/33136634-ff86850e-cfa5-11e7-8aac-4e63af7f3894.gif)

**Comment by reduz** [comment]
you probably changed shadows from stable to optimized in DirectionalLight?

**Comment by kubecz3k** [comment]
@reduz `Deph range` of my directional light is `optimized`. Guess should set as stable and also set proper `Max distance`?

**Comment by reduz** [comment]
yeah

**Comment by kubecz3k** [comment]
Ok I will, I probably changed to optimized at some point since I noticed the quality is a lot better usually. Will be happy to learn more about this when we will have docs. Thanks!

**Comment by reduz** [comment]
I already documented it :D

**Comment by kubecz3k** [comment]
wow, if so then I will do instant read! :D
