### ISSUE TITLE
Automatically install plugin dependencies

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#13187]
If you create a plugin that has dependencies on other plugins, it would be nice to be able to just put

    [deps]
    
    username/repo-name=version

Or some functionally equivalent syntax to automatically have those Asset Library assets installed as well.

**Comment by MrJustreborn** [comment]
I woild suggest the npm style for defining a version 
https://docs.npmjs.com/misc/semver#versions
It's possible to set a minimum version, range, just major version etc

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/142 and https://github.com/godotengine/godot-proposals/issues/607, as feature proposals are now tracked on the Godot proposals repository.
