### ISSUE TITLE
Touching collision shape disables gravity for related 3D bodies

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13182]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
08e6590fd625bc3b592b7398ec2825f3758ab6e8, Ubuntu 17.04

**Issue description:**
When modifying in runtime a collision shape of a body, it seems like the gravity force is not applied anymore to a bodies which are using this  shape resource. 

**Steps to reproduce:**
Demo:
1. Download demo and run `ShapeGravityProblem.tscn`

Manual:
1. Create a body with Sphere collision shape
2. Perform in runtime `collisionShapeNode.get_shape().set_radius(radius + 0.2);`

**Link to minimal example project:**
[ShapeGravityProblem.zip](https://github.com/godotengine/godot/files/1496362/ShapeGravityProblem.zip)

**Comment by kubecz3k** [comment]
Good afternoon @AndreaCatania :hand:

**Comment by gad-o** [comment]
I think its because in example project you've ticked custom integrator and disable internal forces. And then :
```
func _integrate_forces(state):
	return;

```

**Comment by kubecz3k** [comment]
@gad-o just for information: in Godot 3 some forces like gravity are integrated automatically before `_integrate_force` function call.
