### ISSUE TITLE
code folding default shortcuts are same with history prev/next

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#13180]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master 0300522

**Issue description:**

History Next : <kbd>Alt</kbd> + <kbd>Right</kbd>
History Prev : <kbd>Alt</kbd> + <kbd>Left</kbd>
Fold Line : <kbd>Alt</kbd> + <kbd>Left</kbd>
Unfold Line : <kbd>Alt</kbd> + <kbd>Right</kbd>

history next/prev does not work now.
default shortcut should be different from history next/prev.

**Comment by volzhs** [comment]
what about <kbd>Alt</kbd> + <kbd>[</kbd> and <kbd>Alt</kbd> + <kbd>]</kbd>?

**Comment by akien-mga** [comment]
> what about <kbd>Alt</kbd> + <kbd>[</kbd> and <kbd>Alt</kbd> + <kbd>]</kbd>?

Those can be pretty inconvenient depending on the keyboard layout. For example on an AZERTY keyboard that would mean <kbd>Alt</kbd> + <kbd>Alt Gr</kbd> + <kbd>5</kbd> and <kbd>Alt</kbd> + <kbd>Alt Gr</kbd> + <kbd>°</kbd> (first key right of <kbd>0</kbd>).

**Comment by volzhs** [comment]
what about making it as toggle key? A line should be one state of fold or unfold.

**Comment by akien-mga** [comment]
Yeah, maybe <kbd>Alt</kbd> + <kbd>F</kbd> (fold) if it's not used already.

**Comment by Stajin** [comment]
Is there an overview of where default values are referenced in the source?
I see lots of binding but not where it's getting the initial values from (Disclaimer: Am noob at opensource).

**Comment by volzhs** [comment]
I see alt+f is fine.
![image](https://user-images.githubusercontent.com/8281454/33268109-4a3b790c-d3bf-11e7-833a-ef934bd4c401.png)

**Comment by MattUV** [comment]
Here is a possible fix, it is open to discussion if you don't like the way I did.
