### ISSUE TITLE
script editor- fold doesnt fold the whole code- commented code interrupts folding

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#13191]
See bellow
![bugfolding](https://user-images.githubusercontent.com/6495061/33149984-99584ce4-cfc9-11e7-97ee-ab59e5f95582.gif)

found 2 bugs actually- probably related to one another
1. commented code should not be treated as something to be folded/unfolded
2. commented code should not interrupt  folding of parent function

**Comment by kubecz3k** [comment]
sorry it's a duplicate of https://github.com/godotengine/godot/issues/13107

**Comment by blurymind** [comment]
ah sorry, I didnt see the other one
