### ISSUE TITLE
Context menu doesn't open on the first node you add to a scene

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#13198]
Godot 3.0 master
Windows 10 64 bits

Repro:
1) Create a project / create a new scene
2) Add a Node: notice right-click on it doesn't open the contextual menu
3) Add a child: notice now you can, on both nodes
4) Remove the child: you still can
5) Remove all nodes, then add one: you can't open the contextual menu again

**Comment by djrm** [comment]
i have experienced this, it's really annoying.
