### ISSUE TITLE
Add generic swipes/gestures as InputEvents (InputEventGesture)

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#1319]
add generic swipes as actions in the action editor 

https://www.facebook.com/groups/godotengine/permalink/563740600429205/

**Comment by reduz** [comment]
Thanks!

**Comment by florix91** [comment]
Would this be made for 2.1? Strange that has not been made till now. I would like to help but don't really have the ability at the moment...

**Comment by reduz** [comment]
we could add this as an add-on now that we have the asset library

**Comment by akien-mga** [comment]
There's a plugin for this on the Asset Library, though I haven't tested it: https://godotengine.org/asset-library/asset/23

Do we want to keep this issue open for the possibility to add something to the InputEvent API directly, or should we close it and let community plugins handle those use cases?

**Comment by vnen** [comment]
I still want `InputEventGesture` as commented in https://github.com/godotengine/godot/pull/9115#issuecomment-307660443

**Comment by akien-mga** [comment]
See #9115 for an example implementation (rejected, as not cross-platform) of touchpad pinch zooming for OSX.

To have a mergeable implementation, we'd need it to fulfill those requirements:
- It should be based on a new `InputEventGesture` class
- It should be supported on all platforms where it's relevant (at least all desktop platforms, then eventually also mobile ones)

Feel free to split the work in several PRs (a first one could add the `InputEventGesture` class and support for e.g. pinch gestures, follow-ups could add support for swipe, tap, etc.).

**Comment by toger5** [comment]
I posted a proposal about the implementation of Gestures + mouse events in general.

## #9136

Although this one is more about MouseGestures. Not touch screen.

**Comment by raymoo** [comment]
@akien-mga Multitouch isn't even supported on desktop platforms, wouldn't that be a prerequisite of some gestures, like zoom or rotate?

**Comment by akien-mga** [comment]
Well it definitely is at least for laptops with a decent touchpad with decent drivers, and for touch screens.

**Comment by reduz** [comment]
As far as I know, they touch is supported on Windows

**Comment by raymoo** [comment]
@akien-mga @reduz does that mean #7612 and #8028 can be closed?

**Comment by akien-mga** [comment]
Well they're both prerequisites of this issue. I guess it makes sense to ensure first that desktop platforms support multitouch (#8028), and then implement a common gesture interface in core for all platforms (this issue).

**Comment by raymoo** [comment]
If I was unclear earlier I meant that Godot doesn't support multitouch on those platforms.

**Comment by samvila** [comment]
@reduz Please bring multi-touch to Windows and Linux, I'm trying to convince my boss to move from Unreal to Godot at work but not having multi-touch is blocking the move. If Someone is interested I could provide a testing platform and work with him/her to make sure the integration is good.

**Comment by akien-mga** [comment]
Base API is implemented in #12573, it still needs to be implemented on non-macOS (see #13139), and maybe more types of gestures could be added if relevant.
