### ISSUE TITLE
Godot 3.0 Linux compiling error

### ISSUE THREAD

**Issue by leiget** [godotengine/godot#13193]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Xubuntu 16.04

**Issue description:**
When compiling "os_unix_global_settings_path.gen.cpp" it says it can't find "OS_Unix::String get_global_settings_path() const".

**Steps to reproduce:**
I guess compile on any Linux OS.

All that I needed to do to fix this was add "virtual String get_global_settings_path() const;" as the last public method in "os_unix.h" I guess someone just forgot to add it.

**Comment by eon-s** [comment]
You need to remove the (autogenerated) .gen files when give problems, are remnant of removed files on old compilations

**Comment by akien-mga** [comment]
Duplicate of #13076.
