### ISSUE TITLE
The 3D editor opens with an empty additional left-panel

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#13197]
Godot 3.0 master
Windows 10 64 bits

When opening the editor on an empty scene, the 3D viewport has a strange margin on the left, which turns out to be an empty panel:

![image](https://user-images.githubusercontent.com/1311555/33153973-713f379c-cfe5-11e7-9767-23683a97e3ba.png)

One error in the console:
```
ERROR: EditorData::get_edited_scene_root: Indexcurrent_edited_scene=-1 out of size (edited_scene.size()=0)
   At: editor\editor_data.cpp:607
```

**Comment by djrm** [comment]
hehe, i was about to report this.

also this happens

![peek 2017-11-22 17-31](https://user-images.githubusercontent.com/1103897/33154037-2b1d1db8-cfab-11e7-81bd-53cf48eaadfb.gif)

**Comment by djrm** [comment]
i think it was caused by this

https://github.com/godotengine/godot/pull/12301/files#diff-13d4b14c5567b0648154fa7aa9018f3cL4575

but not 100% sure.

**Comment by reduz** [comment]
@MarianoGnu  ?

**Comment by icnikerazah** [comment]
i build today from source. i have same error
<img width="801" alt="ekran resmi 2017-11-27 18 19 20" src="https://user-images.githubusercontent.com/33985414/33273979-ea8c9b7c-d39f-11e7-8f41-441a7a9f426f.png">

**Comment by MarianoGnu** [comment]
will check asap, probably my bad

**Comment by MarianoGnu** [comment]
I've completely mistaken Spatial editor with Canvas Item editor :( worst thing is that this change wasn't even needed.
