### ISSUE TITLE
The editor constantly freezes maxing CPU (doing GDNative stuff?)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#13199]
Godot 3.0 64 bits
Windows 10

I am writing a "plugin" that contains a GDNative library (no tool scripts at all, the plugin isn't even enabled (and doesn't need to)). At the same time, I noticed that the editor started to freeze a lot, like 10 seconds every 10 seconds. I have no error in the console, except a new occurence of the following warning after every freeze:
```
WARNING: not found: editor_plugins/enabled
```
I'm not sure if that's the cause of it though.

Edit: I had a .gdns file open in the script editor (https://github.com/godotengine/godot/issues/13196), I was unable to get rid of it (https://github.com/godotengine/godot/issues/10359) so I deleted my project settings. Now it seems I get no freezes, though the warning is still there.

Edit 2: I got freezes again without .gdns files open... no idea what this is, but it's pretty random.  I often get them when the editor gains or loose focus.

Edit 3: I suspended the debugging session in the middle of a freeze, it seems GDNative is trying to reload libraries:

![image](https://user-images.githubusercontent.com/1311555/33154684-6f05223e-cfea-11e7-9b29-ff5e3d08815f.png)

Note, my library is only 93ko, and I have no tool script at all. I am running with debugger attached though.
I got another freeze with a different call stack, as I was trying to reach the Scene menu:

![image](https://user-images.githubusercontent.com/1311555/33154745-e6bb6eb4-cfea-11e7-8c53-4b2fe79fc44a.png)

**Comment by karroffel** [comment]
Is it a singleton library? (so the singleton flag in the GDNativeLibrary is set)

**Comment by Zylann** [comment]
No, it's a bare hello world in C with no singletons

**Comment by karroffel** [comment]
The interesting thing is that it seems to be freezing in `ClassDB::get_api_hash` and not even the GDNative stuff itself. Weird.

**Comment by bojidar-bg** [comment]
Maybe we should cache the hash?

**Comment by AlexHolly** [comment]
I have a similar issue, it happens randomly. I just removed a *.gd file that had static functions so far no freeze.

**Comment by reduz** [comment]
@karroffel any idea what this might be? I remember you guys wanted to cache the api hash

**Comment by karroffel** [comment]
I have no idea what causes `ClassDB::get_api_hash` to be so slow. But we could try to cache it inside the method itself.

**Comment by akien-mga** [comment]
There were performance improvements done to `ClassDB::get_api_hash`, but did it fix this issue or just mitigated it?

**Comment by karroffel** [comment]
@Zylann did the recent changes fix this?
