### ISSUE TITLE
Interpolated camera causes the editor to always refresh

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#13204]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
fedora 26 64-bit, 62d86b15887371c59f99bfa37dbe2fcaf80478f7, nvidia proprietary drivers v. 387.22

**Issue description:**

having an interpolated camera as a node of an independently saved scene that is referenced by another scene causes the editor to always update

**Steps to reproduce:**
when you open the attached project you will (most likely) notice that the update spinner is always spinning,
if you open the referenced scene you will find an interpolated camera, toggle its enabled property twice (so it gets enabled again) and you will see that the spinner goes back to normal, save it and go back to main scene, you will see the spinner spinning again.

**Link to minimal example project:**

[cam_test.zip](https://github.com/godotengine/godot/files/1497799/cam_test.zip)

**Comment by kubecz3k** [comment]
I noticed that editor will go into 'always updating' loop, when I'm selecting any node that is possessing InterolatedCamera.

**Comment by Calinou** [comment]
I can't reproduce this in Godot 3.2.1, assuming it has been fixed since. Please comment if you can still reproduce this.
