### ISSUE TITLE
Selection of instanced scenes still broken in 3D view

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#13200]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7
Godot built from recent pull of master
Geforce GTX 760

**Issue description:**
This was kind of fixed a while ago by @kubecz3k (https://github.com/godotengine/godot/commit/d2d62122e26afa66ff69d17a2c3b87ec6ed7e885#diff-13d4b14c5567b0648154fa7aa9018f3c) but it looks like @reduz (https://github.com/godotengine/godot/commit/1894157c9fab05984428d83a743b0fe1d720c80c#diff-13d4b14c5567b0648154fa7aa9018f3c) has since changed the way it's handled. Now it becomes more difficult to click on an instanced 3D scene the further away the camera is or the further its zoomed out e.g:

![bug](https://user-images.githubusercontent.com/10464013/33154259-1c91145a-cfdf-11e7-8ae1-91e678559055.gif)
(I'm trying to click the object as the cursor is moving around)

Not sure if it helps, but here's what my scene looks like. I'm not sure what part of the instanced scene actually contributes to the clickable area of instanced scenes, but I figured it can't hurt to show how that particular scene is set up.

![image](https://user-images.githubusercontent.com/10464013/33154300-53ff4c9a-cfdf-11e7-8043-e6835eaeb37d.png)

**Comment by kubecz3k** [comment]
@sketchyfun I think it might be helpful if you could upload reproduction project, with editor camera setting that allows to reproduce it the way how you have done it on the gif.

**Comment by sketchyfun** [comment]
I was about to upload an example project, but as I was putting one together I decided to try the original scenario (the one above) again but on my linux machine at work. The result is it seems a lot more reliable than what was happening on my windows machine at home last night.. I'll have another go tonight and if it still does it I'll upload an example.

**Comment by sketchyfun** [comment]
Okay, so for some strange reason selection of the instanced scenes is pretty easy and relatively accurate when I test it on my Ubuntu machine at work, but I've just tried it again on my Windows 7 machine at home and its still almost impossible to click them if unless the camera is zoomed in on the object. I can't think why this would be different.. I guess I'm gonna have to investigate a bit more :(

**Comment by sketchyfun** [comment]
On further inspection, the instanced scenes become harder to click the further away they are from (0,0,0)

If they're at (0,0,0) then they're easily selectable at any camera zoom level, but as I start to move it away from (0, 0, 0) towards say (100, 0, 0) the instanced scene becomes harder and harder to click, unless the camera zooms in closer, but much closer than it needs to be at (0, 0, 0)

**Comment by sketchyfun** [comment]
![easy](https://user-images.githubusercontent.com/10464013/33230527-22451f18-d1dd-11e7-8bb3-e716a54a52a5.gif)
Easy to click at (0, 0, 0)

![hard](https://user-images.githubusercontent.com/10464013/33230550-6bc5f716-d1dd-11e7-9de9-014beb16f3f3.gif)
Harder to click as it's moved away from the center of the scene

**Comment by sketchyfun** [comment]
Here's the scene I used above. Leave the turret in the center and try selecting it as you zoom out, it should be easily selectable. Now try moving the turret to (0, 0, 800), focus on it with F, and then try and click on it as you zoom out. It should become a lot harder to click on it than if it was in the center of the scene. It would be good if someone could test this on linux and windows, as I seem to be getting two different results on those. Thanks guys!

[Uploading 3d_selection_bug.zip…]()

**Comment by sketchyfun** [comment]
Okay, so we can ignore the OS discrepancies, the version I was using on Linux at work was having less problem selecting things because I'd modified the following line in instances_cull_ray() in visual_server_scene.cpp:

	culled = scenario->octree.cull_segment(p_from, p_to * 10000, cull, 1024);
to
	culled = scenario->octree.cull_segment(p_from, p_to * 100000, cull, 1024);

At a default of 10,000 it's difficult to select the instanced scenes on both my windows and linux systems. 
I'd been playing around trying to fix this issue previously and forgotten that I'd changed it.

It's interesting that increasing this value helps, although it definitely doesn't solve the issue, it just allows the objects to be further away from 0,0,0 before it becomes impossible to click them. I'll continue to investigate..

**Comment by sketchyfun** [comment]
aaaand I've found the problem, changed:
`culled = scenario->octree.cull_segment(p_from, p_to * 10000, cull, 1024);`
to
`culled = scenario->octree.cull_segment(p_from, p_from + p_to * 10000, cull, 1024);`

Now the instanced scenes are selectable no matter how far away from the center they are, or how zoomed out the camera is! I'm happy because now I can actually work on the levels for my game properly without throwing my PC out of the window in frustration ;)

I'll sort out a pull request for the fix soon!
