### ISSUE TITLE
Multiline comments support is broken in GDScript

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#1320]
When I put multiline comments like this:

```
'''
 Multiline comment
 Multiline comment
 Multiline comment
'''
```

...or this:

```
"""
 Multiline comment
 Multiline comment
 Multiline comment
"""
```

Godot complains saying:

```
error(line, column): Unexpected token: Constant:
Parser error: Unexpected token: Constant:
```

where `line,column` is the first line and first character where the  triple-quoted string starts

**_Update**_

It seems to work when the triple-quote is preceded by a space or a tab character

```
 """<--preceded by a space
this works ok
"""
    """<--preceded by a tab character
this works too
"""
```

**Comment by vnen** [comment]
I'm closing this, because GDScript does not have multiline comments. The triple-quote token (""") is used for multiline strings. You can make a feature request if you wish multiline comments.

**Comment by akien-mga** [comment]
Reopening as it seems from the discussion on #2397 that GDScript aims at support multiline strings/comments in the same way that Python does.

**Comment by akien-mga** [comment]
@est31 Want to have a look at this one? :)

I checked gd_tokenizer.cpp and gd_parser.cpp myself but it's a bit over my level, and I couldn't find what exactly determines what is a comment at the class definition scope.

If you manage to get it working at the global scope, a further difficulty would probably be to make it work for inner classes too, as the "add a space before the first ``"""`` trick does not seem to work there. It's also a good question why it works at all in the global scope as I don't see any sign of willingly supporting multiline comments so far (multiline strings yes, but for comments I haven't seen the relevant parser code).

**Comment by bojidar-bg** [comment]
Well, probably we should just ignore all string constants at any level, that are not part of an assignment or similar.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by est31** [comment]
@akien-mga as @bojidar-bg has become a gdscript pro now, I think he can do it better than me :)

**Comment by akien-mga** [comment]
Yep, assigned :p
