### ISSUE TITLE
solicitation - multiplayer class thinking about communicating with external servers

### ISSUE THREAD

**Issue by PerduGames** [godotengine/godot#13206]
**Void Linux - Godot 3**

**Issue description:**

Godot already uses Enet, and already has a high level API for multiplayer, however I always need to communicate with external servers and I believe that most game developers tend to create multiplayer with external and non-local servers, at least for Android this can be said, and I miss a simple client in godot.

Taking the example of the class "**NetworkedMultiplayerEnet**", it uses Enet, however it includes in the packages sent 12bytes non-native Enet, which complicates when you have an external Enet server to communicate.

I request a pure Enet class, which only sends reliable and untrusted messages in a simple way, just by calling a function, and to listen in a simple way so that it can easily communicate with an Enet module on the external server. Of course you can use multiple channels as Enet allows. It could even be part of the Enet module and be another class, I think it would be very useful for many developers. I could write it, I'm not the best programmer in the world, but I have time, and I can write it.

**Comment by Calinou** [comment]
Have you looked at the intermediate-level **[NetworkedMultiplayerPeer](http://docs.godotengine.org/en/latest/classes/class_networkedmultiplayerpeer.html)** class? More information can be found in the [high-level multiplayer tutorial](http://docs.godotengine.org/en/latest/learning/features/networking/high_level_multiplayer.html#mid-level-abstraction).

**Comment by PerduGames** [comment]
@Calinou Yes, the "NetworkedMultiplayerPeer" inherits it, it is not an intermediary class only, and with pure virtual methods, I can not use it, the one I use is the "NetworkedMultiplayerENet" that actually implements the methods, but here comes the question that I raised above, the class ends up limiting just the communication between client and godot servers. I think it would be nice to have a pure base class Enet, to send and receive messages with the possibility of communication with Enet modules on external servers, and then a class that inherits it to implement the high level API, but it has already been implemented, so the best would create another separate class.

**Comment by reduz** [comment]
Will be easier to eventually provide this stuff via gdnative

**Comment by PerduGames** [comment]
I ended up finding an Enet module for Godot 2.1+ and translated it to Godot 3.0, here it is. It tested and works normally with external servers. https://github.com/PerduGames/gdnet3

I think you can close it here. But I still think this could be implemented in godot. Something like a base class Enet, and the high level API would use this base class, so anyone who wanted to use pure Enet would use it, anyone who preferred to use something of the highest level would use it.

**Comment by mhilbrunner** [comment]
Closing this now, as these are available in third-party modules (https://github.com/PerduGames/gdnet3) and also there were recent PRs improving/exposing more of this (https://github.com/godotengine/godot/pull/18827, https://github.com/godotengine/godot/pull/18823)
