### ISSUE TITLE
Increase in memory usage after alpha 2

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#13217]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3a33725014169ce51d6ac581a4dce3b97a60da00

**Issue description:**

The memory consumption of certain projects (for example 2D platformer) exhibit a drastic increase in the amount of static memory usage.

alpha 2
![screenshot from 2017-11-23 12-09-22](https://user-images.githubusercontent.com/1103897/33185367-b18fde66-d047-11e7-9648-b902dafef59c.png)

current
![screenshot from 2017-11-23 12-09-53](https://user-images.githubusercontent.com/1103897/33185368-b5ff7204-d047-11e7-8e56-e57613692011.png)

**Steps to reproduce:**
just play some demos (i tried with the platformer 2D)

**Link to minimal example project:**

**Comment by mrcdk** [comment]
An empty project with only a scene with a node also shows similar results

![https://i.imgur.com/zsgREd7.png](https://i.imgur.com/zsgREd7.png)

**Comment by dragmz** [comment]
`uint8_t command_mem[COMMAND_MEM_SIZE];` => 268435456 bytes
