### ISSUE TITLE
[3.0x] Shader atan2() error

### ISSUE THREAD

**Issue by RaXaR** [godotengine/godot#13214]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win7, nVidia GTX 680

**Issue description:**
I tried to put this line into a shader:
(PS I checked the docs at [Shading Language](http://docs.godotengine.org/en/latest/learning/features/shading/shading_language.html), and it says that atan2() should be there?)
```
...
float lon = atan2(3.0, 4.0);
...
```
then the console gives:
```
ERROR: _display_error_with_code: SceneShaderGLES3: Fragment Program Compilation
Failed:
0(224) : error C7506: OpenGL does not define the global function atan2
   At: drivers\gles3\shader_gles3.cpp:167
ERROR: ShaderGLES3::get_current_version: SceneShaderGLES3: Fragment Program Comp
ilation Failed:
0(224) : error C7506: OpenGL does not define the global function atan2
   At: drivers\gles3\shader_gles3.cpp:470
ERROR: ShaderGLES3::get_current_version: Method/Function Failed, returning: 0
```
**Steps to reproduce:**
Add the above code to a shader.

**Comment by Zylann** [comment]
Is `atan(y,x)` working?

**Comment by eon-s** [comment]
`atan` uses a single parameter and works.

**Comment by Zylann** [comment]
I'm asking because GLSL apparently allows `atan` with two parameters

**Comment by vnen** [comment]
The problem is that the shader compiler uses the same function name (`atan2`) when translating to GLSL, and as @Zylann pointed out, it should translate to `atan` instead, using the two parameters.

**Comment by vigreco** [comment]
I've a similar issue with current master branch.
It seems I'm passing invalid arguments to `atan()`. Am I missing something?

```
float a = atan(-1.0, 1.0);
```

```
:10 - Invalid arguments for built-in function: atan(float,float)
drivers/gles3/rasterizer_storage_gles3.cpp:1649 - Condition ' err != OK ' is true.
```

**Comment by akien-mga** [comment]
Could you open a new issue for this? It's definitely related, but not the same as the original bug, which is solved.
