### ISSUE TITLE
move_and_collide dont work properly in 3D KinematicBody 

### ISSUE THREAD

**Issue by gad-o** [godotengine/godot#13210]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
debian 9, f2d07d5aeb9c591c5b361a3d346f049e003948d3

**Issue description:**
In 3D Plaformer Demo, KinematicBody stuck at on_wall state, when its between wall and floor. It only happens with BulletEngine.
You can see pr related to this : #13192 

**Steps to reproduce:**
1 - Open 3D Plaformer demo
2 - Change physics to bullet
3 - Go to position that shown by image(its first block in game)

![bulletstuck](https://user-images.githubusercontent.com/8027650/33167801-cd5048a4-d04f-11e7-9e01-1a51d535c6bf.png)

**Comment by kubecz3k** [comment]
There is definitely some bug going here (in demo or in the engine):
![peek 2017-11-23 14-54](https://user-images.githubusercontent.com/6129594/33176161-606bfcf6-d05e-11e7-9792-30ffe67c9eec.gif)

 @AndreaCatania could you elaborate? Also don't forget to check #13192 pr which is fix proposed by @gad-o

**Comment by gad-o** [comment]
@AndreaCatania PR probably wrong way for to fix, but it fixed :)
