### ISSUE TITLE
a couple of autotile bugs - straight lines and rectangular area drawing modes dont autotile

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#13224]
A couple of minor autotile bugs:

- holding shift to draw straight lines doesnt autotile 
- holding ctrl+shift to draw a rectangular area doesnt autotile
- bucket fill tool area filling doesnt autotile 

![autotilebug](https://user-images.githubusercontent.com/6495061/33191924-34ae4d8c-d0b6-11e7-849d-7352f834430e.JPG)

**Comment by blurymind** [comment]
Interesting behavior to observe:

1. create a rect area (ctrl+shift+drag) - it wont autotile
2. select the bucket filltool and right click on the area- this will erase it
3. ctrl+z to undo the action - the area will come back- autotiled!

**Comment by MarianoGnu** [comment]
that's definitely a bug, probably everytime you undo/redo the randompy picked tiles are different

**Comment by blurymind** [comment]
@MarianoGnu thank you for looking into this. Sorry for piling up many bug reports in the weekend - I think the autotiles are great, they just have a few things to iron out

**Comment by MarianoGnu** [comment]
leave chatting for fb, and dont worry, keep opening issues, this has to be as best as possible for godot 3.0  and then backported to 2.1.5

**Comment by blurymind** [comment]
I've been extensively pushing the autotile feature and trying to crash it before 3.0 gets to stable, because I plan to use it extensively on a project :D 
I think that it is a great addition to godot that massively improves 2d game workflow!

**Comment by MarianoGnu** [comment]
this is the first bug i'm fixing, i already have lines and rectangles working, but i'm also taking care that Undo/Redo works and is deterministic (will keep the same subtiles) right now the only missing point is undoing bucket fill. I also fixed the Neightbor Quadrant not updating issue wich i haven't seen reported.

**Comment by blurymind** [comment]
Thank you @MarianoGnu  :)
