### ISSUE TITLE
Autotile: ability to specify multiple 'icon' tiles

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#13226]
The icon tile is a tile that is drawn when the auto tile behaviour cant guess from surrounding tiles- as a result it is useful for scattering little pieces of grass or rocks outside of the autotiled area.

The icon is however limited to only one tile.
It would be very useful if we could select more than one tile, so when we drop a rock, it drops one of the selected icons at random
![multipleicontiles](https://user-images.githubusercontent.com/6495061/33192206-8edcc2aa-d0b8-11e7-8cd5-1924134573f3.JPG)
that way we could drop 2 rocks here, 5 rocks there - have some randomization/variety on the outside scatters

**Comment by damarindra** [comment]
Is this really needed? I mean, icon must be an icon. Not for drawing the autotile. If you ever using Tiled (2x2 bitmask), you can't draw single tile right? must be 2x2. That's why 3x3 is in here. To handle such 1 tile.

I think, the right feature needed is, allow specifying non-neighbors tile in 2x2 (I'm not sure actually). Let see @MarianoGnu opinion.

**Comment by blurymind** [comment]
Perhaps we could use the last selected tile as an icon and rename the 'icon' tab to what it is most useful for at the moment - specifying the non-neighbours tile.

I request here is to be able to specify more than one non-neighbours tile.

Notice how inside island tiles can be random, while non neighbours tiles can only be one tile.

Perhaps rename the 'icon' tab to:
- non neighbours tile?
- nn tile
need to come up with a shorter name..

**Comment by damarindra** [comment]
what I want to say is, that was what it works. 2x2 can't do single tile, so, instead of not drawing anything, it will draw the icon instead. 

An icon is important though, for example, I have a single image with multiple types of the tileset.

Also, if you using 3x3, you have a tile without any neighbors. So, if you want to change the icon to non-neighbors, it useless for 3x3. You know what I mean?

So, in the end, what I want to say is, how 2x2 works is like that, you can't specify single tile, at least has neighbors.

Solution with your current situation is, really simple, just create more tile (non autotile) and draw it. Well that was not random though

**Comment by blurymind** [comment]
It would be very useful if we could specify multiple icon tiles though- and have the autotile engine pick one of the selected by random - the way it does for inside tiles.

Thus why I am suggesting it here- it will make autotiling more feature complete imo. Many autotile resources out there contain a number of no neighbour tile variations- which godot's  autotile wont be able to take advantage of

**Comment by MarianoGnu** [comment]
if i'm correct this automatization is posible using _forward_subtile_selection virtual function

**Comment by MarianoGnu** [comment]
if i'm correct this automatization is posible using _forward_subtile_selection virtual function

**Comment by damarindra** [comment]
@MarianoGnu I've been trying to figure out the virtual function, but haven't tried it yet. So, in this case, @blurymind want to make single tile, and the 
`_forward_subtile_selection(int autotile_id, int bitmask, Object tilemap, Vector2 tile_location)`
So, if I draw a single tile, without any neighbors, what is the bitmask value? 0? if that the case, this is possible I think.

**Comment by damarindra** [comment]
yes, this is possible, now I understand that function, haha 👍 😃

**Comment by MarianoGnu** [comment]
```
const icons = [Vector2(0,5), Vector2(1,5), Vector2(2,5)]
func _forward_subtile_selection(int autotile_id, int bitmask, Object tilemap, Vector2 tile_location):
	if autotile_id == 1: # check by id or use tile_get_name(autotile_id) == "name" to verify identity
		if bitmask == 0: # 0 bitmask means tile unidentified
			return icons[randi() % icons.size()]
			# note: i recomend using a pool instead of random to have priority over icons
```

**Comment by MarianoGnu** [comment]
Problem with having multiple icons is that if you chose as icon a tile wich also has bitmask this means this tile should have 2 priorities, one for bitmask and one for icon (because you will most likely wich icon will be used more frequently than the other.

**Comment by blurymind** [comment]
If a tile has two priorities, it could be made to use only one of the two?

**Comment by MarianoGnu** [comment]
how? supose you have a tile both in icon and shared bitmask, you want it to have a priority of 1 for icons but 5 for bitmask group, to work that way you have to give all the icons a priority of 5, then they all will have the same priority, but if any of them is in another bitmask group you have to multiply the priority for all other tiles on that bitmask to match the proportion, this is just not worth imo.

**Comment by MarianoGnu** [comment]
just create individual tiles for these variations and use them instead of the autotile

**Comment by blurymind** [comment]
@MarianoGnu we can already set a tile to an icon and draw a bitmask on it, so I dont understand how setting more than one to icon would be different :)

**Comment by MarianoGnu** [comment]
because the icon usage is different from bitmask usage, it's used when there's no valid bitmask, this issue can be workarounded in many different ways that i described, allowing have several icons and priorities will only cause confusion to users and a bad user experience.

**Comment by damarindra** [comment]
I'm with Mariano, on the other hand, it will not look professional too.

**Comment by blurymind** [comment]
The request is to have autotile automatically set no neighbour tiles to a
random tile. The suggested workaround is to do it manually which is the
same as not have the feature.

**Comment by MarianoGnu** [comment]
Having multiple icons is posible if all of them have the same priority, still causes confusion ("what's priority property for? is it taken in account for icons or not? it should!")
Other solution could be having two Priority buttons, one for icons and one for bitmask groups

**Comment by MarianoGnu** [comment]
or use icon only for editor and have a section for "Fallback Subtiles" to select tiles and priorities

**Comment by blurymind** [comment]
> use icon only for editor and have a section for "Fallback Subtiles" to select tiles and priorities

This sounds like the best way to do it! :+1:

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by blurymind** [comment]
https://github.com/godotengine/godot/pull/16772
has finally been merged so I am closing this now!

**Comment by blurymind** [comment]
Oops, sorry, wrong issue closed

**Comment by akien-mga** [comment]
Is this still relevant in the current master branch?

**Comment by MarianoGnu** [comment]
I belive it does

**Comment by maksloboda** [comment]
What about allowing subtiles to have priorty of 0, and  treating subtiles with no bitmask as normal subtiles but with priority of zero by default?

**Comment by groud** [comment]
This enhancement is not needed anymore on master, as we replaced the Autotile system by the Terrains one.
