### ISSUE TITLE
Make user data path more customizable for exported games

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#13236]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Any OS, current master (bc75fae)

**Issue description:**
Currently there are two options for the system-specific location of the user data path (`user://`):
- `SYSTEM_DATA_PATH/godot/app_userdata/Game Name` (default, useful when developing to avoid cluttering the system paths)
- `SYSTEM_DATA_PATH/Game Name` (when using the `application/config/use_shared_user_dir` boolean option)
(where `SYSTEM_DATA_PATH` would be the relevant XDG path, typically `%APPDATA%` on Windows, `~/.local/share` on Linux and `~/Library/Application Support` on macOS)

See https://github.com/godotengine/godot/blob/d42c564/platform/windows/os_windows.cpp#L2200 and https://github.com/godotengine/godot/blob/d42c564/drivers/unix/os_unix.cpp#L448

I propose to extend the logic triggered by `application/config/use_shared_user_dir` with a second option allowing to define a custom data path, e.g. `application/config/user_dir_slug`.

The user path would then become `SYSTEM_DATA_PATH + custom_data_path`, after making sure that `custom_data_path` is "safe" (see `get_safe_application_name`), so for example `..` should not be allowed as it would let users escape the SYSTEM_DATA_PATH and mess with the system.

Typical use cases could be:
- `SYSTEM_DATA_PATH/Company Name/Game Name`
- `SYSTEM_DATA_PATH/game_name_different_from_autoconverted_one`
- `SYSTEM_DATA_PATH/Game Name/Version`

The `application/config/user_dir_slug` string would be empty by default, and use `get_safe_application_name` if undefined (a placeholder string could likely be shown too if the Project Settings allow that - if not, no need to implement support for it).

*Edit:* By the way right now `application/config/use_shared_user_dir` is enabled by default and must be unticked to use the custom defined path. Maybe it should be change to an opt-in `application/config/use_custom_user_dir` instead? (so same logic, but you need to enable the feature instead of disabling it)

**Comment by vnen** [comment]
Should #4097 be closed in favor of this?

**Comment by akien-mga** [comment]
Indeed. #4097 also mentions that it could be made platform-specific, but I'm not sure this is worth the trouble yet. Maybe better to wait for users actually publishing to various platforms that would express their need for this level of detail.

**Comment by akien-mga** [comment]
I'll work on this, I basically wrote everything that's needed to implement this in the first post :P

**Comment by Calinou** [comment]
I guess platform-specific project slugs could be defined using the `.<platform>` suffixes in the Project Settings, just like how `.mobile` is used for rendering settings specific to mobile platforms.

**Comment by LudovicGuerra** [comment]
I was just trying to change the custom user dir Name. But i don't understand why you put this limitation of putting it in the %APP_DATA%. Why I can't add it anywhere I want ? (like in my Documents).
Sorry for digging up, but this post was the best place to put my comment.

**Comment by Calinou** [comment]
> Why I can't add it anywhere I want ? (like in my Documents).

It's considered bad practice for applications to save files in the user's Documents folder automatically. You can still retrieve its location using `OS.get_system_dir(SYSTEM_DIR_DOCUMENTS)` and save files there manually if needed, but it cannot be selected as the user data directory.

**Comment by LudovicGuerra** [comment]
Ok I understand the problematic. But I found that many people have an error message that a resource is in used when they launch a scene due to the data being on appData.
Thanks for clarification, I will open an other ticket about the error then.
