### ISSUE TITLE
Godot Editor Mouse Offset 

### ISSUE THREAD

**Issue by Kopfenheim** [godotengine/godot#13234]
**HP ENVY x360 Laptop**
**OS**: Windows 10 (Build 15063)
**CPU**: Intel Core i7-7500U
**GPU**: Intel HD Graphics 620 
**Screen resolution**: 1920x1080 (100% global scaling)
**Godot 2.1.4 and Godot 3.0 Alpha 2**

**Issue description:**
I am a new Godot user and tried to run the stable 2.1.4 version on my laptop today. Upon launching it I noticed that the buttons on the greeting screen were registering hover and clicks with a slight pixel offset in the y direction. For example: In the image below, the "Scan" button was in hover state despite the cursor actually being at the highlighted red spot (on top of the "New Project" button).

![hover_offset](https://user-images.githubusercontent.com/33949432/33197823-87f2729e-d09c-11e7-8e7a-60011742f551.png)

This y offset seems to decrease as you go down the screen. This issue is also persistent in the actual editor windows.

I also tried using Godot 3.0 Alpha 2 but had the same result. However, when I entered fullscreen mode (Shift+F11) in Godot 3, the offset seems to disappear and everything starts working fine. But fullscreen mode removes the title bar for the window so I have to toggle the fullscreen mode if I want to open some other program. Trying to use fullscreen mode in Godot 2.1.4 doesnt seem to work as it just makes the 3D or 2D editor space to fill a larger area but doesn't actually make the program go fullscreen.

I have also tried to set the "Override high DPI scaling behavior. Scaling performed by:" to "Application" in the compatibility tab of the .exe's properties but without success

![image](https://user-images.githubusercontent.com/33949432/33198320-40653dfa-d09f-11e7-9ff8-7af3c19f0355.png)

As you can see from the two screenshots, the credits on the greeting screen are hidden by the title bar (the bar with the minimize, maximize and close buttons). So, it seems like the program tries to render itself in the available screen + the title bar area. But, the mouse position is read from the available screen space which results in the y offset.

**Steps to reproduce:**
Run either Godot 2.1.4 or Godot 3.0 Alpha 2 on a Windows 10 computer with a full HD display.

**Comment by Noshyaar** [comment]
Related #8902

**Comment by Kopfenheim** [comment]
Thanks, Noshyaar. Rolling back the display driver for my intel graphics card seemed to do the trick as suggested by #8902.
