### ISSUE TITLE
Error in Docs » Step by step » Design the GUI

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#13239]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

http://docs.godotengine.org/en/latest/learning/step_by_step/ui_game_user_interface.html#replace-the-label-s-font

"Count container has a minimum" it's not the count countainer but the Background one

It was setup in http://docs.godotengine.org/en/latest/learning/step_by_step/ui_game_user_interface.html#create-the-bars-base

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Noshyaar** [comment]
Issues related to documentation should be filed here: https://github.com/godotengine/godot-docs/issues
Note that the whole documentation is undergoing a complete rewrite.

**Comment by matrem** [comment]
Ok thanks I close this one
