### ISSUE TITLE
No hindi language?

### ISSUE THREAD

**Issue by abhaskumarsinha** [godotengine/godot#13248]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

I see there's no Hindi translation of Godot.....
I want to translate it to Hindi because of its the 3nd most speaking language and 2nd most popular one.

source http://www.vistawide.com/languages/top_30_languages.htm

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Noshyaar** [comment]
https://hosted.weblate.org/new-lang/godot-engine/godot/
