### ISSUE TITLE
Inspector spinner bottom bar issue

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#13255]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 https://github.com/godotengine/godot/commit/2e5dfbdb4beb52d021e89058ab64eac1a95d77b2

**Issue description:**

![https://i.imgur.com/wQYDaxi.gifv](https://i.imgur.com/wQYDaxi.gif)

**Comment by reduz** [comment]
bisect to find when this started happening would be welcome

**Comment by YeldhamDev** [comment]
AnimatedSprite had this same issue, maybe the solution works here as well? https://github.com/godotengine/godot/pull/12018

**Comment by mrcdk** [comment]
It's also happening on other places like:
![https://i.imgur.com/WuCA3JU.png](https://i.imgur.com/WuCA3JU.png)

It looks like whenever the data is incorrect (null or empty) it happens

**Comment by Noshyaar** [comment]
Behold! `git bisect` has spoken.

```
commit c2c8aac9a302700d777acf539fda6113004d83e3
Author: toger5
Date:   Tue Sep 12 17:12:47 2017 +0200

    added highlight area to slider
```

c2c8aac #11191
cc: @toger5

**Comment by vnen** [comment]
This also means that #12018 isn't the proper solution.

**Comment by reduz** [comment]
If anyone wants to look for a better solution, feel welcome

**Comment by TheAspiringHacker** [comment]
What if the slider were hidden if min = max? Is that a good design?

**Comment by bojidar-bg** [comment]
@TheAspiringHacker Sounds like a good idea indeed 😃

**Comment by TheAspiringHacker** [comment]
You can't check NaN equality, but C++11 has a function for checking for NaN. Are there any problems with using C++11 in Godot?

**Comment by YeldhamDev** [comment]
@TheAspiringHacker Godot uses C++03.

**Comment by depperm** [comment]
to check NaN you can check `if (x != x)` (where x is nan)

**Comment by bruvzg** [comment]
@depperm `x != x` will not work with `-ffast-math`, `-O3` and similar optimisations, you can test for the NaN bit patterns (assuming compiler use IEEE754 compliant math), but there is no portable way to test for NaN in C++03.

**Comment by TheAspiringHacker** [comment]
Perhaps `get_as_ratio` should throw an exception if the denominator is zero? If I were using a language with tagged unions, I would use an option type, but I don't think that using such a technique is idiomatic C++...

**Comment by bojidar-bg** [comment]
I think [`Math::is_nan`](https://github.com/godotengine/godot/blob/96dbf19093cfc88aa688d4321fd07c2fb9afb259/core/math/math_funcs.h#L108) would be a better idea?

**Comment by toger5** [comment]
Is someone already fixing it?

**Comment by toger5** [comment]
And thank you guys for finding that mistake!

**Comment by YeldhamDev** [comment]
With the merge of the actual solution, shouldn't [this](https://github.com/godotengine/godot/pull/12018) be reverted now?
