### ISSUE TITLE
Add support for difference message contexts in TTR (for polysemic words)

### ISSUE THREAD

**Issue by qichunren** [godotengine/godot#13267]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64 bit, v3.0.beta.custom_build.1406fb6

**Issue description:**
TTR("Project Manager") used in [editor/​editor_about.cpp](https://github.com/godotengine/godot/blob/master/editor/editor_about.cpp#L134) mean a person who manage the project.
And in [editor/​project_manager.cpp](https://github.com/godotengine/godot/blob/master/editor/project_manager.cpp#L1492), this mean project manage tool.

**Comment by Noshyaar** [comment]
This can be done by adding msgctxt field in .po files. Files related to tool translations (core/translation.cpp, core/ustring.cpp, editor/translations/extract.py etc.) have to be edited.

https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

**Comment by vnen** [comment]
Yeah, the macro should be able to define the message context.

**Comment by akien-mga** [comment]
Renamed the issue as the actual symptom was worked around by #15032, but we still need a proper fix (especially to be able to provide translation hints for the translators, as right now it's hard to know how to translate them).

**Comment by Noshyaar** [comment]
Related: #9398

**Comment by Zylann** [comment]
Ran into this while evaluating gettext translation in Godot, and apart from having an optional second string for `tr` (GDScript), `TTR` (C++) and every text property (scenes and resources) I can't imagine how context can be achieved in the way gettext does. For now I just use string identifiers rather than raw english.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/40443, closing.
