### ISSUE TITLE
Editor does not consider translation table when displaying texts

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#13265]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Any, Godot master (6086252f66ac185b97b0580352383e4b068b9fe5)

**Issue description:**

In the editor Godot displays texts without considering the translation table, but in runtime it translates the texts if they correspond to a key in the table. This behavior makes it hard to author localized UIs when you want to see the final layout in the editor - keys are often longer than values, especially for buttons and labels, and they don't let your realize what will be displayed in the end.

A workaround is to use mock strings when authoring layout and then set translations from script.

**Steps to reproduce:**

1. Add a translation key to your project, e.g. `MyTranslationKey`.
2. Add a Label to your scene and set its text to `MyTranslationKey`

Observe that in the editor the key is displayed and not its value. But when you launch the scene, the value is displayed.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/284, as feature proposals are now tracked on the Godot proposals repository.
