### ISSUE TITLE
Calls to set_process_input are pointless before node is ready

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#13270]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Any OS, Godot master (6086252f66ac185b97b0580352383e4b068b9fe5)

**Issue description:**

Not sure if it's a bug or by design, but calls to set_process_input and other similar functions before a node is added to the scene get "overridden" after the node is ready. A node sets process_input flag within its "ready" handler based on the presence of the corresponding process function. So if you set the flag before the node is ready, your value gets overridden. This doesn't seem immediately obvious/intuitive.

**Comment by mhilbrunner** [comment]
Suggestions on what could be improved for this... the docs?

**Comment by endragor** [comment]
Well, the code could remember that the value was set from outside. Or at least the docs should be updated.

**Comment by eon-s** [comment]
Maybe throw a warning if is used before a node is ready.

Set to true is not longer needed on 3, details on the "things can be done in _ready" may need to be added on documentation.

**Comment by reduz** [comment]
i suppose it could be docummented that, if detected on a script on ready,
it's turned on automatically.  if you want to turn it off, you can do on
ready
