### ISSUE TITLE
Pixel snap does not work.

### ISSUE THREAD

**Issue by VinnieH01** [godotengine/godot#13273]
**Windows 10, v3.0alpha2_mono, GTX 980Ti  driver : 388.13:**

**Issue description:**
The "Use pixel snap" feature doesn't work. No matter if it's on or off the sprite does not snap to the pixels. If it's located at a decimal position close to x.5 (e.g. 77.5009) the sprite becomes stretched out at the edges.

**Steps to reproduce:**
1. Create a scene with a sprite and alter the project settings to what's seen in the video.
2. Position the sprite so either x or y is close to (something).5 for example: y position = 77.5009 (like it is in the video and project linked below).

**Link to minimal example project:**

_The project is using mono_
[Test.zip](https://github.com/godotengine/godot/files/1503036/Test.zip)

[Video.zip](https://github.com/godotengine/godot/files/1503037/Video.zip)

**Comment by reduz** [comment]
@groud any news? Pixel snap may not be what most people is thinking about though, it just adjusts the vertex in the shader code, if i am not mistaken

**Comment by groud** [comment]
Oh I though it was for the canvas item editor, not the texture. I think I'm not able to fix it then :/

**Comment by guilhermefelipecgs** [comment]
@VinnieH01 Can you test again with the last commits from master?

**Comment by VinnieH01** [comment]
@guilhermefelipecgs I don't have all the necessary tools in order to build the project. I could certainly install them if you don't have the time to test it. Do you?

**Comment by akien-mga** [comment]
You can test with this binary if you want: https://github.com/GodotBuilder/godot-builds/releases/download/master_20171220-1/godot.windows.opt.tools.64.exe (future version 3.0-beta2).

**Comment by guilhermefelipecgs** [comment]
Tested, it's working properly.
With pixel snap:
![2017-12-21-153515_184x190_scrot](https://user-images.githubusercontent.com/1387165/34267657-d2946da6-e664-11e7-8075-9b7dcae8a1b5.png)
Without pixel snap:
![2017-12-21-153545_182x168_scrot](https://user-images.githubusercontent.com/1387165/34267658-d2b1fd94-e664-11e7-8bbb-5d7612dbe68f.png)
You can close this issue.

**Comment by samdze** [comment]
Found that TextureRect still has this problem, tested with TextureRect in _Stretch Mode: Scale On Expand_ with 3.1 alpha 0063ba92075094b7cc9d36f4551080b89e0c0e50
