### ISSUE TITLE
autotile collision shapes don't register with world.intersect_point(tilePositionHere) due to lacking a fill

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#13287]
This is something we use in order to implement a grid based top down movement:

it's used for detecting collisions, before moving to them

```
var gridSize = 32
func _process(delta):
	var resultUp = world.intersect_point(get_position()+Vector2(0,-gridSize))
	var resultDown = world.intersect_point(get_position()+Vector2(0,gridSize))
	var resultLeft = world.intersect_point(get_position()+Vector2(-gridSize,0))
	var resultRight = world.intersect_point(get_position()+Vector2(gridSize,0))
	print(resultRight)

......
		if Input.is_action_pressed(inputUpAction) and resultUp.empty():
			direction = Vector2(0,-1)
		elif Input.is_action_pressed(inputDownAction) and resultDown.empty():
			direction = Vector2(0,1)
		elif Input.is_action_pressed(inputLeftAction) and resultLeft.empty():
			direction = Vector2(-1,0)
		elif Input.is_action_pressed(inputRightAction) and resultRight.empty():
			direction = Vector2(1,0)
		else:	direction = Vector2(0,0)
```
The problem is that collision shapes created in the autotile editor dont get picked up by this code- as a result world.intersect_point always returns empty in the example code and the player can move through walls.

Note that the code works with normal tilesets collisions that are children to a tile

**Comment by blurymind** [comment]
Ok I think I understand why this might be happening - the autotile editor does not create closed fills. See this:
![autotilebug-emptyfills](https://user-images.githubusercontent.com/6495061/33234381-c31a3956-d21d-11e7-9329-a6b5ff4ab1c9.JPG)

I manually created a closed collision shape - as you can see its grid square centre contains a part  of the shape.

The autotile editor collision shapes are in contrast empty in the middle- they are only outlines - thus why they are completely useless for a grid based movement system where we rely on 

```
	var resultUp = world.intersect_point(get_position()+Vector2(0,-gridSize))
	var resultDown = world.intersect_point(get_position()+Vector2(0,gridSize))
	var resultLeft = world.intersect_point(get_position()+Vector2(-gridSize,0))
	var resultRight = world.intersect_point(get_position()+Vector2(gridSize,0))
```

to check the tiles next to the player

**Comment by eon-s** [comment]
Sounds like #10110

**Comment by MarianoGnu** [comment]
related but not the same. yes, the cquse of the issue is because i used concave polygon shapes wich where easier to use, sadly if i change it now it will break alltilesets done up until now, i could prevent this but would meqn an extra work for just a bunch of tilesets. an opinion here?
@reduz shouldn't segments work with tilemap on static mode? i heard from damar indra that this doesnt work well with kinematic bodies...

**Comment by MarianoGnu** [comment]
I dont think that using convex shapes is needed, your use case can be done in a different (and much better) way using a raycast instead of intersect_point, you case only works for rect shapes with the same size of the tile, but a raycast could detect segments or any other shape in the way to the destination.
Example (sorry for the spanish video, this is done with Godot 2.1 but the technique is the same): https://youtu.be/7MOIQ_oDmpU?list=PLdxpqdgprAY0bLAtdcWi8M1TZjSjIdDHn&t=616

Clossing this issue for now, feel free to reopen it if an use case for convex shapes is found.

**Comment by blurymind** [comment]
@MarianoGnu thank you for the link- although I dont understand what he's saying. My usecase is only one usecase. 
Closing the issue means that intersect_point will continue to not work with autotiles, but other devs wont be able to see it or address it in the future, unless someone reports it again.

I can't re-open it, this option is not available to me in github. I can only re-open issues if I was the one closing t them.
Only you can re-open the issue.

**Comment by MarianoGnu** [comment]
As i said, when the first usecase comes i'll reopen it. Using insersect_point is a bad solution imo, and you shouldn't need to rewrite a lot of code (just 10 lines as much) unless you have a lot of repeated code and  repeated scene setup. Do you use intersect_point for more cases than checking if destination is valid?

**Comment by blurymind** [comment]
@MarianoGnu fair enough. I will try using  is_cell_vacant method as well

**Comment by blurymind** [comment]
Ah damn, that method has been removed in godot3 :o

**Comment by blurymind** [comment]
damn,I wish godot had a method for checking if a cell contains a collision shape or not

**Comment by blurymind** [comment]
Btw gdquest made a popular tutorial on grid based movement here:
https://www.youtube.com/watch?v=3a6z0yxxfaM
Which is now broken for the autotile system. He has a lotof followers and his video tutorials are in english

**Comment by blurymind** [comment]
@MarianoGnu 
I am having the issue @eon-s is having with raycast2d and these empty collisions - the player controller gets stuck inside the tile.
https://github.com/godotengine/godot/issues/13319
Try doing a grid movement with the autotiles  and raycast2d- its super flaky
