### ISSUE TITLE
Editor crash on node hierarchy duplication

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#13282]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win 7 64 bit, Godot 31f62f5

**Issue description:**
The minimal description I found is: when duplicating the instanced scene node with children in the main scene, one gets the editor crash.

**Steps to reproduce:**
1) Open the attached project:

![default](https://user-images.githubusercontent.com/11571820/33232659-f80814d8-d21a-11e7-81a5-99552c10b50e.png)

2) select "DUPLICATE ME" node

3) duplicate it (CTRL+D)

4) crash

**Link to minimal example project:**
[duplicate-crash.zip](https://github.com/godotengine/godot/files/1503253/duplicate-crash.zip)

**Comment by akien-mga** [comment]
cc @RandomShaper

**Comment by RandomShaper** [comment]
Let's have a look!

**Comment by dragmz** [comment]
I think the check for !current_node should be called earlier, i.e.:

>
		Node *current_node = node->get_node(get_path_to(N->get()));

		if (!current_node)
			continue;

		if (p_flags & DUPLICATE_SCRIPTS) {
			bool is_valid = false;
			Variant script = N->get()->get(script_property_name, &is_valid);
			if (is_valid) {
				current_node->set(script_property_name, script);
			}
		}

**Comment by RandomShaper** [comment]
That would certainly fix the issue.

But we must delve deeper in order to understand why that can be `null` at that point in the first place. Otherwise we'll end up with lots of _ad hoc_ logic no one really understands and no one dares to touch because it's actually dangerous.

Please have a look at #13288 to see more exactly what I mean.

**Comment by dragmz** [comment]
@RandomShaper that makes perfect sense to me; thanks for the description in #13288
