### ISSUE TITLE
Autotile - always revert to the first setup when closing godot

### ISSUE THREAD

**Issue by damarindra** [godotengine/godot#13281]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
9738ebcda047fd9b4ddf71a0da5d682ade1a2666

**Issue description:**
When closing godot and open it again, the setup such icon, bitmask, etc revert to the previous setup.

**Step to reproduce**
I'm not quite sure this always happen, but you can clone my repo and try to change the setup -> close -> open again, no changes happen

**Update**
Try to figure out a little bit, so I found the solution, but still, this is a bug. We need to export the tileset scene to .tres after making changes. That will save all changes

**Link to minimal example project:**
https://github.com/damarindra/GameOff2017

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by damarindra** [comment]
This only happens only when I save my tileset as a file, otherwise working fine. Maybe this is normal in godot?

**Comment by E8AkoyqmTxWenGVG** [comment]
I have this problem too. I am using v3.0 stable on Arch

**Comment by damarindra** [comment]
closed, resource is not saved automatically when saving scene. You need to save manually by click the save icon on inspector
