### ISSUE TITLE
autotile editor- ability to mark squares as filled shapes/ autofill squares with a single click

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#13283]
Right now setting collusion,occlusion and navigation is extremely cumbersome, because you have to manually draw the shapes. It would save ALOT of time and effort if there is a quick command that simply fills the selected square with a square shape - instead of asking to manually create each single shape

99% of the time that is what we want anyway

See how rpg maker has it:
![image_tileset](https://user-images.githubusercontent.com/6495061/33233271-136a273a-d20b-11e7-9e76-0c570d53dcb1.jpg)
It takes one single click to mark a square as passable or non passable. We can also click and drag to set multiple squares as non passable and right click and drag- to set multiple squares as non passable.

Can we get a tool that emulates that somehow? Autoshape fill tool?

**Comment by damarindra** [comment]
If you talking about top down game, that was totally fine. But how about sidescroller game? Some of my tiles I created is not full square, sometimes I need polygon shapes (non square). Well, the collision using concave which is currently not usable for KinematicBody2D.

Maybe fixing the snap function (I try the snap and doesn't work) will be more suitable

**Comment by blurymind** [comment]
@damarindra  for more specific shapes, you can use the current shape tool and draw each square painstakingly manual as you  wish.

My proposal does not nullify the current tools. It merely compliments them.

Here I made a mockup:
![colusionshapefilltool](https://user-images.githubusercontent.com/6495061/33233521-17f98e86-d20f-11e7-9c5e-515e338e0241.gif)

**Comment by damarindra** [comment]
That was more suitable in this situation.

Is your snap tool working?

**Comment by blurymind** [comment]
@damarindra not sure about the autosnap- is it supposed to snap to pixels? If so- I dont think it works

**Comment by blurymind** [comment]
@damarindra  do collisions made in the autotile editor work for you? They dont seem to work at all for me- not even showing in debug>visible collision shapes.

**Comment by blurymind** [comment]
Found another bug here:
https://github.com/godotengine/godot/issues/13287

**Comment by MarianoGnu** [comment]
Snapping keep points inside of the tile, and also snaps to bitmask grid (the 2x2 and 3x3 invisible lines)
![autotile4](https://user-images.githubusercontent.com/1776044/33520702-ea21df14-d79e-11e7-8d65-e98b6801228c.gif)
 so a complete fill is 4 (easy) clicks instead of a single click, not sure if this is really necessary, difficult to implement, unless the right click deletes all the shapes on the tile (because there's no way to know which one of the shapes in the tile is the original one created with a fill, sure you can check points and see if they fit, but still not probably the best solution).
BTW @blurymind in the right side of the auto tiles tools there are Zoom In/Out/Reset buttons, it's much easier to edit shapes and record gifts using them. I originally wanted to add buttons to create shapes based on the bitmask (match mask and match non-mask), this tool was suposed to delete all shapes and create new ones. Not sure if will do it, for now it's easy enought to draw shapes.

**Comment by blurymind** [comment]
@MarianoGnu thank you for the tip. I knew about the snap. It still takes too long as compared to a possible bucket tool. 
Right now we can't even copy a shape from one tile and paste it into another. Would a copy and paste feature be easier to implement?
I mean if we can do it for bitmasks, why not also be able to do it for tile collision shapes?

**Comment by MarianoGnu** [comment]
copy-paste ALL the shapes together was also on the plans, and not so difficult to do

**Comment by blurymind** [comment]
copy-paste ALL would help a lot !

**Comment by MarianoGnu** [comment]
Adding 6 buttons (copy, copy all, paste, paste as duplicate, paste all, paste all as duplicate) makes stuff confusing, there are a LOT of things that can be done, making the work as simple and with the best experience is important.

**Comment by blurymind** [comment]
how about 3 buttons- copy all,paste all and a bucket fill tool-for filling
tiles quickly with a simple square

**Comment by CyanBlob** [comment]
I'd like to throw in my support for a bucket-fill tool, I think that would help a lot. I think just copy+paste would be hugely helpful as well, even if you leave off all other operations.
I also have to manually click the save icon to get the colliders to update, but not the icon or bitmask. That is very confusing, to the point where I thought the colliders were simply broken. I can maybe look into fixing that this weekend sometime if I have the time.

**Comment by xphere** [comment]
This has been addressed in 3.1 when creating a square collision, it fills the whole tile. Should we close it?

**Comment by blurymind** [comment]
It's still trash to use. See 
https://youtu.be/RPgTlxb7Bno?t=469

Can we reopen this bug and make it like my gif mockup:
https://github.com/godotengine/godot/issues/13283#issuecomment-346958074
![colusionshapefilltool](https://user-images.githubusercontent.com/6495061/33233521-17f98e86-d20f-11e7-9c5e-515e338e0241.gif)

One click is required to fill a cell - not 3 steps

**Comment by Calinou** [comment]
@blurymind Please open a proposal on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository.

**Comment by blurymind** [comment]
Here is alink to the proposal
https://github.com/godotengine/godot-proposals/issues/648
