### ISSUE TITLE
Carsh in win7 64

### ISSUE THREAD

**Issue by Omaranwa** [godotengine/godot#13280]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win7 64x
Godot Master (1406fb6ed)
Intel Core to Due 3Gh 3m Cash
3 GB ram
Intel G41 Express Chipest

**Issue description:**

I open the exe file i get this and then it show this
![1](https://user-images.githubusercontent.com/20274869/33232064-459e98d8-d208-11e7-8b43-cf4effc34412.JPG)
and then it show this
![2](https://user-images.githubusercontent.com/20274869/33232137-53fdfe5e-d209-11e7-9a24-5a2feaad0cc1.JPG)
and then the last before closing
![3](https://user-images.githubusercontent.com/20274869/33232217-c0f31782-d20a-11e7-9b96-69c545ead57f.JPG)

**Steps to reproduce:**
just run the grogram in that build!
with my spefction
sorry for my shitty english
**Link to minimal example project:**

**Comment by akien-mga** [comment]
The error message explains it: your graphics drivers do not support OpenGL 3.3, which is mandatory to run Godot 3.0.  Intel G41 Express is very low end and outdated, and I'm not sure that it would even support Godot 2.1.4 which requires OpenGL 2.1 - but you can try it.

**Comment by Omaranwa** [comment]
Godot 2.1.4 Works Fine 
is there any plan to add openGL 2.1 to Godot 3.0

**Comment by akien-mga** [comment]
It's planned for Godot 3.1, but not for Godot 3.0.

**Comment by Omaranwa** [comment]
note: i am the arabic trans on welate 
how can i try the last trans of my own i can becouse of this
thats sad thing

**Comment by akien-mga** [comment]
Ah yes that's quite annoying :( But sadly there is no alternative, on this computer you won't be able to run Godot 3.0 at all unless you change your graphics card. You'll have to test on another computer with a better GPU.

Closing as there's nothing we can do for 3.0. The GLES2 renderer will be added in Godot 3.1, but there are other issues keeping track of it already.
