### ISSUE TITLE
get_viewport().get_size_override() wrong in fullscreen Linux

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#1328]
Stretch mode is 2D, strtch aspect is keep_height.  Viewport dimensions are set to a wider aspect ratio than my screen's. When the game first loads (in a node's _ready), get_viewport().get_size_override() reports the correct height, and a width that *would* be correct if the screen was wide enough to fit it (ie, aspect ratio is maintained, disregarding what my screen will actually fit). But it's not actually that wide, so the camera's position is offcenter.  Similarly, if the viewport dimensions have a narrower aspect ratio than the screen, the camera is off center in the other direction.

The value reports this same wrong value the first time through _process.  Every time after that, it's correct.  If I put camera.make_current() in _process, the problem goes away, because it'll quickly be recalculated.  But of course repeatedly setting this is more a workaround than a proper solution.

**Comment by akien-mga** [comment]
Can you still reproduce the issue in the current master branch / nightly builds? This API has changed a bit IIRC.

**Comment by akien-mga** [comment]
Ping :)

**Comment by akien-mga** [comment]
No answer, and no other complaints on this topic from other users, so I'll assume it was fixed. Please comment if you can still experience it and want me to reopen the issue.
