### ISSUE TITLE
Scripting Error

### ISSUE THREAD

**Issue by XavierDD1st** [godotengine/godot#13297]
# **Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 home 64 bit ( x86_64,)
Godot version v2.1.4-stable_win64

# **Issue description:**

So when running a test of the game it stops and in the debug tab it outputs 
Script inherits from native type 'Panel', so it can't be instanced in object of type: 'Button'
# **Steps to reproduce:**

Run the screen

# **Link to minimal example project:**

[LD-40.zip](https://github.com/godotengine/godot/files/1503529/LD-40.zip)

**Comment by sketchyfun** [comment]
Your buttons are using the same script as your panel, and your script extends Panel, so it won't work on a button.

Looking at your scene, only your panel needs the script, so if you clear the script from your two buttons, it will work.

**Comment by XavierDD1st** [comment]
Thanks.

**Comment by XavierDD1st** [comment]
Should I close this?

**Comment by sketchyfun** [comment]
Yes please :)
