### ISSUE TITLE
Crach set_stream_position

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#13305]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu16.04, Master, GTX 965M

**Issue description:**
if use set_stream_position
Game crash

**Steps to reproduce:**
Start example

**Link to minimal example project:**
[Bug video.zip](https://github.com/godotengine/godot/files/1503680/Bug.video.zip)

**Comment by dragmz** [comment]
bus_index seems to have uninitialized value (race condition?) and causes AV exception at:

>
 	godot.windows.tools.64.exe!AudioFrame::operator+=(const AudioFrame & p_frame) Line 67	C++	Symbols loaded.
	godot.windows.tools.64.exe!VideoPlayer::_mix_audio() Line 105	C++	Symbols loaded.
 	godot.windows.tools.64.exe!VideoPlayer::_mix_audios(void * self) Line 79	C++	Symbols loaded.
 	godot.windows.tools.64.exe!AudioServer::_mix_step() Line 289	C++	Symbols loaded.
 	godot.windows.tools.64.exe!AudioServer::_driver_process(int p_frames, int * p_buffer) Line 181	C++	Symbols loaded.
 	godot.windows.tools.64.exe!AudioDriver::audio_server_process(int p_frames, int * p_buffer, bool p_update_mix_time) Line 65	C++	Symbols loaded.
 	godot.windows.tools.64.exe!AudioDriverWASAPI::thread_func(void * p_udata) Line 219	C++	Symbols loaded.
 	godot.windows.tools.64.exe!ThreadWindows::thread_callback(void * userdata) Line 55	C++	Symbols loaded.
 	kernel32.dll!BaseThreadInitThunk()	Unknown	Symbols loaded.
 	ntdll.dll!RtlUserThreadStart()	Unknown	Symbols loaded.

**Comment by DimaKiva** [comment]
OK, no crash now. But the video position does not change.
