### ISSUE TITLE
Drag and drop doesn't work as expected when using C#/mono

### ISSUE THREAD

**Issue by rcarjan** [godotengine/godot#13316]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu Linux 17.10
Godot v3 alpha2
Nvidia GTX970, Driver version 387.34

**Issue description:**
When using the mono build of Godot 3 alpha2, it seems that the drag and drop functionality doesn't work as expected. When dragging from one TextureRect to another, the `DropData` method doesn't seem to fire, although `CanDropData` seems to be called. If I try to use `ForceDrag` and an _InputEvent_, `CanDropData` seems to be called twice when dropping the data onto another TextureRect: Once on left mouse button pressed, and one on left mouse button released, however `DropData` is called only once, on left mouse button pressed. This leads to a few issues rendering drag-and-drop basically unusable when using C#.

**Steps to reproduce:**
Create two controls, and try to implement the drag-and-drop methods on them using C#. Dropping data doesn't work as expected, as explained above.

**Link to minimal example project:**

Here is a gist with the relevant parts of the code, in GDScript and in C#: https://gist.github.com/rcarjan/d921e256be65785d31eac9f64e0ecd5b
The GDScript code works correctly, while the C# code doesn't.

As a clarification, the idea when I have written the GDScript code was to allow drag and drop inside an inventory by either dragging the items from one slot to another, or by either clicking on them to force drag, and dropping them on another slot. If the item was dropped on a already occupied slot, the item they would be swapped and the old item would be force dragged.

Edit: Added Gist link for source code.

**Comment by Vega-KH** [comment]
I can confirm there is a bug with drag / drop and mono. For some reason, it seems like CanDropData ALWAYS returns false. For example, if I hardcode a true value like this:

`public override bool CanDropData(Vector2 position, object data)
        {
            return true;
        }`

And then drag something over that box, it still does not allow dropping (crossed circle as pointer.)

On a related note, why does GetDragData return a Godot.Object, while CanDropData and DropData take a System.Object as a parameter? This makes life more difficult! GetDragData should return a System.Object.
