### ISSUE TITLE
Exported Windows executable doesn't use the game's icon for the running game.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#13321]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64bit - Godot 3.0 2f3c4c94d from http://godot3builds.digitecnology.com/

**Issue description:**
Previously in 2.1.x the exported game would have the proper icon while running. Also in 3.0 while running the game in the editor it does use the correct icon. But the exported executable uses the Godot icon.

Exported game:
![](https://i.imgur.com/AcdwbMA.png)

Game run from editor:
![](https://i.imgur.com/xciPOF3.png)

**Comment by reduz** [comment]
This is a really strange bug, as i think the code is the same everywhere.

In any case, we've been discussing about calling rcedit.exe (was it that one?) to modify the Widnows binary (and running it with wine on osx and linux), @vnen offered to give it a try. There was another issue open i think about it.

**Comment by vnen** [comment]
I know what's wrong with this. If you set the icon to `res://icon.png`, the start routine tries to get the icon from that path, but since the `icon.png` is **not** on the final export (because of the new import system, all resources are in the `.import` folder). So it doesn't find the file and load the Godot icon instead.

**Comment by drentsoft** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  drentsoft@gmail.com
    Domain drentsoft.com has exceeded the max emails per hour (507/500 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:25069)
	by wdc002.hawkhost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-8a6a-info=drentsoft.com@sgmail.github.com>)
	id 1eMTU2-000mgD-Tt
	for info@drentsoft.com; Wed, 06 Dec 2017 01:47:07 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=+Feco0SnxdsUANx6QPx38+eOGN8=; b=KXQjXYDVts4SAiiW
	ND1q0Vekwp8LBnT/qYuKKiKVdoTqHOB4gGoLngqSLxX+xjdd3pDJoL6GwklReJKF
	z8VZG3Qrf0rekteSoAb8/tcFvvuWqm7wgvM8Frq8OOV+ORknClwbsA9TH31GNnHM
	iv3S99TsY0vj7JRVaxVa7GzEyzQ=
Received: by filter0195p1las1.sendgrid.net with SMTP id filter0195p1las1-13727-5A27926A-1
        2017-12-06 06:47:06.350489051 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0010p1iad2.sendgrid.net (SG) with ESMTP id 8Qiux0QKQMO1nknKv3NosQ
	for <info@drentsoft.com>; Wed, 06 Dec 2017 06:47:06.204 +0000 (UTC)
Date: Wed, 06 Dec 2017 06:47:06 +0000 (UTC)
