### ISSUE TITLE
_err_print_error loses track of error description

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#13324]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

The error description provided via last error, is lost before it is forwarded to handlers because _err_error_exists is too global and reseted to false.

Keeping track locally of _err_error_exists can solve the problem, but I guess it's not perfect :
```
void _err_print_error(const char *p_function, const char *p_file, int p_line, const char *p_error, ErrorHandlerType p_type) {

    bool local_error_exists = _err_error_exists;
	OS::get_singleton()->print_error(p_function, p_file, p_line, p_error, _err_error_exists ? OS::get_singleton()->get_last_error() : "", (Logger::ErrorType)p_type);

	_global_lock();
	ErrorHandlerList *l = error_handler_list;
	while (l) {

		l->errfunc(l->userdata, p_function, p_file, p_line, p_error, local_error_exists ? OS::get_singleton()->get_last_error() : "", p_type);
		l = l->next;
	}

	_global_unlock();

	if (local_error_exists) {
		OS::get_singleton()->clear_last_error();
		_err_error_exists = false;
	}
}
```

**Steps to reproduce:**
for example adding this in a script node : 
```
 func _ready():
	var root= get_node("/root")
	var host = Node.new()
	host.set_name("flag_host")
	root.add_child(host)
```

will trigger an error : 
https://github.com/godotengine/godot/blob/024c4f14a14e67f15adbcca39c6a941ea89e0f3d/scene/main/node.cpp#L1330

it should get a description forwarded to godot console, but as this function has a bug (_err_error_exists reseted to false before line 83):
https://github.com/godotengine/godot/blob/024c4f14a14e67f15adbcca39c6a941ea89e0f3d/core/error_macros.cpp#L81

it is not forwarded, we see the description only in std::cout. godot get the simplified error msg

**Link to minimal example project:**

**Comment by matrem** [comment]
Should I make a PR based on this correction, or is this a wrong approach?
Perhaps error macro should never set _err_error_exists to false?

**Comment by reduz** [comment]
Is this still broken? if so a PR would be welcome.

**Comment by Anutrix** [comment]
Is this still broken? If so a PR would be nice.
@ anyone
@matrem

**Comment by akien-mga** [comment]
The example given above seems to work fine in the current master branch (14e6760d), so assuming fixed.

If the issue still exists, it would be best to open a PR with the suggested fix so that it can be discussed and merged directly.
