### ISSUE TITLE
Launching godot error (It crashes on launch.)

### ISSUE THREAD

**Issue by XavierDD1st** [godotengine/godot#13326]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64-bit
Godot_v2.1.4-sable

**Issue description:**

![image](https://user-images.githubusercontent.com/19256175/33245606-2680360c-d2d8-11e7-98a1-513ca7074c51.png)
So I launch it it boots up then it crashes and i have deleted folders relating to it and reinstalled it.

**Steps to reproduce:**
just launching it.

**Link to minimal example project:**

[LD-40 (2).zip](https://github.com/godotengine/godot/files/1504307/LD-40.2.zip)

**Comment by XavierDD1st** [comment]
Does anyone know how to fix this?

**Comment by akien-mga** [comment]
Well I haven't had time to check the linked project yet, but the screenshot looks like there's no `splash_logo.png` file.

**Comment by XavierDD1st** [comment]
![splash_logo](https://user-images.githubusercontent.com/19256175/33277108-8a186814-d365-11e7-82fa-2105500a76a3.png)

**Comment by XavierDD1st** [comment]
Thats the splash logo.

**Comment by volzhs** [comment]
![image](https://user-images.githubusercontent.com/8281454/33277377-b7aaa348-d3db-11e7-8132-9ba72a40f921.png)
it works on my Ubuntu 16.04 with godot 2.1.4 (e132adf)

**Comment by vnen** [comment]
It works for me in Windows 10 64-bit with the 2.1.4-stable executable from the website.

**Comment by XavierDD1st** [comment]
I don't know why its like that for me

**Comment by vnen** [comment]
I know the issue: you are exporting with the data packed into the executable. This option is very unstable, use a export to PCK instead.

**Comment by XavierDD1st** [comment]
Thanks but I can't run the program so I can export.

**Comment by vnen** [comment]
No actually, I got it wrong, the problem is that you used the option "Export selected resources" but didn't select any resource, so it's empty. Use the "Export all resources" option, or select all the individual resources to export.

----

If you can't run Godot, then it's likely that you overwrote the original binary with your empty export. Re-download Godot from the website and put in a folder **outside your project**. It should run fine.

**Comment by XavierDD1st** [comment]
Thats what I have been doing and I don't know what else cause it.

**Comment by XavierDD1st** [comment]
I'll try the steam version.

**Comment by vnen** [comment]
Then likely you have an `engine.cfg` file lost in your system in a folder above the Godot executable.

**Comment by XavierDD1st** [comment]
Well steam's installation didn't crash

**Comment by vnen** [comment]
I'll close because this is not a bug. Search for an `engine.cfg` file in your system, on the folder hierarchy where you put the Godot binary, then delete it or move it to its own folder.
