### ISSUE TITLE
OpenGL error: GL_INVALID_OPERATION in glBindTexture(non-gen name)

### ISSUE THREAD

**Issue by HadesD** [godotengine/godot#13337]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot_v3.0-alpha1_win32.exe, Intel i3 530

**Issue description:**

First, I open editor, it shown popup:
```
Can't Create An OpenGL 3.3 Rendering Context
```
And Error in console:
```
DETECTED MONITORS: 1
ERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core\project_settings.cpp:841
ERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core\project_settings.cpp:841
ERROR: RasterizerGLES3::initialize: Error initializing GLAD
   At: drivers\gles3\rasterizer_gles3.cpp:163
```
Then I trying to install Mesa, generated opengl32.dll, then I open **Godot_v3.0-alpha1_win32.exe** again, Popup not show, but it shown this, and also can not see anythings on editor after Godot logo fadeout:
```
DETECTED MONITORS: 1
Activated GL 3.3 contextERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core\project_settings.cpp:841
ERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core\project_settings.cpp:841
OpenGL ES 3.0 Renderer: softpipe
WARNING: not found: rendering/quality/anisotropic_filter_level
WARNING: not found: rendering/quality/anisotropic_filter_level
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
WARNING: not found: locale/translation_remaps
err status: 8cdd
ERROR: RasterizerStorageGLES3::_render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers\gles3\rasterizer_storage_gles3.cpp:6064
err status: 8cdd
ERROR: RasterizerStorageGLES3::_render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers\gles3\rasterizer_storage_gles3.cpp:6064
err status: 8cdd
ERROR: RasterizerStorageGLES3::_render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers\gles3\rasterizer_storage_gles3.cpp:6064
err status: 8cdd
ERROR: RasterizerStorageGLES3::_render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers\gles3\rasterizer_storage_gles3.cpp:6064
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 2   Severity: High  Message: GL_INVALID_OPERATION in glBindTexture(non-gen name)
   At: drivers\gles3\rasterizer_gles3.cpp:123
mesege
....
```

**Comment by Zireael07** [comment]
Does Intel 530 support OpenGL 3.3?

**Comment by akien-mga** [comment]
> Does Intel 530 support OpenGL 3.3?

Yes it's a relatively recent and decent chipset, it should support OpenGL 4.4 or maybe higher with up-to-date drivers.

**Comment by akien-mga** [comment]
- Check that your drivers are properly installed, and see what OpenGL support is reported in `dxdiag.exe`
- Try with a more recent build, 3.0-alpha1 is several months old

**Comment by HadesD** [comment]
Should I create a new issue?

I downloaded **Godot_v3.0-alpha2_win32.exe** and open it, then popup shown:
```
Can't Create An OpenGL 3.3 Rendering Context
```
Console debug:
```
ERROR: RasterizerGLES3::initialize: Error initializing GLAD
   At: drivers\gles3\rasterizer_gles3.cpp:162
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] ???
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```

**Comment by akien-mga** [comment]
> Should I create a new issue?

No, that's still the same issue related probably to your drivers not being properly set up.

**Comment by HadesD** [comment]
@akien-mga here is **dxdiag** info (so sorry because it is Japanese)
![untitled](https://user-images.githubusercontent.com/11664992/33261013-c4f88222-d3a4-11e7-9dc6-4c8fb9d368bb.png)

_I don't know the version OpenGL of cocos2d-x but it is working correctly on my PC_

**Comment by akien-mga** [comment]
Are you sure that your chipset is "Intel HD Graphics 530"? It's a chipset from 2015 and your drivers are from 2012... I would really recommend that you try to update your graphics drivers, I assume that you're on Windows 7 but even then there should be more recent drivers (those only support DirectX 10, which is also quite low).

**Comment by Stajin** [comment]
Hi HadesD, it appears you have an i3 530 - that is the CPU name, there is an Intel HD 530 GPU but that is a separate thing, available in newer processors.

Your CPU is a Clarkdale, that means it uses a legacy type of Intel HD GPU and, from what I can tell, only supports OpenGL 2.1 from what I can see [here](https://www.anandtech.com/show/2901/4).

I have an old laptop too which has (I believe) one of the first GPUs from Intel to support OpenGL 3.1 (The HD3000, for anyone reading this - yes it *does* do 3.1, but only in Linux), so I'm pretty sure your iGPU is too old as the HD3000 is much newer than your iGPU (and also sucks pretty bad, so even if you can fudge yours to work, I really wouldn't).

Your only recourse is to either use software OpenGL using MESA which will be pretty slow, or to upgrade.

**Comment by HadesD** [comment]
Yeah, thanks @Stajin and @akien-mga
I will wait until 3.1

**Comment by hpvb** [comment]
I see this problem now on my RX580 on Mesa now also. This thing definitely supports all of GL3.3 

```
OpenGL renderer string: Radeon RX 580 Series (AMD POLARIS10 / DRM 3.23.0 / 4.15.0-rc3, LLVM 4.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.4
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```

**Comment by hpvb** [comment]
This error comes from  https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_canvas_gles3.cpp#L1550 it seems to be because there's no glGenTextures() call for the effects.mip_maps[].color textures. I don't really know where this should be added.

Apparently on core contexts it's illegal to try to run glBindTexture() on texture names not generated by glGenTextures(). On Mesa you can only get core contexts.
