### ISSUE TITLE
DAE export/import problem with multimesh skeletons and meshes having shape keys

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1333]
On the following condifion:
1. More than one mesh per skeleton (e.g one skeleton, 3 meshes parented at it)
2. More than one mesh have shape keys

Animation pose on one of the meshes applied twice, as its rest pose
is not actually original rest pose, but pose it was in on export.

**Comment by slapin** [comment]
So if you have either modifiers or shapes, you have to reset armature pose and move timeline to 0
Not doing so makes scene very distorted.

**Comment by akien-mga** [comment]
Hi @slapin, is this issue still valid in the current master branch? IIUC there has been some work done on the collada exporter (in particular by yourself).

**Comment by slapin** [comment]
Well, it regularly happens to me if I don't care to reset to 0 and set
armature to rest pose.

**Comment by akien-mga** [comment]
Thanks, marking as confirmed then.

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.

**Comment by slapin** [comment]
Well, this one is still valid and reproducible, why should I reopen
it? This is not my fault nobody cared for this bug for so long.

**Comment by akien-mga** [comment]
Can you provide a DAE that triggers the issue? It's hard to debug otherwise (and there are enough issues to handle with detailed steps to reproduce to try to make one's own reproducer model in the hope that maybe this stale issue might still be valid after a whopping 3 years).

**Comment by slapin** [comment]
OK, I did serious test and I think this one might be closed. This is no longer fundamental issue, but there are some minor rough edges now which might be solved. Just for notes:
1. RAM consumption during scene import is enormous - 40K poly scene uses 13GB of RAM and that memory remains used (i.e. leak). It looks like fix is not 100% complete (no longer corrupting but still leaking). Need to look into this ASAP unless somebody already works on it. No promises as I have very little time to work on Godot now :(
2. There are spurious indexing errors after import, which might affect performance (mesh with blendshapes is about 3 times slower animating than without them, even trivial ones). Will look into this one in early 2019 unless somebody does it first. I have workaround for this to use "blendmaps" like in that famous Sims4 talk, but stock blend shapes should not be THAT bad.
