### ISSUE TITLE
code folding folds last empty lines

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#13339]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master 6aa331e

**Issue description:**

1. code folding folds last empty lines
    * should not fold empty lines
2. can't click unfold icons
    * last line should be visible beyond scroll bar

**Steps to reproduce:**
![code folding](https://user-images.githubusercontent.com/8281454/33268336-5204d7d6-d3c0-11e7-9c5d-653b9eb1ce23.gif)

**Link to minimal example project:**

**Comment by blurymind** [comment]
possibly related to
https://github.com/godotengine/godot/issues/13195

**Comment by TheAspiringHacker** [comment]
Hi, I would like to work on this issue. I think that I've found the problem; [if the line is blank](https://github.com/godotengine/godot/blob/0f55d3767d03e81e6105185ffae0fae7260cd1e8/scene/gui/text_edit.cpp#L4564), it would be set as hidden, with the program logic assuming that there will be non-empty lines of a lesser indentation later on. In the case that there are trailing blank lines, of course, there are no lines afterward to trigger the else clause. I'll rewrite the code to fix the issue.

**Comment by akien-mga** [comment]
So it looks like we have three pending PRs to fix the same issue: #13362 by @groud, #13375 by @ianb96 and #14010 by @TheAspiringHacker. Could the three of you check all PRs and decide on which one or mix of ones would be the best? :)

**Comment by ianb96** [comment]
I vote to use #13362 by @groud for this issue.
I'll submit a separate pr for the horizontal line scrolling fix.

**Comment by TheAspiringHacker** [comment]
Yeah, I agree. Looking at @groud's code, their solution is the same as mine except for the variable name and the detail that they decided to track the last line to fold as opposed to the first line not to fold. Because they made their PR before I did, I think that theirs should be accepted.
