### ISSUE TITLE
Occasional black rendering artifacts

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13340]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
d992eb1b25e3612293d6c72cd462a99cd5a0e4a3

**Issue description:**
Since some time I'm able to observe one-frame black screen artifacts that are visible rarely. 
I honestly don't know what changed and when it happed for me the first time. My first suspicion was that it's related somehow with directional light shadow, since I was tweaking those parameters some time ago. But not sure it's a case since I tested on default directional light settings and it happens as well. 

***Please take a look at video:*** https://youtu.be/PUbcKjpo8tk

**Steps to reproduce:**
Don't know how to reproduce yet. 

**Link to minimal example project:**

**Comment by reduz** [comment]
1) does it still happen when glow is turned off?
2) any chance to make a reproduction case?

**Comment by kubecz3k** [comment]
1. yes it seems it still happens
2. Well I will try

**Comment by kubecz3k** [comment]
It happens only when rim parameter of the material on the hero. I was able to reproduce it finally inside external small project, but it's not very good project to check if the error exists since it happens very rarely there (at the best once for maybe 3-5 minutes).  
**In any case seems that RIM on material enables this behavior.**
Later I will modify our material demo to see if it will happen more often there.

**Comment by reduz** [comment]
so it seems it's related to #13986

**Comment by kubecz3k** [comment]
Seems like it might be :)
