### ISSUE TITLE
Mono build for macOS hardcodes mono version for the framework lookup, prevents loading with different but compatible version

### ISSUE THREAD

**Issue by bferguson3** [godotengine/godot#13355]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacBook Air on HighSierra (OSX 10.13.1)
Godot 3.0 alpha2-mono

**Issue description:**
Unpacked the mono zip and ran the executable but nothing happened. 

Note: Godot 3.0 alpha2 NON-mono build works fine.
I also already had the most recent version of mono installed because of MonoGame.

**Steps to reproduce:**
1. Download Godot 3.0 alpha2-mono on OSX High Sierra
2. Try to start the app

Please let me know if there's anything I can do to debug this issue. :)

**Comment by akien-mga** [comment]
Do you have mono installed? http://www.mono-project.com/download/

**Comment by bferguson3** [comment]
Yep as I said above, it's installed because of MonoGame.

![2017-11-27 2 04 39](https://user-images.githubusercontent.com/32964659/33291822-00349bd8-d37c-11e7-83b3-c3958b9a7ed5.png)

**Comment by akien-mga** [comment]
Ah sorry I had missed that. Can you run Godot from a terminal?

**Comment by bferguson3** [comment]
Np, and yeah, it does the same thing. It bounces in the tray for a second then closes itself. No error messaging anywhere that I can find.

**Comment by neikeq** [comment]
Can you paste the mono log here? Not really sure what the path is on OSX. It should be in the godot setting's folder, then `mono/mono_logs` directory. Should switch to the new logging system...

**Comment by akien-mga** [comment]
> Not really sure what the path is on OSX. It should be in the godot setting's folder, then mono/mono_logs directory.

In alpha2 it should be in `~/.godot/mono/mono_logs`. In beta1 and later it will be `~/Libraries/Application Support/Godot/mono/mono_logs`.

**Comment by bferguson3** [comment]
Thanks for the tip. They all say the same thing:

Config attempting to parse: '/Library/Frameworks/Mono.framework/Versions/5.4.0/etc/mono/config'. (in domain Mono, info)
Config attempting to parse: '/Users/bferguson/.mono/config'. (in domain Mono, info)
process_set_name: using [(null)] as prog name (in domain Mono, debug)
mono_w32handle_new: create Process handle 0x100 (in domain Mono, debug)
Assembly Loader probing location: '/Library/Frameworks/Mono.framework/Versions/5.4.0/lib/mono/4.5/mscorlib.dll'. (in domain Mono, info)

**Comment by bnowak22** [comment]
I am also experiencing this issue with the 3.0 beta build w/mono on my macbook air.  I also have mono installed.

**Comment by bnowak22** [comment]
in my logs i see Config attempting to parse: '/Library/Frameworks/Mono.framework/Versions/5.4.0/etc/mono/config'. (in domain Mono, info)`.  At that directory, I see I have 5.4.1 installed - seems that might be the culprit.

**Comment by bnowak22** [comment]
I was able to install 5.4.0 from [here](https://download.mono-project.com/archive/5.4.0/macos-10-universal/) and now the Godot 3.0 beta 1 w/mono is firing up like a dream!

**Comment by insraq** [comment]
I have the same issue and the log is as follows:
```
Config attempting to parse: '/Library/Frameworks/Mono.framework/Versions/5.4.0/etc/mono/config'. (in domain Mono, info)
Config attempting to parse: '/Users/insraq/.mono/config'. (in domain Mono, info)
process_set_name: using [(null)] as prog name (in domain Mono, debug)
mono_w32handle_new: create Process handle 0x100 (in domain Mono, debug)
Assembly Loader probing location: '/Library/Frameworks/Mono.framework/Versions/5.4.0/lib/mono/4.5/mscorlib.dll'. (in domain Mono, info)
```
It seems that Mono version is somehow hardcoded in the binary?

**Comment by akien-mga** [comment]
We're indeed building the binaries with 5.4.0 (5.4.1 was released very recently, haven't had time to try it yet), so that should explain the issue.

Still, there should be a version-independent path we can link to, we need to fix this. CC @neikeq

**Comment by bferguson3** [comment]
Awesome, thanks for the workaround and research @bnowak22 @akien-mga !

**Comment by bruvzg** [comment]
This issue and #13726 can be fixed or by setting `MONO_PATH` environment variable to `/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/` and
`MONO_CFG_DIR` to `/Library/Frameworks/Mono.framework/Versions/Current/etc/`

Or by passing correct path to `mono_set_dirs` here:
https://github.com/godotengine/godot/blob/master/modules/mono/mono_gd/gd_mono.cpp#L175

**Comment by akien-mga** [comment]
@neikeq Can we set the path to `Versions/Current` in `mono_set_dirs` as advised by @bruvzg?

I can try to `s/5.4.1/Current/g` in https://github.com/GodotBuilder/godot-builds/blob/mono/.travis.yml#L132-L134 and see if that fixes the issue, but I don't have high hopes (I guess `Current` is just a symlink and the compilation will still hardcode 5.4.1 for the library lookup).

**Comment by bruvzg** [comment]
In addition to Mono assembly path, current master have `libmonosgen-2.0.dylib` copied to `bin` folder during build but is not used since all Mach-O binaries have hardcoded absolute paths to dynamic libraries.

Both executable and library should be patched to use relative lookup path using `install_name_tool`.

```
install_name_tool -change /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/libmonosgen-2.0.1.dylib @executable_path/libmonosgen-2.0.dylib ./bin/godot.osx.opt.tools.64.mono
install_name_tool -id @rpath/libmonosgen-2.0.dylib ./bin/libmonosgen-2.0.dylib
```

**Comment by akien-mga** [comment]
Bump @neikeq, what about @bruvzg's proposals?

**Comment by Arcnor** [comment]
Setting `MONO_PATH`/`MONO_CFG_DIR` works for me as far as opening Godot goes. However, when trying to open a project I get:

```
Stacktrace:


Native stacktrace:

Mono: Runtime cleanup...
debugger-agent: Unable to listen on 43
```
... then Godot just crashes.

However, adding a symlink from 5.8.0 (my current version) to `5.4.1` (on `/Library/Frameworks/Mono.framework/Versions`) did the trick.

I still cannot compile, mind you (`System.MissingMethodException: Attempted to access a missing method.`) but that's for another ticket, I guess.
