### ISSUE TITLE
GDScriptDepSort broken.

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#13353]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**
GDScriptDepSort operator does not work as expected. Does not correctly sort scripts by inheritance. Breakpoint often caught in the if (A == B) conditional, which the comment states should not be happening.

**Steps to reproduce:**
Call the reload_all_scripts() method on GDScriptLanguage singleton in a project with a variety of interlinking script dependencies. Since this is not currently used by any currently existing engine functionality, it must be called manually in C++.

**Link to minimal example project:**

**Comment by MillionOstrich** [comment]
I think the issue here is that transitivity does not hold GDScriptDepSort which I believe is necessary for sorting.

**Comment by SaracenOne** [comment]
Hmm...sounds like you're one the right track. I've honestly not gone super deep into the nitty gritty details myself since the whole sorting system is quite tricky to get head around.

**Comment by Calinou** [comment]
@SaracenOne Can you still reproduce this in Godot 3.2.1 or the `master` branch?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
