### ISSUE TITLE
Mouse click selection is broken for 'half resolution' viewport option

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13364]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
d992eb1b25e3612293d6c72cd462a99cd5a0e4a3

**Issue description:**
It's impossible to select proper object when 'half resolution' rendering option is checked in viewport settings. Usually some other object get selected. Selection code probably is not aware of the fact that viewport is rendered with half of the normal resolution.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by qarmin** [comment]
Still happens with 3.2.dev.custom_build. 6d6d43714
