### ISSUE TITLE
100% GPU load when turning on "Auto Exposure"

### ISSUE THREAD

**Issue by Soarex16** [godotengine/godot#13378]
Windows 10 Fall Creators update
Godot daily build from 28.11.2017
GPU: nVidia GEForce gtx1050ti

Issue description:
If you include the "auto exposure" option in the "world environment", then the use of the graphics processor dramatically increases to 100%

Steps to reproduce:
1. Launch engine
2. Select scene (attached to issue)
3. Set in world environment "auto exposure" to true
4. See in task manager GPU load

There is nothing in the logs to indicate an error.

Link to the project: https://drive.google.com/file/d/1rXu4nqA3XvCinFJbo7dAxfD1Bg69iCvb/view?usp=sharing

**Comment by reduz** [comment]
This is perfectly expected. It shouldnt reach 100% but it will be pretty
high because the window needs to refreshed in every frame.
I mean, you see the spinner spinning, so CPU/GPU is going to be used..

**Comment by qarmin** [comment]
In GLES 2 and Intel HD 4600 I don't see a problem, editor works same with this option on and off.

https://streamable.com/7h1hy

**Comment by KoBeWi** [comment]
Tested with GTX 1060
On GLES3, GPU usage jumps by ~30%
On Vulkan, it jumps by ~3%

That's far from 100%, so closing as per reduz's comment.
