### ISSUE TITLE
`get_rpc_sender_id()` missing in an exported project? 

### ISSUE THREAD

**Issue by dawkot** [godotengine/godot#13377]
Version: alpha 2
Os: Windows 10

> DETECTED MONITORS: 1
> Activated GL 3.3 contextERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
>    At: core\project_settings.cpp:841
> ERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
>    At: core\project_settings.cpp:841
> OpenGL ES 3.0 Renderer: GeForce GTX 770/PCIe/SSE2
> WARNING: not found: rendering/quality/anisotropic_filter_level
> WARNING: not found: rendering/quality/anisotropic_filter_level
> GLES3: max ubo light: 409
> GLES3: max ubo reflections: 455, ubo size: 144
> WARNING: not found: locale/translation_remaps
> ERROR: RasterizerSceneGLES3::environment_set_tonemap: Condition ' !env ' is true.
>    At: drivers\gles3\rasterizer_scene_gles3.cpp:914
> ERROR: RasterizerSceneGLES3::environment_set_adjustment: Condition ' !env ' is true.
>    At: drivers\gles3\rasterizer_scene_gles3.cpp:929
> ERROR: ImageLoader::load_image: Condition ' p_image.is_null() ' is true. returned: ERR_INVALID_PARAMETER
>    At: core\io\image_loader.cpp:47
> UDP Connection listening on port 12345

> SCRIPT ERROR: move: Invalid call. Nonexistent function 'get_rpc_sender_id' in base 'SceneTree'.
>           At: res://NetworkedPlayer.gd:12

There is no such error when testing within the editor.

**Comment by Krakean** [comment]
@dawkot can you share your NetworkedPlayer.gd?

**Comment by dawkot** [comment]
> can you share your NetworkedPlayer.gd?
There's no need, because there's only one relevant line: `print(str(get_tree().get_rpc_sender_id()))`
> Can you try latest master build?
I did now and it works. Sorry, should've checked earlier.
