### ISSUE TITLE
Tooltips for the Import dock

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#13370]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 beta

**Issue description:**
The import dock could have tooltips for the options with descriptions, to help the user understand what they do. Currently it only shows the internal name. This should also be exposed to custom import plugins.

**Comment by sonic2kk** [comment]
Was this fixed by the [commit](https://github.com/godotengine/godot/commit/c69de2ba46463adeadf90f38660d6b6e034d7e0b) referenced in #11186?

**Comment by akien-mga** [comment]
No, the Import dock does have tooltips as it uses the same Inspector widget, but the import options are not exposed to the documentation and therefore there's no content to put in the tooltip yet.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2041, as feature proposals are now tracked on the Godot proposals repository.
