### ISSUE TITLE
Sound missing in Android export

### ISSUE THREAD

**Issue by nylnook** [godotengine/godot#13373]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fairphone 2 with Fairphone Open 17.11.2, Godot 3 Alpha 2 compiled yesterday 06bf5e71f6ec426ff93bcf4fb26fe48841f5d212

**Issue description:**
I tried to export my current projects to Android, it worked, but there is no sound at all.
This is working in Godot and in the HTML5 WebAssembly export

You can download and export my project here: https://github.com/nylnook/turbo-argument

Here is also a minimal example project with a sound from Minilens :
[test-sound.zip](https://github.com/godotengine/godot/files/1510811/test-sound.zip)

Thanks for your work !

**Comment by reduz** [comment]
@marcelofg55 think you could give it a check?

**Comment by marcelofg55** [comment]
@reduz sure, I'll check it out later

**Comment by marcelofg55** [comment]
I've just tested the minimal example project with latest master and I do have sound, I've tested with a Moto G with Android 5.1. 
Is there any info/error on the console log?

**Comment by nylnook** [comment]
I'm sorry, you are right ! 
This is now also working for me with the test sound project and my project.
(by the way, I don't know where to see the debug log on Android... )

I suppose this was buggy with Alpha 2 template, but it's working with Beta one. I don't know which commit fixed it....
Thanks for your work again.
