### ISSUE TITLE
Copy/paste nodes outside the engine

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#13380]
Related to the ability of cut&paste nodes #13309 and #7605 request.

The possibility to copy and paste nodes outside the engine (from Godot scene tree to a textfield, from a textfield to Godot scene tree), this can be used on tutorials, help, sharing structures, no more screenshots or full project/scene files for simple needs.

Something to keep in mind, this won't be able to copy external resources.

Example:

In the scene:

```
Node2D
|-KinematicBody2D
|       |-Sprite
|       |-CollisionShape2D (circle)
```

```
[gd_scene load_steps=3 format=1]

[ext_resource path="res://icon.png" type="Texture" id=1]

[sub_resource type="CircleShape2D" id=1]

custom_solver_bias = 0.0
radius = 10.0

[node name="Node2D" type="Node2D"]

[node name="KinematicBody2D" type="KinematicBody2D" parent="."]

input/pickable = false
shapes/0/shape = SubResource( 1 )
shapes/0/transform = Matrix32( 1, 0, 0, 1, 0, 0 )
shapes/0/trigger = false
collision/layers = 1
collision/mask = 1
collision/margin = 0.08

[node name="Sprite" type="Sprite" parent="KinematicBody2D"]

texture = ExtResource( 1 )

[node name="CollisionShape2D" type="CollisionShape2D" parent="KinematicBody2D"]

shape = SubResource( 1 )
trigger = false
_update_shape_index = 0
```

If I want the KinematicBody2D branch and paste somewhere (text field or godot project) to get :
```
[sub_resource type="CircleShape2D" id=1]

custom_solver_bias = 0.0
radius = 10.0

[node name="KinematicBody2D" type="KinematicBody2D" parent="."]

input/pickable = false
shapes/0/shape = SubResource( 1 )
shapes/0/transform = Matrix32( 1, 0, 0, 1, 0, 0 )
shapes/0/trigger = false
collision/layers = 1
collision/mask = 1
collision/margin = 0.08

[node name="Sprite" type="Sprite" parent="KinematicBody2D"]

[node name="CollisionShape2D" type="CollisionShape2D" parent="KinematicBody2D"]

shape = SubResource( 1 )
trigger = false
_update_shape_index = 0

```
_(or some more compressed format)_ That is recognized for paste into Godot too.
This may need a new resource type for the scene branch. 

ps: also related in some way to #8046 (can share the copied-resource type, depending on how gets implemented).

Ping @Krakean

**Comment by eon-s** [comment]
Missed this issue when elaborating this...
Related #3720.

**Comment by Zylann** [comment]
So that means copying nodes from one instance of Godot is not going to work if you paste into another instance of Godot? I like the use case though

**Comment by KoBeWi** [comment]
This issue has the same problem as in https://github.com/godotengine/godot/issues/7605#issuecomment-526650207.

**Comment by akien-mga** [comment]
Yes, I would close for the same motive as https://github.com/godotengine/godot/issues/7605#issuecomment-526678519

If this is really wanted, I would suggest that it's implemented not as a copy/paste, but as a kind of node/scene export:

> But in this case I'd implement this as a custom "Copy scene/branch outside project" tool and not a copy/paste shared clipboard.

**Comment by akien-mga** [comment]
> If this is really wanted, I would suggest that it's implemented not as a copy/paste, but as a kind of node/scene export:

BTW, this could totally be done with a plugin.
