### ISSUE TITLE
Lose setting items in editor settings after reset

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#13389]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10,  compiled with edde719

**Issue description:**

Setting items missing after reset the value button is pressed.

![scenetree2](https://user-images.githubusercontent.com/6964556/33360593-5471cbaa-d50f-11e7-9a62-5a346c06e22e.gif)

**Steps to reproduce:**
1. Open editor setting dialog
2. Rest any value and watch it disappear

**Comment by akien-mga** [comment]
CC @djrm.
