### ISSUE TITLE
"Can't open" alert for removed resource

### ISSUE THREAD

**Issue by gad-o** [godotengine/godot#13396]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Debian 9, master

**Issue description:**
I have a resource that i've removed, i don't know what happned but Godot says "Can't open xxxx.tscn" always when i try open project.

Only think i can do click "I see". There should be some options like "Yes, i know, remove that file from project" or "Let me help you find that file" etc...

Edit: File is run/main_scene="res://xxxx.tscn" in project.godot

**Comment by Zireael07** [comment]
Change the main scene in your project settings, does that get rid of the message?

**Comment by gad-o** [comment]
I removed the line from project.godot for get rid of the message. But i think problem is how to handle that when resource finding ends with unsuccess.

**Comment by Calinou** [comment]
@gad-o Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by KoBeWi** [comment]
This is still happening in ec1bf96

**Comment by natanbcpc** [comment]
Has this been fixed already? I can't reproduce it on master branch.

**Comment by Aa20475** [comment]
I can work on this issue. Can someone give me a starting point?

**Comment by zak-grumbles** [comment]
Wanted to check in on this. Tried reproducing in master ([f74491f](https://github.com/godotengine/godot/commit/f74491fdee9bc2d68668137fbacd8f3a7e7e8df7)) and haven't had any luck. Tried renaming, moving, and straight up deleting a resource but did not see the alert appear.

**Comment by KoBeWi** [comment]
Seems like it was resolved. There error no longer appears and there is a special dialog when you try to run the project:
![image](https://user-images.githubusercontent.com/2223172/192115149-748a45cf-299c-4ace-a57d-7e3eb65e6939.png)
