### ISSUE TITLE
Implement "Exclude Parent Body" option for 3D RayCast

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#13399]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Current master branch (9725f33).

**Issue description:**
`RayCast2D` has a new "Exclude Parent Body" option which was implemented in fc70824f, but there's no equivalent for 3D `RayCast`. It should likely be added for consistency.

See also #13392 which changed the original implementation a bit.

**Comment by VinegarLove** [comment]
I've implemented the same code using the 3D equivalent objects.
I'll do some testing and then submit a PR.

**Comment by akien-mga** [comment]
Fixed by #13408.
