### ISSUE TITLE
Add keyframe button doesn't respond correctly to mouse clicks

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#13398]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64bits
Godot 2.1.4 and Godot 3.0-alpha2

Steps:
 - Add a new animation track. 
 - Click on the [+] button to add a keyframe. 
Expected:
 - A new keyframe is added to the track
Actual:
 - A new keyframe is added to the track only if clicking on the right half of the [+] button. 

**Link to minimal example project:**
I've attached a small video showing the issue. I click on the button, move the pointer one or two pixels two the right and try again, until it starts working.
[2017-11-29 10-51-25.zip](https://github.com/godotengine/godot/files/1514022/2017-11-29.10-51-25.zip)

**Comment by Krakean** [comment]
@noidexe Works fine in my case.
Try to test in latest master (here you can get binary - http://godot3builds.digitecnology.com/)

**Comment by noidexe** [comment]
@Krakean I've tested it with the last build from digitechnology and managed to reproduce the issue. I've also tested it on different dpi settings. 
What happens is that you need to click on top of the + sign for the button to work. I'll it slightly lighten when the mouse hotspot is in the right place.
Notice that this doesn't happen with the continuous/distcrete, linear/cubic, and clamp/wrap buttons. In those three you can click anywhere on the button as is usual with the rest of the UI

**Comment by poke1024** [comment]
Tried to reproduce this on macOS (on a retina display) but didn't manage to.

**Comment by noidexe** [comment]
Can confirm it still happens on 3.0-beta2

**Comment by noidexe** [comment]
Here's a video with better quality. I'm clicking all along the left side of the button and it doesn't work. Only the middle and right thirds of the button detect input. You can also see the + symbol light up except when the mouse is on the left third of the button.
[2017-12-22 14-32-02.zip](https://github.com/godotengine/godot/files/1583118/2017-12-22.14-32-02.zip)

**Comment by KoBeWi** [comment]
This button no longer exists after the AnimationPlayer rework in 3.1
