### ISSUE TITLE
Crash/Messed up model when importing 3D scene

### ISSUE THREAD

**Issue by CruelThorn** [godotengine/godot#13402]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OS: Windows10 Pro, 64-bit
Godot v2.1.4

**Issue description:**
When trying to import .dae 3d scene, 64 bit Godot crashes. The 32 bit version, however successfully imports the scene, though it is all messed up - the armature is completely broken. If there are animations, they are included, but as much as I could see they are broken, too. The scenes are exported using the Better Collada, although the result is the same with the default exporter

Example scene(similar result with absolutely every scene containing armatures and animation):
http://prntscr.com/hgwbbm

This is the exported result in 32-bit version(completely new project started):
http://prntscr.com/hgw8rs
http://prntscr.com/hgwb1f

P.S. Models(scenes which do not include armatures) are imported correctly in both 32 and 64 bit versions

Please, ask any other information you think is necessary about the problem.

**Comment by akien-mga** [comment]
Sorry for the late answer. Do you still reproduce this issue in current Godot releases? (3.0.6 and 3.1-alpha1)

**Comment by qarmin** [comment]
Can you  provide minimal project?

**Comment by qarmin** [comment]
Closing since there is no response from author since 3 years, and the latest tested version of Godot was 2.1
