### ISSUE TITLE
Xcode 9.1 compiled error: "ordered comparison between pointer and zero"

### ISSUE THREAD

**Issue by KenHuang0917** [godotengine/godot#13403]
Operating system or device - Godot version:
macOS High Sierra 10.13.1, Godot 2.1 stable, Xcode 9.1, iOS 11

Issue description (what happened, and what was expected):
After updated Xcode to version 9.1, I recompiled a Godot project which worked just fine with Xcode 8 and found this compile error:

## scene/gui/tree.cpp:1305:27:{1305:9-1305:26}{1305:29-1305:30}: error: ordered comparison between pointer and zero ('TreeItem *' and 'int') [2]
                                if (c->get_children() > 0)
                                     ~~~~~~~~~~~~~~~~~ ^ ~

Since the compilation process aborted for error, there could be more errors not found.


Steps to reproduce:
Compile Godot with: "Scons platform=iphone tools=no bits=64 target=release ios_sim=yes" for Simulator and with "Scons platform=iphone tools=no bits=64 target=release" for iDevice. 

Thanks for helping!

**Comment by bruvzg** [comment]
fixed in https://github.com/godotengine/godot/commit/31f929caa2bc8422c0a6bb50f81500e1f4db101b (year ago), current stable version is 2.1.4, update your source code
