### ISSUE TITLE
[Suggestion] Ability to chain methods?

### ISSUE THREAD

**Issue by RoryMcMaster** [godotengine/godot#13404]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0

**Issue description:**
Example:
```
	lineedit.set_cursor_position(99999)
	lineedit.grab_focus()
```

Would be cool/nice to be able to do:
```
lineedit.set_cursor_position(99999).grab_focus()
```
Or is this already planned? (Searched but couldn't find anything, sorry if double post)

**Comment by NathanWarden** [comment]
I'm guessing this won't happen for the following reason. What should the following return, the name of the node you're in, or the name of the node you just grabbed?

```
var name = self.get_node("Child").get_name()
```

How it currently works it will give you the name of the "Child" node, but what you're proposing would be confusing, no?

**Comment by reduz** [comment]
not planned and not gonna happen

**Comment by RoryMcMaster** [comment]
Okay nps, ty for quick response :D
