### ISSUE TITLE
Code folding icons are hard to see with light background text themes

### ISSUE THREAD

**Issue by AWKgamedev** [godotengine/godot#13413]
**Issue description:**
Using a combination of dark editor theme with light text theme makes the code folding icons very hard to see.
The problem is that the code folding icon colors are based on the "Icon and Font Color" option in the editor theme section which is not related to the text editor itself, I think it would be better if the code folding colors were editable in the Highlighting section.

![godot engine - harmon_i_c - game tscn](https://user-images.githubusercontent.com/10258315/33440635-a4632618-d5d7-11e7-8ca7-571f7979b387.png)

**Steps to reproduce:**
Set Icons and Font Color to Light and text editor Background Color to something light.

**Comment by Zylann** [comment]
Do folding icons use one of the code editor theme colors?

**Comment by djrm** [comment]
i think they need to be tinted in the script editor, like the 'tab' icon, so this has to be automatic, taking the theme font color in consideration and reducing the alpha or something.
