### ISSUE TITLE
White ellipse while using light shader

### ISSUE THREAD

**Issue by FlamyAT** [godotengine/godot#13416]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 Home 64-bit
Godot 3.0 Beta 1
GeForce GTX 950M
Version: 22.21.13.8189 / GeForce Game Ready Driver Version: 381.89

**Issue description:**
I tried creating a light shader. With this sample code 
`void light(){
	float dt = dot(LIGHT, NORMAL);
	DIFFUSE_LIGHT = vec3(1, 1, 1);
}`,
instead of my sphere being white it got a white "outline". (It's a white ellipse with the height of the window and the width of the window.)

**Link to minimal example project:**
[Light Shader.zip](https://github.com/godotengine/godot/files/1519083/Light.Shader.zip)

**Comment by akien-mga** [comment]
Did it get fixed?

**Comment by FlamyAT** [comment]
Yes, it did get fixed!
