### ISSUE TITLE
Physics 2d shape query

### ISSUE THREAD

**Issue by fy0** [godotengine/godot#1341]
I want to get some shape classes like RayCast2d.
And some simple API  like:
* RayQuery
* SegmentQuery
* CircleQuery
* ShapeQuety

I found something in Physics2DDirectSpaceState.
I had a hard time trying to use it, but i can't understand how it works until now.
And I think it should be easier to use.

**Comment by reduz** [comment]
Just use Area2d and add a child collision shape the way you wanr

**Comment by fy0** [comment]
Hi, @reduz
Area2d seems not work with StaticBody. If I want control a monster avoid walls, it not works well.
And there is no layer mask, no object exclude.

For example,
I cast a spell, then the spell meet an enemy, BOOOM!!!
Now I need create an Area2d, or my spell object have an Area2d.
Then set_enable_monitoring  (to avoid performance lost), get_overlapping_bodies(), check layers ...
So I think an Area2d class without enter_body/exit_body, and just with some queries API is better.

**Comment by akien-mga** [comment]
As mentioned by @reduz, I think using Area2Ds is exactly what you need for the above mentioned scenarios. If there are cases where Area2D is not sufficient or gives a very bad performance, the API could of course be improved to better fit such cases.
