### ISSUE TITLE
Revert button doesn't appear in the editor after overriding any property value.

### ISSUE THREAD

**Issue by jjjuande** [godotengine/godot#13415]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64 bits
Godot 3.0 Beta build 1

**Issue description:**
I was following the Step by step docs on Instancing, but when in "Editing Instances":
http://docs.godotengine.org/en/latest/learning/step_by_step/instancing.html#editing-instances

I found this wierd behavior: After overriding any property value of a node on an instanced scene, the revert button doesn't appear. You need to select another node and then back in order to refresh/redraw the property and the refresh button to appear.

Here's a gif:

![bug](https://user-images.githubusercontent.com/168978/33448458-66b22c72-d606-11e7-814b-160e70dc1b36.gif)

I suppose the right behavior must be similar to when editing properties on the Project Settings:

![bug](https://user-images.githubusercontent.com/168978/33449268-8e40b4f0-d608-11e7-9711-5b2e4c3e753c.gif)

**Steps to reproduce:**
Follow this step by step guide:
http://docs.godotengine.org/en/latest/learning/step_by_step/instancing.html#editing-instances
Until the section Editing Instances

**Link to minimal example project:**
[instancing.zip](https://github.com/godotengine/godot/files/1519078/instancing.zip)

**Comment by reduz** [comment]
In this case, when a property is edited, tree emits signal and this callback is received:

https://github.com/godotengine/godot/blob/master/editor/property_editor.cpp#L3657

it may be possible that the code to check if the value is overriden is not being called. There is a complicated chain of property being changed set to be refreshed later that may not be working.

**Comment by jjjuande** [comment]
From what I could see, there's just 5 references to the "ReloadSmall" icon:

- Three at the end of the update_tree() that makes all the checks:

1. If the property comes from an instanced node and it's different than the original on the instanced node.
```C#
bool mbi = _might_be_in_instance();
if (mbi) {

	Variant vorig;
	Dictionary d = item->get_metadata(0);
	int usage = d.has("usage") ? int(int(d["usage"]) & (PROPERTY_USAGE_STORE_IF_NONONE | PROPERTY_USAGE_STORE_IF_NONZERO)) : 0;
	if (_get_instanced_node_original_property(p.name, vorig) || usage) {
		Variant v = obj->get(p.name);

		if (_is_property_different(v, vorig, usage)) {
			item->add_button(1, get_icon("ReloadSmall", "EditorIcons"), 3);
			has_reload = true;
		}
	}
}
```

2. If the property can revert.
```C#
if (obj->call("property_can_revert", p.name).operator bool()) {

	item->add_button(1, get_icon("ReloadSmall", "EditorIcons"), 3);
	has_reload = true;
}
```

3. If the property has a default value specified on a script.
```C#
if (!has_reload && !obj->get_script().is_null()) {
	Ref<Script> scr = obj->get_script();
	Variant orig_value;
	if (scr->get_property_default_value(p.name, orig_value)) {
		if (orig_value != obj->get(p.name)) {
			item->add_button(1, get_icon("ReloadSmall", "EditorIcons"), 3);
			has_reload = true;
		}
	}
}
```

- And two in the method _check_reload_status() being called after editing any property.

1. If the property can revert. (I saw that this works for example with the Settings properties)
```C#
if (obj->call("property_can_revert", p_name).operator bool()) {
	has_reload = true;
}
```

2. If the property has a default value specified on a script.
```C#
if (!has_reload && !obj->get_script().is_null()) {
	Ref<Script> scr = obj->get_script();
	Variant orig_value;
	if (scr->get_property_default_value(p_name, orig_value)) {
		if (orig_value != obj->get(p_name)) {
			has_reload = true;
		}
	}
}
```

And as I don't think that refreshing the entire tree for a single edited property was a good idea, I edited (Take a look at this pull request: https://github.com/godotengine/godot/pull/13958) the _check_reload_status method to add the checking code (missing, I think, because the update_tree method does three checks, and the _check_reload_status only two) before updating its reload buttons and the issue is gone.

I'll be following this issue to know the correct fix when someone that is familiarized with Godot source code fixes it.

Keep up the good work!
