### ISSUE TITLE
Autotile editor- cant delete navigation and occlusion polygons

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#13411]
In autotile editor- The delete button works on collision polygons, but not on navigation and occlusion polygons 

@MarianoGnu

**Comment by MarianoGnu** [comment]
hum, last time i checked it did work, will try tonight

**Comment by blurymind** [comment]
I made a little gif:
![deletebug](https://user-images.githubusercontent.com/6495061/33430392-55b70a7a-d5c8-11e7-9794-a9ba6e709967.gif)
