### ISSUE TITLE
"Show in file manager"

### ISSUE THREAD

**Issue by dploeger** [godotengine/godot#13422]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS 10.13.1, Godot 3.0.beta.build1

**Issue description:**
Selecting an item in the file panel and select "Show in file manager" doesn't actually do anything. Expected was, that the system file manager (Finder in my case) should open.

**Steps to reproduce:**
* Open any Godot project
* Select an item in the file panel
* right click it 
* select "Show in file manager"

➡️  nothing happens

**Comment by ni-code** [comment]
On linux it only works if I have a file manager window opened, (for example natilus opened in a random folder). If I don't have any instance of the file manager opened, it dosen't work.

**Comment by NathanWarden** [comment]
@ni-code If you try it twice does it open the second time? If yes, then this is a Linux or Nautilus bug, not a Godot bug as this issue appears in several other programs.

**Comment by mhilbrunner** [comment]
Works on Windows 7. Seems to be OS specific.

**Comment by ni-code** [comment]
@NathanWarden ok. I feel embarrassed now. I swear I had this issue, Gtk update must have fixed it. Sorry for the noise. It is working as intended.

**Comment by Noshyaar** [comment]
Can't reproduce on Antergos x86_64 Cinnamon, nemo 3.6.4

**Comment by Calinou** [comment]
@dploeger Does this work on 2.1.4? If it doesn't, it may have not been implemented for macOS.

**Comment by dploeger** [comment]
@Calinou It does work in 2.1.4

**Comment by bruvzg** [comment]
macOS 10.13.1, master e89309b "Show in file manager" works if project path contains no spaces.

**Comment by dploeger** [comment]
@bruvzg Is e89309b already included in beta.1?

**Comment by bruvzg** [comment]
@dploeger beta is 2ab7a0f64cdad863ab31d2c10e58e98d00ae84e7 (18 commits before)
