### ISSUE TITLE
Collapse / expand all has a very annoying behavior

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#13421]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master 9725f33ac606ed4b26573015bcfdb86ed6741323

**Issue description:**

The collapse / expand all function introduced by #13233 has  a very annoying behavior,
for example, i like to collapse the features i dont need and leave the other ones open, but after enabling a paramenter in lets say material properties, everything goes exapanded. it also happens when opening a subresource and returning to main view. this behavior is very distracting and annoying. i also noticed that pressing collapse all keeps my previously exapanded elements open and close the rest, so this might be a bug, but if this is the intended behavior it should definetely be changed.

cc: @Krakean 

**Steps to reproduce:**
edit a material, colapse some properties, enable a property, see how everything gets expanded

**Link to minimal example project:**

**Comment by Krakean** [comment]
@djrm Hm, strange. Will take a look at morning. Can you also please record a video for me with bugged behavior?
Also, have you enabled "expand all properties" in editor preferences?

**Comment by djrm** [comment]
@Krakean i tried with both expand all properties enabled and disabled and it still happens, i tried to make a gif but the action is too fast and is barely visible, i would suggest you to try the reproduction steps, it is really easy to reproduce.

but here it is anyway, the scroll that happens is because the expansion of the rest of the elements.
![peek 2017-11-30 14-46](https://user-images.githubusercontent.com/1103897/33456590-7359d770-d5e5-11e7-89f5-1872ded74e97.gif)

**Comment by djrm** [comment]
after restarting godot i noticed that this only happens when "expand all properties" is enabled.

**Comment by Krakean** [comment]
@djrm Daniel, please apply these files on latest master: https://nofile.io/f/8MP4vBV56fp/editor.zip, compile and test whether it became works better and your issues are solved. If its ok, then ill make PR.

**Comment by djrm** [comment]
@Krakean ok will give it a try.

**Comment by Krakean** [comment]
@djrm Well? :)

**Comment by reduz** [comment]
previous implementation was kind of broken, so doing some fixes myself
