### ISSUE TITLE
[custom cursor hotspot] x not properly used/loaded

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#13425]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux debian buster, Godot Engine 2.1.4, AMD Radeon R9 290

**Issue description:**
Using the Project Settings to set up a Custom Mouse Cursor Hotspot does not work properly.

![selection_608](https://user-images.githubusercontent.com/6616005/33457416-6c47dada-d5f0-11e7-9641-2eda9bbeb84f.png)

And then check the result, only _y_ is used, but not the _x_.
![mouse-decal](https://user-images.githubusercontent.com/6616005/33457345-30fbcee6-d5f0-11e7-81a9-33d35ce97042.gif)

And if you close/open the project via Godot, then the x value just disappear:
![selection_607](https://user-images.githubusercontent.com/6616005/33457384-523a0e1a-d5f0-11e7-8a62-0c57eeb38b05.png)

**Steps to reproduce:**
[A git repository to reproduce](https://github.com/xsellier/godot-hotspot-not-saved)

**Comment by reduz** [comment]
not milestone 3.0, this is a 2.1 issue. 3.0 does not even support this :P

**Comment by xsellier** [comment]
@reduz I will port this Merge Request once it has been validated + merged onto 2.1 :)
