### ISSUE TITLE
External script editor gets focused after changing scenes or selecting any C# script in the Inspector

### ISSUE THREAD

**Issue by Kinerius** [godotengine/godot#13429]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot v3.0.beta.build1.mono
Windows 10
Single UltraWide Monitor 2560x1080.
GTX 780, 16 gb ram.

**Issue description:**
Visual studio code is sent to the front of the screen everytime any script.cs is on the Inspector tab

**Steps to reproduce:**
- Create new Project
- Create Any Node
- Attach new C# script ( Visual Studio Code opens here, if not, select visual studio code as current Editor )
- Go back to godot editor
- Press inspector arrows to select the node, then select the script.
- At this moment Visual Studio Code should be on your screen ( not sure if this will work with multiple monitors ) 

If this is working as intended, its somewhat annoying, making this toggleable in the settings would be very much appreciated.

**Comment by akien-mga** [comment]
I think there were fixes for this recently, can you still reproduce it in Godot 3.0 RC1?

**Comment by neikeq** [comment]
@akien-mga This looks like a different issue. I think it's somewhat related to #10940

**Comment by evan13579b** [comment]
I don't even have to select the script for this to happen to me.

Everytime I click the tab to switch to a different scene, it will start a new instance of monodevelop if the root node of that scene has a c# script.

(I'm using Linux with Godot 3.0.2 64 bit mono compatible version on debian stretch)

**Comment by akien-mga** [comment]
Is this still relevant in the current master branch?

**Comment by somnivore** [comment]
I believe this happens because of `Editor Settings -> Text Editor -> Files -> Open Dominant Script On Scene Change`

Unchecking that should prevent external editors from opening automatically.

**Comment by neikeq** [comment]
Honestly, I think what we need is some way to differentiate between an editor request made explicitly by the user and other editor requests. Only the former should execute an external editor, otherwise it's annoying. I may give this a try after 3.1.

**Comment by nuke-makes-games** [comment]
Somnivore is right, **Open Dominant Script On Scene Change** does this.

I am on current master branch and I find it to be bothersome and disruptive to the workflow. This option should default to off i think.

**Comment by Calinou** [comment]
Should we make **Editor Settings -> Text Editor -> Files -> Open Dominant Script On Scene Change** a no-op when using an external script editor? I'm not sure about disabling it by default when using the built-in script editor.

**Comment by b-hayes** [comment]
Super annoying. Def should be disabled by default.

**Comment by Calinou** [comment]
@b-hayes This will be fixed in 3.2.3 thanks to https://github.com/godotengine/godot/pull/40735 (which is already available in 3.2.3rc4).
