### ISSUE TITLE
No extension method "normalized" on Vector3 with C#

### ISSUE THREAD

**Issue by moisesjpelaez** [godotengine/godot#13430]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0 beta 1 with AMD R5

**Issue description:**

Tried to normalize a Vector3 using .normalize() method with C#, it used to work in alpha 2 and there's a method reference in the class but now I get the following error:
![godotsharp](https://user-images.githubusercontent.com/24682046/33462078-e36ecf72-d60b-11e7-9d27-7dc920d32752.png)

**Steps to reproduce:**
Create a variable of type Vector3 and normalize it.

**Link to minimal example project:**

[GodotSharpTest.zip](https://github.com/godotengine/godot/files/1519958/GodotSharpTest.zip)

**Comment by Zylann** [comment]
isn't it `Normalized` with an uppercase N?

**Comment by Hinsbart** [comment]
Yes, the methods in core types use `PascalCase` now.
