### ISSUE TITLE
V-SYNC doesn´t work?

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#13447]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot3 beta1, win 7 32 bit

**Issue description:**

I open a project and activate V-Sync, I execute the project, FPS goes to 1000 and more, console shows that V-SYNC is activated.

**Steps to reproduce:**
Open attached project and F5/F6

**Link to minimal example project:**

[godot3-VSYNCnotworking.zip](https://github.com/godotengine/godot/files/1521410/godot3-VSYNCnotworking.zip)

**Comment by Calinou** [comment]
What's your graphics card, and did you make sure V-Sync isn't forced off in your graphics driver options?

(I don't have access to NVIDIA hardware right now, only Intel which has a tendency to enforce V-Sync everywhere, I will test this when I get home.)

**Comment by Ranoller** [comment]
I test this in a intel integrated card, but i have 2 computers more in other places with dedicated card, i will test...

**Comment by Krakean** [comment]
@Ranoller VSync doesn't work for you in editor or in game? If I remember correctly, vsync is supported only in game, not in editor.

**Comment by Ranoller** [comment]
There is a project attached at the issue. VSYNC report in game  that is conected but Engine singleton shows that fps are max allowed by scene (sometimes it works, every x executions)... Code is in main.gd. Someone have same issue?...

**Comment by Calinou** [comment]
On Windows 10 and a GeForce GTX 1080, after telling the NVIDIA driver to use the application setting for V-Sync (which is the default option), I can't reproduce this bug. However, if you force-disable V-Sync, Godot will obey the driver's preference (which is expected).

**Comment by Ranoller** [comment]
I do more test in my GeForce GTX 660. VSYNC works if you change that in runtime. Thing that is not working is the editor hint, changing that doesn´t affect game. In my second computer allways is VSYNCed at start, no matters if editor property is toggled, but changing with OS.set_vsync() works... This not happend in 2.1. so probably is a bug.

**Comment by Zephilinox** [comment]
I can confirm, GTX 660 here as well on windows 7 running the godot beta, set to use "3D application setting" for V-sync in the control panel and with vsync turned off in the project settings. vsync remains turned on unless I turn it off via code.

**Comment by MrJustreborn** [comment]
On Manjaro Linux, GTX550Ti:
With disabled "Sync to VBlank" in the global settings, it dosen't sync

**Comment by reduz** [comment]
Keep in mind that, if using a compositor, it may not be possible to turn off vsync (compositor forces it).

**Comment by reduz** [comment]
This probably needs more testing, so adding tag

**Comment by mortem-malum** [comment]
Vsync project setting nor setting in script would turn on vsync for me. Radion r390 vsync set to specified by application windows 10 x64.
