### ISSUE TITLE
Build System: mingw toolchain in windows

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#1344]
Windows comnad lines limited to 8k so the hugea$$ ar command at the end needs to use the ar @file semantics in the scons scripts when platform=windows and mingw toolchain was detected.

Similar for any other similarly large toolchain command lines.

**Comment by UsernameIsAReservedWord** [comment]
i was working on a fix for this issue.
if you want to test it, you can replace the `platform/windows/detect.py` script with this one :
https://github.com/UsernameIsAReservedWord/godot/blob/master/platform/windows/detect.py

if you try it, please tell me if it works on your toolchain.

**Comment by gau-veldt** [comment]
It got past the hugea$$ ar command but now I'm have a different problem of it not recognizing my directx sdk ("dsound.h": No such file or directory.)

**Comment by UsernameIsAReservedWord** [comment]
about all the missing directx headers, you can just copy them into your `C:\MinGW\include` from here :
https://code.google.com/p/mingw-lib/source/browse/trunk/working/avcodec_to_widget_5/directx_include/

**Comment by reduz** [comment]
if it helps, the missing directx headers were somehow added into newer
versions of mingw, and definitely mingw-w64

**Comment by gau-veldt** [comment]
now it's getting somewhere... ar's are working and no complaints about directx headers

**Comment by gau-veldt** [comment]
but linking is the real trial by fire here and it's not done yet only got 8 cores to slam compiles onto :P

**Comment by reduz** [comment]
feel free to send me a PR if it works!

**Comment by UsernameIsAReservedWord** [comment]
@reduz : here you have it #1432

**Comment by eska014** [comment]
Fixed by PR mentioned above.
