### ISSUE TITLE
Request: Remove Hardcoding For Visual Server, Rasterizer, and Lights

### ISSUE THREAD

**Issue by moonshineTheleocat** [godotengine/godot#13455]
This is a simple request for Godot 3.1 when it enters development. A few major problems I have noticed in Godot's Modulerization is that the Visual Server, Raster, and Lighting back end have been hardcoded making it impossible to add to with Modules.

Currently, it does not appear that you have the ability to add custom shaders and materials to lights. The reason this is necessary, is that it opens up more possible graphical features, and performance tricks. For instance, making a custom lighting node based on the Omnilight for IES Lights. Adding geometrical area lights. Making custom nodes that takes a prebaked depth textures or masks to cheaply project shadows that would appear as if the light was inside an object or had something extremely close to the bulb. And correctly adding interactions for GI probes.

These last two are can be a patched pretty simply, though it may or may not look ugly.

The Visual Server can not be replaced. This is noticed with the difference between the Physics Server and the Visual Server. The difference is the Physics server has a manager, in which the project settings uses to select the correct option that is then used in the game. 

Rasterizer is currently hard-coded and should be allowed to be swapped. The way it is hard coded is that each platform directly instantiates the default class in code. This is important if you wish to open Godot up to platforms and Graphics API that it does not currently support.

**Comment by reduz** [comment]
Agree that this should be possible to replace, though the general design wont change. 
The idea in Godot is to have a simple renderer that does the most common tasks instead of a very flexible rendering framework. At much more features can be added.

That said, yeah it would be interesting for anyone to make alternative VisualServer implementations.

**Comment by moonshineTheleocat** [comment]
@reduz I understand the idea, but it is also beneficial to be able to have the power to change how the VisualServer works behind code in the event that game specific optimizations are necessary.

**Comment by DEF7** [comment]
This would lend itself well to ARVR seeing as how the current setup doesn't allow decoupling of pre-setup assets from viewports (i.e. shadowmaps are generated from scratch for each eye/viewport, instead of being generated once and used for both eyes).

**Comment by Anutrix** [comment]
Any updates? Seems highly relevant to 4.0.

**Comment by Calinou** [comment]
This is planned for 4.0 thanks to the Vulkan renderer, see [progress report #1](https://godotengine.org/article/vulkan-progress-report-1):

> One of the main features that will be present in Godot 4.0 is the new `RenderingDevice` abstraction. Up to now, it was impossible to do any internal modifications to how Godot does rendering. This means that if you wanted to run custom low-level rendering code to a texture or buffer, custom post-processing, custom drawing code (other than what Godot shaders allow), custom compute, etc., this was not possible without modifying Godot's rendering backend.
>
> The new `RenderingDevice` API allows to do all of this, or even completely override Godot's rendering code in order to create your own.
>
> …

**Comment by Calinou** [comment]
RenderingDevice is now exposed to scripting, which makes this technically possible.
