### ISSUE TITLE
No render with Mesa when using `invariant gl_Position` (Mesa bug 100316)

### ISSUE THREAD

**Issue by gad-o** [godotengine/godot#13450]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Debian 9, 0243803, Gallium 0.4 on AMD KAVERI (Mesa 13.0.6)

**Issue description:**
No render both viewport in editor and game...

**Steps to reproduce:**
Checkout and build 02438031, render not working.
Return to d81c5004 then render working

**Link to minimal example project:**

**Comment by reduz** [comment]
any kind of error log appreciated, I'm sure there is one

**Comment by gad-o** [comment]
At: drivers/gles3/shader_gles3.cpp:539.
ERROR: get_current_version: Method/Function Failed, returning: __null
   At: drivers/gles3/shader_gles3.cpp:546.
ERROR: bind: Condition ' !version ' is true. returned: false
   At: drivers/gles3/shader_gles3.cpp:122.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: ./drivers/gles3/shader_gles3.h:376.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: ./drivers/gles3/shader_gles3.h:376.

**Comment by gad-o** [comment]
ERROR: _display_error_with_code: SceneShaderGLES3: Program LINK FAILED:
error: declarations for uniform `camera_matrix' have mismatching invariant qualifiers

   At: drivers/gles3/shader_gles3.cpp:167.
ERROR: get_current_version: SceneShaderGLES3: Program LINK FAILED:
error: declarations for uniform `camera_matrix' have mismatching invariant qualifiers

   At: drivers/gles3/shader_gles3.cpp:539.
ERROR: get_current_version: Method/Function Failed, returning: __null
   At: drivers/gles3/shader_gles3.cpp:546.
ERROR: bind: Condition ' !version ' is true. returned: false
   At: drivers/gles3/shader_gles3.cpp:122.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: ./drivers/gles3/shader_gles3.h:376.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: ./drivers/gles3/shader_gles3.h:376.

**Comment by reduz** [comment]
real error is likely way above that, you may want run godot editor manually
by going to the project folder, and doing:

godot -e > dumpfile.txt

and error will most likely appear on top

**Comment by gad-o** [comment]
[output.txt](https://github.com/godotengine/godot/files/1521702/output.txt)

**Comment by reduz** [comment]
This is clearly a Mesa bug. I will workaround it for now, but they need to
fix it..

**Comment by reduz** [comment]
removing the invariant keyword will probably fix this, though it would be
better if it worked

**Comment by gad-o** [comment]
> This is clearly a Mesa bug. I will workaround it for now, but they need to fix it..

> removing the invariant keyword will probably fix this, though it would be better if it worked

I have compiled latest mesa and now its work.
Debian Stretch(Stable) -> Mesa 13.0.6
Debian Buster(Testing) -> Mesa 17.2.5

**Comment by novemberist** [comment]
same issue here on Arch Linux with Mesa 17.2.6

**Comment by gad-o** [comment]
@novemberist and @sketchyfun could you try to delete invariant gl_Positions:
@@ -263,8 +263,6 @@ uniform highp sampler2D skeleton_texture; //texunit:-1
 
 out highp vec4 position_interp;
 
-invariant gl_Position;
-
 void main() {



> This is clearly a Mesa bug. I will workaround it for now, but they need to fix it..
> removing the invariant keyword will probably fix this, though it would be better if it worked

There is a bug report at here :`https://bugs.freedesktop.org/show_bug.cgi?id=100316` related with Mesa

**Comment by mirh** [comment]
This has been fixed in the git going to be released in 19.1.
