### ISSUE TITLE
Debug option to print FPS prints the editor FPS while running a game

### ISSUE THREAD

**Issue by Zephilinox** [godotengine/godot#13452]
On the beta snapshot

![image](https://user-images.githubusercontent.com/2060863/33484611-f10a9d52-d69a-11e7-8c91-f4efd022010c.png)

![image](https://user-images.githubusercontent.com/2060863/33484621-0027c0e4-d69b-11e7-98d0-8709b95d0bd9.png)

Personally I just want to see the games FPS, but I could see making a separate option to print the editor FPS as well without having two identical strings printing to the console.

Interestingly, if you enable the FPS option before the game is running, then while it runs untick it, it will continue to print the games FPS.

**Comment by Krakean** [comment]
@Zephilinox have you tried this one? https://i.imgur.com/ROphFAI.png

**Comment by Zephilinox** [comment]
Oh neat, thanks.

**Comment by Krakean** [comment]
@akien-mga I suppose this ticket can be closed

**Comment by akien-mga** [comment]
No, I still think that it's a bug if the project setting option prints both the game and the editor's FPS in the same output dialog.

**Comment by Krakean** [comment]
@akien-mga what if just to remove "Print Fps" option in editor settings due to its useless (fps monitoring in output window tab, eh...)? And add support to "View FPS" to display fps when in 2D.

**Comment by vnen** [comment]
You can also use the Monitor tab of the Debugger to view the FPS (among other things).

**Comment by icnikerazah** [comment]
I'm so confused
my settings;

> Project Settings > Physics > Common > Fixed Fps = 120
> Project Settings > Debug > Settings > Fps > Force Fps = 120
> Project Settings > Debug > Settings > Stdout > Print Fps = true

Results:
<img width="240" alt="ekran resmi 2018-01-23 17 54 18" src="https://user-images.githubusercontent.com/33985414/35282562-d46cfc58-0066-11e8-8b4f-0a10fcc3eb63.png">

<img width="283" alt="ekran resmi 2018-01-23 17 50 40" src="https://user-images.githubusercontent.com/33985414/35282518-bfab98b0-0066-11e8-92b1-19eaed4e41aa.png">
