### ISSUE TITLE
Project Settings - Uncapitalised text, "Test" properties, and laggy/buggy drag-to-slide

### ISSUE THREAD

**Issue by Zephilinox** [godotengine/godot#13451]
#### Uncapitalised Text
Text which should be capitalised, like GUI, FPS, and 2D, don't seem to be.

![image](https://user-images.githubusercontent.com/2060863/33483836-902bbc44-d697-11e7-9cc0-ec095b7e8dd8.png)
![image](https://user-images.githubusercontent.com/2060863/33483846-9aec083c-d697-11e7-8214-79104b5bf14f.png)
![image](https://user-images.githubusercontent.com/2060863/33483857-a9c93730-d697-11e7-9d11-59a85d39c186.png)

#### Test
Either some kind of debug setting that was left in accidentally, or which wasn't renamed appropriately.
![image](https://user-images.githubusercontent.com/2060863/33483866-beba88c4-d697-11e7-948a-cbcff9c80639.png)

![image](https://user-images.githubusercontent.com/2060863/33483964-3b46f364-d698-11e7-8aa1-63b957659cae.png)

![image](https://user-images.githubusercontent.com/2060863/33484003-6d3763a4-d698-11e7-951e-5fbb2b8067db.png)

#### Dragging to slide values
Kinda hard to see in the gif, but I'm trying to decrease the value (moving my mouse to the left) the entire time, and it feels really unresponsive, in some cases increasing in value?

![slider](https://user-images.githubusercontent.com/2060863/33484289-88ce5554-d699-11e7-9675-9ceb265d70ad.gif)

Trying to do this on some other properties causes the cursor to change
![slider2](https://user-images.githubusercontent.com/2060863/33484520-862cd842-d69a-11e7-9216-fd46e2e23358.gif)

**Comment by Noshyaar** [comment]
>Uncapitalised Text

Those are automatically converted from snake_case for display. Maybe the capitalize function could have some sort of exception of words that shouldn't be capitalized.

>Dragging to slide values

Currently you have to drag it *upward* or *downward*.

**Comment by Zephilinox** [comment]
I figured it was some kind of automatic conversion. It doesn't look particularly pleasing seeing it in snake case.

Ah wow, I figured it would be similar to unity/unreal where you drag left and right, thanks.

**Comment by Anutrix** [comment]
That cursor change and getting stuck issue fix quite a while ago.
Afaik, Test is there to set a locale. Not sure.
Only uncapitalize issue seems to be pending.

**Comment by Anutrix** [comment]
Shouldn't https://github.com/godotengine/godot/commit/162068640b6a2ea6085cd508d0a21a9d51dec5b0 have fixed it?
Though I think it's not fixed though.

**Comment by Calinou** [comment]
@Anutrix To solve this, we could have an editor-only function that's based on `String.capitalize()` with a built-in array of exceptions that should always be written in a specific case ("FPS", "GLES", "glTF", "iOS", …).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1399, as feature proposals are now tracked on the Godot proposals repository.
