### ISSUE TITLE
Godot engine draws behind the title top bar on Windows 10

### ISSUE THREAD

**Issue by adeluiz** [godotengine/godot#13457]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3 beta 1 &  godot stable 2.1 (text is at 100% and the screen resolution is 1920x1080,
 native resolution)

**Issue description:**
When Godot (or a godot game) runs as a windowed app (not full screen),the engine 0 position on the y axis is behind the window title for drawing. So everything that is drawn at the top of the screen is drawn behind the title bar and you can't see it. 
But on the othe hand, if you want to detect a mouse event on the 0 position, you have to be on the line just below the windows bar (as it shoud be). 
Then, there is a mismatch between the cursor event and the drawing (the line 0 drawing is several pixels higher that the lino 0 for touch/mouse events).

I've have capture this on a photo where you can see the cursor highlights a button that is not below the cursor, and with a screen capture where you can see that the godot menu is hidden behind the title bar.
![godotbugw10-0](https://user-images.githubusercontent.com/4427432/33495433-c008502e-d6c6-11e7-89a8-e4826dd55fa7.png)
![godotbugw10-1](https://user-images.githubusercontent.com/4427432/33495434-c02a1966-d6c6-11e7-9b9c-6bc5da5fb2f0.png)

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Noshyaar** [comment]
Duplicate of #8902, are you using Intel GPU?

**Comment by adeluiz** [comment]
Oh, I've search for it but can't found nothing related (my bad). Yes, I'm on a Intel GPU. I'm going to try the workaround  (using last drivers) right now.

**Comment by adeluiz** [comment]
A few drivers intalation and voila: The bug were gone. It was a intel graphic bug as you said. Thanks a lot
