### ISSUE TITLE
More control on Particles randomness

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#13488]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

Only providing one scalar in [0, 1] in random fields, is a bit limitating (for example with particles).

I think random should not be clamped so we can get a random value around ( not clamped) the initial one .
Now we can only have a value between initial and 1 (with random to 1 or even a lesser range with random < 1).

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Noshyaar** [comment]
randf() * N would give a random float from 0 to N

**Comment by Hello445** [comment]
"Not a high priority". Voting to close.

**Comment by matrem** [comment]
I mean something like that (for example on particle  scale) :
https://github.com/matrem/godot/commit/02d0d698b1606246253027432431b02e01a6e4ed
So I can set my scale to X and then configure is random between X-R and X+R (instead of X and 1).

**Comment by Chaosus** [comment]
The randf_range function is fixes this issue ? cc @akien-mga

**Comment by bojidar-bg** [comment]
@Chaosus this issue is about CpuParticles/ParticleMaterial, not the Random class.

**Comment by Chaosus** [comment]
Ah.. right

**Comment by Calinou** [comment]
The `*_random` properties could be changed to add/remove a relative offset with the specified value. For example, if the `*_random` property was set to 1, the old behaviour could be restored by halving the property and setting the `*_random` property to the double of the halved value.

This would break compatibility, so it will have to be done for 4.0.

**Comment by pwab** [comment]
I'll just link here to make it part of the discussion in the GIP:
godotengine/godot-proposals#815

**Comment by akien-mga** [comment]
Superseded by godotengine/godot-proposals#815.
