### ISSUE TITLE
Data dump is unclear

### ISSUE THREAD

**Issue by Spooner** [godotengine/godot#1348]
Dumping data to strings is very bad. It is often not clear at all what type you are printing out.

1) Numbers: "2" and 2 are printed the same (2). This is fine when writing the value directly in print, but not when it is part of a more complex data structure such as an array or dictionary.

2) Dictionaries: Format isn't terrible, but it is completely different than the code to create it for no reason. e.g. {"fish": "frog", "cheese": "pie" } = (fish:frog), (cheese:pie)

3) Arrays: Format isn't terrible, but it is completely different from code, which makes it very ambiguous. e.g. printing 1, [1] and ["1"] all give the same output.

Other examples of ambiguity:
{ "cheese": "pie", "fish": "frog" } =  (cheese:pie), (fish:frog)
[{"fish": "frog"}, {"cheese": "pie" }] =  (cheese:pie), (fish:frog)

Color(1, 1, 1) = 1, 1, 1, 1
[1, 1, 1, 1] = 1, 1, 1, 1
[[1, 1], [1, 1]] = 1, 1, 1, 1

Vector2(1, 2) = 1, 2
[1, 2] = 1, 2
["1", "2] = 1, 2
"1, 2" = 1, 2
["1, 2"] = 1, 2

I suggest one of two options:

1) Following the Python standard (and any other language that outputs complex types as strings):
* Printing string, int, real directly (so no quotes around strings).
* Printing Array, Dictionary, in a meaningful way, exactly the same as they'd be written in code, with nested 
* Printing Vector2, Vector3, Color in a meaningful way related to the class, e.g. Vector(22.2, 4), Color(0.1, 0.2, 1, 1)

Currently, this is the output provided by Variant::get_construct_string(), but that is only used in the editor hints. For some reason, elsewhere only the 

2) As an alternative, how about a repr() function, as in Python, that gives us the get_construct_string() output, rather than the mostly useless (for non-basic types) String() operator output...

(I'm happy to implement this stuff; just want to see which you want or will accept).

**Comment by reduz** [comment]
there is a function that works better for this kind of conversions to code,
but i'm not sure if it's available to script, will leave this open until i
can check issues and make sure it's there and documented.

**Comment by Spooner** [comment]
@reduz: Variant::get_construct_string() does it nicely, as I'd want to see data printed out.

**Comment by Spooner** [comment]
And it isn't available to script (it is only ever used in one place, in auto-completion hints)

**Comment by reduz** [comment]
will try to add this to gd_functions when i get back home

**Comment by Spooner** [comment]
Thanks. That will be great - mainly asking for it today because json parser isn't giving me the data I expect and it is almost impossible to accurately find out what it has actually given me :confounded:

**Comment by Spooner** [comment]
Oh, is there an equivalent of __str__()/__unicode__()/__repr__() for user classes? Because that would be useful too.

**Comment by reduz** [comment]
user classes can't be serialized, but there is a function to convert them
to and from a dictionary

**Comment by Spooner** [comment]
In Python, __str__()/__unicode__()/__repr__() allow you to choose the string representation that is created by a class when it is converted to a string. Nothing to do with serialization.

I think that is an answer to my other issue regarding serializing user objects to json, not this about converting things to strings . The problem with that is that it converts to a dict fine, but doesn't do it recursively (so, if I have an array of other objects in the object I inst2dict, then they aren't themselves converted to dicts so on to_json() they just turn into "[Reference:1234]", which means the data structure can't be jsonified anyway - if I have to inst2dict recursively myself when using inst2dict, then I would damage the data inside the object).

**Comment by reduz** [comment]
yeah don't expect JSON to convert datatypes not supported by JSON, It might
convert them to text in the worst case, but there would be no way to
convert them back afterwards due to the limitation of the format.

are you looking for a specific way of serializing data to text?

**Comment by Spooner** [comment]
I have a Level object filled with Tile objects (these are just data objects, not nodes in the world). Wanted to serialize the level and the tiles it contains too in one operation (currently I do this manually, which works fine, but seems cumbersome). This is what I'm trying to ask for in #1349 - this output of strings issue is just for debugging data structures (and has nothing to do with serialization).

**Comment by Spooner** [comment]
The new var2str() suits me very well. Thank you!

**Comment by Spooner** [comment]
Dumps of dictionary have superfluous parentheses in them.
var2str({"fish": 2, "frog": 3}) => '{("fish":2),("frog":3)}'
