### ISSUE TITLE
Mono: Exported variables from base classes are in the wrong order.

### ISSUE THREAD

**Issue by NathanWarden** [godotengine/godot#13493]
Can we change the order of exported values so that the base class values are on top and the sub class values are on bottom? It would be *much* more consistent this way.

The following project can be used. The base class is BehaviorTreeNode which has one exported variable "enabled". The first BehaviorTreeNode is located at "Navigation->BehaviorTree->Loop".

https://github.com/NathanWarden/godot_ai_csharp

This is how it currently looks.
![swapvalues](https://user-images.githubusercontent.com/629422/33504273-e0baf25c-d6b4-11e7-96c3-3b0f49f78dda.png)

Here's another class:

![screenshot from 2017-12-01 16-49-29](https://user-images.githubusercontent.com/629422/33505000-cf0c5016-d6b7-11e7-9a3f-961e9c6fe599.png)

@neikeq If you think this makes sense to change and it would save you time I'll change it.

Thanks :)

**Comment by leoddd** [comment]
The entire Inspector dock is set up so that base classes are on the bottom (Node -> Spatial -> Script Variables in your example). What do you mean when you say that suddenly reversing this trend would be more consistent?

**Comment by NathanWarden** [comment]
Thanks for asking... It would be more consistent because your variables in base classes would always be in the same place. Right now everything is in reverse order.

For instance:

``` C#
public class BaseClass
{
    [Export] public bool variable1;
    [Export] public bool variable2;
}
```

``` C#
public class SubClass : BaseClass
{
    [Export] public bool variable3;
    [Export] public bool variable4;
}
```

``` C#
public class SubSubClass : SubClass
{
    [Export] public bool variable5;
    [Export] public bool variable6;
}
```


Right now these variables show up as...

variable5
variable6
variable3
variable4
variable1
variable2

What I'm proposing would change it to:

variable1
variable2
variable3
variable4
variable5
variable6

In my case I have an "enabled" variable. So each node's behavior is enabled or disabled. But, it's really strange looking for my most common variables at the bottom of the list, and my specific variables at the top.

**Comment by NathanWarden** [comment]
@leoddd I do see what you're saying though :/ But, do the variable orders really need to follow a convention for component types? Well, not a deal breaker either way :)

**Comment by NathanWarden** [comment]
Actually, fixing this would make it consistent with GDScript...

If you make a script:

ClassA.gd
``` Python
extends Node
export var var1 = true
```

ClassB.gd
```
extends "ClassA.gd"
export var var2 = true
```

The variables show in the inspector as:

Var 1
Var 2

So my proposal will make it consistent :)

**Comment by NathanWarden** [comment]
Opened a PR for this at https://github.com/godotengine/godot/pull/13774
