### ISSUE TITLE
iOS: polygon_path_finder_demo showing flickering shapes

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#1351]
![screen shot 2015-02-10 at 12 38 20 pm](https://cloud.githubusercontent.com/assets/1840524/6131978/eae5ee78-b121-11e4-87a2-af8719718469.png)

iOS 7.1.2
iPodTouch 5g

On the desktop (OS X Yosemite) it runs ok

**Comment by reduz** [comment]
should give it a check i guess,
on a totally unrelated note, PolygonPathFidner is kind of obsolete now, with the recent push of 2D navpoly nodes.

**Comment by reduz** [comment]
will leave this open until punto can give it a check

**Comment by rraallvv** [comment]
Thanks for the info

**Comment by akien-mga** [comment]
The polygon path finder demo has been dropped from the repos. Are you able to reproduce a similar issue with another demo, or a custom project?

**Comment by akien-mga** [comment]
Closing, as this demo has been dropped.
