### ISSUE TITLE
function Input.get_mouse_speed () is unclear

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#1355]
this function for unknown reasons, after the cursor has stopped, it continues returns the speed that has been there before, instead of returning to zero speed.

**Comment by reduz** [comment]
I think the way this function works returns the mouse speed the last time you moved it, but does not keep computing the mouse speed (that would need a running average filter), it is intended to be used for gestures and scrolling with inertia

**Comment by OlexiyKravchuk** [comment]
Hmm ... I understand but then why the function is called "get speed ()" if it is "get inertia ()" or "get momentum ()" ???
I think it makes sense to rename or add new functions, what do you think about this option?

**Comment by akien-mga** [comment]
I guess it could be named "get_last_mouse_speed" or something like that.

**Comment by akien-mga** [comment]
I improve the documentation for `Input.get_mouse_speed`, so it should now be clearer. Maybe the function should be renamed for clarity when breaking compatibility in 3.0, I'll add this to the tracker for compatibility changes.
