### ISSUE TITLE
PSSM artifacts with directional lights

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#13575]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot master branch

**Issue description:**

It seems to me pssm and/or pcf need a little more work to be really usable.

For a simple scene with a cube and sphere, the default settings are not great (gap due to bias) but even after many tweaking I would say it's not ok : 
- split incoherence
- jaggy resolution (the settings for resolution in project settings do nothing)

**Steps to reproduce:**
Here my little scene with results (which are very different in every viewports) :
![screenshot from 2017-12-01 23-42-06](https://user-images.githubusercontent.com/9594859/33507285-3bd678ac-d6f4-11e7-9ba5-3f754e1fb184.png)

Here a comparison with unity (with no tweaking) :
![screenshot from 2017-12-01 23-58-02](https://user-images.githubusercontent.com/9594859/33507307-558b9624-d6f4-11e7-9c1d-7160c0cb9caf.png)

**Link to minimal example project:**

**Comment by soloparatolos** [comment]
I just tried the beta build an looks like the problems with the shadows are still there. I opened a couple of issues about this but got closed. I think that this is gonna be a real problem when more users get aboard with the beta and they see that there is no way to tune the shadows to look ok even in the simplest scene. This is the last issue I created #11390.

**Comment by Calinou** [comment]
Some notes:

- Directional shadow size changes are effective only after an editor restart (or running the project).
- Shadow maps will look poor when the viewport is very wide (but not when it's very tall), see the screenshots below:

**Wide viewport (bad directional shadows):**

![editor_wide](https://user-images.githubusercontent.com/180032/33514623-4781deea-d757-11e7-9222-73d4b747c81f.png)

**Square viewport (good directional shadows):**

![editor_square](https://user-images.githubusercontent.com/180032/33514624-47a0876e-d757-11e7-9015-3f0f46530b82.png)

**Tall viewport (good directional shadows):**

![editor_tall](https://user-images.githubusercontent.com/180032/33514625-47bba986-d757-11e7-844e-bf374944fb43.png)

OmniLights are not affected by this issue.

**Comment by kubecz3k** [comment]
Do blending splits makes it looks better?

**Comment by Calinou** [comment]
> Do blending splits makes it looks better?

Blend splitting is enabled in my project.

**Comment by reduz** [comment]
I insist that the PSSM algorithm is implememted as best as I understand it. It may be a matter of default settings. If anyone wants to research more on this topic, let me know and I will linknto relevant pieces of code

**Comment by matrem** [comment]
Blending help a bit but when there so much difference between two splits it seems not be able to smooth the result properly.
Long time ago I played with pssm and pcf, I don't know if I can improve anything, but I'm interested to look at how you did that. You implemented some specific paper ?

Some cool pointers, for anyone looking for information :
https://developer.nvidia.com/gpugems/GPUGems3/gpugems3_ch10.html
https://docs.unity3d.com/Manual/DirLightShadows.html
https://msdn.microsoft.com/en-us/library/windows/desktop/ee416307(v=vs.85).aspx
http://developer.download.nvidia.com/SDK/10.5/direct3d/Source/VarianceShadowMapping/Doc/VarianceShadowMapping.pdf
http://developer.download.nvidia.com/shaderlibrary/docs/shadow_PCSS.pdf
https://developer.amd.com/wordpress/media/2012/10/Isidoro-ShadowMapping.pdf
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.73.1923&rep=rep1&type=pdf
http://www.nvidia.com/object/doc_shadows.html

**Comment by volzhs** [comment]
@matrem if you are interested, #7204 this also would help. :smile:

**Comment by cosmicchipsocket** [comment]
The main issue I see with the directional shadows is that the objects don't appear to have contact with the ground. Lowering the bias much further from the default produces artifacts.

Here are the results I get using the same bias and normal bias settings from the Unity screenshot:

![screenshot_20180527_203232](https://user-images.githubusercontent.com/34800072/40592434-5edcdd1c-61ed-11e8-92fe-08a63c483c4c.png)

Setting any amount of contact causes pretty nasty artifacting. Here are some examples with a contact value of just 0.1:

![screenshot_20180527_203343](https://user-images.githubusercontent.com/34800072/40592436-6c7264ec-61ed-11e8-8571-d1877d878f9f.png)

Increasing the texture resolution of the directional shadows from 4096 to 8192 does let me set the bias lower before artifacting occurs (and thus make the shadows less floaty), but doing this effectively halves my framerate.

Why has #7204 been closed? Can it be resurrected?

**Comment by cosmicchipsocket** [comment]
Poking at this some more, it seems like the max shadow distance is what determines the resolution and precision of the shadows (combined with the shadow texture size selected in the project settings). This would explain why enlarging the geometry made the shadows more precise.

I wonder how the distance defaults compare to Unity?

**Comment by and3rson** [comment]
Bumping as this issue still persists.

**Comment by jayanam** [comment]
The shadows are still bad for directional lights in 3.1.1. Perhaps have a look at the code of UE4 to see how they did it.

**Comment by Calinou** [comment]
@jayanam We can't look at UE4 code, due to its license.

**Comment by jayanam** [comment]
I didnt mean to copy it, just understand how they implemented directional
lights and shadows, because the implementation of PSSM in Godot seams to be
incorrect.

**Comment by Calinou** [comment]
@jayanam Even merely reading its code constitutes a legal risk, as one of Epic's lawyers could claim the implementation is too close to the original.

**Comment by Zireael07** [comment]
What about Unity? https://blogs.unity3d.com/2018/03/26/releasing-the-unity-c-source-code/

**Comment by akien-mga** [comment]
> What about Unity? https://blogs.unity3d.com/2018/03/26/releasing-the-unity-c-source-code/

That blog posts is pretty clear.

Not open source.

**Comment by Zireael07** [comment]
You can't modify the code, but you can read it "... to understand or improve performance of games... made with Unity engine". And if you understand how Unity did it, there's nothing stopping you from improving Godot's implementation? Neither Unity nor UE4 have those issues with shadows...

**Comment by jayanam** [comment]
Yep, that's what I wanted to say.

**Comment by mysticfall** [comment]
I believe this is one of those gray areas of licensing and copyright. Some people consider it'd be ok to read proprietary source code and take some ideas from it as long as you don't actually copy the code, but there are also precedents like GNU Classpath, for instance, which forbade anyone who had seen the proprietary source code (thus 'becoming tainted') which it aimed to clone from participating to the project, to stay clear of any potential legal problems.
