### ISSUE TITLE
arrows + space-bar not work perfectly

### ISSUE THREAD

**Issue by Zefling** [godotengine/godot#1358]
If a press [←] or [→] + [↑] or [↓] + [space-bar], one of the direction is canceled. 

```python
	if (Input.is_action_pressed("ui_up")):
		orientation.y = -1
	if (Input.is_action_pressed("ui_down")):
		orientation.y = 1
	if (Input.is_action_pressed("ui_left")):
		orientation.x = -1
	if (Input.is_action_pressed("ui_right")):
		orientation.x = 1
	if (Input.is_action_pressed("ui_spacebar")):
		action = true
```
Is it normal ? With other key, I am not this problem.

I'm on Kubuntu 14.10 64.

**Comment by reduz** [comment]
it' s usually a hardware thing with keyboards

**Comment by Zefling** [comment]
I tested with 2 different keyboards, same problem.

**Comment by reduz** [comment]
i have an old IBM keyboard so this works fine, maybe someone else can
corroborate

**Comment by UsernameIsAReservedWord** [comment]
On my lenovo laptop keybord, for any combination of [↑] and [←] and [space], the third pressed key is ignored.
````
[↑] + [←] + [space] = [↑] + [←]
[space] + [↑] + [←] = [space] + [↑]
[space] + [←] + [↑] = [space] + [←]
````

On my logitech K800 wireless keyboard, all combinations work.

So, it must be related to the internal wiring of the keyboards.

What keyboards did you try ?

**Comment by Zefling** [comment]
My keyboards are a very old  Logytec in PS2 and a Pleomax in USB.

**Comment by ni-code** [comment]
I have the same problem on ubuntu 14.10 usb MKplus keyboard. 
Combination of [↑] and [←] and [space], the third pressed key is ignored
I'll try tomorow in other computer

**Comment by ni-code** [comment]
so, I tested with my laptop "asus k55v" runing ubuntu 14.10 and no problems.. the key combinations runs just fine

**Comment by kubecz3k** [comment]
It looks like this bug is related to keyboards (hardware). So I'm archiving it. Please comment if anyone have any informations that might negate that - I will reopen.

**Comment by Barina** [comment]
N-Key rollover
