### ISSUE TITLE
Godot 3.0 crashes when opening project on Mac OSX 10.9.5

### ISSUE THREAD

**Issue by skyburchard** [godotengine/godot#13654]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mac OSX 10.9.5, Godot 3.0 beta1

**Issue description:**
Godot 3.0.beta.build1 crashes after creating new project or opening existing project.

I first trashed my Godot 3.0.alpha.build2 version and the one project I had created using it. I downloaded Godot 3.0.beta.build1 and dragged it to my applications folder. I started the app and got the create project dialog entered a directory and a folder and clicked create. Then the app crashed before I get to the editor. When I reopen the Godot, the new project is listed but when a double click it Godot crashes again.

I have posted the beginning of the error log below for reference. I also noticed that the size of the beta1 app is only 72 MB while the alpha2 app is 140.7 MB.

**Steps to reproduce:**
Start a new project causes a crash
Open a project causes a crash

**top section of error log**
Process:         Godot [1014]
Path:            /Users/USER/Downloads/Godot.app/Contents/MacOS/Godot
Identifier:      org.godotengine.godot
Version:         3.0-dev (3.0-dev)
Code Type:       X86-64 (Native)
Parent Process:  ??? [1]
Responsible:     Godot [1014]
User ID:         501

Date/Time:       2017-12-01 15:57:57.170 -0800
OS Version:      Mac OS X 10.9.5 (13F1507)
Report Version:  11
Anonymous UUID:  2801C782-005A-B2E4-6A7D-62CD0C8C02DF

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Dyld Error Message:
  Symbol not found: __os_log_internal
  Referenced from: /Users/USER/Downloads/Godot.app/Contents/MacOS/Godot
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by JuanDidNothingWrong3** [comment]
Not a high priority. Downvoted, and voting to close.

**Comment by akien-mga** [comment]
Do you still have the same issue with 3.0 beta 2?

**Comment by akien-mga** [comment]
Mac OSX 10.9.5 is quite old now, I'm not sure if we still support it. Maybe @BastiaanOlij can shed some light.

**Comment by akien-mga** [comment]
Well it seems to be our minimum supported version, so should work I guess: https://github.com/godotengine/godot/blob/master/platform/osx/detect.py#L127-L128

**Comment by skyburchard** [comment]
@akien-mga I have 3.0 beta 2, but i have since updated to MacOS 10.13.2. I upgraded, partially to see it I could get Godot 3.0 working on my Mac and it does!

I have a bootable copy of my old mac I can test on though. Ill try it later today, when I have access to it.

**Comment by akien-mga** [comment]
Bug confirmed by @bruvzg in https://github.com/godotengine/godot/pull/15401#issuecomment-355772812. We'll need to find a fix, or decide to drop support for 10.9 (I have no strong opinion, I don't know how widespread that version still is).

**Comment by bruvzg** [comment]
There are two places with post 10.9 code: logger(10.12+) and set_window_size(10.11.4+)
both are inside `#if MAC_OS_X_VERSION_MAX_ALLOWED` sections and building Godot on target os version fix bugs.

Probably we should add additional runtime os version checks.

**Comment by akien-mga** [comment]
AFAIK we can't really do runtime version checks for such things, it's the same for Windows, we need to target the lowest supported version to have a binary that will work everywhere. So to support 10.9+, we need to configure the buildsystem to target that version, and all code requiring 10.11.4+ or 10.12+ won't be used in official binaries (but could be used in self-compiled binaries for those who want).

**Comment by akien-mga** [comment]
CC @endragor @BastiaanOlij

**Comment by bruvzg** [comment]
OSX code already have multiple runtime checks like: https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L77

I just checked logger with similar one on 10.9 and it is working.

**Comment by bruvzg** [comment]
Also all existing runtime checks are for 10.6 an can be removed.

**Comment by akien-mga** [comment]
Ah, good to know. Seems more flexible than Windows then :D
