### ISSUE TITLE
Sprite3D and MeshInstance -> BillboardY property doesn't work

### ISSUE THREAD

**Issue by AlexanderO88** [godotengine/godot#1366]
Hello together,

in Godot 1.0 stable the BillboardY property from Sprite3D seems broken.

To test create a Sprite3D node, add a texture and activate the BillboardY property in the editor and it should nothing happens. The normal Billboard property works fine.

I use Godot 1.0 stable under Kubuntu 14.04.

**Comment by not-surt** [comment]
I had a look in the sources but couldn't find where it's implemented. Maybe a todo or overlooked.

**Comment by not-surt** [comment]
I had a go at fixing this here #1368.

**Comment by AlexanderO88** [comment]
Hello not-surt, thank you for your help and work. :) A small additional information, the billboard_y property from the MeshInstance is broken too.

**Comment by akien-mga** [comment]
The bug is still valid in the current master branch according to https://github.com/godotengine/godot/issues/2061#issuecomment-156806560

**Comment by Calinou** [comment]
I can confirm this bug too, Billboard Y doesn't seem to do anything.

**Comment by trollworkout** [comment]
is still not working :(
even from code FLAG_BILLBOARD_FIX_Y

**Comment by akien-mga** [comment]
Fixed by #5962.
