### ISSUE TITLE
Add more primitives to the editor for rapid prototyping

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#1381]
When it comes to rapid prototyping, rather than creating a new scene in the 3d or 2d modelling tool of choice, and then importing that scene to Godot, it would be great if one could just add primitives like spheres, cylinders, circles, etc. to the scene directly from the Godot editor.

Also exporting the scene from Godot as COLLADA and maybe SVG for 2d scenes, would make easier to move from prototyping to fleshing out the scene with textures and more detailed geometry.

**Comment by reduz** [comment]
this makes a lot of sense..

**Comment by not-surt** [comment]
I've been thinking the same thing.
With the addition of navigation polygons there are now three different 2D polygon types.
It'd be cool if Polygon2D and the other Shape2D classes could be made multi-purpose for physics, drawing, navigation (where relevant).
If a shape is the child of a physics body then (by default) it is not drawn, but used for physics. (An option on physics bodies to draw shapes would be good for when you want both rendering and physics)
If a shape is the child of a CanvasItem then it is drawn, but not used for physics.

**Comment by kubecz3k** [comment]
Closed https://github.com/godotengine/godot/issues/1508 because it was a duplicate but 
bojidar-bg had some idea there:
*I think that it will be better if we have classes like "CubeMesh", "SphereMesh", etc. that extend the "Mesh" class. That way we won't have nodes for everything in the node selection menu, and it will be easy to change properties like size, subdivisions, *

**Comment by reduz** [comment]
I would like to have something like CSG, but don't know much about it

**Comment by kubecz3k** [comment]
It's hard not to mention "Add Primitives" plugin made by @TheHX which generally solves the issue and is working quite well: https://github.com/TheHX/add_primitives

**Comment by kjohnson0451** [comment]
I'm using @TheHX 's plugin as a reference to implement this as a C++ module.
https://github.com/kjohnson0451/godot/tree/create_primitives

**Comment by neikeq** [comment]
IMO this is better in the 3.0 milestone, since the renderer will be improved for 3.0 and probably the 3D tools too.
@godotengine/bugsquad WDYT?

**Comment by kubecz3k** [comment]
@neikeq well I think you are right, in 2.1 we will get plugins, I'm quite sure there will be plugin for that very fast (it already is actually), so I guess we will need to rely on it.

**Comment by JonasT** [comment]
I think the objects should also not be named test objects. Why exactly can people not use this to build actual levels directly not just for testing? Not everyone needs fancy highres 3d models for everything, so some are going to be fine with primitives for simpler graphics styles. Naming "TestCube" degrades it in a weird way, as if it wasn't going to work properly in a final game.

**Comment by eon-s** [comment]
Now that the 3D editor is getting interestingly complicated I agree with this, but not nodes like TestCube, it need builtin meshes to use everywhere, even on the particle system.

Or maybe ship a set of resources with the engine (meshes, materials, shaders and simple scenes ready to use and tweak).

**Comment by akien-mga** [comment]
Fixed by #8661.
