### ISSUE TITLE
How to use NativeScript in Beta 1

### ISSUE THREAD

**Issue by HadesD** [godotengine/godot#13834]
I 've tried create a project in Alpha 2, follow this thread https://godotengine.org/article/dlscript-here, but after build my lib then run scene, it show this Error:
https://i.imgur.com/WDhLlHD.png

In beta 1, I don't know how to create NativeScript. I don't want to use GDScript.

**Comment by Sslaxx** [comment]
GDNative has changed quite a lot since this article was produced.

Take a look at https://github.com/GodotNativeTools/godot_headers and see if it helps?

**Comment by HadesD** [comment]
@Sslaxx thanks your help, I 've run it succcessfully.
Now have some error with godot-cpp build.
Can you help me at there: https://github.com/GodotNativeTools/godot-cpp/issues/53

**Comment by Sslaxx** [comment]
@karroffel is the man to be asking, really, GDNative is his baby.

**Comment by fire** [comment]
I was able to get it working today! Will see if I can solve any of your problems.

**Comment by HadesD** [comment]
@fire I was edit somethings in SCons script, It build successfully.
Now I have a **libtest.so** follow the https://github.com/GodotNativeTools/godot-cpp#creating-simple-class, I want to ask how to use it in Godot 3.0 Beta 1. In Alpha 2, Game crashed after I ran scene.

**Comment by fire** [comment]
The gdns creation steps are competely wrong. I'm reorganizing this repo, but take a look at the sample folder. The dll is at sample/addons/SimpleClass/lib/impleClass.dll and the scripts at  sample/addons/SimpleClass/ https://github.com/fire/com-chibifire-simple-class-gdnativescript-plugin

Don't mind my use of bazel. It's a source code build system.

**Comment by HadesD** [comment]
@fire Thanks you so much. All of the problem is here:
```
[entry]

X11.64=""
Windows.64="res://addons/SimpleClass/lib/SimpleClass.dll"
OSX.64=""

[dependencies]

X11.64=[]
Windows=[]
OSX.64=[]
```

I'm using linux, open the editor do not show how to add these entrys to script. Is it bugging in here?

**Comment by fire** [comment]
I don't know. It's an editor bug that should be fixed, but for the sake of this weekend, I'm going to continue on the ludumdare 48 hour jam.

**Comment by HadesD** [comment]
@fire yeah :+1: 

Just one ask.
I want to use NativeScript as GDScript, that I can just add **dynamic lib** to Editor, game will be use it to control my Node (Like KinematicBody2D in https://godotengine.org/article/dlscript-here). Can I do like that in Beta 1?

**Comment by fire** [comment]
Can you be more specific? Can you give an specific example.

**Comment by capnm** [comment]
@HadesD  IIRC something like this worked for me:

you need at least 3 files. Your compiled library e.g. `libtest.so`
(I used the actual headers built from the godot repo `modules/gdnative/include`),
then you have to create `test.gdnlib` in any text editor:
```
[general]

singleton=false
load_once=true
symbol_prefix="godot_"

[entry]

X11.64="res://libtest.so"

[dependencies]

X11.64=[]

```
Then in the Inspector save the `test.gdns` as a NativeScript  and select the `test.gdnlib` as a library.

In GDScript you can then e.g. access a registered function in the lib with:
```
var testlib = preload("res://test.gdns").new()
testlib.test_function()
```
I have to use the c api directly and it seems to be working as it should. I know nothing about the current c++ interface state, sorry ;)

**Comment by HadesD** [comment]
@fire @capnm thanks all of your help
But I want to use the **libtest.so** like GDScript, like this:
```
#include <godot_cpp/Godot.hpp>

#include <godot_cpp/KinematicBody2D.hpp>
#include <godot_cpp/Input.hpp>

using namespace godot;

class Player : public KinematicBody2D {
    GODOT_CLASS(Player, KinematicBody2D)

    float speed = 200; // pixel/second

public:

    void _fixed_process(float delta)
    {
        Vector2 input;

        if (Input::is_action_pressed("ui_up")) {
            input.y -= 1;
        }
        if (Input::is_action_pressed("ui_down")) {
            input.y += 1;
        }
        if (Input::is_action_pressed("ui_left")) {
            input.x -= 1;
        }
        if (Input::is_action_pressed("ui_right")) {
            input.x += 1;
        }

        self->move(input.normalized() * speed * delta);
    }

    static void _register_methods()
    {
        register_method("_fixed_process", &Player::_fixed_process);
    }

};

GODOT_DLSCRIPT_INIT(godot_dlscript_init_options *options)
{
    register_class<Player>();
}
```

Then in editor, I just add it to script of that Kinematic Node in scene, not like load .gdns in GDScript

**Comment by BastiaanOlij** [comment]
You still need a gdns file to construct the player node. It doesn't work like how module classes are registered.
The samples unfortunately haven't been updated for awhile on the demo repo. You can have a look at a demo project i'm still working on that should work with the latest changes:
https://github.com/GodotNativeTools/GDNative-demos/pull/9
https://github.com/BastiaanOlij/GDNative-demos/tree/space_colonization

Have a look at how its constructed here:
https://github.com/BastiaanOlij/GDNative-demos/blob/space_colonization/cpp/space_colonization/Main.gd#L7

**Comment by HadesD** [comment]
@BastiaanOlij Thanks you.

Your demo is running correctly. But it seem not like what I want

I 've found this and built it successfully, but game can't run, It crashed immediately
https://github.com/GodotNativeTools/GDNative-demos/tree/master/cpp/kinematic_character

**Comment by BastiaanOlij** [comment]
I don't think the kinematic_character demo has been updated in a long while, it probably doesn't have any of the recent changes build in.

I didn't build it so unfortunately I'm not sure what could be wrong with it, other then changing the resource files

**Comment by HadesD** [comment]
So can I make a project like this? With only shared lib?
I ‘ve tried to create alots of them but nothings was happened, they didn’t work

**Comment by BastiaanOlij** [comment]
@HadesD I'm at work at the moment but I'll find some time tonight to see if I can get the character demo going. I think I get your problem now but I've not tried to use GDScript in that manner. Pretty sure what you want is possible.

**Comment by BastiaanOlij** [comment]
Probably needs more testing and I've only played around with this on Windows, but this may help a little:
https://github.com/GodotNativeTools/GDNative-demos/pull/15

**Comment by BastiaanOlij** [comment]
Note btw that I do not think the GDNS files are use in the kinematic example. Everything is used directly inside of the scenes which I think is what you were after @HadesD ?
Do note you do need to use the gdnlib file which is loaded as an external resource, that is currently the only way you can load the dynamic library.
