### ISSUE TITLE
2D viewport issues

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#1383]
![bug](https://cloud.githubusercontent.com/assets/1546044/6230902/11cc991e-b678-11e4-9fd5-d573fa548e2f.gif)

![bug2](https://cloud.githubusercontent.com/assets/1546044/6231073/372b8cf0-b679-11e4-900a-fb1586d8c8ee.gif)

Here is a test scene.
https://www.dropbox.com/s/rlizr4yrsauycz4/2dscalebug.zip?dl=0

Im not exactly sure of all the issues, but these are just some I've witnessed.
they don't seem to actually take effect if you run it, it's just in the editor, I think (not sure).

**Comment by akien-mga** [comment]
Hi @LeonardMeagher2 and sorry for the delay. It looks like your test scene is no longer available, could you upload it again? (use up1.ca if need be)

**Comment by akien-mga** [comment]
Can you still reproduce this issue in the current master branch?

**Comment by reduz** [comment]
it' s better to just disable selection of stuff inside a viewport, as it' s too difficult to figure out what' s going on inside. Better to just edit in a separate scene and instance on the viewport.
