### ISSUE TITLE
The RAY always collide to AREA (3.0 beta1)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#13830]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04, Godot 3.0 Beta 1

**Link to minimal example project:**
[Bug area.zip](https://github.com/godotengine/godot/files/1523709/Bug.area.zip)

P.S. Godot Phisics

**Comment by kubecz3k** [comment]
Hello, you should  add a little more detailed informations. The issue is probably about the lack of collision types in 3.0 which is done  intentionally #13159  In 3.0 you should use normal mechanism of collision layers to handle this.

**Comment by DimaKiva** [comment]
I want AREA not to be an obstacle to RAY. So the weapon of character uses RAY as a target. It must see enemies rather than triggers.

**Comment by kubecz3k** [comment]
so you need to have your areas on different collision layer than your ray

**Comment by DimaKiva** [comment]
I checked in RC1. Bullet and  GodotPhysics work in different ways.

**Comment by DimaKiva** [comment]
RC3 ray rests in area in GodotPhysics

**Comment by AndreaCatania** [comment]
@DimaKiva Did you fix this?

**Comment by DimaKiva** [comment]
@AndreaCatania No. GodotPhysics return Area, Bullet return Null.

**Comment by AndreaCatania** [comment]
Fixed in current master:  #8c435a3 can you please confirm it?

**Comment by DimaKiva** [comment]
3.1-alpha1 The problem is no longer there.

**Comment by vnen** [comment]
Closing as fixed.
