### ISSUE TITLE
Derived instance of CollisionShape2D using parent parameters instead of their own

### ISSUE THREAD

**Issue by gururise** [godotengine/godot#13835]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux - Godot 3.0 Beta

**Issue description:**

Colliders in derived scenes do not use their position or size, instead they use the parent scene Collider position/size.

I would expect the derived scene CollisionShape2D to use its position and size for performing collisions, as other nodes (ie. Sprite) in the derived class make use of their own properties (ie. transform, texture).. otherwise, inheritance for character scenes will really only work for sprites/characters that are the same size.

A clear example of the problem:
![image](https://user-images.githubusercontent.com/4380009/33518174-a2885628-d745-11e7-8ad4-1e2cf3e1ebbb.png)

**Steps to reproduce:**
I have the following base scene:
**Character** (KinematicBody2D)
|-Sprite
|-CollisionShape2D (Capsule Collider)

I derive two scenes from the above:
* Skeleton
* Player

**Note:** In each of the derived scenes, the Shape2D sub-resource of the associated CollisionShape2D has been made "Local to Scene".

On the left is the parent character scene.  On the right is the derived skeleton scene:
![image](https://user-images.githubusercontent.com/4380009/33517588-c780e328-d73b-11e7-9326-236b0f58e543.png)

**Scene setup** (all nodes are at the same y position), only sprites are scaled. (right - child scene player, center - parent scene character, left - child scene skeleton).

The scale of the CollisionShape2D and the KinematicBody2D are all (1,1).  The derived CollisionShape2D capsules have been re-positioned and resized (but not scaled):
![image](https://user-images.githubusercontent.com/4380009/33517562-47577400-d73b-11e7-9dee-d4ed56705775.png)

After running the scene (with gravity):
![image](https://user-images.githubusercontent.com/4380009/33517566-59cadf00-d73b-11e7-8625-10ec0fab8463.png)

* Notice the physics engine appears to be using the parent capsule collider position and size rather than the derived scenes capsule collider parameters.

* Even making the Shape2D sub-resource "Local to Scene" in each derived CollisionShape2D does not fix the problem.  Running the test scene, I've also confirmed that each CollisionShape2D object in each of the three character scenes is different, although I don't see a way in the editor/debugger to view the Shape2D sub-resource.

**Comment by leoddd** [comment]
The same goes for CollisionPolygon2D, meaning it's not an issue of sharing a resource as CollisionPolygon2D has no proper resource attached, just a PoolVector2Array to define the points.
![collisioninheritance](https://user-images.githubusercontent.com/20242421/33518303-ddf9a9da-d792-11e7-83fe-7ec5055b4ce9.gif)

**Comment by mrcdk** [comment]
This happens because the only times the shape transform is updated between the visual representation and the physics world happens when it's parented and when the local transform is updated: https://github.com/godotengine/godot/blob/master/scene/2d/collision_shape_2d.cpp#L51-L77

It looks like modifying the transform in a instanced scene isn't triggering the `NOTIFICATION_LOCAL_TRANSFORM_CHANGED` notification.

Not sure what to do with this but maybe this info helps someone else with it.

**Comment by gururise** [comment]
**Note**: The docs seem to imply that any changes to derived scenes should affect instances of the derived scene.  So the behavior above does appear to be a **bug**:
http://docs.godotengine.org/en/stable/learning/editor/unity_to_godot.html?highlight=%20change%20#where-are-my-prefabs

**Comment by gururise** [comment]
I've attached a minimal project demonstrating the problem:
![image](https://user-images.githubusercontent.com/4380009/33800112-e0eb833c-dcee-11e7-8aaf-d7a744837093.png)

[inheritedScene.zip](https://github.com/godotengine/godot/files/1545173/inheritedScene.zip)

**Comment by RandomShaper** [comment]
Investigation in progress...
