### ISSUE TITLE
Option to preview with remote scene tree should be disabled by default

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#13833]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 beta 1

**Issue description:**

Preview scene starts with default remote scene tree activated, this become in a very bad and choppy performance of the game loop. This option should be manualy activated clicking the remote option in panel only for testing/debugging, not always by default. 

![uncheckremotescenetree](https://user-images.githubusercontent.com/11712737/33516130-9d00d162-d76d-11e7-8713-7f934c0b9cd2.jpg)

**Link to minimal example project:**

**Comment by akien-mga** [comment]
Agreed, until the performance is improved it should be opt-in, not opt-out.
