### ISSUE TITLE
Strange transform in gradient texture inside sprite

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#13838]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 beta 1

Gradient is out of the visual bounding box of a sprite node. 

![strangetransformingradient](https://user-images.githubusercontent.com/11712737/33519209-a4f25398-d7a2-11e7-8cbc-15a215ea8ae0.jpg)

I don´t know if this is expected, but make sense that the bounding box cover the gradient. Maybe doing a gradient with more pixels in height can fix that.

**Comment by mrcdk** [comment]
It looks like it's an issue with any texture that's 1 pixel tall (which a gradient texture is) or 1 pixel wide:

![https://i.imgur.com/wtI1UEe.png](https://i.imgur.com/wtI1UEe.png)
From left to right:
- 128x1 scaled
- 128x2 scaled
- 1x128 scaled
- 2x128 scaled

**Comment by Ranoller** [comment]
Yes. I was user or Construct2 and same happend. My manual solution was use png-gradients 5 pixel tall. I think that math related with texture position don´t like multiply/divide/whatever by 1.

**Comment by mrcdk** [comment]
One way to solve this is to disable the centered property of the sprite.

**Comment by Ranoller** [comment]
Yes, but strange behavior remains, if you change offset.y note that that not work in pixels, it´s behavior is like in percent or something like that. Offset (-200,-2) moves the texture 200 pixels left and a bunch of pixels up. If you want centered y position you can write offset.y=-0.5.... but that should be by default not adding offset!!!!

**Comment by Ranoller** [comment]
Bounding box should be very easy to fix in engine:


![gradientbadoffset](https://user-images.githubusercontent.com/11712737/33521255-7ab82384-d7cd-11e7-8293-e4036fe583c2.jpg)

**Comment by Ranoller** [comment]
This was fixed in master
