### ISSUE TITLE
Load Errors at game startup from editor

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#13839]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 x64, Godot 3 Beta 1

**Issue description:**

Whenever I start playing my project, there is a seemingly random chance for Load Errors telling me that my project's `project.godot` file is in use to pop up. This only seems to happen when I hit play with unsaved changes, or very quickly after saving, but does not always happen when doing so.
![2b6eb62fe2a0a8bdeba4e343686b50cf](https://user-images.githubusercontent.com/20242421/33520110-c11e8db8-d7b4-11e7-80c4-bc5964d8047f.png)
(Note that while there are 3 in this screenshot, only 1 was actually output, they simply aren't removed between each time so the first 2 stuck around from earlier occurences of this issue.)

The console outputs this error whenever this happens, before the usual GPU messages:
```
ERROR: FileAccessWindows::close: Condition ' rename_error ' is true.
   At: drivers\windows\file_access_windows.cpp:139
```

Of note is that these errors do not hinder playback in any way. The game runs fine and everything works, except there's now a popup window in the editor.

**Steps to reproduce:**
Create a project and try to open it with unsaved changes in script or scene.

**Comment by vnen** [comment]
Can you test again with the latest master? This likely have been fixed by #13989.

**Comment by leoddd** [comment]
I won't be able to test this fix any time soon, as my Windows PC just burned alive and I'm stuck with Linux for the time being. I'd appreciate if someone else who had this issue before could test it for me!

**Comment by NathanLovato** [comment]
Just tested it with yesterday's build from http://godot3builds.digitecnology.com/ and the error doesn't appear anymore here - Win 10 :)
