### ISSUE TITLE
Editor sliders are tiny and difficult to hit

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#13845]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 beta 1

**Issue description:**

Horizontal sliders of editor are too thin and is difficult to hit in them and drag. Contextual slider in exported variables are very very tiny. They should be taller:

![tinysliders2](https://user-images.githubusercontent.com/11712737/33520967-47e5f4b6-d7c5-11e7-96a3-4b91ab8bc302.jpg)
![tinysliders1](https://user-images.githubusercontent.com/11712737/33520968-49a0de9c-d7c5-11e7-9c8e-a598b2574ce3.jpg)

**Comment by reduz** [comment]
@toger5 @djrm I noticed the same recently, they are difficult to hit.

**Comment by Zylann** [comment]
Their hitbox used to be fairly clickable (I use sliders in my custom module), I think something broke, I noticed it too in the color picker

**Comment by djrm** [comment]
is this about the hitbox, im not sure if the current hitbox when the slider is unfocused has the size of the small handler, i would expect it to have a constant size so it is texture independent, o is it about its appearance?

**Comment by icnikerazah** [comment]
i hate this ;
![hard](https://user-images.githubusercontent.com/33985414/34457716-e03b31ca-edca-11e7-98eb-53df494981a9.gif)

**Comment by reduz** [comment]
Sorry.. will rewrite the inspector for 3.1

**Comment by djrm** [comment]
@icnikerazah you are not even trying to hit the button at the center.

**Comment by puppetmaster-** [comment]
The slider don't has a hit box! Only the line is responding.
![slider_hitbox_problem](https://user-images.githubusercontent.com/10463138/35461837-be3f6dbe-02e9-11e8-9515-89edef558669.gif)

**Comment by Zylann** [comment]
I just tried with a GDScript editor plugin, they have the same problem in 3.0.2.

**Comment by toger5** [comment]
The slider ui element itself is just the black bar. (the grabber is just overlapping...) so mouse_inside is only the case if your mouse is actually inside the center bar.

There are set to shrink vertically.
Maybe making them bigger and than adapting the style box would be the simplest solution

**Comment by djrm** [comment]
i think this has been fixed with the new inspector.

**Comment by mhilbrunner** [comment]
Closing as fixed for now, please comment if you still encounter this with the new inspector in master/3.1 or recent daily builds
