### ISSUE TITLE
Previous/Next tab shortcuts do not work

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#13843]
Current shortcuts `Ctrl+Tab` and `Ctrl+Shift+Tab` for Next/Previous tab do not work. They change the element/dock in focus instead. Either that should be fixed or another pair of shortcuts should be used. I'd suggest `Ctrl+PageUp`/`Ctrl+PageDown`, which is very common.

**Comment by NilsIrl** [comment]
Working on it

**Comment by NilsIrl** [comment]
Seems to be a duplicate of #8799

**Comment by akien-mga** [comment]
Thanks, closing as duplicate.
