### ISSUE TITLE
Preview game changes editor TAB

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#13846]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 beta 1

**Issue description:**

Executing the game with script tab opened changes the tab to 2D.

 

I don´t know if this is a feature or a bug. But first time that this happens there is no problem, you click in "Script" tab and ok. Ten times later, is annoying lost the code tab. In Godot 2.1 opened tab is respected.

**Comment by AyeTbk** [comment]
By default, when starting your game from the editor, the editor changes its view to show you the scene tree of the running game (remote scene tree) so you can inspect/edit it live. This can be disabled in "Editor Settings" -> "Debugger" -> "Auto Switch To Remote Scene Tree" (untick it).

**Comment by Ranoller** [comment]
Yes, It works... "Auto Switch To Remote Scene Tree" should be disabled by default in editor. I have one issue yet for that so I close this issue. Thanks.
