### ISSUE TITLE
Implement yield_from()

### ISSUE THREAD

**Issue by Spooner** [godotengine/godot#1385]
Newer versions of Python implement yield_from(), which makes nesting co-routines easier.

You can mimic it in a coroutine with:

``` gdscript
    func coroutine1():
        # do something
        yield()

     func coroutine2():
         # Do stuff with yields

         var sub_coroutine = coroutine1()
         while sub_coroutine.is_valid():
             sub_coroutine.resume()
             yield()

         # do more stuff with yielding
```

But with yield_from():

``` gdscript
     func coroutine2():
         # Do stuff
         yield_from(coroutine1())
         # do more stuff
```

**Comment by Spooner** [comment]
In case it isn't obvious, this is just a bit of syntactical sugar, so it is very low priority.

**Comment by vnen** [comment]
In 4.0 we are introducing the `await` keyword which can already do it: `await coroutine()`.
