### ISSUE TITLE
Text editor should allow editing non-script files

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#1390]
We should be able to edit non-script plain-text files in the built-in text editor, with the debugger and syntax highlighting turned off. This would be useful to keep a TODO or Changelog or README file open in a tab for quick reference, and edits without having to open a different piece of software.

**Comment by UsernameIsAReservedWord** [comment]
+1

**Comment by Nulifier** [comment]
I've been looking into how the Script Editor selects which files to open and currently it just handles anything that inherits from Script. I'm trying to make a visual scripting editor and I had to hack this already to get it to check a specific flag on the Script class. Maybe adding a flag to the Resource class of is_text_based or something would be the best way of handling this.

It would be useful to keep everything in the editor. Also for editing data files in json for example.

**Comment by Ace-Dragon** [comment]
My opinion is also that this could be a good idea, ideally this should be done by introducing a separate 'plain text' mode that opens and saves generic text files (and also disables auto-complete, syntax checking, and syntax highlighting).

**Comment by vnen** [comment]
Just to add my :+1: (and facilitate my search for this later on).

**Comment by vnen** [comment]
So, for what I can understand this will require a certain amount of refactoring of the `ScriptEditorPlugin` (or a bunch of hacks to make it just work). I believe the best approach is to create a new type of resource (`TextFile` or something) and use the `ResourceLoader` interface to open the text editor when needed. For what I understand this would also enable the opening of text files via double-clicking in the File System dock.

**Comment by neikeq** [comment]
@vnen What about text files without an extension?

**Comment by vnen** [comment]
@neikeq one possibility is to allow opening any file that is not already recognized by the editor. Maybe change the function that deals with opening the proper editor to open the text editor if the type wasn't recognized. That'd also allow opening of binary files in the text editor, but I guess this can't be avoided.

There's also the issue with the File System dock that shows only recognized files. Maybe it can be made to show all files.

**Comment by SuperUserNameMan** [comment]
If only 8bits text encoding are supported (ascii, utf-8, ansi, and others) then, to differentiate binary files from text files, it could be possible to scan the content to detect uncommon non printable characters (most values between 0 and 31).

**Comment by vnen** [comment]
@SuperUserNameMan it's possible. I just don't know if that can be done efficiently.

**Comment by neikeq** [comment]
That's not the problem I was talking about. IINW, `ResourceLoader` needs an extension, and will only recognize a file if it has this extension (I think it accepts more than one extension).

**Comment by vnen** [comment]
We got some cross talk in here. @SuperUserNameMan was talking about binary files and I answered.

My reply to @neikeq (in https://github.com/godotengine/godot/issues/1390#issuecomment-226942761) was about dropping the "`ResourceLoader` for text files" idea and instead open the files in the text editor if not recognized by any of the `ResourceLoader`s.

**Comment by akien-mga** [comment]
See also #6218 for a request for scene (`.tscn`) edition in the text editor, which depends on this issue.

Godot's text editor can now open both GDScripts and C# files, and @Paulb23 recently abstracted the syntax highlighting logic, so I think we should not be too far from being able to edit any kind of text file. It will be useful for people who want to use thirdparty language bindings like the Nim, D, Python, Rust, etc. ones and quickly edit those scripts in Godot.
