### ISSUE TITLE
Official godot_x11 binaries can't locate libssl.so.1.0.0 on Fedora

### ISSUE THREAD

**Issue by q2dg** [godotengine/godot#1391]
The error is:

    ./godot_x11-1.0stable.64: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

After doing *ln -s /usr/lib64/libcrypto.so /usr/lib64/libcrypto.so.1.0.0* , I get this error:

    ./godot_x11-1.0stable.64: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

After doing *ln -s /usr/lib64/libssl.so /usr/lib64/libssl.so.1.0.0* , I get this error:

    ./godot_x11-1.0stable.64: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./godot_x11-1.0stable.64)
    ./godot_x11-1.0stable.64: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./godot_x11-1.0stable.64)

I'm running a Fedora 21 system (64 bits, of course) with Openssl 1.0.1k installed (stock version from official repository)

**Comment by fry-** [comment]
I'm running Fedora21 (64bit) too and i experienced the same problems. I've built it (stable branch) from source, which works perfectly, so you could make it as a workaround until this issue gets fixed.

**Comment by q2dg** [comment]
Well, it seems to work. Thanks a lot!!

A request: could you add to "Requirements section" in https://github.com/okamstudio/godot/wiki/compiling_linux the command to install Fedora packages (as it is for Ubuntu)? I've successfully tried with:

    dnf install scons python make automake gcc gcc-c++ kernel-devel pkgconfig libX11-devel libXcursor-devel alsa-lib-devel openssl-devel freetype-devel mesa-libGL-devel mesa-libGLU-devel pulseaudio-libs-devel

Only one thing: when I close the editor, I get in terminal these errors...I don't know if they are important:

   ERROR: free: Method/Function Failed.
        At: servers/visual/visual_server_raster.cpp:4314.
    freed code id 6
    ERROR: free: Method/Function Failed.
       At: servers/visual/visual_server_raster.cpp:4314.
    ERROR: free: Method/Function Failed.
       At: servers/visual/visual_server_raster.cpp:4314.
    ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
       At: core/io/packet_peer.cpp:228.
    base resources missing 2
    ERROR: finish: Condition ' instance_dependency_map.size() ' is true.
       At: servers/visual/visual_server_raster.cpp:7003.
    ERROR: cleanup: ObjectDB Instances still exist!
       At: core/object.cpp:1715.

**Comment by adolson** [comment]
For the record, this issue is still present over a year later for Fedora users (and possibly other distros). Debian (and I assume Ubuntu) have the same version of libssl as Fedora (1.0.1k) but they differ in file naming for whatever reason...

What this means is that if someone releases a game made with Godot, that game won't work for Fedora users. This is a problem. The Godot editor itself also won't work on Fedora, but can be made to work by compiling from source. This isn't possible with binary-released games.

There must be a better solution than requiring a specific version of libssl? Can it be linked to libssl.so instead? This is a symlink present on Fedora, Debian, Ubuntu, and likely other distros which points to the correct installed 1.0.1k libssl and I *think* it will solve the issue, at least partially... What happens when Fedora gets libssl.so.1.0.2 or something, and Godot is linked against libssl1.0.1? I have no idea... But for people looking to release games, this is something that needs to get addressed.

**Comment by germinolegrand** [comment]
same problem for me, my colleague built godot on ubuntu, can't run it on fedora.

**Comment by akien-mga** [comment]
> There must be a better solution than requiring a specific version of libssl? Can it be linked to libssl.so instead? This is a symlink present on Fedora, Debian, Ubuntu, and likely other distros which points to the correct installed 1.0.1k libssl and I think it will solve the issue, at least partially...

Nope, libssl.so should not be present by default on new systems as it's a development library. It's likely provided by openssl-devel.
As far as I know it's a Fedora packaging bug as libssl clearly has 1.0.0 as a soname, even if its version is 1.0.2d on my system:
```
$ objdump -x /usr/lib64/libssl.so | grep SONAME
  SONAME               libssl.so.1.0.0
```

**Comment by akien-mga** [comment]
It seems that Fedora consider defines a custom SONAME for openssl, see the topic of this file: http://pkgs.fedoraproject.org/cgit/openssl.git/tree/openssl.spec. As I know their packaging methods, I can imagine it was a useful change back then when they started doing it, and nowadays it's probably just obsolete nonsense. I guess we could try to make a bug report upstream to ask them to provide a libssl.so.1.0.0 symlink for libssl.so.10, but if we don't want to depend on them, we'd have to either:
* Hardcode a way to look for libssl.so.10 as a fallback if the libssl.so the engine was built against is not present (and bump this version when Fedora has a change of hearts).
* Link openssl statically, but I think that would be a bad idea as openssl is a very sensitive library with frequent security fixes, so linking a old version might mean linking against known vulnerabilities.
* Or don't enable openssl by default, so the issue would only affect users that really need the openssl functions; for such games, the lib could be bundled in the game directory (though that would be bad for the above-mentioned security reasons), or a symlink (potentially dangling) to the place where Fedora has this lib.

**Comment by adolson** [comment]
There is a fourth solution: everyone stop using Fedora! :P

**Comment by akien-mga** [comment]
> There is a fourth solution: everyone stop using Fedora! :P

Hehe. Better solution is likely to ask Fedora directly: https://bugzilla.redhat.com/show_bug.cgi?id=1277662

**Comment by q2dg** [comment]
@akien-mga :+1:

**Comment by akien-mga** [comment]
So, it's likely a wontfix as far as Fedora is concerned, so we'll have to find a solution ourselves.

The simplest workaround would be to disable openssl support by default on X11 in https://github.com/godotengine/godot/blob/master/platform/x11/detect.py#L65. WDYT @reduz?

**Comment by thecodethinker** [comment]
Is there any word on a fix for this? It's still an issue for me. I have to compile godot myself to get around it for the engine but all of the x11 exports also have this same issue.

**Comment by akien-mga** [comment]
> Is there any word on a fix for this? It's still an issue for me.

Sadly none for the time being, and as mentioned above the solution likely won't come from Fedora upstream. The best alternative we can think of currently would be to dump openssl and use something more lightweight like mbedtls (previously polarssl). Or link openssl statically, but we *don't want* to do that.

For the 2.0 release we could disable openssl support by default if we want to ensure that binaries run everywhere - we probably don't want developers working on Ubuntu and getting frustrated by all the Fedora users reporting that their game is broken. @reduz WDYT? We would of course have to mention it on the download page, with instructions on how to compile from source for people who need openssl support.

**Comment by techtonik** [comment]
> Or link openssl statically, but we don't want to do that.

Why?

**Comment by akien-mga** [comment]
> Why?

A couple of comments above:
> - Link openssl statically, but I think that would be a bad idea as openssl is a very sensitive library with frequent security fixes, so linking a old version might mean linking against known vulnerabilities.

But we do link statically against libssl on Windows and MacOSX, so if it's the only way to fix the Linux binaries thanks to Fedora's weird packaging we might end up doing that too.

**Comment by techtonik** [comment]
Is it possible to just make Godot download its required binary (and look for updates for it if needed)?

**Comment by techtonik** [comment]
@akien-mga is it possible to make Godot dynamically locate the binary if it is not found at expected location?

**Comment by reduz** [comment]
Fixed I think

**Comment by techtonik** [comment]
@reduz yes, it is fixed.

I see that the binary size increased on 10%
```
30851536 Jan 26 14:35 Godot_v2.0_beta_20160126_x11.64
33020136 Feb  5 15:56 Godot_v2.0_beta_20160205_x11.64
```
Did you compile OpenSSL statically?

**Comment by reduz** [comment]
yeah, it had to be compiled static like in the rest of the platforms.
Planning to eventually move to mbedtls which is smaller.

**Comment by techtonik** [comment]
@reduz - how hard is it to implement [dynamic loading](http://www.ibm.com/developerworks/library/l-dynamic-libraries/) for OpenSSL? Given that location of .so can be detected. Does Linux help to match API so that no surprises occur?

**Comment by akien-mga** [comment]
This is "fixed" as official binaries now use the bundled OpenSSL version built statically (*cringes*).
