### ISSUE TITLE
`Auto Mapping` and `Layers` for GridMap

### ISSUE THREAD

**Issue by HeadClot** [godotengine/godot#13920]
Hey Godot devs,

I have a bit of a feature request / enhancement (or two) for [Grid Maps](http://docs.godotengine.org/en/stable/learning/features/3d/using_gridmaps.html). Currently Grid maps require that we select each mesh individually each time. For example If i want a wall piece I need to manually select a wall piece. If I want a ground piece I need to manually select a ground piece. 

Auto Mapping - This should function similar to [TileED for Unity3D](https://www.youtube.com/watch?v=KzoLbF0v_Os). There are more videos on this tool on the same channel. Give them a look through to get an idea.

Layers - Think of this like Photoshop layers that allow for non destructive editing of a Grid Map. For example If I wanted to add trees to a level I could hit a button create or destroy a layer. There should also be the option to hide a layer from view. Being able to name and reorder layers would be nice as well for organization.

In my opinion this would greatly speed up workflow when using Gridmaps.

Hope I made sense,
- HeadClot

**Comment by Zylann** [comment]
Wouldn't layers be redundant to adding a second GridMap node? I do this too with tilemaps and it works fine.

**Comment by HeadClot** [comment]
Hey Zylann - Layers would just make it easier on the level designer.
Layers could just be creating, hiding or destroying another GridMap with a single button press. Which would be nice.

**Comment by bojidar-bg** [comment]
Just to mention it, layers-like functionality would be welcome for tilemaps too :wink:

**Comment by Zylann** [comment]
If layers are built into the node for editor workflow... would that involve more draw calls in the game still?

**Comment by HeadClot** [comment]
Hey Zylann - I honestly do not know - I am not familiar with the rendering side of Godot.

**Comment by KoBeWi** [comment]
> If layers are built into the node for editor workflow... would that still involve more draw calls in the game? (as in "stuff for editor use cases affects places where it isnt used such as the final game and ends up decreasing perf").

Multiple layers would be probably easier to optimize than mutliple Gridmaps/Tilemaps.

**Comment by Alzter** [comment]
If by Auto Mapping you mean AutoTile, I'm fully on board. If 2D tilemaps can have autotile, why can't gridmaps?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/114, as feature proposals are now tracked in the Godot proposals repository.

As for layers functionality, it's probably better achieved using multiple GridMaps like it's already done with TileMaps. That said, feel free to open a proposal on the Godot proposals repository as well.
