### ISSUE TITLE
Spatial raycast stops to collide detection on huge complex meshes

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#1392]
As the title say: when a complex meshes (like blender auto-generated landscape) is too spatially wide, the raycast of kinematic/rigidbody fail to detect it's collision.
This problem is not effected by the number of vertex/faces.. but only when the spatial scaled size

the small demo provided shows the problem mechanics.

http://tempsend.com/C65749CAB5/C6D1/smalldemo.zip
(press "1" to scale up/down and "2" to reset)

the collider stop working when the landscape mesh is upscaled +x100.... but return working when it grow down x99

== the problem is when a mesh reach the size of (landscape size) \* 100?
it looks like a decimal issue? (99+1... some sort of internal "millennium bug"?)

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
