### ISSUE TITLE
is_playing return always false when AnimationSprite is a child

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#13928]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64bit, Godot 3 beta

**Issue description:**
 `is_playing()` returns always false when AnimatedSprite is a child 

**Steps to reproduce:**
1. create a scene with a AnimatedSprite as root and as child
![image](https://user-images.githubusercontent.com/10463138/33528374-78688226-d85f-11e7-9209-561b2581ea31.png)
2. create a looping animation an both
3. create a script with this content
```
extends AnimatedSprite

func _ready():
	set_process(true)

func _process(delta):
	$is_playing.text = "is_playing: "+str(is_playing())
	$AnimatedSprite/is_playing.text = "is_playing: "+str($AnimatedSprite.is_playing())
```
![gif](https://user-images.githubusercontent.com/10463138/33528379-ace81142-d85f-11e7-9f1b-48dc0d464897.gif)

**Link to minimal example project:**
[animationSprite_bug.zip](https://github.com/godotengine/godot/files/1525028/animationSprite_bug.zip)

**Comment by reduz** [comment]
too much is_playing in this report..
