### ISSUE TITLE
Allow clamping for more than just floats/ints

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#13926]
While doing a tutorial from KidsCanCode, it dawned upon me that the `clamp()` function allows for floats/ints to be clamped, but not other variable types like `Vector2`s, `Vector3`s, or `Color`s that one might want to clamp to a range. What I'm proposing is to allow just that, as I don't imagine it would be too hard to implement and it would allow for code to be condensed a little more.

For example, for a `Vector2` named `position`, this functionality would allow this code snippet:
```gdscript
position.x = clamp(position.x, 0, get_viewport_rect().size.x)
position.y = clamp(position.y, 0, get_viewport_rect().size.y)
```
to be simplified to this:
```gdscript
position = clamp(position, Vector2(), get_viewport_rect().size)
```
(You can see how this might be useful for a `Color`, where there might be a lot more values to clamp.)

Ideally, I would like to see `clamp()` allowed for `Vector2`, `Vector3`, and `Color`, at the least. (Though other types similar in nature to those three might be nice to allow clamping for too!)

Hope this isn't too much to ask for. :)

**Comment by Zylann** [comment]
Similar to #8071

**Comment by LikeLakers2** [comment]
Not sure whether to close this then or leave it open, if it's just similar. :/

**Comment by poke1024** [comment]
It's not a duplicate in my opinion.

**Comment by NathanWarden** [comment]
If https://github.com/godotengine/godot/issues/8071 were implemented, wouldn't it cover this issue? If the API is to be consistent then it shouldn't just cover the clamp function, but should cover as many math functions as possible, right? It does seem like a duplicate to me. :)

**Comment by poke1024** [comment]
@NathanWarden I agree, but than there's Godot's reality, that the more you ask for, the less you generally get into the core :-)

**Comment by NathanWarden** [comment]
@poke1024 I suppose in some cases that's true, it is easier to ask for one thing (and it be implemented) than to ask for an entire library to be extended :)

**Comment by LikeLakers2** [comment]
@NathanWarden Adding onto what poke1024 said, I feel `clamp()` would be more useful than any of the other math functions. Not to mention, this would be a great short-term improvement, with the rest of the math functions being a long-term improvement.

**Comment by NathanWarden** [comment]
@LikeLakers2 Thanks for pointing that out, I can see some functions being more useful than others on a regular basis with other data types.

**Comment by aaronfranke** [comment]
So, Vector2 already has a function called `clamped()`, but this doesn't do the same as clamping a float or int. Vector2's `clamped` is basically `if vector.length() > val: vector = vector.normalized() * val`. What should be done about this? It would be confusing to have both `Vector2.clamp()` and `Vector2.clamped()` since they are similar names. Note: Vector3 does not have `clamped`.

**Comment by lawnjelly** [comment]
I'd vote for renaming the existing method .. limit sounds good or maybe limit_length. The old method is so specific I doubt it is used much outside the 2 mentions in the godot source. In fact there's an argument to get rid of the old method altogether.

**Comment by droqen** [comment]
Since discovering it a few months ago I've used Vector2's `clamped` in every project I have, so if there's an argument to get rid of it altogether I'd like to hear it

**Comment by Zylann** [comment]
I'm not sure `limit` conveys better info than `clamp`. Both sound the same and that still expects the user to "guess" they are referring to length, which is not *directly* a value of the vector. I'd just name this `clamp_length`, or `limit_length`.

**Comment by aaronfranke** [comment]
API proposal:

* Rename `Vector2.clamped` to `Vector2.limit_length`.

* Add `Vector3.limit_length` to be consistent with `Vector2`.

* Add `Vector2.clamp(min, max)` where `min` and `max` are of type `Vector2`.

* Add `Vector3.clamp(min, max)` where `min` and `max` are of type `Vector3`.

* Add `Color.clamp(min, max)` where `min` and `max` are of type `Color`.

    * Bonus idea: We could allow `Color.clamp` to have default values of `min = Color(0, 0, 0, 0)` and `max = Color(1, 1, 1, 1)`, since clamping a color to this range seems like it would be a very common operation.

    * Bonus idea part 2: With the above, you could override only `min` to `Color.black`, which would clamp to non-transparent colors, since black is `Color(0, 0, 0, 1)`.

Thoughts?

**Comment by LikeLakers2** [comment]
@aaronfranke I would of preferred to have it under the global `clamp()` function, but at the same time, your proposal is probably miles easier to implement. So no complaints from me. It sounds like a fine proposal.

**Comment by vickylance** [comment]
@aaronfranke  I really like the idea and I think that is how it has to be implemented. But however it will break the current API maybe for 4.0 as already a lot is broken in 4.0 API.

**Comment by Magodra** [comment]
Just looked for a vector version of the camp for a nice way to code a min, max constraint on a vector 3d. Would be nice if this made its way into the API at some point :)

**Comment by aaronfranke** [comment]
I created #45624 which allows clamping `Vector2`, `Vector2i`, `Vector3`, `Vector3i`, and `Color`, in addition to floats and ints.

**Comment by Xrayez** [comment]
I'd just like to clarify that #45624 won't actually help this issue as originally suggested by the author: https://github.com/godotengine/godot/issues/13926#issuecomment-628921126.

It makes sense to me as well that `clamp` could be made available as a GDScript method to work with `Variant` types.

See note by Zylann in https://github.com/godotengine/godot/issues/8071#issuecomment-288167150. It's likely that people still write wrappers for those functions to work in a general-purpose way.

GDScript 2.0 should also help the case of `float` clamping once it gets type optimizations, so this should no longer be a performance problem.

But having #45624 implemented per type is also just fine as denoted by LikeLakers2.

In any case, adding `clamp` as a GDScript method is a feature proposal which has to go through [GIP](https://github.com/godotengine/godot-proposals) now, so I think it's safe to close this issue now (especially given #45624 is there to help this).
