### ISSUE TITLE
unexpected behavior connecting Astar points

### ISSUE THREAD

**Issue by CarlosAlmarcha** [godotengine/godot#13925]
**Operating system:** Windows7 x64
  
**Issue description:**
I am having problems using the built-in Astar class for pathfinding in a 4x4 grid. When I use the get_point_path() function, the returned path doesn't seem to fit the connections between points I've established.
Checking previous steps I made, I've noticed each point in the grid has more connections that should have. So maybe that's causing the issue.

*It is worth mentioning in this game I only establish orthogonal connections (not diagonals)
*Also, since I'm creating a 2D game and Astar only support 3D coordinates, I translate the coordinates by simply add 0 values in all Vector3 z axis.

<a href="https://imgbb.com/"><img src="https://image.ibb.co/fyaVEb/grid.png" alt="grid" border="0"></a>
**Print log after connecting all the points in the grid:**
point number 0 (coordinate (0, 0)), has the folowing neighbours: [1, 4]
point number 1 (coordinate (1, 0)), has the folowing neighbours: [0, 2, 5, ***0***]
point number 2 (coordinate (2, 0)), has the folowing neighbours: [1, 3, 6, ***1***]
point number 3 (coordinate (3, 0)), has the folowing neighbours: [2, 7, ***2***]
point number 4 (coordinate (0, 1)), has the folowing neighbours: [0, 5, 8, ***0***]
point number 5 (coordinate (1, 1)), has the folowing neighbours: [1, 4, 6, 9, ***4***, ***1***]
point number 6 (coordinate (2, 1)), has the folowing neighbours: [2, 5, 7, 10, ***5***, ***2***]
point number 7 (coordinate (3, 1)), has the folowing neighbours: [3, 6, 11, ***6***, ***3***]
point number 8 (coordinate (0, 2)), has the folowing neighbours: [4, 9, 12, ***4***]
point number 9 (coordinate (1, 2)), has the folowing neighbours: [5, 8, 10, 13, ***8***, ***5***]
point number 10 (coordinate (2, 2)), has the folowing neighbours: [6, 9, 11, 14, ***9***, ***6***]
point number 11 (coordinate (3, 2)), has the folowing neighbours: [7, 10, 15, ***10***, ***7***]
point number 12 (coordinate (0, 3)), has the folowing neighbours: [8, 13, ***8***]
point number 13 (coordinate (1, 3)), has the folowing neighbours: [9, 12, 14, ***12***, ***9***]
point number 14 (coordinate (2, 3)), has the folowing neighbours: [10, 13, 15, ***13***, ***10***]
point number 15 (coordinate (3, 3)), has the folowing neighbours: [11, 14, ***14***, ***11***]

**Link to minimal example project:**
[Astar pathfinding on 2D 4x4 grid.zip](https://github.com/godotengine/godot/files/1524910/Astar.pathfinding.on.2D.4x4.grid.zip)

**Comment by kubecz3k** [comment]
@DmDerbin would be cool if you could elaborate, as far as I have seen the script uses `get_point_connections` which you have added, off-course I'm not sure if this is related to this issue. Thanks!

**Comment by DmDerbin** [comment]
> *Also, since I'm creating a 2D game and Astar only support 3D coordinates, I translate the coordinates by simply add 0 values in all Vector3 z axis.

`class MYAStar extends AStar:
	func get_point_position(id_point):
		var pos = .get_point_position(id_point)
		return Vector2(pos.x, pos.y)

	func get_closest_point(pos_v2):
		var id_point = .get_closest_point(Vector3(pos_v2.x, pos_v2.y, 0))
		return id_point

	func add_point(id_point, pos_v2, weight = 1.0):
		.add_point(id_point, Vector3(pos_v2.x, pos_v2.y, 0), weight)
`

**Comment by DmDerbin** [comment]
get_point_connections

I saw this "bug", but it's a bug (that's my subjective way), it's a feature, because the bidirectional connection is enabled =)

**Comment by CarlosAlmarcha** [comment]
That's the first thing I thought when I saw the list of connections.
That it showed more connections than expected simply because it listed connections in both directions. 
But I'm not so sure that's what's happening here.

You see, the results that I am getting are inconsistent:
Points 0, 3, 12, 15 , are all in the corners of the grid. Either way, wether taking into account bidirectional connections or not, they should have the same number of connections. But they don't.
- point number 0 (coordinate (0,0)), has the folowing neighbours: [1, 4]
- point number 3 (coordinate (3,0)), has the folowing neighbours: [2, 7, ***2***]
- point number 12 (coordinate (0,3)), has the folowing neighbours: [8, 13, ***8***]
- point number 15 (coordinate (3,3)), has the folowing neighbours: [11, 14, ***14***, ***11***]

**Comment by DmDerbin** [comment]
This is not a bug, because you get the connection not after all the passes through the points, but dynamically. At the moment of passage on the first points there is still no second connection, which is evident from the characteristic conclusion of the debug. If you make a 3 cycle with the output connections, then everything will be correct (I apologize for my bad english)

**Comment by kubecz3k** [comment]
@DmDerbin you are saying the reproduction project is written in wrong way?

**Comment by DmDerbin** [comment]
@kubecz3k
Yes, it is

**Comment by CarlosAlmarcha** [comment]
My apologies then. As I said, I'm getting some incorrect movement when calculating pathfinding, and these results seem suspicious enough to be a possible cause for it.
I'll close the issue now.

Thanks to all the people who took the time to check it out.
