### ISSUE TITLE
"no expand bottom panel when play project" Option is not available.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#13935]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**
"no expand bottom panel when play project" Option is not available.

**Steps to reproduce:**
1. play project
2. stop project
2. close output panel
3. play project
4. stop project
5. close output panel
6. play project
7. stop project
8. close output panel

**Link to minimal example project:**

**Comment by akien-mga** [comment]
There is, see the highlighted option:
![spectacle ab9553](https://user-images.githubusercontent.com/4701338/33544103-b942d6a0-d8d9-11e7-95fb-2938dcd3ff52.png)

**Comment by icnikerazah** [comment]
sorry , my fault
