### ISSUE TITLE
Changing render resolution mid game

### ISSUE THREAD

**Issue by jholstein** [godotengine/godot#13939]
Hello, I might be missing something but is there any way to change the resolution in game?

By this I mean when you set the project settings in godot for the display resolution, this changes the resolution the 3d game is rendered at.  

I would like to implement a method to change resolution while in game, such as how games like overwatch offer the resolution option as overall quality control. (As shown here https://i.imgur.com/0DEq988.jpg)

So far everything I have done seems to just change the size of the window while not affecting render resolution.

Thanks for the help.

**Comment by Calinou** [comment]
Viewport undersampling isn't built into the engine yet, but I was told that you could implement it yourself using a custom viewport.

**Comment by jholstein** [comment]
It seems that viewport.set_size(Vector2(w,h)) does what I need. But you need to adjust it in game after the viewport is loaded. Closing the issue.
