### ISSUE TITLE
Inspector not updating when changing values on Spatial nodes using gdscript

### ISSUE THREAD

**Issue by DonSkeleton** [godotengine/godot#13937]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windos 8.1 Pro x64
Godot 3.0.beta.build1

**Issue description:**

I wrote a plugin that is a dock with four buttons. Those four buttons reset the position, rotation, scale or all three properties to default for all currently selected nodes. 

The code works and the nodes are resetted (default position, scale and rotation) but for some reason the Inspector still shows the old values for the manipulated properties when I use a Spatial node. 
If I use a Node2D or CanvasItem node, the Inspector updates immediatly and shows the correct values.
In case of Spatial nodes, I first have to select another node and then go back to the previously selected Spatial node to see the correct values. It seems the Inspector doesn't refresh/update in case of Spatial nodes when the properties are changed through gdscript.

Here a picture of the Inspector for a MeshInstance node that I moved to (2, 2, 2) and then moved it back to (0, 0, 0) using my addon script:

![inspector_not_refreshing](https://user-images.githubusercontent.com/21103642/33530383-fdc976a4-d87e-11e7-96af-f5a32d46e67c.JPG)

**Steps to reproduce:**
In my attached example project:

1. Open the testscene.tscn
2. Select the MeshInstance node
3. Move the cube that is the MeshInstance node to somewhere other than (0, 0, 0), for example (2, 2, 2)
4. Press the "Translation" button in the "Tools" dock that comes with the example project
5. The MeshInstance node moves back to (0, 0, 0)
6. Inspector still shows (2, 2, 2) for the Translation property 
7. Try to edit the Translation property of the MeshInstance in the inspector and the popup will show the correct values (0, 0, 0)
8. Now select another node and then go back to the MeshInstance node, the Inspector now shows (0, 0, 0) for the Translation property

You can try the same with the Sprite and Button node to see that they don't have that problem.

**Link to minimal example project:**

[Inspector values not refreshing.zip](https://github.com/godotengine/godot/files/1525197/Inspector.values.not.refreshing.zip)

**Comment by bojidar-bg** [comment]
Looks like a bug..

Can you test if calling `property_list_changed_notify` on the object workarounds the issue?

**Comment by DonSkeleton** [comment]
Yep it works, the Inspector updates and shows the correct values. Will use the workaround for now, thanks.

**Comment by reduz** [comment]
This is expected, editor does not update by default, you have to do it manually.

**Comment by DonSkeleton** [comment]
@reduz 
I thought so too at first but as mentioned in my first post this is not the case for Node2D or Control nodes. The Inspector does update automatically after changing a property. So the behaviour is not consistent across different types of nodes. 

If I do:
`selected_node.translation = Vector3(0, 0, 0)`
on a Spatial node, I also have to call 
`selected_node.property_list_changed_notify()`
to update the Inspector.

For Node2D nodes
`selected_node.position = Vector2(0, 0)`
or for Control nodes
`selected_node.rect_position = Vector2(0, 0)`
is enough to change the property and update the Inspector. 

No need for calling 
`selected_node.property_list_changed_notify()`
