### ISSUE TITLE
ParticlesMaterial angle setting doesn't work as expected

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#13946]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot af27414b1c10173584539186e396668a899e06b2, any OS

**Issue description:**

It's documented that ParticlesMaterial's `angle` is `Initial rotation applied to each particle.`. In the past it actually applied the rotation along the particle's up axis. However, with current code it uses flags to determine what to do with the `angle` and the results are confusing and any combination of flags doesn't seem to lead to the desired effect of having particle rotated around its axis.

**Comment by kubecz3k** [comment]
From the context I assume it's about 3d particles

**Comment by kubecz3k** [comment]
@endragor is it not the same issue as #10182 ?

**Comment by endragor** [comment]
Yes, seems to be a duplicate. Closing then.
