### ISSUE TITLE
LLVM ERROR: Section too large, can't encode r_address (0x1000008) into 24 bits of scattered relocation entry

### ISSUE THREAD

**Issue by KenHuang0917** [godotengine/godot#13944]
Operating system or device - Godot version:
macOS High Sierra 10.13.1, Godot 2.1.4 stable, Xcode 9.1, iOS 11

Issue description (what happened, and what was expected):
After updated Xcode to version 9.1, I recompiled a Godot project which worked just fine with Xcode 8 and found this link error:

## scons: building terminated because of errors.

It only appeared on compilation for simulator, compiling for iDevice is ok.

Steps to reproduce:
Compile Godot with: "Scons platform=iphone tools=no bits=64 target=release ios_sim=yes" for Simulator

Thanks for helping!

**Comment by marcelofg55** [comment]
That's because you're compiling for x86, iOS 11 doesn't supports 32 bits anymore I believe.

**Comment by KenHuang0917** [comment]
Which means there is no way to compile for iOS simulator ?

**Comment by wombatstampede** [comment]
I noticed that the 2.1 branch can be compiled for the IOS simulator.
I replaced the ./platform/iphone/detect.py of the 2.1.4 release with the one from the "current" 2.1 branch (and did a "touch" on it). Then the build succeeded:
scons p=iphone target=release_debug ios_sim=yes

As far as I understood, the link time optimization option (-flto) was used in 2.1.4 stable for the "release_debug" target and meanwhile removed (unless forced via paramater).

But I'm an absolute beginner on XCode and iOS..

**Comment by KenHuang0917** [comment]
Thank you wombatstampede. Replacing detect.py with the one from 2.1 branch made the build succeed, but failed while running in the simulator. As you said, I had to download the old version of iOS simulator so that the Godot executable could run on it. I think marcelofg55 is right, iOS 11 doesn't supports 32 bits anymore.

**Comment by mhilbrunner** [comment]
Closing, as it doesn't look like we can do much about iOS 11 not supporting 32 bits :)
