### ISSUE TITLE
Remove slang and emoticons from editor UI and error messages

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#13950]
_bugsquad edit: first title of the issue was "Improve Godot editor professionalism"_

-----------

- [ ] Purge uses of words like "*[shit](https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=shit&type=Code)*", "*[fuck](https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=fuck&type=Code)*", "*[ass](https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=ass&type=Code)*", "*[retarded](https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=retarded&type=Code)*", "*[bitch](https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=bitch&type=Code)*", and "*[wtf](https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=wtf&type=Code)*" **ESPECIALLY** in user-facing UI, like error messages
- [ ] Improve error, UI and dialog messages, especially prompts on buttons like "Ok :(" and "..."
- [ ] Kill humor with fire, especially in user-facing stuff, this is mostly underway already for the docs, I think

**Comment by djrm** [comment]
why? what does it mean to be professional? i dont understand this mindset

**Comment by mhilbrunner** [comment]
If you are serious: because this turns people off and may mean I can't use Godot for teaching, at schools, or at work, because this is seen as unprofessional, childish and thus frowned upon.

**Comment by djrm** [comment]
also the links are hilarious, i never expected to find the word ass in a cert, should we also remove that, and we cant touch upstream comments.

do you have any evidence of your statements?

**Comment by djrm** [comment]
sorry but this is very opinionated, a agree at some point that it can be toned down, but not killed, there is no point

**Comment by mhilbrunner** [comment]
The point is that Godot wants to be a professional game engine, used in serious projects by companies, and seens to be as credible as any other engine.

Neither Unity nor UE4 will throw words like "shit" and "wtf" at you. Won't even get into "retarded".

**Comment by djrm** [comment]
have you seen the unity or unreal (well this maybe) source code?, you are even against "Ok :(" whats wrong with that, your are being very extremist

**Comment by Zireael07** [comment]
2 and 3 are not quite a big deal, but 1 is indeed a problem for anyone trying to demo Godot in a serious setting (work, school). It's quite easy to get a couple of error messages with wtf after exporting from 2.1 to 3.0.

**Comment by djrm** [comment]
at most i will agree to remove the vulgar language (since it may offend some people) in engine messages, humor will not hurt anyone and doesnt make something "unprofessional" if "proffesionalism" even means something.

**Comment by mhilbrunner** [comment]
That is not the point. The source code is not the biggest issue. Showing things like "shit" and "wtf?" to users is. (However, I'd argue that yes, even the source code could stand to have more comments and less cursing. Infantile humor gets old fast when digging through stuff.)

"Retarded" should just not be used, not in source code, not in messages, nowhere. Ever.

And "Ok :("? Honestly, it's like including Emojis or a rickroll vid somewhere. Yeah, all fun and games, but it just seems like amateur hour, part-time stuff made for fun. Like the docs humor, and that too was decided to get rid of for good reason.

And yes, I know at least two people IRL that got turned off by this, know at least one project that wen with another engine because of this and I will just not suggest Godot in serious projects while it liberally uses words like "retarded" and does all the other stuff.

You decide if that is the better outcome than just getting rid of that stuff.

**Comment by cbscribe** [comment]
There is source code and there's user-facing messages. I 100% agree the latter should avoid vulgarity, humor, or for that matter, ambiguity. What does "Ok :(" even mean?

Source code is another thing entirely. Have a look at the Linux source code sometime - this is what programmers do, even professional ones. It's invisible to the userbase, and hardly worth raising a fuss over. 

I also agree, there's no excuse for using derogatory language anywhere in the project. The two uses of "retarded" are easily removed with a PR.

**Comment by kubecz3k** [comment]
@mhilbrunner would be nice if we could have pointed out all the places when something like this is showed to the users in this thread (the best would be to have some small screens for each case)

**Comment by groud** [comment]
I agree with all points, as we should avoid being offensive to people, from any cultural origin. Indeed that implies removing bad words. :)
But to be honest, I did not even know there were some in she UI. It must be very hidden ^^(still it stays important)

**Comment by mhilbrunner** [comment]
@kubecz3k Agreed, just wanted to see if the community agreed with changing this before invesitng work.

**Comment by kubecz3k** [comment]
(Sorry for tag juggling, it was unintended)

**Comment by kubecz3k** [comment]
@mhilbrunner well to have healthy discussion it would be the best to see first what we are talking about :) I'm using editor a lot and I'm probably just get used to those things since I can't really recall if they are in the UI or not. Your 'for education use' argument  is very convincing in my eyes

**Comment by mhilbrunner** [comment]
@cbscribe Agreed with everything but the Linux part.

First, I'd argue Linux is used besides, not because of the attitude of the devs, and secondly Linux has a reputation worse than the reality on this. Yeah, there are curse words, but the source code is a lot bigger. 

At least anecdotally, the only times I stumbled upon stuff like that is in arcane driver sources, one line in a thousand containing such a comment.

For Godot, which has a comparatively small source (compare to Linux or even other engines), I seem to stumble upon "shit what is this why does this shit work Idk I don't what I did here" comments every other line while I barely find any useful comments at all. This yields quite a different feel when it comes to the source and the quality. (Yes, I'm exaggerating a little to make the point more clear)

**Comment by cbscribe** [comment]
Actually, it should be pointed out that some of this comes from thirdparty sources:

    /* crypto/rc2/rc2_skey.c */
    /* Copyright (C) 1995-1998 Eric Young (eay@cryptsoft.com)

and while it's only a comment, problems can arise when something's from an upstream source (though it doesn't seem this code is likely to be receiving updates any time soon).

**Comment by mhilbrunner** [comment]
I'd advise against changing upstream stuff because of this. (Or the cert, for that matter, though I don't think that was serious)

But you can always point to upstream for that when this gets discussed, for "retarded" in "our" code I have no defense :)

**Comment by cbscribe** [comment]
I use Godot in an educational environment - with 10-12 year-olds. We haven't run across anything user-facing. If we did, it would definitely be embarrassing. I had to reject Love2D a couple of years ago over this same kind of thing - but there it's not the source code, it's embedded in the whole ecosystem.

Frankly, if one of my students is going onto github and reading the C++ source code, I'm going to be more impressed than worried.

**Comment by Zireael07** [comment]
@kubecz3k: if you use 2.1.4 to export a project containing a node that's not present in 3.0 you'll get an error message upon saving the exported project in 3.0 saying something like "wtf is that class". I saw them with ColorFrame and Quad nodes, so I guess it'd be really quick to reproduce and get rid of. (People were using TestCube a lot too, and it's no longer in 3.0, so I expect this to be one of the most visible error messages with doubtful phrasing)

**Comment by mhilbrunner** [comment]
List of potentially user-visible things:
- When trying to add a node without a root node: `"Okay :("`
- When no OpenGL 3.3 support is present, log message and popup: `"... sorry:("`
- In networking, `perror("shit?");` may be user-visible? ([file](https://github.com/godotengine/godot/blob/bd282ff43f23fe845f29a3e25c8efc01bd65ffb0/drivers/unix/stream_peer_tcp_posix.cpp), [file2](https://github.com/godotengine/godot/blob/bd282ff43f23fe845f29a3e25c8efc01bd65ffb0/platform/windows/stream_peer_winsock.cpp))
- Global error `ERR_OMFG_THIS_IS_VERY_VERY_BAD` (appears in docs)
- Error `ERR_WTF`
- `perror("wtf: ");` in [rw_lock_posix.cpp](https://github.com/godotengine/godot/blob/bd282ff43f23fe845f29a3e25c8efc01bd65ffb0/drivers/unix/rw_lock_posix.cpp)
- `print_line("wtf askd to decompress.. "` in [image_compress_squish.cpp](https://github.com/godotengine/godot/blob/437fb12e1aa3135dc7fa336bd0a53036be649ce8/modules/squish/image_compress_squish.cpp)
- `ERR_PRINT("BUG, wtf was whence set to?\n");` in [audio_stream_opus.cpp](https://github.com/godotengine/godot/blob/00168e3e33f1ca266a4844c65b30e43eaeb9a965/modules/opus/audio_stream_opus.cpp) (and the same in audio_stream_ogg_vorbis.cpp)
- various `ERR_PRINT("NO LOG, WTF");`s in [shader_gles3.cpp](https://github.com/godotengine/godot/blob/bd282ff43f23fe845f29a3e25c8efc01bd65ffb0/drivers/gles3/shader_gles3.cpp)
- `Log.d("GODOT", "PAUSED BY ROAMING      WTF!?");` in [android/Godot.java](https://github.com/godotengine/godot/blob/b83c14db891cb2563930989c35d287d802a23f9d/platform/android/java/src/org/godotengine/godot/Godot.java)
- `Log.d("GODOT", "PAUSED FOR SOME STUPID REASON");` as above
- `Log.d("GODOT", "PAUSED BY STUPID USER");` as above
- `print_line("wtf class is disabled ...` in [packed_scene.cpp](https://github.com/godotengine/godot/blob/2b50dc5d4f0b9d0c6fd5463b5d89d17578b388ab/scene/resources/packed_scene.cpp)

**Comment by mhilbrunner** [comment]
Whats the best way to handle this? Send a PR that fixes all with a single commit?

**Comment by akien-mga** [comment]
> When no OpenGL 3.3 support is present, log message and popup: "... sorry:("

I don't see anything unprofessional in that one, especially since the message tells the user that we're not going to cleanly exit and that there's going to be a crash.

**Comment by mhilbrunner** [comment]
Yeah, I'll agree in that case, akien.

**Comment by silverweed** [comment]
+1 for all the points in the above list, save for the "ok :(", which I don't deem problematic in any way. (not a big deal to change it though)

**Comment by NathanWarden** [comment]
Yep, I 100% agree. Bad words should be removed. I don't think anybody contributes to Godot because they're there, but I can certainly see it turning people off by them being there.

**Comment by mhilbrunner** [comment]
I'll create a PR as soon as I know whether to do it as a single commit touching all those lines or if I have to split it somehow. :)

**Comment by akien-mga** [comment]
A single commit is fine.

**Comment by leoddd** [comment]
@silverweed The "Okay :(" is just really unhelpful, so it has no place to be there. The user would be just as smart about what just happened with or without it, so a better message is in order if anything.

Also yes, good discussion, thanks for bringing it up.

**Comment by marsmoon** [comment]
Seriously what is wrong with "Okay :("? It's not unprofessional nor offensive. Errors are sad for the users and this shows that we care about their feelings ;).

I agree that swear words should be removed from the UI, but I see nothing wrong with keeping them in the code. Programmers are humans too and they too need to laugh sometimes. I always think it's funny when I find stuff like that in the source, because it's unexpected. Of course it would be best if those comments could remain funny and at the same time be informative. That's an art! We write code mostly for other humans to use, so I think it's sometimes good to show that another human wrote it.
