### ISSUE TITLE
Changing Label to LineEdit makes its text can't be edited when the project is played

### ISSUE THREAD

**Issue by tam0705** [godotengine/godot#13955]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 Alpha 2 (I haven't tried Beta 1 yet but I didn't find any open/closed issues related to this one)

**Issue description:**

One day, I changed the type of a Label node to LineEdit to reduce time. When I ran the project, I can't edit the text of the LineEdit node, though its "editable" property is set to true. I tried making an original LineEdit node and it worked fine. I also tried changing Control and Node2D nodes to LineEdit, and they also worked fine.

**Steps to reproduce:**
1. Create a Label Node
2. Change its type to LineEdit
3. Run the project
4. Try to edit its text

**Comment by akien-mga** [comment]
I can confirm it on the current master branch (055c5600).

**Comment by AlexHolly** [comment]
maybe related to #11194

**Comment by reduz** [comment]
Seems like something fun to investigate, I would check the .tscn file to see if something odd is saved in there

**Comment by waldson** [comment]
I found the problem. The 'error' is that Mouse > Filter property is set to 'Ignore' in Label, but LineEdit needs to get mouse interaction to work. When the conversion is made, this property keeps its old value.  Changing this property to either 'Stop' or 'Pass' fix the problem. If it still needs fix, please give me instructions, so I can take a look.

**Comment by volzhs** [comment]
there should be a way to find out if a property is saved(changed) by user to handle properly this case i think.
@reduz is there a way to check if it's changed even if current value is same with default value of property?

**Comment by akien-mga** [comment]
Indeed, currently when we change a node's type, we try to port its compatible properties over to the new node type, but it doesn't take into account whether the properties were changed or not.

We'd need to do something like (pseudo code):
```
if (old_node.property.value == old_node.property.default_value) {
   new_node.property.value = new_node.property.default_value;
}
```
But I don't think we store such default value information currently.

**Comment by akien-mga** [comment]
Not release critical though, so removing from the 3.0 milestone (but a fix would still be very welcome).
