### ISSUE TITLE
Tutorial_instancing out of date, can't complete

### ISSUE THREAD

**Issue by songproducer** [godotengine/godot#1395]
*Instancing, Step by Step
To learn how to do instancing, let's start with downloading a pre-made scene.
Unzip this scene in any place of our preference. Then, add this scene to the project manager using the 'Import' option.*

The problem is the 'Import' option is completely different. Instead of the dialog box in the picture, when I choose 'Import' -> '3D Scene', I'm presented with a different dialog with numerous options and a 'source scene' and 'target path'.

No matter what I try I get an unhelpful error - 'Error importing scene.'

**Comment by UsernameIsAReservedWord** [comment]
Aren't you confusing the "Import / 3D scene" menu inside the editor, with the "Import"  button inside the **project manager** ?

The project manager is the first window that show up when you double-click godot. Below the "New project" button, there is the "Import" button.

**Comment by kubecz3k** [comment]
I seems like the author of the issue misunderstood the tutorial (mistaken project manager window with the import option of the editor). Archiving.
