### ISSUE TITLE
Bullet engine RigidBody not sleeping correctly

### ISSUE THREAD

**Issue by HardCockJones** [godotengine/godot#13952]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64 bit
Godot 3.0 beta 1

**Issue description:**
Rigid bodies, when using Bullet engine (they behave properly in GodotPhysics), do not go to sleep when their velocity falls to ~0 and other forces cease. If you set the sleep variable from the remote view, the engine automatically forces it back to false. Setting sleeping from code does however force the rigidbody to sleep if they aren't moving or colliding with anything at all, but if the rigidbody is colliding with something else like a staticbody/another rigidbody then the sleeping variable is forced to false even if its velocity is ~0 and there arent any other bodies or outside forces interacting with it. Maybe this behavior is intended and I'm missing something? But I feel that they should automatically return to a sleeping state after a physics frame of zero velocity/ no outside forces even if they are colliding with another body as that is how they behave in GodotPhysics.

**Link to minimal example project:**
In this sample project there are 3 cubes
StartSleepingEditor is set to sleep from the editor, but is forced awake by the engine even though its floating not touching anything. It never returns to sleep
StartSleepingCode is the only body that actually sleeps
FallingBody has a script that should force it to sleep after it falls and stops on the static body, but its forced awake as well and never returns to sleep
[SampleProject.zip](https://github.com/godotengine/godot/files/1526077/SampleProject.zip)

**Comment by kubecz3k** [comment]
@HardCockJones As  I understand "can_sleep" flag is set to true on those bodies?
cc @AndreaCatania

**Comment by HardCockJones** [comment]
Yes, its set to true on them

**Comment by AndreaCatania** [comment]
I'll check it soon, however you name @HardCockJones...

**Comment by AndreaCatania** [comment]
Fixed #14965
