### ISSUE TITLE
Nameless script file and weird behavior around script file generation

### ISSUE THREAD

**Issue by ronroniv** [godotengine/godot#13965]
**OS**: Windows 7 64bit
**Godot Version**: 3.0 beta1

It's possible to make a script without name (".gd") in editor. I'm not sure this is a good thing.

Also I found some (unrelated) weird behavior while playing around this. This occurs whether a script has name or not: 
* Make a non-built-in script file in editor.
* Manually remove the file in your file manager.
* Make another script file **with the same name**.
* Then Godot will make two scripts -- a script file you asked for and a nameless built-in script.
  * If you made the script via Attach Node Script dialogue, Godot will attach the built-in script to the node while seemingly ignoring the non-built-in one.
  * If you made the script via Script Editor, the built-in script goes nowhere. But you can save it manually as a file it seems.

I guess this behavior is so obscure that probably will bother nobody but I think it's worth reporting anyway.

**Comment by reduz** [comment]
@willnationsdev can you check this one?

**Comment by willnationsdev** [comment]
Yeah, I'll look into it.

**Comment by willnationsdev** [comment]
I haven't been able to recreate the other bug, so I am thinking that this Issue can be closed:

If you create a script BY attaching it to a Node in your scene, and THEN you delete the script from the project, the original copy of the GDScript text is deleted, but the node still has the script. To preserve the data, the Editor shifts to storing it as an inlined script in the scene. However, creating another script with the same name will never replace the code on the Node in the scene, so there is no perplexing movement of script data happening.

1. If you create the second script, anywhere, then it will simply make another script file, without affecting the built-in script. This is intended behavior.
2. If you click the "Attach Script" button with the built-in one already on the Node, the ScriptCreateDialog will give you an error when it validates the Inherits field, saying that the built-in script's name doesn't represent a valid inheritance path. Again, intended behavior.
3. The only way to switch the node's script around would be to manually remove the built-in script that was preserving the initial deletion for the script in the scene and then follow it up with manually attaching or creating the second script on the Node. Again, intended behavior.
