### ISSUE TITLE
Visual scripting editor panning & zooming : strange behaviour

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#13968]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
linux mint 18.2 64 bits. godot master 

**Issue description:**

Panning seems buggy (with my mouse milddle button), often the canvas move to the right.
And zooming is not possible (at lest with my mouse wheel)

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by kubecz3k** [comment]
To zoom you need to click + - icons in top left (mouse wheel was never programmed to zoom in graph - maybe the behavior should be changed) 
Also was unable to reproduce middle mouse pan issue on af27414b1c10173584539186e396668a899e06b2 in Ubuntu 17.04

**Comment by turtletooth** [comment]
Can your mouse wheel be used as a horizontal scroll (does the wheel tilt side to side)?  I often accidentally trigger scrolling when I use my middle mouse wheel - but only because my mouse wheel can pan horizontally.

**Comment by matrem** [comment]
@turtletooth Yes you're right that's the problem. is there a way to disable this behaviour ? Yet I can click on left and right button to emulate middle click...
