### ISSUE TITLE
Cancelling and restarting download of export templates throws an error

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#13963]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64 - Godot 3 beta1

**Issue description:**

If the download of templates is stopped, you get an error if you immediately try to download them again. 

**Steps to reproduce:**
- Open "Manage Export Templates" window
- Click on Download
- Click on a mirror
- Click on Close on the download window
- Click again on Download
- Click on any mirror
An error saying it couldn't get the url will be shown. A workaround is closing the "manage export templates" and opening it again.
Note: this should probably be a separate issue but the window is not really modal. Clicking anywhere on the editor will close the download window and you have to start the download again.

**Link to minimal example project:**

![image](https://user-images.githubusercontent.com/526829/33559521-d462008e-d8eb-11e7-9919-eadd9a0f703e.png)

**Comment by MoraleIsNone** [comment]
Not a high priority imo, voting to close this

**Comment by noidexe** [comment]
@MoraleIsNone I hope you can sort out whatever is going on in your life that's making you so angry.

**Comment by Calinou** [comment]
@noidexe Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by noidexe** [comment]
Checked on 3.2.2b4 win64 and it seems solved. Both the window not being modal and the restarting of downloads. 

Thanks a lot!

**Comment by Calinou** [comment]
@noidexe Thanks for replying :slightly_smiling_face: Closing as resolved.
