### ISSUE TITLE
Visual scripting : "change may be lost" when editing a node

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#13970]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
linux mint 18.2 master

**Issue description:**

"change may be lost" is displayed when editing a node of the visual script, but why ? I only edit a script on a spatial node of my current scene.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by bojidar-bg** [comment]
Can confirm.

**Comment by kubecz3k** [comment]
I was unable to reproduce in af27414b1c10173584539186e396668a899e06b2, can you provide some simple scene or reproduction steps? Maybe some [inheritance] / [instanced node editing] is needed to reproduce?
