### ISSUE TITLE
Icelandic translation

### ISSUE THREAD

**Issue by johannesgunnar** [godotengine/godot#13972]
I am interested to translate the Godot engine interface to Icelandic. Could somebody with the correct access rights add Icelandic to the available languages on [hosted.weblate.org](https://hosted.weblate.org/projects/godot-engine/godot/)?

**Comment by akien-mga** [comment]
You should be able to do it yourself once logged it, there's a "Start new translation" button at the bottom of the page:
![spectacle b11590](https://user-images.githubusercontent.com/4701338/33570691-f4edc5b2-d92d-11e7-85df-49d5bb25c372.png)

**Comment by johannesgunnar** [comment]
Ah my bad! I must have misunderstood the [Translation readme](https://github.com/godotengine/godot/blob/master/editor/translations/README.md).

Thank you very much. [Icelandic translation](https://hosted.weblate.org/projects/godot-engine/godot/is/) has been created now.

**Comment by akien-mga** [comment]
Oops :) Now fixed.
