### ISSUE TITLE
Dragging a number field in material editor eats the cursor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#13988]
Godot 3.0 beta 1
Windows 10 64 bits

Same as https://github.com/godotengine/godot/issues/3196, just happened for me in beta 1 while dragging SpatialMaterial/Rim/Tint.

**Comment by reduz** [comment]
All this logic for range drag is here:
https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L2418

Feel free to give it a check/review.

**Comment by mortem-malum** [comment]
I cannot seem to replicate this bug on beta 1 or a dev build. Could it be possible that this bug is due to a driver or other systems related error?

**Comment by Zylann** [comment]
@mortem-malum did you specifically tried on the SpatialMaterial/Rim/Tint property?

**Comment by mortem-malum** [comment]
Yes with multiple objects and scenes.

**Comment by mortem-malum** [comment]
But reduz's suggestion on #3196 would be a good if this is system specific.

**Comment by Zylann** [comment]
I tried again with master on the same field and couldn't reproduce... maybe it's random, or was fixed by luck?

**Comment by akien-mga** [comment]
Seems like the same as #15351? Let's close as duplicate of the latter which is more detailed.
