### ISSUE TITLE
Strange rim light behaviour

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#13986]
Godot 3.0 beta 1
windows 10 64 bits
nVidia 940M

I opened a project I made in alpha 2, and I noticed two things that were fine before, but became wrong in alpha 1:
- Rim light became brighter
- Objects with a high roughness become nearly unshaded even with a rim of 0.2
- It flickers in some areas of my level (which is made of a single big mesh).

Here is a video showing this:
https://www.youtube.com/watch?v=ScK9VOFtKtE&feature=youtu.be

It flickers the most if I set a roughness of 1 (but also makes my entire level uniformly brown).

If I instance a projectile which has an emissive material, it also flickers:
https://www.youtube.com/watch?v=dpyZKxgdPMo&feature=youtu.be

**Comment by Zylann** [comment]
It seems to fix flickering when I move around in the editor, but the scene still flickers when I fire my emissive projectile.

**Comment by reduz** [comment]
the rim issue should be fixed, so i guess you will have to create a demo
project for this one

**Comment by reduz** [comment]
nevermind, it should be finally fixed now
