### ISSUE TITLE
Strange 2D in 3D behavior

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#13987]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master 5938466c848becb269f002191901487135e39ce3

**Issue description:**

**edit**: the regular sprite3d problem was solved.

using a viewport texture in a sprite3d fills the sprite3d with solid black, it was working before, but the produced image was SRGB,

~~the sprites3D still are SRGB~~

as shown here

![screenshot from 2017-12-04 18-30-38](https://user-images.githubusercontent.com/1103897/33583822-e4fd8e50-d921-11e7-9f88-a38878f44e52.png)

the top left is from a viewport container,

the center is a sprite3d with texture set from viewport

the right is a regular sprite3d

**Steps to reproduce:**

**Link to minimal example project:**

[vp_test_2.zip](https://github.com/godotengine/godot/files/1529259/vp_test_2.zip)

**Comment by reduz** [comment]
A MeshInstance with a QuadMesh works fine, so it's probably related to some setting in the 3D sprite materials:

https://github.com/godotengine/godot/blob/master/scene/resources/material.cpp#L1552

That mentioned, this will most likely not work with a Sprite3D without a material override, because you need to force the "albedo as RGB" property of the material for it to look good.

**Comment by djrm** [comment]
@reduz i tested with a material override  and directly setting the albedo texture, and it still the same, do you think it really is a sprite3D material issue.

**Comment by djrm** [comment]
@reduz i tested with a material override  and directly setting the albedo texture, and it still the same, do you think it really is a sprite3D material issue.

**Comment by Th0r12356** [comment]
Confirming this issue.
First everything seems to be working fine.
![2017-12-08-202016_1600x900_scrot](https://user-images.githubusercontent.com/33563732/33781850-7919b820-dc56-11e7-929b-eef2c35d2008.png)
But on launching:
![2017-12-08-203107_1600x900_scrot](https://user-images.githubusercontent.com/33563732/33781961-ee6d84f8-dc56-11e7-8906-8091ea030ab7.png)

In different approaches using Sprite3D, MeshInstance, ViewportContainers and changing materialoverride/srgb/albedo-settings  i still get the same result. BUT, the buttons are still clickable =)

same thing on changing or reloading the scene and sometimes getting: ERROR: get_size: Condition ' !vp ' is true. returned: Size2()

**Comment by reduz** [comment]
I just can't figure out what's wrong with this, it doesn't make any sense.
