### ISSUE TITLE
Suggestion: Store minimum engine version in engine.cfg

### ISSUE THREAD

**Issue by jscheel** [godotengine/godot#13984]
This would prevent someone from trying to open a 3.x game in 2.x. I figured something for this already existed, but I haven't seen it. Feel free to close if I'm just missing it.

**Comment by Sslaxx** [comment]
Note that 3.0 uses a different filename anyway - `project.godot`.

**Comment by jscheel** [comment]
@Sslaxx ah, blerg, that makes sense
