### ISSUE TITLE
Edit Group for multiple nodes at the same time

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#13997]
It would be nice if it was possible to select multiple Nodes and set group for all of them togheter

Example of what happened: i created bounds for a map and i wanted to put them all in a group. Had to manually set groups for each Node.

Bonus: It would be nice if Groups were managed with a separate windows, where you can add groups, and then if you assingn a Node to a Group you'd have a drop down menu, to avoid misspelling related bugs.

**Comment by groud** [comment]
So true, this is really annoying
