### ISSUE TITLE
Default values in the editor setings are broken.

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#13995]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux, godot3 tip 03c1b6be23009ca67eb585783ec0f76d9c535c88

**Issue description:**
 Even after 
  rm -rf ~/.local/share/godot ~/.config/godot

and creating a new project, some of the editor settings are marked as changed.

After a clicking at the ↺ 'revert to default' button

:bug: fist time godot crashed in an endless loop
```
EditorSettings::_get - Warning, not found: text_editor/completion/callhint_tooltip_offset
EditorSettings::_get - Warning, not found: text_editor/completion/put_callhint_tooltip_below_current_line
…
```

:bug: the second time it out of blue started to import my whole
home directory. I could only stop that with `xkill` (and  `find -name '*.import' -print0 | xargs -0 rm`)

I didn't dare to test it again ;)

**Comment by akien-mga** [comment]
cc @djrm

**Comment by djrm** [comment]
@capnm you need to post exactly which settings appear as changed, some are ok that way (since they were actually changed by the engine).

**Comment by djrm** [comment]
also your two problems seem to be unrealted, editor settings has nothing to do with import file (thats project specific), also notice that there are more configuration places since the new config organization, so you have to remove all of those to have a proper test.

**Comment by capnm** [comment]
As I said, godot started being mad just after pressing on some of the ↺ buttons.
(it's clear, that godot's auto-import-o-matic feature is unrelated, but it happened anyway.)

I removed everything in ~/.local/share/godot and ~/.config/godot
What else should I delete?

![grafik](https://user-images.githubusercontent.com/4047289/33632849-383be0c4-da0f-11e7-80fa-f5730182e71e.png)
![grafik](https://user-images.githubusercontent.com/4047289/33632908-669563b4-da0f-11e7-925c-e30f40e38bb6.png)
![grafik](https://user-images.githubusercontent.com/4047289/33632954-82787d00-da0f-11e7-8be9-b587b70eb9bc.png)
![grafik](https://user-images.githubusercontent.com/4047289/33633014-b386bb64-da0f-11e7-80e8-f2726a310333.png)

**Comment by djrm** [comment]
the text editor ones, are fine, they are changed because of the adaptive theme. the rest im not sure.

also please include your reproduction steps, whats the real problem here, the fact that those values are changed, the crash or the import of you home dir. im asking you because im unable to reproduce this issue, so you might be reverting a specific setting because at least for me it doesnt happen with the colors at least.

**Comment by capnm** [comment]
Hmm, I did exactly this (linux): 
```
rm -rf ~/.local/share/godot ~/.config/godot
godot
dialog [cancel]
New Project -> Create dir -> /tmp/New Game Project
[create]
```
and opened the Editor -> Editor settings

**Comment by capnm** [comment]
I have built a clean godot build from 7b02f5591d2a4c4d2d7da723b1303a99b6c4f168 and I can no longer reproduce the crash.

**Are some of the editor settings saved in the project folder?**
In a project created a last week, after clicking at some ↺ I see this in the log
(but I couldn't trigger a crash so far):
```
ERROR: get_edited_scene_root: Index current_edited_scene=-1 out of size (edited_scene.size()=0)
   At: editor/editor_data.cpp:607.
EditorSettings::_get - Warning, not found: text_editor/cursor/background_color
EditorSettings::_get - Warning, not found: text_editor/cursor/completion_background_color
EditorSettings::_get - Warning, not found: text_editor/cursor/completion_selected_color
EditorSettings::_get - Warning, not found: text_editor/cursor/completion_existing_color
EditorSettings::_get - Warning, not found: text_editor/cursor/completion_scroll_color
EditorSettings::_get - Warning, not found: text_editor/cursor/completion_font_color
EditorSettings::_get - Warning, not found: text_editor/cursor/caret_color
EditorSettings::_get - Warning, not found: text_editor/cursor/caret_background_color
EditorSettings::_get - Warning, not found: text_editor/cursor/line_number_color
EditorSettings::_get - Warning, not found: text_editor/cursor/text_color
EditorSettings::_get - Warning, not found: text_editor/cursor/text_selected_color
EditorSettings::_get - Warning, not found: text_editor/cursor/keyword_color
EditorSettings::_get - Warning, not found: text_editor/cursor/base_type_color
EditorSettings::_get - Warning, not found: text_editor/cursor/engine_type_color
EditorSettings::_get - Warning, not found: text_editor/cursor/function_color
EditorSettings::_get - Warning, not found: text_editor/cursor/member_variable_color
EditorSettings::_get - Warning, not found: text_editor/cursor/comment_color
EditorSettings::_get - Warning, not found: text_editor/cursor/string_color
EditorSettings::_get - Warning, not found: text_editor/cursor/number_color
EditorSettings::_get - Warning, not found: text_editor/cursor/symbol_color
EditorSettings::_get - Warning, not found: text_editor/cursor/selection_color
EditorSettings::_get - Warning, not found: text_editor/cursor/brace_mismatch_color
EditorSettings::_get - Warning, not found: docks/filesystem/relationship_line_color
```

**Comment by akien-mga** [comment]
Can you still reproduce this in the current master branch? There have been different fixes to EditorSettings since then.

**Comment by capnm** [comment]
On current tip b1ab44aa05994a19f0bae5e700c4007b870a8ecf

1) rm -rf /.local/share/godot ~/.config/godot
2) create a new project
3) open editor settings

![grafik](https://user-images.githubusercontent.com/4047289/34630651-60a5160e-f26d-11e7-879d-473336fd4652.png)

![grafik](https://user-images.githubusercontent.com/4047289/34630692-89f5b72a-f26d-11e7-88f6-8712492cef7a.png)

4) Click at one ↺ in the middle

```
EditorSettings::_get - Warning, not found: text_editor/completion/callhint_tooltip_offset
EditorSettings::_get - Warning, not found: text_editor/completio/put_callhint_tooltip_below_current_line
```

![grafik](https://user-images.githubusercontent.com/4047289/34630805-ef2865ca-f26d-11e7-910f-6ca9f11f355a.png)

**Comment by akien-mga** [comment]
Right, that's what @djrm referred to as:
> the text editor ones, are fine, they are changed because of the adaptive theme.

But they're not fine, since they can disappear when reverted. Those settings are badly defined, the adaptive theme can update them if need be, but they should be defined beforehand.

**Comment by djrm** [comment]
maybe it was broken by this 4b0f075e9584b20f23f6f16f29ea078d8bd69650? im not sure, i could not reproduce it at the time of my comment.

**Comment by djrm** [comment]
also they were defined the same way every other setting is defined before the mentioned commit.

**Comment by volzhs** [comment]
I will take a look
