### ISSUE TITLE
shader from old scene still visible

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#1400]
In 2D, edit a shader's code.  With the code window still open, open a new scene.  Sometimes (but not always?), the shader window remains visible.  Changes to this code then have no effect.  When the scene with the shader is reloaded, all changes that were made in the out-of-place code window are lost.

**Comment by akien-mga** [comment]
Can you still reproduce this issue in the current master branch / nightly builds?

**Comment by akien-mga** [comment]
Ping.

**Comment by vnen** [comment]
Tried this and the shader code window is kept open even when changing scenes and closing the original scene. The code changes are kept too but not save, so if you close the project and open again without saving the original scene those changes are lost.

**Comment by MarianoGnu** [comment]
I did some changes to shader editor, but didn't see this issue, can you conform this is still happening?

**Comment by akien-mga** [comment]
As per the above comment, assuming it has been fixed with the various changes @MarianoGnu did to the shader editor. Please comment if it's not the case, so that the issue can be reopened.
