### ISSUE TITLE
AudioStreamPlayer does not pause

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#14009]
I have an AudioStreamPlayer in a Singleton and it will not pause. Setting pause_mode to inherit or stop makes no difference. Other nodes in the singleton do pause.

Godot 3.0 beta1

**Comment by vnen** [comment]
Doesn't matter if it's in a singleton, audio nodes don't pause when the tree is paused. I noticed this is the same in 2.1, so I wonder what would be the preferred behavior.

**Comment by reduz** [comment]
indeed, it seems most people expects streams to not pause, but i'm not sure what is best

**Comment by vnen** [comment]
I'd say this isn't a bug, since it was meant to be like this, But it could be changed if people expect to work like that.

**Comment by letheed** [comment]
Could streams default `pause_mode` to `PAUSE_MODE_PROCESS` instead of `PAUSE_MODE_INHERIT`?

I don't think they should be pausing by default, just that people should be able to pause them if they want to.

**Comment by reduz** [comment]
kicking to 3.1 as trying to avoid new features
