### ISSUE TITLE
ImageTexture doesn't load images anymore

### ISSUE THREAD

**Issue by dploeger** [godotengine/godot#14004]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS 10.13.1, Godot 3.0.beta.build1

**Issue description:**
In Godot < 3 in the ImageTexture, the load button accepted loading image files. This is not working anymore in Godot 3. Only resources are available there.

If this is the expected behaviour now: How can I create an image texture using the editor and set flags like repeat? StreamTexture doesn't have that option and I can not load an StreamTexture as a ressource in an ImageTexture. If that *should* work, I will create a separate bug for that.

**Steps to reproduce:**

* Create a new Sprite
* Select Texture
* Select "New ImageTexture"
* Select Image
* Select Load

➡️ Only .res and .tres-files are accepted, no image files.

**Comment by Hinsbart** [comment]
The image flags are now specified in the import tab. Just select the image in the Filesystem dock, then open the Import tab.
