### ISSUE TITLE
Failed building Android Template on Windows

### ISSUE THREAD

**Issue by fredlim** [godotengine/godot#1403]
I download the latest Android SDK and NDK, unzipped and add the ANDROID_HOME and ANDROID_NDK_ROOT, but got errors when building the template.

```
E:\Users\___\Documents\GitHub\godot>scons platform=android
scons: Reading SConscript files ...
Godot Android!!!!!

scons: warning: Ignoring missing SConscript 'drivers\gles1\SCsub'
File "E:\Users\___\Documents\GitHub\godot\drivers\SCsub", line 13, in <module>
scons: done reading SConscript files.
scons: Building targets ...
F:\android-ndk-r10d/toolchains/arm-linux-androideabi-4.8/prebuilt//windows/bin/a
rm-linux-androideabi-g++ /Foplatform\android\os_android.os /c platform\android\o
s_android.cpp /TP -DNO_STATVFS -MMD -MP -MF -fpic -ffunction-sections -funwind-t
ables -fstack-protector -fvisibility=hidden -D__ARM_ARCH_7__ -D__GLIBC__ -Wno-ps
abi -march=armv6 -mfpu=neon -mfloat-abi=softfp -ftree-vectorize -funsafe-math-op
timizations -fno-strict-aliasing -DANDROID -Wa,--noexecstack -DGLES2_ENABLED -D_
DEBUG -g1 -Wall -O0 -DDEBUG_ENABLED -fno-exceptions -DNO_SAFE_CAST -DDEBUG_MEMOR
Y_ALLOC -DSCI_NAMESPACE -DDEBUG_MEMORY_ALLOC -DANDROID_ENABLED -DUNIX_ENABLED -D
NO_FCNTL -DMPC_FIXED_POINT -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED
 -DVORBIS_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP
_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DOP
ENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore\math -Itools -Idrivers -
I. -Iplatform\android -IF:\android-ndk-r10d\platforms\android-15\arch-arm\usr\in
clude -IF:\android-ndk-r10d\sources\cxx-stl\gabi++\include -IF:\android-ndk-r10d
\sources\cpufeatures -Idrivers\builtin_openssl2 -Iplatform\android\vorbis -Idriv
ers\builtin_openssl2\crypto -Idrivers\builtin_openssl2\openssl -Idrivers\builtin
_openssl2\crypto\evp -Idrivers\builtin_openssl2\crypto\asn1 -Idrivers\builtin_op
enssl2\crypto\modes
=====
arm-linux-androideabi-g++: error: /Foplatform\android\os_android.os: No such fil
e or directory
arm-linux-androideabi-g++: error: /c: No such file or directory
arm-linux-androideabi-g++: error: /TP: No such file or directory

=====
scons: *** [platform\android\os_android.os] Error 1
scons: building terminated because of errors.
```

**Comment by volzhs** [comment]
I have exact same problem.

**Comment by lengyue524** [comment]
I have exact same problem too

**Comment by KillerJaguar** [comment]
Getting this same problem when trying to compile to Android as well

**Comment by reduz** [comment]
Are you guys trying to compile on windows?


On Tue, Jun 23, 2015 at 12:15 PM, Robert Hernandez <notifications@github.com

**Comment by KillerJaguar** [comment]
Yes

**Comment by reduz** [comment]
I haven't succeeded at building on Windows either, so help is appreciated.
The compilers are supposed to be the same as in Linux but they fail with
different and weird errors

On Tue, Jun 23, 2015 at 12:26 PM, Robert Hernandez <notifications@github.com

**Comment by KillerJaguar** [comment]
I do notice that Windows uses '/' for command line options rather than '-', so that might be affecting it. It's trying to open a folder called "/Foplatform\android\os_android.os".

**Comment by punto-** [comment]
It looks like you have the environment variables setup for a native windows
build, using the VS compilers, so it's trying to use visual studio style
commandline options like /TP and stuff like that. Try running from a normal
cmd.exe with no extra environment.

On Tue, Jun 23, 2015 at 12:31 PM, Robert Hernandez <notifications@github.com

**Comment by KillerJaguar** [comment]
That fixed the first problem, but now arm-linux-androideabi-g++.exe crashes during execution

**Comment by KillerJaguar** [comment]
Compiling worked on my desktop (was on my laptop), except now I get this:

```
F:\Programs\Godot\Source>scons p=android
scons: Reading SConscript files ...

MSVC not detected, attempting Mingw.
- gcc detected.
Godot Android!!!!!
scons: done reading SConscript files.
scons: Building targets ...
C:\Android\android-ndk-r10b/toolchains/arm-linux-androideabi-4.8/prebuilt//windo
ws-x86_64/bin/arm-linux-androideabi-as -o drivers\png\filter_neon.android.debug.
o drivers\png\filter_neon.S
=====
drivers\png\filter_neon.S: Assembler messages:
drivers\png\filter_neon.S:40: Error: bad instruction `elf .type png_read_filter_
row_sub4_neon,STT_FUNC'
drivers\png\filter_neon.S:54: Error: bad instruction `elf .size png_read_filter_
row_sub4_neon,.-png_read_filter_row_sub4_neon'
drivers\png\filter_neon.S:56: Error: bad instruction `elf .type png_read_filter_
row_sub3_neon,STT_FUNC'
drivers\png\filter_neon.S:80: Error: bad instruction `elf .size png_read_filter_
row_sub3_neon,.-png_read_filter_row_sub3_neon'
drivers\png\filter_neon.S:82: Error: bad instruction `elf .type png_read_filter_
row_up_neon,STT_FUNC'
drivers\png\filter_neon.S:93: Error: bad instruction `elf .size png_read_filter_
row_up_neon,.-png_read_filter_row_up_neon'
drivers\png\filter_neon.S:95: Error: bad instruction `elf .type png_read_filter_
row_avg4_neon,STT_FUNC'
drivers\png\filter_neon.S:114: Error: bad instruction `elf .size png_read_filter
_row_avg4_neon,.-png_read_filter_row_avg4_neon'
drivers\png\filter_neon.S:116: Error: bad instruction `elf .type png_read_filter
_row_avg3_neon,STT_FUNC'
drivers\png\filter_neon.S:149: Error: bad instruction `elf .size png_read_filter
_row_avg3_neon,.-png_read_filter_row_avg3_neon'
drivers\png\filter_neon.S:167: Error: bad instruction `elf .type png_read_filter
_row_paeth4_neon,STT_FUNC'
drivers\png\filter_neon.S:188: Error: bad instruction `elf .size png_read_filter
_row_paeth4_neon,.-png_read_filter_row_paeth4_neon'
drivers\png\filter_neon.S:190: Error: bad instruction `elf .type png_read_filter
_row_paeth3_neon,STT_FUNC'
drivers\png\filter_neon.S:225: Error: bad instruction `elf .size png_read_filter
_row_paeth3_neon,.-png_read_filter_row_paeth3_neon'

=====
scons: *** [drivers\png\filter_neon.android.debug.o] Error 1
scons: building terminated because of errors.
```

**Comment by reduz** [comment]
I think at some point i got to the same place (neon error) and have no idea
why it happens.

**Comment by reduz** [comment]
maybe upgrading libpng should be attempted

**Comment by r3010** [comment]
at the start sorry for my English (this entry will google translator more than my skills),
and no knowledge of programming because I am only a graphic :)

i think i had a similar problem as fredlim, volzhs and lengyue524
solution for me was to change the name of a directory in NDK
from
\toolchains\arm-linux-androideabi-4.8\prebuilt\windows
to
\toolchains\arm-linux-androideabi-4.8\prebuilt\windows-x86_64
because scons tried to get there

I already have a file libgodot_android.so (38,5MB debug), and I'm on stage "Building the APK"

what is the "ant" and where to look for it? :)

If it helps that my configuration needed so far:
win7 64bit
jdk 6u45
ndk r10e 32bit
scons 2.3.6
python 2.7.10
mingw

**Comment by r3010** [comment]
i found ant ... now I stopped at this:

c:\godot\platform\android\java>ant debug
Buildfile: c:\godot\platform\android\java\build.xml
-set-mode-check:
-set-debug-files:
-check-env:
 [checkenv] Android SDK Tools Revision 24.3.4
 [checkenv] Installed at C:\Users\Jack\AppData\Local\Android\android-sdk
-setup:
     [echo] Project Name: Godot
  [gettype] Project Type: Application
-set-debug-mode:
-debug-obfuscation-check:
-pre-build:
-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.1
     [echo] Resolving Build Target for Godot...
BUILD FAILED
C:\Users\Jack\AppData\Local\Android\android-sdk\tools\ant\build.xml:538: Unable to resolve project target 'android-19'
Total time: 0 seconds
c:\godot\platform\android\java>

any ideas?

**Comment by reduz** [comment]
go to android project manager and get android-19 sdk

**Comment by r3010** [comment]
it works
i made Godot-debug-unaligned.apk and link as Custom Package Debug file.

new problem :) ... my exported "game" does not want to install on android 4.1.2 Samsung Note 10.1
(with stardard template is OK)

for clarification, my goal this compilation's is to install the game properly on Android 2.2.1 Samsung GALAXY S

is it possible :)? ... there is a magic flag to be set?

**Comment by reduz** [comment]
yes, use the release package, exporter should remove the previous signing
but it's not doing it so far so..

**Comment by r3010** [comment]
with Godot-release-unsigned.apk in Custom Package Debug game has been installed properly on android 4.1.2.
after running and a few seconds of black screen, the game has been terminanted.

on android 2.2.1 still message:
Parse error
There is a problem parsing the package.

**Comment by akien-mga** [comment]
This issue is quite old, and the buildsystem for android has been changed recently.

@oxrock As you commented recently, if you still experience the issue with the current master branch, please open a new bug report with logs and details about your environment, so that it can be better assessed.
