### ISSUE TITLE
Cannot compile android export template

### ISSUE THREAD

**Issue by khairul169** [godotengine/godot#1409]
scons: *** [drivers\libdrivers1.android.opt.debug.a] The parameter is incorrect
scons: building terminated because of errors.

how to fix that?
using windows 8.1 x64, latest android sdk & ndk..

compile params: scons platform=android armv6=yes target=release_debug -j 8

**Comment by akien-mga** [comment]
The error message that you gave does not contain the relevant build error that could help us analyse the issue. I'll assume it's the same issue as #1403.
