### ISSUE TITLE
Support Mesh-based particles in 3D

### ISSUE THREAD

**Issue by Spooner** [godotengine/godot#1418]
Currently only simple billboard (flat texture) particles are supported. Would be nice to have a method of creating mesh-based particles (especially if more primitives, like spheres and cubes are added, as requested by #1381)

Is there a plan to implement mesh-based particles any time soon or should I just write a script for it?

**Comment by akien-mga** [comment]
> Is there a plan to implement mesh-based particles any time soon or should I just write a script for it?

No plan that I know of, but I guess you inferred it when getting no answer ;) It's still an interesting idea though.

**Comment by razvanc-r** [comment]
I also hope this will arrive in v3. Many 3D games wouldn't be as flashy and nice looking without 3D mesh particles

**Comment by bojidar-bg** [comment]
Bumping for the sake of it not being forgotten for 3.0 :smile:

**Comment by reduz** [comment]
working on it

**Comment by Gibbz** [comment]
subscribing. Looking for a way to do this for my current project!

**Comment by akien-mga** [comment]
This was implemented in the master branch.
