### ISSUE TITLE
Upload dev builds please

### ISSUE THREAD

**Issue by Spooner** [godotengine/godot#1421]
I think we would benefit from having debug engine and templates uploaded somewhere whenever you push to master (or at least daily if you push more frequently on a day). Don't think there is a reason to upload release versions except for official releases though.

Building takes quite a while and is fiddly for some platforms, but there are a lot of us needing to use them...

**Comment by reduz** [comment]
hmm jenkins should be in position to do this, but should sort of make sure
there is a proper build-rotation system up.. Will ask Ariel to help with
this when he is back from Germany.

**Comment by Ace-Dragon** [comment]
A approve of having dev. builds made available now and then (like for Win64 which is the platform I'm on).

I don't think it has to be done every single day though, a good way to do it would to be to have it done whenever a major new piece of functionality or one of the release targets is committed (and with things like 2D lighting making it in recently, we could say it's due).

**Comment by Spooner** [comment]
Things aren't pushed/merged to master every day. I was just saying that doing it more than every day would be crazy...
But yes, having dev builds now and then would be fine (rather than 2 months since the last upload, which was the formal 1.0 release!).

**Comment by tonymtbird** [comment]
some type of auto generated change log would be great as well.

**Comment by philiplb** [comment]
Automatically built nightlies via an Jenkins including a changelog would be great! The changelog could be generated with the commit messages from github, an Jenkins has access to them.

**Comment by akien-mga** [comment]
There are now (somewhat) nightly builds on the official website, so this issue is more or less fixed. We might want to look a bit more into it when implementing proper CI #1553, so reuse CI builds as nightly builds).
