### ISSUE TITLE
Sprite3D Billboard isn't work when used Material Override

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#1422]
If do that sprite will not show image.

**Comment by Mavhod** [comment]
I'm override material with standard shader
I just found it must set Invert Faces frag, then image will be appear.

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment]
No answer, and the original bug report had too little details for easy reproduction, so closing. Please comment if you still reproduce this issue so that I can reopen it.
