### ISSUE TITLE
More intuitive controls and operations in the new visual shader editor

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#1425]
Namely, the short list of things I would like to see added to Godot's node window functionality
- Multi Select / Multi Move
- Duplicate (with noodles within the selection intact)
- ~~Zoom in / Zoom out~~ (*bugsquad edit: already done*)
- Option to have newly created nodes appear in the middle of the visible part of the workspace rather than in the middle of the node area

It's a bit basic right now, and working within the window tends to be a slow process when you only have basic controls available, it would be nice to speed things up a bit.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by bojidar-bg** [comment]
Is this issue still valid on master?

**Comment by Ace-Dragon** [comment]
Zoom is there, but I'm pretty sure we're not supposed to touch Master for general use until Reduz gives the all-clear (due to it being unstable).

Last I checked, all of the other points are still more or less valid (but I have not touched Godot in a while due to other work I'm doing). Have anyone else noticed if those features are there now?

**Comment by akien-mga** [comment]
As the Visual Shader Editor was disabled in 3.0 and will be rewritten for 3.1 or 3.2, it might change a lot compared to what this issue was written against in 2015. I'll close this for now, we can revisit it / open a new issue once the new VSE is implemented.
