### ISSUE TITLE
Can't edit the Vector2Array points of a ConvexPolygonShape2D

### ISSUE THREAD

**Issue by Raventara** [godotengine/godot#143]
When adding a shape to an element of a tileset you can't edit the Vector2Array points of the ConvexPolygonShape2D.

You can see the editing box comes up very small usually or sometimes in full but it has no text boxes or anything to edit the points with.

To work around this you have to save the shape to an xml file and manually edit it.

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by vnen** [comment]
This does not seems to be the case anymore. There's proper interface in the Inspector to edit Vector2Array.
