### ISSUE TITLE
2D Light Multiplier

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#1430]
Currently you have to set the light strength via a texture. But sometimes you want the light even be brighter. Therefore it would be great to have a mutiplier for each light. This would help to make lights even brighter, or less bright.

**Comment by bojidar-bg** [comment]
Isn't this done in current master?

**Comment by bojidar-bg** [comment]
Seems like it is the `energy` parameter, closing as done. Comment if this is not correct.
