### ISSUE TITLE
Improve Search Help

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#14319]
Today the search help function searches through Classes, Methods, Signals and Properties separately.

AFAIU, you can't restrict the search to the SceneTree methods by typing `SceneTree.` into the search box, because that leaves you with just the SceneTree class and a bunch of other entries where "SceneTree" appears in the description. It is not possible to restrict entries to properties or signals by typing "Property" or "Signal" either.

It would be nice to implement some form of fuzzy search that would let us do this. The Search Help is a great tool to discover/navigate the API. I'd love to see it become even more powerful.

**Comment by YeldhamDev** [comment]
As the current "Search Help" dialog let's you filter what you want, I think this can be considered closed.
