### ISSUE TITLE
Switch to Linux for macOS and iOS builds on Travis-CI

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#14314]
Is there any chance of this happening?

I'm asking mainly because of the backlog for macOS builds that makes those builds unpredictable, those and can fail right away or last several minutes or even hours just to realize that there were some errors in the static analysis.

I know one could "hang tight ... until the build has started", but then it defeats the purpose of email notifications in the first place.

Also, there is an option (`fast_finish`) that allows builds to fail early, but I think it won't cancel the remaining jobs as discussed [here](https://github.com/travis-ci/travis-ci/issues/2062).

Cheers!

**Comment by akien-mga** [comment]
Well if it's *possible* to build for macOS and iOS from Linux, that would be great yeah.

**Comment by akien-mga** [comment]
Thanks, that solves it. What we could do is disable macOS builds (like we did already for iOS builds) until Travis upgrades their infra.

**Comment by reduz** [comment]
I got Godot to build on OSXCross a long time ago, but it seems to be
illegal now.

**Comment by Calinou** [comment]
For those interested, compiling Godot for macOS using OSXCross still works with the current `master` branch. iOS builds also seem to work, but I can't test them.

**Comment by rraallvv** [comment]
I was able to [cross-compile 2.1](https://travis-ci.org/rraallvv/godot/builds/313737766) but I get this error:

> /home/travis/ioscross-target/usr/bin/arm-apple-darwin11-ld: error while loading shared libraries: libtapi.so: cannot open shared object file: No such file or directory
> clang-3.9: error: unable to execute command: No such file or directory
> clang-3.9: error: linker command failed due to signal (use -v to see invocation)
> scons: *** [bin/godot.iphone.debug.arm] Error 255
> scons: building terminated because of errors.
> 

Also tried passing `LIBPATH`, `LDPATH` and `LD_LIBRARY_PATH` to the Scons environment but I'm still getting this error.

By the way, I'm developing on a Mac computer and the app is intended to be deployed to iOS devices only, both are Apple-branded hardware.

**Comment by rraallvv** [comment]
While putting myself to the risk of being targeted in a witch-hunt or something, I asked to a perfect strange in the site StackOverflow for Law whether this is allowed or not, and it seems there is a consensus on macOS and iOS cross-compilation on not Apple-branded hardware being illegal :(

**Comment by akien-mga** [comment]
Well it's relatively clear from the above quote no? :)

> You are expressly prohibited from separately using the Apple SDKs or attempting to run any part of the Apple Software on non-Apple-branded hardware.

**Comment by rraallvv** [comment]
@akien-mga I was interested in the part "separately using" because it could imply that even compiling from the command line using a build system like Scons could be prohibited unless running from Xcode. Who knows! I'm not a lawyer.
