### ISSUE TITLE
get_stylebox("myStyle") doesn't always get the correct type.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#1431]
An example...

Say I made a progress bar, and I gave it my own style using the "newStyleBoxFlat" entry.

Now say I fetch the bar node using GDscript and used this code...

var Style = myBar.get_stylebox("myFlatStyle")
print(Style)

The print will give me "StyleBoxTextured:#" when it should be saying "StyleBoxFlat:#", as a result, I cannot change the color because the function for that is only for flat styles and the engine thinks I'm using the Textured type..

This shouldn't be too hard to fix I think, thanks.

**Comment by reduz** [comment]
not sure if i understand this bug, did you give it your own style using code?

**Comment by Ace-Dragon** [comment]
The simplest possible test case
http://www.mediafire.com/download/fciqbi9dw8jn5t8/UI_Test.zip

When you play the file, it is clear the stylebox type for the bar graphic is flat, but the debug output shows that the function doesn't recognize that and instead says the stylebox type is textured.

**Comment by akien-mga** [comment]
Confirmed in the current master branch.

**Comment by Chaosus** [comment]
ProgressBar really uses StyleBoxTextured by default, but in UI_Test.zip shows an incorrect usage

```
func _fixed_process(delta):
	var myBox = get_node("ProgressBar")
	var Style = myBox.get_stylebox("myFlatStyle")
	print(Style)
```
there is no "myFlatStyle" stylebox in ProgressBar now. The correct usage is

`var Style = myBox.get_stylebox("fg")`

which is correctly handled as StyleBoxFlat or whatever you apply to it. Closed.

**Comment by Icemole** [comment]
For anyone still coming here: the string passed as the first argument to `get_stylebox()` is NOT the resource's name, but the name when hovering the name of the node, near the checkbox (Godot 3.2.2). [In my case](https://imgur.com/a/7vCZwts), I had to hover over "Panel", and calling `get_stylebox("panel")` yields the correct `StyleBox`. I hope this helps someone out there.

**Comment by tx350z** [comment]
THANK YOU! You just saved me many hours of head-scratching and expletive outbursts!

**Comment by akien-mga** [comment]
Sounds like a documentation improvement is in order.

**Comment by zak-grumbles** [comment]
Hi, I'm interested in updating the documentation here. Quick clarifying question: Has the `get_stylebox()` method been renamed to `get_theme_stylebox()`? I'm unable to find the `get_stylebox()` method in the current [Control.xml](https://github.com/godotengine/godot/blob/master/doc/classes/Control.xml). Admittedly, I may be looking in the wrong class.

**Comment by Calinou** [comment]
@zak-grumbles Yes, all the theme item getter methods have been renamed from `get_<item>()` to `get_theme_<item>()` in the `master` branch.

**Comment by pycbouh** [comment]
Documentation was fixed by https://github.com/godotengine/godot/pull/50429.
