### ISSUE TITLE
Nested ternary `if`s have unexpected associativity

### ISSUE THREAD

**Issue by silverweed** [godotengine/godot#14324]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Debian GNU/Linux, Godot v 2.1.4.stable.official.
I made a friend try on Godot v 3 and the outcome is the same.

**Issue description:**
The ternary `if` clause has unexpected associativity that may cause hard-to-track bugs if one is accustomed to the very similar Python expression.

**Steps to reproduce:**
Create the following script and attach it to a class:

```gdscript
extends Node

enum Direction { UP, RIGHT, DOWN, LEFT }

func _ready():
	for d in [Direction.UP, Direction.RIGHT, Direction.DOWN, Direction.LEFT]:
		print("up" if d == Direction.UP else
			"right" if d == Direction.RIGHT else
			"down" if d == Direction.DOWN else
			"left")
```

Expected output:
```
up
right
down
left
```

Actual output:
```
left
left
down
left
```

The expected output is produced when parentheses are added around nested `if` expressions, but this is not required in Python, and it's quite surprising to the user (also, adding a couple of parentheses per `if` gets very ugly very quickly).

**Link to minimal example project:**
[ternary_if.zip](https://github.com/godotengine/godot/files/1536407/ternary_if.zip)

**Comment by akien-mga** [comment]
CC @bojidar-bg
