### ISSUE TITLE
EditorFileSystemDirectory can't see directory contents.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#14325]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0

**Issue description:**
EditorFileSystemDirectory appeared unable to see any of the files or subdirectories in my resource folder.

**Steps to reproduce:**
Take an existing project that has files and folders inside it already.
Create an empty scene with a Node, and the following built-in script:

    extends Node
    
    func _ready():
        var dir = EditorFileSystemDirectory.new()
        print(dir.get_file_count())
        print(dir.get_subdir_count())
        for i_file in range(0,dir.get_file_count()):
            print(i_file, "> Path: ", dir.get_file_path(i_file))
            print(i_file, "> Name: ", dir.get_file(i_file))
            print(i_file, "> Type: ", dir.get_file_type(i_file))
        print(dir.get_path())
        print(dir.get_name())

Save the scene to your `res://` directory, and then run it. It will print:

    0
    0
    res://

...when it should print a LOT more information.

**Comment by djrm** [comment]
isnt that another singleton?
```
EditorInterface.get_resource_filesystem().get_filesystem()
# or
EditorInterface.get_resource_filesystem().get_filesystem_path(my_path)
```

**Comment by willnationsdev** [comment]
Oh, that may very well be. I can't seem to do `EditorInterface.get_resource_filesystem()` or just `get_resource_filesystem()` though. Not sure how those are supposed be accessed. I've been trying to put in the documentation, so...XD

**Comment by djrm** [comment]
oh i forgot, it is
```
get_editor_interface().get_resource_filesystem()....  # from a EditorPlugin
```

**Comment by djrm** [comment]
i guess that class needs to be virtual.

**Comment by willnationsdev** [comment]
Oh, so they have to be used from an EditorPlugin in order to work properly?

If so, I will amend the documentation I've done for those classes.

**Comment by djrm** [comment]
it makes sense, those are tools needed by EditorPlugins, the Directory class is for the rest.

**Comment by willnationsdev** [comment]
Why are they used in place of Directory anyway? What makes them different? They seem to have limited functionality in comparison. Or is it that they can access the whole file system beyond `res://` and stuff?

**Comment by djrm** [comment]
im not sure it seems to have some utilities only available to them, maybe because behavior optimizations for Editor stuff, but i've never used it nor checked the code, so that might be a good place to start.

**Comment by willnationsdev** [comment]
Yeah, I've peeked at the code, checking the contents of the scripting API-exposed functions, but I wasn't seeing much.  Maybe I'll have to dig deeper later on.
