### ISSUE TITLE
New unusual physics engine request.

### ISSUE THREAD

**Issue by GaponkaGapon** [godotengine/godot#14322]
I'm already understand, that answer is "No", but I want to know why. Is it impossible, or you just don't interested in new unusual physics in Godot, or is it just money and time problem? Sorry for my english, btw.

I’m requesting a new unusual 2D physics engine in addition to the old one. It’s may sound crazy. I’m not sure if this physics is even mathematically consistent and possible physically on modern computers. I know, this will be hard to implement, but it may worth it. It's sound very specific, but it can do normal physics and more. Much more. I think, it may be a one more killer feature, because Godot will stand out not only by the way games are developed, but by the end possibilities of the games themselves. If these possibilities are already in the engine, them hard to achieve, I think.

The idea is in a space consisting of different layers with their own distortions and with their own characters and objects, where characters and objects from different layers can collide and interact with each other despite they distorted in a different ways. I would like to give simple examples and remind, that this is not a game request, but a physics request.

Imagine two-layered square room. First layer is not distorted from the player perspective and has a player character. Second layer has a rock, and space of the second layer becomes more dense to the center of the room. If player character picks up a stone and will go to the center of the room, he will see, that rock shrinks in his hands.

Another example (maybe, this one is already possible to implement with the old 2D physics engine almost without paradoxes, but anyway). Two-layered square room. First layer the same. Second layer has a rock, but its space has a different distortion. Distortions may have sharper boundaries. Imagine a big invisible circle in the center of the room. Then turn space of the second layer which is in the circle on 180 degrees. This is your distortion. Outer surface of the circle leads to the inner surface like portal. If player character picks up a stone and will go to the center of the room, he will see at some moment, that the rock has disappeared from his hands and appeared on the other side of the invisible circle.

And since we're talking about portals. If we have two connected portals of different shapes, then we can assume, that each portal are located on its own layer and leads to the another layer of another portal with different distortion, and that’s mean, everything that passes through portals becomes distorted.

These are simple examples, but in-game worlds can be more complex. I guess, there a lot of things that possible to imagine. For example, moving distortions. Or it’s possible to give the player ways to control distortions and curve portals.

**Comment by greyspot** [comment]
This sounds like it has more to do with game design rather than engine features. What is actually being requested here?

**Comment by akien-mga** [comment]
If that's not an existing "UnusualPhysics2D" library, then indeed the answer is "no". You are basically asking for us to implement your game logic as a new physics engine. You should implement it yourself, and use your own logic instead of Godot's physics engine.

**Comment by GaponkaGapon** [comment]
I know that it's sound too specific. I guess, every physics idea that is different from regular physics sounds too specific. I'm just believe that it is not the way it's meant to be. But anyway, I'm sorry for this and thank you for the answer.

**Comment by reduz** [comment]
No worries, one of the reasons why we created GDNative is that one can create a custom physics engine or anything else in C++ without having to recompile Godot, so this could be eventually be added.

**Comment by akien-mga** [comment]
> so this could be eventually be added.

Albeit by the community, and not officially in the core engine :)
