### ISSUE TITLE
Area don't register collisions after re-enter the scene (Godot Physics) Godot 3.0 beta 

### ISSUE THREAD

**Issue by DrZanuff** [godotengine/godot#14331]
**Windows 10 64bits, Godot 3.0 Beta 1

Issue description:
When you have an area signaling other node with on_area_entered(_) it works. But if you reload the scene a few times, the colission don't work anymore. The collisionShape is still there, but collission don't register anymore. With GodotPhysics

Steps to reproduce:
Switch to GodotPhysics. Create two areas and add a script to one of then. Add a signal on_area_entered(_) and code to print something. Reload the current scene a few times and try to collide again.

Link to minimal example project:
[Godot3AreaBug.zip](https://github.com/godotengine/godot/files/1536809/Godot3AreaBug.zip)

Obs: I know i could use the Bullet engine, but the bullet engine has a bug for me right now with rigidbodies i found during Ludum Dare 40. Issue #14337.

**Comment by emma-fm** [comment]
Still happening in Godot 3.1 (but I'm using 2D)

**Comment by KoBeWi** [comment]
Doesn't seem to happen in 3.2.2. I restarted the scene ~50 times.
