### ISSUE TITLE
X11: splash screen has wrong size when starting maximized

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#14336]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 a496dd4, KDE Plasma 5.11.3  

**Issue description:**
When godot starts maximized, the splash screen sometimes doesn't fill the whole window.
This happens because of this code: https://github.com/godotengine/godot/blob/a496dd4d389e2752a58f5beb98dcfad2eeccaf14/platform/x11/os_x11.cpp#L444-L452

This exits the loop at the first encounter of a `ConfigureNotify` event (which contains the new window transform).
However, WMs sometimes like to resize the window in incremental steps. 
So the first event is not always the one we're looking for.

**Comment by AlmightyScientist** [comment]
You maybe should link the lines of the a496dd4 commit : 

https://github.com/godotengine/godot/blob/a496dd4d389e2752a58f5beb98dcfad2eeccaf14/platform/x11/os_x11.cpp#L444

**Comment by Hinsbart** [comment]
Right, thanks. I updated the OP

**Comment by AlmightyScientist** [comment]
Got to go atm but isn't waiting for the last `ConfigureNotify` of the x11 event queue the good thing to do?

It depends on which order predicate (`_check_window_events` in our case) is called on events.

**Comment by Hinsbart** [comment]
> Got to go atm but isn't waiting for the last ConfigureNotify of the x11 event queue the good thing to do?

Yes, that's what this issue is about.
Problem is, we can't know for sure if a particular event is the last one.

**Comment by AlmightyScientist** [comment]
Huh, that's weird, according to [this](http://menehune.opt.wfu.edu/Kokua/Irix_6.5.21_doc_cd/usr/share/Insight/library/SGI_bookshelves/SGI_Developer/books/XLib_PG/sgi_html/ch08.html#S2-1002-8-3).

> The event structures are placed on an event queue in the order they occur, [...]

Therefore, we can assume the last occurrence is the effectively last event, can't we?

**Comment by akien-mga** [comment]
> Therefore, we can assume the last occurrence is the effectively last event, can't we?

But how do you know that it's the last? I haven't checked the code, but assuming that we're just polling for events in an infinite loop, we need a way out at some point :)

**Comment by AlmightyScientist** [comment]
```C++
    XEvent xevent;
    bool windowEventOccurred = false;
    
    while ((windowEventOccurred = windowEventOccurred || XCheckIfEvent(x11_display, &xevent, _check_window_events, NULL))) {}
    
    if(windowEventOccurred) {
        _window_changed(&xevent);
    }
```

Should world, I guess.
(I use 1TBS style, I don't know if Godot project use a particular one)

**Comment by AlmightyScientist** [comment]
```C++
    XEvent xevent;
    bool windowEventOccurred = false;
    
    while (XCheckIfEvent(x11_display, &xevent, _check_window_events, NULL)) { 
        windowEventOccurred = true; 
    }
    
    if(windowEventOccurred) {
        _window_changed(&xevent);
    }
```

Should world event if it's not well to see xD, I guess.
(I use 1TBS style, I don't know if Godot project use a particular one)

We could use 

```C++
while (XCheckIfEvent(x11_display, &xevent, _check_window_events, NULL) && (windowEventOccurred = true)) {}
```

to save lines. 
But it isn't really readable imho.

**Comment by Hinsbart** [comment]
Well, that's essentially the same as the current behaviour. It would still return on the first event.

**Comment by AlmightyScientist** [comment]
You mean that the last element of the queue is the most distant event while the first one is the last event to occur?

**Comment by Hinsbart** [comment]
Ah sorry, looks like I had a little misunderstanding myself...

We're breaking out of the while when the event type is **not** `ConfigureNotify`. That means we're stopping too early because there are some other events in the queue.

**Comment by AlmightyScientist** [comment]
No problem !

It's not supposed to IMHO : 

Our current implementation is looking for **ALL** events in the queue when `initialize` is executed (when we call the Main setup). On each event that matchs the predicate `_check_window_events` :  `XCheckIfEvent` returns the corresponding `XEvent` through `xevent` parameter, remove this one from the event queue and returns `True`.  

If none of events in queue matchs the predicate, `XCheckIfEvent` returns `False` (thus our loop breaks).

Could you confirm that. Otherwise, could you link me some info on `XCheckIfEvent` because with what I read : `XCheckIfEvent` doesn't return `False` on the first failed `_check_window_events`. Thus, we should iterate **each** event in queue.

**Comment by AlmightyScientist** [comment]
Still happens to me :/

**Comment by AlmightyScientist** [comment]
With what you've done, after the `while`, we have the correct sizes.

```
Window State : 1600, 849
BOOT DRAWING BEGIN
Actually, size is : 1600, 849
```
And still, the gl_context's buffers seems unchanged..

**Comment by guilhermefelipecgs** [comment]
@AlmightyScientist This fix works for gnome too or it's just for kde?
