### ISSUE TITLE
Rim light brutally changes if mesh intersects with the AABB of an OmniLight

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14342]
Godot 3.0 beta 1 and master
Windows 10 64 bits
nVidia geforce 940M

Repro: drag an omnilight near a mesh that has rim on it, you will see it immediately gets affected by the color of the OmniLight without any transition. This is particularly harsh if large parts of the level have rim and are larger than the light, causing flickers like seen here: https://www.youtube.com/watch?v=dpyZKxgdPMo

Minimal repro video: 
https://www.youtube.com/watch?v=vK_iVjyxGV8&feature=youtu.be

Project: 
[RimFlicker.zip](https://github.com/godotengine/godot/files/1537087/RimFlicker.zip)

**Comment by akien-mga** [comment]
Can you try again in the current master branch (especially after 8c78ccb02)?

**Comment by reduz** [comment]
Tested. It works fine now, and it looks reaally nice.
