### ISSUE TITLE
LineEdit eats the last character.

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#14340]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master a8ae46e1431a25ced8565db39e44e068b8815c21

**Issue description:**

It is not possible to see the last character in a line edit if it overflows the it.

maybe a bit confusing, but the instructions are easy to follow.
![peek 2017-12-06 15-51](https://user-images.githubusercontent.com/1103897/33687401-b7fb07ca-da9d-11e7-9024-de3be3672985.gif)

**Steps to reproduce:**
write until you fill the line edit, see how you cant see the last character

**Link to minimal example project:**

**Comment by TheAspiringHacker** [comment]
I would like to work on this issue.

**Comment by TheAspiringHacker** [comment]
Hmm, when I created a LineEdit node, the bug did not occur, and when I used the search bar in the "Create new node" dialog, the bug did not occur. There isn't a magnifying glass icon in those two cases, but there is one in yours. Perhaps the icon covers up the last character?

**Comment by djrm** [comment]
could be possible, seems to happen only when the icon is there, i first saw it with the animation editor function key / function name, but now i can reproduce, so the only one left could be this case.

**Comment by djrm** [comment]
also the gif is for "search classes" in script editor

**Comment by TheAspiringHacker** [comment]
Yes, I found the dialog that was in the GIF. I read the drawing code and find that: 1) the icon is drawn before the string and 2) the icon width is subtracted from the max offset (or else the string would probably overlap the icon). I think that the bug is probably in the cursor code, which I'll check next.
