### ISSUE TITLE
Can't use comma to create float

### ISSUE THREAD

**Issue by QuentinCaffeino** [godotengine/godot#14344]
**Steps to reproduce:**
```gdscript
var p = 3.14  # This is ok
var e = 2,71  # Syntax error
print(float("2,71"))  # 2
```

It would be nice to be able to use both separators if engine doesn't have any special plans on comma in numbers :)

**Comment by akien-mga** [comment]
No, that's not possible and if it were, it would be a bad idea. How would you know if `foo(3,14)` is actually `foo(float)` or `foo(int, int)`?

**Comment by Zylann** [comment]
This is not possible, simply because it would make the following code ambiguous:

```gdscript
var list = [3,14, 2] # How many elements this array contains?
```
