### ISSUE TITLE
Changing between light and dark theme doesn't update some icons.

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#14351]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64 - a88543c

**Issue description:**

Scene tab
![image](https://user-images.githubusercontent.com/26753932/33691552-57ea2b44-db1b-11e7-8cdf-d06d0ca659e9.png)
EditorAbout
![image](https://user-images.githubusercontent.com/26753932/33691617-9b4afe90-db1b-11e7-94c5-69fc8dbbc80f.png)
Help PopupMenu
![image](https://user-images.githubusercontent.com/26753932/33691668-d4dfc582-db1b-11e7-9d77-f72869ef1f0a.png)
Audio bus
![image](https://user-images.githubusercontent.com/26753932/33691687-f1f77444-db1b-11e7-9428-165179dad599.png)
Debugger
![image](https://user-images.githubusercontent.com/26753932/33691720-2aa54ff0-db1c-11e7-8f3c-8f02e1a164a1.png)
EditorFileDialog
![image](https://user-images.githubusercontent.com/26753932/33691854-e2edbb4c-db1c-11e7-8a85-602e77239dd8.png)

Performance tab "start profiling" button
Project settings search

**Steps to reproduce:**
1. Editor settings: interface/theme/preset = Light

**Comment by djrm** [comment]
yeah it needs restart, or some refactoring of the icon setup process for multiple classes (icons are set when ready, but they should also be set when EDITOR_THEME_CHANGED), im pretty sure there is an issue about this, but i could not find it.
