### ISSUE TITLE
Message in console: Invalid Setter: AnimationPlayer::set_current_anim for property.... 

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#14359]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 build from master 07/12/2017 Win 7 64 bit

**Issue description:**

Opening Godot console shows this message. Error is not in Beta1. Error shows in console even not loading any project, is in console every execution of preview and doesn´t affect execution itself (Project doesn´t have animation player):
![erroranimplaypostbeta1](https://user-images.githubusercontent.com/11712737/33694994-4767d2e6-dafb-11e7-8305-fe0aaec2f043.jpg)

**Steps to reproduce:**
Open godot :) :) :)

**Comment by akien-mga** [comment]
I think that's a regression from a496dd4d3, ping @reduz.

**Comment by willnationsdev** [comment]
Ah, yeah, that would be from my PR. You can just recert them and I'll resubmit them under a separate commit that has no properties

**Comment by willnationsdev** [comment]
Or I can actually just submit a "fix" PR that un-does the API changes but keeps all the documentation.

**Comment by akien-mga** [comment]
Fixed by #14384.
