### ISSUE TITLE
Regression: Bad rendering in 2D viewport after b38378dd6

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#14357]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 build from master at 07/12/17 1:00 AM
The last image is the entire desktop (2 godot executions in 2 screens)
(Win 7 64 bit GeForce GTX 660
![regresion07_12_17](https://user-images.githubusercontent.com/11712737/33693862-68ef599e-daf5-11e7-8681-ebfd79be3a0f.jpg)
![regresion07_12_17-part2](https://user-images.githubusercontent.com/11712737/33693867-742f5e4e-daf5-11e7-990c-af1aa46e01af.jpg)

**Comment by reduz** [comment]
guess 2D viewport may not like being 8-bits, will have to check that

**Comment by Ranoller** [comment]
I compiled godot at 20/dic/2017 and this issue was fixed, so i close.
