### ISSUE TITLE
[Visual Shader Editor] normal data output for 'global' space (and other types)

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#1435]
I reason I argue for the change is because I don't know what use people may have for the current 'normal' output data which is view dependent, my idea of making the normal data so that it is global would allow it to have numerous use cases, especially for terrain.

What it can enable for terrain for instance is that it could then be used as a slope-based mask for textures, so steep slopes and overhangs are rocky and flat areas are grassy. On high-elevation maps, you could make it so the flat areas have snow.

Another thing to possible add (not mentioned in the title), is to have a second new output for normal data in space local to the object (for objects that might rotate).

Thirdly, it would also be good to have a third new output that colors the mesh based on the angle of the normal to the camera (for fresnal effects). Finally, one should go through what it available as data outputs right now and see if there's any that may not have much of an actual use (or no one plans to use and see if that can be taken out), just to make sure we have a nice list of outputs that have genuine and expansive uses for users.

**Comment by reduz** [comment]
not completely sure about this, normal is viewspace so light shader can apply it, or am i understanding wrong?

**Comment by Ace-Dragon** [comment]
What I'm talking about here is more for various texturing purposes such as a terrain shader. So for a terrain mesh for instance, you can create a mask based on the direction the normal of the face is pointing (so if it's pointing straight up or straight down on the Y axis the mask value is white and if it's pointing 90 degrees to the side the mask value is black).

This could be used to assign a more rocky texture to cliffs and a grassy texture for flat areas for instance.

**Comment by akien-mga** [comment]
As the Visual Shader Editor was disabled in 3.0 and will be rewritten for 3.1 or 3.2, it might change a lot compared to what this issue was written against in 2015. I'll close this for now, we can revisit it / open a new issue once the new VSE is implemented.

**Comment by RichardEllicott** [comment]
i think some missunderstandings of language here... i think he is asking how to get the world coodinates... you get the camera coordinates by default

i am having trouble doing this with a visual shader, but have the snippet can paste in code shaders... this sort of thing could be solved if we just had some simple examples of visual shaders in a library somewhere
