### ISSUE TITLE
Physics masks flyout display is labelled incorrectly

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#14363]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10 Godot3 beta1

**Issue description:**

When clicking on the physics body mask flyout it is labelled the same as the the layers flyout. Both are labelled as "2D Physics Layers". Shouldn't this read as "2D Physics Masks" instead? This also occurs for the 3d physics bodies.

![physics_flyouts](https://user-images.githubusercontent.com/7741669/33698723-610532cc-db62-11e7-8b5c-85b69c3164b9.jpg)

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by djrm** [comment]
hmm, both show the layers available, so they are the same.

**Comment by fracteed** [comment]
I guess, they are technically "2D Physics Mask Layers". Maybe it is just me, but I have always found the labelling to be unintuitive on this. They are right next to each other and have different functions, yet are labelled the same. I often jump between the 2 on multiple objects and find myself having to doublecheck that I clicked the right one, especially when working on a small laptop screen...

**Comment by eon-s** [comment]
Looks like a waste of space, the selection is highlighted already.

But in any case, the OP proposal sounds good, same wording may be confusing for some.

**Comment by reduz** [comment]
those are the layers, you can assign names to them in the project settings

**Comment by mrcdk** [comment]
Not sure about this, what you are masking are the layers not the masks, so both popups are correct. 

Which questions are more correct?
- Which layers am I masking? Which layers am I adding to be mask?
- Which masks am I masking? Which masks am I adding to be mask?

IMO the second option makes no sense.

**Comment by akien-mga** [comment]
Fixed by #14455.
