### ISSUE TITLE
"F" key Viewport focus problem

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#14371]
version -> http://godot3builds.digitecnology.com/builds/2017-12-06.12:52:48.a8ae46e14/godot-v3.0-osx.fat.zip

**Issue description:**
When i press F key, wrong viewport is active.

**Steps to reproduce:**
https://www.youtube.com/watch?v=y5K5xv7UBuo&feature=youtu.be

**Comment by carlosfvieira** [comment]
Also referred here - #12409 , as a more global issue, not only related with shortcut 'F'
