### ISSUE TITLE
Why is Api a _edit_ prefix? _edit_get_rect _edit_use_rect _edit_get_item_and_children_rect and so on

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#14378]
Why is Api a _edit_ prefix? _edit_get_rect _edit_use_rect _edit_get_item_and_children_rect and so on...
It looks strange.

**Comment by groud** [comment]
That's normal, they are helper to be used only by the 2D editor. They will be used to display / edit the selection rectangles, pivot and all.
That's why they are not in the docs nor accessible from gdscript.

**Comment by cjmxp** [comment]
@groud _edit_get_rect Can't be used in notools?

**Comment by groud** [comment]
notools ?

**Comment by groud** [comment]
It is meant to be an editor only function for now.

**Comment by cjmxp** [comment]
How can I use GDScript in my game to call these API? get_item_and_children_rect ()?? that's what I can use before.

**Comment by groud** [comment]
You can't, they are not meant to be used outside the editor.

Even the get_item_and_children_rect() function returned a rect that included the 64px box around the Node2D (used to move them in the editor), this did not make any sense in games. Thus I removed it.

If you want a similar behaviour, you can code it yourself in GDscript. Depending on what you really need this will be more adapted to your game.

**Comment by Zylann** [comment]
@groud are they still accessible to editor tool scripts though?

**Comment by groud** [comment]
@Zylann, nope, but i don't think we have a system to differentiate functions that can be called in tool scripts

**Comment by Zylann** [comment]
@groud there is one: `#ifdef TOOLS` :D

**Comment by groud** [comment]
Oh cool, I did not know. I should have a look to how using it then.

**Comment by Zylann** [comment]
@groud to be clear, `#ifdef TOOLS` is in C++, I implied that such functions would simply not be bound, the same way I guess Godot doesn't binds editor classes in an exported binary (which is related to my above questionning)

**Comment by vnen** [comment]
If they are bound they are accessible from GDScript, even if not in doc/autocompletion. But the functions that start with an underscore (`_`) are supposed to be hidden, it's a convention.

**Comment by groud** [comment]
Closing as the initial question was answered.
