### ISSUE TITLE
Frame Selection Shortcut (shift+f)  activates "camera fly mode" not "Frame Selection"

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#14370]
Godot version -> http://godot3builds.digitecnology.com/builds/2017-12-06.12:52:48.a8ae46e14/godot-v3.0-osx.fat.zip

**Issue description:**
Where is the "Zoom to Selection Mode" or Frame Selection

**Comment by Zylann** [comment]
Isn't zoom to selection just "F"?

**Comment by akien-mga** [comment]
> Isn't zoom to selection just "F"?

Yes, but there is indeed a "Frame Selection" action bound to Shift+F in CanvasItemEditor:
![spectacle bh7814](https://user-images.githubusercontent.com/4701338/33821493-4b09e072-de54-11e7-9cef-8584674cc379.png)

They both act in different viewports so it should be fine, but it's true that I need to press Shift+F *twice* to get the frame selection (mega zoom-in on the 2D node) to happen in the CanvasItemEditor, so there's something weird happening (which *might* be a conflict with Freelook toggling).

**Comment by Zylann** [comment]
If a 2D shortcut conflicts with a spatial editor shortcut that could hint a more general issue that shortcuts aren't properly encapsulated...

**Comment by carlosfvieira** [comment]
I'm not being able to reproduce the issue using Debian (8.10)... when i have the 2D node selected, and the canvas item editor with focus, i press SHIFT+F once, and the frame selection occurs with no issues.

>They both act in different viewports so it should be fine, but it's true that I need to press Shift+F twice to get the frame selection (mega zoom-in on the 2D node) to happen in the CanvasItemEditor

**Comment by icnikerazah** [comment]
this is 3d only issue. and no zoom in 3d only pan

**Comment by icnikerazah** [comment]
it sould be

"F" = focus
"Shift + F" = zoom and focus
"right click" = camera fly mode

**Comment by carlosfvieira** [comment]
So, basically what you are experiencing is, when you press "Shift + F", it does not focus immediately on the selected object, and you can't zoom in or out... you can just look around by moving the mouse, that's correct?

**Comment by icnikerazah** [comment]
no i can zoom in out with scroll manualy. i want auto zoom like blender

**Comment by carlosfvieira** [comment]
Well, the behavior i described is what i can experience... i click "SHIFT-F" and when using the mouse scroll, it just don't zoom in or out, despite the left distance indicator moves down or up...

**Comment by icnikerazah** [comment]
Frame selection means fill the viewport. frame selection key is only panning object not zoom (frame selection).
and additionaly key binding is wrong

**Comment by Zylann** [comment]
You cannot remove the shortcut to toggle freelook, it was requested as an alternative to RMB.
Shortcuts should be appropriately chosen.

**Comment by carlosfvieira** [comment]
I'm using the current master, and simply can't reproduce any issue with the SHIFT-F shortcut (the reason this issue was created i think)... both in Frame Selection (CanvasItemEditor) and Toggle Freelook (Spacial Editor).

**Comment by carlosfvieira** [comment]
@Zylann , for what i've seen in other issues, you developed the Freelook feature... when i was trying to reproduce this particular issue, i found that in Freelook mode there is no zoom... i tried to zoom in or out and the zoom just don't work, but there is the left indicator (zoom / distance indicator) in the viewport, that in fact responds to the scroll input... my question is:

is it supposed to have or not zooming while in Freelook mode?

**Comment by Zylann** [comment]
@carlosfvieira there is no zoom in freelook, you just move further or closer with a configurable speed using the mouse wheel. The left indicator shows how fast you move, and if you have "link with zoom" checked, that speed will be adjusted from the zoom level you have in pan/orbit mode.

**Comment by carlosfvieira** [comment]
Oh Great @Zylann , now i see how it works! Thanks for the explanation :)

**Comment by icnikerazah** [comment]
>Zylann:  We cannot remove the shortcut to toggle freelook, it was requested as an alternative to RMB for long-held usages.
> Shortcuts should be appropriately chosen/changed.

In that case should be : "F" = focus with zoom
equivalent "F" in Maya
equivalent "." in Blender.
<img width="647" alt="ekran resmi 2017-12-13 22 51 15" src="https://user-images.githubusercontent.com/33985414/33959385-576dee2a-e058-11e7-9f5a-2f7ef2c46811.png">

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by icnikerazah** [comment]
i think this is not a issue. this is feature request. auto zoom with pan feature. closed.
