### ISSUE TITLE
Can't Save Code without Tree Root

### ISSUE THREAD

**Issue by NielsVanM** [godotengine/godot#14389]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot 3.0 Beta Build 1

**Issue description:**
Can't save GDScript when there is no tree root

**Steps to reproduce:**
1. Close all scenes
2. Edit a script and try to save it, you'll get this message: "This operation can't be done without a tree root."

**Link to minimal example project:**
[Can't Save Code Without Tree Root.zip](https://github.com/godotengine/godot/files/1540403/Project.zip)

**Comment by Zireael07** [comment]
Press Ctrl+Alt+S instead of Shift+S (or use the File menu)

**Comment by NielsVanM** [comment]
Good that works, but is there a reason there is a different shortcut for saving scripts without a tree root?

**Comment by Zireael07** [comment]
This is a general "save scripts" shortcut.
