### ISSUE TITLE
Script extended from other script doesn´t show ENUM members in autocomplete

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#14398]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 beta 1 and Godot 2.1.4 win 7

**Issue description:**

Extending a script from other and trying to access a "enum member" with:  _enum_name.CONST_NAME_ works as expected, but autocomplete doesn´t show the constants inside the enum if the enum was declared in the base script.

**Comment by DualMatrix** [comment]
Still relevant in master. In fact it seems autocomplete for enums even in the same file is broken.

**Comment by KoBeWi** [comment]
Works in 3.2
