### ISSUE TITLE
Detail blend in FixedMaterial

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#14392]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 2.1.4

**Issue description:**
http://docs.godotengine.org/en/stable/_images/fixed_materials.png
Unknown if this is a feature request or a bug report for a parameter not showing.
In a screenshot in the docs, there appears to be a parameter for FixedMaterial entitled "Detail Blend"
Is this in the engine core and just not showing in the menu or is it a scrapped feature?

I personally think it would be a good addition to the engine. This would be useful for unreal style detail textures showing when the camera gets near.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Zireael07** [comment]
The screenshot is very very old (Godot 1), I strongly suppose the feature got renamed at some point.

**Comment by mhilbrunner** [comment]
Fixed link: http://docs.godotengine.org/en/2.1/_images/fixed_materials.png

Closing, this just seems to be an outdated screenshot.
