### ISSUE TITLE
Can't see the menubar at the top of the editor

### ISSUE THREAD

**Issue by moonlightarcana** [godotengine/godot#14401]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64-bit, Godot v3.0-beta1, Intel HD Graphics 520

**Issue description:**
Cant See the menu bar at the top of the editor
![godotmenu bar](https://user-images.githubusercontent.com/29647211/33759776-9f3630c8-dc57-11e7-859c-c59ed5868543.PNG)

**Comment by Zireael07** [comment]
Can you try updating the drivers? I think I've seen an issue about this, though you're on Windows and they were on Linux.

**Comment by akien-mga** [comment]
There were several such issues reported by Windows 10 users with Intel IGPs, upgrading your drivers should fix it.

**Comment by moonlightarcana** [comment]
I currently have the lastest version of the drivers installed.

**Comment by eon-s** [comment]
Is duplicate of #8902 , 520 drivers are not fixed by Intel yet, it seems, try downgrading as explained in that issue.

**Comment by groud** [comment]
OK, I close the issue as a duplicate.

**Comment by reduz** [comment]
I also had this problem on the same hardware as you, updating the drivers
fixed it

**Comment by reduz** [comment]
or maybe it was installing windows updates, I don't remember

**Comment by moonlightarcana** [comment]
Thanks for the all the suggestions and help. I did a rollback on the graphics drivers and issue is now solved.
Thanks for the all the speedy responses.
