### ISSUE TITLE
Rim and transmission shader in 3.0

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#14408]
win10, 960m,

rim light make cool effect while using sub surface without follow surface on
![screenshot 144](https://user-images.githubusercontent.com/13883739/33769064-b0ee5c2c-dc4e-11e7-91e2-4e95ec1860cc.png)
![screenshot 145](https://user-images.githubusercontent.com/13883739/33769065-b14598b6-dc4e-11e7-99fe-25ff29130b2a.png)

transmission glow up things with and without sub surface i think it should act acc. to fresnel i.e it should mainly effect outer side.

![screenshot 146](https://user-images.githubusercontent.com/13883739/33769165-1c465c40-dc4f-11e7-8ab2-7dd7ae860b4e.png)
![screenshot 147](https://user-images.githubusercontent.com/13883739/33769166-1c8dda3e-dc4f-11e7-9a18-65ee0283ba74.png)
![screenshot 148](https://user-images.githubusercontent.com/13883739/33769167-1cd1aade-dc4f-11e7-8838-e6477a23564b.png)

i feel like rim and transmission is strong even with low light

![screenshot 151](https://user-images.githubusercontent.com/13883739/33769227-670f8f26-dc4f-11e7-9edd-03b2b70b0feb.png)  rim at 1

**Comment by gamergamesz** [comment]
![screenshot 150](https://user-images.githubusercontent.com/13883739/33769393-1882059a-dc50-11e7-8874-77a33b2fe058.png)
rim at 1

**Comment by reduz** [comment]
1. Rim making cool effect: This is normal and how subsurface scattering works, jut reduce the intensity or adjust quality if you see this effect. it only is mean to apply some blur, if your kernel is too big it will do funny things

2. Tranmission right now affects the whole backfaces. Eventually a depth treshold parameter will be added to achieve the effect you want, but this will happen for 3.

3. Rim being strong in low light has been fixed a few minutes ago, it now takes light attenuation in consideration. Transmission is the same, until a depth treshold is implemented it will be strong.

**Comment by gamergamesz** [comment]
time to close this issue!!! thank you!
