### ISSUE TITLE
Regression: 'View owners' and 'Edit dependences' options are invisible for scene files

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#14407]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
b3b4727dff009dda0a65b8a013ec04d52a54b367

**Issue description:**
In FileSystem dock when right mouse button clicking on the scene file there is no options for [viewing the owners] and [editing dependencies]. The option is still there for script and texture files:
![view_owners](https://user-images.githubusercontent.com/6129594/33766596-830b3f6c-dc1e-11e7-9765-17ccccdbee40.gif)
I'm not sure when it disappeared but I'm quite sure I was using it in 3.0 

**Steps to reproduce:**
1. Download Platformer 3D demo
2. Open it and click with right mouse button on `bullet.scn` inside FileSystem dock

**Link to minimal example project:**

**Comment by kubecz3k** [comment]
I performed a bisection and:
82f896b1ee8c632689baf4bda7e06a9e03c324f5 is the first bad commit

**Comment by kubecz3k** [comment]
@sersoong could you take  a look? Thanks!

**Comment by kubecz3k** [comment]
Probably this line is responsible: 
https://github.com/godotengine/godot/commit/82f896b1ee8c632689baf4bda7e06a9e03c324f5#diff-437a2597f8c2e9b25f7b975bbfd73b2eR1441

**Comment by sersoong** [comment]
Oh,this my fault.I can comfirm it.
Sorry for that.
I will fixed in 24hours.
Sorry again.

**Comment by sersoong** [comment]
I change the entry of that menu.Forgot the two items.

**Comment by kubecz3k** [comment]
@sersoong Cool, thank you! :)

**Comment by sersoong** [comment]
I will fix it soon.
It's too late tonight.
Sorry for my timezone.

**Comment by kubecz3k** [comment]
No need to be sorry, also there is no need to rush. The issue is very much non critical Thank you for contributing in the first place! :)
