### ISSUE TITLE
Setting properties on Particle2d that has been duplicated affects both 

### ISSUE THREAD

**Issue by sionroberts** [godotengine/godot#14404]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Godot 3 Beta (downloaded exe version)
Windows 10 x64

**Issue description:**
Duplicating a particle2d node seems to have the properties linked to both nodes. Setting properties on the first will affect the other. Is this intentional? Maybe properties class is stored as a reference and not instanciated again?

**Steps to reproduce:**
Create a new particle2d. 
Duplicate it.
Select the first one.
Change the properties on it.

**Link to minimal example project:**

**Comment by eon-s** [comment]
Cannot reproduce, which properties have you changed? I have tried with explosiveness, emitting, etc. and everything is working.

**Comment by sionroberts** [comment]
This is what I set on a new Particle2D:

Process Material -> Particle Material

Emission Shape
    Shape:    Box

Scale
    Scale:15
Scale Curve (plot 1 to 0.2 (roughly))


Thanks!

**Comment by sionroberts** [comment]
Maybe it is because Particle Material is copied by ref and is working as designed?

**Comment by eon-s** [comment]
Resources are not duplicated by default, you can duplicate all subresources (make unique) by using the icon on the top right of the inspector (like a screwdriver and other tool) with the Particles Node selected.

Can be done individually by resource with the resource selected in the inspector (like when editing the material) using the same menu, maybe this recommended to not duplicate everything.

**Comment by sionroberts** [comment]
Understood. Thanks. I'll close the issue.
