### ISSUE TITLE
BoneAttachment doesn't work as intended

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1440]
BoneAttachment is not copying bone position, as it is expected,
but is offset from actual bone. Also, offsetting BoneAttachment doesn't help at all.
I can use bone's Transform, but it is workaround, not a fix...

Also BoneAttachment should always be a parent of Skeleton and manipulates its children,
which looks a bit unnatural and unflexible. I'd add some node which behaves more like Joint...
This way it makes possible to have parent scenes to have nodes attached to child's skeleton,
which is more flexible. So, I think ability to select skeleton in node is essential.

**Comment by akien-mga** [comment]
Bumping this up, as I think you have more experience with these parts of the engine now @slapin, so maybe you have a more precise idea on how this should behave and what is the exact bug.

**Comment by slapin** [comment]
Well, it would be more useful if it could select Skeleton, actually an easy fix.
Also, I plan to work a bit on and reshuffle BoneAttachment, this will happen in next two weeks
(no promises though). I also plan to add FK node, but only as soon as my IK PR is reviewed and merged / rejected

**Comment by bojidar-bg** [comment]
Sorry to bump again, but... Code Tirage pointed me here :wink:

**Comment by slapin** [comment]
Well, this one is very old.

the problem was that on various stages of Godot the BoneAttachment node did
various unintended things.

1. This node is copying transform from bone to a point. Sometimes it looks
really weird and it is very hard
to find-out what is going on. The main problem here is that this node makes
some additional restricions on
where to place affected nodes. One can overcome this using physics
constraints, but this adds extra load
on system.

2. Additionally the following misbehaviors was found at different stages of
Godot development:
- was not possible to set properly the offset for object. I.e. you want to
have an apple in hand,
so you add BoneAttachment to hand bone and add apple object as parent. If
bone moves/rotates,
the object will move with offset from intended place, and there is no easy
way to set it to move properly.
Sometimes this offset was quite hard to predict. When one just copy global
transform in code,
this doesn't happen. I don't know if this is valid or not.

I don't remember if this was fixed at some stage. 1. was show stopper for
me so i stopped using
BoneAttachment and used transform copying in fixed_process. Currently I
can't test this,
probably can do this next weekend.

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
