### ISSUE TITLE
Clearcoat effect on materials is too subtle

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#14403]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):** Windows 10, Godot Git https://github.com/godotengine/godot/commit/561490261166a61718e80fe73bc112b8e3cf4b33, NVIDIA GeForce GTX 1080

**Issue description:** The clearcoat effect on materials is too subtle, and isn't noticeable at all on most materials of the [Material Testers](https://github.com/godotengine/godot-demo-projects/tree/master/3d/material_testers) demo; it's only very slightly noticeable on the "mirror" material. This may hint at a bug in the PBR shader.

**Steps to reproduce:** Create a SpatialMaterial, enable its Clearcoat property, then play around with the **Clearcoat** and **Gloss** values.

**Comment by adriansnetlis** [comment]
Yes, I agree that clearcoat doesn't work right.

To me it looks like clearcoat only uses data from light sources and doesn't use reflection map. Clearcoat should also sample reflection map to produce correct results.

**Comment by alukreis** [comment]
Could this be closed given the referenced ticket is closed as fixed.

**Comment by Calinou** [comment]
@alukreis I'm not sure if this was fixed, but I noticed it seems to be closer to the intended effect when using a material with roughness 0.5. Here's a specular highlight on a material with Clearcoat disabled:

![image](https://user-images.githubusercontent.com/180032/65139731-6a0a4a00-da0d-11e9-89ef-d331db3d2529.png)

And this is the same material with Clearcoat intensity and gloss set to 1:

![image](https://user-images.githubusercontent.com/180032/65139717-637bd280-da0d-11e9-8516-01928b133c42.png)

**Comment by Calinou** [comment]
Seems fine as of 4.0.2 (left = no clearcoat, right = with clearcoat, using default properties):

![image](https://user-images.githubusercontent.com/180032/233669413-e27abd65-2299-4811-abbc-5f2cc46cd117.png)

And in 3.6.beta1 too:

![image](https://user-images.githubusercontent.com/180032/233670145-74c28728-9638-4a9b-8aaa-8b0f2aae9052.png)

**Comment by toddwong** [comment]
![a30cdc7879f58149fb1164b079fc744](https://user-images.githubusercontent.com/8896530/233676717-a89d533b-3d52-45d3-8dae-dfd6a805af49.png)

I'm trying to implement the Car Paint effect following this Youtube video https://www.youtube.com/watch?v=dtc3WmL5OTU

The left one is what I achived by Godot 4.0.2, and the right one is by Unity.  Is there anyway I can get the same effect of Unity? What am I missing?

![1682091485722](https://user-images.githubusercontent.com/8896530/233677711-956452a2-1e7a-4518-84ed-00601648ef20.png)

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
