### ISSUE TITLE
In Viewport label text (from particle texture) is upside down

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#14411]
Hi, I tried to use Viewport but seems it is not displayed 

Here a screen-shot
![image](https://user-images.githubusercontent.com/13235119/33770867-f6fa3e0c-dc26-11e7-9114-d524e51a6eaf.png)

**Comment by reduz** [comment]
if you want it to show, it needs to be a child of ViewportContainer

**Comment by git2013vb** [comment]
Thank you for the tip :) 

I guess if I cant see anything in particle2D when I associate that viewport in particle's texture is because I did something wrong?
![image](https://user-images.githubusercontent.com/13235119/33772243-e816c464-dc2b-11e7-8610-0e0a4fa3f2fc.png)

**Comment by reduz** [comment]
no need to put it in normal map, and i have no idea, does other texture
show in the particle system?

**Comment by git2013vb** [comment]
I have some result  - was the viewport rect - but is not what I expected. The label is upside down
Can be the particle orientation?
![image](https://user-images.githubusercontent.com/13235119/33772684-61bde2d8-dc2d-11e7-9826-b4bf586cfbf2.png)

**Comment by ZX-WT** [comment]
@reduz Should there be a warning sign similar to the physicsbody node which reminds users to add a viewport container for this node? maybe I should open an new issue.

**Comment by git2013vb** [comment]
In meantime I turn - with v Flip in viewport - the label.
If I switch in invisible the viewport container the particle keep sowing the label.

![image](https://user-images.githubusercontent.com/13235119/33773413-aaba760c-dc2f-11e7-92f5-814004aa5e43.png)

**Comment by vnen** [comment]
Sorry, but this issue's discussion is quite convoluted and the final issue is not the same as the initial one. Please open another ticket with your specific current problem and follow the template, attaching a sample project if possible.

**Comment by git2013vb** [comment]
Ok, I will do. Thank you :)
