### ISSUE TITLE
3D and 2D Ragdoll setup should be simplified

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1441]
One can't imagine more tedious and gruesome task in current godot than setting up ragdolls.
It is just about copying physic bodies transform to bone poses, but it is very hard to make proper setup.
There is a lot of grey areas here, especially in 3d - what about leaf bones and bone offset calculations?
How to properly setuup proxy-doll of physics bodies having skeleton? yes, there are offsets for all except leaf bones, and you can setup loop in fixed process to copy transforms, but there are a lot of not
so visible problems, like how to set proper positions to RigidBodies to copy skeleton structure? How to handle leaf bones transforms? How to select proper joints? How to limit axis otations on joints?

This all requires some wizad-type class, which should set up ragdoll automatically, havin skeleton and additional parameters. Yes, you can do it by hand, but it consumes enormous amounts of time. And this feature is something for Godot could be proud of
....

**Comment by reduz** [comment]
yeah this is planned for Godot 1.2

**Comment by reduz** [comment]
it pains my heart to move this to 3.1, but we ran out of time for it.

**Comment by AndreaCatania** [comment]
@akien-mga I think so
