### ISSUE TITLE
OS.execute() doesn't execute other godot binaries, executes self again

### ISSUE THREAD

**Issue by daviel** [godotengine/godot#14426]
Fedora 27 - Kernel 4.13.16
Godot 2.1.4
OpenGL renderer string: Mesa DRI Intel(R) Iris Graphics 540 (Skylake GT3e) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.4

When using OS.execute() on godot binaries the already running godot project is started again instead of the referenced one in the function call. I would expect that you can start godot binaries unlimited from within other godot binaries.
I tried relative and absolute paths and running a Shell-script which starts the godot binary with no success though. Also I tried to turn off the shared user dir which too didn't help.

**Steps to reproduce:**
I used following code:
```
var ret = []
OS.execute("godot123", [], false, ret)
```

And here is a example project:
[execute.zip](https://github.com/godotengine/godot/files/1543821/execute.zip)

I found a not-satisfying workaround by running the other godot binary as a different user like so:
```
var ret = []
var proc_id = OS.execute("su", ["-", "godot", "-c", "godot123"], false, ret)
```

Thanks for every help up front. :)

**Comment by akien-mga** [comment]
That's not a bug, the working directory is the one with your `engine.cfg` so that other godot binary will run your project, which is the default behaviour when an `engine.cfg` file is found in the working directory.

If you want it to run the project manager, you can pass `-pm` as parameter.

**Comment by daviel** [comment]
Ah, you're right. I exported my project to a clean dir and tried to run the other godot binary again and now it's working. Thanks 👍
