### ISSUE TITLE
Thumbnails occasionally get glitched

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14425]
Godot 3.0 master
Windows 10 64 bits
nVidia geforce 940M

I just opened the latest screen-space shaders demo from the demo projects:

![image](https://user-images.githubusercontent.com/1311555/33782920-d8aac1a4-dc5a-11e7-92cb-d9d4aad4f1e4.png)

I have this too in my own projects, but not on all resources.

**Comment by PJB3005** [comment]
Seems like a duplicate of #12220

**Comment by Zylann** [comment]
Indeed
