### ISSUE TITLE
Particles are not showing up on exported HTML app

### ISSUE THREAD

**Issue by gururise** [godotengine/godot#14428]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0

**Issue description:**
Using Particles2D node works when exporting to Windows/Linux, but the particles do not show up when exporting to Javascript.

![image](https://user-images.githubusercontent.com/4380009/33786033-614ac304-dc1c-11e7-928c-c7eae675db58.png)
**Left:** HTML Exported  **Right:** Linux

**Comment by akien-mga** [comment]
CC @eska014

**Comment by Kiroto** [comment]
Very sorry to necro, but I'm using Godot v3.2.3 on Windows and I'm experiencing something similar.
My current "game" instances particle nodes on collision, and they show up good on debug, and on windows export, but when exporting to HTML5 (js) they show up very rarely, little, and briefly, about once on every 50 times the particles should show.

I ran it with google chrome, my laptop on and off battery. The computer in question is an Acer Predator Helios 300, if its specs are any use.

Hope the following helps:
Vram texture compression For Desktop is on, For Mobile is off.
I have not touched anything else on that export.
