### ISSUE TITLE
2D rulers are shown but I never chose to

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14424]
Godot 3.0 master
Windows 10 64 bits

I just compiled latest Godot to try one of the demo projects, and after opening the project I noticed the 2D rulers were shown, although I never chose to display them, ever. Is it just me or a config migration issue?

![image](https://user-images.githubusercontent.com/1311555/33782424-f6bea950-dc58-11e7-97e6-534dacc643a8.png)

**Comment by akien-mga** [comment]
They're now on by default, but it's a bug that "Show the rulers" is unticked while they're displayed. CC @groud
