### ISSUE TITLE
Inconsistent "arrow keys/tab/enter" navigation in godot docks

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#14435]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 beta and Godot 2.1.4 - win7 (Fixed)
Edit:
It seems it happend again in Godot 4 beta6

**Issue description:**

First time you change one value from a dock (ej: Inspector) you are able to navigate to the next/previous value with up/down key. Pushing enter allow you to change this value, pushing enter another time consolidate this value, and then.... focus was lost and you can not navigate more with arrow keys (nor with the tab).
With Vector2/3/Matrix,etc... is worst. Pushing enter stores the value but the contextual window doesn´t close until you use the mouse.

**Steps to reproduce:**
Replicate upper paragraph in godot 2 / 3 in windows and probably other versions.

**Comment by Ranoller** [comment]
I think this was almost completely fixed by new inspector, so closing.

**Comment by bsil78** [comment]
Is it back in Godot 4.0 ? I have same troubles in beta6...

**Comment by Ranoller** [comment]
No idea, I´m attached to v3, but I reopen the issue if you think the bad behavior is back.

**Comment by akien-mga** [comment]
This was fixed in 3.1, please open a new issue for problems in 4.0.

**Comment by Ranoller** [comment]
Sorry, my fault.
