### ISSUE TITLE
Is it possible to load shaders from text file?

### ISSUE THREAD

**Issue by Krakean** [godotengine/godot#14431]
Just like script files.
For example, I have working shader:  
https://i.imgur.com/b06eEy5.png

But, I have to put this shader directly to node.
But what if I want three nodes that use same shader? I can CTRL+C, CTRL+V shader to each of them. But what if I decided to change shader? I have to edit code on all those three nodes that uses that shader? 
Can I just put code to separate file (lets say someshader.shader) and specify file like this: 
https://i.imgur.com/i2eMcHK.png

Or there is specific workflow?

**Comment by reduz** [comment]
they are designed for this now, but as far as I know the loader was never
done. It should be rather easy, just keep this open as issue reminder

**Comment by Krakean** [comment]
@reduz Please find some time to finish loader before 3.0 final :)

**Comment by Krakean** [comment]
@reduz Small suggestion: would be nice if public shader parameters that accessible from editor will be independent for all nodes that uses that shader (so I assume one shader will be just compiled N times with different input params and saved as like shadername1.shd, shadername2.shd, ...). 
Simple use case: I have outline shader, it has outline width as public shader param, and I have few objects that will use this outline shader, but for all of them an outline width should be different which will be set just via Inspector.

**Comment by reduz** [comment]
you can use different materials with different parameters but the same shader, and the shader will not be recompiled. It's not a problem if the outline parameter changes on each material.

**Comment by Krakean** [comment]
@reduz 
https://i.imgur.com/MCcz9RI.gifv
What I do wrong? :-\
Have two different materials, both use same shader. But change params on node2 lead to change also and for node1 (though, changing on node1 doesn't make any effect at all, seems like a possible issue may be)

**Comment by djrm** [comment]
@Krakean you need to make the ShaderMaterial resource unique, they will share the shader. there is an option in the tools button 'make unique'

**Comment by Zylann** [comment]
@Krakean if you meant the ability to re-use a shader without copy/paste, you can save it as a `.tres` resource (which is editable but doesn't only contains shader code though).

**Comment by Krakean** [comment]
@djrm 
@Zylann 
Thanks guys, "unique" solved a problem with this one!
