### ISSUE TITLE
GDScript thumbnails in FileSystem-view are not updated correctly

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#14447]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10. Godot 3 nightly build, December 8.

I used the white theme for a while, but switched back to the darker one (new default). However, all of my old GDScript-file thumbnails are still white.

The newly created GDScript file thumbnails are dark, but do not seem to reflect the current theme exactly (background is completely black - when it should be somewhat dark blue, and the text color is off too: the default older yellowish theme(?)).

This is of course not such a big issue... but the mish-mash of white/black thumbnails still makes it harder to separate GDScript files.

Some time ago, there was a temp dir within C:/Users/Me/AppData/Roaming/Godot. I used it in the past to manually purge these outdated thumbnails. However it seems to have moved to somewhere else?

**Comment by akien-mga** [comment]
> Some time ago, there was a temp dir within C:/Users/Me/AppData/Roaming/Godot. I used it in the past to manually purge these outdated thumbnails. However it seems to have moved to somewhere else?

It was moved to `%TEMP%\Godot`.

**Comment by KoBeWi** [comment]
This is how thumbnails generate right now (3.1):
![image](https://user-images.githubusercontent.com/2223172/57198158-dd845100-6f6f-11e9-9a9e-38124fd30982.png)
I guess it's acceptable.
