### ISSUE TITLE
Particles hide when parent node out of screen

### ISSUE THREAD

**Issue by thankjura** [godotengine/godot#14444]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Gentoo, godot 3.0.beta.custom_build.3fd1c0c, GTX 1070

**Issue description:**

Particles hide.

**Steps to reproduce:**
Append particles2D node to rigidBody2d, run scene, if rigidBody out of screen, particles hide

**Link to minimal example project:**

[test_particles.zip](https://github.com/godotengine/godot/files/1544616/test_particles.zip)

**Comment by Ranoller** [comment]
This is not an issue. There is a parameter to control that.

**Comment by thankjura** [comment]
Where is this parameter located?

**Comment by ibrahn** [comment]
Looks like as long as part of the visibility_rect is on screen they're drawn.
The documentation refers to this as "Editor visibility helper."
I'm guessing it's working correctly and the docs just need to be clearer

**Comment by thankjura** [comment]
It workd. Thanks

**Comment by DleanJeans** [comment]
Encountering the same problem but with `CPUParticles2D` which doesn't have `Visibility Rect` under `Drawing`.
