### ISSUE TITLE
Ref cast to pointer does not implement proper const correctness

### ISSUE THREAD

**Issue by Nulifier** [godotengine/godot#1444]
In trying to bind some c++ functions in a module, I notice that when a function takes a `const Ref<T>&` parameter, taking the address of it returns a `const T*` where as it should return a `T*`.

If the current behaviour is wanted, it should take a parameter of `const Ref<const T>&` which would represent a constant reference to a constant object.

I can't think of any other way to pass a reference to a variable in as a parameter without making a copy of a `Ref` which requires a atomic operation.

I would be happy to submit a pull request if this is something that would be merged.

**Comment by akien-mga** [comment]
@reduz WDYT about this?

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by Anutrix** [comment]
Only questions, no answers...
Can someone give me us an update?

**Comment by aaronfranke** [comment]
Is this still valid after the recent core refactoring being done for Godot 4.0?

**Comment by Anutrix** [comment]
@Nulifier Can you please give us on update on this? 

There's just been same questions each with about a year or two for more than 7 years now. Maybe maintainers can close this if it's not valid anymore.
