### ISSUE TITLE
ERROR: ViewportTexture::get_size: Condition ' !vp ' is true. (scene/main/viewport.cpp:105)

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#14445]
ARVR: Registered interface: Native mobile
ERROR: EditorData::get_edited_scene_root: Index current_edited_scene=-1 out of size (edited_scene.size()=0)
   At: editor\editor_data.cpp:607
configure for local: ViewportTexture
vertex uses function: hash
vertex uses function: rand_from_seed
fragment uses function: zero_if_equal
WARNING: not found: editor_plugins/enabled
ERROR: ViewportTexture::get_height: Condition ' !vp ' is true. returned: 0
   At: scene\main\viewport.cpp:100
ERROR: ViewportTexture::get_width: Condition ' !vp ' is true. returned: 0
   At: scene\main\viewport.cpp:95
ERROR: ViewportTexture::get_size: Condition ' !vp ' is true. returned: Size2()
   At: scene\main\viewport.cpp:105
ERROR: ViewportTexture::get_size: Condition ' !vp ' is true. returned: Size2()
   At: scene\main\viewport.cpp:105
ERROR: ViewportTexture::get_size: Condition ' !vp ' is true. returned: Size2()
   At: scene\main\viewport.cpp:105
ERROR: ViewportTexture::get_size: Condition ' !vp ' is true. returned: Size2()
   At: scene\main\viewport.cpp:105
ERROR: ViewportTexture::get_size: Condition ' !vp ' is true. returned: Size2()
   At: scene\main\viewport.cpp:105
ERROR: ViewportTexture::get_size: Condition ' !vp ' is true. returned: Size2()
   At: scene\main\viewport.cpp:105

**Comment by git2013vb** [comment]
I can add a log where there are others
[log-2017-12-08-15-06-51.txt](https://github.com/godotengine/godot/files/1544640/log-2017-12-08-15-06-51.txt)

**Comment by akien-mga** [comment]
You need to be more specific in your issues, just dumping your console log doesn't help much. The various messages shown are either informative strings, or bugs (the first ERROR is #13932, the following warning would have to go in its own bug report, the ViewportTexture errors can't be reproduced here, so I guess they're specific to your project which you are not describing at all).

**Comment by git2013vb** [comment]
My project's zip file will be suffice?

**Comment by Web-eWorks** [comment]
Probably related to #12781. ViewportTextures are rather broken right now, they don't tend to want to actually pick up the viewport they're supposed to be referencing.

**Comment by akien-mga** [comment]
> To give to you the project's zip file I need to clean it from all unrelated stuff first :)

It would be nice to have an example project that reproduces the issue indeed, that would speed up debugging and fixing.

**Comment by reduz** [comment]
I think i most likely fixed this recently, can you try again?

**Comment by akien-mga** [comment]
Fixed by #15528.

**Comment by git2013vb** [comment]
Confirmed too in  my side. thank you.
