### ISSUE TITLE
Godot Shader Language not reporting an error when trying to assign to a constant

### ISSUE THREAD

**Issue by Krakean** [godotengine/godot#14449]
Using latest master
Code example: https://pastebin.com/7X0jcfpt

**Comment by AlmightyScientist** [comment]
I'm not sure I can figure out where you are trying to assign smth to a const.
Could you gimme the line please?

**Comment by AlmightyScientist** [comment]
Yeah seems logic, even if it's not marked as const in docs xD

**Comment by AlmightyScientist** [comment]
Could I have a fresh list of const built-ins ?
