### ISSUE TITLE
Display issues on 4k screen when using fullscreen mode at lower than native resolution

### ISSUE THREAD

**Issue by zejji** [godotengine/godot#14446]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

OS: Windows 10 64-bit
Device: Dell XPS 15 9560 UHD (3840 x 2160 px)
Godot version: Custom build of master as of 08 Dec 2017 (commit 8c78ccb)
GPU: Nvidia GTX 1050

**Issue description:**

When I test my game, I tend to use the following settings in Project Settings > Display:

- Width: 1920 (this represents half the horizontal resolution of the 4k screen)
- Height: 1080
- Resizable: No
- Borderless: No
- Fullscreen: Yes
- Allow hidpi: No
- Vsync: Yes

This leads to a number of issues which are not present when using windowed mode:

- the framerate drops to a third of the framerate for the same resolution in windowed mode (see more details [here](https://github.com/godotengine/godot/issues/9725#issuecomment-350431104))
- the camera view looks zoomed in, as if Godot is rendering to the full 3840 x 2160 resolution but the viewport is only showing the middle section of the buffer.

Please see discussion on [this thread](https://github.com/godotengine/godot/issues/9725#issuecomment-350431104) at for more context.

**Steps to reproduce:**

Use the Display settings listed above for a 3d project on a 4k monitor.

**Link to minimal example project:**

n/a

**Comment by Calinou** [comment]
Note that:

- Godot currently does not support non-native fullscreen on any platforms. This should eventually be done, as performance is higher than by just using undersampled native fullscreen – alt-tabbing will however be slower, as non-native fullscreen requires modesetting every time the user alt-tabs from and to the game.
- Fullscreen on hiDPI displays is currently broken on Godot, at least on Windows. This needs to be tested on Linux and macOS as well.

**Comment by zejji** [comment]
@Calinou 

Many thanks for the information. I've played around a bit and the only combination of settings which gives the correct results for me is as follows:

- disable Windows-provided upscaling as described in your post above; and
- in Project Settings > Display, set:
  - Allow Hidpi: No
  - Stretch - mode: Viewport

The framerate I get is ~20 fps, so slightly worse than windowed mode at the same resolution (i.e. ~30 fps).

**Comment by reduz** [comment]
> Godot currently does not support non-native fullscreen resolutions on any platforms. This should eventually be implemented, as performance will be higher than by just using undersampled native fullscreen (which should still be supported) – alt-tabbing will however be slower, as non-native fullscreen resolutions require modesetting every time the user alt-tabs from/to the game (which takes several seconds).

It sure does support it, the Viewport API allows for setting this manually as you best see it fit.

> Fullscreen on hiDPI displays is currently broken on Godot, at least on Windows. This needs to be tested on Linux and macOS as well.

@Calinou  Link to issue would be nice.

**Comment by reduz** [comment]
I dont have a 4k monitor to reproduce, may have one soon, for now kicking to 3.1

**Comment by reduz** [comment]
This was fixed a few weeks ago, closing.

**Comment by flaviotordini** [comment]
With a 4k monitor and a mac laptop there is a performance problem when HiDPI is enabled. Disabling it returns to normal performance. This is with Godot 4.4.1.

**Comment by Zireael07** [comment]
@flaviotordini Please open a new issue - this one is 8 years old!

**Comment by Calinou** [comment]
> With a 4k monitor and a mac laptop there is a performance problem when HiDPI is enabled. Disabling it returns to normal performance. This is with Godot 4.4.1.

This is expected, as enabling hiDPI means rendering will happen at native resolution, not halved resolution on each axis (which is 25% the pixel count of native resolution).

Use [Resolution scaling](https://docs.godotengine.org/en/stable/tutorials/3d/resolution_scaling.html) with a scale factor of `0.5` to make the 3D rendering render at the same resolution it would when hiDPI is disabled. Note that this will still be a bit slower than hiDPI disabled, as 2D rendering will remain at native resolution. If you also want to reduce the rendering resolution of 2D, use the `viewport` stretch mode and configure the viewport resolution to be half the screen's native resolution.
