### ISSUE TITLE
Vector2 doesn't contains "normalized" method in the C# Pong example. (Mono build)

### ISSUE THREAD

**Issue by CereEnder** [godotengine/godot#14451]
W10, Godot Engine 3.0 beta-1, Nvidia 1050 Ti in a Lenovo y520 i7 7700HQ laptop (8gb Ram)

Trying to run C# example and running. Error thrown in line 31 of Paddle.cs:

`  ball.direction = new Vector2(ballDir, (float) new Random().NextDouble() * 2 - 1).normalized();`

**Comment by Zylann** [comment]
It should be PascalCase

**Comment by akien-mga** [comment]
Yes, the demo should be fixed.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot-demo-projects/commit/296da279ea8d2c2d0b8bc1ae644af0491d35fcfa.
