### ISSUE TITLE
GIProbe data should not be saved in the scene

### ISSUE THREAD

**Issue by vitrig** [godotengine/godot#14450]
Godot version v3.0.beta.build1

When I bake GI Probe the data is saved inside the scene file.

I think it should **not** be saved in the scene, but rather in a separate file, or some cache directory, that can be later excluded from VCS.

The reason for this is that if I a project is maintained under VCS (for example git), every time GI Probe is baked will result in a lot of changes to the scene file.

So each time a little change to the scene is introduced (static object is moved, new object added), GI probe must be recalculated and this data is saved in the scene, and the resulting change is ~5mb in size.

I can try to save GI data as separate file, and ignore it from VCS, but then when the project is cloned and I click bake again (because the GI data was excluded from git), the new GI data is created inside the scene again, so it must be saved again as a separate file.

Imagine doing this for more than 1 probe...

GIProbe data  is a dynamic auto generated data - it doesn't make sense to save it in the scene that is maintained under VCS. In my opinion this must be saved in some cache directory.

This is somehow contrary to #13848

It also makes the `git diff` look terrible...
![image](https://user-images.githubusercontent.com/1430971/33796606-5b7c5bae-dcf8-11e7-9b6f-675faa88fe05.png)

The Reflection Probe does not suffer from this issue.

**Steps to reproduce:**
1. Create scene
2. Bake GI Probe
3. GIProbe data is saved in the scene

**Comment by Zylann** [comment]
Following this logic, the same goes for TileMap and GridMap.

**Comment by Zylann** [comment]
How about making it a resource? This way you can choose to save it as a file.

**Comment by reduz** [comment]
This is up to you, generally for 3D it's recommended you use the .scn binary extension, as .tscn can bloat easily. 

As @Zylann mentioned, if you want to keep using .tscn, just save the resource to a binary file with .res extension.

**Comment by reduz** [comment]
Also the data you save is the prevoxelization, not the dynamic part

**Comment by Zylann** [comment]
Oh, is it a resource already? If yes, problem solved indeed

**Comment by reduz** [comment]
yes the data is in a sub resource, you can save it to disk already

**Comment by vitrig** [comment]
Yes I can save the resource to disk, but if I change the scene and click Bake GI Data, then this newly generated data is not saved to the resource `my_gi_data_resource.res`, but a completely new sub resource is created (what I see is that `my_gi_data_resource.res` changes to `<GIProbeData>` and I have to save it manually again as `my_gi_data_resource.res` in order not to end up with it embedded in the scene.

Ideally I should keep `my_gi_data_resource.res` out of version control, because if it can be generated, it does not make any sense to save it in VCS, because it is a **result of something that is already saved in VCS.**

For the same reason you do not keep compiled binaries under VCS, because they can be generated from the source code.

If I try adding `my_gi_data_resource.res` to `.gitignore` and choose not to commit it. Then after I clone the repository it will not contain `my_gi_data_resource.res`

Godot will complain about missing resources, which is not such a big problem here, because I can regenerate GIProbe again (as it is my intention), but the generated data will not be saved to `my_gi_data_resource.res` but to a new `<GIProbeData>` resource, which I will have to save again manually.

Now I imagine having a scene with 72 GIProbes, and doing this for each one of them manually.

I think the current approach that Godot takes is not too VCS friendly and it would be nice to see it improved.

For now I think I will just commit this data to the VCS, as it is the simpliest way.

**Comment by Zylann** [comment]
I agree re-baking should update the resource rather than recreating it.

**Comment by reduz** [comment]
feel free to attempt a PR for this

**Comment by akien-mga** [comment]
Fixed by #14460.
