### ISSUE TITLE
tooltip placement incorrect from a scroll-area

### ISSUE THREAD

**Issue by Spooner** [godotengine/godot#1445]
Any tool-tips generated by a control that is inside a scroll-area appear on the screen global position based on their position inside the scroll-area. That is, if you have a scroll-area at 100, 100 and a control at 10, 10 within that scroll area, then the control's tool-tip will appear at 10, 10 on the screen, not 110, 110 as they should.

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch / nightly builds?

**Comment by akien-mga** [comment]
Ping :)

**Comment by bojidar-bg** [comment]
@akien-mga I guess it is, even if I haven't tested it, because tooltips always (no matter what the parent element is, etc.) go to global positions.

**Comment by vnen** [comment]
Cannot reproduce this. The tooltip positioning seems to have been fixed.
