### ISSUE TITLE
Add a 'Use in ReflectionProbes' option for MeshInstances

### ISSUE THREAD

**Issue by zejji** [godotengine/godot#14453]
**Issue description:**

If a ReflectionProbe is used with the 'Update once' setting, all meshes in the scene will be included in the generated cube map, even if those meshes belong to dynamic (i.e. movable objects). This can look very strange if a small scene contains a large dynamic object which is later moved or destroyed!

It would therefore be useful to have a 'Use in ReflectionProbes' option for MeshInstances, along the same lines as the 'Use in Baked Light' option.

**Steps to reproduce:**

Create small room containing a large object, a ReflectionProbe and a reflecting surface. Note that the reflections seem perceptually wrong if the large object is moved or destroyed.

**Link to minimal example project:**

n/a

**Comment by clayjohn** [comment]
I don't know what version of the engine this enhancement had in mind, but in Godot 3.x+ ReflectionProbes have a [cull_mask](https://docs.godotengine.org/en/latest/classes/class_reflectionprobe.html#class-reflectionprobe-property-cull-mask) property that does exactly this. It allows you to only render certain objects to the reflection probe.
