### ISSUE TITLE
TTF support to Godot code editor

### ISSUE THREAD

**Issue by EvolutionPixels** [godotengine/godot#14457]
Will TTF support be added in the Code editor? So that you can select TTF except FNT.

**Comment by akien-mga** [comment]
Normally it's supported, but maybe the settings are not properly exposed and should be changed to accept TTF files.

**Comment by Zylann** [comment]
I successfully changed the code editor font with `Consolas.ttf` using editor settings after doing this PR: https://github.com/godotengine/godot/pull/11512

The only problem with it is that the font cannot be outside of the project for some reason...

**Comment by EvolutionPixels** [comment]
![001](https://user-images.githubusercontent.com/12032252/33798118-5d286f5c-dd24-11e7-986b-c689177b44c9.PNG)
![002](https://user-images.githubusercontent.com/12032252/33798119-5d546922-dd24-11e7-9488-29457c0fbd3c.PNG)

**Comment by Zylann** [comment]
Currently it can load a `DynamicFont`, so if you create a DynamicFont in your project you are able to assign it. While this works already, it still involves an extra step, so it should be improved to accept the source font file types (ttf, otf, etc) and have the DynamicFont be created internally.

**Comment by EvolutionPixels** [comment]
Anyone who has encountered the same problem as me will leave an answer to this question.

https://godotengine.org/qa/20870/how-do-you-bring-fonts-into-godot-3-0

Thanks Zylann that left a detailed answer on the link above.

**Comment by akien-mga** [comment]
Fixed by #15073.
