### ISSUE TITLE
Mouse relative motion jumps when mouse mode is set to captured, causing freelook to also jump

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14463]
Godot 3.0 master
Windows 10 64 bits

I noticed that very often and quite randomly, when I use freelook, the camera does big rotation jumps, which makes it rotate from a completely offset target, it's very annoying.

Repro:
Use RMB freelook to look left repeatedly in short drags. You will notice that half of the times, the camera jumps back first before looking to the left.

I printed the relative mouse motion and noticed the jump comes from the input system:

![image](https://user-images.githubusercontent.com/1311555/33798499-e58172a0-dd19-11e7-8e1f-7181bc7c650b.png)

The only guess I have is, that the input system is being fooled by FPS cursor capture (which warps the cursor at the center), and considers it as mouse motion. It would affect any kind of game where you have both FPS phases and GUI phases.

A fix would be to reset previous mouse position when it gets warped like this, but I have no idea where this cached state is... (but it would obviously create a discontinuity in relative motion)

**Comment by bruvzg** [comment]
Same on Linux and Wine but looks ok on macOS.

**Comment by Zylann** [comment]
I tried to write a local fix (so to fix only freelook) but I found that even `Input::get_mouse_position()` yields positions from BEFORE mouse warping, so I am unable to fix this... something should be done at a lower level.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by Iris616** [comment]
A game is currently unplayable (on my system, doesn't happen on some OSes) due to this issue.
(https://bauxite.itch.io/meteorite)

**Comment by akien-mga** [comment]
This should now be fixed (at least on Windows) with #20523 and 2db4942, can you confirm?

**Comment by reduz** [comment]
It is fixed, closing
