### ISSUE TITLE
Error with the scenes

### ISSUE THREAD

**Issue by XavierDD1st** [godotengine/godot#14472]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.4 64bit stable windows 10 64bit

**Issue description:**

So when working on my game I saved and exited and lost most off the imports and lost the ability to open older scenes.

**Steps to reproduce:**
I don't know how it happened

**Link to minimal example project:**

**Comment by XavierDD1st** [comment]
Also I was wondering if there is a way to decompile the data.pck file so I could use an older version.

**Comment by Silvea12** [comment]
May you please attach your project, or a version of your project with as much removed as possible that still reproduces this error? The information you have provided thus far is not enough to really do anything about this issue.

**Comment by vnen** [comment]
Yes, this needs more information. It's impossible to tell what happened. One thing that crossed my mind is that you mistakenly used the 3.0 converter and it changed the assets to match the 3,0 format.

Decompiling the PCK isn't impossible, but there's no tool for that. It's likely that the scripts are compiled to a binary format, which would make it quite hard to recover.

**Comment by XavierDD1st** [comment]
Yeah that must of happened.

**Comment by akien-mga** [comment]
As mentioned above, there's no easy way to go back to the previous state and we can't really know how it broke, but using the 3.0 converter might be a potential culprit. When 2.1.5 is released it will no longer allow to export directly in the project folder, so that might prevent this.
