### ISSUE TITLE
IntersectRay always returns shape_idx=0

### ISSUE THREAD

**Issue by RomanAkberov** [godotengine/godot#14473]
**Version: Godot 3.0 beta1**
As can be seen [here](https://github.com/godotengine/godot/blob/33a59993945fb313309c8a68fe5d6e48b2bd1874/modules/bullet/space_bullet.cpp#L100), ray casting implementation always sets shape index to 0, yielding incorrect results.

**Comment by akien-mga** [comment]
CC @AndreaCatania
