### ISSUE TITLE
Omni light dual paraboloid shadows are broken

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#14487]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10 current Godot 3 build

**Issue description:**
When changing the shadow mode on an omni light from Cube to Dual Paraboloid, the shadow disappears. If you increase the Shadow>contact amount from the default 0, the shadow does start to appear but looks very incorrect.

Not sure exactly when this broke, but I tried this on a build from about a month ago and it looks correct:

![dual_para_bug1](https://user-images.githubusercontent.com/7741669/33801211-0a64b74c-dda8-11e7-8e45-be6f8ef39f99.jpg)

And here is the same scene on a current build. The dual paraboloid shadow light is on the right:

![dual_para_bug2](https://user-images.githubusercontent.com/7741669/33801217-30150596-dda8-11e7-8a21-4b3c5d30c2da.jpg)

**Steps to reproduce:**

**Link to minimal example project:**

[omni_shadow_bug.zip](https://github.com/godotengine/godot/files/1545258/omni_shadow_bug.zip)

**Comment by reduz** [comment]
Can you (or anyone else) bisect? that would be highly appreciated.

**Comment by Noshyaar** [comment]
284f8f6
```
commit 284f8f6d91d7c9663fe8b25aa652265579b412a6
Author: Chaosus
Date:   Sat Nov 25 23:18:01 2017 +0300

    Fixed invalid transform when skip_vertex_transform used
```
