### ISSUE TITLE
The AcceptDialog does not set the properties of the font

### ISSUE THREAD

**Issue by wetiontop** [godotengine/godot#14492]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOS 10.13.1
Godot v3.0.beta

**Issue description:**

When I use AcceptDialog, I can‘t set the font and font color of the title and text.

**Steps to reproduce:**
new a AcceptDialog see the Control property
![qq20171210-102557](https://user-images.githubusercontent.com/4017034/33801492-e5567b1c-dd97-11e7-809d-b7d151856a9d.png)

**Comment by KoBeWi** [comment]
This is not a bug. These properties are inherited from WindowDialog, so you are supposed to use a Theme resource or override it in script. Also this is irrelevant in 4.0, because it uses native dialogs.
