### ISSUE TITLE
Starting the editor/project manager freezes main display for 3-5 seconds

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#14504]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 x64, current master @  bf45e56

**Issue description:**
When I start Godot the main display freezes for anywhere from 3 to 5 seconds until the project manager opens. When I open a project, this happens again until the editor shows up.

Not that secondary displays are fine and can be used, only the content on the main screen locks up.

This did not happen as of a few days ago, so this is likely a regression.

**Comment by Zireael07** [comment]
What is your GPU? (just in case it turns to be relevant)

**Comment by mhilbrunner** [comment]
GeForce GTX 980 Ti. Currently trying to bisect to find out which commit caused it.

**Comment by mhilbrunner** [comment]
Please don't invest any time in this, seems this could be caused by a driver issue on my side, will update later.

**Comment by mhilbrunner** [comment]
Confirmed as a driver issue, seems my driver crashed, got somehow corrupted and didn't fully work.
Reinstalled drivers and now everything is fine again.

Of course, I only realized this after bisecting through the last few days worth of commits to find the issue. D'oh! Closing.
