### ISSUE TITLE
Project manager opens instead of game

### ISSUE THREAD

**Issue by levrik** [godotengine/godot#14508]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win 10, 3.0 Beta 1

**Issue description:**
Sometimes the project manager opens instead of the game when I click the play button.

**Steps to reproduce:**
Not sure yet. Seems to be really random. Trying to figure out reproducible steps.

**Comment by DarkEngineer** [comment]
i wrote this issue earlier and it's fixed now at master branch

**Comment by levrik** [comment]
Ah. Didn't found your issue then.
Closing.

**Comment by akien-mga** [comment]
Duplicate of #11391 indeed.
