### ISSUE TITLE
Godot CSG map editor where you draw walls with custom textures?

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#14506]
Would it be possible to add the ability to edit maps in Godot Engine the classic Quake 1 way ? Have 4 views and draw walls and add textures on the wall and build an environment that way.

The whole thing would be dynamic.  

Pikachu mentioned on discord it would require CSG 

This would add the ability to draw meshes in-engine  on a basic level enough to make an environment.  This would be great for prototyping as well.  I don't need Godot to become a 3D editor only to be able to do draw meshes in the engine directly. 

If not then at least some basic CSG tools exposed so I or someone can build an editor plugin on top of that. 

According to Mes.tres there is no open CSG library available that is compatible with MIT so godot would have to build their own :(

**Comment by vnen** [comment]
Looks the same as #4304.

**Comment by trollworkout** [comment]
@vnen  should I close this?

**Comment by mhilbrunner** [comment]
Yeah, should be fine to close. :)
