### ISSUE TITLE
Crash: Vector<AudioServer::Bus*>::operator[]: FATAL: Index p_index=0 out of size

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#14502]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 x64, master @ bf45e56

**Issue description:**
Created a new, empty project. Exited the editor.
The editor crashed with the following output:
```
ERROR: Vector<struct AudioServer::Bus *>::operator []: FATAL: Index p_index=0 out of size (size()=0)
  At: c:\godot\godot\core\vector.h:137
```

![crash](https://user-images.githubusercontent.com/1654763/33805162-62c9fd50-ddb4-11e7-9ee6-39e9507305d0.png)

**Comment by akien-mga** [comment]
CC @marcelofg55.

**Comment by akien-mga** [comment]
@mhilbrunner Could you get a backtrace? Also, does it really crash? If so isn't there already a backtrace?

**Comment by mhilbrunner** [comment]
That was the only CLI output, I'll see if I can get a backtrace :)

**Comment by marcelofg55** [comment]
Crashes every time? Or is it a random crash? A backtrace would be most helpful :)

**Comment by mhilbrunner** [comment]
Only happened one time upon closing the project, worked fine the other 20 times I tried... I'll try to get a backtrace, but first I have to see if I can reproduce it. :/

**Comment by mhilbrunner** [comment]
I couldn't reproduce this, as often as I tried. As I had some driver issues, it could be that it was caused by that. As this only happened that one time and only on exiting, I'll close this for now, if it happens again or for someone else we can reopen it.
