### ISSUE TITLE
Adding nodes without root node present only works correctly when no node was ever parented previously

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#14503]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Current master @  bf45e56

**Issue description:**
https://github.com/godotengine/godot/pull/13166 was a vast improvement for how creating a node in a new scene without a root present works, but seems to still have an unhandled case:

First, it works as expected:
1. Drang-and-drop a file from the FileSystem pane into a empty scene
2. The popup asks if the new node should be created as root *Sprite*, *Light2D*, etc.
3. Choose one, hit *OK*, the node gets created as a root node, everything works

You can even click on the new node in the scene, delete it, and repeat. Works.

But: Do the following, and it no longer works:
1. Drang-and-drop a file from the FileSystem pane into a empty scene
2. The popup asks if the new node should be created as root *Sprite*, *Light2D*, etc.
3. Choose one, hit *OK*, the node gets created as a root node, everything works
4. Select the created node in the scene, and now drag and drop another node into the scene
5. The new node gets created with the previous node as the parent
6. Delete both
7. Now retry from 1, when you press *OK* in the popup, nothing happens, you can no longer create root nodes this way

**Comment by akien-mga** [comment]
CC @Krakean

**Comment by Krakean** [comment]
@akien-mga @mhilbrunner 
got it, will take a look today

**Comment by mhilbrunner** [comment]
@Krakean If you need any clarification to reproduce this or anything else from me that can help, just ask :)

Thanks for your work on this!

**Comment by Krakean** [comment]
@mhilbrunner done #14533, test it when you will have time
