### ISSUE TITLE
Show how many matches have been found when searching in the code editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#14513]
Currently, it only states if matches have been found or not, but it would be really nice if it displayed how many matches have been found as well.

**Comment by breakmt** [comment]
Yes, it could be very usefull sometimes.
It might be label "Found N occurrence(s)." for Find and Replace functions by analogue with "Replace N occurrence(s).", but with gray colored font.
![2019-04-21_114609](https://user-images.githubusercontent.com/1552169/56467915-d288d700-642d-11e9-97e0-2b361fbd7883.png)
