### ISSUE TITLE
Moving files doesn't updates their path in script editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14522]
Godot 2.1.4
Windows 10 64 bits

I moved a lot of files to reorganize a project, and it worked well when I played the game.
Then I worked on a script, but when I wanted to save the script Godot asked me to create new files:

![image](https://user-images.githubusercontent.com/1311555/33808625-36c75fa0-ddea-11e7-8d6b-9f83e33fab7d.png)

It looks like the path of scripts that were open already was not updated by all the moves.

I also tried to close all scripts to reopen them as a workaround, but I am not able to do so without saving them:
![image](https://user-images.githubusercontent.com/1311555/33808639-7ddffa28-ddea-11e7-8eb2-ebe86b6601ad.png)
"Ok" would create a new file I don't want, and "Cancel" leaves the file open...

So I closed and reopened the editor... only to find out Godot still saved the script, so I have to tidy the mess again, the loop repeats...
I guess I'll have to delete my cache settings.

**Comment by bojidar-bg** [comment]
I have seen this as well.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Zylann** [comment]
I think it's fixed now.
