### ISSUE TITLE
Cannot inspect nodes with remote scene tree

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14536]
Godot 2.1.4
Windows 10 64 bits

I tried using the remote scene tree, and I noticed I couldn't inspect remote nodes with it, and the selected node gets deselected every second:

![image](https://user-images.githubusercontent.com/1311555/33812148-351ce00e-de1b-11e7-9f6c-71f3f178716d.png)

**Comment by eon-s** [comment]
Look at the Inspector dock :eye:

**Comment by Zylann** [comment]
Oh, it was moved here?
But... what is the right panel used for then? Is it object property dictionary? (I remember there was a request to be able to edit that one in general)

**Comment by eon-s** [comment]
The right panel was not removed when the improvements on the remote inspector were made (I think is gone now on 2.1/HEAD), there is a similar panel when you get errors and breakpoints on the debugger tab (with variables, etc.).
