### ISSUE TITLE
Pasted text ignore cursor position if text typed fast enough.

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#14539]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 Pro 64
Godot 3
Build date: 2017-12-08 11:45:30
Git commit id (short): b3b4727df

**Issue description:**
If you type fast enough and then immediately paste afterwards the pasted text will be placed before the location where you start typing.

https://i.imgur.com/PqSSiAj.gifv
https://i.imgur.com/8cLvpF6.gifv

**Comment by bojidar-bg** [comment]
Does the copied text contain a newline?

**Comment by vnen** [comment]
I've seen this too. It happens even if the copied text doesn't have a newline. It seems to only happen with text copied from other places.

**Comment by akien-mga** [comment]
Fixed by #14772.
