### ISSUE TITLE
Signal with 'Extra Call Argument(s)' will not automatically added in functions creation

### ISSUE THREAD

**Issue by AkatDeen** [godotengine/godot#14544]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64 bit, Godot 3.0 beta 1

**Issue description:**
Signal with 'Extra Call Argument(s)' will not automatically added in functions creation

**Steps to reproduce:**
1. Create a button
2. Create a script and attach it to any node (suppose to be reacted by the button's pressed() signal)
3. Add Extra Call Argument (any type will do, in this case just try with Bool)
4. in Connect To Node' window, select the node with the script created in the above step
5. Click 'Connect' - the function '_on_button_pressed()' function will be created in the script
6. Compile / Play and click the button will return an error _on_button_pressed:Method expected 0 arguments, but called with 1

solutions:
1. need to add the argument manually in the function --> _on_button_pressed(var dir)

**Comment by DualMatrix** [comment]
Tested in master, the parameter is still missing.
