### ISSUE TITLE
The camera2D smoothing is always active even the Enabled is switching off

### ISSUE THREAD

**Issue by tobia88** [godotengine/godot#14545]
![default](https://user-images.githubusercontent.com/2604688/33819487-a808ff02-de85-11e7-92ab-b7a093c44c2a.PNG)
The camera2D is always smoothing even the toggled is off, i can only set speed to 0 for terminating the camera smoothing

**Comment by volzhs** [comment]
I can't reproduce it with official beta 1 and current master head 2314f0c

![image](https://user-images.githubusercontent.com/8281454/33819755-65cb83da-de8f-11e7-8aa6-43a601c1b859.png)

```gdscript
extends Sprite

func _ready():
	$Timer.connect("timeout", self, "change_pos")
	pass

func change_pos():
	position = Vector2(rand_range(100,1000), rand_range(100,700))
```

it respects smooth on/off option as expected.

**Comment by mhilbrunner** [comment]
So was this just in a old version? Or in 2.1? Any information @tobia88?

**Comment by bojidar-bg** [comment]
Given the lack of activity and the inability to reproduce, I will close this issue as fixed. If someone can reproduce it, feel free to write, and it would be reopened.
