### ISSUE TITLE
the rotation of PathFollow2D in 3.0 is weird.﻿

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#14554]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0

**Issue description:**

just tale the tutorial http://docs.godotengine.org/en/latest/learning/step_by_step/your_first_game.html
for example.
The rotation of the PathFollow2D is  not expected as 2.1 when set_offset to different values.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
>  3.0

Be more specific.

**Comment by volzhs** [comment]
maybe same issue with #13361?

**Comment by alexzheng** [comment]
I'm not sure, check this demo:
It seems the rotation value is wrong
[demo.zip](https://github.com/godotengine/godot/files/1553949/demo.zip)

**Comment by vnen** [comment]
I'll assume it's the same issue, which was already solved. Comment if it's still present in a more recent version.
