### ISSUE TITLE
Remove irritating Interface > Dialogs category from Editor Settings

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#14550]
As discussed in https://github.com/godotengine/godot/pull/14549, I wanted to prevent the `interface/dialogs/*` settings to be visible in the Editor Settings because:

- Configuring saved window bounds for a handful of selected windows via a Rect2 property editor is needlessly overcomplicated
- The user can indirectly modify this editor settings by actually moving / resizing those windows
- Modifying `editor_settings_bounds` doesn't work anyway as it is overridden when the Editor Settings window is closed
- The category is irritating and might suggest more usefully configurable settings here

![image](https://user-images.githubusercontent.com/9631152/33830821-06c7d6ae-de76-11e7-87b4-727d61c331c5.png)

I [originally implemented hiding it](https://github.com/godotengine/godot/pull/14549#discussion-diff-156055723R4522) in the PR linked above by skipping over the category with a hardcoded check for the name, but that's not a good solution as pointed out by @akien-mga .

How would I be able to hide such "indirectly useful but directly useless" settings from the Editor Settings without the need for hardcoding category names?

**Comment by bojidar-bg** [comment]
Shouldn't we keep this information separate from the settings, for example alongside layouts?

**Comment by RayKoopa** [comment]
Interesting idea, I like it so far.

**Comment by groud** [comment]
If those should not be configurable, just "hardcode" the values in the editor code.
Like in settings_dialog_config.cpp: line 98, 99 and 144.

**Comment by RayKoopa** [comment]
I don't have such file, can you link to it? We previously discussed not to hardcode hiding them as linked above.

**Comment by groud** [comment]
Sorry I meant[ `settings_config_dialog.cpp`](https://github.com/godotengine/godot/blob/master/editor/settings_config_dialog.cpp).
Yeah, instead of hiding them, you just don't make them configurable. You can make the value an attribute of the class for example.

**Comment by RayKoopa** [comment]
Then the whole category is useless, just displaying read-only values. Nah, that's still ugly IMHO. Get rid of them in the settings, there's already too much in them.

**Comment by groud** [comment]
Yeah, if you don't make them configurable, it means removing them from the settings... The category will be removed automatically once you removed all the properties inside it.

**Comment by RayKoopa** [comment]
Oh nice, I didn't know that it works like that exactly. What property do I have to specify then?

**Comment by groud** [comment]
I don't get what you mean. For example at line 144, instead of:
`EditorSettings::get_singleton()->set("interface/dialogs/editor_settings_bounds", get_rect());`
you can define an attribute called "editor_bounds" of the class maybe. And put instead:
`editor_bounds = get_rect()`

But I'm not sure it could work like that, as the property may need to be global.

**Comment by RayKoopa** [comment]
And how are the window bounds stored and restored from settings if it's just a temporary field of the class?

**Comment by groud** [comment]
Reading the code, it might work by just putting an underscore before the property name.
So that `EditorSettings::get_singleton()->set("interface/dialogs/editor_settings_bounds", get_rect());` becomes `EditorSettings::get_singleton()->set("interface/dialogs/_editor_settings_bounds", get_rect());`

**Comment by RayKoopa** [comment]
No, it still appears then.

**Comment by Hinsbart** [comment]
You could also put them in the project metadata file. (`EditorSettings::set_project_metadata()`)

**Comment by RayKoopa** [comment]
It's saved per-project then, if I got that right, I'm not sure if that makes sense. Per-layout would make more sense, aka @bojidar-bg 's solution

**Comment by groud** [comment]
Yeah, probably that @bojidar-bg makes sense too. I'm allright with that.

**Comment by Calinou** [comment]
This appears to have been mostly resolved in the `master` branch. Only one `dialogs/` setting will be saved now when you close the 2D polygon UV editor:

https://github.com/godotengine/godot/blob/4e0f31a67cb757f95a658a02ac28afcdda40b299/editor/plugins/polygon_2d_editor_plugin.cpp#L266-L270
