### ISSUE TITLE
Conversion of scene import plugin to gdnative fails

### ISSUE THREAD

**Issue by fire** [godotengine/godot#14557]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Master...

**Issue description:**
Opened an issue for tracking purposes. Gdnative version of scene import plugin fails. 

**Steps to reproduce:**
Convert https://gist.github.com/vnen/c63d88f17fc44697d27a56ef24d641b3 to C++...

Drag a blank file called test.myext to dock and see it fail to import.

Create a new folder and a file you put in the filesystem shows.

@karroffel

**Comment by karroffel** [comment]
It actually works, it just breaks when it unloads libraries when you tab out.

I'm not sure how to solve this the best way. If you are working on an editor plugin you need to restart the editor anyway, so an idea is to have a new field in a GDNativeLibrary for `run_in_editor` and then those won't be reloaded. This would have the consequence that tool scripts would need to be in a separate library resource than non-tool scripts. I'm not sure how much of a loss that would be.

cc @endragor

**Comment by fire** [comment]
Can you post your copy of the plugin? It would also make a good tools plugin tutorial.

**Comment by fire** [comment]
@karroffel Can you pick a way? I would like to see it in a beta.

**Comment by karroffel** [comment]
@fire this is the project I used to test. It is working, but as I said, as soon as the editor loses focus it's no longer working.

[PluginTest.zip](https://github.com/godotengine/godot/files/1580970/PluginTest.zip)

**Comment by fire** [comment]
@reduz 

Can you give some design commentary for this? This is the patch that throws away the unloading, but it needs a better method. @karroffel is still on vacation

https://github.com/godotengine/godot/blob/master/modules/gdnative/nativescript/nativescript.cpp#L1099

![2017-12-29_06-51-53](https://user-images.githubusercontent.com/32321/34440212-7b1db67c-ec68-11e7-9b74-c5018c4f8141.png)
