### ISSUE TITLE
Multiple problems with TextEdit selection while indenting

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#14559]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Current master: 1401b07

**Issue description:**
Making indentations while having text selected has the following problems:

- [ ] Indenting to the left will remove a character from the start of the selection (this also happens when undoing right indentations):
![screenshot at 2017-12-11 13-52-30](https://user-images.githubusercontent.com/30739239/33840149-3b6934a2-de7b-11e7-8571-12c983177c79.png)

- [x] Indenting to the right will add a character from the start of the selection:
![screenshot at 2017-12-11 13-58-06](https://user-images.githubusercontent.com/30739239/33840185-587c3670-de7b-11e7-839c-8c21a3ee984b.png)

- [ ] Undoing left indentations will remove a character from the end of the selection:
![screenshot at 2017-12-11 13-53-54](https://user-images.githubusercontent.com/30739239/33840115-23f5e0ae-de7b-11e7-8df8-1e87d3c99a22.png)

- [x] There were also times that the indentation options vanished from the context menu, but I'm not sure what causes this.

**Comment by MattUV** [comment]
>There were also times that the indentation options vanished from the context menu, but I'm not sure what causes this.

I never encountered that issue...
Currently the context menu displays these options when there is a selection, maybe we could remove that option and show it all the time?

**Comment by YeldhamDev** [comment]
@akien-mga This shouldn't be closed yet:

> However, I was unable to fix the 3rd issue, nor the 2nd part of the 1st issue. I have some troubles with the "undo" part, I can't figure out how to record the selection in TextOperation. Maybe a dedicated issue would be a good thing, as it would keep selections even when undoing a text deletion.

**Comment by MattUV** [comment]
I am too busy this weekend to do it, but I will open a new issue for that on Monday.
The real problem is more general: the selection is not stored into the history of actions, so it is not retrieved when undoing.

**Comment by SeleckyErik** [comment]
The issue seems to be resolved now? No characters are added, nor removed from the selection while doing indentations. The only "issue" is that undoing actions in `TextEdit` cancels selection - but this seems like an intended behaviour.

I suggest closing the issue. #14835 is still relevant and up for discussion.

**Comment by YeldhamDev** [comment]
@SeleckyErik Yep, seems that those issue where fixed. Closing it.
