### ISSUE TITLE
Roughness = 1.0 with Vertex Lighting gives artifacts

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#14552]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
237be766d4b0247d7ded0a9b85da12a989c561c8 Ubuntu 17.04 debug build

**Issue description:**
When setting vertex lighting on material together with roughness =1 graphic artifacts will appear
![peek 2017-12-11 13-21](https://user-images.githubusercontent.com/6129594/33830896-46e915cc-de76-11e7-836f-6166662b337d.gif)

**Steps to reproduce:**
1. Create new scene with ~`DirectLight`~ `Directional Light` and `MeshInstanceNode`
2. Create new Sphere mesh and `SpatialMaterial` for `MeshInstanceNode`
3. Inside material set `vertex lighting` flag and `roughness` to 1.0

**Link to minimal example project:**
[VertexLightingRoughness.zip](https://github.com/godotengine/godot/files/1547715/VertexLightingRoughness.zip)

**Comment by AlmightyScientist** [comment]
I'm on it :)

**Comment by kubecz3k** [comment]
Yes, sorry it was Directional Light (corrected in reproduction steps)

**Comment by AlmightyScientist** [comment]
Seems like I can't reproduce, DirectLight is a direct child of the root node, isn't it?
