### ISSUE TITLE
Object.rotate rotates in global space

### ISSUE THREAD

**Issue by DKesserich** [godotengine/godot#14569]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot 3

**Issue description:**

When rotating an Spatial object using the rotate(Vector3 normal, float radians) function, or rotate_x, rotate_y, rotate_z, the object will use the global axes for rotation instead of local.

Per the documentation (http://docs.godotengine.org/en/latest/classes/class_spatial.html?highlight=rotate#class-spatial-rotate) rotate functions should operate in local space, not global.

**Steps to reproduce:**
1. Create a new Spatial scene.
2. Add a camera to the scene.
4. Rotate the camera so it is facing down the X axis.
3. Add some objects to the scene (for points of reference)
4. Add the following script to the camera:
```
func _process(delta):
	if Input.is_key_pressed(KEY_W):	
		rotate_x(deg2rad(2.5))
		print(rotation)
	if Input.is_key_pressed(KEY_S):
		rotate_x(deg2rad(-2.5))
		print(rotation)
	if Input.is_key_pressed(KEY_Q):		
		rotate_y(deg2rad(2.5))
		print(rotation)
	if Input.is_key_pressed(KEY_E):
		rotate_y(deg2rad(-2.5))
		print(rotation)
```
5. Run the scene and press W or S to rotate the camera up or down.
6. Observe that the camera will rotate on the global x axis (spin sideways) instead of the local x axis (look up or down)

Note: I know you can use get_transform().basis.axis.normalized() to get the local normal, but if you have to do that then these rotate functions are redundant with rotate_global.

**Comment by reduz** [comment]
maybe a local_rotate should be added?

**Comment by reduz** [comment]
Ah I see the problem

**Comment by tagcup** [comment]
As a cross reference, this behavior of object-local rotations can now be realized by using `rotate_local` method now that #15083 is merged.

@DKesserich, the documents are now clear about the word "local". What you describe is a transformation that takes place in spatial object's local coordinate system, and it is now referred to as *object-local* in the docs. The transform in godot (and also unity, blender, etc...) are written in parent's local coordinate system, and it is now referred to as *parent-local* to avoid further confusion.

**Comment by Mimerme** [comment]
This has been reintroduced in v4 I believe
