### ISSUE TITLE
Inconsistent behavior of delete key

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#14568]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64bits, Godot 3.0 beta1

**Issue description:**
- Clicking on a node and pressing "delete" shows the confirmation window for deleting that node
- Clicking on a key frame in the Animator timeline and pressing "delete" deletes said key frame
- *However*, clicking on a file in the filesystem panel and pressing "delete" shows the confirmation window for deleting the **node** that's currently selected on the scene panel rather than a confirmation window for the selected **file**. 

This behavior is inconsistent and unexpected being that Godot has an otherwise pretty standard UI/UX and can lead to the user accidentally deleting nodes while intending to delete files.

**Comment by turtletooth** [comment]
The same is true in visual scripting.  Clicking a function or variable and hitting delete tries to delete a node.
