### ISSUE TITLE
Button logic incorrect

### ISSUE THREAD

**Issue by Spooner** [godotengine/godot#1456]
Press down on a button. Move the mouse away from the button. Release the mouse button. The button is shown in its "hover" state, only returning to default view after moving the mouse again.

**Comment by Spooner** [comment]
Also, if you release over another button, that button doesn't show hover until you move the mouse.

**Comment by reduz** [comment]
i think this only happens if you have many buttons without a parent
control, this is a known bug but it's difficult to fix so it will be fixed
for 1.2

**Comment by akien-mga** [comment]
Can you still reproduce this issue in the current master branch / nightly builds?

**Comment by reduz** [comment]
this bug was fixed recently, should be no more
