### ISSUE TITLE
Repeat flag to fill with transparency

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#14571]
As it stands, if you try to render a texture outside of its boundaries, it'll do one of 3 things, depending on the Repeat import flag:
* Draw the closest pixel row over and over, with Repeat disabled.
* Repeat the texture over and over, with Repeat enabled.
* Repeat the texture mirrored over and over, with Repeat set to mirrored.

My issue is that, in order to greatly simplify a lot of shaders that need to draw outside of a Sprite's texture boundaries, such as a bloom shader, it would be very useful to have a fourth option here, that treats all pixels outside of the texture's boundaries as transparent, so that a shader can properly detect the texture's alpha outlines.

As an example of what this would accomplish, I've written an outline shader that, in order to avoid the cut-off you see around the edges in the 2D material demo, extrudes the Sprite's vertices and then re-maps the UV to draw the sprite as it usually looks, thus creating would-be empty space around the texture that the shader can draw to.
Issue is, with the current behavior of either repeating the closest pixel row/column or repeating the texture in this area, it ends up looking like this:
![9qf5rml](https://user-images.githubusercontent.com/20242421/33854816-5328de2e-dec3-11e7-990c-2423a7a5a5a2.gif)
As you can see, the UV scaling and the vertex extrusion works fine, but the texture extends the closest rows outward.
(The `Enabled` checkbox disables the entire shader code, in case that isn't obvious.)

Would it be possible to add a fourth behavior for this? I think most people would intuitively expect `Repeat: Disabled` to behave like what I'm asking for instead of drawing garbage rows, but making it another option entirely would work too, in case something like this is more taxing on the GPU or something.

**Comment by mrcdk** [comment]
There is nothing godot can do about this, that's how GPUs work. You'll need to deal with that on your shader.

**Comment by leoddd** [comment]
Ah, I see. Alright.
