### ISSUE TITLE
Create new node tooltip is larger than the text

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#14570]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64 - 1401b07

**Issue description:**

![screenshot from 2017-12-12 04-21-26](https://user-images.githubusercontent.com/26753932/33854443-5d3be5ec-def4-11e7-8cec-1b8c7e118fe8.png)

**Comment by akien-mga** [comment]
Fixed by #14713.
