### ISSUE TITLE
CollisionObject input_event signal doesn't provide valid shape_idx

### ISSUE THREAD

**Issue by MrOneTwo** [godotengine/godot#14575]
I imported a Collada model. It uses colliders made in Blender with ```-colonly```. The top Spatial Node has a script which goes through all the nodes and if the node is a ```StaticBody```
 it connects its ```input_event``` signal to the function in this script.

The problem is that when you click on the object the function properly passes all the arguments except ```shape_idx```. It always has 0 value. Im trying to pick objects by clicking on them in 3D space.

So here is the objects structure:
![](https://u.cubeupload.com/khatake/TPMCfQ.png)

And here is the code:
```
extends Spatial

func getallnodes(node):
	for N in node.get_children():
		if N.get_child_count() > 0:
			print("["+N.get_name()+"]")
			getallnodes(N)
			if N is StaticBody:
				N.connect("input_event", self, "clicked_on", [])
		else:
			# Do something for the childless nodes
			print("- "+N.get_name())

func _ready():
	getallnodes(self)

func _process(delta):
	pass

func clicked_on(camera, event, click_position, click_normal, shape_idx):
	if event is InputEventMouse:
		if event is InputEventMouseButton:
			if event.is_action_pressed('mouse_lmb'):
				print('clicked on me: ' + str(shape_idx))  # ALWAYS SAYS 0
```

**Comment by mrcdk** [comment]
That's the correct behabior. The shape index of each static body is 0 in both cases because t's not a global index but a local index.

**Comment by MrOneTwo** [comment]
Oh ... that seems useless then for my needs. I'm closing the issue then. Sorry.
