### ISSUE TITLE
automatic level of detail generation

### ISSUE THREAD

**Issue by cheece** [godotengine/godot#1457]
hello, 
automatic level of detail generation would be really useful, it reduces project size and working time with the only disadvantage of higher load time, 
in addition to automatic level of detail generation, automatic level of detail sincronization of morph targets would be really good,

**Comment by bojidar-bg** [comment]
Slight bump, just so that this issue doesn't disappear forever :smile:

**Comment by reduz** [comment]
There are some plans for this, but will be moved to 3.1. Ran out of time for 3.0

**Comment by aaronfranke** [comment]
I believe @fire has been working on this, pinging to let him know this issue exists.

**Comment by fire** [comment]
Here's what I have so far.

https://cdn.discordapp.com/attachments/691293474833563659/696517082392559616/Screen_Recording_2020-04-05_at_5.28.19_PM.mov

LOD on Blendshapes.

17748 indexed verts lod3 <- 27552 indexed verts lod0


We begin with a merged scene. (That's another proposal...)

![2020-04-06 15 09 09](https://user-images.githubusercontent.com/32321/78609909-9ace9700-7818-11ea-9c76-352127e6d3b8.jpg)

Here is the automatic LOD generation.

![2020-04-06 15 09 15](https://user-images.githubusercontent.com/32321/78609916-9efab480-7818-11ea-9b2a-ae2d1bb982cf.jpg)

Notice that errors on thin cards.

![2020-04-06 15 09 02](https://user-images.githubusercontent.com/32321/78609923-a457ff00-7818-11ea-9287-5e5a0ea65716.jpg)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/657, as feature proposals are now tracked on the Godot proposals repository. @fire Feel free to repost your comment there :slightly_smiling_face:
