### ISSUE TITLE
2d/3d viewport is broken after resizing editor small

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#14586]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04
GeForce GTX 670 384.90 nvidia proprietary driver
godot 3.0 56a44ca

**Issue description:**
2d/3d viewport is broken after resizing editor small

**Steps to reproduce:**
![viewport_broken](https://user-images.githubusercontent.com/8281454/33875313-385b11fa-df65-11e7-8422-08fb21bcfe52.gif)

**Comment by volzhs** [comment]
nothing

**Comment by guilhermefelipecgs** [comment]
I think this pr #14805 fix that too.
