### ISSUE TITLE
Mono always gives Core API hash mismatch even with glue from same commit

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#14584]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mageia 6 x86_64, current master branch (56a44ca03)
Mono 5.4.0.201, self compiled.

**Issue description:**
Since a few days, I can't get a proper hash check against the Core API. Even when making sure that I'm generate glue from a commit, then build with `mono_glue=yes` from the same commit, I get:
```
ERROR: _initialize_and_check_api_hashes: Mono: Core API hash mismatch!
   At: modules/mono/mono_gd/gd_mono.cpp:259.
```

*Edit:* Generated glue from 56a44ca03: [mono_glue.gen.cpp.txt](https://github.com/godotengine/godot/files/1550716/mono_glue.gen.cpp.txt)

**Steps to reproduce:**
```
scons p=x11 -j2 module_mono_enabled=yes mono_glue=no
./bin/godot.x11.tools.64.mono --generate-mono-glue modules/mono/glue/
scons p=x11 -j2 module_mono_enabled=yes mono_glue=yes
./bin/godot.x11.tools.64.mono
```

I've also noticed that the `mono_glue=yes` build triggers a rebuild of *everything*, which is super slow. Can we optimize this? It's annoying enough to have to build the engine twice for Mono each time, it shouldn't take twice the time too.

cc @neikeq

**Comment by akien-mga** [comment]
Last I tried it worked fine, so assuming it was just my system being weird.

**Comment by Hinsbart** [comment]
> so assuming it was just my system being weird.

I had this issue too, will check if it still happens.

**Comment by paulloz** [comment]
For the record (maybe someone like me will get here in the future).  
I just stumbled upon this issue on my laptop. Not sure it's related but removing the `-j` option and rebuilding seem to fix the problem :thinking:.

**Comment by Ertain** [comment]
I've been getting this message, and I have built it from sources. Btw, I'm using Linux Mint 18.3, Mono version 8.5.0.108 (the version coming from the Mono Project).

**Comment by NathanWarden** [comment]
You might want to try deleting the .local/share/godot/mono folder (or $HOME/AppData/Roaming/Godot/mono on Windows, not sure where it is on macOS) and then try running your project again and see if that fixes the problem.

**Comment by Ertain** [comment]
I deleted that, but it still persists.

**Comment by neikeq** [comment]
@Ertain Did you regenerate the glue sources before building?

**Comment by Ertain** [comment]
@neikeq Yeah, but the "mismatch" error is still there.

**Comment by zaksnet** [comment]
Same here, i am getting the API mismatch error (plus the game is crashing):
![image](https://user-images.githubusercontent.com/1850856/67380719-6c733d00-f593-11e9-9159-1005bb7c9157.png)

**Comment by neikeq** [comment]
@zaksnet The core API hash mismatch doesn't seem to be the cause of your application terminating. An exception is being thrown somewhere from your `Main._Ready()` method.
