### ISSUE TITLE
hide mesh surface in mesh instance

### ISSUE THREAD

**Issue by cheece** [godotengine/godot#1458]
hello,
it would be nice to have a  method in MeshInstance to hide Mesh surfaces  (e.g. hide_surface(int surface_index, bool hidden) ),
this  will be very useful specially for games where characters can have different clothing, hiding parts of the characters

**Comment by reduz** [comment]
it's much simpler to just have each piece of clothing as a separate
MeshInstance, all sharing skeleton.. since you can not only hide it but
load it on demand.

**Comment by akien-mga** [comment]
Closing as per the above comment, as this feature would actually be less useful than what is already possible as described by @reduz. (we could reopen it if there's enough interest in the feature proposed originally though, but I'm trying to bring down the issues backlog ;))
