### ISSUE TITLE
Rigidbody2D behaving broken in 3.0 beta 1 [regression]

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#14585]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win 7 x64, Godot 3.0 beta 1

**Issue description:**
Something seems to have broken the rigidbody 2d linear and/or angular velocity functions (I have a hunch that they went global even though the docs still say they're local)

2.1.4
https://i.imgur.com/5KFmdz8.gifv
![2017-12-12_09-18-24](https://user-images.githubusercontent.com/4525388/33874327-a796ee8c-df1e-11e7-8be9-21dae09c73e0.gif)

3.0 beta 1
https://i.imgur.com/86nHmfz.gifv
![2017-12-12_09-19-54](https://user-images.githubusercontent.com/4525388/33874342-b19f843e-df1e-11e7-915e-b82c8a1985a9.gif)

**Steps to reproduce:**
Export https://github.com/ivanskodje-godotengine/Vehicle-Controller-2D to 3.0, rename fixed to physics and rot to rotation, run and see mayhem ensue.

**Link to minimal example project:**
I could upload it if you want but see above.

**Comment by gururise** [comment]
From what I can tell, this is **not a bug** in Physics.  This has to do with the rotations changing between 2.1 -> 3.0.  The rotations returned in 3.x are opposite what they were in 2.x.

I've forked the Vehicle Controller and updated to make it work on 3.0:
https://github.com/gururise/Vehicle-Controller-2D
