### ISSUE TITLE
Unable to animate the shape of the CollisionPolygon2D

### ISSUE THREAD

**Issue by Waasha** [godotengine/godot#14599]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win 7, 64bit, Godot3 Beta

**Issue description:**

I'm not sure, if it's a bug, or missing feature, but according to this: https://github.com/godotengine/godot/issues/6286 it should be possible to animate the collision shapes in Godot V3.

**Steps to reproduce:**
Create a KinematicBody2D, add CollisionPolygon2D as a child, add AnimationPlayer. Create the polygon with the tools provided on the top bar. All the parameters on the CollisionPolygon2D panel in the inspector have keys next to them. Go inside the Polygon (Vector2), where the individual points of the polygon are listed - there are NO KEYS there...

Again - I'm not sure if it's a bug, but just to be sure, I'm submitting...

**Comment by vnen** [comment]
I'm not really sure if this is a bug. Maybe the AnimationPlayer can't change specific elements of an array (which is what holds the points of a polygon). OTOH animating polygons would be a nice thing to have.

**Comment by Waasha** [comment]
Yes, I totally agree :-)
But I'm a bit affraid it's too late.. After the feature freeze..

But imagine how awesome it would be - animating the exact shape of a weapon
swing - not just swords, but more complicated weapons, which are hard to do
with a static collision..Or characters, that change proportions
significantly during animations..
The usage options are limitless :-)


Dne 18. 12. 2017 2:42 dopoledne napsal uživatel "George Marques" <
notifications@github.com>:

I'm not really sure if this is a bug. Maybe the AnimationPlayer can't
change specific elements of an array (which is what holds the points of a
polygon). OTOH animating polygons would be a nice thing to have.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/14599#issuecomment-352305270>,
or mute the thread

**Comment by bojidar-bg** [comment]
What is the status on master (esp. after the animation player and inspector changes)?

**Comment by pouleyKetchoupp** [comment]
Just tested on master branch, it's possible to animate CollisionPolygon2D points in the new interface.

<img src="https://user-images.githubusercontent.com/1075032/62525150-30072f00-b837-11e9-8f5a-cbae8b81428b.gif" width="200" />

**Comment by akien-mga** [comment]
Thanks, closing as fixed in 3.1 then.
