### ISSUE TITLE
GD Shader Language -> material as new Datatype

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#146]
Hi all,
after testing the shader language quite a bit I have an idea for a feature that can be usefull.
Would it be possible to add Material as a separate Datatype that can be imported?

Usage would be something like this:
### uniform material new_mat;

This variable will then be exposed to the ui where a new material can be set. Now I can access a complete material not only textures or something like this. This way one can create a new material that consists of more materials and can be mixed! From the material datatype the diffuse and other attributes need to be accessible of course.

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch? Some work has been done recently on the shader language IIRC.

**Comment by akien-mga** [comment]
Ping :)

**Comment by akien-mga** [comment]
Last ping before departure :)

**Comment by bojidar-bg** [comment]
@akien-mga No way to expose material uniforms yet, AFAIK

**Comment by bojidar-bg** [comment]
I guess we aren't supposed to support recursive materials, right? :smile:

**Comment by bojidar-bg** [comment]
Closing as inactive, though it sounded cool.... feel free to comment or open a new one.
