### ISSUE TITLE
` Condition ' !animation_set.has(p_anim) ' is true` error at the time of AnimationPlayer creation

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#14602]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
56a44ca03e05a831e5c3c965a4675d53f82e7e6e Ubuntu 17.04, debug build

**Issue description:**
Today I noticed that for (I think) every AnimationPlayer in my project I have an error:
```
ERROR: set_current_animation: Condition ' !animation_set.has(p_anim) ' is true.
   At: scene/animation/animation_player.cpp:998.
```
at the time of instancing scene which holds given animation player. I assume this is recent problem.
I noticed this for the first time today.
Will do a bisection later.

**Steps to reproduce:**
1. Create a new scene with `Node` as root
2. Add `AnimationPlayer` to `Node` 
3. Save the scene
4. Run the scene with F6

**Link to minimal example project:**
[AnimationPlayerInstanceErrorTest.zip](https://github.com/godotengine/godot/files/1552787/AnimationPlayerInstanceErrorTest.zip)

**Comment by kubecz3k** [comment]
I seems that first commit that gave this error is
2d07fe29208b9ccef31ab654ca5405edac7a0de7

**Comment by willnationsdev** [comment]
Oh geez. What did I do now? >_< I thought I fixed the issue here...

**Comment by willnationsdev** [comment]
Looks like we just need to completely reset the file to the state it was in before I ever messed with it.

**Comment by willnationsdev** [comment]
I won't be able to get to a computer to fix it for several hours though. :-/

**Comment by kubecz3k** [comment]
Hmm but very probable the real error was introduced earlier.. commits before 2d07fe2 are having 
`Invalid Setter: AnimationPlayer::set_current_anim for property: anim_name`
 error on AnimationPlayer init

**Comment by kubecz3k** [comment]
@willnationsdev huh that was fast, I haven't seen your comment when I was writing my previous message. Have you introduced `Invalid Setter: AnimationPlayer::set_current_anim for property: anim_name` as well? :P

**Comment by willnationsdev** [comment]
Yeah, I was trying to fix it with the follow up commit. That's why I was suggesting we just wipe it all back completely

**Comment by kubecz3k** [comment]
Oh thanks for letting me know, you saved me from running more bisections :)

**Comment by willnationsdev** [comment]
Basically, we just have to grab a commit from before my `AnimationPlayer new props, members/methods` commit and then re-apply the contents of the changed files animation_player.h/.cpp and AnimationPlayer.xml.

**Comment by akien-mga** [comment]
I'm on it.

**Comment by pivot5** [comment]
Hi, this problem seems to have popped up for me today as well on 3.2.1, seems to have the same steps to reproduce.

**Comment by willnationsdev** [comment]
@pivot5 If so, it is likely caused by something else. My PRs haven't been merged in a long time since I've been relatively inactive as of late.
