### ISSUE TITLE
Collada import fail

### ISSUE THREAD

**Issue by jdavid82** [godotengine/godot#14606]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Windows 10 64 bit GTX 1060

**Issue description:**

Importing DAE file fails as shown in the attached log.

**Steps to reproduce:**
1. Compiled Godot 32 bit from source as of commit hash `fb12d700c9f4f47c775fa1bebeeb40ff683b2ef2`
2. Downloaded and installed the trial of [Akeytsu](https://www.nukeygara.com/)
3. Downloaded and installed [FBX 2013.3 converter for Win 64 bit](http://usa.autodesk.com/adsk/servlet/pc/item?siteID=123112&id=22694909)
4. Opened Akeytsu and loaded the sample project from `C:\Users\Public\Documents\akeytsu\Templates\akeyboy_sample.akt`
5. Clicked on Akeytsu -> Export FBX -> Export Scene
6. Opened FBX converter and converted FBX file to DAE
7. Dragged file to Godot editor

**Link to minimal example project:**

[dae bug demo.zip](https://github.com/godotengine/godot/files/1553203/dae.bug.demo.zip)
[errorlog.txt](https://github.com/godotengine/godot/files/1553204/errorlog.txt)

**Comment by eon-s** [comment]
Will be hard to support the DAE format exported by the converter if the converter does not support the way Godot read Collada files.

Can you try importing the collada or FBX file in Blender then exporting using the Better Collada exporter made to work with Godot?

**Comment by jdavid82** [comment]
OK I'll give that a go when I get home, I'll import the fbx file into blender, then export it from blender to DAE

**Comment by jdavid82** [comment]
Imported it into Blender then exported to DAE using Better Collada export and it worked, thanks.
