### ISSUE TITLE
TileMap occluders disappear in editor after switching to a different scene and back.

### ISSUE THREAD

**Issue by PJB3005** [godotengine/godot#14600]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOS High Sierra 1.13.1, 55962ce28fec5f06016ed3f66f52e6e84b817dbe (fresh compile), using Mono, GTX 660M, whatever GPU driver apple ships with MacOS by default.

**Issue description:**
If you have a `TileMap` with occluders inside the scene editor, then swap to another scene tab and back, the occluders visually disappear until you re-open the scene entirely. 

**Steps to reproduce:**
1. Make a `TileMap`, give it a tileset with some occluders.
2. Add a shadow casting 2D light to the scene.
3. The Light 2D should be properly casting a shadow onto the tilemap's occluders.
4. Open a different scene, then switch back to the tilemap scene's tab.
5. The occluders stopped rendering!

**Comment by blurymind** [comment]
cc @MarianoGnu

**Comment by MarianoGnu** [comment]
Does this happen with occluder nodes too or just tilemap?

**Comment by PJB3005** [comment]
Sorry for the late response, but no, it's exclusive to tilemaps. Regular occluder nodes are fine.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by samdze** [comment]
This also happens during play time, removing a node/scene containing a TileMap from the tree and then re-adding it causes the same issue. 3.0.2 official.

**Comment by mosujiba** [comment]
I am experiencing this issue in v3.0.2 as well.

**Comment by MarianoGnu** [comment]
have you tryed with master? there have been a fix recently for navigations wich i belive could solve this too

**Comment by mosujiba** [comment]
I just tried with master, and it seems that the bug is gone. 
(However, the current master breaks my autotiles.)

**Comment by KoBeWi** [comment]
> I just tried with master, and it seems that the bug is gone.

I tested that too and indeed seems to be working in 3.1.
