### ISSUE TITLE
Orthogonal View glitches

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#14619]
**MBP (15 inch- 2016) Radeon Pro 455 2048 MB - MacOs Sierra 10.12.6 **

**Issue 1.**
i have Orthogonal View glitches when switching beetween perspective and ortho view.

**Steps to reproduce:**
https://youtu.be/_0bj79lsEAM

**Issue 2.**
disappearance bug when rotate zoomed object in orthogonal view.

**Steps to reproduce:**
https://youtu.be/yA2nkLl8uXE

**Comment by Zylann** [comment]
It looks like you are seeing a gizmo fullscreen at some point (the greem one), as they are also not visible in ortho. Maybe their shader need to be adapted for ortho. No clue about the purple stuff though

**Comment by icnikerazah** [comment]
yes, this is only happening while the Spatial node is selected.
<img width="911" alt="ekran resmi 2017-12-13 18 01 48" src="https://user-images.githubusercontent.com/33985414/33945368-de95cbe4-e02f-11e7-81ea-dfcdd6cb03bf.png">

**Comment by LinuxUserGD** [comment]
2nd could be clipping.

**Comment by reduz** [comment]
fix for this seems to have been merged, so closing
