### ISSUE TITLE
'Floor' doesn't make sense when editing gridmap by other axis.

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#14611]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64 - 55962ce

**Issue description:**

IMO, using the word 'floor' implies that gridmap can only be edited in xz plane, while in reality it is configurable.

![image](https://user-images.githubusercontent.com/26753932/33921541-14603f68-dff7-11e7-9cff-fbd47773b7b6.png)

![image](https://user-images.githubusercontent.com/26753932/33921513-cfeb43a0-dff6-11e7-81a5-3ce0d750dfae.png)

**Comment by vitrig** [comment]
Some alternative names?
- Section
- Tier
- **Plane** *(If not Floor, I'd vote for that)*
- Surface
- Level
- Fragment

**Comment by adtofaust** [comment]
I think either **Plane** or **Level** is fine

**Comment by hubbyist** [comment]
"Plane" is math related and hierarchy agnostic so will be better IMO.

**Comment by reduz** [comment]
We can always rename it to "Wall" whem changing axis :D

**Comment by KidRigger** [comment]
Found the string location in the grid_map_editor_plugin.cpp
Should I change it to Plane?

**Comment by KidRigger** [comment]
Will take a bit more time (Trying to get familiar to the codebase right now.)
But I'll try my best.
