### ISSUE TITLE
Why scale the scene editor by dragging two fingers feature is miss in 3.0

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#14610]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0
Mac OS 

**Issue description:**

in 2.1, drag tow fingers on the trackpad to scale the scene is a very nice feature.
 in 3.0, scale by the button is not so easy to use as 2.1.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by poke1024** [comment]
This has changed indeed. 
In Godot 2, dragging was basically a mouse wheel event which defaulted to zooming.
In Godot 3, dragging does panning while pinch and zoom does zooming. This is the macOS default behavior (see for example the Preview app).

**Comment by alexzheng** [comment]
Yes, pinch and zoom works in 3.0.
I think this issue can be closed.
