### ISSUE TITLE
WebGL 1 support

### ISSUE THREAD

**Issue by uldall** [godotengine/godot#14616]
Hi,

I created this issue to start a discussion around support of WebGL 1 in Godot 3.x.

Our interest in WebGL 1 stems from the following statistics (Taken from caniuse.com):
- WebGL 1 browser support: 92.93%
- WebGL 2 browser support: 59.74% (Most notably Safari and Edge support missing)

My understanding is that WebGL 1 is somewhat based on OpenGL ES 2.0: "This specification may diverge from OpenGL ES 2.0 in order to ensure interoperability or security, often defining areas that OpenGL ES 2.0 leaves implementation-defined." from https://www.khronos.org/registry/webgl/specs/1.0/

Since @karroffel will be working on a OpenGL ES 2.0 renderer for Godot 3.1, my question is whether this will also entail WebGL 1 support?

Further, what limitations will the OpenGL ES 2.0 renderer have compared to the GLES3 renderer?

**Comment by reduz** [comment]
It is as you say, currently @karroffel is backporting Godot 3.0 to GLES2,
which should make it work properly on WebGL1.
The GLES2 renderer will be more similar to how Unity works in mobile, and
will likely not support some of the most advanced post processings or real
time -GI (though I'm adding lightmap support to compensate).. yet it should
be full PBR.

**Comment by eska014** [comment]
There's more to it than implementing an OpenGL ES 2.0 rasterizer, [WebGL 1.0 has several limitations](https://www.khronos.org/registry/webgl/specs/1.0.2/#6) that the implementation needs to deal with if support is desired

**Comment by uldall** [comment]
@karroffel Do you have any plans for taking these limitations into consideration when implementing the GLES2 renderer? If not, we would be very interested in discussing work-for-hire in this regard.

**Comment by reduz** [comment]
There should be no problem in supporting WebGL1, the main limitation is not
using arrays from main memory and this should definitely not happen.

**Comment by karroffel** [comment]
@uldall I will make it work on my main development machine first, then make it work on other platforms. Proper HTML export is something that's planned to be done, but not up front but patched in after it's all working already on other platforms.

**Comment by eska014** [comment]
WebGL 1.0 driver is available for testing with #17343

**Comment by uldall** [comment]
Awesome! :)

**Comment by bojidar-bg** [comment]
That PR was merged, shouldn't this issue be closed?

**Comment by akien-mga** [comment]
Some testing might be in order to ensure that basic functionality work (at least similar to current desktop OpenGL 2.1).

**Comment by Chaosus** [comment]
> That PR was merged, shouldn't this issue be closed?

I think now yes, the specific issues can be created separately + the topic seems dead, what do you think @akien-mga ?

**Comment by akien-mga** [comment]
Yes, we can consider it fixed.
