### ISSUE TITLE
Cannot set library for GDNativeLibrary

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#14618]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 compliled with  b110813  on Windows 7

**Issue description:**

Here is no way to set the dynamic library for any platform.
The door to GDNative is totally closed :(

**Steps to reproduce:**
* Create a GDNativeLibrary resource in the inspector
* The inspector lost the platform section
![image](https://user-images.githubusercontent.com/6964556/33933166-e031f734-e02f-11e7-9aaa-9125af7f0f31.png)

**Link to minimal example project:**

**Comment by karroffel** [comment]
Open the file in an external text editor, it needs to look like [this](https://github.com/GodotNativeTools/GDNative-demos/blob/master/c/SimpleDemo/bin/simple.gdnlib) 

There's no UI yet, there might be in future, so if anyone wants to create a user interface for it, feel free, I suck at making UIs 😄

**Comment by Geequlim** [comment]
Is the class [GDNativeLibraryEditor](https://github.com/godotengine/godot/blob/master/modules/gdnative/gd_native_library_editor.h)  is designed for the job?

**Comment by Geequlim** [comment]
It seems like this window UI.

![image](https://user-images.githubusercontent.com/6964556/33934096-cd914f50-e032-11e7-8aca-21b9eae19f7d.png)

And what is this designed for and how to use it?

**Comment by karroffel** [comment]
That UI is for showing active (or soon to be active) GDNative singleton libraries (which are a bit like modules). It currently lacks the feature to disable them in the UI, but it's not intended to be for the editing of GDNativeLibrary files.

**Comment by akien-mga** [comment]
Maybe it can be renamed to `GDNativeSingletonsEditor` so that the `GDNativeLibraryEditor` name becomes available for the edition of `GDNativeLibrary` objects?

**Comment by Geequlim** [comment]
@karroffel I'm making a GUI plugin to edit the GDNativeLibrary.

What is the `dependencies` is designed to do?

**Comment by karroffel** [comment]
@Geequlim the dependencies field is for when a library depends on third party libraries.

As an example, there could be a Steamworks GDNative library. It creates the classes that NativeScript can use but internally it just calls the Steamworks library.

When you export a game Godot needs to copy the libraries. So the dependencies fields are for specifying which libraries to export as well when exporting this specific GDNativeLibrary
