### ISSUE TITLE
High level multiplayer for WebAssembly platform

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#14627]
Will Godot 3.1 support WebAssembly high networked multiplayer?

**Comment by eska014** [comment]
The choices here are:

 - WebSocket, which is relatively simple to use in the browser
 - WebRTC data channels, which are more complex to implement and use, but can be faster
 - HumbleNet, which uses both preceding technologies, has some support from Mozilla and supposedly works automatically both on native and Emscripten

WebSocket and WebRTC would need to be implemented separately for native if multiplayer connections across native and browser are desired.

**Comment by LinuxUserGD** [comment]
Websockify (https://github.com/novnc/websockify) could be used as an TCP bridge for allowing browsers to connect to native applications (1 direction)

**Comment by Faless** [comment]
@LinuxUserGD @eska014 
See https://github.com/LudiDorici/godot-websocket for an implementation of High level multiplayer over websocket compatible with both desktop and and webassembly platform.
