### ISSUE TITLE
Setting orange color on Spatial Material using Color(RGB) shows up as yellow

### ISSUE THREAD

**Issue by DonSkeleton** [godotengine/godot#14624]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 8 x64
Godot v3.0.beta.build1
Nvidia GTX 970, driver version 385.69

**Issue description:**

I wanted to set the color of a SpatialMaterial to orange using 
`material0.albedo_color = Color(255, 128, 0)`
but instead of seeing the color orange on my MeshInstance, the object is yellow.

In the picture below,
the color of the left box is set using the inspector to "255,128,0"
the color of the middle box is set using the line `material0.albedo_color = Color(255, 128, 0)`
the color of the right box is set using the line `material0.albedo_color = Color(1.0, 0.5, 0)`

![wrongcolor](https://user-images.githubusercontent.com/21103642/33939296-f414537a-e00a-11e7-86b6-1f37995f9880.JPG)

Using Color("#ff8800") also works and the box shows up as orange.
So the problem is only with "Color(255, 128, 0)".

**Steps to reproduce:**
1. Have a MeshIstance in your 3D Scene
2. Give it a SpatialMaterial
3. Add a Script to the MeshInstance
4. Then add the following to the "_ready()" function:
```
var material0 = self.get_surface_material(0)
material0.albedo_color = Color(255, 128, 0)
self.set_surface_material(0, material0)	
```
Alternatively, open the attached example project, the node "Block2" has the script mentioned above.
When running the scene, you can see the center object will have a yellow instead of orange color.

**Link to minimal example project:**

[Color Bug.zip](https://github.com/godotengine/godot/files/1555624/Color.Bug.zip)

**Comment by groud** [comment]
I don't think there's a constructor for color with values between 0 and 255.
So the second in interpretated as `Color(255.0, 128.0, 0.0)`, but as the values are clamped between 0 and 1, it ends up with the equivalent of `Color(1.0, 1.0, 0.0)`. Which explains the yellow color.

**Comment by akien-mga** [comment]
> I don't think there's a constructor for color with values between 0 and 255.

There is, `Color8(255, 128, 0)`.

**Comment by groud** [comment]
@DonSkeleton tell us if this solves your problem sothat we can close the issue :)

**Comment by DonSkeleton** [comment]
So using Color8 works, thanks @akien-mga 
I guess my expectation was that if I can use 0 to 1 and hex values for Color, that 0 to 255 will also work.

Maybe it could be made possible to allow Color to also accept values from 0 to 255?
Should I open a new Issue for feature request for that?

Thanks

**Comment by groud** [comment]
It wont be possible to distinguish the two constructors. So I think Color8 is enough.

**Comment by akien-mga** [comment]
>  I guess my expectation was that if I can use 0 to 1 and hex values for Color, that 0 to 255 will also work.

That's not possible. What color would `Color(1.0, 0, 0)` be? Full red or pitch black with a slight hint of red?

**Comment by DonSkeleton** [comment]
So distinguishing between 
`Color(float r, float g, float b)`
and
`Color(int r, int g, int b)`
would not be possible?

@akien-mga In your example you are right that would make no sense, thought it would be possible to use float for one constructor (0.0 to 1.0) and int (0 to 255) for the other.

But atleast I know now that I also need to check @GDScript in the API Reference and not only use the search. Didn't even notice the @GDScript area and thought the whole API Reference was just for GDScript.

**Comment by groud** [comment]
I think having different behaviours for int and floats would be very confusing.
