### ISSUE TITLE
Unable to use OS.set_current_screen while in true fullscreen

### ISSUE THREAD

**Issue by TheSHEEEP** [godotengine/godot#14620]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 64bit & NVIDIA GeForce GTX 970
Linux 64bit & NVIDIA GeForce GTX 1060
Godot 2.1.4

**Issue description:**
When the application is in true fullscreen mode (via `OS.set_window_fullscreen`), using `OS.set_current_screen` does not do anything.
You'd expect it would switch to the passed monitor.

As a workaround, you have to switch the window to another mode (like windowed or borderless fullscreen), before calling `OS.set_current_screen`. Then, you can apply true fullscreen again.
It isn't too much work, but still shouldn't be required.

**Steps to reproduce:**
Try above description in the window management demo.

**Comment by Web-eWorks** [comment]
Can you confirm this still occurs on Godot 3.0.3 / master?

**Comment by johnzantey** [comment]
FYI: Used your suggested workaround for Linux on GD 3.2.1 - TY

**Comment by akien-mga** [comment]
At least on Linux `OS.set_current_screen` seems to have dedicated code to handle the fullscreen mode:
https://github.com/godotengine/godot/blob/2d57df60f7567990b63099978289a15e8df01c94/platform/x11/os_x11.cpp#L1184-L1194

But it could be that it doesn't work. (CC @bruvzg @pouleyKetchoupp)

**Comment by acgc99** [comment]
Same issue in Godot Engine v3.4.stable.official.206ba70f4

If fullscreen is enabled from Project>Settings:

`	print(OS.get_screen_count() )
	if OS.get_screen_count() > 1:
		print(OS.get_current_screen())
		OS.set_current_screen(1)
		print(OS.get_current_screen())
`

Prints
`2
0
0
`
And the game screen is 0.

But  if I disable fullscreen and do:
`	
print(OS.get_screen_count() )
if OS.get_screen_count() > 1:
	print(OS.get_current_screen())
	OS.set_current_screen(1)
	print(OS.get_current_screen())
	OS.window_fullscreen = !OS.window_fullscreen
`
I get:
`
2
0
1
`
And it works  as expected.

**Comment by akien-mga** [comment]
Fixed by #63192.
