### ISSUE TITLE
TileMap tiles can't be placed without dragging the mouse

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#14625]
**Operating system or device, Godot version**
Linux Mint 18.3 Sylvia x64, Godot 3.0 56a44ca

**Issue description:**
Performing a stationary left-click in a TileMap does not place a tile. The mouse has to be dragged at least 1 px while holding down LMB for any tiles to be placed.

![peek 2017-12-14 00-43](https://user-images.githubusercontent.com/27100585/33941805-f7e633f8-e067-11e7-97f9-c02af4dd926c.gif)

Stationary right-clicks work just fine for removing tiles.

**Comment by gururise** [comment]
I can confirm this behavior/bug.
