### ISSUE TITLE
glTF import bug

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#14636]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux AMD64, Godot v3.0.beta.build1

**Issue description:**
Imported a gltf model from blender. Expect to just work™
Actual result:

First time, importing on dir change, crashed with a stack trace. Was not running in debug so I can't really provide it here, sorry.
Second time, imported successfully (was there on load but without the .import file due to me deleting it) but animations scaled instead of moving as they should

**Steps to reproduce:**
Heirarchy just needs:
ROOT: Spatial
.gtlf dragged in directly as a child

Note, .glb version (gltf binary) also exhibits the same behaviour

**Link to minimal example project:**

Not the project, but the source .blend and the exported gltf. This works in isolation.
[navdemo.zip](https://github.com/godotengine/godot/files/1642884/navdemo.zip)
*Updated to include required .bin file*

Animation of correct behaviour (in blender):
![out 1](https://user-images.githubusercontent.com/3120639/33960138-0b21241e-e04a-11e7-94f8-362734178101.gif)

Sidenote. Apologies for the really low quality PR. This is really inconsistent on my computer and it caused so many issues I just gave up on trying to record it.

**Comment by akien-mga** [comment]
You did not include `navdemo.bin` in your zip so the glTF can't be used...

**Comment by capnm** [comment]
[14636_animdemo.zip](https://github.com/godotengine/godot/files/1640480/14636_animdemo.zip)

![peek 2018-01-17 21-17](https://user-images.githubusercontent.com/4047289/35064961-003f20ee-fbcc-11e7-82c9-4be23d97a496.gif)
![peek 2018-01-17 21-29](https://user-images.githubusercontent.com/4047289/35065537-c9ee4c8e-fbcd-11e7-9fa9-7cccecd60b48.gif)

**Comment by Silvea12** [comment]
@akien-mga Blender never exported a .bin file. Where would I find this?

**Comment by Silvea12** [comment]
@akien-mga Apologies, reuploaded with the .bin below. I will also update the initial post.

[navdemo.zip](https://github.com/godotengine/godot/files/1642884/navdemo.zip)
