### ISSUE TITLE
Object Translation not referring as expected

### ISSUE THREAD

**Issue by AkatDeen** [godotengine/godot#14631]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64 bit, Godot 3 B1

**Issue description:**
These codes below wont work:
var p = get_parent().get_node("Player").translation #--------> this works!
translate(Vector3(0,0,p.z-2)) #--------> this works!
p.z -= 2 #--------> this WONT WORK!

have to do this below:
var p = get_parent().get_node("Player")
#we skip this line coz it works anyway
p.translate.z -= 2

**Comment by vnen** [comment]
That's expected, once you do `var p = $Node.translation` you're getting a copy of the vector, not a reference to it. The second part works because nodes comes as a reference.

**Comment by AkatDeen** [comment]
i see.. got it.. pretty confusing there at once.. Thanks vnen.. so we can pull this one out?
