### ISSUE TITLE
Slider notches aren't aligned with the pointer location.

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#14637]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04, Godot a8ae46e

**Issue description:**

The tick notches on HSlider and VSlider are not aligned with the actual hotspots of the slider's pointer:
![notches](https://user-images.githubusercontent.com/20242421/33960569-7346570c-e04b-11e7-9f21-f7f1d8526933.gif)

This seems to be caused by the notches not correctly gathering the pointer's offset from the edges of the slider, instead starting and ending closer to the very ends of the bar.

**Steps to reproduce:**
Create an HSlider or a VSlider, enable `Ticks On Borders` and set the `Tick Count` to any number, for example 5.
Then set the `Min Value` to 0 and the `Max Value` to your number - 1 (eg. 4).
Run the scene and move the pointer; the arrow on it will not point onto any notches.

**Comment by djrm** [comment]
to me it looks like it is the other way around, why the grabber is not able to get to the limits of the slider (it has some sort of margin), the center of the grabber should be able to get to slider position 0, and its max size.

**Comment by leoddd** [comment]
That may be as well, I figured that it was designed this way on purpose so it doesn't leave its "ridge".
I don't mind much which way it gets fixed, as long as the pointer and the notches align. I would definitely move the notches in a little bit though, as the ones farthest on the outside don't look quite right hovering around the rounded ends, they should sit right where the ridge turns into a straight line.

**Comment by henriquelalves** [comment]
I just checked the slider code, the 'grabber' drawing limit is based on the slider width minus the grabber image width (so the grabber image won't have an offset on either min or max values), while the ticks drawing limits are based on the slider width minus the tick image width - which means its drawing limits is different than the grabber, creating this tick offset.

I'm at work right now but this looks easy to fix, as soon as I get home I'll test making the tick drawing limits the same as the grabber and adding a grabber half-width offset.

**Comment by leoddd** [comment]
Fixed by #14666

**Comment by Merlin1846** [comment]
This glitch is still here.

**Comment by Reapetitive** [comment]
This is still present in 3.5.2
