### ISSUE TITLE
Sony Dualshock 4 Controller's right joystick button doesn't work

### ISSUE THREAD

**Issue by G392** [godotengine/godot#14639]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Manjaro, Godot 3.0 Beta 1

**Issue description:**
I tested my USB connected PS4 controller in the misc/Joypads demo 
and noticed that everything (Buttons, axes) worked except the right stick's button.

**Steps to reproduce:**
Run the misc/Joypads demo with a PS4 controller connected to the computer with an usb cable
and press the right joystick's button.

**Fix:**
(Sorry to share this fix that way, I don't know how to use git)
You need to replace: (In main/input_default.cpp)
`"030000004c050000c405000011810000,Sony Computer Entertainment Wireless Controller,leftx:a0,lefty:a1,dpdown:h0.4,rightstick:h0.1,rightshoulder:b5,rightx:a3,start:b9,righty:a4,dpleft:h0.8,lefttrigger:a2,x:b3,dpup:h0.1,back:b8,leftstick:b11,leftshoulder:b4,y:b2,a:b0,dpright:h0.2,righttrigger:a5,b:b1,",`
with:
`"030000004c050000c405000011810000,Sony Computer Entertainment Wireless Controller,leftx:a0,lefty:a1,dpdown:h0.4,rightstick:b12,rightshoulder:b5,rightx:a3,start:b9,righty:a4,dpleft:h0.8,lefttrigger:a2,x:b3,dpup:h0.1,back:b8,leftstick:b11,leftshoulder:b4,y:b2,a:b0,dpright:h0.2,righttrigger:a5,b:b1,",`

**Comment by vnen** [comment]
Looks like this is solved [upstream](https://github.com/gabomdq/SDL_GameControllerDB) but #14512 didn't update the values but just added the new entries.

**Comment by akien-mga** [comment]
CC @Hinsbart @Silvea12.

**Comment by Silvea12** [comment]
I assumed we wanted to keep the old mappings as priority as it contained a few custom ones. I can submit a new pull request that updates all of these with the new mappings overwriting the old ones, if this is required.
