### ISSUE TITLE
Tilemap(Sprite texture region) lost focus in image imported

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#14632]
Imported:
![image](https://user-images.githubusercontent.com/13235119/33957867-c10b3af4-e03a-11e7-9c9e-13277b1f6eee.png)

Original:
![image](https://user-images.githubusercontent.com/13235119/33957891-d8eae98a-e03a-11e7-8d37-ee01ffad5056.png)

**Comment by akien-mga** [comment]
Please follow the given issue template when filing issues. You report is lacking crucial information, like the Godot version..

At any rate, disable texture filtering and this will work as expected.

**Comment by git2013vb** [comment]
I update my comments in main page.

**Comment by leoddd** [comment]
Click on your TileSet image in the FileSystem dock and then select the Import dock, disable filter there and Re-import.

This github isn't for support though, it's for actual bug tracking, you'd be better off asking for instructions on how to do certain things on the QA board or the IRC/Discord chats.

**Comment by git2013vb** [comment]
Thank you for your help. :) I try to do what you suggest.
