### ISSUE TITLE
funcref variables not handled by duplicate()

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#14647]
I have an object which has a var which holds a valid funcref.
When I clone this object, this var is null.

It has not copied the funcref, meaning I have to manually copy the funcref.
I would expect that the value would be copied.

**Comment by supagu** [comment]
actually, it seems my other variables are not being duplicated either.
I had a dictionary assigned to a variable, which is not being duplicated, so again requires me to manually copy the settings across.

Is this the expected behaviour?

**Comment by Zylann** [comment]
Note about dictionaries and arrays: https://godotengine.org/qa/19396/how-do-i-duplicate-a-dictionary-in-godot-3-0-alpha-2

**Comment by supagu** [comment]
Yea, the more i think about it the more it seems reasonable the way it is.

I just overrode the duplicate function and made any changes i wanted too.

This seems the safest route.
