### ISSUE TITLE
Cannot attach a NativeScript to nodes with script creating dialog

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#14643]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 compliled with b110813 on Arch Linux x86_64

**Issue description:**

Cannot attach a NativeScript resource  to nodes with script creating dialog. The script creator complains `Invalid class name`. But it is not allowed to modify the class name field the input is disabled.

**Steps to reproduce:**

1. Right click on any node without script attached
2. Select NativeScript for the language
3. Select a NativeScript resource file `.gdns`

![image](https://user-images.githubusercontent.com/6964556/33971394-2c181d26-e0b3-11e7-942c-bda67b5e9996.png)

**Comment by opkpEh** [comment]
dude any help with this, did you get it solved?
