### ISSUE TITLE
Sprite has pixel distortion when moved under certain circumstances

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#14644]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Mint 18.3 Sylvia x64, Godot 3.0 1c0007b, NVIDIA GTX 980Ti, NVIDIA binary driver 384.90

**Issue description:**
![sfghhh](https://user-images.githubusercontent.com/27100585/33971453-902c1286-e0cc-11e7-8685-b9105c69eea7.gif)
(The jerkiness was caused by my screen-recording software and doesn't actually happen when running the project.)

Use Pixel Snap is enabled, and the Sprite node's scale has been left at (1, 1). I scaled the window's "test" dimensions to 4x its regular dimensions for visibility, but the stretch mode has been set to viewport so there shouldn't be any weird sub-pixel shenanigans.

The Sprite node starts off stationary and is being accelerated upwards at a rate of 0.01 px/frame to a maximum velocity of 1 px/frame. When it hits this maximum velocity, the sprite distortion occurs. The problem only seems to occur when the maximum velocity is exactly 1 px/sec. The acceleration also has to be at a value that causes the current velocity to reach the maximum velocity exactly, so in this case an acceleration of 0.01 or 0.02 would cause the bug, but 0.03 would not. This bug also occurs when moving downwards.

Probably related to #9422.

**Link to minimal example project:**
[Sprite Glitch Test.zip](https://github.com/godotengine/godot/files/1557657/Sprite.Glitch.Test.zip)

(**NOTE:** When I first reported this issue in https://github.com/godotengine/godot/issues/9422#issuecomment-351573323, I had the Sprite as a child of a KinematicBody2D and moved the body using `move_and_slide()`, but I found that this also happens when moving the Sprite node directly, so I updated the test project to better reflect the problem.)

**Comment by VinnieH01** [comment]
Might be related to [#13273](https://github.com/godotengine/godot/issues/13273)
