### ISSUE TITLE
RigidBody apply_impulse not working with linear damping = 1 with Bullet physics

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#14650]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux (also observed on Windows 10), Godot 3.0 beta-1

**Issue description:**

When using a RigidBody in character mode with linear damping = 1 then `apply_impulse` does not move the body at all.

When switching the physics server back to GodotPhysics then it works.

When using Bullet as a physics engine the result should be the same as with the old physics engine.

**Steps to reproduce:**
- Create a RigidBody, set it to character mode. Make sure it doesn't fall down into the void of meaninglessness where you can't observe the bug.

- Set linear damping to 1.

- in _physics_process use `apply_impulse`.

- see that it's not moving the RigidBody

- switch to GodotPhysics

- observe that it does move the RigidBody

**Link to minimal example project:**

[ApplyForceWithDampingBullet.zip](https://github.com/godotengine/godot/files/1558657/ApplyForceWithDampingBullet.zip)

**Comment by AndreaCatania** [comment]
I'll check it soon

**Comment by AndreaCatania** [comment]
I've tested it and it seems fine. The damping in bullet works differently from Godot physics so this statment is not always true:

> When using Bullet as a physics engine the result should be the same as with the old physics engine.

In this case the parameters should be changed according physics engines

**Comment by akien-mga** [comment]
So it's not a bug I guess? If so the documentation should be updated to mention this difference between both engines.

**Comment by AndreaCatania** [comment]
@akien-mga yes i think so

**Comment by akien-mga** [comment]
Superseded by godotengine/godot-docs#2161.
