### ISSUE TITLE
"Attach Node Script" dialog box spawns slightly off-center

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#14659]
**Operating system or device, Godot version**
Linux Mint 18.3 Sylvia x64, Godot 3.0 f3ad142

**Issue description:**
The dialog box always seems to appear too far down and to the right:
![image](https://user-images.githubusercontent.com/27100585/33996458-5be620fc-e135-11e7-8204-205a52685afb.png)

**Comment by vnen** [comment]
This happens for me only the first time the dialog is open. The next time I open the dialog is in the center.

**Comment by homer666** [comment]
@vnen Good observation.

**Comment by KidRigger** [comment]
I called popup_centered() twice in a row instead of just once and it started to align to center. I'm trying to trace the reason why the second call centers the dialog.

**Comment by akien-mga** [comment]
See #16069, which is a later duplicate but has some more debugging details, so closing this one in favour of #16069.

**Comment by homer666** [comment]
This behaviour still occurs as of dd2cd06.

![image](https://user-images.githubusercontent.com/27100585/57003635-7ed77400-6c0b-11e9-9e6b-b7417caada1c.png)

However, it only happens when adding a script from the Scene dock; creating a script from within the Script editor (File > New Script...) has the dialog centered correctly the first time. I narrowed it down to this line:
https://github.com/godotengine/godot/blob/dd2cd06165670bb0d78bf4aa397935be15716e76/editor/plugins/script_editor_plugin.cpp#L971

The Scene dock's dialog is popped up without any size information:
https://github.com/godotengine/godot/blob/dd2cd06165670bb0d78bf4aa397935be15716e76/editor/scene_tree_dock.cpp#L394

Adding it fixes the problem. I have no idea why, though. Is it worth making a PR for this, or is a proper fix desired?
