### ISSUE TITLE
Godot editor doesn't start if no audio device present

### ISSUE THREAD

**Issue by ignaloidas** [godotengine/godot#14651]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0 alpha 1 official build

**Issue description:**
Godot editor console stuck getting errors. It should have opened a project selection window.
**Steps to reproduce:**
Disable all audio devices. Start Godot editor.

**Errors thrown**
At: drivers\rtaudio\audio_driver_rtaudio.cpp:145
ERROR: AudioDriverRtAudio::init: Unable to open audio, retrying with fewer channels..

**Comment by akien-mga** [comment]
> Godot 3.0 alpha 1

Can you try with 3.0 beta 1?

**Comment by ignaloidas** [comment]
Works with 3.0 beta 1. Well I forgot to update.
