### ISSUE TITLE
Just adding an AnimationPlayer node triggers the error ERR_FAIL_COND(!animation_set.has(p_anim)); 

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#14664]
The following error is triggered for every AnimationPlayer node that's added to the scene regardless the node params. 

https://github.com/godotengine/godot/blob/e1b374d5b624c1e0a09d8c6e5c11fc53f8d90423/scene/animation/animation_player.cpp#L995

It's happening at least since 55962ce28fec5f06016ed3f66f52e6e84b817dbe and it didn't happen in beta1

**Comment by akien-mga** [comment]
Duplicate of #14602, should be fixed since yesterday, can you confirm?

**Comment by noidexe** [comment]
Sorry I searched for similar issues but missed the duplicate. It's fixed on HEAD
