### ISSUE TITLE
Can't build with LLVM

### ISSUE THREAD

**Issue by MrJustreborn** [godotengine/godot#14668]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
ManjaroLinux
Godot HEAD ( 93a63a5e1adf1886ea37a8357442de7e2c80cd20 )

I'm unable to build with llvm, gcc works

> /D/t/g/godot (master=) scons -j2 platform=x11 use_llvm=yes
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 38%] Compiling ==> thirdparty/tinyexr/tinyexr.cc
[ 38%] Compiling ==> modules/tinyexr/register_types.cpp
In file included from thirdparty/tinyexr/tinyexr.cc:2:
thirdparty/tinyexr/tinyexr.h:442:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
scons: *** [thirdparty/tinyexr/tinyexr.x11.tools.64.llvm.o] Error 1
scons: building terminated because of errors.

**Comment by bruvzg** [comment]
try building with `scons -j2 platform=x11 use_llvm=yes openmp=no`

**Comment by MrJustreborn** [comment]
> try building with scons -j2 platform=x11 use_llvm=yes openmp=no

That worked

**Comment by bruvzg** [comment]
@MrJustreborn after f3ad14224e27f2a25196575e3c43ebc792c90894 OpenMP is enabled by default, either install LLVM OpenMP library (libomp or libiomp) or build with OpenMP disabled `openmp=no`.

**Comment by MrJustreborn** [comment]
@bruvzg Thanks, I installed OpenMP. It should be added to the docs before 3.0 stable.

**Comment by bruvzg** [comment]
Also this file https://github.com/godotengine/godot/blob/master/platform/x11/detect.py#L271 may required additional linking flag for clang. If you'll get linking errors try changing it like this:

```python
if not env['use_llvm']:
            env.Append(LIBS=['gomp'])
else:
            env.Append(LINKFLAGS=['-fopenmp'])
```

**Comment by MrJustreborn** [comment]
It compiled with this modifications

**Comment by hpvb** [comment]
The link flags have changed for all platforms to use -fopenmp. We could consider adding a runtime check to see if the openmp libs are installed but we currently don't do this for our other dependencies either.

Closing this.

**Comment by akien-mga** [comment]
>  We could consider adding a detect.py check to see if the openmp libs are installed but we currently don't do this for all our other dependencies either.

We do it for some actually, but only using pkg-config. There doesn't seem to be any pkg-config stuff for libgomp or lib[i]omp, so we'd have to implement a more involved check manually.

**Comment by hpvb** [comment]
> We do it for some actually, but only using pkg-config. There doesn't seem to be any pkg-config stuff for libgomp or lib[i]omp, so we'd have to implement a more involved check manually.

Oh absolutely! I wasn't trying to suggest we shouldn't try. It just seemed to me that keeping this issue open for a more generic problem wasn't particularly useful.

Maybe a tracker bug to properly check *all* our dependencies would be in order?

**Comment by akien-mga** [comment]
> Maybe a tracker bug to properly check all our dependencies would be in order?

Yeah definitely.
