### ISSUE TITLE
Creating some range controls shows the wrong theme

### ISSUE THREAD

**Issue by wetiontop** [godotengine/godot#14661]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOS 10.13.1
Godot 3.0.beta

**Issue description:**

Creating some range controls shows the wrong theme, maybe they should not be created in the node list.

**Steps to reproduce:**
![qq20171215-003955](https://user-images.githubusercontent.com/4017034/34004065-e1d8f24c-e131-11e7-955f-69773a6f5e70.png)
![qq20171215-003944](https://user-images.githubusercontent.com/4017034/34004070-e32a7c60-e131-11e7-9b22-2a7132c3dbf5.png)

**Comment by akien-mga** [comment]
CC @djrm

**Comment by djrm** [comment]
i dont even know why you can have those nodes, logically the dont have theme elements, maybe the should be virtual classes.

**Comment by wetiontop** [comment]
@djrm They can be created.
![c30708b7-5999-4974-ad31-cd684cce016d](https://user-images.githubusercontent.com/4017034/34072162-3b1481f0-e2bd-11e7-85f8-e89aea6c2019.png)

**Comment by volzhs** [comment]
![screenshot from 2017-12-17 01-28-02](https://user-images.githubusercontent.com/8281454/34072380-c17212f6-e2c9-11e7-9e1f-3bb309a2fabe.png)

with 2.1.4, we can't create `ScrollBar`, `Slider` node, like `CanvasItem`
I think this is a bug if these are can be created on scene.
maybe we should disallow `Range` node too?
