### ISSUE TITLE
Unsafe mix of type 'bool' and type 'int' in operation (OS::set_borderless_window)

### ISSUE THREAD

**Issue by mattiascibien** [godotengine/godot#14663]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot master

**Issue description:**
While trying to compile with windows I have stumbled on this warning.

```
platform\windows\os_windows.cpp(1602): warning C4805: '==': unsafe mix of type 'bool' and type 'int' in operation
```

Which is related to `set_borderless_window()`.

Is there any particular reason it is a integer as I as far as I can tell it can accept only 1 or 0 from gdscript (it seems that it is a bool). I cannot check on unix or mac but as far as I can tell it can be refactored to accept a bool on every OS implementation (or just cast it to bool on os_windows).

**Comment by akien-mga** [comment]
According to `git blame`, we should blame @SaracenOne :) (6eb4812317). But yeah, there's no reason for it to be an int.

**Comment by mattiascibien** [comment]
I'll send a PR this evening with the changes for all platforms (hoping not to generate other warnings)

**Comment by mattiascibien** [comment]
@akien-mga  thanks

**Comment by akien-mga** [comment]
> I'll send a PR this evening with the changes for all platforms (hoping not to generate other warnings)

Sorry, I pushed my commit right before reading this :D

Thanks for the report, it was a harmless issue but it's good to fix such warnings :)

**Comment by mattiascibien** [comment]
No problem. Glad to be of help.
