### ISSUE TITLE
Script editor text selection with keyboard CTRL+SHIFT+arrows jumps strangely

### ISSUE THREAD

**Issue by lmjk** [godotengine/godot#14675]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux (Fedora) x86_64, Godot 2.1.4 official stable.

**Issue description:**
In script editor, selecting different portions of text sequentially with CTRL+SHIFT+RIGHT/LEFT makes the previous selection to suddenly reappear.

![selection_keyboard](https://user-images.githubusercontent.com/25223253/34016238-cf46857a-e129-11e7-83ff-3fe8448c8b84.png)

**Steps to reproduce:**
1) In script editor, create a new GDScript file, eg. named "bugs.gd".
2) If it is not there already (it is), put the text cursor at the absolute beginning of the file by mouse left-click and *then start jumping forward by pressing CTRL+SHIFT+RIGHT repeatedly until you have selected the three first lines* of the default text in bugs.gd.
3) Left-click the text cursor to the end of the file, ie. on the empty line 11.
4) Press CTRL+SHIFT+LEFT only once.
As result, the region selected in 2) is selected again.

**Link to minimal example project:**
Any new project will suffice.

**Comment by lmjk** [comment]
Can be reproduced in 3.0 beta 1, too.

**Comment by MattUV** [comment]
It is not only happening in the script editor, but in every `TextEdit`.
