### ISSUE TITLE
BakedLightmap does not detect and use the GridMap models.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#14687]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Manjaro 64bit, Godot - Master build, NVidia GT540M

**Issue description:**

BakedLightmap in does not detect and use the GridMap models.

**Steps to reproduce:**
Import an object with generated uv2 for lightmap and make it in to a MeshLib, then create a GridMap and use it. Try to Bake. Nothing happens. It is like the Meshlib meshes are do not have UV2.

**Link to minimal example project:**
[Bake_GI_Probe_Problems.zip](https://github.com/godotengine/godot/files/1561722/Bake_GI_Probe_Problems.zip)

Test tsc in GridMap.tscn

**Comment by kakoeimon** [comment]
Reduz's answer on the issue on irc :

> <reduz> using gridmaps is not possible, because gridmaps are drawn using instancing. They will work with GIProbe, but not BakedLightmap
<reduz> the only way to make them work would be an option to convert gridmaps to meshinstances

He told me to keep it open cause someone may want to work on this.
So I keep it open.

**Comment by reduz** [comment]
After discussing with @MarianoGnu , it may be possible to bake meshes transparently when running the lightmapper pass, so GridMap changes to meshes without you noticing and can add lighting.

**Comment by kakoeimon** [comment]
I am closing this cause it was implemented.
https://github.com/godotengine/godot/commit/e96c40f94a87325a5838662800277577b95f558b

**Comment by kakoeimon** [comment]
Although this lead to another issue : https://github.com/godotengine/godot/issues/14795
