### ISSUE TITLE
BakedLightmap in VoxelTrace mode does not create proper emission.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#14685]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Manjaro 64bit, Godot - Master build, NVidia GT540M

**Issue description:**

BakedLightmap in VoxelTrace mode does not create proper emission. 
![bake_voxel_emmision](https://user-images.githubusercontent.com/13662414/34028752-aaab3f5a-e16d-11e7-9928-9ec7c9946ab2.png)
^^ The left part gets more light.

**Steps to reproduce:**
Bake with only emission lights.

**Link to minimal example project:**
[Bake_GI_Probe_Problems.zip](https://github.com/godotengine/godot/files/1561722/Bake_GI_Probe_Problems.zip)

Test tscn is test_Bake_voxel_cone_emmision.tscn

**Comment by reduz** [comment]
This was the bias issue, which should now be closed.

**Comment by capnm** [comment]
@reduz IMO nothing has changed so far (c2240a2a714526e226ead5a20e3a070bb3eaaef6)
in relation to this issue, please check the example project.

**Comment by reduz** [comment]
I just cant figure out whats going on and cant spend more time on this. For 3.1 will use a different algorithm for baking anyway.

**Comment by reduz** [comment]
Kicking this to 3.2, as a different baking algorithm will be used.

**Comment by KoBeWi** [comment]
Fixed with the new lightmapper in 4.0-dev.
![image](https://user-images.githubusercontent.com/2223172/98412251-e62f7900-2077-11eb-9e00-a17b42a626bf.png)

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/40035 will also likely fix this in 3.2.x once it's merged :slightly_smiling_face:
