### ISSUE TITLE
Particle emission improvement proposal

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#14697]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

For now, amount, explosiveness, and randomness are relative to particle lifetime.
It could be better if :
- a duration parameter is added to define the amount, explosiveness and randomness time scope (instead of lifetime)
- randomness only impact emission frequency (and not lifetime)
- lifetime only drive particle lifetime, is moved in particle material, and get its own random parameter

**Comment by pwab** [comment]
I'll just link here to make it part of the discussion in the [GIP](https://github.com/godotengine/godot-proposals):
https://github.com/godotengine/godot-proposals/issues/815

**Comment by akien-mga** [comment]
Superseded by godotengine/godot-proposals#815.
