### ISSUE TITLE
BakedLightmap energy does not affect dynamic objects.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#14693]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Manjaro 64bit, Godot - Master build, NVidia GT540M

**Issue description:**
BakedLightmap energy does not affect dynamic objects.
Set up BakedLightmap and meshes to be baked, set BakedLightmap to ConeTrace and energy one.
Result looks ok.
![bake_dynamic_energy_1](https://user-images.githubusercontent.com/13662414/34034459-519c2220-e187-11e7-81bb-4cf9e8de7e59.png)

Change energy to 16 (max) and bake.
Dynamic object looks the same with energy 1.
![bake_dynamic_energy_16](https://user-images.githubusercontent.com/13662414/34034496-7bfafbae-e187-11e7-9097-0dfb88447c39.png)

**Steps to reproduce:**
I used only emission lights.

**Link to minimal example project:**

[Bake_energy.zip](https://github.com/godotengine/godot/files/1562110/Bake_energy.zip)

**Comment by reduz** [comment]
This seems fixed in code, so closing.
