### ISSUE TITLE
Text underlines should be two pixels-thick on hiDPI displays at 200% scaling or more

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#14691]
At 200% scaling or more, text underlines should have a thickness of two pixels instead of one.

Text underlines currently look like this on hiDPI (below the "float" keyword):

![godot_thin_text_underline_on_hidpi](https://user-images.githubusercontent.com/180032/34032848-22eae830-e178-11e7-8ab2-bca1fe60ef04.png)

This issue can also be seen in the scene tree's separator and (optional) relationship lines:

![godot_scene_tree_relationship_lines_on_hidpi](https://user-images.githubusercontent.com/180032/34033044-e614774a-e178-11e7-86d3-396c741a7449.png)

Notice how the lines (which are subtle) are only one pixel-thick.

**Comment by volzhs** [comment]
fixed by #14707?
