### ISSUE TITLE
BakedLightmap restarts and freezes when finished if you click on the editor as it bakes.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#14701]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Manjaro 64bit, Godot-Master, GT540M

**Issue description:**

BakedLightmap restarts and freezes when finished if you click on the editor as it bakes. 

**Steps to reproduce:**
Setup a BakedLightmap start baking and click on the view of the editor.

Messages from the Output.
 editor/plugins/baked_lightmap_editor_plugin.cpp:56 - Condition ' tmp_progress != __null ' is true.

After a long freeze it spams several and the editor looks like it does not perform well:

 editor/plugins/baked_lightmap_editor_plugin.cpp:63 - Condition ' tmp_progress == __null ' is true. returned: false

And in the end
 editor/plugins/baked_lightmap_editor_plugin.cpp:68 - Condition ' tmp_progress == __null ' is true.

And the editor is fine.

**Comment by reduz** [comment]
This was fixed recently, so closing
