### ISSUE TITLE
The FPS label in the 3D viewport partially covers the Camera Preview button

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#14719]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 Beta 433cb6f

**Issue description:**
The FPS label partially covers the Camera Preview button.
![Blocked Button](https://i.imgur.com/X546oKa.png)

**Comment by volzhs** [comment]
how about moving it to left bottom corner?
