### ISSUE TITLE
Add a label to describe how to use the Import dock (similar to the Node dock)

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#14714]
A common issue for newcomers and 2.1.4 migrants I've experienced over the past few weeks is that the Import dock is really not clear about how to use it, as nothing on it is usable or gives any reaction on launch and for the majority of the time working in Godot, since people don't usually have a file selected in the FileSystem dock while working through scenes.

I think a good solution to this would be to simply mirror the Node dock's behaviour: display clear instructions on how to get the Import dock to do something inside the dock itself when no file is selected.
Something like this:
![importproposal](https://user-images.githubusercontent.com/20242421/34055288-d07be91c-e1ce-11e7-9698-1d7236f8b24a.png)
(Text is just there to get the idea across, it can definitely be worded better.)

**Comment by Zylann** [comment]
Note it can also be selected from inspector itself if a resource is assigned to a property
