### ISSUE TITLE
Enable download binaries of Nighties for Godot 3

### ISSUE THREAD

**Issue by ironicnet** [godotengine/godot#14710]
**Issue description:**
It would be great to be able to download the binaries from the main page, as we can do for the stable version.

**Steps to reproduce:**
- Purchase a brand new computer
- Try to install godot 3 from website
- Fail to find it on the page, go to the source code.
- Install all the requirements for compiling as listed here: http://docs.godotengine.org/en/stable/development/compiling/index.html
- Go to unity and download

It would be great that nondevs can use the software that they will use in the future. 

I know that there is already an unofficial repository for the nighties:
http://godot3builds.digitecnology.com

Is there a way to integrate them to the download page?

**Comment by brainsick** [comment]
It's not a nightly, but Godot 3.0 Beta 1 is available [here](https://godotengine.org/article/dev-snapshot-godot-3-0-beta-1).

**Comment by Alexia-AT-Digitecnology** [comment]
I'm open to integrate the builds I made in Digitecnology with Godot official people.

**Comment by eon-s** [comment]
Maybe a link to https://github.com/GodotBuilder/godot-builds/releases

**Comment by akien-mga** [comment]
> Maybe a link to https://github.com/GodotBuilder/godot-builds/releases

No, those are not meant for testers, only for release managers.

**Comment by ironicnet** [comment]
I didn't notice that there was an unstable doc path.

Maybe it would be great to add it to the page. Nowadays there is no way from the main page to get to any of those links.
It would be great to see the docs, and have a "Unstable" option behind or in the documentation itself.

**Comment by vnen** [comment]
@ironicnet the home page of the documentation starts with a tip about the documentation version. The beta version link is only provided in the announcement articles because it's not yet a released version and users should be aware it's only for testing.

**Comment by ironicnet** [comment]
I understand that the unstable is only for testing. But educating users about it and providing them a way to test it would be great. 
The annoucement articles works when are the last 4 articles or so. Right now from the main page there is no way to know there is a testing release or a testing documentation.

Unity provides a big warning about their "beta" program:
https://unity3d.com/es/unity/beta

**Comment by NilsIrl** [comment]
Could this be tied to the continuous integration?

**Comment by Calinou** [comment]
#38189, #38303 implement the first step for official nightly builds.

**Comment by akien-mga** [comment]
We do plan to provide daily builds for Godot eventually, and as mentioned above several options exist already for now.

Further down the road we want to use our own CI system (on our own build server) to provide daily builds (or possibly builds for all commits) using the exact same build conditions as our official releases.
That's mostly down to @hpvb and me to make it happen, but we don't necessarily need a feature proposal as a reminder, so I'll close this.
