### ISSUE TITLE
Projects order in Project Manager not always correct

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#14722]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

win10 64bit
Godot 3.0 build 433cb6f49

was messing with a project that was second from top down on the list in project manager, saved the project and quit godot. when I relaunched godot, the project was still listed in second place in project manager, my understanding is that the latest worked on project is pushed to the top unless there is a project with a star tag.

**Comment by kubecz3k** [comment]
As far as I understand, according to code it seems that indeed modification date is the factor that is taken into account in sorting: https://github.com/godotengine/godot/blob/master/editor/project_manager.cpp#L907 (also https://github.com/godotengine/godot/blob/master/editor/project_manager.cpp#L649)

**Comment by kubecz3k** [comment]
Quite possible saving project without doing any modifications at all is simply not enough to consider project as modified.

**Comment by abaky** [comment]
i dont know how the list of projects is stored, but as soon as you open whatever project, project manager should  treats that project as the last one open and bump it to the top of the list. so even if you save nothing, the project was open and is going to be at the top the next time you launch godot.

**Comment by Calinou** [comment]
The "Last Modified" sorting option was renamed to "Last Edited" in https://github.com/godotengine/godot/pull/36152, closing.
