### ISSUE TITLE
GLTF file fails to import correctly

### ISSUE THREAD

**Issue by hpvb** [godotengine/godot#14725]
Godot a5db25bd27351564f391c5f0516dff64ea61544b 

**Issue description:**
Imported a gltf model from https://sketchfab.com/models/b655f2ea990e404b93e8b3c6f3c08246# 
Most of the scene and animation imports properly but there are some bits in the wrong place

**Steps to reproduce:**

Add the downloaded gltf file to your project and open the scene

![screenshot from 2017-12-16 02-14-13](https://user-images.githubusercontent.com/2591099/34065860-d5ba4328-e206-11e7-8316-21b9a7e4f5bc.png)

**Comment by hpvb** [comment]
Still broken after 7d0cabe9d30238ff2d9a05cecbbc22a45ce71ac1

**Comment by LinuxUserGD** [comment]
Try to import the file in another software to maje sure that the glTF file isn't broken. Godot 3 only supports files exported with the Khronos glTF 2.0 blender addon.

**Comment by LinuxUserGD** [comment]
#14636 (duplicate)

**Comment by reduz** [comment]
I found that some animations exported from sketfatch seem to be incorrect, so not quite sure if it's a bug. Wonder if there are other softwares to test.

**Comment by capnm** [comment]
@reduz Unfortunately;) the model doesn't seem to be broken,
see the comparison between godot c595aff4a30f79cc75a30decfad7243c03824bab
and the viewer https://youtu.be/wuoc2FXezcM

Testing the models is  e.g. possible online http://github.khronos.org/glTF-Validator/ or
https://gltf-viewer.donmccurdy.com/
or with the vs-code plugin https://github.com/AnalyticalGraphicsInc/gltf-vscode

For the importer validating there are IMO more tested/sane models in the glft
sample repository https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0

**Comment by akien-mga** [comment]
At this stage I doubt we'll get this fixed for 3.0, so moving to 3.1 milestone. It will of course be a priority for 3.1 and 3.0.x releases to improve the glTF pipeline.

**Comment by reduz** [comment]
I cant find the problem myself, moving to Hero Wanted
