### ISSUE TITLE
AcceptDialog children not affected by light mask

### ISSUE THREAD

**Issue by randoum** [godotengine/godot#14729]
Godot v2.1.4

**Description**
Setting a light mask to an AcceptDialog does not reflect on its children 

**Step by step**
1- Create an empty scene
2- add an AcceptDialog node
3- in the inspector pane, set the light mask as follow : un-check the first box and check the last box
4- add a script to the AcceptDialog node, and paste the following code
```
extends ConfirmationDialog

func _ready():
	print("dialog mask: ", get_light_mask())
	for c in get_children():
		print("child (", c.get_name(), ") mask: ", c.get_light_mask())
		for d in c.get_children():
			print("sub-child (", c.get_name(), "-", d.get_name(), ") mask: ", d.get_light_mask())
```
5- run the project, the ouput shows that the light mask was not reflected to the children of the Dialog:
```
dialog mask: 524288
child (@@8) mask: 1
child (@@9) mask: 1
child (@@10) mask: 1
sub-child (@@10-@@15) mask: 1
sub-child (@@10-@@14) mask: 1
sub-child (@@10-@@11) mask: 1
sub-child (@@10-@@12) mask: 1
sub-child (@@10-@@13) mask: 1
```

**Workaround**
For the meantime, a simple workaround could be:
```
var popup = get_node("my_dialog")
var mask = popup.get_light_mask()
for c in popup.get_children():
	c.set_light_mask(mask)
	for d in c.get_children():
		d.set_light_mask(mask)
```

**Comment by KoBeWi** [comment]
Can't test in 4.0 because dialogs don't seem to show in the editor, but this is likely fixed or no longer valid.
