### ISSUE TITLE
Eye icon in scene tree doesn't shut.

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#14721]
Ubuntu 16.04, Godot 3 build 68cf66c

When hiding a node in the scene tree, the eye that marks visibility no longer shuts and instead merely darkens:
![image](https://user-images.githubusercontent.com/20242421/34061147-2e04e08a-e1e7-11e7-9d0f-d4edd13b5804.png)
(The node named "main" is hidden.)

Could #14674 be the cause?

**Comment by akien-mga** [comment]
CC @djrm

**Comment by djrm** [comment]
thats the new icon.

**Comment by CowThing** [comment]
I think there should be some difference beyond color change. Maybe a slash through it like this?
![example](https://user-images.githubusercontent.com/11450875/34063786-53e60cae-e1c2-11e7-904b-9b52b9d1f77d.png)

**Comment by akien-mga** [comment]
I liked it with the eye shut, what's the reason for changing it?

**Comment by djrm** [comment]
i guess i will rollback then...

**Comment by leoddd** [comment]
It's really helpful to have distinct icon silhouettes to see which nodes are hidden more quickly, so yeah, I preferred it when it shut, but the strikethrough would work too.
Really anything to separate them!

**Comment by djrm** [comment]
the alpha provides enough differentiation, well at least for me, but i will rollback anyways.

**Comment by akien-mga** [comment]
> the alpha provides enough differentiation, well at least for me, but i will rollback anyways.

The problem is what is shown on the above screenshot: We have three alpha states now, for "visible", "hidden", and "configured visible but hidden due to parent", and it's not immediately obvious IMO. With the previous icon, we had open and full opacity for visible, closed for hidden, and open with lower alpha for the third state, which was more intuitive.

**Comment by Zylann** [comment]
IMO, it should be:
- visible: eye open
- hidden: eye closed
- hidden because of parent: eye open but faded
I noticed the three alpha states only after reading Akien's answer...

**Comment by djrm** [comment]
this has been solved
