### ISSUE TITLE
Error during export if there are duplicate assets in the project

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#14728]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot a5db25bd27351564f391c5f0516dff64ea61544b

**Issue description:**
If you have the same sound (and likely any other asset) in different project folders, they will both reference the same imported asset from `.import` folder. Then during export `export_project_files` will call the export function twice for the same file, which is unexpected for some exporting code, leading to errors such as this:

```
jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: assets/.import/Attack01.wav-2daa26c2699672cc6d9773c8c40bcb77.sample
```

For .pck export there won't be an error, but the .pck is going to have duplicate entries which is not good.

**Steps to reproduce:**
Add a sound/image to two different project folders, reference them both from a scene, and export the project to Android.

EDIT:

The steps to reproduce are misleading - the hash part of the imported name is a path, so you won't reproduce it that way. Apparently we accidentally duplicated .import file along with the sound file itself. Still, as a potential improvement Godot could check that the import path is up to date and/or export code could avoid duplicates.

**Comment by kubecz3k** [comment]
So do I understand correctly that we should ensure there are no orphaned .import files in the project?

**Comment by endragor** [comment]
No, they are not orphaned, the problem is that two different assets were referencing the same .import file, which shouldn't happen under normal circumstances. So maybe part of reimport check should be to also check that the .import file path is valid for the current file.

By .import file path I mean this one (from the `[remap]` section):
```
path="res://.import/Sound.wav-0cbddbbcf34b3a40a552c9c6cf51189a.sample"
```

**Comment by reduz** [comment]
This should now be fixed, as the imported files now store the source path, and destination md5 and file paths:

```
[deps]

source_file="res://icon.png"
source_md5="98282455c511259a2dab665605bb7474"

dest_files=[ "res://.import/icon.png-487276ed1e3a0c39cad0279d744ee560.stex" ]
dest_md5="0356d0b3f0b9848c6c1ee307abf658a9"
```

To avoid annoying everyone with massive reimports, old imported files still work, but new ones are imported with this information and properly checked.

**Comment by reduz** [comment]
In any case, please test.

**Comment by endragor** [comment]
@reduz did you mean to close #14858? Does this one actually get fixed after the change? The problem occurred when e.g. you copied over a file along with its *.import counterpart to a different folder. All the hashes were valid, but destination path was left the same which caused problems.

**Comment by reduz** [comment]
Yes this should be fixed, but only on new imports.

On Dec 27, 2017 10:21 PM, "Ruslan Mustakov" <notifications@github.com>
wrote:

@reduz <https://github.com/reduz> did you mean to close #14858
<https://github.com/godotengine/godot/issues/14858>? Does this one actually
get fixed after the change? The problem occurred when e.g. you copied over
a file along with its *.import counterpart to a different folder. All the
hashes were valid, but destination path was left the same which caused
problems.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/14728#issuecomment-354209789>,
or mute the thread

**Comment by topevidence** [comment]
Reproduced in  Godot 3.2.1
jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: assets/.import/girl_blonde.png-79134ee806a109971cf9546b91f8f2b7.stex

I used the same texture several times in the same project. The result I cannot export project to Android (to .apk or to device result the same)
