### ISSUE TITLE
When adding a node, node is not properly selected on adding to tree

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#14733]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux, v3.0.beta.custom_build.433cb6f
From: http://godot3builds.digitecnology.com/ - 2017-12-15.12:12:09.433cb6f49

**Issue description:**
Expectation: Add a node, except it to be highlighted ready for editing
Reality: Node is partially selected but not able to be interacted with unless it is re-selected from the hierarchy or you select a different node first.
![image](https://user-images.githubusercontent.com/3120639/34070469-28141e36-e267-11e7-8775-71e551055d28.png)

**Steps to reproduce:**
1. Open a blank project
2. Add a node
3. Notice you have no drag handles and can't interact with the node until you deselect it
4. Add a child node
5. Notice the same behavior
6. Get on github and open an issue

**Comment by DualMatrix** [comment]
Tested in master, node is now properly selected.

**Comment by akien-mga** [comment]
Thanks, closing.
