### ISSUE TITLE
Editor crash when confirming node deletion with Enter

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#14730]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 a5db25bd27351564f391c5f0516dff64ea61544b, macOS 10.12.6, Windows 10 x64, Windows 7 x64

**Issue description:**
Editor crashes when you confirm node deletion with Enter

**Steps to reproduce:**
Select a node on a scene, press Delete, press Enter.

**Comment by RayKoopa** [comment]
Can't reproduce with https://github.com/godotengine/godot/commit/3f7f65cd1c1d5e247f7f55c49a7e7e2a84fbbec7 (on Windows 10).

**Comment by hpvb** [comment]
Can't reproduce with 7a10d3ab78975a95f55b1bf97705ff8cc300da08
* Linux/64
* Wine/64

**Comment by endragor** [comment]
Oops, indeed, there was a bug in my fork. Thanks for checking guys and sorry for the false alarm.
