### ISSUE TITLE
Cant hide CanvasModulate 

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1473]
It seems like there is some problem with all CanvasItem options in CanvasModulate. 'Visible' checkbox doesn't work, so as all other options there. In order to hide it, you need to delete it basically.

**Comment by reduz** [comment]
CanvasModulate only has a color, the rest of the options are just regular
canvasitem options which are ignroed in that node

**Comment by akien-mga** [comment]
I guess those ignored options should be hidden then?

**Comment by akien-mga** [comment]
> I guess those ignored options should be hidden then?

I'm not sure if parent properties can be disabled/hidden though.

**Comment by akien-mga** [comment]
Toggling the `visible` property seems to work fine here to hide the CanvasModulate. As for the other options, they indeed don't seem to do anything (though it would be nice if the `opacity` property was multiplied to the `Color`'s alpha value).

**Comment by akien-mga** [comment]
Does `CanvasModulate` need to inherit `CanvasItem` if it doesn't use its features, or could it just inherit `Node`?

**Comment by breakmt** [comment]
@akien-mga @reduz sorry, but I don't get it from comments -- is this expected behaviour? I was a little surprised, that Toggle Visibility doesn't affect on CanvasModulate.
![2019-04-21_195019](https://user-images.githubusercontent.com/1552169/56473103-1fd96880-646f-11e9-9ab1-5785f1d51ecd.png)
