### ISSUE TITLE
Regression: MenuButtons stay pressed after clicking them

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#14740]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master: 83b1556

**Issue description:**
Self-explanatory:
![screenshot at 2017-12-16 11-59-41](https://user-images.githubusercontent.com/30739239/34071120-a4926026-e258-11e7-888e-f0a74e713dbf.png)

**Comment by akien-mga** [comment]
That's a regression from today's merges, can't reproduce with a build from 9b33438.

**Comment by akien-mga** [comment]
Didn't test, but likely a regression from #14484.

**Comment by vnen** [comment]
I presume it's fixed since it was reverted by #14756. Comment if still persists on current master.
