### ISSUE TITLE
Regression: Scrolling the mouse wheel inside an unfocused Control doesn't focus it anymore

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#14741]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master: 83b1556

**Issue description:**
I don't know what happened in the last commits, but now using the scroll wheel inside the Scene Editor no longer puts the focus back to it.

**EDIT:** Correction, it doesn't put the focus back in any Control.

**Comment by akien-mga** [comment]
Didn't test, but likely a regression from #14484.

**Comment by vnen** [comment]
I presume it's fixed since it was reverted by #14756. Comment if still persists on current master.
