### ISSUE TITLE
[suggestion] moving scripts tabs : replace Ctrl+Left and Ctrl+Right with something else

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1474]
Hi,

Tested under windows with recent compiled source code.

Into the script editor, when several scripts are opened, it is possible to change their Tab ordering using the "Move Left" and "Move Right" menu items into the "Window" menu.

These menu items are currently associated to the keyboard shortcuts Ctrl+Left and Ctrl+Right.

However, these two shortcuts only work when the "window" menu is opened, because Ctrl+Left and Ctrl+Right are also used into the script editor to move the cursor to the next or previous tocken.

This render these shortcuts useless. They should be changed to something else.

**Comment by silverkorn** [comment]
I don't know if it's a standard but, by example, in FL Studio, I use `Shift` + `Arrow key` to change the selected channel ordering (see also: http://www.shortcutworld.com/en/win/FL-Studio.html)

**Comment by bojidar-bg** [comment]
I guess it will be nice to be able to reorder them by dragging too...

**Comment by okamstudio** [comment]
I am thinking of removing script tabs and adding a list at the left


On Fri, Jun 12, 2015 at 8:25 AM, Bojidar Marinov <notifications@github.com>
wrote:

> I guess it will be nice to be able to reorder them by dragging too...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1474#issuecomment-111457835>.
>



-- 

*OkamStudio*

**Comment by SuperUserNameMan** [comment]
That could be more convenient.

**Comment by eska014** [comment]
Scripts are opened in a list rather than in tabs by now.
