### ISSUE TITLE
RigidBody (character) behave differently between Godot old physics engine and Bullet Physics

### ISSUE THREAD

**Issue by satyries** [godotengine/godot#14751]
Ubuntu Xenial based, Godot nightly 4th and 5th (the switch between Godot Internal Physics engine and Bullet Physics)

**Issue description:**
This script: https://pastebin.com/C3FDmfM4 applied to a RigidBody (character) is expected always move it forward. The result is interpolated each physic cycle because this script is also expected to work in multiplayer games (avoid jerky movements in case of latency). In the old Godot Physics it did work fine with no visible issue at all.

In the switch between Godot and Bullet Physics it seems to causes issues when the body moves on the Y axis (moving on a slope): it visibly stutter, while in the original Godot Engine physics it walks smoothly

**Steps to reproduce and link to minimal example project:**
[testpy.tar.gz](https://github.com/godotengine/godot/files/1565028/testpy.tar.gz)
this archive contain the a small example with the two Godot's Linux binaries for both Godot's old physics engine (file: godot.linux-20171104) and Bullet Physics (file: godot.linux-20171105)

1. run godot.linux-20171104 (the project is automatically loaded)
2. see the capsule descending a slope smoothly
3. run godot.linux-20171105 for Godot loaded with Bullet (pun shamelessly intended u_u) Physics.
4. the capsule stutter while descending the same slope

**Comment by satyries** [comment]
The script simplified like this:
```

extends RigidBody
var hv = Vector3()
func _enter_tree():
	set_physics_process(true)
func _integrate_forces(state):
	var lv = get_linear_velocity()
	lv.z = -1
	set_linear_velocity(lv)
```
gives the same result.

**Comment by LHolten** [comment]
you may need to use this:
```
extends RigidBody
func _enter_tree():
	set_physics_process(true)
func _integrate_forces(state):
	var lv = state.get_linear_velocity()
	lv.z = -1
	state.set_linear_velocity(lv)
```

**Comment by satyries** [comment]
@LHolten sorry for the late reply, I was busy in other projects.
Adding state to get_linear_velocity() doesn't change anything, sadly. When enabling Godot physics, the capsule slide smoothly, when enabling DEFAULT or Bullet physics (which is the default, I presume) the capsule jitter up and down.
(tested on yesterday builds)

**Comment by OGMP-Gyrth** [comment]
I think I'm having the same issue. Changing the Physics FPS in the project settings changes the hippidyhoppidy frequency as well. 
![peek 2018-02-22 18-19](https://user-images.githubusercontent.com/14081613/36553684-3fa93dda-17fd-11e8-9210-c600f279584d.gif)

**Comment by mysticfall** [comment]
Not sure if it's the same issue, but I also see different behavior of a simple primitive rigidbody between the two physics engines.

I created a primitive sphere and attach a sphere collision shape to it. Then I turned it into a rigidbody with the bounce value of `0.3` and the mass of `3`.

When I drop the sphere on to the ground which is a static body with `0` bounce, it bounces off the surface and moves around after the impact, as if there's some force constantly affecting the body in Bullet engine.

But if I switch it to use GodotPhysics instead, the sphere stabilizes after bouncing up a short distance, as it is expected from its properties.

I also took a video showing the problem: https://youtu.be/a5S-1LIzEPc

**Comment by fire** [comment]
I also had the problem with jitter. As I'm in vr, changing the physics to be 90 fps rather than 60 made the motion smoother.

**Comment by Calinou** [comment]
@satyries Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
