### ISSUE TITLE
3D Odd collision bug with the plane shape

### ISSUE THREAD

**Issue by Edmanbosch** [godotengine/godot#14750]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OS: Windows
Godot Version: 3.0 Beta 1

**Issue description:**
So I currently have Rigidbodies that bounce around the scene. There is a Staticbody which is a plane and acts as the "floor". The problem is that even when the rigidbodies are not even close to the floor they still act as if the floor is there and they bounce. I've been messing around with the settings for the collision shape on the Staticbody and I still have no idea why this is happening.

**Steps to reproduce:**
1. Make a scene with a rigidbody node that has a cube collision shape and a cube mesh attached.
2. Add a staticbody node with a plane collision shape and a plane mesh attached to the scene.
3. Move the rigidbody up on the y axis and move it to where it shouldn't collide with the staticbody.

**Gif of the issue**
![godot plane collision issue](https://user-images.githubusercontent.com/30306273/34073164-55f2e978-e248-11e7-9da6-4f78676a7a92.gif)

**Comment by Zireael07** [comment]
Plane rigidbody has infinite dimensions, so it's not limited to your visible mesh. Not a bug.

**Comment by Edmanbosch** [comment]
It's not a rigidbody, it's a staticbody. An if plane collision shapes were infinite, then why am I able to edit the scale of the shape?

**Comment by CowThing** [comment]
Plane collision shape is infinite no matter what body it's attached to. Translation and scale can be changed because the CollisionShape node inherits from Spatial

**Comment by Edmanbosch** [comment]
But when I change the scale and translation they change the look of the collider in the editor, and they don't make it seem at all like it's infinite.

**Comment by CowThing** [comment]
Other collision shapes do the same when you translate or scale them. Although shapes should only be scaled uniformly, I think.

The only reason it renders as a square is to make it easier to see. I don't know if there's a better way to represent an infinite plane, maybe there is?

**Comment by Juankz** [comment]
My thought: If I have a plane shape then the collision shape should match the plane mesh just like box shape match the cube mesh

**Comment by AndreaCatania** [comment]
The plane shape collision is mean to be infinite and is not possible have finite plane shape. It's useful when you want to have floor at the end of the world in order to stop falling bodies at certain height, it's not meant to be used to be part of a scene.

If you need just a plane you can generate a trimesh convex shape, in this case the shape will have the exactly same size of visible mesh.

So this is not a bug and can be closed.
