### ISSUE TITLE
Undo/Redo not functional in AnimationTreePlayer editor

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1476]
Hi,
Like the title say, Undo/Redo not functionnal in AnimationTreePlayer editor.

**Comment by reduz** [comment]
this editor will be rewtritten using the new node graph API in 1,2 I guess..

**Comment by akien-mga** [comment]
Is this bug still valid in the current master branch / nightly builds?

**Comment by akien-mga** [comment]
Ping.

**Comment by SuperUserNameMan** [comment]
Sorry, I have not used Godot for a while, and I had thousands of github notifications ....

To answer your question, yes, this bug is still present into current v2.0.2.stable official release

**Comment by reduz** [comment]
Closing this, because AnimationTreePlayer is deprecated and no further work will be done on it.
