### ISSUE TITLE
Embedded resources

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#14763]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
any, all

**Issue description:**
Godot doesn't have anyway to view embedded resources. This becomes a problem if you created a resource but forget to save to disk. this is troublesome to troubleshoot on a large project since it would likely get buried. Needle in a haystack anyone!

**Steps to reproduce:**
create a embedded resource like a shader. Leave it; Forget it; wait till your project grows. Then good luck.

**Link to minimal example project:**
Nice to have a profiler for embedded resources or just a way to keep track of them.

**Comment by Zylann** [comment]
Yeah seems to be a use case if you always embed resources when creating stuff and at some point you want to re-use one. Though I almost never embed resources unless I intentionally know they are small enough or never going to be reused. But if I change my mind... searching by name won't work because they have no name, so only way is to find the scene in which it is and remember in which spot it wad used.

Would this present in a window showing all embedded resources in all scenes? (Remember they have no name)

**Comment by reduz** [comment]
Maybe an option in the fle manager RMB menu, "Show embedded resoures?"

**Comment by RabbitB** [comment]
> Maybe an option in the fle manager RMB menu, "Show embedded resoures?"

I think this, along with dynamic auto-generated names would be a good solution. When you enable `Show Embedded Resources`, any scenes in the currently viewed directory will have their embedded resources show, with auto-generated names along-the-lines of `SceneName@Node/Path!Property`

Obviously the actual solution would need some more thought put into it than that, but I think it's a starting point.

**Comment by lmjk** [comment]
I'm really new to Godot (and very impressed by it!) and I too have thought about this usability issue already. 

How about just putting everything imaginable in the Node tree view? I think it would be the most logical and fastest place to look for anything a specific node has eaten. They would stay organized. I know virtually nothing about Blender, but at least it _looks_ like they have done it about that way and thus it might be a good candidate to steal and rework ideas from:

![screenshot_20171221_162953](https://user-images.githubusercontent.com/25223253/34259825-6aea4e34-e66c-11e7-8c49-f09cd312fb07.png)

(Such as the possibility to show all scenes in a unified tree view at once, like the "All Scenes" button suggests -- possibly the main scene even highlighted with a special icon or background, why not -- in addition to the everything-in-the-node-tree feature, of course.)

**Comment by Zylann** [comment]
How would you show embedded resources that are shared between multiple nodes? Just shown twice?

**Comment by reduz** [comment]
@lmjk Right click on any node and you can see the embedded resources already,.

**Comment by RabbitB** [comment]
@Zylann As my potential solution involves the node as part of the auto-generated resource name, listing for each use is viable. Especially if an identifier could be visibly added that signified if different listings pointed to the same resource.

Another possible alternative is to list only the first instance of the resource that's found, but if you right-click the listing, you're given all known aliases (as the auto-generated name essentially acts as a human-usable path to the embedded resource).

**Comment by lmjk** [comment]
@reduz Didn't know, thanks for the tip! I'm mostly learning the 2.1 now, but those v3 features are quite tempting...

**Comment by Calinou** [comment]
Judging by reduz's comment, this was implemented in 3.0 already, closing.
