### ISSUE TITLE
Godot v3.0 GUI doesn't work well

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#14773]
**OS:** Archlinux amd64
**Godot v3.0 Build:** 2017-12-16.13:03:24.9079be9e8 from http://godot3builds.digitecnology.com

**Issue description:**
When you use Godot v3.0 focus disappears randomly in the entire GUI and things are no more selectable using the mouse and you can't click anything. Only Alt+F4 works to exit and keys.

**Steps to reproduce:**
- Open Godot v3.0 (using build with commit id 9079be9e8 from [Digitecnology Godot 3 Unofficial Builds](http://godot3builds.digitecnology.com) server.
- Open a Project, add a gltf model, add nodes, etc
- The GUI selection/focus fails.

**Comment by Zylann** [comment]
I think that commit got reverted, try a more recent build

**Comment by vnen** [comment]
I assume this was fixed in a more recent build. Comment if it's not the case.

**Comment by Alexia-AT-Digitecnology** [comment]
Yes, It was fixed in a recent build. It works well now.
