### ISSUE TITLE
[REGRESSION] Thumbnails for 2D scenes do not generate correctly

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#14785]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch linux, 1ef123c57, clang 5.0.0
Was not an issue on the beta1 release

**Issue description:**

Thumbnails are not correctly generated for any scene with a Node2D or Control type as the root. They are saved as green. 3D scenes still work just fine.

**Steps to reproduce:**
1. Create scene with a root of Node2D or control
2. Save scene
3. Thumbnails are entirely green

![image](https://user-images.githubusercontent.com/3120639/34083854-3b9b760a-e377-11e7-99d0-e2db55d47869.png)

**Comment by guilhermefelipecgs** [comment]
duplicate #14422
