### ISSUE TITLE
Bring back type icons

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#14783]
A while back type icons were removed(https://github.com/godotengine/godot/issues/11505#issuecomment-331609673), but with the merge of https://github.com/godotengine/godot/pull/14781, I think there is not problem bringing them back now.

**Comment by djrm** [comment]
yeah, why not if some people use it and everything is there i think it can be added back

here is the code, if someone is interested.
https://github.com/godotengine/godot/pull/12794/commits/01512efbe62dcf8d5f5ca5c070557f227f988f47

**Comment by YeldhamDev** [comment]
@djrm One problem though:
![screenshot at 2017-12-17 18-47-06](https://user-images.githubusercontent.com/30739239/34083633-ccbf0e48-e35a-11e7-96f7-0d55c8d34df3.png)

**Comment by djrm** [comment]
yeah, it seems that it is as i thought, they are not just the variant types, there are some other customs that do not have icon, and also this is using custom icon names, for example `Bool` when this icon is called `bool`, and other stuff like that, so my previous types PR does not include all the necesary icons to make this available. But if you want, you could fix the name and report the ones missing, maybe i will be able to make them if they are a considerable number.

**Comment by YeldhamDev** [comment]
@djrm Solved the issue with integers, but apparently there is no Enum icon.

**Comment by djrm** [comment]
@YeldhamDev is that the only missing icon?

**Comment by YeldhamDev** [comment]
@djrm The ones listed, yes.

**Comment by djrm** [comment]
@YeldhamDev 
```
ArrayData -> PoolByteArray
DictionaryData -> Dictionary
ArrayInt -> PoolIntArray
ArrayFloat -> PoolRealArray
ArrayString -> PoolStringArray
Matrix -> Transform
Vector -> Vector3
```

also there are several items that are array types and can actually make use of `Pool*****Array`

**Comment by groud** [comment]
I personally wouldn't like having those icons in the inspector, it overloads the interfaces, bringing redundant information. Indeed, the widget displayed to change the property already tells you, in almost all situation, what type of value you are modifying.

**Comment by YeldhamDev** [comment]
@groud It's a completely optional option, which is set off by default.

**Comment by groud** [comment]
Well ok, but it would be interesting to know if someone is going to use it. No need to add complexity to the code and a new setting in the editor configuration if nobody use it.
Having concise and pertinent settings is also allowing a better UX design.

**Comment by YeldhamDev** [comment]
@groud Everything is already there, is was only deactivated because the lack of some icons.

**Comment by groud** [comment]
Sure. But it does mean it was good. :)
The icons are obviously useful for visual shaders, but in the inspector, I don't think so.

**Comment by RayKoopa** [comment]
I think they can be useful when getting to know Godot's nodes and stuff. I used them a lot back in 2.0

**Comment by homer666** [comment]
I'll definitely be using them, though I admit they won't be anything more than eye-candy to me, as I'm pretty comfortable guessing what types different properties are.

**Comment by YeldhamDev** [comment]
@djrm Any progress?
