### ISSUE TITLE
script variable don't save if node is child of instanced scene

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#1478]
When I change in this view the script variables it will not save.
![script_variable_bug](https://cloud.githubusercontent.com/assets/10463138/6489732/1c354718-c2a1-11e4-9ccc-a9be7b856b97.png)

Only when opening scene (exp. selection) and then setting the variables it works.

**Comment by reduz** [comment]
yeah this is by design, but design will change for godot 1.1 and you will
be able to save them

**Comment by puppetmaster-** [comment]
Are this the latest build(1.1)? http://sourceforge.net/projects/godotengine/files/Builds/official/

**Comment by reduz** [comment]
oh sorry, i meant it will change for Godot 1.2. Godot 1.1 will be out soon,
then work will start in 1.2

**Comment by akien-mga** [comment]
Subscene editing has been implemented for 2.0.
