### ISSUE TITLE
Reordering child nodes in parent does not update index 

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#14793]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows 10 64, beta 1

**Issue description:**
reordering child notes inside a parent node does not update there index in code.

**Steps to reproduce:**
have a parent node and a couple child nodes. reorder the child nodes, then try to get there index through code, should reproduce the bug.

**Link to minimal example project:**

**Comment by henriquelalves** [comment]
Couldn't reproduce this on Godot master branch version using Fedora. Is there a specific setup, or any children/parent node would do?

I created a base scene with Node2D, and used
`for i in get_children():
  print(i)`
to print its children; changing their order on editor had the expected result on the printing order.

**Comment by vonflyhighace2** [comment]
Using control nodes seems to be where the issue crops up. Also using the get_index() method on the child control node gave the incorrect result. I'm using the Beta don't know if this is fixed in the master.

**Comment by vnen** [comment]
It would be nice if you provided a sample project.

**Comment by vonflyhighace2** [comment]
I found the issue. It was a matter setting up of incorrect Inputs that resulted in the issue. You can close this case/thread.
