### ISSUE TITLE
Add optional support for deep copying in Array's and Dictionary's "duplicate()" method.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#14791]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0

Currently, if someone calls `.duplicate()` on an Array, only a shallow copy is made, evidenced by the following:

    extends Node
    
    class MyClass:
        extends Object
        var me = "Bob"
    
    func _ready():
        var obj = MyClass.new()
        var d = {"hi":"hello"}
        var a = [0,obj,d]
        var a2 = a.duplicate()
        a2[0] = "test"
        a2[1].me = "Jack"
        a2[2]["hi"] = "NOTHELLO"
        print(a)
        print(a2)
        print(a[1].me)
        print(a2[1].me)

Prints:

    [0, [Object:960], (hi:NOTHELLO)] # dictionary is not retaining original value
    [test, [Object:960], (hi:NOTHELLO)] # Same object ID for index 1
    Jack # We can see the same value for property 'me'
    Jack

The same holds for the Dictionary:

    func _ready():
        var a = [1,2,3]
        var obj = MyClass.new()
        var d = {"a":a,"obj":obj}
        var d2 = d.duplicate() # may still be .copy() depending on a PR merge
        print(d)
        print(d2)
        print(a)
        print(obj.me)
        print("-------------------")
        a[0] = "test"
        obj.me = "Jack"
        print(d)
        print(d2)
        print(d.obj.me)
        print(d2.obj.me)

Prints:

    (a:[1, 2, 3]), (obj:[Object:960])
    (a:[1, 2, 3]), (obj:[Object:960])
    [1, 2, 3]
    Bob
    -------------------
    (a:[test, 2, 3]), (obj:[Object:960])
    (a:[test, 2, 3]), (obj:[Object:960])
    Jack
    Jack

Implementing a fix:

Reduz's suggestion in [this Issue](https://github.com/godotengine/godot/pull/14754) was to pass a default-false parameter indicating the desire for a deep copy. And that would work for Arrays/Dictionaries.

I imagine we could easily handle deep copying of stored Arrays and Dictionaries by using their copy constructors after checking for the flag:

    //inside Dictionary::duplicate()
    Dictionary n;
    //loop through list of Dictionary keys...
    Variant val = operator[](E->get()); // get value at that key
    if (p_deep_copy) {
        if (val.get_type() == Variant::Type::ARRAY) {
            val = Array(val);
        } else if (val.get_type() == Variant::Type::DICTIONARY) {
            val = Dictionary(val);
        }
    }
    n[E->get()] = val;

However, doing this kind thing doesn't work as cleanly for Objects/Nodes, possibly Resources. Node's at the very least have a large assortment of flags that must be passed to their own `.duplicate()` function. Object's similarly have signal connections along with scripts that users may or may not want to have in a deeply copied object. As such, we would likely need the same set of flags as `Node.duplicate()` to be available to the Array and Dictionary functions if we were to support deep copying.

Thoughts?

**Comment by Calinou** [comment]
Is this implemented by #14754?

**Comment by willnationsdev** [comment]
@Calinou No, all that PR did was unify the API between Array, Dictionary, and Node so that they could all use `.duplicate()` rather than some using that and some using `.copy()` to do the same thing. When you don't know the type of a variable, but you wanna copy it anyway, it is useful for the methodology to be the same.

**Comment by KoBeWi** [comment]
Array and Dictionary seem to have optional `deep` argument in `duplicate()` now, so this is resolved.
