### ISSUE TITLE
A SCREEN_TOUCH event occurs on scene load in Android build

### ISSUE THREAD

**Issue by emirhanaydin** [godotengine/godot#14797]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
**Godot version:** Godot Engine v2.1.4.stable.official
**Development OS:** Windows 10 Version 1709 (OS Build 16299.125)
**Target OS:** Android, ARM / x86

**Issue description:**

I have two different scenes as menu and game scene typically. There is only one button on the menu to load the game scene on press.

_set_process_input_ is active in the game scene. So the __input_ function is available. I control the _SCREEN_TOUCH_ event in the __input_ function to handle touches.

The problem is that if I run the application on the mobile device (Android), this condition triggered automatically once the scene is loaded. So I have to add an control like _initialized_ and ignore this first touch. This is not happening when I run the application in the editor. But since I ignore the first touch the _"real"_ first touch is not handled this time.

**Steps to reproduce:**
I list the steps I have taken. Not all may be necessary for the problem.

1. Create a scene with the __input_ function and check the _InputEvent.SCREEN_TOUCH_ event type.
2. Create another scene and change to the other scene with a button click over it.

That's all, a touch event occurs automatically when the scene is loaded if the app is running on Android.

**Comment by akien-mga** [comment]
What is your Godot version?

**Comment by emirhanaydin** [comment]
I've updated the description.

**Comment by gerardogc2378** [comment]
It is happening to me, same situation only with Android. Godot Engine v2.1.4

**Comment by akien-mga** [comment]
CC @RandomShaper, maybe this was fixed already by your recent work on 2.1?

**Comment by RandomShaper** [comment]
I don't think so. I'll try to fix it, nonetheless.

**Comment by vnen** [comment]
@gerardogc2378 It doesn't make sense that this is fixed in 2.1.4 since that's the same version in which the bug was reported.

**Comment by gerardogc2378** [comment]
Hi

Yes, my problem is resolved with Android, now I am using Godot 2.1.x from sources :-)

**Comment by akien-mga** [comment]
Assuming fixed in 2.1.5 as per the above comment.
