### ISSUE TITLE
BakedLightmap with GridMap creates some incremental spaces on the GridMap.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#14798]
**Godot version:**

Commit https://github.com/godotengine/godot/commit/e96c40f94a87325a5838662800277577b95f558b

**OS/device including version:**

Manjaro 64bit, GT540M NVIDIA Driver Version: 384.90 

**Issue description:**

When baking with GridMap some incremental spaces are created between the Grid Parts.

This is before the bake
![grid_space_1](https://user-images.githubusercontent.com/13662414/34105618-b936d0f6-e3fd-11e7-9349-9d35b0133742.png)

And this is after the bake (as it looks like after plotting)
![grid_space_2](https://user-images.githubusercontent.com/13662414/34105637-d0a0e7e0-e3fd-11e7-871e-ebba2044ff84.png)

**Steps to reproduce:**
Create a GridMap with parts that can be baked by a BakedLightmap, fill several cells with the objects, add BakedLightmap and then bake.

Maybe it is better to use the example project linked.

**Minimal reproduction project:**

[Gridmap_Bake.zip](https://github.com/godotengine/godot/files/1567822/Gridmap_Bake.zip)

The example project contains a camera which is placed at the position where the problem will be visible after you bake.

**Comment by reduz** [comment]
out of curiosity and to get a better idea, when you edit the gridmap again,
the spaces should be gone, right?

**Comment by kakoeimon** [comment]
@reduz if I first clean the BakedLightmap Light Data yes, If not then it looks like that it is somethin in between.

**Comment by kakoeimon** [comment]
Here the in between screenshot : 
![grid_space_3](https://user-images.githubusercontent.com/13662414/34106910-bd0cb9c0-e402-11e7-8393-8c49cbd55eda.png)

This is an in editor screenshot cause I cannot run this if I make the changes.

**Comment by reduz** [comment]
but i mean, if you go and try to edit back your gridmap, the gaps (together
with the lightmap) go away?

**Comment by kakoeimon** [comment]
@reduz I do not understand the "edit back" you are saying. This issue does not remove some cells from the Gridmap but creates some spaces (offsets?) between the cells. The pics are from a camera that points to the exac intersection between two cells. The more cells you have in line the bigger the gap.

**Comment by reduz** [comment]
I just need confirmation of the following steps:
1) No gap
2) Bake
3) Observe  Gap
4) Go back to gridmap, edit it, add a tile or something
5) Lighting information should be lost and gap should be gone

**Comment by kakoeimon** [comment]
@reduz Sorry for the late response.
That's the case. But if I try to bake again then I get a freeze.

**Comment by reduz** [comment]
Is the freeze solved now?

**Comment by kakoeimon** [comment]
@reduz  When you made this commit : https://github.com/godotengine/godot/commit/1eb1837d0cf95c2c12d8ec51127e222f6f4888c5

GridMap losted all the data and I was unable to add meshes on the cells.

I informed you on this issue : https://github.com/godotengine/godot/issues/14795

**Comment by kakoeimon** [comment]
The incremental spaces seems ok.
So I close this issue.
About the freeze I am going to comment at https://github.com/godotengine/godot/issues/14795
and give you a test file there.
