### ISSUE TITLE
ViewportTexture on a Sprite3D get_node errors on save

### ISSUE THREAD

**Issue by Smjert** [godotengine/godot#14790]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux, 27642868f

**Issue description:**

Saving a scene with Spatial->Sprite3D->Viewport and Sprite3D Texture set to a ViewportTexture pointing to the Sprite3D child Viewport leads to the following errors:

> ERROR: get_node: Node not found: Sprite3D/Viewport
>    At: scene/main/node.cpp:1520.
> ERROR: setup_local_to_scene: ViewportTexture: Path to node is invalid
>    At: scene/main/viewport.cpp:64.

This seems to happen when the Viewport appears after the node containing the ViewportTexture.
The scene duplication happens here https://github.com/godotengine/godot/blob/master/scene/resources/packed_scene.cpp#L241
and the responsible for the call to the instance() function is https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L1030

Probably related to #12781 and #14445.
I also believe that this is somehow related to #13987.

I'm not sure about the whole logic here so i'll let someone more knowledgeable than me fix it ^^'

**Steps to reproduce:**
1) New Project
2) Add a Spatial node
3) Add a Sprite3D
4) Add a Viewport either as a Sprite3D child or Spatial child
5) Set the Sprite3D texture to be a new ViewportTexture selecting the only Viewport there is
6) Save

**Link to minimal example project:**

[TestViewport.zip](https://github.com/godotengine/godot/files/1566146/TestViewport.zip)

**Comment by AlmightyScientist** [comment]
IMHO, It seems logical that a Viewport must be initialized to attach a ViewportTexture.
Should the fix notify the user about it? Or should it Inqueue ViewportTexture to wait until the scene if fully loaded?

**Comment by Smjert** [comment]
For sure i understand that, but i wasn't confindent changing the code in the instance() function, especially since  it's used in a hacky way and especially since, given the other issues, the problem seems bigger than what i've found.

**Comment by reduz** [comment]
closing, as this should be fixed by c858dbdc4
