### ISSUE TITLE
changing Next (auto-queue) doesn't mark scene as changed

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#148]
if you open up a scene (for a character or somesuch) and select the AnimationPlayer node, then click on the =><= blending button, and enter a value for the Next (Auto Queue) field, the Scene does not get marked as changed.

If this is the only change you make before switching to another scene, then you will lose the change without being prompted about it, like you should be.

------

( I poked around in the source code and I got it to mark the scene as changed by inserting an undo step, however, it does not behave as desired.. the text box loses focus after every keystroke and a new undo step is saved for every keystroke, etc.  (And further to that, the undo didn't even work.) I'm currently too much of a newbie to properly fix this, but I did try... I think if I could change the text field to a dropdown menu which lists all the other animations in the AnimationPlayer, that would solve it. )

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch @adolson?

**Comment by vnen** [comment]
Confirmed in the current master.
