### ISSUE TITLE
Any text in the UI editor goes blurry after zooming

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#14807]
**Godot version:**
https://github.com/godotengine/godot/commit/8d13753e9171e2f525d7778b24a911bf60346aa2 Experiencing this since almost a year of 3.0 now though

**OS/device including version:**
Windows 10.0.15063 (also experienced this earlier)
AMD Radeon R9 390 with current drivers (also experienced this with older versions)

**Issue description:**
Not sure if such issue already exists. Am I the only one having this?
When starting a fresh installation / deleting the editor settings configuration file, all text in the UI editor is readable.
![image](https://user-images.githubusercontent.com/9631152/34119162-777bb248-e421-11e7-929b-d0ec11a266f9.png)

However, after zooming once and even after resetting zoom, the text becomes blurry.
![image](https://user-images.githubusercontent.com/9631152/34119179-8632a58a-e421-11e7-9812-2725d1a0b781.png)

It's actually not just the text, it's the whole UI (notice the borders of the panel).

**Steps to reproduce:**
Delete editor config, notice text is ~~nice and toasty~~ crisp and sharp, zoom once, blurry blurp.

Only fix is to delete the config file of the editor (not sure if it stores the current zoom somewhere, please tell me if you want sample configs).

**Comment by Calinou** [comment]
I can confirm this, look at the text at the bottom-left:

![godot_viewport_poor_font_rendering](https://user-images.githubusercontent.com/180032/34127925-29a66004-e43f-11e7-84ac-2a14d9325459.png)

**Comment by groud** [comment]
I wanted to fix it but cannot reproduce. :/
But it is probably due to how the zoom is calculated, ending up with a value like 0.99999.

**Comment by RayKoopa** [comment]
I guessed something like that, but I couldn't find the setting name in the configuration. How about a round it to the nearest .xx?

**Comment by groud** [comment]
We probably can use next_power_of_two() to get a round number. Anyway, I'll handle that when I have time :)

**Comment by vnen** [comment]
I can reproduce this easily in the script editor. Decreasing the zoom with Ctrl+Wheel one tick and then increasing one tick back makes it blurry. Pressing Ctrl+0 to reset the zoom makes it crispy again, even though the size itself does not change.

**Comment by RayKoopa** [comment]
Weirdly enough I don't have that in the script editor. And clicking the "1" button to reset the zoom or the corresponding menu item in the 3D editor doesn't help.

**Comment by vnen** [comment]
Nevermind me, I think I did one more tick with the wheel and it got to a lesser zoom, which looks bad. It's not a bug.
