### ISSUE TITLE
RigidBody2D custom_integrator seems to be broken

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#14803]
**Godot version:**
v3.0.beta.custom_build.9079be9

**OS/device including version:**
Ubuntu 17.04

After setting RigidBody2D `custom_integrator` to `true`, using `set_applied_forces` in `_integrate_forces` doesn't seem to be doing anything. See attached project.
[godot-dbg.zip](https://github.com/godotengine/godot/files/1568266/godot-dbg.zip)

**Comment by groud** [comment]
Probably a duplicate of #13418

**Comment by razvanc-r** [comment]
False alarm, my misunderstanding of docs. Closing
