### ISSUE TITLE
Can't delete cells from GridMap by Right Mouse Click, regression from alpha2

### ISSUE THREAD

**Issue by adtofaust** [godotengine/godot#14800]
**Godot version:**
Compiled on 18.12.2017: d9f7fa4 and Godot 3 beta1

**OS/device including version:**
Probably not OS and graphics related but in case: Linux Mint 18.3, GTX960M, proprietary driver: 384.90

**Issue description:**
Deleting cells by right mouse click doesn't work anymore. It is working in Godot 2.1.4 and Godot 3 alpha2.

**Steps to reproduce:**
Just create any MeshLibrary, load it in GridMap node and try to delete placed cells by right mouse click.

**Comment by akanewf** [comment]
not a bug...

> djrm committed Several improvements to GridMap. on Oct 30

i check the code in modules/gridmap/grid_map_editor_plugin.cpp line 573
```
else if (mb->get_shift()) {
        input_action = INPUT_ERASE;
        set_items.clear();
```
so , you can press `shift+right click` to deleting cells.

**Comment by akien-mga** [comment]
Indeed, Right Click is used to activate the freelook mode in the 3D viewport, so to avoid the conflict it's now Shift+Right Click to delete tiles in a GridMap.
