### ISSUE TITLE
Purge large files more often from SCons cache

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#14817]
~~It seems the current cache handler, once the cache is full, keeps purging smaller files more often that the largest ones, even when the later are not accessed as often. The problem appears to be that the largest files don't "decay" fast enough, and the cache quickly gets full of the largest build artifacts.~~

~~In the equations below, the variable names are changed to make it more readable, but I think the solution could be to make larger files decay faster in proportion to how big they are to the average build artifact size, changing like this:~~

~~`decay = size * exp(exponent_scale * (access_time - current_time))`~~

~~to this:~~

~~`decay = size * exp(exponent_scale * (access_time - current_time) * size / average_size)`~~

**Update:**

Files are now sorted by access time regardless of its size, so the most recently accessed build artifacts are kept in the cache, it seems to work better that way.

**Comment by bojidar-bg** [comment]
Can this be closed now?
