### ISSUE TITLE
Panel node theming inconsistency

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#14813]
**Godot version:**
master: d81bd96

**Issue description:**
The Panel nodes have very different looks when they probably should look similar. Here they are, respectively: **Panel**, **PanelContainer**, and **PopupPanel**.
![screenshot at 2017-12-18 19-50-37](https://user-images.githubusercontent.com/30739239/34130119-d18be3a0-e42d-11e7-889c-e4052612fbad.png)

I personally think they also should have the appearance of the **PopupPanel**.

**Comment by RayKoopa** [comment]
PopupPanel is used for menues, while the other two are used for containers on the UI. I don't think they should look the same. Panel seems to be more basic to simply group controls without any visual interference, while PanelContainer should purposefully separate a group of controls for others (also used by the TabContainer IIRC).

**Comment by YeldhamDev** [comment]
Yep, thinking again, they are fine the way they are. Closing it.
