### ISSUE TITLE
Editor help is broken

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#14811]
**Godot version:**
3.0 (d81bd965b)

**OS/device including version:**
Windows 10, 64-bits

**Issue description:**
The editor help font is wrong in the list of items. The method description section disappeared. Seems like a recent issue, only noticed it yesterday.

![godot_2017-12-18_19-14-53](https://user-images.githubusercontent.com/5599796/34128582-51cb08da-e428-11e7-978f-343c1f379f7a.png)
![godot_2017-12-18_19-16-03](https://user-images.githubusercontent.com/5599796/34128583-53c33ef0-e428-11e7-9623-1af832b710d2.png)

**Steps to reproduce:**
* Open the help page for some class.

**Comment by akien-mga** [comment]
CC @poke1024, sounds like a regression from #14692.

**Comment by akien-mga** [comment]
Fixed by #14814.
