### ISSUE TITLE
Selections are not stored in the text operations for Undo

### ISSUE THREAD

**Issue by MattUV** [godotengine/godot#14835]
**Godot version:**
2.1.4, 3.0 current master a714e1a

**OS/device including version:**
Windows 8.1

**Issue description:**
 - In the script editor, or a the `TextEdit` node, when you undo text editing, the cursor moves where it was at that time, but not the selection.
<img src="https://user-images.githubusercontent.com/13215043/34169800-e1b670fe-e4e8-11e7-995a-47701d8fe077.png" width=250>

 - If you undo while text is selected somewhere else, the selection remains.
<img src="https://user-images.githubusercontent.com/13215043/34170440-25fd87dc-e4eb-11e7-86ef-937755548a4d.png" width=250>

 - If the selected text moves when undoing, the selection will keep its global position, and thus, will not keep the same words selected.
(Fixing that will fix the last issues in #14559)
![undo3](https://user-images.githubusercontent.com/13215043/34170713-3d177bd4-e4ec-11e7-8cb2-37dafcf8302d.png)

**Comment by zqyoung1** [comment]
Is this topic still open? If it is I'd like to work on it.

I'm a novice contributer to godot so if this is a problem please let me know!
