### ISSUE TITLE
Provide a way to load resources/images from bytes easily.

### ISSUE THREAD

**Issue by PJB3005** [godotengine/godot#14839]
Right now, the only way to load resources (that I can see) is either from disk, or hoping that the specific resource you want to load provides an API to load it without a direct disk file.

I'm in a situation where I'm loading assets from a zip file, and I'd like to avoid having to do any disk writes to temporary files just to be able to run `ResourceLoader` on the temporary file path.

My issue specifically *right now* is with PNG images, but I'm not seeing any ways to load say models or audio files directly (though I might've not dug deeply enough). Because of this I put resources/images in the title.

I did take a look at the way the resource loader works, and AFAICT making this a generic thing in the resource loader itself seems infeasible, so should each resource type provide APIs taking in a byte array of bytes that could have raw file data?

**Comment by reduz** [comment]
problem is that images and audio files are imported, so you can't really
open a png or wav.

That said, it should be relatively easy to add a method in Image or
AudioStreamSample to load from a buffer, should that be enough?

On Tue, Dec 19, 2017 at 5:42 PM, Pieter-Jan Briers <notifications@github.com

**Comment by PJB3005** [comment]
Yeah I already figured it probably wouldn't be possible to load say a `StreamTexture` from a `.png` directly, but being able to load an `Image` and then make an `ImageTexture` out of it would be great.

**Comment by PJB3005** [comment]
I've been looking into this more and discovered that Godot appears to have an internal system of loading zip files directly. I can find issues hinting that it's possible to load zips manually, but I can't find *where*. Is this maybe just not exposed to user code?

Either way, I think exposing an API for custom `PackSource`s would be a good way to handle this. Then you can "load" files directly from wherever without needing every resource loader to implement it.

**Comment by PJB3005** [comment]
I made an API to allow this by allowing you to load Pack Sources such that you can implement virtual file systems (and by extension pretend like files exist on disk). Haven't tested it well though.

https://github.com/space-wizards/godot/tree/18-04-28-file_access_script

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/732, as feature proposals are now tracked in the Godot proposals repository.
