### ISSUE TITLE
Strange rendering glitch (3d without effects)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#14837]
**Godot version:**
Last version from Github

**OS/device including version:**
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kabylake GT2) 
Ubuntu Linux 16.04 64 bit
Windows 10 Home 64 bit

**Issue description:**
When I run the FreeRoamRacer game by Zireael (https://github.com/Zireael07/FreeRoamRoguelikeRacerPrototype) with the mode "3d without effects" I get a weird render glitch (massive black horizontal artifacts). After one minute 90% of the screen is black.

**Minimal reproduction project:**
https://github.com/godotengine/godot/files/1587960/video.mp4.zip

**Comment by hpvb** [comment]
I can reproduce this on Fedora 27 native and wine with 7a10d3ab78975a95f55b1bf97705ff8cc300da08

It appears to have something to do with the day/night cycle thing

```
OpenGL renderer string: Radeon RX 580 Series (AMD POLARIS10 / DRM 3.23.0 / 4.15.0-rc4, LLVM 4.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.4
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```

**Comment by Zireael07** [comment]
Hint, day/night cycle involves the ProceduralSky as well as GI probe.

If you untick the day/night cycle on the node (there's a reason I exposed that bool to editor) and/or disable the gi probe, does it still occur?

**Comment by LinuxUserGD** [comment]
I've deleted the GI probe node and the day / night cycle script but the error still occurs.
It seems like it has something to do with the road materials / shaders. If I delete the road node, everything is fine.
The car node (including lights / text viewport) doesn't trigger the bug.

**Comment by Zireael07** [comment]
Road materials are simple textures and standard shader, so nothing fancy there.

**Comment by LinuxUserGD** [comment]
#8651 ?

**Comment by LinuxUserGD** [comment]
The glitch behaves different on Linux and Windows (Linux: horizontal flickering lines on ground, Windows: some black parts flickering on whole screen) - maybe I should record a video sometime

**Comment by Zireael07** [comment]
May be related although #8651 is for 2.1 and I'm not seeing #8651 on any of the 3.0 versions that I tried.

**Comment by LinuxUserGD** [comment]
[video.mp4.zip](https://github.com/godotengine/godot/files/1587960/video.mp4.zip)

First half: Linux
Second: Windows (low fps because of screen recorder problems)

**Comment by LinuxUserGD** [comment]
I also get this error with @Calinou 's Sponza demo and with the Material Demo. There is no issue if you enable MSAA.

**Comment by LinuxUserGD** [comment]
I can't reproduce it anymore.
