### ISSUE TITLE
Text editor color settings have no effect

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#14838]
**Godot 3.0 beta**

I set the color for comments in the script editor. But it changes nothing in reality.

![00](https://user-images.githubusercontent.com/11189223/34175864-a4f88b98-e51f-11e7-8014-b7a9a1be1b0c.png)

**Comment by vnen** [comment]
Does this happen if a theme other than Adaptive is selected?

**Comment by DimitriyPS** [comment]
I use Godot 3.0 by default. Color comments - is the only parameter I changed.

**Comment by vnen** [comment]
Then you are using the Adaptive theme, because it's the default. You can change it in the Theme section just above the Highligthing.

I've seen this, sometimes the colors are all different and don't respect the highlight color settings. Maybe @djrm has an idea of what's going on?

**Comment by djrm** [comment]
yeah the adaptive theme will override the settings, maybe modifiying a color should set to custom theme, like with the theme.
