### ISSUE TITLE
Godot 3 do not import PBM files (no .import file) for Click Masks

### ISSUE THREAD

**Issue by nylnook** [godotengine/godot#14830]
**Godot version:**
Archlinux 64b, Godot 3b1

**Issue description:**
TextureButtons Click Masks seem to be badly imported in Godot 3, and do not generate .import files in the project folder
This might  be the cause of #14828
See also #14700 for a sum-up in and a minimal project example

**Comment by reduz** [comment]
This is not a bug, and seems to be a duplicate of #14700, so closing

**Comment by nylnook** [comment]
As explained in #14828, we are speaking about PBM... @akien-mga asked me to separate feature proposal and bugs, which is why it is separated from #14700 ... please reopen !

**Comment by nylnook** [comment]
thanks @akien-mga ;)

**Comment by reduz** [comment]
PBM format is now gone, you can import an image as bitmap
