### ISSUE TITLE
[Spatial Editor] weird object selection when changing from VIEW_PERSPECTIVE to VIEW_ORTHOGONAL

### ISSUE THREAD

**Issue by carlosfvieira** [godotengine/godot#14836]
**Godot version:**

3ca06e1184e49abd300bce03db1bec0e559c0d03.

**OS/device including version:**

Debian 8.10

**Issue description:**

Weird object selection when changing from VIEW_PERSPECTIVE to VIEW_ORTHOGONAL

**Steps to reproduce:**
In Spatial editor (in perspective view), click on an object, to select it... change then to orthogonal view... after doing some action on the viewport, the selection tool is then fine rendered again.

(1) Select object in perspective view

![image](https://user-images.githubusercontent.com/8830610/34173918-fbf310ca-e4ee-11e7-8562-5747bfd466c4.png)

(2) After changing to orthogonal view

![image](https://user-images.githubusercontent.com/8830610/34173689-39faf4c4-e4ee-11e7-8076-31c377765daf.png)

**Comment by volzhs** [comment]
duplicated with #14619
