### ISSUE TITLE
Right click in TextEdit doesn't move the cursor

### ISSUE THREAD

**Issue by MattUV** [godotengine/godot#14832]
**Godot version:**
2.1.4, and 3.0 current master 8b01b2e

**OS/device including version:**
Windows 8.1

**Issue description:**
In a TextEdit node (and thus, In the script editor as well), if you make a right click, it will not move the cursor. It implies that (for example):
- If you selected some text, and right click somewhere else, the selection will remain and the context menu actions will apply to the selection;
 - If you right click somewhere to paste some text, it will not appear where you right-clicked, but where your cursor was before

You can obviously left click, and right click just after, but it is way less intuitive I think.

**Steps to reproduce:**
Open any script, or any text in a `TextEdit` node
1. Select some text, right click, copy it
2. Right click where you want to paste, and paste it
3. Nothing visible happened, because the text was pasted on the original selection
4. Right click somewhere else and paste
5. The text was pasted where the cursor was before.
![clicks](https://user-images.githubusercontent.com/13215043/34166770-10826d06-e4e0-11e7-9a2c-2ff01333c6b1.png)

**Discussion**
In some text editors (Notepad.exe on Windows for instance), The right click works as in Godot today
In many others (Notepad++, Chrome, Microsoft Word for instance), it works as I propose.
I think it is much more intuitive to move the cursor with the right click, but maybe you'd like to make this optional via the Editor settings, and/or the `TextEdit` properties?

**Comment by YeldhamDev** [comment]
Most software that I use (Firefox, Atom, etc) doesn't work like that, but I wouldn't mind this behaviour.
