### ISSUE TITLE
GRDB-Bridging.h: Failed to parse Mach-O: Reached end of file while looking for: uint32_t.

### ISSUE THREAD

**Issue by ameen96mk** [godotengine/godot#14831]
> 
GRDB-Bridging.h: Failed to parse Mach-O: Reached end of file while looking for: uint32_t.

I've this issue in my project when used (GRDB) in Xcode 9.2, Swift 4.
What's it mean and how can I solve it ??

**Comment by akien-mga** [comment]
Please edit your post and follow the issue template, there's so much information missing from this post that nothing can be done to help you.

What Godot version are you using? (Are you using Godot at all? I have no clue what GRDB-Bridging.h is, but it doesn't come from our sources). What are you doing? How to reproduce the issue?

**Comment by ameen96mk** [comment]
I'm using version 2.4.1

**Comment by ameen96mk** [comment]
How to check if I using Godot or not? @akien-mga

**Comment by akien-mga** [comment]
Again, please follow the issue template. It's proposed for a reason.

- **Godot version:** If thirdparty of self-compiled, specify the build date or commit hash.
- **OS/device including version:** If graphics related, specify also GPU model and drivers.
- **Issue description:** What happened, and what was expected.
- **Steps to reproduce:** How can we reproduce the issue?
- **Minimal reproduction project:** Optional but greatly speeds up debugging. You can drag and drop a zip archive to upload it.

**Comment by mhilbrunner** [comment]
Closing until we get more information, as this issue is quite old now.
