### ISSUE TITLE
StreamPeer.GetData should not return an object array

### ISSUE THREAD

**Issue by iggyvolz** [godotengine/godot#14844]
**Godot version:**
Beta 1

**OS/device including version:**
Windows 10

**Issue description:**
Currently, GetData returns an array of an error code then a byte array.  Since these are different types, it must treat them as an object array.  With implicit type casting in GDScript, this isn't much of an issue, but it requires annoying and unsafe typecasting in C#, like conn.GetData(1)[1] as byte[] - it is unclear why we are taking the second element of the array, and why this is cast to a byte array, which would require explanation every time we use the method.

There are a few ways this could be dealt with:

1. The traditional C# way (akin to [Stream.Read](https://msdn.microsoft.com/en-us/library/system.io.stream.read(v=vs.110).aspx)) - pass in a premade byte array, an offset (where in the byte array you want to start putting data), and a count (how many bytes you want), and it will fill the passed array with values from the stream and return the number of bytes actually passed.  (As a bonus to this - the StreamPeer class could actually extend the Stream class allowing code to use BinaryReader/Writer and StreamReader/Writer)
2. Return a byte array, but throw an exception if the error code is non-normal.  This eliminates the need for typecasting, but requires exception handling.  (ValueTuple was added in C# 7.0, which may be an issue).
3. Return a System.ValueTuple<int,byte[]> instead of object[].  This prevents typecasting while keeping it truer to the GDScript method. 

This will be a BC break with any of the solutions, unless a separate class or method name was made.

**Comment by neikeq** [comment]
We can't make the API of Godot Object derived types different between languages, so there isn't much that can be done. You can use other C# libraries if you prefer them though.

We are going to change the Array and PoolArray type in C# though. We were using `object[]` for now because I was focusing on other stuff, but we need a custom type because Array is mutable and reference counted.

**Comment by iggyvolz** [comment]
Should this be closed since it won't be changed?

If anyone's interested, I was able to simplify this in my project by adding a simple wrapper class (https://gist.github.com/iggyvolz/2b23b3bca2ed3d98f025bbff22a62df5) - used as GodotError.Assert<byte[]>(conn.GetData(1));
