### ISSUE TITLE
Seems like animation_started signal is broken

### ISSUE THREAD

**Issue by Krakean** [godotengine/godot#14843]
**Godot version:**
latest master

**Issue description:**
func _ready():
  AnimPlayer.connect("animation_started", self, "_on_animation_start")

func _on_animation_start(name):
	print(name)

This code should display animation that just started, right?
If yes, then its not working. What I do wrong? :-\\

**Comment by akien-mga** [comment]
Works fine here:
```
func _ready():
	$AnimationPlayer.connect("animation_started", self, "_on_anim_started")
	$AnimationPlayer.play("Anim1")

func _on_anim_started(name):
	print(name)  # Anim1
```
