### ISSUE TITLE
AnimationPlayer docs - no current_animation member variable, though it present in docs

### ISSUE THREAD

**Issue by Krakean** [godotengine/godot#14842]
**Godot version:**
latest master

**Issue description:**
http://docs.godotengine.org/en/latest/classes/class_animationplayer.html
Docs stated that there is "current_animation" member variable, but when you try to use it,
like get_node("Animation_Player").current_animation is shows you error:
https://i.imgur.com/9ZkNCtR.png

Is this field has been removed? Or renamed? How can I get current playing animation, to be able to pause current animation and play it from where it was paused?

**Comment by vnen** [comment]
What does the in-editor help says? The online docs are not always up to date for an unreleased version.

**Comment by Krakean** [comment]
@vnen 
Yep, my bad, in-editor help says there is no current_animation field. Then, problem solved. :)
