### ISSUE TITLE
Is it just me or is there something broken with NativeScript

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#14859]
I created a NativeScript like [this](https://i.stack.imgur.com/qbizL.png) (please click on the link to view the image).

After I created NativeScript, I get this [error](https://i.stack.imgur.com/fIgg8.png)

**Comment by Raj2032** [comment]
Hi @groud , I wanted to know was this a bug or something I did wrong? May I know did you add my issue to the 3.0 milestone?

**Comment by groud** [comment]
Well, if you did nothing more than adding the NativeScript and end-up with and error. Yes, this is a bug.
If the problem is on master (please fill in the issue template correctly next time), yes, it should be on 3.0's milestone.

**Comment by karroffel** [comment]
I don't know where the error line comes from, but just creating a NativeScript resource itself isn't enough and not supposed to work, so I guess the *bug* here is the error reporting.

**Comment by groud** [comment]
When you create an issue, you have this text: 

> **Godot version:**
>  If thirdparty of self-compiled, specify the build date or commit hash. 
> **OS/device including version:**
> If graphics related, specify also GPU model and drivers. 
> **Issue description:**
>  What happened, and what was expected. 
> **Steps to reproduce:**
> **Minimal reproduction project:**
>  Optional but greatly speeds up debugging. You can drag and drop a zip archive to upload it.

Please next time, fill-in the template, instead of removing it and write an incomplete message :)

> What else do I need in order to get the NativeScript resource working then?

This is not the place to ask for help about how to use the engine, but for raising engine bugs/ask for features. 
If the raised error prevent you from using the NatvieScript, tell us. Else the only bug here is that it seems to produce an error message for nothing.

**Comment by Raj2032** [comment]
Sorry mate I was not at all sure if it really was an issue, next time I
will keep that in mind :) Is this error message preventing me from
scripting, or am I still able to use it?

I understand that this place isn't for asking how to do something, but I
have tried asking in forums but I am not getting a satisfied answer so I
wanted to ask somebody who has more experience with this sort of stuff, may
I know what else do I need to do before I can use NativeScript and use C++?

**Comment by karroffel** [comment]
You can check [this](https://github.com/godotengine/godot-docs/pull/832) out, it's using C but it shows the basics.

**Comment by groud** [comment]
Read at least this : https://godotengine.org/article/dlscript-here
But Godot 3.0 is not out yet, a lot of stuff still need to be documented. You can find a PR about that here: https://github.com/godotengine/godot-docs/pull/832

Understand that the Github issues are not here to support people using the engine. Just asking "How do I make NativeScript work ?" is too vague, and here is not the place to ask such question. However, if you think a tutorial is missing, you make a feature request it in the godot-docs repository (its not needed here, a PR is already written).

>  Is this error message preventing me from scripting, or am I still able to use it?

It's up to you to tell us that. But, yeah, it does not seem like a problematic error, you should be able to use a NativeScript anyway.

**Comment by groud** [comment]
Sorry I might sound a little bit direct, but we have already a lot of work on the engine, we don't have a lot of time to help the engine users in there ^^

**Comment by Raj2032** [comment]
Why doesn't everything just come straight out of the box instead of making
users manually do additional tasks just to use C++?

**Comment by Raj2032** [comment]
I mean like why doesn't things just work straight out of the box? Should
this be considered an issue?

**Comment by groud** [comment]
See the comments in the other issue you opened. Setting up a C++ compilation environment is not Godot's purpose. This environment depends on the platform it's running on and thus should be set up by the user. You cannot have out-of-the-box C++ compilation.

**Comment by Raj2032** [comment]
I am so confused, why is it with GDScript and for C#, users can directly
create scripts in Godot and attach it to a game object, whereas we can't do
this using C++ directly?

**Comment by groud** [comment]
Because C++ compiles to native code, while C# and GDscript compile to byte code. While native code is meant to run on a specific hardware, byte code is interpreted by virtual machine (which may run on different hardware).

Thus C++ is faster, but needs to be set-up depending on the environment. While GDscript and C# are slower, but can run over several platform provided it has the adequate virtual machine. GDscript's virtual machine is directly implemented within godot's code, while C#'s is basically Mono.

**Comment by hpvb** [comment]
I guess we could ship GCC with Godot in a separate download (like there is godot-mono, there could be a godot-c++). It'd be a bit of a pain in the ass though.

**Comment by groud** [comment]
To be honest, shipping Godot with mono seems already a pain to me...

**Comment by Raj2032** [comment]
At least my suggestion is in the future builds of Godot, there should be an
addon in the Godot repository that sets everything up for the user without
having to go through complicated procedures.

**Comment by Raj2032** [comment]
In Unity it gives the option to install seperate things such as a third
party IDE, Android builds etc. I am sure Godot can do the same thing, Godot
already gives the user the option to use either the mono version or no mono
version, so why can't it do the same thing for C++ as well?

**Comment by reduz** [comment]
@Raj2032 C++ is not a simple language, and if you use it you are supposed to know what you are doing, or at least how to download a compiler.

If you are making a multi-platform game, you need to get plenty of toolchains and cross compilers that are several gigabytes big. bundling them is pointless. Even for a single OS you have plenty of choice for C++ compilers (MSVC, LLLVM, GCC). It's not only impossible for us to bundle them but also illegal.

I suggest if you are not familiar with this stuff, or don't intend to get more familiar with developing cross platform C++, to stay away from it.

**Comment by Raj2032** [comment]
How is it illegal to bundel them together as one package?

Unreal Engine allows users to use C++ straight out of the box (please do
correct me if I am wrong)?

**Comment by vnen** [comment]
> Unreal Engine allows users to use C++ straight out of the box (please do
correct me if I am wrong)?

You are wrong: Unreal asks the users to install Visual Studio (or another IDE): https://docs.unrealengine.com/latest/INT/Programming/Introduction/index.html

Also, Unreal engine is several gigabytes in size, while Godot is about 40 MB. And they ask you to download the C++ apart from that (Visual Studio is another huge package).

Seriously, if you want to use C++, which is not really an easy language, you should be able to install a compiler. Which is something you do only *once*.

> How is it illegal to bundel them together as one package?

Their licenses don't allow us to bundle with Godot.

----

Maybe we should add a warning on the NativeScript creation so beginners don't make one by mistake.

**Comment by karroffel** [comment]
C++ is not a first class GDNative citizen, because there are **none**. NativeScript wraps libraries - that's what it does.

For tighter integration with a specific language PluginScript should be used.
