### ISSUE TITLE
Menubar items keep the pressed state

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#14854]
**Godot version:**

Godot 3.0 master https://github.com/godotengine/godot/commit/b08735f20987a6188fd54c5e2dcd072dc316b413

**OS/device including version:**

Windows 10 x64

**Issue description:**

![https://i.imgur.com/VfUQY7m.gifv](https://i.imgur.com/VfUQY7m.gif)

**Comment by henriquelalves** [comment]
I can confirm this on master using Fedora; I tested with a local branch from two days ago, and this error isn't there - so I guess it's a commit made in-between.

**Comment by MattUV** [comment]
I compiled several previous version to find which commit introduced that issue
And the culprit is...... Commit 1eb1837 !

**Comment by MattUV** [comment]
The problem comes from lines 2373 to 2376 in scene/main/viewport.cpp from the commit.
