### ISSUE TITLE
Godot editor occasionally doesn't quit cleanly

### ISSUE THREAD

**Issue by hpvb** [godotengine/godot#14851]
**Godot version:**
7a10d3ab78975a95f55b1bf97705ff8cc300da08

**OS/device including version:**
Linux x86
Wine x86

**Issue description:**
Sometimes when quitting the editor it doesn't exit cleanly and instead the following message is scrolled infinitely:
```
ERROR: instance_set_use_lightmap: Condition ' !instance ' is true.
   At: servers/visual/visual_server_scene.cpp:660
ERROR: get: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
   At: core/rid.h:154
ERROR: instance_set_use_lightmap: Condition ' !instance ' is true.
   At: servers/visual/visual_server_scene.cpp:660
ERROR: get: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
   At: core/rid.h:154
```

**Steps to reproduce:**
It varies but it seems to happen a lot when I:
* Select a light node in the sponza scene
* Delete it
* Undo
* Quit the editor

**Minimal reproduction project:**
Not exactly 'minimal' but it seems to trigger this behavior relatively often:
https://tmm.cx/nextcloud/s/Log1eAXen1dJzBz/download?path=%2F&files=sponza.zip

**Comment by sersoong** [comment]
wine godot on linux?

**Comment by hpvb** [comment]
Yes, I tested both on Linux natively and wine.

**Comment by RayKoopa** [comment]
Having the same on Windows very rarely (at least if recall the exception correctly).

**Comment by Calinou** [comment]
I haven't seen this particular error message about lightmaps when closing the editor, so I'll close this. Please comment if you can still see *this* error message (not any others).
