### ISSUE TITLE
Selecting a node change editor to the editor where the node has a "physical" representation

### ISSUE THREAD

**Issue by artisticrender** [godotengine/godot#14862]
**Godot version:**
Godot Engine v3.0.beta.custom_build.1eb1837

**OS/device including version:**
Windows 10, build 1709

**Issue description:**
Whenever I select a node in the scene window the editor change to whatever editor where there is a representation of that node. For instance when I select a sprite node the editor change to the 2D editor. If I select a Position3D node the editor change to the 3D editor. Selecting a Tween doesn't change the editor probably because it doesn't have a representation in the 2D or 3D editor. This is very annoying if I am in the Script editor and want to see what properties are available in the Inspector and I constantly have to switch between editors.

Am I missing something? is there a way to prevent editor switching by all other means than selecting it at the top of the windows or by the f1, f2 and f3 buttons?

**Steps to reproduce:**
when in a new godot project inside the editor, hit the plus in the scene window, add a sprite node, go to script editor, select the sprite node in the scene window.

**Comment by lmjk** [comment]
Yep, this editor behaviour gets on the way very, very frequently. Another similar, and frequent case is that if you switch to another scene, just to have a look, the script editor opens a script from that scene and you have to navigate back to the script you were working on, again.

The problem could be solved by making a single click on a node in the scene tree to open it in the inspector only (and show it selected in the 2D/3D editor, *if* the editor is open). Maybe a double click on a node could then switch to the corresponding editor and center the view to it for easy finding. And when switching between scenes, update only the scene tree, and not the node/resource opened currently in the inspector, neither the script. Just change nothing else than the minimum. The nodes of the newly opened scene tree should be all unselected until clicked on.

**Comment by MaciejGorczycaGD** [comment]
Possible solution maybe could be to allow users to just select node with single click and double click would open appropriate editor if there is representation. 

This gets a lot in the way especially when you just need to look up some node property with open scrip editor.

**Comment by KoBeWi** [comment]
This not really a bug, but rather poor design. I wonder if we should just prevent switching viewports when in script editor.
Also, related issue: #33704

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/39539 which has more information about the issue at hand.
