### ISSUE TITLE
Crackling sound after a non-looped OGG file stops playing.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#14866]
**Godot version:**
3.0 build 0ead6b3.

**OS/device including version:**
Ubuntu Linux 17.10 64-bit. Pulseaudio.

**Issue description:**
I've noticed that a non-looped OGG file, when it stops, results in noticeable crackling sounds that carry on indefinitely.

**Minimal reproduction project:**
https://www.dropbox.com/s/prlc2t8kqqdjcol/14866_demonstrator.webm?dl=0 is a video of the issue.
https://www.dropbox.com/s/ag6wav8m6fbuunh/14866_demonstrator.7z?dl=0 is a project with the issue.

**Comment by akien-mga** [comment]
I can reproduce the issue in 3c7f06a0e on Mageia 6 64-bit (pulseaudio driver).

**Comment by Sslaxx** [comment]
Can anyone confirm this on Mac or Windows, or Linux not using Pulseaudio?
