### ISSUE TITLE
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#14864]
OpenGL ES 3.0 Renderer: GeForce GT 650M/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile

Windows 7-64 - Godot 3.0

ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:77
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:77

[3d.zip](https://github.com/godotengine/godot/files/1575561/3d.zip)

I tried some basic mesh in Godot3 3D and this error come out when I did reset camera's coordinates to 0 (zero)

You can replicate this error just loading basic example in attachment.

**Comment by varkatope** [comment]
I also got this error when setting the scale of a MeshInstance to zero on any of the axes.

**Comment by QbieShay** [comment]
@git2013vb can you try with this patch? https://github.com/godotengine/godot/pull/27090

**Comment by akien-mga** [comment]
Still reproducible in 3.1 and e40aea7.

**Comment by Anutrix** [comment]
Could it be related to https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/core/math/basis.cpp#L269?

**Comment by Anutrix** [comment]
@git2013vb AFAIK, Scale should never be 0 which it is in your case.
