### ISSUE TITLE
add view param to canvas_render_items

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#1486]
Submitting from IRC disucussion - hopefully this makes sense.  In talking about accessing the view and model matrices separately in shaders, reduz suggested that canvas_render_items could be given an additional parameter for view.

**Comment by reduz** [comment]
should do this...

**Comment by akien-mga** [comment]
Not sure what this all means, but I assume it hasn't been implemented yet.

**Comment by akien-mga** [comment]
@reduz What's the status on this topic?

**Comment by akien-mga** [comment]
Closing as stale and users haven't expressed a lot of interest in this feature over the years. It still seems like something that would be worth having, and @reduz agreed about it, but if it's not happening, it just collects dust in the issue tracker :)

Feel free to comment if you still think this would be a good addition, and/or if you want to work on implementing it.
