### ISSUE TITLE
ResourceLoader doesn't work with system paths

### ISSUE THREAD

**Issue by tmathews** [godotengine/godot#14879]
**Godot version:**
3.0 (e3fd61b63860cd82dee12bf77550c1a5cf1373f5)

**OS/device including version:**
Ubuntu 17.10

**Issue description:**
I'm currently using `image.load(path)` to load images from the users file system. I wanted to try loading any kind of resource using `ResourceLoader.load` and `ResourceLoader.load_interactive`, but both give me an error: `No loader found for resource: ...`

I'm not sure if this is intended, but I expected it to work since I could use `image.load` for the same path.

**Steps to reproduce:**
```
print(ResourceLoader.load("res://resource") != null) # Should be true
print(ResourceLoader.load("/path/to/resource") != null) # Should be true
```

**Comment by Ovnuniarchos** [comment]
It seems Godot has been rendered incapable of loading any resource that has not been previously imported.

**Comment by tmathews** [comment]
For now I ended up loading the data through the file API and then using load from jpg/png.

**Comment by ifig4fireghost** [comment]
How can to load .ogv file with user://xx.ogv ?

**Comment by tmathews** [comment]
@ifig4fireghost use webm format. I don't think any other video formats are supported.

**Comment by akien-mga** [comment]
> use webm format. I don't think any other video formats are supported.

Theora / OGV is supported.

**Comment by KoreTeknology** [comment]
same for audio files... doesnt want to load external data without previously re-imported from godot ui

**Comment by Jack-MoG** [comment]
I've done some testing with this, and it seems that it's impossible to load successfully unless the .import files are present. As far as I can tell, there isn't a way to do so through code.
This demo shows the issue with .obj files
[Godot load issue demo.zip](https://github.com/godotengine/godot/files/5147259/Godot.load.issue.demo.zip)

**Comment by ondesic** [comment]
This is a huge problem I am running into.  I have a program that relies on the user picking a wav or ogg file from a file dialogbox.  They then play it.  This will not work as I get errors saying a loader cannot be found for wav or ogg files.
The same code works perfectly if the audio file is in the res:// folder.  Looks like this has been a problem for a long time.  Can this be fixed?

**Comment by Calinou** [comment]
@ondesic There's a proposal about this already: https://github.com/godotengine/godot-proposals/issues/732

**Comment by ondesic** [comment]
@Calinou  The title mentions WAV.  We really could use a solution for wav and ogg.  Do you know what the progress on this is?

**Comment by Calinou** [comment]
@ondesic As far as I know, nobody started working on this feature yet.

**Comment by Calinou** [comment]
@ondesic In the meantime, you may want to look at this script: https://github.com/Gianclgar/GDScriptAudioImport

**Comment by spit4520** [comment]
Hey all,

I know this thread is a bit old, but I was wondering if there is a way to generate meshes from objects in run time. We are loading up a file picker and importing an object, we want to generate a mesh from the object (which also appears to need the MD5 hash and .import files also need to be generated)

We are trying to create something kind of dynamic like the settlement building in Fallout 4, but with your own objects

Thanks

Scott

**Comment by Calinou** [comment]
@spit4520 To load models in an exported project, you need to use an OBJ loader such as [this one](https://github.com/Ezcha/gd-obj).

**Comment by KoBeWi** [comment]
`load()` method in clarifies how to load non-imported Resources:
https://docs.godotengine.org/en/latest/classes/class_%40gdscript.html#class-gdscript-method-load

Loading Resources outside project works normally if they are not importable (e.g. GDScript, JSON). Closing.
