### ISSUE TITLE
"Curve-step" frame interpolating in AnimationPlayer not working in Polygon2D vertex colors

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#14873]
**Godot version:**
Godot 2.1.4

**OS/device including version:**
Win7

**Issue description:**
Is posible to smooth animate a Polygon2D UV and polygon vertex but animate vertex colors doesn´t smooth interpolate, only "discrete" animation allowed. If this is useful: is posible to smooth animate color property of entire polygon, but not in the vertex.

I will reference to original commit: #4765

**Steps to reproduce:**
Create a Polygon 2D, attach animation player, make polygon, add vertex color and try to smooth interpolate some colors.

**Minimal reproduction project:**

I don´t have a project now with this issue... I will try to make one and upload.

**Comment by Chaosus** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Comment by Ranoller** [comment]
It applies to master at 18/09/2018. This was not implemented.
![polygoncolor](https://user-images.githubusercontent.com/11712737/45655445-99c40080-bae0-11e8-8c80-e3a279abeb85.gif)
Gif is bad because colors, but i think that the main idea is understandable.

**Comment by akien-mga** [comment]
Could you upload that test project?

**Comment by Ranoller** [comment]
[PolygonVertexColorAnimation.zip](https://github.com/godotengine/godot/files/2393525/PolygonVertexColorAnimation.zip)

**Comment by mrcdk** [comment]
This PR https://github.com/godotengine/godot/pull/25934 should fix this issue.

**Comment by Ranoller** [comment]
Great, i can not compile this weekend, but looks great. If someone can test with the project in this thread this can be closed. Equally can be closed and if there is other bug with the commit other issue can be opened.

**Comment by akien-mga** [comment]
Fixed by #25934.
