### ISSUE TITLE
Is ClassDB not checking for Object inheritance correctly?

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#14872]
**Godot version:**
b3a1bf324566af58ceedc918c83396cba97aeedb

**Issue description:**
Noticed this when looking at the search results of the [help dialog](https://github.com/godotengine/godot/pull/14535#issuecomment-352458191) i was recently implementing :
![image](https://user-images.githubusercontent.com/9631152/34212032-3d1b87ce-e59b-11e7-9659-3d4646be4487.png)

Items are listed under the `Object` node to visualize they inherit from it. However, notice how some are missing the generic Object "package" icon most items have.

I use `DocData::ClassDoc::inherits` to build the inheritance hierarchy, but `ClassDB::is_parent_class()` to quickly check if a type inherits from `Object` for the icon.

```cpp
if (p_match.doc->inherits != "") {
	if (class_items.has(p_match.doc->inherits)) {
		parent = class_items[p_match.doc->inherits];
	} else {
		ClassMatch &base_match = matches[p_match.doc->inherits];
		parent = _create_class_hierarchy(base_match);
	}
}
```

```cpp
if (ui_service->has_icon(p_doc->name, "EditorIcons"))
	icon = ui_service->get_icon(p_doc->name, "EditorIcons");
else if (ClassDB::is_parent_class(p_doc->name, "Object"))
	icon = ui_service->get_icon("Object", "EditorIcons");
```

This can also be seen when opening the documentation page in the help, so it doesn't seem to be a bug in my hierarchy code (phew!):
![image](https://user-images.githubusercontent.com/9631152/34212423-8808ef14-e59c-11e7-9f5c-36b53cc539d0.png)

Apparently there is some inconsistency here. Checking the source code for all affected classes with the "wrong" icon, I saw that all indeed inherit from Object in the end, but their name is prefixed with `_` - not sure what is expressed with that.

Why is `ClassDB` not reporting the Object inheritance, how could I check "correctly" for it otherwise, is this a bug?

**Comment by poke1024** [comment]
There is indeed a mismatch.

`ResourceLoader` does not derive from `Object` has no `GDCLASS` declaration, and thus it falls back on the default parent class info method, which is:

```
static String get_parent_class_static() { return String(); }
```

i.e. no parent.

At the same time, in `ResourceLoader.xml` the class is documented as deriving from `Object`: 

```
<class name="ResourceLoader" inherits="Object" category="Core" version="3.0-beta">
```

The problematic code is the following inside `DocData::_load(Ref<XMLParser> parser)`:

```
		if (parser->has_attribute("inherits"))
			c.inherits = parser->get_attribute_value("inherits");
```

It overwrites `c.inherits` with the wrong info from `ResourceLoader.xml`.

Now, we could fix the problem in the code, or fix the `.xml` docs to not state `inherits="Object" `.

**Comment by akien-mga** [comment]
> Now, we could fix the problem in the code, or fix the .xml docs to not state inherits="Object".

That's derived automatically from the API by `godot --doctool .`, so if it's incorrect it needs to be fixed in the doc extractor/bindings of ResourceLoader.

**Comment by DualMatrix** [comment]
Still relevant in master

**Comment by ptrojahn** [comment]
The problem here is that ResourceLoader doesn't exist in ClassDB, so ClassDB::is_parent_class can't find the parent. The class for ResourceLoader is _ResourceLoader. Seems to be to avoid conflicts with the internal ResourceLoader class in core. The underscore is removed in DocData::generate(), so the doc only has ResourceLoader. @akien-mga would it make sense to remove the underscore directly in the GDCLASS macro? This would keep the name in the docs consistent with the internal one and stop having checks for the underscore scattered all over the codebase.

**Comment by KoBeWi** [comment]
Still valid in bfc79a2
Also #26114 sounds related.

**Comment by YuriSizov** [comment]
Well, I don't know if it makes sense to put these classes in `Object` if they don't explicitly inherit it, but at least the icons are correct now in the docs. So closing?
