### ISSUE TITLE
Changing default editor on Godot 3 Beta before saving scene tries to reimport entire hardrive

### ISSUE THREAD

**Issue by serapth** [godotengine/godot#14871]
**Godot version:**
3.0 beta 1

**OS/device including version:**
Windows 10

**Issue description:**

Change the default editor in Editor settings, before saving a newly created scene, results in Godot attempting to re-import every single asset on machine

**Steps to reproduce:**
Create New Scene
Editor Settings->Default Editor->Visual Studio Code
Godot starts reimporting every single file on hard drive.

**Minimal reproduction project:**

**Comment by capnm** [comment]
By a similar issue #13995 godot once started to import my (linux) home directory.
It spreads in a short time many config files all over.

**Comment by akien-mga** [comment]
Is it still reproducible in 3.0 beta 2? That's a pretty bad issue, we need to make sure to fix it before 3.0 stable.

**Comment by capnm** [comment]
@akien-mga I don't want to test this one;) but subsequent import by some unexpected internal crash is IMO still generally an issue.

The manager should **in any case** refuse to initialize a non-empty folder or open a folder without the `project.godot` file. See also https://github.com/godotengine/godot/issues/14943#issuecomment-353671325

**Comment by reduz** [comment]
Testing on linux, cant reproduce (using another external editor)..

**Comment by akien-mga** [comment]
I also can't reproduce it on Linux, and I don't understand how this could happen following the steps written above. Didn't you create a project directly in your user folder and it started importing all files in subfolders? That would be the most likely explanation.

At any rate, without additional details on how this could happen, there's not much we can do for 3.0.

**Comment by akien-mga** [comment]
Sadly can't do anything without more details. Some changes have been done since to prevent initializing a project in a non-empty folder, so it might have been fixed.
