### ISSUE TITLE
Can't Compile with MinGW on Windows

### ISSUE THREAD

**Issue by Athomield** [godotengine/godot#14877]
**Godot version:**
3.0 daily build (2 or 3 days old)

**OS/device including version:**
Windows 10

**Issue description:**

This is not a bug, but rather a feature request.
I have been trying to compile Godot on Windows for the past couple of days and It made me wonder why is MSVC the compiler recommended in the documentation, it's just a pain. The whole documentation  relies on using a GNU compiler except for compiling for windows. I don't know enough Sconstruct to tinker with the build settings and I can't compiler it on a regular cmd with MinGW, as it gives the error.

`PS (path)\Godot\godot-master> scons platform=windows
scons: Reading SConscript files ...
MSVC not detected (no VCINSTALLDIR environment variable), attempting MinGW.
No valid target platform selected.
The following were detected:

Please run scons again with argument: platform=<string>
NameError: name 'env' is not defined:
  File "(path)\Godot\godot-master\SConstruct", line 501:
    show_progress = env['progress']
PS (path)\Godot\godot-master>
`
(I replaced a string with (path) for privacy)

**Comment by mhilbrunner** [comment]
By the way, you need to select a target platform. For Windows, it would be `scons platform=windows`.
