### ISSUE TITLE
WindowDialog can't be resized diagonally

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#14880]
**Godot version:**
master:  03823f1

**Issue description:**
The WindowDialog and anything that inherits from it don't seem to be able to be resized diagonally, only horizontally and vertically.

**Comment by RayKoopa** [comment]
Can't reproduce on https://github.com/godotengine/godot/commit/c9d88fd8e8461cc1d5f83281e8d64ef10a5f02c6

**Comment by Noshyaar** [comment]
Not reproducible on Antergos x86_64, c9d88fd

**Comment by YeldhamDev** [comment]
No, wait, I'm a fucking moron. It can be resized, but I wasn't able to click in the correct spot because the cursor doesn't change to reflect that. Likely related to https://github.com/godotengine/godot/issues/14878.

Closing it.

**Comment by RayKoopa** [comment]
I still wonder why the cursor itself affects the hit test which doesn't care about the actual cursor, just the coordinates.

**Comment by YeldhamDev** [comment]
No, no. It detected it just fine, I just have the precision of a mole. :v
