### ISSUE TITLE
Opening Project/Editor Settings or clicking Classes/Search Help crashes the editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#14886]
**Godot version:**
master: 0b1e6ec

**OS/device including version:**
Ubuntu 17.10

**Issue description:**
There is not much else to say, it doesn't even outputs anything in the terminal, it just closes.

**Comment by Noshyaar** [comment]
Not reproducible on Antergos x86_64 c9d88fd

**Comment by vnen** [comment]
So it's either feef500b391b492959b2db3a7699ad14c6a37892 or #14874.

**Comment by Noshyaar** [comment]
Definitely feef500 according to the backtrace:
```
#16 0x0000000002990eec in Object::call_multilevel (this=0x825b270, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:853
#17 0x0000000001e633c7 in Viewport::_gui_show_modal (this=0x5334020, p_control=0x91a5040) at scene/main/viewport.cpp:2380
```

**Comment by chongdashu** [comment]
Seems to be affecting Windows, too on same commit: 0b1e6ec

**Comment by LinuxUserGD** [comment]
And the editor crashes when I create a new node (maybe the popups don't work?). Ubuntu Linux 16.04
@chongdashu

**Comment by chongdashu** [comment]
@LinuxUserGD  - is that happening for any new node at all?

**Comment by LinuxUserGD** [comment]
It happens when I click the + button

**Comment by LinuxUserGD** [comment]
Now it works.
The issue can be closed.

**Comment by volzhs** [comment]
I can confirm it's fixed.
