### ISSUE TITLE
Bugs when clicking "Play Scene" buttons 

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#14889]
**Godot version:**
Godot 3.0 8297ea9

**OS/device including version:**
Linux Mint Cinnamon 18.3 Sylvia x64

**Issue description:**
Clicking on any of the "Play Scene" buttons on the top-right of the editor causes two instances of the game to spawn, and causes any subsequent clicks on the editor to do nothing. Running the project/scene with F5/F6 works fine.

I'm pretty certain it's related to #14886, an issue caused by commit feef500.

**Comment by bearman92** [comment]
Same issue on Windows 8. Also had error when trying to debug on android device by the "android" button. 
![Crash](https://user-images.githubusercontent.com/5793188/34254712-75877a14-e677-11e7-9f32-e4a6915de217.png)
![Callstack](https://github.com/godotengine/godot/files/1579056/callstack.txt)

**Comment by LinuxUserGD** [comment]
Fixed (https://github.com/godotengine/godot/commit/1fa9aac3e415f53a095e955c8a37000629d56dde).
This issue can be closed.
