### ISSUE TITLE
Why users can't directly use C++ in the IDE?

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#14898]
Why do users have to use an External IDE in order to use C++

If Godot's IDE supports C#, why can't it support C++ as well?

**Comment by reduz** [comment]
Seriously, you could gather a bit more information before asking these things. Godot's built-in editor is only for GDScript. C# is meant to be used with an external editor, just like C++. 

There are great IDEs around for editing C++ or C# , which are complex languages and require large teams to develop tools for.

**Comment by Raj2032** [comment]
Yeah and I am trying to suggest to allow Godot's built in IDE to support
C++ and C#

**Comment by reduz** [comment]
Why? It's a huge and enormous amount of work to make a C++ IDE, you need a large team for this and it would never be better than existing IDEs. There is no chance for this to ever happen..

**Comment by Hinsbart** [comment]
Well, it should be enough to make a c++ `PluginScript` to enable c++ editing in the script editor.

**Comment by Raj2032** [comment]
And would there be such a plugin that users can install as this would make
it more convenient?

**Comment by Calinou** [comment]
> And would there be such a plugin that users can install as this would make it more convenient?

It would only provide syntax highlighting and not much else, so you would still be better off using a C++ IDE.

**Comment by Hinsbart** [comment]
Sure for code editing, using a dedicated c++ ide would still be prefered.

But a pluginscript would provide a bit more than just highlighting, for example handling compilation, adding cpp files, not needing to fiddle around with GDNativeLibrary's/NativeScripts, etc...
So if someone were to make such a plugin, I'd be super grateful :)

**Comment by Raj2032** [comment]
Why not make a pluginscript that makes the Godot's IDE very well supported
for C++, as Andreas has suggested?

**Comment by vnen** [comment]
> Why not...

It takes time to do stuff, it's not a matter of flipping a switch. Sure, some contributor can take this and decide to make something, but we can't force people to do that. And it's not a priority, so even if it goes to the official roadmap, it might take a while to be available.

As @reduz usually says (quoting Gandhi): "Be the change you want to see in the world."
