### ISSUE TITLE
Autotile properties missing

### ISSUE THREAD

**Issue by NullNeska** [godotengine/godot#14890]
**Godot version:**
0ead6b3

**OS/device including version:**
Windows 10

**Issue description:**
Autotile properties missing.

**Steps to reproduce:**
Make a tileset, set it to autotile

**Minimal reproduction project:**
![aaaaaa](https://user-images.githubusercontent.com/6185415/34240237-89934bf2-e5da-11e7-9025-a1ed903add38.png)

**Comment by damarindra** [comment]
Confirmed, also happen to me. Beta 1 still fine, beta 2 and master branch got this problem

**Comment by CyanBlob** [comment]
I can confirm this happening on Beta 2 as well. Opening the project in an older build, changing the settings, then opening in Beta 2 works as a temporary workaround.

**Comment by MarianoGnu** [comment]
take a look to `_get_property_list`, `_get` and `_set` functions of the class AutotileHelper on tile_set_editor_plugin.* files, these class and functions are responsible from populating the property editor

**Comment by damarindra** [comment]
@MarianoGnu I just change the `property_editor->call_deferred("edit", helper);` to `property_editor->edit(helper);` and it works fine. Dunno if this the right fix. It seems, edit function never called when using `call_deferred`.

**Comment by MarianoGnu** [comment]
Maybe the the edit function binding on property editor was renamed or removed, or the queue never got called for some reason, don't worry, this will work fine.
