### ISSUE TITLE
Builtin variables are not useable in shader functions

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14904]
Godot 3.0
Windows 10 64 bits
nVidia geforce 940M

I vaguely remember something about this, but I noticed that if you make a function in a shader, that function cannot access builtin variables such as `TIME`. Is this expected? If it is, I find it a bit annoying since such a variable can be expected to work as a global (unlike some others though, like output pixel color or output vertex).

**Comment by reduz** [comment]
Yes this is expected, as functions can be reused between vertex and
fragment shaders

**Comment by Zylann** [comment]
But does this make sense for `TIME`?

**Comment by reduz** [comment]
there is no code in the shader compiler to check that built-ins are global everywhere, TIME is probably the only exception

**Comment by Chaosus** [comment]
Yeah, TIME and VIEWPORT_SIZE should be accessed globally, at some point of development

**Comment by Zylann** [comment]
I just ran in this again, with `SCREEN_TEXTURE`, which should also be accessible from shader functions because I bet it's a hidden `uniform`.

**Comment by Chaosus** [comment]
@Zylann I've added TIME as global variable for custom functions (since its available everywhere) in https://github.com/godotengine/godot/pull/37166

**Comment by akien-mga** [comment]
Based on the discussion in #43150, it's not clear to me whether there's something left to implement for this, at least in the current state of the proposal. A more detailed proposal might be needed to review exactly which non-global builtins could make sense to expose as global, if any.
