### ISSUE TITLE
Binary resources aren't shown when searching for a tileset

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14901]
Godot 2.1.4
Windows 10 64 bits

I accidentally exported a tileset as a `.res`, which is the binary version of `.tres`. Not a big deal, however I noticed `.res` are not visible when trying to load such tileset on a tilemap:

[TileMapYSpanningTiles.zip](https://github.com/godotengine/godot/files/1579625/TileMapYSpanningTiles.zip)

![image](https://user-images.githubusercontent.com/1311555/34261655-32342652-e66a-11e7-840e-c9c43eec71dd.png)

**Comment by vnen** [comment]
Actually, this is a duplicate of #6678.
