### ISSUE TITLE
Can't type accented characters using dead keys with a Mac OS X keyboard

### ISSUE THREAD

**Issue by ricpelo** [godotengine/godot#1490]
Using Mac OS X Yosemite, Godot 1.0 and a Spanish keyboard, I'm unable to type "#" in the script editor, so I can't write comments in my code.

**Comment by okamstudio** [comment]
did you try the version in github? I think that was fixed there


On Sun, Mar 8, 2015 at 6:33 PM, Ricardo Pérez <notifications@github.com>
wrote:

> Using Mac OS X Yosemite, Godot 1.0 and a Spanish keyboard, I'm unable to
> type "#" in the script editor, so I can't write comments in my code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1490>.
>



-- 

*OkamStudio*

**Comment by ricpelo** [comment]
No, I didn't. I'll try to compile it myself later and I'll tell you. Thanks!

**Comment by ricpelo** [comment]
Hi again: I'd just compile the latest version (last commit from today), and it seems to works very good, I can type "#" and similar, but now I can't type accented keys, like áéíóú. If I press the accent key and then I type any vocal, that vocal appears without the accent.

Do you need more info in order to help debugging it? Thanks!

**Comment by reduz** [comment]
how does pressing accented keys work in your keyboard?

**Comment by ricpelo** [comment]
It's a standard Mac wireless Spanish keyboard. When I want to type an accented vocal (say, á), I first press the acute accent key, then I release it and finally type the "a" key.

I've tried with a standard PC USB Spanish keyboard, with the same results.

**Comment by akien-mga** [comment]
Can someone reproduce this issue on OSX?

**Comment by akien-mga** [comment]
Ping.

**Comment by bojidar-bg** [comment]
Pretty ping?

**Comment by akien-mga** [comment]
No answer and no duplicate, so closing as old.

**Comment by vnen** [comment]
Well, I think #4403 is a duplicate and recently updated, though this more broad.

**Comment by mirzakarlidag** [comment]
I'm using Turkish Q (Standard) layout with Gamepower Gasket Elite X keyboard. Control + Option + i worked for me. <">
