### ISSUE TITLE
scene/main/viewport.cpp line 2380 crash the editor when click most menu items

### ISSUE THREAD

**Issue by akanewf** [godotengine/godot#14905]
**Godot version:**

8297ea903a0568c715bdcd421382788174c7d14f

**OS/device including version:**

linux/osx

**Issue description:**

open top main menu or any menu in editor and click menu items made editor crash.

and i found:

reduz committed feef500b391b492959b2db3a7699ad14c6a37892

> "properly send mouse released event when grabbing modal focus"

scene/main/viewport.cpp:2380
`gui.mouse_focus->call_multilevel(SceneStringNames::get_singleton()->_gui_input, mb);`

```
Thread 1 "godot.x11.tools" received signal SIGSEGV, Segmentation fault.
0x00005555579cdd28 in Variant::reference (this=<error reading variable: Cannot access memory at address 0x7fffff7fefc8>, 
    p_variant=<error reading variable: Cannot access memory at address 0x7fffff7fefc0>) at core/variant.cpp:904
904	void Variant::reference(const Variant &p_variant) {
(gdb) quit
```
this line crash editor when click most menu items.
comment out this line no crash anymore.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by volzhs** [comment]
I guess it's already fixed by 1fa9aac3e415f53a095e955c8a37000629d56dde
and duplicated #14886
