### ISSUE TITLE
Moving a folder doesn't remap any path, which breaks all related references

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14900]
Godot 2.1.4 and probably Godot 3.0
Windows 10 64 

Yet another variation of [can't find the initial issue] where Godot doesn't update `.tscn` resource references when they are moved from the file editor's file explorer:

In my project, almost all actor/prop has its own folder with resource, scene and eventually script. I just dragged several of these folders to organize my project, and I noticed it broke all references to them, which I had to fix one by one:

![image](https://user-images.githubusercontent.com/1311555/34259629-4fa563b0-e663-11e7-8c4e-a0e76b21c488.png)

(Damn I even made a mistake in the process, and remapped the wrong scene... now I have to change all the instances aaaaargh)

Then after fixing these, I opened the scene but some other resources were not loaded:

![image](https://user-images.githubusercontent.com/1311555/34259811-f59f4b00-e663-11e7-9636-80ff421833fe.png)

So again, opening the individual scenes one by one and fix them...

Fortunately, I'm alone and the game has only one small map for now, but I can imagine a process like this to be very off-putting when done by designers on a more advanced project (users like me coming from Unity used to take this for granted, even when done from outside the editor).

Isn't Godot supposed to remap these automatically when I do this?

Note: I also noticed that sometimes, when I do this, it LOOKS like it remaps correctly when scenes are open, but that's only because Godot has them loaded and doesn't use paths at this time (unless you save again, which recreates copies at old location). If you move folders while all scenes are closed (or after a fresh restart), you get this issue all the time.

**Comment by 11clock** [comment]
I have noticed this in Godot 3 as well.

**Comment by reduz** [comment]
I think someone fixed this in 3.0 recently

**Comment by BrahRah** [comment]
I'm using 3.0.4 and I just had the same problem when I moved the scenes in a different folder.

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by Zylann** [comment]
I tried to reproduce it and Godot just crashed (closed with no further ado).

**Comment by KoBeWi** [comment]
Since you can now properly move directories in the file system dock and it remaps resources correctly, this issue could be closed.

There are sometimes crashes when moving asset directories, but it's reported in other issues (like #28012).
