### ISSUE TITLE
Lighting changes when using manual lighting transform in shaders

### ISSUE THREAD

**Issue by Maujoe** [godotengine/godot#14911]
**Godot version:**
Godot 3 beta 1/ self compiled  (current master 21.12.17)

**OS/device including version:**
Windows 10/Linux 
Nvidia GTX 1060

**Issue description:**
When using custom shaders with manual vertex transform and there are lights in the scene, the lighting of the object changes and doesn't look right in comparison without the manual vertex transform (Depending on the view position/orientation).

**Steps to reproduce:**
Create an new custom shader and add the following code:
```
shader_type spatial;
render_mode skip_vertex_transform;

void vertex(){
	VERTEX = (MODELVIEW_MATRIX * vec4(VERTEX, 1.0)).xyz;
        //NORMAL = (MODELVIEW_MATRIX * vec4(VERTEX, 0.0)).xyz;
}
```

**Minimal reproduction project:**
[g3_light_test.zip](https://github.com/godotengine/godot/files/1580221/g3_light_test.zip)

**Comment by Ace-Dragon** [comment]
Is there a reason why you are not specifically making use of the ALBEDO parameter (which, at minimum, is what you need to get proper shading in an object using a script)?

**Comment by Maujoe** [comment]
I'm sorry, it seems like it was a repeating mistake of mine, I don't exaclty know where, but now I got it right, so the topic can be closed, sorry for this again.

 (@Ace-Dragon For the minimal reproduction I just have changed the vertex shader and compared it with the default shading (no Material)..)
