### ISSUE TITLE
Rect2 grow_margin does not work

### ISSUE THREAD

**Issue by groud** [godotengine/godot#14918]
**Godot version:**
Current master

**OS/device including version:**
Archlinux

**Issue description:**
The grow_margin function of Rect2 does not do anything.

**Steps to reproduce:**
Just add this script to a node :
```
func _ready():
	var toto = Rect2(0, 0, 10, 10)
	print(toto.grow_margin(MARGIN_LEFT, 10))
```
Which prints (0, 0, 10, 10) instead of (-10, 0, 20, 10)

**Comment by akien-mga** [comment]
From a quick glance the code looks correct, so not sure why it doesn't work: https://github.com/godotengine/godot/blob/master/core/math/math_2d.h#L339-L357

**Comment by groud** [comment]
Me neither. It does not work in cpp either btw. :/
But the grow function and the grow_individual one work.

**Comment by groud** [comment]
I'm testing by replacing line 353 by: 
`g = g.grow_individual(...)`
It might work as `g.grow_individual(...)` was called before, as the function seems not to modify the object itself but create a copy.

But it might mean that the `expand()` does not work too.
