### ISSUE TITLE
Game hangs during exit in a signal handling loop when using dynamic fonts (Regression from b08735f2)

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#14927]
**Godot version:**
Godot 3.0 3068ccc8e69aad68c860ce8688bdc6d41107be1b

**OS/device including version:**
macOS 10.12.6

**Issue description:**

During game exit at the very end it hangs forever. I always get these errors printed at exit (not related to this issue specifically):

``` 
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:99.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:99.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1988.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:417.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:69.
```

And it seems afterwards a list of DynamicFont objects gets destroyed, it fails at self_list.h:99, tries to print an error, but OS singleton is already destroyed. Seems to be caused by b08735f20987a6188fd54c5e2dcd072dc316b413

![stack_trace](https://user-images.githubusercontent.com/2417849/34285189-4532d316-e70a-11e7-8b5a-1a9ea90f6bd0.png)

**Steps to reproduce:**
Use multiple dynamic fonts and quit the game.

**Comment by endragor** [comment]
This issue implies that DynamicFont objects leak. They probably leaked even before b08735f20987a6188fd54c5e2dcd072dc316b413, but thanks to the code added there the leak now causes hanging during exit. The leak cause is probably the same as in the errors printed at exit, such as:
```
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:417.
```
Have those leaks been investigated?

**Comment by reduz** [comment]
I am trying to use multiple dynamic fonts in many buttons and I see no leaks so far, any test project would be welcome.

**Comment by endragor** [comment]
Can be reproduced for me on this project: [project.zip](https://github.com/godotengine/godot/files/1594294/project.zip)

When I run it with `godot --path .` and then close it I get these in the console:
```
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1988.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:417.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:69.
```
And then it hangs forever until I kill it.

**Comment by endragor** [comment]
[Removed comment with a sample that actually leaks :-P]

So maybe those are actually caused by game code. Editor currently prints this though:
```
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1988.
```
Doesn't imply that there is a problem specific to fonts though, could just be an editor bug. So I will investigate more and close if there is no bug.

**Comment by akien-mga** [comment]
So is the original issue still valid?

The latter warning about ObjectDB cleanup is likely unrelated, and though a relevant issue, it should likely be tracked in its own ticket.

**Comment by reduz** [comment]
I can't reproduce it myself so far

**Comment by endragor** [comment]
Investigated the leaks more, and most of those happened because of godot-nim and the game code problems. So far only #15591 seems to happen because of the engine code. godot-nim problems have been fixed.

So closing this one as there is no bug here.
