### ISSUE TITLE
Renaming get_current_animation_position to get_pos

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#14926]
**Godot version:**
Godot 3.0 Beta 2

**Issue description:**
_get_current_animation_position()_
Are you seriously?
I was waiting for the _compactness get_pos()_
_current_ and _animation_ they and so will be visible from the operated in front of the point

**Comment by Dillybob1992** [comment]
Am sorry, but what is the issue here?

**Comment by akien-mga** [comment]
First of all, I would suggest that you phrase your proposals in a more constructive manner. That's no "hellish syntax", that's a very personal opinion that you have on how the Godot API should be like, not a "bug". You could have phrase it "Renaming get_current_animation_position to get_pos" and left away the rant.

Now to the actual rant, Godot's API is always very descriptive. We changed get_pos to get_position in 3.0, and many other such changes as with autocompletion, characters are cheap, and we feel that clearer method names make for self-documenting code.

Regarding this specific method, I don't have a strong opinion. The name *has* to be different from `get_position` though, to prevent conflict with 2D and 3D node positions. And `AnimationPlayer.get_position()` doesn't make much sense, as it's the playback position of the currently playing `Animation` that you're retrieve (and that's a different object).

**Comment by Noshyaar** [comment]
I prefer keeping it `get_current_animation_position()` for these reasons:
- IMO it's not used often enough to justify renaming. Having descriptive method names would be better.
- I know exactly that you're talking about AnimationPlayer despite the suboptimal issue description.
