### ISSUE TITLE
Main menu buttons don't loose focus anymore

### ISSUE THREAD

**Issue by levrik** [godotengine/godot#14924]
**Godot version:**
3.0 Beta 2

**OS/device including version:**
Win 10

**Issue description:**
The blue focus on the main menu buttons stay instead of disappearing on unfocus.
Also it now requires a second click to open the next menu item while having another open (need to unfocus menu first).

Before (3.0 Beta 1):
![2017-12-22_00-37-32](https://user-images.githubusercontent.com/9491603/34279290-5765f356-e6b0-11e7-8551-26fc1a6b0a55.gif)

After (3.0 Beta 2):
![2017-12-22_00-40-03](https://user-images.githubusercontent.com/9491603/34279346-a9324e50-e6b0-11e7-9908-06afa2f51563.gif)

**Comment by akien-mga** [comment]
Thanks for the report. It's the same as #14854 which is fixed already in the master branch (but not in Beta 2, when I did the binaries the fix was not available yet).

**Comment by akien-mga** [comment]
Well I'll keep this open for a bit as I guess many users will want to report the same issue in the coming days, and GitHub makes it hard to find closed issues when searching for duplicates.

**Comment by levrik** [comment]
@akien-mga Sorry. Always forget about switching to the closed issues tab..
Maybe providing this link (https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) in the issue template would be an idea? It searches over open and closed issues.

**Comment by akien-mga** [comment]
>  Maybe providing this link (https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) in the issue template would be an idea? It searches over open and closed issues.

Oh that's a good idea, I'll do that.
