### ISSUE TITLE
Instancing a scene writes its properties with modified values instead of none

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14921]
Godot 2.1.4, not tested in 3.0

I added a property to one of my character scripts, and I noticed all instances of that character in the level now contain an override for that property (and not the others). This means if I change the value in the character scene it won't update in the level, I am now forced to revert all of them somehow to make this work...

Repro (aka how it happened to me):
1) Create scene `Character` with a root script
2) Have the script export a variable like `export apples = 42`
3) Save the scene
4) Create a scene `Level`
5) Instance `Character` into `Level` and save `Level`: notice the value of the `apples` property is not written in `Level`, which is expected because we didn't set an override value here. The value of the property must come from the `Character` scene.
6) Now, go back to the script and add `export bananas = 43`, then **save the script only** (or have no scenes open).
7) Go to `Level` scene and add another instance of `Character` into it
8) Save `Level` again: notice `bananas` is now written as an override value into `Level.tscn`, which is NOT expected (because we never wrote a value in the inspector for the instances). You'll also see it has no symbol to revert the value, and changing the value in the `Character` scene doesn't change it in `Level` unless you manually revert them all.

I believe the reason all this happened is because `Character.tscn` had no value written for `bananas` due to it being closed when I saved the script, or because the script was saved alone (or modified from outside Godot). Consequently, saving a scene with instances of `Character` made Godot think it had no base value to compare against, and assumed the current value was coming from the scene being saved. I guess checking the default value of that property would have prevented this.

**Comment by akien-mga** [comment]
Is this reproducible in the current master branch?

**Comment by Zylann** [comment]
Yes, the same steps get the same result.

**Comment by reduz** [comment]
closed via 6e5872b70
