### ISSUE TITLE
is the result of Vector2.angle_to_point correct?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#14937]
**Godot version:**

godot 2.1

**OS/device including version:**

**Issue description:**

the arguments pass to atan2 should be in order y, x.
Also please check other APIs call  atan2.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by DualMatrix** [comment]
Tested a bit, angle_to_point seems correct. And yes indeed the arguments of atan2 should be swapped, internally they already are y,x someone must've accidentally ordered them wrong.

**Comment by KoBeWi** [comment]
The above PR is merged, so is this issue fixed?

**Comment by akien-mga** [comment]
Indeed.
