### ISSUE TITLE
FileSystem Dock jumps to/from tree hierarchy

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#14931]
**Godot version:**
Godot_v3.0-beta2_x11.64

**Issue description:**
When the FileSystem dock is in the "small mode" (below half screen height) opening a folder by double clicking or right click->open, the folder but switches between the tree hierarchy and the folders + files view

**Steps to reproduce:**
 - Set the FileSystem dock in a column with some other dock, and resize it to < half screen height.
 - Double click (or right click -> open) any folder
 - Repeat above to see how the hierarchy layout changes every time

**Comment by volzhs** [comment]
it's fixed recently by #14912

**Comment by volzhs** [comment]
let's this remain open, like #14924.
there will be more people reporting this.

**Comment by Keetz** [comment]
@volzhs :smile: all right ;) Just thought it was trivial as it was opened after a fix already has been introduced
