### ISSUE TITLE
Error: AudioStreamPlaybackOGGVorbis::_mix_internal: Condition ' !active ' is true.

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#14930]
**Godot version:**
The latest 3.0  8d13753e9

**OS/device including version:**
Win 10

**Issue description:**
When ogg file finished to play, sometimes godot report assert error:
```
ERROR: AudioStreamPlaybackOGGVorbis::_mix_internal: Condition ' !active ' is true.
   At: modules\stb_vorbis\audio_stream_ogg_vorbis.cpp:41
``` 
https://github.com/godotengine/godot/blob/4e442b0648332dd70751c7a9ee739c7c2bf9dfb5/modules/stb_vorbis/audio_stream_ogg_vorbis.cpp#L41

![image](https://user-images.githubusercontent.com/3992195/34287546-6b8d8410-e71a-11e7-979d-532ca291ab07.png)

**Steps to reproduce:**
It can easily reproduced on short ogg files.

**Comment by akien-mga** [comment]
This should be fixed already, can you try a more recent commit or beta2?

**Comment by kosz78** [comment]
Yes it seems fixed in the latest build
