### ISSUE TITLE
Can ViewportContainer's size is smaller than Viewport

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#14933]
**Godot version:**
3.0 beta 2

**OS/device including version:**
All

**Issue description:**
I want render a part of viewport, but ViewportContainer can't resize smaller than Viewport node, so it will can render full viewport only.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
This is not a bug. Use `stretch` property if you want smaller container. Also see #19252
