### ISSUE TITLE
Vcomp140.dll dependency?

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#14935]
**Godot version:**

Godot 3 beta 2

**OS/device including version:**

win7 32 bit

**Issue description:**

Godot 3 beta 2 need vcomp140.dll to execute in windows 7 32 bit. Godot 3 beta 1 not. What was changed to need that dependency?

**Comment by groud** [comment]
This is for the OpenMP library. But what is your problem ? Is there an error message ?

**Comment by akien-mga** [comment]
If it's not provided out of the box on Windows, this is going to be a pain..

**Comment by Ranoller** [comment]
Yes, Godot doesn´t run until I manually put the library near the executable (I can´t install visual studio libraries in this computer). Question is: what changed between Godot3 beta 1 and 2 to this request? This library will be needed in the computer of the player or is only needed  the editor? If is only to compile binaries or something like this there is no problem, but if is needed in the computer of the player.... o my gosh!!! I will test templates and write here!

**Comment by groud** [comment]
Yes, it has been added between beta 1 and beta 2. But you should not have to install it I guess.

**Comment by akien-mga** [comment]
It should not be needed for export templates, but please report it if it is, that would be a bug.

**Comment by bruvzg** [comment]
Vcomp140.dll should be part of [Visual C++ Redistributable](https://www.microsoft.com/en-ca/download/details.aspx?id=48145).

AFAIK it is not possible to link OMP runtime statically (at least it is not supported by GCC and [Clang](http://lists.llvm.org/pipermail/openmp-dev/2016-January/001051.html))

**Comment by Ranoller** [comment]
I test export templates (win desktop 32 bit with an without debug): the file is requested if not found. After putting vcomp140.dll next to the executable, it executes, but does not load anything (debug end in ARVR: register interface: Native mobile... no scene or singleton are loaded)

**Comment by akien-mga** [comment]
> I test export templates (win desktop 32 bit with an without debug): the file is requested if not found.

Thanks for checking, I fixed that with bf4d398d4.

> After putting vcomp140.dll next to the executable, it executes, but does not load anything (debug end in ARVR: register interface: Native mobile... no scene or singleton are loaded)

That's probably a different issue. Do you have a project.godot file next to the binary? Otherwise the export template by itself doesn't do anything, it will just exit when it has nothing to run.

**Comment by Ranoller** [comment]
> That's probably a different issue. Do you have a project.godot file next to the binary?.

Yes, I had a project.godot near. I change directory and it works well (If vcomp140 is in directory).... I will try your fix later, I can´t compile godot templates here.

**Comment by vybr** [comment]
I can't open the engine because of this...

**Comment by Calinou** [comment]
From what I've seen in other software, this basically means we'll have to distribute Windows installers that bundle and execute the Visual C++ redistributable installer. Portable ZIP downloads will require the user to install the C++ redistributable beforehand (perhaps the installer could be included in the ZIP, but I'm not sure if the license allows it, and you'd still probably need administrator privileges to run it).

I don't think this affects MinGW builds, but this should also be checked.

**Comment by Ranoller** [comment]
You don't need administrator privileges if manualy copy the file in the godot folder.... But for instaling in program files or windows directory probably yes. I think that godot can distribute the file, other software includes that with an instaler (90% of steam games?). Godot doesn't need that instaler, can be bundled inside the zip and the executable find that. License must be studied.

**Comment by Ranoller** [comment]
But is necesary to note that there is no one file... You need the file for your platform (32 / 64 bit)

**Comment by bruvzg** [comment]
For Windows - MinGW link OpenMP statically.

For macOS - it is possible to use static OpenMP, but this require custom clang from macports/homebrew and building openmp runtime from source (both macports and homebrew only provide dynamic library).

**Comment by reduz** [comment]
Given the mess this is, me might just implement a custom thread scheduler
for the few tasks needed

**Comment by Ranoller** [comment]
https://github.com/godotengine/godot/commit/021f3c924be29cafe9d8d50bf00ecc6f13675e87 Should fix the issue.
