### ISSUE TITLE
Project manager path handling

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#14943]
**Godot version:**
Godot 3.0 master @ bf4d398

**Issue description:**
Both when selecting a new folder for creating a new project and when downloading/installing templates via the project manager, I often happen to forget that you don't select the path where the project folder is created, but have to create the folder and then select that. Worst case, this means I clutter my home folder with project files and it takes quite some time to start until I manage to kill Godot and remove the newly created files. Also, when opening a project, you have to select the `project.godot`, the folder doesn't work.

Suggestions for improvement:
- There should be a warning if the selected path is $HOME when creating a new project
- When downloading "SomeTemplate", default to creating a new folder under the selected path, e.g. "path/SomeTemplate" and placing the contents there; maybe change the behaviour for project creation to work like this, too - if not, at least make it very clear that the *contents* will be dumped into the folder you select
- When opening a project, and the path ends not with `project.godot`, see if it is a folder and check `path/project.godot`

**Comment by vnen** [comment]
When you create a project, it gives you a warning if the folder isn't empty:
![godot_2017-12-22_12-50-22](https://user-images.githubusercontent.com/5599796/34302134-c1b60c08-e716-11e7-9605-efc8b5dcf5a6.png)

It should give the same warning when downloading a project from the AssetLib.

**Comment by mhilbrunner** [comment]
The asset lib doesn't. You're correct for creating a project though, but I'd suggest expanding the warning by default. You have to click on the warning sign to see it by default, which is a little subtle. :)

![screenshot from 2017-12-22 15-59-02](https://user-images.githubusercontent.com/1654763/34302436-2a575540-e731-11e7-987b-da1bbcab023c.png)

**Comment by capnm** [comment]
I would delete the warning and just generally **do not allow to create a new project in a non-empty folder**. It's too dangerous because the godot3 import-o-matic feature fills in no time the entire fs with lots of garbage.

**Comment by vnen** [comment]
> I would delete the warning and just generally do not allow to create a new project in a non-empty folder. 

I'm not against that. Forbidding creating projects from the editor interface will avoid many troubles. If anyone really wants a project in a non-empty folder, it's as easy as creating an (empty) `project.godot` file and importing it in the editor.

**Comment by djrm** [comment]
the message visible by default was rejected by some people, originally i put it open by default.

**Comment by mhilbrunner** [comment]
Someone at least changed the colors and made the hints more obvious. Thanks, I'll close this for now.
