### ISSUE TITLE
Export Attribute not working in C#. Not showing any variables in Inspector.

### ISSUE THREAD

**Issue by Arskyle** [godotengine/godot#14947]
**Godot version:**
Latest Beta2 from the Website

**OS/device including version:**
Windows 10

**Issue description:**

**Steps to reproduce:**
See the image below. All I did was create a C# script in Godot and added it to a Sprite and when tried to use the Export Attribute(on both private and public variables and also recreated the Sprite and the Script), but it just doesn't work. ??  [ I haven't tried creating a new project and trying yet. Trying more things/alternatives. ]
![capture](https://user-images.githubusercontent.com/19930870/34304777-25b05854-e761-11e7-992c-e86f25e387d1.PNG)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues)
  for potential duplicates.

**Comment by mrcdk** [comment]
You need to build the project every time you add, remove or modify an export variable because they aren't seen by godot until the project is built.

**Comment by vnen** [comment]
I think this is a duplicate of #12518

**Comment by neikeq** [comment]
Yes, it's a duplicate. Note that I plan to make the editor build the project automatically. I just have other stuff to focus on first.

**Comment by Burnout156** [comment]
> You need to build the project every time you add, remove or modify an export variable because they aren't seen by godot until the project is built. This is a C# only issue.

thanks, I forgot this kkkkkkk

**Comment by SlimyFrog123** [comment]
> You need to build the project every time you add, remove or modify an export variable because they aren't seen by godot until the project is built. This is a C# only issue.

Thank you so much for this answer! Just got started with Godot Mono, and I had this problem, this fixed it! Thanks again!

**Comment by jcmonteiro** [comment]
For someone who happens to stumble upon this, the attributes will not show (and the script won't be applied at all) if the class name doesn't match the file name. This is easily overlooked, although it is briefly mentioned in the docs https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#example

**Comment by AThousandShips** [comment]
Please check the other issue that this is a duplicated of for context

**Comment by airtonix** [comment]
> For someone who happens to stumble upon this, the attributes will not show (and the script won't be applied at all) if the class name doesn't match the file name. This is easily overlooked, although it is briefly mentioned in the docs https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#example

This often gets overlooked. 

1. why is this even a thing? 
2. why doesn't the editor warn about this? 
   - It obviously knows there's a script attached
   - It should be able to work out that the script name isn't the same as the node name
   - why does it even matter?

**Comment by LJXLJXLJX** [comment]
I have met the same problem. There are both .NET 8.0 and 9.0 on my device. The Godot seemed tend to use the wrong 8.0 version. I remove all .NET Runtime and reinstall 9.0, it works.
