### ISSUE TITLE
Videos (used with VideoPlayer) not packaged in .pck of exported game

### ISSUE THREAD

**Issue by cyaoeu** [godotengine/godot#14954]
**Godot version:**

3.0b2

**OS/device including version:**

Win8, GTX1070

**Issue description:**

Videos used with VideoPlayer are not packaged in .pck of exported Windows game. Even with Export all and adding *.webm or *.ogv. This means that they don't play at all when you try to play the game outside of the project folder. 
Expected behavior is for videos to be packaged in the .pck so they play with just the .exe and the .pck. 

**Steps to reproduce:**
- Import a video to the project.
- Add a VideoPlayer node.
- Set the VideoPlayer node to play the video.
- Confirm that it plays when playing the project inside the Godot editor.
- Export the game outside of the project folder.
- Run the game. The video doesn't play.
- Move the game inside of the project folder. The video plays again.

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+)
  for potential duplicates.

**Comment by reduz** [comment]
you can for now add them manually as you describe. I am trying to see if we can move video decoding to GDNative for 3.1, so this may no longer be an issue then. I will kick for 3.1 and close when this happens.

**Comment by Sslaxx** [comment]
How would you envisage video decoding via GDNative to work?

**Comment by DimitriyPS** [comment]
There is an option to migrate this patch to 3.0.2?

**Comment by akien-mga** [comment]
> There is an option to migrate this patch to 3.0.2?

Well there's no patch yet. Once there's a fix, we can cherry-pick it for the stable branch, yes.

**Comment by akien-mga** [comment]
> I am trying to see if we can move video decoding to GDNative for 3.1, so this may no longer be an issue then.

That's not a solution for 3.0 (and we need one here), and there's no guarantee that this will happen for 3.1, so exporting videos *should* be fixed. It doesn't hurt to remove that code/move it to gdnative plugins later on.

**Comment by emilevdb** [comment]
Is there a workaround for this for HTML5 games?

**Comment by Calinou** [comment]
> Is there a workaround for this for HTML5 games?

As far as I know, video decoding is disabled in HTML5 games as it's too slow (the assembly code paths cannot be used in WebAssembly).

**Comment by eska014** [comment]
For HTML5, The WebM module is active, though I've never tested it. You'll have to use [`preloadFile()`](https://godot.readthedocs.io/en/3.0/getting_started/workflow/export/customizing_html5_shell.html#engine-preloadfile-file-path)  to load the `.webm` file before starting the game.
