### ISSUE TITLE
No output from Particles2d on Android

### ISSUE THREAD

**Issue by sionroberts** [godotengine/godot#14951]
**Godot version:**
Godot v3.0 beta x64 (pre-built version) (Can't test 3.0b2 due to #14928)

**OS/device including version:**
Windows 10 x64
Android 6.0 - Moto G 2nd gen GPU: Adreno 305 @450 MHz GPU

**Issue description:**
Adding "Scale Curve" to Particles2d -> ParticlesMaterial stop all output from particle node on Andriod

**Steps to reproduce:**
Add Particle2D node

Set the properties:
Process Material -> New ParticlesMaterial -> Edit

Scale: 10
Add new Scale Curve
Edit the curve. Move the final point down to 0 (or near there)

Appears fine when running on Windows. 
Export to Android. It does not appear.
Remove scale curve. It appears!

**Comment by akien-mga** [comment]
The GPU being an Adreno 3xx model, might be related to #12816.

**Comment by reduz** [comment]
This will be solved in 3.2 with the removal of the GLES3 renderer.

**Comment by reduz** [comment]
You can use CPUParticles to work around this problem in the meantime

**Comment by munirehmad** [comment]
@reduz there's no more an option to convert to CPU particles when you select Particles2DNode

Also there's no class in GDScript named CPUParticles2D

I am using v3.0.6.stable.official.8314054

Any ETA when Particles2D will work on Android, or option to use CPU Particles?

**Comment by Zireael07** [comment]
CPU Particles I believe are in master, not in 3.0.6 stable.

**Comment by munirehmad** [comment]
> CPU Particles I believe are in master, not in 3.0.6 stable.

Thank you, I'll try to build from master.

**Comment by akien-mga** [comment]
This should be fixed in 3.1 and 3.2 by using CPUParticles2D.
Adreno 3xx has too bad OpenGL ES 3.0 support, so you can't really use GPU-based Particles2D there.
