### ISSUE TITLE
gltf models not displaying

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#14966]
**Godot version:**
compiled today 23rd dec from github

**OS/device including version:**
linux manjaro amd rx580

**Issue description:**
Exported gltf and glb files with various settings and no mesh displays in the editor, but i can see the node and its position.
Then i put a cube in the scene, and the cube mesh is visible, but my model is still not.

Example attached:
[Structure-TrainStation-A.glb.zip](https://github.com/godotengine/godot/files/1583735/Structure-TrainStation-A.glb.zip)

**Comment by djrm** [comment]
sometimes models have a ridiculous scale, so they are invisble (either they are very tiny or very big)

**Comment by Gibbz** [comment]
I dont think its a matter of scale as the cube is about the same size as my object

**Comment by Gibbz** [comment]
Okay! Looks like ive made progress!

This exporter seems to work:
https://github.com/KhronosGroup/glTF-Blender-Exporter

While this one does not:
https://github.com/Kupoman/blendergltf

Both are gltf 2.0

**Comment by Gibbz** [comment]
ill close this as its likely an issue with the exporter and not godot.
Might be worth having a note of that on the website somewhere which version works.
