### ISSUE TITLE
Auto apply materials

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#14968]
I have a basic import script which applies a material from the material library to meshes that have a material, if they don't, then it applies a default material from the library. 
Currently us artist needs to apply the materials after they have imported the mesh into godot each time, which is a pain.

It would be good to have something automatic like this built in to Godot. 

I've linked the script to give a better idea of what it does.
https://github.com/bit-shift-io/trains-and-things/blob/master/Script/Import.gd

**Comment by Calinou** [comment]
> Currently us artist needs to apply the materials after they have imported the mesh into godot each time, which is a pain.

You can keep materials untouched when overwriting the 3D scene file by saving them to external resources, and making sure the "keep materials" option is enabled in the **Import** dock.

**Comment by kubecz3k** [comment]
Don't think there is need for such functionality. Like Calinou noted your symptoms seems to be similar to the ones from  #10147.

**Comment by Calinou** [comment]
This is already supported via the **Keep Materials** import option (which is enabled by default), closing.
