### ISSUE TITLE
Defining a uniform vec3 or mat2 before a uniform float causes the float to not change in shader.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#14962]
**Godot version:**
Godot 3.0 Beta 2

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When a uniform vec3, or a uniform mat2 is defined before a uniform float the uniform float will not change value. But if the vec3 or mat2 is defined after the float, it will work. I tried some others like vec4, vec2, and sampler3D, none of those had this problem with the float. I haven't tried all types being defined before and after all other types though, so maybe there are others that have this problem.

**Minimal reproduction project:**
This does not work:
```shader
shader_type spatial;

uniform vec3 test_vec;
uniform float test_float;

void fragment() {
	ALBEDO = vec3(test_float, 0, 0);
}
```

This does work:
```shader
shader_type spatial;

uniform float test_float;
uniform vec3 test_vec;

void fragment() {
	ALBEDO = vec3(test_float, 0, 0);
}
```

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+)
  for potential duplicates.

**Comment by binbitten** [comment]
Got it!
- Members of mat2 need to match the alignment of vec4.
- vec3 correctly matches the alignment of vec4, but a scalar can be packed at the end of the vec3 causing wrong offsets.

I'm thinking the easiest solution for vec3 would be renaming it vec4 when dumping to glsl code?

**Comment by binbitten** [comment]
vec3s are proving quite pesky. Some thoughts:
1. Insert an extra scalar uniform for padding. Apparently some compilers get this wrong. Ah, the woes.
2. Order all vec3s to the end of the uniform block. Then no scalars will take up that "extra" space. I can't see any major issues with this. Thoughts?

**Comment by reduz** [comment]
what you describe is already being done, so I'm not quite sure what may be going on

**Comment by binbitten** [comment]
I'll try to explain more clearly.

Say we have a vec3 immediately followed by a scalar. We're then expecting the memory to look like:
`x y z 0 s` - 16 bytes for the vec3 (x,y,z,0) and 4 bytes for the scalar (s).

Instead we end up with `x y z s 0`. The scalar will be put together with the vec3. Most drivers will do this, but some will not, AFAIK.

**Comment by reduz** [comment]
hmm technically in std140 it should work the same everywhere, and the float should not be aligned to the vec3, but maybe i got something wrong

**Comment by binbitten** [comment]
Well, it doesn't violate the rules. Did some testing by manually filling a buffer to confirm. The float does indeed get aligned to the vec3. As for the ambiguous behavior, it seems quite rare and caused by buggy old drivers.
