### ISSUE TITLE
Couldn't get project.godot in the project path

### ISSUE THREAD

**Issue by TutorialDoctor** [godotengine/godot#14963]
**Godot version:**
v3.0.beta.build2

**OS/device including version:**

macOS Sierra V 10.12.6
2.3 GHz Intel Core i7
NIVIDIA GeForece GT 750M 2048 MB
Intel Iris Pro 1536 MB

**Issue description:**
A project I created shows Unnamed Project as the name in the Project Manager. When I click Edit the Project Manager just blinks and it doesn't open. When I click Rename, it doesn't rename. In red it says "Couldn't get project.godot in the project path.

**Steps to reproduce:**
This happened when I manually changed the config/name in the project.godot file.

**Minimal reproduction project:**
[Platformer Test.zip](https://github.com/godotengine/godot/files/1583708/Platformer.Test.zip)

<img width="1440" alt="screen shot 2017-12-22 at 6 45 46 pm" src="https://user-images.githubusercontent.com/12942803/34315091-ad497146-e749-11e7-803b-42bb58f5d32a.png">

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+)
  for potential duplicates.

**Comment by akien-mga** [comment]
Looks like you changed the normal parser-friendly quotes (`"`) to typographic quotes (`“ ”`), so the format is invalid and it can't read it.

The error message it gives is misleading though, that should be fixed.

**Comment by TutorialDoctor** [comment]
Thank you. Yes, that was it. I edited it in TextEdit for MacOs and somehow it kept changing the parser-friendly quotes into typographic quotes. I edited in Atom and now it works.

**Comment by Jerome67000** [comment]
I tried to display a better error message when `project.godot` is here but has syntax problems. Not so easy to do that with clean code...I have a PR read for that but I'm not sure i'm doing that in the right way !
