### ISSUE TITLE
GDNativeLibrary can't save libs when using .tres format.

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#14979]
**Godot version:** 63658fecfc77
**OS/device including version:** Arch Linux

**Issue description:**
When saving a `GDNativeLibrary` as a `*.tres` file, the platform entries for the libs and dependencies won't get saved. It works fine with the `*.gdnlib` format.

.tres:
```
[gd_resource type="GDNativeLibrary" format=2]

[resource]

load_once = true
singleton = true
symbol_prefix = "godot_"
```

.gdnlib:
```
[general]

load_once=true
singleton=true
symbol_prefix="godot_"
_sections_unfolded=[ "Resource" ]

[entry]

X11.64="res://lib/libcppscript.so"

[dependencies]

X11.64=[  ]
```

**Comment by bfloch** [comment]
I saw it, too.
From the look of it only ".gdnlib" is supported to read and write:
https://github.com/godotengine/godot/blob/master/modules/gdnative/gdnative.cpp#L425

This might be by design. The real confusing part is that the resource save dialog offers to save a GDNative resource as .tres.

**Comment by karroffel** [comment]
I will look into how this can be prevented (disallowing .tres) or fixed (making .tres work)

**Comment by haxpor** [comment]
**FYI**: Happen the same on macOS 10.13

**Comment by reduz** [comment]
I see no reason to save these files from within the editor, but i guess adding support for that could be done

**Comment by karroffel** [comment]
Oh, it can't be saved as .tres anymore since 34cdcf5cd0b4ea087b62ecae71c2ac86e06220a9
