### ISSUE TITLE
Move Project Manager favorite icon back to center

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#14989]
**Godot version:**
Godot 3.0 9969c5c

**OS/device including version:**
Linux Mint 18.3 Cinnamon x64

**Issue description:**
This is pretty pedantic, but I may as well put it out there...

Back in 2.1 and probably earlier, the favorites icon next to each project in the Project Manager was centered vertically:
![image](https://user-images.githubusercontent.com/27100585/34322495-a1fbc56c-e87c-11e7-8894-746011594ceb.png)

Some number of months ago, when the new editor theme was applied for 3.0, the favorites icon lost the centering and became anchored to the top-left:
![image](https://user-images.githubusercontent.com/27100585/34322484-6d5221f8-e87c-11e7-9cc0-ab2f7917511f.png)

It doesn't seem like the change was intentional. This issue just proposes that the icon is made to be centered again.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by YeldhamDev** [comment]
I personally like that way, but that's just me.

**Comment by Zylann** [comment]
I prefer the centered one. Better "reachability" in terms of UX.

**Comment by akien-mga** [comment]
Fixed by #15230.
