### ISSUE TITLE
3D Viewport : unable to select Sprite3D

### ISSUE THREAD

**Issue by Nutriz** [godotengine/godot#14981]
**Godot version:**
Godot 3.0 beta 2

**OS/device including version:**
Windows 10

**Issue description:**
In the 3D Viewport I'm unable to select Sprite3D, by click or with box selection.

**Steps to reproduce:**
Add a Sprite3D and a texture to it (godot icon.png) and try to select it in the 3D Viewport.

ps: MeshInstance can be selected by click in the 3D Viewport but box selection isn't working.

**Comment by Arskyle** [comment]
I confirm the bug. And there is also that selection is fine for collision shapes and almost everything else, but sprite3D can't be selected.

**Comment by akien-mga** [comment]
Fixed by #19487.
