### ISSUE TITLE
HingeJoint not working

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#14994]
**Godot version:**
3.0 beta1, beta2

**Minimal reproduction project:**
[Bug join.zip](https://github.com/godotengine/godot/files/1584532/Bug.join.zip)

**Comment by icnikerazah** [comment]
also Generic6DOFJoint motor doesn't work in godot-physics.

**Comment by Hinsbart** [comment]
CC @AndreaCatania

**Comment by AndreaCatania** [comment]
Is this working in Bullet physics?

**Comment by DimaKiva** [comment]
> Is this working in Bullet physics?
No

**Comment by DimaKiva** [comment]
In RK2, there are such hints.
![2018-01-21 07-11-55](https://user-images.githubusercontent.com/11325733/35189448-7e19124a-fe42-11e7-83ce-c8422f84026e.png)
It turns out the jointer is working. And he used to work. Only collision boxing is needed.
Hinsbart, you can close the bug. Why did no one point to my mistake?

**Comment by AndreaCatania** [comment]
I didn't test your project yet, and I cannot know if all was setup correctly.

However you can close this bug since you are the writer of issue
