### ISSUE TITLE
Fragment Shader Builtin "SIDE" broken.

### ISSUE THREAD

**Issue by skyburchard** [godotengine/godot#14990]
**Godot version:**
Godot v3.0.beta.build2

**OS/device including version:**
MacOS 10.13.2 NVIDIA GeForce GT 750M 2 GB
Intel Iris Pro 1536 MB

Also on Windows 10 NVIDIA GeForce GTX 1060 (Godot v3.0.beta.build1)

**Issue description:**
Fragment Shader Builtin "SIDE" only returns a value of 1.0, making it impossible to detect the backside of a triangle.

**Steps to reproduce:**
Create a Sphere Mesh with a shader material. Stet the shader_style to spatial and the render_mode to "unshaded, cull_disabled". Use the following as the fragment:

void fragment() {
	if ( SIDE == 1.0 ) {
		ALBEDO = vec3(1.0, 0.0, 0.0);
	} else {
		ALBEDO = vec3(0.0, 1.0, 0.0);
	}
}

Both the inside and outside of the sphere is red. The inside should be green. I noticed in the raw shader code that came up in the command line that "SIDE" was set to return either -1.0 or 1.0 depending on whether the face was back or front facing. This does not seem to be coming though from the raw shader code.

**Minimal reproduction project:**
[SIDE_broken.zip](https://github.com/godotengine/godot/files/1584436/SIDE_broken.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+side) for potential duplicates.

**Comment by AlmightyScientist** [comment]
I'll try to fix it.
I can't figure out why they chose to do a weird 1.0 or -1.0 trick.
It should just be true (1.0) or false (0.0).

**Comment by skyburchard** [comment]
@AlmightyScientist Awesome!

**Comment by reduz** [comment]
Closing this, SIDE was removed as it was redundant to the FRONT_FACING constant.

**Comment by reduz** [comment]
right fix for your problem is to use
if (FRONT_FACING)
