### ISSUE TITLE
GIProbe Reflections in Orthographic Camera have Converging Lines ( preview and in game )

### ISSUE THREAD

**Issue by skyburchard** [godotengine/godot#14992]
**Godot version:**
Godot v3.0.beta.build2 

**OS/device including version:**
MacOS 10.13.2 NVIDIA GeForce GT 750M

**Issue description:**
GIProbe Reflections in orthographic camera have converging perspectival lines. Reflections in orthographic camera should have orthographic lines that do not converge. This is an issue in camera preview and in game.

**Steps to reproduce:**
Create a scene with walls that have a high roughness value. Create an object and put it in front of the reflective walls, preferable higher up than the camera. Create a InterpolatedCamera and change its Projection to Orthogonal. Make sure all Meshes have "Use In Baked Light" checked. Add a GIProbe to the scene and adjust the bounds. Bake the GI Probe. Look though the preview for the Orthographic camera or play the game. The reflections in the wall appear as if they are seen though a perspective camera while the rest of the scene is rendered through the orthogonal camera.

As a side note, giprobe reflections look correct through the editors ortho camera view ( the view that can be set in the upper left corner of the 3D view ).

**Minimal reproduction project:**
[giprobe_persp_ref_in ortho_cam.zip](https://github.com/godotengine/godot/files/1584456/giprobe_persp_ref_in.ortho_cam.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+orthogonal) for potential duplicates.

**Comment by Calinou** [comment]
@skyburchard Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
