### ISSUE TITLE
No way to create signals in C#.

### ISSUE THREAD

**Issue by AurumStein** [godotengine/godot#15004]
**Godot version:**
Godot 3.0 beta 2

**OS/device including version:**
Windows 10

**Issue description:**
No way to create a signal in C#.

I have searched alot and was unable to find a way to add signals from C# even came across SignalAwaiter but to no avail it seems that Godot C# currently doesn't has a way for adding signals from C# so I would like to request addition of the feature until then I will be using GDScript.
Although receiving works just fine.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by vnen** [comment]
Pretty sure you can call [`add_user_signal()`](http://docs.godotengine.org/en/latest/classes/class_object.html#class-object-add-user-signal) from C#, it should be available through the binding (it should be called `AddUserSignal`).

**Comment by Arskyle** [comment]
It's not that it's more like I can not create a Signal which will be visible through the inspector's Node tab.
Like in GDScript it was as simple as adding `signal my_signal` and then using `emit_signal()`.

**Comment by paulloz** [comment]
Would the right way to do this be a `Signal` class attribute which would behave like GDScript's `signal` (maybe cc @neikeq)?
```C#
[Signal("foo")]
[Signal("bar")]
public class MyCoolScript
{
    ...
}
```
I'd be interested in digging into this if it's OK.

**Comment by neikeq** [comment]
Not sure, wouldn't it look bad when there are many signals?

**Comment by paulloz** [comment]
I don't know if it'd be uglier than a bunch of `signal` lines in a GDScript :thinking: (and I guess, it's possible put every attributes in the same `[ ]`.  
But now that I think of it, it also lacks a way of defining arguments.

**Comment by neikeq** [comment]
Now that I think of it, it doesn't look bad. What about something like this?:

``` C#
[Signal(typeof(StoppedBeingCool))]
public class MyCoolScript
{
    delegate void StoppedBeingCool(string reason);
}
```

This way we can get the name and signature from the delegate.

**Comment by vnen** [comment]
I'm no expert in C#, but isn't possible to add the attribute to the delegate?

```c#
public class MyCoolScript
{
    [Signal]
    delegate void StoppedBeingCool(string reason);
}
```

**Comment by paulloz** [comment]
Yes adding the attribute to the delegate is possible (and less verbose, obviously).

**Comment by paulloz** [comment]
Just a quick heads up about this.  

My work branch is [here](https://github.com/paulloz/godot/tree/csharp-signal-attribute), basically works fine (but could go with some checks of my use of `TOOLS_ENABLED` someday).  

Would be nice to be able to emit signals with the delegate type instead of a String from C# though.
```C#
public class MyCoolScript
{
    [Signal]
    delegate void StoppedBeingCool(string reason);

    public void MakeUncool()
    {
        Emit(StoppedBeingCool, "You know why.");
    }
}
```

**Comment by neikeq** [comment]
@paulloz That sounds great, I will have a look later. What about `nameof(StoppedBeingCool)`?

**Comment by paulloz** [comment]
@neikeq `nameof(TheDelegate)` should work out of the box, no problem with this.

**Comment by BrandonClapp** [comment]
To create a custom signal, `Godot.Object.AddUserSignal` can be used to register the signal. Once registered, you can use `Godot.Object.EmitSignal` to emit the signal up the node tree.

You can then use `Godot.Object.Connect` to connect the signals to the appropriate event handler.

i.e.

**Child pseudo code:**
```csharp
using Godot.Object;

public class Gem 
{
    public override void _Ready()
    {
        AddUserSignal("gem_grabbed");
    }

    ...

    void PickedUp()
    {
        EmitSignal("gem_grabbed");
    }
}
```

**Parent pseudo code:**
```csharp
using Godot.Object;

public class Main
{
    int _score;
    PackedScene _gem = ResourceLoader.Load(@"res://Gem.tscn") as PackedScene;

    public override void _Ready()
    {
        var g = _gem.Instance();
        AddChild(g);
        g.Connect("gem_grabbed", this, nameof(GemGrabbed));
    }

    public void GemGrabbed()
    {
        _score += 10;
    }
}
```

**Comment by paulloz** [comment]
I certainly can add something like this if it feels needed. I personally don't think it is usefull though. 
 
But now that I think of the Signal names: should I do some PascalCase to snake_case translation?

**Comment by redxdev** [comment]
Automatic conversion to snake_case seems like a bad idea, or at least if there isn't a way to turn it off. In my opinion, having a way to override the name (as in my example above) or just writing your delegates as `delegate void snake_case()` would be better.

**Comment by AurumStein** [comment]
I too think that translation or conversion is not a good idea. And having the ability to override the name is I loved quite a bit while fiddling with CSTools.

**Comment by Galileo53** [comment]
Looks like this issue was solved in version 3.01 but I cannot find any information how it should be used correctly. Can anybody give me a short example for C# ?
Thanks

**Comment by neikeq** [comment]
@Galileo53 I think something like this:

``` C#
public class MyCoolScript
{
    [Signal]
    delegate void StoppedBeingCool(string reason);

    public void MakeUncool()
    {
        Emit("StoppedBeingCool", "You know why.");

        // or better (friendlier to refactoring tools)
        Emit(nameof(StoppedBeingCool), "You know why.");
    }
}
```

**Comment by paulloz** [comment]
It is `EmitSignal` I think, but yes.  
I should probably PR the documentation on this. Will do as soon as I have some time 🙂.

**Comment by AurumStein** [comment]
This should be more like it.

```
public class MyScript
{
    [Signal]
    delegate void StoppedAction(string whatHappened);
    [Signal]
    delegate void GivenChoices(string[] choices);

    public bool stopAction = false;

    public void Execute()
    {
        // IF action is action is stopped
        if (stopAction)
        {   
            EmitSignal(nameof(StoppedAction), "INVALID INFO");
        }
        else
        {
            //using other types works too
            string[] strar = new string[] {"YES", "NO"};
            EmitSignal(nameof(GivenChoices), strar);
        }
    }
}
```

**Comment by paulloz** [comment]
The documentation about this [has been updated](https://godot.readthedocs.io/en/latest/getting_started/scripting/c_sharp/c_sharp_features.html#signals).  

On another note @neikeq, I think #11956 is a duplicate from this one, no?

**Comment by Galileo53** [comment]
Thank you so much. It works now :-)

**Comment by neikeq** [comment]
@paulloz Yep, that's a duplicate.

**Comment by Galileo53** [comment]
With your help I finally have ported the "Dodge The Creeps" (= "Your First Game" from the Godot Docs) to C#. As far as I know, this is the first successful porting - there have been some guys around trying it but they failed. Possibly this was because of the missing [Signal] support.
I would like to share this code because it took me a lot of time to create and I feel that it is a good collection of examples and it may help others to save time. Sorry if this is off-topic here but since I'm pretty new with Godot, I have no idea how I can post the code or send it to someone or if anybody is interested at all.

**Comment by LaurentOngaro** [comment]
FYI, I've also ported this tutorial from GDScript to C# a few weeks ago
The source code can be found on gitlab 
https://gitlab.com/GodotCSCourses/DodgeTheCreeps

**Comment by Galileo53** [comment]
Sorry, I did not know this.
So of course there is no need for another port.

**Comment by LaurentOngaro** [comment]
No don't worry , that's not what I meant with my comment.
All jobs on Godot are good, specially on C#.
I also used another port to c# to created my code, because some informations can be hard to find in doc or support. 
So having a C# code to look at is really helpfull/

**Comment by paulloz** [comment]
If you stumble upon something that's missing or is inaccurate in the doc, feel free to report it on [godot-docs](https://github.com/godotengine/godot-docs) :grin:

**Comment by LaurentOngaro** [comment]
You're right ! Of course
