### ISSUE TITLE
Scene not loading in android

### ISSUE THREAD

**Issue by jitheeshsk** [godotengine/godot#1500]
Scene does not load on calling ResourceLoader.load(path) in android. Works fine in desktop

Error log is
/godot(2432): [1;31;40mERROR: goto_scene: [1;37;40mInvalid call. Unexisting function 'dict2inst' in base '_ResourceLoader'.
/godot(2432): [0;31;40m   At: res://global.gdc:16.[0;0;37m

**Comment by okamstudio** [comment]
you are probably using github compiled godot with stable export templates,
try compiling the export templates yourself (at least the ones you need)
and it will work


On Wed, Mar 11, 2015 at 9:28 AM, Jitheesh S Khan <notifications@github.com>
wrote:

> Scene does not load on calling ResourceLoader.load(path) in android. Works
> fine in desktop
>
> Error log is
> /godot(2432): [1;31;40mERROR: goto_scene: [1;37;40mInvalid call.
> Unexisting function 'dict2inst' in base '_ResourceLoader'.
> /godot(2432): [0;31;40m At: res://global.gdc:16.[0;0;37m
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1500>.
>



-- 

*OkamStudio*

**Comment by jitheeshsk** [comment]
Yes you are right.. thanks
