### ISSUE TITLE
NetworkedMultiplayerEnet create_server fails using 4096 max players.

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#15005]
**Godot version:**
3.0-beta-2

**Context:**
Before anything else, I know, 4096 sounds way too high. Allow me to explain.

I'm planning to use a godot-based server instance that I wish it could hold up from 5k up to 10k concurrent users. BUT, I'm NOT going to send 10k calls 60 times a second, since I'm not running _process or _physics_process.

Apocalyptic case scenario I have to make 10k calls over one second period. Think of this server as a chat application for example.

*I know this is not what NetworkedMultiplayerEnet was made for, but I'm just playing around with this.*

**Issue description:**

If you do `peer.create_server(PORT, 4095)` It works. But if you change to 4096 it says: 

> Supplied NetworkedNetworkPeer must be connecting or connected.

The error is generated in https://github.com/godotengine/godot/blob/master/scene/main/scene_tree.cpp#L1674

Is this a bug? Can it be fix/modified to allow 10k as max players?

**Comment by Zylann** [comment]
I guess you may modify it in engine by changing the C/C++ code, however that could cause issues because there has to be a reason for that limit. Maybe ENet optimizes message size by taking this limit into account.

**Comment by Faless** [comment]
@vicguedez it's an ENet limitiation, see https://github.com/lsalzman/enet/issues/41 , you can probably patch ENet to allow for more peers

**Comment by vicguedez** [comment]
Hey guys, thank you very much. I know nothing of C++ or ENet so will not touch anything, as I said it was just curiosity.
