### ISSUE TITLE
AnimationTreePlayer is invalid after deleting Node

### ISSUE THREAD

**Issue by MrJustreborn** [godotengine/godot#15000]
**Godot version:**
9969c5c6a1cc103fb7b23c279b7fde0d92a5599a

**OS/device including version:**
Manjaro Linux (64bit)

**Issue description:**
When you add a node to the AnimationTreePlayer and deleting it, the path becomes invalid.

**Steps to reproduce:**
Create a vaild path in AnimationTreePlayer
![bildschirmfoto_2017-12-24_08-32-26](https://user-images.githubusercontent.com/11594586/34325010-b54bf41c-e885-11e7-963c-dbc6acba7e48.png)

Add a new node
![bildschirmfoto_2017-12-24_08-32-45](https://user-images.githubusercontent.com/11594586/34325015-c7b4c674-e885-11e7-9c07-c9cf42128530.png)

Delete the node
Path becomes invalid
![bildschirmfoto_2017-12-24_08-33-01](https://user-images.githubusercontent.com/11594586/34325017-ca8105d4-e885-11e7-8ff6-074feb77f74e.png)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by AlmightyScientist** [comment]
I just noticed, thanks to you, CTRL-Z doesn't cancel Node insertion in AnimationTreePlayer.
