### ISSUE TITLE
AnimationTreePlayer- Blend2-3-4/blend slider is INT in Godot 2.1.4

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#15007]
**Godot version:**

Godot 2.1.4

**OS/device including version:**

Win7

**Issue description:**

I try to emulate this tutorial: https://www.youtube.com/watch?v=nCBcaStGSRM
(Made with godot 1?) and I find that the AnimationTreePlayer / Blend2-3-4 nodegraph in Godot 2.1.4. only allows to me to select one of the animations (in Blend2 the slider have 2 positions, in Blend3 three, etc...). I try this in Godot3 and the slider is FLOAT and allows you to select intermediate positions (I think that this is the task for this node). So, this can be a regression between godot 1 -2.

There is one fix for AnimationTreePlayer here #9749 , but is on master, not 2.1, I don´t know if is releated.

More test done: In godot 2.1 the behaviour is the expected. In godot 2.1.1 not. So the regression was between this versions.

**Comment by Ranoller** [comment]
I feel that the deleting :float total_weight; in this commit can be releated:
https://github.com/godotengine/godot/commit/d44e6ea26815548d251db2390e1e45d39c86babb

**Comment by akien-mga** [comment]
Fixed by 0fc4b04f5.
