### ISSUE TITLE
Critical delay in _process call after splash screen ends

### ISSUE THREAD

**Issue by realManix** [godotengine/godot#15014]
**Godot version:**
Godot 3.0 beta 2 mono

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
It seems that when the main scene is loaded when you first start the game, _ready on a node in that scene is called, followed by a single _process call before the splash screen ends. Then, after the splash screen ends _process gets called repeatedly but the initial call after the end of splash screen is delayed quite a bit, causing a "snap", when you code movement for the node in _process.
This might not seem like a huge problem, but in the game I'm creating in the main menu I have a camera that follows the player playing a flying animation and because of this issue right after the splash ends, for a fraction of a second camera is looking at the wrong place because _physics_process doesn't have the same problem and it moves the player while camera's _process is idle. Currently, I'm dealing with this particular problem in my game by moving the camera in _physics_process.

**Steps to reproduce:**
1. Create the main scene with the root node and a Sprite as the child. 
2. Add this script:

extends Sprite

func _process(delta):
    position = Vector2(100, position.y + 120 * delta)
    print("position: " + str(position) + "; delta: " + str(delta))

You will notice the "snap" in the sprite's movement right as the splash screen ends (I used a video capturing software to double check). You can also see in the stack trace:
position: (100, 107.966797); delta: 0.133333  <-- this was called before the end of splash screen
position: (100, 123.966797); delta: 0.133333  <-- this was called after the end of splash screen with delay
position: (100, 132.96788); delta: 0.075009
position: (100, 133.159393); delta: 0.001596
position: (100, 134.93335); delta: 0.014783
position: (100, 136.914307); delta: 0.016508
position: (100, 138.921906); delta: 0.01673

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by Dillybob1992** [comment]
Snap is VERY hard to see, but the stack track does prove it is there. Can confirm this

**Comment by realManix** [comment]
_ready always gets called before the first _process. The problem is that the first _process call happens while the splash screen is shown, and the second call after, but for some reason there is an unusually long delay between the two so if there is for example movement code in _process, it would look as if the Node jumped between the first two frames. The _physics_process seems to get called without this abnormality however, so if the movement is done in _physics_process and a camera is following that node in _process, when the splash screen ends, for a split second the camera would be facing the initial position of the node, and only from the second _process call--which happens some time after the end of splash screen--would the camera be correctly following the Node.

**Comment by LinuxUserGD** [comment]
What about http://docs.godotengine.org/en/latest/learning/features/misc/background_loading.html ? Does Godot 3 support background loading the same way as Godot 2 does?

**Comment by akien-mga** [comment]
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by reduz** [comment]
This is not really a bug, it will happen every time you load something on the main thread. I suggest you just work it around.
