### ISSUE TITLE
Something wrong with the camera or clipping plane (regression from 02438031)

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#15013]
**Godot version:**
latest

**OS/device including version:**
no matter

**Issue description:**
The camera clips off the pixels of my planet, in beta this problem is not exist... 

![image](https://user-images.githubusercontent.com/3036176/34328808-c260897c-e8fa-11e7-97d9-41f6a568c5b3.png)

should be view like this -

![image](https://user-images.githubusercontent.com/3036176/34328794-365f7f5a-e8fa-11e7-9f81-29a8fef283d9.png)

**Minimal reproduction project:**
https://github.com/Chaosus/GDPlanet

**Comment by volzhs** [comment]
I believe it is latest but... some days later, it won't.
would you specific commit hash?

**Comment by Chaosus** [comment]
Yeah, as I said this problem is not exist in first beta build... I need more time to find the commit which introduce this regression

**Comment by volzhs** [comment]
I mean the commit hash of your latest for this issue.
not specify which commit causes this.

**Comment by Chaosus** [comment]
63e9102, however I found this problem several days before, but didnt have mood to publish it

**Comment by LinuxUserGD** [comment]
This depends on the camera setting (clipping plane). Try it with the same near and far value.

**Comment by Chaosus** [comment]
If I set near to 0 I've got
 
![image](https://user-images.githubusercontent.com/3036176/34334997-97a3a176-e95c-11e7-9e0b-ed335051ca7f.png)

otherwise changing near or far have no effect

**Comment by Chaosus** [comment]
I found the commit which enable this behavior -
https://github.com/godotengine/godot/commit/0243803117b2a67a33a9e01cf97e79ea4cf48c54
cc @reduz

**Comment by reduz** [comment]
I may have fixed this today, please give it another test

**Comment by Chaosus** [comment]
Yes its fixed ! Thank you very much !
