### ISSUE TITLE
Feature request. Filesystem search should not be case sensitive.

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#15017]
**Godot version:**
Any

**OS/device including version:**
ANY

**Issue description:**
the search feature in the filesystem is case sensitive. this becomes less intuitive in projects involving a team where file names get changed/ upper and lower casing gets accidentally mixed and so on. since the import editor is tied to the filesystem tab and a file must be selected to populate the import settings, this leads to a lot of digging for source files. 

**Steps to reproduce:**

**Minimal reproduction project:**
solutions? make the search ignore case sensitivity or add a quick jump option linking to the source file in question. save a lot of time and headache working with 3d projects or any project really.

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by QuentinCaffeino** [comment]
> projects involving a team where file names get changed/ upper and lower casing gets accidentally mixed and so on

You should have a style guide.

Generally I disagree. Because there could be two different files with just one difference in name eg.:
'dog' and 'Dog'

If someone is still going to implement this then it should show both files.

**Comment by vonflyhighace2** [comment]
Well the point in have non-case sensitive search is to have all theoretical files names dog returned. Yes style guides are important but I assure you in a team based environment your bound to have this problem crop up. having to dig through tens of folders to find the source file/asset in projects can lead to time water and a pain.

**Comment by Calinou** [comment]
It's definitely more user-friendly to make search work in a case-insensitive fashion, so it should be done.

Note that GDScript has an [official style guide](http://docs.godotengine.org/en/latest/learning/scripting/gdscript/gdscript_styleguide.html) as of 3.0. File name casing is not specified yet, but based on my experience, they should use `snake_case` naming (which is what demos use).
