### ISSUE TITLE
Scene crashes when saving with a camera node

### ISSUE THREAD

**Issue by abcde13** [godotengine/godot#15019]
**Godot version:**
3.0 beta 2 build

**OS/device including version:**
Mac OSX 10.10.5

**Issue description:**
Scene crashes when saving with a camera node

**Steps to reproduce:**
1. Start a new scene.
2. Add a Camera Node.
3. Save scene.

Hits 100%, then Godot Crashes

**Minimal reproduction project:**
I don't think this is necessary. The steps are really simple to reproduce

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.
Note: There was [THIS](https://github.com/godotengine/godot/issues/9682) issue, but it seemed related to creating the camera node. I experience the crash only when I save the scene with the camera in it.

**Comment by Ranoller** [comment]
I try to replicate in windows7 and i can´t:
![cameranodes](https://user-images.githubusercontent.com/11712737/34341120-1b1f5480-e991-11e7-97f5-b23d4246229c.png)

**Comment by Zireael07** [comment]
ARVR Camera does not equal a normal camera.

**Comment by abcde13** [comment]
![camerafail](https://user-images.githubusercontent.com/894122/34341397-6645d5f6-e94b-11e7-8633-38e8f222dbce.gif)

GIF for what happens on my end.

**Comment by Ranoller** [comment]
> 

ARVR Camera does not equal a normal camera.
--
I know.  Look at my screen capture. I try to replicate with Camera2d, Camera, InterpolatedCamera and ARVRCamera.

**Comment by abcde13** [comment]
Ah, I see @Ranoller . Also, don't know if you meant it, but you can use the "quote" by clicking the button or using the ">" character to quote a line.

So then this problem is localized to OSX? Hopefully not just my old version of OSX.

**Comment by volzhs** [comment]
not sure but #14977 might fix this.

**Comment by Jerome67000** [comment]
On Windows 10 64 bits I got 2 frezzes / 10 tests after saving a scene with a Camera node, so not sure if it is related. If PR #14977, ping me and I will investigate more.

**Comment by volzhs** [comment]
@Jerome67000 the PR was merged. would you test it?

**Comment by Jerome67000** [comment]
No more freeze for me. But i can't comfirm at 100% that the bug is fixed because only got 2/10 freeze before.

**Comment by akien-mga** [comment]
Assuming fixed by #14977, please comment if it's not the case.
