### ISSUE TITLE
Add ability to duplicate track in AnimationPlayer

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#15029]
I'd like to request the ability to duplicate a track in the AnimationPlayer pane. Often times, I want to have the same animation track play on multiple nodes, so being able to duplicate the entire track, then just adjust the node path would be a huge boon to my productivity. As it is, it's quite tedious to do this.

**Comment by akien-mga** [comment]
Not that I know of, but it should be easy to implement.

**Comment by DleanJeans** [comment]
I really needed when dealing with rendering order problems, where you need to reparent some of your `Sprites` from to a new node and you also wanna animate this new node exactly as the old parent node. Especially tracks with numerous keyframes.

**Comment by DualMatrix** [comment]
Can't this currently easily be done via copy_tracks and paste_tracks?

**Comment by 201604830** [comment]
I'm going to try to fix this.

**Comment by fire** [comment]
This will need the gdscript bindings / ui added, but it should work.

```cpp
int32_t Animation::copy_track_to_path(Ref<Animation> p_animation, const int32_t p_src_track, const NodePath p_new_path) {
	ERR_FAIL_COND_V(p_animation.is_null(), -1);
	ERR_FAIL_INDEX_V(p_src_track, p_animation->get_track_count(), -1);
	ERR_FAIL_COND_V(find_track(p_new_path) != -1, -1);
	int dst_track = get_track_count();
	int32_t r_new_track = p_animation->add_track(track_get_type(p_src_track));

	p_animation->track_set_path(dst_track, p_new_path);
	p_animation->track_set_imported(dst_track, track_is_imported(p_src_track));
	p_animation->track_set_enabled(dst_track, track_is_enabled(p_src_track));
	p_animation->track_set_interpolation_type(dst_track, track_get_interpolation_type(p_src_track));
	p_animation->track_set_interpolation_loop_wrap(dst_track, track_get_interpolation_loop_wrap(p_src_track));
	for (int i = 0; i < track_get_key_count(p_src_track); i++) {
		p_animation->track_insert_key(dst_track, track_get_key_time(p_src_track, i), track_get_key_value(p_src_track, i), track_get_key_transition(p_src_track, i));
	}
	return r_new_track;
}
```

**Comment by fire** [comment]
There are three problems.

1. duplicate a track in the AnimationPlayer which is added in 3.1
2. duplicate a track in the AnimationPlayer to a path which my above code does
3. (Code) duplicate a track from one AnimationPlayer to another AnimationPlayer which should be possible in gdscript since the function takes an animation reference
4. (UI) duplicate a track from one AnimationPlayer to another AnimationPlayer. This requires a UI dialog that lets you select an animation player and then name the nodepath to duplicate the track.

Hope that clears up the confusion.

**Comment by JarLowrey** [comment]
This is now possible by clicking on "Edit" and then "Copy Tracks"

![image](https://user-images.githubusercontent.com/7429786/55023763-c0488400-4fba-11e9-9685-77746c89dade.png)

https://godotengine.org/article/godot-gets-brand-new-animation-editor-cinematic-support

**Comment by kimjiy9607** [comment]
Is it not closed because #24210 hasn't passed the review request?

**Comment by Calinou** [comment]
@kimjiy9607 Indeed, the pull request needs to be merged first before this can be closed.

**Comment by KoBeWi** [comment]
This is possible by using Copy Tracks and Paste Tracks. Looking at the closed PR, the implementation was the same, except you could do it with one button. IMO the Copy/Paste is sufficient.
In any case, this should be moved to [proposals](https://github.com/godotengine/godot-proposals) if you think it's still relevant.
