### ISSUE TITLE
C:\temp\godot\core\typedefs.h(33): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

### ISSUE THREAD

**Issue by veyluna** [godotengine/godot#15021]
First of all sorry If my issue report isn't good enough.

**Operating system or device - Godot version**:

Windows 10, Godot master branch

**Issue description**:

It's the first time I'm trying to run Godot from resource code and I got this error message. In an another issue report something like this happened and resolved with a little change in the related SCsub file but even though I nearly checked all of the SCsub files I couln't find "stddef.h".

In the same issue report they also said delete the related line and after doing that same error happened in different files.

Tried to delete and clone again all repository but didn't work out.

I also tried a bunch of stuff about environment variables but still no action.

Here is the full message I get:
>scons: Reading SConscript files ...
>Detected MSVC compiler: x86
>Compiled program architecture will be a 32 bit executable. (forcing bits=32).
>YASM is necessary for WebM SIMD optimizations.
>WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
>Checking for C header file mntent.h... no
>scons: done reading SConscript files.
>scons: Building targets ...
>[Initial build] run(["core\method_bind.gen.inc", "core\method_bind_ext.gen.inc"], 
>["core\make_binders.py"])
>[Initial build] Compiling ==> platform\windows\godot_win.cpp
>godot_win.cpp
>C:\temp\godot\core\typedefs.h(33): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
>scons: *** [platform\windows\godot_win.windows.tools.32.obj] Error 2
>scons: building terminated because of errors.

**Comment by LinuxUserGD** [comment]
Link to the other issue?

**Comment by QuentinCaffeino** [comment]
1. Please provide commit number.
2. If you use docker, try build source using container.

**Comment by veyluna** [comment]
Commit number: 8b0ad17b760b6cc803edc815fe65f8de1d92bf74

Other issue link: https://github.com/godotengine/godot/issues/10532

And no, I haven't used docker but I'll give it a shot.

**Comment by QuentinCaffeino** [comment]
@veyluna I'm on a same commit and I built it successfully.

Could you provide all steps you took to compile source?

**Comment by vnen** [comment]
This has nothing to do with #10532, it's a different issue. This is a configuration problem. Go to the VS prompt and type: `echo %INCLUDE%`. It should show a list of paths and one of them should be like `C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt` (version might be different), which contains the missing file.

If it's not like this, your configuration is broken. You can try to reinstall Visual Studio and/or its components.

**Comment by veyluna** [comment]
I don't know which thing has done the magic but I installed the SDK from a different link, Repaired it and after run the command prompt as the admin it worked (and I think admin part did it). Thanks for help all

**Comment by gbbnfhb** [comment]
I was due to this
Windows Driver Kit (WDK) 
uninstall  !!
