### ISSUE TITLE
VS Code opens every time you switch scene tabs

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#15024]
**Godot version:**
3.0 beta 2

**OS/device including version:**
Windows 10

**Issue description:**
Every time you switch scene tabs in the IDE, VS Code opens up. This is annoying if you are using the IDE and VS Code on the same screen.

**Steps to reproduce:**
Switch scene tabs.

EDIT: Seems to only occur when you switch to a scene that has a script on the base node.

**Comment by vnen** [comment]
This is likely related to the option on Editor Settings > Text Editor > Files > Open Dominant Script On Scene Change. Try disabling it and see how it goes.

**Comment by 11clock** [comment]
@vnen Fixed it for a bit, but after like a minute VS Code started opening on scene change again despite this feature being disabled.

**Comment by nuke-makes-games** [comment]
In my opinion this option should default to off. It's just incredibly annoying to have VS Code interrupt what i'm doing when i'm navigating the project. Very disruptive.

**Comment by neikeq** [comment]
@nuke-makes-game I can't link it from my phone but there is already another issue about that.

**Comment by Calinou** [comment]
@nuke-makes-games @neikeq See https://github.com/godotengine/godot/issues/13429.
