### ISSUE TITLE
Feature request: Generate executable from a Godot project via terminal / cmd

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#15022]
**Godot version:**
latest

**OS/device including version:**
Linux, Windows, Mac

**Issue description:**
I can compile Godot's source with Scons after installing the required build packages.
The possibility to compile a game (source code of a godot project) with installed export templates the non-gui way with a command-line interface would be awesome as this allows development snapshots generated on the player's computer.

**Comment by QuentinCaffeino** [comment]
Read the docs first)
https://godot.readthedocs.io/en/latest/learning/editor/command_line_tutorial.html?highlight=command%20line#exporting

**Comment by Noshyaar** [comment]
Closing as already implemented
