### ISSUE TITLE
String.Split() function not working properly

### ISSUE THREAD

**Issue by almacero** [godotengine/godot#15034]
**Godot version:**
v3.0.beta.custom_build.59ec417

**Issue description:**
var list = "Do, Re, Mi, Fa".split(",")
list = ["Do", "Re, Mi, Fa"]
instead of:
list = ["Do", "Re", "Mi", "Fa"]

**Comment by volzhs** [comment]
duplicated with #14799

there is a reason why this is in issue template.
it would be better to leave it and don't forget to search for same issue.

> - [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.
