### ISSUE TITLE
[C#] AnimationPlayer doesn't work with C# properties.

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#15030]
**Godot version:**
3.0 b2

**OS/device including version:**
Windows 10

**Issue description:**
The AnimationPlayer node works fine with C# fields, but doesn't seem to work with C# properties. For instance, the following works fine in GDScript:
```swift
extends Node2D

export(int) var frame = 0 setget _set_frame
	
func _set_frame(f):
	frame = f
	var children = get_children()
	for c in children:
		if c is Sprite:
			c.set_frame(frame)
```
But the same code in C# doesn't seem to work at all:
```csharp
using Godot;
using System;

public class Armor : Node2D
{
    private int frame;
    [Export]
    public int Frame {
        get { return frame; }
        set {
            frame = value;
            object[] children = GetChildren();
            foreach (object c in children) {
                if (c is Sprite) {
                    ((Sprite)c).Frame = frame;
                }
            }
        }
    }
}
```
When I try to do this, the following error arises: ```Failed setting track value 'Armor:Frame'. Check if property exists or the type of key is valid...```
In this particular case, I have a workaround, but I think that C# properties should absolutely be supported in AnimationPlayer.

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by Hinsbart** [comment]
Note that this is not really an issue with the `AnimationPlayer` as we currently don't support C# properties at all (e.g `['Export]`ing them doesn't work either).

**Comment by jonbonazza** [comment]
@Hinsbart what kind of timeline do we have for supporting them? In my opinion, not having the ability to export properties is a major hindrance to the C# support.
