### ISSUE TITLE
Focus Selection hotkey only focuses last 3d viewport if viewports > 1.

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#15035]
**Godot version:**
Build: bf4d398d4

**OS/device including version:**

Windows 10pro 64

**Issue description:**

When pressing F to focus on the selection, it will focus on the last viewport.
I expected it to only focus in the viewport the mouse is currently in.

**Steps to reproduce:**
Set the 3d view to have 2 or more viewports. Select a node and in any viewport except the last one press f.

**Minimal reproduction project:**

![2017-12-25_03-22-21_min](https://user-images.githubusercontent.com/12641229/34337773-f46c1274-e927-11e7-87e3-7df75b968864.gif)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Einlander** [comment]
It seems mostly fixed. But you can still reproduce it by double clicking on a node in the scene tree. It ignore the other viewports and sticks with the first one.

**Comment by akien-mga** [comment]
Let's close as fixed then. The other issue with double-click the icon in the scene tree is trickier as it's not clear which viewport should be affected (first one, all of them, last focused one but that's tricky as the "focus" is easily lost when moving the cursor to the scene tree).
