### ISSUE TITLE
Disable Generated Comments in Scripts

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#15037]
The generated comments in scripts are annoying to remove every time. It would be nice to be able to disable them.

**Comment by MrJustreborn** [comment]
You can select a preset with no comments:
![bildschirmfoto_2017-12-25_12-06-04](https://user-images.githubusercontent.com/11594586/34338783-27c1497a-e96c-11e7-9038-13b9d75a06c4.png)

**Comment by Noshyaar** [comment]
Duplicate of #5711, use the presets.
