### ISSUE TITLE
Different behaviour in Mix Modes between Editor and Preview

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#15047]
**Godot version:**

Godot 3 beta 2

**OS/device including version:**

Windows7

**Issue description:**

Light2D, Particles2D, CanvasItemMaterial mix modes.... have different behaviour between editor and preview. There is a demostration of particles here: #13443
![bugmixmodeseditor](https://user-images.githubusercontent.com/11712737/34341221-34780eac-e993-11e7-853e-90bb946c3aee.png)

**Minimal reproduction project:**
Project here #13443

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.
There is a duplicate made by me, but I close and reference here.

**Comment by reduz** [comment]
Tested with demo in #13443 and I don't see any problem. May have been solved by recent fixes. Please test again, worst case just attach another example.

**Comment by Ranoller** [comment]
[Godot3_MixModesBug.zip](https://github.com/godotengine/godot/files/1608966/Godot3_MixModesBug.zip)

Sorry, in this project it´s more clear the problem.

**Comment by Ranoller** [comment]
I test this with Godot 3 compiled at 05/01/2017 (yesterday). Problem seems to be here.
![bugmixmodes](https://user-images.githubusercontent.com/11712737/34641647-857304ba-f307-11e7-933b-01024b211f07.png)

**Comment by vnen** [comment]
I can reproduce with the sample attached.
