### ISSUE TITLE
glTF importer ignores KHR_materials_pbrSpecularGlossiness section

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#15059]
**Godot version:**
37aab45

**OS/device including version:**
Debian GNU/Linux

**Issue description:**
Some glTF files ([example](https://sketchfab.com/models/799ceef5191e4f3fa1bb12350fe847ea#)) store the texture information in KHR_materials_pbrSpecularGlossiness section. Right now, these are silently ignored but Godot can convert the specular-glossiness workflow numbers into metal-roughness numbers using the conversion mentioned in [this document](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness#specular---glossiness) and make it look correct.

**Steps to reproduce:**
Import a glTF file with KHR_materials_pbrSpecularGlossiness section.

**Comment by seadra** [comment]
BTW, importing [that glTF file](https://sketchfab.com/models/799ceef5191e4f3fa1bb12350fe847ea#) with Gen Lightmaps option enabled crashes Godot editor.

**Comment by LinuxUserGD** [comment]
Can you import the glTF file in Blender?

**Comment by seadra** [comment]
Similar to the other glTF issue I created, this is also about the importer.

Godot importer for assets prepared in metallic-roughness work is OK. Godot doesn't seem to support specular-workflow, but there are such assets  online, and Godot silently drops the specular-workflow textures. This is true regardless of the exporter you use.

**Comment by capnm** [comment]
godot3 uses the new metallic-roughness model, also it works as expected.
IMO the actual bug is, that godot doesn't fail to load the model in the xtensionsRequired case:

![glft-mr-sg](https://user-images.githubusercontent.com/4047289/34386861-3f0d9c94-eb2b-11e7-829d-def67430392b.jpg)

**Comment by fire** [comment]
Godot Engine isn't required to support KHR_materials_pbrSpecularGlossiness.

I agree. 

Godot Engine should fail the file with an ERR_FILE_UNRECOGNIZED or FAILED with a message saying that Specular Glossiness is not supported.

https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#specifying-extensions

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?
The linked models died.

**Comment by fire** [comment]
As far as I know this is still valid because my pr for it is unmerged.

If it helps I can give a example model.

https://sketchfab.com/3d-models/scifi-girl-v01-96340701c2ed4d37851c7d9109eee9c0#download This one has gloss spec.
