### ISSUE TITLE
Allow scaling of collision shapes and rigid bodies for easier subscene management

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1505]
Sometimes you implement full part of scene in a subscene, including collision objects and rigid bodies,
for easier testing, then you need to integrate this part into the whole main scene, which requires scaling. With current approach you have to split the resulting scene into physics/collision objects and
visual objects and integrate these separately, actually recreating physics/collision part. There should be
some mechanism for making this less tedious task.

**Comment by reduz** [comment]
this is planned for 1.1. However, for sphere and capsule, only uniform
scale will work (This limitation is standard in all physics engines).

**Comment by reduz** [comment]
err sorry, for 1.2

**Comment by eska014** [comment]
As far as I know, scaling is implemented for all collision shapes by now.
However, scaling rigid bodies is not yet possible.

**Comment by reduz** [comment]
neither works very well, but adding status checks / warnings to nodes
should make this more obvious

**Comment by slapin** [comment]
I think if straightforward approach doesn't work for subscenning of bodies
and
collision shapes, some cheating should be implemented...

**Comment by neikeq** [comment]
> neither works very well, but adding status checks / warnings to nodes should make this more obvious
@reduz

Warnings were recently added, IINW.

**Comment by akien-mga** [comment]
I think the idea is to rework the collision shapes system completely for 3.0, so it will likely be fixed at that time.

**Comment by akien-mga** [comment]
I think this is implemented in 6ba1e467 for 2D, but not yet for 3D.

**Comment by reduz** [comment]
Missing for 3D, will do when porting 3D demos

**Comment by reduz** [comment]
this is implemented now, closing
