### ISSUE TITLE
Open layers in Openexr

### ISSUE THREAD

**Issue by fire** [godotengine/godot#15050]
**Godot version:**

master

**OS/device including version:**

windows 10

**Issue description:**

Anyone got a good design for this? The feature is for openexr to open layers. Currently each channel in openexr is R, G, B, A, but in the openexr format layers are named Layer1.R, Layer1.G, Layer1.B, Layer1.A and Layer2.R, Layer2.G, Layer2.B, Layer2.A How would you recommend modifying godot?

A) It needs to scan all the channels for the list of layers and then provide the list in a list.
B) Provide a way to merge the layers?
C) Provide a way to seperate the layers into different images.

This is the conversation with the tinyexr library author: https://github.com/syoyo/tinyexr/issues/53

There is interest in reddit. https://www.reddit.com/r/godot/comments/7k83du/does_godot_30_support_psd_or_any_other_format/

**Comment by akien-mga** [comment]
Superseded by #23723 which has some more details.
