### ISSUE TITLE
Imported GLTF scenes uses Lambert diffuse

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#15054]
**Godot version:**
beta2

**OS/device including version:**
Debian GNU/Linux

**Issue description:**
Imported GLTF scenes use Lambert diffuse mode, with doesn't look right with PBR models.
If it's OK assume Godot 3 should default to PBR, I think Material's constructor should default to Burley rather than Lambert [here](https://github.com/godotengine/godot/blob/master/scene/resources/material.cpp#L2143).

Or, maybe this can be an import option?

**Steps to reproduce:**
Import any PBR GLTF file from sketchfab, and compare how it looks against Godot.

**Comment by LinuxUserGD** [comment]
Do you have this issue with the Blender glTF 2.0 exporter how does Sketchfab create the glTF file? Is it glTF 2.0?

**Comment by seadra** [comment]
Yes, actually, this behavior is about the importer, it is independent of the exporter.

**Comment by nonfatmatt** [comment]
Can confirm this bug. Given that glTF 2.0 is explicitly uses PBR materials imported materials using glTF should default to Burley instead of Lambert.

**Comment by Jerome67000** [comment]
It is ok to have Burley default material for all kind of 3D model ?

Changing this line to `DIFFUSE_BURLEY` is what this do !
https://github.com/godotengine/godot/blob/2c17af050935bccf17deb6e6489ade64c0af2f73/scene/resources/material.cpp#L2144
