### ISSUE TITLE
RayTrace is much darker than ConeTrace with BakedLightmap

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#15055]
**Godot version:**
37aab45

**OS/device including version:**
Debian GNU/Linux

**Issue description:**
Using the same setting, by just changing the Mode between ConeTrace and RayTrace, the light energy is vastly different.

With ConeTrace
![6tlxiq](https://user-images.githubusercontent.com/9574367/34343484-1d78ecca-e99e-11e7-9dd9-ae8fc5ddd73c.jpg)

With RayTrace
![9bpl7u](https://user-images.githubusercontent.com/9574367/34343485-222d84a6-e99e-11e7-9dd3-9bbe06783fa3.jpg)

**Steps to reproduce:**
Import a GLTF scene with Gen Lightmaps on. Add a DirectionalLight and add an WorldEnvironment with no light. Add a BakedLightmap and bake with ConeTrace. Then switch to RayTrace and rebake.

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by seadra** [comment]
Also, this is a different issue but some light leaks a little around the edge where the wall meets the floor in both modes (can be seen in both screenshots I attached above).

**Comment by reduz** [comment]
Conetrace is an approximation, and generally does look lighter. Raytrace is
more correct.

There will always be bias in very thin walls due to using an octree instead
of a bvh.

**Comment by seadra** [comment]
> Conetrace is an approximation, and generally does look lighter. Raytrace is
more correct.

That's a bit confusing but OK. It would be better to explicitly document this behavior because the difference is very dramatic, and the current documentation [here](http://docs.godotengine.org/en/latest/learning/features/3d/baked_lightmaps.html#baking-quality) doesn't mention it at all.

> There will always be bias in very thin walls due to using an octree instead
of a bvh.

Unreal actually has a few parameters to mitigate the problem of light bleeding through thin-walls. Will there be similar options in Godot?

**Comment by reduz** [comment]
Will eventually port the bakers to OpenCL and use BVH or something else.
This is the best that could be done in the little amount of time available
to implememt the feature.

**Comment by seadra** [comment]
Got it, looking forward to it!

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by akien-mga** [comment]
Is this still relevant in the current master branch? If so, what should be done? Just mention this in the documentation?

**Comment by seadra** [comment]
Yes, it is, unfortunately, and this is bad UX IMO.
Can't Godot be changed such that they look similar out-of-the-box?

**Comment by Calinou** [comment]
@seadra I suppose it could be tweaked if we had several test scenes to compare each mode (with various lighting intensities). If we aim to make them look similar out of the box, it should work in the most situations possible :slightly_smiling_face:

**Comment by Perrottacooking** [comment]
hi  Seadra
v3.1.1 Stable - Still with the same problem?

**Comment by seadra** [comment]
Nothing changed as far as I can tell

**Comment by JFonS** [comment]
Closing as fixed by #44628.
