### ISSUE TITLE
Expose Viewport gui.mouse_over to GDScript

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#15062]
In my game I am raycasting into the scene and picking objects in the world. Yet I do not want this to occur if the mouse is over certain GUI elements.

I see Viewport has a gui.mouse_over variable to track what the mouse is over but there is no way to access this pointer. 

I would like to be able to access this in gdscript.

**Comment by reduz** [comment]
Why not just putting a large control covering the whole screen, behind other controls and just raycast when the mouse is over it?

Accessing this code may not be what you want, as it also accounds for capture when dragging

**Comment by supagu** [comment]
I went with your idea @reduz and it works good. But I am running into another use case:

pressing "t" on the keyboard is bound to bring up my chat dialog. But I only want to do this of there is no line edit that has focus. Not exactly mouse_over functionality, but which widget has focus (perhaps that already exists?)

**Comment by vnen** [comment]
@supagu using `_unhandled_input(event)` is not enough?

**Comment by supagu** [comment]
@ven actually that has helped a lot! I totally forgot about that. One thing I am stuck on is find out if an event is connected to an action. Eg. I have some code:
if (Input.is_action_pressed("move_forward")):
		dir += -transform.basis[2];

I wont to move into my input handler, is there something like event.is_action("move_forward") ?

**Comment by akien-mga** [comment]
http://docs.godotengine.org/en/latest/classes/class_inputevent.html#member-functions

**Comment by supagu** [comment]
_unhandled_input(event) occurring even when a LineEdit has focus and the keyboard is pressed.

I put a break point in Viewport::unhandled_input
then I give focus to a LineEdit and press a buttton. My break point is then hit.

I'm on the godot 3.0 branch, just updated to latest tonight.

**Comment by Calinou** [comment]
@supagu Did you find a suitable workaround, or is there still a need for this feature?

**Comment by supagu** [comment]
Ah I didn't even know this was still open. I have so forgotten about it I must have got things working sufficiently
