### ISSUE TITLE
Weird behaviour when setting the rect size via code and anchors

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15061]
**Godot version:**
master: 37aab45

**Issue description:**
I have an anchored control set fully to `Below`, but I also have a signal that manually changes the `rect_size.x` when its parent is resized. This makes the anchor be completely ignored.

**Minimal reproduction project:**
[Example.zip](https://github.com/godotengine/godot/files/9227076/Example.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by KoBeWi** [comment]
@YeldhamDev Is this still valid in 3.2.4 beta2?
I checked the project, but not sure what is the issue.

**Comment by YeldhamDev** [comment]
If I remember correctly:
The problem is that if the bit of code in the script is uncommented, the `y` value of `TextureRect` stops being updated, even if it just overrides the `x` value.

And from testing right now, it seems that it still occurs.

**Comment by YeldhamDev** [comment]
Still happens in c2d55a4e1a353b75eb598277e9a6403fc6bfc4d5, the example has been updated.

**Comment by EAinsley** [comment]
Related to #92929.
