### ISSUE TITLE
Can't use operator to compare 0 and 1 in If statement

### ISSUE THREAD

**Issue by Skyfrit** [godotengine/godot#15075]
**Godot version:**
Godot 3.0 beta 2

**OS/device including version:**
Windows 10 64bit

**Issue description:**
If you use operator to compare 0 and 1 in If statement, it will give you this error.
Invalid operands 'int' and 'bool' in operator'=='

**Steps to reproduce:**
This work.
```
var Bool = randi() % 2

if (Bool):
    print("True")
else:
    print("False")
```

This not work.
```
var Bool = randi() % 2

if (Bool == true):
    print("True")
else:
    print("False")
```

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by mrcdk** [comment]
That behavior was removed because it was error prone. If you want to still use an int as a boolean you'll need to convert it with `bool(int)`

**Comment by Skyfrit** [comment]
Thank you.
