### ISSUE TITLE
Should we keep the `z` property in Node2D? (naming)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15078]
Godot 3.0

In `Node2D`, there is a property named `z`. When used, this property overrides the drawing order of the node. So far, so good.

However, in Godot 3.0 properties became first-class reserved names in scripts, which means any script inheriting `Node2D` & cie will be unable to use `z` for any variable, be it member, parameter or even locals.

I know good practice about naming variable names, but that one's name is either way too good, or just awful (depends on view point considering good practice xD), but I think it should be renamed, especially when you consider inheritance, and it's not used that much in scripts, in general, to the point of being a one-character variable.

Could it be renamed `z_order`? (now is the best time, 3.0 is still beta)

**Comment by raymoo** [comment]
What about `depth`? I don't like `z_order` because to me an "order" is a global object, defining the ordering relation between different elements.

**Comment by Jerome67000** [comment]
It's a good idea to rename this, can be boring to don't allow to use `z` as a variable.

To visualize a bit :
![image](https://user-images.githubusercontent.com/7358899/34408023-b76754d2-ebc1-11e7-89e2-2aa983e9a2a0.png)

In Libgdx (which is for me a clean code and good named) it's [ZIndex](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/Actor.html#setZIndex-int-). In Phaser it's `renderOrderID`. In OpenGL we are rahter talking about `GL_DEPTH_TEST`...

For me, both `z_order`, `z_depth` or `z_index` can be used.

**Comment by raymoo** [comment]
I like `z_index` or `z_depth`

**Comment by nhydock** [comment]
I like `z_index`, or we could be more explicit and actually call it `draw_order` on Node2D

**Comment by Jerome67000** [comment]
If it's ok for you, I have a ready commit for this :

![image](https://user-images.githubusercontent.com/7358899/34446702-9fc35bf6-ecdd-11e7-907f-13f9b10cc1f2.png)

**Comment by Jerome67000** [comment]
Modification is ready to be checked and merged.

Do you know if an issue listing all breaking changes from 2.1 to 3.0 exist ? I must add this one !

**Comment by akien-mga** [comment]
Fixed by #15191.

**Comment by girng** [comment]
> reserved names in scripts, which means any script inheriting Node2D & cie will be unable to use z

this is untrue. unless that script is using the word `z` (and not a public member variable).

why are we continuing to make silly syntactical changes over use-cases that don't exist?

**Comment by Zylann** [comment]
@girng it used to be true, name lookup was changed, which is why this issue is now closed

**Comment by girng** [comment]
i see. maybe i misread issue, my bad.
