### ISSUE TITLE
Godot plugins need a script-accessible means of accessing all available script extensions

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#15086]
**Godot version:**
Godot 3.0 (in general)

**Issue description:**
If one were to develop a plugin that deals with script files in any way, developers have to account for `.gd`, `.vs`, `.cs` and `.gdns`. However, the fact that `PluginScript`s exist means that people will be able to download additional scripting languages, and therefore those file extensions will also be added to the list for as long as the plugin is active.

3rd party plugins, unaware of a `PluginScript`'s installation, need an agnostic means of including additional file extensions when deducing whether a file is a script or not (preferably something that does NOT involve having to load the resource and check if it extends Script since you'd have to do it for every file to be 100% sure).

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+pluginscript) for potential duplicates.

**Comment by eska014** [comment]
Does `ResourceLoader.get_recognized_extensions_for_type('Script')` work?

**Comment by vnen** [comment]
In a similar note, it would be interesting to expose `Script::instance_create()`. Each language have their own conventions on how to create an instance, so calling `.new()` only works for GDScript. Right now there's no way to create a VisualScript instance from scripting.

**Comment by willnationsdev** [comment]
@vnen Since GDScript and C#, the two arguably most-used scripting languages, both now implement `.new()`, we might as well just implement it for all scripting languages for consistency's sake (and add it to the Script class's interface as a pure virtual function). Also, `instance_create()` doesn't actually create an Object from the script. You have to pass the object in as a parameter and it returns a ScriptInstance. `.new()` is the only thing that actually makes an object and attaches the script to it.

That should be a discussion for a different Issue though. Closing this one since @eska014's answer satisfies its concerns (thanks for that!).
