### ISSUE TITLE
TestSphere is needed

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1508]
To make quick test mesh setup, just TestCube is not enough, having TestSphere will make things more natural, and allows (with help of TestCube) creating of simple character meshes very quickly...

**Comment by LeonardMeagher2** [comment]
#1381

**Comment by reduz** [comment]
planned for 1.2

**Comment by bojidar-bg** [comment]
I think that it will be better if we have classes like "CubeMesh", "SphereMesh", etc. that extend the "Mesh" class. That way we won't have nodes for everything in the node selection menu, and it will be easy to change properties like size, subdivisions, etc. directly in the resource editor. Also it will make it very simple to change from a prototyping mesh to a "real" one.

**Comment by kubecz3k** [comment]
closing because it duplicates the https://github.com/godotengine/godot/issues/1381
