### ISSUE TITLE
RayCast get_collider() is not cleared after a collision

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#15087]
**Godot version:**
3.0 beta 2

**OS/device including version:**
Ubuntu 16.04 64

**Issue description:**
Object caught in the beam remains in its getter forever
In BULLET mode

**Minimal reproduction project:**
[Bug physics.zip](https://github.com/godotengine/godot/files/1588347/Bug.physics.zip)

**Comment by JosephCatrambone** [comment]
Can confirm on Windows 10 for a recent-ish pull of master.

**Comment by brainsick** [comment]
Ubuntu 17.10, Godot 3.0 Beta 2, AMD Radeon R9 Fury

I can confirm the behavior you're reporting and it's not what I would expect.  However, I can't tell if this is intended behavior and/or intended usage of the API.

http://docs.godotengine.org/en/latest/classes/class_raycast.html?highlight=RayCast#class-raycast-is-colliding

When incorporating the `is_colliding()` check, the behavior is what I would expect.

```
func _process(delta):
	var ray = get_node('ray')
	if ray.is_colliding():
		print(ray.get_collider())
```

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by AndreaCatania** [comment]
@DimaKiva I've tested it, and I get the same behavior with godot physics too. Can you please confirm me that? I'll make a fix soon

**Comment by AndreaCatania** [comment]
Fixed, the real problem was that you should check using is_colliding function if the collision happened, however now the body is resetted if no collision occurs.

**Comment by DimaKiva** [comment]
3.1-alpha1 The problem is no longer there.
