### ISSUE TITLE
KinematicBody.move_and_slide() returns initial movement rather than remaining movement

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#15084]
**Godot version:**

d5918b5

**OS/device including version:**

Arch Linux

**Issue description:**

move_and_slide() returns the value put into the first argument rather than what is left to move

**Steps to reproduce:**
Create a kinematicbody
Move in free space
Return value is the same as initial move

**Minimal reproduction project:**

[BrokenMoveAndSlide.zip](https://github.com/godotengine/godot/files/1588164/BrokenMoveAndSlide.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by Silvea12** [comment]
Note: I'm going to have to sleep now, but I noticed that if I put a plane collision in the way, the internal `move_and_collide()` function call returns that there was no collision, and nor does slide return any note of sliding.

**Comment by damarindra** [comment]
I'm aware with this. It seems the documentation is wrong. You don't need remaining movement when using move_and_slide, you can set the max bounce parameter to process the remaining movement until reach to max bounce. The return value is final velocity, not the initial velocity. Example when you don't move and affected by gravity, the velocity is not (0, gravity), but (0,0).

**Comment by FilippoBovo** [comment]
I tested Vector2.slide(Vector2 n) and it returns (0, 0) no matter what inputs I chose.

**Comment by reduz** [comment]
Please read the doc, move_and_slide uses velocity, not a motion vector
