### ISSUE TITLE
Isn't it possible for somebody to make a module that supports C++ natively?

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#15094]
The problem is that why must the user always convert their cpp to dll in order for their code to work in the game? Why can't Godot just understand cpp, like unreal engine?

**Comment by MrJustreborn** [comment]
The dll approach with GDNative is good for not compile Godot yourself, just the scripts you wrote.
You can always code directly in C++; The editor is a "Game" written in Godot with C++. When writing in C++ you have to setup a IDE for it (just like you have to with unreal according to there documentation)

**Comment by Raj2032** [comment]
So you are saying that you 'don't' have to convert cpp to dll am I correct?

**Comment by MrJustreborn** [comment]
No you don't HAVE to, you can write your game in C++ and compile it to a single executable.
But the GDNative-way with dll/so/dynlib is easier IMHO. :wink:

**Comment by Raj2032** [comment]
But every single time you want to test out your game, converting your
scripts to dll is going to be pain in the ass though?

**Comment by MrJustreborn** [comment]
When you change something in your C++ code you ALWAYS have to recompile it, regardless which approach you take (GDNative or directly).

**Comment by groud** [comment]
We already answered you before in  #14856 and #14898. Please read again what we told you, it's not necessary to open 3 times the same issue.
