### ISSUE TITLE
Cannot undo adding points to Line2D

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#15096]
**OS/Godot version:**

Antergos x86_64 - 5c63687

**Issue description:**

Expected: Ctrl+Z undoes last point added to Line2D
Happened: it undoes the previous action instead
*Note: undoing points removal works as expected*

**Steps to reproduce:**
1. New Line2D
2. Add a point
3. Undo, expecting that point to disappear
4. The whole node disappears because adding Line2D is undone

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by poke1024** [comment]
Not sure how to reproduce this. Should I be in edit mode while in (2) adding a point? That at least seems to work.

**Comment by Noshyaar** [comment]
@poke1024 Use create line from scratch tool to create points. Undo once and all points disappears. Also you can't move mouse to move the point during creation.

**Comment by poke1024** [comment]
I see. I think the Line2D editor shouldn't be based on the work-in-progress mode we use for the Polygon2D editor. I've changed that in https://github.com/godotengine/godot/pull/15111 now.

**Comment by Noshyaar** [comment]
Fixed by #15111
