### ISSUE TITLE
The debugger doesn't allow to see more than the 100 first array elements

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15109]
Godot 2.1.4, not tested in 3.0

I was debugging a nasty bug in my game, and found out the Godot debugger doesn't allow me to view array elements past the 99th...
I kind of understand why (if it contains 10 000 elements the debugger would freeze), but that's a pretty naive and frustrating behaviour, there must be a way to select the range.

![image](https://user-images.githubusercontent.com/1311555/34392132-9aa1a888-eb4a-11e7-808a-c4d1a473c8fa.png)

**Comment by Geequlim** [comment]
The ArrayPropertyEdit allow you to show a range.
```
var arr = []

func _ready():
	arr.resize(10000)
```
![image](https://user-images.githubusercontent.com/6964556/34406907-88f47ad2-ebf6-11e7-8dac-7a098ff66fcf.png)

**Comment by Zylann** [comment]
Woops I'm blind, didn't realized "page" was doing that, thought it was a property of the array itself
