### ISSUE TITLE
Delete animation in AnimationPlayer doesn't update the tracks

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15100]
Godot 2.1.4, not tested in 3.0

I just removed the last animation of my AnimationPlayer, but all its tracks and keyframes are still shown:

![image](https://user-images.githubusercontent.com/1311555/34383847-9678447e-eb18-11e7-887f-ab09d714843e.png)

**Comment by akien-mga** [comment]
Fixed in the current master branch.
