### ISSUE TITLE
Suggestion: Make clicking on subfolder in folder directly go to said folder

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#15118]
**Godot version:**
3.0 beta 2

**OS/device including version:**
Windows

**Issue description:**
I really dislike that clicking on a subfolder while inside the containing folder throws you back into the resource tree, making me click twice when I should only have to click once. It would make for a much better workflow if clicking on the subfolder directly takes you to its contents rather than booting you back to the resource tree with the subfolder highlighted.

**EDIT:**
Here is a gif showing the exact issue I am talking about. https://i.imgur.com/dX0L5DK.gif

**Comment by volzhs** [comment]
duplicated with #14931 
and fixed by #14912
