### ISSUE TITLE
Tile flickering on tile map when using CanvasModulate

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#15113]
**Godot version:**
Godot 3 b2

**OS/device including version:**
Windows 10.

**Issue description:**
When adding a Canvas Modulate to a scene with a Tile Map, certain tiles will "flicker" as seen in [this video](https://www.youtube.com/watch?v=anrONC1WIxI&feature=youtu.be). There are no issues with the tile map when not using the canvas modulate. The source file for the canvasmodulate can be found [here](https://cdn.discordapp.com/attachments/212250894228652034/395727735118495744/DayNight.cs).

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by mrcdk** [comment]
duplicate of https://github.com/godotengine/godot/issues/9913

**Comment by jonbonazza** [comment]
@mrcdk i wasnt sure if this was a duplicate because I only see the issue when using canvasmodulate node--not without.

**Comment by brainsick** [comment]
Just as a learning exercise, I ported your DayNight.cs to GDScript.  Now, this is apples to oranges, but I do not experience the flicker with this sample project.  Is this sample representative of your issue?  Do you still experience the flicker if you run this sample?

Ubuntu 17.10, Godot 3.0 Beta 2, AMD Radeon R9 Fury.

[TileMapTest.zip](https://github.com/godotengine/godot/files/1590353/TileMapTest.zip)

**Comment by jonbonazza** [comment]
@brainsick I haven'y forgotten about this. I've just been busy with moving and haven't had a chance to try it out.

**Comment by jonbonazza** [comment]
@brainsick so now I am just _really_ confused. I downloaded your project and ran it, it worked fine. I then swapped out your gdscript... err... script for my c# one and again, it worked fine... I then closed your project and reopened mine (that hasn't been touched since I took the attached video and submitted this issue) and re ran it... and it worked fine... O.o Nothing has changed in the project or the code. The only thing that did change is that I have since disconnected and reconnected my monitors (I moved apartments this weekend, so I had to reconnect my desktop), but I don't think that would cause the issue.

**Comment by jonbonazza** [comment]
Hmm interesting... It seems that if I move my character around it starts to happen (though now, the artifacts are different. Rather than entire tiles disappearing, these weird lines appear across the screen) but if my character is just sitting there, there is no issue.

**Comment by brainsick** [comment]
Is this possibly a duplicate of #9913 then?

**Comment by jonbonazza** [comment]
@brainsick very much looks like it might be (now). For whatever reason, I no longer see the flickering "squares" that are portrayed in the video, but instead see these weird lines that look more like what is captured in the other issue. Also, FWIW, removing the DayNight node entirely doesnt seem to help. I'm not sure where the old flickering squares came from or what happened to them, but that much seems to be resolved at least. 

Should we close this ticket for now or leave it open? 

At the very least, I want to present my findings regarding character movement in the other issue because it's odd that it only seems to occur while the character (or I guess maybe the camera?) is moving and if everything is still, the issue doesn't present itself.

**Comment by brainsick** [comment]
@jonbonazza If you're on board with this being the same issue, I would close this one.  I definitely recommend adding a comment to the other issue with any new information.

**Comment by jonbonazza** [comment]
@brainsick hmm now Im not sure it's the same issue... I just tried taking a video of it and while it definitely occurred during filming, it's nowhere to be found in the video. Something is odd here... I wonder if it's related to the NVida GeForce overlay thing?

**Comment by jonbonazza** [comment]
Looks like there is a driver update. Gonna try installing that and disabling the geforce game overlay and see what happens.

**Comment by jonbonazza** [comment]
No dice. :/ Even after a restart, the issue still persists.

**Comment by jonbonazza** [comment]
Oh wow.. the original tile flickering is back too. lol

**Comment by jonbonazza** [comment]
I thinkk this is the same as the other issue though as it even happens when there is no CanvasModulate in the scene. Gonna close this issue for now.
