### ISSUE TITLE
OpenGL2 Support Query

### ISSUE THREAD

**Issue by abhaskumarsinha** [godotengine/godot#15122]
Hello, heroes of Godot Engine. The work you did in Godot 3.0 beta 2nd release is highly impressive.
Most of you are professionals in everything like Scripting, UI, Design and you professionals are quite fast too.

So, I've liked most of the Godot3.0.

But, unfortunately, My PC uses Intel (R) HD Graphics 370M @ 240gz x 2, which doesn't has any official support for OpenGL3.3 / OpenGL3. Unofficial builds of drivers have those support but those are very much buggy and for some reason they doesn't start with my start of Windows. I've to start them each time.

I currently use Mesa3D Software Renderers i.e. Code 'LIBGL_SOFTWARE_ALWAYS=1'.
The Godot runs awesome but in case when materials is assigned, it lags,

So, Godot 3.1 will start with start of 2018, I've following questions to ask -

1. Can I be able to get glossy, mirror, SSS, Depth, Metallic, Albedo, Normal, Emission and other shaders support in Opengl2 version of Godot 3.1?

2. Will PBR and Other Lightning effects be supported in Opengl2 version of Godot 3.1?

3. What will be the limitations that can't be implemented in Opengl2 version of Godot 3.1?

here's my linux side graphics info - (glxinfo | grep "OpenGL") -

```
root@VAIO-PC:~# glxinfo | grep "OpenGL"
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 11.2.2
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 11.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
root@VAIO-PC:~# 
```

**Thanks in Advance, and Wishing Team Godot and Godot, A Happy New Year in Advance!**

**Comment by Calinou** [comment]
That generation of Intel graphics is very slow, and doesn't even run OpenGL 2.X-era games well.

**Comment by abhaskumarsinha** [comment]
@Calinou It's a 5th generation from what I heard, pbr games like NFS MW (OpenGL2.1) runs @ 100 FPS, So, I don't think its older, its just launched in 2010, will be 7 years in 2018. LOL,

But. also have doubt, Unity runs fine using Directx10 in my PC, not sure OpenGL is why unable to give same performance...

Doubts

**Comment by Calinou** [comment]
> It's a 5th generation from what I heard, pbr games like NFS MW (OpenGL2.1) runs @ 100 FPS, So, I don't think its older, its just launched in 2010, will be 7 years in 2018. LOL,

I refer to Ironlake graphics as first-generation (since Sandy Bridge is 2nd generation, Ivy Bridge is 3rd generation, and so on). Also, NFS MW is not PBR, it's a game released in 2005 using Direct3D 9 (and not OpenGL, by the way).

**Comment by abhaskumarsinha** [comment]
@Calinou but NFS MW is OpenGL supported too [NFS MW (WIKI](https://en.wikipedia.org/wiki/List_of_games_with_OpenGL_support)

**Comment by abhaskumarsinha** [comment]
@Calinou We don't need SSS as they are easy to fake, DOF is a bit disappointing but anyway its cool, I like it.

Still one question, "Can OpenGL match Performance and Graphics as DirextX?"
Because Unity runs great, sorry I'm repeating this because I don't understand it. Official OpenGL sourced doesn't help much

**Comment by Calinou** [comment]
> Still one question, "Can OpenGL match Performance and Graphics as DirextX?"

Yes, it can. Note that the AMD Windows drivers are known for worse performance with OpenGL compared to Direct3D, though. This doesn't affect Linux drivers or NVIDIA/Intel hardware.

**Comment by akien-mga** [comment]
Godot 3.1 supports OpenGL 2.1 again, closing.
