### ISSUE TITLE
Object constants are listed on class-level, but can't be used as static constants

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15125]
Godot 2.1.4, not tested in 3.0

I found out that one (and possibly others) constant in Object cannot be used as class-level constant as it appears in the doc, and seems to only be usable as if it was a global-scope one... until you run it.
Is this expected? If it is, it's confusing.

The doc says:
![image](https://user-images.githubusercontent.com/1311555/34417332-3d487a1e-ebf8-11e7-930d-21e35f8a3109.png)

But this is detected as an error:
![image](https://user-images.githubusercontent.com/1311555/34417365-62dd4c14-ebf8-11e7-9ee9-3b3f928c9c67.png)

This doesn't:
![image](https://user-images.githubusercontent.com/1311555/34417376-6f5d2bb2-ebf8-11e7-8ec3-7c4b9fb25c5c.png)

However none of these work when run:
![image](https://user-images.githubusercontent.com/1311555/34420135-1c1e8d50-ec08-11e7-842f-02980eeb54ec.png)
![image](https://user-images.githubusercontent.com/1311555/34420151-3fb9ca0e-ec08-11e7-921c-ff8f694fa3d4.png)

**Comment by mrcdk** [comment]
It also happens on 3.0 master 81d7b01

![https://i.imgur.com/4beE5Lu.png](https://i.imgur.com/4beE5Lu.png)

**Comment by vnen** [comment]
I think it's missing a `VARIANT_ENUM_CAST(ConnectFlags)`.

**Comment by reduz** [comment]
Is this still an issue?

**Comment by akien-mga** [comment]
Accessing `CONNECT_ONESHOT` from within an Object-extending class (e.g. Node2D) works, e.g.:
```
extends Node2D

func ready():
    print(CONNECT_ONESHOT)  # 4
    var obj = Node2D.new()
    print(obj.CONNECT_ONESHOT)  # 4
```
But indeed these constants can't be accessed as static members with `Object.CONNECT_ONESHOT`, contrarily to others like `Image.FORMAT_ETC2_R11`.

**Comment by akien-mga** [comment]
It seems to be specific to Object though, as for example `Object.NOTIFICATION_PREDELETE` fails with the same error as OP, while `Node.NOTIFICATION_PREDELETE` works.
