### ISSUE TITLE
_fixed_process don't work

### ISSUE THREAD

**Issue by MrJustreborn** [godotengine/godot#15129]
**Godot version:**
7f1265b41fc52def42c433e5d324070bc6454d6b

**OS/device including version:**
Manjaro Linux

**Issue description:**
*_fixed_process(delta)* don't get called and there is no *set_fixed_process(true)* function only *set_physics_process(true)* but setting it don't work

**Minimal reproduction project:**
```
func _ready():
	set_physics_process(true)

func _process(delta):
	print("process")

func _fixed_process(delta):
	print("fixed_process")
```

Just *process* gets printed

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by brainsick** [comment]
Shouldn't that be `_physics_process(delta)` instead of `_fixed_process(delta)`?

http://docs.godotengine.org/en/latest/learning/features/physics/physics_introduction.html?highlight=_process#fixed-process-callback

**Comment by MarianoGnu** [comment]
Closing: as @brainsick  says, function has been renamed to `_physics_process(delta)`
