### ISSUE TITLE
Subpixel font rendering issues

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#15124]
**Godot version:**

7f1265b41, clang/llvm build, release_debug

**OS/device including version:**

Arch Linux x86_64

**Issue description:**

Code editor sometimes shows some lines with duplicated pixels on some rows
![image](https://user-images.githubusercontent.com/3120639/34417099-eb7d2672-ebf6-11e7-9d31-b8dd5adcf9fb.png)

**Steps to reproduce:**
Default font settings, all that
Write some code (script I found this on was 56 lines long)
Set window geometry to `1600x843+0+96`
Scroll around until you start to see pixels duplicated (click+drag scroll tends to trigger this better)

**Minimal reproduction project:**

No project, but the script I used that reproduced the issue:
```gd
extends KinematicBody

const MOVE_SPEED = 250
const EPSILON = 0.01

var ray

var following = false
var target
var home_loc
var initial_rotation
var is_home = true

func _ready():
	ray = $RayCast
	home_loc = translation
	initial_rotation = rotation

func _physics_process(delta):
	if !following:
		if ray.is_colliding():
			var col = ray.get_collider()
			if col.is_in_group("player"):
				following = true
				target = col
				is_home = false
	
	# We seperate this to allow following on the same frame
	if following:
		var distance = target.global_transform.origin.distance_squared_to(global_transform.origin)
		if distance > 225:
			following = false
			return_home_step(delta)
			return
		
		var to_move = (target.global_transform.origin - global_transform.origin).normalized() * MOVE_SPEED * delta
		face_and_move(to_move)
	elif !is_home:
		return_home_step(delta)

# Start returning home
func return_home_step(delta):
	var move_vec = home_loc - translation
	
	is_home = move_vec.length_squared() < EPSILON
	if is_home:
		var collision = move_and_collide(home_loc - translation)
		rotation = initial_rotation
		return collision.remainder
	else:
		var to_move = move_vec.normalized() * MOVE_SPEED * delta
		return face_and_move(to_move)

func face_and_move(move_vec):
	rotation.y = atan2(move_vec.x, move_vec.z)
	return move_and_slide(move_vec)
```

My guess is it is a rounding error somewhere

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by vnen** [comment]
Looks like you decreased the zoom, is that right?

**Comment by Silvea12** [comment]
No, standard zoom.

**Comment by vnen** [comment]
It doesn't look like the default settings then, your screenshot has a smaller font than the default. Are you sure you never decreased the zoom? Press Ctrl+0 on the script editor (to reset the zoom) and see if it makes any change.

Example, your screenshot looks like this, which has a decreased zoom:
![godot_2017-12-29_16-20-41](https://user-images.githubusercontent.com/5599796/34444308-5873a766-ecb4-11e7-8d98-5428365de44b.png)

Here's with the default zoom for comparison:
![godot_2017-12-29_16-20-48](https://user-images.githubusercontent.com/5599796/34444307-585750fc-ecb4-11e7-9c27-dc3bc22daf58.png)

I'm not saying this isn't a bug, but I think it *is* related to the zoom.

**Comment by Silvea12** [comment]
I hit ctrl-0 and the text just got thicker. I think my zoom had been very, veeeery slight in that case.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment]
I can't reproduce this. Can anyone? otherwise it should be closed.

**Comment by Silvea12** [comment]
@reduz It appears to have been fixed.
