### ISSUE TITLE
[C#] AnimatedSprite.GetSpriteFrames() sometimes returns an invalid object

### ISSUE THREAD

**Issue by redxdev** [godotengine/godot#15138]
**Godot version:**
3.0 beta2 (mono)

**OS/device including version:**
Windows 10 1709

**Issue description:**
I'm actually unsure if this is specifically a C# issue, as I'm not able to easily reproduce the conditions for this bug. It may be indicative of a larger issue (and at a minimum there is a C# bug related to null pointers).

I have a script that uses some information from `AnimatedSprite.GetSpriteFrames()` in order to time some actions (firing a bullet in this case). This works fine most of the time, but occasionally `GetSpriteFrames()` will return an invalid object. Let me clarify that - it returns a non-null C# object, but the internal pointer to the Godot object seems to be null, so calling any function on the `SpriteFrames` object results in an error. The result is that execution of the script is cancelled and the following error is spammed into the debugger (spam is caused by the failing function being called every frame):

![debugger](https://i.imgur.com/A0Wu6b1.png)

Additionally, trying to `GD.Print()` the result of `GetSpriteFrames()` will print null as the internal pointer is null, even though there is a valid C# object. For the record, I never change the AnimatedSprite's `SpriteFrames` when the game is running.

**Reproducing the error:**

I'm unwilling to post the project publically, but I'm willing to send a minimal project via email or however a dev would like. Unfortunately, I'm not actually sure what causes the issue and a quick attempt at recreating it in a new project fails. I am, however, able to reproduce the issue 100% of the time in the project that exhibits the issue.

**Comment by neikeq** [comment]
Does `AnimatedSprite.NativeInstance` return `IntPtr.Zero`?

**Comment by redxdev** [comment]
Good question. Just checked and it does indeed.

**Comment by neikeq** [comment]
The AnimatedSprite has been freed by the time you call the method.
If that's expected, then the way to check when that happens is with the NativeInstance property rather than just a null check.
This is a shortcut for both: `obj?.NativeInstance != IntPtr.Zero`.

**Comment by redxdev** [comment]
Wait, sorry. I misread your comment and checked `SpriteFrames.NativeInstance`.

`AnimatedSprite.NativeInstance` is fine - it returns a non-zero pointer.

I also want to note that this error happens on multiple nodes _at the same time_. When this error starts to happen, all instances of a specific AnimatedSprite exhibit this behavior.

**Comment by redxdev** [comment]
https://youtu.be/2RRvV_oEJJM

Most of the video is just setup. I'm not sure what actually causes the bug, but the sequence of actions in the video reproduce it 100% of the time (with varying timing). The second time I spawn 3 "enemies", they will shoot at me for a bit and then at some point they will all get stuck in their firing animation. The moment they hit the last frame of that animation is when `GetSpriteFrames()` starts exhibiting the weird behavior (which is why they get stuck in the animation at the end - the code to fire a projectile and reset their animation never gets hit).

**Comment by redxdev** [comment]
I want to additionally note that when this issue is happening and I inspect the instance of the enemy (via the remote scene tab in the editor), the `Frames` property is set properly.

![inspector](https://i.imgur.com/7Zksii1.png)

**Comment by redxdev** [comment]
I wrote a quick script in gdscript to also print out the `frames` property, and it always returns a valid `SpriteFrames` object, even when C# is getting `SpriteFrames` with `IntPtr.Zero` from the exact same `AnimatedSprite` node.
