### ISSUE TITLE
Make this game engine C++ centered.

### ISSUE THREAD

**Issue by Joe23232** [godotengine/godot#15134]
We need C++ in Godot 3.1 straigthtforward, well documented, and above all C++ centered. We need C++ supported as a main, built-in scripting language for game logic (see Unreal)? NOT for native libraries and NOT bindings.

**Comment by NathanWarden** [comment]
I think I understand what you're saying based on your post over at the Polycode project. https://github.com/ivansafrin/Polycode/issues/715

It seems like you want C++ to be the main language and replace scripting languages as being the primary focus and make it C++ instead. If I'm understanding you correctly then it isn't going to happen. While C++ is faster as far as code execution goes, it's also extremely slow to develop with and the costs end up outweighing the benefits. Most of the performance critical code is already in C++.

However, it isn't hard to learn how Godot's nodes work internally. C++ isn't my primary language and I was able to figure it out. So, you can write your entire game by either making your own custom version of Godot, or you can make your own custom modules for your game using GDNative.

**Comment by brainsick** [comment]
I've seen a number of these requests recently and I find them interesting.  It stands to reason that C++ is the most supported language in Godot considering that it's written in it.  A C++ developer working in or on Godot has access to more engine functionality than anything exposed via the supported scripting APIs.

**Comment by haxpor** [comment]
I'm not sure Joe23232 and Raj2032 are the same guy or not. If not, my apology and you can ignore this comment, but if so (as Joe23232 just joined Github on today Dec 29 just to make an issue here, then please read along)

Based on your [past questions mostly about C++ centric](https://github.com/godotengine/godot/issues/created_by/Raj2032), I would kindly suggest to familiar yourself with Godot's direction and usage. I think every tool cannot be fully 100% of individual wants, but community at large is there to be heard and gradually adapt to provide if need.

About why not C++ centered, I would say that Godot itself has put C/C++ at first class citizen already with the benefit of high productivity in-mind via scripting language (GDScript). If they are not care about C++, I don't think they went too far to make 3.0 onwards support flexible way i.e. shared library to integrate with your custom C/C++ code. So "C++ centered" should not be in a question context. As community answered to your board questions so many times, including [this from myself](https://github.com/godotengine/godot/issues/14856#issuecomment-352957845) about C/C++ and its ecosystem in general or specific. I'd see it as information overwhelming and better to move on further from there and not to stress this again and again. If this sounds rude, I don't mean to, but at some points someone has to point this out.

If you want discussion, please see [community](https://godotengine.org/community) and select which channel is the best for you to initiate the topic. Might be Questions & Answers, IRC, or Discord. Those places are better suitable for this kind of discussion, not issues on Github which is intended for reporting bug or real issues so community would see to fix it (they have seen ton of issues already, so we better at first filter some for them). But if you are only want to initiate topics/discussion without serious concern, neither community or here is suitable for that I believe.

**Comment by Dillybob1992** [comment]
GDScript is Godot's bread and butter though. The language is very powerful for its intended usage and underrated. Performance will rarely cause for a concern (over 20,000 lines so far) paired throughout hundreds of scenes, with no issues. The engine already makes writing custom C++ plugins extremely easy for rare cases as well.

Godot is in a nice ease-ability:performance ratio spot for development already, any change to this could be catastrophic

**Comment by Joe23232** [comment]
But at least stop using native library and bindings and simply allow users to have C++ pre configured straight out of the box without having to deal with native libraries, bindings etc.

**Comment by leoddd** [comment]
As you've already been explained, that is already possible.
Just download the Godot source code off of github and code away. Add your own custom nodes and scripts into the engine, compile it and build your project in the editor using your new nodes.
If you don't want to build your own custom version of Godot and instead use the classic Godot interface (to guarantee compatibility with updates and all), that is where a native library comes into play.
You CAN'T use a compiled programming language like C++ without first compiling it to a library file. That is simply how C++ works. You will face this "problem" in every single C++ project you will ever seek out to ask for "C++ centering" in, because that is simply how C++ works. No way around it, C++ cannot be run as executable code without first compiling it to a binary or library, which then has to be linked to your existing binary, which is what "native libraries" are.

**Comment by Joe23232** [comment]
May you please teach me how to use native library?

**Comment by volzhs** [comment]
https://www.google.co.kr/search?q=godot+c%2B%2B

**Comment by Ranoller** [comment]
Make this game engine C++ centered?...... no thanks!

**Comment by groud** [comment]
This question has already been asked several times the few past days, with several and well argued responses. I close this one.
