### ISSUE TITLE
child Camera2D of scene instance crashes the engine/game

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#15137]
**Godot version:**
v3.0.beta.custom_build.2717b7f

**OS/device including version:**
(I strongly believe that specs are not related to the bug)
Windows 10, 64-bit

**Issue description:**
In my level scene I have an instance of player scene, and to that instance I add child Camera2D node. I save the project and can run it normally. Now, to the player scene (the scene itself, not the instanced one) I add another child node. I save the project now and the whole engine crashes. After some trial and error I identify that the engine crashes only when the level scene (the one with player instance and its child Camera2D) is open in the editor. I "fix" the bug by deleting that child node that I added to the player, then deleting Camera2D, then adding child node back (and more if needed), and finally readding the Camera2D.

**Steps to reproduce:**
(all steps are GUI-related, no code is needed)

1. Create a new project like usual.
2. Switch to 2D.
3. Create the main scene (further referenced as "A"), add Node2D as root node, save it.
4. Create another scene (further referenced as "B"), add Node2D as root node, save it. (make sure scenes don't have the same name)
5. In scene A instance scene B and to that instanced scene B add child Camera2D node.
6. Save the project and set scene A as default scene.
7. In scene B add any new child node to the root node.
(the game will work fine up to here)
8. Save the project
8.1 If you try to save the project while scene A is still open in the editor, the engine will crash.
8.2 If you try to save the project while scene A is not open in the editor, you will save the project succesfully. If you try to run, the game will crash (engine still ok). If you then try to open the scene A again, the engine will crash.
9. You cannot run your project anymore since scene A is first thing that loads in the editor, which causes immediate crash.

**Minimal reproduction project:**
[camera-bug-test.zip](https://github.com/godotengine/godot/files/1592420/camera-bug-test.zip)
There are 2 projects, one that cannot run (crashes immediately), and the other one that runs normally and can be used to replicate the bug. Just go to scene B, add a child node (to the root node) and save. (Warning, you won't be able to run the project again after crash!)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by volzhs** [comment]
couldn't reproduce it with attached example.
no crash, no error on terminal.
@wingedadventurer can you still reproduce it?

**Comment by poke1024** [comment]
cannot reproduce this either on macOS and 57efe0bea5e60eb1849c9e42c89205996df819d5

**Comment by wingedadventurer** [comment]
@volzhs yes, I can still reproduce it.

I am using Beta 2 version, and I'm not a GitHub user so I don't know if I'm supposed to compile my own newer version and try it then? I just came to report a bug, that's all, forgive me. 🙂

**Comment by volzhs** [comment]
@wingedadventurer you can get recent build from http://godot3builds.digitecnology.com/ :)

**Comment by wingedadventurer** [comment]
@volzhs thanks, yeah, I can't reproduce it anymore, so it's solved. 🙂 

I will close the issue.
