### ISSUE TITLE
Generalize enums as tagged unions

### ISSUE THREAD

**Issue by TrulyNonstrict** [godotengine/godot#15141]
As per https://github.com/godotengine/godot/pull/6845, GDScript has pattern matching. ML-family languages feature sum types in the form of a "tag" identifying the discriminant of a union. Then, data can be pattern-matched onto a constructor pattern that succeeds if the data has the tag.

OCaml:

    type Type = Tag1 | Tag2 of a_type ... | TagN [of a_type]

    match datum with
    | Tag1 -> ...
    | Tag2 a -> ...
    | Tag2 _ -> ...
    | _ -> ...

GDScript already has enums and tagged unions may be expressed as a generalization of enums. GDScript enums are syntactic sugar for defining constants as increasing natural numbers. (http://docs.godotengine.org/en/stable/learning/scripting/gdscript/gdscript_basics.html) Thus, the tags of the union would be natural numbers, with

    enum {
        Tag1,
        Tag2 of _ _
    }

    var x = Tag2 of 5 "foo"

being equivalent to

    const Tag1 = 0
    const Tag2 = 1
    var x = [1, 5, "foo"]

Attempting to do `Tag1 of 5 "foo"` or `Tag2 of 5` signal an error (wrong amount of values).

. A new pattern type would be added, `pat1 of pat2...patN`, which matches data in the form of `x1 of  x2...xN` where `xN` matches `patN`.

# Workaround
This idea can be worked around by using arrays:

    enum {
        Tag1,
        Tag2
    }

    match [Tag2, datum]:
        [Tag2, var x]:
        ...
- [X] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates. (I searched "sum types," "tagged union," and "discriminated union.")

**Comment by vnen** [comment]
You gave a nice description of *what it is* but I fail to see *how it is useful*. This seems like a natural feature of functional languages, but GDScript isn't a functional language. For instance, the pattern matching functionality was added as a more powerful alternative for the missing switch case (which was requested by many people).

I feel like whatever you use this for could be done in an imperative way (since GDScript is imperative), instead of mimicking how you would do in a declarative language.

**Comment by akien-mga** [comment]
CC @karroffel

**Comment by karroffel** [comment]
I would love to have that feature as I'm missing ADTs all the time when programming in a non-FP (or Rust) language, but I'm with @vnen here actually, it doesn't quite fit GDScript.

Maybe we could add some syntactic sugar for it, but I'm not sure if it's worth it... :(

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/737, as feature proposals are now tracked in the Godot proposals repository.
