### ISSUE TITLE
Incorrect skeletal mesh translation

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#15148]
**Godot version:**
Godot 3.0 7f1265b41fc52def42c433e5d324070bc6454d6b

**OS/device including version:**
macOS 10.12.6, Windows 10 x64

**Issue description:**

Applying translation to a mesh within Skeleton or any of its parent results in unexpected behaviour: 
![translation](https://user-images.githubusercontent.com/2417849/34433401-a82c97e8-ecb1-11e7-980a-2e384e8f1507.gif)

**Steps to reproduce:**

Import this scene to the project, play its animation so that it's fallen and try translating it: [Cyllinders.tscn.zip](https://github.com/godotengine/godot/files/1592834/Cyllinders.tscn.zip)

This didn't occur before recently. I suspect 7d0cabe9d30238ff2d9a05cecbbc22a45ce71ac1 might be the cause.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by endragor** [comment]
a54e3f72ce9d2427e413aa8fdf9633a49027747b fixed the issue in editor, but moving the same node from script still causes this: 
![scene](https://user-images.githubusercontent.com/2417849/34439330-abc76896-ecdf-11e7-9fa7-97ae01b6dbd9.gif)

Can be reproduced by running main scene in this project: [project.zip](https://github.com/godotengine/godot/files/1593272/project.zip)

**Comment by capnm** [comment]
Hmm, seems to be ok here.
linux 99960d929435423b25e9bfb55051af60edbfcca9

![screen2017-12-29 23-05](https://user-images.githubusercontent.com/4047289/34448394-239717b0-eced-11e7-9973-6dd86300e716.gif)

**Comment by endragor** [comment]
@reduz made several fixes yesterday that address this and the sample project now runs fine, but after the fixes I started getting this in the actual game:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
* frame #0: 0x00000001019361a6 godot.osx.tools.64`Vector<Skeleton::Bone>::operator[](this=0x00000001318b6f50, p_index=0) at vector.h:137
frame #1: 0x00000001019382ff godot.osx.tools.64`Skeleton::_notification(this=0x00000001318b6c70, p_what=29) at skeleton.cpp:163
frame #2: 0x000000010193beb7 godot.osx.tools.64`Skeleton::_notificationv(this=0x00000001318b6c70, p_notification=29, p_reversed=false) at skeleton.h:41
frame #3: 0x00000001022cc9b2 godot.osx.tools.64`Object::notification(this=0x00000001318b6c70, p_notification=29, p_reversed=false) at object.cpp:923
frame #4: 0x000000010151d68f godot.osx.tools.64`SceneTree::flush_transform_notifications(this=0x000000011c52b4d0) at scene_tree.cpp:140
frame #5: 0x0000000101520fab godot.osx.tools.64`SceneTree::idle(this=0x000000011c52b4d0, p_time=0.0336139984) at scene_tree.cpp:511
frame #6: 0x000000010003f87b godot.osx.tools.64`Main::iteration() at main.cpp:1728
frame #7: 0x000000010000d62a godot.osx.tools.64`OS_OSX::run(this=0x00007fff5fbfe698) at os_osx.mm:2003
frame #8: 0x00000001000134cc godot.osx.tools.64`main(argc=3, argv=0x00007fff5fbff8c0) at godot_main_osx.mm:90
frame #9: 0x00007fff9e70d235 libdyld.dylib`start + 1
```

**Comment by reduz** [comment]
Closing as this is most likely fixed now
