### ISSUE TITLE
_input events slow 

### ISSUE THREAD

**Issue by bnpfeife** [godotengine/godot#15146]
**Godot version:**
f11a1385054376bdc4cc01e6aa20d63508a5e6d4

**OS/device including version:**
Linux 4.14.8-1-ARCH
Mesa 17.3.0
Xorg 1.19.5-1

Intel Core I7-2600
AMD Radeon RX-480
16 GiB Ram

**Issue description:**
When using the "_input" function to process events, there is a noticeable delay when vsync is enabled. The delay is greater than the "delta" passed to "_process" and "_physics_process". If vsync locks the framerate to 60Hz, "delta" is around ~0.017s.  When handling InputEventMouseMotion, "_input" is only polled around ~0.033s. This introduces perceptible stuttering when using the mouse to control a first-person camera.

Currently, I found a workaround by forcing 60 fps (project settings) when enabling vsync. I presume that monitors with different refresh-rates would use different values.

**Edit:**
I used the following code to measure the time between function calls:
```
onready var last = OS.get_ticks_msec();
onready var now = OS.get_ticks_msec();

func _input(event):
    if event is InputEventMouseMotion:
        last = now;
        now = OS.get_ticks_msec();
        print((now - last) / 1000.0);
```

- [X] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by Dillybob1992** [comment]
Well, not sure if this is a bug. The delay is just the delay between mouse motion movements at the physical mouse/wrist level. To do pixel perfect movements with no stutter (that is controlled by a mouse's position), it'd have to updated in `_process`

**Comment by bnpfeife** [comment]
Thanks for the suggestion. I'm now retrieving the mouse position whenever `_process `is called on the object. It still seems strange to me. I believe that my mouse polls much faster than 30Hz at the physical level. I'm not savvy of how the hardware works, so I could also be wrong. =P

**Comment by poke1024** [comment]
From Godot's source code, it looks as if `_input` basically gets called every time the operating systems delivers an input event. This shouldn't be affected by vsync settings. Strange.

**Comment by bnpfeife** [comment]
I wonder if something (like a mutex/condition_variable) is blocking event handling when it shouldn't be. I'm not familiar enough with Godot's source code to say. I'll boot into Windows tomorrow to see if this only affects Linux/only my computer.

**Comment by poke1024** [comment]
Yes, that would be interesting I guess.

**Comment by bnpfeife** [comment]
Okay, so I did some investigating. I found out that this only happens when DRI3 is used on Linux. I forced Xorg back to DRI2 and "_input" updates at the current framerate. This fixes the stuttering issue. 

I also found that a workaround by adding these lines:
```
1795     int target_fps = Engine::get_singleton()->get_target_fps();                 
1796     if (target_fps > 0) {                                                       
1797         uint64_t time_step = 1000000L / target_fps;                             
1798         target_ticks += time_step;                                              
1799         uint64_t current_ticks = OS::get_singleton()->get_ticks_usec();         
1800         if (current_ticks < target_ticks) OS::get_singleton()->delay_usec(target_ticks - current_ticks);
1801         current_ticks = OS::get_singleton()->get_ticks_usec();                  
1802         target_ticks = MIN(MAX(target_ticks, current_ticks - time_step), current_ticks + time_step);
1803+    } else {
1804+        OS::get_singleton()->delay_usec(1000L);
1805+    }
```

I am unsure if it should be added because it seems like a DRI issue, but I think that most AMD/Intel GPUs are using DRI-3 by default.

**Comment by Chaosus** [comment]
> "This was superseded by the jitter fix, so closing" 
by reduz in #15159
so I've close it, because I guess its fixed, feel free to ask for reopen if it still happens
