### ISSUE TITLE
Play editor button fails to launch my app

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#15147]
Godot 3.0.
When I use the play button (f5) my app boots up, I see the splash screen then it terminates.
Yet when I use the Play scene (f6) button my app boots up fine.

I have noticed the console shows some unusual errors:

ERROR: _load: No loader found for resource: res://en
   At: core/io/resource_loader.cpp:185.
ERROR: start: Failed loading scene: res://en
   At: main/main.cpp:1605.

these only show up when I load the game using f5. I am wondering if it is trying to load the wrong scene.
my main_scene is set to: res://Prefab/UI/Splash.tscn (which is what I have loaded when I press f6)

**Comment by supagu** [comment]
I would debug this myself, but I do not know how to attach the qt debugger to my app as I only have like 2 seconds before it crashes! If anyone has some tips on how to attach the debugger would be great. I know visual studio used to have some "wait for debugger to be attached" command, I am unsure if linux has something similar...

**Comment by bojidar-bg** [comment]
Would be nice if some minimal example project exhibiting the issue is attached.

About the debugger, can you try cd-ing to the project's directory then running `gdb path-to-godot-debug-exec`?
You might have to add some breakpoints via `break main/main.cpp:1605` or similar. To actually start godot, you would give it `run`. When it hits the breakpoint, you might use `p <expr>` to see the value of some c++ expression, `bt` to get the callstack, or `continue` to have it continue.

**Comment by djrm** [comment]
you should put an extension to your 'en' resource, but i had this problem before, the editor fails to report these kind of problem, and some are actually really hard to solve, like the recent change from `shd` to `res`, turned one of my scene into an inconsistent scene which i cant modify from the editor and no error is reported, however i cant launch the project with that scene enabled.

**Comment by supagu** [comment]
Okay, I have made some progress here. Godot is setting the command line (when I use F5) to:
**--path /home/fabian/Projects/TrainsAndThings/Source --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 6888 --position 128,240 -lang en -map -Test**

now if I try to run my game with the command line:
**-lang en -map -Test**

This is where things go wrong. In main.cpp:1192
game_path is set to "en". So it tries to load the wrong default scene.
