### ISSUE TITLE
Node visibility toggle assertion failure when clicked.

### ISSUE THREAD

**Issue by Yukitty** [godotengine/godot#15158]
**Godot version:** 3.0 Beta 2 Classical, Win64

**OS/device including version:** Windows 7 Home Premium, Service Pack 1

**Issue description:** Clicking node visibility button in the scene editor's tree on the exact farthest right pixel produces an assertion error message, instead of toggling visibility. The button still displays going down while clicked, but does not change its icon nor produce any other effect. This is a minor failure and does not result in a crash or other lasting consequences. The exact error message I am seeing is `editor\scene_tree_editor.cpp:50 - Condition ' !item ' is true.`

**Steps to reproduce:** Open any existing or new project. Add any type of node in any scene. Click the visibility toggle button to hide/show the node. Move the mouse to the right by a few pixels and click again, until you are clicking on the (normally invisible) exact edge of the button. Instead of toggling when clicked, the error message now appears.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by DualMatrix** [comment]
Still relevant in master.

**Comment by KoBeWi** [comment]
I will close it in favor of #27580, because it's the same issue and has a linked PR.
