### ISSUE TITLE
Multiple instanced GI Probes do not blend on overlap.

### ISSUE THREAD

**Issue by lehthanis** [godotengine/godot#15164]
**Godot version:**
3.0 self-compiled 12-27-2017

**OS/device including version:**
Built and tested on Windows 10 with Nvidia Quadro K5200

**Issue description:**
Trying to create level design workflow using multiple overlapping GI Probes for small internal areas.  Cannot get edges of GI Probe or overlapped GI Probes to blend properly.

**Steps to reproduce:**
collada dae rooms imported as inherited scenes and saved as asset scenes.
asset scenes instanced into level scenes, GI Probes added to these level scenes and baked.
Game level created, and instances of level scenes placed along with environment and directional light.
When GI Probes brought in from level scenes overlap, the areas don't blend smoothly.

**Minimal reproduction project:**
[GIOverlap.zip](https://github.com/godotengine/godot/files/1593427/GIOverlap.zip)
![giprobeoverlap](https://user-images.githubusercontent.com/4234630/34441115-b46650e6-ec87-11e7-96f3-ff863c092b1e.jpg)

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

EDIT:  Sorry about the light leaks...I did not model exterior geometry nor did I tweak values. All settings are pretty much default settings for clarity.

**Comment by lehthanis** [comment]
Use left mouse button to move camera in-game and WASD to move through level.

**Comment by lehthanis** [comment]
If someone could verify the project, I'd appreciate it...I tried to test the project on my linux machine and it wouldn't load.

**Comment by lehthanis** [comment]
[GIOverlap.zip](https://github.com/godotengine/godot/files/1593729/GIOverlap.zip)

Here's an updated project that has solid exterior walls on the room models now.  Blend file is included.  Also, adding exterior walls and making the rooms solid do not stop ceiling light leaks.  Should that be a separate issue?  The docs say: A small amount of light leaking can occur if the level is not carefully designed. this must be artist-tweaked. Are there any guidelines on what kind of tweaking is required for this?

**Comment by Ace-Dragon** [comment]
I believe the light leaks are something that's going to be tackled for version 3.1 (according to Reduz). Though I don't think it should stop anyone from making a patch if they want the limitation lifted earlier.

Regarding the lack of blending, I do agree that there should be a parameter (for version 3).0 that would allow the user to set a blend distance (it would allow a workflow with multiple GI probes, which in turn would mean optimized scenes due to only needing lower resolutions, and in turn perhaps even allow culling for GI calculations).

**Comment by lehthanis** [comment]
@Ace-Dragon reduz in chat said the GI Probes should already blend in overlap and if they aren't, it's a bug and he asked me to put this together and open this issue. I agree though.

**Comment by reduz** [comment]
@Ace-Dragon Light leaks can be mitigated but cant be completely resolved using the approach in GIProbe, so best is to simply create geometry where leaks will be less visible. Alternatively I was considering supporting a mixed baked lightmap for diffiuse and GIProbe for voxel reflections approach.
