### ISSUE TITLE
Executable run the project if in the same forlder

### ISSUE THREAD

**Issue by mhdchehade** [godotengine/godot#15165]
**Godot version:**

2.1.4

**OS/device including version:**

ubuntu 16.04

**Issue description:**

when there is engine.cfg in the same folder as the godot executable or in the parent directory, godot attempt to run the project.

**Steps to reproduce:**
put the executable in the same directory of the project and open it.

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by vnen** [comment]
Not a bug, it is intended to work this way.

**Comment by Noshyaar** [comment]
Also, duplicate of #9020, #7764.
