### ISSUE TITLE
TextEdit's initial size is overly small

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15163]
**Godot version:**
master:  2de7069

**Issue description:**
The initial size when instancing a TextEdit node is 6x6. While this is the minimal size of the node, it would be better if its initial size to be at least the same of the base Control node, 40x40.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by akien-mga** [comment]
Fixed by #15592.
