### ISSUE TITLE
Export target for Ubuntu Mobile / Jolla SailfishOS?

### ISSUE THREAD

**Issue by poVoq** [godotengine/godot#1516]
Both are similar new mobile platforms using qt/qml and are quite close to standard gnu/Linux.

For Ubuntu Touch see here: https://developer.ubuntu.com/en/start/

HTML5 would probably work as on FirefoxOS, but native binaries would be awesome.

**Comment by reduz** [comment]
not a priority at all, but contributions are welcome

**Comment by poVoq** [comment]
I see, well hopefully someone will do it.

Here is a previous discussion on the forum I just found for reference: http://www.godotengine.org/forum/viewtopic.php?f=12&t=1021

**Comment by slapin** [comment]
+ n900

**Comment by slapin** [comment]
I mean Nokia N900

**Comment by akien-mga** [comment]
I guess to get those implemented we'd need to have support for Wayland and Mir, both for ARM and x86 architectures.

**Comment by slapin** [comment]
I think X11 is enough for now.

Anyway, if one will do n900 version (including editor!!!) I would be very
happy.

**Comment by akien-mga** [comment]
Though I agree supporting those targets would be nice, this issue has not gathered a lot of interest and is mostly forgotten, so I'll close it to let us focus on current issues in the tracker.

Note that WIP support for SailfishOS is done in #9435.
