### ISSUE TITLE
RichTextLabel combined with set_text

### ISSUE THREAD

**Issue by Tzoop** [godotengine/godot#15176]
Godot version 2.1.4.stable.official
Windows 7Ultimate SP1

**Issue description:**
i am not really sure if this an issue, or if maybe my script or pc causes the problem:
get_node("RichTextLabelName").set_text(String(var))
worked when i started the game inside godot, but when i built it to an exe, it stopped working (see attached png / link)
SCRIPT ERROR: _process: Invalid call. Nonexistent function ´set_text´ in base ´RichTextLabel´.

**Steps to reproduce:**
it happened everytime when i built the project and ran the executable, so i changed the code, now with clear and add_text it is working.

( both var for left and right score are set to 0 when they are created and they increase by one when the other side / player scores)

i do not attach the project, because it is from a udemy tutorial (Godot : Beginner to Advanced - Complete Course)  i am doing atm.

screenshot:
![pong_set_text_rich_text_label](https://user-images.githubusercontent.com/6698415/34445836-c3e2bc18-ecd6-11e7-9e9a-79469601b6a9.png)

this screenshot shows both versions. only the pasted code is different.

**Comment by bojidar-bg** [comment]
You probably have mismatched export templates version. `set_text` was added in 2.1.4, make sure yours aren't from 2.1.3.

**Comment by Tzoop** [comment]
Yes, that was the problem. Thank you for the help. I ve now added the 2.1.4 export templates, now it works fine, ty much
