### ISSUE TITLE
Vertex shaders leaves a black mesh at the original location

### ISSUE THREAD

**Issue by nounoursheureux** [godotengine/godot#15177]
**Godot version:**
Tried both on latest master (99960d929435423b25e9bfb55051af60edbfcca9) and the beta 2.

**OS/device including version:**
I tested it on two Linux machines (1 AMD GPU, 1 Nvidia) and encountered the same behavior.

**Issue description:**
I tried to use a vertex shader and:
* it works, which means I can modify the vertices as I want
* but it leaves a black mesh at the location of the "unmodified" mesh:
![2017-12-29-225239_1600x900_scrot](https://user-images.githubusercontent.com/6280095/34448126-a4a2a9f6-ece2-11e7-9fa4-49e33ba8dba0.png)

I tried it with a plane, a cube, and tried to import a mesh and they all had the same issue.

**Steps to reproduce:**
* Create a new scene
* Add a MeshInstance (a simple cube for example).
* Add a ShaderMaterial:
```c
shader_type spatial;

void vertex() {
	VERTEX.x += 4.0;
}
```
now you should see both the translated mesh and a black mesh at the original location.

**Minimal reproduction project:**
[test_vshader.zip](https://github.com/godotengine/godot/files/1593931/test_vshader.zip)

**Comment by Astr01d** [comment]
confirming on windows beta2

![screenshottu](https://user-images.githubusercontent.com/32207106/34456974-5e00f29c-eda4-11e7-9262-60c64d27f602.PNG)
