### ISSUE TITLE
Exported project linked against GDNative failed to run

### ISSUE THREAD

**Issue by haxpor** [godotengine/godot#15183]
**Godot version:**
Godot Beta 2 official

**OS/device including version:**
macOS 10.13 (17A365)

**Issue description:**
I successfully created a C++ custom module and tested it thoroughly. It runs fine via editor. But when I decide to export it although it successfully exports. It fails to run and show no window.

What are the steps necessary to prepare to export for project that linked with GDNative (in this case C++ custom module)? Do I have to statically compile Godot engine with that module only once when release or export? 

**Steps to reproduce:**
* Create a C++ custom module
* Integrate custom module to Godot
* Check everything is fine in editor
* Export to macOS platform
* Run the output `.app` file.

**Minimal reproduction project:**
[TestGDNative3.0-beta2-4.zip](https://github.com/godotengine/godot/files/1594167/TestGDNative3.0-beta2-4.zip)

In the project, I include everything you need. You just try to export the project.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by haxpor** [comment]
Ok, this error related to #15188 
I have to rename project name to **not** include dot, then it exports and can be ran successfully.

But another problem still kicks in. I modified the code to show sprite when it detects that custom module has method and its one of method return correctly.

```GDScript
extends Node

onready var sl = preload("res://simple_library/simple_library.gdns").new()

func _ready():
	print(sl.method("test"))
	print(sl.method(1))
	print(sl.has_method("test_void_method"))
	
	if sl.has_method("test_void_method") && sl.method("test") == "test":
		get_node("Sprite").visible = true
```

Whenever I run in editor, it works fine, but **not** when I run on executable file `.app`. The latter case doesn't show the sprite.

I included an updated testing project: [TestGDNative3.0-beta2-4 2.zip](https://github.com/godotengine/godot/files/1594325/TestGDNative3.0-beta2-4.2.zip) (no worry about the name of project directory which includes "dot", I've renamed the project via Godot launcher to not include one.

**Comment by bruvzg** [comment]
IIRC static linking is required for iOS, library export is implemented for Android only.

Manually copying .dylib to Resources folder works.

![finder](https://user-images.githubusercontent.com/7645683/34454426-e517b7ce-ed73-11e7-9c14-1b18667fda90.png)

[Same bug on Windows](https://github.com/godotengine/godot/issues/11441), [Android GDNative library export PR](https://github.com/godotengine/godot/pull/13130).
