### ISSUE TITLE
Gltf importer doesn't import skeleton(s) correctly

### ISSUE THREAD

**Issue by fire** [godotengine/godot#15181]
**Godot version:**
Patched version of 99960d929435423b25e9bfb55051af60edbfcca9

**OS/device including version:**
gtx 1080. I don't think driver versions are related.

**Issue description:**
Gltf2 skeletons don't import correctly. It also breaks my gltf2fbx workflow.

License: Creative Commons Attribution
[stepladder.zip](https://github.com/godotengine/godot/files/1594031/stepladder.zip)

TheDrone (https://sketchfab.com/thedrone)

https://sketchfab.com/models/7ece1ee1b602436dbcfb77e4f58ba8e5# (See the animation playback online)

**Steps to reproduce:**

1. Import gltf2 by placing in a folder inside of the project
2. Play the animation. See that is is scaled incorrectly.
3. ![godot windows opt tools 64_2017-12-29_15-53-24](https://user-images.githubusercontent.com/32321/34449724-6d318bfe-ecb0-11e7-9624-b7697ecaa0d9.png)

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by fire** [comment]
4. Even if you scan the entire root to .01 xyz. The skeleton is incorrect.

**Comment by fire** [comment]
[gltf2_demonstration_project.zip](https://github.com/godotengine/godot/files/1594049/gltf2_demonstration_project.zip)

**Comment by fire** [comment]
Trialing https://github.com/godotengine/godot/commit/a8a3d5c8356b96064caa833993e0e1c36bdc8b1f

**Comment by fire** [comment]
https://www.youtube.com/watch?v=_OWce6kJRJ0 I had to rescale xyz to 0.1 and have a 90 rotation, but the bones animation seems correct.

**Comment by fire** [comment]
@RandomShaper https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly This model fails to be imported in gltf2. Reduz said to ping you.

**Comment by fire** [comment]
@reduz Seems to be related to https://github.com/KhronosGroup/glTF-Sample-Models/issues/83#issuecomment-334140006

**Comment by fire** [comment]
Here's a sample project. 
[Test Gltf2.zip](https://github.com/godotengine/godot/files/1874172/Test.Gltf2.zip)

It is based on https://github.com/mrdoob/three.js/issues/11644

https://i.imgur.com/o6cg6oq.png

**Comment by fire** [comment]
```
--- a/editor/import/editor_scene_importer_gltf.cpp
+++ b/editor/import/editor_scene_importer_gltf.cpp
@@ -1723,6 +1723,9 @@ void EditorSceneImporterGLTF::_generate_bone(GLTFState &state, int p_node, Vecto
 			skeletons[i]->get_parent()->remove_child(skeletons[i]);
 			p_parent_node->add_child(skeletons[i]);
 			skeletons[i]->set_owner(owner);
+			Transform parent_inverse = Object::cast_to<Spatial>(skeletons[i]->get_parent())->get_transform().affine_inverse();
+			Skeleton *skeleton = Object::cast_to<Skeleton>(skeletons[i]);
+			skeleton->set_transform(skeleton->get_transform() * parent_inverse);
 		}		
 	}
```

I noticed that doing this for the above Test Gltf2 project it gives the correct animation. Although the entire scene is shrunk by 100.

```
+			Transform parent_inverse = Object::cast_to<Spatial>(skeletons[i]->get_parent())->get_transform().affine_inverse(); 
```

This line should be getting the parent's global transform but I ran into a problem getting it.

Hope this helps.

**Comment by fire** [comment]
https://drive.google.com/a/chibifire.com/uc?id=1iS5JUv5SkuMltYxtluWteBH7tgD6bWl_

This is the dae scene of the above project if it helps for comparison.

**Comment by fire** [comment]
```c++
--- a/editor/import/editor_scene_importer_gltf.cpp
+++ b/editor/import/editor_scene_importer_gltf.cpp
@@ -2069,6 +2069,16 @@ Spatial *EditorSceneImporterGLTF::_generate_scene(GLTFState &state, int p_bake_f
 	for (Map<Node *, Skeleton *>::Element *E = state.paths_to_skeleton.front(); E; E = E->next()) {
 		MeshInstance *mi = Object::cast_to<MeshInstance>(E->key());
 		ERR_CONTINUE(!mi);
+		for (int i = 0; i < skeletons.size(); i++) {
+			//get global transform
+			Spatial *node = Object::cast_to<Spatial>(skeletons[i]);
+			Transform global = Transform();
+			while (node != nullptr) {
+				global = global * Object::cast_to<Spatial>(node)->get_transform();
+				node = Object::cast_to<Spatial>(node->get_parent());
+			}
+			mi->set_transform(global);
+		}
 		mi->set_skeleton_path(mi->get_path_to(E->get()));
 	}
```

This code works for the above project and the ladder project on sketchfab. https://sketchfab.com/models/7ece1ee1b602436dbcfb77e4f58ba8e5#

**Comment by fire** [comment]
```c++
--- a/editor/import/editor_scene_importer_gltf.cpp
+++ b/editor/import/editor_scene_importer_gltf.cpp
@@ -2069,6 +2069,15 @@ Spatial *EditorSceneImporterGLTF::_generate_scene(GLTFState &state, int p_bake_f
 	for (Map<Node *, Skeleton *>::Element *E = state.paths_to_skeleton.front(); E; E = E->next()) {
 		MeshInstance *mi = Object::cast_to<MeshInstance>(E->key());
 		ERR_CONTINUE(!mi);
+		for (int i = 0; i < skeletons.size(); i++) {
+			Spatial *node = Object::cast_to<Spatial>(skeletons[i]);
+			Transform global = Transform();
+			while (node != nullptr) {
+				global = global * Object::cast_to<Spatial>(node)->get_transform();
+				node = Object::cast_to<Spatial>(node->get_parent());
+			}
+			mi->set_transform(global);
+		}
 		mi->set_skeleton_path(mi->get_path_to(E->get()));
 	}
```

Better version of the code.

**Comment by fire** [comment]
```c++
--- a/editor/import/editor_scene_importer_gltf.cpp
+++ b/editor/import/editor_scene_importer_gltf.cpp
@@ -2069,6 +2069,13 @@ Spatial *EditorSceneImporterGLTF::_generate_scene(GLTFState &state, int p_bake_f
 	for (Map<Node *, Skeleton *>::Element *E = state.paths_to_skeleton.front(); E; E = E->next()) {
 		MeshInstance *mi = Object::cast_to<MeshInstance>(E->key());
 		ERR_CONTINUE(!mi);
+		Spatial *node = Object::cast_to<Spatial>(E->value());
+		Transform global = Transform();
+		while (node != nullptr) {
+			global = global * Object::cast_to<Spatial>(node)->get_transform();
+			node = Object::cast_to<Spatial>(node->get_parent());
+		}
+		mi->set_transform(global);
 		mi->set_skeleton_path(mi->get_path_to(E->get()));
 	}
 
```

Better version of the code.

**Comment by RandomShaper** [comment]
Could you try your solution with this one, please?
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedFigure/glTF

**Comment by fire** [comment]
It doesn't work. Note the gltf doesn't open in https://github.com/pissang/clay-viewer though.

**Comment by fire** [comment]
Trying to take raw dae and reexporting it as gltf2. https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/sourceModels/RiggedFigure/RiggedFigure.dae

I tried opening the dae in modo and exporting it as gltf2. Noticed that the animations don't play in modo and the exported scene lacks anims.

I tried opening the dae in blender and hit animate. The animation played, but exporting as fbx and opening it in modo or clay viewer failed with animations.

**Comment by fire** [comment]
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedSimple Works in both patched and master.

**Comment by fire** [comment]
No idea what is happening. Have to do something else now.

**Comment by RandomShaper** [comment]
Thanks. So RiggedFigure doesn't work in Godot even with your patch. Am I right?

**Comment by fire** [comment]
@RandomShaper Tried with EmaSimpleSkin.dae converted to gltf2 using modo. 

https://i.imgur.com/JUvd5bz.png

Sample model was from https://github.com/mrdoob/three.js/issues/11644

**Comment by RandomShaper** [comment]
This issue hasn't changed after #18032, right?

**Comment by fire** [comment]
Let me try it on master.

**Comment by RandomShaper** [comment]
Thanks. It was just to be sure there's still an issue to investigate.

**Comment by fire** [comment]
Works as of 5b70ad9d34d2777e3abd0a13118442eb132aff70
