### ISSUE TITLE
set_auto_accept_quit() doesn't work on android

### ISSUE THREAD

**Issue by Solvero** [godotengine/godot#15189]
**Godot version:**
Godot v3.0.beta.build2

**OS/device including version:**
Majaro Linux and Android 4.4.4

**Issue description:**
set_auto_accept_quit(false) doesn't work after exporting to android.
Same code works well with Godot v2.1

**Steps to reproduce:**
1. Create node with this code:
```gdscript
func _ready():
	get_tree().set_auto_accept_quit(false)
```

2. Export app to android phone
3. Press "Back" button
    Application shouldn't quit.

**Minimal reproduction project:**
[TestNotification.zip](https://github.com/godotengine/godot/files/1594310/TestNotification.zip)

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by volzhs** [comment]
I think it's related to `quit on go back` option.
![screenshot from 2017-12-30 21-03-38](https://user-images.githubusercontent.com/8281454/34454024-08c36494-eda5-11e7-8927-c33ffff7b255.png)

`set_quit_on_go_back()` is not bound to gdscript yet though.

**Comment by Solvero** [comment]
Thanks.
I have unmarked this flag and it seems to work as I expected.
That is: pressing back button shows "popup" with exit button, instead of closing app.
