### ISSUE TITLE
Osx Yosemite crashes that seem related to audio driver

### ISSUE THREAD

**Issue by vichug** [godotengine/godot#1519]
hi,
i tried to install Godot, first the latest stable osx build, then i compiled from sources ; and i have occasional crashes that seem to be related to audio driver : the last line in the crashed thread reads 
> 0   godot.osx.tools.32.app        	0x0145ad91 AudioServerSW::_thread_func(void*) + 81

**Comment by vichug** [comment]
(i mean, in the crashlog.)
I am using an external soundcard (motu ultralite mk3 hybrid) so maybe this is related, i don't know. 
The crashes occured in both versions of godot application.

**Comment by akien-mga** [comment]
Can you still reproduce this issue?

**Comment by vichug** [comment]
sorry - seeing that very late, and honestly i don't know, and i'm unlikely to retry, as i got rid of some stuff which i'm unwilling to reinstall :s (namely LinuxSampler, because it is not actively maintained on OSX and seemed to install some libraries in a place OSX doesn't deem as correct.)

**Comment by akien-mga** [comment]
Closing then as it will be hard to reproduce, and thus to fix. Feel free to reopen or open another issue if you end up experiencing it again.

**Comment by vichug** [comment]
fair enough !
