### ISSUE TITLE
Mono Homebrew is not being used

### ISSUE THREAD

**Issue by Kitefr** [godotengine/godot#15196]
**Godot version:**
Godot 3.0 beta 2

**OS/device including version:**
macOS 10.13

**Issue description:**
Godot cannot start if mono version has been installed with homebrew.
After Launching the application, it close automatically and silently.
Need to go to `mono_logs` to understand what is wrong.

**Steps to reproduce:**
Install Homebrew
Install mono `brew install mono`
Download Godot 3.0 beta 2
Launch the application.

**Minimal reproduction project:**
None

- [X] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Mono Logs**
```
Config attempting to parse: '/Library/Frameworks/Mono.framework/Versions/5.4.1/etc/mono/config'. (in domain Mono, info)
Config attempting to parse: '/Users/yannschmidt/.mono/config'. (in domain Mono, info)
process_set_name: using [(null)] as prog name (in domain Mono, debug)
mono_w32handle_new: create Process handle 0x100 (in domain Mono, debug)
Assembly Loader probing location: '/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/4.5/mscorlib.dll'. (in domain Mono, info)
```

**Comment by bruvzg** [comment]
#13726 and #13355 duplicate?

Try setting `MONO_PATH` environment variable to `/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/`.

**Comment by Kitefr** [comment]
I uninstalled the Homebrew version to install the version downloaded from the official website in DMG. I'll try to reinstall the homebrew version later to test it. Thank you.
