### ISSUE TITLE
Vertex shader and rendering passes

### ISSUE THREAD

**Issue by leon196** [godotengine/godot#15197]
**Godot version:**
Godot v3.0.beta.build2

**OS/device including version:**
Windows 10 with a NVIDIA GeForce GTX 1070

**Issue description:**
Modifying position in a vertex shader does not change the shadow pass and other depth related passes.
And when shadows and post processing are disabled, there is still an unmodified mesh.
How to bypass vertex shadow casting ?
How to manage rendering passes ?

With shadows:
![60](https://user-images.githubusercontent.com/2514652/34456378-a4b2ccf2-ed94-11e7-88b4-c162af19efea.PNG)

Without shadows:
![61](https://user-images.githubusercontent.com/2514652/34456380-b8a4433a-ed94-11e7-94bd-312a7f6b7d51.PNG)

**Comment by nounoursheureux** [comment]
May be related to #15177 ?

**Comment by leon196** [comment]
Indeed ! I'm closing this duplicate issue
