### ISSUE TITLE
atomic_conditional_increment on iOS

### ISSUE THREAD

**Issue by poke1024** [godotengine/godot#15195]
**Godot version:**
Godot 3.0 beta

**OS/device including version:**
macOS 10.13 / iOS 11

**Issue description:**
Not sure if `atomic_conditional_increment` on iOS (`platform/iphone/platform_recount.h`) is still used or obsolete; if not used, it should be removed, I guess. If it's in use, there are two issues:

(1) it contains a race condition and should use the same loop mechanism that the other platform implementations of `atomic_conditional_increment` use
(2) The OSAtomic API it uses is deprecated; Apple suggests moving to the C++11 atomic API (https://opensource.apple.com/source/libplatform/libplatform-125/include/libkern/OSAtomicDeprecated.h.auto.html)

Now if Godot used C++11, this should become:

```
#include <stdatomic.h>

inline int atomic_conditional_increment(volatile int *v) {
	ERR_FAIL_COND_V(!atomic_is_lock_free(v), 0);
	while (true) {
		int tmp = atomic_load(v);
		if (tmp == 0)
			return 0; // if zero, can't add to it anymore
		if (atomic_compare_exchange_strong(v, tmp, tmp + 1))
			return tmp + 1;
	}
}
```

If this is still needed, and we cannot move to C++11, we have a problem, I guess.

We can fix the race like this, but API will go away:

```
inline int atomic_conditional_increment(volatile int *v) {
	ERR_FAIL_COND_V(((size_t(v)) & 3) != 0, 0); // aligned?
	while (true) {
		int tmp = OSBitOrAtomic(0, v);
		if (tmp == 0)
			return 0; // if zero, can't add to it anymore
		if (OSCompareAndSwap(tmp, tmp + 1, v))
			return tmp + 1;
	}
}
```

**Steps to reproduce:**

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by Calinou** [comment]
This file is no longer present in the `master` branch, closing.
