### ISSUE TITLE
Project manager receiving joypad input when starting project via Run-button

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#15199]
**Godot version:**
using Godot 3, the latest master version 0294887a0ca1b42f9fddb3858d4ee304b3f4d055

**OS/device including version:**
Linux Mint
using an Xbox 360 controller

**Issue description:**
When running a project from the Project Manager window the input is process by the game and also by the Project Manager window.

**Steps to reproduce:**
1. Open Project Manager
2. **Run** any project (not Edit!)
3. Move game window out of the way to see the Project Manager
4. Use Joypad while game window has focus (eg. dpad for button switching or A to click on buttons)
5. See that the input is also processed in the Project Manager

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by brainsick** [comment]
Ubuntu 17.10, Godot 3.0 Beta 2, AMD Radeon R9 Fury, Joypads demo, Microsoft X-Box One pad

I can recreate this.  Joypad demo has focus and is responsive to the controller.  Project Manager responds to directional pad and the A button.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by BeayemX** [comment]
I just noticed, that this is not only limited to the Project Manager window. When running multiple Godot games all game will receive the Joyput Input. It does not matter if the games are started from the editor or if they are run from the commandline.

**Comment by akien-mga** [comment]
I'll have a look at refactoring the mess in main.cpp so that the project manager and editor get a similar setup. Currently some things are set only when `editor` is defined, but they are relevant for the project manager too (such as HiDPI support - see #16407).

**Comment by akien-mga** [comment]
> I just noticed, that this is not only limited to the Project Manager window. When running multiple Godot games all games will receive the joypad input. It does not matter if the games are started from the editor or if they are run from the commandline.

Note that I only fixed it for the project manager, by disabling its support for game-specific input.

The fact that multiple instances of a game all receive joypad events regardless of the focus would likely be worth keeping track of in a new issue (if not done already).
