### ISSUE TITLE
Horizontal scrolling with Shift

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#15202]
**Godot/OS version:**
3.0 beta2, X11 Linux

**Issue description:**
In many other applications we can scroll horizontally by holding Shift while scrolling.
It would be nice to have such functionality in the script editor.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by vnen** [comment]
Do you mean "horizontally"? Because vertical scroll is the default when using the mouse wheel.

**Comment by timoschwarzer** [comment]
Oops, it's late here... :sweat_smile:
Yes I meant horizontally.
