### ISSUE TITLE
Build Project Button (Mono)

### ISSUE THREAD

**Issue by pcvonz** [godotengine/godot#15208]
**Godot version: Mono**

It'd be nice if the `Build Project` button under the `Mono` tab looked similar to the other Godot buttons. For example: The `Add Bus` button in the audio tab. 

- [X] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by akien-mga** [comment]
Fixed by #15574.
