### ISSUE TITLE
Difference in behaviour between Linux and Windows.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#15218]
**Godot version:**
3.0 build 548bd4e

**OS/device including version:**
Windows 10 64-bit
Ubuntu Linux 17.10 64-bit.

**Issue description:**
Under _Linux_, time over (either through the debugging key or letting the timer run normally) will kill the player character, play the relevant scene, then resume play.

_Windows_, will go through the time over scene, but after that it does not resume control. Player character is not visible and/or reset to the correct position.

There may well be bugs in my code or scenes setup, but in this instance the behaviour should be consistent between platforms.

https://www.dropbox.com/s/qe83mmc81u75pmv/15218_demonstrator_windows.webm?dl=0 shows what happens under Windows.

https://www.dropbox.com/s/eu0ilcht03fsyym/15218_demonstrator_Linux.webm?dl=0 is what happens with Linux.

**Steps to reproduce:**
Run the relevant project under Windows and Linux to compare.

**Minimal reproduction project:**
https://github.com/Sslaxx/GodotSonicEngine

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by Sslaxx** [comment]
Maybe found the source of this... https://github.com/Sslaxx/GodotSonicEngine/commit/c05eeab2ea1a5858899582fbe736d385988a38c4

**Comment by RandomShaper** [comment]
I'm having a look at this.

**Comment by RandomShaper** [comment]
I'm actually getting inconsistencies between platforms (and even crashes), though not the behaviors you describe.

Can you try disabling multi-threaded Phyisics and test again?

@reduz, I'm a bit outdated. Are multithreaded 2D Physics supposed to work?

**Comment by Sslaxx** [comment]
@RandomShaper changing multi-threaded to thread-safe makes no difference to Windows at least.

**Comment by Sslaxx** [comment]
A recent build (didn't pinpoint which sorry) changed some of the behaviour a little. tree_exited in dead_player stopped working as it should because of trying to access certain nodes while outside of the scene tree. Shifting that to tree_exiting worked. However, the original reported behaviour is still an issue with Windows (Linux works as expected, still).

**Comment by volzhs** [comment]
@Sslaxx it's changed in a26e6c82159c290a53c463dc4714789fc25391c2

> Renamed tree_exited to tree_exiting. tree_exited is now used for actual out of tree notification.

**Comment by Sslaxx** [comment]
Closing as this *seems* to have been fixed. If it crops up with 3.1 will open a new issue.
