### ISSUE TITLE
Godot3b2 support for 48kHz audio output

### ISSUE THREAD

**Issue by JoaquinsVoid** [godotengine/godot#15213]
Godot 3 beta 2 does not play well with an ESI Maya 22 USB set to 48000Hz on Win10 (latest update).
The result is partially gabled buffers. Sounds like rapid ticking or scratching.
Equally true for ogg and wav, long or short.
If the Maya is set to 44.1 kHz it's fine.

It also works with the mobo realtek device, but I suspect that is because it allows 44.1 kHz hook ups regardless of what you set it to.

I don't know if this is a feature request or a bug really. Games normally resample to what ever output they happen to get. And Godot obviously resamples internally anyway.

Addition: 
Tried daemon vs demon. (Godot2 i would assume) No issues.

**Comment by hungrymonkey** [comment]
the default mix rate is kinda hard coded

https://github.com/godotengine/godot/blob/master/servers/audio_server.h#L60

mix rate is set in all sound backends manually

https://github.com/godotengine/godot/tree/53bbc046ee670a1c24b1ec936066857ef6e73dc9/drivers

48 khz audio is a feature request really

**Comment by vnen** [comment]
I'm running the 2de70698ae2b3c94668556140e4c0197cff3327b build and it's working fine. Even if I set my audio interface to 96kHz the sound plays as it should.

**Comment by JoaquinsVoid** [comment]
No there must be something else going on. *Default* suggests that it is subject to change, doesn't it? 

 Looking at the code breifly, the WASAPI layer seems to pick up the sample rate as one might expect.

 And, wouldn't there be some kind of error in opening the audio device if it just wont accept the requested sample rate? There is nothing on the console.

**Comment by JoaquinsVoid** [comment]
Sorry about the closing-opening. Seems you can undo things here. I have no idea whats going on.

Anyway: *Default* suggests that it is subject to change, doesn't it? And the WASAPI layer seems to register the sample rate it receives. And shouldn't there be something printed to the console when this happens? Like sorry, audio device refused to take 44.1 kHz.

**Comment by JoaquinsVoid** [comment]
Investigated a little. The pitch of the samples is correct. This suggests that sample rate as such actually is correct. Maybe it's just the buffer size that is still calculated on the basis of 44.1kHz?

**Comment by JoaquinsVoid** [comment]
More info: 
If I reduce the number of buffers in the driver settings to 4, it goes away. 
So 44.1kHz with 8 buffers is cool. 48kHz with 4 buffers is cool. Even with very small buffer sizes. I don't know if wasapi reacts to that.

Either way, this might something to do with my hardware. So I'm closing it again.

But for the record, Godot2 does not have this issue, it works across the board with 48 kHz. As does SDL and Monogame. But until a related issue shows up it's probably not worth pinning this down.
