### ISSUE TITLE
Crash on creating a new C# script

### ISSUE THREAD

**Issue by AllanDaemon** [godotengine/godot#15214]
**Godot version:**

3.0 with mono support, from commit https://github.com/godotengine/godot/commit/f11a1385054376bdc4cc01e6aa20d63508a5e6d4 with the patch from PR https://github.com/godotengine/godot/pull/15136. 

**OS/device including version:**

Arch Linux 64bits

Mono version (from https://aur.archlinux.org/packages/mono-stable/):
```
$ mono -V
Mono JIT compiler version 5.4.1.6 (tarball Thu 28 Dec 13:08:23 -02 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

**Issue description:**

Godot crashes when attempting to create a new C# script. It doesn't happen when creating scripts in another language.

**Steps to reproduce:**
1. Open the attached project
2. Open the ball.tscn scene
3. Select root node ("ball") and click on attach script button
4. Select C# language with default settings
5. Click on "Create" button

When creating the script, the system hangs and crashes.

![screenshot from 2017-12-31 06-24-47](https://user-images.githubusercontent.com/607994/34460495-5362d668-edf7-11e7-8ea6-33e63f938f85.png)

Here is attached the output log of the terminal.
[output_log.txt](https://github.com/godotengine/godot/files/1595074/output_log.txt)

But a possible relevant part from the end:
```
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

**Minimal reproduction project:**

[project_example.zip](https://github.com/godotengine/godot/files/1595071/project_example.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by novemberist** [comment]
As you seem to be on Arch, I take it you built your own package with a PKGBUILD which installed the binary somewhere to your /bin folder? make sure all other files that get built along with the binary (GodotSharpTools.dll and godot.x11.opt.tools.64.mono.debugsymbols also reside in the same folder as the installed binary), otherwise Godot will crash when you try to create a c# script. At least that used to happen to me too before I modified my PKGBUILD to also include those other files.

**Comment by akien-mga** [comment]
> As you seem to be on Arch, I take it you built your own Godot package with a custom PKGBUILD which installed the godot binary somewhere to your /bin folder?

@AllanDaemon If this the case?

**Comment by novemberist** [comment]
his output.log suggests, that the binary has been installed or copied to /usr/bin/godot3-mono . if he, like me, used https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=godot-git this PKGBUILD from the AUR as a base to roll his own package and modified it to build godot with c# support, only the binary gets installed to /bin/ (which leads to the mentioned crash, unless the other files get copied too).

this is how I modified the PKGBUILD to use /opt/ to install godot, which is not optimal, but works at least https://pastebin.com/C1VFwAKh

**Comment by akien-mga** [comment]
Thanks, it's indeed not a bug in this case, just a bad local installation method. Feel free to comment if that's not the case though, so that we can reopen the issue.

**Comment by Ladvace** [comment]
i have the same problem but on window
