### ISSUE TITLE
Globals are not defined

### ISSUE THREAD

**Issue by Schweigert** [godotengine/godot#15227]
**Godot version:**
Godot 3.0 Beta 2

**OS/device including version:**
Debian

**Issue description:**
Globals not found.

**Steps to reproduce:**

**Minimal reproduction project:**

- [ x ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by volzhs** [comment]
`Globals` in 2.1 is moved to `ProjectSettings` in 3.0
