### ISSUE TITLE
How to create pcz files

### ISSUE THREAD

**Issue by shinyokohamahikaru** [godotengine/godot#1522]
How to create pcz file ?

**Comment by shackra** [comment]
Uh... what's a PCZ file?

**Comment by bojidar-bg** [comment]
As much as I can see on the Internet, it is "Compressed Macintosh PICT Picture Image". Don't know if is it related to the question (or if the question is related to godot).

**Comment by TheoXD** [comment]
editor tries to open data.pck and if it doesn't succeed - it tries to open data.pcz, which is basically a zip file with a different extension, so you can zip your project files and there you have it.

**Comment by reduz** [comment]
pcz is an old pack format of godot, which is basically a zip file. It was
deprecated in favor of the custom one .pck, which is faster and simpler to
read. Should go away soon.

**Comment by akien-mga** [comment]
This should likely go somewhere in the wiki, then this issue can be closed.

**Comment by akien-mga** [comment]
PCZ has been deprecated in favour of ZIP, and ZIP archives can easily be generated when exporting the data, so closing this issue.
