### ISSUE TITLE
Locked nodes are still selectable

### ISSUE THREAD

**Issue by NullNeska** [godotengine/godot#15221]
**Godot version:**
Godot 3.0 beta 2

**OS/device including version:**
Windows 10

**Issue description:**
Everytime i try to move a node, a large locked node is selected

**Steps to reproduce:**
make a large node, lock it, make a smaller node in the same position, struggle to select the node

**Minimal reproduction project:**
![unlawfulrequiredhuman-size_restricted](https://user-images.githubusercontent.com/6185415/34462452-997feec2-ee12-11e7-83d8-d0a541b0ad48.gif)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by volzhs** [comment]
it looks like you added a small size child node at big parent node.
and locked big parent node and make child node unselectable.
is that right?

**Comment by NullNeska** [comment]
both nodes are not related.

**Comment by groud** [comment]
This looks fixed on master branch.

**Comment by groud** [comment]
Closing as likely solved, please tell if someone can reproduce the bug.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
This is still present in 3.1 Beta 1.

**Comment by akien-mga** [comment]
Can't reproduce, please provide an example project and steps to reproduce.
