### ISSUE TITLE
Debugger crashes the program

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#15238]
**Godot version:**
Godot_v3.0-beta2_win64

**OS/device including version:**
Windows 7 x64 SP1

**Issue description:**
What happened: program has crashed
What was expected: breakpoint gets caught and i can debug as usual

**Steps to reproduce:**
1. In file 'SceneSwitcher.gd' put a breakpoint on one of these lines:
`var s = ResourceLoader.load(path)`
`current_scene = s.instance()`
2. Run the project
3. Click the button

**Minimal reproduction project:**
https://github.com/hilfazer/Projects/tree/master/Godot/SceneSwitcher

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

I took code from here:
http://docs.godotengine.org/en/stable/learning/step_by_step/singletons_autoload.html?highlight=change_scene
Program works fine without debugger's intervention.
It was broken in beta1 already.

**Comment by Geequlim** [comment]
You unlocked a bug :P

```gdscript
func _deferred_goto_scene(path):

    # Immediately free the current scene,
    # there is no risk here.
    current_scene.free()

    # Load new scene
    var s = ResourceLoader.load(path)
```

The debugger crashed by encode the variable `current_scene` which is free by you.

I'll try to solve this problem when I'm avaliabe.

**Comment by hilfazer** [comment]
Thank You, Geequlim, it's now working for "Minimal reproduction project" but there's still a problem in my other project. Here's the branch:
https://github.com/hilfazer/Projects/tree/DebuggerCrash2/Godot/DungeonCrawler

Reproduction:
1. In file 'SceneSwitcher.gd' put a breakpoint on this line:
`var newScene = ResourceLoader.load(targetScenePath)`
2. Start project.
3. Click "New Game" button. Debugger will catch the breakpoint.
4. "Continue" debugging, we're not interested in this breakpoint yet.
5. Click "Create character", then "Create", then "Start".
6. If it didn't crash yet, click "Step Over".

**Comment by Geequlim** [comment]
@hilfazer  I followed the steps you said. Can't reproduct that.
Get this scene in the screen
![image](https://user-images.githubusercontent.com/6964556/34522266-be86652c-f0cc-11e7-9428-185b4bc3adcf.png)

**Comment by hilfazer** [comment]
This is very strange. Even if debugger is not crashing the program you should be getting debugger error in Game.gd file at line:
`m_levelLoader.loadLevel( m_module.getStartingLevel(), self, CurrentLevelName )`

Error message is something like "nonexistent function 'getStartingLevel' in base 'Node (Game.gd)'"
This is caused by Godot mysteriously changing a value that is passed from SceneSwitcher.gd's m_sceneParams variable to Game.gd script.
Can you please check what script is in m_module value at the line i mentioned above? It should be 'Module1.gd' but i have 'Game.gd'.
Also, what's your OS/device? Perhaps there's a problem with only some configurations or my PC is cursed (: 

One more thing, are you sure you're on DebuggerCrash2 branch? I'm new to github so maybe i've provided incorrect link.

**Comment by Zireael07** [comment]
Error messages in Godot, especially the stacktraces, love showing that sort of messed up names if scripts inherit... I've gone looking for a function in xx.gd only to find it in yyy.gd, many times.

**Comment by hilfazer** [comment]
It's not just a message, behaviour of my program changes as well. I end up with gray rectangle and nothing else, while Geequlim gets proper result.

**Comment by hilfazer** [comment]
I've checked it on other machine and it also crashes. System:
Windows 7 Profesional N
Godot build commit hash: dbefa06d79237e3a0241d169eaf05fc98c89101a

**Comment by hilfazer** [comment]
Ok, i've found the problem.
I freed a node and passed it later to a signal. Looks like Godot used memory previously occupied by this node for another node. This is why i got different value than i expected in Game.gd script. 

Fixing it also prevented debugger from crashing Godot.

I'm too used to transparent memory management of C++, unique_ptr in particular :(
