### ISSUE TITLE
Specify Default Save Directories

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#15231]
I want to be able to specify the default directory where I save my scripts, scenes, etc. Having it default to the current scene's directory is annoying, because I have to manually move over to my preferred directory repeatedly.

**Comment by vnen** [comment]
That seems to fixed into a specific workflow, and Godot recommends to *not* use directories for asset types, instead they should be grouped by relationship.

**Comment by 11clock** [comment]
@vnen What do you mean specific workflow? I see people divide their projects like this all the time.

**Comment by Calinou** [comment]
> What do you mean specific workflow? I see people divide their projects like this all the time. In fact I don't think I have seen projects organized any other way.

See [Project organization](http://docs.godotengine.org/en/stable/learning/workflow/project_setup/project_organization.html) in the documentation.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/576, as feature proposals are now tracked in the Godot proposals repository.
