### ISSUE TITLE
Long error messages are displayed outside screen in console

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15234]
**Godot version:**

Built from f11a1385054376bdc4cc01e6aa20d63508a5e6d4 with PR #15136.

**OS/device including version:**

_Majaro Linux 17.1-rc2_

**Issue description:**

When a long error message is logged to the console, it is impossible to read the whole content since the displayed tooltip is bigger than the screen size, as shown below:

![godot-console](https://user-images.githubusercontent.com/2367032/34465751-15083c82-ef00-11e7-8e54-012f80c204d5.png)

Ideally, console should show the detailed content in a separate view, when the user selects a message from the list. It is especially important when the message contains a stacktrace information.

**Steps to reproduce:**
Write a code that throws a runtime exception. I tried it with C# project, so I'm not too sure if the problem persists with a GDScript project.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by RyanStein** [comment]
How does this look for a quick mock-up?

![err_details_mockup](https://user-images.githubusercontent.com/5884865/34474832-ce928b42-ef52-11e7-868c-0931f515033c.png)

I used a `VSplitContainer` on the left and a read-only `TextEdit` for the details output, which shows the text normally found only in the tooltip. It allows selection for copying, as shown in the picture.

**Comment by mysticfall** [comment]
@RyanStein Looks fantastic to me :) I think it makes sense to put the stack trace pane to the right side, since stack information tends to grow vertically.

The only improvement I can think of is making details and stack trace panes collapsible, but it's a minor one and I'd be more than happy to see it implemented as it is.

**Comment by RyanStein** [comment]
@mysticfall Thank you for the feedback. I've submitted the PR. The panes are not collapsible, though they _are_ contained in `SplitContainers`, which allows them to be resized as needed, even very minimally so.

**Comment by mysticfall** [comment]
Can't wait to try it out. Thanks much for the work! 😄

**Comment by akien-mga** [comment]
A new PR was proposed to fix this in #15272, but couldn't be merged eventually due to merge conflicts and the PR getting stale. It's up for a rebase if any contributor is interested.
