### ISSUE TITLE
Audio WAV Importer has no option for Loop Mode

### ISSUE THREAD

**Issue by Xydium** [godotengine/godot#15247]
**Godot version:**
3.0 Beta Custom Build 7f1265b

**OS/device including version:**
Windows 10

**Issue description:**
When importing a WAV audio file to use with a stream player node, there is only an option to toggle looping on or off. The audiostream resource has an option to toggle between Forward looping and Ping-Pong looping, however that setting cannot be changed in the import window, nor can it be changed in the resource inspector because changes to imported resources are not saved. The only workaround I've found for this is setting the loop-mode from scripts at runtime.

**Steps to reproduce:**
Import a WAV file into a project that is set to loop, then load it on an AudioStreamPlayer. The file will play forwards until the end, then in reverse. There is no setting to change this.

**Comment by sersoong** [comment]
Does 2.1 has it?

**Comment by Xydium** [comment]
@sersoong 2.1 didn't have this import system?

**Comment by mrcdk** [comment]
The issue came from exported files with custom loop type values. It was wrongly being read as a loop ping-pong when importing it into godot.
