### ISSUE TITLE
current editor default theme is too dark and not constrasted ennough

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1524]
Hi,

I don't know how it is for other Godot users, but at long, current theme is becoming very painful for my eyes when I'm working in a room with natural lighting from windows.

I think current theme is more adapted to work in dark rooms.

Would it be possible to :
- make a slightly better contrasted theme that would be more adapted for both illuminated and dark rooms ?
- or add an option to switch between several themes ?
- or apply a pixel-shader script that would allow users to tweak theme contrast and hue in real time ?

**Comment by okamstudio** [comment]
after 1.1, will be working on a new theme

On Wed, Mar 18, 2015 at 10:40 AM, UsernameIsAReservedWord <
notifications@github.com> wrote:

> Hi,
>
> I don't know how it is for other Godot users, but at long, current theme
> is becoming very painful for my eyes when I'm working in a room with
> natural lighting from windows.
>
> I think current theme is more adapted to work in dark rooms.
>
> Would it be possible to :
>
>    - make a slightly better contrasted theme that would be more adapted
>    for both illuminated and dark rooms ?
>    - or add an option to switch between several themes ?
>    - or apply a pixel-shader script that would allow users to tweak theme
>    contrast and hue in real time ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1524>.
>



-- 

*OkamStudio*

**Comment by silverkorn** [comment]
Personal suggestion (if it's not already the case), keep old purple and current dark theme along with the new theme you will work on, this will let the user choose what they prefer in a few clicks.

**Comment by theuserbl** [comment]
@okamstudio: After 1.1 you also work on a new GUI. Will it be written in GDScript and in the GUI-Builder and in Godot itself or like until now in C++?
/tools/editor/editor_node.cpp (EditorNode) and /tools/editor/project_manager.cpp (ProjectManager) are already components, which can be used in Godot and for which existing an icon for the first one in the GUI designer (/tools/editor/icons/icon_editor_node.png). But it would be nice to create both in Godot itself. Then the GUI can also easier improved. Modifying the GUI is then not more, then moving the controls of the GUI in the GUI Builder.

**Comment by reduz** [comment]
It will remain to be in C++ ( I honestly like to use C++ for tools), but
completely extensible in GDScript. Most of this work is done, but it needs
clean up and documentation.

**Comment by akien-mga** [comment]
What's the status regarding the integration of @ndee85's theme? Is it completed already?
And if so, is it better contrasted now, or are there still things we could improve?

**Comment by neikeq** [comment]
The theme introduced in 2.0 solves the dark problem. There may be new themes for future versions, but I think this issue is solved.

**Comment by SuperUserNameMan** [comment]
I'm working on a new screen and into a different room, and current theme is okay.

If no one objects, I agree to close this issue.

Though, applying some sort of pixel-shader to the editor's theme to tweak contrast and hue could be a cool feature to add.

**Comment by akien-mga** [comment]
Closing as per above comments. The editor can also be themed now, and it will be possible to share themes in the asset sharing platform :)
