### ISSUE TITLE
SSS doesn't work with alpha

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#15250]
**Godot version:**
3.0 Beta 2

**OS/device including version:**
Windows, RX 580, latest drivers.

**Issue description:**
I added a shader that creates alpha based on a map, however when applying the alpha the SSS seems to stop working.

**Steps to reproduce:**
Create a shader, add an alpha mask.

**Minimal reproduction project:**
```shader
shader_type spatial;

render_mode diffuse_toon, specular_schlick_ggx;

uniform sampler2D fluidmap : hint_albedo;
uniform sampler2D albedo : hint_albedo;

void fragment() {
	vec4 text_fluidmap = texture(fluidmap, UV);
	vec4 text_albedo = texture(albedo, UV);

	TRANSMISSION = vec3(0.8,0.8,0.8);

	ALBEDO = vec3(1.0,1.0,1.0);
	vec4 clamped = clamp(text_fluidmap, 0.0, 1.0);
	SSS_STRENGTH = 1.0;

	AO_LIGHT_AFFECT = 0.0;
	ALPHA = clamped.a;
	vec4 clamped2 = clamp(text_fluidmap, 0.0, 0.5);
}
```

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by reduz** [comment]
This is expected, subsurface scattering is a mid process that blurs based on depth. This is not available with alpha.
