### ISSUE TITLE
Region texture sprite

### ISSUE THREAD

**Issue by JeromeOrtali** [godotengine/godot#15255]
![godotbug](https://user-images.githubusercontent.com/5174372/34471877-36eedb04-ef54-11e7-9ed1-26ad61eaf389.png)
**Godot version:3 beta 2**

**OS/device including version:Windows 10**

**Issue description:**
Region texture cut doesnt fit at pixel coordinate ( see screenshoot ) i have half pixel (0.5f) offset in top , and the same value at bottom, the problem is appear when the rect position use certain position like 12,14 , with position start with 11,13 the problem diseapear, my texture sheet as size of 512x512 pixels , with small image , there is no problem... 1 on 2 pixels add or remove 0.5f on the cut with image of 512x512 for size.

-  I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by damarindra** [comment]
I do not quite understand, maybe I'm wrong. Can you tell me your rect region size? If your rect region is an odd number such as 255x255, or in your case, maybe the height is an odd number and the centered option is set to true, so that was normal. 255 / 2 = 127.5, and the anchor of the sprite is center. If your centered option is set to false, that will be fixed.

**Comment by JeromeOrtali** [comment]
yes , with no centered sprite , is fixed, but, i not agree with you, centered or not, pixel coordinate must be respected, when i work with other tool/api, like sfml, i never see that's, your example = 255/2 = 127.5, ok, but , inside the rect , the size , is the size, why you divide the region rect by 2 for centered the sprite ? it's an odd behavior, the vertices must be moved around the center, not the uv texture ( i think the problem is here ). i will look source more closer.

**Comment by JeromeOrtali** [comment]
the problem is here , has you mentioned before, line 86 
https://github.com/godotengine/godot/blob/master/scene/2d/sprite.cpp

**Comment by damarindra** [comment]
mmm, I understand now, the problem is the visual rect sprite. I thought your sprite pixel is not fit with the world coordinate. That's why I tell you to not set the centered option to make it fit to world coordinate.

**Comment by aaronfranke** [comment]
Please provide a minimal reproduction project.

**Comment by JeromeOrtali** [comment]
Impossible to reproduce "bug". i think you can mark as "solved" now.
