### ISSUE TITLE
3D meshes are all rendered pitch black on Ubuntu on Apple hardware

### ISSUE THREAD

**Issue by juan-garcia-m** [godotengine/godot#15259]
**Godot version:**
3.0 beta 2

**OS/device including version:**
Ubuntu on iMac / Ubuntu on MacBook Pro

**Issue description:**
3D meshes are all rendered pitch black. 2d has not have this issue.

**Steps to reproduce:**
1. Install and boot Ubuntu 17.10 on an iMac or Macbook Pro
2. Download and run Godot 3.0 beta 2
3. Clone the godot-demo-projects repo
4. Run any of the 3d demos
5. Observe the issue

**Minimal reproduction project:**
See step 3

**Additional info**
* Please note that this was also happening on previous custom builds of early 3.0 master repository.
* Also please note that this was also happening on previous Ubuntu versions.
* I haven't reproduce this issue on other non Apple hardware running Ubuntu.
* I haven't test this on an Macbook Pro for the Godot 3.0 beta 2, however this happened on previous custom builds, I will test and confirm this shortly on a following comment.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by blurymind** [comment]
What is the video card and OS version? Could help the developers

When you start Godot, you should see some hardware info in the terminal too

**Comment by juan-garcia-m** [comment]
@blurymind OS version is mentioned above: 17.10. Also this happened on at least 2 previous versions.
The graphics card are those that came by default with both desktop and laptop. Not 100% sure, but I think is an AMD on the iMac, and I will need to check the Macbook Pro.
Every other application seems to render correctly.

I am going to need to double check which ones, but I have saw a couple of screen shaders in the example on the godot-demo-projects repo displaying completely black. I will check this also in another non Apple desktop running Ubuntu, as this may be related, for example in the main shader rendering 3d meshes.

The hardware and OS combination for this issue might not be too common, so in case the core devs, or someone able is willing to submit PR, needs me to do some tests, please feel free to request me so.

**Comment by volzhs** [comment]
you can see some information when you run godot in terminal like below.
```
~$ godot3
No touch devices found
OpenGL ES 3.0 Renderer: GeForce GTX 670/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
```

**Comment by mhilbrunner** [comment]
Closing this until we get information about your hardware (see comment above). At least CPU and GPU. Also, you may want to retry with 3.0.2 or wait for 3.1.
