### ISSUE TITLE
rotate_and_collide() function.

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#15256]
Edit: Changed to reflect new info

A rotate_and_collide() function to allow a KinematicBody to rotate while still registering collisions would be extremely useful for both 2d and 3d.

===Original Post===
2.1.4
Windows 10

A KinematicBody2D that rotates using rotate() without move() ing that rotates into another body will not register a collision with is_colliding() despite the engine allowing it to collide with said body, stopping it.

Unsure is functions that require a collision to work still register the collision. 
(Such as get_collision_normal() )
More testing needed.

**Comment by eon-s** [comment]
Setting rotation is like setting position, not collision aware methods that only affect transform.

It will need a new method, lets say, `rotate_and_collide` like the move one, which test rotations until hit.

**Comment by ElfEars** [comment]
Ah. Thanks for the info. As for a potential rotate_and_collide, i'd definately vouch for it for the next version (3.1 as 3.0 is in feature freeze afaik). It would be an extremely useful feature.

**Comment by Anudin** [comment]
Also there should be an equivalent to test_move(). I feel like a general method like test_collision(transform) which works with movement, rotation and scale would be nice.

**Comment by karaketir16** [comment]
Is there any change about this issue? Is there any function like `rotate_and_collide` ?

**Comment by Sylvain303** [comment]
Is there a work around actually for detecting 2D collision manually when rotating a KinematicBody?

**Comment by eon-s** [comment]
@Sylvain303 one that comes to mind is casting rotated shapes with the physics server to see if your motion overlaps and adjust the final rotation accordingly.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/364, as feature proposals are now tracked on the Godot proposals repository.
