### ISSUE TITLE
[Mono][OSx][3.0beta2] No Export templates for Mono

### ISSUE THREAD

**Issue by bferguson3** [godotengine/godot#15268]
**Godot version:**
3.0 beta 2-mono

**OS/device including version:**
MacBook Air, HighSierra

**Issue description:**
1. There are no export templates for mono. 
I may be an idiot, and this may be intended - if so, where does one build the project? From mono?

Regardless, I downloaded the non-mono templates and simply renamed the folder to ~.mono in order to get Godot to recognize them.
2. Exporting after performing the above step finished without error.
3. Running the provided package file crashes immediately when attempting to launch.
4. I tried this with a blank project and Godot just crashed on build instead.

**Steps to reproduce:**
1. Create a new project in GD 3.0-b2-mono
2. Ensure the export templates are installed and recognized
3. Build the project

- [X] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.
![2018-01-02 1 47 19](https://user-images.githubusercontent.com/32964659/34501383-8589dfb0-efc3-11e7-93ce-b56f2be2d223.png)

**Comment by mhilbrunner** [comment]
Exporting is not yet supported for C#/Mono projects, I think.

**Comment by akien-mga** [comment]
Indeed, it's expected that there are no export templates as it's not supported yet. I've fixed the beta2 blog post to mention it (it was mentioned for beta1).
