### ISSUE TITLE
Can we have both C# and C++ video tutorials?

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#15263]
If people are going to use Godot there should be more tutorials. Hardly anyone has made any useful tutorials therefore it is very difficult to learn how to use Godot in the first place.

For C++ specifically is it possible to have video tutorials on how to set up GDnative etc?

**Comment by MrJustreborn** [comment]
3.0 isn't out yet...there will be tutorials/documentation how to use GDNative and C#

For C++ Development:
http://docs.godotengine.org/en/latest/development/cpp/index.html

**Comment by LinuxUserGD** [comment]
For C++ game development:
https://github.com/GodotNativeTools/godot_headers

**Comment by LinuxUserGD** [comment]
https://godotengine.org/community
Official Discord group with GDNative section:
https://discord.gg/zH7NUgz

**Comment by blurymind** [comment]
keep an eye on the patreon page - you can vote for those tutorials there

**Comment by neikeq** [comment]
> Hardly anyone has made any useful tutorials therefore it is very difficult to learn how to use Godot in the first place.

I guess you mean tutorials for C# and GDNative, because there are already a lot of Godot tutorials by the community.
Regarding C#, I plan to write some docs on the differences with GDScript, some technical things, and some cool stuff you can do (like not needing weakref to track a node lifetime).
The rest has to come from the community (there are already a few tutorials out there).

**Comment by Raj2032** [comment]
Hi Ignacio, I have not been able to find GDNative tutorials, can you please
give me a link to GDNative tutorial please?

On Wed, Jan 3, 2018 at 3:18 AM, Ignacio Etcheverry <notifications@github.com

**Comment by vnen** [comment]
Note that Godot 3 isn't even released yet. Just now it's becoming stable and will attract people to make tutorials. Only a few people actually used GDNative and C#, none on a full project (AFAIK). Once things are stable, I'm sure plenty of tutorials will be available.

If you want to be an early adopter, you need to figure out things yourself.

> If people are going to use Godot there should be more tutorials. Hardly anyone has made any useful tutorials therefore it is very difficult to learn how to use Godot in the first place.

There are a very large numbers of Godot tutorials out there. All of them use GDScript, of course, but saying there are not many useful tutorials is a lie. If you mean specifically about C# and GDNative, then there's the reasons I put above.

In any case, if you think the documentation is lacking, open an issue in the [documentation repository](https://github.com/godotengine/godot-docs).  This GitHub is not a place to ask how to use Godot, you have community channels for that. This issue tracker is meant for bugs and tangible feature requests.
