### ISSUE TITLE
the godot editor with pulseaudio driver eat too much cpu usage

### ISSUE THREAD

**Issue by akanewf** [godotengine/godot#15266]
**Godot version:**

9821562b300ecc2401ec1e42600a92053897e51f

**OS/device including version:**

archlinux 

**Issue description:**

Recently I found the editor (and system) respond slower than last year :D.
so i check the system and found pulseaudio eat 6-10% cpu usage.
I didn't even play any sounds or music in editor and system.
so i restart the computer keep no application running and check:

1. play a vidio on youtube with firefox , 1.3-2.0%.
2. stop youtube and play a music (320k/mp3) with firefox ,  0.7-1.2%.
3. play vidio and music, 1.4-2.6%.
3. close firefox and open up godot project manager, 6-10%.
4. close godot, 0%.

It shouldn't be a system problem.

so i check the code and found:
f231eadc9e2487c70db04f912578ec853f11737c
`int latency = GLOBAL_DEF("audio/output_latency", 25);`
changed to
`int latency = GLOBAL_DEF("audio/output_latency", DEFAULT_OUTPUT_LATENCY);`
and
`static const int DEFAULT_OUTPUT_LATENCY = 15;`

so i test two values of DEFAULT_OUTPUT_LATENCY:
value, pulseaudio cpu usage
15, 6-10%
25, 2-4%

emm...DEFAULT_OUTPUT_LATENCY = 15 maybe too low for linux with pulseaudio ?

**Steps to reproduce:**

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by raymoo** [comment]
I don't think it's a bug, lower latency means pulseaudio will need to check its audio buffers more frequently. Are you able to reduce CPU usage by changing the output latency from the project settings?

**Comment by akanewf** [comment]
yes, it's not a bug.
it's work by changing project settings.
thanks.

what I want to express is that the new default value(15) for pulseaudio may cause game performance problems.the old one(25) may more fit for general purpose.

**Comment by raymoo** [comment]
On multicore computers, pulseaudio would only be taking up 6-10% on one core, which is not that big of a price I think.

**Comment by akien-mga** [comment]
CC @marcelofg55 (in case you have an opinion about this :)).

**Comment by marcelofg55** [comment]
I'll check this out this weekend, but I think it's not a godot issue actually. Video players or browsers probably don't request a low latency setting for pulseaudio so that's why they use less cpu.
