### ISSUE TITLE
Android template will needs Latest APIs(targetAPI) and 64bit NDK on GooglePlayStore

### ISSUE THREAD

**Issue by JunShiozawa** [godotengine/godot#15273]
Android template will needs Latest APIs(targetAPI) and 64bit NDK on GooglePlayStore

https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

https://arstechnica.com/gadgets/2017/12/google-fights-fragmentation-new-android-features-to-be-forced-on-apps-in-2018/

**Comment by Calinou** [comment]
This was done a while ago, closing.
