### ISSUE TITLE
Make "Delete" key delete files too

### ISSUE THREAD

**Issue by sudoio** [godotengine/godot#15281]
**Godot version:**
v3.0.beta.build2

**Issue description:**
Currently, if you press the `Delete` key, Godot always asks to delete the last selected node in the scene.
It would be better if it will delete (with confirmation) files too, when a file is selected.

**Comment by noidexe** [comment]
Duplicate of #14568

**Comment by sudoio** [comment]
Ok, didn't notice that one when searching
