### ISSUE TITLE
Default forward axis Z+ or -Z?

### ISSUE THREAD

**Issue by jedStevens** [godotengine/godot#15283]
master branch

Manjaro Linux

I was playing around trying to make an IK system when I ran completely stumped against why I couldn't point bones in the proper direction.

To my knowledge, and correct me at any point, the steps required to point something are as follows:

    var target_t = $target.global_transform
	var bone = $arm.global_transform
	var old_v = -bone.basis[2]
	var new_v = target_t.origin - bone.origin
	var rot_axis = old_v.cross(new_v)
	var new_t = bone.looking_at(target_t.origin, rot_axis)
	
	$arm.global_transform = new_t

This above code makes sense when I use a spatial node with a mesh facing the Godot forward, -Z.

    var sk = get_parent() #Assume Skeleton parent
	if target == null:
		return
	var target_t = target.global_transform #target is a MeshInstance node
	var bone = sk.get_bone_pose(1)
	var old_v = -bone.basis[2]
	var new_v = target_t.origin - bone.origin
	var rot_axis = old_v.cross(new_v)
	var new_t = bone.looking_at(target_t.origin, rot_axis)
	
	sk.set_bone_pose(1, bone.interpolate_with(new_t, delta))

Now when I move this code to a Skeleton and try to apply the same logic to a bone, it always seems really messed up. The bone never points at the target, it either points in the opposite direction, or 90 degrees to it.

This is strange to me because I thought I created my arm in blender in the standard -Y forward, which I thought the axis switch is covered in the conversion. However I notice that the models coming in from blender in both DAE and GLTF are facing Z+ which is my guess as to why the transforms are also backward.

This is also confusing to me, because in the Skeleton tutorial it says that the bone vector is basis[2] of the bone transform. This must be so, but how is this supposed to be used when the looking_at function points using -Z?

I'm sure this is confusing for some others as well, as I've not found much on IK in godot yet, I'm just hoping someone who understands the system better than I can explain this odd behaviour, or heck maybe its not even odd and I'm just wrong.

Can provide a project if needed.

Thanks

**Comment by jedStevens** [comment]
Oh also, on Import the entire model is facing Z+, even when I created it in blender with -Y. Shouldn't this also be corrected; the model should face -Z if I am not mistaken about the coordinate systems.

**Comment by jedStevens** [comment]
Im also noticing now that the Front and Rear view of the camera also support a Z+ forward axis, when still the looking at function points using -Z.

I guess my question becomes, how are you supposed to use a backward pointing function? I can use it by doing a looking_at(-target.origin) but this seems counter intuitive and doesn't hold when I move things off the 0,0,0 origin.

This all just seems jumbled to me I suppose, could someone clarify what I might be doing wrong to make something simply look at another object? Should my forward in Godot be Z+ or -Z? What about blender?

**Comment by jedStevens** [comment]
I've also found tutorials online saying that forward is negative Z which makes me even more confused because I also read on the Godot docs that the bone is in fact supposed to be positive Z. That's what makes me think something is wrong here; wouldn't it be better to load the bone vector as negative Z instead?

**Comment by jedStevens** [comment]
Just found a fix to my issues, which was just swapping the Z and Y axis manually in my code, but I think this shouldn't have to be accounted for, and should just work with the Godot way of things by simply looking at where its told to.

var temp = new_t.basis[2]
	new_t.basis[2] = new_t.basis[1]
	new_t.basis[1] = -temp
	$Skeleton.set_bone_global_pose(0, new_t )

**Comment by jedStevens** [comment]
https://github.com/Kupoman/blendergltf/

I switched to this exporter from the Khronos one and all seems to be good except that the bones show in the editor perpendicular to where they are actually moving the mesh.

![image](https://user-images.githubusercontent.com/6509081/34533285-94d173f6-f087-11e7-8559-0f59d03868e6.png)

**Comment by jedStevens** [comment]
Just saw a PR for Ragdoll and IK, which means I'm effectively wasting my time, nothing to see here folks.

**Comment by Zireael07** [comment]
@jedStevens: That PR is still a WIP and the behavior you're seeing looks like a bug...

**Comment by jedStevens** [comment]
Thank God, I've been messing with this for weeks thinking my matrix math has been off. I'm not so advanced on the importer and exporter myself but I'd wager it's that the bones aren't given the proper basis because of the axis conversion

**Comment by rminderhoud** [comment]
@jedStevens raises some good points. Pressing numpad 1 brings up "front view" which implies the forward direction is +Z but `look_at` rotates assuming -Z. Am I missing something or should I open a new issue about this?
