### ISSUE TITLE
[FreeBSD] Crash editing any project from Project Manager

### ISSUE THREAD

**Issue by robfram** [godotengine/godot#15288]
**Godot version:**
master (3.0beta2) bc513dfa84c2bdfcfbf82c924cbf3fd3bc9c27de custom-build

**OS/device including version:**
FreeBSD 11.0-RELEASE-p1 r306420
Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz (2195.06-MHz K8-class CPU)

**Issue description:**
The application crashed every time it spawns a new process of the executable. It happens when pressing Edit button on Project Manager, or when pressing Play in the Edit button.

Output is:
```
OPENING: /home/user/godot/projects/test (::home::user::godot::projects::test)
**ERROR** OS_Unix::execute - Could not create child process while executing: /usr/home/user/godot/godot.x11.tools.64.llvm
```
**Steps to reproduce:**
Project List -> New Project -> Create Folder -> Create & Edit

**Problem Analysis:**
Missused return value of find method in string class result in the wrong branch of code at drivers/unix/os_unix.cpp:301

```
#ifdef __FreeBSD__
		if (p_path.find("/")) {
			// exec name contains path so use it
			execv(p_path.utf8().get_data(), &args[0]);
		} else {
			// use program name and search through PATH to find it
			execvp(getprogname(), &args[0]);
		}
#else
```

A full path ('/path/to/godot.executable') in p_path variable causes p_path.find("/") return 0 (first character of string is a slash), going for the wrong branch and searching through PATH.

**Solution:**
Using String::npos instead asuming 0 as not-found value. 
This is a diff patch to solve the problem:
```
diff drivers/unix/os_unix.cpp
301c301
<         if (p_path.find("/")) {
---
>         if (p_path.find("/") != String::npos) {
```

**Comment by akien-mga** [comment]
Thanks for the detailed explanations, your proposed fix was indeed the right one (I used `-1` directly as it's consistent with what we do currently on all `String.find()` uses).
