### ISSUE TITLE
Visual glitch when dragging keyframes

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#15285]
**Godot version:** from 2.1 till at least 6188279

**OS/device including version:**
Win 7 64 bits

**Issue description:**
Keyframes jump one track up while being dragged. It only happens when there are enough tracks to make the vertical scrollbar appear. It doesn't happen when the scrollbar is in the topmost or bottommost position.

**Steps to reproduce:**
1 - open animation dock
2 - add enough channels so that a vertical scrollbar appears
3 - put the scrollbar in any position other than complete top or bottom
4 - drag one or a selection of keyframes

**Minimal reproduction project:**
Here's a video showing the issue. The first part shows the issue and after 00:11 it shows how it doesn't happen with the scrollbar on top or bottom position.

[15285-keyframe-dragging-gltich.zip](https://github.com/godotengine/godot/files/1600460/15285-keyframe-dragging-gltich.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by thomaslynge** [comment]
I think I have fixed the error. I will make a pr.
