### ISSUE TITLE
Broken macOs .app bundle 

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15293]
**Godot version:**
https://github.com/godotengine/godot/commit/2488aff93f93deda27c99cf4811986afeb973438

**OS/device including version:**
MacOs Sierra 10.12.6 (16G1036)
MacBook Pro (15-inch, 2016)
2,7 GHz Intel Core i7
16 GB 2133 MHz LPDDR3
Radeon Pro 455 2048 MB
Intel HD Graphics 530 1536 MB

**Issue description:**
godot.app works but;
- The icon of the godot.app is gone.
<img width="136" alt="ekran resmi 2018-01-03 17 41 29" src="https://user-images.githubusercontent.com/33985414/34525260-5c6befb4-f0af-11e7-980e-20250e06483b.png">

- the godot.app does not appear in the Launchpad.

- http://godot3builds.digitecnology.com/ builds have same issue.

**Steps to reproduce:**
I built it with these commands;

```
scons -j6 p=osx target=release_debug bits=64

cp -r misc/dist/osx_tools.app ./Godot.app
mkdir -p Godot.app/Contents/MacOS
cp bin/godot.osx.opt.tools.64 Godot.app/Contents/MacOS/Godot
chmod +x Godot.app/Contents/MacOS/Godot
```

**Minimal reproduction project:**

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by bruvzg** [comment]
Regressing from b50a9114b105dafafdda8248a38653bca314a6f3:

Missing closing `<` in `</string>` an line 12 and 28 in `godot/misc/dist/osx_tools.app/Contents/Info.plist`

```plist
<string>(c) 2007-2018 Juan Linietsky, Ariel Manzur./string>
...
<string>© 2007-2018 Juan Linietsky, Ariel Manzur./string>
```
