### ISSUE TITLE
Inspector Tab focus navigation

### ISSUE THREAD

**Issue by Demmios** [godotengine/godot#15291]
**Godot version:**
3.0

**Issue description:**
How about if the Inspector window if activated (on focus) and if you press "TAB" key instead of cycling throught all the godot tabs it jumps to the next line of the inspector allowing the user to edit faster and cycle the focus between lines while using keyboard only input

**Comment by vnen** [comment]
Duplicate of #3598? Due for a long time...

**Comment by Demmios** [comment]
closed because already have one request of this feature into git
