### ISSUE TITLE
The play window opens always over the editor

### ISSUE THREAD

**Issue by ignotion** [godotengine/godot#1530]
Usually, when debugging, i move the playing window apart so i can see the code and at the same time the play window.
When I start another debugging session, the play windows appears again over the code window. It would be nice it remembered where it was placed the last time and open the window directly there.

**Comment by reduz** [comment]
planned for 1.2

**Comment by neikeq** [comment]
Commit cf57a65 added the option to set a custom position for the game window in which to start. is that enough? or is an option to remember last position planned?

**Comment by reduz** [comment]
yes this was fixed, closing
