### ISSUE TITLE
Suggestion: Send effect within the Audio mixer

### ISSUE THREAD

**Issue by tiniuclx** [godotengine/godot#15302]
Oftentimes, when working on audio, it is useful to send a number of channels to a common track, where they are processed together. A send effect would be a way to achieve this. The effect takes the signal of a track and sends it to a specific channel, with configurable gain. 

For instance, this could be used by having a shared reverb bus, which adds reverb to every channel routed to it, and using it to add reverb to all of your tracks. Doing this, as opposed to using an individual reverb effect per channel, saves resources due to not running multiple effects. Additionally, colouring multiple tracks with the same effect helps to tie them together.

**Comment by mrcdk** [comment]
You can create a reverb audio bus and set every `AudioStreamPlayer` `bus` parameter to that bus.

Also, you can have multiple buses and each bus can send the signal to other buses.

https://streamable.com/14klb

**Comment by tiniuclx** [comment]
Thank you for your reply. I was unaware that channels can route audio to any bus to its left. This would solve many of the use cases i had in mind, and it mostly renders my suggestion unnecessary.
