### ISSUE TITLE
MissingMethodException with Mono

### ISSUE THREAD

**Issue by EugenEistrach** [godotengine/godot#15307]
**Godot version:**
https://github.com/godotengine/godot/commit/cd63407aa40e060631334b307e9ab4273ff90e39

**OS/device including version:**
Windows 10 / [DxDiag.txt](https://github.com/godotengine/godot/files/1601826/DxDiag.txt)

**Issue description:**
I compiled the latest master branch with mono flag. I have installed the latest stable mono version (5.4.1.6) and created a new project with a script attached to a node. In the script I create an instance of the Directory class and call .Open("res://") .  When I build the project and start it I get the following exception when I try to use .Open:

> ERROR: GDMonoMethod::invoke: System.MissingMethodException: Attempted to access a missing method.
>    At: modules\mono\mono_gd\gd_mono_method.cpp:107

The thing is I only get this error on my main machine (Windows 10)
On my second machine which runs Windows 7 I can run the project without any problem
If I use beta 2 of godot I also can run the project without a problem on my main machine.

I also tried it on another windows 10 machine. Did work there without problems. Thought that it might have something to do with my windows user so I created a new one but with the new user I have the same problem. 

At last I reinstalled windows 10 since I wanted a clean setup for some time and thought this would be a good opportunity. I reinstalled everything like I did on the other Win 10 machine earlier this day and still got the missing method exception. But now it doesn't trigger on the Open method but on the BeginListDir method. Completely fresh install, everything is fresh. 

**Steps to reproduce:**
I really don't know how to reproduce this, since I tried it on two other machines where I did exactly the same steps installing everything required to compile and run godot.

**Minimal reproduction project:**
[TestGo.zip](https://github.com/godotengine/godot/files/1601824/TestGo.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by darrylryan** [comment]
![image](https://user-images.githubusercontent.com/3797848/34614843-b86948da-f22a-11e7-8948-3a3b57e39f3b.png)

I'm getting a lot of these too when trying to access nodes in C#

**Comment by pcvonz** [comment]
Just updated recently, now I'm also getting the same error.

**Comment by darrylryan** [comment]
Mono seems very broken now... tons of missing methods etc.

**Comment by neikeq** [comment]
After downloading latest master, did you make sure to do the first step (building with and regenerating the glue) before building your binaries?

**Comment by darrylryan** [comment]
@neikeq yep, I have completely cleaned and rebuilt everything from scratch many times... I have a set of .bat files to do the build which were working fine a few weeks ago but recently there are tons of missingmethodexceptions

**Comment by EugenEistrach** [comment]
You can try removing "%appdata%/Godot/mono" folder so that the GodotSharp and GodotSharpEditor solutions will be regenerated. If this won't fix you problems it would seem that you have the same problem as me, since nothing I have tried fixed it on my main machine.

**Comment by darrylryan** [comment]
@EugenEistrach @neikeq Yep I've tried deleting the whole folder in %appdata% and all the bits in the project except the assets folder. No luck :(

Incidentally it really bugs me that it puts stuff in the user profile without a way to change it - I don't have much space on the system SSD, and also it makes it really hard to back up or roll back all the parts for a given version of the game if some of it is autogenerated in a folder outside the scope of the project. I think this should be put in the project folder too, or at least make it configurable.

**Comment by NathanWarden** [comment]
> I think this should be put in the project folder too, or at least make it configurable.

I wouldn't mind if this was generated for each project in the .mono folder either (or even putting it in a .temp/mono folder and generated each time the editor is opened to ensure it's always the correct one?). Yes, it's somewhat large, but I think the size pales in comparison to what a typical project size is.

**Comment by neikeq** [comment]
The generated API solution should always match the glue API, unless the glue API is outdated or something changed internally in the bindings while the API hash is still the same (which didn't happen here).

**Comment by neikeq** [comment]
Can I have a look at your `modules/mono/glue/mono_glue.gen.cpp` and `%appdata%/Godot/mono/solutions/GodotSharp_???/Core/NativeCalls.cs` files? (`???` is the API hash, if you don't know what your API hash is and there are multiple `GodotSharp_` folders then delete all of them and let the editor regenerate it).

**Comment by EugenEistrach** [comment]
Compiling, building the glue files and compiling again with the the latest commit (#e7400a0f4e29fb5c0d06af3952b54e05a0d9d7d9) here are both files in a zip:
[Files.zip](https://github.com/godotengine/godot/files/1611027/Files.zip)

**Comment by PJB3005** [comment]
I looked into this and decided to add some debug logging to the icall population code inside the bindings generator. It seems that the order in which icalls are generated isn't consistent anymore, even with the same builds, so the generation of the C# `GodotSharp.dll` project files doesn't match up with the glue generated the step before.

**Comment by darrylryan** [comment]
@PJB3005 @neikeq I can confirm I am getting mismatched glue even when I literally just built it fresh.

**Comment by PJB3005** [comment]
I should clarify: the order in which the types are populated is the issue. The individual methods on each type seemed to be consistent (going by method arg counts, I didn't check thoroughly though)

**Comment by neikeq** [comment]
@PJB3005 Oh, that makes sense. Should probably use OrderedHashMap instead. I will make a PR tomorrow you can test.

**Comment by neikeq** [comment]
Can you check if #15533 fixes this issue?

**Comment by darrylryan** [comment]
@neikeq I'm still having issues... the project generated still has an API mismatch and also it doesn't include all the files in the .sln it generates now, I had to open the .sln and add the .cs files to the project to get it to build.
