### ISSUE TITLE
Script cleaning icon doesn't update properly.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15319]
**Godot version:**
https://github.com/godotengine/godot/commit/465d66be6754c446844115d9933022960fe5217c
**OS/device**
macOS Sierra 10.12.6 , MBP 2016

**Issue description:**

To clear the script, you need to de-select and re-select node.

**Steps to reproduce:**
![hard](https://user-images.githubusercontent.com/33985414/34563049-0a00b7d8-f162-11e7-952f-caf435319ecd.gif)

**Minimal reproduction project:**

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by bojidar-bg** [comment]
I have observed this in 2.1 as well.

**Comment by akien-mga** [comment]
I've noticed this one on master yesterday too.
