### ISSUE TITLE
When ResourceLoader.load fails the log is unhelpful

### ISSUE THREAD

**Issue by ravenblackx** [godotengine/godot#15313]
**Godot version:**
v2.1.4.stable.officialGodot 64-bit

**OS/device including version:**
Windows 10.

**Issue description:**
ResourceLoader.load, when it fails, just returns None, with nothing logged about how it failed, which can be extremely unhelpful.

**Steps to reproduce:**
I provoked a failure by:
1. code like
var s = ResourceLoader.load("res://foo.tscn")
var x = s.instance()
2. foo.tscn contains a SamplePlayer2D.
3. Set Samples on that SamplePlayer2D to a new library, and add an audio file to it.
4. Rename or delete the selected audio file outside of Godot.
5. Cause the code from 1 to run.

The console output just complains about instance being called on None, with no hint at all about why the resource loading had a problem. (Luckily I tried it immediately after moving those files so I knew the cause, but if I'd made several changes I'd have been utterly lost.)

I imagine adding a breakpoint wherever ResourceLoader.load is about to give up would be a relatively safe and inexpensive fix, unless someone, somewhere, is relying on deliberate failure to signify something!

- [X] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by akien-mga** [comment]
Cherry-picked for 2.1 as 6dced6218.
