### ISSUE TITLE
Missing translation for part of error message

### ISSUE THREAD

**Issue by sudoio** [godotengine/godot#15327]
At this line:

https://github.com/godotengine/godot/blob/f8b58784bc693114ffe9c6b523ae73ecb3472311/platform/javascript/export/export.cpp#L280

`"Could not read boot splash image file:\n"` is translated with `TTR()`, while `"\nUsing default boot splash image"` is not.

**Comment by bojidar-bg** [comment]
You are welcome to make a PR adding the TTR to the second part as well.

**Comment by akien-mga** [comment]
I'm fixing this.

**Comment by akien-mga** [comment]
Fixed by d78335d87.

**Comment by sudoio** [comment]
Looks like you are now missing a closing parenthesis `)` at the same line.
Travis:
![travis](https://user-images.githubusercontent.com/19972511/34572978-f93cfa20-f183-11e7-84f4-4c49f706d958.png)
