### ISSUE TITLE
latest commit "Add missing translation in Javascript export dialog" compiling errors

### ISSUE THREAD

**Issue by akanewf** [godotengine/godot#15328]
**Godot version:**

**OS/device including version:**

**Issue description:**

d78335d87f4441c2bbe7e1c11642fbf19ae95c12

platform/javascript/export/export.cpp:280:161: error: expected ')' before ';' token
 ->show_warning(TTR("Could not read boot splash image file:") + "\n" + splash_path + "\n" + TTR("Using default boot splash image.")--->>)<<---;

miss ")" :D

@akien-mga

**Steps to reproduce:**

**Minimal reproduction project:**

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by sudoio** [comment]
Added comment to related #15327: [comment](https://github.com/godotengine/godot/issues/15327#issuecomment-355325690).

**Comment by LinuxUserGD** [comment]
```platform/javascript/export/export.cpp: In member function 'virtual Error EditorExportPlatformJavaScript::export_project(const Ref<EditorExportPreset>&, bool, const String&, int)':
platform/javascript/export/export.cpp:280:161: error: expected ')' before ';' token
    EditorNode::get_singleton()->show_warning(TTR("Could not read boot splash image file:") + "\n" + splash_path + "\n" + TTR("Using default boot splash image.");
                                                                                                                                                                 ^
scons: *** [platform/javascript/export/export.x11.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
Oh well, I knew I shouldn't push without compiling right before boarding a plane :P

**Comment by LinuxUserGD** [comment]
I get some linking error using the 'scons p=x11 bits=64 use_lto=yes -j 8' command:
```/tmp/ccrTKqDP.ltrans27.ltrans.o:(.data+0x10fa0): undefined reference to `.L38143'```

**Comment by sudoio** [comment]
@LinuxUserGD I think you should open a separate issue for that error
