### ISSUE TITLE
Tile Set menu causes the editor to crash.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15320]
**Godot version:**
https://github.com/godotengine/godot/commit/465d66be6754c446844115d9933022960fe5217c
**OS/device**
macOS Sierra 10.12.6 , MBP 2016

**Issue description:**

"Tile Set > Add Item" causes crash
"Tile Set > Create from scene" causes crash

**Steps to reproduce:**
Add Item
![crash](https://user-images.githubusercontent.com/33985414/34565635-a1fa9efa-f16c-11e7-94c8-c09147a6950f.gif)
Create from scene
![crash2](https://user-images.githubusercontent.com/33985414/34565665-c333c8da-f16c-11e7-9033-df5f178a78ef.gif)

**Minimal reproduction project:**

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by volzhs** [comment]
isn't this just fixed by #15311?

**Comment by icnikerazah** [comment]
I wrote the godot version. is this fixed?

**Comment by icnikerazah** [comment]
is this fixed?
<img width="233" alt="ekran resmi 2018-01-04 15 42 46" src="https://user-images.githubusercontent.com/33985414/34565957-d06aba3a-f16d-11e7-9d46-5fba9b379b7b.png">

**Comment by bruvzg** [comment]
macOS 10.13.2 (17C88), Godot 3 dc2cc6bc2, can't reproduce.

**Comment by volzhs** [comment]
The "Tile Set" button issue is merged an hour ago. would you try it again with latest?

**Comment by icnikerazah** [comment]
ok i will try latest.

**Comment by icnikerazah** [comment]
there is no crash with latest. it's fixed.
