### ISSUE TITLE
jiggle bones support

### ISSUE THREAD

**Issue by redpandaa** [godotengine/godot#1533]
Jiggle bones are bones that are animated procedurally in realtime with a physics engine. Used for clothing, items a moving character/ object, hair, hats, bunny ears, etc.

Also, ragdolls. https://www.youtube.com/watch?v=wKLaMN9dnjQ

Reference:
https://www.youtube.com/watch?v=RmCNxNkrrKQ
https://wiki.teamfortress.com/wiki/Jiggle_bones

**Comment by reduz** [comment]
this is planned for 1.2

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by tagcup** [comment]
Is this still planned?

**Comment by Corruptinator** [comment]
Curious about this feature too.

**Comment by reduz** [comment]
Planned for 3.1

**Comment by Bauxitedev** [comment]
I've been working on an [addon](https://github.com/Bauxitedev/godot-jigglebones) that does this. Couldn't wait for 3.1 :laughing:.

**Comment by blurymind** [comment]
wasnt this merged ?

**Comment by reduz** [comment]
This is already supported now, so closing
