### ISSUE TITLE
Default editor layout - canvas space improvement

### ISSUE THREAD

**Issue by Demmios** [godotengine/godot#15331]
![default_layout](https://user-images.githubusercontent.com/35068082/34574271-09846240-f15e-11e7-9138-c806436ad653.png)

**Godot version:**
3.0 and below

**Issue description:**
I know Godot have the hability to change the editor layout as you wish but my suggestion would by default the layout should be the one that maximizes the canvas (the most important area of the editor) to do this we need to dock the file system near the scene tab (on top) and by doing this way we can have a much cleaner user interface to work on and a bigger canvas space.

The filesystem its not too much important in my opinion to be on the default left using too much canvas space.

**Comment by sudoio** [comment]
I think the default layout is ok, because it is applied at first launch, and a big empty canvas in the middle does not look very good (at least to me). Also, the filesystem is important at the beginning of development, because you need to import a lot of stuff. 
BTW you can make canvas full screen if you need more space: just `Toggle distraction-free mode` by pressing `Control` + `Shift` + `F11`.

**Comment by Demmios** [comment]
sudoio i see your point of view but the filesystem still exists is just docked next to the scene tab most of modern aplications try to maximize canva space by keeping the UI as clear as possible and stacked uper tabs have much more space in this layout but here its a preference decision =)

**Comment by groud** [comment]
I don't agree, the first time you open an editor the main important thing is discoverability.
Hiding important docks at startup is not a good idea.

As knowing what resources are on the disk is important when you open a software, the FileSystem tab **is** important.

**Comment by Demmios** [comment]
maybe both layouts are important have advantages and disadvantages

**Comment by vnen** [comment]
@groud you beat me to it, I was about to say the same thing, hehe

As stated, it's possible to change the default layout, so I don't think personal preference is important here.

**Comment by groud** [comment]
Well it also that I don't see the point in maximizing the space available for the editor. When you're editing something specific why not, but when you use the engine for the first time I don't think it matters :)

**Comment by Demmios** [comment]
if so i am closing this discussion it should be preference option not a issue at all
