### ISSUE TITLE
Editor crashes if a lightmap file is missing

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#15336]
**Godot version:**
df04f46

**OS/device including version:**
Debian GNU/Linux

**Issue description:**
Editor crashes when a lightmap .tex file is missing. I think an editor warning, or auto-rebake is a better option here.

**Steps to reproduce:**
Bake lightmap in a scene, close the editor, remove a .tex file, start the editor.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by reduz** [comment]
Can't reproduce, please make a demo project.

**Comment by reduz** [comment]
For the record, seems to work perfect here:
![image](https://user-images.githubusercontent.com/6265307/34622506-44658ba4-f22c-11e7-8e53-0c4240d2e30e.png)

**Comment by seadra** [comment]
I can't reproduce it with a fresh build either!
