### ISSUE TITLE
Child Containers reset anchors upon loading

### ISSUE THREAD

**Issue by dploeger** [godotengine/godot#15348]
**Godot version:**

Godot 3 daily build da4edf8

**OS/device including version:**

macOS 10.13.2

**Issue description:**
When a child container has layout anchors set, these are removed upon reloading the scene.

**Steps to reproduce:**

Create child containers to a container. Set anchor values. Save scene, Load scene.

I've created a [Screencast](http://take.ms/J0uMj) about this.

**Comment by reduz** [comment]
This is not a bug, it's working as intended. Containers override anchors of children. We should make sure to put this in the doc for Container, something like:

"Using anchors in childrens of containers will not work, as these settings are overriden by the container"

**Comment by dploeger** [comment]
Hm. Okay. We should definitely do a layouting guide. I'm currently trying to update the git addon for 3.0 and it has custom, quite complex GUI controls for the editor.

For example: How to layout a toolbar over a pane. The VBoxContainer seems to be the wrong solution, because it seems to layout all children with the same size.

@reduz Can you give me a hand over at discord or the IRC about layouting, so I could write a guide for it?

**Comment by dploeger** [comment]
Oh, my bad. Found one already: http://docs.godotengine.org/en/latest/learning/step_by_step/ui_introduction_to_the_ui_system.html?highlight=grow
