### ISSUE TITLE
Pointless dock appears when editing a Tile Set resource

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15349]
**Godot version:**
3f9f0b3

**Issue description:**
I've played a lot with the Tile Set resource, and everytime this dock appears. As far as I am aware, it doesn't seem to have any purpose at all:
![screenshot1](https://user-images.githubusercontent.com/30739239/34585575-73b44efe-f187-11e7-9401-333688cd3c34.png)

**Steps to reproduce:**
Create a Tile Set resource inside a TileMap node and edit it.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by vnen** [comment]
This is the autotile editor. But I agree it's weird when it's empty.

**Comment by YeldhamDev** [comment]
@vnen Wait, isn't the autotile editor this?

![screenshot1](https://user-images.githubusercontent.com/30739239/34586128-dfc530ca-f189-11e7-886c-c52d7e106d21.png)

**Comment by akien-mga** [comment]
CC @MarianoGnu @damarindra

**Comment by damarindra** [comment]
This is autotile editor, only work on autotile type. Look at inspector, you can see autotile option, set true to make it available on the list. You need to select another node / something you can select, and reselect the tileset.res.

I know there is trouble with updating tileset list, I still find a way how to fix that. Sadly I started working irl, I don't have much time to contribute.

**Comment by YeldhamDev** [comment]
@damarindra I see, thanks for answering me.

Taking the opportunity, could you add this to your list of fixes? The "Properties" section can be made to go out-of-bounds if dragged all the way down:
![screenshot3](https://user-images.githubusercontent.com/30739239/34589717-5b9a75f2-f199-11e7-89e7-c40129821b6c.png)

**Comment by damarindra** [comment]
ok, that was quite simple I think.

**Comment by damarindra** [comment]
but IMO, I prefer that way, because tileset list will grow up, and properties only be used once.

**Comment by YeldhamDev** [comment]
Yes, sure, but it still should be kept inside its container.

**Comment by damarindra** [comment]
I will try to make the properties text still show up. Not the entire window, regarding on low resolution monitor will take a pain.

**Comment by damarindra** [comment]
If you don't like it, maybe you can fix it in your way. I'm not doing whatever I don't like anyway.

**Comment by MarianoGnu** [comment]
properties can be different from one tile to the other, anyway these will be movedto inspector on Godot 3.1

**Comment by MarianoGnu** [comment]
I think this issue can be closed since the dock is not pointless after all, unless you make it visible only if there is at last 1 autotile on the tileset, in that case the bottom panel is useless too

**Comment by damarindra** [comment]
This dock still consistent according to Tilemap dock. Tilemap dock also shows as empty when tilemap has nothing. If someone wants to change it, please also change the tilemap dock as well.
