### ISSUE TITLE
InputEventMouseMotion.global_pos is not set on windows 8.1

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#15354]
**Godot version:**
Godot Engine branch 2.1 sha1: 1eed819

**OS/device including version:**
Windows 8.1 64 Bits (fresh install)

**Issue description:**
Using an unhandled_input handler and moving the mouse will not set the global_pos parameter

**Steps to reproduce:**
Create a viewport and add a node2d with a handler for unhandled_input. The global_pos should not been set.

**Minimal reproduction project:**
Maybe later (I'm a bit tired right now)

**Workaround:**
Use pos attribute instead of global_pos.

**Note**
This issue does not appear on Windows 10, or on Linux

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by reduz** [comment]
ah, i screwed up, this is a 2.1 issue

**Comment by akien-mga** [comment]
Ah, my bad.

**Comment by akien-mga** [comment]
Fixed by #16270.
