### ISSUE TITLE
Separate debugsymbols files not working on FreeBSD

### ISSUE THREAD

**Issue by robfram** [godotengine/godot#15367]
**Godot version:**
0c86c1ad152d2b523dc125eb79e838563b3d5f69

**OS/device including version:**
FreeBSD 11.0-RELEASE-p1 #0 r306420
Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz (2195.06-MHz K8-class CPU)

**Issue description:**
After compiling (with debug symbols enabled), the file with .debugsymbols is detected by file command as corrupted program header size:

```
$ file *
godot.x11.tools.64:                   ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 11.0 (1100122), FreeBSD-style, stripped
godot.x11.tools.64.debugsymbols:      ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), corrupted program header size, for FreeBSD 11.0 (1100122), FreeBSD-style, not stripped
godot.x11.tools.64.llvm:              ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 11.0 (1100122), FreeBSD-style, stripped
godot.x11.tools.64.llvm.debugsymbols: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), corrupted program header size, for FreeBSD 11.0 (1100122), FreeBSD-style, not stripped

```

**Steps to reproduce:**
```
$ scons platform=x11 use_llvm=yes -j 4
$ scons platform=x11 CXX=g++7 CC=gcc7 CCFLAGS="-Wl,-rpath=/usr/local/lib/gcc7" CFLAGS="-Wl,-rpath=/usr/local/lib/gcc7" -j 4
```

**Comment by akien-mga** [comment]
As a comparison, I have this on GNU/Linux (Mageia 6 x86_64) with file 5.25:
```
$ file bin/*
bin/godot.x11.tools.64:              ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=86f7aa7c776c4336d02382f80aad3356ca421d26, stripped
bin/godot.x11.tools.64.debugsymbols: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter *empty*, for GNU/Linux 2.6.32, BuildID[sha1]=86f7aa7c776c4336d02382f80aad3356ca421d26, not stripped
```

**Comment by akien-mga** [comment]
CC @hpvb

**Comment by hpvb** [comment]
That really just means that the 'file' command on FreeBSD is broken. I don't know if/what we should do about this. The separate debugsymbol file should work fine in both lldb and gdb alike (they both support the gnu-debuglink section).

**Comment by akien-mga** [comment]
What's missing from this report is the actual reason why the file output was checked: #15360

**Comment by akien-mga** [comment]
Moving to 3.1 as it's not critical for the 3.0 release.

**Comment by robfram** [comment]
I think we can close this, as the debugsymbols file is functional no matter if file command thinks it is corrupted.
