### ISSUE TITLE
Spatial 'Snap Mode' icon not always in sync with editor 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#15366]
**Godot version:**
30cd6643bea5c38128a0dc285c6aeaf0185d2e7b

**OS/device including version:**
Ubuntu 17.04

**Issue description:**
When saving a scene with snap mode on, then after restarting the editor, the icon will look like snap is off, but editor will still snap spatials. To disable snap, double click on the icon is needed (after first click icon and editor are in sync (both indicating snap), second click turns off the snap).

**Steps to reproduce:**
1. Open 3D Platformer demo 
2. Enable snap mode via icon click. 
3. Translate any spatial and save the scene.
4. Turn off the editor
5. Turn on the editor again.
6.1 Notice that icon indicates that snap is off.
6.2 Select and move any object, you will be able to see that object is snapping to the grid.

**Minimal reproduction project:**

**Comment by reduz** [comment]
@n-pigeon

**Comment by akien-mga** [comment]
Fixed by #15572.
