### ISSUE TITLE
Exported properties in C# revert back to old value when changed during play

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15389]
**Godot version:**
`master` / 8e8240450edc48f4fb379e593a4ef7f54ab656b7 (with the fix applied from #15385)

**OS/device including version:**
_Manjaro Linux 17.1-rc2_

**Issue description:**
When I change the value of an exported property in a C# class from the editor while playing a scene, it immediately reverts back to its old value.

(I'm new to the engine, so there's a chance I don't understand how the property system is supposed to work.)

**Steps to reproduce:**
 - Make a C# class with an exported property, and log its value to the console within the `_Process()` callback.
 - Attach the class to a node and play the scene.
 - Select the node and change the property to some other value in the editor.
 - Confirm that the console shows changed value briefly then reverts back to the old value.

**Comment by neikeq** [comment]
Do you mean in-game hot-reloading is not working?

**Comment by mysticfall** [comment]
Is it normal that you can't change node properties in editor during the play? Moving from Unity, I thought it should work similarly in that aspect.

Urg... maybe I should stop reporting issues before I get better accustomed to how Godot works.

**Comment by akien-mga** [comment]
You need to enable it in the Debug options:
![spectacle x30787](https://user-images.githubusercontent.com/4701338/34640260-9307d1f4-f2ef-11e7-9cf3-fba588a4a71d.png)
(That said, I never tried with Mono so I don't know if it will work)

**Comment by mysticfall** [comment]
I just tried it with _Sync Scene Changes_ enabled and it works perfectly fine with it. Thanks for the information, and sorry for the hassle 😅

**Comment by akien-mga** [comment]
Good, closing then :)
