### ISSUE TITLE
Make the Tool UI also usable in a video projector and presentation

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#15381]
**Godot version:**

8e8240450edc48f4fb379e593a4ef7f54ab656b7

There are still some major issues that I'm forced to patch-out in the 
current godot3 GUI to make it usable for a presentation
and/or with limited screen resolutions:

1) The minimum width of the text editor is greater than needed, forced
by the translation-dependent amount of text in the menu bar.

2) The left text editor panel can't be minimized (i.e. slided away to the left side).
It's waste of space to keep the panel always open in a presentation.

3) It's nice that the code auto-completion and other similar features
can already be disabled in the editor settings - except the automatic
code parsing that can be very annoing and not helpful at all
in a video presentation.

It would be fabulous if that were also configurable in the editor settings.

![godot3-tool-gui](https://user-images.githubusercontent.com/4047289/34635463-f475cab4-f28f-11e7-978d-79296f265ddb.png)

**Comment by volzhs** [comment]
you can move file system dock to right though...

**Comment by capnm** [comment]
I know, but then you have to first explain to your audience why it looks different, how it's done, … ;)

**Comment by akien-mga** [comment]
I agree that we should aim for a usable UI on 1024x768, which is what many projectors sadly still use nowadays.. It doesn't have to be perfect (it's not for daily use), but it should not overflow the screen.

**Comment by capnm** [comment]
I think the new godot3 design is now usable on a smaller screen,
e.g. if you set the parameter "Split mode minimum height" to zero. see (https://github.com/godotengine/godot/issues/21499)
