### ISSUE TITLE
Incorrect statuses of IP and StreamPeerTCP

### ISSUE THREAD

**Issue by VitaZheltyakov** [godotengine/godot#15393]
**Godot version:**
All versions (2.1.x and 3)

**OS/device including version:**
All

**Issue description:**
IP and StreamPeerTCP do not change statuses when a connection is lost or restored (see examples). 

As I understand the problem in the cache. Because using IP.clear_cache () allows you to bypass the bug in the case of IP.

**Steps to reproduce:**
- Connect PC
- Call `print(IP.resolve_hostname(host))` - you get ip-adress
- Disconnect PC
- Call `print(IP.resolve_hostname(host))` - you get ip-adress (wrong)

or

- Disconnect PC
- Call `print(IP.resolve_hostname(host))` - you get ''
- Connect PC
- Call `print(IP.resolve_hostname(host))` - you get '' (wrong)

or 

- Connect PC
- Call `var x = StreamPeerTCP.new() print(x.connect(host, port))` - you get 0 (OK)
- Disconnect PC
- Call `var x = StreamPeerTCP.new() print(x.connect(host, port))` - you get 0 (wrong)

or

- Disconnect PC
- Call `var x = StreamPeerTCP.new() print(x.connect(host, port))` - you get 26 (Error)
- Connect PC
- Call `var x = StreamPeerTCP.new() print(x.connect(host, port))` - you get 26 (wrong)

**Comment by VitaZheltyakov** [comment]
https://github.com/godotengine/godot/issues/18323

**Comment by girng** [comment]
best solution i found so far is just have a timer running every 0.5 seconds (or whatever), that uses one of the put_xxx methods. this way, if the server is dead, it'll trigger get_status

**Comment by VitaZheltyakov** [comment]
https://github.com/godotengine/godot/issues/20289

**Comment by VitaZheltyakov** [comment]
I prepared a demo of the error.
[Error Demo.zip](https://github.com/godotengine/godot/files/2320420/Error.Demo.zip)

**Comment by akien-mga** [comment]
CC @godotengine/network

**Comment by Faless** [comment]
Closing as duplicate as #4157

**Comment by Faless** [comment]
Some notes:

> Connect PC
> Call print(IP.resolve_hostname(host)) - you get ip-adress
> Disconnect PC
> Call print(IP.resolve_hostname(host)) - you get ip-adress (wrong)

This is correct, it's called caching, you can call `IP.clear_cache` to clear it if you don't want it (and will make address resolution slower).

> Disconnect PC
> Call print(IP.resolve_hostname(host)) - you get ''
> Connect PC
> Call print(IP.resolve_hostname(host)) - you get '' (wrong)

This is clearly wrong, I will double check. **(1)**

> Connect PC
> Call var x = StreamPeerTCP.new() print(x.connect(host, port)) - you get 0 (OK)
> Disconnect PC
> Call var x = StreamPeerTCP.new() print(x.connect(host, port)) - you get 0 (wrong)

This is actually okay for how TCP works, you probably had the cached hostname resolved already, and TCP is trying to connect to that IP. The fact that the IP is unreachable when you try to connect is unknown. The connection should stay in status `CONNECTING` for a while, and then timeout after few minutes.

> Disconnect PC
>     Call var x = StreamPeerTCP.new() print(x.connect(host, port)) - you get 26 (Error)
>     Connect PC
>     Call var x = StreamPeerTCP.new() print(x.connect(host, port)) - you get 26 (wrong)

This is wrong, and probably related to **(1)** .

I guess I'll actually re-open this and investigate the cache problem when DNS resolution.

**Comment by Faless** [comment]
There you go, PR is in.
Thank you @VitaZheltyakov for reporting this issue, I'm sorry it took me so long to realize how serious this bug was. The fix should get merged quite soon to `master` as the changes are quite small.

**Comment by VitaZheltyakov** [comment]
> Some notes:
> 
> Connect PC
> Call print(IP.resolve_hostname(host)) - you get ip-adress
> Disconnect PC
> Call print(IP.resolve_hostname(host)) - you get ip-adress (wrong)
> 
> This is correct, it's called caching, you can call IP.clear_cache to clear it if you don't want it (and will make address resolution slower).
> 
> Disconnect PC
> Call print(IP.resolve_hostname(host)) - you get ''
> Connect PC
> Call print(IP.resolve_hostname(host)) - you get '' (wrong)
> 
> This is clearly wrong, I will double check. (1)
`IP.clear_cache` - this is not a common mechanism. This approach is implemented only in Godot. He is not logical and uncomfortable.

This behavior of this function can lead to a situation where we will execute queries when there is no connection.
