### ISSUE TITLE
Script editor area goes under other editor windows

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#15394]
**Godot version:**
3.0 beta2

**Issue description:**
If there are no matches in search&replace, the text area for scripts goes under the scene/inspector.
Removing search term in search&replace (so the "No Matches" red label goes away) fixes the issue, after switching to another view (2D/3D) and going back to script

**Steps to reproduce:**
1. Search for something that doesn't exist with search&replace
2. If the window is not wide enough, the "No Matches" label will overflow on the right, bringing the script text editor area along

![photo5947218554979986159](https://user-images.githubusercontent.com/7917475/34639017-e16c1dae-f2d7-11e7-8003-00a7de8fad96.jpg)

![photo5947218554979986160](https://user-images.githubusercontent.com/7917475/34639033-43aef31a-f2d8-11e7-81d6-a91079b9868d.jpg)

**Comment by akien-mga** [comment]
CC @Paulb23 @ianb96 @volzhs

**Comment by capnm** [comment]
Something like this?
By the way, the `Replaced 0 oc.` seems to be pointless and the probably more useful `Replaced xy oc.` is missing.

![grafik](https://user-images.githubusercontent.com/4047289/34640992-69eb60a2-f2fd-11e7-88fd-a02ad79ffee6.png)

**Comment by ianb96** [comment]
This happens in general when resizing the script editor when the find replace bar is open.
![find_resize](https://user-images.githubusercontent.com/10054226/34653478-397edbd4-f3ba-11e7-832d-55e0bd432aea.gif)
This also happens with the shader editor.
see #14812

**Comment by capnm** [comment]
The text in the animation editor has also overflow problems:

![grafik](https://user-images.githubusercontent.com/4047289/34654015-bee59246-f3f5-11e7-9eff-fef6376b69a6.png)

**Comment by YeldhamDev** [comment]
The code editor doesn't have this overflow problem in 2.1.4. Something changed in the 3.0 version.
