### ISSUE TITLE
Allow spaces in auto-loaded node name (or disallow them in normal nodes)

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15390]
**Godot version:**
`master` / 8e8240450edc48f4fb379e593a4ef7f54ab656b7 (with the fix applied from #15385)

**OS/device including version:**
_Manjaro Linux 17.1-rc2_

**Issue description:**
It seems that _Godot_ allows spaces in a node name, as it apparently doesn't produce any error with normal nodes.

However, if I try to register an auto loaded node from the project dialog, it shows a validation error when I try to enter a name which includes a space as the name of the node.

Probably, it'd be better if we could make it consistent across the engine, so that it either allows such names or disallows them in all cases.

**Comment by akien-mga** [comment]
The name of the AutoLoad should not have spaces, as you can use it directly as an identifier in your scripts. For example if you register an AutoLoad named "Game" with a `run()` method, you can do e.g. `Game.run()` from any script. If it were named "My Game", I think you can imagine that no scripting language would let you do `My Game.run()`.

On the other hand non-AutoLoad node names can't be used as identifiers, but only as strings, so it's fine to use spaces in them. If you have a child node named "My Game", you can do `get_node("My Game")` or `$"My Game"` to retrieve it.

**Comment by mysticfall** [comment]
Ah, that makes sense. Thanks for the explanation!
