### ISSUE TITLE
Call to Contributors: Please help close issues for 3.0

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#15404]
As a call to everyone contributing, the betas did a great job and users reported a lot of new issues. 
It would be fantastic to release a 3.0 stable this month, but for this we will need everyone's help.

There are, at the time of this writing, around 200 open bugs marked 3.0:

https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.0

It's not a large number, considering the past months we closed more than 1400, but still significant.

There are bugs of different severities and many are probably not bugs but documentation issues. I've been working on closing the remaining ones for the past weeks, but more hands would be very welcome so our new release is as stable as possible. 

If you are working on new features, or you are not used to closing issues outside the areas you have more expertise, I will kindly ask to lend a hand this month to helping make the new release as best as possible. 

Any help you need, feel free to drop by IRC on # godotengine-devel channel.

**Comment by akien-mga** [comment]
Closing to reduce to 3.0 backlog ;)

But the call is still valid, thankyou to all contributors who worked hard up to now to close 3.0 issues, we've managed to reduce the backlog to around 100 tickets: https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0

There's still some way to go and we want to release 3.0 within a week, at most two, so please all double the efforts to fix the remaining blockers.
