### ISSUE TITLE
Built-in tool scripts aren't reloaded unless the scene is reloaded

### ISSUE THREAD

**Issue by bluegamepoy** [godotengine/godot#15406]
**Godot version:**

Godot 3.0

**OS/device including version:**

Windows 10

**Issue description:**

I just want to report an issue with tool mode. Tool mode only updates my object in the editor when I make changes to my exported variable, after I restart the editor. Basically tool mode doesn't unless the editor is restarted. 

**Steps to reproduce:**
Ex: 
tool
extends Panel

export (int) var  orientation = 0 setget orientation_set

func orientation_set(new_value):
	orientation = new_value
	set('rect_rotation', orientation) 

// So everytime I make changes to the orientation_set() function, I have to restart the editor. Not  a major problem but its a hassle closing and opening godot. 

**Minimal reproduction project:**

[ToolBug.zip](https://github.com/godotengine/godot/files/1608930/ToolBug.zip)

**Comment by Zylann** [comment]
Does closing and reopening the scene makes it work?

**Comment by bluegamepoy** [comment]
> scene



> Does closing and reopening the scene makes it work?

Oh yeah, it does.

**Comment by bluegamepoy** [comment]
> Can't reproduce on latest master

I tried and its the same in the latest master. When I make change to the script, saving the scene also works. Guess this is not really a major problem.

**Comment by hetdegon** [comment]
Is the script built-in?

**Comment by bluegamepoy** [comment]
> Is the script built-in?

I saved the script, and now changes takes effects everytime I save the scene.

**Comment by hetdegon** [comment]
Ah figured. I noticed it still happened in 3.0 and came to see if there was any related issue. I'm pretty sure I reported it happening with builtin scripts way back, but I can't remember if anything came out of it.
Should look it up and maybe link to this issue if I can find a minute later.

**Comment by AssjackGames** [comment]
Just wanted to mention I also seem to have this bug (v 3.0), that is I can also reproduce it.
Oddly enough when I run the test project above it works fine, but it affects my own project.

**Comment by PLyczkowski** [comment]
Noticed a related issue: vars exported in tool mode, for example:
`export(int, "Warrior", "Magician", "Thief") var character_class`
after once set and then changed for instance to:
`export(int, "Warrior", "Magician", "Thief", "Test") var character_class`
don't get updated until editor restart (scene reopening does not update them).

**Comment by PLyczkowski** [comment]
^ Seems to only happen when saving script in external text editor? Saving in Godot editor and then reloading scene fixes the issue.

**Comment by T4g1** [comment]
Seems related to #17044

**Comment by akien-mga** [comment]
I could reproduce it on the master branch, and it only happens with builtin scripts (embedded in the scene file). If you save your tool script as .gd file, it gets properly reloaded on the fly.

**Comment by hetdegon** [comment]
Yeah I'd very much like it to reload builtin scripts. At times your logic is just 10 lines long and it's not worth it to pollute the file layout any further with more tiny files (having an extra file for every image is already overkill and uncomfortable).

**Comment by GlaDOSik** [comment]
After an hour of head scratching, I found this issue. Hope this is going to be fixed soon. I'm developing a pretty complex plugin so built-in scripts are important to me. But this bug makes the development painful.

**Comment by Calinou** [comment]
The external editor part is already being tracked in #29379. See also #31758.
