### ISSUE TITLE
Windows crashes using Godot beta 1 - 2 

### ISSUE THREAD

**Issue by Whyimsobroke** [godotengine/godot#15408]
Major bug!!! #14472 

When ever i use Godot3 beta 1, after some random time (when trying to run a scene) my whole windows 10 crashes,, first time as i ran scene, my laptop froze completely, had to shut down, 2nd time (just now) Godot3 beta 2 froze and my my screen froze to, but periodicly it refreshed it self, like as if the frame rate was 1 frame per 4~ seconds, had to shut down it again. Now im completely scared to use Godot3, lol
P.S. I cant post errors because windows freezes..

**Comment by eon-s** [comment]
Check the system log, can be something else (GPU, memory, disk failure).

**Comment by Zireael07** [comment]
What is your specs? Might be your GPU/CPU can't handle it and is overheating?

**Comment by vnen** [comment]
Check the Event Viewer to see if it has a relevant information. Try to open Godot from the command prompt and redirect the output to a file, then you can check it even if your computer freezes.

Godot isn't able to freeze your whole system, so this might be a problem elsewhere in the system and Godot is just triggering it somehow.

**Comment by akien-mga** [comment]
Sadly there isn't much information here for us to fix anything (understandably so, it's hard to debug something that triggers a BSOD). There are two possibilities:
- Either it's specific to your system (so far I haven't seen any other reports of Windows crashing when using Godot, so it's the most likely)
- Or it's a real Godot crash which somehow messes up your system, but then chances are it's fixed already in the master branch (dozens of crash scenarios were fixed recently).

Closing for now as we can't do anything, but if you can still reproduce it in the upcoming Godot 3.0 RC1, and get more debug infos, please comment here and we can reopen it.

**Comment by RevoluPowered** [comment]
Having the same issue with iGPU.

Causing windows to restart. I'm betting its something to do with the intel opengl driver

I'll see if i can reproduce this on my other computers
