### ISSUE TITLE
Kinematic Character 3D demo shows buggy KinematicBody/GridMap collisions with Bullet

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#15417]
**Godot version:**
Master, 50b97554

**OS/device including version:**
Mageia 6 x86_64

**Issue description:**
When playing the [Kinematic Character 3D](https://github.com/godotengine/godot-demo-projects/tree/master/3d/kinematic_character) demo, the player does little jumps all the time when in contact with the floor:
![peek 06-01-2018 22-57](https://user-images.githubusercontent.com/4701338/34644348-250ed6ca-f335-11e7-96bc-fe2183a2b808.gif)
The terminal is also spammed with Bullet errors:
```
ERROR: remove_owner: Condition ' !E ' is true.
   At: modules/bullet/shape_bullet.cpp:85.
ERROR: remove_owner: Condition ' !E ' is true.
   At: modules/bullet/shape_bullet.cpp:85.
ERROR: remove_owner: Condition ' !E ' is true.
   At: modules/bullet/shape_bullet.cpp:85.
ERROR: _body_inout: Condition ' !body_in && !E ' is true.
   At: scene/3d/area.cpp:160.
...
ERROR: remove_owner: Condition ' !E ' is true.
   At: modules/bullet/shape_bullet.cpp:85.
ERROR: remove_owner: Condition ' !E ' is true.
   At: modules/bullet/shape_bullet.cpp:85.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
ERROR: getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
   At: core/rid.h:165.
ERROR: instance_remove_dependency: Condition ' !inst ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5972.
```

When switching the physics engine to GodotPhysics, it works as expected.

**Steps to reproduce:**
- Run the [Kinematic Character 3D](https://github.com/godotengine/godot-demo-projects/tree/master/3d/kinematic_character) demo

**Minimal reproduction project:**
See above.

CC @AndreaCatania

**Comment by eon-s** [comment]
It was working fine like a week ago, now small safe margin makes the body bounce like that (again), high margin makes the body bounce a lot (as is supposed to, btw).
