### ISSUE TITLE
Files not shown in filesystem dock

### ISSUE THREAD

**Issue by ibrahn** [godotengine/godot#15410]
**Godot version:**
master / 9884597bb3872cd17854b54695344dcb279a2c89

**OS/device including version:**
Debian Buster x86-64

**Issue description:**
Filesystem dock only displays script (.gd) files.
Newly created scenes will be shown, but are not there when the project is reopened.

**Minimal reproduction project:**
[filesystem-test.zip](https://files.glitchmill.com/m/jkxeyg5mv2fq6a34/filesystem-test.zip)

**Comment by capnm** [comment]
b1ab44aa05994a19f0bae5e700c4007b870a8ecf was ok, it happened in some commit afterwards.

**Comment by ibrahn** [comment]
it's fine at 0e6e98a65f26c915b5717992ba881cf33406c8bf
looks like the merge of #15395 is the issue

**Comment by NathanWarden** [comment]
Yep, just noticed this a little while ago too :)

**Comment by akien-mga** [comment]
Should be fixed by 50b97554.
