### ISSUE TITLE
Area2D requires wait time after enabling collisions

### ISSUE THREAD

**Issue by nmearl** [godotengine/godot#15419]
**Godot version:**
Godot 3.0 Beta 2

**OS/device including version:**
Elementary OS 0.4.1 Loki (Ubuntu 16.04.3 LTS)
Linux 4.10.0-42-generic

**Issue description:**
Having `Area2D` with an attached `CollisionShape2D`, and (in my case) a `CirculeShape2D` with the `CollisionShape2D` initially disabled, enabling the `CollisionShape2D` in code and attempting to call `get_overlapping_bodies` returns an empty array. However, adding two `yield(get_tree(), "idle_frame")` (or two `physics_frame`) before attempting to call `get_overlapping_bodies` results in a returned array that is properly populated.

**Steps to reproduce:**
*Does not work*
```
get_node("Area2D/CollisionShape2D").set_disabled(false)
print(get_node("Area2D").get_overlapping_bodies())
get_node("Area2D/CollisionShape2D").set_disabled(true)
```
>` []`

*Works*
```
get_node("Area2D/CollisionShape2D").set_disabled(false)

yield( get_tree(), "idle_frame" )
yield( get_tree(), "idle_frame" )

print(get_node("Area2D").get_overlapping_bodies())
get_node("Area2D/CollisionShape2D").set_disabled(true)
```
>` [[KinematicBody2D:1068]]`

**Comment by reduz** [comment]
This is by design and not a bug. You need to wait until the physics process for this to take effect.
The reason is that processing all collisions at one is a lot more efficient than doing it every time something moves.

**Comment by reduz** [comment]
Is it docummented by the way? This could be a documentation problem.

**Comment by reduz** [comment]
Also, in general, testing for overlapping bodies in every frame is extremely inefficient. Godot gives you signals for when bodies overlap and de-overlap, so just do your tests there, which is a lot more efficient.

**Comment by nmearl** [comment]
Thanks for the response. I did not see documentation suggesting this is the case. 

> Godot gives you signals for when bodies overlap and de-overlap, so just do your tests there, which is a lot more efficient.

I use `body_entered` signals prolifically around my game, but there is a case where a need an `Area2D` to "wake up" in response to a player input, and quickly grab all `PhysicsBody2D` around it and return the array. This would not happen often, but this doesn't seem possible using `body_entered`, as it only provides a single `PhysicsBody2D` and not all of them within an area.

Is there a recommended way to instantaneously get all `PhysicsBody2D`s within an area in response to some input?

**Comment by poke1024** [comment]
@nmearl You need to work directly on `Physics2DDirectSpaceState` if you cannot wait for the physics process. This works, but is not documented at all AFAIK.
