### ISSUE TITLE
"Indented block expected." error doesn't trigger if there isn't a new line below the function

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15415]
**Godot version:**
9cf19f8

**Issue description:**
Maybe this is intentional, but the the error doesn't appear if there isn't a new line below it, and the project plays fine:
![screenshot at 2018-01-06 19-02-28](https://user-images.githubusercontent.com/30739239/34643925-3c63edfe-f314-11e7-9a63-93337117cf65.png)
![screenshot at 2018-01-06 19-02-55](https://user-images.githubusercontent.com/30739239/34643926-3c8b6488-f314-11e7-8964-7bfea3d02e97.png)

Also, it's supposed to output this when the error appears?
`
current: 0 indent: 0
less than current
`

**Comment by Oklomsy** [comment]
aaaaaa

**Comment by Oklomsy** [comment]
Why isn't a solution tho?

**Comment by YeldhamDev** [comment]
@Oklomsy The issue was fixed, what are you talking about?

**Comment by joshuaagega** [comment]
Nice
