### ISSUE TITLE
High Audio Latency using WASAPI

### ISSUE THREAD

**Issue by NyxTheShield** [godotengine/godot#15430]
**Godot version:**
Godot 3 beta 2

**OS/device including version:**
Windows 10
HP Omen 15
i7 7700HQ
Nvidia Gtx 1050 4gb
8gb DDR4 ram
Using an Scarlett Focusrite 2i4 Audio Interface

**Issue description:**
I am experiencing massive Underruns and high latency using the latest beta 2 with Godot 3. At least 200 ms of delay between an action and actually playing the sound, with a lot of underruns when playing more than 1 sfx at the same time.

**Steps to reproduce:**
Just run a  project and play audio.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
CC @marcelofg55

**Comment by marcelofg55** [comment]
Hi, did you try running godot with the RtAudio driver (--audio-driver RtAudio-DirectSound)? Does the same happens with it?
And did you try using the onboard sound from your HP instead of your Audio Interface?

**Comment by NyxTheShield** [comment]
@marcelofg55 I dont know how to enable the RtAudio driver. I tried using RTAUDIO in the project settings but I got a Invalid Audio Error. I will try using my onboard soundcard now

**Comment by vnen** [comment]
The name of the driver to put in Project Settings is `RtAudio-DirectSound`.

**Comment by akien-mga** [comment]
> The name of the driver to put in Project Settings is `RtAudio-DirectSound`.

Is this a free field for now? This should be made an enum.

**Comment by NyxTheShield** [comment]
I retested using the RtAudio-DirectSound driver and the latency is mostly gone, but I am still experiencing Audio artifacts

**Comment by marcelofg55** [comment]
And with the onboard soundcard?

**Comment by NyxTheShield** [comment]
Yes, with, both. I just noticed that it might be related to the audio samples themselves tho. They work perfectly fine outside of godot but produce artifacts when stopped. Disabling the loop on them removes that. Here is a sample that produces a noticeable artifact


[ledge.zip](https://github.com/godotengine/godot/files/1612486/ledge.zip)

**Comment by akien-mga** [comment]
Given the imminent release of 3.0 and the fact that this bug seems hardware-specific and thus hard to debug/fix, I'm moving it to the next milestone. But rest assured that it stays high on the priority list to fix for 3.1 and 3.0.x releases.

**Comment by akien-mga** [comment]
Assumed fixed by #17857, which should be in the future 3.1 and might come in a 3.0.x release (3.0.3 or later).
