### ISSUE TITLE
Opening create_dialog popup does not select tree root

### ISSUE THREAD

**Issue by Stoeoeoe** [godotengine/godot#15442]
Godot version:
v3.0-beta2_win64

OS/device including version:
Windows 10, 64-bit

**Issue description:**
When adding a new node to a scene, the "Create New Node"/create_dialog popup must be opened. By default, the text of the "search box" is empty. However, the "description text" field below shows that the "Area" node is selected, most likely because it is first in the alphabet. 
It is possible to navigate the tree hierarchy with the up and down arrow keys.

Expected behavior: When there is no text in the Search Box, select the root, i.e. "Node".

**Steps to reproduce:**
* Create a new project
* Click on the + button in the scene tree
* Look at the description of the currently selected node
* Move up and down with the arrow keys and wonder a bit

**Comment by vigreco** [comment]
I noticed it too. If there is a Node2D in the scene, `YSort` seems to always be selected instead.

I would like to make a PR for this. I'm quite new to Godot source code so I need a little confirmation here before I'm going to do something wrong.

@akien-mga do you think something very simple like this would be enought?

```diff
diff --git a/editor/create_dialog.cpp b/editor/create_dialog.cpp
index 2dfb01826..de0aef298 100644
--- a/editor/create_dialog.cpp
+++ b/editor/create_dialog.cpp
@@ -312,6 +312,10 @@ void CreateDialog::_update_search() {
                }
        }

+       if (search_box->get_text() == "") {
+         to_select = root;
+       }
+
        if (to_select) {
                to_select->select(0);
                search_options->scroll_to_item(to_select);

```

**Comment by vigreco** [comment]
I'll double check this, but currently when the search box is cleared, it always selects `Area` (or `YSort`) independently from the latest selection.

**Comment by akien-mga** [comment]
Ok, then your fix should be fine IMO.
