### ISSUE TITLE
Some editor properties are no longer persistent

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#15449]
**Godot version:**

380169e3efb959cfeaa3884a3cd440ab84bff9ae

**OS/device including version:**

linux

**Issue description:**
The capitalize_properties, disable_inspector_folding, restore_scenes_on_load
and possibly other properties are reset to default after a tool restart.

**Steps to reproduce:**
Set the property in the editor settings, restart the tool.

diff --git a/editor_settings-3.tres b/editor_settings-3.tres

```
-interface/editor/capitalize_properties = false
-interface/editor/disable_inspector_folding = true
+interface/editor/capitalize_properties = true
+interface/editor/disable_inspector_folding = false

-interface/scene_tabs/restore_scenes_on_load = true
+interface/scene_tabs/restore_scenes_on_load = false
```

```
editor/editor_node.cpp:
	property_editor->set_enable_capitalize_paths(bool(EDITOR_DEF("interface/editor/capitalize_properties", true)));
	property_editor->set_use_folding(!bool(EDITOR_DEF("interface/editor/disable_inspector_folding", false)));
```

**Comment by vnen** [comment]
Maybe related to #15396? CC @volzhs

**Comment by capnm** [comment]
Yep, 6ad43757adbfad0163e639e8425aeaddc6e38018 somehow screws the handling of those props.

**Comment by akien-mga** [comment]
This is a neverending story... CC @djrm

**Comment by volzhs** [comment]
it seems my #15396 causes this. will take a look.
