### ISSUE TITLE
Godot editor crashes inconsistently when Playing Project

### ISSUE THREAD

**Issue by gamerminstrel** [godotengine/godot#15454]
**Godot version:**
Godot_v3.0-beta2_mono_x11.64

**OS/device including version:**
Kubuntu 17.04 (x11_64), 
nvidia gtx660 with nvidia binary driver version 384.90

**Issue description:**
Godot inconsistently keeps crashing (usually) within 15 minutes of me reopening my project. I've gotten about 9 crashes now but I can't figure out what specifically is causing it.

```
ERROR: gdmono_MonoLogCallback: Mono: FATAL ERROR, ABORTING! Logfile: /home/minstrel/.local/share/godot/mono/mono_logs/1515347849.txt
   At: modules/mono/mono_gd/gd_mono_log.cpp:73.
```

then after the huge wall of text in the error log it ended with this:

```
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

Nothing read: Connection reset by peer
ERROR: read: Server disconnected!
   At: drivers/unix/stream_peer_tcp_posix.cpp:275.
```

**Steps to reproduce:**
I open Godot 3.0, open up the Player script in Monodevelop, and by adding lines of code using monodevelop and hitting play to test out my game Godot itself will sometimes crash, but the player will stay open.

**Minimal reproduction project:**
[yggdragodot3.0-Alpha.zip](https://github.com/godotengine/godot/files/1610069/yggdragodot3.0-Alpha.zip)

here's a crash log, if it helps.
[1515347849.txt](https://github.com/godotengine/godot/files/1610070/1515347849.txt)

**Comment by neikeq** [comment]
This happens when unloading the scripts domain (during assembly reloading), when we have the `System.Diagnostics.Process` instance for MonoDevelop. It's weird, because we run that process from a different domain...

**Comment by VitaZheltyakov** [comment]
https://github.com/godotengine/godot/issues/15393
