### ISSUE TITLE
AnimateSprite bugged out when trying to drag and drop frames 

### ISSUE THREAD

**Issue by Arkinum** [godotengine/godot#15456]
**Godot version:**
3 Beta 2

**OS/device including version:**
N/A

**Issue description:**
 When trying to bulk drag and drop several .PNG files (shift + select) to the animation creation window in the AnimateSprite node,  the cursor will randomly snap to the center of the view-port and get stuck and disappear.  Can see the cursor if you hold the middle mouse button, but continuously snaps to the center of the view-port.

The CMD console gives me this error for every frame ERROR: Can't add child 'Node2D' to '@@6299' already has a parent '@@6299'
scene/main/node.cpp:1327

EDIT: sorry it was '@@6299' I had 6200 for the second one.
**Steps to reproduce:**
It seems to happen more frequently if you drag and drop 60+ frames constantly.

**Minimal reproduction project:**

**Comment by reduz** [comment]
Can no longer reproduce. I think this was fixed in the change to raw input on Windows. Please re-open if you can still reproduce by adding proper instructions, demo project and/or a video.
