### ISSUE TITLE
Cannot use TEXTURE_PIXEL_SIZE and the like in canvas_item vertex shader

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15450]
Godot 3.0 beta 2
Windows 10 64 bits
nVidia geforce 940M

EDIT: these are available in fragment shader, so that would be a feature request. Which is certainly doable IMO because that option has to come from an internal `uniform`.

This builtin variable can be used in 2.1.4 to get the size of one pixel in a shader so we don't need to pass the size of the texture everytime. It's hightlighted in 3.0 but not recognized:

![image](https://user-images.githubusercontent.com/1311555/34651719-f269b858-f3d3-11e7-90bc-b1b7f8a8cc19.png)

The same goes for `SCREEN_PIXEL_SIZE`.
The use case here is to displace UVs in the vertex shader (which is obviously less costy than the pixel shader and less boilerplate to get world positions etc).

```
type is: canvas_item
0 shader_type canvas_item;
1
2 void vertex() {
3       UV.x = VERTEX.x * TEXTURE_PIXEL_SIZE;
4 }
5
SCRIPT ERROR: (null): Unknown identifier in expression: TEXTURE_PIXEL_SIZE
          At: :4
ERROR: RasterizerStorageGLES3::_update_shader: Condition ' err != OK ' is true.
   At: drivers\gles3\rasterizer_storage_gles3.cpp:1671
```

**Comment by ywaby** [comment]
version: Godot 3.1 aphla 3
system: debian buster

still has this problem. 
not report error, but TEXTURE_PIXEL_SIZE value is 0

**Comment by deepmax** [comment]
Same problem in Godot 3.0.6,
However documentation doesn't say anything about  `TEXTURE_PIXEL_SIZE` in vertex built-ins of `canvas_item`, but I wonder how it is possible to know the size there while it's necessary in many situations.

**Comment by ywaby** [comment]
@deepmax 
Simplest way is view value in visual shader.

![view](https://user-images.githubusercontent.com/12198203/50879408-bc728000-1415-11e9-965d-62d4e23fcf87.png)

Or put the  TEXTURE_PIXEL_SIZE value to [output] COLOR in script shader .

**Comment by Chaosus** [comment]
![image](https://user-images.githubusercontent.com/3036176/64318436-ba6fb980-cfc2-11e9-8fd0-9ba3e931a4ba.png)

Seems like its fixed, closed by bugsquad.
