### ISSUE TITLE
UI Incorrect (maybe) Labels in attach script inherits 

### ISSUE THREAD

**Issue by Shockblast** [godotengine/godot#15466]
**Godot version:**
3.0B 37ca542d2bfd9aac296e82e30a76117090dea08e
Compiler VS2017
SCons 2.5.1
Python 2.7

**OS/device including version:**
Windows 10 64 bits

**Issue description:**
(sorry my english)
UI
Incorrect text, label or "menu" in attach script -> inheritance -> Open file (Icon).
It works well but it can be confusing.
![bad](https://user-images.githubusercontent.com/5357217/34654577-a38bbe3a-f3dc-11e7-9c48-4c549174520a.jpg)

**Steps to reproduce:**
Create a new scene
Create a root Node in the new scene
Add a new child node in the root Node 
Go to Attach script menu in new child Node
Go To the Inherits section and click in the icon folder

**Observations**
In the Inspector -> Node -> Script -> Load, the menu is correct, you could use the same 😄

**Minimal reproduction project:**
just attach the script in the "child node" and click in icon folder in "Inherits"
[GodotBeta.zip](https://github.com/godotengine/godot/files/1610250/GodotBeta.zip)

**Comment by akien-mga** [comment]
The fix here is not to change the FileDialog mode to Open as done in the now reverted #15504, as this dialog needs to be able to create files (hence the use of the Save mode).
Maybe the title and OK button labels can be reworded for clarity though.

**Comment by YeldhamDev** [comment]
@akien-mga Wouldn't the solution be setting it to Open when choosing what to inherent and setting to Save when selecting a script?

**Comment by Jerome67000** [comment]
Tested on the current master (with my revert commit and new PR #15544 not merged) and it never create an empty new gd file if you fill the file name with an inexistent class.

Also I don't understand what is the purpose to inherits from a class you create in the same time as you create the child class...it's confusing.

**Comment by akien-mga** [comment]
> Also I don't understand what is the purpose to inherits from a class you create in the same time as you create the child class...it's confusing.

This dialog is not only used to inherit from a class, it's also used to create a new script and attach it to a node.

**Comment by Jerome67000** [comment]
The solution can be to split into two sparates dialog popup :
* Inherits : Open a file
* Path : Save a file

This avoid the overkill and confusing part of Inherits dialog allowing to create new gdscript.

**Comment by akien-mga** [comment]
Well to be honest I don't really see the point of the Inherits dialog, I think it's overkill (I understand the use case, but personally I just create my script with default inheritance and then I set `extends "res://my_base.gd"` manually.

**Comment by Jerome67000** [comment]
For me it's overkill too, but most IDE propose it when you create a new class, so well...why not.
