### ISSUE TITLE
Constructing color from hex-string in C# produces values in 0-255 range

### ISSUE THREAD

**Issue by Pandazuechter** [godotengine/godot#15468]
**Godot version:** Godot3 beta2 Mono
As the title says, Color(string), where string is a hexadecimal representation of a color, constructs a Color with values between 0 and 255 as opposed to 0 and 1.

**Steps to reproduce:**
```CSharp
Color w1 = new Color("ffffff");
Color w2 = new Color(1.0f, 1.0f, 1.0f);
GD.Print("w1=" + w1.ToString() + " w2=" + w2.ToString());
```
> w1=255,255,255,1 w2=1,1,1,1

It works correctly in GDScript:
```
var w1 = Color("ffffff")
var w2 = Color(1.0, 1.0, 1.0)
print("w1=%s w2=%s" % [w1, w2])
```
> w1=1,1,1,1 w2=1,1,1,1

I noticed it when I was linear interpolating between "000000" and "ffffff". A t-value of 0.5 outputs pure white when written to an image, instead of the expected grey.

**Comment by akien-mga** [comment]
CC @neikeq
