### ISSUE TITLE
HTML5 Runtime Error On Mouse Enter Viewport

### ISSUE THREAD

**Issue by jedStevens** [godotengine/godot#15464]
**Godot version:**

37ca542d2bfd9aac296e82e30a76117090dea08e

**OS/device including version:**

Manjaro

**Issue description:**

Can't run in browser due to a Runtime Error in the inspector console.

All the info I get is below

    RuntimeError: index out of bounds
    __ZN6Object12notificationEib
    _send_notification
    RuntimeEnvironment/Module._send_notification
    <anonymous>

I think it has something to do with textured materials as I was sometimes seeing a running game with textureless materials,

Now its just a black screen and I get this error when I move the mouse into it.

**Comment by jedStevens** [comment]
It must have something to do with textured materials because now I'm jumping around projects finding that all of the textured materials aren't showing their texture and rather using their vertex coloring.

The project causing the full crash is still not at all running and showing a blank black screen now.

**Comment by akien-mga** [comment]
CC @eska014

**Comment by jedStevens** [comment]
More updates, i got the broken project to run by removing the broken materials, mostly the ones imported via gltf, and it runs without textures. I guess this may aid someone who actually knows what's going on

**Comment by jedStevens** [comment]
Another one, I checked the output from Chrome/Vivaldi and it was saying that there was a texture issue, causing a black screen. On firefox it gave me a running game and black textures.

This was the error from chrome/vivaldi
`[.Offscreen-For-WebGL-0x11cd4bc96200]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.`
