### ISSUE TITLE
Closing a script prints an error in the output

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15478]
**Godot version:**
37ca542

**Issue description:**
When closing a script, the following error is printed in the output tab:
```
 core/rid.h:165 - Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
 servers/visual/visual_server_canvas.cpp:329 - Condition ' !canvas_item ' is true.
```
Closing help files don't print the error.

**Comment by Zylann** [comment]
I noticed that too in https://github.com/godotengine/godot/issues/10359
With the MSVC debugger attached, it also produces a crash.
