### ISSUE TITLE
"Expand All Properties" editor setting not working

### ISSUE THREAD

**Issue by vybr** [godotengine/godot#15473]
**Godot version:** fe841fe

**Issue description:**
Under **Interface > Editor** in editor settings.
New objects have all their properties collapsed even with the setting enabled, and the fact that the state is saved per object makes editing properties a tad fiddly.

**Comment by Keetz** [comment]
Could you clarify why you closed this again?

I am on b49f32d and i am still having this problem

**Comment by akien-mga** [comment]
Yes, please always explain why you close an issue, we can't read your mind.

**Comment by vybr** [comment]
Apologies, I made a mistake. Thought it was essentially a duplicate of #15449.

**Comment by Keetz** [comment]
This seem to be working in the release of 3.0
When the settings has changed, just restart Godot and voila!

Tested on two different computers

**Comment by KoBeWi** [comment]
In 3.1 there's an option called "Disable Folding" under Inspector Editor Settings that does basically this.
