### ISSUE TITLE
UI doesn't allow to set spheremesh size smaller than 10 cm

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15472]

**Comment by Jerome67000** [comment]
Can you be more precise and add steps for reproduce please ?

Where is this `Size` in inspector ? CubeMesh per expemple allow to set value like `0.005` for her size parameter. I see `Top Radius` for CylinderMesh don't allow to set value smaller than 0.1, you are talking about that ?

**Comment by icnikerazah** [comment]
radius and height of spheremesh in inspector

**Comment by icnikerazah** [comment]
i cant set size of snooker ball at real world unit in inspector. i can set by script.

**Comment by Jerome67000** [comment]
Ok I will fix this.

**Comment by Jerome67000** [comment]
snooker ball ? please, use the godot vocabulary...

**Comment by icnikerazah** [comment]
snooker ball = sphere mesh. it's an example.

**Comment by Calinou** [comment]
This should be easy to fix by tweaking the property hint "minimal" values.

**Comment by lokesh-sharma** [comment]
I have corrected the issue . what should be the minimum and step values . I have made minimum to be 0 and step to be 0.01

**Comment by Jerome67000** [comment]
It is already corrected, seems the referenced PR above.

**Comment by akien-mga** [comment]
Issue has been vandalized by its author, so closing.
