### ISSUE TITLE
It's not clear who wins in the depth prepass project settings

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#15482]
**Godot version:**

37ca542d2bfd9aac296e82e30a76117090dea08e

**Issue description:**
The disable check-box isn't needed:

![autsch](https://user-images.githubusercontent.com/4047289/34665759-bb7cde04-f461-11e7-802c-8df8359cb963.png)

**Comment by icnikerazah** [comment]
my feature request: toggle buttons for on off

**Comment by akien-mga** [comment]
`rendering/quality/depth_prepass/disable` should be removed, it's not used.

The other two are defined here: https://github.com/godotengine/godot/blob/34c988cfa92f19c232b65990704816ba1c7d2622/servers/visual_server.cpp#L1958-L1959

And used here, where you can see that `disable` is defined but unused (and should thus be removed there): https://github.com/godotengine/godot/blob/bfeaf27a3e41cd60ec7be4c1d88a3edd2c2a6d87/drivers/gles3/rasterizer_storage_gles3.cpp#L7254-L7261

**Comment by akien-mga** [comment]
> `GLOBAL_DEF("rendering/quality/depth_prepass/disable_for_vendors", "PowerVR,Mali,Adreno");`

While fixing this issue, I'd propose to change the String to `"PowerVR, Mali, Adreno"`, to make it clear that it's comma-separated but that it's OK to use spaces (they're stripped eventually). That's just cosmetic though :)

**Comment by Jerome67000** [comment]
If it's a junior job I will give a try tonight

**Comment by akien-mga** [comment]
It's literally a "remove the line @akien-mga said should be removed" job :P

**Comment by volzhs** [comment]
fixed by #15500

**Comment by capnm** [comment]
![grafik](https://user-images.githubusercontent.com/4047289/34724763-59214fee-f54f-11e7-9764-5170d02715b9.png)
