### ISSUE TITLE
Changing the help's font size doesn't update already opened help docs

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15493]
**Godot version:**
efe27c6

**Issue description:**
When changing the help's font size, any help doc already opened will retain its size. New ones still obey the new size.

**Comment by akien-mga** [comment]
CC @volzhs

**Comment by volzhs** [comment]
yeap. changing font is not applied on opened docs also.

**Comment by YeldhamDev** [comment]
@volzhs So, any progress on this?
