### ISSUE TITLE
Editor font size is not respected

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15502]
Godot 3.0 master d2f4964f58272444f33d6397939ca076b6e1b8f6

I noticed the editor font size I've set some time ago is now ignored and fixed to something around 14.
It doesn't change if I try to modify the size in Editor Settings, and restarting the editor doesn't do anything either.
I believe it's a recent regression.

![image](https://user-images.githubusercontent.com/1311555/34690962-62ce6282-f4bb-11e7-9195-41dff8469ce3.png)
Example here, setting an obviously bigger size doesn't change anything

**Comment by Zylann** [comment]
![image](https://user-images.githubusercontent.com/1311555/34690962-62ce6282-f4bb-11e7-9195-41dff8469ce3.png)

**Comment by Jerome67000** [comment]
Well, it work with build https://github.com/godotengine/godot/commit/bc521741a99823487236526185ae3dc3c1b704fc.

Maybe the key has changed. Try to investigate in `editor_settings-3.tres`. I have try with deleting  `editor_settings-3.tres` before launching Godot.

![image](https://user-images.githubusercontent.com/7358899/34692092-2d263b24-f4bf-11e7-9093-7d68b21e4ecf.png)

**Comment by Zylann** [comment]
My bad... I was fooled by ghost properties again. I wonder if we can do something about it at some point, it's not the first time^^"
