### ISSUE TITLE
request for a _draw() function method that draws the texture of a node with all effects applied to it(rotate,scale,flip...draw_texture can only modulate

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#15501]
This feature request comes from another request where I have been trying to implement a wraparound mode with gdscript:
https://github.com/godotengine/godot/issues/15359#issuecomment-356078897

![newdrawmethodrequest](https://user-images.githubusercontent.com/6495061/34691163-a3e21d2a-f4b3-11e7-8e5d-04b86f8a07ea.JPG)

Using this  code, I was able to draw clones of an animated sprite using the draw_texture method:
```
func _draw(): 
	for node in ChidSprites():
		var spriteFTex = node.get_sprite_frames().get_frame(node.get_animation(),node.get_frame())#( String anim, int idx ) 
		#right
		draw_texture(spriteFTex,Vector2(node.get_pos().x+get_size().x-spriteFTex.get_width()/2,  node.get_pos().y-spriteFTex.get_height()/2))
		#left
		draw_texture(spriteFTex,Vector2(node.get_pos().x-get_size().x-spriteFTex.get_width()/2,  node.get_pos().y-spriteFTex.get_height()/2))
		#bottom
		draw_texture(spriteFTex,Vector2(node.get_pos().x-spriteFTex.get_width()/2,  node.get_pos().y+get_size().y-spriteFTex.get_height()/2))
		#top
		draw_texture(spriteFTex,Vector2(node.get_pos().x-spriteFTex.get_width()/2,  node.get_pos().y-get_size().y-spriteFTex.get_height()/2))
		#top left
		draw_texture(spriteFTex,Vector2(node.get_pos().x-get_size().x-spriteFTex.get_width()/2, node.get_pos().y-get_size().y-spriteFTex.get_height()/2))
		#bottom left
		draw_texture(spriteFTex,Vector2(node.get_pos().x-get_size().x-spriteFTex.get_width()/2, node.get_pos().y+get_size().y-spriteFTex.get_height()/2))
		#bottom right
		draw_texture(spriteFTex,Vector2(node.get_pos().x+get_size().x-spriteFTex.get_width()/2,  node.get_pos().y+get_size().y-spriteFTex.get_height()/2))
		#top right
		draw_texture(spriteFTex,Vector2(node.get_pos().x+get_size().x-spriteFTex.get_width()/2,  node.get_pos().y-get_size().y-spriteFTex.get_height()/2))
```
Unfortunately it is too limited and will not work for me because draw_texture can not do any operations on the texture that it is drawing :'((
draw_texture can only modulate color- it can not apply any of the effects that were applied on the origin sprite/node. There is no method to just get the pixels of the node with effects applied- with alpha preserved 

My request is for such feature- a method that returns a Texture resource of a sprite or animatedsprite node , after effects have been applied to it - if the sprite has been rotated,scaled,mirrored,flipped or wtah have you.

Alternatively get more optional parameters in the draw_texture method, such as flip,scale,rotate

Alternatively create a new simple function that lets the user draw the pixels of any node with an offset in x and y 

A key point to make is that we need to keep the alpha channel, so taking screenshots of the screen with no alpha channel or parts of the sprite that is not visible on the screen won't do

**Comment by mrcdk** [comment]
You can set the transform of the following `draw_*` commands with `draw_set_transform()` http://docs.godotengine.org/en/latest/classes/class_canvasitem.html#class-canvasitem-draw-set-transform

**Comment by blurymind** [comment]
@mrcdk Thank you , but that only covers rotation. What about the rest?
mirror, flip, etc?

**Comment by Dillybob1992** [comment]
Good idea, just to add, I did some testing late last year, and using native sprite2d nodes instead of hundreds of `draw_texture` is actually more performant (was doing char status icons, and dmg numbers from a horizontal spritesheet). 

However, I can understand why this would be a cool suggestion. I recommend trying it out in Sprite2D's first, you'll be surprised

**Comment by blurymind** [comment]
@Dillybob1992 Do you mean creating copies of the sprite and updating their changes with the original on every frame? Can you share some example code where you do that?
Does godot have some way of creating clones of Sprite2d nodes that mimic all of the activity of the original at an offset?

**Comment by Dillybob1992** [comment]
Yes, just store the duplicated nodes in an array, then change the values to move them in _process or wherever.
If you need to mimic all activity of an original, you can create a  separate `Node2D` and it can act as a container, then add the nodes to that specific `Node2D`, then modify that with your scale/rotation/etc

**Comment by blurymind** [comment]
@Dillybob1992 I thought about doing it that way, but ultimately decided to avoid writing tons of code for creating copies and updating them. A simple draw method is much easier to keep track of. My request here is for something that will give us precise pixel copies to draw on the screen without the need to manually update variables of clones with code. We have to do it even now with draw_texture() and draw_set_transform().
Its kind of strange that actually creating more sprites is cheaper on the cpu :o

**Comment by blurymind** [comment]
It would be nice if the new method also somehow copies the z-order value of the node.

A classic example of re-inventing the wheel here (how godot already works) in gdscript is in trying to write a function that puts the cloned nodes in the right order, depending on their z-value and order in the editor - so their pixel copies also have the same z-order!
ChidSprites() in my example needs to return an array of the children sprites - sorted by both their child index and z-order

**Comment by aaronfranke** [comment]
@blurymind Is this issue still relevant in Godot 3.1? I noticed that your post contains `get_pos()` and IIRC all `pos` code was replaced with `position` in Godot 3.0.

**Comment by blurymind** [comment]
I dont think the feature has been implemented, just the gdscript syntax is now a bit different

**Comment by Kazetsukai** [comment]
Since you want it to do everything the normal node rendering will do, have you considered using a [viewport](https://docs.godotengine.org/en/3.0/tutorials/viewports/viewports.html) to capture that into a texture and then draw that texture?

**Comment by blurymind** [comment]
@Kazetsukai can you provide a minimal example? :)

**Comment by Kazetsukai** [comment]
Here is a Polygon2D with a particle system on it, being viewport captured, and being rendered to the main view twice. Once by attaching a viewport texture to a sprite, and once by attaching it to a script and overriding draw.
![image](https://user-images.githubusercontent.com/935494/54782512-f23cac00-4c83-11e9-804e-ae3cb9c85129.png)
![image](https://user-images.githubusercontent.com/935494/54782676-50698f00-4c84-11e9-9ba0-a66578065e47.png)
![image](https://user-images.githubusercontent.com/935494/54782693-58293380-4c84-11e9-8b72-b5570b59fa8e.png)

Everything I want to capture lives under the Viewport, the Sprite is how I give it a physical location in the main view. The things underneath the Viewport don't move around the scene, only the sprite that displays them does. Everything is captured in a render texture, so I can redraw that as many times as I like.

You need to choose appropriate settings for the size of the viewport, make it transparent, etc. 
![image](https://user-images.githubusercontent.com/935494/54782767-89a1ff00-4c84-11e9-935a-1e96ca537c2a.png)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
