### ISSUE TITLE
Problems in the stretch of the window

### ISSUE THREAD

**Issue by Shockblast** [godotengine/godot#15514]
**Godot version:**
3.0b 4b414f45c47d699da4442ac2347c3b1684616cc0
Compiler VS2017
SCons 2.5.1
Python 2.7

**OS/device including version:**
Windows 10 64 bits.

**Issue description:**
(Sorry Translate)
Problems with resizing the window in width and heigth, the black bar can occupy up to half of the "visible project".
*Note the slight stretching of the sprite at the end.
*No tested in 3D.
![godotbugwidth](https://user-images.githubusercontent.com/5357217/34704348-5ad31c00-f4d7-11e7-9769-01467f49b5bd.gif)

**Steps to reproduce:**
Set in project settings ->Display -> window -> Stretch -> "mode"  to "2D"
and "aspect" in "Keep" or "keep_heigth".
Test Project and play with the window.

**Minimal reproduction project:**
Just test project and resizing.
[GodotBeta.zip](https://github.com/godotengine/godot/files/1613775/GodotBeta.zip)

**Comment by akien-mga** [comment]
Related to #15407.
