### ISSUE TITLE
Sprite - add a region area preview

### ISSUE THREAD

**Issue by Demmios** [godotengine/godot#15511]
**Godot version:**
3.0

**Issue description:**
It is a suggestion to add a region area preview in the Sprite right now i have only found the Enable / Disable checkbox and i need to figure out by trial and error the position of the offset i am trying to use a square preview of the offset area displayed in the sprite would be good

**Comment by mrcdk** [comment]
There is a `Texture Region` editor dock:
![https://i.imgur.com/I1XvQ1O.png](https://i.imgur.com/I1XvQ1O.png)

**Comment by Demmios** [comment]
sry didnt saw the option i was just looking to the right panel Thanks!! closed issue
