### ISSUE TITLE
Rename String::ord_at to String::unicode_at

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#15519]
**Godot version:** Godot 3.0

The function name  `unicode_at` should more meaningful than `ord_at `.
I think it is the good chance to make this rename before the 3.0 release.

**Comment by mhilbrunner** [comment]
Is there agreement that this should be in 3.0?

**Comment by mhilbrunner** [comment]
No opinion either. Isn't worse, but not sure its really better.

**Comment by akien-mga** [comment]
Closing as it's now tracked in #16863.
