### ISSUE TITLE
ALT + Left/Right arrow buttons don't change line indentation in the text editor

### ISSUE THREAD

**Issue by jaggygames** [godotengine/godot#15517]
**Godot version:**
Godot 3.0 daily build `2488aff93`
Windows 10

**Issue description:**
`ALT + UP/DOWN` moves a line vertically but using `ALT + LEFT/RIGHT` no longer changes the indentation (Compared to 2.1.4)

**Steps to reproduce:**
Can be tested using a standard `.gd` script.

This is a feature I found myself missing when moving over from 2.1.4. 

Because `ALT + LEFT/RIGHT` seems to serve no other purpose now, it seems like a cheeky regression.

**Comment by Hinsbart** [comment]
It seems these shortcut were intentionally removed:
https://github.com/godotengine/godot/blob/9e477babb3bf0ce5179395c2a5155a3f3cd36798/tools/editor/plugins/script_text_editor.cpp#L1367-L1371

**Comment by vnen** [comment]
This isn't a bug. Alt+Right/Left are used to move in the history. For indentation there's Tab and Shift+Tab.

If you're not happy with the change you can set it as it was before by changing the Editor Settings.

**Comment by jaggygames** [comment]
That's fair enough. As it's so easy to change shortcuts, I suppose it doesn't matter too much it just felt nice having ways to manipulate a line in one place 😄
