### ISSUE TITLE
"Open file dialog" buttons missing besides some settings in the Editor Settings dialog

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15510]
**Godot version:**
4b414f4

**Issue description:**
The following settings that ask for paths don't have the "open file dialog " button besides them:

- Text Editor > Help > Doc Path

**Comment by volzhs** [comment]
* Interface > Editor > Custom Font
* Text Editor > Theme > Font

those 2 options are moved or renamed by #15457

**Comment by YeldhamDev** [comment]
@volzhs They still appear like that, though.

**Comment by volzhs** [comment]
because it's still in `~/.config/godot/editor-settings-3.tres` file.
run editor after removing it, then it will be disappeared.

**Comment by YeldhamDev** [comment]
@volzhs Yeap, that solved those two, thanks. Seems that the problem is only with "doc path" now.

**Comment by Jerome67000** [comment]
I will try to add the Open file dialog for `Text Editor > Help > Doc Path` ! Do you have checked all other path setting ?
