### ISSUE TITLE
[Godot 3 beta 2] Sprite3ds are lit/darkened incorrectly

### ISSUE THREAD

**Issue by 2plus2makes5** [godotengine/godot#15520]
**Godot version:**

Godot 3 beta 2

**OS/device including version:**

Windows 10 home 64bit
gpu: intel hd 4400 + geforce 840m

Windows 10 home 64bit
gpu: intel hd 405

**Issue description:**

-if a sprite3d is lit/darkened it's lit/darkened on both sides instead of being lit on one side and darkened on the other
-if a sprite3d is rotated on the x or y axes with an angle >90 the sprite3d is darkened when it should be lit and vice-versa(always on both sides)

**Steps to reproduce:**
just put a sprite3d and a light of any kind and move and rotate the sprite around the light to see the issues

visual evidence:
<a href='https://postimg.org/image/ue02wo76b/' target='_blank'><img src='https://s13.postimg.org/rwobpen9z/sprite3d.png' border='0' alt='sprite3d'/></a>

**Comment by 2plus2makes5** [comment]
I would like to report that the godot 3 rc 1 seem to have addressed this issue :)

**Comment by akien-mga** [comment]
Great news, thanks for checking :)
