### ISSUE TITLE
Graphic artifacts when using [GI probe] and [SS reflections]

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#15527]
**Godot version:**
4b414f45c47d699da4442ac2347c3b1684616cc0

**OS/device including version:**
Ubuntu 17.04, gpu: gtx 1060

**Issue description:**
When using GI probe together with "ss reflections" (in environment) I'm able to see artifacts in my project:
![artifacts4](https://user-images.githubusercontent.com/6129594/34726043-22457776-f553-11e7-8e97-fd2e367cd9b3.png)

**Steps to reproduce:**
1. Download reproduction project.
2. Run it and try to mimic this screen as close as possible (its visible around this material):
![artifact5](https://user-images.githubusercontent.com/6129594/34725037-18be82ea-f550-11e7-901e-caf449b6288f.png)

**Minimal reproduction project:**
Modified material demo: 
https://www.dropbox.com/s/sczm269oaqcysky/material_testers.7z?dl=0
(to big file to attach to github)

I also noticed another, similar problem during investigating this bug, will create separate issue.

**Comment by kubecz3k** [comment]
It's possible this is a special case of https://github.com/godotengine/godot/issues/15529 issue

**Comment by bruvzg** [comment]
Windows 10; AMD FirePro D300
![black](https://user-images.githubusercontent.com/7645683/34732590-6166da2e-f56e-11e7-8dc3-fd969700de1e.png)

macOS 10.13.2; AMD FirePro D300
![gipr_ss](https://user-images.githubusercontent.com/7645683/34732650-8ef6efd8-f56e-11e7-89cc-b8259a442de1.png)
and shader errors in console:
```
   At: drivers/gles3/shader_gles3.cpp:168.
ERROR: get_current_version: SceneShaderGLES3: Program LINK FAILED:
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 18 samplers

   At: drivers/gles3/shader_gles3.cpp:509.
ERROR: get_current_version: Method/Function Failed, returning: __null
   At: drivers/gles3/shader_gles3.cpp:516.
ERROR: bind: Condition ' !version ' is true. returned: false
   At: drivers/gles3/shader_gles3.cpp:123.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles3/shader_gles3.h:377.
```

**Comment by AndreaCatania** [comment]
@bruvzg Can you please tell me where did you find these errors?

**Comment by beniwtv** [comment]
I'm also getting this on "Ultra" in @Calinou's Sponza Demo with a Godot build from 5 minutes ago.

OS: Manjaro Linux
GPU: AMD RX 480 8GB using Mesa 17.3.1

**Comment by bruvzg** [comment]
@AndreaCatania here's full log: https://pastebin.com/69JdpiWB

**Comment by AndreaCatania** [comment]
@bruvzg thanks for it, I'm trying to get it on my side. I can reproduce the problem on my pc but I don't get the error logs. There's something that I have to activate in order to get it, or there is a dedicated Shader log?

**Comment by bruvzg** [comment]
@AndreaCatania no this is part of main console output and I only get this errors on macOS, on Windows there is no error messages only visual artefacts.

Looks line this is known [macOS limitation](https://forum.allegorithmic.com/index.php?topic=12514.0).

**Comment by reduz** [comment]
seems the driver is limited to 16 texture units, nothing much to do about
that

**Comment by beniwtv** [comment]
I didn't get the problem a few weeks ago, before Christmas on my machine. My artifacts look like the Windows screenshot above.

If it helps, I do get errors in the console printed:

```
No touch devices found
OpenGL ES 3.0 Renderer: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-1-MANJARO, LLVM 5.0.1)
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
OPENING: /home/beniwtv/Downloads/godot-sponza-master (::home::beniwtv::Downloads::godot-sponza-master)
No touch devices found
OpenGL ES 3.0 Renderer: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-1-MANJARO, LLVM 5.0.1)
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
ERROR: getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
   At: core/rid.h:165.
ERROR: instance_remove_dependency: Condition ' !inst ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5962.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
ERROR: getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
   At: core/rid.h:165.
ERROR: instance_remove_dependency: Condition ' !inst ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5962.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
ERROR: getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
   At: core/rid.h:165.
ERROR: instance_remove_dependency: Condition ' !inst ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5962.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
ERROR: getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
   At: core/rid.h:165.
ERROR: instance_remove_dependency: Condition ' !inst ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5962.
```

**Comment by reduz** [comment]
If you guys can bisect to find the commit where this breaks, it would be super appreciated

**Comment by kubecz3k** [comment]
I completed the bisection and 0c86c1ad152d2b523dc125eb79e838563b3d5f69 is the first bad commit

**Comment by Zylann** [comment]
Similar graphical glitches happen in some issues reported to my plugin:
https://github.com/Zylann/godot_heightmap_plugin/issues/228
https://github.com/Zylann/godot_heightmap_plugin/issues/149

**Comment by 7leodev** [comment]
Apparently this works for me with detail shader.  
`ALBEDO = clamp(ALBEDO, 0.0, 1.0);`
