### ISSUE TITLE
[GI probe] artifacts with transparent objects

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#15529]
**Godot version:**

4b414f45c47d699da4442ac2347c3b1684616cc0 

**OS/device including version:**
Ubuntu 17.04, gtx1060

**Issue description:**
When I was investigating #15527 I noticed another graphic artifact. When looking at transparent object when GI probe is on the scene, sometimes black squares are visible:
**video:** https://youtu.be/tmr4hDMQ9X8

**Steps to reproduce:**
1. Download reproduction project.
2. Turn off "ss reflections" in environment
3. Mimic camera to move it similarly how it's on description video

**Minimal reproduction project:**
https://www.dropbox.com/s/sczm269oaqcysky/material_testers.7z?dl=0

**Comment by kubecz3k** [comment]
It's possible this is a special case of https://github.com/godotengine/godot/issues/15527 issue

**Comment by akien-mga** [comment]
Fixed by #15555.
