### ISSUE TITLE
Godot closing upon _Save branch as scene_, on Ubuntu 16.04

### ISSUE THREAD

**Issue by diegodillenburg** [godotengine/godot#15539]
**Godot version:**
v2.1.4.stable.official

**OS/device including version:**
Ubuntu 16.04.2 LTS

**Issue description:**
Upon clicking on a node tree and selecting "Save Branch as Scene" Godot proceeds to saving dialogue, saves the scene, but closes afterwards.

**Steps to reproduce:**
Specific node tree was:
- Path2d
  - PathFollow2d
    - KinematicBody2d
      - Sprite
      - AnimationPlayer
      - CollisionShape2d

Right click on Path2d node and select "Save Branch as Scene"
P.S.: Seems to happen with this specific tree.

**Minimal reproduction project:**
[TestProject.tar.gz](https://github.com/godotengine/godot/files/1616610/TestProject.tar.gz)

**Comment by eon-s** [comment]
Sounds like #9367, can you provide a stacktrace too?

**Comment by diegodillenburg** [comment]
I'm travelling for the next couple of days, but will do as soon as I get back.
