### ISSUE TITLE
Menu Key does not cause a context-menu to pop up

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#15542]
The [Menu Key](https://en.wikipedia.org/wiki/Menu_key) should cause a right-click context menu to pop up when pressed, as it does across the entire OS and most applications.

Useful not only for broken computer mice (which I'm suffering from right now), but also for accessibility and consistency with what a user might expect.

**Comment by Calinou** [comment]
Is this considered fully implemented by #29895, or are there still places where it should be implemented? See also https://github.com/godotengine/godot-proposals/issues/143.

**Comment by ptrojahn** [comment]
My patch is only for the text editors.

**Comment by Anutrix** [comment]
Isn't this fixed by https://github.com/godotengine/godot/pull/38556?

**Comment by akien-mga** [comment]
> Isn't this fixed by #38556?

I don't think so, it only makes the key recognized by the engine, but one still has to implement functionality to trigger an action when it's pressed in relevant editor controls.

But this is superseded by godotengine/godot-proposals#143.
