### ISSUE TITLE
Missing Sprite method get_item_rect()

### ISSUE THREAD

**Issue by VayMoran** [godotengine/godot#15545]
Godot Version: 3.0.beta.custom_build.c037f63
OS: GNU/Linux ~ Linux Mint 18.3

**Issue Description**
When using GDScript, I was unable to access the method get_item_rect() to take into account my sprite's dimensions. On investigating the documentation, this method is also missing from the "latest" documentation. There appears to be no replacement method or variable in the documentation.

**Reproduce Steps**
1) Create a Sprite
2) Assign Texture to Sprite
3) Add script to Sprite
4) Unable to access Sprite "size" parameters

**Comment by volzhs** [comment]
`get_item_rect()` is actually `CanvasItem` method, according to 2.1.x
I couldn't find it on 3.0

**Comment by vnen** [comment]
Apparently it was changed to `_edit_get_rect()`, which won't appear in the docs because it starts with underscore. This was changed in #12955.

**Comment by akien-mga** [comment]
CC @groud

**Comment by groud** [comment]
Yes, it was renamed to _edit_get_rect(). However I also removed the possibility to override it in GDscript, as the editor itself should already display a correct rect around the selected object.

**Comment by groud** [comment]
Also, none of those functions were meant to be used to retrieve the sprite size in a game. They are called by the editor to know how the resizable rect should be drawn. For exemple, on a node2d this return a 64 by 64 square centered on the node, which is inconsistant, as it would return (0, 0) if it corresponded to a real size.

The correct way to access a sprite size is thus the one proposed by @volzhs

**Comment by akien-mga** [comment]
> However I also removed the possibility to override it in GDscript, as the editor itself should already display a correct rect around the selected object.

I wonder if that should be readded? Are we sure that the current logic to define the edit rect will satisfy 100% of use cases? It was nice to be able to override it to e.g. better snap on a grid (of course as you mentioned, it's only for the 2D editor, not for in-game use).

**Comment by groud** [comment]
Well, I can readd it, but the use case seems like quite corner case. Regarding the snapping the API is not complete enough, as it would be great to be able to choose between "center snap" mode and a "rect snap mode".
 The main problem is that, exactly like here, some people will try to use this function to determine the size of objects, and we might end up with complains that it return weird results in some situation.

**Comment by blurymind** [comment]
@volzhs what if the sprite has also been rotated?

**Comment by Zireael07** [comment]
I was actually using set_item_rect in 2.1. when testing some stuff (lines drawn on _draw, that I wanted to have a close-fitting bounding box). That wouldn't happen automatically in 3.0, I think, since it's not a sprite?

**Comment by groud** [comment]
I think this issue can be closed now
