### ISSUE TITLE
crash when opening mono projects since #15463

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#15551]
**Godot version:**
Godot 3 master https://github.com/godotengine/godot/pull/15541

**OS/device including version:**
Arch Linux, Intel HD4000 / Mesa 17.3.1

**Issue description:**
Since https://github.com/godotengine/godot/pull/15463 was merged, Godot crashes for me when trying to open projects that use mono with the following error message:

```
 ERROR: update_godot_api_cache: Mono Cache: Member GDMonoUtils::mono_cache.class_DebuggingUtils is null. This is really bad!
   At: modules/mono/mono_gd/gd_mono_utils.cpp:186.
```

**Comment by akien-mga** [comment]
CC @neikeq.

**Comment by mysticfall** [comment]
I'm having the same issue with my build(`master` / 2ac27608a6892d8d7e28d8afbbcc98505eb3e4b3) as well.

**Comment by neikeq** [comment]
I have to think of a way to make the editor not load outdated assemblies, or at least remain usable as if they weren't loaded.
This time, just delete the `.mono` folder in your project.

**Comment by novemberist** [comment]
I don't think this is it. This crash also happens with newly created projects. Deleting .mono lets me temporarily open the project, but next time it will crash again.

**Comment by mysticfall** [comment]
@novemberist I just tested it and I also had to delete `~/.local/share/godot/mono/solutions/*` and rebuild to make it work again.

But after that, I could open and run my project without a problem, and closing the editor and open it again doesn't seem to reproduce the issue any more.

**Comment by akien-mga** [comment]
Might be worth keeping this issue open as a reminder to find a way to invalidate old assemblies then?

**Comment by novemberist** [comment]
I can confirm deleting .mono in the project folder and the contents of ~/.local/share/godot/mono/solutions/ makes everything work again. Although I find it a little odd how many additional files are scattered outside of my project folder to keep track of when something doesn't work anymore.

**Comment by neikeq** [comment]
Ah, forgot about `~/.local/share/godot/mono/solutions/`. That shouldn't be needed once I add internal versioning to the bindings generator appart from the API hash.
