### ISSUE TITLE
Graphic artifact with [Glow] turned on

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#15557]
**Godot version:**
e49ddf298403ae80977e9811bab6ef39f0ea226b

**OS/device including version:**
Ubuntu 17.04, GTX1060

**Issue description:**
When environment GLOW is on, sometimes artifacts are visible:
![artifact7](https://user-images.githubusercontent.com/6129594/34774256-e3440e4a-f60e-11e7-99b2-b3642dce4774.png)

**Steps to reproduce:**
1. Download sample project
2. Ensure `Glow` is `on` in environment
3. Try to mimic camera setup from the description screen

**Minimal reproduction project:**
https://www.dropbox.com/s/sczm269oaqcysky/material_testers.7z?dl=0
(just for the record, it's the same project as in #15529 and #15527)

**Comment by AndreaCatania** [comment]
Here some other info: 

![untitled](https://user-images.githubusercontent.com/8342599/34774341-4010cf46-f60f-11e7-914a-9df5a80318a3.png)


GIF:
https://gfycat.com/UltimateFrenchHawaiianmonkseal

**Comment by akien-mga** [comment]
Can you check if those issues are still there after reverting #15555? And then after reverting 0c86c1a too? To see if it's related to the recent blending changes.

**Comment by AndreaCatania** [comment]
Yes it was before #15555

**Comment by kubecz3k** [comment]
I tried to bisect this issue but I'm unable to find `good` commit. It seems the issue is quite old and there were some breaking changes in mean time, which are causing editor startup crash on current projects (so I can't check the issues on older commits). The last tested commit which was not crashing was 6c25eabbc5b80c55dea5e3b848cb770c501c0680 (and the issue was present)

**Comment by akien-mga** [comment]
Thanks for taking the time to check this :)

**Comment by AndreaCatania** [comment]
@kubecz3k Fixed #15594 can you please confirm it?

**Comment by kubecz3k** [comment]
@AndreaCatania I can confirm its not reproducible anymore with the fix :+1:
