### ISSUE TITLE
Godot skips middle button double click

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#15567]
**Godot version:**

Godot 2.1.4 and Godot 3

**OS/device including version:**

Win 7 32 bit and Win 7 64 bit.

**Issue description:**

First i need to clarify that I have verified that it is not a normal behavior of windows or the mouse. I test 2 different mouse in two computers. A test can be done here: http://unixpapa.com/js/testmouse.html

Godot label InputEventMouseButton with properties "pressed" and "doubleclick". Pressed are true/false consecutive (down-up-down-up). If third click is fast is labeled too with doubleclik=true... well, this is true for the left and right buttons. Middle button skip this third fast clik. This will not be a problem if the true/false/true/false cadence of click will not be broken, but it is. You have down-up-up (pressed, not pressed, not pressed). This make the input logic for this button a lot of tricky to accomplishment in certain situations.

**Steps to reproduce:**
In any script paste that, execute, try different clicks and see the console:

Godot 3:

```
func _input(event):
	if event is InputEventMouseButton:
		print (str(event.button_index) +"pressed: "+\
		 str(event.pressed) +" Doubleckick:  "+ str(event.doubleclick))

```

Godot 2:

```
func _input(event): 
	if event.type == InputEvent.MOUSE_BUTTON:
		print(event)
```

**Minimal reproduction project:**

**Comment by reduz** [comment]
ah thats right, it was never handled in the input code..
