### ISSUE TITLE
Using TIME in canvas_item shader drops FPS by half

### ISSUE THREAD

**Issue by vigreco** [godotengine/godot#15578]
**Godot version:**
master ([91adb58](https://github.com/godotengine/godot/commit/91adb58d3de1cb22196203d0184374ff034bf950))

**OS/device including version:**
OS X 10.11.6
NVIDIA GeForce 9400M

**Issue description:**
Using TIME, also in a very simple shader, causes a very noticeable performance degradation.
On my machine FPS drop from 60 to 20 (sometimes 30) with only one sprite in the scene.

**Steps to reproduce:**
Use TIME in a shader. Also only assigning TIME to a variable generates the issue:
```
shader_type canvas_item;

void fragment() {
    float t = TIME;
}
```

Not sure if still related, but Godot often crashes when I use TIME dependent shaders. Same as #9123.

**Comment by reduz** [comment]
Using TIME causes the editor to refresh in the object is visible, this may be your source of degratation.
I don't really think this is a bug.

**Comment by reduz** [comment]
Also the editor FPS are probably not a good reference. I will close this unless more information is provided.
