### ISSUE TITLE
Add Sprite3D billboard property to Godot 3

### ISSUE THREAD

**Issue by amedlock** [godotengine/godot#15587]
**Godot version:**
3.1 Beta 3

**OS/device including version:**
Windows 10 Pro 64 bit

**Issue description:**
Using Sprite3d as an imposter works in Godot 2.1 but not in 3.0b 2

I had an imposter in the sky in my godot 2 project with sprite3d and just selected Billboard, Billboard Y.  It looks good no matter which angle I choose.

Now I must choose an Axis which works until it is high in the sky.

Can I get the old behaviour in Godot 3?  If so let me know I will close this.

**Comment by Calinou** [comment]
You set the Billboard properties in SpatialMaterial now, if I'm not mistaken. Both Billboard and Billboard Y are available there.

**Comment by amedlock** [comment]
I created a material and set it under material override and it works like Godot 2.

Thanks.
