### ISSUE TITLE
Dragging non-binary state values gives erronous behavior in Interface section of editor settings

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#15597]
#**Godot version:**
Godot_v3.0-beta2_win64
Godot_v3.0-stable_win64

**OS/device including version:**
Windows 10 Pro 64 bit Build 1709

**Issue description:**
Dragging non-binary state values like contrast, font size, dim amount, etc. gives erroneous behavior in the Interface section of editor settings. Mouse pointer changes to the disabled icon.
Similar to #15351.

**Steps to reproduce:**
1. Open Godot_v3.0-beta2_win64.exe.
2. Click Editor->Editor Settings.
3. Drag values Source Font Size or Contrast or Dim Amount or Dim transition amount a few times.

**Minimal reproduction project:**
Bare minimum New Game Project.
[Testing.zip](https://github.com/godotengine/godot/files/1623154/Testing.zip)

**Comment by Anutrix** [comment]
It seems to be fixed in 3.1Alpha build because the settings were revamped/redesigned. Can someone confirm and then close this issue, I checked and couldn't find the bug.

**Comment by akien-mga** [comment]
That's indeed fixed with the new EditorSpinSlider, thanks for the update.
