### ISSUE TITLE
Shader atan(x, y) produces invalid arguments error

### ISSUE THREAD

**Issue by vigreco** [godotengine/godot#15590]
**Godot version:**
master ([91adb58](https://github.com/godotengine/godot/commit/91adb58d3de1cb22196203d0184374ff034bf950))

**OS/device including version:**
OS X 10.11.6
NVIDIA GeForce 9400M

**Issue description:**
Using atan() function with 2 arguments generates the following error:

```
:10 - Invalid arguments for built-in function: atan(float,float)
drivers/gles3/rasterizer_storage_gles3.cpp:1649 - Condition ' err != OK ' is true.
```
Affects:
```
float atan(float, float)
vec2 atan(vec2, vec2)
vec3 atan(vec3, vec3)
vec4 atan(vec4, vec4)
```

**Steps to reproduce:**
Use any of the above function in a shader.
```
float a = atan(-1.0, 1.0);
```

**Comment by vigreco** [comment]
Just recompiled with latest changes ([`2c17af0`](https://github.com/godotengine/godot/commit/2c17af050935bccf17deb6e6489ade64c0af2f73)) and the issue seems to be gone.

**Comment by akien-mga** [comment]
Ah indeed I hadn't noticed that you were on a build from October..
