### ISSUE TITLE
Leaks occur when using Particles

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#15591]
**Godot version:**
3.0 554e95747c07afa893a2c4c0445370dda57aa7d0

**OS/device including version:**
Tested on macOS 10.12.6, probably occurs on other platforms, too.

**Issue description:**
There are errors and StringName leaks when you use a simple Particles node.

**Steps to reproduce:**
Run [this project](https://github.com/godotengine/godot/files/1622197/project.zip) with `godot -v --path .`, close it, and see this in the output:

```
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
ERROR: getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
   At: core/rid.h:165.
ERROR: instance_remove_dependency: Condition ' !inst ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5962.
Orphan StringName: color_value
Orphan StringName: anim_offset
Orphan StringName: anim_speed_random
Orphan StringName: gravity
Orphan StringName: linear_accel
Orphan StringName: damping
Orphan StringName: initial_angle_random
Orphan StringName: anim_speed
Orphan StringName: radial_accel
Orphan StringName: anim_offset_random
Orphan StringName: orbit_velocity_random
Orphan StringName: hue_variation_random
Orphan StringName: trail_divisor
Orphan StringName: scale
Orphan StringName: hue_variation
Orphan StringName: damping_random
Orphan StringName: radial_accel_random
Orphan StringName: tangent_accel_random
Orphan StringName: linear_accel_random
Orphan StringName: tangent_accel
Orphan StringName: initial_linear_velocity_random
Orphan StringName: flatness
Orphan StringName: angular_velocity_random
Orphan StringName: spread
Orphan StringName: scale_random
Orphan StringName: initial_angle
Orphan StringName: initial_linear_velocity
Orphan StringName: orbit_velocity
Orphan StringName: angular_velocity
StringName: 29 unclaimed string names at exit.
```

**Comment by endragor** [comment]
While the leaks were happening since long time ago, the three errors listed started to occur when removing any particles in a change added within the last couple of weeks. The symptoms are different in 7f1265b41fc52def42c433e5d324070bc6454d6b.

**Comment by vnen** [comment]
Seems related to #15170.

**Comment by endragor** [comment]
@reduz Orphan StringName warnings are now gone, but those 3 errors still occur every time Particles node is removed from a scene. And it seems like a more serious part of this issue as in an actual game it happens all the time and the logs are spammed with those errors.
