### ISSUE TITLE
Stress performance test for a node inside editor

### ISSUE THREAD

**Issue by Bladum** [godotengine/godot#15598]
**Godot version:**
3 beta 2

**Issue description:**
Do we have option to have access to cpu gpu data on IDE level ? If yes then is it possible to add performance indicator of current node ? 

It will show if node is heavy to process from cpu or gpu perspective to show designer potential bottleneck during design in editor not once running game. 

It could be achieved by perform some kind of stress test to benchmark node to show its usage against hardware before its run ?

Reason for that is that some nodes are implemented differently then other game engines and othen nodes and its hard to say if current node structure is optimized.

**Comment by Bladum** [comment]
For example tilemap is somehow confusing me 
In regards of performance compared to other nodes for a set of 10k tiles and more

**Comment by Dillybob1992** [comment]
Heatmap for nodes? Actually  a really cool idea, but how complex some games/scenes get... implementing something like that would be very hard and time consuming (in my opinion at least)

**Comment by Calinou** [comment]
I really don't see how this could be implemented. We could run headless benchmarks in a fashion similar to unit tests to check for regressions, but that's more of a buildsystem/CI thing.

Note that better GPU profiling tools are coming to Godot 4.0, see https://twitter.com/reduzio/status/1174872583898062848.

**Comment by mhilbrunner** [comment]
Godot offers profiling tools that may be used for this in a similar vein. :)
