### ISSUE TITLE
Godot segfaults silently if Opengl 2.1 support is missing

### ISSUE THREAD

**Issue by ranmrdrakono** [godotengine/godot#156]
```
(gdb) backtrace 
#0  0x0000000000000000 in ?? ()
#1  0x0000000000514154 in RasterizerGLES2::init (this=0x7ffff2878040) at drivers/gles2/rasterizer_gles2.cpp:7666
#2  0x0000000000f82e23 in VisualServerRaster::init (this=0x7ffff2856040) at servers/visual/visual_server_raster.cpp:5624
#3  0x0000000000f30a30 in VisualServerWrapMT::init (this=0x7ffff2815040) at servers/visual/visual_server_wrap_mt.cpp:152
#4  0x00000000004080a7 in OS_X11::initialize (this=0x7fffffffdeb0, p_desired=..., p_video_driver=0, p_audio_driver=0) at platform/x11/os_x11.cpp:306
#5  0x0000000000410b1b in Main::setup2 () at main/main.cpp:706
#6  0x000000000040ff64 in Main::setup (execpath=0x7fffffffe668 "/data/Proggen/git/config/scripts/godot", argc=1, argv=0x7fffffffe370, p_second_phase=true)
    at main/main.cpp:661
#7  0x00000000004064c8 in main (argc=2, argv=0x7fffffffe368) at platform/x11/godot_x11.cpp:36
```

Running on an old intel graphics chip, should print a little error message along the lines of "need opengl2.1 support to run" before segfaulting.

**Comment by tonymtbird** [comment]
related to: https://github.com/okamstudio/godot/issues/1283

**Comment by akien-mga** [comment]
If this still valid in the current master branch? If yes, a check for the OpenGL version should probably be added to provide a meaningful error message and close Godot without segfaulting.

**Comment by ranmrdrakono** [comment]
Unfortunately I no longer have the hardware that was causing the problems in my possession.

**Comment by akien-mga** [comment]
Related to #1162.

**Comment by akien-mga** [comment]
Closing as a "won't fix" bug as there is nothing we can do to fix this issue. On the other hand #1162 proposes to catch the error before a segfault and to display a friendly error message, which should make this kind of errors easier to understand for the user.
