### ISSUE TITLE
After Exporting Godot 3.0 HTML5 project and running on local server using node.js http-server module

### ISSUE THREAD

**Issue by Sseriously** [godotengine/godot#15600]
**ERROR**: still waiting on run dependencies:
**ERROR**: dependency: wasm-instantiate
**ERROR**: (end of list)
**ERROR**: pre-main prep time: 12037 ms
**ERROR**: WebGL 2 not available

**Comment by Sseriously** [comment]
Also when using Safari Version 11.0.2 (13604.4.7.1.3) 

ERROR: still waiting on run dependencies:
ERROR: dependency: wasm-instantiate
ERROR: (end of list)
ERROR: pre-main prep time: 12037 ms
ERROR: WebGL 2 not available

**Comment by akien-mga** [comment]
Please follow the issue template when you file an issue...

**Comment by vnen** [comment]
Looks like you don't have WebGL 2, which is a hard requirement for now. What does http://webglreport.com/?v=2 say?

**Comment by Sseriously** [comment]
i will give Chromium a try.....thanks vnen.
