### ISSUE TITLE
Can't compile Godot on Android

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#15603]
Because this PR (#15400) I can't build the Godot v3.0 Android release.

Gradle throws me this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find any version that matches com.android.support:support-v4:27.+.
     Versions that do not match:
         26.0.0-alpha1
         25.3.1
         25.3.0
         25.2.0
         25.1.1
         + 32 more
     Searched in the following locations:
         file:/opt/android-sdk/extras/android/m2repository/com/android/support/support-v4/maven-metadata.xml
         file:/data/environments/workdir/godot/platform/android/java/sdk-manager/com/android/support/support-v4/maven-metadata.xml
         file:/data/environments/workdir/godot/platform/android/java/sdk-manager/com/android/support/support-v4/
     Required by:
         project :
```

Please, I need help, its for Digitecnology Godot 3 Daily Builds (godot3builds.digitecnology.com)

**Comment by Alexia-AT-Digitecnology** [comment]
I updated sdkmanager and there is no option for "Support Library" in Android SDK Manager. Still doesn't work.

**Comment by Alexia-AT-Digitecnology** [comment]
In the file android-sdk/extras/android/m2repository/com/android/support/support-v4/maven-metadata.xml that explains all the versions of Android Support Library, there is no v 27, so maybe the person that have made the PR may have another repository non-standard for android.

**Comment by Alexia-AT-Digitecnology** [comment]
The last version of "Android Support Repository" (v47.0.0) does not include the v27 of the Android Support Library in the Maven Metadata. Please, put a correct version in the build.gradle file.

**Comment by volzhs** [comment]
I made that PR and I'm using android studio 3.0.1
and I installed api 27 from sdk manager in android studio.
I never know there is any "non-standard" repository.

and api 27 is Android 8.1 and is already available some google devices.

**Comment by volzhs** [comment]
and it's duplicated with #15513

**Comment by Alexia-AT-Digitecnology** [comment]
The Support Library v 27 is in an external repository (https://maven.google.com). Please, use a clean SDKManager using console.

**Comment by Alexia-AT-Digitecnology** [comment]
Or you can modify the build.gradle to add this external repository.

**Comment by volzhs** [comment]
would you try add `google()` in `build.gradle.template`?
```
	repositories {
		jcenter()
                google()
	}
```

**Comment by Alexia-AT-Digitecnology** [comment]
I added google() to build.gradle like this:

```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        google()

    }
}
```

It works flawlessly.

Please, change that.

**Comment by volzhs** [comment]
ok. it's my fault. i will update soon.
