### ISSUE TITLE
Label nodes should respect their content when using the shrink size flags.

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#15604]
When using a Label control node, none of the `shrink*` options for the size flag respect the text content of the node.

For comparison, here's what a label and a button look like with `Fill`:

![label1](https://user-images.githubusercontent.com/5330692/34841430-8b8e59ee-f708-11e7-8493-36146485c9df.png)

now with `shrink_center`:

![label2](https://user-images.githubusercontent.com/5330692/34841444-9cf09b7a-f708-11e7-80a2-1db9c2cf0778.png)

I would expect something maybe like that instead:

![label3](https://user-images.githubusercontent.com/5330692/34842070-acd3d1c2-f70a-11e7-8985-22e050c79f2a.png)

**Godot version**
Godot 3.0beta2

**Comment by LeonardMeagher2** [comment]
You should be able to set a minimum width. If the content inside a control doesn't have a minimum width in this case because of line wrap there is no way to know when to stop shrinking.

It could maybe stop when it reaches the largest single letter on a line, but that's not any better than ignoring the width of the letters.

I'd recommend just setting some minimum width you like.

**Comment by letheed** [comment]
@LeonardMeagher2 that doesn't really work if I need to dynamically change the text.

Label, like Button has a `clip_text` property. Here's what Button looks like with `clip_text` on then off:

![button clip_text](https://user-images.githubusercontent.com/5330692/34884130-0c9a8dba-f7bc-11e7-859d-16bc5339a619.png)

I understand that `autowrap` makes it more complicated, but Label should not clip it's content unless `clip_text` is set to true.

**Comment by warent** [comment]
I would still like to see this for Godot 4! Is this still a valid ticket?

**Comment by KoBeWi** [comment]
In Godot 4 there are various autowrap modes for label, including word one.

> I would expect something maybe like that instead:

That's unfeasible. The Label would have to magically know what width do you expect. Shrink always uses the minimum possible size.

Closing, open a [proposal](https://github.com/godotengine/godot-proposals) if you are still interested.
