### ISSUE TITLE
KinematicBody with CollisionShape (sphere shape or capsule shape, or ray shape) stuck.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#1561]
Ray shape get stuck in any of the cases, if in the beginning it can a little move, but then got stuck and nothing more can be done at all, even the jump is not happening!

The capsule shape and sphere shape may for a long time moved, and it seems that there are no problems and everything seems to work fine.
BUT! this is not true! At some point, going on with them the same as with the ray shape it just stuck, and never come move.
This effect is very often occur when the grid moves along the map surface, it is possible that this is happening at the moment when shape reaches the junction point between the tiles of static bodies of grid map.
By the way a lot of problems also occur when sphere shape or capsule shape, touch the walls of which have a boss or pimple, and then it stuck as a result, but sometimes from the bulge, you can retreat, and again move freely.

To see how it breaks in the demo kinematic_char_3D, you just need to replace the body shape "Cubio" on the ray shape. and make an attempt to move and jump.

**Comment by TheoXD** [comment]
I'm not 100% sure, but sounds like you forgot to wake up the "rigidbody"  (that's probably what you're using according to your FB post, since kinematicbody doesn't have character mode)  with set_sleeping(false) if rigidbody goes idle and freezes.

**Comment by OlexiyKravchuk** [comment]
Ouch! I bring my apologies for the confusion!
I will remove the error from the topic ...

You're right, I'm just confused myself, kinematic body has no modes, (but at the moment when I was spending collation, for some reason, I decided that there are) and look at the fields in the "Inspector", I saw the word "character", I just looked there hoping to find out mode, but pulled out the word "haraktel" from the context of not paying attention to the rest ...

But still, a problem exists in effect ...

**Comment by reduz** [comment]
ray shape is not designed to be used with kinematicbody, use segmentshape instead

**Comment by reduz** [comment]
ray shape is for rigidbodies, it just pushes away in that direction but nothing else

**Comment by OlexiyKravchuk** [comment]
What is a segment shape?
I have been unable to find anything similar?

and even if the ray shape, does not provide as work as I expected, what still from the sphere and the capsule? they too have this problem but it is hidden therein deeper?

**Comment by reduz** [comment]
oh sorry, I think I understand what's going on..
and yeah. 

Ray shape is only meant as an add-on to other shapes. It pushes stuff away, but does not work on KinematicBody or by itself.

**Comment by reduz** [comment]
you could try a thin capsule shape instead

**Comment by OlexiyKravchuk** [comment]
as I have said above, the problem also is that the capsule, as well as the scope, broken just like a ray, but it's a little harder to catch, and there is abruptly as diarrhea ... =))

**Comment by TheoXD** [comment]
OlexiyKravchuk, everything besides ray and plane works fine, you really have to provide example projects if you want your issues to be confirmed and resolved faster. I don't see anything wrong with sphere and capsule shapes.

**Comment by akien-mga** [comment]
Seems more like a general support issue than a bug, so archiving.
