### ISSUE TITLE
Some GDScript functions are absent in Mono.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#15619]
**Godot version:**

Beta 2

Right now I found two functions which I cannot find in Mono.
1. wrapf
2. randf

(I haven't searched for more methods I just had to use those in my project)

Also keep in mind that I search in Mathf and GD for both.

**Comment by akien-mga** [comment]
I'm pretty sure those are meant to be provided by existing methods of the C# ecosystem instead of reimplementing them ourselves to mimic GDScript, no?

At least `randf` would be `(float)new Random().NextDouble()`.

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by kakoeimon** [comment]
@akien-mga Yes randf can be replicated this way. 
I also translated wrapf from c++ to c# for my usage.

But atan2 and many more Math functions can be found in Godot.Mathf, I am sure that those too can be found in standard C#, but we have them and from Godot too.

**Comment by Chaosus** [comment]
@akien-mga  Wrap function now added to Mathf.cs, should this issue be closed ?
