### ISSUE TITLE
Add Script Introspection methods to the scripting API.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#15634]
**Godot version:**
Godot 3.x

**Issue description:**
It would be more convenient if the Script introspection methods were made available to the scripting API.

- has_method (bool)
- get_method_info (Dictionary)
- get_script_signal_list (Array)
- get_constants (Dictionary, w/ names to values?)
- get_members (Array, or possibly as a Dictionary representation of the properties?)
- get_language (returns the string value, could be implemented easily enough with, `get_language`, and the static `::get_class`.
- instance_create() (Object) - Edit: at vnen's suggestion
- get_current_script_members (Array) - Edit: new function*, you cannot currently get JUST a list of the properties associated with the current script and not its inherited properties. One use case I can think of would be heavily simplifying the implementation of #13116.

Any other ideas?

**Comment by willnationsdev** [comment]
cc @mhilbrunner in reference to #15581

**Comment by vnen** [comment]
I would like `instance_create()` too, not sure if related to this. (This binding is commented out since the beginning of times, so I wonder if there's an issue with it).

**Comment by willnationsdev** [comment]
@vnen Is that somehow different from just calling `.new()` on the `Script`? I didn't think there was a difference...?

**Comment by vnen** [comment]
@willnationsdev `.new()` is defined in GDScript, you can't use that with other types derived from Script (unless they also define `new()`).

**Comment by willnationsdev** [comment]
It would also be useful to add a method which specifically returns the properties that exist in the current script (not including inherited ones).

**Comment by Calinou** [comment]
Is this solved by #31021?

**Comment by willnationsdev** [comment]
@Calinou Ah, yes, I think so.

**Comment by Calinou** [comment]
@willnationsdev Thanks for your reply :slightly_smiling_face: I'll close this then.
