### ISSUE TITLE
Tool falls into uninterruptable sleep when it's closed with a running app

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#15637]
**Godot version:**
d486cae7016c77af114d8019abf37c57e8bba386

**OS/device including version:**

linux

**Issue description:**
E.g.: start the godot tool in a project folder with `godot -e` and play (f5) the project.
Close the tool window.

The terminal is blocked, godot runs forever (sure, until you press the power button):
```
ps -aux | grep godot
username       10403  1.1  0.0      0     0 pts/23   D+   21:24   0:23 [godot3]

killall -9 godot3

ps -aux | grep godot
username       10403  1.1  0.0      0     0 pts/23   D+   21:24   0:23 [godot3]
```

and prevents the computer from going to suspend (stand-by) mode

```
Jan 12 07:41:14 t2t systemd-sleep[31371]: Suspending system...
Jan 12 07:41:34 t2t kernel: [47564.481329] PM: Syncing filesystems ... done.
Jan 12 07:41:34 t2t kernel: [47564.528695] PM: Preparing system for sleep (mem)
Jan 12 07:41:34 t2t kernel: [47564.528936] Freezing user space processes ... 
Jan 12 07:41:34 t2t kernel: [47584.532861] Freezing of tasks failed after 20.004 seconds 
(3 tasks refusing to freeze, wq_busy=0):
…
Jan 12 07:41:34 t2t kernel: [47584.533187] godot3 D    0 23897   2930 0x00000006
```

**Comment by brainsick** [comment]
Ubuntu 17.10 x64

I couldn't recreate this with my own sample projects.

https://youtu.be/6aO1CD3womE

**Comment by capnm** [comment]
Tested that on desktop and laptop, lts ubuntu 16.04.3 and the amd open source driver.
```
Linux t2t 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.4
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.2.4
```
Strange, with a 2D project that doesn't happen, so it seems to be some issue related to the video driver.

**Comment by capnm** [comment]
I can't reproduce this any more, it was probably a kernel driver issue.
