### ISSUE TITLE
Clicking on sub-resources in a node's right-click menu doesn't do anything

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#15649]
**Godot version:**
v3.0 rc1 (30d7943)

**OS/device including version:**
Linux Mint 18.3 Cinnamon x64

**Issue description:**
I expected that clicking on an item in the sub-resources menu would show the resource in the inspector, but right now it doesn't seem to do anything. I'm not really sure if the lack of behaviour is a bug or not.

![peek 2018-01-13 15-56](https://user-images.githubusercontent.com/27100585/34902931-570f6d3e-f87a-11e7-9ce0-480ce1e1cc92.gif)

**Comment by Noshyaar** [comment]
This is a bug AFAIK. I expect it should act the same as clicking resource's name in the inspector.

![image](https://user-images.githubusercontent.com/26753932/34903509-d78b7bfc-f865-11e7-9185-162ca22991a7.png)
