### ISSUE TITLE
Expanded controls with minsizes results in incorrect sizing inside some containers

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15644]
**Godot version:**
702e28f

**Issue description:**
When a control inside some specific containers(I have found it to happen with split and grid types for now) has its size flag set to `expand` and has a minsize value bigger than 0, will result in incorrect sizing, even when its current size is bigger than its minsize.

![screenshot2](https://user-images.githubusercontent.com/30739239/34897823-3954ced6-f7d7-11e7-8449-7fcb994d881d.png)

**Comment by akien-mga** [comment]
CC @groud, can you evaluate this one and see if it has to be fixed for 3.0 or can wait?

**Comment by groud** [comment]
I can't reproduce. @YeldhamDev, can you provide an example project ?

**Comment by groud** [comment]
Oh I got it !
I tested with a GridContainer (2 columns), with two panels inside both expanded and with a stretch ratio of 1. Both have a vertical minsize of 20px.
If I change the horizontal minsize of one of them (still less than half of the parent's width), its size is impacted, while it should not be the case until the minsize goes over half of the parents width.

**Comment by groud** [comment]
Note that the HBoxContainer and VBoxContainer work fine.

**Comment by groud** [comment]
[Believe it or not, I'm working on it.](https://www.youtube.com/watch?v=JsWgG5v7A3A) 
I managed to make GridContainer work, I have to check the SplitContainer. But I probably can copy-paste the code.
