### ISSUE TITLE
Bullet physics: Collision happens before the mesh contact

### ISSUE THREAD

**Issue by Juankz** [godotengine/godot#15648]
**Godot version:**

v3.0.beta.build2

**OS/device including version:**
GNU/Linux - Solus 3

**Issue description:**

Scene: Rigid body colliding against static body.

Godot Physics: Worked as expected
![godot](https://user-images.githubusercontent.com/18577412/34902632-7d0be6f8-f7ed-11e7-8295-4f07468a07cd.gif)

Bullet physics: Collision happens before the mesh contact
![bullet](https://user-images.githubusercontent.com/18577412/34902640-9c74f4da-f7ed-11e7-9aa0-85b0b11fd904.gif)

**Steps to reproduce:**
Run the minimal test with godot physics. Then run with bullet physics

**Minimal reproduction project:**

[minimalTestPhysics.zip](https://github.com/godotengine/godot/files/1628040/minimalTestPhysics.zip)

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by organicpencil** [comment]
Confirmed the issue. Broken in beta 2, working in master. The fix was 50c9937

**Comment by Noshyaar** [comment]
I'll close this as fixed. Please let us know if you can reproduce in latest master.

**Comment by Juankz** [comment]
Tested in master. Collision between bodies works well now. But I notice the exact same issue with the collision between a Rigidbody and Area3D. Should I open a new issue?

**Comment by vnen** [comment]
@Juankz it's better to open a new issue, preferably with another sample.

**Comment by Juankz** [comment]
False alarm. My mistake, I was scaling an area instead of a collision shape
