### ISSUE TITLE
Editor crashes when opening any project after building from latest

### ISSUE THREAD

**Issue by jdavid82** [godotengine/godot#15642]
**Godot version:**
Commit hash `e56b3439a5e8bf56c4b843e044a96f1446564745`
*Bugsquad edit:* e56b343

**OS/device including version:**

Windows 10 Home 64 bit

**Issue description:**

I rebuild from latest (as of commit hash mentioned above) and now the editor crashes when opening any project as per the screenshot below:
![image](https://user-images.githubusercontent.com/463793/34897011-10e8ef54-f840-11e7-91ae-52394dadd3ba.png)

**Steps to reproduce:**
* Open `x86 Native Tools Command Prompt for VS2017`
* `cd` to godot's repo
* run `scons -j6 platform=windows`
* Open the editor once it's built
* Double click on the 3D platformer demo
* crashes

**Minimal reproduction project:**

* Try latest 3D platformer demo, in the demos repo is currently at commit `f61c760e629c81f570ec9be2eedd3f36c902ca12`

**Comment by Noshyaar** [comment]
I can't reproduce this on Antergos x86_64. 702e28f

*Any* projects? Even the newly created ones?

**Comment by jdavid82** [comment]
@Noshyaar after reading your comment I tried again and got a new commit:
![image](https://user-images.githubusercontent.com/463793/34898193-da797ef6-f845-11e7-9516-2e815fd6f2f0.png)
And now it doesn't crash.

I noticed (I don't know if it's still related to this ticket) that the build log below shows that I had to enter the build command multiple times for the build to finish.

I read the documentation and it looks like I probably should be using an earlier version of `VS build tools`.

If it's not related to this ticket please please feel free to close it.
I could create a new ticket for the build log below, if you think it's necessary.
Thanks.
```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.5.2
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'

C:\Users\David\source>d:

D:\>cd Repos\godot

D:\Repos\godot>scons -j6 platform=windows
scons: Reading SConscript files ...
Detected MSVC compiler: x86
Compiled program architecture will be a 32 bit executable. (forcing bits=32).
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  4%] [94mCompiling [95m==> [93mmain\main.cpp[0m
[  5%] main.cpp
[ 59%] Compiling ==> editor\editor_about.cpp
[ 59%] editor_about.cpp
[ 68%] Compiling ==> editor\editor_node.cpp
[ 68%] editor_node.cpp
scons: *** [editor\editor_settings.cpp] Error
scons: building terminated because of errors.

D:\Repos\godot>scons -j6 platform=windows
scons: Reading SConscript files ...
Detected MSVC compiler: x86
Compiled program architecture will be a 32 bit executable. (forcing bits=32).
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  4%] [91mLinking Static Library [95m==> [93mmain\main.windows.tools.32.lib[0m
[ 69%] Compiling ==> editor\editor_settings.cpp
[ 69%] editor_settings.cpp
[ 77%] Compiling ==> editor\project_manager.cpp
[ 77%] project_manager.cpp
[ 89%] Compiling ==> core\engine.cpp
[ 89%] engine.cpp
[ 99%] progress_finish(["progress_finish"], [])
[100%] Linking Static Library ==> core\core.windows.tools.32.lib
[100%] Linking Static Library ==> editor\editor.windows.tools.32.lib
[100%] Linking Program        ==> bin\godot.windows.tools.32.exe
   Creating library bin\godot.windows.tools.32.lib and object bin\godot.windows.tools.32.exp
[100%] scons: done building targets.

D:\Repos\godot>
```

**Comment by jdavid82** [comment]
After new commit this issue is fixed

**Comment by reduz** [comment]
sorry, my bad, you had the bad luck of pulling on a very short time window

**Comment by jdavid82** [comment]
no problem, glad it's fixed, thank you
