### ISSUE TITLE
Rapidly created 2D rigid body objects won't sleep correctly

### ISSUE THREAD

**Issue by tommila** [godotengine/godot#15658]
**Godot version:**

Godot-3.0 hash: 7de3a114699fa31c8ab0ae8a5c95ef8e1113a090

**Issue description:**
Rapidly created 2d rigid body objects won't sleep if overlapped with other (unmasked/unlayered) shapes.

**Platform:**
Linux debian 4.9.0-4-amd64

**Steps to reproduce:**
Create large flat static body that represents surface/ground. 
Create large 2d kinematic body with collision mask and layer values set to zero. 
Create script that generates small 2d rigid bodies that collides with the surface object and connect them to a function that deletes the bodies when they enter to sleep state ("sleeping_state_changed" signal).
Move the kinematic body over the small rigid bodies on runtime.
When the small rigid bodies are overlapped with the bigger kinematic body, the sleeping_state_changed signal is never emitted.

Note: this only applies if the generation rate is small (1 per 0.25 sec or so), in bigger values the bodies are deleted correctly.
[Sleep bug](https://drive.google.com/file/d/11Jh74ow41zx9ERi11b9rKzagw55RjNpU/view)

**Minimal reproduction project:**

[sleep-bug.zip](https://github.com/godotengine/godot/files/1628252/sleep-bug.zip)

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
