### ISSUE TITLE
Errors when undo/redo removes text that is currently selected

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#15650]
**Godot version:**
v3.0 rc1 (30d7943)

**OS/device including version:**
Linux Mint 18.3 Cinnamon x64

**Issue description:**
![peek 2018-01-13 16-08](https://user-images.githubusercontent.com/27100585/34903031-64a2ccaa-f87c-11e7-898f-2b2eb2f513a2.gif)

**Comment by akien-mga** [comment]
Fixed by #15657.
