### ISSUE TITLE
Update PCRE2 to 10.30+

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#15662]
**Godot version:**
Current master branch (c01575b)

**OS/device including version:**
All.

**Issue description:**
We currently ship with PCRE2 10.23, but version 10.30 was released in 2017: https://www.pcre.org/news.txt

We should sync with this version, but only after 3.0 as this could introduce unwanted regressions.

**Comment by mhilbrunner** [comment]
Done in https://github.com/godotengine/godot/pull/19138
