### ISSUE TITLE
INT_MAX+1 strange result

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#15674]
Godot 3.0 Beta 2
Kubuntu 64-bit

Example:
```
extends Node

func _ready():
	var a = -9223372036854775807
	print(a)
	
	a -= 1
	print(a)
	
	a -= 1
	print(a)
	
	a += 1
	print(a)
	
	a += 1
	print(a)
```

Output:
```
-9223372036854775807
-'..--).0-*(+,))+(0(
9223372036854775807
-'..--).0-*(+,))+(0(
-9223372036854775807
```

What kind of number is `-'..--).0-*(+,))+(0(` ?
Would also be nice to have a `INT_MAX` variable.

**Comment by bruvzg** [comment]
int64_t to string convention function (String::num_int64) use `ABS()` here - [ustring.cpp#L1101](https://github.com/godotengine/godot/blob/master/core/ustring.cpp#L1101).
When it calculates `-(-9223372036854775808)` on a system with [two's complement](https://en.wikipedia.org/wiki/Two%27s_complement) signed integers it takes `-9223372036854775808 == 0x8000000000000000` use a bitwise not ` 0x7FFFFFFFFFFFFFFF` and then add `1` which cause overflow and gives back `-9223372036854775808 == 0x8000000000000000` (signed integer overflow is undefined behaviour and there is no guarantee that it will work like this on every C++ implementation).

This cause `mod` values here - [ustring.cpp#L1119](https://github.com/godotengine/godot/blob/master/core/ustring.cpp#L1119) to be negative and produce incorrect character codes. 

Fix #15679.
