### ISSUE TITLE
Close bottom dock when pressing ESC

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15682]
A minor UX enhancement, could pressing Esc close the bottom dock if nothing else listens to that key?
I was inspired by the way you can press Esc to close docks in QtCreator, and found myself mechanically press Esc to close those in Godot too, but was annoyed to have to take my mouse and close them manually.

**Comment by LinuxUserGD** [comment]
#15969

**Comment by akien-mga** [comment]
Fixed by #15862.
