### ISSUE TITLE
Empty indents after a line creates a fold

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15689]
Godot 3.0 master 6a4521da2ae0b08f42001c2c38396b28a2549c14

Writing one more indent the line after creates a fold, even if the next line doesn't contain anything. That fold is also non functional.
![image](https://user-images.githubusercontent.com/1311555/34912507-98b841e8-f8e3-11e7-903f-5de413abc3a3.png)

**Comment by vnen** [comment]
At this rate we'll need a tracker for folding issues.

**Comment by reduz** [comment]
@Paulb23
