### ISSUE TITLE
NodePath API in C# does not follow Pascal naming convention

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15685]
**Godot version:**
`master` / 30d7943311cdf4efbc6794a52df0e298f5e6d975

**OS/device including version:**
_Manjaro Linux 17.1-rc2_

**Issue description:**
Currently, most of the C# API in Godot follows Pascal (or camel) case in their naming convention, but `NodePath` class still contains members that follows snake case convention, such as `get_name_count` or `get_concatenated_subnames`.

They don't seem to work (#15656) for now, so ironically there's little danger that people will use them and later find out their project fails to compile once the convention problem gets fixed in future.

But it might be a good idea to make them consistent with other parts of the API before they start working again to avoid potential confusion.

**Comment by akien-mga** [comment]
CC @neikeq
