### ISSUE TITLE
Script editor characters are too high within their line "box"

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15688]
Godot 3.0 master 6a4521da2ae0b08f42001c2c38396b28a2549c14

Screenshots speak by themselves.

Godot 3.0:
![image](https://user-images.githubusercontent.com/1311555/34912371-430b32e4-f8e0-11e7-9687-5a95cc385546.png)
It even gets out of range at some zoom levels:
![image](https://user-images.githubusercontent.com/1311555/34912439-ecdb4ae2-f8e1-11e7-967c-2db71895a2e5.png)

QtCreator:
![image](https://user-images.githubusercontent.com/1311555/34912375-49cf8878-f8e0-11e7-8257-1d9d8b311ace.png)

Sublime Text 3:
![image](https://user-images.githubusercontent.com/1311555/34912380-59539a8c-f8e0-11e7-9be7-56685768e54b.png)

VSCode:
![image](https://user-images.githubusercontent.com/1311555/34912382-626a37f2-f8e0-11e7-9d8a-ac6623ce4431.png)

Notepad++:
![image](https://user-images.githubusercontent.com/1311555/34912383-67b0a566-f8e0-11e7-9472-31a82972b682.png)

Paint.NET:
![image](https://user-images.githubusercontent.com/1311555/34912388-6e75c80e-f8e0-11e7-8327-c788785af880.png)

LibreOffice:
![image](https://user-images.githubusercontent.com/1311555/34912389-73dc8efe-f8e0-11e7-9e7e-89d6ec593ab2.png)

Godot 2.1.4:
![image](https://user-images.githubusercontent.com/1311555/34912390-7a7175cc-f8e0-11e7-99b2-e84303c7d7f8.png)

MS Notepad:
![image](https://user-images.githubusercontent.com/1311555/34912393-9c362612-f8e0-11e7-94c4-062bdd0d1eab.png)

All examples use the same font (Consola.ttf) at the same size (except Godot 2.1.4). With the default Hack font, the difference is slightly less noticeable but still present.

**Comment by akien-mga** [comment]
That likely implies changing TextEdit a bit, so would be good to do before 3.0 to avoid regressions/compat breaking post release.
