### ISSUE TITLE
PackedScene.instance() Not Threadsafe

### ISSUE THREAD

**Issue by ubaldy** [godotengine/godot#15687]
**Godot version:**
Godot master periodically over the last month. Also tried 3.0 beta's 1 and 2.

**OS/device including version:**
Windows 10. Nvidia GTX 950. i7-5820K. 

**Issue description:**
Obvious corruption in multiple places if PackedScene.instance() called inside multiple threads simultaneously.

**Steps to reproduce:**
.instance() a scene from multiple threads simultaneously. Need a couple hundred calls before system starts corrupting.

**Minimal reproduction project:**
Here are three variants of a work around. Either using mutexes around all calls to .instance() or moving all calls of .instance() to main thread fixes the problem. Just run the thread_test scene in the attached projects to test it out. To reproduce, remove mutex around .instance() call in script on main node.
[threading_instance_issue.zip](https://github.com/godotengine/godot/files/1628996/threading_instance_issue.zip)

**Comment by reduz** [comment]
May this be related to the recent fixes by @RandomShaper ?

**Comment by RandomShaper** [comment]
I don't know which changes of mine may have had an effect on this.

By the way, is the scene tree API meant to be thread-safe?

**Comment by ubaldy** [comment]
@RandomShaper I looked through your commits and nothing jumped out at me. 

This appears to be a resource loading issue more than a scene tree API issue. This affects background loading from my perspective at least.

**Comment by ubaldy** [comment]
Of interest, the Input subsystem gets clobbered every once in a while. This could be random but could also be a lead.

**Comment by ubaldy** [comment]
That was an easy fix. Preliminary results show that putting a MutexLock at the beginning of PackedScene.instance() that locks a member variable Mutex completely solves the problem. I will test more then do a pull request.

**Comment by ubaldy** [comment]
Would a mutable cache make a const member function non-reentrant?

**Comment by RandomShaper** [comment]
I think so.

**Comment by akien-mga** [comment]
As #15751 was moved to the 3.1 milestone, I guess this issue can be too.

**Comment by ubaldy** [comment]
Will do a formal approach to multithreading in Godot. This isn't that big of a deal at the moment since most people think the scene tree is not expected to be threadsafe.
