### ISSUE TITLE
CollisionShape is not physically scaled by its parent

### ISSUE THREAD

**Issue by hickop** [godotengine/godot#15695]
**Godot version:**
3.0 c01575b3125ce1828f0cacb3f9f00286136f373c

**OS/device including version:**
Linux nvidia 770gtx 387.34

**Issue description:**
Scaling an object containing a CollisionShape does scale the CollisionShape visually but not physically.

**Minimal reproduction project:**
[collision_scale.zip](https://github.com/godotengine/godot/files/1629198/collision_scale.zip)

**Comment by Zireael07** [comment]
Collision shapes aren't meant to be scaled physically at all.

**Comment by hickop** [comment]
As my test sample works in beta2 I thought it was an issue. It makes it really strange seeing object colliding invisible shape. Maybe the CollisionShape should not appear scaled at all then.

**Comment by akien-mga** [comment]
> As my test sample works in beta2 I thought it was an issue.

Note for future issues: *always* mention things like that. A regression (something that worked and later broke) and a feature that does not do what would be expected are two very different things, and regressions are much easier to fix (when we know that they are actually regressions).

**Comment by hickop** [comment]
Narrowed it down to: https://github.com/godotengine/godot/pull/15606
CC @RandomShaper

**Comment by RandomShaper** [comment]
I'll have a look in a few hours. I don't get the reason of this side effect.

**Comment by akien-mga** [comment]
I can confirm that a local revert of #15606 fixes the issue (for the provided example).

**Comment by RandomShaper** [comment]
It doesn't happen in 2D Physics nor in 3D with Godot Physics.

I'd say this has uncovered a latent issue in the Bullet backend. So far I've been not able to spot the bug.

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by RandomShaper** [comment]
For instance, even with #15606 reverted, if you add the following script to the `CollisionShape` under the `StaticBody`, you get wrong behavior:

```
extends CollisionShape

func _ready():
	scale = Vector3(1, 1, 1)
```

**Comment by AndreaCatania** [comment]
Can you please check it again with this PR: #15777?
