### ISSUE TITLE
Folds don't work with non-indented content

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15690]
Godot 3.0 master 6a4521da2ae0b08f42001c2c38396b28a2549c14

In the following code, the array cannot be folded, which is unexpected.
The multiline string inside, however, ends up having folds, which is unexpected.

```gdscript
func _ready():
	var z = [
"""
Hello World!
	Yadayadayada
		yaaaaaaaaaa
"""
	]
```

![image](https://user-images.githubusercontent.com/1311555/34912570-0b8a54da-f8e5-11e7-9cd1-793f54a54657.png)

At this point I would suggest code folding to become a bit more code aware, since it would also help with other languages that are not indentation-based (shaders, C#, JSON or whatever Godot can edit)

**Comment by vnen** [comment]
Yeah, I think that the GDScript module should decide which blocks are foldable and just have an API in TextEdit to set those blocks. Other code editors could use different criteria for code folding.

**Comment by reduz** [comment]
@Paulb23 
though I think this wont get fixed anytime soon..

**Comment by Skaruts** [comment]
In my experience from using other editors, this is normal behavior.

**Comment by Skaruts** [comment]
One thing that could be improved that sometimes causes this problem is the way Godot comments out code
```gdscript
func do_things():
    something.x = 10
    something.y = 100
    # this is a user comment. The comments below are made through hotkey
#   things.append(cake)
#   things.append(bbq_sauce)
```
Godot could try to comment indented code like this
```gdscript
func do_things():
    something.x = 10
    something.y = 100
    # this is a user comment. The comments below are made through hotkey
    #things.append(cake)
    #things.append(bbq_sauce)
```

**Comment by KoBeWi** [comment]
Still valid in 0b910cd

**Comment by MatteoPiovanelli-Laser** [comment]
6b0b1a4c042175190381737e3000027ef912e6cb
I'm seeing a similar folding "issue".
![image](https://user-images.githubusercontent.com/19283945/139580343-34d72348-cd1c-4ba7-a0ca-b8ea9a88b90b.png)
If I fold the `_ready()` function there, the comments below are folded in as well:
![image](https://user-images.githubusercontent.com/19283945/139580384-b6a5325f-3ff2-4c22-b19f-06898944be5c.png)
In my experience with other IDEs (mostly VS) that's unexpected.

**Comment by DinDotDout** [comment]
The first issue mentioned appears to be resolved by now. The issue metioned by @MatteoPiovanelli-Laser is the same as in #84820 and #85016 will potentially fix it.
