### ISSUE TITLE
TextEdit has `add_color_region`, but no way to get colors

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15691]
Godot 3.0 master 6a4521da2ae0b08f42001c2c38396b28a2549c14

TextEdit exposes `add_color_region` and `add_keyword_color` to colorize text, but it has no getter to access coloring information.
Use case: making a code minimap.

**Comment by YeldhamDev** [comment]
Are you pretending to make a code minimap plugin? Because that would be awesome!
