### ISSUE TITLE
Reimport intermittently causes Inspector preview to go black

### ISSUE THREAD

**Issue by brainsick** [godotengine/godot#15692]
**Godot version:**
6a4521da2ae0b08f42001c2c38396b28a2549c14

**OS/device including version:**
Ubuntu 17.10, AMD Radeon R9 Fury

**Issue description:**
Spawned from [here](https://godotengine.org/qa/22327/why-does-fix-alpha-border-effect-jpgs).

I'm trying to import [displace_2.jpg](https://github.com/jedStevens/water2D/blob/master/displace_2.jpg) into Godot 3.0 (rc1-ish; self compiled) as was done in the sample.

Inspector preview goes black intermittently when Reimporting assets.  I was playing with the following settings if that's relevant:

Import As: Texture, Preset.. 2D
Compress:
Mode: Lossy
Lossy Quality: 0.7
Flags:
Repeat: Enabled
Filter: On
Mipmaps: On
Process:
Fix Alpha Border: Off (unchecked)

The console is reporting:

```
ERROR: create: Expected data size of 4194303 in Image::create()
   At: core/image.cpp:1193.
```

**Minimal reproduction project:**
GitHub doesn't allow mp4/video attachments.  So, [here](https://youtu.be/QbiY8fvO4BE).

**Comment by poke1024** [comment]
Seems to happen when going to lossy then turning on mipmaps, then reimporting. A bug inside `StreamTexture::_load_data` that calculates a `total_size` of `4194304` (based on 11 mipmaps it reads), whereas `Image`'s own calculation in `_get_dst_image_size` expects `4194303`. There's another problem hiding here: what if the mipmap count `mipmaps` read in `StreamTexture::_load_data` is completely different? I think `Image` needs a new constructor to import that stuff.

**Comment by poke1024** [comment]
The lossy format decompressed in `StreamTexture::_load_data` loads 11 mipmaps, but `Image::get_image_required_mipmaps` says it wants only 10 mipmaps for that image size.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
