### ISSUE TITLE
Setting pause mode has no effect

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#15694]
**Godot version:**
v3.0 859ac62

**OS/device including version:**
Linux Mint 18.3 Cinnamon x64

**Issue description:**
Neither setting a node's pause mode to "stop" through the inspector, nor setting `pause_mode` to `PAUSE_MODE_STOP` in a script have any effect. They keep processing as if set to "process".

**Minimal reproduction project:**
[Pause mode bug.zip](https://github.com/godotengine/godot/files/1629172/Pause.mode.bug.zip)

**Comment by eska014** [comment]
Use `get_tree().set_pause(true)` to pause the game. A node's pause mode configures how it behaves during pause. http://docs.godotengine.org/en/latest/learning/features/misc/pausing_games.html

**Comment by akien-mga** [comment]
Indeed.
