### ISSUE TITLE
Can i use yield(Object object, String signal) in C# method on Godot 3 mono 

### ISSUE THREAD

**Issue by darkyuu** [godotengine/godot#15698]
**Godot version:**
Godot 3.0 Beta2 mono

**Issue description:**
i found yield(Object object, String signal) method in GDScript docs. I want to use it in C# Script
Does it have this method in C# API form? if it has. How to?

Thank you.

**Comment by paulloz** [comment]
Hi there.  
According to [the documentation](https://godot.readthedocs.io/en/latest/learning/scripting/c_sharp/c_sharp_differences.html#other-differences), `yield` is not available in C# yet.

**Comment by Zylann** [comment]
C# has yield, but it's quite different from the one GDScripy has. However, I remember the C# integration is able to use `await` to wait for a signal.

**Comment by NathanWarden** [comment]
Zylann is right, you should learn to use async methods. However, you can always create a yield system yourself.

If you look in my Unity Compatibility system I have my own coroutines based on Unity's. Look specifically how I implement the coroutines List: https://github.com/NathanWarden/UnityGodotCompat/blob/master/UnityEngine/MonoBehaviourController.cs

So, you could basically use an auto load singleton and just call MyAutoLoad.StartCoroutine(MyIEnumerator());

But, again, you should learn how to use async/await methods instead as they're almost just as easy, but built in... https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/await

**Comment by darkyuu** [comment]
thank you Zylann and NathanWarden

i use async/await in my project. it works

sample from my code:

private async void ShowMainMenuHUDAfterGameOverMessageIsGone()
{
	int result = await Task.Run(() => DidGameOverMessageTimeout());
	if(result == 1)
	{
		startButton.Show();
		messageLabel.Text = "Dodge the\nCreeps!";
		messageLabel.Show();
	}
}

private int DidGameOverMessageTimeout()
{
	while(true)
	{
		if(!messageLabel.IsVisible())
			return 1;
	}
}

**Comment by neikeq** [comment]
The API provides a SignalAwaiter similar to GDScript's yield on signal:

``` C#
await ToSignal(sender, "signal");
```

**Comment by darkyuu** [comment]
thank you neikeq

i try to use them. it work and more easy to read than my recent code

this is edited code sample:
public void GameOver()
{
	ShowMessage("Game Over");
	ShowMainMenuHUDAfterGameOverMessageIsGone();
}
	
private async void ShowMainMenuHUDAfterGameOverMessageIsGone()
{
	await ToSignal(messageTimer, "timeout");
	startButton.Show();
	messageLabel.Text = "Dodge the\nCreeps!";
	messageLabel.Show();
}
