### ISSUE TITLE
Collada (.dae) import inaccurate.

### ISSUE THREAD

**Issue by leiget** [godotengine/godot#15693]
EDIT: The problem was I was compressing the mesh when importing in Godot. It would evidently make the location of the meshes less precise if the individual meshes are far apart in the DAE file. To fix this, go to the import tab while your DAE file is highlighted in Godot's file browser, and make sure "Compress" under the "Meshes" section is *not* selected/highlighted.

- [x] I've searched the issue list for a similar issue and found none.

**Godot version:**
v3.0.beta.custom_build.6a4521d

**OS/device including version:**
Xubuntu 16.04

**Issue description:**
     I export a mesh with no materials, animations, or anything else, just the mesh using both the Blender default Collada exporter and the Better Collada exporter.
     When I import either of those dae files, meshes are not always exactly where they are supposed to be. For instance, look at this picture:
![dae_problem](https://user-images.githubusercontent.com/20325471/34913493-b1dbb6ba-f8c4-11e7-93d7-502de0ee5401.png)
     On the left side is Godot, with the imported dae mesh. The result is exactly the same with either the Blender Collada exporter or the Better Collada exporter.  On the right side is the same dae file imported back into Blender after exporting it with either two of the scripts. And as you can see, in Godot the floor and the wall (two separate meshes) have a gap, but not in Blender even after importing the same file.
     I checked the origins of the meshes in this picture, and the locations of each mesh in Godot match the locations in Blender, before and after export and reimport.

**Steps to reproduce:**
Check my sample project file. Export using the included Blend file and see for yourself.

**Minimal reproduction project:**
[ColladaImportIssue.zip](https://github.com/godotengine/godot/files/1629118/ColladaImportIssue.zip)

**Comment by lichyard** [comment]
This was caused by not applying location to the objects in the .blend file. Assets import correctly when location is (re)applied.

![screenshot_2018-01-14_10-32-22](https://user-images.githubusercontent.com/2403360/34913843-3e8df07a-f918-11e7-995e-91d8d98cfccf.png)

**Comment by akien-mga** [comment]
So I guess this needs to be better documented. Do we have a page about the Blender import workflow already? @godotengine/documentation

**Comment by leiget** [comment]
Really!? I applied location and rotation over and over again, just to be sure. Do I have to apply *just* the location?

**Comment by reduz** [comment]
you can also disable mesh compression and this will also solve these kind
of problems

agreed compression should be much better documented

**Comment by leiget** [comment]
Yep, it was the compression that was the issue. I'll have to read that in the docs whenever someone gets to it. Thanks.
