### ISSUE TITLE
Regression: rigidbody not colliding with static body

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#15703]
**Godot version:**
c01575b

**OS/device including version:**
Win 7 x64

**Issue description:**
Rigidbody sinks through floor (if box shape used on floor) or jitters halfway stuck (if plane shape). First noticed on vehicle bodies and then made a plain rigidbody and observed same behavior.

**Steps to reproduce:**
Import a copy of a project from beta 2, see stuff sinking through floor, create a rigidbody, see it sinking too.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Maybe be related to #15695 and #15606, cc @RandomShaper.

**Comment by RandomShaper** [comment]
I'm checking this in a few hours.

**Comment by akien-mga** [comment]
Please provide a minimal project that triggers the issue, I can't reproduce it myself with the project in #15695 (which is a RigidBody sphere colliding with a StaticBody plane).

**Comment by Zireael07** [comment]
I will try to make a minimal project but no guarantees that it'll be soon (fairly swamped with work)

**Comment by Zireael07** [comment]
Affects rc1 too. Here's how it looks with rc1: https://gfycat.com/ResponsibleSkinnyArchaeopteryx

Vehicle body: box shape
Floor is a static body with plane shape

I will try to make a simplest possible repro (one car + floor) today.

**Comment by Zireael07** [comment]
I tried making a small reproduction project and it doesn't happen. Probably something related to the fact that the project went from beta 2 and/or to the fact that it was originally an export from 2.1.4.

I guess I'll close this and simply remake half of the scene again :/

**Comment by volzhs** [comment]
![staticbody](https://user-images.githubusercontent.com/8281454/34941221-3e6b0e56-fa36-11e7-9bb2-b35a313f856f.gif)
I tested with 05b184381
StaticBody's CollisionShape has PlaneShape.

I couldn't reproduce it either.

**Comment by Zireael07** [comment]
Closing as I simply remade my main scene in rc 1 and it all works again, so must have been something weird in the single scene :P
