### ISSUE TITLE
Unpredictable RigidBody2D bounce against 2 bodies.

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#15707]
**Godot version: Godot 3, b5b2ca8**

**OS/device including version: Ubuntu 17.10**

**Issue description:**
While testing how rigid bodies gain energy after bounces I have found that collisions on 2 consecutive shapes can be totally unpredictable.
Perfect vertical bounces can make bodies from slowly move to a side to turn ballistic.

**Steps to reproduce:**
Run the example project and leave them bounce for a minute.
Bodies that partially touch a second tile will start to slowly move to the sides and later bounce with high angular velocity.
This is reproducible with with 2 bodies too, not only tiles (but mostly affects tilemap usability).

**Minimal reproduction project:**
[bad_rb2d_collision.zip](https://github.com/godotengine/godot/files/1629472/bad_rb2d_collision.zip)

**Comment by reduz** [comment]
I am not totally convinced this is a bug to be honest. Bounce model (when bounce is 1.0) has never been very realistic in physics engines, specially given how contacts are computed. By looking at this example, I don't really see anything that could be changed or fixed. It behaves as expected, even if it's weird. 

I will be closing and archiving, but if a simpler and a lot more specific test case can be created when it's very clear that something is wrong, will be happy to open and test again.

**Comment by eon-s** [comment]
A deterministic physics mode could be useful, getting always different responses makes the physics engine useless for some mechanics.
