### ISSUE TITLE
Editor binary next to project.godot loads project manager with game settings if main_scene missing

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#15704]
**Godot version:**
Current master (f96f11c85)

**OS/device including version:**
Any.

**Issue description:**
When running the Godot editor from a path containing a `project.godot` file without the `-e`/`--editor` argument, it's expected to run the project.

But if the `project.godot` file has no main scene (`application/run/main_scene`) defined, it will instead start the project manager after loading the game's project settings (and especially its stretch options, etc.).

It should instead either abort (no scene to run) or maybe edit the project (but I think abort might be better).

**Steps to reproduce:**
- Create a project with no main scene defined but custom display options (e.g. 320x240) and stretch options (e.g. viewport scaling).
- Go to that project's folder in your terminal
- Run your Godot editor binary from that folder

**Minimal reproduction project:**
[bug_no_main_scene.zip](https://github.com/godotengine/godot/files/1629423/bug_no_main_scene.zip)

**Comment by paulloz** [comment]
Would this make a good [*junior job*](https://github.com/godotengine/godot/labels/junior%20job)? If so I can check it myself.

**Comment by akien-mga** [comment]
I guess, yes. I initially decided against it because one likely needs to mess with `main.cpp`, but if you're not afraid by this weird entry point into the engine, it should indeed be fixable with a couple lines.

**Comment by akien-mga** [comment]
Fixed by #15741.
