### ISSUE TITLE
2D screen space shaders corrupted with stretch_mode=viewport or fullscreen

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#1571]
Running the screen space shaders example, if I change the `stretch_mode` to "viewport" and then resize the window, the shader becomes corrupted:

![Screenshot](https://dl.dropboxusercontent.com/u/7063628/godot-sss/Screen-Space%20Shaders_001.png)

I was trying to use a screen space shader for an effect. It looks fine in the editor, but my game uses the "viewport" stretch mode and a test_width/test_height that are half the size of my screen. Under those conditions, when the game is run the shader graphic was always corrupted. I was also seeing the shader become corrupted after using `OS.set_window_fullscreen()` .

Using git version a12c364489df586bf3cbb38f613c0615f88eaff1 on Ubuntu 14.10.

**Comment by jotson** [comment]
Don't know if this helps any but I can fix the fullscreen issue by adding

`rasterizer->reload_vram();`

to the end of

`OS_X11::set_wm_fullscreen`

I noticed something similar being done in `os_android.cpp`. If I also use stretch_mode=2d (instead of stretch_mode=viewport) then the issue is solved for me.

Is `rasterizer->reload_vram()` a legit fix? I can submit a PR if you think it's a good idea.

**Comment by hurikhan** [comment]
In a nutshell:

* open the demos/2d/screen_space_shaders demo
* change the stretch_mode to "viewport"
* run it
* choose an effect
* resize the window

^^I have taken the liberty to copy your instruction from the mailing list.
Can somebody confirm this issue on Windows or OSX?

**Comment by reduz** [comment]
i just get a GPU crash instead.. nice..
I have not the slightest clue what might be going on.. but reload_vram definitely has nothing to do with this

**Comment by reduz** [comment]
wish there was some way to debug it

**Comment by UsernameIsAReservedWord** [comment]
Below is what I get on Windows 8.1 64bits AMD R4 GPU.
`strech_mode = viewport`
`keep = ignore`
It does not crash. Behavior change with the aspect ratio of the window.

![godot_20150409_1327_bug_screen_shaders_and_strech_mode_to_viewport_00](https://cloud.githubusercontent.com/assets/9801802/7066157/16f331d0-dec0-11e4-88ee-bdc62ba6ab4f.jpg)

![godot_20150409_1327_bug_screen_shaders_and_strech_mode_to_viewport_01](https://cloud.githubusercontent.com/assets/9801802/7066162/214a771a-dec0-11e4-97b8-cb29cfb03b44.jpg)

![godot_20150409_1327_bug_screen_shaders_and_strech_mode_to_viewport_02](https://cloud.githubusercontent.com/assets/9801802/7066171/3825b850-dec0-11e4-99b3-2092e8573925.jpg)

![godot_20150409_1327_bug_screen_shaders_and_strech_mode_to_viewport_03](https://cloud.githubusercontent.com/assets/9801802/7066179/4bd4aac8-dec0-11e4-8fc8-467378909ace.jpg)

**Comment by UsernameIsAReservedWord** [comment]
Hey, in my case, this issue seems to have been solved by : https://github.com/okamstudio/godot/commit/3b434eacde58450965708c3eafb6b22eb2a99361

Could you confirm @jotson ?

**Comment by UsernameIsAReservedWord** [comment]
Oh my bad ... i spoke too fast again ... sorry, it's not solved.

**Comment by HeartoLazor** [comment]
Any status on this issue?
I have a pixel based game with viewport mode, and the shaders only work with 2d mode, when the game is scaled on viewport mode to a different resolution (example a 320x240 target game, scaled x2), all shaders that uses coordinates from vec3 c = texscreen(SCREEN_UV); instructions gets broken.

For my understanding, performance wise for a low resolution pixel game viewport stretch mode > 2d stretch mode, also on viewport mode ensures that all shader effects maintain always the same pixel size.

**Comment by reduz** [comment]
ah right i have to check this in windows because in Ubuntu the crash corrupts the stack

**Comment by Cybolic** [comment]
Just adding a comment to push this issue to the front, as suggested here: https://www.facebook.com/groups/godotengine/permalink/647160102087254/

**Comment by akien-mga** [comment]
See https://github.com/rippledodger/godot/commit/f15bd9c8aa6ff62ed3358f4809b735a56110f3fb for a proposed fix - @reduz was saying however in #2377 that it might beat the purpose of the feature, so he'll probably implement his own fix when he gets to it.

**Comment by reduz** [comment]
Is this not fixed already?

**Comment by jotson** [comment]
Problem remains on latest master 3c6dd5749d445f082fc925a34cc0a26f8d342304

**Comment by jotson** [comment]
I'm still seeing this problem using the latest master e4cb104e6daa9c2e5781535ac8790f406ae53f08.

Resizing the window to a larger dimensions seems to work fine. But resizing the window to a smaller size results in the same corruption as before. For example, using test_width and test_height smaller than width and height in the scene settings with stretchmode=viewport.

**Comment by reduz** [comment]
yes, this won't be fixed as it's really difficult with GLES2. GLES3 backend
in 3.0 will work better

**Comment by jotson** [comment]
No problem (2d is workaround for me). Thanks for all your hard work on this.

**Comment by HeartoLazor** [comment]
So this will be fixed with the GLES3 backend update?

**Comment by reduz** [comment]
yeah, working on GLES3 update and this will definitely be fixed
