### ISSUE TITLE
Changing energy BakedLightmap requires re-baking

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#15716]
**Godot version:**
109242c

**OS/device including version:**
Debian GNU/Linux 9.3

**Issue description:**
Changing energy BakedLightmap requires re-baking. With GIProbe, it immediately takes effect.

**Steps to reproduce:**
Bake a scene with BakedLightmap mode at energy 1 and change energy to 0 afterwards, the light will still be on.

**Comment by akien-mga** [comment]
Isn't it expected, since GIProbe is real time while BakedLightmap is fully baked?

**Comment by Zireael07** [comment]
I was expecting baked lightmap's energy to be changeable without rebaking. Why bake the information about energy anyway? It's just a multiplier on top of everything else that's stored...

**Comment by seadra** [comment]
I don't think it's expected because as @Zireael07 mentioned, it's just an overall multiplier and doesn't depend on the position of lights or objects, or the scene geometry.

Being able to change it dynamically is useful for having some kind of light dynamics.

By the way, can the algorithm used for BakedLightmap allow adjusting the energy multiplier of individual light sources as well?

**Comment by reduz** [comment]
if you edit the baked lightmap resource, you can change the energy there,

**Comment by seadra** [comment]
Thanks, that does work!

Is there a way we can control the energy of light sources independently?

**Comment by Calinou** [comment]
> Is there a way we can control the energy of light sources independently?

I would be surprised if this was possible given the current lightmap implementation; I guess something like lightstyles (as seen in Quake 1/2 and Unreal 1) would require baking lights on multiple textures.

**Comment by reduz** [comment]
> Is there a way we can control the energy of light sources independently?

Sure, check the Indirect Energy property of lights. Of course this is fully baked when using lightmaps, so you need to rebake.

**Comment by seadra** [comment]
I meant without having to rebake it of course :) I opened a new issue, #15727, about it.
