### ISSUE TITLE
Godot crash if a shortcut for freelook is at none

### ISSUE THREAD

**Issue by Nutriz** [godotengine/godot#15721]
**Godot version:**
Godot 3.0rc1 windows 10

**Issue description:**
Godot crash when right click on 3D view(freelook)  if a shortcut for freelook is at none.

![image](https://user-images.githubusercontent.com/7358899/34921185-058fd6f0-f97f-11e7-92c7-7b320fc255bc.png)
![image](https://user-images.githubusercontent.com/7358899/34921259-08d31678-f980-11e7-8c2c-55b4b12e4f79.png)

**Steps to reproduce:**
* Go to Editor > Settings > Shortcuts
* Search for "Freelook Up" and remove the shortcut
* Right click on 3D View

**Comment by akien-mga** [comment]
CC @Zylann

**Comment by Zylann** [comment]
Can you guess which one will output? A or B?

```cpp
static int try_get_shortcut_scancode(const String &p_path) {
	Ref<ShortCut> shortcut = ED_GET_SHORTCUT(p_path);
	if (shortcut.is_null()) {
		print_line("A");
		return -1;
	}
	InputEventKey *k = Object::cast_to<InputEventKey>(shortcut->get_shortcut().ptr());
	if(k == NULL) {
		print_line("B");
		return -1;
	}
	return k->get_scancode();
}
```
The answer was... B!
