### ISSUE TITLE
Android Export doesn't work properly

### ISSUE THREAD

**Issue by Nobelix** [godotengine/godot#15725]
**OS/Device:** 
Exported on Ubuntu 16.04
Godot 3.0 RC1

To a Lenovo A2010 running Android 5.1

**Issue description:** 
Once exported, the project displays only the UI without the 2D render.
![](https://i.imgur.com/9dRxPRO.png)

Related to #15717 ???

**Steps to reproduce**
Create a project with some 2d elements and export it to Android.

**Comment by Nobelix** [comment]
Ok, a strange thing is that in Beta 1 WASM worked fine for another 2D project but had the same issue on Android. Thought it was my phone not supporting OpenGL 3.0. I will share the project tomorrow as I'm going to sleep.

**Comment by Nobelix** [comment]
Ok, a strange thing is that in Beta 1 WASM worked fine for another 2D project but had the same issue on Android. Thought it was my phone not supporting OpenGL 3.0. I will share the project tomorrow as I'm going to sleep.

**Comment by eon-s** [comment]
Is a Parallax the background? can you try with a fixed sprite?

**Comment by Nobelix** [comment]
It's not a parallax, it's a Sprite with a moving region rect

**Comment by jedStevens** [comment]
I exported to Android and got a flashing splash screen.

**Comment by Nobelix** [comment]
@akien-mga ok so I just tested it with another project and it does the same thing. Here is a link to it
https://framadrive.org/s/Yk81uzsbFDtmu9D
