### ISSUE TITLE
All categories unfold when one key binding is changed

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15726]
Godot 3.0 master 109242c011255757c981f634a33f59268a113f67

I tried deleting one of the shortcuts, and to find it I decided to fold categories one by one until I find the one I want. Then I found the shortcut, and deleted it. Doing so caused the window to update and I lost the view on the shortcuts I was watching. Turns out my action unfolded every category.

It would be better if that didn't happen^^

https://www.youtube.com/watch?v=dFHHx-0rG3A

**Comment by Nutriz** [comment]
I got the same problem but I thinked "uh don't be so meticulous with all :D

**Comment by icnikerazah** [comment]
duplicate of https://github.com/godotengine/godot/issues/14628
also another bug on shortcuts panel https://github.com/godotengine/godot/issues/14372
