### ISSUE TITLE
NEXT Classic USB gamepad not recognizing all the keys

### ISSUE THREAD

**Issue by Superwaitsum** [godotengine/godot#15722]
Searched existing issues, may be related to #12696

**Godot version:**

3.0 RC1 (also happens in alpha 2)

**OS/device including version:**

Windows 8.1 x64

**Issue description:**

Gamepad API doesn't seem to handle all the possible key inputs in 3.0. Works well in 2.1.4.

On some controllers, only buttons 0,1,10 and 11 work. Axis are not affected.

Tested with several USB controllers. Bug does not affect all controllers. 
(Affects snes and sega megadrive Datafrog imitation and possibly other controllers)

**Steps to reproduce:**
Testing all the keys in a gamepad affected by the bug. 

**Minimal reproduction project:**

Testing an affected controller in the Joypads demo in Godot 3.0

**Comment by akien-mga** [comment]
CC @Hinsbart

**Comment by Hinsbart** [comment]
Can you try `Input.get_joy_guid(0)` (supposing your device is the first attached one -> id 0), so that we can see if the associated mapping changed recently?

Also, you may try generating a new, hopefully correct, mapping yourself with this tool http://www.generalarcade.com/gamepadtool/ and add it with `Input.add_joy_mapping(<mapping_string>, true)`

**Comment by Superwaitsum** [comment]
Thanks for replying, the ID is 100801e5000000000000504944564944 for both controllers , I remapped it in the gamepadtool (had the same incorrect behavior in the tool) and it works correctly (inside the gamepadtool)

**ORIGINAL (Default and how it works currently in Godot 3.0)**

100801e5000000000000504944564944,NEXT Classic USB Game Controller,a:b0,b:b1,back:b8,start:b9,rightx:a2,righty:a3,leftx:a0,lefty:a1,platform:Windows,

**NEW (Remapped and working)**

100801e5000000000000504944564944,NEXT Classic USB Game Controller,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b6,leftx:a0,lefty:a1,platform:Windows,

Also the sega controller needs replacing 'b6' for 'b5' (rightshoulder) but doing this overrides the mapping

At the moment I'm not working on a game that can be played with controller, so I have no need to add it in script, but could cause problems to others. (and to me when trying to play godot games with a controller 😃 )

Since this doesn't seem to be Godot's fault, should I report it to SDL_GameControllerDB (and try to fix it)?

**Comment by akien-mga** [comment]
Since it's only a specific brand of controllers that seem affected by this issue, it's not critical for 3.0. We'll how to see with the SDL guys how to best fix it upstream and get the same fix here (apparently different controllers from this manufacturer share the same UID..?).

**Comment by Superwaitsum** [comment]
This has been fixed in https://github.com/gabomdq/SDL_GameControllerDB/commit/8ca95ea6cfcf9e1295c4c91a65fccc060b8ebb3d (my PR got accepted), so it will be fixed in the next SDL_GameControllerDB database sync.

**Comment by reduz** [comment]
Was this synced?

**Comment by akien-mga** [comment]
Not recently AFAIK.

**Comment by akien-mga** [comment]
Should have been fixed by #22466.

Please comment if it's still not working.

**Comment by Superwaitsum** [comment]
Can confirm is fixed in master, thanks
