### ISSUE TITLE
viewport in 2d no affect

### ISSUE THREAD

**Issue by vzex** [godotengine/godot#15737]
Godot 3.0 rc1

subscene like this :
![image](https://user-images.githubusercontent.com/4971777/34929104-d9028f96-f9fc-11e7-8599-e8ff6b8137a8.png)
and i tried to add a viewport into another scene like this(Node2D is the subscene above)
![image](https://user-images.githubusercontent.com/4971777/34929506-40168bc2-f9ff-11e7-9481-42115b5d675a.png)
but, if i moved ths Node2D down to the viewport,  
![image](https://user-images.githubusercontent.com/4971777/34929538-684ad292-f9ff-11e7-9013-a5a94480fc98.png)
it shows nothing.
I found the demo in 2.1 (split screen platformer, and the demos has been removed now on github) works well, but when i changed into v3.0, the viewport just has no effect.So does v3.0 get another way to handle this ? or just a bug?

**Comment by bojidar-bg** [comment]
I think you are looking for the ViewportContainer class.

**Comment by vzex** [comment]
@bojidar-bg I don't know how to use ViewportContainer ,is there any document?

**Comment by eon-s** [comment]
Put the ViewportContainer node as parent, any control does not work anymore.

**Comment by KoBeWi** [comment]
> Put the ViewportContainer node as parent, any control does not work anymore.

Seems like this is [already documented](https://docs.godotengine.org/en/latest/tutorials/viewports/viewports.html). I mean, the documentation only mentions ViewportContainers, not Controls.
Unless the proper fix would be explicitly saying that Control nodes no longer work this way?

**Comment by KoBeWi** [comment]
Closing as per above comment. I don't think people would try to use Controls anymore.
