### ISSUE TITLE
Android Modules are not usable in Godot 3.0.rc1

### ISSUE THREAD

**Issue by Kopfenheim** [godotengine/godot#15736]
**Godot version:**
v3.0.rc1 commit: 0a691bf

**OS/device including version:**
Windows 10

**Issue description:**
After seeing that the release candidate version has been announced, I decided to test it out. I am specifically testing out this module https://github.com/kloder-games/godot-admob. I followed the steps described for that module but I can no longer access the singleton associated with the Android module. 

In the stable v2.1.4, I used to use `Globals.has_singleton("AdMob")` to check if the module singleton is available and `Globals.get_singleton("AdMob")` to get the singleton so I can use it. But in v3.0.rc1, I get "Parse Error: Identifier not found: Globals". 

I have tried using `ProjectSettings.has_singleton("AdMob")` and `ProjectSettings.get_singleton("AdMob")` as well but those methods don't seem to exist in `ProjectSettings.`

I have also noticed that if the Globals keyword is not supported in v3.0.rc1, then the references to `Globals` in register_types.cpp ([this line](https://github.com/kloder-games/godot-admob/blob/37703f8048d50b066b61068d742de1e3a7b38b8d/admob/register_types.cpp#L7)) would also need to be changed in the Android module. But, I can't find any information about what it needs to be changed to in order to make the module work on v3.0.rc1

**Steps to reproduce:**
Compile the above mentioned module to create an Android template and test it.

**Comment by akien-mga** [comment]
That's a 2.1.x module, so I doubt you can use it out of the box on 3.0. Did you manage to build it out the box?

`Globals` was renamed to `ProjectSettings`, but the singleton managemenet is now handled in `Engine`, so try `Engine.has_singleton("AdMob")`.

**Comment by Kopfenheim** [comment]
I was able to build it without any problems. And I just tried to use `Engine.has_singleton("AdMob")` as well but without any success

**Comment by akien-mga** [comment]
Well I'd suggest to open a bug report on https://github.com/kloder-games/godot-admob directly asking for Godot 3.0 support. Apparently the Android part still builds, but the iOS part definitely won't (as you mentioned `register_types.cpp` references headers which no longer exist), so I wouldn't presume that the Android part would *work*.

**Comment by Kopfenheim** [comment]
Hmm, I guess so. I will open a bug report about it there.

As an aside, do you know of any android based modules that do work with Godot 3.0 by any chance? Because I mainly develop for Android and I really wanna see if I can switch over my workflow to Godot 3.0. 

Thanks

**Comment by eon-s** [comment]
Try this one https://github.com/FrogSquare/GodotFireBase, looks better maintained and mentions Godot 3 support, may fail on RC1 without fixes, report there any issues you find so it get fixed or result in a new bug of Godot 3.

**Comment by Kopfenheim** [comment]
Thanks a lot. I tried out the Firebase module and it worked!

I also kept digging into the AdMob module that I had been using. It turns out that while initializing the admob object I was using `get_instance_ID()` but Godot 3.0 seems to have changed it to all lower case letters `get_instance_id()`. The AdMob module also works now after making that change and using `Engine` to manage the singletons.

**Comment by jonglae** [comment]
Unforunately ddddd has stopped

**Comment by akien-mga** [comment]
> Unforunately ddddd has stopped

Poor dddddd.
