### ISSUE TITLE
Line highlighting doesn't go all the way if there is more characters to the right

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15732]
**Godot version:**
0a691bf

**Issue description:**
Self-explanatory:
![](https://user-images.githubusercontent.com/30739239/34918974-792a28e0-f943-11e7-98d3-3b4bc1eb416a.gif)

**Comment by binbitten** [comment]
This also happens for selections (both left and right)
![before_mod](https://user-images.githubusercontent.com/685718/35642530-b2d28d20-06c3-11e8-9c61-c19bd339dfd9.gif)

I can modify it a bit, like:
![after_mod](https://user-images.githubusercontent.com/685718/35642562-c146e4e6-06c3-11e8-94b0-ad8f95a72939.gif)

Is this wanted?

**Comment by reduz** [comment]
@Paulb23

**Comment by KoBeWi** [comment]
Still valid in 494bf38
