### ISSUE TITLE
Realtime/direct light from emissive materials

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#15749]
**Godot version:**
109242c

**OS/device including version:**
Debian GNU/Linux 9.3

**Issue description:**
As discussed in #15727, having realtime emissive materials would allow some flexibility and useful applications. @reduz [mentions](https://github.com/godotengine/godot/issues/15727#issuecomment-357581084) that with GIProbe, this should be possible.

**Steps to reproduce:**

**Comment by reduz** [comment]
keep it open, but it's not a priority for me right now

**Comment by Zireael07** [comment]
Tangent: would it be possible to have emissive materials contribute to baked lightmaps?

**Comment by reduz** [comment]
@Zireael07 that is already working

**Comment by Zireael07** [comment]
Doesn't look like it when I tried it in rc 1.

**Comment by reduz** [comment]
open issue if not already open, i remember testing this a while ago and it worked fine

**Comment by seadra** [comment]
> Tangent: would it be possible to have emissive materials contribute to baked lightmaps?

I just tested with 109242c and it does seem to be working for me.

> keep it open, but it's not a priority for me right now

Sure, you did mention 3.0 is the priority so, you know, just so there's an issue for the future.

**Comment by bojidar-bg** [comment]
Is this still valid on master?

**Comment by seadra** [comment]
Yes

**Comment by Calinou** [comment]
This is now implemented in the [`vulkan`](https://github.com/godotengine/godot/tree/vulkan) branch, closing.
