### ISSUE TITLE
Casting ray from C# code results in deferred crash

### ISSUE THREAD

**Issue by crym0nster** [godotengine/godot#15746]
**Godot version:**
3.0 RC1

**OS/device including version:**
Arch Linux, Linux Mint, Windows 7

**Issue description:**
Casting a ray from C# code results in crash in about 5 minutes. Don't know exactly what setup causes this(tried just a box shape and ray from code - that was ok), example project consists of simple mesh and simple kinematic character, ray casts from character position into the ground.
It did also crash before RC1(e49ddf298403ae80977e9811bab6ef39f0ea226b) and crash log was different from RC1. Both logs in attachments.
Casting ray from gdscript is okay and using raycast node is okay too.

**Steps to reproduce:**
In the example project click right mouse button. It will cause raycast to the ground and hit point will appear in console. Then wait about 5 minutes and it should crash

**Minimal reproduction project:**
[test_raycast.zip](https://github.com/godotengine/godot/files/1632006/test_raycast.zip)
[pre-RC1-log.txt](https://github.com/godotengine/godot/files/1632016/pre-RC1-log.txt)
[RC1-log.txt](https://github.com/godotengine/godot/files/1632017/RC1-log.txt)

**Comment by akien-mga** [comment]
Related to #15144.

**Comment by kakoeimon** [comment]
@akien-mga This is indeed related to #15144 and I thing that you can close it.
