### ISSUE TITLE
Crash when trying to access C# exported var from a visual script

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#15745]
**Godot version:** `master` / 05b1843

**OS/device including version:** *Linux Mint 18.2 + Cinnamon 3.4.6*, *Mono 5.4.1.6*

**Issue description:**
I'm not sure this should already work.

Godot crashes when trying to access a C# `[Export]` variable from VisualScript.
![godotcrash](https://user-images.githubusercontent.com/437025/34945427-a1398a18-fa03-11e7-8ae4-e0065f3e4d27.gif)
Here is the full stack trace : [stacktrace.txt](https://github.com/godotengine/godot/files/1631842/stacktrace.txt)
This happens whether the mono project has been built.

**Steps to reproduce:**
* Create a project with mono support
* Create a scene
  * Add a node and attach a C# script to it
    * `[Export]` a var (e.g. `public String foo = "bar";`)
  * Add a node and attach a VisualScript to it
    * Create a `VisualScriptPropertyGet`
      * Set its mode to `Node Path`
      * Set its node path to the C# node
      * Try to select a property

**Minimal reproduction project:**
[bug_csharp_visualscript.zip](https://github.com/godotengine/godot/files/1631807/bug_csharp_visualscript.zip)

**Comment by akien-mga** [comment]
CC @neikeq
