### ISSUE TITLE
Physics regression - scaling objects with static body makes the collisions not work

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#15747]
**Godot version:**
3.0 rc 1

**OS/device including version:**
Win 7 x64

**Issue description:**
I spotted this issue while investigating something else...

**Steps to reproduce:**
Default physics engine.
Load attached project, try to drive through big building. Success.
Now try to drive through smaller one. Nope.

The only difference is that the big one is scaled (2,2,2) and the small one isn't. Both collision shapes are the same (convex) and created the same way (button in editor).

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/1632115/test.zip)

**Comment by jedStevens** [comment]
Aren't physics objects supposed not to have scaling?

**Comment by Zireael07** [comment]
I am scaling the parent spatial, not the collision itself.

**Comment by Zylann** [comment]
@Zireael07 since scaling parent spatial also scales children I would assume this will have the same effect as scaling the collision directly...
However, wasn't there a discussion about the possibility to scale physics shapes *uniformly*? How did it end?

**Comment by Zireael07** [comment]
This works in beta 1 and 2, though - I can collide with scale (2,2,2) buildings fine. I don't mind a change, but I was very surprised and initially thought it was some other problem.

Also I created the shapes after scaling and they show fine in editor and in the 'show collisions' mode, so I was really stumped on the issue.

Maybe have a debug message or a big <!> warning (like the one when the collision shape has a bad parent) that the collision shape is scaled and will not be functional?

**Comment by dynamite-ready** [comment]
I also have a project where collisions were fine in 3.0.0 beta 1 and 2, but are now broken in this release.
The hitboxes look fine with the show collisions property switched on for me too.

I'm guessing it's related to this bug - https://github.com/godotengine/godot/issues/15695

Going to try reverting my build back to one of the earlier betas.

**Comment by hakro** [comment]
I'm having a similar problem.
I made a brick scene with a 3D static body parent, and box collision shape.
I imported it into another scene and resized the box, but the collision shape was not working correctly, even if it's scale is 1,1,1, relatively to it's parent static body.

**Comment by akien-mga** [comment]
Might also be a regression/an existing bug exposed by #15606, cc @RandomShaper.

**Comment by RandomShaper** [comment]
My suggestion is to test all these kind of issues on both Godot Physics and Bullet, and compare.
Godot Physics can serve as a reference implementation of the PhysicsServer so it helps telling where the bug is exactly.

**Comment by brodiefairhall** [comment]
In Beta2, if I had a StaticBody with a MeshInstance and a CollisionShape (both just cubes), both of which are set at default scale. I could scale the StaticBody and both the children would scale with it. In RC1, the CollisionShape seems to have a completely default transform (located at 0,0,0 with 0,0,0 rotation and 1,1,1 for scale), relative to the parent. The collision shape is shown in the editor as the size of the scaled parent, but, when the project is run the collision area just ends up being a 1x1x1 cube in the centre of the parent.

**Comment by brodiefairhall** [comment]
This is a demo project I whipped up.
2 Spherical RigidBodies (Balls) falling onto a floor. 
In Beta2 both balls stop on the floor, in RC1, the ball in the centre stops falling and the other ball falls straight through.

[https://www.dropbox.com/s/uuruiy2x0yddkvh/CollideProblem.zip?dl=0](url)

**Comment by AndreaCatania** [comment]
Can you please check it again with this PR: #15777?
