### ISSUE TITLE
RC1 Mono crash on opening a Godot 3 Beta 2 project.

### ISSUE THREAD

**Issue by dunyakilavuz** [godotengine/godot#15748]
I was trying to edit a 3 Beta 2 project with the newest RC1 build, and got this command line snippet as error. Problem is I can still open/edit the project with the 3 Beta 2 build, so I'm sure the new RC1 build introduces this error. Pasting whole text;

`C:\Users\Dunya>C:\Users\Dunya\Desktop\Godot_v3.0-rc1_mono_win64\Godot_v3.0-rc1_mono_win64.exe
OpenGL ES 3.0 Renderer: GeForce GTX 1080/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
Mono: Initializing module...
Mono: Runtime initialized
Mono: INITIALIZED
OPENING: C:/Users/Dunya/Desktop/SolarX-Godot (C:::Users::Dunya::Desktop::SolarX-Godot)
running cmdline: "C:\Users\Dunya\Desktop\Godot_v3.0-rc1_mono_win64\Godot_v3.0-rc1_mono_win64.exe" "--path" "C:/Users/Dunya/Desktop/SolarX-Godot" "--editor"
Mono: Runtime cleanup...
debugger-agent: Unable to listen on 1656
OpenGL ES 3.0 Renderer: GeForce GTX 1080/PCIe/SSE2

C:\Users\Dunya>GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
Mono: Initializing module...
Mono: Runtime initialized
ERROR: Mono Cache: Member GDMonoUtils::mono_cache.class_DebuggingUtils is null
   At: modules\mono\mono_gd\gd_mono_utils.cpp:197
Mono: INITIALIZED
ERROR: GDMonoClass::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_class.cpp:95
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
ERROR: GDMonoMethod::has_attribute: Parameter ' p_attr_class ' is null.
   At: modules\mono\mono_gd\gd_mono_method.cpp:158
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] BaseThreadInitThunk
-- END OF BACKTRACE --`

**Comment by eon-s** [comment]
Have you done this:
`
Another caveat for users of 3.0 beta 2 with Mono: you might need to delete the mono folder of your Godot user folder, as well as the .mono folder in your project, to remove now-incompatible assemblies.`

Mentioned in the announcement?
https://godotengine.org/article/dev-snapshot-godot-3-0-rc-1

**Comment by dunyakilavuz** [comment]
> @eon-s deleting the .mono folder in the project solves the issue, thanks for speedy reply!
