### ISSUE TITLE
Godot hangs on quit

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#15754]
Godot consistently hangs with high CPU usage after quitting the editor on some projects. [This demo][blaster-faster] in particular reliably triggers this on my computer.

[stdout.txt](https://github.com/godotengine/godot/files/1632724/stdout.txt)
[stacks.txt](https://github.com/godotengine/godot/files/1632725/stacks.txt)
[strace.txt](https://github.com/godotengine/godot/files/1632728/strace.txt)

**Godot version:**
3.0.rc1

[blaster-faster]: https://github.com/letheed/blaster-faster/

**Comment by letheed** [comment]
Not sure why it loops exactly. But if I try to debug it seems that

```c++
111		_FORCE_INLINE_ ~List() { ERR_FAIL_COND(_first != NULL); }
```

fails in self_list.h because `_first` isn't null actually. So `ERR_FAIL_CON` calls `_err_print_error` in error_macros.cpp and

```c++
84		OS::get_singleton()->print_error(p_function, p_file, p_line, p_error, _err_error_exists ? OS::get_singleton()->get_last_error() : "", (Logger::ErrorType)p_type);
```

segfaults because `singleton` is already NULL at this point.

**Comment by mhilbrunner** [comment]
>Godot version:
3.0.rc1

Why would you use that instead of 3.0/3.0.2? Or do you mean the 3.0.3 RC?

**Comment by letheed** [comment]
Sorry that's an old issue. I'm using the 3.0.2 stable.

**Comment by mhilbrunner** [comment]
Ah, I missed the original date. Makes sense.

**Comment by metalim** [comment]
PING!
Version 3.1.1 on macOS - still same issue.

**Comment by Ark2000** [comment]
I meet this problem in 3.2.2 (windows x64) which I have never  met in 3.2.1

**Comment by akien-mga** [comment]
@Ark2000 Please open a new issue with details on what you experience exactly, it's unlikely the be the same cause as a 2018 bug.

I'll close this bug as it's quite old and we've been fixing various issues around the `List` deconstructor which was causing these errors.
