### ISSUE TITLE
Inconsistent fullscreen behavior on Linux when using multiple monitors

### ISSUE THREAD

**Issue by Chainsawkitten** [godotengine/godot#15750]
**Godot version:**
2.1.4 (Custom build) 9a98f3b71c28e39fa021b43782c853c61964636a

**OS/device including version:**
Running on Ubuntu 17.10 64bit.
Compiled on Debian using Clang.

**Issue description:**
Fullscreen works differently in regards to multiple monitors depending on whether it's enabled in the project settings or through script via: `OS.set_window_fullscreen()`.

When running on Ubuntu 17.10, enabling fullscreen in the project settings and using multiple monitors the game stretches across both monitors.

When starting in windowed and then enabling fullscreen through script, the game is fullscreen in the primary monitor (as I believe is the intended behavior).

Doing
```
OS.set_window_fullscreen(false)
OS.set_window_fullscreen(true)
```
will change to the normal behavior, even if it was at first stretched across both monitors.

This applies to Ubuntu 17.10. In Ubuntu 16.04 (LTS) (and Windows) the game is fullscreen only in the primary monitor.

17.10 switched to Wayland, so this may be a difference between running in X11 and XWayland.

Both Ubuntu 17.10 and Ubuntu 16.04 are running in a VM. Steam was installed. Otherwise no packages that didn't come with the OS were installed.

**Steps to reproduce:**
1. Enable Fullscreen under Project Settings->Display.
2. Leave Fullscreen off but do `OS.set_window_fullscreen(true)` in any `_ready()` method.
3. Run both versions on Ubuntu 17.10 (or any linux-distro using Wayland?) when using multiple monitors.

**Comment by brainsick** [comment]
I can confirm this behavior on Ubuntu 17.10 x64 and Godot 3.0 RC2.

I am not currently running Wayland though.
```
todd@todd-ab28d3:~$ loginctl
   SESSION        UID USER             SEAT             TTY             
        c2        121 gdm              seat0            /dev/tty1       
         3       1000 todd             seat0            /dev/tty2       

2 sessions listed.
todd@todd-ab28d3:~$ loginctl show-session 3 -p Type
Type=x11
```

**Comment by Web-eWorks** [comment]
Can someone confirm this still happens? Please also confirm if this happens when running a normal instance with the `-f` command-line flag.

**Comment by Anutrix** [comment]
Is version 2.x branch still supported?

**Comment by Calinou** [comment]
@Anutrix Yes, but we only intend to fix critical issues such as security bugs and platform support.
