### ISSUE TITLE
Node warning icon is hardly visible

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15757]
Godot 3.0 RC1

When a node has a warning to show, its icon is very hard to distinguish due to wrong color contrast:

![image](https://user-images.githubusercontent.com/1311555/34959588-78e154f4-fa37-11e7-80f3-47b207e72b00.png)

**Comment by groud** [comment]
I noticed that recently, mine is blue but also hardly visible.

**Comment by Zylann** [comment]
Note: I was using a orange-ish theme just before, might be why mine is reddish, which could mean that the icon also didn't change when I switched back to blue theme.

**Comment by robfram** [comment]
I have high constrast warning icons using v3.0.rc1.1968cc4 without custom themes nor any other personalization. Maybe it is something related to custom themes.

![output](https://user-images.githubusercontent.com/35065795/35016049-4a9cba08-fb17-11e7-9013-7db793649d66.png)

**Comment by akien-mga** [comment]
CC @djrm @volzhs - probably related to setting the initial values of the relevant EditorSettings.
