### ISSUE TITLE
Hex field in color picker sets the wrong component

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#15759]
Alpha sets blue, blue sets green, green sets red, red sets alpha.

![picker](https://user-images.githubusercontent.com/5330692/34961614-4c9563b4-fa40-11e7-97b1-77c70db43c09.gif)

**Comment by vnen** [comment]
Might be a regression from #15540.

**Comment by letheed** [comment]
I'm guessing the parsing code should have been updated as well.

**Comment by vnen** [comment]
CC @robfram 

The default Color constructor expects ARGB (has been like so for ages). Changing it would be a breaking change and I think we're a bit past that stage now.

**Comment by robfram** [comment]
Sorry. I think I tested it typing the hex color code and it worked. It
seems I didn't notice it failed, as I was testing the bug of screen color
picking.

The merge should be reverted then, although I think it is very strange to
use ARGB for hex. Neither GIMP, Inkscape, Blender nor HTML uses hex colors
this way. Actually, I think I never had sawn hex using ARGB before.
