### ISSUE TITLE
Text alignments in Label not working properly.

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#15758]
align=center, valign=top (seems ~ok):
![valign top](https://user-images.githubusercontent.com/5330692/34959532-393494ba-fa37-11e7-86f4-ba0c4b61da11.png)

align=fill, valign=top:
![halign fill](https://user-images.githubusercontent.com/5330692/34959481-fd37ec6e-fa36-11e7-900f-f8217bf458bf.png)

align=center, valign=fill:
![valign fill](https://user-images.githubusercontent.com/5330692/34959652-b73f8e28-fa37-11e7-993a-21eb6a5107fb.png)

align=center, valign=center:
![valign center](https://user-images.githubusercontent.com/5330692/34959665-c7947acc-fa37-11e7-975e-937083fe1ab0.png)

align=center, valign=bottom:
![valign bottom](https://user-images.githubusercontent.com/5330692/34959667-cb91b77a-fa37-11e7-84e4-3fce97c281f6.png)

Stylebox has 8,8,3,3 content margins.
Godot 3.0 rc1

**Comment by akien-mga** [comment]
Thanks, closing.
