### ISSUE TITLE
RayCasts are blocked by Areas even when area collider is set to disabled

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#15764]
**Godot version:**
Godot RC1

**OS/device including version:**
windows 10 x64

**Issue description:**
even when a Area's collider is disabled Raycasts still seem to be blocked by said area.

**Steps to reproduce:**
fire a raycast towards an area with the areas collider set to disabled.

**Minimal reproduction project:**

**Comment by AndreaCatania** [comment]
Can you please update a sample project?

**Comment by vonflyhighace2** [comment]
[Debug samples.zip](https://github.com/godotengine/godot/files/1671829/Debug.samples.zip)
This is a sample tat I can recreate the bug in. sorry for the long delay.

**Comment by vonflyhighace2** [comment]
I can't seem to reproduce this issue in the current stable version of the engine. It was the release candidate that had it. Looks like it was fixed. Can close this thread I guess.
