### ISSUE TITLE
TileMap with NavigationPolygons returns incorrect path after exiting and re-entering tree.

### ISSUE THREAD

**Issue by authenticate** [godotengine/godot#15767]
**Godot version:**

2.1.4

(Note: Others, in the forum post below, have described the issue in 3.0 as well.  However, I have only tested against 2.1.4.)

**OS/device including version:**

Windows 10 x64

**Issue description:**

When a TileMap containing NavigationPolygons exits and re-enters the tree, the Navigation node's 'get_simple_path' function always returns an incorrect path.  It is as if the TileMap's NavigationPolygons become corrupted or are not fully re-initialized.  The Navigation, TileMap, and NavigationPolygon nodes work correctly prior to exiting and re-entering.

Please see the following forum thread for the full description:

https://godotengine.org/qa/22144/tilemap-navigation-breaks-when-reparent-navigation2d-node

As a side note, this issue seems very similar to the following:

https://github.com/godotengine/godot/issues/11077

However, the reproduction steps are slightly different.

**Minimal reproduction project:**

https://github.com/Gromhunter/navigation_test

Thank you.

**Comment by blurymind** [comment]
@MarianoGnu @damarindra  :)

**Comment by damarindra** [comment]
Anyway, why tagging me? 🤣  Personally, I never use both navigation and occlusion. So, I'm not gonna work on this anytime soon.

**Comment by bojidar-bg** [comment]
Fixed by #15909.
