### ISSUE TITLE
Project manager menu takes game pad input

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#15765]
**Godot version:**
Godot RC1

**OS/device including version:**
\windows 10 x64

**Issue description:**
while on the Project manager menu if you select the run button it remains in focus/selected causing any further input from the game pad to be send to the Project manager.

**Steps to reproduce:**
the run button should be deselected/ lose focus after each press.

**Minimal reproduction project:**

**Comment by BeayemX** [comment]
Duplicate of #15199
