### ISSUE TITLE
Resource path autocomplete fails for preload

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#15766]
When typing a path in `preload()`, the console is flooded with "No loader found for resource: res://".
`load()` works as expected.

**Comment by YeldhamDev** [comment]
With the reversion of  #15849, this should be reopened I suppose.

**Comment by reduz** [comment]
Status of this?

**Comment by YeldhamDev** [comment]
@reduz Can't reproduce the error spamming in `master`, but I noticed a different issue: It doesn't autocomplete with possible paths like `load` does.

**Comment by KoBeWi** [comment]
The autocomplete seems to work until you make a mistake.
https://gfycat.com/MeekEvilAmurstarfish

**Comment by dreamsComeTrue** [comment]
well, It "kinda" works - when you make a mistake, then, backspace all characters from argument's string and then Ctrl + Space - it will show list of resources indeed.
But I assume - it should work on every backspace-gradually-removing-characters keystroke, not only with empty argument while triggering autcomplete by hand?

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

**Comment by HolonProduction** [comment]
Can't reproduce in v3.6.stable.official [de2f0f147]
