### ISSUE TITLE
ERROR: AudioServer::set_bus_volume_db: Index p_bus=-1 out of size

### ISSUE THREAD

**Issue by yanorax** [godotengine/godot#15771]
**Godot version:**
3.0 Beta 2 32bit and 3.0 RC 1 32bit.

**OS/device including version:**
Windows 7 x64

**Issue description:**
I have a project where there are two separate audio buses for sound effects and music.

If I export the project to a 32bit or 64bit Windows Desktop exe, I can adjust the volume of each bus without any problems. Running inside the editor is also OK.

However if I enable _Convert Text Resources To Binary On Export_ in the project settings and export, I get the following error in the debug window when I try and change the volume:
 
ERROR: AudioServer::set_bus_volume_db: Index p_bus=-1 out of size (buses.size()=1)
	At: servers\audio_server.cpp 663 

**Steps to reproduce:**
Open the attached project in Godot 3.0 Beta 2 or RC1, enable _Convert Text Resources To Binary On Export_ in the project settings. Export to Windows Desktop 32 or 64 bit with Debug. Run the exe and move the sliders. 

**Minimal reproduction project:**

[VolumeTest.zip](https://github.com/godotengine/godot/files/1634243/VolumeTest.zip)

**Comment by yanorax** [comment]
As a workaround you can load the bus layout manually in your script by using `AudioServer.set_bus_layout(load("res://my_bus_layout.tres"))` and it will allow you to change volume for multiple buses in game again.

**Comment by Faless** [comment]
I can confirm this issue.
The problem is that the check to see if the default bus layout exists is done via `FileAccess::exists("res://default_bus_layout.tres")` which does not take into account remapping.

https://github.com/godotengine/godot/blob/9ce8d8ddda35cda781364e9b648325a2953d3f63/servers/audio_server.cpp#L919-L927
