### ISSUE TITLE
Can't select .pck outside of project folder to create patches

### ISSUE THREAD

**Issue by vybr** [godotengine/godot#15776]
**Godot version:**
Godot 3 RC1

**Issue description:**
Not sure if this is intentional. But you are unable to select a .pck file outside of the project filesystem (res://) when creating a patch in the export menu.

**Comment by Phoenix1747** [comment]
Still have this problem with 3.0.2-stable. It's not critical, however, it would be a pretty nice enhancement!

**Comment by Calinou** [comment]
[The patch PCK creation functionality hasn't been implemented yet and was therefore hidden in 3.2.](https://github.com/godotengine/godot/pull/34911) This feature would have to be implemented again before this proposal can be considered :slightly_smiling_face:
