### ISSUE TITLE
False and misleading project creation process.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15775]
**Issue description:**

**Steps to reproduce:**
<img width="513" alt="ekran resmi 2018-01-16 13 08 27" src="https://user-images.githubusercontent.com/33985414/34984121-d2d914ae-fac0-11e7-8db4-3536cccbe4ec.png">

1. When I press the " Create & Edit"  accidentally, Godot is trying to import the entire home directory

![orho2](https://user-images.githubusercontent.com/33985414/34984164-f3dcd87a-fac0-11e7-89e2-900c31655f4a.gif)
<img width="699" alt="ekran resmi 2018-01-16 13 06 24" src="https://user-images.githubusercontent.com/33985414/34985198-5d250246-fac4-11e7-92c4-c7872ac313e5.png">

2. At this point the program is not responding. You have to do a "Force Quit" (on macOS).

Why is not the project folder being created automatically? The project creation process makes me Cancer.

**Comment by akien-mga** [comment]
The dialog should not allow creating projects in a non-empty folder.

**Comment by icnikerazah** [comment]
@akien-mga 
> The dialog should not allow creating projects in a non-empty folder.

This is not enough. "Create Folder" is unnecessary. New folder simply should be auto-generated.

**Comment by bruvzg** [comment]
It would be better to have `Create Folder` checkbox (selected by default) instead of button and additional confirmation dialog to create project in a non-empty folder. Warnings hidden under exclamation mark icon are completely useless, no one will notice them.

![project](https://user-images.githubusercontent.com/7645683/34988480-88709296-fac7-11e7-93c5-043e57a70e88.png)

**Comment by icnikerazah** [comment]
default path should be user/home/documents/Godot Projects. this is standart path on every OS

**Comment by eon-s** [comment]
@akien-mga sometimes I want to create a project on a directory with assets, scenes, etc.

**Comment by icnikerazah** [comment]
User friendly welcome

![newproject](https://user-images.githubusercontent.com/33985414/34995130-a312232a-fae6-11e7-8871-7ebc975d0d55.png)

In Project settings

![default](https://user-images.githubusercontent.com/33985414/34995186-c40123f6-fae6-11e7-964b-ae53584662a6.png)

**Comment by icnikerazah** [comment]
@ground Behavior trying to import the whole system. this is definitely a bug.

**Comment by Zireael07** [comment]
I think Godot should detect if you've selected the home directory and prevent creating the project.

**Comment by icnikerazah** [comment]
> Don't know about Godot Projects. I really hate when apps add random folders on their own, at least it shouldn't be create before user try to actually create new project in it.

In that case setting the default project folder should be more easily accessible.(inside dialog panel).
 I hate to make too much effort for a simple operation.

**Comment by eon-s** [comment]
Default project folder is in editor settings, where is the default value for that?

**Comment by icnikerazah** [comment]
default value is home directory

**Comment by bruvzg** [comment]
> In that case setting the default project folder should be more easily accessible.

Would be nice to have access to `Editor Settings` and `Manage Export Templates` without opening a project, or maybe add some sort of "First Start Wizard" with options to select things like interface language, theme, key binding preset and default project path, import settings from previous version, add file type associations, join the [Godot Customer Experience Improvement Program™](https://github.com/godotengine/godot/issues/15602), etc.

**Comment by eon-s** [comment]
There was an issue with a new project manager proposal, no idea if somebody is still working on it.

**Comment by bruvzg** [comment]
> There was an issue with a new project manager proposal

https://github.com/godotengine/godot/issues/8135

**Comment by akien-mga** [comment]
> The dialog should not allow creating projects in a non-empty folder.

Can someone implement this (and only this) for 3.0?

I agree that it's not enough and even not desirable in all use cases, but we don't have time to do more involved refactorings at this stage. For 3.1, the dialog could be redone to be like https://github.com/godotengine/godot/issues/15775#issuecomment-357986284

**Comment by puppetmaster-** [comment]
I would also welcome a tab where you can make some important/main editor settings.
![image](https://user-images.githubusercontent.com/10463138/35095939-a3bb9558-fc4a-11e7-9769-fde606260e25.png)
![image](https://user-images.githubusercontent.com/10463138/35095954-b7831f70-fc4a-11e7-92fe-524590ff1233.png)

**Comment by eon-s** [comment]
Can't default project path point to user document folder instead of home?, maybe in a godot subdir (created like editor_data).

**Comment by akien-mga** [comment]
The critical "bug" part of this issue (it was too easy to import your whole $HOME by mistake) is fixed by #15835 - the rest of the discussion to improve the UX is still valid, but will be 3.1 material.

**Comment by puppetmaster-** [comment]
@vnen I don't like it so much when you see _all_ settings there, just because of the clarity, but _all_ settings are better than _no_ settings. :)

**Comment by egel-lang** [comment]
This happened to me on a Linux system too. I just followed the install and went with all the default parameters, subsequently it imported my home directory in res:// and recursively added .import files in my entire home directory. Please fix this for new users.

**Comment by icnikerazah** [comment]
@egel-lang 

akien-mga:
> The critical "bug" part of this issue (it was too easy to import your whole $HOME by mistake) is fixed by #15835 - the rest of the discussion to improve the UX is still valid, but will be 3.1 material.

**Comment by akien-mga** [comment]
> This happened to me on a Linux system too. I just followed the install and went with all the default parameters, subsequently it imported my home directory in res:// and recursively added .import files in my entire home directory.

With what version? It should be fixed in 3.0 RC2 released on Saturday.

**Comment by icnikerazah** [comment]
Ok sorry
