### ISSUE TITLE
DynamicFont occasionally broken with oversampling enabled

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#15787]
**Godot Version**: 3 RC1

**Windows Version**: Windows 10 64-bit

**Windowed**:
![windowed](https://user-images.githubusercontent.com/12462089/35002323-e2cef922-fb1b-11e7-864f-5990c21d4a70.png)

**Fullscreen**:
![fullscreen](https://user-images.githubusercontent.com/12462089/35002325-e63d5fa4-fb1b-11e7-82e1-19a252d8bed3.png)

**Error Message**:
```
0:00:10:0897 - Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
----------
Type:Error
Description: 
Time: 0:00:10:0897
C Error: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
C Source: c:\projects\godot-builds\godot\core\rid.h:165
C Function: RID_Owner<struct RasterizerStorageGLES3::Texture>::getornull
```

**Comment by reduz** [comment]
Thanks for the report!
However, I would appreciate you follow the guidelines and provide an
example project.

**Comment by DleanJeans** [comment]
I've attempted to replicate the bug in a minimum project couple of times but failed miserably.
Anyway, I stripped down my current project to a minimum of just UIs.

[OversamplingBug.zip](https://github.com/godotengine/godot/files/1638090/OversamplingBug.zip)

**Comment by NykolaR** [comment]
Am also getting the same visual glitches with dynamic font + oversampling. Will try to see if I can pinpoint the cause and make a minimal project later this week when I'm not on any deadlines.
