### ISSUE TITLE
Feature request: Ability to open project folder

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15788]
on macOS (or windows,linux)

Ability to open project folder  in Terminal on macOS;

`$ open -a Godot /Users/razah/Desktop/My\ Project\ Folder`

Ability to open project folder with Godot executable flag;

`$ Godot --folder /Users/razah/Desktop/My\ Project\ Folder`

Ability to open project folder by dragging and dropping on Application icon

![dragdrop](https://user-images.githubusercontent.com/33985414/35005986-5c5e2788-fb06-11e7-8d8b-fcbc595df4f1.gif)

If I had this feature, I do not think I would use the project manager.

https://github.com/godotengine/godot/issues/15775
https://github.com/godotengine/godot/issues/8135

**Comment by vnen** [comment]
> `$ Godot --folder /Users/razah/Desktop/My\ Project\ Folder`

It's possible to that with:

`$ Godot -e --path /Users/razah/Desktop/My\ Project\ Folder`

`-e` says to open the editor.

> `$ open -a Godot /Users/razah/Desktop/My\ Project\ Folder`

Don't know how `open` works on macOS, but if you give a path the `project.godot` file direclty it will open the editor. Essentially:

`$ Godot /Users/razah/Desktop/My\ Project\ Folder/project.godot`

At least on Windows you can drag and drop the `project.godot` file over the executable and it'll open the editor. Or double-click the project file if the association is already made.

**Comment by bruvzg** [comment]
It is possible to pass args to open: `open -a Godot --args -e --path /Users/razah/Desktop/My\ Project\ Folder`
And you can drag and drop the `project.godot` over dock icon.
