### ISSUE TITLE
Strange error message when using a node of the wrong type with a C# script

### ISSUE THREAD

**Issue by redxdev** [godotengine/godot#15789]
**Godot version:**
14b230f

**OS/device including version:**
Windows 10

**Issue description:**
When a C# script is put on a node of the wrong type (let's say the C# script inherits `AnimatedSprite` but the node is just a `Node`) and the project is run, instead of getting an appropriate error you end up with this in the debugger (nothing appears in the right panel):

![debugger](https://i.imgur.com/8zdWTfC.png)

and the following error in the command prompt:

    ERROR: No loader found for resource: res://
    At: core\io\resource_loader.cpp:186

While using the wrong type of node with a script should probably be an error, there should probably be a specific error message for it. As it is right now, it looks like this specific case isn't handled for C#.

If I try to replicate the same situation using gdscript, I end up with an error that makes much more sense:

    Script inherits from native type 'AnimatedSprite', so it can't be instanced in object of type: 'Node'

It looks like this case just isn't being handled for C# (or it is being handled incorrectly).

**Minimal reproduction project:**

[TestProject.zip](https://github.com/godotengine/godot/files/1636469/TestProject.zip)

**Comment by NathanWarden** [comment]
I've done this also a few times and didn't realize what I had done and thought my build Godot was broken. This would be pretty handy to have a more useful error message :)

**Comment by paulloz** [comment]
Seems that's [the only place](https://github.com/godotengine/godot/blob/master/modules/mono/csharp_script.cpp#L1957) we're calling the `ScriptDebugger` from `CSharpLanguage`.  
It's looping indefinitely in the debug method and the proper error can't be shown.

**Comment by Sourgin** [comment]
This was my problem, had a //nameme : notANode//script inside a 'node', changed ": notANode" -> ": node" fixed the error.

**Comment by Calinou** [comment]
@redxdev Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by redxdev** [comment]
@Calinou looks like this has indeed been fixed, closing.

![image](https://user-images.githubusercontent.com/472625/83996390-e254ca80-a910-11ea-9437-7c4f8632dc02.png)
