### ISSUE TITLE
Fix tooltip for Anchor values in Control node

### ISSUE THREAD

**Issue by khinbaptista** [godotengine/godot#15783]
**Godot version:**
3.0 rc

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Anchor values in inspector show outdated tooltip, mentioning the ANCHOR_* constants.

![image](https://user-images.githubusercontent.com/7837147/34997026-782397f8-fac2-11e7-8970-31311d20604d.png)

**Comment by KoBeWi** [comment]
The tooltip was updated in #31119

It was actually correct btw. These constants exist, but the description now includes a proper link to the enum, so it's clear what to use (although it's not useful in the inspector).
