### ISSUE TITLE
GLTF2 Import Issue - Visual Overlap

### ISSUE THREAD

**Issue by brainsick** [godotengine/godot#15798]
**Godot version:**
Godot 3.0 RC1

**OS/device including version:**
Ubuntu 17.10 x64, AMD Radeon R9 Fury

**Issue description:**
I'm trying to import the GLTF2 download of [phoenix bird](https://sketchfab.com/models/844ba0cf144a413ea92c779f18912042) into Godot.

~~Once the import completes, Godot displays a red sick face as an icon for the scene.gltf file.  Hovering over it reports:~~

~~Status: Import of file failed.  Please fix file and reimport manually.~~

~~The console shows no messages that would indicate an error occurred.  Indeed, the scene can be opened.~~  I can no longer recreate this.

That said, the scene has some obvious issues.

![screenshot from 2018-01-16 21-21-04](https://user-images.githubusercontent.com/1111573/35024066-3143d26c-fb03-11e7-9681-c2d2d5fc13a1.png)

Note: the Scene Root has been scaled to 0.05 for the screenshot.

I tested the same model with the another [viewer](https://gltf-viewer.donmccurdy.com/) and it works successfully.

~~Just to confuse things further, if you Reimport the scene, the red sick face goes away and no errors are reported.~~

**Steps to reproduce:**
Download GLTF2 version of phoenix bird and import into Godot.

**Minimal reproduction project:**
[PhoenixGLTFImport.zip](https://github.com/godotengine/godot/files/1637727/PhoenixGLTFImport.zip)

**Comment by brainsick** [comment]
I can no longer recreate the "red sick face", even with my reproduction project.  Aside from a system update and restart, nothing interesting changed.  Sigh.

The visual issues remain.

Just an observation, but if I modify the imported materials and uncheck Flags / Transparent that resolves the visual overlapping.

![screenshot from 2018-01-19 23-54-17](https://user-images.githubusercontent.com/1111573/35180355-3df38048-fd74-11e7-981b-80d80956c472.png)

**Comment by fire** [comment]
Seems to work. I scaled to 0.01 in the import settings. Then, used Depth Draw Mode Opaque Pre-Pass and enable transparency. 5b70ad9d34d2777e3abd0a13118442eb132aff70

![godot windows opt tools 64_2018-08-06_23-18-15](https://user-images.githubusercontent.com/32321/43757845-12b12da2-99cf-11e8-9c44-eea80e116cc9.png)
