### ISSUE TITLE
HTML5 Export Missing Textures

### ISSUE THREAD

**Issue by brainsick** [godotengine/godot#15792]
**Godot version:**
Godot 3.0 RC1

**OS/device including version:**
Ubuntu 17.10 x64, AMD Radeon R9 Fury

**Issue description:**
I've successfully imported [phoenix bird](https://sketchfab.com/models/844ba0cf144a413ea92c779f18912042) and assigned the textures in Godot.

I can see the textures in the Editor and when I Play the project locally:

![screenshot from 2018-01-16 14-26-57](https://user-images.githubusercontent.com/1111573/35011170-dbbcdfba-faca-11e7-8fab-eb588f3e3846.png)
![screenshot from 2018-01-16 14-27-57](https://user-images.githubusercontent.com/1111573/35011176-e1d1b966-faca-11e7-9e50-b046d6311609.png)

However, the textures aren't surviving the export to HTML5:

![screenshot from 2018-01-16 14-28-43](https://user-images.githubusercontent.com/1111573/35011193-edfd248c-faca-11e7-9fc2-baa60ce0ff8d.png)

In the Export dialog, on the Resources tab, the Export Mode: is set to Export all resources in this project.

Note that I tried building new HTML5 export templates from source but there was no difference.  Just in case this was some browser sandbox restriction, I tried to [host](https://drive.brainsick.com/godot/3dModelViewerHTML5Export/) it.  The camera can be rotated with middle mouse button + mouse move and zoomed with the mouse wheel.

**Steps to reproduce:**
Imported into Blender as FBX

Edited animation to end on last keyframe.
Delete light, camera

Exported to DAE via Collada Exporter:
\- Apply Modifiers
\- Selection Only
\- Include Children (disabled/grey)
\- Include Armatures (disabled/grey)
\+ Include Shape Keys (disabled/grey)
\- Only Selected UV Map
\- Include UV Textures
\- Include Material Textures
\- Copy
\- Deform Bones only
\- Export to SL/OpenSim
\+ Triangulate
\+ Use Object instances
\+ Use Blender Profile
Transformation Type: Matrix
\- Sort by Object name

Note that I tried to export this several dozen different ways with various utilities.  This got me the closest.

Glued up in Godot by:

Double click on fly.collada.dae and create a New Inherited scene.
Select AMesh_Ride_FengHuang_01 node
Drag generated MatI_Ride_FengHuang_01a.material to Material / 0
Edit SpatialMaterial
Enable Parameters / Use Alpha Scissors
Drag Tex_Ride_FengHuang_01a_D_A.tga.png to Albedo / Texture
Enable Emission / Enabled
Drag Tex_Ride_FengHuang_01a_E.tga.png to Emission / Texture
Drag generated MatI_Ride_FengHuang_01b.material to Material / 1
Edit SpatialMaterial
Enable Parameters / Use Alpha Scissors
Drag Tex_Ride_FengHuang_01b_D_A.tga.png to Albedo / Texture
Enable Emission / Enabled
Drag Tex_Ride_FengHuang_01b_E.tga.png to Emission / Texture

**Minimal reproduction project:**
[PhoenixBird.zip](https://github.com/godotengine/godot/files/1636718/PhoenixBird.zip)

**Comment by akien-mga** [comment]
CC @eska014 @reduz

**Comment by eska014** [comment]
GL ERROR :GL_INVALID_OPERATION : glDrawElements: uniform buffers : no buffer bound at index 4

This is the error, something wrong with OmniLight uniform buffer

**Comment by brainsick** [comment]
I just have to say that I am totally geeking out on this HTML5 export feature.  

On a lark, I loaded up the hosted link above on my phone.  Chrome 63 loads it up and plays as expected (sans textures).  This is the future!

Thanks for all the hard work @eska014, core team, and contributors.

PS, Firefox 57 didn't fare as well; it initialized but doesn't get past a black screen. If you would expect that to work, I can file a separate issue.

**Comment by reduz** [comment]
@brainsick I have the feeling part of the log regarding why the textures may be missing was not shown. Otherwise, can you check the HTML5 console to see if there is any error there?

**Comment by brainsick** [comment]
When eska014 posted the error I thought he had successfully recreated the issue.  I attached a sample project, does this not happen for you as well?

I've attached the console log in its entirety.  No errors.

[log.txt](https://github.com/godotengine/godot/files/1643192/log.txt)

There is nothing in the browser's console nor the Output window in the exported project.  There's a link above if you would like to check it out yourself.

![screenshot from 2018-01-18 08-46-33](https://user-images.githubusercontent.com/1111573/35103687-365edb8c-fc2c-11e7-9a02-28bd9b5a2b22.png)

**Comment by brainsick** [comment]
Just for grins, I wanted to clean up the visuals some.  I added a panorama sky and a bloom glow to the environment.  The panorama sky isn't showing up well in HTML5.  I don't know whether that's related; I can retest it later.

https://youtu.be/9NYABHYUsK0

**Comment by x1212** [comment]
I loaded the project and exported it with export-templates built from current master.
I get similar results when using anything other than "S 3tc" Texture Format in the export settings.
But in those cases with my own exports I get errors like this instead: "**ERROR**: At: core/io/resource_format_binary.cpp:360:parse_variant() - Couldn't load resource: res://phoenix/Tex_Ride_FengHuang_01b_E.tga.png"
![notextureformat](https://user-images.githubusercontent.com/1871877/35182378-f3e79484-fdd3-11e7-9e5d-364a10ae8b5e.png)

When using "S 3tc", everything works fine for me.
![s3tc_textureformat](https://user-images.githubusercontent.com/1871877/35182380-fa9c2e8e-fdd3-11e7-9710-3de661d4681b.png)

However the using the export from the first post, I get the same result as described.
![original](https://user-images.githubusercontent.com/1871877/35182390-2ea1070e-fdd4-11e7-8e3c-84059d81aeae.png)

So I guess maybe the default "TextureFormat" should be changed from "Etc" to "S 3tc"?
In case it is relevant, the emscripten version I used for my export templates is "1.37.22".

**Comment by reduz** [comment]
I guess default should be s3tc, yeah

**Comment by brainsick** [comment]
The adjusted export settings:

Texture Format:
S 3tc On
Etc Off
Etc 2 On

Does result in textures on the phoenix bird.  Thank you.

The color/brightness issue with the panorama remains.  I don't know if this is expected, but the glow bloom effect is also lost.

https://youtu.be/K6jgaD6ByDI
