### ISSUE TITLE
Change "Depth" in spatial materials to "Height/Depth" and attenuate input values.

### ISSUE THREAD

**Issue by leiget** [godotengine/godot#15794]
I've looked for an existing issue/request.

**Godot version:**
Godot custom 1968cc4

**Feature description:**
Change "Depth" to "Height" or "Height Map" in the spatial material and shader, and attenuate the input values so the effect isn't so extreme.

The reason I suggest this is because from what I've seen the phrase "height map" is much more prevalent than "depth map". This may be because things like bricks and stone are extremely frequent in games.

Another reason being that it is confusing for a first timer to Godot depth maps that a positive value means that something is depressing into the surface. It would be more intuitive to have positive values make things pop out of a surface, and negative values be the opposite.

Also, I believe that the depth scales should for both deep parallax and "regular" depth mapping should be attenuated. Here's some code that I changed that works much better, in my opinion, as the values aren't so extreme.

Source changes I've made in "scene/resources/material.cpp":

Line 647
```
From:
code += "\t\tvec2 P = view_dir.xy * depth_scale;\n";

To:
code += "\t\tvec2 P = view_dir.xy * depth_scale * -0.1;\n";
```
Line 665
```
From:
code += "\t\tvec2 ofs = base_uv - view_dir.xy / view_dir.z * (depth * depth_scale);\n";
To:
code += "\t\tvec2 ofs = base_uv - view_dir.xy / view_dir.z * (depth * depth_scale * -0.05);\n";
```
Line 2083
```
From:
Line 2083: set_depth_scale(0.01);
To:
Line 2083: set_depth_scale(0.1);
```
And here are the before and after results:
![before_edit](https://user-images.githubusercontent.com/20325471/35015187-d681208e-fad8-11e7-9529-8388594efb94.gif)
![after_edit](https://user-images.githubusercontent.com/20325471/35015190-df410aa4-fad8-11e7-81f1-a918fdf1489a.gif)

These code changes are just temporary tweaks while I work on my project and are just for showing the idea. I imagine it would be nessecary to change the "depth" in code to "height" or "HeightDepth" for easier reading, but of course that's up to you guys.

**Comment by leiget** [comment]
The main difference in my changes is that a white pixel in the depth map texture causes the surface to look like it's popping out instead of going inward, because for the longest time in bump maps and displacement maps white makes things go up and black means they are unaffected.

**Comment by jamie-pate** [comment]
I'd think ideally that #7f7f7f would be the midpoint and darker would go down and brighter would come up, but not sure on the technical challenge. Could also have a 'midlevel' setting as well. Similar to the displace modifier in blender.

**Comment by leiget** [comment]
With displacement actual geometry is moved in and out. The mid point in the displace modifier is there so that the vertices don't displace into each other. With a depth, normal, or bump shader no geometry is modified so the midpoint isn't necessary and would make the shader slower.

**Comment by jamie-pate** [comment]
I know this is not actual displacement. `White = maxdepth` or `white = mindepth` seems like it will be fixed by the upcoming 'invert' setting on import.

Not sure if 'height' maps are completely different from 'depth maps' in the other sense where depth means the highest value is at the polygon surface, lowest is 'behind' but height implies that the lowest value ( be it white or black in the texture) becomes the polygon surface and the highest value is 'above'

A midpoint or at least a toggle would let you decide at material creation time which one you want, if 'height' in this sense even makes sense, ever

**Comment by jamie-pate** [comment]
For my project I ended up just inverting and applying a curve by hand since I only have like 5 depth textures 
![image-1](https://user-images.githubusercontent.com/682658/46908030-17f1a800-ced1-11e8-8a3c-260d62a03af0.png)

**Comment by akien-mga** [comment]
I think depth was renamed to height in the `vulkan` branch already. (CC @reduz @fracteed)
I don't know about the attenuation of the input values.

**Comment by clayjohn** [comment]
Yea. Both points are fixed. The attenuation is just an issue of properly scaling the depth value (in master) and depth has been reversed and renamed height in 4.0
