### ISSUE TITLE
Build tools (godot.windows.tools.64.exe) appear to be broken on Windows

### ISSUE THREAD

**Issue by dynamite-ready** [godotengine/godot#15795]
**Godot version:**
GIT Head@1968cc

**OS/device including version:**
Windows 8

**Issue description:**
Tried to build a simple module. The "summator" example here - http://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html?highlight=modules - Managed to compile it very recently, but now it appears to break late on in compilation with the following error message:

LINK : fatal error LNK1168: cannot open bin\godot.windows.tools.64.exe for writing

Relatedly, I tried to build the GDNative CPP project on the same machine - https://github.com/GodotNativeTools/godot-cpp - Which breaks with:

IOError: [Errno 2] No such file or directory: 'godot_api.json

Though I can't be sure if they share the same root cause.

**Steps to reproduce:**
Create a new module on Windows, and rebuild Godot.

**Comment by vnen** [comment]
> LINK : fatal error LNK1168: cannot open bin\godot.windows.tools.64.exe for writing

Make sure the editor is **closed** when building. It's the usual cause for this error.

The CPP bindings error isn't related to this and if you're having problems you should open an issue in their repository.

**Comment by mhilbrunner** [comment]
Clossing, assuming this is solved by vnen's comment above. If you still encounter the issue, please comment here or open a new issue.
