### ISSUE TITLE
Crash when opening a project containing a script that preloads a GDNative class

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15793]
Godot 3.0 master

Just tried to open the project, and it crashed with the following call stack.
The script doesn't even references that class, as there is no .gdns referring to it, but it still gets registered and crashes in the middle of registration.

Edit: it seems to happen as soon as I try to register a signal.

![image](https://user-images.githubusercontent.com/1311555/35014464-f82979ec-fb10-11e7-80f7-a226d5911908.png)

**Comment by akien-mga** [comment]
CC @karroffel

**Comment by Zylann** [comment]
By reading the code, I found that the number of arguments of my signal is indeed zero.
But...
It means that this following code runs down to a malloc(0):

```cpp
template<class T>
void register_signal(String name, Dictionary args = Dictionary())
{
	godot_signal signal = {};
	signal.name = *(godot_string *)&name;
	signal.num_args = args.size(); // <--- THIS IS ZERO
	signal.num_default_args = 0;

	// HERE MALLOC(0)
	signal.args = (godot_signal_argument*) godot::api->godot_alloc(sizeof(godot_signal_argument) * signal.num_args);
```

Which, according to http://www.cplusplus.com/reference/cstdlib/malloc/, returns a pointer that should not be referenced because the return of `malloc` will be implementation-dependent.

**Comment by Zylann** [comment]
I nailed it further. 
I wrote my own `register_signal` function which does nothing, and I found this:

Crashes:
```cpp
template<class T>
void my_register_signal(const wchar_t *name, Dictionary args = Dictionary())
{

}
```

Doesn't crash:
```cpp
template<class T>
void my_register_signal(const wchar_t *name)
{
	Dictionary args = Dictionary();
}
```
![image](https://user-images.githubusercontent.com/1311555/35017886-49be51fc-fb1f-11e7-9a5f-13b5871da1bb.png)
