### ISSUE TITLE
Setting stream with VideoPlayer node

### ISSUE THREAD

**Issue by yuri-karadzhov** [godotengine/godot#158]
I tried to setup videoplayer to play big_buck_bunny.ogg video sample, but it's impossible to set stream neither from GUI nor from scripts.

From GUI Load set stream to null, new VideoStreamTheora does not allow to chose stream path (after several identical attempts it set it somehow but it does not work anyway).

From script set_strem() function require an object from Stream class which does not exists.

Format *.ogv works through Load (filter does not restrict to this format). New VideoStreamTheora and script - still do not work.

**Comment by celisoft** [comment]
Same issue. Is there any progress about this almost 1 year later ?

**Comment by mohaalak** [comment]
it's not enabled in default version you should build it yourself . clone or download repository . download and install scons. download and install vs or mingw . then in the command line of either one type "scons platform=windows theora=yes . then in gui you have option to choose between mp4 ogv .

**Comment by shimpe** [comment]
Is there a reason for disabling it by default? Executable size or software stability? Building yourself is hardly an option as it is nearly impossible to build export templates for all platforms yourself.

**Comment by punto-** [comment]
At some point it wasn't building on all platforms, I think right now it
does build, but we never got it to run fully optimized everywhere.. Audio
sync is an issue too. We need to figure put the right compiler options for
all platforms, and improve on the audio/timer code. The library authors
claim it runs smoothly on old mobile devices so it should be possibe..

**Comment by reduz** [comment]
also there is a pending rewrite of the audio subsystem, which will force us
to rewrite some of this code..

**Comment by shimpe** [comment]
Ok, thanks for all the insights!

**Comment by volzhs** [comment]
I'm waiting for this too.

**Comment by reduz** [comment]
I fixed it, but forgot to push it to github. Tomorrow will do

**Comment by volzhs** [comment]
What a great NEWS ! :)

**Comment by akien-mga** [comment]
According to reduz's comment, I guess this issue is fixed by 52e7567. Feel free to reopen if it's not the case, or to comment here to confirm the fix.

**Comment by BenjaDev** [comment]
Hey there! Did anybody use the "set_stream()" method in script with success? this method requires an object from Stream class which does not exist. Or it does exist, but the docs aren't helpful at all in this case.

Example: 
I saved a file as a raw-byte array, actually it's an .ogv video, and I would like to play it via script:
videoPlayer.set_stream(myFile)

I can play the video, if I load it manually into the player. But I can't figure out, how to do it via script. It's quite important for me, 'cause I'm doing my final exam with godot, so every hint would be very welcome!

**Comment by vnen** [comment]
@BenjaDev should be simply `videoPlayer.set_stream(load("path/to/file.ogv"))`. You can ask in [QA](https://godotengine.org/qa/) if you have doubts,

**Comment by BenjaDev** [comment]
@vnen Now I'm feeling dumb. It worked fine, thanks a lot! :)
