### ISSUE TITLE
Broken Blender -> GLTF2 -> Godot pipeline

### ISSUE THREAD

**Issue by brainsick** [godotengine/godot#15802]
**Godot version:**
Godot 3.0 RC1

**OS/device including version:**
Ubuntu 17.10 x64, AMD Radeon R9 Fury

**Issue description:**
I'm trying to import [phoenix bird](https://sketchfab.com/models/844ba0cf144a413ea92c779f18912042) into Godot.

I first import the FBX file into Blender.  I fix up the textures and edit the animation to end on the last keyframe.  I play the animation to test it; Blender success!  .blend file included (you may need to add a lamp back in).

![screenshot from 2018-01-17 00-25-50](https://user-images.githubusercontent.com/1111573/35029051-a49c00ca-fb1e-11e7-9092-b783ea3eba63.png)

I delete the default lamp and camera and export it via the Khronos GLTF 2 Exporter.

\- Embed buffers
\- Embed images
\- Strip delimiters
\- Export selected only
\+ Export all layers
\- Export extras
\+ Convert Z to Y up
\- Apply modifiers
\- Force maximum indices
\+ Export texture coordinates
\+ Export normals
\+ Export tangents
\+ Export colors
\+ Export materials
\- Export cameras
\+ Export animations
\+ Export within playback range
\+ Keyframes start with 0
\- Force sample animations
\+ Export skinning
\- Bake skinning constraints
\+ Export morphing
\+ Export morphing normals
\+ Export morphing tangents
\- Experimental (none)

Godot imports the GLTF 2 file.  I double click the fly.gltf file and Open Anyway the scene for a preview.  

![screenshot from 2018-01-17 00-46-03](https://user-images.githubusercontent.com/1111573/35029292-db709c72-fb1f-11e7-98b9-b479aa428cab.png)

The scale appears to be way off.  I had this same issue with the GLTF files generated by SketchFab.

Selecting the AnimationPlayer and pressing "Play selected animation from start. (Shift+D)" causes what is visible to inexplicably rotate.

No mesh is rendered.  Nothing I do with the materials makes any difference until I play the animation and then I end up with this:

![screenshot from 2018-01-17 01-01-57](https://user-images.githubusercontent.com/1111573/35029775-109a2ca4-fb22-11e7-99a3-e5dce631db7b.png)

**Steps to reproduce:**

**Minimal reproduction project:**

[PhoenixAltGLTFImport.zip](https://github.com/godotengine/godot/files/1637984/PhoenixAltGLTFImport.zip)

**Comment by fire** [comment]
Issue is very similiar to my issue. https://github.com/godotengine/godot/issues/15181

**Comment by capnm** [comment]
Yep, the gltf2 importer is currently in a sorry state:
https://github.com/godotengine/godot/issues/14725
https://github.com/godotengine/godot/issues/14636
https://github.com/godotengine/godot/issues/15715
https://github.com/godotengine/godot/issues/15798

**Comment by reduz** [comment]
Importing geometry generally works fine, skeletal animation is broken at the moment.
regarding scale, both Godot and GLTF use the same coordinate system and unit scale, so if scale does not look right it's a problem of the model.

**Comment by capnm** [comment]
I didn't figured why, but sometimes some spatial nodes get a completely wrong transformation …
If you correct this manually in the editor (the last man), even the animation will be correct.

**Comment by reduz** [comment]
> didn't figured why, but sometimes some spatial nodes get a completely wrong transformation …

I have seen this in a few scenes I got from sketchfab but, as I mentioned, I'm not sure why it might happen as Godot does no unit or axis conversion at all, given it uses the same exact as gltf

**Comment by brainsick** [comment]
There is similarity with #15181 in that it mentions scale.  The other issues appear to be different situations though.

I thought GLTF was the "approved" 3d asset pipeline, so I was surprised to find these issues and thought I should report them.

**Comment by capnm** [comment]
blender -> gltf -> godot / gltf-viewer

![bildschirmfoto vom 2018-01-17 14-00-37](https://user-images.githubusercontent.com/4047289/35044487-d0d6e7c8-fb90-11e7-83d8-53caafa672df.png)

![bildschirmfoto vom 2018-01-17 14-12-15](https://user-images.githubusercontent.com/4047289/35044500-e01b50ac-fb90-11e7-90e1-24dd1c56b1d7.png)

![bildschirmfoto vom 2018-01-17 14-12-57](https://user-images.githubusercontent.com/4047289/35044512-ef7f184e-fb90-11e7-9716-921f2dd27c96.png)

![bildschirmfoto vom 2018-01-17 14-23-40](https://user-images.githubusercontent.com/4047289/35044859-2af13ece-fb92-11e7-9e6a-472af926015f.png)


[blender-exp2.zip](https://github.com/godotengine/godot/files/1639085/blender-exp2.zip)

**Comment by reduz** [comment]
Nope, "official" is still Collada until gltf importer is more tested and
stable. It will hopefully become less buggy in 3.1

**Comment by reduz** [comment]
In any case, if you guys can make simple scenes (very little amount of
geometry and bones) that break, that will make my job of fixing the
importer easier

**Comment by brainsick** [comment]
Okay, I have issues noted for the Better Collada exporter too. I haven't submitted them because I wasn't sure if it was still supported.

**Comment by brainsick** [comment]
I can do simpler.  This is so simple that I no longer recognize it as the original reported issue though.

https://youtu.be/Sh7nih_8a1g
[BlenderGLTFGodotCube.zip](https://github.com/godotengine/godot/files/1640389/BlenderGLTFGodotCube.zip)

If it matters, I built a spin cube from the ground up and it worked as expected.  I discarded that and tore the spin cube down from my crush cube example and then an unexpected scaling issue manifests.  Blender and [glTF Viewer](https://gltf-viewer.donmccurdy.com/) seem fine though.  blend file included.

**Comment by brainsick** [comment]
Another animation quirk in Godot.  This time using [03 all animations](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/scenes).  The parent sphere does not move fluidly and the tetrahedron has scale issues in its animation.

![image](https://user-images.githubusercontent.com/1111573/35079942-251fc91e-fbd0-11e7-9974-115470754ea1.png)

Just an amusing observation, but Blender rotates counter to Godot and glTF Viewer.

https://youtu.be/quzdp0nYlDI

**Comment by capnm** [comment]
>Just an amusing observation, but Blender rotates counter to Godot and glTF Viewer. This could be an export bug or I did something goofy in the export settings.

That's an inherent problem of the Euler rotation from 0° to 0°. If you change the second endpoint to 360°, it works as expected.

**Comment by brainsick** [comment]
> That's an inherent problem of the Euler rotation from 0° to 0°. If you change the second endpoint to 360°, it works as expected.

I naively used 0° to 360° in my own attempt which didn't manifest this behavior.  So, today I learned!  Thanks.  :+1:

**Comment by brainsick** [comment]
Another animation quirk in Godot.  Using [01 morphed cube](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/scenes).  The cube does not animate at all in Godot.  This one uses something called shape keys.  Those were discussed in #7883; does that need to be revisited due to GLTF?  Or might this be an issue with the exporter?

**Comment by fire** [comment]
https://github.com/googlevr/poly-toolkit-unreal/blob/master/PolyToolkit/Source/PolyToolkit/Private/Gltf2Importer.cpp Has an Apache 2 licensed gltf2 importer. Perhaps it is good to check if Google did things differently.

**Comment by RandomShaper** [comment]
I'm investigating skeleton issues. At this point I have a solid clue to follow.

**Comment by fire** [comment]
Fixes from 5b70ad9d34d2777e3abd0a13118442eb132aff70

First scene is the same as https://github.com/godotengine/godot/issues/15798 

![godot windows opt tools 64_2018-08-06_23-18-15](https://user-images.githubusercontent.com/32321/43758116-f6c6bf0c-99cf-11e8-9f5a-575a91360118.png)

Second scene is Cesium man.

![godot windows opt tools 64_2018-08-06_23-27-58](https://user-images.githubusercontent.com/32321/43758255-616f961c-99d0-11e8-9e58-516c1feeb25c.png)

https://github.com/godotengine/godot/issues/15802#issuecomment-359271606

01_morphed_cube is still not supported.

**Comment by akien-mga** [comment]
Closing as fixed by 5b70ad9, if there are some cases which still don't work, please open specific issues for them.
