### ISSUE TITLE
intersect_ray returns empty dictionary when the ray have some angles.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#15808]
**Godot version:**

b1017261055a815137132740e27200d50f3d2946

**OS/device including version:**

Manjaro 64bit

**Issue description:**

intersect_ray returns empty collision when it is supposed to return collision.

**Steps to reproduce:**
Download the sample project and open the gdscript caster.gd. Uncomment line 10 and you will get an empty collision from the intersect_ray at line 20.

Problem exists in GodotPhysics and Bullet.

**Minimal reproduction project:**

[intersect_ray.zip](https://github.com/godotengine/godot/files/1638987/intersect_ray.zip)

**Comment by poke1024** [comment]
Note that `translation + transform.basis.z * Vector3(0,0,100)` ends up at `(0, 3, 2.079488)`, which is near your caster. Did you mean `translation + transform.basis.z * 100`?

**Comment by kakoeimon** [comment]
@poke1024 You are right, this was my mistake all along.
Sorry about that.
