### ISSUE TITLE
Linux x64 export template not working when debug enabled.

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#15800]
**Godot version:**
Godot Master (commit 14b230f35f6b2498ef1fe93d8947bcc6f54b9261) 

**OS/device including version:**
Debian 9.3 64-bit.
Clang 5.0 (also tried 3.8, 3.9, 4.0 - all behaved the same)

**Issue description:**
Ok, so I compile my templates for linux and android. When I use my templates with debug enabled I get this error

`cannot execute binary file: Wrong executable format`

Two text files are created, they are empty, but here are their names:

`�@	�H\�@NTMc�@"+Rg�@�Wl�@
��H��w��@��G`}	B��L��@�Q��@�>��@�`7�@�L7�@�Q?�@�>?�@�V�@}[�@#�W�@ (codificación no válida)`

`��@@�
�@8 (codificación no válida)`

This is the output from `file` command on export with debug:

`ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter *empty*, for GNU/Linux 2.6.32, not stripped`

And this is the one with debug off:

`ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped`

There are no errors in the logs while making this templates.

Is this a bug? Is this my fault? Someone knows how can I fix it?

**Comment by akien-mga** [comment]
How do you compile the template, and how do you install it? Can you check the validity of the compiled binary in your `bin/` folder?

**Comment by vicguedez** [comment]
Hi akien, this is the script for linux templates

```
echo "Building template for Linux x64 release."
scons -j4 platform=x11 builtin_openssl=yes target=release tools=no bits=64 use_llvm=yes > "${COMPILED_PATH}/logs/x11_64_template_release.log" 2>&1
mv -f "./bin/godot.x11.opt.64.llvm" "${COMPILED_PATH}/templates/linux_x11_64_release" >> "${COMPILED_PATH}/logs/x11_64_template_release.log" 2>&1
echo "Done."

echo "Building template for Linux x64 debug."
scons -j4 platform=x11 builtin_openssl=yes target=release_debug tools=no bits=64 use_llvm=yes > "${COMPILED_PATH}/logs/x11_64_template_debug.log" 2>&1
mv -f "./bin/godot.x11.opt.64.llvm.debugsymbols" "${COMPILED_PATH}/templates/linux_x11_64_debug" >> "${COMPILED_PATH}/logs/x11_64_template_debug.log" 2>&1
echo "Done."
````

And these are the log files for the last build.

[x11_64_template_debug.log](https://github.com/godotengine/godot/files/1639072/x11_64_template_debug.log)
[x11_64_template_release.log](https://github.com/godotengine/godot/files/1639073/x11_64_template_release.log)

Sorry, how can I check validity of the compiled binary?

**Comment by vicguedez** [comment]
I'm DUMB !

I have been using "debugsymbols" instead of the real file, fixed by changing:

`mv -f "./bin/godot.x11.opt.64.llvm.debugsymbols"`

To:

`mv -f "./bin/godot.x11.opt.debug.64.llvm"`

That is the real template file.

Sorry.
