### ISSUE TITLE
Dialog bounds don't have default values in the Editor Settings

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15810]
**Godot version:**
1699978

**Issue description:**
Maybe this is by design, but the dialog bounds inside `Interface > Dialogs` don't have default values.

**Comment by akien-mga** [comment]
Well they're not even supposed to be there, it's just metadata used by the dialogs once resized manually to restore them to the previous size. They should be removed from the editor settings and move to their own metadata file.
