### ISSUE TITLE
Dialog bound value setting popup goes out-of-bounds in the Editor Settings

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15811]
**Godot version:**
 1699978

**Issue description:**
When setting the values of a dialog bound inside `Interface > Dialogs`, the last LineEdit goes outside of the popup:
![screenshot4](https://user-images.githubusercontent.com/30739239/35053061-460fc452-fb90-11e7-8cc7-df25e81e5773.png)

**Comment by AlexHolly** [comment]
Fixed in Master Branch
![image](https://user-images.githubusercontent.com/4741886/44913991-22941b80-ad2f-11e8-9c1d-1c93e219110a.png)
