### ISSUE TITLE
Input.SetMouseMode(Input.MOUSE_MODE_CAPTURED); does not build in rc1 mono project

### ISSUE THREAD

**Issue by typedefJorge** [godotengine/godot#15814]
**Godot version:**

v3.0-rc1_mono_osx64

**OS/device including version:**

![image](https://user-images.githubusercontent.com/5349329/35058760-eca62fe0-fb86-11e7-87cd-3270a58cf4d2.png)

**Issue description:**

Attempted to run project that had the following code snippet:
`Input.SetMouseMode(Input.MOUSE_MODE_CAPTURED);`
and it failed to build with the following error:
![image](https://user-images.githubusercontent.com/5349329/35059245-807014ba-fb88-11e7-9ab9-e3cdefc2948d.png)
Even though when you inspect the code in VSCode(Ctrl + Click) you can see the property exists in the input class
![image](https://user-images.githubusercontent.com/5349329/35059355-dd1149b4-fb88-11e7-9261-0f46add81114.png)

    

**Steps to reproduce:**
1. $git clone https://github.com/typedefJorge/godot3dSample/tree/rc1InputBug
2. Open project in Godot Editor
3. Run from Editor

**Minimal reproduction project:**

**Comment by neikeq** [comment]
It should be `Input.MouseMode.Captured`. Not sure why VSCode is showing you that outdated class.

**Comment by typedefJorge** [comment]
Yeah I deleted the .mono folder in my project and rebuilt and i was able to see the updated typings. Thanks for looking into it
