### ISSUE TITLE
Mouse offset in text editor if  "too many" blocks are folded

### ISSUE THREAD

**Issue by Nobelix** [godotengine/godot#15821]
**Godot version:**
RC1

**OS/device including version:**
Ubuntu 16.04

**Issue description:**
~~When opening a bottom tab (Output/Debugger etc...) the mouse gets offset in the text editor.~~
https://streamable.com/0pnoz 
EDIT:  The mouse gets offset in the code editor after folding numerous blocks in a long script.
**Steps to reproduce:**
Open a long script and fold some blocks, notice how the mouse clicks are offset when editing the end of the script.

**Comment by Einlander** [comment]
This also happens if you have a long script and fold too many functions.

**Comment by Nobelix** [comment]
@Einlander I wasn’t sure of the cause but your hypothesis is more likely.

**Comment by akien-mga** [comment]
CC @ianb96 @poke1024 @Paulb23
