### ISSUE TITLE
Built-in scripts being listed after doc pages

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15827]
**Godot version:**
1699978

**Issue description:**
If a script is a built-in type, it will not be listed together with the other scripts, but after the currently open doc pages:
![screenshot1](https://user-images.githubusercontent.com/30739239/35075583-101603f2-fbdb-11e7-8bd9-dfe86c1e9c7c.png)

**Comment by vnen** [comment]
Isn't this the same as #14400? This seems to happens with all scripts, not only built in ones.

**Comment by YeldhamDev** [comment]
@vnen When opened manually, yes. But they order themselves correctly when closing and opening the editor, except for the built-in scripts.

**Comment by vnen** [comment]
Even when you right-click the script list and click on `Sort` on the context menu?

**Comment by YeldhamDev** [comment]
@vnen Sorting puts them together with the other scripts, but closing and reopening the editor shoves them right back at the bottom.

**Comment by DualMatrix** [comment]
Could not reproduce on master, it seems the way built-in scripts are named has changed as well.

**Comment by akien-mga** [comment]
Indeed, there were various usability changes for this.
