### ISSUE TITLE
Using theme created with 'Create From Current Editor Theme' raises errors

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#15823]
**Godot version:**
Godot 3.0 RC 1

**OS/device including version:**
Windows 10 64, GeForce GTX 970, 

**Issue description:**
Using theme created with 'Create From Current Editor Theme' raises errors

**Steps to reproduce:**
Create theme using Create From Current Editor Theme, errors:
![image](https://user-images.githubusercontent.com/7307968/35070618-21572684-fbde-11e7-98f2-ebc879705ef3.png)
Attach theme to a Control with a couple buttons as children, run project. Errors:
![image](https://user-images.githubusercontent.com/7307968/35070668-55434d2e-fbde-11e7-9a26-8ee5ac7bf94b.png)

**Minimal reproduction project:**
[Test Godot.zip](https://github.com/godotengine/godot/files/1640830/Test.Godot.zip)

**Comment by CCODE05B** [comment]
and also make the engine Lagging

**Comment by reduz** [comment]
@toger5 @djrm @volzhs

**Comment by reduz** [comment]
I am not sure if this will ever work, given editor theme uses resources not available to the engine.
I guess some work would be needed to get this to work properly, else the feature may need to be removed.

**Comment by PLyczkowski** [comment]
Are there any alternative ways to get a theme .tres that looks more or less like the editor?

**Comment by toger5** [comment]
I also found that on 3.1 the theme frome ditor does not work at all...

I can create one from the editor though.
U can than delete all the esitor specific things to just have the needed styleboxes.

But as i said, currently there are a bunch of other issues i think. Played around wirh it a week ago.

**Comment by PLyczkowski** [comment]
Haven't tested yet, but I've seen this was fixed.
