### ISSUE TITLE
VehicleBody won't move once inherited RigidBody enters sleep mode

### ISSUE THREAD

**Issue by nadnam** [godotengine/godot#15828]
**Godot version:**
v3.0-rc1_x11.64

**Issue description:**
Since last official release (beta2) VehicleBody now inherits RigidBody. When vehicle comes to stop its RigidBody enters sleep mode. Applying engine power will not wake it up and vehicle remains static unless "sleeping = false" is called directly. Applying engine power should wake it up.

**Comment by AndreaCatania** [comment]
This should be fixed, can you please check it now?

**Comment by akien-mga** [comment]
Assuming fixed, please comment if you can still reproduce it in the master branch / 3.1 and we'll reopen.
