### ISSUE TITLE
Memery leak with cyclic preload in GDScript

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#15839]
**Godot version:** Godot 3.0 RC1

**Issue description:**

Memery leak with cyclic preload in GDScript.

**Steps to reproduce:**

Create a script `a.gd` with content as below
```gdscript
extends SceneTree

const b = preload("b.gd")
func _init():
	quit()
```

Create another script `b.gd` with content as below
```gdscript
const a = preload("a.gd")
```

Run the script `a.gd` with godot
```bash
godot -s a.gd
```

The program complains about memery leaks
```
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1989.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:418.
```

**Comment by reduz** [comment]
This is not a bug, this is a feature. It's in the GDScript documentation. Any cycles are leaked.

**Comment by Geequlim** [comment]
So how to use this feature in right way？
I can't write as weakref(preload('b.gd')

**Comment by sersoong** [comment]
What?Is it a feature?How to use it.

**Comment by reduz** [comment]
@Geequlim you cant, simply dont do cycles. Just dont use preload, use load() normally and then you can weakref.
