### ISSUE TITLE
C# script variables don't appear in the Remote Scene Tree like GDScript's

### ISSUE THREAD

**Issue by realManix** [godotengine/godot#15832]
**Godot version:**

Godot 3.0 RC1

**OS/device including version:**

Windows 10

**Issue description:**

Script variables, including "Export" variables, do not seem to appear in the remote scene tree if the script is C#.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by samdze** [comment]
This is a bug, please someone mark this issue as such.
I can't see/debug exported variables in the remote scene tree with C# scripts, it's quite debilitating.

**Comment by neikeq** [comment]
Can anyone still reproduce this? Looks the same as #33896 which was fixed a few months ago.

**Comment by Calinou** [comment]
Closing per @neikeq's comment. Please comment if you can still reproduce this in 3.3rc6 or later.
