### ISSUE TITLE
Snap to grid not working

### ISSUE THREAD

**Issue by imekon** [godotengine/godot#15846]
Godot V3.0 RC1

Windows 10

Switch on snap to grid in editor, objects in panel appear to ignore grid

**Steps to reproduce:**
Create a new project
Add a panel container
Give the panel container a size
Add a panel
Snap to Grid is selected
Set grid size to 16
View grid

Editor ignores grid settings.

**Minimal reproduction project:**
[snap_to_grid.zip](https://github.com/godotengine/godot/files/1643906/snap_to_grid.zip)

**Comment by akien-mga** [comment]
CC @groud

**Comment by groud** [comment]
I cannot reproduce, are you sure you activated the snapping in general ?
The icon with a magnet next to the snap configuration menu.

**Comment by imekon** [comment]
Uh... yeah that makes it work. Didn't realise that switched it on/off - so what is "snap to grid" for? Just checked, you have to have *both* turned on for snap to grid to work? That's confusing!

**Comment by groud** [comment]
>  you have to have both turned on for snap to grid to work ?

Well, yes. The button is for activating snapping in general, and the menu to configure how it works.
But maybe it needs to be reworked, if other people complain I'll search for new solutions.

**Comment by drambique** [comment]
I was having trouble getting snap to grid working while making the [Dodge the Creeps](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html) tutorial game and wouldn't have figured it out if this issue didn't exist. I don't think you need to change editor, but I think you should make note of it in the tutorial to help out people learning the engine.

**Comment by altertango** [comment]
I second drambique on the suggestion to clarify a bit the tutorial: 

"make sure “Snap to Grid” is checked. This option can be found under the “Snapping Options” button to the left of the “Lock” button. It appears as a series of three vertical dots."

That doesn't ever mentions the necessity to press another button. It probably even makes it less likely that you search the button since you are just following instructions, although I assume more perceptive people would figure it out before getting to this thread.

Cheers

**Comment by securas** [comment]
I'm trying to use snap to pixel or grid and it works as long as the object is not rotated. If a transform rotation is applied, snapping no longer seems to work.

**Comment by giogadi** [comment]
+1, I had trouble following the "Dodge the Creeps" tutorial and thought that the "Snap to Grid" option wasn't working. The tutorial or the UI could be improved to make this clearer.

**Comment by epuscasu** [comment]
+1 for the issue cropping up when following the tutorial

**Comment by usersaurus** [comment]
I had the same problem with the getting started tutorial, so looks like a conflictive point :)
