### ISSUE TITLE
Message spam on GDScript syntax error

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#15840]
Godot Master
Kubuntu 64-bit

Output show this message many times
`scene/gui/text_edit.cpp:3360 - Index p_to_column=11 out of size (text[p_to_line].length() + 1=11)`

Steps:
1. Create a Default GDScript.
2. Make a new line and add a "#" 
3. Select the line and uncomment with `ctrl+k` or `ctrl+u` 

```
#
```

Note that test1.gd has also a syntax error

**Comment by Applemann** [comment]
I have same issue on Ubuntu 16.04 LTS   with Godot version: v3.0.2.stable.official
```
ERROR: _base_get_text: Index p_to_column=11 out of size (text[p_to_line].length() + 1=11)
   At: scene/gui/text_edit.cpp:3360.
```
Do you plan somebody fix it??

**Comment by AlexHolly** [comment]
https://github.com/godotengine/godot/commit/cdc5264a3ef08c0e6805eb38d3f632ca21a5171e

It seems there is still a case missing I just had a few of these. I am not able to reproduce so far (something with selecting and ctrl+k).
```
ERROR: _base_get_text: Index p_from_column=2 out of size (text[p_from_line].length() + 1=2)
   At: scene/gui/text_edit.cpp:3421.
```
