### ISSUE TITLE
Capacity to use new lines with artithmetic operators

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15859]
To avoid having to use brackets when doing operations like these:
```
example = 1 +
1
```
```
example = "one" +
"one"
```

**Comment by poke1024** [comment]
In GDScript?

```
	var x
	x = 1 +
		2
```

gives an error for me too; I think the current parser always wants a bracket here:

```
	var x
	x = (1 +
		2)
```

**Comment by YeldhamDev** [comment]
@poke1024 I don't need brackets when I'm using only numbers, how are you getting an error?

**Comment by vnen** [comment]
I prefer not, use parentheses or add a `\` at the end of the line if you really need to split an expression.

**Comment by YeldhamDev** [comment]
@vnen Huh, I didn't knew about using `\` for this.

**Comment by YeldhamDev** [comment]
Yep, looking back this seems like a stupid request, closing it.
