### ISSUE TITLE
Text in code editor sliding around in specific manner

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15860]
**Godot version:**
 d7e07fb

**Issue description:**
When it's possible to scroll vertically, and beginning to be able to scroll horizontally this happens:
![peek 2018-01-19 03-22](https://user-images.githubusercontent.com/30739239/35136014-039bf04e-fcc8-11e7-9703-d49facca435a.gif)

**Comment by akien-mga** [comment]
This never stops... :-|
