### ISSUE TITLE
Editor crash after removing a Popup Menu

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#15868]
**Godot version:**
![image](https://user-images.githubusercontent.com/7307968/35149431-4f6b39f0-fd16-11e7-82fe-7cde0fcb3b19.png)

**OS/device including version:**
Windows 10 64, GTX 970

**Issue description:**
Got this when removing a popup menu in tool mode from the editor. The popup menu removed itself, and quee_free itself, triggered by clicking outside of it. Cold not isolate the issue, this works in a empty project.

ERROR: List<class Control *,class DefaultAllocator>::_Data::erase: Condition ' p_I->data != this ' is true. returned: false
   At: c:\projects\godot-builds\godot\core\list.h:158
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] CallWindowProcW
[16] CallWindowProcW
[17] glDebugEntry
[18] CallWindowProcW
[19] DispatchMessageW
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] <couldn't map PC to fn name>
[25] BaseThreadInitThunk
-- END OF BACKTRACE --

**Comment by Malkverbena** [comment]
This bug makes it impossible to use the popup menu node.
I kindly ask you to move this issue to 3.0 milestone.
After all, to realise the engine with a node that does not work is something that demands a more deep thought.

**Comment by PLyczkowski** [comment]
Nope, unless someone else encounters it, I think it's not a bug. The scene I got this in somehow added the Popup Menu twice, most probably dues to my mistake somewhere. Coded around it. Closing.

**Comment by Malkverbena** [comment]
I have this issue but in my case I can't close the menu without crash the project whatever how I use this node.

**Comment by akien-mga** [comment]
@Malkverbena Unless you have the exact same issue ("when removing a popup menu in tool mode from the editor"), please open a new issue with details about how to reproduce the issue and ideally a project that can be used to do so.

**Comment by PLyczkowski** [comment]
@Malkverbena Check in Remote tree view if during runtime the node is not added twice. You can also print something in the Popup node _ready and see if it prints more than once.

**Comment by PLyczkowski** [comment]
Or better yet in _init()

**Comment by Malkverbena** [comment]
My problem is a bit different. The project crash when I use the node. 
I can call the menu when running the project but just it. If I click whatever on the screen after the menu is showed the project chash. On older builds everything works fine.
I'll open a new issue as you tell me to do but here is the link to my project anyway.

https://github.com/Malkverbena/Inventory
