### ISSUE TITLE
Allow setting the client port on NetworkedMultiplayerENet

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#15877]
The new Godot 3 network API is amazing for LAN games, but currently there is no way to use it on games accross different routers because of the NAT port-forwarding problem. One possible solution is to use NAT-punching[1], but that requires an intermediary server connection (easily solvable using current StreamTCP or PacketUDP classes) AND setting up the game on the same port during server connection and client-to-client handshake - as it is right now, Godot will assign a different arbitrary port when creating a client, thus making the router assign a different out-port for the connection and blocking the p2p connection between users.

The easy solution is to allow the user to specify a port when creating a client like in PacketUDP listen(port).

I tried creating this setup on my "Bomber Matchmaking Server" project with both UDP and TCP, but I found no way to guarantee I could use a specified port for the client: https://github.com/henriquelalves/Godot-Bomber-matchmaking-server.

[1]: http://www.brynosaurus.com/pub/net/p2pnat/

**Comment by Calinou** [comment]
How does specifying the client port bypass the requirement to forward a port for the host?

**Comment by henriquelalves** [comment]
The client has to use the same port known by the server for this to work, because routers are configured to drop any packages coming from unrequested sockets; so one way to bypass this is to send/receive packets until you stabilish a connection between players using the same information the server has of each player. NOT using this same socket means the other player will receive a packet coming from an unrequested peer, rendering the information received by the server useless. 

Im not sure I explained it well, but thats basically the idea of NAT punching - using a server to intermediate communication between players using the same sockets.
