### ISSUE TITLE
The value texture of ProgressBar became abnormal

### ISSUE THREAD

**Issue by tam0705** [godotengine/godot#15870]
**Godot version:**
Godot 3.0 rc-1

**OS/device including version:**
Windows 10 Pro 64-bit

**Issue description:**
One day I was testing my multiplayer game. I tried to kill another player, reducing their health value. When their health value went near zero, their health bar became abnormal:
![godot bug](https://user-images.githubusercontent.com/29124683/35153276-6f0d864a-fd58-11e7-94ed-6de6a95a6f8b.png)
Their health bar from their perspective is this:
![godot bug2](https://user-images.githubusercontent.com/29124683/35153363-d3cb32e4-fd58-11e7-9b70-af629e8b9812.png)

Thank you and sorry for my bad English and explanation

**Comment by Noshyaar** [comment]
Please include the minimal project and/or relevant code.

**Comment by tam0705** [comment]
Well, here it is..
[2D LMO Project.zip](https://github.com/godotengine/godot/files/1646704/2D.LMO.Project.zip)

**Comment by Noshyaar** [comment]
Findings:
- It happens when $ProgressBar:
    - has value: `0.02*(max - min) <= value - min < 0.04*(max - min)`
    - has width: `((max-min)/value) < width < 2*((max-min)/value)`
    - has a **foreground StyleBoxFlat with any corner\_radius\_\* != 0**
- It is also visible from the 2D editor.
- It is rendered as infinitely wide.
