### ISSUE TITLE
VisualServer methods are not bound

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15879]
Godot 3.0 master a1c08b71091c47d626410406f36a4bb6fca40953

I am porting my heightmap module to GDNative, but I noticed many functions of VisualServer are not available, neither in the C++ bindings, nor in GDScript to begin with. A bunch of functions are available, but not those I need:

```
instance_create
instance_geometry_set_material_override
instance_set_scenario
instance_set_visible
instance_set_scenario
instance_set_transform
instance_set_base
...
```

The whole instance API?
They were available in 2.1.4, not in 3.0

**Comment by reduz** [comment]
Probably forgot to bind them. Feel free to do it.

**Comment by Zylann** [comment]
Where should I look for bindings?

**Comment by reduz** [comment]
VisualServer::_bind_methods

**Comment by Zylann** [comment]
I noted that some methods are bound twice, like `draw`, `sync`, `force_draw` and `force_sync`

**Comment by Zylann** [comment]
Can I add all other missing ones? Multimesh, Immediate, Skeleton, Light, Reflection probe, GI probe, particles, camera, environment, scenario

**Comment by eska014** [comment]
I added bindings for some VS functions a while ago. I left comments what's left to do:

https://github.com/godotengine/godot/blob/eb9fa02fbdfe59f8012979f137447dd8026f33b5/servers/visual_server.cpp#L1549

https://github.com/godotengine/godot/blob/eb9fa02fbdfe59f8012979f137447dd8026f33b5/servers/visual_server.cpp#L1582

About `draw` and `sync`, you can remove the bindings missing the `force_` prefix, probably just an oversight of mine

**Comment by Zylann** [comment]
@eska014 why call them "force_*" if the base function isn't call that way though?

**Comment by eska014** [comment]
The `force_` prefix makes these functions sound scarier, so users don't touch them unless they know they really need them
