### ISSUE TITLE
Translations don't work on Android when using keys in non-latin characters

### ISSUE THREAD

**Issue by KylaCpper** [godotengine/godot#15871]
First godot translation can run on android
such as my csv 
key ,zh,en,...
你好,你好11,hello11,...
When I was running on the pc is good
but When I was running on the android is bad
Later I studied for a long time found that the "key" there was a problem
I changed csv to
key,zh,en,..
hello,你好11,hello11,...
He translated successfully on android
How do I use on android  when csv key is chinese
godot 2.1.4
___________________
Sorry, Please forgive my native language is not English

**Comment by bojidar-bg** [comment]
Can you also tell us which version of Godot and which OS do you use?

**Comment by KylaCpper** [comment]
godot   2.1.4
android  5.0.2

**Comment by volzhs** [comment]
what is bad?
does it not translate to chinese or english? or something else?

**Comment by KylaCpper** [comment]
pc is windows

**Comment by KylaCpper** [comment]
it not translate 
display  key （你好 or hello）

**Comment by volzhs** [comment]
can you make a small example project for it?

**Comment by KylaCpper** [comment]
![image](https://user-images.githubusercontent.com/22024916/35162429-4e7186d6-fd7e-11e7-84d2-c8474e01be09.png)
I am sure
when key is chinese its not translate
when key is english its translate
Only on Android

Windows can be

**Comment by KylaCpper** [comment]
It seems I can only change the csv key to english

**Comment by Calinou** [comment]
As stated by the documentation, by convention, you should be using keys written `LIKE_THIS` in English. I doubt international characters are supported anyway.

**Comment by KylaCpper** [comment]
ok，thank you all

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

(Note that we could document this limitation in the meantime.)

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
