### ISSUE TITLE
Editor crashes after a recent GDNative change

### ISSUE THREAD

**Issue by rosshadden** [godotengine/godot#15878]
**Godot version:**

a3937e122094bfb70fb6124fabb261173ecca243

**OS/device including version:**

Arch Linux

**Issue description:**

Starting with a3937e122094bfb70fb6124fabb261173ecca243, both the editor as well as launching a scene directly crashes immediately with the error:

```
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
```

I did a bisect to narrow it down to this commit.

**Comment by karroffel** [comment]
Make sure that you update the headers and recompile any libraries used. Then it should work again.

**Comment by rosshadden** [comment]
@karroffel I had tried that yesterday but tried again just now after building from the latest `master` just in case. It did not fix the issue.

Is there anything I can give you to help?

**Comment by rosshadden** [comment]
@endragor Since I get this with godot-nim, have you run into this, and maybe gotten around it?

**Comment by karroffel** [comment]
@rosshadden this is related to the API struct being updated. If code was compiled using the old API struct definition then the offsets will be wrong and you'll be calling wrong methods.

If you are using godot-nim then that needs an update, if you are using C/C++ then you can just update the headers and recompile.

Sorry for the last-minute breakage, there shouldn't be another one.

There is a way to add new functions to the API struct without breaking compatibility, but I think it's fine to do that until an actual release is published, *then* the non-breaking way will be used. But before that I don't want to clutter the API struct too much before we even released.

So sorry again, but this is a "simple" out-of-date problem.

**Comment by rosshadden** [comment]
Okay sounds good. I'll close the issue when we get it working. I don't mind the breakages at all, and have just been going back to an earlier build for now.

**Comment by akien-mga** [comment]
Closing as it's a downstream bug which needs to be fixed on https://github.com/pragmagic/godot-nim.
@endragor will likely do an update and a new godot-nim release when Godot 3.0-stable is out in a couple days and he knows that the GDNative API will stop breaking.
