### ISSUE TITLE
Allow getting notifaction for Node._Ready() from outside

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15889]
**Godot version:**
`master` / eb9fa02fbdfe59f8012979f137447dd8026f33b5

**OS/device including version:**
_Manjaro Linux 17.1.1_

**Issue description:** (This issue is a feature request)

For now, it's not possible to know when a node enters ready state from outside, unless the node itself override its own `_Ready()` or `_Notification` method and take a proper action to notify outside listeners.

However, it's not always possible to take such an approach, like when one's building a framework which need to take some action when user defined node gets ready, for example.

Adding a signal like `node_ready` to `Node` type could be a solution to such kind of requirements.

**Comment by Zephilinox** [comment]
If a node overrides the _Ready function, what happens to the signal? Does it still get emitted?

**Comment by mysticfall** [comment]
@Zephilinox I think so, because all the life cycle related callback methods (i.e. `_EnterTree()`, `_Ready()`, and so on) have an empty implementation with no actual functionalities, so overriding them do not affect the behavior of the node.

As such, it seems it'd be more reasonable to follow the same rule than making an exception.

**Comment by Zephilinox** [comment]
Working on this now, should have a pull request ready soonish if the feature is wanted.

**Comment by Zylann** [comment]
> However, it's not always possible to take such an approach, like when one's building a framework which need to take some action when user defined node gets ready, for example.

Could you elaborate why you need this? Outside of this theoretical framework issue, I see no use for such signal.

**Comment by mysticfall** [comment]
@Zylann In case you add new nodes programatically, it could be a problem. For example, if you want to create a new node, and need to do some initialization process after the node is attached to the scene tree and gets ready, there's no way to achieve this without modifying the source of the node class in question.

**Comment by Zylann** [comment]
@mysticfall as I said, the node will be ready the line after you add it to the tree. If you need further initialization steps, why not just do them the line after?

**Comment by mysticfall** [comment]
Probably it might be easier if I just explain two use cases for such a feature that I encountered in my project.

1. I made a little DI framework where one can mark an arbitrary node as a 'context' which is a scope for the injection process.

The problem is, as I cannot modify the base class of `Node`, I needed to attach a child node which contains all information regarding the registered dependencies.

In order to make this work, user need to call certain extension method from inside the context node's `_EnterTree()`. I cannot use `_Ready()` because it needs to be done before its descendant were initialized.

And when all the descendant nodes are in ready state, I need to notify them that all dependencies are injected to them, which would ideally be done when the parent node's `_Ready()` is invoked.

But as there's no way to know when it happens, I needed to require users to override `_Ready()` also and manually invoke another extension method, which is quite cumbersome and better be avoided.

2. I also wrote an API with which you can access various callback methods as `IObservable<T>` by writing extension methods which automatically add a child node to process these events.

It's especially problematic for `_Ready()` because child node's `_Ready()` is invoked before its parent's method, thus it's impossible to take the same approach in this case.

I admit it could be quite a corner case. But when we already have such signals for `tree_entered`, `tree_exited`, it might be better if we also provide a similar signal for the ready event which can also solve such corner case problems like the ones I have.
