### ISSUE TITLE
Unable To Remove Gridmap

### ISSUE THREAD

**Issue by TritiatedWater** [godotengine/godot#15883]
**Godot version:**
eb9fa02

**OS/device including version:**
Manjaro Linux

**Issue description:**
Unable to remove gridmap with right click. Cursor instead moves to center.

**Steps to reproduce:**
Open Platformer 3d demo.
Select gridmap from Inspector.
Add gridmap with left click (works).
Remove Gridmap with right click (failes).

**Comment by akien-mga** [comment]
I believe the hotkey for deletion was changed to Shift+Left Click in 3.0, as Right Click is used by freelook.

**Comment by Supatier** [comment]
Shift+Left Click selects the gridmap and clear selection removes it. Thanks!
(someone needs to update the docs for godot 3.0 :)

**Comment by Supatier** [comment]
Have the docs been updated?

**Comment by akien-mga** [comment]
> Have the docs been updated?

I don't know, can you point to the docs you were referring to?
