### ISSUE TITLE
Better handling of nested exceptions in error console (C#)

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15886]
**Godot version:**
`master` / eb9fa02fbdfe59f8012979f137447dd8026f33b5

**OS/device including version:**
_Manjaro Linux 17.1.1_

**Issue description:**

In C#, an exception can be triggered by another root cause, in which case the latter can be referenced by `Exception.InnerException` recursively.

Often, the most relevant information of the problem can be found at the last part in such an exception chain, but as Godot displays only the outermost exception, it's very difficult to find out what actually went wrong in that case.

For example, Godot will show the following information when any problem occurs during a method invocation via reflection, regardless of its actual cause:
```
0:00:00:0933 - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
```

Rather, it should follow the exception chain and display details of each exception, preferrably  in a hierarchical manner.

**Comment by neikeq** [comment]
Fixed by #16981
