### ISSUE TITLE
Missing NativeScript entry in inspector->new ressource 

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#15884]
Following #15099 and #15863, all Ressource inheriting from `Script` has been removed from the `Inspector` -> `New resource` dialog box.
As @vnen [mentioned](https://github.com/godotengine/godot/pull/15863#issuecomment-359137026), this is wrong because using this dialog box is the way to create new `NativeScript` according to the [GDNative tutorial](http://docs.godotengine.org/en/latest/community/tutorials/gdnative/gdnative-c-example.html#creating-our-gdns-filel)

The solutions I see to solve the trouble:
- blacklist style: only hide the `PluginScript` node in the dialog box (given it's the one which cause the segfault)
- whitelist style: only show `NativeScript`. Obviously we should also check all the `Script` children to make sure no other class needs to be exposed to the user.

I would be more willing to go whitelist style given it seems creating a Script this way [is more the exception than the rule](https://github.com/godotengine/godot/issues/15099#issuecomment-358696103)

**Comment by karroffel** [comment]
I think hiding PluginScript should be enough

**Comment by touilleMan** [comment]
so be it :smile:

**Comment by MarianoGnu** [comment]
i had the feeling that this was going to happen with GdScript, C# and VS but didn't think of NativeScript xD
