### ISSUE TITLE
Why is RigidBody2D's friction clamped to 0.0 to 1.0?

### ISSUE THREAD

**Issue by jtaart** [godotengine/godot#15893]
Godot version: Godot_v3.0-rc1

Godot allows you to go and raise the friction much higher if you us Physics2DServer. Why is it clamped in the node?

**Comment by madmiraal** [comment]
The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older issues that are not bugs on the main issue tracker.

If you are interested in developing this into a feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
