### ISSUE TITLE
Inconsistent call syntax between languages

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#15894]
**Godot version:** `master` / 09732a1

**OS/device including version:** *Linux Mint 18.2 + Cinnamon 3.4.6*

**Issue description:**
Currently the process of calling functions in scripts defined in several languages is inconsistent.
If I have 3 Nodes with a script attached (`GDScript`, `CSharp` and `VScript`) and a function `foo` defined in each, I can do (commented lines show impossible options):

* From GDScript
```GDScript
GDScript.call("foo")
GDScript.foo()
CSharp.call("foo")
CSharp.foo()
VScript.call("foo")
# VScript.foo()
```

* From CSharp
```C#
GDScript.Call("foo");
// GDScript.foo();
CSharp.Call("foo");
CSharp.foo();
VScript.Call("foo");
// VScript.foo();
```

* From VScript, I guess it does not apply.

Not sure it would be that easy to totally skip the `.Call(...)` syntax in C#, but it sure is weird not being able to call directly  VisualScript functions from GDScript when it's possible with C# methods.

**Comment by paulloz** [comment]
This seems handled by #27497 IINW (at least between C# and GDScript).

**Comment by Calinou** [comment]
Closing, as the base feature seems to be handled now. If you still need something else to be added, please open a proposal on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.
