### ISSUE TITLE
Saving shortcut ALT+S, CTRL+S

### ISSUE THREAD

**Issue by qubodup** [godotengine/godot#159]
Hello,

I am a Linux user. Sometimes I use Windows 8.1. I nearly never use OS X. I have very little experience with Godot so far.

When writing scripts in Godot, I hit CTRL+S to save, which raises an "Alert! This operation can't be done without a tree root. - I see.." message.

Through the menu, I learned that ALT+S is the correct shortcut. This is uncommon. As far as I can tell, any Windows and Linux user would expect CTRL+S and any OS X user would expect CMD+S to be the shortcut.

It seems that other common shortcuts use CTRL (+F = search), so it seems like CTRL+S should be save, not ALT+S.

**Comment by akien-mga** [comment]
Well actually Ctrl+S is already used to save the scene, so it can't be used to save the script only. On the other hand saving the scene will also save all modified scripts. The shortcut to save the script only is Ctrl+Alt+S.

So I don't think there's an easy fix here unless a whole redesign of the hotkeys is worked on.
