### ISSUE TITLE
Skeleton with many bones deform sprites

### ISSUE THREAD

**Issue by jebedaia360** [godotengine/godot#15901]
**Godot 3.0 RC 1:**

**OS/device including version:**
Ubuntu 16.04.3

**Issue description:**
I have rig tail and when I try to move it a lite in editor some last part are scaled.
![zaznaczenie_006](https://user-images.githubusercontent.com/1294815/35187236-eeb75be6-fe20-11e7-8a47-990fb91081e3.png)
![zaznaczenie_007](https://user-images.githubusercontent.com/1294815/35187235-ee981e34-fe20-11e7-9d43-162ba34fdaef.png)

**Steps to reproduce:**
I just crate long 2d skeleton with IK from many bones on 2d sprites and drag some bones.

**Minimal reproduction project:**
[skeleton_bug.zip](https://github.com/godotengine/godot/files/1649213/skeleton_bug.zip)

**Comment by willnationsdev** [comment]
might wanna rename this to "deform" rather than "defrome".

**Comment by Calinou** [comment]
@jebedaia360 Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by jebedaia360** [comment]
@Calinou I will try, but I don't have original project with this bug anymore.

**Comment by jebedaia360** [comment]
@Calinou I just try and bug don't seems to occur anymore in godot 3.2.1
