### ISSUE TITLE
Resource preloading does not work after export due to converted paths (regression from 67ae443)

### ISSUE THREAD

**Issue by Nobelix** [godotengine/godot#15902]
**Godot version:**
3.0 RC2

**OS/device including version:**
Ubuntu 16.04
Firefox

**Issue description:**
Can't collect coins in any export of the plat-former demo.
**Steps to reproduce:**
Export the platformer demo, play it, notice you can't collect coins.

**Comment by x1212** [comment]
This seems to happen to all projects where signals are connected from the editor.
From the output it looks like the scripts the signals get connected to don't exist (aren't loaded) at the time godot tries to connect them:

`**ERROR**: **SCRIPT ERROR**: Parse Error: Can't preload resource at path: res://player.gd
**ERROR**:    At: res://coin.gdc:9:GDScript::load_byte_code() - Parse Error: Can't preload resource at path: res://player.gd
**ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
**ERROR**:    At: modules/gdscript/gdscript.cpp:764:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
**ERROR**: Condition ' err != OK ' is true. returned: RES()
**ERROR**:    At: modules/gdscript/gdscript.cpp:1848:load() - Condition ' err != OK ' is true. returned: RES()
**ERROR**: Failed loading resource: res://coin.gdc
**ERROR**:    At: core/io/resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
**ERROR**: **SCRIPT ERROR**: Parse Error: Can't preload resource at path: res://player.gd
**ERROR**:    At: res://coin.gdc:9:GDScript::load_byte_code() - Parse Error: Can't preload resource at path: res://player.gd
**ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
**ERROR**:    At: modules/gdscript/gdscript.cpp:764:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
**ERROR**: Condition ' err != OK ' is true. returned: RES()
**ERROR**:    At: modules/gdscript/gdscript.cpp:1848:load() - Condition ' err != OK ' is true. returned: RES()
**ERROR**: Failed loading resource: res://coin.gdc
**ERROR**:    At: core/io/resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
**ERROR**: **WARNING**: Couldn't load external resource: res://coin.gd
**ERROR**:    At: scene/resources/scene_format_text.cpp:174:_parse_ext_resource() - Couldn't load external resource: res://coin.gd
**ERROR**: Error calling method from signal 'body_entered': 'Area2D::_on_coin_body_entered': Method not found.
**ERROR**:    At: core/object.cpp:1202:emit_signal() - Error calling method from signal 'body_entered': 'Area2D::_on_coin_body_entered': Method not found.
**ERROR**: Error calling method from signal 'body_entered': 'Area2D::_on_coin_body_entered': Method not found.
**ERROR**:    At: core/object.cpp:1202:emit_signal() - Error calling method from signal 'body_entered': 'Area2D::_on_coin_body_entered': Method not found.
**ERROR**: Error calling method from signal 'body_entered': 'Area2D::_on_coin_body_entered': Method not found.
**ERROR**:    At: core/object.cpp:1202:emit_signal() - Error calling method from signal 'body_entered': 'Area2D::_on_coin_body_entered': Method not found.`

the `Error calling method from signal 'body_entered': 'Area2D::_on_coin_body_entered': Method not found` happen every time an area with is entered.

**Comment by eska014** [comment]
This is not platform-specific, happens on all exports

**Comment by Nobelix** [comment]
@eska014 Sorry my bad, I'm just obsessed with html 5..

**Comment by x1212** [comment]
Ok, looks like it can be fixed by reverting 67ae443c5696b96590ca4c32cb2828692e805b73 .
But I guess that would lead to issues with autocompletion (according to the commit message) ...

**Comment by akien-mga** [comment]
> Ok, looks like it can be fixed by reverting 67ae443 .

CC @poke1024. This is buggy on exports as the paths are changed (resources are converted to different formats, .tscn can be converted to .scn, etc.). I think there's a method available to get the remapped paths, but might be worth double-checking this fix again and see if it's the right approach.

At any rate, we need a RC3 for sure...

**Comment by reduz** [comment]
I guess we should probably make a ResourceLoader::is_valid(path)

**Comment by reduz** [comment]
actually no.. that test should also be within a for_completion check

**Comment by drezgames** [comment]
Uhg.... I just started using Godot and got enough working to actually be a thing.. haha. I was just playing around with it get_tree().change_scene()... now crashes on export. Is there a work around I can use in the mean time? stay with rc1? please advise.

**Comment by LinuxUserGD** [comment]
So there won't be a patch for the RC2 export templates?
@drezgames You can compile the export templates from source for your native platform

**Comment by akien-mga** [comment]
Use RC1 if you need to export *now*. Building from source won't change anything until this bug is fixed.

**Comment by x1212** [comment]
While debugging this to see if it can be solved by adding `(!for_completion) || ` to the `else if` I saw something that might be a problem as well.
When validating the gdscript GDScriptLanguage::validate() calls GDScriptParser.parse() setting the p_just_validate argument to true but parse() calls _parse() which calls clear(), resetting the validating member of GDScriptParser.
This leads to those lines being run and printing errors, when they probably shouldn't be run as they are inside an `if (!validating)` block.

**Comment by poke1024** [comment]
@x1212 I had the same `!for_completion || ...` and saw that it didn't work, but your finding that `p_just_validate` is wrong makes sense.

So we'd need the `!for_completion || ...` condition together with the `p_just_validate` fix to prevent the spurious error messages I guess. Would you prepare a PR? Would be nice for 3.1 I guess.

**Comment by x1212** [comment]
Created the PR and added a comment on the line that I'm not so sure about.
