### ISSUE TITLE
OS.execute not writing output to array on linux?

### ISSUE THREAD

**Issue by mephiticstudios** [godotengine/godot#15912]
**Godot version:**
3.0 RC1

**OS/device including version:**
Ubuntu Linux

**Issue description:**
I created a empty array to hold the results and used the OS.execute function to run a bash command (ls). My understanding is that the output array you pass into the function call should be populated with the output of the command executed. The function itself returns a PID correctly, but the output array remains blank.

 Its possible I'm not understanding exactly the right way to do this but 

Execute a command using OS on linux that should return some value

**Comment by akien-mga** [comment]
I also had a similar issue, but didn't have the time to check if it's due to misunderstanding what this `ouput` argument is meant to do, or if it's an actual bug.

**Comment by brainsick** [comment]
This works for me:

```
var output = []

var pid = OS.execute('ls', [], true, output)
print('pid: ', pid, ' output: ', output)
```

```
pid: -1959160320 output: [default_env.tres
icon.png
icon.png.import
Main.gd
Main.tscn
project.godot
]
```

**Comment by TierraDelFuego** [comment]
> Just to clarify, ls in this instance refers to /bin/ls and not a Bash built-in.

This clarity is important and could be why @mephiticstudios was not able to get it to work. It's also a better practice to include a full path to the executable. Explicit is better than implicit.  

`var pid = OS.execute('/bin/ls', [], true, output)`

**Comment by akien-mga** [comment]
Documentation improved by #15917, so closing. Please comment if you still can't retrieve the output using the provided example.
