### ISSUE TITLE
Support custom external editors for Mono

### ISSUE THREAD

**Issue by redxdev** [godotengine/godot#15913]
The external editor option for mono currently only supports MonoDevelop and VS Code. I suggest an additional option, where it will let you enter a command to execute to open an editor. This probably would require a "Custom Editor" option in the dropdown, and an additional field to enter the path to the editor.

The custom editor option would probably also need to support some form of formatting string in order to feed the file path (and line number?) to the command.

As an example, if I want to use Visual Studio:

    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe" /Edit %s

Where `%s` would be replaced by the filepath.

**Comment by neikeq** [comment]
I'm not sure if we should add a Mono-only custom external editor option, since you can use the language-agnostic one.
I plan to add support for opening scripts with Visual Studio via the DTE interface. The command line is very limited.

**Comment by redxdev** [comment]
I completely forgot about the language-agnostic setting. And good to hear that VS support is planned.

That said, maybe it's worth discussing anyway - a separate editor for Mono vs gdscript does make sense (you might not want to open gdscript files in Visual Studio, for example) so if the mono editor setting is staying, I think it still would warrant having a custom editor option.

**Comment by mysticfall** [comment]
I'm already using _Rider_ to develop a Godot project, and found it working great.

But I was also a bit confused at first to see that it only lists `VS Code` and `MonoDevelop` as viable options before I realized there was another option I could use.

Maybe we may consider changing the labels to prevent users from thinking it was impossible to use other editors.

**Comment by Rinma** [comment]
I use Rider too but I tried VS Code and I like the synchronization between Godot and the external editor. So I think a config field for custom editor settings would be a nice option only when it means that Godot will sync/talk to the custom external editor like it does with VS Code.

**Comment by MightyPrinny** [comment]
I would like to have a separate external editor option for mono because currently I have to deactivate the external editor whenever I want to do something in gdscript.

**Comment by Kowbell** [comment]
> Maybe we may consider changing the labels to prevent users from thinking it was impossible to use other editors.

I definitely agree with this. It took me a second to figure out that the "Disabled" option for `Editor Settings > Mono > Editor > External Editor` actually means "Use language-agnostic editor specified in Text Editor setttings." I'm not sure what would be the better text for this entry...  "Default"? "Language-Agnostic"? "Same as GDScript"?

> I'm not sure if we should add a Mono-only custom external editor option, since you can use the language-agnostic one.

Conversely, it seems inconsistent that the user can specify a custom external editor path and flags for GDScript/language-agnostic editing but they only have a drop-down list of preset options for Mono.

**Comment by AldieNightStar** [comment]
Please! Add VS2019 !!!

**Comment by Calinou** [comment]
@AldieNightStar Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by raulsntos** [comment]
- Custom external editor support was added in `4.1`.
	- https://github.com/godotengine/godot/pull/74517.
- Visual Studio 2019 support was added in `4.0` and `3.2`.
	- https://github.com/godotengine/godot/pull/39578.
	- https://github.com/godotengine/godot/pull/39784.
- Visual Studio 2022 support was added in `4.0` and `3.5` and `3.4.3`.
	- https://github.com/godotengine/godot/pull/57609.
