### ISSUE TITLE
Glow gives artifact line - bug

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#15926]
**Godot version:**
Godot_v3.0-rc2_win64

**OS/device including version:**
OS Win 8.1 64b, AMD R7 200 series 

**Issue description:**
When enabling Glow -> Level 7, gives artifact line.
See the vid: https://www.youtube.com/watch?v=W_0dlB10nD8&feature=youtu.be

**Comment by Akira1San** [comment]
Ive noticed that the line is actually a rectangle, that shows around the glow areas. When switching the levels different rectangles show up.

**Comment by bojidar-bg** [comment]
Seems related to #15756.

**Comment by Akira1San** [comment]
Thanks bojidar-bg. The Roughness value after the export was wrong.
Image: http://pasteall.org/pic/index.php?id=123483
Issue solved.
