### ISSUE TITLE
Particles shader cannot be compiled on Adreno due to a large number of uniforms

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#15927]
**Godot version:**
3.0 rc1

**OS/device including version:**
Samsung Galaxy J5 (Adreno 306 GPU)

**Issue description:**

On Adreno 306 you get this when using Particles:
```
**ERROR**: ParticlesShaderGLES3: Program LINK FAILED:
--From Vertex Shader:
Error: uniform variables in vertex shader do not fit in 256 vectors.
--From Fragment Shader:
Error: uniform variables in vertex shader do not fit in 256 vectors.
```

This seems to be due to `uniform Attractor attractors[MAX_ATTRACTORS];`, where `MAX_ATTRACTORS` is hardcoded to be `64`. And at the same attractors are **not actually used** in the shader (their logic is wrapped into `if (false)` and `attractor_count` is always passed as `0`). So perhaps it makes sense to remove/comment out the related logic for 3.0?

As a side note, such large arrays hurt shader compilation performance, especially on older devices. So I think it always makes sense to move constants such as MAX_ATTRACTORS into project settings.

**Steps to reproduce:**
Use a Particles node and launch the game on Adreno 3xx device.

**Comment by eon-s** [comment]
Looks related to other Adreno issues #12816 and #14951 

3.1 will bring back CPU particles, it seems, hopefully that will make things work again on Adreno devices...

**Comment by endragor** [comment]
Not too related though. In this case it happens because the shader has code that is not used, so the fix here is easy and safe.

**Comment by rafaelpontes** [comment]
Just to give **updated feedback**: I faced this very same problem trying out Godot version 3.0.6 and trying out the generated app on a **Samsung Galaxy Note 8**! Everything in the game works just fine. The **particles** are the only thing that **don't spawn** on the scene. :/

**Comment by rafgp** [comment]
Just to give **updated feedback**: I faced this very same problem trying out Godot version 3.0.6 and trying out the generated app on a **Samsung Galaxy Note 8**! Everything in the game works just fine. The **particles** are the only thing that **don't spawn** on the scene. :/

**Comment by eon-s** [comment]
@rafgp that is Adreno 540, another one of the reported with issues.

**Comment by KoBeWi** [comment]
3.1 did re-introduce the CPUParticles, so using GLES2 fixes this issue.
