### ISSUE TITLE
Some issues caused by #15825

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15921]
**Godot version:**
c58891f

**Issue description:**
There where some issues that #15825 caused:
- The close button now stays centered, and its click area consumes the entire bar vertically:
**Before:**
![screenshot1](https://user-images.githubusercontent.com/30739239/35189748-d75155d4-fe38-11e7-84cf-cb67f46ae216.png)
**After:**
![screenshot3](https://user-images.githubusercontent.com/30739239/35189749-d96fcaee-fe38-11e7-8256-2a637e099913.png)

- The separation between the bar and the text editor is thinner now:
**Before:**
![screenshot2](https://user-images.githubusercontent.com/30739239/35189754-fde0e55c-fe38-11e7-9b82-9749347079eb.png)
**After:**
![screenshot4](https://user-images.githubusercontent.com/30739239/35189755-01c6344c-fe39-11e7-8758-1fd6e2d35e11.png)

**Comment by volzhs** [comment]
the first one about click area has always been like that.

**Comment by YeldhamDev** [comment]
@volzhs No, it hasn't. Using a build from 3 days ago (b101726).

**Comment by akien-mga** [comment]
There's no hurry, it's too late to change this for 3.0 anyway.
