### ISSUE TITLE
Godot 3.0 instantly crashes when creating a new C# script with Mono 4

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#15923]
**Godot version:** 3.0 rc2 (with Mono)

**OS/device including version:** Linux - Xubuntu 16.04 LTS 64-bit, Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4) (the version from the Ubuntu repos via `mono-complete`)

**Issue description:** I tried to create a new C# script. Instead, it just crashes Godot instantly.

**Steps to reproduce:** On any object, Node -> Script -> New Script -> C# -> Create, instant crash. 

**Minimal reproduction project:** [TestingGodot.zip](https://github.com/godotengine/godot/files/1649519/TestingGodot.zip)

STDOUT, STDERR, and godot/mono/mono_logs Logs: [mono_logs.zip](https://github.com/godotengine/godot/files/1649520/mono_logs.zip)

**Comment by akien-mga** [comment]
Mono 4.2.1 is likely too old for Godot, which is built against Mono 5.4.1 (current stable) and likely requires at least a 5.x version for compatibility.

A workaround would be to install the latest Mono using the upstream PPA for Ubuntu (removing before the mono-complete metapackage and its deps): http://www.mono-project.com/download/

Regardless, we need to check the version of the Mono SDK Godot will try to use, and prevent using it if it's older than a version to be determined (5.0?). @neikeq

**Comment by aaronfranke** [comment]
Unfortunately, Ubuntu 18.04 will be shipping with Mono 4.6. This is still lower than Godot requires, so users of Ubuntu 18.04 and Ubuntu flavors will be stuck with an outdated version of Mono unless they manually add the Mono repo from the Mono project.

A warning when trying to use an outdated Mono version would still be a good idea.

**Comment by exts** [comment]
@aaronfranke is this still the case with 3.1 beta & 3.0.6 stable?

**Comment by akien-mga** [comment]
Mono is now distributed with the Godot binaries, so it should no longer be a problem.
