### ISSUE TITLE
Editor: any Particles2D instance makes update wheel spin constantly

### ISSUE THREAD

**Issue by poke1024** [godotengine/godot#15932]
**Godot version:**
At least Godot 3.0 beta 2 and up (including RC2)

**OS/device including version:**
macOS

**Issue description:**
In the 2d/platformer demo (which has some nested particles instances), the editor's update wheel (right top) constantly spins.

The constant updates are caused by `VisualServerRaster::redraw_request();` inside `case Item::Command::TYPE_PARTICLES:` in `RasterizerCanvasGLES3::_canvas_item_render_commands`. Note that actually no particles are animating anywhere. 

I wonder if the whole "animate Particles in the editor" features should get an option for disabling it.

**Steps to reproduce:**
Open the official 2d/platformer demo.

**Minimal reproduction project:**

**Comment by vnen** [comment]
This is not really a bug, see #15355. Essentially the particle system is always running, even if there's no particles, because some particles might still be visible even after it stops emitting.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
