### ISSUE TITLE
Scrolling up/down while mouse if over viewport closes foreground dialogs

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#15937]
**Godot version:**
Current master (https://github.com/godotengine/godot/commit/fa569210f5ef316177724169a42d2b82f4ab03d9)

**OS/device including version:**
Windows 7 x64

**Issue description:**
Scrolling up/down using the mouse may close the foreground dialog unexpectedly if the mouse cursor hovers over the viewport in the background by accident.

Because scrolling may be used in dialogs containing long lists (e.g. settings), this can be quite annoying.

While a foreground dialog is opened, other parts of the UI should be disabled for input and shouldn't accept things like scroll events.

**Steps to reproduce:**
1. Open dialog (About or Settings for example)
2. With the dialog still focused, move the mouse cursor over the viewport in the background
3. Scroll up or down
4. The dialog closes

**Minimal reproduction project:**
![close](https://user-images.githubusercontent.com/1654763/35193840-408d4376-fea9-11e7-9dbd-94cad0a588bc.gif)

**Comment by icnikerazah** [comment]
sometimes i click background accidently and dialog closes. there is a meaningless close button on the dialogs.

**Comment by vnen** [comment]
Old issue, this is a duplicate of #6453. It's related to all popups, not only the editor,
