### ISSUE TITLE
"Change Type" no Changed * on Scene Tab 

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#15936]
Godot Master

![peek 2018-01-21 12-27](https://user-images.githubusercontent.com/4741886/35193708-fcecd494-fea6-11e7-9ae3-a0c968cb030c.gif)

Scene Tab is not showing the * sign.
Undo "Change Type" is also not working.

https://github.com/godotengine/godot/blob/35700921f82d72525555947866ff283f833fee7d/editor/scene_tree_dock.cpp#L1699

**Comment by Amssat221** [comment]
Seems like it's not happening anymore

**Comment by akien-mga** [comment]
Closing as fixed in 3.1.
