### ISSUE TITLE
Can't load scene directly from bundled .app on macOS

### ISSUE THREAD

**Issue by leolimasa** [godotengine/godot#15930]
**Godot version:**
3.0 RC 2

**OS/device including version:**
macOS Sierra 10.12.6
Mono JIT compiler version 5.4.1.7

**Issue description:**
When using RC 2 with mono on macOS, clicking the "play" button does not launch the game. When running the project through the terminal, an error is shown:

<img width="892" alt="screen shot 2018-01-21 at 3 09 55 am" src="https://user-images.githubusercontent.com/523280/35192473-b208ed30-fe58-11e7-828b-26c0edf5e505.png">

If I use Godot 3.0 RC 2 classic, it works flawlessly.

The project is nothing special: just the Godot icon. There are no C# scripts on any nodes.

**Steps to reproduce:**
Attempt to run the project

**Minimal reproduction project:**
[MonoSandboxRc2.zip](https://github.com/godotengine/godot/files/1649636/MonoSandboxRc2.zip)

**Comment by bruvzg** [comment]
macOS 10.13.2 (17C205)
Mono 5.4.1.7 (2017-06/e66d9abbb27)

Attached project (full project and `icon.tscn` opened directly) works with both Mono and Classical RC2.

**Comment by leolimasa** [comment]
I wonder if it's the OS version. I'll upgrade and see if that fixes it. I also wonder what that terminal error message means.

**Comment by bruvzg** [comment]
> I wonder if it's the OS version

Got same error on OSX 10.9.5 (13F34), with both Mono and Classical (opening full project works, opening `icon.tscn` doesn't).

**Comment by akien-mga** [comment]
CC @BastiaanOlij @endragor - seems quite important to fix ASAP if Godot is buggy on macOS < 10.13.

**Comment by cbscribe** [comment]
Opens fine for me on 10.12.6, both with and without mono.

**Comment by leolimasa** [comment]
Upgraded to 10.13.2 and main scene now works. Does seem to be something to do with the OS.

**Comment by BastiaanOlij** [comment]
Same here, I am having no issues on 10.12.6 though admittedly I haven't stress tested anything lately... I'll try and do some more tonight when I'm back home

**Comment by BastiaanOlij** [comment]
(oh mono, I haven't tested anything with mono... should the icon be a tscn file though?)

**Comment by bruvzg** [comment]
Reproduced same error on 10.13.2 as well, it is not related to OS version.

Only bundled executables are affected, and only when you try to load scened directly.

Bundle change current working directory to its `/Contents/Resources/` and try to load `.tscn` from there.

I did not get it on 10.13.2 first time because I was starting Godot using relative path with ".." in it - `../../Godot.app/Contents/MacOS/Godot ./icon.tscn` and in this case current working directory is NOT changed for some reason.

**Comment by akien-mga** [comment]
Thanks for checking, given the actual reproduction steps it doesn't seem that critical in the end.

**Comment by bruvzg** [comment]
`/Contents/Resources/` working directory change is useful only for export templates and should be disable for tools.

**Comment by neikeq** [comment]
@reduz This issue doesn't happen with mono builds only.
