### ISSUE TITLE
Add an InputMap-like ColorMap

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#15944]
**Godot version:**
Godot 3.0 RC2

**Issue description:**
After reviewing some data on ways to improve accessibility in games for audiences with color blindness, I imagine it might make things easier for developers to allow them to easily swap color palettes in their games by creating a global map of colors where a given use case is assigned a label and a color. If you swapped which label was active, you could switch all colors in the color map to use that label's color, thereby making it easier for artists and developers to keep track of color palettes directly (and easily create color-blind compatible palettes for their games).

**Steps to produce:**
Replicate the InputMap functionality, but instead of actions and inputs, you would create use-cases and labels mapped to colors (the difference being only one label is active at a time whereas the InputMap has them all active at once).

**Comment by groud** [comment]
Just creating a screen shader for that should be enough. You can have millions of colors in a game, a color map will always be less efficient than a screen shader.

**Comment by willnationsdev** [comment]
Closing this since it's an unnecessary concept with better alternatives.
