### ISSUE TITLE
OS.alert modal box not taking title string size into account on X11

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#15940]
**Godot version:**
3.0rc2 build fa56921. That said, this issue is **much** older than this.

**OS/device including version:**
Ubuntu Linux 17.10 64-bit.

**Issue description:**
`OS.alert` modal boxes don't appear to take into account the length of the title string when being created, thus appearing cut-off.

i.e. ![alert_window_not_sized_properly](https://user-images.githubusercontent.com/324679/35194097-52fb2694-fea5-11e7-8e6f-d2ba9d51748f.png) - `OS.alert ("Debug mode is ENABLED", "DEBUG BUILD")`

This issue is X11 only.

**Steps to reproduce:**
Use OS.alert to create a modal box.

**Comment by TierraDelFuego** [comment]
I see the same problem on git master. I tried to alter 
`~/.Xresources` 
by using
`xwininfo`
on the modal dialog and then 
`xrdb -merge ~/.Xresources`
I also tried 
`OS.set_window_size(Vector(modalsizex,modalsizey))`

But that set the window size of my "hola mundo" godot app window.

So is the problem that OS.set_window_size is setting the size of the wrong window?
I might peek at the code.

**Comment by vnen** [comment]
> OS.set_window_size is setting the size of the wrong window?

Godot does not have a concept of multiple windows, the alert dialog is a feature of the OS, and not a window spawned by Godot. Also, AFAIK the alert blocks the main window while it's open, so you can't really call any function until it's closed.

**Comment by Sslaxx** [comment]
Wouldn't say it _solves_ this, but #21382 does at least ameliorate this issue to being mostly non-relevant by offering other options for displaying alert boxes with X11, so closing it.
