### ISSUE TITLE
x11 aarch64 (bad) patch

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#15948]
Hi,

I've made a little patch for compiling godot on aarch64. Tried on NVIDIA Jetson-TX1 devboard running Ubuntu 16.04 LTS.
I'm not a programmer, just a 3d artist with some programming knowledge. As thus, this patch may broke 
other arch.

[godot-3.0-rc2-aarch64.patch.gz](https://github.com/godotengine/godot/files/1649971/godot-3.0-rc2-aarch64.patch.gz)

**Comment by vnen** [comment]
Thanks for your contribution, but the way you are providing it makes it very hard to review the code. We have a very comprehensive guide showing [how to make a Pull Request](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html), which you should do when contributing with code.

Feel free to ask for guidance if you need help with some step.

**Comment by arcangeli** [comment]
I'll do that soon.
Thanks for your help

**Comment by akien-mga** [comment]
Closing as superseded by #17197.
