### ISSUE TITLE
Add hard-to-miss info in Mono binaries pointing that they're WIP / alpha

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#15956]
**Godot version:**
Current master, Mono build (37cb029f)

**Issue description:**
The Mono builds as of 3.0 will be released with various known issues, including crashes, and no support for exporting projects. It's fine as there's still a lot that can be done with them already, and the additional feedback from new users will help shape it further.

Still, tons of users will get started with Godot using this version, and might be put off if it's lacking features and crashing on them.

So we need to make it crystal clear both in our public communication AND in the editor itself that the C# support as of 3.0-stable is in ~~*beta*~~ *alpha* stage, and that bugs and missing features are to be expected.

It could be a big warning sign with explanations on the project manager (only for the Mono flavour of course) and/or a popup message when opening a first project with 3.0 giving explanations about the state of the Mono build (with option not to show this message again).

**Comment by aaronfranke** [comment]
The term "Beta" implies feature-completeness. As exporting is not available, it is not feature-complete.

**Comment by mhilbrunner** [comment]
Have to agree with @aaronfranke, as long as project with C# can't be exported and projects aren't synced and need to be edited by hand on changing/renaming/moving files, I'd call it "alpha", not "beta".

**Comment by NathanWarden** [comment]
I agree with @aaronfranke too, it should be considered alpha until it's feature complete or in some shippable form. For instance, if it could export to at least standalones I think it could be considered beta.

**Comment by NathanWarden** [comment]
With that said, I obviously agree with @akien-mga that the messaging should be clear that it isn't in shippable form yet. :)

**Comment by akien-mga** [comment]
I'm working on adding an opt-out popup when you start the editor with information about the state of the C# support:
![spectacle bc7947](https://user-images.githubusercontent.com/4701338/35220823-11b93238-ff78-11e7-9f4d-059b32855aa3.png)

What's missing is to find out how to get it shown in the editor once it finished initialising (I declare it in the Mono module and at that time EditorNode is not ready to show stuff yet), and fix that super tiny icon (currently using `get_icon("NodeWarning", "EditorIcons")`, @djrm any idea how I could get that SVG in 64x64 instead of 16x16?).

**Comment by akien-mga** [comment]
> Looks fine besides the things you mentioned, but I'd drop "frequent" and change "in future releases" to "soon".

OK to drop "frequent", but changing "in future releases" to "soon" sounds like not committing to anything, since "soon" could be "in the next 18 months" (just like Godot 3.0 was coming soon™ at the end of 2016).

**Comment by mhilbrunner** [comment]
Haha, maybe thats jus a opinion/feeling thing then... for me it's the opposite, "soon" is vague but sounds like more of a commitment than "in future releases" to me. Maybe "in one of the next releases"?

Not really that important though.

**Comment by akien-mga** [comment]
Well let's commit to "in 3.0.1", and if @neikeq doesn't implement it by then we'll burn him an the stake. 🔥

**Comment by NathanWarden** [comment]
@akien-mga Thanks Remí, I think this notice is perfect and very clearly sets user expectations.
