### ISSUE TITLE
Rigidbody2d pass through each other

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15958]
**Godot version:** godot 3.0 rc2

**OS/device including version:** macOS sierra

**Issue description:**

![untitled3](https://user-images.githubusercontent.com/33985414/35201644-2ab38f1c-ff2e-11e7-9f83-8fdda978aaef.gif)

**Steps to reproduce:**
open the following project and click to create the rigidbody2d stack.

**Minimal reproduction project:**

[New Game Project.zip](https://github.com/godotengine/godot/files/1650444/New.Game.Project.zip)

**Comment by reduz** [comment]
This depends on the shape code, I will rewrite this code for 3.1

**Comment by vnen** [comment]
This is an old issue, duplicate  of #2092.
