### ISSUE TITLE
sqrt with negative numbers return NaN

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#15954]
**Godot version:**
3 beta - custom build - git id 00387cbe1b05c6093baea76d6852af18842c0f65

**OS/device including version:**
Linux Ubuntu

**Issue description:**
negative numbres in sqrt raise NaN

**Steps to reproduce:**
print(sqrt(-1.0))

**Comment by mysticfall** [comment]
Isn't it how it's supposed to do? What could be the result of `sqrt(-1.0)`?

**Comment by mhilbrunner** [comment]
https://math.stackexchange.com/questions/677619/why-is-the-square-root-of-a-negative-number-impossible
