### ISSUE TITLE
CubeMesh bottom face issue

### ISSUE THREAD

**Issue by brainsick** [godotengine/godot#15952]
**Godot version:**
Godot 3.0 RC2

**OS/device including version:**
Ubuntu 17.10 x64

**Issue description:**
I was writing a basic vertex shader for the cube when I noticed that the bottom of the cube is different than the other faces.

![screenshot from 2018-01-21 13-57-18](https://user-images.githubusercontent.com/1111573/35198336-0492ef56-feb3-11e7-8a48-da3e441d8799.png)

**Steps to reproduce:**
Add a cube, turn on Wireframe, and wonder at the disparity.

**Minimal reproduction project:**
https://youtu.be/tjdsqMIdrwg

I get the same results with the CylinderMesh and PrismMesh.

**Comment by BastiaanOlij** [comment]
@brainsick what difference are you referring too? other then the face being in shadow (though there is no proper lighting setup so I'm guessing its purely getting the color from the sky which would reflect the ground which is indeed black, I'm not sure whats wrong :)

**Comment by brainsick** [comment]
Notice that at run time (the corresponding video) the bottom face is absent entirely.

**Comment by BastiaanOlij** [comment]
The video still just shows the bottom in black which could still have the same problem. Try adding a rotation to see if the face shows correctly when it actually has light from the sky hitting it.

I don't know how complex your vertex shader is but if you're only repositioning the vertices both the normal and bitangent will remain asif the faces belong to a flat cube. Normals are not recalculated unless you specifically write code for that in your vertex shader.

**Comment by brainsick** [comment]
The vertex shader code is in the video; it's literally a one-liner.  I will work on a rotation sample if that's necessary.

In the run time window (right hand side), the bottom face is not black; it's missing.

**Comment by brainsick** [comment]
Okay, I added rotation and it's acting like you said in so much as it's sticking to the face pointed away from the light; just a shadow then?

[vertexshaderhtml5.zip](https://github.com/godotengine/godot/files/1650376/vertexshaderhtml5.zip)

**Comment by BastiaanOlij** [comment]
Ah, youtube always opens up these videos waaaay to small :) I see it now.
Yes seems to be just the face in shadow BUT you can greatly improve your example if you enhance your shader to also update the normal and tangent. Thats a bit more tricky in your case but well worth investigating as it will give you much better lighting on your objects when you distort their shape

**Comment by brainsick** [comment]
I'm right at the edge of my understanding.  I'm naively "correcting" the normal with `NORMAL = VERTEX;`.  I'll read up on the topic (that was the goal of this anyway), but would you have a working example handy?  Maybe as applied to these simple shaders?  "See"ing is a great motivator for learning.  :)

**Comment by BastiaanOlij** [comment]
I don't have an example handy and I'm at work right now but I'll give it some thought. 

Having example code that will calculate normals and tangents in shader would be nice to have though a generic solution may end up being costly..
