### ISSUE TITLE
"Physics Frame Time" is confusing

### ISSUE THREAD

**Issue by anderejd** [godotengine/godot#15955]
Part of commit 9b634180aa9eefe079ecbf0ae1a1227d9555ba02 seems like an accident. "Physics Frame Time" does not make sense to me. I googled for it and found a screen shot displaying "Fixed Frame Time" which I suppose in other words is the frame time budget?

The previous name "Fixed Frame Time" makes more sense to me. Or Frame budget?

Off-topic:
Great project btw :) I'm just starting out experimenting and studying GDNative, imho it's awesome that you created a C API instead of C++ as most other engines (I'm aiming to do some Rust experiments).

**Comment by capnm** [comment]
It's just an abbreviation for **frame time of the physics process**. Will probably be clear if you dive more in godot programming ...

**Comment by anderejd** [comment]
I'm not so sure. "Physics Frame Time" reports 16 ms every frame and there's also "Physics Time" and that one hardly reports any time... ?
I'm playing around with the sponza demo: https://github.com/Calinou/godot-sponza

**Comment by Zephilinox** [comment]
Yeah it's a shame they renamed all the fixed stuff to physics, but it makes more sense for beginners (oh, we put the physics code in here)

**Comment by Dillybob1992** [comment]
@anderejd Physics Time & Physics Frame Time are the same arn't they?

**Comment by anderejd** [comment]
I guess I'll read the code to figure out what it actually is measuring. Feel free to close.

**Comment by akien-mga** [comment]
It's simpler to read the docs that the code though :)
http://docs.godotengine.org/en/latest/classes/class_node.html#description

**Comment by anderejd** [comment]
@akien-mga Thank you for the link :) I will dig into the docs. Sorry for the noise!
