### ISSUE TITLE
Spinbox Tooltip only applies for the control not the line edit 

### ISSUE THREAD

**Issue by bfloch** [godotengine/godot#15965]
**Godot version:** 3.0, potentially 2.1 (untested)

**OS/device including version:** Fedora Linux - x64

**Issue description:**

The text area / line edit of the spinbox does not show the tooltip.
This reduces the area for the tooltip to the little control area.

![bug_spinbox_tooltip](https://user-images.githubusercontent.com/2116566/35207411-dad10730-ff10-11e7-922a-ed329e55b5bf.gif)

**Steps to reproduce:**
- Create a SpinBox
- Set a tooltip 
- Hover over the control area (arrows)
- Tool tip is shown
- Hover over the SpinBox line edit
- No tooltip is shown

**Comment by bfloch** [comment]
I assume that problem exists for any composited control.

A way to solve this is to emit a notification in "control" when the tooltip has changed, so that composited controls can update the tooltips of other controls.

Feedback appreciated.

**Comment by DualMatrix** [comment]
Probably related to #6328
