### ISSUE TITLE
Godot recognizes keyboard key 'I' incorrectly.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15970]
**Godot version:** godot 3.9 rc2

**OS/device including version:** macOs Sierra 10.12.6 macbook pro (2016) turkish keyboard.

**Issue description:**

my keyboard is 'Turkish - QWERTY PC'
Godot recognizes the keyboard key 'I' incorrectly.
All 'I' keys are mapped incorrectly.(I as Apostrophe)

COMMAND+I as COMMAND+Apostrophe

![keyborad](https://user-images.githubusercontent.com/33985414/35217109-18b261b0-ff7b-11e7-9e6c-cacb3683c78a.png)

Should be;
![should-be](https://user-images.githubusercontent.com/33985414/35217610-f493aad0-ff7c-11e7-8316-095ceefc97de.png)

for example auto indent shortcut;
<img width="347" alt="ekran resmi 2018-01-22 13 25 47" src="https://user-images.githubusercontent.com/33985414/35217163-41ba4032-ff7b-11e7-9925-4f906edfbf70.png">
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by bruvzg** [comment]
On macOS physical keyboard layout is detected by 6 letters from first row:
https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L2046-L2061

**Comment by icnikerazah** [comment]
@bruvzg So?

**Comment by bruvzg** [comment]
@icnikerazah I just pointing to code responsible for mapping.

Related problems #4386, #5503, #1106

**Comment by bruvzg** [comment]
In addition to `get_latin_keyboard_variant()` there is proper OS layout detection code: https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L1995

But all keys are remapped twice in a bizarre way. I suspect it's deliberate design decision to remap all keys to US-International QWERTY layout, to have common game mappings like "WASD" always mapped to same physical location on all keyboards.

**Comment by trollworkout** [comment]
Even if this is reported incorrectly it should still work in your game when you press CMD + i  which means is mapped correctly only reported incorrectly which I don't see it as a problem.

It doesn't matter what the engine tells you it is apostrophe or semicolumn as long as your chosen shortcut works as intended.

**Comment by icnikerazah** [comment]
@trollworkout what are you talking about. I can't write turkish characters ( ı İ ş ğ ) in TextEdit
i can't localize my game. Editor shortcuts are unusual.
![untitledd3s3](https://user-images.githubusercontent.com/33985414/35269592-879af69c-003d-11e8-94f9-5574b5c96c6d.gif)

**Comment by bruvzg** [comment]
> I can't write turkish characters ( ı İ ş ğ )

Text editor use `NSTextInputClient` protocol and is not related to keyboard shortcuts.

Text input should work with all keyboard layout, I just check and all characters from "Turkish - QWERTY PC" are inputed correctly (same as displayed in keyboard viewer).
![input](https://user-images.githubusercontent.com/7645683/35270419-b804665c-0037-11e8-89c5-2ae3bd324413.png)

`InputEventKey.unicode` - should have correct character for current keyboard layout.
`InputEventKey.scancode` - remapped scancode for used for keyboard shortcurts.

**Comment by icnikerazah** [comment]
sorry default font is not utf-8 you are right but others issue is same.

**Comment by icnikerazah** [comment]
nevermind I'm sure no one will fix it.
