### ISSUE TITLE
Godot 3- get_type() missing

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#15971]
How does one return the type of a node in godot3?
http://docs.godotengine.org/en/stable/classes/class_object.html#class-object-get-type
aNode.get_type() Seems to be missing from the API - nowhere to be seen in the documentation.

typeof() returns the type of a variable

what i need is to return the type of a node ("Node2d" or "Label")

**Comment by vnen** [comment]
It's called [`get_class()`](http://docs.godotengine.org/en/latest/classes/class_object.html#class-object-get-class) now.

**Comment by blurymind** [comment]
ah sorry, couldn't find it

thank you @vnen
