### ISSUE TITLE
Duplicated nodes are spawned without scripts in-game while Sync Scene Changes is enabled

### ISSUE THREAD

**Issue by AWKgamedev** [godotengine/godot#15978]
**Godot version:**
Godot 3.0 RC2

**OS/device including version:**
Windows 10

**Issue description:**
When using Ctrl+D in the editor to duplicate a node, in the editor it spawns with its script but if you have Sync Scene Changes enabled the node is spawned in-game without its script.
A node spawned by dragging and dropping the .tscn from the FileSystem tab into the scene works fine.

![2018-01-22 14_44_19](https://user-images.githubusercontent.com/10258315/35232499-c22a17ae-ff82-11e7-9719-2c67d746939d.png)
The screenshot shows 3 different nodes:
**Node2D** is part of the scene and created when the game loads.
**Node2D2** is a duplicate of Node2D, it spawns without its script, the parent node checks all its children for testVar and prints a message if the node doesn't have it, indicating that the node has no script attached.
**Node2D3** is the same node but dragged and dropped into the scene , it spawns with the script correctly.

**Steps to reproduce:**

1. Create a node with a script
2. Enable Sync Scene Changes
3. Run game
4. Duplicate the node in the editor
5. The node should be spawned without a script in-game

Note that this only affects the in-game nodes, duplicated nodes do have their scripts in the editor.

**Minimal reproduction project:**
The project has a node with a test variable and a _ready() function that prints a message, plus the root node that checks all its children for the test variable and frees it if the variable isn't found.
[Sync Scene Test.zip](https://github.com/godotengine/godot/files/1652819/Sync.Scene.Test.zip)

**Comment by h4de5** [comment]
Not sure if related: if you use .duplicate() in the code on a node that has a script set, the duplicate does not have that anymore. you have to manually set it.

```
var newnode = get_node("node").duplicate(true/false)
newnode.set_script(get_node("node").get_script())
```

**Godot version:**
Godot 3.0 stable

**OS/device including version:**
Windows 10

may need further testing for child nodes and their scripts.
