### ISSUE TITLE
Can't assign some new instance variable on Visual script!

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#15977]
win10, nvidia 960m,

Well I think there are few missing intances in preload like new networkedmultiplayerenet.new() of visual script for creating variables like gdscript or am i missing something!

**Comment by gamergamesz** [comment]
@Noshyaar

**Comment by Noshyaar** [comment]
You can't use `preload` as it's not Resource.

Try:

![img](https://i.imgur.com/3ckS7Qg.png)

I guess we can make it easier somehow.

**Comment by gamergamesz** [comment]
oh! thank you so much. finally after so long, i guess now i can do a multiplayer on VS as this is the only missing feature i have been looking for!

**Comment by fire** [comment]
Original issue was resolved. Open a issue if you want to contribute new documentation changes.
