### ISSUE TITLE
Multiple issues with RigidBody sleeping/active state with both GodotPhysics and Bullet

### ISSUE THREAD

**Issue by nadnam** [godotengine/godot#15975]
**Godot version:**
v3.0-rc1_x11.64

**OS/device including version:**
Debian 9 64-bit

**Issue description:**

Multiple issues. I am not sure is this correct behavior or my mistake.

Running with Bullet:

 - performance monitor incorrectly reports number of active 3d objects (it seems it doesn't work at all?

Running with GodotPhysics:

 - left body seems to be counted as active even though it should not be (see below)

Explanation about left body:

Left rigid body has attached StaticBody with cube shape (much smaller) and it has layer mask set so it should not be colliding with anything. Idea is to use it for ray picking (which works), but it seems that it affects parent RigidBody in a way that prevents it to ever become inactive, even though parent is sleeping.

I am not sure if this is correct use of StaticBody. When it is replaced by Area, both ray picking and parent rigid body inactiveness work as intended. 

**Steps to reproduce:**

Run attached program. Switch between physics engines.

**Minimal reproduction project:**

[_GodotStaticBodyBug.zip](https://github.com/godotengine/godot/files/1652374/_GodotStaticBodyBug.zip)

**Comment by nadnam** [comment]
rc2 has same problem described for left cube. Left cube never enters inactive mode, even if add_collision_exception is added between itself and sub body.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
