### ISSUE TITLE
Menu hard to use

### ISSUE THREAD

**Issue by willy1920** [godotengine/godot#15974]
example when I click scene menu and show up the menu but if I click scene again menu not close. Same as visualscript menu bar.

**Comment by lmjk** [comment]
I agree, the opened drop-down menus should close on the second click. Now it will close on the third, or on the first if you move the cursor and click anywhere else.

**Comment by lmjk** [comment]
Actually it seems that you only need to move the cursor a little (but enough), even when keeping it over the menu you clicked open and it will close on the second click like it should.

**Comment by MattUV** [comment]
This problem appeared for the 1st time with this PR: #13351

**Comment by letheed** [comment]
Agreed, this is annoying. Maybe this should be renamed. Not sure why this is not tagged Bug or anything.

**Comment by MattUV** [comment]
Well to be honest, the bug report doesn't fit the standards...
@Calinou added the labels after your messages, but I will make a correct topic tomorrow (if it is not fixed yet ^^)

**Comment by letheed** [comment]
No, it's not. There's a few issues with menus that I wanted to report, but they all already have BRs, just not fixed yet.

**Comment by aaronfranke** [comment]
Is this still a problem? If so, can you provide example images/video?

**Comment by letheed** [comment]
No, this is fixed on master and should be closed.

**Comment by willy1920** [comment]
thank you to remind me @letheed
