### ISSUE TITLE
BaseButton's Shortcut system doesn't work with InputEventActions

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#15979]
**Godot version:**
 f4d6743

**Issue description:**
Maybe I don't know how to set it properly, but I have asked others and I have yet to find someone who had made it work.

In my case, I'm trying to use it with an InputEventAction, but no reaction in-game whatsoever.

**Comment by vnen** [comment]
Do you have a sample project?

**Comment by YeldhamDev** [comment]
@vnen Sorry for using a thirdparty site, put GitHub isn't accepting the zip for some reason:
https://www.file-upload.com/kfn3plwv2h96

The button is set to print "Pressed" and its shortcut is set as "ui_accept", so pressing enter should trigger it, but it doesn't.

**Comment by vnen** [comment]
Uploaded here to make it easier for others: [test.zip](https://github.com/godotengine/godot/files/1657528/test.zip)

**Comment by vnen** [comment]
It doesn't work with actions.

**Comment by YeldhamDev** [comment]
@vnen Then why it's possible to use an InputEventAction then?

**Comment by vnen** [comment]
I don't know if it was supposed to work with actions or not, I was just saying that the current state is that it doesn't work.

**Comment by YeldhamDev** [comment]
@vnen Oh, sorry.
Yeah, it seems that thing like InputEventKey works, changing the title to represent the issue better then.

**Comment by DleanJeans** [comment]
Since I've been here twice, for those using 3.0 and waiting for 3.1, here's a workaround, though it won't work with multiple keys with the same action:

1. Create a `InputEventKey` instead
2. Look up `@GlobalScope` find your key (`Ctrl+F` and enter `KEY_*`)
Example: `KEY_1` is 49, `KEY_2` is 50 (above the Q key) and so on
4. Enter that code into the `Scancode` property
5. You're done!

![image](https://user-images.githubusercontent.com/12462089/44296713-fd92b800-a2ed-11e8-911e-8d0fbc4a3d4c.png)

**Comment by salvob41** [comment]
Hi guys, I set the shortcut with InputEventKey, even if it does the same action as the button has been pressed... why it doesn't activate the `pressed` texture on my Button?

**Comment by vince94** [comment]
Why does it want a path?
![image](https://user-images.githubusercontent.com/12562322/57778742-af7ed980-76f2-11e9-8a13-5952cdfdee7e.png)

**Comment by YeldhamDev** [comment]
@vince94 Click `InputEventKey`.

**Comment by vince94** [comment]
At first it just opened this menu again - 
![image](https://user-images.githubusercontent.com/12562322/57793714-ff1fce00-770f-11e9-8228-c40c8e60c277.png)

But I figured it out. I'm so used to vanilla WinForms that I never considered that clicking the text would have a different result than clicking the middle of the control :/

Is there documentation for what scancodes are?

**Comment by chapmanh** [comment]
This issue has been fixed now right? I've managed to link a button up that prints whenever enter is pressed using the default "ui_accept" action at least..

![image](https://user-images.githubusercontent.com/46978481/104844272-3bcda080-58c7-11eb-9fd7-1a38f76fb6ce.png)

**Comment by whoif** [comment]
> This issue has been fixed now right? I've managed to link a button up that prints whenever enter is pressed using the default "ui_accept" action at least..
> 
> ![image](https://user-images.githubusercontent.com/46978481/104844272-3bcda080-58c7-11eb-9fd7-1a38f76fb6ce.png)

Hello, I tried your way but it gives me a hint when I hover the button.

But I don't want this hint. 

Would you plz tell me if this situation happens to you too?

Or does anyone know how can I remove it?

![Screenshot (5)](https://user-images.githubusercontent.com/21272198/107847074-80dfe680-6e23-11eb-9c55-5e859da6728c.png)

**Comment by Calinou** [comment]
> But I don't want this hint.

You can hide it by unchecking **Shortcut In Tooltip** in the Button node's properties.
