### ISSUE TITLE
Cannot decompress normal maps in WebGL 2.0

### ISSUE THREAD

**Issue by gerardabello** [godotengine/godot#15983]
I think this is related to issue #15792

**Godot version:**
3.0 rc2

**OS/device including version:**
Ubuntu 17.10
Nvidia GTX 660 (using propietary driver version 384.111)
Tried on OSX sierra with same results.

**Issue description:**
Exporting to HTML5 renders without some textures. All textures are missing but the sky texture.

Issue #15792 suggests using the texture Format:
S 3tc On
Etc Off
Etc 2 On

But this justs makes it worse, I get a black screen and the console shows this error:
TypeError: Argument 9 of WebGL2RenderingContext.texImage2D is not an object.

I get the same results in firefox and chrome.

**Comment by akien-mga** [comment]
We'd need a project that reproduces the issue to be able to debug here, otherwise there's not much that can be done.

CC @eska014 @reduz

**Comment by gerardabello** [comment]
@akien-mga that makes sense.
I removed some things to make the project smaller, but I keep seeing the problem. I attach the project and the html export (using s3tc + etc2).
[game.zip](https://github.com/godotengine/godot/files/1655784/game.zip)
[html_export.zip](https://github.com/godotengine/godot/files/1655785/html_export.zip)

Tell me if you need anything else.

**Comment by eska014** [comment]
The normal map gets compressed with RGTC, but WebGL doesn't have any extensions for that, and `Image::decompress` can't handle it either. You'll have to disable the `compress/normal_map` import setting on the normal texture for WebGL.

**Comment by gerardabello** [comment]
That solved the problem. Thanks!

**Comment by LinuxUserGD** [comment]
Get the same issue:
```**ERROR**: Condition ' image->is_compressed() ' is true. returned: image
**ERROR**:    At: drivers/gles3/rasterizer_storage_gles3.cpp:559:_get_gl_image_and_format() - Condition ' image->is_compressed() ' is true. returned: image```
Changing compress mode on normal maps from ```Video RAM``` to ```Lossless``` works.

**Comment by reduz** [comment]
@eska014 I think we should just decompress the texture and upload it when this is not supported, so at least it works. If you are around let me know and I can add some code for this.

**Comment by reduz** [comment]
I mean it should not even be that terrible, it will use only twice as much memory for that texture
