### ISSUE TITLE
Can't continue inside a loop if continue is used inside a match block

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#15988]
**Godot version:**

Godot 3.0 master https://github.com/godotengine/godot/commit/511742eb68790345abf594b42b6c25b38360c3df

**OS/device including version:**

**Issue description:**

`continue` inside a `match` block is used to fallthrough and can't be used to continue a loop. http://docs.godotengine.org/en/latest/learning/scripting/gdscript/gdscript_basics.html#match

```gdscript
	for i in 10:
		match i:
			5, 6, 7:
				continue
		print(i)
```
Outputs:
```
0
1
2
3
4
5
6
7
8
9
```

It should output:
```
0
1
2
3
4
8
9
```

`break` does work as expected:
```gdscript
	for i in 10:
		match i:
			8:
				break
		print(i)
```
Outputs:
```
0
1
2
3
4
5
6
7
```

**Comment by vnen** [comment]
Makes sense because `continue` is consumed by the `match` statement itself (it's used to fall through the next pattern code).

One solution to this would be to add a numeric argument to `continue` and `break` (like PHP) so `continue 0` would fall through and `continue 1` would go to the next iteration. Or make it use labeled like Java.

**Comment by mrcdk** [comment]
Uhm, does it make sense to have a fallthrough mechanism when there's already multipatterns? I can't think of anytime I wanted to fallthrough when using pattern matching and I've been using Haxe for the last 5 years almost daily... Oh well, I can live with it.

**Comment by hubbyist** [comment]
I think numeric `continue x` will be better since labels may act as a hidden go to feature.

**Comment by vnen** [comment]
> Uhm, does it make sense to have a fallthrough mechanism when there's already multipatterns?

**Comment by coffeeDrake** [comment]
I curently experience the exact opposite of a problem with godot 3.4. As this issue is still open, I assume that there where no changes to the behaviour mentioned above.

```
for _line in lines:
	var weapon2 = null
	var line10 = null
	var line11 = null
	var createUnit = true
	match _line.size():
		13:
			weapon2 = _weapons.string_to_weapon(_line[12])
			line11 = _line[11]
			line10 = _line[10]  
		12:
			line11 = _line[11]
			line10 = _line[10]
		11:
			line10 = _line[10]
```

does not produce the same result, as:
``` 
for _line in lines:
	var weapon2 = null
	var line10 = null
	var line11 = null
	var createUnit = true
	match _line.size():
		13:
			weapon2 = _weapons.string_to_weapon(_line[12])
			continue
		12:
			line11 = _line[11]
			continue
		11:
			line10 = _line[10]
``` 
That thing runs in it's own thread, but that shouldn't make a diffrence.

**Comment by karroffel** [comment]
@coffeeDrake that is expected, if you check the documentation, it says "it will continue to check the other patterns", so this is actually expected.

**Comment by ThakeeNathees** [comment]
this issue could be closed, since match statement can consume `continue`

**Comment by CitrusWire** [comment]
> this issue could be closed, since match statement can consume `continue`

I'd argue it's a bug because it's unexpected behaviour for many users. `continue` isn't really a normal thing for an if/switch statement. It'd gotcha me. (so a bug in the language design if you will.)

I'd suggest the solution be as vnen etc suggested - allow an integer to be included to specify the depth for continuing/breaking. Otherwise godot is restricting the cases where MATCH can be used in loops.

**Comment by RichardR01** [comment]
I just ran into this today, and luckily, found this page by searching for how Godot's continue works (it's easy to forget when we are so used to using break and continue for loops, not switch like statements). I agree with CitrusWire and Vnen that it needs to be changed so we can use a statement like continue 1 (for the level above, 2 etc) and so on. Same for break.

**Comment by nihiluis** [comment]
so back to using if else.

**Comment by dalexeev** [comment]
See

* #71914

Now the code works as you wanted:

![](https://user-images.githubusercontent.com/47700418/218102046-d7a08bb8-9311-4ab4-a1ec-b60ff2839318.png)
