### ISSUE TITLE
Fixed Fps rename to Physics Fps

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#15981]
**Godot version:**

3.0 rc3 f4d67433e

**OS/device including version:**

**Issue description:**

should `Fixed Fps` rename to `Physics Fps`?
because `_fixed_process` is now `_physics_process`

**Steps to reproduce:**
![screenshot from 2018-01-23 04-55-07](https://user-images.githubusercontent.com/8281454/35241491-fdb42432-fff9-11e7-82f9-32d459aef229.png)

**Minimal reproduction project:**

**Comment by YeldhamDev** [comment]
And here we go again...

**Comment by NathanWarden** [comment]
If this is just a text change, I think it would be good to make everything consistent.
