### ISSUE TITLE
iOS export improvements

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#15997]
Just a few suggestions for improving the iOS export now that I'm using it for the first time in months :)

Biggest issue, when you don't fill in mandatory information instead of a helpful error you get a nasty "export template is corrupt" error. You can see the actual error in the log however when you start Godot as an application bundle that is hidden from view.
We need better checking before the export is being run so we can give a better message.

Other improvement would be to ensure we have default icons and splash screens. You can't do a quick export just to test if something works until you have selected icons and splash screens. It would be good that if you leave these empty, it would just use the defaults (might be a bug)

**Comment by vnen** [comment]
> nasty "export template is corrupt" error.

This is an issue with all exporters, if they return anything other than `OK` it'll show this same message. The individual exporters should be able to set the error message.

**Comment by tommiemartin** [comment]
Honestly I wish the icons and splash screen were not required in the exporter at all. Would be nice to have the option to control this solely in Images.xcassets and storyboards in xcode since Apple's requirements seem to change so quickly.

**Comment by akien-mga** [comment]
This has been improved a lot over the past years.
