### ISSUE TITLE
String.substr(pos, len) second argument should be optional

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15991]
Godot 3.0 RC2

It would be nice to have the second parameter of `substr` optional, and by default indicate the remaining length.
For example, removing the first character of a string currently needs to calculate the length:

```gdscript
s = s.substr(1, len(s) - 1)
```
While it could become:
```gdscript
s = s.substr(1)
```

Also using `-1` as second parameter doesn't work, it returns an empty string.

**Comment by trollworkout** [comment]
You can use s.erase(0,1) to remove first character and is much easier to write also is saved automatically

s.erase(0,1)

**Comment by Zylann** [comment]
That was just an example though, the proposal is still valid ;)

**Comment by hubbyist** [comment]
string.erase() is more appropriate for simplifying 

    string = string.substr(0,2) + string.substr(5,8)
    string = string.erase(3,5)

also can be useful for iterative processing. 

But implementing string.substr() with optional second argument will be more simple and intuitive anyway.

**Comment by ondesic** [comment]
I would also like the second argument to be optional or be able to use -1 to get all of the rest of the string from position

**Comment by akien-mga** [comment]
As mentioned in #28648, the requested feature is already provided by `String.right(pos)` which does what the proposed `String.substr(pos, -1)` would do.

So I'm not sure if it's really that necessary to add such feature. One could also expect that `String.substr(pos)` defaults to a slice of length 1 and gives the `pos + 1`-th character, by analogy with Python's slicing operator where `"string"[pos]` would do that (which `"string"[pos:]` would give the right side of the slice from `pos`).

**Comment by bojidar-bg** [comment]
If the feature is not added, it would be nice to either add links from `substr` to `right` and `left` or to group String methods more logically, in order to make it easier to find those other methods.
