### ISSUE TITLE
Viewport data not being sent to shader parameter in runtime

### ISSUE THREAD

**Issue by AssjackGames** [godotengine/godot#16006]
**Godot version:**

3.0 RC2

**OS/device including version:**

Windows 10
AMD Radeon HD 7700 Series
Driver version: Adrenalin (17.12.1)

**Issue description:**

Viewports aren't properly sending their output to shaders (at least in 2D, haven't tested for 3D). While it appears to work fine in-editor, when the scene is ran the output is all black.

**Steps to reproduce:**

First I created an empty scene, root type node2D. I made a viewport, set it up, and added an image under it, setting the texture to a png. I then made a new sprite outside that viewport and set the texture to the viewport output to test if it was outputting fine. I ran the scene and all seemed to work, I saw the circle image.

I then replaced the texture of the output image with a blank png (Color(1, 1 ,1 ,1)) the size of the screen, and created a new shader, using this code:

```
shader_type canvas_item;

uniform sampler2D mask;

void fragment(){
	COLOR = texture(mask, UV);
}
```

Then I set the parameter `mask` to the viewport output, and I saw the results immediately in the editor, however when I run the scene the output is all black. I also tried sending the viewport data through gdScript using `get_texture`, and it too led to the black screen output.

**Minimal reproduction project:**

Test project attached. I created two output sprites for it, one direct from the viewport, one with the shader. With this bug any shader needing more than a single viewport won't work.

[Viewport Bug.zip](https://github.com/godotengine/godot/files/1657239/Viewport.Bug.zip)

**Comment by DoctorAlpaca** [comment]
Of note, when also using the same texture to a sprite the correct texture gets send to the shader. I'm guessing the shader handling code doesn't correctly tell the texture to update itself.

**Comment by AssjackGames** [comment]
Not that it was on the agenda, just thought I'd mention that the bug exists in 3.0 stable too.

**Comment by AssjackGames** [comment]
Not sure if this is related, but when I try to set an image texture to a new ViewportTexture via gdScript (changing the viewport_texture property too of course) it shows nothing when I run it. I know the viewport works fine, and oddly enough when I make the sprite through the editor, set it to the viewport, clear the path and set the path through gdScript it shows fine too. Problem seems to be initiating a new ViewportTexture through code. Should this be a new ticket?

**Comment by eon-s** [comment]
Related to #16006 and #7998 (possibly duplicated too), on the later is mentioned setting the texture as local to scene but nothing changes with it.

If there is a documentation issue, then the steps to use it should be added because it makes the ViewportTexture look useless for 3D.

**Comment by AssjackGames** [comment]
My tests have been completely in 2D, should that make any difference in diagnosis

**Comment by akien-mga** [comment]
Related to #7998.

**Comment by kubecz3k** [comment]
Related to https://github.com/godotengine/godot/issues/17651

**Comment by reduz** [comment]
This is not a bug (Material was not set as local to scene), but usability was pretty bad to let you know what was going on.
Added warnings to avoid you when creating a ViewporTextures if most common conditions are not met instead.

**Comment by Proggle** [comment]
> This is not a bug (Material was not set as local to scene), but usability was pretty bad to let you know what was going on. Added warnings to avoid you when creating a ViewporTextures if most common conditions are not met instead.

For people finding this thread in the future (on Godot 4.4 ), you have to make _all_ parent resources also local to scene, not just the viewport.

So for instance, in a MeshInstance3D with a Mesh with a Material with a Shader with a ViewportTexture, all four of those (Mesh/Material/Shader/ViewportTexture) have to be set local to the scene for the viewport to work in game (in editor it will often work just fine)

The warnings do not communicate this, and honestly Godot ought to go up the chain and manually make them all local to scene if you set up a viewporttexture, because I don't think any user has the expected behavior of 'your viewport doesn't work'.
