### ISSUE TITLE
Sprite animation frames don't work if region rect is enabled

### ISSUE THREAD

**Issue by DragonAxe** [godotengine/godot#16007]
**Godot version:**

v3.0.rc2.official

**OS/device including version:**

Arch Linux 4.14.12-1-ARCH #1 SMP PREEMPT Fri Jan 5 18:19:34 UTC 2018 x86_64 GNU/Linux

VGA compatible controller: NVIDIA Corporation GM200 [GeForce GTX 980 Ti] (rev a1)
Subsystem: eVga.com. Corp. GM200 [GeForce GTX 980 Ti]
Kernel driver in use: nvidia

**Issue description:**

When a Sprite's `Region` is enabled, it overrides the Animation `Frame` property. This works as expected, but is not intuitive. If the user has enabled the `Region` property and then tries to set the `Frame` property, they will think something is broken as I did.

Perhaps a possible fix would be to have the `HFrames` and `VFrames` subdivide the area selected by the region. This would show to the user that the system is working while also adding an additional feature to the engine (The ability to animate subsections of a larger spritesheet for example).

![bugtestscreenshot](https://user-images.githubusercontent.com/12703200/35295107-83a899d4-0035-11e8-821f-0b03cfa897ee.png)

**Steps to reproduce:**
* Create new project with a new scene
* Add a Sprite node to the new scene
* Set the default Godot project icon as the sprite's `Texture`
* Enable the sprite's `Region` and set the region's `Rect` to `(0,0,32,32)`
* Set the sprite's `HFrames` and `VFrames` values to `2`
* Change the sprite's `Frame` value to values other than `0`

**Minimal reproduction project:**

[BugTest.zip](https://github.com/godotengine/godot/files/1657193/BugTest.zip)

**Comment by bojidar-bg** [comment]
Responsible code is:
https://github.com/godotengine/godot/blob/e4213e66b2dd8f5a87d8cf5015ac83ba3143279d/scene/2d/sprite.cpp#L56-L68
Maybe lines 63,66,67 should be moved outside the else.

**Comment by ibrahn** [comment]
I had a local change that works as you described:
> Perhaps a possible fix would be to have the `HFrames` and `VFrames` subdivide the area selected by the region.
I'll PR a cleaned up version of it, as an option if it's how people would like it to work.

Side note for people wanting to animate sprites from sub regions of a texture:
This can also be done (with greater flexibility, but a few more clicks) by creating AtlasTexture resources that refer to regions of the texture and then composing them into animations, with the AnimatedSprite node.

**Comment by juanpaexpedite** [comment]
Thank you @ibrahn for the note about AtlasTexture, pretty easy to use, set the Region in the AtlasTexture and then go back and set the hframes and vframes it works pretty well. I used the Sprite Node
