### ISSUE TITLE
Clicking outside of the game window breaks collision with Bullet.

### ISSUE THREAD

**Issue by randyyaj** [godotengine/godot#16015]
**Godot version:**

Godot 3.0 RC2

**OS/device including version:**

Windows 10

**Issue description:**

Collision body does not work upon leaving game window and re-entering. It'll also sometimes break randomly.

**Steps to reproduce:**
Run the game, move character with arrow keys pushing against green cube. Then click outside of game window. Re-enter game window and try to move the character against the green cube again. The cube should get pushed around when it's broken the player will go right through the cube.

**Minimal reproduction project:**

[junkforge.zip](https://github.com/godotengine/godot/files/1657989/junkforge.zip)

**Comment by akien-mga** [comment]
I can reproduce it on Linux (Mageia 6 x86_64) using the provided project. It's pretty random, the bug does not appear all the time, so you might need to try several times (by restarting the game in the editor) before it occurs. Starting the game, losing focus *before* testing a collision, then getting focus back and trying to collide works relatively well to reproduce the issue.

I could reproduce it many times with Bullet, but not with GodotPhysics, so assuming that it's an issue only with the former. CC @AndreaCatania.

**Comment by AndreaCatania** [comment]
Related to this: #13148
This is not a real bug, and in order to execute it you just need to wait the other body that go to sleep.

As confirmation of my thesis you can set the other body to never sleep and you can see that this problem never occurs anymore.

I'll implmenet it soon, thanks you for report

**Comment by randyyaj** [comment]
@akien-mga I can produce it with both physics engine on Win10.

**Comment by AndreaCatania** [comment]
Fixed #16757
