### ISSUE TITLE
- Suggestion, Haskell Version

### ISSUE THREAD

**Issue by BenoitKH** [godotengine/godot#16020]
Good afternoon Godot community, I'm one of the lead members from the Haskell committee. One of our team members recommended Godot for game development and fell in love.  We had a talk over there, and would love to hear your opinions as well.  Our team is willingly, and readily available to convert the entire code base to Haskell, but would like hear the community's thoughts first.

### Some reasons for:
- Better performance than C++ (in most cases, not all)
- No object orientation required, functions can be everywhere.
- Generics and inheritance worrying will become obsolete
- Mutable classes with Dynamic Fonts / Nodes won't be as issue because of the inherit functional design
- Concepts from C++14 can still be ported over to Haskell 
- Structures can be mutable objects / classes instead of using a destructor repeatedly
- GDScript can still be used, but under a Haskell parser
- Asynchronous socket IO will be much lower level
- A large established library of tools and programs already available to be integrated
- Memory allocations are dynamic, and GDScript can still use co-routines
- Use of array literals instead of _vectors_  will offer a performance boost
- Stroustrup's low overhead philosophy will still apply

### Reasons against:
- Huge re-write will take an immense amount of time
- Contributors are already focused / strong in their C++ language

If there are any other pros and cons, please don't hesitate to post.  Our committee already voted and if we get the general consensus here from the community, we'll start porting right away. 

Thank you for your time,
\- Benoit

**Comment by mhilbrunner** [comment]
Hi! Some small feedback, not speaking for Godot or someone besides myself:

1. Haskell committee? As an outsider, I only found https://prime.haskell.org/wiki/Committee, https://wiki.haskell.org/Core_Libraries_Committee and https://wiki.haskell.org/Haskell.org_committee - neither of which mentions a Benoit. Googling "Benoit" and "BenoitKH" and "Haskell" also didn't result in much, but maybe my google-fu is especially weak today. No accusation, but seeing as your GH profile is also new and doesn't tell much, could you please provide more detail?
2. You may want to investigate adding a Haskell binding to Godot via the GDNative/PluginScript/NativeScript facilities, like the Nim/Python/D/Rust bindings do, this would allow usage of Haskell in addition to those languages (and GDScript/C#/VisualScript), but of course the core engine would remain C++
3. Your suggestion would basically be a fork of the whole engine

**Comment by LikeLakers2** [comment]
Not a member of the Godot dev team here, but I am personally against. However, this is only because Godot development seems to be going slow already, or at least, I perceive it to be slow, and I would rather Godot's development not be hindered by a re-write. (Of course, I welcome others to disagree with me or dispute whether it's actually slow!)

That being said, I would not be against this being done on the side, as a potential alternative to Godot in the future for people to choose from, especially if it does end up being better as you claim. I would just prefer this not affect current development.

**Comment by mysticfall** [comment]
I'm not a member of the development team either, but I also completely agree with what others said above.

In case this is a legitimate offer, I'm excited to see Godot is broadening its userbase to include such a programming language that traditionally hasn't much presence in this area. But I'm not sure if rewriting the whole engine in Haskell could benefit anyone at this stage, at least in a forseable future.

If your intention is to make Godot more easily accessible to those who use Haskell language, probably creating a binding via `GDNative` and investing time to improve toolsets or streamlining workflow better be the first step toward the goal.

And if it attracts many Haskell users to Godot in future, and if many of them show willingness and ability to contribute to the project, then probably we could discuss if we should start using Haskell in developing the engine itself.

But if we start by rewriting the whole engine in Haskell, the chances are that Haskell users will need to wait quite a long time before they can even think about using Godot for any real project.

And in case your committee is full of capable developers who can migrate the whole engine in a relatively short period of time, then I suppose they won't need much time before they can write a `GDNative` binding to Haskell language, so I think it could be a more reasonable first step, if you want to pursue such a route.

**Comment by queer** [comment]
Hi guys, just a heads up:

This was posted on /r/programmingcirclejerk a few times, with the original post being deleted. This issue was created almost immediately before the original pcj post, so this is likely a joke/troll post. 

Original post: https://www.reddit.com/r/programmingcirclejerk/comments/7skz1w/porting_entire_c_game_engine_codebase_to_haskell

Repost: https://www.reddit.com/r/programmingcirclejerk/comments/7sl5ql/proposal_to_convert_entire_c_game_engine_to

**Comment by moonshineTheleocat** [comment]
My reason against the transfer is that C++

- Already has plenty of resources. A large majority of the common and uncommon problems that a programmer may run into have already been solved with C/C++. This means that if someone wanted to implement a specific feature for their game in Godot, they can easily skip a large majority of the effort. As chances are... it's been done already.
- Has wide spread support. Most operating systems, game systems, and devices have compilers that will work well with C++, and for the most part generally supports the language features of the version they target.
- C++ Is one of the most well known languages. And is generally going to be the first thing a new programmer will see in their life time. If not that, then C#, Python, Java, or Lua.
- The functional programming paradigm quickly becomes nightmare fuel to read when you enter large projects with a lot of parts that must work together. As it is, the language is already difficult to understand when you're not experienced with it. Comparatively, C++'s difficulty to read depends greatly on the programmer not the language.

**Comment by BenoitKH** [comment]
@queer Apologize if it came off that way, as this post was a bit too direct. Was just trying to start discussion on it as we're reading the posts now.  And appreciate all the input thus far

**Comment by akien-mga** [comment]
Sounds good for milestone 42.0 - we already planned to [Rewrite It In Rust](https://github.com/godotengine/godot/issues/8873) for milestone 25.0 before that and there's only so much we can do.

**Comment by groud** [comment]
Proposing to convert a whole object oriented game engine to a functional language, posting it on reddit on a subreddit called programmingcirclejerk and claiming being from the "haskell commitee" without introduction makes me think this is a joke.

I'm closing this issue anyway, no such rework is ever going to happen.

**Comment by akien-mga** [comment]
If there were still doubts about OP being a troll: https://github.com/godotengine/godot/issues/16024#issuecomment-360182394
![image](https://user-images.githubusercontent.com/4701338/35342745-22b6a874-0129-11e8-8506-9edd7bf7fdd2.png)

Locking this issue and blocking account, we have enough work on our hands not to bother with this game.

**Comment by reduz** [comment]
Wait, before Rust I want to rewrite it in Swift..
