### ISSUE TITLE
Fix revert button behaviour

### ISSUE THREAD

**Issue by nattanielgrape** [godotengine/godot#16027]
**Issue description:**

In the editor, when increasing or decreasing an exported integer or float variable from its original value, the revert button appears and gets in the way of the cursor. And when the variable is increased or decreased back to its original value, the revert button disappears and the increase/decrease arrows move away from the cursor, which selects the value unintentionally. The GIF below demonstrates these issues:

![issues](https://user-images.githubusercontent.com/35730957/35340835-5a8dcf5c-010b-11e8-8935-17616cfab5d4.gif)

**Proposed solution:**

Making the revert button always visible (but disabled/greyed out at the variable's original value) would solve these small, yet inconvenient problems, as illustrated by the mockups bellow:

![mockup1](https://user-images.githubusercontent.com/35730957/35343132-f99769be-0110-11e8-9b6d-b5ddf449563b.png)

![mockup2](https://user-images.githubusercontent.com/35730957/35340949-99edbc48-010b-11e8-98ab-c544b8aac0bd.gif)

**Comment by groud** [comment]
I would just make the icon appear at the left of the arrows. Else the icon takes room for no  purpose.

**Comment by bojidar-bg** [comment]
IMHO, might be worth experimenting putting it within the name column, so it won't take any of the space for the value.
Other than that, if it is going to be taking space all the time, we should consider making it smaller.

**Comment by nattanielgrape** [comment]
I renamed the issue to welcome more solutions.

**Comment by icnikerazah** [comment]
There is no need to put an icon for this every time. it may be a bit brighter or a different color if it differs from the default value. "CTRL + DoubleClick" (CMD on macOS) returns the original value. "CTRL + mouse movement" for more precise adjustment.
I am a big fan of [Round sliders](https://www.google.com.tr/search?dcr=0&biw=986&bih=758&tbm=isch&sa=1&ei=64lqWsSBCIessAfGpbLADg&q=round+slider&oq=round+slider&gs_l=psy-ab.3...1382.4276.0.4399.0.0.0.0.0.0.0.0..0.0....0...1c.1.64.psy-ab..0.0.0....0.mJfd4Yj2cLc)

**Comment by kukiric** [comment]
> I would just make the icon appear at the left of the arrows. Else the icon takes room for no purpose.

I think having blank space reserved for the reset button wouldn't be too bothersome, and it would add visual symmetry with the blank space before the variable name. Having the button somewhere else (eg. to the left of the value box) could be awkward, but that can only be decided through trial and error.

**Comment by icnikerazah** [comment]
I think it should be like this.
When the purple text  double is clicked. returns to real value and will be white.
Notice the embedded input box on the right.
![sonson](https://user-images.githubusercontent.com/33985414/35456119-7c325e94-02e5-11e8-9815-1643532113c3.jpg)

**Comment by groud** [comment]
No, in my opinion it should not. Color is not meaningful at all and double clicking on a label is unintuitive.

**Comment by icnikerazah** [comment]
it's not only text, it's variable name in api classes. what about embedded vector input boxes?

**Comment by bojidar-bg** [comment]
Embedded input boxes are a nice idea, but would have to wait for the property editor redo :)

**Comment by puppetmaster-** [comment]
Is someone using this up and down arrow?
What do you think they're behaving the same way? It looks identical.
![image](https://user-images.githubusercontent.com/10463138/35458792-08228526-02de-11e8-9f64-6beb6ff72532.png)
![image](https://user-images.githubusercontent.com/10463138/35459725-aa1614ee-02e1-11e8-8046-eb0e96c4d43d.png)
I never use it. To small, result is different and are hidden when you click in the field.
![image](https://user-images.githubusercontent.com/10463138/35458897-79838a58-02de-11e8-99d9-fc000784183b.png)
We could **replace** it with the place for reset button. 

I also would like to have the opportunity to set property to its original value.
From time to time I move a scene accidentally and like to reset the position to (0,0)
(Modulate to white, Scale to (1,1), etc.)

**Comment by nattanielgrape** [comment]
The keyframe button is being pushed to the left by the revert button, it's the same problem.

**Comment by icnikerazah** [comment]
looks like designed by a troll

**Comment by reduz** [comment]
I will work on rewriting the inspector at some point, but there are other priorities before. Regarding the revert button, it suppose it may be moved to the left?

**Comment by nattanielgrape** [comment]
I made a mockup putting the revert button on the left of the exported variable's value box (within the name column, as proposed by @bojidar-bg):

![mockup1](https://user-images.githubusercontent.com/35730957/35472776-c09f551a-035c-11e8-8b93-86c078baf18e.gif)

It has kind of a visual symmetry with the keyframe button:

![mockup2](https://user-images.githubusercontent.com/35730957/35472816-76f6f3ea-035d-11e8-9b9b-6d11f1f2724e.png)

And it could also work with the proposed embedded value input box:

![mockup3](https://user-images.githubusercontent.com/35730957/35472838-da378e06-035d-11e8-8f9e-ea13a698b4b0.png)

**Comment by nattanielgrape** [comment]
And here's as proposed by @groud, with the revert button appearing at the left of the arrows:

![mockup4](https://user-images.githubusercontent.com/35730957/35473288-46c3c9e8-0365-11e8-928a-089706abde82.png)

**Comment by icnikerazah** [comment]
it is difficult to hit in the icon at macbook pro 15 default retina screen resolutions. Because two icons are very close together.
<img width="43" alt="ekran resmi 2018-01-27 18 41 27" src="https://user-images.githubusercontent.com/33985414/35473495-8ca19954-0392-11e8-9361-bf9993577c6a.png">
or
![35473288-46c3c9e8-0365-11e8-928a-089706abde82](https://user-images.githubusercontent.com/33985414/35473496-90ad2f5e-0392-11e8-82d3-5d94d5238da2.png)

**Comment by nattanielgrape** [comment]
These issues would also affect instanced nodes' properties, but the revert button doesn't seem to work for them, as reported on #7901 and #16068 (there's a cached version of it [here](https://webcache.googleusercontent.com/search?q=cache:naKOpHWb3yIJ:https://github.com/godotengine/godot/issues/16068)):

![instanced](https://user-images.githubusercontent.com/35730957/35486416-d0dce476-0454-11e8-9a0e-46ecfd1fbeb1.gif)

(I changed the title again to better reflect the issues, as they are more general)

**Comment by DualMatrix** [comment]
The revert button now seems to be on the left on master. So this is no longer an issue.

**Comment by akien-mga** [comment]
Indeed, closing.
