### ISSUE TITLE
Unchecked  Generate Tangents for imported .obj + deep parallax = crash.

### ISSUE THREAD

**Issue by Biliogadafr** [godotengine/godot#16026]
Godot version: 3.0 59e83af
OS/device:
Windows 10, GF970

If Generate Tangents is unchecked in  import settings for .obj file, then attempt to use deep parallax on such mesh will lead to crash. 

Example project has this settings so it will immediately crash godot after  opening. 
[crash_import.zip](https://github.com/godotengine/godot/files/1660240/crash_import.zip)
To open this project without crash delete plane.obj.import file. To trigger crash again uncheck Generate Tangents  for plane.obj and press reimport.

**Comment by Alexander-Alekseev** [comment]
Godot doesn't crash in a1f835df771464e9db6909fd104751ccbbc1b91a with attached project.

**Comment by EzraT** [comment]
Can confirm this also happens in 3.0.2 on Linux (Xubuntu 17.10).

**Comment by reduz** [comment]
After checking and re-checking, this is impossible to fix with OpenGL due to attribues not being part of the VAO. It can be properly fixed in Vulkan though. Kicking to 3.2

**Comment by KoBeWi** [comment]
No crash in 4.0
