### ISSUE TITLE
Can’t “sidechain” the audio Compressor effect

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#16036]
It is very possible I may be doing something wrong here, but either the sidechain system isn't working, or the UI is listing entries it shouldn't list.

If I create multiple audio busses, with at least one of them containing a Compressor, the Compressor displays the other busses as options for its Sidenchain parameter (when the combo box next to it is expanded). However, regardless of which bus I select, the bus' name flashes for a moment in the Sidechain parameter's value box and then disappears.

So either the assignment isn't working, or the combo box is listing busses it shouldn't display as options.

**Godot version:**
V3.0, custom build (currently based on Commit #44cce2b of Jan 24, 2018, but the issue has been there for awhile).

**Comment by beniwtv** [comment]
Same thing happens here, with a build from today (Feb 4th, 2018).
