### ISSUE TITLE
Auto-completion "connect"

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#16045]
Godot Master

Is it possible to put the function `connect` on the first place?

![image](https://user-images.githubusercontent.com/4741886/35359904-20970b5a-015c-11e8-81b8-37182c29fcd1.png)

Why is "button_down" on the first place and "button_up" on the last?

![image](https://user-images.githubusercontent.com/4741886/35360128-f489bc46-015c-11e8-8ed1-dd57d01992e7.png)

https://github.com/godotengine/godot/blob/832e2bfcd38965a01a9149d509169dd197e42f58/scene/gui/text_edit.cpp#L5647

**Comment by icnikerazah** [comment]
it's sorted alphabetically
