### ISSUE TITLE
no line when drawing LightOccluder2D polygon

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#16047]
**Godot version:**
Godot 3 RC3

**OS/device including version:**
Windows 7

![occluder_no_line_drawing_bug](https://user-images.githubusercontent.com/10463138/35361141-7e644dac-0160-11e8-8190-953b45e66456.gif)

I expect that a line is visible when drawing the polygon and that the inspector should be updated when finish drawing.

I also expect a pencil cursor.

**Comment by akien-mga** [comment]
CC @poke1024 @groud

**Comment by groud** [comment]
I assign this to myself to keep track of it, but if someone else wants to do it he can.

**Comment by jotson** [comment]
It would also be nice if the UI buttons in the toolbar (above the viewport, next to the View button) for drawing the polygon in occluders was the same as the UI for drawing collision polygons. It's confusing that it's different.

**Comment by puppetmaster-** [comment]
I will close this issue, it is already very old and if there is still a demand I will apply for it again at the new dedicated Godot Improvement Proposals ([GIP](https://github.com/godotengine/godot-proposals)) issue tracker.
