### ISSUE TITLE
Impossible to free a RID

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#16048]
Godot 3.0 RC3

The following script produces an error:

```gdscript
func _ready():
	var rid = VisualServer.shader_create()
	if rid != RID():
		VisualServer.free(rid)
```
...
Ugh damn I can't copy the error from Godot, why is it not printed in any console...
Rewriting it:
`Invalid call to function 'free' in base 'VisualServer'. Expected 0 arguments.`

This is wrong, VisualServer::free obviously takes 1 argument.

I think the function is conflicting with `free` from `Object`... but no error given about that.
The binding must be rewritten `free_rid` like other servers.

**Comment by reduz** [comment]
ah, should be free_rid.. this one is pretty critical

**Comment by reduz** [comment]
can you rebind the function as free_rid() for the script? (its like this in
the other servers) otherwise it clashes with the regular object free()

**Comment by Zylann** [comment]
I could do that easily in my PR that adds the missing binds, but it has been pushed to 3.1. Do you prefer a separate PR?

**Comment by reduz** [comment]
I guess separate PR will be better, yes
