### ISSUE TITLE
Remember "Layout" after resizing

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#16043]
Godot Master

Is this behavior intended?
Is there a way to keep the layout after resizing?

![bug](https://user-images.githubusercontent.com/4741886/35358797-26e7fbee-0158-11e8-8d2a-fba7621655aa.gif)

**Comment by groud** [comment]
> Is this behavior intended?

Yes. The Layout menu is only a helper to set anchors and margins. The layout is not a property of the control itself. The position and size properties of the node that are also helpers setting the margins and anchors values.

The fact is there no way to tell in which direction the node should grow when changing the size, unless reasoning using the anchors value. This would mean that changing the size would also change the position too, but depending on on the anchor position, which is very unintuitive and will probably cause problems with scripts.

> Is there a way to keep the layout after resizing?

No, but honestly I don't think this is required. You can already drag the node from the left to increase it's size, and if you have to reposition-it, just use the layout menu again.

**Comment by AlexHolly** [comment]
Okay, thanks.
