### ISSUE TITLE
Can't intercept InputEvents sent  to pickable CollisionObjects

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#16042]
Godot 3.0 RC2

I had this problem long before, but I was not sure if the feature was hidden somewhere or just inexistent:
basically, I couldn't find a way to mark an InputEvent as handled in the `input_event` signal of a pickable `CollisionObject[2D]`.
This would be especially useful with overlapping objects. It seems the front-most already receives the input first, but it gets forwarded to every next object regardless.

**Comment by volzhs** [comment]
i have same issue.

**Comment by henriquelalves** [comment]
I can confirm this problem, "_input_event" is not working the same as in Godot 2.1.4.

**Comment by mhilbrunner** [comment]
What about SceneTree.set_input_as_handled()?
http://docs.godotengine.org/en/3.0/classes/class_scenetree.html#class-scenetree-set-input-as-handled?

**Comment by KoBeWi** [comment]
> What about SceneTree.set_input_as_handled()?

It doesn't seem to work with `input_event()`.

**Comment by akien-mga** [comment]
Duplicate of #29825 which is more detailed.
