### ISSUE TITLE
use snap button not working when option snap to grid is off

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#16046]
**Godot version:**
Godot 3 RC3

**OS/device including version:**
Windows 7

![snap_bug](https://user-images.githubusercontent.com/10463138/35360231-5676ee42-015d-11e8-854c-e1ab0e3fc74e.gif)

I expect the "use snap (s)" button to control the option snap to grid and turn it on or off automatically.

**Comment by vnen** [comment]
I think this is intended, the snap button enables and disables snapping in general, and in the menu you can select what to snap. CC @groud to correct me.

**Comment by groud** [comment]
Yes, that's on purpose.

**Comment by groud** [comment]
But i should gray-out the entries when the snap is not activated, that would avoid more questions.

**Comment by puppetmaster-** [comment]
and you need first to turn on the option before the snap button "work"

This is for me very confusing.

For me the more logical way is:
- when in move mode (s) turn on/off option grid snapping
- when in rotating mode (s) turn on/off option use rotating snap

Perhaps I'm the only one that has a pr oblem with not matching usecase.

**Comment by groud** [comment]
> and you need first to turn on the option before the snap button "work"

Yes, because smart snapping is more useful without the grid.
But maybe the grid should be displayed only if the snapping is activated, that would avoid the confusion of having a grid with an activated snapping that "does not work".


> For me the more logical way is:
> 
>     when in move mode (s) turn on/off option grid snapping
>     when in rotating mode (s) turn on/off option use rotating snap

Well yeah, the button activates/deactivates snapping in general.

**Comment by puppetmaster-** [comment]
I think the idea is great. It makes sense to connect the two settings (grid visibility and grid snapping).

Very often when I create a new scene, I first set the visibility of the grid and then the snap to grid to on. 

It would be even better if I didn't have to make these settings every time and they would be editor and project settings.
