### ISSUE TITLE
Texture UV Precision Issue

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#16053]
**Godot version:**
3.0 RC3

**OS/device including version:**
Windows, 64.

**Issue description:**
When getting a point from the top of a texture that has two colors:

![imagen](https://user-images.githubusercontent.com/3101690/35365817-bd8a8076-0176-11e8-93ac-3969b90a9b67.png)

texture() returns a mix between the color at the top and the color at the bottom, for example, when getting UV 0.0,0.0:

![imagen](https://user-images.githubusercontent.com/3101690/35365836-e19e4088-0176-11e8-96e0-936477a43561.png)

And then when getting UV 0.0,0.1:

![imagen](https://user-images.githubusercontent.com/3101690/35365847-ed48c1e2-0176-11e8-836f-82225ed14676.png)

UV 0.0,0.6:

![imagen](https://user-images.githubusercontent.com/3101690/35365866-fa7950ca-0176-11e8-8435-64939e5224bc.png)

![imagen](https://user-images.githubusercontent.com/3101690/35365872-006b82e6-0177-11e8-9e49-a414b1f4058b.png)

Seems like a precision issue to me or something.

**Minimal reproduction project:**
[ShaderBug.zip](https://github.com/godotengine/godot/files/1662254/ShaderBug.zip)

**Comment by mrcdk** [comment]
This is how the texture filtering and how the hardware interpolates the pixel colors to get the final color result. If you reimport the texture with filtering disabled it shouldn't happen.

**Comment by EIREXE** [comment]
@mrcdk oh so it's not really a bug?

**Comment by bojidar-bg** [comment]
I tried @mrcdk's solution, and it worked on the test project.

The problem seems to stem from the texture having "Repeat" and "Filter" on, should be like this:
![image](https://user-images.githubusercontent.com/5276727/35390386-ed00cb36-01e3-11e8-988f-b1263b81c43d.png)

After this, it seems to work fine.

**Comment by mrcdk** [comment]
Yes, it's not a bug @EIREXE Basically, when the filtering is disabled, the GPU will pick the closest color it can find but when the filtering is enabled it will combine the surrounding colors to get the final color. This plus repeat enabled makes it get the green and the red color at uv(0, 0) combine them and return yellow. The same will happen at uv(0, 0.5) and uv(0, 1)

![https://www.gamedevelopment.blog/texture-filter/](https://www.gamedevelopment.blog/wp-content/uploads/2017/11/nearest-vs-linear-texture-filter.png)

**Comment by EIREXE** [comment]
Oh alright, thanks!
