### ISSUE TITLE
"popup_centered_minsize" doesn't center the popup

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16069]
**Godot version:**
0181681

**Issue description:**
When showing a popup using the `popup_centered_minsize` method, the popup will not be correctly centered. Here is a image with a centered button used to trigger it:
![screenshot1](https://user-images.githubusercontent.com/30739239/35412442-637466a0-0203-11e8-94f8-278d7c1e8696.png)

**Comment by akien-mga** [comment]
I've seen that too (it's pretty visible with the warning dialog I added to the Mono build, which doesn't start properly centered). I read about this issue a week ago on the issue tracker too, but couldn't find the duplicate again, it might have just been in a comment of an unrelated issue.

**Comment by vnen** [comment]
I have a hunch that this happens because the minimum size is 0,0 by default, and the engine is using that value to centralize, instead of the actual size.

**Comment by YeldhamDev** [comment]
@vnen Your hunch appears to be correct, did it again, but passed the popup's size to the method, and it centralizes it properly. I always thought that the default values being 0 was for it automatically using the popup's minsize, because otherwise there is no sense for these defaults at all.

Also, I think I found another bug. While it the method squishes the popup horizontally, it doesn't affect anything vertically:
![screenshot1](https://user-images.githubusercontent.com/30739239/35420179-34e64a72-0223-11e8-856d-a6897e567f0e.png)

**Comment by Mr-Slurpy** [comment]
I think it might be that the window title size is not being taken into account when calculating the size.
Correct:
![popup_correct](https://user-images.githubusercontent.com/15792219/36357173-2f9b2abc-14c8-11e8-9c84-854f44d9160d.PNG)
Wrong:
![popup_wrong](https://user-images.githubusercontent.com/15792219/36357176-347b44e0-14c8-11e8-8942-7e371b4dba70.PNG)

**Comment by KidRigger** [comment]
@Mr-Slurpy Are you working on this? Or can I?

**Comment by Mr-Slurpy** [comment]
@KidRigger You can work on it.
