### ISSUE TITLE
ProjectSettings.has produce error

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#16078]
**Godot version:**

3.0 rc3 76ec72800

**OS/device including version:**

not related

**Issue description:**

This is what ProjectSettings description says

> Contains global variables accessible from everywhere. Use the normal Object API, such as "ProjectSettings.get(variable)", "ProjectSettings.set(variable,value)" or **"ProjectSettings.has(variable)"** to access them. Variables stored in project.godot are also loaded into ProjectSettings, making this object very useful for reading custom game configuration options.

but there is no `has` method with `Object` class.
```gdscript
ProjectSettings.has("something") 
# error : Invalid call. Nonexistent function 'has' in base 'ProjectSettings'.
```

I'm not sure what is right.
`Object` should have `has` method or remove `ProjectSettings.has` part in description.

**Steps to reproduce:**
just put this somewhere and run.
```gdscript
ProjectSettings.has("something")
```

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
The docs should be changed to `has_setting`.

**Comment by volzhs** [comment]
this sentence should be changed to use `get_settings`, `set_settings`, `has_settings` then

> Use the normal Object API, such as "ProjectSettings.get(variable)", "ProjectSettings.set(variable,value)" or "ProjectSettings.has(variable)" to access them.
