### ISSUE TITLE
Nonexistent "_get_minimum_size" method inside Control

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16074]
**Godot version:**
 76ec728

**Issue description:**
It appears that there is a method called `_get_minimum_size` inside Control, which doesn't exist at all to begin with.

**Comment by vnen** [comment]
It doesn't exist because it's meant to be overridden by scripts.

**Comment by YeldhamDev** [comment]
@vnen I see. But in the docs, it states that it returns Vector2, but if it's overridable, it could return anything, right?

It also has a very similar description to the normal `get_minimum_size` method, which added to my confusion.

**Comment by vnen** [comment]
If you are making custom controls, you'll need some way to tell the engine what's the minimum size. I'm not sure exactly why not just override `get_minimum_size()`, but I've seen this pattern before.
