### ISSUE TITLE
Changing a node's type will remove most signals attached to it (but leave others intact)

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16075]
**Godot version:**
76ec728

**Issue description:**
Self-explanatory:
![peek 2018-01-26 01-05](https://user-images.githubusercontent.com/30739239/35424568-bc58a85c-023b-11e8-869e-cb62ef7b5910.gif)

**Comment by Zylann** [comment]
But which signals were they? Maybe they got removed because the new node doesn't have them

**Comment by YeldhamDev** [comment]
@Zylann It's about the signals from other nodes, not itself.

**Comment by DualMatrix** [comment]
Is there an example project? I can't reproduce this with only the info in the gif

**Comment by YeldhamDev** [comment]
@DualMatrix Sorry for the late response.

There's no need for an example project, all you need to do is:
- Create a scene with a root node and a child.
- Connect a signal from the child to the root node.
- Change the root node's type.
- The connection will be gone.

This error will be outputted as well: `Attempt to connect signal '[child node].[signal name]' to nonexistent method '[node type].[function name]'`

**Comment by KoBeWi** [comment]
Doesn't seem to happen in 3.1. You can connect to any method and it works fine even when you change to type without that method.

**Comment by YeldhamDev** [comment]
@KoBeWi Yep, closing it.
