### ISSUE TITLE
Some Android devices not playing sound

### ISSUE THREAD

**Issue by lagemanngui** [godotengine/godot#16084]
**Godot version:**
Godot 3.0 rc3

**Issue description:**
I've published an app made with Godot, around 45 downloads now but some users are reporting that sounds are not playing (while others had no problem at all). The sound files are in .ogg format.
The two devices with problems are: LG G4 and Moto Z Play.

Someone have a clue if this is a real bug or if its related to the sound driver version or devices specifications?

LG G4
![Screen1](https://preview.ibb.co/gfWD6w/i1.jpg)

Moto Z Play
![Screen2](https://preview.ibb.co/gimwRw/i2.jpg)

Full access to project in [Github](https://github.com/lagemanngui/audiodecultura)
Download from [Play Store](https://play.google.com/store/apps/details?id=com.pixeltroop.audiodecultura) (in portuguese)

Thank you.

**Comment by lagemanngui** [comment]
Another device with sound issues.

Galaxy S6 Edge:
![Screen3](https://preview.ibb.co/jwdrtb/s6edge.jpg)

I was looking into the Project Settings/Audio and found some variables I cant understand/find in the docs what they do. Someone can explain or tell if it can be related to the problem?

In *Project/Project Settings/Audio*
* **Channel Disabe Threshold Db**
* **Channel Disable Time**

Also, what would be the **Driver** options?

**Comment by jonglae** [comment]
Linux godot rc3
linux godot RC3 is didn't export andorid 
and show message unfortunatly app stop

**Comment by jonglae** [comment]
![_008](https://user-images.githubusercontent.com/12964975/35459198-79c5abc4-0322-11e8-97dd-de2e11540576.png)

**Comment by akien-mga** [comment]
@jonglae Please don't hijack other people's issues.

**Comment by jonglae** [comment]
@akien-mga yea i will remove my post
thank you for your teaching

**Comment by vgmoose** [comment]
Was this issue ever resolved / encountered by anyone else? I exported a Godot 3 app for Android and am also observing it's not producing sound (Essential Phone PH1) via AudioStreamPlayer2D with .wav files. The same code and files has sound working on PC and iOS.

**Comment by Calinou** [comment]
@lagemanngui Can you still reproduce this issue on Godot 3.2.1 or [3.2.2beta3](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-3)?

**Comment by akien-mga** [comment]
No answer, so closing.

If you can still reproduce it, please comment and ensure that a minimal reproduction project is available.

**Comment by cetical** [comment]
Godot 4, code is as below, works completely fine on PC but fails on my android phone (Xiaomi 13T)

```
func playsound() -> void:
	var random_sound = sound_streams[randi() % sound_streams.size()]
	audio_player.stream = random_sound
	audio_player.play()
```
