### ISSUE TITLE
Exported project with custom c++ module crashes on start.

### ISSUE THREAD

**Issue by tommila** [godotengine/godot#16087]
**Godot version:**
git commit a98e9496eb71554656c7c1eed9a69d20aed9886c

**OS/device including version:**
OS:	Debian GNU/Linux 9.3 (stretch)

**Issue description:**
Tried to export a project that includes a custom c++ module. Crashed on start. Works great in editor.
Heres the error log:

> No touch devices found
> OpenGL ES 3.0 Renderer: Gallium 0.4 on AMD POLARIS10 (DRM 3.8.0 / 4.9.0-5-amd64, LLVM 3.9.1)
> GLES3: max ubo light: 409
> GLES3: max ubo reflections: 455, ubo size: 144
> ARVR: Registered interface: Native mobile
> SCRIPT ERROR: GDScript::load_byte_code: Compile Error: Identifier not found: Summator
>    At: res://Node.gdc:5.
> ERROR: load_byte_code: Method/Function Failed, returning: ERR_COMPILATION_FAILED
>    At: modules/gdscript/gdscript.cpp:772.
> ERROR: load: Condition ' err != OK ' is true. returned: RES()
>    At: modules/gdscript/gdscript.cpp:1848.
> ERROR: _load: Failed loading resource: res://Node.gdc
>    At: core/io/resource_loader.cpp:186.
> ERROR: poll: res://Node.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Node.gd
>    At: scene/resources/scene_format_text.cpp:439.
> ERROR: load: Condition ' err != OK ' is true. returned: RES()
>    At: core/io/resource_loader.cpp:149.
> ERROR: _load: Failed loading resource: res://Node.tscn
>    At: core/io/resource_loader.cpp:186.
> ERROR: start: Failed loading scene: res://Node.tscn
>    At: main/main.cpp:1613.
> 

**Steps to reproduce:**
Create a Summator module as it is shown in the documents: http://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html#creating-a-new-module
Compile Godot.
Create minimal script that uses the summator. 
Export the project and run it.

**Comment by akien-mga** [comment]
Can you share your module code and the project that uses it?

**Comment by vnen** [comment]
Did you also compiled the export template?

**Comment by tommila** [comment]
No... I guess I have to do that?

**Comment by vnen** [comment]
Yes, the provided export templates won't have your module.

**Comment by tommila** [comment]
Yeah, that did the trick. In my defense there should be some mention about compiling your own export templates at the custom module creation tutorial.

Thanks for the help!

**Comment by vnen** [comment]
Feel free to open an issue about that in the [documentation repository](https://github.com/godotengine/godot-docs).

**Comment by tommila** [comment]
Sure thing.
