### ISSUE TITLE
parse_json: Document that JSON does not preserve order like Godot's dicts

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#16099]
Godot Master
```
extends Node
 
 
func _ready():
    var dict = parse_json('{"D":1,"C":2,"B":3,"A":4}')
    print(dict)
 
# Output : (A:4), (B:3), (C:2), (D:1)
```

**Comment by vybr** [comment]
Tested it with a few more letters, it seems to put the keys in alphabetical order.

**Comment by vnen** [comment]
Technically JSON has no obligation to keep the key order.

**Comment by Hoten** [comment]
Json, nor dictionaries, are designed to preserve ordering.

**Comment by AlexHolly** [comment]
But Godot 3.0 Dictionaries do preserve order, so I was expecting it in this case too.

**Comment by Hoten** [comment]
Oh, I didn't realize that. Still learning GDScript.

Seems the order is reversed. Solution may be as simple as changing a stack to a queue (etc.), which shouldn't have any perf. implications.

**Comment by AlexHolly** [comment]
>But, I would argue that you shouldn't design any application to rely on JSON key ordering.

I agree.

Maybe we can add a note to the docs?

**Comment by mhilbrunner** [comment]
As explained by others above, JSON objects don't guarantee any order for their keys.

From [RFC 7159](http://www.rfc-editor.org/rfc/rfc7159.txt), the JSON spec:
>An object is an **unordered** collection 
>An array is an **ordered** sequence

Indeed, it works fine for arrays: `parse_json('[1,2,3]')` corretly yields `[1, 2, 3]`.

So the only remaining thing is that if someone is familiar with Godot dicts, but unfamiliar with JSON objects, they might not expect this to happen. Will add a note to the docs.
