### ISSUE TITLE
Android exporting and html export Error and stopped APP

### ISSUE THREAD

**Issue by jonglae** [godotengine/godot#16093]
Godot_v3.0-rc3_x11.64

**OS/device including version:**

Ubuntu 16.04 studio LTS

**Issue description:**

Android exporting and html export
i tested a Architechtures
 Arm, x86

**Steps to reproduce:**
simple project--> android export --> app stopped

**Minimal reproduction project:**

**Comment by jonglae** [comment]
![_008](https://user-images.githubusercontent.com/12964975/35459595-2d639294-0324-11e8-98ad-860541589d36.png)

**Comment by jonglae** [comment]
![_009](https://user-images.githubusercontent.com/12964975/35459613-3e5519b0-0324-11e8-9fdc-ff374d4c4074.png)

**Comment by jonglae** [comment]
![_009](https://user-images.githubusercontent.com/12964975/35459626-518b0134-0324-11e8-80de-f2a144c9e91d.png)

**Comment by jonglae** [comment]
![_010](https://user-images.githubusercontent.com/12964975/35459682-8fa07666-0324-11e8-8ccb-a8ec4368a358.png)

**Comment by jonglae** [comment]
![_011](https://user-images.githubusercontent.com/12964975/35459789-f16c306a-0324-11e8-9d3e-32299d3ad89f.png)

**Comment by KoBeWi** [comment]
Looks like related to #16004

**Comment by Calinou** [comment]
@jonglae Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
