### ISSUE TITLE
Tiled importing error, tiles messed...

### ISSUE THREAD

**Issue by marcusViniciusMP** [godotengine/godot#16102]
**Godot version:**
2.1.4

**OS/device including version:**
Ubuntu 16.4 64bits

**Issue description:**
importing tilemap with tiled plug in goes messed

whe i crate a tilemap on tiled editor and import it to godot, tiles goes messed, wrong tiles in wrong positions, also gaps between them. 

![tiles_correct](https://user-images.githubusercontent.com/32377313/35465916-ad00f49e-02e6-11e8-98ca-4e10062c8f48.png)
![tiles_wrong](https://user-images.githubusercontent.com/32377313/35465917-ad2e2e5a-02e6-11e8-8ac7-d485883269ba.png)

**Minimal reproduction project:**

**Comment by vnen** [comment]
This is an issue with the plugin (and already reported at vnen/godot-tiled-importer#63). No reason to report it here unless you found a bug in Godot itself.
