### ISSUE TITLE
Mono Project Fails to Load in 3.0 Mono Stable (Godot crashes)

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#16103]
**Godot version:**
3.0 Stable

**OS/device including version:**
Windows 10

**Issue description:**
When I load my project that is working in beta 2, Godot crashes immediately.

**Steps to reproduce:**
Load the attached project into 3.0 stable.

**Project (it is a small project atm):**
https://app.box.com/s/he178qexzaz7pheqcofew9bjagrbcfok

**EDIT:** Here is the log.
[1517019320.txt](https://github.com/godotengine/godot/files/1669698/1517019320.txt)

**Comment by kakoeimon** [comment]
@11clock Try deleting the .monodirectory in you project directory and then load the project again.

**Comment by mhilbrunner** [comment]
Assuming this is fixed now. If it isn't, please retry with 3.0.2 and after deleting the .mono folder. If it still happens, please let us know!
