### ISSUE TITLE
Prefab with Spatial > Control crashes

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#16112]
I have a scene which just has a Spatial node, which then has a Control node as the child. This scene is imported by other props.
When these other props have duplicate() called on them they crash. 

Crash occurs in Node::move_child

there is this snippet of code:

for (const Map<StringName, GroupData>::Element *E = p_child->data.grouped.front(); E; E = E->next()) {
		E->get().group->changed = true;
	}

E->get().group is NULL, so I get null pointer crash.

If I separate the control with a canvas layer, then it doesn't crash, but then I get strange visibility issues with the Controls

**Comment by Noshyaar** [comment]
Latest commit has if guard so it shouldn't crash, so... version?

https://github.com/godotengine/godot/blob/4a042b1f7a4d6d9d41ab46c5e0f069d848b408f5/scene/main/node.cpp#L345-L347

**Comment by akien-mga** [comment]
Really, there's a reason why we have an issue template that asks for your Godot version... This has been fixed a month ago by #14977.

**Comment by supagu** [comment]
Updated to latest godot and yes, this is now working. Apologies on that, I should have updated to latest before posting this issue.
