### ISSUE TITLE
LineEdit caret blink method name

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#16116]
Godot Master

Any reason why these are called `cursor` and not `caret` in `LineEdit`?

caret_position
```
set_cursor_position(value)  -> set_caret_position(value)
get_cursor_position() -> get_caret_position()
```
caret_blink_speed
```
cursor_set_blink_speed(value) -> set_caret_blink_speed(value)
cursor_get_blink_speed() -> get_caret_blink_speed()
```

caret_blink
```
cursor_set_blink_enabled(value) -> set_caret_blink_enabled(value) 
cursor_get_blink_enabled() -> is_caret_enabled() 
```

`append_at_cursor( String text ) -> append_at_caret( String text )`

**Comment by akien-mga** [comment]
CC @Paulb23. It's too late to change those for 3.0 though, so if there's a real need to rename them, we'll have to keep the deprecated method names for a while to avoid breaking API.

**Comment by AlexHolly** [comment]
When are the next API changes planned? This is not a major thing. I would suggest to keep it until the next changes.

**Comment by akien-mga** [comment]
4.0, or before with a proper deprecation warning over a couple releases.

**Comment by akien-mga** [comment]
Closing as now tracked in #16863.
