### ISSUE TITLE
Make it easy to copy stacktrace content from error console

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#16110]
**Godot version:**
`master` / 511742eb68790345abf594b42b6c25b38360c3df

**OS/device including version:**
_Manjaro Linux 17.1.1_

**Issue description:** (This is a feature proposal)
Currently, the error console only provides a menu item to copy the content of an error message but it lacks a similar feature for its stacktrace.

Sometimes it is difficult to search information about the problem online without being able to copy its stacktrace, and some IDEs (i.e. JetBrains Rider) provides a feature that automatically parses stacktrace from the clipboard to display it inside the editor with links to relevant sources which can be very convenient.

So, it'd be better if we can add a menu item or button to copy stacktrace contents to the clipboard.

**Comment by KoBeWi** [comment]
Seems like "Copy Error" copies whole stack trace now:
```
E 0:00:09:0998   Condition ' !body->get_space() ' is true. returned: false
  <C Source>     servers/physics_2d/physics_2d_server_sw.cpp:1062 @ body_test_ray_separation()
  <Ślad stosu>   Player.gd:99 @ _physics_process()
```
Is that enough, or there should be separate buttons to copy specific stuff instead of literally everything?

**Comment by akien-mga** [comment]
I think it's good enough as is, most of the time you'll want the whole stack trace, and if not you can edit it after pasting where you wanted this content.
