### ISSUE TITLE
"Light Only" 2D shader mode appears to only support shadows for one light at a time

### ISSUE THREAD

**Issue by pshendry** [godotengine/godot#1611]
*Bugsquad edit:* Sample project is now at https://github.com/teedoubleuu/LOS-Test (and is slightly different)

See sample project at https://github.com/pshendry/LOStest. There's a red player (controlled with WASD) and a blue player (controlled with arrow keys), each of which have a Light2D on them.

Each of the red player's light and the blue player's light work fine as a mask on the foreground texture when the other light is disabled, but when both lights are enabled, only one works. (You can test this by disabling the blue player's light and confirming that the red light works correctly as a mask.)

Since the light mask demo works fine with 3 lights masking one texture (shadows are disabled in that demo), it seems that the problem is specific to shadows. Maybe it's a configuration problem, but it seems like only one light's shadows can be used at a time. Is this a technical limitation?

I'll have a look when I get the time to see if I can figure out what's going on, but I figured I'd file a ticket in the meantime. And thanks a ton reduz for implementing this light mask feature pretty much immediately after I mentioned it!

**Comment by okamstudio** [comment]
i think it's fixed, please give it a test

On Fri, Apr 3, 2015 at 2:37 PM, Juan Linietsky <notifications@github.com>
wrote:

> Closed #1611 <https://github.com/okamstudio/godot/issues/1611> via 5d99e15
> <https://github.com/okamstudio/godot/commit/5d99e15e43d5a446b35d48e8a3b08a478f1998a9>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1611#event-272859533>.
>



-- 

*OkamStudio*

**Comment by pshendry** [comment]
Problem persists in the project linked in the issue description. It's specific to the 'Mix' Light2D mode; if I change both lights to the 'Sub' mode, both lights work simultaneously as you would expect (in a subtractive way).

**Comment by reduz** [comment]
I tested the project, but i'm not quite sure i understand the problem

**Comment by pshendry** [comment]
Some images to explain:

When the first light (the one on the red square) is enabled, the texture gets masked like this:
![light_1_on](https://cloud.githubusercontent.com/assets/1829032/6989308/0ce0fffc-da28-11e4-9c18-0258208fdce5.png)

When the second light (the on on the blue square) is enabled, the texture gets masked like this *regardless of whether or not the first light is also enabled*:
![light_2_on](https://cloud.githubusercontent.com/assets/1829032/6989309/0ec6dbd4-da28-11e4-8805-3df29b94406f.png)

What I would expect is that, if multiple light masks are enabled, that the result would be the combination of both, like so:
![lights_on_expected](https://cloud.githubusercontent.com/assets/1829032/6989310/10c7a724-da28-11e4-937f-77ed8692661a.png)

Does that make sense?

**Comment by teedoubleuu** [comment]
I can confirm this issue persists in alpha 1.

**Comment by bojidar-bg** [comment]
Reopening as not fixed yet

**Comment by bojidar-bg** [comment]
@pshendry The project link in the description is dead. Can we get a replacement? 😄

**Comment by teedoubleuu** [comment]
Will alpha 1 project be okay?

**Comment by bojidar-bg** [comment]
@teedoubleuu Yes, as long as it is "minimal", i.e. does not include too much unrelated code/scenes.

**Comment by teedoubleuu** [comment]
https://github.com/teedoubleuu/LOS-Test

There are two lights there in mask mode, but only one of them is casting shadows. I would expect that these lights would combine their masks.

**Comment by bojidar-bg** [comment]
Actually, both are casting their shadows, just one is "out-masking" the other:
![image](https://user-images.githubusercontent.com/5276727/29278409-4e136476-811d-11e7-9699-8375b3a884fd.png)

**Comment by teedoubleuu** [comment]
Shouldn't they NOT mask each other?

**Comment by teedoubleuu** [comment]
If you set the light's shadow color alpha to 0 it does look how would you expect.

**Comment by pshendry** [comment]
Thanks for providing a new sample @teedoubleuu. I've been away from gamedev lately so I won't be of much assistance here debugging. Best of luck!

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
