### ISSUE TITLE
Almost all broken image in project models listed on 3th+ pages

### ISSUE THREAD

**Issue by Omicron666** [godotengine/godot#16128]
**Godot version:**
f12e856

**OS/device including version:**
Win10 64bits

**Issue description:**
Almost all broken image in project models listed on 3th+ pages
![](https://i.imgur.com/p4leK0T.png)

**Steps to reproduce:**
Just check project model pages.

**Comment by bojidar-bg** [comment]
Fixed, sorry about that...:
![image](https://user-images.githubusercontent.com/5276727/35483316-2c370574-0449-11e8-93fd-092f4f8e1619.png)
