### ISSUE TITLE
Add a method to convert user:// paths to absolute paths

### ISSUE THREAD

**Issue by redxdev** [godotengine/godot#16121]
I can't seem to find a method that does this. I'm aware that there is `OS.get_user_data_dir` but that still isn't ideal as then we'd either have to parse for `user://` ourselves or not use `user://`-style paths at all.

The primary use-case I have is actually for C#, where I'd like to use .NET's inbuilt filesystem classes with godot paths rather than having to wrap `Godot.File`, but there are probably others that have different use-cases as well.

Example:

```
OS.get_absolute_path("user://some/file.txt")
```

would return `C:\Users\myuser\AppData\Roaming\MyGame\some\file.txt`. `res://` paths would likely have to error (or return null?) since they aren't actually in the host filesystem.

**Comment by vnen** [comment]
[`ProjectSettings.globalize_path("path")`](http://docs.godotengine.org/en/3.0/classes/class_projectsettings.html#class-projectsettings-globalize-path). Might not be the most intuitive place to be, but it's there.

**Comment by redxdev** [comment]
Aha, that's it. Thank you.
