### ISSUE TITLE
Godot crashes when focus changes to a disabled element.

### ISSUE THREAD

**Issue by Soaku** [godotengine/godot#16131]
**Godot version:**

v.3.0-beta2

**OS/device including version:**

Windows

**Issue description:**

I've created a simple form that user has to fill and connected it's element using the Focus tab in the Inspector. The submit button is disabled by default. When I use tab to move in the form and approach the button, the game crashes. I expected it rather to focus on the next element relative to the button.

**Steps to reproduce:**
1. Place few buttons, set the properties in the "Focus" tab and disable one or few of the buttons. Run the game and try toggling the focus using the "Tab" button on the keyboard.

**Comment by hpvb** [comment]
I tried to reproduce this on current master but was unable to. Can you please supply us with a small project that shows this behavior?

**Comment by Noshyaar** [comment]
Also please use at least [RC3](https://godotengine.org/article/dev-snapshot-godot-3-0-rc-3). It could be fixed before.

**Comment by bruvzg** [comment]
Godot f12e856, macOS - reproducible with only Focus->Next neighbour set.

Test project: [tab_test.zip](https://github.com/godotengine/godot/files/1671164/tab_test.zip)

**Comment by hpvb** [comment]
Thanks @bruvzg it seems that Control::find_next_valid_focus gets in an infinite loop.

**Comment by Soaku** [comment]
@bruvzg That's exactly what I meant. Thanks!
