### ISSUE TITLE
Admins erased this message. there was no swearing.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#16148]
> Is godot designed for children with learning disability?

they erased this message. there was no swearing.

**Comment by Noshyaar** [comment]
Are you sure? I can repost the deleted messages. It contains swearing.

**Comment by Noshyaar** [comment]
And I don't know where you're from. But that message is considered aggressive and disrespectful. We cannot allow that.

**Comment by Noshyaar** [comment]
I said I'll lock if you kept using bad words, and you did, so I locked.

**Comment by Noshyaar** [comment]
Spamming won't help. You account will be deleted by Github.

**Comment by icnikerazah** [comment]
I abused because my message was deleted.

**Comment by icnikerazah** [comment]
I don't care about my account.

**Comment by Noshyaar** [comment]
You also don't care about other's feeling.

**Comment by vnen** [comment]
This is a professional place, if you start offending others we will delete the comments.
