### ISSUE TITLE
json failure to decode example

### ISSUE THREAD

**Issue by jsphpio** [godotengine/godot#16153]
Try to decode this complex example of JSON data: https://bitbucket.org/snippets/backend-coder/geyeqM/godotdata

It fails for me in all of the V3 RC versions

**Comment by vnen** [comment]
Define "fail". Does it give an error? Does it return incorrect data?

Also please show how did you try to decode it (post a code snippet).

**Comment by jsphpio** [comment]
I only get an error object, never any actual data.

**Comment by jsphpio** [comment]
extends Node

var state
var modal
var data= {
	  "regions": [
	    {
	      "id": "as",
	      "name": "Asia",
	      "ports": [
	        "ch1",
	        "ch2",
	        "ch3",
	        "sg",
	        "kr",
	        "jp1",
	        "jp2"
	      ],
	      "exports": [
	        {
	          "id": "leather",
	          "qty": 42000
	        },
	        {
	          "id": "textiles",
	          "qty": 44140
	        },
	        {
	          "id": "electronics",
	          "qty": 36330
	        },
	        {
	          "id": "herbal",
	          "qty": 42140
	        },
	        {
	          "id": "parts",
	          "qty": 5830
	        },
	        {
	          "id": "fruit",
	          "qty": 41220
	        },
	        {
	          "id": "veg",
	          "qty": 14770
	        },
	        {
	          "id": "ceramics",
	          "qty": 9050
	        },
	        {
	          "id": "electrical",
	          "qty": 40900
	        },
	        {
	          "id": "tobacco",
	          "qty": 17850
	        },
	        {
	          "id": "wood",
	          "qty": 23780
	        },
	        {
	          "id": "plastics",
	          "qty": 31510
	        },
	        {
	          "id": "rice",
	          "qty": 16500
	        }
	      ],
	      "imports": [
	        {
	          "id": "leather",
	          "qty": 42000
	        },
	        {
	          "id": "electronics",
	          "qty": 36330
	        },
	        {
	          "id": "parts",
	          "qty": 5830
	        },
	        {
	          "id": "textiles",
	          "qty": 44140
	        },
	        {
	          "id": "toys",
	          "qty": 35360
	        },
	        {
	          "id": "air",
	          "qty": 8920
	        },
	        {
	          "id": "footwear",
	          "qty": 39770
	        },
	        {
	          "id": "rice",
	          "qty": 16500
	        },
	        {
	          "id": "ceramics",
	          "qty": 9050
	        },
	        {
	          "id": "electrical",
	          "qty": 40900
	        },
	        {
	          "id": "plastics",
	          "qty": 31510
	        },
	        {
	          "id": "wood",
	          "qty": 23780
	        }
	      ]
	    },
	    {
	      "id": "ne",
	      "name": "North Europe",
	      "ports": [
	        "ne1",
	        "ne2",
	        "be",
	        "de1",
	        "de2",
	        "fr1",
	        "fr2",
	        "ru",
	        "uk1",
	        "uk2",
	        "uk3",
	        "no",
	        "se"
	      ],
	      "exports": [
	        {
	          "id": "pharma",
	          "qty": 40160
	        },
	        {
	          "id": "electronics",
	          "qty": 36330
	        },
	        {
	          "id": "fruit",
	          "qty": 41220
	        },
	        {
	          "id": "leather",
	          "qty": 42000
	        },
	        {
	          "id": "air",
	          "qty": 8920
	        },
	        {
	          "id": "herbal",
	          "qty": 42140
	        },
	        {
	          "id": "wood",
	          "qty": 23780
	        },
	        {
	          "id": "parts",
	          "qty": 5830
	        },
	        {
	          "id": "rice",
	          "qty": 16500
	        },
	        {
	          "id": "tobacco",
	          "qty": 17850
	        },
	        {
	          "id": "ceramics",
	          "qty": 9050
	        }
	      ],
	      "imports": [
	        {
	          "id": "textiles",
	          "qty": 44140
	        },
	        {
	          "id": "tobacco",
	          "qty": 17850
	        },
	        {
	          "id": "leather",
	          "qty": 42000
	        },
	        {
	          "id": "wood",
	          "qty": 23780
	        },
	        {
	          "id": "plastics",
	          "qty": 31510
	        },
	        {
	          "id": "parts",
	          "qty": 5830
	        },
	        {
	          "id": "pharma",
	          "qty": 40160
	        },
	        {
	          "id": "footwear",
	          "qty": 39770
	        },
	        {
	          "id": "electrical",
	          "qty": 40900
	        },
	        {
	          "id": "electronics",
	          "qty": 36330
	        },
	        {
	          "id": "air",
	          "qty": 8920
	        },
	        {
	          "id": "fruit",
	          "qty": 41220
	        },
	        {
	          "id": "rice",
	          "qty": 16500
	        },
	        {
	          "id": "herbal",
	          "qty": 42140
	        }
	      ]
	    },
	    {
	      "id": "med",
	      "name": "Mediterranean",
	      "ports": [
	        "es1",
	        "es2",
	        "es3",
	        "it1",
	        "it2",
	        "fr1"
	      ],
	      "exports": [
	        {
	          "id": "rice",
	          "qty": 16500
	        }
	      ],
	      "imports": [
	        {
	          "id": "fruit",
	          "qty": 41220
	        },
	        {
	          "id": "ceramics",
	          "qty": 9050
	        },
	        {
	          "id": "wood",
	          "qty": 23780
	        },
	        {
	          "id": "parts",
	          "qty": 5830
	        },
	        {
	          "id": "toys",
	          "qty": 35360
	        }
	      ]
	    },
	    {
	      "id": "ec",
	      "name": "North America - East coast",
	      "ports": [
	        "use"
	      ],
	      "exports": [
	        {
	          "id": "ceramics",
	          "qty": 9050
	        },
	        {
	          "id": "parts",
	          "qty": 5830
	        }
	      ],
	      "imports": [
	        {
	          "id": "ceramics",
	          "qty": 9050
	        },
	        {
	          "id": "plastics",
	          "qty": 31510
	        },
	        {
	          "id": "veg",
	          "qty": 14770
	        },
	        {
	          "id": "air",
	          "qty": 8920
	        },
	        {
	          "id": "textiles",
	          "qty": 44140
	        },
	        {
	          "id": "tobacco",
	          "qty": 17850
	        },
	        {
	          "id": "herbal",
	          "qty": 42140
	        },
	        {
	          "id": "toys",
	          "qty": 35360
	        },
	        {
	          "id": "wood",
	          "qty": 23780
	        },
	        {
	          "id": "leather",
	          "qty": 42000
	        },
	        {
	          "id": "parts",
	          "qty": 5830
	        },
	        {
	          "id": "pharma",
	          "qty": 40160
	        }
	      ]
	    },
	    {
	      "id": "wc",
	      "name": "North America - West coast",
	      "ports": [
	        "usw"
	      ],
	      "exports": [
	        {
	          "id": "fruit",
	          "qty": 41220
	        },
	        {
	          "id": "toys",
	          "qty": 35360
	        },
	        {
	          "id": "air",
	          "qty": 8920
	        }
	      ],
	      "imports": [
	        {
	          "id": "ceramics",
	          "qty": 9050
	        },
	        {
	          "id": "veg",
	          "qty": 14770
	        },
	        {
	          "id": "fruit",
	          "qty": 41220
	        },
	        {
	          "id": "rice",
	          "qty": 16500
	        },
	        {
	          "id": "air",
	          "qty": 8920
	        },
	        {
	          "id": "herbal",
	          "qty": 42140
	        }
	      ]
	    },
	    {
	      "id": "sa",
	      "name": "South America",
	      "ports": [
	        "br"
	      ],
	      "exports": [
	        {
	          "id": "pharma",
	          "qty": 40160
	        },
	        {
	          "id": "electronics",
	          "qty": 36330
	        },
	        {
	          "id": "textiles",
	          "qty": 44140
	        },
	        {
	          "id": "veg",
	          "qty": 14770
	        },
	        {
	          "id": "plastics",
	          "qty": 31510
	        },
	        {
	          "id": "fruit",
	          "qty": 41220
	        },
	        {
	          "id": "air",
	          "qty": 8920
	        },
	        {
	          "id": "wood",
	          "qty": 23780
	        },
	        {
	          "id": "parts",
	          "qty": 5830
	        },
	        {
	          "id": "ceramics",
	          "qty": 9050
	        },
	        {
	          "id": "leather",
	          "qty": 42000
	        },
	        {
	          "id": "rice",
	          "qty": 16500
	        }
	      ],
	      "imports": [
	        {
	          "id": "footwear",
	          "qty": 39770
	        },
	        {
	          "id": "electronics",
	          "qty": 36330
	        },
	        {
	          "id": "wood",
	          "qty": 23780
	        },
	        {
	          "id": "rice",
	          "qty": 16500
	        },
	        {
	          "id": "ceramics",
	          "qty": 9050
	        },
	        {
	          "id": "herbal",
	          "qty": 42140
	        },
	        {
	          "id": "parts",
	          "qty": 5830
	        },
	        {
	          "id": "leather",
	          "qty": 42000
	        },
	        {
	          "id": "textiles",
	          "qty": 44140
	        },
	        {
	          "id": "pharma",
	          "qty": 40160
	        },
	        {
	          "id": "fruit",
	          "qty": 41220
	        },
	        {
	          "id": "veg",
	          "qty": 14770
	        },
	        {
	          "id": "toys",
	          "qty": 35360
	        },
	        {
	          "id": "air",
	          "qty": 8920
	        }
	      ]
	    },
	    {
	      "id": "me",
	      "name": "Middle East and South Asia",
	      "ports": [
	        "uae",
	        "in",
	        "lk"
	      ],
	      "exports": [
	        {
	          "id": "tobacco",
	          "qty": 17850
	        },
	        {
	          "id": "rice",
	          "qty": 16500
	        },
	        {
	          "id": "toys",
	          "qty": 35360
	        },
	        {
	          "id": "wood",
	          "qty": 23780
	        },
	        {
	          "id": "pharma",
	          "qty": 40160
	        }
	      ],
	      "imports": [
	        {
	          "id": "ceramics",
	          "qty": 9050
	        },
	        {
	          "id": "textiles",
	          "qty": 44140
	        }
	      ]
	    },
	    {
	      "id": "au",
	      "name": "Australia",
	      "ports": [
	        "au"
	      ],
	      "exports": [
	        {
	          "id": "plastics",
	          "qty": 31510
	        },
	        {
	          "id": "fruit",
	          "qty": 41220
	        },
	        {
	          "id": "toys",
	          "qty": 35360
	        }
	      ],
	      "imports": [
	        {
	          "id": "parts",
	          "qty": 5830
	        },
	        {
	          "id": "air",
	          "qty": 8920
	        },
	        {
	          "id": "toys",
	          "qty": 35360
	        },
	        {
	          "id": "rice",
	          "qty": 16500
	        },
	        {
	          "id": "fruit",
	          "qty": 41220
	        },
	        {
	          "id": "textiles",
	          "qty": 44140
	        },
	        {
	          "id": "ceramics",
	          "qty": 9050
	        },
	        {
	          "id": "wood",
	          "qty": 23780
	        },
	        {
	          "id": "leather",
	          "qty": 42000
	        },
	        {
	          "id": "footwear",
	          "qty": 39770
	        },
	        {
	          "id": "electronics",
	          "qty": 36330
	        },
	        {
	          "id": "tobacco",
	          "qty": 17850
	        },
	        {
	          "id": "plastics",
	          "qty": 31510
	        },
	        {
	          "id": "herbal",
	          "qty": 42140
	        }
	      ]
	    }
	    ],
	  "ports": [
	    {
	      "id": "ch1",
	      "name": "Shanghai",
	      "loc": "China"
	    },
	    {
	      "id": "ch2",
	      "name": "Shenzhen",
	      "loc": "China"
	    },
	    {
	      "id": "ch3",
	      "name": "Hong Kong",
	      "loc": "China"
	    },
	    {
	      "id": "sg",
	      "name": "Singapore",
	      "loc": "Singapore"
	    },
	    {
	      "id": "kr",
	      "name": "Busan",
	      "loc": "South Korea"
	    },
	    {
	      "id": "jp1",
	      "name": "Tokyo",
	      "loc": "Japan"
	    },
	    {
	      "id": "jp2",
	      "name": "Osaka",
	      "loc": "Japan"
	    },
	    {
	      "id": "ne1",
	      "name": "Rotterdam",
	      "loc": "Netherlands"
	    },
	    {
	      "id": "ne2",
	      "name": "Amsterdam",
	      "loc": "Netherlands"
	    },
	    {
	      "id": "be",
	      "name": "Antwerp",
	      "loc": "Belgium"
	    },
	    {
	      "id": "de1",
	      "name": "Bremerhaven",
	      "loc": "Germany"
	    },
	    {
	      "id": "de2",
	      "name": "Hamburg",
	      "loc": "Germany"
	    },
	    {
	      "id": "fr1",
	      "name": "Le Havre",
	      "loc": "France"
	    },
	    {
	      "id": "ru",
	      "name": "Saint Petersburg",
	      "loc": "Russia"
	    },
	    {
	      "id": "uk1",
	      "name": "Grimsby",
	      "loc": "UK"
	    },
	    {
	      "id": "uk2",
	      "name": "Southampton",
	      "loc": "UK"
	    },
	    {
	      "id": "uk3",
	      "name": "London",
	      "loc": "UK"
	    },
	    {
	      "id": "no",
	      "name": "Bergen",
	      "loc": "Norway"
	    },
	    {
	      "id": "se",
	      "name": "Gothenburg",
	      "loc": "Sweden"
	    },
	    {
	      "id": "es1",
	      "name": "Algeciras",
	      "loc": "Spain"
	    },
	    {
	      "id": "es2",
	      "name": "Valencia",
	      "loc": "Spain"
	    },
	    {
	      "id": "es3",
	      "name": "Barcelona",
	      "loc": "Spain"
	    },
	    {
	      "id": "it1",
	      "name": "Genoa",
	      "loc": "Italy"
	    },
	    {
	      "id": "it2",
	      "name": "Trieste",
	      "loc": "Italy"
	    },
	    {
	      "id": "fr2",
	      "name": "Marseille",
	      "loc": "France"
	    },
	    {
	      "id": "use",
	      "name": "New Jersey",
	      "loc": "USA - East coast"
	    },
	    {
	      "id": "usw",
	      "name": "Long Beach",
	      "loc": "USA - West coast"
	    },
	    {
	      "id": "br",
	      "name": "Santos",
	      "loc": "Brazil"
	    },
	    {
	      "id": "uae",
	      "name": "Dubai",
	      "loc": "UAE"
	    },
	    {
	      "id": "in",
	      "name": "Mumbai",
	      "loc": "India"
	    },
	    {
	      "id": "lk",
	      "name": "Colombo",
	      "loc": "Sri Lanka"
	    },
	    {
	      "id": "au",
	      "name": "Brisbane",
	      "loc": "Australia"
	    }
	    ],
	  "destinations": [
	    {
	      "id": "as",
	      "regions": [
	        "ne",
	        "med",
	        "me",
	        "au",
	        "wc",
	        "sa"
	      ]
	    },
	    {
	      "id": "ne",
	      "regions": [
	        "ec",
	        "sa",
	        "as"
	      ]
	    },
	    {
	      "id": "med",
	      "regions": [
	        "ec",
	        "sa",
	        "as"
	      ]
	    },
	    {
	      "id": "ec",
	      "regions": [
	        "ne",
	        "med",
	        "as"
	      ]
	    },
	    {
	      "id": "wc",
	      "regions": [
	        "as"
	      ]
	    },
	    {
	      "id": "sa",
	      "regions": [
	        "ec",
	        "ne",
	        "med",
	        "as"
	      ]
	    },
	    {
	      "id": "me",
	      "regions": [
	        "as"
	      ]
	    },
	    {
	      "id": "au",
	      "regions": [
	        "as"
	      ]
	    }
	    ],
	  "distances": [
	    {
	      "id": "sa",
	      "values": [
	      {
	        "region": "ec",
	        "dist": 7
	      },
	      {
	        "region": "med",
	        "dist": 8
	      },
	      {
	        "region": "ne",
	        "dist": 8
	      },
	      {
	        "region": "as",
	        "dist": 15
	      }
	      ]
	    },
	    {
	      "id": "ne",
	      "values": [
	      {
	        "region": "ec",
	        "dist": 0
	      },
	      {
	        "region": "ne",
	        "dist": 7
	      },
	      {
	        "region": "med",
	        "dist": 11
	      },
	      {
	        "region": "me",
	        "dist": 17
	      },
	      {
	        "region": "as",
	        "dist": 23
	      },
	      {
	        "region": "au",
	        "dist": 27
	      },
	      {
	        "region": "wc",
	        "dist": 34
	      }
	    ]
	    }
	    ],
	  "routes": [
	    {
	      "id": "ne-ec",
	      "name": "North Europe - North America"
	    },
	    {
	      "id": "ec-sa",
	      "name": "North America East Coast - South America"
	    },
	    {
	      "id": "ne-sa",
	      "name": "North Europe - South America"
	    },
	    {
	      "id": "med-sa",
	      "name": "Mediterranean - South America"
	    },
	    {
	      "id": "ne-as",
	      "name": "Asia - North Europe"
	    },
	    {
	      "id": "med-as",
	      "name": "Asia - Mediterranean"
	    },
	    {
	      "id": "me-as",
	      "name": "Asia - Middle East"
	    },
	    {
	      "id": "as-au",
	      "name": "Asia - Australia"
	    },
	    {
	      "id": "as-wc",
	      "name": "Asia - North America"
	    },
	    {
	      "id": "sa-as",
	      "name": "Asia - South America"
	    }
	    ],
	  "goods":  [
	      {
	        "id": "wood",
	        "name": "Wood",
	        "value": 7050
	      },
	      {
	        "id": "parts",
	        "name": "Vehicle parts and accessories",
	        "value": 41920
	      },
	      {
	        "id": "toys",
	        "name": "Toys, games and sports equipment",
	        "value": 36470
	      },
	      {
	        "id": "tobacco",
	        "name": "Tobacco",
	        "value": 46640
	      },
	      {
	        "id": "textiles",
	        "name": "Textiles snd clothing",
	        "value": 49710
	      },
	      {
	        "id": "rice",
	        "name": "Rice",
	        "value": 21780
	      },
	      {
	        "id": "plastics",
	        "name": "Plastics",
	        "value": 47090
	      },
	      {
	        "id": "pharma",
	        "name": "Pharmaceutical products",
	        "value": 39600
	      },
	      {
	        "id": "leather",
	        "name": "Leather",
	        "value": 9720
	      },
	      {
	        "id": "herbal",
	        "name": "Herbal medicines, supplements and tonics",
	        "value": 5790
	      },
	      {
	        "id": "footwear",
	        "name": "Footwear",
	        "value": 29010
	      },
	      {
	        "id": "electrical",
	        "name": "Electrical items",
	        "value": 43750
	      },
	      {
	        "id": "electronics",
	        "name": "Electronic equipment",
	        "value": 9270
	      },
	      {
	        "id": "veg",
	        "name": "Edible vegetables, roots and tubers",
	        "value": 14380
	      },
	      {
	        "id": "fruit",
	        "name": "Edible fruits, nuts and peel",
	        "value": 26060
	      },
	      {
	        "id": "ceramics",
	        "name": "Ceramics",
	        "value": 42850
	      },
	      {
	        "id": "air",
	        "name": "Aircraft parts",
	        "value": 36620
	      }
	    ],
	  "ships":  [
	      "Pacific Sultan",
	      "Ocean Galaxy",
	      "ODX Sultan",
	      "Atlantic Titan",
	      "Southern Andromeda",
	      "Maerk Star",
	      "Southern Titan",
	      "Atlantic Fortune",
	      "ODX Globe",
	      "Maerk Globe",
	      "Northern Sultan",
	      "Maerk Galaxy",
	      "Pacific Andromeda",
	      "Pacific Galaxy",
	      "Maerk Andromeda",
	      "Atlantic Galaxy",
	      "Maerk Orb",
	      "Ocean Fortune",
	      "Orsk Galaxy",
	      "ODX Titan",
	      "Ocean Globe",
	      "ODX Orb",
	      "Orsk Fortune",
	      "Pacific Star",
	      "Orsk Sultan",
	      "Northern Titan",
	      "Pacific Fortune",
	      "Southern Galaxy",
	      "Northern Orb",
	      "Orsk Andromeda",
	      "Southern Sultan",
	      "ODX Andromeda",
	      "Atlantic Andromeda",
	      "Pacific Titan",
	      "Ocean Orb",
	      "Orsk Titan",
	      "Atlantic Sultan",
	      "Maerk Sultan",
	      "Orsk Star",
	      "Southern Orb",
	      "Ocean Andromeda",
	      "ODX Fortune",
	      "Pacific Globe",
	      "Northern Globe",
	      "Northern Fortune",
	      "Pacific Orb",
	      "Ocean Star",
	      "Ocean Sultan",
	      "Atlantic Orb",
	      "Northern Andromeda",
	      "Maerk Fortune",
	      "Southern Globe",
	      "Ocean Titan",
	      "Southern Star",
	      "Northern Galaxy",
	      "Southern Fortune",
	      "Atlantic Star",
	      "Orsk Globe",
	      "ODX Star",
	      "Northern Star",
	      "Atlantic Globe",
	      "Orsk Orb",
	      "ODX Galaxy",
	      "Maerk Titan"
	    ]
	}

func _ready():
	# _load_data()
	state = {
	  "dummy": true
	}

func _load_data():
	# JSON parsing not working!
	var file = File.new()
	file.open("res://Data/test.json", file.READ)
	var json = file.get_as_text()
	var json_result = JSON.parse(json)
	file.close()
	if json_result.error != 0:
		print("JSON parse error on line: " + data.error_line)
	else:
		data = json_result.result

func get_item_by_id(id, key):
	for item in data[key]:
		if id == item["id"]:
			return item

**Comment by jsphpio** [comment]
There is something going on in the C++ code that always triggers a failure. I would debug it myself but I could not set up a suitable environment on my windows 10 PC.

**Comment by mrcdk** [comment]
Can't reproduce in https://github.com/godotengine/godot/commit/f12e8568d43de853e0b98588e7f132a61a92fc45

![https://i.imgur.com/Menf0Ww.png](https://i.imgur.com/Menf0Ww.png)

**Comment by Dillybob1992** [comment]
You told me on facebook it was working..

**Comment by Dillybob1992** [comment]
Working on RC3
![](https://i.gyazo.com/50ba8e9eab897eabf094cc1d210bb8e3.png)

**Comment by Dillybob1992** [comment]
@jsphpio You can't assign JSON liek that to a variable, you need to have it as text

**Comment by jsphpio** [comment]
Thanks guys. My misunderstanding.
