### ISSUE TITLE
Gizmos become hard to see under some circumstances

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#16154]
Godot 3.0 RC3

Rewritten from https://github.com/godotengine/godot/issues/15198

There are situations in which gizmos become hardly visible, if visible at all, especially with materials outputting specific colors.
There is a need for gizmos that are shaded in a way they can always be visible regardless of whatever is put in the scene.

![image](https://user-images.githubusercontent.com/1311555/35485691-78f64432-0463-11e8-998c-24d204a86262.png)
Can you see Y axes? I can't. Maybe squinting a lot.

![image](https://user-images.githubusercontent.com/1311555/35485740-fbdeb410-0463-11e8-8abb-1f6a943be4aa.png)
Going further and... can't see blue axes anymore.

In some cases it is really supposed to look like this in a game. But these are gizmos, they are editor tools, they need to be usable regardless of the scene.

**Comment by wlodeqp** [comment]
In Godot 3.0.2 you can change gizmos size and opacity. To do that go to EditorSettings -> Editors -> 3D and on the bottom there are two options "Manipulator Gizmo Size" and "Manipulator Gizmo Opacity". After opacity change you need restart Godot.
![gizmos](https://user-images.githubusercontent.com/35608701/39084977-34dc430e-457d-11e8-9ed3-60d4e146e4e6.png)

**Comment by Zylann** [comment]
I may sound picky, but it still doesn't solves the case where the background has the same color, because gizmos are unshaded.

**Comment by Calinou** [comment]
I wonder what can be done to make them visible regardless of the background color while still keeping their red/green/blue colors in all circumstances. Maybe draw a thin black outline around them in some way?

**Comment by Zylann** [comment]
@Calinou that's why I suggested shaded rendering, it doesn't require a postprocessing shader and it makes gizmos render with a gradient which creates a two-color visibility. Flat parts can use an outline with basic line rendering.

**Comment by Skaruts** [comment]
@Calinou add a white or grey outline. If the gizmo becomes invisible, the outline will still give it away. (Check UE's rotation gizmo.)

Back when I played shooters that's how I solved my problem with not being able to see the crosshairs in some places. 

That said, I think the opacity could be greater by default. That alone should keep them visible in a wider range of circumstances. Both UE and Blender have quite opaque gizmos, if not fully, perhaps for that reason.

**Comment by Sakari369** [comment]
![Screenshot 2020-12-14 at 21 04 56](https://user-images.githubusercontent.com/1212726/102123941-4d4b0500-3e50-11eb-8e6d-5acb8961906e.png)
Another example where seeing the gizmos becomes pretty much impossible.

Will post here to make me also remember, I can of course compile a custom version where the gizmo opacity is set to 1.0.
Should something more opaque made default ?

I don't see how the transparency helps gizmos anyway, you want to see them, and they are small compared to most geometry, why not have them be opaque so you can assure the user can see the gizmos all the time ?

**Comment by Calinou** [comment]
> Will post here to make me also remember, I can of course compile a custom version where the gizmo opacity is set to 1.0. to test it out first slightly_smiling_face

You can already increase the manipulator gizmo opacity in the Editor Settings.

**Comment by Sakari369** [comment]
> > Will post here to make me also remember, I can of course compile a custom version where the gizmo opacity is set to 1.0. to test it out first slightly_smiling_face
> 
> You can already increase the manipulator gizmo opacity in the Editor Settings. In hindsight, I think it's a good idea to make the manipulaton gizmo almost opaque by default (like Blender), especially now that it's a bit smaller.
> 
> For reference, this is how manipulation gizmos look like in Blender 2.91:
> 
> ![Manipulation gizmos in Blender](https://user-images.githubusercontent.com/180032/102128848-c0ec1280-3e4e-11eb-88cd-3294b855d4fa.png)
> 
> That said, if you make the current manipulation gizmos opaque, you won't have visual feedback when you hover them anymore. You'll hve to modify the source code to lighten their colors instead.

Ok thanks for the info, I tried looking for a setting but could not at least quickly looking at it.

Set the Manipulator Gizmo Opacity to 1.0 under "Editors/3D", but still the gizmo stays transparent. Ok seems restarting the editor applies the opacity.

Visual feedback for hover with the opacity doesn't feel like the right solution then if it limits the initial opacity to something that can't be seen.

**Comment by Zylann** [comment]
What about https://github.com/godotengine/godot/issues/16154#issuecomment-383298599 ?

**Comment by Calinou** [comment]
@Zylann I think it would be better to open a proposal for that :slightly_smiling_face:
