### ISSUE TITLE
Sprite bugging, black lines appearing

### ISSUE THREAD

**Issue by gustavottc** [godotengine/godot#16151]
I have this problem, the photo is self explanatory, can you help me please?

![image](https://user-images.githubusercontent.com/20030153/35484947-3271e01c-043f-11e8-9377-6edc65bf3f1d.png)

**Comment by Noshyaar** [comment]
Need: version, graphic driver
Optional: minimal project

**Comment by gustavottc** [comment]
thanks, this solved
