### ISSUE TITLE
Expose a game-accessible UndoRedo type

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#16155]
**Godot version:**
Godot 3.x

**Issue description:**
The `UndoRedo` object is currently only available to the `EditorInterface`-accessible classes (so `EditorPlugin` and `EditorScript`), but the ability to easily undo and redo both property changes and method calls would actually be really useful for a variety of games. I believe the engine could benefit from creating a game-accessible version of this class. Maybe rename the current one to `EditorUndoRedo` and have the new one assume the `UndoRedo` name?

**Comment by willnationsdev** [comment]
Nevermind, I somehow just didn't realize that this class is ALREADY accessible. Closing.

**Comment by LeonardMeagher2** [comment]
Should the documentation change to say this is possible?

**Comment by willnationsdev** [comment]
No need. I just didn't realize that I could already instantiate an UndoRedo object whenever I wanted to.
