### ISSUE TITLE
Unable to fire several HTTPRequest simultaneously 

### ISSUE THREAD

**Issue by fpg1503** [godotengine/godot#16165]
**Godot version:**
3.0 RC3

**OS/device including version:**
macOS 10.13.1 Beta (17B35a)

**Issue description:**
I'm unable fire several `HTTPRequest`s  at once. Am I doing something wrong? Should I use several instances manually? Is it a bad practice reusing `HTTPRequest`s? Do I need to turn `use_threads` on? Is it off by default? (I'm a Godot noob so I may be doing several things wrong).

**Steps to reproduce:**
Fire several `HTTPRequest`s using the same `HTTPRequest` instance, not all will go through.

**Comment by Noshyaar** [comment]
I think if `get_http_client_status()` is not `STATUS_DISCONNECTED` you can't make more requests.

I solved this by making a queue and process requests one after another.

**Comment by raymoo** [comment]
@Noshyaar What if you want to run requests concurrently?

**Comment by Noshyaar** [comment]
I'd create another HTTPRequest node.

**Comment by fpg1503** [comment]
So if I want to do several requests simultaneously I need an `HTTPRequest` pool? Is this a good practice? Will having several `HTTPRequest`s in the node hierarchy degrade the performance (when they're not performing requests)? Destroying and recreating `HTTPRequest` nodes looks like a bad idea to me.

The new 3.0 docs state that `use_threads` "if `true` multithreading is used to improve performance.". Should I use threads when using a request pool? Is there any reason why I should set `use_threads` to `false`?

**Comment by fpg1503** [comment]
You can take a look at my current implementation using client pools and request queues [here](https://github.com/fpg1503/GGJ2018/blob/4c0dc6dc258796c7c848ac7f3e5542ac3d9a58b4/client/RestClient/RestClient.gd). Does that make sense? Is this the best way to handle several requests simultaneously?

**Comment by reduz** [comment]
Only one request per node is allowed.
You don't need a pool, though. Just create the node when making a connection and erase it when done.

**Comment by Faless** [comment]
As reduz said, you can't make more than one request per node at the same time (and you have to call `cancel_request()` before making a new one after the first completed).

If you do make very frequent requests to the same server which supports keep-alive and you want to squash some more performance you can use HTTPClient (which again, only do one request at a time, but keep the connection open if the server supports it).
But unless you actually find a bottleneck there I would simply create a new HTTPRequest node every time (or keep a pool of them as workers and queue requests).
The performance difference should be negligible in most use cases.

Closing.

**Comment by DomDumont** [comment]
> erase it when done.

Hi, It seems it's not possible anymore in Godot 4.  I did not find a way to get the "source" http_request when I am in the _on_request_completed handler. With Godot 3 I used to add an extra parameter to the connect function like this http_request.connect("request_completed", self, "_on_request_completed", **[http_request]**) but this does not work anymore.
