### ISSUE TITLE
Create theme From Current Editor Cause lagging and slow

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#16163]
**Godot version:**
Godot 3 RC 3

**Issue description:**
The same issue : https://github.com/godotengine/godot/issues/15823

but this cause Lagging and make the Engine Slow ... then i realized my Scene size increased from 6KB to more then 5MB  !!!

![bug](https://user-images.githubusercontent.com/34812055/35520175-971372b0-0516-11e8-8804-4802bafb3221.jpg)

and after restarting Godot , i'm not able to open the scene

**Steps to reproduce:**
Create theme using "Create From Current Editor" , then work with your project a little bit you will notice the Engine is start lagging and slowing down

**Comment by AlexHolly** [comment]
I have the same issue. I think the slowness comes from this messae beeing spammed.
```
ERROR: texture_get_data: Condition ' !texture->active ' is true. returned: Ref<Image>()
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1013.
```
![image](https://user-images.githubusercontent.com/4741886/44948002-32d2f600-ae16-11e8-8351-102c4516ca51.png)

**Comment by Sslaxx** [comment]
Perhaps, but 5MB seems a bit excessive, and if it cannot be opened then there is clearly some kind of file corruption going on.

**Comment by KoBeWi** [comment]
The error spam seems to be fixed in 3.1. As for the slowdows, if the theme is built in the scene, saving/loading the scene is longer, because the theme is big. I don't see anything other happening.

**Comment by Calinou** [comment]
The editor theme contains a lot of images, which are being saved as Base64 if you save the theme as a `.tres` file or built into a `.tscn` file. Saving to a binary `.res` file or in a binary `.scn` file should help decrease loading times.

**Comment by pycbouh** [comment]
The way the themes are created from other themes has been changed in https://github.com/godotengine/godot/pull/46808. You can now select the parts you want to copy and therefore exclude potentially unnecessary elements, like icons. Or you can include individual icons. Either way, the bigger size is expected here and indeed can cause problems if embedded in your scenes.
