### ISSUE TITLE
SpriteFrames editor forces window to be wider/taller than screen

### ISSUE THREAD

**Issue by Jerferson4** [godotengine/godot#16164]
**Godot version:** Godot_v3.0-rc3_win64

**OS/device including version:** Windows 10 64bits, screen size 1024*768

**Issue description:** will it's just a simple and harmless issue: when I create an animated sprite and go to 'spector' and set 'new spriteframes' at 'frames' and then open the spriteframes box it just cause a part the right boxes (the ones below the play button) to go off the screen, and even when I close the spriteframes box the right boxes continue hiding some parts. I aways have to minimize and then maximize the window to solve temporarely. 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This issue has the same cause as https://github.com/godotengine/godot/issues/26835.

**Comment by akien-mga** [comment]
Consolidating in #26835.
