### ISSUE TITLE
platformer 3d demo crash on android 6

### ISSUE THREAD

**Issue by jfcg** [godotengine/godot#16168]
**Godot version:**
4caadae0f15d658d464d125829039a2e35c68124
(3.0-rc3)

**OS/device including version:**
Android 6.0.1/[Redmi 4 prime](https://www.gsmarena.com/xiaomi_redmi_4_prime-8263.php)

**Issue description:**
platformer3d starts on my phone, i see the godot splash screen and hear the robot's walking sound. then it crashes.

**Steps to reproduce:**
- build godot editor & templates for x11/android
- export platformer3d & install apk on phone
- click on the icon on my phone

**Minimal reproduction project:**
3d/platformer demo

platform-tools/adb logcat godot:W DEBUG:E *:S
[debug.txt](https://github.com/godotengine/godot/files/1675535/debug.txt)

**Comment by Calinou** [comment]
For those wondering, the [Redmi 4 Prime's GPU supports OpenGL ES 3.1](https://www.notebookcheck.net/Qualcomm-Adreno-506.175993.0.html.

**Comment by vnen** [comment]
Can you test with 3.0 stable? https://godotengine.org/download

**Comment by jfcg** [comment]
same crash
[debug.txt](https://github.com/godotengine/godot/files/1678906/debug.txt)

**Comment by java-py-c-cpp-js** [comment]
I've tested some over 3D examples: The Kinematic Character 3D and the Material Tester aren't working, either. It seems to be a problem of Godot 3 3D on Android in general. 2D examples like Platformer 2D are working.

**Comment by vnen** [comment]
A lot of users are having trouble with Adreno chips. My phone with a Mali-T720 chip can run the Platform 3D demo. (albeit not with good performance).

**Comment by Acwok** [comment]
Same issue here with godot 3.2.1 and Android 6.0.1/ Xiaomi Redmi 3S.  
2D projects work fine but 3D ones don't.

**Comment by Acwok** [comment]
@vnen Is there any plan to make godot support Adreno chips for 3D games ?

**Comment by akien-mga** [comment]
Use OpenGL ES 2.0 (the GLES2 renderer) on such older phones with Adreno GPU and outdated Android drivers. The OpenGL ES 3.0 drivers of these devices are broken beyond repair, and the main reason why we developed the GLES2 backend for Godot 3.1.

**Comment by Acwok** [comment]
Just wanted to let you know that moving my game to GLES2 worked.  
I had to convert GPU particle to CPU particle as mentionned in the doc: https://docs.godotengine.org/en/stable/tutorials/misc/gles2_gles3_differences.html
Thanks.
