### ISSUE TITLE
Scoop install godot still gets 2.1.4

### ISSUE THREAD

**Issue by mundusnine** [godotengine/godot#16172]
**Godot version:**
3.0

**OS/device including version:**
Windows/ scoop command-line tool

**Issue description:**
The person who maintains the scoop script file probably needs to update his script from 2.1.4 
with scoop install godot I get:
Installing 'godot' (2.1.4) [64bit]
Godot_v2.1.4-stable_win64.exe.zip (12.5 MB) [=========================] 100%
Checking hash of Godot_v2.1.4-stable_win64.exe.zip... ok.
Extracting... done.
Running pre-install script...
Linking ~\scoop\apps\godot\current => ~\scoop\apps\godot\2.1.4
Creating shim for 'godot'.
Creating shortcut for Godot (godot.exe)
'godot' (2.1.4) was installed successfully!

**Steps to reproduce:**
scoop install godot

**Comment by TheAspiringHacker** [comment]
I think that you should talk to the Scoop developers, not the Godot developers...

**Comment by vnen** [comment]
CC @Calinou

**Comment by akien-mga** [comment]
Yeah third party binaries are outside the scope of this repository. (And guys, give us some air, we literally just released it...)

**Comment by mundusnine** [comment]
Just to clarify it's a .json file maintained by someone in the community @SinisterBlade . If I post an issue on scoop they will tell me that the person has to update their json and that it's not related to the scoop binaries, hence why I posted here.

**Comment by akien-mga** [comment]
Well usually registers to update versions in thirdparty package managers have to be handled in the bug trackers relative to the package managers' repository. You should ask the Scoop community where is the proper place to request a package update, but it's definitely not the upstream project's repository (what would we do of requests to update Debian, Fedora or Linux packages that we don't necessarily maintain ourselves?).

**Comment by mundusnine** [comment]
Ok thanks ! I get what you mean. I will ask around. Good day :)

**Comment by Calinou** [comment]
I just opened https://github.com/lukesampson/scoop-extras/pull/764.
