### ISSUE TITLE
Error when clearing a Tree then immediately creating a new item in it.

### ISSUE THREAD

**Issue by RodeoMcCabe** [godotengine/godot#16174]
**Godot version:**
3.0

**OS/device including version:**
Linux

**Issue description:**
I have a method that clears a Tree and repopulates it with new data:

```
func build_tree():
    tree.clear()
    var root = tree.create_item() # error here: "blocked > 0"
    # create more TreeItems ...
```

**Steps to reproduce:**
Try the above code, or open the provided minimal project, run it and click on any item in the tree. 

I also got it to spit out the error more than once a couple occasions, but I'm not sure exactly how to reproduce that.

**Minimal reproduction project:**
[GodotTreeBug.zip](https://github.com/godotengine/godot/files/1676302/GodotTreeBug.zip)

I looked at the source code and it seems to be something to do with `propagate_mouse_event()`, but I can't make head nor tails of what's happening.

**Comment by Noshyaar** [comment]
Try `call_deferred("rebuild_tree")`

**Comment by RodeoMcCabe** [comment]
Thanks, I managed to make it work using `call_deferred()`.

It's strange, because I'm still calling `clear()` and `create_item()` right next to each other, without deferring them. I only deferred `build_tree()`, but that fixed it.

Oh well! Closing this. Thanks for your help.
