### ISSUE TITLE
Godot Crashes at Startup (Illegal instruction)

### ISSUE THREAD

**Issue by TheAspiringHacker** [godotengine/godot#16171]
**Godot version:**
3.0 64-bit

**OS/device including version:**
Debian (Crouton)

**Issue description:**
When I opened the Godot editor, the grey splash screen appeared, then Godot crashed. The output:

    OpenGL ES 3.0 Renderer: Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits)
    GLES3: max ubo light: 409
    GLES3: max ubo reflections: 455, ubo size: 144
    ARVR: Registered interface: Native mobile
    Illegal instruction (core dumped)

(The first four lines appear as Godot is starting up and the last line appears when it crashes.)

**Steps to reproduce:**
Open Godot

Note that I have managed to build and run Godot 3.0 myself on this same computer a few months ago.

**Comment by akien-mga** [comment]
> OpenGL ES 3.0 Renderer: Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits)

What's your GPU? You seem to be using software rendering, which is not very tested and would give you at most 2-3 FPS in the editor.

**Comment by TheAspiringHacker** [comment]
I don't know much about hardware, but here is the information...

    $ lspci -v | grep VGA
    00:02.0 VGA compatible controller: Intel Corporation HD Graphics (rev 09) (prog-if 00 [VGA controller])
    $ sudo lshw -C video
      *-display                 
           description: VGA compatible controller
           product: HD Graphics
           vendor: Intel Corporation
           physical id: 2
           bus info: pci@0000:00:02.0
           version: 09
           width: 64 bits
           clock: 33MHz
           capabilities: msi pm vga_controller bus_master cap_list rom
           configuration: driver=i915 latency=0
           resources: irq:57 memory:e0000000-e0ffffff memory:d0000000-dfffffff ioport:1800(size=64)

(following instructions at https://askubuntu.com/questions/72766/how-do-i-find-out-the-model-of-my-graphics-card)

**Comment by TheAspiringHacker** [comment]
Please note that I am using Crouton's "Crouton in a ChromiumOS Window:" https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-(xiwi)

**Comment by vnen** [comment]
From the linK:

> While crouton transfers the framebuffer relatively efficiently, there's no GPU acceleration and a fair bit of overhead, so don't expect games or graphics-heavy desktop environments to perform well.

Doesn't surprise me that Godot fails to run.

**Comment by TheAspiringHacker** [comment]
@vnen You are probably right. I tried building Godot from my clone, and it failed. If I recall correctly, the last time that I build Godot, I wasn't using Crouton's Xiwi method.

**Comment by bruvzg** [comment]
FYI: Godot 3 run on Debian buster/sid VM with software rendering (Mesa 17.3.3 llvmpipe LLVM 5.0, 256 bits) and editor is responsive enough to be usable (except 3D stuff).

**Comment by Chaosus** [comment]
Unfortunately I doubt that it can be fixed.. it seems like your videodriver(or xiwi) is not supporting gles3.. Because we will go to Vulkan instead gles3, this issue also have lost actuality. My suggestion is to stay on 2.1.5 if its working.
