### ISSUE TITLE
Export Template Manager issues

### ISSUE THREAD

**Issue by u32i64** [godotengine/godot#16185]
**Godot version:**
`v3.0.stable.official`

**Issues:**
- Clicking on empty space around the manger while it's downloading templates cancels the download. It would be better if there was a confirmation window.

    ![cancel](https://user-images.githubusercontent.com/19972511/35556449-4eb9ea74-05b3-11e8-9d1a-e951f6dd611b.gif)

- If you cancel templates download, and then try again it fails with the warning (only closing and re-opening the manager fixes it):

    ![warning](https://user-images.githubusercontent.com/19972511/35556663-e41f2f70-05b3-11e8-8669-34f43a892447.png)

    ![error](https://user-images.githubusercontent.com/19972511/35556585-a89860ac-05b3-11e8-8a30-522ed361a125.gif)

**Comment by CereEnder** [comment]
Is possible the error is shown due file is still downloading and/or not cancelled, or file is opened but not closed?

**Comment by mhilbrunner** [comment]
Fixed by https://github.com/godotengine/godot/pull/16265
