### ISSUE TITLE
Loud noise when using Area with AudioEffectReverb

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#16186]
**Godot version:**

9f3138e

**OS/device including version:**

Antergos x86_64 

**Issue description:**

AudioEffectReverb predelay feedback should be < 1 : ( 0.98 )

**Comment by akien-mga** [comment]
What version of the Platformer 3D demo? Sounds like the fixed godotengine/godot-demo-projects#202.

**Comment by Noshyaar** [comment]
Yes it's fixed. I have outdated version. I didn't think that it could be the project's fault because there is a report on Discord.

**Comment by vnen** [comment]
Maybe the reverb feedback should not be allowed to be 1.

**Comment by reduz** [comment]
good point, maybe max should be 0.98 ?

**Comment by akien-mga** [comment]
Agreed, reopening so that we set a reasonable limit to protect users' ears :)
