### ISSUE TITLE
Feedback: first time godot user impressions

### ISSUE THREAD

**Issue by sercand** [godotengine/godot#16184]
**Godot version:**
3.0
**OS/device including version:**
MacOS 10.13.2
**Issue description:**
Hello, 
I have been waiting for Godot v3.0 to test and here it is:

- Downloading Godot and installing Godot was easy but on the first try, I downloaded Mono version as an Unity3d developer. But it did not run, just closed without an error message. I figured it out that because I have don't have mono on my system. I think Godot editor should prompt an error message on this type of dependency error.
 
- Godot Project Manager page is not retina compatible and it was confusing because I read on the blog which says that UI has HiDPI support. The second issue on project manager page is that I can't scroll on templates page. I have to use the scrollbar to scroll the page.

- I installed and opened `2D isometric Demo`. When I saw the game editor for the first time, I thought it is beautiful. 

- I could not found how to build project for iOS then I realized that Godot Editor does not use MacOS system menu. After that, I hate Godot editor because MacOS system menu provides search to menu items.

That's all, these are my first 5 minutes experience of Godot v3.0.

**Comment by ariromano** [comment]
I also think, Godot should take advantage of certain macOS system features as well. Another thing is that it has its own file browser you can't just drag and drop files into. In the "save" or "browse" dialog  of any native cocoa app, you can just drag a file from another finder window. In Godot, I always have to drag the file into a text editor to get the path, copy the path into GoDot (minus the filename) and then select the file.

Using the native menu would also.

Another thing, of course, is Accessbility. To MacOS, Godot is just an OpenGL window, so accessibility features like VoiceOver don't work.

**Comment by Calinou** [comment]
@bruvzg Do you know if it'd be possible to support native menu searching on macOS (while keeping the existing GUI system)? If not, this issue should probably be closed as the rest has been either implemented or is discussed in other issues.

**Comment by bruvzg** [comment]
> Do you know if it'd be possible to support native menu searching on macOS

AFAIK menu searching is controlled by OS and will work only with native menu.

And native menu support in Godot currently is too limited (only one level depth, no option box/check box/icon support, no native hotkeys) to use it to reimplement menu as native.

---


> you can't just drag and drop files into. In the "save" or "browse" dialog of any native cocoa app, you can just drag a file from another finder window

Also, native "save" and "open" dialogs are absolutely must-have for sandboxed apps, native dialogs are the only way to access files outside sandbox container and mapped "Documents", "Pictures", etc. folders.
Even inside container, Godot file dialogs won't fully work, selecting something from the disk menu or pressing "up" in the container root ("~/Library/Containers/{app.id}/") will render dialog completely unusable.

**Comment by Calinou** [comment]
I'll close this, as the remaining issue (macOS native menu/file dialog support) should be tracked in a new [proposal](https://github.com/godotengine/godot-proposals).
