### ISSUE TITLE
3D Particles and timescale

### ISSUE THREAD

**Issue by fuha18** [godotengine/godot#16183]
First ever time reporting issues on github; please have mercy on me if this report is lacking.

**Godot version:**

Godot 3.0 stable x64 build

**OS/device including version:**

Windows 7 x64 Professional

**Issue description:**

3D Particles keeps moving even if timescale is set to 0 through `Engine.time_scale`
I expected them to come to a stop like other nodes do.
I haven't tested yet in an exported project but I think behavior will be the same
Not sure if bug or not.

**Minimal reproduction project:**

[particletimescale.zip](https://github.com/godotengine/godot/files/1676772/particletimescale.zip)

**Comment by sudoio** [comment]
Here's a GIF showing the issue:
![time_scale](https://user-images.githubusercontent.com/19972511/35555369-fb362c9e-05af-11e8-8274-02b6f6b180b5.gif)

**Comment by hpvb** [comment]
Thanks for the report! You did a very good job :)

**Comment by CereEnder** [comment]
mmmm... this can be bcs time_scale is a float? I'm not wrong if I assume never will be 0 entirely (in this case 0.00~1) ?
