### ISSUE TITLE
Pressing delete when audio bus effect is selected deletes the currently selected node instead of the effect

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#16198]
**Godot version:**
3.0

**OS/device including version:**
Kubuntu 14.04

**Issue description:**
After adding effects to audio busses, I expect to be able to delete them again by pressing the "delete" key on my keyboard. However, instead of deleting the selected effect, it deletes the currently selected node. This is kind of a workflow breaker, because now I have to right click the effect and select delete if I want to get rid of it.

Additionally, if there is no node selected, pressing delete does nothing.

**Steps to reproduce:**
1. Add a node to an empty scene
2. Add an effect to an audio bus
3. Press delete while the effect is selected
4. Observe how the root of the scene is deleted, instead of the audio bus effect

**Comment by bojidar-bg** [comment]
Still valid on master.
Note that it works fine when deleting the whole bus.
