### ISSUE TITLE
Can't disable "Pan Mode"

### ISSUE THREAD

**Issue by Shin-NiL** [godotengine/godot#16192]
**Godot version:**
3.0-stable

**OS/device including version:**
Linux (Ubuntu 16.04.3 LTS)

**Issue description:**

Using the 2D view, if I click the "Pan Mode" button (Hand icon) the pan mode is enabled. When I click it again to disable it, nothing happens.

**Steps to reproduce:**
Press the "Pan Mode" button on 2D view to enable it and press again to disable it.

**Comment by groud** [comment]
That's normal, it's not a "Pan mode", it's a "Pan tool".
You have to select another tool to "disable" it: 
![output](https://user-images.githubusercontent.com/6093119/35568086-dd1e2640-05c7-11e8-95a1-65cef5724127.gif)

**Comment by Shin-NiL** [comment]
Thanks @groud, I think the tooltip "Pan Mode" made me misinterpret the function.

**Comment by LikeLakers2** [comment]
It'd be nice, then, to have it renamed to "Pan Tool" to avoid this in the future. I'd make the relevant change but I'm not sure where the lines that define the name is.
