### ISSUE TITLE
Use 'command' name instead of 'Meta' for shortcuts on Mac

### ISSUE THREAD

**Issue by michaeldesu** [godotengine/godot#1619]
I'm a new user, so I'm not if this applies to pre-1.1, but I've noticed on a Mac, there is mention of shortcut key 'Meta', e.g. Meta+D for duplicate, and Meta+Drag for rotate. I think this is confusing for new users on Mac. Is it possible to map 'Meta' to 'command' or (better still) the appropriate symbol for Mac (and likewise for the other platforms). I realise this is minor, but it would be a nice polish for the end of the cosmetic things. Thanks.

**Comment by RayKoopa** [comment]
Isn't this implemented now with https://github.com/godotengine/godot/pull/6794 ?
On another note, was the decision to name `Ctrl` "Control` on Windows done on purpose?

**Comment by akien-mga** [comment]
>  On another note, was the decision to name `Ctrl` "Control" on Windows done on purpose?

Probably not, it's a fallback of the method used to retrieve the key name, which now uses https://github.com/godotengine/godot/pull/11933/commits/dd684eaaa08e7c8f2f5902a3e65f244e0bec3ab9#diff-3ee2526a488c4997110bd5cdb37af1e9R62

I don't have a strong opinion either way whether it should stay as "Control" or be changed globally to "Ctrl".

**Comment by RayKoopa** [comment]
It previously was "Ctrl" already as I saw on some old 2.x screenshots, so I wondered:
![image](https://user-images.githubusercontent.com/9631152/33560636-959efb84-d910-11e7-8411-a40eb1a909d6.png)
(Though the order of Ctrl, Alt and Shift here is horrible :P)

**Comment by akien-mga** [comment]
Fixed by #11933.
