### ISSUE TITLE
Material Support in Godot 3.1

### ISSUE THREAD

**Issue by abhaskumarsinha** [godotengine/godot#16195]
Hello, Godot Devs, Congratulations on the 'Stable Release of Godot 3.0'. I've few Requests for Godot 3.1 Material/Rendering Support. I'm not that good in Rendering and OpenGL and don't have much idea about it. Everyone, whether its an Official Group or Unofficial support site, they are saying different things on Godot 3.1. 

First I did few renderings in Blender like this - 
![rendered-02](https://user-images.githubusercontent.com/31654395/35570905-994348e0-05f6-11e8-8b2d-f16bbe040398.jpg)

and this -
![rendered-03](https://user-images.githubusercontent.com/31654395/35570953-bab895f2-05f6-11e8-9672-927e1c6c9947.jpg)

As everyone can see, the art uses a lot of materials.

Mostly the textures used in those materials are -
**1. Diffuse Texture (also called Albedo Textures).
2. Displacement Textures (Parallax Occlusion Mapping/ tesselation and real extrusion, anyone)
3. Glossy Texture
4. Normal Maps
5. AO Texture
6. Roughness Map.
7. And the most important Emission based Lightning (not for lightning, but to just give a sci-fi look, doesn't need to glow anything else around, just for looks)**

Now, Can I officially know, which maps will be supported in Godot 3.1? I want to do that scene in Godot renderer and make a complete 'RENDERED IN REAL-TIME IN GODOT' series, but unfortunately, I don't have an OpenGL3 device.

If anyone knows any alternative way of doing those in Godot 3.1, please do tell me in advance.

Best Regards,
Abhas

**Comment by reduz** [comment]
All are supported in godot 3.0 already, no need to wait for 3.1
