### ISSUE TITLE
Unable to use 3.0-stable export templates with Godot 3.1-dev

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#16194]
**Godot version:**
master (3.1.dev.custom_build)

**Issue description:**
When I try to export a project using the 3.0-stable export templates, I get the message that the 3.0 export templates aren't installed.
This happens because the template manager doesn't allow templates with a different version name, e. g. 3.0-stable in this case.
So it would be nice if the user could decide using them or not.

**Steps to reproduce:**
- Download the 3.0-stable export templates from https://godotengine.org/download/
- Go to editor > manage export templates
- Choose "install from file" and select the 3.0-stable .tpz package
- Try to export a project

**Comment by akien-mga** [comment]
Well that's a feature. Your export templates should always match the exact commit you're using for the engine. So when using 3.1-dev, you should build templates from source.

You *could* just rename your templates folder and edit the `version.txt` file, but it comes without any warranty and you should not report export issues resulting from this hack. Right now it might work, but as soon as there are core changes done to the editor, your exports will crash.

**Comment by volzhs** [comment]
not sure if it's good to allow it.
in most case, old templates do not work well with new version editor.
it will be trouble, not useful.

**Comment by LinuxUserGD** [comment]
Ok thank you, didn't know that I can edit the version inside of the .tpz package :+1:
And it's also possible to select each template inside of the "Custom Template" section
