### ISSUE TITLE
"WARNING: not found: editor_plugins/enabled" being printed when there is a "addon" directory

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16199]
**Godot version:**
20a52aa

**Issue description:**
If you have a sub-directory named "addon" in your project directory, the message `WARNING: not found: editor_plugins/enabled` gets printed when doing things like opening the Project Settings, or just refocusing the editor window.

**Comment by mrcdk** [comment]
The folder `addons` is used to create plugins http://docs.godotengine.org/en/latest/tutorials/plugins/editor/making_plugins.html

**Comment by YeldhamDev** [comment]
@mrcdk There is a lot of people (including myself) that distribute their assets inside this directory, and not all assets need a `plugin.cfg` file (or even can, as it makes it obligatory to the main script to extend from EditorPlugin). So, should this directory not be used unless making an asset that has a `plugin.cfg` file then?

**Comment by vnen** [comment]
@YeldhamDev that should not be a problem, you can the directory for non-plugins too. This is a bug anyway because I see this warning when disabling all plugins, even if I have only real plugins in the `addons` folder.
