### ISSUE TITLE
Font saving: engine should add the expected file ending if not provided

### ISSUE THREAD

**Issue by qubodup** [godotengine/godot#162]
I just received a message "couldn't save font" in the font import dialog, which I was able to fix by adding .fnt at the end of the file.

When only one file ending is possible, I expect a file save dialog to add the ending if it is missing.

I would like to request that either a file name ending is added automatically (needs to be clarified: what happens in .FNT/.FnT file ending cases?) or that the error message explains the reason for the failure ("You have to add the file name ending").

**Comment by akien-mga** [comment]
Bumping this, as far as I know this behaviour hasn't been implemented yet, but would be a welcome usability enhancement. (Probably for more resource types than fonts though)

**Comment by akien-mga** [comment]
Fixed by #4158.
