### ISSUE TITLE
It's possible to create nameless properties in the Project Settings

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16202]
**Godot version:**
 20a52aa

**Issue description:**
Said properties cannot be deleted in the editor, and while they will vanish when the project is reopened, they will still linger in the `project.godot` file:
![screenshot1](https://user-images.githubusercontent.com/30739239/35580364-f00e5e02-05cf-11e8-9ec6-1bad742ab3f5.png)

**Comment by volzhs** [comment]
wow...

**Comment by Hinsbart** [comment]
The category field has a similar issue. If you leave it empty, the property gets added to project.godot but doesn't show in the editor.
