### ISSUE TITLE
Relationship Line Color's "Set to Default" button appear even when having the default value

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16207]
**Godot version:**
 20a52aa

**Issue description:**
If I remember correctly, this used to happened to all color properties in the Editor Settings, but it was later fixed. But I guess the relationship lines were forgotten:
![peek 2018-01-30 17-20](https://user-images.githubusercontent.com/30739239/35586659-911d076e-05e2-11e8-8b18-491a53d2b59d.gif)

**Comment by KoBeWi** [comment]
No longer relevant in 3.1, since the setting was removed.
