### ISSUE TITLE
Switching between "Project List" and "Templates" tabs on startup menu re-downloads existing information

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#16201]
**Godot version:**
Stable 3.0

**OS/device including version:**
Linux Mint 18.3 Cinnamon 3.6.7 64-bit
4.13.0-21-generic

**Issue description:**
On the startup menu, switching between the "Project List" and "Templates" tabs re-downloads the pictures and information for the templates even if the pictures and information are already shown. I expected Godot to cache this instead of re-downloading it every time.

**Steps to reproduce:**

1. From the startup menu, switch to the "Templates" tab
2. Switch back to "Project List"
3. Switch back to "Templates". Launching Godot from terminal will show the assets being downloaded again in the terminal output.

**Comment by Calinou** [comment]
This was resolved by #31906, closing.
