### ISSUE TITLE
v2.1.4 Mouse gets stuck in the center of the screen when dragging a scene into the tree with an Animation also open.

### ISSUE THREAD

**Issue by Iris616** [godotengine/godot#16218]
**Godot version:**

v2.1.4-stable_win64

**OS/device including version:**
Win 10, 64 bits

**Issue description:**
The mouse gets stuck and locked into the center of the godot editor, making it necessary to save and restart the editor when it happens.

**Steps to reproduce:**
-Put an AnimationPlayer on your scene tree.
-Create an animation, whatever it does isn't important, and keep the Animation mode open
-Drag a scene into the tree to instance it
-Sometimes the mouse should get stuck in the center of the screen/viewport.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
