### ISSUE TITLE
Inconsistent 2D render order when removing and adding child nodes

### ISSUE THREAD

**Issue by DoctorAlpaca** [godotengine/godot#16213]
**Godot version:**
3.0

**OS/device including version:**
Arch Linux

**Issue description:**
Removing the first child from a node and then adding another one results in the render order of all the child nodes to scramble around, but only when more than 16 child nodes are present.

**Steps to reproduce:**
Click the "Remove Child" button in the test project at least 8 times, removing and adding a sprite each time. Changing the "num_children" constant to something below 17 has no such behaviour.

**Minimal reproduction project:**
[testing.zip](https://github.com/godotengine/godot/files/1679704/testing.zip)

**Comment by vnen** [comment]
Related to #14364.

**Comment by arccoza** [comment]
I've been experiencing the same problem. When removing nodes from any `Node2D` the
z-order of the remaining siblings shuffle around.
This doesn't happen with 2D nodes inside a `Node` parent.

<img src="https://github.com/arccoza/godot-bug-examples/blob/bugx/node2d-children-zorder-shuffle/adrien/screenshot.png?raw=true">

**Godot version:**
Godot 3.0

**OS/device including version:**
Arch Linux
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 

**Minimal reproduction project:**
[Example](https://github.com/arccoza/godot-bug-examples/tree/bugx/node2d-children-zorder-shuffle/adrien)
