### ISSUE TITLE
Editor Camera Bug

### ISSUE THREAD

**Issue by CCODE05B** [godotengine/godot#16210]
**Godot version:**
Godot 3 official release

**Issue description:**
When navigating in the Editor using WASD keys and mouse .. you can stuck in free looking mode

**Steps to reproduce:**
start navigating using WASD keys and mouse .. then do mouse wheel up or down , now if you release every key you can still rotate the Editor camera and look around .. this should not happen

**Comment by Zylann** [comment]
Similar to https://github.com/godotengine/godot/issues/14373#issuecomment-350515100, the input system again seems to ignore the event where RMB is released...

**Comment by Chaosus** [comment]
Closed as duplicate of #14373 (and looks like its fixed already)
