### ISSUE TITLE
MonoRegUtils::find_mono: Cannot find mono in the registry

### ISSUE THREAD

**Issue by jvitoroc** [godotengine/godot#16222]
Godot_v3.0-stable_mono_win64
Windows 10

When I run Godot the following output appears:
![image](https://user-images.githubusercontent.com/25753747/35604922-3e062a20-062c-11e8-8d34-6b48949f5816.png)

**Comment by Zephilinox** [comment]
Did you install the mono sdk?

**Comment by jvitoroc** [comment]
Problem solved, I just installed mono sdk

**Comment by izaleu** [comment]
I came here because of this same issue. My eyeballs must've skipped right over the Requirements section in the download page. Would it be possible to add a hint to this error message ("Do you have the mono SDK installed?), or does the error come from a library of some sort?

**Comment by Zephilinox** [comment]
Yes it's possible, the location of the error message in the codebase was mentioned in the console output.

https://github.com/godotengine/godot/blob/master/modules/mono/utils/mono_reg_utils.cpp#L161

You could send a pull request to change it, or create a new issue about implementing that change and hope someone else would like to do so.

**Comment by izaleu** [comment]
I'll give it a shot, thanks!
