### ISSUE TITLE
Godot's 3D camera graphic can hide behind its 2D camera icon

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#16221]
**Godot version:**
Godot 3.0 stable

**OS/device including version:**
AMD 7700 GPU; Crimson ReLive drivers; Win10 64 bit (Fall Creator's update).

**Issue description:**
The camera icon (the camera-shaped graphic which denotes the position of the camera node) draws over the actual 3D graphic drawn to represent the camera (due to it not changing size regardless of zoom). This means the graphic can hide behind it and make it more difficult to manipulate, especially when more zoomed out.

**Steps to reproduce:**
Create a camera node and zoom out a little, a project shouldn't be needed.

**Comment by KoBeWi** [comment]
(probably) Fixed in 3.1

![image](https://user-images.githubusercontent.com/2223172/57084387-86c21180-6cfa-11e9-8460-01b7efb0fada.png)
vs
![image](https://user-images.githubusercontent.com/2223172/57084606-e5878b00-6cfa-11e9-9b18-964f5ce53804.png)
