### ISSUE TITLE
Auto Exposure flickers and is erratic.

### ISSUE THREAD

**Issue by leiget** [godotengine/godot#16224]
**Godot version:**

20a52aa

**OS/device including version:**
Xubuntu 16.04
NVidia 960 GTX
I have dual monitors.

**Issue description:**
I try using auto exposure in the world environment, but it flickers and flashes sometimes.
Here are my settings:
Scale: 0.5
Min Luma: 0.05
Max Luma: 8
Speed: 2

**Steps to reproduce:**
Load any scene with meshes, lights, and an environment, turn on auto exposure and look around in the editor. Sooner or later it will start flickering.

**Minimal reproduction project:**
Here's quick and dirty vid of the problem:
https://drive.google.com/open?id=1V5_l9z1BOho5YGfe5u3H-J-AnqIZ6qhc

And here's a example project:
[AutoExpError.zip](https://github.com/godotengine/godot/files/1680410/AutoExpError.zip)
In order to cause the issue, Ctrl+F and fly in and out of the crevaces that are in front of the editor camera when the scene is opened in the editor.

**Comment by leiget** [comment]
I messed with it a bit and it seems to ahve something to do with the "Hdr" setting in "Project Settings/Rendering/Quality/Depth/Hdr" When I turn it off, it doesn't flicker, but it doesn't work as good, either.

**Comment by Calinou** [comment]
This was most likely fixed in the new compute-based auto exposure implementation in the `master` branch, closing.
