### ISSUE TITLE
Audio Latency Problem

### ISSUE THREAD

**Issue by OrchestralBb** [godotengine/godot#16229]
**Godot version:**
Godot 3.0

**OS/device including version:**
Windows 10 64 bit
RME AIO Audio Interface
i7 4930K
GeForce GT 630
64 Gb RAM

**Issue description:**
Any audio file imported into the project is reproduced with cuts if the latency of the audio interface is above 512. 
Usually I have higher latency for music production and I have never had problems playing music or video, playing video games or using other game engines like Game Maker or Unity.

**Steps to reproduce:**
This happens playing audio within the project, but also after exporting it. 

*I can not work with background music while Godot is open. The same thing that I have explained above happens when I pause the player and I want to play a scene in Godot.

**Comment by marcelofg55** [comment]
What's the sample rate setting you're using? 44100 Hz?

**Comment by OrchestralBb** [comment]
96KHz, but 48 Khz also gives problems. Godot only works properly with 44.1 KHz and 512 latency or less.

**Comment by marcelofg55** [comment]
With 44100 Hz and 1024 latency Godot has problems too?

**Comment by OrchestralBb** [comment]
Ahh, now it seems not, Sorry. So is it a problem with the sampling frequency?

**Comment by marcelofg55** [comment]
Yeah, I think I can work it out so that frequeciencies other than 44100 Hz won't give problems, I'll try to fix it and open a PR soon.

**Comment by OrchestralBb** [comment]
Great!!
