### ISSUE TITLE
Font loader file selector doesn't show converted *.fnt files.

### ISSUE THREAD

**Issue by pgregory** [godotengine/godot#16234]
**Godot version:**
3.0stable

**OS/device including version:**
macOS High Sierra 10.13.3

**Issue description:**
When loading a font onto a Label, for instance, the file selector shows "*.font,*.res,*.tres", while the automatic asset importer successfully converts BMFont files (*.fnt) for use. In order to use one of these automatically imported files, it's necessary to change the filter to "All Files" which is a little confusing at first, took me a while to work out why I couldn't see font files that it told me were successfully imported.

**Steps to reproduce:**
1. Create a new scene
2. Add a Node2D
3. Add a Label to the Node2D
4. Import a .fnt/.png pair from BMFont into the project.
5. Select the Custom Fonts, and from the dropdown choose "Load".
6. Your imported font will not show.
7. Change the filter on the file seletor to "All Files (*)" and you will be able to see the .fnt file and successfully apply it to the label.

**Comment by vnen** [comment]
This is a general issue with importable formats, the file dialog filter will hide the formats that can be used when imported.

**Comment by alexzheng** [comment]
3.1.1still has this issue, it's quit uncomfortable to load a fnt file.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by alexzheng** [comment]
still exist.
Just try to load a fnt file in the inspector to reproduce it.

**Comment by KoBeWi** [comment]
As I said, a reproduction project would make this easier to test.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/39771 which includes a minimal reproduction project.
