### ISSUE TITLE
Open the Script editor to other file formats (or allow a plugin to enable other formats' management)

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#16233]
The Script editor is currently locked to .gd text file format read and write.

It would be interesting to allow it to open other text file types. Best would be to have a parameter to allow the editor to open given file types only. Thus a new plugin that needs to manage a specific file type could add its own type in the parameter.

Of course this is risky as users may allow anything to be opened in the editor, including binary files.

**Comment by RiverMesa** [comment]
Wel,l technically you can already open .cs files with it (at least, in the Mono version, not sure if you can even without that), and I believe that new filetypes can be registered via PluginScript (for instance, [godot-python](https://github.com/touilleMan/godot-python) allows you to open Python-related files, mostly` .py`),

It would be nice to expose that kind of functionality to EditorPlugin or EditorScript, though.

**Comment by vnen** [comment]
Looks the same as #1390. I was meaning to do this but completely forgot about it...

**Comment by StraToN** [comment]
@vnen Aw, I did search for an existing issue for this problem, and yes it seems very similar to #1390 .
