### ISSUE TITLE
Small bug + improvement to the folder list icon in the filesystem dock

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#16230]
Some remarks on the folder list icon.

The folder list icon ![icon](https://user-images.githubusercontent.com/5330692/35617332-316170d0-0678-11e8-8393-9850c361bf68.png) should only be displayed (or made clickable) when needed. I wondered for a while what it did, given that clicking it did nothing at all. The icon should probably be disabled or removed when the filesystem dock is in split mode.

Also, there is a small bug: when in "single pane" mode with folder view, the button is hidden. Now if you go back to split view (eg. by moving the dock) the icon is missing.
![missing icon](https://user-images.githubusercontent.com/5330692/35617818-6fd38be0-0679-11e8-9cbf-05173ce04a91.png)

I think it might be better if the toggle button (list/thumbnail) on the right was moved to the left, and the folder list icon was displayed on the right, but only when clicking on it actually does something.

**Comment by akien-mga** [comment]
Fixed by #16255 (and later superseded by the new FileSystem dock anyway).
