### ISSUE TITLE
Windows Defender SmartScreen not recognize publisher

### ISSUE THREAD

**Issue by MasihAkbari** [godotengine/godot#16235]
**Godot version:**
v3 x64

**OS/device including version:**
windows 10 (version 1709 build 16299.192)

**Issue description:**
Windows Defender SmartScreen not recognize publisher and pops up a warning before running downloaded binary for the first time and shows unknown publisher in the body of warning it's better to add some more info in metadata of bin file to prevent smartscreen act like this.

![untitled](https://user-images.githubusercontent.com/8469800/35622675-effc46f8-069d-11e8-8156-ae4213928127.png)

**Comment by vnen** [comment]
This is not just a matter of adding metadata to the binary (in fact, that's already set). This problem happens because the binaries are not signed (see #11984).
