### ISSUE TITLE
Problems with the orthogonal mode viewport.

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#1624]
* In the orthogonal mode when scrolling the mouse wheel does not change the size of the 3D pointer.
* In the orthogonal mode is not editable grid map.
* Num5 not change mode.

Godot 1.1 Beta

**Comment by akien-mga** [comment]
Hi, is this issue still valid in the current master branch or nightly builds?

**Comment by DimaKiva** [comment]
In the assembly of the 10/30/2015 12:25 AM, nothing has changed.

**Comment by akien-mga** [comment]
Tested in the current master branch, all those issues seem fixed.
