### ISSUE TITLE
Somebody can explain how to use c++ in Gdnative? Some step by step tutorial on youtube?

### ISSUE THREAD

**Issue by 111ukasz111** [godotengine/godot#16240]
**Godot version:**

**OS/device including version:**

**Issue description:**

Sorry but I don't know where I should ask.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment]
Please ask usage questions anywhere else in the community channels (Facebook, IRC, discord, Q&A...). See here: https://godotengine.org/community

The Github issues are not meant to help users, but to report bugs or requests enhancements.

**Comment by 111ukasz111** [comment]
ok
