### ISSUE TITLE
Exporting on MacOSX to Windows Desktop Error

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#16243]
**Godot version:**
3.0

**OS/device including version:**
MaxOSX

**Issue description:**
I get this error when I export to Windows Desktop:
`error:could not load game path '.'.`

**Steps to reproduce:**
1. Open Godot on MacOS
2. Make a scene
3. Export to Windows Desktop
4. Try to open on Windows

**Minimal reproduction project:**
https://www.dropbox.com/s/dwyzx3c7i53d0u5/minimal-pack.zip?dl=0

**Comment by Lucrecious** [comment]
This was a mistake on my part.

**Comment by oscar4aar** [comment]
What mistake did you do?
I'm getting the same error, I'm on windows, trying to make it for windows

**Comment by Lucrecious** [comment]
@oscar4aar I was trying to export the game into a non-existent folder.

What happened is that I navigated to a folder in the Godot file exporter, then I renamed that folder, but that didn't update the path in the Godot file explorer. So when I opened up the file explorer again, it was at my previous export path and saving to a non-existent path caused the error.

Hope that helps!
