### ISSUE TITLE
Cannot export Dictionary in 3.0

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#16247]
**Godot version:**
Godot 3.0 20a52aa

**Issue description:**
According to [this](https://github.com/godotengine/godot/issues/10018) and [this](https://github.com/godotengine/godot/pull/12015), the new [debugger PR](https://github.com/godotengine/godot/pull/11940) was supposed to add Inspector editing for *exported* Dictionary variables, but I can't seem to make this work.

**Steps to reproduce:**
1. Create any scene. Add a root node. Add a built-in script:

    export(Dictionary) var dict = {}

2. Examine the node in the scene. Click the right-arrow next to the Dictionary property. The `DictionaryPropertyEdit` won't have anything but a Reference section with the Script variable.

![export_dict](https://user-images.githubusercontent.com/16217563/35637843-07e34ca8-067b-11e8-937d-34638632d286.PNG)

![export_dict_inspector1](https://user-images.githubusercontent.com/16217563/35637851-0b9263b6-067b-11e8-90c4-ad4bd3ebca61.PNG)

![export_dict_inspector2](https://user-images.githubusercontent.com/16217563/35637855-0e1d006e-067b-11e8-804a-18dcadecd5bb.PNG)

**Comment by net8floz** [comment]
I'd also like to know what's going on with this.

**Comment by Noshyaar** [comment]
DictionaryPropertyEdit can only change value. The key is read-only. (for now)

https://github.com/godotengine/godot/blob/6db60c03a9942ba766f52f6a4ae5f157e2edbd42/editor/dictionary_property_edit.cpp#L42-L46

It is supposed to work if you export Dictionary with some values, but there's another bug. Exported dictionaries are saved in the scene file as null.

Node.tscn:
```
dict = null
```

**Comment by bojidar-bg** [comment]
It should be now fixed with the new inspector (though it is slightly crashy, but still works).

>It is supposed to work if you export Dictionary with some values, but there's another bug. Exported dictionaries are saved in the scene file as null.

To be fixed by #19635 (the GDScript part of the changes).

**Comment by akien-mga** [comment]
That's fixed in the master branch.
