### ISSUE TITLE
Ctrl+click leads to empty doc page

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#16256]
Godot 3.0 stable

With the following code:

```
extends Panel

func _ready():
	var s = JSON.parse("")
```

When I Ctrl+Click on `parse`, it takes me to a empty doc page (no error in console). I expected it opens the doc at the function clicked.
If I do this on `JSON`, it takes me to the doc of the class.

If I click again on `parse`, it creates new empty doc tabs:
![image](https://user-images.githubusercontent.com/1311555/35645066-0365fb9e-06cb-11e8-9d00-2f61787a797f.png)

**Comment by Chaosus** [comment]
@akien-mga I checked this issue and found its fixed in the latest master(but exist in 3.0.6)

**Comment by akien-mga** [comment]
Duplicate of #18604 which was fixed by #18642 (could be cherry-picked for 3.0).
