### ISSUE TITLE
HTML export errors

### ISSUE THREAD

**Issue by mizahnyx** [godotengine/godot#1625]
I exported my scene to a HTML page. Then I modified the resulting HTML replacing the JS file referenced at the bottom with the 2 JS files exported by the editor (let's say, X_filesystem.js and X.js). I served the files through Python SimpleHTTPServer. That was the error i got in my browser window (using latest stable Chrome)

    pre-main prep time: 141 ms05pm.html:1244 Module.printErr05pm.js:11392 doRun05pm.js:11408 (anonymous function)
    05pm.html:1232 let it go!
    05pm.html:1232 [1;31;40mERROR: get_executable_path: [1;37;40mWarning, don't know how to obtain executable path on this OS! Please override this function properly.
    05pm.html:1232 [0;31;40m   At: drivers/unix/os_unix.cpp:443.[0;0;37m   
    05pm.html:1232 has res dir: 
    05pm.html:1232 exists engine cfg? 0
    05pm.html:1232 loaded engine.cfg 
    05pm.html:1232 Init OS
    05pm.html:1232 Init Audio
    05pm.html:1232 Init VS
    05pm.html:1232 ANGLE_instanced_arrays
    05pm.html:1232 EXT_blend_minmax
    05pm.html:1232 EXT_frag_depth
    05pm.html:1232 EXT_sRGB
    05pm.html:1232 EXT_shader_texture_lod
    05pm.html:1232 EXT_texture_filter_anisotropic
    05pm.html:1232 GL_ANGLE_instanced_arrays
    05pm.html:1232 GL_EXT_blend_minmax
    05pm.html:1232 GL_EXT_frag_depth
    05pm.html:1232 GL_EXT_sRGB
    05pm.html:1232 GL_EXT_shader_texture_lod
    05pm.html:1232 GL_EXT_texture_filter_anisotropic
    05pm.html:1232 GL_OES_element_index_uint
    05pm.html:1232 GL_OES_standard_derivatives
    05pm.html:1232 GL_OES_texture_float
    05pm.html:1232 GL_OES_texture_float_linear
    05pm.html:1232 GL_OES_texture_half_float
    05pm.html:1232 GL_OES_texture_half_float_linear
    05pm.html:1232 GL_OES_vertex_array_object
    05pm.html:1232 GL_WEBGL_compressed_texture_s3tc
    05pm.html:1232 GL_WEBGL_debug_renderer_info
    05pm.html:1232 GL_WEBGL_debug_shaders
    05pm.html:1232 GL_WEBGL_depth_texture
    05pm.html:1232 GL_WEBGL_draw_buffers
    05pm.html:1232 GL_WEBGL_lose_context
    05pm.html:1232 GL_WEBKIT_EXT_texture_filter_anisotropic
    05pm.html:1232 GL_WEBKIT_WEBGL_compressed_texture_s3tc
    05pm.html:1232 GL_WEBKIT_WEBGL_depth_texture
    05pm.html:1232 GL_WEBKIT_WEBGL_lose_context
    05pm.html:1232 OES_element_index_uint
    05pm.html:1232 OES_standard_derivatives
    05pm.html:1232 OES_texture_float
    05pm.html:1232 OES_texture_float_linear
    05pm.html:1232 OES_texture_half_float
    05pm.html:1232 OES_texture_half_float_linear
    05pm.html:1232 OES_vertex_array_object
    05pm.html:1232 WEBGL_compressed_texture_s3tc
    05pm.html:1232 WEBGL_debug_renderer_info
    05pm.html:1232 WEBGL_debug_shaders
    05pm.html:1232 WEBGL_depth_texture
    05pm.html:1232 WEBGL_draw_buffers
    05pm.html:1232 WEBGL_lose_context
    05pm.html:1232 WEBKIT_EXT_texture_filter_anisotropic
    05pm.html:1232 WEBKIT_WEBGL_compressed_texture_s3tc
    05pm.html:1232 WEBKIT_WEBGL_depth_texture
    05pm.html:1232 WEBKIT_WEBGL_lose_context
    05pm.html:1232 S3TC: 1 ATITC: 0
    05pm.html:1232 Init SM
    05pm.html:1232 Init Mixer
    05pm.html:1232 Init SoundServer
    05pm.html:1232 Init SpatialSoundServer
    05pm.html:1232 Init Physicsserver
    05pm.js:11358 Uncaught Assertion failed: best_error <= 255, at:      drivers/etc1/rg_etc1.cpp,1926,pack_etc1_block_init at Error
        at stackTrace (http://localhost:8000/05pm.js:1049:15)
        at ___assert_fail (http://localhost:8000/05pm.js:8203:210)
        at S4 (http://localhost:8000/05pm.js:9534:661613)
        at F4 (http://localhost:8000/05pm.js:9534:630468)
        at $C (http://localhost:8000/05pm.js:9538:224220)
        at zj (http://localhost:8000/05pm.js:9530:52860)
        at yj (http://localhost:8000/05pm.js:9530:47991)
        at Object.lj [as _main] (http://localhost:8000/05pm.js:9530:13571)
        at Object.callMain (http://localhost:8000/05pm.js:11339:30)
        at doRun (http://localhost:8000/05pm.js:11396:25)

By the way, thanks for making such a great engine, and if you need any further info about this issue, just tell me and I'll send it.

**Comment by vkbsb** [comment]
If you are willing to compile the engine code you can  grab the fix from here https://github.com/vkbsb/godot/tree/h5build

This will probably be fixed in next release.

**Comment by reduz** [comment]
the fix was merged, will be available in beta2

**Comment by vkbsb** [comment]
Please include the wiki page.. https://github.com/vkbsb/godot/wiki/export_html5

Explains in detail how to compile the exporter for html5
