### ISSUE TITLE
Mono slowness

### ISSUE THREAD

**Issue by rogersteve97** [godotengine/godot#16254]
**Godot version:**
3.0

**OS/device including version:**
Windows 10 64x

**Issue description:**
The mono download in the 3D is far slower/glitchier than without mono

**Steps to reproduce:**
Download both versions and compare frame rat.

Also note that this is when loading a 3d template project the 3D Platforming Template

**Comment by Chaosus** [comment]
I dont observe any framedrop in current master between mono and non-mono version of 3D platformer. Futhermore this issue is very subjectively and did not contains real tests, driver info, or demonstration. Closed.
