### ISSUE TITLE
Click on ".." folder in Godot editor FileSystem dock does not indicate if the folder is clicked. 

### ISSUE THREAD

**Issue by gemkibeju** [godotengine/godot#16253]
**Godot version:**
Stable 3.0

**OS/device including version:**
Linux Mint 18.3 Cinnamon 3.6.7 64-bit
4.13.0-21-generic

**Issue description:**
In the Godot editor, clicking on the ".." folder in a subfolder does not highlight the folder, meaning you cannot tell if you clicked on it. In the second screenshot, the ball icon is clickable, but not the folder next to it:

![folder1](https://user-images.githubusercontent.com/35967259/35640614-937ad7a6-06b5-11e8-92c9-58bfd5431cec.png)

![folder2](https://user-images.githubusercontent.com/35967259/35640619-959dbd64-06b5-11e8-8d6d-1315fd5e200d.png)

**Steps to reproduce:**

1. From the Godot editor, descend into a subfolder from the filesystem dock.
2. Click on the ".." folder.

**Comment by guilhermefelipecgs** [comment]
Just for reference: https://github.com/godotengine/godot/pull/11428#issuecomment-335172279
> MillionOstrich commented on 9 Oct 2017 •  edited 
> I have now made it impossible to have ".." selected (you can still right click it and double click it) and rebased this change into the first commit, fixing the issue raised in my previous comment.
> 
> The point Xgor raised I think I will address in a new PR at a later date - along with a different issue I encountered with drag (dragging folders onto the favourites icon doesn't work - it probably should favourite the folder though).

**Comment by gemkibeju** [comment]
@guilhermefelipecgs I would consider behaviour that breaks the user's expectations, being that every folder in the dock would be selectable, as a bug and not a feature.

**Comment by guilhermefelipecgs** [comment]
I agree, I put this reference just to remind those who will work on it that the change may cause some errors that need to be fixed.
