### ISSUE TITLE
"Stable" docs out of doc - Quick Fix?

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#16267]
Recently [had an issue](https://godotengine.org/qa/22906/nonexistent-function-set_fixed_process-kinematicbody2d) where I was following Godot "Stable" (2.1) docs instead of "3.0". Shouldn't 3.0 be the stable branch now? If people are coming in starting at 3.0, and SEO is currently pointing to "Stable" it will be very confusing.

![capture](https://user-images.githubusercontent.com/7429786/35657489-bc0d731c-06ca-11e8-8003-b41bd6b28f97.PNG)

**Comment by mhilbrunner** [comment]
Duplicate of https://github.com/godotengine/godot-docs/issues/1052.
Will hopefully be fixed soon-ish.
