### ISSUE TITLE
Input bug HTML 5 Export

### ISSUE THREAD

**Issue by fLUFFYbLUFF** [godotengine/godot#16262]
**Godot version:**

Godot 3.0

**OS/device including version:**

**Issue description:**

When my website loads my game, the player automatically goes up for no reason. None of the keys are being pressed. When I run my game using the engine this bug does not occur.

**Steps to reproduce:**
1.Create a 2-D game
2. Create a basic move script that moves the player up,left,down,or right
3. Export for HTML5
4. Try playing the game using that export

FOR SOME REASON THESE STEPS ARE NOT WORKING. I TRIED DOING WHAT I COULD TO GET A REPRODUCTION PROJECT. NOTHING WORKED.
Game website: fluffybluff.github.io/Hit-n-Lose/Hi-tn-Die.html
*Just saying this game is nowhere near completion*

**Minimal reproduction project:**

[html5.zip](https://github.com/godotengine/godot/files/1683423/html5.zip)

**Comment by abhaskumarsinha** [comment]
seems to be a bug in Google Chrome. But not sure. 

Can you please give the browser info and version?
also, Have you checked the issue on other Browsers?

**Comment by akien-mga** [comment]
CC @eska014

**Comment by fLUFFYbLUFF** [comment]
I tried Internet Explorer and that's not working. It works in Firefox though. Also, the bug has been occurring Google Chrome

**Comment by abhaskumarsinha** [comment]
@fLUFFYbLUFF believe it or not, the OpenGL part in IE is much more advanced in other Browsers, though, I confirmed it's a bug in Browser

**Comment by NiQuan** [comment]
Change the key bindings in your project to only be keyboard inputs. This seems to solve the issue.

**Comment by ergo** [comment]
I've been following the first game tutorial on godot 3.0.6 and html5 export under chrome generates a build where character still moves in random directions.

**Comment by eska014** [comment]
@ergo The fix isn't included in 3.0.6, expect it for 3.0.7

**Comment by Beelzenef** [comment]
I created new actions to use in my project and the problem disappeared, it works in Chrome and Firefox, hope it helps! :+1:

**Comment by justinluk** [comment]
@Beelzenef Were you using 3.0.6? I haven't tested this out with 3.1 yet.

**Comment by Beelzenef** [comment]
I confirm, @justinluk, using v3.0.6 :ok_hand:

**Comment by triptych** [comment]
What does "create new actions" entail? You changed how you got inputs? You deleted and re-added code? @Beelzenef

**Comment by Beelzenef** [comment]
I deleted every action and created new ones to export, as you can see in the image:

![image](https://user-images.githubusercontent.com/6389665/52880081-4d4d2180-3161-11e9-88e0-57fd4641bc99.png)
