### ISSUE TITLE
Sprite with AtlasTexture can't be selected on canvas

### ISSUE THREAD

**Issue by kaliga** [godotengine/godot#16261]
Version: Godot 3.0 stable (official)

OS: X11 (Manjaro x64)

Sprites can't be selected on the canvas when the texture is an AtlasTexture. They can still be selected with a box selection or by selecting on the dock, but they still can't be moved on the Select Mode (can be scaled with the dots-thing and the other modes works normally)
This error shows up when trying to click on them:
>  scene/2d/sprite.cpp:281 - Condition ' image.is_null() ' is true. returned: false

TextureRects with AtlasTextures behave normally. Sprites with region enabled also works fine.

Screenshot:
![captura de tela_2018-01-31_19-07-38](https://user-images.githubusercontent.com/31441780/35648281-5e8cece4-06bc-11e8-862c-fe6abfd9cf12.png)

Steps to reproduce:
1. Add a Sprite
1. Use an AtlasTexture as its texture
1. Try to select it on the canvas

Minimal reproduction project:
[atlas_texture_bug.zip](https://github.com/godotengine/godot/files/1683384/atlas_texture_bug.zip)

(this is my first issue ever and i'm not very good at english. I hope this issue is allright)

**Comment by binbitten** [comment]
Investigation shows that _get_data()_ is not implemented for AtlasTexture. This function is used by `Sprite::_edit_is_selected_on_click()`, which fails without it.
