### ISSUE TITLE
Editor doesn't support code completion custom shortcut

### ISSUE THREAD

**Issue by Yanpas** [godotengine/godot#16264]
**Godot version:**
3.0

**OS/device including version:**
win 10

**Issue description:**
Editor doesn't support code completion custom shortcut

**Steps to reproduce:**
Set "Shift+space" as a hotkey for complete_symbol
Press Shift+space - nothing happens. Ctrl+space is still used

**Minimal reproduction project:**

**Comment by Zylann** [comment]
Are you sure it's the shortcut and not completion that doesn't work? I've noticed code completion is not always working https://github.com/godotengine/godot/issues/16257

**Comment by Yanpas** [comment]
Yes, I'm sure since I've tried performing the same action from edit menu. SHift+space results in entering space symbol

**Comment by Yanpas** [comment]
The problem is in popup_menu.cpp

This if statement evaluates to true if hotkey is not "shift+space":
```
if (items[i].shortcut.is_valid() && items[i].shortcut->is_shortcut(p_event) && (items[i].shortcut_is_global || !p_for_global_only)) {
			activate_item(i);
			return true;
		}
```

**Comment by Yanpas** [comment]
Function receives event with only Shift pressed, Space key gone away magically

**Comment by reduz** [comment]
in theory, TextEdit should not be eating that event if it does not use it... maybe it would be best to look for why this may be happening

**Comment by Yanpas** [comment]
It treats Shift+Space as Space, enters space symbol it to the cursor and marks event as handled.

**Comment by KoBeWi** [comment]
The base issue is a duplicate of #12164
