### ISSUE TITLE
Highlighting a float value in Visual Script mouse gets stuck

### ISSUE THREAD

**Issue by strongmuffin** [godotengine/godot#16275]
**Godot version:**
3.0 stable

**OS/device including version:**
Windows 10, Nvidia GFX 1070

**Issue description:**
If you create a new variable in visual script, define it as a float. Increment the value by 1, then highlight the value your mouse will get stuck.

To unfree your mouse you either have to use CTRL + ALT + DEL or throw your mouse around to get it off the screen like I did in the demonstration.

Here's a demonstration how to do it
![https://i.imgur.com/GSqF2wb.gif](https://i.imgur.com/GSqF2wb.gif)

**Comment by reduz** [comment]
This code is gone, so this should no longer happen

**Comment by strongmuffin** [comment]
@reduz Awesome! Thanks :D
