### ISSUE TITLE
Proper vector-format-based text outlining

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#16279]
**Godot version:**
3.0 stable

**OS/device including version:**
Any

**Issue description:**
Godot uses its own imperfect way of outlining texts after the glyphs are already rendered by FreeType from the vector format. This results in visible artifacts and outlining looking usually bad. FreeType does support outlining based on the vector format which provides perfect result (see [Stroker API](https://www.freetype.org/freetype2/docs/reference/ft2-glyph_stroker.html)). Godot should use that API instead of relying on its own algorithm for fonts in vector format.

**Comment by volzhs** [comment]
I guess it's because it originally came from bitmap fonts.
it should be handled separated way between bitmap & dynamic font then.
_I'm not against to implement it._

**Comment by volzhs** [comment]
I just assigned myself to this issue, but can't say when I can do about it.
I'd appreciate anyone leaves comment if want to do it.

**Comment by samdze** [comment]
Would be great to have such a feature. Outlining is important, sometimes text wouldn't be readable otherwise.
