### ISSUE TITLE
Syntax highlighting for paths using the $ get_node shortcut is wrong

### ISSUE THREAD

**Issue by Zephilinox** [godotengine/godot#16284]
**Godot version:** 3.0

**Issue description:** Using $ to get a node path where the node name is a variable, such as name, causes the syntax colouring to screw up.

**Steps to reproduce:** make a child called "name" and type $name.

![image](https://user-images.githubusercontent.com/2060863/35684735-b5762a18-075f-11e8-8430-c9f1d1a29e10.png)

I struggled to name the title appropriately, feel free to change it so that it makes more sense.

**Comment by vnen** [comment]
Related to #16284

**Comment by Zephilinox** [comment]
@vnen that's id of this issue, did you mean to post a different one?

**Comment by vnen** [comment]
Oops, I failed at copy-paste. I meant this: #11554

**Comment by Zephilinox** [comment]
So I did my best to take a look at this.

Trying to colourize/decolourize the entire $ bit doesn't seem possible, as there's no clear "end" to it (as there is with strings or comments).

Trying to decolourize keywords inside it is possible, but hacky (at least, as far as I could figure out).

Before:
![image](https://user-images.githubusercontent.com/2060863/35708170-b81290fa-07a4-11e8-9c85-d920c537734c.png)

After:
![image](https://user-images.githubusercontent.com/2060863/35708154-a6aac33c-07a4-11e8-9bf4-fb5064ff1a50.png)

Essentially, if a $ or / character is detected anywhere before a keyword, that keyword won't get coloured. It's not a good solution.

Here's the code/location for it, if anyone else wants to try and give this a go or figure out a better method:

text_edit.cpp, line 1042

```
if (col)
{
	for (int k = j - 1; k >= 0; k--)
	{
		if (str[k] == '$' || str[k] == '/')
		{
			col = NULL;
			break;
		}
	}
}
```
