### ISSUE TITLE
Bullet ignores joint Collision->"Exclude Nodes" setting

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#16282]
Bullet physics seems to ignore the Collision->"Exclude Nodes" setting, which can be found under various joints (tested with Generic6DOFJoint and HingeJoint so far). Bullet always excludes nodes (doesn't allow Node A to collide with Node B) regardless of the state of that option.

If project is switched to GodotPhysics, collisions happen as expected when the "Exclude Nodes" setting is turned off.

**Godot version:**
Godot v3.0 (stable release)

**Comment by AndreaCatania** [comment]
Thanks you for the report, this will fix the problem: #16424
