### ISSUE TITLE
Tabs causing ERR_PARSE_ERROR

### ISSUE THREAD

**Issue by sandorex** [godotengine/godot#16283]
**Godot version:** 3.0 stable official

**OS/device including version:** Windows 64bit

**Issue description:**
Using tabs instead of spaces causes errors in parsing
`built-in:6 - Parse Error: Unindent does not match any outer indentation level.
 modules\gdscript\gdscript.cpp:583 - Method/Function Failed, returning: ERR_PARSE_ERROR`

**Steps to reproduce:**
Use tabs to make indentation instead of spaces.

**Minimal reproduction project:**
[electrothingy.zip](https://github.com/godotengine/godot/files/1685748/electrothingy.zip)
Error in scripts/block/block.gd

**Comment by akien-mga** [comment]
Using tabs is fine, but using tabs *and* spaces for a same indentation level is invalid (just like in Python).

Just change the tab size and see why:
![image](https://user-images.githubusercontent.com/4701338/35683619-d7e89a90-0764-11e8-88c2-f7f14ea88e64.png)
