### ISSUE TITLE
Going for enums in the docs will just put you at the top of the page

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16285]
**Godot version:**
2459eeb

**Issue description:**
Be by searching for them or clicking in a shortcut in another doc, going for any enum (e. g. the ones in the GlobalScope) will just place you at the top of the page.

**Comment by Falke117** [comment]
Hi. I just found out this issue during searching for existing issues when opening new issues.
This issue is partially closed via issue #17396, and the remaining use cases are now separate into issue #17957 and issue #17958. 

(Issues, man, they are everywhere!.)

**Comment by akien-mga** [comment]
Indeed, closing as duplicate of #17396 and follow-ups #17957 and #17958.
