### ISSUE TITLE
Built-in script editor not working

### ISSUE THREAD

**Issue by TobiasDev** [godotengine/godot#16289]
**Godot version:**
3.0 Stable

**OS/device including version:**
Ubuntu 17.10

**Issue description:**
100% when I try to open scripts in the built in editor it shows up empty. I can't even see the scripts in the list or anything. This makes it impossible for me to be able to do any scripting. 

**Steps to reproduce:**
1. Start the editor
2. Create a script
3. Try to open it

**Minimal reproduction project:**
I tried the 2D Rigidbody demo and the 2D Kinematic demo

**Comment by Zephilinox** [comment]
Perhaps try deleting your config folder and seeing if that has something to do with it?

~/.config/godot/

**Comment by groud** [comment]
Could you do a screeencast also ? I cannot reproduce.

**Comment by Zephilinox** [comment]
@TobiasDev informed me on discord that deleting the config folder solved the issue. Probably some left over configs from an older or beta godot version was somehow interfering.

**Comment by groud** [comment]
Ok thanks, I close the issue then. :)
