### ISSUE TITLE
Please use consistent typography for Godot

### ISSUE THREAD

**Issue by buckle2000** [godotengine/godot#16294]
Homepage:

![homepage](https://godotengine.org/themes/godotengine/assets/logo.svg)

Docs:

![docs](http://docs.godotengine.org/en/3.0/_static/docs_logo.png)

Navigation:

![homepage nav](https://user-images.githubusercontent.com/10850402/35699147-2ecf5eb0-07ca-11e8-965b-ec111500067b.png)

Well, using a single typography will make Godot more recognizable. Can anyone update the icon on the [home page](https://godotengine.org/)?

**Comment by groud** [comment]
I don't vote for that. The main logo has a fancy font which is recognizable, while the navigation and godot docs (it's the same font) are more professional / readable.

**Comment by leoddd** [comment]
Logos generally have their own typography, yeah.

**Comment by buckle2000** [comment]
The main logo font is of course legible, but that font does not appear somewhere else (as far as I know).
![default](https://user-images.githubusercontent.com/10850402/35699489-315e4d70-07cb-11e8-9706-44f046bad91d.png)

**Comment by buckle2000** [comment]
Usually, when people see the font in main icon, if users cannot connect the font with the brand the, that typography should not be considered a part of the icon. By this difinition, only the robot head is Godot's icon while the text aside it is not unique enough to be recognized as part of the icon.

**Comment by groud** [comment]
Well, the font is part of the logo: https://github.com/godotengine/godot-design/blob/master/communication/business_cards/92x54/business-card-back.png

But sometimes we remove it when it's not useful. Just like with unity.

**Comment by buckle2000** [comment]
@leoddd 
> Logos generally have their own typography, yeah.
mmmmm....your don't use a new font for the sake of using a new font.

**Comment by akien-mga** [comment]
![image](https://user-images.githubusercontent.com/4701338/35700060-2f01f2d6-0792-11e8-93ca-4d8469d79d86.png)

![image](https://user-images.githubusercontent.com/4701338/35700076-3c7f499a-0792-11e8-8672-9dce98b76c28.png)

![image](https://user-images.githubusercontent.com/4701338/35700096-4e40136c-0792-11e8-9cbb-8019972f71a3.png)

Logs have their own fonts which differ from the normal website text, that's normal.

**Comment by buckle2000** [comment]
That bussiness card looks great. Please show the logo (with text) more often then.

**Comment by groud** [comment]
Examples worth a million words ^^

**Comment by akien-mga** [comment]
> Please show the logo (with text) more often then.

The logo (with text) is shown on the splash screen as well as on the menu bar of the website, and the FB banner, etc. The docs is the only place where it's not used, because we have a fun variant instead.
