### ISSUE TITLE
OS.execute on exported project will go nuts.

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#16290]
**Godot version:**
3.0-stable.

**OS/device including version:**
Debian 9

**Issue description:**
OS.execute should execute said command just once, but seems that when executing an exported project, for some reason the command keeps getting executed.

**Steps to reproduce:**
Create a blank project with a script that says "Hello, World!" on ready. Export it.

Create a new blank project that on ready does OS.execute("first_project_path", [], true) and you will unleash a nightmare.

**Comment by akien-mga** [comment]
You need to set the path to the location of your first project, or use the `--path` argument. By default the Godot binary is not bound to any data pck, it will execute what it finds it the current working directory. In your case, it's the directory of the second project, so the second project actually runs itself endlessly.

**Comment by vicguedez** [comment]
@akien-mga Sorry to reopen this, but I don't understand what you mean by "set the path to the location of your first project" .... I do OS.execute("/home/user/hello_project.x86_64", [], true) that should execute directly the binary, no?

**Comment by Calinou** [comment]
I think @akien-mga said you should execute the exported binary with an argument such as `--path /path/to/project/directory` (I think you can specify the path to the PCK file directly, I'm not sure).

**Comment by isHaacK** [comment]
I'm not a fan of reliving closed issues but the literal answer to this is nowhere to be found on the internet so I'm doing a favour to whoever is having the same issue as me and @vicguedez .
`OS.execute('C:/program.exe' ,['--path', 'C:/'], false)`

**Comment by vicguedez** [comment]
Oh yes, I totally forgot comment here that you should pass any arguments in the array. Thanks @isHaacK.

**Comment by Calinou** [comment]
Can the current [OS.execute()](https://docs.godotengine.org/en/latest/classes/class_os.html#class-os-method-execute) documentation be improved based on your comments?

**Comment by isHaacK** [comment]
It can probably be more clarified. "platform path resolution will take place" wasn't clear for me, I didn't understand that the exported project was being executed in the current path, loading the wrong pck resulting in me struggling to understand how in the hell it was opening another instance of the current project.
