### ISSUE TITLE
Blender 2.8 Eevee Render support

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#16308]
For the upcomming release of Blender 2.8, it is going to use the new Eevee Render. Can Godot 3.1 support .blend files while the .blend models are saved using the Eevee Render materials?

**Comment by groud** [comment]
Importing .blend files is not really possible nor recommended. However, an exporter is being worked on:
https://github.com/godotengine/blender-exporter

**Comment by Raj2032** [comment]
Is this the gltf 2.0 exporter? Does this exporter (the one that you
provided me with the link) support Eevee Render?

**Comment by groud** [comment]
> Is this the gltf 2.0 exporter

No. It exports directly from blender to Godot, without using gltf 2.0.

There's no such thing as an "Eevee render material". Eevee in a renderer that supports PBR. Godot supports PBR too the the material created in Blender should be easily exported to Godot's renderer.

**Comment by Raj2032** [comment]
Oh ok nice. So I can use the Eevee Render, assign certain materials to the
model, including glass materials, emission materials and the mix shader
materials, and I am also able create animations using the armature, and
then I can export the model to that certain file format (I am not sure what
file format this addon exports to), and then Godot will support it with no
issues (once when the addon is ready)?

**Comment by groud** [comment]
Well, with "no issue" we don't know yet. But the goal is to export directly to the .tscn format, so no other intermediate format.

Anyway I think we can consider this issue as solved since the exporter is already being worked on. :)

**Comment by Raj2032** [comment]
Thanks :) But would it support Glassy and Emmission materials if I were to
assign these materials to the model under the Eevee Render though?

**Comment by groud** [comment]
I believe so.

**Comment by toger5** [comment]
https://twitter.com/reduzio/status/957659011054227456

in this twitter discussion there is some interesting information.
Evee uses the priciple shader which is afak really close to Disney's BRDF which is also what godot uses. So the principle shader will work really well I think.
but even for other shaders it seems it will be possible!
