### ISSUE TITLE
[Mono] Display clear error message if dependencies are missing or include them

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#16304]
See original issue: https://github.com/godotengine/godot/issues/16184

**Comment by bruvzg** [comment]
Or ship required subset of Mono assemblies with the editor, `mscorlib.dll` (3.9 MB) alone is sufficient to prevent crash on start, and full set of dependencies referenced by editor is about 12 MB large.

![assemblies](https://user-images.githubusercontent.com/7645683/35721279-ded9f480-07f9-11e8-9080-64976e15cda7.png)

**Comment by mhilbrunner** [comment]
That would probably be even better.

**Comment by Calinou** [comment]
Is this still an issue as of Godot 3.2 RC1?

**Comment by neikeq** [comment]
This is no longer an issue. We ship these dependencies with the editor.
