### ISSUE TITLE
Vector2.angle_to_point(Vector to) is unintuitive

### ISSUE THREAD

**Issue by menip** [godotengine/godot#16307]
I would expect this to find the angle between current vector and another point. Instead, according to [the function's description](http://docs.godotengine.org/en/latest/classes/class_vector2.html#class-vector2-angle-to-point), it returns the angle between the passed in vector and the x-axis. 

I'm not sure if this is industry standard, so if it is, please let me know.

Example:
If I have some Vector `vect` and I want to find it's angle from x-axis, I would have to say `theta = vect.angle_to_point(vect`), which is confusing for me. Because if I have vector `vect2`, I could get it's angle to x-axis by saying `vect.angle_to_point(vect2`), which would give something other than what the function name implies

EDIT: Seems I didn't understand the function before. Now I think what the function does, is treats the current vector as a point, and accepts another point. It then makes a vector between the two points, and finds angle to x-axis. I'll leave this up for discussion, but I do understand that change is essentially impossible now, as it would be api breaking.

**Comment by Omicron666** [comment]
I think documentation is confusing here.

**Comment by menip** [comment]
I see there is now a `Vector2.angle_to(Vector2 to)` that does exactly what I would expect `angle_to_point `to do. 
`Vector2.angle_to_point(Vector2 to)` is now described as "Returns the angle in radians between the line connecting the two points and the x coordinate."

What would be the use case? You could instead have two calls to `Vector2.angle_to(Vector2 to)`.

Either way, function name I believe is confusing and does not reflect it's job. What are thoughts with regard to renaming or removing `Vector2.angle_to_point(Vector2 to)`?

**Comment by aaronfranke** [comment]
The math that this performs is `atan2(y - to.y, x - to.x);`

As such, `a.angle_to_point(b)` is currently equivalent to `(a - b).angle()`.

One particularly strange thing is that this finds the angle *from b to a* if you treat them as points.

I don't think this function is very useful, but we already have `angle_to` to do what @menip wants.

**Comment by burstina** [comment]
actually...

```
	var p1first = Vector2(878,235)
	var p1last  = Vector2(603,475)

	var dir1 = p1first.direction_to(pto)
	var dir1last= p1first.direction_to(p1last)
	var cosine = dir1.dot(dir1last)

	var angle  = acos(cosine) 
	var angle1 = p1first.angle_to(p1last)
	var angle2 = p1first.angle_to_point(p1last)
```
results:

```
angle -> 0.677
angle1 -> 0.406
angle2 -> -0719

```
Wich one is the real angle betweem angle, angle1 and angle2?

The REAL angle between the two points is........
"angle"

**Comment by timothyqiu** [comment]
I think `angle_to_point` can be explained as "angle _relative_ to".

`a.angle_to_point(b)` returns the angle of `b` when `a` is the origin.

**Comment by Shadowblitz16** [comment]
all angles should be consistent and relative to the way the screen is rendered.
Not sure but I know by default sin also returns the wrong angle relative to the the way things are rendered.

everything in the api should complement each other we shouldn't have to flip and reverse angles and vectors to get the right result based on the way things are rendered.

If this is a issue with the way the renderer is flipped then it should be fixed.

**Comment by Shadowblitz16** [comment]
Here is a example of Vector2.angle() being incorrect too...```
func _physics_process(delta):
	var axis_x = Input.get_action_strength("ui_right")-Input.get_action_strength("ui_left")
	var axis_y = Input.get_action_strength("ui_down" )-Input.get_action_strength("ui_up"  )
	var axis   = Vector2(axis_x, axis_y).normalized()
	
	print("cast angle: "+str(rad2deg(axis.angle())))
	cast_to = cast_to.linear_interpolate(axis * length, speed);``` If I use```
	var axis_x = Input.get_action_strength("ui_right")-Input.get_action_strength("ui_left")
	var axis_y = Input.get_action_strength("ui_down" )-Input.get_action_strength("ui_up"  )``` for cardinal movement it is correct however as soon as I use angle() for directional movement it is reversed.

**Comment by Shadowblitz16** [comment]
I also brought this problem up related to the way Vector2 and Vector3 get converted to and from each other.
In that case its not as simple as `Vector2(vector3.x, vector3.y)` and `Vector3(vector2.x, vector2.y)`
But that was closed.

I know I am getting off topic but I am just pointing out there is more problems with angles then just this.

**Comment by aaronfranke** [comment]
@Shadowblitz16 Note that in Godot 4.0 you will be able to use `Input.get_vector`. But this discussion is off-topic.
