### ISSUE TITLE
TextureButton in ScrollContainer can not be scrolled via dragging on touch screen device

### ISSUE THREAD

**Issue by wombatwingdings** [godotengine/godot#16318]
**Godot version:**

2.1 stable official download
3.0 stable official download

**OS/device including version:**
Windows 10 x64
Android 7.1.2 - Moto G 2nd gen GPU: Adreno 305

**Issue description:**

Using a TextureButton (and probably any other button type too) does not scroll when used inside ScrollContainer/VBoxContainer when dragged on a touch screen device. Should be able to drag the button up and down without activating the "pressed" signal. That signal is currently correctly not activating. It is the dragging to scroll that is not working.

This makes ScrollContainer of limited use currently. I am working on a workaround for this by rolling my own texture button class. Will post when it is ready.

**Steps to reproduce:**
See attached simple project (Godot v3) that demonstrates the problem. Export it to Android. Dragging when holding down the text Label nodes work fine. Dragging does not work when holding down TextureButton (the ScrollContainer contents does not move). Press the button to quit the application.

**Minimal reproduction project:**

[g3scrolltest.zip](https://github.com/godotengine/godot/files/1689126/g3scrolltest.zip)

**Comment by volzhs** [comment]
Uncheck `Control/Focus/Stop Mouse` in Inspector panel with 2.1.x
Change `Control/Mouse/Filter` to `Pass` in Inspector panel with 3.0

**Comment by wombatwingdings** [comment]
Thanks for taking the time to look at this issue. I had not actually seen that option. But, although your suggestions allows the button to be scrolled while dragged, as soon as you let go, it is selected anyway. It I were to have several buttons in a ScrollContainer and I wanted to drag and scroll to one out of view, I would not be able to do so without the button being dragged activating.

**Comment by wombatwingdings** [comment]
If anyone else is having this issue, I have worked around it by creating my own plugin. It doesn't do all the things that TextureButton does, but it's good enough for my needs (just supports drag (without activating) and select). It is for Godot v3.

Instructions: create a directory called "addons" in your project dir (if you don't already have one). Extract zip in there. Add a "ScrollTextureButton" node (you should find it as a child of "TextureRect"). Assign your own function to the signal "Pressed". 

[ScrollTextureButton.zip](https://github.com/godotengine/godot/files/1711755/ScrollTextureButton.zip)

**Comment by raptdwar** [comment]
I was also struggling with this issue, however my workaround is a little more direct.

I both connect the "**button_down**" and "**button_up**" signals and check if the parent Scrollcontainer **scroll_vertical** value has changed between the press and release signal.
Not really elegant ( traversing up the hierarchy ) but it works fine

For 2.1 use the **get_v_scroll** accessor

**Comment by volzhs** [comment]
@wombatwingdings 
#17081 solved your problem which button is pressed after scrolling.
and this was cherry-picked to 3.0.3.
so, can this be closed?

**Comment by wombatwingdings** [comment]
@volzhs 
It does sound like it is fixed. I can't test myself until 3.0.3 is released as I haven't got round to building Godot from source yet. Will test and close when it is available, but also happy for it to be closed before hand.

**Comment by volzhs** [comment]
@wombatwingdings we can close after releasing 3.0.3 than. :)

**Comment by wombatwingdings** [comment]
OK, I can now build Godot from source. I can confirm that the issue is fixed in 3.1 trunk.

**Comment by SamToorchi** [comment]
my solution for this problem:

```
func _input(event):
	var v_bar_lenght = $ScrollContainer.get_v_scrollbar().get_instance_id()
		if event is InputEventScreenDrag:
			if (event.relative.y > 1):
				bar_swipe -= 20
				bar_swipe = clamp(bar_swipe, 0, 140)
				if bar_swipe >= v_bar_lenght:
					bar_swipe = v_bar_lenght
				$ScrollContainer.set_v_scroll(bar_swipe)

			if (event.relative.y < 0):
				bar_swipe += 20
				bar_swipe = clamp(bar_swipe, 0, 140)
				$ScrollContainer.set_v_scroll(bar_swipe)
```

Scene structure:

|--> CanvasLayer
    |--> PanelContainer
        |--> VBoxContainer

**Comment by bspear8** [comment]
If anyone is still having issues with texture buttons in scroll containers on mobile, I was able to resolve my issue of scrolling working but the buttons being tricky to select by increasing the scroll container deadzone to ~25.
The scene structure is:
|--> Scroll Container
   |--> VBoxContainer
      |--> Texture Button
