### ISSUE TITLE
Restore_Scenes_On_Load should be enabled by default

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#16317]
Related to #15499
**Godot version:**

Godot 3 stable win 7

**OS/device including version:**

**Issue description:**

Godot remember recent script list, but not opened scenes. It always starts in 3d editor (project doesn´t have any 3d scene)

**Steps to reproduce:**
Close a project with open scenes and reopen

**Minimal reproduction project:**

**Comment by Ranoller** [comment]
I see that file "filesystem_update3" is deleted from  Roaming/godot/projects/projectname on editor open. This file contains name of opened scenes and actual enviroment... I think it´s releated.

**Comment by Ranoller** [comment]
Ok, i find the option. This option should be enabled by default, it´s a bit hidden and disable that by default looks like a bug.

**Comment by groud** [comment]
I agree, I had the same problem

**Comment by vnen** [comment]
No, it should **not** be enabled by default. If you have multiple heavy scenes open, it'll increase the editor loading time significantly.

It should just be better documented so users can know it exists.

**Comment by groud** [comment]
I would make it default provided that we find a way to cancel a scene loading if it takes too much time.

**Comment by Ranoller** [comment]
> No, it should not be enabled by default. If you have multiple heavy scenes open, it'll increase the editor loading time significantly.
> 
> It should just be better documented so users can know it exists.

It´s ok. Problem was fixed by the discovery. I close issue.

**Comment by groud** [comment]
Please don't, I truly believe this should be improved. It is unintuitive as hell for now, ad quite bad UX.

**Comment by akien-mga** [comment]
> It always starts in 3d editor (project doesn´t have any 3d scene)

If you define a main scene, it will start the main scene (that's the most intuitive workflow).

**Comment by KoBeWi** [comment]
> No, it should not be enabled by default. If you have multiple heavy scenes open, it'll increase the editor loading time significantly.

The solution to this is not having multiple heavy scenes open. I mean, if you know they open on project load, then just close them before exiting if you don't want long loading times?

Alternative would be marking/pinning scenes you want to reload, so you don't have to worry that you open too many scenes and forget to close them. There's also #28262, which makes closing multiple tabs easier.

**Comment by name-here** [comment]
This issue is looking kinda dead, but I think this would be a good change.  Would it be better to open a proposal, or just submit a PR for this?  Also, seems weird that it doesn't also remember which workspace you had open, instead inferring it from the root node's type.

**Comment by Calinou** [comment]
> This issue is looking kinda dead, but I think this would be a good change. Would it be better to open a proposal, or just submit a PR for this? Also, seems weird that it doesn't also remember which workspace you had open, instead inferring it from the root node's type.

According to https://github.com/godotengine/godot/issues/16317#issuecomment-362588083, it doesn't seem like it's a good idea to enable it by default.

**Comment by KoBeWi** [comment]
› I think this proposal will be welcomed by small project developers and shunned by large project developers

Large project developers are "advanced" enough to disable this option if needed. But startup time for large project is ridiculously long, regardless if this is enabled or not. Changing default helps discoverability (many people would like to have such option and don't know it already exists), without any real drawbacks.
