### ISSUE TITLE
Missing property thumbnails

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#16315]
**Godot version:**

3.0

**OS/device including version:**

**Issue description:**

When a property has been edited, in this case a Scale Curve and Color Ramp has been added to a 2DParticle, there is no information next to the property only a blank space. This makes it hard to get a quick overview of your settings for any given object. A small thumbnail of the Scale Curve and Color Ramp instead of just nothing would be an improvement. The same goes for all the other properties you can set.

![missinginfogodot](https://user-images.githubusercontent.com/15687516/35726777-538a8f4a-0806-11e8-8076-ff7ac44bf748.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Fixed in the master branch:
![screenshot_20181218_125721](https://user-images.githubusercontent.com/4701338/50152639-76b61200-02c4-11e9-9d4b-b206d836298a.png)
