### ISSUE TITLE
Problems with binds[] array when emitting signal (Mono)

### ISSUE THREAD

**Issue by xfactor2000** [godotengine/godot#16311]
**Godot version: 3.0 stable**

**OS/device including version:**
Manjaro Linux 64 bit (rolling release,so no version is available)

**Issue description:**
Facing multiple issues when trying to pass parameters from pressed signal (probably other signals as well) using `object[] binds`

**Steps to reproduce:**

Please see attached project for full description, to sum it up:
when doing
` b1.Connect("pressed",this,"_on_Button_pressed",new object[]{1,2});`
I get compiler error Method Not Found (when button is clicked)

when doing
` b2.Connect("pressed",this,"_on_Button_pressed",new object[]{1});`
No error is raised, but binds[] array in the function is empty

The only workaround is to wrap the array in another array:
` b3.Connect("pressed",this,"_on_Button_pressed",new object[]{new object[]{1,2}});`

Seems like a bug to me

**Minimal reproduction project:**
[Binds bug.zip](https://github.com/godotengine/godot/files/1688546/Binds.bug.zip)

**Comment by KellyThomas** [comment]
@xfactor2000 
I am finding success with this approach:
```csharp
    public override void _Ready()
    {
        b1 = GetNode("Button1") as Button;
        b1.Connect("pressed", this, "_on_Button_pressed", new object[]{1, 2});
    }

    private void _on_Button_pressed(int p1, int p2)
    {
        GD.Print($"Params: {p1}, {p2}");
        // prints: Params: 1, 2
    }

```

**Comment by xfactor2000** [comment]
@KellyThomas you are right. I think more docs should be added on the matter, right now they're scarce.
