### ISSUE TITLE
Godot fails to launch due to broken Intel HD Graphics 520 Driver

### ISSUE THREAD

**Issue by afeather123** [godotengine/godot#16310]
Godot_v3.0-stable_mono_win64
Microsoft Windows 10 Home
Version	10.0.16299 Build 16299

GPU: Intel HD Graphics 520
Intel HD Graphics 510 515 520 530 540 Driver, Version: 22.20.16.4771 ,A12

Just submitting this so maybe someone else doesn't have to go through the headache I went through with fixing this, couldn't seem to find anything for it specifically. I don't use github a lot so I'm sorry if this is an inappropriate use of this.

Essentially, I recently downloaded godot 3.0 (very hyped to try it out!) and tried running it. I got a string of errors and I ran it in debug mode and said that there was an error with ig9icd64.dll saying there was an access violation trying to read from some register. I looked up the file and found this intel developer thread, perhaps it could be useful to you. Eventually I found the mojang site saying the file was part of the graphics driver. I had to rollback the driver to version Version 21.20.16.4590, A11 published on 25 Apr 2017. 

My laptop model is a "Inspiron 13 7368 2-in-1." I think this problem would mainly apply to similar models with 6th gen intel processors and integrated graphics. Hope this helps somebody out.

https://software.intel.com/en-us/forums/graphics-driver-bug-reporting/topic/731358
https://bugs.mojang.com/browse/MC-94900

**Comment by akien-mga** [comment]
Thanks, that's useful!

I'll close the issue as there's nothing to fix on our end, but hopefully others with the same issue will land here when doing a search on GitHub or their search engine.
