### ISSUE TITLE
Camera2D offset and smoothing problem

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#16323]
**Godot version:**

Godot 2.1.4 (And Godot 3 i suppose but i don´t test)

**OS/device including version:**

Win7

**Issue description:**

Same problem that is described here #2074 in camera zoom and was fixed in godot 2 and 3 (camera stops and later continue with smoothing different that 0), happends when changing camera offset.

Edit: Happends too with camera rotation.

**Steps to reproduce:**
Change camera offset and return to 0,0 in runtime with camera smoothing

**Minimal reproduction project:**

I will try...

**Comment by svendixon** [comment]
I am not sure if this is related. 

But I created a test project that shakes the **camera** using the **offset**. 

After the camera shakes, the movement of the camera is very choppy. It only goes away if you free() the current camera and create a new instance of it.

**Tested in Godot 3 and 3.1 beta2**

![choppy_camera](https://user-images.githubusercontent.com/14341036/51785592-18344d00-2128-11e9-8726-1a366e72d6ae.png)
[Choppy Camera.zip](https://github.com/godotengine/godot/files/2798861/Choppy.Camera.zip)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Ranoller** [comment]
The bug is still reproducible and the example project is in the last comment.

**Comment by Calinou** [comment]
@Ranoller We'd prefer a test project that's made with Godot 3.2, as Godot 2.x projects need to be exported for Godot 3 before they can be opened there.

**Comment by Ranoller** [comment]
I test commited code in 3.2 at 93e20a4cd4513673b297feeb92012900862607ad and works without visible regressions. Code of Camera2D has no changes from 3.2.2 to 4.0, so same solution can be used. I test with the example provided in this issue by @svendixon.
