### ISSUE TITLE
Bone attachment GlobalTransform rotation treats z as up

### ISSUE THREAD

**Issue by cart** [godotengine/godot#16339]
**Godot version:**
95cfa9bf74774110ba01a3987a22c9d7d616c1c6

**OS/device including version:**
Arch Linux

**Issue description:**
BoneAttachments treat z as up when their GlobalTransforms are read directly.  The resulting position is correct but the rotation is wrong.

**Steps to reproduce:**
1. Add a BoneAttachment to a skeleton and set its bone target
2. Copy the GlobalTransform of the bone attachment to a mesh
3. Observe that it is facing the wrong direction

**Minimal reproduction project:**
[BoneAttachmentRotation.zip](https://github.com/godotengine/godot/files/1691319/BoneAttachmentRotation.zip)

This project copies the GlobalTransform from a BoneAttachment to a mesh that is facing up (according to godot).  It should start facing up because the bone is also facing up, but it actually points ~forward (into the screen)~ out of the screen.

It includes the blend file that generated the .dae containing the skeleton

**Comment by reduz** [comment]
BoneAttachment just copies the transform of the bone, which isn't warranted to be anything in particular.
Simply put another node as child of BoneAttachment and re-orient it the way you want.
