### ISSUE TITLE
Haiku fails building on x64 (g++-x86: command not found)

### ISSUE THREAD

**Issue by skarmiglione** [godotengine/godot#16330]
Hello i am here to ask a version for haiku x64, seems like it have the part to get builded on x86 but when i try scons p=haiku this happen  : scons p=haiku
scons: Reading SConscript files ...
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
X11 not found.. x11 disabled.
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] run(["core/method_bind.gen.inc", "core/method_bind_ext.gen.inc"], ["core/make_binders.py"])
[Initial build] Compiling ==> platform/haiku/godot_haiku.cpp
sh: g++-x86: command not found
scons: *** [platform/haiku/godot_haiku.haiku.tools.64.o] Error 127
scons: building terminated because of errors.

**Comment by skarmiglione** [comment]
Ok i forgot to say it is on x64 version but the title is clear with that anyway i try to clear with this.

**Comment by extrowerk** [comment]
It is clear: on x86_64 the g++ called as g++ n6t as g++_x86. Fix the build tools. Make a patch, send it upstream.
Or fix it in HaikuPorts.
Do not forget to check it on gcc2h.

**Comment by Overblob** [comment]
I don't know if this would work with haiku builds, but have you tried to specify the bitness of the build in the command line?

ie: scons p=haiku bits=64

**Comment by akien-mga** [comment]
If you find the right configuration for 32-bit and 64-bit Haiku, you can fix it here: https://github.com/godotengine/godot/blob/master/platform/haiku/detect.py#L62-L65

**Comment by akien-mga** [comment]
Note that beyond fixing this, there are likely many changes needed to get the Haiku platform to build again on the master branch. No Haiku developer has worked on porting the existing 2.x platform code to 3.0 (some fixes were made with "search and replace" by non-Haiku developers, but likely not all the needed ones).

**Comment by skarmiglione** [comment]
I did replaced the g++-x86 with just g++ but start to call a unexistent "alloc" ... then i am not able as it seems.

**Comment by akien-mga** [comment]
Is this still reproducible? There were various fixes to the Haiku build and it now builds fine at least on x86, might work on x64 too.

**Comment by KoBeWi** [comment]
Seems like there was no response to the previous question, so closing this as resolved.
The issue can be reopened if someone manages to reproduce it in Godot 3.2.1 or newer.
