### ISSUE TITLE
Mono version crashes on start

### ISSUE THREAD

**Issue by ScratchOs** [godotengine/godot#16333]
**Godot version:**

3.0 mono version

**OS/device including version:**

Intel integrated HD Graphics
intel i5 4th gen
windows 10

**Issue description:**

Godot crashed reproducibly when opening project, I expected it to not crash.
![error](https://user-images.githubusercontent.com/12380303/35752859-57429bd8-0855-11e8-9920-b56163550a44.png)

**Steps to reproduce:**
open project

**Minimal reproduction project:**

[project](https://github.com/ScratchOs/static/blob/master/godoterror.zip)

**Comment by eon-s** [comment]
Your system has 2 graphics cards? (there is a mention of nvidia optimus there)

**Comment by ScratchOs** [comment]
No, I don't tink so, it only states it has integrated graphics but it's a laptop so I cannot open it to check

**Comment by akien-mga** [comment]
Do you have the Mono SDK installed? If so, what version (and what architecture)?

You seem to use the 32-bit version of Godot, you might need the 32-bit version of the Mono SDK. (But I guess an Optimus laptop with an Intel HD 4400 as IGP and Windows 10 is a 64-bit build, no?).

**Comment by ScratchOs** [comment]
@akien-mga Thank you for that, switching to 64bit fixed it!
