### ISSUE TITLE
[2D Feature Proposal] A more simple way to detect collisions between Area2D nodes

### ISSUE THREAD

**Issue by Arkhano** [godotengine/godot#16342]
Another 2D Feature proposal to make Godot 3 even more friendly for beginners.

Today I read a comment from a great youtube creator (HeartBeast) of Gamemaker 2 and Godot 3 content. It's about what features that he wish were implemented into Godot 3. Gonna create one post per feature request (there are three).

The feature proposal is "a more simple way to detect collisions between Area2D nodes".
(I'm honestly not sure what this would look like but something that would be easier for beginners).

His channel is https://www.youtube.com/user/uheartbeast/videos

Thank you.

**Comment by cbscribe** [comment]
> "a more simple way to detect collisions between Area2D nodes"

This is not really a suggestion, it's a vague statement with no actionable content. What's "hard" about Area2D now? You connect the `area_entered` signal.

As a teacher, I can tell you "easier for beginners" is a very debatable topic. What one person finds easy, another has trouble grasping. What does "beginner" mean? New to Godot? New to game dev? New to programming entirely? These are all wildly different states of mind.

I would recommend closing this unless there's a specific suggestion to discuss.

**Comment by vnen** [comment]
I'm not sure why you are opening issues in HeartBeast's behalf (did he ask you to?), but this description is not helpful at all.

> "a more simple way to detect collisions between Area2D nodes"

I'm sorry, but that could mean anything. I find it quite simple already. Are you having trouble with the current way? In which step the workflows fail for you? Did you try something and it didn't work? Do you have a concrete suggestion?

I advise you to read the Godot's [FAQ](http://docs.godotengine.org/en/latest/about/faq.html#i-have-a-great-idea-that-will-make-godot-better-what-do-you-think), especially the linked section about ideas.

**Comment by eon-s** [comment]
More simple than a signal callback and the use of `get_overlapping_areas`? (remember Areas do not collide)

Also an engine should not point to be beginner friendly, beginners are in that situation for a couple of weeks only then stop being in that group after learning how things work, the only thing useful in that short timespan (for any tool) are documentation and tutorials.

**Comment by Ranoller** [comment]
All the repect to any youtuber that do content to godot. You can tell to him that there is a system for wishes in the patreon (not necesary to contribute, it's open) and everyone can proposal all kind of things (specific or not).
