### ISSUE TITLE
[2D Feature Proposal] Ability to have a collision shape auto generated when you add a sprite to a physics body or Area2D.

### ISSUE THREAD

**Issue by Arkhano** [godotengine/godot#16341]
It's a 2D Feature proposal to make Godot 3 even more friendly for beginners.

Today I read a comment from a great youtube creator (HeartBeast) of Gamemaker 2 and Godot 3 content. It's about what features that he wish were implemented into Godot 3. Gonna create one post per feature request (there are three of them).

The feature proposal is "the ability to have a collision shape auto generated when you add a sprite to a physics body or Area2D".

His channel is https://www.youtube.com/user/uheartbeast/videos

Thank you.

**Comment by vnen** [comment]
Auto-generated is not really good because not always you want the shape to be the same as the sprite (simpler shapes are better for performance too).

About the ability for the engine to generate shapes from sprites, than there's already #3405 open. I'll close this issue since it's essentially the same proposal.

**Comment by xeranas** [comment]
> simpler shapes are better for performance too

@vnen is there automatically way to add 2d rectangle shape collision which is same width and height as sprite?

**Comment by vnen** [comment]
@xeranas not out of the box, but it's not hard to make a plugin to do it, or just make it on runtime. I don't think it's useful apart from a handful of sprite styles though. BTW, no need to ask questions in a closed issue, just use one of the [community channels](https://godotengine.org/community).
