### ISSUE TITLE
Jump on Tileset

### ISSUE THREAD

**Issue by ductuan9603** [godotengine/godot#16340]
Hello,
I'm trying to make a 2d platform game. My player is Rigidbody2D.
I have a function in player.gd to check if the ground is in group "GROUND", so that player can able to jump:

```
#ground check
func ground_check():
    if ground_detector.is_colliding():
        var body = ground_detector.get_collider()
        if body.is_in_group("GROUND"):
            return true
    else:
        return false
    pass
```

I have added group "GROUND" to a StaticBody2D, and it works. But when I try to add group "GROUND" to a Tileset (even the Tilemap), the player still can't jump.

Can anyone help me?
Here's the picture. The red circle is the tilesets that my player cannot jump 
![capture](https://user-images.githubusercontent.com/25024069/35762227-d5277e68-08c5-11e8-9a37-e76811cebab9.PNG)

**Comment by eon-s** [comment]
Is this Godot 2?
What is the exact issue? how are you moving your character? when are you doing the ground check?

**Comment by ductuan9603** [comment]
yes, it's Godot 2.1.4
I use state machine for the movement of the character. This is the code: 

```
func move(to_speed, acc): 
	current_speed.x = lerp(current_speed.x, to_speed, acc*0.01) #acc * 0.01, turn into percent
	set_linear_velocity(Vector2( current_speed.x, get_linear_velocity().y ))
	pass
	
#jump function
func jump(force):
	set_axis_velocity( Vector2(0,-force) )
	pass

##STATES

#ground
func state_ground():
	#inputs
	if btn_left.check() == 2:
		direction = -1
		move( direction * max_run_speed, accerleration)
	elif btn_right.check() == 2:
		direction = 1
		move( direction * max_run_speed, accerleration)
	else:
		move(0, accerleration)
	
	#check state
	if !ground_check():
		state_machine.pop_state()
		state_machine.push_state(STATE.AIR)
	pass
	
#air
func state_air():
	#inputs
	if btn_left.check() == 2:
		direction = -1
		move( direction * max_run_speed, accerleration)
	elif btn_right.check() == 2:
		direction = 1
		move( direction * max_run_speed, accerleration)
	else:
		move(0, accerleration)
	#state
	if ground_check():
		state_machine.pop_state()
		state_machine.push_state(STATE.GROUND)
	pass
```
the _ground_detector_ in function "ground_check" above is a raycast2D, which is lied under the character. So, the idea is if the character is standing on thing which is added to group "GROUND", it will return true and be able to do the next state (like jump). I have tested on a simple staticbody2d (in the picture) and it works. But the problem is when I do the samething (add to group GROUND) with a tileset or tilemap, it doesn't work.
Do you have any idea to fix it?

**Comment by eon-s** [comment]
For that kind of movement you should alter the velocities modifying the state inside `_integrate_forces` and enabling the custom integrator like in the platformer demo (which uses rays too for some extra functions).

**Comment by akien-mga** [comment]
It would be better to ask such questions in the Godot Q&A: https://godotengine.org/qa/
Or in another of the community discussion platforms such as the Forum, Reddit, Facebook group, Discord, etc.: https://godotengine.org/community

This issue tracker is for engine bugs and feature proposals, not for user support.

**Comment by akien-mga** [comment]
Note that if you actually find that there's a bug in the TileMap that makes your code fail, opening an issue about it would be the right thing to do, but it should then come with a minimal example projects that lets us reproduce it and debug further. Engine developers can't really help debug your game itself.
