### ISSUE TITLE
Wiki: licensing FAQ

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#1635]
In order to help against legal uncertainty when making games (and other stuff), I've written a licensing FAQ page (attribution is appreciated but not required). I am pretty sure (but not 100 % sure) the content is valid.

(Note that I'm not a lawyer professionally, I'm just someone who studies copyright as an hobby.)

Could you add this to the wiki, please? This uses Markdown formatting.

``` Markdown
**DISCLAIMER: this is not legal advice.**

This page lists common questions about the licensing of Godot and possible uses.

Q: Can I use Godot in my FLOSS project?
============================================

A: **Of course!**
This is encouraged so that people can learn about Godot and study how it works.

Q: Can I use Godot in my commercial project?
=================================================

A: **Yes, you can.**
Anyone is free to use Godot for both commercial and non-commercial purposes. There are no royalties to pay.

Q: Can I use Godot in my proprietary project?
==================================================

A: **Yes, you can.**
You are not required to release the source code or the assets of your project.

Q: Do I have to release my changes to the source code?
======================================================

A: **You don't have to release your changes**.
This means you don't *have* to contribute to Godot upstream, although your help is appreciated.

Q: Which licenses can I use for my code?
========================================

A: **In case you release the source code, almost any software license is valid.**
It is recommended to use the MIT license or CC0 (public domain waiver)
as it allows us to benefit from your changes and additions (ie. merge them upstream),
but you can also use Apache, BSD, GPL or LGPL (any version) if you desire.

Note that Creative Commons licenses (other than CC0) are **not recommended** for software.
Please refrain from using them on code, however you can use them on assets just fine.

Q: Which licenses can I use for my assets?
==========================================

A: **Any license can be used for your assets**, including but not limited to:

* Creative Commons licenses,
* Public domain waivers (CC0, Unlicense, …),
* The MIT license (of course),
* Your own custom, proprietary license,
* …

Q: Am I allowed to remove the Godot splash screen? In other words, do I have to provide prominent attribution?
==============================================================================================================

A: **Yes.**
The splash screen is not required. No *prominent* attribution is required,
however a mention of Godot engine in your project's credits and/or website is appreciated.

Q: Do I grant a license to Godot developers over my project?
=========================================================

A: **No, your project stays yours.**
```

Feel free to correct me, or to suggest new questions to add. You can paste the Markdown code [here](http://markdownlivepreview.com/) for a preview of how it would look on the wiki.

**Comment by UsernameIsAReservedWord** [comment]
**DISCLAIMER: this is not legal advice.**

Strangely, I find this disclaimer increases legal uncertainty and doubt.

**Comment by Calinou** [comment]
> DISCLAIMER: this is not legal advice.
>
> Strangely, I find this disclaimer increases legal uncertainty and doubt.

Obviously, I can't give any guarantees. This is not perfect, this is better than nothing,

**Comment by seadra** [comment]
MIT License itself is much shorter that this FAQ.
You can simply redirect to its [Wikipedia page](http://en.wikipedia.org/wiki/MIT_License) for further information.

Also, a Google search on "MIT license FAQ" returns [this])(http://www.tophatstuff.co.uk/archive.php?p=40) among many others.

**Comment by TheoXD** [comment]
I'm not a layer either but here's the thing.. MIT license states "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." and because there is no definition of "software" it can be misinterpreted. Software can be defined as a set of machine instructions (which is binary file) meaning you're legally obligated to put a MIT copyright somewhere in the executable file. So mentioning of godot is not required, but copyright notice must be included somehow (not necessarily has to be rendered to the screen). But to play it safe - just include it in the credits and be done with it.

**Comment by Calinou** [comment]
> That being said, you can simply redirect to its Wikipedia page for further information.
Also, a Google search on "MIT license FAQ" returns this among many others.

You'd be surprised at how people are still uncertain over it.

**Comment by kubecz3k** [comment]
What is the status of this issue now when the site is on open project? Is it still needed? Maybe it's already added in one form or another on the site?

**Comment by akien-mga** [comment]
We should add a page similar to Blender's on the main website.

**Comment by akien-mga** [comment]
For the reference, the license page on the website should likely have a human readable version of https://github.com/godotengine/godot/blob/master/COPYRIGHT.txt

**Comment by akien-mga** [comment]
I added https://godotengine.org/license a while ago which covers the most important points. Further work on this will be done directly in the engine to provide features to easily credit the engine and thirdparty libraries.
