### ISSUE TITLE
Automatic switch to viewport in background when playing a scene

### ISSUE THREAD

**Issue by Overblob** [godotengine/godot#16357]
**Godot version:** 
Commit 4ab522799d833c5118f7335a7849d488f7fb3e35
(3.0)

**OS/device including version:**
Windows 10 x64
NVIDIA GeForce GTX 970

**Issue description:**
Hi!
When you play a 2d or 3d scene, the editor view tab automaticaly switches to 2d or 3d viewport (respectively) no matter the viewport you're currently using (gdscript editor included!).

It's maybe not a bug, but it becomes very annoying when you have to go back to the gdscript editor each time you launch your scene when debugging (yes I'm this kind of lazy guys :p).

As I think I'm not the only one to find it inconvenient I prepared a PR for this.

Just waiting your feedback before publish it (as it currently disables this autoswitch for 2d, 3d viewports and gdscript editor).

**Steps to reproduce:**
1 - Create a New Project
2 - Create a new Scene with either a 2D node or a Spatial node
3 - Go to the Script tab with F3
4 - Play the scene

**Minimal reproduction project:**

**Comment by vnen** [comment]
I can't reproduce this.

**Comment by Overblob** [comment]
Strange...if you can try it, I get the same behaviour on Ubuntu 17.10 with the last daily build of Godot 3.0.
Could it be linked to some config parameters?

**Comment by Calinou** [comment]
I can reproduce this when running my [Sponza demo](https://github.com/Calinou/godot-sponza).

**Comment by mhilbrunner** [comment]
Reproducing this too, using the official Godot 3 download for Windows (Windows 7, 64 bit).

**Comment by akien-mga** [comment]
I guess it does this to save a preview of the scene, but I thought we had implemented a way to do it without having to select the viewport.

**Comment by Overblob** [comment]
A preview, for thumbnails you mean?

**Comment by Calinou** [comment]
> A preview, for thumbnails you mean?

I guess that's what @akien-mga meant. 😃
