### ISSUE TITLE
Show in File Manager

### ISSUE THREAD

**Issue by CezaryKopias** [godotengine/godot#16356]
**Godot version:**
Godot 3.0 x64

**OS/device including version:**
Windows 7 x64

**Issue description:**
Godot Editor freezes after "Show in File Manager"

**Steps to reproduce:**
just go to resources right click and use "Show in File Manager"

**Comment by Noshyaar** [comment]
Related #9957

**Comment by binbitten** [comment]
Only way I'm able to replicate is using 32-bit godot in 64-bit win7. Sure you're not using 32-bit godot?

**Comment by avril-gh** [comment]
Win7 32bit
Godot 3.0 x86 stable official
**Cant replicate this bug**.

**Comment by vnen** [comment]
I was never able to replicate this, but apparently a few users still experience it.

**Comment by Ranoller** [comment]
I can't replicate, same system, nor with 32 or 64 bit, nor in win7 32 or win7 64. Can you do a test? Can you open a project situated in desktop, insider other user/ folder or other unit than c:? It's for discard permission problem.

**Comment by vonflyhighace2** [comment]
I think this has to do with windows itself. I had the same problem actually I think I was the first to create an issue. after A windows update or something windows related the issue went away.

**Comment by CezaryKopias** [comment]
seams that way

my windows 7 is offline from quite some time
tested on updated version and the issue is gone

**Comment by CezaryKopias** [comment]
I don`t expect much but maybe someone knows howto identify and download patch for windows with fix to that.
