### ISSUE TITLE
Create a framework for offering narrative scripting language support

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#16368]
**Godot version:**
Godot 3.x

**Issue description:**
There are tools that exist to create interactive storytelling ([Twine](http://twinery.org/), [Yarn](https://github.com/infiniteammoinc/Yarn), [YarnSpinner](https://www.secretlab.com.au/blog/2016/2/10/yarn-spinner), [Ink](https://www.inklestudios.com/ink/), [Articy: Draft](https://www.nevigo.com/en/articydraft/overview/), etc.) and I think Godot could benefit from outlining a clear interface for how Godot might interact with some of these tools' "narrative scripting languages". Specifically, I think allowing the Godot editor to detect and respond to changes in "narrative script" text files would be to its advantage. Because these scripting languages still usually involve the creation of variables and macros for linking dialogue content, the processing associated with them is more involved than just making them a data file of some sort, but neither is their behavior quite as extensive as the existing classes in `script_language.h`.

To that end, I would recommend integrating some types that support `NarrativeScriptLanguage`, `NarrativeScript`, and `NarrativeScriptInstance` types (don't know if these would need to be related at all to the stuff in core yet), all of which could be kept in some kind of module. I'd ultimately like to be able to create a module or plugin that creates an editor for creating these narrative script contents, similar to the graph-based editors that other tools have).

From my experience, a narrative scripting language is responsible for providing a textual representation of the structure of interactive dialogue sequences and their contents. They typically include the following features...

1. Allow for multiple threads of dialogue to run simultaneously.
2. Allow users to define a render target, i.e. "where text will be written to" (probably a RichTextLabel reference by default?).
3. Upon command, add a specified string of text to the render target (you'd have a buffer with delimiters of some kind, and every time you "advance" you would print out the content up to the next delimiter).
4. Allow users to embed the content of one narrative script file within another.
5. Allow users to define links (either via hyperlink in the text or by code) that will trigger an external file to have its content loaded next.
6. Allow users to define and edit variables at runtime which can be inserted into the story content as text (so scripts can request access to a centralized storehouse of script properties for their story).
7. Allow users to define control flow patterns such as if/elif/else, switch/match, for/while loops, etc. to control when a given segment of text should be processed next.
8. Allow users to define functions and/or macros to bundle up subsections of files.
9. Keep track of story-related information like the historical sequence of file-links that have been triggered (so a NarrativeScriptInstance might have a method that adds a particular file path or link name to an array of previously loaded segments. The arrays could then be stored in a map of stories and their respective data in the NarrativeScriptLanguage singleton, etc.).

This type of feature could be extremely useful for Visual Novels, Simulations, and Role-Playing Games, so it's breadth of utility is spread out enough I think.

Personally, I am interested in creating a StoryScript narrative scripting language that would transpile into GDScript, but which ideally could also be edited in the ScriptEditor. That's my use case.

**Comment by vnen** [comment]
While I see the point, I don't think this is something to get in the core. I know it's used by many types of games but each game has specific needs and it's difficult to get a system that attends them all. The fact that there a ton of those systems also tells a lot.

If you want a base to interact with most the dialogue creation tools, either we go with the minimum feature set (and not support them well anyway) or use a greater set (thus bloating the core). Those systems are likely very far from each other in terms of API, and probably would require an abstraction layer which IMO defeats the point. This doesn't sound like a good solution to me.

I think it can be achieved without touching the base engine, by use of PluginScript for instance. In the end is just data: the game script feed data to the dialogue system which does its things to generate the proper text. The engine doesn't need to offer a central place for that, you can do it with an autoload if need be.

Also, this opens a can of worms to add base API to other systems.

The possibility of using the script editor for other types of files handled by plugins is an idea that I like though.

**Comment by willnationsdev** [comment]
@vnen Very fair points. I hadn't thought of using `PluginScript`s to set them up, but that'd be a really good idea. Then you could add a plugin which provides an editor interface for these specific types of plugin scripts in the first place, and then allow that to serve as a base for people to create `PluginScript`s that work with the graph editor for each desired narrative scripting language.

**Comment by willnationsdev** [comment]
> The possibility of using the script editor for other types of files handled by plugins is an idea that I like though

@vnen Isn't this basically covered by the combination of `PluginScript`s (which handle script new script file types) and #1390?

**Comment by naturally-intelligent** [comment]
Related: built a basic Yarn importer for Godot:

https://github.com/naturally-intelligent/godot-yarn-importer
