### ISSUE TITLE
Moving an animated node deletes all of the keyframes in the corresponding animation player

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#16369]
So I have a sprite animated with the animation player and decided to move the sprite into its sibling's hierarchy, and this caused me to lose all of my keyframes in all of my animations. I recommend an automatic refactor for when you move or rename sprites around the hierarchy, as having to remake the animations all over again due to a simple hierarchy change is frustrating.

**Comment by API-Beast** [comment]
I think the main issue here is that invalid keyframes do not get stored when saving the scene and thus you get data loss. Storing the keyframes no matter what would at least allow you to manually fix it once you notice the issue.

**Comment by eon-s** [comment]
I cannot reproduce (moving a animated node around), care to detail the process on how was the scene structure and where was the node moved when keys got deleted?

**Comment by 11clock** [comment]
@eon-s i have a player scene with a kinematic body 2D, and its children are a sprite, a collision shape, and an animation player that animated the sprite. I created a new Node2D under the kinematic body and moved my sprite into its hiearchy. Then later ran the game and noticed my animations were not working. I checked my animation player and noticed that all of the keyframes vanished, and checked the scene's data to confirm that the data for the keyframes was erased.

**Comment by eon-s** [comment]
Is weird, and still cannot reproduce, when I move the sprite, the corresponding tracks get renamed to match the new location.
Maybe there is something in particular that triggers the bug.

**Comment by DualMatrix** [comment]
Tested in master, it worked perfectly fine for me as well.

**Comment by 11clock** [comment]
I haven't had this issue since the time of report, so this can probably be closed.
