### ISSUE TITLE
Isotropic Mipmapping incorrect with non-power-2 textures

### ISSUE THREAD

**Issue by sdfgeoff** [godotengine/godot#16367]
**Godot version:**
Latest Master
(Technically [this branch](https://github.com/sdfgeoff/godot/tree/apply_torque), but the only change is to do with physics as per an open pull request, and it was updated to master a few hours ago)

**OS/device including version:**
Archlinux 64bit. GPU is Intel HD4400

**Issue description:**
When viewing textures from shallow angles, the isotropic mipmapping behaves poorly if the texture has a non power of two texture. I would expect that regardless of texture resolution, the isotropic mipmapping should create the image on the right.
Example:
![mipmap](https://user-images.githubusercontent.com/13490050/35771748-ff11ba4c-0931-11e8-82af-4c5bfb4d6c27.jpg)

Example in a game environment:
![isotropic-mipmapping](https://user-images.githubusercontent.com/13490050/35771751-1ad9dd22-0932-11e8-8d5c-96887d079150.jpg)
Here the texture is a bit higher resolution than the grid example, and on the left-hand-wall you can clearly see that it gets offset by some fixed amount (presumably the difference between texture size and power-of-two)

**Minimal reproduction project:**
[MipMap.zip](https://github.com/godotengine/godot/files/1692211/MipMap.zip)

**Comment by Noshyaar** [comment]
Closing as fixed by #17232

**Comment by reduz** [comment]
I can understand why that solution works better, though I hope scaling of
some image types does not break
