### ISSUE TITLE
Mac IDE - Visual Scripting formatting issue

### ISSUE THREAD

**Issue by codestick** [godotengine/godot#16377]
**Godot version:**

3.0

**OS/device including version:**

OS High Sierra

**Issue description:**

Is pushing the visual scripting label text outside of the boundary

**Steps to reproduce:**
Visual Scripting in Mac IDE
<img width="567" alt="screen shot 2018-02-04 at 07 34 44" src="https://user-images.githubusercontent.com/30180992/35775314-76912e4e-097e-11e8-96e5-2bce6a910836.png">

**Minimal reproduction project:**

**Comment by fire** [comment]
Can you check if this bug still exists?

**Comment by Calinou** [comment]
With the editor scale set to 200%, it seems to look fine as of https://github.com/godotengine/godot/commit/6097a5af14cee12e52f98794459b0484966f2239:
![visual_script_hidpi](https://user-images.githubusercontent.com/180032/46856072-c4665800-ce05-11e8-87f3-e5f3b2faea54.png)

**Comment by fire** [comment]
Closing due to seeming to look fine.
