### ISSUE TITLE
Feature Request. Navigation Node with collision Obstacle support

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#16375]
**Godot version:**
Any

**OS/device including version:**
Any

**Issue description:**
The Navigation/AI features are very limited. A navigation mesh that takes into account collision obstacles would be a nice feature. This I believe is actually required for proper navigation is it not?

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by volzhs** [comment]
duplicated with #3130

**Comment by vnen** [comment]
Closing as duplicate.
