### ISSUE TITLE
Godot always on top when in fullscreen mode, preventing access to hidden Windows taskbar. 

### ISSUE THREAD

**Issue by TylerCompiler** [godotengine/godot#16371]
**Godot version:**

3.0

**OS/device including version:**

Windows 10 Version 10.0.16299 Build 16299

**Issue description:**

While in fullscreen mode, window is always on top, preventing users from being able to access the Windows taskbar if it's set to hidden. This persists even when it is no longer the focused/active window. 

**Steps to reproduce:**
Fullscreen Godot, and attempt to access a hidden Windows taskbar.

**Comment by girng8rgtrhgtrh** [comment]
what happens when alt-tab is pressed?

**Comment by TylerCompiler** [comment]
I can alternate windows normally, but until Godot is either removed from fullscreen, or exited completely, it still removes the ability to show the taskbar by hovering the mouse over it, even if I have alt-tabbed to a new window.

**Comment by Calinou** [comment]
@TylerCompiler Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
