### ISSUE TITLE
run command in res:// folder on android

### ISSUE THREAD

**Issue by vzex** [godotengine/godot#16379]
godot:v3.0 stable
```gdscript
func _ready():
	var output = []
	var code = OS.execute(ProjectSettings.globalize_path("res://") +"/xxx.binary", ['-service', ':1234'], false, output)
	print(code, output)
```
in windows editor the process runs ok,but when i export it to android(with xxx.binary packed in the apk),I saw the adblog,code is > 0, but there is no process with the same pid in "ps". So is this the right way to run the command?

**Comment by akien-mga** [comment]
What is `xxx.binary`? Is it an application that can run on Android?

**Comment by vzex** [comment]
@akien-mga xxx.binary is just a simple test program compiled on linux/arm,like hello world written in c, or written in go, I tested the program with adb shell, and it runs good, but i don't know that is there any way to pack it into the apk, and execute it in gdscipt

**Comment by vnen** [comment]
Note that only resources are exported in the APK. You need to add include filters to actually export that file.

**Comment by akien-mga** [comment]
As mentioned by @vnen, the binary needs to be listed explicitly in the export filters to be included in the APK. That was likely the issue.
