### ISSUE TITLE
Renaming File to Same Name But Different Case: "A file or folder with this name already exists."

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#16384]
**Godot version:**
Godot 3.0 Stable

**OS/device including version:**
Windows 10

**Issue description:**
I am trying to change all my file names from PascalCase to camel_case, but I keep hitting "A file or folder with this name already exists" errors. It is like the editor cannot tell the difference in file names in terms of case.

**Comment by Zireael07** [comment]
Godot runs on systems that are non case sensitive, too, so it's not case sensitive.

**Comment by vnen** [comment]
This is an issue with Windows, because it doesn't consider case when checking the existing files. There's already an open PR to fix this: #15959

**Comment by akien-mga** [comment]
Fixed by #15959.
