### ISSUE TITLE
Godot 3.0 3Din2D template example, exported to android not show viewport.

### ISSUE THREAD

**Issue by emo44** [godotengine/godot#16386]
**Godot version:**
3.0 Stable

**OS/device including version:**
Android Version 5.1.1
OpenGL ES 3.0 V 100.0 AU , GPU RENDERER Adreno

**Issue description:**
3Din2D template example, exported to android not show viewport scene

**Steps to reproduce:**
Export proyect to android with defaults settings in debug mode.

**Minimal reproduction project:**
the 3din2d official godot template for 3.0

**Comment by akien-mga** [comment]
Likely the same issue as #12816, Adreno OpenGL ES 3.0 drivers are terrible and Godot 3.0's 3D is broken on such devices. This will be fixed in 3.1 with the new OpenGL ES 2.0 renderer, which will be enforced on Adreno GPUs until they start making decent drivers for their hardware :)
