### ISSUE TITLE
Input.IsKeyPressed should be able to receive an item from the KeyList enum without having to cast it to int (C#)

### ISSUE THREAD

**Issue by Kiloku** [godotengine/godot#16388]
**Godot version:**
3.0 Stable (Mono)

**OS/device including version:**
Windows 10 Home

**Issue description:**
In C#, the `Input.IsKeyPressed` function can only receive an `int` as parameter, which forces me to cast `Godot.KeyList` values into their `int` values. It'd be easier to work with if the function could receive a `KeyList` value in the first place.

**Example:**

`if (Input.IsKeyPressed((int)Godot.KeyList.Left))` 
could be better as
`if (Input.IsKeyPressed(Godot.KeyList.Left))`

It is, of course, a very minor issue, but each little thing goes a long way toward increasing C# usability.

**Comment by redxdev** [comment]
Actually, this is an issue pretty much everywhere enums are used. Definitely would be nice to have fixed.

**Comment by neikeq** [comment]
This is because the method declaration in C++ uses int instead of the enum. Is there a reason for that?

**Comment by akien-mga** [comment]
> This is because the method declaration in C++ uses int instead of the enum. Is there a reason for that?

CC @reduz; would it be possible to use [`KeyList`](https://github.com/godotengine/godot/blob/master/core/os/keyboard.h#L55) for scancodes, or would it add too much complexity?

**Comment by exts** [comment]
any update on this ? (cc: @reduz )

**Comment by neikeq** [comment]
I've been looking at the code and `is_key_pressed` only checks a set filled with values from `InputEventKey::get_scancode()` which as far as I can tell can only use `KeyList` (even though it uses `int`).

I will make a PR, but I will let someone with more knowledge decide whether to merge it or not as I'm not confident enough about this.

**Comment by aaronfranke** [comment]
Just an update on this issue, this is waiting for #38054 to be reviewed and merged so that I can remake #27450.

**Comment by EricEzaM** [comment]
This can be closed now right @aaronfranke? In C++ all keys are now referenced by the `Key` enum.

**Comment by XR4Y-TEDDY** [comment]
Hey so I'm new to Godot and C# too but does anyone how to detect if a key a released, because I can't find information ANYWHERE on how to do it and i've been really stuck

**Comment by raulsntos** [comment]
This was implemented by #47378
