### ISSUE TITLE
JSON.parse returns JSONParseResult with valid json

### ISSUE THREAD

**Issue by m-irigoyen** [godotengine/godot#16389]
**Godot version: 3.0**

**Windows 8**

**Issue description:**
JSON.parse returns a JSONParseResult object in trivial cases (which are valid JSON), including the documentation example (found here : http://docs.godotengine.org/en/latest/classes/class_jsonparseresult.html#class-jsonparseresult)
I expected to get an array, as in the documentation example.

**Steps to reproduce:**
New project.
Add new node.
Add built-in script to this node
In _ready(), copy-paste the example code from the documentation : http://docs.godotengine.org/en/latest/classes/class_jsonparseresult.html#class-jsonparseresult
Execute. Log outputs "unexpected result"

**Minimal reproduction project:**
[testgodotjsonbug.zip](https://github.com/godotengine/godot/files/1692886/testgodotjsonbug.zip)

**Comment by vnen** [comment]
The documentation is wrong, `JSON.parse()` always return a `JSONParseResult`.
