### ISSUE TITLE
Light icon in 3D view is low-resolution

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#1638]
The light icon in the 3D view is low-resolution, which makes it ugly. I'm using a 1920×1080 screen. It also has visible clipping (because a non-fully transparent pixel touches the edge of the image).

*Click on the image to enlarge it.*

![Image](https://lut.im/vGZAe5UQ/qNo27TpW)

**Comment by bojidar-bg** [comment]
Same here

**Comment by tonymtbird** [comment]
it would be better if it was just an outline, similar to lights in blender.

**Comment by bojidar-bg** [comment]
@tonymtbird +1

**Comment by reduz** [comment]
add this to this document, together with your ideas
https://groups.google.com/forum/#!topic/godot-engine/f4x7hJGUD7M

**Comment by reduz** [comment]
so it can be changed in 1.2

**Comment by akien-mga** [comment]
See also from #2792:

![huge_light_icon](https://cloud.githubusercontent.com/assets/3391055/11169791/098d83ba-8bc2-11e5-83e2-415650ebf4f6.png)

**Comment by tonymtbird** [comment]
i've made a super simple possible fix to this, when i get time i will set up a pull request.  Since its so simple it doesn't matter if it is ever used or not..

**Comment by neikeq** [comment]
I think it's worth having a look at this (if not already being worked) with the recent HiDPI support and the progress on converting icons to SVG.
ping @djrm

**Comment by djrm** [comment]
I've made the svg version which is flat looking, and it still looks ugly, since 3d transforms seems to be scalling the icon, it is unable to keep its original resolution, maybe using a 64x64 or even higher res

**Comment by nunodonato** [comment]
given that the light is a "point" really, shouldn't it keep always the same size, regardless of the zoom?

**Comment by djrm** [comment]
I think you are right, i was a victim of an optical illusion, so maybe just a higher res version of the icon will solve this

**Comment by neikeq** [comment]
In terms of size you should check this bug: #2792
But from the icons side, doing a high res version would be enough.
