### ISSUE TITLE
2D Sprites in 3D Environment

### ISSUE THREAD

**Issue by Puebeck** [godotengine/godot#16387]
I could really use a 2D Sprite option in a 3D environment. Making Flat 3D elements does not always work and require a tedious amount of work to get working.

Some potential features of such a 2D Sprite:
 - Thickness [double] (as it is 2D, it should require some form of thickness)
 - camera tracking [bool] (whether the object should always face the camera.)

That's it mostly, I want to make an isometric map with height (Z) values using a grid map and would like the objects (that aren't the ground) to be 2D.

EDIT: Forgot to specify that I would like to have a 2D Sprite as part of the Grid Map. That's what this post was actually about.

**Comment by ZX-WT** [comment]
Doesn't Sprite3D fit you need?

**Comment by Puebeck** [comment]
yes and no, what I really wanted is to have the Sprite as part of the grid map. But it seems I forgot to add that little detail in my initial post :|

**Comment by eon-s** [comment]
You mean a quad with the sprite image as texture then?

**Comment by toby3d** [comment]
Agree. I make character cut-out animated character and get some problems with camera perspective and shadows. :c

**Comment by Omicron666** [comment]
Have you checked if ![2D in 3D](https://i.imgur.com/T7bsILr.png) would fit your needs ?

**Comment by Calinou** [comment]
Closing, as this can be achieved using a MeshInstance with a PlaneMesh attached (and custom SpatialMaterial with a Billboard mode set).

Also, Sprite3D now features a built-in billboard property which was implemented in #30635.
