### ISSUE TITLE
Make the lightmap render result affected by the WorldEnvironment.

### ISSUE THREAD

**Issue by leiget** [godotengine/godot#16398]
I suggest the environment map should affect the result of the Lightmapper.

**Godot version:**
ea99b90

**OS/device including version:**
Doesn't matter.

**Issue description:**
The WorldEnvironment doesn't affect the render result of the BakedLightmap.
![envaffect](https://user-images.githubusercontent.com/20325471/35781599-cd08833e-09b1-11e8-9749-5cc0925ed49b.png)

**Comment by aaronfranke** [comment]
Has the lightmapper been remade in 3.2? I thought rendering changes will be done for 4.0?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
This is still the case in 3.2.3 – the lightmapper doesn't take the environment light into account. It will be fixed by https://github.com/godotengine/godot/pull/40035 once it's merged.

**Comment by JFonS** [comment]
Closing as fixed by #44628
