### ISSUE TITLE
KinematicBody test_move() function not working with Bullet

### ISSUE THREAD

**Issue by sanki83** [godotengine/godot#16393]
**Godot version:**

Godot_v3.0-stable_x11.64

**OS/device including version:**

Linux Mint

**Issue description:**

KinematicBody test_move function always returns false
KinematicBody2D test_move works fine.

here is a code that I've tried to make it go down

    if not activePiece.test_move(activePiece.transform,Vector3(0,-1,0)):
        activePiece.global_translate(Vector3(0,-1,0))

doesn't matter if I use transform or global_transform.

**Steps to reproduce:**
see attached project

**Minimal reproduction project:**

[kinematicbody_bug.zip](https://github.com/godotengine/godot/files/1693001/kinematicbody_bug.zip)

**Comment by eon-s** [comment]
`test_move` works with Godot physics, is a Bullet bug.

**Comment by sanki83** [comment]
Indeed it does.
But there is another thing with it, even with godot physics it doesn't seem to work properly, when a collision shape is a plane, had to switch it to box to start working

**Comment by eon-s** [comment]
Planes are kind of buggy (also lines on 2D), but I have not tested planes with bullet on bodies.

**Comment by akien-mga** [comment]
CC @AndreaCatania as it's Bullet-specific.

**Comment by AndreaCatania** [comment]
@eon-s are you using the plane shape? Since in this case this shape is not mean to walking on and doesn't works properly with kinematic body.

I should look better on this problem, anyway i'm sure that it'll works if you change the shape type.

**Comment by eon-s** [comment]
@AndreaCatania No, I have just mentioned Plane does not work as solid with any physics engine, test move on other shapes fail on bullet only.

**Comment by AndreaCatania** [comment]
Fixed #16681
