### ISSUE TITLE
Sleeping RigidBody in Bullet does not wake up by sleeping=false (and other stories)

### ISSUE THREAD

**Issue by lmjk** [godotengine/godot#16396]
**Godot version:**
3.0

**OS/device including version:**
Fedora 27 x86_64

**Issue description:**
Once upon a time... If you have a RigidBody resting on a StaticBody and you apply a new translation to it (ie. "teleport" it in the air), it will stay still in the new position if it is sleeping. You may want to wake it up when you apply the new translation, but there are two problems (+ one frame-flashing kind):

* RigidBody does not wake up if you set `sleeping=false`.
* RigidBody does wake up by `can_sleep=false` and successive `can_sleep=true`, but then it will never sleep anymore.

Is this correct usage/behaviour or have I misunderstood something? Or if you think there are more than one issue, I can file issues for each if needed.

**Steps to reproduce:**
Run the test project and do the following:

a) Wait until the cube is sleeping. Press T to restore its initial translation. The cube is shown repositioned as expected, hovering. Then press R to set `sleeping=false`. _The cube is first shown in its previous translation, flashed in one frame_, and then back in the initial translation, _but it is still sleeping_.

b) Wait until the cube is sleeping. Press T. Then press E to set `can_sleep=false` and immediately back to `can_sleep=true`. This time the cube falls from the restored translation as it should. However, the previous state is flashed again and _the cube will never sleep anymore_ regardless of can_sleep being true.

As a workaround RigidBody can be awakened by a negligible impulse (press I or J), or incrementing linear velocity by an equally small amount, before applying the new translation.

**Minimal reproduction project:**
[BulletRigidBodySleep.zip](https://github.com/godotengine/godot/files/1693061/BulletRigidBodySleep.zip)

**Comment by nadnam** [comment]
Can confirm this issue on VehicleBody, I have been using apply_impulse() as a workaround too.
