### ISSUE TITLE
Mac OS Godot 3 stable crashes on edit project.

### ISSUE THREAD

**Issue by dunyakilavuz** [godotengine/godot#16390]
**Godot version:**
Godot 3 stable Mac OS x64

**OS/device including version:**
Mac OS High Sierra 10.13.3

**Issue description:**
The project is editable/runnable on Windows 10, however the same project crashes Godot when I try to edit it, still runnable on OSX as well. 

Note: Older versions of the project did not crash the editor.
Thanks for your attention!

**Console Output**
When i try to edit the project i get the following console output.
```
Dunyas-MacBook-Pro:~ dunyakilavuz$ /Users/dunyakilavuz/Desktop/Godot\ 3.app/Contents/MacOS/Godot ; exit;
arguments
0: /Users/dunyakilavuz/Desktop/Godot 3.app/Contents/MacOS/Godot
Current path: /Users/dunyakilavuz/Desktop/Godot 3.app/Contents/Resources
OpenGL ES 3.0 Renderer: AMD Radeon Pro 555 OpenGL Engine
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
Mono: Initializing module...
Mono: Runtime initialized
Mono: INITIALIZED
OPENING: /Users/dunyakilavuz/Desktop/SolarX-Godot (::Users::dunyakilavuz::Desktop::SolarX-Godot)
arguments
0: /Users/dunyakilavuz/Desktop/Godot 3.app/Contents/MacOS/Godot
1: --path
2: /Users/dunyakilavuz/Desktop/SolarX-Godot
3: --editor
Current path: /Users/dunyakilavuz/Desktop/Godot 3.app/Contents/Resources
Mono: Runtime cleanup...
debugger-agent: Unable to listen on 46
OpenGL ES 3.0 Renderer: AMD Radeon Pro 555 OpenGL Engine
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...39 completed.

[Process completed]
```

**Comment by werty37** [comment]
I would like to second this. I am using High Sierra and Godot seems to be very slow and stuck when trying to open projects. 

<img width="1136" alt="screen shot 2018-02-05 at 2 23 00 am" src="https://user-images.githubusercontent.com/22869624/35782301-eb4aee62-0a1b-11e8-859f-f74c6870707f.png">

**Comment by vkbsb** [comment]
you should probably look at the project settings for the project you are trying to open. That might provide hints at why this might be crashing.

**Comment by dunyakilavuz** [comment]
After a few trial and error session i found a workaround for this issue. Deleting the `.mono`  folder under the project folder, then re-opening the project makes Godot re-create the assemblies and editor does not crash anymore.

**Comment by akien-mga** [comment]
Yeah that's a known problem with the Mono version, it's tracked in various other issues already, so closing.

@werty37 That's unrelated, and it's hanging because you're scanning your whole home directory (potentially with tons of subfolders for the settings of all your applications and all your personal data), so it takes a long time. Instead, scan the folder where you actually put your Godot projects, if any.
