### ISSUE TITLE
Timeline track title overlapping keyframe area.

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#16406]
**Godot version:**

3.0

**OS/device including version:**

**Issue description:**

The tracktitles (when they are too long apparently) overlap the keyframe part of the timeline.
The picture describes it best.

![godottimelinebug](https://user-images.githubusercontent.com/15687516/35798719-eed10eb6-0a63-11e8-846a-249d4dfcb260.png)

**Steps to reproduce:**
Have a long trackname for your animated property and 'contract' the area displaying the track names.

**Minimal reproduction project:**

**Comment by reduz** [comment]
probably when the checkboxes to disable/enable tracks were contributed, the
string clip length wasn't substrcted the size of the checkboxes..

**Comment by akien-mga** [comment]
Fixed by #16410.
