### ISSUE TITLE
Escaped " character breaks bracket highlighting

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16404]
**Godot version:**
ea99b90

**Issue description:**
Self-explanatory:
![screenshot1](https://user-images.githubusercontent.com/30739239/35783627-93d6fc4a-09f1-11e8-878a-83e866c8a03d.png)

**Comment by akien-mga** [comment]
Fixed by #16404.

**Comment by HummusSamurai** [comment]
@akien-mga  

* https://github.com/godotengine/godot/pull/16652
