### ISSUE TITLE
2D Particle Emission Mask is offset

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#16411]
**Godot version:**

3.0
**OS/device including version:**

**Issue description:**

When I load an Emission Mask for a 2DParticle system the result is offset since the mask is placed from the top left corner and not the center.
In the screenshots below the Emission Mask has been generated from the same image used for the Well sprite.
The offset might be the intended behavior or a limitation of the way the particle system works now I don't know. Placement from the center would seem to be the expected behavior however.

The first image shows the center of the Well sprite.
The second image shows the center of the 2DParticle system. 

![godotparticlemaskbug2](https://user-images.githubusercontent.com/15687516/35805238-56cb3f98-0a7b-11e8-9d7d-6fb580be97af.png)

![godotparticlemaskbug1](https://user-images.githubusercontent.com/15687516/35805243-5c48dc46-0a7b-11e8-91ad-9acda19418c4.png)

**Steps to reproduce:**
Place a 2D Sprite and a 2DParticle system at 0,0. Add an image to the sprite and load the same image as an Emission Mask in the 2DParticle system.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
It's actually the Sprite which is offset, as you've enabled the "Centered" option. I guess Particles2D doesn't have it, like most other 2D nodes.

**Comment by PullTheStrings** [comment]
Particles2D emit from the center of its node. The new Emission Mask options are great, it's just somewhat of an annoyance that the Emission Mask created from an image is anchored in the top left corner and not the center. Anchored in the center was the way Emission Masks behaved in Godot 2. So I advocate for the option to choose anchoring the Emission Mask in the center.

**Comment by QbieShay** [comment]
This should be fixed by adding an option "centered" on the generation side.
Pushing to 4.1 since it's not a critical bug and can be worked around.
