### ISSUE TITLE
RayCast enhancement - ability to identify intersecting triangle in trimesh

### ISSUE THREAD

**Issue by nadnam** [godotengine/godot#16412]
**Godot version:**
3.0

**Issue description:**
It would be very useful to have ability to identify triangle of trimesh (concave shape) that is being intersected by RayCast. This way index of triangle (or surface id of ArrayMesh that trimesh is created from) can be used when RayCasting big concave shapes.

It happens a lot in games (eg. raycasting bullet hit against character to determine exact location). 

Reason for this request is performance. Instead of one trimesh shape that stores all surfaces from ArrayMesh, one must create Area/StaticBody for each surface and store single trimesh there to be able to differentiate what was intersected.

Due to bug https://github.com/godotengine/godot/issues/16541 , those Areas or StaticBodies generate collision pairs even when their collision layers/masks should prevent any kind of collision tests, killing performance in the process. Further more, there is performance hit even when performance monitor reports no collision pair were generated, I suspect there is lot going in the background unreported, eating CPU (test confirm for GodotPhysics, Bullet is not tested so far).

**Comment by nadnam** [comment]
Update: raycasting ArrayMesh itself (assigned to MeshInstance) seems to be quick enough using GDScript.

Process involves accessing ArrayMesh surface vertices and going trough them using Geometry.ray_intersects_triangle(). Basical setup is to have eg. capsule shape encapsulating character. When raycast intersect capsule, all mesh instances of characters within it are raycasted in search for intersecting points. This approach has additional advantage - all intersection points can be detected (and sorted by distance) instead of only closest one returned by built in RayCast.

**Comment by Calinou** [comment]
Closing, as there seems to be a good enough solution according to the above comment.

**Comment by Giwayume** [comment]
"But Google, I just want code"

```gdscript
extends Reference
class_name MeshRayCast

# mesh_instance - MeshInstance node that contains the mesh you want to raycast with
# global_ray_from - Starting position of the raycast in world coordinates
# global_ray_to - Ending position of the raycast in world coordinates
static func intersect_ray(mesh_instance: MeshInstance, global_ray_from: Vector3, global_ray_to: Vector3):
	var direction: Vector3 = global_ray_to - global_ray_from
	var mesh: Mesh = mesh_instance.mesh
	var intersections: Array = []
	for surface_index in mesh.get_surface_count():
		var surface_arrays = mesh.surface_get_arrays(surface_index)
		var vertex_array = mesh_instance.get_global_transform().xform(surface_arrays[Mesh.ARRAY_VERTEX])
		var vertex_array_length = len(vertex_array)
		var face_array = surface_arrays[Mesh.ARRAY_INDEX]
		var face_array_length = len(face_array)
		for face_index in range(0, face_array_length, 3):
			var intersection = Geometry.ray_intersects_triangle(
				global_ray_from,
				direction,
				vertex_array[face_array[face_index + 2]],
				vertex_array[face_array[face_index + 1]],
				vertex_array[face_array[face_index + 0]]
			)
			if intersection != null:
				intersections.push_back(
					intersection
				)
	var closest = null
	var closest_distance = INF
	if len(intersections) > 0:
		closest = intersections[0]
		closest_distance = global_ray_from.distance_to(intersections[0])
		for intersection_index in range(1, len(intersections)):
			var distance = global_ray_from.distance_to(intersections[intersection_index])
			if distance < closest_distance:
				closest_distance = distance
				closest = intersections[intersection_index]
	return {
		"intersections": intersections,
		"closest": closest,
		"closest_distance": closest_distance
	}
```

The above function will return something a dictionary that looks like this whentriangle intersections are **NOT** found:

```
{
	"intersections": [],
	"closest": null,
	"closest_distance": INF
}
```

And something like this when intersections are found. These Vector3 are positions in world coordinate space.

```
{
	"intersections": [
		Vector3(3, 5, 2),
		Vector3(5, 10, 20),
		Vector3(4, 6, 3)
	],
	"closest": Vector3(5, 10, 20),
	"closest_distance": 10
}
```
