### ISSUE TITLE
Editor game vs Exported game

### ISSUE THREAD

**Issue by CCODE05B** [godotengine/godot#16413]
**Godot version:**
Godot 3 Stable x64

**OS/device including version:**
Windows 7 x64 bit
GTX 980
i7 4970K
8 GB Ram

**Issue description:**
i have 3 Problems with Godot

Edit : 2 and 3 are my faults .. sorry 

1- Godot was freezing Each second and there is a lot of Jittering and dropping fps when playing from the Editor , but when Exporting the game.. it run Completely Smooth without any problem .. why this Happen ?

here a simple video shows the lag and freezing

https://www.youtube.com/watch?v=hhAHV6CQgag

2- When Exporting my Game and Disable Debug .. it Crash and don't Start , but if i Enable Debug , it work really really GREAT without any Single problem 
i tried to Export other example and they work fine with Disabled Debug , but my Game for some reason don't , and there is no Error in the Debugger when i play in the Editor

3- Loading an Image in Exported game not working

like : 

```
	var MyImage= ImageTexture.new();
	MyImage.load("res://Textures/Test.jpg");
```

this work fine in the Editor , but when Export the Game it does not work

**Comment by Zireael07** [comment]
3) won't work in exported projects as there is no "res://" to load from anymore.

**Comment by vnen** [comment]
> won't work in exported projects as there is no "res://" to load from anymore.

This is not true, `res: //` still exists since the package exposes a file system (you can't write to it though).

The issue here is that the `.jpg` file is not there anymore because it went to the `.import` folder. In this case you need to import the texture directly with `var my_img = load("res://Textures/Test.jpg")`.

For 1, it's the same as #13219.

For 2, look at the console / output when playing in debug and see if there's errors there. Some errors in debug might become a crash in release.

**Comment by CCODE05B** [comment]
@Zireael07 it did not work
@vnen It's Working now !!!
about error messages in Console .. there is one Error : 

`ERROR: Spatial::get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform() At: scene\3d\spatial.cpp:266`

is this the problem ?

**Comment by vnen** [comment]
This error means you are trying to get the transform of a node that's not on the tree. This might be a problem in release.

**Comment by 11clock** [comment]
I experience #1 as well and have been struggling to fix it for weeks now, but glad it is not an issue for exported projects.

**Comment by CCODE05B** [comment]
@11clock you can Fix it by simple steps :D 
Go to Editor settings -> Scroll down until you find "Debugger" -> Turn off "Auto switch To Remote scene tree"
it's a temporary solution until they fix it but it will stop this problem :heart:

**Comment by akien-mga** [comment]
Closing, as 1. is already tracked in #13219, 2. is a project-specific script error and 3. works as explained above.
