### ISSUE TITLE
Update the bundled google play services package

### ISSUE THREAD

**Issue by teamblubee** [godotengine/godot#1642]
Can you update the google play services package.
If you have the android SDK update that to the latest version then copy
ANDROID_SDK_FOLDER/extras/google/google_play_services

that folder and overwrite the one in
GODOT_SRC/platform/android/libs/google_play_services

**Comment by reduz** [comment]
will try.. let me fix some issues first...

also by the way, I'm not very experienced with this, but right now i'm just using the reference to the project.. is it possible to obtain the same stuff using jars? some libs work that way and it seems easier to distribute

**Comment by teamblubee** [comment]
Google moved to the reference project model so that they can auto update play services so that devs can w/o developers having to deal with republishing their apps.

update the android sdk and then grab the latest google play services commit it and that should be all.

**Comment by reduz** [comment]
oh alright. I will try to do this tonight, plus will see if i can get
JavaClassWrapper working better.. hope you can test it

**Comment by teamblubee** [comment]
Hey Reduz

How's this going?
If you replace the google game play services just make sure that the build.properties in the new google play services target is set to 15, after that everything should work just fine.

**Comment by reduz** [comment]
I tried, but let me know when you are around on irc, i'm kind of scared of screwing it up so I want to ask you some questions

**Comment by volzhs** [comment]
+1

**Comment by akien-mga** [comment]
This hasn't been done yet AFAIK?

**Comment by volzhs** [comment]
For android template, godot is now using gradle, and we can define which version of google play service when make android template.
So it's not an issue anymore in my opinion.

**Comment by vnen** [comment]
It seems this is a non-issue anymore.
