### ISSUE TITLE
Can't create builtin script if file exists

### ISSUE THREAD

**Issue by Psykopear** [godotengine/godot#16425]
**Godot version:**
3.0

**OS/device including version:**
Arch Linux

**Issue description:**

I should be able to set a script as builtin even if there is a script with the name specified in the 'path' field of the `Attach node script` form. 

**Steps to reproduce:**
1) Create new project
2) Add Node2D to the scene
3) Create new script file for Node2D
4) Save the scene
5) Clear the script for the node (using the button in the image)
![img-2018-02-05-184526](https://user-images.githubusercontent.com/5968682/35820125-088ef2be-0aa5-11e8-9994-45dc0935f3cb.png)
6) Open the form to create a new script file
7) Try to set the script to builtin mode - Doesn't work
![img-2018-02-05-185500](https://user-images.githubusercontent.com/5968682/35820568-42218888-0aa6-11e8-9291-578e4fda5f74.png)

**Minimal reproduction project:**
Follow steps 5 6 and 7 in this project
[testBug.zip](https://github.com/godotengine/godot/files/1696200/testBug.zip)

**Comment by alex9099** [comment]
It seems to be because there is a file with that name, if you change the filename you can click on built in

**Comment by KidRigger** [comment]
I want to take this.
As @alex9099 said, I think the script deletion is something that should be added (I'll work on that. Meanwhile, what should be the case on the setting built-in for existing scripts? Disallow with popup or allow freely?)

**Comment by bojidar-bg** [comment]
Given that toggling Built-in Script to "On" disables the path field, I would say we should allow them, and it shouldn't possible to convert an existing script to builtin.

![image](https://user-images.githubusercontent.com/5276727/36376312-53cd2b0c-157b-11e8-9f46-220bcf2969f0.png)

**Comment by KidRigger** [comment]
Alright. So I'll simply allow the creation of builtin script. I guess the script detach should be a separate feature request.
