### ISSUE TITLE
Incorrect/vague property in documentation on Viewports

### ISSUE THREAD

**Issue by m-irigoyen** [godotengine/godot#16420]
**Godot version: 3.0**

**Issue description:**
http://docs.godotengine.org/en/3.0/tutorials/viewports/viewports.html#scale-stretching states that "Viewports have a “rect” property." 
Closest thing I can find in the GDScript Help is "Rect2 get_visible_rect() const", is that it ?

**Comment by Noshyaar** [comment]
IIRC it's renamed to `size`.

This is documentation issue. (and it's not the only outdated thing in that page) It should be reported at godot-docs repository: https://github.com/godotengine/godot-docs/issues
