### ISSUE TITLE
Android export with custom boot splash image using same file as the icon

### ISSUE THREAD

**Issue by marionauta** [godotengine/godot#16421]
**Godot version:** 3.0 (from the web)

**OS/device including version:** KDE Neon (based on Ubuntu 16.04), kernel 4.13

**Issue description:**
I wanted to set a custom splash screen for my game in godot 3.0, but then the android export didn't work. Just after it starts signing the release APK, it says:

    'jarsigner' returned with error #1

If the custom boot splash image is unset, the export works.

**Steps to reproduce:**

1. Create project and set custom boot splash image:
     + Project > Project Settings > Boot Splash > Image
2. Create android export template
    + Project > Export > Add... > Android
    + Fill Keystore user and password
3. Click on Export Project.

**Minimal reproduction project:**

[Boot.zip](https://github.com/godotengine/godot/files/1695653/Boot.zip)

The project comes with a `release.keystore` with user `test` and password `pass1234`.

**Comment by malbach** [comment]
Registered to confirm the bug, and also to give some details : 
- can reproduce the bug on my Ubuntu 17.04 64b with the "Boot" project 
- can NOT reproduce it if I duplicate the icon.png ressource and use the new image as splash screen (looks like the bug is activated if the project uses the same image for icon and splash)
- can NOT reproduce it on Windows 7 SP1 64

**Comment by akien-mga** [comment]
> can NOT reproduce it if I duplicate the icon.png ressource and use the new image as splash screen (looks like the bug is activated if the project uses the same image for icon and splash)

Indeed, the problem is:
```
  signing: assets/.import/icon.png-487276ed1e3a0c39cad0279d744ee560.stex
  signing: assets/icon.png.import
  signing: assets/icon.png
  signing: assets/icon.png
jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: assets/icon.png
ERROR: _export_project_to_path: Failed to export project
   At: editor/project_export.cpp:748.
```
