### ISSUE TITLE
RTL.bbcode_text += operator doesn't use append_bbcode

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#16439]
should use `append_bbcode`, currently it uses `set_bbcode` internally if doing `+=` operator on `bbcode_text` property.

 (set_bbcode causes massive lag when adding a ton of text over time to the `"bbcode_text"` property)

@willnationsdev is current rtl guru, plz take a look, ty sir.
https://github.com/godotengine/godot/blob/e24f2c6489afdccc6268008d3dcc1ff4ad8ea71c/scene/gui/rich_text_label.cpp#L2044

just to add: possible internal issue with gdscript's `+=` operator, since it's a string appendation.  
might need a special case for `bbcode_text` appending, and have it use `append_bbcode` instead

**Comment by akien-mga** [comment]
I don't think it can be easily solved, it would imply adding support for all properties to set different methods to overload operators.

**Comment by girng** [comment]
@akien-mga i see. maybe in docs prob be good to note that using `append_bbcode` is ideal then. users who are using `bbcode_text += text` might notice slowdown. ( where i found this bug initially )

can close if you want sir, this is prob low priority, just figured i let u you know!

**Comment by akien-mga** [comment]
Well I agree that at least the documentation should be improved.
