### ISSUE TITLE
Can't copy in shader editor

### ISSUE THREAD

**Issue by MangelMaxime** [godotengine/godot#1643]
We can't do `Ctrl+A` then `Ctrl+C` to coype the code from the shader editor (CanvasItemShader).

It's copy nothing so we can't paste the code like that. But if we select the all or portion of the code with the mouse we are able to copy - paste the code.

**Comment by Ace-Dragon** [comment]
What platform are you on?

if you're on Windows, then simply using **Ctrl C > Ctrl V** should work.

**Comment by MangelMaxime** [comment]
You can't get the text by using either of `Ctrl C` or Edit > Copy.

So you can't do `Ctrl V` after as you don't have any content in the copyboard

**Comment by reduz** [comment]
what operating system?

**Comment by MangelMaxime** [comment]
Hum sorry, I was under Windows 7 with the Godot 1.1 Beta1.

**Comment by WatIsDeze** [comment]
The same problem happens in the general script editor as well. Running OsX.

**Comment by reduz** [comment]
can't reproduce on ubuntu..

**Comment by akien-mga** [comment]
I believe this issue might have been fixed already, could you test it in the current master branch or a recent nightly build? If you can still reproduce the bug, please tell me so that I can reopen this issue.
