### ISSUE TITLE
[UX] Icon in project settings should display *.jpg by default

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#16446]
**Godot version: 3**

**Issue description:**
When you open the select icon dialog it only has `*.png` and `*.webp` filters. I tried choosing a `.jpg` file and it seems to work just fine. No error message, I can clearly see it in the project list and as an Icon on the window. Is there any reason why the `*.jpg` filter is not on by default? If it works I think it should be added to the standard options.
![iconpicker](https://user-images.githubusercontent.com/2206700/35859955-763f06b2-0b42-11e8-9205-752fa2d3231e.PNG)

**Comment by volzhs** [comment]
we need to consider this can be possible for all platforms.

**Comment by Calinou** [comment]
I'm not sure if we should support JPEG icons. It has lossy compression and doesn't support transparency, making it not very useful for application icons in general.

**Comment by coppolaemilio** [comment]
I agree that they should not be supported, but the file dialog is allowing you to select them, so that should be disabled at least.

**Comment by Calinou** [comment]
Closing, as I don't see a strong reason to *prevent* using JPEG icons entirely – it's just not a recommended option.
