### ISSUE TITLE
[MacOS] Editor crashes on launch, mscorlib.dll missing

### ISSUE THREAD

**Issue by TomWor** [godotengine/godot#16443]
**Godot version:**
3.0

**OS/device including version:**
MacOS Sierra / 10.12.6

**Issue description:**
Editor crashes on launch.

I've installed Mono 5.8 but when I launch the Godot executable, it keeps looking for mscorlib.dll in the 5.4.1 folder (which doesn't exist)
```
Mono: Initializing module...
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/4.5/mscorlib.dll' directory.
```
When I run the --version flag on the command line, I get the correct mono version (which has mscorlib.dll) - but Godot seems unable to find it.
```
➜  Versions mono --version
Mono JIT compiler version 5.8.0.108 (2017-10/9aa78573ee2 Wed Jan 10 04:30:03 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```

**Comment by TomWor** [comment]
#16304

**Comment by bruvzg** [comment]
This is know issue - #13355, you can force mono path by setting `MONO_PATH` environment variable to `/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/`, or rebuild Godot from source with newer Mono version.

**Comment by TomWor** [comment]
Ok, the Mono issue seems to be fixed this way, I can see the project manager, but selecting a project I get this now:

```
Stacktrace:


Native stacktrace:

Mono: Runtime cleanup...

[Process completed]
```

Probably unrelated so I'm closing this for now.
