### ISSUE TITLE
Reflection Probe Capture Clips Scene

### ISSUE THREAD

**Issue by Cygon** [godotengine/godot#16441]
**Godot version:** 3.0-stable, custom build from 9bd402698cfa299b79b9144f8d7744c308a4e085
**OS/device including version:** Gentoo Linux 4.9.72, KDE Plasma 5.10.5
**GPU model and drivers:** NVidia GTX 1080 w/proprietary drivers 387.22

**Issue description:**
When setting up a reflection probe, a volume needs to be defined in which the reflection probe will influence lighting. Unlike other engines, Godot clips the captured scene to this volume.

This means that reflection probes will not accurately represent their lighting environment. If there was, for example, a bright white wall just outside the reflection volume, objects affected by the reflection probe will not be lit accordingly.

Also due to this clipping, the reflection will show the scene's background/sky:
![Polished Sphere Reflects the Invisible Sky](https://user-images.githubusercontent.com/3613175/35849658-a9b96b6a-0b22-11e8-872e-b8ea5cc720bf.jpg)

This results in meshes (even if the reflection probe's `Interior` mode is used) getting a blue tint, despite no chance of the sky being visible from their location:
![Blue Tint on Metals in Orange Room](https://user-images.githubusercontent.com/3613175/35849714-d1e21100-0b22-11e8-8659-e08f6243391e.jpg)

I suggest giving the reflection probe a `Near Clip Plane` and `Far Clip Plane` (just like a camera) and using the volume only to calculate a reflection probe's contribution to object lighting/reflections. If backwards compatibility is an issue, a new option `Clip Reflection Capture` or such could be added.

**Other Engines:** Unreal Engine's reflection probes capture use an influence radius and the far clip plane is a multiple of the influence radius while Unity's reflection probes have a near + far clipping distance:
![Unity Reflection Probe Settings](https://user-images.githubusercontent.com/3613175/35850552-89280098-0b25-11e8-850c-7a0da7907ded.png)

**Steps to reproduce:**
1. Create a closed room with an omni light (preferably of a different color than the sky)
2. Place a reflection probe inside the room
3. Place a metallic, reflecting object inside the room and inspect its reflections/tint

**Comment by reduz** [comment]
you have a max distance property you can use (set >0) if you want to override the box extents.

**Comment by Cygon** [comment]
@reduz Outch. You're right, I completely overlooked that property and it does indeed fix my reflection issues.

Sorry for wasting everyone's time, issue can be closed!
