### ISSUE TITLE
2D particles set to blend mode Add are not blending correctly

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#16442]
**Godot version:**

3.0

**OS/device including version:**

**Issue description:**

2D particles with blend mode set to Add are not blending to white but instead to a brighter color of the particle color. Blending to white was the previous behavior in Godot 2.

In the screenshots the same particle system has been set up in Godot 2 and Godot 3. Each with 20 particles and a lifetime of 2, emitting on top of each other. The particles in Godot 2 blend to white, the particles in Godot 3 blend to a brighter color of blue.

![godotaddright](https://user-images.githubusercontent.com/15687516/35851803-678e6784-0b29-11e8-9602-2fbce6846791.png)

![godotaddwrong](https://user-images.githubusercontent.com/15687516/35851811-6a35e688-0b29-11e8-98bd-eecf01723835.png)

 
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by reduz** [comment]
I don't have the slightest clue about why this might be going on. Maybe related to HDR being disabled by default in Godot 2? Other than that it should be exactly the same..

**Comment by reduz** [comment]
After checking and checking again, my guess is that this is numerical precision related given the framebuffer depth being different (Godot2 having less), as the blend-add ecuation is exactly the same and there is not any kind of extra complexity here.. will close unless someone can bring more information and better reproduction examples that go against this.
