### ISSUE TITLE
Pan using middle Mouse Button Click on Mac not working

### ISSUE THREAD

**Issue by kemojal** [godotengine/godot#16449]
**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by kemojal** [comment]
For Godot 2.X, Panning in a Spatial World you just need click on the middle mouse scroll wheel and drag to the desired position. For Godot 3.0 on Windows same way works perfectly fine. However, on Mac Clicking  the middle button and dragging doesn't work.

**Comment by poke1024** [comment]
Works for me on 3d and 2d views (if zoomed in) using latest 900384a622c7f3094540a43670421469e4ee0b06 (using OS X 10.13.3):

![drag](https://user-images.githubusercontent.com/11859538/37109771-40ec7930-223b-11e8-8e9f-fd182f3844c7.gif)

Are you sure you were zoomed in a bit? If you're at the outer zoom level (full default view), Godot 3 has a new (debatable) feature that limits/nulls any movement (I'm actually not a fan of that BTW).

**Comment by kemojal** [comment]
It's working fine, Some how "Modo" was selected as the editor navigation scheme. I changed the navigation to "Godot" and problem solved.
