### ISSUE TITLE
[Godot Rigidbody2D collision error ] two bodies collide without touching each other

### ISSUE THREAD

**Issue by kemojal** [godotengine/godot#16447]
**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
The issue template is there for a reason, please fill it in.

**Comment by Noshyaar** [comment]
**Solution:**

**Comment by akien-mga** [comment]
Can't do anything without more info. Please open a new issue with details as required in the template if still relevant.
