### ISSUE TITLE
CanvasItem.draw_multiline width and antialiasing not functional

### ISSUE THREAD

**Issue by Freakmiko** [godotengine/godot#16448]
**Godot version:**
v3.0-stable_win64

**OS/device including version:**
Windows 10 Pro x64

**Issue description:**
When drawing multiple lines with the CanvasItems draw_mutliline(), the `width` is not taken into account. All lines have a `width` of 1 even though a `width` > 1 was given as a parameter. The same holds true for antialiasing.

**Steps to reproduce:**
1. Create a Node2D
2. Attach script to node that attempts to draw lines with draw_multiline() and a `width` > 1.0 and `antialiasing` set to true.

**Minimal reproduction project:**
[Multiline.zip](https://github.com/godotengine/godot/files/1699193/Multiline.zip)

**Comment by Noshyaar** [comment]
Here's the method where the arguments passed are ignored.
https://github.com/godotengine/godot/blob/b0a73077cb8395ad39124dd08490195adbfb90c9/servers/visual/visual_server_canvas.cpp#L491

**Comment by akien-mga** [comment]
This seems to be unimplemented indeed, it was likely never finished. The code reference in https://github.com/godotengine/godot/issues/16448#issuecomment-363644102 is still a good starting point, as well as `rasterizer_canvas_gles3.cpp` (search for `multiline`), where it's apparent that there is missing code.

**Comment by KoBeWi** [comment]
Still valid in 6bd4074

**Comment by rionhunter** [comment]
Still a problem in v3.2.3 in GLES3 it seems

**Comment by Zylann** [comment]
Similar to #8289?

**Comment by Calinou** [comment]
> Similar to #8289?

The issue here happens because the width and antialiasing properties are not implemented for `draw_multiline`, not because of a hardware limitation.

**Comment by Zylann** [comment]
Ok so once we fix these causes, we may be able to close this issue even if we still see it rendering at 1px due to the first issue

**Comment by rontarrant** [comment]
Still not working in 3.4.4

**Comment by Calinou** [comment]
I made an add-on for antialiased 2D line drawing, although you'll need to use multiple nodes to replicate the behavior of `draw_multiline()`: https://github.com/godot-extended-libraries/godot-antialiased-line2d

**Comment by YuriSizov** [comment]
So as far as I understand, width works now, but antialiasing still doesn't?

**Comment by dalexeev** [comment]
> So as far as I understand, width works now, but antialiasing still doesn't?

Yes, see this comments: [one](https://github.com/godotengine/godot/pull/69851#discussion_r1070381781), [two](https://github.com/godotengine/godot/pull/71679#issue-1549376986).

**Comment by YuriSizov** [comment]
Ah, it was removed. I missed that. Then I guess a proposal is needed if we want to actually bring it back in a working state, one that explains how it should work.
