### ISSUE TITLE
Highlight selected animation in animation list

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#16444]
**Godot version:**

3.0
**OS/device including version:**

**Issue description:**

This is just a suggestion. When you start (keyframe) an animation from within another animation, it would be nice if your selection was highlighted in the dropdown list. The name field that shows your selection afterwards is also very small. As you can see from my screenshot I have two animations with very similar names and I cannot see which one that I have selected.

![godotanimationkeyframing](https://user-images.githubusercontent.com/15687516/35856356-1134b39a-0b36-11e8-8610-403e577142cd.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by girng** [comment]
voted yes

**Comment by volzhs** [comment]
an easy way to solve this is by modifying `Tree.cpp`
but it will break backward compatibility and @reduz will rewrite property editor in 3.1 AFAIK.
so, I will wait for his work.

**Comment by KoBeWi** [comment]
Fixed in 3.1
![image](https://user-images.githubusercontent.com/2223172/57021773-7bed7b00-6c2d-11e9-8e1d-ead65a903cf4.png)
