### ISSUE TITLE
Ability to disconnect client via multiplayer API

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#16452]
When designing a multiplayer game a server disconnecting clients for banning/kicking/server switching reasons is important.
AFAIK: In the multiplayer API there is no way to disconnect a single specified client from a server.
(Obviously this command should only work on the server hosting the game)

An RPC is unreliable as the surver can only ASK the client to carry out it's request, modified clients could easily ignore this.
Even if you deleted everything they controlled they would still be hogging a player slot.

**Comment by avril-gh** [comment]
i agree, disconecting client on will is important option.

**Comment by Neicul** [comment]
Is networking not UDP based? So we don't really have connections, right?
Shouldn't it then not be as simple as just ignoring whatever that client sends us?

**Comment by Zephilinox** [comment]
Enet already supports this, just needs to be added to godot. http://enet.bespin.org/group__peer.html

**Comment by raymoo** [comment]
@Neicul The high level multiplayer API uses Enet, which will keep the connection alive until you tell it not to.

**Comment by akien-mga** [comment]
CC @Faless

**Comment by mhilbrunner** [comment]
Working on this, not sure if I should wait for https://github.com/godotengine/godot/pull/17227 to be merged first though?

**Comment by vspin** [comment]
> Even if you deleted everything they controlled they would still be hogging a player slot.

Exactly. So, if you set your maximum connections at 50, a malicious client could fill all those connections, and no valid user could even join.

**Comment by mhilbrunner** [comment]
>Exactly. So, if you set your maximum connections at 50, a malicious client could fill all those connections, and no valid user could even join.

Thats a problem for every server and you usually solve that at the networking level. (See DDoS protection.)
