### ISSUE TITLE
animating rigidbody in kinematic mode don't return linear velocity

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#16451]
**Godot version:**

Godot 3.0 Stable

**OS/device including version:**

Windows 7

**Issue description:**

In Godot 2.1.4, if I move a rigidbody in kinematic mode by animationplayer,
I can query its linear velocity in GDScript by calling get_linear_velocity

But now in Godot 3, I get zero vector by calling getting its linear_velocity

**Steps to reproduce:**
1. create a rigidbody in kinematic mode
2. create a animation player
3. animate the rigidbody to move from one point to another point
4. get the linear velocity of rigidbody by getting its linear_velocity in GDScript
5. the resulting velocity is always zero vector

**Comment by AndreaCatania** [comment]
I was missing a really useful feature, thanks you for the report: #22257
