### ISSUE TITLE
Changing name of resource

### ISSUE THREAD

**Issue by honix** [godotengine/godot#1645]
Trying to change resource name, but it updates only on reopening scene. I think better to update it instantly.

![default](https://cloud.githubusercontent.com/assets/11596541/7030930/d8b32286-dd70-11e4-93b8-dd5e910e3e75.PNG)

**Comment by Ace-Dragon** [comment]
I think it updates instantly if you save it manually via the use of the little save icon and give it a name there.

But yes, perhaps having it update instantly there would be nice.

**Comment by reduz** [comment]
this screen will probably change in 1.2 (resources dock will most likely be replaced by a history dock)

**Comment by honix** [comment]
Wow, history/undo-redo dock like in photoshop? I thing in 1.2 will be cool to be a tab like in browsers, so user can choose scene to work. In 1.1 no too fast to open and change scene. 

Another problem with resources i have. Build-ins resources sometimes reset they name to default when i reorder my tree. That begin visible only after saving and reload scene.

So, i just save my scripts in folder and problem gone..

**Comment by reduz** [comment]
yes 1.2 will have scene tabs on top

**Comment by akien-mga** [comment]
The resource dock has been removed for 2.0, so this issue is not relevant anymore.

> (resources dock will most likely be replaced by a history dock)

@reduz Is it still on the roadmap? That sounds like a very nice feature! (and I miss a 4th dock now that we have easily customisable dockable panels :D)
