### ISSUE TITLE
Input bug in release version

### ISSUE THREAD

**Issue by GearStarter** [godotengine/godot#16465]
**Godot version:** 3.0.stable.official and 3.0.stable template 

**OS/device including version:** MS Windows 10 and Linux Ubuntu 16.04 Gnome

**Issue description:** Input bug in release version

**Steps to reproduce:**
I use last version Godot Engine. I don't know why my project of release version is not working.
I created simple project and I found breaking node. It's input node.

Editor: First screenshot
![editor](https://user-images.githubusercontent.com/30772977/35914575-257920e2-0c1d-11e8-9ac3-50ba81f831b8.png)

Release version: Second sceenshot
![release](https://user-images.githubusercontent.com/30772977/35914580-2cb881f4-0c1d-11e8-843c-46941c893fcc.png)

Release version is not working: print to screnn Null, instead true/false.

**Minimal reproduction project:** Link project
[InputBugRelease.zip](https://github.com/godotengine/godot/files/1702882/InputBugRelease.zip)

**Comment by Chaosus** [comment]
Some advices
1. You should use the Action node instead CallSingleton
2. Paste screenshots to Github directly, without radikal, same for zip projects(I could not reproduce this bug myself, and download link is not working - freezed on "Файл загружается")

**Comment by Chaosus** [comment]
Try Action node instead CallSingleton, paste the project archive to Github directly instead of rgho.st

**Comment by GearStarter** [comment]
Sorry. I'm newbie. How do I add a project files and screenshots?

**Comment by Chaosus** [comment]
Simply combine it to zip or 7z archive and drag n drop it to comment field on Github.

**Comment by GearStarter** [comment]
You are right. Action node is working. But I use other call nodes. So my project still is not working. As a result, any call node is not working in release version?

**Comment by Chaosus** [comment]
I think this bug is occur because the node path ../../Label:text in NodeSet looks (for some reason) incorrect to engine in release version(did you mean exported binary ?)
The correct version looks like this..
![image](https://user-images.githubusercontent.com/3036176/35915481-1d52ea42-0c18-11e8-9c38-f064742b5e24.png)

I could miss, but thats my thoughts..

**Comment by GearStarter** [comment]
I fixed it. But it still does not work. I think call nodes does not work in release version.

**Comment by avril-gh** [comment]
> I fixed it. But it still does not work

:laughing:

**Comment by ibrahn** [comment]
I've found the uninitialised variable causing this particular problem. (PR to follow)

However, there's rather heavy use of the preprocessor directives ``DEBUG_ENABLED``, ``DEBUG_METHODS_ENABLED`` and ``TOOLS_ENABLED`` throughout the visual script stuff, that probably needs a once over from someone well acquainted with the system
