### ISSUE TITLE
Tiles not ordered in numeric sequence when editing tilemap

### ISSUE THREAD

**Issue by xBeepx** [godotengine/godot#16469]
**Godot version:**
3.0 stable

**OS/device including version:**
Windows 10 Pro version 1709

**Issue description:**
Tiles in the tileset are not listed in numeric order in the tileset tray when editing tilemaps. Instead of being listed in the order 0, 1, 2, 3, 4 etc they are listed as 0, 9, 99, 100, 101, 102... (image attched to better illustrate what's happening).

This happens whether sprites in the tileset are named numerically or alphabetically.

It's not a critical bug, but it means you have to hunt for tiles that should be near each other!

**Steps to reproduce:**
Add Tilemap node, load tileset resource.

![capture](https://user-images.githubusercontent.com/36228828/35915456-e352d898-0bfe-11e8-8cf9-e77d8fe2a379.PNG)

**Comment by Zylann** [comment]
Is that because they are sorted alphabetically? I don't see a clean way to also make it sort numerically at the same time... Maybe prefix zeros? Or have a sorting option?

**Comment by xBeepx** [comment]
Prefixing the names with zeroes does seem to solve the problem. I assumed they were sorted by their index within the tileset. Thanks!
