### ISSUE TITLE
2DEditor: can't select flipped Sprite by clicking it in the viewport

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#16461]
**Godot/OS version:** b0a7307 | Antergos x86_64

**Issue description:**

Can't select flipped Sprite by clicking on it.
Selecting it by either drawing selection box over it or from the Scene Dock works.

Pinging @groud, master of CanvasItemEditor :D

**Steps to reproduce:**
1. add Sprite
2. set Flip H or Flip V on
3. try to select it by clicking on it

**Minimal reproduction project:**

[Node2D_.tscn.txt](https://github.com/godotengine/godot/files/1701673/Node2D_.tscn.txt)

**Comment by kaliga** [comment]
The same thing happens when using AtlasTextures in sprites (#16261)
