### ISSUE TITLE
Getting colliding Tile does not work

### ISSUE THREAD

**Issue by mayuso** [godotengine/godot#16468]
**Godot version:**
3.0 Stable

**OS/device including version:**
Windows 10 64 Bits

**Issue description:**

    extends RigidBody2D

    func _process(delta):
        var tile = get_parent().get_node("TileMap").get_cellv(get_parent().get_node("TileMap").world_to_map(position))
	    print(tile)

Runing this code always makes tile be `-1`. This RigidBody2D is the player, and I can see it collide with diferent types of Tiles, but it doesn't return the ID of each tile, it always returns `-1`. No erros, no exceptions, always `-1`.

**Comment by Zylann** [comment]
That code will return a tile only if there is one underneath the center of your character. To get the colliding tile, you need to use the collision contact point.

**Comment by mayuso** [comment]
AFAIK there is no way to get the collision point in RigidBody2D, right? Only in KinematicBody2D. 

That's the information I've found while searching these past couple days.

**Comment by eon-s** [comment]
There is no direct way to get it but have you tried getting the contact position from the body state during body enter signal? (I have never tried that)

**Comment by mayuso** [comment]
You mean something like this?

    get_node("MyStaticBody2D").connect("body_enter", self, "myFunction")

Tried, doesn't seem to work when applying it to a Tile.

**Comment by Zylann** [comment]
In my game, I detect this with a raycast going in the direction in which the character is going, so I am able to get a contact point. But it has very custom physics anyways, for a more classic game we should be able to get the collision point by using the result of `move_and_collide()`.

**Comment by mayuso** [comment]
Invalid call. Nonexistent function 'move_and_collide' in base 'RigidBody2D'

**Comment by Zylann** [comment]
Aaah that one is on `KinematicBody2D`.
For `RigidBody2D` I am not sure... there is probably a way to get contact points (they are mentionned in some functions) but I can't seem to find the API to actually get them. Maybe the API just misses a signal that contains more info than just the collided body?

**Comment by mayuso** [comment]
I've managed to "make something work":

    func _integrate_forces(state):
	    var collidingBodies= get_colliding_bodies()
	    for i in range(collidingBodies.size()):
		var tile_position = get_parent().get_node("TileMap").world_to_map(state.get_contact_local_position(i))
		var tile = get_parent().get_node("TileMap").get_cellv(tile_position)
		print(tile) 

In my case I have 3 diferent tiles. This seems to work to some extend. It recognises a collison and prints 0 when colliding instead of -1. 

The problem is it now always prints 0, it should print 0, 1 or 2 depending on what type of tile it is touching, but I am pretty sure that's just that I need to configure it correctly. I'll update as soon as I can make it work so that others can find how to do it too (If I can).

**Comment by mayuso** [comment]
var tilemap= get_parent().get_node("TileMap");	
	for i in range(get_colliding_bodies().size()):
		var tile_pos = tilemap.world_to_map(state.get_contact_local_position(i))
		var tile = tilemap.get_cellv(tile_pos)
		print(tile)

This code is working well. It's the same as the last one, but refactored. 

My only problem now is the collision detection, for some reason one tiles collisions are overlapping the others, but that's another issue.

This one is solved.

Thank you all for your patience.
