### ISSUE TITLE
Autotiles collision shape doesn't update properly after modification

### ISSUE THREAD

**Issue by mord79** [godotengine/godot#16477]
Godot version: 3.0

Issue description:
In the autotiles window, collision tab, my new collisison shapes where not updated when I play the scene in debug with visible collision shape.

The shape updated after I turn True and False the "Shape One Way" property of the tileset

**Steps to reproduce:**

Create an Tilemap with an autotile tileset
Create collision shape for some tiles
Create a scene and play with debug: visible collision shape
Modify some collision shape et play the scene again
If changes have not been updated, turn True and False (on and off) the "Shape One Way" property of the tileset and play the scene again to see if the shape have been updated

**Comment by akien-mga** [comment]
CC @MarianoGnu @damarindra

**Comment by MarianoGnu** [comment]
Tileset is a resource and is not saved with scene, you have to manually save it from the inspector while editing it clicking the save button. To understand better the issue: when you mean it doesnt update do you mean:
- you stop and start the game changes are not saved? (This is because what i just told you)
- you have autosync changes enabled and changes are not working

**Comment by mord79** [comment]
I think you're right! I didn't even saw the save button on the inspector..... (my bad)

**Comment by GammaGames** [comment]
Is this anywhere in the documentation? I was fumbling along for a bit until I found this thread, I had searched the documentation but I could only find tools for the manually created tilesets, not autotiles

**Comment by JellyWX** [comment]
Having these issues and there's no way I can actually save the autotile (pressing control-s does nothing, closing/reopening the editor loses changes). How do I save? Never had these issues before...

**Comment by MarianoGnu** [comment]
The save icon has been moved to an even more hidden menu now, this is a problem for any kind of resource that is saved to disk.

**Comment by GammaGames** [comment]
It's more hidden? It's right here

![image](https://user-images.githubusercontent.com/7832163/43049509-413ff22c-8db6-11e8-82d1-819cd3e805f7.png)

**Comment by JellyWX** [comment]
Okay, yeah found it but still makes no sense as to why Control-S doesn't work. Surely open panes with changes should all be saved om Control-S?

**Comment by MarianoGnu** [comment]
Control-S saves the scene, not everithing openned/changed. if the TileSet is not local to the scene it wont be saved

**Comment by GammaGames** [comment]
Why is the bitmap automatically saved then? It shouldn't be part of the scene, it should be part of the tileset and yet you don't have to save it manually through the menu.

**Comment by MarianoGnu** [comment]
you mean the bitmask? dunno, it shoudn't

**Comment by MarianoGnu** [comment]
and btw, this screenshot doesn't show curren't master, the save icon is not there anymore since the inspector rewrite
![imagen](https://user-images.githubusercontent.com/1776044/43146436-9daa0f8e-8f37-11e8-9c0c-553f458eba9a.png)

**Comment by GammaGames** [comment]
Ah, I'm using the current stable release. Where is it in the current master, then? Seems strange to hide the save icon for something so important if it doesn't autosave.
