### ISSUE TITLE
Graph editor looks barely visible, when light theme enabled

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#16475]
![image](https://user-images.githubusercontent.com/3036176/35929958-bfac959e-0c41-11e8-907f-3917dfe7e4e7.png)

I think colors and contrast should be narrowly adjusted for this theme...

**Comment by vnen** [comment]
The graph nodes should have a light background too.

**Comment by akien-mga** [comment]
CC @toger5 @djrm

**Comment by djrm** [comment]
everything was working before (#11789), maybe this is also caused by the editor settings buggy patches. (@Chaosus  also did you try restarting godot?)

**Comment by Chaosus** [comment]
Omg, its working now.. something was incorrect in editor settings.. after change the theme its start drawing correctly

![image](https://user-images.githubusercontent.com/3036176/36163401-5fc993c6-10fa-11e8-86cd-7fad9ac3cacb.png)

**Comment by Chaosus** [comment]
Possible related - #16662

**Comment by djrm** [comment]
exactly, some elements require editor restart, maybe a notification would be nice to have (while we change all the codebase to update without restart).
