### ISSUE TITLE
About project setting

### ISSUE THREAD

**Issue by niu2x** [godotengine/godot#1647]
I can't find a 'save' button in project setting dialog's general page.
I find a  'save' button in project setting dialog's Input Map page.
how to save the config I make in general page?

**Comment by niu2x** [comment]
I have to write config file by text editor.
There is no save button, in my xp os.

**Comment by bojidar-bg** [comment]
For general project settings I just press Ctrl+S (don't know if it does something..) and close the window. Then I run the game, and it works. :smile:

**Comment by reduz** [comment]
sorry, the save button should be removed, project settings is saved
automatically when you change something

**Comment by niu2x** [comment]
sorry, depand on my exercise, when I set the main scene and then close the setting dialog, it's become effective. But when I close the engine, and open it again, my setting become invalid.
when I set the screen width and height, it's always invalid, except write the config file by hand.

And, I have to use 'scene save as' to save my modify on one scene, while the 'scene save' is invalid.

Maybe my windows xp operate system is too old ?

**Comment by reduz** [comment]
might have to do with Windows XP, I honestly didn't even expect Godot to
run there as I use many Vista+ specific APIs

**Comment by niu2x** [comment]
My God.

**Comment by niu2x** [comment]
Yes, it do a good job in linux.
