### ISSUE TITLE
[Functionality] Open a existing 2d Project in the 2d version of godot 3

### ISSUE THREAD

**Issue by Arkhano** [godotengine/godot#16471]
**Godot version:**
Godot 3

**What happen now:**
When you open a 2d project in godot 3, it will always open it in the 3d version of godot.

**Feature proposal**
Open the godot version corresponding to where the existing project has being done: if the existing project was made in the 2d version, godot will open the version 2d. If the existing project was done in 3d version, godot will open the project in the 3d version.

**Comment by Ranoller** [comment]
Read that: #16317

**Comment by vnen** [comment]
Godot has no concept of "2D project" or "3D project". The view is selected based on the current node, since you can have any type of node in the same project..
