### ISSUE TITLE
KinematicBody2Ds still partially inside each other after moving

### ISSUE THREAD

**Issue by Gorgexpress** [godotengine/godot#16484]
**Godot version:**

3.0 stable win64

**OS/device including version:**

Windows 10

**Issue description:**

Kinematic bodies sometimes remain partially inside each other after a head on collision. They should be completely separated from what I understand.

**Steps to reproduce:**
This occurred after having two equal sized square KinematicBody2Ds ram into eachother with move_and_slide or move_and_collide. Size of hitbox and safe margin matters. For colliders with a width and height of 60, this problem occurs with the default safe margin of 0.08, but when both bodies have safe margin set to 0.001 everything is fine. For colliders using rectangle shapes with a width and height of 16, the issue occurs even with the minimum safe margin.

Only happens with a head on collision. If one object is either immobile or moving AWAY from the other object, it's fine. 

The first body in the scene moves fine. The issue arises when the second body moves. It's not content of the node itself, but the order that matters here. If Body1 appears above Body2 in the scene's list of nodes, then Body2's call to move_and_slide() will cause the issue. If you right click on Body2 and choose "move up", Body2 will move fine and the issue will arise after Body1 moves instead. 

**Minimal reproduction project:**

[CollisionTest.zip](https://github.com/godotengine/godot/files/1705773/CollisionTest.zip)

A weird thing I noticed in the reproduction project is that the penetration depth(AFTER the 2nd call to move_and_slide) gets higher as the game runs. For example, when both bodies had a height of 60, the the objects were 60.003662 pixels apart after the first collision. After the 10th collision they were 58.856079 pixels apart. At around ~56.8 pixels apart, the depth no longer increased but instead alternated between being ~56.8 and ~63 pixels apart after the 2nd body moved.

**Comment by groud** [comment]
cc @AndreaCatania, any idea on that ?

**Comment by reduz** [comment]
I am on a phone so cant check your code, but seems you are not properly adjusting your body velocity after the collision response.

**Comment by Gorgexpress** [comment]
The bodies simply move in the opposite direction for 1 second if move_and_slide results in a collision. This does mean that the 2nd body still moves forward for 1 frame after the 1st body collides with it though. This is what results in the bodies staying partially inside eachother for certain collider sizes/safe margins. If you throw the collision response in the function and have the first body call that function for both bodies on collision, then Body2's move_and_slide will never even result in a collision.

**Comment by eon-s** [comment]
Safe margin can be set even lower (by code) but is caped on the inspector and may work on situations like this.

And what happens with more (or less) `move_and_slide` bounces?

**Comment by Gorgexpress** [comment]
Changing the number of bounces did nothing. Changing to move_and_collide did nothing. Tried setting the safe margin to 0(with set("collision/safe_margin", 0)), problem still occurred on rectangle shapes with extents 8,8.

**Comment by AndreaCatania** [comment]
@Gorgexpress I've just checked the project and it seems correct to me, so probably I've miss understood something.

On your side is the two bodies remain stacked each other? or are you complain the fact that when they collides it were a bit penetrated?

(In the first case, can you please post here a video / gif where is possible to see this behaviour?)

Another think to note is that you never have to set the safe margin to 0 or the kinematic body depenetration phase always fail

**Comment by Gorgexpress** [comment]
They remain stacked i guess? Though stacked is a harsh word for it, they are only on top of eachother by a few pixels. 

I can make a gif or video or something later. Here's an image of it using extents 4, safe margin 0.08,  and a zoomed in camera.
![capture](https://user-images.githubusercontent.com/3978088/36031101-a943c340-0d77-11e8-924c-1bb9075b1564.PNG)

I created this issue because I'm assuming they shouldn't still be intersecting after calling move_and_slide.
The picture above is taken during the start of the upper body's physics process. The bodies started the frame still inside each other.

**Comment by AndreaCatania** [comment]
The algorithm (internally) perform multiples time the separation process so it's not guaranteed at 100% that it's able to succeed at first call, instead it's guaranteed the fact that sooner or later the bodies will be separated completely.

So this behaviour is correct, and if your game need a specific behaviour (where the overlaps never occurs) you should consider to implement new algorithm.

Close the issue if this explanation is enough, Thanks you for the report
