### ISSUE TITLE
Viewport Texture works in Editor but not in preview and in exported project

### ISSUE THREAD

**Issue by Danny3107** [godotengine/godot#16481]
http://prntscr.com/ibm0bb
It is rendering correct in the Editor but if i go to preview it looks like this:
http://prntscr.com/ibm1g3
If i export it to .exe it will show me the plane too in black.
Everytime i open the project i have to set the viewport texture again for the plane.

**Godot version:**
official 3.0

**OS/device including version:**
Windows 7 64bit Service Pack 1
AMD Radeon HD 7400m Series

[Test2.zip](https://github.com/godotengine/godot/files/1704984/Test2.zip)

**Comment by NathanWarden** [comment]
This is a known issue: https://github.com/godotengine/godot/issues/7998

For now, you need to use a Sprite3D node and assign the viewport texture there instead of to a mesh.

**Comment by eon-s** [comment]
Related to #16006 and #7998 (possibly duplicated too), on the later is mentioned setting the texture as local to scene but nothing changes with it.

If there is a documentation issue, then the steps to use it should be added because it makes the ViewportTexture look useless for 3D.

**Comment by akien-mga** [comment]
Closing as duplicate of #7998.

**Comment by PatDubbie** [comment]
I'm getting this same issue in 4.2.1. Viewport rendering to MeshInstance3D texture material works in editor:
![image](https://github.com/godotengine/godot/assets/134224970/af182f7e-fbba-48a0-9b42-02fa88acf3b5)
But not in game:
![image](https://github.com/godotengine/godot/assets/134224970/ba61292a-d3e8-49c8-ac37-50933fb92e39)

Using the viewport texture with Sprite3D seems to work as intended.

**Comment by eon-s** [comment]
@PatDubbie this is a very old, closed, archived and duplicated issue (original is also closed).
Open a new one with the corresponding test project and all the new details you can add for your version.
