### ISSUE TITLE
network client/server and single player mode

### ISSUE THREAD

**Issue by Lightnet** [godotengine/godot#16482]
Godot version: 3.0

**Issue description:**
Been trying to build network game and offline game that is not network for testing and solo game play builds.

Example: I was building the network test build but decide to build offline but I get server functions error null. But not sure which function gave error just simple ones that been testing. 

is_network_server(), is_network_master()

Is there way to ignore when not playing online and since I wanted to used those function for game testing?

**Comment by hungrymonkey** [comment]
Are you using high level godot networking?

You can check if the scenetree have a network peer has_network_peer ( ) 


http://docs.godotengine.org/en/latest/classes/class_scenetree.html#class-scenetree-has-network-peer

**Comment by Lightnet** [comment]
Oh that work. Was not sure correct check function. Just using master and remote func calls.
