### ISSUE TITLE
Audio glitching on Android

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#1648]
Pops and clicks happen randomly when playing sounds.
Probably, this is a buffer underrun problem.
Different samplerates make things worse.
The problem is described here:
http://stackoverflow.com/questions/21184979/playing-generative-sound-with-opensl
and 
http://stackoverflow.com/questions/14842803/low-latency-audio-playback-on-android
and maybe this presentation will be of help:
https://www.youtube.com/watch?feature=player_embedded&v=d3kfEeMZ65c
This site is all about the topic:
https://code.google.com/p/high-performance-audio/

**Comment by ThomasMorley-T3D** [comment]
I also experienced this issue with Godot 1.0 Sometime the audio will cut-out after a pop/click forcing me to restart the pone to get the sound back.

**Comment by ThomasMorley-T3D** [comment]
freemanfromgodotengine - did you try changing some of the values in the project settings? I see that you can set a larger buffer and that might help. I lost the original code I had that caused my error so I can't test it with a larger output buffer.

**Comment by freemanfromgodotengine** [comment]
ThomasMorley-T3D, 

I did lots of experimenting with my audio project. I was trying to hunt the cause of the problem for a week or two. What I tried:
- changing sample rate of audio files.
- different settings at sound import dialog - normalize etc.. 
- to normalize, convert all sounds outside of Godots import dialog.
- to set different values for SamplePlayers volume dB, voices count. 
- experiment with settings of an audio in Project Settings: output latency, mixer latency, audio driver.. 

I notices when experimenting with sample rates, that depending of the settings, glitching could occur more often or occur less.
The best setting in case of my tablet was 16-bit 44100 Hz. Glitching was once or twice a minute. I think 22050 16-bit generated glitching more often.
Pop/click sounds always seemed random, not connected to audio amplitude, frequency or anything I could visually connect with it's occurrences.
To my ears that problem sounded very similar to bufferunderrun on Linux in the early days of RealTime kernel and jack server.

Yesterday I have spend long night talking to reduz on irc, asking questions, explaining, sending audio file as an example of the problem and his conclusion was above underrun problem. He promised to work on a solution, but it looks like the problem might be android overall, afaik.

**Comment by akien-mga** [comment]
Can you still reproduce this issue in the current master branch? I think that improvements to the audio engine are planned for 2.1, so assigning to this milestone.

**Comment by freemanfromgodotengine** [comment]
Sorry akien-mga, I missed your reply. I will get back to that app I was building then (I stopped because of the audio issues) to check if the problems remain. I will be able to check it with android 6.0.1. Maybe something changed since android 4.4.4 I was testing with last time.
 I am investigating many things in Godot - audio related - and will report probably when reduz will start to work on audio engine rewrite.

**Comment by vnen** [comment]
@freemanfromgodotengine have you ever got to test this issue again?

**Comment by freemanfromgodotengine** [comment]
@vnen. No, not yet. My fault. Sorry.
Give me some time, please. I have to find time to rewrite that old project again in new version of Godot, because lots of things changed - but no audio related things afaik, so it would be a miracle if the problem would be gone. I am generally waiting for reduz's work to 2.2 that should have audio engine rewrite.

What I can say for now, I am currently working on some new application that I am trying to release really soon and it's an audio app as well. I use AudioServer now for playing samples. The old one was using SamplePlayers only. In the new application I am experiencing - but very occasional and rare this time - singular, quiet clicks. It's definitely not that bad as it was in my old application - maybe new android does things better or newer Godot does, but audio seams not completely bullet proof for me yet.

**Comment by freemanfromgodotengine** [comment]
Ok, I finally did it. I check the thing out after all that time.
Unfortunately the small audio clicks are still there.
I used few weeks old 2.1 alpha I compiled myself and tested on Android 6.0.1.
However I have noticed, while testing on Linux computer, that the click are there as well, so it's not only Android.
I am sure my the audio samples are crystal clear, no clicks must come from the audio system itself.

The thing is rather strange, because I finished working on a newer project, mobile audio app full of sounds as well and I do not encountered the click with this one.
The only difference is that I have learn to use AudioServer now, and the new project uses it instead of calling for SamplePlayer node to play sounds all the time.

I wonder what's the computational/CPU time gain when using AudioServer vs SamplePlayer? There is one for sure as the first thing I noticed when using AudioServer was the latency mostly gone between the touch and the audio reaction.
Maybe SamplePlayer and it's code are not optimized yet, so have a hard time when being used with a lots of longer and higher quality audio files?

**Comment by akien-mga** [comment]
There were various improvements done to the audio drivers for 2.1 and 3.0, as well as a refactor of the audio engine for 3.0, so assuming fixed. Feel free to open a new issue if you can still reproduce audio glitches in the current master branch.
