### ISSUE TITLE
Improve the zoom buttons on graph editors

### ISSUE THREAD

**Issue by alpinus4** [godotengine/godot#16488]
I'm supposed that this:

![](https://user-images.githubusercontent.com/25907897/35966228-7d14e0a2-0cbd-11e8-9ad6-b782330e0d0c.jpg)
should show actual zoom level.

But with any zoom it ever shows "1".
![](https://user-images.githubusercontent.com/25907897/35966301-ba794cd0-0cbd-11e8-9427-773f4bbc92d2.jpg)
![](https://user-images.githubusercontent.com/25907897/35966306-be173c94-0cbd-11e8-92bc-60931373be3b.jpg)
![](https://user-images.githubusercontent.com/25907897/35966307-c04687fe-0cbd-11e8-8f36-9fd6a46704e2.jpg)

**Steps to reproduce:**
Create any visual script and try to zoom.

**Godot version:**
v3.0.stable.official.mono

**OS:**
Windows 10 ver. 1709 64-bit

**Comment by groud** [comment]
It's not the zoom level, it's the "reset to 1/1 scale".

**Comment by alpinus4** [comment]
@groud Hah.. So it's a bit non-intuitive.

For ex. in photoshop reset zoom scale button looks like this:
![](https://user-images.githubusercontent.com/25907897/35971782-9f23be7c-0ccf-11e8-925b-33cb391cd241.png)
And everyone know what it does.

I propose to add something like:
![](https://user-images.githubusercontent.com/25907897/35971522-8e903848-0cce-11e8-82f9-46d1cb196a78.jpg)
or:
![](https://user-images.githubusercontent.com/25907897/35971940-22ae557c-0cd0-11e8-9c5b-423b656f7dc6.jpg)

**Comment by groud** [comment]
Ok I guess something like than would make sense.

**Comment by bojidar-bg** [comment]
IMO, it should be "reset", since "100%" is even more likely to be misinterpreted :smiley:

**Comment by fracteed** [comment]
I would really love to see smaller increments for the zoom levels with the +- buttons. I use a Wacom tablet almost exclusively and I find that I need to plug in a mouse just to use the wheel to get things zoomed to the level I need. Would be great to either have an editor option for the amount of zoom increment for those buttons, or better still just make them smaller by default(maybe 10 or 15 % increments).

**Comment by girng** [comment]
@fracteed just because you use a tablet for development (which is a rare use-case), doesn't mean we PC users (99% of developers) have to suffer with small icons.

**Comment by fracteed** [comment]
@girng I think you are confused...lol. You do know what a Wacom tablet (Intuos) is right? Pretty much every artist uses a Wacom to some extent. Maybe you think I meant a touchscreen PC, ala Surface Pro? Not sure what you mean by small icons, as I am referring to the  zoom percentage you get each time the +- buttons are pressed.

**Comment by girng** [comment]
@fracteed well, to be fair you did say

"still just make them smaller by default(maybe 10 or 15 % increments)." i was thinking you are talking about the button img size.

**Comment by akien-mga** [comment]
@girng "them" is "zoom increments". Smaller zoom increments (e.g. 10%) means that clicking `+` would go from 100% to 110%, instead of maybe 150% currently.

Please try to avoid the passive aggressiveness in your comments on what others propose though, it's not the first comment I read from you where you misinterpret something and call someone out. *Always assume positive intent*, and if you think that a proposal is not a good idea, phrase your objection respectfully and constructively.

**Comment by groud** [comment]
This is implemented on master. Closing :)
