### ISSUE TITLE
GDNative support for NetworkedMultiplayerPeer, PacketPeer, AudioStream, AudioStreamPlayback, VideoStreamPlayback and VideoStream

### ISSUE THREAD

**Issue by fire** [godotengine/godot#16496]
**Godot version:**
master

**OS/device including version:**
Windows 10, gtx 1080

**Issue description:**

Discussed with @reduz that NetworkedMultiplayerPeer, PacketPeer, AudioStream, AudioStreamPlayback, VideoStreamPlayback and VideoStream need to be wrapped in gdnative.

However the approach used in the commit is wrong as it allocates memory.

https://github.com/fire/godot/commit/fa7c07fc352776df25042891fcbd6a5a6d159d21

The correct approach is a low level wrapping where one doesn't go through the class_db and directly uses the gdnative layer like the arvr interface.

* The wrapper needs to use the c api struct method of function pointers
* Json api file needs to be modified
* Misc scons changes

**Comment by girng** [comment]
i originally thought gdnative was not bound to limits, and could modify anything already. it seems like, to me, gdnative shouldn't be have the word "native in it" it's kind of misleading (especially after william told me how it functions).  it's native in the sense,it  uses low level c++ code, however, not native in the sense that is can modify other features in the engine.

**Comment by fire** [comment]
I don’t remember my original problem anymore. Closing.
