### ISSUE TITLE
Crash on canceling collision creation in autotiles

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#16498]
**Godot version:**
Godot 3.0

**OS/device including version:**
Windows 10

**Issue description:**
Crashes on canceling collision creation

**Steps to reproduce:**
Click once with the polygon tool, then change to the mouse tool and click anywhere.

**Comment by akien-mga** [comment]
CC @MarianoGnu @damarindra

**Comment by AleksandrHovhannisyan** [comment]
Autotiling in 3.0 still causes the program to crash. Not sure what's causing this behavior, though.
