### ISSUE TITLE
[Editor 2D] Editor completion not suggesting all the existing methods

### ISSUE THREAD

**Issue by Arkhano** [godotengine/godot#16493]
**Godot version:**
Godot 3

**OS/device including version:**
Windows 8.1

**Issue description:**
The godot editor is not showing the completion for the CollisionShape2D method called "get_shape()" and also for the method "get_shape().get_extents()"

Note1: the **"get_node("CollisionShape2D").get_shape()" and "get_node("CollisionShape2D").get_shape().get_extents()" exists in the engine, but the problem is that there is not a way the user could know about the last one**.
Note2: get_extents() is very important for know the half size of a collider assign to an object, this works similar with the sprite size method.
Note2: the same way the "get_shape()" exists in the docs but the "get_shape().get_extents()" does not exist.

**Steps to reproduce:**
1) Create a CollisionShape2d node as a child of a root node.
2) Create a script in the root node
2) Assign the get_node("CollisionShape2D").get_shape().get_extents() to an variable, **this will work, but the editor will not suggest it.**

**Comment by vnen** [comment]
This is not a bug, the getter and setter methods are not shown in completion when there's a property available.

You should do `$CollisionShape2D.shape.extents` instead.

**Comment by avril-gh** [comment]
> $CollisionShape2D.shape.extents

what a beauty, i like it :heart:

**Comment by Arkhano** [comment]
Thank you for the fast response. So about the shape.extents, is there any doc about it? I discovered it by reading some comments but I don't find nothing about it in the docs.

**Comment by Noshyaar** [comment]
For `Shape2D`s, `extents` is only available for `RectangleShape2D`

http://docs.godotengine.org/en/latest/classes/class_rectangleshape2d.html

**Comment by Noshyaar** [comment]
Closing as working as expected
