### ISSUE TITLE
Normal Map/Texture shows as yellow in the preview window

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#16490]
It seems like the Normal map is actually working in the editor but I don't like that it looks like an object space normal map in the preview window. I have tried diffrent import settings with no luck. Funny thing.. when importing it actually turns purple (correct) for a few secoinds before turning back to yellow.

 
![image](https://user-images.githubusercontent.com/24936603/35970496-cbcbbc5e-0cca-11e8-8486-77c6a2ff7ce6.png)

**Godot version:**

Godot 3.0 Stable

**OS/device including version:**

Windows 10, Geforce gtx 1060

**Issue description:**

Imported a Tangent normal map in png format. It should look Blue/Purple but is yellow/Green like an object space normal map I think. I have tried different settings in the import settings.

**Steps to reproduce:**
Import a normal map in png format. 

**Minimal reproduction project:**

**Comment by vnen** [comment]
I think this is just a preview thing, since normal maps are stored as RG textures.

**Comment by quantum-entangler** [comment]
texture compression, as vnen mentioned some compression methods rely on only the dxdy and rebuild the depth in shader during run-time. You can change the compression mode to none/lossless to get the depth(blue) channel imported, assuming your texture is normalized and in correct orientation/handedness.

**Comment by jesperkondrup** [comment]
@quantum-entangler Thanks, that worked!

**Comment by quantum-entangler** [comment]
@jesperkondrup 
If its resolved then don't forget to close the issue. :)

**Comment by RichardEllicott** [comment]
i keep getting this, almost anually and it's when i forget substance designer should output raw for normal maps

for some unknown reason this clashes with VRAM compressed, so i found setting lossless would solve my yellow normal maps but really the route problem is when i set up a substance graph wrong

i add this note as i get these pages by google searches
