### ISSUE TITLE
Enable plugins downloaded from the Asset Library by default

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#16492]
An user on Discord has noticed that plugins downloaded from the Asset Library are not enabled by default. They probably should be enabled by default to avoid confusion as to why a plugin cannot be used after it was downloaded.

**Comment by Geequlim** [comment]
Maybe popup a notice dialog to warning user that plugins may harm for their project before enable them.

**Comment by hubbyist** [comment]
Auto enable must be an option. Some times you may just want to examine the code or make changes before activating a plugin.

**Comment by Noshyaar** [comment]
Or ask users to choose whether to enable it when there is a dialog for picking files to download.

**Comment by hubbyist** [comment]
If there won't be an option about the default behaviour for "when installed" some users will be unhappy when they forgot to untick "enable when installed" so there must be both an editor option for editor default behaviour and a checkbox in install dialog to override this behaviour when needed.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/324.
