### ISSUE TITLE
Selecting & copying error label

### ISSUE THREAD

**Issue by qubodup** [godotengine/godot#165]
In http://www.godotengine.org/forum/viewtopic.php?f=11&t=254 I reported an issue and wanted to include the error message which I got, however I could not copy-paste the message "Attempt to call function 'play' in base 'null instance' on a null instance."

Screenshot: http://i.imgur.com/ogbkMUt.png

1. Turn the error message label into a read-only text field but allow selecting and copying text. By the way, the Debug output text field should allow selecting text also.

As for the error message, it is debatable whether clicking it should select all of its content for easier selection. At the very least, double- or at least triple-clicking should select all of it. (Does anybody happen to know the behavior of Unity/VisualStudio/Eclipse?)

2. Add an icon to either right or left of the right of the error message label, which has the function of copying the error message text to clipboard.

3. Display error messages in the command line output, when Godot is launched from such (This is probably unusable for many developers).

Without the ability to copy-paste these messages, collaborative (community) debugging takes more time.

**Comment by akien-mga** [comment]
I can confirm that this issue is still valid.

**Comment by jackmakesthings** [comment]
+1 to fixing this - sometimes the error message is wider than the available space and it's impossible to see the end of it. Putting it in the debug window so the words can wrap (and be selectable) would be a good start.

**Comment by akien-mga** [comment]
This has been fixed in 2.0 with the new debugger panels:
![spectacle th6055](https://cloud.githubusercontent.com/assets/4701338/14722803/ca66469a-080d-11e6-9ad3-2707343b0e49.png)

**Comment by GamesOpenSource** [comment]
This does not copy the text "error(line,column): "

It'd be nice if any text that might be necessary to google can be just selected and copy-pasted.

**Comment by microaeris** [comment]
I don't have the same debugger pane as shown in @akien-mga's screen shot. I'm using the latest stable Godot build. Is this feature still available?

**Comment by Talamander** [comment]
+1 for this issue
