### ISSUE TITLE
Add a tab into the Debugger panel to view Arrays content

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1651]
Hi,

It could be useful if there was a mean to see the content of array variables into the Debugger panel.

**Comment by reduz** [comment]
yeah this needs to be done, itś planned for 1.2

**Comment by akien-mga** [comment]
I believe this has been implemented, in the debugger you can now click on a ">" icon to have the array opened in the inspector via the ArrayPropertyEdit. It's a bit weird as it lets you edit the array even though it's only debugging info, but at least the data is accessible :)
