### ISSUE TITLE
Triplanar mapping breaks refraction on SpatialMaterial

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#16516]
**Godot version:**
3.0

**OS/device including version:**
Kubuntu 14.04
NVidia GTX 1060

**Issue description:**
When triplanar mapping is enabled on a material that uses refraction, the refraction disappears.

**Steps to reproduce:**
1. Create a MeshInstance and assign a refractive material to it, also turn down the albedo transparency so you can see the world behind it refracted
2. Turn on triplanar mapping under the UV1 panel
3. Notice the refraction disappears

**Minimal reproduction project:**
[refractionbug.zip](https://github.com/godotengine/godot/files/1711645/refractionbug.zip)
Notice how the refraction is visible on the mesh called "works", but not the one called "broken", even though they use the same material, except for triplanar mapping turned on for the "broken" mesh.

![bug](https://user-images.githubusercontent.com/31383123/36037739-f8f4982e-0dbd-11e8-94af-496df37cd799.png)

Working refraction on the left, broken refraction on the right.

**Comment by Chaosus** [comment]
Note the line 
https://github.com/godotengine/godot/blob/133942cfeb0279ca03ab9943459c5140ab1f1725/scene/resources/material.cpp#L740
