### ISSUE TITLE
Autotile doesn't support uncommon bitmasks

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#16511]
**Godot version:**
Godot 3

**Issue description:**
Uncommon bitmasks do not work.
![j8x2wky](https://user-images.githubusercontent.com/18586380/36068914-3ad406e4-0ec7-11e8-9dd2-1c0fe15e85dd.png)

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by akien-mga** [comment]
Fixed by #18619.
