### ISSUE TITLE
RCEdit does not work when exporting for Windows Desktop on Windows

### ISSUE THREAD

**Issue by ArcOfDream** [godotengine/godot#16517]
**Godot version:**
3.0 Official

**OS/device including version:**
Windows 10 64-bit, Nvidia GTX 1050Ti

**Issue description:**
The tool while working on Linux and Mac through Wine, doesn't appear to produce results when exporting on Windows.

**Steps to reproduce:**

- Set path to RCEdit on Windows
- Add an .ico file to the Icon parameter of Windows Desktop export option
- Export

**Minimal reproduction project:**

**Comment by vnen** [comment]
Note that the Windows Explorer has some sort of cache so it might not show the new icon until you restart. I think the file properties dialog shows the new icon.

**Comment by girng** [comment]
best to just go into `godot-master\platform\windows`

`windows` being the platform you want, and change the `godot.ico` to your custom .ico, and re-compile. much better, hope that helps

**Comment by ArcOfDream** [comment]
ah, no, sorry. there was a total oversight on my end, nothing to see here 🙇
