### ISSUE TITLE
Converting from 2.3 to 3.0 what's the replacement for add_shape?

### ISSUE THREAD

**Issue by lancefreedlund1** [godotengine/godot#16510]
I have several games which use add_shape to create a collision shape in a KinematicShape2D script. What's the replacement for this in Godot 3.0? Can't find it anywhere!

**Comment by AurumStein** [comment]
The replacement for add_shape can be(I still have to try it properly):
`var shp = RectangleShape2D.new()`
`shp.extents = Vector2(1f,1f)`
`$CollisionShape2D.shape = shp`

**Comment by Zylann** [comment]
Before you had to use a shape API on bodies because nodes were editor-only, now you can add the CollisionShape nodes as child of your body.

**Comment by lancefreedlund1** [comment]
It worked! Actually it was combination of both your comments that made it clear. Thanks!

**Comment by Noshyaar** [comment]
Closing as solved
