### ISSUE TITLE
Toggle "Set All Children Selectable/Unselectable"

### ISSUE THREAD

**Issue by ebenson6295** [godotengine/godot#16526]
**3.0**

**Windows 10 64 bit, Dell XPS 15:**

I would like to request a feature where you can select an item in the Node list (under "Scene") and then toggle *all* of its children to be selectable or unselectable. I tried really hard to create this functionality on my own but was unable to do so, as I cannot find a way to edit whether or not a child is selectable using  GDScript. :/

**Comment by YeldhamDev** [comment]
Isn't this what you want?
![screenshot1](https://user-images.githubusercontent.com/30739239/36058743-c851670e-0e0f-11e8-9c06-3f478ef7dab4.png)

**Comment by groud** [comment]
According to your description, this is exactly what the button shown by @YeldhamDev does.
I close the issue for now. If your problem is not solved, please tell us here.

**Comment by ebenson6295** [comment]
I'm sorry, I was half asleep last night and mis-spoke. Here's my real issue. :P 

I'm using a plugin (https://godotengine.org/asset-library/asset/160) that creates a Tileset from a .png tile image. One of its features adds Collision/Navigation/Occluder children to _each tile_ it creates from the image. Let's say that I create a Tileset from a .png that has 4,000 tiles in it. If, during the tile creation, I chose to add an Occluder to each tile, there are 4,000 tiles each with their own Occluder child. Unfortunately, all of those Occluders are selectable and I don't want them to be. I could click on each individual tile in the Tileset and select the button you mentioned above for each tile, but it would take me hours if not days. My feature request was for functionality where I can select the Tileset which contains 4,000 tiles, and then set the children of all 4,000 tiles as unselectable in one click. Even if it's just an addition of a new function to the script, (I can make the plugin myself). 

I really appreciate the fast response, and I appreciate everything y'all have done for us already in creating/editing the Godot engine.

**Comment by groud** [comment]
Honestly I don't know how can we implement that, it looks like a really corner case situation. I would advise you to use a dedicated script to do so.
Note that to make an object's children non selectable you can set the it's meta property "_edit_group_" using :
`mynode.set_meta("_edit_group_")`

**Comment by ebenson6295** [comment]
Thank you! I'm certain that the snippet you mentioned above will solve my problem. :)
