### ISSUE TITLE
Shadows wobble when looked at

### ISSUE THREAD

**Issue by TomWor** [godotengine/godot#16520]
**Godot version:**
3.0

**OS/device including version:**
Windows + Linux GTX970

**Issue description:**
I noticed quite a bit of issues with shadows "wobbling" around in my test scene and was surprised when moving the camera around that the shadows would start becoming super sharp and steady, just like I wanted them to. Is this a misconfiguration on my part, a bug or is this intended behaviour somehow?
Issues #12148 and #13575 might be related.

Edit: Shadow Filtering in project settings is disabled.

Lookin good:
![screenshot 3](https://user-images.githubusercontent.com/9846466/36048501-bed82e18-0ddf-11e8-9cb0-d4689fc9e873.png)

Lookin meh:
![screenshot 4](https://user-images.githubusercontent.com/9846466/36048519-cabdf3a2-0ddf-11e8-8b3e-5a8490a40757.png)

**Steps to reproduce:**
1. Check out https://github.com/Worgames/superspacearcade_godot
2. Open "scenes/TestScene"
3. Move the camera around near a tunnel element

**Comment by Calinou** [comment]
If you set the shadow depth range to **Optimized**, the engine will find the best possible "layout" for shadow rendering, which will make shadows look sharper at the expense of visible "fuzzing" when the camear is moving (it's noticeable around shadow edges). In some scenes, it may also cause shadow quality to vary depending on the camera's position.
The default setting, **Stable**, uses a constant approach; shadows won't look as sharp, but won't have a "fuzzy" appearance when the camera is moving.

See [Lights and Shadows](http://docs.godotengine.org/en/3.0/tutorials/3d/lights_and_shadows.html#directional-shadow-mapping) in the documentation.

**Comment by TomWor** [comment]
Wow, this looks *much* better for what I intended, thanks @Calinou - I also set Mode to "PSSM 4 Split" and now it's just brilliant - don't know the performance hit yet but the visuals are great.
