### ISSUE TITLE
Multiple collision slides when only one expected.

### ISSUE THREAD

**Issue by leiget** [godotengine/godot#16523]
I've already searched for a duplicate issue.

**Godot version:**
68f2774

**OS/device including version:**
Xubuntu 16.04

**Issue description:**
I'm not sure this is a bug or not, but I just wanted to put it out there.

When using slide collision with "get_slide_collision(x)" and "get_slide_count()" I get more slides then I expect. For instance:
![collision_slides](https://user-images.githubusercontent.com/20325471/36052089-e9befedc-0db1-11e8-9109-dc22877a67b4.png)

The top part is the character after he has moved forward. There is only the ground plane.
The bottom part is the same as the top, but the character is invisible. As you can see with the red spheres there are two collision slides. Here is some info that I printed from the program:

```
Current slide collision: 0
Total slide collisions: 2
SlideCollPos = (-54.0494, -0.000023, -7.998839)
-------
Current slide collision: 1
Total slide collisions: 2
SlideCollPos = (-54.0494, -0.000023, -8.015764)
```

**Steps to reproduce:**
Simply have a character with a capsule collision shape and have him move around, with gravity affecting him. Use "move_and_slide()". Check minimal project below.

**Minimal reproduction project:**
[FPS_SlideColls.zip](https://github.com/godotengine/godot/files/1712573/FPS_SlideColls.zip)

**Comment by AndreaCatania** [comment]
Just tested, and all is correctly.
The algorithm internally performs multiple times the sliding process depending by the velocity applied.

If I've clarified your doubt please close the issue. Also thanks you for the report.

**Comment by leiget** [comment]
Okay, so this is the way it's supposed to be? The reason that I'm getting multiple slides is because I'm using a capsule, and as it moves forward, it also moves down, causing two slides? I'll close the issue, anyway.

**Comment by AndreaCatania** [comment]
This should explain well what's happens there: 
![untitled](https://user-images.githubusercontent.com/8342599/36071081-04664d82-0f09-11e8-8049-ba965699365f.png)

More or less this is how it works

**Comment by leiget** [comment]
That seems suboptimal, but I'm guessing that's just the nature of 3D physics on computers.
