### ISSUE TITLE
Unable to delete MeshTile in GridMap on MacBook using Touchpad

### ISSUE THREAD

**Issue by ordigdug** [godotengine/godot#16524]
**Godot version:**
3.0 Stable Official

**OS/device including version:**
macOS High Sierra 10.13.3
MacBook Pro using trackpad

**Issue description:**
Unable to delete/remove a mesh tile using:  Shift + Right Click (2 fingered push on trackpad).

**Steps to reproduce:**
When trying to remove a tile in the GridMap, holding down Shift and placing 2 fingers on trackpad and barely moving makes the "floor" go positive and negative.

**Minimal reproduction project:**
Demo: 3D Platformer

**Comment by DanielDo98** [comment]
Hi, can I deal with this bug? @groud

**Comment by groud** [comment]
@DanielDo98 sure go ahead. :)

**Comment by ordigdug** [comment]
@DanielDo98 Have you looked into this yet? I believe the code below is causing the issue:

file:             modules/gridmap/grid_map_editor_plugin.cpp
function:    bool GridMapEditor::forward_spatial_input_event(...)
	...
	Ref<InputEventPanGesture> pan_gesture = p_event;
	if (pan_gesture.is_valid()) {

		if (pan_gesture->get_command() || pan_gesture->get_shift()) {
			const real_t delta = pan_gesture->get_delta().y;
			floor->set_value(floor->get_value() + SGN(delta));
			return true;
		}
	}

**Comment by DanielDo98** [comment]
I'm sorry, but I've been really busy lately. Someone else can tackle this bug. Again, sorry if I caused any inconvenience.

**Comment by akien-mga** [comment]
Fixed by #17111.
