### ISSUE TITLE
Nesting get_node shorthand "$" causes error "Expected identifier as member"

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#16525]
**Godot version:**
3.0

**OS/device including version:**
Win10

**Issue description:**
`return $KinematicBody2D.$Sprite.texture.get_size()` errors out

`return $KinematicBody2D.get_node("Sprite").texture.get_size()` works fine

[Original shorthand issue](https://github.com/godotengine/godot/issues/4309)

**Comment by cbscribe** [comment]
The $ shorthand requires the full relative path to a node. The correct usage would be:

    return $KinematicBody2D/Sprite.texture.get_size()

**Comment by JarLowrey** [comment]
Great, thanks!

**Comment by JarLowrey** [comment]
Great, thanks!
