### ISSUE TITLE
RpcId not working.

### ISSUE THREAD

**Issue by blukatstudios** [godotengine/godot#16538]
Godot Engine V3.0.stable.official.mono

Ubuntu 64 bit
Actual:
RpcId(int peerId, string method, [args]);
Fails silently.

Expected:
RpcId(int peerId, string method, [args]);
should make a remote call to the specified peer.

Steps to reproduce:
1.Unzip included Example file.
2. Edit Server project in godot editor.
3. Edit Client project in godot editor. (Make sure debug ports are different between godot instances.)
4. Run server in editor.
5. Run Client in server.
6. You should see Rpc calls succed and RpcId calls fail.

[Example.tar.gz](https://github.com/godotengine/godot/files/1713561/Example.tar.gz)

**Comment by mhilbrunner** [comment]
To be clear: This is in C#, I just tested `rpc_id()` in GDScript and it works fine.

**Comment by cart** [comment]
I also hit this issue in an earlier build, but it appears to be fixed in master

**Comment by akien-mga** [comment]
Is it fixed in 3.0.2 too, or is the fix missing there?

**Comment by cart** [comment]
Yeah it works there.  Sorry for the delay!

**Comment by mhilbrunner** [comment]
Fixed as per above comments.
