### ISSUE TITLE
`_area_input` doesn't Work with Moving Objects

### ISSUE THREAD

**Issue by Cygon** [godotengine/godot#16536]
**Godot version:** 3.0-stable, custom build from 9bd402698cfa299b79b9144f8d7744c308a4e085
**OS/device including version:** Gentoo Linux 4.9.72, KDE Plasma 5.10.5
**GPU model and drivers:** NVidia GTX 1080 w/proprietary drivers 387.22

**Background:**
For AR/VR projects, UI has to be in world space. The way to achieve this as demonstrated by the example projects is to render a viewport onto a plane and to translate raycast-based world space input into viewport coordinates.

![World Space UI Example](https://user-images.githubusercontent.com/3613175/36062110-f727c69e-0e65-11e8-9c48-cfdc14cdad93.png)

As described in the [InputEvent Documentation](http://docs.godotengine.org/en/3.0/tutorials/inputs/inputevent.html):

*4. If no one wanted the event so far, and a Camera is assigned to the Viewport, a ray to the physics world (in the ray direction from the click) will be cast. If this ray hits an object, it will call the CollisionObject._input_event() function in the relevant physics object (bodies receive this callback by default, but areas do not. This can be configured through Area properties).*

**Issue description:**
The `CollisionShape`'s `_area_input` signal for mouse and touch input is emitted only when the mouse/touch point moves, but not when movement of the camera or viewport plane causes the mouse/touch point to end up at another location on the viewport.

Use cases in which this may happen could include:
- UI is faded in before the camera stops moving from a cutscene
- The UI plane moves in response to mouse hover events over the UI (think rollouts on screen borders such as the tablet in FNAF)
- The UI is used in VR, where the camera is never static and the user is likely to do head movements even while interacting with the UI

I believe the position of a `CollisionShape` hit by the mouse/touch point should be re-checked once per frame and a new `_area_input` signal emitted if the raycast makes contact at a different position (or even hits a different collider altogether).

**Minimal reproduction project:**
[Moving_3D_UI.zip (version 3)](https://github.com/godotengine/godot/files/1781552/Moving_3D_UI.zip)

_The `Area` node in the reproduction project has a property 'CameraOrPlaneCanMove'. Turn if **off** to see the issue. Turn it **on** to generate synthetic mouse events (which leads to another issue: button press events are not forwarded correctly)._

**Comment by Cygon** [comment]
Here is a small update to the minimal reproduction project. This version forwards a mouse position of (-1, -1) one time after the mouse has moved off the collider. 

The example injects `InputEventMouseMotion`s to the `Viewport` from `_process()` to keep the mouse position up to date while UI plane moves around (this emulates the suggested behavior).

If I keep the mouse perfectly still (and wait for the UI plane to move under my mouse cursor), it will cause the button to become highlighted (*hover* effect, but then it will stay highlighted even though I deliver mouse events where the mouse position is outside the button to the `Viewport`.

[Moving_3D_UI.zip (version 2)](https://github.com/godotengine/godot/files/1713640/Moving_3D_UI.zip)

**Comment by reduz** [comment]
This should work now without any hacks. Just forward the event as soon as mouse moves and it will work out of the box. No need to re-send events on every frame or similar.

**Comment by Cygon** [comment]
I would rate it as a 90% success :)

Everything works, except mouse capture. If you click on a button and hold down the mouse, the button's "down" state will be shown **if the mouse cursor is over the button at its original transform**, no matter where to button actually is on the screen.

Apart from that, an amazing improvement and an early Christmas present. Thank you!
