### ISSUE TITLE
Trouble with glTF import

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#16544]
**Godot version:**
Godot official v3
**OS/device including version:**
Ubuntu 17.10
**Issue description:**
Tried making a blender cloth simulation, baked the animation to shapekeys, exported to glTF 2.0. Godot imports wrong animation track names so animation has to be fixed manually:
![image](https://user-images.githubusercontent.com/1177508/36066272-3da399ae-0ea7-11e8-9d7b-f7b1ef265b8c.png)
I don't experience the crash from #16124.

UV maps also have a problem, I'm not sure exactly what's going on, the UV debug view seems to be correct, check attached images.
![image](https://user-images.githubusercontent.com/1177508/36066275-4c6ff1e4-0ea7-11e8-87e8-aa3da5336212.png)
![image](https://user-images.githubusercontent.com/1177508/36066288-7e9bb748-0ea7-11e8-8e37-f18420100c04.png)
it's clear that the UVs are in the right place based on the UV debugger in godot, but the image doesn't render properly.
![image](https://user-images.githubusercontent.com/1177508/36066281-5f24583e-0ea7-11e8-9344-5119cd7ef99b.png)

project:
[godot-dbg-github.zip](https://github.com/godotengine/godot/files/1713725/godot-dbg-github.zip)

**Comment by razvanc-r** [comment]
I think I narrowed it down, it's not the glTF import per se, it's the morph targets that don't respect the UVs or something of that sorts. Check out the attached project

Blend shapes off (correct texture):
![image](https://user-images.githubusercontent.com/1177508/36071996-30d8de98-0f18-11e8-823f-467e20ac2ce6.png)

Morph target 0 turned on a bit (incorrect texture):
![image](https://user-images.githubusercontent.com/1177508/36072009-5a8a9e20-0f18-11e8-8fc8-13dcf0c8cf1c.png)

Project:
[godot-dbg-github.zip](https://github.com/godotengine/godot/files/1714232/godot-dbg-github.zip)

**Comment by JosephCatrambone** [comment]
I'm also running into GLTF issues with Blend Shapes/Morph Targets.  This is reminiscent of the indexing issue from a long time back.  A GLTF export from Blender yields this in Godot 3.1.

![2019-06-26_13-49-49](https://user-images.githubusercontent.com/2160055/60213892-4aea8a80-9819-11e9-9851-10cc0ae99784.gif)

The same GLTF import in Blender works okay:

![2019-06-26_13-50-42](https://user-images.githubusercontent.com/2160055/60213996-7cfbec80-9819-11e9-8621-68785cc4d55c.gif)

Here's the GLTF and original .blend file:

[Models.zip](https://github.com/godotengine/godot/files/3331861/Models.zip)

**Comment by Anutrix** [comment]
I am running into some dependencies issues on latest master for that project.

**Comment by JosephCatrambone** [comment]
@razcore-art I have a patch for the indexing error pending (https://github.com/godotengine/godot/pull/30877).  When that's merged, would you be able to retest?

**Comment by akien-mga** [comment]
The issue still seems reproducible in the current master branch.

**Comment by ligazetom** [comment]
Blend Shapes work in 3.2 correctly.

**Comment by fire** [comment]
I test https://github.com/godotengine/godot/issues/16544#issuecomment-506039940 and https://github.com/godotengine/godot/issues/16544#issuecomment-364737896. Both seem to work in Godot Engine 3.2

![editor_screenshot_2020-01-09T134048-0800](https://user-images.githubusercontent.com/32321/72107215-c0b1d180-32e5-11ea-9d8c-1e7ad6374c14.png)

![editor_screenshot_2020-01-09T134158-0800](https://user-images.githubusercontent.com/32321/72107271-d7f0bf00-32e5-11ea-9df2-48f7c1b73f53.png)

Thank you for your contributions.
