### ISSUE TITLE
Suggestion: Allow Chaining Multiple AudioStreams

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#16549]
Suppose I want to play two audio streams one after another.

i.e. invoking "play" plays AudioStream A, invoking "play" again, plays AudioStream B, invoking "play" once again, plays AudioStream A again, and so on.

At the same time, I want the AudioStream to go through an AudioStreamRandomPitch, so each of those two sounds playing in alternating order will have randomized pitch.

It'd be nice to be able to add in your own custom AudioStream. Especially, if say, I wanted to add an effect in between my AudioStreamAlternating and AudioStreamRandomPitch. I could make an AudioStreamMyEffect, and slap it in between those two.

I'm thinking maybe this is already possible with AudioStreamSample (with a script attached), but there's no documentation for how I'm supposed to use that (yet).

**Comment by hungrymonkey** [comment]
why dont you use multiple audiostream players?

https://godot.readthedocs.io/en/latest/classes/class_audiostreamplayer.html

audiostreamplayer should have a signal called finished which allows you to call a function asynchronously.

Basically

A .play() -> finish signal calls b.play -> b signal calls a.play()

etc

I never used the audio effects so i am not sure about audiostreamstreampitch etc.

**Comment by groud** [comment]
This is what buses are for.

**Comment by Lucrecious** [comment]
@groud I believe buses are for general redirection into the speakers.

The AudioStream are for effects independent of the buses.

For example, I want to randomize the decibels between a a factor of 1.1. I can't redirect into a bus randomly (I'd need many many buses of different decibels), I need to have an AudioStream that plays the sound at a random decibel - much like the AudioStreamRandomPitch.

**Comment by groud** [comment]
No, AudioStream are just meant to play sounds, not to make effects.
I you need an effet on a sound, you redirect it to a specific bus, then you add the effects you want on the bus. You may need to implement a new effet though, probably using GDnative or C++ code.

If you really need something specific, you can implement a class that extends the AudioStream class, but it also requires using C++ or GDnative.

**Comment by Lucrecious** [comment]
@groud Like I said, buses are for more general redirection. If, say, I want all NPC sounds to go through an amplification bus so they're slightly louder than regular sounds. But, if I want to, for example, randomize the amplification coming from a ball bouncing on the ground, I would use an AudioStream to amplify the sound by a random factor.

**Comment by vnen** [comment]
That also could be achieved with a bus effect, it's possible to add a "Random Volume Effect" that you could use. The issue I see is that currently this system it's not extensible, you can't add new effects unless you change the source and recompile the engine.

**Comment by Lucrecious** [comment]
I see.

How come there exists an AudioStreamRandomPitch rather than a "Random Pitch Effect" on the bus then?

Why not have one or the other?

**Comment by mrcdk** [comment]
I'm not really sure what you want, everything you are asking in this issue can be already done with an `AudioStreamPlayer` some code and/or different audio buses and effects.

The reason to why `AudioStreamRandomPitch` (and `AudioStreamPlayer.pitch_scale` in 3.0.1/3.1) exists is because they aren't really affecting only the pitch of the sound but the speed too and this can't be done as an `AudioBus` effect. You can use the `PitchShifter` effect which will only affects the pitch but not the speed in an `AudioBus` without any problems.
