### ISSUE TITLE
Allow controls to grow from their center

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#16546]
**Godot version:** 3

It would be convenient to be able to automatically grow controls from their center, which makes sense when a control's anchors are centered. Currently, the control's position must be offset based on its size to achieve this result. Since there already are GROW_DIRECTION_BEGIN and GROW_DIRECTION_END, something like GROW_DIRECTION_CENTER would resize the control equally in both directions and fit well with PRESET_CENTER.

There was a lot of discussion on this, see #9520, #9889, so I apologize if such a feature was ruled out previously.

**Comment by girng** [comment]
this is really easy already ^^

just do:

Control Node -> Animation Player

create animation and set control's scale to `0.2` and 0 seconds, and `1.0` at 0.5 seconds

but here is the trick, before u do this, click on control and press `v` at the center.

**Comment by DuskKittyIsHotAF** [comment]
very tolerant and nice commnuity imo. run by great leadership skills, you should be proud juan and akien for leading this great floss project!
![](https://i.gyazo.com/2fd0c035013b3c1bb0652552d35fde92.png)
![](https://i.gyazo.com/e0acd22258872330f342d5d189564f1e.png)
![](https://i.gyazo.com/81b238ce283aa55126e3a2f608583837.png)

**Comment by Footurist** [comment]
This works for scaling, but not for growing the actual rectangle, like when font changes...what do I do then?

**Comment by girng** [comment]
Well, if the font is in inside a 2d Node with offset set to the center, the font should scale from the center as well.

**Comment by KoBeWi** [comment]
Isn't it fixed by the PR above?

**Comment by akien-mga** [comment]
Yes, fixed by #16574.
