### ISSUE TITLE
3D collision tests performed on all bodies regardless of layer/mask with GodotPhysics (probably Bullet too)

### ISSUE THREAD

**Issue by nadnam** [godotengine/godot#16541]
**Godot version:**
v3.0-stable_x11.64

**Issue description:**
3D collision tests are performed on bodies that should never collide. Collision pairs are generated _even before_ bodies come near each other, and after bodies intersect. No collision pairs should be generated.

This causes significant performance problem in all cases. Regardless of layer/mask settings, sufficient number of bodies will kill CPU performance even though there should be no tests performed at all.

**Steps to reproduce:**
Run attached project. Surface and cube have different layers/masks set. They should never collide and this is confirmed when cube falls trough surface.  But collision pairs are generated _before and after_ cube makes "contact".
Running with Bullet can't provide more info because performance monitor isn't showing correct values https://github.com/godotengine/godot/issues/16540

**Minimal reproduction project:**
[BugTest.zip](https://github.com/godotengine/godot/files/1713664/BugTest.zip)

**Comment by fracteed** [comment]
Oh damn, just found out about this issue. No wonder I noticed no improvements in my performance when adding everything to layers/masks! I hope this gets some attention before 3.1. Is this also an issue with the native physics, or just bullet?

**Comment by akien-mga** [comment]
CC @reduz @AndreaCatania

**Comment by AndreaCatania** [comment]
This is really strange, I'll test it soon

**Comment by nadnam** [comment]
It's been long ago, but that test program I included displays number collision pairs in window title (or as text on screen, I don't remember).  There is also related bug with bullet where those counters don't work at all.

I don't know how underlying engine works, I assume collision pair **should not** be generated for objects that are prevented to collide by using layer/mask. But they do, and it is the problem that causes too many collision checks. I assume again that once those checks are performed, engine finally checks layer/mask and discards collision, but it is too late as CPU time is used already in vain.

**Comment by AndreaCatania** [comment]
I think that that data are wrong in Godot physics rather that is created a pair...

In bullet the result is 0 because I didn't create the function that update it, I will do to allow more fine optimization.

**Comment by AndreaCatania** [comment]
I'm moving it to 3.2 for now since doesn't seems that bullet create useless pairs

**Comment by madmiraal** [comment]
Fixed with #39399.
