### ISSUE TITLE
Allow scaling of meshes on import

### ISSUE THREAD

**Issue by ShyRed** [godotengine/godot#16557]
**Situation:**
If you are using 3rd party tools like MagicaVoxel for mesh creation, exported meshes to _obj file format_ are usually in a much larger scale than desired (e.g. 1 voxel = 1 unit).

At the moment, in order to use the mesh in _Godot 3.0 stable_ without setting values for scale everywhere you have to import the mesh in Blender, resize it there and export it again so you can use the mesh in Godot.

If you change the original mesh data (= the voxel file in MagicaVoxel), you have to repeat the whole process again as the exported mesh from the original software is too large again.

**Solution:**
Godot should allow you to set a scale in the import properties of a mesh. So everytime a mesh is imported, the mesh vertices are scaled as set in the import properties.

**Comment by DuskKittyIsHotAF** [comment]
very tolerant and nice commnuity imo. run by great leadership skills, you should be proud juan and akien for leading this great floss project!
![](https://i.gyazo.com/2fd0c035013b3c1bb0652552d35fde92.png)
![](https://i.gyazo.com/e0acd22258872330f342d5d189564f1e.png)
![](https://i.gyazo.com/81b238ce283aa55126e3a2f608583837.png)

**Comment by DuskKittyIsHotAF** [comment]
very tolerant and nice commnuity imo. run by great leadership skills, you should be proud juan and akien for leading this great floss project!
![](https://i.gyazo.com/2fd0c035013b3c1bb0652552d35fde92.png)
![](https://i.gyazo.com/e0acd22258872330f342d5d189564f1e.png)
![](https://i.gyazo.com/81b238ce283aa55126e3a2f608583837.png)
