### ISSUE TITLE
Tilemap hotkeys

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#1655]
The (hidden) hotkeys for editing of tilemaps currently are 'a' (x-mirror), 's' (y-mirror), and 'd' (duplicate). It would be nice if there were some shortcuts for rotation (e.g. rotate left/right) and/or transpose.

**Comment by draxdeveloper** [comment]
and a keyboard key to delete, something like ctrl+click
left click in a touchpad od notebook is not easy to use.

2015-04-08 15:01 GMT-03:00 Bojidar Marinov <notifications@github.com>:

> The (hidden) hotkeys for editing of tilemaps currently are 'a' (x-mirror),
> 's' (y-mirror), and 'd' (duplicate). It would be nice if there were some
> shortcuts for rotation (e.g. rotate left/right) and/or transpose.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1655>.
>



-- 
David Aguiar de Aquino Paiva

**Comment by akien-mga** [comment]
See also #2745 for a general-purpose feature request about hotkey listing and redefinition.

**Comment by bojidar-bg** [comment]
I would close this issue, as the other is much more general, and would most likely cover that case as well :smile:
