### ISSUE TITLE
Exported Android App issue, "(app) has stopped"

### ISSUE THREAD

**Issue by LeDernier** [godotengine/godot#16563]
**Godot version:**
Godot 3.0 stable

**OS/device including version:**
OS Win8.1 64b Intel(R) Core(TM) i7-3520M 2.90GHz
Device specs : [https://www.gsmarena.com/wiko_lenny3-8200.php](https://www.gsmarena.com/wiko_lenny3-8200.php)

**Issue description:**
I successfully exported my app (basic app with a panel node and a LineEdit node) but when I run it in android after installing it, It says "(app) has stopped".

Here is the log file I obtained using : `adb logcat "*:E"`
[output.txt](https://github.com/godotengine/godot/files/1714550/output.txt)

**Steps to reproduce:**
Export the project, install it on an Android device and run it.

**Minimal reproduction project:**
[TestExport.zip](https://github.com/godotengine/godot/files/1714555/TestExport.zip)

**Comment by eon-s** [comment]
The GPU Mali-400MP2 does not support OpenGL ES 3.0, requirement for running Godot 3.

**Comment by LeDernier** [comment]
Thank you for the quick answer. I'll close this issue.

**Comment by GDScriptHacker5000LOL** [comment]
lmfao that wasn't a quick answer, took that dude 13 hours.

**Comment by dbenoy** [comment]
I had this problem, too. It doesn't crash gracefully, though. It just silently dumps you out.

Perhaps this should be reopened to add an error message?

**Comment by Brayacon** [comment]
Having the same issue
