### ISSUE TITLE
Add render_mode billboard to spatial shaders.

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#16561]
**Godot version:**
3.0

**Issue description:**

Billboarding should be available when writing custom shaders for spatial materials, not only particle materials.
Currently you can check off a billboarding flag in SpatialMaterial, but there is no render_mode for it when writing your own spatial shader.

When alternatively writing a particle shader, not spatial, since I want render_mode billboard, there is other stuff missing that is usually needed, such as UVs (and in my case the SCREEN_TEXTURE).

Alternatively this could be set on the mesh level, not material, since any mesh in 3D can potentially want to be a billboard.

Goal: Write any kind of 3D shader and have it face the camera.

**Comment by reduz** [comment]
The same you use for particles works for meshes, not sure I get the point..

**Comment by Boothand** [comment]
But how would you go about setting up billboarding if you write your own shader of shader_type spatial?

Alternatively, using UVs and screen texture from a shader_type particle?

**Comment by Calinou** [comment]
This is already supported (see Chaosus' comment), closing.

**Comment by unfa** [comment]
What if I want to use Visual Shader?
How can I achieve billboarding in that case?

**Comment by Chaosus** [comment]
That's a good question - I think, I could add support for them via some new node

**Comment by unfa** [comment]
I'm trying to build this in Visual Shader, but I can't to get it working correctly.
It seems to be doing billboarding, but there's a weird offset along the negative Z axis for some reason:
![image](https://user-images.githubusercontent.com/491704/116012809-22a65f80-a62d-11eb-9281-785be99450c9.png)

**Comment by tomcraven** [comment]
@unfa not pretty but you can create an expression node and pass the output to an unused input in your vertex shader:

![image](https://user-images.githubusercontent.com/5236109/117200926-f7b5cb80-ade3-11eb-8be3-520d1d9d95b8.png)

**Comment by unfa** [comment]
> @unfa not pretty but you can create an expression node and pass the output to an unused input in your vertex shader:
> 
> ![image](https://user-images.githubusercontent.com/5236109/117200926-f7b5cb80-ade3-11eb-8be3-520d1d9d95b8.png)

Oh. That's... interesting. Looks like a hack to me :D Thank you though! If it works, I won't complain!

**Comment by DissonantVoid** [comment]
For anyone like me who realizes that the code provided by Chaosus needs some tweaking in Godot 4. here's what you should write:

`MODELVIEW_MATRIX = VIEW_MATRIX * mat4(INV_VIEW_MATRIX[0],INV_VIEW_MATRIX[1],INV_VIEW_MATRIX[2],MODEL_MATRIX[3]);`
