### ISSUE TITLE
Added fps asset gives: console: get_global_transfrom: condition !is inside tree()

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#16562]
**Godot version:**
Godot 3 stable.

**OS/device including version:**
OS Win8.1 64b gpu AMD R7 series

**Issue description:**
I get error in the console: get_global_transfrom: condition !is inside tree()
I used the fps asset from the assets lib - simple_fpsplayer, link: https://godotengine.org/asset-library/asset/156

The issue seams similar to:
https://github.com/godotengine/godot/issues/14975 and this; https://github.com/godotengine/godot/pull/14977#issuecomment-353731609

**Comment by vnen** [comment]
The mentioned issue is fixed. Are you sure this isn't a problem with the asset itself?

**Comment by Akira1San** [comment]
I dont know. I tried a build from here too http://godot3builds.digitecnology.com/ "Build date: 2018-02-10 12:59:06" and i see the same message. (console: get_global_transfrom: condition !is inside tree())
project test: https://drive.google.com/open?id=1b5MkVq9DUaNFhwK7l4Va8hawcpkiM3F5

**Comment by Alphasoup** [comment]
Apologies if I'm late on this, but I discovered that if you delete the camera in player.tscn and replace it with a new one (with the same built-in script included) the problem goes away.

**Comment by KoBeWi** [comment]
Running the asset in 3.1 doesn't produce any error.
