### ISSUE TITLE
Add proper UV coordinates to fonts/text

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#16564]
**Godot version:**
3.0

**Issue description:**

When writing shaders, it can be desirable to write shaders for text, to deform and operate on fragments and so on. However, they don't appear to have any UV coordinates set up, so operating on them with the fragment shader in this way isn't possible.

Intention: Write fragment shaders for text as you would do for any quad, screen or 3D model.

**Comment by Zylann** [comment]
That's weird... Without UV, text would not even render, because characters are quads with a texture on them (sub-rectangle of an atlas).

**Comment by Calinou** [comment]
Closing in favor of #23210, which describes the issue more accurately.
