### ISSUE TITLE
List of scenes

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#1657]
It would be great to have a list of scenes, they don't have to be opened, just for faster access.
Thanks.

**Comment by reduz** [comment]
planned for 1.2

**Comment by akien-mga** [comment]
"Quick Open Scene" aka Shift+Ctrl+O already gives a list of all existing scenes in the project. Is it enough to consider this issue solved, or did @reduz have some more specific in mind for 1.2 aka 2.0 now?

**Comment by alketii** [comment]
Thanks for the tip @akien-mga , this is also great, but probably a big list (like scripts) can be good too.

**Comment by vnen** [comment]
There's also "Quick Open Script" (`Alt+Ctrl+O`) and "Quick Search File" (`Alt+Ctr+P`), all of those available in the Scene menu. Not to mention the FileSystem panel (even though it still requires some changes for better usability).
