### ISSUE TITLE
Crash on Mac with Intel HD Graphics 530

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#16572]
**Godot version:**

3.0 stable

**OS/device including version:**

Mac OS

**Issue description:**

crashed

[report.txt](https://github.com/godotengine/godot/files/1715136/report.txt)

**Steps to reproduce:**

**Minimal reproduction project:**

[runner.zip](https://github.com/godotengine/godot/files/1715139/runner.zip)

**Comment by groud** [comment]
Can you give a little bit more explanation? What were you doing when the crash happened?

**Comment by DuskKittyIsHotAF** [comment]
very tolerant and nice commnuity imo. run by great leadership skills, you should be proud juan and akien for leading this great floss project!
![](https://i.gyazo.com/2fd0c035013b3c1bb0652552d35fde92.png)
![](https://i.gyazo.com/e0acd22258872330f342d5d189564f1e.png)
![](https://i.gyazo.com/81b238ce283aa55126e3a2f608583837.png)

**Comment by alexzheng** [comment]
It mostly crashed when I try to click  the open in editor menu for Player. But not always.

**Comment by groud** [comment]
From the log it seems that you have an Intel HD Graphics 530.
Thus, it's probably related to #16576.

**Comment by mhilbrunner** [comment]
@alexzheng May be relevant, may be not: Which Mac OS X version are you using?

**Comment by alexzheng** [comment]
10.13.3 (17D47)
Yes, I have Radeon Pro 460 4 GB and Intel HD Graphics 530 1536 MB

**Comment by Calinou** [comment]
@alexzheng Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
