### ISSUE TITLE
Auto-cast from float to integer

### ISSUE THREAD

**Issue by BBric** [godotengine/godot#1658]
Hello, it could be useful to be able to use a float without decimals as an integer in two cases :
- modulo -> Error with 5.0 % 2
- Dictionary keys -> my_dict[5] != my_dict[5.0]

These errors are hard to find/avoid in a top-level language.

**Comment by WatIsDeze** [comment]
Have you tried using the round(5.0) function? It seems to be that comparing 5 to 5.0 should never be automated with conversions. If it is being done so, a warning should be thrown like most compilers do.

Just my five cents, since essentially we are truly entering 2 diff values. Being a bit rusty on floating point math I also recall even if you enter 5.0, the exponential values will probably not be 0 after the first 0.

Maybe this answers your question, or not at all.

**Comment by BBric** [comment]
Not sure to understand, may be that in some cases it would be a problem but not in all i suppose. The functions round(), floor() and ceil() could equally return an integer. The return's type of min() and max() correspond to their arguments, thus it should be possible.

**Comment by WatIsDeze** [comment]
Well the point is simply that strictly speaking you are entering different values. So this feature request, to me, seems like possibly something that would break the language, in a sense it makes the rules diff vs most languages.

Other than that, your example is speaking about user input. And as such, you can just enter 5 yourself. If you are speaking about real variables, as such, my_dict[my_float_var] then you can indeed, round/ceil/floor it :)

I'm not trying to hate, but it seems rather useless to me from a programmer POV.

**Comment by BBric** [comment]
These functions return a float, so if the type of the keys is int, two values can be created for the "same" (semantically) key. The result must be converted to int before. In python 5 and 5.0 are the same keys. When this behavior is in mind, it is easy to avoid an error of course, but it is easy to forget it too between multiple other things.
Thank you for the comments.

**Comment by WatIsDeze** [comment]
I think the documentation is mistaken with the float, actually using round(float_variable) does return an int, in fact it states: 

"round

float round ( float s )
Round to nearest integer."

Simply put, having tested it, it actually makes comparing floats with integers possible. So it's actually noteworthy now that you mentioned it.

**Comment by UsernameIsAReservedWord** [comment]
@WatIsDeze : 
You're wrong. 
`round()` returns float. "To the nearest integer" just mean the decimal part is removed. 
`round(3.14)` will return `3.0`
If you want to convert float to int, then use `int(3.14)` that will return `3`

**Comment by WatIsDeze** [comment]
@UsernameIsAReservedWord that's quite an interesting difference versus most languages, but I appreciate you clearing it up.

I've never seen floating point comparison work out of the box, aka 3.0 never is strictly 3.0.

Any specific reasons as to why this is?

**Comment by UsernameIsAReservedWord** [comment]
@WatIsDeze : to get a better understanding, you can read the C++ source code of Godot.

**Comment by akien-mga** [comment]
I don't see anything to implement here, adding a hack so that `5.0` is interpreted as `5` would only lead to confusion and weird bugs. For the two cases mentioned in the OP, you should use `int(5.0)`.
