### ISSUE TITLE
File Format '0.1.1' is too new! For Android

### ISSUE THREAD

**Issue by sanchitgulati** [godotengine/godot#1660]
Running from latest commit, project works fine on mac osx but on porting it to Android.
"File Format '0.1.1' is too new! Please upgrade to a a new engine version"

I got it to work by saving the scene as  XML and manually changing the <resource_file version="1.1"> to <resource_file version="1.0">.
But that's not the ideal way, hence the issue generated.

**Comment by reduz** [comment]
the check was put to avoid accidentally open a scene with a previous engine
version.

your export templates for Android are likely outdated

**Comment by sanchitgulati** [comment]
I compiled a custom export template from the latest commit.
works fine on every other platform except for android.

**Comment by reduz** [comment]
i haven't had any other reports on this, I'm pretty sure for some reason the template apk is outdated, but will try to reproduce when i have some time

**Comment by ScyDev** [comment]
I've got the same problem with an Android APK I just now built from source:

I/godot   (29085): ERROR: load: Condition ' err!=OK ' is true. returned: RES()
I/godot   (29085):    At: core/io/resource_loader.cpp:136.
I/godot   (29085): ERROR: load: Failed loading resource: res://Start Scene.xscn
I/godot   (29085):    At: core/io/resource_loader.cpp:209.
I/godot   (29085): ERROR: start: Failed loading scene: res://Start Scene.xscn
I/godot   (29085):    At: main/main.cpp:1263.
I/godot   (29085): ERROR: open: File Format '2.0' is too new! Please upgrade to a a new engine version: res://Start Scene.xscn
I/godot   (29085):    At: core/io/resource_format_xml.cpp:1685.

**Comment by okamstudio** [comment]
export templates must be updated

On Sat, Sep 26, 2015 at 8:29 AM, ScyDev <notifications@github.com> wrote:

> I've got the same problem with an Android APK I just now built from source:
>
> I/godot (29085): ERROR: load: Condition ' err!=OK ' is true. returned:
> RES()
> I/godot (29085): At: core/io/resource_loader.cpp:136.
> I/godot (29085): ERROR: load: Failed loading resource: res://Start
> Scene.xscn
> I/godot (29085): At: core/io/resource_loader.cpp:209.
> I/godot (29085): ERROR: start: Failed loading scene: res://Start Scene.xscn
> I/godot (29085): At: main/main.cpp:1263.
> I/godot (29085): ERROR: open: File Format '2.0' is too new! Please upgrade
> to a a new engine version: res://Start Scene.xscn
> I/godot (29085): At: core/io/resource_format_xml.cpp:1685.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1660#issuecomment-143423564>.
>



-- 

*OkamStudio*

**Comment by ScyDev** [comment]
In my case, the problem was that the export templates weren't actually built!
After the build process, the templates are copied from the "bin" directory to the "templates" directory.
I had old files lying around in the "bin" directory and when they were copied they got a new timestamp so I thought these were fresh templates, when in fact the build was terminated with errors.

**Comment by okamstudio** [comment]
Hmm maybe I could generate md5 strings out of the templates when built and
att them to the editor so it can actually tell if the files are the right
ones and, at most, show a warning or error.


On Sat, Sep 26, 2015 at 8:53 AM, ScyDev <notifications@github.com> wrote:

> In my case, the problem was that the export templates weren't actually
> built!
> After the build process, the templates are copied from the "bin" directory
> to the "templates" directory.
> I had old files lying around in the "bin" directory and when they were
> copied they got a new timestamp so I thought these were fresh templates,
> when in fact the build was terminated with errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1660#issuecomment-143426255>.
>



-- 

*OkamStudio*

**Comment by ScyDev** [comment]
Actually I thing the error message is clear enough. It was my error for thinking I had new templates.

**Comment by kubecz3k** [comment]
Archiving since it looks like the problem is solved, feel free to open new one if the problem still occur.
