### ISSUE TITLE
Update docs on range() function

### ISSUE THREAD

**Issue by nadnam** [godotengine/godot#16639]
**Godot version:**
3.0

**Issue description:**
Only by an accident I discovered that in GDScript:

```
for i in 3:
    print(i)
```

is same as

```
for i in range(3):
    print(i)

```
It is not mentioned in docs anywhere. Is this correct behavior that will stay in future? Are there any performance differences here (big arrays, iterators etc.)?

**Comment by Chaosus** [comment]
_Its GDScript documentation issue about alternative raw syntax of `for` loop(I dont think `range` is valid target in that case), it must be posted in corresponding repository - https://github.com/godotengine/godot-docs
 I push the fix to docs -  https://github.com/godotengine/godot-docs/pull/1695, hopefully this is enough to fix this issue. Closed by bugsquad._

**Comment by Chaosus** [comment]
As discussed, this syntax is inappropriate and should be avoided. In next versions Godot may remove it completly.
