### ISSUE TITLE
Bug with side scroll bar in the script tab of the editor

### ISSUE THREAD

**Issue by fry-** [godotengine/godot#1663]
Built on 07 April 2015
OS: Fedora 21

The side scroll bar within the script tab of the editor seems to have a limit at 70 columns even when the code line is longer. You can only access columns > 70 if you mark and drag the code with the mouse or by maximizing the window.
When maximizing, the side-scroll bar disappears completely. If the code line is bigger then the screen, you have to use above mentioned method with the mouse.
Little demo video:
https://youtu.be/eaTYeD1iIws

**Comment by BBric** [comment]
There is also a problem with the vertical scrollbar, its position is not always correctly restored during a tab change, and otherwise it's not possible to select and scroll in the same time.

**Comment by akien-mga** [comment]
I can't reproduce this issue in the current master branch (on Linux X11), so I'll assume it is fixed. Feel free to reopen or ask me to reopen if you can still reproduce it (it might be platform-dependent).
