### ISSUE TITLE
Assetlib contents not reliably accessible from China 

### ISSUE THREAD

**Issue by flashice2030** [godotengine/godot#16643]
Hardly to open Assetlib  in Godot3 , No matter PC  or Steam version  in the region of China , But Godot2 seems normal.

**Comment by Omicron666** [comment]
Could you be more specific, Assetlib is empty ?
Before opening a project ?

**Comment by flashice2030** [comment]
Assetlib is empty always in the version Godot3 on steam ,but switch godot2  the content cann't be seen in assetlib. The downloadable version seems better, but displayed content slowly,sometime Godot 3 seems no responsible when I type a letter in the search column.

**Comment by flashice2030** [comment]
Godot 2.0  is  ok, Assetlib content can be displayed faster than 3.0

**Comment by Calinou** [comment]
I doubt much can be done about this unless someone offers to host a mirror of the asset library (and GitHub assets) in China.

**Comment by flashice2030** [comment]
I don't know why but now I can see the content in the assetlib.

At 2018-02-13 03:09:48, "Hugo Locurcio" <notifications@github.com> wrote:


I doubt much can be done about this unless someone offers to host a mirror of the asset library (and GitHub assets) in China.

**Comment by Chaosus** [comment]
Maybe this would fix it(after merge) - https://github.com/godotengine/godot/pull/16519

**Comment by Calinou** [comment]
@Chaosus Replacing the SSL library won't fix this issue.

**Comment by Omicron666** [comment]
While inside editor, displaying AssetLib pages is almost instant.
But before opening any project, the AssetLib seems slower, images are displayed quite progressively (in their order of listing).
I would just speculate content is downloaded sequentially.

**Comment by flashice2030** [comment]
It seems better now, thanks for fixing

At 2018-02-14 01:33:47, "Yuri Roubinski" <notifications@github.com> wrote:


Maybe this would fix it(after merge) - #16519

**Comment by Calinou** [comment]
This appearts to have been fixed since this was reported. Either way, bugs related to the asset library itself should be reported [here](https://github.com/godotengine/asset-library.git), not on the main engine repository.
