### ISSUE TITLE
I cann't  find Tilemap from Tiled Editor in Godot3.0

### ISSUE THREAD

**Issue by flashice2030** [godotengine/godot#16646]
This is a tiled map editor plugin, After install it  in Godot 2.0 it will be under  Import -> Tilemap from Tiled Editor . But In Godot3.0 where could I find it?

**Comment by volzhs** [comment]
not sure there is importer for it, but anyway, did you try to just copy it in to project directory?

**Comment by vnen** [comment]
Plugins for Godot 2 won't work on Godot 3, you need a new version of the plugin.

**Comment by groud** [comment]
This is outside the scope of the engine itself. Please ask to the plugin maintainer to update the plugin for 3.0.

**Comment by groud** [comment]
Arf lol, just figured out it was you @vnen.
@flashice2030  You have to install this plugin for 3.0: https://github.com/vnen/godot-tiled-importer

**Comment by flashice2030** [comment]
Yes , I've already installed it through the assetlib, I mean how to use it after I installed.

At 2018-02-13 00:38:43, "Gilles Roudiere" <notifications@github.com> wrote:


Arf lol, just figured out it was you @vnen.
@flashice2030 You have to install this plugin for 3.0: https://github.com/vnen/godot-tiled-importer

**Comment by Noshyaar** [comment]
https://github.com/vnen/godot-tiled-importer#usage-once-the-plugin-is-enabled

**Comment by flashice2030** [comment]
thanks ,I 'll take a look into it.

在 2018-02-13 11:42:09，"Poommetee Ketson" <notifications@github.com> 写道：


https://github.com/vnen/godot-tiled-importer#usage-once-the-plugin-is-enabled
