### ISSUE TITLE
Editor: Spanish version with English text

### ISSUE THREAD

**Issue by jjmontes** [godotengine/godot#16642]
**Godot version:**
v3.0.stable.official

**OS/device including version:**
Ubuntu 17.10

**Issue description:**
The contextual help into "Crear Nuevo Node" (Create new node) window is in English, when I use Spanish version (es_AR)
I am using Spanish version (es_AR). When I open "Crear Nuevo Node" (Create new node) window and see the contextual help, its appear in English.

**Steps to reproduce:**
1- Open Godot Editor
2- Select es_AR language
3- Open / Create one scene
4- Push "Add a new node" button
5- Point some node, the help is in English.

**Minimal reproduction project:**
![godot v3 translate create new node contextual help - 001](https://user-images.githubusercontent.com/576414/36100951-b2f2cd02-0fe6-11e8-971f-75fd9bd0b701.png)
![godot v3 translate create new node contextual help - 002](https://user-images.githubusercontent.com/576414/36100952-b3165f24-0fe6-11e8-9bd5-05084e3d528d.png)
![godot v3 translate create new node contextual help - 003](https://user-images.githubusercontent.com/576414/36100953-b33b55fe-0fe6-11e8-94b3-04faf7d1fcf4.png)

**Comment by groud** [comment]
That's normal, that happens because the translation is not complete. This is not really a technical issue so I close it.
If you want to contribute to the spanish documentation you can use the [weblate](https://hosted.weblate.org/projects/godot-engine/godot/es/). :)

**Comment by Hinsbart** [comment]
Well, the spanish translation seems quite complete actually. But the translation is currently only for the editor.
These particular tooltips are taken from the documentation, which is not translated at all currently. The focus for now is to complete the english documentation first and start translating it when it's in a good state.

**Comment by groud** [comment]
> These particular tooltips are taken from the documentation

Oh, I did not know that. Thanks :)
