### ISSUE TITLE
CollisionShape resize gizmos not interactable when the parent object is scaled

### ISSUE THREAD

**Issue by silverweed** [godotengine/godot#16640]
**Godot version:**
Both 3.0.stable.official and 3.0.stable.custom_build (from AUR)

**OS/device including version:**
ArchLinux (4.15.1-2-ARCH) / Nvidia Geforce GTX 960M
ArchLinux (4.14.13-ARCH) / Nvidia Geforce 840M
Tried both with and without `optirun` with the same results.

**Issue description:**
*Happened*: dragging the Collision Shape resize gizmos of a composite object (StaticBody+CollisionShape+MeshInstance) sometimes gives no result. The gizmos themselves appear to be ignored by the mouse. This appears to happen only when the parent object is scaled.

[video](https://thumbs.gfycat.com/FaintUnderstatedElk-mobile.mp4)

*Expected*: the Collision Shape gets resized via the gizmo.

**Steps to reproduce:**
* Create a new scene
* Add a StaticBody as root
* Add a CollisionShape to it as a child
* Add a MeshInstance to the StaticBody as a second child
* Scale the StaticBody on at least one dimension for a reasonable amount
* Select the CollisionShape and try to grab the gizmo dots: chances are at least one of them isn't interactable (probably the one along the scaled dimension) 

**Minimal reproduction project:**
[collisionshapegizmotest.zip](https://github.com/godotengine/godot/files/1716401/collisionshapegizmotest.zip)

**Comment by DualMatrix** [comment]
Tested in master, all dots were interactable.

**Comment by akien-mga** [comment]
Thanks for testing, closing as fixed.
