### ISSUE TITLE
Godot editor crashes when display drivers crash

### ISSUE THREAD

**Issue by solidmoose** [godotengine/godot#16641]
**Godot version:** 3.0

**OS/device including version:** Windows 7 64 bit, GTX 1070 (ASUS), driver version 390.77

**Issue description:** When my display drivers crash and recover, the Godot editor will crash with no possibility of recovery. There is no "wait for program to respond" option, the application MUST close.

**Steps to reproduce:**

1. Open a project in Godot.
2. Crash & recover your display drivers. Godot will now have crashed.

**Minimal reproduction project:** Any project, including empty projects.

Thanks all.

**Comment by mhilbrunner** [comment]
How do you manage to reliably crash your display drivers?

**Comment by groud** [comment]
Well if your drivers that's normal Godot crashes too.

**Comment by Chaosus** [comment]
I doubt that even Unity or Unreal can handle this

**Comment by eon-s** [comment]
I do not think Godot can recover of that because depends heavily on GPU, is better to solve the driver crash (usually related to broken drivers or faulty GPU/Power supply).

**Comment by akien-mga** [comment]
Most applications using the GPU will crash if the GPU drivers crash, there's no way around it. Adding CPU checks that the GPU is accessible *every time* we try to access it would just kill performance and completely defeat the point of having a GPU.
