### ISSUE TITLE
TileMap tiles in editor is out of id order

### ISSUE THREAD

**Issue by falquinho** [godotengine/godot#16645]
**Godot version:** 3.0 official

**OS/device including version:** Ubuntu 17.10

**Issue description:**

TileMap node show tiles out of order in specific case. They show tiles ordered alphabetically, wich is different from id ordering.

**Steps to reproduce:**
Create a TileSet with nodes named Tile0 - Tile11
You wil notice that they appear on the TileMap in the order: Tile0, Tile1, Tile 10, Tile 11, Tile2 ...

Problem is you would think Tile10 is id 2, since its the third in the list. But its id 10.
Its not the worst problem in the world, but its a bit confusing.

**Minimal reproduction project:**

**Comment by Zylann** [comment]
This is what happens with any kind of alphabetic ordering (even in your file explorer). A workaround is to add zeros.

**Comment by flashice2030** [comment]
I have the same issues ,  I make a tiledmap with tiledmap editor ,reimport shows  different tile in godot scence.

**Comment by flashice2030** [comment]
how to  disable alphabetic ordering of tiles?

**Comment by bojidar-bg** [comment]
Here is how:
![image](https://user-images.githubusercontent.com/5276727/36593982-ea662c22-18a4-11e8-82c6-67dbe3b9ea99.png)
* Go to Editor -> Editor Settings -> Editors -> Tile Map -> "Sort Tiles By Name"
* Uncheck it

**Comment by falquinho** [comment]
That's awesome. Thank you!

**Comment by flashice2030** [comment]
thanks ,too.

在 2018-02-23 22:20:55，"Lucas Falcão de Nantua Bessa" <notifications@github.com> 写道：


That's awesome. Thank you!
