### ISSUE TITLE
Changing a directory/folder's case causes "A file or folder with this name already exists." error

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#16644]
True story, Godot 3.0

Example: `Gun/` -> `gun/` + error

**Comment by eon-s** [comment]
I'm not sure if I understand the description, but looks like a duplicate of #16384

**Comment by vnen** [comment]
Yes, it's a duplicate.

**Comment by vnen** [comment]
Also, this is a platform-specific issue, that's why we ask for the OS in the issue template...

**Comment by JarLowrey** [comment]
Sorry about that. It is a duplicate, Win10
