### ISSUE TITLE
Imported curve from Blender is not closed.

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#16658]
When I create a spline/curve in blender and import it into Godot 3.0 its no longer a closed spline but open at the last segment. I am not sure if this is a Bettercollada issue or Godot import issue.

Blender version: 2.79
BetterCollada: Latest commit 836241a (downloaded yesterday)
 
**Godot version:**
3.0 stable

**OS/device including version:**
Win10

**Issue description:**
Expected to see a closes curve, but the last "step" of the curve is open.

**Steps to reproduce:**
Create a closed curve in blender and export it using bettercollada.

![blendercurvegodotexport](https://user-images.githubusercontent.com/24936603/36148649-0143b774-10bd-11e8-8f0f-fe6de11e79fa.jpg)

**Comment by Calinou** [comment]
@jesperkondrup Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by jesperkondrup** [comment]
@Calinou Yes I am still able to reproduce this using Blender 2.82, Better Collada Exporter and Godot 3.2.1 stable. 

![image](https://user-images.githubusercontent.com/24936603/84006023-596c7c00-a96e-11ea-8603-54987c8b551e.png)
