### ISSUE TITLE
Multitouch Event "InputEventScreenDrag" not triggered

### ISSUE THREAD

**Issue by DionHo** [godotengine/godot#16651]
**Godot version:**
3.0 stable

**OS/device including version:**
Android

**Issue description:**
When using a multitouch screen on Android, no "InputEventScreenDrag" are triggered. Therefore I am unable to track the finger movement on the screen.

**Steps to reproduce:**
Create a RichTextLabel with the following script and try to drag your finger over the touchscreen. You only see Touch Events and no Drag Events.

```
extends RichTextLabel

var touch = {}
var drag = {}

func _ready():
	set_process(true)
	set_process_input(true)

func _input(event):
	if event is InputEventScreenTouch:
		if event.is_pressed():
			touch[event.index] = [event.pressed,event.position]
		else:
			touch.erase(event.index)
	if event is InputEventScreenDrag:
		if event.is_pressed():
			drag[event.index] = [event.pressed,event.position,event.relative,event.speed]
		else:
			drag.erase(event.index)

func _process(delta):
	var touch_state = ""
	touch_state = "Touch Events: \n"
	touch_state += String(touch)
	touch_state += "\n\nDrag Events:\n"
	touch_state += String(drag)
	
	clear()
	add_text(touch_state)
```

**Comment by volzhs** [comment]
There is no `pressed` state for `InputEventScreenDrag`
it should be something like this.

```gdscript
extends RichTextLabel

var touch = {}

func _input(event):
	if event is InputEventScreenTouch:
		if event.is_pressed():
			touch[event.index] = [event.pressed,event.position]
		else:
			touch.erase(event.index)
	if event is InputEventScreenDrag:
		touch[event.index] = [event.pressed,event.position]

```

**Comment by DionHo** [comment]
Thank you for the help. I corrected the code and had to additionally remove the "event.pressed" readout from the InputEventScreenDrag. Then it works as expected.
