### ISSUE TITLE
Order of open scripts in the Scripts Panel, is not saved when closing the editor

### ISSUE THREAD

**Issue by RabbitB** [godotengine/godot#16655]
**Godot version:**
Godot 3.0 Stable Win64

**OS/device including version:**
Windows 10 Pro - Build 15063.850

**Issue description:**
I'm a big fan of composition over inheritance, so when I'm developing a feature, I usually have multiple scripts open simultaneously, each handling their own little domain of the feature or functionality. To help keep track of the open scripts, I usually reorder them in the `Scripts Panel`, from widest to narrowest scope, with scripts grouped together if one belongs to another.

![image](https://user-images.githubusercontent.com/6007524/36144131-f3e85342-1061-11e8-809b-6106fe2f1e0a.png)

I've noticed that although Godot happily allows you to reorder these scripts, and remembers which scripts were open when you restart the editor, it doesn't remember the order they were in. This requires me to reorder all the scripts, every time I launch the editor.

**Steps to reproduce:**
1) Open the editor
2) Create multiple scripts and open them
3) Order them in a way you'll remember their order
4) Restart the editor and check their order in the `Scripts Panel`

**Comment by vnen** [comment]
Is the "sort scripts" setting disabled in the editor settings?

**Comment by RabbitB** [comment]
@vnen I don't think it can be turned off. It only has two options in the drop-down. By name and by path.

**Comment by vnen** [comment]
I was pretty sure there was a way to disable. There really should be one.
