### ISSUE TITLE
Not all colors changed in graph editor, when theme switch from dark to light(or light to dark)

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#16662]
**Godot version:**
3.0

**OS/device including version:**
no matter

**Issue description:**
Incorrect colors

![image](https://user-images.githubusercontent.com/3036176/36163615-e9ed105a-10fa-11e8-811a-9e13b8f9bd1c.png)

**Steps to reproduce:**
Change the theme to light, change the theme to dark

**Comment by Noshyaar** [comment]
The question is, should the editor be restarted after a theme change?

**Comment by Chaosus** [comment]
Ah, no, it begin invalid even wtihout restart

**Comment by Noshyaar** [comment]
Yes. But restarting fixes it. There are two ways to solve this:
- Fix it properly. Change icons/colors accordingly. Users can still use the editor without restarting.
- Just a warning text that says you should restart the editor.

**Comment by bojidar-bg** [comment]
I prefer 1), since most other things work flawlessly already. Probably it is just a missing NOTIFICATION_THEME_CHANGED handler.
