### ISSUE TITLE
Failed to export to Html5

### ISSUE THREAD

**Issue by NedJaims** [godotengine/godot#16664]
**Godot version:**
Godot 3.0 stable

**OS/device including version:**
Windows 10

**Issue description:**
When I export to Html5 it gives me the following bug: "Failed loading file 'tmp_export.wasm'".

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Might be related to #16274.

**Comment by eska014** [comment]
Check out the documentation: [Starting exported games from the local file system](https://godot.readthedocs.io/en/3.0/getting_started/workflow/export/exporting_for_web.html#starting-exported-games-from-the-local-file-system). On Chromium browsers, you have to use a local web server for debugging. We have issue #16245 open for simplifying that.
For now, you can set Firefox as default browser if you want to use the HTML5 debug button in the editor.
