### ISSUE TITLE
RichTextLabel option to forced line break before long words that would escape the label area

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#1666]
If a word in the Rich Text Label too long, longer than the width of the frame and without spaces, a part which overlooks beyond the bounds is not transferred to the new line of forcibly, and it is as it is impossible to read. But now I'm important that it is transferred, even if the word is very long and without spaces.
But I also think that it is important to keep both features, because I can see how one would apply and such an effect that is there now, and it is therefore possible solution is to make the function toggle between which you can switch including forced transfer of long words, and turn it off.
Thank U!

**Comment by reduz** [comment]
haven't seen the richtextlabel code in a while, but will give it a try

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment]
Ping.

**Comment by akien-mga** [comment]
Looks fixed.
![spectacle m29738](https://cloud.githubusercontent.com/assets/4701338/16996848/4907a728-4eb3-11e6-8374-2b2a46dae713.png)
