### ISSUE TITLE
InputEventMagnifyGesture doesn't output anything as text.

### ISSUE THREAD

**Issue by dunyakilavuz** [godotengine/godot#16661]
**Godot version:**
Godot 3 Mono Stable Mac OS x64

**OS/device including version:**
Mac OS High Sierra 10.13.3

**Issue description:**
When I try to output InputEvents as text, I've seen that InputEventMagnifyGesture event does not output anything on MacBook touchpad, though the event itself is registered.

**Steps to reproduce:**
Run this code on your _Process() function, make pinch zoom gesture on your touchpad.

```
public override void _Input(InputEvent @event)
{
        GD.Print("Event: " + @event.AsText());
}
```
You should see that it registers the event but only outputs `Event:   `

I did a quick research before submitting this issue but if I missed any, my apologies.

**Comment by bojidar-bg** [comment]
It is simple -- InputEventMagnifyGesture and InputEventPanGesture just don't override the `as_text` method.

For potential contributors:
* Add `virtual String as_text() const;` to InputEventMagnifyGesture and InputEventPanGesture in [`core/os/input_event.h`](https://github.com/godotengine/godot/blob/master/core/os/input_event.h)
* Implement the methods added in [`core/os/input_event.cpp`](https://github.com/godotengine/godot/blob/master/core/os/input_event.cpp)
