### ISSUE TITLE
Exported game with multiple audio buses fails to run

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#16676]
**Godot version:**
Godot3-stable-official

**OS/device including version:**
linux, windows, windows VM running on linux, wine

**Issue description:**
Game runs in editor but packaging the game up for linux or windows and then running the resulting build exits with an error that appears related to the default_bus_layout file (I have multiple audio buses).

> ERROR: _load_settings_binary: Method/Function Failed, returning: ERR_FILE_CORRUPT;
>    At: core/project_settings.cpp:415.
> OpenGL ES 3.0 Renderer: GeForce GTX 1050/PCIe/SSE2
> GLES3: max ubo light: 409
> GLES3: max ubo reflections: 455, ubo size: 144
> ARVR: Registered interface: Native mobile
> ERROR: open: res://default_bus_layout.tres:1 - Parse Error: Expected '['
>    At: scene/resources/scene_format_text.cpp:838.
> ERROR: load: Condition ' err != OK ' is true. returned: RES()
>    At: core/io/resource_loader.cpp:149.
> ERROR: _load: Method/Function Failed, returning: RES()
>    At: core/io/resource_loader.cpp:186.
> 

**Steps to reproduce:**
Created a project. Added a few Audio Buses, add a few effects. Export the project (tested linux builds and window builds). 

Attached my default_bus_layout.tres file (renamed to txt for github) - never manually edited, only changed using the editor Audio tab.
[default_bus_layout.txt](https://github.com/godotengine/godot/files/1722247/default_bus_layout.txt)

**Comment by dodgyville** [comment]
Using the same default_bus_layout.tres in an empty project builds on linux OK (using tip)

**Comment by dodgyville** [comment]
I'm wondering if there is a file in the project directory that is being included in the .pck file that can't be parsed. Is there a way to check?

**Comment by dodgyville** [comment]
OK, so if I use "Export selected resources" the game runs, which suggests there is a rogue file that is choking the whole thing. It's not default_bus_layout.tres, even though that is what is reported on the command line.

Manually selecting the resources is a pain though -- there's hundreds of files in this game and they have to be selected individually. Sob

**Comment by dodgyville** [comment]
I have tracked the problem down to two texture jpgs. There are part of a set of four attached to a DAE. They load fine in the editor and in the gimp and were generated the same way as all the other DAE models in the game. Deleting the jpg.import files so they reimport does not fix the problem.

**Comment by dodgyville** [comment]
The error on Linux is slightly different to windows build on wine.

```
ERROR: _load_settings_binary: Corrupted header in binary project.binary (not ECFG)
   At: core/project_settings.cpp:415.
ERROR: open: res://default_bus_layout.tres:1 - Parse Error: Expected '['
   At: scene/resources/scene_format_text.cpp:838.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:149.
ERROR: _load: Failed loading resource: res://default_bus_layout.tres
   At: core/io/resource_loader.cpp:186.


```

**Comment by dodgyville** [comment]
So I copied the DAE and textures to a new project and it built and ran... So now I have no idea. Is there some way to rebuild or force a check on a large project that all imports are clean?

**Comment by vnen** [comment]
> Is there some way to rebuild or force a check on a large project that all imports are clean?

You can delete the `.import` folder and then open the editor. Everything will be re-imported (it may take a while if there's many files).

**Comment by yanorax** [comment]
I ran into a similar issue when exporting my project with multiple audio buses: #15771  

You can try to load a copy of the bus layout in your script as a workaround. It allowed me to run the exported game without audio problems.

**Comment by reduz** [comment]
Given #15771 was closed and was most likely the same bug as this, closing this one too.
