### ISSUE TITLE
Full screen mode breaks maximized window

### ISSUE THREAD

**Issue by donotmakegames** [godotengine/godot#16672]
**Godot version:**
3.0 Release

**OS/device including version:**
Windows 10 64bit build 16299

**Issue description:**
Entering full screen mode (Shift-F11) and then exiting full screen mode causes the editor window to de-maximize on windows 10.

**Steps to reproduce:**
- Open any project
- Maximize Godot window
- Enter full screen (Shift-F11)
- Exit full screen

![breaking maximize](https://user-images.githubusercontent.com/11431120/36179883-0c2a62d0-10d3-11e8-8c21-ee6084c9cca9.png)

**Comment by Chaosus** [comment]
Same for Linux/X11, @akien-mga is it intended behavior ? The problem is in OS.set_window_fullscreen for various platforms

**Comment by akien-mga** [comment]
>  is it intended behavior ? 

No.

**Comment by letheed** [comment]
Just hit this as well on Ubuntu 18.04 with 3.0.3. This used to work fine on 3.0.2 so this is a regression.

**Comment by Chaosus** [comment]
For Windows this issue is fixed by me, for Linux its still present (checked on Linux Mint) - I know WinAPI but unfortunately, I don't have any experience with X11 system. Maybe some experienced Linux developer can fix this issue completely.
