### ISSUE TITLE
Godot have problems importing files in not-idexed units.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#16670]
I search 

**Godot version:**

Godot 3 stable 64 bit and 32 bit

**OS/device including version:**

Win 7 64 bit

**Issue description:**

Issue from this: #16313 (Godot do not import files when runing)

I do a lot of test. Problem is that i can not import files in projects located in any fat32 pendrive. If i copy that project to desktop and open, import works. If i copy any working project in any fat32 pendrive, import files fails (project open and runs, file is copied but not imported until editor restart). Is not a problem of unit letters (C: Hardisk E: skipped, F: pendrive, I: Harddisk J: hardisk M: pendrive, G H K and L other things). I try all posible configuration... Import files in project only works when project is not in a FAT32 pendrive... (It can be any other thing but i try a lot of things....)

(Edit: In Godot2 I always work from pendrive and drag files to working directory always allows to me to work with them without restart editor)

**Steps to reproduce:**
Copy a godot3 project in a fat32 pendrive, open project and try to drag and drop any file to filesystem dock. If it works, you give me a dissatisfaction... 

**Minimal reproduction project:**

Not necesary, is not releated with specific project.

**Comment by fire** [comment]
In other projects, the consensus we had was to switch to the exfat, or ntfs filesystems on the pen drive. I'm not sure how to fix this.

**Comment by Ranoller** [comment]
I'm right with someone confirming me the bug to stop testing

**Comment by fire** [comment]
It wasn't godot though, sorry.

**Comment by Ranoller** [comment]
Sad to read... I`m testing in other computer and problem is there. So I maintain opened the issue until cause is discovered.

**Comment by Ranoller** [comment]
More users report:
https://github.com/godotengine/godot/issues/28268

**Comment by KoBeWi** [comment]
So I just tried a FAT32 pendrive on Windows 10 and everything works fine (in 3.2.2 at least).
@Ranoller Can you still reproduce this issue in 3.2.2?

**Comment by Ranoller** [comment]
It´s fixed, thanks.
