### ISSUE TITLE
Feature Proposal: Support for 3d model animation channels

### ISSUE THREAD

**Issue by zspinelli** [godotengine/godot#16674]
In some games I have done research on for learning workflow, the 3d animation systems support multiple animation channels per mesh specified in a script. This allows multiple animations to be played simultaneously in order to create more complex movements using a smaller library of animations.

Support for an analogous feature would be a wonderful improvement to Godot's OOTB 3d capability.

**Comment by Calinou** [comment]
Have you tried the [AnimationTreePlayer](http://docs.godotengine.org/en/3.0/classes/class_animationtreeplayer.html) node? It can be used to blend animations together, as seen in the [3D Platformer demo](https://github.com/godotengine/godot-demo-projects/tree/master/3d/platformer).

**Comment by zspinelli** [comment]
Oops, I hadn't noticed it. I'll close the issue. Sorry to waste your time.
