### ISSUE TITLE
Option to manually rescan for file changes

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#16683]
**Godot version:**

Godot 3

**Issue description:**

I ask for any option that allow to perform the same search that godot internally do when a folder is created from editor. Problem is that godot is not capable of import files in not indexed unit (Windows) and there is nor option to "actualize" "rescan" or similar (Only option is to create a folder or restart the editor). If will be useful to have a button in files dock to actualize (F5  kind...) or a right click option to actualize. Method to re-scan is here because create folder or restart editor execute that, so i suppose is not very hard to implement. (if it´s useful, console shows this mensage when do that:  "Call rescan!")

**Comment by Zylann** [comment]
If needed there is a FileWatcher API on Windows which allows to watch for filesystem changes automatically

**Comment by Ranoller** [comment]
Since EditorFileSystem have exposed that funcionality is easy to do this button in a plugin (1 line in GDScript) so i close this issue to not grow needlessly issues board.
