### ISSUE TITLE
(android) libGLESv3.so not found

### ISSUE THREAD

**Issue by psoslash** [godotengine/godot#16695]
Godot version: 3.0 stable

OS/device including version: running windows 7 exporting for android
GPU used (phone): adreno 306
Emulator used: NoxPlayer 6

Issue description:
when trying to run a project on android i get the "{app} has stopped" message on both my phone and the emulator
if i use logcat i get the following line
`java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libGLESv3.so" needed by "libgodot_android.so"; caused by library "libGLESv3.so" not found`

both my phone and emulator do support GLES 3
also, said library is on my phone /system/lib

**Comment by Zireael07** [comment]
Yet another Adreno issue. I believe we have an open issue for all of those?

**Comment by akien-mga** [comment]
Yes, #12816, but this one looks different.

**Comment by psoslash** [comment]
this has nothing to do with rendering, its a missing library error at runtime
i'm testing with a 2d project btw

**Comment by akien-mga** [comment]
Closing, it was a system issue (see #21710).
