### ISSUE TITLE
Use of override since Godot is now c++11

### ISSUE THREAD

**Issue by fire** [godotengine/godot#16692]
Since Godot is now c++11, what are the opinions on using override in derived class methods everywhere?

It uses the compiler to help detect if the method made is the exact method overridden to avoid mistakes.

It's like the use of const, where it enforces rules but is not necessary.

**Comment by vnen** [comment]
> Since Godot is now c++11

Godot requires a C++11 compiler because some of its dependencies, but the source of Godot itself it's still based on C++03. See #9694.

**Comment by jonesmz** [comment]
That doesn't really answer the question posed in the original post.

Are you saying that the use of the override keyword is disallowed?

**Comment by jonesmz** [comment]
When will that be?

**Comment by fire** [comment]
Reopen when godot revisits c++11.
