### ISSUE TITLE
Script previews are complete black(regression from #15193)

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#16699]
**Godot version:**
https://github.com/godotengine/godot/commit/79f48cde3d9c47e64cca6090c3db0bff1c9e557f

**OS/device including version:**
Linux mint 18.3

**Issue description:**
![image](https://user-images.githubusercontent.com/3036176/36216752-b52cfd3c-11c0-11e8-8079-78b3f32e4280.png)

**Comment by Chaosus** [comment]
Hmm.. its fixed accidentally.

**Comment by akien-mga** [comment]
CC @poke1024
