### ISSUE TITLE
Cannot Copy From Editor

### ISSUE THREAD

**Issue by CaptainKraft** [godotengine/godot#167]
If I select a block of text and hit ctrl+c or use the dropdown menu from edit, nothing is copied to the clipboard. Pasting into the editor works fine with ctrl+v.

Right-clicking on text doesn't show a menu to copy either so the only methods I have to copy are ctrl+c or using the edit dropdown menu and hitting copy.

**Comment by akien-mga** [comment]
@CaptainKraft Is this still valid with recent versions of Godot (1.1 or recent 2.0 alpha builds)?

**Comment by CaptainKraft** [comment]
@akien-mga I won't be able to test that because I'm not using the same setup anymore. I also haven't used Godot in some time.

**Comment by akien-mga** [comment]
Thanks. As there haven't been any confirmation from another user, let's assume that it was a corner case and/or that it might have been fixed.
