### ISSUE TITLE
[2.1.5-latest] godot engine cannot be moved and fullscreen is broken

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#16704]
This pull request introduces the bug https://github.com/godotengine/godot/pull/15565

**OS/device including version:**
Linux 4.14, Debian buster, XFCE

**Issue description:**
Fullscreen is working half of the time
We cannot move the windows using the "Alt + mouse" shortcut
Changing the resolution does not work either.

**Demo:**
Window management is broken on linux:
[Not working](https://imgur.com/mq0BkgC)

I performed a revert of the PR and here is the result:
[Working](https://imgur.com/NgPULZq)

**Comment by bruvzg** [comment]
Changing resolution was never implemented (on any platform, bindings for related functions were removed in 3.0). https://github.com/godotengine/godot/blob/2.1/platform/x11/os_x11.cpp#L666 

Demos are not viewable for me ("Non-Image content-type returned").

**Comment by xsellier** [comment]
@bruvzg I updated the issue for the demo. (I wanted to use a image link, but did not work).

**Comment by xsellier** [comment]
@akien-mga Reverting #15565 will fix most of the regression.

I recompiled godot performing this just before:
`git revert -m 1 e0b20449ad0fa0d60af17f33ab892803b62df725`

It remains only the issue with the shape collisions. (it seems to be an issue from January, still working on it).

**Comment by akien-mga** [comment]
CC @RandomShaper

**Comment by bruvzg** [comment]
Some tests:
Debian GNU/Linux buster/sid (4.14.0-3-amd64), Xfce

Latest 2.1 - fullscreen does not work (I can switch to fullscreen but not back to window), borderless window does not work at all, Alt+Click works.

Latest 2.1 (with e0b2044 and 6a180a6 reverted) - fullscreen works, borderless window does not, Alt+Click works.

Latest 3.0 - everything works

**Comment by xsellier** [comment]
> Latest 2.1 (with e0b2044 and 6a180a6 reverted) - fullscreen works, borderless window does not, Alt+Click works.
Just revert 6a180a6, you will have the same result. Borderless windows was working back in december. But I have no time today to perform another git bisect.

**Comment by bruvzg** [comment]
>I don't know, all I can say that it was working properly before those commits.
>Here the piece of code I'm using to update the windows size:

Window size change and viewport rendering resolution change (stretch mode) should work, but it's not changing actual screen resolution, viewport is rendered at specified size and the scaled to screen native resolution (aka Borderless fullscreen).

Exclusive fullscreen (with real resolution change) is not implemented (#14542, #2094, #6).

**Comment by RandomShaper** [comment]
I'm checking this ASAP.

Talking about X11, in 2.1 I think borderless never worked.
I can't guess now why the Alt + click thing has stopped working. But it seems there are contradictory reports on this.
Not being able to switch back from fullscreen is less surprising.

Any other information or report will be appreciated.

**Comment by xsellier** [comment]
@RandomShaper Once the moving window + _fullscreen_ is fixed, I will implement the borderless feature. It is not that hard to implement (https://stackoverflow.com/questions/1904445/borderless-windows-on-linux).

**Comment by RandomShaper** [comment]
A PR to fix the fullscreen issue has been submitted.

@xsellier, if the Alt + drag issue is still present, please submit it as a separate report.

**Comment by xsellier** [comment]
@RandomShaper I've just tested it. And everything is working well.

**Comment by akien-mga** [comment]
Fixed by #16762.
