### ISSUE TITLE
How to change the shape in a CollisionObject2D?

### ISSUE THREAD

**Issue by dbsGen** [godotengine/godot#1670]
I know I can use  add_shape and remove_shape to do this, but CollisionPolygon2D only allowed to be edit in editor tool and I can not save my draw to a Resource, so I have no idea how to get the Shape2D for add_shape.

**Comment by thecodethinker** [comment]
The github issues page are usually for bugs. If you don't know how to do something the forums is a better place to ask.

**Comment by dbsGen** [comment]
@thecodethinker I post here because I am not clear about is this a mistake on design or lack of documentation.

**Comment by TheoXD** [comment]
@dbsGen, no, aparently you haven't used godot long enough to make conclusions about "mistakes in godot design".

**Comment by reduz** [comment]
it's rather strange design. From 1.2, the shape nodes will be available during runtime.
Still though, CollisionPolygon2D generates many convex shapes, so it can't be edited at runtime unless you generate those shapes yourself.

The alternative is using a ConcavePolygonShape2D, which works with segments and will run in the game.

**Comment by dbsGen** [comment]
@reduz amazing! I wait for the 1.2.

**Comment by dbsGen** [comment]
@TheoXD I am sorry for that.

**Comment by eska014** [comment]
CollisionShape nodes can work as runtime helpers since 2580ca01e6b73a54def5a8f6e61d19509d3278ee.
