### ISSUE TITLE
Disable 2D filter in editor

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#16701]
When you want precision but also the filter you just have to keep disabling > enabling > disabling...
There's no reason to want the filter on at the editor at all. But for the sake of preference, maybe a toggle on editor settings.

**Comment by groud** [comment]
What do you mean by 2D filter ?

**Comment by Chaosus** [comment]
I guess this
![image](https://user-images.githubusercontent.com/3036176/36219485-a3cac13e-11c8-11e8-8721-366d1e518c2c.png)

**Comment by bfloch** [comment]
Have you checked the "Presets" button in the importer?

**Comment by mateusak** [comment]
@bfloch Unrelated

**Comment by groud** [comment]
Please explain a little bit more your problem. What filter are you talking about?

**Comment by akien-mga** [comment]
I guess they want to disable filtering for the 2D viewport itself... but I'm not sure what that would mean, individual CanvasItems are already rendered differently based on their own filter import flag. Apart from that, it's only the background color and the gizmos...

**Comment by groud** [comment]
Well but I don't get why this would be useful. If you need precise positioning you either use pixel snapping or type the value in the inspector. You don't disable filtering it does not makes sense.

**Comment by Noshyaar** [comment]
No filtering means sharper texture border. That kinda helps with positioning.

**Comment by mateusak** [comment]
The issue is as follows
Due to the filter cropping problem, I have to create my textures 1px larger at every boundary. But this causes a blurred edge on editor. So when you need pixel precision but can't know the position beforehand, you HAVE to disable filter. E.g setting up a 2d skeleton
Now this is dumb because what's shown in the editor is completely different from the filter in game (in low resolution art), so just disable it from editor. It's impractical and confusing.

**Comment by groud** [comment]
Can you take screenshots ? If you have different results in game and in the editor this is probably a bug.

> No filtering means sharper texture border. That kinda helps with positioning.

Well yeah but you have a rectangle drown around your selection, so it should not impact that.

**Comment by Calinou** [comment]
Filtering could automatically be disabled for all 2D textures when zooming by a large factor, as seen in image editors like GIMP or Photoshop (the latter also displays a pixel grid at very high zoom values).

**Comment by mateusak** [comment]
![untitled-2](https://user-images.githubusercontent.com/18586380/36496692-cd61fc02-1717-11e8-8d99-fc03ffda49b1.png)
The arm needs to be on an exact pixel and like this it is impossible to have a reference

**Comment by Calinou** [comment]
This should be easier to achieve thanks to bindless textures in the Vulkan renderer. Not sure about OpenGL though :slightly_smiling_face:

**Comment by clayjohn** [comment]
In 4.0 filtering is now done on in the CanvasItem rather than on import of the texture. A global default can also be set in the [Viewport](https://docs.godotengine.org/en/latest/classes/class_viewport.html#class-viewport-property-canvas-item-default-texture-filter). This should allow you to set up a better workflow when you are switching between your game and editor.
