### ISSUE TITLE
SpriteFrames _get_animations not in docs

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#16708]
Godot Master

Is there any reason why this always returns an empty Array?
https://github.com/godotengine/godot/blob/e24f2c6489afdccc6268008d3dcc1ff4ad8ea71c/scene/2d/animated_sprite.cpp#L165

I was trying to get the amount of animations, I can use `_get_animations()` but it is not showing in the docs.

Maybe also rename `_get_animations()` to `get_animations()`?
What is frames for? maybe hide it in GDScript?

**Comment by bojidar-bg** [comment]
Looking at the bindings: (scroll right)
https://github.com/godotengine/godot/blob/e24f2c6489afdccc6268008d3dcc1ff4ad8ea71c/scene/2d/animated_sprite.cpp#L234-L239
Seems like it is there for "Compatibility". Same for `_get_animation` a few lines below.

Calling engine functions starting with _ from GDScript is discouraged in any case.

**Comment by danvalho** [comment]
@AlexHolly I issued a PR adding an exposed call `get_animation_names` that you can use to get an array containing the animation names in a `SpriteFrames` node. Then you can get the amount of animations from array's size.

**Comment by akien-mga** [comment]
Fixes by #19087.
