### ISSUE TITLE
Type icons lack enum and flag types

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16717]
**Godot version:**
133942c

**Issue description:**
Now that type icons have been re-implemented (#15505 🎉 ), the only types that seem to be left are the enum (which just displays an error for now) and flag icons.

**Comment by bojidar-bg** [comment]
(CC @djrm)

**Comment by YeldhamDev** [comment]
![screenshot1](https://user-images.githubusercontent.com/30739239/36282659-02a96bb8-1289-11e8-8117-72d8368c3cb8.png)
But not thinking about it, they are just `int`s, so not really.
