### ISSUE TITLE
Cannot find -lImm32 on Linux mingw64

### ISSUE THREAD

**Issue by fire** [godotengine/godot#16713]
**Godot version:**
https://github.com/godotengine/godot/commit/3be04f73f567b9c39efae697e2a9b7d3c6185fc3#diff-0e85019d6dc0fa1ee8068e9f44d622b5

**OS/device including version:**
Build system

centos 7.4

**Issue description:**
Building with mingw and p=windows fails.

[go] Task: /bin/bash -c "scons platform=windows target=release_debug -j`nproc --all` use_lto=no gdnative_wrapper=yes deprecated=no"took: 21.66sexited: 2
scons: Reading SConscript files ...
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
Linking Program        ==> bin/godot.windows.opt.tools.64.exe
progress_finish(["progress_finish"], [])
/usr/lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lImm32
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.tools.64.exe] Error 1
scons: building terminated because of errors.
[go] Task status: failed, took: 21.66s, exited: 2
[go] Current job status: failed

**Steps to reproduce:**
Build with mingw under Linux.

`scons p=windows`

**Comment by fire** [comment]
Weird, maybe Imm32 isn't imm32. Note casing.

**Comment by fire** [comment]
Confirmed:

Changing this to be "imm32" works. This is a lowercased i.

env.Append(LIBS=['mingw32', 'opengl32', 'dsound', 'ole32', 'd3d9', 'winmm', 'gdi32', 'iphlpapi', 'shlwapi', 'wsock32', 'ws2_32', 'kernel32', 'oleaut32', 'dinput8', 'dxguid', 'ksuser', 'imm32'])

I would change the other one for consistency.

**Comment by akien-mga** [comment]
Yes, please change both to lowercase if that's what MinGW uses on Linux/macOS. Windows is case insensitive so it doesn't matter for MSVC, but change it for consistency.

**Comment by fire** [comment]
Can you patch this in? Good night.
