### ISSUE TITLE
VisualScript files attempt to load in external editor

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#16712]
**Godot version:**

e7351ec

**OS/device including version:**

Windows 10 x64

**Issue description:**

VisualScript files are binary-encoded and not directly human-readable outside of the Godot editor.  As .vs files are a bit different from other scripts, it doesn't make sense to use the same "use external editor" option to load them.  Currently, visual scripts will attempt to launch in the external editor if the "use external editor" option is checked and will fail to display in some editors (such as vscode).

**Comment by bojidar-bg** [comment]
Refs #16023 about saving vsscript files as text.

**Comment by nobuyukinyuu** [comment]
While having text-based .vs files would be nice, right now I'd settle for them being opened in the internal editor by default until the option can be toggled independently of text-based script files...

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by nobuyukinyuu** [comment]
Can't replicate in 3.2.2beta4.
