### ISSUE TITLE
Problems with the Asset LIb

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16719]
**Godot version:**
 133942c

**Issue description:**
- [ ] An error sign appears in the place of the asset logo while it's loading.
- [ ] If the logo fails to load, an exclamation icon appears instead, but it's much smaller compared with the other asset logos, and makes it look out of place.

**Comment by Chaosus** [comment]
Also AssetLib still spam the output with error red strings when preview images not correctly loaded
