### ISSUE TITLE
Adding GDNative API to expose a few key parts of the render engine

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#16732]
@karroffel @reduz , just thinking out loud here because I've had to add in Glad and my own shader compiler to a few GDnative plugins which just feels wrong.

The main problem for me here is that I'm perform a few actions not available in GDScript for good reasons such as creating a render target which is not part of any viewport and applying shaders to prepare the result of rendering for delivery to the VR SDK in use. This duplicates a bunch of work and bypasses some of the x-platform and threading stuff implemented in Godot. It also means it will only work with the GLES3 drivers, not GLES2.

I'm wondering if it would be worth our while to expose more of the internals of the visual server through a GDNative API to allow GDNative plugins to make use of functionality we'd rather not expose in GDScript? Actions like creating a render target and making that the active render target, compiling a shader, using the shader with a quad, etc.

**Comment by Calinou** [comment]
In the `vulkan` branch, the new rendering architecture allows overriding parts of the renderer using a script. Is this enough to implement this feature? See [Vulkan progress report #1](https://godotengine.org/article/vulkan-progress-report-1).

**Comment by Calinou** [comment]
RenderingDevice is now exposed to the scripting API in the `master` branch, closing.
