### ISSUE TITLE
Instancing a node in a new thread causes lockup

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#16731]
**Godot version:**
Godot 3.0 stable

**OS/device including version:**
Windows 10 x64

**Issue description:**
Instancing PackedScene in a separate thread causes a lockup.

**Steps to reproduce:**
start a thread that calls a function that instances a resource/packedScene

**Minimal reproduction project:**
is this intended?

**Comment by akien-mga** [comment]
> **Minimal reproduction project:**
> is this intended?

A bug is never intended, but yes, a minimal reproduction project would be good.

**Comment by reduz** [comment]
As no sample project was provided, this issue is closed.
