### ISSUE TITLE
Changing the radius of a collision shape makes ALL the collision shapes change

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#16737]
**Godot version:**
3.0

**OS/device including version:**
Win10

**Issue description:**
Old-ish issue. Encountered it on my project and found [this QA post](https://godotengine.org/qa/12876/changing-radius-collision-shape-makes-collision-shapes-change) that explains it and the workaround very well

**Steps to reproduce:**

Have multiple nodes use the same CollisionShape2D and CircleShape2D. Change radius in script, it impacts all the shapes.

**Comment by Noshyaar** [comment]
I think this is intended. You have to use "Make Unique" option.

**Comment by akien-mga** [comment]
Indeed, this is a feature. Either use "Make Unique" from the editor as shown above, or duplicate the shape from script if you want to edit it only for one instance.

**Comment by JarLowrey** [comment]
Click `Make Unique` does not seem to solve the problem for me. Setting a new shape in code does though:

```
	var shape = CircleShape2D.new()
	shape.set_radius(min(spriteShape.x,spriteShape.y)/2)
	$KinematicBody2D/CollisionShape2D.shape = shape
```

**Comment by Noshyaar** [comment]
Did you click Make Unique *after* you duplicated a node, or before?

**Comment by JarLowrey** [comment]
I clicked "Make Unique" on the node in the editor. From the code I set the radius to different values, which does not work. 

If I create a new node each time in the code, it works.

**Comment by Noshyaar** [comment]
If you're using code to duplicate nodes, creating new shape is the right way. "Make Unique" is just creating new shape with the same property. If you duplicate nodes after you click "Make Unique", it will use the same shape.

**Comment by MarageDev** [comment]
I had the same problem as you, I know it's an old post but with Godot 4.3 ( stable ) I still had it. And the only way I've found to fix it was by making the Shape of the CollisionShape2D "Local to Scene".

![image](https://github.com/user-attachments/assets/b2aa70bd-c6de-4bbf-8a77-871e29d5adc2)

And then in the script you can modify its size like you wanted to do:
```gdscript
extends Area2D

var size:float = 10.
@onready var collision_shape_2d = $CollisionShape2D

func _process(delta):
	collision_shape_2d.shape.radius = size
```

**Comment by AThousandShips** [comment]
You don't need to use that, just use "Make Unique" in the menu

**Comment by MarageDev** [comment]
As said by [JarLowrey](https://github.com/JarLowrey) it wasn't working, and me neither on my side, this was the only "clean" way I've found to fix the issue instead of creating a new CircleShape2D.
