### ISSUE TITLE
Problems with the new round edges for scene files

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16734]
**Godot version:**
79f48cd

**Issue description:**
- Scene files lose edge roundness when edited and played:
![screenshot2](https://user-images.githubusercontent.com/30739239/36291703-c0c10ab4-12b3-11e8-95eb-ebfc360b10c8.png)

- They affect the scene previews:
![screenshot3](https://user-images.githubusercontent.com/30739239/36291706-c5501f66-12b3-11e8-83c2-8c81d3f17c98.png)

**Comment by akien-mga** [comment]
CC @poke1024

**Comment by Chaosus** [comment]
@YeldhamDev Could you check this issue again ? I think after #16748 this been fixed

**Comment by YeldhamDev** [comment]
@Chaosus Nope, both problems are still here.

**Comment by YeldhamDev** [comment]
Well, the bug itself is fixed, so closing it.
