### ISSUE TITLE
Able to create folders on Windows with a period at the end.

### ISSUE THREAD

**Issue by Battlefrog** [godotengine/godot#16735]
**Godot version:**
Godot Engine v3.0.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
When creating a folder, you can add a period to the end. In Windows, this breaks the file structure. Because that happens, Godot doesn't that the file exists.

**Steps to reproduce:**
On Windows, create a folder inside the program with the right-click context-menu. Make sure to put a period (.) at the end of the name.

**Minimal reproduction project:**
Project with the folder already created. To get rid of a folder with a period at the end, simply open the directory in some sort of zip program and delete it, because Windows is dumb.
[help.zip](https://github.com/godotengine/godot/files/1730140/help.zip)

**Comment by hpvb** [comment]
Closed via #17243
