### ISSUE TITLE
Crash in start in Godot 2 branch in win32 bit version because commit #16269

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#16740]
**Godot version:**

Godot 2.1 32 bit compiled at 15/02

**OS/device including version:**

Win7

**Issue description:**

Godot 2 compiled at 15/02/18 (32 bit version win 7) can´t open some projects. I can´t find cause because is strange, it seems that, if there is not previously filesystem_cache it can crash. And in other projects and demos it seem the opossite, if there is cached files crash, but if you delete that it open.... weird. I can´t find why some times crash and some times not (crash with 2d in 3d demo, Isometric demo, and most of the demos) . If you can open a project, it never crash, but if you open that with previous version, next time you can´t open with 15/02 version. So i feel that the only way is isolate commit to understand why is happend.
On crashing there are two <couldn´t map PC to fn  name> mensagges.

**Comment by Ranoller** [comment]
Probably error is produced only when project have a lot of code files opened in script editor (I´m speculating). So other posible warning is to close all scripts in editor before open project in godot 2.15.  This incidence will be rare because certain conditions have to be met ... but it is worth advertising.

**Comment by akien-mga** [comment]
Note: There is no Godot 2.15, it's 2.1.5.

And why bother with a warning instead of fixing whatever causes a crash? Did you file an issue about this crash?

**Comment by Ranoller** [comment]
I´m testing

**Comment by Ranoller** [comment]
This bug is more strange that is descrived in the issue. It´s reproducible opening most simple demo. So i will need to isolate the commit that do the regression. I´m testing with godot 2 32 bit (release_debug) compiled at 2/02/2018 (versión without bug) and godot 2 32 bit (release_debug) compiled at 15/02/2018 at 8befa3dd2fb00b9e1833f1a6f454860c38df173a.
I suspice from this: https://github.com/godotengine/godot/commit/043593b1dbc62394d0ae9bac6e68af0c6aa96247
but i can´t confirm (can´t compile here).
Well, on monday i will try to isolate. I haven´t the computer to compile this weekend.

**Comment by Ranoller** [comment]
Finaly I had the time.... Commit  #16269 introduces de bug. I see that a bug-fix was introduced in #16711 but i compile at aed100a3c3398ea9cb95d9bb57f2ba176afb7c96 and bug described here is not fixed. So this is the commit that crash 32 bit version of godot at start. I have to say that the bug affects to projects without scripts too, like light2d demo (if this can help).

How to reproduce: compile godot 2 branch for win 32 bit and try to open godot demos with.

**Comment by akien-mga** [comment]
CC @xsellier

**Comment by xsellier** [comment]
I noticed this bug, and I pushed a fix for it https://github.com/godotengine/godot/pull/16724

**Comment by akien-mga** [comment]
Fixed by #16724.
