### ISSUE TITLE
mbedTLS: Error parsing some certificates: 1

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#16750]
**Godot version:**
Godot 3.1.dev (133942c)

**OS/device including version:**
Windows 10 x64 build 16299

**Issue description:**
Every time I open the editor or a game I get a warning in the console:

```
WARNING: StreamPeerMbedTLS::_load_certs: Error parsing some certificates: 1
     At: modules\mbedtls\stream_peer_mbed_tls.cpp:281
```

Doesn't seem harmful but it's strange to have it.

**Steps to reproduce:**
* Open the editor
* Look at the console

**Comment by akien-mga** [comment]
I think @Faless mentioned this in his PR. We should likely start by updating our certs bundle, and see if it still happens.

**Comment by akien-mga** [comment]
Could you try https://github.com/akien-mga/godot/tree/ca-certificates ? It uses the latest Fedora certs bundle (packaged from the Mozilla source).

**Comment by Faless** [comment]
> Could you try https://github.com/akien-mga/godot/tree/ca-certificates ?

Seems to work for me, warning is gone, assetlib works.
