### ISSUE TITLE
Particles AABB is broken

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#16768]
**Godot version: 3 stable**

**Issue description:**
Moving Particles AABB or changing the size does not work as it used to, before stable.

![brokenaabb](https://user-images.githubusercontent.com/10215987/36337508-cda94886-1376-11e8-8201-6c5afda193c2.png)

The grid representing the AABB on the editor is also broken.

**Steps to reproduce:**
Try to move and resize the particles AABB.

**Comment by JFonS** [comment]
The visual representation of visibility AABB should be fixed in #16358.
