### ISSUE TITLE
Resizing an Image captured from Viewport results in empty image

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#16764]
Godot 3.0

Confirmed after seeing it from a QA thread: https://godotengine.org/qa/23965/the-screen-shot-in-the-save-game-porting-a-project-to-godot-3-0

Repro steps:

1) Open the official screenshot demo
2) Change the code to resize the image like so:
```gdscript
	# Flip it on the y-axis (because it's flipped)
	img.flip_y()
	img.resize(300,300) # <-----------
```
3) Launch the demo and click the button: you'll not see the screenshot.

Note: resizing images loaded from typical PNG works.

**Comment by alforium** [comment]
Thanks for the report, I was going to post the same thing! Neither `resize()` nor `resize_to_po2()` seem to work.

**Comment by Noshyaar** [comment]
Image captured from viewport are formatted RGBAH. It must be converted to RGBA8 first.

```
img.flip_y()
img.convert(5) # Image.FORMAT_RGBA8
img.resize(300,300)
```

**Comment by Calinou** [comment]
@Zylann Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

If so, we should at least document this limitation.

**Comment by Zylann** [comment]
I think it works now, however resizing to a larger size produces artifacts (which is a problem I hit in my terrain plugin too), regardless of the format being RGBAH or RGB8:

Original:
![image](https://user-images.githubusercontent.com/1311555/83975422-d3a7ec80-a8eb-11ea-976a-1ccc55e3e668.png)
Expected upscaled x4:
![image](https://user-images.githubusercontent.com/1311555/83975467-1073e380-a8ec-11ea-85c0-8e9e4d7f0c1f.png)
Obtained upscaled x4:
![image](https://user-images.githubusercontent.com/1311555/83975475-21bcf000-a8ec-11ea-8518-f084e830ddde.png)

The default is supposed to be `INTERPOLATION_BILINEAR`, but it ran nearest.

**Comment by Calinou** [comment]
@Zylann I see, thanks for replying. It might be worth opening a new issue about this as to avoid confusion.
