### ISSUE TITLE
VERY slow performance of instancing in thread

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#16769]
**Godot version:**
2.1.4 stable

**OS/device including version:**
Windows 7 32bit

**Issue description:**
Very slow performance of `instance()` while used in thread make it impossible to load big level within resonable time amount.
Loading levels using `instance()` within main thread finishes in resonable time but froze everything for fiew seconds while loading which is unnacceptable.
**Seems like because of very slow `instance()` there is no way to load big levels without freezing whole game.**

**Steps to reproduce:**

(simplified for demonstration) example code to generate level on the fly.
```
var tile = load("res://tile.tscn")
var loop = 0
while (loop < 5000):
	var t = tile.instance() # <--- this is very slow
	t.set_name(str(loop))
	get_node("/root/tile").add_child(t)
	t.set_owner(get_node("/root/tile"))
	loop = loop + 1
```
When this code is ran in thread (to avoid freezing) it executes super slow.
Generating level might take around minute.
When its ran in main thread its resonable fast (fiew seconds) but freezing everything.

I tried to find work around and save generated level as scene and then load it as a whole, but it seems suffer the same performance issue.

executing this 
```
	var stage = load("res://stage.tscn").instance()
	get_node("/root/stage").add_child(stage)
	stage.set_owner(get_node("/root/stage"))

```
or the same different way
```
	get_tree().change_scene("res://stage/stage-2.tscn")
```
gives exacly the same outcomes
when ran in thread its super slow and loading level may take over 1 minute
when ran in main thread its resonable fast but freeze everything for fiew seconds.

I think this might be related to 
https://github.com/godotengine/godot/issues/10970

**Comment by Ranoller** [comment]
So backport of 192a4d7 is needed. This was a great fix and this can be a wonderfull adition to 2.1.5

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Comment by LingLing40Hours** [comment]
I just ran into this issue in 4.1. The scene I'm instancing is a CharacterBody2D with the following attached: a CollisionShape2D, RayCast2Ds, ShapeCast2Ds, Area2D with its CollisionShape2D, Nodes, Node2Ds, and a VisibleOnScreenNotifier2D.

**Comment by Calinou** [comment]
@LingLing40Hours Please open a new issue *with a minimal reproduction project attached*.
