### ISSUE TITLE
Add "Specular Map" property to Sprite (2D) like "Normal Map" was added

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#16775]
Good day everyone,
this is not a bug report, its a new feature request.

Please add "Specular Map" property to 2D Sprite (animated sprite also?), like the "Normal Map" property was added, this would simplify a lot for 2D games avoiding the manual creation of a shader and probably givin the developer a version more mathematically efficient and better integrated with the way the rendering pipeline works right now, like the new 3D materials work.

Also tools like Sprite DLigth or Sprite Lamp generate this specular maps for 2D art with no effort adding better detail than just the normal map.

Thanks in advance,
best regards.

**Comment by rubenjavier** [comment]
Thinking about this some more, Light2D also is going to need a new property "Specular Color", just like its actual "Color" property (color picker), so specularity dont have to be the same color of the light.

**Comment by rubenjavier** [comment]
After checking out some code, this actually would affect the functions "draw", "draw_rect and" "draw_rect_region" in:
scene/resources/texture .h .cpp
scene/2d/sprite.cpp
scene/2d/animated_sprite.cpp
scene/2d/tile_map.cpp
scene/2d/canvas_item.cpp

Since the point would be to also have specularity on those, specially in TileMap

**Comment by reduz** [comment]
2D lighting is very basic and it uses no specularity, which is in general
not very useful anyway. If you really want to create such system, Godot
gives you everything you need in it's material shader system.

**Comment by rubenjavier** [comment]
Thanks @reduz 
I've been searching for some examples for version 3.x 2D shaders with normal + specular maps to create better 2D materials with different gloss per_map or cell shading and even rim light, but havent found a 2D example doing something like this.
Could you please provide a godot example like that?

Im trying to eventually get something like this unity sprite shader (there is a gift on the link showing what I mean):
https://github.com/traggett/UnitySpriteShaders

https://raw.githubusercontent.com/traggett/UnitySpriteShaders/master/ReadmeAssets/Example.gif

I know that since Light2D doesnt have SpecularColor right now, I would have to use its Color or manually set one on the shader, but that would be ok.
Thanks in advance
Best regards

**Comment by rubenjavier** [comment]
Sorry @reduz , I forgot to ask... using such a shader material would work with TileMaps? or it would be limited to its NormalMap material
Thanks in advance

**Comment by reduz** [comment]
It should work everywhere, as tiles can have their own material.

On Feb 19, 2018 16:26, "rubenjavier" <notifications@github.com> wrote:

Sorry @reduz <https://github.com/reduz> , I forgot to ask... using such a
shader material would work with TileMaps? or it would be limited to its
NormalMap material
Thanks in advance

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/16775#issuecomment-366783500>,
or mute the thread

**Comment by rubenjavier** [comment]
Thanks @reduz , Im attaching a zip that contains the godette_body.png at full res and  cleaned to have transparency, and all the maps that Sprite DLight create at its default settings, depth, normal, occlusion and specular, in case somebody can create a new demo for advanced 2D materials.
If I can be of any more help with Sprite Dlight or anything else, just let me know

[godette_body_material.zip](https://github.com/godotengine/godot/files/1738063/godette_body_material.zip)

Thanks in advance

**Comment by Calinou** [comment]
This was implemented in the `vulkan` branch, see the [Vulkan progress report #2](https://godotengine.org/article/vulkan-progress-report-2).

This issue can be closed once the `master` branch incorporates the `vulkan` branch (which will happen after Godot 3.2's release).

**Comment by akien-mga** [comment]
I think we can close now as fixed in 4.0 then.

**Comment by rubenjavier** [comment]
But is it added also on 3.2 branch?
for people using 3.2 for GLES3?

**Comment by akien-mga** [comment]
Since it hasn't seen much activity in 18 months, and feature development for Godot 3.2 is over, I don't think so.

**Comment by rubenjavier** [comment]
could you please keep this open, in case reduz have time to backport it once 4.0 is out?

**Comment by akien-mga** [comment]
No, I don't want to give users false hopes. The work done on 4.0 can't be backported, it's a whole different rendering and material architecture.
