### ISSUE TITLE
set_auto_accept_quit(false) not working on android

### ISSUE THREAD

**Issue by Acvarium** [godotengine/godot#16782]
**Godot version:**
3.0

**OS/device including version:**
Blackview BV5000 Android 6.0 linux 3.18.16

**Issue description:**
I am trying to add a feature to go to the game menu after pressing 'back' button on android device. Added line
get_tree().set_auto_accept_quit(false) to _ready() function
But game still closes

**Minimal reproduction project:**
[android_back_button_bug.zip](https://github.com/godotengine/godot/files/1733992/android_back_button_bug.zip)

**Comment by volzhs** [comment]
see this #15189
there is method for android back button `get_tree().set_quit_on_go_back(false)`

**Comment by Acvarium** [comment]
Thanks.You helped me a lot. I was thinking that there has to be something like this, but did not found a documentation

**Comment by volzhs** [comment]
i think there should comment about `set_quit_on_go_back` and `set_auto_accept_quit` in each function description.

**Comment by KoBeWi** [comment]
Uh, I'm using Godot 3.1.1 with Xiaomi Redmi Note 4 and this actually doesn't work. When I use `set_quit_on_go_back`, the game doesn't receive quit notification at all.
