### ISSUE TITLE
AudioStreamPlayer defaults to 3D in the "Create New Node Menu".

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#16789]
**Godot version:**
3.0 stable

**OS/device including version:**
windows 10 x64

**Issue description:**
A minor bug.  when selecting the  AudioStreamPlayer  node in the "recent" tab when creating a new node form the create new node menu the default selection is AudioStreamPlayer3D

**Steps to reproduce:**
open the create new node menu and select AudioStreamPlayer from the recent tab. I've attched some screen shots of the problem.

**Minimal reproduction project:**

![screenshot 15](https://user-images.githubusercontent.com/5633261/36347818-4c12e444-1416-11e8-89f0-576c5e9ced21.png)
![screenshot 16](https://user-images.githubusercontent.com/5633261/36347819-4da74796-1416-11e8-8e98-3b7d05a032d6.png)
![screenshot 18](https://user-images.githubusercontent.com/5633261/36347820-4ed12c40-1416-11e8-857c-74efca10fcbd.png)

**Comment by Noshyaar** [comment]
Probably a side-effect from #11706. Not sure.

**Comment by KoBeWi** [comment]
Seems to be fixed in 3.1.
![image](https://user-images.githubusercontent.com/2223172/57016049-50ac6100-6c18-11e9-800f-7270a6f62443.png)
