### ISSUE TITLE
Allow Youtube embeds on forums

### ISSUE THREAD

**Issue by qubodup** [godotengine/godot#1679]
Hi,

To allow users to better showcase their games, it'd be neat to allow embedding YouTube videos.

In case you're interested: no extension is needed. Instructions:
http://youtu.be/mxce5nKIe5k
https://gist.github.com/qubodup/fb89b024bea065a46ff8

**Comment by TheoXD** [comment]
There is an idea to move the current forum to https://www.openproject.org/ so don't get too comfy with phpbb ;) It should be easy to add new bb-codes.

**Comment by qubodup** [comment]
First mention of OpenProject was in January, so it seems to be a long-term plan perhaps.

Short term I encourage you to make this small change now. :)

**Comment by vnen** [comment]
The new OpenProject website is live already and it's possible to embed videos (see [the wiki syntax page](http://www.godotengine.org/projects/godot-engine/wiki/Wiki_Syntax#Macros)).
