### ISSUE TITLE
Parallax Issue

### ISSUE THREAD

**Issue by OvermindDL1** [godotengine/godot#16800]
**Godot version:**

3.0 Full Release

**OS/device including version:**

`Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Issue description:**

Parallax is not working properly, four specific issues:

1. A particle system in a parallax layer in a parallax background vanishes at a distance that seems to correspond to a combination of the motion/scale of the layer and of the zoom of the camera and the visible viewport area, far far earlier than it should.

2. The `Ignore Camera Zoom` option on the ParallaxBackground when enabled and the camera is not at world origin causes the parallax layers to sheer across as you zoom in and out.  When it is false it has no such issue.

3. ~The `Ignore Camera Zoom` option on the ParallaxBackground in the Inspector cannot be toggled off, if it always forced On.  Clicking it to attempt to turn it off reports `Set scroll_ignore_camera_zoom` in the log, every time.  Setting it to false in the tscn file straight work, and setting it to false via GDScript works, but touching it in the inspector forces it always on.~ *Bugsquad edit:* Fixed #24011.

4. Set the `ParallaxLayer`'s Motion/Mirroring property to tile the particle field (render multiple times) so the particle field does not need to be so huge with so many particles, and instead any values others than `0` causes the particle field to entirely vanish.

**Steps to reproduce:**

Included in the below link is a minimal project that reproduces the issue.

It has a base `Node` with two children of `ParallaxBackground` and `Sprite`.
The `ParallaxBackground` has a child of `ParallaxLayer` with a motion/scale set to 0.1 (feel free to adjust to see how the cut-out distance chagnes).
The `ParallaxLayer` has a child of a `Particles2D` system that spawns particles that fade in/out in a large boxed area `8192` in distance.  It's Drawing/VisibilityRect is set to 300k values in each extent, feel free to adjust as it seems to make no difference).
The `Sprite` has 2 children, a `Camera2D` that is set as Current and a `Label` that displays the coordinates of the sprite.
There is a GDScript on the `Node` that handles movement/zoom/label, the keys are:

Arrow up/down/left/right to move the sprite (and thus the camera), hold Shift to go 10x faster, or Ctrl to go 10% the speed.  Mouse wheel up/down will zoom the camera in/out (clamped to prevent going too far).

For each problem with the Parallax system perform these steps when the project is loaded and running:

1. Hold 'down' (and 'shift' to go faster, just a couple seconds then) to reach ~3000 units (just a 'touch' under) at the default window size (notice when maximized then it goes further, ~6000 on my screen), at that point the particles will just vanish, and if you move up just a touch back to 2999 or so then they just instantly re-appear, this seems like they are being culled out but the visibility bounds should prevent that?  This happens in any direction

2. Load and remain at origin, zoom in and out, it looks correct.  Move a few hundred from origin and zoom in and out and you see the particle field sheer wildly toward/away to/from origin.  Set the `Parallaxbackground`'s ignore camera zoom option to false and notice that zooming works fine now (though it zooms the particle field too now, which may or may not be what is wanted).

3. Check in the Inspector, click the ParallaxBackground, try disabling the `Scroll/Ignore Camera Zoom` option, notice it cannot be disabled in this way.  Feel free to set it via the GDScript or manually edit the scene's tscn file via a text editor to set it to false in order to test the 2nd issue above.

4. Set the `ParallaxLayer`'s Motion/Mirroring property to anything other than `0`'s and notice the particle field vanishes when the project is run.

**Minimal reproduction project:**

https://overminddl1.com/godot/BugParallaxParticleVanish.zip

**Further Notes:**

I noticed the parallax system was rewritten in a prior issue, it seems it may have introduced these problems.

Each of these issues could entirely be my fault, however the Discord group stated to post these issues here...

**Comment by lben** [comment]
I am learning godot engine and currently using v3.0.6.stable.official.8314054 and cant make the ParallaxLayer mirror work.

get_viewport_rect().size.y is 600 and get_viewport_rect().size.x is 1024. I have ParallaxBackground with its default values and my ParallaxLayer with its default values except for the mirroring which I have been trying with different values and it doesn't work as expected. If I set a small value like x=100, y=0 the parallax layer sprite gets cut in half. If I set a larger value like x=1024, y=0 the sprite doesn't get cut but doesn't repeat until my character sprite meets the end of the parallaxlayer sprite (giving me once again a half empty screen). 

I don't know if I am doing something wrong or if there is a bug with the ParallaxLayer.

**Comment by KoBeWi** [comment]
The particles are vanishing because you are leaving the visibility rect. You can check this by putting
```
extends Particles2D

func _draw() -> void:
	draw_rect(visibility_rect, Color(1, 0, 0, 0.2))

```
in Particles2D node. The visibility rect uses parallax transform too, that's why it appears as if they were vanishing too quickly.

The mirroring seems to work somewhat, although I never fully understood it. Zooming seems fixed too.

I guess the issue can be closed. You can test it again in 3.2 and report any found bugs, but next time create one issue per bug, so they are easier to track.
