### ISSUE TITLE
Inconsistent support for user:// vs res:// directory operations

### ISSUE THREAD

**Issue by ratsdiov** [godotengine/godot#1680]
Windows 7 64 bit, beta 1.1.

1) Globals.globalize_path does not expand user:// references.  The C++ code only checks for res:// and does not expand user://.   A mostly cosmetic issue but it should be consistent.
2) Directory.make_dir does not create directories in user://.  Exact same code works fine if I change user:// to res://

There may be other cases, these are the two I hit.  

Impact, I can't find a way to create a subdirectory under user:// since I can't globalize it and make_dir does not expand it.

**Comment by kbdavidson** [comment]
OS.get_data_dir() will get the proper directory.

print ("System Documents Dir ", OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS)) also has problems... gives:

ERROR: get_system_dir:  Condition ' res!=((HRESULT)0x00000000) ' is true. returned: String()
At:  platform/windows/os_windows.cpp:2255

**Comment by okamstudio** [comment]
I would not trust globalize_path(), maybe for user:// it's always
filesystem but for other OSs or exported res:// may become a packed
filesystem or read from inside an APK, so no globalizing is possible

On Wed, Apr 15, 2015 at 10:11 PM, kbdavidson <notifications@github.com>
wrote:

> OS.get_data_dir() will get the proper directory.
>
> print ("System Documents Dir ",
> OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS)) also has problems... gives:
>
> ERROR: get_system_dir: Condition ' res!=((HRESULT)0x00000000) ' is true.
> returned: String()
> At: platform/windows/os_windows.cpp:2255
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1680#issuecomment-93610094>.
>



-- 

*OkamStudio*

**Comment by kbdavidson** [comment]
Thanks, on a related note I posted what I think are some fixes for the dir_access_windows.cpp code in the issue https://github.com/okamstudio/godot/issues/791 to help with some of the problems I was having.

**Comment by AlexHolly** [comment]
Ubuntu 64-bit, master branch
I made a testfile maybe I'm doing something wrong, maybe it can help to fix this issue.

```

extends Node2D

func _init():
	test1()
	
func test1():
	#creates 2 folders in .godot/app_userdata
	#1. test0
	#2. user:
	#expected: only .godot/app_userdata/test0 - FAIL
	#expected on run again: "Folder already available" message - OK

	var d = Directory.new()
	d.open( "user://" )
	if( !d.dir_exists("user://test0") ):
		print("Folder not available")
		var err = d.make_dir_recursive("test0")
		if(err==OK):
			print("Folder created")
		else:
			print("Error: " +str(err))
	else:
		print("Folder already available")

func test2():
	#creates 2 folders in .godot/app_userdata
	#1. test0
	#2. user:
	#expected: only .godot/app_userdata/test0 - FAIL
	#expected on run again: "Folder already available" - FAIL

	var d = Directory.new()
	d.open( "user://" )
	if( !d.dir_exists("test0") ):
		print("Folder not available")
		var err = d.make_dir_recursive("test0")
		if(err==OK):
			print("Folder created")
		else:
			print("Error: " +str(err))
	else:
		print("Folder already available")

func test3():
	# removing line d.open( "user://" ) and adding user:// to make folder
	# creates 2 folders
		# projectfolder/user:/test0
	# expected: result .godot/app_userdata/test0 - FAIL
	# expected on run again: "Folder already available" message - OK
	
	var d = Directory.new()
	if( !d.dir_exists("user://test0") ):
		print("Folder not available")
		var err = d.make_dir_recursive("user://test0")
		if(err==OK):
			print("Folder created")
		else:
			print("Error: " +str(err))
	else:
		print("Folder already available")
```
