### ISSUE TITLE
Trim trailing whitespaces on save not working until toggled

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#16806]
**Godot version:**

95f7879923783c3cbfc0a42cfd11e2b9d8260b46 

**Issue description:**

When opening the Godot editor the 'Trim trailing whitespaces on save' setting is ignored even though it is set in the editor settings. After deactivating and activating again everything works as expected until the Godot editor is closed

**Steps to reproduce:**
1. Activate 'Trim trailing whitespaces on save' in the editor settings
2. Close the Godot editor
3. Open the Godot editor
4. Add whitespace to any script file
5. Save the project
6. See that the trailing whitespace is still there
7. Disable 'Trim trailing whitespaces on save' in the editor settings and activate again
8. Save the project
9. See that the whitespace is removed

**Comment by vnen** [comment]
I experience this too. I'm not sure if it's this option in particular or the editor settings in general.
