### ISSUE TITLE
Changing rotation (global or local) of RigidBody2D forces position back to zero

### ISSUE THREAD

**Issue by Footurist** [godotengine/godot#16802]
In the same manner as `apply_impulse `overwrites rotation, setting `global `or `local ``rotation `forces its `position` back to zero. After calling `apply_impulse`, the `position `will stay at zero if changing `rotation `every `frame`, although `linear_velocity `is measurable over zero. I guess the two bugs are somehow connected.

**Comment by eon-s** [comment]
Are you setting the rotation of the node or the body state? 
If you want to modify the body transform you need to use the state, not the node.

**Comment by Footurist** [comment]
Oh, I see. I ended up switching to KinematicBody2D, which I could control more precisely, which was nice. So, you say if I modify the body state's transform, then it won't override things. Will this avoid the reset rotation bug by apply_impulse aswell?

**Comment by eon-s** [comment]
Probably, when I need so much control over a body I do not use rigids (in any engine), you can also manipulate velocities enabling the custom integrator, check dynamic platformer demo.

But in any case try to see if forces/velocities are reset after teleporting the state.

**Comment by mhilbrunner** [comment]
Closing, as this seems solved. If it isn't, please leave a comment. :)
