### ISSUE TITLE
RichTextLabel does not save rect_clip_content

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#16809]
**Godot version:** 3

**Issue description:** RichTextLabels do not save the rect_clip_content variable when it is turned off.

**Steps to reproduce**: Turn off a RichTextLabel's rect_clip_variable and save then close the scene. On running the game or reopening the scene, the variable will be turned on again.

I think this is due to a conflict between the line `set_clip_contents(true);` in rich_text_label.cpp and `ADD_PROPERTYNZ(PropertyInfo(Variant::BOOL, "rect_clip_content"), ...);` in control.cpp. I would fix this myself and submit a PR, but I'm not sure what would be the preferred fix between turning off default clipping in RichTextLabels or changing ADD_PROPERTYNZ to ADD_PROPERTY.

**Comment by Noshyaar** [comment]
Changing it to ADD_PROPERTY is better imo.

**Comment by Noshyaar** [comment]
Fixed by #16810
