### ISSUE TITLE
Add warning messages for orphan nodes on debug builds

### ISSUE THREAD

**Issue by Matheusrma** [godotengine/godot#16815]
**Godot version:**
Any
**OS/device including version:**
Any

**Issue description:**
A lot of times, bugs I face when working with Godot were caused by forgetting to add_child() a node to the scene (like an AudioStreamPlayer yday). An idea that might help is adding a warning message to the output for any orphan node you have on your game.

**Comment by eon-s** [comment]
This may also lead to leaks of unreferenced Objects, I think there was another similar issue about that.

**Comment by groud** [comment]
I'm not sure displaying a warning is a good thing. 
As you might want to keep a Node outside the tree on purpose, I don't think it's a good idea to spam the user for that.

**Comment by eon-s** [comment]
@groud there is no reason to create a Node and lose reference to it, I think, also there is a message of objects still in use when closing the program, but nothing tells you what objects are these, if it can throw a warning when you get an unreferenced object it may be easier to spot.

**Comment by groud** [comment]
"Not referenced" is not "not in tree", this is not the same. The add_child() method add the node to the tree, while `var mynode = load("my_node.tres") ` is a reference.

A warning for unreferenced objects might make sense, but I'm not sure it's even possible as unreferenced objects are deleted automatically.

**Comment by vnen** [comment]
Only types derived from Reference are deleted automatically, Nodes are not.

Nodes out the tree are useful only if you are keeping a pool of them, since they don't process. I've seen people trying to use the Tree control as a data structure, but that's not a good practice anyway. So a warning might be good, the only problem is when to trigger it.

**Comment by Zylann** [comment]
Isn't there a -v option when running Godot so it tells which objects were leaked in detail?

**Comment by eon-s** [comment]
-v for the editor or the exported game? I can do a `var n = Node.new()` somewhere to generate an orphan Object and I do not see anything anywhere other than increasing Object count in the monitor.

**Comment by Zylann** [comment]
@eon-s it's a command line argument to send at the execution of Godot, I'm curious if the editor can set it when debugging games. If you don't set it, you should still see a warning like "WARNING: cleanup: ObjectDB Instances still exist!"

**Comment by vnen** [comment]
You can set the run options in the project settings, but it seems that it skips this final phase when running from the editor, so the warning is never shown. It does show if you run directly from the command line.

**Comment by Calinou** [comment]
#28140 has implemented a monitor for orphan nodes, closing.
