### ISSUE TITLE
Provide more convenient way to edit exported strings.

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#16812]
Editing short variables, like a name of a game object is easy enough. But editing something like a description of a game object is quite painful in the little editing box in the inspector.

GUI controls like Labels already provide this feature with the dialog popup, I believe the very same thing could be incorporated with exported strings?

**Comment by Noshyaar** [comment]
```
export(String, MULTILINE) var text
```

**Comment by TX256** [comment]
Ooh, I have missed this! Thanks.
