### ISSUE TITLE
Port 3D physics shapes optimisation to 2D

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#16829]
**Godot version:**
Current master, d9f26af5.

**OS/device including version:**
Any

**Issue description:**
Back in Sep 2017 @reduz added an optimisation to defer the configuration of 3D physics shapes. We just discussed it and he mentioned it would be good to add the same optimisation for 2D, so anyone up to it can work on that.

**Comment by bojidar-bg** [comment]
For the record, the commit for the 3D optimization is adde89e8b1c66b4f4814c3b47a5d347ff576428b.

**Comment by akien-mga** [comment]
Fixed by #29951.
