### ISSUE TITLE
flat shader bug

### ISSUE THREAD

**Issue by Itachi124** [godotengine/godot#16827]
Godot 3.1
Windows 10 GTX 1070 
16GB ram 
i5

i try to add toon shader in this low poly sphere but the materail shader looks flat and not smooth.

import low poly sphere and add toon shader to it

![ws](https://user-images.githubusercontent.com/32880087/36387182-822b2d10-1598-11e8-9be0-7ac20ac724b6.PNG)

**Comment by Zylann** [comment]
Is this sphere looking smooth without toon? Does it look smooth in a 3D modeling program?

**Comment by CCODE05B** [comment]
this is not a bug , you are using non smooth sphere

**Comment by Itachi124** [comment]
Look at the normals of the shader its not smooth at all

**Comment by reduz** [comment]
There is no such thing as Flat shading in Godot, you exported the model
wrong.. this information is not in the material but the geometry.

**Comment by Zylann** [comment]
Can't reproduce with a sphere with correct smooth normals:
![image](https://user-images.githubusercontent.com/1311555/36425419-a2465a1a-163e-11e8-99b1-22f22b898261.png)

Side note, toon shading is this:
![image](https://user-images.githubusercontent.com/1311555/36425454-c33ea3ee-163e-11e8-816c-d56dbad8a48c.png)

**Comment by Noshyaar** [comment]
Closing as not a bug.
