### ISSUE TITLE
Make tile names follow texture order in tileset

### ISSUE THREAD

**Issue by hexdump2002** [godotengine/godot#16823]
**Godot version:**

3.0 official

**OS/device including version:**

High Sierra

**Issue description:**

When tiles are shown in a tilemap to start drawing, tiles are ordered alphabetically (by name). This make the tiles show in a different order that they do in the texture they were cut from. When a lot of tiles are created from a texture or just because user wants to find them at the same place he put them in the atlas would be good to keep same order.

By the way, is there any reason to have the name/id of the tiles taking so much space? Why not just show the tiles whitout its name/id below?

**Steps to reproduce:**
Example texture:

![tilesalpha](https://user-images.githubusercontent.com/7756851/36383072-543d65ec-158b-11e8-9541-e4c3ef19db49.png)

Imported set of tiles when selecting the tile map (ordering by name string):
![screen shot 2018-02-19 at 15 42 34](https://user-images.githubusercontent.com/7756851/36383159-9a334738-158b-11e8-8d67-b3925cefab22.png)

**Minimal reproduction project:**

**Comment by vnen** [comment]
I think there's a setting to sort tiles by id.

**Comment by hexdump2002** [comment]
You are totally right. I was searching for this kind of option but did not find it. Do you want me to delte the issue. I have seeen you can remove tile names/ids too. Handy!
