### ISSUE TITLE
Lightmap (raytrace) not working?

### ISSUE THREAD

**Issue by abgenullt** [godotengine/godot#16820]
**Godot version:**
Godot 3

Hello,

I've created a simple room in blender and exported it with the better collada exporter.
Now, I'm trying to create a lightmap. With ConeTrace mode, everything looks ok but in RayTrace mode it looks very strange...

ConeTrace:
![conetrace](https://user-images.githubusercontent.com/34768615/36380126-72eb75e2-1581-11e8-98b1-b30bb424e442.jpg)

RayTrace:
![raytrace](https://user-images.githubusercontent.com/34768615/36380136-7a0b676a-1581-11e8-8097-b3584a5aba29.jpg)

You can have a look at the project.

Is it a bug or have I done something wrong?
[house_viewer.zip](https://github.com/godotengine/godot/files/1736846/house_viewer.zip)

**Comment by Noshyaar** [comment]
ConeTrace:
![screenshot_2018-02-19_20-57-47](https://user-images.githubusercontent.com/26753932/36381241-96126fea-15b7-11e8-992d-a2bbbce19623.png)

RayTrace:
![screenshot_2018-02-19_20-52-48](https://user-images.githubusercontent.com/26753932/36381010-dbf45e66-15b6-11e8-85a8-6665252aedea.png)

Mine's not as weird. What are the parameters used? Video driver? (not sure if related)

**Comment by abgenullt** [comment]
I've used NVIDIA NVS 310 (driver v. 382.16) but I could test on AMD Rx480, if it is graphics card related.

I used the default parameters for the baked lightmap node and a import texel size of 0.01

**Comment by reduz** [comment]
I will be changing code related to baking in 3.2, so this is on hold.

**Comment by NovemberDev** [comment]
I have the same issue on 3.2.4, here is my setup:

(Force open it despite the missing textures)
[Lightmap_Test.zip](https://github.com/godotengine/godot/files/4005464/Lightmap_Test.zip)

**Comment by Calinou** [comment]
[The lightmapper will be rewritten for 4.0](https://godotengine.org/article/gsoc-2019-progress-report-1-part-2#lightmapper), but it's unlikely this will be fixed before then.

**Comment by KoBeWi** [comment]
Looks still valid in 3.2.4 beta2 (but might be fixed soon, see linked PR above)

Here's the result from 4.0-dev:
![image](https://user-images.githubusercontent.com/2223172/99916104-63115280-2d08-11eb-807a-43cbede7d57f.png)
Not sure if I configured it properly though.

**Comment by Arnklit** [comment]
I'm pretty sure the issue simply is that direct lighting doesn't work on the raytraced version. There is no difference in the result of baking with lights set to bake mode indirect and bake mode all when using the raytracing option.

Conetraced indirect:
![image](https://user-images.githubusercontent.com/4955051/102081399-12bd7a00-3e08-11eb-9d59-f5847d3d4b1b.png)

Conetraced all:
![image](https://user-images.githubusercontent.com/4955051/102081444-24068680-3e08-11eb-9785-1e48482835fd.png)

Raytraced indirect:
![image](https://user-images.githubusercontent.com/4955051/102081499-3d0f3780-3e08-11eb-9367-37716aa834af.png)

Raytraced all:
![image](https://user-images.githubusercontent.com/4955051/102081533-4ef0da80-3e08-11eb-91f0-be24db0842a5.png)

**Comment by akien-mga** [comment]
Fixed by #44628.
