### ISSUE TITLE
Crash on Android draw with a MeshInstance (V3.0)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#16831]
**Godot version:**

3.0

**OS/device including version:**

OnePlus 3  Android 8.0 

**Issue description:**
If any mesh is displayed on the screen, the application fails. 
If you hide it then all at once starts to work.
PS
The project has a log file from your phone "logcat.txt"

**Steps to reproduce:**

**Minimal reproduction project:**
https://yadi.sk/d/rRuIW0x73SafYg

**Comment by Zireael07** [comment]
Lemme guess, an Adreno device?

**Comment by ret80** [comment]
Qualcomm Snapdragon 820 MSM8996 
Adreno 530

**Comment by alex9099** [comment]
Similar to #12816 ?

**Comment by ret80** [comment]
Yeah, looks like the same problem.

**Comment by akien-mga** [comment]
Closing as duplicate of #12816.
