### ISSUE TITLE
Godot 2.1 to 3.0 exporter: problem with rotations in AnimationPlayer

### ISSUE THREAD

**Issue by laverneth** [godotengine/godot#16836]
When exporting projects from godot 2.1 to godot 3.0 I got issues with the conversion of rotations in the AnimationPlayer, they seems inverted. Reading comment of editor_export_godot3.cpp l525, the rotation in godot 30 are clockwise, and therefore the rotations in the animation should be also converted during the export.

In the small project attached the little godot face should go from right (-15) to left (30) counterclockwise. However, when exporting the project to godot 3.0 the rotations in the animation are the same and therefore the head move in the opposite direction since the orientation has changed.

[Test.zip](https://github.com/godotengine/godot/files/1738128/Test.zip)

**Comment by akien-mga** [comment]
Can you specify which 2.1 commit you tested with?

**Comment by laverneth** [comment]
Sure! Sorry! It was the 2.1.4 version

**Comment by akien-mga** [comment]
Well, weren't we discussing the latest version from git all along yesterday?...

**Comment by laverneth** [comment]
Hum, sorry. Yep, that's the 2.1, I don't know why I thought it was the
2.1.4.
The latest commit version I used was
https://github.com/godotengine/godot/commit/ddcbdbd67c94b1780025d3dedb16dbfb4baec272
Sorry, Rémy for this.

2018-02-20 9:50 GMT+01:00 Rémi Verschelde <notifications@github.com>:

**Comment by akien-mga** [comment]
No problem :) I'll dig in further.

**Comment by akien-mga** [comment]
Fixed by #17152.

**Comment by akien-mga** [comment]
I think I know why it doesn't work with `.scn`. The logic that converts the `NodePath()` happens only when writing text, I should move it earlier.
