### ISSUE TITLE
Tree's "item_activated" and "item_double_clicked" signals

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16839]
**Godot version:**
 ad5ac05

**Issue description:**
According with the docs, `item_activated` is emitted when an item is double clicked. However, there is a signal named `item_double_clicked` which says it does exactly the same thing.

I tested both, and seems that only `item_activated` is emitted, so what's the point of the other signal?

**Comment by akien-mga** [comment]
According to `git blame` it was added by @djrm in 70c9979cce, later modified by @volzhs.

**Comment by volzhs** [comment]
based on commit, `item_activated` is emitted when double click on label,
and `item_double_clicked` is emitted when double click on icon.

**Comment by YeldhamDev** [comment]
@volzhs I see. But neither the signal names or their descriptions even remotely imply that.

**Comment by volzhs** [comment]
need someone to update docs I think.
but... it's not me, not a native speaker.

**Comment by akien-mga** [comment]
Maybe we should start maintaining a new list for the stuff we'd like to rename the day where we'll allow ourselves to break compatibility.
