### ISSUE TITLE
Some problems with the Debugger's Stack Frames

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16844]
**Godot version:**
ad5ac05

**Issue description:**
- [ ]  When selecting an item to go for the line, the script editor will generally show said line either at the very top or bottom. This may be because it's not taking into account the opened bottom panel.
- [x] When selecting items when not running the game, this will be printed in the Output: `editor/script_editor_debugger.cpp:1280 - Condition ' connection.is_null() ' is true.` (Fixed by #16882).
- [x] Clicking on an already selected item will not make the script editor go for the line (Fixed by #16843).

**Comment by akien-mga** [comment]
I moved the first item to #24444, the other two are fixed.
