### ISSUE TITLE
godot seemingly crashes my graphics driver

### ISSUE THREAD

**Issue by metalDS** [godotengine/godot#16842]
**Godot version:** 3.0

**OS:** Windows 10 home

**graphics card:** Nvidia Geforce 940M

**Issue description:**
Godot seems to randomly freeze then crash for no apparent reason, and it some how affects the Nvidia driver too as I cannot re-open the program or any program (blender in my case) that uses it. 
I was able to re-open my program when I restarted the graphics driver in device manager, and I re-installed the driver so I would think that it's unlikely that it's a problem with the driver itself. I think I'm having a process time-out with my graphics card, but I don't have any experience with this kind of stuff so i wanted to get a more informed opinion

**Steps to reproduce:**
Unfortunately i cannot give any reproduction steps as my program seems to crash for any reason. it crashed a couple times when i was messing with the texture property of a sprite, and again when i closed the window of a scene simulation that had a debug error

it doesn't seem to be caused by any specific project so it's either a problem with Godot or my PC. the bug makes working nearly impossible, and i really want to learn this program so any advice would be appreciated

**Comment by Zylann** [comment]
I have the same graphics card on a Windows 10 laptop but never had such a crash.

**Comment by metalDS** [comment]
i found an earlier post that has the same issue so i'm closing this and redirecting
[https://github.com/godotengine/godot/issues/16372](url)
