### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by flamendless** [godotengine/godot#16848]
Is Godot 3 not working for devices with opengl 2.1 version? Godot 2.x works, please allow support for 2.1 version since my focus is 2D only.

**Comment by volzhs** [comment]
Godot 3.1 will have opengl es 2 renderer.
here is initial PR for it. #16687

**Comment by volzhs** [comment]
and... use community sites for asking a question.
https://godotengine.org/community

**Comment by Noshyaar** [comment]
2.1 branch is still being maintained.
