### ISSUE TITLE
AudioStreamPlayer3D and AudioStreamPlayer2D setting Stream issue.

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#16846]
**Godot version:**
Godot 3.0 stable

**OS/device including version:**
OS: Windows 8.1

**Issue description:**
I'm not sure it should be written as different issue or not. But I think that this 2 bug about AudioStreamPlayer3D and AudioStreamPlayer2D is related so I reported it under the same issue.
1. Error: !p_stream.is_valid() always shown when running a scene that have an AudioStreamPlayer2D Node or AudioStreamPlayer3D Node with null/unset Stream property. (Not happen with AudioStreamPlayer Node)
![image](https://user-images.githubusercontent.com/8316851/36408727-d34c1a50-1639-11e8-89eb-5a8954a30ffd.png)

2. If you set a Stream property in AudioStreamPlayer2D Node or AudioStreamPlayer3D Node you cannot unset it. (Click clear like in my screenshot below, nothing happen)
(Also Not happen with AudioStreamPlayer Node)
![image](https://user-images.githubusercontent.com/8316851/36408916-f494f168-163a-11e8-9a84-c96d75745413.png)

**Steps to reproduce:**
1. Create new scene
2. Add AudioStreamPlayer2D Node or AudioStreamPlayer3D Node.
3. Save Scene.
4. Do the same thing I did in Issue Description

**Minimal reproduction project:**

**Comment by chanon** [comment]
No.1 is really bugging me as I get lots of
![image](https://user-images.githubusercontent.com/357737/41595500-33ed0206-73f1-11e8-9f4b-fd0ac4511fe5.png)
in my console.
