### ISSUE TITLE
Can not see the text found in internal documentation

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#16840]
**Godot version:**
3.0 stable

**Issue description:**
Can not see the text found in internal documentation

**Minimal reproduction project:**
![2018-02-20 07-58-39](https://user-images.githubusercontent.com/11325733/36403032-391d1cd6-15da-11e8-98c1-cf9884b6a5b8.png)

**Comment by vnen** [comment]
Duplicate of #14410.

**Comment by Zylann** [comment]
It's on the top-right, and it's highlighted in black...
Also would be better to have it not a popup, since popups are obscuring the background and usually text editors have a more convenient docked search.
