### ISSUE TITLE
Godot 3.0 crashes when moving an asset used in an open scene.

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#16853]
**Godot version:**
3.0 stable, Windows 10

**Issue description:**
Selected a dae model and moved it into another folder, while that model was present in an opened scene. This resulted in a crash and I had to close the program. If you close the scene before moving the files everything works as intended. 

Shouldn't it be possible to move a model even though it's active in an opened scene? If not I think Godot should give a warning that the model you are trying to move is currently in use.

**Comment by reduz** [comment]
I think this test is already performed, but not quite sure.

**Comment by reduz** [comment]
As in, opened resources get their path changed in real-time.

**Comment by Zylann** [comment]
This happens in Godot 3.1 beta 1 as well, when I move a folder and one of its contents is used inside an opened scene (and sometimes, even when no scenes are open!)

**Comment by groud** [comment]
I cannot reproduce the bug myself, it would be good that someone could manage to get the stacktrace when Godot crashes.

**Comment by akien-mga** [comment]
Can you still reproduce it in the current master branch? There were fixes to the FileSystem dock recently that might have solved this.

**Comment by akien-mga** [comment]
Assuming fixed as it sounds like some of the bugs fixed recently. Please comment if you can still reproduce it.
