### ISSUE TITLE
Randomize particles local rotation when they spawn (Feature Request) 

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#16857]
Would be great if you could set a min-max value for something like Rotation on a particle.
In the example below I am shooting out a lot of small stones but they all have the same Rotation when they are spawned. If you could set some randomize value for local orientation it would look a lot better. 

![particles](https://user-images.githubusercontent.com/24936603/36430873-76d89c54-1656-11e8-97f6-8d098c09b81a.jpg)

**Comment by KoBeWi** [comment]
There's this option, which exists since 3.1:
![image](https://user-images.githubusercontent.com/2223172/67626622-fbab7980-f84d-11e9-83bc-2c32f5f33c67.png)
I guess it closes the issue.
