### ISSUE TITLE
Issue with stretch and keep ratio options on Nexus 7

### ISSUE THREAD

**Issue by arvejeitor** [godotengine/godot#16859]
**Godot version:**
3.0 stable

**OS/device including version:**

Nexus 7 (2nd gen) - Android 6.0

**Issue description:**

I'm testing exporting to Android with 2 devices, a Moto X (2nd gen) and a Nexus 7 (2nd gen). Both running Android 6. If I select aspect = keep under Display/Window/Stretch option on Project Settings, it works fine on the Moto X but the Nexus gets the image completely glitched immediatly after the Godot Splash Screen. But if select aspect = ignore it works... but since the resolution of the Nexus is 1920x1200 it gets stretched.
I tried to do the same on Godot 2.1.4 and worked fine with the keep ratio option enabled.

**Steps to reproduce:**
Just open any project and select aspect = keep under Display/Window/Stretch option on Project Settings and export to Android

**Comment by AlexHolly** [comment]
duplicate https://github.com/godotengine/godot/issues/17060? Also broken on https://github.com/AlexHolly/godot/commit/a651dbfe7e583267418a504597eaefb2d0da0ada

**Comment by akien-mga** [comment]
Closing as duplicate of #17060.
