### ISSUE TITLE
Making a FileDialog node visible in the editor causes errors

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16864]
**Godot version:**
 e3be5bb

**Issue description:**
When toggling a FileDialog's visibility on and running the game, it will output this error twice:
```
0:00:00:0450 - Condition ' !is_inside_tree() ' is true.
----------
Type:Error
Description: 
Time: 0:00:00:0450
C Error: Condition ' !is_inside_tree() ' is true.
C Source: scene/gui/control.cpp:2069
C Function: grab_focus
```
And it doesn't matter if the node's visibility is toggled off again, **or even it the project is reopened**, this errors will show up until the node is removed from the tree.

**Comment by Noshyaar** [comment]
I can't reproduce this with the given steps.

**Comment by YeldhamDev** [comment]
@Noshyaar Are you sure you're doing everything correctly?
![peek 2018-02-22 14-04](https://user-images.githubusercontent.com/30739239/36552764-6b6a3d6c-17d9-11e8-898b-550e83082b80.gif)

**Comment by Noshyaar** [comment]
I did exactly as shown and still couldn't reproduce it.

**Comment by YeldhamDev** [comment]
It doesn't appear to happen anymore. Closing it.
