### ISSUE TITLE
While loops are resetting themselves after completing condition

### ISSUE THREAD

**Issue by LockManipulator** [godotengine/godot#16868]
Godot 3.0 using GDscript.

Windows 10.

After a while loops completes, it resets and loops a second time.

To reproduce: 

```
extends Node
 
onready var planet = preload("res://Planet.tscn")
var planet_sizes = [0.15, 0.25, 0.35]
var created_planets = []
var goodtoadd = true
 
func _ready():
    randomize()
    draw_planets()
 
func draw_planets():
    while created_planets.size() < 3:
        print("looping")
        var planet_coords = Vector2(rand_range(50, 1870), rand_range(50, 1030))
        if not planet_coords in created_planets:   #if there is not already a planet at those coordinates
            print("not in")
            if len(created_planets) == 0:           #if there are no planets
                goodtoadd = true
            else:
                for existing in created_planets:                   # if planet is further than 35 pixels from all other planets
                    if planet_coords.distance_to(existing) < 35:
                        goodtoadd = false
                    else:
                        goodtoadd = true
        if goodtoadd:
            var s = planet.instance()
            add_child(s)
            s.position = planet_coords
            var size = planet_sizes[int(rand_range(0, 3))]
            s.set_scale(Vector2(size, size))
            created_planets.append(planet_coords)
            print(created_planets.size())
```

From the print statements you can see that the size of created_planets reaches 3, then somehow everything in it gets deleted and it loops through again.

**Comment by Zylann** [comment]
Isn't it deprecated to do `add_child` whithin a `_ready()` function?

**Comment by LockManipulator** [comment]
No error and I have no idea if it's deprecated or not. I didn't know how to do it so that's what I found online. Is there another way to spawn an instance of that sprite?

**Comment by vnen** [comment]
Do you have a small project that reproduce this issue? I can't reproduce with the code attached.

**Comment by LockManipulator** [comment]
https://www.dropbox.com/s/gzg966nv543beiy/Civ.zip?dl=0 Here is the project. It seems like the problem is actually being caused by func _ready(): being called twice.

**Comment by Zylann** [comment]
I created a new project in which I made a dummy `Planet.tscn` scene, so I could copy paste your code with no modifications. Here is the output:

```
looping
not in
1
looping
not in
2
looping
not in
3
```

I would say there is a problem in your project.

**Comment by LockManipulator** [comment]
Oh. Seems like my node is present twice. It's a child of MainMenu and then it gets called later. I just removed it as a child of MainMenu and calling it as before worked fine.

**Comment by reduz** [comment]
If there is no error, it should work. Generally add_child works on _ready
for the same node or children
