### ISSUE TITLE
set_attach_to_screen_rect() causes game to flicker on fullscreen

### ISSUE THREAD

**Issue by JustDevs** [godotengine/godot#16862]
**Godot version:**
3.0

**OS/device including version:**
Windows 10

**Issue description:**
When using set_attach_to_screen_rect() function in Godot 3.0, screen starts to flicker when in fullscreen mode.

**Steps to reproduce:**
Using get_viewport().set_attach_to_screen_rect(Rect2()) to a script should be enough for it.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
This is very similar to #10227, so I will close it due to likely the same cause.
