### ISSUE TITLE
CollisionShape2Ds with Rectangle/RayShape2D can be selected from anywhere in the editor (even when marked to not select children)

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16866]
**Godot version:**
e3be5bb

**Steps to reproduce:**
Self-explanatory:
![peek 2018-02-20 16-01](https://user-images.githubusercontent.com/30739239/36443404-61f97ab4-1657-11e8-855f-b850d9c48a3f.gif)

**Comment by akien-mga** [comment]
CC @groud
