### ISSUE TITLE
glTF scene import: ignores embedded images due to "data:" uri mime type

### ISSUE THREAD

**Issue by fzwoch** [godotengine/godot#16879]
**Godot version:**
5d6c64969cea4f1678ed3760c0353f8860ef661b

**OS/device including version:**
debian/sid NVIDIA 1060

**Issue description:**
glTF scene import does not load embedded images due to unhandled `data:` uri format.

I imported a glTF scene file with embeded texture data. I expected the model with the texture to be imported. The texture was missing and I think I got an error on console(?) about Godot was unable to import `data:image/png;base64` formats.

I have no knowledge of the glTF format, but it seems `data:` uris can have their image type's mime-type as uri mime-type as well instead of `application/octet-stream`?

The three.js editor at https://threejs.org/editor/ does seem to create such files on glTF scene export.

**Steps to reproduce:**
Import a glTF scene with embedded images of mime-type other than `application/octet-stream`.

**Minimal reproduction project:**
Sample glTF scene for importing:
[quaddamage.zip](https://github.com/godotengine/godot/files/1743546/quaddamage.zip)

**Workaround**
```diff
--- a/editor/import/editor_scene_importer_gltf.cpp
+++ b/editor/import/editor_scene_importer_gltf.cpp
@@ -1108,7 +1108,8 @@ Error EditorSceneImporterGLTF::_parse_images(GLTFState &state, const String &p_b
                if (d.has("uri")) {
                        String uri = d["uri"];
 
-                       if (uri.findn("data:application/octet-stream;base64") == 0) {
+                       if (uri.findn("data:application/octet-stream;base64") == 0 ||
+                           uri.findn("data:" + mimetype + ";base64") == 0) {
                                //embedded data
                                data = _parse_base64_uri(uri);
                                data_ptr = data.ptr();
```
With this change applied I'm able to import the glTF scene with the image data and the models is correctly textured.

**Comment by akien-mga** [comment]
That seems like the right fix, could you make a PR?

**Comment by akien-mga** [comment]
Actually you could even initialize `String mimetype = "application/octet-stream";` here: https://github.com/godotengine/godot/blob/master/editor/import/editor_scene_importer_gltf.cpp#L1099

And then just keep the `uri.findn("data:" + mimetype + ";base64") == 0` check.

**Comment by akien-mga** [comment]
Or not, just do it as proposed in the OP, that's safer (in case some glTF files have a mimetype but still use `data:application/octet-stream;base64` as uri.
