### ISSUE TITLE
Memory leak with the gui_input() signal in C# / Mono

### ISSUE THREAD

**Issue by Duehok** [godotengine/godot#16877]
**Godot version: 3.0 stable, Mono 5.4.1.7**

**OS/device including version: win 8.1**

**Issue description:**
C# only
The Godot.Object passed as argument of the signal gui_event(ev) is not disposed of when the method finishes and is not garbage collected unless explicitly disposed of with ev.Dispose().
Consequence: wiggling your cursor above a control with a C# script that listens to the event without disposing of the object will leak Godot Objects at a rate of 60/second.

The workaround is to call ev.Dispose() at the end of the gui_input method. It is bad practice to dispose of an object outside of its creation scope because there can still be references to this object, but it is no longer valid! I forgot to test what happens if several scripts listen to the same gui_input(ev). If the same object is reused in the different scripts then I will get a runtime exception ObjectDisposedException.

Possible solutions:
1) Emergency patch: Add this in the C# warnings in the docs:
http://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_basics.html#current-gotchas-and-known-issues
"Godot Objects passed as arguments of signals must be manually disposed of to avoid memory leaks. A method onGuiInput(Godot.Object ev) connected to the signal gui_input(object) must call ev.Dispose() before onGuiInput returns or ends."
Unfortunately I cannot use github right now, so I cannot do a pull request.

2) Best solution: automagically dispose of the object(s) when all the gui_input(ev) are finished.

3) If an automatic generation of the methods connected to signals is done before the solution 2) is implemented, add an ev.Dispose in the methods' bodies to help not to forget it.

**Steps to reproduce:**
Create any control, add a C# script to it, connect a method to the signal gui_input(object).
Run the scene and wiggle your cursor above the control while looking at the number of godot objects in the debugger's monitor tab.

**Minimal reproduction project:**
[InputEventObjectLeak.zip](https://github.com/godotengine/godot/files/1743286/InputEventObjectLeak.zip)

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by neikeq** [comment]
This is a regression and is only related to Reference objects that don't have a C# script. I'm trying to find a good way to fix it.

**Comment by Duehok** [comment]
A quick test seems to indicate that if one gui_input(object ev) is onnected to several metods, disposing of the object(s) in each method works fine. So the workaround is useable.
