### ISSUE TITLE
Can't play the game in a 2.1 channels audio system

### ISSUE THREAD

**Issue by maikramer** [godotengine/godot#16870]
**Godot version:**

v.3.1 d54e5a4 updated today

**OS/device including version:**

**Issue description:**

Today i discovered that my laptop is 2.1 channels, then i selected, but i cant use godot with this config, i need to change back to Stereo.

In the code i already saw that Pulseaudio is not compatible with 3 channels, are 2 or 4 in the detect_channels functions.

I just couldn't find any issue related, then i'm documenting here to fix this in the future.
There is a workaround without change my system audio settings?

**Steps to reproduce:**
Change system audio to 2.1

**Minimal reproduction project:**

**Comment by marcelofg55** [comment]
What PulseAudio version do you have? If I remember correctly older versions didn't support 3 channels and newer did.

**Comment by maikramer** [comment]
My computer is using 11.1, latest, even if my pulseaudio supports, the godot driver https://github.com/godotengine/godot/blob/master/drivers/pulseaudio/audio_driver_pulseaudio.cpp doesnt.

**Comment by Nutriz** [comment]
Same problem here with Ubuntu 17.10 and PulseAudio 10.0, when I launch my game the debugger always displays this :

![image](https://user-images.githubusercontent.com/7358899/36811821-634ee790-1ccf-11e8-8cf6-5fac5bc35ecf.png)

![image](https://user-images.githubusercontent.com/7358899/36812265-ed758f0e-1cd0-11e8-9d52-ce5ae64bbe57.png)
If I switch to analog stero, the errors in godot disappears.


Indeed, godot switch don't have the case for 3 for channels :
https://github.com/godotengine/godot/blob/c6dff58f491c30ffc2a81a8d69da86ff8105053f/drivers/pulseaudio/audio_driver_pulseaudio.cpp#L160-L170

**Comment by maikramer** [comment]
Yes, exactly the same here, Ubuntu 18.04 with pulseaudio 10

**Comment by marcelofg55** [comment]
I think I know how to fix this, I'll give it a try
