### ISSUE TITLE
File dialog button text is missing

### ISSUE THREAD

**Issue by maksloboda** [godotengine/godot#16885]
**Godot version: 3.0**

**OS/device including version: ubuntu 17.10 (64 bit), windows 10(64 bit)**

**Issue description:**
After project export "Open" button on file dialogs is empty

**Steps to reproduce:**
1.Export minimal project
2.Run
3.Button is empty 

**Minimal project:**
[filedialogbug.zip](https://github.com/godotengine/godot/files/1743856/filedialogbug.zip)

**Comment by Noshyaar** [comment]
Fixed by #16710

**Comment by Noshyaar** [comment]
Sorry, thought it was fixed by recent PR merge.

Issue confirmed.
