### ISSUE TITLE
TouchScreenButton not affected by set_process_input(false)...intended or bug?

### ISSUE THREAD

**Issue by Footurist** [godotengine/godot#16887]
Is it intended or a bug?

```
extends TouchScreenButton

func _ready():
    set_process_input(false)

func _on_TouchScreenButton_pressed(): # connected via inspector
    print("pressed")

*presses button*

Output: pressed
```

**Comment by akien-mga** [comment]
That's not a bug, `set_process_input(false)` just means that `_input(event)` will not be called. Signals are still sent.

**Comment by volzhs** [comment]
## void set_process_input( bool enable )
> Enables or disables input processing. This is not required for GUI controls! Enabled automatically if _input() is overridden. Any calls to this before _ready() will be ignored.

@akien-mga 
_"Enables or disables input processing."_
this description might be vague. is it better to mention about `_input(event)`?

**Comment by volzhs** [comment]
maybe... "Enables or disables `_input(event)` processing." is better?
