### ISSUE TITLE
"Override for" doesn't work after export

### ISSUE THREAD

**Issue by maksloboda** [godotengine/godot#16897]
**Godot version:**
3.0 and 612ab4bbc6f2396f4dcd68c3f142f7dfa2f5f0a5

**OS/device including version:**
Ubuntu 17.10(64 bit)

**Issue description:**
"Override for" in project setting doesn't work after exporting the game.
For example overriding main scene will have no effect at all and default main scene is still loaded

**Steps to reproduce:**
1.Export minimal project with custom feature tag "Game"
2.Run
3.If feature works, you should see text "Game default" but i personally see "Editor default"

**Minimal reproduction project:**
[tagbug.zip](https://github.com/godotengine/godot/files/1745561/tagbug.zip)

**Comment by kyledayton** [comment]
I noticed a probably-related issue in regards to `OS.has_feature`. Custom features defined in the export settings will always return `False` when queried via `OS.has_feature`. Using 3.0 via steam on Solus.

**Comment by maksloboda** [comment]
But OS::has_feature doesn't actually check custom features

**Comment by maksloboda** [comment]
Fixed by 25e64ffa20a15abe6c435ae8abf517be209fea53
