### ISSUE TITLE
add mechanism to prevent older version of godot from reseting AppData/editor_settings.xml

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1689]
Hi,

When I find a bug, it happens that I also test older versions of Godot to compare and to try to tell you when this bug appeared for the first time.

The problem is that when I try with a 1.0RC1, it resets the `AppData/editor_settings.xml`, and when I come back to 1.1beta, the file is reset again.

Maybe each major new version could use its own `AppData/editor_settings.xml` file ? 
And newer version could import the editor setting file of the previous version ?

**Comment by SuperUserNameMan** [comment]
should this one be closed ?

**Comment by bojidar-bg** [comment]
Well, given that it became `editor_settings.tres` and that 3.0 is now saving its settings elsewhere (with completely different names), I guess yes.
