### ISSUE TITLE
Debug menu: add "goto next/prev breakpoints", and "remove all breakpoints" at once

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1690]
Hi,

It could be useful to have such options into the Debug menu :
- go to next/previous breakpoint
- remove all breakpoints

**Comment by reduz** [comment]
add it to the list of editor improvements for 1.1 in the godot-devel google
group

**Comment by reduz** [comment]
for 1.2, sorry

**Comment by UsernameIsAReservedWord** [comment]
If you want me to add it to the shared spreadsheet, my limited internet connexion does not let me access it.
