### ISSUE TITLE
Enabling "One Way Collision" for KinematicBody2Ds doesn't seem to affect "move_and_slide"

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16900]
**Godot version:**
 7cd867c

**Issue description:**
I did a test by enabling `One Way Collision` to a collision owned by a KinematicBody2D, and expected the the `move_and_slide` function to completely ignore floors, but it acted as usual.

I don't know if this affects their 3D versions as well.

**Comment by eon-s** [comment]
Not sure if I understand, the Kinematic Character demo uses one way collisions and work, or are you using one way shapes in the body that is moved by `move_and_slide`?

Can you add an example project to see where it fails?

**Comment by YeldhamDev** [comment]
@eon-s I'm not talking about enabling it on the platforms, I'm talking about enabling it in the character itself.

**Comment by eon-s** [comment]
Not sure if one side is for that, is more for bodies that move against the one side shape rather than the one side shape moving against other bodies (I can see the uses it could have, though).

**Comment by YeldhamDev** [comment]
So this is more of a feature request rather than a bug, then?

**Comment by eon-s** [comment]
We should see what @reduz say about this, the new one side system is his child :P

**Comment by Calinou** [comment]
Closing in favor of #25313, which has a bit more information about the issue at hand.
