### ISSUE TITLE
C# Scripting No longer Working in Native App After Compiling From Source. 

### ISSUE THREAD

**Issue by hasahmed** [godotengine/godot#16911]
**Godot version:**

Hash of compiled version: e3be5bb61d7f8850c1d7a43dbc18f37107c2e317
Official Downloaded .App version: 3.0

**OS/device including version:**

OSX High Sierra
Graphics: Intel HD Graphics 4000 1536 MB

`mono --version` output:
Mono JIT compiler version 5.4.1.7 (2017-06/e66d9abbb27 Wed Oct 25 12:10:41 EDT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
        GC:            sgen (concurrent by default)

**Issue description:**

I already had Godot 3.0 with mono as the native osx app installed on my computer, then I cloned the godot git repo and compiled with C# as described in this [tutorial ](http://docs.godotengine.org/en/3.0/development/compiling/compiling_with_mono.html). Everything worked with compiled-from-source version just find, but then when I tried to run the Godot app that I had installed previously C# scripts no longer ran. The debugger Error log listed System.MissingMethodException as well as System.NullReferenceException.

**Steps to reproduce:**
Download Godot 3.0 with Mono on MacOs High Sierra.
Clone godot from git. Compile project with mono. 
Run the freshly compiled executable.
Attempt to run the original .app. 

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
You mean that you compiled your project solution in 3.1-dev, and then tried to load it again in 3.0-stable? If so that's normal, 3.1-dev has new features which are not backwards-compatible.

**Comment by akien-mga** [comment]
You mean that you compiled your project solution in 3.1-dev, and then tried to load it again in 3.0-stable? If so that's normal, 3.1-dev has new features which are not backwards-compatible.

You can delete your `.mono` folder and compile anew in 3.0-stable.

**Comment by hasahmed** [comment]
@akien-mga That solved the issue. Thanks.

**Comment by mhilbrunner** [comment]
Closing as it is solved.
