### ISSUE TITLE
Godot IDE opens up VSCode whenever scene-tab selected

### ISSUE THREAD

**Issue by KroanNL** [godotengine/godot#16923]
**Godot version:** 3.0

**OS/device including version:** Windows 10

**Issue description:**
The following is for when using Godot with Mono and VSCode as external editor.
Whenever a scene is selected that contains a node that has a script associated to it, Godot will open the external tool (in this case VSCode) to open that script automatically. This happens all the time, even if the script is already opened in VSCode and running in the background. 

(My) Expected behaviour would be that the script is only opened when the script button is used.

**Steps to reproduce:**
Make a new project in Godot and use C#. Set external editor to VSCode. Make two scenes. Add a node in one scene and attache a script. Switch between the scenetabs in the top. Whenever the scene with the node that has a script is selected, godot will open up VSCode.

**Comment by hasahmed** [comment]
Same issue on MacOS High Sierra

**Comment by exts** [comment]
Yeah kind of annoying. Maybe just make an option to not auto open external editor without disabling the external editor all together? That way if I already have all the scripts open I can switch to the editor when I'm done tweaking scenes.

**Comment by jasperdunn** [comment]
Hey guys,
this issue is still happening for me using godot-mono on macOS 10.14.6

**Comment by Pofriel** [comment]
Still getting this on macOS 10.13.6 with godot 3.1.1 mono with visual studio code as the editor.

**Comment by codewing** [comment]
Still there.
Windows 3.2 mono with vscode

**Comment by GonziHere** [comment]
Still here, Godot 3.2.1.64Bit mono on windows

**Comment by geomorillo** [comment]
Still not good on Godod 3.2.2.64 Bit
