### ISSUE TITLE
Folders marked as favorite does not disappear even if the original folder is deleted

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#16921]
**Godot version:**

3.0

**OS/device including version:**

**Issue description:**

A folder marked as favorite will still appear under favorites even when it has been deleted

**Steps to reproduce:**
Favorite a folder and then delete the folder, the folder will still appear under favorites. You have to unfavorite it before it disappears.

**Minimal reproduction project:**

**Comment by garuna-m6** [comment]
Need some help to start , new ,

 till now steps I took :
In
/editor/editor_file_dialog.cpp
in
void EditorFileDialog::update_file_list

I added a check condition of the existence of project but didn't work .

Any help , Thanks.

**Comment by Jason0214** [comment]
new to godot,

I notice confirm to remove file or directory will call **void DependencyRemoveDialog::ok_pressed()** in **editor/dependency_editor.cpp**, so I add a update of **favorite_dirs** in that function and fixed this bug. I already pull request, but not sure if it's the best implementation.

Besides, I find  move or rename a favorited dir also doesn't update the **favorite_dirs**,  I may further fix them
