### ISSUE TITLE
Whitespaces around arguments of functions generated by connecting signals via GUI are inconsistent with the style guide

### ISSUE THREAD

**Issue by anakimluke** [godotengine/godot#16933]
When a signal is conneced via GUI, a bit of code is automatically inserted into the script of the target node. For example:
```
func _on_VSlider_value_changed( value ):
    pass # replace with function body
```
Notice how there are whitespaces around `value`. This is inconsistent with the automatically generated `_process(delta)`, which doesn't have any whitespaces.

Godot's style guide does [mention briefly](http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_styleguide.html) the use of whitespaces, and style guide is inspired by Python's PEP 8 Style guide, of which [does recommend](https://www.python.org/dev/peps/pep-0008/#pet-peeves) to avoid such spaces.

**Comment by akien-mga** [comment]
Fixed by #16934.
