### ISSUE TITLE
Unable to Compile Editor on Linux ARM64

### ISSUE THREAD

**Issue by TritiatedWater** [godotengine/godot#16948]
**Godot version:**
 b6bf572 & 3.0

**OS/device including version:**
Debian GNU/Linux Stretch arm64.

**Issue description:**
Unable to compile godot editor on debian stretch arm64 due to thekla_atlas does not support arm64 (gives me POSH cannot determine target CPU)
Log:
[log.txt](https://github.com/godotengine/godot/files/1751739/log.txt)
 
I simpe patch should fox it.

**Steps to reproduce:**
`scons platform=x11 -j4 CXX=clang++-5.0`

**Comment by akien-mga** [comment]
Fixed by f12cb82e0f, thekla is no longer in use.
