### ISSUE TITLE
Allow to change fields values without capturing mouse cursor

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#16945]
Refers to this issue: #15351

**Godot version:**

Godot 3

**OS/device including version:**

All systems

**Issue description:**

I ask for a redesign of the input fields value change mode. For now, the system is:

1) You click field and start drag
2) Field captures mouse and mouse pointer is hidden
3) You change values (Mouse is captured, and sometimes because refered bug is not released)
4) On button release cursor is released too.

To me this is very invasive, it´s not neccesary at all to capture mouse. I propose do that:

1) You click field and start drag.
2) Field start to capture up/down left/right direction (normally up-right is + and down-left is -) and add/substract value no matters mouse is in or outside field.
3) On mouse release value stops to change.

This is UI improvement to godot and can free editor from a big bug factory (cursor capture).

**Comment by Zylann** [comment]
To clarify, this is when you drag the field, not when you just click it?
That would work if the fields react like Blender ones I think.

**Comment by Ranoller** [comment]
I fix text

**Comment by Ranoller** [comment]
In my opinion:
Good examples (cursor free):
Inkscape:
![goodexamplemousedrag](https://user-images.githubusercontent.com/11712737/36593432-f8a5930a-1899-11e8-8ea4-5966e8da6f22.gif)
Gimp:
![goodexamplemousedrag2](https://user-images.githubusercontent.com/11712737/36593436-ff1a62f6-1899-11e8-851d-ebdb27d184e9.gif)

Bad examples (cursor capturated):
Godot:
![badexamplemousedrag2](https://user-images.githubusercontent.com/11712737/36593447-076781be-189a-11e8-9cd5-e67074be8261.gif)
Blender:
![badexamplemousedrag](https://user-images.githubusercontent.com/11712737/36593449-0bf6232a-189a-11e8-8eb9-8f1f2cade01e.gif)

**Comment by Ranoller** [comment]
I have to say that the standard design is not like the blender/godot does. More examples:
Spine:
![standarbehavior](https://user-images.githubusercontent.com/11712737/36593799-955e6cfc-189b-11e8-8106-5121c19b196e.gif)
Reaper:
![standarbehavior2](https://user-images.githubusercontent.com/11712737/36593809-9a709058-189b-11e8-9ead-658e605215db.gif)
Krita:
![standarbehavior3](https://user-images.githubusercontent.com/11712737/36593819-a1ed14a0-189b-11e8-9d30-2336205b1733.gif)
Marmoset Hexels 2:
![standarbehavior4](https://user-images.githubusercontent.com/11712737/36593830-b2408da0-189b-11e8-86a6-0a795c424b87.gif)
Etc...

**Comment by Ranoller** [comment]
And godot have not consistence with the behavior:
![standarbehaviorgodot](https://user-images.githubusercontent.com/11712737/36593913-2f833e5c-189c-11e8-84d5-90ac10afd59a.gif)

**Comment by Noshyaar** [comment]
I don't like GIMP's slider for values that need precision. I can set any desired values to the decimals using Godot/Blender's method.

**Comment by reduz** [comment]
Problem is that Tree is used for too much in the inspector. This will
eventually be changed to something else.

**Comment by Ranoller** [comment]
But this is not because cursor free-captured, probably is because initial value are nos respected and fader click position is inmediatly changed:
![gimpfader](https://user-images.githubusercontent.com/11712737/36594453-770b54e2-189e-11e8-8160-a3b9fea0f6b5.gif)

... but this is not mandatory. You can start value change in actual value. If the control have limits up and down (That are needed and anctually godot have some faders without limit that allows to set 2398472389472894....) this is not problem, it´s not necessary to respect the init click, only the mouse movement...

**Comment by avril-gh** [comment]
This is common "feature" in apps on Windows OS, because Windows messaging works (bad) like that.
Messages are sent to control under cursor, so if you press mouse key, then move out of control and release, it does not receive WM_LBUTTONUP. Its rather hell than "feature" when you gota handle it.
Try it on calculator.exe

**Comment by Ranoller** [comment]
Yeah, should I open an issue in here?: https://github.com/billgates
:)

**Comment by raymoo** [comment]
With mouse capture you also don't run out of screen room to move your mouse into.

**Comment by Ranoller** [comment]
Thanks to all for the attention and opinions. With the new inspector we have all kind of flavors to insert data. An elegant solution was added (capture mouse if drag in the bar or not resalted knob and don´t capture if drag the resalted knob...). I feel that this is not an issue for now. So closing.
