### ISSUE TITLE
Allow selecting multiple nodes in animation tree player view and delete them

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#16941]
**Godot version:**
`master` / 6e200b1fe0b03bc0acc6d7ab097750d87aa7ac67

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** (This issue is a feature request)
Currently, there's no way to select multiple nodes from inside the animation tree player view, which can make it difficult to arrange or delete many nodes.

It'd be better if we can select multiple nodes by dragging the mouse inside the view and move or delete them at once.

**Comment by KoBeWi** [comment]
Seems to be implemented in new AnimationTree.

**Comment by akien-mga** [comment]
Thanks, closing as fixed.
