### ISSUE TITLE
Allow users to create plugin ideas on GitHub Issues tagged appropriately

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#16951]
**Issue description:**
There isn't a proper dedicated location in which people can get feedback from Godot developers regarding whether a plugin for the engine should be developed or how people might prefer to have it implemented. Some people have gone ahead and created posts of this kind regardless (like the DragonBones support request), but then they receive backlash for creating plugin-related posts on the main engine GitHub.

This is just a general discussion Issue to see whether people like the idea of allowing posts of these sort, but just giving them a dedicated tag for being a plugin idea.

For example, if I wanted to talk about the notion of creating a PluginScript for C++ using scons, that isn't really something that would *technically* be appropriate here, and yet, it would have huge ramifications for the engine's development. As such, I believe the engine could benefit from permitting posts of this sort.

**Comment by girng** [comment]
really hope this could be implemented
https://github.com/dear-github/dear-github/issues/44

can help with this as well +1 will.

**Comment by mhilbrunner** [comment]
What a huge response. :) I think having those posts here is fine. We already have a *topic:plugin* tag. If it becomes a problem due to many such posts, we can discuss it then. :)
