### ISSUE TITLE
Line2D tiling squishes textures horizontally

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16950]
**Godot version:**
 b6bf572

**Issue description:**
When having a Line2D with a texture and enabling the `Tile` mode for it, said texture will look horizontally squished if they're long enough.
This is the texture being used:
![bitmap](https://user-images.githubusercontent.com/30739239/36600041-f0fd52a0-188f-11e8-83d2-70f9bbaecb71.png)
And this is how it looks in the line:
![screenshot1](https://user-images.githubusercontent.com/30739239/36600032-e9d1691c-188f-11e8-94f5-055bc78d2391.png)

**Comment by Zylann** [comment]
I'm not sure to understand what's wrong here...

**Comment by Zylann** [comment]
Ok I found a fix, but master has another graphic bug, which will need a fix too...
