### ISSUE TITLE
Build error when compiling for iOS

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#16954]
**Godot version:** Godot Git https://github.com/godotengine/godot/commit/b6bf572e021f59ca9f6e95fca2e1cd08bd3fe0f2

**OS/device including version:** macOS on Travis CI

**Issue description:** Building an iOS export template fails with the following error:

```
platform/iphone/icloud.mm:147:1: error: control may reach end of non-void function [-Werror,-Wreturn-type,2]
 }
 ^
1 error generated.
scons: *** [platform/iphone/icloud.iphone.opt.debug.arm64.o] Error 1
scons: building terminated because of errors.
```

[Full build log on Travis CI](https://travis-ci.org/Calinou/godot-builds-ci/jobs/345317687)

**Steps to reproduce:** Compile an iOS export template from macOS.

**Comment by akien-mga** [comment]
That's because of #16914, but it's not a regression, it just indicates a pre-existing warning that we turned into an error and needs to be fixed.
