### ISSUE TITLE
Collision Polygon2d Messed Up? 

### ISSUE THREAD

**Issue by ZTarget** [godotengine/godot#16969]
**Godot version:**

3.0 and 3.0.1rc1 x11 64 

**OS/device including version:**

Linux 64 Manjaro

**Issue description:**

Can't get collision working on my tileset. (Maybe I am doing something wrong as Im new to the engine)
See picture. The shape always gets wonky.
**Steps to reproduce:**
Try and make collision work on this tile, here is the project (turn snap on and use 8px gridstep)

![colgodot](https://user-images.githubusercontent.com/35755702/36625044-a7596686-18dd-11e8-83bd-33e836209156.jpg)

**Minimal reproduction project:**

[Project_Test1.zip](https://github.com/godotengine/godot/files/1753969/Project_Test1.zip)

**Comment by Noshyaar** [comment]
The scene loads with correct shape on my machine. (Antergos x86_64 - bd3b958)
![image](https://user-images.githubusercontent.com/26753932/36625317-d843be82-194f-11e8-977b-c41af61b34fb.png)

**Comment by ZTarget** [comment]
Thanks for testing this
Ok it does work on my end on windows 7. I must have been mixed up with some other issues I was having earlier. I will edit my first post, this must be an issue with my linux OS or drivers.

Im using Manjaro here and was unable to get it to work correctly. I'll see if I can figure out if its my drivers.

**Comment by ZTarget** [comment]
So I screwed up Manjaro trying to get the nvidia driver installed. Manjaro was having a few problems with my system anyways so I installed Antergos. So fresh install of Antergos and no changes to any drivers. I'm getting the same problem, here is an example when I move it around a bit..
![godotcolproblem](https://user-images.githubusercontent.com/35755702/36629326-0021cb50-191a-11e8-8d1d-52d75f53f0e5.png)
My gfx card is a nvidia 9800gt ..so pretty old. If I put in "lspci -v" I get...

01:00.0 VGA compatible controller: NVIDIA Corporation G92 [GeForce 9800 GT] (rev a2) (prog-if 00 [VGA controller])
	Subsystem: Device 196e:0719
	Flags: bus master, fast devsel, latency 0, IRQ 30
	Memory at fd000000 (32-bit, non-prefetchable) [size=16M]
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	Memory at fa000000 (64-bit, non-prefetchable) [size=32M]
	I/O ports at cc00 [size=128]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: nouveau
	Kernel modules: nouveau

Could it be nouveau? What driver are you using Noshyaar?

**Comment by Noshyaar** [comment]
I'm using Mesa. But I'm still not convinced that it'd be driver-related.

**Comment by ZTarget** [comment]
Ok I got the nvidia driver installed on Antergos and now it is working correctly with a solid red color.
So thats good news :)

01:00.0 VGA compatible controller: NVIDIA Corporation G92 [GeForce 9800 GT] (rev a2) (prog-if 00 [VGA controller])
	Subsystem: Device 196e:0719
	Flags: bus master, fast devsel, latency 0, IRQ 30
	Memory at fd000000 (32-bit, non-prefetchable) [size=16M]
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	Memory at fa000000 (64-bit, non-prefetchable) [size=32M]
	I/O ports at cc00 [size=128]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	**Kernel driver in use: nvidia**
	Kernel modules: nouveau, nvidia

**Comment by qarmin** [comment]
I'm using Ubuntu  19.10 with Nvidia 970 and everything works.
Do you still have problem with collsion polygon?

**Comment by ZTarget** [comment]
Unfortunately I don't have a system set up right now with nouveau installed on it. Put this in your terminal to see if you are running it "lspci -v" see my previous 2 posts the bold line should be 
Kernel driver in use: nouveau
then run the test in the first post
This could still be a bug as far as I know.

**Comment by Calinou** [comment]
If this is driver-specific, I'm not sure if we can do anything about this. Nouveau in particular is known to be buggier than other open source drivers and is prone to regressions (due to its reverse engineering nature).
