### ISSUE TITLE
File deleted when renaming it to change it's case

### ISSUE THREAD

**Issue by justinluk** [godotengine/godot#16979]
**Godot version:**
3.0.1 RC1

**OS/device including version:**
Windows 10

**Issue description:**
When trying to rename a file from World.tscn to world.tscn, this version of Godot just deleted the file instead of renaming it. In 3.0 you'd get a message saying that the file already exists, but here it just deletes it.

**Steps to reproduce:**
Create a scene and save it with whatever name you want. Then try to rename it by only changing the case of some some of the characters.

Save a scene as hello.tscn and try renaming it to Hello.tscn

**Comment by akien-mga** [comment]
Thanks for the report! @hpvb is working on it right now.

**Comment by akien-mga** [comment]
Fixed by 8cde69f5f.

**Comment by justinluk** [comment]
That was fast! Thanks so much for the fix! :D
