### ISSUE TITLE
C# Export keyword issue - Godot 3.0 Mono Stable

### ISSUE THREAD

**Issue by alexbosquin** [godotengine/godot#16972]
**Godot version:**
3.0 Stable Mono

**OS/device including version:**
Windows 10 64-bit
NVidia GTX 760

**Issue description:**
  Using the [Export] keyword on C# not changing variable value
`
    namespace Game.Characters
    {

    public class Player : Character
    {
        [Export]
        private byte playerID;

        public Player()
        {
            this.managerState = new PlayerMachine(this);
            this.inputHandler = new PlayerInputHandler(playerID);
            GD.Print("player id is: ", playerID);
            checkAttributes();
        }

    }

    }
`
PlayerID should be 1 or 2 (on changing in the inspector) but it is always 0(zero)

**Steps to reproduce:**
Create a player node (Kinematic2D)
attach C# script
insert as below:
`
    public class Player : KinematicBody2D
    {
        [Export]
        private byte playerID;

        public Player()
        {
            GD.Print("player id is: ", PlayerID);
        }

    }
`
*change the playerID attribute on inspector to any else zero
*Run the game and see the print result

**Comment by alexbosquin** [comment]
guys the problem was my code:

`namespace Game.Characters
{

public class Player : Character
{
    [Export]
    private byte playerID;

    public Player()
    {
        this.managerState = new PlayerMachine(this);
        GD.Print("player id is: ", playerID);
        checkAttributes();
    }

    public override void _Ready()
     {
        this.inputHandler = new PlayerInputHandler(playerID);
    }


}

}
`

changing the inputhandler to Ready solved the problem!!!

**Comment by unreadable** [comment]
@alexbosquin feel free to Close the issue if you managed to solve it
