### ISSUE TITLE
Buttons on material slots in MeshInstance bugged when trying to animate material properties.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#16976]
Godot version: v3.0.stable.official (also present in 3.0.1rc1)
OS: Xubuntu 17.10 64bit

Issue description:
When trying to animate material properties with the AnimationPlayer node, the selection buttons on the material slots on for example, a MeshInstance node, get bugged out.
The little downwards dropdown menu arrow button displaces to the left of the material thumbnail, and the clickable area on the thumbnail also gets very narrow, there is also no key button present like there is with other properties.

This makes it quite confusing when trying to animate properties inside Material resources.
![01](https://user-images.githubusercontent.com/781121/36630441-aec40c58-1966-11e8-87c4-6855afcf8c17.jpg)

Steps to reproduce:
1. Create a scene and add any node that uses material slots/material override slots, for example MeshInstance
2. Add a SpatialMaterial to the MeshInstance node.
3. Add an AnimationPlayer node, and ofcourse a new animation.
4. Select the AnimationPlayer node so that the Animator panel opens.
5. Select the MeshInstance node and notice the material slots mess up.

Update: This only seems to happen when the roll back to default button on the right side is present, if there is no default material in the MeshInstance, it behaves as intended.

**Comment by reduz** [comment]
This code no longer exists, so closing this issue.
