### ISSUE TITLE
Mac OS Mono version Doesn't open

### ISSUE THREAD

**Issue by dovker** [godotengine/godot#16980]
Hello,

I tried to download Mono Version of Godot and it doesn't open.
Video shows the issue:
https://youtu.be/jW6uFPaUZJE

File name:
Godot_v3.0-stable_mono_osx64 18.00.02.app

Mac OS Version:
10.13.1

Computer:
Retina 5K, 27-inch, Late 2015

If I am doing something wrong, don't judge me :)

Thanks.

**Comment by Calinou** [comment]
Do you have Mono installed on your system? It is required to use the Mono-enabled version of Godot.

**Comment by dovker** [comment]
Yes, I do have mono Installed. I needed it for monogame. I will try 5.4 though

**Comment by dovker** [comment]
The 5.4 version works. Thank you!
