### ISSUE TITLE
Windows 10 - TypeError: cannot concatenate 'str' and 'NoneType' objects when building 3.0.1

### ISSUE THREAD

**Issue by exts** [godotengine/godot#16999]
**Godot version:**
[3.0.1 Stable](https://github.com/godotengine/godot/releases/tag/3.0.1-stable) - ae540c2efe2a323839241599dcf1181f6e85166a

**OS/device including version:**
Windows 10

**Issue description:**
Couldn't build with mono support. Command line spit out an error

```
C:\temp\godot301>scons p=windows tools=yes module_mono_enabled=yes mono_glue=no
scons: Reading SConscript files ...
Detected MSVC compiler: amd64
Compiled program architecture will be a 64 bit executable (forcing bits=64).
TypeError: cannot concatenate 'str' and 'NoneType' objects:
  File "C:\temp\godot301\SConstruct", line 327:
    detect.configure(env)
  File "./platform/windows\detect.py", line 170:
    env.Append(CCFLAGS=['/I' + os.getenv("WindowsSdkDir") + "/Include"])
```

**Steps to reproduce:**

- Downloaded zip from the link above
- Traveled to the project folder
- Ran the following command: `scons p=windows tools=yes module_mono_enabled=yes mono_glue=no`
- Error got spit out

**Minimal reproduction project:**
_Didn't get this far_

**Comment by exts** [comment]
@akien-mga hmm, not sure. I got it to work previously without issue on a master version, I even [wrote a guide](http://idiotcoder.com/godot3-csharp-visual-studio-code-windows10/) on how I got it working, but yeah now it doesn't seem to want to work right now. That build was on master on like Feb 21st which I had no issues building with my current setup. 

I'll try attempting it again to see if I did something incorrectly, but yeah seems odd.

**Comment by akien-mga** [comment]
From a quick glance I don't see anything in 3.0.1 that could explain such issue, so I would think that something is wrong on your end. Can you try to build f3f49ca again and see if it works or gives the same error now?

**Comment by exts** [comment]
@akien-mga this is very weird, I installed visual c++ 2017 build tools and now it's building. I was using 2015 originally, so idk how much of an impact that had.

**Comment by reduz** [comment]
What should be done with this?

**Comment by exts** [comment]
I haven't had issues in 6 months building with vs studio build tools 2017. Haven't tested 2015 since then. @reduz

**Comment by akien-mga** [comment]
This was fixed a few months ago.
