### ISSUE TITLE
Can we have Atom extensions for Godot?

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#16997]
Is it possible to make an an Atom extension that supports Godot, and it supports all the languages such as GDScript, C#, GDNative C++ etc?

**Comment by Zylann** [comment]
One for GDScript exists for VSCode, so yes, but I don't think this question has its place on Godot's issue tracker.

**Comment by vnen** [comment]
Well, anyone can do it if they want. But we have too much on our plates already, this is not something for this issue tracker indeed.

**Comment by neikeq** [comment]
There are already C# and C++ extensions for Atom, AFAIK.
