### ISSUE TITLE
Single RigidBody2D's not constrained by PinJoint2D's in 3.0 as in 2.1

### ISSUE THREAD

**Issue by Zadck** [godotengine/godot#16992]
Godot Version: 3.0 Official

PinJoint2D's on all RigidBody2D's set in either Rigid mode in all projects in 3.0 would seem to be doing nothing. The RigidBody2D node is not constrained, and simply falls.

Setting node_b to another RigidBody2D will still create a working joint. However, in 2.1, it was not necessary to define the node_b to another RigidBody2D to make them function. It would now seem to be mandatory, but I can find no documentation on this--and the 3.0 documentation that exists says a PinJoint2D can "pin a single body to a fixed position in space" ( http://docs.godotengine.org/en/3.0/classes/class_pinjoint2d.html ) so I assume that this is a bug.

This has been tested in a brand-new project I made but I did not save it. You can see an example of a PinJoint2D functioning pinned to a single RigidBody2D (in Rigid Mode) in 2.1 in the 2.1 Physics Platformer demo, and download the 3.0 Physics Platformer demo as a "example" project to this issue. This same setup, and all basic setups like it, does not work in 3.0:
![2_1](https://user-images.githubusercontent.com/36769730/36635708-76a1853a-197f-11e8-81b1-24a68d6cf5ce.PNG)

**Comment by Zadck** [comment]
@BeayemX Right, and I know that you can have a PinJoint2D pin two RigidBody2D's together by filling out both Node A and Node B, and that this is currently working in 3.0. 

What is not working, and what this bug report is about, is pinning a single body to a point in space instead of another RigidBody2D. This is documented as a feature of PinJoint2D's in 3.0 ( http://docs.godotengine.org/en/3.0/classes/class_pinjoint2d.html  ) and worked in 2.1. In 2.1, you could simply fill in Node A and then place the PinJoint2D wherever you wanted. There has been no documentation on this change, which leads me to think it is a bug and not a documentation error.

**Comment by Zylann** [comment]
I also found the pin is not working if its parent is not a physics body, while it was working in 2.x (I realized that watching a video about it)

**Comment by reduz** [comment]
This should be fixed now, because the editor does not allow you to pick something not a physicsbody
