### ISSUE TITLE
Nodes attached to a KinematicBody randomly get stuck in space

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#16994]
**Godot version:**
`master` / 6e200b1fe0b03bc0acc6d7ab097750d87aa7ac67

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
I have a 3D character with rigged animations. I made the root of the hierarchy as `KinematicBody` and attached other items like hair, clothes, and camera to it.

Then within `_PhysicalProcess`, I move the whole hierarchy with `MoveAndSlide` and also change position of a single control bone in the same process.

About 8 out of 10 times, it works as expected. But sometimes, random parts like camera or hair, or even multiple bones 'fall apart' from the character when I move it, resulting in something quite interesting as shown in the screenshot below (I wish I could make a video of it - it actually looks way cooler when it moves) : 
![screenshot_20180225_083640](https://user-images.githubusercontent.com/2367032/36636656-1ccb6ab4-1a0e-11e8-9c92-3a22edd2f730.png)

When it happens for such items like clothes or bones, they get stuck in the space but still move according to the character animation, albeit in a distorted manner.

I know it's a bit vague but have little idea how to track down the problem further. If you could suggest any way to test it on my part, please let me know.

**Comment by mysticfall** [comment]
It took me more than 30 attempts to reproduce it and capture it to a video, and it was totally worth it :stuck_out_tongue:  :
 * https://www.youtube.com/watch?v=OIheviCea20

I feel tempted to somehow find a way to reliably reproduce it and make a game out of it.

**Comment by mysticfall** [comment]
It may or may not be relevant to my issue, but someone from the Discord channel suggested that #16450 looks similar to this problem.

**Comment by mysticfall** [comment]
Most relevant code that pertains to the issue can be seen from this location:
 * https://github.com/mysticfall/AlleyCat/tree/master/Program/AlleyCat/Locomotion

As you can see, it's relatively simple code and the most unusual thing I'm doing is probably changing bone position by code every physical frame, which I believe to be a permitted operation.

And sometimes even the camera is detaching (or getting stuck in space) from the character hierarchy in the same manner as clothes do, so I doubt if it's something related to the way the character is rigged or how I'm moving one of its bones that could be the main cause.

**Comment by AndreaCatania** [comment]
Is it possible for you test if this bug still happen with: #28909

**Comment by mysticfall** [comment]
In fact, I haven't seen this symptom for quite a while. I'm not too sure what exactly, but apparently something must have fixed the issue for me already.

I'll reopen the issue if I ever see it happen again. Thanks!

**Comment by AndreaCatania** [comment]
Ok let me know thanks
