### ISSUE TITLE
Error compiling without builtin_mbedtls=no

### ISSUE THREAD

**Issue by robfram** [godotengine/godot#16991]
**Godot version:**
master (3647ebc8341ea22dce07d7eb5e47ece8d29c5565).

**OS/device including version:**
FreeBSD 11.1-RELEASE-p4

**Issue description:**
Can't compile without `builtin_mbedtls=no`. The following error message is resulting:

```
thirdparty/mbedtls/library/aes.c:1293:20: error: use of undeclared identifier
      'MBEDTLS_ERR_AES_FEATURE_UNAVAILABLE'
        if( ret == MBEDTLS_ERR_AES_FEATURE_UNAVAILABLE && keybits == 192 )
                   ^
thirdparty/mbedtls/library/aes.c:1357:20: error: use of undeclared identifier
      'MBEDTLS_ERR_AES_FEATURE_UNAVAILABLE'
        if( ret == MBEDTLS_ERR_AES_FEATURE_UNAVAILABLE && keybits == 192 )
                   ^
thirdparty/mbedtls/library/aes.c:1422:20: error: use of undeclared identifier
      'MBEDTLS_ERR_AES_FEATURE_UNAVAILABLE'
        if( ret == MBEDTLS_ERR_AES_FEATURE_UNAVAILABLE && keybits == 192 )
                   ^
3 errors generated.
scons: *** [thirdparty/mbedtls/library/aes.x11.tools.64.llvm.o] Error 1
scons: building terminated because of errors.
```

Definitions are in `thirdparty/mbedtls/include/mbedtls/aes.h`, and `thirdparty/mbedtls/library/aes.c` has this code:
```
#if defined(MBEDTLS_AES_C)

#include <string.h>

#include "mbedtls/aes.h"
```
Perhaps somehow `MBEDTLS_AES_C` is not defined if using FreeBSD.

**Steps to reproduce:**
$ scons platform=x11 use_llvm=yes builtin_mbedtls=yes

**Comment by Faless** [comment]
I've just tried compiling with FreeBSD `11.1` and I'm actually getting an error about malloc.h not being available on FreeBSD, fixing that, it compiles fine.

**Comment by Faless** [comment]
woops, my bad, you are right, it fails, didn't clean before building. though it's actually pretty strange

**Comment by Faless** [comment]
@robfram  from #16497 

> I understand no ssl library is needed installed in the system then, like openssl. Any dependence required to compile? Any package version? What scons command line arguments did you use?
> 
> Which version of LLVM are you using? I'm not sure if it's using 5.0.0 or 4.0.1.

`builtin_mbedtls=yes` does not appear to work on FreeBSD, if you install `mbedtls` system-wide and build with `builtin_mbedtls=no` you'll still get an error about `malloc.h` from the lws module (which lws has fixed in the upstream dev branch but not in the released version). I fixed the `malloc.h` error (will PR it soon) and I'm trying to fix the other error (unable to use `builtin_mbedtls=yes`) not sure what's wrong there.

> ok. I didn't do it because I though the compilation error was more an openssl case than the mbedtls.

OpenSSL has been completely removed from master, If you can compile the `3.0` branch then there's no need to worry about OpenSSL again

**Comment by Faless** [comment]
It appears that the error only happens if you have `mbedtls` installed

**Comment by robfram** [comment]
I'm going to remove the `mbedtls` pkg and do a clean recompile to see if at least it compiles that way.

**Comment by robfram** [comment]
Good! No more `mbedtls` compilation errors with `builtin_mbedtls=yes`. I think it is due a conflict as it imports the wide system one instead the builtin one.

But I still got the openssl error from #16497 😢

**Comment by Faless** [comment]
> Good! No more mbedtls compilation errors with builtin_mbedtls=yes. I think it is due a conflict as it imports the wide system one instead the builtin one.

Yes, the problem is inclusion order (not sure why it only happens in FreeBSD)



> But I still got the openssl error

I'll try to install OpenSSL and see what happens

**Comment by robfram** [comment]
I don't know if it is important, but from this conversation I think this line is quite offending:
```
/usr/local/include/openssl/x509.h:823:1: note: previous declaration is here
DECLARE_ASN1_FUNCTIONS(X509)
```

If I didn't misunderstand, openssl is not needed system wide anymore, so it shouldn't include something like `/usr/local/include/openssl/xxxxx` ever.

**Comment by Faless** [comment]
> If I didn't misunderstand, openssl is not needed system wide anymore, so it shouldn't include something like /usr/local/include/openssl/xxxxx ever.

Indeed, and for what I could see we aren't

**Comment by Faless** [comment]
Anyway, I can reproduce the error with openssl installed

**Comment by Faless** [comment]
I found the source of the inclusion, but more problems seems to arise...

**Comment by robfram** [comment]
I locally fixed the `malloc` issue and it compiles without `openssl` or `mbedtls`. Not the best solution requiring removing system packages, but it works.

**Comment by Faless** [comment]
@robfram can you try if it works with #17115 (should work in every case, no matter if you have OpenSSL and/or mbedTLS installed)

**Comment by robfram** [comment]
@Faless I reinstalled both `openssl` and `mbedtls`, did a `git clean -f -x thirdparty/lws` and it compiles all that sources without errors. Got a linker error with `modules/libmodules.x11.tools.64.llvm.a` but I assume it's because I need a full clean compilation, which I'm going to do right now.

**Comment by robfram** [comment]
After 40 minutes compiling, 0 errors. All fixed. Thanks!
