### ISSUE TITLE
"clamp" built-in function causes an error when exporting on Android

### ISSUE THREAD

**Issue by Mikepicker** [godotengine/godot#1699]
A simple execution of "clamp" causes this error: ERROR: finalizeSwipeAction: Invalid call to built-in function 'nearest_po2'. Expected 1 arguments.

The error only appears "logcatting" an android device (adb logcat | grep godot), while there are no errors upon desktop deployment.

**Comment by reduz** [comment]
ah this is most likely because templates are from beta 1.1 and build is
from github, will soon release a new beta
