### ISSUE TITLE
Calling Thread.Start() in C# causes a crash

### ISSUE THREAD

**Issue by Flascher** [godotengine/godot#17009]
**Godot version:**
3.0.stable.official.mono
3.0.1.devel.official.mono

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When trying to start a thread with Godot's `Thread` object in C# the client crashes.

I did see a potentially related issue with #16024 but the last comment there claims it should be fixed in 3.0.1. Unfortunately this still crashes in 3.0.1-rc1 for me.

**Steps to reproduce:**
1. Create a new `Thread` object
2. Start the thread with any object instance and one of its methods
3. Run project and confirm that the Godot client crashes.

**Minimal reproduction project:**
[CrashTest.zip](https://github.com/godotengine/godot/files/1755872/CrashTest.zip)

**Comment by LaBlazer** [comment]
Any progress on this? Having the same issue...

**Comment by Laaas** [comment]
This isn't really a solution, but why would you use Godot to spawn threads instead of the .NET runtime?

**Comment by LaBlazer** [comment]
@Laaas neither works

**Comment by neikeq** [comment]
Closing as duplicate of #16024

As I mention there, while this issue is open, you can use `System.Threading.Thread` instead.

**Comment by neikeq** [comment]
I was looking some old issues and I just noticed @LaBlazer commented that neither Godot nor .NET spawned threads work. Is this true? The issue with Godot threads is being tracked in #16024, but any issues with `System.Threading.Thread` are unknown to me. If it's really not working, please open a new issue with more details.

**Comment by ArthurAttout** [comment]
Standard `System.Threading.Thread` have always worked fine with me, but indeed, Godot's threads are completely broken as of 3.0.6
