### ISSUE TITLE
Custom mouse pointer not working properly

### ISSUE THREAD

**Issue by Nobelix** [godotengine/godot#17018]
**Godot version:**
3.0 stable

**OS/device including version:**
Ubuntu 16.04
Gnome

**Issue description:**
When setting a custom mouse pointer trough project settings or code it does nothing at all, the mouse pointer is the default one.

**Steps to reproduce:**
Set a custom mouse pointer...

**Comment by mrcdk** [comment]
Custom mouse images must be 32x32 pixels and png format. Anything bigger or smaller won't work.

**Comment by Nobelix** [comment]
Oh right, thanks :D

**Comment by akien-mga** [comment]
This probably needs at least some documentation, at best an editor warning if you set a texture with an invalid size.

**Comment by Nobelix** [comment]
And I just noticed that when you have a custom mouse pointer and you set your mouse mode to captured, after going back to visible mode the mouse pointer is the default one...

**Comment by voithos** [comment]
Yeah, this should definitely at least be documented in [the custom mouse tutorial](http://docs.godotengine.org/en/3.0/tutorials/inputs/custom_mouse_cursor.html). Right now the instructions just say that the image must "be less than 256x256"... which... well, is technically correct, but...

![image](https://user-images.githubusercontent.com/744228/44953335-aaba1400-ae48-11e8-8f56-c55dfc7baab2.png)

**Comment by guilhermefelipecgs** [comment]
> This probably needs at least some documentation, at best an editor warning if you set a texture with an invalid size.

This already have editor warning and documentation/class ref. You can close this.

https://github.com/godotengine/godot/blob/ebd14a778d29e0de4904564a762358cbc2412303/platform/windows/os_windows.cpp#L2261

https://github.com/godotengine/godot/blob/ebd14a778d29e0de4904564a762358cbc2412303/doc/classes/Input.xml#L297

http://docs.godotengine.org/en/latest/tutorials/inputs/custom_mouse_cursor.html#using-project-settings

**Comment by guilhermefelipecgs** [comment]
> And I just noticed that when you have a custom mouse pointer and you set your mouse mode to captured, after going back to visible mode the mouse pointer is the default one...

This was fixed for 3.1.

**Comment by akien-mga** [comment]
Thanks!
