### ISSUE TITLE
Blue/ Pink colored 3D editor grid render bug.

### ISSUE THREAD

**Issue by ngmgit** [godotengine/godot#17029]
**Godot version:**

3.0

**OS/device including version:**

Arch Linux / HD 4250 Oboard GFX
OpenGL ES 3.0 Renderer: AMD RS880 (DRM 2.50.0 / 4.14.20-1-lts, LLVM 5.0.1)
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144

**Issue description:**

The grid for 3d editor has different colors like blue/pink instead of white.
This maybe a render issue. 2D editor doesnt have any such issue.
As we zoom out of he scene the color is all over the grid.

**Steps to reproduce:**
Switch to 3D editor with no scene open which has blue color grid.
If a 3D scene is opened in the 3D editor the grid has pink color. 

Without any 3D Scene opened.
![screenshot_20180224_121337](https://user-images.githubusercontent.com/10939602/36660256-8949b3ae-1afd-11e8-869a-e4a2fa23e491.png)

With 3D scene opened.
![screenshot_20180226_133624](https://user-images.githubusercontent.com/10939602/36660271-961204d8-1afd-11e8-8926-7f996514ffd8.png)

**Comment by ngmgit** [comment]
Today i used a Nvidia GPU and this issue was present. 
And when i again used the onboard AMD HD4250 it was back.

**Comment by eon-s** [comment]
Mesa version?

**Comment by Creuilcreuil** [comment]
here are my specs, since i did not mention them in the duplicate #17270 
OpenGL renderer string: AMD RS880 (DRM 2.43.0 / 4.4.0-116-generic, LLVM 5.0.0)
OpenGL version string: 3.0 Mesa 17.2.8
[AMD/ATI] RS880M [Mobility Radeon HD 4225/4250]

**Comment by Calinou** [comment]
Radeon HD 4000 series GPUs are very old, they don't support modern OpenGL versions *well* (even though they may advertise support for it on Linux).

**Comment by eon-s** [comment]
@Creuilcreuil no idea if it will solve something but you can try latest mesa drivers from here if using AMDGPU drivers https://launchpad.net/~ubuntu-x-swat/+archive/ubuntu/updates

**Comment by reduz** [comment]
This may be fixed in 3.2, with move to Vulkan

**Comment by Calinou** [comment]
>This may be fixed in 3.2, with move to Vulkan

Such old GPUs will never support Vulkan :smiley:

**Comment by akien-mga** [comment]
No recent update, and it's unlikely that we'll be able to fix this as it's due to hardware and driver-specific issues, so closing.
