### ISSUE TITLE
Disabling Godot's Auto Resizing

### ISSUE THREAD

**Issue by Capital-EX** [godotengine/godot#17026]
**Godot version:** 3.0 stable

**OS/device including version:** Ubuntu 16.04 LTS

**Issue description:**
Godot will always automatically resize a window to fit on to the _smallest_ combination of display sizes.  This behavior causes issues on mixed display size setups.  In my case, I have one monitor that is set to 1200 x 1600 and two that are at 1920 x 1080. This causes Godot to use the display size 1200 x 1080 as my display size.
 ![size difference](https://user-images.githubusercontent.com/13488718/36651804-b75cc6ee-1a78-11e8-98bf-db22cf61857c.png)
The above image shows Godot resizing a window from 1280 to 1200 pixels across.  Since there is no setting to disable this, `OS.window_size` is required to correct it.

**Steps to reproduce:**
1. Set the window of a project to be larger than your display
1. Run the project

**Comment by Capital-EX** [comment]
It appears that this only happens on Linux.

**Comment by Calinou** [comment]
@Capital-EX Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

> It appears that this only happens on Linux.

I would consider this to be a bug in this case. The behavior should be as consistent as possible across platforms.

**Comment by Capital-EX** [comment]
@Calinou I don't know if I'll be able to recreate it.  I no longer have that Linux setup nor monitors when I first posted this.  I can try, but it'll have to wait until this weekend.

**Comment by akien-mga** [comment]
Closing for now as we couldn't confirm if it's still reproducible. If anyone experiences the same issue, please comment and we can reopen it.

**Comment by hhhapz** [comment]
Hey, I can reproduce this issue. However, I have two monitors that are both 1920x1080 on Wayland, however this also happened on X11.

I'm using a tiling window manager, however new windows correctly open as floating, however their sizing is very inconsistent and they are almost never centered.

Sometimes, they open up as small as this:
![image](https://github.com/user-attachments/assets/7b6538bb-6c7d-4364-b689-7e5ea5bab407)

other times, in different corners of the screen and other times bigger than the size of my monitors.
