### ISSUE TITLE
Memory leak in [EtcFilter.cpp:310] 

### ISSUE THREAD

**Issue by fangang190** [godotengine/godot#17032]
**Godot version:**

79a225ac2a2f2353f2f626809b56229397dfe52d

**OS/device including version:**

**Issue description:**

contrib leaks if the malloc fails on line 228. 

**Steps to reproduce:**
![screenshot from 2018-02-26 16 47 10](https://user-images.githubusercontent.com/1679432/36660941-c7510938-1b14-11e8-9d77-ad9540804b06.png)

**Minimal reproduction project:**

**Comment by Chaosus** [comment]
Fixed by #17035
