### ISSUE TITLE
Disabled Button can grab focus even with Enabled Focus set to none

### ISSUE THREAD

**Issue by hickop** [godotengine/godot#17037]
**Godot version:**
3.0.1

**OS/device including version:**
Linux

**Steps to reproduce:**
- Create button and set it to disabled
- Set Enabled Focus to none
- Run and click disabled button

If button is not disabled it can't get focused with Enabled Focus set to none.
Also, disabled buttons could not get focused at all in 3.0, is this a regression ?

**Comment by Noshyaar** [comment]
Related to #16152 by @hpvb

**Comment by hickop** [comment]
I think I might have been confused with enabled_focus_mode and focus_mode options.
Just need to set focus_mode to none.

**Comment by gamergamesz** [comment]
It is still happening in 3.2 even though i set Enabled Focus Mode to None

**Comment by Exomode** [comment]
I confirm that the undeveloped behavior of the disabled button is also present in 3.2.4.

Is required:
1. Add `disabled_changed(disabled: bool) -> void` event, thanks to which it will be possible to track the switching state in extension classes that are not inheritors from `BaseButton` nodes
2. When `disabled == true`, should not trigger events `pressed`, `toggled`, `button_up`, `button_down`, `mouse_entered`, `mouse_exited`, `focus_entered`, `focus_exited` and `gui_input`

**Comment by Calinou** [comment]
@Exomode Please open a new issue with a minimal reproduction project attached.
