### ISSUE TITLE
Memory leak in [b2Polygon.cpp:1345]

### ISSUE THREAD

**Issue by fangang190** [godotengine/godot#17031]
**Godot version:**

79a225ac2a2f2353f2f626809b56229397dfe52d

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**
The memory allocated on line 1247 to variable nodes. This memory leaks when the function returns on line 1345. 

![screenshot from 2018-02-26 16 46 19](https://user-images.githubusercontent.com/1679432/36660868-9801822a-1b14-11e8-87c5-ce5177557fec.png)

**Minimal reproduction project:**

**Comment by Chaosus** [comment]
Fixed by #17035
