### ISSUE TITLE
Input.is_key_pressed returns false for any other key when KEY_LEFT/KEY_UP pressed

### ISSUE THREAD

**Issue by jhlothamer** [godotengine/godot#17049]
**Godot version:**
3.0/3.0.1

**OS/device including version:**
Windows/Linux

**Issue description:**
Whenever the left and up arrow keys are pressed, no other key press is reported by Input.is_key_pressed.

**Steps to reproduce:**
1. Create a scene with a root node of type Node.
2. Add labels with Text/names set to up, left, space.
3. Attach script to node root.
4. In process function add the following code.
func _process(delta):
	#if these keys are both pressed - the other _is_key_pressed calls return false ALWAYS
	$left.visible = Input.is_key_pressed(KEY_LEFT)
	$up.visible = Input.is_key_pressed(KEY_UP)
	$space.visible = Input.is_key_pressed(KEY_SPACE)

Note: I've tried KEY_RIGHT/KEY_DOWN too (see attached project), but I'm assuming this goes for any other key as well.

**Minimal reproduction project:**
Attached.  Made with Godot 3.0.1 on Windows 10, but was first seen on Ubuntu 17.10 with Godot 3.0.

[UpLeftKeyPressBug.zip](https://github.com/godotengine/godot/files/1759509/UpLeftKeyPressBug.zip)

**Comment by vnen** [comment]
Does it work with other applications?

**Comment by Ranoller** [comment]
Is hardware limitation. Hp and other keyboards have... no problem with my main keyboard (Tested). this is not fixable with godot, so this issue should be closed.

**Comment by jhlothamer** [comment]
Yes.  Seems like a hardware issue/limitation.  Closing issue.
