### ISSUE TITLE
HiDPI regression - Project List too small and off screen window

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#17041]
**Godot version:**
Godot 3.0.1 installed from Steam

**OS/device including version:**
Windows 10 on laptop with GTX970M with dual-screen setup. Laptop screen is 3840x2160 scaled 200%, secondary screen is 1920x1200 scaled 100% (HDMI).

**Issue description:**
When opening the Project List the window is too small, probably two time smaller than normal. Also when launching a scene from editor the window is half out off screen at the bottom right.

**Steps to reproduce:**
Launch Godot 3.0.1 on a computer with HiDPI screen scaled 200%

**Comment by BraindeadBZH** [comment]
Thanks Calinou, here the result trying the different HiDPI compatibility options:

- Application: same issue

- System: working but scaling looks bad (pixelated)

- System (Enhanced): completely broken

I allow myself to insist, this is a regression, I had 0 issue with the exact same setup with no compatibility mode on 3.0.0 and even on 2.X.

**Comment by ruckustboom** [comment]
Has there been any progress on this? I have the same issue, and the HiDPI compatibility options don't help.

- Godot: 3.0.5 (downloaded from godotengine.org)
- OS: Windows 10
- Display: 3840 x 2160 @ 200% (laptop, single screen)

Issues:
- The project list window is tiny
- The cursor is not where it's displayed
- The top menu is cut off

Changes from HiDPI compatibility options:
- Application: No change
- System: Windows are correctly sized, but cursor position and menus are still wrong
- System (Enhanced): totally broken

Pictures:

Project List:
![project-list](https://user-images.githubusercontent.com/1735659/43047523-7d18341a-8d95-11e8-9496-e40c22797bb7.png)

Missing Menus:
![menus](https://user-images.githubusercontent.com/1735659/43047526-88163998-8d95-11e8-836f-71ea9ac2806c.png)

**Comment by Calinou** [comment]
@ruckustboom It's still not fixed, see https://github.com/godotengine/godot/issues/8543.

**Comment by ruckustboom** [comment]
Indeed, thanks, though I can't get around the cursor issue.

Is the menu issue known?

**Comment by reduz** [comment]
The menu issue is a known bug in the Intel driver. Make sure to update it.

**Comment by ruckustboom** [comment]
Ah, good to know, thanks.

**Comment by ruckustboom** [comment]
FYI, the driver update fixed the menu issue and the cursor issue for me.

**Comment by akien-mga** [comment]
I assume it was the same situation with a broken Intel driver for @BraindeadBZH, as I don't see what would have caused such regression between 3.0 and 3.0.1.

Please comment if you can still reproduce the issue with latest Intel drivers.

**Comment by ruckustboom** [comment]
This issue is not resolved. The focus of this issue is the project list window, which is still broken.

**Comment by BraindeadBZH** [comment]
I can confirm that both issue, small project list and game window half off-screen, are still present. I always run latest drivers for both my Intel and Nvidia CGs (Godot is launch on the Nvidia).

**Comment by aaronfranke** [comment]
Can you please test if this occurs with the latest version of Godot ([3.2 beta 6](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-6) or newer)? IIRC there were some changes to HiDPI support in the past year, and the project manager has been improved in 3.2.

**Comment by BraindeadBZH** [comment]
Sorry for coming back to you so late, but yes it seems to be fixed.
