### ISSUE TITLE
SSL certificate files cannot be loaded in exported game

### ISSUE THREAD

**Issue by sunoru** [godotengine/godot#17042]
**Godot version:**
3.0

**OS/device including version:**
Windows 64-bit

**Issue description:**
SSL certificate files cannot be recognized when packaged in .pck. Manually and externally putting it with the exported game (at the same relative path) is a workaround.

**Steps to reproduce:**
  - Export a project with SSL certificate files as the [tutorial](http://docs.godotengine.org/en/3.0/tutorials/networking/ssl_certificates.html).
  - Run the executable file outside the project folder.
  - It will show no information of "certs loaded".

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Godot only exports known *resources* by default, i.e. stuff that is used by
your scenes.

If a file is loaded manually by script, you need to add it to the whitelist
of files to export in your project export settings.

**Comment by sunoru** [comment]
Yes, I know. I have already exported it as a "non-resource file" as the tutorial says.

**Comment by Ranoller** [comment]
This could be the know issue of Directory class that don´t point inside pck and keep res:// in the same folder that godot executable is. Try use File class to access that file.

**Comment by sunoru** [comment]
I have set the certificate file in project settings. What should I do if I want to manually load it in GDScript?

**Comment by sunoru** [comment]
https://github.com/godotengine/godot/blob/ac5cce5e9513eba34745f7e1e90c320ec92390f9/modules/mbedtls/stream_peer_mbed_tls.cpp#L285
It seems the certificates are initialized here..

**Comment by Keetz** [comment]
I cannot reproduce this error.

As long as *.crt files are included in the export settings everything works fine.

Tested on this minimal project:
[HTTPSClientTest.tar.gz](https://github.com/godotengine/godot/files/1874725/HTTPSClientTest.tar.gz)

And also tested on one of my larger projects with another certificate

**Comment by mhilbrunner** [comment]
Assuming this is working after Keetz's comment above. If this still happens with your project on the current Godot 3.0.2 release and *does* seem like a Godot bug, not one in your project, please ping me to reopen this issue. A minimal example project would help in that case, as would confirming that Keetz' project above does not work for you. Thanks!
