### ISSUE TITLE
C# _Draw, incorect position on screen!?

### ISSUE THREAD

**Issue by alexbosquin** [godotengine/godot#17052]
**Godot version:**
3.0 Mono Stable

**OS/device including version:**
Windows 10 64-bit
NVIDIA Gtx 760

**Issue description:**
When you draw a circle at certain position (checked the position, and its right) when game starts
the position is not the same!

**Steps to reproduce:**
create a Navigation2D Node and attach the following

```csharp
public class NavigationSystem : Navigation2D
{

    private KinematicBody2D owner, target;
    private Vector2[] thePath;

    public override void _Ready()
    {
        try
        {
            owner = GetNode("/root/Main/YSort/Player2") as KinematicBody2D;
            target = GetNode("/root/Main/YSort/Player") as KinematicBody2D;
            thePath = GetSimplePath(owner.GetPosition(), target.GetPosition());
            GD.Print(owner.GetPosition(), thePath);
        }
        catch
        {
            throw new Exception("At NavigationSystem -> Something is null");
        }

    }

    public override void _Draw()
    {
        foreach(Vector2 path in thePath)
        {
            DrawCircle(path, 5f, new Color(255, 0, 0));

        }
    }
```

**Comment by Zylann** [comment]
Note that `_Draw` will draw things relative to the node. If the navigation path is in world space (which I assume it is), you should also make sure your `Navigation2D` is centered at the origin of the world. Or, use `SetDrawTransformMatrix` to undo local space and draw in global space.

**Comment by alexbosquin** [comment]
Everything is correctly centered at scene.

**Comment by Zylann** [comment]
Your navigation (and even your whole scene) are not centered at their origin:

![image](https://user-images.githubusercontent.com/1311555/36695766-86df938c-1b42-11e8-9801-7d170161d604.png)

This means your drawings have several degrees of bias.
It looks like pathfinding points are in the same space as the Navigation2D node, so your points become aligned if you do this:

```cs
DrawCircle(path - Position, 3f, new Color(255, 0, 0));
```

In theory, there is another way, by writing this at the beginning of `_Draw`:
```cs
            DrawSetTransformMatrix(Transform.AffineInverse());
```
But I'm surprised that not only doesn't work, but it has the same effect as doing the opposite:
```cs
            DrawSetTransformMatrix(Transform);
```
Me confused.

**Comment by alexbosquin** [comment]
None of the two options worked

**Comment by Zylann** [comment]
@alexbosquin well they worked for me, if not for you... then send again the project with your changes?

**Comment by alexbosquin** [comment]
I've tested on another personal project, maybe I need tolearn better how canvas or even draw works!!

**Comment by mhilbrunner** [comment]
Closing this for now as it seems solved, if it still seems like an Godot bug to you, please feel free to ping me to reopen this issue or create a new one! :)
