### ISSUE TITLE
draw_polyline()'s width strange behaviour

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17050]
**Godot version:**
7568a45

**Issue description:**
The CanvasItem has a function named `draw_polyline`, which can draw lines using a array of Vector2Ds. But I noticed that if the width of the line is 1 (default) or lower, the segments will be separated.

**Width <= 1:**
![separated](https://user-images.githubusercontent.com/30739239/36684842-56a55c52-1b00-11e8-8447-5e670ee4d04f.png)

**Width > 1:**
![together](https://user-images.githubusercontent.com/30739239/36684846-5b093a2a-1b00-11e8-81f6-9896c398f69c.png)

**Comment by nical** [comment]
This is because in `rasterizer_cavas_gles3.cpp`, the PolyLine primitive is rendered using GL_LINES whereas it should be GL_LINE_STRIP.
This code path is indeed only taken if the width <= 1, otherwise a strip of triangles is generate in `visual_server_canvas.cpp`.
