### ISSUE TITLE
(autotiling) The center bit in the 3x3 bitmask does not have a meaning

### ISSUE THREAD

**Issue by michalove** [godotengine/godot#17064]
**Godot version:**
3.0

**Issue description:**
If I understand correctly, the center bit in the 3x3 bitmask needs always(!) to be turned on, because otherwise the tile will not be drawn. That means there is no case in which the user would not set this bit.
Therefore, I suggest to remove it altogether.

**Comment by mateusak** [comment]
If you look at the code you can see it just ignores it. It doesn't matter if it's on or not. It's just a visual issue.

**Comment by clarfonthey** [comment]
It could have a meaning, if you want to allow empty tiles near occupied tiles to have tiles as well.

For example, two tiles which are diagonally connected might want to have two extra tiles to smooth the difference around them.

**Comment by KoBeWi** [comment]
The center bit was removed in Godot 4 TileMaps, but #61809 restored it, because apparently it has an use.
