### ISSUE TITLE
Error created from Template project page

### ISSUE THREAD

**Issue by P1llus** [godotengine/godot#17062]
**Godot version:**
v3.0.1.stable.official

**OS/device including version:**
Windows 10 64-bit.
Intel i7 7700k
GTX 1080

**Issue description:**
When browsing the Templates window the terminal produces errors when trying to load pictures from the test projects it is listing.
Error returned:
```
ERROR: Image::copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core\image.h:327
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules\jpg\image_loader_jpegd.cpp:125
ERROR: _png_error_function: Not a PNG file
   At: drivers\png\image_loader_png.cpp:62
libpng error: Not a PNG file
ERROR: ImageLoaderPNG::_load_image: PNG Corrupted
   At: drivers\png\image_loader_png.cpp:94
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers\png\image_loader_png.cpp:252
ERROR: Image::copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core\image.h:327
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules\jpg\image_loader_jpegd.cpp:125
ERROR: _png_error_function: Not a PNG file
   At: drivers\png\image_loader_png.cpp:62
libpng error: Not a PNG file
ERROR: ImageLoaderPNG::_load_image: PNG Corrupted
   At: drivers\png\image_loader_png.cpp:94
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers\png\image_loader_png.cpp:252
ERROR: Image::copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core\image.h:327
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules\jpg\image_loader_jpegd.cpp:125
```
![image](https://user-images.githubusercontent.com/8027539/36697078-4d5df1cc-1b46-11e8-88f8-f15282b4b18b.png)

**Steps to reproduce:**
Download Godot from Steam.
Open Godot through Steam Launcher.
Click Template Tab.
Browse any page.
This ONLY seem to happen the first time each page is loaded, so after moving back to a page you have seen before it does not produce the error again.

**Minimal reproduction project:**
No project needed.

**Comment by octavz** [comment]
Download Linux version run and Open Asset Library, same thing happens

**Comment by hpvb** [comment]
This seems to be largely cosmetic but it it's not pretty. This happens in 3.0-stable also but less frequently. I suspect some race with the download threads.

**Comment by roguh** [comment]
I reproduced this bug on Ubuntu Artful (17.10)

```
> uname -a
Linux y580 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
