### ISSUE TITLE
Autotiling does not directly support edge-based tilesets.

### ISSUE THREAD

**Issue by michalove** [godotengine/godot#17063]
**Godot version:**
3.0

**Issue description:**
Autotiling does not directly support edge-based tilesets.

By edge-based, I mean a tileset, with the following layout:
![desired_tileset](https://user-images.githubusercontent.com/3463790/36699235-538c426e-1b4c-11e8-843a-c9fdf1971ffd.png)
Tilesets with this layout are quiet common and necessary for "1d-objects", like streets, rivers, fences,...
It would be a great improvement, if they could be used more easily.

**The intuitive way, does not work:**
Here is, what happens, if the user currently tries to use such a tileset:

The 2x2 bitmask, obviously is corner-based, so for ege-based tileset, we would need the 3x3 bitmask. However, if I set the 3x3 bitmask up like this:
![01-bitmask](https://user-images.githubusercontent.com/3463790/36699547-457a61b4-1b4d-11e8-83ad-3f6606037ec0.png)
I will get this layout as a result:
![01-result](https://user-images.githubusercontent.com/3463790/36699558-4fb41382-1b4d-11e8-99ef-b8e948733f13.png)
(the four bottom tiles in the left arrangement are incorrect)

And if I change the bitmask to this (filling in the holes):
![02 - bitmask](https://user-images.githubusercontent.com/3463790/36699589-6af4c6d2-1b4d-11e8-97fc-21899f471709.png)
I get this result:
![02 - result](https://user-images.githubusercontent.com/3463790/36699611-7b115e68-1b4d-11e8-9f26-61a593970823.png)
The left one is a bit better now, but the right one is wrong.
This goes wrong, because the 3x3-bitmask includes the corners, but this tileset only uses edges.

**Possible workaround**
I found a work around to make the 3x3-bitmask work with the tileset, but it is rather complicated. To make it work, we need a tileset of all 47 possible bitmasks. That means, we have to copy the same tiles multiple times:
![workaround_tileset](https://user-images.githubusercontent.com/3463790/36700197-47b84a34-1b4f-11e8-96ad-815fc9538af6.png)
Then, set up this bitmask:
![workaround_bitmask](https://user-images.githubusercontent.com/3463790/36700327-a2fe7c38-1b4f-11e8-917e-3718a970afe6.png)
And it works, we get the desired result:
![workaround_result](https://user-images.githubusercontent.com/3463790/36700335-aa223518-1b4f-11e8-9095-ecf37b69a82c.png)
I think, this workaround is not optimal: The user has to edit the tileset, and insert the same information (the same tile) multiple times.

Please make it easier to use edge-based tilesets.

**Possible solution**
Here are some ideas for solving this issue. Maybe you find one of them useful:
- introduce a "wildcard" bit. By that, I mean the possibility to set a bit to "I don't care", instead of either "on" (red) or "off" (transparent). That way, the user could set all the corner bit to "I don't care" and the tileset would work right away. Wildcard-bits would also be useful, when using autotiling for hex-grids.
- Let the user select a "bit-template" that defines which of the 9 bits should actually be used for matching and which ones should be ignored. That way, the user could select a plus-shaped template that would only include the four edges, but not the corners.
- Add a third type of bitmask "edge" that is plus-shaped (the same as the bullet point before, but less flexible, because the user cannot chose the template shape freely, only from a list of predefined ones).
- Allow multiple bitmasks for each tile. Currently, one bitmask can have many different tiles (many tiles can share the same bitmask), but a tile cannot have multiple bitmasks. If this were possible, the user would not need to copy the image of the tile as I showed above.

(If I explained anything badly, please ask, I can try to explain more)

**Comment by Shadowblitz16** [comment]
this is the problem with the current autotile system. there was a guy that made a suggestion that would fix these issues.

https://github.com/godotengine/godot/issues/18134

**Comment by mateusak** [comment]
> introduce a "wildcard" bit. By that, I mean the possibility to set a bit to "I don't care", instead of either "on" (red) or "off" (transparent). That way, the user could set all the corner bit to "I don't care" and the tileset would work right away. Wildcard-bits would also be useful, when using autotiling for hex-grids.

This is the most versatile way to do this.
