### ISSUE TITLE
Subclassing scenes lose signal connections when base script is edited to invalid state.

### ISSUE THREAD

**Issue by PrestonKnopp** [godotengine/godot#17070]
**Godot version:**

3.0-stable
3.0.1-stable

**OS/device including version:**

macOS sierra

**Issue description:**

Parser error in a script removes signals and connections from the Node Inspector of subclass scenes. The connections are still there on disk but in memory they are erased and saving the scene will persist the erasures. Only open scenes are affected. Signals of subclasses will not show again in the editor until all related scenes and scripts are closed.

**Steps to reproduce:**
1. Create a Base.gd, InheritsBase.gd, and InheritsBase.tscn
2. Make signals in each Base and InheritsBase
3. Connect signals in InheritsBase.tscn
4. Write invalid code in Base.gd, save.
5. InheritsBase.tscn connections to and the signals defined in InheritsBase.gd will be gone

**Minimal reproduction project:**

[minimal-reproduction-project.zip](https://github.com/godotengine/godot/files/1760889/minimal-reproduction-project.zip)

**Comment by Zylann** [comment]
> Write invalid code in Base.gd, save.

Did you try to save the script only? Note that by default, Ctrl+S saves both script and scene.

**Comment by IndicaInkwell** [comment]
Just tested that now and it has some unexpected results. Saving only the script works correctly, at first. After editing the code to be valid again then saving only the script will produce the issue described.

**Comment by neikeq** [comment]
Can we fix this similarly to how it was done with exported properties?

**Comment by reduz** [comment]
@neikeq fixed it in both gdscript and visual script, but you need to fix it in Mono by implementing Script::is_valid property. Same goes to @karroffel
