### ISSUE TITLE
APK Generated by Godot 3 is installable on Android GLES 2 Devices

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#17076]
**Godot version:**
All 3.0 branches (stable/master)

**OS/device including version:**
Android

**Issue description:**
When an apk is generated and installed on a Android device with only OpenGL ES 2 Android it allows installing (the correct behaviour it's that Android must not install it because it is a OpenGLES 3 app)

**Steps to reproduce:**
Build a android example project and install to an Android OpenGL ES 2 only device.

**Some viewing:**

After decrypting AndroidManifest.xml inside APK, it has this line:

`<uses-feature	android:glEsVersion="0x00030000">`

But i think it may have this line (according to this link: https://developer.android.com/guide/topics/graphics/opengl.html):

`<uses-feature	android:glEsVersion="0x00030000" android:required="true">`

**Comment by akien-mga** [comment]
Thanks for looking into this, the proposed fix should indeed be the right one.

BTW the part about texture compression in this docs page is interesting, we should likely define that too to filter out devices which don't support the formats we need.

**Comment by Alexia-AT-Digitecnology** [comment]
Or to filter Adreno, @akien-mga.

**Comment by endragor** [comment]
> The ETC2/EAC texture compression formats are guaranteed to be available when using the OpenGL ES 3.0 API.

We need ETC2, so filtering just for GLES3 is fine, but we may need to add a filter once GLES2 backend is implemented.
