### ISSUE TITLE
Can't import template if folder contains non-ascii characters

### ISSUE THREAD

**Issue by bussiere** [godotengine/godot#1708]
same as here :+1: http://www.godotengine.org/forum/viewtopic.php?f=11&t=1292

Can't open it event if i renamed it as a zip ...

http://i.imgur.com/6cf9R4Y.png

Regards

**Comment by akien-mga** [comment]
The screenshot shows that there is an encoding issue with your "Téléchargements" folder. Do you manage to import the templates if you place the archive in ~ instead of ~/Téléchargements?

**Comment by Calinou** [comment]
I can reproduce this on Fedora 22, with self-built Godot Git (dated 2015-11-21).

Importing the templates works if I put the templates in "Bureau", but not in "Téléchargements" (my system is French).

**Comment by vnen** [comment]
This is because of UTF-8 encoding problem in String. I think it's trying to double convert to UTF-8 (or converting something that already is). And it doesn't work on Windows either.

**Comment by akien-mga** [comment]
I confirm @vnen's analysis, the bug happens at https://github.com/godotengine/godot/blob/c3bf11d/tools/editor/editor_node.cpp#L1282 where `p_file.utf8().get_data()` apparently introduces an encoding bug when parsing something like `Téléchargements`.

We can't just pass `p_file` though as the function expects a `const char*`.
