### ISSUE TITLE
Lack of Android support on some devices (Can't run / install the apk)

### ISSUE THREAD

**Issue by Marshal313** [godotengine/godot#17088]
**Godot version : 3.0**

**OS / Device including version :**

- Editor running on : Lenovo E531, Ubuntu 16.04
- Built APK works on :
  - Samsung Galaxy J5 (SM-J500H), Android 5.1.1
  - Samsung Galaxy J5 (SM-J510FN), Android 6.0.1
- Built APK does install, but crashes when launched, on :
  - Huawei Honor 4C (CHM-U01), Android 6.0, _Application launches but instantly crashed, Before showing Godot splash screen._
- Built APK doesn't even install on :
  - Huawei G750-U10, Android 4.2.2, _Given error on Install : "Parse error : An error occured while parsing the package", I'm pretty sure that the APK is not corrupt._

**Issue description :**
I created a Simple project with only 3 nodes in a single scene (Though I think its the same with any other project, So there must be a problem with Build system), simply to see how android export works in Godot.
The project plays fine in Editor, But when I tried my device (Huawei Honor 4C), The apk installed correctly and the app launched but instantly crashed. So I began manipulating configurations and nothing changed (Except when I didn't sign the apk, Installation failed !). Then I tested some other devices I had access to and surprisingly the sample game ran on some of them, But not on others. This leads to conclusion that Android Support is either Incomplete or there's a problem with apk exporting and building features in Godot, Or maybe my own SDK and NDK is incomplete (But I don't think so, Because I have ran applications built using Android Studio and my current SDK on my Honor 4C before !)

**Steps to reproduce :**
1. Open Godot, Create a simple project (Anything !), and run on Editor. It works fine.
2. Export APK and install on Huawei Honor 4C or Huawei G750-U10, It won't either launch (Crashed on launch) or install !
_(Sorry I didn't have more devices to try, But you can do it and please tell me the results if you did !)_

**My Honor 4C log file on Crash :**   [Log.txt](https://github.com/godotengine/godot/files/1764670/Log.txt)
_Output of command "adb logcat | grep godot" on Honor 4C_

**Minimal reproduction project :** [Test.zip](https://github.com/godotengine/godot/files/1764538/Test.zip)
_The exact same project I tried on these devices_

**Note :** If there's any more information I can give, or Any way I can help with this, Let me know.

**Comment by bruvzg** [comment]
> Huawei G750-U10, Android 4.2.2

Godot targets minimal API level 18 (Android 4.3), and requires OpenGLES 3 support, both CHM-U01 and G750-U10 use Mali-450 GPU (max OpenGLES 2.0 support). APK shouldn't install on GLES 2.0 devices after 7d09e6540afdf69d3610661145d13090a3d9d18a.

**Comment by Marshal313** [comment]
I see, Any suggestions on how to support GLES 2.0 ? Is it logical to do ?

**Comment by bruvzg** [comment]
@Marshal313 GLES 2.0 renderer support is under development, and planned for Godot 3.1.
[GLES2 PROGRESS REPORT #1](https://godotengine.org/article/gles2-and-gdnative-progress-report-1)
[GLES2 PROGRESS REPORT #2](https://godotengine.org/article/gles2-and-gdnative-progress-report-2)

**Comment by Marshal313** [comment]
Thanks !
BtW, How can I mark this Issue closed now ? :grin:

**Comment by netblink-cobreen** [comment]
HUAWEI TIT-U02 application crashes before splash screen
