### ISSUE TITLE
Using resource_queue.gd script not working on Android

### ISSUE THREAD

**Issue by nyenye** [godotengine/godot#17086]
**Godot version:**
Godot 3.0.2

**OS/device including version:**
Android 5.0 Lolipop / Xiaomi Redmi A4 (GPU: Adreno 308)
Android 7.0 Nougat / Xiaomi Mi6
Android 8.0 Oreo / LG Nexus 5X (GPU: Adreno Adreno 418)

**Issue description:**
When loading a scene in background, the textures are shown in black.

**Steps to reproduce:**
Export project to android, open apk. Should see black space (which should be a texture) over colored background. Button on the right, is to switch between two different scenes.  

**Minimal reproduction project:**
[BackgroundResourceLoading.zip](https://github.com/godotengine/godot/files/1889055/BackgroundResourceLoading.zip)

**Comment by Zireael07** [comment]
Lemme guess, Adreno devices again?

**Comment by nyenye** [comment]
@Zireael07 Sh*t.... the GPU is Adreno 308.

But is it really the issue? If I load the scene with the load() method (on the main thread, which would lag the transition between scenes), the texture shows correctly.

Thanks
