### ISSUE TITLE
Clear scripts when selecting multiple nodes

### ISSUE THREAD

**Issue by justinluk** [godotengine/godot#17089]
**Godot version:**
3.0.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
Currently you need to select each node you want to clear scripts from individually. It would be great if you could multiselect nodes and clear scripts from multiple nodes in one go from the right-click context menu.

**Steps to reproduce:**
Add multiple scripts to multiple nodes. Selected them all and then right click, there is no option to remove scripts available.

**Comment by KoBeWi** [comment]
This is fixed (see above PR).

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/17344, closing.
