### ISSUE TITLE
Projects are not showing on project manager

### ISSUE THREAD

**Issue by abdullahzubair109** [godotengine/godot#17085]
**Godot version:**
Version 3.0.1 

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
I am using Godot 3.0.1 stable_win64... when i run it , cmd shows some error.
ERROR: ResourceFormatSaverTextInstance::save: Condition ' err ' is true. returned: ERR_CANT_OPEN
   At: scene\resources\scene_format_text.cpp:1461
ERROR: EditorSettings::save: Can't Save!
   At: editor\editor_settings.cpp:941

Moreover, my projects are not showing on Project Manager. Every time I have to import my projects again and again..

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Do you have non-ascii characters in your Windows username? (`C:\Users\<Username>\`)

**Comment by abdullahzubair109** [comment]
@akien-mga  no.. it is like this .... C:\Users\Home>

**Comment by abdullahzubair109** [comment]
@akien-mga  it is not a Godot bug.. Windows read-only problem. I am closing this issue.
