### ISSUE TITLE
Can't paste absolute path to a file in FileDialog / EditorFileDialog

### ISSUE THREAD

**Issue by nanodeath** [godotengine/godot#17098]
**Godot version:**

3.0.1

**OS/device including version:**

Windows 10.

**Issue description:**

When choosing an external editor (Editor > Editor Settings > External > Exec Path > File...), I'd expect to be able to paste a path (e.g. `"C:\Program Files\Microsoft VS Code\Code.exe"`) into the `Path:` box at the top, or at least the `File:` box at the bottom. But this doesn't work. If you paste into the `Path:` box and hit Enter, it simply reverts back to the original value of the box. If you paste into the `File:` box and hit enter, nothing happens at all.

**Steps to reproduce:**
Included above.

**Minimal reproduction project:**

**Comment by vnen** [comment]
I think it works on Path if you put a path to *directory*,

**Comment by Chaosus** [comment]
This is no longer happens, Exec Path in Text Editor -> External works as expected

**Comment by Chaosus** [comment]
Damn, I just misunderstood the issue. FileDialog still not understand the full path, then its still an issue

**Comment by akien-mga** [comment]
Note that if you want to paste a path directly, you can do so in the LineEdit without using the FileDialog picker:
![Screenshot_20210515_235841](https://user-images.githubusercontent.com/4701338/118379288-87742a80-b5d9-11eb-993b-61d95cdf7458.png)

But yes, in the FileDialog (and EditorFileDialog), handling of absolute paths could be improved to avoid such papercuts.
