### ISSUE TITLE
Can't read text file from res:// in exported game

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#17095]
**Godot version:**
master

**OS/device including version:**
Linux (Solus Budgie)

**Issue description:**
I use this function to open a file saved in my project structure 
file: res://dialog/dialog
https://github.com/HugeGameArtGD/Solus-Stunts/blob/master/source/dialog/dialog
```
func read(dir):
	var file = File.new()
	if file.file_exists(dir):
		file.open(dir, File.READ)
		var input = file.get_as_text()
		var array = input.split("\n")
		print("file read")
		return array
	else:
		return
```
However the text doesn't show up in the exported game.

**Minimal reproduction project:**
https://github.com/HugeGameArtGD/Solus-Stunts/tree/master/source/dialog

**Comment by akien-mga** [comment]
Only resources are exported by default, as specified in https://github.com/HugeGameArtGD/Solus-Stunts/blob/master/source/export_presets.cfg#L7

You need to add that file to the filter of non-resources that should be exported too, or chose to export everything.

**Comment by LinuxUserGD** [comment]
Thank you, I've renamed the text file to dialog.res, now it works on the exported projection and the file also shows up in the Godot File Explorer.
