### ISSUE TITLE
Can we get generic support for GetNode with csharp?

### ISSUE THREAD

**Issue by exts** [godotengine/godot#17091]
**Godot version:**
3.x

I think it would be nice to have support for generics for certain global functions like `GetNode` for instance changing:

```csharp
var button = GetNode("MyButtonNode") as MyButton;
```

to:

```csharp
var button = GetNode<MyButton>("MyButtonNode"); // would infer MyButton or null if not found.
```

I searched and couldn't find anything regarding this yet.

**Comment by akien-mga** [comment]
Duplicate of #16871.

**Comment by exts** [comment]
Damn, github search failed me today. Sorry about that.

**Comment by akien-mga** [comment]
No worry :)
