### ISSUE TITLE
Unresponsive edges on mobile device when scaling.

### ISSUE THREAD

**Issue by tedwennerstrom** [godotengine/godot#17108]
**Godot version:**
3.0.1

**OS/device including version:**
iPhone SE , iOS 11.2.5

**Issue description:**
The edges of the screen is unresponsive when trying to click on buttons on screen. Seems to be like a margin on the edge that stops me from clicking the button.

**Steps to reproduce:**
Create a empty scene. Place a button at the edge of the scene. Set stretch mode to Viewport and aspect to Keep_Width (don't know if matters if it's keep_width or keep_height). Build the game for a mobile (in my case an iPhone) and try to click on the button at the edges. 

Here's a video describing my issue:
https://youtu.be/TCv0cXxwksc

I've searched for an answer but haven't found anything yet. I noticed a weird behaviour with my game and decided to test with a bare bone scene and see if the problem persisted, and it did.
You can read about my issue here, note that the issue described there is from my main game, not the bare bone test scene I did:
https://godotengine.org/qa/24804/buttons-on-mobile-device-acts-weird

**Comment by de11ed** [comment]
So, it seems as the button is getting called, but sometimes when you release it, rather when you press it (it should activate when you press it, not release it), and the visual feedback of the button being pressed isn't showing at all more times then not.

Also, I haven't tried it without any stretch mode. So I'm not sure if this is a stretch mode issue or a issue in general with buttons in Godot.

Anyone knows what's going on or having similar issues?

I will try to do some more digging next week to try and pin point the issue as it's a game breaking bug for me.

**Comment by Calinou** [comment]
@tedwennerstrom Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
