### ISSUE TITLE
KinematicBody2D's move_and_slide delayed on moving platforms

### ISSUE THREAD

**Issue by tsiegleauq** [godotengine/godot#17107]
**Godot version:**
3.0 Stable

**OS/device including version:**
All

**Issue description:**
(Both) KinematicBody2D (and RigidBody2D) (still) cannot handle moving platforms well.
On a moving platform (moved over AnimationPlayer or script) you still feel like you are playing an egg in an oiled pan.
The character slides left and right too much, depending on the direction where the platform moves.
The problem gets worse with faster platforms.
Increasing the friction does not help to reduce this effect.

**Expected result:**
I expected a physics body to move exactly the same way as the platform does.
This makes 2D Physics in Godot unusable for platforming games that require high precision.

**Steps to reproduce:**
- install Godot3
- get the template "2D Platformer Demo (Kinematicbody)"
  - optional: edit moving_platform.gd to speed up the movement of the platform to get a more extrem result
- run the projekt
- jump on a moving platofrm
- see the character sliding

**Minimal reproduction project:**

2D Platformer Demo (Kinematicbody)

**Comment by podpathos** [comment]
There is also problem if "moving platform" moves up and down - KinematicBody2D is jumping, lagging one frame.
There is so much more problems that you will face if you except to make oldschool platformer with KinematicBody2D (especially proper arcade slope physics).
Spare yourself the trouble of making arcade physics with KinematicBody2D, it is not funcional for that purpouse. Make your own cutom tilebased arcade physics.

**Comment by tsiegleauq** [comment]
Yes I guess you are right. I wanted to use the build in physics "just" to see the limitations.
(and to have cleaner code)
It's still good for some "Castle Vania" - like games, but I would probably not use it for something like "Super Meat Boy" or even "Mario".

Guess I need to learn about Tile-based arcade physics now. Thanks for that information.

**Comment by OliPerraul** [comment]
Have any of you gone around to make that tilebased arcade physics system? I am struggling to make my own. Cheers

**Comment by reduz** [comment]
This is fixed, see [this article](https://godotengine.org/article/godot-31-will-get-many-improvements-kinematicbody).
Closing
