### ISSUE TITLE
GodotSharp - Mesh class has no constructor

### ISSUE THREAD

**Issue by BLaDoM** [godotengine/godot#17121]
Godot 3.0.1

GodotSharp has no equivalent to GDScript's Mesh.new()

**Comment by neikeq** [comment]
Mesh is an abstract class, you cannot instance it. I would be surprised if Mesh.new() works in GDScript.

**Comment by BLaDoM** [comment]
Weird, I've seen a couple of tutorials using Mesh.new() to generate a mesh and modify it.

**Comment by reduz** [comment]
In Godot 3.0, the previous Mesh class is now known as ArrayMesh

**Comment by groud** [comment]
So ? Closing ?
