### ISSUE TITLE
Monitorable Property not working on Bullet

### ISSUE THREAD

**Issue by Superwaitsum** [godotengine/godot#17127]
**Godot version:**

Godot 3.0 and 3.0.1

**OS/device including version:**

Windows 8.1 x64

**Issue description:**

Monitorable property in 3D is not working while using Bullet Physics.
May be related to bug #16541 (but this bug affects only bullet)

**Steps to reproduce:**
Use two 3D areas, one with monitoring enabled (default) and the other with monitorable disabled. In Godot Physics they don't collide (correct behavior), but in Bullet Physics they register collision.

Also would like to add that using monitoring and monitorable in godot physics while having lots of areas reduces the physics frame time, not sure if this optimization is possible in bullet.

**Minimal reproduction project:**

Made a reproduction :smiley: , only have to toggle the physics engine between Godot and Bullet and view the output 
[Test_monitor_bullet.zip](https://github.com/godotengine/godot/files/1769472/Test_monitor_bullet.zip)

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by AndreaCatania** [comment]
Fixed by #17900 can you please confirm it?
