### ISSUE TITLE
Materials changed when saving new material

### ISSUE THREAD

**Issue by amedlock** [godotengine/godot#17125]
**Godot version:**
3.0.1 Release

**OS/device including version:**
Windows 10 64 bit Professional

**Issue description:**
When editing my scene, I wanted to use an existing material **blue_mat.tres** to create a new material so I double clicked the **tres** file to edit in the **_Inspector_**.  I then clicked **_"Save As.."_** and chose **green_mat.tres** to save a copy. 

All my meshes which had **blue_mat.tres** assigned are now assigned to **green_mat.tres**.  I understand you can also right-click duplicate in the File Window but saving a resource under a new name shouldn't change assignments, imo.

**Steps to reproduce:**
Create a Mesh, create a material for it and save to TRES file.  Then edit the material and save it as a new filename.  Your mesh will be assigned to the newly named material.

**Comment by Calinou** [comment]
@amedlock Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by amedlock** [comment]
I am on vacation til Monday but I will test then. Thanks.

**Comment by amedlock** [comment]
This still happens in Godot 3.2.1.  When you save-as and edit a material it re-assigns it to existing Meshes.

**Comment by Calinou** [comment]
I think this is done by design. If you want the saved material to not affect other existing meshes, you must choose **Make Unique** *before* saving the material. I'm not sure if doing this automatically when using **Save As...** is a good idea.

**Comment by amedlock** [comment]
Makes sense. Feel free to close this (or I can if you want).

**Comment by clayjohn** [comment]
I agree with @Calinou. While I can see the appeal of making resources unique automatically when using "save as", I think it makes more sense not to. Especially since making resources unique has a performance penalty. 

Thanks for the idea though!
