### ISSUE TITLE
Improve the SpinBox node

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17126]
Godot, all versions up to 3.0.1

It's been a long time I think grid configuration input boxes need to be improved:

![image](https://user-images.githubusercontent.com/1311555/36822008-2589d7cc-1cf6-11e8-98bf-997dd9828e0e.png)

Please:
- When clicked, select the whole value's text
- Don't embed the units within the box, move them in a label, it adds noise and never need to be changed (as far as I used them... if it ever needs to change, use a dropdown). They also are inconsistent (sometimes p, sometimes px).
- Resize the boxes correctly, sometimes they aren't large enough to display their contents
- Sometimes you can even place the caret outside the visible edition area when clicking on it

![image](https://user-images.githubusercontent.com/1311555/36822111-a98ed7de-1cf6-11e8-849f-cde2a580b6fb.png)

**Comment by puppetmaster-** [comment]
would be cool to have it also directly in the 2D scene window

**Comment by groud** [comment]
It's the SpinBox node that should be improved, I rename the issue. :)

**Comment by Zylann** [comment]
Is the spinbox node alone really responsible for all problems I listed?

**Comment by groud** [comment]
> Is the spinbox node alone really responsible for all problems I listed?

Yes, I started a little bit to rework its code. IIRC, all the problem you mention are handled directly by the SpinBox's code.

**Comment by bfloch** [comment]
Related to https://github.com/godotengine/godot/issues/15965

**Comment by silkentrance** [comment]
I'd like to chime in and would propose that

- upon clicking into the line edit, the value is rendered without the prefix and postfix, that way we can keep both the postfix and prefix in the line edit instead of making them separate labels
- copying the value will only copy the actual value without the prefix a/o postfix

**Comment by TheSofox** [comment]
I'm proposing this bug be closed. It seemed that the majority of the issues have been addressed.

**Comment by Calinou** [comment]
Closing per @TheSofox's comment. Feature requests should be made on https://github.com/godotengine/godot-proposals :slightly_smiling_face:
