### ISSUE TITLE
Particles 3d saved as disabled if saved after emit timeout delay

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1713]
Hi,

Create a scene containing a 3d Particles node.
Set Emitting to On.
Set Emit Timeout to 5 seconds.

If you save before 5 seconds, the Emitting parameter will be saved to On.
If you save after 5 seconds, the Emitting parameter will be saved to Off.

**Comment by reduz** [comment]
Particles3D are on the way of being rewritten, will be able to fix this by then

**Comment by akien-mga** [comment]
Is this bug still valid in the current master branch/2.0.x series?

**Comment by SuperUserNameMan** [comment]
Yes, this behavior description is still valid in official win64 2.0.2_stable release.

**Comment by kubecz3k** [comment]
@SuperUserNameMan can you recheck on 3.0? Thank you!

**Comment by SuperUserNameMan** [comment]
@kubecz3k : no i can't, sorry.

**Comment by akien-mga** [comment]
Assumed fixed in 3.0, feel free to reopen/comment/open a new issue if it's not the case.
