### ISSUE TITLE
Multiple Areas collision giving errors while using bullet

### ISSUE THREAD

**Issue by Superwaitsum** [godotengine/godot#17132]
**Godot version:**

Godot 3.0 and 3.0.1

**OS/device including version:**

Windows 8.1 x64

**Issue description:**

Using several areas together gives unexpected bug only in bullet

**Steps to reproduce:**
Make destructive (queue_free) collision of several areas (in the reproduction project, 8 (4 colliding with 4) and above areas cause the bug. Godot physics doesn't give errors.
Here is the log:

```
0:00:01:0469 - Condition ' !area_in && !E ' is true.
----------
Tipo:Error
Descripción: 
Tiempo: 0:00:01:0469
C Error: Condition ' !area_in && !E ' is true.
C Fuente: scene\3d\area.cpp:357
C Función: Area::_area_inout
```
**Minimal reproduction project:**

The test project will throw several areas against them, but only half of the areas should survive, bullet gives great accuracy in this case, since godot physics sometimes doesn't detect the collisions, but gives the errors.

[Test_Bullet_queue.zip](https://github.com/godotengine/godot/files/1769905/Test_Bullet_queue.zip)

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by AndreaCatania** [comment]
Fixed #17899 can you please confirm it?

**Comment by Superwaitsum** [comment]
Hello, sorry for the delay, since is my first time compiling godot, i'm not sure if this is my fault, but applying this PR makes that instead of the error, the running game window closes. The editor gives this error: " drivers\windows\stream_peer_tcp_winsock.cpp:203 - Server disconnected!". Applied the PR using "cherry pick" command from git GUI to a local repo master.

**Comment by AndreaCatania** [comment]
I don't think the problem is this PR because I didn't touched stream_peer_tcp_winsock.cpp file, Try to clone and build my branch directly

**Comment by Superwaitsum** [comment]
Sadly it's still giving me the error (stream_peer_tcp_winsock), but will wait for the next unofficial hugo pro build to confirm since it may be my VS2017 (though reverting the commit makes it not happen but conserving the bug)

**Comment by vnen** [comment]
@Superwaitsum the error you get is unrelated to this issue (and unrelated to the fix as well). What you have is the same as #17882.

**Comment by Superwaitsum** [comment]
@vnen, thanks for mentioning that bug before me giving a confirmation of it happening also in calinou's builds. Don't know why it happens since adding this fix, but seems to be the same error. Maybe should #17899 reverted until #17882 is fixed? (since previous errors didn't close the game's window). Also the bug demo project could be used to know what causes #17882.

**Comment by Superwaitsum** [comment]
Just found the cause of the bug, there was an array clearing missing. @AndreaCatania, is my fix ok?
https://github.com/Superwaitsum/godot/commit/6d06c08603419eee5312d0616c09f135b2cd6a3e

**Comment by Superwaitsum** [comment]
For some reason without that clear array, this happens:
https://streamable.com/g5ttj
Trying to fix it, found your comment about clearing the array and that worked

**Comment by AndreaCatania** [comment]
Let me check it, I'll let you know

**Comment by Superwaitsum** [comment]
Thanks!! . It is working correctly now.
