### ISSUE TITLE
RichTextLabel has a larger gap between the first and second line compared to the rest.

### ISSUE THREAD

**Issue by sprite-1** [godotengine/godot#17139]
**Godot version:** 3.0.1

**OS/device including version:** Windows 10

**Issue description:**
There is a bigger gap between the first line of text and the 2nd compared to the subsequent ones.
![image](https://user-images.githubusercontent.com/33685433/36847482-76026748-1d99-11e8-9621-62f2b73bc630.png)
![image](https://user-images.githubusercontent.com/33685433/36847494-7ea742ce-1d99-11e8-958d-7937999b7ebf.png)
It doesn't happen in 2.1.4.

**Steps to reproduce:**
Make a **RichTextLabel**. Fill it up with text to the point where the text wraps and has around 3-4 lines. Notice how uneven the gap is?

**Comment by paul-dosenbrot** [comment]
I can confirm this behavior for the daily build v3.1.dev.custom_build.eec9261 (2018/03/01) from https://hugo.pro/projects/godot-builds/.

**Comment by hpvb** [comment]
Did this happen in 3.0 also?

**Comment by hpvb** [comment]
Caused by fa98637acaab9135568bf0d43a65c9c96b59c32d

**Comment by hpvb** [comment]
Fix by 89f607604e82bdce974a45029666c10586c6fe2a

**Comment by sprite-1** [comment]
Nice, does this mean it'll come with 3.0.2? Or will it be in 3.1?

**Comment by hpvb** [comment]
@sprite-1 3.0.2 :)
