### ISSUE TITLE
Making a node's children not selectable no longer works.

### ISSUE THREAD

**Issue by bncastle** [godotengine/godot#17148]
**Godot version:**
234dfde22f42cd18c3f6e390f1e7a30916ef8c9e

**OS/device including version:**
Windows 

**Issue description:**
Making a node's children not selectable no longer works as it did in **Godot v 3.0.1**

Below is the issue in visual form using the Godot version indicated above:

![godotselectchildren](https://user-images.githubusercontent.com/1876691/36860945-a5dab37e-1d50-11e8-8a1a-acbda606a986.gif)

Below is how the same actions behaved in **Godot v 3.0.1**:

![godot-3 0 1](https://user-images.githubusercontent.com/1876691/36861182-320d8772-1d51-11e8-864b-ca0780c852c0.gif)

**Steps to reproduce:**
1) Create a new scene.
2) Create a Sprite
3) Attach a StaticBody2D to theSprite node
4) Attach a CollisionShape2D to the StaticBody2D node
5) Create a collision shape in the CollisionShape2D node
6) Set the Sprite parent by clicking the "Object group button" ![image](https://user-images.githubusercontent.com/1876691/36860373-10efff86-1d4f-11e8-9c32-f48fcc7d2e68.png)
7) Try to select the sprite by clicking on it, and instead the CollisionShape2D will be selected.

**Minimal reproduction project:**
[NodeChildren.zip](https://github.com/godotengine/godot/files/1772207/NodeChildren.zip)

**Comment by akien-mga** [comment]
CC @groud

**Comment by bncastle** [comment]
@reduz @groud I just built with #17502 and I'm still seeing the same behavior as before.

![child not selectable](https://user-images.githubusercontent.com/1876691/38739588-526ad5be-3f03-11e8-91eb-309d24324f01.gif)

**Comment by groud** [comment]
Note to myself: it works for box selection, not for single click one.

**Comment by volzhs** [comment]
@groud in my short test, it works as expected with 47d4a011d

**Comment by groud** [comment]
Ok, I'll close this since #18400 must have fixed this problem :)

**Comment by bncastle** [comment]
@groud I just built 0738ba6bc1ed93ad24f4c0c7e493512ee0670cd6 and it seems to be working correctly. :smiley:
