### ISSUE TITLE
GLES2 doesn't render Line2D with tiled textures correctly

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17147]
**Godot version:**
 234dfde

**Issue description:**
**GLES3:**
![gles3](https://user-images.githubusercontent.com/30739239/36860579-6bac3442-1d60-11e8-888d-d9fffa13b62f.png)

**GLES2:**
![gles2](https://user-images.githubusercontent.com/30739239/36860584-6f65d674-1d60-11e8-8667-b5bdcd82a51e.png)

These errors also appear:
```
0:00:00:0829 - Method/Function Failed, returning: image
----------
Type:Error
Description: 
Time: 0:00:00:0829
C Error: Method/Function Failed, returning: image
C Source: drivers/gles2/rasterizer_storage_gles2.cpp:143
C Function: _get_gl_image_and_format
```
```
0:00:00:0829 - GL ERROR: Source: OpenGL	Type: Error	ID: 14	Severity: High	Message: GL_INVALID_ENUM in glTexImage2D(incompatible format = GL_NONE, type = 0x2a474370)
----------
Type:Error
Description: 
Time: 0:00:00:0829
C Error: GL ERROR: Source: OpenGL	Type: Error	ID: 14	Severity: High	Message: GL_INVALID_ENUM in glTexImage2D(incompatible format = GL_NONE, type = 0x2a474370)
C Source: drivers/gles2/rasterizer_gles2.cpp:111
C Function: _gl_debug_print
```

**Comment by akien-mga** [comment]
CC @karroffel

**Comment by karroffel** [comment]
Will take a look, but a small example would be very appreciated

**Comment by karroffel** [comment]
also note that the errors are related to the 3D environment trying to load a float texture for the skymap. Float textures aren't supported in GLES2, will have to find a way around that

**Comment by YeldhamDev** [comment]
@karroffel 
[Example.zip](https://github.com/godotengine/godot/files/1772434/Example.zip)
