### ISSUE TITLE
A large enough scene size seems to break PSSM shadows.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#1714]
In my game, I enlarged the total size of the scene (in terms of the max and min coordinates of the furthest vertices), and I noticed that the shadows no longer work despite the same settings working fine in levels with smaller dimensions.

I can get them to come back on by switching to the 'perspective' option, but that method doesn't work very well for many cases. I do wonder if this could be fixable by letting the position of the directional light be the center of a region where the PSSM shadow-maps are calculated (and as such shadowing will not exist beyond it). That way I can use a parenting setup to move the directional light, and as such the shadow field with the player and eliminate the distance limit (and perhaps reduce the resolution needed for decent shadows as well).

Thoughts, I think my suggestion may be possible to do with the current OpenGL-ES2 graphics.

**Comment by reduz** [comment]
did you try setting a maximum distance for shadow?

**Comment by Ace-Dragon** [comment]
I've always had the *max distance* field filled out (it's been at 400). Changing it doesn't seem to have any effect,

**Comment by Ace-Dragon** [comment]
So it just occurred to me while looking at my scene that it looks like some (very low detailed) shadows are there, but because we have no control over the size and the position of the shadow frustum, the shadow buffer size would have to be absolutely huge.

To have a good emulation of an unlimited size, we need to have it so the center of the shadow region is on the directional lamp and as such moving the lamp with the player will keep everything that is seen  illuminated with detailed shadows. I don't think having Godot automatically calculate the frustum is the best idea here.

**Comment by Ace-Dragon** [comment]
Here's an image of the issue, you will see on the right that the lamp clearly has shadow casting enabled, but there's clearly no shadows that are visible (hence my suspicion that a large enough scene size can break them).
![godot_brokenshadows](https://cloud.githubusercontent.com/assets/10081256/7400593/b1ed3bea-ee83-11e4-85bd-f1bf799a725b.jpg)

**Comment by reduz** [comment]
i see, i will check this tonight, it's one of the few important bugs I have
left to fix before beta.

btw, did you check the ones about shader graph that you reported? I believe
i fixed them but haven' t heard back from you

**Comment by Ace-Dragon** [comment]
I just checked on the file that displayed the bug before and found that it's all working good now.

I have closed the issues as a result.

**Comment by Ace-Dragon** [comment]
The comment above was referencing the shader graph bug by the way, the bug with the PSSM shadow map still stands.

**Comment by reduz** [comment]
okay, i will check it in the weekend

**Comment by Ace-Dragon** [comment]
Okay, tried deleting the terrain and found that it didn't bring back the shadows.

But what *did* work in bringing them back was re-importing the entire scene using the *overwrite existing scene* option. I'm not sure what happened exactly, but it's possible it might've been an error in updating the scene asset stemming from it being initially imported before various fixes were applied.

So apparently it may or may not be mostly a one-off thing going forward, but I can't say for sure when future changes get applied to the Collada importer.

**Comment by reduz** [comment]
I just fixed a bug that might be the culprit. Check that the property "extra_cull_margin" is zero in the affected scene objects, as it had an uninitialized value, if it's not zero make it zero and it should all work again

**Comment by reduz** [comment]
and of course update github since this was fixed minutes ago

**Comment by okamstudio** [comment]
this should hopefully make the issue not happen anymore

On Fri, May 1, 2015 at 11:29 AM, Juan Linietsky <notifications@github.com>
wrote:

> and of course update github since this was fixed minutes ago
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1714#issuecomment-98144825>.
>



-- 

*OkamStudio*
