### ISSUE TITLE
[feature request] add a separator between "Open scene" and "Save scene"

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1715]
Hi,

It happened at least twice that I clicked on "Save scene" instead of "Open Scene" and that I unwillingly overwritten a poor and innocent scene.

My screen is 15" with a resolution of 1366 x 768. Even if it's not a high density screen or minuscule screen, menu items are small enough to miss my target when I click a little too fast.

**Comment by eska014** [comment]
There is a separator between the two by now.
