### ISSUE TITLE
64bit Crashing after windows 10 update 

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#17157]
**Godot version:**
Godot_v3.0.1-stable_win64.exe (Broken)
Godot_v3.0.2-rc1_win64.exe (Broken)
Steam version (Broken)

**OS/device including version:**
Windows 10 Home 64bit
Version 1709
OS-Version 16299.125

**Issue description:**
Crash when trying to launch godot. the black command window pop up for a split second and then it crash, nothing is displayed in this command window.
I was forced to update windows a few days ago and after that the latest builds from https://downloads.tuxfamily.org/ crash all the time, this builds work on my other windows 10 computer without the update from windows.

BUT!
The 32 bit verison work fine from tuxfamily
Only the 64 bit version crash

The daily 64bit windows build works from http://godot3builds.digitecnology.com/
version v3.0.2.devel.custom_build.3e931e2
The same happend when 3.0.1 stable came out, it crash and the daily build from godot3builds work

**Steps to reproduce:**
Double tap the exe file

[nofiletoupload.txt](https://github.com/godotengine/godot/files/1772815/nofiletoupload.txt)

**Comment by hpvb** [comment]
Could you please try with this exe: https://tmm.cx/nextcloud/s/e1yRqhW6rzM1hgK I don't think it should fix your issue but it should output complete debugging information when it crashes.

Please run this from cmd.exe a couple of times and put the output you see on the terminal on this ticket. 

Thanks!

**Comment by Norrox** [comment]
I will do that!
i forgot to mention that the steam version does crash aswell, maby this is that exe?
i tried open steams version directly from the folder and tried move it and open it from some other place with no luck.

**Comment by Norrox** [comment]
Crashing everytime, no output in the termial. just the little window that says "Godot Engine Editor has stopped working"
![22d8cec872bb7e0f79245d7ef94a8183](https://user-images.githubusercontent.com/13393087/36871755-85595a9e-1da3-11e8-853d-5ab7d6800e0e.png)

**Comment by hpvb** [comment]
That is certainly very... interesting. I have to think a bit on what to do now. 

Can you attach a screenshot of the crash dialog? Does it have a 'details' button or anything like that?

**Comment by akien-mga** [comment]
It's interesting that our builds fail, while the nightly builds of Digitecnology work.

Ours are built with MSVC 2017 with `scons platform=windows target=release_debug tools=yes progress=no warnings=no verbose=no`.

@Alexia-AT-Digitecnology What system/toolchain and configuration do you use for your Windows builds?

**Comment by hpvb** [comment]
The binary I just sent was build with mingw64 

`/usr/bin/scons platform=windows bits=64  -j16 debug_release=yes builtin_openssl=yes warnings=all verbose=yes progress=no debug_symbols=full target=release_debug tools=yes`

**Comment by Norrox** [comment]
Yes very strange, and sadly there are no detail on the error window, the language in the window are swedish
![9dbab4b370be8ceb46719aaf7f364096](https://user-images.githubusercontent.com/13393087/36874038-be563996-1daa-11e8-816a-b9bf3cc22642.png)

**Comment by hpvb** [comment]
Does 3.0-stable have the same problem for you?

**Comment by hpvb** [comment]
@Norrox Do you know how to use a debugger on Windows? If not would you be interested in helping to debug this by joining me on IRC or Discord or some other IM system so that I can guide you through getting the information we would need?

**Comment by Norrox** [comment]
3.0-stable are crashing, and even tried the 3.0 alpha 1 crashing ( those have worked before the update)
No i do not know how to use a debugger on windows, im on Discord in the Godot Engine grp ( Nick: Christoffer#9026 )

**Comment by Alexia-AT-Digitecnology** [comment]
@akien-mga, I'm using last mingw-w64 package with ArchLinux system for maing Windows builds.

**Comment by hpvb** [comment]
@Alexia-AT-Digitecnology could you tell us the exact scons options you use to build the Windows binaries please?

**Comment by Alexia-AT-Digitecnology** [comment]
GODOT_STATIC_LIBS="builtin_enet=yes builtin_freetype=yes builtin_libogg=yes builtin_libpng=yes builtin_libtheora=yes builtin_libvorbis=yes builtin_libvpx=yes builtin_libwebp=yes builtin_openssl=yes builtin_opus=yes builtin_squish=yes builtin_zlib=yes"

# Releases
scons -j3 platform=windows target=release_debug tools=yes bits=32 $GODOT_STATIC_LIBS
scons -j3 platform=windows target=release_debug tools=yes bits=64 $GODOT_STATIC_LIBS

# Export templates
scons -j3 platform=windows target=release tools=no bits=32 $GODOT_STATIC_LIBS
scons -j3 platform=windows target=release_debug tools=no bits=32 $GODOT_STATIC_LIBS
scons -j3 platform=windows target=release tools=no bits=64 $GODOT_STATIC_LIBS
scons -j3 platform=windows target=release_debug tools=no bits=64 $GODOT_STATIC_LIBS

**Comment by bfloch** [comment]
> I was forced to update windows a few days ago and after that the latest builds from ...

16299.125 is from December. There are various reports of failed updates on the net. Maybe it is related to you system? Also worth mentioning that many of the January patches try to harden against spectre and there was the "questionable" intel micro code update, to quote wikipedia:

> On January 29, 2018, Microsoft was reported to have released a Windows update that disables the problematic microcode fix (causing possible reboots, stability and data loss/corruption problems) issued earlier by Intel for the Spectre Variant 2 attack

I would recommend trying to update windows again.

**Comment by eon-s** [comment]
And try to update video drivers (not mentioned in the OP), nvidia and intel seem to have issues with the fall creators update (1709).

**Comment by Norrox** [comment]
Did windows update again and updated to latest video drivers. No luck.

**Comment by Norrox** [comment]
Steamversion works, i do not know what happen.. i havent done anything since last time it didnt work :O

**Comment by eon-s** [comment]
That is interesting @Norrox, can you try itch.io version? (maybe the sandboxing on these store apps is doing something).

**Comment by Norrox** [comment]
The steamversion does not work anymore hahaha, now when i try to launch it it just crashes

**Comment by Norrox** [comment]
@Alexia-AT-Digitecnology have you changed anything on how you do your builds? becous now yours are crashing for me aswll :S

**Comment by eon-s** [comment]
@Norrox being able to run the steam version once was strange, try running the downloaded one in self contained mode (create a file called _sc_.txt next to the executable, an editor_data folder will appear after running it the first time).

**Comment by olejr** [comment]
Had the same problem here with x64 version for a while.
It doesn't always crash. And when it does it's not always at the same place.
Sometimes I get as described here, only the dos-box window.
Or I get to the project window, and when I select/doubleclick a project it dies.
And sometimes it runs just fine..

And when it crashes it generates a crashdump in Users\"username"\AppData\Local\CrashDumps
Infact had to delete a bunch of then when I was running low on disk..

Here's one of the latest if someone knows how to use it (or if it's of any use at all): 
[Godot_v3.0.2-stable_win64.exe.10544.zip](https://github.com/godotengine/godot/files/1805010/Godot_v3.0.2-stable_win64.exe.10544.zip)

**Comment by hashusfb** [comment]
Windows 10 1803'de bende aynı sorunu halen yaşıyorum.

**Comment by Norrox** [comment]
@hashusfb yeah i've switched to linux, that was the solution for me :)

**Comment by hpvb** [comment]
I expect it to work with 3.0.3 now. Can you please verify?

**Comment by huttyblue** [comment]
I had a user on Swedish Windows 8.1 who was coming across mysterious crashes in [CartCrawlers](https://aloe-vertex.itch.io/cartcrawlers).  After eliminating the other possibilities we started to think it was an issue with the language of his OS. We had him test [FrogSmith](https://cowthing.itch.io/frog-smith) and he crashed there too which led me to think its a godot issue and not a CartCrawlers issue. Which eventually led me to this thread.

I did update the game to 3.0.3 and pass him a new 32bit build but that didn't solve the issue. 
[here](https://paste.ubuntu.com/p/GTQkQTYnGb/) is a dump of our discord conversation.

**Comment by Norrox** [comment]
@hpvb I tried it before I did a clean install of the latest version of win 10, it did not work. I believe something in the creators update broke the OS. After the reinstall everything work fine.

**Comment by Norrox** [comment]
@huttyblue I don't know if this helps, but he can try to reinstall the runtimes? Maby there something there that causes this?
http://m.majorgeeks.com/files/details/visual_c_runtime_installer.html

**Comment by NoodleSushi** [comment]
I have this problem too. After a few minutes using Godot it just crashes all of the sudden, if any background audio was playing it loops and glitches. It is the 5th time restarting my laptop and Godot crashing. Godot usually crashes when I navigate in 3D.

**Comment by reduz** [comment]
I suppose this can no longer be reproduced?

**Comment by akien-mga** [comment]
This seems similar to #17856, and it's a Windows 10 updates bug that we can't fix ourselves. Most users report that later system updates or reinstall finally fixed it, so that's the only workaround we can suggest.
