### ISSUE TITLE
Pressing escape to close completion proposals closes the shader editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17159]
Godot 3.0.1

When the shader editor opens completion proposals, pressing Escape usually hides it. Now it also closes the shader editor, which is not expected in that case.

![image](https://user-images.githubusercontent.com/1311555/36871809-a36bc314-1da3-11e8-997a-f86b3456351e.png)

Related to https://github.com/godotengine/godot/pull/15862

**Comment by akien-mga** [comment]
Might be fixed in the master branch with #16947.

For 3.0.2, we may want to revert #15862 @hpvb.

**Comment by hpvb** [comment]
yeah, revert may be best.

**Comment by Zylann** [comment]
The same happens when there is a popup window, pressing Escape closes both the window and the shader editor, while I expected only the popup to close.

**Comment by akien-mga** [comment]
Note: This wasn't fixed by #16947 (see #20738, same issue), but now fixed by the revert of #15862 in 32ee3bf.
