### ISSUE TITLE
Navigation.navmesh_add crashes the game

### ISSUE THREAD

**Issue by minitrope** [godotengine/godot#17153]
**Godot version:** 3.0 (stable)
**OS/device including version:** Ubuntu 16.04.4 LTS (Xenial Xerus)

**Issue description:**

When using the `Navigation.navmesh_add` method, it crashes at runtime.

**Steps to reproduce:**

- Create a scene like the following:
```
- Spatial
  - Navigation
  - NavigationMeshInstance
```
- Write a script to add the NavigationMeshInstance to the Navigation node with the method `navmesh_add`.
- Run the scene and see it crashing

**Minimal reproduction project:**

[Add-Navmesh.zip](https://github.com/godotengine/godot/files/1772654/Add-Navmesh.zip)

In the project above, the relevant code can be found in `Spatial.gd`.

**Comment by atllllll** [comment]
In your minimal reproduction project, it seems like you're trying to run Navigation.navmesh_add with a NavigationMeshInstance and not the NavigationMesh itself. When you replace your definition of ``navmesh`` with ``var navmesh = get_node("Navmesh").get_navigation_mesh()`` it doesn't crash.

**Comment by hpvb** [comment]
While the code in the project is invalid GDScript shouldn't be able to crash the engine in debug mode. I've created a PR that should create an event in the debugger instead.
