### ISSUE TITLE
DEPTH_TEXTURE is not available in CanvasItem shader

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17160]
Godot 3.0.1

I am trying to implement a fullscreen effect with a screen-reading shader, for a 3D game. I need to access the depth with `DEPTH_TEXTURE`, which is listed along `SCREEN_TEXTURE` for spatial shaders.
However, since my effect is a fullscreen node, it usess a `canvas_item` shader type. In those shaders, `SCREEN_TEXTURE` is available, but not `DEPTH_TEXTURE`...

**Comment by Bauxitedev** [comment]
As a workaround you can put a 3D quad in front of the camera and parented to the camera, and then put a spatial ShaderMaterial on it with depth testing disabled, so it draws on top of everything. With the spatial shader type you can access the depth texture.

**Comment by akien-mga** [comment]
It's now properly documented as being 3D-specific: https://docs.godotengine.org/en/stable/tutorials/shading/screen-reading_shaders.html?highlight=DEPTH_TEXTURE

@clayjohn @Chaosus Should this be closed, or do you think `DEPTH_TEXTURE` can be exposed to CanvasItem shaders somehow?

**Comment by clayjohn** [comment]
Superceded by https://github.com/godotengine/godot-proposals/issues/783 and https://github.com/godotengine/godot-proposals/issues/798
