### ISSUE TITLE
Confirm property value change on focus loss (as opposed to hitting return/enter)

### ISSUE THREAD

**Issue by Bonkuraazu** [godotengine/godot#1717]
It would be great if you could confirm a value change by just click away from the property value text-box instead of hitting enter. I remember reading a forum post suggesting this feature a while back. I downloaded Godot v1.1.beta1 to see if the feature was added, but it seemed to be the same as 1.0.release. Or maybe it's implemented hidden in settings somewhere. I know it's not a high-priority feature, but since i couldn't find this request on github, i decided to make one.

**Comment by reduz** [comment]
this is  1.2 material, which will focus on usability enhacements..  do you think you could add it to the google group doc with the usability enhacements planend for 1.2?

**Comment by akien-mga** [comment]
That's indeed a must have for 2.0 in my opinion, I've got used to the "press entern to confirm" behaviour in the end, but at first I found it really frustrating, and I've seen in video tutorials that others do too.
