### ISSUE TITLE
Error [Condition ' p_width < 0 && p_height < 0 ' is true.] when display/window/shrink == 0

### ISSUE THREAD

**Issue by Marshal313** [godotengine/godot#17181]
**Godot version : 3.0.1**

**OS/device including version :** Ubuntu 16.04 using GeForce 740m (NVidia binary driver 384.111)

**Issue description :** I started getting this error, I don't really remember at what point but I guess it happened since when I was scripting for a Label in C#, Not sure though !

Whenever I run my project I get this error in "Debugger" panel :
`0:00:00:0717 - Condition ' p_width < 0 && p_height < 0 ' is true.`
`Type:Error`
`Description: `
`Time: 0:00:00:0717`
`C Error: Condition ' p_width < 0 && p_height < 0 ' is true.`
`C Source: servers/visual/visual_server_viewport.cpp:344`
`C Function: viewport_set_size`

So then I tried to take a look at `viewport_set_size` function in `visual_server_viewport.cpp`, But I couldn't find out where it was called to trace it back, But the problem is this function's parameters are somehow negative.

Ah also, I was trying to change `Text` property of a `Label` But the label never updated its text. That is when I guess this problem started. So I removed this `Label` from my scene, but the problem persisted even after I removed that node. 

**Steps to reproduce :** I don't really know why and when this error started, But it doesn't seem to let go even when I quit and re-open my project.

**Minimal reproduction project :**
Here is the a zip file to the project : [Dodge.zip](https://github.com/godotengine/godot/files/1775659/Dodge.zip)

**Comment by Marshal313** [comment]
OK So I just built the master branch and tried running my project again, And got this error along with the last error :
`0:00:00:0030 - Condition ' !props.has(p_prop) ' is true.`
`Type:Error`
`Description: `
`Time: 0:00:00:0030`
`C Error: Condition ' !props.has(p_prop) ' is true.`
`C Source: core/project_settings.cpp:847`
`C Function: set_custom_property_info`

Thought it might help !

**Comment by Marshal313** [comment]
After spending some hours debugging the source, I Came to these conclusions :

- This error happens only after "Play" button is pressed (Either for "Current" or "Main" scene, Haven't tried "Custom"), After the game starts running.
- The reason for this error is that somehow the parameter passed to `viewport_set_size` method, has a value of of `inf` on its `x`, `y`, `width` and `height` properties.

Yet I'm trying to install a better Debugger / IDE (I ran into some problems with the current one I use !) so that I can actually view local variables to see what the problem really is.

**Comment by Marshal313** [comment]
OK, Meddling with Engine's project settings a little, I found I have set "Shrink" setting under "Display / Window" to 0, I've set it to 1 and the error doesn't appear anymore.
Yep my fault ...
Though, I don't know if I should close this issue or not, I guess setting this option to 0 must be avoided in the GUI.

**Comment by Calinou** [comment]
Setting shrink below 1 in the Project Settings isn't possible anymore since Godot 3.1, closing.
