### ISSUE TITLE
Make possible to add singleton from code for addons

### ISSUE THREAD

**Issue by jeremi360** [godotengine/godot#17180]
I write addon for godot 3.0 that need singleton in background to work,
and also its needed to make it easy to use from GDScript.
But now GDScript don't have any func 'add_singleton'.
Can be this added to GDScript?

**Comment by Noshyaar** [comment]
Is this what you have in mind? #16709

**Comment by jeremi360** [comment]
Yes! My bad, I search only open issue for this.  Then I close this issue.
