### ISSUE TITLE
Add API to project Vector3 to a plane or another vector

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17199]
**Godot version:**
`master` / 3d03bcd0636aacfe530c52fc1cdc32c2edffea04

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
It is often needed when creating a 3D game, to find out a projection of a vector on a plane (represented by its normal) or on another vector:
 * http://www.euclideanspace.com/maths/geometry/elements/plane/lineOnPlane/index.htm

Some other engines provides a method to easily calculate a projection to either on another vector or on a plane, so it'd be nice if Godot also supported such a feature:

_Example_: Unity's API

 ```c#
public static Vector3 Project(Vector3 vector, Vector3 onNormal);
```
```c#
public static Vector3 ProjectOnPlane(Vector3 vector, Vector3 planeNormal);
```

**Comment by Zylann** [comment]
Godot has the `Plane` variable type. In GDScript, you can do this:
```gdscript
var projected = Plane(normal, d).project(vector)
```
I don't know the C# equivalent though. `new Plane()`? Or maybe it was forgotten?

**Comment by mysticfall** [comment]
@Zylann Thanks! I didn't know that it existed already :)

I'll leave the issue open for the other variant for now. If there's such an API already, please let me know.

**Comment by reduz** [comment]
I would use Plane instead, seems a lot less confusing than adding a function to Vector3. I don't like the idea that we should implement the API in a certain way because Unity does.

**Comment by Luramoth** [comment]
> I would use Plane instead, seems a lot less confusing than adding a function to Vector3. I don't like the idea that we should implement the API in a certain way because Unity does.

probably because i spent 3 days trying to make my own version of this only to find out it already exists in a way i dident expect ;-;
