### ISSUE TITLE
Basis and Quat missing constructor that accepts euler angles in C#

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17198]
**Godot version:**
`master` / 3d03bcd0636aacfe530c52fc1cdc32c2edffea04

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
According to the documentation and #10721, it seems that `Basis` should have a constructor that accepts euler angles as `Vector3` but it is not the case with the C# binding.

The same goes for `Quat`, which should have `new Quat(Vector3 from)` according to the API reference for GDScript.

**Comment by Vega-KH** [comment]
It appears that the ```Basis (Vector3 from)``` constructor that is available in GDScript just returns the result of ``` Basis->set_euler_xyz(const Vector3 &p_euler) ``` from matrix3.cpp.  But looking at that, I realize that the C# API is also missing that function.  Lots of Euler functions are missing in the C# API like:

set_euler_xyz
set_euler_yxz
get_euler_xyz
get_euler_yxz
get_rotation
get_rotation_axis_angle

And probably a few more.  At least some of these are important and need to be added to the API before 3.1.

**Comment by Giacom** [comment]
Quat is also missing the euler constructor in GDScript 3.1 stable

```GDScript
var test := Quat(Vector3(0, 0, 0))
```

>Invalid arguments for 'Quat' constructor

**Comment by fossegutten** [comment]
Same as Giacom. I get this error when trying to construct Quaternion from euler angle: "Invalid call. Nonexistent 'Quat' constructor."

**Comment by kmare** [comment]
Yeah, I just noticed that GDscript is missing the constructor with the euler angle (Godot 3.1.1). Is it an omission or something we're supposed to avoid? (using euler for rotations etc)

**Comment by vybr** [comment]
Seems like an omission. If it isn't, the constructor should be removed from the class reference.

**Comment by bojidar-bg** [comment]
Duplicate of #28086?

**Comment by aaronfranke** [comment]
This has already been fixed a long time ago. Basis: https://github.com/godotengine/godot/pull/18974 Quat: https://github.com/godotengine/godot/pull/21205
