### ISSUE TITLE
Object._Get has wrong return type (void) in C# API

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17209]
**Godot version:**
`master` / 3d03bcd0636aacfe530c52fc1cdc32c2edffea04

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
`Object._Get` in C# binding has the following signature which is wrong, since it's supposed to be overriden to return custom property value but the return type is `void`:
```c#
public virtual void _Get(string property)
```

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by paulloz** [comment]
This is because the return type is `Variant::NIL` in [the bindings](https://github.com/godotengine/godot/blob/master/core/object.cpp#L1678-L1680).  
I can PR a change but am unsure of the implications :thinking:
