### ISSUE TITLE
Lines not erased when updating the 3D view 

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#17208]
I don´t know how to search for that strange thing
**Godot version:**

Godot 3 custom

**OS/device including version:**

Win 7

**Issue description:**

3D canvas becomes Amstrad CPC:
![wtfbug](https://user-images.githubusercontent.com/11712737/36930363-608df7c2-1e9f-11e8-9b83-c810991cd731.gif)

**Steps to reproduce:**
Open 3D editor, and drag middlebutton.

**Comment by vnen** [comment]
> Godot 3 custom

What is involved in this "custom"?

**Comment by Ranoller** [comment]
Godot 3 compiled from master at 19/02/2018 with dragonbones module (doesn´t extends any of the 3d nor the editor)

**Comment by Ranoller** [comment]
Ok... i find it. The node WorldEnvironment should have default environment although you only use 2D because ir breaks preview in 3D... I close this or this is a bug?

**Comment by bfloch** [comment]
Probably related.
You can even crash Godot with a world and an unsupported buffer: https://github.com/godotengine/godot/issues/16226

**Comment by Calinou** [comment]
I'll assume this was fixed by #31751, closing. Please comment if you can still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4).
