### ISSUE TITLE
Imported model have little separation between objects

### ISSUE THREAD

**Issue by OscarOG** [godotengine/godot#17207]
**Godot version:**
3.0.1

**OS/device including version:**
Windows 10

**Issue description:**
When importing a model from Blender, i found there is a little separation between objects. Is this an issue or just did something wrong?

![blender279](https://user-images.githubusercontent.com/22715737/65253929-c055b680-dafb-11e9-9e73-ee4babdce902.png)
![godot301](https://user-images.githubusercontent.com/22715737/65253940-c481d400-dafb-11e9-8ca5-93f447692e10.png)

**Steps to reproduce:**
Import model from Blender. Best Collada plugin used.

**Comment by akien-mga** [comment]
No answer, so closing.
Please comment if you can still reproduce the issue and we can reopen it (or open a new issue if it seems better suited).
