### ISSUE TITLE
Windows enter/exit mouse notifications missings

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#17202]
**Godot version:**

Godot 2 y 3

**OS/device including version:**

Windows platform

**Issue description:**

NOTIFICATION_WM_MOUSE_ENTER and NOTIFICATION_WM_MOUSE_EXIT never were delivered. I put the issue that has me an intense headache. I Fix now the issue so i made pull request. 

**Steps to reproduce:**
Try to catch any mouse in /mouse out notification in gdscript. There are not delivered.

**Comment by akien-mga** [comment]
Fixed by #17205.
