### ISSUE TITLE
Godot 3.0.1 Not casting shadows

### ISSUE THREAD

**Issue by cheomanigua** [godotengine/godot#17216]
**Godot version:**
v3.0.1.stable.official

**OS/device including version:**
Lubuntu 17.10.1
Linux 4.13.0-36-generic #40-Ubuntu x86_64
Graphic card: GeForce GTX 960/PCIe/SSE2
Driver: nvidia-384 - NVIDIA binary driver - version 384.111

Windows 10
Graphic card: GeForce GTX 960/PCIe/SSE2
Drivers: nvidia

**Issue description:**
Objects do not cast shadows

**Steps to reproduce:**
1. Created Spatial
2. Created a StaticBody + CollisionShape + MeshInstance cube and resized like a floor
3. Created a StaticBody + CollisionShape + MeshInstance cube and positioned above floor
4. Created DirectionalLight, enabled Shadow, Directional Shadow Max Distance set to 200

**Minimal reproduction project:**
[shadows.zip](https://github.com/godotengine/godot/files/1777272/shadows.zip)

**Comment by bfloch** [comment]
You have a directional light and it is perpendicular to the plane. This does cast a shadow. Basically the whole plane is in shadow.

![shadow](https://user-images.githubusercontent.com/2116566/36932366-dab15cb0-1e95-11e8-9a46-e430da0b7f37.gif)
  
Rotate the light to point towards the ground.

**Comment by cheomanigua** [comment]
Hi bfloch

Oh my, that's embarrassing. Thanks for your answer, never thought about rotating the directional light.

Cheers
