### ISSUE TITLE
StringExtensions API uses mixed naming convention in C#

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17212]
**Godot version:**
`master` / 3d03bcd0636aacfe530c52fc1cdc32c2edffea04

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
While most of the methods defined in `StringExtensions` follows Pascal case, which is the convention used by other parts of the Godot's C# API, there are number of exceptions like `to_lower` or `to_utf8` that still follow snake case.

**Comment by paulloz** [comment]
Hi, can this be re-opened? While writing documentation, I saw that my previous PR missed [a couple of fields in the Transform class](https://github.com/godotengine/godot/blob/master/modules/mono/glue/cs_files/Transform.cs#L15-L16) (they should start with an uppercase letter).

**Comment by aaronfranke** [comment]
@paulloz I disagree with changing these, as they're variables. It's common in C# to have PascalCase methods, camelCase variables, and UPPERCASE constants. It makes them easy to differentiate, and this is the styling that Unity uses (and while this isn't the only reason to do it this way, appealing to Unity users should definitely be a goal of Godot C# to promote Godot).

Either way: https://github.com/godotengine/godot-docs/issues/1296

**Comment by mysticfall** [comment]
@aaronfranke I don't think it'd be a good idea to follow Unity in this matter, as it's notoriously negligent in following the standard coding conventions (i.e. lower case properties).

I think it'd be more reasonable to follow the style guide published by MS themselves which suggests using PascalCase for constants:

 * https://blogs.msdn.microsoft.com/mschray/2013/05/06/practical-naming-standards-for-c/
 * https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

But as you said, I agree that it'd be better to continue the discussion in the other thread.

**Comment by neikeq** [comment]
Is this issue still valid?

**Comment by aaronfranke** [comment]
Looking through the file, it definitely is. There's also a few other things I'm wondering if we should change. Several methods are defined multiple times with case sensitivity booleans, but it would be better to just have it be an optional parameter. But also, some of these are `case_sensitive` and some are `case_insensitive`. Should we be case-sensitive or case-insensitive by default?

**Comment by aaronfranke** [comment]
This issue should be solved as of https://github.com/godotengine/godot/pull/21822, if anyone finds any other issues feel free to mention them and/or make a PR. By the way, it looks like we're doing case-sensitive by default.

**Comment by neikeq** [comment]
Closed by #21822
