### ISSUE TITLE
Omni lights exhibiting very buggy behaviour when nested in the hierarchy

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#17214]
**Godot version:**

Godot 3.0.1

**OS/device including version:**

WIn10 gtx960m

**Issue description:**

I have been having some very strange problems with omni lights in my game for a while now, so this is not a recent bug. I have been having omnis randomly turn off/on and omnis not lighting nearby meshes that should be lit. Was a tricky bug to isolate, but I have managed to trap the little critter with the attached scene.

As can be seen here, moving the omni up and down on the y axis in 0.1 steps goes from nothing being lit, to only the middle cube to the cube/floor but not the outer cubes:

![omni_bug1](https://user-images.githubusercontent.com/7741669/36931358-18b5b5ca-1f08-11e8-815b-34394a967a3f.gif)

Similarly buggy behaviour can be seen as the range radius is adjusted in the viewport. Also note that the inspector does not update which is another bug.

![omni_bug2](https://user-images.githubusercontent.com/7741669/36931386-575bb9fa-1f08-11e8-8d80-fd3199061318.gif)

**Steps to reproduce:**
- create a new scene and add a spatial node
- add 2 mesh instance nodes and make them both cubes
- scale one of these cubes on y axis into a floor and scale the other down uniformly and place on top of floor
- select the smaller cube and add an omni so that it becomes a child of the small cube
- move the light up and down on the y axis and note the odd behaviour with light cutting out as you move
- if the omni is moved in the hierarchy  so that it is a child of the spatial node it still exhibits this behaviour
- however, if the omni is initially created as a child of the root/spatial node, it works fine and if it is then parented to the small cube it is also fine. It seems that the initial placement in the hierarchy is what brings on this behaviour.

NOTE: it seems that most of the issues I have in my game with omnis stem from omnis in hierarchies. Either within the same scene or instanced into a master scene from a sub scene. The further nested the omni is in the hierarchy, the flakier the behaviour becomes, with them turning on/off at random and not lighting nearby meshes that they should. For example if I have an npc scene with a light in it, that is then instanced into a room scene, and then that room is instanced into a master scene...lots of random glitchiness with the light can ensue. Doesn't happen every time though, it is quite random.

**Minimal reproduction project:**

[omni_lighting_bug.zip](https://github.com/godotengine/godot/files/1777184/omni_lighting_bug.zip)

**Comment by eon-s** [comment]
The light transform scale is 0.36, and is child of something with a scale of 0.13, the light on scale 1 works fine, I think light breaks on too low scales.

**Comment by reduz** [comment]
Radius may not be scaled by transform, need to check that..

**Comment by eon-s** [comment]
The omnilight radius can be scaled? What would happen in non uniform scales then?

**Comment by fracteed** [comment]
@eon-s aha, good observation! I hadn't considered that the light was of course inheriting the transform of the parent node. If I drag that same omni out from being a child of the cube and scale it back to 1, yes it does work. However, if I change it to 1 while it is still a child of the cube, it doesn't work. I have to crank it up to about 2.5 for it to work. Not sure why scale is even affecting an omni? Is it affecting the range, as I can't see that actually moving?

@reduz would be great to get a fix for this, as it can be common to create an object with a light in a separate scene that will be instanced/scaled into a master scene.

**Comment by fracteed** [comment]
After a lot of playing around with my game, it seems that many of the random omni problems (aside from this scaling issue) stem from having too may omnis in the scene. Since the Godot output console tells me that opengl 3 can have a maximum of 409 lights, I had assumed that my 50 - 100 omnis in a scene was ok. When I pare it down to below 50 it does seem more stable.
@reduz what is a realistic max of omnis to use at the moment? Maybe I have to wait for clustered rendering and/or Vulkan for better performance in this area?

**Comment by gad-o** [comment]
I think omnilight radius should be able to scaled by transform, because we can use it in a child-parent relationship.
Beside this, spotlight have a different behavior than omnilight. It seems that spotlight radius-angle handles doesn't change radius-angle but changes transform cause indirect scaling effect for light.

**Comment by reduz** [comment]
This is fixed now, had to do with light nodes being scaled.
Should no longer happen, but just in case let me know if it does.
