### ISSUE TITLE
C# editor strings are not translatable (no TTR() support)

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17228]
**Godot version:**
cf0bc13

**Issue description:**
The C# support warning fired at the start of the editor lacks the `TTR` function, making it not translatable to other languages.

I would fix this myself, but for that I would have to install Mono to test it, and as I don't have any plans on using C#...

**Comment by aaronfranke** [comment]
Considering that this is a temporary notice, it isn't very high of a priority to do. I looked around at the TTR code and I wasn't able to figure it out, so I won't be including this in my PR, but it could be done later.

**Comment by Calinou** [comment]
[@neikeq mentioned the possibility of using it in the editor C# project](https://github.com/godotengine/godot/pull/31652#issuecomment-524657254), but will how will the generated `.pot` template take it into account?

**Comment by neikeq** [comment]
> but how will the generated .pot template take it into account?

Didn't think of that. If I can't find a way for it to use the `TTR`s from C# code I will have to move or copy the strings to C++.

**Comment by akien-mga** [comment]
The `.pot` is generated by https://github.com/godotengine/godot/blob/master/editor/translations/extract.py, where `.cpp` and `.h` files are parsed from Python to extract `TTR` strings.

C++ wise `TTR()` is just a no-op, though on non-tools build it's replaced by `String()` as those are only relevant for the editor. (See `core/ustring.h`.)

So for C# code, you'd need any kind of no-op macro or function that can be used for those strings, and extracted by the python script.

**Comment by KoBeWi** [comment]
Is this still valid in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or any later release?

**Comment by YeldhamDev** [comment]
@KoBeWi As far as I'm aware, yes.

**Comment by YeldhamDev** [comment]
Closed by #50476.

**Comment by neikeq** [comment]
This is not really fixed, is it? At least not if we consider this issue's title. That dialog may have been removed but there are still other parts using `TTR`.
