### ISSUE TITLE
Run .exe file occurred error for window 10 (Mono version C#)

### ISSUE THREAD

**Issue by leewonghao** [godotengine/godot#17229]
**Godot version:** Mono version (C#) 3.0.1

**OS/device including version:** window 10

**Issue description:**
When I export to .exe file for windows but I run the file then the error occurred.
Someone please help me. Thank you.

![capture1](https://user-images.githubusercontent.com/8869627/36937542-a0004c54-1f47-11e8-9843-d0b8b309048c.PNG)

**Comment by mhilbrunner** [comment]
Exporting projects is not yet implemented fully for the C# version of Godot.

See https://github.com/godotengine/godot/issues/15615.

Note that the C# version comes with a big warning on the first start that this is not yet possible.

**Comment by neikeq** [comment]
One of the two TODOs I mention in #16920 is using the export templates compiled with the mono module.
If you don't want to wait for that to be implemented, you can compile the export templates yourself with the mono module, and replace the executable `demothud.exe` you got with the one you compiled and the mono runtime dll.
