### ISSUE TITLE
Issues with ViewportTexture flags

### ISSUE THREAD

**Issue by efirdc** [godotengine/godot#17220]
**Godot version:**
`Godot_v3.0.1-stable_win64.exe`

**OS/device including version:**
Windows 10

**Issue description:**
ViewportTexture flags are cleared every time a scene is reloaded or when the ViewportTexture is instanced in another scene. By default a ViewportTexture will have only the filter flag enabled, and all other flags disabled, but no matter what flags are set they are all cleared on reload.

Another probably related issue is that all ViewportTextures to the same Viewport will share the same flags, even if you try to set one of them as unique. This isn't always desired behavior. For example I am working on a GPU fluid simulation. I need my advection fragment shader to have the filtering flag set, but I don't want filtering on the texture that displays the fluid, or on all the pressure iterations (especially if there is a performance impact from filtering).

**Steps to reproduce:**
- Create two `TextureRect`s and a `ViewportTexture`. 
- Give the TextureRects a ViewportTexture to the Viewport.
- Change the flags on one of the ViewportTextures. The flags on the other one should change to match.
- Reload the scene, flags will clear.

**Comment by CptPotato** [comment]
> Another probably related issue is that all ViewportTextures to the same Viewport will share the same flags, even if you try to set one of them as unique.

I want to mention that this is still an issue in the current master branch. I was really confused by this and it took me a while to find out that the shared flags were the issue.

**Comment by KoBeWi** [comment]
No longer relevant in 4.0, as most of Texture-related flags were moved to CanvasItem properties.
