### ISSUE TITLE
Documentation does not mention size of ints / floats etc.

### ISSUE THREAD

**Issue by admiralzeech** [godotengine/godot#17224]
Hi, I can't find any reference in the documentation about whether the ints and floats are 32bit or whatever.
Also, are there built-in constants like C's "INT_MAX" to assist with respecting the limits of these types?

I think it's important to mention the size in both the API reference and this page:
http://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html

Also, we should have some internal constants, like:
https://www.tutorialspoint.com/c_standard_library/limits_h.htm

Thanks.

**Comment by admiralzeech** [comment]
Thanks! The second part of my comment (regarding internal constants) is not addressed.  Should I raise a separate issue for it?

**Comment by bojidar-bg** [comment]
Yeah, open a separate issue about it.
