### ISSUE TITLE
ViewportTexture sampling has many artifacts

### ISSUE THREAD

**Issue by efirdc** [godotengine/godot#17234]
**Godot version:**
`Godot_v3.0.1-stable_win64.exe`

**OS/device including version:**
Windows 10, GTX 770

**Issue description:**
I wrote a fragment shader that detects sampling artifacts in ViewportTextures.

![image](https://user-images.githubusercontent.com/5416313/36939369-e24f43f4-1eec-11e8-9bdd-fc40e041ac0d.png)

In this image the blue pixels have unexpected values in adjacent pixels. There are always errors along the diagonal of the texture, and errors frequently show up in a 16x16 grid pattern as well.

This is the node structure for the scene:

![image](https://user-images.githubusercontent.com/5416313/36939399-76a4018e-1eed-11e8-8599-b3128c06bca7.png)

If you enable multiple passes the errors get much worse.

The display and pass# nodes are TextureRects with ViewportTextures to the Viewport. The pass# nodes have the fragment shader. The shader basically works by increasing the color of every pixel each frame, and also comparing it to the color of adjacent pixels. If at any point it gets an unexpected value it will flash the blue channel of the pixel. The red channel and green channels are incremented or decremented in opposite directions. Which direction red/green goes alternates in a checkerboard pattern over each pixel of the texture. So on every frame the red channel should have the same value of  the green channel of the adjacent pixels, and the green channel of the center pixel should equal the red channel of the adjacent pixels.

I used this alternating pattern so that it has to get the adjacent pixel. If for some reason it tries to sample up and gets a different pixel, it should give an error. 

This is the scene:

[sampling_errors.zip](https://github.com/godotengine/godot/files/1777922/sampling_errors.zip)

Maybe it is not intended to use ViewportTextures in viewports as "ping-pong" textures. Using SCREEN_TEXTURE with BackBufferCopy nodes does not have these errors, but for some things ViewportTexture references are required. For example I am working on a GPU fluid simulation that stores many quantities in different viewports (velocity, pressure, densities, temperature, solids), with many fragment shaders that reference them. So ViewportTextures will make things quite messy.

[Relevant issue](https://github.com/godotengine/godot/issues/16828)

**Comment by clayjohn** [comment]
For reference if anyone else stumbles on this in the future. This issue is caused by OpenGLs default mipmapping when using ``texture()``. The inconsistencies arise from the OpenGL driver selecting higher mipmaps in certain cases (which is what texture is supposed to do). The solution is to instead specify your own mip level using ``textureLod()``.

**Comment by Zireael07** [comment]
How about adding this bit to documentation somewhere?

**Comment by clayjohn** [comment]
@Zireael07 Do you have anywhere in mind? 

We often don't document things like this as it is an OpenGL quirk rather than a Godot issue. So it is very difficult to find a place in the docs for this kind of information where users will actually find it.

**Comment by Zireael07** [comment]
I believe we had several issues that boiled down to OpenGL quirks, so it might be worth having a separate subpage under shading language?
