### ISSUE TITLE
Line2Ds with textures with transparency look weird when doing sharp turns

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17241]
**Godot version:**
 184b2fe

**Issue description:**
A picture is worth a thousand words:
![line](https://user-images.githubusercontent.com/30739239/36941401-30e5df0e-1f39-11e8-9b4f-a5fe1d139760.png)

**Comment by Zylann** [comment]
Sharp turns make it hard for the geometry of the line to keep up, so what happens is, the line produces an overlapping cut, because otherwise you would get a strong distortion instead. 

In yout case it also look like your texture is not completely transparent, making the overlap visible.

**Comment by Zylann** [comment]
That could be related to https://github.com/godotengine/godot/issues/16961 though

**Comment by hpvb** [comment]
Is this on windows? Trying to work out if this is the vector thing or something else.

**Comment by Zylann** [comment]
@hpvb I think it is, in the first screenshot the glitched UV is exactly in a corner.

**Comment by YeldhamDev** [comment]
@Zylann I'm on Manjaro Linux.

**Comment by Zylann** [comment]
@YeldhamDev that might have hidden the problem, but the glitch is probably still here though. The glitch appears grey precisely because the UVs go back to zero, which is grey with filtering.
