### ISSUE TITLE
code complete suggestion : type comment

### ISSUE THREAD

**Issue by loohoo** [godotengine/godot#17242]
**Godot version:** 3.1

**Issue description:** more smart code completion

is there possible let gd code editor to parse type define in comment and improve code completion ?
just Iike [JsDoc](https://www.jetbrains.com/help/webstorm/creating-jsdoc-comments.html) in webstrom

**Comment by akien-mga** [comment]
It's already planned to add optional type hinting (so not just as comments, but as actually working typing information) in GDScript, which will solve this use case.
