### ISSUE TITLE
Audio driver not working, Godot stop when changing driver

### ISSUE THREAD

**Issue by LudovicGuerra** [godotengine/godot#17259]
**Godot version:** 3.02

**OS/device including version:** Windows 10, GeForce GTX960

**Issue description:**
Check this image, this is self explanatory:
![sans titre](https://user-images.githubusercontent.com/19329243/36948630-e95bd4f4-1fdd-11e8-9dfd-8fdac0b535c5.png)
First I have audio driver problem.
Then I tried to change the audio driver with RtAudio-DirectSound.

Now everytime I try to relaunch my project, godot simply stop to work (was pretty hard to get this image as it instantly stop).

**Steps to reproduce:**
Create new project.
Change audio driver, save and switch to origin panel (where you can choose the project)
Reselect your project
Profit

**Minimal reproduction project:**
[instancing.zip](https://github.com/godotengine/godot/files/1778773/instancing.zip)

**Comment by marcelofg55** [comment]
I just tested your project but it didn't crash for me, could you run it with a debug build and post the backtrace again? (I can provide a debug build if you need it)

**Comment by LudovicGuerra** [comment]
Ok after your feedback I tried to investigate further on my part. Seems it's because I got a dedicated audio card. I did some work around it and now I don't have this error anymore.  I close it and reopen it if my work around fail.
