### ISSUE TITLE
Failed to build GodotSharp solution - v3.0.2 stable

### ISSUE THREAD

**Issue by podpathos** [godotengine/godot#17251]
#16327
**Godot version:**

Godot_v3.0.2-stable_mono_win64

**OS/device including version:**

Windows 7 x64

**Issue description:**

Can't build C# solution in v3.02. stable. VSC output:
The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

**Steps to reproduce:**
New Project
Add any Node
Attach C# script
Save scene and run

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Do you have the Mono SDK installed?

**Comment by podpathos** [comment]
Yes. I reinstaled Mono and .Net and now it's working. Don't know what was causing the problem.

**Comment by WallyCZ** [comment]
I had exactly same issue until I have installed .NET 4.5 Developer pack from Windows 8 SDK https://docs.microsoft.com/cs-cz/dotnet/framework/install/guide-for-developers

**Comment by akien-mga** [comment]
Closing as it's a local config issue then (though the usability could be improved, but there are other bug reports keeping track of that).
