### ISSUE TITLE
Editor crashes when trying to add C# script

### ISSUE THREAD

**Issue by WallyCZ** [godotengine/godot#17278]
**Godot version:**
Godot_v3.0.2-stable_mono_win64

**OS/device including version:**
Windows 10 1709 x64
Mono 5.10.0.140 x64

**Issue description:**

When trying to assign new C# script to Label node (but also to other nodes) editor crashes:

CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] mono_image_get_name
[1] mono_image_get_name
[2] mono_image_get_name
[3] mono_image_get_name
[4] mono_image_get_name
[5] mono_image_get_name
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] mono_image_get_name
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
-- END OF BACKTRACE --

Project runs inside editor without any script without any issues

**Steps to reproduce:**
Add root node, add CanvasLayer, add label, assign new C# to it, click Create
Or Mono/Create C# solution

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by Zylann** [comment]
Did you give a name to the script or you left the default name?

**Comment by WallyCZ** [comment]
I left default: "res:///Label.cs" (Label was name of that node)

**Comment by WallyCZ** [comment]
It crashes the same way if I choose Mono/Create C# solution

**Comment by Zylann** [comment]
@WallyCZ does it crash if you choose a different name that is not the name of an existing node, like "Test"?

**Comment by WallyCZ** [comment]
Yep, it also crashes.

But now I found real cause of this crash - I used Mono 5.10 but there is notice in release notes that it currently runs only on 5.4.x - after reinstalling Mono to right version it works (but it crashes elsewhere - but I have found existing issue on this)
