### ISSUE TITLE
3D Editor inconsistent lines color

### ISSUE THREAD

**Issue by Creuilcreuil** [godotengine/godot#17270]
**Godot version:** 
3.0.2

**OS/device including version:** 
Ubuntu LTS 16.04.4

**Issue description:** 
3d lines colors are inconsistent

![godot_bug_lines](https://user-images.githubusercontent.com/12054179/36954039-7d363156-201f-11e8-9008-fd1b9dd7fc21.gif)

**Steps to reproduce:**
Open the 3d editior

**Comment by eon-s** [comment]
Graphics card? 
Looks like a duplicate of #17029

**Comment by leotada** [comment]
Same to me with AMD RX480 using open source driver AMDGPU.

**Comment by vnen** [comment]
Closing as duplicate of #17029.
