### ISSUE TITLE
Unable to View Tree Leaves from certain angle (Tree Sapling)

### ISSUE THREAD

**Issue by Supatier** [godotengine/godot#17272]
**Godot version:**
3.0.2

**Issue description:**

I made a tree in blender with tree sapling and exported it to godot with glTF (same thing with better collada).  But you can't see the leaves from certain angles. 
Here's a top view:
![tre2](https://user-images.githubusercontent.com/19777767/36962398-fb4ce942-2081-11e8-9694-6dd69f12712d.png)
Everything is normal, but from the side and bottom you can't see the leaves.

![tre](https://user-images.githubusercontent.com/19777767/36962370-e315521a-2081-11e8-9a28-ed3e0f23e824.png)

**Steps to reproduce:**
Import the glTF file with new Inherited.

**Minimal reproduction project:**

[Tree.zip](https://github.com/godotengine/godot/files/1779884/Tree.zip)

**Comment by Cygon** [comment]
In realtime 3D rendering, all faces are one-sided by default.

This has several reasons:
- Most objects (eg. a rock, a character) are airtight enclosures, so there's no need to render their insides or the faces that point away from the camera
- Lighting calculations only need to deal with the plain normal vector (if the backside of a face was rendered, lighting calculations would have to be done a second time with the inverse normal).

To get the same effect in Blender as you have in Godot, enable `Backface Culling`:
![blender-backface-culling](https://user-images.githubusercontent.com/3613175/36986032-17d76f8a-2099-11e8-909e-8001a1fc2bb8.png)

To fix the issue, you can either
a) copy the leaves in blender, go to edit mode, select all, flip normal
or
b) disable backface culling in Godot
![godot-disable-culling](https://user-images.githubusercontent.com/3613175/36986163-769e054c-2099-11e8-9a82-41b4a8342e22.png)

*I haven't checked how Godot's lighting system handles backfaces. If you try the second option, better check if the lighting looks right from below the tree*

**Comment by Supatier** [comment]
I copied the leaves and it worked.
