### ISSUE TITLE
unnecessary node in navigation result causes infinite jitter when following path

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#1728]
Using Navigation2D, I've encountered a situation when the start point (the player position) crosses over one of the path nodes.  The next path calculated still contains this node, despite it being unnecessary.  It's not technically an invalid path, as it still eventually leads to the goal, but moving in the direction of that node puts the player back on the other side of that node, so the next calculated path naturally includes that node again.  The end result is that the player oscillates around that path node forever.  I know this is a side effect of the way I'm using the path result, since the path provided isn't actually *wrong*.  But the node is uneeded, and if it weren't there, this easy method of moving along the path would work.

Example project:
https://copy.com/jqROb71r3JyUCUBd

**Comment by reduz** [comment]
I don't completely understand what's going on in the demo but it appears you are recomputing the path every frame..
It also doesn't make much sense that it goes back a node, do you think you could provide on this example the moment when a wrong path  is created so I can take a look at it?

**Comment by akien-mga** [comment]
> It also doesn't make much sense that it goes back a node, do you think you could provide on this example the moment when a wrong path is created so I can take a look at it?

Ping.

**Comment by akien-mga** [comment]
I can't seem to download the test project as the file sharing website seems to be in maintenance (was already a week ago too).

**Comment by akien-mga** [comment]
No answer to the above query, so closing as old, since there's not much to be done without additional info.
