### ISSUE TITLE
C# Godot 3.0.2 - Renaming Project does not change all files

### ISSUE THREAD

**Issue by alexbosquin** [godotengine/godot#17281]
When you rename your project through project listing, id does not change the following files/foldes:

* Folder Name
* .csproj
* .sln
* AsselmblyInfo.cs -> [assembly: AssemblyTitle("project-name-here")]
* project.godot -> config/name="godot-topdown-base"

**Comment by paulloz** [comment]
Related to #15624

**Comment by alexbosquin** [comment]
thank you paulloz, the topics are really related, and complement each other!!!

**Comment by Calinou** [comment]
This was implemented in https://github.com/godotengine/godot/pull/37116, closing.
