### ISSUE TITLE
Search highlight hard to see

### ISSUE THREAD

**Issue by Enhex** [godotengine/godot#17290]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
When viewing documentation inside the editor, the search highlight is black, and when the search box is open there's a dark overlay, and there's a dark background color, which makes the highlighted text very hard to spot.

Perhaps use a bright highlight instead of a dark one (like the code editor does).

Example:
![godot_v3 0 2-stable_win64_2018-03-05_23-46-10](https://user-images.githubusercontent.com/7088062/37001515-746b2e90-20cf-11e8-981a-190e7be3d79f.png)

**Comment by Zylann** [comment]
I'm pretty sure this has already been reported but I can't find the original...
