### ISSUE TITLE
Artifacts when using textureLod

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#17294]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10
Nvidia GeForce GTX 1080, driver version 388.71

**Issue description:**
With a combination of requirements (ones I think not atypical) I get artifacts when using `textureLod` 
![depth](https://user-images.githubusercontent.com/1546044/37009696-f3dc097a-209c-11e8-928e-6c1a6413fedd.gif)

**Steps to reproduce:**
1. You need a material that reads from the screen using `textureLod(SCREEN_TEXTURE,SCREEN_UV,0.5)` (0.5 can be anything above 0.0)
2. You need opaque geometry in view
3. You need a custom world environment
4. You need 2 or more visible lights

It's easier to see if the thing reading the screen texture is overlapping the opaque geometry.
if any of these aren't met it doesn't appear to happen.

**Minimal reproduction project:**
[example.zip](https://github.com/godotengine/godot/files/1783221/Depth_Bug.zip) (sorry it says depth bug all over it, I thought it was an issue related to depth_texture)

**Comment by akien-mga** [comment]
Is this fixed?
