### ISSUE TITLE
--doctool should create directories if they don't exist

### ISSUE THREAD

**Issue by calviken** [godotengine/godot#17297]
Running `godot --doctool` outside the build directory has this output:

```
Loading docs..
Loading docs from: ./modules/gdnative/doc_classes
Loading docs from: ./modules/stb_vorbis/doc_classes
Loading docs from: ./modules/opus/doc_classes
Loading docs from: ./modules/bullet/doc_classes
Loading docs from: ./modules/gdscript/doc_classes
Loading docs from: ./modules/gridmap/doc_classes
Loading docs from: ./modules/mobile_vr/doc_classes
Loading docs from: ./modules/enet/doc_classes
Loading docs from: ./modules/regex/doc_classes
Loading docs from: ./modules/theora/doc_classes
Loading docs from: ./modules/webm/doc_classes
Loading docs from: ./modules/visual_script/doc_classes
Loading docs from: ./doc/classes
Merging docs..
Erasing old docs at: ./doc/classes
Erasing old docs at: ./modules/bullet/doc_classes
Erasing old docs at: ./modules/enet/doc_classes
Erasing old docs at: ./modules/gdnative/doc_classes
Erasing old docs at: ./modules/gdscript/doc_classes
Erasing old docs at: ./modules/gridmap/doc_classes
Erasing old docs at: ./modules/mobile_vr/doc_classes
Erasing old docs at: ./modules/opus/doc_classes
Erasing old docs at: ./modules/regex/doc_classes
Erasing old docs at: ./modules/stb_vorbis/doc_classes
Erasing old docs at: ./modules/theora/doc_classes
Erasing old docs at: ./modules/visual_script/doc_classes
Erasing old docs at: ./modules/webm/doc_classes
Generating new docs..
ERROR: save_classes: Can't write doc file: ./doc/classes/@GDScript.xml
   At: editor/doc/doc_data.cpp:964.
```
It gives up if one of the directory paths doesn't exist, so I have to manually create all of them just to get the command to succeed. Is there any reason why the directories aren't created automatically?

**Comment by calviken** [comment]
On a related note, it seems that any docs generated with `--doctool` are missing all class and function descriptions. I guess there's a lot of work to be done in that area.

**Comment by vnen** [comment]
> On a related note, it seems that any docs generated with `--doctool` are missing all class and function descriptions. I guess there's a lot of work to be done in that area.

Well, the descriptions are stored in the XML itself, so if the description wasn't there before (or if the file didn't exist) the generated parts won't have any description.

**Comment by calviken** [comment]
Problem solved. Solution: I'm a dumdum.

 I thought `--doctool` simply dumped the documentation embedded in the executable as-is so it can be used in an external tool (which is what I was trying to do).  I guess it's meant to be used only when developing the engine. In that case, my issue with the directories is pretty much invalid because there's no reason to run it outside the build directory anyway.

I'm going to go ahead and close this issue and pretend it never happened.

**Comment by akien-mga** [comment]
Well it should still create the directories if missing.

**Comment by calviken** [comment]
> Well it should still create the directories if missing.

Seems to me that there aren't any situations where the directories wouldn't already exist, though. Really what should happen is the line in `godot -h` explaining `--doctool` should be made less misleading, so other poor saps like myself don't try to use it for some unintended purpose.

It *would* be nice if `--doctool` could be used in the way I was trying to use it (generating standalone docs), but that seems like a separate issue entirely.
