### ISSUE TITLE
Assets imported using headless build (platform=server) are broken

### ISSUE THREAD

**Issue by sdfgeoff** [godotengine/godot#17308]
**Godot version:**
Current Master
Server build is done with flags: `platform=server -j 8 target=release_debug separate_debug_symbols=yes`

**OS/device including version:**
Linux. Tested on both Kubuntu 16.04 and Kubuntu 17.10

**Issue description:**
When the headless build has to import assets, they import "broken."
This issue was noticed when exporting a game using the command line from a server build, and the resulting .pck or .zip file has broken assets. After some investigation it was discovered that this was only an issue when the assets were re-imported by the headless build. If the assets are already imported from a non-server build, then they are not rebuilt and the exported zip plays fine.

Inspecting the zip files reveals a vast size difference between asset files. The .scn files that come from .dae files are often 5-6 times larger in the export that works.
When running `godot --main-pack export_broken.zip` the result is that the model doesn't show, and in the console informs you that:
```
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
ERROR: mesh_add_surface: Condition ' !(p_format & VisualServer::ARRAY_FORMAT_VERTEX) ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:2672.
ERROR: instance_set_surface_material: Index p_surface=0 out of size (instance->materials.size()=0)
   At: servers/visual/visual_server_scene.cpp:604.
```

Sample Project: [ExportTest.zip](https://github.com/godotengine/godot/files/1788417/ExportTest.zip)

Export from server: [export_broken.zip](https://github.com/godotengine/godot/files/1788829/export_broken.zip)
Export from editor: [export_working.zip](https://github.com/godotengine/godot/files/1788831/export_working.zip)

Exports were performed with:
```
export-server:
	rm -rf .import
	$(GODOT_SERVER) --export pck export_broken.zip
	
export-editor:
	rm -rf .import
	$(GODOT_EDITOR) --export pck export_working.zip
```

Diff between zips:
```
$diff -y <(unzip -l export_broken.zip) <(unzip -l export_working.zip)
Archive:  export_broken.zip                                   | Archive:  export_working.zip
  Length      Date    Time    Name                                Length      Date    Time    Name
---------  ---------- -----   ----                              ---------  ---------- -----   ----
      621  1980-00-00 00:00   Main.tscn                               621  1980-00-00 00:00   Main.tscn
     3533  1980-00-00 00:00   .import/icon.png-487276ed1e3a0c        3533  1980-00-00 00:00   .import/icon.png-487276ed1e3a0c
      649  1980-00-00 00:00   icon.png.import                         649  1980-00-00 00:00   icon.png.import
     1703  1980-00-00 00:00   .import/Monkey.dae-9595bdbecdf0 |     41935  1980-00-00 00:00   .import/Monkey.dae-9595bdbecdf0
    31836  1980-00-00 00:00   resources/Monkey.dae.import           31836  1980-00-00 00:00   resources/Monkey.dae.import
     2580  1980-00-00 00:00   resources/default_env.tres             2580  1980-00-00 00:00   resources/default_env.tres
     3498  1980-00-00 00:00   icon.png                               3498  1980-00-00 00:00   icon.png
      261  1980-00-00 00:00   project.binary                          261  1980-00-00 00:00   project.binary
---------                     -------                           ---------                     -------
    44681                     8 files                         |     84913                     8 files

```

Notice the ones with a vertical bar in the middle. Look at the difference in filesize. 

Oh look, my time machine is acting up again.

**Comment by sdfgeoff** [comment]
So I've added same projects and sample broken export zips (and some more debug information).

It turns out not to be the export that's the problem, but to be the asset _import_. The headless build doesn't import assets correctly, so they don't export correctly. As a result, this problem only manifests itself if the .import folder needs to be generated by the headless build.

**Comment by fire** [comment]
If somehow you were able to generate the .import for dae file, such as being stored in source control, you can export correctly.

Your demo only shows dae (collada) failing to import.

Png works.

**Comment by sdfgeoff** [comment]
Yup, it's to do with the .import folder. However, I'd rather not have this folder in source control (binary blobs).

It's to do with any resource that needs conversion on import: .dae's, .obj's, escn's, etc.

**Comment by sdfgeoff** [comment]
I've been trying to chase this down, and haven't had much luck. Both reading the scene from text format in `scene_format_text.cpp` seems to be taking place OK (node count is correct), and packing is also happening `SceneState::pack(Node *p_scene)` with object properties appearing to be processed correctly.

The only thing remaining is that it's something to do with sub-resources.

**Comment by jfaust** [comment]
I'm running into this as well. Did you ever find a solution @sdfgeoff ?

**Comment by vnen** [comment]
Is this related to #18680?

**Comment by sdfgeoff** [comment]
@jfaust:
Currently I have a monitor plugged into our build server, so I run `xhost+` from the graphically-logged-in-user, and then use `export DISPLAY=:0` which allows the user of regular Godot. Obviously, this only works if you have a screen plugged in. I also tried various things with `xvfb` without success.
But all of these are workarounds. I hope to invest some development time into this in the near future.

@vnen:
This is to do with imports of 3D models and scenes. It seems that images work fine. (Although there is a compile issue on the server build I had recently that looks like it may be fixed by that PR).

**Comment by jfaust** [comment]
Ah, we're not able to do that (we're in a virtualized environment in a cluster). I'll be beginning to look into this today then.

@vnen That ticket is about loading a (presumably correctly built) pck file in a server build. This is about importing assets (and then generating a pck file) in a server build.

**Comment by jfaust** [comment]
I've figured out where this is coming from. The difference between the good and bad packed binary . scenes is that all the mesh surface information in the bad export have default values (including zero-sized arrays for index/vertex buffers/etc.). 

This happens because the actual backing storage for those arrays is handled by `RasterizerStorage`, and `ArrayMesh` just calls `VisualServer::mesh_surface_get_array` et al when asked for surface properties (which pass through to `RasterizerStorage`). When `platform=server`, that's the `RasterizerStorageDummy`, which immediately throws away the data, and when asked for it later just returns an empty array.

Seems like I should be able to add some `#ifdef TOOLS_ENABLED` sections into `RasterizerStorage` that store off all the necessary data for later retrieval, but maybe there's a better/different way?

**Comment by jfaust** [comment]
@fire `mesh_surface_get_array` is used in the import process, to then write the imported scene to disk. Since `RasterizerStorage` is supposed to own all the mesh surface data, retrieval of that data (to write it to disk) also goes through `RasterizerStorage`. This means we end up with empty arrays for index/vertex/etc. buffers.

`RasterizerStorageDummy` already had code for this for textures (I'm assuming that's why texture import works), which was not ifdefed, so in my patch I also do not ifdef the code. 

PR created: https://github.com/godotengine/godot/pull/18798

**Comment by sdfgeoff** [comment]
Now they're at least both the same, but currently exports both from server and normal build are broken - they cause Godot to freeze throwing:
```
ERROR: get_line: Condition ' !f ' is true. returned: String()
   At: core/bind/core_bind.cpp:1697.
ERROR: eof_reached: Condition ' !f ' is true. returned: false
   At: core/bind/core_bind.cpp:1602.
```

but that's a different issue, and I'll have to investigate to see what is causing it. I suspect it's a single asset....
