### ISSUE TITLE
Collision shape not updating after changing extents (debug mode)

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#17300]
**Godot version:**
Godot 3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
Changing the extents of a collision BoxShape in code does not reflect the change when "Visible Collission Shapes" is turned on in the debug menu.
I do get the idea the new size actually works, it's just not updating the display

**Steps to reproduce:**
Add a physics body with a BoxShape, turn "Visible Collission Shapes" on, and change the extents through code and see if the change is reflected in the interface when the project is run.

**Comment by GammaGames** [comment]
Oh, thankfully I'm not the only one. I was attempting to update a 3d capsule collision shape and it didn't look like it was updating visually but clearly the collisions were changing

**Comment by udit** [comment]
Using Godot 3.2 when I create a collision shape through script using `CollisionObject2D` APIs, the shape works but is not visible at all even with Visible Collision Shapes enabled. Is the issue related?

**Comment by Janglee123** [comment]
@udit I think it's a separate issue and please provide a demo project with the new issue.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Zylann** [comment]
I did the test in Godot 3.3.2

MRP:
1) Enable Visible Collision Shapes
2) Launch `main.tscn`: you should see the box shape in wireframe
3) Press Space: the shape should change size visually.
[VisibleCollisionShapeChanges.zip](https://github.com/godotengine/godot/files/6643225/VisibleCollisionShapeChanges.zip)

If this is the right repro, then the issue could be considered fixed.
