### ISSUE TITLE
Cannot animate a AudioStreamPlayer with the property "playing"

### ISSUE THREAD

**Issue by MatiasVME** [godotengine/godot#17309]
**Godot version:**
Godot Engine 3.0.2 Stable Official

**OS/device including version:**
KDE Neon

**Issue description:**
[Sorry my english is bad]
I can not animate a AudioStreamPlayer with the property "playing" with the editor. Not work with AudioStreamPlayer2D to.

**Steps to reproduce:**
I recorded a video: https://youtu.be/YX7P-dqHW8A

**Comment by ShyRed** [comment]
`playing` works in 2 different ways:

1. If you write a value to it, internally the `start` or `stop` method is called.
2. If you read a value from it, the **current playback status is returned**.

Now there are 2 consequences from that:

1. When you check `playing` you are not really setting a value, but in fact calling a method ( `start` ).
2. The editor is not monitoring properties for changes. So when playback ends, the editor does not know about it and still shows a checked checkbox when in fact the playback status is **false**.

In your example, the sample is very short. So when you activate the playing checkbox the sound plays and stops before you are able to save the key to the keyframe.  When you add the key, you are actually saving the value of the no-longer-playing sound, thus `false`.

You can try this for yourself: use a longer sound or music. As long as the sound is playing, you are able to save the correct key.

I'm not sure, if this is a bug, though. It's unfortunate that the editor is not detecting that the property has changed, but as far as I know, the editor is not meant to do monitoring? Even if the editor detected the change, you would still not be able to animate the sound properly as you just don't have enough time to add the key.

You can fix your problem / work around the issue by creating a script that wraps the actual playing property. See the attached project.

[audioanim.zip](https://github.com/godotengine/godot/files/1790534/audioanim.zip)

**Comment by MatiasVME** [comment]
thanks @ShyRed

**Comment by ShyRed** [comment]
You're welcome :smile:

Actually, I think that this **IS** a bug. The editor is displaying wrong information (showing a checked checkbox when the value behind the checkbox is `false`). It won't really fix the issue with having a time limit to get the key into the keyframe, but the editor should never show wrong information.

**Comment by ShyRed** [comment]
@MatiasVME Just did a pull request that does the same as the GDScript inside the Godot editor. If the pull request is accepted, you will no longer need to use the workaround. :smile:

**Comment by MatiasVME** [comment]
Great :+1:  Thanks you

**Comment by akien-mga** [comment]
Reopening as #17367 was only merged in the 3.0 branch, not master.

**Comment by KoBeWi** [comment]
Fixed in 3.1
The new Audio Track is used to animate the `play` property, but you can do it manually too and it stops properly and all.
