### ISSUE TITLE
Crash in rasterizer_canvas_gles3 due to memory corruption

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#17305]
**Godot version:**
Godot 3.0 stable

**OS/device including version:**
Android 5.0, Android 7.0, different devices, different GPUs (Mali and Adreno)

**Issue description:**
There is an intermittent crash at https://github.com/godotengine/godot/blob/3.0-stable/drivers/gles3/rasterizer_canvas_gles3.cpp#L215. The crash is `SIGSEGV 0x0000000000000097`, which means the first byte of `texture->render_target` address was set to 0x11 by some code (`used_in_frame` field has 0x86 offset, 0x97 is accessed), which makes the `if (texture->render_target)` check pass and the crash happen.

**Steps to reproduce:**
Reproduces rarely after invoking `change_scene` on a SceneTree with a large active tree.

**Comment by endragor** [comment]
Right after filing the issue I realized this doesn't actually matter for 3.1, as this is GLES3-specific :/ And this is likely very hard to track down.

**Comment by akien-mga** [comment]
> Right after filing the issue I realized this doesn't actually matter for 3.1, as this is GLES3-specific :/

Well GLES3 bugs should still be fixed in 3.1 too.

**Comment by endragor** [comment]
3D rendering in general does work on Android (with Godot 3.0 stable at least). There might be a problem specific to your project or device, so better file a separate issue with your project and other details attached.

**Comment by maxim-sheronov** [comment]
I have fired an issue #17770

**Comment by akien-mga** [comment]
Is it still reproducible in the current master branch? Does it also happen with GLES2, or only GLES3?

**Comment by akien-mga** [comment]
No answer, so assuming fixed. We can reopen if anyone can still reproduce it in recent builds.
