### ISSUE TITLE
Meshinstance Not Drawing vertices at correct location and a possible performance issue

### ISSUE THREAD

**Issue by Ron5s** [godotengine/godot#17307]
**Godot version:**
Godot 3.0.2 Mono Stable

**OS/device including version:**
Windows 10 and 7

**Issue description:**
I rewrote the 2D Linebuilder code in 3D using MeshInstance and C#.  It looks like it does not draw the vertices of the mesh in the correct location.  If this geometry is draw with ImmediateGeometry it is draw correctly.  The attached pictures show this.  The green circles show where the location of the vertices are located.  In addition  to this it appears that ImmediateGeometry has a pretty big performance hit.

**Steps to reproduce:**
MeshInstance Function Code:

``` C#
    public List<MeshInstance> Draw(List<Vector3[]> Features, List<Color> featureColor, List<string> featureName, SurfaceTool surfaceTool)
    {
        int i = 0;
        meshInstanceList.Clear();

        foreach (Vector3[] feature in Features)
        {
            SpatialMaterial material = new SpatialMaterial();
            material.AlbedoColor = featureColor[i];
            string name = featureName[i];
            i++;

            if (feature != null)
            {
                if (feature.Length > 2)
                {
                    MeshInstance meshInstance = new MeshInstance();
                    ArrayMesh arrayMesh = new ArrayMesh();
                    material.FlagsUnshaded = true;
                    material.SetCullMode(SpatialMaterial.CullMode.Disabled);
                    meshInstance.SetName(name);
                    meshInstance.SetMaterialOverride(material);
                    surfaceTool.Begin(Mesh.PrimitiveType.Triangles);

                    for (int j = 2; j < feature.Length; j = j + 3)
                    {
                        surfaceTool.AddVertex(feature[j - 2]);
                        surfaceTool.AddVertex(feature[j - 1]);
                        surfaceTool.AddVertex(feature[j]);
                    }
                    
                    surfaceTool.GenerateNormals();
                    surfaceTool.Index();
                    surfaceTool.Commit(arrayMesh);
                    meshInstance.SetMesh(arrayMesh);
                    meshInstanceList.Add(meshInstance);
                }
            }
            surfaceTool.Clear();
        }

        return meshInstanceList;
    }
```

ImmediateGeometry Code:

``` C#
    public List<ImmediateGeometry> Draw(List<Vector3[]> Features, List<Color> featureColor, List<string> featureName)
    {
        int i = 0;
        ImmediateGeometryList.Clear();

        foreach (Vector3[] feature in Features)
        {
            SpatialMaterial material = new SpatialMaterial();
            material.AlbedoColor = featureColor[i];
            material.FlagsUnshaded = true;
            material.SetCullMode(SpatialMaterial.CullMode.Disabled);
            string name = featureName[i];
            i++;

            if (feature != null)
            {
                if (feature.Length > 2)
                {
                    ImmediateGeometry immediateGeometry = new ImmediateGeometry();
                    immediateGeometry.Begin(Mesh.PrimitiveType.Triangles);
                    immediateGeometry.SetName(name);
                    immediateGeometry.SetMaterialOverride(material);

                    for (int j = 2; j < feature.Length; j = j + 3)
                    {
                        immediateGeometry.AddVertex(feature[j - 2]);
                        immediateGeometry.AddVertex(feature[j - 1]);
                        immediateGeometry.AddVertex(feature[j]);
                    }
                    ImmediateGeometryList.Add(immediateGeometry);
                    immediateGeometry.End();
                }
            }
        }
        return ImmediateGeometryList;
    }
```

![immediategeometry](https://user-images.githubusercontent.com/7084944/37043161-d063b38a-2114-11e8-8085-8b6fed923348.png)
![meshinstance](https://user-images.githubusercontent.com/7084944/37043162-d0836a0e-2114-11e8-8457-0452f07b1274.png)

**Comment by K9Kraken** [comment]
I am suffering from the same bug using SurfaceTool. The further you draw something from the position 0,0,0 the worse the distortion gets. I get the same distortion results using SurfaceTool's add_vertex function and the append_from function.
I tested by not using SurfaceTool and added the shape by instancing it and there is no distortion.

I am drawing a terrain using hexagons, around the 0,0,0 position the hexagons look normal.

This is what the hexagons look like when x position is around 600:
![godot_st_distortion_1](https://user-images.githubusercontent.com/37868357/38228102-e3d7dfee-36be-11e8-8f0c-c1eb670fb46b.png)


This is what the shapes are looking like when x position is around 800:
![godot_st_distortion_2](https://user-images.githubusercontent.com/37868357/38227945-f446d6ec-36bd-11e8-9cec-d99a92ff8220.png)

**Comment by K9Kraken** [comment]
Here is a scene that will draw shapes with ImmediateGeometry and SurfaceTool every frame while increasing the distance from position 0,0.

[bug.tscn.zip](https://github.com/godotengine/godot/files/1975592/bug.tscn.zip)

Shapes drawn with ImmediateGeometry have no issues drawing correctly.
Shapes drawn with SurfaceTool increasingly distort the further it is drawn from 0,0.


In this scene the top 3 shapes are drawn with ImmediateGeometry.
The bottom 3 shapes are drawn with SurfaceTool.
  
![1](https://user-images.githubusercontent.com/37868357/39647026-97aa3816-4f9a-11e8-80f2-37f4b516b6ca.png)
![2](https://user-images.githubusercontent.com/37868357/39647028-9a7ca72c-4f9a-11e8-997a-c0a1aa075b13.png)
![3](https://user-images.githubusercontent.com/37868357/39647033-9c465d14-4f9a-11e8-8334-e9065fb8ffd7.png)

**Comment by K9Kraken** [comment]
Did some testing and imported models in Godot suffer from this exact bug: https://github.com/godotengine/godot/issues/17820

**Comment by reduz** [comment]
This was fixed recently, It had to do with vertex compression to 16 bits being enabled by default. This was removed, so it should no longer happen.
