### ISSUE TITLE
Adding tracks/keys to an Animation Resource via code causes errors

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17313]
**Godot version:**
4f1b872

**Issue description:**
While trying to add tracks/keys to an `Animation` resource via code, this error gets printed multiple times:
```
0:00:01:0999 - Condition ' !data ' is true. returned: StringName()
----------
Type:Error
Description: 
Time: 0:00:01:0999
C Error: Condition ' !data ' is true. returned: StringName()
C Source: core/node_path.cpp:204
C Function: get_concatenated_subnames
```
But as far as I could find, they way I'm doing it is correct:
```
var animation = _animation_player.get_animation("animation")
var track_index = animation.add_track(Animation.TYPE_VALUE)
animation.track_insert_key(track_index, 0.0, var)
animation.track_set_key_value(track_index, 0, value)
```
So maybe, it could be something with Godot itself?

**EDIT:** Nope, you just have to use the `track_set_path` to define the path first. The help doc could really use a small example of setting it up.

**Comment by Zireael07** [comment]
Should probably be tagged as a documentation issue then?
