### ISSUE TITLE
[Godot 3.0.2 stable] Strange/Unexpected amount of significant digits of floating-point numbers in Godot

### ISSUE THREAD

**Issue by Foxcataria** [godotengine/godot#17312]
**Godot version:**
Godot 3.0.2 stable

**OS/device including version:**
Windows 8.1, 64 Bit

**Issue description:**
Godot represents floating-point numbers with 12 significant digits. 

When I try to compute `1.0/3.0` within GDScript and format the output to show 16 digits to check how many significant digits Godot uses to represent floating-point numbers then I get a really strange result. The output I get states that the result of the above calculation is `0.3333333333330000`.
This is not what I would except, neither in case of single precision floating-point numbers nor in case of double precision floating-point numbers.

According to the **IEEE Standard for Floating-Point Arithmetic** ( also known as **IEEE 754**) a float (32 bit single precision floating-point number) is able to represent ~7.2 decimal digits and a double (64 bit double precision floating-point number) is able to represent ~15.9 decimal digits. 

If I try the same computation in Java and C++ then I always get the following results:
`0.33333334` (in case of float)
`0.3333333333333333` (in case of double)
which is exactly what the **IEEE 754** standard states.

So Godot seems to not properly represent floating-point numbers in a way the **IEEE 754** standard states.

Here is the reference link to my original question in the Q&A section:
https://godotengine.org/qa/25147/strange-amount-significant-digits-floating-point-numbers

**Steps to reproduce:**
Create a new GDScript and insert the following code:
```
var result = 1.0/3.0
print("%.16f" % result)
```

**Comment by ShyRed** [comment]
The value is stored correctly inside the engine. Seems to be a problem with the print method.

![image](https://user-images.githubusercontent.com/1138805/37050422-211a066c-2174-11e8-8bdf-8ab08606ef74.png)

**Comment by ShyRed** [comment]
Ok, found the reason for the 12 digit precision:

https://github.com/godotengine/godot/blob/4f1b87265e1e74b1fdd0aa0aa59a9daf03fd3f40/core/ustring.cpp#L944-L950

@akien-mga Since you seem to have written that part: can we just set this to 15 (for double) as it is internally stored as a double?

**Comment by akien-mga** [comment]
> @akien-mga Since you seem to have written that part: can we just set this to 16 (for double) as it is internally stored as a double?

Actually I didn't, `git blame` only showed you that I modified this line to fit the style guide :)

It's been like this forever: https://github.com/godotengine/godot/blame/45438e9918d421b244bfd7776a30e67dc7f2d3e3/core/ustring.cpp#L917

**Comment by Foxcataria** [comment]
Tested with the suggested fix and now everything works as expected, thanks :)
