### ISSUE TITLE
Link to external folder causes infinite loop in FileSystem pane

### ISSUE THREAD

**Issue by pro-mole** [godotengine/godot#17323]
**Godot version:** 2.1.4

**OS/device including version:** Ubuntu Linux 4.11.0-14-generic

**Issue description:** If a link to an outside folder is included inside the Godot project folder, the FileSystem pane displays an infinitely looping tree.

![godot bug report - infinite recursion](https://user-images.githubusercontent.com/2591390/37070249-64464c54-2195-11e8-81ce-7912bd367822.png)

This is unexpected because the project folder is actually not contained inside the linked folder, so there should be no loop.

**Steps to reproduce:**
- Create a new Godot Project
- Create a folder in the same level as the Godot Project Folder (e.g. External)
- Create a symlink to the external folder inside the Godot Project Folder (e.g. ExternalLink)
- As Godot Engine updates the editor window, it will show more and more instances of the link folder
*(It may be necessary to make any change in the filesystem for Godot to read the link)*

**Minimal reproduction project:**

[GodotBug.zip](https://github.com/godotengine/godot/files/1787538/GodotBug.zip)

**Comment by Calinou** [comment]
@pro-mole Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
