### ISSUE TITLE
Changing single property-component in editor selection is not possible

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#17329]
**Godot version:**

Godot 2 and 3

**OS/device including version:**

Win 7 and probably all systems

**Issue description:**

Sometimes is needed to change one component of a property in a  MULTISELECTION of nodes (Ej Position.X  , Scale.Y, etc....). But in the moment that you press ENTER to store the new value, the "unmodified value" (other components of the property) are stored to, making your selection things like put all selected sprites in the same position of the canvas or scaling all to the same size, when your intention probably was alineate sprites, resize one side of multiple nodes to fixed number , etc.... 

This behavior does the editing of multiselection really not suited for properties with components.
Correct behavior should be not store "unmodified values", because it makes no sense: If the object is in Position(20,40) and you change it to Position(70,40) godot should only store Position.X, not the full vector.

Changing this behaviour will be an improvement to Animation Player too... because for now you only can store keys to full properties, and not to components, being this is a big problem for make things like curves, etc.... (but this is more complex to accomplish, i know)

**Steps to reproduce:**
Follow last pharagraph

**Comment by vnen** [comment]
You can actually press Shift+Enter, then only the changed axis will be updated in all nodes, the other left intact.

> Changing this behaviour will be an improvement to Animation Player too... because for now you only can store keys to full properties, and not to components

Not entirely true. The inspector doesn't help with that, but NodePath accepts subproperties. Doing a track with `Node2D:position:x` will work fine, changing only the X value of the position.

**Comment by Ranoller** [comment]
Ok, didn´t know all of this, thanks. It will be fine to have that in docs.

**Comment by Ranoller** [comment]
Well, with the new inspector and the separate members probably this will not need any kind of documentation. So closing. Thanks for the info.
