### ISSUE TITLE
Absolute scale in skeleton animation produce incorrect animation

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#17325]
**Godot version:**
Godot 3.1 build from 2f3c45f55eab7364ff0f6806c81ddc7ba861e1a2

**OS/device including version:**
Windows 10

**Issue description:**
Godot uses absolute scale in animation tracks, due this behavior all animation that use rotation + scale keys are imported incorrectly from Collada

I have created a simple animation in blender:
![2018-03-07_11-15-24](https://user-images.githubusercontent.com/3992195/37073516-f974c31e-21f9-11e8-83e6-740129559515.gif)

After export with "Better" collada exporter and import into Godot animation looks incorrect:
![2018-03-07_11-14-24](https://user-images.githubusercontent.com/3992195/37073517-fb3f9962-21f9-11e8-931b-1ffe7fb8f238.gif)

Zip contains blender and exported dae file.
[project-files.zip](https://github.com/godotengine/godot/files/1787762/project-files.zip)

**Comment by endragor** [comment]
This is likely not about editor/importing, but rather about animation system in general. Scale is supposed to be applied in the bone's local coordinate system, but instead it's applied in the global one. It seems there is no way to make scale properly work for a rotated bone. Or is there, @reduz? Can this issue be workarounded?

**Comment by kosz78** [comment]
Another possible reason is that godot use different order of transformation like rotate+scale instead of scale+rotate

**Comment by kubecz3k** [comment]
I think in 2.x we were using bone scaling, so this is a possible regression. Since 3.0 local coords are no longer used in armature animation... that's when I think the issue came out.
