### ISSUE TITLE
Itemlist expose move_item

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#17320]
At first I didnt see that there was already a move_item function so I wrote my own.

```
void ItemList::move(int from_idx, int to_idx) {
	
	ERR_FAIL_INDEX(from_idx, items.size());
	ERR_FAIL_INDEX(to_idx, items.size());

	Item item = items[from_idx];
	items.remove(from_idx);
	items.insert(to_idx, item);

	current = to_idx;

	update();
	shape_changed = true;
}
```
My solution works like I expect it, it moves the item and the selection is updated properly
```
var id = Itemlist..get_selected_items()[0]
Itemlist.move_item(id, id-1) # move up
Itemlist.move_item(id, id+1) # move down
```
![peek 2018-03-06 23-43](https://user-images.githubusercontent.com/4741886/37062942-2eefaae8-2198-11e8-8685-0582908cd04b.gif)

The function "move_item" currently not exposed to GDScript has a strange behavior.
![peek 2018-03-06 23-29](https://user-images.githubusercontent.com/4741886/37062417-aa8c3a1a-2196-11e8-84c0-ca138cf8c204.gif)

This line is missing and the move down code is not working
https://github.com/godotengine/godot/blob/d5daaa72fa94a6d7e122b6e1618dad90fe1d1065/scene/gui/item_list.cpp#L326
`shape_changed = true;`

Is there a way to enable "ensure_current_is_visible()"? I can't find a setting for it in the Inspector.

**Comment by ShyRed** [comment]
Did a quick search and it seems that the method `move_item` currently is not used anywhere at all. :smile:

I'd say go ahead and replace the existing method with your own, expose it and send in a pull request.
