### ISSUE TITLE
Error Running iOS 11 Simulator: EXC_BAD_ACCESS in map.h:524: find()

### ISSUE THREAD

**Issue by Shin-NiL** [godotengine/godot#17331]
**Godot version:**
3.0.2-stable

**OS/device including version:**
iOS 11 running on iPhone X simulator.

**Issue description:**
When running Godot on the iPhone X simulator the app crash and I got the following error:

`Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)`

the debug is pointing to the line 524 of map.h:
```
    const Element *find(const K &p_key) const {
 
        if (!_data._root) // Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
            return NULL;
 
        const Element *res = _find(p_key);
        return res;
    }

```

**Steps to reproduce:**
- Compile Godot for iOS 11 simulator using the following commands:
`scons p=iphone arch=x86_64 target=debug IPHONESDK="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/" -j3`
- Run any project using this template on iOS 11 simulator

**Additional notes:**
If I compile without using the IPHONESDK parameter it works fine, but I have issues with orientation as described [here](https://github.com/godotengine/godot/issues/11623#issuecomment-340642373).

**Comment by nguillot** [comment]
I reproduce the issue on the same condition, there is my stack trace:

![capture d ecran 2018-03-25 a 21 43 23](https://user-images.githubusercontent.com/1530644/37879233-afe4f9c8-3075-11e8-99d1-c1dbc641b995.png)
