### ISSUE TITLE
Editor tool in visual script 

### ISSUE THREAD

**Issue by lukaszbulzacki** [godotengine/godot#17338]
**Godot version:**
900384a622c7f3094540a43670421469e4ee0b06

**Issue description:**
Could not create visual script that is editor tool.
It could be done in gdscript or c# (http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#tool-mode)

**Comment by Jummit** [comment]
We need this so much. Tool scripts are extremely useful, and not having them for visual script is very annoying.

**Comment by swarnimarun** [comment]
@Jummit how do you think it should work? Most of the tool script code is very esoteric and requires lots of boilerplate should it just be a different variant entirely. Like hit the Tool editor mode and you will instantly be provided boilerplate?

**Comment by Jummit** [comment]
Just like it works in GDScript; make the script a tool mode script and it runs in the editor.

**Comment by swarnimarun** [comment]
@Jummit added a PR for it.
https://github.com/godotengine/godot/pull/30852
