### ISSUE TITLE
Rigidbody2d should allow the node to sleep in Character mode if "can_sleep" option is checked

### ISSUE THREAD

**Issue by exts** [godotengine/godot#17336]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
Currently it seems like the only way to stop a rigidbody2d from rotating when falling is to put it in 'Character' mode and that's fine, but the moment you put it into character mode the ability to sleep doesn't exist.  I found that this is normal in https://github.com/godotengine/godot/issues/7996

**What would you like to happen instead?**
I would love it if the ["can_sleep"](https://i.imgur.com/e0ZYX7o.png) option is set to true then in character mode the sleeping works how you would expect it to just without the rotation when gravity is involved.

**Comment by exts** [comment]
Or maybe add a new mode with this functionality?

**Comment by ShyRed** [comment]
You can prevent a RigidBody2D from rotating by implementing the `_integrate_forces ` method ( see http://docs.godotengine.org/en/3.0/classes/class_rigidbody2d.html#class-rigidbody2d-integrate-forces ) and setting the state parameter's `angular_velocity`  to zero and/or even set the transform's rotation to a constant value.

**Comment by exts** [comment]
@ShyRed closing for now. That alternative seems to work.
