### ISSUE TITLE
Base64 encode/decode member functions on String Type

### ISSUE THREAD

**Issue by Type1J** [godotengine/godot#17333]
Feature Request

Please add base64 encode and decode functions to the string type with a signature similar to the percent encode and decode functions:

```
	String percent_encode() const;
	String percent_decode() const;
```

**Comment by vnen** [comment]
You can already do base64 encode/decode with the Marshalls singleton.

**Comment by Type1J** [comment]
@vnen Thanks. Maybe this isn't necessary.
