### ISSUE TITLE
Area2D's monitorable property does not seem to work when being set back to true

### ISSUE THREAD

**Issue by stwupton** [godotengine/godot#17330]
**Godot version:**
3.0.2-stable

**OS/device including version:**
Windows 10

**Issue description:**
When switching an Area2D's monitorable property to false, and then back to true, it continues to act as if it's set to false.

![gd_monitorable_issue](https://user-images.githubusercontent.com/7224013/37085573-4ef29ada-21ed-11e8-89e0-31b78c63f63f.gif)

**Minimal reproduction**
[minimal.zip](https://github.com/godotengine/godot/files/1788638/minimal.zip)

The code is pretty much lifted from my actual project but in a simpler form.

Use the arrow keys to switch the disabled triggers (red) to enabled (blue). When one is enabled, all other triggers are set to disabled. When a trigger is enabled, the monitorable trigger is set to false and the opposite for the disabled triggers.

**Comment by NathanLovato** [comment]
Confirmed, facing the same issue here.

**Comment by AsixJin** [comment]
I can confirm that this is still an issue in the latest version. Has anyone found a workaround?

**Comment by Goutte** [comment]
I can confirm this with `3.0.6-stable` on linux and windows.

---

For those who do not want to download the zip, here's my own minimalist project that makes it easy to see the bug.

Just hit Right once, hit Space twice, move around. No signal is sent anymore.
You can re-enable the signal by messing around, but I could not find a sure way to do it. Looks kinda random.
Note that `monitoring` appears to work just fine, the issue is with `monitorable`.

### `Scene.gd`
```gdscript
extends Node

func _ready():
	$Area2D_A.connect('area_entered', self, 'on_area_a_entered')

func on_area_a_entered(area):
	prints('Area A entered', area)

func _input(event):	
	if event.is_action_pressed('ui_right'):
		$Area2D_A.position.x += 20
	if event.is_action_pressed('ui_left'):
		$Area2D_A.position.x -= 20
	if event.is_action_pressed('ui_accept'):
		$Area2D_B.monitorable = ! $Area2D_B.monitorable
		prints("$Area2D_B.monitorable", $Area2D_B.monitorable)
```

### `Scene.tscn`
```
[gd_scene load_steps=3 format=2]

[ext_resource path="res://Scene.gd" type="Script" id=1]

[sub_resource type="RectangleShape2D" id=1]

custom_solver_bias = 0.0
extents = Vector2( 10, 10 )

[node name="Node" type="Node" index="0"]

script = ExtResource( 1 )

[node name="Area2D_A" type="Area2D" parent="." index="0"]

position = Vector2( 507.05, 295.665 )
input_pickable = true
gravity_vec = Vector2( 0, 1 )
gravity = 98.0
linear_damp = 0.1
angular_damp = 1.0
audio_bus_override = false
audio_bus_name = "Master"

[node name="CollisionShape2D" type="CollisionShape2D" parent="Area2D_A" index="0"]

shape = SubResource( 1 )

[node name="Area2D_B" type="Area2D" parent="." index="1"]

position = Vector2( 543.095, 303.911 )
input_pickable = true
gravity_vec = Vector2( 0, 1 )
gravity = 98.0
linear_damp = 0.1
angular_damp = 1.0
audio_bus_override = false
audio_bus_name = "Master"

[node name="CollisionShape2D" type="CollisionShape2D" parent="Area2D_B" index="0"]

shape = SubResource( 1 )
```

**Comment by Goutte** [comment]
@AsixJin 
Another workaround is to procedurally remove/add the `Area2D` from/to the scene tree, but it may yield unwanted side effects (such as signals, `_ready`, etc.), and it is slow.
