### ISSUE TITLE
Godot 3.0 Error using varying

### ISSUE THREAD

**Issue by 0nepixel** [godotengine/godot#17349]
I try yo modify a vertex varying  from void fragment() and get this error (well is not an error i know) but the edito doesnt show any kind of errors or warning.

shader_type canvas_item;

varying float something;
void vertex() {
    something=2.0;}

void fragment() {
    something = 3.0;
COLOR = texture(TEXTURE,UV);
}

**Comment by hpvb** [comment]
What is the error/warning you are seeing?

**Comment by Zylann** [comment]
Are you allowed to assign the same varying both in vertex and fragment?

**Comment by Chaosus** [comment]
I closed it because it now gives you clear error  

![image](https://user-images.githubusercontent.com/3036176/44334444-319ae400-a47a-11e8-9ef0-89b46ccacaf6.png)

I also looked into GLSL ref and found that its impossible to fix because its designed at driver/compiler-level.
