### ISSUE TITLE
Crash when create C# script

### ISSUE THREAD

**Issue by MagicIsArt** [godotengine/godot#17356]
I'am download Godot_v3.0.2-stable_mono_win64 (released Mar 4, 2018).
When I create C# script GotDot crashed.
![img](https://user-images.githubusercontent.com/20385368/37127564-6594bc88-2287-11e8-91ec-5eb8fab9f032.png)

**Comment by bojidar-bg** [comment]
Looks like a duplicate of #17278.
Are you sure you have the correct Mono version? We currently support 5.4.x, but the newest is 5.10.

**Comment by MagicIsArt** [comment]
I use mono 5.10. After reinstall, all ok. Thank.
