### ISSUE TITLE
Joystick buttons closing or restart game

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#17355]
Hi there,

In project Input joystick is mapped to axis directions axis and button R1.
When i press down A joystick button it closes the game, if i press B button joystick it restarts the game.
Why those work when they are not mapped ?

**Comment by vonflyhighace2** [comment]
there are a number of reason this could be. Are you running the project from the startup project list manager? thats a known issue.

**Comment by akien-mga** [comment]
Duplicate of #15199.
