### ISSUE TITLE
PopupMenu error when opening a scene

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17351]
Godot 3.0.2 stable
Windows 10 64 bits

I get these two errors when I load a scene:
```
ERROR: PopupMenu::get_item_text: Index p_idx=-1163005939 out of size (items.size()=4)
   At: scene\gui\popup_menu.cpp:732
ERROR: PopupMenu::set_item_checked: Index p_idx=-1163005939 out of size (items.size()=4)
   At: scene\gui\popup_menu.cpp:680
```
I just opened the editor and clicked on the scene to load it.
The scene is not complicated, just this:

![image](https://user-images.githubusercontent.com/1311555/37120636-3a15c9a2-225b-11e8-9e2e-9ac2c5b54382.png)

Here is the call stack:
![image](https://user-images.githubusercontent.com/1311555/37120552-0bd97c1e-225b-11e8-8a54-57295c0d45ee.png)

Apparently, the TextureRegionEditorPlugin tries to restore a state out of bounds of its snap modes:
```cpp
	if (state.has("snap_mode")) {
		region_editor->_set_snap_mode(state["snap_mode"]);
	}
```
```cpp
void TextureRegionEditor::_set_snap_mode(int p_mode) {
	snap_mode_button->get_popup()->set_item_checked(snap_mode, false);
	snap_mode = p_mode;
	snap_mode_button->set_text(snap_mode_button->get_popup()->get_item_text(p_mode));
```
But the index is just garbage:
![image](https://user-images.githubusercontent.com/1311555/37120791-a85a3038-225b-11e8-8ff4-210afbb1e760.png)

**Comment by Zylann** [comment]
Hmm turns out my `test.tscn-editstate` contained that value: 
```
TextureRegion={
"snap_mode": -1163005939,
"snap_offset": Vector2( 0, 0 ),
"snap_separation": Vector2( 0, 0 ),
"snap_step": Vector2( 10, 10 ),
"zoom": 1.0
}
```
Deleting the file got rid of the issue...
However, I created that scene only yesterday, which means Godot wrote garbage at some point.

**Comment by reduz** [comment]
I Can't reproduce this any longer, and probably because @MarianoGnu rewrote the region editor..
