### ISSUE TITLE
Godot application crashes on Mac OS.

### ISSUE THREAD

**Issue by felixwcf** [godotengine/godot#17361]
**Godot version:**
v3.0.2_Stable_mono_osx64

**OS/device including version:**
Macbook Pro 2016 i7 16Gb Ram, High Sierra, latest version 10.13.3 at March 2018. 

**Issue description:**
No bug report prompt out.

**Steps to reproduce:**
Download the latest version of godot osx64, copy into Application folder, launch and crash.

**Minimal reproduction project:**
In my Macbook I also have related softwares like Unity 2017 (Bundled with mono), Android Studio, Xcode, Webstorm to build pixi slot games.

**Comment by akien-mga** [comment]
Do you have the Mono SDK installed in version 5.4.1.7?

Can you run Godot from the command line and paste the output?

**Comment by mhilbrunner** [comment]
Closing due to missing information. Please ping me to reopen this if the issues still exists and provide the information above.
