### ISSUE TITLE
TextureRect swallows Inputs for CollisionObject

### ISSUE THREAD

**Issue by Maxpilot** [godotengine/godot#17362]
Godot version: 3.02

Windows 10

An "InputEventScreenTouch" with "is_pressed = true" is not received when TextureRect is present in the scene. What makes me think this is a bug is the fact, that in the same environment the "InputEventScreenTouch" with "is_pressed = false" is received.

To reproduce run the enclosed example. Only the "TouchUps" are received. Delete the textureRect - Node and run again. This time "TouchDown" and "TouchUp" are received (as printed out in the console).

Run example:
[example.zip](https://github.com/godotengine/godot/files/1793063/example.zip)

**Comment by Maxpilot** [comment]
Hmm - ok, I have to put

func _ready():
   set_mouse_filter(TextureRect.MOUSE_FILTER_IGNORE)

in the TextureRect. Anyway I don't quite get it.

**Comment by eon-s** [comment]
You can set that property in the inspector too, by default some Controls consume mouse inputs and they get it before CollisionObjects.

Read here for more details http://docs.godotengine.org/en/3.0/tutorials/inputs/inputevent.html

**Comment by Maxpilot** [comment]
Thanks for answer. I just missed that Controls consume touch Inputs as well and missunderstood the concept of "accept_event()", which is I guess for non-mouse-events. A little bit puzzled though why "TouchUp" gets through.
