### ISSUE TITLE
Radial TextureProgress angles incorrect for angles less than 45°

### ISSUE THREAD

**Issue by OneginIII** [godotengine/godot#17364]
**Godot version:**
Godot v3.0.2.stable.official

**OS version:**
Win 10 64-bit

**Issue description:**
When I tried to use TextureProgress for precise angles I noticed this bug. I think angles between 45 degree increments are somehow incorrectly calculated.

**Steps to reproduce:**
Simply use an angle less than 45 for TextureProgress clockwise or counter-clockwise mode like 22.5 (half of 45)

**Demonstration:**
https://gfycat.com/AnxiousClumsyHalicore
The black lines in this example show where the red ring should end if the angles were correct.

**Comment by Zylann** [comment]
I was able to reproduce it too:
[RadialProgress.zip](https://github.com/godotengine/godot/files/1793383/RadialProgress.zip)

I believe it's because trigonometry is not used here, and the rectangular sides are used linearly instead of projecting the angle.
