### ISSUE TITLE
get_slide_collision not consistently returning the collision

### ISSUE THREAD

**Issue by luizcarlos1405** [godotengine/godot#17375]
**Godot version:**
3.0.2 stable

**OS/device including version:**
Linux Ubuntu 16.04 LTS

**Issue description:**
When just jumping get_slide_collision returns null, but when multiple jumping it returns normally.

![get_slide_collision_issue](https://user-images.githubusercontent.com/15899938/37209963-62722f1c-237d-11e8-8cec-849ccc08d06b.gif)

It's just a KinematicBody2D with the following script:

```
extends KinematicBody2D

var speed = Vector2()
var gravity = Vector2(0, 1500)

func _physics_process(delta):
	speed += gravity * delta
	
	if Input.is_action_just_pressed("ui_up"):
		speed = Vector2(0, -600)
	
	var rem = move_and_slide(speed, Vector2(0, -1))
	var col = get_slide_collision(0)
	
	speed = rem
	
	if col :
		print("col")
```

And the floor is just another KinematicBody2D. It returns the collision depending on the speed (I was able to make it detect or not the first falling collision by changing the gravity, when 2000 it detects, 3000 it doesn't and 4000 it does again).

**Minimal reproduction project:**
[get_slide_collision_issue.zip](https://github.com/godotengine/godot/files/1797045/get_slide_collision_issue.zip)

**Comment by mjf-89** [comment]
I was running into the same issue and I think that it relates to the slope_stop_min_velocity parameter, indeed setting it to 0 in the sample code posted by @luizcarlos1405 you got the desired behavior.

Take a look at the following code:

https://github.com/godotengine/godot/blob/8ac39d886307d76c286e804e027fc39f6b5aaac6/scene/2d/physics_body_2d.cpp#L1045-L1053

If the module of the horizontal velocity hv is less than slope_stop_min_velocity the kinematic body is stopped immediately and the function returns without adding the collision to the colliders vector. I'm not 100% sure but I think that simply adding `colliders.push_back(collision);` before the return statement should fix the issue.

**Comment by reduz** [comment]
I fixed this some weeks ago, in fact test project seems to work. Closing.

**Comment by vlad94568** [comment]
How do i check what collided with it.
