### ISSUE TITLE
Bug GridContainer when change columns property

### ISSUE THREAD

**Issue by MatiasVME** [godotengine/godot#17389]
**Godot version:**
3.0.2 Stable, Official

**OS/device including version:**
Linux, KDENeon

**Issue description:**
[Sorry for my english xd]
When change columns in my GridContainer the editor it freezes

**Evidence:**
You can see the bug here: https://youtu.be/x072q4W8ia0

**Minimal reproduction project:**
[Bug.zip](https://github.com/godotengine/godot/files/1798648/Bug.zip)
For reproduce only change in GridContainer the property "Columns" to 4

Only I tested in my PC I don't know if the same thing will happen in another.

**Comment by bojidar-bg** [comment]
Problem comes from
https://github.com/godotengine/godot/blob/38623e07acb5addbd47b046d7734510d4e074156/scene/gui/grid_container.cpp#L91-L109

It causes an infinite cycle, in which remaining_space.width becomes negative (I stopped it around -2101692420)

Ping @groud

**Comment by bojidar-bg** [comment]
@MatiasVME BTW, for a workaround, you can make the area which the grid can expand to bigger.

**Comment by groud** [comment]
I found the problem, I'm currently fixing it.
