### ISSUE TITLE
Plugin custom resource types are not appearing in property resource menu

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17395]
Godot 3.0.2

I have a plugin that registers a custom resource type, but I have no idea how to make a property `export`ing it. So I tried `export(Resource)` instead, which gave me a huuuuuge menu which is too big to fit on screen (it scrolls though).
But more importantly, my custom resource type **doesn't appear on that list**.

![image](https://user-images.githubusercontent.com/1311555/37237756-7e1ed0da-2418-11e8-957f-c354015a7f64.png)

It does appear only if I click "New resource" in the inspector, which opens a different window.

Repro steps:
1) Have a plugin register a custom resource type
2) Have a script with a property `export(Resource)` on a node
3) Click on that property, see the huge menu and absence of custom type

Turns out https://github.com/godotengine/godot/pull/16995 would fix this

**Comment by vnen** [comment]
Related: #6763
