### ISSUE TITLE
GDScript errors are not reported for non-tool scripts loaded by tool scripts

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17394]
Godot 3.0.2 stable, Godot 2.x too I believe

I thought an issue existed already, but I was unable to find it.

I have a tool script which preloads an utility script:

```gdscript
tool
const Util = preload("util.gd")
```

But for some reason the tool script failed to execute, telling me that `Util` doesn't contain function xxx in base `GDScript`.
Turns out, it was because `util.gd` had a GDScript parsing error, but it wasn't reported explicitely. Adding `tool` on top of `util.gd` made the error show up.

As a result, I am adding `tool` in scripts that didn't need it (not really)...

**Comment by Calinou** [comment]
@Zylann Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Zylann** [comment]
I wish I had written the kind of parsing error `util.gd` had, but the problem seems to be fixed.

**Comment by Calinou** [comment]
@Zylann Thanks for replying :slightly_smiling_face: I'll close this then.
