### ISSUE TITLE
If a scene is instanced multiple times, you can't get each individual instance

### ISSUE THREAD

**Issue by LockManipulator** [godotengine/godot#17392]
**Godot version:**
3.0

**OS/device including version:**
Windows 10

**Issue description:**
Goal: Instance a button several times and free all but the one that gets clicked.

I instanced a button, which gives a signal when clicked, multiple times. The button scene looks like this:

```
Control
    TextureButton
    Label
```

Connecting that signal only works once and all the other times gives the error "Signal is already connected to given method". If I look at the debugger to see which button I'm pressing, the first button instanced is called "Control" and the rest are "@Control@number" with "number" being a number starting at a random number and going up by 1 for each new instance. I instance it like this:

onready var button_var = preload("res://Button.tscn")

```
for item in list_of_strings:
    var button = button_var.instance()
    var button_label = button.get_node("Label")
    button_label.text = item
    $ScrollContainer/VBoxContainer.add_child(button)
    button.connect("signal_emitted", self, "function_todo")
```

So here there a bunch of buttons with different labels on them. But the signal only gets emitted when the first button is clicked and not any of the others. There seems to be no way to 1. Connect the signal from all the instanced buttons and 2. Get the name of one specific instance so that all the rest can be freed except that one.

**Steps to reproduce:**
Instance something multiple times and try to isolate one.

**Comment by Hinsbart** [comment]
Can you provide a minimal reproduction project? It's not quite clear what you're trying to achieve here.
Anyway, there seem to be a few things wrong with that code:
1. You always pass the same path to the `get_node()` call, hence the "Signal is already connected to given method" error -> you're always getting the same node.
2. You're trying to `get_node()` the buttons before they're actually added to the SceneTree with `add_child()`

Instead of trying to get the nodes by name, can't you just use `button.connect()`?

**Comment by LockManipulator** [comment]
I'm not sure how to upload one, is there a button to upload files here? I added in your fixes as an edit to my post, #2 was just a type on my part in the posting of this issue. But to address what you said in #1: "You always pass the same path". Is there a way to pass in a different path? 

>  It's not quite clear what you're trying to achieve here

Instance a button multiple times, as in my for loop, and when 1 of those buttons is clicked, de-instance all the buttons except the one that is clicked.

**Comment by LockManipulator** [comment]
I made a test project and uploaded it to dropbox: https://www.dropbox.com/s/ps5u1hzkrpbf8n1/Test.zip?dl=0 in the function when_clicked() I want all buttons except the one that was clicked, to be freed.

**Comment by PetePete1984** [comment]
You can give the connection extra parameters, which must then of course be present as arguments of your response function. This is the easiest way to pass the specific signal emitter to the responder, in my experience:
```swift
func showemails():
	i = 0
	for item in list_of_strings:
		var button = normal_button.instance()
		var button_label = button.get_node("Label")
		button_label.text = item
		$VBoxContainer.add_child(button)
		button.connect("was_clicked", self, "when_clicked", [button])
	var emptybutton = empty_button.instance()
	$VBoxContainer.add_child(emptybutton)

func when_clicked(who): #I want this to free all buttons except the one that was clicked
	for child in $VBoxContainer.get_children():
		if child != who:
			child.hide()
			child.queue_free()
	pass
```

**Comment by Zylann** [comment]
@LockManipulator hint: you can drag and drop a zip file to Github, same for images etc ;)

**Comment by LockManipulator** [comment]
@PetePete1984 Oh wow I never new you could do that! Thank you, that fixed the issue.

@Zylann Ah, thanks. I haven't ever uploaded anything to github before xD

**Comment by Kunall18** [comment]
what should i do
 for item in list_of_strings this is giving me an error in godot
![Screenshot (2)](https://user-images.githubusercontent.com/62152174/76643003-7cbf9080-6511-11ea-8435-022c9461fd43.png)

**Comment by Zylann** [comment]
@Kunall18 read the error, it says there is no `strings` variable in your script. Maybe it has another name, or maybe you need to obtain that list first.

**Comment by akien-mga** [comment]
And fix that infinite loop, but it has nothing to do with this old issue closed in 2018, and this issue tracker is not the place to ask for support.

**Comment by Kunall18** [comment]
@Zylann or @akien-mga 
actually i m making a game prototype in which i want to instance object scene in  infinite loop on main 
scene but after then i want that whenever someone clicks on  particular instance it get queue_ free()
but every instance getting queue_free() so please tell me how to do it.
thanks
