### ISSUE TITLE
Go to Everything Shortcut

### ISSUE THREAD

**Issue by justinluk** [godotengine/godot#17393]
**Godot version:**
3.0.2 Stable

**OS/device including version:**
Windows 10

**Issue description:**
It would be SUPER handy to have a Go To Everything shortcut, that pops open a window and let's you start typing in a file/class/resource and presents a list of matching files. From there you can select a file and it will open it in the editor.

This is similar behaviour to what programs like Resharper or Sublime Text.

https://www.jetbrains.com/help/resharper/Navigation_and_Search__Go_to_Type.html

**Comment by Zylann** [comment]
There is Ctrl+Alt+O which opens a fuzzy search for scripts.
There is also Ctrl+Shift+O which does the same for scenes.

**Comment by justinluk** [comment]
Ah thanks @Zylann - disregard this then :P
