### ISSUE TITLE
"Error saving resource": OK button not working

### ISSUE THREAD

**Issue by Phoenix1747** [godotengine/godot#17403]
**Godot version:**

v3.0.2-stable official build

**OS/device including version:**

Manjaro Linux, latest

**Issue description:**

Saving an edited resource shows a message window, which is correct in some cases. The window just says `Error saving resource!`.
However, the real problem now occurs if I click on the only available button which is `OK`, it keeps reappearing instantly. The solution is that it has to be closed with the cancel (cross) button in the top right corner of the window.

**Steps to reproduce:**
When opening e.g. a PNG file in Godot's inspector window you can have a look and change some import settings so far so good, but if you then click on `Save the currently edited resource.` ... `Save` the alert window pops up.

**Minimal reproduction project:**

/

**Comment by maxdeviant** [comment]
Seeing this on Windows 10 as well.
