### ISSUE TITLE
Scene window with nodes and the inspector disappears after adding animation

### ISSUE THREAD

**Issue by ILope92** [godotengine/godot#17412]
The window with scenes and properties disappears after the animation is added. The version of the engine is stable. I work in Windows 10, x86. What it is necessary to make that this window appeared or simply did not disappear? What it is necessary to make that this window appeared or simply did not disappear? At others, everything works well, and nothing disappears. 
Are there any hotkeys to open the Inspector, scene for adding nodes?

P.S. While saving the animation scene, after restarting Godot, I'm trying to add a scene with animation and nothing comes out, because Godot can not load, and immediately closes without showing an error. Sometimes it simply saves Area2D without animation, and other nodes. Ie Area2D is empty.

Disappeared window:
![default](https://user-images.githubusercontent.com/31201817/37089640-55fe30a8-2212-11e8-8c9b-0720479507ea.png)

Expected Result (Example):
![default](https://user-images.githubusercontent.com/31201817/37090222-8aff7328-2214-11e8-8398-e3e9dfef6dd2.png)

**Comment by eon-s** [comment]
I have seen this on master too using linux but I was unable to identify when it happened, is a similar effect as the one done by Tilemap on 2.1 series. 

In this case, the central panels get expanded and is impossible to recover the right docks even by window resize (I put all my docks on the left as workaround), to see all again the editor needs to be restarted.

**Comment by akien-mga** [comment]
Fixed by #18259.
