### ISSUE TITLE
x86_64 iOS template crashes in simulator

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#17428]
**Godot version:**

3.0

**OS/device including version:**

**Issue description:**

exported iOS project can not test on simulator.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by endragor** [comment]
All that needs to be done here is to include `x86_64` as a platform into export template build scripts.

**Comment by alexzheng** [comment]
I mean the lib compiled by the following command crash when run on the simulator
scons p=iphone tools=no  arch=x86_64 target=debug

**Comment by akien-mga** [comment]
> All that needs to be done here is to include x86_64 as a platform into export template build scripts.

Actually there is x86_64 support in the `platform/iphone/detect.py` already, so it should work. But the resulting binary seems non functional according to @alexzheng.

**Comment by alexzheng** [comment]
Any exported project just crashed here when running in the simulator.

int OSIPhone::get_unused_joy_id() {
	return input->get_unused_joy_id();
};

**Comment by endragor** [comment]
Ah, right, I fixed this locally few days ago. Will create a PR soon with this and a bunch of other iOS-related fixes.

**Comment by alexzheng** [comment]
Will it be possible to make the default static lib file in the template project support both the devices and simulator. It would make test much easier without compiling custom lib.

**Comment by Shin-NiL** [comment]
Same as here: #17331
