### ISSUE TITLE
Option to disable the Boot Splash for specific platform

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#17427]
**Godot version:**

3.0

**OS/device including version:**

iOS

**Issue description:**

For iOS App, there is already a splash screen in the Xcode project, it would be better to have an option to disable the  Boot Splash in the project settings.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by char0xff** [comment]
Related: #6057

**Comment by akien-mga** [comment]
You can already define per-platform overrides for any properties, including the boot splash image:
![screenshot_20180917_104426](https://user-images.githubusercontent.com/4701338/45613441-a60b7780-ba66-11e8-8239-998abeb4adab.png)

Thus you can set a black image (even 2x2 px) as described in #4642 on those platforms - at least until #4642 is fixed.
