### ISSUE TITLE
CrashHandlerException: Program crashed with largish scene trees (>2500 Nodes)

### ISSUE THREAD

**Issue by bmadgett** [godotengine/godot#17424]
**Godot version:**

3.0.2 Mono

**OS/device including version:**

Win10 64bit, Intel 3570K, NVidia 1080, latest drivers 391.01

**Issue description:**

I'm having crashes with large scene trees under Win10-64 with 3.0.2 Mono. Once I have over ~2500 Nodes in my tree (~50% of which are `MeshInstance` children under plain `Node`s) then I will start getting `CrashHandlerException: Program crashed` from the engine, with no helpful stack trace given, and a Windows exception. I've also occasionally had a video driver failure & restart occur at the same time, which indicates to me it must be something deep in the guts of the rendering engine?

Most of my code is C#, and I do use Threads (one Thread, to service a queue for building landscape chunks). However this issue occurs even when I remove all Threading (just doing the chunk building synchronously in the main thread) so it's not that causing the crashing. If I cut down the number of Nodes, by reducing draw distance or increasing land chunk size (meaning fewer Nodes for the same draw distance, with larger meshes for each Node) then the crash disappears, but neither of those is desirable and I'm assuming there's no design limit reason why it shouldn't work with many Nodes.

It doesn't crash on exactly the same number of Nodes each time, and sometimes will run for a minute or two before crashing, so it's a not 100% reliably reproduced each time, but will definitely occur within minutes once I exceed roughly 2500 Nodes in the scene.

How do I go about getting more useful info on what's causing the crash? Is there a way to get the Godot engine to give a stack trace when it crashes in this way so I can narrow down where it's coming from? I've seen unofficial builds that supposedly include stack trace, but they don't seem to be Mono builds?

I've spotted issue #17305, does this sound plausibly the same issue?

**Steps to reproduce:**

**Minimal reproduction project:**

I don't have a simple project available to replicate - I'm looking for advice first to narrow the issue down or identify as a duplicate of a known issue.

**Comment by vnen** [comment]
Maybe it's because of #8279

**Comment by bmadgett** [comment]
Perhaps, but the memory in use when it crashes (looking at the Monitor->Static Max) has only grown to around 70-80Mb with ~2500 Nodes. Unless I'm looking at the wrong measure?

What I'd really like is a way to get a proper stack trace out of the engine when it crashes, so it gave me more of a clue whereabouts the issue is lying and thus which issue it is related to (or if it's a new one I'm hitting). Currently no amount of console prints are helping me narrow it down, and if I attach to the crash with the VS debugger it just hops into the Exception handling stuff with no back stack trace. Though I'll be the first to admit I don't really know what I'm doing with the debuggers.

**Comment by qarmin** [comment]
I never had a problem with such big project ~4000 objects, ~1000 resources ~2000 nodes.
Can you post here a project, to be able to reproduce issue?

**Comment by qarmin** [comment]
Closing, because there is no response from author since 2 years, and there is no minimal project to test issue.
