### ISSUE TITLE
In the editor, Texture Region window for Sprite does not pan or zoom properly GLES2

### ISSUE THREAD

**Issue by ryerrappa** [godotengine/godot#17429]
**Godot version:**
v3.0.2 -master experimental build with GLES2 support

sorry not sure where the git for it is, got build from here:
https://www.reddit.com/r/godot/comments/8332ht/new_experimental_builds_of_godot_git_master_30/

**OS/device including version:**
Windows 10 64 bit
Intel HD Graphics 3000

**Issue description:**
When using the texture region option for a Sprite Node, in the texture region window, panning and zooming does not work as intended only when using GLES2 renderer.

Expected Behavior vs Actual Behavior:
https://imgur.com/a/pF6Vu
(if Imgur is acting up, right click on each and click view video)

**Steps to reproduce:**
1. Create a project and open with godot editor using --video-driver GLES2 switch
2. Add a scene with Sprite Node
3. set Texture as anything (use godot icon for ease)
4. enable Texture Region and open the texture region tab/window
5. Enable grid snap and grid visibility
6. Try panning or zooming, only the grid updates leading to strange behavior.

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/1800116/test.zip)

**Comment by volzhs** [comment]
can't reproduce it with 7f9209781

**Comment by akien-mga** [comment]
Thanks, assuming fixed then. Please comment if you can still reproduce the issue in the current master branch.
