### ISSUE TITLE
Set function sometimes get called twice on load

### ISSUE THREAD

**Issue by DualMatrix** [godotengine/godot#17436]
**Godot version:**

3.0

**Issue description:**

When an export var has a different value from its default and its in an instanced scene then its set function will get called twice, once for the default, and one for the given value. It won't get called twice if the the given value is equal to the default, it also won't be called twice if it isn't an instanced scene. If a value is given the setter really shouldn't be called with the default.

**Steps to reproduce:**

Make a node and attach a simple script:

```
export var value = true setget setter

func setter(val):
    value = val
    print(val)
```

If you instance this scene and passing true to value this will be printed on load:

```
False
True
```
If you don't give a value only:

`False`

Is printed

**Comment by Noshyaar** [comment]
Still relevant in master 8bf5b50

**Comment by allkhor** [comment]
Also reproduced in 2.1 d1869b3

**Comment by reduz** [comment]
This is by design and not a bug. The scene from the instance is loaded first, and then it gets patched with whathever it changes. Making this work as you expect it would be an insane amount of work and complexity for pretty much no benefit.

**Comment by reduz** [comment]
Maybe it should be documented somehow? is it worth it?

**Comment by oxeron** [comment]
Hello @reduz Is it still relevant for Godot 4.2.2 ? I did not find any information on this subject inside the documentation
