### ISSUE TITLE
Light2d occasionally drops shadow resolution when different buffer sizes overlap

### ISSUE THREAD

**Issue by Cybolic** [godotengine/godot#1743]
Having several lights in the same scene with different buffer sizes can trigger this (e.g. low buffer size for mood lights, hight buffer size for "actor" lights).
Moving the editor view over tile quadrant edges seem to also trigger it, but that might be unrelated or due to culling.

https://www.youtube.com/watch?v=GWLItyLemRU

This is the same in runtime as in the editor and is present in

**Comment by reduz** [comment]
yes this will be fixed in 1.2 o 1.3, shadow code needs a rewrite

**Comment by akien-mga** [comment]
As I understand it, this stuff will likely be reworked for 3.0.

**Comment by reduz** [comment]
this was rewritten and should no longer happen
