### ISSUE TITLE
ScriptEditor: Ctrl+left mouse click on a filepath surrounded by single quotes doesn't open the resource

### ISSUE THREAD

**Issue by Deluvi** [godotengine/godot#17437]
**Godot version:**
eceba5aa6a36521c878cf976845123e820d27161

**OS/device including version:**
Windows 10 x64

**Issue description:**
In the editor, when CTRL+Left mouse click on a resource path surrounded by simple quotes, the click doesn't open the resource. The same resource path surrounded by double quotes does open the resource.

**Steps to reproduce:**
1. Open the script editor in a new project.
2. Write 'res://icon.png' and try to CTRL+Left mouse click on it. Note that the file doesn't open in the inspector.
3. Write on a new line "res://icon.png" and try to CTRL+Left mouse click on it. Note that the file opens in the inspector.

**Minimal reproduction project:**
[CTRL_LEFT_CLICK_SINGLEQUOTE.zip](https://github.com/godotengine/godot/files/1800408/CTRL_LEFT_CLICK_SINGLEQUOTE.zip)

**Comment by Zylann** [comment]
I think I saw this issue posted already but cant find it from py phone rn
