### ISSUE TITLE
16-bit greyscale, bitmap etc image loading/saving

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17450]
I am making a terrain system which requires a bit unusual image formats, such as 16-bit greyscale (mono channel), 8-bit RGB without alpha, or bitmaps (1 bit per pixel). I am currently loading and saving this data manually using my own format, but I figured out it would be interesting if Godot could support these formats out of the box, available in API. (so it could load PNG or EXR directly in the expected format without having to convert manually). The `Image` resource has them all, it's only a matter of getting them loaded (not only as a feature of the editor, but ingame too).

I emphasize the fact channel count and pixel depth must really be in these formats in the saved resource and once loaded (not just picking a common RGBA image and only using R for example), because terrains deal with a very large amount of data so it has a significant impact on memory.

**Comment by fire** [comment]
The openexr format is in 16 floats per channel, but the format itself supports 32bit floats per channel.
