### ISSUE TITLE
[Mono] Exported Project Is Very Slow

### ISSUE THREAD

**Issue by TritiatedWater** [godotengine/godot#17466]
**Godot version:**
#17417

**OS/device including version:**
Manjaro Linux. AMD RX480 AMDGPU.

**Issue description:**
I made a (sort of) benchmark. It drops balls and calculates  0.1 low fps, average fps, and time frame. The exported project is very slow compared to running in the editor. I used GDScript and C#, but still it's stuttering. I used the debug export templates as well as the debug-mono.

Note: I have no Idea how accurate the results are, but it gives a good picture.

**Steps to reproduce:**
Export project and run.

**Minimal reproduction project:**

[Bouncing Ball](https://github.com/Supatier/godot_ball_bench)

**Comment by Calinou** [comment]
Have you compiled export templates from source? The editor version and the export templates version must match exactly, otherwise you are likely to run into issues.

**Comment by Supatier** [comment]
> Have you compiled export templates from source if you compiled the editor from source?

Yes I did.

**Comment by akien-mga** [comment]
How do you compile the editor and the templates?

**Comment by Supatier** [comment]
For the editor ``scons platform=x11 bits=64 -j7 CXX=clang++``
For the export templates ``scons platform=x11 tools=no target=release_debug bits=64 -j7 CXX=clang++``
I used Clang 5.0.1as it's compiling faster than GCC 7.

It works properly on godot 3.0.2 from steam. I'm going to try compiling with GCC.

**Comment by Supatier** [comment]
After further testing, it only applies to mono builds. Other than that, it works perfictly.

**Comment by Calinou** [comment]
@TritiatedWater Can you still reproduce this in Godot 3.2.1 or [3.2.2beta3](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-3)?

**Comment by TritiatedWater** [comment]
it seems to be fixed.
