### ISSUE TITLE
Unable to install VR app on Android Device

### ISSUE THREAD

**Issue by Paritosh97** [godotengine/godot#17462]
**Godot version:**
Godot_v3.0.2-stable_win64

**OS/device including version:**
PC : 
OS : Windows 10 64b version 1709(OS Build 16299.248)
Video device : Nvidia Quadro 2000M

Mobile Devices : 
Lenovo ZUK Z1 : Snapdragon 801, Adreno 330, Android 8.1
Samsung Galaxy S7 SM-G930P : Snapdragon 820, Adreno 520, Android 7.0

**Issue description:**
The android builds of "Native mobile" generate parse errors on installation.

**Steps to reproduce:**
Happens every time.

**Minimal reproduction project:**
[VR-1.zip](https://github.com/godotengine/godot/files/1801008/VR-1.zip)

**Comment by BastiaanOlij** [comment]
Hey @Paritosh97 , 

What are the parse errors you are getting? 

Also can you deploy a non-VR game to your phone or does it only happen when using the mobile VR driver?

One of my other friends was having issues on his phone as well but he couldn't deploy any android app due to the GPU being used.

**Comment by Paritosh97** [comment]
@BastiaanOlij 
There wasn't any package parsing error when deploying a non-VR project.
![error](https://user-images.githubusercontent.com/17229161/37260823-4dafe51e-25bd-11e8-9df8-850aa3b6e542.png)

**Comment by BastiaanOlij** [comment]
Strange, I'll have a look at your example project when I'm home tonight and see if it'll load on my note 4. I haven't touched android in awhile so..

**Comment by BastiaanOlij** [comment]
@Paritosh97 I've only downloaded your example, I haven't tried it out yet, but I noticed that you have downloaded the oculus and openvr addons. 
If it includes those in the package then Android won't know what to do with them. 
I haven't player around enough yet with excluding things but I believe you can tell the export to ignore files with the setting in the resource tab.
Or else just remove that addons folder just to test and see if that resolves your issue.

**Comment by Paritosh97** [comment]
Hey, @BastiaanOlij thanks for the heads up.
Unfortunately, the problem still persists on both my phones even after trying both of these solutions.

**Comment by Paritosh97** [comment]
Yeah my bad.
The issue seemed to be project specific didn't happen again after creating
a fresh project. The export probably got messed up when I tinkered with the
oculus and open vr modules.
