### ISSUE TITLE
Easily modify properties and other UI values by scrolling when cursor is above it (like in Adobe Illustrator or FL Studio)

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#17467]
Adobe Illustrator and FL Studio have an amazing feature where you can easily change any value that is under your cursor by scrolling with the mouse wheel.

Additionally for Illustrator, when scrolling you change the numerical value by 1. If you hold Shift, you change it by 10, and if you hold Ctrl, you change it by 0.1.

Additionally for FL Studio, when you click the value with middle mouse button, it resets to its default.

I found these controls very useful and time-saving, and I believe value-changing in Godot Editor would be a ton faster if we were to implement this.

Another benefit would be that we could remove the "+", "-", and "revert to original value" buttons, which would leave more place for the value itself.

**Comment by volzhs** [comment]
did you try drag it up and down?

**Comment by Noshyaar** [comment]
Duplicate of #17371?

**Comment by wingedadventurer** [comment]
@Noshyaar Sorry, did not see that issue upon searching. :/

Closing this.
