### ISSUE TITLE
ConfirmationDialog has no signal for "cancel"

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17460]
Godot 3.0.2

I have a flow in which I allocate resources, and then potentially show a ConfirmationDialog if some condition is met. If the user cancels, I want to deallocate resources. If the user accepts, I want to continue the process.

The problem is, `ConfirmationDialog` has no signal for "cancel".

What I mean by "cancel" is anything that interprets as a "no" from the user:
- The user clicked "Cancel"
- The user closed the popup
- The user pressed escape

The only signal I found is "hide" and "popup_hide", which i cannot use anyways because the popup hides in both choices, and before "confirmed" is emitted.

**Comment by akien-mga** [comment]
As mentioned by @reduz in https://github.com/godotengine/godot/pull/21623#issuecomment-421056063 you can use the `modal_closed` signal for that already. If it isn't mentioned yet, it should likely be made clear in the docs.

**Comment by Zylann** [comment]
`modal_closed` sounds a bit misleading because the use case has nothing to do with modality (aka a window you can't close until a choice is made).

**Comment by MaaaxiKing** [comment]
Will there be a cancel signal in 3.2.2 or why does this have a milestone and there isn't such a function?

**Comment by akien-mga** [comment]
As you can read above, this feature request was not implemented but the actual existing signal that can be used for this was documented in #34499. The milestone is 3.2 because this was closed during 3.2 development.
