### ISSUE TITLE
Gradients cannot be duplicated

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#17478]
**Godot version:**
3.0.2

**OS/device including version:**
Win10

**Issue description:**
If you attempt to use a duplicated color (Gradient) it will not work correctly when running the game but will appear correct in the editor. When you restart the editor the color will not appear correct.

**Steps to reproduce:**
1. Create a Gradient. I did this by creating a Particles2D, editing the material's color ramp property, adding a new gradient texture, adding a gradient, saving the gradient.
2. Duplicate the gradient. In Godot's file explorer right click the gradient and click "Duplicate" from the pop up.
3. Edit & save the duplicated gradient. It appears correct in the gradient editor
4. Use the gradient, for example on the particle2d's material's color ramp.
5. Gradient appears to work in editor for the particle's scene.
6. Run the game. The particle color will revert the the original gradient color
7. Close the editor. Reopen. The particle will be the original color in the editor. You can try to edit it again to get the same (non functional) result.

Can someone verify this causes issues? Kind of complicated to set up, not sure if every step matches what I did on my machine.

**Minimal reproduction project:**
NA

**Comment by Zylann** [comment]
Could you describe the repro steps more precisely? `Particles2D` doesnt have a color ramp property (but `ParticlesMaterial` does).
Also, color ramp is not a `Gradient` property, but a `GradientTexture`. 
Also, how did you do 2)?

**Comment by JarLowrey** [comment]
Updated. Any other questions?

**Comment by Chaosus** [comment]
Checked, seems like its fixed in the current master. Closed by bugsquad.

**Comment by OdinKong** [comment]
I've had something happen twice now where I duplicate about 6 gradients make changes to all of them apply them to things only to realize they sort of aren't updating through all assets the way I would expect. Restart Godot and all their names are off by one while the most recent one duplicated is gone. I really have no idea whats causing it other than duplicating lots of gradients. This is in Godot 4.3
