### ISSUE TITLE
Joypad changes undetected on Windows

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1747]
Godot doesnt detect if gamepads are connected or disconnected on windows ( I'm using up to date 7 Pro ) at all in runtime. The only way to get gamepads work well is to connect them before running the game itself.
joy_connection_changed signal doesn't detect any changes too. However everything works great on Ubuntu 14.01.
I've checked it on different Godot versions ( down to official beta 1.0 ) - without any luck.
Would love to see it fixed =]

**Comment by reduz** [comment]
i´ll be back to windows soon to give this a try

**Comment by Krzycho666** [comment]
By the way... There is another problem ( on windows - did not checked on linux yes ). When I'm using one of my gamepads ( SpeedLink XEOX Pro ) in XInput instead of DirectInput mode, no other gamepads are detected. When I switch it back to DirectInput all other pads are detected fine.
This problem doesnt exist on Logitech F310 when using XInput. Don't know what's the problem basicaly, but this part of code seem to have some trouble on Windows.

**Comment by akien-mga** [comment]
See also #49 and #909.

**Comment by Hinsbart** [comment]
I think this can be closed, fixed in current master (as of d8143eb3)

**Comment by vnen** [comment]
Fixed by #3138.
