### ISSUE TITLE
OBJ materials are not imported properly (see at the bottom)

### ISSUE THREAD

**Issue by brylie** [godotengine/godot#17475]
**Godot version:** 3.0.2

**OS/device including version:** Ubuntu 17.10

**Issue description:**
I am trying to import an .obj file exported from blender. However, I cannot import the accompanying materials file (.mtl).

**Steps to reproduce:**
1. Open a mesh in Blender with corresponding materials
2. Click *File*->*Export*->*Wavefront (obj)*
3. select a destination
4. open a file browser at the export location
5. drag the .obj and .mtl file and drop them on to the Godot project resources area

**observed results**
The .obj model is available in the assets area, but the .mtl is not. Dragging and dropping the .obj file into the 3D window creates the MeshInstance, but there are not any attached materials.

**Minimal reproduction project:**
Attached are some suburban houses models
[suburbian_houses_v1.tar.gz](https://github.com/godotengine/godot/files/1804522/suburbian_houses_v1.tar.gz)

**Comment by sdfgeoff** [comment]
Currently godot ignores the mtl files completely. If you want to import an object with materials, use one of the other formats (dae, gltf, or the [blender->godot exporter](https://github.com/godotengine/godot-blender-exporter)).

**Comment by akien-mga** [comment]
@reduz often stated that Waveform materials should be supported now in 3.0, so it's a bug if they're not.

**Comment by star-tek-mb** [comment]
I have good support for .obj file. Yes, .mtl files are not shown in file tree. But materals applied to model in preview.

**Comment by brylie** [comment]
> If you want to import an object with materials, use one of the other formats (dae, gltf, or the blender->godot exporter).

I have tried that module. It leaves a lot to trial and error, and lacks step-by-step documentation beyond installing the plugin.

**Comment by Overblob** [comment]
For material import there is still a problem related to texture file loading (map_Kd, map_Ks, map_Kn and map_bump)
When you export a model as `.obj` with materials using textures, Blender writes the texture file's **absolute path** in the `.mtl` file, however Godot tries to import them as if **a relative path** was given...it obviously can't be opened and eventually no texture is assigned for the material albebo, specular, etc..

![image](https://user-images.githubusercontent.com/31958866/43917155-c1f0cd94-9c0f-11e8-8368-f853b8ad176b.png)
![image](https://user-images.githubusercontent.com/31958866/43917250-13ec1d9c-9c10-11e8-81b4-06cd643b60dc.png)

Is Godot supposed to be able to load and use external ressources, i.e ressources that are **not** located under `res://` or `user://` ?

**Comment by pgruenbacher** [comment]
![image](https://user-images.githubusercontent.com/3332598/45580684-08dff180-b862-11e8-8596-2d8f97129173.png)

Doesn't seem like blender likes the replication project's DAE file either... 

![image](https://user-images.githubusercontent.com/3332598/45580695-2614c000-b862-11e8-8bb4-dfb0556cf900.png)

and godot / blender behavior seems to be the same...

**Comment by pgruenbacher** [comment]
![image](https://user-images.githubusercontent.com/3332598/45580833-a556c380-b863-11e8-94ff-0b2e2c166947.png)
 also unable to replicate with the blend file

**Comment by pgruenbacher** [comment]
this seems non-issue or non-replicable issue to me. @brylie can you reply with whether this is still a known issue for you.

**Comment by brylie** [comment]
Sure. I will try to reproduce.

**Comment by brylie** [comment]
@pgruenbacher when you open the .blend file, be sure to change your rendering engine to Cycles. In the screenshot above, you have the Blender Render enabled.

![screenshot_20180915_184032](https://user-images.githubusercontent.com/17307/45588016-d5ab6a00-b916-11e8-86ea-c61d13c3f60b.png)

**Comment by pgruenbacher** [comment]
Hmm I still don't see the PBR materials when switching to cycles render. Likewise when I render image. When I inspect the pbr material node editor I just see a blank "base_texture" for the "luxurious house" when I switch the material to one that works (car orange material) I can export a collada file and re-import it in godot, but the godot material has the albedo as red. When I reimport the collada file from blende it does show the correct color though. I do see there being issues with the general exporting/importing of collada from blender to godot, but that's a separate issue.

![screenshot from 2018-09-15 12-34-23](https://user-images.githubusercontent.com/3332598/45588503-d8409c00-b8e3-11e8-9db0-f23d5f0b47a6.png)
![screenshot from 2018-09-15 12-34-10](https://user-images.githubusercontent.com/3332598/45588504-d8409c00-b8e3-11e8-8bef-745570e8c81d.png)
![screenshot from 2018-09-15 12-29-24](https://user-images.githubusercontent.com/3332598/45588505-d8409c00-b8e3-11e8-9d6c-e73edd8e5e66.png)
![screenshot from 2018-09-15 12-37-33](https://user-images.githubusercontent.com/3332598/45588546-6452c380-b8e4-11e8-82f3-3648b8f0bd10.png)

**Comment by pgruenbacher** [comment]
And finally, exporting and importing from obj does show the materials for me being automatically included with the mesh surfaces.

![image](https://user-images.githubusercontent.com/3332598/45588573-d7f4d080-b8e4-11e8-996a-3049fdd0e67f.png)

**Comment by brylie** [comment]
OK, cool. I am on a new laptop, so will need to get a Godot environment set up again. Thanks for digging into this issue :-)

**Comment by pgruenbacher** [comment]
yea I can dig into c++ code for explicit issues/fixes but it's hard for me to know the fixes to workflow problems and such.
