### ISSUE TITLE
GridMap takes very long to startup because of Bullet Physics

### ISSUE THREAD

**Issue by jprob** [godotengine/godot#17484]
**Godot version:** 3.0.1

**OS/device including version:**
Arch Linux, Intel Integrated Graphics

**Issue description:**
I have some C++ native code which generates a 1000x1000 map (takes about 3 seconds [compile /libs/src/code/debugging.cpp to check that]). It extends GridMap and then basically does owner->set_cell_item(i, 0, j, cell_item[i][j]) for i and j in [0, 1000]. This is done on program startup (The "World" GridMap Node has the nativescript attached to it, you can set width and height there). In Godot this takes ages for width and height being 1000.
TMM on #godotengine-devel was so nice to check the problem and said that I have a few errors related to the physics engine (I don't know how he saw that) and changing the engine back to Godot 3 makes it work which it does.

**Steps to reproduce:**
Open the project and run it

**Minimal reproduction project:**
[reproduce.zip](https://github.com/godotengine/godot/files/1807235/reproduce.zip)

**Comment by groud** [comment]
cc @AndreaCatania

**Comment by hpvb** [comment]
I can't seem to reliably get those messages back. I'm still trying :)

**Comment by akien-mga** [comment]
Not sure what "takes ages" referred to in OP, but for me the MRP can generate the map in 1-2 sec when starting the project with a recent Godot debug build, which seems decent.

As this issue is otherwise stale, I'll close it.
