### ISSUE TITLE
Singletons can have keywords for a name

### ISSUE THREAD

**Issue by kisiel090** [godotengine/godot#17494]
**Godot version:**
3.0 stable win64

**Issue description:**
In the autoload tab, in project settings you can set singleton name to, for example, "const". You will be unable to use this singleton in gdscript, as editor assumes you are using a keyword.
[MVP.zip](https://github.com/godotengine/godot/files/1808453/MVP.zip)

**Steps to reproduce:**
add a singleton with name that is a reserved keyword in gdscript

**Comment by mhilbrunner** [comment]
What about engine singletons? Whats happens if you use names such as "Input", "OS" etc?

**Comment by kisiel090** [comment]
It shows up error that name should not collide with existing class name.
However, i think same should be for keywords, as you are unable to use singleton anyway, and then are forced to change it's name.

**Comment by bojidar-bg** [comment]
Note that the singleton is still useable via `get_node("/root/const")`.
I would retag this to topic:gdscript, as is it a problem only in scripting languages, not in core.

**Comment by akien-mga** [comment]
>  I would retag this to topic:gdscript, as is it a problem only in scripting languages, not in core.

Wouldn't it affect Mono too?

**Comment by willnationsdev** [comment]
I don't think C# creates identifiers for accessing singletons, does it? Sounds like something that C# wouldn't let you do.

**Comment by mhilbrunner** [comment]
>It shows up error that name should not collide with existing class name.

Thats probably only for singletons though, as I can create custom autoloads/singletons that shadow a Godot class.

I just did this by accident, created an *Engine* autoload, which made things funky. There should absolutely be a warning about this.
