### ISSUE TITLE
Add a suffix to MinGW build products to differentiate them from MSVC build products

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#17509]
As noticed in https://github.com/godotengine/godot/pull/17194#issuecomment-373038848, MinGW build products should have a prefix in their name as to be differentiated from MSVC build products. This would prevent conflicts and build errors when using both compilers on the same system.

**Comment by bruvzg** [comment]
ARM Linux/Server builds also have conflicting suffixes ( `.32` and `.64`, same as x86 builds ).

I would prefer to have something closer to standard GNU target triplets instead, like:
```
godot-tools-3.1.0-x86_64-pc-windows-gnu
godot-tools-3.1.0-x86_64-pc-windows-msvc
godot-server-3.1.0-aarch64-unknown-linux-gnu
...
```

**Comment by akien-mga** [comment]
I agree with @bruvzg, it's time to up our game and be a bit more exhaustive.

**Comment by jahd2602** [comment]
@bruvzg Macos won't run an executable with a dot in the name, can we replace the dots with underscore?
```
godot-tools-3_1_0-x86_64-pc-windows-gnu
```

**Comment by bruvzg** [comment]
>Macos won't run an executable with a dot in the name, can we replace the dots with underscore?

Executables with dot in the name (in both executable and bundle names) should work fine on macOS, current build system produce executables with dot like `godot.osx.tools.64` and `godot.osx.opt.64` as well.

But there's a bug with loading exported `pck` when there's dot in the name - #15188.

**Comment by Calinou** [comment]
Closing in favor of #24030, which is a better way to solve the issue at hand.
