### ISSUE TITLE
PNG texture import has inverted, offset background

### ISSUE THREAD

**Issue by brylie** [godotengine/godot#17515]
**Godot version:** 3.0.2

**OS/device including version:** Ubuntu 17.10

**Issue description:**
When importing a PNG file, [from OpenClipArt.org](https://openclipart.org/detail/170428/acrobat-ant), the texture has an offset, inverted background:
![screenshot_20180314_234947](https://user-images.githubusercontent.com/17307/37433216-b0f00014-27e3-11e8-8db9-67fee7979dd4.png)

**Steps to reproduce:**
1. create an empty project
2. add a root Node2D
3. add a Sprite node
4. download the [ant PNG](https://openclipart.org/detail/170428/acrobat-ant) from OpenClipArt
5. drag and drop the and.png into Godot
6. select the sprite node
7. drag and drop the ant.png on to the Sprite texture

**Minimal reproduction project:**
[ant_bug.zip](https://github.com/godotengine/godot/files/1813245/ant_bug.zip)

**Comment by akien-mga** [comment]
That's how the source file is on OpenClipArt: https://openclipart.org/image/800px/svg_to_png/170428/crematogaster.png

**Comment by brylie** [comment]
Ah, really subtle. Thanks for double checking!
