### ISSUE TITLE
Script previews showing as completely black

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17512]
**Godot version:**
e767482

**Issue description:**
Self-explanatory:
![screenshot1](https://user-images.githubusercontent.com/30739239/37429018-d156506a-27ac-11e8-901f-db33f86ea0cb.png)

**Comment by akien-mga** [comment]
It used to work, do you roughly know when it broke?

**Comment by YeldhamDev** [comment]
@akien-mga Sadly no, I just opened the `FileSystem` tab and saw them like this.

**Comment by bojidar-bg** [comment]
Can confirm, though I don't remember when it stopped working either. Maybe a few weeks.

**Comment by ShyRed** [comment]
There seems to be a problem with setting the colors. Lines 465 to 468 the colors are set. At lines 473-476 the colors get set to 0,0,0,0.

If you comment out 473-476, the preview generation starts working again.

https://github.com/godotengine/godot/blob/401a39f57e09a6e919e3291fd3e64e3ee320820f/editor/plugins/editor_preview_plugins.cpp#L465-L477

**Comment by ShyRed** [comment]
Addition: Script preview generation also starts working again, if you do the following steps in Godot:
1. Open `Editor Settings`
2. Go into `Text Editor` section and select `Theme`
3. Set `Color Theme` to `Default`

Maybe this is not a technical bug, but missing settings in the theme?

**Comment by YeldhamDev** [comment]
@ShyRed Changing the color theme didn't fix it here.

**Comment by ShyRed** [comment]
@YeldhamDev Did you save a script? It takes effect only after saving re-generating the previews again (e.g. save a script to make Godot generate the preview).

**Comment by YeldhamDev** [comment]
@ShyRed Yep, now it works.

**Comment by akien-mga** [comment]
Fixed by #18788.
