### ISSUE TITLE
HTML5 Javascript broken export template

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#17518]
**Godot version:**
Master

**OS/device including version:**

Ubuntu
build with emscripten 1.37.36 

While building the template I get these messages maybe they are related.
```
emcc: warning: cannot represent a NaN literal '0xe8de190' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
emcc: warning: cannot represent a NaN literal '0xe8de190' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
warning: unresolved symbol: _ZN10EMWSServer4pollEv
warning: unresolved symbol: glMapBufferRange
warning: unresolved symbol: glUnmapBuffer
warning: unresolved symbol: posix_spawn_file_actions_adddup2
warning: unresolved symbol: posix_spawn_file_actions_destroy
warning: unresolved symbol: posix_spawn_file_actions_init
warning: unresolved symbol: sem_getvalue
```

Running the project from the engine gives me this error
**ERROR**: Failed loading file 'tmp_export.wasm' see https://github.com/godotengine/godot/issues/16093

Exporting the project create a .zip file that contains all project files with different ending

.gd -> .gd.remap
.gd -> .gdc
project.godot -> project.binary

@eska014

**Comment by eska014** [comment]
1. > ERROR: Failed loading file 'tmp_export.wasm'

     You need to host the exported files on a local web server https://godot.readthedocs.io/en/3.0/getting_started/workflow/export/exporting_for_web.html#starting-exported-games-from-the-local-file-system

2. 
   > Exporting the project create a .zip file that contains all project files with different ending

     You need to click the *Export project* button, not the *Export PCK/Zip* button in the export dialog

**Comment by AlexHolly** [comment]
1. So the server is running now but still the same error
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [15/Mar/2018 03:23:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Mar/2018 03:23:33] code 404, message File not found
127.0.0.1 - - [15/Mar/2018 03:23:33] "GET /favicon.ico HTTP/1.1" 404 -

2. Not possible it always tells me the template is not installed that is not true I placed it at 
`.local/share/godot/templates/` and tried those names
`godot.javascript.opt.debug.zip`
`javascript_debug.zip`
`webassembly_debug.zip`

**Comment by eska014** [comment]
The template directory is versioned, so put the file in `~/.local/share/godot/templates/3.0-stable` for 3.0 or `~/.local/share/godot/templates/3.1.dev` for the `master` branch. The file names are  `webassembly_debug.zip` and `webassembly_release.zip`

**Comment by akien-mga** [comment]
So both not bugs then, closing.

> You need to host the exported files on a local web server https://godot.readthedocs.io/en/3.0/getting_started/workflow/export/exporting_for_web.html#starting-exported-games-from-the-local-file-system

@eska014 Do you think we could add an option to autostart a local web server? (provided the user as the required software for that, we could recommend python since many have it installed to build Godot)

**Comment by AlexHolly** [comment]
1. Is not working out of the box the default folder is the home folder this is not where the project is located. I don't want to use this feature but maybe others would like to use it, should I open an issue?

2. Exporting worked now but I get this on an new project.
```
let it go dude!
**ERROR**: Calling stub instead of sigaction()
**ERROR**: Pack created with a newer version of the engine: 3.1.0
**ERROR**:    At: core/io/file_access_pack.cpp:172:try_open_pack() - Condition ' ver_major > 3 || (ver_major == 3 && ver_minor > 0) ' is true. returned: false
**ERROR**: Pack created with a newer version of the engine: 3.1.0
**ERROR**:    At: core/io/file_access_pack.cpp:172:try_open_pack() - Condition ' ver_major > 3 || (ver_major == 3 && ver_minor > 0) ' is true. returned: false
**ERROR**: warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling
Error: Could not load game path '.'.
**ERROR**: Condition ' !_start_success ' is true. returned: false
**ERROR**:    At: main/main.cpp:1232:start() - Condition ' !_start_success ' is true. returned: false
```
https://github.com/GodotBuilder/godot-builds/releases/tag/3.0_20180303-1

**Comment by akien-mga** [comment]
> https://github.com/GodotBuilder/godot-builds/releases/tag/3.0_20180303-1

That's 3.0.2. You can't use 3.1.dev with 3.0.2 templates.

**Comment by AlexHolly** [comment]
I downloaded the x11.tool from this release and stopped using the master until it works.
