### ISSUE TITLE
Resource references from GDscript not followed when exporting w/dependencies

### ISSUE THREAD

**Issue by Cygon** [godotengine/godot#17513]
**Godot version:** 3.0.2-stable (custom build from 2ff3b08583766c975d76d8c39ba0937a5c9bf064)
**OS/device including version:** Gentoo Linux, Kernel 4.14.12, KDE 5, NVidia GTX 1080 with NVidia proprietary drivers 390.12

**Issue description:** Using the `extends` directive in GDScript to derive from another GDScript class will cause the **Export** feature to generate broken builds if converting resources to binary is enabled.

Although GDScript code gets packaged as bytecode, it appears that the path behind the `extends` directive gets stored verbatim. Thus, the export template executable will attempt to load the uncompiled, original GDScript source file (which is not present in the `.pck` file, of course).

![gdscript-inheritance-loading-error](https://user-images.githubusercontent.com/3613175/37431412-77ea2e6a-27d5-11e8-97ea-20a3b19307ac.png)

**Steps to reproduce:**
1. Create a Godot project and add 2 GDScript (`.gd`) files to it
2. Make one GDScript class inherit the other: `extends "res://Other.gd"`
3. Use the derived GDScript class in an arbitrary scene that is included during export
4. Configure the project for binary export
![godot-export-binary-resources](https://user-images.githubusercontent.com/3613175/37431494-b296e512-27d5-11e8-965e-b9360cff2e19.png)
5. Export and try to run the resulting build.

**Comment by Cygon** [comment]
After investigating this further, it seems this issue is just a follow-up of another issue:

Resources referenced only in GDscript are not identified as build dependencies. So whether a script uses `extends "res://some_other_script.gd"` or `preload("res://game_over.wav")`.

A possible workaround is to create a never-loaded scene that references all such resources like this:
<img width="323" alt="godot-scene-resources" src="https://user-images.githubusercontent.com/3613175/40747147-b191a29c-645c-11e8-81ac-881a7c35d9ea.png">

Anyway, I believe this is a known issue, but I could find no other bug mentioning it (i.e. [Issue Search: gdscript dependencies](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+gdscript+dependencies).

**Comment by vnen** [comment]
Apparently this is not really a bug, what happened is that there was a missing resource in the exported project and the GDScript depended on it, so it failed to load. Probably there was more logs before the one showed in the first screenshot.

**Comment by Cygon** [comment]
Okay, I tried to come up with a better title :)

The repro project I attached does `Inherits "res://otherscript.gd"` in GDscript and fails during runtime because `otherscript.gd` isn't exported. Not sure if GDscript base classes are any easier to identify as references, but this caused, at least for me, the most confusion.
