### ISSUE TITLE
AudioStreamPlayer2D does not work when it is inside a CanvasLayer

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#17523]
**Godot version:**
3.x custom built from aeb1c67b5b55c769256a8ffc2f9d9095d6fc74da

**OS/device including version:**
Windows 10

**Issue description:**
Whenever an `AudioStreamPlayer2D` is inside a `CanvasLayer`, it will be silent (it will not work). After initial debugging, I found that this is due to:

- `CanvasLayers` have their own `world_2ds`
- `CanvasLayers` `world_2ds` somehow don't get the default `Viewport` added to it's internal list.
- When `AudioStreamPlayer2D` checks whether it is inside a `world_2d` that has a viewport attached that is an `audio_listener_2d`, it doesn't find any because the `CanvasLayer`'s `world_2d`'s viewport list is empty.

Relavant lines in `AudioStreamPlayer2D`:
https://github.com/godotengine/godot/blob/aeb1c67b5b55c769256a8ffc2f9d9095d6fc74da/scene/2d/audio_stream_player_2d.cpp#L182-L186
Line 182 results in an empty list of viewports when inside a CanvasLayer

**Steps to reproduce:**
Put an AudioStreamPlayer2D inside a CanvasLayer and call play() on it. It will be silent.

**Minimal reproduction project:**
[audioCanvasLayer.zip](https://github.com/godotengine/godot/files/1814295/audioCanvasLayer.zip)

**Comment by chanon** [comment]
It looks like `CanvasLayers` `world_2ds` never get their `_register_viewport` method called. 

`_register_viewport` is where the viewport gets added to the `world_2ds` internal list.

Currently `_register_viewport` is called only inside `viewport.cpp` when
- A viewport is added to the tree.
- The viewport's `world_2d` property is set.

It is not called when a new `CanvasLayer` (an thus a new `world_2d`) is added to the tree, so the `CanvasLayers` `world_2d` does not get the current viewport added to its list.

BTW, I tried setting the viewport's `world_2d` property to the `CanvasLayers` `world_2d`. This works, but it leads to:

```
ERROR: VisualServerViewport::viewport_attach_canvas: Condition ' viewport->canvas_map.has(p_canvas) ' is true.
   At: servers\visual\visual_server_viewport.cpp:473
```

Since `VisualServer::get_singleton()->viewport_attach_canvas` *does* get called for the `CanvasLayers` `world_2d`.

**Comment by chanon** [comment]
I have added a pull request to fix this issue.

**Comment by RandomShaper** [comment]
@hpvb, I've just hit the bug fixed by this and have ended up here.
Since it's been some months since, I'm commenting to remind you to cherry-pick it for 3.0.7.
Would you like me to open a PR with the cherry-pick instead?

**Comment by RandomShaper** [comment]
Well, as @akien-mga says in the comment, that would need further enhancements to preserve compatibility.

Moreover, for 3.0 it might be too breaking. I'm not sure at this point...

**Comment by RandomShaper** [comment]
I'm preparing a PR fixing the compat breakage and another one backporting the fix. So no worries. :)
