### ISSUE TITLE
ProjectSettings.get_setting doesnt work

### ISSUE THREAD

**Issue by houfaru** [godotengine/godot#17521]
**Godot version:**

Godot 3.0.2

**OS/device including version:**

Linux Mint 17.2 x86_64

**Issue description:**

Hi
I could not load AdMob Module from https://github.com/kloder-games/godot-admob

**Steps to reproduce:**
1. download
  https://github.com/kloder-games/godot-admob/tree/master/admob into admob folder
  https://github.com/godotengine/godot into ~/godot-3.0.2-stable
2. put admob folder to ~/godot-3.0.2-stable/modules
3. execute the following commands

 cd ~/godot-3.0.2-stable

 scons platform=x11

 scons platform=android target=release -j 4
 cd platform/android/java
 ./gradlew build
 cd ../../..

 scons platform=android target=release_debug -j 4
 cd platform/android/java
 ./gradlew build
 cd ../../..

4. execute godot.x11.tools.64
5. create a new project and new main scene with its script
6. select Project->Project Settings->General
   add new property
      Category:	Android
      Property: Modules
      Type    : String
      value   : org/godotengine/godot/GodotAdMob
7. Select Project->Export->Android->Options
    add android_debug.apk and android_release.apk into Custom Package
8. add ProjectSettings.has_setting("AdMob") into one the script you have
   and It shows **false**(expected **true**)

NOTE:
The instructions/docs still uses earlier Godot version: 
  engine.cfg instead of project.godot
  Globals.get_singleton instead of ProjectSettings.get_setting
 I can only use project.godot and ProjectSettings

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
You should use `Engine.get_singleton()`.

Issues with third party modules should be reported to the module repos, and only here if you establish with the module maintainer that the issue comes from the engine itself.
In this case, there's even a Godot 3 example showing you how to use it: https://github.com/kloder-games/godot-admob/blob/master/examples/godot-3/main.gd

**Comment by houfaru** [comment]
thanks.I'll keep that in mind. sorry for the trouble
