### ISSUE TITLE
debugger_stdout/max_chars_per_second not respected

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#17522]
**Godot version:**
955397d

**OS/device including version:**
Ubuntu Linux 17.10 64b

**Issue description:**
I found myself needing to print several lines at an specific time for an one-time issue and couldn't access a terminal for unfiltered stdout, but kept running into [output overflow, print less text!] in the stdout panel in the editor.
I went to raise max_remote_stdout_chars_per_second in project settings, as in 2.x, but found out the option didn't exist anymore, and couldn't find the 3.x equivalent. Tried similar-sounding options but none seemed to have any effect, and couldn't find any equivalent through Google either.

After asking around, someone helped out in Discord, and it was found that the setting is now governed by Network/Limits/debugger_stdout/max_chars_per_second, which was confirmed as being set properly, but not having any effect when changed.

**Steps to reproduce:**
Print enough text in a frame until you hit [output overflow, print less text!], then raise debugger_stdout/max_chars_per_second to any higher value. There won't be any changes in how much text is printed.

**Comment by akien-mga** [comment]
Fixed by #17527.
