### ISSUE TITLE
Editor UI Toggle to Disable Scripts

### ISSUE THREAD

**Issue by xudz** [godotengine/godot#17539]
It would be very useful to have a way to quickly turn off a script in the editor. One simple click and the node that said script is attached to is still active and rendering but the script itself does not execute.

Other engines (i.e. Unity) typically offer this as a way to quickly see if a script is causing an observed behavior or misbehavior.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/370, as feature proposals are now tracked in the Godot proposals repository.
