### ISSUE TITLE
Godot doesn't notify user of potentially sizable loss of data when "editable children" is checked off.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#17547]
**Godot version:**

Godot 3.0.2 Stable

**OS/device including version:**

i7 3770 CPU; AMD 7700 GPU; 24 gigs RAM; Win10 64 bit (Fall Creators update)

**Issue description:**

When the editable children checkbox is disabled while information within has been edited or overriden, there will be no notification if the user saves the scene and exits the project. The user then loses the edited data (changed values, groups, everything). I for instance use editable children to modify Blender scene files brought in as a child scene of a larger scene (for avoiding loss of work if a re-import is needed).  This can sneak up on you for instance since the _editable children_ checkbox will instantly revert to 'off' if the name of its top node is changed.

The thing though, you can lose more than assignments if you turn the checkbox off and forget to turn it back on. Material files that only existed inside of overridden material slots can get corrupted and become an invalid file, forcing the user to recreate it.

I do make backups fortunately, so I lost a very small amount of work at most. I don't think the scene has to be a Collada file even, but any scene that is a child and has overridden values. I think it is possible that forgetting data like this is by design, but the user gets no warning that it will be the case (and as I mentioned before, there is one case where it can sneak up and not get caught).

**Comment by akien-mga** [comment]
I agree that it should check for modifications and issue a warning.

> This can sneak up on you for instance since the editable children checkbox will instantly revert to 'off' if the name of its top node is changed.

That's a bug in its own right though, it should be fixed independently of the addition of a warning when checking off.
