### ISSUE TITLE
GDSscript Editor Indent/Outdent Keyboard Shortcut

### ISSUE THREAD

**Issue by xudz** [godotengine/godot#17540]
With indenting and outdenting text being such common operations in Pythonesque GDScript, it would be useful to be able to indent and outdent selected blocks of text with a keyboard shortcut instead of having to navigate a right-click menu for each in/outdent.

**Comment by Zylann** [comment]
Ctrl+K?

**Comment by thismarty** [comment]
I tried that but it doesn't work.  It's not even showing up in the menus as an option.

**Comment by Zylann** [comment]
Weird, I use this all the time, like all regular code editors Oo

**Comment by thismarty** [comment]
Well, that was silly of me. 

I checked the key mappings in Godot and in/outdent were set to null (by default?).

I just set them manually and everything works peachy now.

Still, it might be nice to have these set by default on a new installation, assuming what I am seeing is typical.

**Comment by Zireael07** [comment]
Indent/outdent have been null by default since 3.0 for me, so something to look at?

**Comment by thismarty** [comment]
Agreed.

Re-opened to have the team look at enabling these by default.

**Comment by vnen** [comment]
AFAIK Tab and Shit+Tab works independently of that option, if the text is selected. The shortcuts used to be Alt+Left and Alt+Right, but now that's used for Back/Forward in history, so they were removed from indent/dedent.

**Comment by robfram** [comment]
Just test this. No shortcut assigned to indent/dedent and Tab/Shift+Tab work perfectly in the editor.

**Comment by GalanCM** [comment]
A lot of editors (Atom, VSCode, etc.) use Control + [ and Control + ] for this.

**Comment by KidRigger** [comment]
Confirming Tab/Shift+Tab working on no shortcuts on macOS, 
I think I'll add Control+[ and Control+] (CMD+[ and CMD+] on macOS) as defaults

**Comment by Calinou** [comment]
This is implemented since Godot 3.0 (<kbd>Tab</kbd> and <kbd>Shift + Tab</kbd), closing.
