### ISSUE TITLE
Implement ++ or --

### ISSUE THREAD

**Issue by blendi-93** [godotengine/godot#1754]
hi,

would be usefull i think.
variable +=1 works so why not pls variable++

**Comment by bojidar-bg** [comment]
+1

**Comment by draxdeveloper** [comment]
while(voting==true):
   totalVotes++

2015-04-29 5:23 GMT-03:00 Bojidar Marinov <notifications@github.com>:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1754#issuecomment-97350680>.
>



-- 
David Aguiar de Aquino Paiva

**Comment by kpiorno** [comment]
I guess that topic was discussed on the Python community and was discarted because affects the legibility of the code. May be fine in godot, but I think foo+=1 is good enough.

**Comment by Fiona** [comment]
The answer on this page gives a good reason why Python does not have it: http://stackoverflow.com/questions/3654830/why-are-there-no-and-operators-in-python

One doesn't miss it in Python, the language doesn't need it and adds a bit of unnecessary complexity.

**Comment by WatIsDeze** [comment]
GDScript != Python though, and the explanation given there may not specifically add up to GDScript.

As for if we do ask if it makes sense, it simply does given the fact people whom use Godot come from all sorts of languages. Instead of making things more complex it simply just would make the language feel more welcome to more people. (My 5 cents).

Also adding this probably wouldn't be that hard, me thinks.

**Comment by SuperUserNameMan** [comment]
Yeah, that would be cool if we could write disturbing things like this :
````
if ( ++i != i-- ) :
  j = ++i--
````

**Comment by WatIsDeze** [comment]
What is your point @SuperUserNameMan ? It's entirely up to you, what you write, why would anyone care what others write?

**Comment by touilleMan** [comment]
@WatlsDeze there is reasons for people to care about what others write: reading source code is a great way to learn, people are often working in team etc.

My 2cents: Godoscript is presented as a domain-specific language inspired by Python. This said I think Godoscript should try to keep things as close to Python as possible for the sake of the "principle of least astonishment".

**Comment by akien-mga** [comment]
This has been discussed in #1107 already, so closing as duplicates as we don't need two issues about it. I still don't think that supporting `var++` would bring any added value to GDScript, but well, we can continue gathering community opinions and see if a consensus is finally reached :)
