### ISSUE TITLE
Cannot see RGBA values of a Color in the debugger

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17545]
Godot 3.0.2

The debugger shows colors as coloured rectangles, but they don't show the components.

![image](https://user-images.githubusercontent.com/1311555/37493172-5008cf62-28a4-11e8-96d6-a4f6b192734a.png)

The only way to see them is to find the variable in the code, and put the mouse over it to see the tooltip.

![image](https://user-images.githubusercontent.com/1311555/37493187-6373c20a-28a4-11e8-848a-6248ba71b570.png)

Could we have these component shown in the debugger panel, like regular color picker?

**Comment by akien-mga** [comment]
CC @Geequlim. I expect that clicking the color would show a ColorPicker (read only maybe?).

**Comment by Geequlim** [comment]
@Zylann  In this situation you can click the `self` then you can open a ColorPicker in the inspector.

We can't modify the the stack variables as we need the object to call `set`. But variables in the breakpoint stack may not have an object to hold them.

@akien-mga Yes we can enable the edit mode but changes can't be applied so it would be a strange behavoir.

**Comment by Zylann** [comment]
It wouldn't be a strange behavior if we simply add a read-only state to the color picker.

**Comment by Calinou** [comment]
@Zylann This may have been implemented by https://github.com/godotengine/godot/pull/32997, please check.

**Comment by Zylann** [comment]
That works now.
