### ISSUE TITLE
GridContainer crashes when its elements have the Control.SIZE_EXPAND_FILL flag and its elements are too big to fit

### ISSUE THREAD

**Issue by Jellonator** [godotengine/godot#17549]
**Godot version:**
3.0.2
I do not know if this affects 3.0.1, but it does not affect 3.0, and the below example will run fine in version 3.0.

**OS/device including version:**
OS: Ubuntu 17.10 artful x86_64 Linux 4.13.0-37-generic
GPU: Quadro 1000M with nVidia proprietary 390 driver

I do not know if this will affect other operating systems or drivers, as I do not have access to any other computers for testing at the current moment.

**Issue description:**
When a GridContainer has at least three nodes in a row, two of which have the Control.SIZE_EXPAND_FILL set, and the content of this row is too large to fit in the grid, then the engine/game will crash.

In my game, my nodes are setup to look like this:
![screenshot](https://user-images.githubusercontent.com/1700153/37503222-7b5fcef0-28ad-11e8-82fb-9d8bd42aa626.png)

There is an image on the left representing the player's current status (is drawing, is winner, etc.), the player's name, and the player's score. I found that if the player's name is too long with Godot 3.0.2, then the game crashes.

**Steps to reproduce:**
Create a GridContainer with three columns, give it three Labels, set the horizontal flags to EXPAND and FILL on the last two Labels. Then, set the text on the labels to be too wide for the GridContainer and the engine will crash. If this is done through code, then this will crash the game when run.

**Minimal reproduction project:**
[CrashGUI.zip](https://github.com/godotengine/godot/files/1817893/CrashGUI.zip)

**Comment by bojidar-bg** [comment]
Isn't this a duplicate of #17389 (even if it is a freeze there and crash here)?

**Comment by groud** [comment]
Can you try with the latest master if the crash still occurs?

**Comment by Jellonator** [comment]
Latest master branch (760b0567a668c927820101d057ea8b4218943438) works for me without crashing. Didn't see the other issue probably because I was searching "crash" instead of "freeze" lol. I'll close this issue since it has already been fixed.
