### ISSUE TITLE
Project and editor crash caused by signal with argument in C#

### ISSUE THREAD

**Issue by Duehok** [godotengine/godot#17553]
**Godot version: 3.0.2 stable, Mono 5.4.1.7, Win 8.1**

**Issue description:**
Adding this line: 
```[Signal] delegate void CustomSignal(string message);```
Compiles but the project crash as soon as the project starts and the editor crashes too if the scene is loaded. 
**If the scene is the main scene, the project can no longer be loaded**
**This is the second (at least) issue where a project can be made un-editable**

A signal without argument does not cause a crash:
```[Signal] delegate void CustomSignal();```

**Minimal reproduction project:**
[CrashOnSignal.zip](https://github.com/godotengine/godot/files/1818410/CrashOnSignal.zip)

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by paulloz** [comment]
Can't reproduce on Linux (master build from ebce36c) with the project linked above :thinking:

**Comment by akien-mga** [comment]
> Can't reproduce on Linux (master build from ebce36c) with the project linked above thinking

Note that the report is against 3.0.2, where some Mono commits have been cherry-picked but not all, so it might behave differently from *master*.

**Comment by paulloz** [comment]
You're right, I can reproduce with the 3.0.2 binary.

**Comment by Akronae** [comment]
A signal with argument causes me a crash as well and a signal without argument throws me this error:
<details>
<code>
0:00:01:0526 - Condition ' p_ptr == 0 ' is true.
----------
Type:Error
Description: 
Time: 0:00:01:0526
C Error: Condition ' p_ptr == 0 ' is true.
C Source: core\os\memory.cpp:159
C Function: Memory::free_static
</code>
</details>

**Comment by neikeq** [comment]
Does this still happen in 3.0.4?
