### ISSUE TITLE
Sprite with repeated texture and region repeats in editor but not in game

### ISSUE THREAD

**Issue by ravenblackx** [godotengine/godot#17550]
**Godot version:**
3.0.2

**OS/device including version:**
Windows, NVidia, I don't think the GPU is to blame here since it works in the editor. :)

**Issue description:**
Attempts to repeat a texture work in the editor, but just stretch the last pixel instead when the game is run.

**Steps to reproduce:**
Create a 2D project.
Create a StreamTexture resource.
Set the load path to the .import/icon.png-* file.
Set the flag to repeat, and any other flags you want.
Save the StreamTexture resource.
Create a sprite.
Set the sprite's texture to the StreamTexture resource you saved.
Set the sprite's region enabled: on, rect: 0,0,128,64
In the editor you should see the sprite repeated as two sprites.
![image](https://user-images.githubusercontent.com/1923229/37505949-dfe61770-28a4-11e8-9127-6ea5f0d25f0f.png)

Run the scene. Instead of the two sprites you saw in the editor, you see a stretched sprite like this
![image](https://user-images.githubusercontent.com/1923229/37505938-cf9870b6-28a4-11e8-9370-d45e709e57c1.png)

If you turn off the repeat flag on the resource it looks the same way in the editor; it looks like the repeat flag is not fully propagating to the scene.

**Comment by Ranoller** [comment]
You need to reimport in "import dock". Import flags in inspector are broken.

**Comment by ravenblackx** [comment]
I guess this might also be a good place to mention that the whole system of texture imports seems a little confused - when an image is added to the project a file is generated image.png.import which has flags in it, which appears to include the repeat flag as a combined number (ie. flags=6 means both whatever 4 is and whatever 2 is are the set flags), but if you make, say, image.tres, that file too has flags, including the repeat flag, in the form "repeat=0" (the other flags in the .tres file are of the form "filter=true", so the repeat flag is unusual here too!)

So it's very unclear whether "flags" from the .import file or "repeat" from the .tres file is supposed to represent the repeat flag that will ultimately be used.

**Comment by ravenblackx** [comment]
I guess from Ranoller's comment that it's the .import file that has taken precedence, which seems likely to be unintentional.

**Comment by nadershamma** [comment]
I have this issue.  I found a temporary work around by setting the flags using GDScript. 
`onready var img = get_node("img")

func _ready():
	img.texture.flags = 15`

**Comment by bojidar-bg** [comment]
Note that changing the flags of the texture won't persist them, since it is an imported resource. There should be a warning box telling you that changes might not be saved.

**Comment by hedrickbt** [comment]
I can confirm this is still an issue in the 3.1+ nightly snapshot from https://hugo.pro/projects/godot-builds/.

**Comment by marcJV** [comment]
Confirming that it is still an issue on 3.1 beta 8. TextureRect works correctly in editor and during runtime.

**Comment by KoBeWi** [comment]
Seems like the `flags` property in StreamTexture is no longer exposed since 3.1.something.

Also 4.0 changed the way filtering/repeating works (it's set per CanvasItem), so this can be closed.
