### ISSUE TITLE
Scene tree crashes when changing visibility in a C# method called by a signal

### ISSUE THREAD

**Issue by Duehok** [godotengine/godot#17552]
**Godot version: 3.0.2 stable, Mono 5.4.1.7, Win 8.1**

**Issue description:**
Showing a modal popup in a C# method called by a signal crashes the whole scene tree to crash and disappear, and sometimes the project too.
There are no error messages in the debugger.

I suspect changing the visibility with the visibility property or the SetVisibility method also causes the same problem, but I sudenly have some doubts about my tests.

The behavior is different in GDScript where the expected behavior  is observed (popup showing)

**Steps to reproduce:**
Connect a node's signal to a C# script's method. In this method, call the ShowModal method on a popup. Suddently the whole project window is empty, or the project crashes.

**Minimal reproduction project:**
Two projects, with GDScript and C#
[CrashOnPopup.zip](https://github.com/godotengine/godot/files/1818419/CrashOnPopup.zip)

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by Duehok** [comment]
Finally with the correct project attached to the issue description.

**Comment by PJB3005** [comment]
I can't seem to reproduce it with your test project on latest master (760b0567a668c927820101d057ea8b4218943438)

**Comment by akien-mga** [comment]
Assuming fixed as per @PJB3005's comment. Please comment if you can still reproduce it in recent 3.1 beta builds.
