### ISSUE TITLE
Joypad IDs increment when they shouldn't and fail to signal on Windows.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#17566]
# Update

Tested and confirmed in alpha 3.1 0ab71d67b8efbb09bda36b0d0a2854182d182354

It is a leak in joypad ID accumulation on Windows, it happens when the first joypad (ID = 0) is unplugged and reconnected while having a second joypad connected.

Doing this several times result in a joypad ID array that looks like [0, 1, 2, 3 ,4, 5, 6, 7], where 0 is the first joypad, and 7 is the second.  The rest do nothing.

# Original Post

Initially there was some problem with joypad device IDs flipping around when controllers were unplugged/re-plugged in a certain order.   https://github.com/godotengine/godot/issues/12643 It appears like some work was done on this, but now another problem exists.   

The issue exists in **joypad_connection_changed(index, connected)** signal.

When the joypad using index 0 is unplugged, the joypad at index 1 will stop reporting its signals.  It won't resume sending signals until the previous (index 0) controller is plugged back in.  At which point it will then increment its index and report a signal of being connected.

Here I've outputted the signal results after unplugging and re-plugging the first controller three times.

![godot_v2 1 5-beta2_win64_2018-03-16_17-35-15](https://user-images.githubusercontent.com/13004169/37529701-7a129e5e-2940-11e8-812b-325058c1dcd3.png)

**Comment by akien-mga** [comment]
What is your OS? I can't seem to reproduce on Linux with the current master branch.

**Comment by avencherus** [comment]
@akien-mga I'm running it on Windows 10 using two PS4 controllers.  Double checked it in 2.1.5RC1, it still appears to be incrementing the second controller's index, when the first controller (0 index) is unplugged and plugged back in.

**Comment by avencherus** [comment]
Curious if anyone has any results with what happens regarding the IDs when this is done with three joypads connected?

**Comment by reduz** [comment]
@punto- may know more about this

**Comment by avencherus** [comment]
When combined with this https://github.com/godotengine/godot/issues/26836, it becomes nightmarish and impossible to keep track of multiple joypads for local multiplayer.

These are the IDs that are accumulated for 2 controllers after unplugging and plugging them back in a few times, which belongs to who, anyone's guess.  If player's unplug their controllers, they'll probably have to restart the game.

![2019-03-09_17-46-59](https://user-images.githubusercontent.com/13004169/54074036-85461100-4296-11e9-8672-bd5f2b99f7fd.png)
