### ISSUE TITLE
[Feature Request] Broadcast signal

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#1756]
in this state of godot you can emit_signal just for a node.but signaling should broadcast to all nodes in scene and if some node connect to that signal the method should be called. 
I read c++ and signal is using in object, we should have a signal manager that store all signals and nodes that connected to this signal and be called when broadcast is called.
I can implement it just give me the green light if this is ok.

**Comment by reduz** [comment]
this is what groups are for, you can broadcast to all the nodes in a group

**Comment by mohaalak** [comment]
@eska014  Thank you so much for cleaning up the repository.

**Comment by eska014** [comment]
> @eska014 Thank you so much for cleaning up the repository.

Gladly, passing that on to the rest of @godotengine/bugsquad as well.
