### ISSUE TITLE
Value of exported string property has literal "Null" when not set in C#

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17579]
**Godot version:**
`master` / dad47d8876de45132226985dbbd079e060f6facc

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
When creating a string property and making it exportable, it initializes with a string literal `Null` rather than an actual null value. The same goes for the case when resetting the property within the editor.

The following code reproduces the problem:

```c#
[Export]
private string _key;

public override void _Ready()
{
    base._Ready();

    // Prints "Null".
    GD.Print("### Value = " + _key);

    // Should throw NullReferenceException, but prints "4".
    GD.Print("### Length = " + _key.Length);
}
```

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by Hinsbart** [comment]
Can't reproduce on 700d07cf7, I get the proper NullReferenceException. (Antergos Linux, Mono 5.4.1.6)

**Comment by mysticfall** [comment]
Ok, I'll try to create a test project to make see if it wasn't some specific setup I had with my current project that caused the issue.

**Comment by mysticfall** [comment]
I haven't been able to reproduce it for a while too. Probably we could test it again with the latest branch and close it if it's still the case?

**Comment by akien-mga** [comment]
Assuming fixed as per the above. Please comment if you still reproduce it in the current master branch / recent 3.1 builds.
