### ISSUE TITLE
A way to ensure that camera is disabled completely

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#17570]
**Godot version:**
3.0.1

**Issue description:**
I have implemented split-screen in my game by using viewports and additional cameras.  Each player has its own viewport and camera, and even if only one player is playing, his viewport is in use. The problem is that in my game I have more cameras defined (some of them are for debugging, others are used for raycasting). 
I haven't found any way to disable rendering on main game viewport, so in a result one obsolete camera is rendering completely unnecessary:
![disable_cam](https://user-images.githubusercontent.com/6129594/37535662-b54a683c-2948-11e8-9656-8e4e49b394cb.png)
_(split screen is scaled down a little, and below can be seen third camera)_

I was expecting that when I will `clear_current` on the camera it will be disabled. And it's true as long as there is only one camera in the main viewport. If there are more cameras in the main viewport then automatically next one will be enabled (so it's simply impossible to disable them all).

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Unrelated but: Split-screen Multiplayer in RivenTails! This game keeps getting more promising :D
