### ISSUE TITLE
godot -export Android doesn't show any error if not properly configured

### ISSUE THREAD

**Issue by est31** [godotengine/godot#1757]
When you run `godot -export Android` in the command line (only tested headless version), and exporting isn't set up properly, there is no error shown, godot only hangs without doing anything. There should a list of errors like in the export dialog of the editor.

**Comment by est31** [comment]
It only requires to have `android_release.apk` inside `~/.godot/templates`. Its hanging if that file is missing.

**Comment by akien-mga** [comment]
Quoting #1761:

> Fixes parts of #1757. Real error reporting (why it failed) still doesn't happen.

**Comment by est31** [comment]
It prints "Exporting failed!" and exits with a non-zero exit code. This isn't full error reporting like the error reporting happening via GUI.

**Comment by akien-mga** [comment]
Indeed, I just wanted to add this info here :)
