### ISSUE TITLE
WebSocketClient connect_to_url does not connect

### ISSUE THREAD

**Issue by trit** [godotengine/godot#17587]
**Godot version:**

201d2d7226ba4d385ac26e3cfaada180c2a7dacb

**OS/device including version:**

Windows 10 Pro v1709

**Issue description:**

Trying to test out WebSocketClient, nothing happens after calling the connect_to_url. 

**Minimal reproduction project:**

```
extends Node

var ws = null

func _ready():
	ws = WebSocketClient.new()
	ws.connect("connection_established", self, "_connection_established")
	ws.connect("connection_closed", self, "_connection_closed")
	ws.connect("connection_error", self, "_connection_error")
	
	var url = "wss://echo.websocket.org"
	print("Connecting to " + url)
	ws.connect_to_url(url)
	
func _connection_established(protocol):
	print("Connection established with protocol: ", protocol)
	
func _connection_closed():
	print("Connection closed")

func _connection_error():
	print("Connection error")
```

**Comment by bojidar-bg** [comment]
CC @Faless.

**Comment by Faless** [comment]
You need to call `ws.poll()` periodically for the connection to work (e.g. in `_process` or `_physics_process`).

In this case though, I notice that the secure connection is failing (i.e. `ws://echo.websocket.org` works, `wss://echo.websocket.org` does not), I'll be investigating.
It might be a bug due to the switch to mbedTLS

**Comment by trit** [comment]
Okay, adding poll to the _process function did the trick and I'm able to connect to the insecure version now. Want me to open up a different issue for the SSL_new failed error?

**Comment by arvenjadeaguilar** [comment]
What did you do to enable WebSocketClient? When I used it. It says Parser Error: Identifier not found: WebSocketClient 

Using Godot v.3.0.4

var ws =  WebSocketClient.new();

**Comment by trit** [comment]
I built Godot from the dev branch
