### ISSUE TITLE
bugs in signals of ItemList (item_selected) & (item_rmb_selected)

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#17588]
Godot version: 2.1.4 stable & 2.1.5 beta2
OS: Windows 7 x64

**Issue description:**
1) signals of ItemList (item_selected), has an bug - then the signal does not emit if you select the same item again. Even if you changed the tabs and there you selected a new item, and when you return to the previous tab, you can not select the previously selected one, again - (the signal will not be emitted).
2) signals of ItemList (item_rmb_selected), does not work at all, under any conditions.

Steps to reproduce:
0) download, open and run the sample project
1) in the first tab of the list of items, select item # 0
2) check the inscription with the indicator (the line above the tabs) it should become == 0
3) switch to the second tab, select item # 3
4) check the inscription with the indicator (the line above the tabs) it should become == 3
5) go back to the first tab, try again to select item # 0 (this does not work, it will still be equal to # 3 from the second tab)
6) read the commentators in the script, removing the Comments from the code, you can check the rest of the signals.

Minimal reproduction project:
[https://www.dropbox.com/s/vmq1jl6nh2482bl/bug_signals_for_ItemList.zip?dl=0](https://www.dropbox.com/s/vmq1jl6nh2482bl/bug_signals_for_ItemList.zip?dl=0)

**Comment by akien-mga** [comment]
Still reproducible in the current master branch (f148e8ee), attached converted project for Godot 3.1:
[bug_signals_for_ItemList_3.zip](https://github.com/godotengine/godot/files/2392260/bug_signals_for_ItemList_3.zip)

**Comment by Afsar-Pasha** [comment]
@akien-mga Both of them works fine for me. Just make sure that you have enabled both the properties **allow_reselect** and **allow_rmb_select**

**Comment by akien-mga** [comment]
Ah indeed, then this should be made clear in the signals' documentation.
