### ISSUE TITLE
Wrong rect size in GridContainer children

### ISSUE THREAD

**Issue by Faless** [godotengine/godot#17598]
**Godot version:**

`3.0` -> since a6ca62ac7
`master` -> since #15903

**Issue description:**
GridContainer sets incorrect size to its children

**Steps to reproduce:**
Create an empty scene:

- Add a GridContainer
- Set its number of columns to 2
- Add a Control as child of the grid container.
- Set both its size flags to `fill,expand`

The resulting rect size in the child Control is off by 4 pixels

**Minimal reproduction project:**
Notice the `604 px` height in the `Wrong` node
[layout_test.zip](https://github.com/godotengine/godot/files/1822308/layout_test.zip)

**Comment by Faless** [comment]
cc @groud

**Comment by groud** [comment]
That's because the "hseparation" and "vseparation" constants are 2 by default.
But you are right, in your example the space should not be added if there's only one node.
