### ISSUE TITLE
Ctrl+F in the script editor doesn't work if shader editor is open at the same time

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17591]
Godot 3.0.2
Windows 10 64 bits

Repro:
1) Open script editor
2) Open shader editor at the same time to see both script and shader
3) Click in the script editor to focus it
4) Hit Ctrl+F: notice the search doesn't open in the script editor, in the shader editor instead.

Expected: the search should open in the currently focused text editor.

**Comment by reduz** [comment]
@Paulb23 what do you think?

**Comment by Zylann** [comment]
To me that's just a matter of better handling contextual shortcuts. When the keyboard focus is inside the shader editor, I expect shortcuts to work here, no matter the state of the rest of the editor.

**Comment by npip99** [comment]
@reduz The shader editor definitely shouldn't close.

![Screenshot from 2019-10-13 12-35-59](https://user-images.githubusercontent.com/8939474/66718804-1abdfc00-edb6-11e9-8545-454c7215665b.png)

As seen in the screenshot, both the ctrl+f region for the gdscript, and the ctrl+f region for the shader, are both active. So, using my mouse, I can easily select between the two. However, ctrl+f while having the gdscript editor in view should be the same as me clicking that ctrl+f. It would definitely be worse if it simply closed shader while I was working on it. (Also, what if I haven't saved the file yet?)

**Comment by KoBeWi** [comment]
This issue applies to many shortcuts. Some of them will be fixed once #39039 is merged (e.g. Ctrl + D), but the PR still doesn't fix e.g. Ctrl + F and Ctrl + K. We should probably test which shortcuts are affected, which are fixed by the PR and which are still broken.

**Comment by EricEzaM** [comment]
@KoBeWi I think I have fixed #39039 to include resolving this issue now:
![shader_scrpit_editor_ctrl_f_fixed](https://user-images.githubusercontent.com/41730826/90516627-9db69c80-e1a7-11ea-96d7-63b015cac81d.gif)

**Comment by Skaruts** [comment]
I noticed this when trying to comment a line in a script with both editors opened. Seems like sometimes Godot doesn't properly account for which panel is in focus.
