### ISSUE TITLE
Mono System.ValueTuple no longer works in 3.0.2

### ISSUE THREAD

**Issue by PJB3005** [godotengine/godot#17597]
**Godot version:**
3.0.2 official mono

**OS/device including version:**
macOS High Sierra 10.13.3, Mono 5.4.1.7

**Issue description:**
As of 3.0.2 (worked in 3.0.1), attempting to use `System.ValueTuple` in C#. will result in a `System.IO.FileNotFoundException`:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

I should note that compilation passes without a hitch, runtime is the problem.

**Minimal reproduction project:**
[SystemValueTupleGodot.zip](https://github.com/godotengine/godot/files/1822279/SystemValueTupleGodot.zip)

Note: you need to restore packages with NuGet.

**Comment by mysticfall** [comment]
I tried the attached project but couldn't reproduce the issue. I'm using the master branch of Godot (rev.: dad47d8876de45132226985dbbd079e060f6facc) and Mono 5.13.0.302.

**Comment by akien-mga** [comment]
Seems to be 3.0.x specific then, cc @hpvb.

**Comment by PJB3005** [comment]
Trying it on a Windows machine I can't reproduce it in ANY version. I'll have to look into it more.

**Comment by PJB3005** [comment]
Definitely seems to work on a custom build of 3.1 on macOS, so...?

**Comment by akien-mga** [comment]
Well the main question is does it still affect 3.0.2?

**Comment by akien-mga** [comment]
Well the main question is does it still affect 3.0.2?

**Comment by PJB3005** [comment]
Yep seems to affect 3.0.2 on macOS and Windows.

**Comment by hpvb** [comment]
This appears to work on 3.0.3 on my tests

**Comment by hpvb** [comment]
(I did had to delete the .mono and .import directories of the project after running nuget on Windows)
