### ISSUE TITLE
set_render_target_to_screen_rect in Godot 3

### ISSUE THREAD

**Issue by Miminuit** [godotengine/godot#17605]
Hi,
With Godot 3, it seems the `set_render_target_to_screen_rect` function for viewport was removed. Is there any replacement of this function, or any workaround?

I was using this function in Godot 2.x to display my pixel perfect game scaled up by integers values only, and with black bars around the viewport.

**Comment by chanon** [comment]
I wrote an explanation and a complete example for how you can do that in Godot 3.0:

See:
https://github.com/godotengine/godot/issues/6506#issuecomment-373068587
for the explanation, and the comment after it for the full example.

**Comment by volzhs** [comment]
please, use https://godotengine.org/qa/ for questions.

**Comment by Calinou** [comment]
Closing per @chanon's comment.
