### ISSUE TITLE
Exporting array type property does not work in C#

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17601]
**Godot version:**
`master` / dad47d8876de45132226985dbbd079e060f6facc

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
Referencing any property of an array type (i.e. `string[]`, `int[]`, `Vector3[]`) results in either a `NullReferenceException` or crash if the value is entered within the editor.

The following code can reproduce the problem:
```c#
public class ArrayTest : Node
{
    [Export] public string[] Values;

    public override void _Ready()
    {
        base._Ready();

        GD.Print("### Values = " + Values); // This line throws an exception.
    }
}
```
The exception is as follows:
```
System.NullReferenceException: Object reference not set to an instance of an object
  at System.String.Concat (System.Object arg0, System.Object arg1) [0x00014] in /tmp/yaourt-tmp-fender/aur-mono-nightly/src/mono-5.13.0.302/mcs/class/referencesource/mscorlib/system/string.cs:3037 
```

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by mysticfall** [comment]
I tested with 2ff31badaffc again, and now it seems that I don't get any crash but still I'm unable to edit the value. I also found that it happens for other types of properties as well, so I'll update the description.

**Comment by akien-mga** [comment]
Tested in 3.1 beta 6, exporting values seems to work (I can edit them from the editor), but printing them does raise an exception like described in the OP.

**Comment by neikeq** [comment]
I can't believe I left this issue sitting for a year...
