### ISSUE TITLE
Misleading UI when renaming a node with multiple selected

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#17608]
**Godot version:**
3.0.2 (Steam)

**OS/device including version:**
Linux x64; X11; Debian Testing

**Issue description:**
When one has multiple nodes selected in the editor's scene tree, and tries to change the name of them (F2), the *lowest* selected node in the tree displays the text-edit box for entering the new name. However, when the new name is entered, (only) the *first node which was selected* (that which has the border highlight) gets its name changed.

I would expect that either:

a) The text-edit box should display on the *first selected* node; or
b) The node which displays the text-edit box has its name changed; or
c) Preferably, *all selected nodes* have their names changed to the new value (or, for siblings, the usual numeric derivations thereof)

**Steps to reproduce:**
1. Create a new scene
2. Add a root node (any type)
3. Add a child node (any type)
4. Click the root node
5. Ctrl+click the child node
6. Press F2
7. Enter a new name in the text box on the child node

Result: The root node's name changes, and the child node's does not.

**Comment by KoBeWi** [comment]
This could be easily solved by opening the batch rename dialog when multiple nodes are selected.

**Comment by KoBeWi** [comment]
Looks like rename is not available anymore when multiple nodes are selected and using the shortcut has no effect, There's a new Batch Rename dialog, which handles this (and has a separate shortcut).

There's still problem in some cases, but it's part of bigger issue #18787
