### ISSUE TITLE
Support saving PNG while preserving colors under transparent pixels

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17611]
Godot 3.0.2

I am writing a tool to help optimize shaders by packing various channels in R, G, B and A. The problem is, if a value in the alpha channel is zero, the PNG saver might destroys others colour channels. This is really bad in the context of shaders because you may still need them.

This option is supported by the PNG format so I think it would be nice to support it.

**Comment by reduz** [comment]
I don't think Godot does anything in particular to those pixels, but I
would check resource_saver_png.cpp

**Comment by Zylann** [comment]
To my good surprise, it looks like saving a PNG with zero alpha in Godot preserves color channels... nevermind this issue then :)

However this led me to find another corner case issue, I'll post it for the record...
