### ISSUE TITLE
Sprites using alpha for other purposes than transparency are not selectable in these areas

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17614]
Godot 3.0.2

After playing with shader optimization, I noticed that if you create a sprite with a texture having zero values in its alpha channel, you will be unable to select it if clicking on those pixels.
That seems fine for regular sprites where alpha = transparency, but if you use shaders to interpret the alpha channel differently, this is no longer true and can lead to hardly selectable sprite.

This is quite a corner case, but I'll mention it anyways because it caused me a bit of confusion.

**Comment by Calinou** [comment]
@Zylann Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))? Also, is this in the 2D or 3D editor?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
I'm not sure this can be improved, as disabling the feature that prevents from selecting transparent pixels would be a downgrade in usability for the main use case for the alpha channel.
