### ISSUE TITLE
GdNative  - Invalid call. Nonexistent function 'xxxx' in base 'Reference (sqlite.gdns)'.

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#17613]
**Godot version:**

Godot3.0.2 stable

**OS/device including version:**

Windows64 - Desktop - AMD Radeon 7570M

**Issue description:**

I downloaded the GdNative script release from this repository:
https://github.com/khairul169/gdsqlite-native/
And tryed to use it to load resource Data from a database, but when i tryed to load the data (using the resource's _init function on tool mode) i got the error message:
`res://db/persistent_data.gd:26 - Invalid call. Nonexistent function 'open_database' in base 'Reference (sqlite.gdns)
`
I opened an issue in this repository, but i feel this is not related, the function 'open_database' is declared here:
https://github.com/khairul169/gdsqlite-native/blob/master/src/gdsqlite.c#L275

**Steps to reproduce:**
My project is too big to proportionate a minimum example, but here's the script that loads the file:
https://gist.github.com/MarianoGnu/1d615ce634b5bc9bbc35e8ff64df9f59

**Minimal reproduction project:**

**Comment by MarianoGnu** [comment]
Image with the error logs, i tryed many stuff, but at the end it never worked

![imagen](https://user-images.githubusercontent.com/1776044/37568959-1676f42c-2abb-11e8-8c73-09e633f10bc5.png)

**Comment by robfram** [comment]
Never used GDNative, but all the examples I found online had the `onready` keyword in the `preload`.

For example, the original help documentation: [http://docs.godotengine.org/en/3.0/tutorials/plugins/gdnative/gdnative-c-example.html](http://docs.godotengine.org/en/3.0/tutorials/plugins/gdnative/gdnative-c-example.html)
```
onready var data = preload("res://bin/simple.gdns").new()
```

Other tutorials: (https://stackedboxes.org/2017/08/20/trying-out-gdnative/)[https://stackedboxes.org/2017/08/20/trying-out-gdnative/]
```
# Load the class itself from the NativeScript
onready var Averager = preload("res://averager.gdns")
```

**Comment by MarianoGnu** [comment]
yes, but Resources are not nodes and have not a "_ready" function, that's why i used call_deferred instead to make sure objects where initialized, but this even't woudn't matter, because when i press ctrl+alt+s to save the script it's reloaded, and the error appears again, even thought the native script should be completely loaded long ago.
I suspect it has to do with Native Scripts not being loaded on editor, and the game crashes if i run the game (not sure if related)

I'd like to debug myself, but since my linux distro broke i can't compile godot (or the native script itself)

**Comment by bruvzg** [comment]
This module is outdated and use functions removed in #15580 (`godot_string_new_data`, `godot_string_new_data` and `godot_string_get_data`).

**Comment by MarianoGnu** [comment]
thx, i'll comment it on the module's issue
