### ISSUE TITLE
Inspector with a MultiNodeEdit switches to show a single node after "play" or "stop"

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#17610]
**Godot version:**
3.0.2 (Steam)

**OS/device including version:**
Linux x64; X11; Debian Testing

**Issue description:**
If multiple items are highlighted in the scene tree, and thereby the inspector shows a MultiNodeEdit, playing the scene or project (or stopping one already running) causes the inspector to change to show the settings for only a single node (that which has the border highlight).

Fortunately, going back one step in the inspector history allows one to quickly return to the previous MultiNodeEdit.

**Steps to reproduce:**
1. Load or create any scene with more than one node
2. Select multiple nodes in the scene tree
3. Observe that the Inspector is displaying a MultiNodeEdit
4. Click "Play Scene", or press F6
5. Observe that the Inspector is no longer displaying a MultiNodeEdit

**Comment by Calinou** [comment]
I can't reproduce this in 3.2.1, so I'll assume this issue has been fixed since. Please comment if you can still reproduce this.
