### ISSUE TITLE
Can't override editor font margins in a plugin

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17626]
Godot 3.0.2

I designed some GUIs for my plugin, but it looks like some options I've set in box and grid containers `custom constants` seem to be overrided by the editor's theme. This causes my UI to break in multiple ways.

In edited scene and in game testing, my UI looks like this:

![image](https://user-images.githubusercontent.com/1311555/37573651-87153f90-2b1a-11e8-9ff5-d3db616db21c.png)

In the editor, it looks like this:

![image](https://user-images.githubusercontent.com/1311555/37573656-926d06ac-2b1a-11e8-8c63-e9d63564732d.png)

**Comment by Zylann** [comment]
Still the case in Godot 3.1 alpha2.

![image](https://user-images.githubusercontent.com/1311555/48958332-23b39e00-ef56-11e8-9147-098cc6aa4dc1.png)

Addon:
[zylann.channel_packer.zip](https://github.com/godotengine/godot/files/2611559/zylann.channel_packer.zip)

**Comment by KoBeWi** [comment]
I tried to test the project in 3.2.2 rc1. It threw lots of errors on startup which I ignored, but then the dialog appeared fine.

@Zylann Can you confirm it's fixed or provide a better MRP?

**Comment by Zylann** [comment]
@KoBeWi the dialog appears fine now because I replaced text with icons.

**Comment by KoBeWi** [comment]
Then MRP with `project.godot` and the plugin, that you can actually run and see the bug, would be useful.

**Comment by Zylann** [comment]
I believe it's not a bug actually. `GridContainer`s spacing constants are respected, the problem comes from the font itself. I had this happen in another UI, and even if I can add negative margin, it's pointless to do it because the font could be changed by DPI or user customization.

Now it certainly makes it harder to design editor UIs when the theme in which you make them uses a different font, but I don't know if something can be done about that.

The archive I had linked in my previous post is the plugin folder only. I just tried it in 3.2.2 rc1, but it doesn't throw errors for me (probably because I replaced the plugin in my test project so resources were imported already, see maybe https://github.com/godotengine/godot/issues/17483).
Here it how it looks:
![image](https://user-images.githubusercontent.com/1311555/84837556-550c2700-b030-11ea-9bd9-0673ef7ffa55.png)

And this is how it looks with the version from the asset library, now with icons:
![image](https://user-images.githubusercontent.com/1311555/84837607-710fc880-b030-11ea-8ae0-4fb6a409580c.png)

**Comment by KoBeWi** [comment]
> it's pointless to do it because the font could be changed by DPI or user customization.
Now it certainly makes it harder to design editor UIs when the theme in which you make them uses a different font, but I don't know if something can be done about that.

The editor somehow deals with that problem, so it may be some missing functionality for plugins (if I understand correctly), which would be a matter for a proposal.

So this issue can be closed then?

**Comment by Zylann** [comment]
Yes I think it can be closed.
