### ISSUE TITLE
Instancing EditorFileDialog in a game ran from the editor crashes the game

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17624]
Godot 3.0.2

`EditorFileDialog` is an available class in GDScript.
However, if you try to instance it within a game ran from the editor, it will crash and the debugger will give you no info. The console doesn't give errors either.
While it's obvious the class is editor-only, I expected some feedback from the editor to tell me what's wrong.

**Comment by willnationsdev** [comment]
Should we perhaps add something to the ClassDB that examines the API currently in use? Not sure if that's quite how it works, but...checking that the API is set for the editor when instantiating Editor-classes and reporting an error if it's not the case might be a good idea. But I get the feeling that the ClassDB isn't really the right place for that...

**Comment by Zylann** [comment]
IMO if an entire class can't be used ingame, its symbol should just be null and result in either a parsing error, or null exception.

**Comment by willnationsdev** [comment]
I feel like that might be doable in the gdscript compiler, but I'm not sure if removing the typenames altogether (for a parse error) is the best idea. If you checked `Engine.is_editor_hint()` in `GDScriptLanguage` and prevented `Editor*` classes from being added to the globals array in the first place, then people wouldn't be able to use the same script to conditionally access Editor classes when `Engine.is_editor_hint()` is true. So, it'd have to be the "returns null" solution in that case. And that might still be relatively easy to do.

**Comment by neikeq** [comment]
@willnationsdev ClassDB already differentiates between Core and Editor types:

https://github.com/godotengine/godot/blob/b384bf6fbccd831f597ce8342df32b57485ed656/core/class_db.h#L217

**Comment by willnationsdev** [comment]
Well, I know it understands the API associated with each type. I'm just not sure how the API gets factored into anything currently. GDScript just accesses the class list from the ClassDB and adds them all to the globals array, but neither the `GDScriptLangauge::init()` method nor the `ClassDB::get_class_list()` seem to take a class's API into account. So that seems to be the change that would be needed.
