### ISSUE TITLE
Save Branch as Scene -> Overwrite existing scene -> Open the scene and it is still the old one

### ISSUE THREAD

**Issue by NikodemL** [godotengine/godot#17628]
**Godot version:**
Godot 3.0.2 64 or 32 mono or gdscript

**OS/device including version:**
Window 8.1

**Issue description:**
In the scene view you save a branch to an existing scene file and you overwrite it.
Next you open up the scene file to which you saved to. Godot opens the OLD scene file.
If you close godot and restart the scene file contains the new nodes.
So it seems that when you overwrite a scene file, something is not reloaded.

Video example of the bug:
https://youtu.be/dL1uLqKP0KE

**Steps to reproduce:**
1. Save Branch as Scene
2. Choose an existing scene to overwrite.
3. Open the "new" scene and see that it is still the old one

**Comment by Zireael07** [comment]
I did that a couple of times yesterday (to change root node type) and I am seeing the new scene at step 3...

**Comment by NikodemL** [comment]
I made a video that should better describe the issue
https://youtu.be/dL1uLqKP0KE

**Comment by Applemann** [comment]
I have the same problem on my Ubuntu 16.04.3 LTS
I was saving branch overwriting existing scene but there was still the old.
After remove old and create new scene from branch it was right..

**Comment by reduz** [comment]
closed by accident
