### ISSUE TITLE
Lack of Shadows with custom light shader

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot#17627]
Godot 3.0
Windows 7 | Intel HD 4400

**Issue description:**
I am creating this volume shader to be uploaded in the asset store but after I was finished with the light shader, I realized one crucial detail. The volume is not affected by shadows anymore. I am not sure whether this a bug or a design choice, but it's there.

**Comment by JFonS** [comment]
You need to take into account the ATTENUATION built-in. It takes care of both distance attenuation and shadows. 
[http://docs.godotengine.org/en/3.0/tutorials/shading/shading_language.html#light-built-ins](url)

**Comment by SIsilicon** [comment]
Oh I thank you for that piece of info. That should really be part of the docs.
Hey! Maybe I should do just that. I'm going to read on how to update the docs and fill in the "missing blanks".
Again thank you. My volume renderer plugin is going to be sweet.
