### ISSUE TITLE
Dialogs in project manager don't consume Enter key, runs project instead of confirming input

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#17620]
**Godot version:**
`master` branch commit 883afd1b4d6886676ceb2017caafae0c24df6c24

**OS/device including version:**
Arch Linux

**Issue description:**
Typing the path of a project to import it, and then pressing enter does not always yield the same behavior.

**Steps to reproduce:**
1. Open Godot's project list.
2. Click on a project to select it
3. Click Import
4. Type the path of a project to import it (the path doesn't need to exist)
5. Press enter

Godot now runs the project that was first selected.

If the same steps as above are repeated, but step 2 gets omitted, pressing `Enter` after typing the path does nothing.

I expected Godot to import the project, or at least to have the same behavior on both cases.

**Comment by reduz** [comment]
This is likely in the FileDialog class (which is what project manager uses, not EditorFileDialog)
https://github.com/godotengine/godot/blob/master/scene/gui/file_dialog.cpp

**Comment by Rubonnek** [comment]
I'll take a stab at this soon

**Comment by Rubonnek** [comment]
If there's someone out there who wants to tackle this, feel free.

A lot of work suddenly stacked on me and I haven't been able to work on this. I don't think I will be able to for a while either.

**Comment by lupoDharkael** [comment]
I think I understand what's happening here.
When you open the Import dialog it gives focus to the "Import & Edit" button, the path is not correct so the button starts disabled. When you press Enter the button is disabled so it can't handle de input so it executes here:
https://github.com/godotengine/godot/blob/master/editor/project_manager.cpp#L998

Should we modify how this popup dialog handles the input, or control that input case in the project_manager itself?

**Comment by aaronfranke** [comment]
Ideally, I think that all keypresses should be captured and sent to the dialog box when a dialog box is open, like @pedroalopes says. You shouldn't be able to touch the rest of the window while one is open.

**Comment by KoBeWi** [comment]
Somewhat related to #17580
