### ISSUE TITLE
Error spam when opening a scene with a Line2D

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17625]
**Godot version:**
883afd1

**Issue description:**
When opening a scene with a Line2D with points (an empty one doesn't trigger it), this error will be spammed multiple times in the output:
`Drawing is only allowed inside NOTIFICATION_DRAW, _draw() function or 'draw' signal.`

**Comment by robfram** [comment]
Couldn't replicate in ebce36c22f1aa27e3ef449565bf1e35c19a3e830. Could you provide a sample project where it occurs?

**Comment by Noshyaar** [comment]
I can't reproduce either. Same version.

**Comment by YeldhamDev** [comment]
@robfram @Noshyaar
[Test.zip](https://github.com/godotengine/godot/files/1826796/Test.zip)

**Comment by volzhs** [comment]
can't reproduce with the attached sample project.
I'm using 201d2d722

```
$ godot3 -e --path ~/Desktop/Test
OpenGL ES 3.0 Renderer: GeForce GTX 670/PCIe/SSE2
// when run
Running: /mnt/2TB/Godot/Godot 3/godot.tools.64 --path /home/volzh/Desktop/Test --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 29064 --position 0,0
OpenGL ES 3.0 Renderer: GeForce GTX 670/PCIe/SSE2
```

**Comment by robfram** [comment]
Me neither. Only this output:
```
Running: /godot/bin/godot.x11.tools.64.llvm --path /tmp/Test --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 3585 --position 171,84
Remote Debugger: Connection failed with status: '2', retrying in 1 msec.
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile 
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1989.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1989.
```

**Comment by Phoenix1747** [comment]
Not happening on 3.0.2 either, not even any warning.

**Comment by YeldhamDev** [comment]
Whatever was triggering this warning for me, doesn't seem to happen anymore. So yeah, closing it.

**Comment by letheed** [comment]
Just hit what seems to be the same bug with a tool script drawing lines.

It goes away if I edit `.config/godot/projects/MyProject-###############/editor_layout.cfg` and remove the scene loading the script from `open_scenes`.

If I open godot and open the scene manually and all is fine.

The error spamming seems to happen on startup. Obviously the script runs but `drawing` is false even in the `_draw` call for a short while.
