### ISSUE TITLE
body_enter sometimes don't report contact collisions

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#1762]
I made this project to show the bug.
https://github.com/guilhermefelipecgs/bug_in_body_enter

When the rigid body collide with the static body, rigid body is destroyed, but sometimes fails.

His problem happens when I move the character and he collides first with the "wall " and then with the "ground" in a short time.

**Comment by Ace-Dragon** [comment]
It looks like this was fixed already and should be in the beta 2 release when it comes out
https://github.com/okamstudio/godot/commit/79d5b7f2580e5da87d8c962558517d7cc65fdf45

**Comment by guilhermefelipecgs** [comment]
I tested now with de branch master and this problem is gone.
I will close this issue.

**Comment by deniscomtesse** [comment]
I have encountered this bug in 2.0 alpha (the most recent nightly build) using areas with (3D) rigid and static bodies.
It can easily be reproduced by letting identical cubes with a simple box area repeatedly fly into a static body - sometimes the contact is reported, sometimes it isn't.

**Comment by akien-mga** [comment]
Could you provide a test project that reproduces the issue?

**Comment by deniscomtesse** [comment]
Sure, here's a simple project: https://dl.dropboxusercontent.com/u/1891681/AreaTest.zip

**Comment by deniscomtesse** [comment]
By the way, something I noticed in a bigger project: Whenever an area fails to report a collision, it fails to report future collisions as well, and generally behaves as if it had no collision shape. But it's completely unpredictable. I'm instancing a couple of identical objects, and it only fails for some.

**Comment by volzhs** [comment]
I had same experience.
the collided object is contacted(body enter) "A object" and bounced to somewhere,
but I couldn't hear contact information(body enter) with "A object", just bounced somewhere.

**Comment by akien-mga** [comment]
I can reproduce the bug in the current master branch using the project included above.

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by ProbDenis** [comment]
I haven't encountered this bug in 3.0, and I'm using the body_enter signal a lot.
