### ISSUE TITLE
Add method to get notification when AnimationPlayer actually advances frames

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17623]
**Godot version:**
`master` / dad47d8876de45132226985dbbd079e060f6facc

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
When working with animations, it is sometimes needed to know exactly when a frame is processed. Some of the more common use cases can be such tasks as performing IK calculations, handling 'root motions', or applying morphs.

Unity provides various ways to do this, including `OnAnimatorIK` 'magic method' in 'MonoBehavior's.

Currently, the only possible way to achieve this in Godot is to set `PlaybackActive` property to `false` and manually advancing frames using `Advance` method. But it's cumbersome and even more so when it is driven by `AnimationTreePlayer` in which case you need to disable auto play for both `AnimationPlayer` and `AnimationTreePlayer` then manually advance the latter.

It'd be better if there is a signal or an overridable method that is invoked when frames are actually processed regardless of how - setting `PlaybackEnabled` to true, manually invoking `Advance()` or driving it with a `AnimationTreePlayer`, or else.

**Comment by RabbitB** [comment]
This can be accomplished (although maybe more cumbersome) by making use of method tracks. You can use them to either call a custom method or emit a signal at pre-determined frames.

If you find manually adding method call keys to your animation too cumbersome, it shouldn't be too hard to write a custom node, which when added as a child of an AnimationPlayer, automatically adds the relevant track and keys at frame numbers you specify.

**Comment by mysticfall** [comment]
Theoretically, it can be a workaround for the problem, but for all practical purposes it can't be used in such a situation.

If I were to use such an approach, it'd mean adding a method track for every animation (in my case, there are 8 animations per a single strafe set), and adding a key for each frame (67 frames per animation) which makes total additional 536 keys just for the walking/running animation for one character. And I need to do this everytime when I reimport animations from Blender too.

I can see how there might be some way to automate this process but I believe we shouldn't really force our users to resort to such a workaround for doing such common tasks like implementing IK and such.

**Comment by reduz** [comment]
Animation players have a process mode where you can set fixed or idle (to sync to either mode).
Maybe adding an extra mode which is manual, where you call a function to advance the time would work?

**Comment by mysticfall** [comment]
Sure, that would work perfectly for my case :)

**Comment by merumelu** [comment]
Manual mode for AnimationPlayer and AnimationTree was added in #20665. This can be closed, no?

**Comment by akien-mga** [comment]
Indeed, fixed by #20665.
