### ISSUE TITLE
In ViewportTexture for Sprite3D RichTextLabels and LineEdits do not render (regression from #16707)

### ISSUE THREAD

**Issue by Grosskopf** [godotengine/godot#17635]
**Godot version:**
master as of ebce36c22f1aa27e3ef449565bf1e35c19a3e830

**OS/device including version:**

Windows 10
i7-6700
GTX 1080

**Issue description:**

Using the Button Node is the only way currently to render Text in 3D

**Steps to reproduce:**

Add a Sprite3D with a Viewport texture, in this Viewport texture add a node like RichTextLabel, Label or LineEdit, notice that it does not Render on the Sprite3D while a button gets rendered

**Comment by volzhs** [comment]
can you provide a sample project?

**Comment by Grosskopf** [comment]
yes, it'll be ready in 5 minutes :)

**Comment by Grosskopf** [comment]
oh, i'm unsure how but now the label gets rendered in the demo project, sadly i can't share my original project, but the richtextlabel and the lineedit don't

**Comment by Grosskopf** [comment]
https://nextcloud.grosskopfgames.de/s/2KxH6cBiJJodWya

**Comment by volzhs** [comment]
you can attach it directly on here by dragging and dropping. :)

**Comment by Grosskopf** [comment]
oh, i never tried that ^^ will do next time :)

**Comment by ShyRed** [comment]
Turning off `V Flip` makes the Label and RichTextLabel appear:

![2018-04-09_18-50-58](https://user-images.githubusercontent.com/1138805/38511014-06230b74-3c27-11e8-817e-f11abf2afbca.gif)

**Comment by ShyRed** [comment]
Commit #973be371 messed up the rendering of viewports. Reverting the commit restores the behaviour shown in the gif.

**Comment by reduz** [comment]
Sorry, I had to revert the PR before this one on the same file. It needs to be fixed before this can be merged.
