### ISSUE TITLE
Hotkey CMD+left/CMD+right must navigate to the beginning/end of text

### ISSUE THREAD

**Issue by ziomio** [godotengine/godot#17631]
**Godot version:**
3.0.2

**OS/device including version:**
Mac OS X 10.13.3 High Sierra

**Issue description:**
ANYTHING text-related in Mac OS X uses this shortcut [CMD+left arrow] to navigate to the beginning of line of text and [CMD + right arrow] to navigate to the end of line. In fact I am using them right now in this textbox, but when I double-click for example in Node in Scene browser to rename it those CMD combinations does not work and I am forced instead to use ALT+left/ALT+right combinations which drives me crazy :)

**Comment by KidRigger** [comment]
I'll take a look at this. I have OSX.

**Comment by KidRigger** [comment]
Seems that when Command is held down, the LineEdit doesn't even enter into the KEY_RIGHT case here. 
https://github.com/godotengine/godot/blob/1c419531a009f48aa074f9b5f93b98d387c33723/scene/gui/line_edit.cpp#L338
And instead goes in this if block, where the case handling right key doesn't exist. 
https://github.com/godotengine/godot/blob/1c419531a009f48aa074f9b5f93b98d387c33723/scene/gui/line_edit.cpp#L137

Adding the right key and left key to the L137 if block will cause it to allow CTRL usage analogous to CMD, which can be avoided. Should we allow CTRL usage, or should I just add the case for MacOS?

**Comment by ziomio** [comment]
I would prefer CMD button on Mac OS X.
