### ISSUE TITLE
Questions on plugin / extension system

### ISSUE THREAD

**Issue by guoboism** [godotengine/godot#1763]
On the wiki, there is a slashed "Editor Plugin"
Does it means the feature exist now? 

How does the plugin system work?

The Plugins you planned exist as c++ codes and need compile? Or as gdscript executed at runtime(like Unity)?

The Godot editor is distributed in a single exe file (win64 for example). Without exposing the inner file structure, where to put those plugin files?

I would like to create an extension, to export objects on stage to a file,maybe xml, for use in other game engine. (Godot will only be a scene editor  in this workflow). Can I do that？ How can I do that?

**Comment by volzhs** [comment]
http://www.godotengine.org/wp/community/
There are communities for asking something, facebook, forum, IRC.

**Comment by reduz** [comment]
there is a plugin/extension system but it needs cleanup and documentation.
This work will happen in Godot 1.2 (1.1 should come out soon)

**Comment by TheHX** [comment]
I've used a lot the current plugin system, and i created a [tool](https://github.com/TheHX/add_primitives) with it.

And i only did it because i know how read a C++ code, and i learned how the system works, and how is hard to use it, because it miss cannot access several editor related functions.

**Comment by reduz** [comment]
yeah, it's not on purpose that you can't access them, but more like I have
no idea what kind of functions are needed.
the idea for 1.2 is to try working on figuring out which kind of APIs are
required for plugin developers

**Comment by TheHX** [comment]
I hope help with this matter in the future.
