### ISSUE TITLE
[Mono] Unable To Find Camera Class Methods

### ISSUE THREAD

**Issue by Supatier** [godotengine/godot#17647]
**Godot version:**
3.0.2

**OS/device including version:**
Manjaro Linux 64

**Issue description:**
I wanted to set the FOV of my 3D camera, but ```'Camera" does not contain a defenition for 'Fov and no extention method 'Fov''```
This also happens to all Camera class methods and property `ProjectRayNormal`, `ProjectRayOrigin` and others. Visual Studio Code code assist only lists Spatial class methods and property, no Camera.

**Steps to reproduce:**
``Camera myCamera = (Camera)GetNode("FrontCamera");
myCamera.Fov = 10; ``

**Comment by mysticfall** [comment]
I can't seem to reproduce the problem. I suspect it could be a problem specific to your development environment. Have you tried to delete everything in `{{your project}}/.mono` and `~/.local/share/godot/mono` and rebuild?

If the problem still persists, you can check if the generated `Camera.cs` under the latter directory to see if it has all the members that are defined by the API.

**Comment by Supatier** [comment]
> Have you tried to delete everything in {{your project}}/.mono and ~/.local/share/godot/mono and rebuild?

Yes

> generated Camera.cs

Where is it?
![mono](https://user-images.githubusercontent.com/19777767/37638243-6992acf8-2c3e-11e8-822b-1c98fa9f5cdb.png)
The error `'Camera' does not contain a definition for 'Fov' and no extension method 'Fov' accepting a first argument of type 'Camera' could be found (are you missing a using directive or an assembly reference?)`

**Comment by mysticfall** [comment]
The generated source can be found in `~/.local/share/godot/mono/solutions/GodotSharp_-*/ObjectType`.

By any chance, have you any other class named `Camera` somewhere in your project? The only possible cause I can think of could be something similar to such a situation, if your `.csproject` has a correct reference to `GodotSharp.dll`.

**Comment by Supatier** [comment]
> other class named Camera somewhere in your project

Actually, i do. I didn't think they will conflict.

**Comment by mysticfall** [comment]
Mystery solved :)

**Comment by neikeq** [comment]
This is why I commented on #17388 that I would at least display a warning when naming a script the same way as a built-in type. It's too easy to make this mistake since it's the default name for nodes, and most of the times (if not all) you don't want that.
