### ISSUE TITLE
Paricles2D (world space) ignore scale

### ISSUE THREAD

**Issue by brendor** [godotengine/godot#17641]
**Godot version:**
3.0.2

**OS/device including version:**
Linux Mint 17 (64 bit)

**Issue description:**
In Godot 2, it was possible to flip the whole particle system even if emitting in world space by scaling the node (-1, 1) to flip horizontally. Now it only works for local space particles. I believe this is expected,
because world space ignores the transform altogether,  however there is no other way to flip the particles. Maybe an additional flag?
Can be worked around using a custom shader but this should be a built-in functionality I believe.

**Steps to reproduce:**
In the attached project, check the 4 systems, local one is flipper properly using scale,
the world one is not.

**Minimal reproduction project:**
[particles2D_repro.zip](https://github.com/godotengine/godot/files/1827178/particles2D_repro.zip)

**Comment by bmarzins** [comment]
I would be happy simply with a flip_v and flip_h setting for Particles2D, to flip the particle textures. I'm trying to make shadow images follow an AnimatedSprite around, using the same textures. But I can't flip the particle textures in the same way I can flip the sprite textures.

**Comment by theboyboy** [comment]
It seems that scaling a particle node while using global coordinates on the particles will scale every value on the particles except their actual size. For example, if using a box or sphere emission shape, it will scale the extents/radius of the shapes, and things like initial velocity, spread, etc are also scaled.

**Comment by KoBeWi** [comment]
Still valid in 3.2.3 rc4

**Comment by brendor** [comment]
Seems like noone else is going to look into this, so I might do it when I have time. This could be a more complex issue, due to what @BanchouBoo said. It should be consistent and all (including scale) or none attributes should be affected by the transform. The original issue I reported would be fixed by adding a flip flags, just like the ones Sprite has.

**Comment by KoBeWi** [comment]
@brendor Particles are getting a complete rework in 4.0, so I'd wait until they are finished. Unless you want it fixed for 3.2.x

**Comment by KoBeWi** [comment]
Yes, it works in Godot 4.
