### ISSUE TITLE
output to multiple render targets, screen space shader

### ISSUE THREAD

**Issue by cheece** [godotengine/godot#1764]
to implement things like screen space subsurface scattering https://www.youtube.com/watch?v=NOeOGrNQTCs

**Comment by reduz** [comment]
that's all planned for 1.3, current renderer is GLES2, which is quite
limited, 1.3 will see the
renderer ported to GLES3 or Vulkan

**Comment by reduz** [comment]
this is not yet allowed (actually might never will), though you can now use subsurface scattering
