### ISSUE TITLE
"Replace all" doesn't replace all

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot#17649]
**Godot version:**
3.0.2.stable.custom_build (from [Arch AUR](https://aur.archlinux.org/packages/godot/))

**OS/device including version:**
Arch Linux.

**Issue description:**
Sometimes, the Replace All function in the script editor doesn't replace every occurrence.

**Steps to reproduce:**
This seems to be a bit fiddly to reproduce, but the following steps did it for me:

* Create a new file in the script editor, called `test.gd`, using the Empty template.
* Type `foo foo`.
* Hit Ctrl+R to bring up the replace bar, type `foo`. Note that both occurrences get highlighted (correct).
* Hit Tab, type `FOO`, hit Tab, hit Tab, hit Enter to trigger the Replace All button.

Expected: the text now reads `FOO FOO`.

Actual: the text now reads `foo FOO`. Only the second occurrence has been replaced.        

**Minimal reproduction project:**
n/a

**Comment by akien-mga** [comment]
I can indeed reproduce the bug with the steps provided, though not in a more "natural" scenario (e.g. trying to replace `draw` by `DRAW` in a script calling `draw_polyline` several times).

With
```
foo foo
```
the bug happens reliably.

With
```
foo foo
foo
```
the bug happens every other time...

**Comment by willnationsdev** [comment]
hazarding a guess that it may have something to do with newlines? It affecting only the last item in a given line? I don't know. Haven't looked at the source code for it.

**Comment by bigwebsite** [comment]
With a quick look at the file code_editor.cpp, seems the problem resides in the break logic for the while loop in the function `FindReplaceBar::_replace_all`
I threw in a bit of dirty fix, but the bug stops reproducing with the following break statement: 
`Point2i line_begin(0, 0);`
`if (match_from != line_begin && match_from < prev_match) {
	break;
}
else if (prev_match == line_begin)
{
	break;
}`
Not worth a commit IMO, but definitely a start
