### ISSUE TITLE
OS.get_virtual_keyboard_height() needed on 2.1

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#17652]
2.1 allows showing and hiding the virtual keyboard on mobile devices, but the appearing keyboard covers 60% of the screen, covering whatever the text is being written to. To adjust for the newly restricted screen space, the size of the virtual keyboard is necessary.

This functionality is present in 3.0 in the form of "OS.get_virtual_keyboard_height()"
It would be great to have the feature ported to 2.1, considering it is still the better option for mobile games.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
