### ISSUE TITLE
Display a proper error when trying to load a font inside _draw()

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#17657]
I had encounter the same issue as these two persons of trying to load the font resource on the draw_string() function. There was no proper error on the editor that told me that I was doing something wrong, instead the terminal was vomiting a thousand error messages. 

https://github.com/godotengine/godot/issues/15023
https://github.com/godotengine/godot/issues/9024

I think that the editor should prevent you from running that code because otherwise it can be hard to track down the bug. The error message in the terminal does not point you to the load issue.

**Comment by akien-mga** [comment]
I'm not sure anything can be done at the engine level for this. Instead, I suggest making it clear in the documentation for CanvasItem's `_draw` that any resource used in `_draw` should be created outside it, otherwise it will be deleted when going out of scope before the draw call actually happens.

**Comment by coppolaemilio** [comment]
RIP this issue. It is really badly reported by today's standards, and it seems like no one uses this workflow, so 👋

**Comment by Calinou** [comment]
This works as of Godot 4.3, likely because of DynamicFont -> FontFile refactoring (there is no longer an intermediate DynamicFontData resource).

**Testing project:** [test_draw_font.zip](https://github.com/user-attachments/files/18024486/test_draw_font.zip)
