### ISSUE TITLE
Update android manifest permission template

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#17655]
**Godot version:**
- 2.1: https://github.com/godotengine/godot/blob/2.1/platform/android/AndroidManifest.xml.template
- 3.0: https://github.com/godotengine/godot/blob/3.0/platform/android/AndroidManifest.xml.template
- 3.1: https://github.com/godotengine/godot/blob/master/platform/android/AndroidManifest.xml.template

**OS/device including version:**
Android with latest SDK

**Issue description:**
Permissions are not updated. For example **Read User Dictionary** permission require a signature level (by OEM). So checking this permission leads to a random crash.

A link to the updated permissions (normal level):
https://developer.android.com/reference/android/Manifest.permission.html

**Comment by hpvb** [comment]
This is no longer relevant as we've changed the way the android export works.

**Comment by xsellier** [comment]
Linking to the article that helps user to find a solution to this problem:
https://godotengine.org/article/fixing-godot-games-published-google-play

Sorry for necrobump
