### ISSUE TITLE
Viewport 'update mode: when visible' should take into account scenario when its texture is a parameter of a shader material

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#17651]
**Godot version:**
3.0.2

**OS/device including version:**
Ubuntu 17.04 gpu: nvidiaGTX1060

**Issue description:**
I was trying to push ViewportTexture as parameter to the shader and had a lot of problems which were described in this issue: https://github.com/godotengine/godot/issues/17593
The root of those problems was the fact that Viewport was not rendering when its texture is a uniform parameter of a shader material. 
It can be easily fixed with the change of `ViewPort.update mode:` node to `Always`. 

**Steps to reproduce:**
1. Create new scene with `Node`type and  'World' name as root
2. Add `TextureRect`, load `texture` property (godot icon might be used) and select `expand` option
3. Add `Viewport` node to  'World', set it's size to match window size
4. Add `Camera` node to `Viewport`
5. Add some 3d elements to 'World' node so camera will have something to render
6. Create new shader material in `TextureRect` and attach this shader:
```
shader_type canvas_item;
uniform sampler2D first : hint_albedo; 
void fragment(){
	COLOR.rgb = texture(first,UV).rgb;
}
```
7. Create new script in World and attach this code:
```
func _ready():
	var text = get_node("Viewport").get_texture();
	get_node("TextureRect").material.set_shader_param("first", text);
```
8. Run the scene and observe black background

**Minimal reproduction project:**
[ViewportShaderTest.zip](https://github.com/godotengine/godot/files/1822111/ViewportShaderTest.zip)

**Comment by AssjackGames** [comment]
Author of #16006 here,
I have found that if you need a quick work-around you can send one viewport to the shader if you use the main texture, i.e.:
`COLOR = texture(TEXTURE, UV);`

seems to work. The viewport texture must be assigned in-editor though, setting it up through code (gdScript) did not work.

**Comment by kubecz3k** [comment]
@AssjackGames thank you for the input. I'm actually sending many viewports to the shader, in the end basically all I needed to do was to set `ViewPort.update mode:` to `Always`. (also material is checked as local to scene)

**Comment by reduz** [comment]
Is this still a problem? I remember fixing something related to this.

**Comment by prominentdetail** [comment]
> Is this still a problem? I remember fixing something related to this.

Doesn't seem to work in 4.0 
v4.0.beta.custom_build [0b958971f]
