### ISSUE TITLE
touchScreenButton should emit released when deleted

### ISSUE THREAD

**Issue by honix** [godotengine/godot#1765]
After touchScreenButton.queue_free() + hold button, godot is still emitting press signal

https://yadi.sk/d/3VxvO2RNgLTn8 (here is apk and problem project)

ps - 25 april build (1.1beta1 templates)

**Comment by reduz** [comment]
you mean it should emit released if the button is deleted?

**Comment by honix** [comment]
I think it will.

My scenario is little more sadly. The restart-button remove whole scene and itself ofcourse. Then when this scene loads again button automaticly pressed.

I make strange solution of making animation that pose button off screen when it pressed. *^*

**Comment by neikeq** [comment]
Any update on this? Looks like a straightforward fix if it's considered a bug.

**Comment by Shin-NiL** [comment]
I think it's already fixed.

**Comment by akien-mga** [comment]
Might have been fixed e.g. by recent changes from @RandomShaper.

**Comment by RandomShaper** [comment]
Indeed. :)
