### ISSUE TITLE
Exported android app crashed when trying to split screen

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#17654]
**Godot version:**
(2.1 branch) 940bab27345b5ec8283b8da52bda5c5e272784b6

**OS/device including version:**
Nokia 6 -Android Oreo (tested on 2 differents nokia 6)

**Issue description:**
When splitting the screen, it crashes

**Steps to reproduce:**
1. Create an empty project
2. Export it to your phone
3. Launch it
4. Use the split screen feature of your phone (android 8.0 native feature)

**Logs**
https://pastebin.com/haVmHQcZ

**Comment by freemanfromgodotengine** [comment]
I don't have an access to Android 8.0, but on my 6.0.1 split screen works only with the apps that support it. Those apps have a special two rectangles icon on the right side of the title bar. Other apps don't have it and can't be used in split mode. Is it not the case with the "default" apps created with Godot? By default I mean default manifest file and other android related files.
Or is Android 8 supporting all apps in the split mode no matter what?

Anyway, afaik (and I'm far from being a programmer), even when writing the app with java for android or kotlin, you need to set more than a few things like android:resizeableActivity, android:supportsPictureInPicture in the manifest file and also some layout attributes of the activity like android:minHeight, android:minWidth, and few other that control the way the app behaves when in multiwindow mode. Have you check those things?

**Comment by xsellier** [comment]
@freemanfromgodotengine Thank you for this clue. I checked [this page](http://www.techjini.com/blog/multi-window-split-screen-android/). Meaning by tomorrow I will try to export my app with `android:resizeableActivity="false"` in the manifest. I will update this ticket, and create a PR if it works properly !
