### ISSUE TITLE
Can't load PNG file into ImageTexture

### ISSUE THREAD

**Issue by sprite-1** [godotengine/godot#17650]
**Godot version:** 3.0.2

**Issue description:** The ImageTexture only accepts resource files instead of being able to take in regular images.

**Steps to reproduce:**
1. Create a WindowDialog node.
2. On the property inspector, try to add a Custom Icon for the close button.
3. Select "New ImageTexture"
4. Open the blank ImageTexture
5. Try to load a regular image file (you won't see it because only resources are accepted)

**Comment by Zylann** [comment]
Step 3) can be done differently, which would actually solve your problem:
instead of "New ImageTexture", click "Load", and you will be able to use any PNG from your project.
It won't be an ImageTexture though, but a StreamTexture.

**Comment by sprite-1** [comment]
If I do that the close button icon doesn't change. So I looked at the default theme for Godot 3 and it used ImageTexture so I put two and two together and figured I need ImageTexture too.

**Comment by Zylann** [comment]
That's even weirder... why would a StreamTexture make any difference?

**Comment by sprite-1** [comment]
Are you able to reproduce the issue of not being able to change the WindowDialog close button with an image?

**Comment by Zylann** [comment]
I can't launch Godot right now but I can try to repro later

**Comment by sprite-1** [comment]
Are there any updates on this?

**Comment by AlexHolly** [comment]
https://github.com/godotengine/godot/issues/5738

**Comment by reduz** [comment]
This is now fixed via 317dee9 , although its kinda useless to do this anyway
