### ISSUE TITLE
Cannot run the Godot editor on OS X Yosemite 10.10.5 with Intel HD 3000

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot#17667]
**Godot version:**
bash-3.2$ git log -n 1 origin/master
commit b49ca9486cfae32a9d795ceca52b923820751879
But this bug is reproduced on stable Godot versions 3.0.1 & 3.0.2 too, I tried latest version from GitHub just because I wanted to get it working...

**OS/device including version:**
OS X Yosemite 10.10.5
Intel HD 3000 Graphics, 512 MB

**Issue description:**
Godot crashes when trying to open any project in the editor

**Steps to reproduce:**
Just try to open any template project or create new empty project & try to open it in the editor.
For example, I've used the following command line:
bash-3.2$ ./godot.osx.tools.64 -v --path /Users/Antokolos/Documents/work/Godot/test --editor
I've attached log files to this issue (output to the console & output from the exception window on my Mac)

**Minimal reproduction project:**
Just try to open any template project or create new empty project & try to open it in the editor.
[mac_console.txt](https://github.com/godotengine/godot/files/1832446/mac_console.txt)
[mac_message.txt](https://github.com/godotengine/godot/files/1832447/mac_message.txt)

**Comment by Zireael07** [comment]
Does the Intel HD 3000 support OpenGL 3.0? Somehow I don't think so...

**Comment by akien-mga** [comment]
> Intel HD 3000 Graphics, 512 MB

macOS has typically terrible Intel drivers, and this chip is barely compatible with OpenGL 3.3 Core Profile, which is required by Godot 3.0. You can check if there's an available drivers upgrade that would fix it, as Apple does advertise [OpenGL 3.3 support](https://support.apple.com/en-us/HT202823) - but it can be that its support is incomplete and got certified nevertheless.

You can try Linux which supports [OpenGL 3.3 for Intel HD 3000 via Mesa](https://www.phoronix.com/scan.php?page=news_item&px=MTc5MjY), or wait for Godot 3.1 with OpenGL 2.1 support.

**Comment by Antokolos** [comment]
Thank you very much for your explanation and advices!
