### ISSUE TITLE
Add AnimationPlayer#pause and resume methods

### ISSUE THREAD

**Issue by ziomio** [godotengine/godot#17669]
**Godot version:**
3.0.2

**Issue description:**
Function call to stop an animation looks intuitive: $AnimationPlayer.stop()
But function call to pause an animation, which is $AnimationPlayer.stop(false) is not intuitive at all.
I suggest to add $AnimationPlayer.pause() and $AnimationPlayer.resume() methods

**Comment by robfram** [comment]
I will ask some questions for the sake of discussion about semantic.

I understand that the desired final behaviour will be:

- `stop(void)`: Stops the animation, reseting its state (same as now with `p_reset = true`).
- `play(same arguments as now)`: Same behaviour as now. It always starts the animation, from the very beginning (or from the end if `p_from_end = true`.)
- `pause(void)`: Stops the animation, but the current state of it remains. The animation only freeze.
- `resume(void)`: Unfreeze a previous paused animation.

What should happen when resuming an animation stopped instead paused? Show an error message? Same behaviour as `play` with the default arguments?

**Comment by Noshyaar** [comment]
This is how Love2D does for reference: https://love2d.org/wiki/Source. (Doesn't mean that we have to do the same.) Resuming only works when paused.

**Comment by ziomio** [comment]
>I understand that the desired final behaviour will be...
true

>What should happen when resuming an animation stopped instead paused?
Well, there are 2 options. Me personally would go with option 1.
Option 1) Show an error message or throw exception to allow early problem spotting.  You must not be able to resume an animation which was not paused before. If a person explicitely calls 'resume' then he expects to 'resume' an animation which he thinks now is 'paused'. 

Option 2) which is "Same behaviour as play with the default arguments"

**Comment by KoBeWi** [comment]
Closing this in favor of https://github.com/godotengine/godot-proposals/issues/287
