### ISSUE TITLE
Android/HTML5 custom templates option does not work

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#17661]
**Godot version:**
master (3.1-dev)
compiled export templates

**OS/device including version:**
Antergos OS (Linux)

**Issue description:**
https://godot.readthedocs.io/en/latest/development/compiling/compiling_for_android.html
The documentation shows that custom export templates should be either copied to ```/home/[username]/.godot/templates``` or linked via the Custom Package option in the godot exporter.
However I get the message that the export templates are missing: the export button is grayed out.
This only happens for Android and HTML5; the X11 and Windows export works fine.

**Comment by volzhs** [comment]
the document seems outdated.
it should be located at `~/.local/share/godot/templates/3.1.dev/`

**Comment by LinuxUserGD** [comment]
Thank you, renaming and moving them to ```/home/user/.local``` works for me:
```
mv bin/godot.javascript.opt.zip bin/webassembly_release.zip
mv bin/godot.javascript.opt.debug.zip bin/webassembly_debug.zip
mv bin/godot.x11.opt.64 bin/linux_x11_64_release
mv bin/godot.x11.opt.debug.64 bin/linux_x11_64_debug
mv bin/godot.windows.opt.64.exe bin/windows_64_release.exe
mv bin/godot.windows.opt.debug.64.exe bin/windows_64_debug.exe

cp bin/webassembly_release.zip /home/user/.local/share/godot/templates/3.1.dev
cp bin/webassembly_debug.zip /home/user/.local/share/godot/templates/3.1.dev
cp bin/linux_x11_64_release /home/user/.local/share/godot/templates/3.1.dev
cp bin/linux_x11_64_debug /home/user/.local/share/godot/templates/3.1.dev
cp bin/windows_64_release.exe /home/user/.local/share/godot/templates/3.1.dev
cp bin/windows_64_debug.exe /home/user/.local/share/godot/templates/3.1.dev
cp bin/android_release.apk /home/user/.local/share/godot/templates/3.1.dev
cp bin/android_debug.apk /home/user/.local/share/godot/templates/3.1.dev
```
![screenshot](https://user-images.githubusercontent.com/34406967/37719430-4967474e-2d25-11e8-9572-eeea44c0ad46.png)
What about the error message while using the custom package option? Should it be still possible to link to them manually?

**Comment by akien-mga** [comment]
>  What about the error message while using the custom package option? Should it be still possible to link to them manually?

Yeah it's a bug if those don't work.

**Comment by akien-mga** [comment]
I've repurposed the issue for the custom templates issue. For the outdated documentation problem, it would be best to open an issue on https://github.com/godotengine/godot-docs

**Comment by volzhs** [comment]
@akien-mga can it be closed now by https://github.com/godotengine/godot-docs/issues/1247?

**Comment by LinuxUserGD** [comment]
@volzhs It's closed now

**Comment by LinuxUserGD** [comment]
@akien-mga and @volzhs Sorry, I've misunderstood the question. Moving the compiled export templates to the ```.local/share/godot``` works (documentation fix), but the custom template option still does not work for Android (I've set the keystore etc. in the editor settings). So there is a way to export, but both 2 ways should work.

![bug](https://user-images.githubusercontent.com/34406967/38643649-2585bcce-3dde-11e8-98ec-968c85143d18.jpg)
Can you please reopen?

**Comment by FeralBytes** [comment]
I recommend removing documentation label since the issue is repurposed for fixing the bug in Custom Templates and the documentation has been fixed.
