### ISSUE TITLE
Dragging WindowDialog around causes resizing (ratio anchoring)

### ISSUE THREAD

**Issue by GameCy** [godotengine/godot#1767]
This may relate to #369
https://github.com/okamstudio/godot/issues/369
I have a WindowDialog.
Anchor is (ratio,ratio,ratio,ratio)

I run the app, and drag the window around the screen and off screen. I grab it from the title bar.
The window seems to resize, even larger than the screen at some instances.
Notice while dragging the title bar, the title will lag behind and no longer be at the exact position of the mouse.

**Comment by reduz** [comment]
yes you probably don't want to use ratio for this but begin/end

**Comment by akien-mga** [comment]
See also #2048.

**Comment by akien-mga** [comment]
Seems fixed in current master HEAD. There's another bug with ratio, but I'll report it in a new issue.
