### ISSUE TITLE
RemoteTransform2D behavior is broke

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#17671]
**Godot version: 3.0.2**

**OS/device including version: Windows 10 with GTX 660 @ v.388.13**

**Issue description:**

When setting the `remote_path` of `RemoteTransform2D` the transform doesn't update until an `Edit CanvasItem` notification is thrown on the console. But there's more.

![Remote Transform 2 D not updating when Remote Node is set](https://user-images.githubusercontent.com/10171059/37715388-adc59428-2cfa-11e8-9d12-41d5da3d2d3b.gif)

If you set the `use_global_coordinates` to `true` the transform will only update once the transform is set (below I'm releasing the mouse click after the the terminal report `Edit CanvasItem` and only then the `remote_node` transform is updated). This means that if you drag the `RemoteTransform2D` the `remote_node` won't have its transform updated. 

![Remote Transform 2 D not updating when moving](https://user-images.githubusercontent.com/10171059/37715906-f7863a9e-2cfb-11e8-804e-f922d7553455.gif)

This is also true in runtime, but there it doesn't update at all, so it is impossible to dynamically change the `remote_node` of a `RemoteTransform2D`. The last statement is also true even if `use_global_coordinates` is `true`. This leads to an impossibility to change the `remote_node` dynamically, so mechanics like: 

>grabbing an object in the scene

Are inviable to implement, at least without hardcoding workarounds

**Steps to reproduce:**
Create a scene with the follow hierarchy:
- Node2D
    - Sprite
    - RemoteTransform2D

And try out the behaviors reported as shown in the respective `.gif` images

**Comment by henriiquecampos** [comment]
ps: not sure if:

>the `remote_node` is at the same level in the hierarchy of the `RemoteTransform2D`

is a condition for the last behavior.

**Comment by groud** [comment]
Testing a little bit, it seems that everything works fine until you deactivate the use_global_coordinates.
Maybe it's a cache problem, I'm investigating.

**Comment by henriiquecampos** [comment]
The scaling issue is the most problematic one, did #17690 fixes it too, @groud ?

**Comment by groud** [comment]
> The scaling issue is the most problematic one, did #17690 fixes it too, @groud ?

No, could you move that to another issue ?

**Comment by henriiquecampos** [comment]
Done :3
