### ISSUE TITLE
[C#][3.0.2] Instancing many scenes in a thread and then adding them as children of another node causes a crash

### ISSUE THREAD

**Issue by Jcozman** [godotengine/godot#17674]
**Godot version:**

3.0.2 (with mono)

**OS/device including version:**

Windows 10 build 16299

**Issue description:**

Instancing scenes within a Task and then adding the resulting instances as children of a node causes an out of memory error.

**Steps to reproduce:**
Please run the minimal example project

**Minimal reproduction project:**

[Example.zip](https://github.com/godotengine/godot/files/1834076/Example.zip)

**Comment by Zylann** [comment]
The scene tree is not thread-safe, so you must make sure you add them in the main thread.
