### ISSUE TITLE
ColorPickerButton's modal_closed signal doesn't fire when attached via editor

### ISSUE THREAD

**Issue by girng** [godotengine/godot#17688]
hello godoters. tested on 3.0.2 

1) create scene, add a `ColorPickerButton` node
2) connect the `modal_closed` to `ColorPickerButton`
![](https://i.gyazo.com/6b1f80eada6925d266c74c82478945a5.png)
3) when the colorpickerbutton's modal closes, it doesn't get signal'd

**solution 1.**: 
 - C++ developer might need to edit source so it sends the right signal, @willnationsdev  and poke can take a look. i think in the c++ code, it forgets to grab the reference to `get_popup()`

**solution 2.**:
- you have to do `$ColorPickerButton.get_popup().connect("modal_closed", self, "modal_closed_func")`

tyhx! sorry if reported already

**Comment by bojidar-bg** [comment]
`modal_closed` is a signal of Control nodes in general, since all Control nodes can be modal-ed via `show_modal()`.

`ColorPickerButton` should get a different signal instead, such as `popup_closed`.

**Comment by flashyincceo** [comment]
Hi! I made some changes and opened pull request #18161 that seems to add this feature. Are these changes what you were requesting?
