### ISSUE TITLE
Exporting int[] type property does not work in C#

### ISSUE THREAD

**Issue by stuckne1** [godotengine/godot#17684]
**Godot version:**
3.0.2 stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
Referencing an index in an exported array of integers seems to always result in a value of 0. Calling .Length on an exported array of integers results in a number like -741539840 or some other number that is wrong.

**Steps to reproduce:**
```
public class ArrayTest : Node
{
    [Export] public int[] myIntArray;

    public override void _Ready()
    {
        base._Ready();

        GD.Print($"{this.myIntArray.Length}"); // prints -741539840 or something else that is wrong, expected 2 
        GD.Print($"{this.myIntArray[0]}"); //  prints 0, expected 1 
        GD.Print($"{this.myIntArray[1]}"); //  prints 0, expected 2
    }
}
```

Set the values in the editor for myIntArray with the following:
Array size = 2
Indices 0 = 1
Indices 1 = 2

**Comment by mysticfall** [comment]
Probably related to #17601?

**Comment by Chaosus** [comment]
_Closed as duplicate._
