### ISSUE TITLE
RichTextLabel Meta Underlined is not working

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#17682]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
I tried to remove the underline style on the [url] tags of a RichTextLabel but I can't disable it either via code or by unchecking the box Meta Underlined from the inspector.

**Steps to reproduce:**
Create a node with bbcode, use a [url] tag and try to disable the underline style.

**Comment by girng** [comment]
@willnationsdev has done some work in RTL can take a stab at it

**Comment by willnationsdev** [comment]
So, just testing this out: seems like it stops the mouse from updating to a "click-hand" icon, but it doesn't stop the underline from showing up or the "meta_clicked" signal from emitting. Sounds like it's some kind of if logic that's messed up.

**Comment by coppolaemilio** [comment]
Can we get this to the 3.1 milestone? 🙏

**Comment by vnen** [comment]
Just not that a milestone is not a guarantee that it'll be fixed in that version.

**Comment by coppolaemilio** [comment]
@vnen thanks, I just wanted this fix to not be lost in the sea of the unknown 🙈

**Comment by willnationsdev** [comment]
@coppolaemilio Well, you reminded me about this, lol. I'm taking a look at it now. Looking at the code though, it looks like the `underline_meta` property is literally only getting used in reference to making the click-hand icon not show up. I'd discovered that through usage before, but I hadn't seen that that's the only place it's even used in the source code. lol Maybe the old code for it accidentally got deleted a long time ago or something. Who knows.

**Comment by willnationsdev** [comment]
Wow, that was actually a ridiculously easy fix. Just needed to add the flag to the if statement.

**Comment by reduz** [comment]
@willnationsdev seems like you fixed it? this was not closed though.

**Comment by willnationsdev** [comment]
Oh, perhaps not. My mistake. It was some time ago.
