### ISSUE TITLE
Saving a scene containing a tool node will call PREDELETE notification, while not being deleted

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17681]
Godot 3.0.2

Is this behavior intented? I thought NOTIFICATION_PREDELETE would be sent only before the node to be deleted, but it happens anyways when I save the scene, while no node gets deleted (at least I see no reason for this to happen in this situation).

Not only it calls PREDELETE, but also _init() gets called too, BEFORE the predelete... why is all this even done?
I'm saving a scene containing a terrain, which is quite heavy. These steps seem to be unnecessary.

Test project:
[PluginPredeleteCalledOnSave.zip](https://github.com/godotengine/godot/files/1835374/PluginPredeleteCalledOnSave.zip)

1) Open the main scene, notice the log prints:
```
Init
Enter world
Enter tree
Ready
```
2) Save the scene right away, notice this gets printed:
```
Init
Predelete
```

**Comment by santouits** [comment]
This seems the reason for the notifications.

https://github.com/godotengine/godot/blob/1bbe95b4523ed2084737c3fa0edae227737f1827/editor/editor_node.cpp#L1165-L1172

**Comment by KoBeWi** [comment]
Still valid in aeccd1e

**Comment by KoBeWi** [comment]
Ok so I encountered a similar issue, caused probably by the same thing:
```
tool
extends Node2D

export var test: int setget setest

func setest(t):
	test = t
	prints("test", get_instance_id())
```
Change `test` to 1 in the inspector and save the scene. With each save, the script will print with different ID each time.

**Comment by KoBeWi** [comment]
This is caused by the dummy node created when saving scene (this is the one that calls the method). See #47828
