### ISSUE TITLE
File access error - after a while - for resources loaded after load_resource_pack()

### ISSUE THREAD

**Issue by yleduc** [godotengine/godot#17696]
**Godot version:**
Reproduced on 3.0.2 and 3.0

**OS/device including version:**
macOs 10.13.2 
Reproduced on MacBook Pro 2,6 GHz Intel Core i5/8 Go 1600 MHz DDR3/Intel Iris 1536 Mo

**Issue description:**
After multiple consecutive resources load, some weird errors (in my example : corrupted PNG) occurs-
and we cannot load anything in the game. It only happens for resources loaded dynamically (via gdscript) from packed file (with load_resource_pack).

The exact same resource file loaded directly (without load_resource_pack) work well.

**Steps to reproduce:**
See minimal reproduction project. I did not succeed in isolating it further.

**Minimal reproduction project:**
Please donwload it on : [ErrorFileAccess.zip](https://github.com/godotengine/godot/files/1837758/ErrorFileAccess.zip)

It just periodically (Timer) loads a PNG image with Image.load() and assign it to a Sprite.

After some times : var error_loaded = img.load(path_to_load)
returns an error (corrupted PNG)
(it is not always the same time - it takes from 15 seconds to 60 seconds on my computer to reproduce - it does not depend on the number of loads - sometimes playing with the timer period change the behavior)

I put a const : const LOAD_FROM_PACKED_FILE

- true : load an image from a zip file after
   ProjectSettings.load_resource_pack("res://sample_packed.zip")
   Will trigger the error. (the bug)

- false : load the same PNG image for resource directly
   Will work flawlessly

If it helps, I tried the same scenario/game on an iphone export. I did succeed once to make the exported game crash and it was apparently on PackedData::seek (but I was in release)

Note: It took me more than 1 day to figure out the source of the problem. I had strange behaviors - after some times in my games, it was impossible to load anything (scenes, font_data, images, ...). I did my best to try to find it by myself and have the minimal reproduction steps. Hope the provided information is enough.

**Comment by reduz** [comment]
I can't reproduce this at all.. can anyone else give it a try? May be ÓSX related.

**Comment by qarmin** [comment]
I tried to reproduce this on Ubuntu but I can't.

**Comment by neuromnem** [comment]
Wasn't able to reproduce this issue even after ~5 min of running the reproduction project.
**Godot version:**
3.2.beta.custom_build.98caeb635
**OS version:**
macOS Catalina 10.15.1 (19B88)

**Comment by Calinou** [comment]
I'll close this since nobody has been able to reproduce this.

@yleduc	Please comment if you can still reproduce this on 3.2beta1 or later :slightly_smiling_face:
