### ISSUE TITLE
Dual screen mac editor UI breaks

### ISSUE THREAD

**Issue by adamprocter** [godotengine/godot#17699]
**Godot version:**

**OS/device including version:**

Mac 10.13.3

**Issue description:**

Dragging the editor from one screen to another on dual monitor set up breaks UI of engine so cant be used.
I suspect its a resoltuion related issues

same UI on screen 1
https://www.dropbox.com/s/5exlt4v9mu2by4u/Screenshot%202018-03-22%2015.16.18.png?dl=0
and then dragged to screen 2
https://www.dropbox.com/s/iuu9aowkzxcgv5f/Screenshot%202018-03-22%2015.16.18.png?dl=0

**Steps to reproduce:**
Plug mac into 2 screens and launch editor and drag between monitors.

**Minimal reproduction project:**

No project needed

**Comment by bruvzg** [comment]
This is HiDPI related.
Starting the editor on retina screen and dragging to non-retina one works ok, starting on non-retina screen and dragging to retina doesn't.

**Comment by adamprocter** [comment]
Thanks

**Comment by UngratefulFool** [comment]
I am still having this issue, I start on a retina display and switch to another monitor and the sizing is broken to the point where I cannot work on the project. If I start on my monitor the sizing is very small when I switch to my retina display.

I can provide images to show the scaling, but it is a similar issue as described before.

OS/device including version:
MacOS 10.13.6

Steps to reproduce:
Same as the initial issue described

**Comment by AThousandShips** [comment]
@ericlothspeich please open a new issue report with further details
