### ISSUE TITLE
2d filter shader inside CanvasLayer using SCREEN_TEXTURE "invades" neighbouring nodes

### ISSUE THREAD

**Issue by OrenjiAkira** [godotengine/godot#17698]
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
Any OS (well, I tested on macosx and linux, but probably windows too, given the nature of the problem)

**Issue description:**
When you create a fliter shader (like a grayscale filter) inside a canvaslayer, it also affects nodes of the same type in the same hierarchy in the tree. It also flips the screen texture in both axes on this second node. This only happens when the filter shader is inside a CanvasLayer in the tree.

I'm using the following shader code, in case I'm maybe doing shaders wrong.
```glsl
shader_type canvas_item;
void fragment() {
	vec4 pixel = texture(SCREEN_TEXTURE, SCREEN_UV);
	float avg = (pixel.r + pixel.g + pixel.b) / 3.0;
	COLOR = vec4(avg, avg, avg, COLOR.a);
}
```

So imagine this tree:
```
Root
|- Sprite (or, like, your game world or whatever)
|- CanvasLayer (your hud or something)
   |- ColorRect (a filter shader rendering that uses the SCREEN_TEXTURE, like a grayscale filter for example)
   |- ColorRect (just a white rectangle)
```

This renders the grayscale filter just fine, but it also renders the screen texture on the second ColorRect (which is just a plain node with no shaders or materials!) without the grayscale filter, flipped in both axes, and stretched to the rectangle's size. Basically an inverted copy of the screen texture.

**Steps to reproduce:**
See above.

**Workaround:**
My current workaround is creating a new shader on the second ColorRect that is basically **just** the following code:

```glsl
shader_type canvas_item;
void fragment() {
	COLOR = COLOR;
}
```

This fixes it. The second ColorRect starts rendering just its color as it should. Weird.

**Minimal reproduction project:**
[shader_glitch.zip](https://github.com/godotengine/godot/files/1837927/shader_glitch.zip)

**Comment by bojidar-bg** [comment]
Can someone test this on master? I remember fixing it myself.
