### ISSUE TITLE
c# Node.Connect() not working on predefined signals when called from code

### ISSUE THREAD

**Issue by exts** [godotengine/godot#17697]
**Godot version:**
3.0.2 Stable

**OS/device including version:**
Windows 10

**Issue description:**
When calling connect on a node's predefined signal (for example `mouse_entered` signal for a Label) nothing happens.

**Steps to reproduce:**
1. Create new project
2. Add a Node then add a Label to the node (rename them if you want)
3. Attach script to the parent node 
4. Get access to the label in `_Ready()` then try connecting a local class method to a predefined signal (`mouse_entered` or `mouse_exited`)
5. Start the scene and try hovering over the label.

**Minimal reproduction project:**
[SharpLabelMouseHover.zip](https://github.com/godotengine/godot/files/1837770/SharpLabelMouseHover.zip)

**Comment by Duehok** [comment]
Your label is set to ignore the mouse (mouse_filter = 2) so mouse_entered and mouse_exited will never fire.
I have successfully connected to some built-in signal with C# in code (if i remember correctly to button_toggled)

**Comment by exts** [comment]
@Duehok Yeah you're right setting mouse filter to "stop" fixes this, going to close this for now @neikeq
