### ISSUE TITLE
Control's resized signal not called properly when maximizing/minimizing

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#17701]
**Godot version:**
Godot 3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
Might be linked to this old issue I've posted #7203
I have a GridContainer where I use Container as child to create margins around the actual grid controls. The grid's resized signal is used to call fit_child_in_rect on all containers to apply the margins.

When I resized the window manually, by grabbing the borders, it works fine.
When I use the maximized or minimized button of the window, it does not work properly. The resized signal is emitted, but at the wrong time, my computation to apply margins still use the old size.

** How to reproduce **
Use the following demo project: 
[ResizeIssue.zip](https://github.com/godotengine/godot/files/1838322/ResizeIssue.zip)

Resize the window manually
Resize the window by using maximize/minimize
Notice the different behavior

PS: I also noticed in the demo project that the initial resize is not working too.

**Comment by girng** [comment]
another case of
`yield(get_tree(), "idle_frame")`

being the culprit

add this to the 
```
func _on_grid_resized():
	yield(get_tree(), "idle_frame")
	for container in $grid.get_children():
		container.fit_child_in_rect(container.get_child(0), Rect2(margins, container.rect_size - margins*2))
```

fixes it

**Comment by BraindeadBZH** [comment]
@girng interesting, it is effectively a workaround, I did not knew this was a much deeper issue, thanks.

**Comment by girng** [comment]
@BrainBlasted when creating more advanced UIs, `yield(get_tree(), "idle_frame")` will be your best friend.

it's a double edge sword i feel. works great when you need it, but sometimes you get stuck on something you're like "wtf this feels hacky", but it "works", so you feel good. hard to explain, glad it helped you.

**Comment by BrainBlasted** [comment]
Woops, I think you pinged the wrong user :)

**Comment by girng** [comment]
haha oops, my bad. edited

**Comment by KoBeWi** [comment]
Seems fine in 3.2.3
