### ISSUE TITLE
Exported App crashes on iPad 2 (iOS 9.3.5)

### ISSUE THREAD

**Issue by smeikx** [godotengine/godot#17700]
**Godot version:**
v3.0.2.stable.official

**Issue description:**
an exported app crashes on iPad 2 (iOS 9.3.5) with the following error message:

```
cadisaplylink: 02018-03-22 15:35:17.241 godot-ios-test[1521:304007] -[UIView startAnimation]: unrecognized selector sent to instance 0x14f5f6d0
2018-03-22 15:35:17.247 godot-ios-test[1521:304007] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView startAnimation]: unrecognized selector sent to instance 0x14f5f6d0'
```

Also, I’m presented with this:

```
libsystem_kernel.dylib`__pthread_kill:
    0x23e6ac54 <+0>:  mov    r12, #328
    0x23e6ac58 <+4>:  svc    #0x80
->  0x23e6ac5c <+8>:  blo    0x23e6ac74                ; <+32>
    0x23e6ac60 <+12>: ldr    r12, [pc, #0x4]           ; <+24>
    …
```

**Steps to reproduce:**
1. created minimal project (one scene, one sprite, everything else left on default)
2. provided all necessary icon and screen files for export
3. exported project
4. configured [code signing, etc.](https://www.reddit.com/r/godot/comments/7ynucq/godot_ios_export/) in Xcode
5. hit *Bild & Run*
6. on the iPad, the app started, but immediately halted with above error messages displayed in Xcode

I did the same with an iPhone 5S (iOS 11.2.6) where no errors occurred and everything seems to work fine.

**Comment by volzhs** [comment]
does iPad 2 support opengl es 3.0?
I found this.
https://developer.apple.com/library/content/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/HardwareGPUInformation/HardwareGPUInformation.html

**Comment by smeikx** [comment]
The iPad 2 comes with a PowerVR SGX543MP2, which only supports OpenGL ES 2.
Do you think that’s the reason for this specific error?

**Comment by volzhs** [comment]
I guess so.
Godot 3.0.x does not support GLES 2.
Godot 3.1 will support GLES 2 again.

**Comment by smeikx** [comment]
Okay, thank you *so* much!

I’ll try it later with a newer model of an iPad, just to make sure — but close this issue for now. Thanks!
