### ISSUE TITLE
is_action_just_pressed doesn't work in gamepads

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#17705]
Godot doesn't detect is_action_just_pressed for gamepad-triggered actions. It works fine with mouse and keyboard though.

**Godot version:**
3.0.rc1

**OS/device including version:**
MacOS 10.13.3
MacBook Air (13-inch, Early 2014)
Testing on Moto Z with Moto Gamepad moto-mod.

**Issue description:**
The method Input.is_action_just_pressed doesn't return true when triggering the action using a gamepad. Input.is_action_pressed works fine with gamepads.

**Steps to reproduce:**
This works with gamepad, mouse and keyboard:
```
if Input.is_action_pressed("flip"):
	goingRight = !goingRight
```
This doesn't work with gamepad (only with mouse and keyboard):
```
if Input.is_action_just_pressed("flip"):
	goingRight = !goingRight
```

**Comment by kubecz3k** [comment]
Just a note: I'm using 3.0 and on Ubuntu 17.04 / 18.04 it works fine. @jahd2602 can you confirm it's android only bug?

**Comment by jahd2602** [comment]
I can not test in the computer because I don't have a controller to plug in. It seems it is an android only bug.

**Comment by reduz** [comment]
@Hinsbart any progress on this?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?
