### ISSUE TITLE
Tilemap quadrants are not dirtied when entering the scene tree

### ISSUE THREAD

**Issue by xKamuna** [godotengine/godot#17712]
**Godot version:**

Commit cc34406b5d48c8c09d51c0c8fe6d94b91303745f

**Issue description:**

Tilemap quadrants are not dirtied when entering the scene tree, causing things like occluder_instances and navpoly_ids to be blank upon exiting and then entering the scene tree.  In case NOTIFICATION_ENTER_TREE in the _notification function, Adding a _recreate_quadrants(); before _update_dirty_quadrants() fixes the issue.

**Comment by bojidar-bg** [comment]
Seems like #15909 added such a change, can you confirm it is working properly now?

**Comment by reduz** [comment]
@MarianoGnu can you check if this works for you? so we can close it.

**Comment by akien-mga** [comment]
Assumed fixed by #15909. Please comment if you can still reproduce it in recent 3.1 betas.
