### ISSUE TITLE
Godot vs2015 WindowSDKDir Cannot Compile

### ISSUE THREAD

**Issue by heisty** [godotengine/godot#17713]
C:\Program Files (x86)\Microsoft Visual Studio 14.0>D:

D:\>cd godot-*

D:\godot-master>scons platform=windows
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
Found MSVC compiler: x86
Compiled program architecture will be a 32 bit executable. (forcing bits=32).
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str':
  File "D:\godot-master\SConstruct", line 327:
    detect.configure(env)
  File "./platform/windows\detect.py", line 343:
    configure_msvc(env, manual_msvc_config)
  File "./platform/windows\detect.py", line 196:
    env.Append(CPPPATH=[os.getenv("WindowsSdkDir") + "/Include"])

D:\godot-master>

**Comment by nazgulsenpai** [comment]
You have to open the "VS2015 x86 Native Tools Command Prompt" for all the paths to resolve properly. 

If you are building 64bit, then "VS2015 x64 Native Tools Command Prompt"

![image](https://user-images.githubusercontent.com/31775906/37849768-e876c558-2ea6-11e8-99f6-5b7570bafbd3.png)

If you don't have these listed in your Start Menu, you have to go to Programs and Features and Modify your VS2015 install to include C++. More info can be found here: https://blogs.msdn.microsoft.com/vcblog/2015/07/24/setup-changes-in-visual-studio-2015-affecting-c-developers/

**Comment by vnen** [comment]
Do you you have the C++ components and the Windows SDK installed?
