### ISSUE TITLE
Compress Lossless (PNG) produces Loosy Compressed PNG files

### ISSUE THREAD

**Issue by hubslave** [godotengine/godot#17726]
**Godot version:** 3.0.2

**Issue description:**
Using this method results in Loosy compressed PNG files with artifacts, here is an example DIFF MAP comparing original PNG file with one created by Compress Lossless (PNG): ![diff_map](https://user-images.githubusercontent.com/29800872/37874291-28acfe96-301c-11e8-846a-8adbdcbeb69f.png)
Black == same Red == difference

**Steps to reproduce:**
Load any PNG file using Compress Lossless (PNG) method

**Comment by mrcdk** [comment]
How did you test it? Can you upload the png that causes that? I can't reproduce the issue importing 4 different lossless pngs with the lossless option enabled and comparing both the original png and the imported png (after removing the godot header of the imported png)

The only way I've been able to reproduce it has been with a jpg (which is normal) and a lossy png (using a png optimizer on the original png) In both cases the problem was the original file.

**Comment by hubslave** [comment]
Here is a zip with both images: http://www78.zippyshare.com/v/v2ZBRwYk/file.html

**P.S.** Uploaded to external host since github won't accept zip or stex files.

**Comment by mrcdk** [comment]
The issue isn't not that the imported is lossy compressed. The issue that the original file has alpha values that are modified by the option of the importer "Fix alpha borders" to avoid weird colors around the borders. Those are the differences you see between both.

http://docs.godotengine.org/en/latest/getting_started/workflow/assets/importing_images.html#fix-alpha-border

If you disable that option there won't be any difference.

I used this to optimize the png https://tinypng.com/ I tried in yours and it didn't make any difference with the imported file. Looks like it depends of the original image if there will be differences or not.

**Comment by hubslave** [comment]
TinyPNG is known to use loosy recompression techniques in combination with lossless optimizations in order to "shrink" a file ...

Definitely the project can use better documentation "It’s a good idea to leave it on by default, unless specific values are needed." not to mention the misleading data in **Compress Mode** on the same page...

**P.S.** Thanks for the effort & support @mrcdk
