### ISSUE TITLE
Missing documentation for type_hint in ResourceLoader

### ISSUE THREAD

**Issue by bartosz-m** [godotengine/godot#17728]
There is no information what correct values could be passed to `ResorceLoader` functions `load` and `load_interactive`.
I've looked directly at source code of `ResorceLoader` but I still have no clue.

**Comment by girng** [comment]
might be better here: https://github.com/godotengine/godot-docs

good catch  :)

**Comment by bartosz-m** [comment]
thanks for directing me to right repo, I've wasn't aware that there was separate-one for documentation.

**Comment by bojidar-bg** [comment]
Actually, this repo is better, since the class documentation lives alongside the engine source.

**Comment by Calinou** [comment]
Is this covered by the current [`ResourceLoader.load()`](https://github.com/godotengine/godot/blob/41a320c82719c8201301459338a8eb47752d864d/doc/classes/ResourceLoader.xml#L54-L70) documentation? Note that `ResourceLoader.load_interactive()` was removed in the `master` branch in #36640.

**Comment by pycbouh** [comment]
The docs state that it's a string with the Resource type. I think it's pretty clear now. If someone still finds it unclear, an issue can be reopened or a new one can be filed.
