### ISSUE TITLE
Sprites using deleted image files are still visible in the editor until project is reopened

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#17734]
**Godot version:**
3.0.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
When a sprite has its texture image file deleted, using either external file explorer or Godot's file manager, the sprite is still displayed as normal even though the resource image file no longer exists.

Sometimes even after closing and reopening the scene file it still shows the sprite's image.

However closing the whole project or quitting Godot and reopening the scene will trigger the popup for missing dependencies.

This is a problem because the editor view doesn't represent the reality that the image file is missing. You could look at a scene and everything looks ok, but the next time you open it up lots of images are missing because you messed something up and didn't know about it at the time.

This probably also applies to other resource types (not just Sprites and images). 

**Steps to reproduce:**
* Create a scene with a sprite. 
* Choose a texture image file for the sprite. 
* Delete the texture image file. 
* See that the sprite is still displayed as normal as if everything was ok
* Close the scene and reopen it
* See that everything opens fine. Sprite is displayed as normal as if everything was ok
* Quit Godot and reopen the project and the scene
* NOW see the missing dependency popup

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
