### ISSUE TITLE
Documentation columns aren't correctly aligned

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#17731]
**Godot version:**

Godot master https://github.com/godotengine/godot/commit/fd79de01c20168075dbf425831ac44f2b676f275

**OS/device including version:**

Win 10

**Issue description:**

The documentation columns aren't correctly aligned. Probably a cause of this PR https://github.com/godotengine/godot/pull/17612

**Steps to reproduce:**
![https://i.imgur.com/3HAO1OH.png](https://i.imgur.com/3HAO1OH.png)

**Comment by akien-mga** [comment]
CC @robfram
