### ISSUE TITLE
You can't move child nodes of a viewport.

### ISSUE THREAD

**Issue by 0nepixel** [godotengine/godot#17739]
Godot 2.0/2.1/3.0.
I don't know why but you can't move the child nodes of a viewport (2D) in the editor, you have to take the node out and change the position, then put it back in the viewport, it's anoying and impractical :/.

**Comment by asheraryam** [comment]
I'd like to address this but first would need to know, is this desirable behaviour?

**Comment by bojidar-bg** [comment]
Closing as duplicate of #20619, as the later has a bit more discussion and details.
