### ISSUE TITLE
Feature Request: Allow us to drag assets from desktop folder to folder in FileSystem in godot sidebar

### ISSUE THREAD

**Issue by exts** [godotengine/godot#17737]
**Godot version:**

3.x

**OS/device including version:**
Windows 10

**Suggestion description:**
Allow us to drag an asset from any desktop folder directly into the sidebar of the filesystem. That way say you don't have the current folder open and you just downloaded a new font, and you wanted to quickly drag it to the project without needing to open the folder since you have that folder already opened in godot directly. 

**Why would it be useful**
Sometimes you don't always have the project folder open on your desktop and you're already looking through your assets and you just want to drag them directly into the project since godot's already open. We download free assets offline all the time, it'll save us a bit of time being able to do this without an extra step.

**Comment by vnen** [comment]
Doesn't this work already?

**Comment by exts** [comment]
@vnen yeah seems to work on devel
