### ISSUE TITLE
Export Template Manager: Download broken

### ISSUE THREAD

**Issue by Simran-B** [godotengine/godot#17746]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Trying to download the 3.0.2 official export template within Godot fails with "Could not connect". Console output:

> (mirrors:[(name:Official 3.0.2-stable [HTTPS]), (url:https://downloads.tuxfamily.org/godotengine/3.0.2/Godot_v3.0.2-stable_export_templates.tpz)])
> closed

The download via the website works however, which has the same URL:

https://downloads.tuxfamily.org/godotengine/3.0.2/Godot_v3.0.2-stable_export_templates.tpz

**Steps to reproduce:**
Editor > Manage export templates > 3.0.2.stable (missing) Download > Official 3.0.2-stable [HTTPS]

**Comment by nazgulsenpai** [comment]
Try creating an exception in Windows Firewall for Godot. I have Windows Firewall disabled on Win 10 64 and it downloads without issue.

**Comment by girng** [comment]
that popup that windows gives on a fresh open of godot (w10) asks if you want to allow access. always press yes, should help

**Comment by Simran-B** [comment]
Apparently, I allowed Godot to access the internet on first run according to the advanced settings of the Windows Firewall:

![image](https://user-images.githubusercontent.com/7819991/37924718-f7ecf406-3132-11e8-9d87-df41ce027a14.png)

For inbound connections that is. There was no rule for outbound connections, but I added one. I also tried disabling the firewall altogether, but to no avail.

Also checked the router log, but nothing blocked there either. In-app download fails for some other reason it seems.

**Comment by Toshiwoz** [comment]
Getting the same issue:
```
download 3.0.2.stable
ERROR: IP_Unix::_resolve_hostname: getaddrinfo failed!
   At: drivers\unix\ip_unix.cpp:108
download 3.0.2.stable
ERROR: StreamPeerTCPWinsock::connect_to_host: Condition ' !p_host.is_valid() ' is true. returned: ERR_INVALID_PARAMETER
   At: drivers\windows\stream_peer_tcp_winsock.cpp:296
download 3.0.2.stable
ERROR: StreamPeerTCPWinsock::connect_to_host: Condition ' !p_host.is_valid() ' is true. returned: ERR_INVALID_PARAMETER
   At: drivers\windows\stream_peer_tcp_winsock.cpp:296
```
While I can use httprequest within the editor, so it's not the firewall.

**Comment by Toshiwoz** [comment]
I run a custom build (I usualy download and compile everyday the latest code), and I'm getting this message:
![image](https://user-images.githubusercontent.com/21297356/51791119-3de34580-216c-11e9-8fe4-dcb91d895653.png)

But maybe my case doesn't count as it is a custom build.

**Comment by akien-mga** [comment]
There are no templates mirror for custom builds indeed.

**Comment by Calinou** [comment]
I can still reproduce this issue in 3.2alpha2. #31326 only disables the buttons when using a development build, as official alphas/betas have export templates available. However, it seems the list of mirrors isn't set up correctly, so I get the "Error getting the list of mirrors" dialog as seen above.

**Comment by akien-mga** [comment]
Note that official alphas have release "alpha1", "alpha2", etc. contrarily to the master branch which stays at an undefined "alpha". That's why we can provide templates for download for alpha releases without risk of people using them with their custom build and having a version mismatch.

**Comment by Calinou** [comment]
@akien-mga I see, thanks for the clarification. Maybe the check on https://github.com/godotengine/godot/blob/d0628180aef4987d24f91329e4c3378b5a037a34/editor/export_template_manager.cpp#L74 should be changed to also exclude builds whose status is "alpha", "beta" or "rc" (without a number)?

**Comment by akien-mga** [comment]
Yeah that should work. An alternative would be to query the mirror list, and if not list is found, hire the download option.
