### ISSUE TITLE
HTML export works on computers but not in mobile browsers

### ISSUE THREAD

**Issue by Tinkersedge** [godotengine/godot#17743]
**Godot version:**
3.0.2

**OS/device including version:**
iMac - High Sierra

**Issue description:**
Completed a mock up of the beginning of a game (http://dev.fun4thebrain.com/godot/3/arrayIndex.html) using Godot 3.0.2. I uploaded it to my server. It works fine on all the different browsers. But, no mobile device is able to load it. It starts and then just remains at the loading screen. 

I tried it with another game (http://dev.fun4thebrain.com/godot/creepdodge/CreepDodge.html) It had a few errors that appeared, but nothing that effects games play. But, it will not load on mobile devices either. 

I have searched and other people seem to be having troubles with the HTML export but there are for different reasons and no one has simply said that it will ONLY not show up on mobile devices. Any help would be great!

**Steps to reproduce:**
Load the game on computer, then try to load on mobile device.
[aaPack.zip](https://github.com/godotengine/godot/files/1844576/aaPack.zip)

**Comment by Zireael07** [comment]
What mobile devices do you mean? Maybe the devices don't support OpenGL ES 3?

**Comment by Tinkersedge** [comment]
I have tried it on iPhone (both 8 plus and X) and the iPad, as well as the Samsung S8Plus.

**Comment by akien-mga** [comment]
CC @eska014

**Comment by LinuxUserGD** [comment]
Works on my Samsung Galaxy device (using Chrome)

**Comment by Tinkersedge** [comment]
OK. Interesting. Doesn't work on Samsung S8+ with the default browser.

**Comment by eska014** [comment]
HTML5 export in 3.0 requires a browser with support for WebGL 2.0 and WebAssembly. WebGL 2.0 is currently only supported by Firefox and Chromium-derived browsers. Stock browsers probably don't come with WebAssembly support either. http://docs.godotengine.org/en/3.0/getting_started/workflow/export/exporting_for_web.html#exporting-for-the-web

**Comment by LinuxUserGD** [comment]
Not 100% sure, but I think that Godot only supports Chrome and Firefox (+ Chromium and Chromium based bowsers like Opera).

**Comment by Tinkersedge** [comment]
That doesn't explain why it won't work in Chrome on iPhoneX or iPads

**Comment by Tinkersedge** [comment]
Also does not work in Firefox on iPhoneX or iPads

**Comment by Tinkersedge** [comment]
Not sure why this is closed and archived when the original questions was not answered.

**Comment by mrcdk** [comment]
Firefox and Chrome on iOS are just skins on top of safari because Apple doesn't let other browser to use their engines and safari doesn't support WebGL 2.0 https://caniuse.com/#feat=webgl2 so it won't work there

**Comment by Tinkersedge** [comment]
@mrcdk Thanks for the link. That helped it make a bit more sense. Wish there was somewhere that explained why it doesn't work on Firefox and Chrome on the apple products. I will have to research.
