### ISSUE TITLE
Properties in instanced scenes can't be reverted

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#17753]
**Godot version:**
Godot_v3.0.2-stable_win64

**OS/device including version:**
Windows 7

**Issue description:**
Properties in instanced scenes can't be reverted.

**Steps to reproduce:**

 1. Create a new project
 2. With the default empty scene:
    1. Create a new (root) `Sprite` node named `Sprite1`
    2. Set `Sprite1`'s texture to icon.png
    3. Save this scene as `Sprite1.tscn`
 3. Create a new scene:
    1. Create a new (root) `Node` named `TestScene`
    2. Select this node and click the "instance a scene file as node" button, then open the `Sprite1.tscn` file (note that the sprite is visable in the 2D View).
    3. With this instanced `Sprite1` node selected use the Inspector panel to untick the  `CanvasItem` > `Visibility` > `Visible` property (note that the sprite disappears from the 2D View).
    4. Click the revert button to the right of the checkbox (note that this does not recheck the checkbox or restore the sprites visibility in the 2D View)
       ![2018-03-25_12-10-38](https://user-images.githubusercontent.com/1151394/37871656-bff055ba-3025-11e8-825f-5c05bf28308c.gif)

**Minimal reproduction project:**

[test_instanced_scenes.zip](https://github.com/godotengine/godot/files/1845001/test_instanced_scenes.zip)

**Comment by akien-mga** [comment]
Fixed by 6cc116d.
