### ISSUE TITLE
Obj importer is broken

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#17759]
**Godot version:**
Godot 3

**Issue description:**
Godot 3 Obj importer is broken , it does not import the Correct mesh size and also sometimes there is a problem with material ID ... for example if the mesh contain more than 1 material , let's say 3 or 4
Godot will read many materials instead of 3 or 4 material id

the same meshes on UE4  and Unity work great , but Godot there is problems with the size and materials

**Comment by Calinou** [comment]
Can you please attach a problematic OBJ file packed into a ZIP archive? (GitHub doesn't allow uploading some file types directly, but ZIP files are always accepted up to 50 MB.)

**Comment by StraToN** [comment]
Here is a problematic example (taken here : https://www.turbosquid.com/FullPreview/Index.cfm/ID/561881). In my case, the material (just set the albedo texture) shows correctly in the editor, but all white in the game.
[Stone Pack1_Stone_1.zip](https://github.com/godotengine/godot/files/2193716/Stone.Pack1_Stone_1.zip)

**Comment by akien-mga** [comment]
> Here is a problematic example (taken here : https://www.turbosquid.com/FullPreview/Index.cfm/ID/561881).

The `Stone Pack1_Stone_1.mtl` referenced in `Stone Pack1_Stone_1.obj` is missing, so I don't know if it's a good example.

Nevertheless, I can't reproduce the issue you're mentioning. I instanced the MeshInstance with the obj, set the diffuse texture as albedo texture, the normal map too for fun, and it looks fine both in editor and in game. [Stone Pack1_Stone_1.zip](https://github.com/godotengine/godot/files/2205301/Stone.Pack1_Stone_1.zip)

![screenshot_20180718_115923](https://user-images.githubusercontent.com/4701338/42874692-03e7a6f4-8a82-11e8-8628-a1404ef87ef7.png)
(behold my 3D Camera skills in the awesome animation :P)

**Comment by StraToN** [comment]
@akien-mga The described behaviour occurs if you set the Material into the *mesh set in the MeshInstance node (not on the MeshInstance itself)*. If you set the material on the MeshInstance node no bug occurs at all. 
Don't forget to save, close and reload. In my case, the material disappears after reloading.

**Comment by StraToN** [comment]
@akien-mga Yep, there. I understand, so in my case the "problem" is normal and probably not related to the topic. At least with this OBJ.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
