### ISSUE TITLE
Linux 64 bit, crash on excessive alt-tabbing 

### ISSUE THREAD

**Issue by JohnSmith25** [godotengine/godot#17758]
Duplicate issue: I haven't found any when searching for Linux related crashes

**Godot version:** 3.0.2, binary version
**OS/device including version:** Linux Mint 18.3 

**Issue description:**
Godot crashes when I am switching the windows frequently in order to look up how the tutorial script is structured. The exception it shouldn't crash at all when alt-tabbing. Also it might be worth to note that the game will keep running when the editor crashed. The compiled version (3.0 Github) which is compiled in debug mode doesn't seem to cause this issue at all, I have alt-tabbed at least 30+ times and no crash while the regular Linux binary release has this issue. 
regular release log: [crashlog.txt](https://github.com/godotengine/godot/files/1845257/crashlog.txt)
compiled debug log: [log_debug.txt](https://github.com/godotengine/godot/files/1845285/log_debug.txt)
 

**Steps to reproduce:**
1. Load up any project 
2. Keep alt-tabbing a lot i.e switching the active windows 
3. Godot crashes with a segmentation fault

**Comment by akien-mga** [comment]
Can't reproduce it on Mageia 6 x86_64 running Plasma 5.12 and with a Nvidia GTX 670M (driver 390.42).

I guess you're running Cinnamon? The crash happens in the nvidia 340 driver, so it might be specific to this driver version and/or to Cinnamon's window manager.

**Comment by JohnSmith25** [comment]
>I guess you're running Cinnamon?
No I am using XFCE/xfwm4 + composit 
>The crash happens in the nvidia 340 driver, so it might be specific to this driver version  
Sounds plausible, though it makes me wonder why it is happening for me with Godot and not other programs, I just tested this on Blender too see if it has the same bug or if its due to my driver and it did not crashed.

**Comment by reduz** [comment]
More users trying to reproduce this are welcome.

**Comment by organicpencil** [comment]
Tried a couple different setups:
Mint 18.3 XFCE / NVIDIA 390.77
Mint 19 XFCE / NVIDIA 340.106

Could not reproduce with 3.0.6

**Comment by LittleWhite-tb** [comment]
Can't reproduce using 3.0.2. I am on Manjaro (Linux 4.14.71.1). NVIDIA Driver 340.107. Mate 1.20.3.
I did not see any strange CPU consumption, neither strange RAM consumption.
@JohnSmith25 : did you encounter this bug still with 3.0.3 or newer ?
Can you reproduce it easely ? I mean, opening the project and alt+tab 30 times and voilà, reproduced ?

Would be cool if for each stable release, the godot team save the symbols associated to it. I think it is possible, and making the dumptrace less obscure.

**Comment by aaronfranke** [comment]
Can't reproduce any crash with the latest master on Xubuntu 18.04 LTS (XFCE 4.12)

**Comment by andrew-field** [comment]
Could not reproduce the error using the latest master at the time of writing.
Linux Mint 19 Cinnamon, OpenGL ES 3.0 Renderer: GeForce GT 635M/PCIe/SSE2 - Driver 390.77

**Comment by Nogal** [comment]
Some time has passed and I have a very different setup, but I wanted to include my two cents.

If the issue can still be reproduced, my only suggestion is to recompile the same 3.0.2 version and enable them yourself and try to reproduce it again under gdb output and grab the full backtrace.

As per my own findings, I cannot reproduce this issue under Fedora 29 on version 3.0.6 using the nvidia 415.18 driver

**Comment by akien-mga** [comment]
I tried again and still can't reproduce it. As the backtrace points to a crash in the Nvidia 340 driver, there's likely nothing we can do in Godot to fix it.
