### ISSUE TITLE
Inconsistent naming of material surface related methods in ArrayMesh

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17750]
**Godot version:**
`master` / dad47d8876de45132226985dbbd079e060f6facc

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**

In `ArrayMesh` API, there are several methods to manipulate blendshapes like `GetBlendShapeName` or `RemoveBlendShape` which follows the common naming convention used in other parts of the Godot API.

However, `ArrayMesh` also contains methods for dealing with material surfaces, which follows a different (and rather unusual) naming convention like `SurfaceGetName` or `SurfaceRemove` which can be rather confusing to new users (especially so, when considering `MeshInstance` defines `GetSurfaceName`, not `SurfaceGetName`).

It'd be better to ensure all public APIs to follow a single, commonly used naming convention to avoid such a problem.

**Comment by mysticfall** [comment]
Found another case of a similar naming convention being used:
 * http://docs.godotengine.org/en/latest/classes/class_animation.html

**Comment by Calinou** [comment]
Closing in favor of #16863. Please report renaming suggestions there (if not done already).
