### ISSUE TITLE
The 3D Listener node doesn't work 

### ISSUE THREAD

**Issue by minitrope** [godotengine/godot#17751]
**Godot version:** 3.0 (stable)
**OS/device including version:** Ubuntu 16.04.4 LTS (Xenial Xerus)"
**Issue description:**

When using a Listener in 3d space, the sounds is always perceived through the camera, not the listener.

**Steps to reproduce:**

- Use a Listener and a AudioStreamPlayer3D in a simple scene.
- Makes the listener move but the camera and audio source static.
- Notice that there is no difference when the sound is played

**Minimal reproduction project:**

[Listener.zip](https://github.com/godotengine/godot/files/1844792/Listener.zip)

**Comment by Noshyaar** [comment]
It was commented out since b400c69
https://github.com/godotengine/godot/blob/928cdb4f8a72c2de5751cddd3205c2a3c09e6f6d/scene/main/viewport.cpp#L643-L651

**Comment by reduz** [comment]
Yeah this needs fixing. Anyone volunteer to get the node to work and make AudioStreamPlayer3D use it? (just fetch it instead of the camera, if active).

**Comment by reduz** [comment]
Probably needs a gizmo, too, so you can see L/R ears, as well as front/ back.

**Comment by CereEnder** [comment]
Hello! Can I ask why was this code commented? 🤔

**Comment by vnen** [comment]
> Hello! Can I ask why was this code commented?

The audio engine was rewritten for 3.0, so the old code doesn't make sense anymore.

**Comment by CereEnder** [comment]
I'll try to do something to work, but if someone can do it sooner than me, don't bother to do the pull request.

**Comment by mcccclean** [comment]
I've just run into this issue in my own project, I had a quick look at the source to see what'd be involved in fixing it as it did sound like a relatively straightforward thing to tackle. I'm assuming from the recent inactivity on this issue that it's a safe one to pick up; I have some free time coming up this week to work on a PR.

There're just a couple complications that I ran into that I was hoping to get some advice on before proceeding.

- AudioStreamPlayer3D calls `Camera::get_doppler_tracked_velocity`, which isn't present on Listener. What is a good course of action here? 
  - just add the method to Listener as well
  - lift the method up into Spatial
  - don't worry about it for this issue, just assume no doppler functionality on Listeners
  - something more involved? like, maybe Camera should inherit from Listener?
- The function to get "active listener" cameras reads from World::indexer, which is a map of cameras. Cameras are responsible for registering themselves into this index when they become current. Should the Listener nodes use the same pattern? Or should AudioStreamPlayer3D just traverse the scene tree for a current Listener at call time, and only look at cameras if there're no Listener nodes?
- Currently AudioStreamPlayer3D iterates over all cameras, adding up to `MAX_OUTPUTS` outputs. Does the scope of this issue cover multiple listeners, and do we need to account for a combination of listeners and cameras? Or is it fine to just use the first valid listener found?
- It's almost certainly out of scope for this issue, but does do Cameras need to have _two_ `current` values, one for rendering and one for listening?

(and, my apologies if I'm overthinking all this! thanks for your thoughts!)
