### ISSUE TITLE
Using VisualServer.request_frame_drawn_callback within such a callback results in infinite loop

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17761]
Godot 3.0.2

I am searching for a way to have a function being called once every frame/main loop iteration, but WITHOUT needing a reference to the scene tree, in order to use time slicing on a partially non-thread-safe task.

I've tried a recursive `call_deferred`, however calls are no longer "deferred" if scheduled within such callbacks, which results in a blocking infinite loop. But I thought it was normal because it's a queue being used behind the scenes and there isn't much reason why a callback wouldn't get executed next.

So I've tried `VisualServer.request_frame_drawn_callback`, which from its name, means callbacks get executed once a frame is drawn... BUT, the same infinite loop happens if I schedule a callback within such a callback, which this time makes less sense, because no frames have been drawn between the scheduling and the call.
Hence why I open this issue: is this really intented?

If that's not going to change, my only left alternative is to spawn a dummy thread whose only purpose is to call_deferred on the main thread every 16ms, which feels quite dumb...

**Comment by bojidar-bg** [comment]
@Zylann Can't you connect to `idle_frame` of the MainLoop? The MainLoop is the parent class of SceneTree, and is going to be always present in a running game.

**Comment by Zylann** [comment]
@bojidar-bg but can I access MainLoop in tool mode from outside the tree? (is it a singleton?)

**Comment by reduz** [comment]
Check VisualServer again, there are a few signals to do this:
```
ADD_SIGNAL(MethodInfo("frame_pre_draw"));
ADD_SIGNAL(MethodInfo("frame_post_draw"));
```
