### ISSUE TITLE
Show default property values in the editor

### ISSUE THREAD

**Issue by swenner** [godotengine/godot#1776]
Plaese make it possible to see the default value of a property in the editor. In addition it would be great to be able to reset it to its default using a hotkey or button.

**Comment by KoBeWi** [comment]
I guess the issue is fixed with the introduction of property revert button.

Unless revert + Ctrl + Z isn't a viable way to check default value and e.g. hovering over the revert arrow should display it as a tooltip.

**Comment by swenner** [comment]
Yes, the property revert buttons are awesome. Thanks!

**Comment by akien-mga** [comment]
> hovering over the revert arrow should display it as a tooltip.

That's a good idea IMO.

**Comment by swenner** [comment]
Should it be reopened to do the tooltip change? I'm happy already.

**Comment by akien-mga** [comment]
No, that's fine. If anything, a new issue could be opened for it. But I've had a quick check and the revert "button" is drawn directly as a texture and not an actual `TextureButton`, so adding a tooltip would imply making all those revert buttons Controls, so I don't know if it's worth the trouble.
