### ISSUE TITLE
Project crashes on Android if use 3d objects

### ISSUE THREAD

**Issue by maxim-sheronov** [godotengine/godot#17770]
**Godot version:**
3.0.2.stable

**OS/device including version:**
Android 7.0 / Xiaomi Redmi Note 4X / Adreno 506

**Issue description:**
App crashes if I use any 3d object on the scene.

**Steps to reproduce:**
You can open scene with 3d object with visible=false, then enable it and app will crash.

Log from logcat:
`
03-26 08:38:09.076: A/DEBUG(8127): pid: 8049, tid: 8070, name: GLThread 8731  >>> org.godotengine.godot3dcrash <<<
03-26 08:38:09.191: A/DEBUG(8127):     #11 pc 0062bb60  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (_ZN20RasterizerSceneGLES316_render_geometryEPNS_10RenderList7ElementE+816)
03-26 08:38:09.191: A/DEBUG(8127):     #12 pc 006286c8  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (_ZN20RasterizerSceneGLES312_render_listEPPNS_10RenderList7ElementEiRK9TransformRK12CameraMatrixjbbbbb+10716)
03-26 08:38:09.191: A/DEBUG(8127):     #13 pc 0063f31c  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (_ZN20RasterizerSceneGLES312render_sceneERK9TransformRK12CameraMatrixbPPN15RasterizerScene12InstanceBaseEiP3RIDiSB_iSA_SA_SA_SA_i+5516)
03-26 08:38:09.191: A/DEBUG(8127):     #14 pc 012f863c  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (_ZN17VisualServerScene13_render_sceneE9TransformRK12CameraMatrixb3RIDjS4_S4_S4_i+4508)
03-26 08:38:09.191: A/DEBUG(8127):     #15 pc 012f7434  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (_ZN17VisualServerScene13render_cameraE3RIDS0_7Vector2S0_+568)
03-26 08:38:09.191: A/DEBUG(8127):     #16 pc 0130f410  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (_ZN20VisualServerViewport14_draw_viewportEPNS_8ViewportEN13ARVRInterface4EyesE+544)
03-26 08:38:09.191: A/DEBUG(8127):     #17 pc 013105d0  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (_ZN20VisualServerViewport14draw_viewportsEv+1032)
03-26 08:38:09.192: A/DEBUG(8127):     #18 pc 012eba64  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (_ZN18VisualServerRaster4drawEb+96)
03-26 08:38:09.192: A/DEBUG(8127):     #19 pc 000d0e90  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (_ZN4Main9iterationEv+1120)
03-26 08:38:09.192: A/DEBUG(8127):     #20 pc 000881e0  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (_ZN10OS_Android17main_loop_iterateEv+20)
03-26 08:38:09.192: A/DEBUG(8127):     #21 pc 00098bf4  /data/app/org.godotengine.godot3dcrash-1/lib/arm/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+216)
03-26 08:38:09.192: A/DEBUG(8127):     #22 pc 0023526d  /data/app/org.godotengine.godot3dcrash-1/oat/arm/base.odex (offset 0x220000)
`

**Minimal reproduction project:**
[godot_3d_crash.zip](https://github.com/godotengine/godot/files/1846441/godot_3d_crash.zip)

**Comment by volzhs** [comment]
looks like duplicated with #12816

**Comment by maxim-sheronov** [comment]
You are right. So I close this
