### ISSUE TITLE
Light shading as if normals were flipped while culling works properly.

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#17776]
**Godot version:** 3.0 stable

**OS/device including version:** Arch Linux x64, RX 470, Mesa 17.3.6

**Issue description:** I modelled towers in Blender (file attached) and imported them in Godot (by using the better collada exporter). The towers are part of a bigger scene, but only the towers have the light shading *the other way around*. 

If a DirectionalLight is set up to face away from the front of the towers then the **front** will be illuminated. I double, triple and quadruple checked the normals in Blender.

![screenshot from 2018-03-26 15-13-09](https://user-images.githubusercontent.com/5209613/37909138-66235b1e-310a-11e8-9237-54fc0b2232fb.png)

Yet in Godot the following happens:

![screenshot from 2018-03-26 15-14-10](https://user-images.githubusercontent.com/5209613/37909155-76f2fcba-310a-11e8-8b5e-bd79039521a1.png)
![screenshot from 2018-03-26 15-14-23](https://user-images.githubusercontent.com/5209613/37909157-7717e89a-310a-11e8-93ce-fb9a69b2fce7.png)

**Steps to reproduce:**
Import the .dae file, open an inherited scene and add a DirectionalLight, then rotate the light around to see that the shading is the other way around.

**Minimal reproduction project:** 
[BuggyTowers.zip](https://github.com/godotengine/godot/files/1847988/BuggyTowers.zip)

**Comment by karroffel** [comment]
Those models were made using circles in Blender. I remade them with a cylinder shape and now it works, but I still think this is weird.

**Comment by Zylann** [comment]
Is it doing that too with OBJ? Are the normals flipped within the DAE file?
