### ISSUE TITLE
Minimum size for progressbar does not honour regionrect of custom background

### ISSUE THREAD

**Issue by Tubeliar** [godotengine/godot#17779]
**Godot version:** 3.0.2.stable.official

**OS/device including version:** Windows 10 Pro N 1709 x86_64

**Issue description:** If you set a custom background for a progressbar with a region rect selected, the minimum height for the progress bar is now determined by the height of the entire background image, not the height of the cropped region. I would expect the cropped region to set the minimum height.

**Steps to reproduce:** Assign a custom background to a progressbar and crop a region. The bigger the difference between the cropped image and the original the more prominent the effect will be.

**Minimal reproduction project:**
[Progressbar Region.zip](https://github.com/godotengine/godot/files/1848291/Progressbar.Region.zip)

**Comment by bojidar-bg** [comment]
Opened a PR about it, but keep in mind that you should probably set margins like that on the stylebox, so it would get a good minimum size:
![image](https://user-images.githubusercontent.com/5276727/38047052-f10c5652-32c9-11e8-996f-a78351b7970a.png)
