### ISSUE TITLE
Grid/pixel snapping does not work on rotated objects

### ISSUE THREAD

**Issue by ronroniv** [godotengine/godot#17781]
**Godot version:**
3.0.2 stable

**OS/device including version:**
Windows 7 64bit

**Issue description & Steps to reproduce:**
If you give objects rotation_degrees value other than the default 0, snapping dose not work on them.

![gd_pixel_snap_b](https://user-images.githubusercontent.com/25771553/37918234-61b05432-315b-11e8-8c03-723981707b54.gif)

**Minimal reproduction project:**
[Snap.zip](https://github.com/godotengine/godot/files/1848619/Snap.zip)

This is a very simple project with a Node2D scene with two Sprite children.

**Comment by groud** [comment]
Duplicate of #14496
