### ISSUE TITLE
AnimationSprite does not have a play_backwards function

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#17787]
**Godot version:**
`master` branch 928cdb4f8a72c2de5751cddd3205c2a3c09e6f6d

**Issue description:**
Currently AnimationPlayer has a member function for playing an animation backwards, but this is not true for an AnimatedSprite.

It would be great to have this functionality.

**Comment by girng** [comment]
well, they are two entirely different nodes for entirely different purposes imo, but i mean it could be a feature request i think
