### ISSUE TITLE
Export tileset arranges tiles by alphabet

### ISSUE THREAD

**Issue by kisiel090** [godotengine/godot#17786]
**Godot version:**
3.0.2

**Issue description:**
Exporting to tileset arranges tiles by their name alphabetically. I think this should be an option, not a default behavior which you can't change.

**Steps to reproduce:**

1.  make scene with child names not in alphebetical order
2.  export to tileset
3.  tiles in *.tres file are arranged alphabetically instead of their order in scene

**Comment by Zylann** [comment]
Note: the only place you could save that option in the case of exporting scenes is within the root node's metadata. It would also need an additional checkbox in the export dialog to set that option.

**Comment by kisiel090** [comment]
Oh, i just noticed that you can turn option to show tile ids in editor settings. I think this should be enabled by default, because that is solving this problem.

**Comment by Zylann** [comment]
@kisiel090 just to clarify, this is not going to change the order within  the `.tres`, it's only changes the displayed order ;)
