### ISSUE TITLE
load() not working on export

### ISSUE THREAD

**Issue by GalanCM** [godotengine/godot#1779]
I encountered this bug during the last Ludum Dare, and it seems to still be present in 1.1rc1. The load() function works fine in the editor, but fails in exported game with errors like the following:
```
ERROR: load_interactive: Condition ' err!=OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:1006.
ERROR: load: Failed loading resource: debug2.scn
   At: core/io/resource_loader.cpp:204.
```
I've tested it on rc1 in Ubuntu (15.04) and beta1 on Ubuntu (14.10), Windows 8, and OS X 10.10.

**Comment by reduz** [comment]
this should be working better now on github head, please test or wait for rc2

**Comment by eska014** [comment]
Assuming this is fixed.
