### ISSUE TITLE
NetworkedMultiplayerPeer lacks some exposed methods

### ISSUE THREAD

**Issue by lorenzobeccaro** [godotengine/godot#17798]
The only information exposed to GDScript of a remote peer is its id (int).
I propose to expose something like `get_remote_ip(int id)` and `get_remote_port(int id)` to facilitate anyone who want to implement some kind of NAT trasversal.

**Comment by lorenzobeccaro** [comment]
I was studying how this can be made and I thought adding a binding to GDScript would be easy modifying only networked_multiplayer_enet.h and networked_multiplayer_enet.cpp in modules/enet but it would be better to implement it in the super class NetworkedMutliplayerPeer also. I would make a PR to implement this but I haven't experience in C/C++ stuff so I don't want to do this in a wrong way.

Also, looking in thirdparty/enet I saw this:
https://github.com/godotengine/godot/blob/4b4ed9b72454dea13bd5f0935806519e67f13fbc/thirdparty/enet/godot.cpp#L189-L233

My first thought was to bind a method to expose EnetAddress from peer_map but I can't say it is the best way.

**Comment by bojidar-bg** [comment]
I think it would be better if only NetworkedMutliplayerPeerEnet exposes this information, since there might be NetworkedMutliplayerPeer-s which do not have an ip or a port.

**Comment by Faless** [comment]
Please consider that clients can't know other peers' IP/port except for id 1 (server) as they are not in direct communication.

**Comment by lorenzobeccaro** [comment]
Currently even the server can't know clients IP/port and this is bad in my opinion.
