### ISSUE TITLE
Setters/getters are not matched by in-editor documentation search

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#17796]
https://godot.readthedocs.io/en/3.0/classes/class_os.html

`OS.set_window_size(Vector2(100, 100))` is a fully functional function (no pun intended), but is not documented in the wiki or in the engine help. 
There is currently no function name or mention about the OS.set_window_size() function anywhere to be found.

Worth mentioning that the member variable window_size is there, but if it is intended to replace set_window_size, then it have not yet been disabled and removed from the newer Godot Engine.

**Comment by mhilbrunner** [comment]
No, members are not intended to *replace* setters and getters, setters and getters are just no documented anymore because 1.) it would just be duplicate information and 2.) it is considered more idiomatic to use the member

So just prefer `OS.window_size = Vector2(100, 100)`. AFAIK there are no plans to remove getters or setters, they just aren't documented seperately anymore in 3.0

**Comment by ivanskodje** [comment]
I disagree with that choice, as it would be both misleading and uninformative to those that are not familiar with the engine. 

However if this was a collective documentation choice, who am I to disapprove. :)

**Comment by girng** [comment]
@ivanskodje lmao, member variables are a pain in the butt at first, but i finally got used to em. took a while xD. they are a lot easier though and make the code cleaner  i do give them that.

in this case, it seems like set_window_size as mhilbrunner pointed out is just `window_size` (which is documented)
![](https://i.gyazo.com/e6458e781c39c37ed3c02dea16c54d44.png)

there is just so many things different in 3.0, as i'm an avid watcher of your online tutorials and subscriber i know it's prob a weird feeling coming back. but it's just part of the conversion process (i went throught it as well)

**Comment by akien-mga** [comment]
Note that if searching for `set_window_size` in the help search does not point you to `OS.window_size`, that should be fixed.

**Comment by FeralBytes** [comment]
@akien-mga how should the search be fixed? I am willing but would like to know how you think is best to proceed? As the search currently only yields Viewport.

**Comment by akien-mga** [comment]
As you see in the screenshot, `set_window_size(value)` is documented as the setter for `OS.window_size`. So it should be findable as a search result. Currently it seems not to be, so that has to be fixed by ensuring that setters and getters are part of the searched text data.
