### ISSUE TITLE
Texture option for environment settings

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#17794]
Just to have a bit of a discussion about this...

A little while back I started working on the CameraServer after discussing a potential approach with @reduz, this approach was implemented for iOS and OSX and used for ARKit and basically allowed for a camera feed to be taken from a webcam, or camera on the phone and used as the background in a viewport when rendering in 3D. This is still an open PR slotted for 3.1 as it needs to be enhance with Windows, Linux and Android support first.

However since then I've build a few GDNative modules that stream video or images to a texture (including one based off of VNC) and with some of the issues I ran into especially on Windows I've been thinking about implementing the Camera feed as a GDNative module on Windows instead of adding something into the core.

That got me thinking. It feels to me like the CameraServer overcomplicates things.

A much simpler feature would be to simply be able to set a background texture. A resource which is a subclass of our texture type can streams images from a (web)camera to this texture. 
Obviously you could fake this by just rendering a quad with the texture and do away with Camera Server all together but there is a lot to say for just having this as an option in the environment settings.

**Comment by Calinou** [comment]
@BastiaanOlij Is this issue still relevant nowadays?

**Comment by BastiaanOlij** [comment]
I don't think so, there is a CameraTexture now for use within your scene but I'm happy with how the background stuff works.

I'm hoping others will step in and start adding support for the other platforms but as far as this idea is concerned, I think we should kill this off.

**Comment by Calinou** [comment]
Alright, I'll close this then. If someone needs it, a proposal could be opened to make CameraTexture support more platforms.
