### ISSUE TITLE
SLN isn't updated to reflect file rename

### ISSUE THREAD

**Issue by QuestofIranon** [godotengine/godot#17805]
**Godot version:**
3.0.2 Mono version

**OS/device including version:**
Windows 10

**Issue description:**
Similar to  #17281. If a file is renamed in Godot, the sln and other project related files aren't updated.

**Steps to reproduce:**
 1. create a C# script
(may need to be opened in visual studio/ intellij rider first) 
 2. rename the script
 3. reload project in visual studio/ intellij rider

**Comment by vnen** [comment]
Duplicate of #12917.
