### ISSUE TITLE
Strange Error when changing to the next scene - C Error: Condition ' !f ' is true. returned: ERR_CANT_OPEN

### ISSUE THREAD

**Issue by Zlrxyy** [godotengine/godot#17814]
**Godot version:**
v.3.0.2 Stable

**OS/device including version:**
Gtx-1070

**Issue description:**

-Whenever trying to open scene or run game by debugging, the error below pops up. This is the only scene that shows this error, the others are fine. This error has never happened before until the latest thing I had done which was add a new rock model with a few pbr textures and an area node to warp to the third scene. The stack trace points to the code below at the function call 
`get_tree().change_scene("RealmOfDreams.tscn")`

```
0:00:02:0304 - Condition ' !f ' is true. returned: ERR_CANT_OPEN
----------
Type:Error
Description: 
Time: 0:00:02:0304
C Error: Condition ' !f ' is true. returned: ERR_CANT_OPEN
C Source: scene\resources\texture.cpp:424
C Function: StreamTexture::_load_data
```

**Code:**
```
extends VBoxContainer

#THIS IS A SCRIPT FOR THE MAIN MENU TO SEE IF WE ARE GOING TO START THE GAME UP OR OTHER OPTIONS

func _on_NewGameBtn_pressed():
	#CHANGE TO THE FIRST LEVEL OR SCREEN
	get_tree().change_scene("res://SCENES/RealmOfDreams.tscn") #STACK TRACE ERROR HERE

```

**Steps to reproduce:**
Tried to reproduce by adding new scene, adding the same models, ect. The error does not occur but for some reason the scene I have originally keeps causing the error. I tried to duplicate, rename, and change the scene to that but even the duplicate gives the error. Trying to delete everything in the scene also does not help. 

**Minimal reproduction project:**
None(At the moment)

**Comment by akien-mga** [comment]
Sounds like your made a typo in the scene name. Keep in mind that Godot is cross-platform, and thus case sensitive about paths, so if you're trying to load `res://SCENES/RealmOfDreams.tscn`, you need to make sure that it's in an all-caps `SCENES` folder with a PascalCase `RealmOfDreams.tscn` name.

Without reproduction project there's nothing else that can be done though, the error you're getting means "file not found" so it's quite likely what I described above.
