### ISSUE TITLE
System wide plugin install directory

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#17813]
It would be great (for some plugins) if there would be an option to install plugins system wide (not per project)

I'm thinking about plugins, like the Sketchfab store.

Of course they would be deactivated by default but just be listed in the plugins section of EVERY project.

On plugin download there could be an option which asks the user if the plugin should be installed system wide or just for that one project. (in the projects asset folder)

Maybe there also should be a flag in the plugin cfg if that is even possible since having team projects which rely on specific plugins would make collaboration a little hard.

But for plugins which are JUST tools and don't contain any scripts needed on export it is possible to have them system wide.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/831, as feature proposals are now tracked on the Godot proposals repository.
