### ISSUE TITLE
Doing an HTTPRequest inside the _init function fails silently.

### ISSUE THREAD

**Issue by sdfgeoff** [godotengine/godot#17824]
**Godot version:**
928cdb4f8a72c2de5751cddd3205c2a3c09e6f6d

**Issue description:**
Attempting to run `request()` on an `HTTPRequest` instance during the `_init()` function call does nothing. Checking `get_http_client_status()` informs us that the http_client remains at DISCONNECTED. Simply moving the `request()` call into the `_ready` function makes it work.

It doesn't matter to me that it can't be called in the `_init` function, but perhaps it should fail noisily?

This issue can be closed as I can't see it affecting anyone, but hopefully this will come up in a google search if someone else tries to do a `request()` inside the `_init` call.

**Comment by reduz** [comment]
if the node is not within the scene it will most probably not work, and yes
it should show some kind of error in the log, if it's not it's a bug.

**Comment by Noshyaar** [comment]
It prints `0:00:00:0549 - Condition ' !is_inside_tree() ' is true. returned: ERR_UNCONFIGURED` for me. I'll close this for now as it works as expected.
