### ISSUE TITLE
Zooming is not possible in internal documentation

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#17821]
**Godot version:**
4b4ed9b

**OS/device including version:**
No matter

**Issue description:**
 Currently zooming in internal documentation is not possible and this is bad for people with poor vision. The main problem to fix it, is the documentation uses different text drawing method - RichTextLabel instead TextEdit and its not possible(or I miss something ?) to just change the font size in one place.

**Comment by vnen** [comment]
You can change the font size in Editor Settings (under Text Editor > Help).

**Comment by Chaosus** [comment]
@vnen Thank you, I didnt saw it myself :S
