### ISSUE TITLE
Camera2D Jitter with Smoothing Enabled

### ISSUE THREAD

**Issue by behelit2** [godotengine/godot#17823]
This issue appears to be similar to [#15044](https://github.com/godotengine/godot/issues/15044)

Godot Version 3.0.2
Windows 10 (64bit)

I'm experiencing extreme jittering when using the smoothing feature on Camera2D. I'm using the example code from the kinematic character 2d demo. This behavior is not present in Godot 2.1.4

To reproduce, use the example project below. Pressing and holding left or right will produce slight jitter, followed by periodic "extreme" jitter at various intervals. It's almost like the camera update is completely out of sync when smoothing is enabled. If you disable smoothing in the Camera2D node, the problem disappears completely.

[Camera2d_Smoothing_Jitter.zip](https://github.com/godotengine/godot/files/1856348/Camera2d_Smoothing_Jitter.zip)

*Note: Platform eventually ends, with the player falling off. Press esc to exit.

**Comment by girng** [comment]
if you change `physics_process` to `_process` it removes the jitter

however, since  `move_and_slide` is being used
https://github.com/godotengine/godot/blob/53a2b0a5cec83628474b5f95312fd008e7c213ef/scene/2d/physics_body_2d.cpp#L1018

the internal delta for `move_and_slide` gets multiplied by a `physics delta`, which gives unexpected jitter across monitor rates, because camera2d is being updated at `get_process_delta_time`
https://github.com/godotengine/godot/blob/dcacf36118d14739db74f0acca61e3530e13673a/scene/2d/camera_2d.cpp#L146

**Comment by behelit2** [comment]
Hey, thanks for the reply girng. But unfortunately, setting _physics_process to _process does not fix the problem for me. In fact, it appears to be exactly the same. 

Is there a work around for this? It seems weird that smoothing would use get_process_delta_time. Do you think changing it to get_physics_process_delta_time would fix things? I guess it's time to learn how to compile Godot. :)

**Comment by girng** [comment]
hmm really? that's odd because i totally noticed the jitter and then changed to `_process` and it was gone. night n day.  let me mess with it some more

**Comment by behelit2** [comment]
Well, the slight jitter that is always present remained the same. The extreme jitter that happens at various intervals with _physics_process changed to this weird sort of "teleporting back and forth" jitter when switching to _process. I would like to remove the jittering all together, it kinda ruins the console platformer feel I'm going for. And preferably, I would like it to work regardless of monitor refresh rate.

**Comment by girng** [comment]
@behelit2 yeah, this has been an issue for quite some time... i've been trying to find a permanent solution for it since 2014 :P 

the closest i came to make movement work on all monitor refresh rates (on the current build) is:

- `move_and_slide` under `_process` **with a delta** (even though it says don't use it). must use a higher number for your speed variable however (since it gets multiplied again internally)
-  use the camera2d node on 3.0 or greater **and don't use smoothing**

if you want to use smoothing, you will have to **_craft your own camera smooth_** function using `get_viewport().set_canvas_transform(transformhere)`, and have this update in `_process` after the `move_and_slide` line.

this will be smooth movement across all monitor refresh rates. hope that helps

**Comment by behelit2** [comment]
It helps a lot! I still don't understand why get_process_delta_time is being used on smoothing. When would that ever be appropriate? Wouldn't you always want the camera sync'd up with the character's movement? Furthermore, why did this work perfectly in 2.1.4? Is that version using the equivalent of get_physics_process_delta_time? Sorry about all the questions.

**Comment by Norrox** [comment]
Ok so i think this problem occurs when the physics fps and the screen refreshrate is not the same.
if you change the physics fps to whatever your monitors refreshrate are it shuld work.
godot defaults the game fps to whatever refreshrate your monitor is, that means that your physics fps are default 60 and lets say your screen has a 120hz screen, godot set the fps of the main loop to 120.
so in order to temporarly fix this you can add this line in your game.
``Engine.set_target_fps(Engine.get_iterations_per_second())``
That will set the target fps to whatever you set your physics fps in Project Settings.
Shuld work, i use it. And please feel free to correct me if i am totally wrong here :P

**Comment by behelit2** [comment]
@Norrox At least in my case, I don't think this is the cause. My physics FPS is the default 60 and my monitor refresh rate is 60Hz. Both appear to be perfectly in sync and the problem remains. In fact, this is unchanged since I originally posted the problem. I believe girng is correct... Camera2d smoothing is using get_process_delta_time() when it should be using something based on the physics delta instead, his answer makes perfect sense. After all, when you turn off smoothing, the effect disappears completely.

**Comment by Norrox** [comment]
Ok, well im sorry i don't know then. i tried your example and inserted the code snippet i posted above and the jitter disappears for me :/

**Comment by behelit2** [comment]
@Norrox So, I tried inserting that code in both the example and an animation heavy project I'm working on. It not only does not remove the jitter with smoothing enabled, but it introduces a new problem. With and without smoothing turned on, the movement of the kinematic character became extremely choppy, like the animation frame rate dropped to 20fps or less. It's still showing 60fps in tests... But the animation quality is horrible, I feel like I'm going to have a seizure. 

Without that code snippet (and with smoothing turned off), the animation is as solid as a cartridge based game console. If you don't mind me asking, what kind of video card are you testing with? I'm using an Nvidia GTX 970.

**Comment by Norrox** [comment]
Oh, I'm using GTX 1070 and a a 34" ultrawide 4k monitor with 75hz

**Comment by behelit2** [comment]
> godot/scene/2d/camera_2d.cpp
> 
> Line 146 in dcacf36
```
 float c = smoothing * get_process_delta_time(); 
```

Do you think it would be worth it to recompile my own version of Godot with the above line changed to the following?

```
 float c = smoothing * get_physics_process_delta_time(); 
```
Would that not solve this issue entirely? Also, how severe is the move_and_slide issue with other monitor refresh rates? Surely the default movement method for 2d games is usable on more than just a 60hz monitor... Right?

**Comment by akien-mga** [comment]
@behelit2 This was actually changed the other way around by @poke1024 in #15060 to *prevent* jitter.

**Comment by behelit2** [comment]
I feel like having the camera2d use _physics_process and then having the camera smoothing use _process is like trying to pour gas into a diesel engine, it's not going to work right. It was never going to work right. I mean, I can't be the only one who sees this, right? The camera smoothing works inside the camera2d itself, and is in fact activated as a camera2d option. If one is running at a consistent 60fps and the other is running at an arbitrary XXfps, how on Earth is that EVER going to run consistently and reliably? Seriously, someone show me one situation where both scrolling camera2d and camera smoothing are both being used (simultaneously) and the resulting animation is clean, smooth, and correct looking. I don't think it's possible.

**Comment by akien-mga** [comment]
@behelit2 Both scrolling and smoothing use `NOTIFICATION_INTERNAL_PROCESS`, there's no physics process used at all in Camera2D. https://github.com/godotengine/godot/blob/master/scene/2d/camera_2d.cpp

**Comment by behelit2** [comment]
@akien-mga Okay, apparently you understand something about this that I don't... Yet are failing to see that there is a issue here. Lets break this down.

1. Camera2d, when focused on the player and scrolling along, uses what? Physics process or process?
2. Smoothing, a checkbox inside the the Camera2d node, uses what?  Physics process or process?
3. Does Camera2d and Smoothing sync up perfectly when spitting frames out to the monitor? Yes or no?
4. If Yes, why is there a visual jitter / choppiness with smoothing enabled?
5. If no, why is the answer not yes?

I don't mean to sound like a idiot... But it would really help me as a game developer if someone could answer the above questions clearly and concisely, and without referring to multiple previously closed issues.

**Comment by akien-mga** [comment]
> Yet are failing to see that there is a issue here.

I never said that there wasn't an issue, just that the `physics_process`/`process` internal clash is likely not the reason, since Camera2D doesn't use `physics_process`.

**Comment by behelit2** [comment]
@akien-mga Look... I really don't care what the problem is, or who caused it, or why it's not working. All I really care about as a person creating a video game is "Does this feature work as expected, or not?". 

Clearly, it's not working as expected. Godot 2, add kinematic 2d character, add camera2d, click smoothing checkbox... BOOM! It behaves exactly as expected. Do the same thing in Godot 3? Unexpected, jittery, broken behavior. I don't care if it's a physics process, internal notification, whatever. The moral of the story is... You click the smoothing checkbox, it doesn't work as expected. 

I've learned to live without it, because I've been working on a game since March with no progress on this issue, thinking I'll just add it back when it gets fixed. I didn't mean to be offensive or rude, I quit smoking recently and I appologize. I'm just trying to figure out if this will ever be solved, or if I should just get used to not having this feature and craft my own camera code. 

I think, personally, if the smoothing enabled by the Camera2d node checkbox is broken and always produces unexpected behavior, I would just remove the stupid check box leave a note telling people to craft their own smoothing code. It would save people a lot of stress. LOL Don't give people hope where there is none.

**Comment by ejnij** [comment]
Repeat what I wrote in a different issue related to this - 
For me camera smoothing causes jitters if physics fps < monitor hz (and actual fps is higher than physics). If physics fps is higher than monitor hz then it's fine, but then it's kind of a waste of resources? Being able to adjust physics fps in a similar way to what Juan said here - https://twitter.com/reduzio/status/984783032459685890 would be great.
Not sure when it would be implemented though.

**Comment by behelit2** [comment]
Something has changed, my example jitters with and without smoothing enabled. However, the game I'm developing still works fine without smoothing enabled. Not sure what the deal is. 

Seriously folks, can anyone produce an example of a kinematic based 2d platformer (with Camera2D smoothing enabled) that doesn't produce game breaking jitter? If not, how is this not getting more attention? This feature is straight up broken. I understand 3D is getting all the love these days, but don't break perfectly working 2d features in the process please!

**Comment by reduz** [comment]
reported closed here:
https://github.com/godotengine/godot/issues/25162#issuecomment-457055902

**Comment by behelit2** [comment]
I'm happy to report that I tested this functionality in my main project using 3.1 beta 2, and it appears to be completely resolved.

**Comment by securas** [comment]
There is still a little bit of weirdness when the camera is smoothing to stop.

**Comment by securas** [comment]
> reported closed here:
> [#25162 (comment)](https://github.com/godotengine/godot/issues/25162#issuecomment-457055902)

There is still some weird behavior when smoothing to stop in 3.1 stable, unfortunately.

**Comment by lukad** [comment]
I'm experiencing jittering Kinematic2DBodys when Camera2D smoothing is enabled in 3.1.1 stable.
It stops jittering when I set the physics FPS to my monitor's refresh rate, 144hz. Unfortunately that makes my move_and_slide physics go twice as fast and that seems like another bug to me. The documentation says that I shouldn't multiply my velocity vector with delta because that is handled by move_and_slide.

**Comment by akien-mga** [comment]
@lukad setting Camera2D's process mode to Physics Process might fix it.

**Comment by lukad** [comment]
@akien-mga that fixes it, thanks a lot!

**Comment by StiliyanKushev** [comment]
> @lukad setting Camera2D's process mode to Physics Process might fix it.

I love u <3 :D

**Comment by MaxMarauder** [comment]
Currently experiencing jittering with Camera2D smoothing (at the end of it) in 3.2.2. 
Especially noticeable on parallax backgrounds, but also present on normal tiles.
Using KinematicBody2D + move_and_slide()
Checked monitor refresh rate - it's 60, same as Physics fps.
Switching Camera2D process mode between Idle and Physics has no effect.
Any suggestions?

**Comment by bunman** [comment]
> @lukad setting Camera2D's process mode to Physics Process might fix it.

Hi guys I am pretty new to Godot. Any tips on how to do this exactly? Thanks!

**Comment by Calinou** [comment]
> Hi guys I am pretty new to Godot. Any tips on how to do this exactly? Thanks!

- Select the Camera2D node in the Scene tree dock.
- Go to the Inspector, set Process Mode to **Physics** instead of **Idle**.

**Comment by bunman** [comment]
> > Hi guys I am pretty new to Godot. Any tips on how to do this exactly? Thanks!
> 
> * Select the Camera2D node in the Scene tree dock.
> * Go to the Inspector, set Process Mode to **Physics** instead of **Idle**.

That worked very well, thanks!

**Comment by git2013vb** [comment]
@Calinou Hi, 
Using v3.4.beta4.mono.official [6a058cbf3]
In Debian 11

set in code C#:

```
  ProcessMode = Camera2DProcessMode.Physics;
  SmoothingEnabled = true;
  SmoothingSpeed = 5;
```

I have Jitter problems.

If I set `SmoothingSpeed = 0;` Jitter disappear together width smooth  :)

**Comment by Calinou** [comment]
@git2013vb This issue will only be fully resolved out of the box once https://github.com/godotengine/godot-proposals/issues/2753 is implemented. In the meantime, install, enable and configure lawnjelly's [smoothing-addon](https://github.com/lawnjelly/smoothing-addon).
