### ISSUE TITLE
KinematicBody2D's get_slide_count  sometimes misses collisions

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17835]
**Godot version:**
13d5ee0

**Issue description:**
The KinematicBody2D's method `get_slide_count` can sometimes miss some collisions, depending of the speed of the body itself (at least that seems to be the reason).

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/1858305/Test.zip)

**Comment by eon-s** [comment]
Really weird, increasing the higher jump from 1400 to 1500 gets the slide again.

**Comment by mrcdk** [comment]
Looks like it's somehow hitting this code https://github.com/godotengine/godot/blob/master/scene/2d/physics_body_2d.cpp#L1049-L1054 setting `slope_stop_min_velocity` to 0 registers the collider. Looks like a bug.

**Comment by reduz** [comment]
Can anyone try this one again? I think it should be fixed by now

**Comment by reduz** [comment]
I remember someone fixed the function because it was missing collisions

**Comment by aaforcebox** [comment]
Tried on 3.1.alpha.official and the problem is gone!! So the bug is only 3.0.6 and earlier versions.

**Comment by YeldhamDev** [comment]
@reduz It's... fixed-ish? This used to print "Hit detected!" only when first touching the ground, and not it continuously prints it while being touched. So I'm not really sure.

**Comment by reduz** [comment]
Yes, this is clearly fixed
