### ISSUE TITLE
Compile failed on windows

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#17843]
**Godot version:**
4dbae5a738e33ffe4ab69e84c006bff2adc24cf8

**OS/device including version:**
windows7 sp1 x64
MSVC 14.1

**Issue description:**
KeyError:PROJECTSUFFIX
![011](https://user-images.githubusercontent.com/24988459/38091697-e4e61fb4-3398-11e8-9123-4d06969d243f.PNG)

It's **NOT** like #17551 

It seems to be a Sconstruct error.
What's happen?
How can I fixed it?

**Steps to reproduce:**
scons platform=windows vsproj=yes
**I had tried no vsproj.It works fine.But do not work with ```vsproj=yes```.**

**Comment by ShyRed** [comment]
Works fine on my machine.

Might be an issue that depends on the Python & SCons version that is used?

My setup:
```
c:\Work\godot>python --version
Python 3.6.4

c:\Work\godot>scons --version
SCons by Steven Knight et al.:
        script: v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668, 2017/11/14 13:1
6:53, by bdbaddog on hpmicrodog
        engine: v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668, 2017/11/14 13:1
6:53, by bdbaddog on hpmicrodog
        engine path: ['C:\\Program Files\\Python36\\scons-3.0.1\\SCons']
Copyright (c) 2001 - 2017 The SCons Foundation
```

**Comment by TailyFair** [comment]
Same issue.
Setup:
- Windows 10 64 bits
- Python 3.6.5 (32 bits)
- Scons 3.0.0

**Comment by T4g1** [comment]
Same problem, same fix here. I think you are supposed to run it that way so the Visual Studio environment variable are set. Maybe it should be specified in the documentation ?

**Comment by fire** [comment]
Can someone try https://github.com/godotengine/godot/pull/22026? This has been annoying me.
