### ISSUE TITLE
Assigning an Object as a parameter in a Call Func Track callback doesn't work

### ISSUE THREAD

**Issue by samdze** [godotengine/godot#17841]
**Godot version:**
Godot 3.0.2 stable official.

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
Right now assigning an Object as a parameter in a callback in a Call Func Track doesn't work.
Clicking on the value dropdown makes nothing happen and nothing seems to be drag & droppable.
![immagine](https://user-images.githubusercontent.com/19392104/38084201-3ad23f54-334c-11e8-94f8-80d9cb8aa988.png)

**Steps to reproduce:**
Create an AnimationPlayer node, new animation, new Call Func Track, add a callback with a parameter of type Object.

**Comment by Zylann** [comment]
Although it's possible to have objects in here, I don't think the UI lets us assign anything here currently. There is a similar issue with the signal additional parameters when you connect them from the editor.

We should be able to drag in resources or even nodes, and mayyybe create new objects in it.

**Comment by samdze** [comment]
Yes, I think the same functionality of an array in the inspector should be provided.
![60iqffl](https://user-images.githubusercontent.com/19392104/38087222-9dafa854-3357-11e8-9908-75bbcbf256ca.gif)
Regarding nodes, as they are not Resources, a wrapper resource type could be created? I

**Comment by Zylann** [comment]
Nodes are Objects so they can theoretically fit in the array, however they can't be serialized as is, unless they are stored as node paths (which brings us to this existing issue: https://github.com/godotengine/godot/issues/7821)

**Comment by samdze** [comment]
The ability to export node types directly would be cool.
So yes, I guess if that propose succeeds nodes should be assignable here too, maybe resctricted to nodes owned by the same scene that owns the AnimationPlayer in use.

**Comment by samdze** [comment]
Closing as this works now with the new AnimationPlayer editor.
