### ISSUE TITLE
Duplicated Particles2D do not act independently

### ISSUE THREAD

**Issue by admiralzeech** [godotengine/godot#17852]
**Godot version:**
3.0.2 (steam version)

**OS/device including version:**
Windows 10

**Issue description:**
I have a one-shot Particles2D which I want to emit a spray of particles every time a character is hit.

However, from the 2nd time onwards, when I toggle .emitting to true, nothing happens until the onscreen particles have disappeared.  I can't get another spray of particles to emit whilst the first is onscreen.

This might be a design limitation of Particles2D, so I tried to work around it by creating an array, filling it with particle_effect.duplicate(true), and then toggling the .emitting property of each one in succession.

However, this does not change the behaviour - when toggling .emitting on the next item in the array, it's still ineffective until the first particle spray is finished. (or rather, some undetermined time afterwards.)

**Steps to reproduce:**

I have a Particles2D with various settings, created in the visual editor.  OneShot = true.

I fill my array with the following code:

hit_effect_array.append($hit_effect)
for i in range(NUM_HIT_EFFECT):
    hit_effect_array.append($hit_effect.duplicate(true))

And trigger them thusly:

if (curr_hit_effect >= NUM_HIT_EFFECT):
    curr_hit_effect = 0
	
print(hit_effect_array[curr_hit_effect].emitting) ## TEMP
hit_effect_array[curr_hit_effect].emitting = true
curr_hit_effect = curr_hit_effect + 1

Are the duplicated Particles2Ds supposed to work independently?   Is there any other way I can achieve what I want?

Even if I dynamically create new Particles2D in code, there's no signal or any way to tell that the effect is finished, so that I can delete them to cleanup.

Ideally there would be a signal when all particles from a oneshot are gone.  Even better, an emit() function that I can call at will.

**Comment by aron3097** [comment]
restart? 
I do it with restart().

**Comment by admiralzeech** [comment]
Ok, whilst getting a sample project together I figured out my problem.  When I duplicate the Particles2D nodes in code, I forgot to add them to the tree. (Or rather, didn't know that I needed to.)

I'll close the ticket, sorry for the false alarm.


For future readers, here's another suggestion from reddit that seems like it would work well:

I just create an instance of a Particles2D scene (emitting = false; oneshot = true), set emitting = true, add it to the scene tree and when it's not emitting anymore I call queue_free(). That works without problems.

# In the Particles2D script.
func _process(delta):
    if not emitting:
        queue_free()
