### ISSUE TITLE
Built-in script isn't saved after it was edited

### ISSUE THREAD

**Issue by santouits** [godotengine/godot#17853]
**Godot version:**
master

**OS/device including version:**
ubuntu 17.10

**Issue description:**
### Scene built-in script isn't saved when:
- _you press Play(F5)_
- _you press Play Scene(F6)_
- _you Save All Scenes_
- _you Save All (scripts)_

### It is saved when:
- _you Save Scene_

**Steps to reproduce:**
Create a new project
Add a node
Add a built-in script
Run the project
Edit the built-in script
Run the project again

**Comments**
It seems to work in 3.0.2

**Comment by Noshyaar** [comment]
It is indeed a duplicate, but there are some helpful info here that aren't in the original issue. It'd be much appreciated if you would copy them to the original issue. I'd close this for now. Thanks a lot.
