### ISSUE TITLE
Godot crashing upon startup on Windows 10

### ISSUE THREAD

**Issue by reaply** [godotengine/godot#17856]
**Godot version:3.0.2**
**Windows 10 **
**NVIDIA 1070 on driver version:  391.01 (and previous versions)

**Godot crashing upon startup**
Upon starting up Godot with a fresh new download everything will work properly. Once I create a project, close Godot and try to launch Godot again, it will crash upon initializing graphical settings/ hardware information. 

**I am aware this isn't a common issue but it has been frequent with some users.**

**Comment by reaply** [comment]
I have also found a solution. Once Geforce overlays are disabled AND Discord is closed and doesn't have a process anymore, Godot will running properly. Something about Discord hooking into the Godot process is causing it to crash.

**Comment by eon-s** [comment]
Probably related to #17157 and #17575 (amd but who knows).

**Comment by reaply** [comment]
@girng 
No, no third party anti-chat program.

@eon-s 
There is no error log for this as it's an instant crash.

**Comment by Zireael07** [comment]
I'm often running Discord along with Godot with no problems (but I have game integration/overlays disabled)

**Comment by reaply** [comment]
Strange, now it’s crashing again even with discord closed. I don’t know what’s causing the issue anymore.

**Comment by reaply** [comment]
Upon further research I have found some dump files. The exception is 0xE0464645, and in dissasembly RaiseFailFastException is being thrown and stops at a compare pointer BaseIsSecureProcess.

**Comment by reaply** [comment]
Alright, I found solution finally. This issue is a pushed updated from Intel about spectre. There were a lot of reports that their update corrupted a lot of files and this includes even system files. To see what files are corrupt you will need to run an SFC scan and fix your corrupted files. (If you're lucky like me you will have had corrupted graphics drivers causing the issue with Godot not starting properly.) I have ran Godot 15 times now and it hasn't crashed again since then.

**Comment by Rubonnek** [comment]
Welp, that's great to hear! I have seen audio drivers crash thanks to all these "proper" spectre patches, but it's the first time I heard about graphics drivers getting corrupted. Good to know.

**Comment by olejr** [comment]
SFC scan didn't find any errors her, and Godot still crashed ramdomly.
Then I updated my gfx drivers (gtx1070) from 391.24 to 391.35, 
and my sound drivers just for good measure. 
And something there seem to have fixed the crashing here also.

**Comment by Arax89** [comment]
Same thing for me. Sometimes I got past the launcher, but most of the time Godot just crashes right away. Downloaded and run Godot via Steam. 
System Specs: 
- Intel i7-7700HQ
- Nvidia GeForce GTX 1070 (Notebook) 
- 8 GB RAM
Windows 10x64  Build 10.0.16299.309

**Comment by akien-mga** [comment]
It's impressive how broken Windows 10 can get each time they push an update..

**Comment by f-rank** [comment]
Getting crashes (about 80%+ of the time) at launch with 3.0.2 on windows 10.0.16299.371, sometimes it will crash after hitting play also (around 50%). System has 32 GB ram and a nvidia 1070, i7 6820HK proc.

**Comment by olejr** [comment]
And update from me:
Today after installing yet another big update from Microsoft, version 1803 build 17134.1
and updating nvidia drivers to 397.31.
The crash problem have fixed itself.

**Comment by Norrox** [comment]
None of the above solutions worked for me. the only thing working is switching to linux :)

**Comment by akien-mga** [comment]
Sadly I don't see anything that we could debug further/try to fix in Godot here, it seems to be official Windows 10 updates breaking the system and causing Godot to crash.

As such I'll close the issue as there's nothing we can do to solve it. Godot 3.1 might alleviate the issue with OpenGL 2.1 support, as I suspect issues arise with bogus OpenGL 3+ support in many Windows drivers.
