### ISSUE TITLE
Reflection Probe in interior shouldn't render objects with sky's radiance applied

### ISSUE THREAD

**Issue by Ryptun** [godotengine/godot#17868]
I created that simple interior to show the problem
![1](https://user-images.githubusercontent.com/13279737/38143047-2007407c-343f-11e8-9de5-5b1eab3da448.PNG)
List of objects in scene:
- This room (white)
- cube (green)
- plastic sphere (slightly red (on left))
- metalic sphere (slightly red (on right))
- point light (white)
- reflection probe with **interior on** (and black ambient occlusion)
- world environment node with **blue** sky

As you can see sky is the only one object that can make anything in this scene blue. 
In this closed room you can see blue reflection in sphere anyway
![2](https://user-images.githubusercontent.com/13279737/38143693-00389644-3442-11e8-9e76-b8ddfd8d6d10.PNG)
Reflection Probe is applying sky's radiance on objects while creating his own radiance cubemap - in my opinion it should use probe's ambient color as radiance while **interior is on**

In my opinion this room should look like this
![3](https://user-images.githubusercontent.com/13279737/38143747-3dbbe7d2-3442-11e8-869a-21a51d689ef9.PNG)
To achieve this I had to set sky color to black

**Comment by DEF7** [comment]
I'm trying to make sense of what you're saying, because it looks like you just need to tweak the material on your sphere. When I turn on 'interior' it doesn't blend the sky with the reflection map at all, using 3.0.2.

Although, disabling interior, it will show if I have an environment map sky, but not if I set a custom color for the sky.

**Comment by Ryptun** [comment]
@DEF7 Problem is that the sky's ambient color is already included in reflection map. It renders this same cubemap no matter if you select interior or not. Reflection probe in interior should use some kind of it's own _Environment_ for rendering that cubemap.
And it doesn't depends on material. Materials should work no matter where they are

**Comment by reduz** [comment]
This is what interior is for, is it not working?

**Comment by Ryptun** [comment]
> 
> 
> This is what interior is for, is it not working?

Screens were made with interior setting on. The problem lies in how this node is creating cubemap image - it just applies the lightning from environment. Other example here, metallic sphere shows how the cubemap image looks like. 
![1](https://user-images.githubusercontent.com/13279737/45587911-90823a80-b90c-11e8-9f56-1ea9889df8b5.PNG)
