### ISSUE TITLE
Add functionality to move selected tiles in tile map editor

### ISSUE THREAD

**Issue by covariantlabs** [godotengine/godot#17862]
**Issue description:**
Currently, there is no easy way to move a set of tiles in the tile map editor. There are already options to select a set of tiles and to remove or duplicate the selection elsewhere, so it feels like adding an option to move the selection is a natural way to extend this functionality. This would be helpful in situations where the user wants to move a large set of tiles by a small distance.

**Proposal:**
Adding an option "Move Selection" to the "Tile Map" menu in the tile map editor. When a set of tiles is selected and the "Move Selection" option is chosen, the selected tiles are "attached" to the mouse cursor, similar to the current functionality of "Duplicate Selection". When the left mouse button is pressed, the selected tiles are moved to the new location. When the right mouse button or the escape key is pressed, the tiles remain unchanged.

**Comment by akien-mga** [comment]
Fixed by #17863.
