### ISSUE TITLE
Camera spins when switching to a scene with different view rotation 

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#17870]
**Godot version:**
![image](https://user-images.githubusercontent.com/7307968/38145946-13a52134-344c-11e8-9be3-a1bb2c1f9ef5.png)

**OS/device including version:**
Windows 10 64

**Issue description:**
When view was rotated in a spatial scene, the camera spins when switching to a scene with different view rotation (bigger than 360 degrees difference).

**Steps to reproduce:**
Create spatial scene, rotate view around multiple times (on y axis), switch back and forth between another spacial scene.

**Comment by vnen** [comment]
Duplicate of #11764.
