### ISSUE TITLE
HTTPClient.query_string_from_dict incorrectly encodes

### ISSUE THREAD

**Issue by VitaZheltyakov** [godotengine/godot#17875]
**Godot version:**
All versions (2.1.x and 3)

**OS/device including version:**
All

**Issue description:**
`HTTPClient.query_string_from_dict` does not encode non-English characters correctly (see examples). Now non-English characters are transformed into an unconvertible construct.
An error occurs when the `String.http_escape` is running (`core/ustring.cpp`).

I ask you to pay attention to this problem. Because of this problem, normal operation over the HTTP protocol is impossible.

**Steps to reproduce:**
Now:
`var dic = {
	'arg1' : 'Ж',
	'arg2' : foo
}`
`print(http.query_string_from_dict(dic))`

Return `arg1=%FFD￸EQ&arg2=foo`. This is wrong. 
Need: `arg1=%D0%96&arg2=foo`

**Comment by akien-mga** [comment]
CC @RandomShaper who looked at `String::http_escape` recently.

**Comment by RandomShaper** [comment]
Addressed in #17583.
