### ISSUE TITLE
Add an option to MS Windows Binary to launch without console window

### ISSUE THREAD

**Issue by chris-me** [godotengine/godot#17889]
**Godot version:**
3.0.2

**OS/device including version:**
Microsoft Windows 10

It would be nice to have an option to launch the engine without an attached console window on Windows OS. 

Just little thing, but it makes switching between Godot and other applications one click more, which adds up when switching often. It also gets confusing when having more then one Godot instance open.

**Comment by Calinou** [comment]
The editor is best used with a console window because some errors aren't displayed in the editor window – those are usually bugs, but can also be a result of user error.

Note that release-mode Windows export templates will not spawn a console window (debug-mode Windows export templates will spawn one though).

**Comment by vnen** [comment]
I've actually been thinking about this a while ago. I agree with @Calinou that the console is quite useful, but only on Windows the console is shown, so cross-platform behavior is not quite consistent. If you need the messages you could open via command prompt, like you need to do with Linux or macOS.

**Comment by Megalomaniak** [comment]
> @Calinou commented
> 
> The editor is best used with a console window because some errors aren't displayed in the editor window

log > temp file > disk

**Comment by Timofffee** [comment]
![2](https://user-images.githubusercontent.com/5556081/40628910-90a84b7c-62d0-11e8-9ddc-f9df3911b603.gif)
Okay... But I can hide it in a Blender.

**Comment by Timofffee** [comment]
WinAPI has 2 methods:
ShowWindow() and GetConsoleWindow(). 
Thanks to them, you can change the visibility of the command line. 

For example like this done in Blender:
![image](https://user-images.githubusercontent.com/5556081/44226358-8ef01600-a198-11e8-8397-fa191c958634.png)

It seems to me that it will be quite easy to add such functionality to Godot, but I do not have the opportunity :(

**Comment by dedraks** [comment]
I downloaded the source code and added a code to toggle the console window on F12 key press.

**Comment by Zireael07** [comment]
@dedraks: mind making a PR?

**Comment by sinni800** [comment]
Please do, @dedraks

**Comment by lukad** [comment]
It seemed like no one was working on this at the moment, so I created #24448 which basically mirrors Blender's behaviour. Feedback would be appreciated.

**Comment by stereoa** [comment]
I just googled to see if this was possible and it was added a couple minutes ago. Very surreal and very awesome!

**Comment by Skaruts** [comment]
Meanwhile I've been working around this since godot 2 by opening one command line and running several instances of godot from that same command line. 
Would there be any caveats to doing this? Any conflicts or anything?

**Comment by Quest79** [comment]
The console being useful is not really the point. If you become advanced enough to need the console, it should be clear where it is. It is bad UX to have a console launch along with the main application and sit with no option to hide/unhide like any other (useful) UI element. It being a window outside of the main Godot window makes this even more in eed of this toggle. Some of us have multiple projects open and its, pardon my french, a bit of a shitshow with the consoles getting in the way as well. This feature should be opt-in and off by default. Voted in favor or this. (and if it can be put into the main app along with Debugger etc on the bottom, even better)

**Comment by akien-mga** [comment]
Guys, it's implemented already...

**Comment by HonorsoftEntertainment** [comment]
It's 2020, I am currently starting work on a Godot "assistant application" which enhances Godot, I have had issues with the console window too, and after researching about Godot's console online, it looks like it is still a problem. So I will add a custom plugin for Godot that will allow different methods of displaying any log or console text. I am testting different methods, including adding a console display to Godot to remove the 2nd console window.

**Comment by Calinou** [comment]
@HonorsoftEntertainment You can hide the console window using **Editor > Toggle Console Window**.

**Comment by HonorsoftEntertainment** [comment]
> @HonorsoftEntertainment As of Godot 3.2, you can hide the console window using **Editor > Toggle Console Window**.
Yes, but isn't that just for builds? I read that the console window is always shown in the Godot Editor. I have read complaints about the old-style console windows, and I have a few too. I think a better console output is needed for Godot, maybe with improvements added like a proper text copy paste system which console simply don't have.

**Comment by Calinou** [comment]
@HonorsoftEntertainment The option I mentioned is available in the editor.

**Comment by akien-mga** [comment]
It doesn't work with Windows 11's new terminal, you should use Godot 3.5.
