### ISSUE TITLE
"Server disconnected!" error sometimes when stopping the game in the editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17882]
**Godot version:**
 d2eb731

**OS/device including version:**
Manjaro Linux

**Issue description:**
When stopping the game in the editor, sometimes this error message will be printed out:
`drivers/unix/stream_peer_tcp_posix.cpp:276 - Server disconnected!`

**Comment by Dimonasdf** [comment]
Sometimes I can't initially play the project, as it is saying Server disconnected. But this only happens when I have multiple instances of Godot running (not of the same project, though, and without any other project already playing). Probably not related, bit still.

**Comment by VitaZheltyakov** [comment]
https://github.com/godotengine/godot/issues/15393

**Comment by YeldhamDev** [comment]
Can't reproduce this anymore, closing it.
