### ISSUE TITLE
Editor crashes when changing playback device

### ISSUE THREAD

**Issue by GammaGames** [godotengine/godot#17892]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10 Pro v10.0.16299

**Issue description:**
When you have a project open and change the default playback device the editor will sometimes crash. 

**Steps to reproduce:**
1. Open a project in godot
2. Open the "Playback Devices" window
3. Change the playback device
4. Editor will sometimes crash

I haven't been able to detect the exact conditions, since it sometimes doesn't crash. Sometimes the projects have been open all day and sometimes I've opened them five minutes ago.

**Minimal reproduction project:**
I've had it happen with multiple projects, but I know I've had it happen with this project:  
https://github.com/turtletooth/GodotFirstPersonController

**Comment by vnen** [comment]
Possibly the same as #17453, which was fixed on master.

**Comment by GammaGames** [comment]
Good call! I'll close this, and if the problem still persists it can be reopened.
