### ISSUE TITLE
KinematicBody2D move_and_collide() sliding slope problem

### ISSUE THREAD

**Issue by Jvanmourik** [godotengine/godot#17895]
**Godot version:**
3.0

**OS/device including version:**
macOS High Sierra

**Issue description:**
KinematicBody2D slides slowly of a slope when applying constant downwards movement using move_and_collide(). Expected it to come to a complete stop after first collision with slope.

**Steps to reproduce:**
- Create KinematicBody2D with a collisionShape2D (e.g. new capsuleShape or new rectangleShape).
- Add a script to the KinematicBody2D:
```
extends KinematicBody2D

func _physics_process(delta):
	var motion = Vector2(0, 300) * delta
	move_and_collide(motion)
```
- Create a slope using rigidBody2D using a collisionPolygon2D

**Minimal reproduction project:**
[kinematicBody2D_slide_problem.zip](https://github.com/godotengine/godot/files/1865957/kinematicBody2D_slide_problem.zip)

**Comment by eon-s** [comment]
The problem may be related to some precision issue after the collision resolution due to the big (default) safe margin, try reducing it to 0.01 or less.

**Comment by Jvanmourik** [comment]
@eon-s How do I change this margin?  Looking through the C++ code I can see that the method body_test_motion has a margin, is that the margin you are referring to?

**Comment by eon-s** [comment]
Select the kinematic body, the first property in the inspector.

**Comment by Jvanmourik** [comment]
Aah, reducing it to 0.01 solves this issue! Thanks a lot, I will close this one.
