### ISSUE TITLE
Float rounding

### ISSUE THREAD

**Issue by BBric** [godotengine/godot#1789]
```GDScript
var n1 = floor(0.220 * 100) / 100
var n2 = floor(0.221 * 100) / 100
print(n1) # 0.21 ?
print(n2) # 0.22
print(n1 == 0.21) # false ? (should be false if n1 == 0.22 but should be true if n1 == 0.21)
print(n1 == 0.22) # false ?
print(n2 == 0.22) # false ?
```

**Comment by swenner** [comment]
Floating point numbers implemented in current computers can not represent every number accuratly.
You should never directly compare two floating point numbers for equality.

do this instead:
print(abs(n1 - 0.21) < 0.0001)

More details here: https://en.wikipedia.org/wiki/Floating_point#Accuracy_problems

**Comment by BBric** [comment]
I know this problem but i never know when it appears. With a defined number of decimals i thought that it was sure, but it seems that not. It's good to know, thank you.

**Comment by guilhermefelipecgs** [comment]
I don't understand why godot convert n1 to 0.21 yet.
I tested in other languages, inclusive in C, and all return 0.22.
Anyone can explain this?

**Comment by reduz** [comment]
yeah godot uses the regular C operators for scripting, so this is the same as C
