### ISSUE TITLE
Mac force reboots when clicking something in the app

### ISSUE THREAD

**Issue by LTheGreats** [godotengine/godot#17908]
**Godot version:**
v3.0.2

**OS/device including version:**
mac OS High Sierra (10.13.2)
iMac (27-inch, Mid 2011)
processor 3.4 GHz Intel Core i7
Memory 8gb 1333 MHz DDR3
Graphics AMD Radeon HD 6970M 1 GB

**Issue description:**
When I started the app for the first time seemed to work, but when I clicked on anything in the app it forced my computer to restart.

**Steps to reproduce:**
1. Get the mid 2011, 27-inch iMac or a Mac with similar specs.
2. Download [Godot v3.0.2](https://downloads.tuxfamily.org/godotengine/3.0.2/Godot_v3.0.2-stable_osx.fat.zip) and run it.
3. Click a button.

**Comment by LikeLakers2** [comment]
Without having a Mac myself to test this on, this sounds more like it might be a virus on your computer (Macs can get viruses too, don't believe what Apple tells you) than something Godot is doing. Have you tried running a virus scan?

**Comment by LTheGreats** [comment]
But this doesn't happen with any other program.

**Comment by Zireael07** [comment]
If it doesn't happen with other programs, it looks like a hardware problem, probably with GPU or memory.

**Comment by akien-mga** [comment]
> Radeon HD 6970M

That card doesn't support OpenGL 3.3 AFAIK, it seems to be limited to OpenGL 2.1: http://feedback.wildfiregames.com/report/opengl/device/Radeon%20HD%206970M

Godot should show an error dialog explaining that your drivers are not OpenGL 3.3-compliant and then might crash. If it doesn't show that dialog, it might be that your drivers claim OpenGL 3.3 support, but as they most likely don't support it properly, they crash.

That's either faulty hardware (as mentioned by @bruvzg) or faulty drivers, but sadly nothing that we can fix ourselves. You can wait for Godot 3.1 which will have an OpenGL 2.1 backend that should run with that GPU.

**Comment by bruvzg** [comment]
> Godot should show an error dialog explaining that your drivers are not OpenGL 3.3-compliant...

It won't show error dialog, macOS 10.7.5+ have full OpenGL 3.2 Core Profile with any GPU (using software emulation for missing features).

**Comment by akien-mga** [comment]
> It won't show error dialog, macOS 10.7.5+ have full OpenGL 3.2 Core Profile with any GPU (using software emulation for missing features).

Oh, what a terrible idea :(
This profile check is useless on macOS then, we'd have to check for the actual GPU and blacklist the known incompatible ones.
