### ISSUE TITLE
GridMap Documentation is Very Outdated

### ISSUE THREAD

**Issue by SilverSurfer1221** [godotengine/godot#17904]
The Godot documentation for the GridMap is very much out of date. You can read the doc here:

http://docs.godotengine.org/en/3.0/tutorials/3d/using_gridmaps.html

It uses the older Godot UI, which can make things a bit confusing. But more than that, it has incorrect information. For example, it states the following:

> Now, you can build your own level as you see best fit. Use left click to add tiles and right click to remove them. 

Right click no longer removes a tile. Also, other keyboard+mouse click combos are not referenced.

**Comment by cbscribe** [comment]
Documentation issues should be reported in the godot-docs repo: https://github.com/godotengine/godot-docs
