### ISSUE TITLE
MODO Navigation Scheme Does Not Work with GridMaps

### ISSUE THREAD

**Issue by ArgentArts** [godotengine/godot#17906]
Godot v3.0.2

Windows 10, Nvidia GeForce 1070

MODO Navigation Scheme does not work with GridMap tile placement.

If you go to Editor>Editor Settings>Navigation>Navigation Scheme and change the Scheme to MODO, then you can no longer navigate the viewport when placing GridMap tiles.

- Go through the steps to create a GridMap
- Go to Editor>Editor Settings>Navigation>Navigation Scheme and change the scheme to MODO
- Click on a GridMap item to start placing instances in the viewport
- Attempt to rotate or pan the viewport using MODO shortcuts (SHIFT+LMB, etc.)

**Comment by reduz** [comment]
Modo navigation scheme is at:
https://github.com/godotengine/godot/blob/master/editor/plugins/spatial_editor_plugin.cpp#L1012
check uses of the MODO keyword
Gridmap editor is here:
https://github.com/godotengine/godot/blob/master/modules/gridmap/grid_map_editor_plugin.cpp

**Comment by AntohaRDNS** [comment]
Same in Maya Navigation Scheme

**Comment by zqyoung1** [comment]
I'd like to work on this topic if it's still available
