### ISSUE TITLE
Update container size during test play issue

### ISSUE THREAD

**Issue by Daisdarg** [godotengine/godot#17915]
**Godot version:** 3.0

**OS/device including version:** Windows 7

**Issue description:**

Shorter:
When I generate a list of items as children to container (VBoxContainer), the size of this container is not what it expected to be.

Longer:
I create a random number of control type nodes as children to VBoxContainer via function (let's call it roll), but total size of container does not reflect this change. However, whenever I reroll list of items, rect size of the container changes to the size expected in previous roll. No matter how many rerolls you do, container size is always one step back.
Kinda twisty explanation -__- Here's the [pic](https://drive.google.com/open?id=1M2HFeDhi7CN6-S1k7brj17up6qSZm31Z).

**Comment by bojidar-bg** [comment]
Try calling `queue_sort` on the container.

**Comment by groud** [comment]
Might be fixed with #25298, could you confirm by building and trying with latest master ?

**Comment by groud** [comment]
I'll assume this is fixed, without a reproduction project I cannot check it myself.
Please comment if you can reproduce the bug and provide an example project.
