### ISSUE TITLE
No visual with _draw() on Control has (0,0) size and positioned at (0,0)

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#17917]
**Godot version:**

3.1.dev 4b4ed9b72

**OS/device including version:**

Ubuntu 17.10 / GeForce GTX 670

**Issue description:**

Somethings by on `_draw()` are not visible on Control which has (0,0) size and positioned at (0,0)
it draws at (1,1)

it's pretty simple code.

```gdscript
extends Control

func _ready():
	pass

func _draw():
	draw_rect(Rect2(0,0,100,100), Color(1,0,0,1), true)
	draw_texture(preload("res://icon.png"), Vector2(10,10))
```

here is demonstraition.
![draw](https://user-images.githubusercontent.com/8281454/38184734-aab3cf64-3684-11e8-8ca0-b167184c49fe.gif)

**Steps to reproduce:**
1. create `Control` node
2. make size (0,0) and locate at (0,0)
3. draw somthing in `_draw()`
4. run and see nothing
5. move the `Control` node to (1,1)
6. run and see it's drawn

**Minimal reproduction project:**

[Draw on Control.zip](https://github.com/godotengine/godot/files/1867244/Draw.on.Control.zip)

**Comment by volzhs** [comment]
my guess is... Control node is not drawing if it's out of screen.
not sure if it's bug or not.

**Comment by groud** [comment]
I'm not sure we can do anything about that. Control nodes, probably like sprites, are not drawn if outside of the screen (for performance reasons) . 
If the things you draw  are outside the boundaries specified by the position and size, I guess it is not accounted.

**Comment by girng** [comment]
> are not drawn if outside of the screen

0,0 is not outside of the screen, it's a position.

**Comment by groud** [comment]
Yeah, well à node at 0,0 with a side of 0,0 is considered as outside the screen.

**Comment by nattanielgrape** [comment]
> I'm not sure we can do anything about that. Control nodes, probably like sprites, are not drawn if outside of the screen (for performance reasons) .

@groud Is it possible to override this restriction from the script? Like, create a drawing safe margin to allow nodes outside but close to the screen to be drawn?

**Comment by groud** [comment]
> @groud Is it possible to override this restriction from the script? Like, create a drawing safe margin to allow nodes outside but close to the screen to be drawn?

I'm not sure it's possible. I believe that in most cases it can be worked around by using another Node2d with a different size.
But it might be worth adding the option. @reduz , WDYT about this issue ?

**Comment by eon-s** [comment]
I would expect to not draw at all if size is zero anyway.

**Comment by vnen** [comment]
Can't you simply change the size of the Control to how much you need it?

**Comment by bojidar-bg** [comment]
Is this still valid in master?

**Comment by KoBeWi** [comment]
Still happens in 3.1 stable.

Although the only reason why you would want a control to have 0 size is to prevent it from saving the size in .tscn file. I guess the fix would be something like changing `>` to `>=`, which shouldn't hurt much. But additional line in scene file doesn't hurt much either.

**Comment by bojidar-bg** [comment]
Tagging as rendering bug, since (AFAIK) Controls are culled in the same way as other CanvasItem-s.
