### ISSUE TITLE
Shadow artifacts with multiple directional lights

### ISSUE THREAD

**Issue by garyo** [godotengine/godot#17912]
In Godot latest, 098c7ba4f, on Windows 10 with GeForce GTX 970, I have significant shadow artifacts on a simple scene with multiple lights. 
My scene has just a sphere, a floor, and three directional lights (Warm, Cool, and Key). If you open the attached project in the editor, you'll see big stripes on the floor even though there's nothing to cast such shadows:
![image](https://user-images.githubusercontent.com/139975/38180818-325cf8e2-35fd-11e8-92bf-2f7cc8859731.png)
![image](https://user-images.githubusercontent.com/139975/38180916-e3938f36-35fd-11e8-9b7e-ff28698ba47e.png)

Also if you turn off CoolLight and turn on the other two, there will only be one shadow: the KeyLight shadow has disappeared.
![image](https://user-images.githubusercontent.com/139975/38180929-fbe7ded4-35fd-11e8-903f-dde836bae106.png)

You can see various other false shadows and disappearing shadows with different combinations of lights turned on/off and moving around the scene.

**Steps to reproduce:**

Download the attached project
Run in the editor
Orbit around the central sphere
Observe the stripy shadows on the floor that move as you move the camera
Turn on and off various lights:
 * whenever all 3 lights are on, the scene looks OK (you can see all three shadows)
 * whenever there's only 1 light on, it looks OK
 * with any combination of 2 lights, you get very visible artifacts

**Minimal reproduction project:** 
[shadow-test.zip](https://github.com/godotengine/godot/files/1866962/shadow-test.zip)

**Comment by DEF7** [comment]
It appears that Godot only shadows for a single directional light. In fact, it almost appears that just about all the rendering assumes only a single directional light. I vote that at least up to 2 directional lights are supported, or at least two with shadows.

**Comment by Calinou** [comment]
This seems to have been fixed in the `master` branch (with the new Vulkan renderer), closing.

![image](https://user-images.githubusercontent.com/180032/83975948-1de29b00-a8f7-11ea-93fd-28fe7540fbac.png)
