### ISSUE TITLE
Set material import location

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#17919]
A proposal for Godot 3.1 or hopefully earlier.

When we import a 3d scene we have the option to store the material in file, but we do not have the option to specify the location this file will be saved. 
What I am asking is to be able to specify the location of the materials, and not overwrite them if one exists already.

For example, right now, if we have several 3d scene that shares a material we have to place all the files in the same directory to make them share the materials, but if we can specify the location were the  material is going to be stored, then we can store the scenes were ever we may like and have more organized layout of our objects.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/601, as feature proposals are now tracked on the Godot proposals repository.
