### ISSUE TITLE
Transform3D - looking_at() resets scale

### ISSUE THREAD

**Issue by Lefl1** [godotengine/godot#17924]
**Godot version:**
3.0.2

**OS/device including version:**
Manjaro Linux 4.15.13

**Issue description:**
When using looking_at on a transform of a scaled node, the transform will reset it's scale to `(1, 1, 1)`

**Steps to reproduce:**

1. Create a (visible) node
2. scale it up
3. use looking_at on it.

**Minimal reproduction project:**
[tform_github_issue.zip](https://github.com/godotengine/godot/files/1868282/tform_github_issue.zip)
Press space to transform the cube

**Comment by albertomjp10** [comment]
working on it

**Comment by KoBeWi** [comment]
Fixed by #26897, but wasn't referenced there correctly.
