### ISSUE TITLE
Inconsistent sort in File Manager 

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#17929]
**Godot version:**
098c7ba

**OS/device including version:**
Windows 7

**Issue description:**
When creating new files they are unsorted.  However when duplicating they are sorted.

**Steps to reproduce:**
1. Create a new project then add a Node as root of the default scene.
2. Save this scene as `a.tscn`
![image](https://user-images.githubusercontent.com/1151394/38207587-f2c75c10-36e0-11e8-88b2-459feec83567.png)
3. Duplicate this file as `b.tscn`
![image](https://user-images.githubusercontent.com/1151394/38208695-8629474a-36e4-11e8-9368-8cc7f27a77f1.png)

**Comment by akien-mga** [comment]
Fixed by #18054.
