### ISSUE TITLE
KinematicBody.IsOnFloor() does not work anymore with the latest update

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17938]
**Godot version:**
`master` / 59710880cd21d79ae1329f04eb35ea48e646acb3

**OS/device including version:**
_Manjaro KDE 17.1_

**Issue description:**
After updating Godot from dad47d8876de45132226985dbbd079e060f6facc to 59710880cd21d79ae1329f04eb35ea48e646acb3, I found that `KinematicBody.IsOnFloor` always return false, but `IsOnWall` returns true when it hits the ground.

I tried to change my code to use `IsOnWall` to see what happens, and it makes the body oscilliate while `IsOnWall` changing between `false` and `true` constantly. Raising `safe_margin` doesn't seem to mitigate the problem.

I searched for similar issues and found potentially related problems: #16268, #16250.

And the relevant code can be found here: 
 * https://github.com/mysticfall/AlleyCat/blob/master/Source/AlleyCat/Motion/KinematicLocomotion.cs#L36

(The method is invoked from `_PhysicsProcess`, and the order of `IsOnFloor` check and `MoveAndSlide` doesn't seem to matter in this case.)

**Comment by AndreaCatania** [comment]
Can you please tell me if you still have this problem with last master #c9abe88 ?

**Comment by mysticfall** [comment]
@AndreaCatania I tested it again today with 48f9e6a05 and it seems that the problem has gone.
You can close this issue now. Thanks! :)
