### ISSUE TITLE
Display positional column of the editor cursor

### ISSUE THREAD

**Issue by droxmusic** [godotengine/godot#17931]
**Godot version:**

3.0.2

**OS/device including version:**

Win64

**Issue description:**

It appears the editor in the lower right display of the line and column value, the column count reflects the character in the line one it is no matter that the character is. If it is a tab and the editor is configured to display tabs as multiple spaces, the count will count each tab as a single column even though they take up multiple in the editor. I understand character position in the line can have uses, but it would be nice to display the actual monospace position the cursor is in as well as the character position in the line.

Something like: `Col: positional (character)`

This would be done by just counting tabs as multiple characters when calculating the column value.

**Steps to reproduce:**
This is core editor behavior. Enable the max column line and look at the Col count as you move to lines with tabs to make it more apparent.

**Comment by sherjilozair** [comment]
I think I might be able to do this. @Noshyaar @bruvzg, any tips before I jump into this?

**Comment by Noshyaar** [comment]
IMO having it displayed as `Col: positional (character)` might be confusing to the users. For example, vim displays only positional value. Might need to be discussed first.

@sherjilozair you can start from here:
https://github.com/godotengine/godot/blob/master/editor/plugins/script_editor_plugin.cpp
https://github.com/godotengine/godot/blob/master/editor/plugins/script_text_editor.cpp

**Comment by akien-mga** [comment]
Fixed by #18595.
