### ISSUE TITLE
Animation stopped If in AnimationTreePlayer set  TimeScale to -1.

### ISSUE THREAD

**Issue by wmigor** [godotengine/godot#17934]
**Godot version:**
3.0

**OS/device including version:**
Linux Mint

**Issue description:**
Animation stopped If in AnimationTreePlayer set  TimeScale to -1.

I fixed it by replacing "an->time = MAX(0, an->time + p_time);" by "an->time = an->time + p_time;" in animation_tree_editor.cpp at line 503

**Comment by Rubonnek** [comment]
Feel free to submit a pull request!

**Comment by reduz** [comment]
AnimationTreePlayer is deprecated, use AnimationTree instead
