### ISSUE TITLE
[3.0.2] Editor crash after reopen project with C# delegates

### ISSUE THREAD

**Issue by winipcfg** [godotengine/godot#17946]
**Godot version:**
Godot_v3.0.2-stable_mono_win64

**OS/device including version:**
Windows 10 Home

**Issue description:**
Editor crash after reopen project with C# delegates with parameters. 
No issue if there is no parameters in the delegate.

**Steps to reproduce:**
1. Add following code in C# script. 
```
[Signal]
public delegate void Test(int a);
```
2. Run the project
3. Close Godot 
4. Reopen Godot and open the scene

**Minimal reproduction project:**
[SignalTest.zip](https://github.com/godotengine/godot/files/1871832/SignalTest.zip)

**Comment by nazgulsenpai** [comment]
Possible duplicate of #17553, #17552 and (maybe related) #17615

**Comment by exts** [comment]
Damn, they removed cherry pick from signal arguments PR https://github.com/godotengine/godot/pull/16884 maybe we can get @hpvb to get this in for 3.0.3

**Comment by akien-mga** [comment]
> Damn, they removed cherry pick from signal arguments PR #16884 maybe we can get @hpvb to get this in for 3.0.3

Usually removing the `cherrypick` label without justifying that it's not needed means that it was actually cherry-picked. But I've checked and indeed it was missed in #16884 (@hpvb case in point for your proposal to add a `cherrypicked` or `cherrypicked-3.0` label ;)).

**Comment by neikeq** [comment]
Looks like a duplicate of #17553, which was fixed in 3.0.3
