### ISSUE TITLE
Reply to issue #17948

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#17949]
For some reason, I'm not able to post a comment on #17948 (the reason is apparently @Noshyaar has [blocked me](https://help.github.com/articles/blocking-a-user-from-your-personal-account/) me for whatever reason --I don't even know who the heck that is and don't even remember talking to him once, anyway, interesting choice from actual project owners BTW, giving such people thus many rights: he can and does label non-bugs as bugs right off the bat, and can effectively block actually correct and useful comments) so I'm writing a reply here as a new issue.

I don't see any bugs there; only a bad choice for doing rotations which amplifies precision errors.

```gdscript
	rotation = Vector3(-PI/2,PI/4,0)
	
	print(rotation)
	rotate_y(0)
	print(rotation)
	rotation.z = 0
	print(rotation)
```
gives
```
(-1.570796, 0.785398, 0)
(-1.570451, -2.356194, 3.141593)
(-1.570451, -2.356194, 0)
```
This is correct up to floating point precision errors. There's no sign flip of any angle (which means a -> -a). Sure, y Euler angle has a different sign,  but that's the same angle mod 2\pi (not  not a -0.785398).

Simply don't fiddle with the *components* of Euler angles. Use Euler angles only if you're *(re)orienting* the body, like rotation = Vector3(a,b,c) with all 3 components present (which is the only practical use case of Euler angles, and that is only if you prefer to imagine orienting the body in terms of 3 consecutive rotations around certain fixed axes). For doing rotations (which is something  you'd want to do every frame), use axis-angle parameterization (either through rotate() with a *normalized* axis or an intermediate quaternion). Unlike Euler angles, it treats the rotation axis and rotation angle separately such that you don't mix the errors, and you can suppress axis errors by ensuring that the rotation axis is normalized before each call.

**Comment by tagcup** [comment]
FYI, rotate_y(0) doesn't really change Basis *matrix* itself (only an epsilon perturbation due to fp errors). It's when you try to obtain the Euler angles that would parametrize the matrix you see those "dramatic" changes:

```gdscript
	rotation = Vector3(-PI/2,PI/4,0)
	
	print(rotation)
	print(transform.basis)
	rotate_y(0)
	print(rotation)
	print(transform.basis)
```


```
(-1.570796, 0.785398, 0)
((0.707107, -0.707107, -0), (0, -0, 1), (-0.707107, -0.707107, -0))
(-1.570451, -2.356194, 3.141593)
((0.707107, -0.707107, -0), (0, -0, 1), (-0.707107, -0.707107, -0))
```

**Comment by reduz** [comment]
Working with transforms directly is clearly difficult for a lot of people. We should really document this better.

**Comment by groud** [comment]
I think we can close this issue as we agree that is an expected behaviour.

**Comment by akien-mga** [comment]
@tagcup I've copied your comments to #17948, and I'll close this issue so that we focus on #17948 (relabeled as a documentation issue).

If you still can't add new comments to #17948, feel free to add them here and I'll copy them over..
