### ISSUE TITLE
WorldEnvironment complains about missing camera when one is present in the scene

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17943]
**Godot version:**
`master` / 59710880cd21d79ae1329f04eb35ea48e646acb3

**OS/device including version:**
_Manjaro KDE 17.1_

**Issue description:**
As shown in the attached screenshot, a warning icon is displayed beside a `WorldEnvironment` node, complaining about missing camera node, but there is a camera node presents in the same scene named _'Player Camera'_:
![screenshot_20180403_220206](https://user-images.githubusercontent.com/2367032/38251125-8f8cbe6e-378b-11e8-88f2-339fdf5cd247.png)

The problem occurred when I updated Godot to 59710880cd21d79ae1329f04eb35ea48e646acb3 from dad47d8876de45132226985dbbd079e060f6facc, and it doesn't seem to cause any real trouble other than displaying the warning message.

**Comment by Calinou** [comment]
I can reproduce this issue in [Godot Sponza](https://github.com/Calinou/godot-sponza) on the same commit mentioned by OP.

**Comment by akien-mga** [comment]
For the reference, the issue was caused by @poke1024's #17555 (but #18376 shows that it might be simply exposing an underlying issue).

**Comment by reduz** [comment]
I fixed this, just removed the check as it was unnecesary
