### ISSUE TITLE
Sometimes the editor crashes few seconds after opening a c# project

### ISSUE THREAD

**Issue by Censacrof** [godotengine/godot#17941]
**Godot version:**
Godot_v3.0.2-stable_mono_win64

**OS/device including version:**
Windows 10 Pro 64-bit

**Issue description:**
Sometimes when i open my c# project the editor crashes after few seconds.

**Steps to reproduce:**
I don't really know how to reproduce, it seems that it has something to do with the folder *res://.mono/temp*, in fact **i've been able to reopen the project by deleting it**. I don't know if it's relevant but i use *Visual Studio Community 2017* to code.

**Minimal reproduction project:**
Here's the project with the folder *res://.mono/temp* not deleted yet.
[Voxel.zip](https://github.com/godotengine/godot/files/1871014/Voxel.zip)

**Backtrace**
```
OpenGL ES 3.0 Renderer: Radeon RX 580 Series
Mono: Initializing module...
Mono: Runtime initialized
Mono: INITIALIZED
OPENING: C:/Users/galis/Desktop/Godot_v3.0.2-stable_mono_win64/Voxel (C:::Users::galis::Desktop::Godot_v3.0.2-stable_mono_win64::Voxel)
running cmdline: "C:\Users\galis\Desktop\Godot_v3.0.2-stable_mono_win64\Godot_v3.0.2-stable_mono_win64.exe" "--path" "C:/Users/galis/Desktop/Godot_v3.0.2-stable_mono_win64/Voxel" "--editor"
Mono: Runtime cleanup...
OpenGL ES 3.0 Renderer: Radeon RX 580 Series
Mono: Initializing module...
Mono: Runtime initialized
Mono: INITIALIZED
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Comment by mysticfall** [comment]
What is the version of Mono you are using? It seems that Godot stable works with Mono 5.4.x but not higher, unless you build the engine itself.

And please check if you have MSBuild 15 installed also.

**Comment by Censacrof** [comment]
I use **Mono version 5.4.1**.
```
C:\Program Files\Mono>mono --version
Mono JIT compiler version 5.4.1 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

Also i have **MSBuild 15.0** installed.

**Comment by Censacrof** [comment]
It seems that the issue is gone in both 3.0.6 and 3.1.alpha1.**However ** i just imported the minimal reproduction project i provided before and everything went fine, hence **i don't know if the problem was fixed during the import process or it's just fixed in general**.

**Comment by neikeq** [comment]
The import process shouldn't change anything to fix it. We will assume this to be fixed. Let us know if it find it happening again in the future.

**Comment by Censacrof** [comment]
I will, thanks.
