### ISSUE TITLE
Expose mbedTLS to gdscript

### ISSUE THREAD

**Issue by NHodgesVFX** [godotengine/godot#17952]
It would be great if some of mbedTLS was exposed to gdscript. Specifically, Encryption, hashing, random(RNG) and the pkcs5 (pbkdf2) modules. This would give us a few way to encrypt things properly for saves, when doing networking, etc... Since mbedTLS is already being included adding these functions wouldn't have a significant impact on the file size of Godot.  

#17721 there is a PR adding encryption that supports on the fly. Not sure if mbedTLS supports this or not. So the mbedTLS encryption would be used where stronger encryption is desired or if requiring asymmetric cryptography.

**Comment by Malkverbena** [comment]
I've worked in something this way but it's still very poor.

https://github.com/Malkverbena/cripter

**Comment by Calinou** [comment]
There are now cryptography classes, which were added in #29871 and #30239.
