### ISSUE TITLE
DirectionalLight Shadows are disapearing on the edges of a Camera with Orthogonal Projection.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#17961]
**Godot version:**

Godot 3.0.2 stable-official

**OS/device including version:**

Manjaro 64-bit xfce
OpenGL ES 3.0 Renderer: GeForce GT 540M/PCIe/SSE2

**Issue description:**

When an object comes close to the edges of a camera with orthogonal projection, stops casting shadows from a directional light.
It seems that this happens when the origin of the object gets out of the camera view when the camera size is setted to 10, but in higher zoom (e.g. 40) the problem is visible even with the whole object in the camera view.

**Minimal reproduction project:**

[DirectionalLight_Problem.zip](https://github.com/godotengine/godot/files/1875111/DirectionalLight_Problem.zip)

Use left and right keys to move the cube.

**Comment by oiblank** [comment]
Can confirm, in Orthogonal camera projection, once the object origin is out of view, it doesn't cast shadow. Win 10, Godot 3.0.4

**Comment by qarmin** [comment]
I can't reproduce issue in 3.2.
There is another issue with DirectionalLight, but this is another issue #21462
![Zrzut ekranu z 2020-01-29 19-07-27](https://user-images.githubusercontent.com/41945903/73384359-6cd64f00-42cb-11ea-907c-48573707df51.png)

**Comment by clayjohn** [comment]
Likely fixed by https://github.com/godotengine/godot/pull/35406
