### ISSUE TITLE
Kinematic body with sphere shape hangs on trimesh static body

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#17960]
Godot version: master branch

Kinematic body with sphere shape hangs in trimesh static body
This issue was found by @pgruenbacher and reported here: https://github.com/godotengine/godot/issues/16459#issuecomment-368271711

[godot-desert-physics_collision_error.zip](https://github.com/godotengine/godot/files/1874984/godot-desert-physics_collision_error.zip)

**Comment by AndreaCatania** [comment]
@pgruenbacher I'm working to fix it, however for now try to use a capsule with height 0

**Comment by erwincoumans** [comment]
Thanks a lot for the reproduction case. It should be fixed in this commit / pull request:
https://github.com/bulletphysics/bullet3/pull/1695/commits/62d58259bc7f5b5f44d592ced733cc6d09c2283c

**Comment by AndreaCatania** [comment]
@akien-mga Do you think that we can use directly the Master version of Bullet, or we should wait until a new version that include this fix is released?

**Comment by akien-mga** [comment]
You can go with the current master from https://github.com/bulletphysics/bullet3, as we're already on a newer-than-2.87 commit anyway.

It's once 2.88 / 3.0 would be released that I'd like us to try to stick to stable (unless really mandatory) to let distro packagers link against their shared bullet.
