### ISSUE TITLE
Godot 1.1 RC1 causes overheating of the system.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#1796]
Juan is an incredible pain there, I downloaded and unpacked everything, and started checking everything in order, each demo project, as they were in the list from top to bottom, I reached the (kinematic character 3d) and a bit of it to carry out excrement in the running game, I noticed new light and shadow, and there does not exist a fog as before, but then at some terrible moment, my computer just shut down, it was due to overheating! : '(
I know of only one of all the programs that have ever done such a terrible thing as the one that just happened, it was (Torque 3D) there, it happened even open it, completely empty stage.
After that, I had to refuse to work with this, because no one game or a program that did not do this ever.
 I do not know what triggered such overheating, but I blame the system dynamic light \ shade, I also noticed a lot of light shade, (track town), it looked like a nightmare, and work strange.
Yesterday, I reported about this problem here ... https://www.facebook.com/groups/godotengine/permalink/612012818935316/
I postponed my trip for an indefinite amount of time, now I'm going to give this issue more time ...
PS thanks in advance, I really counting on you.

**Comment by reduz** [comment]
nothing really changed in any of those demos since 1.0, and if a process is
causing system overheat, I suggest you clean your system :P

You can run Godot processes with -fdelay 10 parameter if you wish it to use
less cpu, but any modern CPU should not have any issue with this.

**Comment by Calinou** [comment]
If your computer overheats at high load, there definitely is a cooling problem. No properly made system overheats, even under the worst possible load.

**Comment by OlexiyKravchuk** [comment]
the problem in the new version, I play with the same demo version 1.0 is very much there never any overheating did not occur, and I re-checked all today, 10 rium stable, there is no problem, but the new version 1.1 RC is very heated, which I do?

**Comment by TheoXD** [comment]
@OlexiyKravchuk, for further game development you really need a better gear (if you want to increase your productivity). I had some overheating issues with my old Surface Pro 1, and it occasionally overheated and caused shutdowns while using godot Beta-1.0.
When debugging games, set FPS limit to 30-60, you don't really need to render at 200 frames per second to develop games. (due to your old hardware). I think game developers need at least twice as powerful workstation as a regular consumer one.

**Comment by freemanfromgodotengine** [comment]
@OlexiyKravchuk, if you did clean it for the last 8 years there is a nice warming dust blanket there that basically kills the cpu.
I have never seen a laptop that could not be cleaned. If you do not know how to do that, just give it to a friend who is computer-tech savvy or take it to a proper computer service. They will clean it up and put some new heat paste on a cpu so it will work like a new unit even few years longer. 
You should consider however, that costs of the service may actually be comparable to buying a used but newer laptop on some Internet auction. Your 8 year old laptop is probably on the edge of usefulness for today's game's programming purposes anyway, I would say.

**Comment by Razzlegames** [comment]
Your system overheating is not a Godot bug, it's not like it controls your CPU fan etc.  This would be a low level firmware or BIOS related function.  

I think this dialog belongs somewhere else and the ticket should be closed.

**Comment by OlexiyKravchuk** [comment]
Important people, I'm trying to emphasize again ... version 1.0 stable stays cold ... version 1.1 RC overheating.

**Comment by Razzlegames** [comment]
It's likely due to more performance requirements (larger load).  Optimizations can help, but please understand that your overheating is a hardware issue you'll need to solve, regardless (e.g. when any other high performance application runs, it will cause an issue for you).

**Comment by TheoXD** [comment]
Did you make a fair comparison? Like shutting down your computer for 15 minutes, starting 1.0, testing demos for a set amount of time, measure temperature, shut it down and let it cool down until you repeat the same steps with 1.1?

**Comment by Razzlegames** [comment]
While I agree that a fair test is great for analyzing what is actually happening, I think it is perusing the wrong issue to entertain this as a possible Godot problem.  That is unless Godot were creating Kernel modules or something that could really affect fan control etc.

You have a overheating issue, check your thermal paste fan etc... this dialog really belongs elsewhere. :)

**Comment by OlexiyKravchuk** [comment]
well, I spent more rigorous tests, to be fair, but I want to mention the fact that I work a lot with Godot, for quite a long time every day, about 3-6 hours, and never overheating occurred in 1.0 stable.
  But when there is a new version, I hurried to check everything in it, and just in time until I passed from the beginning of the list to the kinematic demo, I get this result.
But I will try to make an objective test to give exact figures.

**Comment by sgtGarcia** [comment]
@OlexiyKravchuk Just for sake of it download OCCT http://www.ocbase.com/index.php/download & test CPU & GPU ( for at least 30 min ) if it fails, you have to clean your laptop from dust.

@reduz @TheoXD @Razzlegames  But on other hand it might tell that now engine is using more resources then in version 1.0

**Comment by silverkorn** [comment]
`nothing really changed in any of those demos since 1.0`

But the backend has changed a lot since then, no?
IMHO, This is the reason why the same demo is requesting even more resources.

@Razzlegames @TheoXD, with all your respect, please don't over blame the guy having an old laptop. This is probably a good proof that the backend is greedier in 1.1b/rc1 then it was back in 1.0.
There's might be a need of benchmark over this.

I also think this might be something to look carefully at because this might eat a lot of battery.

This said, I believe the best question is: Is there a way to decrease or disable some features such as light / shadow and fog...

**Comment by Razzlegames** [comment]
Well I'm sure it is using more resources, and that's a valid ticket. So ticket could be changed to a feature request to optimize or something (but that is pretty general).  But if the requirements are to avoid overheating some esoteric configurations, "you're going to have a hard time".

**Comment by silverkorn** [comment]
@Razzlegames, indeed, I also suggest a renaming to this issue.

**Comment by KelinciFX** [comment]
I have a 2012 11 inch laptop with AMD-APU E-450. I think it's a little old. Using Godot 1.1RC1, no overheated. But, I do notice that It used 25% (2D mode idle) - 45% (3D mode idle) of CPU usage. I think this state can make give more celcius for very old computer, especially the one that has single core only. But, I do not think godot gonna crack that computer.

**Comment by OlexiyKravchuk** [comment]
Excuse me for a long time I made my way to the stack to get to the record for an answer.

I spent a lot of tests, including a new version 1.1 RC 2, it was probably the most difficult and complicated issue for the past month, I still did not understand until the end of all its aspects.
But here's what I found ...

1) To reproduce the problem, I ran all the demo turns in the list as well as the day and watched the performance of the thermometer (for the capture parameters, I used this utility ... http://openhardwaremonitor.org/downloads/ and later this ... http://www.cpuid.com/downloads/hwmonitor/hwmonitor_1.27.zip)

2) I found out that my computer really gets very hot (I began to sleep badly, when I learned that even in the non-loaded condition, the temperature of my computer, almost at the threshold of the chapel standards ~ 68 degrees, then when should be around 45 degrees and time work should be around ~ 50 degrees, depending on the load, but should not be more than 70 degrees), but in the normal course of work each day, my computer for the 70 crosses, chapel. and in time of active work temperature is kept at ~ 75-79 degrees with the simple editor, but can be heated up to about as much as 90+ when I start to play the scene to check (no matter that stage, it may even be empty ). But then I just turn it off myself by what I'm afraid of overheating, due to the fact that when playing a scene, the temperature gradually begins to grow without restrictions, I'm desperate = (

Possible cleaning would have helped, but I do not know how to properly disassemble the laptop if it was a simple desktop PC, I would easily handle, but not a laptop, and I do not whom to entrust this matter, and the service is too expensive, and I do not have the resources and income, not to mention the purchase of new equipment, for me, is beyond available at the moment ...

**Comment by silverkorn** [comment]
>[...] I noticed __new light__ and __shadow__, and there does not exist a __fog__ as before, but then at some terrible moment, my computer just shut down, it was due to overheating!

@OlexiyKravchuk, do you know if you can decrease/disable those features from the scene and try it back?

If it doesn't happen anymore, you might want to create some options in your game for older hardware by reducing these eye candies to something less intensive but less beautiful. 
This is unfortunately what desktop / consoles / mobiles game developers are always struggling for. :worried: 

@reduz, are those new features adjustable?

**Comment by SuperUserNameMan** [comment]
@OlexiyKravchuk  :
the good news is that you could use your laptop in your kitchen for cooking and during the winter for heating ! (joke)

I understand that you could feel anxiety about disassembling the laptop, but i you do it carefully, i'm pretty sure you will be able to reassemble it without problem. 
I did it several times on different laptops, and even if I ended with some extra screws, the laptops had no problems once reassembled.
Take notes and draw schematics to remember where screws come from, and in what order you have proceeded.

If you absolutely don't want to disassemble it, you could try to blow air into the holes to try to extract dust.

**Comment by SuperUserNameMan** [comment]
also, sometimes, you just have to open the keyboard of the laptop to access the fan.

**Comment by OlexiyKravchuk** [comment]
I do not have experience in disassembling laptops, but I might make an attempt to get it, I can see that my life is necessary to get it back to normal!

When I reach enlightenment and made the feat, I will again report on how to clean affected, what is not whether, but I do not know yet when and how I manage to do it ...

**Comment by DriNeo** [comment]
Hello I noticed that shadows, in the 3D demos, takes a lot of FPS (with old GPU ?). In the Truck town demo when I disabled shadows in "directional light" node, I recovered many fps. 
I don't know if shadows are common GPU eaters in 3D real time and game engines, or if it's an issue. I suggest people to try this.

**Comment by GungnirInd** [comment]
@DriNeo  Yeah, shadows are pretty taxing in realtime 3D.  I'm not sure that Godot's are optimized as much as they could be, but shadows are going to be a fairly major performance hit no matter what engine you use.

**Comment by akien-mga** [comment]
Overheating is indeed not a Godot bug, but a hardware or low level software issue.

The relevant point in this issue is that Godot 1.1 might be more resource-heavy than 1.0, but AFAICS there has not been any real objective comparison made between the two (what is named is "hours of normal usage in 1.0", so one can assume e.g. 2D game without lights, and "running all demos in 1.1" and some 3D demos are indeed resource-heavy).

So I'll close this one; if there is a real performance loss since 1.1, it might be worth investigating, but I believe the focus on overheating of an old laptop is not the way to go to address it.
