### ISSUE TITLE
Godot Mono Crashing When Creating New C# Script

### ISSUE THREAD

**Issue by CyanCoding** [godotengine/godot#17966]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
Godot crashed during the creation of a C# script.

**Steps to reproduce:**
![godot crash](https://user-images.githubusercontent.com/30013496/38305099-9256eebe-37d9-11e8-8267-f4158343bf87.gif)

**Comment by CyanCoding** [comment]
This fixed the problem! Thanks!

**Comment by akien-mga** [comment]
Thanks, closing then as it's a known issue (already tracked in other tickets).
