### ISSUE TITLE
Cannot export a project using godot server version (works fine with GUI version)

### ISSUE THREAD

**Issue by lstep** [godotengine/godot#17977]
**Godot version:** 3.0.2 server official for Linux 64 bits

**OS/device including version:** Ubuntu 16.04.4 LTS

**Issue description:**

Cannot export a project using godot server. Works fine with regular version (GUI)

**Steps to reproduce:**
```
$ ../../godot-server -v --export "Linux/X11"  foobar
ERROR: initialize: AudioDriverManager: all drivers failed, falling back to dummy driver
   At: servers/audio_server.cpp:153.
CORE API HASH: 6715380971059580270
EDITOR API HASH: -5919760101651613804
load resource: res://default_env.tres
load resource: /home/lstep/.config/godot/editor_settings-3.tres
EditorSettings: Load OK!
load resource: res://default_env.tres
ERROR: copy: Condition ' err ' is true. returned: err
   At: core/os/dir_access.cpp:305.
FPS: 1
EditorSettings Save OK!
```
Nothing is created, no foobar file anywhere. Note the **ERROR: copy: Condition ' err ' is true. returned: err**

**Minimal reproduction project:**

[vide.zip](https://github.com/godotengine/godot/files/1877253/vide.zip)

**Comment by Keetz** [comment]
I don't think this is related to the server version, but to CLI exporting being broken.
See #16949

**Comment by lstep** [comment]
You are right. I'm closing it.
