### ISSUE TITLE
Lights (Spatial) set to editor_only still appear in release

### ISSUE THREAD

**Issue by varkatope** [godotengine/godot#17989]
**Godot version:**
3.0.2.stable.official

**OS/device including version:**
Win10 64bit, Intel, GTX 970

**Issue description:**
3D/Spatial lights (tried spotlight and omni) set to editor_only through editor check box still appear in release game.

**Comment by akien-mga** [comment]
The problem is that the `editor_only` logic no longer does anything in `Light`: https://github.com/godotengine/godot/blob/68f224a50483c39c6d13141c0ceb26549ad2579f/scene/3d/light.cpp#L161-L184

@JFonS Maybe you'd like to have a go at this one?

**Comment by JFonS** [comment]
Sure, I will eventually get to it.
