### ISSUE TITLE
Shortcuts for macos users

### ISSUE THREAD

**Issue by sherjilozair** [godotengine/godot#17981]
**Godot version:**
3.0.2

**Issue description:**
I'd like shortcuts for macos to go to start of line or end of line using control-a, control-e. This is a common shortcut used by macos users.

**Comment by bruvzg** [comment]
@sherjilozair search for `KEY_END` / `KEY_HOME` in [scene/gui/line_edit.cpp](https://github.com/godotengine/godot/blob/master/scene/gui/line_edit.cpp) (single line text control) and
[scene/gui/text_edit.cpp](https://github.com/godotengine/godot/blob/master/scene/gui/text_edit.cpp) (multiline / code editor), there are already some macOS specific keyboard shortcuts inside `#ifdef APPLE_STYLE_KEYS` blocks.

**Comment by sherjilozair** [comment]
Thanks. I just checked the code. I basically want to trigger the `KEY_HOME` case when `control-a` is pressed, and `KEY_END` when `control-e`.

Perhaps I can add something like this before the KEY_HOME case?

```
#ifdef APPLE_STYLE_KEYS
case KEY_A:
if (!k->get_control()) break;
```

This will make `control-a` fall through to the KEY_HOME case in a macos build. Similar for `control-e`.

Should I send a PR for this? Do we have tests for such keyboard mappings?

**Comment by sherjilozair** [comment]
Sent a PR for this: https://github.com/godotengine/godot/pull/18003

**Comment by Mochnant** [comment]
Since #18003 has been merged, this issue can likely be closed, as well.

**Comment by sherjilozair** [comment]
While #18003 was merged, it was also fixed later, and I'm not sure if this functionality exists yet. I don't use Godot right now, so I don't know.

**Comment by Mochnant** [comment]
I can confirm that ctrl-A and ctrl-E do indeed work as requested on MacOS 10.14.5 using Godot 3.1.1.

**Comment by sherjilozair** [comment]
Cool! Thanks! I'll close this issue.
