### ISSUE TITLE
Syntax highlighting showing large portions of code in a single color

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17983]
**Godot version:**
a1f835d

**Issue description:**
I think this may have been caused by the recent separation of the syntax highlighting into its own class.
![screenshot1](https://user-images.githubusercontent.com/30739239/38341420-c925e902-384e-11e8-8c4f-100ed58b79e7.png)
I did some testing, and seems to happen when using the # and ' characters.

**Comment by hetdegon** [comment]
I found exactly the same issue, seems it's being overzealous about finding ' and " characters and parsing those in comments.
![out5](https://user-images.githubusercontent.com/323651/38356850-34aebb6e-38c1-11e8-96ea-58c904cf7f98.png)
I am getting past it by adding an extra closing ' at the end of a comment. Better than nothing!

**Comment by bojidar-bg** [comment]
Related to #17923, CC @Paulb23 (I know it was mentioned on the PR as well, but....)
