### ISSUE TITLE
[Mono] GetFilename returns a zero-length string

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#17997]
**Godot version:** 3.0.2 and Build from `master` on 5971088

**OS/device including version:**
* 3.0.2: Windows 10, Mono 5.4
* 5971088: Windows 7, Mono 5.4

**Issue description:**
Discovered this when writing documentation.  
The method `GetFilename()` always returns a zero-length string when called on a C# Node.

**Comment by paulloz** [comment]
My bad, I wasn't focused enough when I read the doc page.  
This issue can be closed, sorry. However it may be interesting to have a mention of `get_filename` in the documentation. Here is what we have for now: https://godot.readthedocs.io/en/3.0/search.html?q=get_filename&check_keywords=yes&area=default

**Comment by bojidar-bg** [comment]
It is a member variable, maybe we should list the getters/setters as well: http://godot.readthedocs.io/en/3.0/classes/class_node.html#member-variables

**Comment by Calinou** [comment]
Closing this issue as requested by OP.
