### ISSUE TITLE
Graphic artifacts with BakedLightmap and SS reflections

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#17995]
**Godot version:**
a1f835df771464e9db6909fd104751ccbbc1b91a as well as 3.0.2

**OS/device including version:**
Ubuntu 17.04, GTX1060

**Issue description:**
It seems there are black graphic artifacts when SS reflections are turned on in Environment mode with BakedLightmap node used at the same time:
![ssreflections_bakedlightmap](https://user-images.githubusercontent.com/6129594/38361365-6704804c-38cd-11e8-8d23-5fe1322ee91f.png)

**Steps to reproduce:**
1. Open Materials demo
2. Hide GIProbe node
3. Enable SS reflections in Environment node
4. Add BakedLightmap node, adjust it to contain all the geometry
5. Bake BakedLightmap node
6. Run the scene and click `next` button couple of times, you will be able to notice black flickering.

Alternatively: 
1. Download reproduction project and run it

**Minimal reproduction project:**
https://www.dropbox.com/s/mbilepg2851g9tp/BakedLightmap%20artifacts.7z?dl=0

**Comment by reduz** [comment]
I can't reproduce this, seems fine. I may have fixed it. 
Can you re-test?

**Comment by kubecz3k** [comment]
it's fixed now, thank you!
