### ISSUE TITLE
image.get_pixel doesn't seem to work on android (or html5)

### ISSUE THREAD

**Issue by usbhell** [godotengine/godot#17994]
**Godot version:**

2.15 rc1 (also 2.14)
**OS/device including version:**

Android MotoE3 (also not working on a Kindle Fire HD and some various Chinese Devices)
**Issue description:**

Specifically I was trying to use get_pixel on a sprite to calculate a more precise collision shape. This works fine on a PC/Mac but doesn't seem to work on any Android device I tried. I also tried exporting to HTML5 just out of interest and it didn't work for that either. I guess get_used_rect must make use of get_pixel as that also doesn't function on Android either.

**Steps to reproduce:**
see the attached project but basically using get_pixel or get_used_rect on Android/HTML5 will return an incorrect value. 

[get_pixel.zip](https://github.com/godotengine/godot/files/1879255/get_pixel.zip)

**Minimal reproduction project:**

**Comment by eon-s** [comment]
Related #2997

**Comment by usbhell** [comment]
Yep getting the image data directly (not via the texture) works fine. For example get_screen_capture() also gives the correct data. This probably isn't a big issue as there is a workaround.

**Comment by akien-mga** [comment]
Is this still reproducible in 3.1-alpha?

**Comment by usbhell** [comment]
It doesn't seem to be working on Android as **get_texture().get_data()** is returning null. I tried GLES2 & 3.
[debug2.zip](https://github.com/godotengine/godot/files/2392571/debug2.zip)

**Comment by akien-mga** [comment]
Should be fixed by #23125. Please comment if you can still reproduce it in 3.1.
