### ISSUE TITLE
Godot 3.0.2 C# crash on open script

### ISSUE THREAD

**Issue by Turkm** [godotengine/godot#17990]
**Godot version:**
3.0.2
**OS/device including version:**
Windows 10

**Issue description:**
as the title says but i recorded this video  which describe the issue:
https://www.youtube.com/watch?v=1Ye-gmOWN9I

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by mysticfall** [comment]
Could you specify the version of your Mono and MSBuild installation?

**Comment by Turkm** [comment]
mono-5.10.0.160-x64-0
Microsoft (R) Build Engine version 14.0.25420.1

**Comment by mysticfall** [comment]
If I'm not mistaken, 3.0.2 stable version supports only Mono 5.4.x unless you build the engine itself with a higher version of Mono. And it's recommended (I'm not too sure if it's required though) to use MSBuild 15.

So, I'd suggest try dowgrading Mono to 5.4.x and see if it resolves the problem.

**Comment by Turkm** [comment]
it works, thank you so much, it's my mistake i didnt' see (For the Mono version, Mono SDK 5.4.x (other versions won't work)) in the download page...

**Comment by mysticfall** [comment]
I'm glad I could help :)
