### ISSUE TITLE
Custom mouse cursor is limited to 32x32

### ISSUE THREAD

**Issue by sprite-1** [godotengine/godot#17992]
**Godot version:** 3.0.2

**OS/device including version:** Windows 10

**Issue description:** `set_custom_mouse_cursor` doesn't work. Either via GDScript or from the project settings. It still shows the system's cursor instead.

**Steps to reproduce:**
1. Try to set a custom mouse cursor

**Comment by ZX-WT** [comment]
It works on linux. Using project: https://github.com/guilhermefelipecgs/custom_hardware_cursor

**Comment by sprite-1** [comment]
An update to this, apparently it turns out that the image **needs** to be 32x32? How are we going to use larger size cursor now? How come it worked for any size of image back in 2.1.x? Why set an arbitrary image resolution limit?

**Comment by akien-mga** [comment]
CC @guilhermefelipecgs

**Comment by bruvzg** [comment]
AFAIK on Windows cursor is limited to specific size, but it is not always 32x32 and may be bigger on HiDPI systems. Cursor size should be determined by calling [GetSystemMetrics](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724385(v=vs.85).aspx) with `SM_CYCURSOR` and `SM_CXCURSOR`.

**Comment by guilhermefelipecgs** [comment]
I think we can remove this size restriction on all platforms. I'll work on this.
