### ISSUE TITLE
Tetris demo fails to run on OSX after export

### ISSUE THREAD

**Issue by triptych** [godotengine/godot#18]
After loading the 2d tetris demo, going immediately to export, then running the new app results in an unresponsive game:

![tetris](https://f.cloud.github.com/assets/8691/2131704/431c60d8-92a4-11e3-8da7-0b1222f0b778.png)

OSX 10.9.1 - MacBook Pro

**Comment by akien-mga** [comment]
After a year and a half, I'll assume that there is no bug anymore. Feel free to reopen if it still happens.
