### ISSUE TITLE
Area2D mouse entered signal does not work when the area2d is set as a child of a Canvas Layer node.

### ISSUE THREAD

**Issue by stubbsy345** [godotengine/godot#18005]
Godot 3.0

When an aread2d node is placed as the child of a canvas layer or further down the node tree, then the mouse entered signal does not appear to work.  

To reproduce simply set an area2d as a child of a canvas layer and try and get a signal from the area2d when the mouse enters the area.

**Comment by eon-s** [comment]
This seems to be fixed in 9e7cee2 (make layers to keep using default world)
The only issue that remains is that CollisionObject positions do not take layer transform into account.

**Comment by eon-s** [comment]
I have opened this for the offset issue #18073

**Comment by reduz** [comment]
@RandomShaper assigned to you as you were working on this

**Comment by RandomShaper** [comment]
When #21386 is merged into _master_ #21271 will be unmarked as _WIP_ and by merging that one, this will be fixed.

**Comment by akien-mga** [comment]
As mentioned above, this is fixed in the master branch already.
