### ISSUE TITLE
Window Transparency

### ISSUE THREAD

**Issue by nattanielgrape** [godotengine/godot#18009]
It would be interesting if there was a way to make the game window transparent, showing the user desktop behind it:

![window_transparency1](https://user-images.githubusercontent.com/35730957/38391081-9a9628bc-38f9-11e8-9e9e-3b516ce55aa2.png)

This would allow the creation of things like transparent splash screens, like Photoshop has:

![window_transparency2](https://user-images.githubusercontent.com/35730957/38390106-b31a35ca-38f6-11e8-9bb2-ddbd09a68048.png)

Applications like the Shimeji-ee desktop mascots:

[![window_transparency3](https://user-images.githubusercontent.com/35730957/38389929-34498ec6-38f6-11e8-99d6-3d95da048d06.png)](https://www.youtube.com/watch?v=AlwFynhoZBo)

And unusual borders and UI, like Winamp has:

![window_transparency4](https://user-images.githubusercontent.com/35730957/38390090-aa215426-38f6-11e8-94ce-e7b41ad96f98.png)

**Comment by vnen** [comment]
Note that there's a WIP here: #14622 (cc @bruvzg).

**Comment by nattanielgrape** [comment]
It's nice to know that there's already a PR addressing this!

**Comment by Noshyaar** [comment]
Related: #6511
