### ISSUE TITLE
Godot 2.1.4 Crash on iOS with libGPUSupportMercury.dylib: gpus_ReturnGuiltyForHardwareRestart + 12

### ISSUE THREAD

**Issue by megasoft78** [godotengine/godot#18016]
Hi,
I just attached the crash that happen on my game on iOS.
I'm not sure but it seems something about GPU.
[68wG2WY3FF7EwLa_-Q_Cv.xccrashpoint.zip](https://github.com/godotengine/godot/files/1883145/68wG2WY3FF7EwLa_-Q_Cv.xccrashpoint.zip)

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Comment by akien-mga** [comment]
Actually reopening, a crash still qualifies as "critical". It's hard to debug only based on automatic crash reports without precise steps to reproduce though, so I have little hope :/

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc1](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-1))?

**Comment by megasoft78** [comment]
This crash is from xCode on the store so I can't reproduce it. I never test it with new Godot version.
I'm sorry. :(

**Comment by KoBeWi** [comment]
Well, I guess this can be closed then.
