### ISSUE TITLE
Mesh Trimesh Static Body generation issues

### ISSUE THREAD

**Issue by GammaGames** [godotengine/godot#18014]
**Godot version:**
3.0.2.stable.official

**OS/device including version:**
Windows 10 Pro v10.0.16299
Nvidia 1060 GeForce drivers v391.35

**Issue description:**
When creating a trimesh static body for a scaled .obj model I **can't see the collision mesh** and the mesh also seems to be **using the wrong scale if the object has been re-imported multiple times** with different scales.

**Steps to reproduce:**
1. Drag model into scene
2. Select model in filesystem, change its scale in the import tab and reimport
2. Select model in filesystem, change its scale to something else and reimport
3. Use the Mesh menu to create a trimesh static body
4. Become confused when you don't see a collision model in the viewport and the collision isn't correct when interacting with the object

It might be finicky to find the cause, because sometimes the import works and it will generate the static body and sometimes it won't.

**Minimal reproduction project:**
[18014.zip](https://github.com/godotengine/godot/files/1882777/18014.zip)

Just a basic scene with a fps controller and kenney's nature pack

**Comment by GammaGames** [comment]
I mentioned that in the original issue, because I have the same issue. Maybe it's related to #13938 ?

For now I just enable visible collision shapes from the debug menu so that I can see them while playing.

**Comment by Zireael07** [comment]
Oh yeah, no visual indication in editor can be a bit throwing for trimesh collisions.

**Comment by fracteed** [comment]
Agreed, a wireframe would be great to have!

**Comment by akien-mga** [comment]
Fixed by #21908.
