### ISSUE TITLE
Godot 2.1.4 Crash on iOS with godot_opt.iphone: AudioDriverIphone::output_callback(void*, unsigned int*, AudioTimeStamp const*, unsigned int, unsigned int, AudioBufferList*) + 256

### ISSUE THREAD

**Issue by megasoft78** [godotengine/godot#18018]
Hi,
I just attached the crash that happen on my game on iOS.
It seems to be related with AudioDriver.
[CKU1CrzcV18EXTapNCu21K.xccrashpoint.zip](https://github.com/godotengine/godot/files/1883157/CKU1CrzcV18EXTapNCu21K.xccrashpoint.zip)

**Comment by akien-mga** [comment]
Please try to follow the issue template, the Godot version should be in the issue description, not title, and it would be good to have the stacktrace directly visible in the issue and not hidden in a zip file (which you are welcome to include nevertheless if it contains more details).

**Comment by megasoft78** [comment]
Hi,
yes, I'll try to follow the template next time. I'm sorry :(
I'm a bit new to iOS so I don't even know where to look for a stacktrace. :)

**Comment by akien-mga** [comment]
Well `godot_opt.iphone: AudioDriverIphone::output_callback(void*, unsigned int*, AudioTimeStamp const*, unsigned int, unsigned int, AudioBufferList*) + 256` is the first line of the stacktrace, so I guess there might be others following it in the zip.

**Comment by akien-mga** [comment]
Well I just checked the logs and it's that it's not easy to extract just the relevant bit of info from it, so I guess you're doing fine :)

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Comment by akien-mga** [comment]
Actually reopening, a crash still qualifies as "critical". It's hard to debug only based on automatic crash reports without precise steps to reproduce though, so I have little hope :/

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc1](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-1))?

**Comment by megasoft78** [comment]
This crash is from xCode on the store so I can't reproduce it. I never test it with new Godot version.
I'm sorry. :(

**Comment by Calinou** [comment]
Closing, as nobody has been able to reproduce this issue recently. Please comment if you can still reproduce it.
