### ISSUE TITLE
Modified GDScript code gets saved to disk without a prompt

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#18010]
**Godot version:**
`master` branch commit eaa5dfbdbd1217d62902f966496658770638c3d1

**Steps to reproduce:**
1. Save all the changes to a scene.
2. Open a GDScript with the built-in editor and write some text to it and do not save those changes.
3. Go to Scene->Quit to exit the editor, and click on Quit.
4. The GDScript that was being modified gets saved to disk

I've also noticed that when editing a GDScript that was just saved, it is not getting marked as modified in the editor as soon as you start typing.

**Minimal reproduction project:**
[saved_without_asking.zip](https://github.com/godotengine/godot/files/1881884/saved_without_asking.zip)

**Comment by eon-s** [comment]
I do not know the system of the reported issue but I can confirm this on Ubuntu in master and 3.0.2 too.

**Comment by AndreaCatania** [comment]
I got the same issue, and I'm able to trigger it by doing this:
- Modify a GDScript
- Instead to save the file Press F5 to start the game

Now even if the editor show saving process the file was not saved and it became impossible to save. The only way to make it saving again is Close then Open the editor.

**Comment by reduz** [comment]
Maybe script text editor is applying (saving to disk) changes on exit?

**Comment by DualMatrix** [comment]
Apparently this is just a feature of the editor and can be enabled/disabled with the interface/editor/save_each_scene_on_quit property. So this isn't a bug and can probably be closed?

**Comment by akien-mga** [comment]
Still reproducible in the current master branch.

**Comment by Hex4F** [comment]
This one's nasty! Combined with #40199 I think the only way to safely discard bad changes to a script is to forcibly kill the Godot process.

**Comment by Calinou** [comment]
This is likely due to the script editor remembering script state across sessions. Can someone try to reproduce this on the latest `master` branch?

cc @Paulb23

**Comment by eon-s** [comment]
I could reproduce it on master branch with the same steps.
