### ISSUE TITLE
Unable to remove a stream from an AudioStreamPlayer

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#18012]
**Godot version:**
eaa5dfb

**Issue description:**
Any attempt results in this error:
`scene/2d/audio_stream_player_2d.cpp:245 - Condition ' !p_stream.is_valid() ' is true.`

**Comment by chanon** [comment]
Probably related, or the same thing as #16846

**Comment by bojidar-bg** [comment]
Yes, duplicate of #16846, thanks for noticing.
