### ISSUE TITLE
Renaming resource used in currently open scene will revert your scene

### ISSUE THREAD

**Issue by NikodemL** [godotengine/godot#18019]
**Godot version:**
Mono v3.0.2

**OS/device including version:**
Windows 8.1 Enterprise

**Issue description:**
When you are editing a scene and have not saved the changes yet you go to the file system and rename a resource (script, texture, anything referenced in the scene). 
After rename the scene will revert to the scene on the disk and you will lose any changes made to the scene.
The expected behavior would be to warn the user about unsaved changes and if he wants to save before renaming the resource. 

Example of the bug:
https://youtu.be/AMlF6gbAUKI

**Steps to reproduce:**
1. Have a texture with a .png loaded from file system in a saved scene
2. Modify the scene (Add new node, do not save the scene)
3. In the file system panel rename the texture that you have in your scene
4. Observe that your modification from step 2 has disappeared.

Example video:
https://youtu.be/AMlF6gbAUKI

**Comment by reduz** [comment]
@groud Can you check this out? (reassign to me if you can't) There should obviously be a warning here (and I think I added it at some point, but does not seem to work), despite that I don't know what actually causes this behavior.

**Comment by KoBeWi** [comment]
Interestingly, this doesn't happen when the resource reference isn't saved yet, i.e. when you add a dependency, but don't save the scene. When you rename the resource, the reference gets correctly updated and nothing is reverted (although resource name in inspector isn't changed until you reselect node). When you save the scene, so the dependency is saved inside .tscn, it will get reverted on rename as described in OP.

**Comment by KoBeWi** [comment]
Fixed in 3.2
