### ISSUE TITLE
Editor::AnimationPlayer::Active dont work in the instanced mode

### ISSUE THREAD

**Issue by Ogimle** [godotengine/godot#1801]
If a scene has AnimationPlayer and instanced inside another scene, the main scene can not override the field "Active". The change in state checkbox "active" does not affect the running application.

**Comment by akien-mga** [comment]
I believe this issue would have been fixed by the recent changes that make instanced scenes customisable. Feel free to reopen/ask me to reopen if you can still reproduce the issue in a recent git build though!
