### ISSUE TITLE
TextEdit (Node, not IDE) breakpoints not working, no breakpoint gutter

### ISSUE THREAD

**Issue by gabrii** [godotengine/godot#18026]
**Godot version:** 3.0.2 stable

**OS/device including version:** Ubuntu 17.10

**Issue description:**
Acording to http://docs.godotengine.org/en/latest/classes/class_textedit.html?highlight=textedit#signals :
  - **breakpoint_toggled ( int row )**: Emitted when a breakpoint is placed via the breakpoint gutter.

But the textedit node doesn't even seem to have a breakpoint gutter (it's enabled on the IDE but not on the node, or I can't seem to find its toggle). 

**Steps to reproduce:**
 - Create new project, new scene, new TextEdit node with __layout > full rect__ so you can try to place a breakpoint.
 - Add the following script to the node: 
```javascript
extends TextEdit
func _ready():
	show_line_numbers = true
	text = "Lore\nipsum"
	connect("breakpoint_toggled", self, "it_works")
func it_works(row):
	# Never called
	print("It works! Row: %d" % row )
```
 - Run, and try to place a breakpoint.

**Minimal reproduction project:** [issuedemo.zip](https://github.com/godotengine/godot/files/1884485/issuedemo.zip)

**Comment by gabrii** [comment]
Oh, it's just a matter of exposing [`TextEdit.set_draw_breakpoint_gutter(bool p_draw);`](https://github.com/godotengine/godot/blob/ec110076caca7a75ffb4795c32362bc52151dbcc/scene/gui/text_edit.h#L608).

**Comment by mhilbrunner** [comment]
Fixed by https://github.com/godotengine/godot/pull/18028
