### ISSUE TITLE
[Compiler bug] clang 6.0.0/Xcode 9.3 clang hangs on compiling optimised `servers/physics/collision_solver_sat.cpp`

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#18023]
**Godot version:**
master ec110076c - e3590a252

**OS/device including version:**
* macOS 10.13.4 (17E199)
* Debian GNU/Linux 9 (stretch) (4.9.0-6-amd64)

**clang versions:**
* macOS, Apple LLVM version 9.1.0 (clang-902.0.39.1), Xcode 9.3 (9E145)
* macOS, clang version 6.0.0 (tags/RELEASE_600/final), installed from MacPorts.
* Debian, clang version 6.0.0-1~bpo9+1 (tags/RELEASE_600/final), installed from OS repo.

**Last knows good clang versions:**
* macOS, Apple LLVM version 9.0.0 (clang-900.0.39.2), Xcode 9.2 (9C40B)
* macOS, clang version 5.0.1 (tags/RELEASE_501/final), installed from MacPorts.
* Debian, clang version 5.0.1-2~bpo9+1 (tags/RELEASE_501/final), installed from OS repo.

Fixed in clang version 7.0.0 (trunk 329027), installed from MacPorts.
**NOT** fixed in Xcode 9.4 beta (9Q1004A)

**Steps to reproduce:**
Build optimised (release or release_debug) Godot on macOS using specified compiler versions.

If you have problems compiling Godot release versions on mac, downgrade Xcode command line tools to 9.2 or use clang-5.0/clang-devel from MacPorts (add `macports_clang=5.0`/`macports_clang=devel` to build command).

*Update (Apr 14):* Same problem affects Linux builds too, so it's clearly compiler bug.

*Update (Apr 22):* Some additional information: clang seems to have problem optimising multiple inlined instances of [`test_axis`](https://github.com/godotengine/godot/blob/master/servers/physics/collision_solver_sat.cpp#L318), in [`_collision_capsule_capsule`](https://github.com/godotengine/godot/blob/master/servers/physics/collision_solver_sat.cpp#L1076) function.

**Comment by volzhs** [comment]
I'm having the exact same issue with this.

**Comment by volzhs** [comment]
it'd be better to mention not to use clang 6.0 on docs. I spent couple of days for it :(

**Comment by bruvzg** [comment]
*Update*: Bisected LLVM/Clang to following commits:

:small_blue_diamond: Bug introduced in `PeepholeOptimizer: Do not form PHI with subreg arguments`
`master` branch: [llvm-project @ 1593fa8](https://github.com/llvm-project/llvm-project-20170507/commit/1593fa84c7874db801e015f5b346a9c7dbe7887a), [reviews.llvm.org @ rL322313](https://reviews.llvm.org/rL322313)
`release_60` branch: [llvm-project @ f5d8d87](https://github.com/llvm-project/llvm-project-20170507/commit/f5d8d8773cab382121140389a1e700029cfd4366), [reviews.llvm.org @ rL322684](https://reviews.llvm.org/rL322684)

:small_blue_diamond: Bug fixed in `PeepholeOpt cleanup/refactor; NFC`
`master` branch: [llvm-project @ 595304a](https://github.com/llvm-project/llvm-project-20170507/commit/595304ad70df4db24a803b5ea3edc2acd8f850d6), [reviews.llvm.org @ rL322325](https://reviews.llvm.org/rL322325)

**Comment by akien-mga** [comment]
Could you file a bug report upstream? If it's a compiler issue it would be good to let them know about it.
