### ISSUE TITLE
Possible angle calculation issue

### ISSUE THREAD

**Issue by ruckustboom** [godotengine/godot#18025]
_I'm no expert, so take this with a grain of salt._

**Godot version:**

master branch

**OS/device including version:**

N/A

**Issue description:**

There appears to be a flaw in the calculation for converting YPR angles to quaternions. In [Quat::set_euler_yxz](https://github.com/godotengine/godot/blob/master/core/math/quat.cpp#L92) it's specifying the z component as
```
-sin_a1 * sin_a2 * cos_a3 + cos_a1 * sin_a2 * sin_a3
```
but, unless I'm mistaken, it should be
```
-sin_a1 * sin_a2 * cos_a3 + cos_a1 * cos_a2 * sin_a3
```

**Steps to reproduce:**
... look at the code?

**Minimal reproduction project:**

Like I said, I'm no expert in this, and unfortunately I can't test it (I can't run Godot on this machine), so I may be way off the mark, but I figured this issue can just be closed if I am wrong.

**Comment by akien-mga** [comment]
CC @tagcup

**Comment by ruckustboom** [comment]
As a note, the PYR conversion looks correct.

**Comment by ruckustboom** [comment]
I did double check with the NASA doc, as well as a Java transform library I have locally. That's how I noticed the discrepancy.

![capture](https://user-images.githubusercontent.com/1735659/38429749-8e17a2b8-397c-11e8-8d27-8751e3aa590b.PNG)

**Comment by tagcup** [comment]
Thanks for noticing it, I for sure didn't (that was my mistake). So could you submit a PR for it?

**Comment by tagcup** [comment]
There's probably a copy of that in C# code too that needs fixing BTW

**Comment by ruckustboom** [comment]
I would have no way of building or testing the PR, so it would probably be better to have someone who can do it. I just noticed it as I was reading through the code on GitHub.

**Comment by ruckustboom** [comment]
I'll let you take care of it. One of these days, when I can get back into game development, I'll try to contribute more.
