### ISSUE TITLE
Huge exported build size on Android in comparison with Desktop version

### ISSUE THREAD

**Issue by antoniotorresm** [godotengine/godot#18021]
**Godot version:** 
3.0.2

**OS/device including version:**
 GNU/Linux X11

**Issue description:**
I'm the developer of [Solaria](https://gitlab.com/atorresm/solaria). When exporting, I noticed that the Android build is +100MB while Desktop versions are about 25MB. Is this huge difference normal?

Thank you in advance!

**Steps to reproduce:**
Build for Android with official export templates.

**Minimal reproduction project:**
https://gitlab.com/atorresm/solaria

**Comment by akien-mga** [comment]
That's just the size of your game, you have 94 MB of assets:
```
$ LC_ALL=C ls -l
total 223512
-rw-r--r-- 1 akien akien 106338580 Apr  6 11:56 solaria.apk
-rw-r--r-- 1 akien akien  94985732 Apr  6 11:54 solaria.pck
-rwxr-xr-x 1 akien akien  27539593 Apr  6 11:54 solaria.x86_64*
```
The Linux version above is not 27 MB, it's 27 MB (binary) + 95 MB (assets).
