### ISSUE TITLE
a lots of suffering coding on godot

### ISSUE THREAD

**Issue by loohoo** [godotengine/godot#18036]
I am unable to endure being coding ..., why no make a better editor plugin, such as intellij

**Comment by mysticfall** [comment]
Maybe we should change the title to a more descriptive one, like _"Provide IntelliJ plugin for GDScript"_?

I'm not sure if it'd be within the scope of Godot engine to do such things though.

**Comment by reduz** [comment]
Closing this issue because no information is given. If you expect anything to be fixed or improved, state your specific problem as clear as possible.
