### ISSUE TITLE
Custom Button Artifacts

### ISSUE THREAD

**Issue by popoysan** [godotengine/godot#18037]
**Godot version:**

Godot 3.0.2

**OS/device including version:**

Windows 10

**Issue description:**

![button_artifact](https://user-images.githubusercontent.com/37913110/38453214-a5e46e46-3a06-11e8-8a21-6e66e8669576.png)

**Steps to reproduce:**
1. Create a button.
2. On custom styles flat.
3. Change corner radius to 16-24px. 

**Minimal reproduction project:**

**Comment by Noshyaar** [comment]
Can't reproduce. The corner blends nicely for me. I suspect that it might be Control focus highlight rectangle that adds the outline.

A minimal project and/or more descriptive steps are appreciated.

**Comment by Vega-KH** [comment]
Corners blend fine for me, tested on Win10. Try it with anti-aliasing ON in the custom style.

**Comment by kn00tcn** [comment]
it's interesting that the bottom two corners of the 'artifact' are barely curved

**Comment by popoysan** [comment]
I want to get rid of the pesky blue outline. Im uploading a sample project to show what I mean. 
[BtnArtifact.zip](https://github.com/godotengine/godot/files/1887083/BtnArtifact.zip)

**Comment by Noshyaar** [comment]
As I suspected, it's focus highlight. Try setting StyleBoxEmpty on `focus` theme constant.
