### ISSUE TITLE
Basis operator Quat() is not exported to gdnative

### ISSUE THREAD

**Issue by garyo** [godotengine/godot#18031]
**Godot version:**
ec110076c

**Issue description:**
Tried to convert a Basis to a Quat in godot-python, discovered it can't be done.

**Steps to reproduce:**
gdscript has a Quat constructor from a Basis; Basis itself has an `operator Quat` that does the proper conversion. But that functionality is not exported to gdnative, so godot-python can't use it.

Discussion from IRC:
```
<darkstarsystems> I'm trying to get a quaternion from a basis in python. In gdscript you can do Quat(basis), and the godot code has basis::operator Quat() to do it. But I can't see where that's exposed in gdnative.
<karroffel> darkstarsystems: oh, seems like you found a hole in the API
<karroffel> In C++ most of the math types are custom implemented anyway, but you are correct that they are missing
<darkstarsystems> karroffel, I see -- I'll file an issue. File it against godot itself?
<karroffel> Yes exactly
<darkstarsystems> I'd be happy to look at fixing it if there's a good sample to follow
<karroffel> The fix itself is simple
<karroffel> the hard thing is to make it work in a non breaking way
<karroffel> Because GDNative uses "layers" of structs with function pointers to keep compatibility, now the API is fixed and to fix it you would have to add in a new GDNative core extension, which has never been done yet, only for NativeScript so far
```

**Comment by garyo** [comment]
Also just discovered with karroffel that there's no `Quat(euler)` constructor in gdnative.

**Comment by profan** [comment]
Also missing from GDNative is a Transform(Quat) constructor, which certainly exists in GDScript but isn't exported, so also not usable from any of the current bindings.

**Comment by tagcup** [comment]
I'll add get_quat and set_quat to Basis. They're supposed to be there, just incompleteness. There're rot-scale constructors which set both at once are also missing and need to be added

**Comment by karroffel** [comment]
#20757 This should be added as well

**Comment by karroffel** [comment]
Also the recent Dictionary change (#21012) should be considered
