### ISSUE TITLE
[suggestion] boolean or if condition to use in gdscript, to detect when code is being exported.

### ISSUE THREAD

**Issue by girng** [godotengine/godot#18065]
hello my friends!

so, i was thinking of a cool suggestion but not sure if it's already implemented.

but basically, i have a splash screen and i use
`export(bool) var play_splash_screen = false`

which is nice, i can toggle it when editing the scene
however, it gets rather annoying to always remember to set it to true before export (as when i'm editing my game i set it to false). my suggestion is if we could could somehow make **it always true, if the code is being exported**.   maybe using a special method similar to `is_editor_hint()` that is `on_game_export()`.

a splash screen is just one example, could be used for many other things

thanks for reading

**Comment by mrcdk** [comment]
Looks like `OS.is_debug_build()` is what you are looking for. http://docs.godotengine.org/en/latest/classes/class_os.html#class-os-is-debug-build

**Comment by girng** [comment]
@mrcdk yep, `!is_debug_build()` works. thank you sir
