### ISSUE TITLE
Animations marked to autoplay don't show the correct radio icon

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#18063]
**Godot version:**
 2f4f8de

**Issue description:**
I'm not completely sure if this only affects the Animation editor, or is related to radio buttons with icons in general:
![screenshot1](https://user-images.githubusercontent.com/30739239/38470135-0c7bc21a-3b35-11e8-8e85-eea8f27d42e2.png)

**Comment by akien-mga** [comment]
CC @RandomShaper

**Comment by sketchyfun** [comment]
I left a comment on the fix, but I also wanted to make a note here:

The PopupMenu theming also needs updating as the customisable icons are still for check boxes only, so there's no way to override the new radio buttons you've added

![image](https://user-images.githubusercontent.com/10464013/39219179-cb87bbe4-4820-11e8-832d-d53df76b2da6.png)
