### ISSUE TITLE
CollisionObject2D nodes inside CanvasLayer are not affected by layer offset or rotation

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#18073]
**Godot version: 3.1dev 34e3675**

**Issue description:**
`CollisionObject2D`s inside a `CanvasLayer` do not take the layer offset or rotation into account for their (state?) position.

It would be desirable if they respect the layer positioning, at least Area2D nodes (may be too complex for PhysicsBody).

**Steps to reproduce:**
Create any `CollisionObject` and add it to a layer, put an offset on the layer and watch the interaction with objects outside the layers or input like mouse.

**Minimal reproduction project:**
[CanvasLayerAndCollisionObjects.zip](https://github.com/godotengine/godot/files/1888009/CanvasLayerAndCollisionObjects.zip)

**Comment by akien-mga** [comment]
Reopening as #21245 was partially reverted, undo the fix for this issue.

**Comment by adamz5k** [comment]
It seems like this issue is back, this time with 3.2's follow viewport and scale feature.
I am experiencing this issue in 3.2 beta 6 Win64. When there is a CollisionObject2D in a CanvasLayer with follow viewport enabled, collisions do not occur where the object is, but stay stationary.

**Comment by akien-mga** [comment]
Please open a new issue following the issue template. This was fixed over one year ago.
