### ISSUE TITLE
Quick open scene doesn't work for scenes created in current editor run

### ISSUE THREAD

**Issue by ficoos** [godotengine/godot#1808]
How to reproduce:
* Open a project
* Create a scene on a non root directory
* Save it
* Quick open scene

The path will be incorrect (root instead of a sub-directory) in the quick open dialog and trying to open the scene will fail.

Workaround:
Restarting the editor will correctly display the scene in the quick scene open dialog.
Opening the scene directly works

**Comment by alketii** [comment]
Works fine here, probably resolved.

**Comment by akien-mga** [comment]
Thanks, closing then.
