### ISSUE TITLE
Call func track used with AnimationTree is resetting transform of a spatial

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#18084]
**Godot version:**
3.0.2

**OS/device including version:**
Ubuntu 17.04

**Issue description:**
When using `Call func Track` in an AnimationPlayer which is used by `AnimationTreePlayer`, something strange happens with the transform of the nodes which are linked with animation by `Call func Track`. 
In platformer 3D demo when this track is added in `walk-cycle` animation and linked with `player` node -> the player will spawn outside of the level. If in the same demo and animation it's linked to `Armature` node then model will never rotate and the scale will be reseted. 
https://youtu.be/b7oDpJ_ral4
_video with problem and reproduction_

**Steps to reproduce:**
1. Open platformer 3D demo
2. Open player scene
3. Add new `Call func track` to AnimationPlayer node in walk-cycle animation
4. Link it with `player` node
5. Run the project and observe that the hero is spawned outside of the level
6. Modify `Call func track` to be linked to Armature node
7. Run the project and observe that armature transform is reseted and the hero is not rotating when player is moving.

**Minimal reproduction project:**
[3DPlatformer_AnimationTreePlaer_TransformResetBug.zip](https://github.com/godotengine/godot/files/1889545/3DPlatformer_AnimationTreePlaer_TransformResetBug.zip)

**Comment by kubecz3k** [comment]
There is another reproduction project in https://github.com/godotengine/godot/issues/8053 (which was closed as a duplicate)

**Comment by rechutox** [comment]
It's still happening in 3.0.5. Even if you filter the `call func track` out in the `AnimationTree` editor, the function won't get called but the transform keep resetting.

**Comment by reduz** [comment]
Please move to AnimationTree, which supersedes AnimationTreePlayer. Code is new and should be working
