### ISSUE TITLE
Glow effect renders differently in editor vs. at runtime

### ISSUE THREAD

**Issue by zhaytee** [godotengine/godot#18099]
**Godot version:**
3.0.2

**OS/device including version:**
macOS 10.13.4
Radeon Pro 460 (4GB)

**Issue description:**
I set a sprite's modulate color to raw mode (1.2, 1.2, 1.2), added a WorldEnvironment to the scene, and enabled the "glow" effect with the default HDR threshold setting of 1. The effect looked nice in the editor, but at runtime it seemed completely absent. After some experimentation, I realized that the effect just looks totally different in the editor vs. at runtime.

**Steps to reproduce:**
1) Add nodes to scene: Node2D, child Sprite, and child WorldEnvironment.
2) Load a texture into the Sprite so that it shows up as expected.
3) Set the sprite's modulate color to something above 1, in raw mode.
4) Modify the WorldEnvironment's Environment resource: set background_mode to "Canvas", set glow_enabled to true.
5) Play with the glow_hdr_threshold setting until the desired effect is seen in the editor.
6) Run the scene, notice how the effect is different.

**Screenshots:**
<img width="1147" alt="glowbug_01_editor" src="https://user-images.githubusercontent.com/43938/38540028-548720d4-3c4f-11e8-94ec-1fc7bacc2156.png">
<img width="1282" alt="glowbug_01_runtime" src="https://user-images.githubusercontent.com/43938/38540034-59cf6a42-3c4f-11e8-86b7-30af478f519f.png">
<img width="1214" alt="glowbug_02_editor" src="https://user-images.githubusercontent.com/43938/38540039-5c3f0008-3c4f-11e8-9e8a-8771b88d9ee6.png">
<img width="1062" alt="glowbug_02_runtime" src="https://user-images.githubusercontent.com/43938/38540041-5de9a0e8-3c4f-11e8-94c1-0ea6588b0297.png">

**Minimal reproduction project:**
[GlowBugDemo.zip](https://github.com/godotengine/godot/files/1893125/GlowBugDemo.zip)

**Comment by reduz** [comment]
Whathever was broken seems to be working now, as it can be evidenced in the following test:
![image](https://user-images.githubusercontent.com/6265307/48644419-40cdf700-e9c1-11e8-8c5b-cc0da1422fdf.png)
closing.
