### ISSUE TITLE
Convert to Tileset Ignores StaticBody2D position transforms

### ISSUE THREAD

**Issue by kenneth-leblanc** [godotengine/godot#18090]
Possibly related to issue [#14386](https://github.com/godotengine/godot/issues/14386) but the description on that issue was unclear. I think this bug may also ignore scaling on the StaticBody2D, but that requires further investigation.

**Godot version:**

v3.0.2 

**OS/device including version:**

Windows 10

**Issue description:**

Convert to Tileset Ignores StaticBody2D position transforms. When creating a tileset using a scene. If the StaticBody2D is re-positioned using it's Position Property, that re-position will be ignored and the collision shape will not be in the correct position.

**Steps to reproduce:**
- Create a Scene.
- Add a root **Node**
- Add a **Sprite** node. 
  - Add a 32px by 32px image. 
  - Turn off **Centered** (Allow the **Offset** to be 0,0)
- Add a **StaticBody2D**
- Add a **CollisionShape2D**
  - Add a **RectangleShape2D**
  - Set **Extents** 16,16

**Note:** See how the collision shape doesn't line up with the Tile? Now correct by follow the step below.

 - On the **StaticBody2D** (NOT the CollisionShape2D) set the **position** to 16,16

Now it looks correct. Convert to Tileset and add the tile to a game. Now turn collision shapes on and view where the collision shape for the tile is located. It ignored the StaticBody2D position shift.

**Note:** If instead of shifting the StaticBody2D the CollisionShape2D were shifted it would have correctly been shifted. Both can be seen in the example provided below.

**Minimal reproduction project:**

[Bug1.zip](https://github.com/godotengine/godot/files/1891053/Bug1.zip)
remember to turn on Visible Collision Shapes under the Debug menu

**Comment by bojidar-bg** [comment]
Some notes for solving it:
* Here the shape transform is calculated:
    https://github.com/godotengine/godot/blob/6c2d36271d3ef3761ebcf611da2d270a6aac49bf/editor/plugins/tile_set_editor_plugin.cpp#L123-L129

* Here are the places in which the `phys_offset` variable is changed:
    https://github.com/godotengine/godot/blob/6c2d36271d3ef3761ebcf611da2d270a6aac49bf/editor/plugins/tile_set_editor_plugin.cpp#L81
    https://github.com/godotengine/godot/blob/6c2d36271d3ef3761ebcf611da2d270a6aac49bf/editor/plugins/tile_set_editor_plugin.cpp#L94-L96

* Here the staticbody is found:
    https://github.com/godotengine/godot/blob/6c2d36271d3ef3761ebcf611da2d270a6aac49bf/editor/plugins/tile_set_editor_plugin.cpp#L118

What should be done is changing the `shape_transform` to include the staticbody transform.
Something along the lines of `sb->get_transform().xform(shape_transform)` should do the trick.

**Comment by alexzheng** [comment]
Some other values like the scale in sprite are also lost in the exported tileset.

**Comment by bojidar-bg** [comment]
@alexzheng While it would be best if it was exported as well, currently there is only a Vector2 offset for the texture/normal_map in the TileSet resource itself, so it would require some more tinkering around to do properly. I would suggest opening another issue for that, if you think it is useful to have.

**Comment by swarnimarun** [comment]
I think this issue should now be closed.

**Comment by akien-mga** [comment]
Fixed by #18529.
