### ISSUE TITLE
Add overloaded Timer.start() that accepts wait_time

### ISSUE THREAD

**Issue by kenneth-leblanc** [godotengine/godot#18107]
**Godot version:**

3.0.2

**OS/device including version:**

All
 
**Enhancement Suggestion:** 
Add an overload of Timer.start() that accepts a float and automatically assigns it to wait_time.
it would basically roll two lines of code into one when desired.
```
$Timer.set_wait_time(1)
$Timer.start()
#vs
$Timer.start(1)
```

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Hinsbart** [comment]
Sadly Godot doesn't support method overloading. We could add a new method for this though.

**Comment by kenneth-leblanc** [comment]
Maybe I am using the wrong term, but Godot claims it supports this type of "overloading" for AnimatedSprite.

> void play( String anim="" )
> Play the animation set in parameter. If no parameter is provided, the current animation is played.

**Comment by KidRigger** [comment]
Chaosus's method seems doable. I can get on this if it has to be done.

**Comment by kenneth-leblanc** [comment]
Here is how it it done in AnimationPlayer
`void AnimatedSprite::play(const StringName &p_animation) {

	if (p_animation)
		set_animation(p_animation);
	_set_playing(true);
}`
