### ISSUE TITLE
Visual Script error debugging improvements (regression)

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#18103]
Master branch

This is a feature proposal, When an error occurs on a VisualScript the node is not highlighted and the script is not opened like in GDScript. Improving this part makes way easier debug an error since you don't need to check the stack trace

**Steps to reproduce:**
- Open the attached project
- press F5

**Minimal reproduction project:**
[VisualScript.zip](https://github.com/godotengine/godot/files/1893695/VisualScript.zip)

**Comment by eon-s** [comment]
This is a regression, on 3.0.2 the node is highlighted in red on error.

**Comment by akien-mga** [comment]
Confirmed the bug on the current master branch (34d0585) and 3.0.6. As mentioned by @eon-s, it works well in 3.0.2, so the regression was cherry-picked to the 3.0 branch too.

**Comment by akien-mga** [comment]
Confirmed, the regression is caused by 095e2bcc (#16888) in the `master` branch, and 5eebe510 (its cherry-pick) in the `3.0` branch.
