### ISSUE TITLE
Shader editor no longer does syntax highlighting (Regression)

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#18104]
**Godot version:**

ca1312d

**OS/device including version:**

Antergos x86_64

**Issue description:**

![image](https://user-images.githubusercontent.com/26753932/38548841-fa43a7ee-3cdc-11e8-935d-80097e889e8f.png)

**Steps to reproduce:**
1. Open existing shader, or create a new one.

**Minimal reproduction project:**

Try with this basic shader:
```
shader_type canvas_item;
void fragment(){
COLOR=vec4(1.0);
}
```

**Comment by akien-mga** [comment]
CC @Paulb23

**Comment by Noshyaar** [comment]
Bisection indeed says #18040
