### ISSUE TITLE
Saving a texture as png with save_png() gives corrupted image

### ISSUE THREAD

**Issue by garyo** [godotengine/godot#18109]
Saving a texture with `save_png()` saves what looks like a corrupted mipmap, or maybe something overwrote the image data; it's not the full-res texture image.
This is with godot 3.0.1 master 3ad9e4740 on Windows. No GDnative or anything fancy. Here's the main.gd that does the saving:

```
func _ready():
	var filename = "texture-image-saved.png"
	print("Saving PNG for ", $Floor, $Floor.get_surface_material(0))
	var img = $Floor.get_surface_material(0).albedo_texture.get_data()
	var x = img.save_png(filename)
	print("Saved.")
```

Minimal project attached; just run it and look at the resulting `texture-image-saved.png` file.

Minimal repro project: 
[save-tex-test.zip](https://github.com/godotengine/godot/files/1894976/save-tex-test.zip)

Source texture:
![picture08_basecolor](https://user-images.githubusercontent.com/139975/38562165-eefea4f4-3ca7-11e8-9eda-6a3ffc41489e.jpg)

What you get from save_png():
![texture-image-saved](https://user-images.githubusercontent.com/139975/38562353-5facc4ba-3ca8-11e8-992b-86efc09442a0.png)

The bottom 3/4 of the main image is OK; the top 1/4 is quarter res vertically and doubled horizontally (could be a half-res image in the same memory), then quarter of that etc.

**Comment by Vega-KH** [comment]
I haven't found the solution to this yet, but this may be useful: This error only happens if you import the texture using the "VIDEO RAM" compression method. If the texture compression is set to lossless, lossy, or uncompressed, the saved image file is correct.

Probably related to #16079

**Comment by Vega-KH** [comment]
On second thought, it seems the get_data method is buggy when writing a file saved as video ram.  With the other formats, the image writes fine even if MipMaps are on.  

As a work around, you can clear mipmaps before you save like this:
`
func _ready():
	var filename = "texture-image-saved.png"
	print("Saving PNG for ", $Floor, $Floor.get_surface_material(0))
	var img = $Floor.get_surface_material(0).albedo_texture.get_data()
	img.clear_mipmaps()
	var x = img.save_png(filename)
	print("Saved.")
`
This will produce a correct image.

**Comment by volzhs** [comment]
should `clear_mipmaps()` be done in `save_png()`?

**Comment by Vega-KH** [comment]
On a brief look at the code, it appears that the save_png function works on a reference to the texture image (rather that creating a copy like the code above does.) So running clear_mipmaps() inside save_png() would delete the mipmaps from the original texture.

So one solution would be to alter the save_png function to make a copy of the image, then clear mipmaps, then save it. This would temporarily use up some memory, but it could be immediately disposed.
