### ISSUE TITLE
Opening an AnimationPlayer "edits" the scene

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#18112]
**Godot version:**
 cc5acaf

**Issue description:**
When opening an AnimationPlayer (clicking the node to open the Animation tab), it will make the scene think something was edited, and make it act as such (add (*) besides the title, and ask for confirmation when closing it).

**Comment by flashyincceo** [comment]
Hi! I am unable to replicate this issue on OSX with the latest development version. Is there a minimal reproduction project you could provide? 

![animationplayer](https://user-images.githubusercontent.com/18668880/39101289-34193b8a-465d-11e8-8a52-46a13c5ab552.gif)

**Comment by YeldhamDev** [comment]
@flashyincceo I think I got that triggers it!

- Have a AnimationPlayer with at least two animations.
- Make that they have different lengths from each other.
- Switching between then will cause the scene to be "edited".

**Comment by flashyincceo** [comment]
@YeldhamDev Thanks! I am able to replicate it and will look into why.
