### ISSUE TITLE
Mouse cursor must be exactly 32x32 on Windows

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#18115]
**Godot version:**
Godot 3.0.2

**OS/device including version:**
Windows 7 x64

**Issue description:**
The code for `Input.set_custom_mouse_cursor` calls `OS_Windows::set_custom_mouse_cursor()` internally, which only checks whether the given cursor's width and height are below 256 pixels. It then calls `SetCursor`.

On Windows, `SetCursor()` seems to fail for any texture that isn't exactly 32x32:

>Type:Error
Description: 
Time: 0:00:01:0503
C Error: Condition ' texture->get_width() != 32 || texture->get_height() != 32 ' is true.
C Source: platform\windows\os_windows.cpp:1895
C Function: OS_Windows::set_custom_mouse_cursor

This needs to be checked for on Windows if true and needs the corresponding docs to be updated.

Reported on Discord by user Paco.

**Steps to reproduce:**
Try setting a custom cursor on Windows to any texture that isn't exactly 32x32.

**Comment by mrcdk** [comment]
Already fixed in master with this PR https://github.com/godotengine/godot/pull/18002

**Comment by mhilbrunner** [comment]
Ah, thaks. Duplicate of https://github.com/godotengine/godot/issues/17992 then.
