### ISSUE TITLE
Theme with text editor

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#18126]
**Godot version:**

3.1.dev cb7fe2c79

**OS/device including version:**

**Issue description:**

are those menu still functional and needed?
![image](https://user-images.githubusercontent.com/8281454/38633397-77d5ce4e-3dfa-11e8-8cab-23e47590e3aa.png)

I got `Error while saving theme` when save theme from this menu.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by volzhs** [comment]
Oh, I can save it if the file name is not `default.tet`, `adaptive.tet` or `custom.tet` and use it from editor settings.
it'd be better to show proper message than just saying "Error while saving theme"

**Comment by Zylann** [comment]
Shouldnt this menu be in `Syntax Highlighter` though?

**Comment by volzhs** [comment]
almost...
this `.tet` file for text editor theme has like below.

```
[color_theme]

background_color="ff1d2227"
completion_background_color="ff2f363f"
completion_selected_color="11ffffff"
completion_existing_color="23ffffff"
completion_scroll_color="11ffffff"
completion_font_color="ffcbcccf"
caret_color="ffffffff"
caret_background_color="ff000000"
line_number_color="7fcbcccf"
text_color="ffcbcccf"
text_selected_color="ff171b1f"
keyword_color="ffff7085"
base_type_color="ff42ffc1"
engine_type_color="fff451d2"
function_color="ff56b3ff"
member_variable_color="ffb781f8"
comment_color="7fcbcccf"
string_color="ffffeba0"
number_color="fff6c183"
symbol_color="ff2e95da"
selection_color="ff460846"
brace_mismatch_color="ffff5634"
current_line_color="11ffffff"
line_length_guideline_color="ffdfff37"
mark_color="66ff6666"
breakpoint_color="ffff5634"
code_folding_color="cccccccc"
word_highlighted_color="56cb94d3"
search_result_color="11ffffff"
search_result_border_color="b2ffffff"
```

**Comment by Amssat221** [comment]
Is this Issue closed? I can't reproduce it

**Comment by Calinou** [comment]
I still get an error when trying to save over a built-in theme such as **Adaptive** (tested on https://github.com/godotengine/godot/commit/25c1363a1167cc5833111e78e33b2561f1ceb76c):

![image](https://user-images.githubusercontent.com/180032/55439127-eca86580-55a3-11e9-9acc-2f6c70aab1bf.png)

Results in:

![image](https://user-images.githubusercontent.com/180032/55439106-ddc1b300-55a3-11e9-900f-31f06407f82e.png)
