### ISSUE TITLE
Can't select child node by clicking on viewport

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#18128]
**Godot version:**

3.1.dev cb7fe2c79

**OS/device including version:**

**Issue description:**

Can't select child node by clicking node on viewport when parent node is selected.
it works fine with 3.0.2-official

**Steps to reproduce:**
![3 0 2-official](https://user-images.githubusercontent.com/8281454/38639923-a878ec08-3e0d-11e8-93a8-2bae876b2153.gif)
[3.0.2-official]

![3 1 dev](https://user-images.githubusercontent.com/8281454/38639929-b109fee8-3e0d-11e8-9e08-7595b5690d42.gif)
[3.1.dev]

**Minimal reproduction project:**

**Comment by groud** [comment]
hmm, I don't know what shall we do with that. 
The current system is more consistent since you don't want to have to click only on the parent area to drag the node. Maybe I can check if the node moved on drag release, and select the child if the mouse hasn't moved.
