### ISSUE TITLE
AnimationPlayer playing animation in reverse problem.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#1812]
animation speed set to -1 should play animation in reverse from the end to the start. At least it does, when animation is looped. When it is not looped, animation does not play, and playhead stays at the first frame.

**Comment by okamstudio** [comment]
from the editor or from code?

On Mon, May 4, 2015 at 9:52 PM, freemanfromgodotengine <
notifications@github.com> wrote:

> animation speed set to -1 should play animation in reverse from the end to
> the start. At least it does, when animation is looped. When it is not
> looped, animation does not play, and playhead stays at the first frame.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1812>.
>



-- 

*OkamStudio*

**Comment by freemanfromgodotengine** [comment]
from the editors UI.

**Comment by reduz** [comment]
oh ok, playing animations backwards with a button like in blender is a feature for 1.2 (itś on the list)

**Comment by akien-mga** [comment]
I think this feature has been implemented now, at least I know that I can play animations backwards from the animation editor.
