### ISSUE TITLE
Control selection hitbox is offset

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#18129]
Godot 3.0.2
Windows 10 64 bits

I made a simple dialog with controls, and I found out that selecting controls inside it is offset in the editor. It's like the transform of the WindowDialog is not taken into account.

Test project: 
[ControlSelectionDoesntLineUp.zip](https://github.com/godotengine/godot/files/1900319/ControlSelectionDoesntLineUp.zip)

Repro:
1) Open the project above, or create a WindowDialog with some controls in it
2) Move the dialog away from the origin
3) Try to click on controls inside: notice the WindowDialog takes over.
4) Try to click outside of the dialog, near the world origin: notice you can select controls that are inside the dialog.

**Comment by groud** [comment]
Is it still a problem on master ?

**Comment by groud** [comment]
Ok, comes from the fact that the is_set_as_toplevel() value of the WindowDialog is not taken into account in the editor.
