### ISSUE TITLE
KinematicBody move_and_slide doesn't register collisions with sleeping rigid bodies

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#18137]
**Godot version:**

Godot master https://github.com/godotengine/godot/commit/d87307d850186d27d2c27c5916ec8c4744c14979

**OS/device including version:**

Win 10

**Issue description:**

When using `move_and_slide()` with `infinite_inertia = true` it won't register a collision with a RigidBody and if the RigidBody is sleeping it won't wake it up. Because the collision isn't registered trying to manually wake up with the `get_slide_collision()` information isn't possible. With `inifite_intertia = false` the collision will be registered (`get_slide_collision()` works here)

**Steps to reproduce:**
Video https://streamable.com/laqpx

**Minimal reproduction project:**

[kinematic_infinite_intertia_issue.zip](https://github.com/godotengine/godot/files/1901292/kinematic_infinite_intertia_issue.zip)

**Comment by AndreaCatania** [comment]
Fixed #18138

**Comment by mrcdk** [comment]
Yes, that fixed it. Thanks!
