### ISSUE TITLE
Autotiles lacks 'ignore' option in bitmask

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#18134]
Right now it's not possible to do simple bitmask autotiling, because there's no option to ignore if there's a surrounding tile or not in the chosen position. This creates the need to repeat an image to cover all possibilities, consuming space and time.

Things like a simple dirt -> grass in a minecraft-like style, water where the top tile is shorter, etc. are more complicated to be done than needed because of this.

**Comment by MarianoGnu** [comment]
i'm not sure what you mean, but you could easily: slice your tiles in half the size using 2x2 mode or add a tool script to the tileset and override the virtual function _forward_subtile_selection
http://docs.godotengine.org/en/3.0/classes/class_tileset.html#class-tileset-forward-subtile-selection

**Comment by MarianoGnu** [comment]
Sorry, I don't see an use case for this, can you give me an example?

**Comment by mateusak** [comment]
Right now there's the need for a 3x3 and a 3x3 minimal. But the 3x3 isn't really usable, since you need to cover so many cases. If this would be implemented, there would be no need for a 3x3 minimal and the 3x3 would become usable, since you can ignore some cases.

**Comment by MarianoGnu** [comment]
so, 3x3 minimal is too simple and 3x3 is too complex? i'm not buying this U_U as much i'd add a 2x2 custom and 3x3 custom and let the user generate the bitmask himself using an script, the same way _is_tile_bound and _forward_subtile_Selection works, but i'm not sure what do you expect with a mixed frankenstein like that, it's so confusing to me

**Comment by mateusak** [comment]
Okay, you're clearly not understanding, since this is the default for about every autotiling mechanism I've ever seen.

![example](https://user-images.githubusercontent.com/18586380/40795754-629ce516-64d9-11e8-86c5-09d146186711.png)
_Example bitmask. There must be tiles on top and bottom, not be tiles on right and left, and it doesn't matter if there's tiles on the corners._

It's pretty simple. On the current bitmask tab on autotiles, you can paint it red or transparent, as to check or not to check for adjacent tiles. It's only natural to have an option to ignore adjacent tiles (which is blue on the example). **There is no generating the bitmask yourself whatsoever (where did you take that from?), just clicking on a tab like you do now.**

This can be achieved without hassle, adding a shit ton of functionality, uniting 3x3 and 3x3 minimal, simplifying minimal tilesets and so much more.

**Comment by MarianoGnu** [comment]
this is because the bitmask is not generated on the tile and then see if it fits the map, it's done on the inverse, it's generated on the map and then search for a tile that matches it, i really dont see too much of a win on this, but if someone wants to to this, PR welcome

**Comment by Shadowblitz16** [comment]
this needs to be supported.
there is actually a unity addon called rule tiles which does this.

i would suggest using green for tile required, red for not tile required and off for not caring
this would make autotiles much more customizable.

**Comment by mateusak** [comment]
@Shadowblitz16 Yeah. Right now you can't really do 2D platforms using TileMaps because of the lack of this. I don't think I made my point very sellable, hahaha.

And I can't bother to learn the tilemap logic and alter it, unfortunately. Nobody else seems to care too. Probably never going to be implemented.

**Comment by Shadowblitz16** [comment]
what why? this is a major flaw in autotiling

@MarianoGnu please add this. it would be used I guarantee it.
for example this is my tilemap 
![image](https://user-images.githubusercontent.com/2453707/52529617-aa505f80-2ca9-11e9-9853-866f1dc51352.png)

I can't make the middle piece be picked when there is a tile top,bottom,left,right.
I don't want it to take in account diagonal tiles.

**Comment by tomc1998** [comment]
I'm also having a problem with this, autotiling is basically unusable unless you design your tileset FOR the godot autotiling:/

**Comment by SpechtMagnus** [comment]
I'm about to implement this. Do you think I should use an extra integer for this bitmask or use the same that is used for regular autotiles.
I think the second option would cause less problems with existing tilemaps. But I'd have to extend it to 32 bits. Additionally it would probably be better to use the 16th bit of the integer  as the first of the ignore bits so there's some room for additional flags in between. (Yes I already have something in mind but I need this to work first.)

**Comment by SpechtMagnus** [comment]
Done
