### ISSUE TITLE
Compile Android with libc++_shared.so STL 

### ISSUE THREAD

**Issue by sixo** [godotengine/godot#18141]
**Godot version:**
3.0.2

**OS/device including version:**
Android

**Issue description:**
Android build is now compiled with STL enabled by default. `gnustl_static` is selected as the default library in `platform/android/detect.py`. 

Possible issues with gnustl_static:
- it will be [deprecated and removed](https://developer.android.com/ndk/guides/cpp-support.html#gnustl) in future NDK release
- it is covered by GPLv3
- it is linked statically; I'm not sure if this could be an issue, but with GDNative, additional .so library linked to a different STL runtime could be loaded, and this [might cause issues](https://developer.android.com/ndk/guides/cpp-support.html) (see "One STL Per App" & "Static runtimes")

The build system could link to LLVM's libc++_shared.so by default or provide a way to pick the library with build parameter from shell.

**Comment by rdhafidh** [comment]
Hello. I have some basic working android build of detect.py modification to work with current 2.1 branch and of course with current android ndk r17b using [libc++_shared stl config](https://github.com/rdhafidh/godot/commit/f18df587633185825bb6c500fb0f152317d3d026). Will try forward port into 3. But still have no idea on how to bundle libc++_shared.so into final exported apk. Reading though platform/android/export/export.cpp has kind of this logic. Am I missing some dummy config this case or prefer hacking around export.cpp's logic to include my missing libc++_shared.so ?
What do you think?

Regards
Hafidh.

**Comment by sixo** [comment]
I checked only the build scripts in version 3.0.2. 
In that version at the end of the SCSub file inside of platform/android/,  there is code that copies  the actual godot library (libgodot_android.so) into platform/android/java/libs/.
```
# Somewhere around line 167 in platform/android/SCsub
env_android.Command(out_dir + '/libgodot_android.so', '#bin/libgodot' + env['SHLIBSUFFIX'], Move("$TARGET", "$SOURCE"))
```
Copying a library into this dir seems to be  sufficient for the library to be included into the final APK. <br>
So adding e.g. this into the SCsub should be sufficient to package c++_shared.so into APK
```python
    stl_lib_path = str(env['ANDROID_NDK_ROOT']) + '/sources/cxx-stl/llvm-libc++/libs/' + lib_arch_dir + '/libc++_shared.so'
    env_android.Command(out_dir + '/libc++_shared.so', stl_lib_path, Copy("$TARGET", "$SOURCE"))
```

**Comment by rdhafidh** [comment]
@sixo, sorry it does not seems to work here, tried multiple times open / close project and clicking export android apk in project setting, still leaving missing c++_shared.so.

**Comment by sixo** [comment]
It's possible that I didn't completely understand your question. <br>
After changing SCsub you need to rebuild godot for Android from sources once again
```
scons p=android target=realease_debug
```
You should check if the `libc++_shared.so` was correctly copied into `platform/android/java/libs`
<br>
After you have build godot with the new changes successfully for Android platform, you should generate new export templates by going to `platform/android/java` and executing
```
gradlew build
```
Now the new android_debug/release.apk inside of output `godot/bin` directory should contain the libc++_shared.so
<br>
Once you have your updated APKs, you need to point to them in Godot's editor in Project/Export->Custom Package.
Only then will the exported APK use libc++_shared.so

**Comment by rdhafidh** [comment]
confirmed working now, thanks. Is it worth now to make upstream change?

**Comment by Calinou** [comment]
@rdhafidh [The Travis CI setup is now on NDK r18](https://github.com/godotengine/godot/commit/7be2152d2ac89c1b8049b27aa6d90f3d372849a5), should this issue be considered as resolved?

**Comment by sixo** [comment]
I couldn't test this myself on any device yet.

I see that `gnustl_static` has been removed from build script. 
`libc++_shared.so` is now picked in the link flags in `platform/android/detect.py`. 
That might be sufficient, but ideally somebody should test this with gdnative module linked to c++ runtime to see how it works.

**Comment by Calinou** [comment]
As per @sixo's comment, I'll close this issue. If you're having trouble linking third-party libraries, please open a new issue.
