### ISSUE TITLE
Godot .pck exporter cannot handle over 2.4 GB

### ISSUE THREAD

**Issue by Tugsav** [godotengine/godot#18147]
Tested on Godot 3.0.2-stable_x11.64
OS: ubuntu 16.04 LTS (64 Bit)

When exporting a project with an import folder of 2.4 GB or more the .pck exporter throws errors. The resulting .pck file is corrupted.

![image](https://user-images.githubusercontent.com/3738264/38680071-b214a7c2-3e65-11e8-88f2-a04483d53772.png)

Reproducing:
This [repository](https://github.com/Tugsav/GodotPackBug) contains a small test project for reproducing the issue.
Not that upon import it will generate 2.4 GB in the .import folder (10000x10000 px uncompressed images)
Attempting the export a .pck from this project will generate an error. If one of the images are deleted (and the corresponding import file removed) the project can be exported without issues (2.0 GB in the .import folder).

**Comment by sdfgeoff** [comment]
I doubt this is the case, but FAT32 file systems don't support files larger than 2Gb. However, as you're on Linux and probably using ext4, this is likely an engine bug.

**Comment by Calinou** [comment]
@sdfgeoff The file size limit on FAT32 filesystems is 4 GB, not 2 GB (at least on modern Windows versions).
