### ISSUE TITLE
[GDScript] Add support for trailing commas in function calls

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#18151]
**Godot version:**
3.0.2 (Steam)

**Issue description:**
GDScript currently supports trailing commas when creating arrays and dictionaries, but not when calling functions. Eg.:
```
var foo = [
    1, 2, 3,
    4, 5, 6,
]
var bar = {
    1:1,
    2:2,
    3:3,
}
do_baz(
    1, 2, 3,
    4, 5, 6,
) # Error parsing expression, misplaced: ')'
```
My diffs will thank you if this gets added. :)

**Comment by vnen** [comment]
I find this syntax quite odd, never seen it before, but some languages supports it (like Python and Javascript). So I guess it's an okay addition.

**Comment by romlok** [comment]
I find that this functionality is useful in and of itself.
For example, if I have the following call committed in my codebase:
```
my_tween.interpolate_method (
    get_node("SomeNode"), "set_thing",
    from_val, to_val, duration
)
```
and later I want to change the transition and easing from the default:
```
my_tween.interpolate_method (
    get_node("SomeNode"), "set_thing",
    from_val, to_val, duration,
    TRANS_BOUNCE, EASE_OUT
)
```
The diff for this would include something like:
```
-    from_val, to_val, duration
+    from_val, to_val, duration,
+    TRANS_BOUNCE, EASE_OUT
```
Whereas if trailing commas were used, the diff could need only one change:
```
+    TRANS_BOUNCE, EASE_OUT,
```
A simpler diff not only means it's easier to see at a glance what functionality has changed, but may also make a rebase/merge less troublesome, in case another branch has modified the prior line.

**Comment by remram44** [comment]
This is really surprising because a trailing comma is accepted in arrays, dictionaries, and enums. In fact they are recommended in [the official style guide](https://docs.godotengine.org/fi/latest/getting_started/scripting/gdscript/gdscript_styleguide.html#trailing-comma).

But they don't work for function calls :thinking:

**Comment by vnen** [comment]
> But they don't work for function calls

Because arrays and dictionaries and enums usually span multiple lines. Function calls are usually in the same line.

**Comment by Calinou** [comment]
Implementing this in function calls is definitely possible, it just uses a different code path compared to arrays/dictionaries/enums. This is probably why it's not supported yet.

**Comment by Calinou** [comment]
This was implemented in the GDScript rewrite which is now merged in the `master` branch, closing. See also https://github.com/godotengine/godot/issues/41066.
