### ISSUE TITLE
Current selected script or doc is not updated when using sort in script list

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#18153]
**Godot version:**

3.1.dev cb7fe2c79

**OS/device including version:**

**Issue description:**

Current selected script or doc is not updated when using sort in script list

**Steps to reproduce:**
![sort](https://user-images.githubusercontent.com/8281454/38695070-3c6efd36-3ec6-11e8-827f-78b2dcba96cd.gif)

**Minimal reproduction project:**

**Comment by vnen** [comment]
This correct to me, considering that doc pages go to end of the list (unless you disabled this in Editor Settings).

**Comment by volzhs** [comment]
![sort2](https://user-images.githubusercontent.com/8281454/38697040-c9243340-3ecb-11e8-92d1-7ec0faca787b.gif)
@vnen what about this one?

**Comment by vnen** [comment]
Oh, I misunderstood the issue, I thought it was a problem with the sorting.

I see now what you mean, the script list should keep the same item select, but it keeps the same *position*.

**Comment by Calinou** [comment]
I can't reproduce this in Godot 3.2.2beta4, closing. It's probably been fixed since this bug was reported.
