### ISSUE TITLE
Fail to build Godotsharp solution

### ISSUE THREAD

**Issue by Tommel1234** [godotengine/godot#18152]
**Godot version:**
Godot 3.0.2 with mono

**OS/device including version:**
Windows 10 64bits

**Issue description:**
I was working on a 2d project with godot 3.0.2 mono C# and everything was working very well ! but I had to reinstall win 10 for some reason. Now i can't build my project even if i have installed mono 5.4.1 .. It's the same if I try to generate a C# solution with a new project. I always get the same error (Screenshot)
![monissue](https://user-images.githubusercontent.com/18587154/38692919-4f7d3ab4-3e53-11e8-86b0-5e97433f171f.png)

I have try to reinstall mono.. and even try other versions, and still nothing.

**Mono log: msbuild_log.txt**
Project "GodotSharp.sln" (Build target(s)):
	Message: Building solution configuration "Release|Any CPU".
	Project "GodotSharp.csproj" (default targets):
		Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
		C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB6004: The specified task executable location "\\csc.exe" is invalid. [C:\Users\tomme\AppData\Roaming\Godot\mono\solutions\5128684965136174502_1_1\GodotSharp\GodotSharp.csproj]
	Done building project "GodotSharp.csproj" -- FAILED.
Done building project "GodotSharp.sln" -- FAILED.

I can't find what wrong, my system is exactly the same as previously, I got everything install like before (vs code, vs community, unity ..) and everything seem to work fine except Godot mono :/

(Sorry for my bad english)

**Comment by KellyThomas** [comment]
Have you set Editor Settings > Mono > Builds > Build Tool to `Mono (System)`?

**Comment by Tommel1234** [comment]
Yes ! Still get an error !

**Comment by KellyThomas** [comment]
I had the same "\\csc.exe" issue when I was using the Build Tools for Visual Studio 2017 distribution.

After uninstalling build tools and then Installing Visual Stuido Community 2017 with these components I could successfully build godot projects:

 * .Net Framework 4.6.1 SDK
 * C# and Visual Basic Roslyn compilers
 * C# and Visual Basic
 * .NET Framework 4.5 targeting pack
 * MSBuild
 * .NET Framework 4.6.1 targeting pack
 * .NET Core runtime
 * .Net Compiler Platform SDK

I would be surprised if every one of these are needed but I never went back to test which ones were required.

**Comment by Tommel1234** [comment]
Thank a lot ! I have follow your advice and it's working now .. I think the problem was the .Net framework 4.5 targeting pack which could not be found by godot! I had to reinstall vs community and his components to fix it.

Maybe there was a problem during my first visual studio installation.. I think this issue can be closed if there is nobody else with this problem.

**Comment by mhilbrunner** [comment]
Closing for now, as it was fixed as per comment above.
