### ISSUE TITLE
Open project folder in File Manager from the Project Manager window

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#18165]
**Godot version:**
v3.0.2.stable.mono.official

**Recommendation:**
I believe you would greatly benefit from being able to open a project folder in your OS's explorer/file browser, as a developer working actively with Godot Engine.

We might all benefit from not having to manually open up a separate file browser, and navigate to the project folder.
![Project Manager window](https://i.imgur.com/KHX3oZ2.png)

Currently there is no option to open your local file explorer/browser from Godot Engine's Project Manager window. Adding a simple "Open Project Folder" button (or something equivalent in function) would be one more step forward towards improving workflow with Godot Engine. 

It might be noteworthy to mention that with the evolution of Godot Engine, with the added functionality, we might also want to consider adding a context menu in the Project Manager in addition to the buttons that already are on the page. 

![Project Manager window with context menu](https://i.imgur.com/v9NQdyg.png)

**Comment by Noshyaar** [comment]
Introducing the hide-and-seek champion.
![screenshot_2018-04-13_10-11-01](https://user-images.githubusercontent.com/26753932/38714998-0feb0ec0-3f03-11e8-91b4-8d2fec6c3637.png)

**Comment by mattiascibien** [comment]
Isn't it already introduced with https://github.com/godotengine/godot/commit/1d2d08da5b04abcd1c956c32d5cec4733b281d40?

**Comment by ivanskodje** [comment]
Wait - That's photoshop right? 
If it exists, we should name the button node "Waldo"

**Comment by vnen** [comment]
It only shows when you select the project.

**Comment by ivanskodje** [comment]
You mean like this? No button, unless it has been added in a newer release.
Keep in mind that this is on the Mono version on Windows.
![](https://i.imgur.com/4er1Rgp.png)

**Comment by Noshyaar** [comment]
3.0.2 stable doesn't have it yet.

**Comment by ivanskodje** [comment]
The improvement I could suggest, is adding a right-click context menu in the Project Manager menu,

**Comment by Anutrix** [comment]
Button is visible all the time and works on single click in Godot_v3.1-alpha1_win64

**Comment by KoBeWi** [comment]
In 3.1 the icon is always visible and in 3.2 it got a new look
![image](https://user-images.githubusercontent.com/2223172/67622227-9b4e1500-f818-11e9-9e95-aeb7e4759a2f.png)
So it's probably enough to close this
