### ISSUE TITLE
X-Box One S Controller getting incorrect input - Linux

### ISSUE THREAD

**Issue by MoustafaC** [godotengine/godot#18167]
**Godot version:**
3.0.2

**OS/device including version:**
Ubuntu 17.10 x86_64

**Issue description:**
Recently acquired an X-Box One S controller. Tried running it with my project, and noticed inconsistencies with other controllers:

* Right thumbstick incorrectly maps input:
    - Left/Right results in Up/Down motion
    - Up does not work
    - Pressing thumbstick results in View/Back
* Left thumbstick click results in Right thumbstick click
* View/Back results with Left Trigger
* Menu/Start results with Right Trigger
* X-Box button results in Left thumbstic click
* RT moves Axis 5
* LT moves Right thumbstick Left/Right, sticks on left after release

**Steps to reproduce:**
Plug in/pair X-Box One S controller, start project/assign inputs

**Minimal reproduction project:**
*Joypads* demo

I can attach a video and any logs needed for this issue.

**Comment by Hinsbart** [comment]
3.0.2 is missing a few controller mappings compared to the master branch.
Could you try it again with
`Input.add_joy_mapping("050000005e040000fd02000003090000,Xbox One Wireless Controller,a:b0,b:b1,back:b15,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b16,leftshoulder:b6,leftstick:b13,lefttrigger:a5,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a4,rightx:a2,righty:a3,start:b11,x:b3,y:b4,platform:Linux,", true)`  and

`Input.add_joy_mapping("030000005e040000d102000001010000,Xbox One Wireless Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,", true)` ?

**Comment by NykolaR** [comment]
I also have problems using the dualshock 3, the left analog and triggers are the only things that seem correctly mapped, all the other buttons kinda wildly toggle on/off (maybe mapped to gyro or something?). I've been dodging the issue by using xboxdrv, but will look into the incorrect mappings further and try to fix it.

Also will try the current master branch to see if it's already working

**Comment by MoustafaC** [comment]
@Hinsbart Had to look-up the correct SDL value for the controller while plugged in (030000005e040000ea02000001030000), and everything works correctly then.

**Comment by aaforcebox** [comment]
I had the same problem, added @MoustafaC 's mapping and it worked. Both mappings by @Hinsbart doesn't work. I'm using an X-Box One controller on Linux Mint 19, Godot 3.1.alpha.official.

**Comment by akien-mga** [comment]
@MoustafaC @aaforcebox So what's the exact mapping to use for this controller? I know about `030000005e040000ea02000001030000` but what about the rest?

**Comment by aaforcebox** [comment]
I tried every button without the mapping, so this is what we get:
```
y: "button_index":3
a: "button_index":0
x: "button_index":2
b: "button_index":1
L: "button_index":4
R: "button_index":5

left: 14
right: 15
down: 13
up: 12
select: 6
start: 7

left stick b: 9
right stick b: 10

left stick: axes 0 1
right stick: axes 3 4

left trigger : a2
right trigger : a5
```
So @Hinsbart 's mapping was right, just replace the 'key' with @MoustafaC 's:

`Input.add_joy_mapping("030000005e040000ea02000001030000,Xbox One Wireless Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,", true)`

Now everything works. =]

**Comment by akien-mga** [comment]
Thanks, I'll add this in #22466.

**Comment by akien-mga** [comment]
I made a PR upstream (gabomdq/SDL_GameControllerDB#222).
