### ISSUE TITLE
Controls use bad calculation for margins + anchors when child of Node2D

### ISSUE THREAD

**Issue by groud** [godotengine/godot#18169]
**Godot version:**
Master branch

**Issue description:**
Following the discussion in #18166, several calculus in control.cpp use the _edit_get_rect() function for core mechanisms. This ends up in the code using the meaningless Node2D's "selection rectangle" as a base for the calculation of archors and margins, when a Control is used as a child of a Node2D.

So if you have this hierarchy:
- Node2D
   - Control with anchors 0,0,1,1 and Margins 0,0,0,0

The control will appear 64x64 while it should be 0x0 (the Node2D size makes no sense)

**Comment by Zylann** [comment]
What happens if the parent is a sprite though?

**Comment by groud** [comment]
It acts as if the sprite was a control node
