### ISSUE TITLE
2DEditor: error spam when creating sprite with compressed texture

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#18177]
**Godot/OS version:**

1d15c5d Antergos x86_64

**Issue description:**

`Can't get_pixel() on compressed image, sorry.` prints when mouse over sprite with compressed texture.

```
Godot Engine v3.1.dev.custom_build (c) 2007-2018 Juan Linietsky, Ariel Manzur & Godot Contributors.
Create Node
 Can't get_pixel() on compressed image, sorry.
 Can't get_pixel() on compressed image, sorry.
 Can't get_pixel() on compressed image, sorry.
 Can't get_pixel() on compressed image, sorry.
 Can't get_pixel() on compressed image, sorry.
 Can't get_pixel() on compressed image, sorry.
```

**Steps to reproduce:**
1. reimport icon.png as compress_mode: vram
2. drag it on the 2D editor viewport (to create sprite node)
3. move cursor over image, prints error

**Comment by Noshyaar** [comment]
cc: @groud

**Comment by groud** [comment]
cc: @poke1024 
I suspect [this commit to be the cause](https://github.com/godotengine/godot/commit/8505871a87b59b27acc0912a6dd815231c3b78b1#diff-3910e354cfb3848e417581c47035e5c5). :)
