### ISSUE TITLE
Export on Android with external modules that contains provider android:authorities

### ISSUE THREAD

**Issue by megasoft78** [godotengine/godot#18173]
Hi,
I had an issue exporting my game using a custom template that include external modules with provider android:authorities. I'm using branch 2.1.
It must be unique and because they normally get generated based on the package name during gradle it will always end up to something like this:

> android:authorities="com.godot.game.MyProvider" />

I setup a very small change to export.cpp to replace it to the game package name.
It's a diff file I did with WinMerge. I don't know how to use github to create a PR.
If you think it could be useful could you please merge it for me?

[export_cpp_patch.zip](https://github.com/godotengine/godot/files/1907431/export_cpp_patch.zip)

**Comment by megasoft78** [comment]
@xsellier What do you think of it?

**Comment by xsellier** [comment]
This is related to:
https://github.com/godotengine/godot/issues/1813

Those permissions are placeholders, even if they are included in the final APK, android ignore them.

**Comment by Calinou** [comment]
@megasoft78 Is this still necessary given the current status of the Android platform?

**Comment by megasoft78** [comment]
@Calinou Probably not. :)

**Comment by Calinou** [comment]
@megasoft78 Alright, closing then.
