### ISSUE TITLE
Variable binding in match pattern allows invalid identifiers

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#18178]
**Godot version:**
3.0.2 Mono

**OS/device including version:**
KDE Neon

**Issue description:**
Another match issue. If you use a variable binding in a match pattern with invalid characters like `(` and `-` then the parser allows it. Although there is an error printed in the console when the code runs, the match pattern is still matched. See code below for an example.

**Steps to reproduce:**
1. Make new project, add node and add this script to it: (As you can see the variable names in the bindings are invalid identifiers.)
```
func _ready():
	match "emotion":
		var ):
			print("sad")
		var (:
			print("happy")
		var |:
			print("natural")
```

2. I expect the execution of the game to stop and tell me this is not allowed. I also expect an error in the editor *before* I run the game. Instead, it prints "sad" followed by an error in the console when running the game, and the game keeps running.

**Comment by karroffel** [comment]
Ups hehe, the code that causes this should be this one: https://github.com/godotengine/godot/blob/1d15c5d726600047805ab10d53ff2a7efdc41d8e/modules/gdscript/gdscript_parser.cpp#L1896-L1900
