### ISSUE TITLE
Run exported game (server) inside docker

### ISSUE THREAD

**Issue by tecbeast42** [godotengine/godot#18171]
**Godot version:** 3.0.2
**OS/device including version:** Linux
**Issue description:**
If i use a basic template for linux export. I get a list of "presets" (64, X11, pc, s3tc). Is it possible to change these presets so that i can export a version of the game that does not use X11 or even s3tc? The goal is a headless binary export to run inside docker. 

We have successfully build a continous integration pipeline and can export our game with docker, but the server seams to just not run inside docker.

**Steps to reproduce:**

1. Export any game with a Linux/X11 preset 
2. Try to run it inside Docker e.g. ubuntu with all need libs installed

The binary will give the following error:
```
ERROR: initialize: X11 Display is not available
At: platform/x11/os_x11.cpp:129.
```

**Sidenote**
We tried to use the headless build of godot to just run it directly without exporting the game inside docker. This gives the AudioDriver Dummy Error and just hangs.

**Comment by tecbeast42** [comment]
What would be needed to export a project without X11 dependencies? Like a dummy window server maybe?

**Comment by touilleMan** [comment]
related to #17408

**Comment by tecbeast42** [comment]
We got it to work. Closing.

**Comment by touilleMan** [comment]
@tecbeast42 Can you share you setup ?

**Comment by tecbeast42** [comment]
The server is writing essay sized error logs about some render and material stuff but it works.

```
FROM ubuntu

RUN  apt -y -o Acquire::ForceIPv4=true update && apt -y -o Acquire::ForceIPv4=true install xvfb libxcursor-dev libxinerama1 libxrandr2 libxi6 libasound2 libpulse0 libgl1-mesa-glx

COPY export/linux .

CMD xvfb-run -a -n 55 -s "-screen 0 1400x900x24 -ac +extension GLX +render -noreset" ./i-like-walls.x86_64
```

**Comment by tecbeast42** [comment]
This is not a good solution for production. Since the CPU usage goes way up because of the software opengl render i think.

**Comment by touilleMan** [comment]
thanks, will try

**Comment by deralbert** [comment]
I know my suggestion doesn't quite fit the question, but maybe it will help some people who are desperately looking for the solution on the internet and end up in this issue.

When you've built a pipeline and have this error
ERROR: initialize: X11 Display is not available
   At: platform/x11/os_x11.cpp:129.
   
than you can just add export **DISPLAY=":0"** to your script.
