### ISSUE TITLE
No visual feedback on selected curve and polygon edition buttons

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#18188]
**Godot version:**
Godot 3.0.2 stable

**Issue description:**
There is no feedback on the mode selected to edit a polygon or curve, all buttons are always the same.

![toolbar](https://user-images.githubusercontent.com/10215987/38762681-e5f597ae-3f64-11e8-8bf0-be338ad86a25.png)

These buttons should be grayed out except the selected one.

**Steps to reproduce:**
Create a Polygon2D or Curve2D, select a mode (new, edit, delete) and see that all looks the same.

**Comment by aaronfranke** [comment]
In addition to coloring, we should consider a box outline and/or a backdrop.

**Comment by eon-s** [comment]
Wow, I have not noticed that, it should not require so much attention to see it, it must be easy for peripheral vision when editing a scene.

**Comment by willvincent** [comment]
Agreed, it's far too subtle. The non-active buttons should probably be grayscale, or dimmed somehow. A box outline around the active tool as @aaronfranke mentioned would be a great improvement too

**Comment by bojidar-bg** [comment]
CC @djrm

**Comment by djrm** [comment]
There should be a marker below tool buttons, like a little dot or a bar.

**Comment by avencherus** [comment]
Graying out seems like an easy solution, but conflicts with the concept that this is generally used to indicate controls are disabled and can't be used.

I like aaron's idea of including box outlines or backdrop highlights.  Better highlights certainly will help, but it might hard to find a generally agreeable highlight color between all the hue choices for these buttons.  With certain hue mixes, maybe there isn't exactly one highlight that won't be competing for emphasis.

**Comment by aaronfranke** [comment]
I think we have a general idea of what should be done to fix this issue, all we need is someone to propose and implement something, and make a PR. I won't, since I don't use Polygon2D myself.

Regardless, this won't be done for 3.2, so I suggest bumping to the 4.0 milestone.

**Comment by Calinou** [comment]
The [editor theme redesign](https://github.com/Calinou/godot/tree/improve-editor-theme) I'm working on adds a transparent background behind active buttons, so this should be fixed once it's merged.

**Comment by eon-s** [comment]
The UI was updated on 4, but now is counterintuitive.

One can think that the selected button here is the green +
![imagen](https://user-images.githubusercontent.com/10215987/129621103-88d955f4-a5eb-4e5d-887d-17a682b023c4.png)
But is the grayed out red X.

And this is on the default theme, light themes seem to have other issues with this design.

**Comment by Calinou** [comment]
This should be fixable by making those buttons non-flat, so that they will have a background when active.

**Comment by KoBeWi** [comment]
Fixed
![image](https://github.com/godotengine/godot/assets/2223172/cb86587f-5035-4816-a0dd-64de0d1dc768)
