### ISSUE TITLE
ItemList index out of bounds when changing item selection with keyboard

### ISSUE THREAD

**Issue by codespren** [godotengine/godot#18195]
**Godot version:**
Godot engine v3.0.2.stable.mono.official

**OS/device including version:**
Mac OS 10.13.3

**Issue description:**
ItemList doesn't check the number of items in list when user tries to change the selection out of the list bounds by keyboard.

**Steps to reproduce:**
1. Create an ItemList with one or more items in it.
2. Select the last item.
3. Try to change the selection by pressing right arrow key.

Godot prints an error message (in this case there were 3 items): 

0:00:23:0762 - Index p_current=3 out of size (items.size()=3)
----------
Type:Error
Description: 
Time: 0:00:23:0762
C Error: Index p_current=3 out of size (items.size()=3)
C Source: scene/gui/item_list.cpp:283
C Function: set_current

**Comment by ShyRed** [comment]
Cannot reproduce at master version eac2863  

**Demoproject:** [issue18195.zip](https://github.com/godotengine/godot/files/1910304/issue18195.zip)

**Comment by Noshyaar** [comment]
Can confirm but only with 2 colums or more. eac2863

This errors in editor too. Set FileSystem dock to thumbnail mode and when the last row isn't full, select the last item and press right arrow.

**Comment by codespren** [comment]
Example project:
[demo2.zip](https://github.com/godotengine/godot/files/1910350/demo2.zip)

For some reason error occurs only if max. columns is set to 2.
