### ISSUE TITLE
Basic Button Command Does Not Function

### ISSUE THREAD

**Issue by Doomish2005** [godotengine/godot#18198]
**Godot version:**
3.0

**OS/device including version:**
Windows 7 32-Bit operating System Nvedia 210 PC 

**Issue description:**
So I am really want to learn Godot till it is second nature because I want to be an Indie Developer, yet when I was following the official documentation (Word By Word) I discovered a problem with the nodes.The node is The "Button" node. So on Pg. 46 Line 22 It tells us to "Finally, connect the button’s “pressed” signal to _ready() by using Object.connect().". I followed The Instructions below it and found out that Godot thought there was no "Button" node. Which is a real punch in the gut. So please Try to Fix it and thank you in advance! (: (;

**Steps to reproduce:**
Follow all the steps up to were it tells you to connect the to nodes together.(Steps In Official Documentation)

**Minimal reproduction project:**
[BUTTON ERROR.zip](https://github.com/godotengine/godot/files/1910522/BUTTON.ERROR.zip)

**Comment by Doomish2005** [comment]
I Hope You Guys Fix This Major Problem And Thank You

**Comment by Noshyaar** [comment]
Documentation says:
![image](https://user-images.githubusercontent.com/26753932/38770296-0278a5ca-403b-11e8-9e12-05a68d4dc14a.png)

Your scene:
![image](https://user-images.githubusercontent.com/26753932/38770303-211d0d2c-403b-11e8-91a1-3fbb12717abb.png)

Button should be Panel's child, not Label's child. It's not the same.
