### ISSUE TITLE
Support comparison operators in `match` patterns

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#18194]
This is a feature request.  In trying to find a syntactically "nice" solution to a problem I had, I stumbled across the "Invalid operator in pattern" design-time error.  The code looked something like this:
```gdscript
func _input(event):
	match true:
		event is InputEventMouseButton:
			pass
```
This actually isn't very nice syntax at all, but bear with me!

Reading the docs seemed to imply in the Input events tutorial that there exist constants which correspond to each event type that could be read using `typeof()`.  I couldn't find where these constants live -- they don't appear to be in autocomplete or listed as members of InputEvent or GlobalScope, either, nor in the class docs for them.  So, I started writing an `if` block to compare event class types.  A series of `elif` statements would have to go from the most narrow case to the most broad, or I could nest multiple `if` statements and use `get_class()` to compare strings instead of using the `is` operator to compare to true.

Coming from a VB background, I'm used to being able to match expressions to a clause with a comparison operator using the `Select..Case` statement.  `switch (true)` is a bit of a hack I've used in other languages where Case Select functionality isn't available; unfortunately (or perhaps *very* fortunately!), it seems Godot won't let me use `match` in a similar fashion.  

My request is to support using a shorthand keyword in addition to a comparison operator to signify matching if a pattern evaluates true -- specifically, inside a `match` block -- in cases where it would be more readable and/or fallthrough is desired.  Here's some examples of possible syntax:
```gdscript
#using `is` as the first part of a compound operator for comparison shorthand
match x:
    is SomeClass:  #if no other operator follows is, "is" is the default operator
        print("I'm SomeClass!")
        continue
    is > 5:  #can be separated by commas
        print("I'm over 5")

#using `if` instead
match x:
    #if becomes a shorthand for the left-hand operand; there's no default operator
    if is SomeClass:  
        print("I'm SomeClass!")
        continue
    if > 5:  #can be separated by commas, defaulting to matching any clause. 
        print("I'm over 5")

#using a previously reserved keyword to signify matching patterns against true
match x:
    case is SomeClass:  
        print("I'm SomeClass!")
        continue

    #Entire expression clause must evaluate true, 
    # or use commas to match expressions other than `true` without the `case` keyword
    case > 5 and case < 10 or case == -1, SPECIAL_CASE:  
        print("I'm over 5 and maybe I'm special but sometimes I'm also negative")
    
```

I'd appreciate any thoughts or discussion people may have on this.  ~~Maybe there's a smart way to support function calls in the syntax?~~ *(Bad idea, just saw https://github.com/godotengine/godot/issues/18174 !)*  Maybe we still are in need of a `switch` statement?  :)

Also, please excuse any half-baked thoughts here;  I'm filing this issue at 2am and my brain is thoroughly melted...!

**Comment by vnen** [comment]
This could be solved with the addition of pattern guards. Like Haskell:

```haskell
case value of
    x | x > 5     -> "Is greater"
      | x == 5    -> "Is equal"
      | otherwise -> "Is less"
```

Still, for the original example you could match with strings:

```gdscript
match event.get_class():
    "InputEventMouseButton": print("mouse button click")
    "InputEventKey": print("key pressed")
    _: print("other event")
```

**Comment by vnen** [comment]
BTW, this:

```gdscript
match x:
    #if becomes a shorthand for the left-hand operand; there's no default operator
    if is SomeClass:  
        print("I'm SomeClass!")
        continue
    if > 5:  #can be separated by commas, defaulting to matching any clause. 
        print("I'm over 5")
```
Is just an ugly shorthand for a series of `if`s, that doesn't even save you that much typing (and IMO has worse readability). There's nothing really wrong with a bunch of `if`s when you need it. Look how it looks with regular `if`s:

```gdscript
if x > 5:
    if x is SomeClass:
        print("I'm SomeClass!")
    print("I'm over 5")

**Comment by nobuyukinyuu** [comment]
@vnen

Thanks!  Matching by class string is what I ended up doing.  It worked for my specific scenario,valthough I'm not sure this works well when looking for if a class inherits from another named one the way `is` does.  

As for whether or not using `if` in this fashion is ugly shorthand, do you mean aesthetically, syntactically, or both?  I guess beauty is in the eye of the beholder, seeing how many ways `switch`-like branching can be abused in other languages. I do like having more nesting options than what a bunch of nested `if` blocks can give me, though; in a language where indentation matters and block level isn't always easy to make out where a lot of them end in the same place, it seems like it could be helpful with some of the larger blocks to have this bit of syntactical sugar.

**Comment by vnen** [comment]
> As for whether or not using if in this fashion is ugly shorthand, do you mean aesthetically, syntactically, or both?

Both. Of course the first one is subjective. About syntax, looks like `if` with fallthrough, it just allows some rearrangement in a few cases. I feel like it can help with some constructs but most of the time it wouldn't be much of a gain (if any) over the regular `if`/`elif` blocks.

OTOH, pattern guards make much more sense and doesn't rely on implicit variable insertion, and also are more powerful than this proposal. Maybe @karroffel has an idea for this.

For instance, take this proposal:

```gdscript
#using a previously reserved keyword to signify matching patterns against true
match x:
    case is SomeClass:  
        print("I'm SomeClass!")
        continue

    #Entire expression clause must evaluate true, 
    # or use commas to match expressions other than `true` without the `case` keyword
    case > 5 and case < 10 or case == -1, SPECIAL_CASE:  
        print("I'm over 5 and maybe I'm special but sometimes I'm also negative")
```

You can do a full expression, but you can only match the whole value. With pattern guards you could match partial values. E.g. (using Haskell-like syntax for example, but could be different):

```gdscript
match my_array:
    [x, y] | x > 5 and y <= 2: print("match one condition")
           | x > 5: print("x is greater than 5 and is greater than 2")
           | else: print("x is not greater than five")
```

Which is more powerful and is a standard in languages with pattern matching.

**Comment by willvincent** [comment]
@vnen I'm not particularly familiar with Haskell, but how is your Haskell example really any different from a series of if/elif's?

```
if (x > 5 and y <= 2):
  print("Match one condition")
elif (x > 5):
  print("x is greated than 5 AND y is greated than 2)
else:
  print("x is not greated than 5")
```

Granted it may be slightly more code, but it's more readable to me.  

I don't know if it makes a difference in GDScript, but I do know that if/elif/else logic is more generally performant than switches in other languages (PHP and Javascript come to mind)

**Comment by vnen** [comment]
> I'm not particularly familiar with Haskell, but how is your Haskell example really any different from a series of if/elif's?

Well, that's my argument against the original proposal as well, it can just be done with if/elif/else.

For my example it's the same thing, unless there's an added ability to fall through the next pattern guard. Usually the `switch(true)` trick is used to avoid **nested** `if`s, so if you're not using fall through, there's no benefit.

> I don't know if it makes a difference in GDScript, but I do know that if/elif/else logic is more generally performant than switches in other languages (PHP and Javascript come to mind)

Not really, switch is usually better if you use the regular way (i.e. with constant cases). With `switch(true)` the performance is about the same. For instance, C/C++ replace the `switch` with a jump table, which is much faster than an `if` chain, but they only allow this with integers and constant cases. AFAIK it's going quite well without supporting the `switch(true)` trick.

That's why `match` requires constant patterns, because they are reduce at parse time (so it's probably faster than a series of `if`s to the same purpose). When you try to do `match true`, however, you're going against this optimization to do something that could be achieved with regular `if` chains.

**Comment by viktor-ferenczi** [comment]
Take a look at how [Go's switch statement](https://gobyexample.com/switch) works. I think defaulting the argument of match to true does make sense.

**Comment by ThibaultLemaire** [comment]
Having conditional guards in pattern matching would still be a great feature. This was originally suggested by @karroffel on #6593, and I'm surprised it hasn't found more support.

For example (I'm currently following the [Godot Game Engine Projects](https://github.com/PacktPublishing/Godot-Game-Engine-Projects) and) [the following code snippet](https://github.com/PacktPublishing/Godot-Game-Engine-Projects)

``` gdscript
func _on_Player_area_entered( area ):
	if area.is_in_group("coins"):
		area.pickup()
		emit_signal("pickup", "coin")
	if area.is_in_group("powerups"):
		area.pickup()
		emit_signal("pickup", "powerup")
	if area.is_in_group("obstacles"):
		emit_signal("hurt")
		die()
```

could be rewritten (following [karroffel's syntax suggestion](https://github.com/godotengine/godot/issues/6593#issuecomment-249258893)) as

``` gdscript
func _on_Player_area_entered( area ):
	match area:
		var coin if area.is_in_groups("coins"):
			coin.pickup()
			emit_signal("pickup", "coin")
		var powerup if area.is_in_groups("powerups"):
			powerup.pickup()
			emit_signal("pickup", "powerup")
		_ if area.is_in_groups("obstacles"):
			emit_signal("hurt")
			die()
```

Pay attention to how local variable assignment could be used to add meaning.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
