### ISSUE TITLE
Add possibility to create concave shapes in TileSet Dock

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#18197]
**Godot version:**
e7445c3d82b60eae2d02e201d21990f0aac096ae

**Issue description:**
Tile Set dock doesn't support create concave shapes like this:

![2018-04-14-105651_500x422_scrot](https://user-images.githubusercontent.com/1387165/38769027-8d8b48a2-3fd2-11e8-964f-4f00f267c322.png)

When I play the scene, the physics doesn't work properly.

We can only create if we made manually in a scene and converting to tileset.

Don't know if this is a feature request or a bug. Not related with this issue #17789 that was fixed in this pr #18144.

**Minimal reproduction project:**
[tileset_concave_test_v2.zip](https://github.com/godotengine/godot/files/1910441/tileset_concave_test_v2.zip)

**Comment by reduz** [comment]
@MarianoGnu does this work now?

**Comment by akien-mga** [comment]
@guilhermefelipecgs Is this feature still missing?

**Comment by guilhermefelipecgs** [comment]
I updated the project in the description.
![peek 22-01-2019 09-27](https://user-images.githubusercontent.com/1387165/51532730-0bfa7800-1e28-11e9-9f56-6b0784272485.gif)

**Comment by MarianoGnu** [comment]
This should be fixed now, there's a button to toggle convex/concave shapes. And also a workaround was made to have that wind of shapes working with convex shapes (they are split into several convex shapes) Please reopen the issue if it doesn't work, or open a new one referencing this.

**Comment by guilhermefelipecgs** [comment]
@MarianoGnu It's working pretty well now, Thanks :+1:
