### ISSUE TITLE
Remove godot.* if not in use from the final apk (Android)

### ISSUE THREAD

**Issue by megasoft78** [godotengine/godot#18192]
Hi,
I notice that on Godot 2.1.5 when I export the final apk of my game I get in the AndroidManifest.xml a lot of these:
```
<uses-permission
        android:name="godot.ACCESS_CHECKIN_PROPERTIES" />

```
It seems Godot use them as placeholder and replace them with the right permissions during the export.

Even if that's fine because those permissions don't exist when I upload on Google Play Console they are detected anyway and it's difficult to spot which permissions has my apk.

How easy it would be to remove them when not in use?
I already spot the specific part of the code (export.cpp function _fix_manifest) to detect the one to remove but I'm not sure how to remove them.

@xsellier Any idea?

**Comment by xsellier** [comment]
This is related to:
https://github.com/godotengine/godot/issues/1813

Those permissions are placeholders, even if they are included in the final APK, android ignore them.

**Comment by volzhs** [comment]
yeah, user won't see those permissions but...
I saw this kind of issue somewhere which was about google complains APK requiring these many unknown permissions.
it could be a problem later.
the best way to solve this for now is removing or commenting out those unused permissions in `platform/android/AndroidManifest.xml.template` file and compile android templates.

**Comment by megasoft78** [comment]
@volzhs Yes that's my current solution. :)

**Comment by akien-mga** [comment]
If there's logic in the exporter to replace those placeholders with actual Android permissions, I guess we could add some logic to remove the unused placeholders at the same time?

FWIW, Google Play doesn't display those permissions but F-Droid does, and it looks bad: https://f-droid.org/en/packages/io.github.kobuge.games.minilens/

**Comment by volzhs** [comment]
@akien-mga I had tried it before and I found that we need to read the whole manifest.xml file and rewrite it.
certain xml node in manifest.xml can't be easily just removed.

**Comment by megasoft78** [comment]
@volzhs  Not sure this can help:
http://www.olafdietsche.de/2015/05/11/exploring-android-binary-xml-file-format

**Comment by marionauta** [comment]
My game was removed from Play Store because it "collects user data" without a privacy policy. The only way Google would think I may be collecting user data is because of the permissions in the `AndroidManifest.xml`, so I think it is **very important to remove** this placeholder permissions, so this doesn't happen to more people.

**Comment by 2dvision** [comment]
I use [Apktool](https://ibotpeaches.github.io/Apktool/) in godot 2.1.4 stable.

1. Decode ‫‪**android_release.apk**‬‬
2. Remove unnecessary permission in ‫‪**AndroidManifest.xml‬‬**
3. build **android_release.apk‬‬** again.

**Comment by marionauta** [comment]
Thank you @gerardogc2378 , I'm going to do this. The thing is, I shouldn't need to add that link as I have more apps without privacy policy that weren't affected.

The game was taken down after a human review and I'm sure that person saw the list of placeholder permissions, and thought they were the real permissions.

**Comment by freemanfromgodotengine** [comment]
Yes, @gerardogc2378 is right, @marionauta . My apps were removed too. The fast "solution" was to create simple text of "Privacy Policy" and publish it on the web. Helped at least for now ;)

**Comment by alglez** [comment]
I'm experiencing the same problem as well, and I'm neither collecting or transmitting data. I'm not an expert, and actually looking to upload my app again. The main problem I see when people are using a link as a way to provide privacy policy is that for google that shouldn't be enough as:

"Sign in to your Play Console and be sure to include a link to a valid privacy policy on your app's Store Listing page and **within your app**"

and in this [link](https://play.google.com/about/privacy-security-deception/personal-sensitive/), under  **Your in-app disclosure:** there is more information about how the privacy policy must be withing the app. 

So as far as I understand It's necessary to modify the app as well as provide a link to a "privacy policy"

**Comment by guilhermefelipecgs** [comment]
My app was banned too. :(
And this was they said:

![captura de tela de 2018-05-21 21-59-07](https://user-images.githubusercontent.com/1387165/40336834-4a777bf2-5d42-11e8-8041-216a5fcfe06e.png)

**Comment by lukaskotik** [comment]
My app was removed from Play store too. The google developer support insists on that "godot.CAMERA" etc. request sensitive data... They ignore my claims that "godot._" are only placeholders.
Publishing "Privacy policy" and linking it to apps that do not request any permission seems to me as ugly workaround.

**Comment by guilhermefelipecgs** [comment]
@lukaskotik You can do what @2dvision suggested.
> I use Apktool in godot 2.1.4 stable.
> 
>     Decode ‫‪android_release.apk‬‬
>     Remove unnecessary permission in ‫‪AndroidManifest.xml‬‬
>     build android_release.apk‬‬ again.
But remember to use zipalign and apksigner after rebuild your apk.
https://developer.android.com/studio/publish/app-signing?#sign-manually

**Comment by akien-mga** [comment]
This seems to be causing an Androidocalypse now (Google recent removals are likely related to global GDPR-induced privacy improvements) as per godotengine/godot-website#56.

Anyone able to provide a good fix for me to include in 2.1.5 in the coming days would be hero of the week :)

**Comment by reduz** [comment]
@TMM is working on a fix, guess we'll have to release a new 2.1 build soon

**Comment by reduz** [comment]
I also contacted Google btw to see if there is anything that can be done

**Comment by reduz** [comment]
Here is a link explaining how to fix the problem:

https://godotengine.org/article/fixing-godot-games-published-google-play

**Comment by akien-mga** [comment]
And here's a cross-platform tool to let you fix your existing APKs without having to re-export with a modified one: https://godotengine.org/article/godot-apk-fixer-tool

**Comment by reduz** [comment]
@hpvb already fixed this issue, so closing
