### ISSUE TITLE
The friction property is name collision_friction in TileMap

### ISSUE THREAD

**Issue by Chais** [godotengine/godot#18190]
**Godot version:**
master (3a5b25d5b  as of writing this)

**OS/device including version:**
Linux 4.15.15

**Issue description:**
The `friction` property is named `collision_friction` in the `TileMap` class. But only there. `RigidBody2D` and `StaticBody2D` for example just use `friction`. This necessitates unsightly constructions like this:

```
var friction = 0.8
if collision:
	if collision.collider.name == "TileMap":
		friction = collision.collider.collision_friction
	else:
		friction = collision.collider.friction
```

Or any other method of determining the type of the collider.

**Comment by akien-mga** [comment]
This is now kept track of in #16863, so closing.
