### ISSUE TITLE
Meshes without index array spam errors

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#18201]
**Godot version:**

3.0.2

**OS/device including version:**

Win 7 x64 bit
Radeon 6630M

**Issue description:**

Getting spammed with  drivers\gles3\rasterizer_storage_gles3.cpp:3265 - Condition ' surface->index_array_len == 0 ' is true. returned: PoolVector<uint8_t>()

I tracked it down to https://github.com/godotengine/godot/blob/e7445c3d82b60eae2d02e201d21990f0aac096ae/drivers/gles3/rasterizer_storage_gles3.cpp#L3266

(I use procedural meshes and then use node.create_convex_collision() to make collisions. Everything works ok but I get spammed with 200+ errors on game start :( )

**Steps to reproduce:**
Add a Mesh Instance node containing a Quad Mesh, add a script that does node.create_convex_collision() or node.create_debug_tangents()

**Minimal reproduction project:**

If really needed, I could add one tomorrow, but given it reproduces easily, well...

**Comment by Zireael07** [comment]
Note: the collision works, it's even displayed in when collision display is on, the only problem is that the error message shows up. (So I don't think it's a rendering problem - the function works so maybe downgrade the message from error to warning?)

**Comment by Zireael07** [comment]
Ok, I take that back - the error is spammed also during game, probably when rendering quads. It's the reason I have a persistent stutter every few seconds (every time the error gets spammed).

I hadn't noticed it earlier because I wasn't looking at the output during gameplay, just during set up.

So even more reason to muzzle this, the functions work, the quads are displayed properly, it's just an annoyance.

**Comment by Banderi** [comment]
Yeah, getting this too. I understand why it was made to warn you, but it'd be better if the error is only thrown when indexes are actively used, rather than in geometry that is only using vertex data directly, and works 100% fine for both mesh rendering, collision, etc.

**Comment by aaronfranke** [comment]
As mentioned [here](https://github.com/godotengine/godot/issues/19047), this issue goes away if `SurfaceTool.index()` is called.

Perhaps it would be best if `SurfaceTool.commit()` also called `.index()`?
