### ISSUE TITLE
Improving the node connections in the graph editors

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#18200]
**Godot version:**

any

**Issue description:**
I used the shader graph editor today in 2.14 and realized a few things that need some improvement.
I am a blender user and I expect similar features like cutting the connection with knife and automatic movement when node is added in between nodes. Also auto connection when node is overlapping the line.

I don't know when does the shader graph come back but I would like to see some improvement.  

This is an blender addon that adds more features to the node editor, this may be too much but few of the features are enough to make the shader graph nicer. It is late and I may add more details later. 
http://gregzaal.github.io/node-wrangler/

**Comment by akien-mga** [comment]
Indeed, this changed a lot in recent years. This should have been moved to a more detailed proposal years ago, it seems like we missed it. So we can close, and if more improvements are needed on top of what's now in 4.3, they can be requested in https://github.com/godotengine/godot-proposals.
