### ISSUE TITLE
The editor 2D doesn't let you to fully scroll to the right of a tilemap

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#18202]
**Godot version:**

Godot master https://github.com/godotengine/godot/commit/e7445c3d82b60eae2d02e201d21990f0aac096ae

**OS/device including version:**

Win 10

**Issue description:**

The editor 2D doesn't let you scroll to the right of a tilemap even though there's still more tilemap.

**Steps to reproduce:**
![https://i.imgur.com/rcOi9Vn.gifv](https://i.imgur.com/rcOi9Vn.gif)

**Comment by Zylann** [comment]
Similar to https://github.com/godotengine/godot/issues/5736
