### ISSUE TITLE
Build failure on iOS

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#18205]
**Godot version:** Git https://github.com/godotengine/godot/commit/eac2863c25a4c01d99f3af3aa45e1eaa444a1f5f

**OS/device including version:** macOS on Travis CI

**Issue description:** Building an iOS export template fails with the following error:

```
platform/iphone/gl_view.mm:84:10:{84:3-84:9}{84:12-84:38}: error: no viable overloaded '=' [2]
                insets = [_instance safeAreaInsets];
                 ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//System/Library/Frameworks/UIKit.framework/Headers/UIGeometry.h:15:16: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'id' to 'const UIEdgeInsets' for 1st argument [2]
 typedef struct UIEdgeInsets {
                ^
1 error generated.
scons: *** [platform/iphone/gl_view.iphone.opt.debug.arm64.o] Error 1
scons: building terminated because of errors.
```

[Full build log on Travis CI](https://travis-ci.org/Calinou/godot-builds-ci/jobs/366364422)

**Steps to reproduce:** Compile an iOS export template from macOS.

**Comment by bruvzg** [comment]
Check https://github.com/godotengine/godot/pull/18106#issuecomment-380082058, Travis uses outdated Xcode by default (8.3), iPhone X support requires iOS SDK 11.0+ (Xcode 9+).

**Comment by akien-mga** [comment]
I've already configured Travis here to use Xcode 9.3: 040e9eca

So you just need to do the same in your own Travis script.
