### ISSUE TITLE
Animation switch "continuous/discrete" doesn't work

### ISSUE THREAD

**Issue by ValSergeev** [godotengine/godot#1821]
*Bugsquad edit:* Initially seen on 1.1rc2 win32/64

Can't switch animation type when trying to setup a new animation

![continuous_bug](https://cloud.githubusercontent.com/assets/2426313/7478886/0e889140-f35e-11e4-8063-b3b6656cb2b0.gif)

**Comment by Ace-Dragon** [comment]
I can confirm it on Windows, only my version of Godot defaults new animations to *Continuous* and you can't change the movement type to "Discrete".

The continuous mode is what is usually used in 3D so it doesn't affect me so much at the time being, but I can see where the other can be useful.

**Comment by frederico4d** [comment]
Same thing here on ubuntu 14.04

**Comment by captainwasabi** [comment]
Interesting, I have the opposite problem.  It seems stuck on discrete.

Verified it on Win7 and Win8.1

**Comment by akien-mga** [comment]
I haven't seen this recently, so I'll assume it has been fixed. Feel free to notify me if you can still reproduce it.
