### ISSUE TITLE
No sound when chorus effect added

### ISSUE THREAD

**Issue by ibenx** [godotengine/godot#18217]
**Godot version:**
Build from master branch ([last commit](https://github.com/godotengine/godot/commit/7b5703bc41460c5c8b955f879190625da85a2a81))

**OS/device including version:**
Ubuntu 14.04

**Issue description:**
No sound when chorus effect added

**Steps to reproduce:**

1. Create new scene
2. Add AudioStreamPlayer
3. Fill stream with audio file
4. Go to audio busses tab
5. Add chorus effect in master bus
6. Play

**Comment by YeldhamDev** [comment]
Can't reproduce with Manjaro Linux.

**Comment by marcelofg55** [comment]
I couldn't reproduce this either on OS X. I guess maybe this was fixed?

**Comment by reduz** [comment]
Can't reproduce it either, I assume fixed
