### ISSUE TITLE
GDScript comment doesn't escape quotation mark and apostrophe

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#18214]
**Godot version:** Master

**Issue description:**
GDScript comment doesn't escape quotation mark and apostrophes

**Steps to reproduce:**
Just write `# '` or `# "` in a GDScript

**Comment by volzhs** [comment]
are you talking about #17983?

**Comment by Noshyaar** [comment]
I don't understand this issue. Everything is working as expected so far.

**Comment by AndreaCatania** [comment]
@volzhs yes it's the same issue. Thanks you!
