### ISSUE TITLE
ColorN() can cause game to crash before SceneTree.quit() completes.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#18216]
Running this in 2.1.4 and 2.1.5 for Windows.

To reproduce this, you need a scene running in game that has a GDScript where one of the script scope variables request a ColorN() Color.  

Export the project and run it.  When exiting it will crash before closing.  This only happens in the exported .exe.

```
extends Node2D

var color = ColorN("white")
```

Color8() appears to be fine, and Godot 3.0.2 doesn't have this issue, but depending on the issue maybe it manifests itself in some other way.  Is the string argument passed in leaking in some way?

Attached a sample project, just export it, run it, and quit it.

[ColorN Crash.zip](https://github.com/godotengine/godot/files/1913109/ColorN.Crash.zip)

**Comment by akien-mga** [comment]
CC @bojidar-bg

**Comment by bojidar-bg** [comment]
TBH, I have no idea what might cause this, but I'll try to give it a check at some point in time...

Probably it is related to the allocation of the hashmap mapping name -> color though.

**Comment by akien-mga** [comment]
Fixed by #20239.
