### ISSUE TITLE
Corrupt exported Android APK when project files include non-ASCII (accented) characters like ñ

### ISSUE THREAD

**Issue by seyacat** [godotengine/godot#18222]
**Godot version:**

3.0.2

**OS/device including version:**

can reply in all os

**Issue description:**

when compile project, apk not run on any device, apk looks corrupt because its not possible to sign externally

adb install paratrooper.apk 
paratrooper.apk: 1 file pushed. 4.8 MB/s (23578106 bytes in 4.644s)
	pkg: /data/local/tmp/paratrooper.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

**Steps to reproduce:**
download project, try to compile and run apk

**Minimal reproduction project:**

can found project here
http://seyanim.com/apks/gdproject.zip

**Comment by eon-s** [comment]
JDK version?

**Comment by seyacat** [comment]
1.8

**Comment by seyacat** [comment]
I can solve the problem.
Innitialy i think its on custom font, but no
the problem its on filename, i have filenames with "ñ" and font name has "-"
remove this characters on filename solve the problem

**Comment by volzhs** [comment]
this issue raised multiple times from time to time.
probably we need to check file names when exporting android.

**Comment by seyacat** [comment]
You can put non valid  filename alert on debug messages? it solves problem on all cases.

**Comment by Calinou** [comment]
@seyacat Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by volzhs** [comment]
I can't tell but i guess it has still a problem with non-ascii file or directory name for android platform.

**Comment by eon-s** [comment]
Recently an user had this problem with spaces in names so I guess it still an issue, the export window may need to disable exports if this kind of requirements are not met (also the same happened to me for iOS exports with spaces on project's folder name).

**Comment by akien-mga** [comment]
This is indeed still reproducible with the attached project in the OP. Here's the error I get:
```
Installing to device (please wait...): Xiaomi POCOPHONE F1
Performing Streamed Install
adb: failed to install /home/akien/.cache/godot/tmpexport.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1797285048.tmp/base.apk: File assets/Sprites/Cañon3.png.import in manifest does not exist]
```

**Comment by akien-mga** [comment]
CC @m4gr3d @pouleyKetchoupp

**Comment by m4gr3d** [comment]
This seems to be an issue with the zipping tool on the host OS. I exported the project as a zip file, and when trying to unzip I get the following error messages:
```
error:  cannot create .import/Ca+?on1.png-78b071cf1a548edcd5c4c2799a79ed1f.stex
        Illegal byte sequence
error:  cannot create Sprites/Ca+?on1.png.import
        Illegal byte sequence
error:  cannot create .import/Ca+?on2.png-9b8bd2cc1071124e39b7bf9a1386dde1.stex
        Illegal byte sequence
error:  cannot create Sprites/Ca+?on2.png.import
        Illegal byte sequence
error:  cannot create .import/Ca+?on3.png-be72c9b05c9f4ea4bc3b923c6350550e.stex
        Illegal byte sequence
error:  cannot create Sprites/Ca+?on3.png.import
        Illegal byte sequence
error:  cannot create .import/Ca+?on4.png-d86f1966755172217d798194ae63e344.stex
        Illegal byte sequence
error:  cannot create Sprites/Ca+?on4.png.import
        Illegal byte sequence
error:  cannot create .import/Ca+?on5.png-ff149dc6a2827f2b8ec439e699af7681.stex
        Illegal byte sequence
error:  cannot create Sprites/Ca+?on5.png.import
        Illegal byte sequence
```

However when I try to run the project as a pack file, instead of using the regular load process, the Godot engine is able to see and index all the assets:

```
2020-07-27 23:35:50.007 17660-17755/? I/godot: FHK - Adding path res://Sprites/Cañon1.png.import with size 659
2020-07-27 23:35:50.007 17660-17755/? I/godot: FHK - Adding path res://Sprites/Cañon2.png.import with size 659
2020-07-27 23:35:50.007 17660-17755/? I/godot: FHK - Adding path res://Sprites/Cañon3.png.import with size 659
2020-07-27 23:35:50.008 17660-17755/? I/godot: FHK - Adding path res://Sprites/Cañon4.png.import with size 659
2020-07-27 23:35:50.008 17660-17755/? I/godot: FHK - Adding path res://Sprites/Cañon5.png.import with size 659
```

So the solution for this issue should be https://github.com/godotengine/godot-proposals/issues/946 and https://github.com/godotengine/godot-proposals/issues/947

**Comment by pouleyKetchoupp** [comment]
Apart from solving the issue itself, we're only getting minimal error info in the editor's log:
```
Performing Push Install
C:\Users\[user]\AppData\Local\Temp/Godot/tmpexport.apk: 1 file pushed, 0 skipped. 6.9 MB/s (22365020 bytes in 3.078s)
        pkg: /data/local/tmp/tmpexport.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
```

Maybe we could add extra flags to show error details that can help with debugging?
