### ISSUE TITLE
image error keeps occurring when moving mouse around sprite

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#18229]
**Godot version:**

3.1.dev 1d15c5d72

**OS/device including version:**

**Issue description:**

following error keeps occurring when moving mouse around sprite.
sprite uses region_rect.
```
core/image.cpp:1892 - Index p_x=150 out of size (width=128)
```

**Steps to reproduce:**
1. add sprite
2. assgin texture to it
3. turn on Region > Enabled on inspector
4. define rect size larger than texture at Region > Rect
5. move mouse around sprite

![image_error](https://user-images.githubusercontent.com/8281454/38804930-0cb9f726-41af-11e8-83f8-fdef39f3b9f7.gif)

**Minimal reproduction project:**

[Image error.zip](https://github.com/godotengine/godot/files/1914919/Image.error.zip)

**Comment by ByTheQuietLake** [comment]
Hello, the error is back now when you hover the mouse over the image in select mode , in the console/output it reads as 
Error: Image::get_pixel: Index p_x="value" out of size <width="value">
At: core\image.cpp:1950
