### ISSUE TITLE
Default world environment not great for character editing in 3D

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#18226]
**Godot version:**

3.x (tip)

**OS/device including version:**

Linux

**Issue description:**

Opening a DAE of a character model in godot, the default world environment is not great. More neutral colour or lighting would be great. Adding a WorldEnvironment and an Environment and a directional light and having to tweak it is a hassle.

[Imgur](https://i.imgur.com/ksfMtgc.png)

**Steps to reproduce:**
Open a DAE (or scn created from a a DAE) in the editor.

**Minimal reproduction project:**

**Comment by DEF7** [comment]
Agreed, having the blue cast over everything when just trying to work on an isolated scene (like a game object or unit, etc) just adds an extra step. One idea would be to allow customization of the default values used.

**Comment by Zylann** [comment]
There used to be a default light for this (https://github.com/godotengine/godot/issues/10451) so that we could design individual scenes, without polluting them all with a new light node, but it was closed in favour of adding a node yourself with "editor only" checked... as far as I know?

**Comment by Zireael07** [comment]
Default environment itself can be changed easily, yeah.

**Comment by DEF7** [comment]
Ah, there's also the ability to define a default project environment via
Project->Project Settings->Rendering->Environment

**Comment by eon-s** [comment]
Double click on the default environment resource at filesystem dock and it will open in the inspector for editing, but better defaults will be good to have (lower sky contribution and probably a pale yellow light), especially for the first impression it gives to users.
