### ISSUE TITLE
Some ideas on HttpRequest node

### ISSUE THREAD

**Issue by Tim-MCC** [godotengine/godot#18232]
Adding options to inspector & suggesting some extra fields 

![untitled-2](https://user-images.githubusercontent.com/13506293/38812174-d8875566-418b-11e8-9a37-5e6a02e4c3b4.gif)

Some abstract ideas

![untitled](https://user-images.githubusercontent.com/13506293/38812182-e0b50878-418b-11e8-91fb-7e203f3df347.png)

More Signals:

on_error
while_requesting

**Comment by Vaiktorg** [comment]
I have an abstracted version of httpRequest and httpClient if u need it lol

**Comment by akien-mga** [comment]
Not sure why this was closed, but CC @Faless @mhilbrunner in case there are useful ideas to implement.

**Comment by Timberland-7** [comment]
@akien-mga closed it as there was no reaction for long except one dude trolling

**Comment by mhilbrunner** [comment]
@Timberland-7 will have a look. I'll reopen for now if you don't mind :)

**Comment by akien-mga** [comment]
This should likely be reopened as a detailed proposal on https://github.com/godotengine/godot-proposals so that it's more actionable and stays on the Networking team's radar.
