### ISSUE TITLE
Allow writing custom values to the depth buffer from a fragment shader

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#18231]
I'd like to propose writing custom values to the depth buffer from a fragment shader.
In GLSL, you can write to `gl_FragDepth` to put custom values in the depth buffer, but this functionality seems to be missing in Godot's shader language.

This would enable stuff like sphere impostors which draw a sphere that correctly intersects with other objects, using only 2 triangles and by writing custom values to the depth buffer. See this OpenGL tutorial: [Chapter 13. Lies and Impostors](https://paroj.github.io/gltut/Illumination/Tut13%20Deceit%20in%20Depth.html)
![Sphere Impostor](https://paroj.github.io/gltut/Illumination/Depth%20Correct%20Impostor.png)

It also allows deep parallax to have correct intersection with other objects in the scene, and probably a lot of other effects I'm not aware of.

**Comment by antoniotorresm** [comment]
Added in #22800
