### ISSUE TITLE
Navigator grouping

### ISSUE THREAD

**Issue by ToxicCrack** [godotengine/godot#18249]
It would be nice to group several nodes in the navigator / scene outliner together for better organisation. This is especially useful if you have a YSort root node, because you can't group the nodes in an subnode. YSort wouldn't work in that case.

**Comment by ToxicCrack** [comment]
Nevermind. I got an working solution / workaround. I simply create Node2D's as a grouping node and set an group to it ("ysort_group" in that case). In ready() i search for all of the nodes in that group, get the children and move them to the parent ysort. It even works with instanced scenes. Here is my code:

```
func _ready():
  for ysortGroupParent in get_tree().get_nodes_in_group("ysort_group"):
    for node in ysortGroupParent.get_children():
      ysortGroupParent.remove_child(node)
      node.position = node.position + ysortGroupParent.position
      ysortGroupParent.get_node("..").add_child(node)
    ysortGroupParent.queue_free()
```
And that's how the nodes are organized:

- YSort
  - NodeX
  - NodeY
  - Container (Group: ysort_group)
    - OrganizedNode1
    - OrganizedNode2
    - OrganizedNode3

**Comment by Calinou** [comment]
Closing per the above comment. If you still need additional features, please open a proposal on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.
