### ISSUE TITLE
Repeated results in autocomplete for GDScript.

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#1824]
![captura de tela de 2015-05-05 19 23 27](https://cloud.githubusercontent.com/assets/1387165/7484197/6125a462-f35c-11e4-967c-3ab806f43790.png)

**Comment by akien-mga** [comment]
I can confirm this bug in the current master branch, at least for InputEvents. If it does not affect other classes, I think this might be due to the versatile nature of InputEvents (InputEvent.Key, InputEvent.Mouse, etc.)
