### ISSUE TITLE
Overridden instance property loses overridden status if scene property is changed to matching value

### ISSUE THREAD

**Issue by AlanLynn** [godotengine/godot#18241]
**Godot version:** v3.02.stable.official

**OS/device including version:** Windows 10 64-bit

**Issue description:**
Expected behavior: Overridden instance properties remain overridden until the reset button is pressed.
Actual behavior: Changing a scene property to the same value as an overridden instance property causes the instance property to no longer be considered overridden.

**Steps to reproduce:**
1. Load the project from below. Scene 'label' is a label with Text set to "scene-value". Scene 'main' contains 3 instances of 'label'. Label3 has Text set to "override-value".
2. Open label.tscn and change Text to "override-value".
3. Save the scene.
4. View scene 'main'. Notice that Label3 no longer has a reset button for its Text property.
5. Switch back to scene 'label'.
6. Change Text to "scene-value".
7. Save the scene.
8. View scene 'main'. All labels now have Text set to "scene-value".

**Minimal reproduction project:**
[Instance Properties Bug.zip](https://github.com/godotengine/godot/files/1917495/Instance.Properties.Bug.zip)

**Comment by akien-mga** [comment]
This is described more in-depth in this proposal, so I'll close this issue to keep discussion focused there: https://github.com/godotengine/godot-proposals/issues/2280
