### ISSUE TITLE
2DEditor: can't scroll past 2x viewport size when zoomed in to a certain level

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#18254]
**Godot/OS version:**

e44444e Antergos x86_64

**Issue description:**

Expected: viewport to zoom in directly where mouse cursor is
Happened: you can't go past 2x viewport size (eg. if window size = 1024x800, you can't go beyond 2048x1600) when zoomed in

**Steps to reproduce:**
1. optional - add a Sprite with texture larger than 2x viewport size.
2. try to zoom in to see the texture outside beyond the mentioned area

cc: @groud  :D
I think it's a "feature" but quite problematic when I want to see shader result of large textures.

**Comment by groud** [comment]
Looks like this is closed on master. Can you confirm ?

**Comment by Noshyaar** [comment]
i don't care anymore

**Comment by akien-mga** [comment]
We do. But closing as fixed as per @groud's comment.
