### ISSUE TITLE
Add duplicate option for root node(s)

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#18263]
Currently, trying to duplicate the root node yields a "this can't be done for the root node" error.
The thinking probably is/was that there can of course only be one route.

But it still would be useful to be able to duplicate the root node and have the duplicate added as a new child in some cases.

Example:

I just used a RichTextLabel as a root, configured it (fonts, sizes, colors, ...).
Then I wanted the exact same settings on a new RichTextLabel as a child.
I tried duplicating... but of course that doesn't work. :)

**Comment by volzhs** [comment]
probably #13309 would solve this.

**Comment by mhilbrunner** [comment]
yeah, copy/paste would be great

**Comment by akien-mga** [comment]
> I just used a RichTextLabel as a root, configured it (fonts, sizes, colors, ...).
Then I wanted the exact same settings on a new RichTextLabel as a child.
I tried duplicating... but of course that doesn't work. :)

I don't think that's a good example, as it's not a particularly good scene design to have a `RichTextLabel` as root node and another one as child node. You'd typically want to have a `Control` or `Panel` as root node, and the two `RichTextLabel`s as siblings and children of the root node.

And for this scenario, you'd use "Make Scene Root" on the Control that you want to become the new root, which automatically makes the old root its sibling. It still requires you to create the new root first as a sibling, but IMO it's not a big deal. An alternative would be to add an "Insert root node" option on the right click menu for the root node, which would let you select a new node type to add as the new root.

That being said, the feature to duplicate a root node as a sibling is not necessarily a bad idea. But it would be good to have more actual use cases to discuss whether it makes sense. In particular, duplicating a node also duplicates all its children, so duplicating the root node as a sibling in a node where there are already children would create a nested duplicated scene in the scene. I don't see it being very useful.

**Comment by mhilbrunner** [comment]
Closing this in favor of actual copy/paste support. :)

**Comment by hak33m16** [comment]
Following the trail of PRs, looks like they were closed this is still an issue in Godot 4.2

I used my root node for something that I later realized I wanted to be a child element of that scene. Perhaps we should create another issue?
