### ISSUE TITLE
AnimatedSprite.animation shall complain wrong animation name

### ISSUE THREAD

**Issue by snake3276120** [godotengine/godot#18264]
**Godot version:**
3.0.2

**OS/device including version:**
Win 10, but it should be general

**Issue description:**
For now, when assigning the AnimatedSprite.animation in GDScript to a wrong name, the output won't complain but instead hides the node from displaying during the game. It will be convenient to add an error checking mechanism.

**Steps to reproduce:**
One can simply use the "Dodge the Creep" project, either Mob or Player node. In the script, let AnimatedSprite.animation = a wrong name comparing to what you wrote when editing the animation in the Godot editor.

**Comment by mateusfccp** [comment]
I started to work on this one, I got do make it verify if the animation exists, but I couldn't find a way to throw the error. Any hints? @akien-mga

**Comment by mateusfccp** [comment]
I've managed to emit an error with `ERR_FAIL_COND` and other error macros, but it doesn't show to the end user. I can't find a simple way to show it to the user.

**Comment by akien-mga** [comment]
Fixed by #24489.
