### ISSUE TITLE
Game stutters each time new material appears on camera

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#18265]
59b8166 Antergos x86_64 
```
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Haswell

$ lspci
00:02.0 VGA compatible controller: Intel Corporation 4th Generation Core Processor Family Integrated Graphics Controller (rev 06)
01:00.0 3D controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev a1)
```

**Issue description:**

Expected: camera to rotate smoothly
Happened: Game stutters each time new material appears on camera (only for the first time)

GIF recording is kinda misleading. Video here: https://youtu.be/EKV-0EJcJUM as you can see the 2nd time the camera rotates it's smoother.

(Number shown is frame count, not frame rate :P)

![peek 2018-04-18 11-15](https://user-images.githubusercontent.com/26753932/38911562-689d56e0-42fa-11e8-8f38-d3ccd4706a02.gif)

**Steps to reproduce:**
1. add several MeshInstances with QuadMesh
2. assign a unique ShaderMaterial for each one
3. change the view so that it appears on screen one at a time

**Minimal reproduction project:**

[issue.zip](https://github.com/godotengine/godot/files/1922425/issue.zip)

Edit: how it looks in the profiler. It takes roughly a second to render that frame.
![image](https://user-images.githubusercontent.com/26753932/38911814-e4e60912-42fb-11e8-8701-09668b0317de.png)

**Comment by DEF7** [comment]
This also happens with particle systems when they first spawn, I imagine for the same or similar reasons. Isn't this perfectly fixable with preload() called in _ready()? Or will Godot only actually load/compile a material's shader when it actually is expected to use it for rendering? I can see this making more sense in a large game where it needs to unload/reload textures/shaders dynamically, but only if it were to do so quietly and smoothly in a threaded fashion without blocking the main update cycle.

**Comment by Zireael07** [comment]
Particle systems are mentioned in the linked issue, #17263

**Comment by Noshyaar** [comment]
Duplicate of #13954
