### ISSUE TITLE
Importing/exporting (merging) Input Maps

### ISSUE THREAD

**Issue by TheRadMatt** [godotengine/godot#18274]
I find it extremly inconvinient to make new inputs in _Input Map_ in every project when you import f.e. first person character. At this moment (as far as I know) you need to see the button mapping in a script and then recreate them in the Input Map tab. It would be much easier to just import a file with input actions and merge the new ones with the existing ones (or replace them) - just like it works with tilesets.

**Comment by Hinsbart** [comment]
> At this moment (as far as I know) you need to see the button mapping in a script and then recreate them in the Input Map tab.

You can also just copy & paste the mappings from/to the `godot.project` files.

**Comment by TheRadMatt** [comment]
Yes, I know of this solution but it really seems like there should be a more user friendly way.
