### ISSUE TITLE
if button is pressed, emit the signal 

### ISSUE THREAD

**Issue by dneild** [godotengine/godot#18278]
**Godot version:**

Godot 3.0 windows 64

**Issue description:**
hi, I have a problem with signals. I want to emit a signal 
![game](https://user-images.githubusercontent.com/33464119/38951831-ca1a778c-4317-11e8-9fe6-ade5aba323d8.png)
when the button is pressed, but it says method not found.

**Steps to reproduce:**
func _on_Spring_pressed():
        

emit_signal("switch1")

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
This looks like a bug in your project (you connected the signal to a non existing method), not a Godot bug.

**Comment by dneild** [comment]
thanks, I accidentally connect the signal to a node that I have deleted
