### ISSUE TITLE
Regression: It's impossible to scale mesh in billboard mode

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#18292]
**Godot version:**
3.0.2

**OS/device including version:**
Ubuntu 16.04, GTX1060

**Issue description:**
It's impossible to scale any Mesh/Sprite3D in billboard mode. This feature is often used in a many graphic effects. It was working fine in 2.1.3

**Steps to reproduce:**
1. Create new Scene
2. Add mesh instance to scene, create new QuadMesh inside `mesh` property
3. Create new spatial material 
4. In material parameters set billboard mode to enabled
5. Try to  scale mesh instance. 

**Minimal reproduction project:**
[BillboardScale.zip](https://github.com/godotengine/godot/files/1927906/BillboardScale.zip)

**Comment by kubecz3k** [comment]
Further notes: 
- It seems it works fine in `Particle Billboard` mode.  (but only x is taken into account and the scale is uniform not sure but maybe this is how particle mode should work) 
- In `Y only` billboard mode only the Y scale is used.

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/9a759750421bc72ed41c1dc67c0fa9b5564b8abc.

Do you know on which commit the regression occured?

**Comment by kubecz3k** [comment]
@Calinou I think it happen during the graphic engine rewrite between v2 and v3, but don't know the specific commit.

**Comment by JFonS** [comment]
I've working on this issue and so far my fix seems to work, it should add support for #18298 too. Once I have time to clean the code and fully test my fix I will make a PR.

**Comment by kubecz3k** [comment]
@JFonS Cool to hear, thank you!

**Comment by Calinou** [comment]
This was fixed by https://github.com/godotengine/godot/pull/18365 a while ago, closing.

**Comment by unfa** [comment]
I'm glad there's a workaround with the "Particle Billboard" mode...
