### ISSUE TITLE
HTTPRequest.request returning OK on getaddrinfo failure

### ISSUE THREAD

**Issue by KennethWilke** [godotengine/godot#18297]
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
Ubuntu 16.04.4

**Issue description:**
Expected `request()` method to return non-zero value, probably `RESULT_CANT_RESOLVE`

**Steps to reproduce:**

Call HTTPRequest.request() with an invalid hostname, ie:
```
extends Node

func _ready():
	print($HTTPRequest.request("http://thisaintnodomain"))
```

**Minimal reproduction project:**
[HTTPRequestError.zip](https://github.com/godotengine/godot/files/1929215/HTTPRequestError.zip)

**Comment by KennethWilke** [comment]
nvm i'm a dummy, the error code i expect is returned in the signal. though now i don't understand what the int returned by the request method indicates

**Comment by Noshyaar** [comment]
This is a bug.
```
ERROR: _resolve_hostname: getaddrinfo failed!
   At: drivers/unix/ip_unix.cpp:108.
```
