### ISSUE TITLE
Ability to rotate Sprite3D / Mesh instances in billboard mode

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#18296]
**Godot version:**
3.0.2

**OS/device including version:**
Ubuntu 17.04 Gtx1060

**Issue description:**
It seems there is no way to rotate Sprite3D in billboard mode. Rotation X/Y/Z don't do anything in such case. Not sure how implementation should work, but I see two ways: 
 - new property inside Sprite 3D
 - just take rotation x into account (in such case it probably would be good if it could work with any billboard mesh)

It's quite basic feature that can be used in many  graphical effects, it would be great to have such ability.

**Comment by oiblank** [comment]
This please, I need this one like salt.

**Comment by Devastus** [comment]
+1 to this, without this working I reckon you're pretty much forced to make your own custom shaders if you intend to work with 3D sprites.

**Comment by fossegutten** [comment]
You can use look_at as a workaround, instead of billboard mode.

**Comment by clayjohn** [comment]
I have a feeling this is implemented with the various [billboard modes](https://docs.godotengine.org/en/stable/classes/class_spatialmaterial.html#enum-spatialmaterial-billboardmode) in godot 3.x

Can anyone confirm

**Comment by KoBeWi** [comment]
No answer to the last comment and also this is something more fit for a [proposal](https://github.com/godotengine/godot-proposals), so closing.

**Comment by Gastronok** [comment]
Ran into this myself; created a discussion-for-proposal at https://github.com/godotengine/godot-proposals/discussions/5821
