### ISSUE TITLE
2D Sprite Normal Maps Are Inverted

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#18299]
**Godot version:**
3.0.2

**OS/device including version:**
Win10

**Issue description:**
2D normal mapping is inverted on Sprite's: dark is is light and light is dark. [This user](https://www.reddit.com/r/godot/comments/7xjbud/help_with_sprite_normal_maps_inverting/dua482q/) had the same issue and solved it by inverting the green or the red & green channels, depending on how they generated the map.

![capture](https://user-images.githubusercontent.com/7429786/39011473-5bd35fbe-43c6-11e8-8835-72d2307ca90d.PNG)

**Steps to reproduce:**
Create sprite, add normal map, add Light2D. Colors are inverted.

**Minimal reproduction project:**
[New Game Project1.zip](https://github.com/godotengine/godot/files/1929347/New.Game.Project1.zip)

**Comment by eon-s** [comment]
Could be that Sprites are upside down (-Y = up) for 2D while normal maps do not have the 2D correction.

**Comment by JarLowrey** [comment]
I have tried inverting G and RG channels and rotating the sprite 180 degrees and unfortunately it didnt solve the problem

**Comment by JarLowrey** [comment]
Translating my Godot2 normal map shader into Godot 3 also did not solve anything

```
shader_type canvas_item;
uniform sampler2D normal : hint_normal;

void fragment(){
	//normal maps expect Y-up, but 2D is Y-down, so must mirror this.
	NORMAL = texture(normal, UV).rgb * vec3(2.0,-2.0,1.0) - vec3(1.0,-1.0,0.0);
}
```

**Comment by JarLowrey** [comment]
It looks like the light is coming from the correct direction but is getting blocked after touching the map. I have dramatically reduced my normal map height and it doesnt appear to help much

![capture](https://user-images.githubusercontent.com/7429786/39667864-21d0e79a-5074-11e8-8dcf-8960723bc6f3.PNG)

**Comment by fracteed** [comment]
@JarLowrey I tried adding your line of code to my shader and it was working much better than a straight *= -1 of the y/green channel. But, for the life of me I cannot work out why you are multiplying the red and green channels by 2 and the blue by only one? Why do you then subtract that vector. I have started using this line of code, but I never like using "magic numbers", so enquiring minds would love an answer :)

**Comment by JarLowrey** [comment]
Great question! ... I don't know. I think I found this code about a year ago and cannot find my original source again. I guess it's mirroring those two channels in opposite directions, but B is fine. Kind of like the issue we're facing in 3.0.

I believe it is based on [this example](https://github.com/godotengine/godot-demo-projects/tree/master/2d/sprite_shaders) and [this comment from @reduz](https://github.com/godotengine/godot/issues/1467#issuecomment-76750068).

**Comment by fracteed** [comment]
@JarLowrey  thanks for the info! Strangely, in that post from reduz you linked to, he adds the vector at the end, rather than subtracting. Also, had a look at the 2d sprite shaders project file and could see no normal map example. I am guessing it was in the the Godot 2.0 version example scene and not the current one, as there is built in 2d normal lighting. The builtin normal light is great, assuming you have the correct normal map format which I am not sure that any programs render by default. 

Anyway, all is good at it works well now in my game, so obviously reduz did it this way for a reason :)

**Comment by JarLowrey** [comment]
Looks great! I followed you. I'll try the normal mapping again when I have time.

**Comment by clayjohn** [comment]
For future reference, in CanvasItem shaders use `NORMALMAP` when using normal maps that are meant for 3D. This will override `NORMAL` and perform the conversion for you automatically. This isnt documented right now, but Reduz [mentions it](https://github.com/godotengine/godot/issues/1467#issuecomment-96611832) at the end of the thread linked to above.

**Comment by Calinou** [comment]
Should we flip 2D normal maps for 4.0, since we can break compatibility there?

**Comment by greygraphics** [comment]
What about a flag to invert one of the channels for sprite normal maps?

**Comment by Calinou** [comment]
@greygraphics This was requested here already: https://github.com/godotengine/godot-proposals/issues/785

It'd work for both 2D and 3D normal maps.

**Comment by HeroicNate** [comment]
I ran into this issue and I've been trying to figure out how to flip it in code. I see the code in the above posts but have no idea where to put it. I dropped my normal map into the normal map area under the texture but there is not a place to enter code on it.

**Comment by greygraphics** [comment]
> I ran into this issue and I've been trying to figure out how to flip it in code. I see the code in the above posts but have no idea where to put it. I dropped my normal map into the normal map area under the texture but there is not a place to enter code on it.

It is shader code, see [the documentation](

**Comment by HeroicNate** [comment]
> It is shader code, see [the documentation](https://docs.godotengine.org/en/stable/tutorials/shading/your_first_shader/index.html) on writing your own shaders.

Thanks for the link to the documentation. I'll have to do a deep dive on the shaders in godot to fully understand how it applies to the specific case of the normals being flipped. The documentation appears to be about 3D, but I guess it all applies the same.

**Comment by eon-s** [comment]
@HeroicNate you can convert a spatial material into shader material and see how it is used.

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot/pull/39202 (`master`) and https://github.com/godotengine/godot/pull/48693 (`3.3`). To use this normal map Y inversion feature, select the normal map texture in the FileSystem dock, check **Normal Map Invert Y** in the Import dock then click **Reimport**.
