### ISSUE TITLE
Shader: vec4(vec3(float), float) is not compiled correctly

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#18306]
**Godot version:**

394e6d5 Antergos x86_64 
```
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Haswell

$ lspci
00:02.0 VGA compatible controller: Intel Corporation 4th Generation Core Processor Family Integrated Graphics Controller (rev 06)
01:00.0 3D controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev a1)
```

**Issue description:**

Expected: no error from doing `vec4(vec3(0.7),1.0)`, giving `vec4(0.7,0.7,0.7,1.0)`
Happened: no shader output rendered
```
249: 		color=vec4(0.7,1.0);
[...]
ERROR: _display_error_with_code: CanvasShaderGLES3: Fragment Program Compilation Failed:
0:249(8): error: too few components to construct `vec4'
```

**Steps to reproduce:**
Attach this shader to a CanvasItem's ShaderMaterial
```
shader_type canvas_item;

void fragment(){
	COLOR = vec4(vec3(0.7),1.0);
}
```

**Minimal reproduction project:**

\-

**Comment by panzergame** [comment]
The function `_reduce_expression` is causing the issue:

For an expression like `vec3(0.0, vec2(1.0))` the reduction will reduce intent to make a constant with the expression between parenthesis and assign it to the constructor operator (e.g vec3() vec2()).
So `vec2(1.0)` became `1.0` and `vec3(0.0, 1.0)` (after derivation) is `0.0, 1.0`.

What is the interest of keeping only one float for vector construction of the form vecX(val) ?
I didn't investigated more but maybe expanding in the example `vec2(1.0)` to `1.0, 1.0` will solve the issue.

**Comment by panzergame** [comment]
I leave an experimented developer work on this issue as I didn't really understand the goal of the reduce expression function.
