### ISSUE TITLE
GridContainer with children having a Min Size causes freeze

### ISSUE THREAD

**Issue by arnaudcoj** [godotengine/godot#18307]
**Godot version:**

3.0.2

**OS/device including version:**

Windows 7 64 bits - Geforce GT 425M

**Issue description:**

Godot freezes when using a GridContainer which has several children. Those children being Control nodes and having a given min size.

**Steps to reproduce:**
- Instantiate a GridContainer
- Set its Rect > Size > x to a given number (here 1000)
- Set its column numbers to a given number (here 4)

- Create a child Control node
- Set Rect > Min Size > x to a given width (here 300)

- Duplicate the new Control node until you have 4 children (with a cumulated width of 300 * 4 = 1200, superior to GridContainer's current size)
- Watch Godot freeze

**Minimal reproduction project:**

[GridContainerBug.zip](https://github.com/godotengine/godot/files/1929822/GridContainerBug.zip)

**Comment by arnaudcoj** [comment]
(I'm sorry the title isn't very explicit, I didn't know how to put it...)

**Comment by arnaudcoj** [comment]
Before posting I searched in the open issues only (woops), but I just saw this in the closed issues : https://github.com/godotengine/godot/issues/17956
Can this be related ?

**Comment by groud** [comment]
Yeah this is already fixed for 3.0.3
