### ISSUE TITLE
Debuger panel fail on show export objects

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#1831]
At this pic when debuger show export variable override_mat_image the table jump to next variable!
![captura de tela - 06052015 - 06 17 51](https://cloud.githubusercontent.com/assets/85936/7490945/e30583cc-f3ba-11e4-9be3-b9b24dd6545c.png)

**Comment by akien-mga** [comment]
Can you still reproduce this issue in the current master branch? If so, could you provide an example project that triggers it?

**Comment by mohaalak** [comment]
@marcosbitetti can you still reproduce this issue master branch or even in Godot 2.0 ? can you provide us with a project that trigger this issue?

**Comment by marcosbitetti** [comment]
The code is lost. But when I post it are a ordinary matrix.
But in next releases I not notice it.

**Comment by mohaalak** [comment]
@marcosbitetti then we close this issue for now, @akien-mga can you please close this issue?

**Comment by bojidar-bg** [comment]
Assumming it has been fixed then, if somebody spots the issue again, he might open a new one.
