### ISSUE TITLE
Clearing a recently attached script fails without error

### ISSUE THREAD

**Issue by krogank9** [godotengine/godot#18311]
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
Linux/Ubuntu 1710

**Issue description:**
"Clear script" does not work on a recently attached script until you reselect the node. The node appears to become half selected without the usual outline, and once you reselect it, it shows the usual select outline and clearing the script works fine. This bug also does not occur if you drag the script on rather than click "Attach script" and select the script through that menu.

This is what a node looks like when selected:
![screenshot from 2018-04-20 02-31-18](https://user-images.githubusercontent.com/12469653/39034077-047d75a6-4443-11e8-8e0e-234c722c5d76.png)
This is what a node looks like after a script is added to it (notice no selection outline) and the "Clear script" button does nothing.
![screenshot from 2018-04-20 01-53-41](https://user-images.githubusercontent.com/12469653/39033256-38fd43d2-443f-11e8-9aac-dd9399fb381e.png)
It seems to be not completely selected, yet the clear script icon is still present above the node list. You can right click and do other actions such as "Change type" which work, and you can right click other nodes and clear their scripts when the node list is in this state, the only thing that seems to be broken is clearing the current node's script.

This is strange behavior even if it was intentionally designed like this. I think it is still a bug. What is that weird half selected state? Why would you want to deselect a node after attaching a script to it? If this is intended behavior, dragging a script onto a node should also make it half selected. If this is supposed to mean the node is not selected, then why is the clear/add script icon not hidden as it is when no node is selected?:

![screenshot from 2018-04-20 02-10-13](https://user-images.githubusercontent.com/12469653/39033472-2ae0712e-4440-11e8-9dbd-78d9b754a617.png)

**Steps to reproduce:**

1. Attach/create a script on any node using the "Attach script" button.
2. Hit "Clear script" by right clicking the node or by using the button above the node list
3. It fails without error or explanation

**Minimal reproduction project:**
Any project with a node and script file

**Comment by flashyincceo** [comment]
I am unable to replicate this bug on macOS 10.12.6 with the latest development version. Maybe I am misunderstanding the bug? Pressing "Clear script" immediately after "Attach script" seems to work fine on my setup. 

Current behavior:
![scriptexample](https://user-images.githubusercontent.com/18668880/39158029-50bcaab2-4723-11e8-8136-85e82c4d3e46.gif)

**Comment by krogank9** [comment]
Interesting, it's possible it's because you're on a different version than I am, but I don't have time to compile it. Here is a gif of what happens on mine:

![mov](https://user-images.githubusercontent.com/12469653/39163434-74dd53fe-4748-11e8-9daa-eaab5aba70db.gif)

I wonder why yours doesn't open the script after attaching like mine does? When it does that it seems to do the deselecting thing.

**Comment by krogank9** [comment]
Just tried with latest git version, it seems to be fixed.

**Comment by akien-mga** [comment]
Closing as fixed then. If someone tracks down what commit fixed it in the master branch, it could likely be cherry-picked for the 3.0 branch.
