### ISSUE TITLE
Autotiling: non-rectangular collision shapes do not work as expected for corner tiles

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [godotengine/godot#18318]
**Godot version:** 3.0.2 stable

**OS/device including version:** Windows 10 Home

**Issue description:**
When using the autotile feature, collision shapes you draw seem to automatically be converted to square shapes behind the scenes. In other words, if I draw a non-rectangular collision shape along the border of a tile, the character will still collide with the entire tile and not just the border I drew.

**Steps to reproduce:**
Create a Tilemap with an autotiled tileset. Give one of the tiles a non-rectangular collision shape.

**Minimal reproduction project:**

[autotile.zip](https://github.com/godotengine/godot/files/1932342/autotile.zip)

(Turn on visible collision shapes and try moving to the top left or bottom left corner of the map)

**Comment by guilhermefelipecgs** [comment]
Duplicate #18197

**Comment by vnen** [comment]
Closing as duplicate of #18197 then.
