### ISSUE TITLE
Cross compilation for Windows using MinGW failed, header missing?

### ISSUE THREAD

**Issue by atsuzaki** [godotengine/godot#18313]
Using master at #18119.
I'm on Ubuntu 16.04.3 LTS under Windows Linux Subsystem.

Here's the log:
> $ scons platform=windows tools=yes target=release_debug bits=64
> scons: Reading SConscript files ...
> Configuring for Windows: target=release_debug, bits=64
> Using Mingw
> YASM is necessary for WebM SIMD optimizations.
> WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
> Checking for C header file mntent.h... (cached) no
> scons: done reading SConscript files.
> scons: Building targets ...
> [Initial build] Compiling ==> thirdparty/mbedtls/library/entropy_poll.c
> thirdparty/mbedtls/library/entropy_poll.c:67:21: fatal error: intsafe.h: No such file or directory
> compilation terminated.
> scons: *** [thirdparty/mbedtls/library/entropy_poll.windows.opt.tools.64.o] Error 1
> scons: building terminated because of errors.

**Comment by akien-mga** [comment]
Ubuntu 16.04 ships with mingw-w64 4.0.4, which does not include `intsafe.h` indeed. It was added to mingw-w64 in version 5.0.

@Faless proposed #16984 to fix it, but we decided that it was too hacky and would be better to drop support for mingw-w64 < 5.0.

**Comment by akien-mga** [comment]
If you want to cross-compile from WSL (sounds a bit far fetched, but why not :P), I'd advise to use the latest Fedora, which always comes with a very recent version of mingw-w64.
