### ISSUE TITLE
Debugger outputs incorrect line number when parent constructor is not called correctly

### ISSUE THREAD

**Issue by krogank9** [godotengine/godot#18312]
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
Linux/Ubuntu 1710

**Issue description:**

The debugger displays an error with wrong line number when an inherited class doesn't call his parent's constructor correctly:

![screenshot from 2018-04-20 03-11-06](https://user-images.githubusercontent.com/12469653/39035663-dbdc7d94-4448-11e8-8f3d-7f9f940c7e9a.png)

As you can see the error it gives is on line 8, but the invalid call to _init() occured on line 9. If there are no vars defined and set above the constructor it will display the correct line number.

**Steps to reproduce:**

1. Make a parent class whose constructor takes 1 parameter
2. Make a child who fails to call the parent constructor with required arguments.
3. Define and set a variable directly above the child constructor.
4. Create an instance of the child class, producing an error.

The debugger displays/links to the wrong line number. It instead links to the line number of the variable above the childs constructor.

**Minimal reproduction project:**
```
extends Spatial

class a:
	func _init(abc):
		pass

class b extends a:
	var v = 0
	func _init():
		pass

func _ready():
	b.new()

**Comment by Calinou** [comment]
@krogank9 Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Sslaxx** [comment]
Attempting this with 3.2.1:

`Parser Error: Too few arguments for "_init()" call. Expected at least 1.`

Stack frames point to the script I used (just c&p-ed the above), at line 9 (`func _init():`). Line 9 is also red-highlighted in the script editor.

**Comment by Calinou** [comment]
@Sslaxx Thanks for replying :slightly_smiling_face:

If I'm reading correctly, this means the bug has been resolved, so I'll close this (correct me if I'm wrong).
