### ISSUE TITLE
Pasting over a selection adds an extra undo step

### ISSUE THREAD

**Issue by krogank9** [godotengine/godot#18325]
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
Linux/Ubuntu 1710

**Issue description:**

Pasting over a selection adds an extra undo step

**Steps to reproduce:**

1. Copy something to clipboard
2. Make a selection, then paste replacing the selection
3. Undo. Instead of the text reverting to the initial selection which you replaced, it reverts to an empty string.
4. Undo again. This will restore the original string

**Minimal reproduction project:**
Any script file

**Comment by Zouch** [comment]
Considering the "paste" operation as complex seems to be doing the job. I Will add a PR soon

**Comment by vnen** [comment]
Fixed by #18743.
