### ISSUE TITLE
Annoying Visual Script bug

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot#18322]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 7

**Issue description:**
While I was creating a visual script for text-based tutorial, I used an assign node to assign text to a label.
I want to have multiple of these nodes in a chain, but every time I update the script in someway, the previous node's text gets changed.

**Steps to reproduce:**
1: Create a control node with a visual script connected
2: Create a label node as a child.
3: Override the _ready function in visual script.
4: Drag the text property of the label into the script and connect it to _ready.
5: Type in anything in the value of the new node.
6: Drag the text property again into the script and connect to previous node.
7: Type in something an-
7: !!!! The last node's value field will most likely be empty.

**Comment by fire** [comment]
![godot windows tools_2018-10-11_15-57-26](https://user-images.githubusercontent.com/32321/46838498-620e4880-cd6e-11e8-8079-baca93987212.png)

Does this help?

**Comment by KoBeWi** [comment]
Doesn't happen in 3.1 stable
![image](https://user-images.githubusercontent.com/2223172/56931385-1b045c80-6ae0-11e9-8d10-2859d4ae2a5a.png)

**Comment by fire** [comment]
Closing due to report it doesn't happen anymore.
