### ISSUE TITLE
Android Crash 

### ISSUE THREAD

**Issue by NedJaims** [godotengine/godot#18326]
**Godot version:**

Godot 3.0.2 stable

**OS/device including version:**

Samsung Galaxy A7 2017 ,Android 7.0 

**Issue description:**

When I run the game on android the splash screen blinks and the game closes

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
Is the Samsung Galaxy an Adreno device? Is the game 2d or 3d?

**Comment by NedJaims** [comment]
No, the graphics card is ARM Mali-T830 MP3, and it's a 2D game.

**Comment by NedJaims** [comment]
No, the graphics card is ARM Mali-T830 MP3, and it's a 2D game.

**Comment by vnen** [comment]
You should run `adb logcat` to see the output from Godot. Otherwise it's impossible to know what's happening.

**Comment by NedJaims** [comment]
It was nothing, it was the JDK that is outdated, anyway thanks for the support. :)

**Comment by bojidar-bg** [comment]
@NedJaims Is this issue fixed then?

**Comment by Calinou** [comment]
I'm closing this since this issue is resolved.
