### ISSUE TITLE
can't update rect_position.y by any number smaller than a whole number  

### ISSUE THREAD

**Issue by girng** [godotengine/godot#18335]
**Godot version:**
3.0

**OS/device including version:**
win 7 64bitz

**Issue description:**
when updating a control node's `rect_position.y` property, it doesn't let you update it if you use something less than a whole number.

**Steps to reproduce:**
create a rich text label node, set the size of it to be very big. fill it with random text.
now attach a script, and use this code:
```
func _process(delta):
	print(delta/15, "::BUG::->>", rtl.rect_position.y)
	rtl.rect_position.y -= delta/15
```

as you can see. the rect_position.y property can't be updated by floats, only whole numbers. it should allow floats because when scrolling a control node (for example, a credits page), you want it to scroll very slow.  

e: this use to work, might be a regression somewhere

**Comment by ShyRed** [comment]
Hi @girng ,

Godot 3.0 is outdated. You should upgrade to the latest stable version that is version 3.0.2. A lot of new features are added and a lot of bugs a fixed there already.

I am able to reproduce your issue on current master, but this does not seem to be a bug to me:

Godot snaps controls to pixels by default. This optimization is what makes Godot ignore the tiny position updates you are sending it. You can turn off this optimization by going into *Project Settings* -> *Gui* -> *Common* and uncheck the *Snap Controls To Pixels* checkbox:

![image](https://user-images.githubusercontent.com/1138805/39085901-2dd30f86-458a-11e8-8a24-ef6e74557301.png)

Please check, if this fixes your issue.

**Comment by groud** [comment]
Yeah, that's not a bug, that's a feature. Control nodes snap to the grid by default.

**Comment by girng** [comment]
@ShyRed yeah, that seemed to fix it. thank you for the help

@groud srry about that, i need to look into settings before i post issue =]

**Comment by groud** [comment]
No problem. It happens ^^
