### ISSUE TITLE
Animation scene prevent game to start

### ISSUE THREAD

**Issue by Garrom** [godotengine/godot#18333]
**Godot version:**
3.0.2-stable

**OS/device including version:**
Windows 7 Ultimate x64
Laptop Lenovo B50-80
CPU Intel Pentium 3825U
GPU Intel HD Graphics Broadwell-U GT1 - Integrated GPU

**Issue description:**
If I try to play scene containing animation (Better Dae Exporter was used), Game window close during initialization reading following error in Output tab

`running cmdline: "C:\Users\Garrom\Desktop\Programs\Godot.exe" "--path" "C:/Users/Garrom/Desktop/Files/GoDot/Projects/PickTheCube" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "4832" "--position" "171,84" "res://Objects/Yellow_Cube.tscn"
** Debug Process Started **
 drivers\windows\stream_peer_tcp_winsock.cpp:203 - Server disconnected!

** Debug Process Stopped **`

**Steps to reproduce:**
1) Download attached scene
2) Import attached scene
3) Play attached scene
4) It pointing to drivers but all are up to date
5) Because it pointing to drivers it can be my personal problem but I need some assistance to solve this

**Minimal reproduction project:**
(Unzip required)
[Yellow_Cube.zip](https://github.com/godotengine/godot/files/1934653/Yellow_Cube.zip)

**Comment by Garrom** [comment]
Nevermind, I'm still too new to godot and deleting and recreating imported instated of moving it have fatal effects.

**Comment by Calinou** [comment]
Closing, since the original poster marked the issue as resolved.
