### ISSUE TITLE
Inherited variables not visible in debugger.

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#18346]
I have a .gd that inherits from another .gd.

The problem is when I am debugging with breakpoints. Inside the debugger the inherited variables are not shown. Only the child variables are shown. This makes it impossible to debug.  

ps, also, is there any work around for now?s

**Comment by Geequlim** [comment]
@ondesic  I'm fixing this problem.

**Comment by Geequlim** [comment]
![image](https://user-images.githubusercontent.com/6964556/39225733-851f328a-4880-11e8-8a93-43fad5deb3e0.png)

**Comment by ondesic** [comment]
Awesome!!

**Comment by ondesic** [comment]
is this fix included in the 3.03 release?

**Comment by Geequlim** [comment]
I think the code is fine with 3.0 branch

**Comment by ondesic** [comment]
I am using the 3.03 rc 2 and it isn't in there.  is this considered part of the 3.0 branch?

**Comment by ondesic** [comment]
I am using the 3.03 rc 2 and this feature is NOT in there.  Is 3.03 rc 2 considered part of the 3.0 branch or is there another build.
--

**Comment by akien-mga** [comment]
3.0.3 rc 2 is built from the 3.0 branch, but this change will not be included there *before* it gets reviewed and merged in the master branch.
