### ISSUE TITLE
Request: Allow button pressed() signal to pass an optional object (current button) to the callback

### ISSUE THREAD

**Issue by exts** [godotengine/godot#18358]
Currently if you want to trigger the same functionality for individual buttons when attaching the pressed signal you have to create N amount of callback functions, one for each button. Then another function for handling those calls if you want the functionality to be executed. For instance:

```gdscript
func execute_button(button):
    match button.get_name():
        "button1":
            print("do something with button1")
        "button2":
            print("etc...")

func button1_pressed():
    execute_button($Button1)

func button2_pressed():
    execute_button($Button2)

func button3_pressed():
    execute_button($Button3)

func button4_pressed():
    execute_button($Button4)
```

This would be better done if we can pass an optional object directly to the pressed signal and do what we want with that button to avoid unnecessary duplication.

**Comment by HugeGameArtGD** [comment]
What about ```execute_button(get_node("button"))```?

**Comment by exts** [comment]
@HugeGameArtGD I think you missed the point of my post. Buttons have a "pressed" signal and it doesn't know anything about the button. The programmer knows this, so they have to write code with that in mind.

**Comment by LinuxUserGD** [comment]
So you want to know which button is pressed in one function? In this case you would simply replace match with ```print("do something with " + button.get_name()```

**Comment by exts** [comment]
@LinuxUserGD again you guys are not getting the picture.

![](https://i.imgur.com/7qH55w6.png)

Lets go back to my example. Say you have 4 buttons, each button has a "pressed" signal. If you have _one_ function that you want all those buttons to connect to. that function won't have any idea what button is calling that function. The only thing that call back will know is "something is calling this, do something"

What I'm requesting is `pressed(object button)` so if I attach each button to the same method, that button now optionally knows about which button is being pressed. Think of it like an area2d when you setup a `body_entered(object body)` signal.

I honestly don't know how to break it down any simpler.

**Comment by sprite-1** [comment]
I get what you're saying 👍

**Comment by sprite-1** [comment]
You can use this to achieve the same effect
```
func _ready():
    $button.connect("pressed", self, "hello_there", [$button])
    pass

func hello_there(hey):
    print(hey.name)
```

**Comment by exts** [comment]
Going to close this issue for now, connect workaround is solid.
