### ISSUE TITLE
File.seek(0) not resetting File.eof_reached in compressed files

### ISSUE THREAD

**Issue by Phoenix1747** [godotengine/godot#18352]
**Godot version:**

3.1.1-stable

**OS/device including version:**

Manjaro Linux, Windows

**Issue description:**

I'm currently working with the `File` class and just noticed a rather annoying bug. If you open some compressed file and go through a `!eof_reached` while loop, then set the file cursor back to the beginning with `seek(0)`, a second `!eof_reached` loop will instantly break. It looks to me as if calling `seek(0)` indeed resets the file cursor to 0 (checked this) but does not "reset" `eof_reached`. I'm not sure, maybe the documentation about `File.seek` or `File.eof_reached` is incomplete and I just don't know something? :thinking: 
The specific piece of code I'm talking about is below.

**Steps to reproduce:**
Test with this code:
```python
var save = File.new() #New file, let's name it "save"
var compression = 2
var path = "res://file.txt"
	
save.open_compressed(path, File.WRITE, compression) #write content to the test file
save.store_line("line 1")
save.store_line("line 2")
save.store_line("line 3")
save.close()
	
save.open_compressed(path, File.READ, compression) #open the compressed test file
	
while !save.eof_reached():
  print("Loop 1: ", save.get_line())
	
save.seek(0) #go back to the start of the file
	
while !save.eof_reached():
  print("Loop 2: ", save.get_line())
	
save.close()

```
... the second while loop will not be called.

This code will work fine with uncompressed files, the issue only occurs with compressed files.

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment]
Tagging as topic:porting since File.eof_reached is implemented per-platform.

**Comment by Phoenix1747** [comment]
Experiencing this bug on Linux and Windows; just tested it with a debug build on Windows and the same problem happens.

**Comment by KidRigger** [comment]
Does not occur on macOS, debugged with code 

    var savegame = File.new()
	savegame.open("res://tt/test.txt", File.READ)

	var y = savegame.is_open()
	var x = savegame.eof_reached()
	while not x:
		x = savegame.eof_reached()
		savegame.get_line()
		y = savegame.get_position()
		print(x)
	
	savegame.seek(0)
	y = savegame.get_position()
	
	x = savegame.eof_reached()
	while not x:
		x = savegame.eof_reached()
		savegame.get_line()
		y = savegame.get_position()
		print(x)
	
	savegame.close()
	pass

**Comment by Phoenix1747** [comment]
Thanks @KidRigger for checking. I just tested it again and it seems to work now; I'll investigate my use case again.

**Comment by Phoenix1747** [comment]
Really strange it works for me with uncompressed files too, **however** doing so with **compressed** files fails. I updated the test code, could you please check that too?

**Comment by bojidar-bg** [comment]
Ah, my bad.. didn't realise compressed files are implemented separately.

**Comment by KidRigger** [comment]
> Does not occur on macOS
For posterity,  this is changed to: 

> Does not occur on uncompressed files

**Comment by KidRigger** [comment]
Issue is not as straightforward as just resetting read_eof bool on seeking < total_size
I can do it only after 11th May. Anyone is free to take it till then.

**Comment by Phoenix1747** [comment]
Just checked back with the latest Godot 3.1 and wanted to let you know that the issue is still here.
