### ISSUE TITLE
The Delta Situation (Delta Error)

### ISSUE THREAD

**Issue by Doomish2005** [godotengine/godot#18353]
The Delta Situation

**Godot version:**
3.0

**OS/device including version:**
Windows 7 (Up To Date) GTX 210 Nvedia 

**Issue description:**
As usual I follow the documentation and BOOM!It tells me that it tells me "Praser Error: Identifier not found: delta".An obviously I tried again redid the steps and still tells me Identifier not found. I hope you can fix this or tell me if i was insolent and did not read it properly.Thank You!

**Steps to reproduce:**
Follow Documentation from Page 53 to 61

**Minimal reproduction project:**
[Error with Delta.zip](https://github.com/godotengine/godot/files/1935536/Error.with.Delta.zip)

**Comment by Doomish2005** [comment]
I Thank You Guys Again For Being The Best People to work with!

**Comment by Noshyaar** [comment]
`delta` can only be used in `_process` or `_physics_process`

**Comment by Noshyaar** [comment]
![image](https://user-images.githubusercontent.com/26753932/39094872-061d77ec-4661-11e8-872f-d607693cf33e.png)

Closing as the docs is correct.

**Comment by NathanLovato** [comment]
note if you need to access delta somewhere else, you can use `get_process_delta_time` but keep in mind it's only for `process`, not `physics_process`, which ticks at different time intervals.
