### ISSUE TITLE
Overflow warning message during compilation

### ISSUE THREAD

**Issue by ricpelo** [godotengine/godot#1835]
Compiling latest HEAD on OS X I get the following warning message:

```
./servers/physics/collision_object_sw.h:85:45: warning: overflow in expression; result is 276447232 with type 'int'
      [-Winteger-overflow]
                if (p_transform.origin.length_squared() > MAX_OBJECT_DISTANCE_X2) {
                                                          ^
```

I don't know if it's harmless (if it is, sorry for the noise).

**Comment by akien-mga** [comment]
`MAX_OBJECT_DISTANCE_X2` is defined as `10000000.0*10000000.0`, i.e. in theory 1e14 (100000000000000). I don't think that `int` can handle that (or is it a `float`?).
