### ISSUE TITLE
Memory issue on Main::cleanup() on Android?

### ISSUE THREAD

**Issue by joshuatam** [godotengine/godot#18360]
**Godot version:**
master

**OS/device including version:**
Android

**Issue description:**
I am integrating Godot Engine into an android app so to start the game after some Activities.
It is working fine on the first load of the game, while I quit the game activity, and start the game again, it crashed and show the following errors in logcat:

```java
**ERROR**: Condition ' !t ' is true.
       At: core/class_db.h:174:register_class() - Condition ' !t ' is true.
**ERROR**: Condition ' !t ' is true.
       At: core/class_db.h:186:register_virtual_class() - Condition ' !t ' is true.
**ERROR**: Condition ' !t ' is true.
       At: core/class_db.h:174:register_class() - Condition ' !t ' is true.
**ERROR**: Condition ' !t ' is true.
       At: core/class_db.h:174:register_class() - Condition ' !t ' is true.
**ERROR**: Condition ' !t ' is true.
```

After that, I traced these errors which are actually thrown from `Main::setup()`, and related file is `core/class_db.h`,  throw the error with the following code in it:

```cpp
template <class T>
static void register_class() {

	GLOBAL_LOCK_FUNCTION;
	T::initialize_class();
	ClassInfo *t = classes.getptr(T::get_class_static());
	ERR_FAIL_COND(!t); // <-----Throw errors when re-open the game
	t->creation_func = &creator<T>;
	t->exposed = true;
	T::register_custom_data_to_otdb();
}
```

I also checked `ClassDB::cleanup()`, seems the `classes` HashMap is actually cleared in the function.

```cpp
void ClassDB::cleanup() {

	//OBJTYPE_LOCK; hah not here

	const StringName *k = NULL;

	while ((k = classes.next(k))) {

		ClassInfo &ti = classes[*k];

		const StringName *m = NULL;
		while ((m = ti.method_map.next(m))) {

			memdelete(ti.method_map[*m]);
		}
	}
	classes.clear(); // <----- classes HashMap cleared?
	resource_base_extensions.clear();
	compat_classes.clear();

	memdelete(lock);
}
```

Are there any reasons the memory (`classes` HashMap) still keeping in android? Or any other reasons behind it?

I have several commits to add android `stop()` and `cleanup()` for this functionalities, please check it at [https://github.com/lambdabit/godot/commit/56baa6157f17dd5c53a69e6c2df927acf5431bf7](https://github.com/lambdabit/godot/commit/56baa6157f17dd5c53a69e6c2df927acf5431bf7)

**Comment by akien-mga** [comment]
Is this still reproduce this bug in [Godot 3.2.3 rc5](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-5) or any later release?

CC @m4gr3d

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
