### ISSUE TITLE
Regression: AudioStreamPlayer.set_stream() performance issues

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#18366]
**Godot version:**
Godot 3.1-dev 1c41953

**OS/device including version:**
Linux Mint 18.3 Cinnamon x64

**Issue description:**
Setting a stream to an AudioStreamPlayer (via `AudioStreamPlayer.set_stream()` or setting the`AudioStreamPlayer.stream` property) takes up much more processing time in 3.1 than it does in 3.0.2, to the point where it causes the game to stutter for a frame in some cases. The node doesn't even need to be playing for this to happen; the game takes the performance hit upon assigning the resource.

To test this, I created a simple scene in both 1c41953 and 3.0.2-stable with two buttons that set an AudioStreamPlayer node's `stream` to either an .ogg (AudioStreamOGGVorbis resource) or .wav (AudioStreamSample resource).

![image](https://user-images.githubusercontent.com/27100585/39099922-73d6aa7e-46c5-11e8-9478-e0c5b876aa0d.png)

```swift
extends Control


onready var player = get_node("AudioStreamPlayer")

onready var ogg_file = preload("hweru3.ogg")
onready var wav_file = preload("attack2.wav")


func _on_ButtonOgg_pressed():
	player.stream = ogg_file


func _on_ButtonWav_pressed():
	player.stream = wav_file
```

I then clicked each button 10 times while monitoring the average performance in the profiler. These are the results:

### .ogg:
![image](https://user-images.githubusercontent.com/27100585/39099997-9870a3fc-46c6-11e8-9a61-c00d44d32f1a.png)

### .wav:
![image](https://user-images.githubusercontent.com/27100585/39100012-c00263ba-46c6-11e8-9b70-ef4104d0d707.png)

### .ogg:
![image](https://user-images.githubusercontent.com/27100585/39099959-370fa874-46c6-11e8-97ff-2e477d34bd9a.png)

### .wav:
![image](https://user-images.githubusercontent.com/27100585/39099971-4acf3406-46c6-11e8-8331-e0150e612fcd.png)

**Minimal reproduction project:**
[audiotest-3.1.zip](https://github.com/godotengine/godot/files/1936121/audiotest-3.1.zip)
[audiotest-3.0.2.zip](https://github.com/godotengine/godot/files/1936122/audiotest-3.0.2.zip)

**Comment by ShyRed** [comment]
**A shot in the dark:** There have been a few pull requests merged regarding PulseAudio: https://github.com/godotengine/godot/pulls?q=is%3Apr+pulseaudio+is%3Aclosed

The pull request "Fixed high cpu usage with PulseAudio" increated latency from 2,79ms to 11,57ms. Maybe that is a good candidate to start with?

**Comment by Phoenix1747** [comment]
Holy cow, that's a pretty significant issue. 

> The pull request "Fixed high cpu usage with PulseAudio" increased latency from 2,79ms to 11,57ms.

Also #18215 is pretty damn ironic if that's true :D
