### ISSUE TITLE
 Enable Debugging checkbox inverted

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#1836]
If you export and uncheck Enable Debugging, it exports using the debug version, and if you check it, it exports release version... :smile:

**Comment by akien-mga** [comment]
Are you sure about this, or is it that you misunderstood the (IMO somewhat confusing) ON/OFF button? IIUC, when the option is toggled on it shows "ON", even though one could think due to the graphics that one has to click this "ON" to toggle it on.

**Comment by bojidar-bg** [comment]
@akien-mga I would rather close this issue, as I remember it as a checkbox, plus there is a high chance that either it was fixed or I was mistaken.
