### ISSUE TITLE
C# Dynamic keyword missing references for csproj

### ISSUE THREAD

**Issue by Kayomn** [godotengine/godot#18371]
**Godot version:**
3.0.2

**OS/device including version:**
Microsoft Windows 10

**Issue description:**
Compilation failure while using the C# `dynamic` keyword in a normal way.

**Steps to reproduce:**
Attempt to use `dynamic` in a Godot C# project and compile. It will produce a similar or exact error to:
```
Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
```

**How to fix**
Make the project include a reference to `Microsoft.CSharp` in the generated Godot `.csproj`.

**Comment by neikeq** [comment]
As you mention, the solution is to add `Microsoft.CSharp` as a reference to the project. We are not doing this though, because `dynamic` is not allowed on iOS. If there are users who want to use this feature and they don't care about iOS, they can simply add the reference to their projects.
