### ISSUE TITLE
Spatial material : Detail texture not good

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#18377]
Godot version: 3.0.2

Win 7, 64 bit I5, GTX 960

Hi there, 
The detail textures of spatial material does not look good and needs improvments because  albedo color doesn't mix well whatever we choose "Mix" or "Add" modes and normal map is almost no more visible and overriden with the detail normal map.

Also the detail texture shader would need two additionnal inputs : 
- Detail texture multiplier input number for UV otherwise it's not a detail texture
- Input number to specify the strength of the normal map over the detail normal map 

Left is my custom shader detail texture, right this is Godot Spatial material with detail textures result 

![*bugsquad edit: inlined image*](https://s9.postimg.cc/82fvmyt8v/detail_Texture.jpg)

Below is detail texture shader i made with for results

>     shader_type spatial;
    uniform float tex1res = 1;
    uniform float tex2res = 10;
    uniform sampler2D tex1Albedo;
    uniform sampler2D tex1Normal;
    uniform sampler2D tex2Albedo;
    uniform sampler2D tex2Normal;
	
	varying vec4 vertexColor; 
	varying vec3 vertexNormal; 

	void vertex() {
    	vertexColor = COLOR; // make the normal the color
		vertexNormal = NORMAL;
	}
 
    void fragment() {
        vec3 a1 = texture(tex1Albedo, UV * tex1res).rgb;
        vec3 n1 = texture(tex1Normal, UV * tex1res).rgb;
        vec3 a2 = texture(tex2Albedo, UV * tex2res).rgb;
        vec3 n2 = texture(tex2Normal, UV * tex2res).rgb;
		
		vec3 resultAlbedo = mix( a1 , a2, 0.5); 
        ALBEDO =  resultAlbedo;

		vec3 addNormals = mix(n1 *1.8,n2,0.5 );		
        vec3 nResult = normalize(addNormals);
        NORMALMAP = nResult;
		
        ROUGHNESS = 0.5;
    }

**Comment by DEF7** [comment]
The detail spatialmaterial option requires a mask in order to determine how much detail to incorporate via the chosen blend method.

**Comment by DevMagicLord** [comment]
Why there is not a simple detail texture without needing artists to create a mask ?
Let's say i want a rock to have detail textures all over in close  view.

Should Godot have some option to put the detail texture over the whole mesh without needing a mask ? 

Also there is no input to tell the scaling of the detail texture. It's not usable.

**Comment by DEF7** [comment]
You can scale the detail texture if you setup UV2 to be triplanar and set
UV2 to > 1 scaling. Yes, I agree the mask is kinda cumbersome in some cases
if you just want it to globally combine but really the whole detail
paradigm revolves around blending a secondary albedo/normal with a base
material. Just use a 50% gray texture with the mix blend and you'll have a
perfect combination.

**Comment by DevMagicLord** [comment]
Triplanar is to avoid, it costs too much when your scene is heavy with complex characters models and shaders.
I do agree , add some option to say to the detail shader "cover whole mesh" , this is how detail is used most of the time.

**Comment by DEF7** [comment]
> Triplanar is to avoid, it costs too much when your scene is heavy with complex characters models and shaders.

Are you referring to the triple-count texture taps?

**Comment by DevMagicLord** [comment]
Yes triplar mapping is to avoid or distribute wisely.

**Comment by DevMagicLord** [comment]
For detail texture, making a custom shader is more appropriated i think.
(While Godot could have a better detail texture).
