### ISSUE TITLE
Need Quaternion.AlignTo(Vector3)

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#18378]
**Godot version: 3.0.2

**Issue description:**

Hi there,

I tried using look_at function, but is has bugs and its' not easy to use.
Godot would need a very simple way to align two vectors like : 
**Quaternion.AlignTo(Vector3)**
 
And one that uses lerp to slowly rotate to a vector direction using the shortest angle path : 
**Quaternion.AlignToWithLerp(Vector3, lerpFactor )**

We need high functions like that instead of having to deal with angles.

**Comment by giladbau** [comment]
Can you please assign this to me?

**Comment by ShyRed** [comment]
> I tried using look_at function, but is has bugs and its' not easy to use.

1. Can you elaborate on what bugs you faced and why you find the `look_at` function not easy to use?
2. Can you try using the latest master version and see if the bugs you faced are still there? You can get an unofficial nightly build from https://hugo.pro/projects/godot-builds/ , for example.

**Comment by groud** [comment]
Both transforming a vector into a quaternion, and linear interpolation between quaternions are already possible. Please, [read the documentation](http://docs.godotengine.org/en/3.0/tutorials/3d/using_transforms.html). It also explains how look_at works, and probably why you think it's a bug.
