### ISSUE TITLE
[Feature] HTML5: Allow loading "main pack" as folder

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#18384]
**Godot version:**
master (3.1-dev)

**OS/device including version:**
Firefox 59.0.2-2

Former issue description:
```
 I've tried to export my project to .zip (using the gui resource exporter), but when I run the executable exported from the game, it's looking for the .pck instead (resource tree path./. not found).
sprite~1 mentioned on Discord that the export workflow already works for windows so this might be a bug.
```
**Request:**
Currently the .html file has to be edited (https://godot.readthedocs.io/en/latest/getting_started/workflow/export/customizing_html5_shell.html) to load a ``.zip`` as the main pack instead of the ``.pck``. I'm not sure if it's currently possible to load folders as the main pack that are in the same folder as the ``.html``, ``.js``, ``.png`` and ``.wasm``.

**Error Output:** (after editing to ``engine.startGame(BASENAME + '.zip'``)
```
let it go dude!
Error: Could not load game path '.'.
**ERROR**: Condition ' !_start_success ' is true. returned: false
**ERROR**:    At: main/main.cpp:1230:start() - Condition ' !_start_success ' is true. returned: false
```

**Comment by LinuxUserGD** [comment]
Sry, I had to move the executable inside the project folder (extracted .zip), this solves the problem it for X11 and Windows.

**Comment by eska014** [comment]
Querying the contents of a directory isn't allowed by the great majority of web servers, so it doesn't make sense to provide a built-in function.
You can use [`engine.preloadFile()`](https://godot.readthedocs.io/en/3.0/getting_started/workflow/export/customizing_html5_shell.html#engine-preloadfile-file-path) to manually download every individual file in a directory.

**Comment by LinuxUserGD** [comment]
@eska014 Is there a similar method to load the ```.zip```? ```engine.startGame(BASENAME + '.zip')``` doesn't work locally (not tested with URL).

**Comment by LinuxUserGD** [comment]
Ok, thank you, it works now!

```Swift
if (!Engine.isWebGLAvailable()) {
				displayFailureNotice("WebGL not available");
			} else {
				setStatusMode('indeterminate');
				engine.setCanvas(canvas);
				engine.startGame(BASENAME + '.zip').then(() => {
					setStatusMode('hidden');
					initializing = false;
				}, displayFailureNotice);
				engine.start('--main-pack', BASENAME + '.zip');
				engine.start('--main-pack', BASENAME + '.wasm');
				document.getElementById("status-notice").style.visibility = "hidden";
			}
```
[game.html.txt](https://github.com/godotengine/godot/files/1960995/game.html.txt)

**Comment by eska014** [comment]
You should use promises here to prevent race conditions and remove redundancy:

    const MAIN_PACK = BASENAME + '.zip';
    if (!Engine.isWebGLAvailable()) {
    	displayFailureNotice("WebGL not available");
    } else {
    	setStatusMode('indeterminate');
    	engine.setCanvas(canvas);
    	Promise.all([Engine.init(BASENAME), engine.preloadFile(MAIN_PACK)]).then(() => {
    		return engine.start('--main-pack', MAIN_PACK);
    	}).then(() => {
    		setStatusMode('hidden');
    		initializing = false;
    	}, displayFailureNotice);
    }
