### ISSUE TITLE
No way to see together 3D Nodes and Control Nodes

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#18396]
**Godot version:** 3.0.2

**Issue description:**
There is no way to see together how a GUI would look in a 3D scene. This is uncomfortable, expecially for scenes where GUI and world are highly tied together (for example, a character selection screen).
**Would be nice if the GUI rendered in the camera preview mode.**
In my particular case, i have 4 character that might join the game and i would like to have the ui positioned where the characters will appear, showing information as team, ready status, etc.

I think this is related to #11727 

**Steps to reproduce**: make a scene with both control nodes and spatial nodes(mesh instance for example) with a 3D camera.

**Comment by eon-s** [comment]
Maybe something like Sprite3D, a like a Mesh-Container3D to render controls easily in a spatial viewport.

**Comment by eon-s** [comment]
@QbieShay wait, you mean an overlay/canvas like when running (on 2D space), not controls attached to 3D nodes?

**Comment by Zylann** [comment]
How is the editor switching between 2D and 3D views? I guess this mechanism could be bypassed when Preview mode is on.

**Comment by QbieShay** [comment]
@eon-s  for me would be fine to just have the control render in the "camera preview" view. When you have a camera, you can click on the preview button. 

My workflow would be to have 2 views open, one classical spatial 3D, the other one is the camera preview.

@Zylann  it could work, but it's a bit of a porkaround :P

**Comment by Calinou** [comment]
The current `master` branch will display the 3D world as a background to the 2D editor, but I'm not sure if this is a bug or intended behavior. There should probably be a way to toggle it. Anyway, I'll consider this implemented for now :slightly_smiling_face:
