### ISSUE TITLE
Material cannot be removed (deleted) via engine.

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#18393]
**Godot version:**

Godot 3.0.2

**OS/device including version:**

OS: Windows 8.1

**Issue description:**

So, I imported a model from Blender (material is created automaticly from dae import). When I dont need the imported material anymore, i tried to delete it from the project explorer. But it still there not deleted.

About the materials:
> The material name is in japanese.
> The material dont have owner.

This is the screenshot.
![cantremovemat](https://user-images.githubusercontent.com/8316851/39173486-0e81bece-47cf-11e8-9f72-c149cde9dbae.JPG)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Anutrix** [comment]
Also SHFileOperationW should be replaced by IFileOperation.

**Comment by clayjohn** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by AureaFUNSoft** [comment]
Hi. I'm the poster of this bug report.
I think it's fixed now.
I've lost the above project, so I can't post it. But It is easy to reproduce the bug. You just need to make a new spatial material and then rename it to some Japanese kanji character using file explorer, then try delete that in Godot.
Or just copy this project: 
[Coco.zip](https://github.com/godotengine/godot/files/4906419/Coco.zip)
and try delete file: 様泳.tres

I've done this and can reproduce in the version above.
However in the latest version i have (Godot 3.2.2) it is not happen again.

**Comment by clayjohn** [comment]
Thats great to hear! :)

Thank you for following up and testing it out in 3.2.2. I will close the issue now.
