### ISSUE TITLE
Godot 2.1.4 windows export template (.exe output) compressed with UPX will throw error

### ISSUE THREAD

**Issue by dns** [godotengine/godot#18404]
I can compress games created with Godot 2.1.4, but it will not run (32 & 64-bit not working).

It's works on previous Godot release and the new Godot 3 export template, but will not work on Godot 2.1.4 export template.

I've not tested on Linux/OSX, maybe it will not work too.

```
D:\SANDBOX\Godot\Deploy>upx godot2.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94w       Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  17544528 ->   6558544   37.38%    win64/pe     godot2.exe

Packed 1 file.

D:\SANDBOX\Godot\Deploy>
D:\SANDBOX\Godot\Deploy>upx godot2.exe

ERROR: Corrupted header in binary engine.cfb (not ECFG)
   At: core\globals.cpp:735
```

**Comment by vnen** [comment]
Are you using the `Pack into executable` option? That's bound to have problems, even more if you pack with UPX (which is a non-standard tool, there's no guarantee it will always work). Bundling the resources into a `pck` is always better anyway.

**Comment by dns** [comment]
Yes I'm using "Pack into executable".

I just tried the "Pack into binary file (.pck)". It generate 2 files (.exe & .pck), but it throw this error:

```
D:\SANDBOX\Godot\Deploy>upx godot2.apk
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX 3.94w       Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: godot2.apk: UnknownExecutableFormatException

Packed 0 files.
```

**Comment by dns** [comment]
Yes, I'm using "Pack into executable".

**Comment by girng** [comment]
unfortunately, might be beyond the scope of this repo (upx not officially supported). can try cross-posting here: https://github.com/upx =]

**Comment by dns** [comment]
This have nothing to do with UPX, since the regular godot file can be compressed by UPX.

Because Godot 3 has removed "Pack into executable", I'll close this issue for now.
