### ISSUE TITLE
Ctrl+Click @GlobalScope constant scrolls to the wrong location

### ISSUE THREAD

**Issue by flashyincceo** [godotengine/godot#18409]
**Godot version:**

a096df5

**OS/device including version:**

macOS 10.12.6

**Issue description:**

Ctrl+Clicking (or Command+Clicking for Mac) on a `@GlobalScope` or `@GDScript` constant while editing a script scrolls too far in the documentation. This only happens the first time you Ctrl+Click, though. It seems to be related to the issues mentioned in #17396.

**Steps to reproduce:**
1. Create a new project
2. Add a label to the scene
3. Attach a script to the label
4. Add a `@GlobalScope` or `@GDScript` constant (I used `SPKEY`)
5. While holding down the control key (or command on Mac), click `SPKEY`
6. The documentation will scroll beyond the SPKEY definition
6. If you go back to the script and Ctrl+Click again, it will scroll to the appropriate line.

![editor-problem](https://user-images.githubusercontent.com/18668880/39223021-63bf3a98-4805-11e8-9d83-b12d812d39f0.gif)

**Minimal reproduction project:**

[Editor Help Bug.zip](https://github.com/godotengine/godot/files/1945230/Editor.Help.Bug.zip)

**Comment by flashyincceo** [comment]
It looks like this problem is not limited to Constants. Ctrl+Clicking on `Node.NOTIFICATION_ENTER_TREE`, for example, displays the same behavior. 

I'm working on a bug in the same area, so I should have a pull request for this issue soon.

**Comment by akien-mga** [comment]
Partly fixed in 3.1 (now scrolls to the relevant enum), and fully fixed in the master branch by #27465.
