### ISSUE TITLE
Mesh material not rendered when looking from some angles

### ISSUE THREAD

**Issue by srseil** [godotengine/godot#18417]
**Godot version:**
3.0.2 from the Fedora package archives

**OS/device including version:**
Fedora 27, open-source graphics stack (radeon + mesa)
OpenGL ES 3.0 Renderer: AMD PITCAIRN (DRM 2.50.0 / 4.15.17-300.fc27.x86_64, LLVM 5.0.1)

**Issue description:**
I have code fore building a level of tiles, some of which have different materials than others. Depending on from where the camera looks at the meshes, some of the tiles are not rendered with the material that I assigned to them in my code, but rather the standard material defined in the editor. See here:
https://i.imgur.com/fu7HkIJ.png (Only one green tile on the floor)
https://i.imgur.com/8k4y2yk.png (all other tiles except the one from the last image)

What is even weirder is that what is being displayed changes when I move the cube around the board, even though there is nothing in my code that changes the meshes or materials based on that:
https://imgur.com/a/5H4UdTc

**Comment by volzhs** [comment]
your materials have Transparent flag on.
did you fix with this flag off? and closed this?

**Comment by srseil** [comment]
Nevermind. It turned out that I accidentally spawned two tiles per grid position, so sometimes one was laying over the other and blocking it.
