### ISSUE TITLE
Texture atlas generation and set his resolution in the lightmap bake node

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18421]
Godot's lightmap baking generates one texture for each asset in the scene configured as "bake indirect". We can end up with thousand of tiny files that can make the engine take several minute to save our work and the same time to compile and test a script.
I suggest that the lightmap bake node allow to set a lightmap resolution, then the engine generates an atlas by packing as much UVs as possible based on the texel of the assets (or World texel density like suggested here: https://github.com/godotengine/godot/issues/18420 ).

**Comment by Calinou** [comment]
This should be fixed with the upcoming [new lightmapper in 4.0](https://godotengine.org/article/godot-40-will-get-new-modernized-lightmapper), closing.
