### ISSUE TITLE
Added Feature: "New Script" Context Option for FileSystem Docker

### ISSUE THREAD

**Issue by TheYokai** [godotengine/godot#18435]
**Godot version:**
Master

**Description:**
I've added a new feature to my own version of the Godot Editor that allows you to create a new script from the FileSystem docker. I believe this helps to quickly make many scripts before attempting to attach them to a node, which ultimately allows you to work more top down. I'm sorry if this is a bit unorthodox for contributing a feature by implementing it myself right away, but since I added this feature for myself I thought I would offer the changes upstream as well (if the team is interested in this feature.)

![gdt_patch_filesystem-new-script](https://user-images.githubusercontent.com/3040352/39283879-4cf83510-48c5-11e8-87e5-6fdec787535f.png)

As you can see, it uses the pre-existing create-script dialog box so most of the code added to this patch is minor. This also means it works as you would expect it to, and allows you to create VisualScript and other script types. You can try the patch file below:

[patch_filesystem_docker_new_script_option.txt](https://github.com/godotengine/godot/files/1949569/patch_filesystem_docker_new_script_option.txt)

Minor code changes thanks to how clean most of the code is to begin with. 😃

**Comment by TheYokai** [comment]
So should I go ahead and do a pull request with this change in the patch?

**Comment by bojidar-bg** [comment]
@TheYokai Yes, a pull request is going to be reviewed and merged faster than a patch file.

**Comment by TheYokai** [comment]
Ok, I'll get on that today then.

**Comment by groud** [comment]
This is implemented on master now, closing. Thanks !
