### ISSUE TITLE
"Load as placeholder" state not copied on duplication

### ISSUE THREAD

**Issue by yscik** [godotengine/godot#18431]
**Godot version:** 3.0.2

Looks like it was fixed once for 2.1 but lost in the rewrite:
https://github.com/godotengine/godot/pull/7671

It would also be nice to be able to set the "Load as placeholder" state for multiple selected nodes. 

**Steps to reproduce:**
- Check "Load as placeholder" on a node in the scene tree
- Duplicate it with Ctrl+D

**Comment by Calinou** [comment]
I can reproduce this in Godot 3.2.2beta4.
