### ISSUE TITLE
gles2 renderer/Shading language `undefined variable "screen_uv"`

### ISSUE THREAD

**Issue by enthus1ast** [godotengine/godot#18439]
**Godot version:**

29b8364ef09f32467070ac34051f2bc2e2d84ebf

**OS/device including version:**

```
Linux eb 4.16.2-2-ARCH #1 SMP PREEMPT Tue Apr 17 19:37:34 UTC 2018 x86_64 GNU/Linux
```

```
01:00.0 VGA compatible controller: NVIDIA Corporation GK104GLM [Quadro K3000M] (rev a1)
```

**Issue description:**

I'm testing a 2d project which works on the gles3 renderer
with the new gles2 renderer.

But the shader 

```c
void fragment() {
	vec4 pixelColor = texture(SCREEN_TEXTURE,SCREEN_UV);  // <- this seems to fail
	//vec4 pixelColor = textureLod(SCREEN_TEXTURE,SCREEN_UV, 0.1); # failes as well
	//vec4 pixelColor = vec4(0.5); // this works
	COLOR = brightnessMatrix( brightnessFac ) * contrastMatrix( contrastFac ) *  saturationMatrix( saturationFac ) * pixelColor;
}
```

failed to compile and outputs:  

```
0:00:00:0676 - CanvasShaderGLES2: Fragment shader compilation failed:
0(161) : error C1008: undefined variable "screen_uv"

----------
Typ:Fehler
Beschreibung: 
Zeit: 0:00:00:0676
C Fehler: CanvasShaderGLES2: Fragment shader compilation failed:
0(161) : error C1008: undefined variable "screen_uv"

C Quelle: drivers/gles2/shader_gles2.cpp:425
C Funktion: get_current_version
```

and a lot of

```
0:00:00:0680 - GL ERROR: Source: OpenGL	Type: Error	ID: 1282	Severity: High	Message: GL_INVALID_OPERATION error generated. No active program.
----------
Typ:Fehler
Beschreibung: 
Zeit: 0:00:00:0680
C Fehler: GL ERROR: Source: OpenGL	Type: Error	ID: 1282	Severity: High	Message: GL_INVALID_OPERATION error generated. No active program.
C Quelle: drivers/gles2/rasterizer_gles2.cpp:111
C Funktion: _gl_debug_print
```

**Steps to reproduce:**
start the attached project with gles2 renderer

**Minimal reproduction project:**

[minimalshader.zip](https://github.com/godotengine/godot/files/1950982/minimalshader.zip)

**Comment by Noshyaar** [comment]
cc: @karroffel

**Comment by Zireael07** [comment]
When did you last merge from his gles2 branch? Commits say he implemented it 9 days ago...

**Comment by karroffel** [comment]
Yup, as @Zireael07 said, it's implemented on my branch, it's just not merged here. But `SCREEN_TEXTURE` doesn't work yet, some code is there already (but commented out), but it's buggy so it's just not supported for now. Will come soon :tm:

**Comment by MarianoGnu** [comment]
is this fixed now that the GLES2 branch has been merged?

**Comment by karroffel** [comment]
SCREEN_UV should be fine, SCREEN_TEX not :/

**Comment by akien-mga** [comment]
`SCREEN_TEXTURE` is tracked in #21899, so closing this one.
