### ISSUE TITLE
3D Editor fails to move points after scaling the Path Node

### ISSUE THREAD

**Issue by davi2205** [godotengine/godot#18432]
**Godot version:**
3.0.2 (32 bits)

**OS/device including version:**
Windows 8 64 bits

**Issue description:**
After applying any scaling operation on the Path node the 3D editor becomes unable to move any points of the curve, it does move sometimes, but most of the time it doesn't. The problem solves itself once I reset the Scale to [1, 1, 1]. The editor is not picking those curve point dots properly. The other Transform properties like Translation and Rotation does not seem to cause problems.

**Steps to reproduce:**
![before](https://user-images.githubusercontent.com/12879282/39277726-a6973fbc-48c5-11e8-90f7-ab51b6ae3606.PNG)
![after](https://user-images.githubusercontent.com/12879282/39277731-ab928e18-48c5-11e8-9d69-7698bfcb8e99.PNG)

**Comment by cchipont** [comment]
Confirm still present in 3.1

**Comment by KoBeWi** [comment]
Works fine in 3.2
