### ISSUE TITLE
Script Inheriting Goes Wrong

### ISSUE THREAD

**Issue by WouterB15** [godotengine/godot#18446]
Godot v3.0.2
Windows 10

I was just copying some some code from one script to the other to make it better. After I tried it launch it gave me this error:
`Script inherits from native type 'Reference', so it can't be instanced in object of type: 'Node'`
I've looked around the internet for this, but I couldn't find anything useful.

What are possible causes of this? I can't find anything wrong with the script itself.

Project:
[Project.zip](https://github.com/godotengine/godot/files/1964004/Project.zip)

**Comment by vnen** [comment]
The script starts with `extends` follow by the type. If the type does not match the object you're assigning it too, you'll get this error. If it does not have the `extends` statement, it'll inherit from Reference by default.

BTW, this GitHub tracker is for bugs/proposals, if you need general help you can go to any of our [community channels](https://godotengine.org/community).

**Comment by WouterB15** [comment]
I have checked all of the '`extends`', but they're all correct. I've also never changed any of them since creating the script. 

Sorry for posting this in the wrong place.

**Comment by volzhs** [comment]
You can attach minimal sample project to reproduce it.

**Comment by volzhs** [comment]
isn't it exported project?
I can't check with attached project.

**Comment by WouterB15** [comment]
I attached it to the comment I posted. But I'll put it in the main 'issue' too.

**Comment by volzhs** [comment]
I downloaded it from your comment.

**Comment by WouterB15** [comment]
I both zips to be a manually created zip instead of an exported one by Godot. You should be able to extract it and open it in Godot.

**Comment by volzhs** [comment]
can't open the zip file

**Comment by WouterB15** [comment]
I assume you have Winrar installed? I can download it and open it perfectly fine.

**Comment by WouterB15** [comment]
I found the issue! It turns out that there was a script still attached to a node, which I had deleted because I didn't need it anymore. After I had deleted it I forgot to remove the script from the node.
