### ISSUE TITLE
Some skeleton bones missing in the viewport

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot#18443]
**Godot version:** 

3.0

**OS/device including version:**

 macOS High Sierra 10.13.3

**Issue description:** 

 I have a simple scene with only one mesh and one skeleton. 
![rest](https://user-images.githubusercontent.com/19422835/39307358-2b95a4a4-4995-11e8-997a-179d90afa16b.jpg)

the skeleton has two bones, but only one bone is displayed in viewport.
the missing bone looks like that in Blender: 
![blender](https://user-images.githubusercontent.com/19422835/39308082-20e91f2a-4997-11e8-85d6-e9bb979e913f.jpg)

To prove the the missing bone functionally works,   I changed the pose matrix and the mesh deformed correctly, so it may be a bug with bone display.
![pose](https://user-images.githubusercontent.com/19422835/39307505-9110ff72-4995-11e8-8900-f81988750a13.jpg)

**Steps to reproduce:**
open the tscn I attached

**Minimal reproduction project:**

[just_armature.tscn.zip](https://github.com/godotengine/godot/files/1951268/just_armature.tscn.zip)

**Comment by jotson** [comment]
I'm seeing this same issue in 3.1 alpha 1. Further, creating a physical skeleton also only creates nodes for the visible bones.

4 bones in blender
![Blender](https://user-images.githubusercontent.com/1168026/44926255-b224d480-ad05-11e8-9603-d5af1ce4640e.png)

Only 3 bones are visible in Godot and only 3 physical bones are created for the skeleton
![Godot 3.1 alpha 1](https://user-images.githubusercontent.com/1168026/44926259-b650f200-ad05-11e8-882d-ccf2e8c271fe.png)

**Comment by AndreaCatania** [comment]
When Godot imports the skeleton it is missing the information of last bone tip, so it's impossible to know the length so draw it it's not possible.

This doesn't mean that last bone doesn't exist, it exist and can deform the mesh.

**Comment by jotson** [comment]
You can't create a physical bone for the missing bone. That makes using ragdolls difficult. Are you saying that this isn't a bug? Seems like it should be possible to draw all the bones.

**Comment by AndreaCatania** [comment]
Nothing stop you to add manually a physical bone to the last bone, you know the correct size to use for the last bone.

From Godot prospective it's possible to create a physical bone and / or draw the last bone with a fixed size, but it should be discussed.

Said that, I really don't like this behaviour but seems that collada format doesn't have this information.

**Comment by jotson** [comment]
The collada file in my upload does seem to have all of the info for four bones. But only 3 show up in Godot.

**Comment by AndreaCatania** [comment]
upload it please

**Comment by jotson** [comment]
I did. It's here in this bug with my original comment: https://github.com/godotengine/godot/issues/18443#issuecomment-417731294

It's in the zip file. I used the better collada exporter.

**Comment by AndreaCatania** [comment]
Yes you right, so collada is not the problem. The problem is on how godot store it.

Add another transform is not the best solution I need to check the skeleton code again

**Comment by jotson** [comment]
I really appreciate you looking at this. Thank you!

**Comment by glaforte** [comment]
Hello :) There seem to be two problems discussed in this issue.

1) Does the last bone actually export and is accessible in Godot, in the imported Skeleton node? I confirmed with John's data and this part works as expected, today. Maybe it failed earlier in the year?

2) Does the last bone appear in the Viewport, providing important visual feedback to the user? I was also surprised by this issue a few weeks back. I've reviewed how Blender and Godot define a bone. In Blender, a bone is defined as two points in space. This inherently gives a length to the bone. In Godot, a bone is defined as a transform in space, so there isn't this idea of how long a bone is. This "bone-length" information is rebuilt in Godot when a bone has children, but isn't generated for end bones. As @AndreaCatania mentioned: this length information is necessary to draw the bone reliably.

The COLLADA file format also defines a bone as a transform in space, so the 'bone-length' information isn't available in the standard file format for the importer. There's different ways that this situation can be improved with more data, but it would require more user input and/or changes to the Blender COLLADA exporter. More importantly, the way Godot draws bones would have to change as well.

@akien-mga I suggest this issue should be labeled : "featurerequest" and "topic:editor".

**Comment by Two-Tone** [comment]
What about appending the length to the name of the bone on export, then on import Godot can use that to apply the proper length and remove that info from the name? 

In the mean time, a simple workaround is to add a new bone to the end of the missing bones.

I do have a question though. This may be a bug (if it is, I'll open a new issue), but the collision shapes generated with the physical skeleton are suppose to transform with their bones, right? They're currently not but the bones are.

**Comment by glaforte** [comment]
> I do have a question though. This may be a bug (if it is, I'll open a new issue), but the collision shapes generated with the physical skeleton are suppose to transform with their bones, right? They're currently not but the bones are.
I'm afraid I'm not familiar with the feature of physical skeletons. Maybe opening a new issue would be best :)

**Comment by reduz** [comment]
This is not really a bug, the actual information for the last bone (and free bones) is lost in exchange formats such as Collada or GLTF.

I think the Godot -> Blender exporter could actually save a length or whether it's a free bone (which we add in Skeleton for display purposes)

**Comment by Jason0214** [comment]
@reduz, so does Skeleton node already has properties like `bone length` which we can use to specify the length of the last bone? or there is some work need to be done at Godot side to support it?

**Comment by akien-mga** [comment]
Is this still reproducible in 3.2 beta 5 / with the latest Blender exporter?

**Comment by jotson** [comment]
1. I downloaded the latest https://github.com/godotengine/godot-blender-exporter and installed it in Blender 2.81.16
2. I loaded the original fish.blend in the zip I uploaded here https://github.com/godotengine/godot/issues/18443#issuecomment-417731294
3. I exported from Blender using the Blender Exporter
4. I double clicked the exported .escn file in Godot 3.2 beta 5 (downloaded release, not built from master) and created a new inherited scene
5. I selected the fish skeleton in the scene tree, clicked the Skeleton button, then clicked Create physical skeleton

Result:

- 4 bones show up in the inspector for the skeleton just as I expected
- Only the first 3 bones are visible in the viewport but I expected to see 4 bones
- Only the first 3 physical skeleton bones were created but I expected 4 physical bones

![screenshot-2020-01-05T10:07:07](https://user-images.githubusercontent.com/1168026/71784052-bf11a200-2fa3-11ea-825f-332d831a5c4c.png)

**Comment by fire** [comment]
Is this an issue affecting Godot Engine 3.2?

**Comment by Calinou** [comment]
@fire I guess it still affects Godot 3.2. While glTF 2.0 is now the preferred workflow, we still support Collada for now.

**Comment by 19PHOBOSS98** [comment]
and 3.2.1 :(

**Comment by fire** [comment]
> 
> 
> This is not really a bug, the actual information for the last bone (and free bones) is lost in exchange formats such as Collada or GLTF.
> 
> I think the Blender -> Godot exporter could actually save a length or whether it's a free bone (which we add in Skeleton for display purposes)

According to @reduz quotes above this is working as intended. I don't expect this bug to be changed to expected behavior because information has been lost.

**Comment by TheContainer** [comment]
So how exactly is this intended behaviour? Why do you want this to happen?

**Comment by AThousandShips** [comment]
@TheContainer please read the conversation, it isn't "as we want it" but a limitation due to loss of information
