### ISSUE TITLE
Folder created from Godot with trailing space is broken on Windows

### ISSUE THREAD

**Issue by ecoludology** [godotengine/godot#18457]
**Godot version:**
v3.0.2.mono.official

**OS/device including version:**
Windows 10 Home
version 1709

**Issue description:**
Creating a new folder when creating a new project results in an unusable folder, broken in the OS.

When creating a new folder I created a folder with the create new folder button (I also used the browse button, and created a new folder in there, which also had the same issue).
I can not create a project in that folder.
I can navigate to that folder in windows explorer, but I can't rename it, delete it, or look at its security settings. 
I believe the problem is that it has a special character in the file name - I think it's been added as a trailing character. In the command prompt, my folder name showed up as "Polycule Editor ", but even there, I couldn't remove the folder.

Steps to remove folder for those with the same problem:
In command prompt, go to the containing folder.
"dir /x" to find the 8.3 name of the folder.
"rd /s /q POLYCU\~1" replacing POLYCU\~1 with the 8.3 name of your folder

**Steps to reproduce:**
Open Godot project manager
Click New Project
Enter a name (mine had a space) and click Create Folder

**Minimal reproduction project:**
Happens before getting to the point where a project is created.

**Comment by ecoludology** [comment]
Apparently the tilde character is markdown for underscore. Sorry.

**Comment by akien-mga** [comment]
Fixed by #18552.
