### ISSUE TITLE
Write alpha in canvas item shader to viewport as is

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#18462]
I couldn't find an option for this so I'm guessing these needs to be added to the shader logic. 
I would like to add a render_mode to custom canvas_item shaders that allows you to write the color as is to a viewport even if the alpha isn't 1. 
So in essence, just disabling GL_BLEND before rendering.

The use case here is when using a viewport as a render target being able to write values into the alpha channel of the render target.

**Comment by Zylann** [comment]
You're almost walking the same path as me^^
See https://github.com/godotengine/godot/issues/10255

**Comment by BastiaanOlij** [comment]
@Zylann well we are both busy on terrains, I've been trying to find you on IRC so I can give you a copy of what I'm doing :)
