### ISSUE TITLE
Export not working if target name is not valid

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#18469]
Godot Master

Exporting with command line leads to separate file placement when target file is wrong.

**Reproduce**
1. Switch to project folder run this
`godot --export "Linux/X11" ./../exports/test`

**Result**
 ./../exports/test
 ./..pck

**Expected**
 ./../exports/test
 ./../exports/test.pck

The correct command is
**X11**
`godot --export "Linux/X11" ./../exports/test.x86_64`
**Windows**
`godot --export "Linux/X11" ./../exports/test.exe`

**Comment by bojidar-bg** [comment]
Found the bug: String::get_basename and String::get_extension are having trouble with files not having an extension.
Going to make a PR.

**Comment by akien-mga** [comment]
Fixed by #18520.
