### ISSUE TITLE
Quick function list does not sort functions in alphabet order.

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#18461]
**Godot version:**
3.0.2

**OS/device including version:**
no matter

**Issue description:**
The quick function list in GDScript editor is very useful, but it not sorting functions in alphabet order which cause problems when file is huge and contains a lot of functions..

![image](https://user-images.githubusercontent.com/3036176/39351944-d3e8018a-4a0b-11e8-9c94-10f5ae72207d.png)

**Comment by Zireael07** [comment]
The quick function list shows functions in the order that you have them in the file.

**Comment by Chaosus** [comment]
Probably extra sort button is required.

**Comment by groud** [comment]
This is done by #18442
