### ISSUE TITLE
input_event Signal Doesn't Work While Paused Although PauseMode is Processing

### ISSUE THREAD

**Issue by Supatier** [godotengine/godot#18474]
**Godot version:**
3.0.2

**Issue description:**
My scene is set to paused with `get_tree().paused = true`. My `area`'s pause mode is set to `processing`. I have a signal to a script which is located on my `area` node. Everything should work fine.

**Steps to reproduce:**
Run project.
If you disable `get_tree().paused = true`, it would trigger the signal.
if you enable `get_tree().paused = true`, it won't work.

**Minimal reproduction project:**
[junk.zip](https://github.com/godotengine/godot/files/1957190/junk.zip)

**Comment by panzergame** [comment]
It looks like `_input` event is triggered but not `_input_event`.

**Comment by reduz** [comment]
_input_event no longer exists in Godot 3, use _gui_input instead

**Comment by Supatier** [comment]
Yes, but, any examples to port my project?

I just need to get my mouse's vector 3 coordinates in 3D space.

**Comment by Supatier** [comment]
Any workaround

**Comment by Supatier** [comment]
@reduz If I pause may game, does that mean the physics server is paused?
If so, how do I make parts of it unpaused?

**Comment by Supatier** [comment]
Closing as this is not a real issue.
