### ISSUE TITLE
vector.length() and vector.normalized() functions

### ISSUE THREAD

**Issue by poeaod** [godotengine/godot#18472]
OS = Windows 7

I've found some possibly unintended behavior with how the vector.length() and vector.normalized() functions interact.  I'm not sure if it's just unavoidable floating point nonsense, or problems with the code, or otherwise.  But here it is:

```
extends Node
var vector = Vector3(2,2,2)

func _physics_process(delta):
	var y_vec = vector.y
	vector.y = 0

	var length = vector.length()
	print(length)
	
	#weird behavior is here
	vector.normalized()
	#vector /= vector.length()
	
	vector.x = vector.x * length + delta 
	vector.z = vector.z * length
	
	#weird behavior is here
	vector.normalized()
	#vector /= vector.length()
	
	vector.x *= length
	vector.y = y_vec
	vector.z *= length
```	

Running this script as is on my system causes the length of the vector to go off to infinity.  If I comment the two `vector.normalized()` lines out, and uncomment the two `vector /= vector.length()` lines in then `length` will stay the same, as it should.

**Comment by vnen** [comment]
`vector.normalized()` will not change the original vector, it returns a new one (which you are discarding in this sample). You need to do `vector = vector.normalized()`.

**Comment by poeaod** [comment]
Aha!  I see now.  I was emulating code from another engine which changes the original vector and returns its length from the normalized function.  I should have looked at the Godot API more closely  -_-  Are there any advantages to using `vector = vector.normalized` over `vector /= vector.length()`?

**Comment by vnen** [comment]
`vector = vector.normalized()` is clearer and probably has better performance since you do less operations in the script.
