### ISSUE TITLE
Command line export prints unspecific error if template missing

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#18470]
Godot Master

Happens with Linux and Windows probably the others too.

**Command**
`godot_server.server.tools.64 --export "Windows Desktop" ./../exports/test.exe`

`ERROR: copy: Failed to open` - means the templates are missing(in my case). It would be nice to get a more specific error message.

```
./godot_server.server.tools.64
ERROR: copy: Failed to open 
   At: core/os/dir_access.cpp:304.
ERROR: _fs_changed: Project export failed with error code 12.
   At: editor/editor_node.cpp:494.
```

**Comment by akien-mga** [comment]
Reverted with 007d1754e, I'll work on a better error handling.

**Comment by AlexHolly** [comment]
@h4de5 Are you on a linux mashine? Ans master branch?

 ~/.local/share/godot/templates/3.1.dev/

**Comment by h4de5** [comment]
@AlexHolly : thank you, very much! i just managed to get a valid export on WSL (ubuntu 18.03) using your path and the older 3.0.2 version. it seems its broken from 3.0.3 onwards... took me a while.

**Comment by akien-mga** [comment]
Still fails the same way in the current master branch.
