### ISSUE TITLE
CSG: subtraction result doesn't appear in editor viewport until the scene is reloaded

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#18473]
**Godot version:**

8d199a9

**OS/device including version:**

Antergos x86_64

**Issue description:**

Expected: A CSGBox subtracted by another CSGBox result shown in the editor viewport
Happened: It appears as if the subtraction didn't happen, but when run, it's subtracted correctly.

(This can be workaround by save, close, reload scene.)

In editor
![image](https://user-images.githubusercontent.com/26753932/39391111-b68a072e-4ac8-11e8-9a7d-7874fc4a6120.png)
In game
![image](https://user-images.githubusercontent.com/26753932/39391120-d084e536-4ac8-11e8-92f1-b53497dc7f47.png)

**Steps to reproduce:**
1. New CSGCombiner, & 2 new CSGBox children
2. Set 2nd one to subtract & slight offset
3. Editor shows no subtraction
4. Add a camera and run the scene
5. Shape is subtracted correctly

**Minimal reproduction project:**

<details>

```
[gd_scene format=2]

[node name="CSGCombiner" type="CSGCombiner" index="0"]
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 0.118509, 0, 0 )
layers = 1
operation = 0
use_collision = false
snap = 0.001

[node name="CSGBox2" type="CSGBox" parent="." index="0"]
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, -1.66656, 0, 0 )
layers = 1
operation = 0
use_collision = false
invert_faces = false
width = 1.0
height = 1.0
depth = 1.0
material = null

[node name="CSGBox" type="CSGBox" parent="." index="1"]
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, -0.87969, 0.433939, 0.529962 )
layers = 1
operation = 2
use_collision = false
invert_faces = false
width = 1.23616
height = 1.0
depth = 1.0
material = null

[node name="Camera" type="Camera" parent="." index="2"]
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 6.94839 )
keep_aspect = 1
cull_mask = 1048575
environment = null
h_offset = 0.0
v_offset = 0.0
doppler_tracking = 0
projection = 0
current = false
fov = 70.0
size = 1.0
near = 0.05
far = 100.0
```

</details>

**Comment by Noshyaar** [comment]
Can't reproduce anymore.

**Comment by sketchyfun** [comment]
You may have encountered the same problem as me, and thats when you create a CSG node and then re-parent it. I'll open a ticket for it
