### ISSUE TITLE
Godot Engine runs slow

### ISSUE THREAD

**Issue by DroidPlayer12** [godotengine/godot#18486]
Hello,

So i have the problem that godot runs slow like 15fps (Estimated) and it runs slower when using tilemap editing

**Godot version:**
3.0.2

**OS/device including version:**
Windows 10
CPU: i3 3220
RAM: 8gb 1600mhz DDR3 Ram
GPU: asus radeon hd 6850 Directcu
Mainboard: ASRock H61M-GS

*i didnt use a big project

**Comment by Zylann** [comment]
Godot runs decently on my computer, but I noticed slowness too in tilemap editing: https://github.com/godotengine/godot/issues/12391

**Comment by girng** [comment]
6850 and i3 3220...

**Comment by QbieShay** [comment]
Hi @DroidPlayer12, this could be a graphic driver issue. Are your graphic drivers up to date?

**Comment by DroidPlayer12** [comment]
No i have the newest drivers available

**Comment by kubecz3k** [comment]
@DroidPlayer12 Can you tell if there is any significant difference between 2.x and 3.x version of Godot?

**Comment by Chaosus** [comment]
Just another driver-related issue.. Godot is not slow if you use fresh drivers, non-damaged hard drive and your system is not under virus attack. Closed, also because the discussion is stopped
