### ISSUE TITLE
Setting up the minimal LOD to use

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18484]
For the Fortnite port to mobile, Epic Games used a feature of UE4 that allows to setup the most detailed LOD to display. Instead of using the LOD0 of PC for assets that are close to the camera, they display the LOD1, this allowed them to quickly optimize the polycount of the game for the mobile version.

I suggest to add this option in Project Settings quality:
- Minimal LOD: LOD0

Maybe their should be two options:
- Minimal LOD for PC
- Minimal LOD for WebGL and Mobile

**Comment by Calinou** [comment]
A "LOD bias" option sounds good to me.

> Maybe their should be two options:
>
> - Minimal LOD for PC
> - Minimal LOD for WebGL and Mobile

You can use [feature tags](http://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html) to accomplish this – there is no need to create dedicated settings here.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/692, as feature proposals are now tracked on the Godot proposals repository.
