### ISSUE TITLE
[proposal] please consider adding open sound control nodes in godot 3

### ISSUE THREAD

**Issue by shimpe** [godotengine/godot#18483]
See e.g. https://github.com/djiamnot/gdosc . Their project seems to work quite well already, integrates nicely in godot 3, and it opens up godot to an entire new audience by allowing godot to be used as a remotely controlled graphics canvas for art installations, as well as a simulation environment that sends feedback to e.g. generative sound programs (e.g. collision information).

**Comment by akien-mga** [comment]
That's a cool feature but much better suited maintained as a thirdparty GDNative module than integrated in the core, as it's very tangential to the needs of regular game developers. If ported to GDNative, binaries could be distributed in the Asset Library for plug 'n play in Godot.

**Comment by shimpe** [comment]
I just wanted to add that tagging this proposal "topic:audio" is quite misleading, as the possibilities go much further that just sound. 

Open Sound Protocol, despite the name, is a flexible general purpose inter process communication protocol (based on UDP), which can be used to pass any kind of info between processes, also if those are running on different PCs in a network.  And as a bonus it's extremely easy to use...
