### ISSUE TITLE
NetworkedMultiplayerENet signals do not fire with Mono/C#

### ISSUE THREAD

**Issue by lordee** [godotengine/godot#18498]
**Godot version:**
git commit 7d6f210ccb5de9ef414f94ad42f9f3dea14c0493

Xubuntu 17.10

**Issue description:**
Signals such as "connected_to_server", "network_peer_connected", "network_peer_disconnected" do not fire methods, however "connection_failed" does.

I have attached a minimal project to demonstrate.  Press create server, open another copy of project, press create client.  Eventually connection_failed will fire method.  If instead you stop version running server, you will see (for me, in terminal):
Nothing read: Connection reset by peer
ERROR: read: Server disconnected!
   At: drivers/unix/stream_peer_tcp_posix.cpp:276.

I have also tested by adding to end of _on_CreateClient_pressed() in attached project a fake RPC: RpcId(1, "myfakemethod");

This causes an error for attempting to RPC without an error, however then a connection is made and "connected_to_server"/"network_peer_connected" signal is called:

Server view:
on_CreateServer_pressed
Creating server on port 27500
Server Created
_player_connected: 891357087

Client view:
Client connecting server
ERROR: _send_rpc: Attempt to remote call/set when networking is not connected yet in SceneTree.
   At: core/io/multiplayer_api.cpp:334.
_player_connected: 1
_connected_ok
[example.tar.gz](https://github.com/godotengine/godot/files/1958589/example.tar.gz)

**Comment by QbieShay** [comment]
@Faless

**Comment by hungrymonkey** [comment]
I wonder if this problem is mono related.

**Comment by Faless** [comment]
> I have also tested by adding to end of _on_CreateClient_pressed() in attached project a fake RPC:

That is wrong, at the end of the function the client is not yet connected, put it in `_connected_ok` function.

Events seems to fire fine in GDScript, so as @hungrymonkey said, it appears to be a problem related to the mono part.

@lordee can you try the [GDScript ported version](https://github.com/godotengine/godot/files/1970774/openFortressGDScript.zip)?

**Comment by lordee** [comment]
@Faless The _connected_ok function is never called if I do that, eventually only the _connected_fail function is called.

I'll try the GDscript version this weekend and report back

**Comment by lordee** [comment]
@Faless I can confirm the gdscript version works with my install.  So on that note, I went and updated mono and I can no longer reproduce the bug.

**Comment by mhilbrunner** [comment]
FYI, taken from Discord's #csharp, may help somone:
![enet_mono](https://user-images.githubusercontent.com/1654763/39683766-928e1946-51b7-11e8-9657-8f2db145c8c0.PNG)
