### ISSUE TITLE
deep in scene tree TextEdit and LineEdit doesn't work ( can't focus on them to type in them)

### ISSUE THREAD

**Issue by babak-karimi-asl** [godotengine/godot#18492]
**Godot version:**

3.0.2 stable

**OS/device including version:**

Lubuntu 16.04

**Issue description:**

for example look at the todo object in my simple productivity app , it's a LineEdit , and when i play the app , i can't input any text in it 
![2018-04-28-225610_1366x768_scrot](https://user-images.githubusercontent.com/31150843/39399681-7d4cbeba-4b37-11e8-8009-f2604f9a5793.png)

**Steps to reproduce:**

**Minimal reproduction project:**

it's a simple project . i uploaded it completely. 
[oneMinuteTwoMinute.zip](https://github.com/godotengine/godot/files/1958036/oneMinuteTwoMinute.zip)

**Comment by girng** [comment]
is there a parent node's control that is over it? if so, you need to set that control's mouse_filter to 0

**Comment by CowThing** [comment]
I downloaded the project and looked at it. The LineEdit node's mouse filter was set to "Ignore", so it didn't accept any mouse inputs. Changing it to "Stop" allowed me to click on it and start typing just fine.

**Comment by babak-karimi-asl** [comment]
@girng , @CowThing  thank you both . my mistake . problem solved . 

@CowThing  Wow! you are so productive . the last game i saw from you was "Mouse Bot" which i loved .
cant wait today after work to see your new works . Love your work . keep going.
