### ISSUE TITLE
Update rate capped to 60 times per frame when going into fullscreen

### ISSUE THREAD

**Issue by k4sma** [godotengine/godot#18497]
Godot version 3.0.2

When I turn on fullscreen and enable the "print fps" in the project settings, the update rate seems to be capped at 60 times/second. Vsync is disabled in graphics settings and in project settings as well. Also happen when setting resolution to screen resolution and enabling "borderless"

**Steps to reproduce:**
-create empty project
-enbale "print fps" in project settings
-turn off vsync
-enable fullscreen

**Comment by guilhermefelipecgs** [comment]
> When you go into fullscreen mode, does it still print out a higher fps than 60?

Yes, my fps is above 5000 on fullscreen, but I just tested it on Linux, I need to test it on windows now.

**Comment by k4sma** [comment]
Ok, so I tested it on linux and I have no issues whatsoever. High fps when going fullscreen; I have no idea why this is happening on my windows machine..

**Comment by guilhermefelipecgs** [comment]
I tested on win10 here and I've no problem, probably it's something in your system.

Your machine is a notebook right? Maybe the problem could be something related with the optimus technology (maybe godot it's not using the nvidia). I don't have any hybrid GPU to test, so I can't help much.

**Comment by KoBeWi** [comment]
@k4sma Did you try what the comment above said? (or you can try Godot 3.2.1 too)

I tested with GTX 1060 on Windows 10 and don't have this issue either.

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
