### ISSUE TITLE
Inconsistent is_pressed() function on Joy and Keyboard

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#18500]
**Godot version:**
3.0.2

**Issue description:**
The handling of key press and joy button press is inconsistent:

KEY: an event is fired every frame that a key is down.  In order to check if it was just pressed, it's needed to use the is_echo() function
JOY: an event is fired **only** when the key is pressed the first time, forcing the user to keep a bool variable to know if the button is down or not.

Would be nice to have the same api for both. The key one is more expressive and gives more control, so i'd like the joy to use the same convention.

**Example code**

```gdscript
if (event is InputEventJoypadButton and event.button_index == JOY_XBOX_A and event.is_pressed()):
    print("joy pressed")
if(event is InputEventKey and event.scancode == KEY_V and event.is_pressed()):
    print("key pressed")
```

"joy pressed" will be print only when the button is first pressed, while "key pressed" will be print every frame.

**Comment by guilhermefelipecgs** [comment]
Maybe you already know this but If you really need more control I recommend use `Input.is_action_pressed("jump")` or `Input.is_action_just_pressed("jump")` inside `_process` or `_physics_process` instead `_input`. This method always return the same result independent of the device you're using.

**Comment by QbieShay** [comment]
Yes, but in my specific case I wanted to access the key directly and not use action :(

**Comment by vnen** [comment]
It's not "sent every frame", this happens because the OS keeps sending key events if you keep a key pressed, while a gamepad will only send one event if you keep a button pressed. So this is not a Godot function, it comes from the underlying system. You can even configure the repeat rate in your OS settings.

The `is_echo()` function is a convenience to help you avoid the repeated key events that the OS will inevitably send.

**Comment by guilhermefelipecgs** [comment]
> Yes, but in my specific case I wanted to access the key directly and not use action :(

Like @vnen said, `_input` will always behave this way, but you can try with this two methods if you want to use the "keys": `Input.is_joy_button_pressed(0, JOY_XBOX_A)` and `Input.is_key_pressed(KEY_V)` (use inside `_process` and `_physics_process` to achieve the behavior that you described)

**Comment by QbieShay** [comment]
@vnen yes, but i assume Godot's role is to abstract OS and give a layer on top of that. What I am saying is that, in my opinion, would be better to have the same interface/behaviour.

@guilhermefelipecgs  thanks for the tip :)

**Comment by groud** [comment]
Well the problem is that we cannot abstract that unless we add another layer of event processing / filtering, which is basically what's done by the Input class. IMHO, I think keeping input events raw is better.
But in any case, I would personally completely remove the InputEventJoypadMotion.is_pressed(), since it does not really makes sense.

**Comment by vnen** [comment]
I think adding `and not event.is_echo()` is not such inconvenience if you are already testing for key events. OTOH if Godot filtered them out, it would be impossible to get the echo events if you wanted to.

Different devices have different interfaces, there's not much way around it. Actions are supposed to abstract that away, but if you don't want to use actions you'll need to deal with the differences, sorry.

**Comment by QbieShay** [comment]
@vnen there have been some interesting points in this issue.

I think the final difference is that I expected Godot to behave in a game-consistant way, while it is behaving instead in a system-consistant way.

This discussion boils down to this design decisions so, unless there is an interest from the Devs to continue discussing about it, I agree to close it.
