### ISSUE TITLE
CSG: Shapes created and then re-parented don't work correctly

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#18504]
**Godot version:**
Built from current master

**OS/device including version:**
Windows 7
GTX 760

**Issue description:**
Adding a CSG shape to the root of a scene, setting the operator, and then re-parenting it to another CSG shape results in the operation not working in the editor (it seems okay when the scene is run).

**Steps to reproduce:**
- Add spatial root node
- Add CSG shape
- Add another CSG shape to the root of the scene and set it's operation to subtract or intersect
- Reparent that CSG shape to the first one and notice how it has the incorrect effect

**Minimal reproduction project:**

**Comment by Bauxitedev** [comment]
I've noticed the same issue. You can work around it by closing the scene and then opening it again.

**Comment by fire** [comment]
Happens to me too.

**Comment by Zireael07** [comment]
Same thing happened to me when I added a CSG scene to another scene.
