### ISSUE TITLE
Consider moving godot's build system to Bazel

### ISSUE THREAD

**Issue by fire** [godotengine/godot#18518]
See https://github.com/godotengine/godot/issues/16014

Rather than repost the reason why the build Bazel system is good, I've forked godot to use bazel.

It currently is barebones, but the editor is able to launch without icons nor gdscript. The build is much faster on both initial and rebuilds compared to scons.

![godot_2018-04-29_17-41-12](https://user-images.githubusercontent.com/32321/39412645-8abb415a-4bd4-11e8-8b42-596ea20b6af8.png)

https://github.com/fire/godot/blob/bazel/BUILD

This is the current script.

Instructions to setup. 

* assume visual studio 2017 is installed
* git clone https://github.com/fire/godot.git -b bazel
* scons p=windows
* Modify platform/register_platform_apis.gen.cpp
```cpp
#include "register_platform_apis.h"

void register_platform_apis() {
}

void unregister_platform_apis() {
}
```
* Install bazel
`choco install bazel -y`
* bazel build godot

Note that the current setup uses scons to generate generated cpp files and is not a complete solution, but maybe others can expand on it.

Can someone post some times for a build?

**Comment by Redwan13** [comment]
Any progress?

**Comment by fire** [comment]
I have not worked on it since because there has been no feedback.

Since you're the first to contact me, would you able to help test the bazel build?

**Comment by Redwan13** [comment]
OK. To be truthful I tried to solve the same problem from the other end recently. I have BUILD files for godot_headers and godot-cpp, but I couldn't correctly export symbols from nativescript library with my project.

**Comment by Redwan13** [comment]
Execution time on my windows machine for clear build

scons --debug=time platform=windows
```
scons: done building targets.
Total build time: 840.135720 seconds
Total SConscript file execution time: 9.602505 seconds
Total SCons execution time: 31.972438 seconds
Total command execution time: 798.560776 seconds
```

Building with bazel: 

```
INFO: Elapsed time: 138,730s, Critical Path: 31,21s
INFO: 712 processes: 712 local.
INFO: Build completed successfully, 718 total actions
```
Editor successfully starts. I can try also on mac os x.

**Comment by fire** [comment]
This is a BUILD file for a native script library. https://github.com/fire/com-chibifire-fbx-plugin/blob/master/BUILD I hope it is helpful.

**Comment by fire** [comment]
I updated bazel to latest git master.

The editor starts but isn't really usable yet. There needs to be some work.

**Comment by fire** [comment]
It seems like the cmake version is more up to date. I'll close this.
