### ISSUE TITLE
Godot editor player doesn't open unless using an external monitor

### ISSUE THREAD

**Issue by Dakkers** [godotengine/godot#18513]
**Godot version:**

3.0.2

**OS/device including version:**

![image](https://user-images.githubusercontent.com/5009136/39409332-53977908-4bb3-11e8-87db-a18f771d805a.png)

**Issue description:**

Player (game?) doesn't open from the editor when hitting the "Play" button when I'm just using my laptop. If I put the editor on my external monitor and hit "Play", it appears. It seems as if, in the former scenario, nothing really runs because there is no output. There's some output with the monitor, though. Additionally, the game window appears at the very bottom of the monitor...

![image](https://user-images.githubusercontent.com/5009136/39409363-b05ca1d6-4bb3-11e8-8e86-56c9399cf8e1.png)

**Steps to reproduce:**
Hit "play"

**Minimal reproduction project:**

[game2.zip](https://github.com/godotengine/godot/files/1959010/game2.zip)

**Comment by Calinou** [comment]
> Additionally, the game window appears at the very bottom of the monitor...

This is a known issue, see #16570.

**Comment by Dakkers** [comment]
Ok, good to know. Any thoughts on the play button itself not doing anything? 😭

**Comment by Calinou** [comment]
@Dakkers Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
