### ISSUE TITLE
imporve uniform of shader language

### ISSUE THREAD

**Issue by ywaby** [godotengine/godot#18537]
1. default value dispaly in inspect windows
```c
uniform float zoom  =5.0;
```
2. hint_range support min value /max value 
```c
uniform float zoom : hint_range(0,FLOAT_MAX);
```
3. support default value set when set hint_range
```c
uniform float zoom : hint_range(0,1) =5.0;
```
4. hint_range support vec type
```c
uniform vec2 zoom : (hint_range(0,1), hint_range(0,1));
```

**Comment by swarnimarun** [comment]
I really like the idea but I think it will be easier to implement something like,
``uniform float zoom : hint_range(0, 1, default_value);
and for vecs,
``uniform vec2 zoom : hint_range(0,1,0,1);   // for x min, max and then y min, max

**Comment by ywaby** [comment]
already achieve at lastest build.
