### ISSUE TITLE
Swapping Audio Source with Logitech G930 Headset crashes/buzzes

### ISSUE THREAD

**Issue by Ceryni** [godotengine/godot#18536]
**Godot version:**
v3.0.2

**OS/device including version:**
Windows 10
Version 1709
OS Build 16299.371

**Issue description:**
Godot does not play well when swapping audio playback source devices. Maybe specific to my headset/speakers?
Results in either a crash of the editor or a permanent low tone buzzing until you close the whole editor.

**Steps to reproduce:**
I have a Logitech G930 Gaming Headset and a generic set of speakers.
1) Playback source is headset
2) open godot (just to project picker screen is sufficient)
3) Swap playback source to speakers
Results in Godot crashing

1) Playback source is speakers
2) open godot
3) Swap source to headset
Results in headset outputting a permanent buzzing tone

I've tested swapping from the rift headset audio to speakers and no issue, so I'm inclined to think it's specific to my headset. All drivers are up to date I believe. Low priority issue imo as well, just figured I'd report it for documentation's sake.

**Minimal reproduction project:**
N/A

**Comment by marcelofg55** [comment]
This should be solved already.

**Comment by vnen** [comment]
Closed since it's probably a duplicate and already fixed.
