### ISSUE TITLE
Windows Export should warn if custom resources are specified but rcedit isn't

### ISSUE THREAD

**Issue by AlanLynn** [godotengine/godot#18532]
**Godot version:** v3.02.stable.official

**OS/device including version:** Windows 10 64-bit

**Issue description:**
Expected behavior: Changing the Application settings in the export options should set the file attributes of the exported exe.
Actual behavior: File details are all set to the default values. If an icon is specified in the export options, it is not used.

**Steps to reproduce:**
1. Add a Windows Desktop export.
2. Set the Application options.
3. Click "Export Project" and save the exe.
4. Right click the exported exe then "Properties".
5. Switch to the "Details" tab.

**Comment by Calinou** [comment]
It is possible to change the application properties of Windows exports, but you need to download [rcedit](https://github.com/electron/rcedit/releases) and specify the path to the rcedit executable in the Editor Settings before exporting the project for Windows.

**Comment by KoBeWi** [comment]
Seems like this was implemented.
