### ISSUE TITLE
File Dialog's returned path does not account for suffix filter correctly

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#18534]
I could not find a duplicate, but I find it hard to believe this hasn't been encountered before. Then again most users are building games, not applications that might use this feature.

**Godot version:** 3.0.2

**OS/device including version:**
Linux Mint 17.3

**Issue description:**
If you include a suffix filter (simply called 'filter') to a FileDialog, it will allow the user to type in the name of the file they want to save and the suffix filter will be appended to the end of the file. As an example, let's say a file name is 'mydocument' in the file naming box and the filter is set to '.godoc'. The result _should_ be something like '/home/agameraaron/Documents/mydocument.godoc' that should be returned as the path. Instead, it misses the dot / period. It currently outputs to '/home/agameraaron/Documents/**mydocumentgodoc**'
No dot to separate the file suffix.

The consequence being is my program is slightly less fool proof if I disable filters as users can name to whatever format they want, yet only load in a certain type. If I keep it enabled, I'd have to make a small hack/workaround that just inserts the dot (which is what I'll do).

**Steps to reproduce:**
Use the file_selected signal on a FileDialog node. Use this code:
```
func _on_FileDialog_file_selected(path):
	print(path)
```
Activate the node by showing it, then save a file (it won't save anything on it's own, or at least I don't think it's supposed to and doesn't). It will output to the screen the offending result.

**Comment by akien-mga** [comment]
This is actually working as expected, see https://github.com/godotengine/godot/pull/22614#issuecomment-427640081

The documentation could be made clearer though.

**Comment by Calinou** [comment]
How should we amend the documentation to denote this? This issue report is a bit confusing.

**Comment by KoBeWi** [comment]
I think I know what this is about:
![godot windows tools 64_ssmeANGiwL](https://user-images.githubusercontent.com/2223172/148649251-740db7dd-f5eb-4474-98e2-7b2722965dfa.gif)
I added a filter without wildcard and the FileDialog will append this filter to the specified filename, but remove the dot.

We should probably just forbid using filters that start with dot. A filter should either be a filename or wildcard.
