### ISSUE TITLE
Animation in Godot 3 needs more keyframes than in Godot 2

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#18546]
**Godot version:**

Godot 3.0.2

**OS/device including version:**

**Issue description:**

Keyframes no longer 'stretch' back on the timeline if no other keyframes exist before them. I now have to create more keyframes to get the animation to work like it would have in Godot 2.

**Steps to reproduce:**
In the included Godot 3 project first playback Animation1 and you'll see the Godot head fade out. Now play the animation again but stop between the two key frames and play the animation from the beginning again. The opacity of the Godot head will still be at the opacity level it had when the animation was stopped. 
Now try the same thing in the Godot 2 project and you'll see that the Godot head is not at the same opacity level as when the animation was stopped but instead at the opacity level dictated by the first keyframe on the timeline. 
To get the same behavior in Godot 3 I have to insert an extra keyframe at the beginning of the timeline as I have done in Animation2.

**Minimal reproduction project:**

[AnimationGodot2.zip](https://github.com/godotengine/godot/files/1964009/AnimationGodot2.zip)
[AnimationGodot3.zip](https://github.com/godotengine/godot/files/1964010/AnimationGodot3.zip)

**Comment by KoBeWi** [comment]
That's somewhat related to #812

**Comment by Calinou** [comment]
This is now considered expected behavior,
 as it's required to work this way for the **Capture** mode to work.
