### ISSUE TITLE
Depth texture maybe incorrect display when rotate in z-axis

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#18548]
**Godot version:**

commit: 6244b9

**OS/device including version:**

750M

**Issue description:**

depth texture maybe incorrect display when rotate in z-axis
[rock.zip](https://github.com/godotengine/godot/files/1964108/rock.zip)
rock.zip is a video
in video
first rotate x-axis -> display correct
and rotate z-axis -> display incorrect

if set Depth scale to negative
rotate x-axis -> display incorrect
rotate z-axis -> display connect

**Steps to reproduce:**
create a plane
add a depth texture to it
rotate z-axis

**Minimal reproduction project:**

[GodotMaterial.zip](https://github.com/godotengine/godot/files/1964123/GodotMaterial.zip)

**Comment by Calinou** [comment]
This was likely solved by #23760, closing. Note that SpatialMaterial now offers options to flip normals and bitangents as well.
