### ISSUE TITLE
LineEdit should have restrictions settings.

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#18542]
**Godot version:**
3.0.2

**Issue description:**
LineEdit should have restrictions settings in inspector. For example for preventing users to type numbers, special symbols, non-english symbols, upper case or lower case symbols. Also it should have min length parameter.

**Comment by Zylann** [comment]
Would a validation callback do this work?

**Comment by Chaosus** [comment]
Yeah, its works.. Just need to attach script and overload `text_changed `or `focus_exited`. However it would be nice if this could be automatic

**Comment by volzhs** [comment]
reminds me of... https://twitter.com/reduzio/status/990599053456171009

**Comment by Paulb23** [comment]
Related / Duplicate of #10416

**Comment by Chaosus** [comment]
Ok, I close it then.. sorry for duplicate
