### ISSUE TITLE
Bug on godot 3.0.2

### ISSUE THREAD

**Issue by demacedius** [godotengine/godot#18543]
Hi i have a bug on godot. Je i launch a script or if i load a latest project.  Godot dans this.
Module/gdscript/gdscript.cpp : 792 ...
Module/gdscript/gdscript.cpp:1856...
Faites loading ressources. 
**Godot version:**

**OS/device including version:**
Osx sierra 

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by volzhs** [comment]
can't say anything about it.
I think you need to attach reproducible project.

**Comment by akien-mga** [comment]
We need more details to help you, either detailed steps to reproduce the issue, or a zipped project (you can drag and drop to upload in the GitHub comment) that triggers the bug.

**Comment by Noshyaar** [comment]
Closing as Not reproducible
