### ISSUE TITLE
Control.has_point() does not exist

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#18540]
**Godot version:**

3.0.2 stable

**Issue description:**

The documents list `has_point()` as a method of `Control`, but attempting to use it throws an invalid call error claiming the function does not exist.  I'm not sure if this is a documentation problem or a problem with the member definition in the class itself.

**Steps to reproduce:**
Add a script to any node that is or extends from `Control`.  Attempt to call has_point().  Run project.

**Comment by Noshyaar** [comment]
`has_point` is virtual method so you have to implement it yourself like `_gui_input`.

**Comment by Zylann** [comment]
If the intent is to test if a point is in the control's rectanglem you can also do `control.get_rect().has_point(pos)`
