### ISSUE TITLE
Make unique not working for materials in duplicated meshes

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#18547]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
When I attempt to make a material unique in a duplicated cube mesh It fails and editing it still edits the other's material (It does dissapear for about half a second in the inspector when I attempt to make it unique before reappearing though). 
I have to make the mesh itself unique to be able to edit the material independantly.

**Steps to reproduce:**
Make MeshInstance node, set it as cube mesh.

Make spatial material, fumble about with it.

Duplicate MeshInstance node, attempt to make material unique

Attempt to edit "Unique" material, observe that both MeshInstances' materials change

**Comment by bojidar-bg** [comment]
If the material is a subresource of the mesh, you have to "make unique" both.
In order to have per-meshinstance materials, you have to set them in the meshinstance's properties, not in the mesh's.

**Comment by ElfEars** [comment]
Hmm. I see what you're saying. I started this issue because it seemed confusing but now it seems like it isn't a bug
