### ISSUE TITLE
cone twist joint not updating on viewport

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#18549]
**Godot version:**

3.0.2

**OS/device including version:**

linux mint
750ti

**Issue description:**

I am playing with the joints and cone twist joint doesn't show when added to scene
![2018-05-01 23 07 09](https://user-images.githubusercontent.com/10883749/39478334-b732f612-4d94-11e8-8d94-4e1ecf393653.png)

**Steps to reproduce:**
add a cone twist joint 

**Minimal reproduction project:**

**Comment by AndreaCatania** [comment]
In order to show it you should connect it to a rigid / static body

**Comment by ZX-WT** [comment]
With more testing, I think the issue is that the joint doesn't update.
![2018-05-05 12 47 29](https://user-images.githubusercontent.com/10883749/39659766-98eaf5e4-5062-11e8-8467-a18023f7b9cb.png)
Here I placed the joint originally between the two object and a straight line is drawn. I translate it and it is still a straight line. It only update when I toggle the visibility or switch scenes and show two cone.

**Comment by AndreaCatania** [comment]
Yes the problem is the gizmo update, that should be called when the spatial position changes.
Doesn't exists a signal to attach to know when it changes, so a solution could be add a cycle that iterate only when the editor is on, and checks if the attached rigid body position changes.

@reduz what do you think about?

**Comment by JFonS** [comment]
Updating all gizmos all the time would be too much I think. I would leave it to specific nodes (in this case ConeTwistJoint) to set up some kind of timer to update the gizmo.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 3.2 builds?
