### ISSUE TITLE
RichTextLabel fill alignement wrap bug 

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1855]
Hi,

With current head.
The text wrap with fill alignement seems to have a bug that makes the last word of a line to overlap the first word the same line. Here is a photo of the bug caught in flagrante delicto into the "Rich Text Label BBcode" demo :

![godot_20150507_1922_rich_text_label_text_wrap](https://cloud.githubusercontent.com/assets/9801802/7521738/940b42de-f4f0-11e4-9077-1ac5d243a35a.png)

This must be a romantic bug, because by reading the sentence carefully, you'll notice that the bug makes "Joy" and "Will" "end up fitting the horizontal space entirely ..." over each other. 

The window client size is about 738x600 pixels.

Might be related to #1848.

**Comment by akien-mga** [comment]
I can't reproduce in the current master branch, so assuming it has been fixed.
