### ISSUE TITLE
Have an option to export a bitmask variable.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#18551]
**Godot version:**
Godot 3.0.2

**Issue description:**
What I'm requesting is a way to export a bitmask with labeled names from a script. What I want to be able to do is something like this

```GDScript
export("Basic", "Fire", "Ice", "Electric") var weakness
```

And be able to check or uncheck any of those names to create a bit mask. It could look something like the bitmask that physics layers and render layers have, except only have the options specified in the export.

![godot_v3 0 2-stable_win64_2018-05-01_12-29-13](https://user-images.githubusercontent.com/11450875/39482003-6b038224-4d3b-11e8-831e-29c1bea0cfed.png)

And the actual variable would be an integer, so I can then do something like

```GDScript
if weakness & damage_type:
    damage_value *= 2.0
```

**Comment by bojidar-bg** [comment]
This should work ([docs](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#exporting-bit-flags)):
```gdscript
export(int, FLAGS, "Basic", "Fire", "Ice", "Electric") var weakness
```

**Comment by CowThing** [comment]
Oooh, yes, that is what I wanted. I completely missed that because I was only looking at all the export examples which were directly above that bit flag section. And none of my googling found any mention of it probably because I was searching "bitmask" instead of "bit flag".
