### ISSUE TITLE
Locking root node doesn't work if node has a bounding box

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#18558]
**Godot version:**
1113a73

**Issue description:**
Some types of nodes, such as `Control` and `Sprite`, when set as root nodes, ignore their locked meta status and can be dragged around by their bounding box regardless.  This doesn't seem to affect nodes with a 0-size bounding box or none at all, such as `Node2D`.

**Comment by groud** [comment]
Can you check again,  #18400 has been merged this morning, the problem might be solved.

**Comment by nobuyukinyuu** [comment]
sorry for not getting back to you right away, I've been waiting for the next nightly build to hit callinou's site and my browser had been aggressively caching an old version :)

Confirmed, it seems to have been fixed.
