### ISSUE TITLE
Bug - Area2d Body Entered Gets triggered always

### ISSUE THREAD

**Issue by Mark11110** [godotengine/godot#18554]
The Player's area2d body enter whenever you hit play. The spawn location never hit the player position, but godot thinks it did.

[Space Rocks.zip](https://github.com/godotengine/godot/files/1965841/Space.Rocks.zip)

**Comment by samdze** [comment]
Maybe related to #18748
This bug is currently seriously afflicting my game.

**Comment by KoBeWi** [comment]
It doesn't happen when you add asteroid to scene tree _after_ setting its position.

That's because asteroids appear right on the ship, so it detects the collision before you move it. I guess that's correct behavior. Just move asteroid first and then add to scene.

**Comment by KoBeWi** [comment]
Closing as per comment above. It's not a bug.
