### ISSUE TITLE
Create scene instance as child of root when no node selected

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#18557]
**Godot version:**
3.0.2 (steam)

**OS/device including version:**
X11; Linux x64; Debian Testing

**Issue description:**
When one tries to instance another scene into the current one in the editor, if there is no node currently selected an alert dialog will pop up saying "No parent to instance a child at." To correct this, the user must select a node in the scene tree, and then repeat the process of choosing the scene to instance.
I feel it would be logical in such cases to instance the scene directly under the root node on the first attempt.

**Steps to reproduce:**
1. Create new scene.
2. Create a root node.
3. Create a child of the root node.
4. Delete the child node (this results in no node being selected).
5. Click "instance a scene file", and select any scene.

**Comment by mhilbrunner** [comment]
Fixed in https://github.com/godotengine/godot/pull/18587
