### ISSUE TITLE
Locking a Node2D node causes its children to also be locked

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#18559]
**Godot version:**
Godot 3.1-dev a04323e

**OS/device including version:**
Linux Mint 18.3 Cinnamon x64

**Issue description:**
You can no longer select the children of a locked node. Probably brought about by the changes in #18400. You might want to have a look @groud!
![peek 2018-05-02 20-25](https://user-images.githubusercontent.com/27100585/39518698-52a56064-4e47-11e8-8e78-a3dd37463d55.gif)

**Comment by groud** [comment]
Yeah that an expected behavior I think.

**Comment by homer666** [comment]
Having the ability to lock a certain node without affecting its children was handy, so I'm not sure why the behaviour was changed, or really convinced that it was a good move.

**Comment by groud** [comment]
Ok we discussed about  that in IRC and you are probably right. The previous behaviour allows locking a node and its children using lock + unselectable children.
I'l revert the change then.
