### ISSUE TITLE
Expecting to rename node by right-clicking and choosing 'rename' in the context window

### ISSUE THREAD

**Issue by atari-8bit** [godotengine/godot#18560]
I tried double-clicking but was not successful and tried to figure out another way to rename the node in scene.  Eventually I tried to double-click node and was able to rename it.

I think it would be more 'noob' friendly if there was a 'rename' added to the context menu of node that includes the ability to rename the node.

Godot version 3.0.2

**Comment by akien-mga** [comment]
Fixed by #18786 / 1378ca1e0.
