### ISSUE TITLE
Can't select a Sprite with CurveTexture

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#18563]
**Godot version:**
4c3c510a807ee57c564e7b8b7885cf4fa113bbd5

**OS/device including version:**
Linux 4.16.5

**Issue description:**
I can't select a sprite with CurveTexture.

**Steps to reproduce:**
Create a sprite with CurveTexture and try to select it in the viewport.

**Minimal reproduction project:**
[bug_selection.zip](https://github.com/godotengine/godot/files/1967648/bug_selection.zip)

**Comment by Zylann** [comment]
Note: a CurveTexture is a texture with a 1px height.

**Comment by guilhermefelipecgs** [comment]
GradientTexture works, not only 1px. I put it in the example for comparison with the CurveTexture. CurveTexture should have the same behaviour.

**Comment by Zylann** [comment]
GradientTexture should be 1px high... if it's not, I'd like to know why^^

**Comment by akien-mga** [comment]
This seems fixed in the master branch.
