### ISSUE TITLE
HTML5 + Mono export fails to load C# scripts

### ISSUE THREAD

**Issue by aschuhardt** [godotengine/godot#18569]
**Godot version:**
Master branch as of commit a096df5
Mono 5.10.1.47 64-bit
emscripten-1.37.38

**OS/device including version:**
Windows 10 64-bit
Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Issue description:**
A game exported to HTML5 that uses the Mono module will fail to load .cs files if any are present.
Console log (using attached sample project):
```
let it go dude!
Init OS
Init Audio
Init VS
Init Physicsserver

OpenGL ES 3.0 Renderer: WebKit WebGL
**ERROR**: No loader found for resource: res://MyCsharpScript.cs
**ERROR**:    At: core\io\resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
**ERROR**: No loader found for resource: res://MyCsharpScript.cs
**ERROR**:    At: core\io\resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
**ERROR**: **WARNING**: Couldn't load external resource: res://MyCsharpScript.cs
**ERROR**:    At: scene\resources\scene_format_text.cpp:174:_parse_ext_resource() - Couldn't load external resource: res://MyCsharpScript.cs
```

**Steps to reproduce:**

1. Compile latest master branch with Mono and build HTML5 export templates.
2. Create a new project.
3. Attach a C# script to a node.
4. Export for HTML5.
5. Attempt to run the built .html file by hosting it from a web server (I am using IIS 7, but I can't imagine that it matters).
6. Observe the error messages that appear in the console when the app tries to load .cs scripts.

**Minimal reproduction project:**
[HTML5_Test.zip](https://github.com/godotengine/godot/files/1968921/HTML5_Test.zip)

**Comment by mhilbrunner** [comment]
That is a known limitation for C# in Godot. As of today, Web and Mobile exports don't support C#. 

See https://github.com/godotengine/godot/issues/18364 for discussion.

Currently, there is no planned timeline for C# support on these platforms.

**Comment by KvaGram** [comment]
Is this still the case? It has been 3 years.

**Comment by Calinou** [comment]
> Is this still the case? It has been 3 years.

[C# is now supported in HTML5](https://github.com/godotengine/godot/issues/18569#issuecomment-866860619), but there are many bugs. I would recommend sticking to GDScript for now if you plan to export to HTML5.
