### ISSUE TITLE
window management demo : FixedSize add an extra border around client rectangle

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1856]
Hi,
With current head. Under Windows 8.1.

If you run the "window management" demo, click on the "FixedSize" button and move the window by dragging its title bar, an extra white or black or randomly colored border will be added around the client rectangle, and the window will be resized to a larger size.
If you disable the "FixedSize" and move the window again, the extra border will be removed, and the window will be resized to a smaller size.

See the capture below :
![godot_20150507_2019_windows_fixedsize](https://cloud.githubusercontent.com/assets/9801802/7522719/3e243f72-f4f7-11e4-9b42-3e51f0f1ffae.png)

I have not tested with Linux and others.

**Comment by reduz** [comment]
Windows 8.1 here, I can't reproduce, did you do anything else for this to happen?

**Comment by SuperUserNameMan** [comment]
I just click the FixedSize button, then I drag the window using the title bar, and the extra margin appears.

Then I click FixedSize button again, I drag the window again, and the extra margin disappears.

That's all.

**Comment by SuperUserNameMan** [comment]
Here is an animated GIF to show you :
![godot_window_management_demo_20150520_1241](https://cloud.githubusercontent.com/assets/9801802/7724035/18cbaf34-feee-11e4-895d-cc4ec250fa1a.gif)

**Comment by reduz** [comment]
whoa.. that is strange, it does not happen on my Windows.. I wonder what
can be the difference

**Comment by SuperUserNameMan** [comment]
I've just tried with official 2.0.3stable win64 version on the same computer and OS than last year, and it does not happen again.

So if no one else is affected by this bug, I think it could be closed.

**Comment by vnen** [comment]
Can't reproduce here, so might have been fixed. If this happens to someone else they can report again.
