### ISSUE TITLE
Godot 3.0.3 rc1 Crash

### ISSUE THREAD

**Issue by NedJaims** [godotengine/godot#18577]
**Godot version:**

Godot 3.0.3 rc1 - Classic & Mono version.

**OS/device including version:**

Windows 10

**Issue description:**

I know it's a new version, but Godot closes after he imported a project and imported the assets and Godot closes.
This happens in the classic version and in the mono version.
There is also an error, when I try to do a new project you can not create the folders.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
> I know it's a new version, but Godot closes after he imported a project and imported the assets and Godot closes.

It just closes, without any error? What is displayed in the terminal?

>  There is also an error, when I try to do a new project you can not create the folders.

What's the error?

**Comment by KellyThomas** [comment]
On my windows 7 PC this error occurs only when launching Godot_v3.0.3-rc1_mono_win64.
It does not occur when launching Godot_v3.0.3-rc1_win64.

**Comment by NedJaims** [comment]
It simply closes
![bug](https://user-images.githubusercontent.com/36456992/39592716-3d8c9dec-4ecd-11e8-93f7-752be3832405.png)
And this is the bug of folders
![bugfolder](https://user-images.githubusercontent.com/36456992/39592855-ad5496b6-4ecd-11e8-84e6-b0e1ad88b658.png)

**Comment by akien-mga** [comment]
Do you still have the same issue with 3.0.3 RC3? https://download.tuxfamily.org/godotengine/3.0.3/rc3/

**Comment by NedJaims** [comment]
No, since the RC2 leaves the error after having formatted my PC.
Thanks for the support Rémi
