### ISSUE TITLE
GDScript Keywords in Editor Reference

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot#18579]
This is strictly a feature request

I think it would be beneficial for new people to be able to look up GDScript keywords in the editor, just like the API. It could have the keyword, the definition of it, and an example of how it is used (or maybe two examples).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2361, as feature proposals are now tracked on the Godot proposals repository.
