### ISSUE TITLE
Godot 3.0.3-rc1 wont start the editor

### ISSUE THREAD

**Issue by M4gma** [godotengine/godot#18574]
**Godot version:**
https://downloads.tuxfamily.org/godotengine/3.0.3/rc1/Godot_v3.0.3-rc1_x11.64.zip

**OS/device including version:**
Fedora 28 

**Issue description:**
```
[lucio@localhost ~]$ ./Godot_v3.0.3-rc1_x11.64 
Error: Could not load game path '.'.
[lucio@localhost ~]$ ./Godot_v3.0.3-rc1_x11.64 -e
Error: Could not load game path '.'.
[lucio@localhost ~]$ 
```

**Comment by M4gma** [comment]
It is possible tools is disabled on this build because I've put the executable in my project folder and instead of showing the editor, godot showed an empty scene for me

**Comment by hpvb** [comment]
This release was done with new release scripts and it looks like I accidentally shipped the export template as the editor. I've just uploaded new zips for X11... Sorry.

**Comment by hpvb** [comment]
Thanks for the report, I've verified that the new zips are correct.
