### ISSUE TITLE
In game profiler

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#18571]
Godot version: 3.0.2

Hi there,

We need a on screen profiler like this 

![profiler](https://answers.unrealengine.com/storage/attachments/7969-info3.jpg)

When the game is running full screen or full window we should be able to read fps and other profiling metrics directly in game, without needing to switch to Godot editor view.
A toogle key to switch profiling in game on/off would be usefull.

Thanks you.

**Comment by eon-s** [comment]
This can be probably made with a plugin, since most monitoring tools are exposed in Performance class.

**Comment by Ranoller** [comment]
I'have one in my project. Very easy to do. You have the singleton that says eon-s. You can monitorize several things, but not functions like in profiler... Monitorize in screen have a trap, if you print things in screen and you are calling api methods all frames to do that your performance get down so.... You monitorize worst performance that you really have, but is very usefull i agree

**Comment by TheYokai** [comment]
This may be better as an example-project -- one to show developers how to make their own in game profiling tools. I think games have a unique set of statistics that need to be profiled, and thus it is hard to create a "generic" profiler because of it. Giving developers examples that help them make their own tools (or making an easier to use API if necessary) may be a better way of thinking about it.

**Comment by groud** [comment]
This is something you can easily achieve with the current [Perfomance API](http://docs.godotengine.org/en/3.0/classes/class_performance.html).
There no reason why this should be built-in, it's up to you to make this profiler if you need it in your game.

**Comment by Ranoller** [comment]
Create a singleton that extends canvas layer, make them not sensitive to zoom, add a rich text label and send info to them with .add_text("text"). Make lines with "\n" , and make an action to hide/show that ("on_action_release" or similar)... And that is, if this is dificult to acomplish, sure that any other thing in godot will becomes near imposible...

**Comment by eon-s** [comment]
can be used with _draw too, that may have a lower impact on performance than label updates

**Comment by DevMagicLord** [comment]
Performance API is the way to go.

I wonder why Godot does not have an option to display those in efficient way ? 
Perhaps some new profiler option in Godot with : 
- frame rate
- average frame rate
- min frame rate
- real time curve frame rate drawing

**Comment by Zireael07** [comment]
I believe it should.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/63, as feature proposals are now tracked on the Godot proposals repository.
