### ISSUE TITLE
Godot 3.0.2 Stable Win 64 crashes when creating a C# script. Mono is updated.

### ISSUE THREAD

**Issue by ElysRealm** [godotengine/godot#18576]
I did a search and the only thing I could fid similar was [Issue #17745](https://github.com/godotengine/godot/issues/17745)

**Godot version:**
Godot_v3.0.2-stable_mono_win64

**OS/device including version:**
Windows 10 64-Bit

**Issue description:**
Created a C# script, GoDOt crashes with the following log. Mono version is 5.10.1.47 (latest stable version).

> OpenGL ES 3.0 Renderer: GeForce GTX 980/PCIe/SSE2
> Mono: Initializing module...
> Mono: Runtime initialized
> Mono: INITIALIZED
> OPENING: C:/Users/e_mcw/Downloads/Testing (C:::Users::e_mcw::Downloads::Testing)
> running cmdline: "D:\GoDot\Godot_v3.0.2-stable_mono_win64.exe" "--path" "C:/Users/e_mcw/Downloads/Testing" "--editor"
> Mono: Runtime cleanup...
> OpenGL ES 3.0 Renderer: GeForce GTX 980/PCIe/SSE2
> Mono: Initializing module...
> Mono: Runtime initialized
> Mono: INITIALIZED
> no access to
> ERROR: FileAccessWindows::_get_modified_time: Method/Function Failed, returning: 0
>    At: drivers\windows\file_access_windows.cpp:272
> CrashHandlerException: Program crashed
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [0] mono_image_get_name
> [1] mono_image_get_name
> [2] mono_image_get_name
> [3] mono_image_get_name
> [4] mono_image_get_name
> [5] mono_image_get_name
> [6] <couldn't map PC to fn name>
> [7] <couldn't map PC to fn name>
> [8] <couldn't map PC to fn name>
> [9] <couldn't map PC to fn name>
> [10] mono_image_get_name
> -- END OF BACKTRACE --

**Steps to reproduce:**

1. Open project.
2. Make node.
3. Attach C# script.
4. Crash.

**Minimal reproduction project:**
I don't think that applies here.

**Comment by KellyThomas** [comment]
Godot v3.0.2-stable requires Mono 5.4.x

**Comment by ElysRealm** [comment]
Didn't realize it wouldn't work beyond that.

**Comment by akien-mga** [comment]
It does if you build from source, but for the pre-compiled binaries you indeed need exactly 5.4.x. This will be fixed in 3.0.3 which should be more flexible.
