### ISSUE TITLE
Support adaptative icons for Android

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#18580]
Google has released a new feature for latest android devices.
It is about adaptative icons, and it render pretty well on latest android versions.

[Link to the feature itself](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive).

It would not be hard to introduce it in Godot Engine, unfortunately I don't have much time lately.

**Comment by volzhs** [comment]
looks duplicated issue with #18256

**Comment by xsellier** [comment]
Indeed, apologies, Im closing this one.
