### ISSUE TITLE
Emulate mouse from touch option can't be found

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#18582]
**Godot version:**

3.1.dev 75ff86f8f

**OS/device including version:**

Kubuntu 18.04

**Issue description:**

Can't find `input/pointing_devices/emulate_mouse_from_touch` at Project Settings > General.

There is 2 `pointing_devices` at Input Map instead.
![screenshot_20180503_151812](https://user-images.githubusercontent.com/8281454/39562196-50f4d260-4ee5-11e8-8c39-f38ea90e3b8c.png)

And I was able to test this code on PC instead of phone with `Emulate Touchscreen` option on.
```gdscript
func _unhandled_input(evt):
    if event is InputEventScreenTouch:
        print("touched")
        pass
```
but it does not work anymore.
is it expected?
should I change it to use `if event is InputEventMouseButton` instead if I want to handle it both on PC and mobile?

**Steps to reproduce:**
create new project and see Project settings.

**Minimal reproduction project:**

**Comment by volzhs** [comment]
forget to mention that it seems to come from #17196
cc @RandomShaper

**Comment by RandomShaper** [comment]
You can emulate in one direction or the other and base your code on mouse or touch events. Mouse emulation is restricted to one touch pointer, though, but allows _touching_ the GUI.

That said, you shouldn't be needing cofe changes.

I'm curious about the missing options and the spurious entries in the input map dialog.

Could you rename your editor settings file and have a look at how it looks? :)

**Comment by RandomShaper** [comment]
Sorry. Naughty thumb.

**Comment by volzhs** [comment]
![screenshot_20180503_160309](https://user-images.githubusercontent.com/8281454/39563535-8ec2cad8-4eeb-11e8-9915-589484fdc720.png)
![screenshot_20180503_160334](https://user-images.githubusercontent.com/8281454/39563538-9036ca90-4eeb-11e8-96b6-cca3f7049c0a.png)
@RandomShaper This is how it looks after removing previous editor settings file.
No `Input` section on General tab.
and 2 `pointing_devices` on Input Map tab.

**Comment by volzhs** [comment]
oh, about the question in OP,
I got it now there are 2 different options. :)

```
input/pointing_devices/emulate_touch_from_mouse
input/pointing_devices/emulate_mouse_from_touch
```
couldn't realized it before.

**Comment by volzhs** [comment]
I think it's on Input Map tab because of https://github.com/godotengine/godot/blob/master/core/input_map.cpp#L225

**Comment by volzhs** [comment]
should it be like `input_devices/pointing/emulate_touch_from_mouse`?
