### ISSUE TITLE
Shape keys name not displayed correctly

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#18583]
**Godot version:**
Godot 3.0.2

**OS/device including version:**
OS: Windows 8.1

**Issue description:**
So, I have a model that have shape keys / morphs written in Japanese, I export it from Blender to dae using Better Collada Exporter, and import it to Godot.

In the inspector the some of the name is not displayed correctly, but when I keyframe it to animation it displayed correctly in animation panel.

This is the screenshot.

![wrongjap](https://user-images.githubusercontent.com/8316851/39564533-cbfb92a2-4ede-11e8-8cd0-fd9d37949226.JPG)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@earlroxas13 Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by AureaFUNSoft** [comment]
I think it's ok now. I open this with 3.2.1 stable.
![Untitled](https://user-images.githubusercontent.com/8875839/83999496-1241b380-a98d-11ea-84a6-57ddf017c396.jpg)

**Comment by Calinou** [comment]
@AureaFUNSoft Thanks for replying :slightly_smiling_face: Closing as resolved then.
