### ISSUE TITLE
Pasting text from HTML into the script editor makes Godot unresponsive to keyboard input (in Virtual Machine)

### ISSUE THREAD

**Issue by jldinh** [godotengine/godot#18586]
**Godot version:**
3.0.2, 3.0.2 Mono,  3.0.3-rc1 Mono

**OS/device including version:**
Ubuntu 16.04

**Issue description:**
When copy-pasting text from an HTML page into the script editor, the editor then becomes unresponsive to the keyboard. Sometimes a few Ctrl+V (~ 1 to 15) are needed before it happens, but it eventually stops working.
Mouse input is unaffected though.
Copy-pasting raw text seems to work fine (50+ pastes).

**Steps to reproduce:**

1. Copy text from HTML page (but not from a text area), e.g.: `copy me`.
2. Paste into the editor with Ctrl+V. Repeat 15 times, or until it breaks.
3. Once Ctrl+V has stopped working, try to type additional things anywhere in Godot (in the editor, inspector properties...).

**Comment by reduz** [comment]
Script editor is here:
https://github.com/godotengine/godot/blob/master/scene/gui/text_edit.cpp

**Comment by nikibobi** [comment]
I couldn't reproduce this in Godot 3.0.6 under linux with chrome/firefox. Does the issue still persist for you @jldinh ?

**Comment by stewartnjohnston** [comment]
I was just able to reproduce this issue using:
- Godot Engine v3.0.6
- Ubuntu 14.06
- Chromium Version 69.0.3497.81 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

When I restart Godot the problem goes away.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc1](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-1))?

**Comment by KoBeWi** [comment]
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.
