### ISSUE TITLE
3D viewport mouse locking causes mouselook to feel snappy and awkward

### ISSUE THREAD

**Issue by smt923** [godotengine/godot#18597]
**Godot version:**

v3.0.2.stable.official

**OS/device including version:**

Windows 10 x64 (v1709)

**Issue description:**

The mouse snapping in the 3D viewport when holding right click feels very awkward and unnatural, as well as it snaps your view erratically when you right click and drag around immediately.

If it's going to lock the mouse at all I think it shouldn't allow the viewport view to move until the mouse is locked, or the mouse lock should just be an option as Unity and UE4 both don't (at least, not in the same way) lock the mouse in such a way.

At least in Unity (UE4 is similar but I can't speak for it as well) the mouse isn't locked or hidden at all, and when going off the monitor it simply wraps around (the wrapping around is minor, but just presumably how they deal with unlocked mouse) - to me this feels great, and super natrual. Even aside from the snapping/awkwardness, just having the cursor reset to the center after moving the viewport even a little feels very unnatrual too.

[Youtube video of Godot's behavior vs Unity](https://www.youtube.com/watch?v=C6s9zpuvz7Y)

It isn't _super clear_ in the video alone, but I think it's still visible how much smoother unity's viewport is, and it just feels better to have the mouse visible and unlocked, as well as it doesn't have any jerky or "flicky" movement when grabbing the viewport quickly

imo, the editor would be one huge step forward in usability and smoothness if either the snappiness and awkwardness could be somehow fixed, or if there could be a setting to just make it behave more like other similiar programs

**Steps to reproduce:**
Open any project
Right click near the edge of a viewport and while you right click start dragging to move the camera
The view will snap in an awkward way that doesn't match your input, presumably due to mouse/cursor locking

**Minimal reproduction project:**

N/A (happens on an empty scene)

**Comment by Zylann** [comment]
There are existing issues about free look, but I don't remember the links (I'm on a phone).
It jumps off when doing repeated drags due to bad events handling at OS level and sometimes stays locked due to bad event handling with the viewport.

**Comment by Zylann** [comment]
Basically if you want a reference for this use of RMB, it was inspired from Unity3D, and is intented to work the same.

**Comment by Zylann** [comment]
It has to wrap around though, because your desktop size can be smaller than the amount you have to drag... unless we use raw mouse input events, in which case the pixel position of the cursor won't matter.

**Comment by smt923** [comment]
You might be misunderstanding me, the wrap around is fine and feels good, like the 2D viewport and other engines like Unity which have wrap around and don't snap the cursor, that feels good - my problem is just with Godot's 3D viewport, where it locks your mouse to the center and this causes a ton of weird issues that make the freelook mode just feel very snappy and awkward

**Comment by Norrox** [comment]
Sorry for bumping this issue, i can see it has been added to 3.1 witch is nice.
I would just like to say that i too would like to see the mouse "reappear" at the same position when you first clicked RMB, because rightclicking and rotating something and then have the mouse reappear in the center of screen is annoying

**Comment by reduz** [comment]
this MAY be fixed now with the switch to rawinput on Windows, so please test

**Comment by smt923** [comment]
The 3D inspector now feels a lot more responsive and I'm unable to reproduce the weird snapping/"warping" I felt before, it feels super super good now 👍

I'm still not a massive fan of the mouse locking to the center (this can get a bit annoying when playing with stuff in the inspector, quickly moving the mouse to the side of the viewport and moving, but then the mouse snaps into the center, further away from the inspector and just not where you expect it - it'd be cool if this could be an option, with the other setting being the "warp around" and visible cursor like in the 2D  viewport) but otherwise this fixes the main point of the issue 👍

**Comment by akien-mga** [comment]
Closing as fixed then.

For the remaining point described in https://github.com/godotengine/godot/issues/18597#issuecomment-419483517, it might be better to open a new issue to discuss this specifically.
