### ISSUE TITLE
GI issue: the light range of the GIProbes for emissive light and bounce lighting is too low

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18599]
Edit: we told me that this is not a bug, Godot does currently one bounce, the Vulkan port will allow multiple bounces.

I have done a test between Blender Cycles (same result with Eevee's light probes) and Godot's GIProbes. I have created an hollowed cube with an emissive shader for the face at the top. The left wall is red and the right is green. Here is the result:

![gi cycles godot](https://user-images.githubusercontent.com/30020215/39609091-80f26e3a-4f46-11e8-9ff7-00d7494b0340.png)

The emissive lighting range in Godot is very small, it doesn't cover the entire cube but we can also see that the bouncing light is unnoticeable, we should see a lot of red and green on the white wall in the back. If the emissive energy is increased in Godot the range doesn't change to cover the entire cube's interior and the lighting on the wall becomes burned.

**Comment by Calinou** [comment]
Support for multiple bounces has been implemented in the new GIProbe in the `master` branch, closing.
