### ISSUE TITLE
Mouse gets stuck in freelook mode if you scroll to adjust camera while holding right mouse

### ISSUE THREAD

**Issue by smt923** [godotengine/godot#18598]
**Godot version:**

v3.0.2.stable.official

**OS/device including version:**

Windows 10 x64 (v1709)

**Issue description:**

Right clicking in the 3d viewport, then scrolling to adjust the speed will cause the freelook mode to continue even after letting go of right mouse, I assume this isn't meant to happen, and should instead end the freelook mode whenever you let go of right mouse

**Steps to reproduce:**
Open a scene, go to the 3D viewport, hold right click and scroll to change speed, the mouse will be stuck in freelook mode even if you let go of right mouse

**Minimal reproduction project:**

N/A (happens on blank scene)

**Comment by jv110** [comment]
It's probably not intended, but it's certainly a cool feature. Navigating levels without holding the mouse button is nice. If this gets fixed, we should have a key to use this "permanent freelook" mode.

**Comment by CowThing** [comment]
Shift+F already puts the camera into a permanent freelook.

**Comment by jv110** [comment]
Ah, didn't know that.

**Comment by dodgyville** [comment]
I have a similar issue in master and after using scroll button and RMB it gets stuck in freelook mode, then when I press ESC the mouse pointer is gone and mouse input no longer works anywhere in the editor. Keys still work but editor is unusable :(
