### ISSUE TITLE
VehicleWheel produces NaN errors when colliding when Roll Influence = 0

### ISSUE THREAD

**Issue by Quakermann** [godotengine/godot#18605]
**Godot version:**
 3.1.custombuild (commit hash: b3e4bc562c07142d48907278f9cc496791ff7b33)

**OS/device including version:**
Linux 4.14.30-1-MANJARO

When a VehicleWheel collides with a physics object, like a StaticBody, it flings out NaN errors and teleports the wheel far off into the void. Here's one of my errors:

```
0:00:03:0608 - Condition ' Math::is_nan(p_aabb.size.x) ' is true.
----------
Type:Error
Description: 
Time: 0:00:03:0608
C Error: Condition ' Math::is_nan(p_aabb.size.x) ' is true.
C Source: core/math/octree.h:847
C Function: move

```
**Steps to reproduce:**
Create a VehicleBody with a VehicleWheel, give the wheel with a CollisionShape, and give a Roll Influence value of 0. Then, create something to collide with the vehicle, for example a StaticBody. Create and StaticBody and give it a CollisionShape.

**Minimal reproduction project:**
[test_bug.zip](https://github.com/godotengine/godot/files/1973365/test_bug.zip)

**Comment by akien-mga** [comment]
CC @BastiaanOlij @AndreaCatania

**Comment by BastiaanOlij** [comment]
Owh, that sounds pretty funky.. Need to find some time to look into that...

**Comment by BastiaanOlij** [comment]
We probably should prevent roll influence being set to zero as that basically results in a divide by zero:
https://github.com/godotengine/godot/blob/master/scene/3d/vehicle_body.cpp#L590
Which admittedly is the change i recently did to fix the shaking we had when the car wasn't moving.

Or we constrain that logic. Thought it would probably result in the car just rolling over at the first bit of steering input... Still it's better then a divide by zero and all the flow on effects of that...

**Comment by AndreaCatania** [comment]
I think that the first solution is way better, prevent to set roll influenze to 0

**Comment by Quakermann** [comment]
Perhaps check to see if roll influence is equal to 0 then disable
stablization all together?

**Comment by BastiaanOlij** [comment]
The problem with setting roll influence to zero is that the impulse will be applied to the center of mass doing pretty much nothing. But I'll stop it from at least spitting the dummy
