### ISSUE TITLE
'~./local/share/..../GodotSharp.csproj' was not found (Linux Mono)

### ISSUE THREAD

**Issue by DavidJVitale** [godotengine/godot#18606]
**Godot version:**
Godot_v3.0.2-stable_mono_x11_64

**OS/device including version:**
Ubuntu 16.04.2 LTS

**Issue description:**
Hello, I am trying to get a "Hello World" C# project working in Mono with Linux. When I either import an existing C# Godot project. or create a new one, I receive this compile error:
![screenshot from 2018-05-04 01-12-49](https://user-images.githubusercontent.com/18691334/39615189-77ea03a4-4f3a-11e8-9c3e-4f0b32a92624.png)
As a side note, the error does not show up in the "Output" tab, I cannot copy/paste the content of the message. It only shows up when I hover my mouse over the error.
I checked my filesystem, there is no GodotSharp.csproj file in the specified location.

__I was able to fix the problem by  deleting the entirety of `~/.godot/` and `~/.local/share/godot/`__. I am not sure why this fixed the problem, although I do also have an old version 2.0 of Godot installed that might have originally created those folders.

**Steps to reproduce:**
* Install Godot Mono x64 for Linux
* Install 5.4.X of mono
* Try to create any C# code files, and press "run"

-----

Thanks for your great work and all that you do! I am documenting this issue and it's solution incase anyone runs into it, or incase this relates to any other bug seen.

**Comment by exts** [comment]
Ah yeah, i had this issue on LInux Mint and I had to delete just the share folder. There's no simple way to fix it other than deleting those files. Godot doesn't try to replace missing files for some odd reason. Never happened again though after running into that issue.

**Comment by codespren** [comment]
Had same problem with MacOS, Godot version 3.0.3. I renamed the Mono's solution-folder (lots of numbers in it's name) in directory
/Users/userName/Library/Application Support/Godot/mono/solutions/
and that was enough to fix the problem.

**Comment by olivierLefebvre96** [comment]
A friend of mine got the same problem but on Windows 7 64 bits. He downloaded the last Godot C# version 64 bits with Mono 5.12.0 64 bits too.
Deleting/renaming these full-of-numbers directories doesn't seem to fix the problem.

**Comment by Calinou** [comment]
@DavidJVitale Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by DavidJVitale** [comment]
I have been using Godot mono consistently since 3.0.2, I have not been able to reproduce it on 3.1.X, 3.2.X, or any of the 3.2.2 betas. To me, this issue seems to have been resolved, considering the last comment was ~2 years ago in 2018. 

Closing this issue, please comment if anyone is seeing this in more recent releases.
