### ISSUE TITLE
Directional Shadow Atlas Size Cannot be Modified at Runtime

### ISSUE THREAD

**Issue by cwook** [godotengine/godot#18621]
version 3.0.2 stable

There is currently no way (AFAIK) to change the resolution of the directional shadow atlas from GDScript, which makes changing graphics settings during runtime difficult, since the directional shadow is used in most large 3D scenes.

Additionally, changing the size of the directional shadow atlas in the Project Settings does not actually affect the size of the atlas until Godot is restarted (when it re-reads the godot.project file and properly sets up the directional shadow atlas). I've tried deleting the node and re-adding it, closing and opening the scene, and even creating a new scene, but the shadow atlas size stays the same as when Godot was launched.

**Comment by cosmicchipsocket** [comment]
+1, tried to make a graphics settings menu and was wondering why my changes weren't taking effect.

**Comment by YeldhamDev** [comment]
Does this dosn't work?
`get_tree().root.shadow_atlas_size = [value you want here]`

**Comment by Calinou** [comment]
It's possible to override project settings before the project is actually set up, see https://github.com/godotengine/godot/issues/30087#issuecomment-505879289. However, this still requires the user to restart the project to be able to see changes to the directional shadow size.

@YeldhamDev The shadow atlas size is only used by OmniLights and SpotLights, not DirectionalLights.

**Comment by EzraT** [comment]
+1, Would love to have this accessible in Viewport directly.

Is there a specific reason why the Directional Shadow Atlas can not be resized on the fly? or is it just simply not implemented yet?

**Comment by clayjohn** [comment]
@EzraT it has to do with the current design of the renderer. It just wasn't built to handle that sort of thing. So it's not a matter of just allowing directional atlas to be resized, we would have to significantly restructure parts of the rendering backend. 

 AFAIK 4.0 will allow you to change most graphics settings on the fly due to the restructuring that already took place for Vulkan. :)

**Comment by EzraT** [comment]
@clayjohn Gotya, thanks for the clarification!
Good to know rendering will be more flexible in 4.0.
