### ISSUE TITLE
Filling in current_file in FileDialog causes two !is_inside_tree() errors

### ISSUE THREAD

**Issue by DualMatrix** [godotengine/godot#18631]
**Godot version:**
3.0.2

**Issue description:**

If a scene contains a FileDialog with it's current_file property filled in it will produce two errors:

```
Condition ' !is_inside_tree() ' is true.
----------
Type:Error
Description: 
C Error: Condition ' !is_inside_tree() ' is true.
C Source: scene\gui\control.cpp:2067
C Function: Control::grab_focus
```

This happens when the scene loads

**Steps to reproduce:**

Make a scene, add a FileDialog, fill in the current_file property and load the scene.

**Minimal reproduction project:**

[file_dialog_error.zip](https://github.com/godotengine/godot/files/1976517/file_dialog_error.zip)

The scene is called Control.tscn, load it and the errors will occur

**Comment by vnen** [comment]
I notice this only happens if the contents of `current_file` has a period in it.

**Comment by godot999** [comment]
Just happened to me too.
