### ISSUE TITLE
Preloaded resources in .gd scripts don't get exported as dependencies of those scripts

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#18641]
**Godot version:**
3.0.2 stable

**OS/device including version:**
MacBook Air (13-inch, Early 2014) (1,4 GHz Intel Core i5)
MacOS High Sierra 10.13.3

**Issue description:**
When selecting Project > Export > Export selected resources (and dependencies), .gd scripts selected won't include as dependencies the preloaded resources included in the script.

**Steps to reproduce:**
1. Create scriptParent.gd and preload scriptChild.gd
2. Set first node script to scriptParent.gd
3. Enable Project > Export > Export selected resources (and dependencies)
4. Select the scene to be exported
5. Play on device

**What it should do**
Load the scene correctly because the scene references scriptParent.gd, and this scripts is preloading scriptChild.gd so it should be exported too

**What it does instead**
The game quits and logcat shows an error similar to this:

>  **ERROR**: No loader found for resource: res://scriptChild.gd

**Minimal reproduction project:**
I can do it if needed.

**Comment by jahd2602** [comment]
Yes, it is not implemented right now but it would be very useful. Basically, we would need to parse them the exported scripts recursively at compile/build/export time, and determine it's dependencies from the preload function calls.

I understand that the preload function is only for convenience, but we can use it for more useful things.

**Comment by KoBeWi** [comment]
Somewhat related to #26497

**Comment by vnen** [comment]
Pretty sure I fixed this for 3.1, scripts now know what their dependencies are (both for `preload` and `extends`).

**Comment by jitspoe** [comment]
I'm running into this issue in 4.5 and 4.6(dev).  I have a script with a bunch of sounds preloaded and when I export a build, if I don't explicitly include the sounds in the export, stuff breaks (including sounds that are exported because I think the script just stops at the first failed preload).

**Comment by AThousandShips** [comment]
That's probably tracked in:
* https://github.com/godotengine/godot/issues/90643
