### ISSUE TITLE
web load

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#1864]
Hope to be able to support web loading
For example:

func _ready():
  texture = load("http://www.google.com/logo.png")

**Comment by reduz** [comment]
I suppose an asynchronous loading function should be added eventually..

**Comment by cjmxp** [comment]
Try to integrate curl Lib

**Comment by reduz** [comment]
godot already has http support and ability to do http requests on a thread,
it' s not that difficult

**Comment by marcosbitetti** [comment]
The only difficult is manage HTTP return messages, like redirects. I work on it http://pastebin.com/uZKSkJL3

**Comment by akien-mga** [comment]
Duplicate of #2310...
