### ISSUE TITLE
Make the Region property work together with Animation in Sprite nodes

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#18648]
Currently, with **Sprite** nodes, if `Region` is enabled, `Animation` will be completely ignored. I would be great to be able to make them work together for things like animation sub-states.

**Comment by vnen** [comment]
Do you mean region with frames together (as in #16007) or animation in general doesn't work with Sprite if region is enabled (which would be quite a strange bug). Or do you mean you can't animate the Region rectangle?

**Comment by YeldhamDev** [comment]
`Region` working with `Frames`, and it seems that there is even a pull (#16122) for that already, really hope that is merged soon. Closing.

**Comment by nightblade9** [comment]
I ran into this also. The PR was merged into 3.1. Hopefully we can get it soon (the bug exists in 3.0.4)
