### ISSUE TITLE
Add alternate pseudo 3D retro 3D rendering.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#18653]
Hi, I think It would be nice if godot would let the player to play pseudo 3D ancient 3D rendering techniques, like a basic 2D raycaster (DOOM and wolfestein), or something like Mode 07 for the SNES or even the perspective integer mode of the early psx.

I'm not sure if those can be easily done with 2D rendering mode.

**Comment by Zireael07** [comment]
Pseudo 3D of Wolfenstein style can be done fairly neatly with billboarding sprites.

The other modes are well, completely different.

**Comment by jv110** [comment]
2D with depth and mode 7 are not 3D, as you seem to be aware. If you want those, you should just simulate them with 3D sprites. Mode 7 could be done in 2D, but Wolfenstein and Doom graphics would be extremely hard to reproduce correctly without making your own engine. I don't think this is worth adding.

**Comment by vnen** [comment]
The thing is: why would want to use ancient pseudo-3D techniques in a modern 3D engine? Why not simply use the modern 3D techniques?

In any case, I believe all of those can accomplished by applying custom transforms to 2D nodes.

**Comment by groud** [comment]
And is too corner case to be added to the core.

**Comment by akien-mga** [comment]
Those are too game-specific indeed and no really something that should be implemented in the render engine, as others mentioned. You can achieve such effects easily using the existing features of the 2D and/or 3D renderer based on the expected output. I'm pretty sure the community will make demos for those on the Asset Library eventually.
