### ISSUE TITLE
Kinematicbody2D [help] 2 collision boxes in one object. 1 to use as trigger only.

### ISSUE THREAD

**Issue by unTanana** [godotengine/godot#18656]
**Godot version:**
3.0.2

**Issue description:**
I'm trying to separate the collision with other characters & environment, from the hitbox of a character. I'm trying to accomplish this with an extra collision shape. It didn't work. I also tried adding an area2D node inside the character node, and listening for "area_entered" or "body_entered" signals. I can't seem to get the weapons detected in this way (I've been playing around with collision layers and masks). Is there a way to do this properly ? I suspect that having 2 collision shapes inside the kinematicbody2D would do the trick, with the "hitbox" one set as trigger. But the trigger option doesn't exist, and I don't know how to emulate it.

What I'm trying to do so far:

![image](https://user-images.githubusercontent.com/22821635/39674368-66c24b3e-5153-11e8-9905-0be22b19a01c.png)

**Minimal reproduction project:**
The project I'm testing with
[godot-test.zip](https://github.com/godotengine/godot/files/1977701/godot-test.zip)

Thanks! :)

**Comment by KoBeWi** [comment]
Area2D as a child should work, you are probably doing something wrong with layers/masks. The provided minimal reproduction project however isn't minimal enough to isolate the issue properly.

**Comment by KoBeWi** [comment]
So as I said, this is not engine issue. Using an Area2D child should work perfectly fine if you setup collisions properly.
