### ISSUE TITLE
Reduction of the number of colors in the Project Settings Quality options

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18662]
The ability to reduce the amount of colors like 256 colors in the project settings could allow to convert a 3D game into a retro game. It could be used in combination with a video scaler with sharp pixels for a pixel art look: https://github.com/godotengine/godot/issues/18661

**Comment by Calinou** [comment]
Modern graphics hardware cannot always use a 16-bit color depth, let alone a 8-bit color depth. Palette reduction can be done using a shader (this way, you have full control over the palette to use).

**Comment by Xrayez** [comment]
I think the actual intention is not converting an image to 8/16-bits but actually having an ability to reduce the number of colors alone even if the format is unchanged.

**Comment by Calinou** [comment]
This can be implemented using a paletting shader (as is done in engines like GZDoom), closing. Video scaling can be implemented using custom viewports or setting the stretch mode to `viewport` in the Project Settings.
