### ISSUE TITLE
NavigationMeshInstance does not have refresh functionality

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot#18669]
**Godot version:**
Godot v3.0.2.stable.official

**OS/device including version:**
Windows 10, should apply to all OS

**Issue description:**
NavigationMeshInstance has no way to refresh itself natually. Instead, users must set it's enable property to false, then back on, for it to recognize changes.
If this is not done, the navigation debug view will *appear* as if it worked, but it is misleading and navigation will fail.
I have not fully investigated this on 3d (NavigationMeshInstance) but it appears to have the same issue.

There should be a function in these nodes that allows them to be called to refresh instead of relying on the set_enabled property to accomplish this for you:
https://github.com/godotengine/godot/blob/e24f2c6489afdccc6268008d3dcc1ff4ad8ea71c/scene/2d/navigation_polygon.cpp#L324

For example:
```
var points = PoolVector2Array()
points.append(...)
navpoly.add_outline(points)
navpoly.make_polygons_from_outlines() #This could also automatically refresh
navpoly.refresh() #This function is explicit, instead of relying on enabled false/true
```

There is no documentation that supports this Node either, so there is nothing to let users know of the correct behavior, nor how to use the NavigationMesh/Instance in scripts.

**Steps to reproduce:**
Create a navigation node. Give it a NavigationPolygonInstance child node, with a simple polygon.
Give the NavigationPolygonInstance a script that simply adds a new outline inside of it. Call add_outline, then make_polygons_from_outlines, and you will have the issue. You must then immediately set enabled to false, then true, and it will behave as expected.

**Minimal reproduction project:**
[navigation.zip](https://github.com/godotengine/godot/files/1978299/navigation.zip)
See navpoly.gd and the scene. Comment out the enable/disable lines to see the glitch.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

I tried the demo, but it doesn't seem to be working at all or maybe I'm doing something wrong.

**Comment by smix8** [comment]
I reworked the MRP for Godot 4.0 and 3.5 and indeed the update on the NavigationServer is broken when only polygons are changed and not the entire NavigationPolygon resource. Interestingly enough the navigation debug display updates correctly.
