### ISSUE TITLE
Enums can't be passed as arguments to other Nodes' methods

### ISSUE THREAD

**Issue by camrodgers** [godotengine/godot#18668]
Godot version: 3.0.2
OS/device including version: Fedora 27
Issue description:
If I try to access another node's enum value or send one node's enum value to another node, the other node won't recognize the enum's contents' names, and will only view it as an integer. For example:
In my first person controller node:
```
func _physics_process(delta):
	Camera.testEnum(stance)
```
In my camera node:
```
func testEnum(var a):
	if a == STANDING:
		print("yay")
```
This crashes. "Parser error: Identifier not found: STANDING." Same crash if I tried to access the enum var directly, eg "match FirstPerson.stance:"
But this works:
```
func testEnum(var a):
	if a == 0:
		print("yay")
```
This severely limits the usefulness of enums! Code readability goes way down when I have to consult the numeric value of each constant. Is there a possible solution, or is this just how it has to be?

**Comment by DevinPentecost** [comment]
Where is the enum defined? If it's in different files, then of course it cannot be found.
Import the file either via preload or onready, or use a singleton and that will open up access to the enum. Then you can use it like normal.

**Comment by Zylann** [comment]
You can do:

```gdscript
const FirstPerson = preload("firstPerson.gd")

func testEnum(a):
    match a:
        FirstPerson.STANDING:
            print("yay")
```

consts and enums are scoped to the script or class they are defined into, so to be used somewhere else they must be referenced (you only need the script/class, not necessarily an instance of it)

**Comment by NathanLovato** [comment]
That's normal, members in an enum are not objects: they are lists of flags to which Godot automatically assigns int values.
```gdscript
enum MY_ENUM { OPTION_1, OPTION_2, OPTION_3 }
```
In this example, options one, two and three will respectively have the values `0`, `1` and `2`.
This makes it perfect if you need flags inside a node like error types or something. As Devin explains above you may have an enum in an [autoloaded script file](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/singletons_autoload.html?highlight=autoload) (singleton) so you can access it from anywhere in your project.

**Comment by mhilbrunner** [comment]
This is not a bug. To use an identifier, it must be available in the current scope. Either load/preload the script where it is defined, or use an autoload/singleton to define your enum.

**Comment by vnen** [comment]
This isn't a bug, an enum is only available where it's defined, there's no global scope in GDScript. Like @Zylann said you can load the source script to get it.
