### ISSUE TITLE
AnimationPlayer's "play_backwards" doesn't have autocompletion

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#18663]
**Godot version:**
 baa3933

**Issue description:**
While the `play` function in **AnimationPlayer** autocompletes with the current list of animations, `play_backwards` doesn't.

**Comment by jv110** [comment]
Lack of autocompletion doesn't happen only with that function. I noticed ConcavePolygonShape.set_faces doesn't have it either.

**Comment by bojidar-bg** [comment]
@jv110 Can you elaborate about that? `set_faces` takes a `PoolVector3Array` of faces, it doesn't have any parameters to autocomplete the way `AnimationPlayer.play` or `Input.is_action_pressed` have.

**Comment by bojidar-bg** [comment]
Tagging as junior job, the only thing to be done is adding the `play_backwards` function here:
https://github.com/godotengine/godot/blob/9aa9dd27fef7aeea92cf5bbec771f7d6f47caf82/scene/animation/animation_player.cpp#L1210-L1212

**Comment by bojidar-bg** [comment]
@jv110 Ah, that's not a bug actually. You should use the `faces` property instead of the getter and setter methods directly. So, `xx.faces = y` instead of `xx.set_faces(y)`

**Comment by jv110** [comment]
`faces` doesn't appear either.

**Comment by bojidar-bg** [comment]
Oh well... that's my bad..
Basically, the property is listed as "internal", while it probably shouldn't be.

https://github.com/godotengine/godot/blob/9b8e8b2220b4e2bac3310262d3d1cd7a8eb3b0a5/scene/resources/concave_polygon_shape.cpp#L85
