### ISSUE TITLE
Godot is washed out/dim on HDR displays with Win10

### ISSUE THREAD

**Issue by redxdev** [godotengine/godot#18667]
**Godot version:** baa3933

**OS/device including version:** Windows 10 1803 (April 2018 update)

**GPU:** GTX 1080

**Issue description:**
The godot editor is dim/washed out on HDR displays. I'm guessing this is related to the new HDR/SDR options in the recent Win10 update, as Godot isn't the only program to exhibit this behavior (Chrome, annoyingly enough, being another one). That said, most programs work fine so I'm guessing it is something that needs fixing on Godot's side. This problem _does_ go away when HDR is disabled in Windows settings.

Unfortunately, I can't actually take a screenshot as screenshots act as if HDR isn't enabled, so here's the best comparison I have that shows the problem:

![image](https://user-images.githubusercontent.com/472625/39680409-420e7612-5155-11e8-9306-4029ee4ff839.png)

Both of those are on an HDR display with HDR enabled in windows settings. The left is Godot itself, and the right is a screenshot taken of Godot - notice how much brighter the screenshot is, and that's displaying in a program that shouldn't be doing anything special for HDR displays.

Here's another somewhat convoluted example:

![image](https://user-images.githubusercontent.com/472625/39680456-cfd75590-5155-11e8-94b5-21390c411bab.png)

That's a pure white box rendered in the Godot editor on the right, with explorer open on the left. Notice how much brighter explorer is.

I know those are pretty bad images, but unfortunately I can't think of a better way to show off the problem. If someone has an idea for a better way to capture this I'm all ears.

**Comment by SevastyanDark** [comment]
Have the same problem

**Comment by akien-mga** [comment]
Windows 10's rolling release seems to be more unstable than Arch Linux nowadays... Closing as we can't fix their buggy updates sadly.
