### ISSUE TITLE
Depth pre-pass not working for multimesh instances?

### ISSUE THREAD

**Issue by pgruenbacher** [godotengine/godot#18671]
**Godot version:**

Godot_v3.0.2_stable

**OS/device including version:**

Linux 64 Nvidia native driver

**Issue description:**

Doesn't seem like depth works when using multimesh. I've set depth mode to opaque pre-pass for all of the materials. Yet when I do multiple multimeshes of different meshes in the same scene, the depth of the meshes changes with camera movement. The gif below should illustrate. Am I just missing a parameter?

**Steps to reproduce:**
Take a mesh with grass material, create multiple multimeshes with it. 
![bad_depth](https://user-images.githubusercontent.com/3332598/39683584-586dc898-5184-11e8-8582-4bee25967057.gif)

**Minimal reproduction project:**

I'll get to this later if someone actually wants to reproduce, but I'm guessing I'm missing a spatial material parameter.

**Comment by Zylann** [comment]
Are you using a transparent material?

**Comment by pgruenbacher** [comment]
yea. I think I realized I need to use alpha cut. I believe that resolves the alpha sorting issue? I'll see if that works and will update this issue with the result.
I'm also going to have the close-to-ground foilage have a lower render priority. 
I should adopt this post into the godot blog documentation. https://blogs.msdn.microsoft.com/shawnhar/2009/02/18/depth-sorting-alpha-blended-objects/

**Comment by pgruenbacher** [comment]
![alpha_cut](https://user-images.githubusercontent.com/3332598/39733023-999514ba-523e-11e8-8455-ac918a03fc72.gif)
Seems like alpha cut resolves the issue, though now there's the issue of it not looking very good but I'll worry about that.
