### ISSUE TITLE
Should this also include pre multiplied alpha?

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#18676]
@reduz  Just noticed this bit of code doing a different change and just asking this question out loud.

https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_canvas_gles3.cpp#L1284
```
bool unshaded = shader_cache && (shader_cache->canvas_item.light_mode == RasterizerStorageGLES3::Shader::CanvasItem::LIGHT_MODE_UNSHADED || blend_mode != RasterizerStorageGLES3::Shader::CanvasItem::BLEND_MODE_MIX);
```
If I read this correctly, unshaded can only be false if blend mode is BLEND_MODE_MIX 

Later on however:
https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_canvas_gles3.cpp#L1358
```
if ((blend_mode == RasterizerStorageGLES3::Shader::CanvasItem::BLEND_MODE_MIX || blend_mode == RasterizerStorageGLES3::Shader::CanvasItem::BLEND_MODE_PMALPHA) && p_light && !unshaded) {
```
This line of code suggest that lighting should also be applied if blend mode is BLEND_MODE_PMALPHA however as unshaded will always be true in this case, that won't happen.

One of those lines of code is incorrect...

**Comment by akien-mga** [comment]
Fixed by #21857.
