### ISSUE TITLE
it is really slow to quit a scene with large amount instance nodes

### ISSUE THREAD

**Issue by chenjie199234** [godotengine/godot#18673]
version:3.0.2

i use script to instance 30000 instance and add them to the scene.it just cost 2-3 seconds

but if i quit() the scene or queue_free() the scene it is really slow!!

the test example was uploaded

[Test.zip](https://github.com/godotengine/godot/files/1978646/Test.zip)

**Comment by Geequlim** [comment]
As the profiler show the performance is lost in the destructor of Object.

https://github.com/godotengine/godot/blob/e15305721da0e4478b62efcda3e79f1c04e7a901/core/object.cpp#L1886-L1890

![image](https://user-images.githubusercontent.com/6964556/39693552-f6bd56f2-5216-11e8-8e2a-c6950ebc532b.png)

**Comment by TheYokai** [comment]
I'm not entirely sure why the performance should be bad with disconnect since maps should be pretty efficient in terms of performance. It's worth checking this out to see if there's some way to improve performance of our disconnection.

**Comment by Geequlim** [comment]
@chenjie199234  Why closing this issue? It is not solved yet.

**Comment by chenjie199234** [comment]
@Geequlim just closed all my issue~~just disappointed~~i will go back to use urho3d

**Comment by mhilbrunner** [comment]
@chenjie199234 Reopening for now, feel free to ignore and have fun & success with Urho, but we still need to fix this. Thanks for reporting!

**Comment by pgruenbacher** [comment]
This seems like a non-issue to me. We should just be documenting how to achieve 1000+ instances using particles, multimesh, server.

**Comment by reduz** [comment]
This was actually a design problem which was just fixed.
