### ISSUE TITLE
How does audio work internally?

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot#18672]
I am asking out of curiosity. I already know about the 2D and 3D graphics renderers. glsl, binding buffers, textures, UBO's. The likes. However I don't really much how audio is handled. Do you use openAL? Why are their multiple audio drivers? How do the buses' effects change the sound? On CPU or somewhere else?

**Comment by mhilbrunner** [comment]
GH issues are not suited to this kind of discussion. Head over to the engine dev channel on IRC.

Also, see http://docs.godotengine.org/en/3.0/development/cpp/custom_audiostreams.html.
