### ISSUE TITLE
[Bug] Keep screen on does not work for android

### ISSUE THREAD

**Issue by braniii** [godotengine/godot#18683]
**Godot version:**
3.0.2 (stable from AUR)

**OS/device including version:**
Arch linux and android 7.1 cancro (and some other devices)

**Issue description:**
Even though I checked in settings "Display -> Window -> Keep screen on" and selected the permission "wake lock", the app does not make use of the android permission "keep awake". So the device fells a sleep.

**Steps to reproduce:**
- Create an empty project
- Create node, save it and select as main node.
- Check "Display -> Window -> Keep screen on"
- Create Export scheme for Android with permission "wake lock" checked

**Minimal reproduction project:**
See: https://github.com/braniii/Keep_screen_on

And thanks for this great engine!

**Comment by Zireael07** [comment]
I believe this setting is for Godot editor itself, not the exported app.

**Comment by braniii** [comment]
@Zireael07 
Oh, but then it is confusing that it is part of the "project settings" and not of the "editor settings". Can you tell me how to make use of the android permission "wake lock". Do I need to call a function?

**Comment by Sulkway** [comment]
Did this get resolved? I'm struggling to keep the screen on in my exported app having used the settings I had thought were correct.

**Comment by braniii** [comment]
Nope. It will be fixed with 3.1. If it's urgent you need to use 2.*

**Comment by Sulkway** [comment]
No worries, thanks for your help!

**Comment by eon-s** [comment]
This seems to be working on master, is there any chance to get the fix cherry picked on 3.0?

**Comment by akien-mga** [comment]
The fix is #20192, it's marked for cherry-picking. I'll add it for 3.0.7.
