### ISSUE TITLE
OptionButton.add_icon_item() requires 3 arguments

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#18686]
**Godot version:**
3.0.2

**Issue description:**
![image](https://user-images.githubusercontent.com/1023003/39713718-62a7ce30-51ed-11e8-9bd6-4a5744ee2fb6.png)

Docs state that the 3rd argument is optional, but the compiler expects 3 arguments.  This may be a documentation issue, but it's more likely that this function signature is supposed to be consistent with OptionButton.add_item(), where `id` is optional.

**Workaround:**   Specify `-1` as the third argument.

**Comment by vnen** [comment]
Should just be a matter of adding a default argument value in the bindings and/or the method itself.
