### ISSUE TITLE
if Enable Debugging ((on / off) == off) exe crash.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#1868]
I tried to test the ability to export to Windows x32, in the mode of release, after the export was created EXE file when I run, it creates a window, it shows Godot logo, and then, there comes a crashed, but if I put the flag enable debugging (on), and exported project, the EXE file runs the game normally. I tried different projects and 3D and 2D but it happens everywhere identical.

**Comment by DriNeo** [comment]
Same issue for me.

**Comment by reduz** [comment]
will check it next time i'm on windows

**Comment by KelinciFX** [comment]
I do not have these issues.. I'm on Windows 8 x64 with 4GB RAM and APU E450 (DualCore 1.65GHz + Radeon 6320). Exporting for Win 32 with / without Enable Debugging is OK, as well as Exporting for Win 64.

All is working veeerrryy well... :-)

**Comment by MarTinazzI** [comment]
I'm in win7_32bit and me and a friend is with the same problem. 
Note:
- Only in win_32bit debugger off
- The crash of the game when you put the mouse in the game window.

**Comment by TD25** [comment]
I have the exactly the same issue. Details the same as for MarTinazzl

**Comment by akien-mga** [comment]
Haven't heard about Windows issues for a while, is this still valid in the current master branch?

**Comment by akien-mga** [comment]
I've had some bad experiences too with the Windows 32bit release template a few weeks ago. For the 2.0 we will have to make sure that all templates work fine on all platforms.

**Comment by akien-mga** [comment]
Fixed by #3363.
