### ISSUE TITLE
Compiling for X11 aarch64 fails (undefined reference linking)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#18692]
**Godot version:**
master

**OS/device including version**
Termux Arch on Android phone

**Issue description:**
Compiling for the aarch64 doesn't work natively in a termux Emulator with arch repo.
I've previously disabled yasm (with yasm there are other issues).

Command:
```scons p=x11 target=release_debug tools=yes arch=aarch64 -j 1```

**Error Output:**
```
/Recast/Source/RecastRegion.cpp              [Initial build] Linking Static Library ==> modules/recast/librecast_builtin.x11.opt.tools.aarch64.a   Ranlib Library         ==> modules/recast/librecast_builtin.x11.opt.tools.aarch64.a                   [Initial build] Linking Program        ==> bin/godot.x11.opt.tools.aarch64                            modules/libmodules.x11.opt.tools.aarch64.a(systemdependent.x11.opt.tools.aarch64.o): In function `vp8_machine_specific_config':
/godot/thirdparty/libvpx/vp8/common/generic/systemdependent.c:102: undefined reference to `arm_cpu_caps'                                                 collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.opt.tools.aarch64] Error 1
scons: building terminated because of errors.      [19:06 godot ]$

```

**Minimal reproduction project:**

**Comment by bruvzg** [comment]
Related #7252 (same error for `armv7`, fixed in #7267)

[modules/webm/libvpx/SCsub#L266](https://github.com/godotengine/godot/blob/master/modules/webm/libvpx/SCsub#L266) probably should have additional check for `aarch64`.
