### ISSUE TITLE
Problem with size flags inside ScrollContainer

### ISSUE THREAD

**Issue by Applemann** [godotengine/godot#18707]
**Godot version:**

v3.0.2.stable.official

**OS/device including version:**

Ubuntu 16.04.3 LTS

**Issue description:**

I am trying make Highscore table by using Control items and when I want give V/HBoxContainers 
with horizontal size flags (Expand, ShrinkCenter} as child into ScrollContainer, 
I see i my Editor this:
![screenshot from 2018-05-08 13-53-02](https://user-images.githubusercontent.com/2686906/39755707-2aad4a0c-52c7-11e8-9e5c-2fdab98d4fe8.png)

but after run the current scene (F6) I see this:
![screenshot from 2018-05-08 13-53-44](https://user-images.githubusercontent.com/2686906/39755745-534a930c-52c7-11e8-8b65-dadae860ea29.png)

I also discovered that VBoxContainer always change size when I change size of ScrollContainer which is parent..  see video:
[highscore-video.zip](https://github.com/godotengine/godot/files/1983772/highscore-video.zip)

And when VBoxContainer is not inside ScrollContainer, all is ok:
![screenshot from 2018-05-08 14-08-53](https://user-images.githubusercontent.com/2686906/39756320-63479546-52c9-11e8-9e7f-c3bb7152873e.png)

**Steps to reproduce:**
Download 'Minimal reproduction project', import and run it by this video:
[highscore-reproduce.zip](https://github.com/godotengine/godot/files/1983850/highscore-reproduce.zip)

**Minimal reproduction project:**

[Highscore.zip](https://github.com/godotengine/godot/files/1983808/Highscore.zip)

**Comment by groud** [comment]
Ok, this is a misunderstanding on how Containers work: they choose the size of their children.
So the size you change in the video is overriden by the ScrollContainer.

To get the expected behavior, you need to set the Horizontal Expand flag on the VBoxContainer.
