### ISSUE TITLE
PSA: Add this code to your main script to fix all your bugs

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#18708]
**Godot version:**
Godot 2.1.x, 3.0.x and *master* branch.

**OS/device including version:**
All OSes and all users affected.

**Issue description:**
It has come to my attention that many users are experiencing bugs in their projects, all of which can (presumably) be fixed by running this simple method:
```gdscript
func new_day(relax = true):
	var date = OS.get_date()
	if date.month == 5 and date.day == 8:  # May 8th
		var reduz = get_node("/root/alpaca")
		reduz.congratulate("Happy birthday!")
		if relax:
			reduz.work_schedule[date].free()  # Holiday!
		return "🎉"
```

I strongly encourage you all to try it out today.

**Steps to reproduce:**
1. Log in to IRC, #godotengine-devel on Freenode
2. Ping @reduz and spam him with congratulations

*Caution:* May increment the age of your alpacas, turning them eventually into wise alpacas:
![screenshot_20180508_151410](https://user-images.githubusercontent.com/4701338/39759246-76f942ac-52d2-11e8-8769-8ccb7a3ac7f7.png) **»»** ![screenshot_20180508_151506](https://user-images.githubusercontent.com/4701338/39759291-976ab0ac-52d2-11e8-9f1a-9837c76de06c.png)

**Comment by gamergamesz** [comment]
@reduz Happy birthday Sir Alpaca!

**Comment by LikeLakers2** [comment]
Happy birthday, @reduz!

**Comment by AlexHoratio** [comment]
@reduz Happy birthday!

**Comment by bojidar-bg** [comment]
Happy birthday!

It seems to me that _tomorrow_ this issue would be a duplicate of #9303.

**Comment by SatishGodaPearl** [comment]
Happy Birthday @reduz :) May all your wishes come true.

**Comment by rubenjavier** [comment]
Happy birthday ;-D
nice code snippet
Feliz cumpleaños!

**Comment by akien-mga** [comment]
Closing as *old*. :þ
