### ISSUE TITLE
App manifest validation error "ARM" -> "arm"

### ISSUE THREAD

**Issue by juanpaexpedite** [godotengine/godot#18705]
I know it is a really small issue, but because it is hardcoded, I will have to compile godot to test...  it should be "arm"

https://github.com/godotengine/godot/blob/de97339a2d66cc9e3bd9ab77dd4e0c5c6534a869/platform/uwp/export/export.cpp#L780

Because using Winappdeploycmd install -file XXX.appx -ip 127.0.0.1 -pin XXXX appears:

0x80080204 - error C00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 3, Column 83, Reason: 'ARM' violates enumeration constraint of 'x86 x64 arm arm64 x86a64 neutral'.
The attribute 'ProcessorArchitecture' with value 'ARM' failed to parse.

**Comment by akien-mga** [comment]
Wow, Windows APIs that actually cares about the case :P

CC @vnen

**Comment by vnen** [comment]
Well, I'm more surprised that there's someone trying the UWP export on a device...

Still, if that change solves it then it's quite simple. I don't have an ARM device with Windows to test.

**Comment by vnen** [comment]
I guess it's fixed by  #18728.
