### ISSUE TITLE
Polygon2D skeletal deform going wrong.

### ISSUE THREAD

**Issue by Plopsiskopsis** [godotengine/godot#18719]
**Godot version:**
V3.1.dev.calinou.2bf71d0

**OS/device including version:**
Win10 64 bit. Geforce gtx 950M

**Issue description:**
Added skeletal deform to a polygon2D as mentioned here: https://godotengine.org/article/godot-gets-2d-skeletal-deform 

After moving the skeleton around as kinematic body the deform goes wrong. Seems like the position/transformation data is not passed properly.

**Steps to reproduce:**
Make a skeletal polygon2d. Animate it. Move the thing around as kinematic body and see the animation go wrong. 

**Minimal reproduction project:**
[stickman.zip](https://github.com/godotengine/godot/files/1985192/stickman.zip)

**Comment by Plopsiskopsis** [comment]
Also might be related but noticed that moving the character around the collision shapes move away from the original position. Eg. not following properly it's parent.

**Comment by jvdnbus** [comment]
Not specific to kinematic body, simply moving the Polygon2D (its Transform) causes unwanted deformation of the texture.

**Comment by reduz** [comment]
Did not get to check the issue, but you are supposed to move the skeleton and the Polygon2D together, as transform happens in Global coordinates.If you don't do that it's expected that it will deform.

**Comment by jvdnbus** [comment]
@reduz Selecting and moving both, or just moving the root gives unexpected deformation.

![tree](https://i.imgur.com/dLaJygJ.png)

**Comment by Ranoller** [comment]
![polygondeform](https://user-images.githubusercontent.com/11712737/43106885-ec103b10-8eda-11e8-92d1-1a7713ef5bdd.gif)


Scalating the parent node of a structure like that give that result... there is something wrong between skeleton -> bone -> polygon
