### ISSUE TITLE
Shortcut does not work for MenuButton and OptionButton (no Popup is opened)

### ISSUE THREAD

**Issue by legione** [godotengine/godot#18715]
**Godot version:**

Godot 3.0.2 stable

**OS/device including version:**

Windows 10 and Linux

**Issue description:**

Shortcuts for MenuButton or OptionButton don't open the correspondent popup. 
The buttons should open the popup also when the shortcut is pressed.

**Steps to reproduce:**
1. Create a MenuButton or an OptionButton
2. Assign a shortcut in the inspector
3. Run the scene and press the shortcut, no Popup shows up

**Minimal reproduction project:**

[ShortcutNoPopup.zip](https://github.com/godotengine/godot/files/1984917/ShortcutNoPopup.zip)

**Comment by vnen** [comment]
I'm not sure this a bug, I don't think the shortcuts are meant to open menus/popups. They just send a signal as if the item was clicked, nothing is done in the GUI itself.

**Comment by legione** [comment]
I think it all depends on how the function of a shortcut is intended. If the shortcut has just to send a signal you're right, but I think this is counter-intuitive. I consider the shortcut the same of clicking a button so I expect the same behavior. And in the case of MenuButton and OptionButton clicking means opening a popup.
If this is not the case, then would be nice to have a function that opens the popup in the right place, since if I get the popup and open it manually it appears in the wrong position and I have to manually give the Rect2D where to open it.

**Comment by akien-mga** [comment]
Fixed by #29717.
