### ISSUE TITLE
Unable to check `if variable is` built-in type

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#18713]
**Godot version:**
Godot Engine v3.0.2.stable.official

**OS/device including version:**
Surface Pro 4 running Windows 10 Home v1709 (Fall Creator's Update)

**Issue description:**
I am unable to check if a variable is a built-in type using the `is` keyword.

Consider the following:
```gd
extends Node2D

func _ready():
	print(is_this_a_string('This is a string'))

func is_this_a_string(variable):
	var is_str = false
	if variable is String:
		is_str = true
	return is_str
```
This should print `true` to the console, but instead the engine complains something similar like `error(8,19): Error parsing expression, misplaced: Built-In Type`

**Steps to reproduce:**
Use the `if <variable> is <Built-in Type>` syntax anywhere.

**Minimal reproduction project:**
[Bug Report - Can't Check for Built-in Types.zip](https://github.com/godotengine/godot/files/1984583/Bug.Report.-.Can.t.Check.for.Built-in.Types.zip) (I went a little overkill and checked for every built-in type, but it should still be easy to understand regardless)

**Comment by vnen** [comment]
Shouldn't be hard to add. I guess many users will expect this to work like that, but it would make `typeof()` redundant.

**Comment by bojidar-bg** [comment]
I actually proposed this a while back on IRC, so :+1:.

**Comment by Zylann** [comment]
`typeof` would not become redundant because it returns the type, while `is` only tests it.
