### ISSUE TITLE
SOLVED: Lock up when running project in 1.1rc2 (and rc3)

### ISSUE THREAD

**Issue by Lyaer** [godotengine/godot#1871]
Trying to run my project in godot1.1rc2 but it isn't working

I can load the project just fine, but when I go to run the scene, it locks up on the loading screen. Nothing is printed in the output box aside from ** Debug Mode Started ** and ** Debug Mode Stopped **. I have that white screen with the Godot logo, which windows tells me is "Not responding." However, the console is still showing me some print() commands that should be showing up from my _ready() scripts, but not ones from my _process(delta) scripts. The same project runs fine from godot1.0stable.

If I leave it running, every once in a while the console will give me a
md5: [big string of characters]
vs: [another big string of characters]
checking: c/[...]/skeleton.png

A couple times a line popped up that said "lloosstt??"
or sometimes just "lost?"

It is possible I asked it to print that (I know I started to code a function somewhere to check if a battle was lost, and might have had it print that as a placeholder), but if so, I couldn't find a line in my script anywhere with those particular strings of characters in any of the obvious places.  So thinking it might be triggered by something in the engine?

skeleton.png is a spritesheet for a placeholder character. It appears to be loading just fine in the editor. I'm not seeing any error messages in the console, so I have no idea what the problem is. Exception being: the first time I loaded the project in rc2 I got some messages about a custom interface theme not loading, but haven't seen that error since.

I don't have this problem with the 2D platform jumper demo, so it clearly has something to do with the particular project I am working on, and not just any project that was made with an older build of godot. 

is this an engine bug?  If not, pointers on where to trouble shoot on my end?

**Comment by SuperUserNameMan** [comment]
could you provide a minimal project exhibiting this issue ?

**Comment by Lyaer** [comment]
I can provide the project I'm working on.  I tried starting a new project in the old version and loading it in the new one, and it loads fine. I have no idea what I would need to add or change in the minimal project to reproduce the error.  If there are some obvious things to try, I could use some pointers. My programming experience is limited to pretty high level scripting languages (before I started with Godot I had only used Adventure Game Studio  extensively) and the debugger isn't giving me much to work with, this time around.

Current unfortunately sort of messy project:
https://drive.google.com/file/d/0B7W5oKuT9nHgOU1ZRzlNaDVEbWc/view?usp=sharing

**Comment by SuperUserNameMan** [comment]
everything seems to work fine here on Windows8.1 with todays compiled source-code.

What is your OS ?

**Comment by Lyaer** [comment]
Windows 7, 64 bit.

**Comment by SuperUserNameMan** [comment]
Did Windows 7 opened a window about Firewalls parameters when you ran the scene for the first time ?

**Comment by Lyaer** [comment]
Yes.  I just checked Windows Firewall and I had it godot1.1rc2 enabled for private networks but not public ones.  I'm working from school library so I thought maybe that was it.  I made a new firewall exception for public networks but no change.

**Comment by Lyaer** [comment]
I tried again with RC3, and still the same problem.  It did lock up immediately after allowing it past the Firewall (via pop-up), the first time, again, but since I told the firewall to let it through, I don't know how that would be the problem.

**Comment by Lyaer** [comment]
I still don't know what was going on, but I was able to narrow it down to a single non-essential custom function call in one of my _ready() functions.  The function still works elsewhere in the script, and I have no idea why the game would still run for other people, but at least it isn't freezing anymore, and if I have more problems, I know one function to look at more closely.  Thanks for the help, SUNM.

**Comment by eska014** [comment]
Closing this for now. If this ever turns out to be an engine bug after all, feel free to comment or open a new issue.
