### ISSUE TITLE
Curve/easing editor allows dragging curve to infinity

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#18712]
**Godot version:**
3.0.2

**OS/device including version:**
KDE Neon

**Issue description:**
In the curve editor seen when e.g. adjusting the triplanar sharpness, you can keep dragging the curve to end up in infinity.

Demonstration:
![curve](https://user-images.githubusercontent.com/31383123/39763916-a2b3c910-52de-11e8-97d9-219d28c7287f.gif)

**Steps to reproduce:**
1. Open the curve editor on a control.
2. Keep dragging and observe the value goes to infinity.

**Comment by bojidar-bg** [comment]
So you are sure it is not a feature?

**Comment by capnm** [comment]
> So you are sure it is not a feature?

Yes please, mark this as a feature-request :o)

![egg](https://user-images.githubusercontent.com/4047289/39776915-748db8f6-5302-11e8-86d2-7e1530777ad5.png)

**Comment by Calinou** [comment]
I can confirm this in 3.2.2beta4:

![image](https://user-images.githubusercontent.com/180032/83975428-3ac99f00-a8f4-11ea-97c8-5adbdffecb71.png)

What kind of limit should we set?
