### ISSUE TITLE
DirAccess fails on make_dir and dir_exists with user://

### ISSUE THREAD

**Issue by ratsdiov** [godotengine/godot#1872]
I added a comment to issue #791 but could not reopen the issue because I did not originally create it.  The comment I added is repeated below but see the original issue for the test driver and patch that was working for 1.0 stable.  The test driver can be run with godot -s test_driver.gd.

I just tried my test driver with 1.1rc2 and it fails on line 10, the dir.make_dir() line, with ERR_CANT_CREATE. Manually creating the directory and commenting that line out, it fails on line 11 doing the dir_exists() check.

I did not look closely at the changes made in 1.1rc2 but I know with the patches I have above this test driver runs all the way through with 1.0 stable + my patch.

**Comment by nunodonato** [comment]
this doesnt work in linux either (v2.0.3)

**Comment by akien-mga** [comment]
Could you open a new report for it maybe, as this one has already been fixed for the Windows bug? There are various reports about DirAccess issues, I think we need to test it extensively and find what works and what doesn't.

**Comment by akien-mga** [comment]
Well actually let's reopen, I'm making a tracker for all DirAccess bugs anyway.

**Comment by jjay** [comment]
I've meet this issue while playing with remote file access. This is because DirAccess::make_dir_recursive is rely on Globals::globalize_path which works only with res:// paths.
