### ISSUE TITLE
Visualscript Node Suggestion

### ISSUE THREAD

**Issue by NoodleSushi** [godotengine/godot#18734]
I have a new visualscript node suggestion Called the Formula Node

The Formula Node inputs a string and multiple variables:
This node could simplify the workflow from creating complicated calculations with multiple operator nodes, to simply typing a formula on a node with inputs and an output

the number of arguments (a,b,c.....) will depend on an exported integer value

So you could go from this:
![capture](https://user-images.githubusercontent.com/34954180/39796674-871cfff8-538a-11e8-9c61-4292bf1ad40d.PNG)
To this:
![capture](https://user-images.githubusercontent.com/34954180/39796684-9808d224-538a-11e8-9e38-b00fe2345db9.PNG)

**Comment by akien-mga** [comment]
Isn't there an Expression node that does just that already?

**Comment by NoodleSushi** [comment]
@akien-mga oops, my bad
