### ISSUE TITLE
Editor interface bug

### ISSUE THREAD

**Issue by CCODE05B** [godotengine/godot#18739]
**Godot version:**
Godot 3.0.3 RC 1

**OS/device including version:**
Windows 7 x64 bit
8 GB Ram
Nvidia GTX 980

**Issue description:**
Godot sometimes do this thing ( not always )

![interfacebug](https://user-images.githubusercontent.com/34812055/39809466-2b92d58e-5382-11e8-8321-88efb10c8d4c.jpg)

**Comment by akien-mga** [comment]
>  Godot sometimes do this thing ( not always )

When does it do it?

**Comment by CCODE05B** [comment]
@akien-mga i don't know .. sometimes i play games .. then i decide to work on the project 
when i open Godot and try to start coding .. this happen ... 3D and 2D are ok but the Script tab have this problem

**Comment by Zireael07** [comment]
Any nvidia drivers addons or Steam overlay or other stuff that gets launched when you play games that might mess up resolution or I don't know, drivers themselves?

**Comment by girng** [comment]
did this happen after the recent geforce driver update by chance?

**Comment by ordigdug** [comment]
@CCODE05B Do you still have this issue with latest release Godot v3.0.6?

**Comment by CCODE05B** [comment]
@ordigdug nope , Godot now work really really well

**Comment by ordigdug** [comment]
@CCODE05B Great, can you please close this issue?

**Comment by Calinou** [comment]
I closed this as the issue seems to be resolved.
