### ISSUE TITLE
Warning, not found: interface/editor/main_font_bold error in console

### ISSUE THREAD

**Issue by ByTheQuietLake** [godotengine/godot#18737]
**Godot version:**

0f930f8

**OS/device including version:**

Windows 7

**Issue description:**

I get the following warning on the console after opening project manager:

EditorSettings::_get - Warning, not found: interface/editor/main_font_bold
EditorSettings::_get - Warning, not found: interface/editor/main_font_bold

**Steps to reproduce:**
1. compile engine
2. open project manager
3. check the console

**Minimal reproduction project:**

**Comment by ByTheQuietLake** [comment]
#18113 issue mentioned in comments here

**Comment by akien-mga** [comment]
CC @toger5

**Comment by toger5** [comment]
Thank you! For reporting! Will have a look at it

**Comment by ByTheQuietLake** [comment]
Hello, The issue still seems to persist even after the pull request.

**Comment by ByTheQuietLake** [comment]
@toger5 the issue was actually just a typo, it should be main_font_bold but initially it was main__font_bold
