### ISSUE TITLE
File.file_exists() doesn't take remappings after resource conversion into account

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#18740]
**Godot version:**
Current master branch, earlier versions too.

**OS/device including version:**
All OS AFAIK.

**Issue description:**
This is an issue that was mentioned as the reason for "bugs" people were encountering, but since all those previous issues only came to this conclusion after a lot of discussion, they're not so convenient to keep track of a potential resolution (see #1562 and #8773 for example).

Some resources are being converted automatically or optionally when exporting a project, and either get a new suffix (e.g. `scene.tscn` becomes `scene.tscn.converted.scn`, or they even go to the `.import` folder where they are appended a MD5 sum.

Methods like `load()` or `preload()` know how to convert original paths to their new location and name, but `File.file_exists()` doesn't, and it generates a lot of confusion.

`File.file_exists()` could maybe be given an optional `remap` parameter that would involve the resource filenames remappings in its check (defaulting to `true`).

**Steps to reproduce:**
1. Make a project with a `res://scene.tscn` file. Use a script checking `File.new().file_exists("res://scene.tscn")`, it should be true when running from the non-exported project.
2. Export the project, converting .tscn files to .scn resources.
3. The check should now return false. Same story with assets.

**Comment by chanon** [comment]
I needed this to get my exported game to work correctly, so I went ahead and implemented it.

**Comment by akien-mga** [comment]
Fixed by 8523781.

**Comment by chanon** [comment]
Ah, I finally edited the commit message. Sorry for the junk messages, there will be no more of them.

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.
