### ISSUE TITLE
3.1-dev projects can't be opened on 3.0.x, should show a warning

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#18758]
**Godot version:**

3.1.dev & 3.0.3-rc1

**OS/device including version:**

Kubuntu 18.04

**Issue description:**

3.0.x editor just restart project manager without warning message when opening 3.1.dev project.
It should say something.

**Steps to reproduce:**
1. Create a project with 3.1.dev editor
2. Try to open it with 3.0.x editor

**Minimal reproduction project:**

**Comment by vnen** [comment]
Probably because of the version bump in the Project Settings. Cc @groud

**Comment by groud** [comment]
Yeah maybe. Weird it does not displays a message.

**Comment by volzhs** [comment]
it should be warned that it can't be opened 3.0.x editor after opening it with 3.1.x, before opening.

**Comment by nobuyukinyuu** [comment]
You can fix this in the project.godot file by changing the version number back, but  you'll lose your shortcut binds when doing this, so be careful.

**Comment by akien-mga** [comment]
> Also, when upgrading, a message such as "This project was previously opened in Godot [oldversion], would you like to update it to Godot [newversion]? This process is not reversible." would be nice.

That part is #20626. I'll try to tackle both, even though it's tricky to show proper warnings at this early stage when the editor is not up yet.

**Comment by 1F1R5T** [comment]
The project still exits itself without notification of any errors ..., here I am using the version of Godot_v3.1-beta2_x11.64

**Comment by akien-mga** [comment]
It's fixed on 3.1 onwards, we can't change 3.0.x releases :)

**Comment by Zireael07** [comment]
@akien-mga 1F1R51 says he's using 3.1 beta 2?

**Comment by akien-mga** [comment]
For creating the project, sure, but this issue is about opening 3.(n+1) projects in a 3.(n) release, so here it's about opening projects in 3.0.x.
