### ISSUE TITLE
Time line of AnimationPlayer is faster than display during time.

### ISSUE THREAD

**Issue by dbsGen** [godotengine/godot#18760]
**Godot version:**
Godot Engine v3.0.2.stable.official

**OS/device including version:**
Window 7

**Issue description:**
Time line of AnimationPlayer is faster than display during time.

**Steps to reproduce:**
I put a small demo project. just a AnimationPlayer and a Timer.
Sample code: 

      extends Node2D

      var is_run = false
      var time = 0
      var timer
      func _ready():
            timer = get_node("timer")

      func _process(delta):
            time += delta

      func test_begin():
            print("anim begin!")
            time = 0
            is_run = true
            timer.start()

      func test_end():
            print("anim end " + str(time))
            is_run = false

      func _on_timer_timeout():
            print("time out " + str(time))

test_begin will be called when the animation begin. And test_end when the animation end.
Out put is:

      anim begin!
      anim end 0.870479
      time out 0.97043

In my project it is more faster than this.

**Minimal reproduction project:**

https://drive.google.com/file/d/18fkytpfh88_rOSwUYl9trk5igW9LGj2b/view?usp=sharing

**Comment by dbsGen** [comment]
I found it is related to physics fps. when I set physics fps to 10, Output will be:

      anim begin!
      anim end 0.301288
      time out 0.997115

**Comment by dbsGen** [comment]
I added listener to listen the animation_started and animation_finished. 

just insert these code bellow exists codes.

      func _on_anim_animation_finished(anim_name):
          print("anim finished " + anim_name + " - " + str(time))

      func _on_anim_animation_started(anim_name):
          print("anim started " + anim_name + " - " + str(time))

Output:

      anim started auto - 0
      anim begin!
      anim finished auto - 0
      anim end 0.470023
      time out 0.976881

Maybe some thing wrong in animation_finished signal.

**Comment by dbsGen** [comment]
I found that replace NOTIFICATION_INTERNAL_PROCESS to NOTIFICATION_PROCESS would fix the problem. Although I do not know the difference between NOTIFICATION_INTERNAL_PROCESS and NOTIFICATION_PROCESS.

		case NOTIFICATION_PROCESS: {  // NOTIFICATION_INTERNAL_PROCESS ->NOTIFICATION_PROCESS
			if (animation_process_mode == ANIMATION_PROCESS_PHYSICS)
				break;

			if (processing)
				_animation_process(get_process_delta_time());
		} break;
		case NOTIFICATION_PHYSICS_PROCESS: { // NOTIFICATION_INTERNAL_PHYSICS_PROCESS ->NOTIFICATION_PHYSICS_PROCESS

			if (animation_process_mode == ANIMATION_PROCESS_IDLE)
				break;

			if (processing)
				_animation_process(get_physics_process_delta_time());
		} break;

**Comment by reduz** [comment]
I admit i don' t understand this isue very well, but if anyone wants to take the time to understand it better, feel free. I have the feeling this is probably not a bug but a misunderstanding of how animation/timer works, but I may be wrong.

**Comment by DualMatrix** [comment]
So if I understand this correctly this isn't a bug and the AnimationPlayer should just be set to follow the physics process. Right?

**Comment by Anutrix** [comment]
Shouldn't they be set to follow physics process by default?

**Comment by akien-mga** [comment]
This is indeed related to the processing mode. In 3.2, both Timer and AnimationPlayer let you select either Idle or Physics process mode. By default they both use Idle, so the project in the OP works properly (it might have been different in the past with one using Idle and another one Physics, before this was made configurable).
