### ISSUE TITLE
Node.GetChildren should return an array of Node, not Object in C#.

### ISSUE THREAD

**Issue by PJB3005** [godotengine/godot#18773]
**Issue description:**
Right now, it returns an `object[]` (it'd be an `Array<object>` if #15880 went through), which isn't amazing because the objects are *always* `Node`s

Yes, this would require some changes to the binding generator.

**Comment by neikeq** [comment]
I wonder if we could create a type safe Array template class that wrapped Array. It would only wrap it, pretty much the same as the generic Array in #15880 does.
This way the C++ method would be `Array<Node> _get_children()` instead, and the bindings generator would know about the type of the elements.
@reduz WDYT?

**Comment by neikeq** [comment]
I must add that once #15880 is introduced, you will be able to do `var children = (Array<Node>)GetChildren();`, which improves the situation. However, it would be better if the method signature returned a generic Array in the first place.

**Comment by akien-mga** [comment]
Is this still relevant in the current master branch?

**Comment by mysticfall** [comment]
Seems to be so, albeit in a slightly different form:
```csharp
public Godot.Collections.Array GetChildren()
```

**Comment by akien-mga** [comment]
In 4.0 alpha 1, the C++ method is:
```cpp
TypedArray<Node> Node::_get_children(bool p_include_internal) const {
```

This seems to be what would be needed to solve this issue. Is it handled properly on the Mono side too or does it still require dedicated development work? @godotengine/mono

**Comment by raulsntos** [comment]
This is still not solved. The [`bindings_generator`](https://github.com/godotengine/godot/blob/30701e3966fe0869868d09d57249ff140e55849e/modules/mono/editor/bindings_generator.cpp) still generates a method that returns `Array` in that case, instead of `Array<Node>`.
