### ISSUE TITLE
DynamicFonts' outlines are not oversampled

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#18774]
**Godot version:** Git https://github.com/godotengine/godot/commit/1ec2fa42f83ec107d346e610496a547bde861725

**OS/device including version:** Fedora 28

**Issue description:**
When DynamicFont oversampling is enabled, the outline is not oversampled – only the fill part of the font is.

**Original size:**
![font_outline_original](https://user-images.githubusercontent.com/180032/39894208-68fdba18-54a6-11e8-8039-571e11e81477.png)

**Oversampled:**
![font_outline_oversampled](https://user-images.githubusercontent.com/180032/39894209-6921483e-54a6-11e8-8b8b-a00763af8fea.png)

Notice how only the fill part of the font looks crisp; the outline is pixelated.

**Steps to reproduce:**
- Make sure DynamicFont oversampling is enabled in the Project Settings (it should be enabled by default now).
- In the Project Settings, configure the project to use the `2d` scaling mode and `expand` aspect scaling mode.
- Create a Label using a DynamicFont with a FreeType-based outline enabled.
- Run the project and resize the window.

**Minimal reproduction project:** [font_oversampling_outline.zip](https://github.com/godotengine/godot/files/1993207/font_oversampling_outline.zip)

**Comment by endragor** [comment]
Outlines do consider oversampling, but only the initial value - if you start the project with `--resolution 2560x1440` you'll see the outlines are correct. So the bug is about reacting to size change.
