### ISSUE TITLE
HDR is not working correctly with vsync off

### ISSUE THREAD

**Issue by Zamaroht** [godotengine/godot#1877]
I'm trying out the HDR demo and it is not working correctly. It seems to update really slow in a "frame-by-frame" basis. However the project is running at good fps (I can move the cave around smoothly).
If I move around the game window, it seems to update the HDR to the state at which it should be.
The HDR effect works correctly while in the editor.

Also, the hdr tutorial (https://github.com/okamstudio/godot/wiki/tutorial_hdr), in the "Parameters of HDR" section, says that the Environment resource should have the Hdr parameters, however they don't appear in my editor.

I uploaded a video showing these things to clarify:

https://www.youtube.com/watch?v=3YW8WqQEleE

My system specs:
Windows 8.1 64bit, dual screen
CPU: AMD FX-8320 8-core @ 3.5Ghz
GPU: AMD HD6850
RAM: 8GB

**Comment by reduz** [comment]
do you by chance have vsync off? could you check in the debuger tab the game fps?

**Comment by Zamaroht** [comment]
VSync is off from the driver settings. The FPS are in the range of 1300-1500.
I just tried this demo aswell from a notebook I have with lower specs, here the FPSs stay in the range of 65-85, and the HDR demo works correctly.

**Comment by reduz** [comment]
that must be it.. i wonder if there is any way  to force vsync on..

**Comment by akien-mga** [comment]
Related to #2621.

**Comment by akien-mga** [comment]
VSync has now been implemented in Godot 2.1-beta, do you still reproduce this issue when it's enabled?

**Comment by Chaosus** [comment]
(checked) Nope, its fixed in all Godot versions now. _Closed by bugsquad._
