### ISSUE TITLE
3D tiles materials not displaying

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#18778]
3.0.2
Win 7 64bits GeForce 960

Tiles doesn't show any material when used in a gridmap
Changing a tile material doesn't work, it does not reflect in the level gridmap that have been made.

Download the Zip tileset project below , create a new material, changes some tiles with the new material and save it as a new meshlib. Create a new gridmap in the level and assign the new meshlib, tiles won't reflect the new material or won't have any material.
[https://opengameart.org/content/modular-grassland-3d-tileset](url)

**Comment by Plopsiskopsis** [comment]
You need to put the material in primitive mesh. 
![kuva](https://user-images.githubusercontent.com/35765659/39918966-d9588f6c-551a-11e8-9161-76148dd220a0.png)

**Comment by DevMagicLord** [comment]
There is away, while it's not on the docs.

https://github.com/DevMagicLord/Godot3/blob/master/tools/godotMEshlib.jpg
