### ISSUE TITLE
Make "Syntax Highlighter" a radio menu

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#18779]
**Godot version:**
 1ec2fa4

**Issue description:**
I don't exactly know what's its purpose, but while it acts like a radio menu, it's not set as one:
![screenshot1](https://user-images.githubusercontent.com/30739239/39900061-bbb06992-5495-11e8-95d8-43f902a5083e.png)

**Comment by akien-mga** [comment]
CC @Paulb23

**Comment by capnm** [comment]
Please **remove this entry** (it is an useless feature, the syntax should be already
known to the editor). At least move it somewhere else (e.g. File menu, Editor configuration, …)
Thanks.

**Comment by akien-mga** [comment]
It's not useless, but I agree that it should be a sub-menu (probably in `Edit`?).

**Comment by neikeq** [comment]
Most editors allow manually specifying the language, while still detecting it automatically. It would be even more useful if we ever add support to the editor for editing non-script files.
IMO, it should be moved to the status bar at the bottom, next to the line and column labels. Language, encoding and line endings selectors are commonly placed there.

**Comment by capnm** [comment]
I don't remember the last time I needed to disable the autodetection in a general purpose editor and they must cope with an endless amount of possibilities.

Godot generally have to know how to handle any text file anyway, so I think the internal editor doesn't need such overrides.

**Comment by neikeq** [comment]
There are many files which have a custom file extension even though they use are a known format. Things like csproj/*proj (xml), ini-like formats. It's good to give the user a choice on this.

**Comment by capnm** [comment]
Actually I like the current alpaca design pattern to not swallow unknown vegetables in the first place ;)

The engine or plug-in can associate all known used files with a format or meaning (e.g with a content header/ID independent of the file extension). I think, it's a better to give the alpaca the choice and don't bother the editor-user with an, at a some point, giant syntax-options-tree. The engine or plug-in unrelated files are out of scope of the internal editor and belong to an another IDE.

![alpaca](https://user-images.githubusercontent.com/4047289/39939573-00c12a5a-5557-11e8-8087-702645dc167f.png)

**Comment by mhilbrunner** [comment]
Fixed by https://github.com/godotengine/godot/pull/19166
