### ISSUE TITLE
3DKinematic move_and_slide not working under some conditions

### ISSUE THREAD

**Issue by golonia** [godotengine/godot#18794]
This issue seems to be related to #18245 but I cannot re-open it.

**Godot version:**

3.0.2

**OS/device including version:**

Arch Linux (rolling release)

**Issue description:**

It seems I have the same issue as #18245 but I cannot find the `infinite_inertia` field for 3D (it seems to only exist for `RigidBody2D` in the `test_motion()` function. I have a MWE where changing the scale of the floor can toggle the issue on and off. Apparently the body is dropping into the floor (slightly negative y-value) which causes it to indefinitely fall (vertical velocity increases). The strange thing is that the position is not updated even though the velocity is ever increasing. It seems in this case `move_and_slide()` simply does nothing at all.

Here is the working example. The box is dropping onto the ground and can be moved normally: 
![2018-05-11_13-56-53](https://user-images.githubusercontent.com/39191140/39924060-ea01dd46-5515-11e8-9b80-65d5eef7c95b.gif)

Here is the broken example. Except for the floor being scaled bigger in the XZ-plane there are no changes in the example. The box is dropping _into_ the ground and cannot be moved.
![2018-05-11_14-10-32](https://user-images.githubusercontent.com/39191140/39924071-ed177162-5515-11e8-832b-a564593a1c0e.gif)

**Steps to reproduce:**

The change I made is in the `World` scene for the `Floor` node using `scale = (20, 1, 20)` for example 1 and `scale = (128, 1, 128)` for example 2. Please check the MWE project below.

**Minimal reproduction project:**

[Test3D.tar.gz](https://github.com/godotengine/godot/files/1995295/Test3D.tar.gz)

**Comment by groud** [comment]
cc @AndreaCatania

**Comment by AndreaCatania** [comment]
The blue floor is using a plane shape? Because the plane shape is not meant to be walcable, It's meant to be a world margin. Try to use all other shapes

**Comment by golonia** [comment]
The blue floor uses a box shape with height 1. You can check it in the project for yourself if you want. Do you mean I should still use other shapes? From my understanding a box shape should be fine for walking as it is very commonly used as in-game geometry.

**Comment by AndreaCatania** [comment]
Yes box is fine, I'll check it

**Comment by golonia** [comment]
Do you have an estimate when you will have the time to check it? I don't mean to be impatient, I am just asking because currently the development of my project is on hold because of this (character getting stuck is breaking the game). If you don't have the time right now, it's okay but it would be good to have an estimate for my own planning. Thanks!

**Comment by AndreaCatania** [comment]
I've checked it yesterday and I've noticed that the scale of static body is the problem. I've also noticed that this problem happens only with kinematic cube shape.

I need more time to investigate how to fix this issue, in the main time you can use a scale like this 128 10 128 to avoid it.

I let you know soon about the fix

**Comment by Calinou** [comment]
https://github.com/bulletphysics/bullet3/issues/1703 was fixed (and Bullet in Godot updated since then), so I'll assume this bug has been resolved since. Please comment if you can still reproduce this bug.
