### ISSUE TITLE
modifier+key action shows also key action as pressed

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#18793]
Godot Master
https://godotengine.org/qa/28199/how-to-use-shortcuts-with-modifier

I am looking for something like this I thought godot checks this internally. Try to press CONTROL+S.

Expected result CONTROL_S
```
func _process(event):
    if Input.is_action_just_pressed("CONTROL_S"): # KEY_CONTROL+KEY_S
        print("CONTROL_S")

    if Input.is_action_just_pressed("S"): # KEY_S
        print("S")

# Output: CONTROL_S and S
```

This works but I can't use it in my case
```
func _process(delta):
    if Input.is_action_just_released("CONTROL_S"): # KEY_CONTROL+KEY_S
        print("CONTROL_S")

    if Input.is_action_just_released("S") && !Input.is_action_just_released("CONTROL_S"): # KEY_S
        print("S")

# Output: CONTROL_S
```

**Comment by kubecz3k** [comment]
How would you solve that? Go though Input action list and ignore other actions if there is 'direct match'?

**Comment by AlexHolly** [comment]
If such a check is possible, that would probably solve it.

Someone one irc suggested to add a flag for these cases. If that behavior I described is intended you would have to activate the flag for the specific actions.

**Comment by vnen** [comment]
> Someone one irc suggested to add a flag for these cases. If that behavior I described is intended you would have to activate the flag for the specific actions.

That's probably the best way. Many times you don't want a modifier key to shadow an action without modifier, e.g. pressing Space to jump should work even if you are holding Shift to run.

**Comment by AlexHolly** [comment]
Yeah thats true.
I have no idea how the actions work internally in the example the shadow should only happen when an actual action exists for mod+space otherwise they are simply 2 separate actions mod=run and space=jump but when mod+space=superjump only run will activate and superjump will happen once space is also pressed.


If that is only possible with a flag thats fine too.

**Comment by vnen** [comment]
That's assuming Shift+Space replaces jump. If the action is used for something on UI, for instance, then this automatic detection will fail.

I believe there are use cases for both, so it should be a flag per-action.

**Comment by tinmanjuggernaut** [comment]
If an InputMap is going to abstract the keys for me, then it should do the work of filtering and fire exclusively based on most specific matching.

My code should not know or care whether ui_focus_next or ui_focus_prev has more or less specific keys, whether they use modifiers or duplicate keys, or what order they should be in, as that defeats the whole purpose of the InputMap and abstracting the keys for me. 

ex.
* ui_focus_next -> S
* ui_focus_prev -> Control+S
Pressing control+s should result only in ui_focus_prev.

ex2.
* shift -> run
* space -> jump
* shift+space -> super jump
Pressing shift+space should result in run, then super jump. If the third mapping is removed, then it should result in run, then jump.

**Comment by DoctorWhoof** [comment]
I just ran into this, and was about to file a bug.
In my case it's an App with a complicated UI, not a game, and there will be tons of such conflicts, i.e:

Z: Play C4 Note on piano
Ctrl+Z: Undo

But Ctrl+Z Plays the note AND performs undo.
Since there are two piano octaves available via keyboard... yeah, there will be a ton of conflicts. 😅 

Filtering it myself would be a lot of work prone to bugs, since there's no central "UI Control" script and each part of the UI is a sub-scene and manages itself, not aware about where the conflicts may happen in other scenes. Allowing the Input system to perform this filtering as it's being suggested would be much, much welcome.

Maybe an "Exclusive" checkbox column in the Input Map editor would cover most of the cases, and stay simple enough? Checking it would only fire the action if that key, and only that key, is pressed.

Thanks!

**Comment by EricEzaM** [comment]
More Information about this bug is in #44180.

I found where the problem code is. I will have to fix this very soon as it is required for #43663 to be merged

**Comment by MuffinInACup** [comment]
Reproducible in Godot 4.1
It can be worked around with an elif setup in the correct order but figured might as well report this

Sample project: https://drive.google.com/file/d/176GERr0Lba_PfpjPdpepBfQg24ZYtmJK/view?usp=sharing

Pressing ctrl+A in the project triggers the action for a standalone A press

**Comment by pineapplemachine** [comment]
I've also just run into this. Not having a way to require that a modifier key _not_ be pressed means that I will apparently need to write my own input controller code and cannot use the one integrated with the engine if I will allow players to configure these controls. This seems like a pretty serious piece of missing functionality.

**Comment by Cheeseness** [comment]
> This seems like a pretty serious piece of missing functionality, or a serious regression if this was working before.

Just to confirm, are you saying that you still get modifier when the exact match parameter of Input.is_input_pressed(), etc. is true?

**Comment by zommerfelds** [comment]
Nice, thanks for the solution! `is_action_just_pressed(..., true)`

Would be nice if this was the default for new projects. I can't think of many cases where someone wouldn't want an exact match.
