### ISSUE TITLE
Mangled names for some Mono enum members

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#18796]
**Godot version:**
486ec499f for mono

**OS/device including version:**
Windows 7

**Issue description:**
`CSGPolygon.PathRotationEnum` members appear to be missing their first letter:
  * `ath`
  * `athFollow`
  * `olygon`

![no-p](https://user-images.githubusercontent.com/1151394/39938195-bf9c7b78-5584-11e8-8a55-f62f9bb51bd1.png)

**Edit:** 
see  also `CollisionPolygon2D.BuildModeEnum`:
 * `egments`
 * `olids`

![image](https://user-images.githubusercontent.com/1151394/44822631-a4505000-ac2e-11e8-853c-18b395598f3d.png)

**Comment by PJB3005** [comment]
This is because it tries to cut off the "prefix" from the constants, but since every value starts with `P` it counts that as prefix too.

Not sure how to even go about this.

The relevant function is `BindingsGenerator::_determine_enum_prefix` if anybody's feeling adventurous.

**Comment by neikeq** [comment]
Damn, can't believe I didn't see this issue before.
