### ISSUE TITLE
SpriteFrames editor forces window to be wider than screen

### ISSUE THREAD

**Issue by aomimezura** [godotengine/godot#18803]
**Godot version:**

3.0.2

**OS/device including version:**

Ubuntu

**Issue description:**

Opening the SpriteFrames editor resizes the Godot editor to be larger than the monitor width and cuts off part of the screen.

**Steps to reproduce:**
I'm using dual monitors, the monitor in question is 1280x1024 5:4 ratio. Expand the editor to fill the screen. Open the SpriteFrames editor and it forces some of the editor offscreen (but it doesn't overflow to the other monitor). 

If the copy, paste, insert empty, etc. buttons could wrap to the next line, this would not be an issue.

**Minimal reproduction project:**

**Comment by groud** [comment]
Closing as a duplicate.
