### ISSUE TITLE
ResourceSaver does not correctly save ImageTexture

### ISSUE THREAD

**Issue by cmfcmf** [godotengine/godot#18801]
**Godot version:** 3.0.2

**OS/device including version:** Ubuntu 18.04

**Issue description:** The ResourceSaver is not correctly saving ImageTextures (at least I think so). The `[resource]` section's `image` is set to `null`, but should be set to `SubResource( 1 )`.

**Minimal reproduction script:** This is a simple script you can run. The asserts will _not_ trigger. However, in the generated `.tres` files, `image` is set to `null`. (I hope it's okay to attach a script instead of a full project. I can also create a project, if you want me to.)

```python
extends SceneTree

func _init():
	test1()
	test2()
	
	quit()

func test1():
	var image = Image.new()
	image.create(2, 2, false, Image.FORMAT_RGBA8)
	assert(image.save_png("test1.png") == OK)
	
	var image_texture = ImageTexture.new()
	image_texture.create_from_image(image)
	assert(ResourceSaver.save("test1.tres", image_texture) == OK)

func test2():
	var image = Image.new()
	image.create(2, 2, false, Image.FORMAT_RGBA8)
	assert(image.save_png("test2.png") == OK)
	
	var image_texture = ImageTexture.new()
	image_texture.load("test2.png")
	assert(ResourceSaver.save("test2.tres", image_texture) == OK)
```
Generated `.tres` files:
```
[gd_resource type="ImageTexture" load_steps=2 format=2]

[sub_resource type="Image" id=1]

data = {
"data": PoolByteArray( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
"format": "RGBA8",
"height": 2,
"mipmaps": false,
"width": 2
}

[resource]

flags = 7
storage = 0
lossy_quality = 0.7
flags = 7
image = null
size = Vector2( 2, 2 )
```

**Comment by guilhermefelipecgs** [comment]
Also it is not possible to do this with the inspector.

**Comment by cmfcmf** [comment]
Here's the console output when running the code:
```
ERROR: _write_resource: Resource was not pre cached for the resource section, bug?
   At: scene/resources/scene_format_text.cpp:1368.
ERROR: _write_resource: Resource was not pre cached for the resource section, bug?
   At: scene/resources/scene_format_text.cpp:1368.
```

**Comment by cmfcmf** [comment]
I've done some debugging which revealed the root cause of the issue.
Saving the `ImageTexture` will call 
https://github.com/godotengine/godot/blob/a0ea57b72cfd2f3895e93545f557d0d505e0ee89/scene/resources/scene_format_text.cpp#L1460
which calls:
https://github.com/godotengine/godot/blob/a0ea57b72cfd2f3895e93545f557d0d505e0ee89/scene/resources/scene_format_text.cpp#L1482
which calls for both the `ImageTexture` (= `Image::get_data()`) and the referenced `Image` object:
https://github.com/godotengine/godot/blob/a0ea57b72cfd2f3895e93545f557d0d505e0ee89/scene/resources/scene_format_text.cpp#L1417

So far so good. Now back to `ResourceFormatSaverTextInstance::save`. It iterates through the `saved_resources` and populates the `internal_resources` map. This will set `internal_resources[<Image Object>] = 1` (line 1585), meaning that it shall be subresource 1 (which is correct).
https://github.com/godotengine/godot/blob/a0ea57b72cfd2f3895e93545f557d0d505e0ee89/scene/resources/scene_format_text.cpp#L1555-L1589
The next `for` loop now saves the resources' properties. It will first do so for the `Image` object, which it does correctly. Then comes the `ImageTexture`.
https://github.com/godotengine/godot/blob/a0ea57b72cfd2f3895e93545f557d0d505e0ee89/scene/resources/scene_format_text.cpp#L1594-L1614
It calls `VariantWriter::write_to_string` (line 1611) for the `image` property of the `ImageTexture`. This is where it _should_ write `image = SubResource( 1 )`, but instead writes `image = null` and prints 
> ERROR: _write_resource: Resource was not pre cached for the resource section, bug?
   At: scene/resources/scene_format_text.cpp:1368.

The `VariantWriter::write_to_string` calls `ResourceFormatSaverTextInstance::_write_resource`. For the reasons outlined below, the `internal_resources.has(<Image Object>)` check will return `false`, even though it should've been set to `1` (see above), resulting in `"null"` to be returned.
https://github.com/godotengine/godot/blob/a0ea57b72cfd2f3895e93545f557d0d505e0ee89/scene/resources/scene_format_text.cpp#L1353-L1375

And here's why: `ImageTexture::get_data()` uses the `VisualServer` to return the texture's data:
https://github.com/godotengine/godot/blob/a0ea57b72cfd2f3895e93545f557d0d505e0ee89/scene/resources/texture.cpp#L243-L246
which calls 
https://github.com/godotengine/godot/blob/a0ea57b72cfd2f3895e93545f557d0d505e0ee89/drivers/gles3/rasterizer_storage_gles3.cpp#L883
which **always creates a new `Image` object**
https://github.com/godotengine/godot/blob/a0ea57b72cfd2f3895e93545f557d0d505e0ee89/drivers/gles3/rasterizer_storage_gles3.cpp#L959-L961

That means two calls to `ImageTexture::get_data()` will always return **different** `Image` objects, even though the data did not change. That is why the `Image` can't be found in the `internal_resources` when looked up the second time.
To verify this is indeed the problem, I replaced 
https://github.com/godotengine/godot/blob/a0ea57b72cfd2f3895e93545f557d0d505e0ee89/scene/resources/texture.cpp#L243-L246
by 
```cpp
Ref<Image> ImageTexture::get_data() const {
    static auto data = VisualServer::get_singleton()->texture_get_data(texture);

    return data;
}
```
and now the resource is indeed saved correctly. This "solution" is obviously just a hack and probably breaks 100 other things, but shows that this really is the problem.

**Comment by maikramer** [comment]
Oh man, 2 days on this and now that i found your work, this bug is REALLY a problem to me, cause its breaking the BakedLightMap generated by code.

I will try your hack

**Comment by cmfcmf** [comment]
Is there anything else I can do to help fix this? I noticed that this issue hasn't received any labels yet.

**Comment by maikramer** [comment]
I tried to debug but i'm not able to do so, its simple to test, just create a imagetexture in code and use ResourceSaver to save it.
I have a terrain shader that use a splatmap(ImageTexture), if i create the imageTexture in code, i have almost the same error even without try to save it. my workaround is create the imageTexture in editor and just create the image in code.
My precedural terrain also try to create a baked lightmap but fails in the bake method, also because LightBaker wants a texture saved in disk, this i just gave up and used GIProbe, that bakes by code without problems.
The error you can see in #18954 .
Everything is related to the fact that Godot wants the texture in ResourceCache, this is what i think.
If you Create a ImageTexture in inspector, then try to save it to disk, also doenst work.

If you can solve this, the game my team is creating will get very happy.

**Comment by Bauxitedev** [comment]
I've also run into this issue in my [texture painter](https://github.com/Bauxitedev/godot-texture-painter). I'm trying to create a save format and I thought I'd just create a `tscn` file containing a scene tree with all texture slots (albedo, roughness, metalness and emission as 4 different sprites and ImageTextures). Unfortunately the `image` property of the ImageTexture is null so it cannot be loaded again after saving. It works if I manually replace `null` with `SubResource( 1 )` in the `tscn` file as you mentioned. Any idea for a workaround or fix? I'd rather not modify Godot's source code.

I was thinking maybe just loading the `tscn` file afterwards and and automatically replacing all instances of `null` with `SubResource( x )` and keeping a counter `x` but that won't work if I switch to `scn` which will save a lot of space when saving big textures.

**Comment by cmfcmf** [comment]
> I was thinking maybe just loading the tscn file afterwards and and automatically replacing all instances of null with SubResource( x ) and keeping a counter x but that won't work if I switch to scn which will save a lot of space when saving big textures.

That's also been my workaround, but, as you said, the `tscn` files are huge because the images can't be compressed in `tscn` files.

**Comment by DGWana** [comment]
I'd the same problem. For me just saving the Image from the TextureImage with
`my_image_to_save = my_texture_image.get_data()`
 worked fine. Then I recover the TextureImage by loading the image and using
`my_texture_image.create_from_image(my_loaded_image)`

In my case that was enough. If you're using more information from the Texture like flags, you can do
`my_image_to_save.set_meta("flags", my_texture_image.flags)`
and then on load
`my_texture_image.flags = my_loaded_image.get_meta("flags")`

**Comment by girng** [comment]
possibly related https://github.com/vnen/godot-tiled-importer/issues/97

**Comment by AlexHolly** [comment]
related https://github.com/godotengine/godot/issues/20178

One more example: ResourceSaver saves nothing
```
	var ts = TileSet.new()
	var id = ts.get_last_unused_tile_id()
	ts.create_tile(id)
	
	var i = Image.new()
	i.create(10,10, true, Image.FORMAT_RGBA4444)
	
	var texture = ImageTexture.new()
	texture.create_from_image(i)
	
	ts.tile_set_texture(id, texture)
	ResourceSaver.save("res://tileset.tres", ts)
```
