### ISSUE TITLE
Object flickers when using orthogonal projection

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#18809]
![flickering2](https://user-images.githubusercontent.com/3484686/39956240-dace0774-55dc-11e8-9af1-91668418340a.gif)

**Godot version:**
3.0.2 stable

**OS/device including version:**
Elementary OS 0.4, Windows 7

**Issue description:**
When you use orthogonal projection in editor and move the camera, object flickers. Sometimes even dissapears. Closer to the object you are, more intensive the flickering is. It doesn't happen when you are far enough.

**Steps to reproduce:**
Use orthogonal projection in editor and move with camera. Not sure if this is related to all meshes or just when you set specific parameters in shader.

**Minimal reproduction project:**
[Object Flickering.zip](https://github.com/godotengine/godot/files/1997490/Object.Flickering.zip)

**Comment by akien-mga** [comment]
May be related to #17961.

**Comment by GlaDOSik** [comment]
Could be. Btw, also gizmos and bounding box are flickering, not only the mesh itself.

**Comment by fracteed** [comment]
Can also confirm that this happens a lot under Win10 (960m) and is not a new issue. Objects often disappear and flicker when rotating the scene in ortho mode.

**Comment by oiblank** [comment]
I second this and [#17961](https://github.com/godotengine/godot/issues/17961) which is the main problem for me, there is quite a few problems with orthogonal camera, which is a real trouble for us 2D in 3D enthusiasts.

**Comment by qarmin** [comment]
I still can reproduce this with Godot 3.2
