### ISSUE TITLE
Tag property for Node ?

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#18811]
**Issue description:**
What about adding Variant called Tag to the Node for helping user ? For example user can attach integer to procedural generated button and when this button pressed the user can use this tag for various actions as it will works as button Identificator.

Also Unity have Tags on GameObjects...

**Comment by kubecz3k** [comment]
The same thing can be achieved by using meta data or groups (depending on the usage)

**Comment by KellyThomas** [comment]
You may want to look at metadata.
 There was a lengthy conversation about its future here: https://github.com/godotengine/godot/issues/18591

**Comment by Chaosus** [comment]
Ah, thanks guys, I just didnt know about metadata in Godot...
