### ISSUE TITLE
Closing a menu entry in the menu bar without moving the mouse cursor takes two clicks

### ISSUE THREAD

**Issue by Kanabenki** [godotengine/godot#18819]
**Godot version:**
* Godot 3.0.2 Windows 64-bit from the Godot website
* Godot 3.0.2 Linux 64-bit built from the Arch user repository

**OS/device including version:**
* Windows 10 64-bit
* Manjaro 64-bit (Arch-based Linux)

**Issue description:**
After clicking on a menu entry such as *Scene* in the main menu bar or *File* in the code editor menu bar, if the mouse cursor is not moved, closing the opened entry takes two clicks instead of one.

**Steps to reproduce:**
* Open an empty project
* Click on *Scene* in the menu bar
* Click again without moving the mouse, the entry doesn't close
* Click a third time and it closes

**Comment by groud** [comment]
This is fixed on master.
