### ISSUE TITLE
AnimationPlayer call function track cannot enable CollisionShape2Ds even when in physics process mode

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#18824]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
Attempting to enable a CollisionShape2D via the call function track in an AnimationPlayer (via set_disabled ) does not function even when the AnimationPlayer is set to run in physics process mode.
Not even calling a passthrough function that sets disabled to false works

**Steps to reproduce:**

Create AnimationPlayer, create Area2D with CollisionShape2D
Disable CollisionShape2D
Set AnimationPlayer tophysics process mode, create animation with call function track that uses set_disabled to enable the collision shape.
Add KinematicBody2D with CollisionShape2D, ensure it touches the Area2D's CollisionShape2D
Verify that the collision shape never enabled via scripting by connecting body_entered signals and using debug prints or breakpoints

**Comment by Warlaan** [comment]
I don't know whether you are supposed to enable or disable collision shapes at all. You weren't in Godot 2.x, but I know that it was announced that this would be changed in Godot 3.0, I just haven't checked whether it was.

For what it's worth in most cases you can use collision layers instead, so if you want to disable collision for a whole rigidbody you can just clear the collision mask and reset it later to enable collision.

**Comment by ElfEars** [comment]
Er, realtime collision shapes have been a thing since 1.1
They ARE a thing (or else fighting games would be a nightmare) just less efficient as the collision shape nodes you modify are just editor helpers and thus have to do a little hacky magic to update the actual shapes.
Either way, it seems to be something else at work here so I'm closing this.
