### ISSUE TITLE
turn(), for all nodes (canvas item)

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#1883]
I think it was good if it was possible to turn() all (canvas item) of objects including nodes (control), I found a way how to do it without this function, but it's redundant, and does not always work as I would like to .

**Comment by Kermer** [comment]
Or just simply add transform, like in Node2D, to Control

**Comment by reduz** [comment]
Control uses anchoring, which would break if they could rotate or scale.
If you want to rotate or scale them, put them as a child of Node2D

**Comment by OlexiyKravchuk** [comment]
exactly this the way I used, and it's not very comfortable, so I create this request here, in addition there is another way to do this without (Node 2D) as a parent, but it is also inconvenient, though retains the advantage of scale and anchors. I do it simply by converting 2D matrix, but in contrast to the use of 2D Node, then you need to use the script with excess code, and this is another reason why I would like to support this feature out of the box ...

**Comment by akien-mga** [comment]
See also #312.

**Comment by akien-mga** [comment]
> Control uses anchoring, which would break if they could rotate or scale.
If you want to rotate or scale them, put them as a child of Node2D

Closing as per this comment, since apparently the feature would introduce issue and is easily worked around.
