### ISSUE TITLE
Visual Scripting takes too much effort to call a function

### ISSUE THREAD

**Issue by fire** [godotengine/godot#18831]
Targeting 3.1

**Issue description:**
Visual Scripting UX takes too much effort to call a function. It takes too many clicks.

**Steps to reproduce:**

Current flow:

1. Add a new str input to the function.
![Add new str input](https://i.imgur.com/GRBvQzQ.png)
1. Drag from str input
![Drag from str input](https://i.imgur.com/g5IH6ql.png)
2. Click call (a dialog that says call / set / get) 
![Drag from str input](https://i.imgur.com/NtCB6Ln.png)
3. Type name of function constrained by type 
4. Move mouse to open and click / double click open 
![Move mouse to open and click.](https://i.imgur.com/UW2J0wD.png)

New flow:

1. Add a new str input to the function. (This is still bad...)
![Add new str input](https://i.imgur.com/GRBvQzQ.png)
1. Drag from str input
![Drag from str input](https://i.imgur.com/g5IH6ql.png)
2. Do a search constrained by type 
![](https://i.imgur.com/vpIk7JL.png)
3. Single click / press enter to create

Rid of the current flow's B, you can put those into the search bar and have it so clicking on the function name once is enough (not double clicking)

**Comment by fire** [comment]
Other ideas:

1. A plus button to add inputs and outputs on the create a function ui on the graph area
2. Create the first function _ready. Every visual script has an empty _ready function that can be deleted. It is a template.

**Comment by ironsoul** [comment]
I will agree that it's not intuitive and a bit fiddly to get anything done in visualscript at the moment. I'm exploring it as an option for my friend who is primarily interested in Art and VERYLIGHT scripting and even this feels too difficult to explore and figure out.

Perhaps node based programming is not the solution... hmm.

**Comment by fire** [comment]
Able to do this through tweaking. Anyways, the battle is winnable!

![Faster VS](https://i.imgur.com/vUXKOLn.gifv)

**Comment by girng** [comment]
that looks like it's just 1 step less lol

**Comment by fire** [comment]
https://github.com/fire/godot/tree/better_vs_ux 

This is my branch.

A) Has the new workflow for both the white line actions and methods / properties.
B) Zoom is now scroll wheel
C) Right drag moves the canvas

**Comment by fire** [comment]
Was merged. Some changes were made.
