### ISSUE TITLE
Crash when trying to close a scene with Tilemap editing active.

### ISSUE THREAD

**Issue by ByTheQuietLake** [godotengine/godot#18833]
**Godot version:**

a0ea57b

**OS/device including version:**

Windows 7

**Issue description:**

Godot crashes when you try to close a scene that just had some tiles placed on its tilemap, saved and then closed.

Crash does not occur when there is no tileset or when there are some changes that need to be saved or when the tilemap is not selected(not in tile map editing mode). It does not even crash when you do have tilemap selected but don't have the cursor enter the viewport  and close it directly.

**Steps to reproduce:**
1. Create a scene with a tilemap equipped with a tileset
2. Place some tiles on the scene
3. Save the scene with no unsaved changes present
4. Close the scene

**Minimal reproduction project:**

**Comment by ByTheQuietLake** [comment]
No does not actually. I just build from the master branch.

**Comment by reduz** [comment]
Guess this just needs testing, but seems odd that no one else could reproduce

**Comment by Ertain** [comment]
@Reduz Drat. Thanks for looking at it, Juan!

**Comment by MarianoGnu** [comment]
> Save the scene with no unsaved changes present

I'm not sure what do you mean with this, i select tilema, add some sotes, click on "Save Scene" and then close it being already saved?

**Comment by ByTheQuietLake** [comment]
@Ertain @MarianoGnu   I cant seem to reproduce this bug anymore after building from master, Do you get this issue still?
Do note I am using a laptop with igpu now while I did use a desktop with a amd 480 before(Win7 on both).

@MarianoGnu  Sorry for not being clear, what I meant is to do some work on the tilemap and save the scene after, so that you don't see this symbol (*) next to the scene name on the tab. and then close the tab by clicking on the x on that tab.

While there is no crash now, I do get the following message on the console while following the above steps:

ERROR: Object::emit_signal: Condition ' !target ' is true. Continuing..:
      At: core\object.cpp:1227

**Comment by ByTheQuietLake** [comment]
Closing this issue as there is no longer a crash, only an error output at the console as stated above and creating a new issue to address it.
