### ISSUE TITLE
Can't bake navmesh on Gridmap

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#18837]
Godot 3.0.2

Hi there,

I have a meshlib tileset with collisions, i tried to add a navmesh to the Gridmap but it bakes nothing.

https://github.com/DevMagicLord/Godot3/blob/master/bugs/gidmapnonavmesh.jpg

**Comment by DevMagicLord** [comment]
You can download the project and check navmesh only bakes on objects not on gridmaps
https://github.com/DevMagicLord/Godot3/blob/master/bugs/GiProbeGridmap.zip

**Comment by Toshiwoz** [comment]
Hey, maybe this can be helpful, as it is related:
https://github.com/godotengine/godot/issues/17118
AFAIK, GridMap does not allow Navmesh baking.

**Comment by DevMagicLord** [comment]
> AFAIK, GridMap does not allow Navmesh baking.

One way to get it work could be to bake the GridMap to a mesh.
There is a function, but it's not exposed in the editor like for example a button like "Bake to Mesh"
[](https://github.com/godotengine/godot/issues/22315)
The navigation should bake when Gridmap is transformed to one simple 3D model.
