### ISSUE TITLE
None of the mono versions are working for me

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot#18840]
So far I've tried:

- v3.0-stable_mono_win64
- v3.0.2-stable_mono_win32
- v3.0.2-stable_mono_win64
- v3.0.3-rc1_mono_win32
- v3.0.3-rc1_mono_win64

All of them except 3.0.3 crash when either loading a pre-existing C# project, or when creating a C# script.

Both versions of 3.0.3 are able to open C# projects and create C# scripts, however they don't compile.
In the output panel each script that's being used in the scene comes up with a line of red text like this:

Cannot find class 'Main' for script res://Main.cs

But it's wrong, Main.cs, consists of:

```
using Godot;
using System;

public class Main: Spatial
{
    public override void _Ready()
    {
        GD.Print("Hello World");
    }
}
```

It's like this with every .cs script file.

**Comment by oisincar** [comment]
Do you have the right Mono SDK (v5.4.x) installed and working?

**Comment by hedgehog90** [comment]
I have 5.10.1 installed.
That probably explains the crashes for the other versions, but it doesn't explain the 'Cannot find class' messages I'm getting in 3.0.3 :/

**Comment by hpvb** [comment]
3.0.3-rc2 is out now. Can you please retry?

**Comment by drako0812** [comment]
I know I'm still having this issue in 3.0.3-rc2. Is it because GodotSharp.dll and GodotSharpEditor.dll never get placed in the "$(ProjectDir)\.mono\assemblies" folder?
