### ISSUE TITLE
Unexpected behavior of async/await (wrong task scheduling?)

### ISSUE THREAD

**Issue by madadam** [godotengine/godot#18849]
I thinks the code before and after an `await` expression in an `async` method should run on the same thread, but that doesn't seem to be the case. Consider this minimal example:

```csharp
using Godot;
using System;
using System.Threading.Tasks;

public class Main : Node
{
    public override async void _Ready()
    {
        GD.Print($"Before: {System.Threading.Thread.CurrentThread.ManagedThreadId}");

        await Task.Delay(1);

        GD.Print($"After:  {System.Threading.Thread.CurrentThread.ManagedThreadId}");
    }
}
```

When attached to a node and executed, it produces output like this:

```
Before: 1
After:  6
````

Which means the code post-await runs on different thread than pre-await. I find this surprising and inconvenient, because it means that if the post-await code wants to access some state in the scene tree, it needs to be explicitly synchronized (via mutex or other means) which kind of defies the purpose of async/await in the first place. For example this code is unsafe:

```csharp

public override async void _Ready()
{
    // ... some stuff here
    await DoSomethingAsync();
    GetNode("some/path").DoSomethingElse() // <-- unsafe, possible race condition / crash
}      
```

This is a safe workaround, but it's inconvenient and/or ugly:

```csharp
public override async void _Ready()
{
    // ... some stuff here
    await DoSomethingAsync();
    CallDeferred(nameof(DoSomethingElse));
}      

private void DoSomethingElse()
{
    // safe, runs on the main thread.
    GetNode("some/path").DoSomethingElse();
}
```
Am I missing something or is this a bug?

**Godot version:**
81b1d3c846de263cf843e9e0e9d7c0c0a94f65c8

**OS/device including version:**
Linux, Ubuntu 17.10

**Comment by madadam** [comment]
OK, after a bit of digging I think I figured this out. There is this thing called `SynchronizationContext` which is responsible for scheduling task continuations. Godot provides its own implementation ([GodotSynchronizationContext](https://github.com/godotengine/godot/blob/master/modules/mono/glue/cs_files/GodotSynchronizationContext.cs)) which seems to do the right thing. Problem is this context is not properly attached to the main thread (via calling `SynchronizationContext.SetSynchronizationContext`) before the game loop runs. It is only attached in [GodotTaskScheduler.Activate](https://github.com/godotengine/godot/blob/master/modules/mono/glue/cs_files/GodotTaskScheduler.cs#L58) which gets called every frame. So when `_Ready` is called, the current synchronization context isn't set yet (`SynchronizationContext.Current` is `null`) and mono uses a thread-pool based fallback.

The fix is simple - just set the current SynchronizationContext to the instance of `GodotSynchronizationContext` before the game loop begins. A decent place to do it seems to be in the `GodotTaskScheduler`'s constructor.

I'm going to raise a PR shortly.

**Comment by tvardero** [comment]
Using async tasks freezes the game.
In the code below, program never reaches `stopwatch.Stop();` and game window is frozen.

Win10Pro x64 19044.1826
Godot v3.4.4.stable.mono.official.419e713a2

**May be important:** `<TargetFrameworks>netstandard2.1</TargetFrameworks>` in csproj file, not the Godot generated `net472`.

```c#
    public override void _Ready()
    {
        var stopwatch = Stopwatch.StartNew();

        var task1 = Task.Delay(1000);

        var task2 = TestAsync();

        Task.WaitAll(task1, task2);

        stopwatch.Stop(); // <-- Never reaches this line

        GD.Print(stopwatch.ElapsedMilliseconds);
    }

    private async Task<bool> TestAsync()
    {
        await Task.Delay(1000);

        return true;
    }
```

Changing code to syncronous execution fixes the issue:
```c#
    private async Task<bool> TestAsync()
    {
        Task.Delay(1000).Wait();

        return true;
    }
```
