### ISSUE TITLE
Enabling an external editor prevents the class search from showing

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#18844]
**Godot version:**
master branch commit 2014bb485ae9a0c63569f71be9c83c3458e3e8e4

**OS/device including version:**
Arch Linux - GCC 8.1.0

**Issue description:**
Enabling an external editor prevents the class  search window showing.

**Steps to reproduce:**
1. Open a project
2. Under Editor Settings -> Text Editor -> External enable "Use External Editor"
3. Close Godot
4. Reopen a project
5. Press F3
6. Press the "Classes" button to search for a class.
7. The window dims and stays like that regardless from clicking on other buttons and there's no class search available.

**Comment by bojidar-bg** [comment]
Can confirm on 3.1.dev.custom_build.8684b63 / Arch Linux / GCC.

**Comment by Rubonnek** [comment]
I am not able to reproduce this issue now. This has been fixed at some point within the past month.
