### ISSUE TITLE
Remote inspector is running the get function from a var with getset

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#18859]
**Godot version:**

Godot 3.02

**OS/device including version:**

**Issue description:**

The remote inspector is using the get function from a var with setget to get the value of the var.
It was expected to just get the value of the var without running the get function, but as it looks like it is running the get function. This may lead to many problems...

**Steps to reproduce:**
Create a node with a script with a var that uses setget and click the node in the remote inspector.

**Minimal reproduction project:**

[remote.zip](https://github.com/godotengine/godot/files/1999775/remote.zip)

**Comment by vnen** [comment]
This is similar to #6916. Any external entity trying to get values will invariably call the getter. There's no special path in GDScript to get the value directly.

**Comment by kakoeimon** [comment]
I close this issue cause the issue pointed by @vnen is quite similar and contains valuable discussion.
