### ISSUE TITLE
Duplicating/Copy-Pasting nodes in Visual Script unexpectedly links them

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#18854]
**Godot version:**
3.0.2 Official Build

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Duplicating nodes in Visual Script links them and they can not be used separately. They are even connect during runtime.
The is issue is also there while copying and pasting nodes.

**Suggested Source and Solution:**
The root of the problem seems to be the resource duplicate function so it seems necessary to create a separate duplicate function for VisualScriptNode like there is in the case of Image.

**Steps to reproduce:**
- Create a node with some float inputs and then duplicate it.
- Now change the value of the duplicated nodes input using the text-field.
- Now force update the GUI of the old node by deleting the newly created node or just creating a new node.
- The value will change to the new value, and it will happen no matter how many duplicates you have.

![bug](https://user-images.githubusercontent.com/19930870/39980032-6b09586c-5767-11e8-86eb-4e9d7ff51a6f.gif)

**Minimal reproduction project:**
Any VS Project.

**Comment by Linko-3D** [comment]
It link their parameters when running the game too, I had this issue with a duplicated Input node and Transform node, they were all set to the same key and same vector everytime.

**Comment by swarnimarun** [comment]
Oh hadn't checked it out. Thanks for pointing it out. I haven't created any proper games using the system.

**Comment by akien-mga** [comment]
Why close?

**Comment by swarnimarun** [comment]
Didn't want to seems like the Github Apps are useless.
