### ISSUE TITLE
get_local_mouse_pos() offset bug in the editor

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#1885]
I try to write a small editor plugin with gdscript. In my script I need the mouse coordinates in 2d world space. There for I use CanvasItem.get_local_mouse_pos() which in general seems to work fine, but there is an offset which I think may be a bug.

Take a look at the screen attached. When I position my mouse at 0,0 the printed position is about 12,98. Which seems to be the exact dimensions of the upper left rect I illustrated.
This offset is set by a zoom of 100%. Whenn I zoom in, the offset gets smaller and when I zoom out the offset gets bigger!

![local_mouse_pos_bug](https://cloud.githubusercontent.com/assets/6723918/7580546/6228c766-f877-11e4-9f27-f755efc457cd.jpg)

**Comment by OlexiyKravchuk** [comment]
I'm not sure but I think you're confused get_local_mouse_pos () function with, get_mouse_pos () function when you specify to take the local coordinates it takes out from the node of your object instead of just the viewport, and the node they differ because that they are locally .. .

**Comment by reduz** [comment]
ah there is one extra matrix you need that you probably don't have access to, I need to figure out how to get it available

**Comment by ndee85** [comment]
I wanted to bump this issue. Would be nice if this gets fixed for the editorplugin overhaul.
In addition. This does not only not work for get_local_mouse_pos() but also for viewport.get_mouse_pos(). I think it is related to this fixes issud 08e0e64.

And probably the same matrix as in the fix above has to be multiplied with the mouse coords:
https://github.com/godotengine/godot/blob/08e0e64a192940468b0f74b594fbaff32b39dfd6/scene/main/viewport.cpp#L1370


I get the viewport with: get_tree().get_edited_scene_root().get_viewport.

**Comment by remorse107** [comment]
As soon as the video was posted demonstrating the "tool" keyword at the top of the script I immediately began to perform a test and noticed the same issue.  There seems to be no way to guarantee the coordinates of the mouse position in relation to the scene's global 0,0 position.  Works perfectly in game mode, but not in the editor.

**Comment by ndee85** [comment]
@remorse107 @reduz 
I think the viewport is ingame always at position 0,0. Thats the reason why it works there. In the editor the 2d viewport is not at 0,0 and there for the printed cursor location has this offset.

**Comment by akien-mga** [comment]
What's the status on this issue?

**Comment by ndee85** [comment]
@akien-mga 
Status is still not fixed.

**Comment by reduz** [comment]
I don't completely understand this issue, you mention calling CanvasItem.get_local_mouse_pos() 
Where and when do you call this?
