### ISSUE TITLE
ProceduralSky energy doesn't do anything

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#18856]
**Godot version:**
3.0.2

**Issue description:**
While documenting the ProceduralSky class I noticed that the properties sun_energy, sky_energy, and ground_energy aren't used anywhere else in the rendering code. I even set up a basic test scene and tried changing them around to see if I was missing something and no matter how the values were set there was no change in the scene. If I changed the background_energy property in the environment then a huge difference was apparent immediately. 

Can someone who knows more about the internal renderer confirm this?

**Comment by creole** [comment]
Just to confirm that these properties don't change anything either when accessed through code, e.g;.
`environment.background_sky.ground_energy = 0`
Godot version 3.0.4

**Comment by karroffel** [comment]
I think this has little to do with the renderer and more with the generation of the procedural sky that doesn't use them. The renderer doesn't know anything about any procedural skies. All it sees is textures and buffers, there's no special "procedural sky creation" code in the renderer, it's probably somewhere in `scene/` as a high-level construct.

**Comment by clayjohn** [comment]
Your right. It was incorrect to call it rendering code. What i was referring to was sky_box.cpp in scene/resources/ which generates the sky. It has functions and bindings to set and get sky_energy and ground_energy but it doesn't use them anywhere in the generation process. I thought maybe they would appear somewhere in the rendering code but i couldnt find anything.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
