### ISSUE TITLE
How to rotate view in 3D scene by mac magic mouse ？

### ISSUE THREAD

**Issue by lengyue524** [godotengine/godot#1886]
I'm using mac book and mac magic mouse。but I can't rotate view in 3D scene。
Do I need to use 3 button mouse？

**Comment by kubecz3k** [comment]
I don't know what mouse you should use, but I'm unsure if issue tracker is good place to ask that kind of questions.. Try with forums first and try to gather more info to be sure if you want to post feature request or report a bug. There are 600 opened issues on this tracker, some of them are not really a issues, please respect a developers a little ;-)

**Comment by akien-mga** [comment]
Yes it looks like currently only a middle mouse button can be used to pan the view in 3D scenes. There is another bug report about this (#53), so I'll close this one as a duplicate.
