### ISSUE TITLE
3.0.3rc2 mono export issue on windows 10

### ISSUE THREAD

**Issue by exts** [godotengine/godot#18873]
**Godot version:**
3.0.3.rc2

**OS/device including version:**
Windows 10

**Issue description:**
After exporting using 3.0.3.rc2 templates I get this error after running executable.

```
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
Mono: Initializing module...
no access to .mono/assemblies/mscorlib.dll
ERROR: FileAccessWindows::_get_modified_time: Method/Function Failed, returning: 0
   At: drivers\windows\file_access_windows.cpp:290
no access to .mono/assemblies/mscorlib.dll
ERROR: FileAccessWindows::_get_modified_time: Method/Function Failed, returning: 0
   At: drivers\windows\file_access_windows.cpp:290
Mono: Runtime initialized
no access to .mono/assemblies/System.dll
ERROR: FileAccessWindows::_get_modified_time: Method/Function Failed, returning: 0
   At: drivers\windows\file_access_windows.cpp:290
Mono: INITIALIZED
Found class ProjectGiada.Application.Global for script res://Application/Global.cs
Found class ProjectGiada.Application.Splash for script res://Application/Splash.cs
no access to .mono/assemblies/System.Core.dll
ERROR: FileAccessWindows::_get_modified_time: Method/Function Failed, returning: 0
   At: drivers\windows\file_access_windows.cpp:290
ERROR: ResourceFormatLoaderText::load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: scene\resources\scene_format_text.cpp:1225
ERROR: Failed loading resource: res://scenes/StartMenu.tscn
   At: core\io\resource_loader.cpp:186
ERROR: Error loading resource: 'res://scenes/StartMenu.tscn'
   At: core\bind\core_bind.cpp:79
```

The second error I get if I attempt to switch scenes:

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
  at ProjectGiada.Application.Global.DeferredSwitchScene (System.String path) [0x0001f] in <bae74f1b3b714486aa3460dc8bbc48b6>:0
```

**Steps to reproduce:**
- Just export project
- Copy dll's from editor project and run exe.

Notes: Runs fine in the editor.

**Minimal reproduction project:**
[PGTest.zip](https://github.com/godotengine/godot/files/2002665/PGTest.zip)

**Comment by hpvb** [comment]
On Linux/64 I see the same messages but the project appears to run fine. Does the project work for you?

**Comment by exts** [comment]
@hpvb on windows it runs, but i can't switch scenes it doesn't load at all.

**Comment by hpvb** [comment]
Hmm, on Linux/64 the project does switch scenes. The second scene is empty though. But it is empty in the editor also.

**Comment by exts** [comment]
@hpvb ah yeah the second scene isn't empty.  https://i.imgur.com/PyooZGO.png this is the scene

**Comment by exts** [comment]
Going to close this issue now @hpvb the issue was a pathing issue. it was trying to read `res://scenes/StartMenu.tcsn` but the folder is `res://Scenes/StartMenu.tcsn`
