### ISSUE TITLE
CollisionShape2Ds that start off disabled and are enabled in runtime have inconclusive behaviour

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#18872]
Edit: Download updated with new version.

**Godot version:**
3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
Area2Ds with CollisionShape2Ds enabled in runtime that start off disabled have inconclusive behaviour when sending signals such as "body_entered" and "area_entered"

**Steps to reproduce:**
Create Area2D with CollisionShape2D, 
set the CollisionShape2D to start disabled and enable it after 0.1 secs via animation
Create KinematicBody2D or Area2D with a(n enabled) CollisionShape2D
Make a scene where they intersect.
Observe that no signals are emitted from the first Area2D

**Minimal reproduction project:**
I've compiled a reproduction project below.
I suggest you run the main scene several times and monitor the output.
(in the past I've gotten different results each reset)
(The current setup appears to have no varience but it is still incorrect) 
I also suggest you attempt removing (and adding) bodies and areas from the main scene.
It appears to alter the wierdness.
Also: debug view of collisionshapes in runtime is mandatory
PS. If you're wondering what the inherited/not inherited stuff is, I was having trouble with stuff in my game so I theorized that the problem only affected inherited scenes. Inheritance appears to have no effect on the results.

[Area2D Runtime Enable Test.zip](https://github.com/godotengine/godot/files/2069221/Area2D.Runtime.Enable.Test.zip)

**Comment by KoBeWi** [comment]
Seems fixed in 3.2
