### ISSUE TITLE
PopupPanel will focus and hover buttons in the panel when popup

### ISSUE THREAD

**Issue by chenjie199234** [godotengine/godot#18879]
when popup a popuppanel,the button in the panel will be hovered and focused.
in the test example.when click the popup button the popuppanel will show and button1 will be hovered with red rectangle.
the theme onle set hover is red and press green
here is the example
[Test.zip](https://github.com/godotengine/godot/files/2003467/Test.zip)

**Comment by mhilbrunner** [comment]
Reopening, as this is still a valid issue.

**Comment by KoBeWi** [comment]
Seems working in 3.2.3
