### ISSUE TITLE
Editor Settings - some odd behaviors/appearance

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#18874]
**Godot version:**
Godot 3.0.3 rc2 

**OS/device including version:**
windows 7

**Issue description:**
Listing of odd things I noticed in the Editor Settings section
1) setting property after resetting
![reset_property_bug](https://user-images.githubusercontent.com/10463138/40021965-d63a8dae-57c6-11e8-827c-357bce79b3dc.gif)
2) ~~duplicate incorrect settings~~ _problem with old editor_settings-3.tres file_
![duplicatet_properties](https://user-images.githubusercontent.com/10463138/40022709-0fb0d230-57c9-11e8-9d4b-01b1ba47f33a.gif)
3) search behaves like a filter (search hits should be marked)
![search_like_filter](https://user-images.githubusercontent.com/10463138/40023518-a0a2e75e-57cb-11e8-8b99-279bf7182bd3.gif)
4) sentence with a punctuation mark (look a little off)
![image](https://user-images.githubusercontent.com/10463138/40024573-05cd3a00-57cf-11e8-933d-3bc814989751.png)
5) move Network setting **Debug Host** to sub category **Network/Debug**

**Comment by akien-mga** [comment]
Some of those might be due to having an old `editor_settings-3.tres` from pre-3.0 dev builds. Do you still get those issues if you reset your config? (rename/delete the file)

**Comment by YeldhamDev** [comment]
The first issue was already reported: #12233

**Comment by puppetmaster-** [comment]
@akien-mga problem no.2 is gone when I delete existing editor_settings-3.tres file

The problem on point three is confusing. (You found something, but you still can't do anything with it)
As a solution I would suggest, if the search hit is a category the setting inside should not be filtered out.

**Comment by puppetmaster-** [comment]
I will close this issue, it is already very old and if there is still a demand I will apply for it again at the new dedicated Godot Improvement Proposals ([GIP](https://github.com/godotengine/godot-proposals)) issue tracker.
