### ISSUE TITLE
Godot 3.0.3 rc2 Crash

### ISSUE THREAD

**Issue by NedJaims** [godotengine/godot#18870]
**Godot version:**

Godot 3.0.3 rc2

**OS/device including version:**

Windows 10 x64 bits

**Issue description:**

Godot crashea, when I create a project and godot is in the process of importing this crashea and in the console I see this:
![bug](https://user-images.githubusercontent.com/36456992/40012694-0e0b654c-5771-11e8-8942-dd7eb6428f2a.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
CC @hpvb

**Comment by hpvb** [comment]
Is it possible for you to share this project with us?

**Comment by NedJaims** [comment]
Sorry, but I think it was something that was wrong with my pc; I tried to install programs and had problems. At the end I chose to reinstall windows and it worked perfectly.
Thanks for the support. :)

**Comment by hpvb** [comment]
no worries, thanks!
