### ISSUE TITLE
Signals are not duplicated with their parent node when created from editor UI

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#1888]
*Bugsquad edit:* Initially seen in 1.1 rc2 and still exists in 2.0 alpha  b2f9acb8c96aed0505cbac21661e21e4acef710f commit

**Update2 (20.01.2016)**
One more time, a better test project to test the issue: [DuplicateTests.zip](https://github.com/godotengine/godot/files/97359/DuplicateTests.zip)

**Update:**
New sample project that replicate this issue in more straightforward way:
https://dl.dropboxusercontent.com/u/168251/godot/bugsquad/NotDuplicatedSignalIssue.7z
Also small video that shows how issue has been replicated in this sample (for quick judge):
https://youtu.be/_fYBUKBWzrA

**Old** (not so relevant currently) content:
It seems that VisibilityEnabler/Notifer is not working if it's on a scene that has been duplicated with .duplicate() method. Below is a link to sample project that illustrates the problem.
https://dl.dropboxusercontent.com/u/168251/godot/some/issues/DuplicateIssue.7z

**Comment by kubecz3k** [comment]
It looks like this bug is caused by the fact that signals are not duplicated (if they were set from gui).

**Comment by kubecz3k** [comment]
Changed title to better reflect actual issue. I can confirm it still happens in Godot 2.0 alpha b2f9acb8c96aed0505cbac21661e21e4acef710f
Here is new test case that test the issue in more straightforward way:
https://dl.dropboxusercontent.com/u/168251/godot/bugsquad/NotDuplicatedSignalIssue.7z

**Comment by neikeq** [comment]
This was fixed by the above PR, but was not closed automatically.

**Comment by kubecz3k** [comment]
Unfortunately the fix was only partial, signals that are emitted by internal (not scene root) nodes are still lost during duplication.
I have prepared small project that tests various things related to duplication method and report results in the following form:
```
----Testing signal duplication----
Root signal duplicate status: SUCCESS
Inner signal duplicate status: FAIL
 
----Testing group duplication----
Root node group duplicate status: SUCCESS
Inner node group duplicate status: SUCCESS
 
----Testing dynamic structure duplication----
Translation test: SUCCESS
Root export variable test: SUCCESS
Inner export variable test: SUCCESS
Root variable value test: FAIL
Inner variable val test: FAIL
Inner node structure test: SUCCESS
 
------- Final result------- 
Summary result: FAIL
```
Here is projects for testing these things:
[DuplicateTests.zip](https://github.com/godotengine/godot/files/97338/DuplicateTests.zip)

**Comment by kubecz3k** [comment]
Related issue but with variable values: https://github.com/godotengine/godot/issues/3393

**Comment by vnen** [comment]
There might be a problem if someone actually wants a shallow copy. Recursively copying all variables, signals, groups, and stuff will create an overhead if the programmer does not want to duplicate the state, but only the structure. IMO this should be optional and default to a shallow copy.

**Comment by kubecz3k** [comment]
@vnen I assume signals can be safety duplicated under the condition that both emitter and receiver are inside duplicated node. Currently it don't work even if emitter and receiver is the same node. 
When it comes to copying internal variables there is another issue about this but generally I think it should be on by default (exported variables are copied currently after all), with eventual possibility to create your copy manually instead of using build one mechanism via duplicate() method overriding .

**Comment by akien-mga** [comment]
I think this was fixed recently, can you confirm?

**Comment by akien-mga** [comment]
Tested with the above-linked project and signal duplication seems to work fine now:
```
----Testing signal duplication----
Root signal duplicate status: SUCCESS
Inner signal duplicate status: SUCCESS
 
----Testing group duplication----
Root node group duplicate status: SUCCESS
Inner node group duplicate status: SUCCESS
 
----Testing dynamic structure duplication----
Translation test: SUCCESS
Root export variable test: SUCCESS
Inner export variable test: SUCCESS
Root variable value test: FAIL
Inner variable val test: FAIL
Inner node structure test: SUCCESS
 
------- Final result------- 
Summary result: FAIL
```

The issue about the failed test for root and inner variable values is likely #3393, so closing this one as fixed.
