### ISSUE TITLE
Make license and copyright info available in GDScript

### ISSUE THREAD

**Issue by ibrahn** [godotengine/godot#18888]
It might be useful to expose the information from `editor/license.gen.h` in GDScript, to make it easy to build license screens, like the about page in the editor

**Comment by akien-mga** [comment]
That's planned already, and it's on my TODO list for this week :)
https://github.com/godotengine/godot/issues/6745#issuecomment-256144607

**Comment by akien-mga** [comment]
Thanks, I'll have a look at it tomorrow.
