### ISSUE TITLE
Error with SCons while Compiling Godot

### ISSUE THREAD

**Issue by abhaskumarsinha** [godotengine/godot#18890]
I've never had such a strange error while working on Linux Before. A few days back I reinstalled windows 7 _86 (32 bit) on my PC. Then I installed Python 2.7 and SCons Latest version on my PC.

I'm using Visual Studio C++ Compiler (Build tools) 2017 here.

I get an error here, whenever I try to make a windows Binary.

```
C:\godot-gles2\godot-gles2>c:/python27/scons.bat p=windows
scons: Reading SConscript files ...

scons: warning: No version of Visual Studio compiler found - C/C++ compilers mos
t likely not set correctly
File "C:\godot-gles2\godot-gles2\SConstruct", line 3, in <module>

scons: warning: No version of Visual Studio compiler found - C/C++ compilers mos
t likely not set correctly
File "C:\godot-gles2\godot-gles2\SConstruct", line 71, in <module>
Configuring for Windows: target=debug, bits=default
Found MSVC compiler: x86
Compiled program architecture will be a 32 bit executable. (forcing bits=32).
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str':
  File "C:\godot-gles2\godot-gles2\SConstruct", line 327:
    detect.configure(env)
  File "./platform/windows\detect.py", line 343:
    configure_msvc(env, manual_msvc_config)
  File "./platform/windows\detect.py", line 196:
    env.Append(CPPPATH=[os.getenv("WindowsSdkDir") + "/Include"])

C:\godot-gles2\godot-gles2>
```

It never happened with Linux Before.

I'm a newbie with MSVC, so Can anyone help me why this error is coming with SConstruct File of Godot. I don't understand this error.

**Comment by Calinou** [comment]
Which Git commit are you using locally? Based on the directory name, it looks like you're attempting to build a third-party branch (I may be mistaken).

**Comment by abhaskumarsinha** [comment]
I'm trying to compile @karroffel 's fork, but the same is with the current master build. I don't use git, I download the code using zip on github

**Comment by abhaskumarsinha** [comment]
hello anyone managed to find the problem here?

**Comment by mhilbrunner** [comment]
The `WindowsSdkDir` environment variable appears to not be set for whatever reason. Either set it manually or reinstall Visual Studio and make sure it gets properly set.
