### ISSUE TITLE
TextEdit.CursorSetLine(), bool as default for arg3

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#18895]
**Godot version:**
0738ba6 - mono

**OS/device including version:**
windows

**Issue description:**
My godot project fails to build with this message:

````
TextEdit.cs(336, 85): A value of type bool cannot be used as a default parameter because there are no standard conversions to type int.
````

This is the code in question:

````csharp
[GodotMethod("cursor_set_line")]
public void CursorSetLine(int line, bool adjustViewport, bool canBeHidden = true, int arg3 = true)
{
    NativeCalls.godot_icall_4_657(method_bind_6, Object.GetPtr(this), line, adjustViewport, canBeHidden, arg3);
}
````

**Comment by KellyThomas** [comment]
Yes.

Is it based on the docs xml files?

The new parameter was added in #14848 but isn't in TextEdit,xml  yet.

**Comment by PJB3005** [comment]
This is because the documentation XML file wasn't updated I think.

**Comment by neikeq** [comment]
The method bind is missing both the name (`"wrap_index"`) and default value (`DEFVAL(0)`) of the last parameter:

https://github.com/godotengine/godot/blob/3b8bd50b41e0197ab3bce653548715872a93ea80/scene/gui/text_edit.cpp#L5998
