### ISSUE TITLE
[WebGL2] Black shading

### ISSUE THREAD

**Issue by lastrodamo** [godotengine/godot#18892]
**Godot version:**

3.0.2

**OS/device including version:**

Nvidia Geforce GTX980 driver 387.22 on Archlinux 17.11
Firefox 59.0.2

**Issue description:**

I have a bad black shading on the pillow of the chair on html 5 export
But the shading is ok on godot rendering
Here a screenshot of the shading problem
![bad_shading_html_export_video_ram_import_bug_m](https://user-images.githubusercontent.com/10653143/40060096-144589d4-5856-11e8-9eaf-0e7b8b65da66.jpg)
Perhaps i think this will be of the Video RAM Compress file
I want to Reimport with Lossless compression and Normal map disabled of the image tissue.jpg of the chair's pillows
But Godot reimport to Video RAM compression

**Steps to reproduce:**
Download this file [chair.zip](https://github.com/godotengine/godot/files/2005180/chair.zip)
Dowload html export template for godot 3.0.2
Launch Html 5 Export : Project > Export > HTML5 > S 3tc with the name index.html
Execute index.html on Firefox or Chromium

**Minimal reproduction project:**

**Comment by 37TS** [comment]
With firefox, what is the webconsole showing when loading and running the project?
When I export with "S 3tc" I see the following:

- Error: WebGL warning: compressedTexImage2D: COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT requires that width and height are block-aligned, or, if level>0, equal to 0, 1, or 2. Chair.js:4:227559
- Error: WebGL warning: drawElements: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE.

**Comment by LinuxUserGD** [comment]
For me everything works when I pick all checkboxes in the export menu.

**Comment by clayjohn** [comment]
We are no longer working on the WebGL2 backend due to poor driver support on most systems. We recommend you use the GLES2/WebGL backend instead. 

Unfortunately, that means this bug just isn't going to be fixed in GLES3/WebGL2, sorry.
