### ISSUE TITLE
More significative and descriptive names for built-in scripts in Script tab

### ISSUE THREAD

**Issue by samdze** [godotengine/godot#18900]
**Godot version:**
Godot 3.0.2 official.

**Issue description:**
<img width="289" alt="schermata 2018-05-15 alle 17 26 10" src="https://user-images.githubusercontent.com/19392104/40067601-cc8bfa68-5866-11e8-9a73-4dc9cbf2e831.png">
Names displayed in the Script tab for built-in scripts are not indicative of their behaviour or/and origin.
I suggest to directly show the **scene name + script id** instead of **GDScript(####)** (**treasure_small.tscn::1** in this case) and to keep the current message on mouse hover.

**Comment by vnen** [comment]
Isn't this the same as #14577?
