### ISSUE TITLE
Control inside viewport steals focus of other control elements outside of the viewport

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#18908]
**Godot version:** 3.0.2

**OS/device including version:** Arch Linux, x64

**Issue description:**

Control nodes overlapping a ViewportContainer don't receive input if there is a Control Node inside the Viewport also convering the area in question.

Example:
![screenshot from 2018-05-15 21-32-11](https://user-images.githubusercontent.com/5209613/40079244-7d63f47e-5887-11e8-887a-70e15a921001.png)
This is the SceneTree for an application that has a "Top Bar" with menu items. The rest of the screen is occupied with a ViewportContainer, which shows a nice spatial world. That Viewport also contains a Control node which occupies the whole size of the Viewport that is supposed to catch some events.

Now if the menu buttons are activated, the menu items will overlap with the Viewport, **but the menu items can't actually be clicked**.

**Steps to reproduce:**

1. Add some UI, possibly popups.
2. Create a ViewportContainer so that the popups will overlap with it.
3. Fill ViewportContainer with a Viewport that contains a  large Control node that will occupy the overlapping space of the popups.
4. Try to click popus.

(see example project)

**Minimal reproduction project:**

[viewport-control-bug.zip](https://github.com/godotengine/godot/files/2006416/viewport-control-bug.zip)

**Comment by and3rson** [comment]
I can also reproduce this.

**Comment by KoBeWi** [comment]
Resolved in 4.0-dev.
