### ISSUE TITLE
Consisted stuttering / frame drops every few seconds 

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#18936]
Godot 3.0.2
Intel HD Graphics 630 *and* NVIDIA GeForce GTX 1050
Created a project with just a slowly rotating quad with a flat shader:

![capture](https://user-images.githubusercontent.com/13801432/40129228-aa5ba964-592b-11e8-8e5f-34e3bab65241.PNG)

If you follow a corner of the quad visually, you'll notice a stutter every once a few seconds. Printing out the frame rate this appears to correspond to delta times above 17ms. While 17ms might be tolerable, examining the data further shows drops to 33ms every 30s or so:

OS.get_ms_time - delta in _process
> 2300 - 0.133333
2397 - 0.133333
7082 - 0.018959
15290 - 0.03416
31369 - 0.076607
43466 - 0.018043
62398 - 0.0334
65795 - 0.033267
113320 - 0.033276
115370 - 0.018379

Here's the zip:
[Glitching Project.zip](https://github.com/godotengine/godot/files/2009930/Glitching.Project.zip)

This alone keeps me from migrating from 2.1, which does not appear to have the same issue with an equivalent project. Also, it does not appear to be my machine specific as I've seen it been mentioned at least 3 times before posting this.

**Comment by Zylann** [comment]
Jittering has been mentionned for years https://github.com/godotengine/godot/issues/2043
Also:
- Make sure you aren't running the game with remote scene tree active
- Try with an exported game

**Comment by Calinou** [comment]
A [jittering fix](https://github.com/godotengine/godot/pull/17353) was recently merged in the `master` branch. Can you please test with a recent Git `master` build? Thanks in advance :smiley:

**Comment by rokasv** [comment]
> Jittering has been mentionned for years 
Makes it a problem worth solving then.

@Calinou the fix did in fact fix the jittering! had both .exes running side by side and the difference was very clear, supported by the new build not printing any values.

This is the version used (would be nice to be able to copy-paste the version):
![capture](https://user-images.githubusercontent.com/13801432/40148461-fec96664-5965-11e8-88a9-6969dbf3e28f.PNG)

This along with gles 2.0 will make 3.1 will leave no reason to stay on 2.1. Thanks.

**Comment by akien-mga** [comment]
Sounds like it :)
