### ISSUE TITLE
Popup scaling issue with custom editor font size

### ISSUE THREAD

**Issue by michaeldesu** [godotengine/godot#1893]
When I set the editor font to unicode 14pt Noto Sans, I found one instance where I can't press the create or cancel buttons on the "create script" dialog due to overlapping UI (text) elements interfering with buttons (see the attached for comparison between normal & user-specified font). Other than this case, I've not found an issue with using a larger font (except a trivial issue with About dialog text overflowing to beyond the dialog box dimension). I will try using a smaller font size...so this is JFYI for the future.. 

![image](https://cloud.githubusercontent.com/assets/11791450/7608034/9840d0cc-f9a9-11e4-8e40-9a0ebf47a1eb.png)

About dialog (when using 14pt font - JFYI only)
![image](https://cloud.githubusercontent.com/assets/11791450/7608141/324d6950-f9aa-11e4-9ca8-7f151fc95484.png)

**Comment by akien-mga** [comment]
Setting to the 2.1 milestone for now, though it would be a nice-to-have for 2.0 if it could be fixed before.

**Comment by neikeq** [comment]
I am not sure, but this may be an issue with AcceptDialog and ConfirmDialog not using a BoxContainer.

**Comment by reduz** [comment]
I fixed this when implemented HiDPI, should no longer be a problem
