### ISSUE TITLE
Calculations no longer works in new inspector

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#18932]
**Godot version:**
since 005b69c

**OS/device including version:**
Windows10

**Issue description:**
Calculations in number fields no longer works eg if you enter 1920 / 2 nothing happens, in old ui this feature was very useful.

**Comment by akien-mga** [comment]
Likely a regression from 005b69cf.

**Comment by reduz** [comment]
Yeah this needs to be done in a non-hacky way

**Comment by ordigdug** [comment]
@akien-mga @reduz I'm going to take a crack at adding calculations back into the inspector.
