### ISSUE TITLE
GUI Control sizing/positioning initially incorrect

### ISSUE THREAD

**Issue by ibrahn** [godotengine/godot#18940]
**Godot version:**
e62e7fd768467aad9452cacf7331caee7f730020

**Issue description:**
Several parts of my UI/menu screens are now placed/sized incorrectly.
In most cases it appears to be containers being sized as if they have no contents, but I'm not sure at the moment.

Similar problems can be seen in a couple of places in the editor UI:

In the project settings, the first time you select a property with a horizontal slider, the slider appears lower down. Reselecting it will put the slider in the right place.
![project_properties](https://user-images.githubusercontent.com/24498832/40137935-7f60350a-5943-11e8-9e8a-cbdc699e0422.png)

On the Help->About screen, the details do not appear on the first three tabs (Authors, Donors and License) until the tab is visited a second time. I suspect part of the UI is being sized as if it was empty.
The content of the Thirdparty License tab overflows its parent the first time it's viewed:
![about_page_overflow](https://user-images.githubusercontent.com/24498832/40138479-abc65632-5944-11e8-9613-8fe7b9c52f9c.png)

The smallest related example I've found so far is Popup.popup_centered() will position the popup incorrectly the first time. The top left of the popup will be in the center of the screen.
See example project below:

**Minimal reproduction project:**
[gui_testing.zip](https://github.com/godotengine/godot/files/2010455/gui_testing.zip)
Press 'p' for the popup. Note the first time it appears it is not correctly centered.

**Comment by TailyFair** [comment]
I think related:
![something wrong](https://user-images.githubusercontent.com/27275873/40139546-e4a98852-5958-11e8-9e51-70df384ae5dd.gif)

**Comment by volzhs** [comment]
it seems regression from 005b69cf6e276209464cc8c36ebc7376679925b6

> Changed UI resizing code, gained huge amount of speed.

cc @reduz

**Comment by maikramer** [comment]
No resize at all here:
![captura de tela de 2018-05-16 17-37-50](https://user-images.githubusercontent.com/8235076/40142751-eea38c82-592f-11e8-8519-8c9aa92caed4.png)

**Comment by ibrahn** [comment]
3b1ea51e4 seems to be involved too, at least for the about screen.
It somehow causes the Tree and RichTextLabel on the third party tab to be sized without respect to the size of their container.
