### ISSUE TITLE
No easy way to properly draw a texture used  in 3D also in an editor plugin UI

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#18941]
Godot 3.0.2

I'm writing a plugin that needs to show textures used in 3D, but in the UI.
Problem is, if I do that, they get converted between sRGB and linear color spaces in various ways, depending on the draw order (also I can't just ask the user to have two versions of their textures for that purpose, that would be silly).

So my current workaround is to manually load full textures uncompressed using ImageTextures everytime I need to display one, which is a bit inefficient and a hassle to deal with.

In some areas I could use the texture previews used by the editor (when I don't need a high res version), however there doesn't seem to be a way to get those previews?

**Comment by Calinou** [comment]
This is now solved in the `master` branch as the Vulkan renderer uses bindless textures. This means a single texture can use different flags depending on where it's used (including simultaneously).
