### ISSUE TITLE
Transmission texture makes a mesh look extremely bright

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#18953]
**Godot version:**
`master` / 224d5371ff65a

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
I made a grayscale 'thickness map' for a humanoid character, representing where the skin is thick (like abdomen) with brighter colors and the opposite (like ears, or nose) with darker tones.

The intention was to mimic the effect of reddish subdermal tint of human skin to be shown through when the light hits thin areas of the body.

But I wasn't able to achieve the effect with any texture and color combination since using a texture image always resulted in extremely bright colors.

This image shows how my model looks like with an all black image used as a transmission texture (with moderately bright red color):
![transmission-all-black](https://user-images.githubusercontent.com/2367032/40150147-e91f6e10-59b2-11e8-8eea-d6153dcba579.png)

And this shows how it looks like with an all white texture:
![transmission-all-white](https://user-images.githubusercontent.com/2367032/40150160-f9f47348-59b2-11e8-9eb0-3ce8748a0fc0.png)

**Comment by reduz** [comment]
No thickness support in transmission right now, its too difficult to do with OpenGL due to limitations in ho the sampler works. Will be done properly in Vulkan.

**Comment by mysticfall** [comment]
Another reason to wait for the Vulkan support then. Thanks for the info!

**Comment by reduz** [comment]
I fixed a bug in transmission some weeks ago, so closing this.

**Comment by mysticfall** [comment]
Great, thanks! :)
