### ISSUE TITLE
Autoloads without the tool keyword run and draw in the editor

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#18956]
**Godot version:** 3.1 custom build ba134d4

**Issue description:** Since #18545, all autoloads will run and draw in the editor even without the tool keyword, as in this test project [Test.zip](https://github.com/godotengine/godot/files/2011278/Test.zip).

**Expected behavior:** Only autoloads with the tool keyword should actually be running and drawing in the editor.

**Comment by akien-mga** [comment]
Confirmed with [Escoria](https://github.com/godotengine/escoria), if you run the project (in the `device` folder), you should see a grey bar at the top of the window and it crashes on exit. Commenting out the autoloads in the `project.godot` fixes it.
