### ISSUE TITLE
Restrict range for subsurface scattering

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#18952]
**Godot version:**
`master` / 224d5371ff65a

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
It seems that the sub-surface scatter creates multiple 'ghosting' images of the original mesh which can be especially noticeable when combined with other effects like transmission.

The image shows how it looks with subsurf scatter at 0.2 (with transmission effect). As you can see, the shilouettes of multiple juxtaposed images appear in shadowed areas:
![sss-0 2](https://user-images.githubusercontent.com/2367032/40149848-1802b05e-59b1-11e8-9f68-b529d5f7f4e6.png)

And it becomes more noticeable if I increase the value to 0.5:
![sss-0 5](https://user-images.githubusercontent.com/2367032/40149943-b9bbc34a-59b1-11e8-9deb-8c76e7063ac9.png)

**Comment by reduz** [comment]
Not a bug, you just set the value too high, simply use it as a blur with a smaller value.

**Comment by reduz** [comment]
Actually lets do this, I will change this to an enhancement for 3.2 (which will likely break compat)

**Comment by Calinou** [comment]
Is this still relevant with the new SSS implementation?

**Comment by clayjohn** [comment]
The range in the new implementation is much better, put at its highest you still get a little bit of artifacts when zoomed in, but not like in this issue.
