### ISSUE TITLE
GitHub issue flair addition: "Minimal reproduction project"

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#18950]
Flair would be added if there is a minimal reproduction project included in the issue, enabling better prioritization by maintainers. Thoughts?

**Comment by KellyThomas** [comment]
While they are handy for issues to which they are applicable, for many issues a repro project would be irrelevant.

**Comment by vnen** [comment]
I don't think this would help that much. My question is: do you want that to be easier *for you* to find potential issues to fix? If it's not for you, then it's just speculation.

While sample project definitely help pinpoint the origin of issues, in the end contributors will search issues in the area they're more familiar with.

**Comment by Calinou** [comment]
We don't currently plan to add a `mrp` label, but we now [require all issues to include a minimal reproduction project if asked by a maintainer](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project).
