### ISSUE TITLE
Split segment in curve (in Path2D) does not split curve

### ISSUE THREAD

**Issue by Hubber116sx** [godotengine/godot#18958]
**Godot version:**
v3.0.2

**OS/device including version:**
Linux

**Issue description:**
When manually adding points to a Path2D, clicking on one of the created curves of a Path2D does not split the curve with a new point when such action is implied when hovering the mouse over the add point tool. 

The pop-up statement is this:
"Add Point (in empty space) 
 **Split Segment (in curve)**""

**Steps to reproduce:**
1) Create a Path2D.
2) Manually add points to the Path2D.
3) Attempt to split a one of the curves with the "Add Point (in empty space) Split Segment (in curve)" tool.

**Comment by IoriBranford** [comment]
Persists in 3.0.6

**Comment by remorse107** [comment]
Path2D would be a so much more useful if splitting was working.  Should work like splitting a Polygon2D.
