### ISSUE TITLE
improve Node.get_filename ()

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#1895]
_ready ():
SELF_RES_SCENE = get_filename ()

SELF_RES_SCENE will be empty, but if get_filename () call in the running process, it works well.

**Comment by TheoXD** [comment]
I don't see why this wouldn't work inside of ready, Please provide an example project.

**Comment by okamstudio** [comment]
the filename is set when you call instance() on the packedscene, I guess
you are probably checking on the wrong node

On Thu, May 14, 2015 at 9:31 AM, TheoXD <notifications@github.com> wrote:

> I don't see why this wouldn't work inside of ready, Please provide an
> example project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1895#issuecomment-102023032>.
>



-- 

*OkamStudio*

**Comment by okamstudio** [comment]
are you sure you are not checking it on _init() ?

On Thu, May 14, 2015 at 9:38 AM, Juan Linietsky <juan@okamstudio.com> wrote:

> the filename is set when you call instance() on the packedscene, I guess
> you are probably checking on the wrong node
>
> On Thu, May 14, 2015 at 9:31 AM, TheoXD <notifications@github.com> wrote:
>
>> I don't see why this wouldn't work inside of ready, Please provide an
>> example project.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/okamstudio/godot/issues/1895#issuecomment-102023032>.
>>
>
>
>
> --
>
> *OkamStudio*
>



-- 

*OkamStudio*

**Comment by OlexiyKravchuk** [comment]
https://www.dropbox.com/s/jlbstfrwekqpbfy/ProstoyUI.7z?dl=0 
while I was doing this demo, I found something that changes the question of the problem, to reproduce, run this demo several times the editor, there is also a comment in the script.

**Comment by TheoXD** [comment]
@OlexiyKravchuk , I'm just going to citate what was written earlier:
"are you sure you are not checking it on _init() ?"
Because no wonder it doesn't work, the object is just being initialized, and doesn't have all the properties yet. And why do you call _init() from _ready()? Because you can?

And it always prints the output, make sure you scroll all the way down in the console otherwise you won't see the new output. It can happen that the debug stops working if another process is using the same port (like another instance of godot running the game).

**Comment by OlexiyKravchuk** [comment]
@TheoXD
1) because I took that phrase differently than now, X))

2) I wrote this several reasons ...
1. where the bad example, but I do not remember where.
2. I'm not a professional programmer, I'm just an amateur who learn on their own to practice empirical method of spear, I never had a mentor, or even someone who could to prompt, and I do not know all the nuances, but try very hard to find out ...
3. And yes! because I can, (PS this is the most important reason, and my favorite;)) :))

3) Yes, do not worry, I'm completely scroll down to see of all lines of addition there can be clearly seen when they add new and I have to follow this intently.

and I have another question, if there is a function _init (), but it can not use data about the object that is to be initialized, then what you can do there is to use the values? what's win over simple static initialization?

**Comment by OlexiyKravchuk** [comment]
Hi again, today I spent more tests, initialization, live code and found additional information about the second call _init () from _ ready (). I found out that only this way, function calls, forcing it to give me the desired effect of the initialization, all the defined variables.
1) if you comment out this line call will happen only the first automatic call _init () function. before calling the function _ ready (), but will not initialized variables.
2) I tried to rename the function _ init () by changing only its function name (and in the definition and at the call site), and everything else did not touch, I did it to prevent the first call _init () function before _ ready () but did not comment the second call to the renamed _init () in, ready _ (), and in such case renamed function _init () also did not give the desired initialization.
3) and only if the function _init () possess its name, ie calling and to call _ ready (), and inside _ ready (), it finally occurred actual initialization, all I needed fields.

**Comment by TheoXD** [comment]
Let me make this very clear:
_init() is a Constructor, where you define class members that hasn't been defined yet
_ready() is where all class members are already set and you are free to redefine them

**Comment by OlexiyKravchuk** [comment]
Yes, thank you, I certainly understand that the _init () plays the role of constructor in this case, and I apologize for the, obsessive ignorance, but there is I do not understand the other collision ...
Imagine that each parent class from which this class inherits causes corresponding constructor in order from the oldest ancestor, and right up to the calling the constructor _init (), which is the last in the queue constructors and if there is a function Node.get_filename () in the senior ancestor class "Node", then, according to the rule of this class constructor must be called first, am I right?
And if I am right, even in the previous point, in the intended field, which is definitely in a class "Node" in his constructor, as the parent, had to be flooded and existence after the calling the constructor "Node", and then even in the first call _init () I can only override it, but it turns out that in reality, it is not true, and I can not cause has yet initialized field in the constructor of ancestor, so I need to invent the wheel. Where did I go wrong, or maybe all arranged differently?
