### ISSUE TITLE
Autotile 3x3 fix breaks compatibility with the common minimal 3x3 tileset

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#18959]
I would like to raise this issue in response to  #16511 and its fix #18619

**Issue description:** The mentioned pull release does allow uncommon tile configurations, but the fix itself completely breaks usability when using common tile configurations. Compare 
![aa](https://user-images.githubusercontent.com/35355161/40154481-80697d58-595c-11e8-9815-d2ad8193890a.png)
 with and without #18619.

I would argue that the most common use case for 3x3 tilesets is found on this [site](http://www.cr31.co.uk/stagecast/wang/blob.html), specifically, the minimal 3x3 tileset with only 48 tiles. The code that #18619 removes was most likely put there to ensure that such tilesets work.

Now I agree that allowing uncommon tile bitmasks is a useful feature but I doubt most projects will make use of it. On the contrary, people will be confused as to why Godot doesn't support the simplest 48 tileset format shown above. As far as I understand, there is no easy way to fix this.

**Suggestion:** Add a bitmask mode such as BITMASK_3X3_MINIMAL that specifically supports the tileset above and runs the code removed by #18619. BITMASK_3X3 can be left as it is.

**Comment by akien-mga** [comment]
CC @MarianoGnu @mateusak

**Comment by MarianoGnu** [comment]
Now remember why i did it that way in thefirst place

**Comment by mateusak** [comment]
The best way to solve this is to address #18134
