### ISSUE TITLE
how to use depth in shader？

### ISSUE THREAD

**Issue by ywaby** [godotengine/godot#18965]
i want to use depth to simulation light fade in water.  
like shader in unity water4
![](https://docs.unity3d.com/uploads/Main/Water_ReflectiveRefractive.png)
```c
half depth = SAMPLE_DEPTH_TEXTURE_PROJ(_CameraDepthTexture, ,NITY_PROJ_COORD(i.screenPos));
depth = LinearEyeDepth(depth);
edgeBlendFactors = saturate(_InvFadeParemeter * (depth-i.screenPos.z));
edgeBlendFactors.y = 1.0-edgeBlendFactors.y;
baseColor.a = edgeBlendFactors.x * saturate(0.5 + refl2Refr * 1.0);
```
but i can't find depth in godot fragment shader, how to achive it?

**Comment by Megalomaniak** [comment]
I can't recall which however in `SpatialMaterial` look for `proximitly_fade` and `distance_fade` parameters towards the end of the inspector. Enable both and then convert the material to `ShaderMaterial`. Experiment with those. IIRC one of those should be able to help you achieve what you are looking to-do.
