### ISSUE TITLE
GD.Print() prints 'Null' with non-Godot type objects.

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot#18969]
Here's an example...

```
public class Thing
{
    public string ToString(string format)
    {
        return "Thing";
    }

    public override string ToString()
    {
        return "Thing";
    }
}
```

```
var thing = new Thing();
GD.Print(thing);
```

The output you get is:

```
Null
```

**Comment by Chaosus** [comment]
You can workaround it by `GD.Print(thing.ToString());`

**Comment by KellyThomas** [comment]
This looks very similar to the restriction on passing user defined classes at signal parameters.

In that case one solution is to inherent `Godot.Object` instead of `System.Object` as you are in the example above.

**Comment by aaronfranke** [comment]
> You will be able to use Console.WriteLine instead.

Sounds good, but since GD.Print is shorter to type, it would still be nice to improve that as well.

**Comment by Kowbell** [comment]
> Then I remembered we should be redirecting mono's print and printerr to the editor output dock, so I prefer to leave this as is. 

I am very much interested in contributing to Godot and getting `GD.PrintErr()` output to show in the output console is a feature I've been seriously pining for. As a heads up, I'm going to start investigating this. I'll report back to this issue with any updates!
