### ISSUE TITLE
New Property Editor no more hover information

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#18964]
**Godot version:**

e62e7fd

**OS/device including version:**

osx

**Issue description:**

Hovering over the properties in the new PropEditor does not show the property path anymore ("translation:x" for example)

This is inconvenient when setting up something like tween.

**Comment by ibrahn** [comment]
Should be fixed by e62e7fd768467aad9452cacf7331caee7f730020
It works for me at the moment

**Comment by toger5** [comment]
This is the exact commit have compiled. 
But ill try again and report if it works.

**Comment by toger5** [comment]
tested again and it works now!
