### ISSUE TITLE
reflection no correct

### ISSUE THREAD

**Issue by ywaby** [godotengine/godot#18961]
![screenshot from 2018-05-17 12-34-07](https://user-images.githubusercontent.com/12198203/40156974-064f2554-59cf-11e8-8396-0c680d7c65a4.png)

large object relection data no correct

**Comment by akien-mga** [comment]
Please include a minimal project that can be used to reproduce the issue, nobody can fix a bug with a screenshot.

**Comment by ywaby** [comment]
https://github.com/ywaby/godot-WaterPack

**Comment by ywaby** [comment]
the reason is reflection probes postion will effect reflection result.
so how to place reflection probe?

**Comment by Calinou** [comment]
Reflection probes are not intended to be used for planar reflections over large areas such as water; they simply cannot reflect things accurately in this case. Same goes for screen-space reflections, which are more suited to reflect small details.

The solution here would be to use planar reflections, but they're not implemented in Godot yet.

**Comment by ywaby** [comment]
@Calinou 
OK, i will use camera to get reflection effect,like unity.
but how to right use reflection probe? Like
![](http://docs.godotengine.org/en/3.0/_images/refprobe_ssr.png)
