### ISSUE TITLE
Its not possible to do horizontal indent on LineEdits/RichTextLabel ?

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#18972]
**Godot version:**
latest

**OS/device including version:**
no matter

**Issue description:**
I creating complex UI system for my project, and Godot have a lot of required instruments..
What I need now is LineEdit(and RichTextLabel) to be Left Align but with some offset from beginning

![image](https://user-images.githubusercontent.com/3036176/40177648-d8a9519c-59e7-11e8-8a65-b600e7498502.png)

It is possible with current system, or not ? If not somebody should implement it...

**Comment by Zylann** [comment]
Maybe the theme or options for that LineEdit should have configurable inner margins?

**Comment by Chaosus** [comment]
Yeah, I tried most of them in theme settings and inspector but didnt find required one..

**Comment by ibrahn** [comment]
I think the Content Margin section of the StyleBox resource might do what you're looking for

**Comment by Chaosus** [comment]
@ibrahn Thanks ! That exactly what i need..
