### ISSUE TITLE
Can't drag and drop resources into inspector

### ISSUE THREAD

**Issue by ibrahn** [godotengine/godot#18970]
**Godot version:**
e62e7fd768467aad9452cacf7331caee7f730020

**OS/device including version:**
Debian (Buster)

**Issue description:**
Dragging resources from the filesystem panel into properties on the inspector doesn't work at the moment.
Over the property the cursor is a cross (as it is when can_drop_data returns false).
Dropping has no effect.

Tested with:
StreamTexture into Sprite.texture
Theme into Control.theme
AudioStreamSample into AudioStreamPlayer.stream

**Comment by Chaosus** [comment]
Yeah, its a regression from brand new inspector...

**Comment by volzhs** [comment]
fixed by c5182a580a292327583b92c17a53cf6cc85d133d
