### ISSUE TITLE
Setting a global rotate and scale may lead to a broken Basis

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#18987]
Spatial has global rotate and scale methods, but those may not work in general when a node in the chain (apart from the node at the very end of the chain) contains a non-uniform scale.

Consider a chain two just two nodes, and just consider the basis part for simplicity; the global basis is Bg = (Rp.Sp)(R.S) where Rp and Sp are scale and rotation of the parent node. When you apply a global scale S', the new global basis becomes Bg -> S' Bg = S'.(Rp.Sp)(R.S), and the current code, `set_global_transform`, updates the node's local scale as AffineInverse[(Rp.Sp)].S'.(Rp.Sp).(R.S). When S' and Sp are uniform scales, they're simply proportional to identity and can be moved around freely like AffineInverse[(Rp.Sp)].S'.(Rp.Sp).(R.S) = AffineInverse[(Rp.Sp)].(Rp.Sp).(R.S'.S) resulting in (R.S'.S).

But when Sp or S' is a nonuniform scale, the resulting basis is no longer a rotation-scale matrix in the form R.S (but rather M.R.S where M is S' in the inverted parent-frame), which is an assumption made almost everywhere in the code base ---it can rather for example involve shearing, in which case  `set_global_transform`  can break stuff *silently* when used.

I don't see a way this can be fixed, but we can add checks (wrapped by MATH_CHECKS) and warn the user when this happens.

**Comment by tagcup** [comment]
Regarding the implementation of such a check; if a Basis instance is indeed valid, meaning has the form B = R.S, then it should satisfy

(B^T).B = [(R.S)^T].(R.S) = [(S^T).(R^T)].(R.S) = (S^T).S = S.S == diag(sx^2, sy^2, sz^2)

and we can add this as a function like Basis::is_valid, and call it from set_global_transform and other similar places (wrapped with MATH_CHECKS, of course). 

And this caveat should probably be mentioned in the documentation of set_global_transform and possibly other functions which call it. We may even consider discouraging users from using `set_global_transform`, which probably comes up when working with skeletons or custom physics, or alternatively discourage nonuniform scale at large.

**Comment by aaronfranke** [comment]
Can you provide a minimal reproduction project that shows an example of when this can happen?

**Comment by TokageItLab** [comment]
@aaronfranke For un-normalized scales, the transformation will be forced to be normalized in the next transformation with local coordinates, causing a sudden transformation.

https://user-images.githubusercontent.com/61938263/127756227-12cde8eb-a360-4dce-bccc-774d98868909.mov

**Comment by TokageItLab** [comment]
I see, it's bad that local-transform forces the scale to be uniform. Normalization should not be undertaken rashly, when rotating a matrix of non-uniform scale, it should be rotated with keeping non-uniform scale.

**Comment by TokageItLab** [comment]
As a first step, I sent a PR #51164 to unify gizmo's behavior, which has been inconsistent for a while. This should allow us to implement a mode that does not break Basis' orthonormal with consistent.
