### ISSUE TITLE
The tilemap editor freezes when updating the undo_redo buffer

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#18996]
**Godot version:** 942e0c4

**Issue description:** The tilemap editor freezes for a few seconds when painting tiles, erasing, etc. Most slowdowns that I trigger occur when releasing mouse buttons. The slowdown gets worse as the number of tiles set increases, but in my case, it starts at around 150 drawn tiles and becomes unbearable around 200. This is a pretty big roadblock for anyone drawing levels with tilemaps. Such problems with the tilemap editor are noted in #12391 and #18486 but they're more general and didn't garner much attention. 

By commenting out some parts of tile_map_editor_plugin.cpp, I am pretty sure this issue is caused by updating the undo_redo buffer. For example, when painting tiles, the slowdown that occurs *when releasing* the left mouse button goes away when commenting out lines 788, 789:
```
undo_redo->add_do_method(node, "set", "tile_data", node->get("tile_data"));
undo_redo->commit_action();
```
Compare before and after commenting out the lines above.
![with](https://user-images.githubusercontent.com/35355161/40225831-29c85f12-5a58-11e8-9579-4c2333035488.gif) ![without](https://user-images.githubusercontent.com/35355161/40225834-2ce79302-5a58-11e8-9ca0-0571610b51bf.gif)

I'm not familiar with how undo_redo works, so could someone try to optimize the plugin? If this doesn't help, maybe an option to bypass the undo_redo system would be needed?

**Comment by akien-mga** [comment]
Reopening as #19127 was reverted.

**Comment by wombatwingdings** [comment]
I get this problem too. Was OK in v3.0 stable but not in trunk head today. Works OK in very small example but not anything of reasonable size.
