### ISSUE TITLE
New inspector: right-clicking on resource doesn't show context menu

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#18994]
**Godot version:**
Godot 3.1 942e0c4

**OS/device including version:**
Linux Mint 18.3 Cinnamon x64

**Issue description:**
You used to be able to right-click anywhere on a resource in the inspector to show its context menu,
alongside clicking the arrow to the right of it. The new inspector doesn't have this functionality yet, so I'm making this issue to keep track of that.

**Comment by Aaron-Fleisher** [comment]
Compiling now, very excited this was fixed!
