### ISSUE TITLE
Feature set_hinting for DynamicFonts not functioning.

### ISSUE THREAD

**Issue by romeojulietthotel** [godotengine/godot#18991]
**Godot version:**

git master

**OS/device including version:**

Linux

**Issue description:**

Not able to set_hinting. The feature is documented but not working.

**Steps to reproduce:**

wontonfonton = DynamicFont.new()
wontonfonton.set_font_data(preload("res://fuhfuhfafont.ttf"))
wontonfonton.set_hinting(0)   <- **BOOM** <- **POW**

**Minimal reproduction project:**

**Comment by romeojulietthotel** [comment]
This commit seems relevant and possibly it's incomplete. i.e. more code is needed to wire everything up to make it work

https://github.com/godotengine/godot/commit/96bda9c463b08797493bb39d639f96f12a8d7dbb

**Comment by Calinou** [comment]
It is working, but there are some caveats:

- You should call `set_hinting()` on the DynamicFontData resource, not DynamicFont.
- If loading a DynamicFontData from the editor, it **must** be saved to a resource (`.tres` preferably, or `.res`) so that the hinting property can be saved to disk (and the project can actually make use of it).

**Comment by romeojulietthotel** [comment]
Alright, I did not understand that. I will test this out, I have to rebuild. Shall I keep open as a reminder for making this work for DynamicFont?

**Comment by Calinou** [comment]
Actually, I can confirm it isn't working anymore as of commit https://github.com/godotengine/godot/commit/66871322b99436990daec5a70c09620619430b8d. The editor setting for font hinting is also ineffective.

**Comment by Calinou** [comment]
This was fixed by https://github.com/godotengine/godot/pull/19843 a while ago, closing.
