### ISSUE TITLE
New inspector displays preview images of gradient textures at their full width

### ISSUE THREAD

**Issue by JFonS** [godotengine/godot#18999]
**Godot version:**
942e0c4

**Issue description:**
The new inspector displays preview images of gradient textures at their full width. The default width for gradient textures is 2048 so the editor window gets huge and stretched. Haven't tested with other types of texture previews.

**Steps to reproduce:**
Open a gradient texture in a nested inspector and give it some values.

**Comment by AndreaCatania** [comment]
Confirmed
