### ISSUE TITLE
Emulate Touchscreen doesn't work

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#19005]
**Godot version:**

Godot 3.1 compiled with b003b7d846a2aa2369a13f957131fdbc1c1cd398

**OS/device including version:**

Arch Linux (X11)

**Issue description:**

Cannot emulate screen touch with mouse drag any more.

**Steps to reproduce:**
Enable `Display/Window/Emulate Touchscreen` in the project settings.
Create a ScrollContainer and put a TextureRect and set a large image as texture.
Run the project and drag the ScrollContainer with your mouse.

**Comment by volzhs** [comment]
it's removed since #17196
there was related issue was reported #18582
and it's fixed by #18755

so, at the bottom line, you need to look at Project settings > Input Devices > emulates...

**Comment by Geequlim** [comment]
@volzhs  Thanks!
