### ISSUE TITLE
Connecting Node Signals from the editor does not fill the functions with the required vars.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#19001]
**Godot version:**

Godot b003b7d846a2aa2369a13f957131fdbc1c1cd398

**Issue description:**
I chechek only LineEdit Signal text_entered and SpinBox value_changed but it looks like that this is a general problem.
It was expected to create a function like this :
`
func _on_LineEdit_text_entered(new_text):
	pass # replace with function body
`
but it created this :
`
func _on_LineEdit_text_entered():
	pass # replace with function body
`
new_text is missing.

**Comment by BastiaanOlij** [comment]
Happens to me consistantly

**Comment by YeldhamDev** [comment]
It sometimes gives the wrong arguments for me.

**Comment by jahd2602** [comment]
Sometimes it generates no params (first 2 cases in the video), and sometimes it generates a completely different set of params (3rd case in the video), in that case, it had to generate:
```gdscript
body_shape_exited(body_id, body, body_shape, area_shape)
```
and, instead, it generated:
```gdscript
body_shape_exited(area)
```
Video:
[![](https://img.youtube.com/vi/H1asTFrZucA/hqdefault.jpg)](https://www.youtube.com/watch?v=H1asTFrZucA)
