### ISSUE TITLE
Inspector Label Text Input reversed

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#19008]
Godot Master

Reproduce:
Cntl+D for duplicating the Node.
![peek 2018-05-18 15-52](https://user-images.githubusercontent.com/4741886/40238695-3c060e66-5ab4-11e8-9f9a-929f7a771142.gif)

**Comment by MatiasVME** [comment]
I have the same problem:

![expandeditor](https://user-images.githubusercontent.com/342117/40271478-d0dc8aee-5b6b-11e8-8583-69b1f9ef9477.gif)

**Comment by hedgehog90** [comment]
I've got the same issue.
@MatiasVME shows another problem whereby on expanding the text editor, on the first keypress the window disappears but the dark overlay remains.
Requires restart.

**Comment by toger5** [comment]
Anybody working on this? It's a quiet important issue to solve!

**Comment by guilhermefelipecgs** [comment]
@toger5 I worked on this.

**Comment by remorse107** [comment]
3.1rc appears to have re-introduced this problem.  I'm trying to enter text in a label from within the property section and the text entered is going in reverse order.

**Comment by akien-mga** [comment]
You mean 3.1 rc 1, or a specific commit?

**Comment by remorse107** [comment]
9d36ce2

**Comment by akien-mga** [comment]
I can't reproduce in 91d3ea0.

**Comment by remorse107** [comment]
It is probably me.  I discovered that if I put the animation player into affect, while trying to also edit the text of the label being animated (rotation and scale) that entering text is reversed.  It appears to be fighting for focus and then not positioning the cursor in the text box in the correct location.
