### ISSUE TITLE
look_at resets scale

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot#19000]
Call reset on a spatial with a scale that isn't (1,1,1) and see what happens.

**Comment by kakoeimon** [comment]
This is not a bug of the method look_at, but the way this function is implemented. I suggest if you want to achive a similar functionality with the look_at but keep scale to use Quads.

**Comment by hedgehog90** [comment]
Ok, should probably mention that in the documentation then because that behaviour will not be expected to newcomers.

**Comment by kakoeimon** [comment]
I agree with you. 
By the way the discription of the function always seemed misleading to me.
Check this out : https://github.com/godotengine/godot/issues/11717

**Comment by QbieShay** [comment]
Anyone working on a solution for this? It is very annoying.
