### ISSUE TITLE
Look_at not starting from the Node rotation

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#19003]
**Godot version:**
Godot 3

**Issue description:**
Look_at function should be start from the Node rotation .. not from 0 or 90
it should be smooth rotation

download the project and see 
press the Arrow the move the Target , press Space bar to start looking at the target
it must start from the node rotation to be smooth rotation .. not from 0 or 90 degree

**Minimal reproduction project:**
[Look_at.zip](https://github.com/godotengine/godot/files/2016702/Look_at.zip)

**Comment by kubecz3k** [comment]
Not sure if I understand the issue correctly, but `look_at` works in global coord system, so you need to use global positions. If you have direction then you need to do something like `look_at(global_transform.origin + lookDir)`

**Comment by Calinou** [comment]
I think ghost wanted to have an "offset" for the node rotation applied after `look_at()`. Isn't this a matter of just calling `look_at()` then adding the angle you need to the `rotation` property every frame?

**Comment by KoBeWi** [comment]
It's unclear what this issue is about and the author is no longer with us, so closing.
There is new `lerp_angle()` function that probably addresses it.
