### ISSUE TITLE
Remote Inspector loses focus

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#19006]
Godot Master 1fc7973a00e17025441b6b8333e38d1606c1d304
x11 
![peek 2018-05-18 14-26](https://user-images.githubusercontent.com/4741886/40234554-94436ef0-5aa7-11e8-993f-ff3b3c9df73b.gif)

Reproduce:
Click and wait a second

**Comment by Geequlim** [comment]
Related to #13346

Same problem caused by the inspector force updated.

**Comment by AlexHolly** [comment]
It also steals the focus using "Search Help" is not possible.
