### ISSUE TITLE
Navigation get_simple_path doesn't optimize straight lines in 3D.

### ISSUE THREAD

**Issue by Gyrth** [godotengine/godot#19011]
**Godot version:**
3.0.2
**OS**
Ubuntu Linux 18.08

I've been using the Godot Navigation system and noticed that my character sometimes does a little dance around nav target when they are very close to each other. I've made the nav targets visible by spawning a cube in the locations and I noticed that the ones in a straight line don't get optimized out. Is this by design?

I use this to generate the nav path.
`var path = navigation.get_simple_path(starting_point, end_point)`

![image](https://user-images.githubusercontent.com/14081613/40241959-8969302c-5abc-11e8-8a55-9775d056fc55.png)

![image](https://user-images.githubusercontent.com/14081613/40242608-5c80ccda-5abe-11e8-8f99-ba36b147b623.png)

**Comment by Einlander** [comment]
A habit that I have picked up from other engines is to have a threshold for each waypoint. If they are within a specific distance from a point go to the next one. This avoids the circle dance that sometimes happens, and adds some variation so it does not look exactly the same every run.

**Comment by Calinou** [comment]
This may have been resolved by https://github.com/godotengine/godot/pull/34776.

**Comment by timcode77** [comment]
I do think that my test project (https://github.com/godotengine/godot/issues/48361) presents an interesting case that exemplifies how pathfinding with Navigation2D get_simple_path() is broken. Please have a look at it if you're interested in understanding the bug. I would say this is high priority given getting shortest paths easily is an expected basic process in game engines. Sorry if this comment isn't appropriate for here; I'm new!

**Comment by Calinou** [comment]
> I would say this is high priority given getting shortest paths easily is an expected basic process in game engines.

The current navigation is known to be broken in `3.x`, hopefully the new NavigationServer in 4.0 should do a better job at it.

**Comment by timcode77** [comment]
> The current navigation system is known to be broken in `3.x`. Hopefully, the [new NavigationServer in 4.0](https://godotengine.org/article/navigation-server-godot-4-0) should do a better job at it.

That's good to know. How can I help update the 3.x documentation to warn users so they don't waste their time?

**Comment by Calinou** [comment]
> That's good to know. How can I help update the 3.x documentation to warn users so they don't waste 
their time?

Done here: https://github.com/godotengine/godot/pull/48367

**Comment by smix8** [comment]
This is the same issue for 3D paths as #60277 for 2D.
