### ISSUE TITLE
Dof Blur doesn't detect Sprite3D.

### ISSUE THREAD

**Issue by ninetones** [godotengine/godot#19018]
**Godot version:**

3.03 rc2

**OS/device including version:**

windows10, Intel HD Graphics 515

**Issue description:**

As in the picture below, Dof near/far blur effect doesn't detect the distance to Sprite3D nodes. 
The Upper part of the Godot icon is blurred because there is no close objects behind it.

![default](https://user-images.githubusercontent.com/25213070/40249058-d471370e-5b0c-11e8-9904-323a3c72865f.PNG)

**Comment by bojidar-bg** [comment]
@ninetones Try setting "Flags/Alpha Cut" to "Opaque Pre-pass". That way, it would write to the Z-buffer properly.

**Comment by ninetones** [comment]
Worked fine,thank you!
I'm not sure if something needs to be changed for better usability.
Anyway I couldn't find the way.

**Comment by bojidar-bg** [comment]
Well, I will tag it as "documentation" for now.

@reduz and others: do you think it makes more sense to have opaque pre-pass enabled by default, or is it too much of a performance hit in typical scenarios?

**Comment by uheartbeast** [comment]
Is it possible to make it write to the z-buffer properly without turning on opaque pre-pass? Turning it on is fine for pixel art but if you have a texture with softer edges it ruins it.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/28240 and https://github.com/godotengine/godot/issues/40948.
