### ISSUE TITLE
Inspector press Tab while Edit Mode

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#19012]
Godot Master

In the old Inspector Tab switched to the next property (x,y in position), but  this is currently not possible.

I have to Confirm first with Return and then Tab works.
Would be nice to confirm with Tab and go to next property(edit mode).

![peek 2018-05-18 18-06](https://user-images.githubusercontent.com/4741886/40245675-9a0d156a-5ac6-11e8-9acc-224526dfe341.gif)

**Comment by ordigdug** [comment]
Related Issue: #18982

**Comment by ordigdug** [comment]
@AlexHolly This issue has been fixed in latest master, I believe it was one of the inspector fixes pull requests merged around 4 Jul.

**Comment by vnen** [comment]
"Godot master" is not a good description because the target shifts pretty much every day. It's better to put a specific commit hash.

**Comment by AlexHolly** [comment]
Looks like this is broken again. It jumps to the next but not into edit mode.

**Comment by AlexHolly** [comment]
Master branch always.. https://github.com/godotengine/godot/commit/89e1b302b504feb1cea218adcc6fac77c8ae0052

**Comment by akien-mga** [comment]
> Master branch always..

Yes, but when talking about regressions, the commit hash is the most important piece of information. Especially if it was not valid 8 days ago and is valid today.

**Comment by PJB3005** [comment]
This works again on master (80a8636aa3739822b1ebbbad39f932a176ec158d) but it doesn't select the next field for editing. You have to hit enter first before you can enter numbers which is kinda akward.

**Comment by AlexHolly** [comment]
works on https://github.com/godotengine/godot/commit/bf1c81adf4b1584470318d25fa2ef67e261874cf
