### ISSUE TITLE
Environment maps not build with sky based viewport texture

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#19028]
**Godot version:**
Master 19 May 2018

**OS/device including version:**
Windows 10 PC but doesn't matter

**Issue description:**
Now that #18159 makes it possible to use viewports for the sky texture, unfortunately things only half work. The maps generated from the texture that drive the PBR shader aren't being build:
![sky_no_reflection](https://user-images.githubusercontent.com/1945449/40263228-a4506ae0-5b52-11e8-99d9-0aa204a02d05.PNG)

This should look like this:
![sky with reflections](https://user-images.githubusercontent.com/1945449/40263247-e28419ce-5b52-11e8-8a2b-81f56e451922.PNG)

**Steps to reproduce:**
1. Create a 2D viewport and add some nice things in there so there is content to show
2. Add a camera to your main view, give it an environment, set the background to PanoramicSky and assign a viewport texture with your viewport (you may need to do that last part in _ready or the texture proxy won't be in place yet)
3. Add a cube mesh in your scene visible by the camera and give it a material with a high metallic setting so its reflective.

**Minimal reproduction project:**
Checkout this branch of my skyshader asset:
https://github.com/BastiaanOlij/godot-sky-asset/tree/use_proxy_fix

**Comment by Malkverbena** [comment]
I got the same issue.
