### ISSUE TITLE
get_rpc_sender_id() returns 0 when sender was self

### ISSUE THREAD

**Issue by CosineP** [godotengine/godot#19026]
**Godot version:** 3.0.2 Stable

**OS/device including version:** Debian Buster

**Issue description:** When you `rpc` yourself, `get_rpc_sender_id` returns `0`, instead of the expected `[your network id]` i.e. `1` or `707033679`

If this is expected, consider this issue "please document that...."

**Steps to reproduce:**

    sync func test():
        print(get_tree().get_rpc_sender_id())
    func send_test():
        rpc("test")

**Minimal reproduction project:** 
[rpc-issue.zip](https://github.com/godotengine/godot/files/2018965/rpc-issue.zip)

**Comment by hilfazer** [comment]
You can't RPC yourself. If you do
rpc_id( get_tree().get_network_unique_id(), "functionName" )

debugger will show an error message and function will be called locally. It's documented here:
http://docs.godotengine.org/en/3.0/tutorials/networking/high_level_multiplayer.html?highlight=rpc

"The sync keyword means that the rpc() call will go via network and execute remotely, but will also execute locally (do a normal function call)."

**Comment by CosineP** [comment]
Oh, ok, I understand the behavior now.

It's too bad, tbh. "rpc yourself" should behave *like* a normal function call, it's extremely useful often. I get that attempt to rpc yourself error a lot and have to fix it :(
