### ISSUE TITLE
Stuck in the removed directory in scene selection dialogbox

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#19022]
**Godot version:**
228b09b

**OS/device including version:**
Windows 7 64 bit

**Issue description:**
Stuck in the removed directory in scene selection dialogbox (open, instance, add autoload, etc)

**Steps to reproduce:**
1. In any project create a new directory 'test' in Godot's file manager
2. Select 'Scene->Open Scene...'; navigate to 'test' directory and click 'Cancel'
3. Remove 'test' directory
4. Select 'Scene->Open Scene...' => stuck in the removed directory ("Go to parent folder" doesn't work), but can exit by changing text in path bar

**Comment by Calinou** [comment]
I can partially reproduce this in Godot 3.2.2beta4. That said, the EditorFileDialog is still in the removed directory after removing it and choosing **Scene > Open Scene** again. The "parent folder" button works as expected though.
