### ISSUE TITLE
RigidBody2D mass is not taken into account in the first physics processing loop when applying an impulse

### ISSUE THREAD

**Issue by Pxllux** [godotengine/godot#19024]
**Godot version:**
3.0.2
**OS/device including version:**
Win 10 (1709)
**Issue description:**
Applying an impulse of 100 to a rigid body with mass 100 is expected to result in a speed increase of about 1. In Godot this is true if the impulse is applied in any physics processing loop except the very first.
When applied in the very first call to _physics_process, the resulting speed is close to 100, as if the mass were 1 instead of 100.

**Steps to reproduce:**
Create a simple scene (or download the attached one, below) with a Node2D having a RigidBody2D  (with a collision shape and a sprite or polygon node to render it) as only child.
Set the mass of the RigidBody2D to 100 and set gravity scale to 0.
Attach the script below to the RigidBody2D. This allows to specify the loop in which the impulse will be applied by setting property 'Poke In Loop' and prints the status of the object for the 20 first loops.
Setting 'Poke In Loop' to 1 will result in a speed close to 100, setting it to 2 or more gives a speed close to 1.

    extends RigidBody2D
    export (int, 1, 10, 1) var poke_in_loop = 1
    var loopCounter = 0
    
    func _physics_process(delta):
    	loopCounter += 1
    	if loopCounter == poke_in_loop:
    		apply_impulse(Vector2(0, 0), Vector2(100, 0))
    	if loopCounter < 20:
    		print("loop ", loopCounter, " mass: ", mass, " linear velocity: ", linear_velocity)

**Minimal reproduction project:**
[Physicsloop.zip](https://github.com/godotengine/godot/files/2018826/Physicsloop.zip)

**Comment by Calinou** [comment]
@Pxllux Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Pxllux** [comment]
No, I can't. Even in 3.0.2 I can't anymore (windows installation and physics drivers have received updates over time.)

**Comment by crapola** [comment]
This bug is still in 3.3.2 stable.
