### ISSUE TITLE
bugs about mouse_mode,window_size,borderless etc..i have to say this engine cant use now...example uploaded

### ISSUE THREAD

**Issue by chenjie199234** [godotengine/godot#19033]
can we just dont waste the efforts on the awesome effects now.
basic function is more important
Example is bolew!
godot version 3.0.x
pc:win10 1803
there are 3 bugs:
mouse_mode:MOUSE_MODE_CONFINED.i dont know how to say about this.just useless~
borderless mode/window mode: take a look on the label at the buttom of the scene
window_size:useless gray bar ,black bar on side and buttom(all these resolution is 16:9)
[Test.zip](https://github.com/godotengine/godot/files/2019191/Test.zip)
![t e f9g 9leqbidqf6g mi9](https://user-images.githubusercontent.com/29348971/40276148-e1debba4-5c34-11e8-919c-c87e83418672.png)
![ro8nmfybm e iw506qr prg](https://user-images.githubusercontent.com/29348971/40276149-e223e5f8-5c34-11e8-828a-6bba2d889dfa.png)
![xg59s qm d 6hhtml mx1 t](https://user-images.githubusercontent.com/29348971/40276150-e2d600bc-5c34-11e8-8050-2f4c2151bc30.png)
![8kd8 j clc3cldbu0 _a j](https://user-images.githubusercontent.com/29348971/40276151-e3631fec-5c34-11e8-9fe4-bda439162ab4.png)

**Comment by guilhermefelipecgs** [comment]
I tested your project and don't see any problem, everything worked as expected here. Tested on Linux.

**Comment by chenjie199234** [comment]
@guilhermefelipecgs 
my pc is windows 10 1803version.

**Comment by chenjie199234** [comment]
@mysticfall @
@guilhermefelipecgs

**Comment by Zireael07** [comment]
chenjie closed all of his issues in a snit :/
