### ISSUE TITLE
SurfaceTool spams output if not setting an index array

### ISSUE THREAD

**Issue by anasofgo** [godotengine/godot#19047]
**Godot version:**
Godot 3.02

**OS/device including version:**
Windows 10, GTX 1060

**Issue description:**
using surface tools with tool mode keeps spamming the output window with:
```
drivers\gles3\rasterizer_storage_gles3.cpp:3265 - Condition ' surface->index_array_len == 0 ' is true. returned: PoolVector<uint8_t>()
```
**Minimal reproduction project:**

[SurfaceToolTest.zip](https://github.com/godotengine/godot/files/2019656/SurfaceToolTest.zip)

**Comment by clayjohn** [comment]
It seems the issue here is somewhere in the mesh code. For some reason the mesh drawing code is expecting there to be an index array. For now, an easy way to avoid getting the errors is to get the `SurfaceTool` to generate indexes for you by calling `surfacetool.index()` before you commit it.

**Comment by anasofgo** [comment]
Thanks for taking the time to review this issue, and yes I confirm that calling ```surfacetool.index()``` solves the issue.

**Comment by bojidar-bg** [comment]
@Zireael07 Should we merge those two issues (since it seems to be about the same problem)?

**Comment by Zireael07** [comment]
Feel free to.

**Comment by bojidar-bg** [comment]
Okay, merging into #18201, as it is the same problem (meshes without indexed arrays spam output).

**Comment by ConnorDY** [comment]
This issue is still present. Will this be addressed anytime soon?

**Comment by bojidar-bg** [comment]
@ConnorDY This is the same issue as #18201, please track the progress there.
