### ISSUE TITLE
For how to use Navigation2D in GDScript

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#1904]
For how to use Navigation2D in GDScript

**Comment by guilhermefelipecgs** [comment]
Have you seen this demo?
https://github.com/okamstudio/godot/tree/master/demos/2d/navpoly

**Comment by cjmxp** [comment]
Yes I have carefully read。
demo navpoly Is not exactly built with GDScript。

My own example
func _ready():
   NData = NavigationPolygon.new()
   NPath = Navigation2D.new()
   NData.add_polygon(polygon)
   NPath.navpoly_create(NData,Matrix32())
   var value = NPath.get_simple_path(start,end,true)
   value.size()==2

**Comment by guilhermefelipecgs** [comment]
Well, I don't know why you need create 100% with GDScript but I made this example for you:
https://gist.github.com/guilhermefelipecgs/6d504dedfc6a5476e3eb
Put this code in a Node2D, 
I hope this help you.
