### ISSUE TITLE
LineEdit ctrl left/right broken

### ISSUE THREAD

**Issue by ibrahn** [godotengine/godot#19042]
**Godot version:**
228b09bafbad467389dd851699df1a327fbdea21

**OS/device including version:**
Debian (Buster)

**Issue description:**
In LineEdit controls Ctrl+left/right now jumps to the ends of the line rather than by word.
Shift+Ctrl+left/right no longer selects.

**Steps to reproduce:**
In any LineEdit control (e.g. a node name in the scene tree panel), enter some text with a space in.
Try ctrl+left, ctrl+right.

**Comment by ibrahn** [comment]
reverting a126876cc834aeb9c81b3f4abecf5836f0c02782 fixes it.
Guessing this should have been ifdeffed for mac style keys.
cc @KidRigger

**Comment by KidRigger** [comment]
@ibrahn My apologies, I must've forgotten. Fixing.
