### ISSUE TITLE
Can not create C # source project for Godot.

### ISSUE THREAD

**Issue by minhdung321** [godotengine/godot#19049]
Hello. Can you help me? My Godot Mono can not create a **C #** project for my game project. Each time I create, my 

> Godot will automatically stop working and exit

. I installed Mono who installed **winx86** and **winx64** or **gtk #**. But socks are not useful. And when it does, it still escapes. Excuse me for not being familiar with **VisualScript** and **GDScript** so I have to use **C #**, which is very annoying for me. Thank you for reading, please help me fix it. Thanks again.

**Comment by Zireael07** [comment]
Which version of Godot, which version of Mono?

**Comment by minhdung321** [comment]
Yesh, Godot_v3.0.2.

**Comment by minhdung321** [comment]
![image](https://user-images.githubusercontent.com/39442146/40274304-287f9266-5b88-11e8-9f2b-1ea3d14703ec.png)

**Comment by minhdung321** [comment]
No. I using mono 5.12.0.226

**Comment by KellyThomas** [comment]
The pre-built 3.0.2 binaries require Mono 5.4.x

**Comment by minhdung321** [comment]
Thank you. I will try again :)

**Comment by minhdung321** [comment]
Can I use Mono 5.4.1.7?

**Comment by minhdung321** [comment]
Tks

**Comment by minhdung321** [comment]
:( I created a C # code file now, how do I open it? I clicked open set without seeing anything.

**Comment by minhdung321** [comment]
Tks. I opened it with Visual Studio code. Tks.

**Comment by aaronfranke** [comment]
If you have solved your problem, please close this issue.
