### ISSUE TITLE
Can Tile Sprite in the Editor but not from Script

### ISSUE THREAD

**Issue by mwerezak** [godotengine/godot#19051]
**Godot version:**

v3.0.2.stable.official

**OS/device including version:**

Ubuntu 16.04

**Issue description:**

I am creating a tiling sprite by setting the Repeat flag on the sprite's texture and then setting the region rect to be larger than the texture size. In the editor everything works fine, however when I try to set the region rect from code, it does not work if the Rect2 is larger than the texture size. 

My texture size is 1440x960 and I am trying to set the rect size to 3072x2664. If I print the region_rect after setting it the console outputs Rect(0, 0, 3072, 2664), but visually the sprite is no larger than 1440x960 (exactly 1 tile)

**Steps to reproduce:**
1. Create a texture of a certain size, load it with the Repeat flag on.
2. Create a sprite. Set it's region rect to be larger than the texture size and observe tiling. Launch the game and ~~observe tiling~~ no tiling. EDIT: It does not appear to tile in the actual game, even though it does in the editor.
3. Attempt to set the region rect from a script. Note the absence of tiling.

If this is not the correct way to create a tiling sprite please let me know.

**Comment by bojidar-bg** [comment]
@mwerezak Instead of editing the Texture resource in the inspector, edit it in the import panel. Otherwise, any changes to flags would be lost upon reimport.

**Comment by mwerezak** [comment]
@bojidar-bg and now I just discovered the import panel. Thank you.

**Comment by mwerezak** [comment]
It works only when you use the import panel, but it works.
