### ISSUE TITLE
Script resource thumbnail doesn't highlight comments using the configured comment color

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#19057]
**Godot version:**
5b11d16

**Minimal reproduction project:**
The big chunk of text in the beginning is a license boilerplate, it's a comment, but in the thumbnail treats it as code:
![screenshot2](https://user-images.githubusercontent.com/30739239/40274592-da5e1dea-5bc9-11e8-8b4e-958351db8050.png)

**Comment by akien-mga** [comment]
To be more specific (I was writing a complete answer about how it's not worth it to try to *remove* comments from thumbnails which are too small to be readable anyway), this issue would be about changing the highlight color of comments in the thumbnail.

**Comment by YeldhamDev** [comment]
@akien-mga Sorry if I wasn't clear enough.

**Comment by akien-mga** [comment]
I think I just read too fast :P

**Comment by Calinou** [comment]
This seems to have been fixed in Godot 3.2.1, closing.

![image](https://user-images.githubusercontent.com/180032/85035135-26529580-b183-11ea-9317-acceb1f6092c.png)

**Comment by Calinou** [comment]
Nevermind, this issue is about file thumbnails, not the script editor minimap. I can still reproduce that one in Godot 3.2.1:

![image](https://user-images.githubusercontent.com/180032/85035365-5bf77e80-b183-11ea-914f-e38065b203c8.png)

**Comment by akien-mga** [comment]
This should be easy to solve with a quick dive in this basic parser:

https://github.com/godotengine/godot/blob/f879a08a621b153c216453b97e2bf48c8ac296d6/editor/plugins/editor_preview_plugins.cpp#L506-L580

Note that the aim is not to replicate the full blown syntactic coloring of GDScript, but adding support for `text_editor/highlighting/comment_color` on lines that start with `#` should be good enough. (Note that this should also apply to inline comments, e.g. `some_code()  # This part is a comment`.)
