### ISSUE TITLE
New inspector doesn't trigger the TextureRegion editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#19053]
**Godot version:**
eded061

**Issue description:**
When clicking in a Atlas resource, the TextureRegion editor doesn't open anymore.

**Comment by guilhermefelipecgs** [comment]
@YeldhamDev I didn't have problem to open texture region for atlas texture. I didn't understand how you are testing.

To edit tileset, clicking on "Edit" works yet.

![captura de tela de 2018-05-20 21-06-44](https://user-images.githubusercontent.com/1387165/40285383-c2cc2afc-5c71-11e8-9154-3f992b96a280.png)

**Comment by YeldhamDev** [comment]
@guilhermefelipecgs It used to open automatically when clicking in the resource itself.

**Comment by guilhermefelipecgs** [comment]
@YeldhamDev  You're right, I was clicking in the resource through FileSystemDock, not from SceneTree. :)
