### ISSUE TITLE
On change parent, the state from some nodes is lost

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#1905]
**If I change the parent from a node with remove/add. I expect to continue with the same state.**
The worst and most notorious offender for this behaviour is animation player, for example: if the animation is playing x on second 10, on change parent, gets stuck at second 10 without autoplay, or on case of autoplay an animation, play this animation again.

It's seems that the ready event gets called on every add_child call, I don't know if this is supposed to happen all the time, and not only the first time where the node gets added to a tree.

I know i could detect the change parent on notify, save the animation state, and restore it, but that is like a patch and i don't know how many node types from godot follow this behavior and I need to patch it.

So we need someway to make the base nodes don't loss the state on reparent without adding code to the reparented node, included his subchildrens.

At first we need to clarify if ready should be called on all the add_child, and not only the first one.

For possible solutions I think:
- **Call the _ready() event only the first time and create another event for the old behavior like _on_enter_tree():** best option for me, this fix all the nodes without intervention, from the name of the event I expect this behavior, but could break some projects expecting the old behaviour, but I couldn't think a case where you need the old behaviour
- **Add a new optional parameter or method for add children which skips the ready event:** this option is the most clean and project friendly one, make a optional parameter like add_child(Node node, bool skip_ready == false) or a new method called like add_child_and_skip_ready(Node node)
- **Fix the behaviour for each node with problems from godot:** most time consuming option and could break some projects

Here is a project with the bug:
https://mega.co.nz/#!zcgxTBAa!_uC6-kA_Znuo21SPxHEi2JZ_rX3erNCNkrx0tb63hiE

More documentation of the issue and the project with the bug explained here:
http://www.godotengine.org/forum/viewtopic.php?f=11&t=1117#p9336

**Comment by guilhermefelipecgs** [comment]
The problem happens because when you call remove_child, all animations will stop,
https://github.com/okamstudio/godot/blob/master/scene/animation/animation_player.cpp#L226
Maybe we need an option to reparent without calling (add|remove)_child.

**Comment by guilhermefelipecgs** [comment]
Like Node:move_child but for reparent.

**Comment by guilhermefelipecgs** [comment]
About the _ready(), I think we don't need alter, because the new function will not call NOTIFICATION_READY, maybe we can create a new notification, eg: NOTIFICATION_REPARENT.

**Comment by HeartoLazor** [comment]
The code you linked, still executes the autoplay routine on ready, about the stop, you're right
> case NOTIFICATION_READY: {
			if (!get_tree()->is_editor_hint() && animation_set.has(autoplay)) {
				play(autoplay);
			}
		} break;

On reparent should still call enter_tree, but not ready.

**Comment by guilhermefelipecgs** [comment]
I added a function called Node::reparent and I will make a PR, let's see if @reduz will approve.

Do you know how to compile from source?
If yes, try compile this (https://github.com/guilhermefelipecgs/godot/tree/add_reparent_method) and test your example.

change this:
```GDScript
if(traveler.get_parent() == containerA):
	traveler.get_parent().remove_child(traveler)
	containerB.add_child(traveler)
else:
	traveler.get_parent().remove_child(traveler)
	containerA.add_child(traveler)
```
for this:
```GDScript
if(traveler.get_parent() == containerA):
	traveler.reparent(containerB, 1)
else:
	traveler.reparent(containerA, 1)
```
Example working:

![out](https://cloud.githubusercontent.com/assets/1387165/7691672/c2764196-fd92-11e4-97cc-412843c72e8b.gif)

**Comment by HeartoLazor** [comment]
Yeah, let me see and test your fix, I will test it also with some 2d nodes based on states over time, those should be umm timer, animation player, another one?

Also on your method reparent this line doesn't check if his parent is != null

> data.parent->data.children.remove( data.pos );

Also would it not be better to receive the object to move, test if have a parent, look for his position and reparent, rather than the pos?

**Comment by HeartoLazor** [comment]
traveler.reparent(containerB, 1) works perfect

traveler.reparent(containerB, 0) crash on close (press the x from the window) after 2 reparents on my demo.
I print the tree for all the reparents and it's seems that the reparent sometimes replaces nodes on destructive way if I move to an index from another node, the prints explained

Tree status at start without a move, look at the bg node:

> containerA
containerA/bg
containerA/traveler
containerA/traveler/labelnode
containerA/traveler/labelnode/animatedLabel
containerA/traveler/labelnode/animatedLabel/@Timer5
containerA/traveler/labelnode/animatedLabel/@TooltipPanel6
containerA/traveler/labelnode/animatedLabel/@TooltipPanel6/@TooltipLabel7
containerA/traveler/AnimationPlayer
containerB
containerB/bg

First move to position 0 from A to B:

> containerA
containerA/bg
containerB
containerB/traveler
containerB/traveler/labelnode
containerB/traveler/labelnode/animatedLabel
containerB/traveler/labelnode/animatedLabel/@Timer5
containerB/traveler/labelnode/animatedLabel/@TooltipPanel6
containerB/traveler/labelnode/animatedLabel/@TooltipPanel6/@TooltipLabel7
containerB/traveler/AnimationPlayer
containerB/bg

Second move from B to A, notice how bg is replaced with another traveler and the tree gets corrupted, this results on a crash on exit or queue_free() from the corrupted node:

> containerA
containerA/traveler
containerA/traveler/labelnode
containerA/traveler/labelnode/animatedLabel
containerA/traveler/labelnode/animatedLabel/@Timer5
containerA/traveler/labelnode/animatedLabel/@TooltipPanel6
containerA/traveler/labelnode/animatedLabel/@TooltipPanel6/@TooltipLabel7
containerA/traveler/AnimationPlayer
containerA/traveler
containerA/traveler/labelnode
containerA/traveler/labelnode/animatedLabel
containerA/traveler/labelnode/animatedLabel/@Timer5
containerA/traveler/labelnode/animatedLabel/@TooltipPanel6
containerA/traveler/labelnode/animatedLabel/@TooltipPanel6/@TooltipLabel7
containerA/traveler/AnimationPlayer
containerB
containerB/bg

**Comment by HeartoLazor** [comment]
Ok I managed to fix all the errors, changed the behaviour to use the node destination parent only and make it work based on remove/add code but without the events and is much more tested, Use the same method name/event.
Pulling from my fork

**Comment by guilhermefelipecgs** [comment]
I forgot to update the index after reparent. Thanks for letting me know, now it's right.
About receive to_pos argument, I think it's better to wait @reduz decide.

**Comment by HeartoLazor** [comment]
I found many bugs because the implementation don't take on account childrens and deep tree (look at _propagate_enter_tree()/_propagate_exit_tree();, I'm fixing a nasty one and should be ready

**Comment by guilhermefelipecgs** [comment]
I am stuck in same error.

**Comment by guilhermefelipecgs** [comment]
I made more commits in my branch, can you test if your project?

**Comment by draxdeveloper** [comment]
reparent was merged? need something like this right now.

**Comment by guilhermefelipecgs** [comment]
no.
remove_child and add_child does not fit for you?
depending what is your problem you can solve via GDScript.
if you need help try the forum.

2015-06-24 17:15 GMT-03:00 David Paiva <notifications@github.com>:

**Comment by HeartoLazor** [comment]
drax this continues here
https://github.com/okamstudio/godot/pull/1949
and the answer is no.
Now were busy until next week on some freelance work, after that I will check the gdobjects for bugs and finish what is left from reparent (maybe 1 week more). We need the reparent without loss of state for our game too, you could look the other pull (1949) for more info of the state of this and you could help if you understand the source too.

**Comment by reduz** [comment]
reparent is not necessary, if you find nodes that lose state on reparent
they must be fixed, so please report them.

**Comment by HeartoLazor** [comment]
Ok so you want to apply the changes directly on add/remove, that could be very destructive for old projects who expect the loss state behaviour, but if you want, we' re gonna apply/report changes directly on add/remove

**Comment by reduz** [comment]
no one complained when the lost state was fixed in AnimationPlayer, and so
far I haven't heard of any other node that loses state on add/remove,
if you do please report it

**Comment by HeartoLazor** [comment]
I will use the demo from my pull on the next week to find somewhat fastest the errors, and posible fixes

**Comment by akien-mga** [comment]
What's the status on this issue?

**Comment by HeartoLazor** [comment]
Fixed and Merged for Nodes which I'm interested (animation/timer), you could see more here:
https://github.com/godotengine/godot/pull/1949#issuecomment-137957452
and responses from reduz here
https://github.com/godotengine/godot/pull/1949#issuecomment-178916766
A summary on the actual state, but those could be another issue:
**2dLight** problems are **fixed** too on latests versions
**Joints 2d/3d** are **broken** after add/remove but I'm not interesed on fixing it because I don't use it on my game.
**Music and Sound** I **propose** a fix which consist on don't stop playing the music or sounds when they are removed / added, the user manually should stop the sounds if they wan't the old behavior, but @reduz discarded it:

> no.. because by convention, no node can work or do anything while removed
> from the scene. Any node removed from the scene is completely disabled.

**Sound** is **broken** on add/remove and We couldn't found a good fix, On my game I use a [**special branch**](https://github.com/HeartoLazor/godot/commit/2b0d350ec46c33d645800701afd2718ec323dbf7) with my fix applied, which consist on don't stop playing on add/remove and this is needed for my game. 
He has tried a solution for **Music**, but that one sometimes still generates noises on add/remove. Now nobody move the music from his initial node, so I'm fine with this, **but is still a bug**. 

Also the **new reworked sprites** from this commit https://github.com/godotengine/godot/commit/bed3efb17ede58a2bfc177b47cb3a49091aea30a
Need a check on add remove, the expected result is on add/remove, the animation should continue playing.

One thing a **fix** I think for **sound** could be on remove, wait 1 frame before stop the sound, if at the next frame is on another node, don't stop it, but it's a hacky one.
What do you think of this solution?

Feel free to Close this if you wan't, most of the issues described here or possible solutions for them should be addressed on a new issue.

**Comment by bojidar-bg** [comment]
I think this was closed by f3f4a11cfb9767e1d691aec431dd2f1a87a31977, can you just retest on 3.0/master?

**Comment by HeartoLazor** [comment]
I will retest in 1 or 2 weeks, after I finish a demo from my game.

**Comment by akien-mga** [comment]
Assumed fixed in the master branch as mentioned by @bojidar-bg.
