### ISSUE TITLE
CanvasLayers are sporadically not displayed at all

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#19054]
**Godot version:**
Tested my project with 3.0.2, 3.0.3 RC2, 3.1

**OS/device including version:**
Windows 10

**Issue description:**
This is a sneaky bug... every now and then, when I run my project, CanvasLayers are simply not displayed at all.

**Steps to reproduce:**
Run a project with CanvasLayers many times.

**Comment by TX256** [comment]
Has no one else ran into this?

**Comment by Zireael07** [comment]
What is your GFX card? drivers? You omitted that info from the template.

**Comment by vnen** [comment]
Any message in the console?

**Comment by TX256** [comment]
Intel HD Graphics 620. Second newest drivers. For some reason, the Intel driver update utility says "incompatible" for the latest drivers.

No messages in console.

If I had to guesstimate, this occurs around 15% of the times I run my project, and it also appears to occur often - but not always, 2-3 times in a row.

**Comment by bojidar-bg** [comment]
@TX256 Since you mention 3.1 in the description, can you test it with gles2 as well?

**Comment by TX256** [comment]
Hi, I tested the project with GLES 2, and it did not take many runs to reproduce the bug.

In addition, with GLES 2, the console is totally flooded with an error message:

`GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error`

**Comment by TX256** [comment]
Btw, I also managed to update my drivers via Windows Update to the latest one.

**Comment by reduz** [comment]
I can't reproduce this, please submit a test project and reopen.
