### ISSUE TITLE
The type or namespace name 'Godot' could not be found (are you missing a using directive or an assembly reference?) 

### ISSUE THREAD

**Issue by minhdung321** [godotengine/godot#19060]
Welcome. Sorry because you like you again. After when the manual instructions could not be create C # project for the game, it will be specified a new error.
![image](https://user-images.githubusercontent.com/39442146/40276494-79ea1d96-5bc0-11e8-98eb-d86be18ee028.png)
And I have checked on the VS will be found in the references directory, the 1 Godot.dll name is expired and both GodotSharp.dll and GodotSharpEditor.dll has an warning.
![image](https://user-images.githubusercontent.com/39442146/40276508-da8061e2-5bc0-11e8-82b8-1071bf42f22e.png)
What to do now. Or just find Godot.dll copy to finish the problem. I'm tired of the code for the game. Please help me.

**Comment by KellyThomas** [comment]
The godot assemblies are placed in your projects `.mono/assemblies` directory *after* building your project.

This can be triggered by either:
1. running your project / scene (top left corner of the godot window) or
2. clicking the build button mono panel (center-bottom in the same stack as output, debugger etc).

**Comment by minhdung321** [comment]
![image](https://user-images.githubusercontent.com/39442146/40277793-d89d26ee-5bd9-11e8-9789-a32ae51d1f49.png)
It's like this :(

**Comment by minhdung321** [comment]
![screenshot_20180520173848](https://user-images.githubusercontent.com/39442146/40278090-85b26d26-5bdf-11e8-9897-a25a1e10dce0.png)

**Comment by KellyThomas** [comment]
This post has some pointers for this error: https://github.com/godotengine/godot/issues/18152

**Comment by minhdung321** [comment]
Oh, so I have to download VS 2017?

**Comment by KellyThomas** [comment]
Yes, 3.0.2 on windows requires a visual studio install.

**Comment by minhdung321** [comment]
Then I installed VS. And next I have to do?

**Comment by minhdung321** [comment]
Tks. It's working. When I install VS 2017, Net Core Runtime,..... and Mono 5.4.1.7. Tks

**Comment by Szesan** [comment]
VS started doing this to me today, out of nowhere. Rebuilding the project didn't help, what helped was deleting the .vs directory from my mono project. It completely solved the issue.
