### ISSUE TITLE
Export setter executes before object is ready

### ISSUE THREAD

**Issue by Redwan13** [godotengine/godot#19065]
**Godot version:** 3.0.2

Scene:

```
MainObject
-> Effects
-> -> Effect1
-> -> Effect2
....
```
MainObject exports public interface and propagates exported values to inner nodes via setter. 
```
export (int) var Radius = 40 setget set_radius

func set_radius(value):
    if Radius == value:
        return
    Radius = value

    get_node("Effects/Effect1").Radius = value 
    get_node("Effects/Effect2").Radius = value
```

When values are set from editor (or when scene deserialises on application) load setter is executed before child nodes are initialised which leads to errors and possible object state invalidation.

Related discussion https://github.com/godotengine/godot/issues/6916

**Comment by vnen** [comment]
It's actually the same as discussed in #6916. Closing this as duplicate.

**Comment by vnen** [comment]
Just to reiterate (as I said in the linked issue), there's no guarantee that a setter will be called only after the node is in the tree, much less after it's ready. It can be called at any time, even if you don't put the node in the tree at all.
