### ISSUE TITLE
SpatialMaterial preview in file manager not updated when material changes

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#19062]
**Godot version:**
3.0.2

**OS/device including version:**

KDE Neon
GTX 1060

**Issue description:**

When you have a SpatialMaterial resource in your project, and edit it and then save it, the preview icon is not updated until the project is restarted.

**Steps to reproduce:**
1. Create a new MeshInstance in your scene with a sphere mesh and a new SpatialMaterial and then save the material as a resource.
2. Change the albedo color from white to red in the material, and then save it.
3. Notice the thumbnail preview in the file manager still shows a white material, even though when running the game the sphere is red.
![img1](https://user-images.githubusercontent.com/31383123/40277861-bfc7eb02-5c26-11e8-8e14-1c7319705d06.png)
4. Close and re-open the project.
5. Notice the preview is now red, like it should be.
![img2](https://user-images.githubusercontent.com/31383123/40277863-c9d85d0c-5c26-11e8-9c31-6fd5a9b6a183.png)
6. Change the color to cyan and save it again - notice how the preview still shows red.

So every time you change the material, you need to reload the project to see the change in the preview, which is kind of annoying.

**Minimal reproduction project:**

Not relevant, since opening the project updates the material preview.

**Comment by KoBeWi** [comment]
Fixed in 3.1.
