### ISSUE TITLE
Android arm64-v8a build's apk contains no lib folder. Crashes on launching.

### ISSUE THREAD

**Issue by jagannath-rath** [godotengine/godot#19061]
Godot version:
Godot v3.0.2.stable.oficial

Issue description:
Any Godot project that I build for arm64-v8a is crashing upon launching. But the same projects runs properly for arm-v7a builds. I checked both the apks and found that for arm64-v8a build there is no lib folder in the apk although it is getting build successfully. Whereas for arm-v7a build contains the lib folder in the apk.

**Comment by akien-mga** [comment]
The arm64-v8a library hasn't been shipped in any stable release so far.
It's being added in the upcoming 2.1.5 and 3.0.3.
