### ISSUE TITLE
Mass/Weight doesn't update

### ISSUE THREAD

**Issue by Skwint** [godotengine/godot#19072]
Master revision 9a5950ace52c4ebb575d452d6451259d6f2323e3
Windows 7, 64 bit

3D Rigid Body has both a mass and a weight, and these update each other, but the new values aren't visible until you select a different object and then come back.

**Comment by Web-eWorks** [comment]
Probably related to the new inspector code, as materials are/were having issues with the checkboxes not enabling their respective inputs.
