### ISSUE TITLE
How to export properties of a child node

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#19073]
I have a scene that I use as a child scene in my main scene.

In this scene one of its child nodes is a MeshInstance, this mesh instance has a mesh (duh) and a material that is used for this mesh. So far straight forward.

Now this material has a texture, I want to be able to set that texture by setting a property in my main scene. Right now I've solved this by creating the following script on the root node of my scene:

```
export (Texture) var my_texture = null setget set_my_texture, get_my_texture
var my_material = null

func set_my_texture(new_texture):
  my_texture = new_texture
  if my_material and my_texture:
    my_material.set_shader_param("a_texture", my_texture)

func get_my_texture():
  return my_texture

func _ready():
  # get the material I'm using on my mesh
  my_material = $MyMeshInstance.get_surface_material(0)

  # re-execute setting now that we have access to our material
  set_my_texture(my_texture)
```

Now this works brilliantly. I can set the texture I want to use in my main scene. 

As far as I can tell I had to do access to the material the way I did here because the material isn't available until the scene has been fully loaded and instantiated and the set_my_texture function was called before that was all done and dusted and that is part of my problem.

I don't get to see the result of assigning my texture until I run my scene. I'd like to be able to make this work in the editor. And no, I don't want to use editable children and set the texture directly on the MeshInstance. For my use case that becomes extremely messy and unclear, I'd live with not being able to see this work until I run my scene :)

Is my approach wrong? Is this a limitation of what I'm doing? Should I make this a tool script to make this work (seems yucky)? Any advise would be welcomed :)

**Comment by Zylann** [comment]
To me, exposing properties on the root node of the scene is a natural way to go, in terms of encapsulation, so it maps the internal details of your scene to the outside world to use. I'm not sure to fully grasp the other issues you describe though.

**Comment by zaniar** [comment]
@Zylann I think he meant that he need the change take effect in edit mode, not in play mode. While his current code only take effect in play mode.

**Comment by dala00** [comment]
I want this too.

**Comment by dala00** [comment]
I tried this.
https://docs.godotengine.org/ja/stable/tutorials/misc/running_code_in_the_editor.html

Using `tool` and `setget` is perfect behavior.

**Comment by KoBeWi** [comment]
This is a [proposal](https://github.com/godotengine/godot-proposals) material.
