### ISSUE TITLE
Localization fallback

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#19076]
I'm on master branch and I have this problem where godot is picking a random translation. Seeing as I have an en.po file and de.po file, sometimes my game is in English, sometimes it will load in German.

in my project.godot file I have:

[locale]
translations=PoolStringArray( "res://Locale/en.po", "res://Locale/de.po" )

so OS_Unix::get_locale() is returning a value of en_AU, which is correct, BUT I only have the en.po file.

It would be really nice to have a fallback such that if there it no translation support for say "en_AU", it will then fallback to look for a "en"

I'll happily implement myself if this is a suitable suggestion.

**Comment by volzhs** [comment]
AFAIK, the first one(en) should be used as fallback, if there's no match.
is it a problem only with master? not 3.x or 2.x?

**Comment by supagu** [comment]
that was my first thought, that the first one acts as the default, but somehow it is seemingly random. It's been an issue for me for along time, so is likely in 3.x. No idea about 2.x.
I'll poke around with the code further now I know the first one is the default.

**Comment by akien-mga** [comment]
> It would be really nice to have a fallback such that if there it no translation support for say "en_AU", it will then fallback to look for a "en"

I thought it was already the case, but if it's not, it should be implemented indeed. First check for a perfect match, then strip the country identifier and try the language identifier.

I think we do it already at least for the editor localization itself, so the logic should likely just be copied to the translation server.

**Comment by akien-mga** [comment]
Fixed by #19213.
