### ISSUE TITLE
Can't get rid of Bias warnings for Hinge Joints

### ISSUE THREAD

**Issue by Skwint** [godotengine/godot#19071]
Master 9a5950ace52c4ebb575d452d6451259d6f2323e3
Windows 7, 64 bit

3D Hinge Joint allows Bias to be specified. It helpfully reports (warning in console) that Bias doesn't work for hinge joints if the value is not 0, but it does not allow the value to be set to 0.

This is trivial to reproduce you don't need my help.

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by akien-mga** [comment]
Fixed by #21433.
