### ISSUE TITLE
Engine.set_time_scale and RigidBody

### ISSUE THREAD

**Issue by marcelokohl** [godotengine/godot#19080]
**Godot version:**
3.0.2.stable.official

**OS/device including version:**
Windows 10 pro

**Issue description:**
Changing the Engine.time_scale variable interferes with the behavior of rigidbodies, when timescale is different from 1, for example .3, rigidbodies lose strength when thrown.
There is a discussion about this, with videos, here: https://godotengine.org/qa/28698/engine-set_time_scale-and-rigidbody

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by AndreaCatania** [comment]
Can I close this issue?
