### ISSUE TITLE
HTML5 export templates missing in Godot_v3.0.3-rc2

### ISSUE THREAD

**Issue by 37TS** [godotengine/godot#19088]
**Godot version:**
Godot_v3.0.3-rc2

**OS/device including version:**
Windows/Linux/OS X

**Issue description:**
Template files missing

**Steps to reproduce:**

- Export project
- Select html5
- Install Godot_v3.0.3-rc2_export_templates.tpz
- Export unavailable

I had to use rc1 export templates instead (which are working "fine").

**Comment by hpvb** [comment]
Resolved in 3.0.3 rc3
