### ISSUE TITLE
Mass-autotile generates incorrect spacing

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#19086]
**Godot version:**

v3.0.2

**OS/device including version:**

Arch Linux/Antegos x86_64

**Issue description:**

Creating a bunch of autotile elements in a tileset causes the incorrect spacing to be shown for the 2nd one on.
Assets used here were kenney, but any tileset will do - even just any standard ol image. All other properties seem to be correct, just spacing causing irregular display and breaking interaction.

**Steps to reproduce:**
1. Create a scene, add sprites of tilesets
2. File -> Convert to -> Tileset, save
3. Create a new scene with a tilemap, attach tileset, edit
4. Set elements 0 and 1 to autotile
  - Element 0 will be correct
  - Element 1 will have incorrect "Spacing" value, causing bitmask editing to be incorrect, as seen here:

![image](https://user-images.githubusercontent.com/3120639/40319171-7dc7d350-5d27-11e8-933f-e290a5cd5941.png)

**Comment by MarianoGnu** [comment]
Please try out if this still happens with the new TileSet Editor. I think it's fixed now

**Comment by MarianoGnu** [comment]
ping @Silvea12

**Comment by Silvea12** [comment]
Sorry about that. Seems to be working as of 3.0.6.
