### ISSUE TITLE
godot freezes if new navmesh is assigned

### ISSUE THREAD

**Issue by swenner** [godotengine/godot#1909]
*Bugsquad edit:* Initially reported against 1.1rc2.

Assigning a Navigation mesh to a NavigationMeshInstance freezes Godot.

How to reproduce:
Open the Navmesh Demo. Clear the Navmesh and create a new one. Godot no longer responds.

<pre>
ERROR: create: Condition ' !fc || ((fc%3) != 0) ' is true.
   At: core/math/triangle_mesh.cpp:102.
ERROR: mesh_add_surface: Condition ' array_len==0 ' is true.
   At: drivers/gles2/rasterizer_gles2.cpp:1804.
ERROR: add_surface: Condition ' len==0 ' is true.
   At: scene/resources/mesh.cpp:268.
ERROR: mesh_surface_set_material: Index p_surface out of size (mesh->surfaces.size()).
   At: drivers/gles2/rasterizer_gles2.cpp:2621.
</pre>

**Comment by n-pigeon** [comment]
I can confirm this, still present in git-master.
