### ISSUE TITLE
CheckBox pressed signal does not use a value.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#19100]
I tried to check but searching for checkbox issues returns obscure results.

**Godot version:**

3.02

**Issue description:**

When we connect a CheckBox node Signal with an object, the function to be used with the Signal does not take or have any arguments.
We need a way to retrive the state of the CheckBox in the function called by the Signal and searching for the CheckBox inside the tree is not ideal.
This may be marked as a future request, but in reality does not make sense to have a signal for pressed without taking an argument with the pressed value of the CheckBox or any other Node that have Signal pressed.

**Steps to reproduce:**
Create a CheckBox and connect the Signal pressed to a Node with script.
the created function looks like this:
`
func _on_CheckBox_pressed():
`
we need something like this:
`
func _on_CheckBox_pressed(value):
`

**Comment by Zylann** [comment]
Do checkboxes have a signal for 'unpressed' though? (That could explain the absence of argument)

**Comment by kakoeimon** [comment]
Yes indeed you are right, toggled signal seems to work as expected.
Now I just realized that this pressed signal is in this way cause it inherits from the button.
So there is no issue... closing it.
Thanks.
