### ISSUE TITLE
Script Editor File > Run shortcut CTRL+Shift+X not working?

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot#19104]
I'm pretty sure it's not another program capturing it.

Has anyone else noticed this?

**Comment by bojidar-bg** [comment]
Which version of Godot (and OS)?

**Comment by romeojulietthotel** [comment]
If I select File->Run I get a warning pop-up that says "Script is not in tool mode, will not be able to run."

And Control-Shift X produces no warning pop-up or anything else.

Linux 3.0.2 stable here.

**Comment by hedgehog90** [comment]
@bojidar-bg custom build 3.1 760ec58 (built a few days ago) on Windows 10 64 bit

**Comment by hedgehog90** [comment]
@romeojulietthotel that's probably because you haven't put 'tool' at the top of the script, like this:

```
tool
extends EditorScript
func _run():
    print("Hello from the Godot Editor!")
```

**Comment by romeojulietthotel** [comment]
@hedgehog90, yeah, was just meant as additional data.

**Comment by erickgtorelli** [comment]
I'm having the same problem. If I change the shortcut for this on the settings it works as expected, but using the default Control + Shift + X is not working. If I Right Click + Run the script also works.

Running on Windows, version 3.0.2 stable.

**Comment by reduz** [comment]
May not be a bug, but may need additional feedback
