### ISSUE TITLE
The resource name in the inspector is typed reversibly

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#19107]
**Godot version:** 0980991
**OS/device including version:** Manjaro Linux 4.16.8-1 (x86_64)
**Issue description:** When you enter a resource name in the inspector, the name is entered backwards
**Steps to reproduce:**
* Make a new scene
* Add `Node`/`Node2D`/`Node3D`
* Add `AudioStreamPlayer`
* Import some music as resource for `AudioStreamPlayer`
* Click on resource "folder"
* Try enter some name in `name` field (i try write `my_super_awesome`)
* ???????????
* ![bildo](https://user-images.githubusercontent.com/5412322/40375955-87cfdae8-5e06-11e8-94dd-090e71ad6708.png)

**Comment by bojidar-bg** [comment]
Not sure if I should tag this as a feature instead.

**Comment by Zylann** [comment]
Not sure if `name` is meant to be editable at all

**Comment by CowThing** [comment]
@Zylann It should, that's how you give built-in scripts readable names instead of the auto-generated name.

**Comment by Zylann** [comment]
@CowThing but, to be used where and how? *wonders if I missed something for all this time*

**Comment by vnen** [comment]
Isn't this the same as #19008?

**Comment by toby3d** [comment]
@vnen yes. Sorry! >_<
