### ISSUE TITLE
Desktop environment "Focus follow mouse" support

### ISSUE THREAD

**Issue by romeojulietthotel** [godotengine/godot#19109]
**Godot version:**

3.0.2 stable (hopefully there's not a 3.0.2 unstable)
git master may also be the same

**OS/device including version:**

Linux 4.16.10

**Issue description:**

This is for multiple issues with editor usability.
1. focus -- the editor does not seem to adhere to the desktop's focus method
of "focus follows mouse" (it does seem to adhere to "do not raise on mouse over")

I have to actually click the mouse in the editor to get the blinking cursor

2. This is probably a feature request but I don't know. Godot does not remember the last line and column where I was editing a .gd program last time I ran Godot.

These problems also exist on git master IIRC.

**Steps to reproduce:**

1. Switch between clutter-free and clutter mode.

2. stop/start Godot and editor will place cursor at line \# 1

**Minimal reproduction project:**

**Comment by romeojulietthotel** [comment]
Desktop focus models on X11 are  important, the editor is broken around _focus_.

###### (Not sure why this has a discussion tag. Does that mean that it's questionable as a bug or ??? What should or needs to be discussed?)

**Comment by akien-mga** [comment]
#27979 mentions that it fixes "most" of this issue. What's left @Paulb23?

Should we close this issue and move the remaining part to a new issue?

**Comment by Paulb23** [comment]
@akien-mga  Just point 1 remains. Might be worth changing the title, rather then opening a brand new issue.

**Comment by Calinou** [comment]
This needs to be tested again with the DisplayServer changes. Please open new bug reports if you experience issues when using your window manager's "focus follows mouse" setting. Make sure to specify which DE/WM you're using in the report.
