### ISSUE TITLE
EventStreamChibi only plays right channel (left is mute)

### ISSUE THREAD

**Issue by Domarius** [godotengine/godot#19119]
**Godot version:** Godot_v2.1.4-stable_x11.64 / Godot Engine v2.1.4.stable.official
**OS/device including version:** Windows 7 64-bit / Linux Mint 18.3 (Mate)  (Yes I am dual booting)

**Issue description:**
The left speaker is completely mute during playback of MOD type files (this includes S3M, IT, XM, etc.)
This is unusable as only "half" of the song is heard.  (It's the same as when one speaker goes out in your headphones and then part of the vocals go missing, etc.)

**Steps to reproduce:**
* Add an EventPlayer to the scene, have it load and play any MOD type file, eg. S3M, IT, XM.  
* Notice that it sounds like half the song is missing.
* Play the same file in any appropriate sound player (eg. VLC) to hear the song as it should be.

Don't try and play actual *.MOD files as they don't play at all due to a bug. https://github.com/godotengine/godot/issues/12805 

**Minimal reproduction project:** 
[MOD music test.zip](https://github.com/godotengine/godot/files/2030230/MOD.music.test.zip)   
Run the project to hear the problem. You can play the included file "JUMP.xm" in VLC to hear it correctly.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
