### ISSUE TITLE
3D transform gizmo is not a fixed size if view port size changes

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#19116]
Godot 3.1 dev, Win 10.

**Issue description:**
As I understand a transform gizmo from 3ds max and Blender, it should stay the same size no matter the size and aspect of your view port. This is only a problem if the view port is divided on the horizontal axis and scaled to an aspect higher than 3:1.

![image](https://user-images.githubusercontent.com/24936603/40408170-f39922f6-5e66-11e8-8826-3f37c0e23593.png)

**Comment by toger5** [comment]
The same occurs when choosing half resolution. the gizmo is double the size than ;)
