### ISSUE TITLE
Camera2D margins don't consider zoom for calculations

### ISSUE THREAD

**Issue by Zamaroht** [godotengine/godot#1912]
If the camera zoom is set to 1 for X and Y, the margins work as expected. That is, the camera stops scrolling right when it touches the margin.
However if the zoom is greater than 1 for X or Y, the camera will scroll past the right/bottom margin respectively. If the zoom is lower than 1, the camera will stop scrolling before reaching the right/bottom margins.

**Comment by akien-mga** [comment]
Confirmed (though the parameter is called "limits" and not "margins" IINM)

**Comment by akien-mga** [comment]
@reduz Here's a simple project that reproduces the issue, and tries an incomplete workaround. It seems to show that there are actually two issues when using zoomed cameras:
- The zoom ratio is not taken into account to adapt the limits, so limits have to be recomputed manually by the user (tick "Workaround" in my example to try that). IMO it's a bug, users should set the limits in global coordinates, and the runtime stuff should be computed internally.
- Even with this workaround, you'll see when scrolling to the right or bottom that it goes way past the actually set limits when there is a zoom, and for that I have no clue as my workaround is fine AFAICT.

[camera2d_zoom.zip](https://github.com/godotengine/godot/files/122702/camera2d_zoom.zip)

**Comment by akien-mga** [comment]
I can confirm the fix, nice job :D
