### ISSUE TITLE
2D workspace auto-pans while dragging items

### ISSUE THREAD

**Issue by ffxsam** [godotengine/godot#19125]
**Godot version:** 3.0.2

**OS/device including version:** macOS 10.13.4

**Issue description:**

While dragging items around in the workspace, it auto-pans which sometimes makes it difficult to place things precisely.

**Steps to reproduce:**
(see screencap)

![screencap](https://user-images.githubusercontent.com/12532733/40432855-3d96e72c-5e70-11e8-9887-5aa114a37154.gif)

**Comment by KoBeWi** [comment]
Any steps to reproduce?
Tested with 3.1 and 3.0.6 and it doesn't seem to happen.

**Comment by ffxsam** [comment]
@KoBeWi Three people 👍'd my issue, so it seems like I wasn't alone. But I have a feeling it's probably fixed by now.. this was May of last year.

**Comment by akien-mga** [comment]
Closing as fixed in 3.1.
