### ISSUE TITLE
Nonexistent function 'set_pitch_scale' in base 'AudioStreamPlayer'

### ISSUE THREAD

**Issue by Martin-Ziegler** [godotengine/godot#19123]
**Godot version:**
3.0.2.stable.official

**OS/device including version:**
Linux Mint 18.3

**Issue description:**
if you want to apply pitchscale on an AudioStreamPlayer, the following Error Message is displayed:

> Invalid call. Nonexistent function 'set_pitch_scale' in base 'AudioStreamPlayer'

I didn't found any documentation how to use set_pitch_scale properly in this case.
I posted this issue here, because it was recommended to me:
https://godotengine.org/qa/28629/how-to-use-set_pitch_scale-correctly-in-gdscript

**Steps to reproduce:**
Add in a parentscript of AudioStreamPlayer named "Tone200" the following line:
`$Tone200.set_pitch_scale(4)`

**Minimal reproduction project:**
[PitchAudiostreamplayer.zip](https://github.com/godotengine/godot/files/2031514/PitchAudiostreamplayer.zip)

**Comment by vnen** [comment]
I think the error is quite clear: you're calling a function that does not exist. There's no `set_pitch_scale()` in the AudioStreamPlayer class. This function existed in the 2.1 version, but for 3.0 the audio engine was rewritten and many things changed.
