### ISSUE TITLE
Persistent Input key pressed Bug/Glitch

### ISSUE THREAD

**Issue by MrHoothoot** [godotengine/godot#19137]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 7 x64 RX 470

**Issue description:**
Input is Stuck

**Steps to reproduce:**
Greetings everyone, I would just like to share that I've notice some bug and there are 3 ways to reproduce this issue. For example if you are player and is moving using move_and_slide or position movement.

If Godot or your computer freezes or hangs for a bit, the input is stuck and is being read as key pressed. Another way to reproduce this is when you drag around the window of running godot game while moving(which makes it stutter), the Input also ends up stuck. Lastly, the easiest way to reproduce this issue is when you rapidly press shift+key (which enables sticky key for windows), The input key pressed ends up stuck.

Also, just wanted to follow up, there are cases that when if godot stutters/hangs, it seems to skip some frames/cycles of the code and causes inaccurate calculation which I'm not sure if its normal.

**Comment by fbsr** [comment]
**Godot version:**
3.1.10.alpha
**OS**
Windows 10 x64

The issue persists.

**Comment by avencherus** [comment]
I think I'm running into this as well, possibly with when keys are held and the game is paused and unpaused.

**Comment by TaberIV** [comment]
I've also noticed this issue if I very quickly tap then release the key

**Comment by avencherus** [comment]
@guilhermefelipecgs Curious if you might have some insights into the input handling.  Have you encountered anything like this?

**Comment by guilhermefelipecgs** [comment]
I made a PR to try to fix this issue, but I only tested on Linux, can someone test it on Windows please?
