### ISSUE TITLE
Default Input Map Actions work even if not activated

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1913]
All of the default Input Map Actions work even if not activated. The only way to make them not working is to make them active ( tick them ), and remove all of the attached keys.

**Comment by akien-mga** [comment]
Confirmed in the current master branch. The default navigation actions are indeed working even if you delete the corresponding action, as stated above the only option to disable them is to tick them on and remove the bound keys.

**Comment by reduz** [comment]
The tick is not for working or not working, it's for persisting. If you remove the tick, the option will disappear from engine.cfg

**Comment by reduz** [comment]
that said, it's kind of stupid to edit that, so removing the tick
