### ISSUE TITLE
Tilemap:  Erasing last cell via code in low processor mode doesn't update texture

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#19134]
**Godot version:**
3.0.2 stable

**OS/device including version:**
Windows 10

**Issue description:**
I'm using the following code to paint a tilemap at runtime:
```gdscript
if event is InputEventMouseMotion:
	if Input.is_mouse_button_pressed(BUTTON_LEFT):
		$Layers/Base.set_cellv(get_local_mouse_position()/16/$Layers.scale,1)
	elif Input.is_mouse_button_pressed(BUTTON_RIGHT):
		$Layers/Base.set_cellv(get_local_mouse_position()/16/$Layers.scale,-1)
```
The tilemap is on its own CanvasLayer.
When erasing cells, the canvas doesn't always update in a timely manner.  This usually happens when there are only 1 or 2 cells left in an almost-blank tilemap.  If the canvas is told to update in any way, it seems to reflect the correct state of the tilemap.  A workaround in this case is to add `update()` whenever erasing cells.  This problem only occurs when low processing mode is enabled for the project.

**Comment by Calinou** [comment]
@nobuyukinyuu Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by nobuyukinyuu** [comment]
Can't seem to replicate since posting.
