### ISSUE TITLE
Play scene inside editor

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#19141]
I recently played around with plugins.
And Think it would be possible to run the current scene inside the editor when all the scripts are set to tool mode.

If tool mode can be set by a function on the script api, it should be possible to run scenes anywhere in the editor, (in a dock, fullscreen, or (most useful) over the main center window.

There was an issue some time ago, about having such a feature.
So it might be worth to further investigate?

Any doubts this works? What did i overlook.

I'll make a plugin as a proove of concept. But i think it will be necassary to set all the involved scripts to tool mode manually.

**Comment by toger5** [comment]
@Zireal07 do you have a link?

**Comment by eon-s** [comment]
This one #13354, but has not been touched for awhile.

And this issue may be related/duplicate of #5802.

**Comment by Zireael07** [comment]
Found it: #13354

Oh, ninja'd.

**Comment by toger5** [comment]
Thank you two!
I think #13354 Is a much better place for this discussion. (I even remember reading that pr a long time ago now ;) )

So this issue is defitly unecassary
