### ISSUE TITLE
Allow custom script templates in project folder to override global shared script template

### ISSUE THREAD

**Issue by exts** [godotengine/godot#19145]
**Godot version:**
3.0.4+

**Suggestion:**
So recently I found out you could override default script templates inside the shared files eg.: `$HOME/.config/godot/script_templates` (linux) and `%AppData%/Godot/script_templates` (win) or `$HOME/Library/Application Support/Godot/script_templates` (osx)

Thing about this is each template for gdscript makes sense, but for c# when you involve namespaces per project the naming doesn't work for each project. Unless we added a `%PROJECT_NAME%` and `%FOLDER_PATH_AS_NAMESPACE%` template variables. 

Then it comes down to everyone not wanting to use the folder path as namespace for c# (lot of weird naming politics would revolve around this), so why not allow us to override the default script templates in the project folder itself if one exists? Then you can customize your template script for each project the way you want (which would work for all scripting languages) without having to constantly edit the global shared template to cater to each individual project. Then you'd have to edit it when going back to a different project. Seems tedious.

**Comment by adabru** [comment]
Furthermore if the project is versioned with git, script templates inside the project folder would be immediately available for new team members after a `git clone`.
