### ISSUE TITLE
Exported arrays not editable in the inspector

### ISSUE THREAD

**Issue by wmigor** [godotengine/godot#19158]
**Godot version:**
master

**OS/device including version:**
Linux Mint

**Issue description:**
"export(Array, PackedScene) var values" is not editable in inspector

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by ordigdug** [comment]
Godot version:
master (as of 8 June 2018)

OS/device:
MacOS High Sierra

Issue description:
Inspector BUG:
Unable to edit exported Arrays in inspector.
"export(Array) var myArray" does not show up in inspector therefore is not editable 

![screen shot 2018-06-10 at 5 11 37 am](https://user-images.githubusercontent.com/5384251/41200124-cc8d9a98-6c6c-11e8-9a48-b6bd55b450f0.png)

**Comment by ordigdug** [comment]
@akien-mga Can you please change the title of this issue?

**Comment by akien-mga** [comment]
CC @bojidar-bg, likely a regression from the new inspector.

**Comment by bojidar-bg** [comment]
Pushed a preliminary fix, type hints are still not supported, but you should be able to edit the array.

**Comment by ordigdug** [comment]
export(Array) is editable in Inspector now. Still need type hints supported.

**Comment by bojidar-bg** [comment]
Let's move the type hints part to #20004 (since the original issue mentioned here was fixed).
