### ISSUE TITLE
Building mono project under Debian Stretch doesn't work

### ISSUE THREAD

**Issue by lukaszbulzacki** [godotengine/godot#19162]
**Godot version:**
335679f48198364ab0d0c2f21c0a86fecdd726e0

**OS/device including version:**
PC, Linux (Debian Stretch), Mono 5.10.1.20

**Issue description:**
Building mono project doesn't work.
Below exception.

> Unhandled Exception:
> System.MissingMethodException: Attempted to access a missing method.
>   at (wrapper managed-to-native) GodotSharpTools.Build.BuildInstance.godot_icall_BuildInstance_get_MSBuildInfo(string&,string&)
>   at GodotSharpTools.Build.BuildInstance.GetMSBuildInfo () [0x00008] in <00bcfea228cc41c5a44c035a71a777cd>:0 
>   at GodotSharpTools.Build.BuildInstance.Build (System.String loggerAssemblyPath, System.String loggerOutputDir, System.String[] customProperties) [0x00000] in <00bcfea228cc41c5a44c035a71a777cd>:0 
> ERROR: start: The build method threw an exception.
> System.MissingMethodException: Attempted to access a missing method.
>    At: modules/mono/editor/godotsharp_builds.cpp:546.
> 
>

**Comment by akien-mga** [comment]
Are you building from a clean repo, or on top of a previous build? For the latter I think you may need to delete the `bin/GodotSharpTools.dll` file.

**Comment by lukaszbulzacki** [comment]
I have build sh script that removes binary data so it should be same as from clean build.
If I should delete some other files please say what and I will check if it helps.
Code below.
>  find ./bin -type f -name '*.dll'
>  find ./bin -type f -name '*.mono'
>  find ./bin -type f -name '*.debugsymbols'
>   
>  find . -type f -name '*.o' -delete
>  find . -type f -name '*.a' -delete
>  find . -type f -name '*.so' -delete
>  find . -type f -name '*.lo' -delete
>  find . -type f -name '*.lib' -delete

**Comment by neikeq** [comment]
This is definitely the old `GodotSharpTools.dll`. `godot_icall_BuildInstance_get_MSBuildInfo` became `godot_icall_BuildInstance_get_MSBuildPath`. Deleting `bin/GodotSharpTools.dll` should fix it...

**Comment by neikeq** [comment]
This file is automatically removing on cleanup, but the cleanup command must also include the argument which enabled the mono module. e.g.: `scons --clean p=x11 module_mono_enabled=yes`

**Comment by KellyThomas** [comment]
@neikeq That explains why `scons --clean` never seemed to do what I wanted it to!

**Comment by lukaszbulzacki** [comment]
Commands `scons --clean p=x11 module_mono_enabled=yes` and `scons --clean p=x11` solved problem so closing, because everything works.
@neikeq thanks for help.
