### ISSUE TITLE
Inconsistent results when using is_nan() or comparing with NAN

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#19160]
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
Ubuntu 18.04 LTS 64-bit

**Issue description:**
Using is_nan() seems to always return False, even with argument NAN.
On the other hand, comparing with NAN seems to always return True.

**Steps to reproduce:**

1. print the result of is_nan(NAN). Expected : True, actual : False
2. print the result of 0 == NAN. Expected : False, actual : True

**Minimal reproduction project:**
[godot_nan_issue.zip](https://github.com/godotengine/godot/files/2039195/godot_nan_issue.zip)

**Comment by Sephtenen** [comment]
> Seems like it was fixed in the meantime, though I can't find the commit (but I remember seeing another issue about this recently, which I can't find again either :/ maybe @hpvb knows).

I couldn't find any change in the repo about that, I guess I just missed the right place.

> The only remaining "bug" might be that NAN == NAN still gives False, but I guess that might be expected/a normal limitation of using NAN in the first place.

I would also expect `x == NAN` to always give `False`, as in most programming languages. My issue there was that is always gave `True`.
That said, is the behavior of comparing with NAN specified ?

**Comment by vnen** [comment]
> The only remaining "bug" might be that NAN == NAN still gives False, but I guess that might be expected/a normal limitation of using NAN in the first place.

I say this is the proper behavior. If you write `sqrt(-1) == NAN` to test if it's a number might look fine, but if this is true then `sqrt(-1) == sqrt(-2)` would also be true, which can be quite problematic and lead to a bug hard to find.

**Comment by hpvb** [comment]
We had a large discussion about this in the past where I made NaN == NaN true for GDScript. This got reverted for some good reasons. In Godot NaN == NaN is *only* true when hashing a value so a NaN can be stably used as a key (so non-math type operations). For all math-type operations we follow the standards. 

Closing this as fixed.
