### ISSUE TITLE
New inspector doesn't change theme with rest of editor.

### ISSUE THREAD

**Issue by Web-eWorks** [godotengine/godot#19190]
**Godot version:**
Godot master ba125a6

**OS/device including version:**
Solus Linux (rolling release)

**Issue description:**
When changing the editor's theme, portions of the inspector fail to update their colors.

**Steps to reproduce:**
Change the editor's theme (Editor->Settings->Theme), see the inspector's internal area not update.

**Comment by toger5** [comment]
Yea true ! Ran into the same issue.

It is not too hard. Will see if i find time for it.
Basically all the the related things in the inspector initiator need to be recalled in the EDITOR_SETTINGS_CHANGED event.

I might find time to fix it. But if someone is interested in doing it would be nice.

I think i can answer questions, just ask here.

**Comment by djrm** [comment]
@toger5 since im redoing most of the theme stuff, i think this will be solved with my changes.

**Comment by toger5** [comment]
Sure i will not touch it!
Probabaly my changes would than just lead to merge conflicts anayway ;)

**Comment by reduz** [comment]
@toger5 should be ready to be fixed now

**Comment by toger5** [comment]
No time right now, can have a look in about two weeks 😬
