### ISSUE TITLE
HingeJoint : Inspector forces bias value > 0, but HingeJoint does not support non-zero bias

### ISSUE THREAD

**Issue by xemjeff** [godotengine/godot#19204]
**Godot version:**
3.1.dev  (master branch, as of 5/25/18)

**OS/device including version:**
Windows 10

**Issue description:**
This is more of an annoyance. For the HingeJoint, the inspector sets the params/Bias value to 0.01 when you try to set it to zero. Leaving it at 0.01 results in this message in your output window:

```
The Bullet Hinge Joint doesn't support bias, So it's always 0
```
I think the solution is to allow a zero value for Bias in the inspector.

**Steps to reproduce:**
Add HingeJoint node. Try to set the bias value to zero. The inspectors forces it to 0.01.

**Comment by akien-mga** [comment]
Fixed by #19246.
