### ISSUE TITLE
3D mapping inside the editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#1920]
This is a large feature request. Basically, this is a list of functionality needed in order to create maps for 3D games directly in the editor. This would be appreciated to appeal to Quake people who like mapping using tools like [GtkRadiant](https://icculus.org/gtkradiant/) or [TrenchBroom](http://kristianduske.com/trenchbroom/).

Many of these features (but not all) are already present in Add Primitives plugin.
## Shape creation
- Plane
- Cube
- Sphere, half-sphere with optional cap
- Extruded polygon with optional caps (with 3 to N sides, high polygon number makes a cylinder)
- Pyramid with optional cap (with 3 to N sides on bottom, high polygon number makes a cone)
- Torus

 
- CSG Substract
- CSG Merge
- Hollow selection (eg. to make a cube into a room)
- Ability to manipulate those shapes (interact with vertices, edges and faces) directly in the 3D view
- Clipper tool
## Texturing
- Set material on a specific face (to change texture of one face only)
## Helpers
- Selection: “Select inside”, “Select touching”
- Staircase generator

**Comment by bojidar-bg** [comment]
+1, though I think some of the features will be an overkill

**Comment by TheHX** [comment]
I already have the enough knowledge to turn Add Primitives into a level editor. But i don't have motivation to do it. Right now i'm almost abandoning the plugin.

**Comment by TheHX** [comment]
But thinking better i can create a level editor on top of Add Primitives, but for this i will need help. Especially with the design of the GUI and the tools of the plugin.

**Comment by TeddyDD** [comment]
@TheHX 1.2 will contain a lot of gui related changes. Maybe better to wait and see how plugin/gui api will change?

**Comment by TheHX** [comment]
@TeddyDD I know this, that's why i'm waiting now. Just practicing testing some new tools and changing some things i source code.

But now i'm really tempted to create a C++ module instead of a GDScript plugin. This will allow much more freedom and better results, but this will be less fun and with more headaches. I only need a bit more of motivation to do it.

**Comment by trollworkout** [comment]
minimal 2D image editing  in the 2D panel would be fantastic! just wanna be able to touch up pixel art on the go. something basic like color picker Fg Bg and button to swich up, eye dropper(hold alt for quick pick), pencil (left click Fg color, right click Bg color), selection tool, move tool.

**Comment by HeadClot** [comment]
Opposed to reinventing the wheel on CSG. I would recommend looking at SabreCSG. https://github.com/sabresaurus/SabreCSG

It is under the MIT license and is open source. Might serve as a guide to making decent CSG tools for Godot.

**Comment by reduz** [comment]
I will close this, as it's not intended to be a built-in editor feature. 
Instead, support for SabreCSG could be added via GDNative now
