### ISSUE TITLE
Delayed crash on window height = 0

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#19207]
Godot v3.0.2
Windows 10

If window height is dragged to 0, application freezes for a few seconds before silently crashing.  Does not happen with width as the OS seems to enforce a min-non-0 value for it.

As far as I'm aware no API for setting minimum window size is exposed, making this not preventable (application freezes before emitting the "size_changed" event). Issue is encountered accidentally and often when dealing with tiny window sizes.

**Comment by akien-mga** [comment]
Fixed by #20026.

**Comment by mhilbrunner** [comment]
Note that https://github.com/godotengine/godot/issues/19628 is still open and occuring :)
