### ISSUE TITLE
Quick open won't work with new scenes

### ISSUE THREAD

**Issue by moltedopablo** [godotengine/godot#1921]
When I recently create an scene and try to open it with the quick open dialog Godot can't find the scene. Clearly, the path is wrong. The problem goes away when I restart the engine.
![captura de pantalla - 160515 - 15 06 52](https://cloud.githubusercontent.com/assets/4377823/7667433/b66dec84-fbdd-11e4-9730-13489d8675b2.png)

**Comment by ficoos** [comment]
Clone of #1808
