### ISSUE TITLE
Poor performance using Bullet on Godot_FPS_Tutorial 

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#19222]
**Godot version:**
fac0120521f1bf37dc7a8b86e67eb0754baee931

**OS/device including version:**
Linux 4.16.11 / Win10
CPU: i5-4460 @ 3.20GHz
GPU: GeForce GTX 970
GPU Driver: 396.24 (Proprietary)
RAM: 8 GB

**Issue description:**
Testing this demo [Godot_FPS_Tutorial](https://github.com/TwistedTwigleg/Godot_FPS_Tutorial), I had a very bad performance caused by physics.

**Steps to reproduce:**
- Level 1: runs with both physics engines with good performance.
- Level 2: if I remove "Other_Objects", GodotPhysics run with 60fps but Bullet doesn't.
- Level 3: only GodotPhysics run with 60fps.

**Minimal reproduction project:**
https://github.com/TwistedTwigleg/Godot_FPS_Tutorial

**Comment by Supatier** [comment]
@guilhermefelipecgs What hardware (AMD/NVIDIA/Intel HD), driver are you using (propritary/opensource), and the driver version.

**Comment by guilhermefelipecgs** [comment]
Description updated with my specs.

**Comment by kubecz3k** [comment]
@AndreaCatania This looks like something that you might want to give a check / benchmark

**Comment by AndreaCatania** [comment]
@kubecz3k Yep thanks you. I'll check it soon

**Comment by AndreaCatania** [comment]
This is really interesting. 
Level 2: When I remove the node other object as you said I'm able to run the scene with both engines without lag, I've also notices that with Godot physics when I go near the yellow lamps the game start to lag a lot when I go away from it the game runs again correctly.

Can you please confirm it?

The lamp collision shape should be a capsule shape in order to optimize the process. I'm investigating more on that

**Comment by AndreaCatania** [comment]
I've checked more closely the collision shapes of few object and this is the result:

- Computer static: 3097 points ---> For this object a box is enough
- Pilar static 828 points ---> for tis object a capsule is enough 
etc...

You should use primitive collision shape and if it's not possible you should use a really optimize collision shape. This rule is true for both engines

**Comment by guilhermefelipecgs** [comment]
> Can you please confirm it?

Same here.

Indeed, this demo is very poorly optimized and I already knew that. I just found it strange that Godot Physics had more performance than Bullet (Bullet should be faster right?), so I thought it might be a bug somehow and maybe could be improved, but if there's nothing to do then we can close it.

**Comment by AndreaCatania** [comment]
Bullet is well optimized and from what I saw it handle better the  Pilar
shape, but this doesn't mean that it can handle multiple instance of this
shape... 3000 point for each collision shape is really too much.

If you notice the same behavior with these shapes "optimized" please open
an issue and tag me

**Comment by guilhermefelipecgs** [comment]
@AndreaCatania Ok, thanks.
