### ISSUE TITLE
Build Failed - Windows x64 

### ISSUE THREAD

**Issue by MJ-meo-dmt** [godotengine/godot#19226]
**Godot version:**
Master Branch
Maybe related to this commit: https://github.com/godotengine/godot/commit/98846b39ee039358584884b439b96e799f1d2bd0

**OS/device including version:**
Windows 8.1 x64
Python Version 3.6.4 (Build fine last night)

**Issue description:**
```
[ 57%] scons: *** [core\license.gen.h] AttributeError : 'collections.OrderedDict
' object has no attribute 'itervalues'
←[94mCompiling ←[95m==> ←[93meditor\editor_asset_installer.cpp←[0m
Traceback (most recent call last):
  File "C:\Python36\scons-3.0.1\SCons\Action.py", line 1197, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "E:\Development\Github\godot\methods.py", line 664, in make_license_heade
r
    for project in projects.itervalues():
AttributeError: 'collections.OrderedDict' object has no attribute 'itervalues'
editor_asset_installer.cpp
scons: building terminated because of errors.
```
Changing `for project in projects.itervalues():` to `for project in projects.items()` gives the following error.
`Traceback (most recent call last):
  File "C:\Python36\scons-3.0.1\SCons\Action.py", line 1197, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "E:\Development\Github\godot\methods.py", line 666, in make_license_header
    part["file_index"] = len(data_list)
TypeError: 'str' object does not support item assignment`

**Steps to reproduce:**
Pull master and build with mono support

**Comment by MJ-meo-dmt** [comment]
Fixed it locally with the following changes at 3 places. Inside methods.py
` Removed dict.iteritems(), dict.iterkeys(), and dict.itervalues().
 Instead: use dict.items(), dict.keys(), and dict.values() respectively.`
This is mainly for Python 3

**Comment by ibrahn** [comment]
Sorry about that one, my bad.
