### ISSUE TITLE
Exposing CSG functionality to scripts

### ISSUE THREAD

**Issue by AlexFlasch** [godotengine/godot#19232]
I've been trying to construct some low poly terrain, and was implementing my own CSG functionality when I saw that this was recently added to the engine for level prototyping. Exposing CSG functionality to scripts could be beneficial to procedurally generated terrain / objects.

It would be nice to:

* Transform a Mesh or MeshInstance into a CSG volume
* Union / Intersect / Add / Subtract volumes together procedurally
* Potentially (unsure if possible with the current implementation) construct a solid mesh out of the modified CSG volumes so that CSG volumes are "finalized" and aren't working as multiple volumes anymore

After discussing this with @reduz on IRC he mentioned adding barebones CSG functionality to scripts that would lack nodes, but at least allow scripts to use CSG volumes to construct meshes.

@reduz also requested that this issue be assigned to him.

**Comment by Zireael07** [comment]
I would also like to request being able to access CSG volumes after creation, possibly as a mesh (or at least using API similar to MeshInstance)

**Comment by TheSHEEEP** [comment]
Add my voice to this. It would be very valuable for procedural generation of more than just terrain.

**Comment by BastiaanOlij** [comment]
CSGMesh already allows you to load a mesh into a CSGNode for further boolean functions
Procedurally changing what you're combining would just be a matter of programatically adding more nodes, I'm not entire sure what is missing here. Procedurally generating terrain is a different story, is that what you're referring to?
The end product is only calculated once and that is what is rendered. The only advantage of pulling the end result out of the combiner node would be to allow you to remove all the CSG nodes and free up memory I guess. It would be a nice feature and I don't think all to difficult as its just pulling out the surface data.

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/23837#issuecomment-459925022 Posted about my thoughts on how exporting any mesh could work in Godot.

**Comment by TheSHEEEP** [comment]
> CSGMesh already allows you to load a mesh into a CSGNode for further boolean functions
> Procedurally changing what you're combining would just be a matter of programatically adding more nodes, I'm not entire sure what is missing here. Procedurally generating terrain is a different story, is that what you're referring to?
> The end product is only calculated once and that is what is rendered. The only advantage of pulling the end result out of the combiner node would be to allow you to remove all the CSG nodes and free up memory I guess. It would be a nice feature and I don't think all to difficult as its just pulling out the surface data.

The way I understood it, so far you can use the CSG functionality only within the editor, for prototyping. That is nice, but entirely useless for purposes of procedural generation at runtime. 
When it comes to procedural generation at runtime, at the moment AFAIK, there is only the SurfaceTool - which is extremely low-level and cumbersome to use if you want to construct entire levels with it - or using "Lego-like" nodes to put together a level (imagine pieces of walls, floors, furniture, etc.) - which would result in a gigantic amount of nodes for a larger level, which is likely a problem on its own.

Exporting it to a mesh would be useful so that you only have to procedurally generate something once, then export it, and from then on can simply load a mesh instead of contructing it every time.

**Comment by Calinou** [comment]
@TheSHEEEP I've seen projects where CSG is used at run-time (sometimes even with brushes moving constantly). @BastiaanOlij also developed a procedural mesh add-on which can be used at runtime (if I recall correctly).

**Comment by BastiaanOlij** [comment]
@TheSHEEEP I don't know where this idea came from that you can't create CSG nodes in runtime. They are just nodes, like any other nodes, and as such you can write GDScript to instance them and add them to your scene tree.

Saving the resulting mesh is a nice enhancement, hopefully someone will find some time for that. I might tackle it if I don't forget, it shouldn't be hard to do ;)

**Comment by AlexFlasch** [comment]
It's been the better part of a year since I've looked at using this in a project (though I think I'd pick that project back up if this functionality was added).

If I remember correctly when I opened this issue the problem wasn't just being able to add a CSG node to the scene tree, but being able to *do* anything with it via GDScript, C#, etc was the issue.

This may have changed since then, but I don't believe there were any exposed functions for manually telling the CSG node to intersect, add, subtract, etc with another CSG node.

**Comment by BastiaanOlij** [comment]
@AlexFlasch It works the same way as in the editor, they aren't actions on a single node, you have to add nodes for each object you want to intersect/add/subtract and set their modes accordingly.
If you can do it in the editor, you can do it in GDScript, just set the correct properties.

I do think that for the use case you described my procmesh module might be a better fit

**Comment by LeonardMeagher2** [comment]
@BastiaanOlij currently a hacky way to save the mesh is like this
```gdscript
extends CSGShape
func _ready():
	_update_shape()
	var mesh = get_meshes()[1]
	ResourceSaver.save("res://test.mesh",mesh)
```
If you put this script on the root CSG node (no CSG parent) it'll save it.
The `_update_shape` function is hidden, and does a lot more than just generate enough data for the mesh, collision faces. `get_meshes` isn't a great name, since it actually returns an array like `[Transform(), Mesh]` which that transform will always be an identity transform, but the GridMap uses a similar named function.

I think it'd be pretty easy to make a simpler function to just return a new ArrayMesh, and allow it to be called by child CSG nodes (maybe you want to save sections of the operations?)

**Comment by fire** [comment]
How would you suggest implementing the save functionality? Go from an arbitrary parent and then output gltf / fbx from that as the root? For each node save the specific mesh or spatial. For the csg use the above code right? I have access to the asset import code.

**Comment by golddotasksquestions** [comment]
The ability to merge CSG meshes together after boolean operations are applied, creating one single mesh, is a desperately needed functionality to turn the CSG feature from a fun toy to an actual tool. The same is true for the ability to export that mesh.

**Comment by BastiaanOlij** [comment]
It already becomes a single mesh, just need to add a property so you can access it and do something with it. Someone just needs to find time to do it.

**Comment by fire** [comment]
Given a single mesh converting it to gltf/glb is straight forward. /me has a concept!

**Comment by BastiaanOlij** [comment]
@fire if you look at CSGShape._update_shape():
https://github.com/godotengine/godot/blob/master/modules/csg/csg_shape.cpp#L276
That is the functionality that gets called on the root node whenever anything in the CSG tree changes, it will build the final mesh and then convert it to a plane old ArrayMesh which gets stored in the member root_mesh:
https://github.com/godotengine/godot/blob/master/modules/csg/csg_shape.h#L71

All you really need to do here is add an access method that checks if the shape is "dirty" (a boolean) and if so calls _update_shape() to make sure the mesh is up to date, then return root_mesh and voila, you have your mesh object to save.

**Comment by LeonardMeagher2** [comment]
@BastiaanOlij @fire
I'd be happy to make a project today to expose that mesh, I'd personally prefer to just make the `get_meshes` function call `_update_mesh` if it's dirty, and possibly change the name of the function, and remove the transform from the return.

**Comment by BastiaanOlij** [comment]
@LeonardMeagher2 yeah I was wondering, wasn't that what I mentioned doing :) Yeah please submit a PR!

**Comment by fire** [comment]
The design is given a mesh instance go through all the surfaces and export each as a mesh with associated materials in gltf2.

Is that compatible?

**Comment by BastiaanOlij** [comment]
I think you'd want to keep it one mesh with different materials for each surface. Breaking it up into multiple objects might make it harder to modify the mesh. Though it probably isn't much of a problem either way

**Comment by fire** [comment]
I wrapped the assimp gltf2 export and made a ui button. Clicking on it crashes the engine. 🍡 

![2019-04-18_21-03-52](https://user-images.githubusercontent.com/32321/56404781-7c454980-621d-11e9-9b29-eb8ba6342fe4.png)

Work in progress.

**Comment by fire** [comment]
I defined a cube and clicking that "Export Mesh" button now exports that cube as glb2.

**Comment by fire** [comment]
For the 0th index surface in the mesh instance, I can now export the entire surface as a glb2. The white mesh is the exported one.

![2019-04-18_23-41-36](https://user-images.githubusercontent.com/32321/56410864-92f69b00-6233-11e9-9278-06aeb9179ec7.png)
![2019-04-18_23-41-54](https://user-images.githubusercontent.com/32321/56410867-9558f500-6233-11e9-9eff-b2c9d5f00786.png)

https://github.com/fire/godot/tree/mesh_export

Todo: 

* Support more than one surface.
* Support materials
* Not supported skeletons and animations.

**Comment by TheSHEEEP** [comment]
Good stuff. The more features, the better!

**Comment by BastiaanOlij** [comment]
Looking good, what I would do is move the functionality to Scene->Convert To->GLTF. That way you could look at all the nodes in the current loaded scene and export any node that has a mesh associated with it. You could have a look at the Convert To->MeshLibrary as an example of pulling out usable nodes.

Come to think of it, the MeshLibrary export should really be updates as well to recognise a CSG node and export the mesh and collision shape.

**Comment by fire** [comment]
Here's what I have so far.

* I can export the entire scene. 
* Everything is reversed...
* No materials yet
* No skeletons and animations
* Only MeshInstances

![2019-04-19_09-29-56](https://user-images.githubusercontent.com/32321/56433458-cb26c980-6285-11e9-89a3-6d0ca54cc9c5.png)
![2019-04-19_09-32-15](https://user-images.githubusercontent.com/32321/56433555-104afb80-6286-11e9-85b2-32fbc9e1a20a.png)

**Comment by fire** [comment]
![2019-04-19_09-35-49](https://user-images.githubusercontent.com/32321/56433668-88192600-6286-11e9-8036-7c2af5b85358.png)

Here's the export dialog.

**Comment by fire** [comment]
Corrected the reversed order.

Anyone want to try it and comment?

**Comment by golddotasksquestions** [comment]
Can we get an "Export Mesh ..." dialog? 
I ask because I know "Convert To ... Mesh Library ... " or "Scene GLTF2 GLB)" will mean very little to 3D Artists and Level Designers new to Godot or open source. While "Export Mesh ..." is self-explanatory to anyone who knows what a mesh is.

**Comment by Calinou** [comment]
What about naming it **Convert To… → Scene as GLTF2**? The fact it's a GLB file is probably a technical detail that doesn't need to be explicitly stated in the button.

**Comment by golddotasksquestions** [comment]
"Convert" implies that something is happening inside of the Engine and stays inside the engine. "Export" would imply to convert whatever is in this program and make is usable outside of the application. That's how it is in any larger editing software I am aware of.
"Convert To… → Scene as XYZ" is aditionally confusing imho, because the Scene contains a lot of things for the user that won't be converted like scripts or signal links, groups and so on.
"Export Scene as GLTF2", "Export Scene as obj" would already imply what is exported.

**Comment by fire** [comment]
GridMaps and some basic materials now work.

Things should be generally oriented correctly.

Materials aren't fully working and I ran out of time to work on this. Feel free to continue the work.

**Comment by fire** [comment]
GridMaps, CSG and regular MeshInstances work.

Here are some photos from the Godot Third Person Sample.

This is the initial scene.

![2019-04-19_17-29-27](https://user-images.githubusercontent.com/32321/56449008-42318180-62c9-11e9-839b-0cc5597297e7.png)

Materials are broken.
![2019-04-19_17-32-12](https://user-images.githubusercontent.com/32321/56449009-42318180-62c9-11e9-8895-680df1ce0a8a.png)

The mesh looks fine in wireframe mode.
![2019-04-19_17-33-06](https://user-images.githubusercontent.com/32321/56449007-42318180-62c9-11e9-82ee-37490ad77188.png)

CSG:

The initial scene.
![2019-04-19_17-35-53](https://user-images.githubusercontent.com/32321/56449047-b2d89e00-62c9-11e9-8446-520c2011349b.png)

The exported scene.
![2019-04-19_17-36-33](https://user-images.githubusercontent.com/32321/56449048-b2d89e00-62c9-11e9-893c-7005e98d4a39.png)

**Comment by BastiaanOlij** [comment]
I agree that export is a better naming convention however I think we need to be careful not to add another menu or option just for one function. What I do like about the convert to menu is that it doesn't imply you are saving the entire scene as is. Just like the other options in this menu we're saving just the mesh data to another format loosing things like code, non-mesh objects, etc.

Also the convert to accurately reflects the data is converted. For instance, I'm assuming a gridmap will result in the entire resulting mesh being saved, when opening the GLTF/GLB you won't have a gridmap anymore. Same with CSG, it will be converted to a normal mesh.

@fire looking good man! amazing how quickly you've put this together.

**Comment by BastiaanOlij** [comment]
Btw, that broken mesh (the enemy from the TPS demo), looks like the UVs got inverted.

**Comment by fire** [comment]
Made a pull request. https://github.com/godotengine/godot/pull/28459

**Comment by fracteed** [comment]
@fire look like some great work! Will the export to mesh option still be in the mesh menu for single meshes? This would be very useful to me.

**Comment by fire** [comment]
My design is that anything can be considered a scene, to only export a single mesh I would make the single mesh be the entire scene.

**Comment by fracteed** [comment]
thanks, sounds good!

**Comment by golddotasksquestions** [comment]
I've been trying to convert 3 intersecting CSG blocks to a single MeshInstance by using Convert to... -> Mesh library. Is that not how it is supposed to be done?

I find the workflow very confusing. I tried to save it as .meshlib, .tres and .res, and then drag the resulting resource into fresh MeshInstance node of a new scene, none of those three types will work. 

How is this supposed to be done?

**Comment by Calinou** [comment]
MeshLibrary is the resource you use in a GridMap, it has nothing to do with converting CSG nodes to a MeshInstance. See also https://github.com/godotengine/godot/issues/14752.

**Comment by golddotasksquestions** [comment]
Yes I'm following this issue. 
What I was looking for was not an export but a way to combine CSG meshes into one single mesh within the editor (preferably one click) and continue using it as regular mesh. If I were able to continue using it as CSG that would been even much better. 
Are you saying we need to export it first, a feature that is not available yet?
Should I write up a proposal for the "merge a few meshes to one"? 
I thought this was what was discussed and above, no?

**Comment by Calinou** [comment]
> Should I write up a proposal for the "merge a few meshes to one"?

Yes :slightly_smiling_face: 

> I thought this was what was discussed and above, no?

No, this issue seems to be about exposing CSG functionality to scripts so you can procedurally generate stuff using CSG nodes.

**Comment by golddotasksquestions** [comment]
@Calinou 
https://github.com/godotengine/godot-proposals/issues/182

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/182, as feature proposals are now tracked in the Godot proposals repository.

**Comment by C0rez** [comment]
hay posibilidad de implementar esto en la versión 4.3 o posterior, combinación de mesh csg para generar una nueva de la fusión anterior? 

Is there a possibility of implementing this in version 4.3 or later, changing the mesh csg to generate a new one from the previous fusion?
