### ISSUE TITLE
Godot crashes when assigning a viewport to an exisiting viewport texture

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19248]
**Godot version:**
`master` / 2ff31bada

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
Godot crashes with the following message, if you reassign `viewport_path` property of an existing viewport texture instance:

```
ERROR: get_data: Condition ' !vp ' is true. returned: Ref<Image>()
   At: scene/main/viewport.cpp:124.
Stacktrace:
[omitted]

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
```

This can be reproduced with the official `gui_in_3d` demo scene.

**Comment by hpvb** [comment]
I've tried to reproduce this in the editor but it seems to work as expected. Are you programatically changing the path or are you also using the editor?

**Comment by mysticfall** [comment]
No, I just used the `gui_in_3d` demo scene without modifying the source. I just tested it again with the latest master again and it seems that I can no longer reproduce the issue.

Thanks for letting me know that it's fixed now!
