### ISSUE TITLE
Scaled SphereMesh is shaded wrong

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19256]
Godot 3.0.2
Windows 10 64 bits
nVidia 940M

I created a SphereMesh, scaled it vertically so it becomes an ellipsoid, but I quickly noticed something wrong with the shading:

![image](https://user-images.githubusercontent.com/1311555/40680621-0bf33812-6387-11e8-93a6-52dc365033fd.png)

A part of the sphere is completely dark, even though it should be lit at such angle.

Project: 
[ScaledMeshWrongShading.zip](https://github.com/godotengine/godot/files/2050417/ScaledMeshWrongShading.zip)

I had this issue too in my terrain plugin when I implemented ground scaling. At the time I didn't realized it could be a Godot bug, so what I did was to set `global_transform.basis.inverse().transposed()` into a uniform (that matrix interestingly is not built-in), and then I multiply the normal by it in the vertex shader. That's only valid as a replacement to `WORLD_MATRIX` though.

**Comment by akien-mga** [comment]
Fixed by #19786.
