### ISSUE TITLE
UI controls under a viewport node cannot be designed directly

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19258]
**Godot version:**
`master` / 2ff31bada

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
Currently, if you want to create a UI that would be rendered on a viewport node, it is required to create a separate scene to design UI controls because they don't show up in the 2D design view when they are under a viewport.

I'm not sure if there's a good reason that it works the way it does, but from a user's point of view I'd like have an easier way to design UI controls to be used in a viewport without having to create a separate scene just to make them visible in the editor.

**Comment by Zylann** [comment]
Is it only GUI or any node? I remember seeing an issue already about this

**Comment by mysticfall** [comment]
It's for GUI, as I can add/remove/modify child nodes under a viewport from the hierarchy view without a problem.

**Comment by Zylann** [comment]
I know it works to add in tree, what I mean is, that's probably not just an issue with GUI nodes, but also sprites for example.

**Comment by mysticfall** [comment]
Oh, I see. I have no idea if it'd happen for sprites then because I haven't used them yet.

**Comment by Calinou** [comment]
Duplicate of #11727.
