### ISSUE TITLE
Viewport texture logs error if the referenced viewport node is declared after it

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19259]
**Godot version:**
`master` / 2ff31bada

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
If I declare a viewport node, and a mesh which has a material with a viewport texture that references the viewport node, it seems that the mesh mush be placed after the viewport node in the scene hierarchy because it'd throw the below error if the order is reversed:
```
0:00:01:0169 - ViewportTexture: Path to node is invalid
----------
타입:에러
설명: ViewportTexture: Path to node is invalid
시간: 0:00:01:0169
C 에러: Condition ' !vpn ' is true.
C 소스: scene/main/viewport.cpp:65
C 함수: setup_local_to_scene

0:00:01:0186 - Node not found: Viewport
----------
타입:에러
설명: Node not found: Viewport
시간: 0:00:01:0186
C 에러: Condition ' !node ' is true. returned: __null
C 소스: scene/main/node.cpp:1381
C 함수: get_node
```

The error doesn't seem to prevent it from working though.

**Comment by Calinou** [comment]
Closing in favor of #27790, which has more information about the issue at hand.
