### ISSUE TITLE
Tilemap performance reduced when having tiles outside view

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#19254]
**Godot version:**
3.0.2 stable

**OS/device including version:**
MacBook Air (13-inch, Early 2014) (1,4 GHz Intel Core i5)
MacOS High Sierra 10.13.3

**Issue description:**
When having a tilemap with a lot of tiles, the fps is reduced, even if the tiles are outside view. (outside the camera)

**Steps to reproduce:**
1. Create a tilemap
2. Add some tiles
3. The performance is good
4. Add a lot of tiles
5. The fps drops a lot (as shown in Debugger > Monitors > FPS)

**Minimal reproduction project:**
[Tilemap Performance Test.zip](https://github.com/godotengine/godot/files/2049898/Tilemap.Performance.Test.zip)
The reproduction project has 2 scenes:
* Fast scene
When running, the fps is very high. My results are:
![captura de tela 2018-05-29 as 15 04 51](https://user-images.githubusercontent.com/2841740/40677040-de4f5492-6352-11e8-9882-5574e402020f.png)

* Slow scene
The only difference is that the tilemap has a lot more tiles. When running, the fps is very low. My results are:
![captura de tela 2018-05-29 as 15 04 09](https://user-images.githubusercontent.com/2841740/40677076-fb9ed1bc-6352-11e8-88d6-b1e2f0ee0ad6.png)

**Comment by kubecz3k** [comment]
What gpu do you have? How big is the problematic tilemap?

**Comment by jahd2602** [comment]
It is Intel HD Graphics 5000 OpenGL Engine but I found a solution thanks to the guys in the IRC chat. 

> when using y-sort, tiles can't be batched, so it's considerably slower

So disabling y-sort in the tilemap fixes the issue.

**Comment by ByTheQuietLake** [comment]
@jahd2602 hey I just tried your example project and found the faster scene improving moderately from about 1400 fps to 1700fps with Y-sort turned off and the slow scene improving drastically from 60fps to about 800 fps. But I feel your initial question is still valid? why is there a performance difference when the tiles are actually off screen with no difference in the on screen tiles?
