### ISSUE TITLE
ViewportContainer can't change size smaller than initial Viewport size

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#19252]
**Godot version:**
3.1.dev.custom_build.46bab3a

**OS/device including version:**

**Issue description:**
I set Viewport and ViewportContainer size = [1024, 600]
I resize Viewport smaller than [1024, 600] and ViewportContainer still can't resize smaller than [1024, 600]
If over [1024, 600] that OK

**Steps to reproduce:**

**Minimal reproduction project:**
https://www.dropbox.com/s/tc9pjq78bf9pdkz/testViewport.zip?dl=0

**Comment by KoBeWi** [comment]
Still reproducible in 3.1. For whatever reason, it only happens when you set Viewport's size and reload scene. Then you can't resize the container to smaller than Viewport, unless you set Viewport to smaller and reload scene again.

**Comment by KoBeWi** [comment]
This is still valid in 48049b8
The problem is that changing Viewport size doesn't call `minimum_size_changed()` in the container. Also `set_stretch()` should call it too.

**Comment by Nichinoyoobiko** [comment]
Any chance this can be merged into the next 3.x release?

**Comment by KoBeWi** [comment]
It was already, it will come in the next beta.
