### ISSUE TITLE
Add a Script to a node not working sometimes

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#19253]
**Godot version:**
Godot 3.0.3-rc2 win64 

**Issue description:**
When the project get more and more complicated ... when i add a new script to a new node .. it add fine .. i run to test it .. it's not working .. the Editor says that node have that script .. but it's not saved in resource file of that node or scene
when i close Godot and reopen it again .. the node will have no script

and how to fix that is i need to remove .import folder and open the project again .. let Godot load everything again .. add the same script to that node again .. it works fine

Edit : sometimes it's not fixed like that 
sometimes i need to Open the node scene in Text editor and add the script path manually 
like this for exampled adding this line 

`[ext_resource path="res://Scripts/GUI/mybutton.gd" type="Script" id=1]`

**Comment by Zireael07** [comment]
How big is "huge amount", again? 20? 30? 50?

**Comment by eon-s** [comment]
What happens if you add the script, hit ctrl+s, then close and reopen godot?

**Comment by CCODE05B** [comment]
@eon-s nothing .. it does not save the script path at all ... it show save progress bar popup .. but don't save the node / scene and the script
i need to do it manually : open the target scene in a text editor and add the script path like this
`[ext_resource path="res://Scripts/GUI/mybutton.gd" type="Script" id=1]`

save and close ... remove .import folder , open Godot and let it load the project again ... this way work

in Godot 3.0.2 Stable everything work Great

**Comment by eon-s** [comment]
And no error output on the console window on add script or close?

**Comment by CCODE05B** [comment]
@eon-s Nothing ... everything is fine until i run the scene to test it - and when i test it .. it's like a scene without a script
Close and open Godot again .. the scene or the node does not contain the Script that i added

**Comment by Calinou** [comment]
This issue is old (and the author has deleted their account from GitHub), so I'll close this. Please create a new issue if you can still experience a similar bug.

**Comment by mtedmist** [comment]
I am having a similar problem with 3.2.3.stable. Right-clicking a scene and adding a script does not correctly link the script. I have to manually edit the scene outside of Godot.

**Comment by Calinou** [comment]
@mtedmist Please create a new issue if you can still experience a similar bug.
