### ISSUE TITLE
UI Improvement - Export with Debug On

### ISSUE THREAD

**Issue by SystemLogoff** [godotengine/godot#19260]
**Godot version:**

3.0.2

**OS/device including version:**

Windows

**Issue description:**

The export with debug button is very hard to notice, and the documentation does not list where it is very well. I had to ask the community the location after looking for it. 

Can the documentation be updated to include the location? Or have a way to make it more obvious in the UI when you are exporting your project?

https://i.imgur.com/AdntNoA.png -- Screenshot.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1071, as feature proposals are now tracked on the Godot proposals repository.
