### ISSUE TITLE
Transparent material mix issue.

### ISSUE THREAD

**Issue by Gyrth** [godotengine/godot#19269]
**Godot version:**
3.0.2

**OS/device including version:**
Ubuntu Linux 18.04

**Issue description:**
When I look through my skylight asset the glass seems to flicker. This is because the Blend Mode is set to Mix. With Blend Mode set to Add it doesn't happen. I'm not sure if this still counts as a bug, since you can work around it, but I thought I report it anyway.

**Steps to reproduce:**
Apply a transparent material with the Blend Mode set to Mix to two different objects and look through both of them. 

![peek 2018-05-30 15-40](https://user-images.githubusercontent.com/14081613/40724436-5bc97eec-6421-11e8-83b1-e2fbdd35f574.gif)
![image](https://user-images.githubusercontent.com/14081613/40724475-6dc79336-6421-11e8-8c66-a81ad53efc8f.png)
![image](https://user-images.githubusercontent.com/14081613/40724520-83d0a366-6421-11e8-8514-5627619ce1bb.png)
![image](https://user-images.githubusercontent.com/14081613/40724529-89bc2e08-6421-11e8-9291-2ea5d8b64407.png)

**Comment by swarnimarun** [comment]
It does count as a bug, and it seems to be a problem with the rendering system.

**Comment by CptPotato** [comment]
Maybe it's z-sorting related. Where are the origins of your glass objects?

**Comment by OGMP-Gyrth** [comment]
Yes, @CptPotato, it appears the origin is all at the same position. I thought the polygon position set it's z position, but it's the origin position?

**Comment by bojidar-bg** [comment]
When multiple transparent objects are rendered, the z-buffer becomes mostly useless. Instead, they have to be sorted on-CPU before sending them for drawing, otherwise, improper layering occurs.

**Comment by OGMP-Gyrth** [comment]
So should this be regarded as a bug or should I close this? And don't put transparent objects at the same origin point?

**Comment by CptPotato** [comment]
It's not really a bug in my opinion, it's just how 3d engines sort transparent objects.

One possible proposal would be to have an option to automatically calculate an origin offset that's used for sorting. But looping through thousands of vertices is kind of slow so it would mostly make sense as an import option.

Personally I think that fixing the origin should be done when exporting the mesh. Adding a new feature just for that seems more like an unnecessary workaround to me.

**Comment by Zireael07** [comment]
I had similar issues with meshes at different origin points (clouds = player's origin, tree = the tree's own origin, ahead of the player; clouds ended up obscuring the tree). I worked around this by making most of them use alpha scissor, which moves them to opaque pass and neatly sidesteps the issue.

**Comment by Calinou** [comment]
This can't really be solved without introducing expensive order-independent transparency, so I'll close this.

This limitation (among many others) has been documented in [3D rendering limitations](https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html).
