### ISSUE TITLE
Visual Script Editor is broken since the new Inspector

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#19267]
**Godot version:**
Godot Master

**Issue description:**
As you can see that the VS editor is now broken. Made this issue just to remind people of the issue. So that it's not forgotten for long.

![image](https://user-images.githubusercontent.com/19930870/40717154-fd537c20-6428-11e8-82fa-6b9d79d64977.png)

**Comment by bojidar-bg** [comment]
Potentially related to #18940.
