### ISSUE TITLE
Changing Area2D shape causes resend of body_exited and body_entered for enclosed body

### ISSUE THREAD

**Issue by Ramshell** [godotengine/godot#19271]
**Godot version:**
3.0.2-stable

**OS/device including version:**
Ubuntu 18.04 bionic

**Issue description:**

If a body __x__ is inside an Area2D (I mean the Area2D already received the body_entered(__x__)) and you resize the Area2D shape in such a way that the body is still inside the shape, it triggers body_exited(__x__) and then body_entered(__x__), like if the Area2D or the shape were being deleted and created again.
¿Is this the expected behavior?
I think that the body_entered and body_exited should be called only once in this case (i.e the body have never exited the area)

**Steps to reproduce:**
I have something like this:
* Area2D
  * CollisionShape2D with a Rectangle

![selection](https://user-images.githubusercontent.com/12850723/40724299-1fb71114-63f7-11e8-942b-47a515525f63.png)

This Area2D has an script that updates the rectangle with the mouse dragging (like a rectangle selection)

```gdscript
extends Area2D

var dragging = false
var color = Color(0, 0, 1, 0.3)

func _ready():
	$".".connect("body_entered", self, "select_unit")
	$".".connect("body_exited", self, "deselect_unit")
	pass
	
func select_unit(body):
	body.set_selected(true)

func deselect_unit(body):
	body.set_selected(false)

func _input(event):
	var mouse_pos = get_global_mouse_position()
	if event is InputEventMouseButton:
		match event.button_index:
			BUTTON_LEFT:
				if event.is_pressed() and not event.is_echo():
					dragging = true
					$rect.position.x = mouse_pos.x
					$rect.position.y = mouse_pos.y
					$rect.shape.extents.x = 0
					$rect.shape.extents.y = 0
				elif not event.is_pressed():
					dragging = false
					print($rect.position.x, " ", $rect.position.y)
					$rect.shape.extents.x = 0
					$rect.shape.extents.y = 0
					update()
	elif event is InputEventMouseMotion:
		if dragging:
			$rect.shape.extents.x += event.relative.x / 2
			$rect.shape.extents.y += event.relative.y / 2
			$rect.position.x += event.relative.x / 2
			$rect.position.y += event.relative.y / 2
			update()

func _draw():
	if dragging:
		var a_rect = Rect2($rect.position.x - $rect.shape.extents.x, $rect.position.y - $rect.shape.extents.y, $rect.shape.extents.x * 2, $rect.shape.extents.y * 2)
		draw_rect(a_rect, color)

func _process(delta):
	print($rect.position, " ", $rect.shape.extents)
	pass
```
In the other hand I have a KinematicBody2D with a rectangle shape:

![unit](https://user-images.githubusercontent.com/12850723/40726858-fcde1fba-63fc-11e8-9477-6472541e9dec.png)

The unit code is this:

```gdscript
extends KinematicBody2D

export var selected = false

func set_selected(value):
	selected = value
        print(value)
```

To test it you can put this nodes in a parent Node. You will have to draw a rectangle that overlaps the KinematicBody2D and see how it prints false -> true -> false -> true infinitely while the rectangle is being resized.

**Comment by swarnimarun** [comment]
It's likely because it recalculates the whole thing again. Once size is changed, not really sure if it can even be fixed.

**Comment by Ramshell** [comment]
Recalculate doesn't mean to resend the signals to the objects that have already been notified. I could try to fix it but I would like to discuss it first.

**Comment by eon-s** [comment]
Is what usually happens, not what is expected.
There is another related issue with the inverse problem where you need to move the area for the Physics server to register the new shape too #8325.

**Comment by swarnimarun** [comment]
It seems old, is there some problems with fixing it. Why has it not been fixed yet.?
Cause it seems like sort of major issue, even though it has workaround it is common enough that many if fall prey to it. Is it breaking something to fix it.

**Comment by Ramshell** [comment]
I looked in the code and I couldn't find any clue on where could this bug be. Probably it is the part that calls update() in the CollisionShape2D::shape_changed() method.

**Comment by akien-mga** [comment]
Confirmed in the current master branch (c4234b152), made this reproduction project: [area2d_shape_resize.zip](https://github.com/godotengine/godot/files/2561941/area2d_shape_resize.zip)

**Comment by KoBeWi** [comment]
I have a similar problem. I use KinematicBody2D with 2 shapes, one of which is disabled. When I disable one and enable another, any area the body is in gets `body_enter` triggered. This does happen even if both shapes are never disabled at the same time.

**Comment by akien-mga** [comment]
For the record, I checked if #33615 fixes this but it doesn't.

**Comment by fossegutten** [comment]
Disabling a CollisionShape2D also triggers the exited signal, which is probably should not.
Workaround: Set collision layer to 0 instead

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4

**Comment by AttackButton** [comment]
As I mentioned here: https://github.com/godotengine/godot/issues/14578#issuecomment-761567247, one workaround is to reconnect the `body_entered` (or `area_entered`) signal with the CONNECT_DEFERRED | CONNECT_ONESHOT options every time the signal is used instead of let it always connected.

Something like:
`$Area2D.connect("body_entered", self, "_player_to_right", [], CONNECT_DEFERRED | CONNECT_ONESHOT)`

**Comment by Rindbee** [comment]
> Confirmed in the current master branch ([c4234b1](https://github.com/godotengine/godot/commit/c4234b15211beca909c5850aeb74f87356c895d1)), made this reproduction project: [area2d_shape_resize.zip](https://github.com/godotengine/godot/files/2561941/area2d_shape_resize.zip)

Using this reproduction project, I was unable to reproduce it in v4.0.stable.official [92bee43ad].
