### ISSUE TITLE
Edited value has change when Play Scene

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#19274]
**Godot version:**

v3.1.dev.custom_build.28fa82c

**OS/device including version:**

**Issue description:**
Example:
gdscript add:
```
export( Rect2 ) var rect = Rect2( 0, 0, 1, 1 )
```
Inspector I edit value to ( 0, 5, 1, 1 )
When I press "Play Scene" button value has change to ( 5, 0, 0, 1 )

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by ordigdug** [comment]
@Mavhod I am unable to reproduce this issue. Are you still experiencing it with latest build?

**Comment by Mavhod** [comment]
Ok, It correct now.
