### ISSUE TITLE
Ability to manually place autotiles

### ISSUE THREAD

**Issue by Jellonator** [godotengine/godot#19295]
Godot version: 3.0.2.stable.official

I have an autotiling tileset for a city road that looks kinda like this:
![tileset-road](https://user-images.githubusercontent.com/1700153/40807393-304e009a-64f2-11e8-8c78-a9c633317874.png)

However, when I draw something using it, it ends up looking chaotic sorta like this:
![screenshot_2018-05-31_16-51-22](https://user-images.githubusercontent.com/1700153/40807650-ec5dcf2c-64f2-11e8-81b4-2632acf2e06f.png)

What I want is to be able to create something like this, without having to constantly change probabilities and remove/re-add tiles to get it the exact way I want it:
![screenshot_2018-05-31_16-51-22-v2](https://user-images.githubusercontent.com/1700153/40807898-936153c0-64f3-11e8-8832-6146b62723f4.png)

It would be really useful to be able to switch between autotiling and manually placing tiles from an autotile-set. It would also be useful to be able to set a tile's probability to 0 so that it doesn't get placed when autotiling.

**Comment by Zylann** [comment]
But... isn't this what non-autotiles do? (aka normal tiles?)

**Comment by Jellonator** [comment]
Kinda, but autotiles have many quality of life improvements. They're easier to set up (I don't need to create a scene with separate objects for each tile of a tileset), and they're easier to create tilemaps with.

My ideal workflow with autotiles would be to create the general shape of what I want with autotiles, then go through and add specific details that I want later.

**Comment by Zylann** [comment]
> They're easier to set up (I don't need to create a scene with separate objects for each tile of a tileset)

Note that this reason isn't really valid, because that's just an issue with the UI not integrating creation of normal tiles in the first place.

**Comment by CowThing** [comment]
Should this be closed? Now that the PR was merged.

**Comment by bojidar-bg** [comment]
Yes, implemented by #19314.
