### ISSUE TITLE
RigidBody.get_colliding_bodies() doesn't identify CSG

### ISSUE THREAD

**Issue by CosineP** [godotengine/godot#19298]
**Godot version:** 255d6470eec957b2d5010bd494f357aff1f7e8c6 (master as of writing)
 

**OS/device including version:** Linux (Debian 9)

**Issue description:** CSG collisions, while performing in the physics engine, are not brought out to `get_colliding_bodies`

What happens:
 - `get_colliding_bodies()` always returns `[]`

What's expected:
 - `get_colliding_bodies()` returns an array including a reference to the `CSGCombiner` with collision enabled

The same occurs if the `CSGCombiner` is a child of a `StaticBody` (the `StaticBody` doesn't recognize the `CSGCombiner` as a collisionshape)

**Steps to reproduce:**
Have a RigidBody, and CSGCombiner with even just one cube. Call `get_colliding_bodies()`. (See project)

**Minimal reproduction project:**
[csg-colliding.zip](https://github.com/godotengine/godot/files/2060462/csg-colliding.zip)

**Comment by akien-mga** [comment]
The reproduction project seems to work fine on the current master branch (cf07169), this was probably fixed by #22973.
