### ISSUE TITLE
Popup spawned from EditorPlugin has size (0,0)

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#19292]
**Godot version:**
10cab25

**Issue description:**
Sometime between the build specified and one from about a week ago (sorry, don't know the exact commit!), the popup in my plugin now seems to spawn into the editor with an incorrect size.  It's launched nearly immediately after activating the plugin, using popup_centered().  No min size set, default rect size of (800,480).  Perhaps one of the recent tweaks to make sure certain UI elements don't fly out of bounds are responsible?

![image](https://user-images.githubusercontent.com/1023003/40790980-ef5f5cae-64bb-11e8-80eb-1c1f2c609305.png)

**Steps to reproduce:**
Make an EditorPlugin spawn a popup of a certain expected size.  (Toss some controls on it to see what's going on maybe)

**Comment by AlexHolly** [comment]
duplicate? https://github.com/godotengine/godot/issues/18940

**Comment by nobuyukinyuu** [comment]
@AlexHolly they certainly seem like they could be related....
