### ISSUE TITLE
[Bullet] area_shape is 0 in body_shape_entered and body_shape_exited

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#19290]
**Godot version:**

v3.1.dev.custom_build.43b7ebf

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**
1. Add Area node in scene
2. Add CollisionShape with some Shape
3. Add 2. more
4. Connect body_shape_entered or body_shape_exited signal
5. When body is intersected ```area_shape``` in function will always = 0 event if body had intersect any shape of Area

**Minimal reproduction project:**

**Comment by AndreaCatania** [comment]
Can you please upload a sample project please?

**Comment by Mavhod** [comment]
See here:
https://www.dropbox.com/s/ixe9lv93jxjs1ib/testCollide.zip?dl=0

From sample it also have bug receive signal even it's not collided.

You can set "Project Settings->General->Physics->3d->Physics Engine" and set to "GodotPhysics", so it will be run correctly.

**Comment by jknightdoeswork** [comment]
Just chiming in to say that I experience this issue as well.

**Comment by akien-mga** [comment]
I can confirm the bug in the current master branch (ce75a2f33d).

It works fine with GodotPhysics using the project in https://github.com/godotengine/godot/issues/19290#issuecomment-464853583 (`area_shape` is respectively 0, 1, 2 or 3), but with Bullet it's always 0.

**Comment by KoBeWi** [comment]
Turns out `body_shape` has the same problem. Here's a project (I wanted to make issue, but it would be pretty much duplicate):
[ReproductionProject.zip](https://github.com/godotengine/godot/files/4167845/ReproductionProject.zip)

**Comment by AlexZan** [comment]
Anyone working on this? Is it just a matter of replicating the solution from area_2d into area?

**Comment by 19PHOBOSS98** [comment]
it's still here on 3.2.3 rc3. Please for the love of everything that is pure and good someone fix it :'(

**Comment by chucklepie** [comment]
hello, i  don't know if this is the solution or an artefact of the problem (i raised ticket #42614, which was kind of more about lack of documentation and mixing up of parameter names). In the area_shape entered signal, the self_shape property actually contains the index of the shape not shape_id, which is always zero.  When you use body_shape entered the index is called shape_id.

So, I dunno if simply the self_shape/shape_id are being mixed up or intentionally like this in area shape entered function?

**Comment by chucklepie** [comment]
I've discovered something worse. I have two different scenes with area2D using multiple collisions and need to check for which collision polygon shape was triggered.

In my two methods, one always has area_shape parameter as zero and self_shape parameter as the collision index,
the other always has self_shape as zero and the area_shape the collision index!

I have no idea how it's coded or what's making it choose the index but it cannot be the ordinal value in the scene :(

If you want a video I am happy to share it. Can I produce a small program? I don't know because it's just random which method it chooses to set the index to.

```
func _on_PlayerSpawnPointCentre_area_shape_entered(_area_id: int, area: Area2D, _area_shape: int, self_shape: int) -> void:
#this one uses self_shape!

func _on_PlayerEdgeDetection_area_shape_entered(area_id: int, area: Area2D, area_shape: int, self_shape: int) -> void:
#this one uses area_shape!
```
