### ISSUE TITLE
Add the ability to import projects by selecting a ZIP archive

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#19296]
It would be easier for users if Godot could import projects as ZIP archives directly (as an alternative to selecting a `project.godot` file). This way, less clicks would be required to import a freshly-downloaded project; this would also solve the issue with [some beginners forgetting to extract the ZIP and wondering how to import the project](https://www.reddit.com/r/godot/comments/8n0nxv/problem_with_godot_tutorial_it_may_seem_very_dumb/).

This could work in two cases:
- If the `project.godot` file is located at the root of the ZIP archive.
  - This is the kind of ZIP that is created when selecting all files in the project's root directory then adding them to a ZIP archive.
- Or, if the project.godot file is located at the root of the only directory contained in the ZIP archive.
  - This is how most ZIP archives are created, such as automatically-generated ZIPs from GitHub.

For the record, this is supported in other software such as Blender, which is able to import add-ons directly from a ZIP archive.

**Comment by eon-s** [comment]
Also, the asset library download and unpack zip files, so the functionality is there.

**Comment by mhilbrunner** [comment]
Sounds good, but wondering to which path should Godot extract the project?

**Comment by bojidar-bg** [comment]
Well, maybe it should be handled by the asset lib, so, showing the same dialogs and stuff.

**Comment by Sslaxx** [comment]
Importing new projects should go to the default directory shouldn't it? It might require (for the first time) having the user specify which directory is used for Godot projects though.

**Comment by swarnimarun** [comment]
I think that it's time for Godot to have a default directory like a Work-space and that will be where we create imported projects.
But that would also be the place where Godot asks to create projects whenever we click new project button. If not set then, we can just ask for a path to place the imported project into.

But if all that were to be added it won't really be a junior job.

**Comment by OvermindDL1** [comment]
I also agree that it should just ask the path to extract to.

**Comment by LinuxUserGD** [comment]
I think it could extract it to the same path.

**Comment by numan98khan** [comment]
You know what I am gonna try to do this. @swarnimarun are you the same guy from the discord chat?

**Comment by swarnimarun** [comment]
@numan98khan yep. 
And I think that even though this one says junior job this one one depending what you plan to do might not be one. Anyways I don't think it will be very difficult anyways.

And I think a selection on opening Godot the first time to select a home directory for Godot will be a good addition.
Import from Zip will be directly done there.

**Comment by numan98khan** [comment]
@swarnimarun got it thanks for the support.

**Comment by Calinou** [comment]
[A pull request that implement this feature was already opened](https://github.com/godotengine/godot/pull/19693).

**Comment by akien-mga** [comment]
Fixed by #19693.
