### ISSUE TITLE
Impossible to set colors properly on Color Gradient in Particled2D

### ISSUE THREAD

**Issue by wombatwingdings** [godotengine/godot#19308]
**Godot version:**

3.1 build from source
Head as of 1st June 2018

**OS/device including version:**

Windows 10 x64 (tried on two separate machines using independent build from source)

**Issue description:**
It is next to impossible to set the color gradient as you want it using the color tab stops and color picker

**Steps to reproduce:**
Create new scene
add root node (anything)
add Particles2D
Process Material -> New Particles Material
select Particles Material -> Color -> Color_ramp -> New Gradient Texture
select GradientTexture -> gradient -> New Gradient
select Gradient

Problem 1 
Opening Colors "ColArray[2]" shows index 0 and 1 with color bars. Select one of those colors brings up the "color picker".
Selecting the right hand column high-level color just closes the color selector. I would have thought it should reposition the left hand color column to allow finer detail color selection. But it does not. On some indexes it selects the high level color into the array there and then. On others it just does nothing.

Problem 2
Adding "stops" on the color gradient is impossible to set the colors how you want them. Clicking on one of the color stop tabs allows you to set a color, but it doesn't set it to the tab you selected. It's just a bit mad.

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
Same problem in Particle3D

**Comment by ordigdug** [comment]
Array color picker issues are fixed in #20363.
