### ISSUE TITLE
Could not create framebuffer when showing minimized window

### ISSUE THREAD

**Issue by travisapple** [godotengine/godot#1930]
I get these two warnings over and over hundreds of times in the output window

drivers/gles2/rasterizer_gles2.cpp:10314 - Could not create framebuffer!!
drivers/gles2/rasterizer_gles2.cpp:10350 - Could not create framebuffer!!

https://github.com/okamstudio/godot/blob/master/drivers/gles2/rasterizer_gles2.cpp

My video card is relatively new with current and non-custom drivers on win7 64
Card: NVIDIA GeForce GTX 760

**Comment by reduz** [comment]
do you have the latest drivers installed?

**Comment by travisapple** [comment]
I do. I have the latest version from NVIDIA. Thanks for looking into this!

**Comment by travisapple** [comment]
This is displayed with the above warnings in the command line window but not the output frame:
ERROR: _draw_viewport:  Condition ' desired_rect.width<=0 || desired_rect.height <=0 ' is true.
At:  servers/visual/visual_server_raster.cpp:6965

https://github.com/okamstudio/godot/blob/master/servers/visual/visual_server_raster.cpp

**Comment by romulox-x** [comment]
Do you have an example project where this happens?  I've got a 770, and Windows 7 64 bit.  I'm curious if I could reproduce it.

**Comment by travisapple** [comment]
Ok after playing around with this I finally figured out a way to reproduce this.
1: Open Godot
2: Open Any project
3: On windows, there's a blue "Show Desktop" button in the tray (bottom right). Click that. It should minimize all windows.
4: Now click on the task bar to show the Godot window. There should be hundreds of these errors in the output window that showed up as the window was minimized.

I verified that this is also an issue on two other computers (all Win 7) for both 32bit and 64bit. All three computers have different video cards from different manufacturers. 

The issue is the "Show Desktop" button on Win 7.

**Comment by SuperUserNameMan** [comment]
On Windows 8.1 too.

````
WARNING: RasterizerGLES2::_update_framebuffer:  Could not create framebuffer!!
At:  drivers\gles2\rasterizer_gles2.cpp:10314
WARNING: RasterizerGLES2::_update_framebuffer:  Could not create framebuffer!!
At:  drivers\gles2\rasterizer_gles2.cpp:10350
ERROR: VisualServerRaster::_draw_viewport:  Condition ' desired_rect.width<=0 || desired_rect.height<=0 ' is true.
At:  servers\visual\visual_server_raster.cpp:6965
````

**Comment by Krzycho666** [comment]
I thought that this is normal ( Windows 7 x64 Pro ):

```
At:  servers/visual/visual_server_raster.cpp:6965
WARNING: _update_framebuffer:  Could not create framebuffer!!
At:  drivers/gles2/rasterizer_gles2.cpp:10314
WARNING: _update_framebuffer:  Could not create framebuffer!!
At:  drivers/gles2/rasterizer_gles2.cpp:10350
ERROR: _draw_viewport:  Condition ' desired_rect.width<=0 || desired_rect.height
<=0 ' is true.
```

**Comment by toger5** [comment]
This also happens when using the Win+D shortcut (obviously), just wanted to mention that I have that problem too. (Raden HD7850)
```drivers\gles2\rasterizer_gles2.cpp:10467 - Could not create framebuffer!!, code: 36054```
