### ISSUE TITLE
Question : Why Lights make FPS drop ? and why only 7 or 8 lights can effect one object ?

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#19305]
**Godot version:**
Godot 3.0.2 Stable

**OS/device including version:**
windows 7 x64
8 GB Ram
GTX 980
i7 4790K

**Issue description:**
Why any light source make the FPS Drop ?
i have a very very simple scene .. the FPS is about 200 , Added 4 Spot lights + 4 Omni lights .. the FPS dropped to about 125 , i know the lights and shadows cost ... but not that much 

Another question .. i noticed a single object can be affected only with 7 or 8 lights ?

**Comment by Zireael07** [comment]
Yes, maximum of lights that can affect an object is 8.

Also you should not look at absolute FPS value, but at the ms timings. The difference in timings between 200 fps and 125 fps is not that huge - 5 ms vs 8 ms per frame.

**Comment by CCODE05B** [comment]
@Zireael07 why it's limited to 8 lights ? is it OpenGL limitation ?
where / how can i find ms timing ?

**Comment by CptPotato** [comment]
> Yes, maximum of lights that can affect an object is 8.

I find it a bit confusing that lights are performed in a forward rendering fashion, as Godot is presendet as a forward/deferred rendering hybrid on the homepage. One of the main benefits you get from deferred rendering is unlimited lights per object.

**Comment by CCODE05B** [comment]
i hope someone can answer

**Comment by mrcdk** [comment]
Yes, lights are limited. Clustered rendering is in the roadmap https://github.com/godotengine/godot-roadmap/blob/master/ROADMAP.md and will probably come when Vulkan is added.

**Comment by Olm-e** [comment]
actually this rendering of the shadows make them unusable in VR at the moment : 
when activated, just one shadow makes the framerate to 1/4th of previous fps or less ... 
imho something is not ordered correctly here I think not just waiting vulkan ;)
https://github.com/GodotVR/godot_openvr/issues/24#issuecomment-409710775

**Comment by Calinou** [comment]
The 8-lights-per-mesh limit has been removed in the `master` branch thanks to clustered forward rendering, closing.
