### ISSUE TITLE
Triplanar mapping breaks additional maps

### ISSUE THREAD

**Issue by yaelatletl** [godotengine/godot#19301]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10, latest release

**Issue description:**
Materials applied as triplanar won't use any maps other than roughness, normal maps, albedo and emission; depth and refraction maps will be ignored, I haven't tested any other maps though.

**Steps to reproduce:**
Just create a material with any mentioned map and use triplanar mapping

**Minimal reproduction project:**
Will provide if asked to.

**Comment by Bauxitedev** [comment]
Yeah, I noticed detail textures won't work with triplanar enabled as well: https://github.com/godotengine/godot/issues/18550

**Comment by akien-mga** [comment]
Duplicate of (fixed) #19301.

**Comment by bojidar-bg** [comment]
@akien-mga of course it is a duplicate! It is the same issue after all..

Was the issue actually fixed?

**Comment by akien-mga** [comment]
It was a duplicate of #18550 referenced above.
