### ISSUE TITLE
[C#] Godot does not recognize source code changes anymore unless I manually build them

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19317]
**Godot version:**
`master` / 2ff31bada

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
If I recall correctly, Godot used to detect source code changes from an external editor (which is almost mandatory for C#), so I can just hit play to see the result.

But recently, it stopped doing so and now I have to manually build the source from my IDE to see the changes in effect when running the project inside Godot.

**Comment by mysticfall** [comment]
I just discussed it with other people who use C# on Discord, and at least one person say he can't reproduce the issue.

I think I prematurely assumed that it was Godot that has been changed recently. I'll close the issue for now and will reopen it if I find any more specific information that confirms it's indeed an issue.

**Comment by neikeq** [comment]
This sounds unlikely since right now, builds are ran everytime the game is execute. Maybe the problem was something different?

**Comment by mysticfall** [comment]
Yes, I still see this problem from time to time but it happens pretty rarely. I haven't been able to find the real cause, and it's quite possible that something other than Godot is at fault.

I'll reopen the issue in case if I find new information as I mentioned above. Thanks!

**Comment by mysticfall** [comment]
Upon more testing, the problem still persists and seems to have something to do with `.dll` assembly remaining stale even after the build.

I updated the title and description to reflect the new information, and see if I can gather more to track down the cause.
