### ISSUE TITLE
Can Round() have second parameter?

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#19315]
Is there a way to round 1.3453 to 1.35?
round() only rounds to the nearest integer. Some languages have a second parameter in the round() function to designate what position to round to. Is there an equivalent in Godot?  If not, can this be added, for instance: 

`round(1.3453 , 2)`

results: 1.35

**Comment by romeojulietthotel** [comment]
Does stepify(1.3453, 0.01) meet your needs?

**Comment by ondesic** [comment]
Thanks! that works.  On the normal forum Q&A, no one knew of an answer.  I was using stepify at first, but using it wrong.  
To be honest the name "stepify" isn't intuitive.  I had to search a lot and stumbled upon it.  It is basically rounding, but to a preset decimal place.  This is probably the reason other languages use `Round(num, place)` because it is all part of rounding
