### ISSUE TITLE
Editor closes sub-windows when clicking outside them 

### ISSUE THREAD

**Issue by alkhimey** [godotengine/godot#19312]
**Godot version:** 

3.0.2

**OS/device including version:** 

Linux, Ubuntu 17.10 64 bit

**Issue description:**

Pressing the mouse button when the cursor is outside an open sub window will close it.
This is not a bug but rather a design flaw.
It can cause a little bit of frustration when work in progress is accidentally closed because of careless mouse press.

For example, downloading export templates might take some time. It really surprised me when I tried to bring the editor from background by clocking on it and the download window suddenly disappear. 

**Steps to reproduce:**
![screenshot from 2018-06-01 23-50-51](https://user-images.githubusercontent.com/652603/40863012-10f29516-65f7-11e8-904c-c19cca8b4ab8.png)

**Minimal reproduction project:**

Not relevant

**Comment by Zylann** [comment]
Since it matters for some windows but not others, could this be an option? They could also be set as modal.

**Comment by KoBeWi** [comment]
The export template window no longer closes when clicked outside, as of 3.1.

**Comment by Calinou** [comment]
This behavior was removed in 4.0, closing.
