### ISSUE TITLE
Keeping a control centered in it's parent is a hassle

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#19329]
**Godot version:**
3.1 master branch

**Issue description:**
With the complex anchors/margins/size/position/pivot system in Godot 3.x you would think that it would be easy to set a control to be centered in its parent and keep it that way.

However if that control has to have its size changed, then the only way to keep it centered is to write additional code to 'recenter' it each time its size changes.

This also applies to designing a UI in the editor. `CenterContainers` don't seem to re-center the item for you when the size changes, only when the minsize changes. I don't really understand why.

What I think should be done is that when a control's size changes, it should look at the current Anchor settings and respect them. For example if the anchors corresponds to 'Top Left' then the width should increase to the right. If the anchors correspond to 'Top Right' then the width should increase to the left. If it corresponds to 'Center' then width should increase to the left and right equally Etc. It should be done like this when you're dragging to resize, when you edit the size in the inspector and when the control's size is changed in code.

See below for gif of trying to keep a control centered
![center](https://user-images.githubusercontent.com/357737/40872206-af719728-6674-11e8-83f8-e173d54753fb.gif)

Even during ui design, this is a bit irritating as when you adjust something's size you have to keep 'recentering' it.

In some ways in HTML/CSS it is actually easier to position things than this.

**Comment by groud** [comment]
They are several points your question:
- I kind of agree that changing a node's size should use the anchor position to grow the node in the appropriate direction. I might look into it.
- The anchors and margins have no meaning when child of a container. I think I will disable editing nodes that are child of a container. Only the minimum size is taken into account in such case.
- we cannot change the editor behaviour regarding resizing a node. You should be able to grow a node in both direction (thus kept centered) if you press the ALT key while dragging.

**Comment by chanon** [comment]
I tried implementing this in the pull request above and it works pretty nicely, except drag-resize ui needs to be adjusted.

**Comment by bojidar-bg** [comment]
Shouldn't this be handled by the Grow Direction settings?

**Comment by chanon** [comment]
I did try using Grow Direction but it doesn't seem to have any effect. I think Grow Direction is used only when it is in a container? Here the controls are not in a container.

**Comment by mitchcurtis** [comment]
Related: https://github.com/godotengine/godot/issues/28489

**Comment by KoBeWi** [comment]
Grow Direction only has effect when Control's minimum size changes, not its size. It's already documented, closing.
