### ISSUE TITLE
Editing a Vector2Array in the inspector can make the cursor disappear

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#19321]
**Godot version:**
 8684b63

**Issue description:**
This seems to only happen to me when editing a `Vector2Array` elements in a `LightOccluder2D`, but when clicking very fast/moving the mouse while clicking, it can make the mouse cursor disappear completely, and not reappear until the editor is closed.

**Comment by bojidar-bg** [comment]
A video of the bug would be welcome; alternatively, more specific reproduction steps would be good as well.

**Comment by YeldhamDev** [comment]
@bojidar-bg I don't think a video would help in this case, but here it goes:

![peek 2018-06-03 13-11](https://user-images.githubusercontent.com/30739239/40888592-04580e32-6749-11e8-9bb3-21be6e85e998.gif)

And the I can't really get more specific on the reproduction steps, it's just clicking fast and moving the cursor left and right.

**Comment by bojidar-bg** [comment]
That's remarkably easy to confirm actually...

**Comment by YeldhamDev** [comment]
This issue doesn't happen anymore, closing it.
