### ISSUE TITLE
KEY_BACK is confusing on mobile devices

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#19325]
**Godot version:**

Godot 3.0.2

**OS/device including version:**

Android device with soft navigation keys.

**Issue description:**

When press the back key, no InputEventKey is triggered.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment]
Shouldn't it trigger a `NOTIFICATION_WM_GO_BACK_REQUEST` instead? [Docs about handling it.](http://docs.godotengine.org/en/latest/tutorials/misc/handling_quit_requests.html)

**Comment by alexzheng** [comment]
Yes, it triggered a NOTIFICATION_WM_GO_BACK_REQUEST, the document need update.
However, there is a KEY_BACK definition, I thought there must some way to catch it, or else this constant is useless.

**Comment by bojidar-bg** [comment]
Looking at the code, `KEY_BACK` is emitted when pressing:
* `AKEYCODE_MEDIA_REWIND` on android,
* `VK_BROWSER_BACK` on windows,
* `XF86XK_Back` on x11/linux (with a comment about it being a media key).

Maybe it would be better to rename it as `KEY_MEDIA_BACK` (similar for `KEY_MEDIA_FORWARD`)?

**Comment by alexzheng** [comment]
Yes, the KEY_BACK will be mistaken as pressed the back key of the device in Android.
Then is the only collect way to catch the press back key in Android is the NOTIFICATION_WM_GO_BACK_REQUEST? If that's true, the issue can be closed.
