### ISSUE TITLE
Change type doesn't support undo.

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#19326]
**Godot version:**
Godot Master

**Issue description:**

- There basically is no code to support undo and tell the scene that something has changed in the replace_node() method, and obviously it doesn't do anything if you try to undo it.
- And neither does the scene register any changes(you know that asterisk on the right of the scenename).
- And if you don't hit Ctrl+S or save the scene you are doomed to lose the change.

And if there is already an issue about it I am sorry couldn't find it,

**Comment by aaronfranke** [comment]
Related: https://github.com/godotengine/godot/issues/6150
