### ISSUE TITLE
Mouse Cursor must be 32x32 on Mac

### ISSUE THREAD

**Issue by christophgomez** [godotengine/godot#19339]
**Godot version:**
Godot 3.0.2

**OS/device including version:**
macOS

**Issue description:**
Input.set_custom_mouse_cursor() returns an error if image is not exactly 32x32, same error if trying to do it through the editor. The image is 64x64.

> 0:00:00:0687 - Condition ' texture->get_width() != 32 || texture->get_height() != 32 ' is true.
> ----------
> Type:Error
> Description: 
> Time: 0:00:00:0687
> C Error: Condition ' texture->get_width() != 32 || texture->get_height() != 32 ' is true.
> C Source: platform/osx/os_osx.mm:1353
> C Function: set_custom_mouse_cursor

Issue #18115 says it was fixed back in April, but I'm still getting this error. 

**Steps to reproduce:**
Try setting the input cursor through GDScript or the editor

**Comment by vnen** [comment]
> says it was fixed back in April, but I'm still getting this error.

Godot 3.0.2 was release in March.

**Comment by christophgomez** [comment]
Oh, odd. I have Godot installed through Homebrew and when I run brew upgrade on it, it says it's up to date. Ok, not a Godot issue.
