### ISSUE TITLE
Request: Add 'Wait for Debugger' option to the debug menu drop down for Mono version

### ISSUE THREAD

**Issue by exts** [godotengine/godot#19335]
**Godot version:**
3.0.X

**OS/device including version:**
All

**Description:**
Basically right now we have to constantly open the `Project -> Project Settings -> Mono -> Debugger Agent` settings to enable/disable the wait for debugger setting for debugging our mono projects.

It would be nice if we could get this option also added here under the debug menu.

![](https://cdn.discordapp.com/attachments/389794884585914368/452248815135621140/unknown.png)

**Comment by neikeq** [comment]
AFAIK, there is no interface to add options to that menu.

**Comment by Calinou** [comment]
This should now be implemented as of Godot 3.1 (or 3.2), closing.

**Comment by neikeq** [comment]
Today, you don't have to go through any of this trouble as Godot extensions that simplify this process are available for most IDEs.
