### ISSUE TITLE
exporting to android tres resources not found

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#19333]
**Godot version:**

latest master compiled from git sources

**OS/device including version:**

linux

**Issue description:**

I have a project with tres theme resource.
Exporting to andreoid I have this error:
*ERROR**: Failed loading resource: res://themes/space/space.tres

**Steps to reproduce:**
Create a project whit theme resource, export to android

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment]
Just to add some context from IRC -- the poster also tested to save the theme as `.res`, but it also led to the error.

@GrandFunkR Just to make sure, are you using android templates for the same version as the editor (so, self-compiled template from git)?

**Comment by GrandFunkR** [comment]
> @GrandFunkR Just to make sure, are you using android templates for the same version as the editor (so, self-compiled template from git)?

Yes, tool and templates self-compiled from git.

**Comment by vnen** [comment]
BTW, the error is that it failed to load, not necessarily "didn't find". If there's other errors before that, it might explain why it failed. A small reproduction project would be nice as well.

**Comment by GrandFunkR** [comment]
note that by deleting the theme, the app opens correctly. 
As soon as possible I attach a project but in any case it is enough to create an empty project with a theme. 
The theme is present in the apk but in the assets directory and not found because in the tscn file the assets su directory is missing

**Comment by GrandFunkR** [comment]
I created a new project with my theme and to my surprise the theme was visible. 
So I tried to delete the .imports folder of my project. Reopening the project godot reimported resources but gave me an error for some broken dipendences. 
So I deleted the themes directory of my project and created it from godot, after that I copied the contents of my backup themes folder inside. 
I reopened the project and godot  created the missing files inside .import directory. 
I tried to start the project on android and everything worked. 
I do not know what happened but I think my .imports folder for some reason was not correct.

**Comment by Calinou** [comment]
Has anyone been able to reproduce this on Godot 3.2?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
