### ISSUE TITLE
_post_ready ?

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#19331]
**Issue description:**
I know its maybe a silly idea, but the current system seems not enough for me.. How about an event which called after **_ready** when all sub-child elements called their **_ready** ? - this could be useful for example for scene root if it have full control over their elements and do some post-initialization stuff on them. Or I something miss again and this possibility is easy to be implemented without new stuff ?

**Comment by Faless** [comment]
`_ready` is called in reverse order, i.e. from child to parent, so what you are looking for *is* the `_ready` function.

**Comment by Chaosus** [comment]
Ah, I still a bit struggling with engine ) Thank for explanation..
