### ISSUE TITLE
Suggestion: can  change_scene method emit a scene_changed signal in gdscript?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#19341]
**Godot version:**

3.0

**OS/device including version:**

**Issue description:**

With a signal scene_changed(from_scene, to_scene), from_scene and to_scene and is a type  of node , we can easily handle different scenes change event in a common place.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by kubecz3k** [comment]
Such signal could be added to `SceneTree` node

**Comment by vnen** [comment]
Godot does not emit signals for actions initiated by the game itself. If you need such a signal you can simply emit one when calling `change_scene()`.

> Yes, even more specific, with another scene_will_changed event before loading the new scene, we can show a simple transition(loading) scene for all scenes change in just one place and hide it on the scene_changed signal.

I don't think there's time to add a transition scene. Both because  `change_scene()` will likely block the process while it loads the other one, and because it might be problematic to mess with the tree while this is happening. I believe it's simple enough to make a system like that yourself (for instance you could change to your loading scene and have that load the next one in the background).

**Comment by alexzheng** [comment]
Since the _change_scene is called deferred in the source code, after calling  change_scene, the new scene instance is not available yet.
the scene_will_changed is emit BEFORE loading the new scene, just give the developer a chance to show a loading scene in just one common place from all scenes change event.

**Comment by vnen** [comment]
The `_change_scene()` is only called internally **after** the other scene is loaded. So if you call `change_scene()`, it'll block the main thread while it loads the new scene, so you won't have an opportunity to put in your loading scene. Even if the load was the deferred, it would block the next frame, so still no opportunity (or if there is, it would only render the first frame, if it even gets that far).

The function itself is just a convenient shortcut to: load the and instance the new scene, delete the current one, add the new instance in the tree. If you really need a loading scene, you have to load the new scene in the background, so the shortcut won't be enough.

Again: if you need custom steps it's quite easy to make your own.

**Comment by alexzheng** [comment]
OK, that's true.
Show a loading scene is not a good example for these signals, but some other situations such as saving game data, modify global navigation menus according to the current scene may be useful.

**Comment by vnen** [comment]
Yeah, but you can do any of that when you call `change_scene()`. There's no need for a signal because if you need one you can simply emit yourself at that point. If you need the new scene for something, you can load it in code and use `change_scene_to()` instead.

**Comment by alexzheng** [comment]
The parameter passed to change_scene_to is a PackedScene, not a instance of node, when call change_scene_to, it's not possible to access the instance of the new scene,

**Comment by alexzheng** [comment]
It's not possible to pass parameters to the new scene before it is added to the tree by calling change_scene.

**Comment by ninetones** [comment]
You can use call_deferred() to emit "scene_changed" for a singleton. 
The signal will be emitted after the new scene is loaded.

**Comment by KoBeWi** [comment]
> It's not possible to pass parameters to the new scene before it is added to the tree by calling change_scene.

That is the exact case #26833 was created for.

**Comment by alexzheng** [comment]
I think it's not exactly the same request.
I need a common signal for scene changed event.Then I can do something on the new scene instance.

**Comment by KoBeWi** [comment]
My comment referred to the case I quoted. If you want to do some initialization for new scene, you can do it after instancing it and then you can set it as current scene (which is possible now, but somewhat hacky). You don't need any signal for that purpose.

**Comment by codyreign** [comment]
You could use an AutoLoad script to accomplish something similar. Lets say you have a bool called SceneLoaded. When you change the scene you set the global.SceneLoaded = false and then via _process() if SceneLoaded=false:  you emit your _scene_loaded signal. 

`
#AutoLoad script with alias global
var sceneLoaded=false
signal scene_loaded

func _process(delta):
	if not sceneLoaded:
		sceneLoaded=true
		emit_signal("scene_loaded",on_scene_loaded());
		
func on_scene_loaded():
	print('SCENE WAS LOADED')
`

**Comment by KoBeWi** [comment]
This should be moved to [proposals](https://github.com/godotengine/godot-proposals).
For the case when you want to change scene to instance, see #85762
Closing.
