### ISSUE TITLE
HSeparation of CheckButton is incorrect

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#19355]
**Godot version:**
 2a9253a 

**OS/device including version:**
no matter

**Issue description:**
 I better post screenshot than say words

![image](https://user-images.githubusercontent.com/3036176/40906687-3753f19c-67ea-11e8-8d81-45b8ad48dc6b.png)

**Comment by guilhermefelipecgs** [comment]
![captura de tela de 2018-06-05 11-50-41](https://user-images.githubusercontent.com/1387165/40983774-b4747b5c-68b6-11e8-934c-c20abf5646dc.png)
I don't get it, can you provide an project?

**Comment by Chaosus** [comment]
[Bug.zip](https://github.com/godotengine/godot/files/2072868/Bug.zip)

**Comment by Chaosus** [comment]
Oh, I never tried changing Align for this kind of element... Thats will fix this issue..
