### ISSUE TITLE
[TRACKER] Particle System Enhancements

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#19358]
The particle system in Godot works fairly well (when you get to know it) but compared to Unity there are some features that could be added to make it even better. Some of these features have already been added in other issues and I will try avoid adding these again.

**Cool things to add for the Godot Particle System:**
- Sub Emitters, these can be set when the particle spawns/dies, so it spawns a new particle system.
- Stretch particles (Could be by speed or some custom fuction).
- Noise function, so each individual particle can chance size and velocity using noise.
- Add lights to Particles (set a max light count and distribution).
- A Reset Button so you don't have to wait for particles to die out when you test new settings. 

#16857 #10182 (these are regarding the Rotation issue when Particle Material is not Billboarded).
#6377 (list by mateusak of improvements, including Collision and random life time).
#3994 (Collision).
#10239 (Tracker for particle issues).

**Comment by Ranoller** [comment]
... And don't forget missing particles-attractor node please.

**Comment by jesperkondrup** [comment]
Created a more precise list of features we are missing. #20473
