### ISSUE TITLE
GDNative and GDScript not working on 3.1 custom build

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#19359]
Godot V3.1.dev.custom_build.5d1ed78
Linux Ubuntu Studio 16.04

/* Description */
I try to execute all tutorials... but no one work! In Godot when run, see the message that not found the called native method!

/* Manual fix */
After read exaustily examples I found a difference in files. Then I edited .gdn file to put missing data (see image)

![captura de tela de 2018-06-04 08-00-02](https://user-images.githubusercontent.com/85936/40914599-37c60ebe-67cf-11e8-9a2c-16cf2f479832.jpg)

**Comment by akien-mga** [comment]
> I try to execute all tutorials... but no one work!

What tutorials?

**Comment by Zireael07** [comment]
I suspect... outdated tutorials?

**Comment by BastiaanOlij** [comment]
@Zireael07 then i wonder if this isn't just a very old question?

**Comment by akien-mga** [comment]
This is an old question yeah, it was just untriaged until now. Given that much has changed for godot-cpp in the meantime, closing as likely no longer relevant.
