### ISSUE TITLE
Absurd behaviour of Windows archive extractor.

### ISSUE THREAD

**Issue by 37TS** [godotengine/godot#19352]
**Godot version:**
Godot_v3.0.3-rc3_win64.exe

**OS/device including version:**
Win10 x64 1799 

**Issue description:**
The standard archive extractor of Windows doesn't make a proper executable or doesn't extract the file at all.
WinRar does.

**Steps to reproduce:**
-Download Godot_v3.0.3-rc3_win64.zip;
-Extract with windows extractor.

Two things can happen : 
- the executable cannot run because windows defender blocks it saying "it's not signed";
- the file doesn't get extracted at all.

**Doesn't happen with WinRar. All good and fine.**

Definitely something wrong with Windows but I thought that this had to be shared with the community as somebody may encounter the same problem.

**Comment by 37TS** [comment]
@vnen I thought that it could be related to the known issue "Some users report crashes on Windows 10 after a recent Windows update. We currently don't know what is causing this."

**Comment by hpvb** [comment]
I can try some different options to the zip command. Issue is that I never saw this problem on my windows 7 and 10 test VMS.

**Comment by akien-mga** [comment]
> the executable cannot run because windows defender blocks it saying "it's not signed";

This would be solved by code signing, see #9313.

> the file doesn't get extracted at all.

That's quite weird as Godot uses plain ZIP, so the only cause I can think of is Windows Defender / an antivirus treating the Godot binary as dangerous and putting it in quarantine.
Should also be alleviated by code signing.
