### ISSUE TITLE
Request for more Dynamic Font effects in Godot 3

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#19356]
This is a request for more Dynamic Font effects in Godot 3.

Specifically:
That a gradient can be assigned as the font colour.
That any outline applied looks good (called Shadow by Godot).
That any outline applied can be either soft of hard.
That multiple outlines can be applied.
That the effects are applied to the font and not the label.

This was all available in Godot 2.

![godot2](https://user-images.githubusercontent.com/15687516/40905822-5cbf03f0-67df-11e8-8b70-6436b21d8949.png)

Resulting in this:

![godot2_result](https://user-images.githubusercontent.com/15687516/40905841-665c651a-67df-11e8-9181-db79bac0469c.png)

In Godot 3 these are your choices.

![godot3](https://user-images.githubusercontent.com/15687516/40905936-ac23744e-67df-11e8-98ea-063b3cfc80ac.png)

Resulting in this:

![godot3_result](https://user-images.githubusercontent.com/15687516/40905950-b73792fc-67df-11e8-8e09-61265ddf89b1.png)

The Dynamic Font seen from a graphics artist viewpoint is very limited right now and would benefit greatly if more options for stylization were possible.

Of course if you were to use a Bitmap Font instead, all the effects in the world are available to you, but it would forego the ease of use and convenience that the Dynamic Font offers.

**Godot version:**

3.0.2

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
The `master` branch offers high-quality DynamicFont outlines – these are configured in the DynamicFont resource, not in the Label. Old outlines have been preserved for compatibility with existing projects.

Also, note that when configuring old outlines, setting **Shadow as Outline** above 1 has no effect.

**Comment by PullTheStrings** [comment]
The new font options in Godot master branch are cool but you still can't add a gradient or have multiple outlines that you can make hard or soft.
The new outline does look great though.

![godot3_1](https://user-images.githubusercontent.com/15687516/41291516-330cc0a2-6e50-11e8-80cd-5f177352eaaa.png)




Godot version:
76875ba

**Comment by volzhs** [comment]
that one looks like https://github.com/godotengine/godot/issues/19385#issuecomment-395257849 about clipping.

**Comment by PullTheStrings** [comment]
I have made some new mockups to clarify my request.

The below image is how I imagine the Dynamic Font inspector window could look. 
It includes the ability to: 

- Add a flat colour to the font, or a gradient consisting of two colours
- Add two outlines each with their own colour 
- Add a drop shadow. The drop shadow can be offset and be either sharp or soft.

![dynamicfontinspector](https://user-images.githubusercontent.com/15687516/43266474-cbf65fe0-90eb-11e8-84f8-0b0f0039c506.png)

Using the above a Dynamic Font could look like this!

![dynamicfontexample](https://user-images.githubusercontent.com/15687516/43266513-e5b653e0-90eb-11e8-8246-c1a3e88eaf89.png)

The next mockup is of a more advanced gradient. 

- The gradient can have multiple points of colour
- Each point of colour can be positioned individually 

If it is possible to add this type of gradient to the font it would be awesome.
(The gradient to the left is from Photoshop and is for illustrative purposes only)

![dynamicfontgradientadvanced](https://user-images.githubusercontent.com/15687516/43267516-778da2da-90ee-11e8-9e5e-6ec073a7f079.png)

Using the above gradient a Dynamic Font could look like this!

![dynamicfontgradientadvancedexample](https://user-images.githubusercontent.com/15687516/43269014-412fd6dc-90f2-11e8-9b46-64630a52a95a.png)

**Comment by Gramps** [comment]
@volzhs, yeah that clipping thing on Label needs fixed, if possible.  Not sure if Label can adjust the text to account for outline or shadow but it does seem to work for Rich Label; as my issue points out.

**Comment by akien-mga** [comment]
Since we're in feature freeze for Godot 3.1, moving to the next milestone.

**Comment by arrkiin** [comment]
I ran into this problem too. But finaly I figured out a nice combination of `outline_size`, `extra_spacing_char` and a custom `CanvasItem` shader. The shader gets a custom gradient resource and works around the UV problems that are mentioned in #23210.

The important part of that workaround looks like this. 
```
uniform float height;
varying float myuv;

void vertex()
{
	if (VERTEX.y <= height / 2.0){
		myuv = 0.0;
	} else {
		myuv = 1.0;
	}
}

void fragment()
{	
	vec3 gradient_color = texture(gradient, vec2(myuv,0.0)).rgb;
        ...
}

```

The gradient can be configured in the inspector panel.

![image](https://user-images.githubusercontent.com/6756598/53335802-bb7dab00-38fc-11e9-97ed-5c801067efa5.png)

With this in mind I got the following results.

![image](https://user-images.githubusercontent.com/6756598/53335480-dbf93580-38fb-11e9-8845-6914527ef43e.png)

**Comment by TicklesTheBrain** [comment]
3.2 was removed, but 4.0 not added. is this no longer considered to be a worthwhile feature by the core team?

**Comment by Calinou** [comment]
@TicklesTheBrain No, it just means there is no milestone defined. Someone could still work on the feature, but nobody on the core team plans to do it in the near future.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
