### ISSUE TITLE
Connection_failed fails to trigger in ENET clients connecting to non-existing server

### ISSUE THREAD

**Issue by Dekker3D** [godotengine/godot#19357]
**Godot version:**
3.03 RC2 64-bit, Mono version with build tool set to MSBuild (System). Also tested briefly with Pong template on 3.02 64-bit Mono and 3.02 64-bit non-Mono

**OS/device including version:**
Windows 10 x64 Pro 10.0.17134

**Issue description:**
Each of the three multiplayer templates (Pong, Bomberman and platformer) I found in the template browser (in the startup screen where you can also open your own projects) had an issue where the connection_failed signal would not trigger when trying to connect to 127.0.0.1 with no server currently running. Other possibly-related signals, like network_peer_disconnected or server_disconnected also failed to trigger in this situation. This means that the menu gets stuck in "connecting" mode indefinitely. The same issue has occurred in my own project after copying the Bomberman network code to get started.

**Steps to reproduce:**
Download any of the above templates and try to connect with the default settings, name "The Warrior" and IP "127.0.0.1", without running any server on the port used for that template.

**Minimal reproduction project:**
The above templates.

**Comment by Dekker3D** [comment]
After experimenting a lot and leaving one of the templates running, I noticed it takes 30 seconds to time out, but it does happen. The port should be closed (no server running on it) so I expected it to fail instantly or within 5 seconds or so. Not failing instantly is still weird, but it seems there's nothing drastically wrong here.

**Comment by Faless** [comment]
> Not failing instantly is still weird, but it seems there's nothing drastically wrong here.

That is basically how `UDP` works. Being connectionless you won't get informed in any way of the port being closed. `ENet` has no way of knowing if the peer on the other side is not responding due to some issue (e.g. slow to respond, lost packets, etc) or the fact that there is actually nothing on the other end.

There is no "fix" for this, because this is just how it is supposed to work.

**Comment by Salvakiya** [comment]
This should be revisited "ENet provides a simple connection interface over which to communicate with a foreign host. The liveness of the connection is actively monitored by pinging the foreign host at frequent intervals, and also monitors the network conditions from the local host to the foreign host such as the mean round trip time and packet loss in this fashion." - http://enet.bespin.org/Features.html

**Comment by Shadowblitz16** [comment]
> > Not failing instantly is still weird, but it seems there's nothing drastically wrong here.
> 
> That is basically how `UDP` works. Being connectionless you won't get informed in any way of the port being closed. `ENet` has no way of knowing if the peer on the other side is not responding due to some issue (e.g. slow to respond, lost packets, etc) or the fact that there is actually nothing on the other end.
> 
> There is no "fix" for this, because this is just how it is supposed to work.

Wait why can't you just wait 5 seconds and if you don't get a ack packet back in that time emit connection failed?
I don't see the issue

**Comment by Faless** [comment]
> Wait why can't you just wait 5 seconds and if you don't get a ack packet back in that time emit connection failed? I don't see the issue
> 
> or better yet allow us to specify a timeout period?

Sorry, my answer was probably not clear.

As the OP mentioned, it does fail after a timeout, and in fact you can configure the ENet timeout:
```gdscript
var peer = ENetMultiplayerPeer.new()
peer.create_client("127.0.0.1", 4433)
peer.get_peer(1).set_timeout(0, 0, 3000)  # 3 seconds max timeout
multiplayer.multiplayer_peer = peer
# Will be emitted if the timeout is above 3 seconds.
multiplayer.connection_failed.connect(func(): print("Disconnected")
```

Please note that ENet timeouts works in a quite specific manner (see [the docs](https://docs.godotengine.org/en/latest/classes/class_enetpacketpeer.html#class-enetpacketpeer-method-set-timeout)).

This could also be handled at the SceneMultiplayer level but please if you feel that's the case, use the [proposal repository](https://github.com/godotengine/godot-proposals/) instead or replying in this 5 years old issue.
