### ISSUE TITLE
tiles in tileset get duplicated after making changes in the original .tscn where the tileset was exported from

### ISSUE THREAD

**Issue by kvonspiczak** [godotengine/godot#19366]
**Godot version:**
3.0.2stable mono official

**OS/device including version:**
win10 

**Issue description:**
Obsolete sprites that I can pick from and draw with in the scene, are not removed when making changes to the source tscn and convert it again as tres file. 

**Steps to reproduce:**
Create new 2d scene and add a node as root.
Add a sprite, I used a 16x16 placeholder sprite as texture. 
Save the scene and convert to tileset, save as .tres file.

Make a new scene, add tilemap node, drag the .tres file onto the tilemap. You should now only have one single sprite available to draw with. Go back in the original scene and rename the sprite to anything else.
Convert the scene and overwrite the tileset.tres file. Now go back to the tile picker. Now you should see the "old" sprite with the "old" name before you renamed it + the new one, with the new name.

**Comment by cbscribe** [comment]
This is by design. You need to set "Merge with Existing" to off when you re-converted the tileset, or it will do exactly what you're describing.

**Comment by kvonspiczak** [comment]
@cbscribe Thank you for that explanation! Next time I'll take a closer look first.
