### ISSUE TITLE
[C#] Type safe return types for PhysicsDirectSpaceState API

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19362]
**Godot version:**
`master` / 2ff31badaff

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
Currently, all methods of `PhysicsDirectSpaceState` API have generic return type like `object` or `Dictionary<object, object>` in C#, which better be changed to something more specific to prevent potential mistakes.

**Comment by akien-mga** [comment]
Is this fixed in current Godot versions? The 3.4 docs seem to indicate that return types for these methods are either `Array` or `Dictionary`, which matches the GDScript API / information from ClassDB.

**Comment by raulsntos** [comment]
This sounds like a duplicate of #19342
