### ISSUE TITLE
HTML5 template is not saving the writable partition user:// to the HTML5 storage, or anywhere else.

### ISSUE THREAD

**Issue by OvermindDL1** [godotengine/godot#1936]
HTML5 template is not saving the writable partition user:// to the HTML5 storage, or anywhere else.

See how at:
https://cs-263-emscripten.readthedocs.org/en/latest/files.html#persisting-data
http://diveintohtml5.info/storage.html
https://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html

Example at:
https://github.com/kripken/emscripten/blob/master/tests/fs/test_idbfs_sync.c

**Comment by OvermindDL1** [comment]
Also, more explained filesystem setup information at: https://hacks.mozilla.org/2014/11/porting-to-emscripten/

Integrating CloudFS for Emscripten night be useful as well, configurable option between that and the normal Emscripten filesystem perhaps.

**Comment by reduz** [comment]
this is implemented now
