### ISSUE TITLE
Sorting order of files in FileSystem browser is not auto updating

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#19360]
When adding new items to your project, in this case new materials, they will appear in the FileSystem browser in the order you create them and will not automatically sort themselves according to their name. 
They only do so after you close Godot and open it again. 

The order the materials have as I create them:

![sortingorder1](https://user-images.githubusercontent.com/15687516/40915030-d2973190-67fa-11e8-87a4-5656c35a193f.png)

After closing and opening Godot again the order is this:

![sortingorder2](https://user-images.githubusercontent.com/15687516/40915085-ff034fa2-67fa-11e8-8967-f925a23080bd.png)

 
**Godot version:**

3.0.2

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KellyThomas** [comment]
Related https://github.com/godotengine/godot/issues/17929

**Comment by groud** [comment]
This looks fixed on master, closing.
