### ISSUE TITLE
ItemList clipping does not work after visibility toggle (in nightly build)

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#19365]
**Godot version:**
Godot Engine v3.1.dev.calinou.fd1ee14
(Works in the steam stable version)

**OS/device including version:**
Linux Mint 18.3 Cinnamon 64-bit
Kernel 4.16.3-041603-generic

**Issue description:**
If i have more items than fits in a ItemList window and toggle the visibility the clipping fails.
![itemlistbug](https://user-images.githubusercontent.com/13393087/40938305-d05dd086-6841-11e8-9e84-3bdc25aabbcc.png)

**Minimal reproduction project:**

[ItemListBug.tar.gz](https://github.com/godotengine/godot/files/2069790/ItemListBug.tar.gz)

https://i.imgur.com/0H2a8IV.png

**Comment by guilhermefelipecgs** [comment]
Not a bug, you need to turn off `auto_height` property on ItemList.

**Comment by Norrox** [comment]
Thank you that was the issue :)
