### ISSUE TITLE
Godot editor causing randomly  BSOD

### ISSUE THREAD

**Issue by Garrom** [godotengine/godot#19370]
Godot randomly causing BSOD. Whole computer freezes and on first click cursor disappear. Then after roughly 30 sec BSOD shows up and restarts computer. It happens roughly 2-3 times a week.
**Godot version:**
3.0.2

**OS/device including version:**
Machine : LENOVO Lenovo B50-80
OS : Microsoft Windows 7 Ultimate (x64) Build 7601
CPU : Intel Pentium 3825U
RAM : KHX1600C9S3L/4G
GPU : Intel Broadwell-U GT1 - Integrated Graphics
AUDIO : Intel Broadwell PCH-LP - High Definition Audio Controller

I cannot tell you much. I really don't know what happened but at least i can give you dump file created by crash. It happens quite frequently lately, this one is latest(packed to zip because of allowed file formats).
[BSOD-DumpFile.zip](https://github.com/godotengine/godot/files/2069996/BSOD-DumpFile.zip)

**Comment by Zylann** [comment]
See https://github.com/godotengine/godot/issues/18871

**Comment by Garrom** [comment]
@Zylann Yeah, i know. This is different. In #18871, computer only freezes, without BSOD happening.If you look at #18871 I wrote several comments there so yeah, i know about that but this is different.

**Comment by Zireael07** [comment]
What does the BSOD say?

Also, BSOD is usually a sign of overheating and/or bad drivers...

**Comment by Garrom** [comment]
@Zireael07 I'm more into high level languages so I really cannot understand what it trying to tell me. I tried to use dump file viewer and got those informations :

_caused by driver : dxgkrnl.sys
caused by address : dxgkrnl.sys+5d388
crash address : ntoskrnl.exe+70e40
bug check code : 0x00000116
parameter 1 : fffffa80`0b549010
parameter 2 : fffff880`07645c60
parameter 3 : ffffffff`c0000001
parameter 4 : 00000000`00000003
processor : x64
processor count : 4
major version : 15
minor version : 7601_

**After all, this is what you get if you open attached dump file.**

**Comment by Zireael07** [comment]
A guy on the net had an identical problem, https://www.sevenforums.com/bsod-help-support/398580-bsod-caused-dxgkrnl-sys-5d134-2.html?s=02672bd64ce0ff7a7ed6c005438bc97f giving the computer a good clean and/or putting the RAM back fixed it.

Many graphic cards have poor OpenGL 3 support, especially integrated cards, which leads to bsod/crashing/freezing.

**Comment by Garrom** [comment]
@Zireael07 I cleared my computer with canned air from pc shop (that over-pressurized can full of strange-stinking air, you know what I mean), still happening. I used "_Geeks3D GPU caps viewer_" and find out I have support of OpenGL 4.4 with 220 extensions and OpenCL 1.2. I don't think there is problem neither.

**Comment by Garrom** [comment]
I found out it can be possibly memory problem. It happens only if GoDot editor running for long time. If I exit GoDot every hour, wait 10 minuts and start again, I avoid the problem entirely. Maybe some memory leaks ?

**Comment by Zylann** [comment]
@Garrom or overheating?

**Comment by Calinou** [comment]
> I found out it can be possibly memory problem.

If you want to check whether your RAM could be faulty or not, you could run [MemTest86](https://www.memtest86.com/download.htm#free) for an hour or two.

> Maybe some memory leaks ?

You can check RAM usage by keeping the Task Manager around (press <kbd>Ctrl+Shift+Escape</kbd> to open it).

**Comment by Garrom** [comment]
@Zylann Nah, when overheating happens, thanks to my settings, laptop forcefully enter hibernation mode so it can cool down in peace and I don't lost any work or downloads. Anyway it didn't happen for some time because I purchased cooling pad under my laptop.
@Calinou My Ram chip is just fine. It was purchased recently to replace terribly slow Ram what came with laptop. Use process manager to monitor ram usage is good idea. I'll let it run and report back.

**Comment by Zylann** [comment]
> Can godot possibly overflow RAM by undos ? 

Interesting point. I should check that with my terrain plugin, where I put any modified pixels in it :p

**Comment by Garrom** [comment]
Apparently it is another Windows stuff. I'm using Ubuntu 18.04 for some time already and it didn't happen yet. Stop using Windows and start using Linux seems to be workaround.

**Comment by reduz** [comment]
This is a driver bug, as Godot can in no way crash Windows or cause a BSOD. 
This can't be properly close, but I suggest someone should keep track of troublesome driver versions for Godot, as we have a few reports from that.

**Comment by akien-mga** [comment]
Closing, as there's nothing we can do on our side to fix buggy drivers. As mentioned above, Godot can't cause a BSOD, so the fault lies in an implementation bug of the drivers. If it's not fixed in the latest drivers versions available, you should raise the bug with your drivers vendor.
