### ISSUE TITLE
Add "GDScript: " in front of tooltips

### ISSUE THREAD

**Issue by CloudAlRio** [godotengine/godot#19379]
In brief, my proposal is as follows: add "GDScript: " in front of tooltips. I think it would make it more easy to figure out what those tooltips mean. Ex: "GDScript: 'size/always_on_top'" or without quotes

**Comment by akien-mga** [comment]
But those are not GDScript, they're the internal name of the property, which you can use from any scripting language (not only GDScript but also VisualScript, C#, C++, Python, Nim, D, etc.).
