### ISSUE TITLE
Error in File class documentation

### ISSUE THREAD

**Issue by frankiezafe** [godotengine/godot#19383]
**Godot version:**
v3.1.dev.custom_build.92f1deb

**OS/device including version:**
Linux Mint 18.3 - 4.8.0-53-generic 

**Issue description:**
Error in the documentation

**Steps to reproduce:**
The code snippets in the File class documentation online and in the engine are not correct for copy/paste (the first ting i did)

The lines:

 file.open("user://save_game.dat", **file**.WRITE)
 file.open("user://save_game.dat", **file**.READ)

should be:

 file.open("user://save_game.dat", **File**.WRITE)
 file.open("user://save_game.dat", **File**.READ)

Url of the page: http://docs.godotengine.org/en/3.0/classes/class_file.html?highlight=File, chapter description.

Really simple to fix, too much for a pull request :) - keep on, I love this engine! 

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Thanks for the report, it's now fixed.

@hpvb You can cherry-pick 8569a0db for 3.0.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
