### ISSUE TITLE
Label's Clip Content always on.

### ISSUE THREAD

**Issue by Gramps** [godotengine/godot#19385]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10 / Ubuntu LTS 18.04

**Issue description:**
A Label's Clip Content seems to always be on.  Seems to be a bug.  Clip Content does work fine on Rich Text Label.

Worth noting that any text with outlining (generally ported from Godot 2.1.4 fonts) is clipped.

**Steps to reproduce:**
Basically any label has it on even when checked off.

**Comment by volzhs** [comment]
@Gramps did you use bitmap font?

**Comment by Gramps** [comment]
In 2.1.4, I think so.  I used the editor's Import Font option since there is no good way to make font outlines in 3.0.2 yet.

**Comment by volzhs** [comment]
I'm not sure clip content is always on is true.
![screenshot_20180607_041348](https://user-images.githubusercontent.com/8281454/41060021-4266dd44-6a09-11e8-9ee1-259755e6c7b1.png)
if clip content property is alway on for `Label`, then the icon should not be displayed.
(left one is on editor, right one is on running game)
I think, there is something another.
would you demonstrate your problem with image(screenshot)?

**Comment by Gramps** [comment]
You are actually correct, to a degree.  It turns out that auto-wrap is the culprit.  If auto-wrap is off, then the outline is fine; but if it's on, then anything outside the border gets clipped for some reason.  This, however, is not the case for Rich Text Label.  The image below shows this in action.

![test](https://user-images.githubusercontent.com/1097098/41072231-324dac18-69c2-11e8-814b-bef4f41d67e8.jpg)

You can see the second label has the outline clipped off with auto-wrap on, unlike the first.  Rich Text Label doesn't even have an auto-wrap toggle but works regardless.

I added the test project as requested which includes the font file I'm using from Godot 2.1.4.

[Godot 3.zip](https://github.com/godotengine/godot/files/2078576/Godot.3.zip)

**Comment by reduz** [comment]
This is not a bug, if autowrap exists, stuff that is outside the label will be removed. This is the expected behavior.

**Comment by Gramps** [comment]
It was more that the shadows or outlines should be inside the area wrapped instead of cut off like they are in the image I added; much like how Rich Text Label does so there is consistency in the two.

Though I do think there does need to be more dynamic font effects as there is no way to outline text (easily) in Godot 3 like there was in 2 so I am constantly importing font files from that.
