### ISSUE TITLE
Cannot open a project with stable version after saving it with nightly

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#19380]
**Godot version:**
3.0.2 stable and nightly

**Issue description:**
A project thats saved with the nigtly cannot be open in 3.0.2 stable
i post the error msg i get below

![error](https://user-images.githubusercontent.com/13393087/40972868-69159f68-68c2-11e8-9767-551fa216c8ed.PNG)

**Comment by akien-mga** [comment]
That's on purpose and thus not a bug. But as discussed recently with @groud, we should likely improve the error reporting and show some warnings when you try to open a 3.0.x project in 3.1, so that you know that you'll make it incompatible with 3.0.x.

**Comment by Norrox** [comment]
Ah okey, thanks for clearing that up :+1:

**Comment by KellyThomas** [comment]
@Norrox From a practical perspective you could try following these pointers to roll back your project file
https://www.reddit.com/r/godot/comments/8o1d3u/dev_snapshot_godot_303_rc_3/dzzwz2u/

**Comment by Norrox** [comment]
@KellyThomas i already got it to work,
I changed the "config_version = 4" to 3 in the file project.godot and it worked for me :-)

**Comment by akien-mga** [comment]
This is actually the same issue as #18758.
