### ISSUE TITLE
No ../ when entering the folder without permissions to read

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1938]
After entering some folder with no permissions to read using Open File popup, there is no way to get back. The ../ folder does not appear in files tree. The only way is to enter the directory manualy then.
Using Windows 7

**Comment by akien-mga** [comment]
I think it's normal not to have "../" when in a folder without read permission, but what's wrong is to be able to enter a folder for which one does not have read permission, so that's a bug at any rate :)
