### ISSUE TITLE
Feature Request: Depth only geometry / Depth Mask

### ISSUE THREAD

**Issue by SpechtMagnus** [godotengine/godot#19395]
**Godot version:**
3.x

**OS Version**
all

**Feature description:**
For at least one specific problem (described [here](https://godotengine.org/qa/28462/how-to-hide-the-water-plane-inside-a-boat) it would be extremely usefull for Godot to have the ability to render geometry that only writes the depth-buffer and masks some specified other geometry. The most efficient way would probably be some kind of shader allowing this.

**Long feature description**
My specific use case is that I want to draw a boat that has an interior below sea level. The interior should be visible from the outside and not have any water in it. Unity handles this by drawing a plane on the upper border of the boat that only writes the depth buffer and is drawn after the boat and before the water. So when the water plane is drawn the boat looks like a closed object in the depth buffer. I think this technique is called "_depth masking_". For more details check the following links:

- [Godot Q&A](https://godotengine.org/qa/28462/how-to-hide-the-water-plane-inside-a-boat)
- [Unity Wiki - Depth Mask](http://wiki.unity3d.com/index.php?title=DepthMask)

Transparent geometry wont allow this as it's (to my understanding) not drawn with the other geometery.

**Possible uses**
- Draw boats with interiors below sea level
- Draw cave entrences into terrain
- Draw windows onto walls

Obviously this feature requires custom sorting of the render queue. But to my understanding that was added in 3.0 ( #10135 ).

I hope this feature description is clear enough.

**Comment by Zylann** [comment]
Duplicate of https://github.com/godotengine/godot/issues/18901 ?

**Comment by SpechtMagnus** [comment]
Seems like it. well I didn't dor my research good enough then.
