### ISSUE TITLE
Godot V3.0.3 RC3 C# (_Ready not being called?) editor link to script is wrong

### ISSUE THREAD

**Issue by imekon** [godotengine/godot#19403]
**Godot version:**

Godot V3.0.3 RC3 Mono 64bit

**OS/device including version:**

Windows 10

**Issue description:**

I created an empty projected, added a scene with a Node2D and added a C# script to it. I added

    GD.Print("ready");

to the _Ready function.

When it runs the "ready" message does not appear. I then added a second scene and the following code:

    public class Main : Node2D
    {
	private PackedScene red;
	
        public override void _Ready()
        {
		GD.Print("ready");
		
		red = (PackedScene)ResourceLoader.Load("res://scenes/red.tscn");
		var random = new Random();
		for(int i = 0; i < 10; i++)
		{
			var blob = (Sprite)red.Instance();
			int x = random.Next(100, 400);
			int y = random.Next(100, 300);
			blob.Position = new Vector2(x, y);
			AddChild(blob);
		}
          }
      }

When run, the red blobs don't appear either. It looks as though _Ready is not being called. Tried setting a breakpoint but that doesn't work either.

**Steps to reproduce:**
 * Create an empty project with one scene based on Node2D.
 * Add a C# script to scene
 * Add GD.Print("ready") to _Ready function
 * Run project

"ready" does not appear

**Minimal reproduction project:**

[test3.zip](https://github.com/godotengine/godot/files/2079082/test3.zip)

**Comment by imekon** [comment]
I tried something similar with GDscript:

extends Node2D

onready var red = load("res://scenes/Red.tscn")

    func _ready():
	print("ready")
	
	for i in range(0, 10):
		var blob = red.instance()
		var x = randi() % 300 + 100
		var y = randi() % 200 + 100
		blob.position = Vector2(x, y)
		add_child(blob)

works fine

**Comment by natrim** [comment]
Seems to me like you forgot to attach the Main.cs to the Main node (Node2D)

**Comment by imekon** [comment]
I created the C# file by adding a script to the main node (Node2D)

**Comment by neikeq** [comment]
In the demo project you uploaded, I don't see the script attached to anything in the scenes, neither Main.tscn nor Red.tscn.

**Comment by imekon** [comment]
That's weird... as I said, I created the script through the script button on the main scene. I'll see tonight, if plugging in the script fixes the problem. That does beg the question: how come creating the script by pressing thr script button didn't assign it to the scene as it does with GDscript?

**Comment by neikeq** [comment]
> That does beg the question: how come creating the script by pressing thr script button didn't assign it to the scene as it does with GDscript?

No idea, that never happened to me. If it ever happens again, check if there is any error in the console.

**Comment by imekon** [comment]
I tried a new project. Same result, GD.Print("ready") doesn't work.

I can see in the editor, Main.tscn is (apparently) linked to main.cs

So I saved it all and shutdown Godot.
Then I restarted and reloaded.

Main.tscn is now pointing at null for the script. So there is a bug - it's done this for me on two separate systems. When you create the script, the editor shows a link to Main.cs which isn't actually there. You have to restart to see the link is gone and reattach, then it works.

Now I'm seeing "ready" printed in the output window. This is consistant for me, i.e. repeatable.

**Comment by Zireael07** [comment]
Does it only happen on the Mono version?

**Comment by akien-mga** [comment]
CC @hpvb.

I'll see if I can reproduce it on Linux (after updating my local Mono install to 5.12...).

**Comment by imekon** [comment]
Doesn't happen on 3.0.2 Mono but does (for me on two systems) on 3.0.3. RC3 Mono. Only for C# scripts. Didn't happen when I tried GDScript.

**Comment by akien-mga** [comment]
Can't reproduce it on Mageia 6 x86_64 (Linux) with 3.0.3 RC3 and Mono 5.12.0.226 (self-compiled).

Steps used to try to reproduce:
- Created a new empty project
- Added a "Node" named Node
- Attached a C# script named MainNode.cs, with `_Ready()` function calling `GD.Print("ready");`
- Saved scene and ran, the print worked

**Comment by imekon** [comment]
I used a Node2D but can't imagine why that would make much difference

**Comment by neikeq** [comment]
Perhaps this is a recent Windows-only bug. I will try to reproduce it tonight.

**Comment by hpvb** [comment]
I can't reproduce this on Windows either. Does the original reporter have Mono 5.12.0 installed?

**Comment by imekon** [comment]
Yes

**Comment by hpvb** [comment]
I've seen this on windows 7 is the .net SDK is not installed. Can you try that?

**Comment by imekon** [comment]
I've got Windows 10 with the .NET SDK installed on both machines.

**Comment by exts** [comment]
I can't reproduce on 3.0.5. The `test3.zip` file that you had above didn't have the script attached to the node. I reattached it and it works as intended. Maybe you didn't realize the script wasn't attached.

**Comment by bojidar-bg** [comment]
Seems it only happens on 3.0.3, can the OP try on 3.0.5 (or later)?

**Comment by imekon** [comment]
I tried 3.0.5, it was working. Previously I'd always have to assign the script again.
