### ISSUE TITLE
Sign function should always return an int

### ISSUE THREAD

**Issue by heroofhyla** [godotengine/godot#19405]
**Godot version:**
3.0.2.stable.official

**OS/device including version:**
Windows 10 Professional 64 Bit

**Issue description:**
When calling the `sign()` function on a float, the result is returned as a float. This leads to some headaches when debugging, because the result *looks* like an int when printing the value. It would make more sense for it to be returned as an int.

**Steps to reproduce:**

Execute the following script on any node:

```
extends Node2D
var messages = {
	-1: "This is negative",
	0: "This is zero",
	1: "This is positive"
}

func _ready():
	print("Sign of 23: " + str(sign(23)))
	print(messages[sign(23)])
	print("Sign of 23.5: " + str(sign(23.5)))
	print(messages[sign(23.5)])
```

You'll notice that the script crashes with the following error:

```
`Invalid get index '1' (on base: 'Dictionary')`
```

Go back to the "Output" tab and check the output from the script:

```
Sign of 23: 1
This is positive
Sign of 23.5: 1
```

The return value of `sign()` *looks* exactly the same in both cases. But since the second one is secretly returning a float instead of an int, anything that expects an int (in this case a dictionary lookup) fails.

You can obviously get around this by manually converting the return value to an int, but it's very confusing to try and deal with this error when you don't even know that `sign(float)` returns a float. It would be more intuitive for it to return an int. At the very least, some sort of indication of the type of the variable would be useful.

**Minimal reproduction project:**

[Sign Issue.zip](https://github.com/godotengine/godot/files/2079270/Sign.Issue.zip)

**Comment by Zylann** [comment]
While it makes sense to have an int if you use `if` or `match`, we also need to keep in mind situations where `sign` is also used in legit float formulas, though it should probably work anyways.

**Comment by bojidar-bg** [comment]
The only question would be what should `sign` return for `-0`. Currently `sign(-0.0)` returns `-0.0`, not `0.0`.

**Comment by Zylann** [comment]
Also, I realize it could also fall into the same ballpark as requests for integer versions of `clamp`, `min`, `max` etc

**Comment by neikeq** [comment]
I wonder if there is interest in support for function overloading.

**Comment by heroofhyla** [comment]
@bojidar-bg Interesting, I hadn't considered negative zero (floats are weird). I did some research into this, and it seems that the current behavior is the same as Java's `java.lang.Math.signum()`. Maybe it should be left as-is for parity.

I guess I'm just left complaining that it was a pain to figure out what was going on when I was running into these issues last night.

**Comment by lukostello** [comment]
why not make a signf() signi() you did it with wrap and rand lets do it again.

**Comment by Zylann** [comment]
@neikeq that would be a good point, because currently to support this we can only make it take and return `Variant`, like what happened with `lerp`. The problem with that, is that it clashes with static typing, so if you want to type vars you often have to cast manually the result again, which would probably not happen with function overloading?

**Comment by Wolfe2x7** [comment]
Good, I managed to track this issue down...I have an extra wrinkle to add. (Version 3.2.3 stable, both Linux Mint 20.1 and Windows 10)

I am using integers to identify types of parts on a car, and in this case I have three code branches based on three possibilities for the identifier -- from zero to two, three, and anything above three.

This portion of code always worked totally fine in the editor and debug exports, but when I exported a release version for the first time, my drivetrain simulation was disabled and cars could not move. Fortunately, it didn't take long to figure out what happened.

Godot rejects this first example in the editor, saying, "The pattern type (int) isn't compatible with the type of value to match (float)":

~~~~
# match sign(identifier - 3):
#    -1:
#        print("identifier is zero, one, or two")
#    0:
#        print("identifier is three")
#    1:
#        print("identifier is anything greater than three")
~~~~

I found that strange for a function that returns -1, 0, or 1 (and a language that is typically nowhere near being that picky about variables), but I unwittingly obliged.

This works in debug, but is quietly broken in release. There is no match with what the editor requested:

~~~~
match sign(identifier - 3):
    -1.0: (ditto above)
    0.0:
    1.0:
~~~~

This works in both debug and release:

~~~~
match int(sign(identifier - 3)):
    -1: (you get the idea)
    0:
    1:
~~~~

I decided to just do this instead:

~~~~
if identifier < 4:
    match integer:
        3:
            print('identifier is three')
        _:
            print('identifier is zero, one, or two')
else:
    print('identifier is greater than three')
~~~~

In any case, I can report that this issue can cause an unexpected snag when finally exporting a project as a release. It could be a huge headache for projects larger than mine if they happen to use that kind of erroneous match more frequently.

**Comment by Anutrix** [comment]
What's the status of this on master?

In current latest 4.0 master 78f86ff51, `sign`, `signf` and `signi` all return int values(i.e, -1, 0, 1). Is this intentional?
```
sign(-6.5) # Returns -1
sign(0.0)  # Returns 0
sign(6.5)  # Returns 1

signi(-6.5) # Returns -1
signi(0.0)  # Returns 0
signi(6.5)  # Returns 1

signf(-6.5) # Returns -1
signf(0.0)  # Returns 0
signf(6.5)  # Returns 1
```

**Comment by akien-mga** [comment]
I think you assumed the types based on what is `print`ed, and not the actual types. `print(5.0)` prints `5`, that's normal.

The documentation states that `signf` does return `float`, and a quick test with `typeof` seems to confirm:

```gdscript
	assert(typeof(signi(-42)) == TYPE_INT)
	assert(typeof(signf(-42.0)) == TYPE_FLOAT)
	assert(typeof(sign(Vector2i(-3, 5))) == TYPE_VECTOR2I)
```

So this is indeed fixed.
