### ISSUE TITLE
Align naming of Viewport Clear Mode and Update Mode Enums

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#19404]
The enums for CLEARMODE and UPDATEMODE should be renamed to match each other. In particular CLEAR_MODE_ONLY_NEXT_FRAME should be renamed to CLEAR_MODE_ONCE.

Right now the options for Clear Mode are: 
CLEAR_MODE_ALWAYS
CLEAR_MODE_NEVER
CLEAR_MODE_ONLY_NEXT_FRAME

While the options for Update Mode are:

UPDATE_DISABLED
UPDATE_ONCE
UPDATE_WHEN_VISIBLE
UPDATE_ALWAYS

CLEAR_MODE_ONLY_NEXT_FRAME means the exact same thing as UPDATE_ONCE. Therefore they should have the same naming. It is more intuitive to have CLEAR_MODE_ONLY_NEXT_FRAME named CLEAR_MODE_ONCE as it reflects more accurately what is happening, namely the Viewport is cleared once and then set to CLEAR_MODE_NEVER.

**Comment by akien-mga** [comment]
That would be nice, but since it will break compatibility it will not happen until the next planned compatibility breakage. I've added it to the #16863 tracker, in the meantime closing this issue as it won't be done in the near future.
