### ISSUE TITLE
Renaming/Moving Files Should Also Update AutoLoad Tab

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#19401]
I think that when you rename or move a file, the autoloaded node paths should be updated as well. Currently when you rename or move autoloaded scenes and scripts, you have to re-add them in the AutoLoad tab.

**Comment by KoBeWi** [comment]
Ah, I was annoyed each time I wanted to change Autoload path and found out that I have to remove it and re-add. I wanted to suggest adding patch changing, but then realized I need it only when moving file, so fixing this issue would work for me too.

**Comment by akien-mga** [comment]
Duplicate of #22995, fixed by #23000.
