### ISSUE TITLE
mouse_entered never fires when root/parent node does not inherit Node2D

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#19411]
**Godot version:**

3.0.2, 3.0.3 RC3

**OS/device including version:**

Arch Linux

**Issue description:**

mouse_entered does not fire on area2d if parent/root node does not inherit CanvasItem

**Steps to reproduce:**
Create scene, root node is Node or WorldEnvironment, or any other node that is not CanvasItem
Create a new scene, root node is area2d, children of Sprite + CollisionShape2D, attach script listening on mouse_entered (and optionally mouse_exited)
Add scene as child of root node
Run in main scene, events never fire
Change root of main scene to Node2D/Control, events will now fire

**Minimal reproduction project:**

[buggy.zip](https://github.com/godotengine/godot/files/2080732/buggy.zip)

**Comment by swarnimarun** [comment]
Close it now, not an issue really.

**Comment by Silvea12** [comment]
Issue was control node above node2d, control was consuming mouse events, preventing them reaching the Area2D. My mistake. Closing.
