### ISSUE TITLE
AnimationPlayer Setting the time of a key manually and moving the key messes the time

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#19418]
**Godot version:**

Godot master efdd0c4

**OS/device including version:**

Windows 10

**Issue description:**

Setting the time of a key manually and moving the key messes the time:
![https://i.imgur.com/dJlHYo6.gifv](https://i.imgur.com/dJlHYo6.gif)

**Comment by mrcdk** [comment]
Thinking about it, this may be the same issue as https://github.com/godotengine/godot/issues/19416 but I can't test it right now.

**Comment by DualMatrix** [comment]
Could not reproduce in current master 5614692

**Comment by akien-mga** [comment]
Thanks, closing as fixed.

Feel free to comment if you can still reproduce it somehow.
