### ISSUE TITLE
AnimationPlayer key time can go to negative values

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#19416]
**Godot version:**

Godot master https://github.com/godotengine/godot/commit/efdd0c4b894a4329469e3c8456b0440e7398c5d8

**OS/device including version:**

Windows 10

**Issue description:**

Keys can be moved to negative values and some stuff breaks like:
- The timeline isn't updated until something else changes so you lose the key until then.
- Trying to move the play line is offset by the negative values:
![https://i.imgur.com/2irClw3.gifv](https://i.imgur.com/2irClw3.gif)

**Comment by reduz** [comment]
I think this is fixed now, can you test?

**Comment by DualMatrix** [comment]
Keys can still be moved to negative values. But the play line seems to behave normally.

**Comment by reduz** [comment]
I don't see any problem with dragging keyframes to negative values. This is intended.
The origina issue is fixed, so closing this.
