### ISSUE TITLE
AnimationPlayer can't add a script's function key

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#19417]
**Godot version:**

Godot master efdd0c4

**OS/device including version:**

Windows 10

**Issue description:**

Trying to add a function key that's declared inside the script doesn't work:
![https://i.imgur.com/vV73c9x.gifv](https://i.imgur.com/vV73c9x.gif)

**Comment by AndreaCatania** [comment]
I can confirm it and I think it's just a bug on the check because if you add another method and change its name and its arguments it works correctly

**Comment by akien-mga** [comment]
According to @reduz this is fixed in the current master branch: https://github.com/godotengine/godot/pull/19474#issuecomment-412178402
