### ISSUE TITLE
AnimationPlayer Changing the track name size doesn't update the contents correctly

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#19419]
**Godot version:**

Godot master efdd0c4

**OS/device including version:**

Windows 10

**Issue description:**

![https://i.imgur.com/qnbUujr.gifv](https://i.imgur.com/qnbUujr.gif)

**Comment by DualMatrix** [comment]
Tested in 8704b77, what's shown in that gif doesn't seem to happen anymore.

**Comment by akien-mga** [comment]
Closing as fixed then.
