### ISSUE TITLE
Boot Splash - Pixel Art Scaling is Blurry - need option to turn Texture Filter Off

### ISSUE THREAD

**Issue by naturally-intelligent** [godotengine/godot#19415]
**Godot version:**
3.0.2

**OS/device including version:**
Ubuntu MATE 18.04

**Issue description:**
Boot splash screen scales up low-res pixel art to be blurry.  It appears to be from applying the Filter flag to the texture, but there also seems no way to change this.  Changing the texture flags from the Import panel also has no effect.  Perhaps the solution would be to honor those texture flags set on that texture on the Import panel.  Otherwise, have more options in Project Settings -> Boot Splash.

**Steps to reproduce:**
Use low-res boot splash PNG, such as 320x180.  Easiest to see with Fullscreen On, Stretch Mode = viewport, Stretch Aspect = keep.

**Minimal reproduction project:**
Seems unnecessary.

**Comment by naturally-intelligent** [comment]
I do have a temporary workaround for this problem: use an upscaled image of the low-res image.  This won't work for every resolution but for example a 1920x1080 image will offer better results for most devices I imagine.

**Comment by akien-mga** [comment]
You can disable `application/boot_splash/fullsize` to prevent scaling and show it in the original size, but there is indeed no option to scale with filtering disabled.

#22488 aims at solving this issue.
