### ISSUE TITLE
AnimationPlayer curve editor tangents color should be different

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19432]
Godot master efdd0c4b894a4329469e3c8456b0440e7398c5d8

I was a bit confused about what was a tangent and what was the actual curve, they have the same color. I think tangents should have a slightly more transparent color.
I also expected the tangents to look smaller, the first time I created such a track the tangents were actually so much bigger than the curve itself.

![image](https://user-images.githubusercontent.com/1311555/41125663-645c4bb8-6aa5-11e8-95ff-6e8553172032.png)

Compared to the `Curve` resource editor:

![image](https://user-images.githubusercontent.com/1311555/41125777-b8883c6a-6aa5-11e8-9918-a8d595b1136f.png)

**Comment by mateusfccp** [comment]
Is this enough? 
![captura de tela de 2018-12-18 13-49-26](https://user-images.githubusercontent.com/4605213/50165329-dfed5380-02cb-11e9-9932-e26c7080d9c6.png)

**Comment by Zylann** [comment]
That looks better, yes :)
