### ISSUE TITLE
Cull mask in DirectionalLight appears to have no effect

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#19438]
**Godot version:**
3.x trunk

**OS/device including version:**
ubuntu 18.04, nvidia

**Issue description:**
I have two meshes, one in VisualInstance layer 1 and the other in layer 2. I'd like the DirectionalLight to only affect one mesh but toggling the Cull Mask layers in the inspector has no effect on the scene at all (even toggling off all cull mask layers the scene is still illuminated). 

Switching the DirectionalLight to invisible hides the light source from the scene.

**Comment by Wolfcrux** [comment]
I also have this problem. 

Godot 3.0.6 Stable

**Comment by lordkettune** [comment]
I’m still having this issue as well in 3.1 alpha 3 — the cull mask on directional lights doesn’t seem to do anything whatsoever :L

**Comment by NathanWarden** [comment]
Just ran into this same issue right now. If it matters... alpha 3, Ubuntu 18.04

**Comment by reduz** [comment]
Implementing this in current GLES3 renderer is pretty much impossible. I will work on it on the Vulkan port.

**Comment by finkizo** [comment]
Seems it also affects the GLES2 renderer.

**Comment by phaitonican** [comment]
same problem with GLES 2

**Comment by danilw** [comment]
as I understand "Cull Mask" for lights still not implemented, in 3.2 Godot stable...

**Comment by Calinou** [comment]
@danilw This is indeed the case. It will only be implemented starting in Godot 4.0.

**Comment by Norrox** [comment]
alright, that's why it won't work for me

**Comment by Calinou** [comment]
Should we hide the Cull Mask property from Light in the `3.2` branch? I couldn't get it to work with OmniLight and SpotLight either, not sure if I did something wrong on my end.

**Comment by Calinou** [comment]
In the `3.2` branch, we should find a way to hide the Cull Mask property in DirectionalLight (but not other light types), and in all light types when using the GLES2 renderer.

**Comment by ConnorDY** [comment]
This still appears to be an issue. Is this still being tracked?

**Comment by Calinou** [comment]
@ConnorDY We can't implement this feature in the `3.2` branch, but it's now implemented in the `master` branch with the Vulkan renderer.

All we can do now is hide the Cull Mask property in DirectionalLight in Godot 3.2 (and print a warning when attempting to change its value).

**Comment by akien-mga** [comment]
Fixed by #46694.
