### ISSUE TITLE
AnimationPlayer scrollbar doesn't update if an audio clip is dragged out of view

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19433]
Godot master efdd0c4b894a4329469e3c8456b0440e7398c5d8

If you drag an audio clip to the left beyond the beginning of the animation, the scrollbar doesn't update and you can't scroll to look at the clip. So if you drag the clip out of view to the left, you can't get it back. The only way is to zoom out to make the scrollbar appear.
This also reproduces when dragged on the right.

![image](https://user-images.githubusercontent.com/1311555/41126840-2db07a36-6aa9-11e8-8f72-8019ef826074.png)

**Comment by mrcdk** [comment]
This happens with all keys https://github.com/godotengine/godot/issues/19416 Basically setting the time of a key to negative values messes the editor
