### ISSUE TITLE
Cursor doesn't switch to "resize" when hovering editor dock splitters

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19431]
Godot master efdd0c4b894a4329469e3c8456b0440e7398c5d8

When I move my mouse over these splitters, it doesn't change to a "resize" cursor until I actually click and drag them:

![image](https://user-images.githubusercontent.com/1311555/41125415-b214f8ba-6aa4-11e8-8586-a99fb0e0c206.png)

**Comment by vnen** [comment]
Isn't this what #19426 fixed?

**Comment by Zylann** [comment]
Looks like it is, yes
