### ISSUE TITLE
Autosaving scripts not working

### ISSUE THREAD

**Issue by Clean3d** [godotengine/godot#19449]
**Godot version:**
Issue exists on latest git pull (as of writing): 6f328420c3f62726c2264d5d3725a48d57f218e1

**OS/device including version:**
Ubuntu 17.10

**Issue description:**
After editing a script with the Godot editor and playing the scene (with either F6 or F5), the script changes are not used. The included project file uses a built-in script, but I've also tested this with an external .gd script.

The script works after saving the scene manually. Nodes added between manual saves are present in the auto-saved scene, so I think this issue is specific to scripts.

**Steps to reproduce:**
* Run the sample project and note the "Hello, world!" print output.
* Comment out the print line in the Node2D script
* Without manually saving, press F6 and note output.
* Manually save the project and play the scene again.

**Minimal reproduction project:**
[issue.zip](https://github.com/godotengine/godot/files/2085061/issue.zip)

**Comment by bojidar-bg** [comment]
This is not exactly related, since this issue is about autosaving of builtin scripts (#4987), while the other is about scenes failing to save dependencies in certain cases.

Going to retitle this a bit better..

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by akien-mga** [comment]
No answer, so I'll close. Please comment if you can still reproduce it.
