### ISSUE TITLE
Custom fonts hardly work

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#19442]
version:
3.0-stable-2011-g11895566d

I just been trying to get custom fonts working so I can do some small text. But it really doesn't like to work. The text just isn't visible. See attached scene for example.

[font_test.zip](https://github.com/godotengine/godot/files/2084157/font_test.zip)

**Comment by aron3097** [comment]
I just give it a try.

1. I see the custom font / setting / size is 0;  changed to 12, text display on editor.

2. clear the custom font. recreate new dyn font data. load the DroidSansFall**ttf. set the font size to 12. label text appear. both editor and running.

ps.  the dynamticalfont size is in the custom font/setting  not the label property.

**Comment by supagu** [comment]
@aron3097, step #1 did show in the editor but not in the game, but step #2 worked in both the editor and the game.

but there is still an issue, try a font size of say 5 or 3 - the font size ingame does not change. The editor seems to shrink it ok.

**Comment by aron3097** [comment]
emm. I reproduce it. as u mention. same.
maybe the same change is the cause of the problem. with recent GE git version, changing the word_env background will not affect running, only editor.

**Comment by Calinou** [comment]
This seems to be related to the `DroidSansFallback.ttf` font file, as it works correctly with other fonts in https://github.com/godotengine/godot/commit/17d92c2b0995e82f5291c5a1e097e7b607151d31 (I tried [Inter Bold](https://rsms.me/inter/) in the same project).

**Comment by Calinou** [comment]
@supagu @jhch3 Can you reproduce this with 3.1 stable or a [daily build](https://hugo.pro/projects/godot-builds/) of the `master` branch? Also try with different fonts.

The default DynamicFont size is now set to 16, which should fix the issue of its size being 0 by default.

**Comment by jhch3** [comment]
latest `master` branch custom build
default size is 16 now. 
1 add font and attach dynamic font do not make label visible. throw error DynamicFont uninitialized.
2 click play, the label display text in running, editor still void.
3  check "use Mipmaps", the custom font label finally display text in editor.

**Comment by KoBeWi** [comment]
Seems to work without problems in 3.2
The DynamicFont in repro is loaded from wrong path. After assigning the font data again everything is fine.
