### ISSUE TITLE
AnimationPlayer - New bezier keys don't use current value for some variant types

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#19448]
**Godot version:**
Current master

**Issue description:**
When you add a new bezier key for a float value, it will insert the key with the current value of that float property.
However, if you add a new bezier key for a Vector2, Vector3, or I guess anything that uses a '.' at the end of the property path (i.e position.x) then the value of the key always ends up being 0

I looked into the code and it looks like it's unable to resolve the property path of properties with '.x' etc on the end, so it ends up being NIL and thus 0

**Steps to reproduce:**
Add Sprite to scene, set its position to something other than 0,0
Add Animation player
Add Bezier track for sprite's position
Add new key for x
Notice how the key value is 0, even though the sprites X position is not 0

**Minimal reproduction project:**

**Comment by reduz** [comment]
@bojidar-bg I think this maaay be yours
