### ISSUE TITLE
Wrong minimum size of Control node

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#19441]
**Godot version:**

3.1.dev f35115309

**OS/device including version:**

not related

**Issue description:**

Wrong minimum size of Control node.

**Steps to reproduce:**
![master](https://user-images.githubusercontent.com/8281454/41150067-1a4788aa-6b48-11e8-98ff-a11edf3fbcb8.gif)

comparing to 3.0.2 official
![3 0 2](https://user-images.githubusercontent.com/8281454/41150109-31dc810a-6b48-11e8-89be-af26d6a4897b.gif)

**Minimal reproduction project:**

**Comment by volzhs** [comment]
@groud do you have a clue?

**Comment by groud** [comment]
No, I'll have a look. I think last time I checked it worked fine

**Comment by guilhermefelipecgs** [comment]
Already fixed #19334

**Comment by volzhs** [comment]
I feel #19334 needs to be merged immediately if there is not any other concern about it.

**Comment by guilhermefelipecgs** [comment]
I agree.
