### ISSUE TITLE
OptionButton dropdown popup doesn't scale

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#19451]
**Godot version:**

v3.1.dev.custom_build.6f32842

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**
- Create OptionButton node
- Change scale in Rect->Scale e.g. x=2, y=2
- Play Scene
- Press button and dropdown don't scale

**Minimal reproduction project:**

![image](https://i.imgur.com/RyGQMR7.png)

**Comment by clarkejm** [comment]
I see the same problem in 3.0.5
