### ISSUE TITLE
Templates exports RC3 1.1 for Windows 32 release and debug completely broken! and HTML to.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#1945]
I checked on the windows 32 new templates to export RC3, 1.1. and the case is even worse than RC2 1.1 in this issue # 1868. there after export check "debug" work, but if you turn off and collect the EXE file after falling immediately after the logo.
BUT! In the new version, even EXE compiled in debug mode, after starting, just an empty gray window, and if a check mark off, shows the logo and immediately crashed again, well as for all HTML totally broken, and now he does not even create any files other than the date. pac, and again asserts that there are no templates out there where they actually are, and now that the two, as in the previous version said that the only release.

PS Besides, I also tried to specify the path to the templates by hand for each test and for Windows and HTML, but it gave the same results as in the first case. all the tests, I spent the last version of the project, 2D platformer and 3D platformer.

**Comment by OlexiyKravchuk** [comment]
https://github.com/okamstudio/godot/issues/1868#issuecomment-102526967

**Comment by reduz** [comment]
did you try unzipping the templates manually in the templates folder?

**Comment by OlexiyKravchuk** [comment]
No, it is unpacked and identified everything himself, I just saz where is an archive of the export template.

**Comment by reduz** [comment]
try uncompressing the templates yourself in c:\users\youruser\appdata\roaming\Godot\templates
and then try exporting and let me know if this works

**Comment by OlexiyKravchuk** [comment]
I went back, I deleted those templates are installed Godot, and replaced them by hand from the archives, and ran the tests again, the result is identical to the first, but after that, I discovered that the console that appeared after the launch at a moment when I ran the EXE built in debug mode I managed to catch it in the lens ...
http://snag.gy/XUCA4.jpg

I also found out that every time when I made attempts to create a new EXE is bit off part of the free space on your C: \ drive, ultimately in the butt to zero (do not worry, it's constantly going on at me very little memory, and it is not because Godot), as well as any point can not be removed by the EXE files (I pressed SHIFT + DELETE and the file disappear from the folder but after the second reappeared in the same place, but later disappear spontaneously O_o), then I started seek ways.
As a result, I found that the debugging version, there is a way to build, if the drive C: \ has more space, but I was not able to achieve, to build a release version, in any case, regardless of the amount of free space on drive C: \, and wherein each attempt to build places becomes smaller. I do a lot of problems with my PC ...

**Comment by ShedoSurashu** [comment]
@reduz I tried your suggestion of uncompressing the templates myself as opposed to doing it from the GUI but it's still producing the same result that is; exporting to Windows 32-bit will cause the game to crash on startup. With debugging enabled, however, it works.

**Comment by OlexiyKravchuk** [comment]
https://github.com/okamstudio/godot/issues/2093

**Comment by OlexiyKravchuk** [comment]
https://github.com/okamstudio/godot/issues/2189

**Comment by OlexiyKravchuk** [comment]
https://github.com/okamstudio/godot/issues/2238

**Comment by akien-mga** [comment]
Closing as it's too vague and a duplicate of other better described issues. Please try not to mix different bugs in the same issue next time (e.g. HTML5 should not have been mentioned at all here).
