### ISSUE TITLE
True Modal Dialog Box

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#19450]
Currently in Godot there is a Popup, WindowsDialog, AcceptDialog etc that allow for a pop up box with buttons.  One property that can be set is "exclusive" which is supposed to make the box Modal and so nothing can be clicked on except the box and its children.

The problem is that the _input(event) processes from other nodes underneath the dialogbox are still registering and reading clicks of the user.

Can the "exclusive" setting be made to be truly "modal" where all _input from other nodes are ignored until the Dialog node is exited?

**Comment by guilhermefelipecgs** [comment]
I think you should use this `_gui_input(event)` instead of `_input(event)`.

**Comment by ondesic** [comment]
Also, part of the Modality would great to have a built in yield() function that can wait for user response before continuing code when a dialogbox is open.

**Comment by ondesic** [comment]
I just tested _gui_input()

This doesn't stop the _input(event) of other nodes from firing.

I created a Sprite node and set the _input(event) function active.
Next, on top I create the AcceptDialog node.  I set the AcceptDialog input function to `_gui_input(event)` 
I also set the AcceptDialog to "exclusive"

I run the program and when I click on the AcceptDialog, it fires the _gui_input() function.  However, it also fires the Sprite's _input() function underneath it.

**Comment by Zylann** [comment]
It's expected. For non-GUI element, you have to use `_unhandled_input`.

**Comment by guilhermefelipecgs** [comment]
`_gui_input`will only work for GUI (Control nodes), in your case, try this:
On `AcceptDialog` create this code:
```
func _unhandled_input(event):
	if visible:
		get_tree().set_input_as_handled()
```
and for `Sprite`:
```
func _unhandled_input(event):
	 # your code here
```
More info here: http://docs.godotengine.org/en/3.0/classes/class_node.html#class-node-unhandled-input

**Comment by ondesic** [comment]
Let's say instead of a Sprite, like the code above indicates, it is a Button node.  
So, you have your normal GUI buttons, and then you have a Dialog open.  The normal GUI buttons are still visible.  Even using a script on the Dialog with _unhandled_input(event) and setting the input as handled, I can still push the GUI buttons.

How do I stop GUI elements from being pressed (like buttons) while the Dialog is open?

**Comment by guilhermefelipecgs** [comment]
> How do I stop GUI elements from being pressed (like buttons) while the Dialog is open?

Just set the dialog as exclusive.

See here: [TrueModal.zip](https://github.com/godotengine/godot/files/2087374/TrueModal.zip)

**Comment by tanjunior** [comment]
using v3.2.1 here. exclusive is not working

**Comment by KoBeWi** [comment]
Dialogs are sub-windows now, so this was implemented.
