### ISSUE TITLE
feature request: expose Script Creation Dialog to editor tools

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#19458]
I am creating an editor tool using the GraphEdit and GraphNode nodes and one of the features I want to provide the user is to be able to create a script and assign it to a graph_node for later compilation into a scene. Right now, this is implemented via Drag & Drop, but I want to also provide the ability to create a new script directly from that GraphNode itself in the editor tool similar to how it's done in the inspector. To do this, I would like to be able to reuse the same dialog that the inspector generates when creating a script instead of having to recreate this dialog myself.

**Comment by akien-mga** [comment]
Fixed by #19849.
