### ISSUE TITLE
Add ability to test whether something is being dragged

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#19457]
## Use Case

I am using drag and drop in my Editor Tool. When I am dragging an item over a Label, I want to set a border on the Label. The problem I found is that there is no good way with the current facilities of the D&D subsystem to implement this in a foolproof manner. 

At first, I tried to set a flag in my `Label`'s  `can_drop_data` method, and then check this flag in the callback for the connected `mouse_entered` signal. This issue I found with this was that the order at which these two callbacks are called is unreliable, so it wouldn't always work.

I have resorted to simply testing the left mouse button's stated using `Input.is_button_pressed` in the `mouse_entered` callback. If the mouse button is down at this time, I am assuming the user is dragging something. While this will probably be _good enough_ for a normal developer's workflow, it's technically not fool proof, as it will still place the border around the label if I just hold the left mouse button and drag the mouse into the Label's bounds.

## Proposed Solution

What I propose is to add a method to the `Input` singleton to test whether _something_ is being dragged currently (e.g. `Input.is_dragging`)

I feel that this is probably the simplest solution, but I understand that it may lead to some confusion around what is meant by "dragging".

I'm not really sure what the best approach here is. Maybe we instead offer some function in the `Control` or `CanvasItem` class to get this state instead of in the `Input` singleton and call this state something that more accurately describes its intent. 

I'm kind of opening this for discussion, as I feel that it's a facet of the current D&D subsystem that is somewhat lacking.

**Comment by bojidar-bg** [comment]
Note: it should be on SceneTree or Viewport, not on Input, since Input known nothing about dragging.

**Comment by akien-mga** [comment]
Should be fixed by `Viewport.gui_is_dragging()` added in 683c3f2fcf.
