### ISSUE TITLE
Bug with animation inside sprite.

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#1946]
When I put a node with animation inside sprite like this:
![captura de tela de 2015-05-19 17 05 12](https://cloud.githubusercontent.com/assets/1387165/7712701/5d758808-fe49-11e4-87ce-54ee1606cf93.png)

this bugs happens:
![out](https://cloud.githubusercontent.com/assets/1387165/7712638/c370b160-fe48-11e4-8a1d-a707e8fb7e33.gif)

Link to project created by @HeartoLazor:
https://mega.co.nz/#!zcgxTBAa!_uC6-kA_Znuo21SPxHEi2JZ_rX3erNCNkrx0tb63hiE

**Comment by HeartoLazor** [comment]
Change the color of the background or the font and test again.
![rp3hh1l 1](https://cloud.githubusercontent.com/assets/12376042/7713182/258a71d8-fe44-11e4-9d2d-c21ff8c02d4f.png)

**Comment by guilhermefelipecgs** [comment]
I changed and the problem continues.

**Comment by akien-mga** [comment]
I can't reproduce the issue using the given test project in the current master branch (apart from the fact that I had to disable "Centered" on the "bg" nodes to get it to look fine. Assuming it has been fixed, feel free to reopen or ask me to reopen if it's not the case for you.

**Comment by guilhermefelipecgs** [comment]
This problem continues happening (I tested now with this last commit a1059e3e3e54e9921c0426c8a5c9faf595175cf0), I guess I didn't explain very well how to reproduce this bug:

Download the project;
Open it in edit mode;
Click in "traveler" node and then reparent it to "bg" node;
And now play it.

**Comment by akien-mga** [comment]
Alright, this way I can reproduce too. I'll also add that the offset in the first bg node needs to be removed else it looks completely broken.

**Comment by reduz** [comment]
I have no idea what the problem is, but the bg node has a huge scale, which causes the node to become very large

**Comment by akien-mga** [comment]
Can this still be reproduced in the current master branch and/or in Godot 2.1.4?

**Comment by guilhermefelipecgs** [comment]
I'll give a check.

**Comment by guilhermefelipecgs** [comment]
I can't reproduce this error anymore.

**Comment by akien-mga** [comment]
Great! :)
