### ISSUE TITLE
GDNative can't open dynamic library with OpenMP

### ISSUE THREAD

**Issue by lupoDharkael** [godotengine/godot#19467]
**Godot version:**
3.0.2.stable.official

**OS/device including version:**
Fedora 28 x86_64

**Issue description:**
when I try to use OpenMP in my GDN (C++) project, Godot fails to run the project even though I used the ``-fopenmp`` flag
Here is the log:
```
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
ERROR: open_dynamic_library: Can't open dynamic library: /home/dharkael/generation/bin/libgeneration.so. Error: /home/dharkael/generation/bin/libgeneration.so: undefined symbol: omp_get_thread_num
   At: drivers/unix/os_unix.cpp:373.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:315.
ERROR: init_library: No nativescript_init in "res://bin/libgeneration.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1054.
```

**Steps to reproduce:**
Use any #pragma omp directive

**Comment by akien-mga** [comment]
That means that you did not link openmp with your library. Adding something like `env.Append(CCFLAGS=["-fopenmp"])` to your build script might do the trick.

At any rate it's not an issue with Godot but with how you build your GDNative module, so closing. (Feel free to ask further in this issue if you need help to properly link it, but then I'd need to see your SCons script)

**Comment by lupoDharkael** [comment]
That's how I did it. I changed the flag to LINKFLAGS and now it works! thanks for the help anyway and sorry for the for the inconvenience.
