### ISSUE TITLE
Opening a 3.0.2 project with Godot 3.0.3 reimports all assets

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19477]
Godot 3.0.3 RC3
Windows 10 64 bits

I opened a 3.0.2 project with 3.0.3, and it caused all of my assets to be reimported, which took a pretty long time...
I don't understand why this even happens, I changed none of the assets, and that's not a major release.
Reopening the project back in 3.0.2 reimports the assets again. What did change?

**Comment by akien-mga** [comment]
CC @hpvb

**Comment by hpvb** [comment]
The way the hashes are saved have been changed for 3.0.3 so a reimport cannot be avoided. This should help with storing your projects in a vcs however.
