### ISSUE TITLE
highp needed in shaders

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1947]
I look forward for some missing stuff in shaders, like highp. I'm currently developing some shaders for my game, and without it, they look very different on mobiles then on pc.

**Comment by reduz** [comment]
problem is that many mobile phones don't really support them or support
them half assedly (highp in the fragment program)

**Comment by Krzycho666** [comment]
Ok. Now I get it. I've checked GLSL_ES_Specification for this. I understand that since highp is obligatory it will couse compilation errors on some GPUs. But GLSL ES gives us "#define GL_FRAGMENT_PRECISION_HIGH 1" macro to check if highp is available on our GPU or not.
But anyways... lowp and mediump are fully supported by all GLSL ES 2.0 devices - so it could be added with no worries.

**Comment by reduz** [comment]
this will be added in 3.0 with 3D renderer rewrite

**Comment by reduz** [comment]
already added, so closing this
