### ISSUE TITLE
No grid in side orthogonal views

### ISSUE THREAD

**Issue by drequivalent** [godotengine/godot#19470]
**Godot version:**
3.0.2, but is present in 3.1 dev

**OS/device including version:**
Elementary OS Loki

**Issue description:**
Grid is only visible in the top view, it is expected to be in all orthogonal views. 

**Steps to reproduce:**
Switch the 3D viewport to left view, and then to orthogonal view
![selection_056](https://user-images.githubusercontent.com/1463277/41193844-1901b92e-6c1b-11e8-968e-75b020c63f99.png)

**Comment by AsherGlick** [comment]
The grid is currently locked in XZ plane it seems, I cannot find a UI to change it. It would probably be beneficial to allow it to be adjusted, similar to how the grid on GridMaps can be adjusted to different axises.

**Comment by Calinou** [comment]
The grid axes can now be configured in the Editor Settings thanks to https://github.com/godotengine/godot/pull/28289, but this is a global setting, not a per-viewport setting.
