### ISSUE TITLE
Unpredictable behaviour of aligning UI controls

### ISSUE THREAD

**Issue by alkhimey** [godotengine/godot#19478]
**Godot version:**

3.0.2

**OS/device including version:**

Linux, Ubuntu 17.10 64 bit

**Issue description:**

First of all I must say that this might be a lack of knowledge from my side rather than a real issue.

It seems that sometimes when changing one UI related parameter of a control, the editor would change some other parameters in random and unpredictable way, with undo not able to reverse these changes.

**Steps to reproduce:**
These things looks arbitrary to me, so I cant specify the exact steps. All I can say is that I had a `HBpxContainer` and two `Label`s inside it. I was trying to make it to fill the screen horizontally and put the labels on opposite sides of it. I was playing with `Align`, `Anchor`, `Margin`, `Rect` and the `Layout` option at the top of the editor.

**Minimal reproduction project:**

This might help. In this scene, try to change the `Margin` of the `HBoxContainer` named GUI to something else. What I experienced is that the content is centered and `Ctrl+Z` will not reverse this.

[Scene.zip](https://github.com/godotengine/godot/files/2087301/Scene.zip)

**Comment by guilhermefelipecgs** [comment]
Your project doesn't have a scene, can you post a new project?

**Comment by alkhimey** [comment]
@guilhermefelipecgs  Sorry accidentally uploaded a script, here is the scene as well as a GIF. This is only one example that I was able to consistently reproduce. 

![peek 2018-06-10 19-42](https://user-images.githubusercontent.com/652603/41203937-b0b5e7b0-6ce6-11e8-8bfa-8a0011fdcba2.gif)

[Scene.zip](https://github.com/godotengine/godot/files/2088049/Scene.zip)

**Comment by alkhimey** [comment]
Another mystery:

![peek 2018-06-10 19-58](https://user-images.githubusercontent.com/652603/41204092-c99801c6-6ce8-11e8-89de-a976b4dcb00f.gif)

**Comment by mrcdk** [comment]
Containers arrenge their contents automatically when they update. Anything inside a container will automatically receive anchors and margins from the container. 

Manually changing these parameters in a child of a container won't work and whenever the container updates itself it will be overwritten. The editor letting you modify these parameters is a known issue and will be addressed sooner or later.

**Comment by alkhimey** [comment]
@mrcdk  Oh, I understand now. Does it include the `Layout` menu at the top of the editor? 

In my particular example, how can I make each label "float" to the right/left sides of the container?

**Comment by mrcdk** [comment]
Yes, it includes the `Layout` menu because that's just some shortcuts to different layouts.

It really depends on your design and what you want to achieve. Some times you don't even need a container. But if you need one a mix of rect min size and different size flags applied to its children will get the job done.

For your particular example you don't need a container. Set the layout of your labels just like you did in the first gif but change the parent to a Control.

**Comment by guilhermefelipecgs** [comment]
> In my particular example, how can I make each label "float" to the right/left sides of the container?

Set horizontal flag "Expand" for the two labels will do what you want:
![captura de tela de 2018-06-10 16-41-09](https://user-images.githubusercontent.com/1387165/41205614-22784b82-6ccd-11e8-863b-4d42c22509a2.png)

**Comment by bojidar-bg** [comment]
Alternatively, you can add a Control node with Expand on between the labels, to push them away.

**Comment by groud** [comment]
I'll disable the layout menu when the control is a child of a container, that will be simpler.

**Comment by volzhs** [comment]
you mean greyed out instead of hiding?

**Comment by groud** [comment]
> you mean greyed out instead of hiding?

Yes, with a warning message as a tooltip.
