### ISSUE TITLE
Hiding a row of items in GridContainer messes up the layout

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19479]
Godot 3.0.3 RC3

I use a GridContainer with two columns to make a small inspector, and sometimes I need to hide lines so I hide two items at a time.
But it doesn't work:

![image](https://user-images.githubusercontent.com/1311555/41195760-ed71f792-6c33-11e8-922b-15b9a34d09c6.png)

I'm aware there is an issue with hiding an item, but here I'm hiding a full row.
It seems it was fixed in master though, but 3.1 is coming in more than a month... any chance to get it fixed in 3.0.3?

**Comment by akien-mga** [comment]
Given that 3.1 was released in the meantime and 3.2 is around the corner, there's little incentive to backport a fix to 3.0. If anyone feels strongly about it, feel free to make a PR backporting the relevant changes.
