### ISSUE TITLE
Godot 3.0.3 RC3 is a lot more bigger thhan RC1

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19476]
Godot 3.0.3 RC3
Windows 10 64 bits
Classic version (without Mono)

I don't know if anyone noticed it, but while RC1 weights 46 Mb, RC3 weights 58 Mb...
Any reason for this?

![image](https://user-images.githubusercontent.com/1311555/41195645-bb8b82cc-6c31-11e8-82dd-ecc4d6ee879a.png)

**Comment by hpvb** [comment]
Godot for Windows is now built with MingW instead of msvc due to incompatibilities with static linking of Mono. I can see if I can reduce the size of the binaries but this will likely not change for 3.0.3.

**Comment by Zylann** [comment]
@hpvb will we keep MinGW for long? Because I'm concerned that the following issue resurfaces as a result  #4313

**Comment by akien-mga** [comment]
@Zylann The builds at the time of #4313 were made with a ridiculously ancient version of MinGW/GCC on Ubuntu 14.04. The new builds @hpvb made use the latest MinGW/GCC, and have in many scenarios better performance than MSVC.

**Comment by Zylann** [comment]
I'll give my benchmarks a go with this version then

**Comment by hpvb** [comment]
I changed some settings in the build scripts, the new releases will be about 40MB in size.

**Comment by Zylann** [comment]
I ran my benchmarks, and it looks good :) overall performance even increased a little.
Except maybe for setting `PoolIntArray` items from GDScript:
![image](https://user-images.githubusercontent.com/1311555/41386847-fe55df80-6f83-11e8-8974-fea92d320797.png)
(3.0.3 RC3 on the left, 3.0.3 stable on the right)

**Comment by OvermindDL1** [comment]
@Zylann So what is that graph saying as there are no axis on it?  Is the 3.x series really that much slower than 2.x, or what is it showing?

**Comment by akien-mga** [comment]
@Zylann That looks pretty rad :D Is your test suite available somewhere?

**Comment by Zylann** [comment]
@OvermindDL1 the point of that graph isn't much the value of each bar, but their proportional difference. If you want to know what the value is, it's how many milliseconds the test took to run a large amounts of iterations.

**Comment by OvermindDL1** [comment]
>  If you want to know what the value is, it's the absolute amount of milliseconds the test took to run a large amounts of iterations (so the vertical axis starts at zero).

Ahh, so shorter is faster, in that case 3.0.3 had quite a loss in performance...

**Comment by Zylann** [comment]
@OvermindDL1 yeah, but as I explained I saw this loss only in a test where I set values in a `PoolIntArray`.

**Comment by Zylann** [comment]
The test suite is here https://github.com/Zylann/gdscript_performance

**Comment by akien-mga** [comment]
Awesome, thanks :)
