### ISSUE TITLE
"Insert Key" contextual button on CanvasItemEditor with AnimationPlayer open is not intuitive

### ISSUE THREAD

**Issue by imekon** [godotengine/godot#19484]
**Godot version:**

Godot V3.0.2 stable

**OS/device including version:**

Windows 10

**Issue description:**

I managed to create a track in the AnimationPlayer for the modulate property but I'm unable to create keyframes

I'm not clear if this is a bug or my misunderstanding of how to create keyframes. I think I'm following the same steps as I did for position and rotation. For modulation, I cannot create keyframes. What I'm trying to achieve is for "New Wave" to fade in, fly across the screen, then fade out.

**Steps to reproduce:**
 * Create modulate track in AnimationPlayer for a Label
 * Change length of track to 5 seconds, say
 * Move to 1 second
 * Change modulation on item by changing alpha value from 255 to 0 - you should see the label disappear except for it's outline selection rect.
 * Click on insert keyframe

Nothing happens, no keyframe appears. This process works fine on position and rotation. EG Rotation - you move to 1 second, change rotation, click on insert keyframe and one appears.

**Minimal reproduction project:**

[NewWave.zip](https://github.com/godotengine/godot/files/2087623/NewWave.zip)

**Comment by imekon** [comment]
So I was clicking on the keyframe button on the main editor toolbar. I tried clicking on the keyframe button by modulation - it creates a keyframe! That's so confusing... that main toolbar button is for location, rotation... only?

**Comment by imekon** [comment]
Deleting animations doesn't update the editor until you click away from the node then back, the animation is gone. Should I enter this as another bug?

**Comment by Zylann** [comment]
@imekon yes

**Comment by akien-mga** [comment]
Renamed issue to better match the actual problem. I agree that this "Insert Key" button is not intuitive, nothing says that it's going to keyframe the current transform (position, rotation, scale) of the selected node.

I'm not sure anyone uses it nor the loc/rot/scl buttons, IMO they could be dropped altogether.

**Comment by volzhs** [comment]
I am using it when making animations with 2d bones. it would be terrible without it.
