### ISSUE TITLE
[Mono] Conversion of MonoString to UTF8 failed

### ISSUE THREAD

**Issue by Supatier** [godotengine/godot#19483]
**Godot version:**
257d3c3f39fd144d202f112c9cb08a82c174afbc

**OS/device including version:**
Ubuntu Linux 18.04

**Issue description:**
I'm trying to get a bool from my settings file.
But it gives me:
```
0:00:00:0847 - Conversion of MonoString to UTF8 failed.
----------
Type:Error
Description: Conversion of MonoString to UTF8 failed.
Time: 0:00:00:0847
C Error: Method/Function Failed, returning: p_default
C Source: core/io/config_file.cpp:90
C Function: get_value
```

**Steps to reproduce:**
```
config.SetValue("Display", "Fullscreen", false);
config.Save("user://settings.cfg");
if ((bool)config.GetValue("Display", "Fullscreen") == true) {
                 OS.SetWindowFullscreen(true);
        } else {
                 OS.SetWindowFullscreen(false);
        }

**Comment by aaronfranke** [comment]
I'm getting the same error. Code and error:

    GD.Load("res://Assets/Menu/UI/MenuTheme.tres")

    0:00:01:0599 - Conversion of MonoString to UTF8 failed.
    ----------
    Type:Error
    Description: Conversion of MonoString to UTF8 failed.
    Time: 0:00:01:0599
    C Error: Method/Function Failed, returning: RES()
    C Source: core/io/resource_loader.cpp:186
    C Function: _load

**Comment by Supatier** [comment]
CC @neikeq

**Comment by lordee** [comment]
I'm also getting this, on something I otherwise do right above it:

`Button _joinBtn;
    Button _hostBtn;
    Network _network;
    public override void _Ready()
    {
        _joinBtn = (Button)GetNode("panel/join");
        _hostBtn  = (Button)GetNode("panel/host");
        _network = (Network)GetNode("/root/OpenFortress/Network");`
 

Fails on finding/assigning network.

**Comment by neikeq** [comment]
I cannot reproduce this. Does this always happen or only some times?

Can you try replacing these two lines: https://github.com/godotengine/godot/blob/3e128a6d8aa2982ec4da20c1dd73faa968b9207a/modules/mono/mono_gd/gd_mono_marshal.cpp#L195-L196

with:

``` C++

	if (!mono_error_ok(&error)) {
		ERR_PRINTS(String("Failed to convert MonoString* to UTF-8: ") + mono_error_get_message(&error));
		ERR_FAIL_V(String());
	}
```

and paste the new error message here?

**Comment by Supatier** [comment]
Hmm, the error doesn't happen anymore on c3023e8. I don't know why.

**Comment by akien-mga** [comment]
Closing as fixed as per the above.
