### ISSUE TITLE
Pick tile shortcut on macOS

### ISSUE THREAD

**Issue by k7771911** [godotengine/godot#19496]
**Godot version:** 3.0.3.RC3

**OS/device including version:** macOS High Sierra

**Issue description:**

The "Pick Tile" shortcut is Control-Click which on macOS registers as a right click and deletes the tile instead of picking it. The Shortcuts configuration does not seem to include any option to change the key.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by k7771911** [comment]
@vnen that should be the behavior indeed but it looks like the macOS shortcuts are not configured correctly.

**Comment by akien-mga** [comment]
Duplicate of #10761.
