### ISSUE TITLE
Click and drag points in texture region not responding to clicks as expected

### ISSUE THREAD

**Issue by gitnix** [godotengine/godot#19493]
**Godot version:**
3.0.2

**OS/device including version:**
macOS 10.13.4

**Issue Occurrence**:
In texture region
**Expected**:
Clicking and dragging the circles should adjust region size. 
**Actual**:
starts a new region at the point of click.
**Notes**:
If I click closer to the white border box I can get the size to adjust, but this is a small region to click (can accidentally click too far past the border) and not intuitive. I would expect clicking anywhere on the circle would allow me to resize the region.

![no_resize](https://user-images.githubusercontent.com/5448785/41205127-832cbd8a-6cbb-11e8-8f85-512031f84054.gif)

**Comment by groud** [comment]
This is fixed on master.

**Comment by akien-mga** [comment]
Closing then.
