### ISSUE TITLE
Class Ref pages do not link to tutorials

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#19495]
Looking at individual class ref files under doc/classes they include a section to link to relevant tutorials. But when you go to the actual generated documentation there is no tutorial section. 

For example in [Viewport.xml](https://github.com/godotengine/godot/blob/master/doc/classes/Viewport.xml) under the the heading 'tutorials' it lists:
http://docs.godotengine.org/en/3.0/tutorials/2d/2d_transforms.html
http://docs.godotengine.org/en/3.0/tutorials/viewports/index.html

However in the [actual docs](http://docs.godotengine.org/en/stable/classes/class_viewport.html) there is no section titled 'Tutorials' nor is there a link to any tutorials.

Im not sure if this is just something missed when the xml is converted into rst or if this was a choice. But I really think that relevant tutorials should be linked to from class references so new users can find more information and examples of how to use specific classes.

**Comment by akien-mga** [comment]
This should be fixed in the XML to RST converter: https://github.com/godotengine/godot/blob/master/doc/tools/makerst.py

**Comment by robojumper** [comment]
Can/should the format in the XML be changed too? Two ideas I had while implementing this in makerst.py were:

* Replacing direct http links with relative links makerst can use for sphinx :doc: references
* Using a more structured format for tutorial lists

Which would look something like this:
```
    <tutorials>
        <tutorial>../tutorials/2d/2d_transforms</tutorial>
        <tutorial>../tutorials/viewports/index</tutorial>
    </tutorials>
```

instead of this:
```
<tutorials>
		http://docs.godotengine.org/en/3.0/tutorials/2d/2d_transforms.html
	http://docs.godotengine.org/en/3.0/tutorials/viewports/index.html
</tutorials>
```

**Comment by akien-mga** [comment]
The engine uses those links too, so if you deconstruct the URL, you'll need to reconstruct it in the engine in C++ :) It's easier to parse the URL in makerst.py if it needs to be reduced.

I'm fine with adding a `<tutorial>` tag, though maybe `<link>` would be better.

**Comment by robojumper** [comment]
Thanks! There's one thing I'm not quite sure how to handle, and it's fragment identifiers in docs urls. I see two ways to implement them, example in [JavaScript.xml](https://github.com/godotengine/godot/blob/3fa77b3172c1c69b7bee9cdba4085c8947590e95/doc/classes/JavaScript.xml#L10):

![grafik](https://user-images.githubusercontent.com/14299449/41249695-12c79b78-6db5-11e8-8a72-c27b49a1efd8.png)

Looks mediocre, attempts to make the fragment identifier look pretty would probably look worse in many other languages (though running the section header through Sphinx to generate the fragment identifier probably already handles the make-it-look-worse part). A `:ref:` role would be better, but it can't be inferred from the URL.

![grafik](https://user-images.githubusercontent.com/14299449/41249700-166b1a2a-6db5-11e8-828d-b82f2abb956b.png)

In both of these, Exporting for the Web links to the docs page, while the first link each links to the actual section in the docs page. Not sure what would be better here.

**Comment by Ankk98** [comment]
I am a beginner and would like to give it a try.
