### ISSUE TITLE
Help quick search crashed

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19502]
Godot 3 master acd9646ede45f8c34f423e392e60bf128c953bd1
Windows 10 64 bits
With Visual Studio 2015 debugger attached <-- with time I found this detail is quite important as it makes silent bugs apparent

I got a crash when using the help quick search (typing quickly I might say, so maybe timing makes the bug likely).
Here is a screenshot of the crime scene:

![image](https://user-images.githubusercontent.com/1311555/41208837-3b237846-6d27-11e8-89e2-71dc8ab9fbcc.png)

**Comment by bojidar-bg** [comment]
Hm, whenever I read the title, my mind inserts an exclamation mark after the "Help".

Related/duplicate of #16529?

**Comment by Zylann** [comment]
Looks like it is, yeah

**Comment by bojidar-bg** [comment]
Closing this one then, discussion might continue on the other.
