### ISSUE TITLE
Ability to keyframe in Inspector is missing

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#19519]
**Issue description:**

The ability to keyframe in Inspector is missing when following the steps below. But hiding the Animation timeline and showing it again fixes it.

![timeline-bug](https://user-images.githubusercontent.com/15687516/41286775-f2b29c98-6e40-11e8-998c-93c72624bff2.jpg)

**Steps to reproduce:**
Create new project, open new scene, add 2D Root node, add 2D Sprite node, add Animation Player create new animation.

Godot version:

76875ba

**Comment by kubecz3k** [comment]
I was able to confirm in d5bb6faac77334154d2b16a3ff2d7ef6479b98be
Worth to note that this can be workarounded  by hiding animation doc and showing it again (by clicking `Animation` button on the bottom of the editor)

**Comment by akien-mga** [comment]
Also couldn't reproduce it, assuming fixed.
