### ISSUE TITLE
Problem setting up XCode as IDE with godot_ios.xcodeproj

### ISSUE THREAD

**Issue by Kaliham** [godotengine/godot#19513]
**Godot version:**
Verison : v3.1.dev.bustom_build.2a9253a

**OS/device including version:**
MacOS/OSX High Sierra version 10.13.4

**Issue description:**

**info:** 

so i followed these two article/docs to build and run Godot on xcode
osx compiling:
http://docs.godotengine.org/en/3.0/development/compiling/compiling_for_osx.html#compiling
configuring ide:
http://docs.godotengine.org/en/3.0/development/cpp/configuring_an_ide.html#xcode
though this step was out-dated so couldn't follow it:
![screen shot 2018-06-12 at 7 18 30 am](https://user-images.githubusercontent.com/39249811/41269914-e367ffba-6e10-11e8-84a3-1faac6399dad.png)

**problem :**

now after i finished going through the steps i get this error :
<img width="270" alt="screen shot 2018-06-08 at 10 50 56 pm" src="https://user-images.githubusercontent.com/39249811/41269781-05472d64-6e10-11e8-8f5f-1044bc2f1689.png">
i was told to use a pip module called kin ( https://github.com/Karumi/Kin ) which helps check the problems in a .xcodeproj file especially the project.pbxproj so the output of kin was as follows
<img width="1409" alt="screen shot 2018-06-12 at 6 23 41 am" src="https://user-images.githubusercontent.com/39249811/41269861-86e9712e-6e10-11e8-836f-f248e4553dc0.png">
( https://pastebin.com/Ht000nmP ) the text of the output.
*the stackoverflow post : https://stackoverflow.com/questions/37073610/xcode-7-3-couldnt-load-project

**additional:** 
if possible along the way to update the documentation regarding xcode . please 👍

**Comment by akien-mga** [comment]
Are you building for macOS as you mention or for iOS as the template you're trying to use says ("godot_ios")?

**Comment by Kaliham** [comment]
MacOSi followed the tutorial i mentioned above to make a xcode dummy project please check the configuring ide like that waz provided

**Comment by akien-mga** [comment]
None of the two pages you link mention `godot_ios.xcodeproj`, so why are you trying to use it?

**Comment by Kaliham** [comment]
i am not trying to use them but when i import the project as in the configuring ide doc i always get this error .  so when i reach the end of the docs it says that if i put a breakpoint it should stop their but it doesn't tho it's built (gives me build successful message) but i think i doesn't run

**Comment by bkapukaranov** [comment]
While I agree the Xcode setup documentation page could be clearer and more verbose, it is not outdated (I'm not sure if it hasn't been updated since the bug was opened). 
I followed the guide and compiling/running in Xcode works.

The error you see will not prevent you from building and debugging the engine.
If you followed the instructions and the engine did not run after successful build it could be due to incorrect execution of the post build script that links the Godot executable so Xcode can run it afterwards (the paths used in the post build script depend on where the project was created on the fs).

**Comment by myhalibobo** [comment]
I have the same problem. And the documentation is not detailed enough

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc2](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-2) or any later release?

**Comment by dandingol03** [comment]
i can reproduce this bug 
![QQ_1725735860949](https://github.com/user-attachments/assets/38671261-3086-44d3-b5c7-8e985f3d78d4)
