### ISSUE TITLE
TabContainer don't show hidden tabs when it's size changed.

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#19510]
**Godot version:**
3.0.3

**OS/device including version:**
Any

**Issue description:**

![out2 mp4](https://user-images.githubusercontent.com/1387165/41255458-001663aa-6d9d-11e8-8afd-efa2435d939b.gif)

**Comment by vnen** [comment]
Maybe related to #15992 (or the same?) 

Also, "any" version means it's also a problem in Godot 2?

**Comment by guilhermefelipecgs** [comment]
> Maybe related to #15992 (or the same?)

I'm not sure, I can't reproduce the error reported there. Maybe was fixed.

> Also, "any" version means it's also a problem in Godot 2?

In godot 2, I can't even click on this buttons to change tab.
