### ISSUE TITLE
The new animation timeline/workflow has major issues

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#19518]
With the new animation timeline/workflow two major issues have arisen.

### Adding keyframes:
Where has the ability to keyframe node properties from the Inspector gone? 

The new way of adding keyframes to the animation timeline is not good and needs improvement.
To add a new keyframe you have to go through the convoluted process of clicking the Add Track button, then navigating a scene tree and selecting your node, then navigating a property tree to find the property you want. Right click the resulting track and select Insert Key, click the keyframe, find the Inspector window and input the value you want. This is making a process that up until now required only two mouse clicks needlessly difficult. 

**Please bring back the ability of keyframing node properties from the Inspector.**

**Current workflow (Godot 3.0.2).**
![timeline-02](https://user-images.githubusercontent.com/15687516/41277464-9c0c8e6c-6e27-11e8-9961-9f9e4d0fa3fd.jpg)

**New Workflow (Godot 76875ba).**
![timeline-01](https://user-images.githubusercontent.com/15687516/41277454-98145eac-6e27-11e8-9148-8f7d0610f11d.jpg)

### Displaying the properties of a keyframe:
The keyframe properties has been moved from the animation timeline to the Inspector, this is counter productive.
Most of the time when making an animation you are working with multiple values for multiple nodes and this change just makes that process more difficult, more time consuming and ultimately more irritating. You are now required to constantly click back and forth between your keyframes and scene nodes to display the properties of one or the other. Before this change you were able to see both at the same time. 

**Please move the keyframe properties back to the animation timeline.**

**Current workflow (Godot 3.0.2)**
![timeline-03_1](https://user-images.githubusercontent.com/15687516/41280020-3d499bca-6e2e-11e8-8e32-7a56b164b076.jpg)

**New Workflow (Godot 76875ba).**
![timeline-03_2](https://user-images.githubusercontent.com/15687516/41284758-83ec5e94-6e3a-11e8-9477-5ffc5a24dac9.jpg)

**Godot version:**

76875ba

**Comment by kubecz3k** [comment]
I'm not sure if I get this issue right, you don't have keys in inspector? In such case it's a bug, but I was unable to reproduce on d5bb6faac77334154d2b16a3ff2d7ef6479b98be
![anim](https://user-images.githubusercontent.com/6129594/41285761-87fb5dde-6e3d-11e8-9656-4272d51c4599.png)

**Comment by kubecz3k** [comment]
Would be great if you could provide reproduction steps if my above statement is right

**Comment by kubecz3k** [comment]
Also about displaying properties of keyframe: what I'm experiencing is quite an improvement, but again not sure if that part is not somehow bugged for you as well.
I have UI for keyframed property in inspector area, but it's there only contextually. I can't imagine you would want to modify keyframed property and node property exactly at the same time. Keyframed properties are displayed in inspector _only_ when keyframe is selected, when you click on any node in scene tree or somewhere else keyframe will lost it's focus and will no longer be displayed inside inspector tab:
![anim_keyframe](https://user-images.githubusercontent.com/6129594/41286171-ce2333e4-6e3e-11e8-8fda-7a40028279c2.gif)

**Comment by PullTheStrings** [comment]
Reprodution steps:
Open new scene, add 2D Root node, add 2D Sprite node, add Animation Player create new animation.

That's what I'm doing in 76875ba and no small keys in the Inspector are to be  seen. So this must be a bug in my build. I am relieved actually as this add new keyframe thing really made me worried.

**Comment by kubecz3k** [comment]
@PullTheStrings I was able to reproduce in d5bb6faac77334154d2b16a3ff2d7ef6479b98be with provided steps, but only in a fresh project (so I would add 'create new project') in first step. I think it might be good idea to create new 'more direct' issue for this bug

**Comment by kubecz3k** [comment]
note: to 'workaround' this big with missing key icons, all that needs to be done is to hide animation docs and show it again (by clicking `Animation` button on the bottom of the editor)

**Comment by PullTheStrings** [comment]
Work in progress I guess. And thanks.

**Comment by PullTheStrings** [comment]
I have reported the keyframe issue here #19519

**Comment by kubecz3k** [comment]
Cool, would be the best if you could also start with clean issue report for "Displaying the properties of a keyframe" part

**Comment by kubecz3k** [comment]
@PullTheStrings thank you!
Archiving since new more direct issues were created:
#19519 - missing keyframe icon
#19518 - keyframed properties presentation
