### ISSUE TITLE
Basis 3 axis constructor doesn't work as expected.

### ISSUE THREAD

**Issue by oisincar** [godotengine/godot#19511]
**Godot version:**
Commit hash: d5bb6faac77334154d2b16a3ff2d7ef6479b98be (Mono)

**OS/device including version:**
Windows 10.

**Issue description:**
Basis constructor from 3 axis doesn't work as expected in both c++ source and c#.
Godot stores basis internally as the transpose of the vectors, however this isn't taken into account when constructing this way.

```
Basis ( Vector3 x_axis, Vector3 y_axis, Vector3 z_axis )
```

You'd expect Basis(x,y,z).x == x, however this isn't the case.

**Steps to reproduce:**
```
var b = new Basis(new Vector3(0,1,0), new Vector3(0,0,1), new Vector3(1,0,0));
GD.Print(b.x, ", ", b.y, ", ", b.z);
// Prints: (0, 0, 1), (1, 0, 0), (0, 1, 0)
```

Edit: I'd happily submit a PR to fix this if someone can confirm this isn't intended behavior.

**Comment by reduz** [comment]
@neikeq Remember that in Godot those are flipped, if you need help getting them right let me know..

**Comment by neikeq** [comment]
>Basis constructor from 3 axis doesn't work as expected in both c++ source and c#.

Quoting @reduz:

>C++ implementation is designed so auto vectorizer is more efficient, this is why its flipped

So we're only changing C#'s implementation to match GDScript's. The constructor behavior in C++ is the intended one.
