### ISSUE TITLE
Alt Key not recognized in Linux Editor

### ISSUE THREAD

**Issue by naturally-intelligent** [godotengine/godot#19525]
**Godot version:**
3.0.2 Stable

**OS/device including version:**
Ubuntu MATE 18.04

**Issue description:**
Left or right ALT keys are not recognized by the editor, so any keyboard shortcuts using ALT are unavailable.  Other applications running alongside the Godot editor successfully recognize ALT, for example Firefox.  It may be an issue with MATE, but using Marco or Compiz compositor doesn't affect the behavior.  This is for the editor specifically, not for exported game builds (which I haven't tested).  Confirmed on two separate hardware installations of same OS.

**Steps to reproduce:**
Press any ALT keyboard shortcut combination on Linux while in editor - nothing happens.

**Minimal reproduction project:**
Not project-related.

**Comment by kubecz3k** [comment]
On Ubuntu 18.04 in d5bb6faac77334154d2b16a3ff2d7ef6479b98be build shortcuts with alt key are working (checked alt+[up]/[down] in script editor).

**Comment by Calinou** [comment]
Does it work if you change your window manager's "action" key from <kbd>Alt</kbd> to <kbd>Meta</kbd> (for example)? This should generally not have an impact on keyboard shortcuts, but it will definitely impact <kbd>Alt</kbd> + mouse button combinations.

**Comment by naturally-intelligent** [comment]
After upgrading to 3.0.3, the Alt key is now working in the editor!
