### ISSUE TITLE
Double clicking on linked signal should open that function in the editor

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#19527]
**Godot version:**
3.0.2 stable

**OS/device including version:**
MacBook Air (13-inch, Early 2014) (1,4 GHz Intel Core i5)
MacOS High Sierra 10.13.3

**Issue description:**
When connecting a signal from the *Node* panel, the code editor opens in that new function. However, when the signal is already connected, double clicking on the connection doesn't open the editor in the referenced function.
![](https://i.imgur.com/liF18sC.png)

**Steps to reproduce:**
1. Click on a node
2. Connect a signal
3. Double-click the newly created connection
4. Nothing happens, it should open the editor in that function

**Comment by kubecz3k** [comment]
I was able to reproduce in d5bb6faac77334154d2b16a3ff2d7ef6479b98be. 
But it's worth to say that in my case after saving the scene and script it started to work.
