### ISSUE TITLE
Polygon2D + texture altas broken

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#1953]
The texture coordinates used by a Polygon2D seem to not be adjusted to work with the texture's new position in the atlas.  So Polygon2D's that use a texture that ends up in an atlas render with the wrong texture coordinates.

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by romulox-x** [comment]
Just checked.  This is still an issue.

**Comment by reduz** [comment]
Polygon2D uses normalized coordinates, so it's not expected to work with a generated atlas
