### ISSUE TITLE
New inspector: inconsistencies with exported enums

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#19534]
**Godot version:** 3.1 acd9646

**Issue description:** Exported enums don't work:
![daheck](https://user-images.githubusercontent.com/35355161/41320435-c94ced9a-6e6d-11e8-89c7-002dfa78888e.png)

There seem to be at least three problems here. First, the inspector shows an incorrect default value. Second, the default value appears to be ignored. Third, changing the value through the inspector doesn't seem to work, at least in certain cases:
![daheck2](https://user-images.githubusercontent.com/35355161/41320139-8ae03496-6e6c-11e8-9a24-fee7c063acae.png)

Probably related, clicking on the reset icon in the inspector above prints this error
` core/object.cpp:1202 - Error calling method from signal 'property_changed': 'EditorInspector::_property_changed': Method expected 2 arguments, but called with 1.
`

**Minimal reproduction project:** [TT.zip](https://github.com/godotengine/godot/files/2095974/TT.zip)

**Comment by akien-mga** [comment]
CC @bojidar-bg

**Comment by ordigdug** [comment]
I have a fix for:  "Clicking on the reset icon in the inspector above prints this error
core/object.cpp:1202 - Error calling method from signal 'property_changed': 'EditorInspector::_property_changed': Method expected 2 arguments, but called with 1."
This was happening for any "export(type) var name " with no assignment.
Will submit a pull request soon.

**Comment by ordigdug** [comment]
@bojidar-bg Your right, when changing the enum value in the inspector its not setting the enum value correctly. I will work on a fix for that.

**Comment by ordigdug** [comment]
@bojidar-bg Pull request inspector-fix-inconsistencies-with-exported-enums has been updated.

**Comment by ordigdug** [comment]
@bojidar-bg updated pull requests.

**Comment by Chaosus** [comment]
I checked this issue and looks like its fixed. _Closed by bugsquad._
