### ISSUE TITLE
Global Illumination picks up gizmo colors.

### ISSUE THREAD

**Issue by Gyrth** [godotengine/godot#19535]
**Godot version:**
3.0.2

**OS/device including version:**
Ubuntu 18.04 Linux.

**Issue description:**
My game is a black and white shooter, but while baking the GI on my new level I get colors mixed in. I think it sometimes picks up the gizmo color. Sometimes there is a lot of green, which leads me to believe that it's actually picking up the color of the GI Extends.

**Steps to reproduce:**
1. Create scene without any color. Most likely small interior.
2. Add a GIProbe and bake at 64 Subdiv with the GIProbe selected.
3. See colors on walls.

![image](https://user-images.githubusercontent.com/14081613/41322609-368e4c32-6eaa-11e8-81c6-d3aba4b03dd4.png)

![image](https://user-images.githubusercontent.com/14081613/41322767-1d4d87a0-6eab-11e8-86ff-e8586fb674fa.png)

**Comment by Calinou** [comment]
I can't reproduce this issue in 
[this sample project](https://github.com/godotengine/godot/files/2354353/test_gi.zip). Have you tried baking GIProbe after hiding gizmos in your project? (You can do so by clicking the **[ Perspective ]** button at the top-left corner at the 3D corner then choose **View Gizmos**.)

**Comment by Gyrth** [comment]
[test_project.zip](https://github.com/godotengine/godot/files/2797459/test_project.zip)
Here is a test project which should show the bug when you run it. I think it has something to do with the compression of textures. On both the material texture and the GIData. 

This project also shows a graphical bug when you use triplanar material with a 1 roughness set. And in some cases the GI seems to darken and lighten based on the camera angle. 

![image](https://user-images.githubusercontent.com/14081613/51767352-5e17f380-20dd-11e9-9987-0651d943fbdb.png)
[Peek 2019-01-25 20-10.zip](https://github.com/godotengine/godot/files/2797481/Peek.2019-01-25.20-10.zip)

**Comment by KoBeWi** [comment]
This is basically #32427
Just disable the `compress` property.
