### ISSUE TITLE
Bizarre UI bugs.

### ISSUE THREAD

**Issue by Gutmaster** [godotengine/godot#19546]
**Godot version:**
3.02/3.03

**OS/device including version:**
Windows 7
Radeon RX 560

**Issue description:**
Initially when I opened my project today my script text was just jammed into a tiny thin box at the top of the screen with the rest of the UI proportions in the center square also out of wack. After updating it looked the same, after opening different projects that worked fine and switching back to mine it looks like this.
![help](https://user-images.githubusercontent.com/6592724/41377715-ca68cfec-6f11-11e8-8e6b-ec4c06f55bc8.png)

After deleting a large chunk of my files, opening the project and then restoring them it seems to be back to normal.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment]
It looks like a driver bug. Have you tried upgrading them ?

**Comment by Calinou** [comment]
Closing due to lack of response (see @groud's comment above). Please comment if you can still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4).
