### ISSUE TITLE
Scripts don't recognize onready variables when there isn't a _ready() function

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#19548]
**Godot version:**
3.0.2 stable

**OS/device including version:**
MacBook Air (13-inch, Early 2014) (1,4 GHz Intel Core i5)
MacOS High Sierra 10.13.3

**Issue description:**
Consider these two scripts:
```python
extends Node2D

onready var testVariable = position

func _ready():
	pass
```
and:
```python
extends Node2D

# Comment the line below and it will work
onready var testVariable = position
```

They might appear to be equivalent, but only the first one works. The second shows an error saying that it can not find the position variable.

**Minimal reproduction project:**
[Onready Bug Test Project.zip](https://github.com/godotengine/godot/files/2099898/Onready.Bug.Test.Project.zip)

**Comment by ordigdug** [comment]
Bug happens in 3.0.3 Stable and 3.1 Master as well.

**Comment by dragmz** [comment]
Seems to error for _init as well:

````
extends Node2D

var p = position

func _init():
	pass
````

vs

````
extends Node2D

var p = position
````

**Comment by dragmz** [comment]
I think it's because ````_is_class_member_property```` returns false if ````_parse_function(p_script, p_class, NULL)```` is called with a NULL p_func, which is the case for a missing _ready / _init.

**Comment by Zylann** [comment]
In my plugin I have a tool script which has `onready` but I didn't define `_ready` or `_init`. However... it works fine.

**Comment by vnen** [comment]
@Zylann this is only a problem if you are accessing member properties withing the `onready` statement.
