### ISSUE TITLE
Conditionally Cancel Auto Import Resource (Custom Import Plugin)

### ISSUE THREAD

**Issue by Ragnoroct** [godotengine/godot#19555]
**Godot version:**
3.3

Hi,

I'm working on a custom import plugin. The extension currently imports (automatically) json files so when a json file is added it tries to import it (and fails if it is in the wrong format). But I only want to conditionally import it based on its contents. I'm not sure how to do that. 

I want to somehow exit the import function if some keys are missing or any other condition is true.

So that some .json files are imported as resources and others are not.

**Comment by Web-eWorks** [comment]
If you are writing your importer in GDScript, returning one of the ERR_* constants (other than ERR_OK) from your import function will cause the editor to cancel importing the file.

[Reference](https://github.com/godotengine/godot/blob/master/editor/editor_file_system.cpp#L1438-L1442)

**Comment by Ragnoroct** [comment]
Thank you! It accomplishes the problem. It is sort of lying though because the import isn't failing. It's just the wrong import script. 

I know I can change the extension and have a unique extension per import plugin too.

Okay, thanks for your help!
