### ISSUE TITLE
Skeleton::get_bone_global_pose function should be renamed

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#19551]
Skeleton's `get_bone_global_pose` returns the transform of the specified bone with respect to the skeleton, rather than the actual global/world frame (similar for the setter).

Something like `get_bone_skeleton_pose` would probably be a better name.

This would be a compatibility breaking change, so in the short term this could at least be documented.

**Comment by akien-mga** [comment]
Thanks, I've added it to the list of methods to rename on #16863.

Once the documentation for the current name is improved, we can likely close this issue (and keep only the tracker open which references it).

**Comment by tagcup** [comment]
Can we add also `get_bone_transform` to that list?

That is, of course, assuming that you want to keep it. I'm not sure how it's useful. It's not used anywhere, and it's badly named.

**Comment by akien-mga** [comment]
> Can we add also get_bone_transform to that list?

Done.

Since we now have better docs that make the ambiguity clearer, closing this issue (simply to bring down the number of open issues :)). The actual renamings should happen as part of #16863 (but we can keep discussing proposals in this closed issue to keep things focused).

**Comment by tagcup** [comment]
Thanks!

**Comment by akien-mga** [comment]
@tagcup Unrelated, but I've sent you an email to the address used in your git commits last week, I'm not sure if that's an inbox you check regularly so notifying you here :)
