### ISSUE TITLE
Error on create C# script

### ISSUE THREAD

**Issue by leotada** [godotengine/godot#19554]
**Godot version:**

v3.0.3

**OS/device including version:**

Fedora Linux 28 x64 bits 4.16.14-300.fc28.x86_64
```
Mono JIT compiler version 5.12.0.233 (tarball Tue May  8 09:28:02 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

**Issue description:**

```
 modules/mono/editor/godotsharp_builds.cpp:135 - Cannot find binary for 'MSBuild (Mono)'
 The build method threw an exception.
System.IO.FileNotFoundException: Cannot find the MSBuild executable.
 modules/mono/csharp_script.cpp:2360 - Cannot add res://Sprite.cs to the C# project because it could not be created.
 modules/mono/csharp_script.cpp:1957 - Condition ' !valid ' is true. returned: __null
```

**Steps to reproduce:**
Install Mono 5.12
Create a Godot Project > Add a C# script.

**Minimal reproduction project:**

New project with C# script.

**Comment by vnen** [comment]
> Cannot find binary for 'MSBuild (Mono)'

Do you have MSBuild installed? If so, which version?

**Comment by leotada** [comment]
Should not come with Mono installation?

**Comment by leotada** [comment]
I did not try install explicity msbuild. Later at home I will try.

**Comment by leotada** [comment]
mono-complete didn't install msbuild. I had to run explicitly this command:
`sudo dnf install msbuild`
And works now. Maybe it can be a requirement in the website.
