### ISSUE TITLE
CollisionPolygon2D with polygon point count < 3 throw issue in debug console

### ISSUE THREAD

**Issue by TotCac** [godotengine/godot#19558]
**Godot version:**
current master

**OS/device including version:**
Windows 10 64bits

**Issue description:**
Creating a CollisionPolygon2D with polygon points < 3 throw error (not catched by editor) in debug console when saving scene or loading one
ERROR: canvas_item_add_polygon: Condition ' pointcount < 3 ' is true.
   At: servers/visual/visual_server_canvas.cpp:668

**Steps to reproduce:**
Place CollisionPolygon2D with no additionnal properties and save the scene

**Minimal reproduction project:**
n/a

**Comment by Zylann** [comment]
This is expected, the node cannot work if it doesn't have enough points to form the simplest shape possible (a triangle).

**Comment by TotCac** [comment]
I expect having only a visual warning in the editor as it was before 2d meshes commit, not an error of the engine.
Because having an empty CollisionPolygon2D that you populate at runtime is needed sometimes.

**Comment by vlad-ed-git** [comment]
was about to post this issue too... it would be better if a warning was thrown not an error!

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/45724 as it's more up-to-date.
