### ISSUE TITLE
Missing icons in 3.0.3 (regression)

### ISSUE THREAD

**Issue by Barugon** [godotengine/godot#19567]
Godot 3.0.3

There are missing icons in the project export window. 

![screenshot from 2018-06-14 10-52-10](https://user-images.githubusercontent.com/16503728/41429410-e60de330-6fc1-11e8-8fde-5d511f49ef95.png)

**Comment by akien-mga** [comment]
CC @hpvb

**Comment by Barugon** [comment]
This is the Linux x86_64 executable BTW.

**Comment by hpvb** [comment]
Oh, never noticed that. I'll figure out what was missed. Sorry!

**Comment by hpvb** [comment]
This no longer seems to be an issue, at least on 3.0.5 I see all icons everywhere.
