### ISSUE TITLE
1.1 stable iOS and HTML5 exports

### ISSUE THREAD

**Issue by jsaade** [godotengine/godot#1956]
Just downloaded 1.1 for testing. It is missing iOS export (I am on Mac). And the html5 export is broken (the generated html file seems to link to other missing files).

**Comment by vnen** [comment]
The iOS export exists, but it is not possible through the editor. Check [the documentation](http://www.godotengine.org/projects/godot-engine/wiki/Exporting_for_iOS) on how to export for iOS. One Click Deploy is asked in #2703.

As for HTML5, it is working in the current nightly builds, though it's still not perfect.
