### ISSUE TITLE
C# 3.0.3 failed to build GodotSharp solution

### ISSUE THREAD

**Issue by Astrych** [godotengine/godot#19564]
**Godot version:** 3.0.3-mono

**OS/device including version:** Windows 10

**Issue description:** Clicking on "Create C# solution" (with VS Build Tools) lead to the fallowing errors:
failed to build GodotSharp solution
CSC(0,0): Invalid option 'portable' for /debug; must be full or pbonly

**Steps to reproduce:**
In Editor Settings -> Mono -> Builds set -> Build Tool: select "MS Build (VS Build Tools)".
Click "Create C# solution".

Creating solution with MS Build (Mono) works as expected.

**Comment by akien-mga** [comment]
The error sounds like it might be related to #18949, and #14822 where @neikeq commented:

> For existing projects, you need to manually rename all `<DebugType>full</DebugType>` occurrences in your csproj file to `<DebugType>portable</DebugType>`.

@hpvb This should likely be mentioned in the 3.0.3 release notes.

**Comment by akien-mga** [comment]
Though wait before mentioning it in the release notes, it seems like the issue is the other way around here (`portable` used by only `full` supported?).

**Comment by neikeq** [comment]
What's the version of MSBuild and csc?

**Comment by DevMagicLord** [comment]
I got same issue on Windows, last mono is installed but Godot is unable to locate it and compile.

**Comment by Astrych** [comment]
It was my mistake. I've installed Microsoft Build Tools 2015 version 14.0.23107.10. It's a very old version I think. Installed newest one and it works like a charm. So I think I will close that issue :)
