### ISSUE TITLE
Better collada import

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#19569]
Hi there,

When some collada object is drop in Godot project folder there is to much steps 
1 ) Double Click on collada file 
2) new inherited scene dialog box , click ok 
3) rename scene root as the same name of the object

Godot could automatically 
1 ) create a new inherited scene with object at center when a collada file is droped or imported in project
2) name inherited scene root node with collada file name
3) create automatically a thumbnail of the object without grid and origin display (it can be updated later when material is changed)

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
There is something called ESCN which is being worked on. ESCN is a type of TSCN (Godot text scene file) which can be exported DIRECTLY from Blender. So you would open the .escn file directly in Godot as a scene.   

Follow the development of godot to blender native exporter here https://github.com/godotengine/godot-blender-exporter

**Comment by DevMagicLord** [comment]
I don't know what ESCN or GLFT2 will be better and able to
- create automatically a new inherited scene with object at center when a file is dropped in the project 
- name inherited scene root node with original file name
