### ISSUE TITLE
Warn or open editor if project.godot in $pwd can't be run

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#19570]
Hi there

Double click on Godot 3.0.3 on windows, it closes without showing Godot project list.

**Comment by hpvb** [comment]
This happens if you try to open the editor in a directory that has a godot project in it without a main scene set. We should maybe open a pop-up in that case.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Godot can function as a a generic editor for all projects or can load specific projects as well. Run godot binary executable from Poweshell/Terminal and you will see a lot of commands that you can tell godot editor how to behave or what to run directly even run without gui.

I think Godot will try to run the project present in current directory and if the project is not well set up it will fail opening the project. 

Put godot  executable in it's own folder separate from all other projects

**Comment by DevMagicLord** [comment]
The only way was to add  "--project-manager" in Godot shortcut.

Perhaps Godot should provide a default shortcut  ?

**Comment by DevMagicLord** [comment]
Or fallback to display project list with any projects it could find or none if there is no projects available.
