### ISSUE TITLE
Need to press F5/F6 twice on 3.0.3 in release_debug (regression)

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#19576]
I sometimes need to press F5 or F6 twice to run the project or scene with 3.0.3.

**Comment by akien-mga** [comment]
OS?...

**Comment by volzhs** [comment]
I've experienced the same issue with 3.1.dev.
couldn't figure out reproduce steps yet.

**Comment by letheed** [comment]
I'm on Ubuntu 18.04.

**Comment by Zireael07** [comment]
What happens the first time you press the button? (i.e. nothing, debugger disconnected message, something else?)

**Comment by letheed** [comment]
Nothing, the output tab remains empty if I've cleared it.

**Comment by hpvb** [comment]
well, this is a fun one... ;)

**Comment by paul59** [comment]
I have the same issue on Linux Mint 18.3. Not sure if this is related but F5 causes a window or desktop refresh (even though it's not listed in Mint's desktop shortcuts as far as I can see). Perhaps the first press of F5 is intercepted by the OS and refreshing the window? Pure guesswork.

**Comment by akien-mga** [comment]
I can reproduce it too on Mageia 6 x86_64 (Linux) with 3.0.4-stable. I'll see if I can bisect.

**Comment by akien-mga** [comment]
Can't reproduce it with a debug build (`scons p=x11 -j2`) of the 3.0.3-stable tag, now testing release_debug.

Tested so far:
- 3.0.2-stable official build (GCC 7, LTO, release_debug): No bug
- 3.0.3-stable official build (GCC 8(?), LTO, release_debug): Bug (different buildsystem than 3.0.2 and earlier)
- 3.0.4-stable official build (GCC 8(?), LTO, release_debug): Bug
- 3.0.3-stable custom build (GCC 5, no LTO, debug): No bug

**Comment by akien-mga** [comment]
I could reproduce it with a custom build of 3.0.3-stable with `target=release_debug`, so the problem comes from that option.

**Comment by akien-mga** [comment]
The regression is caused by 28ab60422d648d43d219186ea0ecffce1645188f in the master branch (7563c17113790fe66a816c781001791bd571ef3c in the 3.0 branch). CC @robfram

**Comment by allkhor** [comment]
Still reproducible on my machine:
Godot versions:  godot 3.1 ebd14a7 and all 3.x versions target=release_debug
OS: Xubuntu 16.04.5 LTS 4.4.0-135-lowlatency
PC: Core i5-750, Nvidia GTX 750 Ti proprietary drivers 390.77
Not reproduced on second machine:
OS: Xubuntu 16.04.5 LTS 4.4.0-135-generic
PC: Pentium 4 (old), Nvidia GTX 260 latest proprietary drivers
![f6](https://user-images.githubusercontent.com/1049442/45669190-0a026e80-bb41-11e8-87f5-85a17027d96d.gif)
With target=debug work as expected.
