### ISSUE TITLE
Universal Gizmo

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#19571]
Hi there,

Like many users i use editor menus and icons instead of keys shortcuts.
Please bring universal gizmo manipulator, able to move,scale and rotate.
Its less clicks and faster objects placement.

http://forum.reallusion.com/uploads/images/30616bf2-0132-49f0-8f6f-3f6f.jpg

Or bring a key shortcut like space to quickly switch between move,rotate and scale gizmos.

**Comment by akien-mga** [comment]
Well there's one already, no?

**Comment by Web-eWorks** [comment]
There's already a universal manipulator (select, move, and rotate, under the Q key), but a shortcut to cycle through the individual manipulators would be useful.

Spacebar is the standard shortcut (at least in UE4), and is currently unused in the Godot Editor, so it would be a good candidate.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
This is already implemented. You can move between gizmos (select, move, rotate, scale) using QWER buttons (changeable) but in Select mode (Q) it does everything is universal gizmo. 
![image](https://user-images.githubusercontent.com/36826319/41438919-e57ec9fe-6ff6-11e8-8e5f-f9992173a576.png)

**Comment by HeadClot** [comment]
Hey,
This probably warrants its own issue but why not replace QWER with one key (Space Bar for example) and have it cycle to the next tool when ever the key is pressed? 

Unreal engine does this and it frees up space on the keyboard for more functions to be assigned else where. Again this probably deserves its own issue.

**Comment by Web-eWorks** [comment]
Unreal Engine keeps the (Q)WER keys for selecting each tool specifically, however. Removing these is very emphatically _not_ a good idea.

The main issue with replacing the keys is that the user's normal workflow would change from one key press = mode change (which can be - and is - muscle memory accelerated,) to 1-3 three key presses, which also looses any advantage of muscle memory, because the key _doesn't_ have a consistent behavior.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@HeadClot  why not simply change them in Shortcuts?

**Comment by DevMagicLord** [comment]
The universal gizmo is already available.
