### ISSUE TITLE
Inspector does not remember scroll position of edited object

### ISSUE THREAD

**Issue by jkb0o** [godotengine/godot#19582]
**Godot version:**

Build from master, 4da6216

**Issue description:**

When I switch between edited objects editor scroll keep position of last edited object. This is especially annoying when I edit resource in separate inspector and then switch back (press back button) to owned node.

**Steps to reproduce:**

Editing resource:
1. Create Button
2. Scroll down to custom_styles
3. Create new StyleBoxFlat
4. Select `edit` from dropdown menu
5. Press `back` (at the top of the inspector dock)
6. You do not even see custom styles properties and need to scroll again.
Excepted:
I expect that in step 6 the position will be exactly the same as before step 4.

Switching between nodes:
1. Create Control node and child Button node
2. Select Button
3. Scroll down to modulate property
4. Select Control
5. Select Button again
6. Scroll position is not at the modulate property
Excepted:
I expect that in step 6 the position will be exactly the same as before step 4.

It would be better if the inspector remembered the position of the scroll for the class, and not for the object. Also remembering position from the bottom would be even better.

**Comment by KoBeWi** [comment]
Fixed in 3.1
