### ISSUE TITLE
OptionButton Font should also affect the Items in dropdown list

### ISSUE THREAD

**Issue by Wend1go** [godotengine/godot#1958]
Changing the font of an OptionButton to one with a bigger size seems to only affect the selected Item displayed inside the OptionButton but not the items in the drop down list.
Choosing the correct item from the OptionButton on a mobile device is mere chance because the items are really tiny.

**Comment by akien-mga** [comment]
Marking this as a bug as it's clearly something that would be expected (especially when you need e.g. a custom font for Unicode characters).

**Comment by reduz** [comment]
can't be fixed as this is a control made of many controls. Easy workaround is editing the theme or doing it by code. Check issue #2379 for more info
