### ISSUE TITLE
WebSocket fragmentation makes connection unusable

### ISSUE THREAD

**Issue by pawilon** [godotengine/godot#19588]
**Godot version:**
Godot built from master @ commit acd9646e (Jun 10th) 

**OS/device including version:**
MacOS High Sierra v 10.13.5

**Issue description:**
I played around with the WebSocket feature implemented by @Faless. I've setup a simple server and a client on localhost. The server will send an rpc message to the client every physics frame (60FPS) and vice versa. A single message has around 450 bytes of data in it, coming to around 512 when all headers are added, so that's just around 30 KBps sent every second by both sides.

Server always sends the data to the client just fine during my tests. However, the client will randomly decide if the tcp packets should be fragmented or not. If the packets aren't fragmented, the connection works fine. If they do get fragmented, the server will accumulate more and more network delay and the connection becomes too lagged to be useful.

The issue also happens if I disable sending an rpc message from server to the client, so now it's only client sending rpcs. The issue happens for around 50% of connections during my tests.

Correct connection:

![image](https://user-images.githubusercontent.com/16836842/41488173-ada142aa-70eb-11e8-99d3-97bf5abdca3e.png)

Bad connection:

![image](https://user-images.githubusercontent.com/16836842/41488196-c106f68c-70eb-11e8-8f8a-59e153ca751e.png)

Notice the dots next to the selected packet. The dots indicate which packets were used to reassemble the full tcp packet. Each packet has 66 bytes of payload, but I've seen it go as low as 20 bytes on my other project, so it's not constant.

**Steps to reproduce:**
1. Make sure you're using godot compiled with websocket support 
2. Download reproduction project and cd into it from command line
3. Start the server using "\<path to compiled godot\> --server"
4. In another terminal, start the client using "\<path to compiled godot\>"
5. Look at the output from the server. If after 5 seconds you only see messages like "OK - network delay is 0 seconds", do a Ctrl+C on the client and start it again. Repeat until you get an error.
6. On around 50% of tries, the server will accumulate more and more delay, as indicated by messages like "ERROR - observed large network delay of 5 seconds". Observe that the delay gets bigger as time progresses.

**Minimal reproduction project:**
Attaching a reproduction project. The zip also contains the full wireshark captures screenshotted above.

[websocket_fragmentation.zip](https://github.com/godotengine/godot/files/2107423/websocket_fragmentation.zip)

**Comment by pawilon** [comment]
I also just confirmed that the issue also happens on my Ubuntu 18.04 VM, so it's not MacOS specific.

**Comment by Faless** [comment]
Confirmed, I found the problem and I'm working on a fix, thank you so much for spotting this! :+1:

**Comment by pawilon** [comment]
Hey @Faless, can you share what do you think the problem is and if there are maybe any possible workarounds in the meantime?

**Comment by pawilon** [comment]
Gave it a try and now I can see the reproduction project consistently throws the high delay error, however I didn't add any threads as you've suggested, so maybe that's the reason. Before I do, one doubt I have is if it's enough to just add this thread on the server, or will it need to happen on both the client and the server? Because according to http://docs.godotengine.org/en/3.0/getting_started/workflow/export/exporting_for_web.html threads aren't available when exporting for the web, so it won't work on the client. And I guess the web export is the main usecase for websockets :)

**Comment by pawilon** [comment]
Alright, turns out I made some changes to the reproduction project locally which I forgot about :) After reapplying the patch and retesting now I'm getting consistently good results!
