### ISSUE TITLE
Consider flipping Z-axis

### ISSUE THREAD

**Issue by AdityaGupta1** [godotengine/godot#19594]
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
iMac with macOS High Sierra 10.13.2

**Issue description:**
Making a node move according to `Vector3(sin(rotation.y), 0, cos(rotation.y))` moves it in the opposite direction on the X-axis

This is likely because the axes are as such:

```
        -Z
         |
         |
         |
-X ------+------ +X
         |
         |
         |
        +Z
```

when it would make more sense for them to be as such:

```
        +Z
         |
         |
         |
-X ------+------ +X
         |
         |
         |
        -Z
```

This way the Z-axis in 3D space could represent the Y-axis in 2D space. This would be very useful for a 3D bullet-hell project I am working on as I wouldn't have to take the opposite of rotation for bullets and movement.

**Steps to reproduce:**
Place a node in the world and move it around; see which way is positive/negative X/Z

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2107851/test.zip)
This project has only one scene with one cube `MeshInstance` that you can move around

**Comment by akien-mga** [comment]
We're not going to change the whole engine just so that you don't need to use a `-` in a formula, are we? :)

All game engines and frameworks use their own conventions for 3D axes, there's no "better" or "best" way. Godot uses the same convention as OpenGL and Maya: https://twitter.com/freyaholmer/status/644881436982575104

**Comment by AdityaGupta1** [comment]
I never realized there were so many different axis systems in game engines, thanks!
