### ISSUE TITLE
Cursor jumps to beginning on every keypress on text-entry in inspector

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#19597]
**Godot version:** 
78fbf507f

**OS/device including version:**
Windows 10

**Issue description:**
When entering text in inspector, cursor jumps to beginning of text input after any keypress.

![text input broken](https://thumbs.gfycat.com/BriskKindAfricanwilddog-size_restricted.gif)

**Comment by volzhs** [comment]
duplication of #19008
