### ISSUE TITLE
Tooltips flashing in Editor UI on Windows

### ISSUE THREAD

**Issue by jarfil** [godotengine/godot#1959]
There is an annoying bug in the Windows version that makes tooltips in the editor to not show correctly, but instead to constantly flash on and off:

https://youtu.be/oUM-cz9hKq8

Both the 64bit and 32bit versions seem to be affected.

System: Windows 8.1
Version tested: 1.1stable

**Comment by Krzycho666** [comment]
Works fine on Windows 7 Pro with all updates on the board.

**Comment by reduz** [comment]
i think this was fixed long ago

**Comment by Bonkuraazu** [comment]
I'm experiencing this issue on windows10 64bit using the 2.0beta. I also tried using the old 1.0stable and the flashing was still there.
