### ISSUE TITLE
Lightmap Baking hangs at "Plotting Meshes" then fills the RAM up until Godot crashes.

### ISSUE THREAD

**Issue by CheesecakeCG** [godotengine/godot#19604]
**Godot version:** 3.0.3

**OS/device including version:**

- Pop_OS! (Ubuntu 17.10)
- 8GB of DDR3 (~60% usage)
- 2GB of Swapfile
- i3-2100
- Nvidia GT610 1GB
- 390.25 (Latest drivers for the card AFAIK)

**Issue description:**
The Godot locks up at "Plotting Meshes: (1/1)" and causes Godot to use up all of the system memory without spilling over into the SWAP file, then crashes. VRAM is also unaffected. It also maxes out a single core while it's running. 3.0 Beta 2 is able to bake the lightmap properly in the same project, all later builds do not work.

**Steps to reproduce:**
Attempt to bake a lightmap.

**Minimal reproduction project:** [borked.zip](https://github.com/godotengine/godot/files/2108481/borked.zip)

**Comment by reduz** [comment]
this is expected unfortunately given current approach, use a bigger cell size. Baker will be rewritten in 3.2 to use a better technique.

**Comment by CheesecakeCG** [comment]
Alright, thanks!

**Comment by CheesecakeCG** [comment]
This PR should have made this irrelevant, so I went ahead and closed this. https://github.com/godotengine/godot/pull/38386
