### ISSUE TITLE
Item List Editor improvements

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#19606]
Item List Editor used to edit items of MenuButton should deserve some attention as in current state, I would rather use code. The biggest issue is that we aren't able to reorder items so any future change is impossible without deleting items and adding them back. Here are my ideas how to improve the editor. Feel free to suggest more.

- [ ] Drag & Drop support *1
- [ ] Collapsable items *2
- [ ] Selection aware Add button *3
- [ ] Item naming *4
- [ ] Deleting selected item by Delete key
- [ ] Populated items from code in tool mode can leak to scene (TODO - create a bug)

1. User is able to reorder items by drag & drop
2. Items can be collapsed in order to save space. When editor is opened, all items are collapsed. When new item is added, it's uncollapsed.
3. When Add button is used, new item is added under the selected item. Not at the end of the list.
4. Items can be named so the user knows what is what when all items are collapsed. Names are only hints in editor with no relation to PopupMenu API. Another option is to add content of text property next to the id.

**Comment by homchom** [comment]
The Item List Editor also appears to not be able to add submenu items (like with the `add_submenu_item` method). Maybe this should be added as well?

**Comment by EricEzaM** [comment]
The current implementation uses an `EditorInspector` to show the item list. This makes it difficult to add custom functionality as described in this issue.

Points 1 and 3: D&D: `EditorInspector` is not designed to drag and drop groups or sections, nor select them as far as I can tell.
Point 2: Very easy. `EditorInspector` supports folding so this is literally one line of code.
Point 4: Again, the implementation is heavily tied to `EditorInspector`. The naming of categories and groups is tied to the property definitions and not their values from what I can tell.

I feel to do this it would need to drop the usage of `EditorInspector`. Modifying it to include the desired functionality would be possible, but it is already a big class and this functionality would not be needed in other places it is used.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/368, https://github.com/godotengine/godot-proposals/issues/1975, https://github.com/godotengine/godot-proposals/issues/2355 and https://github.com/godotengine/godot-proposals/issues/2356, as feature proposals are now tracked on the Godot proposals repository.
