### ISSUE TITLE
RigidBody2D pushing KinematicBody2D when hit from a certain angle and using move_and_collide

### ISSUE THREAD

**Issue by emalamela** [godotengine/godot#19619]
**Godot version:**

3.0.2, 3.0.3

**OS:**

Ubuntu 16.04

**Issue description:**

A `RigidBody2D` (Ball), with a child `CircleShape2D`, manages to push a `KinematicBody2D` (Palette), with a child `CapsuleShape2D`, when it hits the bottom-right corner of the Palette while being moved with `move_and_collide`.

The Ball is moving upwards by setting its `linear_velocity` to `(0, -400)` and the Palette is being moved downwards by calling `move_and_collide(Vector2(0.0, 100 * delta))` in `_physics_process(delta)`.

Additionally, other relevant properties of the Ball where changed:

* Gravity Scale was set to 0.
* Friction was set to 0.
* Bounce was set to 1.

The expected result was the ball just bouncing off towards the down-right diagonal direction. The result was:

* The Palette being displaced in the X axis towards the left side, but keeping its downward movement.
* The Ball bouncing off towards the top-right diagonal direction with its velocity reduced.

I believe this is a bug since the Docs state that [***A KinematicBody2D can be affected by gravity and other forces, but you must calculate the movement in code. The physics engine will not move a KinematicBody2D***](http://docs.godotengine.org/en/latest/tutorials/physics/using_kinematic_body_2d.html#what-is-a-kinematic-body).

**Steps to reproduce:**

1. Open ***Minimal Reproduction Project*** in any of the reported ***Godot Versions***.
2. Play the Project and watch the effect.

**Minimal reproduction project:**

[CollisionBug.zip](https://github.com/godotengine/godot/files/2109595/CollisionBug.zip)

**Experiments:**

* Instead of setting the Ball's `linear_velocity` manually i called `apply_impulse` in `_ready`. Yielded the same result. Just wanted to make sure this wasn't something of the kind "don't set properties manually, apply forces instead" type of issue.
* Lower the Ball's `mass` to minimum. Yielded the same result.
* Replace the Palette's collision shape with a `RectangleShape2D`. This led to the ball continually pushing the Palette in upwards direction which i believe isn't intended behavior either.
* Changing the Ball's `continous_cd` property to ***Cast Shape*** which fixed the issue. However, bumping the speed of both the Ball and the Palette made it reappear. **This leads me to believe that maybe this isn't exactly a bug but an implementation limit of the physics engine when dealing with high speed objects**. If this is indeed the case, should we document this interaction somewhere?

**Comment by eon-s** [comment]
The issue here is that you are using move_and_collide, when the ball s too close, the separation makes the capsule try to avoid the rigid, the only option on Godot 3.0 is to use a children KB to collide with the ball.

Godot 3.1 applied some inertia settings that allow the KB to ignore the rigids so is solved there.

**Comment by emalamela** [comment]
Indeed, if i don't `move_and_collide` the Palette this doesn't happen.

I will keep the test project to check the behavior when 3.1 is released.

Should we close or archive the issue?

**Comment by eon-s** [comment]
Not sure if close, but probably, the fix breaks compatibility so I guess it cannot be picked for 3.0
Is #16757

**Comment by akien-mga** [comment]
Fixed by #16757 as per above comment.
