### ISSUE TITLE
glTF default roughnessFactor should be 1

### ISSUE THREAD

**Issue by bkmeneguello** [godotengine/godot#19613]
Accordingly to **glTF** [specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughness), default `roughnessFactor` should be **1**, but [currently](https://github.com/godotengine/godot/blob/a74e1514206af1b8456ece2cf009b841b86b72f1/editor/import/editor_scene_importer_gltf.cpp#L1264), it's not being set, so, it defaults to **0**.

**Comment by bkmeneguello** [comment]
I didn't compare the other attributes with the spec, only found this by accident.

**Comment by Keetz** [comment]
Maybe related to #10160
Though the conclusion in that issue was to have it at 0 :smile:

**Comment by bkmeneguello** [comment]
@Keetz, I think it's not related. I noticed the glTF importer is leaving the roughness value of material with the default value when it's not set on ".gltf" file. But glTF spec says the default value should be **1**, while Godot's default value is **0**. It means Godot's glTF importer must force roughness to **1** when the file omits its value. I'm not suggesting to change the Godot's default material roughness value.

**Comment by rodolforg** [comment]
I can assure that [metallic factor should default to 1](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessmetallicfactor) too, but it is wrongly 0 by default after import.
