### ISSUE TITLE
GDScript: Rename TCP_Server to TCPServer

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#19623]
It's the only class using an underscore in the name and sticks out like a sore thumb: http://docs.godotengine.org/en/latest/classes/index.html

**Comment by akien-mga** [comment]
> It's the only class using an underscore in the name 

There's `IP_Unix` too.

**Comment by akien-mga** [comment]
Can't happen before next planned compatibility breakage, moved to the tracker.
