### ISSUE TITLE
My wish list

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#19629]
Ok, I want to create my list of things I wanna see in Godot. Im not posting something unnatural like "make engine behavior close to Unreal Engine 4", I concentrated on common things which is currently required for my development

- [ ] Fullscreen resolution changing - Currently it is not possible without app restart, any modern game engine have this feature and Godot should have it too. Related #14542
- [ ] Interprocess communication(through pipes on stdin/stdout) - Yes, maybe its too specific but its required for chess games I like to make, and currently not possible in GDScript(thankfully through C# it can be maked)
- [ ] More options for random - There is already a bunch of proposed PR about it, but main devs (for some reason) does not accept them into engine (which is sad in my opinion)
- [ ] Update code base at least to C++11 and it will be great for all(developers especially)

**Comment by LikeLakers2** [comment]
In regards to updating the codebase to C++11, #9694. Doesn't mean it won't happen, just don't expect it to.

**Comment by reduz** [comment]
> Fullscreen resolution changing - Currently it is not possible without app restart, any modern game engine have this feature and Godot should have it too.

You don't really need it, just use viewport resize mode.

> Interprocess communication(through pipes on stdin/stdout) - Yes, maybe its too specific but its required for chess games I like to make, and currently not possible in GDScript

This sure is possible, just use regular TCP. Stdin/stdout/pipes is just a terrible way to do this.

> There is already a bunch of proposed PR 

This is in discussion, but In mose cases you don't really need this.

> Update code base at least to C++11 and it will be great for all(developers especially)

This is being discussed. If it happens, we will still ensure a very strict C++11 usage, so it won't change that much from current codebase anyway.

Nothing here is useful or new, so closing.

**Comment by Chaosus** [comment]
@reduz Thanks for response, I will research the possibility of fullscreen changing and tcp connection...
