### ISSUE TITLE
Getting system time in milli or micro seconds

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#19636]
**Godot version:**

3.1.dev

**OS/device including version:**

not related

**Issue description:**

we have `OS.get_system_time_secs()` for getting system time in seconds.
but no method for milli or micro seconds.
this is needed when making a game requires more precise time without game server but can be continue to play after quit and re-run.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zylann** [comment]
:) https://github.com/godotengine/godot/pull/19612

**Comment by volzhs** [comment]
@Zylann no. it's usec since game starts.
I need system time in milli or micro seconds.
