### ISSUE TITLE
Shadows get clipped in exported (non-debug) 3D project

### ISSUE THREAD

**Issue by Dogpot** [godotengine/godot#19633]
**Godot version:**

v3.0.3.stable.official.e649ec7, x64

**OS/device including version:**

Windows 10 Home x64, version 10.0.17134 (1803)
Nvidia GTX 1080, driver version 388.59

**Issue description:**

![shadow_export_bug](https://user-images.githubusercontent.com/40367965/41556001-17557858-7342-11e8-97b7-56d729ba6b3d.jpg)
Shadows work as expected when the game is run from the editor, but shadows in the exported version get clipped like in the above screenshot. Exporting with debug on works fine, disabling debug produces the above effect.

**Steps to reproduce:**
1) Open project
2) Export a runnable executable using a default Windows desktop template (DEBUG OFF)
3) Run the executable
4) Move camera to examine the issue (WASD to move, QE to rotate, wheel to zoom)

**Minimal reproduction project:**

[ShadowExport.zip](https://github.com/godotengine/godot/files/2112586/ShadowExport.zip)

**Comment by pgruenbacher** [comment]
the clipping moves with the camera?

**Comment by securas** [comment]
I've also observed this on windows, nvidia, GLES3. But it didnot happen on GLES2

![image](https://user-images.githubusercontent.com/2881755/51216066-731ab700-1966-11e9-8888-6d7a80069ece.png)

**Comment by securas** [comment]
Another note... This happens if the camera is far away enough from the nodes on screen.

**Comment by Dogpot** [comment]
You can adjust the PSSM splits to "fix" the issue, but that still doesn't explain the debug/release thing. Default splits on that minimal project, btw.

**Comment by aurodev** [comment]
> 
> 
> You can adjust the PSSM splits to "fix" the issue, but that still doesn't explain the debug/release thing. Default splits on that minimal project, btw.

You are right @Dogpot Debug and Release need to be identical or you have to export to see changes for release? Kind of interrupts the workflow.

**Comment by reduz** [comment]
This was not assigned to me for some reason, must have skipped it when i went through the issues some months ago, it's now on my list for 3.1

**Comment by reduz** [comment]
This actually seems like a weird gcc compiler bug, @hpvb is investigating..
