### ISSUE TITLE
custom class inheritance/constructor incomplete documentation

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#19644]
![image](https://user-images.githubusercontent.com/1177508/41595532-6546b344-73c7-11e8-87f3-7a9342ae6fa8.png)

There are multiple combinations of `_init` defined in inheriting & inherited classes that work/don't work and I tried documenting them in the attached project.

Open `States/State.gd` and `States/Idle.gd` and the attached script to `DBG` node and play with commenting/uncommenting the relevant parts

[godot-dbg.zip](https://github.com/godotengine/godot/files/2115083/godot-dbg.zip)

**Comment by vnen** [comment]
This is not really a bug. If you inherit the class, you need to define `_init` again and send the needed arguments to the parent class. That is:

```gdscript
# State.gd
var entity
func _init(e = null):
	entity = e

# Idle.gd
extends "State.gd"
func _init(e = null).(e):
	pass

# DBG
const Idle = preload("res://States/Idle.gd")
func _ready():
	var s = Idle.new(1)
```

See #3387 and #2193.

**Comment by razvanc-r** [comment]
That makes a lot of sense, it needs to be better explained in the docs, cause the only entry about `_init` and inheritance (that I saw at least) is

```gdscript
func _init(args).(parent_args):
    pass
```

And it isn't clear that `args` can be sent through `parent_args`. In fact I though that `parent_args` can be only literals in this context.

I'm gonna keep this issue open for the docs.
