### ISSUE TITLE
KinematicBody movement does not wake RigidBody

### ISSUE THREAD

**Issue by rodolforg** [godotengine/godot#19640]
**Godot version:**
3.0.3

**OS/device including version:**
Linux (Debian testing)

**Issue description:**
If a `RigidBody` sleeps, it is not awaken by a collision with a `KinematicBody`.

**Steps to reproduce:**
Just open test project and exec the single scene.
The `RigidBody` prints out when it sleeps and when it awakes.
It falls and after a short time it sleeps.
A kinematic body is moving to left in a collision route. It slides through it but does not make him awake.
I've also tried with cube mesh for the rigid body.

The doc describing [RigidBody::can_sleep](http://docs.godotengine.org/en/3.0/classes/class_rigidbody.html#member-variables) member says that it should awake on collision. Or KinematicBody does not apply forces?

**Minimal reproduction project:**

[physics-test.zip](https://github.com/godotengine/godot/files/2113605/physics-test.zip)

**Comment by eon-s** [comment]
Looks like a duplicate of #13148 which was fixed by #16757 for 3.1.

This may be a won't fix for 3.0, a workaround can be to register the collision with the body and wake it up/push manually.

**Comment by rodolforg** [comment]
Indeed. I tested and it is solved in master branch.

Sorry I couldn't find this issue and the pull request before.
