### ISSUE TITLE
tree_exited signal emitted *before* the node actually exits the tree

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#19641]
Was having some issues when deleting nodes (dying enemies) in a turn based game and I found that `tree_exited` signal lies. It advertises itself as being triggered after the node is no longer in the tree, but that's not the case. Check the example project, there's 3 children to begin with under the main node.

```gdscript
extends Node

func _ready():
    $N01.queue_free()
    print("before ", get_child_count()) # returns 3
    yield($N01,"tree_exited")
    print("after ", get_child_count()) # returns 3
    yield(get_tree(), "idle_frame")
    print("after idle ", get_child_count()) # returns 2
	

func _on_timeout():
    print("timeout ", get_child_count()) # returns 2
```

Used
![image](https://user-images.githubusercontent.com/1177508/41580939-2013aa04-739d-11e8-92b2-33f01bcfbb75.png)
By the way, we should have that text in `About` selectable or have a `Copy Version` button or something like that for easy copy/paste here.

[godot-dbg.zip](https://github.com/godotengine/godot/files/2114113/godot-dbg.zip)

**Comment by razvanc-r** [comment]
@akien-mga well I don't know what the discussion is for, cause there's already a `tree_exiting` which gets triggered before the node exists the tree so that part is covered
