### ISSUE TITLE
Navigation2D results rotate with object

### ISSUE THREAD

**Issue by JohnGabrielUK** [godotengine/godot#19647]
**Godot version:**
3.0.3

**OS/device including version:**
Windows 10 x64

**Issue description:**
The points returned by get_simple_path rotate with the object.

Demonstration: https://gfycat.com/FondNegativeGrouse

**Steps to reproduce:**
Make an object, get a path, rotate object.

**Minimal reproduction project:**
[Tests.zip](https://github.com/godotengine/godot/files/2115431/Tests.zip)

**Comment by volzhs** [comment]
you just draw a path on `KinematicBody2D` object and rotating it.
I don't think this is a bug.

**Comment by volzhs** [comment]
you just draw it on a wrong rotating object.
did you try to move it along the `path`?

**Comment by JohnGabrielUK** [comment]
Yes, but if it's rotated, the path that it follows is too. So say the KinematicBody2D is a zombie moving towards a goal, rotating the zombie to face towards the goal will have the path move, and the zombie will be stuck walking in circles.

**Comment by volzhs** [comment]
Here is `Seeker.gd` for test.

```gdscript
extends KinematicBody2D

export (NodePath) var path_target
export (NodePath) var path_nav
export (NodePath) var path_label
onready var target = get_node(path_target)
onready var nav = get_node(path_nav)
onready var label = get_node(path_label)

var path
export(float) var CHARACTER_SPEED = 100.0

func _ready():
	path = nav.get_simple_path(global_position, target.global_position, false)

func _draw():
	var last_point = global_position
	if path.size() > 1:
		for p in path:
			draw_line(last_point - global_position, p - global_position, Color(1, 0, 0), 2, true)
			last_point = p

func _physics_process(delta):
	#var next_point = path[1] - global_position
	rotation += delta
	label.text = "Rotation: " + str(int(rotation_degrees) % 360)
	
	var walk_distance = CHARACTER_SPEED * delta
	move_along_path(walk_distance)

func move_along_path(distance):
	var last_point = position
	for index in range(path.size()):
		var distance_between_points = last_point.distance_to(path[0])
		# the position to move to falls between two points
		if distance <= distance_between_points and distance >= 0.0:
			position = last_point.linear_interpolate(path[0], distance / distance_between_points)
			break
		# the character reached the end of the path
		elif distance < 0.0:
			position = path[0]
			set_process(false)
			break
		distance -= distance_between_points
		last_point = path[0]
		path.remove(0)
```

![peek 2018-06-20 00-06](https://user-images.githubusercontent.com/8281454/41606127-ec4d1210-741d-11e8-9996-af7f122ba5fc.gif)

as you can see, it follows the `path` no matter how much rotated.

**Comment by JohnGabrielUK** [comment]
Huh. My apologies.
