### ISSUE TITLE
Update wiki documentation about -export CLI switch

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#1964]
There are some bits of documentation here about the -export switch that can be used to export a project directly from the command line: https://github.com/okamstudio/godot/wiki/command_line#exporting

Two things that could be improved:
* ```-export Windows``` does not work actually. The expected target name is ```Windows Desktop```. As for the other targets, they are not easy to guess, so they should probably be documented too (or you could say that the exact same name should be used as in the export GUI, i.e. "Linux X11", "Mac OSX", etc.).
* In "The version of Godot that is headless (no video) is ideal for this.", it would be nice to specify that the headless version of godot is actually the "server" version.

**Comment by akien-mga** [comment]
Regarding the first point, it would also be really nice if there was a command line switch to get a list of all available export targets (e.g. ```godot --list-export-targets```).

**Comment by akien-mga** [comment]
@est31 Do you want to handle this one as you have been working on it?

**Comment by est31** [comment]
@akien-mga I can't edit the wiki.

**Comment by akien-mga** [comment]
Too bad, I'll have to do it :)

**Comment by akien-mga** [comment]
Fixed in http://godotengine.org/projects/godot-engine/wiki/Command_line_tutorial#Exporting
