### ISSUE TITLE
Mouse position offset in W10

### ISSUE THREAD

**Issue by j0z** [godotengine/godot#1965]
The mouse pointer appears to be above the actual click point. In other words, I have to put the mouse about 10-20px above the button/ui element I want to press to actually click it. 

Spec details:

W10 10122
2 monitors, 1440p and 1680x1050, no scaling, both have the issue.

**Comment by punto-** [comment]
does it change if you maximize the window or if you launch in full screen
mode? (or even if you switch to fullscreen mode while running, you can use
the window manager demo)

**Comment by kiwimonk** [comment]
![godot issue](https://cloud.githubusercontent.com/assets/384529/7783661/de970b1c-00e4-11e5-9ef6-0a60ad5ac457.png)

The mouse offset appears to be related to the black border seen at the top and left hand side of each window. (As seen in the screenshot)

**Comment by j0z** [comment]
@punto- no, it doesn't seem to be affected by window resizing. But going full screen with the window management demo does fix it.
And kiwimonk is right, the black borders seem to be directly linked to the issue.

**Comment by DanHot** [comment]
I had this issue with build 10122. I've just tried build 10130 and it seems to be resolved.

**Comment by akien-mga** [comment]
Assuming fixed as per the above comment.
