### ISSUE TITLE
AStar: cannot remove points connection when was connected more than once

### ISSUE THREAD

**Issue by sloneczko** [godotengine/godot#19656]
**Godot version:**
3.0.3 stable

**OS/device including version:**
Arch Linux x86_64

**Issue description:**
When method _connect_points_ is invoked more than once for the same points, then I cannot disonnect them.
```GDScript
#for debug used method get_point_connections(1) are_points_connected(1,2)
astar.connect_points(1,2, true) #connections: [2], connected: True
astar.connect_points(1,2, true) #connections: [2, 2], connected: True
astar.disconnect_points(1,2) #connections: [2], connected: False
astar.disconnect_points(1,2) #connections: [2], connected: False
```
_get_path_ treats nodes as connected

**Comment by MetaSaval** [comment]
I believe I can handle this one. I've been looking for a good beginner issue. While the second solution seems the most simple, I'm interested to see if I can make the first one work. I'm thinking of adding an  `std::find` call to the `neighbors` vector at the beginning of the `AStar::connect_points` function. If it finds `p_with_id`, I'll add an `ERR_FAIL_COND`. Sound like a good start?

**Comment by MetaSaval** [comment]
Took a look at the code and realized that the vector class includes a find function. Added the following line below the initilization for points a and b.

`ERR_FAIL_COND(a->neighbours.find(b, 0) != -1);`

If I understand the find function correctly, it returns a -1 if it doesn't find the value in the vector. This should cause an error if it doesn't find point b as a neighbour of point a. Going to build and test this tomorrow.

**Comment by bojidar-bg** [comment]
@MetaSaval TBH, I would prefer the second version as long as it doesn't cause performance problems.

About the other two solutions, you should be careful with the bi-directional parameter. Consider:
```gdscript
command  # expected state after
# Case 1:
astar.connect_points(1, 2) # 1 -> 2
astar.connect_points(2, 1) # 1 -> 2, 2 -> 1
# Case 2:
astar.connect_points(1, 2) # 1 -> 2
astar.connect_points(1, 2, true) # 1 -> 2, 2 -> 1, no errors
# Case 3:
astar.connect_points(1, 2) # 1 -> 2
astar.connect_points(2, 1, true) # 1 -> 2, 2 -> 1, none duplicated
```

I would suggest not raising errors, but just putting a check around each `neighbours.push_back` call.

**Comment by MetaSaval** [comment]
Makes sense. Was able to make `neighbours` a `set`, but there's a few places in `a_star` that need to be updated. More specifically, there's a few places where `a_star` iterates through `neighbours` with a for loop, which break because a `set`doesn't have access by index. As far as I can tell, there's no iterator class for me to use, and the `set` class only has a `find` function, which doesn't really help. Any idea on where to go from here? And how would I check to see if this change ends up causing performance problems?

**Comment by bojidar-bg** [comment]
I think something like this loop might do the trick:
https://github.com/godotengine/godot/blob/d6ddfdf004a1b5a334a0709e87e2e427624e616b/editor/plugins/theme_editor_plugin.cpp#L276
(sorry for not replying earlier)

**Comment by MetaSaval** [comment]
Sweet, that worked. I was able to make the changes. Committing now.

With the test script:

`	var as = AStar.new()
	
	as.add_point(1, Vector3(1,0,0), 4)
	as.add_point(2, Vector3(2,0,0), 4)
	
	as.connect_points(1,2, true)
	print(as.are_points_connected(1,2))
	print(as.get_point_connections(1))
	
	as.connect_points(1,2, true)
	print(as.are_points_connected(1,2))
	print(as.get_point_connections(1))
	
	as.disconnect_points(1,2)
	print(as.are_points_connected(1,2))
	print(as.get_point_connections(1))
	
	as.disconnect_points(1,2)
	print(as.are_points_connected(1,2))
	print(as.get_point_connections(1))
	
	print(as.get_point_path(1,2))`

I got the following output:

`
True
[2]
True
[2]
False
[]
False
[]
[]
`
