### ISSUE TITLE
changing WorldEnvironment and shader in new inspector do not effect the running

### ISSUE THREAD

**Issue by jhch3** [godotengine/godot#19664]
**Godot version:**

3

**OS/device including version:**

manjaro
win10

**Issue description:**

![]( https://raw.githubusercontent.com/aron3097/issueImg/master/new_inspector/2018-06-20_14-15-33.png )
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Can you still reproduce this in the current master branch / 3.1 beta 3?

**Comment by KoBeWi** [comment]
The issue lacks details and response, so closing.
If someone can reproduce it in Godot 3.2.1 or newer, this can be reopened.
