### ISSUE TITLE
Fedora out-of-date package

### ISSUE THREAD

**Issue by AllanDaemon** [godotengine/godot#19661]
Fedora packages is not updated to latest Godot stable version 3.0.3.

@akien-mga  is listed as the packager:
https://apps.fedoraproject.org/packages/godot/sources/

**Comment by akien-mga** [comment]
Duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1591994. Downstream package requests should be made downstream ;)

**Comment by akien-mga** [comment]
Updated candidate pushed for Fedora 27 and 28, EPEL7 pending:

- https://bodhi.fedoraproject.org/updates/godot-3.0.3-1.fc27
- https://bodhi.fedoraproject.org/updates/godot-3.0.3-1.fc28

If you can help test it and give karma if it works, that would speed up the release to stable.
