### ISSUE TITLE
There should be runtime error when using EditorPlugin in runtime

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#19669]
**Godot version:**
3.0.3

**Issue description:**
Since EditorPlugin can't be used in non-tools builds, there should be a runtime error in the editor when running a game using it. Not having this error can lead to potentially hard to debug problems on user ends when releasing the game (coming from #19649)

**Steps to reproduce:**
1. Create main scene of the project with a script
2.  Add such code in script ready function:
```
editorPlugin = EditorPlugin.new();
add_child(editorPlugin);
```
3. Run the scene, observe that there is no indication that something is not right

**Comment by Zylann** [comment]
Note: it sounds like we could do a check for any editor-specific classes, however that's not always possible in case the plugin comes with debugging capabilities (which would require access to editor-only classes).

**Comment by Calinou** [comment]
Running the snippet gives the following error messages in Godot 3.2.1, so I'll consider this resolved.

![image](https://user-images.githubusercontent.com/180032/85112677-48492800-b216-11ea-8905-f9eca262369b.png)
