### ISSUE TITLE
The display of modulate keys in the animation timeline

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#19666]
**Godot version:**

76875ba

**Issue description:**

In the image below the scale and modulate keyframes are both keyframed at 0 and 1 respectively.

![colorkeyswrong](https://user-images.githubusercontent.com/15687516/41644689-1be8356c-746f-11e8-82a7-928febc4318b.png)

The animation timeline displays keyframed modulate values as large square boxes that are placed in front of the blue playhead line. This defies convention of current keyframes being in the middle of the playheadline. Keyframes at the same point in time  should line up and not be offset.

I propose something like this with keyframes lined up and of the same size. Easier to understand at a glance and easier to work with.

![colorkeysright](https://user-images.githubusercontent.com/15687516/41645173-75ecdb3e-7470-11e8-8bee-0ce525af6155.png)

**Comment by PullTheStrings** [comment]
I would argue that the colour and opacity displayed by the keyframe mainly serves as a reference and that any slight change in opacity would not be percieved either way. The prime reason for an animation timeline is working with keyframes and where they are in relation to each other. Having a larger square offset keyframe for modulate runs counter to that goal.

**Comment by KoBeWi** [comment]
The modulate keys are still square, but are now centered
![image](https://user-images.githubusercontent.com/2223172/64463874-e6478800-d105-11e9-8fdf-1c88fbc313f8.png)

@PullTheStrings Is that good enough to close this?

**Comment by PullTheStrings** [comment]
Looks good to me. I must admit that I have grown fond of the squares they provide a good reference. Centering them just makes them better. Thanks!
