### ISSUE TITLE
Tween follow_property/method return Nan on the last frame

### ISSUE THREAD

**Issue by maksloboda** [godotengine/godot#19679]
**Godot version: 3.0, 3.0.2 and a9acdd84b7a6fd074f21d500a64976326f6cbb67**

**OS/device including version: Ubuntu 64 bit**

**Issue description:**
follow_property and follow_method at the last frame set node's position to (0,0)

**Steps to reproduce:**
1. Your project **HAS** to be **EXPORTED** as with **DEBUGGING OFF**
2. Call "follow_property" on a tween interpolating node's position (I only tested with Vector2)
3. Let it playout till the end
4. Notice that node's position at the last frame teleports to (0,0)

It also works if you do it with "follow_method".
That way i figured out that in the last frame it gives NAN

**Minimal reproduction project:**
WARNING: this project was opened by the 3.1 so 3.0.* cant open it
[TweenBug.zip](https://github.com/godotengine/godot/files/2120681/TweenBug.zip)

**Comment by reduz** [comment]
This may be compiler specific and/or related to the other Vector2 -> NaN issue we found before? (happened when compiling with clang)

**Comment by maksloboda** [comment]
Retested with 4b6846a59d785af3bef6a29958387ed0ee0f6575 and bug still happends

**Comment by maksloboda** [comment]
Retested with Godot 3.1 beta 2, bug still persists, but i used a different project (its a 3D version of the first one)
[TweenBug.zip](https://github.com/godotengine/godot/files/2787945/TweenBug.zip)
As i said, in editor everything works as intended, but when it is exported in release mode it breaks

**Comment by maksloboda** [comment]
Also tried commit 51c67a3 and bug still appears

**Comment by akien-mga** [comment]
Thanks for testing. I was able to reproduce it with the 3D project and a release build from the current master branch. It doesn't happen all the time so needed to restart the build ~10 times or so to see it the first time (I've only seen it happen in the first few cycles of the tween, hence the need to restart the project).

**Comment by DleanJeans** [comment]
Still occuring on a 3.1 beta 3.
Created a minimal testing project for this: [TweenFollow.zip](https://github.com/godotengine/godot/files/2844785/TweenFollow.zip) in 2D
with shortcuts for tweening, reloading scene and switching between `follow_property` and `follow_method`.

**Comment by maksloboda** [comment]
I leared something recently in Godot 3.1 and 3.1.1. When you use custom method to set position it works fine. Here is an updated project from DleanJeans with that fix included as an option [TweenFollow.zip](https://github.com/godotengine/godot/files/3130655/TweenFollow.zip)

**Comment by akien-mga** [comment]
Fixed by #32951.
