### ISSUE TITLE
EditorScenePostImport not working

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot#19671]
```
tool
extends EditorScenePostImport

func post_import(scene):
	print("HELLO " +str(scene))
	return scene
```

On importing or re-importing a COLLADA model ( .dae), there is no evidence of the function having run.
Nothing is output anything to the stdout window or the output panel, I assume post_import isn't being called.

I'm using Godot build d5bb6fa, but earlier versions have the same problem.

[example.zip](https://github.com/godotengine/godot/files/2119264/testa.gaun.zip)

**Comment by hedgehog90** [comment]
Found part of the problem but am not familiar with Godot source and can't get any further.

In this file:
https://github.com/godotengine/godot/blob/master/editor/import/resource_importer_scene.cpp#L1329

This is always null:
```String post_import_script_path = p_options["nodes/custom_script"]```

It should be pointing to the file extending EditorScenePostImport, but for some reason it isn't registering.

**Comment by hedgehog90** [comment]
I'm currently moving a project from Unity to Godot and this feature is essential.
I'd really appreciate it if someone could look into this.

**Comment by reduz** [comment]
You can set the import settings of a file to be the default, but agree its not very obvious.
This is an enhancement though, and will move to 3.2 as it may not happen in 3.1

**Comment by akien-mga** [comment]
This workflow has been reworked significantly in 4.0 so I think this specific issue might no longer be relevant as is.

If it still is, please comment so we can reopen it and make sure to include a test project that's suitable for 4.0 alpha 1 or later.
