### ISSUE TITLE
GDScript register based interpreter for performance

### ISSUE THREAD

**Issue by yafacex** [godotengine/godot#19688]
I have read gdscript's virtual machine code.It seems that it is stack based.Is it possible to imply it with registers.instead of push value to stack.assign it to a register to reduce push and pop cost.As i know jit is not permitted on ios.I want to write complicated logic at update function.I hope GDScript can be more efficent at runtime

**Comment by vnen** [comment]
A register VM is harder to implement than a stack VM. And I'm not sure if this would improve performance significantly when it's still using an interpreter. Even if it is, I still think it wouldn't be fit for heavy processing.

Sounds like a lot of work for a long shot.

**Comment by OvermindDL1** [comment]
There's some talk about AOT compilation in https://github.com/godotengine/godot/issues/5049 being done at some point.

**Comment by yafacex** [comment]
thanks for your reply.i know cpp is better to rewrite performance sensitive part with.sometimes i am too lazy to do that.lol

**Comment by vnen** [comment]
I know sometimes it needs to be rewritten for better performance and I'm not against it. But you have to measure the performance and find the bottlenecks, otherwise you might spend a lot of time with little results or even make it worse.

**Comment by Calinou** [comment]
I'll close this due to lack of support. There are still plans to optimize GDScript by other means (such as adding typed instructions).

**Comment by tebz** [comment]
I don't believe that a clean register based storage can be implemented if recursion are permitted.
