### ISSUE TITLE
LineEdit not emitting "text_changed" signal (3.0.3)

### ISSUE THREAD

**Issue by naturally-intelligent** [godotengine/godot#19680]
**Godot version:**
3.0.3

**OS/device including version:**
Ubuntu MATE 18.04

**Issue description:**
Not receiving text_changed signal in LineEdit node.  Does work in TextEdit nodes.  Am using focus_exited as a workaround.

**Steps to reproduce:**
Create LineEdit node
Connect text_changed signal
Issue print statement inside signal
Run and change text

**Comment by CloudAlRio** [comment]
As side note, I'm on Windows 10 and it works fine.

**Comment by rodolforg** [comment]
Here on Debian testing, Godot 3.0.3, it works flawlessly.

**Comment by ibrahn** [comment]
I couldn't reproduce this on the 3.0.3 stable release or master (at 80f7eacf88f301567f60f990f2c8dacf7fc96e7e).
Do you have a test project we can look at?

**Comment by naturally-intelligent** [comment]
I took another look at this.  I wasn't adding the text parameter to the callback function, so the function was ignored.  My mistake  :|
