### ISSUE TITLE
Game exits without error if an inexistent subclass constructor is called

### ISSUE THREAD

**Issue by swenner** [godotengine/godot#1968]
BugSquad edit: bug is still present in 2.0 alpha b2f9acb8c96aed0505cbac21661e21e4acef710f
The following script makes the game exit and no error is shown in the dubugger or on the commandline.

```
extends Spatial

class Test:
	func _init():
		pass

func _ready():
	var t = Test.new(1)
```

**Comment by Ciastex** [comment]
Actually, it causes the engine to crash (on Windows, at least, I suppose on *nix it's a segfault).

**Comment by kubecz3k** [comment]
I can confirm this bug on 2.0 Alpha b2f9acb8c96aed0505cbac21661e21e4acef710f build.

**Comment by reduz** [comment]
I'm just getting: 

ERROR: _ready: Invalid call to function 'new' in base 'GDScript'. Expected 0 arguments.

I guess it's fixed
