### ISSUE TITLE
Imported COLLADA file from Mixamo doesn't apply scale in blend shapes

### ISSUE THREAD

**Issue by David-Ochoa** [godotengine/godot#19687]
**Godot version:**
Godot 3 Custom build, [a9acdd8] https://github.com/godotengine/godot/commit/a9acdd84b7a6fd074f21d500a64976326f6cbb67)

**OS/device including version:**
Windows 7, Intel integrated video card

**Issue description:**
Mixamo exported models have an internal scale of 0.01, in Godot if a blend shape is applied this scale is not applied and the results can be seen in this video: [Mixamo to Godot](https://youtu.be/QTyPLQQdrUg)

**Steps to reproduce:**
Create a new project, export attached file to project folder.
Once Godot imports it open as new inhereted scene, select the body mesh and move the blend shapes sliders.

**Minimal reproduction project:**
Attached DAE model, it's a 7z inside a Zip.
[Model.zip](https://github.com/godotengine/godot/files/2121490/Model.zip)

**Comment by vnen** [comment]
Maybe it's related to (or the same as) #12618

**Comment by David-Ochoa** [comment]
I think it's something else because with previous versions it had the visibility problem but with latest code visibility is not an issue. As I mentioned it may be related to the scale Mixamo applies, problem is I can't change that scale. Maybe a smaller example could be more useful, I'll try to make a cube with the same characteristics.

**Comment by David-Ochoa** [comment]
After trying many conbinations I found the culprit: the morph has the value "RELATIVE", changing it to "NORMALIZED" solves the issue. It's maybe my fault, because I'm merging animations AND changing the instanced mesh from the geometry to the morph, that's the way Godot loads the morphs. You can see the results here: [Video](https://youtu.be/06l3ZdORX7I)

I may create a tutorial for importing Fuse characters to Godot because it's not an easy process and I had to create a script to make the mentioned changes.
