### ISSUE TITLE
Various problems with rotating and scaling multiple nodes in 2d

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#19691]
**Godot version:**
current master 3.1 branch

**OS/device including version:**
Win10 960m

**Issue description:**
- Rotation of multiple nodes has been added to 3.1, which is fantastic! However there are some issues with it. By default they rotate around the individual origins. If the origin is moved by holding down v, to create a temporary pivot, this works fine, but permanently changes the individual sprite offsets. See the following gif for an example:

![rotation_bug1a](https://user-images.githubusercontent.com/7741669/41698513-24e9faf8-7562-11e8-831f-050fe15f2d1e.gif)

- Maybe there can be another mode that averages the positions of each mode without having to move the pivot via "V" that can be toggled on, much like in blender? Otherwise the offsets should be reset back to where they were before the multi rotation was performed.

- There should be a similar behaviour to be able to scale a multi selection in 2d interactively in the same manner . As far as I can tell, there is no way to do this in 3.0.3 or 3.1. My current workaround(in 3.0.3) is to parent the nodes under a node2d and rotate/scale the node2d , and then unparent the nodes. A pretty clunky workflow, but it does work!

- Also, there is a bug in 3.1 where if you rotate a 2d node using the rotate mode and snap is off, it performs as expected without any snap. However, if you rotate with select mode by holding  down the ctrl key, it snaps to increments even though snap is turned off.

![rotation_bug1](https://user-images.githubusercontent.com/7741669/41698527-2fac9e5a-7562-11e8-993e-471fa8075d8e.gif)

- Additionally in 3.1 the pivot crosshairs have disappeared on sprites, as can be seen in these gifs.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by volzhs** [comment]
> Also, there is a bug in 3.1 where if you rotate a 2d node using the rotate mode and snap is off, it performs as expected without any snap. However, if you rotate with select mode by holding down the ctrl key, it snaps to increments even though snap is turned off.

I'm suffering same issue. but I found workaround.
dragging with Ctrl hold down is going to kind of "rotate mode".
so, releasing Ctrl key with keeping to drag while it's rotating will enter the no snap rotating mode.
(I'm not sure I explain correctly...)

**Comment by fracteed** [comment]
@volzhs ah yes, just noticed that... you are right. Is this by design? It is actually not too bad when you are aware of this behaviour, but not very intuitive.

**Comment by akien-mga** [comment]
> Also, there is a bug in 3.1 where if you rotate a 2d node using the rotate mode and snap is off, it performs as expected without any snap. However, if you rotate with select mode by holding down the ctrl key, it snaps to increments even though snap is turned off.

The issue is that Ctrl toggles snapping (e.g. in Move mode and Rotate mode), but in Select mode it conflicts with the Ctrl+Drag rotate shortcut, so it ends up being a Rotate + Toggle snapping.

The solution would be to change either of those shortcuts.

**Comment by fracteed** [comment]
@akien-mga I think it is good in theory to have temporary snapping modifier key, as Blender operates the exact same way with ctrl held down. Having the ctrl key operate 2 different functions in the same mode is troublesome. Even if you changed the hotkey for rotate in select mode, you would then have to hold down 2 keys in select mode to rotate and temp snap. The other current problem is that to do a temp snap move in select mode, you have to start moving the object and then hold down ctrl to start snapping.

Personally I would love to see the 2d controls go a similar direction to Inkscape, with a widget for rotating and scaling. It is very clean and intuitive with Inkscape as you add objects to your selection, the widget boundary updates and it is always very obvious what mode you are in without relying on hotkeys. Just clicking on your selection toggles between rotate and scale, and move mode is always active. Using a temp snapping modifier key like ctrl could then easily be added on top of this.

**Comment by groud** [comment]
All of those are enhancements, not bugs.
1) Yeah, the V key set a sprite's pivot, that's not a temporary thing. We could add such a temporary pivot but it's not easy to do. It should be discussed.
2) That would be a solution.
3) That's not a bug. The ctrl key toggles the snapping. I agree it's not the best UX though, but I don't know if there are other solutions than not using the ctrl key for rotating.
4) The pivot crosshair is not visible on multiple nodes as the calculated position cannot be exactly the same due to float computation. It should still be visible when only one node is selected.

What we should do with that should be discussed.

**Comment by fracteed** [comment]
2. Would be great to have this averaged mode if possible. Personally I would find this a better default when rotating multiple selections than having them rotate around their individual origins, which would be used rarely.
3. As mentioned above, I like the idea of a temp snap modifier key, but being able to rotate should take precedence in select mode and there is a conflict there. Maybe alt could be used instead? Then when moving you can hold down alt to snap, as a standard move doesn't actually require it (even though the select tooltip mentions it for some reason). Currently holding ctrl to temp snap in select mode requires you to move first before you hold ctrl, which feels quite odd. This would also enable ctrl/alt to be held simultaneously for a rotate/snap and just ctrl for a normal rotation.

4. in my current build there is no crosshair visible for sprites even with just one selected.

Do you have plans to enable scaling of multiple nodes? Currently I am having to do temporary parenting to a node2d to achieve this.

**Comment by groud** [comment]
> Would be great to have this averaged mode if possible. Personally I would find this a better default when rotating multiple selections than having them rotate around their individual origins, which would be used rarely.

I'm not sure this is true. I someone needs to do so he can use Node2D as a parent and rotate it (and the problem is gone). Both solutions make sense to me. But I agree this is not the most expected behavior.

> As mentioned above, I like the idea of a temp snap modifier key, but being able to rotate should take precedence in select mode and there is a conflict there. Maybe alt could be used instead?

The problem is that it would be inconsistent with the fact that ctrl toggles snapping when moving or scaling. There will be an inconsistency, however the way we do it.

> Do you have plans to enable scaling of multiple nodes? Currently I am having to do temporary parenting to a node2d to achieve this.

Probably someday yeah.

**Comment by jbenman** [comment]
I'm not sure if I understand correctly, so I may have a separate issue or one related to this, but when I change the position of the pivot of a Sprite2D node in 3.1, it also changes the position of any children Sprite2Ds. Furthermore, ctrl-z (or manually selecting undo from the menu) seems to not undo this.
