### ISSUE TITLE
Scene tabs should have a right-click menu: Close, Close All, Close Others

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#19701]
**Godot version:**
3.0.2 stable

**OS/device including version:**
MacBook Air (13-inch, Early 2014) (1,4 GHz Intel Core i5)
MacOS High Sierra 10.13.3

**Issue description:**
When right-clicking the scene tabs (scenes opened in the editor), currently nothing happens. It should show a right-click menu with the usual tab-related options:

- Close Others
- Close Tab
- Close All

**Steps to reproduce:**
1. Have many tabs opened
2. Try to close all the other tabs except the one that is selected

**CURRENT:** It's needed to click on the tab + click on the close button for every opened tab
**EXPECTED:** Right-click the current tab an click Close Others

**Comment by nunodonato** [comment]
Not sure how relevant it would be...

You can use Middle mouse button to quickly close any tab without selecting it first. There's also an option in the editor settings to always display the close button in all tabs.

**Comment by jahd2602** [comment]
@nunodonato  Thanks! I didn't know that and it will surely improve my workflow. However, the menu still needs to be implemented. (Specially because of the Close Others option)

**Comment by starry-abyss** [comment]
Just wanted to create the issue too, but it's already there!

**Comment by Calinou** [comment]
Similarly to Web browsers, we can offer two more buttons: one that will close all other tabs, and one that will only close tabs to the right of the tab that was right-clicked. This way, one can close several scenes at one in a more selective manner.

![Tab contextual menu in Chromium](https://user-images.githubusercontent.com/180032/55172457-60004080-517a-11e9-95d6-66e233ea9bcd.png)
