### ISSUE TITLE
2D Visibility Mask

### ISSUE THREAD

**Issue by DaddySmash** [godotengine/godot#1970]
We tried our hardest to make a 2D visibility mask yesterday, but we had to resort to using scroll boxes instead.

We aren't the only ones who need this feature.  See http://www.godotengine.org/forum/viewtopic.php?f=11&t=1015.   He ended up porting his game to 3D, so he could have a visibility mask.  He also has screenshots detailing the effect.

**Comment by reduz** [comment]
this is really easy to do now in just released 1.1, since there are shaders
for 2D.. and also you can edit them visually

**Comment by Krzycho666** [comment]
How about OpenGL's stencil and scissor test - it's ready to go feature and it's speeding up the game itself.

**Comment by DaddySmash** [comment]
Thanks reduz, I'll look at the 2D shaders next time I need to do a mask.

**Comment by reduz** [comment]
This kind of masks can now be done very easily with lights in Mask mode
