### ISSUE TITLE
[GDNative/C++] _init method of C++ class alters the owner variables in the editor

### ISSUE THREAD

**Issue by lethiandev** [godotengine/godot#19703]
**Godot version:**
3.0.3.stable.official.e649ec7
No-Mono

**OS/device including version:**
Windows 10 x64

**Issue description:**
I'm using gdnative like a generic gdscript in my game, but to my surprise, gdnative works differently than gdscript. The native script changes the values of the owned node by just reopening the scene tab in the editor. I'm not sure if it's an intended workflow of the gdnative.

For now, I have to feed the code by conditional test if the game isn't open in the editor:
```cpp
#define SKIP_ON_EDITOR_HINT \
	if (Engine::is_editor_hint()) { return; }

void TestLabel::_init() {
	SKIP_ON_EDITOR_HINT;
	// (...)
}
```

IMO for the sake of gdscript, native script instantiation in the editor should be reserved for the tool classes only.

Out of curiosity, I checked how mono scripts work, and they work as I expected. The mono constructors are called only in the running game and not in the editor.

**Steps to reproduce:**
- Attach a gdns to a label node
- Reopen the scene tab with the label
- The label have an altered text now

**Minimal reproduction project:**
[gdnative-_init-method-call.zip](https://github.com/godotengine/godot/files/2124359/gdnative-_init-method-call.zip)

Please notice the label change in the GDNativeLabel node at the editor startup.

**Comment by akien-mga** [comment]
Fixed by #27320.
