### ISSUE TITLE
TileMap, TileSet feature proposal

### ISSUE THREAD

**Issue by CloudAlRio** [godotengine/godot#19700]
Current tilemaps and tilesets are very limited in terms of functionality. So, basically, they're not really useful when making grid-based RPG games (quite popular even these days) or similar games. 
 I tried to sort features by implementation difficulty. 

**Main features:**
 - Ability to use AnimatedSprite2D with Sprites. Or Sprites with AnimationPlayers (Usage ex.: water/fire tiles) (Well, they can be animated by changing texture/region from AnimationPlayer...)
 - Support nodes with scripts (can function as trigger). 
 - TileSet as new node type with it's own editor.

**TileSet Editor features:**
 - New Tile node. And ability to generate tiles from Sprites or from spritesheets with given step, offset, separation. (Reusing 'Texture Region' is fine I think).
 - Having all selected tiles visible on region picker would be nice

**Optional features:**
 - Visualize collisions. (Ex: When having invisible wall tiles) 
 - Make grid-based movement easier, i.e. make player node aware of TileMaps existance. Probably would be better to add player node into tileset. (I know this can be easily implemented, but still...)

Well, maybe some of these features are already implemented/being implemented or exist in some other form, but still wanted to write them down, because I couldn't find them. 

There are a lot of feature proposals similar to this, So, I think people would like to see some improvements in this direction.

**Comment by mhilbrunner** [comment]
See also: https://github.com/godotengine/godot/issues/19538

**Comment by swarnimarun** [comment]
> Ability to use AnimatedSprite2D with Sprites. Or Sprites with AnimationPlayers (Usage ex.: water/fire tiles) (Well, they can be animated by changing texture/region from AnimationPlayer...)
> Support nodes with scripts (can function as trigger).

@CloudAlRio Adding the ability to have AnimationPlayer and Scripts per tile will be bad for optimisation, you can merge collision shapes, and sprites and use them as one(or in quadrants) thus having better optimisation than separate tiles. 
So all those thing are become way difficult with optimisations in mind.

On the rest I am with @Zylann.

**Comment by CloudAlRio** [comment]
Why having script on one or few tiles in grid-based game would hurt optimization that much. Also those games do have animated tiles and they don't hurt optimization too much. 
Anyway, closing issue with proposals because they seem to be pointless and bad for optimization.

**Comment by vnen** [comment]
> Why having script on one or few tiles in grid-based game would hurt optimization that much.

It would still have to check every tile to see it has a script or not.

> Also those games do have animated tiles and they don't hurt optimization too much.

**Comment by swarnimarun** [comment]
@CloudAlRio Having anything other than textures will mean bad for optimizations for it will not be consistent thus will have to check each tile for scripts and stuff they will not be bundle together properly then.
And visualising collisions is already there(turn debug collision shapes on), but doesn't work in the Editor(run the game to see the collsions), I don't really know why at the moment.
Should not be impossible to implement.

Overall I like that you tried to put up a good and descriptive proposal here. You seem to have some ideas but just don't seem to know how it could be proposed. 
Try talking to some people on Discord server to help with it and then create a proper one.
