### ISSUE TITLE
Attach script does not work when editing sub-resource

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#19714]
**Godot version:**

3.1.dev

**OS/device including version:**

not related

**Issue description:**

Attaching script does not work when editing it's sub-resource.

1. create a AnimatedSprite (or any node has sub-resource)
2. edit resource
3. try to attach script on that node

it's because selected node is set to NULL from here.
https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L1424

**Steps to reproduce:**
![attach_script](https://user-images.githubusercontent.com/8281454/41761378-0429bd14-7632-11e8-8132-ff35090d9fe8.gif)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Still reproducible in the current master branch.

**Comment by BlackCatter** [comment]
Tools in the `editor/scene_tree_dock.cpp` use different ways to get selected node.

For example attach script tool uses `scene_tree->get_selected()` which returns null while resource editor is open https://github.com/godotengine/godot/blob/e930fb9a6e4277ad3c4dc60a775785b294840512/editor/scene_tree_dock.cpp#L337-L339

But clear script tool uses `editor_selection->get_selected_node_list();` which returns expected node and works while editing resource
https://github.com/godotengine/godot/blob/e930fb9a6e4277ad3c4dc60a775785b294840512/editor/scene_tree_dock.cpp#L374-L376

Is there a hidden logic for this choices of methods? Is it safe to change all calls to `editor_selection->get_selected_node_list();` or another solution is preferred?

**Comment by KoBeWi** [comment]
Likely fixed by #26643 (assuming from above comment)
