### ISSUE TITLE
Project with extra large icon triggers X11 error: BadLength (poly request too large or internal Xlib length error)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#19716]
**Godot version:**
3.0.3-stable and current master branch (80f7eacf)

**OS/device including version:**
Linux (Mageia 6 x86_64) with X11 1.19.5
Nvidia GTX 670MX

**Issue description:**
The Godot jam entry [Meltdown Hydrocooler Force](https://darrell-wulff.itch.io/meltdown-hydrocooler-force) by @DarrellWulff doesn't run on Linux X11 64-bit. The (custom) splash screen is shown, and then freezes on the splash screen with this error in the terminal:
```
OpenGL ES 3.0 Renderer: GeForce GTX 670MX/PCIe/SSE2
Boot splash path: res://DWLogo.png
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Serial number of failed request:  242
  Current serial number in output stream:  242
```

This could be reproduced by another user too: https://itch.io/post/448272

[Source code for the game](https://github.com/DarrellWulff/Meltdown-Hydrocooler-Force-Godot-Game-Jam-) is available, and I could confirm that the same issue happens when running from the source code with both Godot 3.0.3-stable and the current master branch.

**Steps to reproduce:**
- Download https://github.com/DarrellWulff/Meltdown-Hydrocooler-Force-Godot-Game-Jam-
- Open it in the editor to get assets imported
- Try to run the main scene

**Minimal reproduction project:**
See above.

**Comment by akien-mga** [comment]
The issue happens because of this line: https://github.com/DarrellWulff/Meltdown-Hydrocooler-Force-Godot-Game-Jam-/blob/14aaba438560cf9cc1556769529e3946398dec28/project.godot#L18

That project tries to load a 3072x2048 PNG (!) as project icon (!!), which X11 likely doesn't like: https://raw.githubusercontent.com/DarrellWulff/Meltdown-Hydrocooler-Force-Godot-Game-Jam-/master/UI/MainTitle.png

We likely need to add some icon validation logic on X11 to prevent such issues (might also be relevant on other platforms).

**Comment by hpvb** [comment]
Hmm, yeah, I don't think this *should* work, but we obviously also shouldn't just crash. I'll try to fix this.
