### ISSUE TITLE
NodePath property assignment for inspected resource crashes editor

### ISSUE THREAD

**Issue by lchew** [godotengine/godot#19712]
**Godot version:**
v3.1.dev.calinou.a9acdd8

**OS/device including version:**
Windows 10

**Issue description:**
Editor will crash when selecting a node for a NodePath property in an inspected resource. Possible to see this in AnimationPlayer when using a call func track and creating a key that takes a NodePath as a parameter. Not specific to AnimationPlayer since also producible in other inspected resources.

**Steps to reproduce:**
- create a call func track in AnimationPlayer
- create a key that takes a NodePath as a parameter
- click on the key to inspect the AnimationTrackKeyEdit in the property inspector
- try assigning a node to the arg in the property inspector
![nodepathbug](https://user-images.githubusercontent.com/5759274/41758052-dfb3dcc2-759a-11e8-8188-c20226ec654a.png)

**Minimal reproduction project:**

[NodePathBug.zip](https://github.com/godotengine/godot/files/2126311/NodePathBug.zip)

**Comment by m4nu3lf** [comment]
Not sure the issue i created (#19746) is a duplicate as I don't get a crash. Just a 'node not found'
