### ISSUE TITLE
RidigBody2D in Character Mode stucks at tiles corners and between 2 tiles (regression since 3.0.2)

### ISSUE THREAD

**Issue by jeremi360** [godotengine/godot#19715]
**Godot version:**
3.0.2 and 3.0.3

**OS/device including version:**
Linux Mint 19 x64

**Issue description:**
In my title map platformer hero get stuck on titles corners and between them :(
I use RigidBody in Character Mode.
The code and title in previous version works fine.
![peek 2018-06-21 18-39](https://user-images.githubusercontent.com/1294815/41763168-abf89914-75fd-11e8-8abc-c862749e8998.gif)

**Steps to reproduce:**
Just run project and try to move hero using left, right and up (jump) arrows

**Minimal reproduction project:**
[Platfromer 2D.zip](https://github.com/godotengine/godot/files/2129056/Platfromer.2D.zip)

**Comment by akien-mga** [comment]
>  The code and title in previous version works fine.

What previous version exactly? As I understand it the issue is reproducible in both 3.0.2 and 3.0.3?

**Comment by jeremi360** [comment]
@akien-mga  it works correctly 3.0.0 and 3.0.1. Yes, issue is reproducible in both 3.0.2 and 3.0.3.

**Comment by girng** [comment]
couple things:
this was over 150mb in download for a zip, please try to reduce example projects  

second:
player's collision ship was scaled

third:
```
	if y > 0 and ray.is_colliding():
		$AnimationTreePlayer.oneshot_node_start("land")
```

removing this inside `_process` fixed everything. bug is related to `oneshot_node_start`

**Comment by jeremi360** [comment]
Thanks @girng , I will try reduce size and fix scale

**Comment by jeremi360** [comment]
@girng I comment out this to lines and result is the same :(

**Comment by girng** [comment]
@jeremi360 try a capsule shape instead of a rectangle for player body  collision

**Comment by jeremi360** [comment]
I change collision shape to capsule and now it's working

**Comment by girng** [comment]
@jeremi360 glad you got it fixed sir!
