### ISSUE TITLE
Get scene node from VisualScriptCustomNodes

### ISSUE THREAD

**Issue by mishapsi** [godotengine/godot#19725]
As the title says, I'd love to have a feature that'd let me access the node that the Visual Script is attached to, (or even scene tree) either from Visual Script Custom Node, or from the Visual Script class.  There's currently no way to access the scene tree directly from code without making an input for every custom node that I need to access the parent scene node, which is cumbersome and makes the VS messier than it needs to be.

My current work around is to create a custom node directly after the function, that sets a scene node usually the parent node, to a project settings variable of my definition, which I can reference in subsequent scripts.  But it'd be so much cleaner not to:
```
tool
extends VisualScriptCustomNode

export(String) var Node_Reference

func _get_caption():
	return "Make Global"

func _get_category():
	return "Global"

func _get_input_value_port_count():
	return 1

func _has_input_sequence_port():
	return true

func _get_output_sequence_port_count():
	return 1

func _step(inputs, outputs, start_mode, working_mem):
	if(inputs[0] != null):
		ProjectSettings.set_setting(str(get_visual_script()) + Node_Reference, inputs[0])
	return 0
```
I really like the idea of seeing and using visual scripts as a more top level way of viewing and working with code, for designers in mind.  Having the same access and functionality as regular gdscripts I think is really important for that.

**Comment by vnen** [comment]
Well, you can use the custom node on any script that might be attached to any kind of object. There's no guarantee that the script is attached to a node nor that it is on the tree.

I believe it's cleaner to just use an input connection to receive the node, and in the visual script it's just a matter of connecting a SelfNode. Just adding another node for the input is not "messier" IMO, it is just more explicit (which is usually better for reading).

**Comment by akien-mga** [comment]
Closing as per the above.
