### ISSUE TITLE
Nodes become black randomly.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#19723]
**Godot version:**
3.0.3 stable official e649ec7

**OS/device including version:**
Geforce 8400gs 1GB.
Nvidia binary version 340.106 since Nvidia-340 (gpu driver).
Ubuntu 18.04 LTS

**Issue description:**
https://www.youtube.com/watch?v=iionCoaB5Tc
Godot suddenly and randomly makes the nodes in a scene completely black.

**Steps to reproduce:**
Just after a minutes, godot nodes becomes black even inside editor.

**Minimal reproduction project:**
[Bomberlite.tar.gz](https://github.com/godotengine/godot/files/2129503/Bomberlite.tar.gz)

**Comment by qarmin** [comment]
Can't reproduce with 3.1 RC 3

**Comment by bojidar-bg** [comment]
Looks like there might be a bug with the generated shader. Can you check if there is any input to stdout (in the console window that opens alongside the editor or debug builds)?

**Comment by KoBeWi** [comment]
Can't reproduce either. Closing this, because there was no response.
The issue can be reopened if someone manages to reproduce it in Godot 3.2.1 or newer.
