### ISSUE TITLE
Reading ScreenTexture causes ghosting and artifacts

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#19738]
**Godot version:**
Godot 3.0.4 stable

**OS/device including version:**
64 Bit Windows Home

**Issue description:**
Reading ScreenTexture causes ghosting and artifacts when there is something to read.
*Problem*
![Problem](https://user-images.githubusercontent.com/19930870/41812076-b20900d6-7739-11e8-8ef3-3878fad1c479.png)
*No Problem*
![No Prob](https://user-images.githubusercontent.com/19930870/41812112-5320ce86-773a-11e8-831f-58d1821b84d3.png)

*Another Scenario*
![image](https://user-images.githubusercontent.com/19930870/41819512-12b41b6e-77df-11e8-8abe-fbe82e8d0aa6.png)

**Steps to reproduce:**
Add a Shader to read screen and give it something to read. Then use the default texture for color of the Sprite.
Haven't tested in 3D yet.

**Minimal reproduction project:**
[Test_New.zip](https://github.com/godotengine/godot/files/2130091/Test_New.zip)

**Comment by Chaosus** [comment]
![image](https://user-images.githubusercontent.com/3036176/43199215-edc77e6a-9019-11e8-8144-9349e4e95c59.png)

Im not see any problem in current master, @akien-mga should this to be closed ?

**Comment by swarnimarun** [comment]
I will recheck it today. Will my old projects and confirm.

**Comment by Chaosus** [comment]
@swarnimarun So what is the result ?

**Comment by swarnimarun** [comment]
Yeah forgot to update, it doesn't seem to be there any longer but still haven't figured out what fixed it.
Might test for that if I find time.

Closing this issue for now.
