### ISSUE TITLE
Shaders aren't saved when running without save

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#19733]
25275de

When you run without manually saving, godot saves for you automatically, the shaders aren't included in this auto save. You have to save manually for them to take effect.

![image](https://user-images.githubusercontent.com/1177508/41810636-4dd7333a-7702-11e8-8c6f-e42254d3ed2a.png)

Uncomment the line from the shader attached to the sprite in the provided project and run without saving manualy.
[godot-dbg.zip](https://github.com/godotengine/godot/files/2129979/godot-dbg.zip)

**Comment by eon-s** [comment]
I have seen more than one issue similar to this, on master, many resources are not autosaved when running.

Related #17853 but I'm sure there are more.

**Comment by razcore-art** [comment]
Maybe we should make one of those issue lists that point to other issues since all of these are related, you know any other similar issues?

**Comment by eon-s** [comment]
I remember seeing others suspiciously similar but can't find them, I think this affects materials and all kind of resources, also some property changes, I have no idea _when_ the autosave got broke.

**Comment by Chaosus** [comment]
Seems like its fixed. The shaders now correctly save when "Save Before Running" is turned on. Closed by bugsquad.
