### ISSUE TITLE
Make subresource save option more visible in v3.1

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#19749]
25275de

As it stands now, it's very counterintuitive how to save a subresource (like material, shader etc.). The inspector currently expands subresources without opening them directly which is fine, but there's no option in this view to save any of the subresources.
![image](https://user-images.githubusercontent.com/1177508/41819824-78b7c798-77c7-11e8-91b0-7c93c59c857d.png)
You have to know how to open the resource first which isn't easy to find if you don't know where to look (clicking the node name in the inspector or right-clicking in the scene tree)
![image](https://user-images.githubusercontent.com/1177508/41819832-9ca40b3a-77c7-11e8-9959-b7b1b40f4ebc.png)
It's hard to guess that this menu would open the resource in it's own view in the inspector and then have the option to save it in the tools menu.
My proposal is to use the new AnimationPlayer selection menu when making a new property track
![image](https://user-images.githubusercontent.com/1177508/41819844-e2e52890-77c7-11e8-9a96-ae92268a067f.png)
But instead of properties you get a list of the subresources so save. This save window would appear only when you try saving from the tools icon in the inspector if there are any subresources on the currently selected node.

**Comment by JFonS** [comment]
I opened #23802 which could serve as a solution for this issue.

**Comment by akien-mga** [comment]
Fixed by #23802.
