### ISSUE TITLE
Setting NodePath script variable from the editor is broken

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#19746]
**Godot version:**
Custom Build 012e212

**OS/device including version:**
Arch Linux

**Issue description:**
Setting NodePath script variable from editor is broken

**Steps to reproduce:**
Create a script exporting a NodePath variable and set it to an existing node in the editor

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2130640/test.zip)

**Comment by groud** [comment]
Duplicate of #19712

**Comment by m4nu3lf** [comment]
@groud I though I had written it in the description, but I actually didn't. I'll fix that
