### ISSUE TITLE
Wrong default resolution in android

### ISSUE THREAD

**Issue by minisrc** [godotengine/godot#1974]
Hello,

I just started with godot and created a simple gui (just some panels and buttons). But when I exported to android with **stretch_mode = 2d** and **stretch_aspect = keep** in project settings, some parts of the gui were missing. After some testing I found out that when I set the diplay width and height or just checked both option, everything worked as expected.

It's just a small issue, but it really confused me.

Lastly: thanks for an awesome game engine and for making it open source.

**Comment by reduz** [comment]
Yes, you have to specify this. I am making it that if you change some properties, the resolution will automatically persist
