### ISSUE TITLE
Cannot install plugin demo in existing project

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19742]
Godot 3.0.4

I search "terrain" on https://godotengine.org/asset-library/asset, then I search "terrain" too in the editor, but I get less results.
I initially wanted to install the demo project for my plugin but it's not shown in the editor. I have no filtering, I just left the defaults which are supposed to show everything (switching back and forth doesn't fix it).

![image](https://user-images.githubusercontent.com/1311555/41813918-ae0d200e-7737-11e8-85a9-64dac01c52a7.png)

**Comment by mrcdk** [comment]
That happens because the results are filtered. Using Godot 3.0.x only 3.0.x compatible plugins will show in the AssetLib and the demo will show in the project manager templates tab.

**Comment by Zylann** [comment]
So I have two problems here...

- I cannot download the demo in an existing project. Perhaps add a way to access them still somehow?
- The demo will straight not work if users try to download it from the project manager because it depends on my plugin.

I could switch my demo to be a "plugin" but it makes it confusing.
