### ISSUE TITLE
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received. Occurs in chrome browser, fine in firefox.

### ISSUE THREAD

**Issue by stubbsy345** [godotengine/godot#19754]
I get the following error when trying to use websockets in chrome 'failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received', however, the exact same project works when ran in firefox both locally and when run on a server. 

Full Error:
```
pixelDrGame.js:4 WebSocket connection to 'wss://url.com' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
(anonymous) @ pixelDrGame.js:4
_emscripten_asm_const_iiii @ pixelDrGame.js:4
<WASM UNNAMED> @ wasm-02bceeb2-44243:194
<WASM UNNAMED> @ wasm-02bceeb2-44225:297
<WASM UNNAMED> @ wasm-02bceeb2-44215:231
<WASM UNNAMED> @ wasm-02bceeb2-10260:129
<WASM UNNAMED> @ wasm-02bceeb2-5747:48
<WASM UNNAMED> @ wasm-02bceeb2-1761:5382
<WASM UNNAMED> @ wasm-02bceeb2-18646:36
<WASM UNNAMED> @ wasm-02bceeb2-10260:62
<WASM UNNAMED> @ wasm-02bceeb2-5747:48
<WASM UNNAMED> @ wasm-02bceeb2-1761:5382
<WASM UNNAMED> @ wasm-02bceeb2-18646:36
<WASM UNNAMED> @ wasm-02bceeb2-10260:62
<WASM UNNAMED> @ wasm-02bceeb2-5747:48
<WASM UNNAMED> @ wasm-02bceeb2-1761:5382
<WASM UNNAMED> @ wasm-02bceeb2-18660:151
<WASM UNNAMED> @ wasm-02bceeb2-2179:35
<WASM UNNAMED> @ wasm-02bceeb2-10260:129
<WASM UNNAMED> @ wasm-02bceeb2-6018:302
<WASM UNNAMED> @ wasm-02bceeb2-361:57
<WASM UNNAMED> @ wasm-02bceeb2-42422:75
<WASM UNNAMED> @ wasm-02bceeb2-18940:389
<WASM UNNAMED> @ wasm-02bceeb2-36952:137
<WASM UNNAMED> @ wasm-02bceeb2-44279:4
<WASM UNNAMED> @ wasm-02bceeb2-19369:7
RuntimeEnvironment.Module.dynCall_v @ pixelDrGame.js:4
browserIterationFunc @ pixelDrGame.js:4
runIter @ pixelDrGame.js:4
Browser_mainLoop_runner @ pixelDrGame.js:4
```

**Godot version:** Master branch

**OS/device including version:** Webassembly export

**Comment by stubbsy345** [comment]
Hi Faless, I am connecting to the Microsoft Websocket framework. Working absolutely fine on firefox. With regards to the `WebSocketClient.connect_to_url` I am only passing a url and leaving the other arguments blank as I only need to connect to the websocket. I do not pass any protocols  and gd_mp_api=false.

**Comment by pawilon** [comment]
@stubbsy345 Are you sure this isn't an error in your server code? I think Chrome is just more stringent when it comes to WebSockets than Firefox. Make sure your server websocket is configured to use the binary subprotocol. If it all looks good, some more code snippets and a way to reproduce the error would help.

**Comment by stubbsy345** [comment]
So I’m connecting to the Microsoft bot framework wss link. So I don’t own the server. However, it works fine on Firefox but not on chrome. Surely this would be due to some incompatibility problem in the websocket module with chrome considering it works fine in Firefox? Happy to share my code if it helps.

**Comment by eska014** [comment]
We currently default to `binary` as default subprotocol instead of the empty string like JS, @Faless is this intended? https://github.com/godotengine/godot/blob/6fcc20ec5116a77c2328f4406a258527cc1aad5e/modules/websocket/emws_client.cpp#L75-L76

@stubbsy345 Does it work if you pass `PoolStringArray([""])` as protocol to `connect_to_host`?

**Comment by Faless** [comment]
@eska014 yes it was, I did that for compatibility at first.
We can remove it maybe, but it has to be the same behaviour on both native and browser.
I'll need to check how to support "no sub-protocol" in `libwebsockets`
