### ISSUE TITLE
[Feature Request] The ability to delete files.

### ISSUE THREAD

**Issue by IonizedGears** [godotengine/godot#1975]
There currently is no easy way to delete files from Godot. Currently the only way to do this is by closing the file in Godot and then deleting the file from the directory it's in, and even this has some errors with being "unable to find" the file.

Also, in the case of dependencies, perhaps Godot can tell you what depends on the file so you could then change the lines it highlighted to not depend on the file.

**Comment by captainwasabi** [comment]
Doing this will break Version Control Systems (VCS) where the file needs to be removed from the directory using the VCS.

For instance, we use SVN.  If I delete a file from my working copy without using svn delete, then when I have to svn update before a svn commit it will put the file back.  WRT the code repository my working copy has missing files, not deleted files.

**Comment by choikwa** [comment]
git is nice alternative. scm integration in godot would be nice, but I'd be okay with enable/disable delete files feature for now.

**Comment by reduz** [comment]
1.2 will allow to delete files, but if you are using something like SVN,
you will have to delete it yourself.

Git doesn't have much of an issue as if you delete a file, it considers it
deleted.

**Comment by choikwa** [comment]
nice thing that godot plays nice with git which just tracks content.

**Comment by kubecz3k** [comment]
In current 2.0 alpha there already is ability to delete files from inside of the editor (as well as dependencies tracking)
