### ISSUE TITLE
Shadow projected by an object using alpha scissor doesn't take alpha scissor threshold into account

### ISSUE THREAD

**Issue by JBiche** [godotengine/godot#19752]
**Godot version:**

v3.1.dev.custom_build.a74e151

**OS/device including version:**

Linux, DRI Intel ivybridge mobile

**Issue description:**

Shadow projected by a plane whose material was using alpha scissor with various threshold values seemed incoherent, as if the user-defined threshold value wasn't taken into account.

However, when using a texture without half-transparency (generated so it would look like the first plane, thus alpha threshold is irrelevant), the shadow is correct.

**Steps to reproduce:**
Open the minimal project, it should appears right in the editor. The screen capture shows what happens.

**Minimal reproduction project:**

[NoThresholdForShadows.zip](https://github.com/godotengine/godot/files/2131136/NoThresholdForShadows.zip)
![alphascissorshadowbug](https://user-images.githubusercontent.com/11290267/41822729-baffed1a-77f4-11e8-9867-16294aa6e8ce.png)

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch? If so, does it happen with both GLES2 and GLES3, or only one of them?

**Comment by Calinou** [comment]
I tested this with commit https://github.com/godotengine/godot/commit/70689ebffd95ab34e45bcbfdce3f6389033bfd44 and while the appearance is correct in GLES3, the alpha scissor in GLES2 only affects the shadow in a visible manner (the material itself remains *mostly* unaffected when changing the alpha threshold value).

### GLES3

![image](https://user-images.githubusercontent.com/180032/51839561-d400a280-2309-11e9-8049-df5e84d84bf3.png)

### GLES2

![image](https://user-images.githubusercontent.com/180032/51839611-feeaf680-2309-11e9-9454-c83f47eeab06.png)

**Comment by JBiche** [comment]
Hello akien-mga, Calinou,

Thanks you for acknowledging the issue (and sorry for the long wait...)

It doesn't appear anymore on the same machine (git revision a42549b8f ) when using GLES3 (At the time I opened this bug report, GLES2 was in a highly WIP state, I didn't tried using it to reproduce the issue) 

It seems fixed, at least for GLES3. Because with the a42549b8f revision, I have the same problem with GLES2  Calinou has.

**Comment by clayjohn** [comment]
It looks like the main issue has been solved. The GLES2 issue is being tracked here https://github.com/godotengine/godot/issues/26568
