### ISSUE TITLE
No options to import custom collision shape into the Scene Root(VehicleBody)

### ISSUE THREAD

**Issue by Socterean** [godotengine/godot#19765]
**Godot version:**
Godot 3.0.3 Mono Official

**OS/device including version:**
Laptop: Lenovo Y510P
OS: Manjaro 17.1.10 Hakoila
Kernel: x86_64 Linux 4.17.0-2-MANJARO
DE: KDE 5.46.0 / Plasma 5.12.5
GPU: GeForce GT 750M

**Issue description:**
I have posted this issue on every place that I know in order to find a solution with no luck.
The problem is about custom collision shapes, I made a car and I made a collision shape for it, but when importing it in Godot, using the -colonly  command (EDIT: I have found the official mentions about the commands, I am really sorry, but still that doesn't solve the issue) it creates a separate node for the collision shape that cannot be accesed by the Scene Root(VehicleBody) node, so it asks me to give it another collision shape in order to work. 
![colonly](https://user-images.githubusercontent.com/38301587/41824217-81f59e86-7815-11e8-8a05-249cd0af244f.png)
This is my Blender project setup:
![collision_problem](https://user-images.githubusercontent.com/38301587/41824228-b20e9c8a-7815-11e8-8d50-600f303e349f.png)

I could't find any informations on how to solve this on the web and in the documentation.
Also Blender cannot export .res, .tres and .shape files so I cannot add it that way either, and there are no mentions on how we can actually make those type of files on the web or in the docs. 

**Minimal reproduction project:**
[CarTest.zip](https://github.com/godotengine/godot/files/2133520/CarTest.zip)

**Comment by akien-mga** [comment]
Why do you have a `root` StaticBody as child of the VehicleBody? Is it in your Blender file? VehicleBody is already the physics body which should have the CollisionShape as child, this StaticBody is bogus.

**Comment by akien-mga** [comment]
It seems like you should use `-col` to generate the collision shape for your vehicle mesh, not `-colonly` which generates a StaticBody: http://docs.godotengine.org/en/latest/getting_started/workflow/assets/importing_scenes.html#create-collisions-col-colonly-convcolonly
