### ISSUE TITLE
The ability to move nodes around in the list for Organization and the ability to move nodes to different parents and shift select.

### ISSUE THREAD

**Issue by IonizedGears** [godotengine/godot#1976]
I don't know about you but I like some organization in the list of my nodes. Currently, the only way to do this is to get it right the first time, which is nearly impossible with the changes that occur in a game's development. I would like the ability to grab and drop a node to a different place on the list.

Also, there isn't a way yet to move nodes to different parents. It's annoying to do a lot of work on a particular node only to realize that it would be better moved somewhere else. Now, you could copy the script over, but there's also the case of non-script based work that's don't to nodes. This isn't easily ported over. There's also the issue of dependencies, but that can be worked out. It would be great to just grab and drop nodes into different parents.

Another bit for the list UI, you can control + click to select multiple nodes, but not shift + click, which can be especially useful in larger projects.

**Comment by jackmakesthings** [comment]
While you may not be able to "grab and drop" per se, the editor does have buttons for both reordering and re-parenting nodes. 
![godot-nodes](https://cloud.githubusercontent.com/assets/3606708/7790118/e1fe4bca-0248-11e5-9c7a-4c143a3e418a.jpg)
Look under the node list panel (in the upper right) at the small icons - the two arrows let you move a node up or down, and the fourth one over that looks like an "open in new window" link lets you give it a new parent.

**Comment by captainwasabi** [comment]
Node order isn't just for organization, it's also draw order.

**Comment by akien-mga** [comment]
Archiving, as this feature already exists (apart from the drag and drop support, but there's already #570).
