### ISSUE TITLE
Moving Label node right to left is faster than left to right

### ISSUE THREAD

**Issue by paul59** [godotengine/godot#19763]
**Godot version:**
3.0.3

**OS/device including version:**
Linux Mint 18.3
On-board graphics: Intel Xeon E3-1200

**Issue description:**
When continuously moving a Label node left and right across the screen it travels from right to left at a greater rate than when moving left to right. Probably no good reason for doing this (!) but it might reveal issues elsewhere

**Steps to reproduce:**
See below

**Minimal reproduction project:**

    extends Node

    var speed = 200
    var dir = 1
    var elapsed = 0

    func _ready():
	    pass

    func _process(delta):
        elapsed += delta
        var temp = get_node("Label").rect_position
        temp.x += speed * dir * delta
        if (temp.x  < 1) or (temp.x > 600):
		dir = -dir
		temp.x += speed * dir * delta
		elapsed = 0

        get_node("Label").rect_position = temp
        if dir == 1:
		get_node("LabelLeft").text = str(elapsed)
        else:
		get_node("LabelRight").text = str(elapsed)

**Comment by groud** [comment]
Alright I know what's happening. 

To fix the problem, you can disable the "snap to pixel" preference into the project settings for control nodes. The snapping makes the setter snap the node to a rounded value which accelerate/decelerate the movement.

However this is a little bit annoying, something should probably be done for that.

**Comment by akien-mga** [comment]
The symptom described in this bug is fixed with #19782. The more complex underlying issue is still valid though, and described in #17890.
