### ISSUE TITLE
AnimationPlayer - bezier keys for Camera3D strange behaviour

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#19777]
**Godot version:**
3.1.x

**OS/device including version:**
ubuntu, nvidia

**Issue description:**
I'd like to use bezier curves to animate my Camera3D but there seems to be some quirks.

**Steps to reproduce:**
1. Create a camera and an animationplayer
2. Add an animation to the player
3. Add bezier tracks for the Camera's translation and rotation
4. How to add keyframe to track?!? There's no key icon in the inspector nor a create keyframe in the view window as for 2D objects. Right click on the track lets you create a keyframe but the value is zero.
[](https://s8.postimg.cc/qltfp79wl/godot1.png)

In one project the key icon returned in the inspector (couldn't reproduce) but using it to add keyframes for the Camera result in animations that did not play smoothly (would jerk when hitting a key frame).

Deleting an animation key frame and then adding one back or selecting a different one caused a crash (could not reproduce).

**Comment by dodgyville** [comment]
Here's an [animated gif](https://i.imgur.com/srgs6ka.gifv) of the problem. I am using bezier tracks on the Camera's translation and rotation and I would expect a smooth transition when the animation track hits a keyframe but instead the animation jumps wildly.

![godot_bezier_problem](https://user-images.githubusercontent.com/13980/42193238-c0f2f498-7eb0-11e8-8e3e-eaf70ba81876.gif)

**Comment by bojidar-bg** [comment]
I remember seeing something similar when I played around with bezier curves.

**Comment by sketchyfun** [comment]
I'm getting this too. It appears as though the values aren't interpolating correctly, as the values are quite far off until the frame is finally reached. Here's an example:

![bug](https://user-images.githubusercontent.com/10464013/42413122-c5490f78-8211-11e8-8bdf-c49819c97100.gif)

Also, despite the first frame's X value being -20 as show here:
![image](https://user-images.githubusercontent.com/10464013/42413126-d1032682-8211-11e8-8615-7e8a76ddf50b.png)

The actual value X value of the objects position on the first frame ends up as a different number:
![image](https://user-images.githubusercontent.com/10464013/42413136-f34733c8-8211-11e8-976f-1dac95e815a3.png)

**Comment by avencherus** [comment]
@bojidar-bg 

Yes, looking more closely, this should be the same problem.  As requested, here is the screenshot showing the actual curve that is produced.

![godot_2018-07-12_20-11-22](https://user-images.githubusercontent.com/13004169/42683501-27aea262-8696-11e8-89a0-18294d71bb18.png)

**Comment by dodgyville** [comment]
Hi @avencherus,

Are you able to share your canvas project?

**Comment by dodgyville** [comment]
Are the interpolated values being cached somewhere? I notice I get different behaviour when I adjust the keyframe by dragging it. Reducing the length of a broken animation by dragging the keyframe from say 5 seconds to 2 seems to fix the animation (even the start error) but then dragging the keyframe again to a different location causes the animation to jump wildly but now with a garbled echo of the previous animation.

**Comment by dodgyville** [comment]
OK, I have checked in a fix #20146 for this issue. It was trying to interpolate over the duration of the animation segment (eg 5 seconds) instead of the percentage of the animation (eg 100%)

![tmp_bezier_fix](https://user-images.githubusercontent.com/13980/42719676-2f490e14-875d-11e8-810c-d3010e224c61.gif)

**Comment by avencherus** [comment]
@dodgyville Nice nice.  It looks like those lines fixed it.

![godot windows opt tools 64_2018-07-14_14-19-12](https://user-images.githubusercontent.com/13004169/42723903-2befcdf2-8771-11e8-9b0f-83dbc9d82dd2.png)

Here is the project if you still need it.

[bezier canvas test.zip](https://github.com/godotengine/godot/files/2194904/bezier.canvas.test.zip)
