### ISSUE TITLE
No Energy-Conservative Mode for Glow

### ISSUE THREAD

**Issue by adriansnetlis** [godotengine/godot#19770]
**Godot version:**
v4.0.3

**OS/device including version:**
Antergos with 4.17.2-ARCH kernel
NVIDIA GeForce GTX 1060 6GB with driver 396.24

**Issue description:**
Glow effect doesn't offer energy conserving mix mode. Current modes increase the brightness of bloom (except for "replace" which just gives blurred image). That's not optimal since enabling bloom doesn't conserve overall average color and brightness. It's also not the most realistic looking option. Using "mix()" function for blending blurred texture of bloom and intensity as the % value for it would produce much more realistic bloom that obeys the laws of physics and conserves the light energy received by the "camera".

P.S. This blending node only makes sense with no threshold whatsoever.

**Comment by CptPotato** [comment]
I mentioned something similar in #19361.

**Comment by Calinou** [comment]
This is now supported in the [`vulkan`](https://github.com/godotengine/godot/tree/vulkan) branch, closing. You can choose the Mix glow mode in Environment and configure the mix intensity.
