### ISSUE TITLE
Integrate Mono SDK directly into th C# releases

### ISSUE THREAD

**Issue by darkhog** [godotengine/godot#19780]
This is important, because you already require users to use a very specific version of the SDK, not "whatever is newest", which may pose problem on Linux because aside of very few distributions you can usually download only the newest version of a given package with the package manager. And for Windows/OSX it's a matter of convenience as you wouldn't need a separate download.

Please consider doing it - Unity does bundle mono with its releases and is friction-free. Also my deepest thanks for adding export functionality for Mono versions, now the only thing that keeps me on Unity is my current project, the next one will probably use Godot.

**Comment by exts** [comment]
This is already a WIP by TMM and is coming with a 3.0.x release.

**Comment by darkhog** [comment]
OK, thanks. Closing the issue then.

**Comment by Ploppy3** [comment]
@akien-mga It was stated that this would be released in the 3.0.X but 3.1.0 is just around the corner, when should we expect this to land?

**Comment by exts** [comment]
@Ploppy3 https://godotengine.org/article/dev-snapshot-godot-3-1-alpha-4 starting with 3.1 alpha 4
