### ISSUE TITLE
AutoLoad script order

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#1978]
Since, in some cases, order would matter when the engine is calling _ready() in Autoloaded scripts, it would be nice if you could move them up and down in the Project Settings->Autoload list. To move one to the top of the list so it loads first you have to remove all of them then re-add them in the correct order.

A workaround, of course, is to not use _ready() but have a init() function that gets called by the _ready() function of another autoloaded script that calls the inits in the correct order.

**Comment by okamstudio** [comment]
makes sense

On Sun, May 24, 2015 at 8:37 PM, captainwasabi <notifications@github.com>
wrote:

> Since, in some cases, order would matter when the engine is calling
> _ready() in Autoloaded scripts, it would be nice if you could move them up
> and down in the Project Settings->Autoload list. To move one to the top of
> the list so it loads first you have to remove all of them then re-add them
> in the correct order.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1978>.
>



-- 

*OkamStudio*

**Comment by AlexHolly** [comment]
I think this is now implemented. I can see up/down arrows to move a autoload script.

**Comment by vnen** [comment]
@AlexHolly you're right this was fixed by cb6839c5c1a6ada31a2c00ffa4645fe81fca922f.

**Comment by captainwasabi** [comment]
I do not see the arrows.

**Comment by vnen** [comment]
@captainwasabi The arrows are still there in the latest Beta.

![godot_v2 0_beta_20160205_win64_2016-02-05_20-31-59](https://cloud.githubusercontent.com/assets/5599796/12861074/d0a87142-cc47-11e5-9af2-2d6b51f4a32c.png)

**Comment by captainwasabi** [comment]
Yep, they are not in the beta-2.0 that I built at home.  They are in the latest nightly (I didn't go back to find the pre-built beta.)
