### ISSUE TITLE
"mouse_entered" signal inconsistently affected by MOUSE_FILTER_PASS and MOUSE_FILTER_IGNORE

### ISSUE THREAD

**Issue by danboo** [godotengine/godot#19785]
It seems that `mouse_entered` events are treated inconsistently by the `mouse_filter` setting. They don't honor the `MOUSE_FILTER_PASS` value, but do honor `MOUSE_FILTER_IGNORE`.

Given a scene made of two `Button` controls in a simple parent child relationship:

    parent
      +-- child

Attach the following script to both controls:

    extends Button
    
    func _ready():
        mouse_filter = MOUSE_FILTER_PASS
        connect("pressed", self, "_on_pressed")
        connect("mouse_entered", self, "_on_mouse_entered")
    
    func _on_mouse_entered():
        printt("entered", name)
    
    func _on_pressed():
        printt("pressed", name)

My hope/expectation was that both the `parent` and `child` controls would receive the `mouse_entered` signal, since the `mouse_filter` is set to pass events up the hierarchy. However what I found was that when you go to press the button, this prints:

    entered child
    pressed child
    pressed parent

This leaves out the expected `entered parent` line. The `pressed` signals are there just to confirm the `mouse_filter` settings work in other cases.

It occurred to me that the documentation for `mouse_filter` refers to click events, so perhaps it is not supposed to affect `mouse_entered` behavior. However, if I change the code above to:

    mouse_filter = MOUSE_FILTER_IGNORE

even the `mouse_entered` signals are ignored. So at a minimum it seems the effect of `mouse_filter` on the  `mouse_entered` signal is inconsistent.

**Comment by Jcozman** [comment]
I am seeing a similar issue. Here is a small example project that shows that mouse filter `pass`  on a child causes the `mouse_exited` signal to be emitted from the parent when the child is hovered.
[Example.zip](https://github.com/godotengine/godot/files/2251877/Example.zip)

**Comment by akien-mga** [comment]
It actually seems like `MOUSE_FILTER_PASS` is not implemented at all - several Controls set it, but it has no effect whatsoever in `scene/main/viewport.cpp`.

**Comment by nezvers** [comment]
3.1.1 stable
Control node  (mouse -> pass) blocks InputEventMouseMotion to go to _unhandled_input
+
It seems that Control node blocks handled input on HTML5 builds as the _gui_input goes before _input.

**Comment by Banderi** [comment]
Can confirm, PASS still doesn't let the events propagate - at the moment it does the same thing as STOP.
