### ISSUE TITLE
get_contact_collider_shape_metadata takes wrong argument, and returns void

### ISSUE THREAD

**Issue by Zamaroht** [godotengine/godot#1979]
First, there are some problems in the documentation:

- KinematicBody2D: get_collider_metadata() and get_collider() methods are listed as returning void, but they actually return something if you try them.

- Physics2DDirectBodyState: get_contact_collider_shape_metadata() is also listed as returning null, and taking contact_idx as parameter.

Since the function to get a collider's metadata actually worked in KinematicBody, I tried it too in Physics2DDirectBodyState. However, if you provide the contact index as the parameter, the game crashes.
I made a minimal example showing this crash here: https://github.com/Zamaroht/crash_example

After speaking with romulox_x on IRC, he found out that the parameter this method actually takes is the number returned by get_contact_collider_shape(). However, by using that number the game doesn't crash, but it doesn't return anything.

Since get_collider_metadata() returns the tile position of a Tilemap in KinematicBody2D, I'd expect get_contact_collider_shape_metadata() to return this same data.

Is it actually a bug or am I missing something? Thanks!

**Comment by akien-mga** [comment]
Regarding the wrong documentation, it has likely been fixed recently (check the in-game help) as the help was regenerated from the source code.

The other points might still be valid though.
