### ISSUE TITLE
Spatial Material map controls do not show up when enabled

### ISSUE THREAD

**Issue by kyledayton** [godotengine/godot#19792]
**Godot version:**
3.1 @ f036353

**OS/device including version:**
Solus (4.16.15-76)

**Issue description:**
When enabling additional maps on a Spatial material (Normal, AO, etc.), the controls for the map (texture, etc.) do not show up.

**Steps to reproduce:**
Create a spatial material and enable the normal map

**Minimal reproduction project:**
![screenshot from 2018-06-26 12-51-51](https://user-images.githubusercontent.com/1011026/41935727-53db13f0-7950-11e8-8c35-38c29ea01b57.png)

**Comment by kyledayton** [comment]
Some observations: If I enable normal map, then save and close the scene, and re-open the scene, the controls for the normal map show/hide appropriately. I'm guessing the map properties are only being shown when the Inspector is initialized, and are not updated properly when the enable button is check/unchecked.

**Comment by akien-mga** [comment]
Seems fixed in the current master branch.
