### ISSUE TITLE
Raycast3D is very hard to see in editor

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#19793]
**Godot version:** v3.1 c861756

**Issue description:**
Raycast3D gizmo is almos impossible to view if it overlaps with the axis. It also z-fights with the axis.
My proposal is to have a more visible gizmo for the raycast node.

![image](https://user-images.githubusercontent.com/7917475/41940214-50695cac-7998-11e8-941f-6a3ad4fafb28.png)
![image](https://user-images.githubusercontent.com/7917475/41940232-5b58f03c-7998-11e8-9f24-423231384908.png)

**Comment by MCrafterzz** [comment]
What would be the best way to approach this?

**Comment by Calinou** [comment]
@MCrafterzz Displaying RayCast3D as a thin box instead of a line would likely solve this.

**Comment by QbieShay** [comment]
I'd probably recommend an arrow shape, similar to the one used for directional lights, but thinner.

**Comment by lightspot21** [comment]
Can I take this up, since it looks like it's not fixed yet? I'll start working on this from next week though due to exams (so if anyone else wants it and is able to take it instead, please let me know)

**Comment by Calinou** [comment]
@lightspot21 Sure :slightly_smiling_face:

Feel free to salvage things from #33103.

**Comment by MCrafterzz** [comment]
There's not much to salvage but sure 😉

**Comment by Calinou** [comment]
This was fixed by https://github.com/godotengine/godot/pull/46529, closing.
