### ISSUE TITLE
Line2D is not working with GLES2 on Android

### ISSUE THREAD

**Issue by williamd1k0** [godotengine/godot#19797]
**Godot version:**

non-official (c633b77)

**OS/device including version:**

Windows 10 x64 and Android 6.0
![image](https://user-images.githubusercontent.com/10428035/41953118-337c96a6-79aa-11e8-9a16-76668c99dd20.png)

**Issue description:**

I tried to export a recent game to Android using GLES2 but all Line2D are not being drawn.

Windows (GLES2):
![2018-06-27 01_21_58-waffle scanner](https://user-images.githubusercontent.com/10428035/41953186-9b2bb160-79aa-11e8-89bd-939195a4d224.png)

Android (GLES2):
![image](https://user-images.githubusercontent.com/10428035/41953214-ca5e5cee-79aa-11e8-94bf-b87ae972408a.png)

**Steps to reproduce:**
I tried to reproduce using a simple scene with a Line2D as root. Same result.

Windows:
![2018-06-27 01_28_19-waffle scanner](https://user-images.githubusercontent.com/10428035/41953276-247dc552-79ab-11e8-9f52-c50255892e4d.png)

Android:
![image](https://user-images.githubusercontent.com/10428035/41953288-31b07ecc-79ab-11e8-95f7-1da05d99a7f3.png)

**Minimal reproduction project:**

https://github.com/godotengine/godot/files/2237476/Line2D-GLES2.zip

**Comment by dragmz** [comment]
Line2D works fine for me on Android (f778bd8). @williamd1k0  can you attach your simple project, please?

**Comment by dragmz** [comment]
@williamd1k0 Unfortunately this project does not work correctly on my Android device (blinking startup screen and then just quits) when using GLES2. Are you able to provide the project with just the line?

**Comment by williamd1k0** [comment]
I don't know what happened but here is a simple project: [Line2D-GLES2.zip](https://github.com/godotengine/godot/files/2237476/Line2D-GLES2.zip)

I added a Line2D node and a `_draw()` method calling `draw_polyline()` with the same points of the Line2D. On my device only the `draw_polyline()` is working (tried 832e2bf).

PC(Windows):
![image](https://user-images.githubusercontent.com/10428035/43350357-de667efc-91dc-11e8-843d-b8aaadac6617.png)

Android:
![image](https://user-images.githubusercontent.com/10428035/43350328-a5955b7a-91dc-11e8-8bc6-bc21ea988394.png)

**Comment by williamd1k0** [comment]
I just found an old Samsung to test and it's not working too.

![image](https://user-images.githubusercontent.com/10428035/43360064-134d6f88-9285-11e8-806c-52b951dc2804.png)

![screenshot_2018-07-28-16-33-55](https://user-images.githubusercontent.com/10428035/43360067-16997efc-9285-11e8-8e6b-dd0c9360f7ef.png)

**Comment by underdoeg** [comment]
I have the same issue, also with an older android device

**Comment by williamd1k0** [comment]
Still reproducible in 9587861

![screenshot_20181124-175917](https://user-images.githubusercontent.com/10428035/48972521-17414b00-f013-11e8-9003-3902f578e717.png)

**Comment by reduz** [comment]
The problem is that some older phones do not really support 32 bit indices for arrays. This needs to be fixed.

**Comment by williamd1k0** [comment]
Unfortunately I can't test it now because I can't compile for Android now and there is no recent nightly build available (see https://github.com/Calinou/godot-builds-ci/issues/13).

**Comment by avril-gh** [comment]
@williamd1k0 

godot 3.1 compiled by VSBuildTools 2017 at  https://github.com/godotengine/godot/commit/34d0585618d848ea67d0773cffd45c8b2428d793
[godot.windows.opt.tools.64.zip](https://github.com/godotengine/godot/files/2782344/godot.windows.opt.tools.64.zip) packed with [UPX](https://upx.github.io/)
[android_debug.zip](https://github.com/godotengine/godot/files/2782356/android_debug.zip) , [android_release.zip](https://github.com/godotengine/godot/files/2782374/android_release.zip)

**Comment by savegame** [comment]
yeh!! this fix my SailfishOS build of Godot Engine!! Its now works!!! cool! Thanks!

**Comment by williamd1k0** [comment]
@avril-gh Hey, thanks for the builds :3 

I tested it now and I can confirm that it is fixed! :)

**Comment by Sandheaver** [comment]
This has fixed #25202 also. Thank you.
