### ISSUE TITLE
Script editor fonts don't render sharply, also off center

### ISSUE THREAD

**Issue by smt923** [godotengine/godot#19805]
**Godot version:**

v3.0.4

**OS/device including version:**

Windows 10

**Issue description:**

Fonts used for the script editor render with a weird, blurred edge (on all hinting modes) and also render at the top of a line rather than in the center, like so:

![godot](https://i.imgur.com/yOy99IG.png)

Compared with my external editor, vscode:

![vscode](https://i.imgur.com/KIXuMB0.png)

To me, vscode is clearly rendered sharper (very noticeable around curves in letters) and isn't pushed to the top of the line

Both of these are using Consolas (though the same happens with the default font for godot's code editor), with default zoom and a font size of 14, godot is using the default line size of 4 (playing with this doesn't help, the issues are present in most line sizes and font sizes), where as vscode by default calculates this based on font size

**Steps to reproduce:**
n/a - blank project, with any code in the in-engine editor, with any editor settings I've tried

**Minimal reproduction project:**

n/a

**Comment by CptPotato** [comment]
The difference is that Godot doesn't use the rgb subsamples to increase sharpness (called "ClearType" in windows for example).

I like how smooth the fonts look in Godot, but I guess that's personal preference.

**Comment by Zylann** [comment]
See also https://github.com/godotengine/godot/issues/15688

**Comment by volzhs** [comment]
@Zylann oh. I missed that one. thanks :smiley:

**Comment by Noshyaar** [comment]
Does this get better with #19735 ?

**Comment by smt923** [comment]
Text is definitely much much better centered with #19735 👍 

![pic1](https://i.imgur.com/Wt5Q0nv.png)

blurriness/font quality is still not as good as external editors, imo, but I lack the understanding to know exactly why or how hard it would be to fix (just so that letters rendered a bit more solidly, like my vscode image, at least as an option if others like how it is now), but the centering alone is a huge improvement imo, code in the editor just seems a little neater overall to me now 👍

**Comment by Calinou** [comment]
@smt923 (or anyone else) Is this issue still reproducible on 3.1.1 or a [daily build](https://hugo.pro/projects/godot-builds/)?

**Comment by volzhs** [comment]
![Screenshot_20190609_053249](https://user-images.githubusercontent.com/8281454/59152064-171d1000-8a78-11e9-9d5a-29cb08c76f86.png)
pretty good with 197b65f32

**Comment by akien-mga** [comment]
Closing as fixed then.
