### ISSUE TITLE
Include directive or autoloads as global variables

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#1980]
I would REALLY like an "include" directive.  I just got finished pasting:

 var logger

func _enter_tree():
	logger = get_node("/root/Logger")

near the top off all my scripts. (or is there a better way to do this?)

**Comment by BBric** [comment]
I also find this syntax ugly. The use of a custom type should be transparent and smart.

**Comment by reduz** [comment]
An option will be added to make autoloads as global variables if desired..
So this syntax is not needed

**Comment by akien-mga** [comment]
Fixed by e0d21d2.
