### ISSUE TITLE
mouse_exited event/notification called after mouse button released in Control

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#19808]
**Godot version:**
Godot 3.0.4

**OS/device including version:**
Windows 10

**Issue description:**
When I hold a mouse button inside a control and move outside, the mouse_exited event is called after the button release.
I expect the event after the mouse is outside of the Control area, not after the release of the button.
If I don't hold the button, works as intended.
Here is a video where the half show the weird behavior
https://gfycat.com/IllustriousSoupyHadrosaurus
look at the mouse when it's pressed / released and the console output.

**Steps to reproduce:**
1. Create a control with stop filter. Register mouse_entered and mouse_exited events.
2. Hold Left or Right click inside the control.
3. Move the mouse outside and the mouse_exited event is ignored

**Minimal reproduction project:**
[mouse_exited_bug.zip](https://github.com/godotengine/godot/files/2142028/mouse_exited_bug.zip)

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by akien-mga** [comment]
This seems still reproducible in current `master` / 4.0 alpha 5.
Here's the MRP updated for 4.0: [mouse_exited_bug.zip](https://github.com/godotengine/godot/files/8354370/mouse_exited_bug.zip)
