### ISSUE TITLE
[TRACKER] GraphNode/GraphEdit issues

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#19806]
Just want to list out issues about the shader graph editor, I would also want to mention some issues about the VS editor but I am not sure whether shader editor and VS editor should be consider the same or not as they may share common problems.

## General

- [x] #41538

## Shader graph editor

- [x] #11001
- [x] #10989
- [x] #9618

## VS editor

- [ ] #18200
- [x] #6381
- [x] #16220
- [x] #16488

**Comment by KoBeWi** [comment]
Only one issue remains, so closing this.
