### ISSUE TITLE
Godot 3 shader compiler bug: syntax error, unexpected NEW_IDENTIFIER, expecting ')' or ','

### ISSUE THREAD

**Issue by deepmax** [godotengine/godot#19803]
**Godot version:**
3.0.4 (and 3.0.2)

**OS/device including version:**
GLX version: 1.4
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.0.4
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 11.0.4
OpenGL shading language version string: 1.30

**Issue description:**
It translates the shader program so that CanvasShaderGLES3 fails. This is the shader code:
```
shader_type canvas_item;

void fragment() 
{
	float fr = sin(0.5)*273758.5453123;
}
```

But it fails with this error message:

>  drivers/gles3/shader_gles3.cpp:168 - CanvasShaderGLES3: Fragment Program Compilation Failed:
0:248(30): error: syntax error, unexpected NEW_IDENTIFIER, expecting ')' or ','

the generated code is:

```
247: 	{
248: 		float m_fr=(sin(0.5f)*273759f);
249: 	}
```
I think the problem is related to `273758.5453123`, my current workaround is to rewrite that number as `273758.0 + 0.5453123`

**Steps to reproduce:**
Put an element in the scene and attach it this shader code:
```
shader_type canvas_item;

void fragment() 
{
	float fr = sin(0.5)*273758.5453123;
}
```

**Comment by JFonS** [comment]
I've encountered this bug before, for some reason floats with many decimal figures get rounded when generating GLSL code (String::num_scientific is used). I only get this bug when using my laptop, can't reproduce it on my main PC.  

It might have some relation with the fact that float constants are parsed and stored as doubles and later on converted to float.

I haven't come up with a solution to this other than changing 
`snprintf(buf, 256, "%lg", p_num);` to `snprintf(buf, 256, "%.16lg", p_num);` [here](https://github.com/godotengine/godot/blob/68f7cf13c7326c077cc6ff8a6a267ae2610c4519/core/ustring.cpp#L1296), but I guess the #defined is there for a reason.

**Comment by TheLastOperator** [comment]
Same error caused by the loading of a GDNativescript library.
Got the issue on a Linux laptop (Intel GPU), didn't tested with Linux on my main PC yet but it works on Windows.
Code generated : 
```gles
{
    color_interp.rgb=mix(pow(((color_interp.rgb+vec3(0,055))*(1.0f/(1.0f+0,055f))), vec3(2,4)), (color_interp.rgb*(1.0f/12,92f)), lessThan(color_interp.rgb, vec3(0,04045)));
    uv_interp=((uv_interp*m_uv1_scale.xy)+m_uv1_offset.xy);
}
```
It also caused the line numbers in the script editor to be displayed like this:
```
1,000000
2,000000
3,000000
```
Happens with Godot 3.0.6 stable

Probably an issue with localized floats separators (the FR local specifies to use a `,` instead of a `.`)
