### ISSUE TITLE
Fade in / fade out / loop from specific time in audio

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1981]
I look future forward for fade in / fade out effect in audio, with custom lenth of fading. Also looping, but not from the beginning, but from custom moment of time. It would give a nice freedom in use if those two would be used together simultaneously.

**Comment by kubecz3k** [comment]
Simple and working workaround for fade in and fade out would be to animate volume with animation player.

**Comment by Krzycho666** [comment]
hoh... Yes - You are right ;) But it doesnt seem to be clean to me. Besides it solves the problem only at some point. Thanks for an idea anyways.

**Comment by vichug** [comment]
yea... one requires the volume level to be interpolated at sample rate for a fade-in/fade-out to be clean. Is that possible with the animator yet ?

**Comment by vichug** [comment]
however Krzycho666, you may have better results if you just use a very small step size (the samllest i could is 0.01) in your animations

**Comment by vichug** [comment]
hm i need help, i don't know which volume value i have to animate. If i try to change the defaults/volume_db, it doesn't seem to do anything...

**Comment by reduz** [comment]
i don't think the engine should provide this, you should be able to write it yourself. volume_db is in decibels, so go from 0 to some low number such as -60
