### ISSUE TITLE
Constants are not 'virtual' when defined in a derived class but accessed from a static function in a base class

### ISSUE THREAD

**Issue by bundabrg** [godotengine/godot#19818]
**Godot version:**
c633b770cb648613ca88fc9e007718acfc219317

**OS/device including version:**
Linux

**Issue description:**
I'm not sure if this is a bug or not.

It appears that constants defined in a base class are not 'virtual' when it comes to using them in a derived class via a static function. The static function uses the const definition of its own class.

**Example:**

res://objects/a/a.gd
```
extends Node2D

const SCENE=preload("a.tscn")
const WHOAMI="a"

static func instance():
    print(WHOAMI)
    return SCENE.instance()
```

res://objects/b/b.gd
```
extends "res://objects/a/a.gd"

const SCENE=preload("b.tscn")
const WHOAMI="b"
```

res://screens/test.gd
```
const B = preload("res://objects/b/b.gd")

func _ready():
    print("Should be: ", B.WHOAMI) # Prints 'b'
    var test = b.instance() # Prints 'a'
```

**Workaround**
Defining the static function again in b.gd will fix the issue as long as it doesn't call its superclass.

**Comment by bundabrg** [comment]
Closest equivalent I can think of in python:

```
class A(object):
  WHOAMI="a"

  @classmethod
  def test(cls):
    print(cls.WHOAMI)

class B(A):
  WHOAMI="b"

a=A()
b=B()

a.test() # prints 'a'
b.test() # prints 'b'
```

**Comment by razcore-art** [comment]
82e769f

Indeed I confirm there's something strange going on. That example confused the hell out of me tho' so I made my own version. See the project.

[godot-dbg.zip](https://github.com/godotengine/godot/files/2144371/godot-dbg.zip)

**Comment by KoBeWi** [comment]
You can no longer re-assign constants in inheriting classes since 3.1, so this is basically resolved...
