### ISSUE TITLE
The meta+r key is bound to two different commands

### ISSUE THREAD

**Issue by Radbuglet** [godotengine/godot#19817]
**OS/device including version:**
Mac OS X Sierra 10.12.6

**Issue description:**
The meta+r keyboard shortcut is bound to the find and replace key and the project run key so when it's executed in the script editor, you will open the find and replace dialog and run the project. The key bindings should be changed or it should be made so that the find and replace key has priority.

**Steps to reproduce:**
Go into the script editor and press the meta key (ie Windows key, Mac command key) and the "R" key.
This key binding will open the find and replace menu in the editor but will also run the project.

The two lines of code relevant to this issue are:

`ED_SHORTCUT("script_text_editor/replace", TTR("Replace..."), KEY_MASK_CMD | KEY_R);`

which can be found [here](https://github.com/godotengine/godot/blob/c488a74e0c9d56975d5b23e5bff5ca2341f80036/editor/plugins/script_text_editor.cpp#L1785) and

```
#ifdef OSX_ENABLED
	play_scene_button->set_shortcut(ED_SHORTCUT("editor/play_scene", TTR("Play Scene"), KEY_MASK_CMD | KEY_R));
```

which can be found [here](https://github.com/godotengine/godot/blob/7dcaabaf1989f0e4d6957ca123df522c805ac57a/editor/editor_node.cpp#L5152).

NOTE: The bug is OSX only.

**Comment by akien-mga** [comment]
Still relevant in the current master branch, should be easy to fix. Just needs a macOS user to find out what would be the best alternative hotkey for one of those two. Typically, check an IDE that has options to both replace text and run (+ compile) code.

**Comment by tko** [comment]
Looking at TextEdit, Xcode and Visual Studio Code the keybinding for Find and Replace is `Option`+`Command`+F

And in Xcode the binding for Run is `Command`+`R` and Run with options is `Option`+`Command`+`R`

**Comment by tko** [comment]
But then `Option`+`Command`+`F` is already used for "Goto Function..." currently -- I guess the closest equivalent for that could be 
* Xcode "Jump to Definition" `Ctrl`+`Command`+`J`
* VS Code "Go to Symbol in File..." `Shift`+`Command`+`O`
* VS Code "Go to Symbol in Workspace..." `Command`+`T`

**Comment by tko** [comment]
Related: https://github.com/godotengine/godot/pull/21496
