### ISSUE TITLE
Simple scene as a loading screen / boot splash

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1982]
Now there is only and option to load a simple picture as a splash screen. How about using some fair simple scene - with some lightweight animations and so on. Do you think that this is to much?

**Comment by MarianoGnu** [comment]
Actually you can disable splash screen and set you intro scene as main scene and it will play automatically.

**Comment by Hinsbart** [comment]
As the splash screen is shown during startup, before the engine is set up, I think it's impossible to use a scene for it.

**Comment by reduz** [comment]
yes this is a non-issue
