### ISSUE TITLE
Memory leak when yielding (regression from #17291)

### ISSUE THREAD

**Issue by jjay** [godotengine/godot#19823]
**Godot version:**

Godot 3.0.4

**OS/device including version:**

macOS Mojave 10.14 Beta (18A314h)

**Issue description:**

simple yielding produces huge memory leaks

This code 
```gd
extends Node

func _ready():
	while true:
		yield(get_tree(), "idle_frame")
		yield(get_tree(), "idle_frame")
		yield(get_tree(), "idle_frame")
		print("yield 3 idle frames ", Performance.get_monitor(Performance.OBJECT_COUNT))
```
produces dat output:
```
** Debug Process Started **
Remote Debugger: Connection failed with status: '2', retrying in 1 msec.
OpenGL ES 3.0 Renderer: Intel(R) Iris(TM) Plus Graphics 640
yield 3 idle frames 702
yield 3 idle frames 705
yield 3 idle frames 708
yield 3 idle frames 711
yield 3 idle frames 714
yield 3 idle frames 717
...
```
Memory/Static && Object/Objects are constantly increasing in Debug/Monitors view.
Godot 3.0.2 didn't leak with same code.

**Comment by akien-mga** [comment]
Bisecting between 3.0.2 and 3.0.3 to find the culprit.

**Comment by jjay** [comment]
Reverting #17291  fixes this, but I am already use this functionality.

**Comment by akien-mga** [comment]
CC @Warlaan

**Comment by Zylann** [comment]
Argh, that `complete` signal was so promising... I hope it gets fixed
