### ISSUE TITLE
Portable Mono Godot - "mono path" input box on settings

### ISSUE THREAD

**Issue by brmassa** [godotengine/godot#19833]
Godot has the nice "feature" of being portable: just decompress and execute.

However, for Mono integration, Godot requires that Mono must be INSTALLED in the machine. On Windows, it relies on the registry to discover the Mono executable and config paths.

I suggest to create a fallback method: an input box on editor settings, to allow users to arbitrarily define the Mono path. This will allow to use Gogot/Mono even in a USB stick.

**Comment by ipavel83** [comment]
It's still actual. Especially with troubles of installing hell of different Mono/MS on each computer just to run "Portable" Game engine. Why we still can't just select foulder with Mono on USB drive? Is there some roadblocks?

**Comment by neikeq** [comment]
Godot doesn't require Mono to be installed anymore. It does require MSBuild to be installed, which can be obtained from different places: Mono, Visual Studio (or the Build Tools subset if you don't want the whole IDE), Rider (on Windows) and .NET Core SDK (recently added support for the latter in Godot).

**Comment by ipavel83** [comment]
Thank you for your answer, but I mean other thing: Why we don't have an option to choose path of MSBuild? So, for example, I can include it to folder with Godot. For many computers is schools and university there no way to install MSBuild permanetly on system, but Mono utilities runs from USB fine, Godot version without C# runs fine. It would be really great to teach students with proper programming language, give them opportunity to work with it on different computers. How can we do this without installing external libraries on closed machines?

**Comment by neikeq** [comment]
I do plan to change the MSBuild selection setting and also add an option to select a custom one.
However that is outside the scope of this issue which was about the installed Mono runtime and its assemblies. Since that is no longer a requirement I'm closing this. Feel free to open a new one about specifying a custom MSBuild path.
