### ISSUE TITLE
Can't export to android on 3.0.4 Mono

### ISSUE THREAD

**Issue by Akronae** [godotengine/godot#19839]
**Godot version:**
3.0.4 Mono x64

**OS/device including version:**
Win 10

**Issue description:**
I'm struggling to export my game to android, i set all the needed paths:![enter image description here][1]

Then i download the 3.0.4.mono export template (from the download page), i installed it![enter image description here][2]

And i even tried to install the classical export template
But when i try to export to android, godot says me:
![enter image description here][3]

And if i click on Manage Export Templates, it gives me the same screen as before:
![screen][4]

Godot gives me the export android icon too:
![enter image description here][5]
But if i try to export with the icon:
![enter image description here][6]

I really don't know what to do :/

  [1]: https://image.ibb.co/m8QBGd/image.png
  [2]: https://image.ibb.co/byw1Gd/image.png
  [3]: https://image.ibb.co/gfa6hJ/image.png
  [4]: https://image.ibb.co/byw1Gd/image.png
  [5]: https://image.ibb.co/f2ZGhJ/image.png
  [6]: https://image.ibb.co/jRgJwd/image.png

**Comment by akien-mga** [comment]
Mono export is limited to desktop platforms for now, there are no Android templates: https://godotengine.org/article/maintenance-release-godot-3-0-3

**Comment by dunyakilavuz** [comment]
When should we expect android exporting functionality for mono, any rough estimations?

**Comment by akien-mga** [comment]
Closing as support for Android will be tracked in #20267.
