### ISSUE TITLE
Timer, TooltipPanel and TooltipLabel objects created in random places in SceneTree

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1983]
I was just studing my SceneTree for some memory leaks in Info tab, and what I've noticed is a lot of stange objects that I did not make. There is a lot ot Timers, TooltipPanels and TooltipLabels a it's child - they are always together. Where do they come from? They are like in many different, quite random places.

**Comment by akien-mga** [comment]
I can confirm the bug, though in my small game I don't get too many of them, but I do get some. In the attached screenshot there are children of a hidden Label, and if I go to the main menu, I also get the same bundle of Timer, TooltipPanel and TooltipLabel objects as children of the menu's Node2D.

![st](https://cloud.githubusercontent.com/assets/4701338/11170317/c85e4910-8bd0-11e5-802e-33dbe055b4be.jpg)

**Comment by vnen** [comment]
I believe those are internal to the engine and must be needed for some work. What would be good is an option to hide them or, better yet, hide them by default and add an option to show'em.

**Comment by reduz** [comment]
they are hidden by default, but shown in the sene tree inspector, the fact they start with @ shows they are internal nodes. I'm closing as I belive this is a non issue

**Comment by akien-mga** [comment]
It was indeed not an issue, but I believe @reduz just fixed it nevertheless in 07e7909.
