### ISSUE TITLE
using "draw_line" function draws lines with incorrect width (and scales incorrectly on some values)

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#19844]
**Godot version:**
3.0.3; also latest daily build (downloaded 2018-06-29)

**Issue description:**
I am using `draw_line` function to draw a line (doing so in `draw()` function and calling `update()` in `_process(delta)` function). However, the line draws with incorrect width at times. It also scales improperly based on camera zoom.

Here are 2 cases:

1. When `width` argument is left default, or set in `<0.01, 1.00]` range, it draws the line with width of 1.0. And when you zoom in or out (either with camera node, or in the editor), the width stays the same on-screen. So if I draw a super long line with `width` in the range above, it's always visible when zoomed out, and not scaling up when zoomed in.

2. However, when `width` argument is set above 1.00, it works as expected and scales normally based on camera zoom.

Biggest issue here is that `width` doesn't scale when it's in `<0.01, 1.00]` range, but scales normally when above.

This happens both in the editor (when using `tool`) and in-game.
I haven't tried with negative values, nor have I tried scaling the node that draws the line.

**Steps to reproduce:**
use `draw_line` and modify `width` argument in `draw()` function (and of course put `update()` in `_process(delta)` function). View the results either in-game, or in-editor with `tool`.

**Comment by khairul169** [comment]
In this [code](https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_canvas_gles3.cpp#L530), lines with width <= 1 are drawed using lines primitive, and not triangle fan. The line width are always 1 pixel regardless of the canvas transform is.

Maybe line with width less than 1.0 should be drawed with triangle fan? 😆 cc @reduz

**Comment by vnen** [comment]
I guess it should not use the width property directly, but consider its value after applying the transform.

**Comment by reduz** [comment]
I guess, this needs some re-thinking, though.

**Comment by chrisb123** [comment]
What if the line is always drawn with thickness unless the width is null? in which case the width is always 1 pixel wide not width units wide

**Comment by wingedadventurer** [comment]
@chrisb123 I wouldn't recommend that because it's illogical. Line with width set to 0 should not be visible. Constant-width and varied-width lines are 2 different behaviours and should be treated that way.

What could work is drawing it constant-width when it's set to -1 because lines with negative width don't (shouldn't) exist. The default width value would then be -1, and if someone wants to draw it using primitives, they just set it to a value in `[0, +inf>` interval.

**Comment by SonerSound** [comment]
Hey there, I'd be willing to work on this, if someone would give me some more pointers, if possible, besides that linked code in the first comment.

**Comment by iatenine** [comment]
I see the issue but am pretty confused how this should look. How can you represent less than 1px width on screen? I've had some success by causing the if statement to jump right to the the else statement but the line disappears at around 0.8 or 0.7 thickness. Drawing the line at an angle also causes it to break into smaller lines that shrink in width before disappearing

**Comment by wingedadventurer** [comment]
@iatenine I might want a line that's visible when I zoom in. Like if I zoom in 5 times, a line of 0.2 thickness should be visible as if it had 1.0 thickness on normal zoom.

**Comment by rileylyman** [comment]
Would it make more sense to have a flag to determine whether the line should be one pixel wide or not? Looking here in `RenderingServerCanvas::canvas_item_add_line`:
```cpp
if (p_width > 1.001) {
	Vector2 t = (p_from - p_to).tangent().normalized();
	line->points[0] = p_from + t * p_width;
	line->points[1] = p_from - t * p_width;
	line->points[2] = p_to - t * p_width;
	line->points[3] = p_to + t * p_width;
	line->point_count = 4;
} else {
	line->point_count = 2;
	line->points[0] = p_from;
	line->points[1] = p_to;
}
```
it seems like the code assumes that width is in screen-space. It would make sense if `p_width=1.0` corresponded to 1px, but usually it doesn't. My thinking would be either to apply the correct transformation on `p_width` first, or to just always take the first branch and add a flag to make the line constant 1px width. 
@reduz

**Comment by m6502** [comment]
I opened a proposal to fix this issue at https://github.com/godotengine/godot-proposals/issues/1363

**Comment by dalexeev** [comment]
Closes with the following PRs:

* godotengine/godot#69851
* godotengine/godot#71679
