### ISSUE TITLE
Editor: No fallback font if a non-existent font is selected

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#19859]
Godot version: 3.0.4 (64bit)
OS: Windows 10

If you select a non-existent font in the editor settings (Interface > Editor > Main Font / Code Font) the font is initialized without any texture rather than falling back to a default font. Doing this with the "Main Font" can make the UI almost impossible to navigate when trying to change it back.

![fontless](https://user-images.githubusercontent.com/3957610/42127687-6a4b00e6-7c9d-11e8-8bf3-c76545317e2a.png)

To reproduce, simply set the one of the fonts mentioned above to "asdf" or something.

**Comment by vnen** [comment]
@numan98khan this issue wasn't closed. What was closed is the related pull request, since the author closed it to open another.
