### ISSUE TITLE
MySql built-in class

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#1985]
something like Python's MySqldb or SQLAlchemy

**Comment by okamstudio** [comment]
can always be an optional module

On Mon, May 25, 2015 at 7:17 PM, captainwasabi <notifications@github.com>
wrote:

> something like Python's MySqldb or SQLAlchemy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1985>.
>



-- 

*OkamStudio*

**Comment by Niriel** [comment]
In there a workaround in the meanwhile, besides being careful when (de)serializing on disk?

**Comment by captainwasabi** [comment]
Eventually I'm going to get around to writing a python gateway.  gscript<->python<->mysql

**Comment by akien-mga** [comment]
What about gdsqlite? https://github.com/khairul169/gdsqlite

**Comment by captainwasabi** [comment]
hmm, well it's been a while since I looked at sqlite, but I think there would be a problem providing simultaneous access to a large user base. 

I was actually almost finished implementing the python gateway when the project I was working on got cancelled. IIRC all I had left to do was json'ize the output and send it back to godot to import into a dict.

**Comment by vnen** [comment]
SQLite is interesting because it's pretty much standard for embedded DBs. If you want as a server, then I'd prefer as separate module, because it's not really a hassle to compile Godot once to run on your own server. Since there are competing software for DBs, favoring MySQL might not be really helpful.

Maybe ODBC might be better, as asked in godotengine/godot-modules#4.

**Comment by girng** [comment]
I think https://github.com/khairul169/gdsqlite-native is a solution to this proposal

**Comment by captainwasabi** [comment]
Oh, there are a million different easy ways to do this now!  If sqllite works for you then 100%, it wouldn't have worked for the particular use case I had at the time. Probably not even worth further discussion but I'll let one of the Godot dev team close it if they agree

**Comment by girng** [comment]
@captainwasabi I was just looking at the feature proposals from long ago and saw this XD

**Comment by vnen** [comment]
Today it's much easier to integrate with GDNative without changing the base engine. MySQL is quite a specific addition (what if you want PostgreSQL or SQL Server?) and not helpful in most of game projects (similar reasoning applies to SQLite). Given that I'm closing this.
