### ISSUE TITLE
Setting: "Visible Collision Shapes" doesn't affect tiles in the editor

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#19858]
**Godot version:**
3.0.2 stable

**OS/device including version:**
MacBook Air (13-inch, Early 2014) (1,4 GHz Intel Core i5)
MacOS High Sierra 10.13.3

**Issue description:**
After enabling _Debug > Visible Collision Shapes_, only collision shapes of objects are visible in the editor, but collision shapes of tilemaps are not visible in the editor.

**Steps to reproduce:**
1. Create a tilemap
2. Play some tiles in the scene
3. Enable _Debug > Visible Collision Shapes_
4. Collision shapes for tile are not shown in the editor, and they should be shown in the editor

**Note:** I clarify: In the editor. Because it works fine while playing the game.

**Comment by daniel-luper** [comment]
I know that this is a bit of an old issue but at least in version 3.1.1 (I'm pretty new so I don't know anything before then), enabling _Debug > Visible Collision Shapes_ doesn't affect anything in the editor, it only displays collisions in-game.

However, to see the collision shapes of objects in the editor, you have to tick the visibility icon of the collision node. Now I agree that there isn't a way to display collision shapes for tiles in the editor, maybe that could be remedied with a little box to tick in the properties window, under "Collision" in the inspector? 

Essentially the "Visible Collision Shapes" property isn't the actual problem, it's the fact that there's no way to view collision shapes for tile maps in the editor, correct?

**Comment by rmvermeulen** [comment]
Why not put it in the view menu? I think it would fit in nicely there as "Show TileMap CollisionShapes" (and NavigationPolygons maybe?).
![godot_2d_view_options](https://user-images.githubusercontent.com/14540163/76904252-e805bb80-689f-11ea-889d-7c1ba9c66fb6.png)

**Comment by Calinou** [comment]
@rmvermeulen It's in the Debug menu as the option only affects the running project. Whether you've chosen to display collision shapes is information that's sent to the running project via the debugger connection.

**Comment by rmvermeulen** [comment]
@Calinou I see it's passed as arguments to the executable, and set on the scene tree. Wouldn't setting that property at runtime cause the next draw-pass to include these shapes? Or is it passed on further to e.g. the physics engine itself at initialization?

**Comment by Janglee123** [comment]
@Calinou this Can be closed now.
