### ISSUE TITLE
Trouble with my C# project...

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#19855]
**Godot version:**
3852c5f

**OS/device including version:**
Windows 10

**Issue description:**
I reinstalled windows, but after restoration, my main project (which use C#) is printing this error
All new projects are created with C# are not have this problem

![image](https://user-images.githubusercontent.com/3036176/42125736-eccf017a-7c84-11e8-8222-8ba7fd03c364.png)

log - 
![image](https://user-images.githubusercontent.com/3036176/42125753-331ee7da-7c85-11e8-8b50-fac79f044fa4.png)

How to fix it ?
CC @neikeq

**Comment by Chaosus** [comment]
Ah.. changed Build tools.. not it works at least

**Comment by neikeq** [comment]
What build tool was selected when you received this error? Was it `MSBuild (Mono)`?

**Comment by Chaosus** [comment]
@neikeq Yeah

**Comment by neikeq** [comment]
Someone on discord had the same issue. Switching to `MSBuild (System)` build tool works as a workaround, but this is still a valid issue.

**Comment by aaronfranke** [comment]
I experienced this issue when I tried to open my project on Windows (I've previously been using Linux).

**Comment by ArthurAttout** [comment]
This bug also appears when **adding another project inside the auto-generated .NET solution**. 

When dealing with big projects, I like to have an additional console app inside my C# solution to debug easily certain methods (having it inside the solution allows me to access Godot assemblies, NuGet, custom folders, etc.). 

However it is mandatory to remove it (or exclude it from the project) to allow Godot engine to compile it again. The error is the exact same as @aaronfranke mentioned.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

**Comment by neikeq** [comment]
This may no longer be an issue now that we reference `Microsoft.NETFramework.ReferenceAssemblies`. I'm not sure how to confirm it as it's been a long time since I had to deal with this error.

**Comment by KoBeWi** [comment]
If it's that problematic let's just assume it's fixed. Can be reopened if someone reproduces this again.
