### ISSUE TITLE
[Regression] TileMap response time with mouse it's very bad

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#19864]
**Godot version:**
3852c5f8a0b439a8c0c6e72433d6fe82e3e596de

**OS/device including version:**
Linux 4.17.3

**Issue description:**
It's very bad to work with tilemap because response time is horrible.
In 3.0.4 the response time is good enough.

In my project, the cpu goes to 100% of usage and it's very unusable.

**Steps to reproduce:**
Create a simple TileMap and see the delay on response with your mouse cursor.
Video: https://youtu.be/-kiq_HEtvdc

**Minimal reproduction project:**
Just create a simple TileMap, ~you don't even need to have a TileSet~ you need a TileSet, even if it's empty.

**Comment by Zylann** [comment]
I think it ran faster even before 3.0.4 #12391

**Comment by guilhermefelipecgs** [comment]
Yes. I never seen this before. Now it really sucks.

**Comment by guilhermefelipecgs** [comment]
I'll do a `git bisect here to see if I can find what could be the cause of that.
