### ISSUE TITLE
Gridmap gizmo translation cannot be undone

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19861]
Godot 3.0.4

This is supposed to be a feature any Spatial supports, but `Gridmap` doesn't.
Create a `GridMap` node, move it using the gizmo, try to undo: notice nothing is undone. Instead it undoes the previous action and removes the `GridMap` node.

**Comment by Chaosus** [comment]
_Bugsquad edit_: note its still happens in 3.1 when you creates a GridMap - then drag it using snapping and try to undo after that + it will spam these errors..
![image](https://user-images.githubusercontent.com/3036176/54473304-e5810980-47e6-11e9-840d-eda0c69b5f39.png)

**Comment by KoBeWi** [comment]
This only affects moving while holding Ctrl. For some reason, the translation action isn't recorded in undo/redo. Seems to be happening only to GridMaps.

The error spam was another issue and is already resolved.
