### ISSUE TITLE
Can't select methods of C# node as target for function track's animation key

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19869]
**Godot version:**
`master` / 0ffec7daf

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
When I add a function track in an `AnimationPlayer` and try to add a key frame, Godot shows a dialog which lists methods that belong to the specified target node, but it doesn't include any methods defined in an attached C# source file.

Currently, the problem can be circumvented by choosing an arbitrary method at first, then use the inspector view to change it again to the intended method name.

We better let users select C# methods from the dialog window, or at least type the name without having to resort to such a workaround.

**Comment by Baekalfen** [comment]
I've run into the exact same issue in macOS 10.13.6 with a build from 7c712a2
