### ISSUE TITLE
AddChild throws an error if I try to pass a node that was removed from another parent

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19867]
**Godot version:**
`master` / 0ffec7daf

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
If I call `RemoveChild()` on a parent to remove a child node then use the node as an argument to `AddChild` for a different parent, I get the following error:

```
ERROR: get_node: Node not found: /root/Test Area/Entities/Characters/Player/Rig/Skeleton/Right Hand/Equip/Rag2
   At: scene/main/node.cpp:1277.
```
The node path displayed in the message refers to the child's previous path before it was removed. And I can't find much clues from the stacktrace aside from that the error was thrown from the native method that `AddChild` invokes.

**Comment by vnen** [comment]
AFAIK `add_child()` doesn't call `get_node()`. Are you sure that your script is not calling `get_node()` from somewhere else?

**Comment by mysticfall** [comment]
Yes, I checked that part too and I couldn't find any of my own code referencing `GetNode()` between those calls.

And as I mentioned in the description, the stacktrace indicates `Node.AddChild` so I doubt it was caused by any user level code:
![image](https://user-images.githubusercontent.com/2367032/42129884-9d0020fa-7d0d-11e8-98d2-dd6d0dd1284e.png)

**Comment by mysticfall** [comment]
`AddChild` itself seems to work despite the error message. I tried to add and remove the same node repeatedly and it didn't cause any serious problems apparently, even though the error message was logged each time it was added.

**Comment by mysticfall** [comment]
Upon some debugging, I found that the problem was caused by my own mistake. I assigned an absolute path to `MeshInstance.Skeleton`, so when the `MeshInstance`'s parent path is changed (i.e. being dropped to the ground), it will try to restore the skeleton path upon `tree_enter`, thus throwing an error about failing to find the target node.
