### ISSUE TITLE
Add 'scroll to the active scene' feature to the file system view

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19870]
**Godot version:**
`master` / 0ffec7daf

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
In many applications whose main window consists of a navigator tree and a content view (i.e. IDEs), there is a button on top of the navigator called something like _'Scroll from source'_ or _'Show in hierarchy'_ with which you can quickly reveal the location of the item you are currently viewing in the content view within the hierarchy.

Currently, Godot can optionally remembers scenes that were opened in the last session and restore them when reopened, but the file system hierarchy always shows as collapsed initially. So, it may take some effort to navigate to the directory which contains the scene loaded in each of the restored tabs when they are located deep inside the hierarchy.

If we can add such a button on top of the file system view as mentioned above, we can quickly navigate to the location where the current scene can be found without having to manually expand the tree nodes multiple times, thus improving the user experience.

**Comment by volzhs** [comment]
what about showing and selecting scene file in file system dock when double clicking scene tab?

**Comment by mysticfall** [comment]
It can work, but I think it may be not as familiar a feature as the suggested button is.

In such a type of applications (which have customizable subviews with tabbed content pane in the center), double clicking on the header of a view, or a tab usually maximizes it. So if we are also considering such a feature in future, I think it'd be better to follow the common route to minimize the potential confusion.

**Comment by volzhs** [comment]
agreed. :smile:

**Comment by Zylann** [comment]
I'd like to have this feature as a context menu of scene tabs, inspector properties and script tabs.
