### ISSUE TITLE
Mouse shows dragging hand when not dragging

### ISSUE THREAD

**Issue by GammaGames** [godotengine/godot#19874]
**Godot version:**
3.0.3

**OS/device including version:**
elementary OS 0.4.1

**Issue description:**
When holding spacebar to drag the hand should not show a closed hand when not dragging. It should only show a spacebar when you are dragging.

![godot_drag](https://user-images.githubusercontent.com/7832163/42131096-dcbc0094-7cb6-11e8-877f-958eb3b621e5.gif)

**Steps to reproduce:**
1. Hold space bar in a scene
2. Notice the hand is closed
3. Be confused when the scene isn't dragged when you move the mouse
4. Hold the mouse down, see that it is dragging

**Comment by Calinou** [comment]
I can confirm this on https://github.com/godotengine/godot/commit/a18989602b00f2940befa0b780af14efc7603dd8, both when dragging with the space bar (with **Simple Spacebar Panning** enabled in the Editor Settings) and the middle mouse button. The "dragging" cursor remains visible at the end of the dragging operation until you move the cursor again.

**Comment by Calinou** [comment]
It seems that as of https://github.com/godotengine/godot/commit/efd55631e2f05141072c26129bdc75d65cd1c53c, the cursor no longer turns into a "dragging" shape when panning (on Linux). It just keeps its original arrow form. Is this intended?

**Comment by akien-mga** [comment]
@Calinou I think that depends on your OS theme and whether it provides a specific cursor for this action.

**Comment by Calinou** [comment]
@akien-mga I tried switching from DMZ-White to Adwaita then rebooting, but I still can't see a dragging cursor. Also, I can still see the "dragging" cursor when moving something in the 2D editor, just not when panning.

Maybe this warrants a separate issue?

**Comment by GammaGames** [comment]
I don't see it anymore
