### ISSUE TITLE
Model textures don't render correctly in Android and appear scrambled 

### ISSUE THREAD

**Issue by mastorak** [godotengine/godot#19883]
**Godot version:**
3.0.2 and 3.0.4

**OS/device including version:**

Ubuntu 18.04 
Nexus 5x  Android 8.1.0

**Issue description:**
I have exported some simple models from Blender using the Better Collada exporter. The textures of those models render correctly in Desktop but incorrectly in Android.  The texture is a png image set from the exporter in the mesh ->material->SpatialMaterial->Albedo->texture
Check the field's texture bellow for an example. It appears scrambled 
![textureproblem](https://user-images.githubusercontent.com/1886412/42132944-7b82d63e-7d21-11e8-88e4-d3efc05e64df.png)

**Comment by mastorak** [comment]
What's the regular Adreno chip issue(if it is indeed this)? Also is there a workaround? Applying a texture to a model is a pretty common thing to do.

**Comment by kubecz3k** [comment]
Would be nice if you could provide a simple reproduction project.

**Comment by kubecz3k** [comment]
Also it will be worth to check if it's ok on gles2 backend (in 3.1)

**Comment by mastorak** [comment]
Please find attached a sample project of the table in the screenshot.
[TestTextureIssue.zip](https://github.com/godotengine/godot/files/2167614/TestTextureIssue.zip)
I did some further experimentation. The wall of the table renders the texture correctly whereas the floor doesn't. I tested the wall texture on the floor and again it was not rendered correctly, so I rule out something weird about the image used for the floor. So there is something about the floor mesh that makes the texture not rendering correctly.

**Comment by reduz** [comment]
Please use GLES2 backend for these things, as GLES3 mobile issues on Android are quite difficult to fix.

**Comment by akien-mga** [comment]
The test project seems to work well for me on Xiaomi Pocophone F1 using Godot 3.2 beta 5.
Both GLES3 and GLES2 (after enabling ETC import) produce similar results on the phone and desktop.

I'll close as it might have been fixed in 3.1 or 3.2, but if you can still reproduce the issue in a recent Godot release, please comment and we can reopen it.
