### ISSUE TITLE
Script error log shows the wrong file when inherited

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19894]
Godot 3.0.4

Repro steps:
1) Create a new project
2) Create a new script called `base.gd`, with a `_ready` function that calls an inexistent function on `OS`.
3) Create another script called `main.gd` which inherits `base.gd`, but doesn't define anything else
4) Put `main.gd` on a `Node` and save that as the main scene of the project
5) Close Godot
6) Run the project with Godot in the command line: observe it logs a script error as expected, but the file from which it occurred prints as being `main.gd`. However, we put nothing in `main.gd` but one line to inherit `base.gd`. The error should have come from `base.gd`.

Example project:
[WrongScriptInErrorMessage.zip](https://github.com/godotengine/godot/files/2153122/WrongScriptInErrorMessage.zip)

**Comment by Calinou** [comment]
Is this reproducible on 3.1 or the `master` branch?

**Comment by KoBeWi** [comment]
Yep, still happens. Only from command line.

**Comment by AstroStucky** [comment]
I can confirm that I'm seeing the same error on the master branch, although I'm on a commit back from August 21st, 2019.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3
