### ISSUE TITLE
preload() doesn't show enough characters (50 max) when autocompleting

### ISSUE THREAD

**Issue by BlueNoise** [godotengine/godot#19893]
**Godot version:**
Godot Engine v3.0.2.stable.official

**OS/device including version:**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

**Issue description:**
When typing the scene location with the preload() method, the maximum number of characters (50) is too low to show the complete path when the scene is stored within multiple folders layers.

**Steps to reproduce:**
- Create an empty Godot project
- Create a scene with only a node and save it here: res://BaseScene.tscn
- Create a scene with only a node and save it here: res://Characters/Enemies/Monsters/Monster/InstanceSceneNode.tscn
- In the BaseScene.tscn, attach a script and type:
var scene = preload(
- You should now see that the path displayed is limited to 50 characters long and displayed as : 
"res://Characters/Enemies/Monsters/Monster/Instanc
The complete path should be displayed.

I looked in Editor->Editor Settings for a setting, but I couldn't find one.

**Comment by Zylann** [comment]
See also https://github.com/godotengine/godot/issues/16542

**Comment by kubecz3k** [comment]
Closing as #16542 duplicate
