### ISSUE TITLE
Suggestion: Priority Patch Review/Committing for bugfixes.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#19895]
Currently in the Pull Requests tracker, there are 60 fixes for known bugs in Godot waiting to be green-lighted for inclusion into master. Since commercial game engines such as Unity and Unreal have historically been known for their bugs, having Godot become the engine where the vast majority of things simply work as intended could serve to help it make major inroads among studios small and large.

Some of these proposed fixes are for highly notable things that a developer is somewhat likely to come across with any given project, so it is important to give them priority to ensure that people can get games out with little to nothing to stand in their way (working around issues can be time consuming and are not guaranteed to work).

Apologies if a sweep of that category is planned, but Godot as a project needs to encourage patch makers to submit fixes if it is to thrive.

**Comment by eon-s** [comment]
Some things are measured by reactions, also there is a "hero wanted" and "pr welcome" tags, priority tags for contributors may help a bit more.

**Comment by mhilbrunner** [comment]
Note that many of the PRs are waiting for changes/feedback. But a focus on bufixing would definitely be welcome for me :)

**Comment by vnen** [comment]
Well, most of the work is in the new features scheduled for 3.1. After that is done we start the alpha cycle which is focused on small enhancements and bugfixes.

**Comment by exts** [comment]
@vnen I think OP is mostly talking about PR's that are already done that have been waiting for review.

**Comment by Calinou** [comment]
In my experience, priority tags aren't very useful to have on GitHub. In open source projects, people work on what they want to work on :slightly_smiling_face: 

The PR backlog has increased significantly, but this is due to the renderer still being reworked in the `master` branch. In a few months, we should be able to host [PR review meetings](https://github.com/godotengine/godot/issues/28853) more often.
