### ISSUE TITLE
Implementing A Extremely Thick and Close-up Fog?

### ISSUE THREAD

**Issue by M00nR4bb1t** [godotengine/godot#19890]
**Godot version:** 3.0.stable.official

**OS/device including version:** macOS Sierra Version 10.12.6, Intel HD Graphics 6000 1536 MB (Newest MacBook Air, 13-inch)

It seems that currently, there is no way to implement a very thick fog that is close to the camera. What I want to achieve is a fog that looks like the fog of the original Silent Hill title, except way closer to the camera. Something like that of the game *7 Days*.

![7 Days Fog](http://games.gameshed.com/_screens/22016_3.jpg)
![Original Silent Hill](https://static.giantbomb.com/uploads/original/16/168238/2436728-6498758650-3_19_.jpg)

I *can* emulate the effect using shaded materials and an omni light where the camera is, but there's gotta be a way to achieve this without such a hack?

GameMaker (I'm used to GM8 - GMS1.4, I don't know if any of those points are relevant in GMS2) has a very extremely poor and tedious 3d workflow, but even GameMaker has a "fog" option that does exactly what I described. (It takes a near value, a far value, and a color)

Or does this already exist and I am just not looking at the right place? I don't think the Environment's fog property works for this...

Any help would be highly appreciated, thanks in advance!

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/12454 which details why fog doesn't fully cover things in Godot.

**Comment by Zylann** [comment]
Fog can be done by modifying your `WorldEnvironment` (either the default one that comes in Godot 3 projects or create a `WorldEnvironment` node). In the resource there is a fog category where you can setup fog like you describe.

However, as pointed in Calinou's issue, fog doesn't apply if there is no geometry, so if your sky is black but your fog is white, you will see fog become whiter in the distance but if you look at a window it will be black.
A workaround is to simply change the sky to be the same color as your fog.

**Comment by Calinou** [comment]
This should work as expected now that https://github.com/godotengine/godot/issues/12454 has been fixed. Dense fog can be achieved by setting the environment fog's **Depth End** property to a low value.
