### ISSUE TITLE
New lines at long files only makes editor jump half a line

### ISSUE THREAD

**Issue by hemagx** [godotengine/godot#19902]
**Godot version:**
3.0.4.stable.official.d916135

**OS/device including version:**
Windows 10 version 1803 build 17134.137
Nvidia GTX 1060 (Mobile version)

**Issue description:**
New lines in the editors scrolls your only *half line*, which make you required to scroll again to be able to show the whole line.

**Steps to reproduce:**
Make a new line at the end of a new file that long enough to need scrolling.

**Minimal reproduction project:**
Any project would do it.

** Picture Example: **
![Example of the issue](https://i.gyazo.com/42881b3d791accdfdc420e35906f1267.png)

**Comment by Calinou** [comment]
Is this reproducible on 3.1 or with a [daily build](https://hugo.pro/projects/godot-builds/) of the `master` branch?

**Comment by KoBeWi** [comment]
If smooth scrolling is disabled, it happens consistently every second line. With smooth scrolling it happens only on first newline.
Tested with 3.1 stable.

**Comment by KoBeWi** [comment]
Still valid in 3.2.2, same as comment above.

**Comment by KoBeWi** [comment]
Fixed in Godot 4
