### ISSUE TITLE
Tween interpolate/follow methods don't work after calling `remove_all`

### ISSUE THREAD

**Issue by voithos** [godotengine/godot#19901]
**Godot version:**
v3.0.2.stable

**OS/device including version:**
Ubuntu 17.10

**Issue description:**
A bit of a weird case, this one. I had a Tween node in my scene that I wanted to reuse for multiple animations, and basically had code like this:

```
func _ready():
  tween.interpolate_method(self, "foo", 0, 1.0, ...)
  tween.start()

# Later...
func on_tween_complete():
  tween.remove_all()
  tween.follow_method(self, "foo", 0, self, "bar", ...)
  tween.start()
```

Unfortunately, the `follow_method` call wasn't doing anything. I discovered that the problem was the call to `remove_all` right above it. After getting rid of that call, the tween worked as expected.

**Steps to reproduce:**
It only seems to happen if the Tween has already run to completion at least once, after which calling `remove_all` seems to break subsequent interpolate_* or follow_* methods.

**Minimal reproduction project:**
[repro.zip](https://github.com/godotengine/godot/files/2153556/repro.zip)

**Comment by reduz** [comment]
tween is here:
https://github.com/godotengine/godot/blob/master/scene/animation/tween.cpp
