### ISSUE TITLE
set_custom_mouse_cursor() can cease working.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#19906]
This is for Windows and so far seen only in **2.1.5**

The problem occurs when setting all the cursors at once.  At some point, rapid cursor changes will break the ability to set the cursor texture, and the function will become unresponsive.

```
for i in range(17):
	Input.set_custom_mouse_cursor(preload("res://icon2.png"), i)
```

@guilhermefelipecgs Maybe you can shed some light on this one.  X)

![cursor problem](https://user-images.githubusercontent.com/13004169/42147135-0378458e-7dd5-11e8-8198-63a81d043fd7.gif)

Small demo project: [cursor bug.zip](https://github.com/godotengine/godot/files/2153884/cursor.bug.zip)

 Just whirl the cursor around these for a minute until it breaks.

**Comment by avencherus** [comment]
@guilhermefelipecgs Just curious how this one went.

**Comment by guilhermefelipecgs** [comment]
Sorry for the delay. I took a look at this a while ago and did not find out much. This problem needs to be investigated further but I need to setup an windows environment again. I can't promise that I'll be able to fix, but I'll take a look again when I can.

**Comment by avencherus** [comment]
Also a bit late getting back to this, but to confirm, yes it was retested on the master branch, and double checked tonight on version 268ae71fae08587e6df5b3270b7fc4833f30e34e

**Comment by dragmz** [comment]
Setting cursor leaks GDI objects
