### ISSUE TITLE
Not selecting last item in Tree class [Godot 2.1.x]

### ISSUE THREAD

**Issue by Heyter** [godotengine/godot#19903]
**Godot version:**
Godot 2.1.x (Steam)

**OS/device including version:**
Win7x64

**Issue description:**
Not selecting last item in Tree class.
[Work]
![image](https://user-images.githubusercontent.com/12237569/42145004-2237e898-7dc7-11e8-86be-fe914a8c4a1e.png)

[Not work]
![image](https://user-images.githubusercontent.com/12237569/42145006-280ef946-7dc7-11e8-975a-3bce4e0269ba.png)

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/2153737/example.zip)

**Comment by Calinou** [comment]
Is this reproducible on 3.1 or with a [daily build](https://hugo.pro/projects/godot-builds/) of the `master` branch?
