### ISSUE TITLE
StaticBody2D only appearing in scene window after restart

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#19909]
Godot version: 3.04 stable

OS/device including version: Win7

Issue description:
StaticBody2D only appears in scene window after a restart.

Steps to reproduce:
Click on create StaticBody2D.

Pictures:
https://i.imgur.com/el5b2Nr.jpg
https://i.imgur.com/R3H9jGP.jpg
https://i.imgur.com/qsT33ie.jpg

**Minimal reproduction project:**

**Comment by Zylann** [comment]
I can't reproduce it. When I create a `StaticBody2D`, it appears immediately in the scene tree and the scene view.

**Comment by BrahRah** [comment]
It seems to have been a one time thing can't reproduce it again either.
