### ISSUE TITLE
Godot html5 game - collision bug (Chrome)

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#19910]
**Godot version:**

**OS/device including version:**
win10 x64, Chrome 67.0.3396.99 （32 bit）, GTX 760

**Issue description:**
see this video
https://youtu.be/UFHBEHUAXQ0
game: https://dalton5000.itch.io/blazing-rails
not only this game...

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment]
Looks similar to #19304.

**Comment by eska014** [comment]
Duplicate of #16281
