### ISSUE TITLE
Double-sided mesh is shaded wrong when a normal map is used

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19918]
Godot 3.0.4
Windows 10 64 bits
nVidia geForce GTX 1060

If I apply a normal map on a double-sided mesh (culling mode off), its lighting will be wrongly flipped in half of its sides, while it is correct if I don't apply a normal map. It also appears that was working correctly in Godot 2.1.4.

Without normal map:
![image](https://user-images.githubusercontent.com/1311555/42180973-1cfb4536-7e31-11e8-9176-197f617bdfa4.png)

With normal map:
![image](https://user-images.githubusercontent.com/1311555/42181001-3f76c07c-7e31-11e8-839b-5be57881ceda.png)
![image](https://user-images.githubusercontent.com/1311555/42181068-68fa7bb4-7e31-11e8-8bc3-ac5bbbeb1f20.png)

Example project:
[DoubleSidedLighting.zip](https://github.com/godotengine/godot/files/2156469/DoubleSidedLighting.zip)

**Comment by reduz** [comment]
Closed by 78624ad
