### ISSUE TITLE
 Text rendering performance low due to missing batching

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#19917]
**Godot version:**

Godot 3.1 compiled with 54988df9ce0227d9f933f6f82e2f9f1d35df28c0

**OS/device including version:**

Android 7.1.2
Qualcomm® Adreno™ 430 GPU  OpenGL ES 3.1

**Issue description:**

Text rendering harms the FPS on Android with GLES3.
In the screenshots below the same scene rendered with diffrent text content.
More text rendered less FPS.

![screenshot-1530551860525](https://user-images.githubusercontent.com/6964556/42177581-ceaa8fd4-7e5f-11e8-8645-c76a087a1e3a.jpg)

![screenshot-1530551712802](https://user-images.githubusercontent.com/6964556/42177594-daba4cba-7e5f-11e8-91a7-01b8df5883eb.jpg)

**Steps to reproduce:**
* Create a RichTextLabel and fill a long text as its text
* Export and run it on Android with GLES3

**Minimal reproduction project:**

**Comment by Geequlim** [comment]
@akien-mga  I don't think this problem is only for Android. It is more obviously on Android as it can reach 60 FPS.
If I didn't limit the max FPS to 60 on my Linux desktop. The FPS can still down with the large text scene.

![2018-07-03 02-30-17](https://user-images.githubusercontent.com/6964556/42180243-181e3702-7e69-11e8-9ade-2f6b437a6f8f.png)
![2018-07-03 02-30-37](https://user-images.githubusercontent.com/6964556/42180250-1e3abf98-7e69-11e8-92bd-76045724f688.png)

**Comment by mrcdk** [comment]
2D doesn't batch anything so each character is a draw call. It looks like you are working on an app so enabling low processor mode would make it only render when needed.

**Comment by mhilbrunner** [comment]
Related issues:
https://github.com/godotengine/godot/issues/5838
https://github.com/godotengine/godot/issues/11797

**Comment by akien-mga** [comment]
@Geequlim Would you have a test project to share for @dragmz to test their text batching WIP?

**Comment by Geequlim** [comment]
@akien-mga Of couse yes

**Comment by Geequlim** [comment]
@dragmz  You can download this project for testing 
[text_rendering.zip](https://github.com/godotengine/godot/files/2212989/text_rendering.zip)

**Comment by dragmz** [comment]
Thanks @Geequlim 

Here are my first results: (batching vs master FPS with given number of "Add More Text" clicks):

Empty: no change
100 "Add More Text" clicks: 175 vs 53 [~3.3]
200: 65 vs 28 [~2.3]
300: 35 vs 19 [~1.8]
400: 21 vs 14 [~1.5]
500: 14 vs 12 [~1.2]

That's on Intel GPU. I should be able to test on Android but that may take me a few days.

**Comment by reduz** [comment]
@akien-mga did we not merge a new batching afterwards?

**Comment by akien-mga** [comment]
No, #20965 was the "new" batching (the previous one was never merged, it was rejected).

**Comment by lawnjelly** [comment]
Hold my beer! :sunglasses: 

This is the result of my new batching (PR coming soon) with the text_rendering.zip test project posted above, in GLES 2 on desktop (similar gains on Android though):

I rigged it so that each press added 100 lots of the text instead of 1 (I'm guessing this is what dragmz was doing).

### Godot 3.2
No clicks 1560 fps
100 clicks 20 fps
200 clicks 10 fps
300 clicks 7 fps
400 clicks 5 fps

### Godot 3.2 + new batching
No clicks 2050 fps
100 clicks 525 fps
200 clicks  523 fps
300 clicks 524 fps
400 clicks 524 fps

As you can see, after the first click it became fill rate limited and thus further batches could be added for free. So at 400 clicks there was approx 100x speedup over normal Godot.

This is on Intel Core i5-7500T CPU
Intel HD Integrated Graphics 630 GPU

**Comment by fire** [comment]
What are the steps to get this working for gles3?

**Comment by lawnjelly** [comment]
Although the interesting thing is the rich text should probably cull away the text that isn't on screen, and if this were working, there would in theory be no performance drops after about the 8th click. Still kind of useful as a benchmark.

**Comment by lawnjelly** [comment]
> What are the steps to get this working for gles3? Although it is going away...

Looks pretty simple actually, that part of the renderer is pretty similar, almost a copy and paste job.

**Comment by fire** [comment]
I and others who use 2d menus in 3d games on mobile gles3 would very appreciate this! I hope it isn't too hard to do in the same pr. Thanks.

**Comment by burstina** [comment]
Meanwhile You can use FastText asset. It is a little workaround I did for my projects and it works perfeclty on both Android and desktop. No noticeabily frame drops after stress trst of 1000 FastText label spawns.

**Comment by lawnjelly** [comment]
Can now test my batching PR on Android, debug build, same test as before, on a Google Nexus 7 2012:

### Godot 3.2 without batching
0: 60fps
100: 7fps
200: 3fps
300: 2fps
400: 1fps

### Godot 3.2 with batching
0: 60fps
100: 37fps
200: 24fps
300: 17fps
400: 13fps

That's 5.3x speedup.

**Comment by burstina** [comment]
Good, but if it is an engine builtin batching, it should be better: look at this [custom GDscript text batching video for Android](https://youtu.be/0dF4k-tM48A)


> 
> 
> Can now test my batching PR on Android, debug build, same test as before, on a Google Nexus 7 2012:
> 400: 13fps
> 
> That's 5.3x speedup.

**Comment by lawnjelly** [comment]
> Good, but if it is an engine builtin text batching, my newbie opinion is that it could be improved: look at this [custom GDscript text batching running on Android video](https://youtu.be/SY-yBQ8Nmlo)
> 
> [FastTextStresstest.zip](https://github.com/godotengine/godot/files/4188175/FastTextStresstest.zip)

You are absolutely right, if you mean caching the text as an image. However this isn't what these batching PRs do, they are lower level and intended to accelerate all rects (and eventually all primitives), and letters are still ultimately drawn one at a time. They aren't specifically to address text rendering.

There could be an argument to add the caching you suggest in core (many GUI systems do this for text and other elements), you could propose it on godot proposals (if it is not there)? :blush:

**Comment by burstina** [comment]
> They aren't specifically to address text rendering.

Oh well, I told you I am a newbie 😄 Infact I understood wrong 💭

**Comment by clayjohn** [comment]
This should have been closed when #37349 was merged.
