### ISSUE TITLE
NativeScript variables not saved with ResourceSaver-saved scene

### ISSUE THREAD

**Issue by DGWana** [godotengine/godot#19932]
**Godot version:**
3.0.4.stable

**OS/device including version:**
Windows 10 64-bits

**Issue description:**
When I try to save a runtime-created scene with ResourceSaver, nodes having a NativeScript attached with export variables are not correctly saved. In the saved scene, the node properties are written in the following order:
- [script variables]
- script = ExtResource( 1 )

If I do the same using GDScript, the order is as follows:
- script = ExtResource( 1 )
- [script variables]

When the scene is reloaded, in the case of NativeScript, it will find first the script variables, but since it doesn't know yet there is a script attached, it will ignore them. So these variables are effectively not saved, while in the case of GDScript the scene can be saved and reloaded correctly, with the export variables keeping their values.
The problem I can find is the order of the node properties in the SceneState. Scripts should be first always, for both GDScript and NativeScript. Note that when loading the ResourceSaver-saved scene in the editor, after modifying the NativeScript export variables and saving, the file is correctly written. So this happens only when saving with ResourceSaver and not from the editor.

**Steps to reproduce:**
Make a NativeScript including and export variable
Load the script into a node, like: var gdnative_node = load("path/to/script").new()
Change the value of the export variable
Pack the node into a PackedScene
Save the PackedScene with ResourceSaver

**Minimal reproduction project:**
I add a project which shows how GDNative can save the value of export variables and NativeScript fails.
[ResourceSaver.zip](https://github.com/godotengine/godot/files/2159238/ResourceSaver.zip)

**Comment by lethiandev** [comment]
I had the problem too, but after applying the pr of https://github.com/godotengine/godot/pull/19748 on custom build works ok

**Comment by DGWana** [comment]
Nice, thanks
