### ISSUE TITLE
Exporting scenes as TileSet is not intuitive

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#19949]
Godot version: 3.0.4 stable
OS/device including version: Win7

Issue description:
Saving the Tileset is cumbersome and not intuitive.

 I found myself editing the tileset scene a lot and it is very cumbersome if you make small changes and have to save the scene as tileset everytime. I even forgot that I had to save it as a tileset and had a hard time finding the error. It's not intuitive the scene is not going to be used as anything else either: Thus it would be much easier to just declare the scene as a tileset and when the user presses ctrl + s it's saved as a tileset/map. This would increase workflow and speed a lot.

Steps to reproduce:
Use the editor

**Comment by scayze** [comment]
I agree, editing tilesets is very cumbersome. The same goes for MeshLibarys obviously.

**Comment by MarianoGnu** [comment]
New TileSet editor has been added recently, this probably solves the issue. Give it a shot when Godot3.1 alpha is out

**Comment by KoBeWi** [comment]
Now that 3.1 is out with new tileset editor, the issue is provably resolved.
