### ISSUE TITLE
[Regression] AnimationPlayer no longer has "KeyNext" on frame property

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#19942]
**Godot version:**
085483e88577ea91400a1ee46bc4321340824c51

**OS/device including version:**
Any

**Issue description:**
Before (3.0.4):
![captura de tela de 2018-07-03 14-08-46](https://user-images.githubusercontent.com/1387165/42240686-759352bc-7ede-11e8-9216-ebd59328f972.png)

After:
![captura de tela de 2018-07-03 16-40-49](https://user-images.githubusercontent.com/1387165/42241126-dde476c4-7edf-11e8-81f7-a913e94bba1d.png)

**Comment by akien-mga** [comment]
>  Before:

When is "Before"?

**Comment by guilhermefelipecgs** [comment]
Any stable branch like 3.0.4 for example.

I was trying to re-implement this but I found this code maded by @reduz and basically he deprecated the "advance" option used by this "KeyNext" feature.  
https://github.com/godotengine/godot/blob/085483e88577ea91400a1ee46bc4321340824c51/editor/editor_inspector.cpp#L1821

**Comment by reduz** [comment]
I forgot to add this :\
