### ISSUE TITLE
Setting Control.rect_size before adding to scene is ignored

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#19948]
**Godot version:**

3.1.dev ac9e736b065f0ec30f3b1af19c41b7cd3a0371e6

**OS/device including version:**

not related

**Issue description:**

Setting Control.rect_size before adding to scene is ignored.
it's `rect_size` is just `(0,0)`
it's regression with recent changes.

**Steps to reproduce:**
run below code and see nothing on scene
```gdscript
	var control = ColorRect.new()
	control.rect_size = Vector2(100,100) # this is ignored
	control.rect_position = Vector2(100,100)
	add_child(control)
```

run below code and see added control can be seen
```gdscript
	var control = ColorRect.new()
	control.rect_position = Vector2(100,100)
	add_child(control)
	control.rect_size = Vector2(100,100)
```

**Minimal reproduction project:**

**Comment by volzhs** [comment]
possibly from #18634? @groud

**Comment by groud** [comment]
Yep that must be me

**Comment by ibrahn** [comment]
Does manually setting a control's rect_size have any meaning?
Aren't they supposed to always set their own position/size based on their anchors and margins?

**Comment by volzhs** [comment]
you can think in that way.
but we have set/get for rect_size.
it should be removed if it has no meaning.
and `control.rect_size = Vector2(w,h)` is easier than setting margins with considering its parent size.

**Comment by groud** [comment]
The position and size make sense, but significantly more when all anchors are at (0,0), in the upper left corner. They are simple helpers.
