### ISSUE TITLE
No replace in the ctrl + f search.

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#19952]
Godot version: 3.0.4 stable
OS/device including version: Win7

Issue description:
The replace feature seems to be missing when using ctrl + f. It's not intuitive to use ctrl + r, ctrl + r should just jump to the replace part of the ctrl + f search.
![no search and replace](https://user-images.githubusercontent.com/40721994/42262267-17cf4be4-7f6b-11e8-9bb9-eef8344bd698.jpg)

here is how it should be:
![note](https://user-images.githubusercontent.com/40721994/42262275-1ae07812-7f6b-11e8-912b-c8f86a6f955d.jpg)

Search is in a small popup and there are many options to edit the searched text.

Steps to reproduce:
use the code editor

**Comment by guilhermefelipecgs** [comment]
I prefer the way it is, without a dialog box. Many editors are like that.

Example VSCode:
![captura de tela de 2018-07-04 12-54-40](https://user-images.githubusercontent.com/1387165/42286491-7ad40ab8-7f89-11e8-9bce-da75d52f3433.png)
![captura de tela de 2018-07-04 12-54-51](https://user-images.githubusercontent.com/1387165/42286492-7af234d4-7f89-11e8-9f56-df91b148ca72.png)
Maybe we could implement a toggle button like VSCode.

**Comment by Zylann** [comment]
Ctrl+R doesn't immediately jump to the `replace` box because 99% of the cases you have to write something in the `find` box, so that it can properly find and replace.

**Comment by guilhermefelipecgs** [comment]
The only missing feature I see is regular expression.

**Comment by toger5** [comment]
maybe the search bar could also get a button to open the replace bar... (ctrl + r is not too obvious... ctrl + f is more than obvious, so no-one has to search how to reach the replace if the find bar gives you the option to open the replace bar like in vsCode)

regex is another issue.

I think pressing ctrl + r and than tab is better than
ctrl + f and than ctrl + r
So I think the current design is fine?

**Comment by KoBeWi** [comment]
Eh, I was going to make a similar issue, but it's too similar to this one :/

Basically, in VS Code when you select text and open the replace, it will automatically copy the selected text to find field and select the replace field. Ctrl + R would focus the find field only if there's no text selected. I think this behavior makes sense.
