### ISSUE TITLE
TPS Demo don't start on android (exporting problem?)

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#19957]
**Godot version:**

Godot 3.1.dev from 0b7df80eb

**OS/device including version:**

Macosx 10.13.4
Android 7.1.2

**Issue description:**

I downloaded TPS Demo sources from https://www.patreon.com/posts/19844846
When I exported and started it on android it fails with errors:
```
07-04 12:25:26.245: E/godot(1766): **ERROR**: Failed loading resource: res://player/playerrobot_diffusion.png
07-04 12:25:26.245: E/godot(1766):    At: core/io/resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
07-04 12:25:26.246: E/godot(1766): **ERROR**: Can't load dependency: res://player/playerrobot_diffusion.png
07-04 12:25:26.246: E/godot(1766):    At: core/io/resource_format_binary.cpp:659:poll() - Method/Function Failed, returning: error
07-04 12:25:26.246: E/godot(1766): **ERROR**: Condition ' err != OK ' is true. returned: RES()
07-04 12:25:26.246: E/godot(1766):    At: core/io/resource_loader.cpp:149:load() - Condition ' err != OK ' is true. returned: RES()
07-04 12:25:26.246: E/godot(1766): **ERROR**: Failed loading resource: res://player/playerobot.material
07-04 12:25:26.246: E/godot(1766):    At: core/io/resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
07-04 12:25:26.246: E/godot(1766): **ERROR**: Can't load dependency: res://player/playerobot.material
07-04 12:25:26.246: E/godot(1766):    At: core/io/resource_format_binary.cpp:659:poll() - Method/Function Failed, returning: error
07-04 12:25:26.246: E/godot(1766): **ERROR**: Condition ' err != OK ' is true. returned: RES()
07-04 12:25:26.246: E/godot(1766):    At: core/io/resource_loader.cpp:149:load() - Condition ' err != OK ' is true. returned: RES()
07-04 12:25:26.247: E/godot(1766): **ERROR**: Failed loading resource: res://.import/player.dae-5611407abdadd55b4ab0ac0830102352.scn
07-04 12:25:26.247: E/godot(1766):    At: core/io/resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
07-04 12:25:26.248: E/godot(1766): **ERROR**: Failed loading resource: res://player/player.dae
07-04 12:25:26.248: E/godot(1766):    At: core/io/resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
07-04 12:25:26.248: E/godot(1766): **ERROR**: res://menu/menu.tscn:5 - Parse Error: [ext_resource] referenced nonexistent resource at: res://player/player.dae
```

The full log: https://gist.github.com/DrMoriarty/ec8f21161564119182158f4b1dd7d49f
I see that it tries to load playerrobot_diffusion.png and so on. My apk contains `assets/player/playerrobot_diffusion.png.import` but it doesn't contain `.import/playerrobot_diffusion.png-87af19dce8d18d8080572c916504bb92.s3tc.stex` 

I uploaded apk to https://www.dropbox.com/s/ql7d491h6zvc4w6/GodotDemoLevel.apk?dl=0

Also I saved full export log to https://gist.github.com/DrMoriarty/5aee4dcae8ca509f4c4d135ece52dcad
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by DrMoriarty** [comment]
Actually apk's assets/.import doesn't contain any *.s3tc.stex files. But there are some regular *.stex files.

**Comment by Zireael07** [comment]
The author of the demo probably didn't plan to export to Android and switched off S3TC to speed up importing? Just guessing

**Comment by DrMoriarty** [comment]
@Zireael07 could you give me a tip where this s3tc switch is?

**Comment by Zireael07** [comment]
Projects settings, but I can't recall where exactly.

**Comment by Calinou** [comment]
As far as I know, Android and iOS cannot make use of S3TC but only of ETC2. Therefore, you want to make sure ETC2 importing is enabled (it's often disabled because it's pretty slow in comparison to S3TC, and you don't need it if you target only desktop platforms).

**Comment by DrMoriarty** [comment]
@Calinou Thank you. I enabled exporting to etc and etc2
![2018-07-04 16 05 21](https://user-images.githubusercontent.com/1177068/42278621-2044fdc6-7fa4-11e8-86b4-8857e90a8d4f.png)

Than I have to manually select every image in project and press Reimport in order to make the project runnable on android.
Is there any easy way to do it?

**Comment by volzhs** [comment]
1. type `png` on search field on File system dock
2. select all files
3. make some changes as you want on Import dock
4. hit Reimport button

then, all selected files are reimported as you want.

**Comment by DrMoriarty** [comment]
Thank you very much, guys!

**Comment by reduz** [comment]
heh i dont think this is even close to be able to work on Android..
