### ISSUE TITLE
Resize handles are too confusing for beginners

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#19958]
Godot version: 3.04 stable
OS/device including version: Win 7

Issue description: Resize handles too confusing for beginners:
![resize handles](https://user-images.githubusercontent.com/40721994/42270400-0bace112-7f81-11e8-8208-f015432ee790.jpg)

I'm sure if I read the doc from beginning to end I'll find some explanation somewhere. But I like to follow video tutorials first and I use the docs more like a lexicon. From my exp. docs aren't that great at teaching practical use of the software. I only use them to search the part I'm currently interested in. I couldn't figure  out myself what the outside handles do and the video tutorials just said don't use them. I've tried searching resize and "node 2d handles" in the docs which resulted in this issue: https://github.com/godotengine/godot-docs/issues/1564

There seems to be no easy to find and clear explanation for the outside handles and I personally don't see them being used that much. I'm sure I'll find out what they do along the way...

BUT:

That special resize should be done by pressing a key or getting toggled! It only confuses beginners and will fill up the bug report and result in a lot of people asking in the chat and forum. They create a lot of work for everyone involved which can be removed by showing the resize with the outside handles in a "toggeld off" state. Users that need them and know what they do can then just toggle them on when they need them.

**Comment by Zylann** [comment]
The double resize handles are confusing for collision shapes because AFAIK they should not be scaled anyways. They are still shown because CollisionShapes inherits Node2D... unless this was worked on by @groud in 3.1?

**Comment by groud** [comment]
The default resize handles are removed in 3.1.

**Comment by groud** [comment]
The default resize handles change the Node2D scale, while the inner ones (the two dots), resize the collision shape itself. As you should not scale a CollisionShape, the default handles have been removed in 3.1
