### ISSUE TITLE
Close Bug

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#19953]
Godot version: 3.0.4 stable
OS/device including version: Win7

Issue description:
Can't close the code editor anymore:
![pressing close](https://user-images.githubusercontent.com/40721994/42263281-d739c570-7f6d-11e8-9a95-5b1c5608b900.jpg)

leads here:
![leads here](https://user-images.githubusercontent.com/40721994/42263291-ddbfaf40-7f6d-11e8-854b-2206a652667a.jpg)

ctrl + w leads here:
![ctrl w](https://user-images.githubusercontent.com/40721994/42263305-e7f5c38c-7f6d-11e8-89c3-c470779d493a.jpg)

Opening a different scene:
![different scene](https://user-images.githubusercontent.com/40721994/42263357-17332220-7f6e-11e8-92ad-9b8c636450ba.jpg)

**Steps to reproduce:**
Open & Close the code editor

Minimal reproduction project:
[Farty Flies2.zip](https://github.com/godotengine/godot/files/2162243/Farty.Flies2.zip)

**Comment by DaDude** [comment]
I don't know if i properly understand your problem, but you don't have to close the code editor.
Just switch to the 2D or 3D View with the Buttons on the top, where "Script" is selected at the moment.

In the first set of screenshots you close a currently opened scene, which seems to work properly.
In the second set of screenshots you close the currently opened script file, which also seems to work properly.

**Comment by akien-mga** [comment]
That tab is not the script editor, it's your currently edited scene. If you want to go back to the scene, use the "2D" button on the top bar (or F1).
