### ISSUE TITLE
GDScript - warn about discarded results

### ISSUE THREAD

**Issue by paul59** [godotengine/godot#19964]
**Godot version:**
3.0.4

**OS/device including version:**
N/A

**Issue description:**
var p = 1
if p = 1:
    ...
Rightly generates an IDE error: 'Unexpected assign'

However,
var p = 1
p == 77
...
Passes silently but should generate at least a warning.

**Steps to reproduce:**

**Comment by akien-mga** [comment]
CC @vnen

**Comment by vnen** [comment]
Well, it's already done in my fork.

For the unaware, I'm currently working on #18271.

**Comment by akien-mga** [comment]
Duplicate of #7302 then.
