### ISSUE TITLE
Dependencies of res://.import resources missed after export

### ISSUE THREAD

**Issue by jjay** [godotengine/godot#19967]
**Godot version:**
3.0.4

**Issue description:**

I've created LargeTextureImporter add-on which can import texture as a `LargeTexture`. It splits big image into smaller parts and stores them into `res://.import` as well as lightweight `LargeTexture` resource which keep references to small `ImageTexture` (via `ExtResource( )`).

Everything is ok if I play from editor. But when I export the game, small images do not get exported, only `res://.import/bigimage.png-<hash>.tres`.

It is important to save this small images outside large largeimage.tres to be able to load/unload them from memory at runtime. This also allow high granular `ResourceInteractiveLoader.poll`'ing. 

**Steps to reproduce:**
1. Download example project
2. Open it, wait when it imports resources. 
3. Check `res://.import/` folder. 
4. Export zip
5. Insure the exported .import folder misses dependent resources ( it differs from content from step 3)

**Minimal reproduction project:**

[godot-test-dependent-export.zip](https://github.com/godotengine/godot/files/2163722/godot-test-dependent-export.zip)

**Comment by akien-mga** [comment]
Some feedback from @reduz on IRC:
```
22:53 <reduz> i never really thought of this use
22:53 <Akien> It's a custom importer that generates a main .tres and external .stex files, all written into .import/
22:54 <Akien> But only the .tres (i guess the main end product for ResourceImporter) ends up exported
22:54 <reduz> but its kind of weird, though
22:54 <Akien> Yeah
22:54 <reduz> it could create a simple .tex with everything
22:54 <reduz> there is not much need to create many resources
22:55 <Akien> He says "It is important to save this small images outside large largeimage.tres to be able to load/unload them from memory at runtime. This also allow high granular ResourceInteractiveLoader.poll'ing."
22:55 <reduz> i dont think resourceinteractiveloader takes that into consideration (though it probably should)
22:55 <reduz> also they will be loaded/unloaded at the same time
22:55 <reduz> so it doent make any practical difference
```

**Comment by reduz** [comment]
I don't think this is a bug, more like strange usage of the API that is not really expected to work
