### ISSUE TITLE
Typing "" in the code editor with Dutch keyboard selects to end of file

### ISSUE THREAD

**Issue by Wiering** [godotengine/godot#19976]
Godot 3.04 (and all previous versions I've ever tried, including 2.1)
Windows 10 (English version, but Dutch keyboard enabled)

If I want to type an empty string "" in the code editor, I get one quote, all remaining text is selected and the cursor is placed at the end of the file. The next character I type replaces the selection. So tying 'print ("")' produces 'print(")' and deletes the remainder of the file. It's not really a big deal, since undo works. But still very annoying and it makes Godot feel buggy.

Normally, with Dutch keyboard settings, when you type a quote ", at first nothing happens until you press another key. If that is a vowel, you get an ä, ë, ï, ö, ü or ÿ, otherwise you still get the " followed by the other key (unless it's a space or enter, then you only get the quote). So when typing "" you don't see anything happen until you've typed them both. 

Of course an easy workaround is just typing a space after each ".

If I switch to English keyboard with Alt+Shift, I can enter quotes without any problems.

Similarly, when typing two single quotes '', you only get one ' and the cursor goes to the beginning of the next line (which is far less annoying, but also incorrect). However, typing `` or ^^ (which are also used for accents in the same way) both do work correctly.

**Comment by NathanLovato** [comment]
Same with the international US layout, where you need to press ", ', and a few other characters twice (or <kbd>"</kbd><kbd>SPC</kbd>) to write them.

**Comment by akien-mga** [comment]
This seems to be the same issue as the later #25548, but I'll close this one as the other has a broader scope and more users involved.

**Comment by catafest** [comment]
the same issue with windows 8.1 and Godot 3.1 64 stable, maybe is a virus or an operating system faults because is needed to press twice the key to have a "" ?!

**Comment by catafest** [comment]
Fix it
Control Panel\Clock, Language and Region\Language\Language options 
Set the Handwriting to Write each character separately
