### ISSUE TITLE
Editor hangs and makes Xorg take up 100% cpu [fvwm]

### ISSUE THREAD

**Issue by Elronnd** [godotengine/godot#19978]
**Godot version:** 3.0.3

**OS/device including version:** Arch linux (latest everything as of 2018-07-06), Freebsd 11.2-RELEASE, cpu: intel i3-5005u, (i)gpu: intel hd 5500

**Issue description:**
Whenever I try to open up the editor on a project, I get a maximized window that hangs and displays no output, Xorg uses ~100% cpu, godot takes up ~55-60% cpu, nothing there changes until I kill it.  I also tried building from source, from the `3.0` branch -- same result.

EDIT: same result with master branch.

EDIT: same result on linux.

**Comment by hpvb** [comment]
Does this happen with any project you open? Does it happen when you open a 2d-only project for instance?

**Comment by Elronnd** [comment]
Yes.  I tried making a project and using the hdr for 2d demo, same result.

**Comment by Elronnd** [comment]
I have debugged it.  It appears that `OS_X11::set_window_maximized()` is calling `OS_X11::is_window_maximized()` in a while loop, but the latter always returns false.  I don't know enough about godot internals to know why it's expecting the window to become maximized -- I suppose that another thread is supposed to maximize it?  That seems like a bad design, as revealed in this case.  Anyway, the actual problem appears to be *in* the function that checks if the window is maximized, because a maximized window does appear, but in `is_window_maximized`, the `len` value is always zero.  If I force `is_window_maximized` to break out of the loop, it *appears* to work, although a bunch of error messages appear of the form

    ERROR: _EDITOR_GET: Condition ' !EditorSettings::get_singleton()->has_setting(p_setting) ' is true. returned: Variant()
       At: editor/editor_settings.cpp:1060.

**Comment by hpvb** [comment]
What wm/dm do you use?

**Comment by jasonpweber** [comment]
Did you figure out a solution?  We just started using Godot, and 3.0.5 and 3.1 both freeze up on us, at least those who use fvwm.  I've been trying out Godot examples on 2.1.5, but we need to move forward on writing C++ plugins and the old Godot doesn't want to use the newer compiler versions.

**Comment by jasonpweber** [comment]
file godot/platform/x11/os_x11.cpp line 1394
bool OS_X11::is_window_maximize_allowed()

I added an immediate "return false" with no checking, and all seems fine now.

**Comment by Elronnd** [comment]
Hmmm.  That's basically what I ended up doing (actually, I commented out the spinlock [here](https://github.com/godotengine/godot/blob/6cf7cfa0813755dec19a9b34249f4fb56f3f8172/platform/x11/os_x11.cpp#L1386), because that makes more sense imo and spinlocks are bad anyway and it's fine to assume it succeeded).  Never did end up finding a cleaner solution, but I stopped using godot so ¯\\\_(ツ)_/¯
