### ISSUE TITLE
INSTALL_FAILED_CONTAINER_ERROR when installing exported apk

### ISSUE THREAD

**Issue by sebastianhaba** [godotengine/godot#1997]
I exported apk and got this message INSTALL_FAILED_CONTAINER_ERROR

**Comment by prurigro** [comment]
I had the same issue and was able to prevent it from occurring on my own device by going into `Settings->Apps`, then opening the menu, selecting `Preferred install location`, and changing the value from `Let the system decide` to `Internal device storage`.

Godot Devs: some Googling lead me to a stackoverflow where someone resolved this error in their own project by setting: `android:installLocation="internalOnly"`. The fact that my device doesn't have an external storage, and that forcing it to install to the internal storage fixed the issue leads me to believe that Godot might be configuring the export to either use the external device only (or possibly to prefer it, in which case Android would presumably not check to ensure it exists).

Cheers!
