### ISSUE TITLE
Margin Container Default Value is Nonzero

### ISSUE THREAD

**Issue by JosephCatrambone** [godotengine/godot#19988]
**Godot version:**
Master Branch 9f82368 (2018/07/05)

**OS/device including version:**
Windows 10 x64 -- nVidia GeForce 1070.

**Issue description:**
If one sets the left margin of a child of a margin container to nonzero, then hides and unhides the parent, the left margin is set to 8.  **Workaround: set the custom_constraints in the parent margin container to zero and enable them.**

Expected behavior: if the left margin of a child is set to zero, that left margin should NOT be lost when hidden.

Observed behavior: left margin of the child node goes from zero to eight when the parent is hidden.

**Steps to reproduce:**

1. Create a root control node.  Verify the layout is full rect.
2. Add a margin container.  Verify the layout is full rect and the margin is zero.
3. Add a child of some sort (a texture rect, for example).  Set it to use the full rect.  
4. Left margin of the child is zero.  Set the parent margin container to hidden and observe as the margin jumps to 8.

See video:

![2018-07-05_10-20-01](https://user-images.githubusercontent.com/2160055/42338061-7cfb92e8-803d-11e8-8129-229e0aaf2b50.gif)

**Minimal reproduction project:**

[TestMarginContainer.zip](https://github.com/godotengine/godot/files/2167578/TestMarginContainer.zip)

**Comment by mhilbrunner** [comment]
Can you test with a more recent master or daily build? I believe we just merged a fix for this one

**Comment by akien-mga** [comment]
Indeed, this was fixed by #19398.
