### ISSUE TITLE
TextEdit.set_line_as_hidden doesn't hide the line

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#19981]
**Godot version:** Godot 3.0.4 Linux

**OS/device including version:** SolusOS 3.9999 Gnome 3.28.2

**Issue description:**

When using `TextEdit.set_line_as_hidden` the line doesn't hide at all, no matter the value of **bool** `enable` (which is confusing because I don't know if the hide is enable or the visibility of the line is enabled)

**Steps to reproduce:**
1. Create a `TextEdit`
2. Add a line with whatever
3. Add a `GDScript` to the `TextEdit`
4. In the `GDScript` add a method to toggle a **bool**
5. In the above method add `set_line_as_hidden(0, your_bool_var)`
6. Call this method somehow (a `Timer` maybe?)

**Comment by Paulb23** [comment]
`TextEdit::set_line_as_hidden` is used internally for code folding. I guess it should be hidden from the API.

**Comment by henriiquecampos** [comment]
It is very useful. Isn't it possible to allow its usage decoupled from code folding? Some use case I have:

I want to hide some lines of code and ask my user to complete the text.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
Fixed by #49238.
