### ISSUE TITLE
Bucket fill does nothing on master (Tilemap editor)

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#19985]
**Godot version:**
master @ 92bfde531cea21555dc74ad928a79120fbc9c34d

**OS/device including version:**
Windows 10 Home Version 1803 Build 17134.147
Processor i9-8950HK
Nvidia GTX 1050 Ti

**Issue description:**
In 3.0.2, the bucket fill function from the tilemap editor was working fine. Now in master, it does nothing.

![](https://i.imgur.com/vHUwfdF.jpg)

**Steps to reproduce:**
1. Create tilemap
2. Activate Tile Map Menu > Bucket Fill
3. Hover over the tilemap in the editor: No preview appears (the preview was working on 3.0.2)
4. Click in the editor: nothing happens, it should fill the area with that tile

**Comment by Zylann** [comment]
Note: it should also show a preview of that fill as you move the cursor around. But that's maybe related to the same bug.

**Comment by marcelofg55** [comment]
I've just checked this and the problem is that `Rect2i r = node->_edit_get_rect();` returns an empty Rect (at tile_map_editor_plugin.cpp:541). Not sure what broke that function for TileMap.
