### ISSUE TITLE
DualShock 4 malfunctional

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#1998]
I tested a DualShock 4 with Linux Mint 17.1

It responds, but it does not map the buttons correctly, particularly the face buttons on the right side of the controller. It has two additional buttons not listed being the Home or System button between the analogue sticks & the touchpad press above it, which make it a larger button map. Due to this the button numbers don't go high enough to access the Dpad.

Here is my attempt to remap:
![remapping](https://cloud.githubusercontent.com/assets/12471157/7846542/6594d236-047b-11e5-8c32-183b8eb3d8ec.png)
.

**Comment by Hinsbart** [comment]
I'm currently re-working the joystick code for linux, with it comes sdl compatible remapping support that punto- allready wrote some time ago. While there's more work left for the future, for now it will definitely fix your problem^^ I have to acquire some more controllers for final testing but expect a PR soon

**Comment by agameraaron** [comment]
Thanks so much! I will retest when possible to update this.
It will be in the upcoming alpha, if I am understanding correctly?

**Comment by agameraaron** [comment]
It's been a little more than a month, so I was curious what the status your PR might be? Is it shooting for SDL2 compatible joysticks?

**Comment by akien-mga** [comment]
I suppose the incomplete support for DualShock 4 is the same as for all other gamepads as discussed in #49.
