### ISSUE TITLE
The PackedScene (.tscn) doesn't update built-in scripts some times in the Editor

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#19982]
**Godot version:** 3.0.4 Linux x64

**OS/device including version:** SolusOS 3.9999

**Issue description:**

Editing a built-in script and saving the scene don't always change the .tscn file. I think for some reason the reference for the built-in is lost, or something, I don't know actually. But this persists until we create a *non built-in* script. But not only that, if we add this new .gd to the node and remove it to add a new built-in one, it takes back the undesired previous built-in script data. The only way to work-around this is to editting the .tscn by hand removing all the script data in it.

This is very annoying because some times we are editting a built-in script, test the scene, get some error, fix the script but the changes are not applied, so we keep getting errors until we realize the problem is not the logic, is that the script is not updated.

Also, in #5535 @vnen raised the discussion about the existence of built-in scripts. I find them very, very useful, specially for small tweaks in a `Node` behaviors, e.g. add a built-in script to allow a `Button` to grab focus, keeping the project folder nice and clear. But they do seem to be problematic, anyone that didn't know the script content is saved on the .tscn would flip the table trying to figure out what's wrong with their script, like @Keyaki777 did, so I think this bug needs some attention, especially as lots of newcomers are arriving and messing with built-in scripts is probably one of the first thing they may do (as adding script is mandatory, and a huge BUILT-IN (OFF) button is displayed every time they add a new script, so the margin for running into this bug is large)).

I'd like to shoutout to @NathanLovato can you confirm that this is the same problem you have with built-in scripts as well?

**Steps to reproduce:**
I don't know what exactly triggers this bug, but it is very common and happens very frequently, so I'll presume the steps are:
1. Create a New Scene
2. Add a `Node`
3. Add a Built-in script to the node
4. Force an error (try to print a non existing member in the _ready() for example)
5. Test the scene (F6)
6. Fix the error
7. Test the scene again
8. Look at the .tscn file and find the built-in script there
9. Confirm the changes were not applied

**Comment by NathanLovato** [comment]
Confirmed, but can't find exactly what triggers the bug. Sometimes it saves, often it doesn't/creates a new script with a different ID that's not kept inside the tscn file.

**Comment by KoBeWi** [comment]
This issue still exists, but doesn't happen normally. You have to meddle with script references (like closing scenes see #10423, copying scripts via inspector or removing and re-adding scripts). This is somewhat similar to #22289

**Comment by KoBeWi** [comment]
Fixed in #54653
