### ISSUE TITLE
Folder operations in FileSystem dock cause all assets to be rescanned

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19991]
Godot 3.0.4
Windows 10 64 bits

I tried deleting an empty folder and as soon as I do, Godot opens a loading popup in which it appears to re-scan every asset in the project, freezes a little, and resumes. Then I notice the empty folder I removed is still shown, and the file browser shows the entirety of my project as duplicate folders under it.
If I unfocus Godot and focus it again, the folder finally disappears.

Video:
https://youtu.be/HBWBYopradI

Update: Godot does this for any folder actually, not just empty ones.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by Zylann** [comment]
Looks like it got fixed.

**Comment by LATRio** [comment]
Reproducable in 3.3.2 when creating a new folder. "Scanning files" message doesn't appear when deleting a folder, but deleted folder disappears after a while.

**Comment by Calinou** [comment]
@LATRio Please open a new issue with a minimal reproduction project attached.
