### ISSUE TITLE
Nothing clickable just panning on 2D Workspace

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#19997]
Godot version: 3.0.4 stable
OS/device including version: Win7

Issue description:
When I tried to use the Node2D resize handles instead of resizing there was just a pan motion.
It happened after running the project and the Bug vanished after reopening the project. 

[Finger & Screen RPG.zip](https://github.com/godotengine/godot/files/2169776/Finger.Screen.RPG.zip)

**Comment by akien-mga** [comment]
It sounds like you selected Pan Mode by mistake?
![screenshot_20180724_135319](https://user-images.githubusercontent.com/4701338/43136452-149aef94-8f49-11e8-82fe-6a623909e652.png)

**Comment by groud** [comment]
No response in a year for something which is likely not a bug. Closing.
