### ISSUE TITLE
Dodgey normals when X or Y component approach 1

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#19994]
I'm using latest godot master branch.
And I'm getting black marks on my normal map when the Y normal approaches 1:
![normalmap](https://user-images.githubusercontent.com/11153232/42361220-6d42dc4a-812c-11e8-8580-21489237a7f2.jpg)

I found these black marks align perfectly with where my own normal map decompression code was producing errors:

        Vector2 normal = (Vector2(compressed.x, compressed.y)  * 2.f) - Vector2(1.f, 1.f);
        normal.y = -normal.y;
        float z = Math::sqrt(1.f - (normal.x * normal.x) - (normal.y * normal.y));
        return Vector3(normal.x, z, normal.y);

I fixed my code by changing:

        float z = Math::sqrt(MAX(0.f, 1.f - (normal.x * normal.x) - (normal.y * normal.y)));

The problem is due to rounding limitations. The value passed into sqrt can be negative (eg. something like -0.002 in my case), in which case sqrt returns a NaN value.

I suspect the godot shader must be doing something similar. If the MAX is added to the shader I suspect the issue will be resolved.

Can someone point me to where abouts this shader code is and I will try to confirm my hypothesis.

**Comment by akien-mga** [comment]
I don't know where the exact code is located, but this should point at potential culprits that might be worth reviewing:
```
$ cd drivers/gles3
$ rg sqrt
rasterizer_scene_gles3.cpp
191:    if (subdiv & 0xaaaaaaaa) { //sqrt(subdiv) must be integer
195:    subdiv = int(Math::sqrt((float)subdiv));
562:    if (subdiv & 0xaaaaaaaa) { //sqrt(subdiv) must be integer
566:    subdiv = int(Math::sqrt((float)subdiv));

shaders/cube_to_dp.glsl
37:     //normal.z = sqrt(1.0-dot(normal.xy,normal.xy));

shaders/scene.glsl
904:    // return 1.0 /( cos_theta_m + sqrt(cos2 + alpha*alpha*sin2) );
918:    return 1.0  / max(cos_theta_m + sqrt(cos2 + (s_x*s_x + s_y*s_y)*sin2 ), 0.001);
1086:           float aspect = sqrt(1.0-anisotropy*0.9);
1703:   normalmap.z=sqrt(1.0-dot(normalmap.xy,normalmap.xy)); //always ignore Z, as it can be RG packed, Z may be pos/neg, etc.

shaders/screen_space_reflection.glsl
257:                                    radius = (a * (sqrt(a2 + fh2) - a)) / (4.0f * h);

shaders/cubemap_filter.glsl
122:    float CosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a*a - 1.0) * Xi.y));
123:    float SinTheta = sqrt(1.0 - CosTheta * CosTheta);

shaders/subsurf_scattering.glsl
119:    strength*=strength; //stored as sqrt

shaders/tonemap.glsl
240:            color.r = (glow.r <= 0.5f) ? (color.r - (1.0f - 2.0f * glow.r) * color.r * (1.0f - color.r)) : (((glow.r > 0.5f) && (color.r <= 0.25f)) ? (color.r + (2.0f * glow.r - 1.0f) * (4.0f * color.r * (4.0f * color.r + 1.0f) * (color.r - 1.0f) + 7.0f * color.r)) : (color.r + (2.0f * glow.r - 1.0f) * (sqrt(color.r) - color.r)));
241:            color.g = (glow.g <= 0.5f) ? (color.g - (1.0f - 2.0f * glow.g) * color.g * (1.0f - color.g)) : (((glow.g > 0.5f) && (color.g <= 0.25f)) ? (color.g + (2.0f * glow.g - 1.0f) * (4.0f * color.g * (4.0f * color.g + 1.0f) * (color.g - 1.0f) + 7.0f * color.g)) : (color.g + (2.0f * glow.g - 1.0f) * (sqrt(color.g) - color.g)));
242:            color.b = (glow.b <= 0.5f) ? (color.b - (1.0f - 2.0f * glow.b) * color.b * (1.0f - color.b)) : (((glow.b > 0.5f) && (color.b <= 0.25f)) ? (color.b + (2.0f * glow.b - 1.0f) * (4.0f * color.b * (4.0f * color.b + 1.0f) * (color.b - 1.0f) + 7.0f * color.b)) : (color.b + (2.0f * glow.b - 1.0f) * (sqrt(color.b) - color.b)));

shaders/canvas.glsl
493:            normal.z = sqrt(1.0-dot(normal.xy,normal.xy));

shaders/effect_blur.glsl
251:    color_accum.a=max(color_accum.a,sqrt(max_accum));
```

**Comment by supagu** [comment]
changing scene.glsl:1703 to:

    normalmap.z=sqrt(max(0.0, 1.0-dot(normalmap.xy,normalmap.xy))); //always ignore Z, as it can be RG packed, Z may be pos/neg, etc.

fixes the problem:
![fixed_normals](https://user-images.githubusercontent.com/11153232/43176777-68c42e26-9004-11e8-83a8-fd0b8bcce366.jpg)

unfortunately I cant do any further PR for this as I have foolishly done some other PR's in the master branch (#19391 and #19374)

**Comment by akien-mga** [comment]
> unfortunately I cant do any further PR for this as I have foolishly done some other PR's in the master branch (#19391 and #19374)

You can always create new branches and reset your master branch on `godotengine/master`.

**Comment by codingHahn** [comment]
I could try to open a PR with this change
