### ISSUE TITLE
Editing text property of MultiNodeEdit keeps cursor at leftmost position

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#19999]
**Godot version:**

ecee0c9

**OS/device including version:**

Manjaro x86_64

**Issue description:**

Expected: being able to type normally into text field
Happened: cursor keeps going back to the leftmost position

This also affects expanded multiline text property editor.

**Steps to reproduce:**
1. select multiple nodes with multiline text e.g. Labels
2. edit text property
![peek 2018-07-06 17-24](https://user-images.githubusercontent.com/26753932/42374264-e005fd10-8141-11e8-9ee4-3e485dae026b.gif)

**Minimal reproduction project:**

**Comment by vnen** [comment]
Wasn't this fixed by #19351?

**Comment by Noshyaar** [comment]
...and here I thought 5-day-old build was recent enough. :man_facepalming:
Fixed indeed.
