### ISSUE TITLE
Label's "uppercase" property does not account for locale

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#19998]
**Godot version:**
3.0

**Issue description:**

Label currently has the "uppercase" property, but it doesn't work for any language, since the same small letter character may be represented by a different capital letter character depending on a language. For example, lowercase `i` must be uppercased into `I` for English, but into `İ` for Turkish and Azerbaijani.
There is at least one case when a single small letter is represented by multiple capital letters - in German `ß` is uppercased into `SS`.

This makes `uppercase` property of a Label a bit misleading, since people may not be aware of these specifics, use it for English, but then face problems when localizing their game.

**Comment by KoBeWi** [comment]
Still valid in 4.0 15aea89
CC @bruvzg
