### ISSUE TITLE
mouse pos tracking in scaled viewports is not correct

### ISSUE THREAD

**Issue by ratsdiov** [godotengine/godot#2000]
Windows 7 64 bit, 1.1 stable

I chased this down as a problem with moving a WindowDialog by dragging on the title bar but I think it is actually a mouse position reporting issue.  To reproduce:

1. New project setup as:
![image](https://cloud.githubusercontent.com/assets/4614207/7850383/9b212c86-04af-11e5-8824-2784d084bc22.png)
2. Add a WindowDialog node
3. Run
4. Click and hold on the dialog title bar and slowly move the mouse - the dialog drags in sync with mouse
5. Resize the application window (make it substantially bigger or maximize it)
6. Click and hold on the dialog title bar and slowly move the mouse - the dialog does not move unless the mouse is moved quickly

I suspect the issue is in mouse movement event handling with scaled viewports - printing ev.relative_pos from _input_event on the WindowDialog node shows it as (0,0) unless the mouse is moved quickly.

**Comment by reduz** [comment]
this was fixed recently, closing
