### ISSUE TITLE
Export arrays with type hints do not work (Regression)

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#20004]
**Godot version:**
master @ 8bb90fd5f3b9819bc3bc475e8b9f36c012d6c855

**OS/device including version:**
Windows 10 Home Version 1803 Build 17134.147
Processor i9-8950HK
Nvidia GTX 1050 Ti

**Issue description:**

export(Array, NodePath)  seems to not be working properly in master, the items of the array in the inspector or not being auto-detected as NodePath.
This was working fine in 3.0.2.

**Steps to reproduce:**
1. Create a node with a script with:
```gdscript
export(Array, NodePath) var triggerTargets
```
2. Go to the inspector, and notice that there is no Assign button
![](https://i.imgur.com/thlrwIp.jpg)
3. Clicking the pencil allows you to select NodePath, but this should be automatic because you already defined NodePath in the definition of the export variable
![](https://i.imgur.com/nYL2JOu.jpg)

**Comment by ordigdug** [comment]
#19158

**Comment by bojidar-bg** [comment]
This was part of #19158, but since the original issue was sorta-fixed, I'm moving the discussion about typehint support here.

**Comment by ordigdug** [comment]
@bojidar-bg I'm currently working on a solution to add Array type hint support. I'm most of the way there, hope to have something to submit soon.

**Comment by ordigdug** [comment]
@jahd2602 Can you please thoroughly test out my solution and let me know if you find any issues.

**Comment by jahd2602** [comment]
@ordigdug  I tested your branch ![ordigdug/godot/Inspector-add-array-typehint-support](https://github.com/ordigdug/godot/tree/Inspector-add-array-typehint-support) and is auto-detecting the type when I try with:
```gdscript
export(Array, NodePath) var triggerTargets
```

But, after assigning nodes to the array, it looks like this:

![image](https://user-images.githubusercontent.com/2841740/43081062-882818c0-8e67-11e8-9c09-d284d6acbaec.png)

**Comment by ordigdug** [comment]
@jahd2602 I'm working on it, this one is harder to solve.

**Comment by ordigdug** [comment]
@jahd2602 Fixed. Please test. Thanks.

**Comment by jahd2602** [comment]
@ordigdug Did you push to a different branch in your fork? I tried executing  ![ordigdug/godot/Inspector-add-array-typehint-support](https://github.com/ordigdug/godot/tree/Inspector-add-array-typehint-support)  and I don't see the fix.

**Comment by ordigdug** [comment]
I just updated it.
https://github.com/ordigdug/godot/tree/Inspector-add-array-typehint-support 
https://github.com/godotengine/godot/pull/20363

**Comment by jahd2602** [comment]
@ordigdug tested and now it works fine! The only issue I saw is with the "Select a Node" dialog:

![image](https://user-images.githubusercontent.com/2841740/43416836-c0cda89a-940f-11e8-82a2-b58ae0b7432a.png)

And when I click OK outside the border, let's say here:
![image](https://user-images.githubusercontent.com/2841740/43416878-dcb2ed36-940f-11e8-96a2-952cdae3c36a.png)

It won't assign the item. But that's probably for a different issue.

**Comment by jahd2602** [comment]
Needs merge

**Comment by ordigdug** [comment]
TypeHint support is planned to be rewritten after 3.1 is released.
