### ISSUE TITLE
Drag & dropping assets directory from filesystem to Godot Filesystem panel does not work

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#20016]
Straight from RMLL 2018.

**Godot version:**
master
Linux, Mageia 6, KDE @akien-mga 

**OS/device including version:**
N/A

**Issue description:**
Drag & dropping a directoyy from file system windows (KDE in this example) onto the Filesystem panel should copy the directory to the project directory. However, nothing happens.

**Steps to reproduce:**
Drag & drop an assets directory to the filesystem panel.

**Minimal reproduction project:**
N/A

**Comment by reduz** [comment]
This is more like an enhancement, but would be nice to have

**Comment by akien-mga** [comment]
This is likely not platform-specific, I did some quick debugging and we properly get and pass on X11 requests to drop directory paths.

Eventually the `files_dropped` signal is emitted with the list of paths which were dragged and drop, and for the FileSystem dock I believe it's this method which takes care of them:
https://github.com/godotengine/godot/blob/ca90dd302b7ebff4ceb3ebc7070dc4c17d626ec0/editor/editor_node.cpp#L4393-L4409

So currently only recognized asset types are supported, and directories are not part of those. It could probably be changed to accept any kind of file/dir path.
