### ISSUE TITLE
WorldEnvironment not reset on scene change

### ISSUE THREAD

**Issue by ConnyOnny** [godotengine/godot#20019]
**Godot version:** 3.0.4 x64

**OS/device including version:** Windows 10, GeForce GTX 1060 Ti

**Issue description:**
An included WorldEnvironment is not correctly reset when switching scenes.

I have three scenes:
* "Env"
* "Menu"
* "Game"

The "Env" scene is a Spatial, which contains a WorldEnvironment with my sky color definition and a directional light source. Both "Menu" and "Game" include the "Env" scene. The "Menu" scene changes the environment on load (make the scene blurry to make the UI more legible):

```
onready var env = $Environment/WorldEnvironment.get_environment()

func _ready():
	env.dof_blur_far_enabled = true
	env.dof_blur_far_distance = 0.01
	env.dof_blur_far_transition = 0.01
	env.dof_blur_far_amount = 0.2
```
Then when the user wants to start the game, I do it like this:
```
func _process(delta):
	if Input.is_joy_button_pressed(0, JOY_START):
		get_tree().change_scene("res://Game.tscn")
```
_The blur is still there in the "Game" scene although I switched the scene._

**Steps to reproduce:**

1. Have two scenes both including one scene containing a WorldEnvironment.
2. Change the environment programmatically
3. Switch to the other scene and see that the modifications are not reset

**Workaround:**

Have another scene "Workaround". Instead of switching from "Menu" to "Game" directly, go from "Menu" to "Workaround". In "Workaround" scene have nothing but one node with this script:

```
func _ready():
	get_tree().change_scene("res://Game.tscn")
```

Then the environment will be correctly reset when the game is loaded.

**Minimal reproduction project:**
[EnvBugTest.zip](https://github.com/godotengine/godot/files/2172934/EnvBugTest.zip)

When you start the reproduction project, you can hit "ui_accept" to trigger the bug, or you can hit "ui_up" to test the workaround. Afterwards you can go to the initial scene again with "ui_accept".

**Comment by Calinou** [comment]
@ConnyOnny Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
