### ISSUE TITLE
The loaded Core API assembly is out of sync

### ISSUE THREAD

**Issue by Marshal313** [godotengine/godot#20013]
**NOTE :**
I tried searching for the same issue and I found a lot of other issues facing similar problems, But they were mostly closed and reported as resolved, So I decided to write a new one because this still happens on master build as well as current official release.

**Godot version:**  
v3.0.4.stable.mono.official.d916135

**OS/device including version:**  
Ubuntu 18.04 running mono version 5.12.0.226

**Issue description:**  
When I open Godot Editor I get this error in output panel :
```
 modules/mono/csharp_script.cpp:1957 - Condition ' !valid ' is true. returned: __null
```
And as soon as I run my project I get the following error in Debugger :
```
0:00:00:0761 - The loaded Core API assembly is out of sync
----------
Type:Error
Description: 
Time: 0:00:00:0761
C Error: The loaded Core API assembly is out of sync
C Source: modules/mono/mono_gd/gd_mono.cpp:253
C Function: initialize
```
I also tried the same with Godot built from master, and I got an additional error in debugger :
```
0:00:00:0719 - Mono Cache: Member GDMonoUtils::mono_cache.class_RemoteSyncAttribute is null
----------
Type:Error
Description: Mono Cache: Member GDMonoUtils::mono_cache.class_RemoteSyncAttribute is null
Time: 0:00:00:0719
C Error: Method/Function Failed.
C Source: modules/mono/mono_gd/gd_mono_utils.cpp:217
C Function: update_godot_api_cache
```

**Steps to reproduce:**
I tried to reproduce the bug using a simple single-line C# code but I could only get the first error (on editor startup) and not the others. I'll work on my other - more complicated - project to see where the problem rises.

**Comment by Marshal313** [comment]
**Doing the following resolved the problem :**

1. Exit Godot
2. Completely remove .csproj and .sln files, and the .mono and obj directories (Everything mono except .cs files !)
3. Enter Godot again and rebuild the mono solution
4. Enter your IDE and add all .cs files to your project again
5. Run the project in Godot
And the errors in didn't show up again.

I think what happened was because I created this project using Godot 3.0.2 and now in 3.0.4 this error happens because of some old built uncleaned files !

**Comment by neikeq** [comment]
The error `The loaded assembly is out of sync` is expected if you upgraded to a newer Godot version, but it shouldn't keep happening after building the project. The cache errors are to be expected if the assembly is out of sync. I tested on a731bd58 master and with 3.0.4, and the errors don't appear after building the project.

`modules/mono/csharp_script.cpp:1957 - Condition ' !valid ' is true. returned: __null` is a false error, I noticed this a few days ago. It shouldn't be printed.

**Comment by neikeq** [comment]
If you can still reproduce the error after building the project, could you share an example project for testing?

**Comment by Marshal313** [comment]
I couldn't reproduce the error again, And I think it's the same thing you said about Upgrading to a newer version because I was using 3.0.2 with this project and I got the error on 3.0.4 !
I'll try again to see if I can reproduce the situation.

But, I did rebuild the project and the error kept happening !
It went away only after I removed .csproj and .sln files.

**Comment by neikeq** [comment]
Can you share an example project (including the .mono directory) where you can reproduce the error? Also, this is 3.0.4, right?

**Comment by Marshal313** [comment]
Yes, I got the error on 3.0.4, But right after an Upgrade from 3.0.2
Rebuilding the Mono solution didn't work so I had to remove the .csproj and .sln files.

I'll see if I can reproduce the error by creating a project using 3.0.2 and then trying to open it using 3.0.4 and will upload the project if it did give me the error.
But so far I wasn't able to reproduce the error in any new projects I created, And the error never happened again in my own project after I removed those files and recreated them by rebuilding the solution in Godot.

**Comment by Marshal313** [comment]
Hi everyone !
So, I tried but I couldn't reproduce the problem.
At this point I guess the issue should be closed, because I couldn't reproduce it !

**Comment by daimeng** [comment]
I believe removing the Roaming Data or Making it regenerate the project files fixed this for me.

**Comment by neikeq** [comment]
This is expected to happen when upgrading to a newer Godot version. Rebuilding the project (by running the game or via the "Build project" button) should be all that's needed to fix it.
I will modify the error to include this info.
