### ISSUE TITLE
SurfaceTool add_triangle_strip method

### ISSUE THREAD

**Issue by Toshiwoz** [godotengine/godot#20018]
A method that allow to create a triangle strip would be a great feature to add to the SurfaceTool.

I checked the code that generates the triangle fan, and I believe that would be enough to copy that method and make a slight modification to that to allow the triangle strip to create.
I am going to try to compile godot on my pc, but I heard that takes a lot (and my pc is low end, very low...). If I manage to I'll try to create that function myself.. lol, but I hope a more experienced C++ programmer would come to rescue.

I have searched for existing issues (feature proposals), but I just fund the proposal of the add quad, that was then abandoned in favor of the add_triangle_fan method (that helps a lot btw).

**Comment by clayjohn** [comment]
You don't actually need a separate function. To draw a triangle strip with SurfaceTool just use 

```
var st = SurfaceTool.new()
st.begin(Mesh.PRIMITIVE_TRIANGLE_STRIP)
#Add vertices in order
````

This will allow you to make a triangle strip with the SurfaceTool without having to make any changes to the engine.

**Comment by Toshiwoz** [comment]
Oh, cool, I'll try.
But I noticed that the add_triangle_fan is much faster as it's C++ function, imagine if a triangle strip can be added.

**Comment by clayjohn** [comment]
Yes. You are right. It would likely be much faster (especially for large triangle strips) to have a c++ function. If you want to dig into the engine code and add it then im sure you will make lots of people happy!

**Comment by Toshiwoz** [comment]
For those interested, I was able to create the function, and I tested it against the same mesh drawn with triangle fan...
a tile with random heights, 256x256 and 512x512, the difference, in both sizes is just a fraction of second, like 500ms.. so it doesn't seems to help  that much.. of course it may be the way I implemented it:
 - **triangle fan method:** is a series of fans made of 9 vertices arranged as a 3x3 square
 - **triangle strip method:** is a series of strips of the same width of the tile and height 1, so 256x1 or 512x1

I'm not even adding the PR, unless I find a reason for it.
![strip_mode_vs_fan_mode](https://user-images.githubusercontent.com/21297356/43809669-33e0c870-9a79-11e8-8c94-adc1f7c1355d.png)

As I was grabbing the screenshots I realized that sometimes it even takes less time with the add_triangle_fan method.. 😢
