### ISSUE TITLE
Projector texture on lights showing no effect

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#2002]
_Bugsquad edit:_ Originally seen in 1.1 stable

A texture can be specified as projector for a spotlight, however I can see no effect. I'm expecting the texture to be projected onto the objects. Or at least the light from the spotlight having the shape of the texture.

**Comment by volzhs** [comment]
no milestone for this issue?

**Comment by bojidar-bg** [comment]
Example from @zoiba from #2506 -- http://ffxrunner2.ffx.it/godot_testcases/testcase_projector_lamp.zip

**Comment by bojidar-bg** [comment]
Moving for 3.0, as 2.2 won't happen, plus, rendering engine is currently refactored :smile:

**Comment by reduz** [comment]
kicked to 3.1, as it needs to use the same architecture as decals.

**Comment by akien-mga** [comment]
Most rendering features are now planned to be implemented once we have the Vulkan renderer (scheduled for 4.0). As such, moving to milestone 4.0.

**Comment by OBKF** [comment]
Wow, it's that old huh?
So is there a possibility this hits 3.2 with decals?

**Comment by Calinou** [comment]
I'll close this in favor of https://github.com/godotengine/godot-proposals/issues/451, as feature proposals are now tracked in the Godot Proposals repository.
