### ISSUE TITLE
musl libc compatibility: Can the use of execinfo.h be made optional?

### ISSUE THREAD

**Issue by MazeChaZer** [godotengine/godot#20035]
Godot currently uses `execinfo.h` for its crash reporting. This is an extension that only glibc supports so compilation with musl libc doesn't work. Is it possible to check if glibc is used and only then use `execinfo.h`?

https://github.com/godotengine/godot/blob/ea473594086ebc4d0f5ec8d3cb5fac1607909571/platform/x11/crash_handler_x11.cpp#L43

**Comment by ronchaine** [comment]
I've found two ways to fix this.  Either disable crash handler for musl, with `#ifdef _GLIBC_`s, or as a better solution, install libexecinfo on a musl system.  It is a BSD project that is meant for situations where libc doesn't have execinfo.  Alpine linux has working APKBUILD for it.

**Comment by rofl0r** [comment]
this still causes a build error as of https://github.com/godotengine/godot/archive/3.0.6-stable.tar.gz . imo scons should check whether execinfo.h is available and simply disable it if not.

**Comment by akien-mga** [comment]
This was fixed in the master branch, not in 3.0.6.

**Comment by JL2210** [comment]
The execinfo that's used in Alpine has some issues. It uses builtin functions that can only be passed constant ints to do backtraces, and it relies on compiler optimizations to be efficient at all. I agree with @rofl0r. It should just be disabled if not on a glibc or *BSD system. Along with that, the project has been discontinued.

**Comment by rofl0r** [comment]
> It should just be disabled if not on a glibc or *BSD system.

no, it should *check* for whether the header and function is available, because it might be provided by libexecinfo, and turn it off if not, instead of assuming certain systems have certain properties.
