### ISSUE TITLE
BMP image loader fails to import images

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#20038]
**Godot version:**
3.1.dev master branch ea47359

**Issue description:**

![2018-07-08](https://user-images.githubusercontent.com/17108460/42419787-2d3a5da0-82c4-11e8-8f30-da5af842bd88.png)

The support for BMP was added in #15549
The BMP was created in MS Paint...

**Minimal reproduction project:**
[bmp_load_fail.zip](https://github.com/godotengine/godot/files/2173734/bmp_load_fail.zip)

**Comment by vnen** [comment]
Cc @SaracenOne

**Comment by SaracenOne** [comment]
Pretty simple mistake. Should be fixed now :)
