### ISSUE TITLE
Export project not complete on Windows ?

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#20039]
**Godot version:**
7dcaaba

**OS/device including version:**
Windows 10

**Issue description:**
I have a problem with export to Windows platform - it does not save the information from export menu !
I mean these fields does not affect the resulted binary
![image](https://user-images.githubusercontent.com/3036176/42419812-b05825aa-82c4-11e8-90e7-68144298d12f.png)

The resulted binary does not apply custom icon and information - the result is same as default For example(sorry if you dont understand russian language),

![image](https://user-images.githubusercontent.com/3036176/42419830-15ac1f60-82c5-11e8-8512-03021a7a0f56.png)

Or I something misunderstood ?

**Steps to reproduce:**
Try export your own project on windows..

**Comment by Calinou** [comment]
Have you downloaded rcedit from [its Releases page](https://github.com/electron/rcedit/releases) and set its path in the Editor Settings?

**Comment by Chaosus** [comment]
Oh, I didnt knew about it.. Thanks for information

**Comment by Chaosus** [comment]
Hmm.. after trying it - the data is changed to valid values, but icon still remains as Godot.

**Comment by Chaosus** [comment]
Tried other version of this tool, and its worked !

**Comment by PaulHMason** [comment]
@Chaosus Which version of rcedit worked for you (none of them work for me)?
