### ISSUE TITLE
Disabling "receive shadows" seems to have no effect.

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#2003]
I disabled "receive shadows" on various objects, including a TestCube, but it seems to have no effect at all.

**Comment by kubecz3k** [comment]
I can confirm the bug in Godot 2.0 alpha b2f9acb8c96aed0505cbac21661e21e4acef710f build
Video for quick look on what is going on: https://youtu.be/6KRb6G2K34Q
Sample project: https://dl.dropboxusercontent.com/u/168251/godot/bugsquad/ReceiveShadowIssue.7z

**Comment by volzhs** [comment]
I tested sample project with bd3dbe5fa306c96f79190ccfcd116436d27acb93 commit.
It works as expected now.

**Comment by akien-mga** [comment]
Indeed, it was fixed by @SaracenOne in 24bc7d8.
