### ISSUE TITLE
Bone2D fail deform when another instance is present in scene

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#20040]
**Godot version:**
3.1.dev.custom_build.e6734a2

**OS/device including version:**
Ubuntu Studio

**Issue description:**
Bone2D fail deform when another instance is present in scene

**Steps to reproduce:**
Make a 2d skeletal deform as the tutorial
Make a second skeletal deform in another poligon2d.

Video from the issue

[https://youtu.be/ZI45MTLXkT8](youtube)

**Comment by Ranoller** [comment]
Not only that, if you make a skeleton2D child of a Node2D and you resize that Node2D, the skeletal deform fails.

**Comment by marcosbitetti** [comment]
New updates:
now, a vertex assigned to any bone is hide from scene! (3.1 custom release from january/2019)

**Comment by reduz** [comment]
I would reaaally appreciate reproduction projects for this, as-is there is not much I can do.

**Comment by reduz** [comment]
I just can't reproduce this. Maybe you duplicated and forgot to re-assign skeleton?

**Comment by reduz** [comment]
Please reopen if enough information can be provided for reproduction, Closing in the meantime.
