### ISSUE TITLE
Android P notch support.

### ISSUE THREAD

**Issue by thorx2** [godotengine/godot#20044]
**Godot version:3.0.4**

**Device OS version:Android P**

**Issue description:**
We now have [support for iPhoneX's ](https://github.com/godotengine/godot/pull/18106)notch with the safe area fix. Since android P is a few months away it would be nice to have the support extended to the OS as well.

**Steps to reproduce:**
1. Create any project
2. Run on an android device running Android P.
3. In the developer settings turn on the notch.

**Screenshot:**
On a Pixel device running at FHD res.
![screenshot_1531060440](https://user-images.githubusercontent.com/7636788/42420899-69ca0efc-82ea-11e8-9418-1c289e21ff6e.png)

On a Pixel 2 XL device with an emulated top notch.
![screenshot_1531060444](https://user-images.githubusercontent.com/7636788/42420900-74a61a3c-82ea-11e8-9bf3-bf391f138457.png)

**Comment by hhuseyincihangir** [comment]
You can try these.
Project > Project Settings > General > Display > Window > Stretch 
Make: 
- Mode = 2D
- Aspect = keep_height (or keep_width, you've probably used keep)

**Comment by Tobi-La** [comment]
Is there any progress on this? Would be a great feature!

**Comment by Calinou** [comment]
@Tobi-La Not that I know of. Someone needs to step up to do it :slightly_smiling_face:
