### ISSUE TITLE
Confusing behavior of ScrollContainer when making a chatbox

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20043]
Godot 3.0.4

I am trying to make a kind of chat where each message is a separate label/control. I could get this to work using a `VBoxContainer` and appending items to it, with `grow direction` set to `Begin`.

But as soon as I put this `VBoxContainer` inside a `ScrollContainer`, everything breaks:
- The `VBoxContainer` suddenly shrinks to a width of 1, for no reason since `ScrollContainer` is not a container supposed to resize its children, AFAIK. Anchors can't be changed because they get reset everytime. I have set a minimum size but that makes resizing a PITA, ScrollContainers should not require this workaround IMO
- The overflow direction doesn't work anymore and messages get shifted to the bottom instead of the top

Here is the result, with both VBoxContainers having the same settings (except for those the ScrollContainer is screwing up):

First message:
![image](https://user-images.githubusercontent.com/1311555/42420811-8b6b5b00-82c3-11e8-8401-18064d6614cc.png)

More messages:
![image](https://user-images.githubusercontent.com/1311555/42420834-e50d2620-82c3-11e8-87c7-261434ad22da.png)

Try the project to see more details:
[ChatIssue.zip](https://github.com/godotengine/godot/files/2173811/ChatIssue.zip)

**Comment by ibrahn** [comment]
For the first bit, you're just missing a size flag. If you add Expand on the horizontal for the VBoxContainer, it will expand to the available width in the scroll container.
Also setting Expand on the Vertical, combined with the BoxContainer Alignment of End, will give you want you want with the first page of messages being aligned to the bottom.

The scrolling itself could use a better API and suffers a little from the changes to GUI sizing.

Here's what I've got at the moment.
Before I add a new message to the box (checking to see if we're currently scrolled to the bottom):
```
var vsbar = my_scroll_container.get_v_scrollbar()
if vsbar.value + vsbar.page >= vsbar.max_value :
        scroll_next_update = true
```
And then in _process (it has to be delayed to here to get the updated scroll bar size):
```
if scroll_next_update :
        var vsbar = my_scroll_container.get_v_scrollbar()
        vsbar.value = vsbar.max_value
        scroll_next_update = false
```
This keeps you scrolled to the bottom if you were already there, but leaves things alone if you were scrolled back reading older messages.

**Comment by ibrahn** [comment]
Took another look at the autoscrolling today.
Possibly a cleaner version is to connect the ScrollContainer's sort_children signal to a function that checks the current scroll position and queues a deferred call to do the scrolling (which will then be run after the container is finished updating sizes).

```
func _on_sort_children():
	var bar = get_v_scrollbar()
	if bar.value + bar.page >= bar.max_value :
		call_deferred("_scroll_later")

func _scroll_later:
	var bar = get_v_scrollbar()
	bar.value = bar.max_value
```

**Comment by KoBeWi** [comment]
As noted in the above comment, you just have to set your size flags and the container will have correct size. Not sure how to approach the auto-scrolling, but if it's a chat, it's better to use a RichTextLabel. Makes text formatting easier and it has a built-in scroll following functionality.
