### ISSUE TITLE
Mono exporting requires CS files to be exported as well

### ISSUE THREAD

**Issue by redxdev** [godotengine/godot#20053]
**Godot version:** e2b7a68db450d0d48d005719731619a49f96b7c8

**OS/device including version:** Win10 x64

**Issue description:**

Exporting a mono-based game requires you to include the cs files in the exported pck file, otherwise the engine fails to load said scripts despite the compiled assembly being present in the pck. This is especially an issue for closed-source/commercial games which probably don't want to ship the source to their game in the pck.

I'm guessing that fixing this will require #15661 unfortunately.

**Comment by redxdev** [comment]
Random thought on this - does the engine actually read anything from `cs` files at runtime? If not, a (hacky) fix would be to have only empty cs files put into the pck file.

**Comment by KellyThomas** [comment]
It's trivially easy to decompile very readable C# from the DLLs.

For most purposes it's probably best to consider the source published, FOSS or proprietary, once your product is released.

**Comment by redxdev** [comment]
I have to absolutely disagree. Decompiling C# may give you something semi-readable, but it will be missing variable names and comments, and will have all kinds of weird code due to compiler optimizations. It is a far cry from outright shipping your code with the game.

**Comment by neikeq** [comment]
@redxdev Oops, you're actually right. I forgot to change it:

https://github.com/godotengine/godot/blob/02372bfdf7e81bb3e1a154f824665fc9ddbcd566/modules/mono/csharp_script.cpp#L124
