### ISSUE TITLE
Audio bus output dropdown menu should use radio buttons, not checkboxes

### ISSUE THREAD

**Issue by voithos** [godotengine/godot#20054]
**Godot version:**
v3.0.2.stable

**Issue description:**
The audio bus output menu uses checkboxes, which implies that multiple outputs can be selected simultaneously (this would actually be a useful feature, I think). In reality, though, it behaves like a radio button, so the UI should reflect that if it's intentional.

![screenshot from 2018-07-08 17-45-12](https://user-images.githubusercontent.com/744228/42425951-3e6cee62-82d8-11e8-983f-31e5b61fc6d0.png)

I recall seeing similar checkbox-instead-of-radiobutton usage elsewhere in the editor, but can't think of specifics at the moment.

**Comment by akien-mga** [comment]
Indeed, this was fixed by #17730, also included in 3.0.3.
