### ISSUE TITLE
(Script Editor Shortcuts) Where is "insert line above/below"?

### ISSUE THREAD

**Issue by Ragnoroct** [godotengine/godot#20065]
**Godot version:**
3.0.4
**OS/device including version:**
Windows 10 x64

I'm used to changing my editor settings for **insert line above** -> **ctr+enter** and **insert line below** -> **ctr+shift+enter**

I tried searching the source code for the defined shortcut, but I couldn't find it. I think that it is somehow inherited or hard coded?

Does someone know where this functionality in the script editor is defined?

**Comment by akien-mga** [comment]
> I tried searching the source code for the defined shortcut, but I couldn't find it. I think that it is somehow inherited or hard coded?

Well what is the current shortcut? I don't see this feature at all in the script editor.

**Comment by Ragnoroct** [comment]
@akien-mga If you press "ctr+enter" or "ctr+shift+enter". It is a very common shortcut for editors. It doesn't show up in the shortcut list but it still works.

**Comment by Calinou** [comment]
Adding support for customizing TextEdit shortcuts in the editor will probably have to wait for #31739 to be done. (We can't add more editor-only code to TextEdit due to #29730.)

**Comment by Paulb23** [comment]
Fixed by #43663
