### ISSUE TITLE
All format video player idea

### ISSUE THREAD

**Issue by Logmytech** [godotengine/godot#20064]
I want to make a VR theater in Godot.

Then, I learnt that Godot support only one type of video and it's not at all ideal to play videos on users computer because most of the files on user's PC are generally not of that format.

Some people seem to be citing patents and other stuff when some one asks about this.

What if you wouldn't have to write any of the code for specific formats and not have to think of any format specific stuff. What if you had a library that played any video regardless of it's format.

The answer might be a wrapper for VLC library. Or maybe even other open source video playing libraries some other assets on Unity use.

This asset does just that it seems.
https://assetstore.unity.com/packages/tools/video/ump-pro-win-mac-linux-webgl-83281

Eidt: It seems there is already a C# project that aims to achieve this in multiple engines including Godot, but currently supports only Mobile platforms and Xamrim forms.

https://github.com/videolan/libvlcsharp

**Comment by Calinou** [comment]
There are plans to move video playback to GDNative libraries, so that it can be decoupled from the engine.

That said, when this will be done (and someone develops a library supporting the formats you need), you will still need to acquire licenses for patent-encumbered formats such as H.264 or H.265.

**Comment by Logmytech** [comment]
`you will still need to acquire licenses for patent-encumbered formats such as H.264 or H.265.`

Software patents aren't valid in my country and I assume in many other countries.

**Comment by akien-mga** [comment]
This is planned already and worked on by @KidRigger and @hpvb as part of GSoC 2018: https://github.com/KidRigger/godot-videodecoder/tree/throwaway-proto
