### ISSUE TITLE
Rotating a Light2D causes incorrect lighting on normal mapped sprites

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#20060]
**Godot version:**
3.0.4 Mono

**OS/device including version:**
KDE Neon
GTX 1060

**Issue description:**
When you rotate a Light2D it appears the lighting direction on normal mapped sprites gets wrongly rotated as well. See gif:
![output](https://user-images.githubusercontent.com/31383123/42444135-a34aca4c-836f-11e8-9ca0-40f812271464.gif)

**Steps to reproduce:**
1. Create a Light2D and a sprite with a normal map.
2. Rotate the light.
3. Observe results.

**Minimal reproduction project:**
[light2d_rotation_bug.zip](https://github.com/godotengine/godot/files/2175641/light2d_rotation_bug.zip)

**Comment by groud** [comment]
Yes, closing as a duplicate.
