### ISSUE TITLE
"Invalid to set ' xxx ' ( on base "InputEvent" )

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#2006]
It's impossible to set members of unioned classes in InputEvent ( like InputEventKey, InputEventMouse etc. ).

example:
```
var ev = InputEvent()
ev.type = InputEvent.KEY
ev.echo = false
```

gives:
```
"Invalid to set ' echo ' ( on base "InputEvent" )"
```

**Comment by TheoXD** [comment]
Works here on my end, I used to do something like this to simulate joystick input for virtual joystick.

**Comment by akien-mga** [comment]
Working fine for me too, with:
```
func _input(event):
	print(event.echo)
	if (event.type == InputEvent.KEY):
		print(event.echo)
```
I get an error on the first print() when doing a mouse click but the second one works fine.

Also this works fine:
```
	var ev = InputEvent()
	ev.type = InputEvent.KEY
	ev.echo = false
	print(ev)
```
