### ISSUE TITLE
Scene reference deleted asset and crashes in exported version

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#20066]
**Godot version:**
3.0.3

**OS/device including version:**
Windows 10 64

**Issue description:**
I made a 2D game. Later on, i deleted some assets and every scene that depended on them had missing dependencies. I said "open anyway" and saved. When i run from the engine, there are no problems, all my levels load fine. When I run from windows export, it says that it could not load the scene because it depended on a missing resource

**Steps to reproduce:**
Not exactly sure, it might be that i changed Godot version after i deleted the missing assets, don't know. The general idea is that the project might break if you delete some assets and you have a scene referencing them. (The broken scene was loaded from script)

**Minimal reproduction project:**
Could not make a minimal reproduction prject yet, sorry. With small scenes, everything seems fine.

**Comment by Calinou** [comment]
@QbieShay Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by QbieShay** [comment]
Hi @Calinou, sorry for the late reply. No, I could not reproduce anymore.
