### ISSUE TITLE
Build error on stable releases

### ISSUE THREAD

**Issue by maksloboda** [godotengine/godot#20074]
**Godot version:** 6a88e22423b5212fdb660d3cacad362382fbb805

**OS/device including version:** Ubuntu 17.10 64 bit

**Issue description:**
Tags 3.0.4-stable and 3.0.5-stable wont build tried both gcc and clang same errors

**Steps to reproduce:**
git checkout 3.0.4-stable or 3.0.5-stable
scons platform=x11 bits=64 tools=yes target=release_debug -j 4 (use_llvm=yes)

**OUTPUT**
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[  3%] Compiling ==> main/default_controller_mappings.gen.cpp
[  3%] Compiling ==> main/performance.cpp
main/default_controller_mappings.gen.cpp:2:10: fatal error: default_controller_mappings.h: No such file or directory
 #include "default_controller_mappings.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[  5%] Compiling ==> main/main.cpp
[  5%] scons: *** [main/default_controller_mappings.gen.x11.opt.tools.64.o] Error 1
Compiling ==> main/input_default.cpp
scons: building terminated because of errors.

**Comment by AlexZ005** [comment]
The master branch have the file "default_controller_mappings.h", error could be bypassed after putting it to the **main** folder of 3.0.5-stable

**Comment by KellyThomas** [comment]
This error means that you been to clean your repo of build artifacts when switching branches.

Both git and scons have clean commands for this purpose.

**Comment by AlexZ005** [comment]
well, yes, cloned godot repo and checked out 3.0.5, scons built executable, works, thanks

**Comment by vnen** [comment]
Yeah, if you build master and stable branches in the same clone, you need to clean up when you change branch. Otherwise the generated files will give those kind of errors.

**Comment by maksloboda** [comment]
Maybe this should be noted on the docs?

**Comment by maksloboda** [comment]
On a related note. Compiled binary size is bigger then the one on the site's download. Are stable releases compiled with non-default settings?

**Comment by KellyThomas** [comment]
The build scripts are the official releases are available here:

https://notabug.org/hp/godot-scripts

**Comment by Calinou** [comment]
> On a related note. Compiled binary size is bigger then the one on the site's download

You can strip debugging symbols from a binary with the `strip path/to/binary` command.

**Comment by maksloboda** [comment]
Offical builds have option debug_symbols=no when building
