### ISSUE TITLE
Exporting Templates Persist on Asking templates for custom builds

### ISSUE THREAD

**Issue by arvenjadeaguilar** [godotengine/godot#20071]
Godot version: 3.1.dev

OS/device including version: OSX high Sierra

Issue description: I have already compiled export templates by following this 
http://docs.godotengine.org/en/3.0/development/compiling/compiling_for_android.html

And Copied the apk's generated for release and debug into /users/[username]/.godot/templates based on the documentation but when I tried to open export my app. It was still asking for the templates. I even supplied it into the custom package hoping it will fix the issue but it still no luck. Hope you can help me on this one.

**Comment by volzhs** [comment]
I guess that is an old one.
http://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html
follow this guide.

**Comment by arvenjadeaguilar** [comment]
The content looks the same to me.. I already copied the release and debug apk to /users/[username]/.godot/templates

but its still the same.  It still wont let me export the project

**Comment by volzhs** [comment]
http://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html#installing-the-templates

it says...

> Installing the templates
> The newly-compiled templates (android_debug.apk and android_release.apk) must be copied to Godot’s templates folder with their respective names. The templates folder can be located in:
> 
> Windows: C:\Users\[username]\AppData\Roaming\Godot\templates
> Linux: /home/[username]/.local/share/godot/templates/[gd-version]/
> macOS: /users/[username]/.godot/templates

**Comment by volzhs** [comment]
oh. are you using mac?

**Comment by volzhs** [comment]
maybe `/users/[username]/.godot/templates/[gd-version]/`?

**Comment by arvenjadeaguilar** [comment]
yes I am using mac..

**Comment by arvenjadeaguilar** [comment]
already tried /Users/macbookpro/.godot/3.1.dev/templates/ also /Users/macbookpro/.godot/templates/3.1.dev still the same

**Comment by bruvzg** [comment]
On macOS templates are located in: `/Users/_user_name_/Library/Application Support/Godot/templates/...`

**Comment by arvenjadeaguilar** [comment]
Thank You very much @bruvzg that solves my problems.
