### ISSUE TITLE
Inspector "remote view" not closing automatically after closing game

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#20075]
1fc7973a00e17025441b6b8333e38d1606c1d304
x11

1. Start Game
2. Choose Remote
3. Close Game
4. Still shows 
![image](https://user-images.githubusercontent.com/4741886/42478685-eeb015bc-83d5-11e8-8184-29df5175a1dc.png)

**Comment by akien-mga** [comment]
Reopening as #20136 was reverted due to a regression (#22573).

**Comment by KoBeWi** [comment]
Seems to be fixed in 3.2 beta1.
