### ISSUE TITLE
Input.is_mouse_button_pressed() is failing during double clicks

### ISSUE THREAD

**Issue by matwhill** [godotengine/godot#20070]
**Godot version:**
 v3.0.5

**OS/device including version:**
Windows 10 on Lenovo Ideapad

**Issue description:**
When polling for input in _process(),  `Input.is_mouse_button_pressed(BUTTON_LEFT)` doesn't return true for a rapid second click. It appears as if some unseen double clicking functionality is blocking it.

Using `is_action_*` with the Input Map works as expected:
`Input.is_action_pressed("left_click")`

No other `Input.is_*` methods seem to have this issue, only `is_mouse_button_pressed()`.

**Steps to reproduce:**
Run the line following in _process():
`print(Input.is_mouse_button_pressed(BUTTON_LEFT))`
Try doing two clicks in a row at different speeds. I found that, while it should be printing `true` whenever the button is down, it prints `false` during additional clicks that occur within <1s of the first.

**Minimal reproduction project:**
The above line of code is all that's required, I'm happy to put together a test project if necessary :)

**Comment by API-Beast** [comment]
Ran into this issue in 3.0.6 as well.
