### ISSUE TITLE
FileDialog "Open many" inconsistent "Open" Button behavior 

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#20073]
1fc7973a00e17025441b6b8333e38d1606c1d304
x11

Mode: "Open many"

![peek 2018-07-09 21-41](https://user-images.githubusercontent.com/4741886/42472239-ecd9dbd4-83c0-11e8-9408-533077db3690.gif)

Should it always allow folders?

**Comment by alex9099** [comment]
Where is that dialog? You should be more specific on where the problem is :) also, is it expected to load folders or not in that case?

**Comment by raymoo** [comment]
@alex9099 Looks like the problem is that the enabledness of the "Open" button is different whether the file or the folder is selected first, even though the set of selected items is the same.

**Comment by AlexHolly** [comment]
I think the idea of "Open many" is to allow only Files and no Folders.


I was looking for a way to open many Files and Folders but this is another issue.

**Comment by alex9099** [comment]
@raymoo @AlexHolly yeah, i understood that, what i mean is, where does this problem appear? Where can you select multiple files in godot? (maybe i'm just being dumb and it is right in front of my eyes :D)

**Comment by AlexHolly** [comment]
I am not sure if it's possible in the editor since it uses the "EditorFileFialog". My case is in Game and uses the "FileDialog" like the issue topic describes.

**Comment by AlexHolly** [comment]
Looks like the signal "cell_selected" is not fired on second selected item (multiselect).

```
extends Tree 
 
func _ready(): 
	var root = create_item() 
	set_hide_root(true) 
	set_select_mode(SELECT_MULTI)
	set_size(Vector2(200,200))
	var child1 = create_item(root) 
	var child2 = create_item(root) 
	var child3 = create_item(root) 
	child1.set_text(0, "Subchild1") 
	child2.set_text(0, "Subchild2") 
	child3.set_text(0, "Subchild3")
	
	connect("cell_selected", self, "_on_Tree_cell_selected")
	connect("multi_selected", self, "_on_Tree_multi_selected")

func _on_Tree_cell_selected(): 
	print("Select: " + str(get_selected().get_text(0)))
 
func _on_Tree_multi_selected(item, column, selected): 
	print("MultiSelect: " + str(item.get_text(0)))
```


https://github.com/godotengine/godot/blob/master/scene/gui/file_dialog.cpp#L892
https://github.com/godotengine/godot/blob/master/scene/gui/file_dialog.cpp#L282
