### ISSUE TITLE
Godot  crashing on this C# project

### ISSUE THREAD

**Issue by M4gma** [godotengine/godot#20078]
**Godot version:**
3.0.5, 3.1

**OS/device including version:**
Windows 10
Linux Elementary OS 0.4.1

**Issue description:**
It looks like the crash occurs because the autoload script runs when the editor starts
[https://pastebin.com/nWQu598T](https://pastebin.com/nWQu598T)

**Minimal reproduction project:**
[ArrayMesh test.zip](https://github.com/godotengine/godot/files/2178270/ArrayMesh.test.zip)

**Comment by hydrocat** [comment]
ugh, maybe you could put this really big trace on pastebin or something like it

**Comment by M4gma** [comment]
here it is: https://pastebin.com/nWQu598T

**Comment by hpvb** [comment]
Did you install mono 5.12.0 on your distribution?

**Comment by M4gma** [comment]
Yes, mono 5.12.0 installed. I also tested on Windows, it is crashing too

**Comment by M4gma** [comment]
Hmm.... I forgot to mention this bug is also occurs on Godot 3.1

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by xfactor2000** [comment]
I'm having similar problems, what I do is I delete .mono folder. Does it help you?

**Comment by akien-mga** [comment]
Seems to work fine in 3.1 beta 6 (after removing the `.mono` folder from the old MRP).
