### ISSUE TITLE
Using INSTANCE_ID in a shader renders it useless.

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#20088]
Godot 3.0.2 + Windows 10

Reproduction: use this shader when rendering 2 (not tested in other cases) instances with a MultiMeshInstance object:
```
shader_type spatial;
render_mode blend_mix,unshaded,cull_back;

void vertex() {
        //removing the line below will make the shader work
	INSTANCE_ID;
       //same applies to "int a = INSTANCE_ID;"
}

void fragment() {
	ALBEDO = vec3(1.0,0.0,0.0);
}
```

When `INSTANCE_ID` is not used, shader draws the meshes as normal, when it is used, nothing is rendered. 

This makes instancing useless.

**Comment by Zylann** [comment]
I'm not sure the line you wrote is valid shader code, though.

**Comment by rokasv** [comment]
It is valid statement which does nothing. Also, you can change it to `int a = INSTANCE_ID;` and get the same result. Optimizing it out could be an issue, but this a reduced example, which I encountered when attempting to use the variable in a more complex shader.
