### ISSUE TITLE
InputEventMouseMotion is generated every frame even when the mouse doesn't move

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20086]
Godot 3.0.4
Windows 10 64 bits

Repro:
1) Create a new scene and add a single `Node` in it
2) Put this script on it:
```gdscript
extends Node

func _input(event):
	print(event)
```
3) Run the scene, place your move above the game, and don't touch anything:
Notice you get a flood of `[InputEventMouseMotion:3480]`, even though the mouse is not moving at all.

I didn't expect this because input events are... event-based. But here we get an event for something that didn't happen (also it could affect performance since that event is dispatched every frame).

Edit:
Surprisingly, this does not happen on my personal PC (which is almost the same setup), but it did happen at my office.
However, on my personal PC I also noticed that when I release a mouse button, it is always followed by a motion event, even if the mouse didn't move:

```
..._process...
..._process...
..._process...
[InputEventMouseButton:997]
..._process...
..._process...
..._process...
..._process...
..._process...
..._process...
..._process...
..._process...
..._process...
..._process...
..._process...
..._process...
..._process...
[InputEventMouseButton:1000]
..._process...
..._process...
[InputEventMouseMotion:1003]
..._process...
..._process...
..._process...
```

**Comment by moiman100** [comment]
I also have mouse motion after clicking, but not the flood while still.

**Comment by Zylann** [comment]
Ok, I found that it happens while a game is running in Unity Editor at the same time... it's not happenning strictly because Unity runs though, the project I was running might be doing something invisible to the mouse which makes Godot produce those events... fishy^^

Not sure what the extra motion on release is for.

**Comment by akien-mga** [comment]
If Unity messes up with the system input in a way that sends events to thirdparty applications, they really need to fix that. But it's not a Godot issue as such, we're only receiving those events, not emitting.

For the mouse motion after clicking issue, if reproducible, it might be worth opening a new issue.
