### ISSUE TITLE
Cubic interpolated animations have a hitch at the start and/or end

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#20087]
**Godot version:**
3.0.5 (steam)

**OS/device including version:**
Linux x64; X11; Debian Testing

**Issue description:**
A translation animation which is set to cubic interpolation appears to hitch either at the start or end of the animation. This makes looped or repeated animations look a bit janky.
This is evident both in the editor's animation preview, and when the scene is played.

The exact same track when using linear interpolation transitions smoothly from the end to the next iteration.

**Minimal reproduction ~~project~~ scene:**
This is a single self-contained tscn file which should demonstrate the issue for both 3D and 2D animations. You should be able to notice a definite hitch when the squares pass upwards through the centre line.
[testanim.zip](https://github.com/godotengine/godot/files/2181761/testanim.zip)

**Comment by KoBeWi** [comment]
Still valid in 15a9767
