### ISSUE TITLE
OptionButton doesn't fire item_selected() signal 

### ISSUE THREAD

**Issue by FeralBytes** [godotengine/godot#20089]
**Godot version:**
3.0.4
**OS/device including version:**
Linux Mint 18.3 Cinnamon
Kernel 4.13.0-45-generic x64
Intel Onboard Graphics Lenovo
**Issue description:**
The function _item_selected() is never called after changing the selection in the running GUI.
What I found is that this is a documentation error, the signal should be _selected as demonstrated in the minimal reproduction zip attached.
But the error also needs to be corrected in the Godot Editor as it shows the Node:Signals as item_selected() instead of selected().
I can fix the documentation but how do I fix the editor?
**Steps to reproduce:**
I created a OptionButton, then created a gd script attched to the button, containing.
```
extends OptionButton

#External References:
onready var submit_btn = get_node('/root/base/Submit_btn')

func _item_selected(id):
	print('id = ' + str(id))
	if id != 0:
		submit_btn.disabled = false

func _selected(id):
    print('This fires correctly; id = ' + str(id))
```

**Minimal reproduction project:**
[Godot_OptionButton_Error.zip](https://github.com/godotengine/godot/files/2181852/Godot_OptionButton_Error.zip)

**Comment by FeralBytes** [comment]
FYI fixing the documentation is a fix but this then overrides the default behaviour of _selected() which sets the self.text and self.selected variables to the id that is passed into _selected(). A better fix may be to actually create the _item_selected() func to allow for users to keep the default behaviour of _selected() and still receive a signal.  _selected() would need to be updated to call or signal _item_selected(id) .
Devs please let me know which way you want to go and I will adjust my pull requests as directed.

**Comment by vnen** [comment]
In your sample project you didn't connected the signal.

But apparently `_selected()` is an internal function called every time an item is selected (functions starting with `_` are internal and not documented since they aren't supposed to be used). It seems that if you override this function you break the behavior of the node. So you need to not declare a `_selected` function and properly connect the signal (either via UI or via code) to another custom function.

**Comment by FeralBytes** [comment]
OK I thought that I could connect to signals on the same Node as it's attached script by using _signal_name() as short hand. I now see that was an incorrect assumption on my part. Too bad would have been handy to stay more in code, but that is just my preference as a programmer.
