### ISSUE TITLE
File importer dialog does not see files added via the OS filesystem on real-time

### ISSUE THREAD

**Issue by fishywishy** [godotengine/godot#2009]
reproduce bug steps:

use Windows 8.1
download latest godot / run it as normal
download the project files ("pong assets") and unzip
create a project, as in  https://github.com/okamstudio/godot/wiki/tutorial_2d
(don't close godot)
go to Main menu -> Import -> 2d texture
add "pong assets" folder inside the new project's dir
See that the new folder doesn't appear in the /pong/ directory in the godot dialog.
put the individual image files into the /pong/ directory
See that the new files don't appear in the /pong/ directory in  the godot dialog.
go up a dir twice, in the godot file dialog.
navigate back to /godot/pong
See that the directory has been "refreshed" or "re-scanned" only now. This is the issue.

**Comment by akien-mga** [comment]
This is pretty common when not using the system's file manager but a custom one; if files are added via the OS file manager, it's usually needed to reload the folder to see changes (which is what you do by going to the parent folder and back).

The FileSystem tab has a "Re-scan Filesystem" button that is used exactly for this. To address this issue, I guess the same button could be added to the file chooser dialog.

**Comment by vnen** [comment]
Live reload could be done using a filesystem watch (not sure how all platforms handle this), though it might not be worth it.
