### ISSUE TITLE
Gear VR Oculus Signature

### ISSUE THREAD

**Issue by Paritosh97** [godotengine/godot#20094]
**Godot version:**
Godot 3.x

**OS/device including version:**
Not applicable

**Issue description:**
While working on Gear VR GDNative plugin for Godot, I came across a little complication.
The gear asks for an oculus signature file to be present in the apk's root://assets/ folder.
For now, we are just manually sideloading the signature file and rebuilding the apk.
I plan to COPY the signature file(s) in the Godot project structure to the apk's root://assets/ folder when it's being built.
Currently, the exporter seems to copy all the Resource files(Scene, png, gdc, etc) to the assets folder and skips the osig file. We want it to copy that too ONLY when GearVR is set as the ARVR interface.

**Steps to reproduce:**
Not applicable

**Minimal reproduction project:**
https://github.com/GodotVR/godot_gearvr

**Comment by akien-mga** [comment]
I'm not very familiar with the Android export workflow, but as I understand it, currently you should be able to whitelist the *.osig file in the export dialog to make sure it gets exported together with the known resources:
![screenshot_20180718_095956](https://user-images.githubusercontent.com/4701338/42867959-54b04a0c-8a71-11e8-8153-2044608fc00d.png)

For modules (but that's not available to GDNative yet AFAIK), there's a compilation option to include directories in the APK's assets folder, added in 8bb90fd5f3b9819bc3bc475e8b9f36c012d6c855.

To go beyond, a new feature should likely be implemented as part of #18865 to allow including arbitrary files in `root://assets/` based on project features.

**Comment by Paritosh97** [comment]
Thanks.
Can't believe I didn't see that.
Unfortunately, the Oculus signature file doesn't have any extension.
And the exporter doesn't seem to recognize the !(*.*) filter.
So I had to resolve to add an extension to the osig file and then add the filter.
Luckily the Gear still recognizes it.
Any suggestions to avoid this extra step?

**Comment by akien-mga** [comment]
You should be able to set `filename` as filter directly, even without extension.

**Comment by Paritosh97** [comment]
Tried that.
It didn't work.

**Comment by akien-mga** [comment]
Ok, I'll have a look at fixing those export filters then. It should support arbitrary filenames and not just globbed files with a given extension.

**Comment by akien-mga** [comment]
@Paritosh97 #20241 should help, but until it's merged you can also use `res://filename` or `*filename`.

**Comment by Paritosh97** [comment]
Thanks! It did the trick.
