### ISSUE TITLE
Rendering problems with Light2D and particles for WebGL 2 and desktop export

### ISSUE THREAD

**Issue by 95camarones** [godotengine/godot#20098]
**Godot version:**

v3.0.3.stable.official.e649ec7

**OS/device including version:**

MacBook Pro, Mac OS 10.11.6, Intel HD Graphics 4000 GPU
Firefox 61.0.1 (Can't get it to even start in Chrome)

**Issue description:**

There are some other issues logged for Light2D, but none seem to describe the behaviour that I see here.

I have been using a Light2D node on Mix mode to darken a scene. When played in the editor or exported MacOS particles are rendering incorrectly if they are covered by the the Light2D. Overlapping sections of particles become much darker but the rest of the particle stays the original colour. 

The correct behaviour with Light2D disabled
<img width="85" alt="correct1" src="https://user-images.githubusercontent.com/41108485/42559889-499a0d9e-84ed-11e8-8b1f-2791eeaf7a96.png">

Darkening effect with Light2D enabled.
<img width="89" alt="incorrect1" src="https://user-images.githubusercontent.com/41108485/42559909-557b0ac8-84ed-11e8-9f7f-3a735254d5be.png">

The effect is different when exported to HTML5. The red particles shown above fail to render at all and I get a weird x-ray effect where the silhouettes of all nodes are visible, even if they should be rendered behind other nodes.

Light2D disabled. Zombie behind trees and trees behind banner at bottom (GUI nodes, but children of Node2D)
<img width="202" alt="correct2" src="https://user-images.githubusercontent.com/41108485/42560212-128d44b4-84ee-11e8-9ea1-e2766c2fefc9.png">

Light2D enabled. Silhouettes become brighter as energy or opacity of Light2D increases.
<img width="190" alt="incorrect2" src="https://user-images.githubusercontent.com/41108485/42560311-47a9bdf8-84ee-11e8-9218-4b2c031961e9.png">

**Steps to reproduce:**
Open the minimal example project and move the light2d around in the editor.
The darkness of the particles varies according to the alpha of the light2d texture.
The silhouetting effect is visible (only in the editor) where the light2d intersects the gui panel. 

**Minimal reproduction project:**

[issue20098.zip](https://github.com/godotengine/godot/files/2186010/issue20098.zip)

**Comment by eon-s** [comment]
What browser? and do you have a minimal example so others can test quickly?

**Comment by 95camarones** [comment]
Firefox 61.0.1 tested on both Mac and Windows. I have now added an example

**Comment by bluepandion** [comment]
Could this be a related issue?
#17542 Light2D misbehaves if nodes use custom draw() 

The behavior looks similiar. As if the effect of the light is stacking for every "sub-object".

**Comment by clayjohn** [comment]
We are no longer working on the WebGL2 backend due to poor driver support on most systems. We recommend you use the GLES2/WebGL backend instead. 

Unfortunately, that means this bug just isn't going to be fixed, sorry.
