### ISSUE TITLE
Access node info in debug mode?

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#20108]
I have a scene setup like this:

```
Node2D
    Sprite
    Enemy

```
While in debug I cannot access the properties of $Sprite or $Enemy.  I can look at variables but I don't see a way to see the nodes info in the debug screen.  Is this a feature that needs to be added or is it there already?

**Comment by ElfEars** [comment]
It's directly in the node tree and inspector now instead of the old mini version.

**Comment by ondesic** [comment]
What version did that start in? Does 3.04 have it?

**Comment by ondesic** [comment]
I found it.  You have to click on "REMOTE" and not "LOCAL" to be able to see them.

**Comment by groud** [comment]
I guess this is solved then ?

**Comment by Calinou** [comment]
> What version did that start in? Does 3.04 have it?

The remote inspector made its debut in 2.0, it's been here for a while now :slightly_smiling_face:

It was redesigned in 3.0 and is now at the same place as the local inspector while the project is running.
