### ISSUE TITLE
Hang with latest Intel graphics driver 24.20.100.6136 on Windows 10 64-bit

### ISSUE THREAD

**Issue by mobybrick** [godotengine/godot#20106]
**Godot version:** 2.14, 3.0x

**OS/device including version:** Windows 10 64-bit.  Any Intel integrated graphics (6-8th gen, desktop or laptop) using latest driver 24.20.100.6136

**Issue description:** Godot hangs at start, and hangs when you try to do almost anything.

**Steps to reproduce:** Install Intel driver 24.20.100.6136.  Run Godot. Keeps hanging and being unresponsive straight away. Main Window will open after a while, but every action requires user to move focus away from Godot and then back again, and still not always come back.  Revert to Intel 24.20.100.6094 and all OK.

**Minimal reproduction project:**No project required.

**Comment by vnen** [comment]
If reverting the driver works, then it seems like a driver bug.

**Comment by mobybrick** [comment]
Very possibly - but the only other thing to add is that so far I can't find any problems with any other app using the latest driver - Kdenlive, VLC, FreeCAD, Blender all OK.

**Comment by akien-mga** [comment]
This should be reported to Intel as a regression in their Windows 10 drivers.

Their forum for reporting graphics drivers bug seems to be https://communities.intel.com/community/tech/graphics/
And this sticky thread has details on the info you should provide in your report: https://communities.intel.com/thread/126119
