### ISSUE TITLE
directory class doesn't seem to work in user://

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#2010]
I don't seem to be able to create a directory in user:// or detect file_exists() using directory (but File works for that)

This code does not work:
<code>
       
        export var local_data_dir = "user://SA_local_data"
        ...
        var dir = Directory.new()
        #if local_data_dir directory does not exist
        if (!dir.dir_exists(local_data_dir)):
        #	create local_data_dir
                logger.info(logstr("Creating " + local_data_dir))
                dir.make_dir(local_data_dir)

        if (!dir.file_exists(highScoreFile)):
                ...
</code>

(could be by design to prevent stuff like user://../../ )

**Comment by akien-mga** [comment]
Duplicate of #1680.
