### ISSUE TITLE
Moving a script does not update `extends "res://..."` lines in other scripts

### ISSUE THREAD

**Issue by voithos** [godotengine/godot#20109]
**Godot version:**
v3.0.2.stable, but also checked at recent master

**Issue description:**
When clicking a .gd script in the editor and selecting `Move To..`, I expected any references to said script to get updated throughout the project, including the `extends "res://...gd"` lines in other scripts that may be inheriting from the script that was moved. Unfortunately, those lines don't seem to get updated.

**Steps to reproduce:**
Create a script that extends from another script (`extends "res://foo.gd"`), then move the *base* script somewhere else and observe that the `extends` reference doesn't get updated.

![screenshot from 2018-07-11 21-23-58](https://user-images.githubusercontent.com/744228/42612783-188efaa6-8552-11e8-98b0-1351a60450a0.png)

**Comment by voithos** [comment]
I guess in some sense this isn't specific to moving scripts and applies to any `res://` path used in scripts, including things like `preload()` calls, etc. Maybe this should be a simple search+replace for the res string through all existing scripts?

Searching through all scripts in a project for every file move could be a bit expensive, though - perhaps this could use a toggle option in the move-file dialog to control whether or not scripts are updated (default true)?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/899, as feature proposals are now tracked on the Godot proposals repository.
