### ISSUE TITLE
"Open in Editor" button doesn't work with visual scripts

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#20111]
Godot Master, Linux

In the inspector, the "Open Editor" under the "scripts" sections works fine for a gdscript, but doesn't do anything if the script is a Visual Script. The icon in the scene tree dock works as it should.

Steps to reproduce:
- create a visual script for a node in the tree
- go back to the scene, and check the inspector for that node
- scroll to the script section and open it if necessary
- click the "open in editor" button, nothing happens

**Comment by akien-mga** [comment]
Reopening as #20112 was reverted.
