### ISSUE TITLE
Auto generated arguments (text_changed) and no comment end

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#20113]
Godot version: 3.0.4

OS/device including version: Win7

Issue description:
Some signals autogenerate outputs (arguments) but these are not visually indicated:
self.connect("text_changed", get_node("../../../NPCPanel"), "_changeVariable", [get_name()])

function _changeVariable recives 2 arguments: the one from "text_changed" and [get_name()]

This is messy and rubs me the wrong way it should be [Changed text, get_name()]

I would just insert [/* Changed Text, */ get_name()] but # seems to only work for the whole line. Something like /# would be nice.

**Comment by Zylann** [comment]
@BrahRah this extra array has a different meaning. That's values that are fixed at connection time, not values you receive at emission time.

**Comment by ibrahn** [comment]
The purpose of this array is to add additional parameters to the call, not to document the signature of the receiving function. The receiving function will do that just fine itself. GDScript doesn't have function overloading, so there's no real opportunity for confusion there.

**Comment by vnen** [comment]
If you had to repeat all the signal arguments in every `connect()` you call, it would get very repetitive.
