### ISSUE TITLE
Assigning a custom theme for your game breaks the editor's UI

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20123]
Godot 3.0.4, also happens in master 085483e88577ea91400a1ee46bc4321340824c51
Windows 10 64 bits

I wanted to create a global theme for my game, but when I assigned it in `ProjectSettings -> Theme -> Custom`, it slightly broke the editor's UI:

![image](https://user-images.githubusercontent.com/1311555/42662966-859efa9a-862b-11e8-93cf-9b2565eb9af7.png)

![image](https://user-images.githubusercontent.com/1311555/42663003-b12e8374-862b-11e8-8738-94bc7b372d37.png)

Repro:
1) Create a new `Theme`
2) Save it as a file
3) Assign it in `ProjectSettings -> Theme -> Custom`
4) Restart the editor: notice UI is broken

**Comment by Vultraz** [comment]
Also breaks the color picker:

![](https://cdn.discordapp.com/attachments/495815752654520330/565969592116051968/unknown.png)

**Comment by williamd1k0** [comment]
This bug is really annoying me :/

The color picker is practically unusable for me..
![Screenshot_2019-04-18_03-24-46](https://user-images.githubusercontent.com/10428035/56339424-9c74fa00-6184-11e9-8b92-d452d850c38a.png)

**Comment by KoBeWi** [comment]
This is already fixed, tested in d711c57d7
