### ISSUE TITLE
ERROR: _install_from_file @ editor/export_template_manager.cpp:286

### ISSUE THREAD

**Issue by zacharytyhacz** [godotengine/godot#20125]
**Godot version:**
3.0.5.mono.stable

**OS/device including version:**
windows 7 64 bit 
3.00ghz intel 2udo
 4 gb ram

**Issue description:**
Trying to export my project. Says I am missing export template so I go to manage export templates and install from the file that I downloaded from the website, the .tpz, and once I hit open to install it, this error comes through in the log and it continues through it's ' installation.' Upon going back to the export screen, it still says I am missing the export template so it does not install.

**Steps to reproduce:**
turn off Windows defender 

exclude godot on my drive as well as in my AppData / godot / folder in my Antivirus software

open godot as administrator and my project 

turn off ' safe save on backup then rename ' 

go to Project > export > add > Android 
' Export templates are missing " > Manage Export Templates

current version : 3.0.5.stable.mono ( installed )
installed versions:  3.0.5.stable.mono ( current )

install from file, select the downloaded " Godot_v3.0.5-stable_mono_export_templates.tpz " 

log prints : 

ERROR: _install_from_file: Condition ' !f ' is true. Continuing...:
At: editor/export_template_manager.cpp:286
closed

If i go back to the Project > Export, it still says export template is missing.
I've tried googling all over for days now trying all sorts of solutions such as windows safe mode, reinstalling, I cannot find a similar issue with this error message. Some please give a hand!

**Minimal reproduction project:**

**Comment by mrcdk** [comment]
Mono only support desktop export templates for now
https://godotengine.org/article/maintenance-release-godot-3-0-3

**Comment by akien-mga** [comment]
I think this was fixed by #20186.
