### ISSUE TITLE
I can't run or edit projects

### ISSUE THREAD

**Issue by redmarbleroad** [godotengine/godot#20121]
Hi. I recently downloaded Godot. The editor launches normally, but when I select a project and try to open it, Godot gives me this message: Alert! Can't open project. When I try to run it, it tells me that it can't run it because "no main scene has been defined". It then tells me to change this in Project Settings, but I can't find them. This issue is probably down to my own lack of experience, since I've never done gamedev of any kind before. This might not be an issue, but perhaps you could point me to a better place to find a solution. Thanks.
**Godot version:**

Version 3.05

**OS/device including version:**

Linux (Ubuntu 16.04.04), Acer chromebook R11

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by redmarbleroad** [comment]
I have tried a new project. I'm not sure if it was a 2.X project or not, but I created it in the project manager, so I don't see why it would be incompatible. Here's the exact message I got when I tried to run the project: Can't run project. No main scene defined. Please edit the project and set the main scene in "project Settings under the Applications category.

**Comment by LikeLakers2** [comment]
You can find the option to select a main scene in the top-left menu -> Project -> Project Settings. Under the Application category, click Run, and it should be labeled Main Scene.

However, Godot should be giving you a button to select the main scene when that "No main scene defined" prompt comes up. If you still can't find the setting, then hit the Run button, and click the button labeled "Select". It'll bring up a file selector -- just select whatever scene you want to be your main one.

Also, welcome to Godot! Don't worry about being new to game-dev, everyone's gotta start somewhere. :)

**Comment by vnen** [comment]
> However, Godot should be giving you a button to select the main scene when that "No main scene defined" prompt comes up.

Not when you try to run directly from the Project Manager. First you need to click "Edit" to open the project in the editor.
