### ISSUE TITLE
Unable to change environment's ambient_light_energy from gdscript

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#20128]
**Godot version:**
3.x

**OS/device including version:**
ubuntu, nvidia

**Issue description:**
I have a scene with a WorldEnvironment containing an custom Environment. I would like to change the ambient light. However setting the variable in gdscript appears to have no effect.

**Steps to reproduce:**
Create a scene
Add a WorldEnvironment and fill it out, set ambient light energy to 1.
Attach a script to the Scene
In the _ready or in a function called by a button have the following code
`get_node("WorldEnvironment").environment.ambient_light_energy = 0.1`

Run the scene, the ambient light does not change.

**Comment by Zireael07** [comment]
You need to use get_node("WorldEnvironment").get_environment().ambient_light_energy.

**Comment by dodgyville** [comment]
thanks!
