### ISSUE TITLE
CPU Particles converter issues

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#20126]
**Godot version:**
Godot master build (d488c35ef)

**OS/device including version:**
Windows 10

**Issue description:**
I found the following problems when converting Particles into CPU particles:
1. Converter dont save old node name and set name of converted node to `CPUParticles`
2. Converter dont migrate node translation and rotation and set to zero
3. `Life time` and `gravity`  of converted CPUParticles affect in different way than in original particles 
![2018-07-13_09-29-51](https://user-images.githubusercontent.com/3992195/42669666-e84000ea-8680-11e8-9bc6-fbf4d339e7df.gif)

**Minimal reproduction project:**
[godot-particle-test.zip](https://github.com/godotengine/godot/files/2191050/godot-particle-test.zip)

**Comment by karroffel** [comment]
Technically it's not about rendering either. The particles are computed outside of the renderers, those just display the computed elements.

The actual computation happens here

https://github.com/godotengine/godot/blob/911febb41f95481f3cb6290ba810c25885427b16/scene/3d/cpu_particles.cpp

**Comment by kosz78** [comment]
@reduz All works correct except `Initial Velosity -> Velocity`. 
In CPU particles this parameter affects more strongly
This is sample project 
[godot-particle-test.zip](https://github.com/godotengine/godot/files/2227516/godot-particle-test.zip)
