### ISSUE TITLE
new() subclass from script's subclass itself results in error

### ISSUE THREAD

**Issue by Ciastex** [godotengine/godot#2012]
Suppose we have a following script:
```gdscript
extends Node2D
 
func _ready():
        var item = MyItem.new()
        item.add_item()
 
class MyItem:
        extends Node2D
        var script = get_script()
       
        var items = []
               
        func add_item():
                items.append(script.MyItem.new())
```
This script seems to be perfectly fine, although at runtime the last line - specifically the `script.MyItem.new()` directive - results in execution error which reads as follows:
> Invalid get index 'MyItem' (on base: 'GDScript').

But it should return the subclass which is requested.

**Comment by akien-mga** [comment]
Does it work if you put the class definition *before* _ready?

**Comment by akien-mga** [comment]
The issue is still valid in the current master branch.

**Comment by reduz** [comment]
This is not a bug, instead of:

items.append(script.MyItem.new())

you should do

items.append(script.new())

keep in mind you will be creating a cyclical reference which will not be erased by doing this unless items[] is cleared
