### ISSUE TITLE
Unable to move file, 'FileSystemDock::_move_operation_confirm' expects 2 arguments from dir_selected signal but called with 1

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#20129]
**Godot version:**
3.1.x

**OS/device including version:**
ubuntu, nvidia

**Issue description:**
Attempting to move a tscn file into a new directory via what I think is called the filesystem dock (the thumbnails of files on the lhs of the editor) does nothing and in the terminal the following error is thrown:

`ERROR: emit_signal: Error calling method from signal 'dir_selected': 'FileSystemDock::_move_operation_confirm': Method expected 2 arguments, but called with 1
`

**Comment by ibrahn** [comment]
Just to confirm, this is referring to selecting "Move To..." from the right-click/context menu and then picking a directory in the dialog that pops up?
No problems with drag and drop?
