### ISSUE TITLE
 Not able to set or change Sprite Rotation Degree in Inspector.

### ISSUE THREAD

**Issue by samdaiya** [godotengine/godot#20130]
**Godot version:** 3.0.5.stable.custom_build

**OS/device including version:** ManjaroLinux 17.1.11

**Issue description:** I was trying to make a simple animation using "Sprite Node" and "Animation Player". I want to rotate my sprite to the specific Rotation Degree using Inspector. So, I opened animation tab and then selected specific time frame and then selected Sprite node to change Rotation Degree but when I Hit enter it does not apply changes to the Rotation Degree.

**You can see that in this Screenshot below.**

![screenshot_2018-07-13_16-53-33](https://user-images.githubusercontent.com/17422674/42675244-cd229a6a-8690-11e8-9678-943aaabe2fb0.png)

Note: Rotation Degree feature works fine when i am not working with animation player.

**Steps to reproduce:** Extract the project and then import in Godot Engine 3.0.5 and try to change rotation degree using inspector windows for animation player.

**Minimal reproduction project:** [godot_project.tar.gz](https://github.com/godotengine/godot/files/2191428/godot_project.tar.gz)

**Comment by sketchyfun** [comment]
I may have misunderstood, but If you want to update a specific keyframe, either place the timeline position indicator over the existing keyframe, change the value in the inspector and then press the key icon next to the property, or instead you can select the keyframe and then press the little pencil icon in the bottom right-corner and you'll be able to directly edit the keyframe values

**Comment by akien-mga** [comment]
I can't reproduce it with 3.0.5-stable on Linux (Mageia 6 x86_64). And your screenshot shows a Sprite rotated by 90° while you're trying to input 90° as its rotation, so I guess it's expected that nothing happens...?

**Comment by samdaiya** [comment]
When I try to change to different degree it doesn't work.

**Comment by akien-mga** [comment]
It works for me. Can you record a video of what doesn't work?

**Comment by samdaiya** [comment]
I was using custom build maybe because of that i got this issue, When i installed Official Stable build of Godot v3.0.5 it solved my problem.
