### ISSUE TITLE
Export Debug setting should be persistent across editor runs

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#2013]
I set debug off when I export.  If I exit the editor then come back in, the next time I export debug is back on.

**Comment by akien-mga** [comment]
I confirm that the above-described behaviour is still current (i.e. the editor always proposes debug=on regardless of what was done before).

**Comment by akien-mga** [comment]
Is this still valid now that the debug toggle was moved in #4466?

**Comment by captainwasabi** [comment]
No, it seems to remember the setting now.

**Comment by akien-mga** [comment]
Thanks, closing then.
