### ISSUE TITLE
Strange behavior of BlendSpace2D in 8-way animation

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#20135]
**Godot version:**
Last version from https://hugo.pro/projects/godot-builds/

**OS/device including version:**
Windows 10 x64

**Issue description:**
Hello. I try to make 8-way animation by using BlendSpace2D, but after change blend_postion it has small time lag before animation changed. I think, it's wait when current animation finished. 
https://gfycat.com/DelightfulDizzyHart

**Minimal reproduction project:**
[AnimationBlendBug.zip](https://github.com/godotengine/godot/files/2192983/AnimationBlendBug.zip)

**Comment by reduz** [comment]
added.
