### ISSUE TITLE
Apple Rejects iOS App For Using MoltenVK

### ISSUE THREAD

**Issue by hamad-almamari** [godotengine/godot#20139]
Hello World !
[https://www.phoronix.com/scan.php?page=news_item&px=Apple-Rejects-iOS-MoltenVK](https://www.phoronix.com/scan.php?page=news_item&px=Apple-Rejects-iOS-MoltenVK)

**Comment by OvermindDL1** [comment]
Not for using MoltenVK, but because MoltenVK was using IOSurface on older iOS versions (when it's only supported on newer iOS versions), MoltenVK has already removed IOSurface usage entirely so it's not an issue anymore anyway.

**Comment by vnen** [comment]
There's no need for alarm. The MoltenVK devs already said this is likely a valid reason to reject and the library is already patched to fix this issue: https://www.phoronix.com/scan.php?page=news_item&px=MoltenVK-IOSurface-PR

Last but not least: Godot does not use Vulkan and do not use MoltenVK. It is in the plans, but until then this is not a valid issue. Feel free to bring the discussion to other [community channels](https://godotengine.org/community) but the GitHub tracker is for bugs only, and this is not a bug in Godot.
