### ISSUE TITLE
Need a simple way to clear yield() in queue

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#20143]
Right now I am running into a problem.  There are a few ways for a player to add a Yield() function without completing the other Yields already active.  They all build up until yield() is completed.  Then all the yields in the queue get fired.
Before I start a new yield() I need to be able to cancel any pending yields.  Is there a way to do this, or can this feature be added?

**Comment by Calinou** [comment]
[`yield()` was replaced with `await` in Godot 4.0](https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged
, closing.
