### ISSUE TITLE
Discard renders black in spatial shader

### ISSUE THREAD

**Issue by DavidSichma** [godotengine/godot#20159]
**Godot version:**
3.0.5

**OS/device including version:**
Windows 10 (NVidia) and Debian (AMD)

**Issue description:**
Using `discard;` in `fragment()` inside a spatial shader renders the mesh black. It shouldn't render anything.

![discard_bug](https://user-images.githubusercontent.com/25692790/42727310-a2b25544-87a4-11e8-9862-41ccdb587584.png)

**Steps to reproduce:**

1. Use `discard;` in `fragment()` inside a spatial shader.
2. The mesh is rendered black.

**Minimal reproduction project:**
[bug_discard.zip](https://github.com/godotengine/godot/files/2195158/bug_discard.zip)

**Comment by DavidSichma** [comment]
I found a workaround using Alpha Scissors:

    ALPHA = 0.0;
    ALPHA_SCISSOR = 1.0;

This works just fine. 

But for some reason, replacing just one `discard;` will also fix every remaining `discard;`.
The [documentation](http://docs.godotengine.org/en/latest/tutorials/3d/spatial_material.html#use-alpha-scissor) states that using Aplha Scissors puts the objects into the opaque pipeline. Could it be that using `discard;` puts the objects into the wrong pipeline?

**Comment by Zylann** [comment]
But writing to ALPHA makes the object go to the transparent pipeline, which has no need for `discard`.

**Comment by DavidSichma** [comment]
I did some testing. If I remember correctly, objects in the transparent pipeline do not cast shadows, whereas objects in the opaque pipeline do.

- Only `discard`: Draws opaque black pixels which do also cast shadows.
- Writing only to ALPHA: fixes `discard` and puts object into transparent pipeline (as no shadow is casted).
- Writing only to ALPHA_SCISSOR: fixes `discard` and puts object into opaque pipeline (shadows casted).
- Writing to both ALPHA and ALPHA_SCISSOR: fixes `discard` and puts object into transparent pipeline (no shadows).
- `render_mode depth_draw_alpha_prepass;` enables shadows for transparent objects. And fixes `discard`.

However, I found out where that black color comes from. It is the background color.
If _Sky_ is selected in the WorldEnvironment then the discarded pixels are black.
If _Clear Color_, _Custom Color_, _Color+Sky_ or _Canvas_ is selected then the discarded pixels are of the specified color.
If _Keep_ is selected then the discarded pixels draw whatever has been there in the last frame.

I don't think that this is the intended behavior: In 2D discarded pixels just aren't drawn, whereas in 3d discarded pixels draw the background color.

I think, I will use `if(false){ALPHA_SCISSOR = 1.0;}` for now.

**Comment by DavidSichma** [comment]
I think i located the bug.

If the shader does not use any fancy effects, such as transparency, alpha_prepass or `discard`, a generic solid material is used for the depth pass.

But if only `discard` is used, this solid material will still be used. The reason is that Godot's Shader Compiler does not keep track if `discard` has been used.

But why is every variable kept track of but `discard`? Because `discard` is not a variable. It's a flow control. Godot keeps track of every variable but does not of flow controls. This way `uses_discard` will never be true.

I will file a PR soon.
