### ISSUE TITLE
gl version error while supported

### ISSUE THREAD

**Issue by err0r1nc0de** [godotengine/godot#20153]
**Godot version:**

3.0.5 stable win32

**OS/device including version:**

windows 7 32 bit with ati radeon hd 4300 series

**Issue description:**

error:
gives a message with "cannot create opengl context"
" it looks like your graphic drivers doesnt support opengl 3.3" (it does)
"godot will self destruct as soon as you close this message"
on console:
ERROR: initialize: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:147
ERROR: initialize: Your system's graphic drivers seem not to support OpenGL 3.3
/ OpenGL ES 3.0, sorry :(
Try a drivers update, buy a new GPU or try software rendering on Linux; Godot wi
ll now crash with a segmentation fault.
   At: drivers/gles3/rasterizer_gles3.cpp:157

**Comment by Zireael07** [comment]
your drivers are probably buggy?

**Comment by err0r1nc0de** [comment]
sorry it looks like my drivers support opengl 3.1
