### ISSUE TITLE
No Orientation option when export to iOS.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#20164]
**Godot version:3.0.5

**OS/device including version:**

**Issue description:**

When export  iOS project, the orientation of the project is alway landscape left and landscape right.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by jjay** [comment]
It is fixed in master and handled by window/handheld/orientation project settings.

**Comment by akien-mga** [comment]
I've marked #19840 for cherry-picking, so it should get fixed in a future 3.0.x release.

**Comment by alexzheng** [comment]
Then is this setting also works for Android?
Will the Screen/Orientation for Android export be removed?
