### ISSUE TITLE
VisualShader OpenGL error when using a Texture2D constant node

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#20162]
**Godot version:**

Godot master f6ce73f

**OS/device including version:**

Nvidia GTX 1070 Windows 10

**Issue description:**

The shader:

![https://i.imgur.com/V0AXVdB.png](https://i.imgur.com/V0AXVdB.png)

The OpenGL error:
```
drivers\gles3\shader_gles3.cpp:168 - CanvasShaderGLES3: Fragment Program Compilation Failed:
0(258) : error C7528: OpenGL reserves names containing '__'
```
The generated name that triggers that error:
```
258:   vec4 m__tex_read=texture(color_texture, m_n_out2p0.xy);
```

**Comment by DavidSichma** [comment]
The underlying issue (#12880) has been resolved. This should work now.

**Comment by akien-mga** [comment]
Indeed, thanks.
