### ISSUE TITLE
"Closest/furthest number" functions.

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#20168]
**Godot version:** 3.0.5

It would be nice to have functions for finding ~~the absolute-value minimum or maximum~~ the closest or farthest number from a given target number. ~~That is,~~ Or, if no target is specified, the functions would return the number which is closest to 0, or farthest from 0, respectively.

This should be given a low priority though.

**Comment by Zephilinox** [comment]
So instead of Min(Abs(a), Abs(b)) you can to do AbsMin(a, b)? Doesn't really seem necessary to me, I don't think I've ever had to do that or even seen a function that does. Neither Unity nor Unreal have such a function, nor any other math library I can find such as C, C++ or C#.

**Comment by aaronfranke** [comment]
@Zephilinox No, not quite. `Min(Abs(-1),Abs(-2))` would return `1` but I need it to preserve the negative sign and return `-1`. But it would also need to successfully compare `-2` and `1` and identify `1` as the absolute minimum. Basically "Return the number closest to zero" but I couldn't think of a better name for this than "AbsMin".

I think this functionality is niche and so it's definitely a low priority at least.

**Comment by vnen** [comment]
If sign is important, what would be the proper result of `AbsMin(1, -1)`?

**Comment by aaronfranke** [comment]
Both are equally good results. Either is acceptable as a result.

**Comment by nobuyukinyuu** [comment]
```gdscript
func closest(values, target=0):
	var first = true
	var runningTally
	var result
	for value in values:
		var tally = abs(target-value)
		if first:
			runningTally = tally
			result = value
			first = false
			continue
		if tally < runningTally:
			runningTally = tally
			result = value
	return result
```

**Comment by aaronfranke** [comment]
Good idea @nobuyukinyuu I hadn't thought of making it a general case for closest to any number.
