### ISSUE TITLE
Visual shaders dont have flow control operators

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#20175]
For now it misses `if/else`, `while` and `for` loops

**Comment by reduz** [comment]
Indeed, this makes them simpler to make. Most visual shader editors I know work this way.

**Comment by Chaosus** [comment]
Do you mean that they are not required and may not be implemented ?

**Comment by reduz** [comment]
Probably not going to be implemented. Adding flow control ports like Visual Script does would make them  unnecessarily more complex for 99% of the tasks visual shader editing is aimed at.

**Comment by Chaosus** [comment]
Ah, true that even UE4 does not have loops inside material editor, but it have if/else (for simple floats). Not a bad idea to add this..
