### ISSUE TITLE
Script Editor Find in Files Dialog Feature Request

### ISSUE THREAD

**Issue by ShawnMcCool** [godotengine/godot#20173]
# Feature Request - Find in Files

I'd like to be able to search all scripts in the project for a string. Here's a demo of the fantastic implementation from JetBrains.

https://www.youtube.com/watch?v=Y8kVJF1ho88&feature=youtu.be

![screenshot_1531654523](https://user-images.githubusercontent.com/560749/42733563-7f6c3430-8833-11e8-898f-f4f3131c10e6.png)

# Example Scenario

I change the name of some entity in my system and would like to update all references in all scripts accordingly.

In order to accomplish this I would:

1. Press a shortcut key to bring up a dialog.
2. Type the string that I wish to find (the needle). (Optionally, select to search in project or specific path)
3. See a list of all scripts containing that needle (preferably with preview of the actual relevant section)
4. Act upon the results by:
    1. Clicking into a single script which is then loaded into the editor with the cursor position at the first instance of needle.
    2. Choose to do a massive search/replace by filling a 'replace' field and clicking 'replace all'.

**Comment by Zylann** [comment]
I implemented a Find in Files in master some time ago.

**Comment by ShawnMcCool** [comment]
Thanks. In that case, I'll close the issue.
