### ISSUE TITLE
Unable to connect float to vector in shader graph

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#20171]
**Godot version:**

f6ce73f

**OS/device including version:**

linux mint

**Issue description:**

cannot connect input float into vector input

**Steps to reproduce:**
Try to connect any float into vector input and you cannot establish any connection, however, you can connect it backward from right to left.

![2018-07-15 16 51 29](https://user-images.githubusercontent.com/10883749/42732194-5c2d2026-884f-11e8-80aa-7569047273e6.png)

I can drag from b to float but not from float to b

**Comment by swarnimarun** [comment]
you have to use a Vector Constructor.
![image](https://user-images.githubusercontent.com/19930870/42732363-c7fe74ec-883d-11e8-8019-86b53f3227c3.png)

**Comment by groud** [comment]
It should not be possible I think, there is no obvious way to transform a float into a vector.

The bug is that you can connect them, while you should not.

**Comment by JFonS** [comment]
@groud Usually the way to convert  float into a vector is to use the float value as all the components of the new vector. This is how most shading languages do it and probably what reduz did as well, but it just works one way.
