### ISSUE TITLE
Nonexistent functions of AudioServer

### ISSUE THREAD

**Issue by r3d9u11** [godotengine/godot#20188]
**Godot version:**
3.0.2_stable

**OS/device including version:**
Linux Mint 18.3 x64

**Issue description:**
Can't call methods (also autocompletion doesn't show these methods):
```
	musicLevel = AudioServer.get_stream_global_volume_scale()
	effectsLevel = AudioServer.get_fx_global_volume_scale()
```
Result:
`Invalid call. Nonexistent function 'get_stream_global_volume_scale' in base AudioServer.`

What I'm doing wrong? Thanks.

**Comment by marcelofg55** [comment]
Those functions don't exist anymore (used to exist pre 3.0), check the AudioServer doc: http://docs.godotengine.org/en/3.0/classes/class_audioserver.html

**Comment by r3d9u11** [comment]
@marcelofg55 thanks for answer.
but, how I can [mute all sound](https://godotengine.org/qa/10944/mute-all-sound)?

**Comment by marcelofg55** [comment]
You can use set_bus_mute or set_bus_volume_db. If you want different levels for music and SFX create two buses so you can control their volumes separately.

**Comment by r3d9u11** [comment]
@marcelofg55 thanks!
