### ISSUE TITLE
No way to just preview sounds

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20181]
Godot 3.0.5 and master 085483e88577ea91400a1ee46bc4321340824c51

I started importing sounds for the first time in my project, and I rapidly found annoying it's not possible to listen to them. When I double-click on a sound in the file explorer, all I see is this:

![image](https://user-images.githubusercontent.com/1311555/42738037-f7968eb0-8874-11e8-8115-e0154a0ea963.png)

**Comment by Ace-Dragon** [comment]
Currently, I preview a sound by ticking the 'playing' box in the interface for the node.

I do have to turn it on and off again constantly though, a generic preview button (that can loop the sound while you're editing or adding filters to it) would be nice.
