### ISSUE TITLE
AudioStreamPlayer3D is stuck with playing=true in the editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20183]
Godot 3.0.5
Windows 10 64 bits

At some point when adding sounds to my game, I found one of my scenes started to play sound everytime in the editor. The `playing` property is `true`, and I cannot set it back to `false`. Eventually reopening the editor solved it.

The same happens with another AudioStreamPlayer3D, however restarting the editor doesn't reset it.
It is configured with no initial stream (because I dynamically choose a random sound with this one), but it is also stuck with `playing` = `true`, and I think this one also generates a warning when I play the game:
```
ERROR: set_stream: Condition ' !p_stream.is_valid() ' is true.
   At: scene/3d/audio_stream_player_3d.cpp:554
```

Sorry I don't know what is the repro steps for this, but I would suggest to investigate what can cause an editor user from being unable to stop a player.

https://youtu.be/1_nokkxePA0

**Comment by Calinou** [comment]
@Zylann Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Zylann** [comment]
Tried again in the project where it happened, that doesn't seem to reproduce. I was never able to find precise reproduction steps so I can't tell for sure if it was fixed.

**Comment by Calinou** [comment]
@Zylann I'll close this for now then.

If anyone else can reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4), please comment.
