### ISSUE TITLE
scroll wheel event on button not propagated through node2d ancestor

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#2018]
Scene setup:  ScrollContainer, with a Node2D child.  Node2D has GridContainer that contains a Panel with a TextureButton.  Scroll wheel events that happen with the cursor over the button do not propogate up to the ScrollContainer.  If you take the Node2D out of the chain, and parent the GridContainer to the ScrollContainer, the scroll wheel events make it to the ScrollContainer just fine, and it scrolls.  Stop mouse is disabled on all controls below the ScrollContainer.

Example:

https://copy.com/meod6XvaHMAzgXUJ

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by bojidar-bg** [comment]
Example is down, can you reupload, @romulox-x?

**Comment by bojidar-bg** [comment]
Really pretty bump.

**Comment by akien-mga** [comment]
No answer, so closing.
