### ISSUE TITLE
Renaming a C# project breaks all singletons with C# scripts attached

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#20190]
**Godot version:**

3.0.4 Mono

**OS/device including version:**

KDE Neon

**Issue description:**

In a C# project, if you change the name of the project in Project Settings, any autoloads/singletons that have a C# script attached no longer exist and calling any methods on them results in an error.

I have a singleton called Singleton with this code attached:
```
using Godot;
using System;

public class Singleton : Node
{
    public void Test(string s)
    {
        GD.Print(s);
    }
}
```
Then I call it from GDscript like this:
```
extends Node

func _ready():
	Singleton.Test("hello from mono")
```
This works fine and dandy, until you rename the project from `mono_singleton_bug` to `something` and restart Godot. Then I get this error on line 4 of the GDscript code when I run the game:
`Invalid call. Nonexistent function 'Test' in base 'Nil'.`

Additionally I get this error:
```
0:00:00:0702 - Script does not inherit a Node: res://Singleton.cs
```

**Steps to reproduce:**
1. Download the project below.
2. Run it and observe correct results.
3. Rename the project to something else in the Project Settings.
4. Close and re-open Godot.
5. Open the project and run it. Observe it no longer works.

**Minimal reproduction project:**

[mono_singleton_bug.zip](https://github.com/godotengine/godot/files/2197532/mono_singleton_bug.zip)

**Comment by Calinou** [comment]
@Bauxitedev Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

cc @neikeq

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
