### ISSUE TITLE
Optimizations for MacOS

### ISSUE THREAD

**Issue by CoalaJoe** [godotengine/godot#20199]
**Godot version:**
v3.0.5.stable.official.6a88e22

**OS/device including version:**
macOS 10.13.5

**Issue description:**
- Scrolling e.g. in the templates list does not work properly. (If it works, then it just moves one step and then stops)

**Steps to reproduce:**
Not applicable.

**Minimal reproduction project:**
Not applicable.

**Comment by toger5** [comment]
which version are u using?
I have none of your issues. except there is no binding for settings. But it also would not be to obvious which settings to open. Project or Editor settings?

I don't know what you mean with templates. but there is a fix for trackpad scrolling which makes it scroll when you are over another input element. (this is a regression from the gesture class. but it's fixed now)

`Fn` + `Backspace` => `Delete` is os wide. So godot gets a delete event. this should definitely work. (and it does for me)

**Comment by toger5** [comment]
<img width="400" alt="screen shot 2018-07-16 at 23 18 42" src="https://user-images.githubusercontent.com/16718859/42784176-9d758bea-894e-11e8-98cb-832a830e7223.png">
This is scaled x3 and I think the font looks as good as it can get?

**Comment by CoalaJoe** [comment]
@toger5 
<img width="1018" alt="bildschirmfoto 2018-07-17 um 21 47 32" src="https://user-images.githubusercontent.com/5689499/42841655-0d0a03e8-8a0b-11e8-8540-4208d998fe2c.png">
This is the window that I encounter issues when scrolling.

Thanks for the clearance. I was expecting to delete Scenes or Nodes with `Fn`+`Backspace` but it did not seem to work.

I updated the issue.

**Comment by toger5** [comment]
okay I see.
this was fixed by #19015
I didn't know this was the case for the template list too...

**Comment by CoalaJoe** [comment]
@toger5 This is fine. I just want to add any odds I can find here.

Can we close this issue?
