### ISSUE TITLE
Custom node icons are not resized with higher display scaling values (doesn't apply to `class_name`-provided nodes)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#20197]
**Godot version:** Git https://github.com/godotengine/godot/commit/f8417ac6829fa00e9168cdca8c5ea9aa1ede1ad4

**OS/device including version:** Fedora 28

**Issue description:** Custom nodes' icons will always be drawn at the default scale, even when using a larger editor scale. This occurs even when a SVG icon is used:

![hidpi_plugin_icon](https://user-images.githubusercontent.com/180032/42774745-cf7d0f76-8932-11e8-909a-e545aa1d4542.png)

**Steps to reproduce:** Create or import a plugin that uses a PNG or SVG icon.

**Minimal reproduction project:** https://github.com/Calinou/godot-procedural-crosshair

**Comment by MatiasVME** [comment]
I can't see my icon directly, but I can see it in the add nodes part.

I'am using aeddb30fa38215acf8620238209cb53f5bddc28d

![screenshot_20181030_132022](https://user-images.githubusercontent.com/342117/47733296-a93d7a00-dc46-11e8-9022-2a17b7effb9b.png)

![screenshot_20181030_132040](https://user-images.githubusercontent.com/342117/47733305-b0648800-dc46-11e8-933f-9df17854fe33.png)

**Comment by Calinou** [comment]
@MatiasVME That's unrelated to the issue I'm reporting here.

**Comment by Calinou** [comment]
This doesn't seem to be fixed by #33019, as it only fixes the issue for custom types declared using `class_name`. Still, as custom types declared by editor plugins might be deprecated in the future, fixing this is low-priority.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?
(I tried changing my editor scale, but it doesn't seem to do anything...)

**Comment by Calinou** [comment]
I can't reproduce this issue on Godot 3.2.4beta1:

![image](https://user-images.githubusercontent.com/180032/98089254-c2571200-1e82-11eb-9619-f3e767f3e22a.png)

The icons are SVGs but are still blurry, unfortunately.

https://github.com/Zylann/godot_heightmap_plugin/issues/209 says this can still be reproduced though…

**Comment by KoBeWi** [comment]
Ok I was just changing `custom_display_scale` instead of `display_scale`. I managed to reproduce the bug in 3.2.3:
![image](https://user-images.githubusercontent.com/2223172/98101785-fd614180-1e92-11eb-88fe-406663c98a21.png)

**Comment by coppolaemilio** [comment]
I have this same issue in my plugin, but it only happens on mac. It works well on windows.

(Notice the Dialogic icon at the top and the relative size on the rest of the icons) Even the custom nodes (the color bars) have icons that are shown smaller on mac. 

Windows screenshot @125% display scale
![dia-win](https://user-images.githubusercontent.com/2206700/99411379-d32c6c80-28f3-11eb-9fe4-ecf960169ade.PNG)


Mac screenshot @any display scale:
![dialogic-mac-bug](https://user-images.githubusercontent.com/2206700/99411080-7df05b00-28f3-11eb-85b5-a6d84b484f2a.png)

**Comment by andrejp88** [comment]
> The icons are displayed at the correct size but are still blurry, unfortunately.

Calinou, were you able to fix the blurriness? Do you think it's related to this issue, or is it something separate?

Here is a screenshot of the problem. The bottom node is an actual StaticBody2D node, but the top node is a custom class where the icon is set to the StaticBody2D SVG copied to my project folder. Godot 3.5, Linux, editor scale set to 200% (for testing this out).

![](https://user-images.githubusercontent.com/7419746/183512675-fa2defd9-3195-4a73-9887-d663be6698a9.png)

PNGs don't seem to have this problem, here the top node is using a 32x32 PNG of the icon exported via Inkscape:

![image](https://user-images.githubusercontent.com/7419746/183513708-d58ae5d0-a6c6-43df-bf48-43fd56b3e019.png)

**Comment by Calinou** [comment]
> Calinou, were you able to fix the blurriness?

You can set **Svg > Scale** import option to 2 in the Import dock for the editor icon.

**Comment by andrejp88** [comment]
Thanks, that didn't work unfortunately, even tried to set the scale to 4 at one point, but it looks exactly the same. I had also tried fiddling with the Filter and Mipmaps flags but nothing seemed to make a difference.

It's not a big deal one way or another, was just curious if someone had already gone down this rabbit hole :D

**Comment by coppolaemilio** [comment]
There is a proposal to fix this kind of issues: https://github.com/godotengine/godot-proposals/issues/5034

**Comment by dzil123** [comment]
This appears to be fixed in the crosshair project when the icon.svg has enabled "Scale With Editor Scale" from #64938, should this be closed?
