### ISSUE TITLE
add cloud in environment sky

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#20205]
It would be great if there is paramter-tunable procedural cloud in the default sky, which should be more realistic for the environment

**Comment by akien-mga** [comment]
Procedural clouds are highly game-specific, depending on the kind of game you're making you'll likely want completely different types/shapes and styles of clouds, if any. I don't think it should be added to the default sky which is a simple Skybox and should stay so. Maybe it could be added to ProceduralSky, if not available already.

**Comment by nagasawamaki** [comment]
Yes, please add to ProceduralSky. What I mean is ProceduralSky. Sorry for misleading.
And I think with adjustable parameters to adjust the cloud type, size, color, shape, etc., it would be useful for many types of games.

Thank you.

**Comment by Calinou** [comment]
This may have been implemented by #38791, but I'm not sure if the blending scheme works well with cloud panoramas. Either way, it could be achieved by customizing the sky shader.

**Comment by clayjohn** [comment]
This discussion is being tracked in https://github.com/godotengine/godot-proposals/issues/835 now
