### ISSUE TITLE
Do anybody have navmesh baking working on master?

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#20208]
**Godot version:**

e1f2feec2eccbc0589a66b84ea8b3af34c1740b4

**Issue description:**

No navigation mesh generated on bake.

Error message:
ERROR: _navmesh_unlink: Condition ' !nm.linked ' is true.
   At: scene/3d/navigation.cpp:145.

**Steps to reproduce:**
I add Navigation node to a scene, then add MeshInstance as a child of it (I used both imported meshes
and stock godot primitives), then as child of MeshInstance I add NavigationMeshInstance. On that I create NavigationMesh and press bake. No navigation mesh generated.

I see the following message on console:
ERROR: _navmesh_unlink: Condition ' !nm.linked ' is true.
   At: scene/3d/navigation.cpp:145.

**Comment by rcarjan** [comment]
Didn't the _NavigationMeshInstance_ have to be a direct child of _Navigation_, and the _MeshInstance(s)_ have to be children of the _NavigationMeshInstance_ in order to be able to bake the navmesh? I thought that was the only way it was supposed to work. I have tested it and it works on my PC.

**Comment by slapin** [comment]
Well, as I see 3D navigation example I see Navigation/Mesh/Navmesh tree.
Something should be corrected.


On Wed, Jul 18, 2018 at 3:01 PM, Carjan Radu-Liviu <notifications@github.com

**Comment by kakoeimon** [comment]
@slapin  I just checked this, the order is: 
Navigation/NavigationMeshInstance/Map
Map is the Spatial that holds all the map with their collisions.

**Comment by slapin** [comment]
Thanks everyone, this looks like nav3d example issue as it have order
reversed.

**Comment by slapin** [comment]
As this is not Godot issue, but example issue, this should be closed.
