### ISSUE TITLE
Per Pixel Transparency black windows [nvidia on Windows]

### ISSUE THREAD

**Issue by Duskitty** [godotengine/godot#20203]
Not sure what version , it's whatever is the current here > https://hugo.pro/projects/godot-builds/

Windows 10 1703, 1803 (Just updated it and still not working)
Ryzen 5 1600
Nvidia GTX 1060

For some reason I only get black windows, all the objects show up fine, but the transparency never seems to work even across the demos and such even though it works for everybody else

![godot_2018-07-16_07-31-59](https://user-images.githubusercontent.com/13949321/42795183-820f44aa-8948-11e8-9dc0-b17590dbaad9.png)

![godot_2018-07-16_07-29-08](https://user-images.githubusercontent.com/13949321/42795189-88d1766e-8948-11e8-9e29-1c46cb49bdaf.png)

[Edit]

I tried compiling the master and the issue still persists

**Comment by bruvzg** [comment]
Try adding `OS.window_per_pixel_transparency_enabled = true` into `_ready` instead of setting `display/window/per_pixel_transparency` in Project Settings.

**Comment by Duskitty** [comment]
Nope still a black area where the alpha is ment to be

**Comment by Duskitty** [comment]
Got 2 other people to test using this, the build i compiled, they both get the black screens, so i'm assuming something possibly changed since the files were last messed with.
[bin.zip](https://github.com/godotengine/godot/files/2205788/bin.zip)

**Comment by karroffel** [comment]
You can also run Godot from a console with `godot.exe --version` to get version information

**Comment by Duskitty** [comment]
the version linked in that file above is 3.1.dev.custom_build.1d84c4f

**Comment by bruvzg** [comment]
I have tested your project with both my (`3.1.dev.custom_build.d603a74`, debug 64-bit tools, 32-bit and 64-bit release export template) and your executable, transparency work correctly with all of them. Tested on Windows 10 (version 1803 build 17134.167).

**Comment by Duskitty** [comment]
This is very odd, i'm on the same version of windows as you and the issue still persists, do you have a discord? my user is Duskitty#4455 if you're on there

**Comment by bruvzg** [comment]
Done some additional testing (same Windows 10 version):

* AMD FirePro D300, driver version 17.10.3101.1006 - OK.
* Intel HD Graphics 530, driver version 22.20.16.4749 - OK.
* NVIDIA GTX 970M, driver version 398.36 - Black screen.

**Comment by Duskitty** [comment]
I can confirm it doesnt work on both 390.95 and 398.36 with a GTX 1060

**Comment by Duskitty** [comment]
Had somebody test it on an Intel computer vs a Nvidia one, this seems to be restricted to Nvidia cards so far

**Comment by akien-mga** [comment]
Tested on Linux with NVIDIA GTX 670MX 390.59 and it works fine.

**Comment by bruvzg** [comment]
@Duskitty please test #20245, works for me on GTX 970M.

**Comment by Duskitty** [comment]
Can confirm that this fixes it @bruvzg  @akien-mga
