### ISSUE TITLE
Creating a new directory causes a rescan which takes ages

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#20202]
**Godot version:**
3.1.x (master)

**OS/device including version:**
ubuntu, nvidia

**Issue description:**
Moving a file or creating a new directory causes godot editor to start "scanning files, please wait..." (stdout shows "call rescan!") and it sits at 97% for a minute or so. 

Is this new? And is it possible to avoid this call or speed it up?

**Comment by rminderhoud** [comment]
I've also had the editor crash when moving a directory with a large amount of files/sub-directories and it starts the re-scan. Unfortunately I didn't capture the crash logs. I will see if I can reproduce.

**Comment by akien-mga** [comment]
Duplicate of #19991.
