### ISSUE TITLE
toon shading issue

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#20207]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 7, Nvidia GeForce GTX 1060 

**Issue description:**
I am testing Godot toon shader for my character but I found some issues on it.

First I found there is some gradient shadow in the model even I use the toon shader.
I think The gradient shadow should not be appear in toon shading. Or am I setting wrong?

![q01](https://user-images.githubusercontent.com/24987226/42799935-4148d1f0-89cc-11e8-9947-7e1d57e34c72.png)

Below is my setting for the material:
![q02](https://user-images.githubusercontent.com/24987226/42799936-41712204-89cc-11e8-8f6c-8f66869c64c7.png)

Metallic: 0
Roughness: 0

Another issue is when the directional light enable shadow, the mesh become the following:
![q03](https://user-images.githubusercontent.com/24987226/42799937-419a93aa-89cc-11e8-9fb4-d81898d042e4.png)

I think it should not happen in toon shading.

Ultimately, I just want to achieve the visual effect like this:
![q04](https://d.ibtimes.co.uk/en/full/1572376/wind-waker-toon-link.jpg)

If I am doing something wrong, please tell me how can I get the toon shading like above (wind waker style). Thanks so much!

**Steps to reproduce:**
-make a meshInstance
-set the material to toon shading
-add directional light

Thank you!!

**Comment by CptPotato** [comment]
The shadow around the chin comes from the environment lighting. I'm not sure if there's a way to disable it.

The shadow problem has workarounds but there's no perfect way. Using a normal offset and good bias value usually takes care of it pretty well.
Also, the screenshot you posted does not use shadows - so that would be an option, too, if you want to go for that specific look.

**Comment by nagasawamaki** [comment]
thank you. so now the problem is due to the shadow from the environment lighting?
Can the shadow also be calculated as toon shaded shadow?
Or just as you said can the shadow be disabled?

Thank you.

**Comment by nunodonato** [comment]
toon shading works well with directional lights. if you use omnilight or your sky is contributing to ambient light, you get this kind of shading. not sure if supposed to be or bug

**Comment by nagasawamaki** [comment]
actually, I use directional light only and do not have omnilight and any sky in my scene.
But I still get the result

**Comment by nagasawamaki** [comment]
if no ambient light, objects which do not receive the directional light will become black.
Then how can I achieve the same result as the screenshot I posted (like the Wind Waker)?

**Comment by nunodonato** [comment]
@nagasawamaki you can use ambient light to have some basic light in all objects, just disable(or reduce) the sky contribution in the world environment node, that's the issue

**Comment by clayjohn** [comment]
@nagasawamaki using the suggested settings were you able to get things figured out? If so, can we close this issue?

**Comment by QbieShay** [comment]
On v 3.2.stable.official this problem still appears:

![Screenshot_2020-02-15_01-29-07](https://user-images.githubusercontent.com/7917475/74578037-a9c06800-4f92-11ea-99e5-f6dc33abf3c0.png)

**Comment by volzhs** [comment]
what @nunodonato suggested is **use ambient light** and **disable the sky contribution**.
you disabled ambient light.

**Comment by QbieShay** [comment]
@volzhs ah yes, you are correct.
I tried, but i still see soft shading on the face. 

![Screenshot_2020-02-15_01-37-23](https://user-images.githubusercontent.com/7917475/74578246-cf01a600-4f93-11ea-9209-20d1dfd226fe.png)

**Comment by volzhs** [comment]
what about setting Background > Energy to `0`?

**Comment by QbieShay** [comment]
The sky becomes black, the model is unaffected.

![Screenshot_2020-02-15_01-41-09](https://user-images.githubusercontent.com/7917475/74578330-4c2d1b00-4f94-11ea-89e2-a935bdc8d807.png)

**Comment by volzhs** [comment]
I guess this will help you.
https://www.youtube.com/watch?v=laastFVkTaA

**Comment by clayjohn** [comment]
Try background energy of 1 and ambient energy of 0. 

Also, this has been fixed in 4.0. You can now disable radiance and/or irradiance as you choose.

**Comment by QbieShay** [comment]
Here:

![Screenshot_2020-02-15_23-15-38](https://user-images.githubusercontent.com/7917475/74595990-1dbd4780-5049-11ea-8ad0-c0857e352150.png)

@clayjohn any chance this can be fixed for 3.2.x? I could do it with a bit of help, if that's desired.

**Comment by QbieShay** [comment]
Managed to obtain the typical banding, but it does not behave as expected. Opened a proposal with more detail here. https://github.com/godotengine/godot-proposals/issues/484

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/484, as feature proposals are now tracked on the Godot proposals repository.
