### ISSUE TITLE
add_child error with cross-compiled MinGW-w64 templates

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#2020]
I have a Node and a script in it:
```
extends Node

func _ready():
	var cl	= CanvasLayer.new()
	var lb	= Label.new()
	cl.add_child(lb)
	self.add_child(cl)
```
I build to platforms, It work fine on x11 Linux and .exe with Wine, the template .exe I build from MinGW-w64 in my Arch Linux.

But when I run that build on Windows 7 it crash and stopped working.

**Comment by Mavhod** [comment]
Today I build template Windows 32bit .exe MinGW-w64 from Windows7 and it run fine had no error.

When I switch to Arch Linux and run it with Wine it error, perhaps it is a bug from MinGW.

**Comment by okamstudio** [comment]
should run valgrind on linux to see if anything is not working properly


On Sun, Jun 14, 2015 at 6:28 AM, Mavhod <notifications@github.com> wrote:

> Today I build template Windows 32bit .exe MinGW-w64 from Windows7 and it
> run fine had no error.
>
> When I switch to Arch Linux and run it with Wine it error, perhaps it is a
> bug from MinGW.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2020#issuecomment-111805965>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment]
Just to be clear, does the crash refer to the add_child function, or is it just a general "broken" template when cross-compiled with MinGW-w64? i.e. is there an error log relative to add_child, and/or do you reproduce the crash without using add_child?

**Comment by reduz** [comment]
most likely it was a broken template, everything seems to work fine and no valgrind errors, closing
