### ISSUE TITLE
Improve workflow when exporting release or debug builds

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#20219]
Moving discussion from the closed #19667.

The current workflow to select the debug/release mode when exporting binaries is a hardly visible stretched button in the editor file dialog where you define the export location. Many users miss it, and as it defaults to debug, end up shipping games in debug mode.

I think a proper fix should be somewhat like what @razcore-art proposed:

> I am in favor of adding a watermark or a warning or something like that on a project exported with debug enabled by default. And have a separate checkbox for disabling this watermark in case you want to export for testers for example, but with debugging enabled. This will make you more conscious of the option.
>
> And like was mentioned before it's also a visibility problem. I also think it should be a global option (that affects all templates), not per export template.

More proposals welcome.

**Comment by Joleeee** [comment]
How about changing the loading screen? I feel like a watermark would be annoying and unnecessary.

**Comment by razcore-art** [comment]
that's the point, to be annoying, or maybe a slim red border?

**Comment by vnen** [comment]
> How about changing the loading screen? 

Changing the splash screen is not enough because most of the time it only flashes for half a second, might not even show up if your main scene loads fast enough.

**Comment by Joleeee** [comment]
I think a red border is the better solution.

**Comment by AKashyap86** [comment]
warning would be good I think , a popup at the final export, unless specified in the project settings ..

**Comment by akien-mga** [comment]
This was improved a bit by #25175.

I think an opt-out watermark or visual identification of some sort would still be interesting for exported debug builds (so not when running in-editor).

**Comment by exts** [comment]
An even clearer/simpler solution would be to change the save button text. From `Save` to something like `Save 'Debug' Build` or `Save 'Release' Build` based on which setting you check.

**Comment by wyattbiker** [comment]
I missed it on the Save dialog too, because that is not where I usually look for settings, but please don't over complicate things with messages and extra step annoying popups. A checkbox at the top of the Export Settings should suffice and call it Release Mode or whatever. No one will complain they missed it especially with tooltip a description.  At worst you can, in addition to the checkbox on the Export Settings, have the current progress message just say Exporting DEBUG or Exporting Release . E.g.

![image](https://user-images.githubusercontent.com/930478/67642510-e3396e80-f8e2-11e9-99d9-c424c7d16483.png)

**Comment by Calinou** [comment]
@wyattbiker Not all platforms display a progress bar when exporting the project, so it may still be missed depending on the platform the user is exporting to.

The progress bar is implemented for Android, iOS, macOS and UWP.

**Comment by wyattbiker** [comment]
As an amendment to my above comment, I would consider mutually exclusive checkbox in the settings labeled 
```
Export Mode: 
    Release [ ]
    Debug   [ ]
```
No ambiguity and tooltips will provide more detail. Also users can save their export modes as presets E.g.

![image](https://user-images.githubusercontent.com/930478/67643404-98712400-f8ed-11e9-953b-4505c47d8c98.png)

As far as the progress bar differences between platforms I can see where it could be difficult to track export progress (perhaps no feedback?), though it can be a plain popup message that auto-closes when completed. I also noticed the Export Settings groupings **order** between Mac and Windows/Linux are inconsistent. Little nuances.

**Comment by Calinou** [comment]
@wyattbiker The debug/release export option is not specific to export presets, it's intended to be a "stateless" option (i.e. it's not persisted to `export_presets.cfg`). This means you don't have to duplicate export presets if you wish to export projects both in debug and release mode.

Remember that we also allow command-line exporting using `--export` (release mode) and `--export-debug` (debug mode). If we persist the export mode to `export_presets.cfg`, we'd require the users to perform `sed` trickery to change the export mode before exporting a project from the command line.

**Comment by bruvzg** [comment]
> The debug/release export option is not specific to export presets, it's intended to be a "stateless" option

There's plenty of space for the separate Export Release/Debug buttons in the main dialogue.

![Screenshot 2019-10-28 at 22 49 29](https://user-images.githubusercontent.com/7645683/67717324-27f20200-f9d6-11e9-970c-251981f0c85e.png)

> watermark could be annoying

Watermark is overkill, but we can add something like `(DEBUG MODE)` to the end of window title (modify `OS.set_window_title` to make sure it's still present on every change).

**Comment by Calinou** [comment]
> There's plenty of space for the separate Export Release/Debug buttons in the main dialogue.

I tried doing yesterday, but it seems overriding the parameter in `_OS::set_window_title()` in core_bind doesn't work. It would be better to have it there, so we don't have to duplicate the logic for every OS.

**Comment by bruvzg** [comment]
> It would be better to have it there, so we don't have to duplicate the logic for every OS.

It's probably enough to additionally change this line: https://github.com/godotengine/godot/blob/master/main/main.cpp#L1714

**Comment by ulvido** [comment]
same here. how to export to release from gui? I loaded release and debug custom templates.

![2020-04-06 00-16-37 ekran görüntüsü](https://user-images.githubusercontent.com/27722274/78510177-1e966e00-779c-11ea-9c7d-51833c203230.png)

and godot commant not exist

![2020-04-06 00-16-02 ekran görüntüsü](https://user-images.githubusercontent.com/27722274/78510181-2d7d2080-779c-11ea-8e37-7cc6e08a217b.png)

**Comment by Calinou** [comment]
@ulvido Click **Export Project** then uncheck **Export With Debug** at the bottom of the file dialog that appears.

**Comment by akien-mga** [comment]
Partly fixed by #39208, and superseded by godotengine/godot-proposals#1073 for the watermark/outline part.
