### ISSUE TITLE
Changing the name of an AnimationNode in AnimationTree renders the AnimationNode to unusable.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#20210]
**Godot version:**

e1f2feec2eccbc0589a66b84ea8b3af34c1740b4

**OS/device including version:**

Ubuntu 18.04 NVidia GT540M (NVidia drivers)

**Issue description:** and **Steps to reproduce:**

I created an AnimationTree and added an AnimationNode that I connected with output.
After that when I change the name of the animation (inside the GraphEdit and not in the inspector) and move the animation node a little bit (moving it to get the changes this is how GraphEdit works), the AnimationNode looses the connection with the output and the output of the AnimationNode and the input of the Output are rendered to unusable (you cannot connect the with anything). This is the error that popups :
"Unable to connect, port may be in use or connection may be invalid."

This error popups when I try to connect a node to an input that it is already in use.

**Comment by kakoeimon** [comment]
Some more info.
If after the creation of the problem, I select another node in the inspector and the again select the AnimationTree node and get in to the editor of it, the connections and functionality are all back.

**Comment by AntohaRDNS** [comment]
Add info: You cannot assign an animation to an AnimationNode if the name of that node has changed before

**Comment by Favkis** [comment]
I still have this bug with transition node, need to restart godot to make new transition node work.

**Comment by Calinou** [comment]
@Favkis Please open a new issue with a minimal reproduction project attached.
