### ISSUE TITLE
"About C# Support" text requires update

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#20218]
The "About C# Support" text is now out of date.
https://github.com/godotengine/godot/blob/26d3e31e053784993d316580390bba3b3d9b52ff/modules/mono/editor/godotsharp_editor.cpp#L279-L289

This paragraph in particular is misleading now that we have working exports for desktop platforms:

> The main missing feature is the ability to export games using C# assemblies - you will therefore be able to develop and run games in the editor, but not to share them as standalone binaries yet. This feature is of course high on the priority list and should be available as soon as possible.

**Comment by akien-mga** [comment]
Should be trivial to edit. I'd prefer if someone up to date on the current Mono status and shortcomings could do it. Or it can be removed altogether if Mono support is considered good enough.

**Comment by aaronfranke** [comment]
Funny, I was just thinking about this recently. https://github.com/godotengine/godot/pull/20229 Most of the other text is good.

@akien-mga C# support is not considered finished right now, and we should show the warning until it has been stably "good enough" for at least one minor version. I suggest removing in 3.3 or 3.4.

**Comment by KellyThomas** [comment]
Fixed with #20229
