### ISSUE TITLE
No debugging info when calling static func with wrong arguments

### ISSUE THREAD

**Issue by mikica1986vee** [godotengine/godot#2024]
Example project:
https://github.com/mikica1986vee/static_func_with_wrong_args_01

game freezes when function is called with wrong argument. It's probably some weird corner case.

**Comment by akien-mga** [comment]
I think the freeze is normal as there will be an exception raised and shown in the debugger. Or do you mean a complete freeze without debugging possibility?

**Comment by mikica1986vee** [comment]
I'll recheck this in a few hours. If I remember correctly debugger would not activate but game window would stop responding. I don't remember encountering this in a last few months, so it might be fixed.

**Comment by akien-mga** [comment]
The issue seems still valid. The game stops as expected, but there is no debugging info at all.

**Comment by mikica1986vee** [comment]
Argh! Forgot to leave a comment... It rises the exception without debugging info and, at least I think, it raises it at the wrong place. It should raise it at the point of a function call, 'couse I'm calling a function with 2 required and one optional by using only one arg.

Maybe there is a reason for this kind of behavior?

**Comment by reduz** [comment]
wow, this was a serious gdscript bug, haven't seen one of these in years. Nice catch and surprised no one else found it
