### ISSUE TITLE
All contributors: Update your clang-format plugin/hook to version 6.0.1

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#20247]
I just updated our `clang-format` Travis checks to use version 6.0.1 (vs 5.0 before) in 003ac67d, and applied it to the code base in 7c9f745, thus fixing long standing issues with comments before `#define` statements.

Make sure to update your own `clang-format` distribution to the same version or later, as using a version < 6.0 will mean undoing the changes from 7c9f745 and thus add unnecessary diffs and CI failures to your PRs.

You can download version 6.0.1 here: http://releases.llvm.org/download.html#6.0.1
There are also upstream deb repos for Debian/Ubuntu: http://apt.llvm.org/

**Comment by vnen** [comment]
Good, I don't have to manually fix things to comply with the old version anymore.

**Comment by Zylann** [comment]
Is version 6.0.0 ok?

**Comment by akien-mga** [comment]
> Is version 6.0.0 ok?

I didn't test, but I guess it should behave the same as 6.0.1 yeah.

**Comment by volzhs** [comment]
```
~$ clang-format --version
clang-format version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
```
done :)

**Comment by Calinou** [comment]
This migration was completed a while ago, this can be closed :slightly_smiling_face:
