### ISSUE TITLE
Godot can override open scenes or scripts changed on disk by an external process (e.g. git pull)

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#20250]
**Godot version:**
3.0.5

**OS/device including version:**
Windows + Linux (shared)

**Issue description:**
When files are replaced in the tree, while a scene is open but has no changes pending (such as a git pull), changes are lost as the engine will try to overwrite the changes in git unless you are to close the scenes and re-open them, EXCEPT if it's the scene that is currently visible.
This also applies to changes to project.godot, as well as export templates

**Steps to reproduce:**
1. Create 2 scenes, keep both open throughout this
	- You can additionally edit the project settings and add an export template to see the other bugs
2. Save both
3. Push it to git/copy it/etc
4. Edit it elsewhere/in another godot instance
	- You can additionally edit the project settings and add/edit an export template
5. Copy back
6. Find that scenes do not correctly refresh unless you close/reopen the scenes - saving or running will destroy changes in all open scenes

Note: Other resources, and closed embedded scenes will update properly, though the latter will not visually refresh unless sub-resources that are not .tscn change.

**Minimal reproduction project:**
Not applicable

**Comment by lupoDharkael** [comment]
Can someone point out to the files related to this behaviour? I'd like to check if I can do something about this problems as it is very annoying working with branch in git.

**Comment by akien-mga** [comment]
As discussed during the Godot Sprint, what should be done is to show a dialog when an open scene changed on the filesystem asking if the user wants to reload, save, save as, etc., as IDEs would typically do.

**Comment by raphaelsiz** [comment]
I have a question regarding this, because I saw that [the docs](https://docs.godotengine.org/en/stable/tutorials/best_practices/version_control_systems.html) said to close the editor before running `git pull` because of this issue. If someone were to open the editor, *not make any changes,* and run `git pull`, would it correctly sync to the editor? Or should they run `git pull` before opening?

**Comment by Calinou** [comment]
> I have a question regarding this, because I saw that [the docs](https://docs.godotengine.org/en/stable/tutorials/best_practices/version_control_systems.html) said to close the editor before running `git pull` because of this issue. If someone were to open the editor, _not make any changes,_ and run `git pull`, would it correctly sync to the editor? Or should they run `git pull` before opening?

This recommendation is now outdated in Godot 3.4 and later, as external changes are detected correctly.
