### ISSUE TITLE
Mono/C# support on iOS

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#20268]
Similar to #20267, currently we don't support exporting Mono/C# projects to iOS. This issue should serve to keep track of the things that need to be done for this support to happen.

CC @neikeq

**Comment by akien-mga** [comment]
Moving to 3.2 milestone, for 3.1 the focus is on getting the desktop platforms in good shape, plus maybe Android support if we can figure out the buildsystem.

**Comment by aaronfranke** [comment]
Very likely won't be done in time for 3.2.

**Comment by neikeq** [comment]
This will be done by the end of this month, but I don't think that's in time for 3.2... or maybe it is, I don't know.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/36979 (`3.2`) and https://github.com/godotengine/godot/pull/37153 (`master`), closing.
