### ISSUE TITLE
SamplePlayer2D plays back sounds at a higher pitch than they are

### ISSUE THREAD

**Issue by kernelcrasher** [godotengine/godot#2026]
I have a WAV file exported from LMMS that I trigger to play upon stage load. It does play back, but the pitch is altered to be higher than the original sound. This can be confirmed by loading and playing the sample back via a regular SamplePlayer, which plays the sound without distortion.

**Comment by ThomasMorley-T3D** [comment]
Sound from the SamplePlayer2D will change based on the position of the node on the screen and is normal behavior.

**Comment by kernelcrasher** [comment]
Why would changing the pitch of a static sound emitter be normal?

**Comment by ThomasMorley-T3D** [comment]
![2dsound](https://cloud.githubusercontent.com/assets/11800663/7975062/8347efc0-0a2f-11e5-9e9b-77486258dc66.png)

**Comment by ThomasMorley-T3D** [comment]
I don't know for sure that it's normal I guess it's just my observation. But I have noticed that if you move the SamplePlayer2D from the top of the screen to the bottom while playing a sound you get the same effect as an ambulance driving by your house. The amplitude and pitch change based on location. The effect can be changed/minimized in the Params section by modifying Pitch Scale and Attenuation.

**Comment by punto-** [comment]
Is the camera/sound source moving? maybe it's the Doppler effect
https://www.youtube.com/watch?v=VJdL72udNyY

**Comment by kernelcrasher** [comment]
Nothing is moving, I know what Doppler effect is.

**Comment by vichug** [comment]
have you checked the sampling rate is correct ?

**Comment by kernelcrasher** [comment]
Where would I check that? There is no property or function related to the sampling rate in SamplePlayer2D.

**Comment by akien-mga** [comment]
Could you provide a minimal example that reproduces this issue?

**Comment by reduz** [comment]
this will be rewritten in 2.1, will see it then

**Comment by Zylann** [comment]
I noticed that sound plays OK from the Sample Library editor, but in game I can confirm it plays at a higher rate, kind of +20%.

**Comment by neikeq** [comment]
The audio system re-write have been moved to the 2.2 milestone.

**Comment by akien-mga** [comment]
Assumed fixed in 3.0 with the new audio engine, feel free to reopen/comment/open a new issue if it's not the case.
