### ISSUE TITLE
export template for this platform are missing [ android platform ]

### ISSUE THREAD

**Issue by muafakul** [godotengine/godot#20266]
**Godot version:**

**OS/device including version:**

**Issue description:**
[]
please see the screenshoot below
https://raw.githubusercontent.com/muafakul/muafakul.github.io/master/Screenshot_146.png

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
> Godot version:

?

> OS/device including version:

?

> Steps to reproduce:

?

**Comment by akien-mga** [comment]
At any rate, that's the same issue as #19389 and will be fixed in 3.0.6.

There are no Android export templates for the C# version btw, it only supports desktop platforms for now.

**Comment by HexKnight** [comment]
i am using gdscript and i have the same probleme

**Comment by Brayacon** [comment]
is this solved ?

**Comment by volzhs** [comment]
@HexKnight @Brayacon what problem do you have?
if you have a specific error and reproduce steps, open an issue for it.

**Comment by Brayacon** [comment]
Am I required to install the export templates
