### ISSUE TITLE
GDNative C example not working on Windows

### ISSUE THREAD

**Issue by beamer159** [godotengine/godot#20279]
**Godot version:** 3.0.5 (64 bit)
**OS:** Windows 10 (64 bit)

**Issue description:**
Working through the GDNative C example [here](http://docs.godotengine.org/en/3.0/tutorials/plugins/gdnative/gdnative-c-example.html), I made it to the last step, where I build the project. Unfortunately, I get the following error:

    Attempt to call function 'new' in base 'NativeScript' on a null instance.

Other Godot users experienced this issue and brought it up [here](https://godotengine.org/qa/24453/function-nativescript-instance-nativescript-simpleexample). None of the suggestions in that thread helped in my case.

**Steps to reproduce:**
Download the attached project archive (also contains the `godot_headers` I used) and attempt to build. You may need Windows 10 to do this since it is using .dlls. 

**Minimal reproduction project:**
[GDNative.zip](https://github.com/godotengine/godot/files/2210506/GDNative.zip)

**Comment by vnen** [comment]
That might be a problem in the documentation (so more fit to https://github.com/godotengine/godot-docs)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-docs/issues/2921.
