### ISSUE TITLE
Mono/C# support for HTML5

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#20270]
Bringing Mono/C# to the HTML5 platform will probably come only after #20267 and #20268, but opening this issue to keep track of what needs to be done and progress.

CC @neikeq

**Comment by akien-mga** [comment]
Moving to 3.2 milestone, for 3.1 the focus is on getting the desktop platforms in good shape, plus maybe Android support if we can figure out the buildsystem.

**Comment by DleanJeans** [comment]
Anything I can do to help progress this and other HTML5 related issues?

**Comment by unicomp21** [comment]
Is this working in 3.2?

**Comment by nhold** [comment]
I don't think that will work @DavidJVitale because I believe it would have trouble converting the godot API as those are just wrappers around the C++ code. It might be an idea to do IL2CPP using Brute, although it's closed source while in development.

**Comment by SourceSkyBoxer** [comment]
And Mono/C#: WebAssembly and LLVM support?

**Comment by hydroper** [comment]
Where can I track the progress on C# support for Godot 4?
