### ISSUE TITLE
body_test_motion not available in gdscript on PhysicsServer

### ISSUE THREAD

**Issue by rminderhoud** [godotengine/godot#20276]
**Godot version:**
master

**Issue description:**
`body_test_motion()` is available on `Physics2DServer` but not in the 3D server (`PhysicsServer`). It would be quite useful to have in 3D physics to implement custom physical motions.

**Comment by MrModez** [comment]
Can we please fix that? I don't think it's too much work :c

**Comment by Draghi** [comment]
Just ran into this myself. I don't imagine this should be too difficult, would it be fine for me to take a crack at it?

**Comment by RevenantX** [comment]
you can use this https://docs.godotengine.org/en/3.2/classes/class_physicsdirectspacestate.html instead (and for some things this is better choice)

**Comment by Draghi** [comment]
That's a significant amount of code required to work around an asymmetrically exposed method, imo, it'd be easier to just manually expose it unless you've got a need for some more unique work cases (which https://github.com/godotengine/godot-proposals/issues/710 helps with in a lot of cases)

**Comment by Calinou** [comment]
The way the source code is organized seems to make this nontrivial. `PhysicsServer3D` doesn't have `body_test_motion`, but `PhysicsServer3DSW` does. Any ideas?

**Comment by Draghi** [comment]
`body_test_motion` exists on PhysicsServer3D as a pure virtual method (line 494 in the header) implemented by both backends. 

So, exposing it only requires the same setup as the 2D version, namely a wrapper around MotionResult, and a proxy method. Did have a crack at it before and got it working, but ran into some issues (segfault) with passing it certain Rigidbodies - which were, from memory, any non-kinematic bodies.

**Comment by pouleyKetchoupp** [comment]
Closed by #50102 (4.0) & #50103 (3.4)
