### ISSUE TITLE
AnimationPlayer animation_changed not emitting

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#20274]
**Godot version:** 3.0.5 stable

**OS/device including version:** Linux Solus 3.9999

**Issue description:**

When connecting the `AnimationPlayer` **animation_changed** signal to a script, the signal doesn't emit at all.

**Steps to reproduce:**

- Create a new scene
- Add a root `Sprite`
- Add an `AnimationPlayer`
- Attach an script to the root
- Connect the **animation_changed** signal (both by the Editor interface and by code, on _ready() for example)
- Create a method to be triggered by the signal and add a breakpoint or any debug tool to know if it is being called
- Make some animations for testing purposes
- At some point in the script, call `AnimationPlayer.play(animation_name)` using the different animations' name 
- Confirm that the method the **animation_changed** signal is connected to is not being called

**Minimal reproduction project:**
[animation_player_bug.zip](https://github.com/godotengine/godot/files/2209757/animation_player_bug.zip)

**Comment by vnen** [comment]
That might be by design, usually signals are not triggered when the action is initiated by the developer. This signal is probably triggered only for queued animations.

**Comment by avencherus** [comment]
The name implies any animation changes might trigger it, but yeah seems like intended only for queue changes.

The signal might be better understood if it were named something like `queue_changed`, or at least better documented.

> If the currently being played animation changes, this signal will notify of such change.


Compatibility breaking is probably far from desired.  If the name stays, it might be less confusing if it were at least expanded to support the direct animation changes as well.  

It would also give more flexibility to the programmer to also have it that way, given its arguments for old and new animation names.  Using the started signal means keeping around a variable for the previous animations if you want that information.
