### ISSUE TITLE
GDScript Editor Autocomplete Not working

### ISSUE THREAD

**Issue by HAMSAMS** [godotengine/godot#20275]
**Godot version: 3.0.5**

**OS/device including version: Windows 7 Ultimate **

**Issue description:**

Auto Completion feature of the GDscript editor does not work at all.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment]
Please include some steps to reproduce the issue or a gif/video of the problem. We need to know what makes things not work in your case, since it usually works.

**Comment by HAMSAMS** [comment]
Update:

I noticed that removing all text from the created GDscript and start typing when the script file is empty solve the issue ....I consider this as closed for windows 7 case....

I also tested with windows 10, its all working fine without even removing test,
