### ISSUE TITLE
General feedback on 2.1.5 RC2

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#20273]
**Godot version:**
2.1.5 RC 2

Downloads: https://downloads.tuxfamily.org/godotengine/2.1.5/rc2/

There have been tons of changes since 2.1.4 in the `2.1` branch, some of which may have introduced regressions or API breakages - during 3.0 development, the pressure to get new features in 2.1 was high and we were less conservative than we plan to be for 3.0.x releases.

This thread should serve to notify of potential regressions or breakages that you will find in 2.1.5-rc2 build, and which were not present in 2.1.4-stable. This is not the place for feature requests - and at this stage we really don't want to spend too much time on 2.1 features, finishing 3.1 has much high priority.

Please test it on your games (after doing backups/using version control of course!) and report any potential breakage. It would be especially useful to test it on complex games currently in production with 2.1.4. If you're using custom compiled templates to add some modules (Steam, ads, etc.), check the README.txt file in the download folder to know what commit it was made from.

Continuation from #16813.

**Comment by akien-mga** [comment]
So no new issue? :)

**Comment by Shin-NiL** [comment]
I've just republished a game made with 2.1.4 using now 2.1.5 RC2 and it seems pretty stable so far.

**Comment by avencherus** [comment]
Haven't found any new issues compared to the build from the master branch I compiled a few weeks back.  I'm only aware of a handful of previously unresolved issues with the cursor, OS display functions, and joypad ids.

**Comment by williamd1k0** [comment]
I'm using a custom version because of this 3.0 feature (https://github.com/williamd1k0/godot/commit/783d37740ef7c5b03eaef5c0b55061eed77720d4) but I'm updating my builds from [godotengine/godot@2.1](https://github.com/godotengine/godot/tree/2.1) and everything seems to work fine.

Btw, is it safe to merge https://github.com/williamd1k0/godot/commit/783d37740ef7c5b03eaef5c0b55061eed77720d4 into 2.1 branch?

**Comment by akien-mga** [comment]
Thanks for the testing reports everyone :)

> Btw, is it safe to merge williamd1k0@783d377 into 2.1 branch?

No, this change caused memory leaks so you'd need to at least cherry-pick 30317296af1124e2092d3acd374ca0246afd5536 with it too.

**Comment by Chaosus** [comment]
Is this issue should be closed ?

**Comment by akien-mga** [comment]
Yes, 2.1.5 was released.
