### ISSUE TITLE
3.0 - Http request returns empty body

### ISSUE THREAD

**Issue by sugarmaster** [godotengine/godot#20272]
**PLATFORM**:
I'm using Ubuntu 18.04 LTS.

```
cat /proc/version
Linux version 4.15.0-23-generic (buildd@lgw01-amd64-055) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018
```
**STEPS TO REPRODUCE:**
1. Do an httprequest (it doesnt matter if its post or get) 
2. Expect to get json data 
`{"status":"success","api_key":"someapikey"}`
3. Get a 200 response code, a correct response header with no body

**EXAMPLE PROJECT:**
https://gist.github.com/sugarmaster/369467a9773639856b8d4f0cfacce2be

I'm having problems using Httprequest to connect to a Lumen api.

I can make the connection no problem and the data is processed ok on the server side, I confirmed it. Also I get a 200 code so the request is good.

I recieve the header:
[Host: localhost:8000, Connection: close, X-Powered-By: PHP/7.0.30-1+ubuntu18.04.1+deb.sury.org+1, Cache-Control: no-cache, private, Date: Wed, 18 Jul 2018 20:45:19 GMT, Content-type: text/html; charset=UTF-8]

But the body of the response is empty.
When I try it with Postman it is obviously returning json data:
`{"status":"success","api_key":"bjr41VVdwGjxOO9ofraNWKTuhYeEhOe3hLtyGd1c"}
`
The code gist:
https://gist.github.com/su…/369467a9773639856b8d4f0cfacce2be

If it helps I will post the Lumen API to github.

**Comment by akien-mga** [comment]
CC @godotengine/network

**Comment by sugarmaster** [comment]
Ok, I found the solution.
If the server doesnt return a "Content-length" header with the correct size of the response the HTTPRequest node wont read the body of the response. 

Lumen doesnt return a "Content-lenght" header by default so as it was missing the engine just doesnt read the body of the response.

I suppose it's for performance purposes but I wish this was mentioned somewhere in the docs.

**Comment by jjhax** [comment]
Same problem. The server I'm hitting doesn't return `Content-Length` so `HTTPRequest` is setting it to `0` by default resulting in `body` of the callback being empty.
