### ISSUE TITLE
Newline doesn't render in some parts of the inspector

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#20288]
**Godot version:** 4ebcbea

**OS/device including version:** Arch Linux

**Issue description:** It looks like the newline character added in #20217 works as expected in tooltips but cannot be rendered in the inspector, or at least in certain submenus:
![layernameproblem](https://user-images.githubusercontent.com/35355161/42971960-eaa76f4e-8b7b-11e8-8330-eaf0e7a752f6.png)

**Steps to reproduce:** Open up a collision/light mask chooser submenu.

**Comment by vnen** [comment]
CC @akien-mga
