### ISSUE TITLE
Suggestion for kinematic2d move_and_slide_with_snap()

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#20284]
**Godot version:**

3.1dev compiled 17/07/2018

**Issue description:**

I see this function now in kinematic2d and my opinion is that this can be simply accomplished by adding that parameter with default value to move_and_slide:

- NOW:

**move_and_slide** (linear_velocity, floor_normal, infinite_inertia, slope_stop_min_velocity, max_bounces, floor_max_angle)

**move_and_slide_with_snap** (linear_velocity, **snap**, floor_normal, infinite_inertia_ slope_stop_min_velocity_ max_bounces, floor_max_angle)

- SUGGESTION:

**move_and_slide** (linear_velocity, floor_normal, infinite_inertia, slope_stop_min_velocity, max_bounces, floor_max_angle, **snap= default value to no snap**)

If **snap** is added behind last parameter and with default value, there is no breaking compatibility.

I feel that this two functions can be too redudant and move_and_slide_with_snap can go out of script screen easely. To long, tooo, looooong.

I don´t know if this make sense but thanks for read.

Juan Post:
https://godotengine.org/article/godot-31-will-get-many-improvements-kinematicbody

**Comment by eon-s** [comment]
If `infinite_inertia` was added, snapping can also be added, and snapping is used mostly on sidescroll so it can be:
**move_and_slide** (linear_velocity, floor_normal, **snap**, infinite_inertia, slope_stop_min_velocity,  max_bounces, floor_max_angle)

**Comment by vnen** [comment]
New arguments should go to the end. `infinite_inertia` was moved to end as well.

**Comment by Ranoller** [comment]
Sometimes when scripting in godot i think that can be awesome to have a keyword to specify to use default argument. Something like that:   

`move_and_slide ( Vector2(1,1), def, def, def, def, def, Vector2(1,0))`

... it can be ugly by stetics, but very useful (I know that def is function in python.....)

**Comment by akien-mga** [comment]
For 4.0 we plan to refactor the `KinetaticBody(2D)` APIs to rely less on passing so many cryptic arguments, but use class-wide configuration and a better interface to pass custom values.
It's not fully defined how it should be done exactly, but this will definitely be addressed at the same time.
