### ISSUE TITLE
CSG shapes are ignored for navmesh

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#20281]
Currently CSG shapes are ignored when baking navmesh which requires building substitute geometry then hiding it after bake. Not nice.

**Comment by Megalomaniak** [comment]
Has this been fixed? I was just about to recommend CSG's as a solution to someone when I found this issue report.

**Comment by slapin** [comment]
It is trivial to fix in your code locally. But no, still there.

**Comment by JFonS** [comment]
#29749 should do the trick.
