### ISSUE TITLE
WebSocketClient can't send/read received packets

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#20289]
**Godot version:**
[Godot Engine v3.1.dev.calinou.43dc050](https://github.com/godotengine/godot/commit/43dc050947753d201607d26717ca6fc3fe412c34) (obtained from <https://hugo.pro/projects/godot-builds/>)

**OS/device including version:**
Windows 10 Home v1803 (April 2018 update) x64

**Issue description:**
I don't seem to be able to use WebSocketClient for anything that isn't multiplayer. Any attempt to send packets will result in error code 3 (ERR_UNCONFIGURED), and attempts to read received packets will result in the same error. (Godot, from testing on the Discord websocket, seems to recognize when I get packets -- I just can't read them, as the packets are always `null` when I read them with `get_var()`.)

After digging around, I seem to have located the places where the errors might be coming from; see [line 113](https://github.com/godotengine/godot/blob/master/modules/websocket/websocket_multiplayer.cpp#L113) and [line 131](https://github.com/godotengine/godot/blob/master/modules/websocket/websocket_multiplayer.cpp#L131), both of [websocket_multiplayer.cpp](https://github.com/godotengine/godot/blob/master/modules/websocket/websocket_multiplayer.cpp).

Hopefully this isn't just me missing a step. I want to use the websocket implementation for non-multiplayer functions.

**Steps to reproduce:**
Try to send or receive anything to/from a websocket using the `WebSocketClient` class.

**Minimal reproduction project:**
[Websocket issues.zip](https://github.com/godotengine/godot/files/2211744/Websocket.issues.zip) (This uses `ws://echo.websocket.org` for testing)

**Comment by akien-mga** [comment]
CC @godotengine/network

**Comment by Zephilinox** [comment]
@akien-mga was that what you mean to CC? It doesn't link anywhere

**Comment by Calinou** [comment]
@Zephilinox It mentions everyone in the `godotengine/network` team so that they get notified of the issue :slightly_smiling_face:

**Comment by Faless** [comment]
@LikeLakers2 you need to call `client.get_peer(1).get_available_packet_count()` and `client.get_peer(1).get_packet()`.
The version you are using (`client.get_available_packet_count()` and `client.get_packet()`) only works when `gd_mp_api` is enabled)

**Comment by LikeLakers2** [comment]
@Faless Can that maybe be documented then, if that's how it's supposed to work? I looked through the documentation and found no mention that I needed to use `get_peer(1)`.

**Comment by Faless** [comment]
@LikeLakers2 you are right, it should be documented. I'm reopening the issue and adding the documentation tag, I'll try to make a PR over the WE

**Comment by LikeLakers2** [comment]
@Faless While it doesn't happen on the build I was using to make this issue, the latest build from that website (v3.1.dev.calinou.6c569c9) seems to have issues sending packets. I'm unsure what changed between the issue being created and now, but when I send any packet (whether through `get_peer(1).put_var()` or `get_peer(1).put_packet()`) the program freezes before abruptly sending me back to the editor. In the console (not the output tab, the console that appears alongside the editor), this is what's shown:

```
Nothing read: Invalid argument
ERROR: read: Server Disconnected!

   At: drivers/windows/stream_peer_tcp_winsock.cpp:203
```

**Comment by Faless** [comment]
Yeah, I opened an issue about that, see #20696

**Comment by LikeLakers2** [comment]
I'm unsure if I should open a new issue about this, but in writing my Discord implementation for Godot, I notice Discord isn't registering the client as disconnected immediately. I took a small look into it, and unless I'm misunderstanding the protocol or how Godot's websockets are structured, it seems like Godot's implementation of websockets isn't sending a close frame when `client.get_peer(1).close()` or `client.disconnect_from_host()` is called? I'm unsure what to do about this.

**Comment by VitaZheltyakov** [comment]
https://github.com/godotengine/godot/issues/15393

**Comment by LikeLakers2** [comment]
@VitaZheltyakov That's not the issue I'm having. The problem I described in my last message was packets not being sent/received.

**Comment by LikeLakers2** [comment]
@Faless Should I open a couple new issues regarding the things I mentioned above (Godot not sending close frames like it should when the websocket closes, and being unable to read close event data)? This issue is marked as a documentation issue and those don't seem to be about the same thing, but they're still related to the current issue title.

**Comment by akien-mga** [comment]
> you are right, it should be documented. I'm reopening the issue and adding the documentation tag, I'll try to make a PR over the WE

@Faless Was this done in the end?
