### ISSUE TITLE
Run Window Placement Not Same as Editor

### ISSUE THREAD

**Issue by CRHough** [godotengine/godot#20283]
When more than one screen or monitor is detected please add an option to Editor Settings->Run->Window Placement's Screen option for Not Same as Editor.

**Comment by Calinou** [comment]
This is an interesting suggestion, but what if the user has more than 2 monitors? Which monitor would the project start on?

**Comment by CRHough** [comment]
You raise a good question and give a great answer to it! Your suggestion works much better than what I was thinking.
