### ISSUE TITLE
TextEdit not showing typed text and error on scrolling/typing

### ISSUE THREAD

**Issue by lukaskj** [godotengine/godot#20296]
**Godot version:**
Tried with:
v3.1.dev.custom_build.b2d7641
v3.1.dev.custom_build.43dc050
v3.1.dev.custom_build.911febb

Every time that I will use Godot I make a build

**OS/device including version:**
Windows 10 Pro
GeForce GTX 1080/PCIe/SSE2

**Issue description:**
Can't use the TextEdit properly.
It was supposed to show the text that I type or the text on _Text_ property

**Steps to reproduce:**
Create a blank project, place a root node (I tried with _Node_ or _Control_), create a TextEdit child node and run the project.
With the TextEdit on focus, scroll down and then "scroll more" to get the first debug errors
Typing after that scroll does trigger the error too.

Error:
> 0:00:04:0295 - Index line=3 out of size (text.size()=3)
> Type:Error Description: Time: 0:00:04:0295 C Error: Index line=3 out of size (text.size()=3) C Source: 
> scene\gui\text_edit.cpp:3731 C Function: TextEdit::times_line_wraps

**Minimal reproduction project:**
[TextEditTest.zip](https://github.com/godotengine/godot/files/2212381/TextEditTest.zip)

[Video of the problem](https://www.youtube.com/watch?v=44m4fBDgN_0)

**Comment by AlexHolly** [comment]
As a workaround resize the game window while running, works in some cases.
