### ISSUE TITLE
Expose editable_children option to scripts 

### ISSUE THREAD

**Issue by Piet-G** [godotengine/godot#20292]
This would be helpful for tool scripts since they can modify the value of children of a node. In that case it would be helpful to know if the changes it makes will be saved (`editable_children` = true) or not. 

It would also be nice to have to be able to set the value of `editable_children` from code to force it to be true or false for certain nodes.

**Comment by Xrayez** [comment]
Interestingly I've made some success toggling `editable_children` from script with hacks, [see here](https://github.com/Xrayez/godot-editor-plugin-tools/blob/bb8429d6d3283268d8d33ef1fa9a194acd11a427/editor_plugin_utils.gd#L127-L148). It would be certainly much easier for this to be implemented internally though.

**Comment by revilo** [comment]
I've created a PR that fixes this, however according to this comment it was decided that the flag should not go into the Node's scripting API as it is only related to the editor:

https://github.com/godotengine/godot/pull/20569#issuecomment-412988767

Shouldn't the ticket be closed then?

**Comment by lyuma** [comment]
Obsoleted by #52000
