### ISSUE TITLE
Project/Settings Editor rich-text tooltips look weird

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#20317]
**Godot version:**
cfcb6e11f25adb13177ba08777263288a5ec6f61

**Issue description:**
They don't have a uniform colour and are not correctly formatted:
![untitled](https://user-images.githubusercontent.com/30739239/43029150-84aa5186-8c5a-11e8-8683-3a9631b6510a.png)

**Comment by reduz** [comment]
i dont think i changed the formatting, so that probably is related to something else..
also, that border is likely not very fit (i just used the tooltip style and put an editorhelp thing inside)

**Comment by toger5** [comment]
We should add a style override for the help i side. And give it a style box empty.
Should be the cleanest fix.

**Comment by akien-mga** [comment]
Fixed by #22423.
