### ISSUE TITLE
Input function does not run in tool scripts

### ISSUE THREAD

**Issue by Hubber116sx** [godotengine/godot#20319]
**Godot version:**
v.3.0.5.stable

**OS/device including version:**
Pop!_OS 18.04 LTS (Linux)

**Issue description:**
The _input() function does not run in a tool script while in the editor.

**Steps to reproduce:**
1) Create a node and add a script to it
2) Add tool to the top of the script
3) Add _set_process_input(true)_ to _ready()
4) Create the __input(event)_ function and add a way to know if it is running

**Minimal reproduction project:**
[input_tool_error.zip](https://github.com/godotengine/godot/files/2215819/input_tool_error.zip)

**Comment by Zylann** [comment]
I think this has been mentionne already:

`_input` does not run for the same reason you cannot click on buttons in your edited scene. It would be a mess.
The viewport in which your edited scene lives does not transfer input to its children, probably due to http://docs.godotengine.org/en/3.0/tutorials/viewports/viewports.html#input

**Comment by Hubber116sx** [comment]
I also get 
`Invalid call. Nonexistent function 'forward_canvas_gui_input' in base 'EditorPlugin'`
when calling forward_canvas_gui_input. I'm assuming this is the function that handles inputs while in the editor.

**Comment by vnen** [comment]
> I also get
Invalid call. Nonexistent function 'forward_canvas_gui_input' in base 'EditorPlugin'
when calling forward_canvas_gui_input. 

It's a virtual function, you're supposed to overwrite it to receive the editor input.

**Comment by Hubber116sx** [comment]
Overriding the function does nothing without calling it manual in code. I'm assuming overriding is done by adding the function to the script inheriting EditorPlugin like this 
```
func forward_canvas_gui_input(inp):
```
or this
```
func _forward_canvas_gui_input(inp):
```
