### ISSUE TITLE
Low res UI when using GLES2 video driver

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#20326]
**Godot version:**
Godot 3.1 dev

**OS/device including version:**
Win 10 64bit AMD gpu

**Issue description:**
When switching project from GLES3 to GLES2, editor will restart but icons will be low res (see picture). This happened on a completely fresh new project.
![snap](https://user-images.githubusercontent.com/9384421/43035248-b1eaf762-8cec-11e8-97b4-f12a426237ed.PNG)

Switching back to GLES3 solves the problem, icons go back to being rendered sharp. If I save a scene and close editor and reopen project it will look ok. If I then switch from GLES2 to GLES3 it will look ok, but switching back to GLES2 and the icons go back to low poly if I dont have any scene open.

Dont know if this is relevant, but when restart to GLES2 happens, boot image of godot will be smaller, like slightly scaled down.

This is what the console is spitting out 

ERROR: RGBA float texture not supported
   At: drivers/gles2/rasterizer_storage_gles2.cpp:143
ERROR: RGBA float texture not supported
   At: drivers/gles2/rasterizer_storage_gles2.cpp:143

**Comment by dragmz** [comment]
I'm getting this low-res effect randomly when starting Godot with "--video-driver GLES2" flag (i.e. don't have to switch the drivers to reproduce)
