### ISSUE TITLE
Allow each control to use a specific custom style defined in the assigned theme

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#20320]
**Godot version:**
`master` / cfcb6e11f25ad

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
When defining an UI theme, sometimes it's needed to make the same type of control to look differently depending on a context.

For example, a `Panel` can have an opaque background normally, but when they are used as a backdrop of a modal dialog, it's maybe necessary to show them with a translucent background.

With CSS, such a use case would be covered by declaring a style definition for normal panels and an override for backdrop panels, which can be identified by having a specific CSS class, like `backdrop`:
```css
.panel {
    background-color: black;
}

.panel.backdrop {
    opacity: 0.5;
}
```
However, in Godot, it seems that there's no clear way to achieve a similar functionality. I can define a theme resource which defines how all panels must look, but if we want to make a certain type of panels to look differently, we need to either create a separate theme, or define a stylebox and set it to individual `Panel` instances.

It seems that it's possible to define various custom styles for such controls like `Button` or `Panel`, but apparently it's not possible currently, to make each control to use one of those custom styles defined in a theme its using rather than the default one.

It'd be better if there is a way to specify that a control belongs to a certain group, i.e. `backdrop`, so it should be rendered differently according to a custom style defined for that context in its associated theme.

**Comment by toger5** [comment]
Intersting though!
I'm thinking a lot about godot themes. And of course there is lot of potwntial for  improovement.

To answer your question: you are supposed to use stylebox override for this...

Theming in godot is very simple. It's basically a dicrionary with objects (styleboxes) which know how to draw rectangles ;) ) thats it.
But godot is a game engine. Not gtk or qt ;)
So this simple approach night be the right choice. It's still possible to achieve a lot with it.
It would need quiet a bit of work to make it a fully css themable platform. 
But what u can do, is introduce new theme classes. Create a theme in gdscript. Add a stylebox for ("panel/popover","Panel") (first string can be anything) than, mark all the panels you want in that class with add_style_override

**Comment by toger5** [comment]
But if you convince me, with a very nice implementatiln, and some good arguments, i might do sone work on theming. Planning to do that anyways. (Shader style boxes, theme based dpi setting with inmediate update, better theme loading withou all svg recreating, auto icon upscaling woth bitmap icons...)

**Comment by Poobslag** [comment]
I'd love to see this implemented. As a workaround I'm using 4 themes in my game `h1.theme`, `h2.theme`... and applying them selectively to different components. But, it's a little clumsy and eliminates a lot of the convenience of applying a single theme to a UI component and having it get inherited throughout

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/850, as feature proposals are now tracked on the Godot proposals repository.
