### ISSUE TITLE
Visual scripting glitch with GLES2

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#20327]
When using GLES2 rendering, connections between nodes in visual scripting will sometimes disappear, and to get them to render again, you have to reselect nodes or drag nodes around the canvas.

**Comment by eon-s** [comment]
Keep in mind that GLES2 renderer on master is still one of the first implementations and do not have all the features added.

I guess it was a mistake to add the GLES button before the feature...

**Comment by abaky** [comment]
I disagree, I think its great that new features get pushed to master early, gives community a chance to break stuff and I hope that developers get useful feedback.

**Comment by dragmz** [comment]
@abaky Is there a chance that you could attach a project that can be used to reproduce the issue?

**Comment by eon-s** [comment]
I have meant that the GLES button was added before GLES2 proper, we won't know if this is a bug until we get the full thing on master.
