### ISSUE TITLE
Missing and incomplete documentation

### ISSUE THREAD

**Issue by kernelcrasher** [godotengine/godot#2032]
Godot's documentation is very spotty and makes learning the engine a very slow, sometimes borderline impossible process.
* The most obvious part is the fact that some features (Light Baking, Editor Plug-Ins) have remained undocumented for **more than a year**. This issue was raised in https://github.com/okamstudio/godot/issues/72, but after promises were made, nothing has changed.
* Another issue is the low quality of existing pieces of documentation. For example, the Physics and Collision (2D) tutorial doesn't explain how to use the collision triggers *at all*, it just mentions their existence and the developer is left to reverse engineer the rest with the use of example projects and forum posts.
* Some code is completely undocumented. An example would be the Path2D and PathFollow2D classes. What exactly are they meant to do? How does the developer use them?

The documentation has to be complete and up to date if the engine is meant to be usable.

**Comment by ThomasMorley-T3D** [comment]
I agree with this point as well. I'd like to see the tutorials opened up for user submissions. I for one would be glad to do a few. Maybe you could put a call out on the main page asking for text tutorial submissions. if you asked everyone in the community to pick one part of Godot and create a tutorial for it this would be a dead issue in less than a month I'd bet. You as the main programmers of the engine would only have to review, approve, and post them. What do you think?

As a side note I've never used the Path2D and PathFollow2D before today, but in just 5 mins I figured out how to use them. I now have snow falling down my screen from a Particle2D node parented to the PathFollow2D node. Super cool! I'll take the Path2D and PathFollow2D nodes for my tutorial! :)

**Comment by ThomasMorley-T3D** [comment]
![path2d](https://cloud.githubusercontent.com/assets/11800663/7996727/4fb140f2-0ae9-11e5-9c67-a870c45de7d6.png)

**Comment by punto-** [comment]
We (mostly TheoXD) are putting together an openprojects site to allow for
this. Try this:

http://godotop.cloudapp.net/projects/godot-engine?jump=welcome

It's not ready but there are the features it'll have roughly.

**Comment by ThomasMorley-T3D** [comment]
That is great news to hear punto! Having an openprojects site where everyone can contribute is a great thing. It will put Godot userbase into warp drive once documentation and tutorials are available. Will the site have asset sharing as well?

**Comment by captainwasabi** [comment]
Wow, that is nice!!  Can't wait for the official launch :)

**Comment by agameraaron** [comment]
Looking great. You guys are really on top of the big issues. I hope to contribute some myself.

**Comment by akien-mga** [comment]
Archiving as the OpenProject website is now live, and everyone can take part in writing documentation there (you might have to ask for edit rights in the forum, but they're easily granted).

**Comment by akien-mga** [comment]
Regarding the API documentation you can also make PRs in this repo for the doc/base/classes.xml file (see http://godotengine.org/projects/godot-engine/wiki/Reference_filling_work)
