### ISSUE TITLE
Setting visual shader type to 'CanvasItem' crashes the editor

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#20322]
**Godot version:**
`master` / cfcb6e11f25ad

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
When creating a visual shader material for a control, switching the mode to `CanvasItem` crashes the editor.

However, if you open the visual shader editor first (with mode set to `Spatial`) and change the mode to `CanvasItem` later, it seems to work as expected.

**Comment by CezaryKopias** [comment]
win64
confirmed
