### ISSUE TITLE
Saving scene replaces values for dictionary export variable to null

### ISSUE THREAD

**Issue by OliPerraul** [godotengine/godot#20332]
**Godot version:**
v3.1.dev.custom_build.cfcb6e1

**OS/device including version:**
win64

**Issue description:**
Saving scene replaces values for dictionary export variable to null. Potentially related to error messages in the console indicating wrong number of arguments.

**Steps to reproduce:**
1. Create a project
2. Create a scene
3. Create a node
4. Attatch a gdscript
5. write `export(Dictionary) var dict
6. Insert key/val pair and modify value in inspector
7. ctrl-s
8. Notice fields replaced with null

**Comment by OliPerraul** [comment]
I am currently working on fixing this problem on my own fork.

**Comment by OliPerraul** [comment]
![capture](https://user-images.githubusercontent.com/24371247/43038783-02e9be72-8cee-11e8-9a8b-3b4fa3fa0f80.PNG)
Currently working on a fix

**Comment by OliPerraul** [comment]
![capture2](https://user-images.githubusercontent.com/24371247/43038791-21ea742e-8cee-11e8-9f0d-1290b07f8a63.PNG)

**Comment by hpvb** [comment]
Are you still investigating this issue @OliPerraul? Can I offer some assistance to you?

**Comment by OliPerraul** [comment]
@hpvb I issued a pull request and everything seemed fine on my end but the test would never pass. #20400. I am quite busy at the moment so i gave up

**Comment by akien-mga** [comment]
Fixed by #20400.
