### ISSUE TITLE
Dims while debug, doesn't revert

### ISSUE THREAD

**Issue by menip** [godotengine/godot#20336]
**Godot version:**
cfcb6e1

**Issue description:**
Godot dims, then doesn't revert.

**Steps to reproduce:**
Run scene, pause. Select remote in inspector, then select one of your objects. Select your objects path under node options. Some dialogue pops up but closes immediately. Godot is now dimmed.

**Comment by aaronfranke** [comment]
Godot version should be a version number or a hash. Don't reference pull requests. 

The current head is cfcb6e11f25adb13177ba08777263288a5ec6f61

**Comment by reduz** [comment]
Does this still happen?

**Comment by menip** [comment]
Yup.
Following steps to reproduce causes same dimming behavior on 1093c0f.

**Comment by menip** [comment]
Instead of selecting inspector->remote, need to select scene->remote.
Nevertheless, I was not able to reproduced issue again following previous steps, so closing.
