### ISSUE TITLE
Necessary to show whether GL|ES3 or GL|ES2 is being used at all times?

### ISSUE THREAD

**Issue by menip** [godotengine/godot#20334]
Current build of master has this:
![image](https://user-images.githubusercontent.com/22862244/43039009-eb7ce454-8cd8-11e8-89e6-95979121d506.png)

Where in top right of project there is visible what rendering backend is being used. After using editor for a bit, I see having this setting is not useful to me at all, and is just taking up space. I don't know if this is more useful for those that need to deploy to large number of platform, but I would prefer to keep this option in project settings.

Could we discuss some reasons why this is useful for majority of userbase?

**Comment by DualMatrix** [comment]
I agree, it might be useful when doing complex graphics stuff but for regular use it hasn't come up for me. Perhaps have a setting to enable it?

**Comment by Zephilinox** [comment]
I like it for two reasons.

1. It makes it very clear that you can switch renderer now, and that gles2 is supported, even if you haven't been following along with the updates

2. It makes it very easy to switch between renderers for testing performance/visual differences

**Comment by vnen** [comment]
[According to @reduz](https://twitter.com/reduzio/status/1019933477930721281), this is so the editor can give proper hints on why something isn't working. If you use something not available in GLES2, you can easily see why it's not working.

**Comment by swarnimarun** [comment]
This will come up when you use things that are GLES2 or GLES3 specific, especially Particles and Shaders.

Mostly everything else is independent of the change i.e. it works awesome in both.

**Comment by PJB3005** [comment]
I can definitely tell you I was going insane on why my lights weren't working yesterday till I realized I was on GLES2.

**Comment by swarnimarun** [comment]
Yeah currently GLES2 port is not 100% complete, so there is that.

**Comment by menip** [comment]
With vulkan around the corner, this will be even more useful. Closing as no additional discussion for over 6 months
