### ISSUE TITLE
Animation player has no animations after instancing scene

### ISSUE THREAD

**Issue by kroopson** [godotengine/godot#2033]
When I create the scene with Animation Player and some animations it works only if it's a main scene. If I try to load and instance it with:

var scene = load("/scene_with_animation_player.scn")
var instance = scene.instance()
add_child(instance)

the animation player is not working anymore. Debugging has proven that it's missing the animation tracks.

Here are the test scenes.
https://www.dropbox.com/sh/rqnzwgkv6urag60/AAA2ZKvEmx6WYGgp4WoaqNKma?dl=0

**Comment by kubecz3k** [comment]
I have downloaded these files and I can confirm that I can reproduce the bug on my machine (Godot 1.1). From what Kroopson said on irc it seems this bug was not present in Godot 1.0

**Comment by reduz** [comment]
okay, will check as soon as I can

**Comment by kroopson** [comment]
don't - I'm an idiot and it was my fault. I've had a "play" method executed in _process method.

**Comment by kubecz3k** [comment]
@kroopson Hmm in the sample files uploaded by you, I have run the 'play' method in _ready  just after instancing a scene... and for me it's not working..
