### ISSUE TITLE
Impossible to override methods with different function signature in typed GDScript

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#20349]
**Godot version:**
525384d master

**OS/device including version:**
Windows 10 1803 build 17134.165

**Issue description:**
For instance, the parser doesn't allow me to override set/get methods of a class that inherits Object:

```gdscript
extends Node

var property
	
# It was possible to override `set` method before typed GDScript
func set(p_property, p_value, some_other_value = null):
	property = p_property
	
# Same with `get`
func get(p_property, some_other_value = null):
	return property
```

```
SCRIPT ERROR: GDScript::reload: Parse Error: Function signature doesn't match the parent.
          At: res://Node.gd:7
```

**Minimal reproduction project:**
[typed-gdscript-set-get.zip](https://github.com/godotengine/godot/files/2216911/typed-gdscript-set-get.zip)

**Comment by akien-mga** [comment]
CC @vnen - I don't know if it's a bug or a feature, overriding Object `set` and `get` sounds like asking for trouble.

**Comment by vnen** [comment]
It's not about `set` and `get` specifically, the issue is changing the method signature (adding more arguments) when doing so. This is one of the things that GDScript used to allow that is not safe when considering OOP concepts (inheritance and polymorphism).

Say you have a variable of type Object, you can put an instance of this script there. But if the signature of the `get()` method can be different, there's no way to type-check this in the parser (or rather, the parse would say it's okay, looking at Object, but when you run it breaks), and it's very easy to make a mistake, breaking the game in runtime with a hard to track bug.

I know you added only optional arguments, so in theory it would still work, but it would require ignoring all the extra arguments when checking, allowing for some potential mistakes.

While this is technically breaking compatibility, I prefer *not* allowing changing the method signature when overriding.

**Comment by Xrayez** [comment]
> While this is technically breaking compatibility, I prefer not allowing changing the method signature when overriding.

This is the reason why I created the issue because you stated in your merged PR that it shouldn't break anything. But I've got to agree that it's logical not to break OOP concepts...

I'll try to refactor my code base with that in mind and see if I get any more errors (it spits plenty of errors now, and I'm not sure whether they're related to method signature alone). I don't really need to be able to override set/get methods specifically, I can rename them as `setup`  and `retrieve`.

**Comment by vnen** [comment]
> This is the reason why I created the issue because you stated in your merged PR that it shouldn't break anything.

It's okay to open the issue. There's a lot of things I didn't anticipate because GDScript is very lenient in many aspects. But in this particular case I think it was a flaw in the old GDScript.

I'll leave this up for discussion.

**Comment by nazgum** [comment]
I also ran into this today, but not by adding more arguments to my function.

If I make a scene called Enemy.gd, and that scene has a script:

```
extends Node2D

func hit(dmg, stun = true):
   pass
```

And I instance this as a New Inherited Scene, say Orc.gd, and give it the following script:

```
extends "res://Enemy.gd"

func hit(dmg, stun = true):
   .hit(dmg, stun)
```

It fails with: " Parse Error: Function signature doesn't match the parent."

**Comment by swarnimarun** [comment]
Here's another error while we are at it,

![image](https://user-images.githubusercontent.com/19930870/43059366-b710324c-8e69-11e8-9539-1d5bc93eb6ef.png)

![image](https://user-images.githubusercontent.com/19930870/43059390-cf72c7be-8e69-11e8-84c9-8fac2e285374.png)

I don't think that is expected.

And sorry about the absurd naming, was just testing things.

**Comment by bojidar-bg** [comment]
@swarnimarun This is unrelated to the issue since default arguments were allowed only at the end even before the typed gdscript PR.

**Comment by K3nIchi** [comment]
I´m having similar issue trying to make [FSM](https://godotengine.org/asset-library/asset/94) works in Godot [0e8f2c8](https://github.com/godotengine/godot/tree/0e8f2c81cc58399746fd8f7401cea65a11709acf) master

FSMState.gd
![fsmstate_gd](https://user-images.githubusercontent.com/7603409/43164651-10f567ba-8f68-11e8-9b07-5a6b65f1db52.jpg)

foo.gd
![foo_gd](https://user-images.githubusercontent.com/7603409/43164680-26d6f760-8f68-11e8-8584-1fa6b6bce4d5.jpg)

any idea how I can make this plugin works again in the new typed gdscript?

**Comment by ArcOfDream** [comment]
Also having weird errors like this, with the base class having the method like this.
![](https://cdn.discordapp.com/attachments/212250894228652034/471385886538334208/unknown.png)

And another class inheriting the class with an override like this.
![](https://cdn.discordapp.com/attachments/212250894228652034/471385657219088386/unknown.png)

**Comment by Xrayez** [comment]
Seems like typed GDScript deems using default parameters as some kind of an evil thing to do when overriding, so most likely it's a bug related to using default parameters, isn't it? The number of arguments doesn't change according to reports by @K3nIchi and @ArcOfDream.

**Comment by bojidar-bg** [comment]
The problem lies somewhere in ~this map~~ this piece of code:
https://github.com/godotengine/godot/blob/f778bd8e694cb9c93cc0e021418f2be362dcdd3c/modules/gdscript/gdscript_parser.cpp#L7171-L7185

**Comment by vnen** [comment]
I guess we *could* allow adding arguments as long as they are optional.

The other reports (when the signature really didn't change) are effectively a bug.

**Comment by vnen** [comment]
@bojidar-bg it turns out that GDScript's `get_default_argument_count()` method is return the wrong number (off-by-one).
