### ISSUE TITLE
Allow fragment coordinates to be accessed in light shader

### ISSUE THREAD

**Issue by lordkettune** [godotengine/godot#20341]
_(This is a feature proposal)_

Information about the current fragment should be available to light shaders as well, since it can be necessary for shaders that generate patterns or textures. Basically, FRAGCOORD should be available in both the fragment and light processor functions.

I was trying to write a halftone pattern light shader, but it doesn't really seem to be possible in Godot currently, since I can't access the fragment's position.

**Comment by Bauxitedev** [comment]
Can't you use `SCREEN_UV` instead of `FRAGCOORD`?
