### ISSUE TITLE
Application often hangs upon exit when using Multi-Threaded 2DPhysics mode

### ISSUE THREAD

**Issue by pedromundo** [godotengine/godot#2034]
Developed (simple 2DPhysics/AnimatedSprites and some custom code testing) application hangs upon exit when the threading model for 2DPhysics is set to Multi-Threaded, tested on windows and android, the problem apparently only happens on the former. Tested with godot 1.1 built from source with Visual Studio 2013 in all of 32bit and 64bit release and release_debug scenarios.

Sometimes, and after a long time (happened quickly once) the output will be something around the lines of "sync ==true" and the application properly quits.

I have already tried doing a lot of customized unload logic such as deactivating the physics server altogether, making sure all existing bodies are asleep and queueing their deletion, blocking signals on both the bodies and the 2DPhysicsSever itself by handling event 7 on _notify, all to no avail; the program still hangs **after** the custom logic runs, I can even go in the debugger and see 0 active bodies for 2DPhysics (but still around 500-ish collisionPairs)

EDIT: Realized that while running from the downloadable release doesn't have this problem, it also does not give the console output for the Multi-Thread 2DPhysics, it's most likely ignoring the parameter and running as Single-Thread.

[image](https://cloud.githubusercontent.com/assets/10016968/8014823/31490980-0baa-11e5-9ae8-169742a8b3d7.png)

![image](https://cloud.githubusercontent.com/assets/10016968/8014978/77327b4c-0bab-11e5-889d-e10abd635e7d.png)

**Comment by pedromundo** [comment]
PS: Changing back to Single Thread-Safe, naturally, fixes the problem.

**Comment by trollworkout** [comment]
im pretty sure the engine is single threaded at the moment. i think i read something about that being worked on.

**Comment by akien-mga** [comment]
IIRC there was work done on threading post-1.1, could you try the master branch to see if your bug is still there?

**Comment by pedromundo** [comment]
Will do so sometime tomorrow :)

On Fri, Nov 13, 2015 at 5:15 AM, Rémi Verschelde <notifications@github.com>
wrote:

> IIRC there was work done on threading post-1.1, could you try the master
> branch to see if your bug is still there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/godotengine/godot/issues/2034#issuecomment-156359196>.
>



-- 
Pedro Oliveira Raimundo.
*Graduado em Análise e Desenvolvimento de Sistemas, IFBA. (2011-2015)*

**Comment by ZuBsPaCe** [comment]
Had the same experience with mulitthreaded physics lately, mentioned here: #2760. You better use SingleThreaded-Unsafe, because I believe this was the default in Godot 1.1 and that SingleThreaded-Safe does not yield any benefits, but I could be wrong.
