### ISSUE TITLE
Problems with new parser functionality from typed GDScript and exported NodePaths and get_node

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#20345]
**Godot version:**
525384d gcc

**OS/device including version:**

Windows

**Issue description:**
When exporting a nodepath the new parser functionality thinks the variable type is the same as the name of that variable, resulting in the following error:

`Parser Error: At 'get_node()' call, argument 1. Assigned type (node_name) doesn't match the function argument's type (NodePath).`

**Steps to reproduce:**

Setup example:
```

export(NodePath) var road_renderer

func test():
	return get_node(road_renderer)
```

**Minimal reproduction project:**

**Comment by vnen** [comment]
Do you have a sample project? Your sample code is invalid because you declared a variable called `node` and used a undeclared variable called `road_renderer`. If I change them both to the same name it works.

**Comment by EIREXE** [comment]
@vnen it doesn't appear to happen in other projects, i've sent you a message in discord so I can send you the project privately
