### ISSUE TITLE
Editor text rendering issue on specific resolutions

### ISSUE THREAD

**Issue by Clyybber** [godotengine/godot#20355]
**Godot version:**
790a81d

**OS/device including version:**
Arch Linux 4.17.8 , Intel i7-4710HQ

**Issue description:**
The text of the `player` `scripts` folder on the left side of the screen has this little stretching artifact. This happens only if godot is fullscreen on a resolution of 1680x1050. This doesn't happen on my 1080p monitor. This doesn't happen in 3.0
[screenshot](https://imgur.com/a/KGfdmx6)

**Steps to reproduce:**
Start godot fullscreen or full-maximized on a screen with the a 1690x1050 resolution

**Comment by akien-mga** [comment]
The same effect is visible on line 74 in the script editor (more or less same vertical position), so it looks like there's a full line which is stretched to 2 or 3px.

**Comment by Clyybber** [comment]
Appears to be fixed, at least on master.
