### ISSUE TITLE
typed gdscript: nested class default member initializer ignores outer class scope

### ISSUE THREAD

**Issue by muiroc** [godotengine/godot#20354]
**Godot version:**
525384d

EXAMPLE EDITED (see vnen comment below)

so the scope issue is not limited to the nested classes member initializers (makes more sense)

```gdscript
extends Node

const CONSTANT = 10

enum Enumeration {
	ZERO
}

class Nested:
	# comment the two members below
	# Identifier 'CONSTANT' is not declared in the current scope.
	func hello():
		return CONSTANT

	# Identifier 'CONSTANT' is not declared in the current scope.
	var first = CONSTANT

	# Identifier 'Enumeration' is not declared in the current scope.
	var second = Enumeration.ZERO

```

**Comment by akien-mga** [comment]
CC @vnen

**Comment by vnen** [comment]
Did this even worked before? This code fails in Godot 3.0.5.

**Comment by Chaosus** [comment]
@vnen my project which uses enums from outer space is no longer compiles too. I think its critical backward compatibility break and must be fixed before alpha..

**Comment by vnen** [comment]
The code in the OP didn't work before. It worked with constants but not with static functions.

**Comment by muiroc** [comment]
sorry my mistake! vnen is right about the static funcs

**Comment by supagu** [comment]
I have some code like:

    enum State {
    	STATE_UP,
    	STATE_DOWN
    };

    class Action:
	    var state = STATE_UP;

which used to compile, but now errors saying: **Identifier 'STATE_UP' is not declared in the current scope.**

which used to compile, but now errors. I've tried changing to:
var state = State.STATE_UP;
but this gives me the error: **Identifier 'State' is not declared in the current scope**
