### ISSUE TITLE
Bug in calculation of 6-channel AudioRBResampler

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#20362]
**Godot version:**
Master (89e1b30)

**OS/device including version:**
All.

**Issue description:**
@Rubonnek found unnecessary assignments in `AudioRBResampler::_resample` in the `C == 6` case: https://github.com/godotengine/godot/blob/9f479f096cb50fa8d1215e68c262f110116114ef/servers/audio/audio_rb_resampler.cpp#L101-L117

If compared with other channels calculations, there should likely be intermediate calculations: https://github.com/godotengine/godot/blob/9f479f096cb50fa8d1215e68c262f110116114ef/servers/audio/audio_rb_resampler.cpp#L70-L80

There's also something fishy in the `C == 4` configuration as `v3` and `v4` are ignored: https://github.com/godotengine/godot/blob/9f479f096cb50fa8d1215e68c262f110116114ef/servers/audio/audio_rb_resampler.cpp#L82-L99

**Comment by reduz** [comment]
Code is unused and will likely never be used, but added version of it anyway
