### ISSUE TITLE
Error parsing class_name token

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#20369]
**Godot version:**

174cf31d002268f0d5e309b6587c91d62534842d

**OS/device including version:**

macOS

**Issue description:**

when changing the name after class_name
I get the following error
`modules/gdscript/gdscript_tokenizer.cpp:1092 - Condition ' tk_rb[ofs].type != TK_IDENTIFIER ' is true. returned: StringName()
`
**Steps to reproduce:**
change class name:
 for example `class_name Hell` -> `class_name Hello`

**Comment by akien-mga** [comment]
CC @vnen
