### ISSUE TITLE
Freeze when checking input event type

### ISSUE THREAD

**Issue by MrMinimal** [godotengine/godot#20367]
**Godot version:**
Godot_v3.0.5-stable_win64.exe

**OS/device including version:**
Windows 10

**Issue description:**
When using `event.type` in GdScript, the game freezes if the event is a mouse movement.

```
func _input(event):
	print("Hover over the game window to start to freeze")
	print(event.type)	# freezes the game when mouse input occurs
```

**Steps to reproduce:**
Access `event.type` in `func _input(event):` while moving the mouse over the game window.

**Minimal reproduction project:**
[InputTypeBug.zip](https://github.com/godotengine/godot/files/2217274/InputTypeBug.zip)

**Comment by bojidar-bg** [comment]
Any errors in the debugger tab or console?

**Comment by AlexHolly** [comment]
Is "event.type" even a thing in 3.0?
`if (event is InputEventMouseMotion)`

**Comment by akien-mga** [comment]
Indeed, `event.type` is not valid in Godot 3.0, it's from the old 2.1 InputEvent system.

You can use `event.get_class()` if you want to know its class, or better as suggested by @AlexHolly, you likely want to compare it with other classes with the `is` inheritance check.

The game does not freeze, it just raises an error in the editor's debugger.

**Comment by MrMinimal** [comment]
You were absolutely right, my debugger did not show any errors. I suspect it was because of multiple Godot instances running on Windows, debugger and console output seem to have a problem with that.

My bad!
