### ISSUE TITLE
Possible bug in reflection probes handling of ambient sky contribution

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#20361]
**Godot version:**
Master (89e1b302)

**OS/device including version:**
All.

**Issue description:**
@Rubonnek found this unused variable/assignment in the GLES3 rasterizer: https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_scene_gles3.cpp#L3008

Either it should be removed, or there's a bug and this line should be changed to use `contrib`:
https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_scene_gles3.cpp#L3014

**Comment by cosmicchipsocket** [comment]
I was wondering why the Ambient Sky Contribution slider wasn't doing anything!

**Comment by akien-mga** [comment]
> I was wondering why the Ambient Sky Contribution slider wasn't doing anything!

Well it should work for most objects, it's only for Reflection Probe where it was not directly taken into account - but it's still taken into account via the Ambient Sky Contribution on the objects that the Reflection Probe reflects, so it's hard to say if there's really a bug in the end.

**Comment by cosmicchipsocket** [comment]
It was specifically the slider in WorldEnvironment, but I just tried again and the slider seems to be working, so I'm not sure what's up with that.

The slider also works in ReflectionProbe, but setting it to anything lower than 1 causes massive Z-fighting artifacts.
