### ISSUE TITLE
Typed GDScript doesn't infer the type of function parameters with a default value

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#20366]
**Godot version:**

Godot master https://github.com/godotengine/godot/commit/4b549faaab40f09756b644d4ad4d9d63e3b5e70c

**OS/device including version:**

Windows 10

**Issue description:**

![https://i.imgur.com/bSurNcd.png](https://i.imgur.com/bSurNcd.png)

**Comment by vnen** [comment]
Didn't add this one, but it could be added.
