### ISSUE TITLE
Error exporting typed variables

### ISSUE THREAD

**Issue by DGWana** [godotengine/godot#20376]
**Godot version:**
Godot 3.1 latest #20374

**OS/device including version:**
Windows 10 64-bits

**Issue description:**
When trying to assign a type for a variable I want to export I get the following error:
`error(3,7): Export hint type (Object) doesn't match the variable's type (Environment)`
so exported variables are always untyped

![sin nombre](https://user-images.githubusercontent.com/29492561/43067133-be461070-8e66-11e8-8949-4426237604d2.png)

**Steps to reproduce:**
Declare a variable like
`export(Environment) var environment: Environment`

**Comment by akien-mga** [comment]
CC @vnen

**Comment by vnen** [comment]
I'll investigate this, but FIY you can omit the export hint if you're adding a type hint: `export var environment : Environment`

**Comment by DGWana** [comment]
Ok, thanks. That works but then it shows all types of files when loading from the file system plus don't let me make a new resource on the fly.
