### ISSUE TITLE
Drag a Node to reference field

### ISSUE THREAD

**Issue by brmassa** [godotengine/godot#20389]
1* Create a custom script with a **Export** _reference_ variable.
2* It will show a field to select or drag a reference.
3* try to drag a packet scene Node from hierarchy. It works!
4* try to drag a sub Node from this scene. It does not work, because the moment you click on the child node, it changes the inspector.

Solution:
Godot should DO not _select_ the node when the user are just draging it around

**Comment by bojidar-bg** [comment]
Nodes are not references, and you cannot assign nodes to export variables. Instead, try NodePath.

**Comment by brmassa** [comment]
@bojidar-bg, ok.

Questions: 
1- if i drag the node to another folder, the nodepath is updated automatically?
2- can I refer both internal (children nodes) and external nodes (other files)?

**Comment by Chaosus** [comment]
@brmassa The issue tracker is not a place for the questions, use the appropriate community channels for that (such as Discord, IRC, or forums). Closed.
