### ISSUE TITLE
Changing the position of a Path2D does not properly update the position of PathFollow2D nodes

### ISSUE THREAD

**Issue by vybr** [godotengine/godot#20386]
**Godot version:**

3.0.5

**Issue description:**

Here's an image to show what I mean: https://i.imgur.com/OkT3h2D.png
The red dots are the ACTUAL positions of the path followers (they have random v and h offsets).
The blue line is the path with its **position currently set to (-16, 0).** 
The magenta line is the original path position.

The frogs are shown at the correct place but their actual positions are the original points of the path, instead of the points + position.

**Comment by avencherus** [comment]
I've recently observed that moving the path in the editor doesn't update the positions of the PathFollow2D nodes until their offsets are changed individually.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13004169/66217771-93df9400-e6d0-11e9-9f3c-0f7fc058e1ef.gif)

@Calinou I recall your fine work polishing to the curves tool recently, have you noticed this by chance?  Wondering if I'm missing something...

**Comment by Calinou** [comment]
@avencherus I didn't test PathFollow2D while working on the curve editor, so I don't know.

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

**Comment by Stazis555** [comment]
Noticed that `get_baked_points()` returns original world coordinates, not considering Path2D transform position.

![print](https://user-images.githubusercontent.com/2266017/188729124-5eb08590-a6c6-4aed-87b9-4f6a48c81d82.png)

![animation](https://user-images.githubusercontent.com/2266017/188729250-b03b537b-8285-4c51-b3c2-c08781fbb6fb.gif)

Trianle is moving by this code 
```
func _ready():
	points = get_node("/root/Node2D/Path2D").curve.get_baked_points()

func _physics_process(delta):
	var target = points[target_index];
	if position.distance_squared_to(target) < 10:
		target_index = posmod(target_index + 1, points.size())
		target = points[target_index]
	linear_velocity = (target - position).normalized() * speed
```

**Comment by Linie3** [comment]
Any idea how to fix this, or is there any workaround? I really need this for a project, in which I move around the parent of the Path2D which seems to totally displace and misform the path I created.

**Comment by KoBeWi** [comment]
If you are able to compile the engine, make a custom build with #43399 included.

**Comment by Linie3** [comment]
Sadly I am not that of an advanced of an programer, so that is kinda out of my reach at this point. I will try to get a workaround to work tho, as I really need that. Thx for ur help anyways!
