### ISSUE TITLE
--generate-mono-glue fails to run

### ISSUE THREAD

**Issue by migueldeicaza** [godotengine/godot#20384]
There was a similar problem logged before, but was closed with the error indicating it had been fixed:

https://github.com/godotengine/godot/issues/12361

**Godot version:**

godot from github ec85fd554b0ae9861fddabbda1667a93bdd52450 (July 23rd, 2018)

**OS/device including version:**
MacOS

**Issue description:**

Followed the instructions to generate the Mono Glue from here:

http://docs.godotengine.org/en/3.0/development/compiling/compiling_with_mono.html

But when I run Godot to generate the glue, it aborts:

```bash
$ scons platform=osx module_mono_enabled=yes tools=yes mono_glue=no
[ ... ] wait
[100%] Linking Static Library ==> modules/freetype/libfreetype_builtin.osx.tools.64.a
Ranlib Library         ==> modules/freetype/libfreetype_builtin.osx.tools.64.a
[100%] Linking Program        ==> bin/godot.osx.tools.64.mono
[100%] progress_finish(["progress_finish"], [])
[100%] scons: done building targets.
$ bin/godot.osx.tools.64 --generate-mono-glue modules/mono/glue
arguments
0: bin/godot.osx.tools.64
1: --generate-mono-glue
2: modules/mono/glue
Current path: /cvs/godot
OpenGL ES 3.0 Renderer: AMD Radeon Pro Vega 64 OpenGL Engine
ERROR: _load: No loader found for resource: res://modules/mono/glue
   At: core/io/resource_loader.cpp:186.
ERROR: start: Failed loading scene: res://modules/mono/glue
   At: main/main.cpp:1664.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1989.
$ _
```

**Comment by akien-mga** [comment]
Thanks for the report Miguel :)

CC @neikeq

**Comment by akien-mga** [comment]
@migueldeicaza Actually, the compiled binary with the Mono module has a `.mono` suffix, as seen in the log:
```
[100%] Linking Program        ==> bin/godot.osx.tools.64.mono
```
So you're actually running the non-Mono binary here:
```
bin/godot.osx.tools.64 --generate-mono-glue modules/mono/glue
```
I definitely need to work on proper arguments validation to make such issues clearer.

**Comment by akien-mga** [comment]
I enhanced the documentation a bit to make this suffix clearer. (Should be live on the `latest` docs domain in ~30 min.)
