### ISSUE TITLE
iOS export error: Condition '!da ' is true. returned: ERR_CANT_OPEN

### ISSUE THREAD

**Issue by KierBear11** [godotengine/godot#20383]
**Godot version:**

master branch, Jul. 22, 2018
commit hash: 15ee6b781bd3f946790fbe3d20be52d4f621b99a

**OS/device including version:**

rMBP 2015, macOS 10.13.3

**Issue description:**

When exporting to iOS, the export fails and returns the following error messages:

```
exporting res://Node2D.tscn
exporting res://default_env.tres
static library: libgodot.iphone.debug.fat.a
Unzipping...
READ: libgodot.iphone.debug.fat.a
ADDING: game.a size: 57098640
READ: libgodot.iphone.release.fat.a
READ: data.pck

 platform/iphone/export/export.cpp:401 - Condition ' !da ' is true. returned: ERR_CANT_OPEN
 editor/project_export.cpp:762 - Failed to export project
```

All required launch screen images and icons have been included, and the team_id field has been filled.

**Steps to reproduce:**

Export any project on the master branch to iOS

**Minimal reproduction project:**

[ios_export_project.zip](https://github.com/godotengine/godot/files/2220262/ios_export_project.zip)

thanks for the help, this issue has been very frustrating for me!

**Comment by jahd2602** [comment]
I am getting the same error in master @ cfcb6e11f25adb13177ba08777263288a5ec6f61
(just before typed gdscript merge)

**Comment by jahd2602** [comment]
It is probably related to this commit https://github.com/godotengine/godot/commit/1d9a3a9b1c9ef7db26e53c8aeaab731992cffd6e

**Comment by wombatwingdings** [comment]
I'm also getting this error on master with clean pull and build from 12 Jan 2019. The line number has now moved to export.cpp:472 due to further commits since the problem was originally reported. But it is the same code.

Looks like export to iOS is broken for all at the moment.

**Comment by akien-mga** [comment]
Since this appears to be an issue with the compilation docs, I'm moving it to godotengine/godot-docs#2153.
