### ISSUE TITLE
Ctrl + Click to get function definition in GDscript only works if function is declarated before the call

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#20393]
**Godot version:**

Godot 3.1dev 17/07/2018

**OS/device including version:**

Win7 and probably all systems

**Issue description:**

Doing control + click in a user function inside a script only scrolls to that function if this was declarated previously to the clicked text.

**Comment by bojidar-bg** [comment]
Somewhat related: #5973

**Comment by PLyczkowski** [comment]
Bump? This one is annoying and seems like an easy fix...

**Comment by 2shady4u** [comment]
Trying to solve this with PR #31112
All comments welcome!

**Comment by akien-mga** [comment]
Fixed by #31843.
