### ISSUE TITLE
direct space state intersect_ray function doesn't seem to take excludes into account

### ISSUE THREAD

**Issue by Ijatsu** [godotengine/godot#2039]
Here's my function:
```javascript
const ray_length = 1000
func screen_center_raycast (camera, caster):
	var from = camera.project_ray_origin(screen_center)
	var to = from + camera.project_ray_normal(screen_center) * ray_length
	
	var space_state = caster.get_world().get_direct_space_state()
	var result = space_state.intersect_ray( from, to, [ caster ] )
	
	return result
```
This function basically cast a ray from the center of the screen (like a common fps) 

and here is the call
```javascript
func _fixed_process(delta):		
	if( right_click):
		right_click = false
		var result = global.screen_center_raycast(camera, self)
		if( result.has("collider") && result.has("shape") &&  result.has("normal")):
			print("right click " , result.collider , " " , result.shape , " " , result.normal)
			result.collider.right_click( result.shape, result.normal)
```
self is a rigidbody node and camera is a children camera node.

The problem is: the result of this function always return the "self" node which shouldn't since I gave "self" as an exclude for the raycast.

This bug is present in the latest sources but not in the 1.1 official release.

**Comment by Ijatsu** [comment]
it works if I feed the function with caster.get_rid()
Is it a normal change?

**Comment by FEDE0D** [comment]
In 2d the excluded bodies are passes using an array. Did you try using [self]?

**Comment by Ijatsu** [comment]
FEDE0D, I don't understand what you mean, why would I give an array with self if I put it in an array then?

**Comment by akien-mga** [comment]
It's working fine for me in the master branch in 2D (see e.g. https://github.com/akien-mga/dynadungeons/blob/master/scripts/bomb.gd#L78) so I guess that would be specific to 3D / RigidBody?

**Comment by akien-mga** [comment]
```PhysicsDirectSpaceState::_intersect_ray``` does seem to expect an array of RIDs indeed: https://github.com/godotengine/godot/blob/2d8866574dd2c06ac03e7055642b917a0a3c6dac/servers/physics_server.cpp#L260 so it's not a bug per-se.

Now the question is whether we can improve the function to make it accept also object references instead of just RIDs?

**Comment by reduz** [comment]
As per this commit on April 24, it should work:
https://github.com/godotengine/godot/commit/1f8e3117dd8643b9c6d6127a891a0f4673479fa2
Does it still fail?

**Comment by Ijatsu** [comment]
I compiled the last commits of sources and tested, and it doesn't fail, the excluded body is not considered colliding the raycast. :)

**Comment by akien-mga** [comment]
Thanks!
