### ISSUE TITLE
Creating a PhysicalBone crashes the editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20397]
Godot master 779c9d638e7046f285b301aa79f7cf50aa4c2f1c
Windows 10 64 bits

1) Create a new scene with a root `Node`
2) Create a child node of type `PhysicalBone`: editor crashes.

![image](https://user-images.githubusercontent.com/1311555/43109799-91114e88-8ee0-11e8-8752-f542a3470e27.png)

**Comment by bojidar-bg** [comment]
CC @AndreaCatania
