### ISSUE TITLE
Add a way to directly perform a Raycast from a Camera

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#20398]
**Godot version:** 3.0.5 +

https://godot.readthedocs.io/en/latest/classes/class_camera.html

The Camera node has some methods for assisting with projecting rays, but none of these methods actually perform full Raycasts. I think it would be useful to have a method which returns a [RayCast](https://godot.readthedocs.io/en/latest/classes/class_raycast.html#class-raycast) object containing a RayCast from the mouse position on the screen into the world. That way, I could, for example, simply run `get_collision_point()` on that returned RayCast object to figure out the 3D point on a CollisionShape in the world that the camera is pointing at.

**Comment by Zylann** [comment]
Why not just:
- Putting a RayCast node as child of the camera pointing forwards?
- Or doing the raycast via code using `-transform.basis.z`?

**Comment by pgruenbacher** [comment]
https://godotengine.org/qa/1996/ray-casting-from-the-camera-in-3d

also input_ray_pickable may also help if you're trying to pick objects from your camera and mouse.
https://godotengine.org/qa/1996/ray-casting-from-the-camera-in-3d
