### ISSUE TITLE
Layer editor shouldn't close each time one is toggled

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20399]
Godot 3 master 779c9d638e7046f285b301aa79f7cf50aa4c2f1c
Windows 10 64 bits

In Godot 3.0.5, clicking on collision layer mask editor would open a popup with checkboxes, and you could toggle one or more without closing the popup.

In master the new popup closes everytime. It would be nice to keep the previous behaviour.

**Comment by AlexHolly** [comment]
Is this fixed?

**Comment by akien-mga** [comment]
Fixed by #20466.
