### ISSUE TITLE
New file manager declares file is corrupt, but displays fine in Ristretto

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#2040]
This is the conflicting file, the top face of a cubemap: https://lut.im/vOebvJLd/f0tRDVe5

It displays just fine in Ristretto and Chromium, yet Godot says the file is corrupt when trying to generate a thumbnail.

![Image](https://lut.im/N3WA6uNy/lH8e5sbl)

```
ERROR: load_image: Condition ' ret!=0 ' is true. returned: ERR_FILE_CORRUPT
   At: drivers/jpg/image_loader_jpg.cpp:52.
ERROR: load: Failed loading image: res://media/textures/sky/arid2_up.jpg
   At: scene/io/resource_format_image.cpp:114.
ERROR: load_image: Condition ' ret!=0 ' is true. returned: ERR_FILE_CORRUPT
   At: drivers/jpg/image_loader_jpg.cpp:52.
ERROR: load: Failed loading image for BitMap: res://media/textures/sky/arid2_up.jpg
   At: scene/resources/bit_mask.cpp:219.
ERROR: load: Failed loading resource: res://media/textures/sky/arid2_up.jpg
   At: core/io/resource_loader.cpp:209.
ERROR: free: Method/Function Failed.
   At: servers/visual/visual_server_raster.cpp:4668.
```

**OS:** Debian stretch 64-bit
**Godot Git commit:** 8d61817, Sun Jun 7 00:32:29 2015 -0300

**Comment by akien-mga** [comment]
Yeah I've seen the same issue on Mageia 5 64-bit, I just went browsing in my ~/Images folder where I have random stuff and maybe 5% of the JPG files could not be displayed. That's a minor disagreement though :)

**Comment by Calinou** [comment]
This still happens with latest Godot Git (compiled on 2015-11-27), with JPEG, PNG and WebP images.
