### ISSUE TITLE
Exported variable of type float is mistaken for an int if not explicitly using decimals

### ISSUE THREAD

**Issue by mrzapp** [godotengine/godot#20402]
**Godot version:**
v3.1.dev.custom_build.b665809 (godot-git from the AUR)

**OS/device including version:**
Manjaro 17.1.11

**Issue description:**
An assignment of float value fails, with variables both indicated as type "float", as the exported variable is still considered an int, unless a decimal place is added

**Steps to reproduce:**
1. Create an exported variable of type float and save the script
2. Make an assignment to a float variable created using optional typing at runtime

**Code example**
```
export (float) var exported_float = 5

func _ready():
    var runtime_float : float = 0.5
    runtime_float = exported_float # <- This fails
```
**Workaround**
If you add a decimal place to the exported float, it will work. However, the inspector doesn't allow adding .0, so you do have to actually change the number

**Comment by akien-mga** [comment]
CC @vnen

**Comment by mrzapp** [comment]
It seems that the export (type) is only used as an instruction to the inspector and not considered a "real" static type. Using this code might work:

```
export (float) var exported_float : float = 5

func _ready():
    var runtime_float : float = 0.5
    runtime_float = exported_float # <- This works now
```

I will test this once the engine is done compiling

**Comment by zedutchgandalf** [comment]
Why do you still need the export type if the variable has a static type? That seems a bit redundant...

**Comment by mrzapp** [comment]
@zedutchgandalf In this particular case it's redundant, but:  
1. If I leave it out, the user can input float values into the inspector, even though I want an int
2. There are more features of the export hint than just indicating the type, such as [range definitions](docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#exports)

**Comment by vnen** [comment]
To clarify, you *can* omit the export hint: `export var my_float = 5.0` worked before and still do. With type hints you can also do: `export var my_float : float`.

If you need other arguments from the hint (like range), then you need to make the full export hint, repeating the type. `export` is an editor/serialization helper, type-hints are for forcing the variable to have a static type. They are not directly related.

**Comment by mrzapp** [comment]
@vnen Understood, it makes perfect sense. I'll close this issue, then. Good work on the static typing feature, I love using Godot even more! 😁

**Comment by vnen** [comment]
It was just a note, the OP is actually a bug since it should accept an int assigned to a float variable. I'm already preparing a fix to this and other issues, I'll keep this one open until we merge the fix.
