### ISSUE TITLE
Rigid bodies fall through trimesh / Collada-generated static bodies

### ISSUE THREAD

**Issue by Rattel** [godotengine/godot#20408]
**Godot version:**
v.3.0.stable.official

**OS/device including version:**
Lubuntu 18.04, AMD E1-6010 APU with AMD Radeon R2 graphics

**Issue description:**
Rigid bodies (mostly ones that have box shapes with changed extents or trimesh shapes generated from meshes) tend to 'fall' through static bodies that have trimesh / Collada-generated shapes. Default box-shaped rigid and static bodies work fine though. Also kinematic bodies collide and slide fine with the problematic static bodies. Not sure if it's a Godot bug or I do something wrong?
https://youtu.be/6Bsv9yCTgbg
https://youtu.be/zNtpzmws314

**Steps to reproduce:**
Create a mesh in Blender with -col suffix to be exported with Collada and import (or choose 'create a trimesh collision' in Godot itself to make a static body)
Create a rigid body with box collision with changed extents or generate trimesh collision shape from a mesh
Make the rigid body 'fall' onto the static body
Sometimes rigid bodies act fine and sometimes they fall through

**Comment by Rattel** [comment]
Yep, for rigids I tried the collision shapes that are available to choose (like box or sphere), and seems like they do work fine but if I change their extensions or radius, this issue appears.

**Comment by Rattel** [comment]
After searching more info, seems like it's the physics "tunneling" problem, rising physics FPS level and linear velocity damp improved the situation, but it's weird that in my case it happened at relatively slow speeds

**Comment by takhimi** [comment]
@mysticfall Does 3.1 solved your problem ? I still got bunch or rigidbody on the floor and when the player (KinematicBody) moves or collides with them , it will be pushed down or out from the floor or wall which are trimesh collision shape.

**Comment by mysticfall** [comment]
Yes, I can confirm that this is reproducible with 5b00cd89. The ground mesh looks like this:

![image](https://user-images.githubusercontent.com/2367032/55458588-51a59f00-5628-11e9-8697-824b86b3bd8b.png)

**Comment by bojidar-bg** [comment]
5823b5d77d47339c3c981953ca8178e7ef14b6df added support for [convex decomposition](https://godotengine.org/article/godot-3-2-adds-support-convex-decomposition). Maybe it has somewhat fixed the problem?

**Comment by takhimi** [comment]
@bojidar-bg nope it still happens. After watching Juan GDC videos, we may need to wait for Godot 4.1. Now they are focusing on other things like Vulkan, Navmesh, performance on typed gdscript, android, godot in browser and etc. 

Unless somebody comes in and try to fix this.

**Comment by asheraryam** [comment]
It's not only for trimesh, and it's not only for rigidbodies.

It also happens in the following scenario: KinematicBody player with simple sphere as collision shape, and StaticBody obstacle with convex collision shape (changing it to trimesh didn't help).

So the main issue can be summarised as "a moving physics body will tunnel into a moving static body".

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by asheraryam** [comment]
@KoBeWi I tried 3.2.3 and [u]my[/u] issue https://github.com/godotengine/godot/issues/20408#issuecomment-511135433 seems to be fixed, but I cannot confirm if the OP issue is fixed as it wasn't confirmed that they were related.

**Comment by slapin** [comment]
Seems to work for simple cases.

**Comment by akien-mga** [comment]
Let's close then as there's no new report of a similar issue to OP's.
