### ISSUE TITLE
Rename an "Instanced Scene as Node" disables "Editable Children"

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#20409]
https://github.com/godotengine/godot/commit/89e1b302b504feb1cea218adcc6fac77c8ae0052
x11

It only happen if it's a name that the node never had before.

![peek 2018-07-24 15-22](https://user-images.githubusercontent.com/4741886/43141195-a0ca2c76-8f55-11e8-9968-034fa812be30.gif)

**Comment by QbieShay** [comment]
@akien-mga I see this is in no milestone at the moment, but I can reproduce with 2940475c716eab517ca52957acc87

This is my reproduction case: 
[EditableChildrenReset.zip](https://github.com/godotengine/godot/files/2936487/EditableChildrenReset.zip)

**Steps to reproduce:**
1. open `main.tscn`
2. tick editable children on the `RenameMe` node
3. move the rigidbody around
4. rename the `RenameMe` node with something different
5. close and reopen the scene.

**Comment by QbieShay** [comment]
Seems like @DualMatrix 's [changes](https://github.com/DualMatrix/godot/commit/b170c6143f1addddc177545e27c35ed1a3414b5d) are fixing this issue ( merged his work on the master branch ) and also adds the ability to duplicate instanced scenes which is great!
