### ISSUE TITLE
Do not display hidden folders in new file manager

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2041]
Currently the new file manager (as of 8d618172) displays hidden folders on Linux, which can be bothersome when trying to locate a file in your home directory. It would probably be best not to show hidden folder by default, and maybe to have a CheckButton to toggle visibility of hidden folders.

**Comment by Calinou** [comment]
:+1:, note that Ctrl + H is commonly used to toggle visibility of hidden directories.

**Comment by bojidar-bg** [comment]
+1, maybe not a checkbox, but some preferences dialog :smile:

**Comment by alketii** [comment]
+1
I don't mind not seeing them at all, since hidden folders are not meant for end-users but for certain programs.

**Comment by erik90mx** [comment]
+1 for checkbox preference in Godot's file manager menu

**Comment by est31** [comment]
+1 (kobuge crowd support)

**Comment by fry-** [comment]
:+1: +1 (Kobuge peer pressure)
