### ISSUE TITLE
Better project-wide group management

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#20416]
**Godot version: 3.0+**

**Issue description:**

Groups are great but group management is terrible, if available groups are stored in the Project, then can be easily used in the scene editor and scripts (with autocompletion) reducing risks of typos.

It can be exactly like Autoload tab on Project Settings, and add the groups to the project confguration file to be accessible project-wide (pretty much like physics layers).
![groupmanagement](https://user-images.githubusercontent.com/10215987/43154778-ef096eec-8f4b-11e8-958f-180ffac195f9.png)

This will allow:
 - Show the groups on the group tab (Node dock), and let you only select from a checklist (or dropdown, but checklist looks better).
![groupdock](https://user-images.githubusercontent.com/10215987/43154708-b9808e86-8f4b-11e8-985b-67506b7066ee.png)
 - Autocompletion of groups names for scripts.

I'm only proposing the idea because UI stuff is too far from my reach as can be seen in the mockups.

ps: I know that there is a new interface for groups on master but is far from ideal also not working at all across scenes.

**Comment by Zylann** [comment]
Oh, you did it again? https://github.com/godotengine/godot/issues/5744
But you have fancy screenshots :)

**Comment by eon-s** [comment]
@Zylann I was sure I made one but could not find it, so I supposed that was just a comment on another issue, I'll close it again I guess :sweat_smile:
