### ISSUE TITLE
Blank/Comment lines at the beginning are considered "unsafe"

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#20418]
**Godot version:**
cf297b4

**Issue description:**
If a typed GDScript file starts with a blank line or a comment, these lines will be considered unsafe until it reaches a line of actual code.

**Comment by akien-mga** [comment]
Still reproducible in the current master branch.

**Comment by YeldhamDev** [comment]
@akien-mga I would consider this a bug rather than an enhancement request.

**Comment by akien-mga** [comment]
One can argue both ways (incomplete feature vs wrong behavior), but I'm fine changing it.

**Comment by YeldhamDev** [comment]
Doesn't happen anymore on `master`.
