### ISSUE TITLE
Suggestion: Do not halt if Script.reload() fails and return a ScriptParseResult object

### ISSUE THREAD

**Issue by Kinsman** [godotengine/godot#20421]
**Godot version: 3.0.2** 

**Issue description:**
I'm writing an event scripting engine in GDScript, suitable for visual novels or similar games. I had a thought that instead of interpreting line-by-line, I could write code that would transform what I wrote into GDScript (with post-processing that could have the code, for instance, block for input after certain lines) and attach it as a script to my game.

The documentation says that Script.reload() will return an error code. It can return an OK code, but Godot halts if there's a parsing error. If I'm using the editor, I can read what the error was; but if I or a modder was running my game and trying to edit a script, they'd need to have their script either be perfect, or crash the game without explanation.

Could you please add an extra argument where Godot will not halt if Script.reload() fails - and instead of an Error code, return a "ScriptParseResult" object, similar in structure to JSONParseResult?

Thank you.

**Comment by zx013** [comment]
I am also looking forward to this feature. I expect to edit the gdscript on Android, so Script.reload() halt which will cause me some troubles. This makes it difficult for me to locate script errors.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by zx013** [comment]
I went to see the source code of reload in godot3.3 and tested it. I found that Script.reload will call the debug_break_parse function to halt only when debugging. When the project is exported, reload will return the correct error value.
