### ISSUE TITLE
For some sizes of the code editor scrolling with the mouse does not reveal the last one or two lines

### ISSUE THREAD

**Issue by ficoos** [godotengine/godot#20420]
**Godot version:**
9377f8db5

**OS/device including version:**
Linux 4.17.7-200.fc28.x86_64 #1 SMP x86_64 GNU/Linux

**Issue description:**
For some sizes of the code editor scrolling with the mouse does not reveal the last one or two lines.

**Steps to reproduce:**
Resize the code editor and try to scroll down. If it works resize a bit and try again until it happens.
For me it happens when the code editor is at maximum size on full screen at 1920x1080 but the size of the window title bar is different between OSs.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Is this reproducible on 3.1 or with a [daily build](https://hugo.pro/projects/godot-builds/) of the `master` branch?

If so, can you reproduce this when you disable **Text Editor -> Open Scripts -> Smooth Scrolling** in the Editor Settings?

**Comment by KoBeWi** [comment]
Doesn't seem to happen in 3.1 stable.

**Comment by akien-mga** [comment]
Assuming fixed in 3.1. Please comment if you can still reproduce it.
