### ISSUE TITLE
Make transform inspector more compact

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20423]
Godot 3.1

I find the inspector for transforms is taking a lot of space.
Spatial, Rigidbody, shader params, everytime there is one, it is composed of 3 vertical fields for position, then 3 vertical fields for rotation, then again 3 vertical fields for rotation, AND also a raw 3x4 matrix which is not used often (see #20419).

See the comparison between Godot and Unity, to scale:

![image](https://user-images.githubusercontent.com/1311555/43169131-c086767c-8f97-11e8-9848-962069dd7aee.png)

We can fit the other one 5 times.

I think a proper transform editor should more look like the Unity one, with the 3 properties fields inline, and eventually have a toggle button to switch to raw mode where the full control represents the raw matrix.
More like:
![image](https://user-images.githubusercontent.com/1311555/43169806-624e7926-8f9a-11e8-883d-a6167735b7f4.png)
Or:
![image](https://user-images.githubusercontent.com/1311555/43169846-834b5216-8f9a-11e8-9033-440c221691c7.png)

**Comment by mattiascibien** [comment]
I definetely like the proposal. Seems better to me.

**Comment by Two-Tone** [comment]
I agree that these look good, although I prefer the first one as it doesn't
waste much space.

**Comment by Zylann** [comment]
It's in master now, if you want to have a look ;)

**Comment by reduz** [comment]
closing, as this is indeed in Master now.

**Comment by Radivarig** [comment]
This was closed as completed, but I don't see the full compact state no matter how much I resize the inspector.

And there's a lot of space between the name and the values that could be used if the width is low.

| Current | Compact |
|---------|---------|
| ![Current](https://github.com/user-attachments/assets/ae982339-2674-4c56-bb01-7585061355ff) | ![Compact](https://github.com/user-attachments/assets/0629f08e-192d-475c-97ca-e101a5d0a8db) |
