### ISSUE TITLE
visual scripting shift + A bug!

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#20433]
@fire 
Shift+A shows search box at every screen weather its 2d, 3d or asset library.
When i select a specific function from the search box it hang and crashes the software.
Sequencing drop works fine but it shows some non select-able option like float in physics_process.

**Comment by fire** [comment]
Will look into it.

**Comment by fire** [comment]
Pushed a fix for part 3. (part 2 is associated with part 1).

**Comment by fire** [comment]
Pushed to master.

**Comment by akien-mga** [comment]
Fixed by #20450 and #20452.
