### ISSUE TITLE
Problems with the new Physics Materials.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#20434]
**Godot version:**

f8e8ac2c664a12f3af2b9bb545da193d86c75503

**Issue description:**

It spawns a warning and an error when ever a PhysicsObjects are instanced.

WARNING: set_friction: The method set_friction has been deprecated and will be removed in the future, use physical material
   At: scene/3d/physics_body.cpp:186.
WARNING: set_bounce: The method set_bounce has been deprecated and will be removed in the future, use physical material
   At: scene/3d/physics_body.cpp:212.
WARNING: set_friction: The method set_friction has been deprecated and will be removed in the future, use physical material
   At: scene/3d/physics_body.cpp:620.
WARNING: set_bounce: The method set_bounce has been deprecated and will be removed in the future, use physical material
   At: scene/3d/physics_body.cpp:642.
ERROR: disconnect: Nonexistent signal: changed
   At: core/object.cpp:1465.

The main problem is that it drops the framerate, leading to unexpected physics behaviour.
My guess is that the slow down comes from the ERROR

**Comment by kakoeimon** [comment]
Seems like that the failure of the rayshape have something to do with the soft bodies. Unchecking the physics/3d/active_soft_world in the project settings fixes the problem.

**Comment by Noshyaar** [comment]
Closing as Fixed by #20381
