### ISSUE TITLE
Spatial material's some parameter are not working some of them does not give the expected result!

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#20437]
win10, 960m nvidia
Clearcoat is not working 
![screenshot 47](https://user-images.githubusercontent.com/13883739/43184893-cad9d112-9007-11e8-9033-48c084293954.png)

Depth parallax does not show expected result
expected result https://www.youtube.com/watch?v=XwVDhljljro
https://www.youtube.com/watch?v=6PpWqUqeqeQ
![screenshot 43](https://user-images.githubusercontent.com/13883739/43184973-163ec3ec-9008-11e8-9c3a-a14641223a3e.png)
![screenshot 44](https://user-images.githubusercontent.com/13883739/43184974-16b27c88-9008-11e8-9574-3e474f3be58d.png)
![screenshot 45](https://user-images.githubusercontent.com/13883739/43184976-172530ca-9008-11e8-87ba-6f247f564151.png)

SSS are still not good. and with RIM on it further breaks the material. It might be good to have something like blur/jitter control like in blender2.8
![screenshot 46](https://user-images.githubusercontent.com/13883739/43185088-7d1dc95a-9008-11e8-8650-5f72e05a6092.png)
![screenshot 48](https://user-images.githubusercontent.com/13883739/43185089-7d50549c-9008-11e8-9a3e-5bed45b12c81.png)

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/14403 and https://github.com/godotengine/godot/issues/15934 for issues on clearcoat and depth mapping.

**Comment by gamergamesz** [comment]
Got fixed
