### ISSUE TITLE
Minor Node2D naming nitpick.

### ISSUE THREAD

**Issue by zspinelli** [godotengine/godot#20430]
Node2D: Featureless node with 2d spatial properties.
Spatial: Featureless node with 3d spatial properties.

The Node2D and Spatial seem to be their respective dimension's node equivalent, so why not rename one to show this?
I propose renaming Node2D to Spatial2D.

**Comment by aaronfranke** [comment]
We could also call it "Planar" or "Flat" something. But in the end, we probably won't break compatibility.

"Spatial" implies 3D space. A 2D world contains no volume.

**Comment by akien-mga** [comment]
We're indeed not going to do such a major compatibility breakage, invalidating all existing Godot projects and the documentation for this.

As @aaronfranke mentioned, "Spatial"/"Space" most commonly implies a three-dimensional extent/volume: https://en.wikipedia.org/wiki/Space
It *can* also be used to refer to a N-dimensional space, including 2D, but that's not the common use case and wouldn't bring much over the current Node2D.

The 2D equivalent would be "Areal", but then again it's hardly an improvement and not worth breaking everything. If we were back in 2007 when those names were chosen we could maybe bikeshed further, but today it's way too late for any such change.
