### ISSUE TITLE
Rearranging nodes in the scene panel with keyboard shortcuts no longer works.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#20445]
**Godot version:**
Calinou's nightly 3.1 build a2f9ce2

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Using `Control+Up Arrow` and `Control+Down Arrow` in the Scene panel will no longer move nodes up or down like it did in Godot 3.0. All it does it select the next node in the direction pressed. I checked the shortcuts and they were still set to Control+Up and Control+Down, I tried changing them to different keys and it still didn't move the nodes.

**Comment by reduz** [comment]
It would be interesting to do a bisect to figure out when this started happening. Anyone with a fast computer up for giving it a try?

**Comment by volzhs** [comment]
it has happened since #17633

**Comment by akien-mga** [comment]
Duplicate of #17633.
