### ISSUE TITLE
FileSystem view improvements

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#20444]
We are basically suggesting to make it possible to see files directly in the Tree view.

**List of improvements for the FileSystem view in Godot 3**

- A toggle button in the editor settings to turn the FileSystem split view on and off. 
- When Filesystem is not in split view it should show files directly in the tree view (see image 1).
- Favorites should both be able to contain files and folders. 
- Textures should show a small thumbnail of the image. All other file types should show the small icon currently shown in the left corner of a file (See image 2).

**Image 1** This is a Mockup of Unitys file system view. It shows what we are aiming for.
![image](https://user-images.githubusercontent.com/24936603/43197925-0fbf4d98-900d-11e8-8c14-bb4089cf4340.png)

**Image 2** These icons should be used in the Tree view.
![image](https://user-images.githubusercontent.com/24936603/43199828-900d965c-9013-11e8-90d6-cd1ab6e0d20f.png)

**Comment by jesperkondrup** [comment]
I uploaded a 100 mb test project with a huge amount of files and many different file types included.

[https://github.com/jesperkondrup/GodotFileSystemTest](url)

**Comment by akien-mga** [comment]
Fixed by #21426.
