### ISSUE TITLE
New Inspector panel can no longer be selected.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#20446]
**Godot version:**
Calinou's nightly 3.1 build a2f9ce2

**OS/device including version:**
Windows 10 64bit

**Issue description:**
I'm not sure if that's the correct term. But for all other panels, like the Scene panel, FileSystem panel, etc, when you click on the panel it gets a light grey border showing that it's selected. The new Inspector panel doesn't do that, the last selected panel is still highlighted.

**Comment by homer666** [comment]
This seems to be fixed. Tested with cb5a629 on Linux Mint 19 Cinnamon x64

**Comment by homer666** [comment]
Oh whoops I misread, thought you were talking about the filesystem...

**Comment by KoBeWi** [comment]
I don't think this is a bug. Unlike filesystem or scene panel (which are Tree nodes), inspector doesn't have content on its own, so there's nothing to select/focus on. Only inspector controls can be focused.
