### ISSUE TITLE
(Feature Request) ParallaxBackground to ignore Camera2D zoom

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#2045]
I've searched everywhere for a solution to this but I couldn't find anything in the forums or the facebook group: how to set the parallax background to ignore the camera zoom (in 2D world)  or at least making it so it repeats the background accordingly.
This is what the background layer looks like when the camera zoom it's not 1:1
![pantallazo](https://cloud.githubusercontent.com/assets/6296184/8026350/739ab08c-0d48-11e5-9ff7-50f33d7ae217.png)

**Comment by reduz** [comment]
ah yes, this is a longstanding issue and needs to be resolved..

**Comment by FEDE0D** [comment]
Already solved & merged #2330
