### ISSUE TITLE
pressing Shift-A in GDScript editor shows VisualScript search

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#20454]
Pressing Shift-A in GDScript editor shows VisualScript search rendering editor
hard to use.
**Godot version:**

41a0ecb59b244ee01ece644107f02c64d2a5b64a

**OS/device including version:**

Linux

**Comment by fire** [comment]
See https://github.com/godotengine/godot/issues/20433

**Comment by akien-mga** [comment]
Duplicate of #20433.
