### ISSUE TITLE
Godot crashes when opening a project, can't write caches and confiqs

### ISSUE THREAD

**Issue by usernameisalreadytakennn** [godotengine/godot#20461]
**Godot version:**
Godot 3.0.5 64-bit Mono version.

**OS/device including version:**
Windows 10

**Issue description:**
When creating and opening a project, Godot crashes instantly after it has loaded the project. It seems that it cant write confiq and cache files:
![image](https://user-images.githubusercontent.com/41706229/43227996-001790e2-9069-11e8-8057-4d465be917b7.png)
There isn't even a file called projects in godots appdata folder, so it doesn't even start  writing the fscache.
Also every time when opening the launcher, it says that i dont have any projects and sets the default language, but thats expected since it cant write confiqs.

Also, i dont have an antivirus other than windows defender.

**Steps to reproduce:**
Opening a project.

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/2229575/project.zip) (just a basic empty project)

**Comment by qarmin** [comment]
Seems that you had problem with permissions in appdata folder.

Can you reproduce this with the latest version?

I think that reinstalling OS should help fix this issue.

**Comment by usernameisalreadytakennn** [comment]
> Seems that you had problem with permissions in appdata folder.
> 
> Can you reproduce this with the latest version?
> 
> I think that reinstalling OS should help fix this issue.

Yeah it was, if I remember correctly it was windows' controlled folder access which prevented it from writing.

Solved it by myself after opening this thread, but then forgot to close this. 
My bad, sorry!
