### ISSUE TITLE
Autotile editor is not responsive, zoom buttons disappear

### ISSUE THREAD

**Issue by Charlignon** [godotengine/godot#20471]
**Godot version:**
Godot Engine v3.0.5.stable.official.6a88e22

**OS/device including version:**
Windows 10
Screen resolution : 1366x768‎

**Issue description:**
In the autotile editor, on the tabs Collision / Occlusion / Navigation, the grid snap configuration option is off by default. When switching, the menu expand anf option like 'Offset' and 'Step' appear. This push the zoom buttons (+ / 1 / -) off the screen.
However, it does not come back when switching off, the position is still off screen. You have to force the view to update (closing and reopening the autotile editor, resizing the window...) to get the zoom buttons back.
This occurs on small windows, so obviously everytime on small screens.

**Steps to reproduce:**
1- Get Godot in a small window (resize if necessary)
2- Go to autotile editor, then Collision tab for example
3- Click on the last icon of the line. Three options, with 6 spinboxes (2 each) should appear
4- Zoom buttons may be out of screen if your window is small enough
5- Click the same button again: Zoom buttons does not come back

**Suggestion:**
Simply change the location of these buttons (bottom right of this editor for example)

**Pictures:**
View of menu step by step : http://prntscr.com/kb4oz5

**Minimal reproduction project:**
[Zoom buttons.zip](https://github.com/godotengine/godot/files/2230475/Zoom.buttons.zip)

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by MarianoGnu** [comment]
check https://github.com/godotengine/godot/pull/20585
zoom buttons are still on the same location thought and can dissapear on a very small screen, but i had not major problems to use the editor in a 17" monitor

**Comment by akien-mga** [comment]
Assuming fixed by #20585.
