### ISSUE TITLE
Godot 3 compiling issues on latest OSX

### ISSUE THREAD

**Issue by thisismike97** [godotengine/godot#20482]
**Godot version:** Tag stable 3.0.3 and 3.0.5.
**OS/device including version:** macOS High Sierra 10.13.6. (Latest version.)
**Xcode version:** 9.4.1. (Latest version.)
**Scons version:** 3.1.0. (Latest version.) (Also tried with scons 2.5.0.)
**Python version:** 2.7.12.
**Issue description:** 

Compiling gets stuck at 62% on this file: "[Initial build] Compiling ==> servers/physics/collision_solver_sat.cpp"

Compiling with the following parameters: sudo scons platform=osx bits=64 target=release tools=no (I also tried it with fat bits.)

I've tried removing the problematic file, but a little bit later the compile still fails with the following log:

> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: modules/recast/librecast_builtin.osx.opt.64.a(RecastAssert.osx.opt.64.o) has no symbols
Ranlib Library         ==> modules/recast/librecast_builtin.osx.opt.64.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: modules/recast/librecast_builtin.osx.opt.64.a(RecastAssert.osx.opt.64.o) has no symbols
[Initial build] Linking Program        ==> bin/godot.osx.opt.64
Undefined symbols for architecture x86_64:
  "sat_calculate_penetration(ShapeSW const*, Transform const&, ShapeSW const*, Transform const&, void (*)(Vector3 const&, Vector3 const&, void*), void*, bool, Vector3*, float, float)", referenced from:
      CollisionSolverSW::concave_callback(void*, ShapeSW*) in libservers.osx.opt.64.a(collision_solver_sw.osx.opt.64.o)
      CollisionSolverSW::solve_static(ShapeSW const*, Transform const&, ShapeSW const*, Transform const&, void (*)(Vector3 const&, Vector3 const&, void*), void*, Vector3*, float, float) in libservers.osx.opt.64.a(collision_solver_sw.osx.opt.64.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.osx.opt.64] Error 1
scons: building terminated because of errors.

**Comment by akien-mga** [comment]
It's the same issue as #18023 and fixed by #18868 in the master branch. That fix needs to be cherry-picked in the 3.0 branch (CC @hpvb).

**Comment by hpvb** [comment]
I've pulled the fix into the 3.0 branch.
