### ISSUE TITLE
GDScript Expose Directory.erase_contents_recursive and copy_dir

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#20486]
1.
It would be nice to have `Directory.erase_contents_recursive()` in GDScript.
https://github.com/godotengine/godot/blob/master/core/os/dir_access.cpp#L134

Is it open for discussion or do you say that it is too dangerous?

It would be a bit safer to add `Directory.erase_contents_recursive(path)`.
Using dir.erase_contents_recursive() without open deletes the current project.

2.
Also Directory.copy is a bit misleading it only copies files and copy_dir is not exposed.
Maybe rename copy or simply expose copy_dir?

**Comment by akien-mga** [comment]
As mentioned on #21226, this is too dangerous to expose.
