### ISSUE TITLE
Dictionary: try(key) method to return value or null when key doesn't exist.

### ISSUE THREAD

**Issue by stephanngamedev** [godotengine/godot#20488]
**Actual behavior:**
Raise a error 'Invalid get index 'key_name'

**New behavior:**
- Keep raising error but dictionaries will have the method 'try(key_name)' which returns value if key exists or returns null if the key doesn't exist

This will clean the code. The multiples lines with `if my_dictionary.has('key_name'): my_variable = my_dictionary.key_name` will no longer be necessary. It increases the developer happiness.

**Comment by williamd1k0** [comment]
I agree with this one but I think it should be more similar to Python:

`dict.get(key[, default])`: which returns `None` or `default` if the key doesn't exist (it doesn't raise any error).

Docs: https://docs.python.org/3/library/stdtypes.html#dict.get

**Comment by malcolmhoward** [comment]
Does anyone mind if I attempt this one?  It's not currently assigned.  Are there any recommendations for testing builds without having to rebuild the entire project after each change, such as a way to run it in debug mode?

**Comment by malcolmhoward** [comment]
@ordidug Thanks.  I found the answer.

For anyone with a similar question in the future,  please see the following from the docs:  http://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html#improving-the-build-system-for-development

"However the trade-of is every single change means a full recompilation of the game. Even if SCons is able to detect and recompile only the file that have changed, finding such files and eventually linking the final binary is a long and costly part.

The solution to avoid such a cost is to build our own module as a shared library that will be dynamically loaded when starting our game’s binary."

**Comment by akien-mga** [comment]
Fixed by #20627.
