### ISSUE TITLE
CPUParticles error when spread is used.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#20480]
**Godot version:**

832e2bfcd38965a01a9149d509169dd197e42f58

**OS/device including version:**

**Issue description:**

An error is spammed when spread is used in CPUParticles

ERROR: move: Condition ' Math::is_nan(p_aabb.size.x) ' is true.
   At: core/math/octree.h:847.

**Steps to reproduce:**
Create a CPUParticle (set it up) and use spread.

**Minimal reproduction project:**

[cpuparticles.zip](https://github.com/godotengine/godot/files/2231563/cpuparticles.zip)

**Comment by JFonS** [comment]
Seems fixed in master.
