### ISSUE TITLE
Audio Recording from godot #15967 crash

### ISSUE THREAD

**Issue by fire** [godotengine/godot#20487]
**Godot version:**

03e11c13bfb1649fc9cf9a460249bce5e7f07462

**Issue description:**

@Tugsav

Create a new project.

Add record to audio bug, and enable recording.

Restart project. 

The editor crashes.

![devenv_2018-07-26_08-54-10](https://user-images.githubusercontent.com/32321/43273536-8d1e4c54-90b1-11e8-9c9e-878b8719bcf2.png)

**Minimal reproduction project:**
[Audio Record Crash.zip](https://github.com/godotengine/godot/files/2232671/Audio.Record.Crash.zip)

**Comment by Tugsav** [comment]
Ah. It forgot to test using it through the editor, as the original intent was to enable the recording during runtime through a script.
I will look into it.

**Comment by hpvb** [comment]
Is this indeed fixed by #20508 ? Can this be closed?

**Comment by fire** [comment]
Completely forgot about this. Have to travel so try out the test case.

**Comment by fire** [comment]
Doesn't crash anymore.
