### ISSUE TITLE
Singletons are broken

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#20481]
**Godot version:**
96d3776 

**OS/device including version:*
Win10

**Issue description:**
Looks like custom auto-loads(singletons) are broken in the current master. You cannot call functions or use constants from them

**Minimal reproduction project:**
[STBug.zip](https://github.com/godotengine/godot/files/2231915/STBug.zip)

**Comment by akien-mga** [comment]
CC @vnen (likely regression from #20468).

**Comment by Chaosus** [comment]
Looks like its just an error I maked in source and singletons are worked now, sorry for attention and false alarm
