### ISSUE TITLE
Control/Anchor-Ratio not working from the inspector

### ISSUE THREAD

**Issue by Meckie** [godotengine/godot#2048]
The inspector doesn't allow float input, that way the ratio can only be an integer value. That way setting the ratio only works via script.

**Comment by Meckie** [comment]
Changed in control.cpp the bing from INT to REAL and still only accepting int values.

**Comment by reduz** [comment]
ratio anchoring does not work very well, it's there mainly for compatibility, but you can put the control where you want in the editor, change to ratio and it will keep that ratio

**Comment by 29jm** [comment]
I can confirm this is still valid in the current master (380fe0bd529990f06df9dd831055fec979246b9c)

**Comment by reduz** [comment]
Ratio anchoring will go away in 3.0, so it's not going to be changed at this point and left to work as-is.

**Comment by reduz** [comment]
there are better alternatives for behaviors like this such as containers

**Comment by akien-mga** [comment]
@reduz IMO we should either drop the ratio anchoring (or continue supporting it in the engine but hide it in the editor, for compatibility) or fix it. Apparently it just accept int values when ratios should obviously be floats, so maybe just changing that would be enough?

**Comment by akien-mga** [comment]
I've had a quick look and it's indeed not so trivial to fix, as the ``margin/*`` property is rightfully set to only accept integers (for "Begin", "End" and "Center" anchoring modes). It indeeds does not work so well when selecting "Ratio", but we don't want to hide it either if people do use ratio and worked around the inspector limitations.

So I guess it won't be fixed for 2.0, and for 2.1 we can have a look at a better usability improvement.

**Comment by azurvii** [comment]
@reduz why is ratio going away? any discussion happened for the decision? How do you achieve the same/better behavior using containers?

I myself can't think of a simpler solution than changing a field in the editor. imo this is a very useful feature for positioning UI elements. I think pixel-only placement is not great for multi-resolution/dpi screens nowadays.

**Comment by vnen** [comment]
This was fixed by #4102.
