### ISSUE TITLE
Can't use tab to edit vector or transform elements in new inspector

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#20495]
**Godot version:**
Calinou's nightly build 832e2bf

**OS/device including version:**
Windows 10 64bit

**Issue description:**
In Godot 3.0 you could edit each element of a vector or transform in the inspector by pressing tab to go to the next element. This no longer works with the new inspector, it only highlights the next element, but doesn't allow it to be edited.

**Comment by AlexHolly** [comment]
duplicate https://github.com/godotengine/godot/issues/19012
