### ISSUE TITLE
--check-only does not seem to work

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#20503]
**Godot version:**

`3.1.dev.custom_build.e2b7a68`
**OS/device including version:**

`Linux 4.17.4-1-ARCH x86_64 GNU/Linux`

**Issue description:**

I'm trying to use `--check-only` as introduced in #19280, but none of my calls seem to work:

```
[rcorre@desktop-arch godot_3d]$ /home/rcorre/projects/godot/bin/godot.x11.tools.64 --check-only -s Player.gd
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
ERROR: start: Failed loading scene: res://Player.gd
   At: main/main.cpp:1678.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1986.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:422.
[rcorre@desktop-arch godot_3d]$ /home/rcorre/projects/godot/bin/godot.x11.tools.64 -s Player.gd  --check-only
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
ERROR: start: Can't load script 'Player.gd', it does not inherit from a MainLoop type
   At: main/main.cpp:1403.
```

I expected that `--check-only` would not start a full godot GUI (which it did), but would just return 0 if my .gd script was valid, or an error code and message if it is invalid.

I tried this with and without an existing godot instance running.

I also did not expect the behavior to differ based on the order of the flags (which it did, though neither behavior was correct).

**Steps to reproduce:**

1. `godot -s my-script.gd --check-only`

**Minimal reproduction project:**

**Comment by rcorre** [comment]
It seems like, contrary to the `--help` string, `--check-only` is [mutually exclusive](https://github.com/godotengine/godot/pull/19280/files#diff-395c1089ded171b1757742cab9e7297dR1264) with `--script`.

Also, it seems like it will still only work with scripts that inherit `Mainloop`, which is a bit limiting. Is there any way to check arbitrary scripts, at least for correct syntax?

**Comment by akien-mga** [comment]
>> Also, it seems like it will still only work with scripts that inherit Mainloop, which is a bit limiting. Is there any way to check arbitrary scripts, at least for correct syntax?

> Not for now. --check-only just means that the editor will close as soon as it has loaded the script. A proper script validation tool would need to be implemented differently.

Actually yes, with the working `--check-only` option it works on scripts which don't inherit MainLoop, as it's not trying to run them.
