### ISSUE TITLE
Splitting editor tabs

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#2050]
Allow spliting tabs - to view two ( or more ) different scripts, scenes and so on at the same time, both horizontal and vertical. Also multiple times something like in blender.

**Comment by reduz** [comment]
Godot workflow will keep going in the opposite direction. Everything is contextual and appears when it has to appear. 
Viewing several scenes at the same time will also never be implemented, tabs is the limit. Scripts and 3D/2D viewport is planned, though.
