### ISSUE TITLE
SoftBody doesn't render the mesh material

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#20502]
**Godot version:**

tip 03e11c13bfb1649fc9cf9a460249bce5e7f07462
linux

**Issue description:**

![image](https://user-images.githubusercontent.com/4047289/43295397-edb6ed12-9144-11e8-9e05-2ebbd0ed6fdb.png)

**Minimal reproduction project:**

[2018-07-24-softbody-bug.zip](https://github.com/godotengine/godot/files/2233995/2018-07-24-softbody-bug.zip)

CC @AndreaCatania

**Comment by AndreaCatania** [comment]
Can you please confirm that this #20550 fix the problem?

**Comment by capnm** [comment]
Yes the PR #20550 fixes this, thank you!
