### ISSUE TITLE
Cannot orbit like before, and only panning works instead

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20500]
Godot 3 master 03e11c13bfb1649fc9cf9a460249bce5e7f07462
Windows 10 64 bits

Godot used to allow orbitting in 3D using middle mouse button and pan by pressing Shift at the same time. Now it only pans and Shift has no effect.

My navigation scheme is set to `Godot` with default options.
![image](https://user-images.githubusercontent.com/1311555/43290972-bd94e3ae-9127-11e8-9132-1953d256da74.png)

**Comment by homer666** [comment]
I noticed a new option in the viewport menu called Lock View Rotation, which seems to just force MMB to only pan instead of orbit (with Shift having no effect). It sounds pretty similar to what you're describing so maybe give it a toggle if you haven't already...

**Comment by Zylann** [comment]
Ugh, is this for locked views like the 4-viewport mode? That should not be on by default.
