### ISSUE TITLE
GLES2 texture region editor does not move texture along with guide

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#20519]
**Godot version:**

3.1.dev c7dc066dc180149652006e86f07765e5326f324b

**OS/device including version:**

Kubuntu 18.04 / GTX670

**Issue description:**

GLES2 texture region editor does not move texture along with guide
here is demonstration.

![texture_region_gles3](https://user-images.githubusercontent.com/8281454/43330316-c15d09e0-91fd-11e8-8b26-b91517a9aa01.gif)
with GLES3

![texture_region_gles2](https://user-images.githubusercontent.com/8281454/43330321-c3cdcaf2-91fd-11e8-8cf3-0e8ffad22fbd.gif)
with GLES2

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by efornara** [comment]
It looks like a duplicate of https://github.com/godotengine/godot/issues/17429

**Comment by volzhs** [comment]
nice catch. it is.
