### ISSUE TITLE
GDscript CLI checking tool

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#20513]
From #20503:

> Not for now. --check-only just means that the editor will close as soon as it has loaded the script. A proper script validation tool would need to be implemented differently.

I couln't find an existing issue for a "proper script validation tool", so I'm opening this as an official feature request.

Basic features would include:

- [ ] Runnable from the command line on a single script
- [ ] Consistent, machine-readable error format (compatible with e.g. vim's `errorformat`)
- [ ] Produces errors for invalid syntax
- [ ] Uses an existing godot instance rather than launching a new instance

"Nice to have" features include:

- [ ] Usable without _any_ godot instance running
- [ ] Style warnings (e.g. nonstandard indentations)
- [ ] Linting (unused variables, mismatched string format, ect.)

I think `--check-only` currently satisfies the first 3 basic features, so the only thing missing is to not open a new instance of godot to lint every script (I'd like to check syntax automatically on saving a .gd file with [neomake](https://github.com/neomake/neomake)).

**Comment by Zylann** [comment]
If you want to be able to do that in `neomake`, you will need to connect it to the correct Godot instance (you could be running more than one) and communicate via signals or TCP.

**Comment by rcorre** [comment]
@Zylann I'm not sure why that should be necessary. All neomake would need is a CLI tool that takes a script path as input and produces machine-readable errors as output (and neomake is just one example). `--check-only` pretty much does that, but starts a new instance of godot.

Even if TCP communication with godot _is_ required to check scripts, it would make sense to have a CLI in front of that to standardize the interface for editors.

**Comment by Zylann** [comment]
@rcorre you would need such communication if you want to *re-use* an instance.

**Comment by rcorre** [comment]
@Zylann right, but it wouldn't make sense to have neomake do that communication (and have that work repeated in every other linter). I'm saying that `godot --check-only -s myscript.gd` should perform that communication.

Of course, it would be even better if the gdscript parser didn't require the full godot engine to be running. Does gdscript have a grammar specification somewhere?

**Comment by Zylann** [comment]
@rcorre it would make sense because you have to select the instance. People may not be running only one instance of Godot.

**Comment by rcorre** [comment]
@Zylann ah, I see what you're saying. I guess the question is how important it is to actually reuse an instance. Do you actually need the godot engine running to parse a script?

I also haven't looked at the code much but I'm wondering if just not starting the GUI when `--check-only` is passed would be a low-hanging fruit here.

**Comment by vnen** [comment]
There's the `--no-window` option, but currently it works only on Windows.

**Comment by Zylann** [comment]
I was talking about re-use because you wrote this as a 4th point :p

**Comment by xsellier** [comment]
Sorry for the necro bump.
I've been working on a very rough linter for GDscript:
https://github.com/binogure-studio/gdlinter

It is really far from being perfect.

**Comment by rcorre** [comment]
@xsellier  nice! Unfortunately I'm on 3.1, and it looks like your linter supports 2.X only.

**Comment by xsellier** [comment]
@rcorre There is one module, but you'll need to recompile Godot Engine to use it:
https://github.com/hedin-hiervard/gdlint

**Comment by karlpeter35** [comment]
whats wrong with this script 
extends KinematicBody

var speed = 200
var direction = Vector3()

func _ready():
	# Called every time the node is aded to the scene.
	#Initialization here
	pass

func _physics_process(delta):
	direction = Vector3(0, 0, 0)
	if Input. is_action_pressed("ui_right"): 
		direction.x -= 1 #direction = direction - 1
	if Input. is_action_pressed("ui_left"): 
		direction.x += 1 #direction = direction - 1
	if Input. is_action_pressed("ui_up"): 
		direction.z -= 1 #direction = direction - 1
	if Input. is_action_pressed("ui_down"): 
		direction.z += 1 #direction = direction - 1
		direction = direction.normalized()
		direction = direction * speed * delta
		move_and_slide(direction, Vector3(0, 1, 0))

i try to make my player move in 3d but it dont work

**Comment by Calinou** [comment]
@karlpeter35 Please don't post support questions on GitHub issues, use one of the other [community channels](https://godotengine.org/community) instead :slightly_smiling_face:

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by rcorre** [comment]
LSP support made this unnecessary for my use case.

With the TCP patch https://github.com/godotengine/godot/pull/35864 it all works nicely in neovim with https://github.com/dense-analysis/ale.
