### ISSUE TITLE
Add dedicated type/class for Euler rotations

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#20514]
Godot currently returns Euler rotations as `Vector3` objects, apparently just for convenient bundling of three floats. I guess that this has caused confusion, or at least has the potential to do so, as I think it is specifically noted in the documentation that the values are *not* actually a vector, and can't be treated as one in most cases.

Now that Godot is introducing type hints, I think Euler rotations should have a dedicated `EulerRotation` (or `EulerRot`, `EulerAngle3`, etc.) class to avoid further confusion, as well as to prevent passing "the wrong kind of Vector3" to functions.

I also ask for this to be added in 3.1 (or, rather, at the same time as type hints) because if it were to be released in a later patch, people may already have type-hinted Euler values as `Vector3`s and this would be a breaking change for them (albeit somewhat minor).

**Comment by OvermindDL1** [comment]
Quaternions are so much better, don't know why euler angles would be chosen at all as they have some pretty big issues that quaternions just don't have...

**Comment by romlok** [comment]
I agree that Eulers are usually suboptimal, and personally try to avoid using them whenever possible.
However, IME quaternions are generally not taught in school, whereas Euler angles are. I expect most beginner game devs don't have an extensive math background, so will be more comfortable using Eulers, at least at the start.

> EulerRotation would be just an alias to Vector3 though, I don't think it needs its own class, and would operate only on typed GDScript side

That's what I was thinking might do as an initial solution. However, there are a lot of `Vector3` methods which simply don't make sense for non-vectors, so could be a distraction and confusing for those unfamiliar with the hows and whys of Godot's implementation, so I do think a separate class would be beneficial.

> I'm not sure if it should be made forcefully incompatible with Vector3 though, I would be annoyed by that.

Are there situations when it's useful to mix actual vectors and Euler triplets? AFAIK the two are completely distinct and conceptually incompatible?

**Comment by Zylann** [comment]
Thing is, it takes only a day for a beginner to get what euler angles are. Do you want all devs and the engine to support an additional primitive type just because of a knowledge gap? If it goes to core types, that would be to core devs to decide.

**Comment by romlok** [comment]
> Thing is, it takes only a day for a beginner to get what euler angles are. Do you want all devs and the engine to support an additional primitive type just because of a knowledge gap?

It's not a question of understanding Euler angles, it's about not having Vector3s which aren't vectors, and shouldn't be used as Vector3s, but are programmatically indistinguishable from other Vector3s which actually are vectors that can safely be used when something expects a Vector3.
Of course, some things expect a Vector3 which isn't a vector, so you can also have the same problem in reverse, but you'll have to check the documentation to find out which kind of Vector3 you should be passing.

My understanding is that the entire point of having type hints is to prevent accidentally using variables inappropriately. That we have two incompatible uses for a single type is rather a fly in that ointment!

**Comment by Chaosus** [comment]
Pushed to 3.2, as we are entered to feature freezed state

**Comment by aaronfranke** [comment]
When dealing with rotations, you can also use Basis vectors, which are intuitive unlike Quaternions and flexible unlike Euler angles. GDScript already allows you to use Basis vectors via the Basis class.

**Comment by akien-mga** [comment]
We recently introduced the https://github.com/godotengine/godot-proposals repository to discuss such feature proposals. I would suggest to move this proposal there if it's still relevant, following the issue template provided to give all relevant information on use case, etc.
