### ISSUE TITLE
Viewport's render_target_v_flip breaks Labels

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#20522]
**Godot version:**
3.0.5

**OS/device including version:**
Windows 10 64

**Issue description:**
Turning on Viewport's render_target_v_flip on, and moving Control's into it with Labels that have autowrap or clipping on makes the text not display in texture rendered from such viewport. Turning render_target_v_flip off and not touching anything else makes the text display correctly.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch? If so, could you upload a project that reproduces it?

**Comment by tom-jk** [comment]
Testing with project: [20522_2.zip](https://github.com/godotengine/godot/files/4967277/20522_2.zip)
3 Labels (left) have been duplicated into the viewport and shown with a TextureRect (right).

Can reproduce in 3.0.5.stable.official.6a88e22
![Godot20522_Screen_305](https://user-images.githubusercontent.com/64640811/88309173-e04e9b80-cd05-11ea-9d48-ebdd95841e39.png)

Can't reproduce in 3.1.alpha.official, 3.2.2.stable
![Godot20522_Screen_322](https://user-images.githubusercontent.com/64640811/88309189-e3498c00-cd05-11ea-8ef1-c2cbc8005541.png)

**Comment by akien-mga** [comment]
Thanks for testing!
