### ISSUE TITLE
Inspector's property edit types right to left

### ISSUE THREAD

**Issue by maksloboda** [godotengine/godot#20526]
**Godot version:** 25f1833890a643e07d31f5160917c46ec5665e9e

**OS/device including version:** Ubuntu 18.04

**Issue description:**
Property edits for resources type right to left  

**Steps to reproduce:**
1. Create a button
2. Create shortcut for it
3. Create InputEventAction for the shortcut
4. Type the name of the action
It appears to type right to left, but it teleports the cursor to the beginning every time something is typed.
(It works fine if you click "Edit" on the InputEvent)

**Minimal reproduction project:**
[InspectorBug.zip](https://github.com/godotengine/godot/files/2236936/InspectorBug.zip)
(Just select the button and do step 4)

**Comment by DualMatrix** [comment]
This bug seems to be no longer present in master, probably fixed by #21159
