### ISSUE TITLE
Disabled popup buttons can be pressed if active ones are also present

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#20525]
**Godot version:**
92c5938

**Issue description:**
This will explain better:
![peek 2018-07-27 15-56](https://user-images.githubusercontent.com/30739239/43341397-bc8ddee6-91b5-11e8-9c11-444cfd805474.gif)

**Comment by reduz** [comment]
@akien-mga sounds like a side effect of the menu button code added recently

**Comment by YeldhamDev** [comment]
@reduz It's fixed in the referenced pull request above.
