### ISSUE TITLE
class inside a class cyclic error

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#20533]
Just updated to the latest on the master branch today to get the latest gdscript fixes and I am getting this new error with this bit of gdscript:

    class SharePortfolio:
	    var nothing;
	
	    class Cheese:
		    var nothing;

'class Cheese' is where the debugger says the problematic line is and say:
**Parser Error: Cyclic class reference for 'SharePortfolio'**

**Comment by akien-mga** [comment]
CC @vnen
