### ISSUE TITLE
Tree.create_item uses Object as return and parameter type instead of TreeItem

### ISSUE THREAD

**Issue by PJB3005** [godotengine/godot#20538]
This is really weird. Everything uses `TreeItem`, *including* `create_item`, but there's a special version `_create_item` handling around `Object` and casting and it's only used in the ClassDB registration.

**Comment by KoBeWi** [comment]
Related to #21160 and partially fixed by #21705 (the parameter is still object).

**Comment by akien-mga** [comment]
Let's review this for 3.2 and see if the parameter could be `TreeItem` too, or if it's as good as it can be.

**Comment by akien-mga** [comment]
> Let's review this for 3.2 and see if the parameter could be `TreeItem` too, or if it's as good as it can be.

So this is a limitation of the binding system which can't take any pointer. The only supported object pointers are `Object *`, `Node *` and `Control *`:
https://github.com/godotengine/godot/blob/30701e3966fe0869868d09d57249ff140e55849e/core/variant/variant.h#L341-L343

This could possibly be improved, but likely needs discussion in a dedicated proposal. For this issue specifically, we could change the type to `Control *` at least, and clarify in the documentation that the Controls are expected to be TreeItems.
