### ISSUE TITLE
[Regression] Numeric exported properties read incorrect values in C#

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#20531]
**Godot version:**
`master` / aecc3a444

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
After updating the engine to the latest revision, all exported numeric properties (including enums) started reporting incorrect values to the attached C# code. For example, if I set a `float` type property to `0.5` in the editor, it reads ` -1.221263E+32` at runtime.

And deleting `.mono` directories and rebuilding assemblies don't seem to affect the issue.

As I update the engine on a weekly basis, it seems that there were some changes in the marshalling code introduced during the past week.

If I'm not the only one that have this problem, I think this issue better be fixed before 3.1 and hopefully get higher priority, since it'd make the engine virtually unusable to all C# users.

**Comment by neikeq** [comment]
I cannot reproduce on aecc3a4. Can you share an example project?

**Comment by mysticfall** [comment]
I've already reverted back to the old version to work on my project again, but I'll try it again before the weekend ends and see if I can make an example project, or at least make a branch of my current project that can be tested with the latest revision.

**Comment by mysticfall** [comment]
I was able to create a minimal test case by deleting everything irrelevant from my project.

It includes a single source file with one `float` type property, which is initialized with `1` from the associated scene file.

It should print the property value when you run the project, but it shows such random output:
```
### Float value = -1.256955E+16
```

Please let me know if you need further information. Thanks!

[issue-20531.tar.gz](https://github.com/godotengine/godot/files/2238623/issue-20531.tar.gz)

**Comment by mysticfall** [comment]
Just did a bisect and found out ee3c476c9a8a was the first commit that introduced the issue.

**Comment by mysticfall** [comment]
It seems that this particular change has caused the problem:
* https://github.com/godotengine/godot/commit/ee3c476c9a8a3be949252468570e75f35fea2697#diff-ef655c61e03da3e7215029fdb5923e8dL142

If I revert the content of that function to its previous status, the problem goes away. And as it only deals with properties, fields don't seem to be show such a symptom with or without the change.

**Comment by neikeq** [comment]
I see now why I wasn't unable to reproduce it. You had to run the game.
The reason the change broke things is because the method that takes `void**` for parameters expects unboxed values for value types. I will revert for now.
Thanks for debugging it :)

**Comment by mysticfall** [comment]
Thanks! Now I can happily enjoy the latest features again. :)
