### ISSUE TITLE
LineEdit string to float doesn't read decimals on MacOS exported projects

### ISSUE THREAD

**Issue by iRadEntertainment** [godotengine/godot#20540]
**Godot version:**
Godot 3.0.4

**OS/device including version:**
-Windows 7
-project exported with standard template to Mac OSX

**Issue description:**
LineEdit_node.text return a string which I would convert to float.
Converting it to float works fine when exported for Windows.
On macos Sierra instead the string to float conversion got stucked on the decimal point and return a float number with only the integer part of it

**Steps to reproduce:**
Create a scene with a LineEdit node in it (editable) in Windows release.
Connect the signal `("text_entered")` to a `print ( float (LineEdit.text) )`
Export the project on debug mode for Mac OSX using standard templates.
Insert a decimal number in the LineEdit node, press Enter and read the output in the console when running o a macos Sierra OS.
--The output doesn't include decimal parts.--

**Notes:**
I'm using an Italian keyboard.
My best guess is that the encoding for the "dot" key on macos Sierra could be different from the Windows OS systems

**Comment by iRadEntertainment** [comment]
With a dot

**Comment by Calinou** [comment]
@iRadEntertainment Can you still reproduce this issue in Godot 3.1.1 or with a [daily build](https://hugo.pro/projects/godot-builds/)?

Also, can you paste the dot character in question here? We could then determine if it's a standard ASCII dot character or a special Unicode character.

**Comment by iRadEntertainment** [comment]
Cannot reproduce anymore on the same machine I got the issue with the same build.
I have no idea really, I cannot reproduce on any other MacOS. I would say it is solved.
