### ISSUE TITLE
Tree node should have a delete_item() function

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#20547]
As it stands currently, the Tree node doesn't have a way to delete TreeItems. Using free() on a TreeItem doesn't cause any issues with the respective Tree node, besides that Tree.get_selected() isn't updated, plus it's just... odd having to use free(). I haven't tested if it causes any issues with the parent TreeItem, though.

**Comment by AlexHolly** [comment]
I encountered the same issues you have with "Tree". Would be nice to know if this is by design or just missing. As a workaround I simply recreate the Tree(maybe this works for you too).
