### ISSUE TITLE
Tree node should have select()/deselect() functions

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#20548]
I feel like this one is self-explanatory. My reasoning for this is that using TreeItem.selected doesn't update the Tree's get_selected() result, which turned into me having to make my own selected_item variable just so I could make it `null` whenever I don't have an item selected.

On that note, it would also be useful to allow deselecting all TreeItems whenever whitespace is clicked. It's not that hard to deselect all in GDscript, but I feel it'd be welcome as an option.

**Comment by AlexHolly** [comment]
get_select() is not updated in `Tree.SELECT_MULTI` mode.

https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L3077
`selected_item = p_item;`

**Comment by LikeLakers2** [comment]
@AlexHolly Did you mean to make a new issue? This is a feature proposal, not a bug report; I don't think bugs should be reported on a feature proposal.

**Comment by AlexHolly** [comment]
> I feel like this one is self-explanatory. My reasoning for this is that using TreeItem.selected doesn't update the Tree's get_selected() result, which turned into me having to make my own..

Do you think it should be updated? I would make a PR and fix both.

**Comment by LikeLakers2** [comment]
@AlexHolly If you'd like to try, go for it. Also, I see your reasoning now for the bug report being here -- my bad!

**Comment by Eoin-ONeill-Yokai** [comment]
Is there something I'm missing here?

I have a situation where my Tree might need to be reconstructed. In that situation, I would like to be able to modify the selected item, but that seems to be impossible to do via GDScript. So is there no way at all to change the visually selected item through GDScript alone?

**Comment by radlotus** [comment]
Yeah. It seems to be impossible to select a TreeItem via GDScript. Why is that? Is it because the Editor doesn't use such feature? It would be very convenient actually.

**Comment by marzecdawid** [comment]
@radlotus It look like methods `TreeItem:Select()` and `TreeItem:Deselect()` are exposed in GDScript for many years:
https://docs.godotengine.org/en/stable/classes/class_treeitem.html#class-treeitem-method-select

Can you clarify if this is the functionality you were looking for?

**Comment by egiezen** [comment]
The method Tree.deselect_all() doesn't deselect the root TreeItem (Godot 4 Beta 12).
