### ISSUE TITLE
A function to clear particle‘s emission mask

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#20543]
**Godot version:**
master

**Issue description:**
can't find a function or a way to clear particle‘s emission mask,

**Comment by KoBeWi** [comment]
There's a property in ParticlesMaterial called `emission_point_texture`. Setting it to null is pretty much clearing the emission mask, isn't it?

**Comment by KoBeWi** [comment]
Closing as per above comment (and no reply).
