### ISSUE TITLE
GDNative error on Godot official builds only

### ISSUE THREAD

**Issue by Superwaitsum** [godotengine/godot#20559]
**Godot version:**

Godot 3.0.3RC3 - Godot 3.0.5 (Only Official releases)

**OS/device including version:**

Windows 8.1 64 Bits

**Issue description:**

There seems to be a bug with official releases only, which affects gdnative only on windows builds.

Initially tought it was a bug of my plugin, but it works well with godot 3.0 - 3.0.3 RC2
Also works well with builds from master (tested with hugo.pro builds and self compiled)
Also compiled 3.0 and master branches using 
`scons p=windows tools=yes target=release_debug use_static_cpp=yes use_lto=yes debug_symbols=no`
in a try to reproduce official builds, but my asset still works perfectly with those flags.

Asset works perfectly on Godot 3.0.5 on Lubuntu 18.04 64bits, so it's windows only.

**Steps to reproduce:**

1. Run my Serial Asset
2. Click the refresh button (the **R** near bottom center)
3. Select a port (there is usually an active port, so list should not be empty)
4. Select a baudrate in the list at the right (Any baudrate will work)

5. Under normal circunstances, the console should throw a message saying it couldn't open port. (Expected Result)
6. On the official releases Godot will Crash.

**Minimal reproduction project:**

https://github.com/Superwaitsum/GDSerialAsset

**Comment by akien-mga** [comment]
That hints at a regression related to buildsystem changes in 3.0.3 RC3 (mingw instead of msvc maybe?). CC @hpvb.

**Comment by hpvb** [comment]
The windows versions of the shipped DLLs require microsoft visual studio to be installed. It may be worth doing a 'release' build of the library and seeing the issue persists. Since all of this is C code I do not think that this has anything to do with compiler mismatches. Also it seems to work on Windows 7 and 10. :-/

**Comment by hpvb** [comment]
(I said this before, but I'm going to get myself an 8.1 license so I can test releases there, I can currently only test on Windows 7 and 10 and it seems that this is not sufficient)

**Comment by Superwaitsum** [comment]
Interesting, I didn't think 8.1 would be the problem. Then I just have to wait patiently for hpvb's solution, thanks.

**Comment by hpvb** [comment]
@Superwaitsum you could help maybe by providing a GDB coredump of Godot as it crashed in your setup? That'd be very helpful. I could also send you a binary with debug symbols then you could just send me a backtrace initially.

**Comment by Superwaitsum** [comment]
@hpvb maybe it's no needed anymore, just tested 3.0.6 and it is working fine!, did you make any changes to the build system?

**Comment by Superwaitsum** [comment]
Changelog shows mono minGW fixes, maybe that also fixed this?

Just for historical purposes, here is a screenshot of cdb in 3.0.5
![godot-stable](https://user-images.githubusercontent.com/22568812/43370030-7557d304-933d-11e8-93f4-d6465d1550b8.png)

**Comment by hpvb** [comment]
@Superwaitsum are you using the mono binaries to test or the regular binaries? (I myself did only test with 3.0.6, I should probably have specified that)

**Comment by hpvb** [comment]
hmm, I did change how inlining works on tool builds, it's the same between tool and non-tool builds. This could actually explain this. I'll check if that's the reason.

**Comment by Superwaitsum** [comment]
@hpvb All the tests were done with regular version.

**Comment by Superwaitsum** [comment]
Thanks!
