### ISSUE TITLE
Parameter hint doesn't show if accepting the autocomplete and only shows default value of first parameter.

### ISSUE THREAD

**Issue by rnoriega31** [godotengine/godot#20555]
**Godot version:**

3.0.5 stable.

**OS version:**
macOS High Sierra v10.13.4

**Issue description:**

If I have a function `test_function(value1 = 0, value2 = 3)`, when I start typing the name of the function, if I press enter on the autocomplete offer, the editor doesn't display the parameter hints, you have to delete the `(` and re-write it for the parameter hint to show. Additionally, if the function has multiple parameters with default values, the hint will only display the default value of the first parameter and not for the rest.

Not the end of the world, but I have to assume this isn't the intended behavior.

**Comment by KoBeWi** [comment]
Fixed since 3.1
