### ISSUE TITLE
Allow android export version code to be greater than 4096

### ISSUE THREAD

**Issue by AKashyap86** [godotengine/godot#20553]
8192 or 16384 would be good I think. I do not know how many us actually require these many version codes , but I do, at least in my first project. Later on someone like me might set up things more differently, but maybe still more codes might be needed on bigger projects.. Earlier, n 2.1 and maybe even in 3.0 it used to be more but maybe too much . but 4096 is too little I think, especially with so many new technologies coming to the market and so many experiments to do.

Steps to reproduce:
Export an android project and under Version, there will be code. Slide the slider all the way forward, and it will go to a max value of 4096 only.

**Comment by vnen** [comment]
Pretty sure I've already seen an issue about this, but can't find right now. Might even be already fixed in master.

**Comment by aBARICHELLO** [comment]
![image](https://user-images.githubusercontent.com/16687318/43361016-b183ea6e-929a-11e8-8f9d-d225bdc13f0c.png)
Just reproduced the steps in version 3.0.5 and the version number can be greater than 4096.

**Comment by AKashyap86** [comment]
oh . sorry about it . my first few issues on github .. I was testing master :(

**Comment by akien-mga** [comment]
There's indeed an issue on master, the max is 4096 but defined with `or_greater`, so it should be possible to manually input a greater value. But it doesn't seem to work. https://github.com/godotengine/godot/blob/master/platform/android/export/export.cpp#L1095

**Comment by AKashyap86** [comment]
yes it doesn't work . unless in export.cpp the export max value 4096 is changed to some other higher number . that's what i have been doing the past few weeks . someone gave me the suggestion on IRC

**Comment by akien-mga** [comment]
I just tested again and it seems to work now in the master branch.
