### ISSUE TITLE
Autocomplete list doesn't appear in code editor

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#20565]
_Version 3.0.6 stable (was also in 3.0.5 too)_
Strange behavior of autocomplete feature in code editor.

1. New script, in "_ready" I write "var pos = Vector2()"
2. In next line I type "pos." and expected to see a list of methods/variables, but list is not appear
3. If I do two empty lines and then write "pos." - list appears

GIF:
![bug](https://user-images.githubusercontent.com/1552169/43365885-61862e62-933c-11e8-858e-ea2a6719f350.gif)

**Comment by vnen** [comment]
This has been a problem for quite some time (isn't there any other issue about this?). In any case, I refactored the GDScript completion so this is no longer a problem in master.

**Comment by akien-mga** [comment]
Fixed in the master branch.
