### ISSUE TITLE
Unable to open HDR Image `ERR_CANT_OPEN`

### ISSUE THREAD

**Issue by Supatier** [godotengine/godot#20564]
**Godot version:**
b62586c

**OS/device including version:**
Linux mint 18

**Issue description:**
Opening HDR image gives me ` Failed loading resource: res://Assets/Images/untitled.hdr
 editor/editor_node.cpp:578 - Condition ' !res.is_valid() ' is true. returned: ERR_CANT_OPEN`

When reimporting it gives me ` modules/hdr/image_loader_hdr.cpp:42 - Condition ' header != "#?RADIANCE" && header != "#?RGBE" ' is true. returned: ERR_FILE_UNRECOGNIZED
 editor/editor_file_system.cpp:1529 - Error importing: res://Assets/Images/untitled.hdr`

The HDR image isn't corrupt and I can open it with Luminance HDR
![screenshot from 2018-07-29 17-47-46](https://user-images.githubusercontent.com/19777767/43365464-88acc3be-9357-11e8-91ed-af41027e0a58.png)

**Steps to reproduce:**
Add a hdr image to your project 

**Minimal reproduction project
[hdr](https://www.dropbox.com/s/phkyyb1nwrpbppn/untitled.hdr.zip?dl=1)

**Comment by goodyttoor** [comment]
There is 0 follow in the return string from this line ("#?RADIANCE0" or #?RGBE0").

https://github.com/godotengine/godot/blob/3f01f40e91c962b68fd18c0ca00144dfb6aee65f/modules/hdr/image_loader_hdr.cpp#L40

So it fails the condition check. Not sure why.

**Comment by Supatier** [comment]
@goodyttoor Removing that line worked. Thanks.

```
wget https://github.com/goodyttoor/godot/commit/7fbb8264224c3194436e53df7f43d6b166200201.patch
git apply 7fbb8264224c3194436e53df7f43d6b166200201.patch
```
