### ISSUE TITLE
Grid lines overlaping

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#20563]
Tested on Godot 3.1 dev

#20246 fixed grid lines at origin not being drawn when origin lines are disabled, but now grid lines and origin lines draw over each other, producing flickering or z-fighting.

**Comment by aaronfranke** [comment]
Confirmed on my system. Video of the problem: https://www.youtube.com/watch?v=w76BZ3GslR0

Regression caused by #20328 PR and #20246 issue. CC @ordigdug @akien-mga @Zephilinox

**Comment by ordigdug** [comment]
I'm working on this.
