### ISSUE TITLE
Nonexistent signal: changed when saving/instancing StaticBody2D

### ISSUE THREAD

**Issue by Araken** [godotengine/godot#20574]
**Godot version:**
Master, 07129deaeb767528e550344e1134f2739c89bdd0

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Godot prints "Nonexistent signal: changed" each time a scene with StaticBody2D is saved in editor or instanced in game.

**Steps to reproduce:**
Create a new scene, add StaticBody2D, save the scene.

**Comment by Ace-Dragon** [comment]
This happens a lot with games using the 3D nodes as well. The same prints also occur with nearly all of the Godot demo projects.

**Comment by mysticfall** [comment]
This looks to be a duplicate of #20521.

**Comment by akien-mga** [comment]
Assuming fixed by #20381.
