### ISSUE TITLE
Tween leaks memory

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#20580]
Windows 10 + Godot 3.0.2

**Issue:**
Calling `interpolate_method` (and possibly others, untested), continually increases static memory usage.

**Minimal code:**
```
var tween
func _ready():
  tween = Tween.new()
  add_child(tween)

func temp(value): return

func _input(event):
  if event is InputEventKey and event.pressed:
    for i in range(50):
      tween.interpolate_method(self, "temp", 0, 1, 1, Tween.TRANS_EXPO, Tween.EASE_OUT)
```
**Reproduction:**
Run code, press keys, view the Memory/Static field under Monitors tab increase.

**Motivation:**
My games are 95% tween based, the memory gets eaten up quick because of this.

**Comment by vnen** [comment]
Seems the same as #19297

**Comment by vnen** [comment]
Closing as duplicate.

**Comment by gotnospirit** [comment]
Hi,
You did forget to start the tween (after the for loop?) but the leak was real.
I will send a PR for #19297.
Minimal code was really helpful to test the fix, thanks!

**Comment by rilpires** [comment]
Is it intended to have to call `tween.remove(obj,key)` for a tween when we want to restart a tween on a property? I was calling stop() and calling a new interpolate_property() on the same property, and the memory was building up. 

When calling "interpolate_property" for a certain property it probably should automatically remove an existing one, shouldn't it?
