### ISSUE TITLE
move_and_slide - slope collision issue

### ISSUE THREAD

**Issue by piratesephiroth** [godotengine/godot#20593]
**Godot version:**
3.0.x

**OS/device including version:**
All

**Issue description:**
move_and_slide does not work properly on 2D platformers with slanted terrain.
If the player character colides with a slope fast enough it will bounce/slide a little. This interferes with horizontal movement and it of course is not the expected behaviour in most situations.

This also happens in some cases when landing/jumping on slopes,

![Imgur](https://i.imgur.com/L91yoZJ.gif)

I know it's just the player being ejected out of the solid ceiling according to the surface's normal but it doesn't feel natural. move_and_slide can detect floor, ceiling and walls so it should also be able to use predetermined directions for the ejection instead of the ones calculated according to the colliding surface's' normal.

So, regardless of the surface angle:
* Ceilings should always eject the player downwards (no effect on x speed);
* Floors should always eject the player upwards (no effect on x speed);
* Walls should always eject the player sideways (no effect on y speed);

**Steps to reproduce:**
Use move_and_slide to collide with a slope in a 2D platformer.

**Minimal reproduction project:**
The issue is quite self-explanatory so a project isn't really necesssary but here's the platformer scene from the [kinematic2D page](http://docs.godotengine.org/en/3.0/tutorials/physics/using_kinematic_body_2d.html) on the documentation.
[using_kinematic2d.zip](https://github.com/godotengine/godot/files/2239694/using_kinematic2d.zip)

**Comment by eon-s** [comment]
I think is caused by the default safe margin, separation is big and pushes the body in an angle making the effect of a sliding, reduce the margin to 0.001 and try again.

**Comment by reduz** [comment]
This is not a bug, and it really depends on the game and control. There is not an universal way to do this, though I see the following could be improved:

1. Could set a threshold for sliding against the ceiling
2. You can easily implement your own motion logic using move_and_collide instead of move_and_slide, but there are not good enough examples about this.

Godot 3.1 also will add a few more tools to make all this easier and straightforward, so I will leave this open as enhancement and documentation tags.

**Comment by piratesephiroth** [comment]
>I think is caused by the default safe margin, separation is big and pushes the body in an angle making the effect of a sliding, reduce the margin to 0.001 and try again.

A smaller safe margin will only reduce the effect. Also safe margins that low might cause issues with the sliding on slopes.



    >Could set a threshold for sliding against the ceiling
Threshold? I don't really see how to do that.
   >You can easily implement your own motion logic using move_and_collide instead of move_and_slide, but there are not good enough examples about this.

Yeah, for the ceiling collision I just added a test with move_and_collide whenever the player isn't on the floor and Y speed is positive. If it would collide with a slanted ceiling then the Y speed is immediatly zeroed.
I know I can do everything with move_and_collide however I prefer to use move_and_slide because not only it's simpler but also most the calculations are performed internally instead of being interpreted by scripting engine so it should also be a little faster.

**Comment by piratesephiroth** [comment]
Well, a single ray shape works fine however it's not enough for a decent collision check
Adding more rays only results in weird behaviour and this error

Condition ' p_normal.is_normalized() == false ' is true. returned: Vector2() in C Source: core\math
math_2d.cpp:173 C Function: Vector2::slide

It's still experimental so that was sort of expected, heh

**Comment by eon-s** [comment]
I'm a bit confused, the issue is about slide or collide?

**Comment by piratesephiroth** [comment]
>I'm a bit confused, the issue is about slide or collide?

it's about move_and_slide. I opened this issue right before I went to bed so I only caught the mistake in the title on the next day, heh

**Comment by piratesephiroth** [comment]
solved by #50495
