### ISSUE TITLE
Optimizer doesn't handle Shape Keys (Morph Targets)

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#2059]
![image](https://cloud.githubusercontent.com/assets/1546044/8066240/5a623348-0e9b-11e5-82ce-90982fe83206.png)

@reduz

**Comment by akien-mga** [comment]
Could you be a bit more specific about what the issue is? I know a picture is worth a thousand words, but it's not enough for me to understand the bug (though I'm not a Godot expert, so I might be missing something easy to grasp when one knows the corresponding features well).

**Comment by reduz** [comment]
Can you guys make a simple example .dae scene for me to test out? I don't have anything handy currently

**Comment by akien-mga** [comment]
Ping.

**Comment by LeonardMeagher2** [comment]
Hey guys, sorry, this was such a long while ago, and I think I was just posting the image for reduz to look at based on a conversation we had, obviously I should have put some text into it

What I think is going on, is the every step is a keyframe for shape keys, but it'd be nice if there were only key frames for the changes, since all of those shape keys (based on my flow) were the exact same value id have to go and manually delete all of them, and rekey them all
@akien-mga

**Comment by bojidar-bg** [comment]
Pretty ping :smiley:
