### ISSUE TITLE
Broken light in 3D

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#20599]
**Godot version:**
Godot 3.1.dev.calinou.15db793 (GLES2 / GLES3)

**OS/device including version:**
OS: Win 8.1, Win 10, Debian 9.4
GPU: AMD Radeon HD 7610M (latest driver)

**Issue description:**
Broken light in 3D.

**Steps to reproduce:**
GLES2
![2](https://user-images.githubusercontent.com/5556081/43393040-5a4f36ee-93fe-11e8-920e-861d93ee5963.gif)
GLES3

![ezgif com-optimize](https://user-images.githubusercontent.com/5556081/43393372-7cc0c57a-93ff-11e8-8851-9ce7ecbd336e.gif)

**Minimal reproduction project:**
![image](https://user-images.githubusercontent.com/5556081/43393184-dd8db8b4-93fe-11e8-8f1c-2b0fbb28cd41.png)
[Download minimal project](https://github.com/godotengine/godot/files/2240822/bl.zip)

**Comment by Ace-Dragon** [comment]
3D lighting works for me on an Nvidia GTX 1060 6GB card.

Maybe try rolling back your drivers? This could be an issue specific to AMD Radeon.

**Comment by Timofffee** [comment]
Light does not work since Godot 3.0 alpha. During this time, I have repeatedly reinstalled the OS and drivers, trying to find the problem.

**Comment by Zireael07** [comment]
If it doesn't work since Godot 3.0 alpha, then it must be something on your end.

**Comment by NewNodeGames** [comment]
Try to activate normal map on meshes material and/or decrease roughness parameter. This is not a final solution but you can get better results.
