### ISSUE TITLE
2D scene view screen range doesn't adapt everytime

### ISSUE THREAD

**Issue by maxime4000** [godotengine/godot#20591]
**Godot version: 3.0.2 -> 3.0.6**

**OS/device including version: Windows 10 Éducation**

**Issue description:**
Hello, I'm no real game dev, maybe I'm doing it wrong on my side, but I've been working on a 2D game for 3 months for a university project and I came to the part where I'm testing free roam in a 2D world. Right now my Environnement is something I create on my own and probably not the best way to make it, but for what I have done, I think it does the job. 
Today I try to use my main Tiles which I was using for testing to make a bigger world. So i duplicate it 3 times. for a 2x2 world. 
Got this zoom out the most I can (not full screen). (92160, 51200)
![image](https://user-images.githubusercontent.com/4070713/43374001-691d9158-937b-11e8-9133-6383ec4f39b2.png)
But if i zoom to the farthest point I can go I can't get the distance write when zoom out. 
Lowest point (-5120, -5120) : 
![image](https://user-images.githubusercontent.com/4070713/43374099-e86117fa-937b-11e8-9b00-39389c8fe65c.png)
Highest Point (8733, 8132):  
![image](https://user-images.githubusercontent.com/4070713/43374138-2376ffc6-937c-11e8-91fb-87067304b5b5.png)

From what I understand if you zoom out you can go to near (-5120, -5120) to over (92160, 51200) but if you try to nitpick thing, you can't go farther than those point (-5100,-4506) to (8733, 8132). It change when you add things but in my case, it didn't change when it should have change. 
This is a big restriction because I'm able to drag thing out of my reach and after I'm not able to do anything precise because I need to zoom out to reach it or the scene viewer doesn't allow me to move to this location. The problem I see with that is I can move my character in game to the fartest position possible in negative or positive axe but the scene editor doesnt allow me to go beyond those position... So I could allow my character get out of map where me as a game dev, can go there? That make no logical sense...

**Steps to reproduce:**
Just try to zoom in at the fartest position. You can't go where you want. Suggestion, allowing the Dev, who know what he/she does, to go anywhere he/she want in a scene even if that's completely stupid.... Requested features, adding a way to enter coordinate and it teleport the view at those coordinate.

So I try something like moving my KinematicBody2D to higher point and it seem it work and i can now see farther than where I could before. but put it back to pos (0,0) and I wasn't able to go back to this point...

Here is what make me realize the bug : Was on godot 3.0.2 when doing this. I tought updating would fix it but it didn't help.
Create a Node2D Environment with sprite background, staticBody, imported scene.
Create a new Node2D call Tile0-0 in the Node2D Environment
Took every object in Environment and place it in Tile0-0
Duplicate Tile0-0 3 times to get Tile0-1, 1-0, 1-1
Try to edit every Tile because I didn't want to be all the same,
When i try to edit Tile1-1, I couldn't... The editor didn't allow me to zoom at this point...

Download Godot 3.0.6
Try again doesnt allow me either...

Try moving a tile (Tile1-1) and that allow me to go further but still not at the maximum of what I want for. Example, there is more content after those position, but the editor doesnt allow me to go there...
![image](https://user-images.githubusercontent.com/4070713/43375885-b087ecaa-9385-11e8-87f7-a91ecb92be79.png)

Scene structure Image :
![image](https://user-images.githubusercontent.com/4070713/43375447-1e3439e6-9383-11e8-8eb2-0fb7ef7c1e7f.png)

Background picture is 1800x1800px with scale (4,4) and i add object on this after, mostly scale (3,3). I mostly use low res free image for placeholding, that's why they all scale that much. Maybe that can be related (that's why I'm telling that). I'm not a 2D artist and I'm alone, so i just found image on internet for my school project that will never be release.

**Minimal reproduction project:**
I will wait answer and if I can help, I will try my best to give useful content.

[Test.zip](https://github.com/godotengine/godot/files/2239629/Test.zip)

**Comment by Calinou** [comment]
Godot 3.2 onwards allows you to unconstrain the editor bounds in the Editor Settings, which should resolve this issue:

![image](https://user-images.githubusercontent.com/180032/83979895-f0efb180-a911-11ea-8a71-fc4c0272944c.png)
