### ISSUE TITLE
Mono: Can't build master w/ latest compilation changes

### ISSUE THREAD

**Issue by exts** [godotengine/godot#20598]
**Godot version:**
Master

**OS/device including version:**
Windows 10 64bit

**Issue description:**
This https://github.com/godotengine/godot/commit/0deb8dda517aee11280bcaf12d96456d5a404ad3 is breaking mono building for me.

Error:
```
d:\godot-devel\build\godot\modules\mono\mono_gd\../utils/thread_local.h(79): error C2059: syntax error: '*'
d:\godot-devel\build\godot\modules\mono\mono_gd\../utils/thread_local.h(79): error C2091: function returns function
[Initial build] Compiling ==> modules\mono\godotsharp_dirs.cpp
godotsharp_dirs.cpp
[Initial build] Compiling ==> modules\mono\mono_gc_handle.cpp
mono_gc_handle.cpp
d:\godot-devel\build\godot\modules\mono\mono_gd\../utils/thread_local.h(79): error C2059: syntax error: '*'
d:\godot-devel\build\godot\modules\mono\mono_gd\../utils/thread_local.h(79): error C2091: function returns function
scons: *** [modules\mono\mono_gc_handle.windows.tools.64.obj] Error 2
scons: *** [modules\mono\csharp_script.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

**Steps to reproduce:**
1. Open x64 Native Tools Command Prompt for VS 2017
2. Run `scons p=windows tools=yes module_mono_enabled=yes mono_glue=no -j3`
3. Wait for error

**Comment by exts** [comment]
(cc: @neikeq @hpvb)

**Comment by neikeq** [comment]
I think msvc requires `__stdcall` to be placed like this:

``` diff
-void __stdcall (*p_destr_callback)(void *)
+void (__stdcall *p_destr_callback)(void *)
```

@hpvb does that work with mingw as well?

**Comment by hpvb** [comment]
@neikeq yeah that should be fine for MingW also. Sorry about that, feel free to change it.
