### ISSUE TITLE
Tween speed

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#2060]
I'm using Tween quite offen in my work. But to be honest, I'm not quite sure what does the "set_speed" really stands for - which is crusial. Ok - it makes it faster or slower but I cant find what is the unit here. Wouldn't it be better to change the approach here and swap it with something like "set_tween_time/lengh" or "set_duration" in seconds/miliseconds ? It would be much more intuitive and self documentating.

**Comment by bojidar-bg** [comment]
I personally think that speed is a multiplier, BTW.

**Comment by akien-mga** [comment]
It seems to be a scale: https://github.com/godotengine/godot/blob/199a29b353748245e9589d3ef38877613eef0ede/scene/animation/tween.cpp#L697-L700

It should probably be renamed to set_speed_scale/get_speed_scale, or at the very least the argument should be documented as ```speed_scale``` and not ```speed```.

**Comment by aroncds** [comment]
Hello guys!

I made a compilation with set_duration using milliseconds, making all the animation run during that time, but then I made it take priority over speed_scale, or you use speed_scale or duration.

What do you think?

Sorry, bad English!

**Comment by akien-mga** [comment]
@aroncds Sorry, I'm not sure to understand your question. If you are asking about whether to use speed_scale or duration, I guess this would be a good quesiton to ask on the Godot Q&A: https://godotengine.org/qa/

As for the original issue here, it was fixed by 00ec16e for Godot 3.0.
