### ISSUE TITLE
Fullscreen game can't start on second monitor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20618]
**Godot version:**
3.0/3.1-dev

**OS/device including version:**
Windows 10 x64 NVidia GPU

**Issue description:**
When you set project to fullscreen and in editor settings set screen in window placement to monitor 2, it will still appear on monitor 1 and you need to move it yourself. If the game isn't fullscreen, it will correctly start on second monitor. Happens also with default placement and editor on monitor 2.

**Comment by Calinou** [comment]
I'll close this in favor of #21746, which is more detailed :slightly_smiling_face:
