### ISSUE TITLE
Texture size isn't correctly updated on sprite displayed in editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20614]
**Godot version:**
3.0/3.1-dev

**Issue description:**
When you change image size and a scene with Sprite using this image is being displayed, Godot reimports the texture and refreshes the sprite, but doesn't update the size until you refresh view.

**Steps to reproduce:**

1. Create Sprite node
2. Assign any texture (even icon.png on empty project)
![image](https://user-images.githubusercontent.com/2223172/43423612-2b80a31c-944d-11e8-86bd-8029299064f3.png)
3. Edit texture and change size
4. Re-focus Godot to reload texture
5. The texture appears glitched
![image](https://user-images.githubusercontent.com/2223172/43423638-3ba525a6-944d-11e8-979c-8007c276831b.png)
6. Everything is fixed when you refresh scene (e.g. change scene tab)
![image](https://user-images.githubusercontent.com/2223172/43423697-5e40441a-944d-11e8-951d-bd0b68fdbdc4.png)

**Comment by akien-mga** [comment]
CC @groud

**Comment by avencherus** [comment]
Confirmed this in **Win10 64-bit alpha 3.1 aad70d5**

Texture doesn't refresh itself until moved or sometimes the scene has to be closed and re-opened if you don't want to upset your positioning.

![import](https://user-images.githubusercontent.com/13004169/46576232-bc558500-c9cd-11e8-913f-cef10940816f.gif)

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by Zylann** [comment]
I can still reproduce this with an `ImageTexture`, calling `create_from_image` using an image of different resolution.

Project:
[TextureRectNotResizingIfTextureRecreated.zip](https://github.com/godotengine/godot/files/3649573/TextureRectNotResizingIfTextureRecreated.zip)

**Comment by akien-mga** [comment]
That would be worth a different issue, even if the symptoms are similar the cause is likely different (the original bug *is* fixed).
