### ISSUE TITLE
Mac build is broken

### ISSUE THREAD

**Issue by viktor-ferenczi** [godotengine/godot#20613]
Affects master 66429a15

Broken by PR: #17595 

Quoting comment of @marcelofg55

> I'm getting a build error on OS X when building with scons -j4 platform=osx bits=64 debug_symbols=full separate_debug_symbols=yes dev=yes:
> 
> [ 99%] progress_finish(["progress_finish"], [])
> [100%] make_debug_osx(["bin/godot.osx.tools.64"], ["platform/osx/crash_handler_osx.osx.tools.64.o", "platform/osx/os_osx.osx.tools.64.o", "platform/osx/godot_main_osx.osx.tools.64.o", "platform/osx/sem_osx.osx.tools.64.o", "platform/osx/dir_access_osx.osx.tools.64.o", "platform/osx/joypad_osx.osx.tools.64.o", "platform/osx/power_osx.osx.tools.64.o"])
> scons: *** [bin/godot.osx.tools.64] TypeError : 'NoneType' object has no attribute '__getitem__'
> Traceback (most recent call last):
>   File "/usr/local/Cellar/scons/3.0.0/libexec/scons-local/SCons/Action.py", line 1197, in execute
>     result = self.execfunction(target=target, source=rsources, env=env)
>   File "/Volumes/Data/git/godot_3.0/platform_methods.py", line 22, in wrapper
>     return builder_function(target, source, None)
>   File "/Volumes/Data/git/godot_3.0/platform/osx/platform_osx_builders.py", line 11, in make_debug_osx
>     if (env["macports_clang"] != 'no'):
> TypeError: 'NoneType' object has no attribute '__getitem__'
> scons: building terminated because of errors.
> ERROR!
> 

It is because the env parameter is not passed over to the subprocesses. It is because there were no usages in Windows nor Linux builds. It looks like I missed the reference on Mac.

Possible solutions:
1. Pass `env` as a dictionary (converting if needed)
2. Running the builds inside the process (instead of in subprocess) on non-Windows platforms

I think 2. would be a simpler fix. It needs a simple platform condition to the `run_in_subprocess` method to return the builder function as is if not on Windows.

**Comment by marcelofg55** [comment]
If you need any help testing a possible fix let me know.

**Comment by viktor-ferenczi** [comment]
Fixed in PR #20617

**Comment by viktor-ferenczi** [comment]
@marcelofg55 Yes, thank you. 

Could you please try to build this PR branch on Mac?

**Comment by marcelofg55** [comment]
Just tested it, works fine.

**Comment by viktor-ferenczi** [comment]
Thank you. PR #20617 has passed all checks, it is ready for code review.
