### ISSUE TITLE
Godot 3.0.6 Missing Release Tag

### ISSUE THREAD

**Issue by codingHahn** [godotengine/godot#20615]
Godot 3.0.6 was announced here: https://godotengine.org/article/maintenance-release-godot-3-0-6 but there is no release tag, which prevents me as package maintainer to update my package.

Could you please tag this release?

**Comment by hpvb** [comment]
Sorry I still need to update the Changelog file. I will do that soon and tag the release. Sorry!

**Comment by codingHahn** [comment]
Thank you

**Comment by hpvb** [comment]
3.0.6-stable has been pushed
