### ISSUE TITLE
rotation_degrees in inspector are incorrect

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20616]
**Godot version:**
3.0/3.1-dev

**Issue description:**
I discovered this when I needed to compare rotation_degree values. Basically, when you set rotation_degrees in inspector and run the scene, the actual value is different. Just see this:
![image](https://user-images.githubusercontent.com/2223172/43424443-b8f19056-944f-11e8-92ec-b776de04fa50.png)
I set the degrees to 180, but the actual value is different (using print() in _process()). Even remote inspector shows 180, which definitely shouldn't be like this.

**Comment by vnen** [comment]
I'm not sure if it's possible to get rid of those precision errors, floating point numbers are imprecise by nature. Especially because the angle is stored in radians, so there's two conversion happening: degrees to radians for storage and then back to degrees for printing.

**Comment by akien-mga** [comment]
7-digit precision is normal for floats. This will likely improve when we get double precision, but as @vnen mentions the conversion back and forth between radians and degrees makes it unlikely to avoid any kind of floating point precision issue.
