### ISSUE TITLE
Area2D _on_body_entered() is triggered while CollisionShape2D is disabled

### ISSUE THREAD

**Issue by devin-e** [godotengine/godot#20620]
**Godot version:**

Version 3.0 64 bit for Linux

**OS/device including version:**

Linux Xubuntu
16.04.5 LTS
xenial
AMD Quad-Core Processor A10-8700P

**Issue description:**

This problem only occurs if I alter the CollisionShape2D.shape.extents after I disable the CollisionShape2D.

I've built a simple program that replicates the problem. The two relevant sections are:

```
func reset_area2D():
    $Area2D/CollisionShape2D.disabled = true
    $Area2D/CollisionShape2D.shape.extents = Vector2(10, 10)
```

```
func _on_Area2D_body_entered(body):
    print(body == $".."/Player, ", Disabled: ", $Area2D/CollisionShape2D.disabled)
```

Even when $Area2D/CollisionShape2D.disabled == true, the _on_body_entered function will run and print "True, Disabled: True"

If, however, I reorder the reset_area2D() function as:
```

func reset_area2D():
    $Area2D/CollisionShape2D.shape.extents = Vector2(10, 10)
    $Area2D/CollisionShape2D.disabled = true
```

then everything functions as normal. The _on_body_entered() signal is not triggered while the Area2D is disabled. When it is triggered, it appropriately prints "True, Disabled: False", but will not otherwise print anything. So, it's not presently causing me any trouble, but it did cause some confusion for a time. I don't see this as expected behavior, and haven't stumbled across anything in the documentation explicitly stating not to alter the extents of a collision shape after disabling it. It seems worth reporting to save some one else the headache. 

**Steps to reproduce:**
In the below project, wait until _on_PunchDuration_timeout() is called, which will reset the collision shape. Then move the player character into the disabled enemy collision shape. 

**Minimal reproduction project:**

Here is the simple project reproducing the issue:
[collision-shape-bug-test.zip](https://github.com/godotengine/godot/files/2243037/collision-shape-bug-test.zip)

**Comment by eon-s** [comment]
Looks similar to #17151 and affects master 4b549fa.

**Comment by devin-e** [comment]
Oh perfect. Much appreciated. Apologies for not finding that myself.

**Comment by eon-s** [comment]
@devin-e is similar to the raycast case, but not solved for Area2D, so your issue is still valid.

**Comment by akien-mga** [comment]
In the current master branch, I can't reproduce the issue where it prints `"True, Disabled: True"`, so this seems to have been addressed somehow.
