### ISSUE TITLE
Add the ability to refactor variable names, like in VSCode or Eclipse.

### ISSUE THREAD

**Issue by FlashDaggerX** [godotengine/godot#20624]
**Godot version:**
v3.1.dev.custom_build.7b63c63

**OS/device including version:**
Arch Linux *4.17.10-1-ARCH*

It would really help, because renaming variables a lot is very annoying. I think it would be
a great feature to add to the GDScript editor.

**Comment by hilfazer** [comment]
Also function names.
Also 'Go to variable declaration', 'Go to function definition'.
Also 'Find Usages' for functions and variables, like in QtCreator.

**Comment by FlashDaggerX** [comment]
Inactive, closing.

**Comment by hilfazer** [comment]
Was in necessary to close this? It's one of the most needed feature request.
