### ISSUE TITLE
Stray pixels on Sprite frame

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20622]
**Godot version:**
3.0/3.1-dev

**OS/device including version:**
Windows 10 x64 NVidia GPU

**Issue description:**
Sometimes a sprite will display pixels from adjacent frame. The sprite is correctly cut, because it only appears on a specific flip mode. Happens even with filtering disabled. Screenshot below shows the same sprite and same frame, but the one above is flipped horizontally.
![image](https://user-images.githubusercontent.com/2223172/43426689-dc8d5b2e-9456-11e8-815c-a62192650b09.png)

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2243069/TestProject.zip)

**Comment by eon-s** [comment]
That happens because there is no gap between frames and at some zoom levels, it will blend some part of the rest of the texture, but if you enable 2D pixel snap option it _may_ be solved (again, zoom can introduce artifacts so is better to add a transparent gap).

**Comment by williamd1k0** [comment]
If you are going to use pixel art as an example, you should at least use a 1:1px texture.

As you can see, your texture has different pixel sizes:

![image](https://user-images.githubusercontent.com/10428035/43435287-b3cce228-9455-11e8-8a33-e6b3dbedb1a7.png)

**Comment by KoBeWi** [comment]
The sprite is actually placeholder and I used it as example, because this is where issue happened.

Pixel snap seems to help, but I still think it shouldn't happen at all. Especially when it's dependent on whether the sprite is flipped or not.

**Comment by williamd1k0** [comment]
I was messing with it and it's only happening when the sprite is **centered**.
This makes some sense because your sprite has 105px of width.

As I said, you should use 1:1 textures, and as @eon-s said, you should use 2D pixel snap (it's something needed for pixel art games to avoid half-pixel issues).

By the way, this issue also happens using 1:1 texture when the sprite/rect is centered and the size is odd.

**Comment by akien-mga** [comment]
As mentioned, this is indeed normal behaviour and you should use pixel snapping to fix it when doing pixel art games. Eventually we'll have easy to use game templates and the pixel art one will come preconfigured for that.
