### ISSUE TITLE
Signal "pressed" and "released" from TouchScreenButton seems not always working

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20630]
**Godot version:**
3.0.6,  v3.1.dev.calinou.3f01f40

**OS/device including version:**

Windows 10 1709(HD 4000), Linux Mint Mate 19(HD 3000)

**Issue description:**

When I try click several times on the screen, TouchScreenButton not always send signal "pressed" and "released" when I realease button.
When I press Space key(alternative method to jump), Player always jump.

**Steps to reproduce:**
1. Set to true  Project Settings -> Input Devices -> Pointing -> emulate_touch_from_mouse 
2. Run Scene/Game
3. Click fast several times(it is the most visible when click three times) to screen and see that some "pressed" signals are not recorded/send(print via Output) and Player still fall down.

**Minimal reproduction project:**

[Color Changer.zip](https://github.com/godotengine/godot/files/2244383/Color.Changer.zip)

**Comment by moiman100** [comment]
#20081 should fix this

**Comment by qarmin** [comment]
It is fixed now.
