### ISSUE TITLE
Nodes who are not freeing

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#20637]
I have a scene for collectable items in a game.  They are all part of the group "item".  They are not connected to any signal. 
I have added the scene to my main scene as
`export (PackedScene) var Items`
I then create new instances of these items.
I use `get_tree().get_nodes_in_group()_` a lot to check for conditions on the items.
The problem I am running into is when the user dies and creates a new game.  I am destroying these instances with a for loop like this:
```
for i in get_tree().get_nodes_in_group("item"):
    i.queue_free()

```
It seems like this should work, but the items are locked and are not being deleted.  When I create a new set of items for the new level, the old items are still there and they are all placed.
Is there a better way to do this or is there a way to unlock these instances?  Could there be a bug that is not freeing these items?

**Comment by eon-s** [comment]
You can do `get_tree().call_group("item","queue_free")` to make it shorter, but why does it fail? do you get an error or something?

Can you make a small example where `queue_free` fail?
Also specify the godot version and OS as the template requested.

**Comment by akien-mga** [comment]
Such question would be better asked on the Godot Q&A, without a minimal reproducer or details on steps to reproduce, this can't be qualified yet as an engine issue.
