### ISSUE TITLE
Auto-complete for change_scene()

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20635]
So, when you write load or preload, you get a list of all resources to easily fill in stuff. This is one of the most helpful things in Godot. However, when you do get_tree().change_scene(, you don't get anything. You need to manually write the scene you want, so you need to actually locate it in file list and write the exact name etc. and it's a bit of hassle.

It would be **really** useful if change_scene() suggested you all resources that end with .tscn/scn for auto-completion, because they are potentially scenes you want to switch to.

**Comment by PetePete1984** [comment]
Preload the scene into a variable and use http://docs.godotengine.org/en/3.0/classes/class_scenetree.html#class-scenetree-change-scene-to
