### ISSUE TITLE
Object.set_meta() overwrites data in all instances if children are not selectable

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#20648]
**Godot version:**
3.0.6.stable.official

**OS/device including version:**
Ubuntu 18.04.1

**Issue description:**
When the "Makes sure the object's children are not selectable" button is active on a node, and later set_meta() is called on an instance of that node, the metadata for all instances is modified.

**Steps to reproduce:**
See attached project which reproduces the problem.

**Minimal reproduction project:**
[set_meta_debug.zip](https://github.com/godotengine/godot/files/2247653/set_meta_debug.zip)

Related to
https://github.com/godotengine/godot/issues/12990
https://github.com/godotengine/godot/issues/18591

**Comment by akien-mga** [comment]
Fixed by #32416.
