### ISSUE TITLE
Animation track data not being instanced

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#20653]
**Godot version:**
master 5a5614e8adcc49b92621dc2f39364385769d36a0

**OS/device including version:**
ubuntu, nvidia

**Issue description:**
I have a Scene of a Button, an AnimationPlayer and a Timer. The AnimationPlayer has a "slide in" animation that moves the button the width of the button to the left. I do this by using track_set_key_value on the Animation in the Timer to set the final keyframe position x to the width of the Button text.

I want to instance the Scene a bunch of times so I can have a bunch of Buttons cascade in nicely from the side of the screen.

But if the Timer timeout is called before another instance's track has finished, the other instance's animation track data is changed and it messes up.

I think this might be because the track data in an Animation inside an AnimationPlayer is not being instanced but rather shared. I say this because in the Timer timeout function, "self" contains a unique instanced object so I would expect the animations to be unique too.

Here's a project that shows the behaviour. 14 Scenes instanced. The first seven display correctly since their Timers timeout without overlap but the next 7 Scenes have shorter times that overlap and so overwrite each other and their animations go wonky.

[GodotEditAnimTrack.zip](https://github.com/godotengine/godot/files/2248874/GodotEditAnimTrack.zip)
**Minimal reproduction project:**

**Comment by Zylann** [comment]
I had this problem too in my game, and I solved it the same way as we solve it for modifying materials at runtime: I make them unique in my script.

**Comment by dodgyville** [comment]
Hey thanks for replying.

Would I have duplicate the tracks or just the animation player?

There is an option in the inspector on AnimationPlayer to "make sub-resources unique" but after I select it none of the animations play so I have no idea what it does.

**Comment by Zylann** [comment]
@dodgyville you have to duplicate the animation you are modifying within the AnimationPlayer (is animation is a resource). `track_set_key_value` is a method of `Animation`, you are clearly modifying it, so you need to make it unique, and at runtime.

**Comment by dodgyville** [comment]
I have duplicated the Animation and copied across the Animation Track data. The duplicate animation plays but I am unable to edit the keyframes in the code. Calling new_animation.track_get_key_count(track_id)) returns zero when I know there are five keyframes and I can see them being hit on the screen when it plays the animation.

```
    # duplicate Animation to make it unique
    var orig_anim_title = "original"
    var unique_anim_title = "duplicate"

    var aplayer = self.get_node("Button/AnimationPlayer")
    var anim = aplayer.get_animation(orig_anim_title)
    var unique_anim = anim.duplicate()
    aplayer.add_animation(unique_anim_title, unique_anim)  
    for track_id in anim.get_track_count(): # copy tracks to new animation
        var track = anim.copy_track(track_id, unique_anim)

    var new_anim = self.get_node("Button/AnimationPlayer").get_animation(unique_anim_title)
    var track_id = new_anim.find_track(".:rect_position")
    print("track key count",new_anim.track_get_key_count(track_id))
    # should print the number of keys in the track? which is about five.

    aplayer.play(unique_anim_title)
```

**Comment by Zylann** [comment]
`    var unique_anim = anim.duplicate()`

Doing this should already copy all tracks, keep in mind tracks ARE in the Animation, there is no need to copy them again because it's `duplicate`'s job.
If you find different number of keys then maybe it's broken?

**Comment by dodgyville** [comment]
I initially did just anim.duplicate() but there didn't appear to be any tracks on the new animation (don't quote me on that though)

**Comment by dodgyville** [comment]
yeah, I tried to duplicate Animation again and I just can not get it working. The animation is there but playing it does nothing, as if there is no track data.

**Comment by clayjohn** [comment]
Is this still reproducible in 3.1?

**Comment by substract** [comment]
Hello, I have a a similar scene and can confirm the animations are not running after duplicate in godot 3.1.

**Comment by akien-mga** [comment]
It's pretty weird, but yes it does seem reproducible with the project in OP (note that you need to tweak a script to `add_child()` the instanced node which contains the timer before starting said timer).

**Comment by KoBeWi** [comment]
Can't reproduce in 4.4, tested with this code:
```GDScript
func _ready() -> void:
	var player: AnimationPlayer = $AnimationPlayer
	
	var animation := player.get_animation("new_animation")
	animation = animation.duplicate()
	player.get_animation_library("").add_animation("newer_animation", animation)
	
	player.play("newer_animation")
```
