### ISSUE TITLE
Anchor positions are ignored by canvas item

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#20663]
**Godot version:**

6c569c90b666c7fb773eca3948fc76ba7a160a27

**OS/device including version:**

Linux, OpenGL ES 3.0 Renderer: Gallium 0.4 on NVE7.

**Issue description:**

CanvasItem ignore anchor settings. When right and bottom anchors are set to 1
CanvasItem behaves like these are set to 0 (margins are calculated from left, etc.).

**Steps to reproduce:**
Create new scene, add Node2D, add CanvasItem, set bottom and right anchors to 1,
try to set margins.

**Comment by groud** [comment]
That's an expected behavior, Node2Ds have no meaningful size.
Anchors and margins are supposed to work with Control nodes as parents.
