### ISSUE TITLE
Minimal editor width isn't const

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20669]
**Godot version:**
3.0.x, master

**Issue description:**

When I set editor witdth to minimal in 2D view and change view to script editor, part of the screen view is hidden. 

![2018-08-02 10-30-40](https://user-images.githubusercontent.com/41945903/43572800-a4bb1ad8-9640-11e8-9cd0-95cac8aebe25.gif)

**Comment by YeldhamDev** [comment]
Related to #14806.

**Comment by Anutrix** [comment]
Still happens in latest master commit https://github.com/godotengine/godot/commit/34224d5ce55cd22ca8c627f79413f71f957af800 .

**Comment by Calinou** [comment]
Thanks to https://github.com/godotengine/godot/pull/29752, we now have a way to limit the minimum window size. However, the minimum window size required for an usable editor depends on several settings, such as the editor scale and the font size.
