### ISSUE TITLE
Particles not showing on Tiles and 

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#20660]
I looked this up and didn't find a similar post.  I have added some particles to a few tiles.  The problem is, even after saving as a tileset, the particles don't show up when actually using the Tileset on a Tilemap.

**Comment by PetePete1984** [comment]
http://docs.godotengine.org/en/latest/classes/class_tilemap.html#description

> Tilemaps use a TileSet which contain a list of tiles (textures plus optional collision, navigation, and/or occluder shapes) which are used to create grid-based maps.

**Comment by eon-s** [comment]
You can inspect a TileSet resource, is only data representing the tiles to be drawn by the TileMap, it does not contain any Node.

**Comment by ondesic** [comment]
I guess where this throws me off is that you CAN add a shape and collision node to the tile and it will be baked in.  Can this feature be added to copy the particle info into the tile?

**Comment by ondesic** [comment]
Do you have quick example of how one would do this? :)

**Comment by KoBeWi** [comment]
Probably something like
```
for pos in your_tile_map.get_used_cells():
    if your_tile_map.get_cellv(pos) == TILE_ID_WITH_PARTICLES:
        var particles = preload("urparticles.tscn").instance()
        particles.position = your_tile_map.map_to_world(pos)
        your_tile_map.add_child(particles)
```

**Comment by eon-s** [comment]
There is a method to get all the cells (positions) of certain type(id), so you can do it without reading the whole tilemap.

**Comment by akien-mga** [comment]
Tiles in a TileMap are intentionally limited for performance, they can't be a full scene with all available features. There's now support for animated tiles in the master branch. If you need more, the best is indeed to instance a scene with the additional effects you need based on the underlying tile.
