### ISSUE TITLE
Plugin error not selectable

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#20662]
**Godot version:**

3.0.5.stable.custom_build

**OS/device including version:**

Linux 4.17.4-1-ARCH x86_64 GNU/Linux

**Issue description:**

I encountered the error described in https://github.com/godotengine/godot/issues/20661. The error label when loading a plugin is not selectable, so I cannot easily paste it into an issue.
![1533176997](https://user-images.githubusercontent.com/2496231/43559079-76a2107c-95da-11e8-8972-b8a3381d3798.png)

Related: #165.

**Comment by Zylann** [comment]
Is it printing in the console though?

**Comment by rcorre** [comment]
@Zylann I get these errors in the console:

```
 Failed loading resource: res://addons/my_custom_node/button.gd
 res://addons/my_custom_node/custom_node.gd:7 - Parse Error: Can't preload resource at path: res://addons/my_custom_node/button.gd
 modules/gdscript/gdscript.cpp:583 - Method/Function Failed, returning: ERR_PARSE_ERRO
```

So that particular error is only visible in the un-selectable menu. 

![1533559667](https://user-images.githubusercontent.com/2496231/43717426-8f6a8c64-9955-11e8-9475-5bf34f569b3b.png)
