### ISSUE TITLE
Don't change workspace on node select

### ISSUE THREAD

**Issue by TrickyWidget** [godotengine/godot#20676]
Godot, 64-bit, 3.06.stable.official.8314054
Windows 10 Home, 64-bit, Version 1803, Build 17134.165

In the Scene dock, whenever a node is selected, the workspace is automatically switched to 2D/3D.  When I'm focused on coding, this is very annoying.  I'd very much like to stay in the Script workspace.  It would be a great boon to have an option in Editor Settings to disable this behavior and just leave open whatever workspace is current.

Thanks for all your hard work!

**Comment by PetePete1984** [comment]
Number one reason why I usually code in an external editor, right here - the context switching is incredibly distracting. You want to double-check some Node's properties while coding and you're out of it.

**Comment by r-mice** [comment]
If you only change the workspace by middle-click in a node, would be great

**Comment by eon-s** [comment]
Or double click, but is already on viewport focus.

Or, "leave select without changing context" to middle click (or key combination+ click) to not affect much the current workflow.

**Comment by r-mice** [comment]
@eon-s Thinking better, Ctrl+Left Click to change workspace is better. What if we open an issue suggesting this?

**Comment by TrickyWidget** [comment]
I'm not too particular, so long as there's some way to make a normal left-click leave the workspace alone.

**Comment by swarnimarun** [comment]
I like the idea of pinning a workspace.
And probably the ability to pin the bottom panels too. Especially for the Visual Shader and Animation Player.

**Comment by andrejp88** [comment]
Any progress on this? Maybe a simple solution with minimal UI changes is a toggle in the editor settings.

**Comment by Keetz** [comment]
Since Godot 3.2.x I am beginning to see a lot more automatically context switching that I haven't seen before.

For example, when loading a scene (from script) in the running game, it changes to the 2D/3D view.

Sometimes it is like the editor is in a "bad state" and it kind of changes to the 2D view on completely unrelated actions, for example I experience it changing to 2D when pressing "ctrl + s" to save my script, which is really annoying.

**Comment by KoBeWi** [comment]
Closing this in favor of newer and more detailed discussion issue: #39539
