### ISSUE TITLE
UWP fails to build due to something in websockets and upnp

### ISSUE THREAD

**Issue by Grosskopf** [godotengine/godot#20672]
This one might be similar to #16830 due to websockets being a Problem again but i haven't looked into it jet, it Fails at 100% when trying to link miniupnpc and lws-plat-win in. If websockets and upnp are left out, it builds.

**Godot version:**
6c569c90b666c7fb773eca3948fc76ba7a160a27

**OS/device including version:**
Windows 10 in Virtualbox

**Issue description:**
Fails to build for platform uwp

**Comment by Faless** [comment]
What version of Visual Studio? What version of the Win10SDK? What architecture?
What error are you getting? Last time I checked it compiled fine.

**Comment by Faless** [comment]
@Grosskopf I just built current master (64bits) with VS 2017 (15.7.6) and Win10SDK (10.0.16299.0) with no errors.

**Comment by Grosskopf** [comment]
I use the VS 2015 command prompt, and have sdk's from 10.0.10586.212 to 10.0.26624 installed, not sure wich one the command prompt picked, my windows 10 is 64 bits. It seems to build to 32 Bits though.
Can you tell me how i can check the used sdk in the native tools command prompt?
this is the end of the Output currently

`[ 71%] Linking Program        ==> bin\godot.uwp.debug.32.x86.exe
   Creating library bin\godot.uwp.debug.32.x86.lib and object bin\godot.uwp.debug.32.x86.exp
modules.uwp.debug.32.x86.lib(minissdpc.uwp.debug.32.x86.obj) : error LNK2019: unresolved external symbol _GetBestRoute referenced in function _ssdpDiscoverDevices
modules.uwp.debug.32.x86.lib(minissdpc.uwp.debug.32.x86.obj) : error LNK2019: unresolved external symbol _GetIpAddrTable referenced in function _ssdpDiscoverDevices
modules.uwp.debug.32.x86.lib(lws-plat-win.uwp.debug.32.x86.obj) : error LNK2019: unresolved external symbol _CreateFileW referenced in function __lws_plat_file_open
modules.uwp.debug.32.x86.lib(lws-plat-win.uwp.debug.32.x86.obj) : error LNK2019: unresolved external symbol _GetFileSize referenced in function __lws_plat_file_open
bin\godot.uwp.debug.32.x86.exe : fatal error LNK1120: 4 unresolved externals
scons: *** [bin\godot.uwp.debug.32.x86.exe] Error 1120
scons: building terminated because of errors.`

**Comment by Grosskopf** [comment]
ah right, the x86 command prompt compiles to x86, will test 64 bits

**Comment by Grosskopf** [comment]
Oh, 64 bits builds

**Comment by Grosskopf** [comment]
Sadly the hololens has a 32 bit operating system :/

**Comment by mhilbrunner** [comment]
I will try to get a UWP build & debug env up and running this weekend.

First things I would test, if somebody wants to try:

- define `MINIUPNP_STATICLIB` as mentioned in the miniupnp [README](https://github.com/miniupnp/miniupnp/tree/master/miniupnpc)

- play around with the link order ([see here](https://stackoverflow.com/questions/44267611/undefined-reference-in-an-object-file-how-find-which-library-contains-it))

**Comment by Faless** [comment]
#21548

**Comment by akien-mga** [comment]
> @mhilbrunner for UPNP the miniupnpc dev suggests a native implementation cry miniupnp/miniupnp#238 .

That's a bit shooting themselves in the foot if they don't care about cross-platform support...

**Comment by Faless** [comment]
> That's a bit shooting themselves in the foot if they don't care about cross-platform support...

Yeah, the main problem though seems to be that there is no replacement function in UWP, I'll dig a bit more.

**Comment by Faless** [comment]
Well, there is a [`GetBestRoute2` function](https://docs.microsoft.com/en-us/windows/desktop/api/Netioapi/nf-netioapi-getbestroute2) which might be supported (of course, I a function is missing, check for `Function2` xD).
I'll see for a replacement for `GetIpAddrTable` in https://docs.microsoft.com/en-us/windows/desktop/api/Netioapi/
