### ISSUE TITLE
Make Sub-Resource Unique, modify undesirable Node

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20684]
**Godot version:**
3.1 calinou 3f01f40

**OS/device including version:**
Windows 10  Intel HD 4600

**Steps to reproduce:**
![ezgif-5-723abaaaaf](https://user-images.githubusercontent.com/41945903/43635125-7650bf58-970e-11e8-8e9e-7a5a1dbfe2eb.gif)

I expected, that Label2 will change size but Label changed size even it wasn't selected.

**Comment by bojidar-bg** [comment]
Does it still happen if you reselect the label after "Make resources unique"?

**Comment by qarmin** [comment]
This only happens, when I change settings in Inspector immediately after select opition "Make Sub-Resource Unique".
When I change Node and return to it, everything seems to work.
