### ISSUE TITLE
Inspector: Allow to search properties in sub-resources

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20688]
**Godot version:**
3.1-dev

**Issue description:**
Godot 3.1 introduced sub-resource editing in the same inspector. It also made property search feature more visible (I didn't notice it in 3.0 xd). However, I noticed that searching doesn't show properties from sub-resources, which is a bit counter-intuitive given how integrated they are now in inspector. So the search field should search for sub-resource properties too.

![image](https://user-images.githubusercontent.com/2223172/43649400-5898d7be-973d-11e8-94ea-983dea2ba437.png)
![image](https://user-images.githubusercontent.com/2223172/43649389-5223fa44-973d-11e8-98a2-e48f2e07d64c.png)

**Comment by akien-mga** [comment]
This is still valid as of Godot 3.3.

**Comment by KoBeWi** [comment]
Closing in favor of a proposal: https://github.com/godotengine/godot-proposals/issues/5502
