### ISSUE TITLE
Cancel search button for file explorer and inspector

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20689]
Basically this:
![image](https://user-images.githubusercontent.com/2223172/43649769-4d55564c-973e-11e8-86ab-20c78c795ac1.png)
It was in 3.0, but was removed with introduction of new search bar in 3.1. This button would also be useful in file explorer and is missing in both versions.
![image](https://user-images.githubusercontent.com/2223172/43649840-866bbc5a-973e-11e8-965c-0ca7657e6a44.png)

**Comment by williamd1k0** [comment]
Related PR: #20155

**Comment by akien-mga** [comment]
Fixed by #20155.
