### ISSUE TITLE
Error: Cannot get Proc Address for CreateContextAtrribs

### ISSUE THREAD

**Issue by Jermaine0Forbes** [godotengine/godot#20687]
I have been getting this error whenever I try to start up godot  on my  laptop recently, and I get a following message that says " Your system's graphic drivers seem to not support OpenGL 3.3 / OpenGL ES 3.0, sorry :( Godot Engine will self destruct as soon as you acknowledge this error message". So after I click that window, the application terminates. I don't know why this is a problem because I have been using godot 3 on this laptop the whole time. Could it be that some type of system update on my laptop did something that gave me an error? I decided to download an OpenGL Viewer and I found out that the  current version I have is 1.1 which was surprising. It was even more surprising when I saw that my  6 year old desktop has a OpenGL version 4.5.  The version of Godot I'm using is 3.04 stable, is there a better way to Godot

**Godot version:**

3.04

**OS/device including version:**

OS: Windows 10 Home
GPU: Intel(R) UHD Graphics 620
RAM: 6GB

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
Yes, it's possible a system update gave you the error. But for us to be able to help you you should fill out the issue section about your device (OS, GPU card, RAM).

**Comment by Jermaine0Forbes** [comment]
OS:  Windows 10 Home
GPU:  Intel(R) UHD Graphics 620
RAM: 6GB

**Comment by vnen** [comment]
You should try to reinstall the Intel Graphics driver.

**Comment by Jermaine0Forbes** [comment]
Okay , reverting back from the recent update made godot work again. So I'm closing it
