### ISSUE TITLE
Two loading bars are displayed instead of one

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20685]
**Godot version:**
3.1 calinou 3f01f40

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
When I open AssetLib, in the botton of the editor I see a loading bar which resets at 30%. It looks a bit strange. I think, the first bar shows progress opening AssetLib and second shows progress loading description of assets from server. It will look better when the bars become one

**Steps to reproduce:**
This gif is little slow down, open it in new tab to see it without strange colours.
![2018-08-03-12-11-58](https://user-images.githubusercontent.com/41945903/43638269-6d9565f8-9718-11e8-80d4-fe6b1518089e.gif)

**Comment by KoBeWi** [comment]
In 3.2 there's no loading bar at all, so like, fixed.
