### ISSUE TITLE
Add a Node2D/Spatial toggle to CreateDialog.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#20694]
**Godot version:**
Godot master

**Issue description:**
It would be nice if users didn't have to recompile the engine just to remove the Node2D or Spatial nodes from their CreateDialog content. Why don't we create a ProjectSettings value (perhaps toggleable directly from the CreateDialog) that allows users to indicate the type of game they are making, and it can automatically hide the opposite type of node from the dialog (so you don't get any filter conflicts and such). Someone on FB already asked about this feature and I've heard of people wanting to remove the clutter many times.

What do you guys think?

**Steps to produce:**

1. Add a `GLOBAL_DEF` in the CreateDialog constructor.
2. Add a toggle button to the CreateDialog GUI and connect to its signal
3. Add a function callback to toggle the value with GLOBAL_SET.
4. Modify the update_search method to incorporate the GLOBAL_GET value.

**Comment by eon-s** [comment]
I'm not in favor of hiding things, on the contrary, I would like that panel to be an easily pluggable one where _global editor templates_ can be added.

**Comment by KoBeWi** [comment]
Probably fixed in upcoming 3.2 with fature disabling.

**Comment by akien-mga** [comment]
Indeed, https://godotengine.org/article/godot-32-will-allow-disabling-editor-features solves this use case.
