### ISSUE TITLE
Default directory for creating new resource from explorer

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20690]
**Godot version:**
3.1-dev

**Issue description:**
There's this new "New resource" option in 3.1's file explorer.
![image](https://user-images.githubusercontent.com/2223172/43650014-f5ebe226-973e-11e8-999f-fd64db1dc44a.png)
However when you click it and select resource, it opens a root res directory to save the file to. It should by default open the directory you clicked inside.

**Comment by akien-mga** [comment]
Ping @swarnimarun who implemented the feature in #20359.

**Comment by swarnimarun** [comment]
I thought I missed something, foolish me. This might take a while as I am busy due to college since the past few weeks hopefully I can get back to doing all this stuff soon.

**Comment by swarnimarun** [comment]
Going back on my words feels wrong but I happened to fix it.
