### ISSUE TITLE
GodotPhysics collision shapes table not matching enums

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#20699]
**Godot version:**
Any version after commit 0a36e974daeac1875d4e7551f4ba88ba8e1d1851

**OS/device including version:**
Any device

**Issue description:**
GodotPhysics sat resolution function table has not been updated to take into account the new cylinder collision shape during the resolution function lookup.

**Steps to reproduce:**
Create a rigid body with a spherical collision shape and another with a concave polygonal collision shape and make them collide.
The collision is not resolved and an error is printed (the solver function is not found). 

I know that GodotPhysics has been deprecated but it won't be removed in 3.1 AFAIK, so it should keep working in the next release.

**Comment by muiroc** [comment]
Sorry I completely missed this! I should have tested more the previous behavior. 

I'll try to fix it, but the best I can do is updating the table and doing an early out for cylinders since i don't know how to properly implement it.
