### ISSUE TITLE
Path setting control in EditorInspector does not allow setting paths manually or clearing set paths

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/godot#20709]
In 3.0.6 the settings editor offers one line edit to type in a path in addition to a small folder icon on the right which allows you to use the file dialog.

In 3.1 dev this has been replaced with a single button. It does not offer the convenience of editing the path straight into a line edit.

Example: in settings editor File System -> Directories, Text Editor -> External -> exec_path and so on.

The new way is less convenient since there's no easy way to copy paste paths or, as is my case, write them very quickly on the keyboard instead of spending time scrolling through endless number of files.

Unless there's a very good reason for denying the user to type in a path straight up in a line editor, is it possible to revert this?

**Comment by akien-mga** [comment]
Actually found an issue with this new path setting widget which is worse than not being able to type in paths manually: you can no longer *clear* a path once it has been set.

So if I set a custom export template, I can no longer unset it.
