### ISSUE TITLE
A way to recover scene's exported values with old variable names

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#20700]
All godot versions:

**Issue:**

There is an issue on exported variables, if you save scenes with them and for some reason you need to rename a variable, all the scenes will be virtually broken, they won't recognize the original variable anymore (for obvious reasons, the name is not there) and can be a real problem for mid/big projects and teams.

Other engines have ways to kind of solve it, like Unity with `FormerlySerializedAs` attribute, although I think is kind of messy because in some time can end in:
```csharp
[FormerlySerializedAs("puntos")]
[FormerlySerializedAs("points")]
[FormerlySerializedAs("stars")]
[FormerlySerializedAs("coins")]
[SerializeField]
private string anotherTemporaryScoreName;
```

But it solves the issue...

In the case of Godot and to make it more clean than the other solution, it can use extra elements to add the name in which will be serialized:
```gdscript
export(int,"SerializationName") var variable_with_many_names

#or

export(int) var variable_with_many_names serializedAs SerializationName
```

This way, the tscn files will keep a serialized name independent of the script, so old scenes will keep working without having to open, edit and save and without accumulation of legacy names, also programmers won't mess up scenes where designers are working.

**Comment by Zylann** [comment]
This is one in maaany things we could add to `export`, but that "short" keyword is not enough to fit them all. Ideally we would need annotations #20318

**Comment by eon-s** [comment]
Is a proposal so, closing, the proper proposal was made in the corresponding repository
