### ISSUE TITLE
ViewportTexture broken path when reassigning Viewport Path

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#20713]
**Godot version:** 3.1.dev.calinou.6c569c9
**OS:** Win 10 64bit

**Issue description:**
When reassigning the `Viewport Path` property of a `TextureRect` the editor will set a different path:

![grafik](https://user-images.githubusercontent.com/3957610/43677541-d6503352-9803-11e8-9e49-822217af8671.png)

It looks like it's the absolute path within the editor, not the path relative to the project.

**Steps to reproduce:**
- create a `Viewport`
- create a `TextureRect`
- set `TextureRect > Texture` to new `ViewportTexture` (on the dialog, select Viewport created above)
- clear the `Viewport Path` property and try to assign it again - this time a different dialog is shown and the Editor will use the strange path as seen in the screenshot

**Comment by spacechase0** [comment]
I seem to be having this issue too, except using a MeshInstance with a material using said viewport for its texture. I'm using Godot 3.0.6.

Another instance: https://godotengine.org/qa/34701/viewporttexture-loses-track-viewport-time-what-doing-wrong

**Comment by CptPotato** [comment]
Yes, looks like this one is an exact duplicate. Thanks for bringing it up, I'll close this issue now since the other one is already set for the 3.1 milestone.
