### ISSUE TITLE
Attaching C# source to AnimationNodeOutput results in a crash

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#20718]
**Godot version:**
`master` / 6c569c90b66

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
Attaching a C# source (which extends `AnimationNodeOutput`)  file to an output node in an `AnimationTree` causes the editor crash either when the scene is saved, or it is launched.

The stacktrace of the crash is as following:

```
Thread #1 [godot.x11.tools] 20003 [core: 3] (Suspended : Signal : SIGSEGV:Segmentation fault)

__cxxabiv1::__dynamic_cast() at dyncast.cc:68 0x7ffff4e802f2	
cast_script_instance<CSharpInstance, CSharpLanguage>() at csharp_script.h:56 0x5555569fa757	
_GodotSharp::_dispose_object() at gd_mono.cpp:897 0x555556a0ef7c	
_GodotSharp::_dispose_callback() at gd_mono.cpp:918 0x555556a0e1b1	
MethodBind0<_GodotSharp>::call() at method_bind.gen.inc:137 0x555556a157cd	
Object::call() at object.cpp:918 0x55555ab08c6a	
MessageQueue::_call_function() at message_queue.cpp:260 0x55555ac7468a	
MessageQueue::flush() at message_queue.cpp:305 0x55555ac74978	
SceneTree::iteration() at scene_tree.cpp:476 0x55555886753f	
Main::iteration() at main.cpp:1,777 0x555556699a62	
<...more frames...>	
```

**Comment by reduz** [comment]
this may have been fixed though, so please test again

**Comment by mysticfall** [comment]
I haven't been able to use the latest master for a while due to a couple of blocking issues for my project. At this moment, I'm spending time to make art assets instead, hoping they could be fixed in the meanwhile.

Probably I'll somehow find some workaround to make it work again if it looks like the issues would take more time to be addressed.

I guess I'll be able to test it in a few weeks at any rate. Thanks!

**Comment by akien-mga** [comment]
Assuming fixed for now, please comment if you can still reproduce it in 3.1 beta 6.
