### ISSUE TITLE
Allow adding custom animation node in AnimationTree

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#20720]
**Godot version:**
`master` / 6c569c90b66

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
The current implementation of `AnimationTree` seems to support adding a custom `AnimationNode` to the tree and it works as expected when it's done dynamically from the code.

However, as there's no matching UI functionality to do the same process, such a node cannot be added within the editor but has to be added programatically, which involves disconnecting existing nodes and reconnect them after inserting the custom node.

And even though it can be made to work this way, there's a potential to cause problem when saving the modified `AnimationTree` back into a packed scene and opening it again, as the editor probably wouldn't know how to draw such a node.

As such, it'd be better if there's an editor feature to add a blank custom `AnimationNode` with a property to adjust number of available inputs.

**Comment by karroffel** [comment]
@reduz mentioned that a `tool`-API exists for that, but it's not exposed.

cc @reduz

**Comment by mysticfall** [comment]
Thanks! Does the PR also contain some fixes for #19878 (maybe except for the `GetInputConnection()` part)?

**Comment by uzkbwza** [comment]
this appears to be broken again in 4.x - there is no way to use a custom animationnode implementation.
