### ISSUE TITLE
Possible to force use of dummy audio driver?

### ISSUE THREAD

**Issue by rfht** [godotengine/godot#20729]
**Godot version:** 3.0.5

**OS/device including version:** OpenBSD 6.3 -current

**Issue description:**

I'd like to run Godot with the dummy audio driver specified via the command line. I tried the following without success:

```
godot --audio-driver dummy
godot --audio-driver Dummy
godot --audio-driver DummyAudio
godot --audio-driver dummy-audio
```
All of this returns the `Invalid Audio Driver: ` error message. However, the argument `PulseAudio` works.

Am I missing the right way to specify this? Or is triggering dummy audio from the command line not supported? I saw it fall back to it when there was an issue that pulse couldn't be initialized.

The reason for this is that on OpenBSD, pulseaudio is currently causing issues with closing Godot's windows and the application. It's being looked into, but disabling audio via CLI flag would be useful to have for such and other situations IMO.

**Steps to reproduce:** run Godot with any of the above `--audio-driver dummy` etc. arguments

**Minimal reproduction project:** not applicable

**Comment by akien-mga** [comment]
The "Dummy" audio driver is only used by the server platform, it's not registered as a driver for Linux/*BSD.

I guess it *could* be registered as an option if there's a use case for it though. CC @marcelofg55 @fire

**Comment by marcelofg55** [comment]
Sounds okay to me to add the Dummy driver as an option always. I can add it if nobody is against it.

**Comment by akien-mga** [comment]
I tested on X11, seems to work just fine. So yeah, IMO it wouldn't hurt to register it for all platforms.

Minimal diff for X11:
```diff
diff --git a/platform/x11/os_x11.cpp b/platform/x11/os_x11.cpp
index 9d1e3291b..2ef7f9a4b 100644
--- a/platform/x11/os_x11.cpp
+++ b/platform/x11/os_x11.cpp
@@ -2834,6 +2834,8 @@ OS_X11::OS_X11() {
 	AudioDriverManager::add_driver(&driver_alsa);
 #endif
 
+	AudioDriverManager::add_driver(&driver_dummy_audio);
+
 	layered_window = false;
 	minimized = false;
 	xim_style = 0L;
diff --git a/platform/x11/os_x11.h b/platform/x11/os_x11.h
index 44455a2d8..4b75e1be3 100644
--- a/platform/x11/os_x11.h
+++ b/platform/x11/os_x11.h
@@ -39,6 +39,7 @@
 //#include "servers/visual/visual_server_wrap_mt.h"
 #include "drivers/alsa/audio_driver_alsa.h"
 #include "drivers/alsamidi/alsa_midi.h"
+#include "drivers/dummy/audio_driver_dummy.h"
 #include "drivers/pulseaudio/audio_driver_pulseaudio.h"
 #include "joypad_linux.h"
 #include "main/input_default.h"
@@ -165,6 +166,8 @@ class OS_X11 : public OS_Unix {
 	JoypadLinux *joypad;
 #endif
 
+	AudioDriverDummy driver_dummy_audio;
+
 #ifdef ALSA_ENABLED
 	AudioDriverALSA driver_alsa;
 #endif
```

**Comment by marcelofg55** [comment]
@akien-mga I've used another approach on the PR, a more generic one.

**Comment by rfht** [comment]
I think the main benefit is that the whole godot engine doesn't fail if there is an issue with the audio backend (like currently pulseaudio for me). A lot of work can still be done with the dummy audio driver.

@marcelofg55 Because of our (new) issues with pulseaudio, I've been looking into adding sndio as backend. Can I ping you about this later if I have specific questions that I can't solve?

**Comment by rfht** [comment]
PS: thanks for adding this!

**Comment by marcelofg55** [comment]
@rfht Is there an Issue with the pulseaudio problems? And sure, if you need any help let me know.

**Comment by rfht** [comment]
I haven't opened an issue because this seems to be on the OS side on OpenBSD - Godot 3.0.2 worked fine until about the time that our pulseaudio port got updated to version 12 in June/July. Haven't heard from problems elsewhere.

I'm still trying to get my bearings on this problem and might open an issue later if there's something on Godot side that could help or be fixed.

**Comment by marcelofg55** [comment]
@rfht what's exactly the issue? It doesn't let Godot close its window?

**Comment by rfht** [comment]
Since about 3-4 weeks, godot in its default ports version on OpenBSD that uses pulseaudio backend (the only one supported by godot that's available on OpenBSD) exhibits the following behavior:

* Regular windows fail to close (e.g. project manager, main editor interface) via the godot interface buttons. They can then be closed via the window manager's close function.
* After closing all windows, the main process fails to close. This can usually be aborted with Ctrl+C.
* Audio playback doesn't work (tested with Dodge the Creeps in the godot-demo-projects that does play back audio on a Mac).

Expected behavior:
Normal audio playback, and normal closing behavior of windows and the main process.

None of these issues were present in the port based on Godot version 3.0.2 before about 3-4 weeks ago. Running the same port since then results in above bugs; as does running newer versions (tested up to 3.0.6).

The windows close and the program terminates normally if Godot is run with the Dummy audio driver.

A review of related changes to the OpenBSD operating system and dependencies in our ports tree showed 2 changes that fit the timeline and the bug behavior:

* [pulseaudio updates to 12.0, 12.1, and then 12.2 between end of June and July 17th](https://github.com/openbsd/ports/commits/master/audio/pulseaudio)
* [several commits to the OS regarding threads/locks](https://github.com/openbsd/src/search?q=thread&type=Commits) - examples include [releasing kernel lock on thread exit](https://github.com/openbsd/src/commit/3183901a3680e0c1e9251698ac99b7a66e0a2b3f), and [thread signal handling](https://github.com/openbsd/src/commit/3f0b58624f77a2c3f50097dc3510d689f9c832ff)

Need to rebuild pulseaudio with debug symbols for some more info from a backtrace...
