### ISSUE TITLE
PI is not defined in shaders

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#20726]
**Godot version:** 3.1

PI is defined in GDscript but not in the shading language. Setting a `uniform` leads to an extra variable that could be modified through the inspector. Also, even if constants were available (#10577), some basic constants defined directly in the language would be useful. I'm new to shaders, so apologies if this is not desirable.

**Comment by CptPotato** [comment]
Pi is often used in shaders so I think this is a good idea.

**Comment by creikey** [comment]
Along with `TAU`

**Comment by udit** [comment]
Can this be added to 3.3?

**Comment by clayjohn** [comment]
@udit No, 3.3 is receiving bug fixes only. There is a PR open to add ``PI``, ``TAU``, and ``E`` to 3.4, but there is still ongoing discussion about whether breaking compatibility is worthwhile https://github.com/godotengine/godot/pull/52315
