### ISSUE TITLE
Attempt to call function 'add item' in base 'null instance' on a null instance

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#20736]
**Godot version:**
https://github.com/godotengine/godot/commit/464d59935dccd558e54f30de24c9ad8ce4e7b686

**OS/device including version:**
Antergos (Arch Linux)

**Issue description:**
Expected: Show target 'Stereo'
Terminal error: "No Target 'x-special/gnome-copied-files'"

**Steps to reproduce:**
Code: (was working with former versions of the master branch)
```Swift
onready var AudioDropdown = $"Panel/Mix target/target"

func _ready():
	$"Panel/GraphicsQuality/graphics_preset".select(default_preset)
	_on_graphics_preset_item_selected(default_preset)
	var screen_size = OS.get_screen_size()
	for resolution in display_resolutions:
		if resolution.x < screen_size.x and resolution.y < screen_size.y:
			ResolutionDropdown.add_item(str(resolution.x) + "×" + str(resolution.y))
	ResolutionDropdown.add_item("Fullscreen")
	ResolutionDropdown.select(0)
	for target in mix_target_presets:
		AudioDropdown.add_item(target)
```

**Minimal reproduction project:**
https://github.com/HugeGameArtGD/Solus-Stunts/blob/master/source/settings/settings.gd

**Comment by akien-mga** [comment]
I'm not sure what to do with this issue, you don't really describe any engine bug, just that your game has a bug and we have to clone a big repo and import dozens of assets to try to find out how...

The error you're mentioning is likely unrelated to Godot, we don't do any handling of `x-special/gnome-copied-files`. I think you need to debug this on your end, and open an issue once you've narrowed it down to an actual engine issue and not a bug in your scene/script/system.

**Comment by akien-mga** [comment]
For the reference, I did try to run the attached "minimal" project, and after 10 min of assets import I get:
![screenshot_20180815_095239](https://user-images.githubusercontent.com/4701338/44137505-f639589a-a070-11e8-947c-2e3e5655a30a.png)
I chose "Open Anyway", tried to run the game, and got:
![image](https://user-images.githubusercontent.com/4701338/44137526-0493a238-a071-11e8-9b40-5427e13b0e1b.png)

**Comment by LinuxUserGD** [comment]
Thanks for testing +1
Full clone: git clone --recursive https://github.com/HugeGameArtGD/Solus-Stunts.git

Fixed in https://github.com/HugeGameArtGD/Solus-Stunts/commit/4b4c9bc6eb143edb96bb21feb85015123255bff4
