### ISSUE TITLE
When instancing a scene as a node, Godot should check if a parent is selected before it shows the file dialog 

### ISSUE THREAD

**Issue by Maykeye** [godotengine/godot#20730]
**Godot version:**
3.0.6 official steam

**OS/device including version:**
Linux-x86-64

**Issue description:**
In rare case if I forgot to select a node/deselect it somehow, instancing scene as a node makes me to select scene file twice

**Expected behavior:**
* Without selected node  I click on "instance scene as node" button on top of the scene tree dock  
* Godot displays "No parent to instance a child at/OK :("
* I properly select a node
* Click "instance scene as node"  again
* Select the file, everyone happy

**Actual behavior:**
* I click on "instance scene as node" without selected node.
* Godot displays file dialog to choose a scene
* I select a scene file
* Only now godot displays "No parent to instance a child at/OK :("
* I properly select a node
* Click "instance scene as node"  again
* Select the file again, 

Though godot remembers directory, it's still annoying to choose the file  second time. 
There is no reason to show the file dialog  at all if parent is not selected as operation can never succeed so it basically wastes user time a little.

**Comment by DualMatrix** [comment]
I'm unable to reproduce this issue in the master branch, it seems fixed already?

**Comment by Maykeye** [comment]
Yes, it works now.
