### ISSUE TITLE
Realtime audio filtering (lowpass, highpass, bandpass)

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#2073]
Hi!

Is it possible to perform simple audio processing in realtime in Godot?

This could have many uses like effects of being underwater or stunned.

Every piece of realtime audio manipulation saves storage capacity needed for games - as some effects can be used to alter the sound samples without storing additional copies of them.

**Comment by akien-mga** [comment]
Does AudioServer.voice_set_filter() fit the bill? Or the similar stuff in SamplePlayer, etc.? Check the in-game help in the current master branch, it's more up-to-date than the API reference on the wiki. (source is https://raw.githubusercontent.com/godotengine/godot/master/doc/base/classes.xml)

**Comment by reduz** [comment]
godot 2.1 will have a new audio backend

**Comment by neikeq** [comment]
The new audio backed was postponed to 2.2

**Comment by toby3d** [comment]
@neikeq The new version will be possible to receive real-time audio data?

**Comment by akien-mga** [comment]
Assumed fixed in 3.0 with the new audio engine, feel free to reopen/comment/open a new issue if it's not the case.
