### ISSUE TITLE
Selecting a Button from the recent nodes list returns a TouchScreenButton.

### ISSUE THREAD

**Issue by FlashDaggerX** [godotengine/godot#20740]
**Godot version:**
v3.0.6.stable.custom_build

**OS/device including version:**
Arch Linux _4.17.10-1-ARCH_

**Issue description:**
Adding a Button from the recent nodes list returns a TouchScreenButton instead. I haven't tried it with anything else except the Button.

**Steps to reproduce:**
Add a Control node, with a button as its child. Then go back to add another button from the list, and it returns a TouchScreenButton.

**[A video depicting the issue](https://www.youtube.com/watch?v=526lzNFt6mo&feature=youtu.be)**

**Comment by Noshyaar** [comment]
Related: https://github.com/godotengine/godot/issues/6535
