### ISSUE TITLE
Autotile is broken in 3.1 for 3.0 tileset resources

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#20746]
**Godot version:**

Pre-broke : https://github.com/godotengine/godot/tree/ba48417147efef6c17d0e1d1a0f9f11b75c2648e
Post-broke: https://github.com/godotengine/godot/tree/c291fc39ad6a9e072798311c0ba97c30cc8d24cb

**OS/device including version:**

All

**Issue description:**

If you open a godot 3 game that use tileset with autotile in master, tiles aren´t added to tileset editor and 2d editor doesn´t show correct position to tiles (allways shows entire texture).

Game: https://itch.io/jam/godotjam062018/rate/270307

Pre-broke:
![autotilebudpost3x3commit](https://user-images.githubusercontent.com/11712737/43689132-def85f32-98f5-11e8-9a9e-273cc389a730.png)

Post-broke:

![autotilebudpre3x3commit](https://user-images.githubusercontent.com/11712737/43689133-e5c13dac-98f5-11e8-84c8-e66056b55f73.png)

This commit: #16772  made the compatibility breakage. (note that compiling from https://github.com/godotengine/godot/tree/ba48417147efef6c17d0e1d1a0f9f11b75c2648e or 
https://github.com/godotengine/godot/tree/c291fc39ad6a9e072798311c0ba97c30cc8d24cb anyways doesn´t allow to you to select a tilemap (Godot closes). 

Only one tile is showed in tileset editor, tres resource is not correctly opened.

I test this bug in godot compiled today (05/08/2018) and bug is present (If compatibility - breaking between 3 and 3.1 is going to be considerated a bug)

**Minimal reproduction project:**
https://itch.io/jam/godotjam062018/rate/270307

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by MarianoGnu** [comment]
Yeah, someone changed the is_autotile property to tile_mode without worring about backwards compatibility, con can fix it changing the tile_mode of the autotiles.
A hack to do it automatically would be nice too. i just needs to take in account the is_autotile property on the _get() method if tile_set.cpp
