### ISSUE TITLE
Make it possible to serialize objects through GDScript

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#2075]
According to that page: https://github.com/okamstudio/godot/wiki/binary_Serialization , it is possible to serialize vars only when reading/writing from a file, and when sending over PacketPeer.

It would be nice if it is possible to convert a RawArray (or String) to var and back, for some applications like Compressed Protocols, (strange) Game Save Formats,  etc.

**Comment by jrimclean** [comment]
I think this will be covered by the pack/unpack functionality Juan an I have been discussing. See https://groups.google.com/forum/#!topic/godot-engine/t14p7xzxb9E and feel free to contribute your ideas.

**Comment by captainwasabi** [comment]
I could/can use this for my font converter where you have to give the unicode value for the character.  it would be nice to let my non-technical people provide a string like "0123456789" that corresponds to the characters in the .png rather than "0x0030", "0x0031", etc

**Comment by est31** [comment]
@jrimclean could you copy the contents here, its only accessible to embers of the google group.

**Comment by captainwasabi** [comment]
All you have to do to see it is join

**Comment by est31** [comment]
I need a google account and whatnot for that, no thanks.

**Comment by est31** [comment]
Closed forums are bad.

**Comment by jrimclean** [comment]
@est31 We will be implementing something similar to this: https://docs.python.org/2/library/struct.html
That is the most important bit (no pun, really). Pack/unpack will become methods of ByteArray (RawArray in GDScript).

**Comment by est31** [comment]
pack/unpack is something different I think, because there you don't have to store type information, it is supplied by the format string. Its like comparing protobuf with json.

**Comment by jrimclean** [comment]
@est31 I'm sorry I don't understand your objection. bojidar-bg, said "It would be nice if it is possible to convert a RawArray (or String) to var and back" This is what pack/unpack will do.

**Comment by est31** [comment]
pack/unpack takes a format string thats defined by the caller and interprets the input that way (like protobuf). godot's native serialisation (the one bojidar wants to use) passes the format together with itself (like json).

**Comment by jrimclean** [comment]
So if I understand correctly, bojidar wants access to the raw data contained in a Variant represented as a RawArray?

**Comment by bojidar-bg** [comment]
@jrimclean Well, to some extend yes... but.. what is a Variant? Is it the format godot's binary serialization is based on, is it some kind of object, or what? :smile:  

In the best case, I want to be able to serialize any type of variable in godot, e.g. Vectors, numbers, arrays, dictionaries, etc.

**Comment by reduz** [comment]
not sure if a solution, but var2str and str2var in GDScript now conversion to text and back
