### ISSUE TITLE
Let the "Baked Lighting" node take sky lighting into account

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#20754]
Recently, I started experimenting with using the _Baked Lighting_ node to improve the lighting in my game in general. There is just one major issue that prevents it from being fully usable.

The game level being baked is largely outdoors with a few sheltered areas, and I noticed that the sky makes no contribution whatsoever to the result that pops out when the bake button is pressed.

I figured then that the lightmapping simply does not support it (at least I couldn't find an option anywhere that would allow for it otherwise). As a result, I'm placing a request for someone to let the sky become a contributor to the lighting solution (so as to have be able to have full lighting for indoor/outdoor scenes with solid transitions and full indirect lighting).

Is this practical to add?

**Comment by Calinou** [comment]
The upcoming [new lightmapper in Godot 4.0](https://godotengine.org/article/godot-40-will-get-new-modernized-lightmapper) takes sky lighting into account, closing.
