### ISSUE TITLE
Move input section in project.godot to the end of file

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20759]
**Godot version:**
3.1 

**Issue description:**
It is a bit annoying when you wanna check/change settings manually via project.godot and you must scroll through all [input] section to get to the some settings. 

It would be better to move the entire [input] section to the end of the file

**red line** - [input] section
**black line** - others settings

![aaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/41945903/43707093-720a3bda-9967-11e8-9e62-f45f05bae5af.png)

**Comment by akien-mga** [comment]
That's not possible, sections are ordered alphabetically.

But it should be less of a bother now, as `ui_*` actions with default values are no longer written to project.godot, only if modified.
