### ISSUE TITLE
Allow basic math operations in number fields of the inspector

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#20756]
**Godot version:**
3.1

**Issue description:**
Something I find extremely useful in the GIMP is that in number fields it is possible to do basic maths that update the field when it loses focus.

I find myself really missing this feature in Godot.

Example:
Inspect a Control in the Inspector and navigate to Min Size, the values are x: 380, y: 100

If I want to half the Min Size I would go to x and update it to read 380/2 and once the field loses focus it evaluates to 190. (So the new value is 190).

**Comment by KoBeWi** [comment]
I can confirm it no longer works in 3.1.

**Comment by eon-s** [comment]
On 2.1 was also possible to do things like `pow(some_number)`, that cannot be done on 3.0.

**Comment by Hinsbart** [comment]
Closing as duplicate of #18932
