### ISSUE TITLE
I cant apload publish my godot3 game to play store!! I use windows 10

### ISSUE THREAD

**Issue by baymefe** [godotengine/godot#20768]
I had made a game for android and I put some AdMob and then I exported the apk file. I tried it on my phone, it worked as well on others phone. When I tried to publish my app it gave an error "You have to cancel debug and you uploaded a file that was signed on debugging" I tried to uncheck the signed but it gave another error I also tried to turn off export with debugging but then it gave an error when it was exporting. Also, it says in comments after exporting that jarsigner signature does not include a timestamp. I have no idea what to do. I have been trying to solve this problem for two weeks but I  have done nothing. I am very sad and I can't find any documentation. PLEASE HELP :(

**Comment by eon-s** [comment]
This is a question more suited for the Q&A, open one there with more details about the error (which seems to be related to not exporting the game signed with release key).

https://godotengine.org/qa/

**Comment by groud** [comment]
Please ask this question on one of our [other community channels](https://godotengine.org/community), this is not an engine issue.
