### ISSUE TITLE
_input() of a Node2D is processed before "pressed" signal handlers of a Button

### ISSUE THREAD

**Issue by gber** [godotengine/godot#2076]
The _input() of a Node2D with input processing enabled seems to processed before any "pressed" signal handlers of a Button, the documentation at <https://github.com/okamstudio/godot/wiki/tutorial_input_events> suggests that GUI widgets handle input first before calling any _input() handlers.

**Comment by reduz** [comment]
kind of, it goes in tree order, but it affects the base controls first. I
wouldn't really expect any specific order for this stuff, are you trying to
do anything in particular?

**Comment by gber** [comment]
I use the left mouse button to trigger a shoot action (handled via _input() of a Node), however there is also a GUI Button to pause the game (both the Button and the Node are siblings and children of the root node of the scene). Clicking on the button to pause the game first triggers a shot before actually pausing which I'd like to avoid. So it would be nice if the GUI widgets were preferred and the event would not propagate to the _input() handler of the Node, that is what I was expecting based on your diagram on the above wiki page.

**Comment by reduz** [comment]
oh i see, use _unhandled_input then, so this way the GUI has priority. this
is the best way to get input in the game and also have the UI to get
priority

**Comment by gber** [comment]
OK, thanks for clarifying. I'll leave this open as a documentation issue in the ["How does it work"](https://github.com/okamstudio/godot/wiki/tutorial_input_events#how-does-it-work) section.

**Comment by akien-mga** [comment]
I don't see what needs to be fixed in the documentation: http://docs.godotengine.org/en/latest/tutorials/engine/inputevent.html#how-does-it-work
It makes it pretty clear that the order is: `Node._input()` -> `Control._input_event()` -> `_unhandled_input()`, i.e. `_input()` always has precedence over GUI elements.

**Comment by vnen** [comment]
The documentation *was* wrong, but it was fixed in https://github.com/godotengine/godot-docs/commit/dc6361ffd9c8b7fa5acebc64cb7f74de20d73c86

**Comment by akien-mga** [comment]
Ah nice :)
