### ISSUE TITLE
EditorSettings: dim_amount and dim_transition_time shown as modified even with default value

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20763]
**Godot version:**
3.1 b5a20d2

**Issue description:**
When I open editor settings first time(or with cleaned editor data) and i look into his settings, some properties do not look default.

**Steps to reproduce:**
1. Close Godot
2. Rename Godot Editor data folder (`%APPDATA%\Roaming\Godot` on Windows)
3. Create new project
4. Check editor settings

EDIT:
This picture shows what I saw when I open Godot Editor without any data. Look at the option "dim_amount" and "dim_transition_time", these settings don't look like default but when i click an arrow at left of value, value does't change.

EDIT2:
It also happens with:
Text Editor -> Completion -> code_complete_delay
Docks -> Scene Tree -> relationship_line_color
Editors -> 3d -> primary_grid_color
Editors -> 3d -> secondary_grid_color

![ssss](https://user-images.githubusercontent.com/41945903/43719715-bb1b5896-998e-11e8-829d-6c918572df9e.png)

**Comment by akien-mga** [comment]
CC @Hinsbart

**Comment by Hinsbart** [comment]
Fixed as of  a16d9c6a, likely via f2e54057aec3a4
