### ISSUE TITLE
setter sets the variable before calling the setter

### ISSUE THREAD

**Issue by KillerJaguar** [godotengine/godot#2077]
var variable= 0 setget _variable_set
    func _variable_set()
        print(variable)

The variable is set before the setter is called, making the setter useless for special set conditions. My use case is:

    func _dir_set(value):
        if dir != value:
            dir = value.normalized()
            emit_signal(SIGNAL_ANIMATE) # animator is only updated when direction is changed

The above code never emits because dir will always equal value.

**Comment by akien-mga** [comment]
Fixed by #2088.
