### ISSUE TITLE
Viewport doesn't show anything if set to never clear, unless it is told to clear once

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20775]
Godot 3.0.6
Windows 10 64 bits
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

I am trying to setup a simple scene for a shader feedback effect, with a viewport that always render and never clears so I can accumulate frames.
but found a number of confusing stuff.
First one is, my viewport doesn't show anything, no matter what I do. BUT, if I set it temporarily to `always clear`, then back to `never clear`, it works fine and starts accumulating frames.
Why is this happening? It's quite inconvenient for such a setup to happen.

Reproduction project:
[FeedbackViewportIssues.zip](https://github.com/godotengine/godot/files/2264444/FeedbackViewportIssues.zip)

1) Open main.tscn, you should normally see something but nothing is shown
2) Change the Viewport to `always clear`: boom, stuff is appearing
3) Change it back to its previous setting: all is fine now, but ideally we should not need to go through step 1 and 2 just to make this work... (and you have to redo this everytime you open the scene)

Edit: I'm told to use ClearOnce, but what is NeverClear for then? Why can't it simply work with NeverClear?

**Comment by KoBeWi** [comment]
Works correctly in 4e0f31a 
(although still broken in 3.2.2 rc2)
