### ISSUE TITLE
Default input map

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#20784]
I don't think the input map should be populated by default.  The user should be able to specify what they want without having to clear everything first.

**Comment by Calinou** [comment]
If it is not populated at all, then it becomes impossible to navigate GUIs using the keyboard or gamepads. So, no, you are not supposed to clear it either.

**Comment by Maykeye** [comment]
> You should not use them for gameplay.

@groud  Well, even  [the official tutorial](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html) suggest using them for gameplay,

Also input map editor does not encourage adding mappings so I don't like empty input map for practical reason.

Right now to add mapping, intuitive way is very inefficient and generally looks like this: first you enter "UP" as action name, press enter, move mouse across the whole screen down(as default ui actions take whole list), click plus, click Key, press arrow up, press enter to close dialog, swear, blame muscle memory(obviously pressing enter doesn't closes input key dialog), press up again, move mouse half way across the screen, click ok, move mouse other half way across the screen, type "DOWN", repeat.

So this requires pixel hunting(buttons are plenty and are small), moving mouse all over the screen and clicking several times to assign single key.

(Faster way requires resizing, repositioning window and adding all actions before adding keys to them)

IMHO it's better to have opposite of what op wants: either populate map with common actions or (even better) have the ability to load some presets(e.g. "arrows", "arrows+wasd" for left/up/down/right)

**Comment by groud** [comment]
> @groud Well, even the official tutorial suggest using them for gameplay,

Yeah, it helps going faster in the tutorial, but that's not how you should do it in a real game.
Maybe the tutorial should be modified actually.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/303, as feature proposals are now tracked in the Godot proposals repository.
