### ISSUE TITLE
Make default mesh materials more flat or less reflective.

### ISSUE THREAD

**Issue by Logmytech** [godotengine/godot#20782]
https://github.com/godotengine/godot/issues/20780

When Creating a cube mesh or others, the materials looks weird.

The cube reflects all the light like it is shiny and weird looking.

Cubes are generally used for floors, boxes or walls. None of these are metallic generally.

It is like niegther real nor good looking. If there were one and not the other it would be just preference.

For example Unity has better default materials.

Maybe it's time we changed the default materials to something that is not so shiny and more good looking.

**Comment by nunodonato** [comment]
its easy to change, perhaps to make things easier to discuss and evaluate, why dont you create a material that you think is nice as a default one, and then screenshot the differences and put it here so everyone else can have their say?

**Comment by CowThing** [comment]
Looks like the default editor material, the material that is used when no material is set on a mesh, has a roughness of 1 and a slightly grey color.
The default Spatial Material is white with a roughness of 0. I think the only thing that needs to be changed is the roughness. Using 0.5 or 1 would look better by default, I think.

![material](https://user-images.githubusercontent.com/11450875/43783005-a647916e-9a2e-11e8-9c74-5562a18e2d52.png)

**Comment by Logmytech** [comment]
@CowThing Your screenshot isn't showing the problem for some reason.

When I create a new cube and especially if it is set to red or blue, it acts like it is shiny like a mirror and even shows some of the sun some times.

**Comment by ConnorBP** [comment]
this still happens in 3.1 Any plans for 3.2 to fix this or do I have to recompile my editor just to change this. A setting to change the default values would be nice tbh so I don't have to de-shine stuff every time i place it in the world

**Comment by akien-mga** [comment]
This was fixed in the default environment, if you created yours before the change, it won't be modified. Check in a new projects and you should see the difference. You can then replace your default environment with the one from a new project.

> A setting to change the default values would be nice tbh so I don't have to de-shine stuff every time i place it in the world

You can change your default environment for that.

**Comment by ConnorBP** [comment]
> This was fixed in the default environment, if you created yours before the change, it won't be modified. Check in a new projects and you should see the difference. You can then replace your default environment with the one from a new project.
> 
> > A setting to change the default values would be nice tbh so I don't have to de-shine stuff every time i place it in the world
> 
> You can change your default environment for that.

thanks :)
