### ISSUE TITLE
Hotkey to search the hovered text in the help

### ISSUE THREAD

**Issue by robertdhernandez** [godotengine/godot#2078]
Coming from Game Maker, one of my favorite utilities was pressing middle mouse button on text to search it in the help screen. Shift+F1 does the same function, but having it bound to middle mouse button would be a much more major convenience.

**Comment by bojidar-bg** [comment]
I use middle mouse button for so many other things... like opening links, closing tabs, rotating/panning the view... I think that it will be better if it is modifier+middle mouse.

 :+1: for making workflow faster, BTW

**Comment by KillerJaguar** [comment]
Well in the code editor, you're not clicking on links or panning the view

**Comment by neikeq** [comment]
Middle click is used to paste text on Linux. It could be confusing.

**Comment by vnen** [comment]
I don't like this as it is not intuitive. I would never think in middle-clicking for seeing the reference. It might be a common way in Game Maker, but nowhere else, AFAIK. Also, when coding I'm usually far from the mouse, so a keyboard shortcut is faster than a mouse command.

A right-click context menu with such option among others would be better. But the major IDE way to do it is just to display the method reference in a small pop-up (activated by a keyboard shortcut).

**Comment by akien-mga** [comment]
See also the implementation proposal and discussion in #2112.

**Comment by akien-mga** [comment]
Fixed by 37f1e861 \o/

**Comment by neilw1** [comment]
As a new user coming from .net development, it would be nice if hover/autocomplete worked more like Visual Studio so that when you are over a method, if that method has a method comment then this is shown to provide quick contextual help. Having to press shift-f1 feels almost backward compared to most editors.
