### ISSUE TITLE
Error spam while searching in the "New Node" dialog while having scripts with "class_name"

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#20789]
**Godot version:**
 e0456f7

**Issue description:**
![peek 2018-08-07 15-00](https://user-images.githubusercontent.com/30739239/43793770-e4f07290-9a52-11e8-9a7c-7eff5f045404.gif)

**Comment by AlexHolly** [comment]
I am not able to reproduce works fine on x11.

**Comment by YeldhamDev** [comment]
@AlexHolly I'm using Manjaro, so it kinda doesn't.
