### ISSUE TITLE
Problem with the inspector' slider for Float values and ColorPicker in exported arrays

### ISSUE THREAD

**Issue by skgalaxy** [godotengine/godot#20795]
**Godot version:**

Master(3.1) a3bd9c2

**OS/device including version:**

Windows 7 Ultimate x64
OpenGLES 3.0: Intel <R> HD Graphics 4400

**Issue description:**

Before continuing with the development of my game, I have tried to play with the new inspector of the future version, trying to export different values. When testing the Arrays, I experimented with the data that could be put in the inspector. bool, int, string, float ... When I got to try the float type in the exported array, I tried to put the value with the keyboard. No problem. But when I tried to slide the mouse over the value of the float to change its value, the mouse pointer disappeared. I dragged in all directions and no trace of the mouse. And Godot did not respond. I just had to put Alt + F4.
I tried again, but with the Color type in a exported Array. When I click anywhere in the Color Picker, it disappears after set the color. Which causes you to have to click again on the color field to change the selected color.

**Steps to reproduce:**
Create a Node, Attach Script and create an export Array.
In the inspector, create a field for a float value and slide the mouse over the cell trying to change its value. Look with wide eyes!
Create another field (or change the type of the previous one) for a Color type, click and change the color by clicking on a point in the ColorPicker palette, trying to change a numeric value or trying to pull a slider. Look with wide eyes!

**Minimal reproduction project:**

[LaboApr.zip](https://github.com/godotengine/godot/files/2268318/LaboApr.zip)

**Comment by YeldhamDev** [comment]
Related to #19321.

**Comment by reduz** [comment]
This seems to be a Windows problem (does not happen on X11), I will give it a check there

**Comment by reduz** [comment]
Ok, this should be fixed thanks to the switch to raw input in #20523, plus some extra fixes I added.
