### ISSUE TITLE
[Mono] Godot freezes when loading a project

### ISSUE THREAD

**Issue by nathanjwtx** [godotengine/godot#20796]
**Godot version:**
3.0.6 Mono Stable

**OS/device including version:**
Windows 10 Pro GTX1050 Graphics i5 CPU

**Issue description:**
All my projects either freeze when trying open a scene or load but don't run correctly.

I tried deleting the mono folder from AppData with no luck. Mono log files are saying they can't find a file. Not sure if this is related to the issue or not.

```
Config attempting to parse: 'C:\Program Files\Mono\etc\mono\config'. (in domain Mono, info)
Image addref mscorlib[0000000012E043D0] -> C:/Godot306-C#/mscorlib.dll[0000000020845820]: 2 (in domain Mono, info)
Unloading image C:/Godot306-C#/mscorlib.dll [0000000020845F70]. (in domain Mono, info)
Image addref mscorlib[0000000012E05420] -> C:/Godot306-C#/mscorlib.dll[0000000020845820]: 4 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (C:/Godot306-C#/mscorlib.dll) (in domain Mono, info)
AOT: image 'C:/Godot306-C#/mscorlib.dll.dll' not found: The system cannot find the file specified.
 (in domain Mono, info)
AOT: image '**C:\Program Files\Mono\lib\/mono/aot-cache/amd64/mscorlib.dll.dll'** not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly mscorlib[0000000012E05420] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly mscorlib[0000000012E05420] added to domain GodotEngine.ToolsDomain, ref_count=2 (in domain Mono, info)
Image addref GodotSharpTools[0000000012E05810] -> C:/Godot306-C#/GodotSharpTools.dll[00000000208DC8C0]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotSharpTools' (C:/Godot306-C#/GodotSharpTools.dll) (in domain Mono, info)
Assembly GodotSharpTools[0000000012E05810] added to domain GodotEngine.ToolsDomain, ref_count=1 (in domain Mono, info)
Assembly mscorlib[0000000012E05420] added to domain GodotEngine.ScriptsDomain, ref_count=3 (in domain Mono, info)
Domain GodotEngine.ScriptsDomain search path is: (in domain Mono, debug)
	path[0] = '.' (in domain Mono, debug)
End of domain GodotEngine.ScriptsDomain search path. (in domain Mono, debug)
Assembly Loader probing location: 'C:\Program Files\Mono\lib\GodotSharp.dll'. (in domain Mono, info)
Assembly Loader probing location: 'C:\Godot306-C#\/Facades\GodotSharp.dll'. (in domain Mono, info)
Assembly Loader probing location: 'C:\Program Files\Mono\lib\GodotSharp.exe'. (in domain Mono, info)
```

Line in particular from above: C:\Program Files\Mono\lib\/mono/aot-cache/amd64/mscorlib.dll.dll'

**Comment by terids** [comment]
I have this issue also. Windows 10. Happened when adding an [Export] tag to a public Vector2 on a clean project (project was running perfectly fine before adding the [Export] tag.

C# projects now just fail to find the Godot namespace.

**Comment by akien-mga** [comment]
CC @neikeq @hpvb

Seems definitely Mono related but this is puzzling:
> Update: I had switched the graphics on my laptop from intel onboard to nvidia GTX1050 prior to this issue starting up. Switching it back made the issue go away. The nvidia GTX worked fine when running 3.0.5

**Comment by nathanjwtx** [comment]
I haven't had this issue since installing a new hard drive at the weekend and a fresh windows install.

**Comment by neikeq** [comment]
The mono log doesn't seem to imply anything wrong. Can you run Godot in verbose mode and paste the output here? (and a backtrace if there is a crash). Does this happen with any project (a new one, for example, with a hello world C# script)?

**Comment by nathanjwtx** [comment]
@neikeq it was happening with existing projects. From memory it worked ok when i tried a new project.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch or latest beta build?

**Comment by nathanjwtx** [comment]
Not sure. I'm on vacation till next weekend so I can try it when I get back.

**Comment by akien-mga** [comment]
I'll close for now as it's very likely to have been fixed in the last 6 months. Please comment if you can still reproduce it, and I'll reopen the issue.

**Comment by lanskey** [comment]
@akien-mga Issue still exists, i've recently downloaded the new version of godot (Godot_v3.1-beta9_mono_win64) and i have a problem with importing export template for android device. Even if it says its downloaded/installed godot displays the message "export templates for this platform are missing).

i'm attaching also the log file from mono logs
`Config attempting to parse: 'E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/etc\mono\config'. (in domain Mono, info)
Image addref mscorlib[000000000F71D620] (asmctx DEFAULT) -> E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll[000000000F877C40]: 2 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll) (in domain Mono, info)
AOT: image 'E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll.dll' not found: The system cannot find the file specified.
 (in domain Mono, info)
AOT: image 'E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/lib/mono/aot-cache/amd64/mscorlib.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly mscorlib[000000000F71D620] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly mscorlib[000000000F71D620] added to domain GodotEngine.ToolsDomain, ref_count=2 (in domain Mono, info)
Image addref GodotSharpTools[000000000F71E160] (asmctx DEFAULT) -> E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Tools/GodotSharpTools.dll[000000000F90E090]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotSharpTools' (E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Tools/GodotSharpTools.dll) (in domain Mono, info)
Assembly GodotSharpTools[000000000F71E160] added to domain GodotEngine.ToolsDomain, ref_count=1 (in domain Mono, info)
Assembly mscorlib[000000000F71D620] added to domain GodotEngine.ScriptsDomain, ref_count=3 (in domain Mono, info)
GC_MAJOR: (user request) time 0.24ms, stw 0.25ms los size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR_SWEEP: major size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR: (user request) time 0.09ms, stw 0.11ms los size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR_SWEEP: major size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR: (user request) time 0.13ms, stw 0.14ms los size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR_SWEEP: major size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR: (user request) time 0.12ms, stw 0.17ms los size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR_SWEEP: major size: zdK in use: zdK (in domain Mono, info)
GC_MINOR: (user request) time 0.14ms, stw 0.18ms promoted zdK major size: zdK in use: zdK los size: zdK in use: zdK (in domain Mono, info)
Unloading domain GodotEngine.ScriptsDomain[000000000F8D9FA0], assembly mscorlib[000000000F71D620], ref_count=3 (in domain Mono, info)
GC_MAJOR: (user request) time 0.11ms, stw 0.15ms los size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR_SWEEP: major size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR: (user request) time 0.16ms, stw 0.19ms los size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR_SWEEP: major size: zdK in use: zdK (in domain Mono, info)
Unloading domain GodotEngine.RootDomain[000000000F8739C0], assembly mscorlib[000000000F71D620], ref_count=2 (in domain Mono, info)
Assembly image 'E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Tools/GodotSharpTools.dll' still loaded at shutdown. (in domain Mono, info)
Assembly image 'E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll' still loaded at shutdown. (in domain Mono, info)
`
Also on the same machine i've tested the same version of godot without mono and everything seems to work (it successfully installed the export template).

My machine:
Graphic Card: GTX 980
CPU: i5 4750k
System: Windows 10
Mono and gtk: mono-5.18.0.268-x64-0, gtk-sharp-2.12.45

If you'd need some more information just let me know, happy to help.

**Comment by akien-mga** [comment]
This has nothing to do with this issue.
And the Mono version doesn't support Android yet.

Le samedi 2 mars 2019, Emanuel Slotwinski <notifications@github.com> a
écrit :
> @akien-mga Issue still exists, i've recently downloaded the new version
of godot (Godot_v3.1-beta9_mono_win64) and i have a problem with importing
export template for android device. Even if it says its
downloaded/installed godot displays the message "export templates for this
platform are missing).
>
> i'm attaching also the log file from mono logs
> Config attempting to parse:
'E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/etc\mono\config'. (in
domain Mono, info) Image addref mscorlib[000000000F71D620] (asmctx DEFAULT)
->
E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll[000000000F877C40]:
2 (in domain Mono, info) Prepared to set up assembly 'mscorlib'
(E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll)
(in domain Mono, info) AOT: image
'E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll.dll'
not found: The system cannot find the file specified. (in domain Mono,
info) AOT: image
'E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/lib/mono/aot-cache/amd64/mscorlib.dll.dll'
not found: The system cannot find the path specified. (in domain Mono,
info) Assembly mscorlib[000000000F71D620] added to domain
GodotEngine.RootDomain, ref_count=1 (in domain Mono, info) Found assembly
remapping for mscorlib and was for the same version 4.0.0.0 (in domain
Mono, debug) Assembly mscorlib[000000000F71D620] added to domain
GodotEngine.ToolsDomain, ref_count=2 (in domain Mono, info) Image addref
GodotSharpTools[000000000F71E160] (asmctx DEFAULT) ->
E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Tools/GodotSharpTools.dll[000000000F90E090]:
2 (in domain Mono, info) Prepared to set up assembly 'GodotSharpTools'
(E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Tools/GodotSharpTools.dll)
(in domain Mono, info) Assembly GodotSharpTools[000000000F71E160] added to
domain GodotEngine.ToolsDomain, ref_count=1 (in domain Mono, info) Assembly
mscorlib[000000000F71D620] added to domain GodotEngine.ScriptsDomain,
ref_count=3 (in domain Mono, info) GC_MAJOR: (user request) time 0.24ms,
stw 0.25ms los size: zdK in use: zdK (in domain Mono, info) GC_MAJOR_SWEEP:
major size: zdK in use: zdK (in domain Mono, info) GC_MAJOR: (user request)
time 0.09ms, stw 0.11ms los size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR_SWEEP: major size: zdK in use: zdK (in domain Mono, info)
GC_MAJOR: (user request) time 0.13ms, stw 0.14ms los size: zdK in use: zdK
(in domain Mono, info) GC_MAJOR_SWEEP: major size: zdK in use: zdK (in
domain Mono, info) GC_MAJOR: (user request) time 0.12ms, stw 0.17ms los
size: zdK in use: zdK (in domain Mono, info) GC_MAJOR_SWEEP: major size:
zdK in use: zdK (in domain Mono, info) GC_MINOR: (user request) time
0.14ms, stw 0.18ms promoted zdK major size: zdK in use: zdK los size: zdK
in use: zdK (in domain Mono, info) Unloading domain
GodotEngine.ScriptsDomain[000000000F8D9FA0], assembly
mscorlib[000000000F71D620], ref_count=3 (in domain Mono, info) GC_MAJOR:
(user request) time 0.11ms, stw 0.15ms los size: zdK in use: zdK (in domain
Mono, info) GC_MAJOR_SWEEP: major size: zdK in use: zdK (in domain Mono,
info) GC_MAJOR: (user request) time 0.16ms, stw 0.19ms los size: zdK in
use: zdK (in domain Mono, info) GC_MAJOR_SWEEP: major size: zdK in use: zdK
(in domain Mono, info) Unloading domain
GodotEngine.RootDomain[000000000F8739C0], assembly
mscorlib[000000000F71D620], ref_count=2 (in domain Mono, info) Assembly
image
'E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Tools/GodotSharpTools.dll'
still loaded at shutdown. (in domain Mono, info) Assembly image
'E:\GODOT\Godot_v3.1-beta9_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll'
still loaded at shutdown. (in domain Mono, info)
> Also on the same machine i've tested the same version of godot without
mono and everything seems to work (it successfully installed the export
template).
>
> My machine:
> Graphic Card: GTX 980
> CPU: i5 4750k
> System: Windows 10
> Mono and gtk: mono-5.18.0.268-x64-0, gtk-sharp-2.12.45
>
> If you'd need some more information just let me know, happy to help.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/OdJgkTA67XEgdIcGM0uDoH_wxZDWF07A5URgcJQf1mhmMJ1AT6-BahlgQhgUwFI4V1UKuPpSXa07QSfmocFV2uUJcbqB-l5Doqv-LN6c-VMBp19zFAEUba1e-1RNZT86c_cILP7ADALZgqHN78E3ENCzhg=s0-d-e1-ft#https://github.com/notifications/beacon/AEe8mns48J3hxYvlbYzGuy4Y0wxL-ELiks5vSnp_gaJpZM4VzBm2.gif>
