### ISSUE TITLE
Particle mask importer generates a bad resource.

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#20800]
**Godot version:** 619ba7
**OS/device including version:** Debian SID
**Issue description:**
The Particles2D emission mask importer creates an ImageTexture resource with an Image as a sub-resource, but forgets to reference it.

**Steps to reproduce:**

1. Create a Particles2D with the default ParticlesMaterial, and assign an emission mask to it.
2. Edit the generated emission mask, and save it as .tres. If you try to edit the mask image, Godot will crash.
3. Edit the .tres file with a text editor. The resource has an Image sub-resource, but the resource image property is set to null.

**Comment by KoBeWi** [comment]
Opening the tres file no longer crashes the editor since 3.1. I don't think you are supposed to save the texture to file, the texture gets saved as Image resource, which can be then loaded into ImageTexture's `image` property. So I think this is resolved.
