### ISSUE TITLE
FileDialog doesn't display directory content until refresh

### ISSUE THREAD

**Issue by godot999** [godotengine/godot#20809]
**Godot_v3.0.5-stable_x11.64, Linux PC**

_FileDialog_ doesn't display the directory content until refreshed. This happens both while editing it in the editor and while running.

Steps:
Create a FileDialog manually using the editor, setting the directory path.
In the code, make it visible. The dialog appears, the directory is correct, but its content is not shown.

Workaround:
Set the directory path again, but this time via code.

**Comment by godot999** [comment]
This happens with _EditorFileDialog_ too.

**Comment by godot999** [comment]
In the case of _EditorFileDialog_, the workaround is:
`dialog.visible = true`
`dialog.invalidate() # force refresh`

**Comment by char0xff** [comment]
Looks like __post_popup()_ was never called.

**Comment by reduz** [comment]
file dialog is here:
https://github.com/godotengine/godot/blob/master/scene/gui/file_dialog.cpp

**Comment by char0xff** [comment]
@reduz Yes but the problem was that __post_popup()_ of _scene/gui/popup.cpp_ (from which _FileDialog_ inherits) was never called, so _file_dialog.cpp_ didn't received the notification that it was popped up / visible.
See my attempt at fixing: #21413

**Comment by reduz** [comment]
Oh, I See, this is not a bug, you need to call popup() for popup dialogs to work correctly. I think this is a documentation problem if you misunderstood this.
