### ISSUE TITLE
Running a script gives a nice, magical screen

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#2081]
Using the instructions in https://github.com/okamstudio/godot/wiki/command_line#running-a-script I get a magenta (magical pink) window (The scripts does run nevertheless). I think that the window is not needed at all, and it will be better if no window is opened when godot runs with the -s flag... (or maybe a --no-gui flag? :smile: )

OS: Ubuntu-gnome 14-10
GODOT: master

**Comment by captainwasabi** [comment]
-quiet -nowindow

**Comment by bojidar-bg** [comment]
@captainwasabi nope, doesn't work...

**Comment by punto-** [comment]
There's no reason to assume that your script will not try to use graphics,
your script is actually capable of running a whole game (it just provides
an implementation of MainLoop). The "server" platform (which compiles only
for linux at the moment, but should be too hard to port) provides a
headless implementation that won't open a window.

**Comment by captainwasabi** [comment]
Just more FYI.  On Windows (8.1) using the example from the wiki, https://github.com/okamstudio/godot/wiki/command_line#running-a-script, using both -silent -nowindow looks like it does run, but nothing prints but engine debug stuff.  If I just run with -nowindow it works fine (although I wish there was a way to suppress the engine debug stuff, i.e.

    EXEC PATHP: C:\Projects\Games\Godot\godot_win64.exe
    EXEC PATHP: C:\Projects\Games\Godot\godot_win64.exe
    DETECTED MONITORS: 1
    Hello!
    freed code id 1
    ERROR: free_static:  Condition ' !MemoryPoolStatic::get_singleton() ' is true.
    At:  core/os/memory.cpp:58

**Comment by bojidar-bg** [comment]
@punto-  nice to know... :smile: Maybe when we are able to have many game windows, it will be simpler to do this things...

**Comment by akien-mga** [comment]
@bojidar-bg What's the status on this issue?

**Comment by bojidar-bg** [comment]
@akien-mga There is still no way to make a script run without a window in non-server versions. The best workaround would be:

````sh
godot.dbg -r 1x1 -w  -s <path/to/script.gd>
````

Anyway, it would now display the splash screen, or "nothing", but it would not display pink. So, I guess it might be closeable, but we would need a multiwindow support issue, and/or a nowindow support issue.

**Comment by hubbyist** [comment]
I encountered this issue when developing algorithm for https://github.com/godotengine/godot/issues/9264#issuecomment-311601979.

So a quiet mode for `godot -s` command will be useful I think.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/198.
