### ISSUE TITLE
FileDialog has old theme

### ISSUE THREAD

**Issue by godot999** [godotengine/godot#20810]
**Godot_v3.0.5-stable_x11.64, Linux PC**

_FileDialog_ has the old Godot theme, the one in violet, instead of the one in blue.

**Comment by MarianoGnu** [comment]
If i'm correct, that's because the theme on the Editor is not the default theme for games, the default theme for games is the old one

**Comment by godot999** [comment]
However, you see, I'm making a plugin that works inside the Godot Window. So I was expecting that the FileDialog would have the same theme of Godot Editor.

**Comment by MarianoGnu** [comment]
It should inside editor, you can use EditorFileDialog in a plugin too (but you have to instance it by code, you can't add it with the editor)

**Comment by MarianoGnu** [comment]
do you mind sharing an screenshot?

**Comment by godot999** [comment]
Oh, so inside the editor you are supposed to use _EditorFileDialog_... I was using _FileDialog_ instead.
My bad then.
Still, I don't seem to be able to use it. I do `dialog.visible = true` but it doesn't appear.

**Comment by MarianoGnu** [comment]
any parent node that is part of your custom plugin editor, it's a popup so as long as you show it using the popup functions it will work as expected

**Comment by godot999** [comment]
Not a bug.
