### ISSUE TITLE
Sprites doesn't fit the bounds. Endless redrawing.

### ISSUE THREAD

**Issue by Maxsior** [godotengine/godot#20818]
**Godot version:**
Godot_v3.0.6-stable_mono_win64 & Godot_v3.0.6-stable_win64

**OS/device including version:**
Windows 10 64-bit
AMD Radeon R5 M430, AMD Radeon R5 Graphics

**Issue description:**
Sprite doesn't fit the bounds.
Redrawing indicator rotates permanently. Sprite blinks. It disapears and apears with correct size, and all repeats...
![screenshot_1](https://user-images.githubusercontent.com/9255915/43859539-5a947b00-9b6a-11e8-84ff-3d2ff13ec5e6.png)

**Steps to reproduce:**
Drag'n'drop sprite to scene...

**Comment by Maxsior** [comment]
I'm fix this problem to reinstall AMD Radeon Graphics drivers

**Comment by Maxsior** [comment]
Problem has been fixed with reinstalling AMD Radeon Graphics drivers

**Comment by Maxsior** [comment]
The problem was fixed by reinstalling AMD Radeon Graphics drivers

**Comment by Chaosus** [comment]
Please close the issue if its fixed
