### ISSUE TITLE
FileDialog.dialog_hide_on_ok has no effect and is not "On" in the GUI editor

### ISSUE THREAD

**Issue by godot999** [godotengine/godot#20817]
Godot_v3.0.5-stable_x11.64, Linux PC

_dialog_hide_on_ok_ in _FileDialog_ has no effect, both via the editor and via code. Whatever the variable is, the dialog always close/hide after clicking the confirmation button.

Also, the property is not "On" ("true") by default in the GUI editor, even though the description says it is.

**Comment by akien-mga** [comment]
Fixed by #21053.
