### ISSUE TITLE
Autocomplete for $ syntax sugar does not see children if "" are used.

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#20811]
**Godot version:**
3.0.6

**OS/device including version:**

Windows 7 Pro SP1

**Issue description:**
Autocomplete does not recognize node's children if i use quotation after dollar. It does, however, if only dollar is used.

**Steps to reproduce:**
Open Node.gd script, put your cursor at the end of line with '$"' and trigger autocomplete.

**Minimal reproduction project:**
https://github.com/hilfazer/Projects/tree/EngineIssues/Godot/DollarAutocomplete

**Comment by hilfazer** [comment]
I've got a fix for this bug. Do i need to be assigned to it first or can i just issue a pull request?

**Comment by Zireael07** [comment]
Just make a PR.
