### ISSUE TITLE
Debugger catches breakpoint before 'for' loop completed its iterations

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#20815]
**Godot version:**

3.0.6

**OS/device including version:**

Windows 7 Pro SP1

**Issue description:**

Breakpoint was caught after one out of three 'for' loop's iterations. Expected it to be caught after all three.

**Steps to reproduce:**
Open Node.gd and place breakpoint at 'pass'. Run project and look at Console output.

**Minimal reproduction project:**

https://github.com/hilfazer/Projects/tree/master/Godot/EngineIssues/DebuggerCatchesBreakpointTooSoon

**Comment by ThakeeNathees** [comment]
seems like fixed

**Comment by akien-mga** [comment]
> seems like fixed

In which version(s)?

**Comment by ThakeeNathees** [comment]
> In which version(s)?

v3.2.1-stable debugger working as expected

**Comment by akien-mga** [comment]
Thanks, closing as fixed then.
