### ISSUE TITLE
Attach a note/comment to a node

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#2082]
I'd like to be able to attach a note to any node in the editor.

**Comment by unfa** [comment]
Could you elaborate a bit? Do you mean parenting node A to another node B or maybe continuously copying the location/rotation/scale from node B to node A without making node A child of node B?

Could you describe what are you trying to achieve?

**Comment by captainwasabi** [comment]
a text note.

Like "this needs to link to that and the other thing" or "This node is a collection of particle systems that the particle system manager uses for scoring effects" etc.

I think maybe you commented to the wrong issue ;)

**Comment by unfa** [comment]
Oh. I read "attach a NODE to a NODE" sorry.

Now I realized it's "NOTE to a NODE". My bad, nevermind.

**Comment by punto-** [comment]
Nodes (and all Objects) have metadata, you can use set_meta() and
get_meta() on them. This is more like an interface issue tho, it would be
nice to have something to inspect and edit the metadata..

**Comment by captainwasabi** [comment]
that would work, if there was an interface.  I'm a programmer and I want to be able to set up the scripts to work with the game/asset structure I want.  Then I want to be able to hand it over to the artists and let them fill in the content.  But they are going to need hints (and I don't really want to have nodes named "Add particle systems used for hits here" because then I have to use  that name in the code.  It's certainly not that big of a deal, I will be generating printed docs for them to use anyway.

**Comment by lorenzobeccaro** [comment]
Notes can be useful when assets exchange will be available. So you could upload a *.scn file without instructions in other text files!

**Comment by unfa** [comment]
Now I get the point. Something like a viewable text hint?

**Comment by vichug** [comment]
What about using empty attached script files, with commented out lines as notes ?..

**Comment by unfa** [comment]
I think we might need a mockup to get these ideas ironed out.

**Comment by captainwasabi** [comment]
I would prefer my artists NOT even look at the scripts ;)

Ideally, this could be the "tooltip" that the editor uses in the scene tree.

**Comment by trollworkout** [comment]
comments not notes. each node can have 1 comment stored inside the node as metadata. could be handy for teamwork passing a file around. you could have a note button before the visible/hidden  icon that pulls out the comment textbox or when the node graph is implemented you could have comments show up there. alternatively mouse over a node shows comment text.

**Comment by trollworkout** [comment]
this could also be useful for developers to leave quick dirty messages to artists by setting default node comments to something informative like "this not is not fully implemented yet do not use" so you don't need to change help all the time.

**Comment by akien-mga** [comment]
That's a cool idea! I slightly edited the title to make it clearer, as I also misread "attach a node to a node" like @unfa :P

**Comment by PlanetKiller** [comment]
I'd like to attach meta data to nodes within the editor. It would be like Blender's properties. You could also create a meta data node to access properties/values within the game. This idea could be useful for a variety of applications. Although I'd like to be able to add multiple metas to a node.

**Comment by Sslaxx** [comment]
[As asked to by @vnen on #5992 -]

Having comments on a node might be useful for projects (perhaps larger ones in particular?) where you may not necessarily remember what a node is for, why it's there etc. So if nodes have comments that you can set in the Inspector (and then see by hovering over their entries in the Scene panel), that might be of use?

Please excuse the awful editing, but hopefully these help get my point across?

![node_comment_2 png](https://cloud.githubusercontent.com/assets/324679/17279872/77243b12-5778-11e6-9617-08dc29a15ea5.png)
 ![node_comment_1 png](https://cloud.githubusercontent.com/assets/324679/17279871/771299c0-5778-11e6-8964-8f59d2c2b3b2.png)

**Comment by bojidar-bg** [comment]
@Sslaxx Also, an icon in the Scene dock (like the script icon, or signal/group icon) that it has a comment would be pretty nice.

**Comment by Sslaxx** [comment]
Bump. Will 3.0 add any functionality for this?

**Comment by reduz** [comment]
it's not a bad idea at all, documenting your scenes
lets think a bit better how this can be edited and displayed

**Comment by Sslaxx** [comment]
Any progress?

**Comment by girng** [comment]
godot already has a WYSIWYG like editor, which is amazing in and of itself. with proper naming of nodes, and visualization, the likelihood of needing sticky notes all over one's scene is/should be greatly diminished

**Comment by Sslaxx** [comment]
Nobody's suggested "sticky notes" that would be "all over one's scene"? Note that this issue suggests using tooltips (i.e., they'd only appear when said node or whatever is being hovered over by the mouse cursor).

**Comment by girng** [comment]
> Nobody's suggested "sticky notes" that would be "all over one's scene"?

that's from what i got from all the screenshots regarding this suggestion

**Comment by captainwasabi** [comment]
Well, it's kind of implied by marking #24762 as a duplicate of this one, which IS about that.  I left a comment over there stating that I didn't think that was a dupe of this suggestion.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
I was thinking . Could it be possible to add the comment both via the editor under Node perhaps have a Comment box similar to Hint->Tooltip and from script  something like `self.comment = "leave a comment here`" ?  In both cases when you mouse over you see it right in the editor . Perhaps even add a new icon beside script (a tiny paper note) or the Node name is highlighted with different color.
