### ISSUE TITLE
Debugger reports wrong error line

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20820]
**Godot version:**
3.0/3.1-dev

**Issue description:**
Godot sometimes highlights wrong line when error happens. It's always the previous non-empty line and probably has something to do with inline code blocks (e.g. single-line if with statement).
![image](https://user-images.githubusercontent.com/2223172/43863833-319c7ea2-9b5e-11e8-9358-a7d8e5b2f515.png)
That's the isolated case I managed to reproduce the issue, but it might appear on other occasions too. Maybe.

In the given example, if you put any non-empty line (like another print etc.) between the if line and error line, debugger will show it correctly.
![image](https://user-images.githubusercontent.com/2223172/43864008-b6a736b4-9b5e-11e8-998d-f4b886b1d450.png)

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2271988/TestProject.zip)

**Comment by rogeriodec** [comment]
Same here (3.2 dev, Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K):

![image](https://user-images.githubusercontent.com/11199752/55695992-6750f680-5991-11e9-8196-5a44469a6ca1.png)

**Comment by akien-mga** [comment]
Still reproducible in the current master branch (41c8ec99).

**Comment by KoBeWi** [comment]
Fixed in 4.0-dev
