### ISSUE TITLE
Obj importing materials with wrong roughness

### ISSUE THREAD

**Issue by Juankz** [godotengine/godot#20824]
**Godot version:**
3.0.x and master branch

**OS/device including version:**

Solus OS

**Issue description:**

My use case: For fast prototyping I like to use premade 3D models, most of them from itch.io and kenney.nl

Most of this models come in OBJ format. And as far as I've seen all OBJ models I've used are imported way too metallic. Here you can see the OBJ imported by Godot on the left and a DAE exported with blender on the right.

![godot_obj](https://user-images.githubusercontent.com/18577412/43877616-975fbf5e-9b60-11e8-8586-9e63f630d72d.png)

 And just for sake of comparison, the same OBJ imported in Unity3D.

![unity_obj](https://user-images.githubusercontent.com/18577412/43877661-d05d1a54-9b60-11e8-9743-7326fedc765d.png)

Now as I said this is just for prototyping and usually for production one can really tweak what is needed on blender. But this could be an issue for newcomers and sometimes is really not cool:

![worst_case](https://user-images.githubusercontent.com/18577412/43878186-71abef96-9b63-11e8-8e24-296892c47a6f.png)

**Minimal reproduction project:**

[obj_import_test.zip](https://github.com/godotengine/godot/files/2272785/obj_import_test.zip)

**Comment by bojidar-bg** [comment]
~~You don't like metallic trees?~~
Just to make sure, is this fixed by #20787? (we merged about 6 hours before this issue was opened)

**Comment by Juankz** [comment]
~Actually metallic trees sounds like a good game theme~
Yes it has been fixed. We can close this. Thank you :)
