### ISSUE TITLE
Rotating controls and scrolling by script in ScrollContainer + HBoxContainer

### ISSUE THREAD

**Issue by ChrisWhatever1980** [godotengine/godot#20829]
**Godot version:**
v3.1.dev.custom_build.b5a20d2

**OS/device including version:**
Windows

**Issue description:**
I created a button list using a HBoxContainer inside a ScrollContainer. Per script I add a new TextureButton to the list every time the first button in the list is pressed. The new button is supposed to be rotated randomly using
`newButton.set_rotation(deg2rad(randi() % 4 * 90.0))`
However, the rotation is not performed. 
I connect the pressed signal to rotate the new button when it is clicked. Now the rotation is performed.
However, when another button is added all button rotations reset to 0.
Finally, the scroll container is supposed to keep the add button visible by scrolling to the end of the list with
`scroller.call_deferred("set_h_scroll", -list.get_rect().position.x)`	
which does not happen.

**Steps to reproduce:**
Run the attached project.
Click the + button.
New buttons are added, which are not rotated.
Click the created buttons to rotate them.
Add another button. The rotation of the buttons is reset.
Fill the list with buttons until the add button moves outside the visible area. The list is not scrolled.

**Minimal reproduction project:**
[GUITest.zip](https://github.com/godotengine/godot/files/2273371/GUITest.zip)

Thanks! Let me know if you need more information.

**Comment by groud** [comment]
When I control node is a child of a container, it's size and position are handle by the container.
Put it in a normal node instead.

**Comment by groud** [comment]
Closing as this is a usage problem. 
Note that children of containers are no more selectable now, so things are more obvious now.
