### ISSUE TITLE
timer timeout signal

### ISSUE THREAD

**Issue by torohaifisch** [godotengine/godot#20827]
**Godot version:**
3.0 stable

**OS/device including version:**
windows 10

**Issue description:**

shouldnt timer timeout signal trigger only once when the timer reaches 0 instead of continuously triggering?

**Comment by Noshyaar** [comment]
It should, if you set `one_shot = true`. Please include your reproduction steps.

**Comment by torohaifisch** [comment]
ah yes you are right, i didnt check the tooltip as i thought one shot meant something else, the name wasnt clear enough for me. i find a little odd as when i think in a timer that countsdown i dont expect something that restarts over and over again by default

**Comment by Noshyaar** [comment]
We'll leave the default value to `one_shot = false` for now as there's not much demand to change and it'd be compatibility breaking otherwise. Also, recurrent timer has many uses in game development. (e.g. object spawning)
