### ISSUE TITLE
Enhancement and input map bug

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#20836]
**Godot version:**
v3.1.dev.calinou.9bd5315

**OS/device including version:**
windows 10 x64

**Issue description:**
1)On the input map deadzone click any up or down will close the editor , and the slider under the number not working.

2)In visual script area : if there is a possibility to focus the editor on the node where the error occures and mark the node visualy.

3)In 3d view and 2d view and visual script area :If there is a possibility to make pan with right mouse button instead of middle button or make option to change the button of pan.

4)Particles : need a wizard dialog or library of templates.

**Steps to reproduce:**
project > project settings > input map > click on any deadzone up or down.

**Comment by Calinou** [comment]
As per the [contributing guidelines](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs-or-proposing-features), please open one issue per bug report or suggestion.

**Comment by sami8github** [comment]
Ok thanks , I will open issue for each one.
