### ISSUE TITLE
Stopped Profiler still show graph after clearing

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20830]
**Godot version:**
3.1 9bd5315

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
When game is launched(to see the graph), need to start, wait a moment and stop Profiler and click to Clear button. Graph still is visible even left panel was cleared. This only happens when Profiler is stopped.

https://streamable.com/iq2im

**Comment by scayze** [comment]
was fixed by 92a9a8969dc97cd6b4028f8164c96316af23da10
