### ISSUE TITLE
FileDialog "access" member doesn't work: you can always navigate the entire filesystem

### ISSUE THREAD

**Issue by godot999** [godotengine/godot#20833]
**Godot_v3.0.5-stable_x11.64, Linux PC**

FileDialog's and EditorFileDialog's **_Access (access)_** member doesn't work correctly.
It **does** change what is displayed in the text edit "Path", e.g. _ACCESS_RESOURCES_ shows "res://", while _ACCESS_USERDATA_ shows "user://".
**However**, by navigating up to the above levels with the up arrow button, you can reach any part of the filesystem up to the root ("/").

**Comment by reduz** [comment]
This was working and broke at some point...

**Comment by akien-mga** [comment]
Fixed by 8ba0d513f.
