### ISSUE TITLE
Feature request particles wizard or templates

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#20847]
**Godot version:**
v3.1.dev.calinou.1800664

**OS/device including version:**
windows 10 x64

**Issue description:**
Particles need a wizard dialog or library of templates.

**Comment by vnen** [comment]
Not sure what a wizard would do in this case. As for templates, it should be provided by the Asset Library. I guess we could have some official samples, but most could be made by the community.

**Comment by sami8github** [comment]
OK ,some presets will be very good

**Comment by akien-mga** [comment]
I agree too, particle templates can be provided easily via the asset library.
