### ISSUE TITLE
Occlusion offset set incorrectly in Tilemap

### ISSUE THREAD

**Issue by KeithArch** [godotengine/godot#20840]
**Godot Version**
 3.0.6

**OS/device including version:**
Windows 10/Dell XPS 1 27: GPU GT Nvidia GeForce 640M

**Issue description:**
When creating a tileset from a png file if the resulting tilemap is set to autotile the property occlusion offset is set to the centre of the tilemap. That is to say that if the png is 1728x1280 pixels and the region
property is (0,0,1728,1280) the occlusion offset is (864, 640).  This causes occlusion shadows to be offset by this value from the element throwing the shadow and in most cases for the shadow to be outside the viewport. To work correctly for most cases the occlusion offset should be set to (0,0).  The problem is easily corrected by setting the offset to (0,0) but it is difficult to realise this if the user is unaware of the cause of the problem.

**Steps to reproduce:**
Create a tilemap from a png file.
Addit it to a scene and convert it to an an auto tile.
Use the tilemap to create objects in the scene via autotile.
Set occlusion on the autotile.

**Minimal reproduction project:**
[Occlusion problem.zip](https://github.com/godotengine/godot/files/2273997/Occlusion.problem.zip)

**Comment by KoBeWi** [comment]
I think this was solved by the new TileSet editor in 3.1.
@KeithArch Can you check if it's still a problem in 3.2.1?

**Comment by KeithArch** [comment]
Very sorry, but I haven't used Godot in quite some time, and the particular project where encountered the error is no longer available.  So I can't easily recreate the error and check if it is still a problem.  I am happy to accept that it is fixed from my point of view, if you want to close the bug report.

**Comment by KoBeWi** [comment]
Ok, thanks for response.
