### ISSUE TITLE
VisualScript editor: highlight node on error

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#20845]
**Godot version:**
v3.1.dev.calinou.1800664

**OS/device including version:**
windows 10 x64

**Issue description:**
In visual script area : if there is a possibility to focus the editor on the node where the error occurs and mark the node visualy.

**Comment by bojidar-bg** [comment]
Quite a bit of time passed.. Is this issue still valid on master?

I think I've some highlights of erroring nodes in VisualScript, but I might be wrong.

**Comment by sami8github** [comment]
tested on 3.1.beta.calinou.ffd4453 build 05/03/19 its working like charm
