### ISSUE TITLE
Missing translation for menu items

### ISSUE THREAD

**Issue by gotnospirit** [godotengine/godot#20853]
**Godot version:**
a71a5fc0
v3.1.dev.custom_build

**OS/device including version:**
Windows 10

**Issue description:**
"Open Project Data Folder" and "Open Editor Data/Settings Folder" menu items are not translated (at least for FR and DE) and can't be found on hosted.weblate.org

**Comment by Noshyaar** [comment]
These items have `TTR` already.

cc: @akien-mga  :)

**Comment by akien-mga** [comment]
Translation templates from the *master* branch are not on Weblate yet, it's still tracking the *3.0* branch. I'll soon do the change (we can only have one version there, so once it's master strings, we can no longer update 3.0 translations).
