### ISSUE TITLE
Sprite3D and AnimatedSprite3D is rendering very slow (fixed in `3.x`, not in `master` yet)

### ISSUE THREAD

**Issue by i-void** [godotengine/godot#20855]
I tried so much variations with/without shading with gdScript, nativeScript (Nim) and different import settings without luck. One archer walk animation, with 8 frame costs 14 fps (reduced to 46fps) . It slows to 19-20fps when I exported it to android also. I'm adding screen shots from my computer with GeForce 940MX screen card (I can play Anno 1404 without any lag with this screen card). 

I have only `one` archer on the screen, and I scripted with nim (very fast programming language). I supposed in this example I made the fastest things I can do. If not please share my mistake.

Version: Godot 3.0
System: Linux Manjaro (ArchLinux derive)
Frame rate drops too much (14fps for only one node). I expect it to work with 60fps. 

Screen shots:
![animation](https://user-images.githubusercontent.com/5237679/43920092-a15685fe-9c20-11e8-8a57-239ac5255ed6.png)
![code](https://user-images.githubusercontent.com/5237679/43920093-a177e1fe-9c20-11e8-96bd-6871f0d70329.jpeg)
![import-settings](https://user-images.githubusercontent.com/5237679/43920094-a198425a-9c20-11e8-8963-ecf67224d97b.png)
![screen1](https://user-images.githubusercontent.com/5237679/43920095-a1b88844-9c20-11e8-9d90-2f4efedd961a.jpeg)

I have only one scene as Archer and I'm using a sprite image only. Nothing more.

**Comment by semirix** [comment]
I've experienced this as well. After removing them all and replacing with MeshInstance planes, FPS returned to normal.

**Comment by usbhell** [comment]
I've noticed this also on 3.1, quite bad fps on 2 android devices I tried (GLES2) with just a couple of sprite3d's. If I use the builtin quadmesh instead to display my texture the fps is perfectly fine.

**Comment by Toshiwoz** [comment]
Same here, I had to get rid of them, and now I know what to use in replacement.
I've taken a bit of my time to make a sample project, that, if you run on pc, it doesn't make a huge difference, but as you export to a mobile you can see the incredible difference.
On my MYA-L11 I can run at 50+fps more than a hundred plane meshes (that is not that much, but in comparison), while it can't stay above 10fps with barely 10 Sprite3D.
[Sprite3D_Mobile_Test.zip](https://github.com/godotengine/godot/files/3660443/Sprite3D_Mobile_Test.zip)


I think this is indeed a quite old issue: https://github.com/godotengine/godot/issues/2096
And afaik also ImmediateGeometry displays similar, hum... symptoms.

**Comment by Calinou** [comment]
Immediate geometry isn't intended to manage large amounts of geometry, so it should probably be replaced to use some other kind of mesh generation (like ArrayMesh?).

**Comment by Toshiwoz** [comment]
> 
> 
> ImmediateGeometry isn't intended to manage large amounts of geometry, so it should probably be replaced to use some other kind of mesh generation (like ArrayMesh?).

Yeah I am referring to a few lines drawn.
But, never mind, I'll open a new issue or add to existing ones as I have time to make another test/benchmark project.

**Comment by BenMcLean** [comment]
I am also getting hit by this / #31023 in my [WOLF3D](https://github.com/BenMcLean/WOLF3D-Godot) project. As a workaround, I am looking into replacing all my Sprite3Ds with MeshInstances of a QuadMesh. Sure would be nice if Sprite3D was actually fixed though

**Comment by sp00mm** [comment]
I'm also having this issue. They almost should put a disclaimer on the sprit3d node. Now I'm going through ~20+ nodes and changing them to meshes. It would be REALLY nice to have a feature like the 2d sprite where you can convert it to a mesh2D with just a click.

**Comment by semirix** [comment]
Does Sprite3D need a refactor? Surely an object that simple should not be so slow to render.

**Comment by clayjohn** [comment]
@semirix it should probably just be removed and made into a thin she'll for a billboarded quad.

**Comment by Calinou** [comment]
@clayjohn What about AnimatedSprite3D? It's surely possible to emulate its functionality using a MeshInstance + QuadMesh, but it sounds tedious.

**Comment by Seel** [comment]
Yeah... as someone working on a mixed 2D and 3D game I really want that sprite functionality.

**Comment by fossegutten** [comment]
I can only draw about 100 Sprite3D before i drop below 100fps, but i can draw almost 1000 QuadMesh.

**Comment by t-mw** [comment]
For anyone trying to work around this by using an `AtlasTexture` on a `MeshInstance` material, here's a shader and script that might help: https://gist.github.com/t-mw/0b78167372ed97e7c78e3f3844f3ae75.

**Comment by tommiemartin** [comment]
I started looking at this as well but my knowledge of rendering isn't to the point where I can be much help.
Is this currently using immediate geometry to create quads on which the frames are drawn? Seems like the goal would be to put a SpriteFrames resource in 3d space which looks like would somehow need to inherit from a visual instance. 

Seems like ios (ipad mini 2) handles lighting,  normal maps and sprite3d objects much better in its pipeline where as even a couple sprite3d objects on galaxy s7 causes huge fps drops.

I feel this is pretty huge even for 2d games where you see games like hollow knight leveraging 3d for parallax effects. Also anything mixed mode like using meshes instead of sprites for character skins / items.

Another workaround I've used is to create an animated texture resource in a spreadsheet for parsing and import it into the engine. It has a max of 256 frames and very limited control but works for basic playback.

Really hoping this gets cherry picked for the 4.0 release.

**Comment by Calinou** [comment]
> Really hoping this gets cherry picked for the 4.0 release.

It's the other way around :wink: Pull requests in the `master` branch get cherry-picked to the `3.2` branch if they're backwards-compatible.

**Comment by clayjohn** [comment]
I'm going to just replace the backend of the Sprite3D with a proper mesh instead of using ImmediateGeometry.

**Comment by clayjohn** [comment]
PR is up now! Please test it if you are having performance issues with Sprite3D! 

#39867

**Comment by akien-mga** [comment]
Fixed by #39867 in the `3.2` branch.

It's not fixed in `master` yet though, so keeping this issue open. A different fix will be used there.

**Comment by berarma** [comment]
This has already been fixed, hasn't it? Can we close it?

**Comment by akien-mga** [comment]
See my comment above yours: https://github.com/godotengine/godot/issues/20855#issuecomment-654278054

**Comment by berarma** [comment]
> See my comment above yours: [#20855 (comment)](https://github.com/godotengine/godot/issues/20855#issuecomment-654278054)

Sorry, I thought it was a hanging comment.

**Comment by Calinou** [comment]
This was addressed by https://github.com/godotengine/godot/pull/50014, closing.

To confirm this, I benchmarked `3.x` against `master` to compare the current rendering performance of 900 Sprite3Ds in a blank scene (no lights, fallback environment).

**OS:** Fedora 34
**CPU:** Intel Core i7-6700K
**GPU:** GeForce GTX 1080
**Resolution:** 2560×1440
**Godot versions:** `3.x` a05aefb74, `master` fe6c65a1a

**Testing projects:**

- `3.x`: [test_sprite3d_performance_3.x.zip](https://github.com/godotengine/godot/files/7470804/test_sprite3d_performance_3.x.zip)
- `master`: [test_sprite3d_performance_master.zip](https://github.com/godotengine/godot/files/7470805/test_sprite3d_performance_master.zip)

### `master` - Vulkan Clustered

```
Project FPS: 1198 (0.8 mspf)
Project FPS: 1195 (0.8 mspf)
Project FPS: 1198 (0.8 mspf)
Project FPS: 1198 (0.8 mspf)
Project FPS: 1199 (0.8 mspf)
```

### `master` - Vulkan Mobile

*Runs faster than Vulkan Clustered thanks to a lower base cost. However, its performance will fall behind in a more complex scene with many lights.*

```
Project FPS: 1380 (0.7 mspf)
Project FPS: 1376 (0.7 mspf)
Project FPS: 1380 (0.7 mspf)
Project FPS: 1379 (0.7 mspf)
Project FPS: 1349 (0.7 mspf)
```

### `3.x` - GLES3

```
Project FPS: 1691 (0.5 mspf)
Project FPS: 1704 (0.5 mspf)
Project FPS: 1667 (0.5 mspf)
Project FPS: 1690 (0.5 mspf)
Project FPS: 1689 (0.5 mspf)
```

### `3.x` - GLES2

*Despite the GLES2 renderer's lowest base cost (out of all the renderers tested here), this is by far the slowest result.*

```
Project FPS: 546 (1.8 mspf)
Project FPS: 548 (1.8 mspf)
Project FPS: 550 (1.8 mspf)
Project FPS: 548 (1.8 mspf)
Project FPS: 550 (1.8 mspf)
```
