### ISSUE TITLE
Add track_set_key_time as method to Animation class

### ISSUE THREAD

**Issue by Rriik** [godotengine/godot#20858]
**Godot version:** 3.0.6

**OS/device including version:** Windows 10 Pro

**Issue description:**
The Animation class currently has a method called `track_get_key_time` for returning the time at which a key is located on an animation track. However, the class does not have a `track_set_key_time` complement method to change the time property of a given key.

Currently, by my understanding, to move a key to another time position, you would need to `get` all of the key's properties, save for time, then remove the key, add a new key using `track_insert_key` to a desired time position, and then `set` all of those properties to the new key, which is painstaking and inefficient. Adding a `track_set_key_time` would allow users to quickly change the position of a key without hassle.

**Comment by avencherus** [comment]
Would like to second this.  Just bumped into this problem today.
