### ISSUE TITLE
OS.GetScreenSize(); gives wrong values

### ISSUE THREAD

**Issue by FabIV** [godotengine/godot#20859]
**Godot version:**
3.0.6 Mono Build

**OS/device including version:**
Win 10

**Issue description:**
I want to read the screen size /resolution) and adapt my viewport options.
The reading of the screen size gives only a fraction by 0.5715 of the actual pixels.

Actual resolution 3000x2000
What Godot says 1714x1143

**Steps to reproduce:**
Use the command:
`        Vector2 screenSize = OS.GetScreenSize();
        GD.Print("Screensize :" + screenSize);
`

**Minimal reproduction project:**
Attached
[Bug.zip](https://github.com/godotengine/godot/files/2275851/Bug.zip)

**Comment by Noshyaar** [comment]
I'm using non-Mono 3.0.6 and it reports the screen size (1366x768) correctly. I have only one monitor. I can't test your project as it's Mono version and I don't have it installed.

**Comment by CptPotato** [comment]
Sounds like it might be related to Windows' desktop scaling. Are you using 100% scale or something larger?

**Comment by FabIV** [comment]
Is definatley related to the scale factor from windows. I changed it and could directly see the changed result.
Activating The Hi DPi option mentioned by @reduz fixed it. 
So i think we can close this.

P.S:: 
Thanks for all the comments
