### ISSUE TITLE
Feature Request: Double-clicking on a set signal (GUI) opens the belonging script

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#20866]
**Godot version:**
v3.0.6.stable.mono.official.8314054

**OS/device including version:**
GNU/Linux - Ubuntu 18.04

I am sure many would enjoy the ability to be able to double-click on a set signal via the godot GUI, in order to open the script file in use. Preferably having automatically navigated to the set function, but just being able to open the associated script would be a good start.
![](https://i.imgur.com/xd6VPYZ.png)

(I could not find an existing issue about this)

**Comment by YeldhamDev** [comment]
This already happens in the `master` branch.

**Comment by romlok** [comment]
Looks like the same as #19527, which was fixed by #20131.

Since bugs get closed when they're fixed in master (currently 3.1), and not only once there's a new stable release, I always include closed issues and PRs when searching for bugs I encounter. I recommend everyone else to do the same!

**Comment by ivanskodje** [comment]
@romlok A great suggestion searching for closed PRs :) 

Closing this since it has been discussed before in #19527
