### ISSUE TITLE
Undo errors when shader editor is open

### ISSUE THREAD

**Issue by ValerioBulla** [godotengine/godot#2087]
When the shader editor is open and you edit something else in the scene, if you try to undo the scene changes it will ALSO undo the changes done to the shader.

That's very likely to cause data loss if one is not aware of it.

Tested in 2D scenes, untested in 3D.

**Comment by romulox-x** [comment]
I can confirm this.  This one's lost me some changes when I wasn't paying attention.

**Comment by akien-mga** [comment]
Like the input signal is not stopped by the scene editor and propagates further to the shader editor. @MarianoGnu recently fixed something similar for the Ctrl+A input.

**Comment by MarianoGnu** [comment]
weird, shouldn't shader editor close when you select something in the canvas item editor?

**Comment by reduz** [comment]
this one is fixed, related to strange focus grabbing in editor.
