### ISSUE TITLE
Add an option to replace the names of two selected items

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20879]
**Godot version:**
3.1 b293dd3 calinou

**OS/device including version:**
Windows 10 HD 4600

**Issue description:**
Replacing the names of two files with each other is a bit difficult because there is a risk of confusion, therefore I would postulate adding an option available after selecting two items in the File System to replace the names of these items(on image below).

I. Now to rename files with each other:
1. Change the name of the first file to not associated with anything
2. Change the name of the second file to the first one
3. Change the name of the first file to the second one

- It takes about 12 actions (3xRMB, 6xLMB, 3x Write text)

II. When this option is available, the above option will replace the names:
1. Select two files
2. Right-click on the selection
3. Select the option to replace names

- It will take about 5 actions (3xLMB, 1xCTRL, 1xRMB)

![change name](https://user-images.githubusercontent.com/41945903/43950968-2471e688-9c92-11e8-8feb-7d387bed91f3.png)

**Comment by Noshyaar** [comment]
Would this really be useful? I mean, if something would be responsible for renaming, it would be a file manager of the OS, and it doesn't have this feature as far as I know. I don't think there's a shell command for it either.

https://stackoverflow.com/questions/1115904/shortest-way-to-swap-two-files-in-bash

**Comment by akien-mga** [comment]
I also don't think it's a good idea, it's not our job and if even OS file manager don't do it, there's no reason we should.
