### ISSUE TITLE
Audio thread work even without any sounds in game

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20870]
**Godot version:**
3.1 b293dd3 calinou

**OS/device including version:**
Windows 10 HD 4600

**Issue description:**
I don't know if it is issue but even if in game i don't have any sounds, I see in Profiler that Audio Thread still working.  

![sssssaaaaa](https://user-images.githubusercontent.com/41945903/43944421-1d756066-9c7f-11e8-890a-eeef0d7d1b1a.png)

**Comment by Zireael07** [comment]
Same here, I have no sound but Audio thread takes around 0.0003 time.

**Comment by akien-mga** [comment]
CC @marcelofg55

**Comment by marcelofg55** [comment]
Yeah, this is expected, it is not worth to add checks to see if there is no sound playing, Usually a game is playing sounds or music, and the CPU time the Audio Thread uses when there is no sound playing is really low.
