### ISSUE TITLE
Import: after deactivation of materials/keep_on_reimport, the material remains unchanged.

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#20878]
**Godot version:**

a71a5fc0c3f5d487d3f18c3b9e9a768052795e86

**OS/device including version:**

Linux

**Steps to reproduce:**
Change the model material and re-export the model.
Godot insists on using the old one.
 
**Minimal reproduction project:**

![reexport-keeps-material](https://user-images.githubusercontent.com/4047289/43952019-f8459908-9c94-11e8-81a8-14bc0f2d3bf8.png)

**Comment by akien-mga** [comment]
Maybe you need to reimport the resource once to get the modified import settings taken into account?

**Comment by capnm** [comment]
Also doesn't work, even if set as default. The only way is to delete the material file and restart godot.

**Comment by akien-mga** [comment]
Since @reduz closed #15853, I'll reopen this one as we still need this Keep on reimport option reviewed.

**Comment by glaforte** [comment]
I reviewed #15835 and I reproduced the issue as reported, on "master".
Right now, for a user: the 'Keep on Reimport' option does not seem to have any impact. Does this mean it should be removed?
I'll check the code to see what it is supposed to do...

**Comment by nklbdev** [comment]
Godot Collada importer does not overwrite any generated files at all when re-importing: meshes, materials or anything else. Deleting files before re-importing helps. The `keep_on_reimport` flag doesn't work at all
