### ISSUE TITLE
Feature Request (Potential Bug): Error messages for Vector3's rotated method.

### ISSUE THREAD

**Issue by LandonPowell** [godotengine/godot#20874]
**Godot version:**

 v3.0.2.stable.official

**OS/device including version:**

Windows 10

**Issue description:**

When calling `rotated` on a `Vector3`, many inputs result in an unexpected (0,0,0), failing silently. The axis not being a normalized vector, while listed on the documentation page as an invalid input, produces no error, making debugging more difficult than necessary. Passing in `0` as the angle of rotation also results in an unexpected (0,0,0) vector, and this is not listed on the documentation as an invalid input at all.

**Comment by Noshyaar** [comment]
It does produce an error:
![image](https://user-images.githubusercontent.com/26753932/43951908-9e671982-9cbe-11e8-8e42-971e4344bb1f.png)

Passing 0 won't produce error as long as axis is normalized, and the docs does say that axis must be normalized.

**Comment by LandonPowell** [comment]
Hm, I could have sworn passing 0 to the angle value was returning a vector of (0,0,0) for me last night. Looks like the bug is gone now, so I'll close this issue until I can replicate it.

**Comment by LandonPowell** [comment]
Alright, found out what was wrong: Vector3s of value (0,0,0) are normalized to (0,0,0), and Vector3(0,0,0).is_normalized() returns false. `Vector3(0,0,0).normalize().is_normalized()`

I had misattributed this to something else due to cross products returning (0,0,0) when both input vectors are the same. 

Should I open a new issue that more aptly describes the issue?

**Comment by Noshyaar** [comment]
I still don't understand what the issue is. You can't normalize zero vector as it doesn't have direction, and if you try to rotate vector using itself normalized as axis, it ends up in the same position regardless of the degree. It's expected so far.

Here's the relevant parts in the docs:
(http://docs.godotengine.org/en/3.0/tutorials/math/vector_math.html#cross-product)
```
 If two vectors are parallel, the result of their cross product will be null vector.
```
(http://docs.godotengine.org/en/3.0/tutorials/math/vector_math.html#normalization)
```
Because normalization involves dividing by the vector’s length, you cannot normalize 
a vector of length 0. Attempting to do so will result in an error.
```

**Comment by Noshyaar** [comment]
Well that's a valid issue indeed. Either the docs or the engine is wrong. Since our discussion here was about `rotated` method of a Vector, you could open another issue (and maybe refer to this issue) for this so that it's not confusing to other contributors.
