### ISSUE TITLE
Bug : "Invalid call. Nonexistent function `slerp` in base `Vector3`"

### ISSUE THREAD

**Issue by LandonPowell** [godotengine/godot#20875]
**Godot version: **

v3.0.6.stable.official

**OS/device including version:**

Windows 10

**Issue description:**

Documentation for Vector3 includes a `slerp` function. Calls to this function result in the engine returning an error stating that the function doesn't exist. 

**Steps to reproduce:**
```
var newVect = Vector3(0,1,1)
var oldVect = Vector3(1,0,0)
newVect.slerp(oldVect, 0.1)
```

**Comment by Noshyaar** [comment]
Vector3 doesn't have slerp. The docs doesn't include it either. Where did you find it?
