### ISSUE TITLE
Autocomplete Path in Project Manager

### ISSUE THREAD

**Issue by aswinmohanme** [godotengine/godot#20888]
The current Path textbox in the project selection screen does not have autocomplete support. It would be nice if it provided fuzzy autocomplete

**Comment by Calinou** [comment]
I'm not sure how feasible this is (or even if it's desired as of Godot 3.2). The project search was overhauled in #31356 to search both in the project name and path at the same time.

Does the new search behavior suit your needs? Please give it a try :slightly_smiling_face:
