### ISSUE TITLE
Locking 2D nodes doesn't lock them

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#20884]
**Godot version:**
3.1 b293dd3

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Locked 2D nodes can still be moved and rotated as if they weren't locked at all. This only affects 2D nodes, locking still works in 3D.

**Comment by Noshyaar** [comment]
cc @groud :)

**Comment by groud** [comment]
Can you confirm this happens only when moving with the arrow keys ?
The bug is only reproducible by moving with the arrow keys and rotating.

**Comment by CowThing** [comment]
When in select mode alt+drag will move the locked node and control+drag will rotate it. The locked node can also be moved and rotated while in move mode or rotate mode.
