### ISSUE TITLE
Adding a transform on primitive meshes, good or bad?

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/godot#20883]
I had problems using planes as billboards, found someone else with a similar issue https://github.com/godotengine/godot/issues/19249 so I experimented a bit and added translation and rotation to primitive meshes.

https://github.com/spongeboburu/godot/commit/fd474e232f8c6a500ed4439463987162c77fabf0

Basically all primitive meshes have the two added properties "Translation" and "Rotation Degrees" which work the exact same way as for spatial transformation section.

Maybe there's a better way of solving the billboard issue?

**Comment by spongeboburu** [comment]
Nobody else seems to like this, I'll just close it.

**Comment by Calinou** [comment]
For anyone stumbling upon this from a web search, note that a translation offset property was added to QuadMesh and PlaneMesh in https://github.com/godotengine/godot/pull/48764.
