### ISSUE TITLE
Update visual scripting to use new expression class

### ISSUE THREAD

**Issue by fire** [godotengine/godot#20885]
**Godot version:**

6e0adf3656183602f3603b8a26319bcaf84eb7dd

**Issue description:**

Update the visual scripting code to use a71a5fc0c3f5d487d3f18c3b9e9a768052795e86.

**Comment by reduz** [comment]
Yes good idea, that should be done. Both VisualScriptExpression and VisualScriptBuiltinFunc should use it.
