### ISSUE TITLE
Can't set a script for a tileset in the new tileset editor.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#20886]
**Godot version:**
Godot 3.1 b293dd3

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Opening a tileset no longer shows the tileset resource in the inspector panel, so it's not possible to set a script for the tileset. And from what I can see there's no way to set the script in the new tileset editor.

**Comment by MarianoGnu** [comment]
Oh, good catch
