### ISSUE TITLE
Input-map action buttons stacked on each other on OSX  3.1- Dev

### ISSUE THREAD

**Issue by stonekase** [godotengine/godot#20898]
**Godot version:**

Godot 3.1-dev

**OS/device including version:**

Mac OSX high Sierra 10.13

**Issue description:**

The input tab of the project settings draws input settings button stacked on each other.
**Steps to reproduce:**
open the project settings ,click on the input tab.Try to create a custom action-input and add control type(impossible to create)

<img width="1098" alt="screen shot 2018-08-10 at 10 45 04 pm" src="https://user-images.githubusercontent.com/5037778/43985035-4e3fd41a-9cfc-11e8-936c-809edcbdd4f8.png">
<img width="907" alt="screen shot 2018-08-10 at 10 49 45 pm" src="https://user-images.githubusercontent.com/5037778/43985036-4e786e74-9cfc-11e8-9d82-9b5fe2e606e2.png">

**Minimal reproduction project:**

**Comment by tetious** [comment]
PR https://github.com/godotengine/godot/pull/21709 fixes this bug.
