### ISSUE TITLE
No way to see tile IDs in new tileset editor

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#20895]
**Godot version:**
Godot 3.1 b293dd3

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Previously every tile was listed in the tileset resource and you could see which ID each tile is. Now it is not possible to see what the tile ID is even when a tile is selected. A way to see the tile IDs in the tileset editor would be useful.

**Comment by akien-mga** [comment]
CC @MarianoGnu
