### ISSUE TITLE
Inconsistent behavior of `Show in File Manager` on file and on directory

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot#20897]
**Godot version:**

non-official [hash: 52e6f1f25c86891381ca3ce9e03422db586ecd16](https://github.com/godotengine/godot/tree/52e6f1f25c86891381ca3ce9e03422db586ecd16)

**OS/device including version:**

macOS 10.13

**Issue description:**

inconsistent behavior of `Show in File Manager` on file and on directory. Not sure it is a bug or a feature.

**Steps to reproduce:**
##### open “Show in File Manager” on a directory
<img width="242" alt="screen shot 2018-08-10 at 16 03 59" src="https://user-images.githubusercontent.com/19422835/43984759-6de1d2fe-9cb7-11e8-99f1-d1f065fa8fa2.png">

##### it opens the select directory
<img width="552" alt="screen shot 2018-08-10 at 16 04 12" src="https://user-images.githubusercontent.com/19422835/43984771-89a5e4e4-9cb7-11e8-8b82-0b22097bcdd1.png">

##### open "Show in File Manager" on a file
<img width="248" alt="screen shot 2018-08-10 at 16 04 37" src="https://user-images.githubusercontent.com/19422835/43984775-94756d04-9cb7-11e8-883b-db354f118048.png">

##### it opens the directory contains that file
<img width="659" alt="screen shot 2018-08-10 at 16 04 55" src="https://user-images.githubusercontent.com/19422835/43984782-9e6024da-9cb7-11e8-98de-6df3ce9503ee.png">

In Godot 3.0, click on "Show in File Manager" both on file or directory will open the directory contains it

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Perhaps the option could be named **Open In File Manager** when a directory is selected; this way, it will become obvious that the file manager will open inside the selected directory (rather than outside).

**Comment by Jason0214** [comment]
yeah, it makes more sense
