### ISSUE TITLE
Duplicate String Literal Added on Autocomplete Partial String

### ISSUE THREAD

**Issue by aswinmohanme** [godotengine/godot#20905]
Godot Version: 3.0.6-stable

Current Behavior:
- Open Editor 
- Enter `if Input.is_action_pressed("ui_up"):` 
- Change `ui_up` to `ui_right` and select it from the autocomplete menu
- An extra `"` gets added at the end

Expected:
- The extra `"` should not be added

**Comment by gotnospirit** [comment]
I'm unable to reproduce it using master af93842f.

**Comment by akien-mga** [comment]
Indeed, this was fixed by #19187. I've tagged it for cherry-picking so it might end up in the 3.0 branch too eventually.
