### ISSUE TITLE
Android export error with logcat output

### ISSUE THREAD

**Issue by TaofeekS** [godotengine/godot#20909]
**Godot version:**

Godot version 3.0.5 & Godot version 3.0.4

**OS/device including version:**

Hp 
Ram size: 4gb

**Issue description:**

i try exporting my game to my android phone which android version is norgat(7.0) it installed perfectly but it will stop immediately with error message "sorry game has stopped" i try using andriod studio logcat and it print out this information

```
--------- beginning of crash
08-09 21:33:28.037 29344-29359/org.godotengine.brave E/AndroidRuntime: FATAL EXCEPTION: GLThread 5045
    Process: org.godotengine.brave, PID: 29344
    java.lang.RuntimeException: createContext failed: EGL_SUCCESS
        at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1245)
        at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1236)
        at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1086)
        at android.opengl.GLSurfaceView $GLThread.guardedRun(GLSurfaceView.java:1462)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1299)
```
the jdk version i installed is jdk1.8.0_181, my adb is up to date and i have tried export to other devices it still the same problem and the game i want to export is a 2D game

i dont  know if there is something am missing when it comes to exporting to android 
thanks

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by volzhs** [comment]
this log does not give any useful information. 
did you try to install and run empty project?

**Comment by clayjohn** [comment]
Superceded by #31420
