### ISSUE TITLE
Visual script bug: zoom and drag a function will place it wrong

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#20912]
**Godot version:**
v3.1.dev.calinou.b293dd3

**OS/device including version:**
windows 10 x64

**Issue description:**
in visual script :
zoom maximum in or out , and drag a function node (ex: a=b , action,..) or drag from inspector or scene will place the node on wrong place.

**Comment by fire** [comment]
Can you check if this still occurs in 3.2 master? 

After https://github.com/godotengine/godot/commit/ae6c390eb215c8c3f27f0f7a249cb2c07fcfc08a git commit.

**Comment by KoBeWi** [comment]
No reply, so assuming it's resolved.
