### ISSUE TITLE
Visual script: copying function node should copy values

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#20911]
**Godot version:**
v3.1.dev.calinou.b293dd3

**OS/device including version:**
windows 10 x64

**Issue description:**
in visual script :
-when copy a function node (ex: a=b ,or any node contain values) it create the node but it does not copy values.
-when copy a function node (ex: animated sprite "set animation" with str value run) it create the node but the value type will be "any" and the value gone.

**Comment by fire** [comment]
Can't reproduce. Was probably fixed.

I tried duplicating a vector3 constructor with values (10,10,10) and a set variable function with a string "12345".

Can you check?

**Comment by sami8github** [comment]
Yes its fixed , in both cases it copy correctly.
