### ISSUE TITLE
Moving shader files within the editor discards the unsaved code without asking

### ISSUE THREAD

**Issue by iRadEntertainment** [godotengine/godot#20923]
**Godot version:**
Godot 3.0.5

**Issue description:**
As title suggest, when moving file.shader from a location to another within the editor, Godot moves just the last saved file without any warning of losing unsaved edits. Will be nice to have at least a warning with an confirmation diag if the editor realizes that new conten has been added to the about-to-move file

**Minimal reproduction project:**
Create a new shader and save it as a file. Edit with few lines and then move it in another folder using the editor.
Reopening the shader file will display of course just the last saved one. A warning could help to avoid mistakes from users.

**Comment by akien-mga** [comment]
Tested in 3.3 and it seems to behave as expected now, renaming or moving a `.shader` file with unsaved changes will preserve those unsaved changes.

Incidentally, closing the project without having saved those changes will auto-save them without asking. This may not be optimal behavior but it's better than the other way around.
