### ISSUE TITLE
Case-aware autocomplete

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20925]
Right now, autocomplete feature ignores whether you write something in uppercase or lower case. It leads to situations like this:
![image](https://user-images.githubusercontent.com/2223172/43995199-2c3d7b0c-9daa-11e8-9ef8-003d0456edcd.png)
Whenever I want to use `position`, the editor suggests me `Position2D` type. It should jump to `position` in this case and only suggest `Position2D` if I start typing from _Pos.._

**Comment by vnen** [comment]
I agree that it should prefer the same case, but it should show everything.

**Comment by KoBeWi** [comment]
> it should show everything.

Obviously. That's why I wrote "case-aware" not "case-sensitive".
