### ISSUE TITLE
Godot pseudo-crashing when trying open C# script in Visual Studio Code

### ISSUE THREAD

**Issue by theOtherHolmes** [godotengine/godot#20935]
**Godot version:**
3.0.6.stable.mono.official.8314054

**OS/device including version:**
macOS 10.11.6 (El Capitan)

**Issue description:**
I cannot get Godot to open C# scripts in VSCode.

**Steps to reproduce:**
1. Installed VSCode, v1.25.1 (latest version).
2. Added VSCode to PATH per instructions [here](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line).
3. Created a node in Godot, then created a sprite as a child node.  Named the sprite "MySprite."  (per the YouTube tutorial [here](https://www.youtube.com/watch?v=h1t6ZSIW5L8), to prevent the problem of having the class name and script name be the same.)
4. Ran "Attach Script" on MySprite, kept all of the default values:
![screen shot 2018-08-11 at 7 28 40 pm](https://user-images.githubusercontent.com/42307383/43997590-ee7777f8-9d9c-11e8-8efc-b57476240807.png)
5. Clicked "Create" and waited a few seconds, nothing seems to be happening, until...
![screen shot 2018-08-11 at 7 31 21 pm](https://user-images.githubusercontent.com/42307383/43997598-3672b702-9d9d-11e8-8c7b-35bc6d7818f9.png)
6. Godot actually keeps running, it's not really a crash.  In any event, VSCode does **not** open.

As far as I can tell, this is the same problem reported and resolved at [17615](https://github.com/godotengine/godot/issues/17615), but the solution there -- add VSCode to PATH -- worked to resolve it there.  It has NOT resolved anything for me (see step 2, above).

Any help would be appreciated.

**Comment by aaronfranke** [comment]
Which version of Mono are you using? You must use the latest version, old versions do not work at all.

**Comment by MackeyK24** [comment]
I get the same exact crash. I have installed CODE on the PATH. I have REMOVED Visual Studio Mac mono version of 5.10 and download the LATEST 5.14 Stable Version.

Still get the the same crash. something about SIGBYTE

**Comment by MackeyK24** [comment]
Yo @aaronfranke ... I got 3.0.2 to work with C#. you need EXACTLY Mono Version 5.12... Goto mono downloads grab OLDER Version. This is the latest 5.12 version 

https://download.mono-project.com/archive/5.12.0/macos-10-universal/MonoFramework-MDK-5.12.0.macos10.xamarin.universal.pkg

Note: Create your C# Solution File First... Then attach C# scripts to nodes... If you get an Error trying to double-click the C# script in Godot Editor... just manually open the Project file with .sln in VSCode... Everything still works... including code complete :)

**Comment by theOtherHolmes** [comment]
@aaronfranke, I am with @MackeyK24 on this one.  I believe you must use Mono 5.12.0, which is not the latest version (5.14.0).  The Godot website specifically says to use 5.12.0 . . .

![screen shot 2018-08-12 at 6 45 54 am](https://user-images.githubusercontent.com/42307383/44002176-f16fbace-9dfb-11e8-84a1-c9f6bd2e29a8.png)

. . . and I learned by experience that this does NOT mean "5.12.0 or higher," because I couldn't even create or edit a C# script in the Godot built-in editor (much less think about VSCode) until I uninstalled 5.14 and installed 5.12.

@MackeyK24 You mentioned uninstalling Visual Studio for Mac. I will try that -- I still have VSMac (from Unity days).  I'll report back.

**Comment by MackeyK24** [comment]
Run this command to clear out the current MONO:

sudo rm -rf /Library/Frameworks/Mono.framework
sudo pkgutil --forget com.xamarin.mono-MDK.pkg
sudo rm /etc/paths.d/mono-commands

**Comment by MackeyK24** [comment]
I am about to try and build the 3.1 on GitHub and see how that works... If we can double click our c# files ini editor and it Open VS Code... E

Note: Even with the 3.0.2 Godot and 5.12 Mono... Still crashes when double clicking C# scripts.
So I am just manually open C# Project Folder with .sln... At least it works :)

**Comment by theOtherHolmes** [comment]
@MackeyK24 Just to be safe, I completely uninstalled Godot, Mono, VSMac, and VSCode.  Reinstalled Godot, Mono 5.12, and VSCode, and set PATH (per my step 2 in the original post).  Also created a C# solution first, per your suggestion in your [second post](https://github.com/godotengine/godot/issues/20935#issuecomment-412340519).  Then I attached the script, clicked Create, and.... same crash.

HOWEVER, you are correct, if I just open the script directly through VSCode, it seems to work.  So I will do that for now.

But there must be a better way.....

**Comment by aaronfranke** [comment]
CC @neikeq, own any Macs?

**Comment by Rinma** [comment]
Hi. I think I have the same problem. 
I can't create/attach a C# script and I can't create a C# Solution with the menu in the top right. In both cases, Godot crashes.

Godot 3.0.6
MacOS 10.13.6
Mono 5.12.0.226

**Comment by MackeyK24** [comment]
Yo @Rinma ... Try this 5.12

https://download.mono-project.com/archive/5.12.0/macos-10-universal/MonoFramework-MDK-5.12.0.macos10.xamarin.universal.pkg

I think its 5.12.0.3xx series

**Comment by MackeyK24** [comment]
I cant really tell anymore... I upgraded to 5.14 as i am trying to build the 3.1 Mono Version from source.

I really want those 3.1 features... they are freaking AWESOME... Did you see the Animation State Machine Stuff... Cant wait till thihs freaking things builds... Slow going when building all the Mono Steps:

FYI... Anyone who want to try and Build 3.1... I made a little build Cheat Sheet:

```
# Got Godot Project
git clone --recursive https://github.com/godotengine/godot.git

# Setup environment variable
export MONO64_PREFIX=/Library/Frameworks/Mono.framework/Versions/Current

# Build temporary binary
scons p=osx tools=yes module_mono_enabled=yes mono_glue=no

# Generate glue sources
bin/godot.osx.tools.64.mono --generate-mono-glue modules/mono/glue

### Build binaries normally
# Editor
scons p=osx target=release_debug tools=yes module_mono_enabled=yes

# Export templates
scons p=osx target=debug tools=no module_mono_enabled=yes
scons p=osx target=release tools=no module_mono_enabled=yes


===================
OSX PLATFORM BUILD
===================
To create an .app like in the official builds, you need to use the template located in misc/dist/osx_tools.app. Typically, for a “.64” optimised binary built with scons p=osx target=release_debug:

cp -r misc/dist/osx_tools.app ./Godot.app
mkdir -p Godot.app/Contents/MacOS
cp bin/godot.osx.tools.64.mono Godot.app/Contents/MacOS/Godot
chmod +x Godot.app/Contents/MacOS/Godot

```

Good Luck :)

**Comment by MackeyK24** [comment]
if i cant get 3.1 to build after all this... I will clean and rebuild with LATEST 5.12.03xx (i forgot exactly what 300 version...until then try and use the LATEST 5.12 from Mono Archives) or use that URL link i made in the previous post. That one worked for me on . my Mac 10.13.6 with Godot Binary 3.0.6

**Comment by akien-mga** [comment]
There's a lot of noise in this issue, it's hard to keep track of what the bug is if there's one.

To use official Godot 3.0.6 binaries, you need Mono 5.12.x. Not 5.14, not 5.10, only **5.12**.
If you compile from source, you can use any recent Mono version.

**Comment by MackeyK24** [comment]
I tried compiling the master 3.1 with mono 5.12 and 5.14

**Comment by theOtherHolmes** [comment]
@akien-mga To distill the problem:

Even when taking all the right steps [see all my steps documented in my various posts, above] Godot:
1. _announces_ that is has crashed, even though Godot _actually_ keeps running, and
2. VSCode does not open.

But VSCode _does work_ if you open it yourself and open any project scripts directly through it, instead of through Godot.

So there are two problems: (1) the pseudo-crash, and (2) Godot's inability to launch VSCode when opening a C# script directly through Godot.

**Comment by exts** [comment]
cc: @hpvb

**Comment by neikeq** [comment]
I will check this tonight.

> 1. _announces_ that is has crashed, even though Godot _actually_ keeps running

This is covered in #17615
