### ISSUE TITLE
AnimationNode.GetName() returns an empty literal in C#

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#20939]
**Godot version:**
`master` / 80a8636a

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
When referencing an `AnimationNode` from the code, both `GetName()` and `GetCaption()` return an empty literal even though the node can be found by calling `AnimationTree.GetNode()` using its name which is assigned within the editor.

It occurs with `AnimationNodeBlend2` in a C# project, but it's not certain that it's specific to the type of a node, or a binding language used.

**Comment by mysticfall** [comment]
Not sure if it's related. But now I'm having a similar issue with `Animation.GetName()` in 6c569c90b66.

**Comment by reduz** [comment]
get_name will likely be empty given that is just the resource name and it is unused.. not quite sure if this is a bug then, so up to @neikeq.

**Comment by mysticfall** [comment]
@reduz You are right about resource name. It seems that I got confused as there's `ResourceName` property as well, so I assumed `GetName()` would return the name of animation itself.

Is it correct then there is no way to get the name of an animation instance? If it is so should I open another issue to add such a functionality and close this one?

**Comment by mysticfall** [comment]
By the way, I've been using `Animation.GetName()` to dynamically add an animation to `AnimationTree`. 

I have an item definition which can define an animation resource to be used when the player picks it up or equips it.

Before the refactor, `AnimationTreePlayer` accepted an animation resource so I could use it to achieve that functionality, but the new `AnimationTree` only accepts the name of an animation so I changed my code to use `Animation.GetName()` instead (#19877).

I think it had been working for a while before a recent update, and now I find that both `Animation.GetName()` and `AnimationNode.GetName()` no longer does what I thought they did.

So, if it is indeed an intended behavior I think it would be another blocker issue for me as it'd mean there's no way to add an animation dynamically to a `AnimationTree` when you only have a property reference to an animation resource.

**Comment by neikeq** [comment]
`ResourceName` is a property whose setter and getter are `SetName` and `GetName`. Note: I plan to make methods private if they are setter of getter of a resource.

**Comment by neikeq** [comment]
If I understand well, this is not an issue with C# right? If that's the case, I would close this and open a new one.

**Comment by mysticfall** [comment]
I just opened #21946 with a more accurate description of the problem. It only mentions about `Animation` resource though, since I think the actual problem with `AnimationNode*` is that the API doesn't really allow manipulating them which is already reported by #19878.

I'll close this one to avoid confusion.
