### ISSUE TITLE
Godot GLES2: Buggy Crashes (Strange Results on Different OS)

### ISSUE THREAD

**Issue by abhaskumarsinha** [godotengine/godot#20943]
<h1 align='center'>GODOT CONFLICTS/CRASHES DUE TO GLES2</h1>
<hr>

_After the GLES2 Backend for Godot has been merged, I've observed a strange error and Crashes in Godot which I think that the Developers are not able to Reproduce, so I've started a new issue so that the Developers can understand if there is a single Issue with it which is happening to many users with different Error Messages. I further Observed a strange error in Different OS which I'll explain shortly here._

<hr>
<h3>Godot Custom Build: 12th August 2018</h3>
<p align='justified'>
I downloaded the 2 Versions of Godot one for Linux and another one for Windows 7 (32  bit). Then the problem occurred and the Steps that I've performed have been summarized  below:

- <h4><b>Windows</b></h4>
I downloaded the Windows 32 bit Version of Godot from the Hugo Daily Builds. I first ran that. The Godot Crashed by giving an error Message that GLES3 is not supported in my PC and it'll self Destruct. Then after that I Ran it on Command Prompt window:

```
godot_custom.exe --editor --path "./project/files/" --video-driver GLES2
godot_custom.exe --video-driver GLES2
godot_custom.exe --video-driver GLES2 --debug
```
To my bad luck, none of them did worked. I tried watching the console for any error messages or any other type of info. Only thing it showed was that hdpi aware? and next line line was something like this - OpenGL Debugging not supported and the splash Screen of Godot did Greyed and I was unable to even select any one window of it and an windows Crash Reporting also came there.

The main issue was to reproduce the problem, if something didn't even start (not even console), then how can I give the error messages and warning to reproduce the problem?

- Linux 64 bit

On, the same Device with Debian Linux. I tried Downloading and running the Linux version. Finally, I was able to record the Error Message about crash (on the same PC). It showed more Lines than Windows.

```
root@VAIO-PC:~/Downloads# '/root/Downloads/godot-linux-nightly-x86_64.AppImage'  --video-driver GLES2
OpenGL ES 2.0 Renderer: Mesa DRI Intel(R) Ironlake Mobile 
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 16	Severity: High	Message: GL_INVALID_OPERATION in glTexImage2D(bad target for depth texture)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x34f00) [0x7f049cc09f00] (??:0)
-- END OF BACKTRACE --
Aborted
root@VAIO-PC:~/Downloads# 

```
Again the application Crashed in the Splash Screen in Linux. The Error messages did repeated same thing more times (except that in the middle line) and the last line did showed a Linux Library.
</p>

<hr>
<h2 align='center'>ERROR THAT HAPPENED TO OTHERS</h2>
<hr>]
I think that what error happened to others are worth being added here and may be related to this issue.

- Issue #20734 
Joseph Halter gives his own error Message which happened to him during Startup using GLES2 Backend on a MAC Device.

```
arguments
0: /Applications/Godot.app/Contents/MacOS/Godot
1: --verbose
2: -e
3: --video-driver
4: GLES2
Current path: /Applications/Godot.app/Contents/Resources
Using GLES2 video driver
OpenGL debugging not supported!
OpenGL ES 2.0 Renderer: AMD Radeon R9 M370X OpenGL Engine
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:2296.
CoreAudio: detected 2 channels
CoreAudio: audio buffer frames: 512 calculated latency: 11ms
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x00007fff62eb6f5a _sigtramp + 26
[2] 2   libsystem_malloc.dylib              0x00007fff62d513bf szone_malloc_should_clear + 422
[3] Ref<MobileVRInterface>::instance() (in Godot) + 42
[4] register_mobile_vr_types() (in Godot) + 35
[5] register_module_types() (in Godot) + 74
[6] Main::setup2(unsigned long long) (in Godot) + 5121
[7] Main::setup(char const*, int, char**, bool) (in Godot) + 20358
[8] main (in Godot) + 609
[9] 9   libdyld.dylib                       0x00007fff62ba8015 start + 1
-- END OF BACKTRACE --
```
where @karroffel figured out that the problem is with Mobile VR.

- Other users

While there are few users who are facing this same issue on this, but still I've found that there are users who are able to run the application on GLES2 Backend. For those who are having the crash issues on splash Screen have reported to get different error message too from me.

<h1 align='center'>PC SPECS</h1>

The PC on which the error has happened -
```

root@VAIO-PC:~/Downloads# glxinfo | grep "OpenGL"
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 11.2.2
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 11.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
root@VAIO-PC:~/Downloads# 

```
I've tested this on my New Laptop with GTX 1080, had same issue, it crashes without any warning.

<hr>
<h1 align='center'>TIMESTAMP DETAILS</h1>
I'd like to give some Details just before the Godot GLES2 Backend was merged (just 1 week before this), I've downloaded the Godot for both Windows and Linux and tried testing them (making a 2D game for Android), this worked! and there was grey screen in 3D Tab but 2D part and other features worked really well, which again Confirms that there are no issue with Drivers.
Other than that I tried Software Emulation to see what, the present 3D Version and the older one (which I've mentioned) worked well with Linux Mesa OpenGL Software Emulation.

![screenshot from 2018-08-10 20-50-23](https://user-images.githubusercontent.com/31654395/44002045-f9d8ffce-9e2b-11e8-99da-919ddddf560a.png)

**I did the best I think that from which I can tell the error, if something is missing then comment, I'll add those details soon, since the problem is not with Specific Hardware I don't know how to Add Steps of reproduction**
<hr>
Best Regards.
 <hr>

**Comment by abhaskumarsinha** [comment]
also as @karroffel suspected that there might be some problem with the drivers, so, I've updated my drivers -
```

root@VAIO-PC:~# glxinfo | grep "OpenGL"
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 18.1.4
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.1.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
root@VAIO-PC:~# 

```
Plus, there are some other people too which've confirmed this strange thing that error repeats several times, you may see their Output similar to mine too - [click here to go to issue - #20734 ](https://github.com/godotengine/godot/issues/20734)

**Comment by LimitlessChamp** [comment]
I have been fighting with this issue the last few weeks. I was able to ultimately get it to load but not sure why.  After a lot of debugging and trial and error, here is what i did:

Issue 1 - glDrawArrays segfault kills application
https://github.com/godotengine/godot/blob/2005b0c820bac050e48c59f986e8e9fd3d7dce77/drivers/gles2/rasterizer_storage_gles2.cpp#L970

I ended up commenting out glDrawArrays(GL_TRIANGLE_FAN, 0, 4) in rasterizer_storage_gles2.cpp near line 970 in the sky_set_texture(RID p_sky, RID p_panorama, int p_radiance_size) function. Interesting  enough I still see the sky rendered.

Issue 2 - (bad target for texture) This does not cause a fatal failure 

Problem: 
https://github.com/godotengine/godot/blob/60312915dc9c52d8dbf2b5cd6d28a9fcde92840e/drivers/gles2/rasterizer_scene_gles2.cpp#L2622
```
glTexImage2D(_cube_side_enum[i], 0, GL_DEPTH_COMPONENT, cube_size, cube_size, 0, GL_DEPTH_COMPONENT, GL_UNSIGNED_SHORT, NULL);
```
The reason i think this does not work as expected from the opengl documentation 
http://docs.gl/gl2/glTexImage2D
GL_INVALID_OPERATION is generated if target is not GL_TEXTURE_2D or GL_PROXY_TEXTURE_2D and internalFormat is GL_DEPTH_COMPONENT, GL_DEPTH_COMPONENT16, GL_DEPTH_COMPONENT24, or GL_DEPTH_COMPONENT32. 

Hope this help get to the root of the issues, let me know how I can help figure this out.

**Comment by akien-mga** [comment]
There have been lots of fixes to the GLES2 backend since September, is this issue still reproducible?

**Comment by reduz** [comment]
I think this can be safely closed, please reopen if you find anything.

**Comment by LimitlessChamp** [comment]
I haven't be able to test my project lately. When I get back to it I will reopen this if the problem continues. Thank you for the update
