### ISSUE TITLE
Exported negative enums can't be set in inspector

### ISSUE THREAD

**Issue by immccc** [godotengine/godot#20944]
**Godot version:** Godot 3.0.stable.official

**OS/device including version:** Windows 10

**Issue description:**
When defining an enum to be used throughout a whole project,  and when defining an exported variable in a Node with that enum, not all values are selectable: When selecting the very first in the enum values, the property in the node is never updated, but it works fine for second, third, fourth, etc.

**Steps to reproduce:**

1. Create a gd file, direction.gd:

```
enum Direction {
	LEFT = -1,
	RIGHT = 1
}
```
2. Create any kind of Node and assign an script like:

```
const DirectionDefinition = preload("res://direction.gd")
#...
export (DirectionDefinition.Direction) var direction_for_being_set_from_editor
#...
```

3. Check that enum values are theoretically selectable:
![image](https://user-images.githubusercontent.com/3154692/44002857-0343c328-9e4a-11e8-8219-41a127fa1f41.png)

4. Assign "Left"
5. "Set direction_for_being_set_from_editor" is shown in output.
6. "Left" value is not set, after all. Sometimes value is "(other)", some others "Right".

**Comment by immccc** [comment]
After playing around a little bit more, seems that the issue comes from being LEFT a negative integer. 

But in docs I don´t see any restriction regarding negative/positive values mentioned. As it is a shorthand of constants here in GDScript, I would expect that, since constants can have obviously negative values, a value in enum can as well.

**Comment by kubecz3k** [comment]
cc @bojidar-bg

**Comment by bojidar-bg** [comment]
cc @ordigdug as well.

**Comment by ordigdug** [comment]
Confirmed issue in 3.0.6, works correctly in current 3.1 master 9f8e2d5.

**Comment by akien-mga** [comment]
Closing as fixed in the master branch then.

If someone tracks down which commit fixed it, and it's simple enough, it could be considered for cherry-picking to the 3.0 branch.
