### ISSUE TITLE
Huge performance loss when compiling Godot from source

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#2095]
When compiling Godot from source on Ubuntu 14.04 it roughly half of its performance. Everything in the editor takes twice as long. And when building and running a game with that custom Godot build, the game also runs much much slower than the official build.

This is a persistent problem, not just with a specific revision from GitHub. 
http://www.godotengine.org/forum/viewtopic.php?f=12&t=1482&p=10020#p10020
And at least one other person described the same problem in the Facebook group, but I have no link to that post.

I followed the instrucions here: https://github.com/okamstudio/godot/wiki/compiling_linux

Should I provide the output of the scons command?

Should I provide my compiled binary so you can see how slow it runs?

Could you provide automated nightly builds on the Godot website? That would also solve this problem and make it easier for other people too to use the latest version.

**Comment by akien-mga** [comment]
I built the latest git version on Mageia 5 64bit and I don't reproduce this issue. I built it with the minimal instructions, i.e. ```scons p=x11 target=debug tools=yes```

**Comment by akien-mga** [comment]
Quoting @reduz from the forum topic:
> I am aware of this, and I know what is causing it (forced linked list of subwindows to sort each time one is added for popups, but this turned out to be really slow because there are more than a few thousands invisible in the editor), will try to fix it asap

**Comment by ScyDev** [comment]
Thanks for your comment. Could it make a difference whether I build on a 32bit or 64bit platform?

Unfortunately that answer from reduz was half a year ago.
And how does that explain that you don't have this problem, but I do?

**Comment by akien-mga** [comment]
> Could it make a difference whether I build on a 32bit or 64bit platform?

No idea, but I've only tried 64bit build so far.

> Unfortunately that answer from reduz was half a year ago.

Yes I'm just giving it for consistency, it could help @reduz diagnose the problem further.

**Comment by choikwa** [comment]
you could try target=release_debug build which compiles at -O2 -ffast-math

**Comment by reduz** [comment]
ah that must be the reason of the performance difference, release_debug is
faster.
Godot is MUCH faster when compiling using just release, but the editor will
not work without debug

**Comment by akien-mga** [comment]
Note that I am the one building with target=debug, and I don't experience the issue discussed here. But maybe @ScyDev uses debug too?

**Comment by ScyDev** [comment]
Yes, using target=release_debug seems to have resolved this problem.
Thanks! :)

But why isn't this mentioned on the official compiling instructions?
https://github.com/okamstudio/godot/wiki/compiling_linux

The command for building the Godot editor should therefore be:
```
scons platform=x11 target=release_debug
```

Can you please update the wiki? This seems to be pretty essential information, as the difference in performance is pretty drastic.

**Comment by Krzycho666** [comment]
Building on windows 7 with gcc 4.9.2 using 
```scons platform=x11 target=release_debug```
takes 45min on my pc which sucks to me :/ And the output is about 40MB. And sometimes is takes about 176MB - don't know why.

**Comment by akien-mga** [comment]
@Krzycho666 That's normal if it's the first time you build it. The next build should be faster thanks to incremental compilation. You can also assign several CPU cores to the build process using the -j argument, eg.: ```scons platform=x11 target=release_debug -j4```

**Comment by ScyDev** [comment]
Yes, I can confirm, the speed up on the second build is enormous.

Need to try mutliple cores next time :)

**Comment by Krzycho666** [comment]
The main problem is probably in the scons itself:
http://electric-cloud.com/blog/2010/07/a-second-look-at-scons-performance/

**Comment by choikwa** [comment]
Krzycho666, I believe godot at current stage is no where near the observable limits of scons overhead .. yet. Also, ScyDev, there is a reason dev builds use debug. We want to dev, not debug at opt. Debugging capability is reduced a lot at opt. If you want performance, use the release build for it or build using release_debug. If you want to debug performance, you usually need another way, like using profiler.

**Comment by raould** [comment]
please somebody who has permissions do update the wiki as suggested above to warn about the slowdown, i encountered it myself and did not know why. :-)

**Comment by akien-mga** [comment]
Everyone can update the docs: https://github.com/godotengine/godot-docs
The question is "where" to put this information.

**Comment by raould** [comment]
ok i will try to do it. 

the docs are on the whole surprisingly good vs. what usually exists even from e.g. Apple sometimes :-) 

(having said that... it would be kinda nice if things were in a public wiki so it would be a no-brainer to add small helpful tips like this? but i realize that is untenable now.)
