### ISSUE TITLE
`PackedScene` ignores all nodes added as index 2 or above

### ISSUE THREAD

**Issue by shackra** [godotengine/godot#20954]
**Godot version:**
3.0.6

**Issue description:**
`PackedScene` don't save any node added to `index=1` node.

**Steps to reproduce:**
Add a root node, then add a child, then with GDScript create any sort of node and add it as child of the child we add before, save scene with `PackedScene`, reload the saved scene.

**Minimal reproduction project:**
[PackedScene bug.zip](https://github.com/godotengine/godot/files/2281332/PackedScene.bug.zip)

**Comment by nunodonato** [comment]
i think setting a parent is not enough, you need to set owner in order to work with packedscene.
not sure though :)

**Comment by shackra** [comment]
That was done:

```
        $Subnode.add_child(line)
        line.owner = $Subnode
```

**Comment by Noshyaar** [comment]
```gdscript
line.owner = $Subnode
```
Change it to
```gdscript
line.owner = self
```

From the docs
> The node owner. A node can have any other node as owner (as long as it is a valid parent, grandparent, etc. ascending in the tree). **When saving a node (using PackedScene) all the nodes it owns will be saved with it.** This allows for the creation of complex SceneTrees, with instancing and subinstancing.

**Comment by shackra** [comment]
Boy, this needs to be more clearly, maybe some warnings on PackedScene...
