### ISSUE TITLE
A preview pane for Animations in`AnimatedSprite`

### ISSUE THREAD

**Issue by Logmytech** [godotengine/godot#20968]
I remember that Game Maker had an animation preview for Animated Sprites.
Like this: https://youtu.be/5V5CIAmAtRU?t=1m44s

But when watching HeartBeast's Godot Platformer tutorial, I realized Godot doesn't have a previewer for Animations.

It makes it had to see how the animation plays and how fast it really looks.

We need a preview pane, maybe on the right or maybe left.

Then we can adjust speed and see if the animation plays nicely like how it's gonna look in the game and if it is missing any frames or looks bad.

Edit: It seems we can preview going to root of AnimatedSprite and selecting animation and checking Play. However this is hard to see if your speed is right. You need to set speed, repeat the whole process every time you change speed and want to preview.

**Comment by KoBeWi** [comment]
Setting `playing` property to true will play the animation in the editor, which effectively previews it. In any case, this is a material for a proposal that should go to the [official proposal repository](https://github.com/godotengine/godot-proposals).
