### ISSUE TITLE
More visible debug collision shapes

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#20962]
**Godot version:**
Latest master

**Issue description:**
Collision shapes in 3D are very hard to see. I suggest to have them look more transparent and solid, like 2D collision shapes (if not all the time, at least on demand.)
I had a bug because a collision shape was wrong and I couldn't figure out for a while because in the game the collision shape seemed fine, because it looked hollow but it wasn't.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/906, as feature proposals are now tracked in the Godot proposals repository.
