### ISSUE TITLE
Particles2D node causes screen flickering and artifacts on macOS

### ISSUE THREAD

**Issue by phutflesz** [godotengine/godot#20961]
**Godot version:**
v3.0.6.stable.official.8314054

**OS/device including version:**
macOS High Sierra 10.13.6 (17G65)
MacBook Pro (13-inch, 2017)
2,3 GHz Intel Core i5
8 GB 2133 MHz LPDDR3
Intel Iris Plus Graphics 640 1536 MB

**Issue description:**
The whole screen starts flickering and artifacts start appearing when there is a Particle2D node active and visible in the project. This affects the Godot IDE window, macOS menu bar and dock, context menus in IDE and macOS, sometimes icons on the desktop or even portions of the desktop itself, other windows like Firefox,...
Current workaround: Turning the particle node's visibility off (works, but it's really clumsy).
[Video showing the bug](https://streamable.com/t7j19)

**Steps to reproduce:**
Open the "Dodge the Creeps" demo project from the official docs, or add a Particle2D node to an otherwise empty scene. Then continue using Godot normally or switch between open windows.

**Minimal reproduction project:**
[flickertest.zip](https://github.com/godotengine/godot/files/2282467/flickertest.zip)

**Comment by eon-s** [comment]
This looks like a shader issue (and probably driver related).

Can you open the editor from a terminal window to see if there are some engine errors in the output?

**Comment by phutflesz** [comment]
Sure thing!
The output:

$ /Applications/Godot.app/Contents/MacOS/Godot --path ~/Godot/flickertest/ -e Flicker.tscn --verbose
arguments
0: /Applications/Godot.app/Contents/MacOS/Godot
1: --path
2: ~/Godot/flickertest/
3: -e
4: Flicker.tscn
5: --verbose
Current path: /Applications/Godot.app/Contents/Resources
Using GLES3 video driver
OpenGL ES 3.0 Renderer: Intel(R) Iris(TM) Plus Graphics 640
CoreAudio: detected 2 channels
CoreAudio: audio buffer frames: 512 calculated latency: 11ms
CORE API HASH: -7254815458013810978
EDITOR API HASH: 2577452685349188824
load resource: res://default_env.tres
load resource: ~/Library/Application Support/Godot/editor_settings-3.tres
EditorSettings: Load OK!
load resource: res://default_env.tres
load resource: res://Flicker.tscn
EditorSettings Save OK!
Audio Driver CoreAudio average latency: 11ms (frame=512)
Audio Driver CoreAudio average latency: 11ms (frame=512)
Audio Driver CoreAudio average latency: 11ms (frame=512)
EditorSettings Save OK!

**Comment by reduz** [comment]
This is most likely driver related and not much can be done from my part for the time being.

**Comment by reduz** [comment]
I suggest for better compatibility, use the CPUParticles node instead for now.

**Comment by tavurth** [comment]
Issue can also be found by using my repository for a simple FPS camera here:

[Video example](https://i.imgur.com/nKcE9GX.mp4)
[Project repository](https://github.com/tavurth/godot-simple-fps-camera)

**Comment by tavurth** [comment]
Working in OSX High Sierra

[Video link](https://i.imgur.com/TH7MDZM.gifv)

![image](https://user-images.githubusercontent.com/100964/53348535-c9a7e780-394d-11e9-8a22-12c72bd7fb28.png)

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 3.2 build?

**Comment by tavurth** [comment]
Tested in Godot 3.2 with the same Mojave as above, it's now working for me

**Comment by akien-mga** [comment]
Awesome, thanks!
