### ISSUE TITLE
Expose get_cell_auto_tile_coord() to the editor

### ISSUE THREAD

**Issue by Aasdyfi** [godotengine/godot#20979]
**Godot version:**

3.0.6 stable

**OS/device including version:**

Windows 10

**Issue description:**

There is a method called get_cell_autotile_coord(int p_x, int p_y) in tilemap.cpp,, but it's not available in the editor. The autotile information is useful to have, especially if you are not using the built-in physics engine but tiled-based collisions, and/or doing animations on a per tile basis, or for some other reason need to know the tile for gameplay specific purposes, like doing damage to the player etc, or placing lights or traps.

**Steps to reproduce:**
Try to use the method.

**Minimal reproduction project:**

**Comment by ysharlaimov** [comment]
I have access to this method in v3.2.
![image](https://user-images.githubusercontent.com/30211339/71450430-f68d7c80-2761-11ea-9739-0e3ec20f0abf.png)

**Comment by ysharlaimov** [comment]
@KoBeWi @clayjohn @Aasdyfi , i think this issue can be closed.

**Comment by clayjohn** [comment]
Great! Thanks for letting us know. :)
