### ISSUE TITLE
UNUSED_CLASS_VARIABLE doesn't work with Dictionary assignment

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#20975]
**Godot version:**
e5ce6b728f2af108fd3c183cc7d9d540adda5193

**OS/device including version:**
Linux 4.17.13

**Issue description:**
![captura de tela de 2018-08-13 11-32-15](https://user-images.githubusercontent.com/1387165/44038261-ce1de8b0-9eec-11e8-93bb-e521b100c699.png)
I think this message should not appear in this case.

**Minimal reproduction project:**
```
extends Node

var test

func foo():
	var json = {
		"condition": test
	}

	print(json)
```

**Comment by guilhermefelipecgs** [comment]
CC @vnen

**Comment by noidexe** [comment]
I have a similar issue. I have a singleton called AvatarLibrary.gd with the following:
```GDScript
[...]
var eyes = {
    adult_eye_12 = preload("res://scenes/avatar/eyes/adult_eye_12.tscn"),
    adult_eye_13 = preload("res://scenes/avatar/eyes/adult_eye_13.tscn"),
    adult_eye_14 = preload("res://scenes/avatar/eyes/adult_eye_14.tscn")
}
[...]
func generate_random():
    var new_config = {}
    [...]
    new_config.eyes = {"id": ArrayPickRandom(eyes.keys()), "color_r": "255", "color_g": "255", "color_b": "255"}
    [...]
[...]
```
When I run the project I will get the following error: 
`0:00:01:0508 - The class variable 'eyes' is declared but never used in the script.`

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by noidexe** [comment]
Still happening

**Comment by akien-mga** [comment]
Seems fixed in the current master branch (note that `Unused Class Variable` warning is disabled by default now, so it needs to be enabled to confirm).
