### ISSUE TITLE
GDScript warnings should not appear as errors.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#20973]
**Godot version:**
Godot 3.1 0fc1c4e

**OS/device including version:**
Windows 10 64bit

**Issue description:**
I like having the warnings in the script editor. But they should not appear as errors when the game launches, this can be confusing and potentially cover up actual errors since if there's too many errors some errors will be dropped.

![errors](https://user-images.githubusercontent.com/11450875/44037381-2f330e06-9ee2-11e8-9943-0d84a54fd0e0.png)

**Comment by akien-mga** [comment]
CC @vnen

**Comment by vnen** [comment]
The only problem is that there's no other way to track warnings if you don't have the scripts open in the editor.

Also, the system treats everything as errors, even though it's only printing warnings (this includes other warnings generated by the engine as well). So maybe we should add a distinction between them.

**Comment by Chaosus** [comment]
This should fix this issue - https://github.com/godotengine/godot/pull/20976
