### ISSUE TITLE
Mono: Image.Load() doesn't recognize res:// outside of editor

### ISSUE THREAD

**Issue by exts** [godotengine/godot#20972]
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10

**Issue description:**
`Image.Load` won't accepted res:// path's in exported projects, but works fine in editor. I was told image.load() wasn't meant for res:// paths (which doesn't make logical sense), so I'm assuming this method is broken or doesn't explicitly state its correct usage in the method name.

**Steps to reproduce:**
1. Create an asset 
2. Try loading it using

```csharp
                var image = new Image();
                image.Load($"res://pathtoasset");
```

3. Create an image texture 
```csharp
                var imageTexture = new ImageTexture();
                imageTexture.CreateFromImage(image, (int) Texture.FlagsEnum.Mipmaps);
```
4. Add it to the scene
5. Run scene to make sure it outputs
6. Export project and watch the image not print to the screen because it can't find the .png path

**Minimal reproduction project:**
Will create one after ludum dare 42

**Comment by FeralBytes** [comment]
@exts shouldn't you be using an absolute path, not a resource path?

**Comment by exts** [comment]
@FeralBytes yes, the above is a placeholder. the original code was something along the lines with:

```csharp
var img = new Image();
img.Load($"{assetPath}/{food.Value}");
```

where `$"{assetPath}/{food.Value}"` looked something like: `res://Assets/Art/Food/Meats/Chicken.png`

**Comment by FeralBytes** [comment]
@exts just to make sure we are on the same page. I am saying the path should not be `res://Assets/Art/Food/Meats/Chicken.png` but rather it should be an absolute path like `/home/user/.godot/myGame/Downloaded/Assets/Art/Food/meats/Chicken.png`. The path could be to any wheres but since you are using things outside of the executable then your path should not be `res://` If the path is interal to the executable then the path should work fine, but you will have to handle 2 conditions when running in the editor use the standard `res://Assets/Art/Food/Meats/Chicken.png` but once exported to executable if you path is dynamically generated realize that the code will be only seeing `res://Assets/Art/Food/Meats/Chicken.png.import`.

**Comment by exts** [comment]
that makes absolutely no sense lol why would you use absolute paths with an api library that targets multiple os's?

If I pass "res://" to any load method it should grab my local resources from the project root. Else the method needs to be renamed to something else

**Comment by FeralBytes** [comment]
Your part about that making no sense is you mis understanding what I meant. as I state if you read the entire post, if the path is a resource within your project then `res://` is fine but outside of your project you will need to use absolute paths. It seemed to me from what you wrote that you were actually trying to load an external file.

I think you need to read [Data Paths](http://docs.godotengine.org/en/3.0/tutorials/io/data_paths.html).

Yes exactly it will grab your local resources from the project root. So lets do this as a test you try and load an asset using the path you provided `res://Assets/Art/Food/Meats/Chicken.png`, not dynamic and tell me if it works.
For reference the method is [`Image.load()`](http://docs.godotengine.org/en/3.0/classes/class_image.html#class-image-load)

**Comment by exts** [comment]
> Your part about that making no sense is you mis understanding what I meant. as I state if you read the entire post, if the path is a resource within your project then res:// is fine but outside of your project you will need to use absolute paths. It seemed to me from what you wrote that you were actually trying to load an external file.

Not the case. I was only loading resources from within the project assets that were exported which have `.stex` files. Using `Image.Load()` does not load those assets, only can I load those assets using `GD.Load()`

Here you can see the code here https://github.com/exts/godotsharp-shortserve/blob/master/App/Food/FoodLoader.cs#L81 this is the updated code.

The original method was:

```csharp
private static void CreateTextures(string type, Godot.Dictionary<string, string> foods, ICollection<FoodItem> foodItemTexturess, string assetPath)
{
    foreach(var food in foods)
    {
        var image = new Image();
        image.Load($"{assetPath}/{food.Value}");

        var imageTexture = new ImageTexture();
        imageTexture.CreateFromImage(image, (int) Texture.FlagsEnum.Mipmaps);

        foodItemTexturess.Add(new FoodItem(food.Key, type, imageTexture));
    }
}
```

> It seemed to me from what you wrote that you were actually trying to load an external file.
You can try compiling that [code](https://github.com/exts/godotsharp-shortserve) and tell me why it shouldn't work with the original method because I'm not looking for an external file.

**Comment by PetePete1984** [comment]
To clarify a bit, Image.Load() seems to expect a path to a physical file: it works when the file is present while you're running the project from the editor, but once you're into exported virtual filesystem .pck territory, Image.Load doesn't get redirected to the imported .stex files (the .png doesn't exist in the .pck at that point).
In contrast to that, GD.Load() explicitly tries to load a Resource and as such probably respects the virtual filesystem (ie it loads the .stex when you tell it to load the corresponding .png).
Absolute or relative paths are irrelevant to the problem.

**Comment by reduz** [comment]
Use GD.Load and import the file as an image. Should probably unbind that
and other functions, as it confuses users.

**Comment by exts** [comment]
@reduz yeah that was the solution to fix my problem. Almost didn't make the ldjam when I ran into the issue 😄. Definitely confused me when I found out.

**Comment by PetePete1984** [comment]
Update: Seems to also be the case for ImageTexture.load()

**Comment by Zylann** [comment]
Please don't remove Image.load, or you will piss off everyone loading non-resource images dynamically in their games :/

**Comment by exts** [comment]
or better yet just have proper support for `res://` and `user://` in exported games because currently it doesn't seem to work @Zylann

**Comment by Zylann** [comment]
@exts does this work?
```gdscript
var f = File.new()
f.open("res://something.x", File.READ)
```

**Comment by exts** [comment]
@Zylann yes that definitely works https://github.com/exts/godotsharp-shooter/blob/master/Application/Core/Formations.cs#L90

I've done it in a tutorial game a while back. Can test it via https://g4mr.itch.io/godotsharp-shooter

**Comment by Xrayez** [comment]
> Please don't remove Image.load, or you will piss off everyone loading non-resource images dynamically in their games and tools :/

@Zylann yep, I really depend on this as it's one of the core features currently used in my game. I extract contours from images and create collision shapes from them dynamically.

As I understand, loading a texture by path will return imported one (`StreamTexture`). What if it can be made that if the loader doesn't find imported texture by path, it should fallback to loading other compatible resource types? In this case it would be `Image`.

```gdscript
var img = load("my_image.png") # returns `StreamTexture` if found, else it's an `Image`
```

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc1](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-1))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by exts** [comment]
@KoBeWi let me try reproducing it today.

**Comment by Xrayez** [comment]
@KoBeWi it seems like this is only a limitation when you try to `image.load` in exported games, which doesn't work, and should likely just be documented there.

The "opposite" use case is here though: #39396 (the warning should be moved to documentation IMO).

**Comment by KoBeWi** [comment]
Tagging as documentation then.

**Comment by Xrayez** [comment]
> Looks like this is intended then.

I wouldn't say this is intended, but that's just a limitation that you have to be aware of. You could optionally try to include all image files while exporting, I would be actually interested if this works:

![Annotation 2020-06-17 202156](https://user-images.githubusercontent.com/17108460/84929343-5c870b00-b0d8-11ea-8388-1f9dbc7a249c.png)

But instead, if you need to load an image specifically, you just need to reimport the texture as an Image resource:

![Annotation 2020-06-17 202452](https://user-images.githubusercontent.com/17108460/84929585-b1c31c80-b0d8-11ea-9730-ec488c544fb2.png)

If you want to distribute some images along with exported project you can also try globalizing the `res://` path before doing so, so that the engine won't look into the virtual filesystem, but instead search for OS filesystem.

```gdscript
static func image_load(filepath):
    var image = Image.new()
    image.load(ProjectSettings.globalize_path(filepath))
    return image
```
