### ISSUE TITLE
[Mono] Editor crashes when building due to exported properties on a resource

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#20987]
**Godot version:**

3.0.6 ( also tested on 80a8636aa )

**OS/device including version:**

Linux

**Issue description:**

The editor will crash with a SIGSEGV error when building.

**Steps to reproduce:**
1. Create a new resource, save it
2. Attach a CS script to that resource
3. Export a property on that script
4. Build the project, everything seems to be OK
5. Add another exported property to the script
6. Attempt to build again, the editor should crash

Note, that deleting the `.mono` folder appears to solve the issue temporarily, but the problem will remerge if these steps are followed.

**Minimal reproduction project:**

[MonoCrash.zip](https://github.com/godotengine/godot/files/2284999/MonoCrash.zip)

Extra debugging info:
`Thread #1 [godot.x11.tools] 8351 [core: 0] (Suspended : Signal : SIGSEGV:Segmentation fault)    
    CSharpInstance::refcount_incremented() at csharp_script.cpp:1,289 0x555556a04f4c    
    Reference::reference() at reference.cpp:70 0x55555ad2c70c    
    Reference::init_ref() at reference.cpp:37 0x55555ad2c5a9    
    CSharpInstance::_reference_owner_unsafe() at csharp_script.cpp:1,251 0x555556a03863    
    CSharpScript::_create_instance() at csharp_script.cpp:1,898 0x555556a0c572    
    CSharpScript::instance_create() at csharp_script.cpp:2,011 0x555556a0d7f1    
    Object::set_script() at object.cpp:984 0x55555ac22b3a    
    Object::set() at object.cpp:432 0x55555ac225a5    
    ResourceInteractiveLoaderText::poll() at scene_format_text.cpp:598 0x555559a24403    
    ResourceFormatLoader::load() at resource_loader.cpp:138 0x55555afc23b1    
    <...more frames...>
`

**Comment by mysticfall** [comment]
When I tested the project with my build(80a8636aa with couple of cherry picked commits), I could not reproduce the problem.

However, when I tried it with my own project I could make it crash by changing a custom property of a resource and save the scene (changing it marked the currently edited scene as modified, even though the resource isn't used anywhere on the project).

The stack trace of the crash looks as follows:
```
Thread #8 [Finalizer] 14270 [core: 1] (Suspended : Signal : SIGSEGV:Segmentation fault)	
	__cxxabiv1::__dynamic_cast() at dyncast.cc:50 0x7ffff5a28691	
	cast_script_instance<CSharpInstance, CSharpLanguage>() at csharp_script.h:56 0x555556a112c7	
	_GodotSharp::queue_dispose() at gd_mono.cpp:979 0x555556a25f76	
	godot_icall_Object_Dtor() at glue_header.h:64 0x555556ad2762	
```
And from the look of it, it might be related to #20718 as both problem occurs with `_dynamic_cast` when it tries to dispose an object.

**Comment by somnivore** [comment]
As of f148e8eedeb1ff2dcf74d6843d1314d7c6db12a7, I can no longer crash the editor using the steps above; attaching scripts to resources, modifying those scripts and rebuilding, modifying the exported properties on the resource, will not crash the editor.  All seems to be OK on my end.

**Comment by akien-mga** [comment]
Great, thanks for testing!

**Comment by somnivore** [comment]
80618700ca668a595fd214ca8db43a69ca2a8b67 Crashing again when building due to exported properties in resources.

**Comment by akien-mga** [comment]
That's a different issue, your original report was about a segmentation fault.

**Comment by somnivore** [comment]
I'll open a different issue
