### ISSUE TITLE
TileSet should have a get_texture method

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#20983]
I need to get the texture path used by a TileSet, but there's no member variable / method to do that.
I can work around this, but it makes sense for the class to have such a method.

**Comment by PetePete1984** [comment]
A TileSet can consist of hundreds of tiles, each with their own texture - which one would you get? `tile_get_texture()` is already available for these specific textures.

**Comment by char0xff** [comment]
You are right. My tiles use the same texture and the "region" variables to use different areas of that texture, which is better for performance, so in my head I was thinking that it's the tileset that stores the texture path, but now I remember that each tile does it.
