### ISSUE TITLE
Godot Docs - Your First Game - 'Mathf' does not contain a definition for 'PI'

### ISSUE THREAD

**Issue by Esharsid** [godotengine/godot#20990]
**Godot version:**
 v3.0.6.stable.mono.official.8314054

**OS/device including version:**
Operating system: 
 Ubuntu 18.04 running under 
  VMWare Workstation 12 Player running on
   Windows 10 Pro

 Intel Core i7, 64-bit, x64

**Issue description:**
Using the C# provided for the main scene of "Your First Game", errors are raised for the three occurrences of Mathf.PI.
http://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html#main-script
![capture](https://user-images.githubusercontent.com/42361511/44066350-ea7620a8-9f3d-11e8-842b-9c1c480d783a.JPG)

![errors](https://user-images.githubusercontent.com/42361511/44066461-682ada48-9f3e-11e8-83fe-d13ffa83437d.JPG)

**Corrective action:**
In Unity, I would have added "using System.Collections;" but that didn't work here.
Instead I used "(float)Math.PI" to replace "Mathf.PI".

**Comment by Chaosus** [comment]
Ah. Its fixed in master branch. For whatever reason its stays incorrect in 3.0 branch.

**Comment by akien-mga** [comment]
Note that such issues should be opened on the https://github.com/godotengine/godot-docs repository.
