### ISSUE TITLE
Exported variables are not updated in the inspector when their value is changed via GDScript

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21009]
v3.0.5 stable, Xubuntu
Making a plugin, if you change the property value of a node via GDScript, that is reflected on the inspector. This doesn't happen with exports, so you have to manually refresh the inspector clicking on something else.
Example project attached.
[Example project.zip](https://github.com/godotengine/godot/files/2287794/Example.project.zip)

**Comment by vnen** [comment]
I think this is expected. The export is done so you change the value for the specific scene, overriding the default. So the value on the scene is kept even if you change the default.

**Comment by char0xff** [comment]
Hrmm... I don't think you understood the problem. It's about the inspector not being refreshed, not about the change of the actual value, which occurs fine. I'm not "changing the default", I am changing the actual value of the exported variable.
Have you tried the example? It contains detailed instructions. If you click on another node and then click back on the effected node, you will see that the value **is** changed. The inspector just didn't refresh that change right away.

**Comment by Zylann** [comment]
I have a similar issue, in my custom node some properties are dynamic depending on which enum value is selected, but to see them update I am forced to inspect something else and go back to my node.
Is there an issue about this already?

**Comment by timoschwarzer** [comment]
I have the same issue. For example, if you make an `EditorPlugin` that moves `Node2D`s, the inspector does not display the updated transform values. If I move the `Node2D` using the default move tool, the inspector does update.
IMO there should be a method in `EditorPlugin` to indicate that a node's property has changed. (e.g. `node_property_updated(node: Node)`)

**Comment by Zylann** [comment]
In C++, what triggers this is `_change_notify("property_name")`: https://github.com/godotengine/godot/blob/master/scene/2d/node_2d.cpp#L54

**Comment by Zylann** [comment]
@timoschwarzer however I wonder what @reduz thinks about this because last time I found this, he wasn't super-happy with this hack

**Comment by Razzlegames** [comment]
In gdscript I used this to update any exported variables if changed in the tool script code: `property_list_changed_notify()`.  Didn't check, but probably calls the `C++`  `_change_notify` for all properties etc.

**Comment by hiulit** [comment]
> In gdscript I used this to update any exported variables if changed in the tool script code: `property_list_changed_notify()`. Didn't check, but probably calls the `C++` `_change_notify` for all properties etc.

This worked for me. Thanks!

**Comment by sean256** [comment]
Considering `property_list_changed_notify` exists and it works, is this even a bug?

**Comment by Calinou** [comment]
@sean256 I think we still need to document this in the GDScript exports documentation.
