### ISSUE TITLE
"Search Help" - Bad selection color

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#21000]
https://github.com/godotengine/godot/commit/9f8e2d5c5bb0ab56630768530025e9e36c4bd445

![image](https://user-images.githubusercontent.com/4741886/44093350-9bfaca50-9fd3-11e8-9998-03942f73e00e.png)

If someone works in a bright environment the selection color(black) is almost not visible on the greyish background. (thinking maybe I should look for a basement to solve this issue thinking )

**Comment by ComradeSparklePony** [comment]
I found that replacing all instances of "selection_color" with another color in `editor/editor_help.cpp` worked (lines 1784, 1866, 1932, 1951).

**Comment by AlexHolly** [comment]
It points to a specific path `"text_editor/theme/selection_color"`.
I don't think using a different name is a good idea.
The setting in the editor is missing too so I added it.
I am not sure if this is right but it works.


https://github.com/godotengine/godot/blob/master/editor/editor_settings.cpp#L360
`_initial_set("text_editor/theme/selection_color", Color::html("006400"));`

Replacing all 4 lines from @ComradeSparklePony 
https://github.com/godotengine/godot/blob/master/editor/editor_help.cpp#L1784
` class_desc->add_color_override("selection_color", EditorSettings::get_singleton()->get("text_editor/theme/selection_color")); `

What would be a good color default color?

**Comment by Calinou** [comment]
> What would be a good default color?

You could try a semi-transparent grey color such as `Color::html("40808080")`, this way, it works on both dark and light backgrounds. However, it will become less visible in low-contrast themes (as the background color becomes closer to gray).
