### ISSUE TITLE
When changing a scene via GDScript the scene is not considered modified

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21011]
When changing anything in a scene via GDScript, the scene doesn't get the "modified" "(*)" tag in the name and you can in fact close it without getting a confirmation message.
Is this by design?

Example project:
[Example project.zip](https://github.com/godotengine/godot/files/2287883/Example.project.zip)
Open Scene.tscn and notice how Rotation Dregrees property in My Node is continuously changing but the scene is not considered modified and can just be closed with no warning.

**Comment by Noshyaar** [comment]
As far as I know this is by design. You have to use `UndoRedo` to manage versions and the editor will be able to tell if the scene is modified.
```gdscript
var ur = get_undo_redo()
ur.create_action('rotate')
ur.add_undo_property(root_node,'rotation_degrees',root_node.rotation_degrees)
ur.add_do_property(root_node,'rotation_degrees',root_node.rotation_degrees + 60)
ur.commit_action()
```
