### ISSUE TITLE
Godot does not update already imported models.

### ISSUE THREAD

**Issue by joleeee** [godotengine/godot#21019]
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10 64-bit

**Issue description / Steps to reproduce:**
1) Export .escn from blender into your project
2) Change the object in blender and then do step 1 again
3) It seems like nothing has changed in godot, but if you duplicate the .escn in godot and then open it you will see the changes.

**Comment by KoBeWi** [comment]
Isn't it basically #22450? Escn files are scenes and they won't update if you have them open. Reloading the scene should update it. Or they won't update at all, @joleeee ?

**Comment by Calinou** [comment]
Closing due to lack of response from OP. Either way, this sounds like a duplicate of #22450.

**Comment by superlou** [comment]
@KoBeWi, I believe I ran into this in https://github.com/godotengine/godot-blender-exporter/issues/331, and reloading the scene wasn't sufficient. I had to delete the `.escn.import` file to get Godot to regenerate the export file and update the scene.
