### ISSUE TITLE
GDNative: Change Dictionary.remove(key) return value.

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#21012]
`Dictionary.remove(key)` now returns `bool` but, as discussed in https://github.com/godotengine/godot/pull/20945#issuecomment-412888960, the changes were not applied to GDNative in fear of breaking compatibility. This issue is for @karroffel

**Comment by karroffel** [comment]
<3

**Comment by akien-mga** [comment]
Fixed by #21602.
