### ISSUE TITLE
GLES2 artifacts with maximized window

### ISSUE THREAD

**Issue by r-mice** [godotengine/godot#21027]
**Godot version:**
3.1.dev.calinou.c4e75aa

**OS/device including version:**
kubuntu 18.04

**Issue description:**
When in Project Settings -> Display -> Window -> stretch, mode is set in 2d or viewport, and aspect is set to keep_height and the scene is play and you maximize the windows, the top and bottom black bars have artifacts and thus not are completly blacks. Is hard to explain, please try it.

**Steps to reproduce:**
Those described above.

**Comment by vnen** [comment]
CC @karroffel

**Comment by r-mice** [comment]
The problem is solved! Thanks @karroffel

**Comment by r-mice** [comment]
Sorry for bothering you again @karroffel , but it seems like the error come back. I do not know what happened.

![screenshot_20180826_154420](https://user-images.githubusercontent.com/39884830/44633330-3d3d4d80-a947-11e8-9fe1-17964db7f046.png)
**The project:**
[artifacts-bars-returns.zip](https://github.com/godotengine/godot/files/2321938/artifacts-bars-returns.zip)

**Comment by karroffel** [comment]
The fix I made broke Android rendering, better have some artifacts than no output at all on many many devices, so we reverted it. I'll have to take another look

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by reduz** [comment]
No, I fixed this already (implemented the black bars), closing.
