### ISSUE TITLE
Function body_shape_entered use of the body_shape to get node of the colliding shape

### ISSUE THREAD

**Issue by maxime4000** [godotengine/godot#21028]
**Godot version: 3.0.6**

**OS/device including version: Windows 10**

**Issue description:**
I want to acheived that bullet can pass some of my collision define by a group. I use body_shape_entered(body_id, body, body_shape, area_shape) to know which collisionShape I touch to know if the bullet need to be kill or not. While it's easier with some hack with the CollisionShape2D, when trying to work with CollisionPolygon2D, it's awful. 

I think the body (which is one of those : StaticBody2D, RigidBody2D, Area2D or KinematicBody2D) should have a member function that is: Node getCollisionNode(int body_shape) which return the node that have been hit in the collision process. That way, I could use body_shape without having to think that maybe the node returned could be null... Even that I not really sure what is suppose to be use has there is no example of body_shape being use... CollisionPolygon2D seem doing optimization in the background for better collision detection and this is why it's annoying and also why I didn't try to reply my answer in the reddit post.

**Edit** : I think I wasn't that clear to begin with. What I ask is some member for getting direct node easier. Being able to get the collision shape node from the body is what I ask because why would I need a number if I can't use it directly on the first line (need to do a function myself). From what I understand, body is not the object/node itself but a CollisionObject. In the documentation it's not said so and debugging doesn't tell you what the object is. Documentation on the member body_shape_entered isn't that clear, at first I though body was only the reference of the colliding object and now I think it's a CollisionObject? Because this GDScript is not a Typed language, sometime it's become hard to know what is the object that is return even more if the type return is inherit from Object which everything is inherit from...
Also, one of the respond on reddit with the _collision_mask_ and _collision_layers_. Having documentation/tutorial on how they work would be great, because I didn't know what they are so I didn't use them. If I knew, I probably wouldn't ask on reddit and wouldn't write the issue on github. 
Also, having exemple at the end of each class in Godot API for signal, member variable, member function that are less obvious could really help understanding why they are there and what are there purpose. I must said that Godot documentation make learning the engine a breeze, but at the same time, when you try doing more advance things, documentation start lacking...

Context : https://www.reddit.com/r/godot/comments/97cy41/area2d_detect_which_collision_shape_it_hit/

**Steps to reproduce:**
See reddit post

**Minimal reproduction project:**
Don't have one, but if it's really need, I will create one later. Just ask me to do it

**Comment by bojidar-bg** [comment]
`CollisionObject::shape_find_owner` and `CollisionObject::shape_owner_get_owner` should do the trick just fine.
Example:
```gdscript
func get_collision_node(body, shape_index):
    return body.shape_owner_get_owner(body.shape_find_owner(shape_index))
```

A method which does this behind the scenes might be nice though.

**Comment by clayjohn** [comment]
I'm confused about what the original post is asking for. But it seems to be addressed. Closing for now.
