### ISSUE TITLE
MenuButton popup appears behind containers

### ISSUE THREAD

**Issue by CRHough** [godotengine/godot#21036]
**Godot version:**
3.0.6-stable_x11.64

**OS/device including version:**

Gentoo Linux/Nvidia GeForce GTX 1080, driver v396.45

**Issue description:**

Menu button popups appear below the rest of the UI. For the image I shrank the widget HBoxContainer so the the top of the popup was visible.

Scene is:
```
Node
--> HBoxContainer
    --> MenuButton
    --> MenuButton
    --> MenuButton
--> HBoxContainer
(other widgets)
```

![menu](https://user-images.githubusercontent.com/1259012/44143169-e151df64-a03f-11e8-95c8-7c3fd6bba5b2.png)

**Comment by Noshyaar** [comment]
Change root node type to `Control`

**Comment by CRHough** [comment]
That was easy. Thank you.
