### ISSUE TITLE
GDScript warnings fill log with junk warnings…

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#21034]
…discarding other, possibly useful ones, when doing things like:

- UNUSED_CLASS_VARIABLE (it is used outside the class)
- UNUSED_SIGNAL (ditto above)
- RETURN_VALUE_DISCARDED (as in move_and_* methods, I care about the effects of the method, not their return value)
- UNUSED_ARGUMENT (it's a predefined signal, you forced me to put it)

…and possibly others I haven't encountered yet.

Is there (or planned) a way of letting the compiler know you know what you're doing?

**Comment by akien-mga** [comment]
CC @vnen

**Comment by vnen** [comment]
> Is there (or planned) a way of letting the compiler know you know what you're doing?

Documentation will be updated, but for now see #19993. You can disable warnings in a file, or in a particular instance of the warning with special comments. You can also disable a type of warning globally in the Project Settings.

**Comment by aaronfranke** [comment]
Also, `RETURN_VALUE_DISCARDED` should not be thrown when a method is called on that line. For example, the return value IS indeed used here, but it's just not stored:

    get_tree().change_scene("res://whatever")

**Comment by akien-mga** [comment]
@aaronfranke In this case it would complain about the return value of `change_scene` (`Error`) being unused, which is true.

**Comment by vnen** [comment]
This is solved already, warnings are not printed to output anymore.
