### ISSUE TITLE
Allow Area collision-notification with StaticBody with a toggle function

### ISSUE THREAD

**Issue by N8n5h** [godotengine/godot#21043]
Godot version:
Godot 3.1

Feature request:
A toggle-based function to enable/disable Area collision notification with StaticBody, expanding the reach of body_entered.
The functionality could be OFF by default so it doesn't break older projects that rely on the old behavior.

Background:
Area doesn't report collision with StaticBody by design.
This functionality results inconvenient when you want to detect when a StaticBody enters a moving Area. 
To get around this you would need to replace the StaticBody with something else, even though it might be ideal for the situation.
So for that reason, I think a function such as "set_staticbody_monitoring" or "set_staticbody_detection" in the Area class that enables the collision notification with StaticBody, could make the best solution for this case.

**Comment by Zireael07** [comment]
Why close? The request seems reasonable...

**Comment by vnen** [comment]
@Zireael07 areas already report contact with static bodies. This is related to the discussion on #21013
