### ISSUE TITLE
TouchScreenButton is not consuming the event

### ISSUE THREAD

**Issue by timokoesters** [godotengine/godot#21041]
**Godot version:**
Godot 3.0.6 stable

**OS/device including version:**
Gentoo GNU/Linux

**Issue description:**
Pressing a TouchScreenButton does not seem to consume the event and is thereby also handled by a _unhandled_input() method. 
I am trying to make a 2D platformer game for Android and make my controls using TouchScreenButtons which trigger a "game_left/right" action. My player also detects if the player presses the screen and looks in the direction of the mouse/touch event (and shoots a bullet). The problem is that pressing the movement buttons (TouchScreenButton) does not consume the event so the player looks (and shoots) in the direction of the buttons.

**Steps to reproduce:**
Load up the minimal project from below.
Press somewhere on the screen. Only the bottom label is changing.
Press on the button. Both the top and the bottom label are changing.
Press 'ui_right' (right arrow). Only the top label is changing. This is the intended behaviour of the button.

**Minimal reproduction project:**
[touchscreenbutton_bug_example.zip](https://github.com/godotengine/godot/files/2290295/touchscreenbutton_bug_example.zip)

**Comment by reduz** [comment]
This is not intended to consume the event, in fact you can use several of them at the same time to create a custom joypad, and it is expected you can press many of them at the same time. I don't see any reason for them to also consume the event, given they don't go via the regular GUI functions.

**Comment by reduz** [comment]
I suppose an option could be added if you optionally wanted this, but I suggest opening a PR or feature request.

**Comment by supagu** [comment]
I've also run into this. I need a way to consume the event to stop my character walking towards the button.
