### ISSUE TITLE
Make the Debugger also display warning color

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#21055]
The Output tab was recently updated to show the color yellow when displaying warnings (#20976), but the Debugger still shows red even if there's only warnings:
![screenshot at 2018-08-15 15-06-45](https://user-images.githubusercontent.com/30739239/44164962-d6de4280-a09d-11e8-94f0-2ce3c80ff5e4.png)

**Comment by aaronfranke** [comment]
CC @Chaosus @akien-mga

**Comment by TheShed412** [comment]
So behavior wise, if you have only warnings it will be yellow, and if it has warnings and an error it will be red?

**Comment by Chaosus** [comment]
@TheShed412 Yes, for now.
