### ISSUE TITLE
KinematicBody2D and move_and_slide with no velocity causes wrong movements

### ISSUE THREAD

**Issue by T4g1** [godotengine/godot#21054]
**Godot version:** 3.1

**OS/device including version:** Windows 10

**Issue description:**
When moving a KinematicBody2D using move_and_slide(): If it hits another KinematicBody2D that is using move_and_slide(Vector2(0, 0)), it push it. The collider should not be moved on impact, it feels like the physic engine glitch and tries to replace bodies causing a body that should not move to move.

**Steps to reproduce:**
Basically:

1. Create two KinematicBody2D with collision shape (one circle and another one with rectangle)
2. Attach scripts to them
3. use _physics_process to move_and_slide() the rectangle one into the second one
4. use _physics_process to move_and_slide(Vector2(0, 0)) the second one

**Minimal reproduction project:**
Minimal project here: https://github.com/T4g1/gd-test/tree/issue_kinematic

**Workaround:** Simply check the velocity length applied to any body for value equal to zero and don't call move_and_slide on bodies that should not move if the velocity is null.

**Comment by reduz** [comment]
I am not sure if I understand, but not calling it is up to you...

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by KoBeWi** [comment]
Nope, the second body isn't pushed anymore.
