### ISSUE TITLE
Use "var: type" instead of "var : type"

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#21057]
When having typed auto-completion enabled, I noticed that it completes as `var : type`, and my question is, **why**?

In Python, the syntax is `var: type`, and as GDScript's syntax is Python-like, I don't see why not have it as this instead.

@vnen

**Comment by raymoo** [comment]
Python has typed variables?

**Comment by YeldhamDev** [comment]
@raymoo https://docs.python.org/3.5/library/typing.html

**Comment by Calinou** [comment]
> Python has typed variables?

Yes, as of 3.5 ([PEP 484 -- Type Hints](https://www.python.org/dev/peps/pep-0484/)).

**Comment by nobuyukinyuu** [comment]
I'd be totally fine with `var:type`, as it's done in Monkey and ActionScript.  As long as these are all valid syntax, I don't necessarily care what the IDE defaults to.  Having an option to retain user formatting the way it does with other operators is fine.  I'm somewhat surprised the IDE enforces a space, but I'm guessing this is probably to reduce ambiguity with `:`'s usage in stuff like one-line `if` statements or something.

**Comment by YeldhamDev** [comment]
@nobuyukinyuu It doesn't. The issue is about the auto-completion.
`var: type` and `var:type` compile fine.

**Comment by vnen** [comment]
Is there other case than when completing virtual functions and making methods for signal connections?

In any case, I'm can change if people prefer that way.

**Comment by OvermindDL1** [comment]
I'm personally used to `var : type` because I work in ML languages fairly often, but I can see the `var: type` thing from python and scala and such...  Personally `var: type` seems very unbalanced to me, but I'm biased.  ^.^;

**Comment by akien-mga** [comment]
No strong opinion either, being close to Python is good in my book, but at the same time `var : type` avoids the confusion with the colon that starts a code block (`func <...>:`, `if <...>:`, etc.).

**Comment by somnivore** [comment]
I feel that `var : type` is clearer.  I use `var := val` much more frequently in any case.

**Comment by YeldhamDev** [comment]
When a language wants its syntax to resamble another, it should stick to it, and deviate only when necessary.

There's a lot of people that don't like GDScript for being a language of its own. Looking like an already exiting and popular one (Python) medigates that effect, but if the default syntax starts deviating too much, that strength starts to weaken.

@akien-mga If this confusion didn't happened in the Python world, I don't see it happening here.

**Comment by OvermindDL1** [comment]
> In general, I've seen var: type in more languages than var : type — for instance, TypeScript and Rust recommend the former syntax in their official style guides.

Yet I've seen `var : type` in (a *lot*) more languages than `var: type`, it depends on the coding world in which you've existed.

> but at the same time var : type avoids the confusion with the colon that starts a code block (func <...>:, if <...>:, etc.).

This is a good point though, I didn't think of this...
