### ISSUE TITLE
"Input.is_mouse_button_pressed"  failes with mouse wheel up and down

### ISSUE THREAD

**Issue by PostPollux** [godotengine/godot#21058]
**Godot version:**
Both, official Godot 3.0.6 and 1c17c2b

**OS/device including version:**
Linux Manjaro

**Issue description:**
"Input.is_mouse_button_pressed"  does not work with mouse wheel up and down. Nothing happens. Left, right and middle mouse buttons work fine.

**Steps to reproduce:**

Just add the following script to a node in the tree, start the scene and test it yourself:

func _process(delta):
	
	if Input.is_mouse_button_pressed(BUTTON_LEFT):
		print ("left pressed!")
		
	if Input.is_mouse_button_pressed(BUTTON_RIGHT):
		print ("right pressed!")

	if Input.is_mouse_button_pressed(BUTTON_MIDDLE):
		print ("middle pressed!")
	
	if Input.is_mouse_button_pressed(BUTTON_WHEEL_UP):
		print ("wheel up!")
	
	if Input.is_mouse_button_pressed(BUTTON_WHEEL_DOWN):
		print ("wheel down!")

**Minimal reproduction project:**
[mouse_wheel_bug.zip](https://github.com/godotengine/godot/files/2291914/mouse_wheel_bug.zip)

**Comment by cbscribe** [comment]
This is not a bug. Mouse wheel "buttons" can't really be in a "pressed" state, they are instantaneous. This means you can't poll them with the Input singleton.

To handle mouse wheel events, you can use `_input()` along with the [`InputEventMouseButton`](http://docs.godotengine.org/en/3.0/classes/class_inputeventmousebutton.html) class.

Example:

    func _input(event):
        if event is InputEventMouseButton and event.pressed:
		if event.button_index == BUTTON_WHEEL_UP :
			print("up")
		if event.button_index == BUTTON_WHEEL_DOWN:
			print("down")

**Comment by PostPollux** [comment]
Thanks for the info! Sorry, I didn't know that.
