### ISSUE TITLE
Large texture on Sprite brings the editor to a crawl, crash

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#21059]
**Godot version:**

3.1 1c17c2b9b39d9c6e7440d25251ac8b1a1fede5bb

**OS/device including version:**

Arch Linux, GeForce GTX 1060 3GB/PCIe/SSE2

**Issue description:**

A large texture (4096x4096) on a Sprite is causing the editor to freeze up when the 2D scene is in any way manipulated.  In-game, the framerates are fine, and as long as the 2D scene is not being manipulated, the framerates are fine.

Possibly related, the output tab is reading the following when the large sprite is selected:
> core/image.cpp:1587 - Loaded resource as image file, this will not work on export: 'res://testroom.png'. Instead, import the image file as an Image resource and load it normally as a resource.

It can also lead to a crash, as I've recently discovered:

> ERROR IN: res://
> ERROR: _get_modified_time: Method/Function Failed, returning: 0
>    At: drivers/unix/file_access_unix.cpp:296.
> ERROR IN: res://icon.png
> ERROR: _get_modified_time: Method/Function Failed, returning: 0
>    At: drivers/unix/file_access_unix.cpp:296.
> ERROR IN: res://testroom.png
> ERROR: _get_modified_time: Method/Function Failed, returning: 0
>    At: drivers/unix/file_access_unix.cpp:296.
> handle_crash: Program crashed with signal 11
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [1] /usr/lib/libc.so.6(+0x37be0) [0x7fd6a9229be0] (??:0)
> [2] EditorFileSystem::reimport_files(Vector<String> const&) (??:0)
> [3] EditorFileSystem::_update_scan_actions() (??:0)
> [4] EditorFileSystem::_notification(int) (??:0)
> [5] EditorFileSystem::_notificationv(int, bool) (??:0)
> [6] Object::notification(int, bool) (??:0)
> [7] SceneTree::_notify_group_pause(StringName const&, int) (??:0)
> [8] SceneTree::idle(float) (??:0)
> [9] Main::iteration() (??:0)
> [10] OS_X11::run() (??:0)
> [11] /home/user/Software/godot/bin/godot.x11.tools.64(main+0xd5) [0x5619c349740e] (??:0)
> [12] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7fd6a9216003] (??:0)
> [13] /home/user/Software/godot/bin/godot.x11.tools.64(_start+0x2e) [0x5619c349726e] (??:0)
> -- END OF BACKTRACE --

**Steps to reproduce:**
Place a large texture on a Sprite, try to move it around.

**Minimal reproduction project:**

[LargeSpriteEditor.zip](https://github.com/godotengine/godot/files/2291966/LargeSpriteEditor.zip)

**Comment by akien-mga** [comment]
As per #21251, this also happens with medium size textures like 750x733 (see attached project).

**Comment by reduz** [comment]
This should be now fixed
