### ISSUE TITLE
Add popup with information about new stable/unstable version of engine.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21065]
**Godot version:**
3.1 dev

**Issue description:**
It would be good to see a little popup when new version of Godot Engine is released. It should be only shown once when new version comes.

![ver](https://user-images.githubusercontent.com/41945903/44196972-b9f94c00-a13d-11e8-91fe-cf82c3821d1c.png)

**Comment by Noshyaar** [comment]
I'd prefer a simple Label that says something like "Update available!", underlined, at the version number and it links to the download page when clicking on it. We have too many popups.

**Comment by qarmin** [comment]
For me the best option, will be add a small bar(like in TV news) at the bottom of the Project Manager.

It should contain the latest news about engine, something like headers from https://godotengine.org/news, and when clicked, they should open a browser with target news

Maybe the bar should move from right to left, like in TV news

I readed #20603, and I think that ideas from this thread, take too much space


Open in new tab to see in full resolution.
![vvv](https://user-images.githubusercontent.com/41945903/44226042-539d1980-a18f-11e8-832b-de31ec753f28.png)

**Comment by vnen** [comment]
Godot doesn't connect to the internet without user intent. At most a "Check for updates" button could be added to demonstrate that intent.

**Comment by KellyThomas** [comment]
Would an opt-in "Check of updates on startup" setting be acceptable?

**Comment by Calinou** [comment]
Do we have a JSON endpoint that we can use to fetch the identifier and release date of the latest stable Godot version? The GitHub Releases API might be suitable here, but we'll need to perform some checks to avoid recommending older version patches. For instance, if someone is using 3.1.2, notifying them when 3.2 is released is fine, but they shouldn't be notified if 3.0.7 is released.

**Comment by aaronfranke** [comment]
Godot displays the version in the corner. Perhaps this could double as a "check for updates" button?

**Comment by Calinou** [comment]
@aaronfranke This would conflict with #35375, unfortunately.

**Comment by qarmin** [comment]
Godot Proposal - https://github.com/godotengine/godot-proposals/issues/1132
