### ISSUE TITLE
Label text entry is going in reverse.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21061]
Not sure what's going on here, but typing into a Label now enters text in reverse order.  Anyone else noticing this?

This is in a build from this morning in the master branch.  Running on Windows 10 with 64-bit editor.

![backwards label](https://user-images.githubusercontent.com/13004169/44179195-4be16480-a0fe-11e8-8d56-9c36909f76f2.gif)

**Comment by Noshyaar** [comment]
Looks like https://github.com/godotengine/godot/issues/19008 has made a comeback.

**Comment by sketchyfun** [comment]
Seems to happen when the length of the text exceeds the available space in the gui item (this happens for other items that have text too)

**Comment by akien-mga** [comment]
Related to #20526.

**Comment by akien-mga** [comment]
Also affects other Controls, e.g. Spinbox (I typed "meters"):
![screenshot_20180816_141710](https://user-images.githubusercontent.com/4701338/44207898-10c34d80-a15f-11e8-8a0a-fd6e22385450.png)

**Comment by avencherus** [comment]
Taking these posts into account, took another look at it this afternoon.  If it helps narrow down the hunt, it seems the problem is specifically the text entry widgets in the inspector. 

When I added an export var for a String type and start typing in it, the same thing happens.

`export (String) var test = ""`

![godot windows opt tools 64_2018-08-16_15-45-44](https://user-images.githubusercontent.com/13004169/44209266-a1a02600-a16b-11e8-81f4-9ed722974263.png)

 LineEdit nodes, at least when running in game, appear fine.

![godot windows opt tools 64_2018-08-16_15-49-47](https://user-images.githubusercontent.com/13004169/44209395-052a5380-a16c-11e8-9eb6-97ce9b06792f.png)

**Comment by Noshyaar** [comment]
Regression from #20400
