### ISSUE TITLE
Can't create folder in domain and can't create project in domain in empty folder.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21070]
**Godot version:**
3.1 calinou c4e75aa

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When I try to create folder in my documents,(my computer is in domain) the error has occurred:

![vvvv](https://user-images.githubusercontent.com/41945903/44204783-67775a00-a154-11e8-976a-739ce0cf5ad3.png)

When I create new folder on desktop and try assign new project to it, it shows that folder don't exist but I'm sure that isn't true, because a bit before i created it(I'm sure that the name is correct).

![vbvbvb](https://user-images.githubusercontent.com/41945903/44204784-680ff080-a154-11e8-956b-dd1513f589fd.png)

**Comment by akien-mga** [comment]
Seems to be the same issue as #16022.
