### ISSUE TITLE
Script which inherits from a class defined by `class_name` keyword does not feature the parent's attributes in the inspector

### ISSUE THREAD

**Issue by OliPerraul** [godotengine/godot#21076]
**Godot version:**

![image](https://user-images.githubusercontent.com/24371247/44208882-b8288c00-a12f-11e8-894c-1b96d84fd0d5.png)

**Related PR**
https://github.com/godotengine/godot/pull/20233

**Steps to reproduce:**
1. Create a gdscript with global scope, using the the `class_name` keyword
2. Declare a an `export(..) var` inside the gdscript
3. Inherit from the declared class from anohter gdscript.
4. Attach the gdscript to a node in the inspector.
5. Notice the the parent node's export attributes are not featured in the inspector. (I tried restarting godot too)

**Comment by DualMatrix** [comment]
This is still broken in master, I feel this is a rather big issue and would make class_name really hard to work with.
