### ISSUE TITLE
Errors after opening new project, !EditorSettings::get_singleton()->has_setting(p_setting)

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21073]
**Godot version:**
3.1 calinou c4e75aa

**OS/device including version:**
Windows 10

**Issue description:**
After opening new project, in console i have a 39 errors:
                                                                              
ERROR: _EDITOR_GET: Condition ' !EditorSettings::get_singleton()->has_setting(p_setting) ' is true. returned: Variant()   
At: editor/editor_settings.cpp:1070

![sssssssssssssssssss](https://user-images.githubusercontent.com/41945903/44207777-a5797b80-a15e-11e8-9a54-52ff74145e83.png)

**Comment by qarmin** [comment]
It only works when I clear editor data, when I use my default engine settings, this errors doesn't occur.

**Comment by akien-mga** [comment]
The error happens due to those two `EDITOR_GET` with no matching previous definition:
```
$ rg "editors/3d_gizmos/gizmo_colors/instanced"
editor/plugins/spatial_editor_plugin.cpp
5659:   Color instanced_color = EDITOR_GET("editors/3d_gizmos/gizmo_colors/instanced");
5701:   Color instanced_color = EDITOR_GET("editors/3d_gizmos/gizmo_colors/instanced");
```
Caused by #20584, CC @JFonS.

**Comment by JFonS** [comment]
I won't be able to fix this for a while, but it's an easy fix. If someone wants to give it a go, adding the EDITOR_DEFs in SpatialEditor::_init_gizmos_menu() should do the trick. These EDITOR_DEFs can be copied from SpatialEditorGizmos constructor (#20584 removes SpatialEditorGizmos, it was in spatial_editor_gizmos.cpp)

**Comment by JFonS** [comment]
@akien-mga sorry, I didn't think about gizmos defined in other modules. 

I think at this point it's better to just change EDITOR_GET with EDITOR_DEF in both EditorSpatialGizmoPlugin::create_material and create_icon_material.

So remove EDITOR_DEFs from _init_gizmos_menu and change the create material methods (adding the default value).

Sorry for the hassle.

**Comment by Jayman2000** [comment]
I’m experiencing this bug in `v4.0.alpha4.official [f47097973]` on Linux, but I only get two of them:

```
Godot Engine v4.0.alpha4.official (c) 2007-2022 Juan Linietsky, Ariel Manzur & Godot Contributors.
  editor/editor_settings.cpp:1062 - Condition "!EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
  editor/editor_settings.cpp:1062 - Condition "!EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
--- Debug adapter server started ---
--- GDScript language server started ---
```
