### ISSUE TITLE
No way to select class items in theme

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#21078]
**Godot version:** 3.1 custom build

**Issue description:**
Themes allow different Items for each class but there is no way to select them. For example, I have a Label with 3 different fonts and I would like to be able to select the font that fit best in that situation.

**Steps to reproduce:**

1. Make a theme
2. Make a class (Label)
3. Make a class item (font)
4. Make another class item (font)
5. Try to apply one of the two fonts in the editor

**Comment by Chaosus** [comment]
Seems like #20320, but not sure whether it a duplicate or not..

**Comment by pycbouh** [comment]
If I understand correctly, Chaosus is correct that this is a duplicate of #20320 and therefore of https://github.com/godotengine/godot-proposals/issues/850. Both of which, I believe, are covered by this PR: https://github.com/godotengine/godot/pull/47544.

**Comment by pycbouh** [comment]
https://github.com/godotengine/godot/pull/47544 and https://github.com/godotengine/godot/pull/50169 make it possible to define variations of theme classes and pick them from a list in the Inspector (and set them via code too if needed).

I don't think that in the foreseeable future we will be able to pick from a list of available items on a single class, so this is the solution that we have for this problem. So I'll close this.
