### ISSUE TITLE
One-click deploy on Android fails if "Clear previous install" is unchecked

### ISSUE THREAD

**Issue by salalex** [godotengine/godot#2107]
When using one-click deploy to install a game to an Android device, the installation fails with INSTALL_FAILED_ALREADY_EXISTS if the "Clear previous install" option is unchecked and the .apk is already installed.

If the .apk is already installed, the `adb install` command needs the `-r` flag (replace existing application) to properly install the updated version.

The fix should be trivial: simply adding `args.push_back("-r");` at line 1538 of platform/android/export/export.cpp should solve the issue:
```C++
args.push_back("install");
args.push_back("-r");   // <- Add this
args.push_back(export_to);
```

**Comment by kubecz3k** [comment]
I can confirm this behaviour in 2.0 Alpha b2f9acb8c96aed0505cbac21661e21e4acef710f build. Would be nice addition to have -r option in this case

**Comment by reduz** [comment]
This does not work becasue Android does not allow you to re-install the project if you installed it with a different computer or certificate, you have to clear and install again

**Comment by salalex** [comment]
Yes, this is true, but even if you re-install from the same computer with the same certificate, you need to add the '-r' option to 'adb  install' (at least with adb 1.0.32), otherwise the installation fails.
