### ISSUE TITLE
Bind method ItemList::set_item_custom_fg_color

### ISSUE THREAD

**Issue by Zzzzac** [godotengine/godot#21086]
**Godot version: All**

**Issue description: bug**

The **set_item_custom_fg_color** method of the ItemList class is visible in the script api but doesn't exist in the engine.

**Comment by vnen** [comment]
I don't see this function in any documentation, online or in-editor, for any current version of Godot (looked at 2.1.5, 3.0.7, and a recent master build).

Do you have a specific version of Godot with this? Can you post a screenshot?

**Comment by akien-mga** [comment]
I think they want the existing function to be bound for the scripting API:
```
$ rg set_item_custom_fg_color
scene/gui/item_list.h
163:    void set_item_custom_fg_color(int p_idx, const Color &p_custom_fg_color);

scene/gui/item_list.cpp
172:void ItemList::set_item_custom_fg_color(int p_idx, const Color &p_custom_fg_color) {

editor/plugins/script_editor_plugin.cpp
1685:                   script_list->set_item_custom_fg_color(i, hot_color.linear_interpolate(cold_color, v));
```

But unless you explain *why* you want it, it's unlikely that we'll bind it.

**Comment by Zzzzac** [comment]
I need this to differentiate two types of items in my game. Blue ones and red ones.
I reallllly need this feature.

**Comment by akien-mga** [comment]
Makes sense, and the equivalent methods for background color are bound already, so foreground should be added too.

**Comment by Zzzzac** [comment]
Thx <3
