### ISSUE TITLE
glTF: Use the vertex colors when available

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#21087]
**Godot version:**

tip de0fb0798ed1c8d16633da9b4d29ce4114f25540

**Issue description:**

![image](https://user-images.githubusercontent.com/4047289/44227143-31f16180-a192-11e8-98c1-e9ac1a65516a.png)

After the import you have to change each material manually:

![image](https://user-images.githubusercontent.com/4047289/44227338-a0362400-a192-11e8-8c6b-e5eafc662272.png)

**Comment by fire** [comment]
Can you post a sample project?

**Comment by paulmiller** [comment]
I think they're saying they want "use as albedo" to be enabled automatically if the model has vertex color info. Assuming that's what they meant, I disagree. "Use as albedo" is a property of the material, not the model. The material's properties shouldn't change depending on which models are using it.

**Comment by paulmiller** [comment]
I think they're saying they want "use as albedo" to be enabled automatically if the model has vertex color info. I personally wouldn't want that - at least, not for materials outside the model's own gltf file. It'd be very confusing for the material's properties to change depending on which models are using it.

**Comment by fire** [comment]
I'm not able to find a gltf2 spec description that allows this. https://github.com/KhronosGroup/glTF/tree/master/specification/2.0

**Comment by capnm** [comment]
> So I'm asking for a valid gltf2 file.

It feels like someone is calling me from the grave :-)

[waiting-for-godot-5.0.zip](https://github.com/godotengine/godot/files/5013282/waiting-for-godot-5.0.zip)

![grafik](https://user-images.githubusercontent.com/4047289/89136341-7e770880-d533-11ea-912a-0739bb0f0682.png)
```
Validation report

    Format: glTF 2.0
    Generator: Khronos glTF Blender I/O v1.2.75
    Stats:
        1 draw calls
        0 animations
        0 materials
        22269 vertices
        8217 triangles
    Extensions: None
```

https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#geometry


![grafik](https://user-images.githubusercontent.com/4047289/89136426-f9d8ba00-d533-11ea-9337-5ab7c5c37166.png)

**Comment by fire** [comment]
Try this https://github.com/godotengine/godot/pull/41007.

**Comment by capnm** [comment]
> Try this #41007.

I guess for 3.2.x this should be:

```

				Ref<Material> mat;
				mat.instance();
				mat->set_flag(Material::FLAG_ALBEDO_FROM_VERTEX_COLOR, true);
```

right?

**Comment by fire** [comment]
Looks good on a first glance. Haven't ported the vertex color patch over though. In the middle of something.

**Comment by capnm** [comment]
> Looks good on a first glance. Haven't ported the vertex color patch over though. In the middle of something.

I figured it out, someone renamed the [SpatialMaterial](https://docs.godotengine.org/en/stable/classes/class_spatialmaterial.html#class-spatialmaterial) :face_with_head_bandage: 
Also works with objects that have textured and vertex-colored surfaces combined.

Added to my 3.2.x patch set :-)
Thanks!


[texture-and-vertex-color-a01.zip](https://github.com/godotengine/godot/files/5023417/texture-and-vertex-color-a01.zip)

![grafik](https://user-images.githubusercontent.com/4047289/89321301-15060f80-d683-11ea-8a57-2f5071bb23c4.png)

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/pull/41007#issuecomment-686560389, this can be done on a per-project basis by setting the default import preset for glTF in the Import dock.

**Comment by capnm** [comment]
> See #41007 (comment), this can be done on a per-project basis by setting the default import preset for glTF in the Import dock.

I'm not sure which preset you're talking about, at least in the glTF / Scene preset in 3.2.x I couldn't find any related options.
Please try to import the [waiting-for-godot-5.0.zip](https://github.com/godotengine/godot/files/5013282/waiting-for-godot-5.0.zip) file.

Anyway, thaks for the fish ...

**Comment by akien-mga** [comment]
Reopening as per https://github.com/godotengine/godot/pull/41007#issuecomment-686653280 and further IRC discussion.
