### ISSUE TITLE
GLES2: Canvas item shader for TextureRect

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#21097]
**Godot version:**
Godot 3.1 1c17c2b9b39d9c6e7440d25251ac8b1a1fede5bb

**OS/device including version:**
Windows 10

**Issue description:**
In GLES2 mode function `texture` in  `canvas_item` type shader for TextureRect node returns always value from `TEXTURE` variable.

For example this shader for both cases returns value from `TEXTURE`
```cpp
shader_type canvas_item;

uniform sampler2D mask_texture: hint_albedo;

void fragment() {

	COLOR = vec4(texture(TEXTURE, UV).rgb, texture(mask_texture, UV).r);
}
```

**Minimal reproduction project:**
[godot-canvas-shader-test.zip](https://github.com/godotengine/godot/files/2295907/godot-canvas-shader-test.zip)

**Comment by akien-mga** [comment]
CC @karroffel
