### ISSUE TITLE
glTF: Nodes are parented incorrectly, skeleton is duplicated

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#21092]
**Godot version:**

tip de0fb0798ed1c8d16633da9b4d29ce4114f25540

**Issue description:**

Nodes in Blender:

![image](https://user-images.githubusercontent.com/4047289/44233439-26a73180-a1a4-11e8-9748-6f8144a0bdea.png)

The nodes in the scene that are imported with Colada-importer look sane and the translation through the animation is correct:

![peek 2018-08-16 21-56](https://user-images.githubusercontent.com/4047289/44232263-c19e0c80-a1a0-11e8-82b4-784400e0cad8.gif)

A scene imported with glTF has a strange node structure and duplicated skeletons. The skeleton is not parented on the object node of the rig, so the animation translates the model into the middle immediately after launch:

![peek 2018-08-16 21-59](https://user-images.githubusercontent.com/4047289/44232794-6836dd00-a1a2-11e8-8899-aea26f3f373a.gif)

Duplicate skeletons on wrong positions (a model without exported pose animation) demonstrate the broken node structure:

![image](https://user-images.githubusercontent.com/4047289/44233293-c0221380-a1a3-11e8-8b69-96d1f4a72f85.png)

**Comment by fire** [comment]
Can you provide a sample project.

**Comment by reduz** [comment]
I have no idea what is going on here, but GLTF2 Specification is clear in that meshes affected by skeletons must ignore their hierarchy and behave as if they were transformed by them, so this is why you see the re-parenting.

**Comment by capnm** [comment]
I didn't have time to dig deeper, sorry. But if I look at the node structure in Blender and glTF, it is very similar. There is only one skeletal parent and all bones are children. No idea why your importer creates multiple, mis-translated skeletons and unconnected node that should actually be the parent:

![screenshot from 2018-08-28 00-58-53](https://user-images.githubusercontent.com/4047289/44691636-baf47c80-aa5f-11e8-9ca2-4fc3dfdb5a85.png)

![screenshot from 2018-08-28 01-01-36](https://user-images.githubusercontent.com/4047289/44691644-c3e54e00-aa5f-11e8-96a2-ea23c77f1c3d.png)



Slightly off topic: tomorrow I will try to generate the scene in escn. Do you think that it could somehow be extended with a pure binary format (ebscn ...), similar to the gltf + bin format?

**Comment by fire** [comment]
You can see how the import breaks from your sample project. There's something strange with your [glb](https://github.com/godotengine/godot/files/2434963/schwert-03-04.zip). This video is the [view in Godot Engine](https://youtu.be/r6iR9HS788w ).

This is the [view in Microsoft 3d builder](https://youtu.be/tk5M4kLUhEE) of my fbx to gltf workflow. I took the sample blender and exported it to fbx and then to [gltf2](https://github.com/godotengine/godot/files/2434906/schwert-03-04-590deac1e9e983c0782c44e83066fbef.zip). As you [can see](https://youtu.be/qfiZJTZbb8U) it looks ok.

No idea why this happens.

**Comment by fire** [comment]
The https://user-images.githubusercontent.com/4047289/44306095-e43e4a00-a387-11e8-9191-50267ff5c2b4.gif animation shows two problems.

A) the export is exported with different scale and unit conventions (like what is up) 

B) is as discussed before the non uniform scaling.

> \<reduz> Yes, we already discussed this. Need to break compatibility for fix
> \<iFire> yes.
> \<reduz> So not happening until 3.2/4.0

**Comment by reduz** [comment]
Yeah this can't be properly fixed without breaking compatibility. I will kick for 4.0 and make sure to fix it there.

**Comment by fire** [comment]
https://github.com/godotengine/godot/commit/0ab1726b43dbe81c96d208a41a582435b76fd058 Tested on master and appears to be fixed.
