### ISSUE TITLE
Create engine.cfg from command line

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2109]
I need to add an option to create empty project in current directory (or one specified by path)
to use in scripts. 
Use case: I create deploy project for showcase and want to keep my current development to myself, I run script wich creates empty project and copies stuff from development project, then runs godot binary with -e without using launcher which is not very useful with large number of template projects.
Then I can quickly edit new project and export it. This doesn't clutter launcher window with many
crappy one-time-usage projects.

This usage scenario is not possible without this feature.

**Comment by punto-** [comment]
Did you try "touch engine.cfg" or something similar? An empty engine.cfg
file (as in, 0 bytes) is enough to run godot -e on it.

**Comment by slapin** [comment]
I think clear feature should be added, as this seems to be hack to me, and undocumented.

**Comment by slapin** [comment]
If 1.2 target is usability, I think this feature aligns perfectly with that.

**Comment by kubecz3k** [comment]
Triaging this issue:
I assume this issue for now could be solved by documenting the fact that it's possible to create project manually and load it to editor by creating empty folder with empty engine.cfg file.
However not sure if this enough in the long term, maybe this command line option would be more straightforward and self explanatory?

**Comment by reduz** [comment]
touch engine.cfg

done

**Comment by slapin** [comment]
Well, that is fine, but ability to reuse engine.cfg (keybindings/action
binding and various settings) should be better. Also, touching engine.cfg
looks redundant and not nice. I think fully-featured project creation
commandline should be implemented, which could be extended
in future for template usage, for example.

**Comment by kubecz3k** [comment]
All main developers have spoken, and it seems that creating empty engine.cfg is official way of creating projects from command line. I'm assuming it's a matter of documentation now. Investigating things further it seems that this documentation is already written: http://godotengine.org/projects/godot-engine/wiki/Command_line_tutorial 
Taking this all into account I think that this issue in it's current form should be closed now.
