### ISSUE TITLE
Changing the X position of several selected nodes also changes the Y value.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21104]
**Godot version:**
3.1 dev calinou d906746

**OS/device including version:**
Windows 10

**Issue description:**
- [x] 1. I select two nodes and deselect one or two, I can still move two Nodes. 
Look at the MultiNodeEdit at the bottom and you can see that only VBoxContainer is selected but when I change x coordinate in inspector it still move previously unselected node.
![ziemniakq](https://user-images.githubusercontent.com/41945903/44959122-2cae4980-aeea-11e8-8f1d-655b093218a9.png)
- [ ] 2. I don't know if it is bug so don't open new issue(if this is a issue, then I create a new one), so when I try change position two selected Nodes with axis X, then also Y axis is changing 
- [x] 3. When I unselect a node from Scene panel, the selection is still present until I move Mouse over 2D viewport (Duplicate #5885, fixed with #21316)

I can't find duplicate issue, but I'm almost sure that exist for 2,3 points

**Steps to reproduce:**
1,2,3 point
https://streamable.com/6ph3u

3 point
https://streamable.com/quf1n

**Comment by AlexHolly** [comment]
duplicate https://github.com/godotengine/godot/issues/5885?
Can you test if everything works on master branch?

**Comment by qarmin** [comment]
Yes, third point is duplicate and it works in master

**Comment by AlexHolly** [comment]
Replacing "" with "x" or "y" will update the right value but this information is still missing.

https://github.com/godotengine/godot/blob/12290c172a6dd3763670d36039fbac8198e711f5/editor/editor_inspector.cpp#L1967
https://github.com/godotengine/godot/blob/12290c172a6dd3763670d36039fbac8198e711f5/editor/editor_inspector.cpp#L1993

https://github.com/godotengine/godot/blob/12290c172a6dd3763670d36039fbac8198e711f5/editor/editor_inspector.cpp#L1890

https://github.com/godotengine/godot/blob/12290c172a6dd3763670d36039fbac8198e711f5/editor/editor_inspector.cpp#L1912

**Comment by qarmin** [comment]
Better visual representing first point
https://streamable.com/hzllg

Look at the Restart button, when I deselect it, Godot still think that it is in MultiNodeEdit mode and when I change position in Inspector, it change position Restart button too.

**Comment by groud** [comment]
I marked the first issue as solve. I opened a more generic version there #22479.
Please open an issue for each point next time.

**Comment by groud** [comment]
And the second point is a consequence of the first one. So closing the issue. :)

**Comment by qarmin** [comment]
@groud Really second is a consequence of the first one? 
I don't think so, look at the AlexHolly pull request https://github.com/godotengine/godot/pull/21701. 
This repair only second point, so or this pull is partial or this is completely different issue.

**Comment by groud** [comment]
> @groud Really second is a consequence of the first one?

Sorry I misread, indeed it's not.
