### ISSUE TITLE
For loop (with range) is always generate unused variable warning

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#21102]
**Godot version:**
68676c7

**Issue description:**
IMO "for" loops should not spawn this warning to log, because its often used just for iteration and temp value can be not used at all

![image](https://user-images.githubusercontent.com/3036176/44253274-bdf1a080-a207-11e8-9226-aece9d1a12d5.png)

**Comment by Noshyaar** [comment]
Interestingly, `for i in 2:` doesn't raise the warning.

**Comment by PelegMedia** [comment]
While trying to clean the logs to hunt for real problems, I find two annoying ones.

One of them is the above.  I even naturally tried _ hoping it will work. 
The other one is integer division. No matter what I do or cast it keeps showing,
@karroffel suggestion is great +1 for that.
Additional option to silent warnings via settings or event better via code (to specific code blocks) will also help.

**Comment by okynos** [comment]
This workaround works like a charm!
```
for _i in range(X):
```

**Comment by PelegMedia** [comment]
Thank you @okynos ,

Yes, I know this issue already solved in one of the 3.x releases.
I guess this issue is not relevant anymore.
OP ( @Chaosus  ) should decide if he wishes to close it.

**Comment by BaddRadish** [comment]
can we get new syntax for this like `for 2:` sheesh
