### ISSUE TITLE
[script editor] auto-wrap / line breaking / line wrap / word wrap

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21101]
I think the editor is missing a word wrap option. Very useful when typing long strings / comments.
In the implementation, it's important to not display the line number in the "child lines".

![auto-wrap example](https://user-images.githubusercontent.com/10872697/44252392-4b2ef800-a1fc-11e8-8959-48a4bfa777cc.png)

**Comment by akien-mga** [comment]
The feature exists already, albeit maybe not in the most obvious category:
![screenshot_20180817_104522](https://user-images.githubusercontent.com/4701338/44256840-a536ba00-a20a-11e8-8e3e-1cb0e07a83be.png)
![screenshot_20180817_104545](https://user-images.githubusercontent.com/4701338/44256860-b253a900-a20a-11e8-9e8c-18dbb67b3ee3.png)

**Comment by char0xff** [comment]
I swear that I don't have the whole "Text Editor" section. 
I'm using v3.0.5.stable on Xubuntu.

**Comment by char0xff** [comment]
I don't have it 0_o
I've also tried the search bar, no luck.
The language is italian, if it could be a problem with the localization. Hrmm...
![wth](https://user-images.githubusercontent.com/10872697/44284213-1f922900-a261-11e8-984d-325e5ade6af6.png)
