### ISSUE TITLE
QOL: Box Containers string select unintuitive nodes in Create new Node.

### ISSUE THREAD

**Issue by PrinceMerluza** [godotengine/godot#21100]
**Godot version:**
3.0

**OS/device including version:**
Windows 10

**Issue description:**
Typing in 'vbo' in Create New Node does not default to VBoxContainer but to 'VehicleBody'.  VBoxContainer will only be selected upon typing up to 'vbox'.

Worse, in typing 'hbox', it selects 'CheckBox' instead of 'HBoxContainer'. You need to type up to 'hboxc' to get the HBoxContainer.

**Comment by KoBeWi** [comment]
Sounds very similar to #21726
Looks like all search fields might be affected.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/46427, as that issue has more information about the problem at hand.
