### ISSUE TITLE
[Regression] Nothing but black screen on Android with GLES 2.0

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#21103]
**Godot version:**

3.1.dev 68676c774d4f3b7bfad8866a08546acf5a594cdf

**OS/device including version:**

Android 8.0 / Galaxy S8+

**Issue description:**

Everything works but nothing shows on screen but black with 0ef85b55e004f1b4a68aa57f9ae3a4a88ad1ee4c
it works fine if reverting it.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by volzhs** [comment]
Note that, it works fine on desktop but not on mobile.

**Comment by quendera** [comment]
Same behaviour on my end.

**Godot v**: v3.1.dev.calinou.1c17c2b
**Android v**: Android 7.1

**Comment by dumitru-stama** [comment]
Same here
Godot v3.1.dev
Commit: c93888ae71bcc2b633f335b407c75412a493012d
Android: Android 9
