### ISSUE TITLE
Strange behavior when resizing editor window that has 0 or 1 pixel height

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21107]
**Godot version:**
3.1 dev calinou d906746

**OS/device including version:**
Windows 10(Probably this is Windows issue not Godot)
Intel HD 4600

**Issue description:**
When I try resize window which have 0 or 1 pixel height(I don't know how much exactly), window change self position.
It is related with #14806

https://streamable.com/jw1r6

**Comment by clayjohn** [comment]
Is this relevant in 3.1. There were some changes with window handling.

**Comment by qarmin** [comment]
Still happens with Godot 3.2 Beta 4 on Intel HD 3000

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

I can't reproduce (although the video is dead). Also the linked issue is resolved on master, so maybe this one is no longer relevant too.

**Comment by qarmin** [comment]
I don't have anymore access to Windows and can't test it, so I think that it may be closed.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/24702 and https://github.com/godotengine/godot/pull/37260.
