### ISSUE TITLE
How To Create A Game Like This

### ISSUE THREAD

**Issue by mikrokode** [godotengine/godot#21119]
Hi,

I interested in creating a multiplayer 3D game using Godot. My I know How can I start it ? Where can I find a full tutorial to create a first person and third person game like https://www.youtube.com/watch?v=btazdd8jNEc  ?

**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Noshyaar** [comment]
http://docs.godotengine.org/en/3.0/index.html

**Comment by Noshyaar** [comment]
I posted the link to the docs and removed it. Let's pretend that didn't happen.

I want to know:
1. where have you looked for the tutorial/documentation and unable to find it?
2. why do you seek for the answer from this issue tracker first?

This might help us improve beginner's experience in the future. Thanks!

**Comment by groud** [comment]
This is not the place to ask for how to use the engine, but to ask for new features/file bugs. Please ask into other  community channels (facebook, reddit, etc...)
