### ISSUE TITLE
CSG: Resizing shapes using opposite side instead of center

### ISSUE THREAD

**Issue by mrzapp** [godotengine/godot#21120]
**Godot version:**
3.1-dev

**Issue description:**
When resizing a CSG shape (or any shape, probably), the resizing is done from the center on the chosen axis, forcing us to move the Spatial node for every adjustment to the shape. Also mentioned [here](https://github.com/godotengine/godot/issues/17411#issuecomment-413239933)

**Solution:**
I propose that, when holding down a modifier key, the shape is resized using the opposite side as an anchor rather than the center.

**Comment by CptPotato** [comment]
What exactly do you mean by 'opposite' side?

**Comment by nodefish** [comment]
Resizing a CSG Shape (or even collision extents) expands/shrinks both sides from the center of the shape. This makes it very hard to judge the resulting size, and very often you have to re-adjust the position of the shape after doing it.

It would be much easier to work with if you could resize non-symmetrically, in 1 direction only, e.g. in the case of a cube, moving a single face like so: https://imgur.com/a/Gyqm6OL

(The above is using a simple tool I wrote in GDscript to make it faster and less finicky to resize CSG shapes).

**Comment by mrzapp** [comment]
@nodefish Please go ahead and share it, I don't see how it couldn't be helpful.

And thanks for supplementing with your explanation, it was a lot more precise than mine.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/452, as feature proposals are now tracked on the Godot proposals repository.
