### ISSUE TITLE
[Editor] Default color of multi-line string (""") should be different than comments color

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21127]
Minor bug.
<code>""" comment """ var x = 0 """ comment """</code>
<code>""" comment """ var x = 0; """ comment """</code>
<code>var x = 0; """ comment """ var y = 0;</code>
<code>var x = 0; """ comment """ var y = 0</code>
These all fails with:
_Expected end of statement after expression._

It's probably even intentional, but it can be useful when you want to quickly experiment with code, e.g.:
**node.position =** _"""old_position +"""_**new_position**

**Comment by vnen** [comment]
It's not a comment, it's actually a string. It can be used as multi-line comment but it still needs to standalone.

**Comment by char0xff** [comment]
Uh... that's confusing to say the least, since it's displayed in the same gray color of # comments. I honestly always thought it was multi-line commenting. The color should definitely be changed.

**Comment by char0xff** [comment]
Closing this and making a better issue description: #21142
