### ISSUE TITLE
[Script editor] "word_wrap" option missing in Editor Settings

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21126]
The _word_wrap_ option is missing in my EditorSettings.
![wth](https://user-images.githubusercontent.com/10872697/44285079-3c7c2b80-a264-11e8-9369-3fb74bd383fb.png)

I'm using **v3.0.5 stable** on **Xubuntu**

**What I've tried:**
I've also tried the **search bar**, but the option doesn't list.
I have deleted all the _"godot"_ folders in my /home directory and ran the program again.

https://github.com/godotengine/godot/issues/21101#issuecomment-413961183

**Comment by akien-mga** [comment]
It's a 3.1 feature.
