### ISSUE TITLE
CSG: co-planar faces break algorithm

### ISSUE THREAD

**Issue by nodefish** [godotengine/godot#21125]
**Godot version:**
3.1.dev

**OS/device including version:**
Win10 64 / GTX 980 Ti

**Issue description:**

Using union, subtraction or intersection on CSG nodes with co-planar / overlapping faces breaks the CSG algorithm and results in either missing faces or clipping.

![image](https://user-images.githubusercontent.com/16632464/44284663-933d3180-a273-11e8-8bbe-a6d5224abdbb.png)

Adding a small jitter (e.g. translating by 0.01) resolves the issue as it makes the affected faces not co-planar, but this creates significant workflow strain that adds up.

**Steps to reproduce:**

- Add 2 CSGBox (or other CSG node) in the same CSGCombiner
- Place them such that 2 of their faces are co-planar, e.g. try making a staircase with `union`

*Bugsquad edit (keywords for easier searching):* coplanar

**Comment by bojidar-bg** [comment]
Can confirm, this is quite a nuisance when playing around with CSG-s.

**Comment by MikeSchulze** [comment]
this bug still occurs on 3.2.1

**Comment by Calinou** [comment]
@MikeSchulze Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
@MikeSchulze This is because the fix wasn't cherry-picked to 3.2.1. Due to how big the PR to fix it was (over 1,000 modified lines), it would be difficult to cherry-pick it for a later 3.2.x release.

**Comment by MikeSchulze** [comment]
@Calinou thanx for this information. Me was not clear this fix was only merged into master
@madmiraal very good to you create a pull request to bring the fix in 3.2.x  ;)
