### ISSUE TITLE
TileMap editor not cleaning everything when painting with multiple tiles

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#21128]
**Godot version:** c93888ae71bcc2b633f335b407c75412a493012d

**OS/device including version:** Win 10

**Issue description:**
1. Paint some stuff on a TileMap
2. Paint with multiple tiles over what you did in step 1.
3. TADADADA!
![2018-08-17_22-17-51](https://user-images.githubusercontent.com/437025/44287220-53bf1700-a26c-11e8-9829-e0e5bf79de93.gif)

I'm not sure if it's intended but it can lead to a weird feeling when you want to completely cover what you first draw.
![2018-08-17_22-37-51](https://user-images.githubusercontent.com/437025/44287776-49058180-a26e-11e8-9682-ec2d1528c300.gif)

As you'd imagine, the same thing happens when you're trying to duplicate or move a selection.  
I thought it has something to do with y-sort at first but it also happens when y-sort is disabled.

**Comment by Zylann** [comment]
Wait, those big tiles you place are actually way larger than one tile. They are not "multi-tiles", they still occupy one cell so they won't overwrite what's behind them.

With Y-sort disabled that will just happen all the time just like with regular sprites. So you better should order draw calls with Y-sort.

Also I experimented a bit with tiles larger than a cell, and I would recommend you position their pivot in a way that it is aware of sorting from its position. For example, the origin of a tree should be the bottom of its trunk. The origin of a house should be its front door, etc.

However that only works if the "parts" of the tile dont conflict with others in terms of "height".
for example, you are trying to layer your house on top of grass, which is however at the same height in the same tilemap, so it is going to conflict with neighbors it overlaps on. So you would need a second tilemap anyways for this layering to work.

**Comment by paulloz** [comment]
@Zylann I'm unsure what's the difference for your between *“drawing multiple tiles”* and *“drawing something larger than a tile”* (as long as that something's size is a multiple of the tile size it is multiples tiles by essence).  

I agree that my first example is a bit biased as that shouldn't be on the same TileMap layer. However, editing TileMaps still feels weird sometimes.  
As I said, I'm unsure if this is totally an intended behaviour or not, but I'm going to close and experiment further with offseting and stuff.

**Comment by Zylann** [comment]
Drawing multiple tiles means they xan be ordered separately, or even replace others. Something larger than a tile is a single thing so it can only occupy one cell and can only be drawn all at once.
