### ISSUE TITLE
Not optimal usage of enet_host_service() in networked_multiplayer_enet.cpp

### ISSUE THREAD

**Issue by shinyclaw** [godotengine/godot#21121]
The last parameter (wait time) is set to 1 while it should be 0. ENet always process all queued events, so it is a waste of processing time.

Also, the comment above: "Wait up to 1000 milliseconds for an event." has no sense :)

**Comment by akien-mga** [comment]
CC @godotengine/network

**Comment by Faless** [comment]
> The last parameter (wait time) is set to 1 while it should be 0.

I agree, but maybe we might want to add a timeout option to the `poll` function of `NetworkedMultiplayerPeer` to limit the time spent in the cycle even if there are still events in queue.
And then expose that in `MultiplayerAPI`.
What do you think?

> Also, the comment above: "Wait up to 1000 milliseconds for an event." has no sense :)

Yeah, probably a left over comment from initial stages of development. Will fix along with this :)

**Comment by Faless** [comment]
> Remember that if you pass 1000 as a timeout to enet_host_service() it will block the execution for one second every frame

Well, not exactly, it will wait for **up to** `1000ms` for an event, but would return as soon as an event is received.

> This may be a good solution for some cases (e.g. debugging) but in a normal situation

That is also a good solution if you use threading (and remember, by default it will be 0).

> Another problem that I see is that poll() method is called every frame

@shinyclaw  You can disable that with latest changes and do your own polling so you can implement all the logic you want -> [see multiplayer_poll](http://docs.godotengine.org/en/latest/classes/class_scenetree.html#member-variables) member variables.

> Of course, this requires client-side prediction, server reconciliation, and interpolation - it is rather easy to achieve this, but it will be great if Godot can do this by hand

This is very game specific, and hard to generalize at engine level.
Server reconciliation is really dangerous and IMHO helps cheaters.
All this can be implemented by hand with not much effort, but if it can be generalized I wouldn't be against it.

**Comment by shinyclaw** [comment]
Thanks for clearing things out - I missed the multiplayer_poll part.

> Server reconciliation is really dangerous and IMHO helps cheaters.

So, in your opinion, what is the best way to implement dedicated server logic? I have found this article: https://mrminimal.gitlab.io/2018/07/26/godot-dedicated-server-tutorial.html, but I'm not sure that creating two separate projects is the best way...

**Comment by Faless** [comment]
> So, in your opinion, what is the best way to implement dedicated server logic?

Well, all the other techniques are fine (and should be used), it's just server reconciliation that is cheater-prone. Although, depending on your game, you might need it in the end (e.g. for FPS where bullets are RayCast), I think it should be avoided unless really necessary, especially now that users playing *real time online games* are usually on good connection (either home if they can, or Internet Cafe), or prefers to play LANs with friends.
Again, please don't get me wrong, I'm not saying: "it should never be used", I'm saying "given the risks, avoid it unless your game mechanics really needs it". In this sense, it is again quite game-specific.


> I'm not sure that creating two separate projects is the best way...

Well, that again, depends on your game.
In my game I use a single project as the idea is that the client can also host a match, so they share a lot of code.
I then have 2 different [export presets](http://docs.godotengine.org/en/3.0/getting_started/workflow/export/exporting_projects.html#export-menu) for the dedicated server and regular client, and switch a flag in a common [Autoload](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/singletons_autoload.html) script.
