### ISSUE TITLE
Attaching script to a node / saving a script should immediately refresh the inspector to show script exported vars

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21136]
Attaching a script to a Node or saving a script, should immediately refresh the inspector to show the script's exported variables.
If that Node is the only Node in the scene, the only way to refresh the inspector is to basically open and close another scene, which is very bad.

**Comment by DualMatrix** [comment]
I tested a big and it seems to already do this? When I add a new script with an export var it updates immediately.

**Comment by char0xff** [comment]
@DualMatrix I am in current master, and it doesn't work for me. Maybe you didn't exactly understood the problem?
My steps:
- Create a script with an exported variable and save it.
- Create a new scene with a 2D root node.
- Select the only node, the one you just created.
- Click on Script and load the existing script.
- Notice how the inspector doesn't update to show the exported variable.
- Create a new scene tab and then close it.
- Notice that now the inspector has updated itself to show the exported variable. Too late.

**Comment by char0xff** [comment]
I would actually change this to "bug" in place of "enhancement". This bug could really confuse a new user.

**Comment by akien-mga** [comment]
Seems related to #24845.

**Comment by jlahman** [comment]
I can test again later today if my PR fixed this, will update tonight

**Comment by akien-mga** [comment]
Seems to work fine in the current master branch.
