### ISSUE TITLE
Ghost editor when switching to blank workspace in GNOME 3 in fullscreen mode

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#21133]
**Godot version:**

c93888a Manjaro x86_64 GNOME 3
```bash
$ gnome-shell --version                                                    
GNOME Shell 3.28.3
```

**Issue description:**

Expected: editor window to hide
Happened: editor window stays, blocking the desktop

note: switching to non-blank workspace works as expected 

**Steps to reproduce:**
1. set the editor to Fullscreen in the next-to-last workspace
2. Switch to the blank workspace (Ctrl Alt Down)
3. The editor stays but uninteractive.

**Comment by capnm** [comment]
Works as expected on Ubuntu 18.04 LTS, GNOME Shell 3.28.2.
There may be a problem with your Linux distribution.

**Comment by Noshyaar** [comment]
Thanks for the info! I tried with another machine (Manjaro x86_64 GNOME 3.28.3, same version as my first PC) and it seems to work as expected. Not sure about the cause but it might be a local issue. I'll close this for now.
