### ISSUE TITLE
"Create convex static body/collision sibling" freezes the editor if used on sphere mesh (regression)

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#21141]
**Godot version:**
c93888a

**OS/device including version:**
Windows 10

**Issue description:**
If you use these options when MeshInstance with sphere geometry is selected

![image](https://user-images.githubusercontent.com/3036176/44297908-054c5f80-a2e2-11e8-8058-9c5f16ddf35c.png)

the editor will freeze for a long time(or maybe crash) with the following error spam in console

![image](https://user-images.githubusercontent.com/3036176/44297901-e6e66400-a2e1-11e8-9cb8-ec4bb120c5ce.png)

Update: It also have same behavior if you use it on Capsule mesh

**Comment by reduz** [comment]
@hpvb i think you did some changes in quickhull, maybe its related?

**Comment by AaronCRobinson** [comment]
As an FYI, I was experiencing this with letters which I was making into 3-D models with rounded edges. The process was to use my font, edit a nurb circle to a semi-circle, add as bezel object on text, and to create a 3-d, rounded letter model from this. I was having trouble with a bunch of the models from this process when adding the static bodies but eventually recreated my blender scene so that I could get the models in. This bug may also be related to another case where two edges/faces are coming close together (as the first letter I worked with had this feature).

**Comment by Norrox** [comment]
This still happens in 3.1 beta 3, i see @reduz will look in to this in 3.2, still i wanted to add my experience aswell.

[issue.zip](https://github.com/godotengine/godot/files/2800602/issue.zip)
![f1bc983a480cc7c87431a312bd0bc2d8](https://user-images.githubusercontent.com/13393087/51807934-79296580-228d-11e9-88eb-761a8e7ec6c4.png)

**Comment by ComicoTeam** [comment]
> See also #25388, it happens with QuadMesh too. I could reproduce it on 3.0.6 and master.

For me with customMeshes as well

**Comment by nu-fulla** [comment]
This happens to me also, every time with a sphere. Godot 3.1 Beta 4 , Windows 10 64 bit.

**Comment by nu-fulla** [comment]
Is this going to be ignored until 3.2? It crashes the entire program and happens every time when using one of the few basic shapes, this is going to happen very frequently, surely you can't just leave it.

**Comment by nu-fulla** [comment]
> This does not seem to work very well. I will give it a check in 3.2 and implement proper convex decomposition.

I don't understand what could be more important than this bug, a complete crash on one of the most frequent tasks.

**Comment by nu-fulla** [comment]
Leaving this issue as is guarantees countless crashes. I have not come across anything else like it in Godot, a common task that causes a total crash.

I submit that the "Create Convex Static Body" and "Create Convex Collision Sibling" are **removed** from the menu until it's fixed.

Users can **still** use "Create Trimesh Static Body" and "Create Trimesh Collision Sibling". No functionality is truly lost.

**Comment by nu-fulla** [comment]
Leaving this issue as is guarantees countless crashes. I have not come across anything else like it in Godot, a common task that causes a total crash.

I submit that the "Create Convex Static Body" and "Create Convex Collision Sibling" are removed from the menu until it's fixed.

Users can still use "Create Trimesh Static Body" and "Create Trimesh Collision Sibling". No functionality is truly lost.

**Comment by TC1061** [comment]
> I submit that the "Create Convex Static Body" and "Create Convex Collision Sibling" are removed from the menu until it's fixed.
> 
> Users can still use "Create Trimesh Static Body" and "Create Trimesh Collision Sibling". No functionality is truly lost.

No, trimesh collision shapes are buggy. They have no volume and they don't collide with each other.

**Comment by nu-fulla** [comment]
> 
> No, trimesh collision shapes are buggy. They have no volume and they don't collide with each other.

I didn't realize they couldn't be used as collision shapes until after I posted that.

In the interim is it possible to disallow converting shapes that cause a crash. Trigger a  little pop up that says "It is not possible to convert this shape into a convex body." Even just doing that to the sphere would cut down on crashes.

**Comment by reduz** [comment]
A proper fix would definitely be implementing a convex decompositing library like HACD:
https://github.com/kmammou/v-hacd
instead of using quickhull, as this option as it currently is, is really sub-optimal.

**Comment by reduz** [comment]
Kicking to 3.2 as no clear way of fixing this exists..

**Comment by baudren** [comment]
Is there no way to restore the functionality from 3.0 in the meantime? There was no problem generating a collision shape from a sphere or capsule there (except for warnings in the console output).

That would prevent quite a lot of frustration in using this functionality - as it is impossible to save the scene after having clicked on the button, therefore leading to losing some work.

**Comment by nu-fulla** [comment]
I don't mean to be an annoyance but this does seem to be a "critical" bug. Although I don't know the exact definition. There's not a way to revert the code for just the convex creation portion of the current code? I also think disabling convex creation on affected meshes is a much better option than allowing lock ups/crashes.

**Comment by akien-mga** [comment]
Moving back to 3.1 milestone, as this is a regression.

The feature works well in 3.0.6, so there's no reason it can't be made to work again in 3.1.

Test project: [convex_crash.zip](https://github.com/godotengine/godot/files/2899630/convex_crash.zip)
(Select MeshInstance, pick one of the "Create convex" options.

**Comment by akien-mga** [comment]
I tested 3.1 alpha 1 and it reproduces the bug too.
If someone is willing to bisect what caused the regression between `3.0-stable` and 3.1 alpha 1 (don't have the exact commit reference anymore, but should be around 3304e6ce or a day or two earlier, so this one can be used as `git bisect bad`).

**Comment by Chaosus** [comment]
@akien-mga I will try to find it..

**Comment by baudren** [comment]
@Chaosus sorry, I just saw your comment right now, I searched for it during the day. If I bisected right, the first bad commit is e179bf0726868fbf2c6216a6c6a715c4a2f99419. Hope this helps!

```
e179bf0726868fbf2c6216a6c6a715c4a2f99419 is the first bad commit
commit e179bf0726868fbf2c6216a6c6a715c4a2f99419
Author: Juan Linietsky <reduzio@gmail.com>
Date:   Tue Jul 3 10:55:50 2018 -0300

    Ensure, if a texture meant for a normal map is imported and size limit exists, that it's renormalized after resize.

:040000 040000 1751c3142ae7fb86da5e18dbf790443cffd1a292 44578e251f21d54e217c0580761e9c21380383e0 M	core
:040000 040000 f9d307110e2f06d73f76e18b86e1050e0cfe1bcf cd18305297ba36ff22e655afd7bd50be216b5a22 M	editor
:040000 040000 66128b79e7494716723fc12986bdf49e0395dfc5 fbb843714fe87f758faf8c9eb5ff149947e262f9 M	scene
:040000 040000 588e4422da2a86d6f06849bd1b92460f592a8e41 3d73b700a069c96df9da0c024edb945ff5d3f5ac M	servers
```

**Comment by hpvb** [comment]
The crash is caused because of the default settings on the mesh being changed. Particularly ARRAY_COMPRESS_VERTEX appears to be necessary for quickhull to function. I'll try to fix quickhull to be able to work with different mesh formats.

**Comment by ardicoetzee** [comment]
What ever came of this? What is one to use while this feature is not there? It's on version 3.4 now so surely people are using another workaround by now?

**Comment by Calinou** [comment]
Use a CollisionShape node with a SphereShape instead of generating a convex collision shape from a SphereMesh primitive.
