### ISSUE TITLE
Cant add second anchor point to first cotrol point in Path2D

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#2114]
There is no option to add second anchor point in the first point of Path2D - while it is possible to do it on Path3D. Also editing both is quite different and incoherent to me - including shortcuts for doing same things.

**Comment by djrm** [comment]
Path does not allow curves, why would somebody want 2 pivots in the first or last point, now the shortcuts and behaviors of both editors is coherent

**Comment by akien-mga** [comment]
Closing as old then.
