### ISSUE TITLE
Inspector:  Save button missing from top level

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#21158]
**Godot version:**

68676c7

**Issue description:**
![image](https://user-images.githubusercontent.com/1023003/44301708-5b6cd300-a2e1-11e8-85a9-af961f3f3f6a.png)

The save button no longer appears in the inspector.  Tested with font resource and shader resource.
Workaround:  Save is located in Object Properties, but is now a lot less convenient to reach.

**Comment by Noshyaar** [comment]
Related to https://github.com/godotengine/godot/issues/19749

**Comment by akien-mga** [comment]
Is a Save button in this view still needed after #23802?

**Comment by nobuyukinyuu** [comment]
@aiken-mgav does this save from one level higher up from the resource in the inspector?  The particular use case I typically hit the save button for was when I wasn't confident Godot was saving changes to a Resource when I was currently editing it (particularly ones with custom bottom windows but not exclusively), so this might not address it since you would still have to go one level out to perform a save if it didn't have a fold out menu.

Not sure if *everything* has a fold out now by default, so ignore if the "subresource view" feature of the inspector has changed since 3.0.

**Comment by Zylann** [comment]
@akien-mga it does not adress it because it is only available if the resource is contained within another object. The button we ask here is for the current resource.

**Comment by Zylann** [comment]
I think I found the commit where it disappeared: https://github.com/godotengine/godot/commit/9a365a1216b8fe9f394d6efdd9550eab4e899eca

It was about moving the inspector to its own file, but `resource_save_button` disappeared in the process ¯\\_(ツ)_/¯
