### ISSUE TITLE
[Regression] Scene thumbnails show up as black squares

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#21157]
**Godot version:**
`master` / c93888ae

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
After a recent update of Godot (approx. 1-2 week before c93888ae), all file icons began to show up as black squares as shown below:
![image](https://user-images.githubusercontent.com/2367032/44301629-59dcf280-a355-11e8-85a2-1bb4fd5bab7e.png)

It seems that existing icons are not affected by the problem, but all new or updated files show the symptom.

**Comment by Noshyaar** [comment]
Thumbnails stop generating since 0e29f79

**Comment by Noshyaar** [comment]
cc: @hpvb
