### ISSUE TITLE
Do we need a Godot Enhancement Proposal 

### ISSUE THREAD

**Issue by paulhocker** [godotengine/godot#21164]
As I look through the Issues and Requests for Godot I have noticed a very large number of closures and moves (I do not have exact numbers, its more of a gut feel based on observations) because things have been discussed in the past with no history, or because it is something on the road map and was not searched for properly *myself included* or is actively being worked on.

Perhaps, this has already been discuss (I did not find an issue or request) that Godot start an Enhancement Proposal site similar to Pythons [PEP](https://www.python.org/dev/peps/).

I think something like this would be helpful for people, and it would certainly assist the developers in having to re-hash old discussions because the entire history of the discussion for a feature would already have been saved.

Again, my apologies if this has been discussed already. If it has not, I would be willing to start something to get the ball rolling.

I am simply amazed at the progress this engine makes, and how fantastic the community is. My intentions are purely selfish here because I want @reduz and crew to be working on new things, and not having to explain themselves over and over again on why things are the way they are.

Please leave comments, feedback or high fives.

Paul

**Comment by Xrayez** [comment]
Found this repo by accident that I wasn't aware of:
[Godot Roadmap](https://github.com/godotengine/godot-roadmap)
[Godot Roadmap wishlist](https://github.com/godotengine/godot-roadmap/blob/master/WISHLIST.md)

Not as user-friendly for people who don't have knowledge how to make a pull request to propose a feature, so a dedicated site would be a better choice?

**Comment by Xrayez** [comment]
@paulhocker godot proposals is up and running now! 😛

https://github.com/godotengine/godot-proposals

**Comment by akien-mga** [comment]
Indeed. This is still WIP but it aims at addressing this (and a lot of unwritten feedback and our own growing feeling that the main godotengine/godot issue repo is too difficult to handle when flooded with often low-quality proposals).
