### ISSUE TITLE
Cannot bind function accepting a `TreeItem*`

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#21160]
Godot ff8e6f920cd99954c3394412713950c1195199f2
Windows 10 64 bits MSVC 2017

In the engine, I'm trying to connect a C++ function to the signal `button_pressed` of `Tree` node. This signal makes you receive a `TreeItem` object.

Here is the signature of my function:
```cpp
	void _on_button_pressed(TreeItem *item, int column, int id);
```
Then I bind it so I can use it on the connection:
```cpp
	ClassDB::bind_method("_on_button_pressed", &FindInFilesPanel::_on_button_pressed);
```
But it results in a compilation error:
```
C:\Projects\Godot\Engine\godot_fork\core\method_bind.h:68: error: C2440: 'return': cannot convert from 'const Variant' to 'TreeItem *'
```

Then I found some related oddities:
- In the documentation, the signal signature is `button_pressed( Object item, int column, int id )`, but the item is always a `TreeItem`, so I think there is something to be improved here.
- As a result, in C++ code we have to accept an `Object` and cast it, as seen in `scene_tree_editor.cpp`
- Other types such as `Control` work fine in `scene_tree_editor.cpp`, so `TreeItem` should have worked too (they are both `Object` types accessible from script API), *although `Control` has been placed in `Variant` for the cast to work...*
- I tried using `D_METHOD` but that didn't fix it

Is this a known issue and do we plan to improve it?

**Comment by Noshyaar** [comment]
I was wondering the same in #9764. I can't think of a reason why it should be Object instead of TreeItem.
