### ISSUE TITLE
Debugger's Video Memory tab shows empty resource paths

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#21163]
**Godot version: 3.0.6**

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
The resource path column on the Video memory tab is empty.
![godot3videomemory](https://user-images.githubusercontent.com/10215987/44303462-f7193600-a317-11e8-90b6-95808e31cceb.png)

On Godot 2 looks like this:
![godot2videomemory](https://user-images.githubusercontent.com/10215987/44303471-1c0da900-a318-11e8-8a95-39043482cefd.png)

**Steps to reproduce:**
Run any project, check the video memory tab on the debugger.

Some resources like tscn sometimes appear on the list when only image files should be.

**Comment by ni-code** [comment]
Just to confirm this issues still happens on current master (#22357) .
solus linux, nvidia gpu.

**Comment by DualMatrix** [comment]
Went digging and even in the texture_debug_usage() function in RasterizerStorageGLES3 and RasterizerStorageGLES2 the path of the texture is empty.
