### ISSUE TITLE
.gdignore also used by Exporter

### ISSUE THREAD

**Issue by gmarais** [godotengine/godot#21178]
**Godot version: 3.1**

**Issue description:**
> .gdignore takes effect after closing/reopening the editor not before. (maybe not a bug)

> it leaves zombie files if added after the editor imported the ressources

> .gdignore also makes exporter ignore the folder which is not handy!

Here is why it matters (to me at least):
It would be better to have a different filename for that functionality because for example, in my case, I wanted the importer **not** to import my .png files in a given folder so I could export them myself and have them in my res:// as png files.
These images are for my script to use as Images not textures and will never be drawn as such. Also it is not possible to import images as "Image" rather than as "Texture" or "Bitmap" which could have been an other viable solution.

**Steps to reproduce:**
add .gdignore in a folder search for that folder or try to export files contained in the folder.

**Possible fixes:**

- Make the exporter not ignore necessarily the same folders as importer by separating the two behaviors if both are wanted. Having some other more specialized names like: .gdnoexport .gdnoimport

- Allow users to import images as Image and not Texture if they want to use that resource as an image in their code but not as a texture to draw on the screen.

- when detecting that a link to one or more sources of imported files are broken ask user if they want to keep the imported else remove the imported files.

- Make the editor detect when a ignore file is placed/moved/removed and make the expected changes.

Ps: the new import workflow might be good for very simple/small projects but so far it has only made things more painfull to me. This is so far the only feature I cant get used to.

Thank you for your attention :+1:

**Comment by Zylann** [comment]
If you want this, why not configure the importer to treat them as `Image` instead of texture? That feature was added recently to master.

**Comment by gmarais** [comment]
Aw so this is inc well good then I didnt know that I looked at master didnt see the push Godot devs rock :+1:
I ll wait for stable release though as for now it works in testing.
Other suggestions do still apply though.

**Comment by clayjohn** [comment]
Is this fixed in 3.1? It sounds like it is. If there are additional problems do you mind splitting them into new issues?

**Comment by Calinou** [comment]
It seems this has been solved in 3.1, so I'll close this.
