### ISSUE TITLE
Selecting Incorrect Nodes in 2D 

### ISSUE THREAD

**Issue by orosmatthew** [godotengine/godot#21172]
**Godot version:**

3.0.6 Stable (Steam)

**OS/device including version:**

Windows 10

**Issue description:**

For some reason, I cannot select the right node
![selecting](https://user-images.githubusercontent.com/32916949/44304636-c04f1a00-a32f-11e8-91fe-d56cbc6ed71e.gif)

**Steps to reproduce:**
Have a bunch of nodes and copy and paste them and try and select the right one. Snapping is turned on and the nodes are instanced scenes. But honestly, I notice this in many, many situations where Godot constantly selects a completely different node/scene than what I am pointing at so the "steps to reproduce" are to pretty much try and accurately select something and move it around in almost any project.

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
Do you have scaling (dpi) other than 100% in your Windows settings?

What is your GPU/drivers?

**Comment by orosmatthew** [comment]
I have it on 100% scaling and my laptop has Intel 630 Graphics along with an Nvidia 1060 Max-Q

**Comment by Zireael07** [comment]
Which card are you using for Godot?

**Comment by orosmatthew** [comment]
The Nvidia 1060 Max-Q

**Comment by eon-s** [comment]
Is not affecting Controls in the editor?, like, project manager buttons?

**Comment by orosmatthew** [comment]
It does not affect the UI buttons in the editor but the actual selecting of nodes within the 2d viewport

**Comment by groud** [comment]
Does this still happens on 3.1 alpha?

**Comment by orosmatthew** [comment]
I figured out this is occurring only when the collision shapes are visible and doesn't when they aren't. I haven't tested in 3.1 alpha yet. I will download and see later.

**Comment by akien-mga** [comment]
No update since a year and it's not clear to me how to reproduce the issue. I'll close for now, but we can reopen if anyone can confirm the issue in 3.2 and provide clear steps to reproduce it.
