### ISSUE TITLE
Please don't stop assignning values to variables decleared with const

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#21177]
**Godot version:**

Godot 3.1.dev compiled with 8bc9986

**OS/device including version:**

Arch Linux x64

**Issue description:**

In GDScript I always define ***static*** variables with the keyword `const` . 
The code below works fine from godot 2 to godot 3.0.

```gdscript
class MyClass:
	const static_variable = 100
	
	static func get_static_value():
		return static_variable
	
	static func set_static_value(p_value):
		static_variable = p_value

func _ready():
	MyClass.set_static_value(100)
	print(MyClass.get_static_value())
```

In the new version of godot compiled from master branch. This code parse failed with this message
```
Parser Error: Cannot assign a new value to a constant.
```

Please consider remove this syntax checking or add a new way to define ***static*** variables like this

```gdscript
static var static_value = 1
```

**Comment by Geequlim** [comment]
CC @vnen

**Comment by Noshyaar** [comment]
You've been using bug as feature. I don't think we're going to support that.

Reassigning const bug: #6221 #15200 #20179
Static var: https://github.com/godotengine/godot/issues/6840

**Comment by Zylann** [comment]
Note: there is a simpler legit way to do the same thing you just did:

Create a normal script inheriting `Resource`, put non-const vars inside, create a `Resource` in the inspector, put the script on it, and save as file. Now you can preload it and use it as pseudo-singleton with shared vars as long as the resource is referenced somewhere at runtime.
But honestly, an autoload is closer to globals if that's what you want.

**Comment by vnen** [comment]
If this is really wanted we can add static variables (assuming it could work properly, see discussion in #6840). But allowing constants to be reassigned is a big problem and maybe the source of many game bugs when done by mistake, so I'm 100% against it.

**Comment by akien-mga** [comment]
Indeed, this was a bug and we won't reintroduce it. But discussion can continue in #6840 regarding adding proper static variables.
