### ISSUE TITLE
Make path/polygon editing more user friendly

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#2118]
While path and polygon editing is crucial in some cases, it is very important to user, to see it behaving as he want it to. While Adobe Illustrator seems to be a technology standard in that topic nowadays, I would love to see godot working more like it when it comes to vector graphics.

**Comment by akien-mga** [comment]
Could you be more specific? User friendliness is without end, we could improve every bit of Godot towards more user friendliness.

It would be easier for contributors to work on this if you had some concrete enhancement proposals for path and polygon editing.

**Comment by reduz** [comment]
i have no idea what making it more user friendly means, but i fixed a few bugs in path editor recently..

**Comment by vnen** [comment]
I think this should be archive, unless @Krzycho666 tell us something more specific about the topic. "Like Adobe Illustrator" doesn't really help.

**Comment by djrm** [comment]
Abandoned by the author
