### ISSUE TITLE
GDScript: Add a syntactic shortcut to typed nodes

### ISSUE THREAD

**Issue by skgalaxy** [godotengine/godot#21189]
**Godot version:**

3.1 in dev

**Issue description:**

Good day. Since I'm now testing the development version to start with some projects, I should comment on something to improve the GDScript experience a bit.
Optional typing and safe lines provide **security** to the code you want **without sacrificing duck typing**. But when I started writing regularly on typed GDScript and referencing nodes I realized that the syntax for safe lines **is very long**.
```
#no safe line
$AnimationPlayer.play("eating") #it is not safe because "node" does not have a defined "play" function
#safe line
($AnimationPlayer as AnimationPlayer).play("eating")
#in this last line you must put parentheses
```
And that's why I propose a way to **shorten it**. The form does not matter, it only matters that it is short enough and that you do not have to put parentheses. My proposal is to put a double dollar symbol before the node name. That pretty reminds of the "get_node" symbol and it's pretty short. It would be implemented like this:
```
#safe line
$$AnimationPlayer.play("painting") #it is safe since "$$AnimationPlayer" is an instance of AnimationPlayer and it does have a "play" function
#in summary, $$AnimationPlayer==$AnimationPlayer as AnimationPlayer
#and you do not need to put parentheses!
```
It is a small feature, but it **simplifies** written code a lot. So, whether we use typed GDScript or not, we can **forget to assign nodes to variables** to use later. Precisely for that the symbol of dollar was invented:
```
#Before Godot 3.0
var left_ball=get_node ("MyPong/Balls/Left")
var my_pos=left_ball.get_pos()
#Godot 3.0
var my_pos=$MyPong/Balls/Left.position
#the dollar symbol simplified things a lot and many of you know
#Godot 3.1
var my_pos=$MyPong/Balls/Left.position #no safe
var my_pos=($MyPong/Balls/Left as Node2D).position #safe
#or, if you have a much more complex code you have to go back to the old habit of assigning the node to a variable
var left_ball=$MyPong/Balls/Left as Node2D #safe
var my pos=left_ball.position #safe
#Godot 3.1 with $$
var my_pos=$MyPong/Balls/Left.position #no safe
var my_pos=$$MyPong/Balls/Left.position #safe
#Now, the double dollar symbol simplifies the GDScript code, so we do not have to assign nodes to variables.
```
And another great improvement is in the autocomplete, since now you will be able to know the type of node members without having to write a lot.
```
$Particles.visibility_aabb.size=Vector3 (125, 23, 558) 
#no safe, also, does the autocompleter have a way to know the type of 
"visibility_aabb" if it does not even know if the node has that member?
$$Particles.visibility_aabb.size=Vector3 (125, 23, 558) 
#safe. and now we know that "visibility_aabb" is of type AABB, so we can autocomplete the "size" member
```
I await your comments. Thank you.

**Comment by skgalaxy** [comment]
Oh, before I forget and in case someone doubts, as to the type to which the nodes would be casted (since a Sprite3D is also a Spatial, a VisualInstance and a SpriteBase3D) I propose that the type to which they are casted is determined by the most derived type that can be detected in the scene and that the syntax only serves in nodes and where it can be put "$", it is say, it would only autocomplete in the scope of the scene where the script is. In other words, or rather, in code:
```
#if "MyGUI" is a Control
$$MyGUI==$MyGUI as Control
#if "Coleur" is a ColorPicker, will not be casted to CanvasItem, Control, Container or BoxContainer
#Will be casted to ColorPicker, the most derivative type
$$Coleur==$Coleur as ColorPicker
#If "Player" is a KinematicBody2D
$$Player==$Player as KinematicBody2D
```
I await your comments.

**Comment by Zylann** [comment]
```gdscript
#safe line
$$AnimationPlayer.play("painting") #it is safe since "$$AnimationPlayer" is an instance of AnimationPlayer and it does have a "play" function
#in summary, $$AnimationPlayer==$AnimationPlayer as AnimationPlayer
#and you do not need to put parentheses!
```
Sorry, how is this working? The best thing the script parser can do is to to test if the name of your node is the same as its class (and even that is not robust). Keep in mind a script can be instanced in multiple places, so it's not trivial to look at the scene to check things when it gets parsed, because it's possible that there is no scene in the first place (when you do `load(script.gd)` for example).
(on a side note, `get_node` is orders of magnitude slower than keeping it in a var, just so you know before you abuse the shortcut ;) )

**Comment by skgalaxy** [comment]
I have done some experiments to prove something I wanted to know before answering.
Indeed, a script can be instantiated several times and even created from the GDScript editor without even assigning it to a node. On the other hand and on the way how Godot would guess the type, when I write "$", the name of the node and place a point, the functions available for the node appear in its most derivative type possible.
```
#I start writing letter by letter
$KinematicBody2D.
#When I put the point, the list of functions is displayed
#which is elaborated according to the most derivative type possible.
#That's why it contains functions like move_and_collide or move_and_slide
```
Then it is possible, in the context of the scene tree, to know the most derived type of the node. That in the context of editing. That would serve more than anything for safe lines, warnings, errors, etc.
At compile time of the script, something like:
```
var scenes_prop= search_for_script's_owner_scenes()
#possible, since Godot can show the list of owners
for scene in scenes_prop:
    var found_node=scene.search_node_with_the_name_or_path_in_the_scene()
    #exist a find function
    var type=found_node.get_type_from_that_node()
turn_($$node) into ($node as type)
```
And what happens if the type can not be detected, the node does not exist or the scene does not exist?

I can think of 3 possibilities:
1. Show a fatal error.
2. Do not cast. Make that expression equivalent to $.
3. Automatic casting to Node, for what it would mean.
But that already depends on all of you. If there is something else I should know or what I am wrong about, please tell me. Thanks.

**Comment by vnen** [comment]
> Then it is possible, in the context of the scene tree, to know the most derived type of the node.

Yes, but that's for completion only, as a convenience. The compiled script cannot assume the scene structure because the same script could be used in a another scene where it's possible that such node wouldn't exist or would have a different type. So you can't rely on that information to perform transformations when parsing/compiling the script.

It _could_ be used for the safe lines indicator, just like it is for completion: an editor convenience. Just note that you would have different results whether the related scene is active in the editor or not, which can become quite confusing. For this reason it **can't** be used for auto-casting because you'd have to always open the scene before compiling, and failing to do so could make different results when running, which is not acceptable.

**Comment by skgalaxy** [comment]
Analyzing a little better the situation and according to @vnen  and @Zylann , the best would be an improvement in the autocomplete. Start typing the name of the node, and the option already typed appears. But that is too trivial and, in my opinion, unnecessary.
Closing.

**Comment by OvermindDL1** [comment]
Honestly I'd prefer if autocomplete added the whole casting as well based on what it knows in the scene, so typing `$Blah/Blo` then autocompleting would autocomplete to `($Blah.Blo as Sprite2D)` or whatever it currently infers the type of that node to be.  As this is purely via editor completion then it would be the best help for it.

**Comment by OvermindDL1** [comment]
At the very least it could be an option to do that or not, default to casting the type properly of course.  It would save me time for sure.

**Comment by skgalaxy** [comment]
#21340
