### ISSUE TITLE
warning: delta is never used in function process

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#21186]
**Godot version:**
master (https://github.com/godotengine/godot/commit/5d09877da8003740928502aead0b46505495721f)

related issue: #21180

**OS/device including version:**
Linux

**Issue description:**
Do I have to ignore this warning or can I replace delta with another String that doesn't trigger the warning?

**Steps to reproduce:**

```Swift
func _process(delta):
   pass
```

**Comment by rcorre** [comment]
`pylint` will not complain about unused variables starting with `_`. Should godot do the same?

```
[rcorre@desktop-arch tmp]$ echo -e 'def forp(thing):\n    return 1' > test.py
[rcorre@desktop-arch tmp]$ pylint test.py -d missing-docstring
************* Module test
test.py:1:9: W0613: Unused argument 'thing' (unused-argument)

--------------------------------------------------------------------
Your code has been rated at 5.00/10 (previous run: -5.00/10, +10.00)

[rcorre@desktop-arch tmp]$ echo -e 'def forp(_thing):\n    return 1' > test.py
[rcorre@desktop-arch tmp]$ pylint test.py -d missing-docstring

-------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 5.00/10, +5.00)
```

It also respects `dummy` and `_`, though I prefer `_delta` as it is obvious what the variable is if it is needed in the future.

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/pull/19993#issuecomment-412260079

**Comment by vnen** [comment]
I'll add the underscore prefix convention to ignore the unused variable.

**Comment by aaronfranke** [comment]
@vnen Also do this for functions with names starting with underscores, so that default Godot functions don't have to be changed (and `delta` looks cleaner than `_delta` IMO).

**Comment by vnen** [comment]
@aaronfranke No because then there's no way to opt-in for this type warning. You can change argument names at will, but the names of those virtual functions are forced. Also `_delta` might not look clean, but if you're actually using the argument then you don't need the underscore.

**Comment by aaronfranke** [comment]
Change your code to this:

    func _process(_delta):

**Comment by Coder6969696** [comment]
now my godot just crashes the game window and doesnt even give any errors what should i do

**Comment by LinuxUserGD** [comment]
@Coder6969696
Which Godot version?
Does it also crash if just `delta` is used?
If it's latest master, it could crash because of using self directly. Better open a new issue with add a minimal reproduction project.
