### ISSUE TITLE
Do not write GDScript warnings to Output panel / stdout

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#21180]
**Godot version:**
Current master (238a78f1)

**OS/device including version:**
All.

**Issue description:**
Current GDScript warnings are nice, but they are displayed in too many locations redundantly:
- Warnings panel in script editor (when you click on "Warnings:  \<number\>")
- Debugger "Errors" panel (btw I see warnings there when running the game which are not found by the static analysis in the script editor)
- Output panel when running the game
- Console stdout when running the game

I think at least the last two are unnecessary, debugger + warnings panel are enough. Even those might be redundant UX-wise, but since they don't seem to catch the same warnings for now it's likely fine to have both.

**Steps to reproduce:**
Run a project with script warnings.

**Comment by vnen** [comment]
It seems I can send only to the debugger panel, but it looks like an engine warning

![screenshot from 2018-08-21 15-05-22](https://user-images.githubusercontent.com/5599796/44420204-b7d72900-a553-11e8-9d07-5e2e57199f96.png)
