### ISSUE TITLE
Decals implementation

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#21185]
I'm opening this issue to talk about decals implementation.

The decals are a really useful feature and you can see it in action here: https://www.youtube.com/watch?v=rUOKIrfpHGw, you can use it to create bullet holes, footprint, blood / dirty in the walls, etc..

If someone is looking on something new to implement, this could be an idea.
In ue4 this is how it's looks like in editor: https://youtu.be/ANCm_EMfjP4?t=45s

**Comment by CptPotato** [comment]
I didn't use godot for much 3d yet but I assumed that decals were implemented. If this is not the case I think this should be done as they're very useful for many things.

They might not integrate as seamlessly as in UE4 (since UE4 uses deferred rendering, godot doesn't) but should still work very well.

**Comment by Zireael07** [comment]
No, decals are not yet in core @CptPotato. I believe someone made a fake decal addon that basically uses quads and some shaders?

**Comment by CptPotato** [comment]
^ this is an interesting paper. Though it's more about vector-like filtering not the decals themselves. iirc, Godot supports distance field fonts which is the same technique as this article describes.

**Comment by pgruenbacher** [comment]
https://github.com/Mr-Slurpy/Screen-Space-Decals
Screen-space-decals implemented here ^

Dumping some of my blog notes.
http://blog.wolfire.com/2009/06/how-to-project-decals/
http://blog.wolfire.com/2009/05/decals-editor-part-one/
https://pompidev.net/2014/12/02/projecting-a-dynamic-decal-on-a-3d-mesh/
https://mtnphil.wordpress.com/2014/05/24/decals-deferred-rendering/
https://bartwronski.com/2015/03/12/fixing-screen-space-deferred-decals/

**Comment by pgruenbacher** [comment]
that being said the scree-space decals has a lot of issues that I haven't been able to overcome like only rendering it on specific meshes, side stretching, etc.

**Comment by anderlli0053** [comment]
Anything new on decals? When they will be added? Why so much waiting for it, as it is vital part of game creating

**Comment by Calinou** [comment]
@anderlli0053 While they are on the [roadmap](https://github.com/godotengine/godot-roadmap), rendering features will likely only be added in Godot 4.0, as work in other areas is currently being done for Godot 3.2.

**Comment by anderlli0053** [comment]
Aha Ok, thank you for information!

**Comment by Calinou** [comment]
This was implemented in #37861, closing.
