### ISSUE TITLE
Audio volume decreases when playing other audio node

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#21196]
**Godot version:**
v3.1.dev.calinou.8bc9986

**OS/device including version:**
windows 10 x64

**Issue description:**
Audio volume of "audio stream" node decreases when play other "audio stream"
It is described in the attachment project.

https://drive.google.com/open?id=1kLt_PF4vd7Xvf-UfUsJHJ21Z1G3EpiOm

**Comment by Calinou** [comment]
@sami8github Can you still reproduce this in Godot 3.2.1 or [3.2.2beta3](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-3)? Also, make sure you don't have a system-wide equalizer that would perform auto-ducking on all applications.

**Comment by akien-mga** [comment]
No answer, and I can't reproduce it with the attached project, so closing.
