### ISSUE TITLE
Support for TextureRect scale below 1

### ISSUE THREAD

**Issue by IceflowRE** [godotengine/godot#21201]
Currently `TextureRect`s scale below `1` is not supported. It can be set but the margin is not correct calculated then. (It still uses the size of scale 1)

**Comment by KoBeWi** [comment]
Isn't it the same as #19068?

**Comment by IceflowRE** [comment]
In the mentioned issue it's not explicit note for size lower 1, but it addresses the same problem and could be solved with the other.

**Comment by KoBeWi** [comment]
Closing as duplicate of #19068
