### ISSUE TITLE
PhysicsDirectSpaceState.cast_motion() has different behaviour between Bullet and GodotPhysics

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#21212]
**Godot version:**
3.1-dev faa49c1

**OS/device including version:**
Windows 10 x64

**Issue description:**
`PhysicsDirectSpaceState.cast_motion()` is used to check how far a shape can travel to a point both with and without triggering a collision. It returns an array containing two values.

With GodotPhysics:
* The first value is how far it can move with no collision, while the second is how far it needs to move for a collision to be detected. The values are usually very slightly different.
* If no collision is detected, both values will be 1.
* If no movement can occur (a collision occurs without any movement), the returned array will be empty.

However, with Bullet:
* The first and second values are always identical, both representing how far it needs to move for a collision to be detected.
* If no collision is detected, the returned array will be empty.
* If no movement can occur, both values will be 0.

The documentation only reflects the GodotPhysics behaviour, and I haven't seen any dscussion regarding this, so the discrepancy seems like a bug...

**Minimal reproduction project:**
[cast motion test.zip](https://github.com/godotengine/godot/files/2301492/cast.motion.test.zip)
Change between "Bullet" and "GodotPhysics" in the Project Settings (under `physics` > `3d`) to observe the differences in behaviour. Move around with the arrow keys and press Space to perform a new query. The results will be displayed in a Label.

@AndreaCatania

**Comment by homer666** [comment]
The first point discrepancy has been solved, but the other two still apply. Is this considered to be expected behaviour?

**Comment by AndreaCatania** [comment]
Only the second one (that I've missed) should be fixed

**Comment by homer666** [comment]
Thanks for your hard work odino!

So the behaviour of `PhysicsDirectSpaceState.cast_motion` using Bullet is as follows:
- The first value is how far it can move with no collision, while the second is how far it needs to move for a collision to be detected.
- If no collision is detected, both values will be 1.
- If no movement can occur, both values will be 0.

The last point is still different between Bullet and GodotPhysics, but given that the latter is deprecated, I will assume the current Bullet behaviour is desired and edit the docs to reflect this.

I think `Physics2DDirectSpaceState.cast_motion` should be modified to match Bullet eventually.

**Comment by AndreaCatania** [comment]
In this way you don't need to check array size

**Comment by homer666** [comment]
@AndreaCatania that's fine, I just wanted to clarify it for others until the docs are updated.

**Comment by aaronfranke** [comment]
Will GodotPhysics be changed to make it return `[0, 0]`?
