### ISSUE TITLE
Copy params shouldn't copy the script

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#21214]
**Godot version:** 3.1 custom

**Issue description:**
During a refactor, it is likely that some classes are broken down into multiple child classes. In that case, you might need to keep the parameters of the parent script for the child script. If you try to do that with copy params, when you paste the parameters it will also paste the script, resulting in your node having the parent script instead of the child one.

**Proposal**
Allow to choose between copying everything or everything but the script
-- OR --
Allow to copy only one of the sections of the hierarchy of the parameters

**Comment by PLyczkowski** [comment]
I've also hit upon this and agree it's non-intuitive that the script is copied when you use copy params.
