### ISSUE TITLE
Deep Parallax Depth mapping does not work correctly on Godot's built-in meshes.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#21221]
**Godot version:**
v3.1.dev.custom_build.30bfe5c

**OS/device including version:**
Linux Mint 19 - 64bit
Nvidia GeForce GTX 1060 on driver version: 396.51

**Issue description:**
Parallax depth mapping does not work as expected on Godot's Built-in meshes (see example project).
This is confusing and a potential turn-off to new users testing out the engine's rendering capabilities.
It looks as it should on a mesh imported from Blender.
I tested with exporting an OBJ, DAE with the better collada exporter, and ESCN with the new blender godot exporter.

OBJ does not work, same results as the built-in meshes.
DAE works fine, but you need to make sure to check the "Tangent Arrays" export option, otherwise it won't.
The Blender exporter works fine out of the box.

**Steps to reproduce:**
1. Add a MeshInstance node to your scene.
2. Assign any of the built-in meshes to the MeshInstance node. (The quad is the only one that looks correct, the rest of them look flat and strangely warped, as if the normals aren't facing the right direction.)
3. Assign a SpatialMaterial to the MeshInstance node.
4. Assign textures and enable Deep Parallax, observe results.(Disabling Deep Parallax looks even worse.)

**Minimal reproduction project:**
[depth_issue.zip](https://github.com/godotengine/godot/files/2302301/depth_issue.zip)
The red sphere is using Godot's built-in mesh.
The green sphere is imported from Blender(DAE).

**Comment by reduz** [comment]
yeah there is clearly a problem with tangent space

**Comment by Windfisch** [comment]
could #16096 be the fix for this?

**Comment by akien-mga** [comment]
Fixed by #23760.
