### ISSUE TITLE
Loading GDScripts Not Working

### ISSUE THREAD

**Issue by primesoftware** [godotengine/godot#2122]
I have a custom class as follows:

[code]
#MyClass.gd
class MyClass:

vars ...

func _init(arg1, arg2, arg3):
       print(arg1)
func otherFunc():
       #do stuff
[/code]

MyClass.gd gets loaded by a script attached to PopupWindow:
[code]
extends PopupDialog

vars ...
var MyClass = preload("res://Scripts/MyClass.gd")

func _ready():
       var MyClassInst = MyClass.new("hi", "I dont", "work")
       MyClassInst.otherFunc() #Debugger says it doesn't exist
[/code]

The result is Godot crashes and never even loads the popup window. There is no error in the Godot debug console. If I don't create a new MyClass script everything works fine. Is this a bug in loading classes?

**Comment by jackmakesthings** [comment]
Try writing your classfile without the "class MyClass:" line (and indentation level) and it should work as expected - this took me a few missteps to get my head around, but when you create a script file, that file is already treated as a class, more or less. Declaring "class MyClass" inside it creates a subclass. So to access anything under that, you'd need to do MyClass.MyClass.otherFunc() - the first MyClass refers to the whole file, then the second refers to the subclass. (If that doesn't solve it, let me know.) 
     
    ###########
    # file res://Scripts/myclass.gd

    func class_level_function():
        (do something)
 
    class mySubClass:
        func subclass_level_function():
            (do something)
 
--
    ##############
    # meanwhile, in another file...

    var myClass = preload("res://Scripts/myclass.gd")
    var myClassInst = myClass.new()

    # will work
     myClassInst.class_level_function()
     myClassInst.mySubClass.subclass_level_function()

    # won't work (as far as I know)
    myClassInst.subclass_level_function()

**Comment by eska014** [comment]
Closing as user error
