### ISSUE TITLE
LightOccluder2D not see when polygon occluder is set and Inspector don't update polygon Occluder coordinates

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21225]
**Godot version:**
3.1 calinou faa49c1

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
1. When I create LightOccluder2D and I create in it Occluder and set polygon coordinates, Scene panel still show warning until I move LightOccluder(Occluder is drawn).

2. When I change Occluder coordinates through 2D Viewport, this coordinates don't change in inspector

**Steps to reproduce:**
1.
![jfile](https://user-images.githubusercontent.com/41945903/88825556-02de2a00-d1c8-11ea-982b-e80c6df64ddf.gif)

2. 
![jfile](https://user-images.githubusercontent.com/41945903/88825764-3e78f400-d1c8-11ea-8d5d-370911fa5953.gif)

**Comment by mitchcurtis** [comment]
By warning do you mean this one?

> The occluder polygon for this occluder is empty. Please draw a polygon!

I get that warning after creating a polygon for the occluder. It doesn't go away until I close the scene file and reopen it.

**Comment by Calinou** [comment]
@mitchcurtis See also https://github.com/godotengine/godot/issues/29619. The issue here is that LightOccluder doesn't report a change when its list of points changes. Do other polygon-based nodes such as Polygon2D suffer from this?

**Comment by mitchcurtis** [comment]
> @mitchcurtis See also #29619.
> 
> The issue here is that LightOccluder doesn't report a change when its list of points changes. Do other polygon-based nodes such as Polygon2D suffer from this?

I'm not sure, I've only tried with LightOccluder2D.

**Comment by KanoAlgiz** [comment]
Still reproducing as for v4.3 - after creating a polygon warning disappears only after scene (or project) reopen.

**Comment by jazibobs** [comment]
Reproducing as of version v4.4.1 - the warning disappears after closing/reopening the scene.
