### ISSUE TITLE
Splashscreen does not scale to fullscreen on Linux

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#2123]
On Linux, the splash screen always shows in size of the viewport, even when the game is started in fullscreen. The rest of the screen is black or filled with GPU artifacts.

On windows it works, is scaled to fullscreen.

**Comment by akien-mga** [comment]
Confirmed in the current master branch.

**Comment by reduz** [comment]
Sorry guys, I can't figure this out. X11 is too much of a mess

**Comment by Sslaxx** [comment]
This bug was filed over a year ago, has anything changed?

**Comment by neikeq** [comment]
I did build from source two weeks ago and it was still there.

**Comment by reduz** [comment]
I have no idea how to fix it
