### ISSUE TITLE
ItemList fails with complex items

### ISSUE THREAD

**Issue by tko** [godotengine/godot#21235]
**Godot version:**
3.0.6

**OS/device including version:**
macOS High Sierra 10.13.6 (probably OS independent)

**Issue description:**
ItemList with complex / custom items as children fail to display the items as a list. Instead everything is overlapping. The same item in a different container like VBoxContainer doesn't have the same problems, but misses all the features (hover, selection, scroll to focus, right click, ...)

**Steps to reproduce:**
Create an ItemList with complex items added with `add_child()` as neither of the `add_*item` convenience methods accept necessary parameters, for example:
```
+- ItemList
  +- HBoxContainer
    +- CheckButton
    +- Label (expand)
    +- Label (right align)
    +- CheckButton
    +- CheckButton
```

**Minimal reproduction project:**
[ItemList Test.zip](https://github.com/godotengine/godot/files/2303237/ItemList.Test.zip)

**Comment by Zylann** [comment]
I'm not sure `ItemList` is supposed to be used like that. `ItemList` generates its own elements.
If you want to make a list of controls ending up like `ItemList`, you should use `ScrollContainer` instead.

**Comment by Noshyaar** [comment]
`ItemList` is not meant to be used like that. It doesn't inherit from `Container` unlike `HBoxContainer`. Only those inherited from `Container` can control their child size and position. It seems like it's working because of the inner HBoxContainer. If you replace the ItemList with any other Control nodes, it will do the same.

**Comment by tko** [comment]
Possibly, I'm new to Godot and was looking for something to handle a list of items with basic mouse interactions taken care of already. Something like ItemList and/or PopupMenu without the popup bit but with fewer restrictions on what the item can be.

**Comment by Noshyaar** [comment]
Having nested HBoxContainer and VBoxContainer is not uncommon. The editor is doing this too.
```
VBoxContainer
    HBoxContainer
        Label
        Button
    HBoxContainer
        Label
        Button
    etc.
```
or try GridContainer.

**Comment by nobuyukinyuu** [comment]
Instead of `ItemList`, nesting your containers inside `ScrollContainer -> VBoxContainer` will provide listbox style functionality.

**Comment by Noshyaar** [comment]
Closing as working as expected, but we still want to hear the suggestion on improving the docs about ItemList so it's less confusing.
