### ISSUE TITLE
changing output font size with the slider crashes Godot and now no project will open unless you delete editor settings. Mac OS X

### ISSUE THREAD

**Issue by sdhy** [godotengine/godot#21237]
**Godot version:**
Godot 3.0.6 for Mac OS X.

**OS/device including version:**
Mac OS X 10.11.6 (15G20015)
El Capitan

**Issue description:**
I moved the slider to change the Output font size,
expecting it to simply change the font size,
but it changed to a really big negative number,
and then Godot started lagging (i.e. the spinning colour wheel).
I didn't waste time to force quit it.

But now it won't open any Godot project,
not even a brand new one.

I had to delete editor_settings-3.tres
But even after doing that, Godot crashes if you try to scan your user name's folder in Mac OS X.
Making a new folder or scanning an encr
ypted volume works, though.

**Steps to reproduce:**
Editor Settings > Run > Output > Font Size:
move the slider and you'll see big numbers - or + for font size

Once you open the Output window, Godot freezes (i.e. spinning rainbow wheel).

You can either force quit, or wait for Godot to quit by itself.

Then when you re-open Godot and try to open any project, even a brand new one, Godot quits.

Godot won't open any project until you delete Godot settings by typing this in Terminal:
rm ~/Library/Application\ Support/Godot/editor_settings-3.tres
(Thanks to Calinou and john_cephalopoda for telling me how to delete this file)

No recent projects will appear.
Scanning your user name's folder in Mac OS X will freeze Godot.

Making a new folder for a new project or scanning an encrypted volume works, though.

Note: Typing font sizes worked normally.

**Minimal reproduction project:**
The happens on a new project.

**Comment by bruvzg** [comment]
Setting font size too high do cause slowdown with tons of [mv > 4096 condition errors](https://github.com/godotengine/godot/blob/master/scene/resources/dynamic_font.cpp#L485-L486) and eventually crash.

In master branch "slider" behaviour is fixed and value won't change too fast, but it's still uncapped and can be set to any value (including negatives).

>Godot won't open any project until you delete Godot settings by typing this in Terminal:
rm ~/Library/Application\ Support/Godot/editor_settings-3.tres

You do not need to delete whole settings file, simply open it in the text editor and change invalid value manually, line is named same way as in editor settings `run/output/font_size`

**Comment by reduz** [comment]
@toger5 i suppose a higher limit needs to be used?

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by Calinou** [comment]
I can confirm this in https://github.com/godotengine/godot/commit/17d92c2b0995e82f5291c5a1e097e7b607151d31. If anyone has crashed the editor this way, it can be fixed by removing this line from `editor-settings-3.tres` then restarting the editor:

```text
run/output/font_size = -74
```
