### ISSUE TITLE
Light2d shadow with mix mode modulates transparent pixels

### ISSUE THREAD

**Issue by veloc1** [godotengine/godot#21238]
**Godot version:**
3.0.6.stable

**OS/device including version:**
Tried at several configurations:
Windows / Intel HD 4400
Windows / Radeon R5

**Issue description:**
Setting up a Light2D with mode = mix, shadow enabled and shadow color #5c525252. Light texture from here: http://www.gamefromscratch.com/post/2016/09/23/Godot-Engine-Tutorial-Part-18-2D-Lighting.aspx

When adding sprite with some transparent pixels, shadows affects transparent pixels too:
In engine:
![default](https://user-images.githubusercontent.com/18250624/44359139-a6dcd800-a4bf-11e8-960e-4032af275b8f.png)
In game:
![default](https://user-images.githubusercontent.com/18250624/44359174-bd832f00-a4bf-11e8-8506-4a1b0b598a3c.png)

Did I missing something, while configuring lightning?

**Minimal reproduction project:**
[godot-test-light2d.zip](https://github.com/godotengine/godot/files/2303530/godot-test-light2d.zip)

**Comment by reduz** [comment]
this is a problem of multi pass rendering, should be fixable in 3.2 with singlepass

**Comment by asheraryam** [comment]
Wondering if there's a workaround for this currently?

**Comment by KoBeWi** [comment]
Should be resolved already in 4.0-dev.

**Comment by dweremeichik** [comment]
4.0 Has a number of Light2D issues that prevented me from testing this in the past. I managed to find a workaround in v3.4.2.stable.official [45eaa2daf] that should work for a good number of use cases.

I've attached an MRP for the workaround, so others can see for themselves.
[transparent_light_workaround_mrp.zip](https://github.com/godotengine/godot/files/7991693/transparent_light_workaround_mrp.zip)

As an overview here is the setup I used (the project has some extra nodes for testing purposes not shown here):

- Node2D (World)
  - ColorRect (test background color)
  - LightOccluder2D
  - Sprite2D (to test shadows)
  - Sprite2D (to test shadows w/ "Light only" Light Mode)
  - Player
    - Sprite2D ("Unshaded"  CanvasItemMaterial LightMode)
    - Light2D (in Mix mode, Shadow enabled, all other settings default)
  - CanvasModulate (set to a greyscale color, but could be any color)

I used a greyscale ramp to test the Light2D which worked surprisingly well to see what I did and didn't like (default in the MRP).
<img src="https://user-images.githubusercontent.com/4079608/152277426-34f5fd58-5134-42da-8785-de448a8f0b7b.png" width=500>

For posterity I also used the light texture used in the original issue MRP. You can find each texture as a separate Light2D under the Player scene.
<img src="https://user-images.githubusercontent.com/4079608/152276422-01382819-f990-408f-81b8-46c9c643bc4a.png" width=500>
