### ISSUE TITLE
Save a project's open scenes in editor between sessions

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#21247]
This is a feature request related to #20994, but was a bit off-topic to post in that thread, so I made a separate issue for it.  

Editor folding defaults sound like they are currently saved in `project.godot`.  One quality-of-life improvement similar to saving the folding defaults would be to save the tabs for open scene views in a project so that they can be reloaded automatically the next time the project is opened.  This would probably have similar issues with version control compared to folding defaults if implemented in a similar fashion.

**Comment by akien-mga** [comment]
The option exists already:
![screenshot_20180820_235740](https://user-images.githubusercontent.com/4701338/44368943-d2b68880-a4d4-11e8-9fc9-57de361216ac.png)

**Comment by nobuyukinyuu** [comment]
much appreciated; I had no idea.  (I tried searching for a dupe issue first, I promise!)
