### ISSUE TITLE
store_pascal_string() crashes when saving an empty string

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21242]
**Godot version:**
v3.0.5-stable_x11.64, Xubuntu

**Issue description:**
_store_pascal_string()_ crashes the game when trying to save an empty string.

**Steps to reproduce:**
Download the example project.
Run the scene.
The game quits.
Edit the script, write anything in the currently empty string.
Run the game.
The game runs fine.

**Example project:**
[pascal_string_bug.zip](https://github.com/godotengine/godot/files/2303609/pascal_string_bug.zip)

**Comment by reduz** [comment]
yes, problem here is that in an empty string, doing string[0] crashes.

**Comment by hpvb** [comment]
There's a PR open for this #21708
