### ISSUE TITLE
When reparent, two lines are shown which do the same thing

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21258]
**Godot version:**
3.1 calinou faa49c1

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
When I try to move my node at the top of children of parent node, two lines are shown which do exacly the same thing, it only happens when Node have child. (Video 1)

It is also visible when I try to move Node below other(Video 2)

EDIT: Look at the length of this lines one is longer and the other is shorter so it must be different.

**Steps to reproduce:**
1. https://streamable.com/30w4v
2. https://streamable.com/otjdy

**Comment by Noshyaar** [comment]
It does different things that result in the same thing. If you slowly move the cursor, longer line will appear when hover above parent, shorter line when above child.
Longer line: put node as child right below parent
Shorter line: put node right above that child node

Not sure what to fix here, unless you expect that longer line means put node as the parent's sibling.

**Comment by clayjohn** [comment]
I agree. This doesn't look like a bug. Closing.
