### ISSUE TITLE
keyboard hide show in mobile

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#2126]
I was reading the code for android and I saw functions for hide and show keybaord but it was not binded to gdscript I wonder why ? 
I think status of keyboard is it showing or not , and function to hide and show it can be very helpful. why not just bind them to gdscript?

**Comment by akien-mga** [comment]
@reduz @punto- Any idea about this?

**Comment by punto-** [comment]
Aren't they on OS? As far as I remember there was no api to show or hide on
Android, only to "toggle", but the OS api provides functions to show and
hide as far as I remember..

**Comment by akien-mga** [comment]
There seems to be OS methods for that indeed, but they're not exposed to GDScript: https://github.com/godotengine/godot/blob/master/platform/android/os_android.cpp#L627-L651
