### ISSUE TITLE
Curve editor is not moving points in the correct plane

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#21262]
When I'm editing a curve for a Path, I have the interface set to top view Orthogonal I expect that moving the points on a curve around, the points should only move in the X and Z direction, the Y should remain constant.

After moving things around I can see the curve is now all over the place, it has changed the Y coordinates. Didn't use to do this :)

Godot 3.1 master commit 68676c774d4f3b7bfad8866a08546acf5a594cdf

**Comment by JFonS** [comment]
I tried to reproduce this but I couldn't. I added a Path node and moved points around while in top orthogonal view but they all ended in the same plane, any idea on what can be going on? 

I suspect it may be related to #20584 but I'm not sure.

**Comment by oisincar** [comment]
I'm getting this too. More detailed steps to reproduce:

0: Create path with 2 points.
1: Viewing the path from the side, move one of the points up high along the vertical axis
2: Move viewport camera to the top, looking down. Move the both points a small amount.
3: See that both points are now very close by, the second point has been moved a lot along the vertical axis.

It seems like whenever you move a point, it moves it to be the same distance from the camera as the path's center is.

**Comment by JFonS** [comment]
It was my fault indeed, I'll open a PR fixing this in a bit.
