### ISSUE TITLE
Spatial axis lines in editor are choppy.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21264]
Using Win10 and a 64-bit build from this morning, I noticed the axis lines in the spatial editor are having some rendering issues.  Maybe the problem is deeper than this?

![3 1 0](https://user-images.githubusercontent.com/13004169/44407680-69338a00-a567-11e8-97df-82f4478cdd88.gif)

Looks fine in the stable release.

![3 0 6](https://user-images.githubusercontent.com/13004169/44407693-6fc20180-a567-11e8-8d33-591efb67aa8f.gif)

**Comment by vnen** [comment]
I thought this was fixed by #21129. CC @Calinou

**Comment by Calinou** [comment]
It looks like the grid doesn't take the origin into account when it's first created. This can be worked around by unchecking **View -> View Origin** and then checking it again, but the editor should be fixed to draw the grid correctly from the start.

**Comment by avencherus** [comment]
@Calinou Seems fine now, has anything changed?  If it can be fixed in a permanent way with that work-around, I'm not sure how to recreate it to check for it.

**Comment by avencherus** [comment]
Nevermind, cleared the editor settings out today, still there until the origin option gets toggled.

![godot master_2018-08-29_01-15-34](https://user-images.githubusercontent.com/13004169/44754133-51d93b80-ab29-11e8-811f-db419eebd56f.png)
