### ISSUE TITLE
Official Nightly Builds Server

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#21270]
Hi all, I talked personally with @reduz in a Godot Meetup in Thursday 2 August in Montevideo (the city where I'm living) about the nightly builds server and he told me that @hpvb have available servers to host it. Today I lost my job due disability problems I had the previous week, and now I'm free for building the server. I watched that Contabo (https://contabo.com) has cheap and bigger servers (VPS) but they have no kvm (for virtualizating windows and mac for making the mono enabled builds) but the dedicated server solutions are expensive I think. In a little I can send you the architecture model of the buildserver to begin building it, but before I need a server.

@hpvb, what's your opinion for the best server for doing ALL Godot builds?

I'm thinking to offer a service for doing custom builds for people that want to pay some money or special Patreon contributors (for doing builds with admob, etc)

@reduz, give me feedback ;)

**Comment by Chaosus** [comment]
Seems like discussion seems dead here. I suggest to discuss it in IRC, reduz is always been there.
