### ISSUE TITLE
GDScript doesn´t allow implicit declaration in function parameters in a plugin

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#21273]
**Godot version:**

**3.1 dev after 06/08/2018 doesn´t compile plugin**

**3.1 compiled at 17/07/2018 compiles plugin**

**OS/device including version:**

Win7,8,10

**Issue description:**

This plugin: https://github.com/Ranoller/JSON_Edit compiles perfectly in godot 3.1 from 17/07. Now, in master, throws this error:
`**res://addons/json_edit/json_edit.gd:601 - Parse Error: Identifier 'item' is not declared in the current scope.**
`
Referenced code:

```
func text_item_to_itemetadata(item=SelectedItem, key= item.get_text(1), member= item.get_text(2),tipo= item.get_text(3)): 

	#Columna 1 : Key->
	
	item.set_metadata(1, str(key))

	#Columna 2 y 3 : Miembro/tipo->
	
	if member.is_valid_float():
		item.set_metadata(2, float(member))
		item.set_metadata(3, TIPOS.FLOAT)
```

So... godot 3 allow to access variables declarated in function parameters and 3.1 after jul/18 not. I think that this is a bug or a breaking compatibility.

**Steps to reproduce:**
Install that plugin in a project and open godot.

**Comment by akien-mga** [comment]
CC @vnen

**Comment by akien-mga** [comment]
Here's a simpler reproducer that can be pasted in any test project:
```gdscript
var dict = {
	"id": 42,
}

func _ready():
	some_method()

func some_method(param1=dict, param2=param1.id):
	print(param1)
	print(param2)
```

It errors with:
```
SCRIPT ERROR: GDScript::reload: Parse Error: Identifier 'param1' is not declared in the current scope.
   At: built-in:10.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:579.
```

It does work in 3.0, even though I would not expect such a feature to work.

**Comment by akien-mga** [comment]
I also don't think this should be supported. To confirm with @reduz, but I think it was really by chance that it worked in the past, not by a design decision.

**Comment by akien-mga** [comment]
@Calinou Can you add this to the known compat changes in the changelog?
