### ISSUE TITLE
Changing default value of exported variable not reflected in editor

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2128]
When I change the default value of an export var in the GDScript, it is not reflected in the editor, or to the engine. Only after I temporarily re-name the variable, it gets updated.

**Comment by okamstudio** [comment]
yeah, the editor for now will not realize you had previously set it or not,
you have to change it manually.
This will change eventually, but for now change it from the UI or rename.

On Fri, Jun 19, 2015 at 10:02 PM, seadra <notifications@github.com> wrote:

> When I change the default value of an export var in the GDScript, it is
> not reflected in the editor, or to the engine. Only after I temporarily
> re-name the variable, it gets updated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2128>.
>



-- 

*OkamStudio*

**Comment by seadra** [comment]
OK, thanks!

**Comment by reduz** [comment]
changing the default value will not reflect in the editor given it might have been edited and you want to keep what was edited. What was added instead is the ability to roll-back to the value written in code
