### ISSUE TITLE
Segmentation fault on opening a project on musl libc

### ISSUE THREAD

**Issue by ronchaine** [godotengine/godot#21282]
**Godot version:**
master branch, haven't found a working version yet

**OS/device including version:**
Any linux distribution using musl libc.  Repeatable at least on Gentoo and Alpine.

* amdgpu open source driver

**Issue description:**
When opening editor, godot crashes.  Segmentation fault is visible in the debugger.

**Steps to reproduce:**
* Have a linux that uses musl instead of glibc.
* Launch godot, select any project, press "edit".

This might be amdgpu issue, or have something to do with musl stack size.  Needs more data when it appears, and if it happens on non-amdgpu-systems.

**Comment by ronchaine** [comment]
I am working on this myself, but unfortunately can't allocate much time.  It's probably not very high priority anyways, since same computer can run godot just fine in glibc chroot.

**Comment by akien-mga** [comment]
Can you get a backtrace?

**Comment by ronchaine** [comment]
```
#0  0x00007ffff7dc7c35 in memcpy () from /lib/ld-musl-x86_64.so.1
#1  0x00007ffff65fc704 in ?? () from /lib/libz.so.1
#2  0x00007ffff65fc989 in ?? () from /lib/libz.so.1
#3  0x00007ffff65fdeed in deflate () from /lib/libz.so.1
#4  0x00007ffff2c2d649 in ?? () from /usr/lib/dri/radeonsi_dri.so
#5  0x00007ffff2c2d8b5 in ?? () from /usr/lib/dri/radeonsi_dri.so
#6  0x00007ffff2c34991 in ?? () from /usr/lib/dri/radeonsi_dri.so
#7  0x00007ffff2c34727 in ?? () from /usr/lib/dri/radeonsi_dri.so
#8  0x00007ffff7dbbc2e in ?? () from /lib/ld-musl-x86_64.so.1
#9  0x0000000000000000 in ?? ()
```

I had the plan that I'd build mesa with debug symbols and take a closer look at that next, but haven't gotten to that yet.

**Comment by ronchaine** [comment]
OK, this is fixed by increasing stack size.  There's a mesa patch for Void linux, and a PR exists for gentoo/musl and alpine that increases thread stack size.  Closing this.

**Comment by rofl0r** [comment]
i suppose this was the patch fixing it: https://github.com/void-linux/void-packages/commit/18838a6cd6b00b1d309d6cc712b7d54660597221 (linking it here in case others encounter this too).
