### ISSUE TITLE
RigidBody2D speeds up geometrically

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#21289]
**Godot version:**
ed10ff65f

**OS/device including version:**
Windows

**Issue description:**
When Camera2D is child of moving RigidBody2D with linear velocity, the body will speed up geometrically instead of moving linearly.

**Steps to reproduce:**

1. Set up RigidBody2D with Camera2D as child.
1. Disable linear damping and gravity to make problem apparent.
1. Apply linear velocity to the body. Error will manifest once camera begins moving.

**Minimal reproduction project:**
[Github repo](https://github.com/lekoder/godot-issue-physics2D-transform-broken)

*Expected behaviour:* Body moves steadily at 10px/sec.
*Actual behavior*: Body speeds up geometrically.

**Additional information**
I managed to pinpoint the problem down to ed10ff65f, it works well in 65c8a4912. Likely caused by #21245 by @RandomShaper. I speculate that the transforms mentioned in #21245 are applied errorously.

**Comment by RandomShaper** [comment]
Could you try with 20dc630 reverted? (only that commit that adds optimization, but keeping the other one in the PR).

**Comment by lekoder** [comment]
@RandomShaper unfortunately, same thing happens without 20dc630.
