### ISSUE TITLE
LineEdit expand on text length

### ISSUE THREAD

**Issue by gmarais** [godotengine/godot#21284]
**Godot version: 3.0.6**

**Issue description:**
One setting that option to true, the line edit box will expand but will not expand all the way and the first characters of the line are being eaten away.
Also the line edit expand does not take into account the placeholder's length.
(Font used: Arial)

**Steps to reproduce:**
Place a LineEdit in the scene and add a place holder text, check on expand on text length, start the game type some text in it.

**Additional Suggestion:**
Add an option to not have a background. (we can always use and empty stylebox but still might be an idea)

**Comment by gmarais** [comment]
I might add that in the mean time for people that would want that kind of behavior:
You can always do something like that in gdscript which should work fine for a line edit:

`const TEXTXMARGIN = 32
func update_size():
	var f = get_font("font")
	var textsize
	if text.length():
		textsize = f.get_string_size(text)
	else:
		textsize = f.get_string_size(placeholder_text)
	rect_min_size = Vector2(textsize.x + TEXTXMARGIN, rect_min_size.y)
	rect_size.x = textsize.x + TEXTXMARGIN
`

**Comment by adabru** [comment]
> One setting that option to true, the line edit box will expand but will not expand all the way and the first characters of the line are being eaten away.

Hi @gmarais, can you still reproduce this in Godot 3.2.1? I couldn't reproduce a setup where characters disappear.

**Comment by KoBeWi** [comment]
Looks fixed to me, please provide a minimal reproduction project if you can still reproduce in Godot 3.2.4.
