### ISSUE TITLE
Material Preview is affected by distance fade dithering

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#21295]
**Godot version:**

106e5a8 Manjaro x86_64

**Issue description:**

The preview is accurate, but it's not useful.

PixelAlpha
![image](https://user-images.githubusercontent.com/26753932/44497184-3346f080-a6a2-11e8-8f20-27b10eaa7113.png)

ObjectDither & PixelDither
![image](https://user-images.githubusercontent.com/26753932/44497103-a0a65180-a6a1-11e8-94ee-76f3aca9bf58.png)

**Steps to reproduce:**
New MeshInstance
New SpatialMaterial
Set SpatialMaterial distance_fade_mode to anything except Disabled.

**Comment by reduz** [comment]
I think it's really cool, also i don't think it can be fixed :P

**Comment by reduz** [comment]
Yes, no matter how much I think about it, I see no way of fixing this.
