### ISSUE TITLE
Camera2D causes KinematicBody2D to fall through collisions

### ISSUE THREAD

**Issue by suptoasty** [godotengine/godot#21292]
**Godot version:**

master

**OS/device including version:**

windows 10, nvidia gtx 1060

**Issue description:**

I have a kinematic player that can move left, right, and has gravity with move_and_slide. I added a camera2D to it and it immediately began to fall through the staticbody2d floor

**Steps to reproduce:**
1) make a player that has gravity so it moves to contact point like staticbody2d. it should collide and stop
2) add a camera2d. it will move through floor

**Comment by lekoder** [comment]
Probably related/duplicate of #21289

**Comment by akien-mga** [comment]
Assuming this was the same issue as #21289, it should be fixed by ab3716bd4. Please comment if you still reproduce the issue.
