### ISSUE TITLE
Errors while closing GridMap editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#21298]
**Godot version:**
 2db4942

**Issue description:**
`core/rid.h:154 - Condition ' !p_rid.is_valid() ' is true. returned: __null`
`servers/visual/visual_server_scene.cpp:620 - Condition ' !instance ' is true.`

**Comment by Vadyanga** [comment]
@YeldhamDev did you solve this?

**Comment by YeldhamDev** [comment]
@Vadyanga Nope, and now it happens when opening it as well.

**Comment by YeldhamDev** [comment]
Fixed by 8306d60e85269f97e0173a4f7c61bcac46f4087b.
