### ISSUE TITLE
Changes in RigidBody Rotation and Scale properties aren't reflected in the game

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2129]
I have a RigidBody, and it has two children: a CollisionShape (BoxShape) and a TestCube.
When I select the RigitBody and change it's Rotation and Scale properties, it is immediately reflected corectly in the editor. But when I run the game, it appears like Rotation and Scale are in their default values: (0,0,0) and (1,1,1).

**Comment by reduz** [comment]
depends on the mode.

If it's in character mode, you can't rotate it (but you can rotate the
shapes)
And you can't scale it unless in Kinematic or Static mode (but, again, you
can rotate and scale the shapes)
Scale must also not be non-uniform for non-polyhedral shapes.

This is a standard limitation in physics engines, you will see it in Unity
and other engines, as PhysX suffers from the same.

**Comment by seadra** [comment]
Thanks! I just went through the [doc](https://github.com/okamstudio/godot/wiki/class_rigidbody2d).
However, the RigidBody object is in Rigid mode, so I guess it this is indeed a bug?
