### ISSUE TITLE
Snap to grid can not Snap to position(0, 0)

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#21300]
**Godot version:**

3.0.6

**OS/device including version:**

**Issue description:**

When set grid step to 8 or 16, it's impossible to drag to position(0,0)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by eon-s** [comment]
Cannot replicate with Node2D nodes, but in the case of Controls snap is not respecting the pivot.

Can you share a small project with the bug?

**Comment by alexzheng** [comment]
Oh, I notice I have shifted the parent node off (0, 0), so it's impossible to Snap its children to (0, 0), I thought snap can support relative to parent, it seems it can not.

**Comment by alexzheng** [comment]
I found the steps to correct it, after check snap relative on, the position of node to be dragged must be set manually in the inspector to (0, 0).Then it's possible to drag and snap to (0,0).

**Comment by alexzheng** [comment]
I think it's not a bug. only a manually step is required to change to the start position .

**Comment by KoBeWi** [comment]
So the true issue here is that you can't snap relatively to parent's position, but only in absolute coordinates, which means that you can't reach the _local_ (0, 0) and similar points. Which doesn't sound like a bug.

**Comment by KoBeWi** [comment]
Closing as non-bug then.
