### ISSUE TITLE
Improving the new project dialog box

### ISSUE THREAD

**Issue by LittleWhite-tb** [godotengine/godot#21306]
Hello,

I would like to suggest some small improvements to the "New Project" dialog box.
The overall goal of that is to make it even easier to use, lighter and more direct to start a new project.

When opening a new project, the dialog box is prompted and directly you have a red message telling that the project path is not empty (at least on Linux, since it's pointing in the home folder). To solve this, you have to change the project name (or to keep it) and click on the "Create folder" button. Then, you can create your project.
If you manually type a project path, you could specify a folder which does not exists yet. Of course, the dialog box will tell you about it. And if you type an existing folder, you will possibly have the "not empty"  message. Ever, you will create the folder by hand in the file explorer, or click on the create folder (but, in such cache, the folder has the same name that the project), or to use the embedded file explorer.

As an improvement, I would suggest to automatically create a new folder, with project name, in the folder specified by project path.
Moreover, If the project path does not exist, Godot should try to create the missing folders.

By doing this, it would be possible to:
- remove the "Create folder" button
- remove the different red messages
- make it easier to use: when opening the dialog box, you can directly press the "Create & Edit" button

**Comment by Oranjoose** [comment]
A lot of applications work like this, such as Unreal Engine and Adobe Premiere. If you really want to "protect" users from using a folder with existing assets in it, then the compromise should be that the folder is created automatically with the project name as the name imo.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/4749, as feature proposals are now tracked on the Godot proposals repository.
