### ISSUE TITLE
godot Export2Linux issue

### ISSUE THREAD

**Issue by ahmedyounis75** [godotengine/godot#21302]
hi 
i want to solve this issue found on this video .. i use linux-mint distribution

in fact i run all steps at laptop and desktop pc - i cant understand what is the missing - i want to know the core of problem to solve it clearly 
i cant export for any platform although i run all steps 
maybe i don't know something for install all export file by right way 
thank you in advance

https://youtu.be/sQPWTfCa1r8

**Comment by akien-mga** [comment]
Indeed, please use one of the other community channels: https://godotengine.org/community
This repository is for engine bugs, not usage questions.

**Comment by ahmedyounis75** [comment]
sorry for that .. and thank you .. i think this is problem for more users 
i will put it at another community :+1:
