### ISSUE TITLE
Multi line comments in GDScript

### ISSUE THREAD

**Issue by CCODE05B** [godotengine/godot#21310]
I wish if there is another way to do multi line comments in GDScript , i know there is a way of selecting a code and pressing CTRL + K to comment the code , and press the buttons again to uncomment
but sometimes it does not uncomment the code , it adds another # 
@vnen , you did typed script , please you or someone add another way to comment the code , like this way maybe ? : 

#*
code
code
code
*#

**Comment by akien-mga** [comment]
You can fake multiline comments with multiline strings,
```
"""
code
code
code
"""
```

But additional work is needed on the parser to make multiline strings behave as true comments when not used as strings.

**Comment by CCODE05B** [comment]
@akien-mga well , that's something i didn't know about it , this works great !

**Comment by swarnimarun** [comment]
I don't think we need this issue anymore.

**Comment by AlexHolly** [comment]
You can also use ctrl+u to uncomment multiline selection where some lines have no comment.
