### ISSUE TITLE
A scene should be able to specify which children are editable by default

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#21311]
**Godot version:** 3.1 custom

**Issue description:**
If often happens to me that, when i make a scene, I have some objects that will need to be tweaked in another scene where my scene is instanced. Every time, i need to tick editable children and edit the children that i want to edit. This happens incredibly often with trigger areas.

**Suggestion:**
Have a system that behaves in a way similar to private/public in code: the scene specifies which nodes should be editable from a foreign scene. In order to not break compatibility, the current "editable children" could be renamed with "force editable children"

**Comment by DualMatrix** [comment]
I agree, this would be useful

**Comment by akien-mga** [comment]
Closing as duplicate of #22263 where most of the discussion is happening.
