### ISSUE TITLE
Inspector won't clear exported array when reset.

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/godot#21319]
**Godot version:**
3.1 master

**OS/device including version:**
Fedora 28 64-bit

**Issue description:**
When exporting arrays with default value null they wont reset to null when pressing the reset icon.

**Steps to reproduce:**
```
export(Array, NodePath) var components = null
```

It will start as "(Nil) Array". Set some value in the inspector and then try reset.

**Comment by Zylann** [comment]
What kind of array `null` is? I wonder if Godot is confused about that, maybe you should write it as an empty array `[]` instead?

**Comment by capnm** [comment]
@Zylann No, it's actually the other way around, Godot(-script) confuses people  ;)

https://www.lucidchart.com/techblog/2015/08/31/the-worst-mistake-of-computer-science/
« NULL has become so pervasive that many just assume that it’s necessary. We’ve had it for so long in so many low- and high-level languages, it seems essential, like integer arithmetic or I/O.

Not so! You can have an entire programming language without NULL. The problem with NULL is that it is a non-value value, a sentinel, a special case that was lumped in with everything else. »

**Comment by spongeboburu** [comment]
It's not a big bug, you can work around it by using [].

However, there is no purpose to allow values that doesn't work at all or yields inconsistent behaviour in the editor. The inconsistency lies in, why can't it be reset? It works like normal for everything except the reset. Either don't allow null or allow it to be reset like any other exported variable.

**Comment by spongeboburu** [comment]
I've tried the reset button and there's a bunch of resource types that it just doesn't work with. Tried TextFile, it too won't reset if the reset value is null (or not set).

**Comment by spongeboburu** [comment]
I'm sure someone will get around to fixing this before 3.1. In either case the topic seems dead so imma close this sucker.
