### ISSUE TITLE
Stopping games started from editor hangs editor for 10 seconds

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#21324]
**Godot version:**
current master 
https://github.com/godotengine/godot/tree/0edb50f629bd878d2b8c98d1a6f50c23316f1ac2

**OS/device including version:**
Windows 10

**Issue description:**
I noticed recent master branch builds now have a pretty annoying delay when 'stopping' the game started from the editor.

It used to be that when you click stop you would be able to continue working on your game instantly. Now when you click stop there is a painful delay where the whole Godot hangs for many seconds.

I believe this negatively affects productivity too much.

Looking at #21236 which I believed to be (and actually is) the cause of the issue, I noticed that I can configure the `editor/stop_max_wait_msec`. I couldn't find it in the project settings, so I added it manually and set its value to 10 (milliseconds). Now it is instant as before.

I just want to say that the default should be set very low as I think this negatively impacts productivity and could create a bad impression to new users. Let people increase the number if they want.

The default in the code is 10 seconds, and it seems that when I hit stop using the defaults I have to wait 10 seconds every time before I can continue working on my project.

**Comment by dragmz** [comment]
@chanon How do you reproduce the problem?

**Comment by chanon** [comment]
Here is the reproduction:
[SlowClose.zip](https://github.com/godotengine/godot/files/2320788/SlowClose.zip)

In this case I think it has something to do with the `config/auto_accept_quit=false` setting.

I am not sure if there may be other causes, but this is the first that I have found.

With my game, if I clear the `config/auto_accept_quit=false` setting, then stopping the game is fast with a very small (but noticeable) delay.

However, if I play my game a bit more, the delay will be about 3 seconds, which is not too bad but still annoying. Personally, I would set my project setting for this to 10 msec to not waste development time (it adds up).

**Comment by chanon** [comment]
I guess it makes sense since with graceful quitting it is not sending a hard kill message.
My app is probably responding with the same thing as what I coded for my android 'back' button .. and it doesn't quit so everything just hangs.

**Comment by dragmz** [comment]
It does make sense to me, thanks @chanon.

**Comment by chanon** [comment]
I think same result would occur if people coded their game so that when you try to quit / alt-f4 / click the X button on the window and it pops up with a message to ask whether you are sure.

I'm not sure how to make this work for that case.

**Comment by dragmz** [comment]
I should be able to fix it with a custom windows message that forces the scene tree to quit even if ``config/auto_accept_quit`` is ``false``

**Comment by dragmz** [comment]
@akien-mga thanks for reverting this
