### ISSUE TITLE
Invalid root Viewport size

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#21338]
**Godot version:**
my last build was SHA1 - d7b892294b5385834c8d5e78d3da41e4217c7eab

**OS/device including version:**
Windows x64  + AMD Radeon HD 7500M/7600M Series

**Issue description:**
I copypasted some code from the Navmesh Demo and when started to move my character a lot debug of messages started to spam, when i checked i found out that when i minimized the window the root viewport's size is 0 rather than the window screen (wich is the value i'd expect to see) causing th span, even though i'm not calling `project_ray_origin` myself from script (i call it only on mouse clicks, but the error spams on every frame after my first call)
![imagen](https://user-images.githubusercontent.com/1776044/44557579-8c03a100-a715-11e8-8b7f-29f87625e9a4.png)

**Steps to reproduce:**
1. Open Navmesh Demo
2. Click somewhere
3. Minimize the window
4. Look at the console (looks like inproject console output is disabled somewhere on this project, because it doesn't displays prints or anything)

**Minimal reproduction project:**
This can be reproduced with the [Navmesh demo](https://github.com/godotengine/godot-demo-projects/tree/master/3d/navmesh)

**Comment by marcelofg55** [comment]
This should be fixed by #24078, if you can please test it again with latest master. Thanks!

**Comment by akien-mga** [comment]
Closing as fixed by #24078 so that we don't forget, but please comment to confirm that it does work as expected. If not, we can reopen the issue.
