### ISSUE TITLE
\n and \t doesn't work in controls, unless if set via GDScript

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21334]
_\n_ and _\t_ doesn't work in _Label_, _Button_, etc. when set via the editor. It does work though via GDScript.

Looks like this has been lost on the way:
https://github.com/godotengine/godot/issues/2967#issuecomment-210496149

**Comment by akien-mga** [comment]
That's a duplicate of #2967, no?

**Comment by char0xff** [comment]
Oh, it's still open, my bad, I thought it was closed.
