### ISSUE TITLE
"Show in File Manager" doesn't show the correct folder when a search is active

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#21331]
Godot 3.0.6
Windows 10 64 bits

Reproduction steps:
1) Have a project with a resource (say a shader) inside a sub-folder
2) Go to that sub-folder
3) Right-click on the resource, and `Show in File Manager`: the file manager opens at the correct location
4) In Godot, go back to the root of the project
5) Type the name of the resource in the search box
6) Right-click on the resource which appears again, and `Show in File Manager`: the file manager now opens at the root of the project instead. I expected the same as 3).

**Comment by swarnimarun** [comment]
Was originally gonna make a description about how to fix it but, 
seems like someone has already fixed it. But seemingly it not cherrypicked in 3.0.x branch.
It should be cherrypicked for 3.0.7 if that is coming.
So this is no BUG.

This is the commit. https://github.com/godotengine/godot/commit/836565b2493b9f5b39c885cab35b40457604c306

Close this @akien-mga or @Zylann.
And I think you should try master before making a issue, just saying.

**Comment by Zylann** [comment]
Indeed, works in master. Sorry I was going to but forgot as I went on another issue while it was compiling.

**Comment by swarnimarun** [comment]
I feel ya, happens to the best of us.
