### ISSUE TITLE
Ability to make animations unique without changing names

### ISSUE THREAD

**Issue by kernelcrasher** [godotengine/godot#2133]
As of now, a duplicate AnimationPlayer will share the animation and the parameters with the original. Sometimes it would be convenient to use relative transform paths in an animation and just duplicate the AnimationPlayer, tweak the parameters on its version of the animation, then reparent it to a different node. This would make it so that you can use a template for the animation and then play the same animation name on each node through GDScript, resulting in a different behavior in each case.

**Comment by reduz** [comment]
already have it, select animation player -> go to property editor -> press
the gear icon -> make resources unique
if you want to do this for individual animations, just make a copy.

**Comment by okamstudio** [comment]
ah I lacked "without changing names".. good point


On Sat, Jun 20, 2015 at 11:52 AM, Juan Linietsky <notifications@github.com>
wrote:

> already have it, select animation player -> go to property editor -> press
> the gear icon -> make resources unique
> if you want to do this for individual animations, just make a copy.
>
>
>
> On Sat, Jun 20, 2015 at 11:36 AM, kernelcrasher <notifications@github.com>
> wrote:
>
> > As of now, a duplicate AnimationPlayer will share the animation and the
> > parameters with the original. Sometimes it would be convenient to use
> > relative transform paths in an animation and just duplicate the
> > AnimationPlayer, tweak the parameters on its version of the animation,
> then
> > reparent it to a different node. This would make it so that you can use a
> > template for the animation and then play the same animation name on each
> > node through GDScript, resulting in a different behavior in each case.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/2133>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2133#issuecomment-113776749>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment]
will try to make this more obvious in 2.1

**Comment by nunodonato** [comment]
Folks I was about to add an issue but I found this one and I'm not sure if I have a duplicate or something different. My case is as follows:
I have an object with has an animation player has a child.
In my main scene I add several duplicates of said object. When the player touches on, it should play an animation. But instead, it plays the animation in all objects. Is this the same thing?

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
What's the status on this issue in the current master branch?

**Comment by KoBeWi** [comment]
Looks like since 3.0 animations in duplicate AnimationPlayers are independent, which is what OP wanted.
