### ISSUE TITLE
CSG should have an `update:never/once/always` setting

### ISSUE THREAD

**Issue by nodefish** [godotengine/godot#21345]
CSG shapes should have an `update: never / once / always` setting to determine whether to execute the boolean operation on every frame.

If CSG shapes are constantly re-evaluated in real time, performance suffers. I'm aware they're more for "blocking out" levels but as exporting them to a DCC is a convoluted idea at this point with regard to the modeling pipeline, and not yet implemented, this is a simple way to make them usable for simpler needs without having to use a DCC.

(Apologies for the formatting of this post, I kind of bungled it and had to edit everything in...)

**Comment by Xrayez** [comment]
CSG operations are done as frequently as local transform of these shapes are changed, so it's not really real-time. I see no `NOTIFICATION_PROCESS` or similar:

https://github.com/godotengine/godot/blob/74932b905e928015394aff68a0502a49994d47f7/modules/csg/csg_shape.cpp#L500-L547

One can also change the visibility of each shape, it will skip boolean operation against hidden shapes.
