### ISSUE TITLE
Bit flags in godot does not match documentation.

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/godot#21349]
**Godot version:**
3.1 dev

**OS/device including version:**
Fedora 28, 64-bit.

**Issue description:**
Editor shows exported bit flags without bit names as an integer instead of a list of booleans.

**Steps to reproduce:**
```
# Individually edit the bits of an integer.
export(int, FLAGS) var spell_elements = ELEMENT_WIND | ELEMENT_WATER
```
This becomes a normal integer spin edit in the editor while the documentation suggest that I might be able to set each bit of the integer as boolean values.

"Integers used as bit flags can store multiple true/false (boolean) values in one property. By using the export hint int, FLAGS, they can be set from the editor"

**Comment by Noshyaar** [comment]
cc: @vnen 
Should exporting bit flags without hint text be deprecated? Or the `PROPERTY_HINT_ALL_FLAGS` will be reintroduced in the future?
