### ISSUE TITLE
PI is not a constant

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2134]
const max_angle = PI/2
gives an error, complaining that the expression is not a constant.

**Comment by foxik0169** [comment]
If i am right, you aren't allowed to write expression to const variable. More info here: https://github.com/okamstudio/godot/wiki/gdscript#constantsts

**Comment by seadra** [comment]
That is a const expression though, and is clearly a bug.

**Comment by reduz** [comment]
yeah PI should be a language constant, this will be fixed later
