### ISSUE TITLE
GLES2: Color parameter of CPUParticles dont work

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#21350]
**Godot version:**
Godot 3.1 c9868faa88b938432d23a4b047b4d4942b632edb

**OS/device including version:**
Windows 10

**Issue description:**
Predefined `COLOR` parameter of spatial shader for CPUParticles dont work in GLES2 mode.
For example this shader works fine for GLES3:
```
shader_type spatial;
render_mode blend_mix,depth_draw_never,cull_back,unshaded;

void fragment() {
	ALBEDO = COLOR.rgb;
	ALPHA = COLOR.a;
}
```
**Minimal reproduction project:**
[godot-particle-test2.zip](https://github.com/godotengine/godot/files/2317340/godot-particle-test2.zip)

**Comment by akien-mga** [comment]
CC @karroffel
