### ISSUE TITLE
LineEdit's secret text can be copied and pasted revealing the secret text 

### ISSUE THREAD

**Issue by Claptrapwubwub** [godotengine/godot#21352]
**Godot version:**

v3.0.5_stable_win64

**OS/device including version:**

Windows PC 

**Issue description:**

LineEdit's secret property hides the text behind asterisk, however, the text can still be copied and pasted elsewhere to reveal the "secret" text. Its expected that the secret text either cant be copied or should remain asterisk after copying. 

**Steps to reproduce:**
copy any LineEdit text that is set to secret, then paste anywhere other than a LineEdit with secret enabled to reveal the secret text.  

**Minimal reproduction project:**

**Comment by Noshyaar** [comment]
What would be a better solution? Add another `allow_copy` property or force every secret LineEdit to be unable to copy? There's a corner case where this behavior is desirable e.g. Puzzle game.

**Comment by reduz** [comment]
should this not be closed?

**Comment by Noshyaar** [comment]
Fixed by #21358
