### ISSUE TITLE
IntArray, FloatArray, etcArray crash a game when accessing out of bounds index with get() (Should be detected by debugger)

### ISSUE THREAD

**Issue by Biliogadafr** [godotengine/godot#2135]
Accessing to IntArray, FloatArray, StringArray, Vector2Array,  Vector3Array, ColorArray with incorrect index is not detected by Godots debugger
For example this code will hard crash the game:
```
	var vector = Vector2Array()
	vector.get(0)
```

**Comment by akien-mga** [comment]
I can confirm this issue on the current master branch.

The debugger works fine if using ```vector[0]``` is the above exemple, but it crashes with ```get()```.

**Comment by akien-mga** [comment]
Those *Arrays are DVector internally, so this should likely be investigated around here: https://github.com/godotengine/godot/blob/2c45ee5e1ce939bcef32129ac01944f3995269f4/core/dvector.h#L303-L306

**Comment by reduz** [comment]
there is no way to fix this bug, so will simply remove the get() method :)
