### ISSUE TITLE
Typed GDScript - Cannot infer type on iOS

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#21366]
**Godot version:**
From master

**OS/device including version:**
iPhoneX iOS 11.4.1

**Issue description:**
Doing
```
var test: = File.new()
```
Works fine on Windows and MacOS, however when run on an iOS device results in:
```
 **SCRIPT ERROR**: Parse Error: Assigned value does not have a set type, variable type cannot be inferred.
At: res://child.gd:3:GDScript::reload() - Parse Error: Assigned value does not have a set type, variable type cannot be inferred.

```

**Minimal reproduction project:**
[res.zip](https://github.com/godotengine/godot/files/2318364/res.zip)

**Comment by akien-mga** [comment]
CC @vnen

**Comment by chanon** [comment]
Also failed with the same error when I defined a custom class eg.

```
class SomeClass:
	var someMembers: float = 0
	var object: Object = null

```

And then later

```
var myVar: = SomeClass.new()
```

**Comment by ricardoalcantara** [comment]
It also breaks on Android devices, as I mentioned here #24493
