### ISSUE TITLE
Air resistance

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2136]
It would be very nice if the RigidBody has built-in air resistance (Drag and Angular Drag properties), similar to [Unity](http://docs.unity3d.com/Manual/class-Rigidbody.html).

**Comment by mohaalak** [comment]
I think linear and angular damp is do this . is it not?

**Comment by seadra** [comment]
I can't find anything on damp in [RigidBody documentation](https://github.com/okamstudio/godot/wiki/class_rigidbody). Are you talking about [RigidBody2D](https://github.com/okamstudio/godot/wiki/class_rigidbody2d)?

**Comment by akien-mga** [comment]
The wiki documentation is outdated currently, but will be soon regenerated based on the source code. Check the in-game help in the master branch/nightly builds, it is more current and does mention linear and angular damp for RigidBody. (see also the source https://raw.githubusercontent.com/godotengine/godot/master/doc/base/classes.xml if need be)

**Comment by mohaalak** [comment]
Hey,

I just signed the petition "Donald Trump: Remove league of legends block
for iran and syria" and wanted to see if you could help by adding your name.

Our goal is to reach 500 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/zCHmTPLVMt

Thanks!
Mohammad Hadi
