### ISSUE TITLE
Crash exported game when using Particles2D but compiled with disable_3d=yes

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#21362]
**Godot version:**

3.1.dev f123694b4

**OS/device including version:**

Kubuntu 18.04 / gtx 670

**Issue description:**

Game crashes when using `Particles2D` but templates are compiled with `disable_3d=yes` option.
```
ERROR: instance: Condition ' !ti ' is true. returned: __null
   At: core/class_db.cpp:511.
ERROR: poll: res://play/play.tscn:16 - Parse Error: Can't create sub resource of type: ParticlesMaterial
   At: scene/resources/scene_format_text.cpp:494.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:153.
ERROR: _load: Failed loading resource: res://play/play.tscn
   At: core/io/resource_loader.cpp:190.
ERROR: start: Failed loading scene: res://play/play.tscn
   At: main/main.cpp:1678.
```
it seems that `ParticlesMaterial` is a part of 3d now.

**Steps to reproduce:**
1. compiled templates with `disable_3d=yes` option.
2. put `Particles2D` and make `ParticlesMaterial` for it
3. export and run game.

**Minimal reproduction project:**

**Comment by chanon** [comment]
So disable_3d is an option? I can use it to disable all 3d support? 
If so, then that's nice. However, I don't see it documented anywhere.

**Comment by akien-mga** [comment]
```
$ scons --help
[...]
disable_3d: Disable 3D nodes for a smaller executable (yes|no)
    default: False
    actual: False
[...]
```
