### ISSUE TITLE
Critical info missing from TreeItem.set_custom_draw documentation

### ISSUE THREAD

**Issue by squished-01** [godotengine/godot#21374]
**Godot version:**

3.0.5

**Issue description:**

The documentation for TreeItem.set_custom_draw should specify that the custom draw function should accept two arguments, (parent_object, draw_rect) or it won't get called.

**Comment by akien-mga** [comment]
Relevant code: https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L1332
