### ISSUE TITLE
change_scene() function does not support 3D games.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#2137]
Download this file, play it, and press 'enter' to switch the scene.
http://www.mediafire.com/download/dmvwzu4npwxqm89/Test.zip

In my game, I have to use the old way to change scenes because the function has no support for 3D games at all (2D graphics load in fine). What you'll see is that instead of seeing the new scene with two cubes, you get something grey and empty.

I can see this virtually eliminating the chance of Godot 1.1 making any headway in getting 3D-centric users, a fix in my view should be high priority.

Confirmed on a Win7 64 bit machine with an ATI 7xxx GPU, 16 gigs of RAM and an i7 processor. The latest drivers are installed.

Thanks.

**Comment by akien-mga** [comment]
Can you still reproduce this issue in the current master branch?

**Comment by vnen** [comment]
This is related to cameras. No camera is set after `change_scene()`. If you add a script to the second scene that calls `make_current()` in one camera it will work.

Maybe `change_scene()` should set a default camera as current, the same way the first scene does when loaded.
