### ISSUE TITLE
GDScript circular const references.

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#21372]
**Godot version:**
f123694b4e5ac52bb82b3a2e3cbd6d36db1d0c9c

**OS/device including version:**
Windows 10

**Issue description:**
It used to be possible in GDScript to handle circular const references, but with some recent changes, it no longer works.

**Steps to reproduce:**
Simply create to script files which contain const references to one another. See the included example.

**Minimal reproduction project:**
[godot_circular_reference_example.zip](https://github.com/godotengine/godot/files/2318685/godot_circular_reference_example.zip)

**Comment by akien-mga** [comment]
CC @vnen

**Comment by akien-mga** [comment]
Same issue as #26119. @reduz says that this is by design and that it should not have worked in 3.0 in the first place, so it's an expected compat breakage.
