### ISSUE TITLE
New TileSet Editor Navigation regions are not placed relative to the selected tile's location.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#21398]
**Godot version:**
3.1 dev f72f744

**OS/device including version:**
Windows 10 64bit

**Issue description:**
I added New Single Tiles to a spritesheet. Everything looked fine. I did the same for collisions. Fine. Did navigation, and the region is always rendered in the top-left corner. Not even sure if the points are actually at the right locations.

![tileset_editor_navigation_bug](https://user-images.githubusercontent.com/16217563/44615159-44a21100-a7f8-11e8-9db8-6912030e1e18.png)

**Steps to reproduce:**
1. Make TileSet resource.
2. Open TileSet editor.
3. Load a texture into it.
4. Assign a region to it.
5. Assign a navigation region to the regioned tile.

**Minimal reproduction project:**
[sample.zip](https://github.com/godotengine/godot/files/2320353/sample.zip)

level_a.tscn, in the TileSet I loaded into the TileMap node.

**Comment by paulloz** [comment]
Same is happening with occlusions.  
![godot windows tools 64_2018-08-25_11-28-39](https://user-images.githubusercontent.com/437025/44616930-06d5d480-a85a-11e8-8cd1-96a5956f230c.png)

**Comment by MarianoGnu** [comment]
hum i thought this was working, maybe got broken with the rebase. Can you check if this happens to you with collision shapes too?

**Comment by willnationsdev** [comment]
@MarianoGnu As mentioned, this problem doesn't seem to happen with the collision shapes (at least, in my testing with New Single Tile creations).

**Comment by MarianoGnu** [comment]
how about autotiles?

**Comment by willnationsdev** [comment]
I haven't tried (don't actually know how those work, aside from the fact that they use a bitmask/priority. Just haven't tried them yet).

**Comment by paulloz** [comment]
Autotiles seem fine:
![godot windows tools 64_2018-08-26_11-52-20](https://user-images.githubusercontent.com/437025/44626986-9052d880-a926-11e8-951d-0d8746dd8648.png)
![godot windows tools 64_2018-08-26_11-52-28](https://user-images.githubusercontent.com/437025/44626987-93e65f80-a926-11e8-8962-9c5b747f306b.png)
