### ISSUE TITLE
Material turns dark

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#21391]
**Godot version:**
Godot master commit f72f74486d3f07b2be0c6480c6c0d34edd47794f

**OS/device including version:**
Windows

**Issue description:**
See image :)
![image](https://user-images.githubusercontent.com/1945449/44613691-98454680-a85a-11e8-877c-e8412ff1497d.png)

This only seems to happen when you use repeating textures that are scaled down enough. I've reproduced it both with spatial materials and shader materials. My first thought was that the creation of the mipmaps had an issue but turning mipmapping off doesn't seem to resolve this. Could still be related though seeing the recent importer changes.

**Steps to reproduce:**
1) load up an HRDI sky map (don't know if this has an influence here but I'm using a panaramic sky)
2) Create a mesh instance
3) Create a plane mesh and make it nice and large
4) Create a material
5) Load a texture for the ALBEDO color
6) Set the UV scale high enough to get a good repeat of the texture

**Minimal reproduction project:**
My vehicle demo shows the issue well:
https://github.com/BastiaanOlij/vehicle-demo
Seeing this was working fine a few weeks ago I figure this issue was recently introduced.

**Comment by capnm** [comment]
At least I can't reproduce it on current tip f72f74486d3f07b2be0c6480c6c0d34edd47794f,
even your unmodified demo looks like you'd probably expect it:

![image](https://user-images.githubusercontent.com/4047289/44616293-6aa5d080-a84d-11e8-8eaa-dc6bca12f7ac.png)

However, it has a lot of spam in the log:

```
** Debug Process Started **
 core/image.cpp:1446 - Index p_width - 1=-1 out of size (MAX_WIDTH=16384)
OpenGL ES 3.0 Renderer: AMD Radeon HD 7700 Series (CAPE VERDE / DRM 3.26.0 / 4.18.1-041801-generic, LLVM 6.0.0)

...

WARNING: get_friction: The method get_friction has been deprecated and will be removed in the future, use physical material
   At: scene/3d/physics_body.cpp:634.
WARNING: get_bounce: The method get_bounce has been deprecated and will be removed in the future, use physical material
   At: scene/3d/physics_body.cpp:655.
ERROR: multimesh_instance_set_color: Condition ' multimesh->color_format == VisualServer::MULTIMESH_COLOR_NONE ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:4233.
ERROR: multimesh_instance_set_color: Condition ' multimesh->color_format == VisualServer::MULTIMESH_COLOR_NONE ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:4233.

0:00:00:0334 - Too many errors! 1197 errors were dropped.

…

WARNING: set_friction: The method set_friction has been deprecated and will be removed in the future, use physical material
   At: scene/3d/physics_body.cpp:186.
WARNING: set_bounce: The method set_bounce has been deprecated and will be removed in the future, use physical material
   At: scene/3d/physics_body.cpp:213.
WARNING: set_friction: The method set_friction has been deprecated and will be removed in the future, use physical material
   At: scene/3d/physics_body.cpp:622.
WARNING: set_bounce: The method set_bounce has been deprecated and will be removed in the future, use physical material
   At: scene/3d/physics_body.cpp:644.
WARNING: load: Loaded resource as image file, this will not work on export: 'res://icon.png'. Instead, import the image file as an Image resource and load it normally as a resource.
   At: core/image.cpp:1731.

**Comment by elasota** [comment]
I'll take a look at this, it might be related to the BPTC additions.

I was running into this problem while working on it, and it was caused by generate_mipmaps quietly failing if it can't mipmap the input format, but I updated mipmapping to support all HDRI input formats, which I thought fixed this, but maybe not.

**Comment by elasota** [comment]
I think this regressed due to mipmap generation being implemented for HDR textures, combined with some old bugs causing the last mipmap levels to contain uninitialized data.

It would still happen without that, but it would be harder to see because the working sky would make it harder to tell that the last mipmap of the floor texture was corrupted.  Now both are corrupted though.

**Comment by BastiaanOlij** [comment]
@capnm , @elasota yes it is indeed caused by an issue around mipmapping. After talking about it with Reduz yesterday on IRC it seems that mipmapping is always applied regardless of the setting when you use compressed textures. So with a few more setting changes and fully turning mipmapping the issue goes away (and things look very ugly so its not a fix). 

I'll try out that fix :)
