### ISSUE TITLE
New TileSet Editor initialization doesn't properly handle "no current tile" cases.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#21397]
**Godot version:**
3.1 dev f72f744

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Numerous errors appear when opening the TileSet Editor from the TileMap's Inspector. As far as I can tell, they are all the result of calling various methods that refer to get_current_tile(), passing its return value into other methods, when the current_tile's index doesn't actually exist because no tiles have been defined yet. These are all triggering during the `_on_texture_list_selected(-1)` call on [line 2082](https://github.com/godotengine/godot/blob/master/editor/plugins/tile_set_editor_plugin.cpp#L2082).

Example occurrences...

- [line 2129](https://github.com/godotengine/godot/blob/master/editor/plugins/tile_set_editor_plugin.cpp#L2129).
- which defaults to true, leading to 2134's `select_coord(...)` which jumps to [1959](https://github.com/godotengine/godot/blob/master/editor/plugins/tile_set_editor_plugin.cpp#L1959) that has the same problem.

There are many more of the same nature.

![tileset_editor_init_bugs](https://user-images.githubusercontent.com/16217563/44615019-5df58e00-a7f5-11e8-8777-e757a8a62a7b.png)

**Steps to reproduce:**
1. Create scene with TileMap.
2. Create new TileSet resource for the tileset property. Click on it.
3. Click the "Open Editor" button.
4. Check error log.

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by MarianoGnu** [comment]
i was hoping noone complained about this :rofl:
