### ISSUE TITLE
Tileset Editor: snap constrain collisions to first cell on large tiles

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#21402]
**Godot version:** f72f74486d3f07b2be0c6480c6c0d34edd47794f

**OS/device including version:** Win10

**Issue description:**
When trying to draw a collision shape in a large tile (whose width and/or height > one cell) with the snap option enabled, it seems it can only be drawn in its first (upper left) cell.  
It'll be easier to explain with a gif:  
![2018-08-25_11-00-27](https://user-images.githubusercontent.com/437025/44616772-587c6000-a856-11e8-9838-cc486d20011e.gif)  
You can see that even if my mouse is trying do draw outside of the cell (but inside the tile), the shape is constrained in the cell.

**Steps to reproduce:**
* Create and edit a new *Tileset*
* Add a new *Single Tile* taking more than one cell
* Enable *Snap*
* Try do draw a *Collision Shape*

**Comment by akien-mga** [comment]
CC @MarianoGnu
