### ISSUE TITLE
Jittery physics (object does not come to rest) (regression from 912131f)

### ISSUE THREAD

**Issue by SneakyMax** [godotengine/godot#21409]
**Godot version:**

`master` (e.g. 8c435a343e9739f30cb2e347df95835c91c1ff1a)
Problem introduced in: 912131fe03d7f82126463fc62cc0a166ed5434f4

**OS/device including version:**

Windows 10 - x64

**Issue description:**

I have my camera attached to a Character type RigidBody, with a Capsule CollisionShape as the collider. Before 912131fe03d7f82126463fc62cc0a166ed5434f4, the physics are stable and the world does not move. After 912131fe03d7f82126463fc62cc0a166ed5434f4, when standing still, the player's RigidBody vibrates up and down, and does not come to rest.

Good (912131fe03d7f82126463fc62cc0a166ed5434f4 reverted):

![stable](https://user-images.githubusercontent.com/342540/44619633-f7955d80-a83e-11e8-98f0-6e2cc2b89899.gif)

Bad (current master):

![unstable](https://user-images.githubusercontent.com/342540/44619636-03811f80-a83f-11e8-91c0-d55d829d98a7.gif)

It obviously has something to do with the collision margins, but I am not familiar enough with Bullet to instantly know what's going on. I'll look into it some more when I have time.

**Steps to reproduce:**

Create a scene with a Character RigidBody and a capsule shape, and attach the camera to it. Place the body on another static body. Watch other static bodies (or just view the player's Y axis)

**Minimal reproduction project:**

Can provide one if other people can't reproduce it.

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by SneakyMax** [comment]
Sure thing. Reproducing this in a fresh projected revealed that this happens only with `ConcavePolygonShape`.

[jitter-example-project.zip](https://github.com/godotengine/godot/files/2321715/jitter-example-project.zip)

**Comment by SneakyMax** [comment]
Actually this is an even better example, just a cube:

[jitter-example-project.zip](https://github.com/godotengine/godot/files/2321725/jitter-example-project.zip)

**Comment by Ace-Dragon** [comment]
Working on my project in a build done as of yesterday, I come to conclude if exposing the collision margin is just way more trouble than it is worth. This bug (which makes 3D physics nearly unusable) is a much bigger issue in 3D games than any potential issue the commit was supposed to make solvable.

**Comment by reduz** [comment]
Can you compare to Godot physics by the way? I saw this in Bullet but not Godot

**Comment by AndreaCatania** [comment]
I'm checking this problem here: #21341
