### ISSUE TITLE
Godot exits trying to load a scene

### ISSUE THREAD

**Issue by imekon** [godotengine/godot#21403]
**Godot version:**

V3.0.6 mono
V3.0.6 standard
V3.0.5 standard
V3.0.4 standard

**OS/device including version:**

Windows 10

**Issue description:**

I tried to load a scene called "core", there was a brief pause, then Godot exits

**Steps to reproduce:**
Load the project attached and try to open scene "Core" in scenes

**Minimal reproduction project:**

[reactor3.zip](https://github.com/godotengine/godot/files/2320548/reactor3.zip)

**Comment by imekon** [comment]
If I remove the collision shapes, I can load the scene. I created the collision shapes by creating the meshes, then selecting Mesh -> Create Convex Static Body. I then move the collision shape to the parent kinematic body and delete the unwanted static body.

I'm going to try creating the collision shape manually and see if that works.

**Comment by Noshyaar** [comment]
I can open it. Godot 3.0.6
![image](https://user-images.githubusercontent.com/26753932/44617319-6a77f600-a88a-11e8-8893-af2bf265f336.png)
Some error messages:
```
ERROR: build: Condition ' !F ' is true. Continuing..:
   At: core/math/quick_hull.cpp:399.
ERROR: build: Condition ' O == __null ' is true. Continuing..:
   At: core/math/quick_hull.cpp:403.
```

**Comment by AlexHolly** [comment]
Is it the same? https://github.com/godotengine/godot/pull/21202

**Comment by imekon** [comment]
Tried with an unofficial nightly build (v3.1.dev.calinou.5df9109), works fine loading scene. So, I'm guessing it's the same and is fixed.
