### ISSUE TITLE
Crash deleting GridMap from project panel.

### ISSUE THREAD

**Issue by PeaceSells50** [godotengine/godot#2140]
Windows 8.1. Surface 2 Pro. x64.

Callstack:
>	godot.windows.tools.64.exe!Ref<MeshLibrary>::ref(const Ref<MeshLibrary> & p_from) Line 84	C++
 	godot.windows.tools.64.exe!Ref<MeshLibrary>::Ref<MeshLibrary>(const Ref<MeshLibrary> & p_from) Line 224	C++
 	godot.windows.tools.64.exe!GridMap::get_theme() Line 277	C++
 	godot.windows.tools.64.exe!GridMapEditor::do_input_action(Camera * p_camera, const Vector2 & p_point, bool p_click) Line 288	C++
 	godot.windows.tools.64.exe!GridMapEditor::forward_spatial_input_event(Camera * p_camera, const InputEvent & p_event) Line 641	C++
 	godot.windows.tools.64.exe!GridMapEditorPlugin::forward_spatial_input_event(Camera * p_camera, const InputEvent & p_event) Line 238	C++
 	godot.windows.tools.64.exe!SpatialEditorViewport::_sinput(const InputEvent & p_event) Line 695	C++
 	godot.windows.tools.64.exe!MethodBind1<SpatialEditorViewport,InputEvent const &>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 681	C++
 	godot.windows.tools.64.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 891	C++
 	godot.windows.tools.64.exe!Object::call(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 768	C++
 	godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1182	C++
 	godot.windows.tools.64.exe!Control::_window_call_input(Control * p_control, const InputEvent & p_input) Line 925	C++
 	godot.windows.tools.64.exe!Control::_window_input_event(InputEvent p_event) Line 1224	C++
 	godot.windows.tools.64.exe!Control::_gui_input(const InputEvent & p_event) Line 340	C++
 	godot.windows.tools.64.exe!MethodBind1<Control,InputEvent const &>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 681	C++
 	godot.windows.tools.64.exe!Object::call_multilevel(const StringName & p_method, const Variant * * p_args, int p_argcount) Line 619	C++
 	godot.windows.tools.64.exe!Object::call_multilevel(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 831	C++
 	godot.windows.tools.64.exe!SceneTree::call_group(unsigned int p_call_flags, const StringName & p_group, const StringName & p_function, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 192	C++
 	godot.windows.tools.64.exe!Viewport::input(const InputEvent & p_event) Line 1195	C++
 	godot.windows.tools.64.exe!Viewport::_vp_input(const InputEvent & p_ev) Line 1163	C++
 	godot.windows.tools.64.exe!MethodBind1<Viewport,InputEvent const &>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 681	C++
 	godot.windows.tools.64.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 891	C++
 	godot.windows.tools.64.exe!Object::call(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 768	C++
 	godot.windows.tools.64.exe!SceneTree::call_group(unsigned int p_call_flags, const StringName & p_group, const StringName & p_function, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 210	C++
 	godot.windows.tools.64.exe!SceneTree::input_event(const InputEvent & p_event) Line 425	C++
 	godot.windows.tools.64.exe!InputDefault::parse_input_event(const InputEvent & p_event) Line 293	C++
 	godot.windows.tools.64.exe!OS_Windows::WndProc(HWND__ * hWnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 417	C++
 	godot.windows.tools.64.exe!WndProc(HWND__ * hWnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 693	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for user32.dll]	
 	godot.windows.tools.64.exe!OS_Windows::process_events() Line 1938	C++
 	godot.windows.tools.64.exe!OS_Windows::run() Line 2239	C++
 	godot.windows.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 146	C++
 	godot.windows.tools.64.exe!main(int _argc, char * * _argv) Line 172	C++
 	[External Code]

**Comment by PeaceSells50** [comment]
I think there could be a pull request for this bug.  "Godot crash when deleting gridmap #2102"

**Comment by akien-mga** [comment]
Closing as duplicate from #2102, feel free to reopen if the PR did not fix your particular bug.
