### ISSUE TITLE
TabContainer children can overflow on tab switch (e.g. Export and Project dialogs)

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#21404]
**Godot version:**
3.1.dev-1

**OS/device including version:**
Arch Linux

**Issue description:**
Export manager has too long textboxes: https://i.imgur.com/HvjGhzF.png

**Steps to reproduce:**
Open export window and enter resources menu.

_Bugsquad edit:_ 
![hvjghzf](https://user-images.githubusercontent.com/6093119/44621086-4fb07c00-a8a0-11e8-8c65-24e20a869e9c.png)

**Comment by vnen** [comment]
FYI you can attach images to your issue directly, no need to use an external provider.

**Comment by reduz** [comment]
No idea why this is going on, but export Window is here:
https://github.com/godotengine/godot/blob/master/editor/project_export.cpp

**Comment by toger5** [comment]
I just checked, and i cannot reproduce this on my machine (Linux official 3.0.6)

**Comment by szenasitibi** [comment]
I was able to reproduce the bug in the export manager once, with polish language, but after dragging the right side of the window, it snapped back to normal, and ever since, even with restarting the application or making a new project or switching between languages, it's been working correctly.

**Comment by toger5** [comment]
maybe it's an issue with some cached value in the config?
you could still look through the file posted by @reduz. Ill notify you when I'm able to reproduce and under which circumstances.

**Comment by szenasitibi** [comment]
Alright, I'm gonna go do that.

**Comment by szenasitibi** [comment]
I have found a reliable way to reproduce the bug: increase the size of the string on this line in project_export.cpp (around line 962)

`resources_vb->add_margin_child(TTR("Filters to export non-resource files (comma separated, e.g: *.json, *.txt)"), include_filters);`

If you increase it with at least a couple of characters, the box will be messed up, but will adjust back if you resize the window, or exit from the window and reopen it. As @nikibobi mentioned this must be a more general issue, I think too.

**Comment by toger5** [comment]
could be the min_size function that is broken
