### ISSUE TITLE
 Fonts and icons on interface are super tiny on load

### ISSUE THREAD

**Issue by diegodelarocha** [godotengine/godot#21416]
**Godot version:**

Godot_v3.0.6-stable_mono_osx.fat

**OS/device including version:**

iMac (Retina 5K, 27-inch, Late 2014)
4 GHz Intel Core i7
32 GB 1600 MHz DDR3
AMD Radeon R9 M295X 4096 MB

External monitor plugged (Cintiq 21WX)

Display settings on System Preferences set to looks like 2048 * 1152
**Issue description:**

Fonts and icons on interface are super tiny on load.

I was able to fix it by going on Editor > Editor Settings>Interface> Editor> Hidpi MOde Mid + Main Font Size 24

Then restart Godot, and it works. 

But this settings should be a default, since it's way too tiny

**Steps to reproduce:**
Just run Godot at the begninning

**Minimal reproduction project:**

**Comment by Calinou** [comment]
It's possible that automatic hiDPI detection fails since there is an external monitor connected (which may or may not be hiDPI).

**Comment by bruvzg** [comment]
Thats because your DPI is `√((2048×2)²+(1152×2)²2) / 27 = 174.06` and for unknown reasons Godot only enables editor UI scaling and `DPI ≥ 192`, see [editor/editor_node.cpp#L4809](https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L4809).

**Comment by Calinou** [comment]
@bruvzg I think automatic editor scaling was implemented this way because OS APIs don't always return reliable values for monitor DPI. (That said, we should obey the OS scaling setting instead of relying on monitor DPI.)

**Comment by bruvzg** [comment]
I'm now sure how DPI is handled on Windows and X11, but on macOS current implementation of `OS::get_screen_dpi` returns monitor physical DPI (X11 seems to use physical DPI as well, Windows likely is not).

e.g: 21'' 4K display in `4096x2160` mode and in `2048x1080 (HiDPI)` mode - `OS::get_screen_dpi` return same value (`220`) for both modes

There's additional private `OS_OSX::_display_scale` function which returns `1.0` for `4096x2160` mode and `2.0` for `2048x1080 (HiDPI)` mode.

It's probably better to expose it and use for UI scaling directly.

**Comment by akien-mga** [comment]
Is the issue still reproducible with the latest 3.2 build?

**Comment by TheCleric** [comment]
3.2_beta5 resolves this issue for me on my MacBook Pro running OS X 10.15.2

**Comment by akien-mga** [comment]
Awesome, thanks for testing!
