### ISSUE TITLE
Build products compiled with an automatically-detected MSVC do not contain an architecture in the name

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#21418]
**Godot version:** Git https://github.com/godotengine/godot/commit/8c435a343e9739f30cb2e347df95835c91c1ff1a

**OS/device including version:** Windows 10, Visual Studio 2017

**Issue description:** Build products compiled with an automatically-detected MSVC installation do not contain an architecture in their file name. For instance, an editor binary will be named `godot.windows.opt.tools.exe` instead of `godot.windows.opt.tools.64.exe`.

This causes the build to fail when compiling a 32-bit binary after compiling the same target in 64-bit (or vice versa), as the linker will attempt to reuse files built for an incompatible architecture.

**Steps to reproduce:** With MSVC 2017 installed, compile Godot twice using the following commands from a *generic* command prompt (cmd.exe or PowerShell):

```
scons p=windows bits=64
scons p=windows bits=32
```

**Comment by akien-mga** [comment]
Closing as superseded by #24030 which is the better solution. I prefer not to break compatibility with build scripts until then, especially since most users don't build both MSVC and MinGW concurrently.
