### ISSUE TITLE
KDE Neon freezing up beyond recovery when pressing play in project editor

### ISSUE THREAD

**Issue by KevinStirling** [godotengine/godot#21414]
**Godot version:**
v3.0.6.stable.official.8314054

**OS/device including version:**
KDE Neon 5.13 stable
- Kernal: x86_64 Linux 4.15.0-33-generic

Intel Core i7 4790k

NVIDIA GTX 970
- Driver : nvidia-384 - distro non-free recommended

**Issue description:**
Occasionally, Plasma will freeze up completely after hitting the play button in the project editor. I can only move the mouse, nothing responds to clicks, any video / audio stops playing. After waiting about 10 minutes eventually I just press the power button on the computer and let the computer go through the improper shutdown recovery process. 

I'm doing this on a pretty fresh install of KDE Neon, only installed 2 days ago and have a very basic configuration with just a few development tools and chat clients installed, I really can't think of anything that could be interfering. While it happened, i had Konsole, and Firefox with a tutorial video playing, and thats all I had opened.

**Steps to reproduce:**
Open a project, press play,  KDE Plasma has a chance of freezing up beyond recovery. Over the course of 1 hour, its happened to me about 3 times.

**Minimal reproduction project:**
You can reproduce this in any project, it happened in a demo project i downloaded from the website and it happened to a brand new project i just created about 20 minutes ago.

**Comment by Calinou** [comment]
Does this occur with other 3D applications/games?

**Comment by KevinStirling** [comment]
So far I've tested it with team fortress 2 installed from steam, seems to be working just fine for that game. Going to see of I can inspect plasma logs to see if that's any help.

**Comment by eon-s** [comment]
Anything on the system logs?

**Comment by KevinStirling** [comment]
I wasn't able to see anything in the system logs using  `journalctl -f | grep --line-buffered kde
` maybe because the screen stops updating before it can log anything. Or it just doesn't seem to log anything at all. However, I changed my display settings to not allow applications to block compositing... and it seems to have fixed it? I'm still testing it because I almost don't believe it to be true. I suppose I'll update this thread again if I'm able to capture the issue.

**Comment by KevinStirling** [comment]
Starting to suspect its a problem with that specific driver version. The driver I was using before was the one that was bundled in the Ubuntu auto-install for pcie devices, and i have since upgraded to nvidia-390 proprietary driver and it seems to be a lot more reliable and smoother. Have not had any crashes since updating!
