### ISSUE TITLE
Problem with file: grid_map_editor_plugin.cpp Ln: 307

### ISSUE THREAD

**Issue by PeaceSells50** [godotengine/godot#2142]
In this line of code it uses a segment of length 500.0. I created a default scene, with a default gridmap using tiles from the Platformer demo. And the distance far exceeded 500. Had to change to greater than 3000 before the segment finally intersected the plane. Unsure how to fix this any other way.

**Comment by akien-mga** [comment]
I believe you fixed this yourself in a009fad?
