### ISSUE TITLE
Skeleton.cpp transform is redundant I think...

### ISSUE THREAD

**Issue by pgruenbacher** [godotengine/godot#21424]
https://github.com/godotengine/godot/blob/8c435a343e9739f30cb2e347df95835c91c1ff1a/scene/3d/skeleton.cpp#L226

I'm pretty sure a transform * (other_transform * transform^T) just leads to == other_transform...

	var t = Transform()
	t = t.scaled(Vector3(1,3,4))
	t = t.translated(Vector3(5,1,0))
	t = t.rotated(Vector3(1,0,0), 5)
	print("T", t)
	print("T", get_global_transform() * (t*get_global_transform().affine_inverse()))

Output:

     T1, 0, 0, 0, 0.850987, 3.835697, 0, -2.876773, 1.134649 - 5, 0.850987, -2.876773
     T1, 0, 0, 0, 0.850987, 3.835697, 0, -2.876773, 1.134649 - 5, 0.850987, -2.876773

**Comment by akien-mga** [comment]
That code was added in 448b58ba4, CC @reduz.

**Comment by pgruenbacher** [comment]
code is still in master.

**Comment by tagcup** [comment]
That's how you make a change of basis. Example: Z(-90).X(x).Z(90) gives Y(x) since X rotated around Z by 90 degrees is Y. Here Y(x) is a rotation around Y by x etc.

**Comment by pgruenbacher** [comment]
yea ok. I'll make a comment PR to clarify that in the code then.

**Comment by tagcup** [comment]
Why? That'd be similar to adding a comment to all lines where a vector is rotated using a transform R.v

That's pretty much basic linear algebra, that's how you rotate a matrix

**Comment by pgruenbacher** [comment]
oh sorry I misread...
i read the code as `global_transform * (global_transform * inverse_global_transform)`
it's actually `global_transform * (bone_transform * inverse_global_transform)` 

very much my bad.
