### ISSUE TITLE
More CPU info methods like OS.get_processor_count ( )

### ISSUE THREAD

**Issue by marcelofg55** [godotengine/godot#21427]
This is not an Issue but more a discussion about if more methods like OS.get_processor_count ( ) are desired.
There is already OS.get_processor_count ( ) but we could also have:

- OS.get_processor_vendor_name()
- OS.get_processor_model_name()
- OS.get_processor_speed()
- OS.get_processor_bits() (suggested by LikeLakers2)

Alternatively we could have just one function instead, OS.get_processor_info() that would return all this information in a Dictionary.

I can implement these myself but I want to know first if this methods are desired or not.
These methods can be used to auto-detect performance settings for the current user.

**Comment by marcelofg55** [comment]
@akien-mga any thoughts on this?

**Comment by Calinou** [comment]
> If I could add one to the pile, how about a function that returns whether the processor is 32-bit or 64-bit?

This is already possible using the `32` and `64` [feature tags](http://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html).

**Comment by LikeLakers2** [comment]
> This is already possible by checking for the `32` and `64` [feature tags](http://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html).

Yeaaaah but that's for the build of Godot. Having the `32` feature tag doesn't necessarily mean Godot is running on a 32-bit CPU, y'know? :P

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1660, as feature proposals are now tracked on the Godot prooposals repository.
