### ISSUE TITLE
"Selecting" multiple exported script variables at the same time is possible

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#21438]
**Godot version:**
3.1.dev-1

**OS/device including version:**
Arch Linux

**Issue description:**
Multiple node properties were selected at the same time. Only one should be possible (?)

**Steps to reproduce:**
Create a new node script with two or more exported variables with the same names. Every variable with the same name will beee highlighted in the inspector.
![imgur-2018_08_26-13 40 20](https://user-images.githubusercontent.com/15695377/44627864-c055a800-a935-11e8-9f1d-21fefa6b28b3.png)

It is also possible to select them again after focus loss, by pressing shift and selecting all variables with the same name.

**Minimal reproduction project:**
Not possible, since variables need to be newly created.

**Comment by KoBeWi** [comment]
It's not impossible to create multiple variables with the same name anymore. It throws parsing error and the variables don't appear in the inspector due to error.
