### ISSUE TITLE
Buttons in GridContainer do not grab focus using grab_focus() Mac OSX 10.13

### ISSUE THREAD

**Issue by stonekase** [godotengine/godot#21434]
@reduz #
**Godot version:**
Godot 3.1 dev

**OS/device including version:**
Mac OSX 10.13 ,  NVIDIA GT 750M 

**Issue description:**
Buttons in a GridContainer does not grab focus when grab_focus() is used but works 
in horizontalContainer/verticalContainer

**Steps to reproduce:**
put some buttons in a gridContainer and call grab_focus() on the button from the root control node GDScript _on_ready() function

**Minimal reproduction project:**
<img width="1121" alt="screen shot 2018-08-26 at 11 49 48 am" src="https://user-images.githubusercontent.com/5037778/44627552-c0e74200-a927-11e8-8fbe-eb0bf245e11b.png">

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Often, you need to use `call_deferred("grab_focus")` instead of `grab_focus()`. See https://github.com/godotengine/godot/pull/38679.

**Comment by KoBeWi** [comment]
No answer from the OP so closing. Judging from the above comment, this is not a GridContainer bug, but a common issue with `grab_focus()`.
