### ISSUE TITLE
Strange behavior with Camera2D and GodotPhysics in recent master

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#21448]
**Godot version:**

5df9109

**Issue description:**
See image.  Interactions with KinematicBody2D and StaticBody2D no longer happen properly.  Interactions behave normally again if Camera2D is static relative to viewport or removed entirely.  The bug doesn't occur in faa49c1, so I think it had to be introduced within the last week.
![asdfd](https://user-images.githubusercontent.com/1023003/44630379-0143c180-a922-11e8-8f20-063f1652dd15.gif)

**Minimal reproduction project:**
[MinimalCamBug.zip](https://github.com/godotengine/godot/files/2321664/MinimalCamBug.zip)

Minimal project doesn't have the same Camera2D settings as the screenshot;  no filtering is used, which may or may not be related to the uncontrolled panning observed there.

**Comment by davidpwbrown** [comment]
Confirm same issue in current master that wasn't present previously.
Static camera2d = no problem
camera2d following sprite = no collisions detected between area2ds with collision shapes.

**Comment by nobuyukinyuu** [comment]
Confirmed fixed in db55d8a.  Probably a dupe of #21289.  Closing.
