### ISSUE TITLE
Out of Bounds Selection on Failure to Create Script

### ISSUE THREAD

**Issue by TheBritain** [godotengine/godot#21447]
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10 GTX770 AMD FX8350

**Issue description:**
When creating a script, if you select a directory and then fail to create the script, but instead select somewhere else like the minimize button, the script creation prompt will disappear and generate an "ERROR: _select_ray: Bug? at editor/plugins/spatial_editor_plugin.cpp:394", the editor can not be minimized and some functionality is lost until either the program is restarted or the window loses focus.

**Steps to reproduce:**
See above.

**Minimal reproduction project:**
Simple enough to not need a project.

**Comment by JFonS** [comment]
@TheBritain I'm not sure how to reproduce your error. Is it just minimizing the window while the ceeate script dialog is open? 

It's not clear to me what "fail to create the script" means.

**Comment by TheBritain** [comment]
Apologies, to clarify I meant, when you don't create the script. As in you do not click "Create" nor close the menu, and you click somewhere else.
