### ISSUE TITLE
Exported values - steps do not work as expected

### ISSUE THREAD

**Issue by Wiadomy** [godotengine/godot#21441]
**Godot version:**
3.1.dev-1

**OS/device including version:**
Arch Linux

**Issue description:**
Note explaining value step and slider step:
![imgur-2018_08_26-13 54 59](https://user-images.githubusercontent.com/15695377/44627962-b339b880-a937-11e8-9dcf-44c99241692f.png)

Step digits are truncated if digits > 1. Examples:
1. `export(float, EXP, 100, 300, 200) var test1` real value step = 20 **slider step** = 1
2. `export(float, EXP, 100, 300, 1200) var test2` real value step = 120 **slider step** = 1
3. `export(float, EXP, 100, 300, 50) var test3` real value step = 5 **slider step** = 1
4. `export(float, EXP, 100, 300, 8) var test4` real value step = 8 (correct) **slider step** = 1

Example image to **1**:
![imgur-2018_08_26-13 05 11](https://user-images.githubusercontent.com/15695377/44627560-4bcc3a80-a930-11e8-8b47-abec1ede7ed0.png)

It shouldn't be possible to get such value via value scrolling.
The only values possible should be 100 and 300.

**There's also issue with changing values via slider -** I'm not sure if it is intended but it always changes only by 1 (even if steps are larger).
If step value is with a comma (0.1, 0.2, 0.3), slider has ALWAYS 0.1 step.

Except when there are more zeroes. Example:
1. `export(float, EXP, 100, 110, 0.5) var test1` real value step = 0.1 **slider step** = 0.1
2. `export(float, EXP, 100, 101, 0.0753) var test2` real value step = 0.01 **slider step** = 0.01

**There are even more problems** if we omit EXP in a variable (Sorry, I'm just reading a tutorial, I'm not yet sure what such thing means):
1. `export(float, 100, 300, 200) var test1` real value step = 20 **slider step** = 200 (correct)
2. `export(float, 100, 300, 1200) var test2` real value step = 120 **slider step** = 1200 (correct)
3. `export(float, 100, 300, 50) var test3` real value step = 5 **slider step** = 50 (correct)
4. `export(float, 100, 300, 8) var test4` real value step = 1 **slider step** = 8 (correct)

**If we replace float with int, steps are completely ignored, they're always 1.** (plus there's no slider)

**Steps to reproduce:**
Attach a new script to a node and create export variables as shown above. If you scroll value using value box or slider, the values are changed incorrectly.

**Minimal project:**
[Slider Weird Behaviour.zip](https://github.com/godotengine/godot/files/2321490/Slider.Weird.Behaviour.zip)

**Comment by akien-mga** [comment]
CC @bojidar-bg @vnen

**Comment by vnen** [comment]
This might be an issue with the inspector, there's nothing special in the GDScript part (unless it's not setting the flags right).

**Comment by DualMatrix** [comment]
It seems int does not support step when exporting.
