### ISSUE TITLE
Unable to enter some characters to LineEdit boxes (macOS non-US keyboard layout)

### ISSUE THREAD

**Issue by tko** [godotengine/godot#21440]
**Godot version:**
3.0.6

**OS/device including version:**
macOS High Sierra 10.13.6

**Issue description:**
In Finnish (Swedish, and other) keyboard layout several characters such as `@£$|\{[]}` require the use of `alt/option` key to type, for example `@` is `alt/option`+`2` and `{` is `shift`+`alt/option`+`8`.

These characters can not be typed into LineEdit boxes, seemingly nothing happens. OTOH TextEdit does not have that problem.

**Steps to reproduce:**

0. select Finnish keyboard layout in macOS System Preferences
1. attempt to type `@` to Godot text boxes – that is `alt/option`+`2`

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment]
Related to #4386 (and #4403 but which was apparently fixed by @bruvzg in #10142).

**Comment by bruvzg** [comment]
I can confirm this, `Alt-gr`/`Options`+`?` keys are processed by IME but they have ALT flag set, this probably cause problems with input.

**Comment by bruvzg** [comment]
These keys are discarded at [scene/gui/line_edit.cpp#L505](https://github.com/godotengine/godot/blob/master/scene/gui/line_edit.cpp#L505), removing `!k->get_alt() &&` fixes Alt+gr combos.

Similar code in `text_edit` only checks for command [scene/gui/text_edit.cpp#L3167](https://github.com/godotengine/godot/blob/master/scene/gui/text_edit.cpp#L3167)
