### ISSUE TITLE
AStar doesn't find shortest path

### ISSUE THREAD

**Issue by Maykeye** [godotengine/godot#21445]
**Godot version:**
master as of commit 8c435a343e9739f30cb2e347df95835c91c1ff1a

**Issue description:**
As soon as end node is found by A* it will stop looking for better solution even if there is one.
Issue happens in two forms:

* The end node is an immediate neighbour of the start node
Consider triangle made of 3 nodes A,B,C where all nodes are connected, A-C costs 1000, A-B and B-C computed as 100 each. If we ask AStar to find shortest path from A to C, it will return A->C (costs 1000) instead of cheaper A->B->C. It happens in the first loop
https://github.com/godotengine/godot/blob/8c435a343e9739f30cb2e347df95835c91c1ff1a/core/math/a_star.cpp#L245
It sees that A is connected to C, sets `found_route` and doesn't even consider movements from the node B
* The end node is not an immediate neighbour of the start node. 
Consider triangle ABC with X attached to A. If we to ask shortest path from X to C, it will go X-A-C
In this case at
https://github.com/godotengine/godot/blob/8c435a343e9739f30cb2e347df95835c91c1ff1a/core/math/a_star.cpp#L309
it will see that C is a neghbour of A and once again give up. 

**Expected behaviour**
* AStar should remember current minimum length and continue to work
* If least_cost from all open nodes exceeds last remembered length - return previously found path 

(as a bonus of this approach, we can pass maximum length of desired path, so if no path can be quickly found shorter than N, it cuts loses and doesn't explore literally all nodes of the map)

**Steps to reproduce:**
Click around in demo project. It moves character around the grid, heavily discouraging diagonal movement. Try to move from top left corner to bottom right.
Diagonal movements occur only as a last move. Intermediate moves are not diagonal, as expected.

**Minimal reproduction project:**
[astar_test.zip](https://github.com/godotengine/godot/files/2321535/astar_test.zip)
At start it prints path in in triangle ABC and path in X-ABC as described above and allows to move icon around the grid.

**Comment by akien-mga** [comment]
CC @bojidar-bg

**Comment by DualMatrix** [comment]
I noticed this was the case as well in the navigation code

**Comment by akien-mga** [comment]
Fixed by #21492.
