### ISSUE TITLE
Considerations on WindowDialog design (internal hidden nodes)

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21458]
**Godot version and OS:**
v3.0.5-stable_x11.64, Xubuntu

**Issue description:**
This was quite hard to debug.
So, it looks like WindowDialog and all derived classes have "invisible" children nodes that makes it possible for them to work. Problems arise when you don't know that and you want to delete all children of a _WindowDialog_. On the editor, via the dock, this works fine because you are actually selecting the "visible" nodes manually and you leave the "invisible" ones out of the selection.
However, via _GDScript_, something like:
<code>
       for child in children:
                     child.queue_free()
</code>
will also delete the "invisible" nodes, leading to Godot's crashes.

**Example project:**
The example project has extensive commenting.
[Example project.zip](https://github.com/godotengine/godot/files/2321878/Example.project.zip)

**Considerations:**
Reading the documentation you can guess what's going on, because there are methods that will return the internal nodes. So if this is not considered a bug, I can understand. Still, this design gave me a bit of trouble. And considering that _WindowDialog_ and all derived classes are very likely to contain other stuff, it makes sense that the developer may want to delete all that stuff to start rebuilding their content, however this will lead to some unexpected crashes until you figure out what's going on.

**Comment by akien-mga** [comment]
That would be the same for any complex Node type with children nodes (e.g. SpinBox which has a LineEdit, or most advanced controls like *Dialog or ColorPicker). I'm not sure if there's an easy way around this.

**Comment by girng** [comment]
The problem isn't necessarily hidden nodes, it's the crashing. Doing queue_free on the hidden nodes should not crash. I think isolating the issue deeper is the solution

**Comment by girng** [comment]
> However, via _GDScript_, something like:
> ` for child in children: child.queue_free() `
> will also delete the "invisible" nodes, leading to Godot's crashes.

This should not be happening. I've queue_free'd I don't know how many nodes that have "internal nodes" in my life and they have not caused a crash. Something else is going on, maybe a regression somewhere specific to that Node

Please post example code to reproduce
