### ISSUE TITLE
RigidBody cannot fall over when collider is offset

### ISSUE THREAD

**Issue by SneakyMax** [godotengine/godot#21452]
**Godot version:** 

`master`

**OS/device including version:**

Windows 10 x64

**Issue description:**

When a CollisionShape is offset from the RigidBody, and using Bullet physics, the RigidBody cannot fall over.

Is the center of mass calculated as the position of the RigidBody itself? Is this intentional?

Bullet:

![wobble](https://user-images.githubusercontent.com/342540/44631298-d99f2a00-a91e-11e8-892a-fd9bf6417659.gif)

GodotPhysics:

![wobble-godotphysics](https://user-images.githubusercontent.com/342540/44631300-ddcb4780-a91e-11e8-9334-69b5ede0cb4a.gif)

**Steps to reproduce:**
See reproduction project.

**Minimal reproduction project:**

[fall-example-project.zip](https://github.com/godotengine/godot/files/2321752/fall-example-project.zip)

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by AndreaCatania** [comment]
Yes it's intentional, not a bug

**Comment by SneakyMax** [comment]
Thanks. I'll see if the documentation can be improved, because this was very confusing to figure out,
