### ISSUE TITLE
Particle2D issue when export to android

### ISSUE THREAD

**Issue by homarox** [godotengine/godot#21468]
**Godot version:**
3.0.6

**OS/device including version:**
Samsung devices have Mali GPU

Mali GPU

**Issue description:**

Particle2D do not emit when running on Android devices have Mali GPU.
Check Godot Example first game on Android:
http://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html
issue on Android
https://vimeo.com/286211087

**Comment by KoBeWi** [comment]
In 3.1 you can use CPUParticles, which are supposed to fix compatibility issues like this.
