### ISSUE TITLE
Scripts and assets in sub-directories cause problems

### ISSUE THREAD

**Issue by macramole** [godotengine/godot#2146]
Related to #1808 and #1921 . When exporting the game, and running the exported version, it will throw an error of the asset or script not being found. This can be very frustating if you don't know about this issue.

The workaround for now is just restarting the editor, it seems that when it first load the project the paths are correct.

**Comment by reduz** [comment]
ah, hopefully it will be time to fix this long soon..

**Comment by macramole** [comment]
this is my favorite issue

**Comment by akien-mga** [comment]
IIRC correctly the problem only happens for resources that were created during the current editor's instance?

**Comment by macramole** [comment]
I don't fully understand the question. As I said, restarting the editor fixes the problem. 

Also, I think that if for example you create a Sprite node and set an image to it which is in a nonroot location and then export the game, the exported binary will fail. Again, restarting the editor and exporting will fix the problem.

**Comment by akien-mga** [comment]
Well restarting the editor fixes the problem, but how is the problem created? It just happens sometimes and not others? i.e. what is different between the time where it does not work, and after you have restarted the editor?

**Comment by macramole** [comment]
I guess Godot internally have a list of assets and it's paths that it is
loaded when you load a project. That is working ok. If you add or link a
script or asset later on, I guess Godot want to add this to its list but if
it is in a nonroot location it add it wrong (without the full path). It
will later on use this internal list for the "quick open scene" or for
exporting and it will fail. Since it does a good job when you first load a
project, restarting the editor fixes the bug.

As I stated this is my guess on the problem, I haven't checked out Godot's
source code to assert this.

2015-11-11 13:58 GMT-03:00 Rémi Verschelde <notifications@github.com>:

**Comment by akien-mga** [comment]
Ok that's also how I understand then issue. If resources are placed out of root *during* the editor session, export won't work, but if there has been one or more restart of the editor since the resources were added, it will work.

**Comment by reduz** [comment]
hey btw, is this not fixed already?

**Comment by nunodonato** [comment]
tried it here, could not replicate. everything works fine
(ended up here due to CodeTriage ;)

**Comment by akien-mga** [comment]
Assuming it has been fixed then, thanks for checking :)
