### ISSUE TITLE
Blinking of the editor when it is running in full-screen mode and the game is started or exited

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21475]
**Godot version:**
3.1 5df9109

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
When I try work on editor in full screen mode, any attempt to turn the game on or off resulted in the editor flashing.
I can't record it with OBS Studio because all screen is black.

**Steps to reproduce:**
1. Open editor in full screen (SHIFT + F11)
2. Run game/scene or close it

**Comment by qarmin** [comment]
On master I can still reproduce this with Windows 10 1903 but not with Ubuntu 19.10

**Comment by Calinou** [comment]
This is likely specific to the OS or graphics driver (or both).

**Comment by Torguen** [comment]
The same thing happens to me with my nvidia gt 440

**Comment by raformatico** [comment]
Same thing to me, is there a way finally to fix it?

**Comment by Calinou** [comment]
@raformatico Which OS and graphics card model do you have? Also, are you using the GLES3 or GLES2 renderer?

Does the issue go away if you enable **Update Continuously** in the Editor Settings?

**Comment by raformatico** [comment]
Specs:
- Windows 10 Pro
- Nvidia GTX 1060
- GLES3

There is a change when I activate *Update Continuously*. The flickering continues but it occurs exactly at the moment I launch or stop the game. Without this property active this happens maybe 1 or 2 seconds after I take one of the mentioned actions.

Thank you for the extremely fast answer!

**Comment by viksl** [comment]
It's happening to me too. Win 10, nvidia gtx 1660Ti (latest drivers 452.06, checked the previous ones as well but same problem), both GLES3 and GLES2.

**Comment by johnnygossdev** [comment]
> Does the issue go away if you enable **Update Continuously** in the Editor Settings?

This fixed my issue of flickering footage when using the Godot editor in fullscreen mode in OBS (for tutorials). 

With **Update Continuously** = `false`, this is what the footage looks like. This only affects the footage.

![flickering-2](https://user-images.githubusercontent.com/3285214/101482569-d0e78c00-394e-11eb-9baa-68b9a42850a1.gif)

My specs
- Windows 10 Pro
- Nvidia GTX 1660 Super
- GLES3

I'm glad I could solve the editor flickering, but I also have a second or two of black screen when the project is run or closed. Not so much of an issue as I can edit those frames out of tutorials.

**Comment by Calinou** [comment]
As a workaround, you could also turn the Godot editor into a borderless window using [Borderless Gaming](https://github.com/AndrewMD5/Borderless-Gaming). This way, you won't have to enable **Update Continuously** which greatly increases CPU and GPU usage.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/60665, as this is the same underlying cause.
