### ISSUE TITLE
Add ability to sort filenames in FileSystem Panel by value.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21473]
**Godot version:**
3.1 5df9109

**OS/device including version:**
Windows 10 HD 4600

**Issue description:**
I have some folders with levels which are named like 1,2,3... but level in 10 folder is putted between 1 and 2 instead after 9 

I tried to found option in settings but I can't find it. 

Current sort - checks character by character
![niepos](https://user-images.githubusercontent.com/41945903/44647988-f3ed0c80-a9df-11e8-9568-16c487689780.png)

Better for me sort - first checks the value of the number. It should be sorted also with name before number like "ziemniak7", "ziemniak8", "ziemniak9", "ziemniak10"
![pos](https://user-images.githubusercontent.com/41945903/44648098-47f7f100-a9e0-11e8-9e6e-e4d0ed97489e.png)

**Comment by akien-mga** [comment]
CC @groud since you're working on FileSystem dock UX.

**Comment by PetePete1984** [comment]
The same sorting style happens in the Tile selection dock when working with TileMap / TileSet (although I'd suggest giving tiles proper names and/or zero-padded names at least)

**Comment by groud** [comment]
I have no clue how to do that in a smart manner. If someone wants to create a generic sorting algorithm for that, we could apply it wherever it's needed.

**Comment by PetePete1984** [comment]
Short research later, we're looking for "logical" or "natural" sorting, as described in detail over there:
http://www.davekoelle.com/alphanum.html

**Comment by groud** [comment]
> Short research later, we're looking for "logical" or "natural" sorting, as described in detail over there:
http://www.davekoelle.com/alphanum.html

Indeed, it looks like a good solution. I'll have a look to how to implement that.

**Comment by groud** [comment]
Note to myself: apparently this file sorting is already implemented in the engine. I could use `myvector.custom_sort<NaturalNoCaseComparator>()` to sort the files.
