### ISSUE TITLE
RichTextLabel auto-wrapping on chinese

### ISSUE THREAD

**Issue by ganlub** [godotengine/godot#21482]
**Godot version:**
v3.0.6

**OS/device including version:**
Archlinux

**Issue description:**
I'm getting different behaviors on Label and RichTextLabel regarding auto-wrapping and spacing.
![image](https://user-images.githubusercontent.com/1272617/44660674-b2248c00-aa08-11e8-8e75-711e9403eb07.png)

This is the output I'm getting, as you can see the RTL isn't handling it the same way. This is caused by the space that follows the hyphen.

There's no difference when RTL bbcode is enabled.

I've found #3081 which marks #1848 as done, but I'm not sure it's the same issue.

**Steps to reproduce:**
Add a RichTextLabel to your scene and set this text: `- 你是个乐观主义者，你制定的计划永远会关注产出和利益，不过也千万记得关注风险与劣势，这样才能让你提高成功几率;`

**Minimal reproduction project:**
There's an official RichTextLabel demo that could be used as a playground.

Edit: As a workaround I've found that with other [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character#Unicode) this isn't happening. For example with: `U+2002`.

**Comment by KoBeWi** [comment]
This will be probably fixed by Complex Text Layout PRs.

**Comment by akien-mga** [comment]
Fixed by Complex Text Layouts in 4.0, and fixed by #49280 in 3.4.
