### ISSUE TITLE
Make Inspector bigger by default

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21480]
**Godot version:**
3.1 5df9109

**Issue description:**
Inspector is one of the most important and the most used panel in editor but at the same time is one of smallest.

Inspector should look like in Unity, should have all vertical space to work. It is very unintuitive to scroll small Inspector Panel to find the right property.

This is my Editor Layout:
![aafaffafafafafafafafa](https://user-images.githubusercontent.com/41945903/44654459-096b3200-a9f2-11e8-933c-bcbbccd7954b.png)

Panel also should have smaller minimum size because that layout may be a little to big on small resolution screens or Godot should detect, on first opening, the resolution and choose right layout.

**Comment by nobuyukinyuu** [comment]
Inspector is the same size I expect a properties window to be. Coming from Visual Studio, the default size is about the same.

**Comment by qarmin** [comment]
On my screen resolution of 1366x768, which is still used by many people, the inspector shows only a few properties. Only after adding the second panel, godot seems to be really useful and does not take up too much space.
I also think that some properties should be smaller and with bigger inspector it should be really good layout from beginners to professionals

Default panel with full screen Godot (1366x768)
![1](https://user-images.githubusercontent.com/41945903/44958263-113d4180-aede-11e8-80a2-6979997e4e13.png)

My suggestion with the second panel has more space that not need to be scrolled.
![2](https://user-images.githubusercontent.com/41945903/44958265-126e6e80-aede-11e8-9fad-a152108efa18.png)

**Comment by eon-s** [comment]
This is a matter of taste, and bigger panels by default means less space on the central one which may not be desirable.
Also video tutorials may not be a valid reference because content creators need particular things to show the details they want to show.

On small resolutions, setting the font on size 12 looks better without changing sizes of panels.
<details>

![panelsizes](https://user-images.githubusercontent.com/10215987/44962989-355c4b00-aefd-11e8-9456-624e412f8198.png)

</details>

**Comment by qarmin** [comment]
Font with size 12 still looks good and I think godot should automatic choose layout for different resolution at first launch 
e.g. <1366x768 should have font size 12, two panels - left FileSystem, right Inspector, Scene etc.
>1366x768 should have font size 14, three panels - left FileSystem, right left Scene Import and Node, right right Inspector
