### ISSUE TITLE
RichTextLabel bbcode support evaluation

### ISSUE THREAD

**Issue by ganlub** [godotengine/godot#21488]
**Godot version:**
v3.0.6

I've experienced some issues with RTL such as #21482 and #21285 and I decided to evaluate bbcode's full support against the official tags [reference](https://bbcode.org/reference.php).

So far I couldn't find support for the following (names from the official reference):
1. Font-size (#5557)
2. Left align text
3. Quote
4. Image (resized)
5. Image attributes `title` and `alt`
5. Preformatted
6. Youtube videos

**3**, **5** and **7** probably aren't something that need to be implemented on a platform like Godot. But the others could be quite handy.

The only available [reference](http://docs.godotengine.org/en/latest/tutorials/gui/bbcode_in_richtextlabel.html#reference) on Godot's documentation doesn't clearly state if more tags are supported. For example lists and tables are supported, yet they aren't there.

I thought this situation could be discussed and maybe get some of this implemented.
Maybe this issue could also be used to group the other RTL's issues and make them easier to work on.

**Comment by Calinou** [comment]
There's already an issue about setting the font size in a RichTextLabel: https://github.com/godotengine/godot/issues/5557

Text in RichTextLabel is currently left-aligned by default, but I agree the default alignment should be configurable. In this case, a `[left]` tag would become useful.

As for preformatted text, RichTextLabel already supports `[code]` tags (which requires a font to be loaded into the **Mono Font** property). Line breaks should be preserved inside of those tags, so I'm not sure if another tag for pre-formatted text would be useful.

**Comment by Calinou** [comment]
In 4.0, [the `[img]` tag supports defining a width and/or height](https://docs.godotengine.org/en/latest/tutorials/ui/bbcode_in_richtextlabel.html#reference). You can specify only a width to let the image scale automatically while preserving its aspect ratio.

> The difference between [code] and [pre], if I'm not mistaken, is it that the last one preserves the indentation and spacing. Maybe [code] could, if it isn't already, handle those and reduce the overhead of having two that are basically the same.

RichTextLabel does not interfere with whitespace in any way, unlike HTML in general (which is why `<pre>` is needed there).
