### ISSUE TITLE
Filesystem bottom box should scale, not disappear

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#21499]
**Godot version:**

current tip
0565adb20ff01a758c5ae8e4534a2cb7f07952df

**OS/device including version:**

Linux

**Issue description:**

![peek 2018-08-27 20-51](https://user-images.githubusercontent.com/4047289/44679630-ccc42880-aa3b-11e8-8b91-aaee391e71d6.gif)

**Comment by groud** [comment]
No, it should disappear when there is not enough space to use it properly.
You have the Split Mode Minimum height parameter to make the height required less height.

**Comment by capnm** [comment]
IMHO This may be technically correct, but a human would expect it to behave similarly to the right side, and he will not seek any obscure parameters.

**Comment by groud** [comment]
I disagree, this avoid bloating on small screens. You simply have to double click on a folder to display the file list, 
so discoverability is not a problem in that case.

Honestly I don't see the problem here, the file view adapts automatically to the window size, which is a good UX in my opinion. And there is no point in copying the right side, which is technically made of two different docks instead of one for the file list / tree.

**Comment by capnm** [comment]
> You simply have to double click on a folder to display the file list

Well, I couldn't have imagined that a double-click would switch to the file list :-)
I'd still prefer, if the middle dividing line would shift proportionally and only with manual pulling down then the upper box would work like that. But if it is not doable, I guess you can close the issue.

**Comment by groud** [comment]
Everything it doable.
But let's see what other people think about it. 

Maybe the default value for the minimum height is too high though. On you gif it seems, that it disappears too soon.

**Comment by capnm** [comment]
I finally took the time to find and change the option. If I put it to zero, the file list behave almost like I expected.  10000, to enforce the one-box double-click mode is not bad either ;-)

![image](https://user-images.githubusercontent.com/4047289/44725389-6d1a5b80-aad5-11e8-9b93-c950a8c31640.png)

I don't like it disappearing automatically, but maybe someone could work out a better value ...
