### ISSUE TITLE
class_name line not marked safe

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#21509]
**Godot version:**
master

**Issue description:**
`class_name` line and following lines not highlighted as safe, in otherwise fully safe file.

**Comment by akien-mga** [comment]
CC @vnen

**Comment by KoBeWi** [comment]
On 3.1 stable, when `class_name` is before everything, it's safe
![image](https://user-images.githubusercontent.com/2223172/56160363-4f97f480-5fc7-11e9-8596-318890816d5e.png)

Otherwise not
![image](https://user-images.githubusercontent.com/2223172/56160409-6cccc300-5fc7-11e9-8b3c-dddd14899d55.png)

**Comment by 2shady4u** [comment]
Putting class_name above extends is not permitted anymore in latest master.

I've hopefully fixed this issue in PR #31041
