### ISSUE TITLE
Error on array type

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#21508]
**Godot version:**
master

**Issue description:**
```gdscript
const TABLE: float[] = [0.0, 1.0]
```
produces `Constant expects assignment`.

```gdscript
var table: float[] = [0.0, 1.0]
```
produces `Expected end of statement (continue)`.

I think that's the proper syntax, from #19264, but types are not really documented ATM.

**Comment by vnen** [comment]
Typed arrays are not implemented, so this won't work.

**Comment by letheed** [comment]
Arf, I just realized that 30s ago... -_-
