### ISSUE TITLE
Material roughness of 1 causes extreme graphical glitches in GLES2/Phong specular mode

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#21513]
**Godot version:**
3.1-alpha 02490db

**OS/device including version:**
OS: Linux Mint 19 Cinnamon x64
GPU: NVIDIA GTX 980 Ti
Drivers: nvidia-driver-390 (390.48-0ubuntu3)

**Issue description:**
Using any type of light (OmniLight, DirectionalLight, SpotLight) results in heavy graphical artifacts. This just applies to the 3D renderer. According to the [last GLES2 progress report](https://godotengine.org/article/gles2-and-gdnative-progress-report-7) this should be working... 

Test scene in GLES2:
![gles2](https://user-images.githubusercontent.com/27100585/44693632-a8ecfb00-aaac-11e8-8860-5f22ea3e04ac.png)

The same scene in GLES3:
![gles3](https://user-images.githubusercontent.com/27100585/44693636-abe7eb80-aaac-11e8-9090-4b00c52d1be7.png)

@karroffel :rat: 

**Steps to reproduce:**
1. Switch to the GLES2 renderer
2. Add a mesh
3. Add a light

**Minimal reproduction project:**
[gles2 lights bug.zip](https://github.com/godotengine/godot/files/2326039/gles2.lights.bug.zip)

**Comment by karroffel** [comment]
The problem here is that "Lambert Wrap" looks horrible with roughness = 1. The same actually happens on GLES3 as well if you change the diffuse mode to "Lambert Wrap".

A workaround could be to clamp the roughness inside the shader to like 0.99 or so.

**Comment by CptPotato** [comment]
As it's somewhat related (#19175): Limiting the roughness in general would be a good idea. Either by clamping/remapping the value or modifying the light calculations themselves.

Having 0 or 1 as roughness usually produces very extreme (and unrealistic) results that the renderer might not handle very well.

**Comment by homer666** [comment]
> The same actually happens on GLES3 as well if you change the diffuse mode to "Lambert Wrap".

I tried this out, and it isn't the case:
![image](https://user-images.githubusercontent.com/27100585/44717316-09595800-ab00-11e8-8841-a7018ba5beb8.png)
(all three materials have Diffuse Mode set to Lambert Wrap btw)

This isn't meant to refute your point or anything, I just want to understand the problem a little better...

**Comment by homer666** [comment]
At the risk of missing the point, I tried setting the roughness of the three materials to 0.5 to avoid the problems mentioned. The diffuse modes are set to Lambert Wrap, since based on @karroffel's comment I assume GLES2 implicitly uses that regardless of what is actually set.

Even then, there's some weirdness:

GLES2:
![image](https://user-images.githubusercontent.com/27100585/44717774-525ddc00-ab01-11e8-82f6-fd2fd5d78f0b.png)

GLES3:
![image](https://user-images.githubusercontent.com/27100585/44717796-61dd2500-ab01-11e8-85ff-3b3385753e4c.png)

I'll also note that the scene is pretty much identical when all lights are disabled.

I guess my point is that it seems like GLES2 just isn't doing something with lights that GLES3 is. It's reasonable to assume the two renderers will do things differently, but it's hard to tell where the line between "difference" and "bug" lies...

**Comment by karroffel** [comment]
Maybe it's not lambert but Phong, can you try setting "lambert wrap" for diffuse and "phong" for specular?

**Comment by homer666** [comment]
Okay, the GLES3 with all materials' diffuse set to Lambert Wrap and specular set to Phong (roughness still at 0.5) is a lot closer to the GLES2 renderer:
![image](https://user-images.githubusercontent.com/27100585/44745896-5105d100-ab4c-11e8-99d2-d2b0f62811bf.png)

With roughness in all materials set to 1, similar lighting glitches do in fact occur in GLES3:
![image](https://user-images.githubusercontent.com/27100585/44745979-8b6f6e00-ab4c-11e8-9ce4-5c3fd9ff0de5.png)

So I guess the root of the problem is Phong shading not playing nice with extreme (also default) roughness values. This issue is pretty similar to #19175, so maybe this should be collapsed into that one...

**Comment by Zireael07** [comment]
I am seeing the same in a copy of my racer. At first I thought something broke, but at night (when the sun's directional light is disabled) the problem doesn't exist.

**Comment by homer666** [comment]
Can't reproduce with 2d57ec2 (on Windows 10)

**Comment by akien-mga** [comment]
Thanks, closing as fixed.
