### ISSUE TITLE
TileMap has set_celld() missing get_celld()

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#21512]
**Godot version:**
db55d8a

**Issue description:**
I was excited to see `set_celld()` in the classref, and immediately wanted to try using it to set some custom per-tile data. However, as there is no `get_celld()` there doesn't seem to be a way to retrieve that data from the TileMap.

**Comment by akien-mga** [comment]
I'm not sure if `set_celld` should be exposed in the first place, it does no validation of the input dictionary whatsoever, that seems pretty unsafe: https://github.com/godotengine/godot/blob/2062d6126d70f5c70b7b03ecb9372ec637c0ea3e/scene/2d/tile_map.cpp#L729-L732

It was added as a utility method for engine features AFAICT, by @marcelofg55 in #19164.

**Comment by cbscribe** [comment]
Yeah, that doesn't sound safe. While it would be nice to have a place to store per-cell data, it would probably be better at this point to hide that function. As it is, it serves no purpose, and definitely doesn't do what you'd expect seeing it in the classref.

**Comment by marcelofg55** [comment]
@akien-mga If I rename the function to _set_celld it will be hidden from the classref, right?

**Comment by akien-mga** [comment]
Yep.
