### ISSUE TITLE
ScrollContainer's max scroll_vertical is larger than expected

### ISSUE THREAD

**Issue by sicienss** [godotengine/godot#21517]
**Godot version:**

3.0.6

**OS/device including version:**

Windows 8.1

**Issue description:**

I noticed that no matter what I do, the maximum value of a ScrollContainer's scroll_vertical is always 12 px more than expected.

With three Buttons each 20 px tall, inside a VBoxContainer with separation = 0, you'd expect a ScrollContainer 60 px tall to have no VScrollBar. But it does, and you can scroll down 12 px (that is, scroll_vertical can be increased to 12).

The result of this is that there is an ugly gap at the bottom of the VScrollBar, corresponding to the 12 extra pixels. 

**Steps to reproduce:**

- Create a ScrollContainer 60 px tall with scroll_vertical_enabled = true.
- Add a VBoxContainer with separation = 0.
- Add 3 buttons to the VBoxContainer, each 20 px tall.
- Observe the extra 12 px at the bottom of the VScrollBar.

**Minimal reproduction project:**
[ScrollContainerIssue.zip](https://github.com/godotengine/godot/files/2326383/ScrollContainerIssue.zip)

**Thoughts:**

Maybe these 12 extra pixels correspond to the height of an HScrollBar that isn't visible but is somehow figuring into the mix.

**Comment by reduz** [comment]
This is not a bug and you are under a false assumption:
* ScrollContainer has a stylebox which contains a margin, if you want it gone then override it in the inspector or from code.
* VBox and HBox also have some separation distance between elements in pixels. If you want it gone override it in the inspector or from code

**Comment by volzhs** [comment]
@reduz  `ScrollContainer` has only `Bg` style.
This custom style seems not related this issue.
What should I take a look?

![screenshot_20180912_233359](https://user-images.githubusercontent.com/8281454/45432259-64847080-b6e4-11e8-93bc-12e02db2dbb4.png)

**Comment by volzhs** [comment]
![screenshot_20180913_032906](https://user-images.githubusercontent.com/8281454/45445452-3fecc080-b705-11e8-99fd-3d9fb9bca660.png)
Here is what top of the inspector look.

![screenshot_20180913_032150](https://user-images.githubusercontent.com/8281454/45445509-601c7f80-b705-11e8-8f65-811850abc702.png)
And this is what inspector looks with current branch

![screenshot_20180913_032739](https://user-images.githubusercontent.com/8281454/45445534-732f4f80-b705-11e8-84da-302990a94d02.png)
And this is what #21534 PR provided.

This shows ScrollContainer shows more than it should.

**Comment by reduz** [comment]
@volzhs I think this is related to clip being the same size as the canvas item rect, while items are offseted by the stylebox. I never really thought of this as a problem, but maybe some can see it as it. Probably the way to fix it is to give a custom rectangle to the clip function..

**Comment by WeRideForCoffee** [comment]
> @reduz What I found caused this issue is here.
> 
> [godot/scene/gui/scroll_container.cpp](https://github.com/godotengine/godot/blob/9c0cc0db63f61cd71a2a735519dc7816973e5b7e/scene/gui/scroll_container.cpp#L385)
> 
> Line 385 in [9c0cc0d](/godotengine/godot/commit/9c0cc0db63f61cd71a2a735519dc7816973e5b7e)
> 
>  v_scroll->set_page(size.height - hmin.height); 
> [godot/scene/gui/scroll_container.cpp](https://github.com/godotengine/godot/blob/9c0cc0db63f61cd71a2a735519dc7816973e5b7e/scene/gui/scroll_container.cpp#L398)
> 
> Line 398 in [9c0cc0d](/godotengine/godot/commit/9c0cc0db63f61cd71a2a735519dc7816973e5b7e)
> 
>  h_scroll->set_page(size.width - vmin.width); 
> these lines set scrollbar page size with considering the other scrollbar also shown, even it's hidden.
> there's no considering the other scrollbar is hidden.

Interestingly I think I found where the 12px is coming from:
To replicate: Make a new project, add a panel container, add a scroll container (remove size flags, disable horizontal and vertical scrolling) and add just a basic color rectangle with a min size (I used 32x32)

When you run the project, inspect the nodes with the "Remote" view on the Scene tree you will find two (invisible) scrollbars _h_scroll and _v_scroll.. which have a size of 12px vertically and horizontally (respectively).
Despite being invisible the ScrollContainer sizes up to make room for this hidden Controls.

I think updating the ScrollContainer to _not_ create these when the respective scroll is disabled would resolve this bug, and if each respective option is enabled or disabled, then to add a new one to the control, or delete, as needed.

**Comment by volzhs** [comment]
yes.

**Comment by volzhs** [comment]
I think what @WeRideForCoffee found is same with mine.
the invisible scroller size affects the other.
and I still think #21534 fixes this issue.
