### ISSUE TITLE
Reload all scenes button in editor

### ISSUE THREAD

**Issue by mikica1986vee** [godotengine/godot#2151]
From the Facebook group discussion.

Please add reload all edited scenes button.

Thanks! :D

**Comment by draxdeveloper** [comment]
I upvote this, but would be better the reload working in individual scenes.

**Comment by mikica1986vee** [comment]
Why don't we have both? xD

**Comment by draxdeveloper** [comment]
Well, both would be even better =D

**Comment by jackmakesthings** [comment]
+1

**Comment by akien-mga** [comment]
Likely related to #2307.

**Comment by akien-mga** [comment]
With the various improvements made to scene and script reloading in 2.1, I believe this feature request is no longer relevant. Feel free to comment and ask me to reopen if you think it would still have an important use case.
