### ISSUE TITLE
class_name causes parse error in 3.0.6

### ISSUE THREAD

**Issue by bfishman** [godotengine/godot#21518]
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10

**Issue description:**

class_name seems to have broken

![image](https://user-images.githubusercontent.com/3529531/44699853-289aab80-aa54-11e8-9843-974bc2bde0e8.png)

**Steps to reproduce:**
Paste the following into a file called "Character.gd"

```
class_name Character

var health = 5

func print_health():
    print(health)

func print_this_script_three_times():
    print(get_script())
    print(ResourceLoader.load("res://character.gd"))
    print(Character)
```
note any errors:
```
 built-in:1 - Parse Error: Unexpected token: Identifier:class_name
 modules/gdscript/gdscript.cpp:583 - Method/Function Failed, returning: ERR_PARSE_ERROR
```

**Comment by akien-mga** [comment]
That's a feature of Godot 3.1, it was never in 3.0.6 (and will not be backported to the 3.0 branch).

**Comment by bfishman** [comment]
oh, thanks. good to know!  sorry about that, I didn't realise the latest docs covered 3.1, I figured they represented 3.0.6
