### ISSUE TITLE
Item List Editor window is nearly unusably small

### ISSUE THREAD

**Issue by tko** [godotengine/godot#21520]
**Godot version:**
3.0.6

**OS/device including version:**
macOS High Sierra 10.13.6

**Issue description:**
The Item List Editor window is tiny, showing only a single item vertically and about 8 characters of the text horizontally. And it is not resizable making it quite painful to use.
<img width="1792" alt="screen shot 2018-08-28 at 08 53 05" src="https://user-images.githubusercontent.com/13787/44706110-d59b1580-aaa0-11e8-943b-2ddaa32d08d7.png">
With 2880x1800 screen resolution there doesn't seem to be any good reason for the editor to be that cramped (around 325x450.) At least it should be resizable.

**Steps to reproduce:**
1. Create/Select an ItemList
2. Click "Items" in the toolbar

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment]
CC @Calinou, EDSCALE needed :)
