### ISSUE TITLE
3D 180 Y axis rotation + move() = bug

### ISSUE THREAD

**Issue by Kermer** [godotengine/godot#2153]
( Win64, 1.1 stable )
If you change Y rotation to 180 or -180 inside `_input` and you use `move()` inside `_fixed_process` instead of having (0,180,0) rotation you'll get (-180,0,-180) rotation next frame. While it looks the same it can break a lot of logic inside a script.
Here's example code:
```python
extends KinematicBody

func _ready():
	set_process_input(true)
	set_fixed_process(true)

func _input(ev):
	if ev.is_action("ui_up") and ev.is_pressed() and !ev.is_echo():
		set_rotation( Vector3(0,deg2rad(-180),0) )
	elif ev.is_action("ui_down") and ev.is_pressed() and !ev.is_echo():
		print(get_rotation()) # -180,0,-180

func _fixed_process(delta):
	move(Vector3(0,0,0))
```

**Comment by reduz** [comment]
this will be rewritten in 3.0, need to investigate more on how to do this properly

**Comment by SuperUserNameMan** [comment]
( official 2.0.3stable win64 )

when  -90 < ya < 90, we get (-0, ya, -0 )

when -180 < ya < -90, we get (-180,  ( -180 - ya ), -180 )

when 90 < ya < 180, we get ( -180, ( 180 - ya ), -180 )

And I confirm that when you did not notice this behavior, this breaks your scripting logic and sabotage your brain zenitude ...

**Comment by akien-mga** [comment]
This appears to be the same bug as #1479.
