### ISSUE TITLE
Tileset new editor -> Collision polygon becomes un-editable if you edit a region that is not created with the editor.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#21533]
**Godot version:**

Godot 3.1 apha compiled after bump
0565adb20ff01a758c5ae8e4534a2cb7f07952df

**OS/device including version:**

win

**Issue description:**

Editing single tile:
You can´t edit the collision polygon of the tile once the option was changed, editor closed, etc....
Multiples polygons are drawn instead.

![collisionuneditabke](https://user-images.githubusercontent.com/11712737/44725662-2711c780-aad6-11e8-8e3c-1886902eb274.gif)

I have to note that entire code of tileset take for garanted that multiple collision polygons are allowed, and specify an "shape_id"... so, probably is necessary a method to select what polygon you want to edit.

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by Ranoller** [comment]
I did more test. It´s seem that if you start the process of draw the collision shape after push +New Single Tile, the behavior is correct and you can edit that after draw the region in the new editor, but if the region is preexisting, every collision that you draw is locked and stay yellow and fixed.

**Comment by MarianoGnu** [comment]
a tile can have many collision shapes, you have to click on them to edit them

**Comment by Ranoller** [comment]
If a shape becomes yellow i cant select that by any click, nor ctrl+click alt+click RMB... i try all of them

**Comment by Ranoller** [comment]
I don´t know, im a bit busy working in the game and didn´t compile godot in a weeks.... I try to have a time this weekend to compile godot and test.

**Comment by MarianoGnu** [comment]
@Ranoller @akien-mga there has been some recent changes to collision shape selections. Can you confirm if this issue is still valid?

**Comment by akien-mga** [comment]
Assuming fixed as there were no new reports about this since August. Please comment if you can still reproduce it and we'll reopen it.
