### ISSUE TITLE
Can't see selected node indicator for zero size node with GLES2

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#21535]
**Godot version:**

3.1.alpha a651dbfe7

**OS/device including version:**

Kubuntu 18.04 / gtx 670

**Issue description:**

Can't see selected node indicator for zero size node with GLES2 renderer, like Node2D, YSort, Position2D...

**Steps to reproduce:**
1. put Node2D
2. select it from Scene dock
3. try to select it from viewport

![selected_node_gles2](https://user-images.githubusercontent.com/8281454/44728462-9065fa80-ab17-11e8-8168-7ed9c2ad8279.gif)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by reduz** [comment]
This seems to work fine now on GLES2, closing.
![pivot](https://user-images.githubusercontent.com/6265307/51778852-ba314680-20e2-11e9-8fa9-4965f51444f3.gif)
