### ISSUE TITLE
Tile selector: add option to resize tile entries

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#21536]
It is weird that even with a `list` mode, images are still horribly big.
I mean tiles like in a gridmap object, we should be able to resize it, for example:
![imgur-2018_08_28-13 33 55](https://user-images.githubusercontent.com/15695377/44720699-dd21e500-aac7-11e8-9320-7cca68373d01.png)

Option to disable icons to get more space would be useful too.

**Comment by MarianoGnu** [comment]
maybe an EditorSetting could be added to allow chose the maximum icon size, but it will scale the texture uniformly, you example looks horrible imo :P

**Comment by reduz** [comment]
example looks terrible, please don't
