### ISSUE TITLE
Tileset new editor -> Edit button for single tile only works if there is previous region in tile.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#21531]
**Godot version:**

Godot 3.1 alpha after "bump" commit.

**OS/device including version:**

Windows

**Issue description:**

Editor button only works if tile has a region previously and you need to press first the button and later the image to display options.

![singletile](https://user-images.githubusercontent.com/11712737/44724931-70611780-aad4-11e8-9d3d-2f0248369209.gif)

**Steps to reproduce:**
Open tile in editor with and without previous region.

In every selected tile throws this error:

TileSet::tile_get_tile_mode: Condition `!tile_map.has(p_id)` is true. returned: SINGLE_TILE.
At: scene\resources\tile_set.cpp: 412

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by Ranoller** [comment]
It´s seem that the dessired workflow is draw always a region, because pushing +NewSingleTile allows to you to draw a region and start to draw shapes, if this is intended, this confusion will be skipped with documentation... If someone confirm that tiles without region will be no editable in new editor this can be closed.

**Comment by MarianoGnu** [comment]
You are not editing any tile, use the "New Single Tile" button to add it before editing it...

**Comment by MarianoGnu** [comment]
there's no confusion, you add a texture, not a tile, if you dont create a tile in the texture it will dissapear from the tileset if you leave it and come back latter
