### ISSUE TITLE
Issue with creating siblings/children from the Mesh menu in foreign scenes

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#21543]
**Godot version:**

Godot master https://github.com/godotengine/godot/commit/d42807371c667cc117460b01e9d1484f4418906f

**OS/device including version:**

Windows 10

**Issue description:**

When trying to create a sibling/child using the Mesh menu in a foreign scene (obj object imported as a scene) the sibling/child can't be edited (moved, renamed, deleted,..) because it will be treated as if the node were from that scene.

Possible related issue: https://github.com/godotengine/godot/issues/18014

I think the issue comes from here: https://github.com/godotengine/godot/blob/master/editor/plugins/mesh_instance_editor_plugin.cpp#L153 but I'm not sure how to fix it.

**Steps to reproduce:**
![https://i.imgur.com/8zr8s1W.gifv](https://i.imgur.com/8zr8s1W.gif)

**Comment by KoBeWi** [comment]
Still valid in 4dede9e
Looks as if the CollisionShapes gets the same owner as the mesh, but the strange thing that the problem vanishes upon reloading the scene (you can move the CollisionShape).
