### ISSUE TITLE
Tilemap  -> deleting autotiles with ctrl+shift+RMB with "autotile not disabled" throws a bunch of errors to console

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#21549]
**Godot version:**

3.1 apha after bump
0565adb20ff01a758c5ae8e4534a2cb7f07952df

**OS/device including version:**

win

**Issue description:**

Deleting a section of autotiles with autotile activated and CTRL+MAY RMB throws:

ERROR: TileSet::tile_get_tile_mode: Condition ´!tile_map.has(p_id` is true. returned: SINGLE_TILE.
At: scene\resources\tile_set.cpp:412

No mathers if you try to delete single tiles, or only autotiles.... i think it throws one error by tile, behavior is not correct (stuck a bit by the print of the errors) and do holes

![tilemaperrors](https://user-images.githubusercontent.com/11712737/44754851-ffe1e700-ab23-11e8-9e84-ba365b2c701c.gif)

**Comment by akien-mga** [comment]
CC @MarianoGnu
