### ISSUE TITLE
libwebsockets does not link on UWP/32bit

### ISSUE THREAD

**Issue by hpvb** [godotengine/godot#21548]
**Godot version:**
Godot 6fcc20ec5116a77c2328f4406a258527cc1aad5e

**OS/device including version:**
UWP

**Issue description:**
Cannot link libwebsockets on 32bit UWP platforms

**Steps to reproduce:**
Build 32bit UWP binaries

```
modules.uwp.opt.32.x86.lib(minissdpc.uwp.opt.32.x86.obj) : error LNK2001: unresolved external symbol _GetBestRoute
modules.uwp.opt.32.x86.lib(minissdpc.uwp.opt.32.x86.obj) : error LNK2001: unresolved external symbol _GetIpAddrTable
```

Note: For the current a1 build libwebsockets is disabled for uwp.

**Comment by akien-mga** [comment]
CC @vnen @Faless

**Comment by bruvzg** [comment]
Looks like these functions are available for desktop apps only. See [GetBestRoute](https://docs.microsoft.com/en-us/windows/desktop/api/iphlpapi/nf-iphlpapi-getbestroute), [GetIpAddrTable](https://docs.microsoft.com/en-us/windows/desktop/api/iphlpapi/nf-iphlpapi-getipaddrtable).

**Comment by vnen** [comment]
UWP is a weird thing, 32bit builds are different than the 64bit. To solve this we can either patch the lib to use a different function, or add a shim function to replace the missing one, like we did with OpenSSL.
