### ISSUE TITLE
Tileset new editor -> Undo is not implemented

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#21542]
**Godot version:**

3.1 alpha
0565adb20ff01a758c5ae8e4534a2cb7f07952df
**OS/device including version:**

All

**Issue description:**

Undo is not implemented

**Comment by reduz** [comment]
@MarianoGnu guess you need to implement UndoRedo ?

**Comment by MarianoGnu** [comment]
Closed by #24645
