### ISSUE TITLE
Editing a project in 3.1 makes it impossible to open in 3.0.x

### ISSUE THREAD

**Issue by MattUV** [godotengine/godot#21547]
**Godot version:** v3.1.alpha.02490db and 3.0.5.stable

**OS/device including versionWindows 10 :** Windows 10

**Issue description:**
If you edit a project in Godot 3.1, you cannot open it anymore in Godot 3.0. It throws this error:
<pre>
ERROR: _load_settings_text: Condition ' config_version > 3 ' is true. returned: ERR_FILE_CANT_OPEN
   At: core/project_settings.cpp:495
ERROR: _load_settings_text_or_binary: Couldn't load file 'C:/Users/matth/Documents/Godot/testBug/project.godot', error code 12.
   At: core/project_settings.cpp:519
</pre>

**Steps to reproduce:**

- Create a project in v 3.1 and try to open it in Godot 3.0.
- OR : Create a project in 3.0, edit it in 3.1 and try to open it again in 3.0

**Minimal reproduction project:**
This project was made in 3.1, I cannot open it again in 3.0
[testBug.zip](https://github.com/godotengine/godot/files/2330058/testBug.zip)

**Comment by AlexHolly** [comment]
It is not a bug
Open project.godot and `edit config_version=4` to `config_version=3`

**Comment by MattUV** [comment]
Thank you very much!
Also, this post was a duplicate of #18758. I am closing it.
