### ISSUE TITLE
Failure detecting one way collisions

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#21555]
**Godot version:** 57ba7caa6

**OS/device including version:** Debian SID

**Issue description:**
KinematicObject2D (and maybe the rest, not tested) doesn't detect collisions between a RayShape2D and anything marked as one way collision.

**Steps to reproduce:**
Play the attached scene with collision shapes visible. Move the object with the cursors. It should change colors when detecting a floor collision, but will not stop on any of the shapes.

**Minimal reproduction project:**

[BadRayCollision.zip](https://github.com/godotengine/godot/files/2330953/BadRayCollision.zip)

**Comment by Anaxagor14** [comment]
Seems recent updates have changed the behavior a bit (collision is now detected as seen by the color change in the repro project) but no sliding/depenetration occurs). The problems are still there, RayShape2D and one-way collisions do not work together well, at all.

**Comment by akien-mga** [comment]
Seems fixed in the current master branch.
