### ISSUE TITLE
Inconsistencies across RigidBody's method parameters

### ISSUE THREAD

**Issue by TGRCdev** [godotengine/godot#21552]
In a [recent issue](https://github.com/godotengine/godot-docs/issues/1696) brought up on the godot-docs repo, @rcorre pointed out that RigidBody's ``add_force`` and ``apply_impulse`` methods had different parameter order:
```
void add_force (force, position)
void apply_impulse (position, impulse)
```
I wanted to start an issue to discuss some consistency changes that should be made to the ``RigidBody`` class and classes related to it.

I went back and compiled the method differences between ``RigidBody``, ``PhysicsDirectBodyState`` and ``PhysicsServer`` classes across 2D and 3D. The results [can be seen here.](https://docs.google.com/spreadsheets/d/1TgMlfHxzwE_qDxbMOpp7IzzCtgW6z8CT9euljWGzAt0/edit?usp=sharing)

Overall, every case of ``apply_impulse`` used ``(position, force)`` (which i will refer to as Format A), while only 3D instances of ``RigidBody`` used ``(force, position)`` (Format B) for ``add_force``. I think we should change all instances of Format B to Format A, but this will require breaking compatibility.

Any thoughts?

**Comment by eon-s** [comment]
Related #16863

**Comment by TGRCdev** [comment]
Whoops, didn't see that. I'll throw a comment on that and close this.
