### ISSUE TITLE
All keyboard shortcuts is not working on OSX

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot#21558]
**Godot version:**

commit [6671096dd7a442](https://github.com/godotengine/godot/commit/6671096dd7a442b250a8d07a175db99ba02e6d5a)

**OS/device including version:**

macOS High Sierra 10.13.3

**Issue description:**

1. In all the text area, I can not move cursor with directional key and 'delete' key.
2. all the shortcuts such as  'save scene' (command + s), 'open scene (command + o)'  are not working 

**Steps to reproduce:**
a simple example:
![image](https://user-images.githubusercontent.com/19422835/44771227-02345780-ab9d-11e8-93d5-84a35cbd0ca7.png)
try rename a project, the cursor can not be moved by keyboard

**Minimal reproduction project:**

**Comment by Jason0214** [comment]
I am not sure if it is really 'recent',  I haven't build the master for weeks 😅

**Comment by bruvzg** [comment]
Input and common shortcuts like `Command-S`, `Command-O` are working normally on my b6c170165c build. macOS 10.13.6 (17G65).

**Comment by Jason0214** [comment]
just rebuild it with commit 29f2571, the same problem still exists for me.

@bruvzg how about the problem that can not moving the cursor with direction key and 'delete' in text areas (e.g. gdscript editor), do you have it?

**Comment by bruvzg** [comment]
@Jason0214 no, arrow keys and delete works normally as well (lineedit, gdscript editor, moving scene node).

Tested with custom 29f2571 build and official [3.1 alpha 1](https://godotengine.org/article/dev-snapshot-godot-3-1-alpha-1) on Mavericks 10.9.5 (13F1911) and High Sierra 10.13.6 (17G65).

**Comment by Jason0214** [comment]
You just inspired me by saying that @akien-mga. When I try to bring up godot by directly calling `bin/godot.osx.tools.64`, everything works fine, so it is not the problem with the code, I will try to find out what happened with the .app template

**Comment by Jason0214** [comment]
whoops, it is still not working by calling `bin/godot.osx.tools.64`
