### ISSUE TITLE
Dev build config paths

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#21567]
Is there a way to make dev builds use different config paths than the stable ones? When I build godot from master I backup `.config/godot` so that it doesn't get "polluted" by master changes, it'd be nice if it could use `.config/godot.dev` instead or something like that. If there is not, I can patch that manually, but I was wondering how others dealt with that, and if there was an interest for maybe a build option.

**Comment by Calinou** [comment]
You can enable self-contained mode by creating a file named `._sc_` in the same directory as the Godot binary. All configuration files will be created in that directory, so your user-wide configuration directories won't be touched. (For the record, this is used by the Steam version.)

**Comment by letheed** [comment]
@Calinou Ah, thank you. I went through the compiling instructions in the doc, but I didn't think to look into the `Packaging` section for that. Do you think that could be renamed maybe? It seems it would be useful to most people compiling Godot and not just the handful looking into packaging it. Or maybe have a word about it in the general build/compilation sections?
