### ISSUE TITLE
KinematicBody2D using move_and_collide makes other colliding KinematicBody2D move

### ISSUE THREAD

**Issue by samdze** [godotengine/godot#21560]
**Godot version:**
Godot 3.0.6 and custom build 12290c172a6dd3763670d36039fbac8198e711f5

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
When a KinematicBody2D collides with another KinematicBody2D, they make each othe move if their movement is not parallel.
Reducing the safe margin mitigates the problem but doesn't completely solve it.

Here the object to the left performs `move_and_collide(Vector2(15 * delta, 0))` and the one the right `move_and_collide(Vector2(0, 0))` inside _physics_process. Safe margin is default 0.08.
![](https://i.imgur.com/8zMBvNf.gif)
Probably related to #18433

**Minimal reproduction project:**
[move_and_collide_test.zip](https://github.com/godotengine/godot/files/2331832/move_and_collide_test.zip)

**Comment by avencherus** [comment]
I can verify this as well, using Win10 64-bit with version 3.1 alpha c320d93.

**Comment by eon-s** [comment]
The project is using the default safe margin which is too high for this kind of interaction, all the bodies try to separate after move, making it move to the sides, reduce the safe margin to the minimum: `0.001`.

**Comment by avencherus** [comment]
@eon-s That seems to solve it.  That is quite a small margin value though.  X)

**Comment by eon-s** [comment]
On faster motions you can use higher margin (like on platformer demos), but if you want this kind of behavior, you must use a really low one.

**Comment by samdze** [comment]
> Reducing the safe margin mitigates the problem but doesn't completely solve it.

Even setting it to `0.001` doesn't ensure the KinematicBody2D doesn't move.

If the current approach with collision detection doesn't allow to completely solve this issue, I'd like to choose whether to enable the "try to separate" behaviour when I move a body.

Could this be implemented in a convenient way?

**Comment by eon-s** [comment]
It may still happens at very small motions, I do not know if there is a better option than `test_move`, check the results and decide if move or not to avoid pushing other objects.

**Comment by samdze** [comment]
That's not accurate enough, `test_move` only returns whether the movement would result in a collision or not, it doesn't provide any other informations.
The normal vector, the distance that is safe to travel before colliding with something, the colliding object and in general all the variables contained in KinematicCollision2D.

The only method I can think of is Physics2DDirectSpaceState's `cast_motion`, but it only provides the distance that it's safe to travel and the distance that would trigger a collision, this is not enough.

**Comment by Calinou** [comment]
This is likely resolved in the [physics nodes reorganization](https://github.com/godotengine/godot/pull/48908) for 4.0, closing.
