### ISSUE TITLE
3D Scene Gizmo

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#21565]
Hi there,

A scene gizmo to quickly change  views (right,left, front, top ... ) clicking on colored arrows, 
and ability to switch perspective/ortho by clicking on a center cube, 
would enhance the usability of the editor in 3D.

A video example : 
https://www.youtube.com/watch?v=fxJR2pHPyTQ&feature=youtu.be&t=218

**Comment by Lefl1** [comment]
IMHO this isn't really necessary as there are already Keyboard shortcuts for that.

**Comment by DevMagicLord** [comment]
I never use shortcuts.
I think this would be a nice addition to Godot, in one click to switch views.

**Comment by DevMagicLord** [comment]
The actual Godot viewport item [Perspective] works well, i don't think a 3D gizmo will add a lot.
