### ISSUE TITLE
Armature hierarchy requests

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#21574]
[Godot 3]

Hi there,

Godot is unable to display the armature hierarchy

https://github.com/DevMagicLord/Godot3/blob/master/bugs/noarmatrure.jpg?raw=true

It should be able to display the hierarchy, and also allow to attach objects to any armature hierarchy directly in the editor without coding 

https://www.youtube.com/watch?v=S_USClc_r5c&feature=youtu.be&t=28

**Comment by mrcdk** [comment]
You can use a [`BoneAttachment`](http://docs.godotengine.org/en/3.0/classes/class_boneattachment.html) node to attach objects to bones

**Comment by DevMagicLord** [comment]
Someone reported BoneAttachment doesn't work in all situations.

Why Godot should not be able to display armature hierarchy , and drag and drop objects to attach them like many 3D engines ?
