### ISSUE TITLE
SSL Not Working

### ISSUE THREAD

**Issue by primesoftware** [godotengine/godot#2157]
I am using a REST API and would like to connect over SSL. I downloaded the CA's public cert and made sure it is PEM encoded, but I'm getting the following error:

Cause: unable to get local issuer certificate
CERT STR: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance CA-3

I have the CA's public cert in my Godot project root and checked it off in the Project Settings menu. Any ideas?

Godot console errors....
https://www.dropbox.com/s/6tygegd6hi6twvv/errors.png?dl=0

**Comment by reduz** [comment]
are you sure you are using the right cert? try getting the standard linux all-certs file and test with that to make sure

**Comment by primesoftware** [comment]
I am pretty sure I had the right cert, but I tried the all-certs bundle I got from Mozilla (https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt) since I am not on Linux yet. Still no luck (https://www.dropbox.com/s/hp12hnuo9f6j1bt/errrors.png?dl=0). Says there are IO errors.

**Comment by akien-mga** [comment]
Can anyone reproduce this issue?

**Comment by primesoftware** [comment]
@akien-mga I'm still having this issue and kind of left Godot to explore some other options only to return back here. The difference however is this time I know some C++ so I am currently working on gutting Godot's HTTP handler and making a new one using the lightweight ASIO (not boost version) package. I cannot say for sure when it will be ready, but I think its the best way to go. I nearly pulled my hair out trying to figure out what was going on with Godot networking as it is now before I gave up.

**Comment by primesoftware** [comment]
@akien-mga I am going to try to get mbedTLS working in Godot. It is cross-platform and light weight. I have it compiling and successfully accessing yahoo on TLS connection. I just need to write some code to build and process the HTTP request after the server responds. So far so good....

**Comment by reduz** [comment]
wow never heard of mbed tls, if you manage to get it working that would be
awesome.. can't wait to get rid of openssl

**Comment by akien-mga** [comment]
mbed TLS seems to be dual-licensed Apache 2.0 and GPL 2.0. Would the former with compatible with the MIT?

**Comment by primesoftware** [comment]
@reduz That makes 2 of us! So far I have things working fairly well. I just need to break down the server response so its easy to work with headers, requests, and data.

@akien-mga According to what I have read, it is (http://choosealicense.com/licenses/). The only difference between Apache and MIT is that with Apache you have to state any significant changes to the code itself. Since we are not going to be modifying mbedTLS in anyway that shouldn't be an issue. Apache also grants people the right to patent their software if it includes an Apache license library.

**Comment by akien-mga** [comment]
@primesoftware Yep I've just done some reading and it looks like APLv2 can be used in MIT projects and vice versa. We probably just need to make sure that we have a doc file somewhere that described what libraries we use and under which licenses.

**Comment by akien-mga** [comment]
Dropping openssl would btw fix #1391 too.

**Comment by reduz** [comment]
if you get that to work, please make sure to get domain validation to work,
as otherwise using ssl would be useless unless you use your own certs

**Comment by primesoftware** [comment]
@akien-mga @reduz Update on my efforts to remove OpenSSL:

I've decided to go with libcurl as the HTTP/S client since it meshes well with mbedTLS. Figuring out how to compile it has been a project in itself, but I've got it working (mbedTLS + libcurl) with HTTP/S. The only dep for libcurl is zlib. I'm going to play around with getting this to build with scons next. I'm on vacation now so I have more time to play around. So far so good!

**Comment by reduz** [comment]
please do not go with libcurl, it has too many dependencies and is not as
portable

**Comment by reduz** [comment]
oh wait you managed to get it to compile and it works? nevermind then :)
Make sure you can get it to work on Android, iOS, etc though. My Biggest
issue wit libcurl is that as far as I remember it's a pretty large library
and adds a lot to the binary for functionality we are most likely not going
to use

**Comment by reduz** [comment]
$ ls -l /usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0
-rw-r--r-- 1 root root 436640 abr 29  2015
/usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0

kind of big

**Comment by reduz** [comment]
as in, I don' t mind if it's provided as a module, but let's keep using
godot built-in http client with openssl or mbedtls directly for the time
being

**Comment by primesoftware** [comment]
I compiled libcurl without the bells and whistles (I.e HTTP_ONLY). The
static lib is 500kb. I've read you can get it down to about 170kb though
with some tweaking.

**Comment by reduz** [comment]
Can you try linking with it and without it? So we tell the difference

**Comment by punto-** [comment]
Is this using the StreamPeer class?

**Comment by primesoftware** [comment]
@punto- No, its not.
@reduz I haven't compiled the godot executable with libcurl / mbedtls yet, because I wanted to get the two working on their own first. The test binary I compiled only with the cURL is 350kB, but requires several dll files (libcurl-4.dll - 385 kb, libgcc_s_seh-1.dll - 82kB, libmbedcrypto.dll - 285 kB, libmbedtls.dll - 161 kB, libmbedx509.dll - 78 kB, libwinpthread-1.dll - 56 kB, zlib1.dll - 89kB). Its seems the crypto library is adding a lot of weight. What does OpenSSL add to the binary?

**Comment by primesoftware** [comment]
@akien-mga @reduz Ok, I've made some significant progress here. I've got a test application running with the mbedtls (approx 500kb for .a files) and libcurl (approx 350 kb for .a) pulling data from the Google homepage via TLS. We could probably trim down the mbedtls lib to only use certain ciphers / features. I used the default config file which compiles everything in, but there are others that are optimized for low resource devices. The issues I had were due to improper linking on my part. I'm using Mingw to compile and GCC has a particular order it likes the libs listed....sigh

I'm going to start integrating this with Godot. I need to know a few things to speed this up. 

1. How is the path to the cert set from project properties? I want devs to specify the name of the cert file to use as we do now so I just want to know where to find that in the code.

2. Both mbed and curl have pretty good makefiles. I know Godot uses Scons and I rather like scons too. Are there any short cuts here I can take to port make to scons?

**Comment by azurvii** [comment]
@primesoftware has there been more updates so far? Thanks for all the efforts BTW.
1. Not sure what it was like before, you can add "category-name-value" in project settings quite easily, and Globals.get("name") can get it out at runtime.
2. Try calling make directly from scons? https://stackoverflow.com/a/6380330/1066506

**Comment by primesoftware** [comment]
@azurvii I have not forgotten about the mbedTLS integration into Godot. Unfortunately I got sidetracked with another project. Also, I learned the REST API I was going to use (Parse) is getting shutdown permanently. The other open source options to Parse are not a good fit for me so I've been rolling out my own Java solution for a REST API based on Vert.x. I know that isn't going to do anything for Godot, but before I can continue Godot dev I need a working REST API. Thankfully, Vert.x is rather complete and close to being a full fledged solution to what I need so I don't anticipate it being much longer before I get back into the mbedTLS integration. I could post what I have thus far, however I will warn that there are some dangling pointers to be dealt with. If you want a perfect solution though it will take some time. I'm only a hobbyist so I don't get to work on the game dev as often as I wish.

**Comment by azurvii** [comment]
Cool advancement @primesoftware.
I also tinkered around some more and I got the built-in openssl to work with https requests on master. The code works, just that I need to flip a switch. I put some details in https://godotengine.org/qa/4047/, in case it could help you in anyway for the time being.

**Comment by vnen** [comment]
Considering the last comment by @azurvii, I believe the recent change @punto- made to the buildsystem might have remove the `OPENSSL_ENABLED` flag from a file it shouldn't: [`drivers/register_driver_types.cpp`](https://github.com/godotengine/godot/blob/master/drivers/register_driver_types.cpp). Then the openssl driver is being built correctly but never registered.

**Comment by azurvii** [comment]
[SConstruct](https://github.com/godotengine/godot/blob/2.0.3-stable/SConstruct#L310)'s openssl config part was commented out, which leads to no `OPENSSL_ENABLED` set for the compiling process, no matter what the options are given to `scons`.

**Comment by vnen** [comment]
@azurvii  `OPENSSL_ENABLED` is now set in [`drivers/SCsub`](https://github.com/godotengine/godot/blob/master/drivers/SCsub) in a cloned environment. This makes it better because you can enable/disable without having to recompiling everything else, since there's no change of flags for the rest of the source. The problem here is that `register_driver_types.cpp` seems not to be included in this configuration, so it doesn't register the OpenSSL driver.

**Comment by azurvii** [comment]
I see. Thanks for the explanation @vnen.

**Comment by reduz** [comment]
It seems Godot had a bug and did not support SNI authenthication for SSL, this has now been fixed. Not sure if that was the root of the original problem

**Comment by akien-mga** [comment]
@reduz implemented SNI support, and @vnen fixed OpenSSL 64-bit support on Win64, so there are high chances this issue got fixed too. Feel free to comment and ask me to reopen if it's not the case for you in the master branch / 2.1-beta.
