### ISSUE TITLE
 zstd does not link on UWP/ARM

### ISSUE THREAD

**Issue by hpvb** [godotengine/godot#21579]
**Godot version:**
Godot cf834a22dc78950a9fba484a7f9db98da84cae59

**OS/device including version:**
UWP

**Issue description:**
Cannot link upnp on ARM platforms

**Steps to reproduce:**
Build ARM UWP binaries

```
core.uwp.opt.32.arm.lib(zstd_decompress.uwp.opt.32.arm.obj) : error LNK2001: unresolved external symbol __cpuidex
core.uwp.opt.32.arm.lib(zstd_decompress.uwp.opt.32.arm.obj) : error LNK2001: unresolved external symbol __cpuid
```

Note: For the current a1 ARM builds are disabled.

**Comment by akien-mga** [comment]
CC @vnen @mhilbrunner

**Comment by akien-mga** [comment]
See also #21546.

**Comment by vnen** [comment]
Might be worth opening an issue upstream. They fixed UWP issues in the past.

**Comment by vnen** [comment]
I opened the issue upstream: facebook/zstd#1313. If there's no answer I can make a temporary patch.

**Comment by mediaexplorer74** [comment]
> I opened the issue upstream: [facebook/zstd#1313](https://github.com/facebook/zstd/issues/1313). If there's no answer I can make a temporary patch.

Hi, George Marques. Sorry for pinging you at this place. One Dev question:
how to find some good UWP C# Gogot sample that consisits of Microsoft Angle inside?... I'm explored that "Export to UWP" (from the non-Mono edition of Godot) only generates appx ( not-editable package, without C# logics... that is full absurd). 
I'm really don't want to use SCONS and so on. I have professional VS.

**Comment by Zireael07** [comment]
@mediaexplorer74 Please stop spamming on unrelated issues
