### ISSUE TITLE
Gridmap map level is not affected by undo

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#21583]
**Godot version:**
3.1.dev-1

**Issue description:**
If we change gridmap level, we can't restore its previous value by using undo.

**Steps to reproduce:**
1. Change the level, doesn't matter how.
2. Try to undo.
![imgur-2018_08_29-23 06 05](https://user-images.githubusercontent.com/15695377/44815396-b2c34b00-abdf-11e8-9295-279e80feaa64.png)

**Comment by vnen** [comment]
Does this really need to be undone? Its just an editor control, it's not even saved anywhere AFAIK.

**Comment by KoBeWi** [comment]
Yep, this is not a bug.
