### ISSUE TITLE
Continuous undoing things while pressing Ctrl+Z

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#21582]
Right now if we press Ctrl+Z, only one "undo" is done. No matter how long we're pressing it.

I think it should activate "continuous undo mode" after holding Ctrl+Z for more than 0.5s (or different value) to undo things faster/more efficiently.

**Comment by EricEzaM** [comment]
This is because MenuButton ignores echo's.

#36493 should resolve this.

**Comment by Anutrix** [comment]
I think https://github.com/godotengine/godot/pull/36493 has indeed fixed this. Holding Ctrl+Z on `master` build does undo continuously.
