### ISSUE TITLE
Strange FS behavior after load .pck file

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#21580]
**Godot version:**
3.1.alpha.calinou.1ff772b

**OS/device including version:**
Win 8.1

**Issue description:**
Code:
```
extends Node2D

func _ready():
	dir_contents()
	print('-- LOADING PACKAGE --')
	# Small .pck with one scene (Node2D.tscn)
	ProjectSettings.load_resource_pack('nf.pck')  
	dir_contents()

func dir_contents(path = "res://"):
	var dir = Directory.new()
	if dir.open(path) == OK:
		dir.list_dir_begin(true, true)
		var file_name = dir.get_next()
		while (file_name != ""):
			if dir.current_is_dir():
				print(dir.get_current_dir() + file_name + "/")
			else:
				print(dir.get_current_dir() + file_name)
			file_name = dir.get_next()
	else:
		print("An error occurred when trying to access the path.")
```

Output:
```
res://.import/
res://default_env.tres
res://export_presets.cfg
res://icon.png
res://icon.png.import
res://main.tscn
res://nf.pck
res://Node2D.gd
res://project.godot
-- LOADING PACKAGE --
res://.import/
res://Node2D.tscn
res://icon.png
res://icon.png.import
res://project.binary
```
It is normal that the structure changes after loading .pck file?

**Minimal reproduction project:**
[dlc.zip](https://github.com/godotengine/godot/files/2333730/dlc.zip)

**Comment by Timofffee** [comment]
And if that's OK, then how can I find out about the files that have been added from the downloaded .pck file?

**Comment by LikeLakers2** [comment]
I was having the same issue, and also found a workaround. See #19815.

In short:
* The first load replaces all the files.
* Subsequent loads add files to the current list, replacing any current ones.

**Comment by raymoo** [comment]
Was this closed for being a dupe of #19815?

**Comment by LikeLakers2** [comment]
@raymoo I would assume so. The two at a glance, seem to describe the same issue, though admittedly it's been nearly a year since I made #19815, so I don't remember if I thought of this as a duplicate when making my comment above.

**Comment by Timofffee** [comment]
Ahm... Yeah.
