### ISSUE TITLE
Keeping different rotation values for tiles in a tile selector window

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#21581]
**Issue description:**
I checked only gridmap tiles, I'm not sure if it is the same for tilemaps.

The main problem is that, if we select a tile via tile selector and rotate it, the same rotation will be used for the next tile we select and place.
It is a bit non-intuitive, tiles should have their own rotations (at least I think so).
They use the rotation from previously selected tile instead.

**Steps to reproduce:**
1. Place two different tiles on a map,
2. Select first tile, rotate it and place,
3. Select second tile and place it,
4. The same rotation is applied to the second tile too (we can compare rotations with tiles placed in step 1)

**Comment by KoBeWi** [comment]
Fixed in new TileMap.
