### ISSUE TITLE
Color constants in visual shader can't be changed.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#21598]
**Godot version:**
3.1 alpha 9eb4d4a

**OS/device including version:**
Windows 10 64bit

**Issue description:**
The color constant node is always white and can't be changed. The console is also spammed with these errors when trying to set the color.
![error](https://user-images.githubusercontent.com/11450875/44861623-e1284100-ac46-11e8-9ae2-832e52f73c6a.png)

**Steps to reproduce:**
Create a visual shader on a mesh, create a color constant and try to change the color.

**Comment by DynasoulStudio** [comment]
Can confirm, the Constant Color node will remain white no matter what, actually this issue can be found with all nodes, you cannot edit them inside the visual editor, it only works if a shader parameter appears under the inspector, and even then it doesn't always save properly.

I asked a related question here:
[https://godotengine.org/qa/32554/how-do-i-save-apply-a-visual-shader-in-godot-3-1-alpha](https://godotengine.org/qa/32554/how-do-i-save-apply-a-visual-shader-in-godot-3-1-alpha)
