### ISSUE TITLE
Scene file created by PackedScene.pack contains redundant properties

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#21594]
**Godot version: 3.0.6

**OS/device including version:**

**Issue description:**

When use PackedScene create tscn file, all properties are included in the file which should be found in the instanced scene file. That result the file become huge.

See the demo project, compare the file SceneCreateByPack.tscn and SceneCreatedInEditor.tscn.
[PackedSceneIssue.zip](https://github.com/godotengine/godot/files/2335318/PackedSceneIssue.zip)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Fixed in 3.1
