### ISSUE TITLE
custom font not applied to newly-opened scripts

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#2159]
#1496 is somewhat related.

Opening a script for editing ignores the custom font. I have to close out to the project manager, and load the project again and then the opened scripts will have the custom font.

**Comment by akien-mga** [comment]
Confirmed in the current master branch.

**Comment by akien-mga** [comment]
Interestingly, after opening a new script to which the custom font is not applied, if you go in the editor settings and clear the "custom font" field, the custom font will be applied to the newly opened script...

**Comment by reduz** [comment]
does this still happen? looks like it might have been fixed

**Comment by adolson** [comment]
I tested it last night and when I open a script it still uses the small
font. When I close the project and reopen it and the script is already
open, it uses the custom font. So it's still buggy.

**Comment by akien-mga** [comment]
Is this still valid with the new editor fonts system in 2.1?

**Comment by vnen** [comment]
I can't reproduce, will assume it's fixed. If the bug still happens, someone can comment here or open a new issue.
