### ISSUE TITLE
autocomplete should search autoloads

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#2160]
The autocompletion should support the autoloaded nodes as well. for example, if I have an autoload for SUTjoystick, then get_node("/root/SUT should pop up an autocomplete option to get_node("/root/SUTjoystick")

It could even dig into the autoloaded scene or script for variables, functions, nodes, etc.

**Comment by jackmakesthings** [comment]
+1

**Comment by reduz** [comment]
I have added this to github head last week, dows it not work for you?

**Comment by adolson** [comment]
I tested it VERY briefly tonight, it doesn't seem to crawl through the
scene tree of an autoload. Is it supposed to? It does show the member
variables, I believe.

**Comment by okamstudio** [comment]
Is the autoload a script or a scene?

**Comment by adolson** [comment]
I was testing with a scene. I tried opening it in another tab too, in case
it had to be open for some reason, but it didn't appear to make a
difference. I didn't test it very much, though.

**Comment by draxdeveloper** [comment]
yeah, autocomplete sometimes complete and sometimes not (not just the
autoload) but it's always completes with the get_node()

2015-07-07 10:03 GMT-03:00 Dana Olson <notifications@github.com>:

> I was testing with a scene. I tried opening it in another tab too, in case
> it had to be open for some reason, but it didn't appear to make a
> difference. I didn't test it very much, though.
>
> On Tue, Jul 7, 2015 at 2:12 AM, Okam Studio <notifications@github.com>
> wrote:
>
> > Is the autoload a script or a scene?
> >
> > On Jul 7, 2015 8:07 AM, "Dana Olson" <notifications@github.com> wrote:
> >
> > > I tested it VERY briefly tonight, it doesn't seem to crawl through the
> > > scene tree of an autoload. Is it supposed to? It does show the member
> > > variables, I believe.
> > >
> > > On Tue, Jul 7, 2015 at 1:45 AM, Juan Linietsky <
> notifications@github.com
> > >
> > > wrote:
> > >
> > > > I have added this to github head last week, dows it not work for you?
> > > > On Jul 7, 2015 4:08 AM, "jack" <notifications@github.com> wrote:
> > > >
> > > > > +1
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > https://github.com/okamstudio/godot/issues/2160#issuecomment-119047402
> > > > >.
> > > >
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/okamstudio/godot/issues/2160#issuecomment-119079769
> > > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/okamstudio/godot/issues/2160#issuecomment-119082573
> > >.
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/2160#issuecomment-119083341
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2160#issuecomment-119197893>.
>



-- 
David Aguiar de Aquino Paiva

**Comment by vnen** [comment]
Is this already fully implemented?

**Comment by akien-mga** [comment]
For me autocompletion of autoloaded scenes works fine.
