### ISSUE TITLE
Background thread loading demo not working on Android and iOS

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#21609]
**Godot version:**

master: v3.1 2b9902d

**OS/device including version:**

Windows 10
Android 7.1.1 in Motorola Moto Z
iOS 11.4.1 in iPhone 6

**Issue description:**

Running the background loading demo works fine on Windows, but shows black boxes on Android.

**Steps to reproduce:**
1. Open the ![background thread loading demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/background_load)
2. Test on Windows: works fine
3. Test on Android: shows black squares instead of the images
![Android screenshot](https://user-images.githubusercontent.com/2841740/44875494-c076e000-ac74-11e8-8aa2-a200eecbfb68.png)

**Minimal reproduction project:**
![Background thread loading demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/background_load)

**Comment by henriquelalves** [comment]
I can confirm this also won't work on my phone (Redmi Note 4)

**Comment by henriquelalves** [comment]
I adapted the Background Loading Demo code for Godot v2.0 to test, and it's working there on both PC and Android - so this is probably a rendering problem?

**Comment by jahd2602** [comment]
Tested on iOS 11.4.1 in iPhone 6, the bug happens too.
Tested Godot 3.0 in Windows/Android/iOS and the bug happens too.
Looks like a regression regarding the "visual pipeline" change from 2.x to 3.x.

**Comment by FeralBytes** [comment]
FYI, ran into this with Godot master 3.1 e6cfaa18cae296e441a0496b28e4ec3e0d4061ee  So the problem still exists.

**Comment by jahd2602** [comment]
@FeralBytes thanks for testing. 

Any clue on what part of the code may be generating these problems?

**Comment by FeralBytes** [comment]
I have my suspicions but have not had time to dig into the issue further.

**Comment by vnen** [comment]
I discovered that if you uncomment these lines fix the issue: https://github.com/godotengine/godot/blob/7f3093d3b98abff26a93b1c3d8e30d9f794919de/platform/android/os_android.cpp#L186-L189

The question is why were they commented out in this commit: b5a06cecffeda556438b33807d766f4823623fee, but the message is not clear about this change.

**Comment by akien-mga** [comment]
> The question is why were they commented out in this commit: b5a06ce, but the message is not clear about this change.

That's probably because multithreaded rendering was temporarily dropped when working on the new GLES3 renderer. It was then restored in 612ab8fcdb, but Juan likely forgot to reenable it for Android.

There are quite a few other features disabled in b5a06ce that would be worth checking in the current master branch (like `power_android.cpp` is still not compiled).

**Comment by FeralBytes** [comment]
Respectfully, will there be an upcoming PR to reverse the comments? Or do you need someone to submit a PR?

**Comment by vnen** [comment]
I'll make a PR soon. I want to check the other platforms as well.
