### ISSUE TITLE
AnimationPlayer dont work of duplicated node

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#21616]
**Godot version:**
Godot 3.1  9320c852f

**OS/device including version:**
Windows 10

**Issue description:**
When node with animation player was duplicated, in new node animation player dont work because all tracks become empty (without any keys)

**Minimal reproduction project:**
[godot-animplayer-test.zip](https://github.com/godotengine/godot/files/2338691/godot-animplayer-test.zip)

**Comment by DualMatrix** [comment]
Tested in 3.0.6 and it did work there, so this seems to be a regression
