### ISSUE TITLE
Tileset editor-> When two or more tiles completely overlap in a texture, the tiniest can´t be selected.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#21610]
**Godot version:**

3.1 alpha
2ba42b709541928aaaa0312077d5b9cacdb696a5

**OS/device including version:**

Windows 7

**Issue description:**

When you have more that one tile in a texture in the new editor, and two or more tiles are overlaping completely at the same place of the texture, the tiniest becomes un-selectable, allways is selected the bigger. Behavior should be the oposite, allways select the tiniest, because the bigger have "non colliding space" to click, but the tiniest not, and become "un-clickable"... and this is a problem because tileset editor don´t allow to load a texture more that one time, so any tile that you need to do with a texture will be together with others.

**Steps to reproduce:**

![tilemaperrors](https://user-images.githubusercontent.com/11712737/44876580-c9ca7180-aca1-11e8-8ba2-4c345169966a.gif)

**Comment by vpellen** [comment]
I also ran into this. I feel like there should be an explicit list of all the tiles tied to a texture as opposed to the current behavior of trying to be "smart" about it with contextual clicking and overlapping colored borders. As it stands, on a complex tileset it can be difficult to ascertain how many tiles you even _have,_ and managing multiple tiles on a single texture can become extremely unwieldy extremely fast. Atlas sprites seem to cover most use cases of having to deal with lots of similarly configured tiles, so I don't feel like we'd be losing much by completely axing the current selection methodology.

**Comment by KoBeWi** [comment]
Still valid in 3.2.2 rc2
IMO we should just disallow tiles with overlapping regions. Somewhat related to https://github.com/godotengine/godot-proposals/issues/896

**Comment by KoBeWi** [comment]
Tile overlap is no longer possible.
