### ISSUE TITLE
Godot doesn't send close frames upon disconnecting, and doesn't allow reading of close frames

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#21617]
**Godot version:**
v3.1.dev.calinou.5df9109 (from https://hugo.pro/projects/godot-builds/)

**OS/device including version:**
Windows 10 Home v1803 (April 2018 update) x64

**Issue description:**
Currently whether I use `client.disconnect_from_host()` or `client.get_peer(1).close()` to close a WebSocketClient's connection, Godot does not send a close frame, instead opting to just sever the connection. This means that, on the other end, I just time out after a while.

Additionally, when Godot *receives* a close frame, it marks the connection as closed as it should -- but I'm unable to read any data that might be bundled with that close frame. For example, if I have a connection to Discord and the service decides to disconnect me, I'm supposed to receive a [close event code](https://discordapp.com/developers/docs/topics/opcodes-and-status-codes#gateway) inside the close frame when the connection is terminated. However, as I'm unable to read the close frame's data, all I know is that I've been disconnected, not why.

**Comment by akien-mga** [comment]
CC @godotengine/network
