### ISSUE TITLE
OrientedPathFollow uses positive Z as forward

### ISSUE THREAD

**Issue by henkz1** [godotengine/godot#21624]
**Godot version:**
21ea1d8

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When using OrientedPathFollow increasing offset will move the node along positive Z (0,0,1).
The old implementation of PathFollow in 2.x branch will move along negative Z (0,0,-1)
Vector3 constant FORWARD is defined as Vector3( 0, 0, -1 ).

@danilo2205

**Comment by danilo2205** [comment]
Hello @henkz1 , I'm not quite sure what  _moving along negative Z_ would mean in this context, could you please provide me a screenshot or something so I can visualize it better?

_OrientedPathFollow_ is supposed to make a _Node_ move along a _Path_ using the _Curve_'s points as means to provide its forward orientation. Keep in mind that the order the _Curve_'s points are created does matter in this case.

**Comment by henkz1** [comment]
Hi @danilo2205, I mean the nodes local z axis, if you toggle "local space mode" (button looks like a cube) or just press T in viewport, then you can see local axis of selected node, then just change the offset and you will see what I mean.

**Comment by danilo2205** [comment]
That's a very interesting finding here, I never really used _PathFollow_ in any Godot version below 3.x and, as far as I can see, _PathFollow_ in 2.x behaves differently from its 3.x counterpart. 

I'm not the author of the _PathFollow_ node myself, I just created _OrientedPathFollow_ as an alternative to 3.x _PathFollow_ that enforces orientation (and use the _Curve3D_'s up vector information for tilting), I never knew Godot 2.x had a _PathFollow_ node that'd enforce orientation like my _OrientedPathFollow_ does, it's a coincidence that they behave similarly.

![image](https://user-images.githubusercontent.com/12879282/44949145-090fd400-ae02-11e8-9433-3e50fcfae97f.png)

_OrientedPathFollow_ is working as expected, it's supposed to align the Z axis to the _Path_'s _Curve_ at some offset using the order of the point's creation as the rule to find "where" it should be pointing at. It's not supposed to work like 2.x _PathFollow_.

![image](https://user-images.githubusercontent.com/12879282/44949193-285b3100-ae03-11e8-900a-0276428e19d6.png)

Nevertheless, I could create a feature (like a bool option) to turn the forward vector into its opposite direction (a.k.a negate the vector), so it would behave more like the 2.x _PathFollow_. What do you think?

Also, thank you for the feedback.

**Comment by henkz1** [comment]
Nah if it's not a bug you don't need to change anything, I can compensate or continue using my own implementation (based of 2.x). Thinking about it it might be better for me to customize my own pathfollow to better suit my needs. Thanks for taking the time to look at this!
