### ISSUE TITLE
 Add type information to signal documentation

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#21627]
**Migrated from:** https://github.com/godotengine/godot-docs/issues/1716  

At 3.1 the editor currently shows detailed type information:
> ![signal_types](https://user-images.githubusercontent.com/1151394/44911592-0c4f8500-ad5a-11e8-8144-d725ca99ae1a.png)

While the documentation shows only `Object` for all non-built-in types.

Both online:
> ![signal_types2](https://user-images.githubusercontent.com/1151394/44911940-40777580-ad5b-11e8-9585-a3396791c4ef.png)

And in editor:
> ![signal_types3](https://user-images.githubusercontent.com/1151394/44912037-8fbda600-ad5b-11e8-8eb9-95e883ecc3a9.png)

**Comment by akien-mga** [comment]
Fixed by #21635.
