### ISSUE TITLE
Shader Material is not unique

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#2162]
when I duplicate a sprite that has a shader and change the params of shader in one of them , both of them will change, I am instancing this sprite , and I need to change everyone of them separately how can I achieve that? can I make the materials unique in the code?

**Comment by ilearain** [comment]
In right/upper of property editor, Click on the settings icon in the inspector (it looks like a gear icon). Select "Make Resources Unique."

#2054

**Comment by ilearain** [comment]
Ahh.. In code? I have never tried it :laughing:

**Comment by mohaalak** [comment]
yeah I wrote load it then I duplicate it with value false, in this way
everyone of them is unique.

**Comment by reduz** [comment]
If you want to make the material unique by code, in case you want to change
parameters, just do:


sprite.set_material( sprite.get_material().duplicate() )
