### ISSUE TITLE
Editing sub scenes of control nodes is not trivial

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#21620]
**Godot version:** 3.1 custom

**Issue description:**
When making multiple scenes for the GUI, using the default viewport size is not always wanted. I have an object that needs to stay in a small square on the screen. That small square changes size and it is animated. The foreign scene that gets instantiated needs to be anchored as full rect. The problem arises when i want to edit the foreign scene on its own: if i use the full rect the control get stretched all over the viewport size, meaning that some things, like label text, does not show in an accurate way.

**Proposal:**
In the view menu, be able to specify a custom viewport size for the current scene.

**Comment by Zylann** [comment]
I had this situation too but I got over it by just not defining the anchors in the subscene, and instead choosing them in their "host" scene. It just made sense to me because a control meant to be integrated should not assume how its anchors should be, because that's the "host" to decide that.

**Comment by QbieShay** [comment]
@Zylann good point. I will try to design with that in mind.
