### ISSUE TITLE
godot crash after a file overwrite

### ISSUE THREAD

**Issue by Axeltherabbit** [godotengine/godot#21625]
Godot3

`uname -a
Linux xxx 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux
`

godot crash after a file overwrite, is not the first time time that happen, it has corrupted the file

logs:  https://anonfile.com/i6FcG1gfb4/log.txt

**Comment by qarmin** [comment]
Can you provide reproduction project?

**Comment by Axeltherabbit** [comment]
> Can you provide reproduction project?
No, sorry I lost the files

**Comment by akien-mga** [comment]
Closing then as we won't be able to debug further.
