### ISSUE TITLE
GUI focus not moving when holding d-pad on gamepad

### ISSUE THREAD

**Issue by antoniotorresm** [godotengine/godot#21628]
**Godot version:**
v3.1.alpha.official

**OS/device including version:**
Arch Linux with kernel Linux 4.18.5-arch1-1-ARCH

**Issue description:**
When moving UI focus with keyboard arrows, if you hold one arrow, it will move the focus in that direction until you release it. However, if you do the same using the d-pad from a gamepad, it won't move (it will behave as if you only pressed the button once instead of holding it).

**Steps to reproduce:**
1. Create some controls and configure them to be able to gain focus.
2. Run scene, give focus to one of them and hold keyboard arrow / d-pad.

**Minimal reproduction project:**
[UIFocusCyclingBugReport.zip](https://github.com/godotengine/godot/files/2340778/UIFocusCyclingBugReport.zip)

**Comment by vnen** [comment]
This is not a bug. For keys, the OS repeats the event if the key is kept pressed, but that does not happen for joysticks. There's no reason for Godot to override the OS behavior.

**Comment by antoniotorresm** [comment]
I see. Thank you!
