### ISSUE TITLE
RichTextLabel  underlining does not respect visible character

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#21637]
**Godot version:** 3.1alpha 02490db

**Issue description:** BBcode underlines are always shown even if the character is hidden. For example, with visible_characters += 1 in step,
![ezgif-5-d15294f8f4](https://user-images.githubusercontent.com/35355161/44936264-fc2bab80-ad41-11e8-9b33-5bdd2abe15fb.gif)

**Comment by Darenn** [comment]
Hi! I would like to add that this behaviour also happen with the striketrough bbcode.

![image](https://user-images.githubusercontent.com/11272715/78584001-dcbb0580-7837-11ea-9d96-b4256e0f81a2.png)

**Comment by 01271** [comment]
![image](https://user-images.githubusercontent.com/3951049/155570100-5ac7e86a-e1bd-4081-9100-8be21b7ed6fa.png)
![image](https://user-images.githubusercontent.com/3951049/155570323-17910d2a-8908-4c08-a8df-bb5f32b34b1e.png)

This issue has returned. My version of Godot is v3.4.stable.official [206ba70f4].

**Comment by akien-mga** [comment]
That's expected, the bug was fixed in 4.0, not in 3.4. I'll see if #37656 and its regression fix can be cherry-picked for 3.5.
