### ISSUE TITLE
WRONG supports for images largest that 4095 pixels

### ISSUE THREAD

**Issue by neos-eureka-srl** [godotengine/godot#2163]
When I try to load a Sprite Texture image largest that 4095 pixels, GoDot shows it bad, as if corruption of out-of-memory occurred.

See the attached screenshot.

PS: thanks a lot for the really GREAT WORK! :P

![screenshot](https://cloud.githubusercontent.com/assets/13015536/8303952/2005ec28-19a2-11e5-8663-8d62df706917.png)

**Comment by reduz** [comment]
most devices (low end PC, mobile) do not support textures this big. Try
creating a Large Texture (Import -> Large Texture)

**Comment by ilearain** [comment]
I use tilemap for background with big picture size, just slice the big image (in image editor by percent) then import them into godot. create new tilemap resource, add new item and fill all item with all part of image. dont forget the cell size is should be fit with image size (part size)
