### ISSUE TITLE
ProgressBar with StyleBoxFlat styles has larger minimum size than in v3.0.6

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#21633]
**Godot version:**
3.1 alpha 1

**OS/device including version:**
Ubuntu 18.04.1

**Issue description:**
Can't set `ProgressBar` `Rect Size` in the property inspector to small values. In 3.0 I could set the x and y to values as small as 0 pixels. The minimum x,y now seem to be 4 and 14. I'm using this for enemy health bar indicators. 

**Steps to reproduce:**
- Create a `ProgressBar`
- Change Fg and Bg Custom Styles to `StyleBoxFlat`
- Use the property inspector to set the `Rect Size y` property to 5 pixels. Or just try to resize the `ProgressBar` height using its handles.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

CC @bojidar-bg who modified ProgressBar in 91eb80041d588ef22926422ae2fc39f375e11aec, might be related.

**Comment by bojidar-bg** [comment]
Ensure that Percent Visible is unchecked (since it requires a minimum height for the text) and that the Styleboxes both have a minimum size of 0x0 (check the Margins section). A sample project would be helpful.

**Comment by jotson** [comment]
It is still reproducible in beta 2. I can't build master 8ff00ca... I get this error:

```
drivers/unix/os_unix_global_settings_path.gen.cpp:3:44: error: no 'String OS_Unix::get_global_settings_path() const' member function declared in class 'OS_Unix'
 String OS_Unix::get_global_settings_path() const {
                                            ^~~~~
scons: *** [drivers/unix/os_unix_global_settings_path.gen.x11.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by jotson** [comment]
Here's a sample project. I can't make the progress bar smaller than 4x14.

[test-progress-bar.zip](https://github.com/godotengine/godot/files/2793403/test-progress-bar.zip)

**Comment by akien-mga** [comment]
> `drivers/unix/os_unix_global_settings_path.gen.cpp:3:44: error: no 'String OS_Unix::get_global_settings_path() const' member function declared in class 'OS_Unix'`

Delete the `.gen.cpp` file.

**Comment by jotson** [comment]
Ok, I was able to compile master. In that build, I can set rect_size.x to 0 but rect_size.y still won't go any smaller than 14.
