### ISSUE TITLE
[Godot 3.1 Alpha1] Error when exporting to Android

### ISSUE THREAD

**Issue by homarox** [godotengine/godot#21630]
**Godot version:**

Godot_v3.1-alpha1_win64.exe

**OS/device including version:**

Window 10 | Android 7.1

**Issue description:**

--------- beginning of system
--------- beginning of main
08-31 23:41:30.126 28685 28701 I godot   : Loading module: org/godotengine/godot/GodotAdMob
08-31 23:41:30.198 28685 28701 I godot   : OpenGL ES 3.0 Renderer: Mali-T760
08-31 23:41:30.530 28685 28685 I godot   : WARNING: not found: display/driver/keep_screen_on
08-31 23:41:31.109 28685 28701 E godot   : **ERROR**: Bytecode is too New! Please use a newer engine version.
08-31 23:41:31.109 28685 28701 E godot   :    At: modules\gdscript\gdscript_tokenizer.cpp:1142:set_code_buffer() - Condition ' version > 12 ' is true. returned: ERR_INVALID_DATA
08-31 23:41:31.109 28685 28701 E godot   : **ERROR**: FATAL: Index p_index=-1 out of size (size()=0)
08-31 23:41:31.110 28685 28701 E godot   :    At: core/vector.h:147:operator[]() - FATAL: Index p_index=-1 out of size (size()=0)
--------- beginning of crash
08-31 23:41:36.036 28776 28792 I godot   : Loading module: org/godotengine/godot/GodotAdMob
08-31 23:41:36.099 28776 28792 I godot   : OpenGL ES 3.0 Renderer: Mali-T760
08-31 23:41:36.299 28776 28776 I godot   : WARNING: not found: display/driver/keep_screen_on
08-31 23:41:36.603 28776 28792 E godot   : **ERROR**: Bytecode is too New! Please use a newer engine version.
08-31 23:41:36.603 28776 28792 E godot   :    At: modules\gdscript\gdscript_tokenizer.cpp:1142:set_code_buffer() - Condition ' version > 12 ' is true. returned: ERR_INVALID_DATA
08-31 23:41:36.603 28776 28792 E godot   : **ERROR**: FATAL: Index p_index=-1 out of size (size()=0)
08-31 23:41:36.603 28776 28792 E godot   :    At: core/vector.h:147:operator[]() - FATAL: Index p_index=-1 out of size (size()=0)

**Steps to reproduce:**
Export working well with Godot 3.0.6 
Export error both release and debug
Export error both ES 2 & ES 3
**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Did you install export templates for 3.1 alpha 1? The error messages sound like what you get when using outdated export templates.

**Comment by homarox** [comment]
I have already installed it
<a href="https://ibb.co/efZxNz"><img src="https://preview.ibb.co/f5RYvK/Capture.jpg" alt="Capture" border="0"></a>

**Comment by Shin-NiL** [comment]
It seems like you're using a custom template with Admob module, you should recompile it for 3.1-alpha.

**Comment by homarox** [comment]
@Shin-NiL you are right, thanks for your help 👍
