### ISSUE TITLE
Some junk icon warnings in new project

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#21646]
**Godot version:**
3.1 Alpha

**OS/device including version:**
Windows 10

**Issue description:**
If you create and run a new project you can observe these warnings in console window..
![image](https://user-images.githubusercontent.com/3036176/44943040-a3065b00-adc7-11e8-9740-fb9dc023af14.png)

**Comment by akien-mga** [comment]
Duplicate of #21072.
