### ISSUE TITLE
Crash on refocusing text editor

### ISSUE THREAD

**Issue by FlamyAT** [godotengine/godot#21647]
**Godot version:** 
v3.0.6 upwards (tested some nightly builds / 3.1.alpha1)

**OS/device including version:** 
Windows 10 64-bit 10.0.17134 Build 17134
NVIDIA GeForce GTX 950M Version: 24.21.13.9907 (System information) - 399.07 (GeForce Experience)

**Issue description:**
The engine crashes after refocusing while the text editor is open. Shortly before the crash screen turns dark and a Windows Vista like theme is briefly visible. Running the engine via command line did not reveal any issues.
I tried reproducing on latest Ubuntu 64-bit version (date of writing 01-Sep-18). Using Linux the engine did not crash.

**Steps to reproduce:**
Open any script.
Alt-Tab to e.g. the browser.
Refocuse Godot and click on the text editor.

**Comment by akien-mga** [comment]
Do you modify project files/resources outside Godot before refocusing it?

**Comment by FlamyAT** [comment]
No, I don't.
For example, I just send a tweet via the browser and refocusing crashes it

**Comment by FlamyAT** [comment]
Closing this issue since I didn't run into this problem anymore. I also tried actively reproducing it, no result
