### ISSUE TITLE
Empty item inside "Search Classes" dialog

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#21640]
**Godot version:**
29f2571662da0ee93ea2a632ec3b60aa26246563

**Issue description:**
![screenshot at 2018-08-31 21-26-52](https://user-images.githubusercontent.com/30739239/44940426-9c92c780-ad64-11e8-87fb-15c9ee27ef9d.png)

**Comment by volzhs** [comment]
can't reproduce with f50dd682f

**Comment by akien-mga** [comment]
I can reproduce on Mageia 6 x86_64 with 6d7a8a6c.

**Comment by DualMatrix** [comment]
I tested and there is indeed an empty string in class_list
