### ISSUE TITLE
Can't Select 3D Models in Viewport

### ISSUE THREAD

**Issue by ArgentArts** [godotengine/godot#21649]
**Godot version:**
3.1 Alpha

**OS/device including version:**
Windows 10 v1803

**Issue description:**
When a 3D model is added to a scene, I cannot select it by clicking on it in the viewport. I can only select it by clicking on it in the scene tree.

**Steps to reproduce:**
Import a 3D model. Create a spacial node. Bring the model into the scene. Deselect it. Try to select it by clicking on it in the viewport.

**Comment by Ace-Dragon** [comment]
A little more detail on my end.

If the mesh instance is in the base scene (ie. having a .dae file as part of a new inherited scene). then selection works fine in select mode.

However, scene instances cannot be selected. I believe this happens to be a regression that occurred sometime back in August (as older 3.1 dev. builds had working selection/shift selection of instances).

**Comment by ArgentArts** [comment]
Some more info from me:

I've tested this with both glTF and with files exported from Blender via the Blender to Godot Exporter (.escn). As Ace-Dragon says, if I open the base scene (New Inherited Scene) then I can select the geometry just fine. But in the main scene, it is not selectable.
