### ISSUE TITLE
Failure at starting a thread returns "success"

### ISSUE THREAD

**Issue by dark-penguin** [godotengine/godot#21659]
According to the documentation, Thread.start() should return an Error enum. But it always returns 0, even if you try to start a thread with a nonexistent function and without passing mandatory userdata to it.

In the documentation, it says:
> OK = 0 — Functions that return Error return OK when no error occurred. _Most functions don’t return errors and/or just print errors to STDOUT._

But according to [this](http://docs.godotengine.org/en/latest/classes/class_thread.html?highlight=thread), Thread.start() **does** return an error.
Of course, it also prints an error to the debugger (and **not** to STDOUT!), but this does not cause an abort or anything - the program runs as if nothing happened, and even your code thinks the thread is running.

This will make it even harder to debug multithreaded code for someone.

**Comment by dark-penguin** [comment]
...This is still an issue in 3.2.2.rc.

**Comment by KoBeWi** [comment]
The problem is that the Thread checks whether object is valid and method name is not empty, but doesn't actually validate if the method can be called. It should be easy to fix in 3.x with `has_method()`, not sure about 4.0, where the method is Callable.

Although IMO the Error return is unnecessary. You get an error in the debugger, which is enough to see that something is wrong.

**Comment by dark-penguin** [comment]
Then at least the documentation should be fixed. But I would say it's not okay to return "success" on error from a function that is there specifically to check whether it's success or error. I put this check in by force of habit, and I think I didn't even check the debugger output tab, because there was nothing wrong in the output console, and I was already checking this with my code, which was telling me that everything is fine, the result was "OK".
