### ISSUE TITLE
weird spacing for displaying gl es version

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#21660]
**Godot version:**

3.1 alpha

**OS/device including version:**

nil

**Issue description:**

![default](https://user-images.githubusercontent.com/10883749/44946622-88b59700-ae32-11e8-8975-5797a8af30f8.PNG)
 The is a line in between gl and es , which I guess is to distinguish the version, IMO, the line is unnecessary, using suitable color is enough, if you insist the use of line, please improve the spacing between the line, I feel bad when looking at it... 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
That line is on the official logo: https://en.wikipedia.org/wiki/OpenGL_ES
![](https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/OpenGL_ES_logo_%28Nov14%29.svg/640px-OpenGL_ES_logo_%28Nov14%29.svg.png)

**Comment by ZX-WT** [comment]
I see,then, I think we can fix the spacing a bit. Is it now using the font glyph for the vertical line or is it vector image?

**Comment by akien-mga** [comment]
It's vector icons, see `editor/icons/icon_g_l_e_s_2.svg` and `editor/icons/icon_g_l_e_s_3.svg`.

**Comment by ZX-WT** [comment]
So I try to adjust it myself, I just tweak the spacing a bit, still crowed though and I notice that the number doesn't really align with the letter and I try to adjust it as well, still need to tweak a bit.

I think it will be better to thicken and lengthen the vertical line a bit to keep the spirit from the official logo.

![2018-09-02 15 38 37](https://user-images.githubusercontent.com/10883749/44953331-581f3d00-aec6-11e8-96d3-fbe464df422c.png)

**Comment by ZX-WT** [comment]
should the number be treated as part of ES or individual part? The current design treats it as individual.
![2018-09-02 15 54 07](https://user-images.githubusercontent.com/10883749/44953482-738b4780-aec8-11e8-97fc-183678464ac1.png)

noticed that the final result should be judge by the real size not what I shown here, the alignment looks different after zooming in and out.

**Comment by ZX-WT** [comment]
#21724

I open a pr myself for modifying the svg but I don't know how to align the icon to match the radio button, I might be a paranoid about alignment :p

![2018-09-03 19 04 16](https://user-images.githubusercontent.com/10883749/44983677-94c56400-afac-11e8-90a8-e069fb188438.png)
