### ISSUE TITLE
MonoGCHandles for resources being released

### ISSUE THREAD

**Issue by PJB3005** [godotengine/godot#21667]
**Godot version:**
3.1 Alpha 1

**OS/device including version:**
Windows 10

**Issue description:**
I ran into a bug in my game where `ResourceLoader.Load()` was returning null, but the `--verbose` log and lack of any errors (outside of my code dying on a nullref) were indicating it was fine. After compiling with debug symbols, it seems that the packed scene `MonoGCHandle`s were being released, causing the code to bail out and return a null reference when passing the packed scene resources up to my C# code.

I wasn't even touching the related code when this started breaking and, being seemingly GC related, it's pretty inconsistent to reproduce. I also doubt I'll be able to easily make a reproduction project, but Neikeq told me to make an issue so here it is.

I'm still gonna try to do some experimenting myself.

Relevant code in my project it's dying on, but it's not that useful:
```cs
protected static Godot.Control LoadScene(string path)
{
    var res = (Godot.PackedScene)Godot.ResourceLoader.Load(path);
    return (Godot.Control)res.Instance();
}
```

My theory is that it's only for the "used once then managed instance forgotten" resources like `PackedScene`. In fact that's the only case in my project I can think of where I use the objects like that.

**Comment by neikeq** [comment]
I couldn't reproduce the issue with the code snippet.

**Comment by PJB3005** [comment]
Managed to reproduce it in a tiny project.

[test.zip](https://github.com/godotengine/godot/files/2343226/test.zip)
