### ISSUE TITLE
Godot fails to import glTF2 file with NaN values

### ISSUE THREAD

**Issue by TheOnlyJoey** [godotengine/godot#21668]
**Godot version:** 3.0.6

**OS/device including version:** Ubuntu 18.04 Intel UHD 620 Mesa 18.0.5

**Issue description:** Godot fails to import this asset exported with glb from Maya. It does import in Blender correctly using the gltf2 importer.

**Steps to reproduce:** Add to project, try to open file

**Minimal reproduction project:** [DomeAssetTest.zip](https://github.com/godotengine/godot/files/2342517/DomeAssetTest.zip)

**Comment by reduz** [comment]
Support for glb exists and was tested at some point, wonder why It is not working

**Comment by capnm** [comment]
Your project contains only corrupt gltf + bin files exported from Blender. You can check / validate your glTF files online here: https://gltf-viewer.donmccurdy.com/

**Comment by TheOnlyJoey** [comment]
@capnm Incorrect, the file is exported from Maya, and can be imported in both Maya and Blender (each with its own importer) without any issues.

**Comment by capnm** [comment]
Please, as I said, test your files with https://gltf-viewer.donmccurdy.com/

```
DomeAssetTest/alphatree$ ls
 Beech_Leaf1_Bunch_Platanus_2.png          Beech_Leaf2_BranchBeech2.png.import  'Test Tree.gltf.import'
 Beech_Leaf1_Bunch_Platanus_2.png.import  'Test Tree.bin'                        Twisted_Oak_Bark_Bark2.png
 Beech_Leaf2_BranchBeech2.png             'Test Tree.gltf'                       Twisted_Oak_Bark_Bark2.png.import

godot -e
SCRIPT ERROR: : Expected 'true','false' or 'null', got 'NaN'.
   At: res://alphatree/Test Tree.gltf:83.

```

Test Tree.gltf :
```
   "asset" : {
        "generator" : "Khronos Blender glTF 2.0 exporter",
        "version" : "2.0"
    },

…

       {
            "bufferView" : 5,
            "componentType" : 5126,
            "count" : 4500,
            "max" : [
                NaN,
                NaN
            ],
            "min" : [
                NaN,
                NaN
            ],
            "type" : "VEC2"
        },

…

**Comment by TheOnlyJoey** [comment]
Why would i test something on a three.js importer? to be honest i trust the one from Blender more (both the official Khronos one and the community one, which both import the file correctly).

**Comment by capnm** [comment]
Because I has a built-in **validator**. Sorry, whatever you opened was not that from your zip file.

**Comment by TheOnlyJoey** [comment]
It is, the files, as provided in the zip, open in Blender (official and
community GLTF2 importer) and Maya.

**Comment by reduz** [comment]
Been investigating and nan/inf/etc. are clearly not valid per JSON specification. We should probably raise this to the GLTF spec.

**Comment by reduz** [comment]
Additionally, even in the GLTF spec it clearly states for binary data:
> Values of NaN, +Infinity, and -Infinity are not allowed.

**Comment by reduz** [comment]
I dont mind adding support for them in our JSON parser, but I am not sure if this would be a mistake

**Comment by capnm** [comment]
Personally, I think it would be a mistake ;-) it could only give a clearer error message.
Otherwise, you have to put workarounds in every correct JSON parser in the world:

```go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	var glft interface{}
	data := []byte(`{
            "bufferView" : 5,
            "componentType" : 5126,
            "count" : 4500,
            "max" : [
                NaN,
                NaN
            ],
            "min" : [
                NaN,
                NaN
            ],
            "type" : "VEC2"
        }`)
	if err := json.Unmarshal(data, &glft); err != nil {
		fmt.Println(err)
	}
}
```

go run main.go 
**invalid character 'N' looking for beginning of value**

**Comment by emackey** [comment]
The Khronos Blender import/export [has been corrected](https://github.com/KhronosGroup/glTF-Blender-IO/issues/22) to disallow `NaN` as per glTF spec and JSON spec.  If Maya export still has that problem, a separate issue should be filed on that project.  I think this issue can be closed, as Godot is not affected.
