### ISSUE TITLE
OS.get_static_memory_usage() don´t return real memory, stucks at 1.1GB and later return negative number.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#21677]
**Godot version:**

Godot 3.1 master at 29f2571662da0ee93ea2a632ec3b60aa26246563

**OS/device including version:**

Win 7 64 bit

**Issue description:**

Well, doing this test: https://github.com/Ranoller/Godot_crash_memory_test I find that this function: **OS.get_static_memory_usage()**, that calls **Memory::get_mem_usage()**  that returns from core\os\memory.cpp a date named **uint64_t Memory::mem_usage**... have a strange behavior:

This variable don´t actualize at the same time that real computer memory, it jumps by intervals until achieves 1.105.526 KB and later returns -2.115.684 KB... yes, a negative number! in this "jump" operating system momentarily grows godot memory use (I think that it try to give 2GB to godot) but then go to the normal allocating (use refered test to understand). The finish is godot crash at 2.2GB aprox....

Edit:

More test done and godot can allocate any amount of memory if it´s done in different arrays, since windows have certain caps and don´t allow to allocate more that about 2 GB in a single array (closes the process). I will actualize my test .... but i let the issue that is: Why OS.get_static_memory_usage() returns negative numbers....

Thanks for read.

**Steps to reproduce:**
Use refered test with **windows task manager opened** to compare real allocated memory with memory reported from godot.

**Minimal reproduction project:**

https://github.com/Ranoller/Godot_crash_memory_test

**Comment by reduz** [comment]
@RandomShaper I remember you did some changes to this code, think you could give it a check?

**Comment by RandomShaper** [comment]
I think the issue is that `OS::get_static_memory_usage` and all in that family are returning `int` (32-bit signed integer) while the core memory routines return `uint64_t`.

That makes the reported amount wrap to negative beyond 2 GiB.

That's very easy to fix, but I have no computer right now. I'll be able to do it in a few days, though.

**Comment by akien-mga** [comment]
> That's very easy to fix, but I have no computer right now. I'll be able to do it in a few days, though.

Bump ;)
