### ISSUE TITLE
SceneTree move shortcuts are not working

### ISSUE THREAD

**Issue by williamd1k0** [godotengine/godot#21671]
**Godot version:**

Godot 3.1-alpha (not applicable to 3.0)

**OS/device including version:**

Windows 10 and Manjaro 17.1

**Issue description:**

The SceneTree Move Up and Move Down shortcuts are already set but are not working.

![image](https://user-images.githubusercontent.com/10428035/44949405-d916ff80-ae06-11e8-9324-313f993d8ed2.png)

**Steps to reproduce:**
Just try to move nodes in the tree (Ctrl+Up|Down).

**Comment by avencherus** [comment]
https://github.com/godotengine/godot/issues/21171

**Comment by williamd1k0** [comment]
Oops, closing as duplicate of #17633.
