### ISSUE TITLE
[UX] Please let me double click warnings

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#21676]
**Godot version:**
3.1

**Issue description:**
As a user I want to double click on a warning to go to that script line specifically. Also, it would be nice to see the name of the file in which this warning is happening, otherwise you get many duplicated messages.

![warning-spam](https://user-images.githubusercontent.com/2206700/44951050-9af6fb80-ae59-11e8-91d3-f9b083fd1e36.PNG)

**Comment by vnen** [comment]
> Also, not using delta on _process should not be a warning.

See #21186.

**Comment by coppolaemilio** [comment]
Cool, going to remove that part
