### ISSUE TITLE
hard to create new line from a node in visual shader editor when zoom out

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#21686]
**Godot version:**

3.1 alpha

**OS/device including version:**

Win10

**Issue description:**

The visual shader editor works fine when in 1:1 ratio but when zoom out, click on any output of a node will select the node instead of creating a line, it makes it unusable after zoom out... 

**Steps to reproduce:**
zoom out in visual shader editor

**Minimal reproduction project:**

**Comment by reduz** [comment]
zoom is broken, will be fixed in 3.2 hopefully

**Comment by reduz** [comment]
maybe it should be disabled in the meantime..?

**Comment by reduz** [comment]
@akien-mga ?

**Comment by akien-mga** [comment]
Fine with me, though it likely won't ever be worked on anymore if we disable it ;)

**Comment by clofresh** [comment]
Still active in 3.2. Here is a repro case:

[bug.zip](https://github.com/godotengine/godot/files/4168196/bug.zip)

Making connections when zoomed out works on some nodes, like the Output node, but most of them don't work, like the ColorUniform node

**Comment by KoBeWi** [comment]
Still valid in 545c894

**Comment by KoBeWi** [comment]
Fixed in 3.3
