### ISSUE TITLE
Import Texture with Invert Color results in an infinite loop of errors.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21681]
My build is Windows 10, 64-bit, v3.1.alpha.custom_build.ab60283

By tinkering with the import texture settings, ticking the Invert Color option and doing a reimport results in this stream of errors that will not return control to the editor:

![godot master_2018-08-31_17-29-18](https://user-images.githubusercontent.com/13004169/44952536-00fb7700-ae8a-11e8-98bc-8d9fe8be08b0.png)
![this happens when setting invert color on import options](https://user-images.githubusercontent.com/13004169/44952537-022ca400-ae8a-11e8-90ae-e47cfa2e7e57.png)

Here is a sample project if needed:  
[Texture Option Bug.zip](https://github.com/godotengine/godot/files/2342985/Texture.Option.Bug.zip)

**Comment by akien-mga** [comment]
CC @guilhermefelipecgs
