### ISSUE TITLE
Softbody doesn't collide with plane collider (ground)

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#21688]
**Godot version:**
3.1. alpha 1 (how do I check the exact hash given I didn't build it?)

**OS/device including version:**
Win 7 x64
Radeon HD 6630M

**Issue description:**
Softbody goes through ground.

**Steps to reproduce:**
Place softbody node in scene which has a plane collider serving as ground, see it go through ground.
Mesh applied to softbody doesn't matter. Place said softbody above some other collider (e.g. box shape) and see it work properly.

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
Planes are used in 3D game design as an ultimate "bottom of the world" collider that nothing should ever go through (and that's how I'm using it in my game, there is nothing below the ground)

**Comment by eon-s** [comment]
I know that the concept of a plane is the ideal for this kind of use, but the physics engine do not like it.
See (or remember) #17893 .

**Comment by Chaosus** [comment]
As stated in #17893 there should been Quad physic shape support instead. Closed as supersede by #17893.
