### ISSUE TITLE
Best C++ Code Comment Syntax to use

### ISSUE THREAD

**Issue by Cradmon** [godotengine/godot#21696]
There are two types of comment syntax:
`// This is a comment.` and `/* This is a comment. */`

**Issue:** My issue is to define a level of abstraction between the two styles, such that as I update comments during refactoring, I can maintain a consistent style.

**Proposal:** My proposal is to use `/* */` style comments for indicating markdown type comments and `//` style for code describing comments.
Markdown type comments: `clang-format`, `LICENCE`, `Section Header` etc.
Code describing comments: `TODO`, `Explaining code`, `Commenting out some code` etc.

Here's an example:
```
/*         *
 * LICENCE *
 *         */

/* Section Header 1 */

void H1Func() {
    /* clang-format off */
    // Write function here
    /* clang-format on */
}

void H1Func2() { // Single line func }

/* Section Header 2 */

void H2Func() {
    // Write
    // function
    // here
}
```

**Feedback:**
Would this type of abstraction in comments be useful?
Are there improvements that could be made?
Are there any potential problems with the proposal?

**Comment by Maykeye** [comment]
What problem it solves other than dividing comments into arbitrary categories? 

Also I don't understand why explaining the code is low level comment and clang-format is high level comment. Shouldn't it be vice versa? Because clang is just a tool and `clang-format on` is not useful for human  reader while explanation of algorithm is

Honestly seems more confusing than useful.

**Comment by Cradmon** [comment]
The problem I'm trying to address is one where the file being refactored has made use of both styles of comment (`//` and `/* */`) based on preference.

By using a more systematic approach, I'm hoping to provide some basic structure to the comments. This structure could for example:
- Allow the reader to search through the file from section to section.
- Help visually separate comments that are to do with the code and those that are essentially markdown.

The high level and low level labels are misleading, I've changed them to be a bit clearer, hopefully...

I didn't know about the `#if 0/#endif` uses. From my understanding most of these uses are for commenting out a block of code, but keeping it there for reference. So they'd probably remain the same, until they can be safely removed. If they are valid comments that describe code etc. they could be converted (This is the grey area that is slightly problematic).

**Comment by Calinou** [comment]
Closing due to lack of support. Note that in general, we tend to favor inline comments over doc-block comments. That said, using Javadoc-style comments in source files is considered acceptable in some cases: https://github.com/godotengine/godot/pull/35521
