### ISSUE TITLE
Issue with rendering alpha at low angles

### ISSUE THREAD

**Issue by dark-penguin** [godotengine/godot#21690]
Is this a bug or an issue I don't know about due to my n00bliness in 3D graphics? :)

Here is my favorite testing cube from #21685 (you're welcome to take that script, add alpha material and see for yourself). With opaque material (transparency set to false), it looks good:
![opaque](https://user-images.githubusercontent.com/16963337/44955438-ffe33d80-aebb-11e8-88d3-f60b315933db.png)
With transparent material and alpha = 0.01, it looks perfect:
![alpha001](https://user-images.githubusercontent.com/16963337/44955489-d24ac400-aebc-11e8-83ce-8d2f55ca4e73.png)
With alpha = 0.1, it looks great:
![alpha01](https://user-images.githubusercontent.com/16963337/44955492-e68ec100-aebc-11e8-8fd9-c449771b15ce.png)
With alpha = 1, which should be completely opaque, it looks like this:
![alpha1](https://user-images.githubusercontent.com/16963337/44955507-04f4bc80-aebd-11e8-8f3d-fac3a5c82410.png)
Actually, I think this happens with any alpha, but only becomes noticeable at around 0.3 .
This only happens when you look in a direction almost parallel to those cubes; turn camera a little, and the effect disappears.
This behavior is present in Godot 3.0 stable and Godot master, on Linux and on Windows, on GLES2 and GLES3.

**Comment by CptPotato** [comment]
Sounds like a z-sorting thing to me again (there already were a number of similar issues).

To keep it short: I don't think this behavior is wrong.

Rendering with transperency has limitations. The main one being drawing order. Drawing back to front is the correct way but sorting it correctly is not always possible.

If you're using a single mesh the drawing order is fixed and defined by the order of polygons in your mesh. If you're using multiple meshes the engine sorts them (back to front) which works well for nicely separated meshes with transparency.

Other than that you'll always have to fight with these kind of artifacts.

**Comment by dark-penguin** [comment]
So it is not a "bug", but an "unsolvable feature of 3D graphics", as I thought!

Hmmmm... So then, it would help if I used a MultiMesh instead? Then everything would become one mesh, drawn in one draw call, and ordered by polygons and not meshes?

I tried it. No, it did not help. MultiMesh seems to have its own method of Z-sorting, which produces slightly different, but mostly similar results.

I also tried "separating them nicely" (reduced the size of each building block a little to make them separate). That didn't help, either.

**Comment by CptPotato** [comment]
The optimal case would be using mostly opaque objects in your scene and having little transparent ones here and there when needed. The further they are apart (and the more simple their geometry) the less likely z-sorting is going to fail.

**Comment by dark-penguin** [comment]
Generally, I will do that. In real life, too many transparent objects would be too hard to render, anyway. In this case, I wanted to visualize a 3D array, being able to see every block at once.

**Comment by dark-penguin** [comment]
In Godot master with GLES2, the same thing happens even with opaque cubes (transparent = false). I don't know what does that tell us though...

**Comment by CptPotato** [comment]
Strange... so it might be related to something different after all.

**Comment by dark-penguin** [comment]
I am certainly no expert in this area, especially in math, but I struggle to imagine how can Z-ordering two opaque polygons be much different from Z-ordering two transparent polygons or cubes, especially when they share two vertices, and one of them goes towards the camera, and the other goes away from the camera.

Maybe this was fixed in the opaque ordering algorithm, but missed in transparent ordering mechanism? Since those are different, someone may not have thought to implement some fix in both places, or something like that...

**Comment by CptPotato** [comment]
Opaque rendering is different as it's checking against a depth buffer. So even if the drawing order is random it shouldn't cause these artifacts.

**Comment by Calinou** [comment]
Can this still be reproduced with *opaque* materials in the GLES2 renderer in [3.2 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4)? (The issue with *transparent* materials is likely impossible to solve in a low-end renderer.

**Comment by dark-penguin** [comment]
> Can this still be reproduced with _opaque_ materials in the GLES2 renderer in [3.2 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4)?
I will check that in a few days.
> (The issue with _transparent_ materials is likely impossible to solve in a low-end renderer.)
Does that mean it would be possible to solve with a _high-end_ renderer like maybe GLES3 or Vulkan? ^_^

**Comment by Calinou** [comment]
@dark-penguin I don't think so either, as fixing it requires implementing order-independent transparency. This is very slow (often too slow to be usable in a game).

**Comment by dark-penguin** [comment]
I've checked it. I think I must have done something wrong; with `transparent=false`, I can't reproduce the problem on either 3.0, 3.1-stable or 3.2-beta4 , even with GLES2. With `transparent=true` and alpha=1, the problem is there - as it should be.

I guess we can close this as "impossible" - opaques work, and transparents aren't supposed to.

**Comment by clayjohn** [comment]
The proper solution would be for you to manually sort using render priority. 

As far as the engine goes, yes it is impossible for us to solve this problem at an engine level unfortunately. 

Thanks for revisiting the issue and confirming the problem. Sorry that we couldn't come to a better solution :)

**Comment by dark-penguin** [comment]
Oh, I did not know there was such a thing as assigning the render priority!.. So there _is_ a "best solution we have" after all. :) Thank you, I'll look into that!
