### ISSUE TITLE
Missing description in the documentation for Array.append() function

### ISSUE THREAD

**Issue by set-killer** [godotengine/godot#2169]
On this wiki page:
https://github.com/okamstudio/godot/wiki/class_array

there is link for the **append** function, but no description available.
Also there is no description in Godot Help screen - Array class description.

Sorry if this issue duplicates another one.

**Comment by set-killer** [comment]
If Array.append() is going to be deprecated, please delete this issue...

**Comment by WalasPrime** [comment]
I don't think it's going to be deprecated. The description is just not there, and since we don't have access to the wiki editing there's not much we can do (as a community).

**Comment by rdcklinux** [comment]
append add an item as last item on the list

**Comment by akien-mga** [comment]
Array:.append is now described in the in-editor help, and the API reference on OpenProject will soon be updated based on the current source code. The GH reference is outdated and will be removed.
