### ISSUE TITLE
Open scenes in editor_layout.cfg are not removed if they cannot be loaded

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#21704]
**Godot version:** 3.1alpha 19d7589

**Issue description:** With the interface option `restore_scenes_on_load` set to true, have a scene opened in the scene dock and close Godot. Manually delete the .tscn. Whenever Godot will be started, the error message "Can't open scene.tscn. The file could have been moved or deleted." will appear. This cannot be fixed unless editor_layout.cfg is edited or the scene is recreated and manually removed from the scene dock.

Probably related to #21703, it seems like  the scene dock doesn't save on closing.

**Comment by KoBeWi** [comment]
I did some testing and seems like when you finally save the settings (i.e. by opening a scene), the problem is resolved. So the actual problem is settings not being saved, like in linked issue.

**Comment by isaacremnant** [comment]
You're right, this changed some time this year. The scenes are removed from the config file on saving the settings, so I'll close this issue.
