### ISSUE TITLE
godot --gdnative-generate-json-api godot_api.json generates incorrect bindings for default values

### ISSUE THREAD

**Issue by Acclution** [godotengine/godot#21702]
**Godot version:**
3.1.alpha.custom_build.a1019c2 (master branch)

**OS/device including version:**
Arch Linux 64bit

**Issue description:**
I am scripting with C++ using godot-cpp. I am using a KinematicBody2D in my scene and I am trying to move it around with move_and_collide. This will crash in a callback some ware (can't remember where). I looked in the generated godot_api.json for KinematicBody2D move_and_collide and it seems like it have not generated correctly.

```
"name": "move_and_collide",
"return_type": "KinematicCollision2D",
"is_editor": false,
"is_noscript": false,
"is_const": false,
"is_reverse": false,
"is_virtual": false,
"has_varargs": false,
"is_from_script": false,
"arguments": [
	{
		"name": "rel_vec",
		"type": "Vector2",
		"has_default_value": false,
		"default_value": ""
	}
]
```

I think it should have generated like this:
```
"name": "move_and_collide",
"return_type": "KinematicCollision2D",
"is_editor": false,
"is_noscript": false,
"is_const": false,
"is_reverse": false,
"is_virtual": false,
"has_varargs": false,
"is_from_script": false,
"arguments": [
	{
		"name": "rel_vec",
		"type": "Vector2",
		"has_default_value": false,
		"default_value": ""
	},
	{
		"name": "infinite_inertia",
		"type": "bool",
		"has_default_value": true,
		"default_value": "true"
	},
	{
		"name": "exclude_raycast_shapes",
		"type": "bool",
		"has_default_value": true,
		"default_value": "true"
	},
	{
		"name": "test_only",
		"type": "bool",
		"has_default_value": true,
		"default_value": "false"
	}
]
```

I changed the godot_api.json to the above and my code works now.
Is it something wrong with the generator and default values?

**Steps to reproduce:**
get godot source, build editor, generate api then find KinematicCollision2D and compare.
```
git clone https://github.com/godotengine/godot.git
cd godot
scons p=x11 use_llvm=yes target=debug tools=yes -j 4
bin/godot.x11.opt.tools.64.llvm --gdnative-generate-json-api godot_api.json
```

**Comment by akien-mga** [comment]
It is generated correctly for me (with the "should have" snippet you gave) in 19d57894d.

But you're running the wrong binary:
```
scons p=x11 use_llvm=yes target=debug tools=yes -j 4
bin/godot.x11.opt.tools.64.llvm --gdnative-generate-json-api godot_api.json
```
"opt" is for `target=release_debug`, so your new binary should be `godot.x11.tools.64.llvm`.
