### ISSUE TITLE
Godot crash writing  Array.empty() in a Script if the array was declared in the function parameters and is empty.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#21700]
**Godot version:**

29f2571662da0ee93ea2a632ec3b60aa26246563

**OS/device including version:**

Win 7

**Issue description:**

Godot crash if you write this code in a script:

```
func godot_crash (FirstArray = [], SecondArray = []):
    if SecondArray.empty():
         return true
    else:
         return false
```

The test is "write" this function, not copy paste.  At the point that autocomplete jumps to help you to write ".empty" ... godot closes.

**Comment by akien-mga** [comment]
CC @vnen
