### ISSUE TITLE
New scenes are not saved to editor_layout.cfg

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#21703]
**Godot version:** 3.1alpha 19d7589

**Issue description:** With the interface option `restore_scenes_on_load` set to true, create a new scene and save it, keep it opened in the scene dock and close Godot. On restarting, the scene is no longer in the scene dock.

It seems that Godot doesn't save to `editor_layout.cfg` on creating/saving a new scene so the scene will stay in the dock only if it is manually opened.

**Comment by akien-mga** [comment]
Open saves are not saved anywhere unless you use the option `interface/scene_tabs/restore_scenes_on_load` - do you? If so it's worth mentioning in related bug reports :)

**Comment by isaacremnant** [comment]
@akien-mga Sorry, totally forgot this wasn't on by default!
