### ISSUE TITLE
valgrind errors of incorrect data access  in MeshDataTool

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#21713]
==3135== Invalid read of size 4
==3135==    at 0x1B7DECC: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:117)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==  Address 0x3394e1b0 is 16 bytes inside a block of size 240,992 free'd
==3135==    at 0x4C2DDBB: free (vg_replace_malloc.c:530)
==3135==    by 0x46E1BD: PoolVector<float>::_unreference() (dvector.h:246)
==3135==    by 0x1B7E57B: ~PoolVector (dvector.h:469)
==3135==    by 0x1B7E57B: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:84)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==  Block was alloc'd at
==3135==    at 0x4C2CB8F: malloc (vg_replace_malloc.c:299)
==3135==    by 0x239FFD1: Memory::alloc_static(unsigned long, bool) (memory.cpp:83)
==3135==    by 0x67142A: PoolVector<float>::resize(int) (dvector.h:577)
==3135==    by 0x230376F: _convert_array<PoolVector<float>, PoolVector<int> > (variant.cpp:1769)
==3135==    by 0x230376F: PoolVector<float> _convert_array_from_variant<PoolVector<float> >(Variant const&) (variant.cpp:1791)
==3135==    by 0x22FD02C: Variant::operator PoolVector<float>() const (variant.cpp:1841)
==3135==    by 0x1B7E53A: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:84)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135== 
==3135== Invalid read of size 4
==3135==    at 0x1B7DEF1: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:118)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==  Address 0x3394e1b4 is 20 bytes inside a block of size 240,992 free'd
==3135==    at 0x4C2DDBB: free (vg_replace_malloc.c:530)
==3135==    by 0x46E1BD: PoolVector<float>::_unreference() (dvector.h:246)
==3135==    by 0x1B7E57B: ~PoolVector (dvector.h:469)
==3135==    by 0x1B7E57B: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:84)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==  Block was alloc'd at
==3135==    at 0x4C2CB8F: malloc (vg_replace_malloc.c:299)
==3135==    by 0x239FFD1: Memory::alloc_static(unsigned long, bool) (memory.cpp:83)
==3135==    by 0x67142A: PoolVector<float>::resize(int) (dvector.h:577)
==3135==    by 0x230376F: _convert_array<PoolVector<float>, PoolVector<int> > (variant.cpp:1769)
==3135==    by 0x230376F: PoolVector<float> _convert_array_from_variant<PoolVector<float> >(Variant const&) (variant.cpp:1791)
==3135==    by 0x22FD02C: Variant::operator PoolVector<float>() const (variant.cpp:1841)
==3135==    by 0x1B7E53A: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:84)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135== 
==3135== Invalid read of size 4
==3135==    at 0x1B7DF12: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:119)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==  Address 0x3394e1b8 is 24 bytes inside a block of size 240,992 free'd
==3135==    at 0x4C2DDBB: free (vg_replace_malloc.c:530)
==3135==    by 0x46E1BD: PoolVector<float>::_unreference() (dvector.h:246)
==3135==    by 0x1B7E57B: ~PoolVector (dvector.h:469)
==3135==    by 0x1B7E57B: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:84)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==  Block was alloc'd at
==3135==    at 0x4C2CB8F: malloc (vg_replace_malloc.c:299)
==3135==    by 0x239FFD1: Memory::alloc_static(unsigned long, bool) (memory.cpp:83)
==3135==    by 0x67142A: PoolVector<float>::resize(int) (dvector.h:577)
==3135==    by 0x230376F: _convert_array<PoolVector<float>, PoolVector<int> > (variant.cpp:1769)
==3135==    by 0x230376F: PoolVector<float> _convert_array_from_variant<PoolVector<float> >(Variant const&) (variant.cpp:1791)
==3135==    by 0x22FD02C: Variant::operator PoolVector<float>() const (variant.cpp:1841)
==3135==    by 0x1B7E53A: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:84)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135== 
==3135== Invalid read of size 4
==3135==    at 0x1B7DF37: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:120)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==  Address 0x3394e1bc is 28 bytes inside a block of size 240,992 free'd
==3135==    at 0x4C2DDBB: free (vg_replace_malloc.c:530)
==3135==    by 0x46E1BD: PoolVector<float>::_unreference() (dvector.h:246)
==3135==    by 0x1B7E57B: ~PoolVector (dvector.h:469)
==3135==    by 0x1B7E57B: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:84)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==  Block was alloc'd at
==3135==    at 0x4C2CB8F: malloc (vg_replace_malloc.c:299)
==3135==    by 0x239FFD1: Memory::alloc_static(unsigned long, bool) (memory.cpp:83)
==3135==    by 0x67142A: PoolVector<float>::resize(int) (dvector.h:577)
==3135==    by 0x230376F: _convert_array<PoolVector<float>, PoolVector<int> > (variant.cpp:1769)
==3135==    by 0x230376F: PoolVector<float> _convert_array_from_variant<PoolVector<float> >(Variant const&) (variant.cpp:1791)
==3135==    by 0x22FD02C: Variant::operator PoolVector<float>() const (variant.cpp:1841)
==3135==    by 0x1B7E53A: MeshDataTool::create_from_surface(Ref<ArrayMesh> const&, int) (mesh_data_tool.cpp:84)
==3135==    by 0x1B873A1: MethodBind2R<Error, Ref<ArrayMesh> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1608)
==3135==    by 0x226387C: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:968)
==3135==    by 0x2305C4F: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1049)
==3135==    by 0x433002: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1069)
==3135==    by 0x3CF61C: GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (gdscript.cpp:1161)
==3135==    by 0x2263A8B: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:947)
==3135== 

Enjoy.

**Comment by reduz** [comment]
Anyone volunteering to fix those?
