### ISSUE TITLE
Tileset Editor: Alternative Collision/Occlusion Shapes (and associated usability)

### ISSUE THREAD

**Issue by vpellen** [godotengine/godot#21712]
The new Tileset Editor is a wonderful tool, but still has the issue of requiring collision and occlusion shapes to be specified individually via polygon drawing. Even leaving aside the potential performance issues of using large numbers of convex polygons in cases where simple circle or square shapes would suffice (admittedly because I don't know how the engine chooses to optimize this), actually placing such shapes is an awkward mess. I propose the following:

- Allowing the user to specify box and circle shapes for tile collision and occlusion
- The ability to copy and paste colliders between tiles (although if the ability to place colliders is fast enough this may cease to be a major issue)

**Comment by sian2005** [comment]
The ability to copy and paste tile collision masks in the TileSet Editor is something I really wish Godot already had...

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/896, https://github.com/godotengine/godot-proposals/issues/648, https://github.com/godotengine/godot-proposals/issues/265 and https://github.com/godotengine/godot-proposals/issues/574, as feature proposals are now tracked in the Godot proposals repository.
