### ISSUE TITLE
BitmapFont resource leak?

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#21718]
**Godot version:**
3.1a1

**OS/device including version:**
Windows 10 x64
GTX750/PCIe/SSE2

**Issue description:**
Sorry if this bug is very general.  Over the last week or so, my project had been taking longer and longer to build.  Over time, I thought I was having an issue similar to #20566 , but after a while I found the actual culprit:
![image](https://user-images.githubusercontent.com/1023003/44969726-161ce800-af14-11e8-85e0-ed502b98baa6.png)

Somehow, this file ballooned in size!  Unable to open it in anything but a hex editor, I saw the problem was with the `textures` key.  It specified something like `textures = [ ExtResource( 1 ), ExtResource( 1 ), ... ]` over and over again.  I nuked this key and everything started to work again as normal.  

**Steps to reproduce:**
I'm afraid I haven't figured out the culprit, as I've so far been unable to get this to happen again.  Will update the issue if I can figure out what happened.

Attached is the resource file and the font itself for reference.

[font - Copy.txt](https://github.com/godotengine/godot/files/2344365/font.-.Copy.txt)
![spelunkid_font](https://user-images.githubusercontent.com/1023003/44970202-246c0380-af16-11e8-828d-fe7c995c826b.png)

**Comment by nobuyukinyuu** [comment]
First update:  Each successive run of the game ("Play" / F5) adds another `ExtResource( 1 )` to the key.  This doesn't seem to be dependent on the amount of times the .tres file has been manually altered to reduce the number of values to 1.  This suggests the editor process is keeping a tally internally.  Something in the re-importer?

Setting the offending file to read-only seems to stop the problem.  Will update again if the problem "moves" to another file in the project.

**Comment by nobuyukinyuu** [comment]
Update 2:  Confirmed to be happening sporadically in a minimal reproduction project.  Resource started to have issues when closing to project list and re-opening and running again.  Console log:
```
WARNING: load: Loaded resource as image file, this will not work on export: 'res://icon.png'. Instead, import the image file as an Image resource and load it normally as a resource.
     At: core/image.cpp:1734
OpenGL ES 3.0 Renderer: GeForce GTX 750/PCIe/SSE2
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2081
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:70
Editing project: C:/Users/zzz/Documents/MinimalCamBug (C:::Users::zzz::Documents::MinimalCamBug)
OpenGL ES 3.0 Renderer: GeForce GTX 750/PCIe/SSE2
erasing C:\Users\zzz\AppData\Roaming/Godot/projects/MinimalCamBug-664acf0ea78745e6ce63fef41329ba69/filesystem_update4
Running: D:\Projects\godot\godot.exe --path C:/Users/zzz/Documents/MinimalCamBug --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 16360 --debug-collisions --position 288,150
OpenGL ES 3.0 Renderer: GeForce GTX 750/PCIe/SSE2
WARNING: load: Loaded resource as image file, this will not work on export: 'res://icon.png'. Instead, import the image file as an Image resource and load it normally as a resource.
     At: core/image.cpp:1734
OpenGL ES 3.0 Renderer: GeForce GTX 750/PCIe/SSE2
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2081
Editing project: C:/Users/zzz/Documents/MinimalCamBug (C:::Users::zzz::Documents::MinimalCamBug)
OpenGL ES 3.0 Renderer: GeForce GTX 750/PCIe/SSE2
erasing C:\Users\zzz\AppData\Roaming/Godot/projects/MinimalCamBug-664acf0ea78745e6ce63fef41329ba69/filesystem_update4
Running: D:\Projects\godot\godot.exe --path C:/Users/zzz/Documents/MinimalCamBug --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 5324 --debug-collisions --position 288,150
```

I'm assuming the problem happens during the re-import process somewhere.

Attached is a minimal reproduction project.  Sorry about the project folder name;  I re-used it from a previous (unrelated) bug report.  Please let me know if anyone can confirm having the same or a similar issue.
[ResourceLeak.zip](https://github.com/godotengine/godot/files/2346500/ResourceLeak.zip)

**Comment by akien-mga** [comment]
I can confirm the bug with the attached project, the `art/font.tres` file grows in size exponentially the first time the game is ran in a newly opened editor.

To clarify reproduction steps:
- Check file size
- Open project 1st time
  - Run game
  - Check file size: increases after starting the game
  - Run game
  - Check file size: no increase
  - Repeat ad lib: no increase
- Close project
- Open project 2nd time
  - Run game
  - Check file size: increased again
  - Run game
  - Check file size: no increase
  - Repeat ad lib: no increase
- And so on and so forth

**Comment by reduz** [comment]
anyone willing to investigate? Valgrind can be a useful tool.

**Comment by LittleWhite-tb** [comment]
Hello,
I am able to reproduce the bug. I will try to fix it.
