### ISSUE TITLE
Ctrl+Drag to rotate collides with Ctrl+Click to add point in Path2D

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#2171]
Ctrl+Drag to rotate node,
Ctrl+Click to add point in Path2D.

They collide with each other, so when you want to rotate path2d node you add a new point instead, which is quite annoying.

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by Krzycho666** [comment]
It looks like it was fixed.

**Comment by akien-mga** [comment]
Great, thanks!
