### ISSUE TITLE
RigidBody: apply_torque and waiting -> object disappears and stream of Errors

### ISSUE THREAD

**Issue by gitnob** [godotengine/godot#21722]
**Godot version:**
3.0.6-stable (official download and compiled from sources)

**OS/device including version:**
Linux - Debian (GeForce GTX 1060 /w nvidia drivers)

**Issue description:**
Using a RigidBody object with Godotphysics server.
A RigidBody object vanishes after a while when the rotation applied via torque or impulse is damped. A stream of errors is on the command line and in the debugger area of the Godot editor.
Errors are always about a determinant which is 0.0:
ERROR: set_axis_angle: Condition ' p_axis.is_normalized() == false ' is true.
   At: core/math/matrix3.cpp:751.
or in consequence... 
ERROR: set_axis_angle: Condition ' p_axis.is_normalized() == false ' is true.
   At: core/math/matrix3.cpp:751.

Suggestion: It seems to be issued while damping of the rotation of a rigid body object

I'm lost, because I can't debug to find the error origin.

An adequate script with 2.1.5 worked fine, but with apply_impulse() calls from within _process() function.

**Steps to reproduce:**
1. Unzip attached file

2. Open in editor or directly as a game with Godot 3.0.6

3. rotate rigid_body object with "a", "d" and/or arrow buttons AND wait some time (on my computer it was about 10-20s) without pressing any button 
---> visible rigid_body object vanishes and several errors appear: 
"Condition ' determinant() == 0 ' is true" and similar et.al. see above

4. restart the game and move the rigid body object ONLY with "w" and "s" (forward/backward) AND 
wait some time 
---> everything OK
but as soon as you rotated the object, see topic 3.

**Minimal reproduction project:**
[showRigidBodyProblem.zip](https://github.com/godotengine/godot/files/2345113/showRigidBodyProblem.zip)

All in all, strange.... probably a bug in physics engine?

**Comment by KoBeWi** [comment]
Still valid in 3.2.3 rc3, but the error is different (something about Vector3 must be normalized).

**Comment by madmiraal** [comment]
Fixed with #41879 which was [cherry-picked](https://github.com/godotengine/godot/pull/41879#issuecomment-688852280) for 3.2.3.
