### ISSUE TITLE
Autocomplete is inaccurate due to alphabetical sorting of suggestions

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#21726]
Basically this:
![image](https://user-images.githubusercontent.com/2223172/44985061-3cc43880-af7f-11e8-9a77-881852ac1781.png)
I wanted to autocomplete Vector3, but writing Vec3 suggests me PoolVector3Array. This happens when you write letters in different order (in example above I'm skipping "tor"). Autocomplete ignores how you started writing a word and sorts everything alphabetically. I'd expect it to actually select Vector3 in above case.

Another example:
![image](https://user-images.githubusercontent.com/2223172/44985528-f53eac00-af80-11e8-8840-ec165f1b63af.png)
Actually for this one writing "minf" would work, but still, autocomplete could better predict what I'd like to write. I doubt anyone would start RemoteTransform this way.

Tested in 3.1 alpha.

For comparison, here are VS Code results for these completions:
![image](https://user-images.githubusercontent.com/2223172/44985814-f15f5980-af81-11e8-9051-e2eb48e267cd.png)
![image](https://user-images.githubusercontent.com/2223172/44985825-f7edd100-af81-11e8-85af-12c52e7d4d48.png)
(btw, see how VS Code highlights actual written letters, rather than just the beginning of the suggested words like it is in Godot. But I suppose I could create separate issue for that)

**Comment by rokasv** [comment]
`Vec3` into `PoolVector3Array` is excruciatingly painful

**Comment by KoBeWi** [comment]
Yeah, the linked PR fixes it, but adds some more stuff that made it too big, so it's not merged yet :/

**Comment by rokasv** [comment]
Just realized this is not marked as a bug. 
That's a shame, since the code editor and export features are the only thing I use in the engine. 😞

**Comment by me2beats** [comment]
Still in 3.2.3
Why not a bug tho?

![needless results](https://user-images.githubusercontent.com/16458555/107846486-ede48380-6e05-11eb-98ee-684f34fc8dfd.png)
![needless2](https://user-images.githubusercontent.com/16458555/107846493-f9d04580-6e05-11eb-81bc-cf819e80b597.png)

As you can see, completion suggests superfluous results.

this is quite annoying and slows down the scripting.

**Comment by Calinou** [comment]
> Why not a bug tho?

It's working less than ideally, but it's technically working as intended.

**Comment by KoBeWi** [comment]
Closing in favor of this proposal: https://github.com/godotengine/godot-proposals/issues/4189
