### ISSUE TITLE
Changing custom cursor position on Linux can crash without errors.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21721]
**Using a 64-bit build on Ubuntu 18.04.1 LTS with v3.1.alpha.custom_build.6ead007.**

When trying to set the cursor position with `Input.set_custom_mouse_cursor(texture, cursor, position)` and the position exceeds some distance, it will crash without any useful information, unless I'm overlooking something.

A sample project to demo this:  [Moving Cursor Bug.zip](https://github.com/godotengine/godot/files/2344962/Moving.Cursor.Bug.zip)

@guilhermefelipecgs Hoping you may have some insight into this one.

_Works fine on Windows 10 as far as I can tell._

**Comment by guilhermefelipecgs** [comment]
It's seems on Linux we can't create a position (hotspot) bigger than the image size.
```
typedef struct _XcursorImage {
        XcursorDim    size;        /* nominal size for matching */
        XcursorDim    width;        /* actual width */
        XcursorDim    height;        /* actual height */
        XcursorDim    xhot;        /* hot spot x (must be inside image) */
        XcursorDim    yhot;       /* hot spot y (must be inside image) */
        XcursorPixel    *pixels;    /* pointer to pixels */
    } XcursorImage;
```

**Comment by capnm** [comment]
still crashes for negative values ;-)
        print(x)
        Input.set_custom_mouse_cursor(icon, 0, Vector2(x, x))

```
0.936904
0.313949
-0.313956
-0.93691
-1.545089
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  27 (RenderCreateCursor)
  Serial number of failed request:  401
  Current serial number in output stream:  404
```

**Comment by avencherus** [comment]
@capnm Nice catch, just noticed this on a retest.  Next time I rebuild I'll triple check.  Any insight into why the hotspot is so finicky for Linux?

**Comment by capnm** [comment]
Not really, but it makes sense to me that it shouldn't be outside the cursor shape.
