### ISSUE TITLE
Ability to flip horizontally or vertically TextureRect

### ISSUE THREAD

**Issue by salvob41** [godotengine/godot#21729]
Wouldn't be useful having the option to flip a textureRect ? Since it is a Control Node and it can be very useful in creating UI, but there is no way at all to flip the Node (unless you use rect_scale , but this does not work when inside Containers like HBOX or VBOX)

What do you guys think about it?

**Comment by Chaosus** [comment]
I think its good idea, it could be implemented but not now, cuz we are at the feature freeze state

**Comment by Xrayez** [comment]
If the reason to flip `TextureRect` is a need to fix upside-down rendering issue with `ViewportTexture`, then a `Viewport` has `render_target_v_flip` property for that, in case someone stumbles upon with a similar issue not related to this feature proposal.
