### ISSUE TITLE
Segfault on VirtualBox with VBoxGuestAdditions' libGL

### ISSUE THREAD

**Issue by Wend1go** [godotengine/godot#21728]
**Godot version:**

Godot_v3.1-alpha1_x11.64

**OS/device including version:**

Linux Mint 18.3 Mate 64bit guest on Windows10 Professional 64Bit host via Virtualbox 5.2.16

**Issue description:**

Upon running the IDE the following error is displayed on the console and the IDE doesn't start:
```
$ ./Godot_v3.1-alpha1_x11.64
ERROR: initialize: Condition ' !glXCreateContextAttribsARB ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:93.
OpenGL Error: No context.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fe01b72c4b0] (??:0)
[2] /var/lib/VBoxGuestAdditions/lib/libGL.so.1(+0x2a489) [0x7fe01bb66489] (??:0)
[3] ./Godot_v3.1-alpha1_x11.64() [0xee5288] (<artificial>:?)
[4] ./Godot_v3.1-alpha1_x11.64() [0xfa5c2f] (<artificial>:?)
[5] ./Godot_v3.1-alpha1_x11.64() [0x79f4fa] (??:?)
[6] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fe01b717830] (??:0)
[7] ./Godot_v3.1-alpha1_x11.64() [0x7a8a0e] (??:?)
-- END OF BACKTRACE --
Aborted (Speicherabzug geschrieben)
```
Same when running godot with "--video-driver GLES2" parameter.

**Steps to reproduce:**
Download Godot v3.1 alpha1, extract it and run it via bash.

**Comment by akien-mga** [comment]
Last I tried, VirtualBox's libGL isn't nearly usable enough for OpenGL 2+ applications, so that's more or less expected.

It would be nice if it failed gracefully instead of segfaulting though.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.2 or a 4.0 dev build?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/40370, which tracks current rendering issues when using VirtualBox's OpenGL acceleration.
