### ISSUE TITLE
get_real_window_size() is a frame behind on Linux builds.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21720]
I had this issue with a 64-bit build on Ubuntu 18.04.1 LTS with v3.1.alpha.custom_build.6ead007

_It is working fine on Windows 10._

It seems that when you use `OS.window_size` it won't be until the next frame that `get_real_window_size()` will have the new window size.

Sample project: [Delay Window Info Bug.zip](https://github.com/godotengine/godot/files/2344927/Delay.Window.Info.Bug.zip)

**Comment by avencherus** [comment]
Oh yeah, looking back on those display issues, this might be related, and maybe goes deeper.

I saw that https://github.com/godotengine/godot/pull/16648 was when the function was added.  So it wasn't in 2.1.5 at least, but maybe was manifesting in the other window size queries.  I remember having to do a lot of awkward yields even on Windows back then for various things.

**Comment by akien-mga** [comment]
> I saw that #16648 was when the function was added. So it wasn't in 2.1.5 at least, but maybe was manifesting in the other window size queries. I remember having to do a lot of awkward yields even on Windows back then for various things.

It was actually included in 2.1.5 too with #13930.

**Comment by avencherus** [comment]
Oh I totally missed it when it came out, I didn't make use of it in the 2.1.5 project.

Also thanks for these corrections, still a Git rookie and it helps me get oriented.  That was twice I missed the link right next to something.  Was quite exhausted though, and was tunneling all my remaining resources in on making sure my first pull request was done correctly.  XD

There are several more issues that I'm fiddling with at the moment with the user experience end of things.  If anything else related to this appears, I'll tack it on.

**Comment by avencherus** [comment]
That would be unfortunate.

Currently, working around it by introducing a two frame delay after any window changing stuff.

```
const X11_DELAY_FRAMES = 2
```
...
```
OS.window_size = new_size()

if(OS.get_name() == "X11"):
	for i in range(X11_DELAY_FRAMES): 
		yield(get_tree(), "idle_frame")

OS.center_window()
```
Hopefully there is a backend solution, because I can't imagine it very safe to introduce yield/co-routines to it.
