### ISSUE TITLE
CSGMesh using ArrayMesh with multiple materials fails to assign materials to surfaces correctly

### ISSUE THREAD

**Issue by clarkejm** [godotengine/godot#21739]
**Godot version:**

v3.1.alpha.official

**OS/device including version:**

Windows 10 Pro v1803 17134.254
Lenovo Yoga P40
NVIDIA Quadro M500M Driver 24.21.13.9836

**Issue description:**

Using a CSGMesh object, assigned the mesh to an existing ArrayMesh containing a multiple surface & materials. CSGMesh appears to have surfaces missing material assignment as well as other visual artifacts (rightmost object). 
For comparison, original mesh was loaded to scene as a MeshInstance (left-most object) and a CSG object created (using the same materials) to represent the same mesh (middle object), both appear to render correctly except the difference of smoothing on the green awning.
![image](https://user-images.githubusercontent.com/24907845/45003484-ba506e80-afa8-11e8-8540-d76671324bcf.png)

**Steps to reproduce:**
Create a new project, import a mesh with multiple materials (e.g [Kenney's modular buildings](https://www.kenney.nl/assets/modular-buildings)
[MeshSamples.zip](https://github.com/godotengine/godot/files/2346717/MeshSamples.zip)
Add CSG Mesh object, assign the mesh to the CSG Mesh.

**Minimal reproduction project:**
[CSGTest.zip](https://github.com/godotengine/godot/files/2346719/CSGTest.zip)

**Comment by Takanu** [comment]
+1, ive recently encountered this problem.  The ArrayMesh asset renders perfectly when put in a MeshInstance but fails when given to a CSGMesh type.

**Comment by Takanu** [comment]
Can confirm this still occurs in Godot 3.1 Stable - in my current tests only the first surface from a MultiMesh will render with the right texture and normals, every surface other than that will lack textures and in some cases will show distorted normals.

[MultiMat CSG.zip](https://github.com/godotengine/godot/files/2967852/MultiMat.CSG.zip)

The test file included shows the generated shape in a CSGMesh (which it displays correctly in the asset preview but not on the node itself), and the ArrayMesh saved as an asset and applied to a MeshInstance where it works as expected.

**Comment by LeonardMeagher2** [comment]
I've got a PR I'm working on to fix this
![image](https://user-images.githubusercontent.com/1546044/54971606-79b84280-4f44-11e9-92f4-21aaaee11b46.png)
