### ISSUE TITLE
Graphics Driver Crash When Loading Project

### ISSUE THREAD

**Issue by 9BitStrider** [godotengine/godot#21731]
**Godot version:**
3.1 Alpha

**OS/device including version:**
Windows 7 Home w/ Intel HD Graphics
Windows 8 Home w/ Intel HD Graphics

**Issue description:**
Application causes graphic driver crash upon loading a project on either computer listed above.

![untitled](https://user-images.githubusercontent.com/23580375/44993313-bcdaa600-af5f-11e8-8c2a-3d46aa67ef15.png)

**Steps to reproduce:**
Load a project in Godot. Happens even when using _sc_ for self contained mode.

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
3.1. alpha supports both GLES3 and GLES 2, which one were you using?

**Comment by 9BitStrider** [comment]
GLES2. Neither system are GLES3 compatible.

**Comment by akien-mga** [comment]
What is your CPU? "Intel HD Graphics" is sadly very unprecise, but I know that's what Windows says itself. With CPU details we can find which Intel IGP it is exactly.

**Comment by Zireael07** [comment]
In that case, there are a couple of issues about GLES2 crashing on Intel integrated cars, so you might want to use the search (I'm not saying your issue is an exact duplicate, but you might try looking around).

**Comment by akien-mga** [comment]
Also, does Godot 2.1.5 work on that system?

**Comment by 9BitStrider** [comment]
Yes, it does.

**Comment by akien-mga** [comment]
Please also answer my first question :)

**Comment by 9BitStrider** [comment]
Where would I find that information? I opened device manager and all I can see is "Intel(R) HD Graphics".

Driver Version: 8.15.10.2993

**Comment by NewNodeGames** [comment]
Solution here: https://github.com/godotengine/godot/issues/21551
Simply open the file called project.godot and remove this line:

[rendering]
environment/default_environment="res://default_env.tres"

But get ready for more crashes (ex.: trying to create a procedural skybox on world envoronment node) and bad lights results. For 2D projects can be valid for now.

**Comment by 9BitStrider** [comment]
Also, I opened a project from the asset library and it's functioning fine. But when I open one of my existing ones or creating a new one.

**Comment by Zylann** [comment]
> Where would I find that information? I opened device manager and all I can see is "Intel(R) HD Graphics".

@9BitStrider in case you have it, try running `dxdiag` in the `Execute` prompt, this will tell you more about your graphics hardware.

**Comment by akien-mga** [comment]
> Where would I find that information? I opened device manager and all I can see is "Intel(R) HD Graphics".

I know Windows is very unclear about the graphics unit, that's why I was asking about the CPU (Intel i3-<number> or similar). But I guess it's one of the ~2010 low end graphics units (5th/6th gen CPUs).

It's the same issue as #21551 apparently so closing, we can continue discussion there.

**Comment by ferhand** [comment]
HP Elitebook 2560p, core i5, 4Gb RAM, Graphic HD 3000

The same happened to me. The Godot 3.1 start fine, but the graphic card crash when try to start a new proyect or any proyect. 

Now I solved comenting the line:

[rendering]
environment/default_environment="res://default_env.tres"

in the file called project.godot.
