### ISSUE TITLE
BoneAttachment needs care

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2173]
Bone attachment is node, which is intended to be used as parent to things attached to bones,
like CollisionShapes/Areas and "hats"/"weapons". But currently it is extremely uncear how to use it.
On earlier versions it was used like on video on youtube which I still use as sole reference on
3D setup in Godot: http://www.youtube.com/watch?v=ZyTIiwfn2ag

The problem is that this usage is not flexible as it very much depends on node tree.
The best usage for this should be like physics joints - ability to specify used Skeleton, bone, and affected object (this one can be direct child, allright, but Skeleton should not necessarily be the direct parent of BoneAttachment

**Comment by slapin** [comment]
The most annoying case for this problem is this:

1. I import scene from Blender which I don't want to modify in Godot and always import
from scratch (as Godot sometimes doesn't operate correctly on modified scene re-import),
as it is quite complex and partial dependencies are not supported, and are quite hard to support,
so it is easier to handle this leaving imported scenes unmodified and do all extra stuff from upper-level (parent) scene.
2. Almost everything (animations, joints, physics, etc. supports this workflow well, except for
BoneAttachment, which forces me to edit imported scene again and again (thanks to subscenes,
it is a small edit, though) and it is frustrating and very annoying, like trip-over on flat surface.
I don't think it is complicated in any way to make BoneAttachment be consistent with everything else.

**Comment by akien-mga** [comment]
Is this still relevant in the current master branch, and if so to what extent?

**Comment by slapin** [comment]
This one was fixed, the workflow was stramlined with .escn, and inherited scenes allow fluent operation.
Also the node itself was fixed.
