### ISSUE TITLE
GLES 3 BakedLightmap requires rebake on editor start

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#21733]
**Godot version:**
3.1 alpha 1

**OS/device including version:**
Debian

**Issue description:**
After restarting the editor, the lightmap no longer affects the scene, until a rebake.

The CLI is full of these errors:

> ERROR: create_from_image: Condition ' p_image.is_null() ' is true.
>   At: scene/resources/texture.cpp:190.

and

> ERROR: write_variant: Resource was not pre cached for the resource section, bug?
   At: core/io/resource_format_binary.cpp:1507.

Possibly related to #18954 and #18801.

**Steps to reproduce:**
Add a BakedLightmap, bake. Restart the editor.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by seadra** [comment]
No, it seems to be working OK now
