### ISSUE TITLE
GLES 2 BakedLightmap not working in the editor

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#21732]
**Godot version:**
3.1 alpha 1

**OS/device including version:**
Debian

**Issue description:**
GLES 2 BakedLightmap not working in the editor, spamming the console with the error

> ERROR: instance_set_use_lightmap: Condition ' lightmap_instance->base_type != VisualServer::INSTANCE_LIGHTMAP_CAPTURE ' is true.

**Steps to reproduce:**
Add a BakedLightmap node & bake

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by reduz** [comment]
No, I fixed this afterwards (It was unimplemented) and I am confident it works. Please reopen if it does not.
