### ISSUE TITLE
Visible Collision Shapes draws tileset's collision in the wrong spot (GLES2)

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#21738]
**Godot version:**

f50dd682f6a0f9506daaf16fed06f4bc9efa6599

**OS/device including version:**

Linux

**Issue description:**

The collision shapes for a tilemap are drawn in the wrong location, seemingly all overlapping one another in the top left corner of the screen.  In practice, the position of the collider for each tile is correct and will be collided with, it is simply being drawn in the wrong location.

![image](https://user-images.githubusercontent.com/28724859/45003537-406cb500-afa9-11e8-8f11-3fc7061c84ce.png)

**Comment by DualMatrix** [comment]
I can't reproduce this as of the latest commit. Do you have an example project?

**Comment by somnivore** [comment]
I have recently discovered that this is actually a GLES2 issue; on GLES3, the tile collisions are rendered in the appropriate locations.

GLES3:
![image](https://user-images.githubusercontent.com/28724859/45120610-433fe500-b124-11e8-8bc5-76ea62050160.png)

GLES2:
![image](https://user-images.githubusercontent.com/28724859/45120635-55ba1e80-b124-11e8-8c00-e6555fe2d05f.png)

**Comment by akien-mga** [comment]
Can't reproduce it in the current master branch, so I assume it was fixed. Please comment if you can still reproduce it.
