### ISSUE TITLE
Bitflags have no dark theme variant

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#21740]
**Godot version:**

f50dd682f6a0f9506daaf16fed06f4bc9efa6599

**OS/device including version:**

Linux

**Issue description:**

Using a dark theme makes it difficult to read bitflags due to them staying black no matter how bright or dark the theme is; the darker the theme, the worse the issue gets.  Ideally they would swap out to white squares beyond a certain threshold.

Dark theme:
![image](https://user-images.githubusercontent.com/28724859/45003969-9e9b9700-afad-11e8-97b3-26f544b1c9a8.png)

Light theme:
![image](https://user-images.githubusercontent.com/28724859/45003986-cab71800-afad-11e8-8ba3-e7cf5417be18.png)

**Comment by akien-mga** [comment]
CC @toger5 @volzhs
