### ISSUE TITLE
linux binary not stripped

### ISSUE THREAD

**Issue by revast** [godotengine/godot#21749]
**Godot version:**
 3.0.6 official, downloaded from godot downloads page

**OS/device including version:**
 Ubuntu 18.04

**Issue description:**
the binary is 50+ mb, when I strip it, it's down to 45mb, when I compress it with upx, 
I can get it down to 17mb

I don't now if this is relevant, I just wanted to report it. Zipped download is 20mb, so I guess there is not really a bandwith problem

**Comment by Noshyaar** [comment]
Probably intended since we need the symbols for debugging crashes.

**Comment by akien-mga** [comment]
I think official binaries are built with `debug_symbols=no` already, not sure what the remaining 5 MB amount to and whether it would make sense to strip them, CC @hpvb.

**Comment by marxin** [comment]
Yes, I would recommend to preserve debug info in order to get a reasonable backtraces.
Note that RPM-based distributions have debug info in a separate package that is normally not installed by default.

I would recommend to not to strip debug info for Godot official binaries.

**Comment by Bleuzen** [comment]
Can we please get an export option to strip the binary?

**Comment by marxin** [comment]
Debug info is stripped with no additional option needed.

**Comment by Bleuzen** [comment]
No, the linux binary is not stripped after game export.

marxin <notifications@github.com> schrieb am Fr., 31. Mai 2019, 15:42:

**Comment by Calinou** [comment]
It'd make sense to strip debugging symbols from release-mode export templates, while keeping them in debug-mode export templates. This way, we don't have to call `strip` when exporting (which is only available on Linux anyway).

**Comment by Calinou** [comment]
This should be resolved as of 3.3, closing.
