### ISSUE TITLE
RigidBody should be able to use not only direct children CollisionShapes

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2174]
RigidBody should be able to use not only direct children CollisionShapes for collision prevention.
This probably should be possible to specify somehow, probably via implementation of
proxy nodes. In this case the following setup should work for collision prevention:
RigidBody
---Skeleton
------BoneAttachment
---------CollisionShape

For worm-like creatures this would be awesome :)

**Comment by Kermer** [comment]
Could be useful, but I suppose it would need a lot of work. Mainly because CollisionShapes are resources, not nodes and they don't even hold their transform - their Body holds it.

**Comment by slapin** [comment]
Nobody said it would be easy, but I can't see how this would be hard to implement?
It just require to add a transform to CollisionShape node, or to CollisionObject and
that won't affect existing setup much as the Transform is relative anyway.
Should be quite small change. And collision tests could have RigidBody Transform multiplied with CollisionShape transform. This behavior could be enabled with a flag (to have some collisionshapes not participate in collision avoidance). Also Area node should prevent its CollisionShapes to
participate in collision avoidance.

**Comment by slapin** [comment]
BTW, CollisionShape extends from Spatial, how come it doesn't have own Transform?

**Comment by Kermer** [comment]
CollisionShape is just an editor helper. Read [THIS](https://github.com/okamstudio/godot/wiki/tutorial_physics_2d#collisionshape2d). It isn't written for 3D, but 3D works the same.

**Comment by slapin** [comment]
But there are CollisionShapes which are used by the same RigidBody for collision detection and these can be parented to Spatial or BoneAttachment and is it hard to make them work for collision prevention? Strange..

**Comment by aaronfranke** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/535.
