### ISSUE TITLE
No way to set a custom AABB on GeometryInstance using nodes API

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#21758]
Godot 3.0.6

Valid concern from this Q&A thread: https://godotengine.org/qa/32596/rid-instanced-node-need-this-set-aabb-for-multimeshinstance

I added `VisualServer::set_custom_aabb(rid, aabb)` to be able to set custom AABBs on `GeometryInstances` (not mesh), so it works on `MeshInstances`, `MultimeshInstances`, `Particles`, `SpriteBase3D` or `ImmediateGeometry`, but didn't expose that to the higher-level API. There is also no getter.
I think this could be exposed, without having to add an extra member, if that's possible?

Also it is mentionned in the thread to expose RIDs of such nodes, but I wonder if there is another use.

**Comment by torshid** [comment]
Any news about this?
