### ISSUE TITLE
Visual Scripting "Set stream" node crashes when choosing New AudioStreamOGGVorbis

### ISSUE THREAD

**Issue by RomualdDub** [godotengine/godot#21756]
**Godot version:**
3.1 a

**OS/device including version:**
Windows 10

**Issue description:**
Visual Scripting "Set stream" node crashes when choosing New AudioStreamOGGVorbis

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by fire** [comment]
Can you provide an example project?

**Comment by groud** [comment]
There is not enough information in this issue to reproduce the bug. Closing.
