### ISSUE TITLE
.csproj may be created with an invalid RootNamespace element

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#21757]
**Godot version:**
4571089 - mono

**OS/device including version:**
Windows 7

**Issue description:**
The .csproj file uses an unsanitised  project name for the RootNamespace element.
https://github.com/godotengine/godot/blob/4f5a7ebaecfcf00cf1e5c4af4b20034f0dcecd29/modules/mono/editor/GodotSharpTools/Project/ProjectGenerator.cs#L144

The project name may hold a sequence that is an invalid identifier for c#.

When this occurs Visual Studio shows this warning:

    Load of property 'RootNamespace' failed.  The string for the root namespace must be a valid identifier.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch or latest beta build?

**Comment by neikeq** [comment]
Yes. Should be a quick to fix.
