### ISSUE TITLE
Built-in script errors should automatically open related scene

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#21750]
**Godot version:**
3.1 alpha

**Issue description:**
If you have a node with built-in script and it happens that an error pops there and the scene is closed, you will correctly get an error what happened and at which line, but at the same time, a warning appears that "Built-in scripts can only be edited after opening their scene".

Debugger will correctly highlight the error line if the scene is opened, but since you can have many such scenes and error might appear in a one you don't have opened, Godot should automatically open the corresponding scene on error.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2348414/TestProject.zip)
Just press F5 and behold the warning.

**Comment by DualMatrix** [comment]
Yeah that warning message is really annoying and makes working with built-in scripts a pain.
