### ISSUE TITLE
GLES2 Normal map rendering artifacts in 3.1 alpha official

### ISSUE THREAD

**Issue by aurodev** [godotengine/godot#21752]
Normal map rendering in GLES2 for desktop Win8.1 displays artifacts.

**Godot version:**
Godot v3.1 Alpha Official

**OS/device including version:**
Windows 8.1 64bit, 8GB AMD FX 6350 6 core
Graphics Chipset
AMD Radeon HD 7700 Series
Memory Size 1024 MB
Radeon Software Version 17.4.4

**Issue description:**
Godot displays incorrect rendering of Normal maps in GLES2 on Win8.1

**Debugger:** _No relevant errors or warnings_
0:00:00:0456 - The argument 'delta' is never used in the function '_process'.
0:00:00:0511 - Loaded resource as image file, this will not work on export: 'res://icon.png'. Instead, import the image file as an Image resource and load it normally as a resource.

**Steps to reproduce:**
Add a MeshInstance + Spatial Material w/Albedo + Normal Map
Toggle GLES3/GLES2 rendering
Brightness: Also toggle the project's DirLightGLES2 and DirLightGLES3 

**Minimal reproduction project:**
[Testbed_3.1Alpha.zip](https://github.com/godotengine/godot/files/2348595/Testbed_3.1Alpha.zip)

GLES3
![gles3nmap](https://user-images.githubusercontent.com/7356383/45031430-cfff7b80-b01c-11e8-82ad-51a3c4f24d6c.PNG)

GLES2
![gles2nmap](https://user-images.githubusercontent.com/7356383/45031459-e0aff180-b01c-11e8-9da4-f1f11862ce58.PNG)

Inspector
![inspectornmap](https://user-images.githubusercontent.com/7356383/45031583-37b5c680-b01d-11e8-8af0-ff941fe8979d.PNG)

**Comment by Chaosus** [comment]
I see it too on modern Win10/GTX 1060.. cc @karroffel

**Comment by aurodev** [comment]
A repeating pattern perhaps helps illustrate the issue better.
GLES3
![image](https://user-images.githubusercontent.com/7356383/45265123-b1322800-b414-11e8-8364-99f8c2f3ea77.png)

GLES2
![image](https://user-images.githubusercontent.com/7356383/45265152-efc7e280-b414-11e8-91ce-cb3622d28471.png)

**Comment by akien-mga** [comment]
Fixed by #23971.
