### ISSUE TITLE
Visual Shader Editor connection line is misbehaving. LMB+RMB=BUG

### ISSUE THREAD

**Issue by LATRio** [godotengine/godot#21769]
**Godot version:** master-93a888e

**OS/device including version:** Windows 10 x64

**Issue description:**

**Steps to reproduce:** 
1. Drag out curve from pin.
2. Press RMB (while holding LMB).

**Minimal reproduction project:**

**Comment by Chaosus** [comment]
Not detectable in current master. Closed.
