### ISSUE TITLE
Resizing window when mouse cursor confined uses old area.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21768]
**v3.1.alpha_custom_build.93a888e**

When your cursor mode is CONFINED and you resize the window, the confinement area is stuck as the last window size from what it looks like.

![bad_cursro](https://user-images.githubusercontent.com/13004169/45071432-ea9a2900-b0de-11e8-8f71-5df051736af7.gif)

Example Project: 
[Mouse Confine and Resize.zip](https://github.com/godotengine/godot/files/2351218/Mouse.Confine.and.Resize.zip)

@capnm @guilhermefelipecgs 

I believe this may be an issue as well for other OSes, but so far testing in Windows 10 64-bit.

Might be tying into: https://github.com/godotengine/godot/issues/21751 and https://github.com/godotengine/godot/issues/21744

**Comment by guilhermefelipecgs** [comment]
Linux works fine.
