### ISSUE TITLE
set_mesh() results in error message Godot 3.1 Alpha 1

### ISSUE THREAD

**Issue by austinrseabolt** [godotengine/godot#21762]
**Godot version:**
3.1 Alpha 1

**OS/device including version:**
Windows 10 Pro 1803 x64

**Issue description:**
When running an imported project built in GDScript Godot 3.0.6, set_mesh() causes an error message and crash upon run. 

From editor: Parser Error: Method 'set_mesh' is not declared in the current class.

From command line:

ERROR: debug_get_stack_level_instance: Condition ' _debug_parse_err_line >= 0 ' is true. returned: __null
   At: modules/gdscript/gdscript_editor.cpp:330

**Steps to reproduce:**
Attempt to use set_mesh() in GDScript

**Comment by Zireael07** [comment]
What class are you inheriting from? The GDScript typing means you have to be really careful about extending the correct stuff you want.

**Comment by austinrseabolt** [comment]
Ah, thanks for pointing that out. I made a typo. Sorry!
