### ISSUE TITLE
Search and filter node on Scene tab

### ISSUE THREAD

**Issue by draxdeveloper** [godotengine/godot#2176]
there should be a way to search and filter the nodes on the scene tab.
I have a scene with a LOT of nodes and in the game i an devoloping having scenes with hundredes of nodes will be very common.

**Comment by reduz** [comment]
2.1 will change the UI for that considerably, so we can add a search filter

**Comment by vnen** [comment]
Implemented by f9d615ee87ac27fa5fa26f91738b5267ecc7b40e
