### ISSUE TITLE
Android UI scrambles if I change the project's window size

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#21764]
**Godot version:** 3.0.6
**OS/device including version:** Windows 8 and Android 7.1.2 N2G47H
GPU: Qualcomm Adreno (TM) 308, OpenGL ES 3.0

**Issue description:**
I've set up my project window size as 960x540. Since this doesn't divide evenly into my tile size (48x48), I decided to resize it to 960x528.  

For some reason, changing the window height (even by 10px) causes the graphics to appear very very very glitched out.

Expected (when I set the window size to 960x540):

![](https://i.imgur.com/kZiEuBU.png)

Actual (960x528):

![](https://i.imgur.com/ghP7e20.png)

**Steps to reproduce:**
- Run the game and look at the title screen. It's messed up.
- Click to go to the main game map. It's messed up.

**Minimal reproduction project:** [GitHub link to the second-most-recent commit](https://github.com/nightblade9/eid-island/commit/d54e9e43a753ade1d6d78a36a6c33645eb8740c5)

**Comment by Zireael07** [comment]
Looks very much like an issue that has been reported but I can't find it atm (what are your viewport settings?)

**Comment by nightblade9** [comment]
Here are my settings from the `project.godot` file ([ref](https://github.com/nightblade9/eid-island/blob/master/source/project.godot)):

```
[display]

window/size/width=960
window/size/height=540
window/size/resizable=false
window/stretch/mode="viewport"
window/stretch/aspect="keep"
```

**Comment by Zireael07** [comment]
Yeah, aspect keep was mentioned in that other issue. Try searching.

**Comment by nightblade9** [comment]
Looks like it could be related to / the same as: https://github.com/godotengine/godot/issues/17060

Is that the issue you were thinking of?

**Comment by Zireael07** [comment]
Yeah ;)

**Comment by nightblade9** [comment]
Closing as dupe of #17060
