### ISSUE TITLE
GLES2 Android device, Weird glitchy ghost sky box like effect

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#21772]
**Godot version:**
Godot 3.1 master branch 93a888e at 2018-09-05

**OS/device including version:**
Tested on
Android 4.4.2 - MTK6592 - 1GB - GPU Mali 450 MP4 700Mhz - GL2.0
Android 4.4.2 - BCM23550 - 1GB - GPU VideoCore IV - GL2.0

```
GL_ARM_mali_program_binary
GL_ARM_mali_shader_binary
GL_ARM_rgba8
GL_EXT_blend_minmax
GL_EXT_debug_marker
GL_EXT_discard_framebuffer
GL_EXT_multisampled_render_to_texture
GL_EXT_robustness
GL_EXT_shader_texture_lod
GL_EXT_texture_format_BGRA8888
GL_KHR_debug
GL_OES_EGL_image
GL_OES_EGL_image_external
GL_OES_EGL_sync
GL_OES_compressed_ETC1_RGB8_texture
GL_OES_depth24
GL_OES_depth_texture
GL_OES_depth_texture_cube_map
GL_OES_get_program_binary
GL_OES_packed_depth_stencil
GL_OES_rgb8_rgba8
GL_OES_standard_derivatives
GL_OES_texture_npot
GL_OES_vertex_half_float
```

**Issue description:**
Weird glitchy ghost sky box like effect as seen on attached video recorded on Android 4.4.2 - MTK6592 - 1GB - GPU Mali 450 MP4 700Mhz - GL2.0 Note also grainy dithering of this ghost sky box.
_This is not visible while running on PC nor in editor._

![glitchy-sky-box-like](https://user-images.githubusercontent.com/3224132/45088424-382b8b80-b109-11e8-8a9c-1b6bcfcaae78.gif)
_FPS is low due to recording_

**Example project:**
[g31-test-8.zip](https://github.com/godotengine/godot/files/2352378/g31-test-8.zip)

**Additional info for the attached project:**
On android to look around and zoom, you can move camera with touch screen.
On pc you can look around and zoom with mouse.

**Comment by CptPotato** [comment]
Looks like an issue with mipmapping for cubemaps (you can see what seems to be the texture's mipmaps in the cube reflection)

**Comment by NewNodeGames** [comment]
Also there are errors with materials on old GL2 gpu's (2010 Intel and probably others). A partial solution is decrease roughness parameter on spatial materials to 0.99 or less but lights don't work well (some zones too bright).

**Comment by akien-mga** [comment]
CC @karroffel

**Comment by avril-gh** [comment]
might be related to WorldEnvironment node - ProceduralSky as i cant see it in other places just when ProceduralSky is enabled.
