### ISSUE TITLE
Pen and Touch doesn't work in MOUSE_MODE_CAPTURED

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#21779]
**Godot version:**
3.1 alpha 1 (from here https://downloads.tuxfamily.org/godotengine/3.1/alpha1/)

**OS/device including version:**
Win 10
Wacom Intuos Pro M

**Issue description:**
When changing to capture mode, I can't get any movement event.

Works fine on Linux.

**Steps to reproduce:**
Change the demo to capture mode.

**Minimal reproduction project:**
https://github.com/godotengine/godot/files/2352422/i21744-Constrained-Cursor-v4.zip

**Comment by akien-mga** [comment]
CC @RandomShaper

**Comment by RandomShaper** [comment]
I'm can't access a computer right now. @akien-mga, could you tell me if f2e52ff is in the alpha build referred in the report?

**Comment by guilhermefelipecgs** [comment]
I retested here with nightly build from today v3.1.alpha.calinou.93a888e and the issue is there. 
Note that this only affect MOUSE_MODE_CAPTURED, with other modes pen and touch works fine.

**Comment by guilhermefelipecgs** [comment]
Maybe this is the problem #20523:
https://github.com/godotengine/godot/blob/53070437514e448c87f6cb31cf5b27a3839dbfa1/platform/windows/os_windows.cpp#L468-L471

But I'm without the windows environment configured to compile and test it.

**Comment by RandomShaper** [comment]
@guilhermefelipecgs, could you test on 3.0.6-stable and/or 3.0.7-dev, please?

**Comment by RandomShaper** [comment]
Although I'd still like to know if it's solved by now, I think I'm buying a basic digitizer to be able to debug these issues non-blindy.

**Comment by guilhermefelipecgs** [comment]
I'll test it asap. Probably today.

**Comment by RandomShaper** [comment]
Great, thanks!

Then, I'm closing this as fixed by #21611.
