### ISSUE TITLE
Proposal: make the tool keyword necessary in the currently edited scene only

### ISSUE THREAD

**Issue by samdze** [godotengine/godot#21773]
## Premise:
Right now the tool keyword is necessary if a script were to be executed anywhere in the editor.

## Proposal:
Every script should be executed without the tool keyword in every part of the editor, the only exception being the currently edited scene, that would be the only sub-tree with scripts that are not executed by default and where the tool keyword would still be necessary.

## Motivations and advantages:
1. I always found annoying having to add the tool keyword to scripts of my custom docks or other scenes that will be added to some part of the editor, when I edit those scenes I'm always risking to save them in a modified state due to the scene being in execution.
2. What if I want to reuse some scripts in my game scenes in my editor scenes as well?
In the current state I'd have to duplicate them, otherwise the tool keyword would break my game scenes if I save them.
3. The only purpose of adding a scene somewhere in the editor (currently edited scene excluded) is to make it run as an editor tool, according to this I find the tool keyword unnecessary in this case.

There likely will not be huge compatibility breakages, what were working previously in the editor with the tool keyword will continue to work and scripts of scenes instantiated out of the currently edited scene sub-tree should have been marked as tool to work anyway.

Possible alternative solution to  #17592

**Comment by reduz** [comment]
Sorry, this is unfeasible. Scripts do have logic that runs when the node is outside the edited scene (like constructor, child added, etc), also detecting this condition is too high level and complicated, as it must include autoloads (which can also not work).
