### ISSUE TITLE
(*) indicator doesn't go away after save

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#2177]
If I make changes to a scene then (*) gets put in the tab, and after saving, it doesn't go away. As a habitual saver with a little OCD, this drives me nuts. :)

**Comment by draxdeveloper** [comment]
If you have mutiple scenes, just change the scene on scenes tab. I know
that is not ideal, but will solve for now.

2015-06-24 10:47 GMT-03:00 Dana Olson <notifications@github.com>:

> If I make changes to a scene then (*) gets put in the tab, and after
> saving, it doesn't go away. As a habitual saver with a little OCD, this
> drives me nuts. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2177>.
>



-- 
David Aguiar de Aquino Paiva

**Comment by Hodes** [comment]
It should be marked as a BUG. It's a common issue, that needs a fix for next releases, thanks.

**Comment by eska014** [comment]
Fixed by #2362
