### ISSUE TITLE
VisualScript GetSceneNode displays editor-time NodePath (super long/unreadable)

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#21776]
**Godot version:**
3.1 93a888e

**OS/device including version:**
Windows 10

**Issue description:**
When creating a GetSceneNode graph node in VisualScript, it displays what the node path is from the root of the Godot Editor itself, not relative to the edited scene's root.

![get_scene_node_bug](https://user-images.githubusercontent.com/16217563/45102981-779bad00-b0f4-11e8-8669-339cb5e09cf4.png)

**Steps to reproduce:**
1. Create scene with Node root and Sprite child.
2. Add script to Node root. Have it GetSceneNode on the child Sprite.
3. Text in the node will be incorrect.

**Comment by fire** [comment]
![godot windows tools_2018-10-11_16-27-18](https://user-images.githubusercontent.com/32321/46839404-89ffab00-cd72-11e8-9d5b-78d1e5e3414c.png)

Maybe drag and dropping should be changed. This is using a pure visual script method with out drag and dropping.

**Comment by KoBeWi** [comment]
Fixed since 3.1 stable
