### ISSUE TITLE
Broken 3D texture support.

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot#21788]
**Godot version:**
Godot 3.1 alpha

**OS/device including version:**
Windows 7 64-bit | Intel HD Graphics 4400

**Issue description:**
I'm creating a port of my volume renderer to 3.1 and noticed this new texture 3D import option. I tried it out along with the new `sampler3D` uniform in a regular shader. And I get strange results.

![suzanne emulated 2d texture](https://user-images.githubusercontent.com/34734122/45126775-ab99c100-b13a-11e8-8e54-74c0475f1743.PNG)
Here is a Suzanne 3D texture I made. Prior to Godot 3.1, I emulated the 3D texture sampling of a regular 2D texture. To the edge of the viewport is a pyramid volume. Rendered the same way as the Suzanne volume.

![suzanne true 3d texture mipmaps](https://user-images.githubusercontent.com/34734122/45126806-e1d74080-b13a-11e8-93f5-d0b7f69c223f.PNG)
This is after the switch to a 3D texture. The texture has mipmaps enabled.

![suzanne true 3d texture no mipmaps](https://user-images.githubusercontent.com/34734122/45126956-9a9d7f80-b13b-11e8-9d1c-80d86cafdb26.PNG)
I disabled mipmaps in this one.

If a reproduction project is required let me know.

**Comment by SIsilicon** [comment]
I also noticed that the change also happens to pyramid volume despite it's texture not even being 3D. As if all `sampler3D`'s have the same values.

**Comment by aaronfranke** [comment]
CC @reduz Possibly related: https://github.com/godotengine/godot/issues/20904

**Comment by SIsilicon** [comment]
Thank you for acknowledging this. :-)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
