### ISSUE TITLE
Out of memory bug when saving scene with a navigation mesh

### ISSUE THREAD

**Issue by ComicoTeam** [godotengine/godot#21786]
ERROR: set: Condition ' p_index < 0 || p_index >= size() ' is true.
   At: ./core/dvector.h:488
In the console every time I try to save a scene that has a new navigation mesh

Godot version: 3.0.6

Windows 10 x64

**Steps to reproduce:**
Open the scene from the project then create a navigation mesh and save the scene

**Minimal reproduction project:**
[Bug.zip](https://github.com/godotengine/godot/files/2354779/Bug.zip)

**Comment by ComicoTeam** [comment]
Tried on 3.1 and it's happening as well

**Comment by ComicoTeam** [comment]
Is nobody going to talk about this issue. That you can't generate complex navigation meshes?

**Comment by Zireael07** [comment]
@ComicoTeam: You reported a bug one day ago, the team has a lot of bug reports (not to mention they are now doing a cleanup of the issues list in preparation for 3.1)

**Comment by ComicoTeam** [comment]
@Zireael07 I know that they are busy with 3.1. but the bug is present in that version as well

**Comment by DevMagicLord** [comment]
After import your project , i did not see the navigation and navmeshInstance, do you know how they work ? 

I added them and i could bake the navmesh without any issues with Godot 3.1 alpha 1
https://github.com/DevMagicLord/Godot3/blob/master/bugs/navmesh31alpha1.jpg

**Comment by ComicoTeam** [comment]
@DevMagicLord The issue is still happening
And I've saw that godot has some issues with amd gpu's

**Comment by reduz** [comment]
Navigation mesh is too complex, and there is no way to fix this issue without breaking backwards compatibility. I suggest you use a simpler mesh manually created for this.

Will rewrite how navigation code works eventually for 4.0, so kicking this forward

**Comment by Calinou** [comment]
This was most likely resolved by #34776, closing. See https://github.com/godotengine/godot/issues/17885#issuecomment-596490309 if you need a solution in Godot 3.2.
