### ISSUE TITLE
How to organize font oversampling for scaled control?

### ISSUE THREAD

**Issue by r3d9u11** [godotengine/godot#21797]
Hi. Is it possible to organize font oversampling for scaled control?
Stretch Mode is Disabled and Use Oversampling is Checked.

Now font doesn't changes:
![1](https://user-images.githubusercontent.com/15020827/45155695-86fa2380-b1e4-11e8-8a53-5bff1638eb03.png)
![2](https://user-images.githubusercontent.com/15020827/45155669-67fb9180-b1e4-11e8-81ca-de0ca5d8fe64.png)

Thanks.

**Comment by Calinou** [comment]
Font oversampling uses a global factor, whereas Control scaling is local by definition (it can be applied to specific controls, each with their individual scale property). Therefore, I doubt this is possible.

**Comment by r3d9u11** [comment]
@Calinou if I'll try to handle "resize" event of control to change size (if it possible in Godot) of dynamic font - will it be a good and possible solution?

**Comment by Calinou** [comment]
@r3d9u11 I don't think that would work, since the DynamicFont will not be aware of the Control's scale. Besides, the same DynamicFont resource can be used in different Controls, each of them using their own scaling value — what would be done in this case?

**Comment by r3d9u11** [comment]
@Calinou in that case font size will be automatically changed for all similar controls, I think.
But as I see, currently Godot conception doesn't allow to change font size on the fly.
As workaround I should to make separated scenes and themes for each needed display resolution.
Am I to understand that correctly?

**Comment by Calinou** [comment]
> As workaround I should to make separated scenes and themes for each needed display resolution.

You don't need to, just use the `2d` stretch mode as explained in [Multiple resolutions](http://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html).

**Comment by r3d9u11** [comment]
@Calinou Yep, it is a good and fast solution, and game scene looks nice. But I trying to escape it globally.

I tried to use game scene in the fullscreen mode: `Stretch Mode: 2D, Aspect: Ignore.`
Game scene looks nice, but popup menu and buttons looks ugly, because its proportions are viaolated.

Or if I use `Stretch Mode: 2D, Aspect: keep ` the popup menu and main menu with controls are looks nice, but game scene will not stretched to fullscreen (because it will save proprotions, too).

Finally I want to stretch game scene to the full screen, but popup menu I want stretch to currenct desktop resolution and save proportions (and place it to the cetnter of the screen).

**Comment by r3d9u11** [comment]
@Calinou well, I found a similar issue: https://github.com/godotengine/godot/issues/1919
but solution with "scale" property looks bit ugly :-|

Original size:
![1](https://user-images.githubusercontent.com/15020827/45218651-110fbe00-b2b1-11e8-8614-9606395309f5.png)
Scaled via Stratch-Mode: 2D + Font Oversampling (font looks nice)
![2](https://user-images.githubusercontent.com/15020827/45218704-3b617b80-b2b1-11e8-938c-669ddc9055e4.png)
Scaled via property "Rect_Scale" + Font Oversampling (font looks ugly)
![3](https://user-images.githubusercontent.com/15020827/45218732-50d6a580-b2b1-11e8-8363-ad34dfe06c08.png)

Why font oversampling doesn't work with scaled control? (when Stretching is disabled)

Well, now I see one solution: use anchors + Import fonts for each screen resolution.

**Comment by Calinou** [comment]
@r3d9u11 To support multiple aspect ratios, use the `expand` stretch aspect property instead of `ignore` or `keep` (it was added in 3.0).

**Comment by r3d9u11** [comment]
@Calinou sorry, Yes, I my samples upper I used mode "expand" to keep proportions. But I want to use stretch behavior for different nodes. Shortly: I want to stretch background to full screen (and distort proportions), but in that time I want to stretch controls and save its proportions.

Currently with global flag "Stretch" it is not possible. I should to implement this logic manually.

**Comment by Calinou** [comment]
> Currently with global flag "Stretch" it is not possible. I should to implement this logic manually.

Have you tried using setting a TextureRect's anchor to Full Rect (while making sure the root control node is also anchored as Full Rect)?

**Comment by r3d9u11** [comment]
@Calinou thanks for hint! I'll check this solution soon.

**Comment by r3d9u11** [comment]
@Calinou many-many thanks!!! I should to use "Node" as a Root node + Layout/Anchors settings + Stretch:2d/Expand. Works fine and looks nice with different resolutions.
