### ISSUE TITLE
A lot of demo projects not working/crash with Godot 3.1 Alpha

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21792]
**Godot version:**
3.1 alpha

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
A lot of demo projects crash or have a lot of errors and should be repaired before stable 3.1

</details>
CirclePop
<details>

![aaaaaafafwfqfq](https://user-images.githubusercontent.com/41945903/45144798-6e2b4700-b1bf-11e8-9eb3-e94b3368fcbd.png)
</details>
Windows Management
<details>

![asfasfasfsafasfas](https://user-images.githubusercontent.com/41945903/45145179-556f6100-b1c0-11e8-87f1-82fcb359a97b.png)
</details>
Drag&Drop GUI
<details>

![asfasfasfasfaf](https://user-images.githubusercontent.com/41945903/45145529-22799d00-b1c1-11e8-894d-1f01a9cb01ba.png)
</details>
RichTextLabel BBcode
<details>

![fasfasfaf](https://user-images.githubusercontent.com/41945903/45145620-62d91b00-b1c1-11e8-8a78-f9580318be0e.png)
</details>
Platformer 3D
<details>

![fasfasfaf](https://user-images.githubusercontent.com/41945903/45145742-a9c71080-b1c1-11e8-8bb6-ef4add0cfdde.png)
</details>
Material Tester

<details>

![asfasfasfasasfasfasfasfa](https://user-images.githubusercontent.com/41945903/45145865-f90d4100-b1c1-11e8-945c-724166d280c9.png)
</details>
3D IK
<details>

![fasfasfaf](https://user-images.githubusercontent.com/41945903/45145999-3bcf1900-b1c2-11e8-915c-555858c97ccc.png)
</details>
Particle System
<details>

![fasfasfaf](https://user-images.githubusercontent.com/41945903/45146216-ba2bbb00-b1c2-11e8-91ff-d984c541f614.png)

</details>
Grid based pathfinding Astar
<details>

![fasfasfaf](https://user-images.githubusercontent.com/41945903/45146277-d4fe2f80-b1c2-11e8-9428-f2e50b036070.png)

</details>
Errors from some of above projects

[tekst.txt](https://github.com/godotengine/godot/files/2356295/tekst.txt)

**Minimal reproduction project:**
https://github.com/godotengine/godot-demo-projects

**Comment by akien-mga** [comment]
Fixed most cases with:
- godotengine/godot-demo-projects@faae60ac2f4fda761139a266f083878e39692ba3
- godotengine/godot-demo-projects@a38b31506449174072c1bb2827d3c55a513db473
- godotengine/godot-demo-projects@cfcc0f3964a318573ad04944d74bc3a5ae3887ec

Left to do:
- 3d
- 2d/*platformer
- visual_script

But that's better tracked in https://github.com/godotengine/godot-demo-projects
