### ISSUE TITLE
Disable ability to set stupid values to almost all number properties in Settings

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21795]
**Godot version:**
3.1 Alpha

**OS/device including version:**
Windows 10 

**Issue description:**
It is possible to set, to almost all properties, stupid values in Settings.
e.g. Window height could have negative value or big values like 1000000.

Godot should not allow such things, should always clamp values between typical values e.g. Window heigh (1,10000)

![asfasfasfasfasfasfasfasfasfas](https://user-images.githubusercontent.com/41945903/45153625-f5cf8080-b1d4-11e8-89ca-7f69d08775ac.png)

**Comment by AlexHolly** [comment]
https://github.com/godotengine/godot/issues/9229

**Comment by qarmin** [comment]
Window size is clamped between 0 - 8K values by #22621 so other forms waiting to be "repaired"

**Comment by akien-mga** [comment]
Readding junior job tag, it turns out that it's simple enough to do as shown in #22621.
