### ISSUE TITLE
2D viewport opened in 3D scene can scroll only to down

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21798]
**Godot version:**
3.1 https://github.com/godotengine/godot/commit/53070437514e448c87f6cb31cf5b27a3839dbfa1

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
When I open for example grenade scene (res://Grenade.tscn) and change view to 2D, i can scroll down to infinity but I can't come back.

**Steps to reproduce:**
1. Open 3D scene from project below (e.g. Bullet_Scene.tscn)
2. Open 2D view
3. Try to scroll in any direction

**Video**
https://streamable.com/n95ai

**Minimal reproduction project:**
[Ziemniakq.zip](https://github.com/godotengine/godot/files/2356937/Broken_Target.zip)

**Comment by groud** [comment]
According to you projects settings, you set a negative size to your Display/window/Size.
I don't know how it happened but this seems to be the source of your bug.
