### ISSUE TITLE
Node get_position_in_parent() and get_index() do the same

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#21802]
I used `get_index()` a lot, but recently while randomly looking at documentation, I noticed the `get_position_in_parent()`. It has different description (!), but does the same. I looked at implementation and they literally are the same functions under different names and different descriptions, so it seems like unintended alias.

**Comment by eon-s** [comment]
Related #16863

**Comment by akien-mga** [comment]
Both date back to the original open source commit, one should indeed be removed. Moving this to an entry in #16863.

**Comment by girng** [comment]
`index` implies it's a child of a node that has a parent
