### ISSUE TITLE
live editing of remote scene in inspector is impossible

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#21805]
**Godot version:**
Godot 3.1 master branch at 5307043 2018-09-06
Godot 2.1.5 at 2018-09-06

**OS/device including version:**
Windows 7 32bit

**Issue description:**
**One from most iconic feature's of godot** which is live editing / debugging of running scene / game,
...is unusable.

**Steps to reproduce:**
1. run a project
2. chose object you want to change / edit at runtime, from scene -> remote -> some object
3. try to change anything in inspector

![g31-test-remote-tree-debug](https://user-images.githubusercontent.com/3224132/45163531-dcd4c880-b1f0-11e8-9a59-19b725c55015.gif)

**Minimal reproduction project:**
perhaps you could see it on any project but for your pleasure i'll post a test project that is visible on movie above.
[g31-test-remote-tree-debug.zip](https://github.com/godotengine/godot/files/2357438/g31-test-remote-tree-debug.zip)

**Comment by PetePete1984** [comment]
On that note, the error spam could be a bit more helpful if the variables used in `ERR_FAIL_COND` macros had names that function without their context

**Comment by AlexHolly** [comment]
https://github.com/godotengine/godot/issues/13346
https://github.com/godotengine/godot/issues/20365

**Comment by avril-gh** [comment]
it simply constantly steal focus while updating controls so they cannot be selected nor edited by user.

it should'nt set focus to control while writing data to it, because user cant select anything if focus jumping all around everywhere.
if control have focus - it shouldnt be updated - because it meant user is editing it just now.
if user press enter / lose focus - meant he finished editing - data from control should be immediately send to remote object, before it gets overwrited.

**Comment by avril-gh** [comment]
closing due to resolved by d16ce4a in https://github.com/godotengine/godot/issues/13346

![remote_debug](https://user-images.githubusercontent.com/3224132/48316557-a9922980-e5e5-11e8-84e9-52cc60e7c824.gif)
