### ISSUE TITLE
syntax highlighter setting not saved

### ISSUE THREAD

**Issue by girng** [godotengine/godot#21815]
latest master.
In the editor:
 - Go to GDS Editor
 - Click  syntax highlighter
 - Change it

reload godot, not saved

**Comment by DualMatrix** [comment]
I tested in f148e8e, my settings were saved.

**Comment by akien-mga** [comment]
I tested in f148e8e too and could confirm that the value did not get saved in my case.

To be clear, this is about
![screenshot_20180919_090848](https://user-images.githubusercontent.com/4701338/45736576-a08b6a00-bbeb-11e8-9ba5-ce1f61149b43.png)
and not the `syntax_highlighting` bool property in Editor Settings.

**Comment by girng** [comment]
ty @akien-mga. yep thats it

**Comment by DualMatrix** [comment]
Oh yeah I was testing the Editor Settings sorry.

**Comment by girng** [comment]
@DualMatrix  i need to be more specific in my issues :). i re-read this issue and just realized my op is a bit ambiguous. the problem is, if i find a bug, i go to github in rage and just post. i need to calm down, explain the situation fully and coherently
