### ISSUE TITLE
Change duplicate line behavior to duplicate selection

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#21814]
Basically this: https://github.com/Microsoft/vscode/issues/2075#issuecomment-172943564
Would be cool if Godot's CTRL+B behaved this way, so duplicate line if nothing is selected and duplicate selection if something is selected. It's really useful sometimes.

**Comment by SeleckyErik** [comment]
The shortcut seems to behave just as is described in the referenced comment for me. Can you double-check that on your end too?

**Comment by KoBeWi** [comment]
It doesn't. I'm using 3.1 alpha2.

**Comment by SeleckyErik** [comment]
I suppose that by 3.1 alpha you mean you have compiled a master branch yourself, right? If so, can you check what commit it is you are using and/or update to the latest if it's not the case already? Other than that, I am not really sure what the issue might be,

**Comment by SeleckyErik** [comment]
> I meant the official release. But I tried it with master branch and it works the same.

Alright, so that's not the cause of issue then.

> Might be that you misunderstood the request ._.

That might be the case indeed. So what I understood is that pressing Ctrl + B in code editor should duplicate  the line above the cursor; If a section of code is selected, though, it should duplicate the selected code instead. This is how it works for me. I am ppending a recording of the behaviour I get.

![2018-12-02_18-39-01](https://user-images.githubusercontent.com/35656626/49342954-d1fbc980-f661-11e8-86cf-57ee939c169a.gif)

**Comment by KoBeWi** [comment]
Well, you describe it correctly, but then you provide wrong example. The current text editor doesn't duplicate selected code, but selected lines. So if you select even one word, it will duplicate whole line. It should duplicate only the selected word.

This is what I mean:
![screen_recorder_plus_video_2018_02_12_18_52_41](https://user-images.githubusercontent.com/2223172/49343064-a11c9400-f663-11e8-82b9-af4b16f426c7.gif)

While in Godot, it would produce:
```
this is example
this is example
this is example
this is example
```

**Comment by SeleckyErik** [comment]
Alright! Now I see what you mean, thanks for the explanation. I will take a look into later this week and hopefully open a PR.

**Comment by SeleckyErik** [comment]
@KoBeWi Sorry bud, I didn't have time for this at all. Opened a PR now. You can download my PR branch and test whether it works as expected now.
