### ISSUE TITLE
Meshlibs bugs

### ISSUE THREAD

**Issue by Heryhelder** [godotengine/godot#21816]
**Godot version: 3.1 alpha 1**

**OS/device including version: Fedora 28**

**Issue description:**
When using a meshlib in a gridmap it doesn't keep the same scale i had set (in GLES 3).
When click in one of the meshes to draw my map, godot closes (in GLES 2).

**Steps to reproduce:**
1) Create a scene with spatial -> one or more meshes
2) Scale Mesh(es)
3) Convert to Meshlib
4) Create a new scene with Spatial -> Gridmap
5) Set the created meshlib to Mesh Library in Gridmap
6) Try to draw in the editor

**Minimal reproduction project:**
[scaletest.zip](https://github.com/godotengine/godot/files/2358697/scaletest.zip)

**Comment by Zylann** [comment]
Similar scale issue: https://github.com/godotengine/godot/issues/10128
Tracker for gridmap issues: https://github.com/godotengine/godot/issues/10418
The GLES2 one might be new.

**Comment by Heryhelder** [comment]
@Zylann the meshes icons is black in both GLES 2 and 3. And i have this errors:
![captura de tela_2018-09-06_22-28-45](https://user-images.githubusercontent.com/8170891/45197025-89389e00-b235-11e8-95fd-3f867ead1879.png)
![captura de tela_2018-09-06_22-29-01](https://user-images.githubusercontent.com/8170891/45197026-89389e00-b235-11e8-90f0-d07ef8832424.png)
![captura de tela_2018-09-06_22-29-25](https://user-images.githubusercontent.com/8170891/45197027-89389e00-b235-11e8-801b-c0cfc85cd378.png)
![captura de tela_2018-09-06_22-29-32](https://user-images.githubusercontent.com/8170891/45197028-89389e00-b235-11e8-9500-38ac80305d0a.png)
![captura de tela_2018-09-06_22-29-44](https://user-images.githubusercontent.com/8170891/45197029-89d13480-b235-11e8-8a52-65553f668a71.png)
![captura de tela_2018-09-06_22-30-03](https://user-images.githubusercontent.com/8170891/45197030-89d13480-b235-11e8-9d37-ad3541020710.png)

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by Heryhelder** [comment]
I'm trying right now and it still reproducible (except for the GLES2 resulting in crash). I have downloaded Godot from here (https://hugo.pro/projects/godot-builds/). I dont know how to build godot from master.

It still dont keep scale, the images of the meshes are totally black and if i rename one of the meshes after export to meshlib, it creates another mesh in Gridmap (in this case i have renamed MeshInstance to Cube2x, saved and exported. Now editor shows me 3 meshes in the Gridmap, instead of 2). Both errors in GLES 2 and 3.
GLES2:
![gles2](https://user-images.githubusercontent.com/8170891/51640556-8ddec400-1f42-11e9-9025-cb7f748db374.png)
GLES3:
![gles3](https://user-images.githubusercontent.com/8170891/51640557-8ddec400-1f42-11e9-8b77-e76bad469fc5.png)

Minimal Project:
[Projetos.zip](https://github.com/godotengine/godot/files/2789368/Projetos.zip)

**Comment by akien-mga** [comment]
Seems fixed in the current `master` branch. You might need to reimport the Meshlib with "Merge With Existing" disabled to ensure that the previous ones are overridden (which is why you had three meshes in the previous comment).
