### ISSUE TITLE
Collision from PhysicsBody in Inspector have a lot of unused space after resizing

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21828]
**Godot version:**
3.1 Alpha

**OS/device including version:**
Windows 10

**Issue description:**
When I resize Inspector, Collision looks bad because it have a lot of unused space.
I don't know how to change this to look good but probably a good idea would be to centre this layers.

![asfasfaf](https://user-images.githubusercontent.com/41945903/45208629-55886300-b28b-11e8-92f1-75e847a79951.png)

**Comment by akien-mga** [comment]
I don't think it looks that bad, and I'm not sure centering or adding padding between flags would make things better. I'm not against a change but I don't see an easy way to improve the looks here.

**Comment by akien-mga** [comment]
I think it's fine as is, and we'll likely change it in the future to display the full 32 bits instead of 20 as done now.
