### ISSUE TITLE
Wrong gamepad values for shoulder buttons on usb joystick

### ISSUE THREAD

**Issue by HummusSamurai** [godotengine/godot#21829]
**Godot version:**
Godot master, commit https://github.com/godotengine/godot/commit/f1e5b7cf42010db1251ecef34695367c125f02e1

**OS/device including version:**
Fedora 28 KDE

**Issue description:**
I've been using an older controller which was mapped fine, but now I'm using Havit HV-G61.

Godot mixes up the shoulder button, with L1 being read as L2 and vice versa, and R1 being read as R2 and vice versa.

I used my OS tools to check the calibration and the buttons are mapped fine and the signals are being received accordingly:
L1 - Button 5
R1 - Button 6
L2 - Button 7
R2 - Button 8

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by aaronfranke** [comment]
There don't seem to be any Havit controllers in the [SDL Game Controller Database](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt). Please consider adding your gamepad to the database.

**Comment by akien-mga** [comment]
Indeed, you need to retrieve the mappings for this controller as described by @aaronfranke. We can't fix it without your help :)

**Comment by aaronfranke** [comment]
I suggest closing this because it's not a Godot bug. If not, at least bump it to 4.0.

@HummusSamurai If you want this issue fixed, please add your controller to the SDL Game Controller Database. https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

**Comment by akien-mga** [comment]
This might actually have been due to #34910. Can you check if you still have the bug in 3.2 beta 5, and if so, whether that PR fixes it? (should be in the next 3.2 build)

**Comment by akien-mga** [comment]
I'll assume this is fixed for now by #34910.

Please comment if it is not. In that case, it would likely be fixable by contributing updated mappings to this repository: https://github.com/gabomdq/SDL_GameControllerDB
