### ISSUE TITLE
Fragment shader COLOR behaves differently in GLES2 and GLES3

### ISSUE THREAD

**Issue by 0nepixel** [godotengine/godot#21826]
Godot 3.0, Godot 3.1
Windows 7
Issue:
When you try to use COLOR on a light shader, returns a white rectangle
for instance LIGHT = COLOR;
I was trying to port the isometric 2D lighting shader from 2.1 to 3.1, but COLOR is broken.
1- create a new shader
2- void light() {
LIGHT =COLOR;
}

**Comment by CowThing** [comment]
COLOR is different between GLES3 and GLES2. For example this shader on a Sprite:
```
shader_type canvas_item;

void fragment() {
	COLOR;
}
```
In GLES3 this will render as white, in GLES2 this will render as the sprite's texture. I don't know if this is intended or which one is meant to be correct. For GLES3 you have to set COLOR like eon-s mentioned.

**Comment by 0nepixel** [comment]
i see what you mean, but now the shader ignores completly the light and draws the sprite normaly (without light), maybe is something to do with the GLES3 like you say, but turning on the GLES2 on editor gives me an error of drives (this doesn´t happend on Godot 2.x) rare

**Comment by 0nepixel** [comment]
Well i guess that Godot 3.1 GLES3 and GLES2 are pretty broken by the moment :/

**Comment by eon-s** [comment]
Yeah, shaders are still to be tested on GLES2, there are many cases for these to fail (like with loops).
Lot of checks and warnings will have to be added...

**Comment by clayjohn** [comment]
I think this was fixed by #23339. Both GLES2 and GLES3 now assign the vertex color to `COLOR` and require the user to explicitly call `texture(TEXTURE, UV)` if they want to read from the sprites texture.

**Comment by akien-mga** [comment]
Indeed, thanks.
