### ISSUE TITLE
is_action_pressed inconsistent for faked inputs

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#21821]
**Godot version:** 3.1 19d5789

**Issue description**: Suppose I create a new `InputEventAction` and set `action = "action"` and `pressed = true` and then send this action through `get_tree().input_event(event)`. The event is recognized in `_input` but the statement  `event.is_action_pressed("action")` is `false`. This is unexpected since  `event.is_action("action") and event.is_pressed()` is `true`.

This was discussed in #6135 where it looks like `is_action_pressed` behaved as expected, but now it doesn't?

**Minimal reproduction project:** [TT.zip](https://github.com/godotengine/godot/files/2359197/TT.zip)
Press space, it will show that the event is pressed but `is_action_pressed` returns false.

**Comment by akien-mga** [comment]
I've had a quick look at this, and the Input code is not super straightforward.

But basically `event.is_action_pressed("action")` takes a different route than `event.is_action("action") and event.is_pressed()` in `core/os/input_event.cpp`. It uses the `InputMap::event_get_action_status`  method, which then calls `InputMap::_find_event` and `InputEvent::action_match`.

And there we see that `InputEvent::action_match` defaults to `False`, and only some InputEvent types override it. `InputEventAction` doesn't, which is likely why it ends up returning false.
