### ISSUE TITLE
organizing script tab

### ISSUE THREAD

**Issue by draxdeveloper** [godotengine/godot#2183]
Ok, now there is a script list on script tab and this is very nice, except that if you have a huge list of scripts you will have a hard time finding it.

Some suggestions:
A simple search feature.
A filter feature.
A category feature, that would work with the filter. You would mark scripts in categories so if you put a script on player category you would just see scripts from various nodes that you marked as player.
A script could be in more than one category, for example: player and movement.

**Comment by reduz** [comment]
you can click the script tab and type the name of the script, it will
search for it.
Alternatively there is alt-ctrl-o, which will open the script locator

**Comment by draxdeveloper** [comment]
a ok, ty

**Comment by draxdeveloper** [comment]
but what you think about scripts categories?

**Comment by reduz** [comment]
i don't think that's necessary. If you are organized and put your project
scenes in folders, the locator (alt-ctrl-o) does a great job showing all
the scripts in a specific folder

**Comment by draxdeveloper** [comment]
ah, ok ty :)

**Comment by BBric** [comment]
Is there a way to avoid the alphabetical order ?
I prefer sort the scripts per importance.

**Comment by reduz** [comment]
How does importance work?

**Comment by Fiona** [comment]
I think they mean they'd like to be able to manually sort script tabs by dragging them.

**Comment by BBric** [comment]
Yes, it's that, and by importance i would want say the scene script in first, then the fundamental classes and finally the utilities or others (for example).
With the tabs it was possible to organize them, it's the same thing.

**Comment by bitwes** [comment]
I'd second being able to drag them.  I've gone so far as to reopen scripts in the order i want them.  

On the flip side, it's not that big of a deal to reopen , mash ctrl+w to close tabs and then use the resources tab to one-click open them in the right order.  I usually find that I have too many things open when I get the urge to reorder...but still, dragging would be great.

**Comment by KillerJaguar** [comment]
Dragging and right-mouse-button context menus are both things I want to see added in general

**Comment by bitwes** [comment]
I may have to retract what I said earlier.  Just built from source and the new layout is great.  This specific item doesn't even make sense anymore, though it could be applied to the vertical list of scripts.

**Comment by reduz** [comment]
I think calling ._init() is also valid

**Comment by akien-mga** [comment]
The script listing in the current master branch has changed since this bug report, so I think it's no longer relevant. I'll check if there is the ablilty to reorganise scripts in the list though, and open a new issue if not.
