### ISSUE TITLE
GodotSharp solution build error on Windows if engine and project not on C: drive

### ISSUE THREAD

**Issue by ChinaChenMingQuan** [godotengine/godot#21834]
Godot version: 3.0.6

PC System: Windows 7 x64.
PC Language: China Chinese.

Mono from: https://www.mono-project.com/download/stable/#download-win.

Mono Installation:
![qq 20180907205113](https://user-images.githubusercontent.com/32387920/45220253-24864d80-b2e0-11e8-8829-d0d6eee5a6e6.png)

Visual Studio Installer:
![qq 20180907205611](https://user-images.githubusercontent.com/32387920/45220378-80e96d00-b2e0-11e8-9d88-e05cf2ae2299.png)
![qq 20180907205540](https://user-images.githubusercontent.com/32387920/45220379-81820380-b2e0-11e8-9d8d-3131c38e0784.png)
![qq 20180907205524](https://user-images.githubusercontent.com/32387920/45220380-821a9a00-b2e0-11e8-95ea-f6c97d954ae7.png)

But godot engine build error, error image:
![qq 20180907204456](https://user-images.githubusercontent.com/32387920/45220451-bb530a00-b2e0-11e8-931c-c8529258ddeb.png)

I do not know, This what bug ?

**Comment by KellyThomas** [comment]
I've seen  people have discuss this "D:\Release\" error message before.  For them the error only occured when running Godot from a drive other than C: drive.

Can you please try running from C: to see if it helps on your PC too?

**Comment by ChinaChenMingQuan** [comment]
![qq 20180907220618](https://user-images.githubusercontent.com/32387920/45223619-4d134500-b2ea-11e8-9ee3-cbb20528fd3d.png)


@KellyThomas, In C: drive run godot engine, not success, result: Failed to build GodotSharp solution.

**Comment by KellyThomas** [comment]
Thanks for testing!

**Comment by ChinaChenMingQuan** [comment]
@KellyThomas, so this is bug?

**Comment by KellyThomas** [comment]
It looks like it.  It also looks like it might have a different cause for you, not the same as the other cases I was reading about.

**Comment by ChinaChenMingQuan** [comment]
@KellyThomas, Oh my God, Move godot engine to C: drive and move game project to C: drive, success, is success !!! But have one problem, my game project very big, my C: drive capacity very little.

**Comment by Zireael07** [comment]
@neikeq why does it seem to require both project and engine on c: ?

**Comment by Fefe-Hern** [comment]
I've had the same issue as well, but I'm going to assume moving Godot and the project to the main drive would work properly.

**Comment by neikeq** [comment]
So this bug only happen when the project is located on a drive other than `C:`?

**Comment by ChinaChenMingQuan** [comment]
@neikeq, yes, only happen when the project is located on a drive other than C: drive.

**Comment by Kiotenhariyo** [comment]
Hopefully this gets changed. Really hurt trying to get a project started from D: lol
Limit C: space also.

**Comment by nairdaen** [comment]
I have Godot engine and project folders in my D drive, and creating a "release" folder in D like "D:\release" fixed the problem.

**Comment by Astrych** [comment]
Same issue with Godot 3.1 beta 2. Creating project on drive different then C: shows above error. Project in default directory works without issues. How to workaround above issue? Create first project in default location and build solution. After that creating or porting projects on different drives will start working. I think that Godot during building solution creates `C\:Release` directory and saves it's location to:
 `C:\Users\ <username> \AppData\Roaming\Godot`. When we try to build first project on drives different then C: it can't create Release directory.

**Comment by neikeq** [comment]
Could anyone reproduce this error after changing `Mono > Builds > Build Tool` in editor settings from `MSBuild (Mono)` to `MSBuild (VS Build Tools)`? I could only reproduce it with `MSBuild (Mono)`.
