### ISSUE TITLE
Scrolling an ItemList which is inside a ScrollContainer will also scroll the ScrollContainer

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21848]
**Godot version:**
v3.0.5-stable_x11.64, Xubuntu

**Issue description:**
Scrolling an _ItemList_ which is inside a _ScrollContainer_ will **also** scroll the _ScrollContainer_.
If the mouse is over the _ItemList_'s scroll bar it works fine instead.

**Minimal reproduction project:**
[scroll_bug.zip](https://github.com/godotengine/godot/files/2362576/scroll_bug.zip)

**Comment by girng** [comment]
nice catch. looks like the focus outline needs to be clipped as well
![](https://i.gyazo.com/d861bb4f51a84fe214194064ee4fac64.png)

**Comment by char0xff** [comment]
@girng Yes, that's already been issued in #9612.
