### ISSUE TITLE
Allow discarding signal arguments for method call

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#21844]
Simple use case: you have a node, which has an AnimationPlayer. You want it to play the animation and disappear. However, since `animation_finished` requires one argument, you can't just connect it to `queue_free()` and be done. You need to create a script, which literally has one line, which is a single dummy method that call queue free, while ignoring the passed argument.

IMO there should be an _option_ to connect signal to method that requires less arguments and allow us to discard unnecessary arguments if needed.

**Comment by Faless** [comment]
I second this, it could be an extra flag to `connect`, something like `CONNECT_NO_ARGS`

**Comment by PetePete1984** [comment]
The old Space Shooter demo just used func tracks that call queue_free after the animation is done. Just need to remember to save the scene before testing the animation, otherwise your node is gone..

**Comment by KoBeWi** [comment]
Closing this in favor of https://github.com/godotengine/godot-proposals/issues/762
