### ISSUE TITLE
Can't use variable in Vector3 constructor in VisualScript

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#21840]
**Godot version:**
3.1 Alpha

**Issue description:**
You currently can't use a variable in the Vector3 constructor using VisualScript.
**If you use the variable for all axis though, it works.**

**Steps to reproduce:**
Make a VisualScript script with a variable and use this variable in a Vector3 constructor, then print the result. It will return null. 

**Minimal reproduction project:**
[Cant use variable in Vector3 constructor using VisualScript.zip](https://github.com/godotengine/godot/files/2361711/Cant.use.variable.in.Vector3.constructor.using.VisualScript.zip)

**Comment by fire** [comment]
It's similar but not the same as https://github.com/godotengine/godot/issues/18024

**Comment by Jummit** [comment]
I was wondering, what exactly goes wrong so that if you take the variable on all axis, it works fine?

**Comment by fire** [comment]
It's related to some sort of default value. If you go to each axis and set the values to 0 for example, it doesn't break.

**Comment by akien-mga** [comment]
Fixed by #22944.
