### ISSUE TITLE
Remove keyframing for CollisionShape

### ISSUE THREAD

**Issue by othelarian** [godotengine/godot#2185]
It's a little bit confusing, and I take two days to understand that collision shape can't be animate in game.

By the way, some information may be useful in the class doc, like the use of the trigger, and the non usage of animation in game.

**Comment by OlexiyKravchuk** [comment]
yes it is impossible because it does not exist at the time of execution, as node.

**Comment by reduz** [comment]
Plan is to keep it for 1.2

**Comment by KillerJaguar** [comment]
So you'll be able to keyframe collision shape in animations for 1.2?

**Comment by reduz** [comment]
yeah

On Thu, Jun 25, 2015 at 11:13 AM, Robert Hernandez <notifications@github.com

**Comment by eska014** [comment]
Resolved per 2580ca01e6b73a54def5a8f6e61d19509d3278ee.
