### ISSUE TITLE
TOWARDS 3.1 BETA - Let the bug hunt begin!

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#21855]
![image](https://user-images.githubusercontent.com/6265307/45248630-f73e9d00-b2e9-11e8-9cb5-7878c6ed8794.png)

### Issue Tagging

I have gone through the entire [3.1 bug list](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc). It is currently (September 7) at 576 open bugs. 

I took the work of assigning issues to most contributors, so if you are tagged, you can easily check which issues are assigned to you.

### Issues by Contributor

Here is a rough list of issues by contributor:

[reduz](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3Areduz) - 207 issues 
[neikeq](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3Aneikeq) - 43 issues
[vnen](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3Avnen) - 36 issues
[hpvb](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3Ahpvb) - 32 issues
[karroffel](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3Akarroffel) - 26 issues
[odino](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3AAndreaCatania) - 26 issues
[groud](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3Agroud) - 21 issues
[MarianoGNU](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3AMarianoGnu) - 19 issues
[paulb23](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3APaulb23) - 9 issues
[faless](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3AFaless) - 9 issues
[Hinsbart](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3AHinsbart) - 8 issues
[RandomShaper](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3ARandomShaper) - 8 issues
[JFonS](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3AJFonS) - 7 issues
[ifire](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3Afire) - 2 issues
[bojidar_bg](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3Abojidar-bg) - 5 issues
[eska014](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3Aeska014) - 5 issues
[mux213](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+assignee%3ABastiaanOlij) - 4 issues

(Not here and have issues assigned? let me know)

Yes, the amount of issues assigned to me is pretty high, but unlike the rest of the contributors, I work full time on Godot all seven days of the week :-P. Of course help is always appreciated.

If you believe an issue that I assigned does not belong to you, please let me or @akien-mga know, so we can re-assign it to the proper contributor. Don't just un-assign it yourself :)

### Not listed?

If you believe yourself capable and are not on the list, but you still want to help. Or if you are done with your issues (or want to take a break), feel free to take issues from other contributors, starting by those who have the highest amount (the includes me of course! ).

If you have not done much Godot development and want to start getting into fixing issues (which is a great learning experience), we have re-introduced the [Hero Wanted!](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.1+sort%3Acreated-asc+label%3A%22hero+wanted%21%22) tag, which are great bugs to get you started. They include a description and hints on how the bug could be approached.

### Feature Freeze

Remember that we are now in Feature Freeze, so no new features will be added. Please focus your effort on fixing issues, so we can get 3.1 out of the door as soon as possible!

**Comment by RiverMesa** [comment]
> Remember that we are not in Feature Freeze, so no new features will be added.

Isn't this a bit...Contradictory?

**Comment by neikeq** [comment]
:beetle: :ok_hand: :gun: :joy:

**Comment by samvila** [comment]
Any news on these reports?:

#19659
#12795

And for the Godot to Blender exporter: 

https://github.com/godotengine/godot-blender-exporter/pull/91

**Comment by Nodragem** [comment]
On my browser, I see 3931 issues :/ even with solving 576, there will be 3355 remaining? which sounds a bit discouraging! :) 

Are there a lot of duplicates and non-issues in the list? if the issue list is cleaned up, would we expect to go under 1000 issues remaining after the hunt? 

In any case to solve these 576 issues would be a wonderful achievement; whatever remains in the list.

**Comment by novhack** [comment]
Issues are not bugs. There are feature requests and enhancement suggestions there as well. There are 1800 reported bugs over all and yes some might be duplicates, some are not relevant anymore and some might be already resolved but nobody noticed. For a software this size with so many users (that are actually reporting bugs properly) and contributors it's actually not that many bugs. Other engines which I will not specify most likely have more bugs than Godot you just don't know. 😀

**Comment by reduz** [comment]
> On my browser, I see 3931 issues 

Most are feature/enhancement requests, we are thinking of moving those to the Roadmap repo, otherwise the issue tracker is growing too big.

**Comment by Nodragem** [comment]
@novhack, yep, that's true that a lot of the issues are feature requests. We might need a regular cleaning of the issues, closing the irrelevant ones, and of the feature requests (we can't accumulate all of them forever). It is not because we are smaller and have less bugs than a big game engine that we don't need to make efforts to prevent us from reaching an unmanageable situation with bugs.
@reduz, yep, it would be wise to somehow separate bugs and feature requests. Feature requests may have a natural tendency to accumulate because they can't be closed until they are implemented or formally refused. Maybe it could help reassuring Github's visitors to see on the main Github page how many of the issues are bugs / feature requests. That way, visitors would see the number of bugs decreasing or being reasonable. Not sure how important that statistics can be for people to start or continue to use the engine.

**Comment by clarkejm** [comment]
I know it's fairly new but has anyone had a chance to confirm if #21739 would be considered a bug or feature (imported multi-material meshes that otherwise render correctly don't render correctly when used in CSGMesh)
thanks in advance!

**Comment by LikeLakers2** [comment]
> I have gone through the entire 3.1 bug list. It is currently (September 7) at 576 open bugs.

It sort of bothers me that some of the 3.1 bugs got set to the [3.2 milestone](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3Abug+sort%3Acreated-asc+milestone%3A3.2). Wouldn't it be easier to just fix those now instead of moving them...?

**Comment by akien-mga** [comment]
> It sort of bothers me that some of the 3.1 bugs got sent to the 3.2 bug list. Wouldn't it be easier to just fix those now instead of moving them...?

If a bug is moved to a later milestone, it means that we can't reasonably spend time fixing it now, without pushing the current milestone further needlessly.

Yeah, some bugs are old and get moved to the next milestone often, but that's how software development works. You can't fix all bugs that ever existed for a given release, and most importantly, you *shouldn't*. If we tried to do that, it would mean:
- Feature freeze for 3 years
- No PRs accepted unless it's strictly a bug fix and was tested by 20 users
- 3 years without any release, without anyone talking about (or using) Godot

I doubt that's what the community would want :)

If we are now moving issues to the 3.2 milestone (or removing them from a milestone altogether), it means that we don't consider them must-fix for 3.1 to be a good release. That's our call and users are welcome to challenge it if they think it's a wrong assessment, but you can't ask us to fix them in priority if we just decided that they're not so high priority.

**Comment by nobuyukinyuu** [comment]
Now to pray to the gods of godot that my pet issues get fixed in time for release  😂

**Comment by ZX-WT** [comment]
#18549 I haven't check this bug in master but if this still exist, shouldn't this also be on the list?

**Comment by LikeLakers2** [comment]
> If a bug is moved to a later milestone, it means that we can't reasonably spend time fixing it now, without pushing the current milestone further needlessly.

Okay, now that I understand. Sorry if I sounded like I was complaining.

**Comment by Garrom** [comment]
Oh guys, I love you all. Too bad that I can't understand C/C++, I so badly wish to help you with it...

**Comment by mhilbrunner** [comment]
@Garrom Godot is a great way to learn C++ and to get into contributing to Open Source. I had a great experience with it. Don't be afraid, just start doing! There are a lot of helpful people around.

That said, you can also contribute in other ways: by testing and triaging issues, improving the documentation, by spreading the word or even donating. See [Ways to Contribute](http://docs.godotengine.org/en/latest/community/contributing/ways_to_contribute.html).

**Comment by islam1999h** [comment]
make it easy to use
support .fbx .mp3 .unitypackage

**Comment by islam1999h** [comment]
making game easy and fast
like this tool: https://assetstore.unity.com/packages/templates/systems/game-creator-89443
I think this is the next generation tool should be built-in any game engine
i hope to see that in godot 4.0

**Comment by groud** [comment]
@islam1999h please, this is not the topic here. We're not here to discuss feature requests.

**Comment by islam1999h** [comment]
Sorry but where can I discuss feature requests? @groud

**Comment by groud** [comment]
@islam1999h Create another issue on Github, and be specific on the feature you need.

**Comment by Nodragem** [comment]
how is the bug hunt going?

**Comment by akien-mga** [comment]
Superseded by #24822.
