### ISSUE TITLE
Re-organize files from within Godot while keeping connections

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#2186]
Like the title says, since Godot 1.2 is focusing on usability, I think what would increase the usability by quite a bit is to add re-organization functionality in the file browser window (functionality that will keep all of the connections intact if possible)

_______________________________
BENEFITS::
--------------------------------------------------------
 - Less need to plan ahead as the game is worked on
 - Vastly increased ability to keep a project organized as it grows (without requiring hours of work to re-connect everything).
 - Gives more room for experimentation
 - More accessibility to people who aren't seasoned game developers

I hope you will find this a good idea, as I think file-structure management is an important thing to have in any creation software.

**Comment by reduz** [comment]
oh yeah this is on the list for 1.2, i've been slowly closing stuff on it
(changed them to strikethrough) but still have many of them left to do

**Comment by slapin** [comment]
I think ability to relink stuff on demand should be useful, too...

**Comment by akien-mga** [comment]
I think there's a feature for that in the filesystem dock, but I haven't tested it much so I don't know if it addresses this feature request fully.

**Comment by reduz** [comment]
i think this works already

**Comment by akien-mga** [comment]
Alright, I'll close it to reduce the number of tasks at hand, but I'll remember to do some testing of the feature to check for potential remaining improvements to do.
