### ISSUE TITLE
Loading a JPG image gives an image with an alpha channel

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#21867]
Godot 3.0.6

As found in https://github.com/godotengine/godot/issues/18882#issuecomment-389115304, loading a JPG  gives an image with an alpha channel, even though JPG cannot contain one.

**Comment by Chaosus** [comment]
Yeah, its still present in 3.1 ex:

```
var image = Image.new()
image.load("res://Moon.jpg")
var format = image.get_format() # format is 5 which is FORMAT_RGBA8
```
