### ISSUE TITLE
Way to export Direct References to Nodes in Scene Tree

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#21875]
**Feature Proposal:**
It's something that has always been really awkward in Godot, why don't we have a way to point to an Node as a reference rather than only use it's node path.

When you move from Unity this might be the biggest difference that Godot's NodePath is more useless than Magikarp (hello poke fans). 

Case and point, all that NodePath does is store a string in a wrapper object and provide some helper functions. Atleast that's what it seems to be doing.

Ok so references might not be possible(easy to implement) but callbacks are can't we have communication between the nodes in the scene tree similar to how dependencies work in the FileSystem dock. It knows where it's being refered to for Resources.

It's not a necessary feature, might be.
But an important one. YES. I am sure about that.

It will add soo much more ease of use to the Godot system.

**Comment by vnen** [comment]
Isn't this the same as #7821?

**Comment by akien-mga** [comment]
I don't understand what feature you're proposing...

**Comment by swarnimarun** [comment]
@vnen @akien-mga Yeah it's the same as #7821 so closing it now but I would really like to see some work on it.
