### ISSUE TITLE
Vibration does not work

### ISSUE THREAD

**Issue by SmithJohnFirst** [godotengine/godot#21870]
**Godot version:**
3.1 alpha

**OS/device including version:**
Android 6.0.1 / SAMSUNG Galaxy A7

**Issue description:**
Vibration does not work.
I added the possibility of vibration to my project. I used the function `start_joy_vibration`. When I tested my project on a PC with a XBox gamepad, it worked.
I exported my project to Android. Vibration does not work.

**Comment by vnen** [comment]
Vibration for phones isn't implemented, see #4833.
