### ISSUE TITLE
Run system command [GDScript]

### ISSUE THREAD

**Issue by Allespro** [godotengine/godot#21881]
**Hi. Can someone help me?**
I need run system command in game, for example "ping example.com"
How can I do that?

_In c++ I can use "cstdlib" library and function "system"_

**Comment by AlexHolly** [comment]
`OS.execute` ?

**Comment by eon-s** [comment]
For questions like this go to any of the community channels (the recommended are the Q&A and Discord)
https://godotengine.org/community

This place is for engine development (bug report, proposals, etc.).

**Comment by groud** [comment]
Closing as not a bug.
