### ISSUE TITLE
Large Particles2D shapes not rendering unless their center is visible.

### ISSUE THREAD

**Issue by chaosdrop** [godotengine/godot#21887]
**Godot version:**

3.1 Alpha and Master build as of 9/8/2018

**OS/device including version:**

GTX 970 official drivers

**Issue description:**

Large Particles2D shapes such as a box 1500x500 do not render until the center point is visible. Which causes them to just suddenly pop in to existence.

**Steps to reproduce:**

**Minimal reproduction project:**

[Particles2D POPIN.zip](https://github.com/godotengine/godot/files/2363978/Particles2D.POPIN.zip)

**Comment by Bauxitedev** [comment]
I think you need to increase the visibility AABB to match your particle's emission box.
You can do that either manually by increasing the width/height of the Visibility Rect...
![1](https://user-images.githubusercontent.com/31383123/45262963-391e2f00-b421-11e8-98cb-f5d6424ca550.png)
...or automatically by going to `Particles → Generate Visibility Rect` on the toolbar...
![2](https://user-images.githubusercontent.com/31383123/45262967-4d622c00-b421-11e8-91da-c5fbdf19f64d.png)

**Comment by chaosdrop** [comment]
That fixed it, I would have never guessed to try that due to it's description in the documents being. "Editor visibility helper." I thought it only existed to make seeing the Particle area easier in the editor.

**Comment by Zireael07** [comment]
AABB really should get a better description (I tried fiddling with one of my meshes' AABB to no avail, for a similar reason as here)

**Comment by chaosdrop** [comment]
I've never contributed to a git project before, but perhaps this would be a good place to learn and start. As I often run into circumstances with the API documentation in godot where just a little more information would make a world of difference. 

How dose this sound:

**Comment by chaosdrop** [comment]
I think I've figured git out enough to make a pull request properly.
Though the CONTRIBUTING.md says I should talk to other developers before making a pull request. Since I don't use IRC I'm guessing this issue is as good as any place to ask to make sure it's okay if I start trying to contribute extra details to the Class References.

**Comment by JFonS** [comment]
@chaosdrop The "ask other developers" thing is there mainly to avoid the situation where someone works for many hours on a specific feature and it ends up being rejected. Documetation improvements are usually fine to PR, if something needs to be changed it will be discussed in th PR itself.
