### ISSUE TITLE
what about haskell bindings?

### ISSUE THREAD

**Issue by 221V** [godotengine/godot#21891]
hello

what about haskell bindings?
i think some people want have possible include haskell code, not only C/C++

thanks

**Comment by akien-mga** [comment]
There are no plans to make official bindings for any language other than the currently included ones.

Any other efforts are welcome but will not be part of the core engine and should be implemented via GDNative as community efforts, and thus discussed elsewhere.

There are already Haskell bindings provided by the community: https://github.com/SimulaVR/godot-haskell
