### ISSUE TITLE
32 bit release_debug Windows export crashes. 32 bit debug export works.

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#2189]
Doesn't matter whether on Windows 32 or 64 bit. The non-debug export always crashes after the splash screen.

Both exports in a ZIP:
http://www.mediafire.com/download/pmbri2nb2pfc27q/No_Rest_for_the_Wicked_Ones_-_DEMO_v0.96_-_win.32_-_testing_crash.zip

**Comment by reduz** [comment]
i could never figure why this happens, will give it a check at home
meanwhile if you can compile godot using visual studio, the release 32 bits
versions compiled with it seems to work fine

**Comment by ScyDev** [comment]
Would be great if you could fix this on the quick :)
I have no experience with Visual Studio... open project and compile? Or would I need to do a lot of configuring?

Is there any way I can get some log messages from the non-debug export?

Releasing the debug version would defeat the purpose of encrypting the scripts, right?

**Comment by reduz** [comment]
oh wait, I think I changed the bytecode format and forgot to raise the version number, may this be the cause?

**Comment by okamstudio** [comment]
meaning templates from the site will not work with github codebase

On Sat, Jun 27, 2015 at 10:47 AM, Juan Linietsky <notifications@github.com>
wrote:

> oh wait, I think I changed the bytecode format and forgot to raise the
> version number, may this be the cause?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2189#issuecomment-116050082>.
>



-- 

*OkamStudio*

**Comment by okamstudio** [comment]
also yes, it would probably better if you compile godot yourself. It's
really easy (most people is doing it atm) and there are instructions in the
site,
just get visual studio 2013, python and scons

https://github.com/okamstudio/godot/wiki/compiling_intro
https://github.com/okamstudio/godot/wiki/compiling_windows

On Sat, Jun 27, 2015 at 10:48 AM, Juan Linietsky <juan@okamstudio.com>
wrote:

> meaning templates from the site will not work with github codebase
>
> On Sat, Jun 27, 2015 at 10:47 AM, Juan Linietsky <notifications@github.com
> > wrote:
>
>> oh wait, I think I changed the bytecode format and forgot to raise the
>> version number, may this be the cause?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/okamstudio/godot/issues/2189#issuecomment-116050082>.
>>
>
>
>
> --
>
> *OkamStudio*
>



-- 

*OkamStudio*

**Comment by okamstudio** [comment]
if something goes wrong don't hesitate to ask here, on facebook or on irc

On Sat, Jun 27, 2015 at 10:51 AM, Juan Linietsky <juan@okamstudio.com>
wrote:

> also yes, it would probably better if you compile godot yourself. It's
> really easy (most people is doing it atm) and there are instructions in the
> site,
> just get visual studio 2013, python and scons
>
> https://github.com/okamstudio/godot/wiki/compiling_intro
> https://github.com/okamstudio/godot/wiki/compiling_windows
>
> On Sat, Jun 27, 2015 at 10:48 AM, Juan Linietsky <juan@okamstudio.com>
> wrote:
>
>> meaning templates from the site will not work with github codebase
>>
>> On Sat, Jun 27, 2015 at 10:47 AM, Juan Linietsky <
>> notifications@github.com> wrote:
>>
>>> oh wait, I think I changed the bytecode format and forgot to raise the
>>> version number, may this be the cause?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/okamstudio/godot/issues/2189#issuecomment-116050082>
>>> .
>>>
>>
>>
>>
>> --
>>
>> *OkamStudio*
>>
>
>
>
> --
>
> *OkamStudio*
>



-- 

*OkamStudio*

**Comment by ScyDev** [comment]
I DO compile Godot and the export templates myself.
The code is about 2 weeks old though...
Does it make a difference whether I compile on Linux or on Windows?

**Comment by reduz** [comment]
oh sorry, misunderstood. For some reason the export templates compiled on
linux for windows on release seem to fail. I'm not sure if this is
something related to mingw because i can't seem to get mingw to work on
Windows. I do know that export templates compiled with MSVC on release
work. The bytecode also changed some days ago so if you are using githu
head you will need to recompile templates

**Comment by ScyDev** [comment]
So... this isn't actually true: "The following is almost the same exact script we use to build all the export templates that go to the site. "?
https://github.com/okamstudio/godot/wiki/compiling_batch_templates

You don't build everything on Linux? You build on Windows, OS X and Linux separately?

**Comment by reduz** [comment]
templates are built on linux, but i am currently working on Widows

**Comment by ScyDev** [comment]
So the official win32 template isn't working either, since it is built on Linux?
And you are able to build the OS X templates on Linux too?

**Comment by reduz** [comment]
it seems the release version of the official one doesn't work.
OSX templates are built on a mac via ssh

**Comment by ScyDev** [comment]
I see. Well I hope you can find the problem soon :) Thanks for your answers.

**Comment by popcade** [comment]
Hi,
I can confirm this on a Win7 SP1 x64, the 32bit non-debug export crashes immediately on my system, any fixes expeted? Thaks.

**Comment by ScyDev** [comment]
@reduz Did you find something out? It's pretty crazy that we can't release win32 exports, with Windows still being the main gaming platform... :D

**Comment by popcade** [comment]
I compiled the recent reository with VS2013 Community and this problem seems gone away.

**Comment by reduz** [comment]
Yes its a gcc issue, if you compile with msvc it works

**Comment by ScyDev** [comment]
I managed to compile on Win8.1 with Visual Studio Express 2013, Python 2.7 and Scons.

Bit still, this needs to be fixed.

**Comment by draxdeveloper** [comment]
Sorry about not founding this issue before and creating another...
So using debug export will work? Also, since i am here... When we export from godot it's comes with the godot logo before the game starts, i can change this?
I will in fact put a "made with godot engine" but i will put it after the game have started.

**Comment by draxdeveloper** [comment]
Also, i will have to use godot on windows to export to windows???? :(

**Comment by ScyDev** [comment]
Yes, if you use the Win32 debug export it doesn't crash. But it is bigger, slower, contains debug symbols and therefore makes encrypted scripts less secure (I suspect).

I don't understand how this is not treated with the highest priority. Games exported with the official Win32 template just crash. How sick is that? :D

You can easily change the splash screen in project settings.

**Comment by reduz** [comment]
I am in france and away from the computer it makes the builds, so will only
be able to fix it in a week

**Comment by ScyDev** [comment]
This one needs urgent fixing! And compiling for OS X/iOS as well.

**Comment by alvin00221** [comment]
thanks for new update.. ill try at home. so excited.

**Comment by akien-mga** [comment]
Haven't heard about Windows issues for a while, is this still valid in the current master branch?

**Comment by popcade** [comment]
I downloaded the alpha release, the problem is still there, you have to compile with VS2013 from the source by yourself (and you WILL need to do this eash time Godot release a new version).

**Comment by akien-mga** [comment]
Thanks, setting as high priority for the release then, this will have to be sorted out.

**Comment by akien-mga** [comment]
Likely related to #1868.
