### ISSUE TITLE
The project list can't retain projects, starts up empty every time.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#21906]
**Godot version:**
hash 4b6846a

**OS/device including version:**
Win10 64 bit; Ryzen 2700X CPU; GeForce 1060 6GB GPU; 32 gigs RAM

**Issue description:**
When launching very recent builds of Godot, the project list is always empty. Every time you start up, you have to scan for the project file before you can work on it.

**Steps to reproduce:**
Place the following test project in the project list. Open the project and then quit Godot. Now open Godot and see if the project is still listed.

**Minimal reproduction project:**
[Test3.zip](https://github.com/godotengine/godot/files/2364488/Test3.zip)

**Comment by AlexHolly** [comment]
https://github.com/godotengine/godot/issues/21823

**Comment by Ace-Dragon** [comment]
Hi.

It's hard to check for duplicates when so many of the reports use very technical language without a plain description of the consequences that result.

I think it would be good if people started using more visual language in the titles and descriptions so making duplicate reports are easier to avoid.

**Comment by Chaosus** [comment]
Sadly, but its duplicate, and there is no "sticky" thread possibility on github to aware new users..

**Comment by KellyThomas** [comment]
> I think it would be good if people started using more visual language in the titles and descriptions so making duplicate reports are easier to avoid.

I find I have the opposite problem.  When I  try to search for specific keywords from the error message I often miss posts that describe the issue in general terms.  These (like #21823) often including an unsearchable screenshot showing the error.

In fact I found that issue earlier via a closed dupe that included the message as plain text.

It can be hard to write technical content that caters to all audiences.

**Comment by Chaosus** [comment]
I renamed the #21823 to the same name as #21868, so its more easy to find now..
