### ISSUE TITLE
Improve versioning and bw/fw-compatibility of editor settings

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#21903]
![screen shot 2018-09-09 at 12 33 39 pm](https://user-images.githubusercontent.com/930478/45266901-a9807c80-b430-11e8-99f1-4c914da9cd3c.png)

**OS/device including version:**
Mac OS X High Sierra

**Issue description:**

3.1 uses version 3.0 configs folder. Messes up 3.0s projects list.
~/Library/Application Support/Godot
Need to have a way to set this for testing.

**Comment by aaronfranke** [comment]
Perhaps add another set of subdirectories with versions, and on upgrading to a newer version, import from the highest previous one?

**Comment by wyattbiker** [comment]
Something like that. The devs should be able to figure this out easily. But you don't want to inconvenience thousands of testers. I can my suggestion for now is to make a backup if 3.0 configs exists in that Godot folder.

**Comment by akien-mga** [comment]
That's on purpose, and IMO it works relatively well. Most settings of 3.0 are still relevant in 3.1, so it makes sense to keep using the same config files instead of branching off for each minor version.

Otherwise we end up either losing configuration at each minor release (brand new config each time), or having to write tools that can parse the config of version N-1 (or N-X if you skipped a version) to convert it to version N. This is doable if there's really a strong need for it, but currently I think it works just fine.

**Comment by aaronfranke** [comment]
> (or N-X if you skipped a version) to convert it to version N.

Well, that is already a potential problem isn't it? If users skip a version they would have the same issues regardless of separate config folders.

**Comment by wyattbiker** [comment]
@akien-mga.  Agreed you don't want application versions folders floating around and managed by the Editor. But this is one of the dilemmas when testing and upgrading to new versions.

I think though this issue will be popping up in and will get serious because especially in production people may lose certain settings (due to bug or some change) and may even want to go back and use an old version.

My simple suggestion would be to put a version id _**Major.Minor.patch**_ in a file (e.g. editor_setting.tres) and provide a warning to users to backup their ~/Library/Application Support/Godot (or AppData I assume under Windows or ~/.godot ?? in Linux) before full launch. 

And for the hard cores provide a command line path to their settings. People will want to be able to fall back to prior versions or experiment. After all we are developers.

My 2 cents.

**Comment by vnen** [comment]
If you're using multiple versions, you should use them in self contained mode.

**Comment by Calinou** [comment]
I'll close this, as this enhancement request is now tracked in the Godot proposals repository: https://github.com/godotengine/godot-proposals/issues/269
