### ISSUE TITLE
Mac OS X Editor Settings fails to open path.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#21904]
![screen shot 2018-09-09 at 12 33 39 pm](https://user-images.githubusercontent.com/930478/45267196-e8fd9780-b435-11e8-9e4a-55088d1774b0.png)

Mac OS X High Sierra

Editor: Fails to open Editor Data/Settings with the following message:
**There is no application set to open the URL /Users/user/Library/Application%20Support/Godot.**

![screen shot 2018-09-09 at 1 37 18 pm](https://user-images.githubusercontent.com/930478/45267177-8c9a7800-b435-11e8-9e0d-93f2bc560f77.png)

**Comment by akien-mga** [comment]
@Calinou You should maybe prefix those paths in `shell_open` calls with `String("file://")`.
