### ISSUE TITLE
Variables changed by tool script not saving 

### ISSUE THREAD

**Issue by Hubber116sx** [godotengine/godot#21900]
**Godot version:**
v3.0.6.stable.official.8314054

**OS/device including version:**
Pop!_OS 18.04 LTS 

**Issue description:**
If a node with a tool script edits one of it's own variables while in the editor the variable will not be saved with the scene. (If this is working as intended and there is a way around this then please inform me of the workaround.)

**Steps to reproduce:**
- Create a scene containing a node with a tool script
- Give the node a variable and have the variable be changed by the tool script while in the editor
- Save the scene after the variable has been changed
- Close then re-open the scene (The variable would have reverted to it's default value)

**Minimal reproduction project:**
[godot_var_issue.zip](https://github.com/godotengine/godot/files/2364402/godot_var_issue.zip)

**Comment by vnen** [comment]
This is expected. Only exported script variables are saved in the scene file.

**Comment by Hubber116sx** [comment]
Is there a way to make the engine save a variable into the scene file even if it isn't edited as an exported variable?

**Comment by vnen** [comment]
@Hubber116sx you can implement the `_get_property_list()` to say that your variable is meant to be save (using a property hint). In doubt refer to our [community channels](https://godotengine.org/community) to get help.
