### ISSUE TITLE
Can't load any projects on MacBookPro late 2011.  Full logs supplied

### ISSUE THREAD

**Issue by therealrobster** [godotengine/godot#21917]
**Godot version:**
3.0.6 stable OSX

**OS/device including version:**
OSX 4.13

**Issue description:**
Godot Engine shuts down when opening an existing OR  a brand new project.

**Steps to reproduce:**
Run Godot on OSX 4.13 on a MBP late 2011.

LOGS:

https://pastebin.com/Wj8mKgmm

**Comment by girng** [comment]
> Intel HD Graphics 3000

might be related, afaik older drivers for this don't support some versions of opengl

**Comment by akien-mga** [comment]
macOS has terrible OpenGL drivers, especially for older cards like Intel HD 3000 where it definitely doesn't support OpenGL 3.3 needed for 3.0.6. And yet, Apple claims they do, so our version tests pass and you are not shown the more helpful message saying that OpenGL 3.3 is not supported and you therefore can't use Godot.

Sadly there's nothing we can do against Apple's carelessness regarding OpenGL support -- they even started deprecating it officially (which it had been officiously for half a decade, as poor drivers show).

In your case you might have more luck with [Godot 3.1 alpha 1](https://godotengine.org/article/dev-snapshot-godot-3-1-alpha-1) which supports down to OpenGL 2.1, which *should* be OK on that GPU, even on macOS. Note that it's a development build and some features are not complete (especially in the GLES2 backend).
