### ISSUE TITLE
Autocomplete no longer recognizes type under if-block checked by 'is'

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#21915]
**Godot version:**

af290f7b7d0ea22fbb8d4c3ca5c5a8fb72a30a7e

**OS/device including version:**

Linux

**Issue description:**

A type's autocompletion would appear under an if-block when that object's type has been checked; for a common example:

```
func _input(event):
    if event is InputEventKey:
        event.
```

In 3.0.6, autocomplete would give you this:
![image](https://user-images.githubusercontent.com/28724859/45269715-fe83b900-b457-11e8-8c21-028f4034cb7e.png)

Post-typed gdscript, this no longer works; the autocompletion for `event` under the if-block just displays the following:
![image](https://user-images.githubusercontent.com/28724859/45269646-24f52480-b457-11e8-8117-8bb1f4039f74.png)

Using typed gdscript, autocomplete works fine outside of the if-block (albeit just for the base class):
```
func _input(event : InputEvent) -> void:
    event.
    if event is InputEventKey:
```
![image](https://user-images.githubusercontent.com/28724859/45269721-2115d200-b458-11e8-8d91-ebfc9272dac4.png)

But inside the if-block, again, it displays `new` and some constants.

As of right now, it's necessary for the user to cast `event` before autocomplete will appear:
```
var key = event as InputEventKey
if key:
```

**Comment by akien-mga** [comment]
CC @vnen

**Comment by avencherus** [comment]
Been noticing this as well.  Wasn't sure about it though, since I had some other auto-completion issue.
