### ISSUE TITLE
Joy-con joystick doesn't have an axis mapping, and it becomes buttons

### ISSUE THREAD

**Issue by s0ra** [godotengine/godot#21918]
**Godot version:** 3.05 stable

**OS/device including version:** Windows 10 64-bit

**Issue description:** Joy-con joystick axis not aligned with the axis provided in the engine, Joy-con joystick becomes buttons

**Steps to reproduce:** Use a single Nintendo Joy-con and all axis don't have the mapping with the joystick

**Comment by akien-mga** [comment]
I synced the controller mappings a few days ago in #25188, and I see that it now includes Joy-Con bindings. Could you try with a recent nightly build from https://hugo.pro/projects/godot-builds/ (or Godot 3.1 beta 3 or RC1 once it will be released).

**Comment by s0ra** [comment]
I tried my Joy-Con's analog stick with the following code:
`func _input(event):
	print(Input.get_joy_axis(0, 0))`
It only prints out zeros. 

with the following code:
`func _input(event):
	for i in range(20):
		if Input.is_joy_button_pressed(0, i):
			print(true)`
Godot still thinks the stick as buttons

**Comment by akien-mga** [comment]
Could you test it with http://www.generalarcade.com/gamepadtool/ and, if working, retrieve the matching mapping?

**Comment by s0ra** [comment]
I set up mapping and set mapping as environment variable, but it still prints out zeros.

**Comment by akien-mga** [comment]
Godot doesn't use mappings from environment variables. You should add it in the relevant section in https://github.com/godotengine/godot/blob/master/main/gamecontrollerdb.txt and compile the engine from source. If it works, it should be contributed back upstream to https://github.com/gabomdq/SDL_GameControllerDB

**Comment by s0ra** [comment]
I might do it later. Is it not something urgent?

**Comment by Hinsbart** [comment]
Godot does indeed try to read mappings from the environment variable `SDL_GAMECONTROLLERCONFIG`: https://github.com/godotengine/godot/blob/caf5e921210eb893a95e674b7477d13cc9a34d39/main/input_default.cpp#L687-L696

**Comment by akien-mga** [comment]
> Though it reads those first and the default ones afterwards, so mappings from the env variable will get overridden if also present in the defaults..

This is addressed in #34908.

Regarding the non-working Joy-con gamepad, there have been various updates to the SDL2 mappings and our copy since then, so it might have been fixed. Please test in the latest 3.2 builds whether it's working.

**Comment by akien-mga** [comment]
This might actually have been due to #34910. Can you check if you still have the bug in 3.2 beta 5, and if so, whether that PR fixes it? (should be in the next 3.2 build)

**Comment by akien-mga** [comment]
I'll assume this is fixed for now by #34910.

Please comment if it is not. In that case, it would likely be fixable by contributing updated mappings to this repository: https://github.com/gabomdq/SDL_GameControllerDB

**Comment by HEAVYPOLY** [comment]
Maybe the issue has something to do with Joycons having a split (L) (R) mode vs combined mode (L+R)

Joycon (R) mapping is working well for me, except for 1 problem.

Joystick Left and Right show up as:
button_index 14
button_index 15

Also,  ZR (lower bumper), R (upper bumper) show up as:
button_index 14
button_index 15

Is it possible to remap ZR and R to different index?

**Comment by HEAVYPOLY** [comment]
got it working by creating a new map on SDL2.  This is for when you want to use a Joycon(R) vertically.  If you want to use it horizontally, the existing godot mapping works better
7e050720000000000000504944564944,Joy-Con (R),platform:Windows,a:b2,b:b0,x:b3,y:b1,back:b12,start:b9,leftstick:b11,leftshoulder:b14,rightshoulder:b15,-leftx:h0.1,+leftx:h0.4,-lefty:h0.2,+lefty:h0.8,

**Comment by fenixn0909** [comment]
Just tried both Joycon (L) & (R) via my MBP OX version: 10.15.7 with godot 3.2.4.rc2.
using the project mad by meloonicscorp on reddit, you can find the project link on his post:
https://www.reddit.com/r/godot/comments/ej6tpq/i_did_some_research_on_gamepad_behaviour_that_id/

Both two joycon got axis from joystick,and almost all buttons works fine even press the joystick generated index = 8.
but when i press L,R,ZL,ZR there's no signal detected.

Has anyone tired them yet?
