### ISSUE TITLE
AnimationTrackKeyEdit "Easing" editor picks up unintended mouse-drag 

### ISSUE THREAD

**Issue by bfishman** [godotengine/godot#21912]
**Godot version:**
3.1 alpha 1 (feature lock release, from https://downloads.tuxfamily.org/godotengine/3.1/alpha1)

**OS/device including version:**
Widnows 10

**Issue description:**
When dragging a resource into the 'value' field of the `AnimationTrackKeyEdit`, if the mouse passes over the "Easing" window, the easing graph is modified.

**Steps to reproduce:**
Create an animation track for a texture and insert a key-frame
open the AnimationTrackKeyEdit by clicking the key frame's diamond (in the animation editor)
drag some asset from the FileSystem onto the AnimationTrackKeyEdit (do not release mouse)
move mouse over easing window, and notice the easing values change.

The easing value should only change if the most recent mouse-down event took place inside of its control's bounding box

**Minimal reproduction project:**

**Comment by rcorre** [comment]
Just hit this, here's a visual:

![out](https://user-images.githubusercontent.com/2496231/72068363-e07bd200-32b2-11ea-9a20-c930614dd0bf.gif)

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3
