### ISSUE TITLE
Can't run my game on Windows 7 64

### ISSUE THREAD

**Issue by gravit22** [godotengine/godot#21919]
I didn't find similar issues

**Godot version:**
 3.0.6 

**OS/device including version:**
 My Os Ubuntu 64 GT 1030 

**Issue description:**
When I export game from export template for Windows 7 it doesn't run on Windows 7 64 maybe other But I know only about it. The game works perfectly fine on linux and Mac export files.

**Export as "exe" file for Windows**

**Comment by gravit22** [comment]
Yes. Here is my game https://drive.google.com/open?id=1t0hMe5Ee0-0wSW6aiMKwlKiEOHK0yv44

**Comment by akien-mga** [comment]
What are the specifications of the Windows 7 system you tried on? Especially what GPU?

**Comment by qarmin** [comment]
For me the problem is with your code, beacause you have the same name for function and variable(Windows don't recognize size of chars) but I think that things Godot should format.

0:00:00:0269 - Function declaration of 'up()' conflicts with a variable of the same name.
----------
Type:Warning
Description: Function declaration of 'up()' conflicts with a variable of the same name.
Time: 0:00:00:0269
C Error: FUNCTION_CONFLICTS_VARIABLE
C Source: res://Fighters/Fighter.gd:198
C Function:

**Comment by gravit22** [comment]
> What are the specifications of the Windows 7 system you tried on? Especially what GPU?
Windows 7 64, GTX 7xx. But I had reports about this bug from different specs. 

> 0:00:00:0269 - Function declaration of 'up()' conflicts with a variable of the same name.
I even don't know where to see such bugs, Can you tell me where? I didn't have any in my error window.

**Comment by qarmin** [comment]
I used godot 3.1 master (can be downloaded in https://hugo.pro/projects/godot-builds/ or compiled manualy) which automatically show in debugger this warnings

**Comment by girng** [comment]
ok well i was just going to mention about disabling the typed gds warning stuff, but i saw his main op said 3.0.6
in any event, Project Settings -> GDScript -> Warning -> Disable that
and treat warnings as errors. then export, should help i think

**Comment by gravit22** [comment]
I get a bit confused... So in order to fix this problem I need change names of variables or functions?
Yes. I use 3.0.6 I won't use 3.1 for that because I don't want my game to be broken completely... Can I fix that or Do I need to wait for problem to be fixed?

**Comment by qarmin** [comment]
Did you try do a copy this project and open with Godot 3.1?
For me Godot should working with this code, but at this moment you must change name of your functions(It would be easier than variables because functions have after name a bracket and it is easier to find it and change name)

**Comment by gravit22** [comment]
I am sorry I found the problem... I exported for linux and for windows in the same time. And when I checked it on linux I thought that .pck file is only for linux run file. and after that I zip it and delete the .pck file and I gave .exe file without .pck file. I am sorry It's my fault. Thank you for your time and patience. You can close this topic.

**Comment by ferhand** [comment]
Ups, I make the same mistake yesterday and had the same behaviour on windows 7 64 bits... 📦 
Ja, ja, ja :D ....sorry for that... :/
