### ISSUE TITLE
GLES2   Performance.get_monitor() functions do not work on GLES2

### ISSUE THREAD

**Issue by aurodev** [godotengine/godot#21928]
Performance.get_monitor() functions do not work on GLES2 in a running scene or in the editor.

**Godot version:**
Godot v3.1 Alpha Official

**OS/device including version:**
Windows 8.1 64bit, 8GB AMD FX 6350 6 core
Graphics Chipset
AMD Radeon HD 7700 Series
Memory Size 1024 MB
Radeon Software Version 17.4.4

**Issue description:**
Performance.get_monitor() functions do not work on GLES2

**Steps to reproduce:**
Setup a basic scene with Performance.get_monitor functions.
Toggle between GLES3 and GLES2

**Minimal reproduction project:**
[Perf_get_monitor_3.1Alpha .zip](https://github.com/godotengine/godot/files/2366362/Perf_get_monitor_3.1Alpha.zip)

**Comment by aurodev** [comment]
Seems for GLES2   VisualServerRaster::get_render_info(...)  calls
 int RasterizerStorageGLES2::get_render_info(VS::RenderInfo p_info) {
	return 0;
}
 which isn't yet implemented.

**Comment by OBKF** [comment]
This is why information label shows zeros
![normal_bug](https://user-images.githubusercontent.com/12987951/53881223-6552eb00-4013-11e9-85cf-da9a65c9442c.png)

**Comment by KoBeWi** [comment]
Seems ok in 3.2.4 beta2, can someone confirm?

**Comment by Calinou** [comment]
Seems fixed as of 3.2.4beta2:

![image](https://user-images.githubusercontent.com/180032/99879542-fd40a000-2c0d-11eb-83a4-76ed593f3c79.png)
