### ISSUE TITLE
Rename collision layers

### ISSUE THREAD

**Issue by robertdhernandez** [godotengine/godot#2192]
A 10x2 checkbox isn't very helpful to indicate what layer is what. It would be helpful to be able to rename each layer so you know what they're for.

**Comment by reduz** [comment]
blender uses the same thing and it generally works, but I agree that it
would be a good idea to change them per project

**Comment by KillerJaguar** [comment]
Yeah, it should be a per-project thing. I got the idea from Unity which does that.

**Comment by neikeq** [comment]
I second this. The same would be good for light masks. On big projects, it's quite difficult to remember what is each layer related to, specially with big teams; unless you have a draft with notes about it.

**Comment by reduz** [comment]
Should be doable i guess

**Comment by reduz** [comment]
let's do this for 2.1, we are in kind of a hurry for 2.0

**Comment by neikeq** [comment]
Is this still planned for 2.1? :)

**Comment by Zylann** [comment]
I need this as well, a non-coder friend helps to make levels for me but it's difficult for him to remember the layers.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by neikeq** [comment]
Implemented by 4338c90
