### ISSUE TITLE
GLES2 Chaning scenes sometimes results in a messed up editor UI, colors becoming transparent

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21930]
**Godot version:**
3.1 5707034

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
When I changing scene([from  3D tutorial](https://godot.readthedocs.io/en/latest/tutorials/3d/fps_tutorial/index.html)), sometimes I see that theme crash. After theme crash I can see a big slowdown, even several times

Videos with this strange behaviours:

https://streamable.com/ira9l
https://streamable.com/9l0cm

Log from cmd from this: [GLES2.txt](https://github.com/godotengine/godot/files/2366483/GLES2.txt)

*Bugsquad edit:* Error spam consists of:
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1280        Severity: High  Message: Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 1938861751) <target> 0 is not valid.
   At: drivers/gles2/rasterizer_gles2.cpp:111
...
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1281        Severity: High  Message: Error has been generated. GL error GL_INVALID_VALUE in (null): (ID: 173538523) Generic error
   At: drivers/gles2/rasterizer_gles2.cpp:111
```

**Comment by girng** [comment]
probably a rare edge case of maxxing out a intel hd 4600 by scene switching as fast as possible :P

**Comment by qarmin** [comment]
i7 4770S

This error occurs at different times. First time I had to change scene several times, but different time I change scene only once and it happened.

**Comment by qarmin** [comment]
Issue still exist, but now when editor change color, I don't see any slowdown - https://streamable.com/zdboj

**Comment by akien-mga** [comment]
Thanks, it's an impressive bug :D

**Comment by qarmin** [comment]
Can't reproduce bug with master
