### ISSUE TITLE
High-level multiplayer not working over Ethernet and Wi-Fi

### ISSUE THREAD

**Issue by Nitroretro** [godotengine/godot#21948]
**Godot version:** 3.1 alpha 1

**OS/device including version:** Arch Linux and Android

**Issue description:** (LAN game) The host is on Arch, and the client is on Android. When they are both connected to the network using Wi-Fi, I can connect just fine. But when I connect my PC to the network via Ethernet, I can't connect to the server anymore. (signal `connection_failed`)

(Side note: I'm using PacketPeerUDP on the server to send UDP broadcasts via LAN so the client can find the server easily, and when connecting the host to the network via Ethernet the broadcasts are still being received by the client, therefore this is only an issue with the high-level multiplayer API.)

**Steps to reproduce:**
1) Open up a project that uses high-level multiplayer.
2) Have the host or client be connected via Ethernet and the other via Wi-Fi.
3) You can't connect to the host using the high-level multiplayer API.

**Minimal reproduction project:** You can try it with the official Pong Multiplayer demo.

**Comment by akien-mga** [comment]
CC @godotengine/network

**Comment by LinuxUserGD** [comment]
similar: https://github.com/godotengine/godot/issues/14627

**Comment by Nitroretro** [comment]
@Faless I have no idea mate, and yes, I do have the `Internet` permission, I'm not binding to a specific interface and I'm connecting to the right IP. I will try some stuff tomorrow and see if I can try to fix it. Thank you for the response.

**Comment by LikeLakers2** [comment]
This sounds to me like something between the two (i.e. the WiFi router) could be blocking one from connecting to the other, as I doubt Godot would really even care whether you're on Ethernet or WiFi. See if you're able to ping one from the other, while one is connected to Ethernet.

**Comment by Nitroretro** [comment]
@LikeLakers2 Yes, that's basically what was happening. I think my router considers them to be two different networks. If I send a UDP packet to 255.255.255.255 the router still forwards it to everyone on the network, but if I send it to 192.168.1.5 (phone's LAN IP) it doesn't receive anything. Thank you, closing as this is not a Godot Engine issue.
