### ISSUE TITLE
Frame Jitter in GLES3 but Not in GLES2

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#21947]
**Godot version:**
3.1 alpha

**OS/device including version:**
Windows 10
NVIDIA GTX 1070 (latest driver)

**Issue description:**
When I play any game of mine in GLES3, I get frequent frame jitters. But when I run the game in GLES2, it runs perfectly fine without problems.

**Comment by girng** [comment]
jitter depends on a ton of stuff.
your monitor refresh rate, how you are updating your character's position (is it in physics_process, or _process)? are you using move_and_slide with or w/o a delta, are you updating your camera in manually or using camera's 2d node, etc.

is this 3d or 2d btw? can u post example i'll check it out

**Comment by DevMagicLord** [comment]
It is 2D or 3D game ? 
Do you have "Vsync" on ? 

Did you try to export the game and check if there is frame jitter ? 

We got a discussion about 2D game , it appears jitter or lagg appear in editor mode, but there is none when the game is exported.
[https://godotdevelopers.org/forum/discussion/19912/godot-need-to-have-its-laggy-issues-solved#latest](url)

**Comment by avril-gh** [comment]
> jitter or lagg appear in editor mode

it do, when one use remote tree / debugger / monitoring features.

**Comment by 11clock** [comment]
Important update. As of recently, the frame jitter happens even with gles2 now. But enabling the NVIDIA draw_rect flicker workaround in the project settings stabilizes it. I looked into his setting and apparently it is for a completely different issue regarding tiles randomly vanishing, but it fixes frame jitters for me as well. The two may be related somehow.

What does the draw_rect workaround change, exactly? What could it be doing to keep the physics and render loops from desyncing so badly on my end (what I assume to be causing the jitters)?

Note that the jitter fix in the physics settings does nothing for me.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.2 or a 4.0 dev build?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
