### ISSUE TITLE
Mouse cursor is resetting "Input.set_default_cursor_shape"

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#21958]
https://github.com/godotengine/godot/commit/c320d9394d82b755e2ccffb0d8fac3e9df61396b
x11

"reset is never printed"
Looks like the cursor is resetted internally somewhere.

Step:
1. Make the control `FullRect`
2. Add this script
```
extends Control

func _ready():
	pass 

func _process(delta):
	if get_rect().has_point(get_global_mouse_position()):
		Input.set_default_cursor_shape(Input.CURSOR_HSIZE)
	else:
		print("reset")
		Input.set_default_cursor_shape(Input.CURSOR_ARROW)
	
```

![peek 2018-09-11 02-49](https://user-images.githubusercontent.com/4741886/45331940-05045480-b56e-11e8-8c18-e23732943c62.gif)

**Comment by akien-mga** [comment]
CC @guilhermefelipecgs

**Comment by capnm** [comment]
The bug is that the cursor movement is setting the shape back to arrow:
```python
var i = 0.0
func _process(delta):
	i+=delta
	if int(i*10)%10 == 0:
		Input.set_default_cursor_shape(Input.CURSOR_HSIZE)

```

**Comment by guilhermefelipecgs** [comment]
I think this is a bug yes, `set_default_cursor_shape` should works with control, probably a bug introduced recently, I'll check that.
