### ISSUE TITLE
export (float, EASE) no longer adds a curve tool to the inspector.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21951]
### Version Alpha 3.1 8a8a5e6 and seen also back in my oldest version 4571089.

Was trying this one out today, and it seems to be presenting only a move cursor when hovering it.

Has something changed, anyone know?  Thanks.  X)

![godot windows opt tools 64_2018-09-10_21-49-47](https://user-images.githubusercontent.com/13004169/45317760-97dbc980-b543-11e8-95a6-881997dc0031.png)
![godot windows opt tools 64_2018-09-10_21-49-38](https://user-images.githubusercontent.com/13004169/45317764-990cf680-b543-11e8-88e8-c3659401b64b.png)

**Comment by eon-s** [comment]
Godot version?

**Comment by avencherus** [comment]
@eon-s Oh whoops.  X)  Good catch, added it.  

My oldest version 4571089 has the problem as well, though doesn't go back as far as 43dc050.

**Comment by DualMatrix** [comment]
The easing editor still works if you right click and select something other than the 0.

**Comment by avencherus** [comment]
@DualMatrix Oh I see.  Thanks for pointing it out.  XD  That is very misleading.  So if it's null or 0, it will default to that.  Maybe there should be something that could be dragged upon still to pull it out of zero?

I should probably put it up as an enhancement.
