### ISSUE TITLE
Program Icon replacement

### ISSUE THREAD

**Issue by arnzzz** [godotengine/godot#2195]
I think the program icon should be replaced.

OLD ...
![capture](https://cloud.githubusercontent.com/assets/4146123/8390092/77881bca-1c7b-11e5-9558-a5dd0efe2d0e.PNG)

NEW ...
![godot](https://cloud.githubusercontent.com/assets/4146123/8390097/a85d54d6-1c7b-11e5-92e0-401244be319d.png)

**Comment by okamstudio** [comment]
do you know of a portable way to set an icon to an exe file?


On Fri, Jun 26, 2015 at 11:22 PM, arnzzz <notifications@github.com> wrote:

> I think the program icon should be replaced.
>
> OLD ...
> [image: capture]
> <https://cloud.githubusercontent.com/assets/4146123/8390092/77881bca-1c7b-11e5-9558-a5dd0efe2d0e.PNG>
>
> NEW ...
> [image: godot]
> <https://cloud.githubusercontent.com/assets/4146123/8390097/a85d54d6-1c7b-11e5-92e0-401244be319d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2195>.
>



-- 

*OkamStudio*

**Comment by guilhermefelipecgs** [comment]
For windows I think the best way is create a *.rc file for embed the icon.

reference:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa380599%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/aa381018%28v=vs.85%29.aspx

SCons have a option for this I think:
http://www.scons.org/doc/production/HTML/scons-man.html#cv-RC

Example from aseprite project using cmake:
Lines 1 to 3 - [rc file](https://github.com/aseprite/aseprite/blob/master/src/main/resources_win32.rc)
Lines 270 to 289 - [cmake file](https://github.com/aseprite/aseprite/blob/master/src/CMakeLists.txt#L268)

I hope this help you.

**Comment by reduz** [comment]
Godot now is able to export icons properly on windows thanks to pe_bliss , and also has a nice icon on windows.
