### ISSUE TITLE
Area: signal body_entered is called too early with correct collision shape setup

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#21952]
**Godot version:**
master (https://github.com/godotengine/godot/commit/864a3143406fe9a8023995ef5ca10758bcdd6ecd)

**OS/device including version:**
Arch Linux

**Issue description:**
When I run the racing game, the game ends before the car reachs the final lap. This only happens on master.

**Minimal reproduction project:**
https://github.com/HugeGameArtGD/Solus-Stunts.git (```git clone --recursive```)

**Comment by LinuxUserGD** [comment]
maybe it has to do with https://github.com/godotengine/godot/commit/b252e66414c2dc70f5e36045e4f0144dd29147cc ?

**Comment by AndreaCatania** [comment]
Please next time try to update a sample project where the problem is immediately visible.

Anyway this should fix the problem: #22257

Thanks you for the report

**Comment by HugeGameArtGD** [comment]
I sill get some errors with https://github.com/HugeGameArtGD/Solus-Stunts/releases/download/v6.0/car-bug.zip

**Comment by AndreaCatania** [comment]
I'm unable to test this project, I can't open any level. Also I need a sample project where the problem is immediately visible. Try to find it inside a game is a waste of time.

Thanks you for your understanding.

**Comment by LinuxUserGD** [comment]
Yes, that's the bug (and didn't happen before) --> scene changes back to main screen
The code is in `car/1/ground2.gd` and has to be commented out in order to play the level:

res://car/1/ground2.gd:
``` python

extends Area
var ROUND = 1
var round2 = preload("res://assets/voice/round_2.ogg")
var finalround = preload("res://assets/voice/final_round.ogg")
var gameover = preload("res://assets/voice/game_over.ogg")
var winner = preload("res://assets/voice/winner.ogg")


func _ready():
	pass 

func game_over():
	pass
	#print("Game Over")
	#get_tree().get_root().get_node("lobby/world").audioend()
	#$"/root/lobby/world/countdown/audio".stream = gameover
	#$"/root/lobby/world/countdown/audio".play()

func _on_StaticBody2_body_entered(_body):
	game_over()


func _on_Area_body_entered(_body):
	game_over()

func _on_goal2_body_entered(_body):
	nextround()
	
func nextround():
	pass
	#if ROUND < 3:
	#	ROUND += 1
	#	$"/root/lobby/world/round".text="round " + str(ROUND) + " of 3"
	#	if ROUND == 2:
	#		$"/root/lobby/world/countdown/audio".stream = round2
	#	if ROUND == 3:
	#		$"/root/lobby/world/countdown/audio".stream = finalround
	#		
	#	$"/root/lobby/world/countdown/audio".play()
	#else:
	#	get_tree().get_root().get_node("lobby/world").audioend()
	#	$"/root/lobby/world/countdown/audio".stream = winner
	#	$"/root/lobby/world/countdown/audio".play()

func _on_goal_body_entered(_body):
	nextround()
```
res://world.gd:
``` python
func audioend():
	endaudio=true

func _on_audio_finished():
	if endaudio:
		get_tree().change_scene("res://lobby.tscn")
```

**Comment by AndreaCatania** [comment]
I know that could be tedious and useless for you, but I need a sample project with one scene where the bug is show exactly after hit F5 button.

Sorry if I'm repetitive, but I prefer be clear instead to not write at all, and leave the bug open for ever.

Here few example of well written issue report: 
#22283
#22281
#22249

Here you can see that the focus is on the engine and problem and not on the game it self.

**Comment by LinuxUserGD** [comment]
@AndreaCatania Sorry, it is fixed. The problem was that the area also detected StaticBody.
```
nextround[StaticBody:2932]
nextround[StaticBody:2950]
nextround[StaticBody:2947]
nextround[VehicleBody:2967]
nextround[VehicleBody:2967]
nextround[VehicleBody:2967]
```
I solved it by using ```if str(body).begins_with("[VehicleBody"):```.

**Comment by AndreaCatania** [comment]
Perfect, Thanks you for opening this issue :)
