### ISSUE TITLE
Change label "Window" to "Screen"

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#21968]
Godot 3.1 alpha 1.

In project settings, there is : 
- Display
  - Window

It's confusing, window means display as window and not fullscreen.
While Godot "window" means display area properties.

Perhaps some new title would be more appropriate
- Display
    - Screen

**Comment by akien-mga** [comment]
I don't think it's worth breaking compatibility for that.

Moreover, "screen" is a hardware notion, while "window" is the software one and the *correct* one. Any application renders in a "window", whether it is fullscreen or "windowed". Even more so nowadays where fullscreen mode is usually a full-size borderless window and no longer a video mode that breaks your desktop if you alt-tab of it :)

**Comment by DevMagicLord** [comment]
Most of the time in games, these options are not under windows , but "graphics".
When i saw "window" , i seen it as "window mode".
