### ISSUE TITLE
Cannot apply Normal Map to Sprite3D

### ISSUE THREAD

**Issue by grotar00** [godotengine/godot#21961]
**Godot version:**
3.0.2
3.0.6

**OS/device including version:**
Windows 10 Pro 64 bit

**Issue description:**
I have a _Sprite3D_ object with _SpatialMaterial_ applied in _GeometryInstance_ tab. Everything looks good until a normal map is enabled: sprite gets darker and stops reacting to any light sources regardless of normal texture picked (or none):
![nmap](https://user-images.githubusercontent.com/8709735/45336111-d052c600-b58a-11e8-9ee0-eb7962d88685.gif)
However, material is rendered as intended on the preview ball:
![nmap](https://user-images.githubusercontent.com/8709735/45336112-d0eb5c80-b58a-11e8-9ab1-5e0b68399836.png)
Also same material works fine with plane _MeshInstance_.

**Steps to reproduce:**
Bumped into issue on Godot v3.0.2 (noticed fps drop when sprite entered viewport first time) and reproduced on v3.0.6 by creating a new project with initial settings, adding Sprite3D, adding SpatialMaterial to it and enabling normal map.

**Minimal reproduction project:**
[Sprite3D Normal Map.zip](https://github.com/godotengine/godot/files/2369261/Sprite3D.Normal.Map.zip)

**Comment by and3rson** [comment]
I can reproduce this as well. We're currently experiencing the same issue. We have a lot of sprites and as a temporary workaround we'll have to use them as `MeshInstance`s. Which is quite painful...
