### ISSUE TITLE
Scene Tree Multiselect is not showing selection in tree

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#21960]
https://github.com/godotengine/godot/commit/c320d9394d82b755e2ccffb0d8fac3e9df61396b
x11
it worked here https://github.com/godotengine/godot/pull/21316

Control-Control3 shpuld be highlighted in the Tree 

![peek 2018-09-11 03-00](https://user-images.githubusercontent.com/4741886/45332092-de92e900-b56e-11e8-9ae9-094e5d6553ed.gif)

` editor/editor_data.cpp:959 - Parameter ' p_node ' is null.`

**Comment by capnm** [comment]
Das hier hat deine Katze vermutlich sauer gemacht:
(works again if I revert) https://github.com/godotengine/godot/pull/21831
```diff
diff --git a/editor/editor_node.cpp b/editor/editor_node.cpp
index 3eebb73cd..172e340da 100644
--- a/editor/editor_node.cpp
+++ b/editor/editor_node.cpp
@@ -1558,8 +1558,6 @@ void EditorNode::_edit_current() {
 
 				editor_plugin_screen->edit(current_obj);
 			}
-		} else {
-			editor_plugin_screen->edit(current_obj);
 		}
 
 		Vector<EditorPlugin *> sub_plugins = editor_data.get_subeditors(current_obj);


```
