### ISSUE TITLE
Missing Collision Layers in Area (3D) (1.1)

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#2196]
Is it possible to add collision Layers in Area(3D)?
![image](https://cloud.githubusercontent.com/assets/10463138/8391782/96c36108-1ccf-11e5-83f0-2fcfb959a26d.png)

**Comment by soloparatolos** [comment]
Im waiting for that too, I have a proyect on stand by.

https://github.com/okamstudio/godot/issues/2062

**Comment by okamstudio** [comment]
I've been slowly migrating all the 2D physics engine features to 3D, and I
think the only missing one is this so hope to implement it soon

On Mon, Jul 6, 2015 at 3:45 PM, soloparatolos <notifications@github.com>
wrote:

> Im waiting for that too, I have a proyect on stand by.
>
> #2062 <https://github.com/okamstudio/godot/issues/2062>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2196#issuecomment-118954120>.
>



-- 

*OkamStudio*

**Comment by eska014** [comment]
See #1759.
