### ISSUE TITLE
Simplified 3D models import

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#21969]
Godot 3.1 alpha 1

There is some things other 3D engines do better on 3D models import : 

- A thumbnail is automatically created

- the new object have the same name as the imported file

And there is no need to create a new inherited scene in other 3D engines.

I wish Godot will become as fast and simple (whatever it is ESCN, GLFT2 or other formats).

**Comment by Zylann** [comment]
But do other engines generate colliders, lights and materials based on the 3D file, which Godot can do by importing it as a scene?

**Comment by vnen** [comment]
You also don't _need_ to create inherited scenes. You can simply instance the imported scenes inside other scenes. You need to inherit only if you intend to modify the imported scene directly.

**Comment by reduz** [comment]
It is as @vnen says, most of the time you just instantiate the scenes somewhere and, at much, do local changes.

**Comment by DevMagicLord** [comment]
> You also don't need to create inherited scenes. You can simply instance the imported scenes inside other scenes. You need to inherit only if you intend to modify the imported scene directly.

Because when it's not a mobile game, you won't do all work in Blender.
Most textures i do are from external packages like Substance Painter or Zbrush , and imported into Godot. Most of the time you won't do lighting in Blender but directly in your 3D engine, i don' t see the need to import Blender lights , specially when you do level design in engine editor with plugins instead.

About import , one step import would be faster, drag and drop the model and that's it. 

Godot options would have some option checkbox  for import ? When checked they force Godot to 
- auto instance
or
- auto create new inherited scene 
and create a thumbnail automatically (3D model centered without grid display and without origin).

**Comment by DevMagicLord** [comment]
I think it's important to let the choice to user to continue importing this way,
or have some option to pre define how improt should work (au instance on import and auto thumbnail generation).

**Comment by DevMagicLord** [comment]
I guess import won't get new options and stay as it is.
