### ISSUE TITLE
Weird kerning on labels

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#21965]
**Godot version:** 
3.1 custom

**OS/device including version:**
ArchLinux

**Issue description:**
Font kerning is different in Godot. 
I am using [Lato-regular](https://fonts.google.com/specimen/Lato).
In the image you can see Godot (black background) compared to the font in the web browser (white background)
In Godot's rendering, the 'l' and 'r' are too close to the 'o'

![kerning](https://user-images.githubusercontent.com/7917475/45344075-1582f200-b5a3-11e8-985d-5eba8a1b3773.png)

**Comment by Zylann** [comment]
Would this be caused by the weight of the font? The Godot example looks more "fat" than the browser example.

**Comment by QbieShay** [comment]
@Zylann what do you mean with weight? In both cases I am using Lato-regular

**Comment by Zylann** [comment]
@QbieShay oh ok... and does it repro with the same font size?

**Comment by chaigler** [comment]
Seeing this as well on 3.1-alpha5:

![fonts broken](https://jesterdance.com/font_wat.png)

Top left shows the font (PetitLatin) at size 36 in Godot. Top right shows the same font at size 26 in paint.net. Bottom shows same font in paint.net at size 36. Definitely something strange going on.
