### ISSUE TITLE
Godot FPS demo have a lot problems with GLES2

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21964]
**Godot version:**
Godot 3.1 c320d93

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
Opening [FPS Project from documentation](https://godot.readthedocs.io/en/latest/_downloads/Godot_FPS_Finished.zip) with GLES2 cause a lot of problems like:
- [x] Some objects become more and more transparent as the distance increases (Vid 1, Shields at wall)
- [x] The edge between the wall and the ceiling looks like a staircase instead of a straight line (Vid 1)
- [x] A lot of problems with disappearing and appearing shadows (Vid 2)
- [x] Grid shows and disappearing at different locations (Vid 2)
- [x] Some objects like bricks, flags, turrets teleport to strange locations (Vid 2,3) 
- [x] Some textures are violet (Vid 2)
- [x] Strange white lines/areas cover textures when camera is far away (Vid 3)
- [x] Sometimes the engine turns itself off
- [ ] On some objects is visible some texture noise (Vid 4)

**Vid 1** - https://streamable.com/dcj38
**Vid 2** - https://streamable.com/ygqpy
**Vid 3** - https://streamable.com/wrl6b
**Vid 4** - https://streamable.com/01o1r

**Comment by NewNodeGames** [comment]
All these glitches are caused for directional lights.

**Comment by qarmin** [comment]
Not all, but most
Here is bug with wrong transparency without lights https://streamable.com/8dypd

**Comment by qarmin** [comment]
I use now commit 399910d and probably with https://github.com/godotengine/godot/commit/65fd37c14947bd596510fb764de649927e1b18f4 Ruin Space Level almost all disappear in GLES 2
![asfasf](https://user-images.githubusercontent.com/41945903/45948047-d15a0d80-bff6-11e8-9235-bc5f9e871005.png)

Only this error is spamming:
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1281        Severity: High  Message: Error has been generated. GL error GL_INVALID_VALUE in (null): (ID: 173538523) Generic error
   At: drivers/gles2/rasterizer_gles2.cpp:111

**Comment by qarmin** [comment]
Still some shadows are broken and in space exists strange objects.
https://streamable.com/rbgzf

**Comment by reduz** [comment]
I was testing this yesterday (due to another bug) and just checked again. All looks fine, so will be closing it.
If you find anything else, let me know.
