### ISSUE TITLE
RayCast node doesn't display ray if length is < 0.5

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2197]
RayCast node doesn't display ray if length is < 0.5
If size is less, the ray is not displayed in editor (which makes it hard to setup).

(Cast to field)
Enter 0.0 -0.2 0.0 - ray disappears
Enter 0.0 -0.5 0.0 - ray appears

**Comment by slapin** [comment]
Seems to be related to video drivers.
With intel driver of xorg-edgers this bug was not reproduced by MrGreenTea
I reprduce it with nvidia.
With latest godot version the value should be bigger than 0.5, it is probably due to float rounding errors.
This issue is not related to Linux or 64 bit.

**Comment by reduz** [comment]
well, not a bug then :P

**Comment by slapin** [comment]
Last time I checked thes bug was still reproducible, will check soon.

**Comment by slapin** [comment]
I hope nobody considers that there are configurations with which a bug is
not reproducible, the the bug is not really a bug,
otherwise there is no reason to waste time on Godot, batter do something
which is more fun and profit.

**Comment by reduz** [comment]
i think it's kind of the opposite, if the bug only happens with a certain
driver then it's likely a driver bug

**Comment by slapin** [comment]
Juan, I think you're wrong here - nvidia driver is mainstream ATM, and a
bug on nvidia driver is a bad thing.

**Comment by slapin** [comment]
And there is no proof that it is a bug in driver, probably the solution
used is working on other drivers just
by accident.
