### ISSUE TITLE
Dialogs scaled incorrectly, no longer match size of their contents

### ISSUE THREAD

**Issue by k7771911** [godotengine/godot#21975]
**Godot version:** 3.1.alpha.official

**OS/device including version:** MacOS High Sierra, iMac Retina 5K

**Issue description:**
Some of the popup dialog boxes (Find in files, Go to Line) and results are not showing properly on Retina displays, see screenshots below. Other dialogs like Search Classes and Search Help show up fine.

![3443e9fc-9261-4de0-8cf6-2cf231105358](https://user-images.githubusercontent.com/38134085/45367349-a9a28880-b5a6-11e8-8333-ac65c857c16b.png)

![3c6a07fc-c4f3-4b2b-82c4-09d470cf3637](https://user-images.githubusercontent.com/38134085/45367662-6399f480-b5a7-11e8-9f61-4ee99c3ff25a.png)

![395a3686-d1b7-49ad-bd55-f891015dd3c9](https://user-images.githubusercontent.com/38134085/45367791-a65bcc80-b5a7-11e8-86a1-0f8c3153c670.png)

**Comment by Zireael07** [comment]
For non-retina part, a cause was found in https://github.com/godotengine/godot/issues/21933#issuecomment-422490629
