### ISSUE TITLE
Axis lock for Kinematic 

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#21970]
Godot 3.1 alpha 1

Could Kinematic physics get an Axis Lock feature like RigidBody physics ? 

On collision with other objects it would be constrained when there is Axis Lock values on, instead of moving anywhere physics do.

**Comment by LikeLakers2** [comment]
Wait, why was this closed? It seems like a good idea to me, albeit I'm unsure what the use case would be.
