### ISSUE TITLE
Compiling Android with too many arguments

### ISSUE THREAD

**Issue by KillerJaguar** [godotengine/godot#2198]
I've been looking into compiling Android on Windows, and been playing with different options. The latest I did was "scons platform=android x86=yes" which worked up until linking. I couldn't even see the start of the command but it ends with "The parameter is incorrect." I've looked into it and found that Windows has a maximum character limit for command line arguments. This may be a start for finding a fix for compiling Android on Windows.

**Comment by blam9** [comment]
This was fixed in #2302 in detect.py where it comments on workaround for long command lines.

I actually have the same problem even after the fix, and for me it was because there was a space in my android sdk path. I removed the space and was able to build the .so

**Comment by akien-mga** [comment]
Thanks for the feedback, closing then.
