### ISSUE TITLE
Minor C# warnings about hidden inherited members, "use the new keyword if hiding was intended".

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#21989]
**Godot version:** Master / 0d04fb76e1d4543d04d6e41244c06f35bfecb07c (after 3.1 Alpha)

**OS/device including version:** Xubuntu 18.04 LTS 64-bit

**Issue description:** There are some minor C# warnings about overriding methods that lack a "new" keyword. These warnings only show up if there is also an error - otherwise the warnings are hidden - but still, these problems should be fixed. CC @neikeq 

![f](https://user-images.githubusercontent.com/1646875/45394539-282b1480-b5ff-11e8-9117-23fadf0d678b.png)

**Steps to reproduce:** Break some C# code on purpose to get it to show errors and warnings, then notice that there's all of these warnings in addition to the error you caused.

**Comment by neikeq** [comment]
I have a TODO about this: https://github.com/godotengine/godot/blob/0d04fb76e1d4543d04d6e41244c06f35bfecb07c/modules/mono/editor/bindings_generator.cpp#L696-L697

**Comment by KellyThomas** [comment]
See also #15763

**Comment by neikeq** [comment]
Oh, indeed. This is a duplicate.
