### ISSUE TITLE
Missing .pck results in silent failure on Windows export

### ISSUE THREAD

**Issue by voithos** [godotengine/godot#21994]
**Godot version:**
3.0.6

**OS/device including version:**
Window 10

**Issue description:**
I had exported a Godot game to Windows (from a Linux workstation), but in transferring the data I missed the .pck file. Attempting to start the .exe resulted in a brief "busy" indicator, and then... nothing.

At first, I thought Windows Defender was interfering, so I spent some time trying to figure that out, but I eventually realized that the .pck file was just missing. A simple error message would have saved me a bit of time.

**Steps to reproduce:** / **Minimal reproduction project:**
Should be (in theory) trivially reproducible with any project.

**Comment by Zireael07** [comment]
We recently had a very similar issue reported, where someone attempted to run a .exe without the .pck.

**Comment by Calinou** [comment]
It would make sense to call [`OS.alert()`](http://docs.godotengine.org/en/latest/classes/class_os.html#class-os-alert) if the PCK file cannot be found when running an export template binary, as a command prompt won't show up when running a release Windows export template (it will display only in debug mode).

**Comment by voithos** [comment]
Agreed with @Calinou. And I guess just to say it out loud - I only tried this on Windows, but we'd ideally want a missing .pck file to give some kind of error indication on *all* applicable platforms (I assume `OS.alert()` would do the right thing?).

**Comment by Calinou** [comment]
> I only tried this on Windows, but we'd ideally want a missing .pck file to give some kind of error indication on *all* applicable platforms (I assume `OS.alert()` would do the right thing?).

That's the case, `OS.alert()` works on all platforms — it will look different depending on the platform, but it should get the message across.
