### ISSUE TITLE
GDScript parser has issues with static typing outer class in inner class.

### ISSUE THREAD

**Issue by MidZik** [godotengine/godot#21996]
**Godot version:** 3.1 alpha 1

**OS/device including version:** Windows 10

**Issue description:**

If you give a script a `class_name`, then try to use that class inside one of the inner classes as a static type, instead it is statically typed as the _inner class_.

Example script:

```
extends KinematicBody2D
class_name Pawn

var controller : PawnController = null

func _get_movement_vector():
	if controller:
		return controller.calculate_movement_info(self)
	else:
		return Vector2(0,0)

# Pawn controllers should extend and implement these functions.
class PawnController extends Node:
	func calculate_movement_info(pawn : Pawn):
		return Vector2(0,0)
```

Godot gives an error on the line `controller.calculate_movement_info(self)`, saying that the function's assigned type (`Pawn`, the type of `self`), does not match the function argument's type (`PawnController`).

For some reason, `pawn` is assigned the static type of `PawnController` instead of `Pawn`.

This error prevents the game from running (parser error).

**Comment by steveday4u** [comment]
Sorry, I still get the same error. 

Sample:

`
class_name MyClass
extends Node

func createA(s: String) -> InnerA:
	return InnerA.new(self, "wot")

class InnerBase:
	var _my_ref: MyClass
	func _init(my: MyClass) -> void:
		_my_ref = my

class InnerA extends InnerBase:
	var data: String
	func _init(my: MyClass, s: String).(my):
		data = s
`
Gets "error(5,1): At init() call argument 1. Assigned type (MyClass) doesn't matct the function argument's type (InnerA)"
built from git including your fix.

**Comment by vnen** [comment]
I'll give it a check, I think I know what is the problem.

**Comment by steveday4u** [comment]
Thanks!

**Comment by steveday4u** [comment]
When I leave out the type in the init function of `InnerA`
`func _init(my: MyClass, s: String).(my):` i get a

> Invalid type in function _init: Cannot convert argument 1 from Object to Object.

When i leave out all the type information and check for `my.is_class("MyClass")` in the init function I get false. But I am still able to call functions that i define in `MyClass`...

**Comment by akien-mga** [comment]
Still reproducible in the current master branch.

**Comment by MidZik** [comment]
Can confirm that the original issue still exists in 3.1 beta 8.

**Comment by steveday4u** [comment]
Looks good. Thanks!
