### ISSUE TITLE
Better collada doesn't properly export when there's several armatures on the same mesh

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#22001]
I have a female character, the body is rigged with the blender default human rig, and the hair of her is rigged with another armature parented to the head bone.

[azuka new.zip](https://github.com/godotengine/godot/files/2375679/azuka.new.zip)

It works great on blender, but when I export to godot the hair doesn't become parented properly.

I already tried to test this on unity as well and the same problem appears, it seems is not just a godot issue.

**Comment by vnen** [comment]
If the problem is the exporter it should be reported on https://github.com/godotengine/collada-exporter
