### ISSUE TITLE
Elastic Tabstops for the Editor

### ISSUE THREAD

**Issue by Zephilinox** [godotengine/godot#22011]
![Gif](http://nickgravgaard.com/elastic-tabstops/images/columnblocks_coloured.gif)

http://nickgravgaard.com/elastic-tabstops/

Elastic tabstops are a way to format code by linking tabs to the same indentation level as those above and below them, so they're automatically aligned.

You can try it here https://github.com/dail8859/ElasticTabstops/releases

**Comment by fire** [comment]
Is there a c++ compatible library that implements this? The linked library is GPL.

**Comment by AlexHolly** [comment]
You mean for the GDScript Editor?
What is the benefit? I can only see that you don't have to move comment manually.

**Comment by Calinou** [comment]
I'll close this due to appearent lack of support. If you still need Godot to support elastic tabstops, please [open a proposal](https://github.com/godotengine/godot-proposals) in the Godot Proposals repository.
