### ISSUE TITLE
Polygon2D with skeleton makes everything else invisible if nothing is drawn after it (?)

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#22010]
**Godot version:**
3.1 alpha1

**OS/device including version:**
Windows 10 Nvidia GTX 1060

**Issue description:**
Sooo, I can't really explain what happens here. I noticed that sometimes in my project there's a sprite disappearing just like that. I mean, it acted so weird, as it was visible and then wasn't and then was again, depending on camera position. I later noticed that when I shoot a fireball, the sprite appears as long as fireball is visible.

After digging into the issue and removing more and more parts of the project, it turned out to be somehow caused by a scarf. I mean, it's a Polygon2D node with texture and skeleton and kind of custom physics. Now, this is interesting part. When the scarf is on screen, everything beside scarf becomes invisible. If it's out of screen, everything is normal. What's more, if there's anything drawn AFTER the scarf (e.g. a Sprite node that is below it in scene tree), it will be visible and everything else will be fixed too.

I reduced the project to single scene with 3 sprites and the scarf that causes the issue. I didn't manage to go deeper, as trying to meddle with skeleton caused crashes and creating a clean new polygon doesn't reproduce the issue.

Here's a really low-quality gif of what happens:
![visibilityerror](https://user-images.githubusercontent.com/2223172/45458075-47ef3500-b6f2-11e8-9ef9-5e7d31b2da7b.gif)
The red dot in the middle is the scarf. Sprite to the left is lower in scene tree and sprite to the right is higher. When the left sprite is visible, everything else is visible too.

**Minimal reproduction project:**
[VisibilityError.zip](https://github.com/godotengine/godot/files/2377164/VisibilityError.zip)
^ and this is the "minimal" project where it happens. Just move the camera to have scarf on screen and off screen and see what happens

**Comment by eon-s** [comment]
I do not know what this means or if is related to the bug but I see this error on the output
` core/image.cpp:1731 - Loaded resource as image file, this will not work on export: 'res://Maps/World4/Landscape/RuinedCorridor.png'. Instead, import the image file as an Image resource and load it normally as a resource.`

**Comment by KoBeWi** [comment]
>I see this error on the output

I see that error ever since upgrading to 3.1 and no idea what causes it. Pretty sure it's unrelated.

**Comment by avencherus** [comment]
Confirmed it in: 268ae71fae08587e6df5b3270b7fc4833f30e34e

For me it seems to cause the vanishing when the scarf is exactly on the viewport edge.  Right before that its fine, and right after that it is also fine.  Maybe perhaps aligned to the bones?

**Comment by clayjohn** [comment]
Is this bug still present in 3.1?

**Comment by KoBeWi** [comment]
Looks like it's not reproducible anymore in the stable version.
