### ISSUE TITLE
Implement "Ordered Initializer" for Scene Instancing.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#22028]
**Godot version: 3.2**

The _init function which can take arguments can only be used on script, not scene instantiation whereas _ready can't take parameter`s, which wouldn't be clear.

This presents bit of a problem when using setget that utilize tree nodes.

```GDScript
var title setget set_title
onready var label = $Label

func set_title(string):
	label.text = string
```

If we use .new and pass in the title string, the setter will trigger but the label has yet to been readied.

If we use .ready, we have to make additional calls. 

```GDScript
var example = scene.instance()
example.initialize("Godot")
```

My suggestion is to implement a special ordered constructor, which first instances a scene, sets its data, and then returns the complete scene. This would only be called explicitly by the user, unlike ready, which should hopefully avoid more issues.

This is how I'm implementing it currently in my project:

```GDScript
var title setget set_title
var label = $Label

set_title(string):
    label.text = string

class Initializer
    static func initialize(title):
        var scene = scene.instance()
        scene.title = title
        return scene
```

Instantiation from elsewhere:

```GDScript
self.add_child(scene.Initialize.initialize("Godot"))
```

I've seen a few people run into this issue so I think it would serve well as a built-in method.

**Comment by AlexAndDraw** [comment]
> If we use .new and pass in the title string, the setter will trigger but the label has yet to been readied.

I've just realized using setget will run into an issue either way. I still believe there is merit in a single place for ordered scene instancing though.

**Comment by KoBeWi** [comment]
From a glance, looks related too https://github.com/godotengine/godot-proposals/issues/325
Closing, because we are removing proposals from this repository. Also OP is a ghost 👻👻
