### ISSUE TITLE
Red and blue line from grid in 3D viewport blinking 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22022]
**Godot version:**
3.1 cc71012

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
When you open a new project and move the view with the mouse, the red and blue lines flash in the 3D view

When I opened the FPS demo from documents, this problem does not appear

In GLES2 lines are barely visible

**Steps to reproduce:**
1. Open new project
2. In 3d viewport move view by mouse

GLES3 - https://streamable.com/zgpvf
GLES2 - https://streamable.com/2h8d1

**Comment by akien-mga** [comment]
CC @Calinou - neverending story...

I'm starting to wonder if we should not just revert all the changes made for this and keep the i = 0 lines hidden at all times.

**Comment by akien-mga** [comment]
This might be fixed by #22282, can you confirm?

**Comment by qarmin** [comment]
Now works perfect
