### ISSUE TITLE
Clicking inside the pop-up window next to the edge results closing it

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22023]
**Godot version:**
3.1 cc71012

**OS/device including version:**
Windows 10

**Issue description:**
When I open pop-up and click a little above or below edge(but still inside this popup), this pop-up close itself. 
I think that this pop-up shouldn't close because I don't click outside it and clicking at free area between options doesn't close it.

Red Line - space we can click at free space and popup doesn't close (of course except choose option like "Show Grid")
Yellow Line - space in which we can click and then pop-up close itself

![asfa](https://user-images.githubusercontent.com/41945903/45477533-fff7fe80-b741-11e8-92e7-46080d1b7713.png)

![jfile](https://user-images.githubusercontent.com/41945903/70703348-3c613400-1cd0-11ea-9e7f-13b393bdeb7f.gif)

**Comment by KoBeWi** [comment]
Fixed in 4.0
