### ISSUE TITLE
Give a break to the game loop in PeekMessage while

### ISSUE THREAD

**Issue by testmana2** [godotengine/godot#22024]
**Godot version:**

master at 3.1

**OS/device including version:**

windows

**Issue description:**

OS_Windows::process_events() {
...
	while (PeekMessageW(&msg, NULL, 0, 0, PM_REMOVE)) {
		TranslateMessage(&msg);
		DispatchMessageW(&msg);
       }
}
When engine received lots of input event such as drag event the while statement take long time more than frame step.  the renderer will not redraw immediately.

**Steps to reproduce:**
Give a simple Line2D node. on touch down event and add point to line2d, if you move your tablet pen drawing something without a break, the line will be show after more than 1 second.

So, I think give a break on PeekMessage like below or implement multi-thread rendering.
	while (PeekMessageW(&msg, NULL, 0, 0, PM_REMOVE)) {
		TranslateMessage(&msg);
		DispatchMessageW(&msg);
               if( now - lastTime > frameStep * 0.3 ) break;
       }

**Comment by Calinou** [comment]
InputEvents are now accumulated on a per-rendered-frame basis by default, so this issue is probably solved. Please comment if you can still reproduce it in Godot 3.2.1 or the `master` branch.
