### ISSUE TITLE
Irritating bug  Condition ' !metadata.has(p_name) ' is true. returned: Variant()

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22021]
**Godot version:**
3.1 cc71012

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
It is annoying when almost all output is spamed by this bug text:
`core/object.cpp:1084 - Condition ' !metadata.has(p_name) ' is true. returned: Variant()`

with only adding Node2D to scene and help menu I have also this warnings
WARNING: grab_focus: This control can't grab focus. Use set_focus_mode() to allow a control to get focus.
     At: scene/gui/control.cpp:2067
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers/png/image_loader_png.cpp:67
WARNING: _get: Property not found: _global_script_class_icons
     At: core/project_settings.cpp:194

**Steps to reproduce:**
1. Create new project
2. Add Node2D
3. Change viewport to 2D
4. Move this viewport

https://streamable.com/ecz1e

**Comment by akien-mga** [comment]
I've noticed this too, it's relatively recent (a week at most I'd say).

**Comment by DualMatrix** [comment]
I tried but I couldn't get that error following those instructions on master e20a28a.

**Comment by qarmin** [comment]
Confirm that in master c2abf1a it isn't reproducible.

**Comment by qarmin** [comment]
Nope, this is still reproducible:
1. Open attached project
2. Open Sticky Grenade Scene
3. Click at the some of child of grenade
4. Click up or down arrow and click Enter

https://streamable.com/8t2xn

[FPS FIRST).zip](https://github.com/godotengine/godot/files/2460076/FPS.FIRST.kopia.zip)

**Comment by qarmin** [comment]
Also clicking in scene dock at left side of nodes which are far from left side of this dock cause this error:
https://streamable.com/gyc33

**Comment by sgamerw** [comment]
I am a new comer for this engine, got this error every time.

Reproduce:
1.Download 3.0.6 from official web site
2.Add margin container to a new scene
3.Add VBoxContainer as the child of margin container
4.Edit property of VBoxContainer,  anchor, position or rect, will produce this error and save change doesn't make sense, the VBoxContainer always has a position x = 8, it's wired

[pyramid.zip](https://github.com/godotengine/godot/files/2570767/pyramid.zip)

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch or latest beta build?

**Comment by qarmin** [comment]
Yes, it is still reproducible with this steps

**Comment by TheMadScientist1234** [comment]
I'm having the same problem with my project in Godot 3.1. It makes it impossible to debug my project.

**Comment by mmatttheww** [comment]
hi! i can confirm i'm having this issue as of 6/20/2019

**Comment by akien-mga** [comment]
Fixed by #31295.

**Comment by qarmin** [comment]
Still I can reproduce this in Godot 3.2 beta 5 with this steps https://streamable.com/gyc33

**Comment by akien-mga** [comment]
That's pretty extreme :) The hundreds of issues that you're getting with `CSGMesh` before that are likely part of the issue.

**Comment by nesja** [comment]
A similar error that is displayed after the freezing of the Godot interface for 1-3 seconds. Occurs randomly and repeats approximately every 10 minutes. It only happens when working with Godot. OS: Kubuntu 19.10, the same in Godot 3.2 and 3.2.2 beta1 
Error: ` core/object.cpp:1047 - Condition "!metadata.has(p_name)" is true. Returned: Variant()`
