### ISSUE TITLE
Confusing behaviour of Texture.FLAG_CONVERT_TO_LINEAR / color space conversions

### ISSUE THREAD

**Issue by Windfisch** [godotengine/godot#22031]
**Godot version:** Current master (bcc50de2d168c3184dc5c07bbfbea68236c32864)

**OS/device including version:** Both Linux/X11 and Windows 10 64bit. NVidia GPU.

**Issue description and Steps to reproduce**
When creating an ImageTexture from an Image using `.create_from_image()`, the `Texture.FLAG_CONVERT_TO_LINEAR` flag seems to have no effect at all. Instead, color space conversion is decided solely on the image format chosen, where e.g. RGB8/RGBA8 perform the gamma conversion, while RGBF/RGBAF don't. This is not documented, the docs should improve there.

In the attached project, try all four combinations of `img.create(1,1,false,Image.FORMAT_RGB8/RGBF)` and `tex.create_from_image(img, Texture.FLAG_CONVERT_TO_LINEAR / 0)`.
The demo program creates an Image with a color of (0.5,0.5,0.5), and in the shader checks what has been read. If a 0.5 has been read, it draws a green square. If a 0.217 == pow(0.5, 2.2) has been read, it draws red.

Expected behaviour:
 - FORMAT_RGB8 and RGBF should behave the same (both read 0.5/green), OR the docs should reflect this.
 - setting or not setting `Texture.FLAG_CONVERT_TO_LINEAR` should have a noticeable effect (or the docs should be more clear about what it does)

Actual behaviour:
 - the docs are unclear about this
 - `Texture.FLAG_CONVERT_TO_LINEAR` has no visible effect.

**Minimal reproduction project:**

[docbug.zip](https://github.com/godotengine/godot/files/2379693/docbug.zip)

**Comment by Windfisch** [comment]
The first bullet points are fixed with the PR mentioned above, but the `Texture.FLAG_CONVERT_TO_LINEAR` point persists. Frankly, I have no idea what this flag is supposed to do ;), can someone help me out please?

**Comment by fjordyo0707** [comment]
I face this similar problem when I try to fix #31759. The document is ambiguous, and I cannot find the source code which handles this part. If you have figured it out, any information about FLAG_CONVERT_TO_LINEAR will be appreciated.

**Comment by clayjohn** [comment]
I understand the frustration with the current handling of linear/sRGB, it will be overhauled in 4.0 so it doesn't make sense to spend the time improving it before that unfortunately :/

**Comment by Windfisch** [comment]
Hi @clayjohn, I understand your point. If you (or anyone) happen to know the purpose of FLAG_CONVERT_TO_LINEAR, though, I think it would be a good idea to at least update the 3.1 documentation until 4.0 is out. Do you, by chance :)?

**Comment by clayjohn** [comment]
Here is the code that gets run when you set it. 

https://github.com/godotengine/godot/blob/3e782c78ae46dd3452e7a61a52c65a69f09b8413/drivers/gles3/rasterizer_storage_gles3.cpp#L1391-L1401

As you can see it requires a specific extension. Maybe your machine just doesnt support this feature?

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@clayjohn  Just want to add to what you said that this is also an issue when you have GLES2 fallback because the two drivers handle color rendering differently.  GLES2 appears to do a srgb to linear for each Vertex color where as GLES3 does not.

**Comment by akien-mga** [comment]
This needs to be re-assessed in the context of Godot 4.0, where this has changed significantly.

For 3.x, more documentation can likely be added to clarify this.

**Comment by akien-mga** [comment]
This flag doesn't seem present in 4.0 anymore.
