### ISSUE TITLE
Chrome does not allow applications to play audio

### ISSUE THREAD

**Issue by GustavoMarciano** [godotengine/godot#22036]
**Godot version:**
All

**OS/device including version:**
Mobile Browsers

**Issue description:**
Chrome does not allow applications to play HTML5 audio without an explicit "action" by the user but even with user actions no audio is played:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Minimal reproduction project:**
https://dexpace.itch.io/ultra-gravity-switch

**Comment by chandujr** [comment]
I don't think this is a Godot issue. The link you provided clearly says it's a Chrome policy. I don't think any browser today plays audio without user interaction. Developers usually overcome this by placing a button, something like "ENTER", to actually start the game. In that button click listener, just play some click sound or start background music. Any other audio will play from there on.

**Comment by GustavoMarciano** [comment]
> I don't think this is a Godot issue. The link you provided clearly says it's a Chrome policy. I don't think any browser today plays audio without user interaction. Developers usually overcome this by placing a button, something like "ENTER", to actually start the game. In that button click listener, just play some click sound or start background music. Any other audio will play from there on.

Well in Defold engine this is already done in the export.

**Comment by GustavoMarciano** [comment]
> Well, adding a hard-to-customize "Run" button to exported games won't be much better IMO.
> 
> On the other hand, if HTML5 audio does not play even after interacting with the game, that might be a bug.

Then this is a bug and I have no idea how it can be solved.
