### ISSUE TITLE
Websocket client not working in OSX

### ISSUE THREAD

**Issue by thanksbuddy1980** [godotengine/godot#22039]
**Issue description:**

I was trying with new websocket port in 3.1 (with downloadable alpha build and one built from master branch #4b6846a59 revision).
Websocket client wasn't giving callbacks for "connection_established" or any other notifications, when launched from godot editor. It was stuck there. 
Same client worked in linux (ubuntu-1804) as well when I exported in HTML5 on OSX.

Also, I tested the client against Java websocket server as well godot websocket server. Result is same, worked on linux but not on osx.

Reverse setup worked pretty well (server in godot and client in java).

Note: Websocket client/server are using poll function in _process.

**Godot version:**
3.1 (Alpha download)
#4b6846a59 master branch revision.

**OS/device including version:**
OSX 
MacOS HighSierra (10.13.6)

**Steps to reproduce:**
1. Either download godot alpha version or build it from master.
2. Launch Websocket server (either in godot or external).
3. Launch the websocket client (Ex: websocket_chat_demo from https://github.com/LudiDorici/godot-websocket.git) from godot editor.
3. Client doesn't trigger any notifications like connection_established or any other.

**Minimal reproduction project:**
websocket_chat_demo from https://github.com/LudiDorici/godot-websocket.git

**Comment by thanksbuddy1980** [comment]
@Faless for visibility.

**Comment by Faless** [comment]
@thanksbuddy1980 , I'm sorry, I don't have a Mac. Can you provide some logs?
Do you get any additional log in the Java WebSocket Server? (i.e. does it even try to connect)?

**Comment by nchiring** [comment]
@Faless No connection opened/established log observed on the server end.  It seems Godot client on Mac fails in trying to connect itself.

**Comment by Faless** [comment]
@nchiring what about the Godot log?
Can you send me that at least?
Websocket is in verbose logging mode when debug is enabled.

**Comment by thanksbuddy1980** [comment]
Hi @Faless, 

With your tip of debugging, I tried reproducing the issue. Below are the logs, which shows godot didn't recognise 'localhost', whereas it recognised 127.0.0.1 and '0.0.0.0'. I checked localhost setting in /etc/hosts, which is proper. Don't understand why its not picking it. 

cat /etc/hosts
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost

Anyway, we are unblocked with numeric addresses, didn't knew about how to debug godot and websocket! sorry for false alarm. Thanks for prompt reply!

One more, tried to test out 'wss://echo.websocket.org'. Which is not working, but worked from java. Any pointer in this direction? Attached logs for the same.

**Logs with localhost**
_Connecting to host: ws://localhost:9000/test/
[2018/09/14 20:28:21:3151] NOTICE: Creating Vhost 'default' (serving disabled), 4 protocols, IPv6 off
[2018/09/14 20:28:21:3151] NOTICE: created client ssl context for default
WARNING: _handle_cb: No CA cert specified in project settings, SSL will not work
   At: modules/websocket/lws_client.cpp:125.
**[2018/09/14 20:28:21:3152] ERR: Couldn't identify address**
Connecting to host: ws://127.0.0.1:9000/test/
[2018/09/14 20:28:37:7194] NOTICE: Creating Vhost 'default' (serving disabled), 4 protocols, IPv6 off
[2018/09/14 20:28:37:7194] NOTICE: created client ssl context for default
WARNING: _handle_cb: No CA cert specified in project settings, SSL will not work
   At: modules/websocket/lws_client.cpp:125._

**Logs with wss**
_:godot priya$ Connecting to host: wss://echo.websocket.org
[2018/09/14 20:31:09:0958] NOTICE: Creating Vhost 'default' (serving disabled), 4 protocols, IPv6 off
[2018/09/14 20:31:09:0958] NOTICE: created client ssl context for default
WARNING: _handle_cb: No CA cert specified in project settings, SSL will not work
   At: modules/websocket/lws_client.cpp:125.
thirdparty/mbedtls/library/ssl_tls.c:4837 x509_verify_cert() returned -9984 (-0x2700)
Client just disconnected_

**Comment by Faless** [comment]
@thanksbuddy1980 check the WARNING: `No CA cert specified in project settings, SSL will not work`, and then `thirdparty/mbedtls/library/ssl_tls.c:4837 x509_verify_cert() returned -9984 (-0x2700)`.
You need to specify the SSL CA certificates for now. See #17328 and #22066 .

> With your tip of debugging, I tried reproducing the issue. Below are the logs, which shows godot didn't recognise 'localhost', whereas it recognised 127.0.0.1 and '0.0.0.0'.

Where you binding to `0.0.0.0` when trying `localhost`? If yes, try binding to `*` instead.
`0.0.0.0` is IPv4 only, whereas `*` is dual stack, and your `localhost` likely resolves to an IPv6 `::1`. Can you double check?

**Comment by thanksbuddy1980** [comment]
Spot on! removed ::1 from /etc/hosts and its connecting. localhost was resolving to ::1. Thanks for help.

Sorry for ignorance, which certificate we are saying here. As this is just a client, do I need to give certificate from website which I am connecting to. I gave a lame shot of exporting certificate from "websocket.org" and pointing it in 'Project Settings -> SSL -> Certificates'. But didn't work, gave the same error.

**Comment by thanksbuddy1980** [comment]
Figured out... how to configure ssl. 
Thanks a lot for help.
