### ISSUE TITLE
Getting negative delta values for _process on Android

### ISSUE THREAD

**Issue by samuelpedrajas** [godotengine/godot#22041]
**Godot version:**
Godot 3.1 Alpha (commit bcba5a99cdb2debcd9a595a4e9e905809f65da10)

**OS/device including version:**
Xiaomi MI5 - Miui 9.6 (Android 8)

**Issue description:**
Toggling Android's "plane mode" on and off several times while some object is processing seems to cause Godot to give a delta value of -139812 for _process in some devices. Here's an illustration using the attached minimal project:

![deltatest](https://user-images.githubusercontent.com/8157352/45502625-c4caef00-b784-11e8-9d7e-2900ef5f4f6b.gif)

Sometimes I only need toggling 1 or 2 times and sometimes I need many more. In some other Android devices I just get negative values close to 0, but they do not get stuck in that "negatively large" number.

Probably there're other ways to reproduce this but I haven't been able to find them. I've tried with other Android toggles or adding thousands of processing objects to slow down the frame rate but only the "plane mode" thing seems to trigger it for me.

**Steps to reproduce:**
1. Run the attached project on Android.
2. Toggle Android's "plane mode" mode on and off several times (rapidly or slowly, it doesn't matter).
3. Depending on the device (sometimes) you'll get:
   - Negative numbers close to 0 for delta parameter (in _process) just for a few frames, then it continues to work correctly (positive numbers again).
   - A delta value of -139812 all the time, so the game gets glitched.

**Minimal reproduction project:**
[DeltaTest.zip](https://github.com/godotengine/godot/files/2380257/DeltaTest.zip)

**Comment by nathanwfranke** [comment]
Related to https://github.com/godotengine/godot/issues/26887
