### ISSUE TITLE
Its not possible to quickly remove script from node

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#22043]
**Godot version:**
06c8b5a

**OS/device including version:**
Any

**Issue description:**
In 3.0.6 its can be possible through this button

![image](https://user-images.githubusercontent.com/3036176/45507197-15991280-b79a-11e8-96fc-b0aaec2fd44e.png)

but its not possible now

![image](https://user-images.githubusercontent.com/3036176/45507251-3497a480-b79a-11e8-9aa2-a561c946b254.png)

instead this button open attach new script dialog which really does not much sense if you just want to remove a script from node

**Comment by vnen** [comment]
See #20590
