### ISSUE TITLE
Debugger doesn't connect to game, and doesn't work.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#22040]
**Godot version:**
3.1 9c0cc0d

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Nothing in the debugger works right, like it isn't connected to the game. It was all working in 3.1 Alpha 1. For example, `print("Hello World")` will not print in the Output panel, only in the console window. Breakpoints don't trigger and stop the game. If the code has an error, that error doesn't pop up when you run the game. If there are warnings, they are not shown. Monitors show nothing. Profiler does nothing.

**Comment by Faless** [comment]
Already fixed via #22030
