### ISSUE TITLE
Node get_child(String)

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#22052]
Godot 3.1 alpha 1

When a script uses PackedScene to keep script and player model independent , any time we can change the player model sub scene, while the script will continue to work.
 
`export(PackedScene) var playerModel`

We need a way in script to quickly access each child of playerMode  sub scene in the example above.

There is  Node get_child(int) , but changing the sub scene node order or after a re import , it won't work.
We need a stable way that uses node names :  get_child(String).

**Comment by vnen** [comment]
`get_child()` is a direct reference to the node, so there's no search needed. It is used a lot in the engine code, especially when iterating the children. Now `get_node()` can get _any node_ in the tree, not only the children, so the naming is accurate.

**Comment by DevMagicLord** [comment]
I was focused on child, but get_node() will work.

**Comment by akien-mga** [comment]
There's no point to add `get_child(name)` as it would be the same as `get_node(name)`.
`get_node` is actually *meant* to get children, you can use it to access parents or node at an arbitrary path, but that's bad practice - your should keep your scenes self-contained as far as possible.

**Comment by akien-mga** [comment]
I've added a mention to `get_node` in the `get_child` documentation, just in case.
