### ISSUE TITLE
Popping up a WindowDialog causes an error message to appear in the editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#22060]
**Godot version:**
 909c06e

**Issue description:**
The editor has the behaviour of making itself go darker when a dialog pops up (e. g. the quit confirmation), it seems that triggering a popup of a WindowDialog node also has the same effect.

**Steps to reproduce:**
Connect the `ready` signal to call `popup` in the WindowDialog itself. Restart the editor.

**Comment by Xrayez** [comment]
Not sure usability-wise whether editor dimming is appropriate (might be the case that you could drag-n-drop items between dialog and other controls more easily, if that even possible), but I've encountered another bug when after closing editor's window dialog it would *remain* dimmed, but I fail to come up with steps to reproduce it.

**Comment by Calinou** [comment]
Can anyone still reproduce this on the latest `master` branch? #30379 may have fixed this.

**Comment by YeldhamDev** [comment]
It does not anymore, but now an error appears:
`scene/gui/control.cpp:2183 - Condition ' !data.SI ' is true.`

**Comment by Calinou** [comment]
Has anyone been able to reproduce this since #31767 was merged?

**Comment by YeldhamDev** [comment]
@Calinou The error still occurs.

**Comment by akien-mga** [comment]
I can't reproduce it on 3.2.3 RC 1, can you check @YeldhamDev and attach a MRP if still valid?

**Comment by YeldhamDev** [comment]
@akien-mga Ha, it got even worse. It now gets stuck on the splash screen! :stuck_out_tongue_closed_eyes:

[popup_bug.zip](https://github.com/godotengine/godot/files/4982181/popup_bug.zip)

**Comment by YeldhamDev** [comment]
Not applicable anymore on `master`.
