### ISSUE TITLE
Default Zoom In shortcut key should be Command+Equal

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22067]
**Godot version:**
![godot3 1version](https://user-images.githubusercontent.com/930478/45556715-ef12c000-b809-11e8-9422-1f43aca39769.png)

**OS/device including version:**
MacBook Pro OS X High Sierra

**Issue description:**
Default zoom in key for in Editor shortcuts should be Command+Equal (it is set to Command+Plus which does not Zoom In)

**Steps to reproduce:**
![screen shot 2018-09-14 at 10 38 37 am](https://user-images.githubusercontent.com/930478/45557090-d22abc80-b80a-11e8-8184-336a0e559585.png)

**Comment by wyattbiker** [comment]
I am familiar with QWERTY keyboards which in my opinion are the most predominant. And they all seem to have the '=' below the '+' or just the '=' by itself. 

You can google keyboard images. 

Also, please verify the Editor  settings are getting saved. On my system they are not. After I restart Godot3.1 they seem to disappear. When do they get saved? I have a feeling it's related to another issue I reported. https://github.com/godotengine/godot/issues/21904

**Comment by akien-mga** [comment]
> Also, please verify the Editor settings are getting saved. On my system they are not. After I restart Godot3.1 they seem to disappear. When do they get saved?

That was fixed 5 days ago, but your build is older.
