### ISSUE TITLE
export (float, EASE) ZERO mode is misleading.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22079]
This is for 3.1 alpha 909c06e

Just a small thing I'm posting perhaps as enhancement/discussion.  I thought there was a bug with this at first  https://github.com/godotengine/godot/issues/21951, until @DualMatrix  pointed out the context menu.

So when declaring an export var for easing with no assignment or 0, it will be set in a Zero mode.  I know it must be tied into where it appears elsewhere, but in the inspector is a bit confusing, since it isn't immediately obvious what might be a good default value to set for this type.

Not sure about what would make it better.  Perhaps still showing some kind of line in a curve editor that can be dragged out from that mode.

![45317760-97dbc980-b543-11e8-95a6-881997dc0031](https://user-images.githubusercontent.com/13004169/45570904-2070a780-b86d-11e8-9487-8725c6f3adcc.png)

It can start like this, and be unresponsive unless you right click to discover these options.

![45317764-990cf680-b543-11e8-88e8-c3659401b64b](https://user-images.githubusercontent.com/13004169/45570901-1e0e4d80-b86d-11e8-8d5b-79f8aa400f31.png)

Totally didn't try right-clicking until told about it.  X)  These other options will unlock it back to a curve editor.

![godot_master_2018-09-14_22-20-43](https://user-images.githubusercontent.com/13004169/45570980-6fb6d800-b86d-11e8-96f9-1244e3af8961.png)

**Comment by avencherus** [comment]
@Calinou I'd be curious if you had an opinion on this one.

**Comment by Calinou** [comment]
I think dragging an easing curve with a value of 0 should just turn it into a very low value like 0.001, so you can start dragging it into any shape again.

**Comment by avencherus** [comment]
Nice.  I believe that would solve the immediate confusion, and without adding anything extra to the widget.
