### ISSUE TITLE
Boot splash image is also used when Godot editor starts

### ISSUE THREAD

**Issue by andrea-calligaris** [godotengine/godot#22073]
**Godot version:**
Master

**Issue:**
Issue #4739 has been closed, but in master, if you choose an image for the boot splash, it's also used by Godot editor when it opens your project. If this is intended, I don't think it is a reasonable behavior.

**Steps to reproduce:**
Set a custom splash image in your project. Now it is used when your game boots.
Notice that it's also used by the Godot editor when it opens your project: some may like this, others may not.
This is especially important when the user replaces the boot splash with a blank image because he's using a custom splash screen scene. As an unexpected side effect, he will get a black boot splash when he opens his game project with the Godot editor.

**Example project:**
[boot_splash.zip](https://github.com/godotengine/godot/files/2384781/boot_splash.zip)

**Comment by akien-mga** [comment]
I don't mind either way, but yeah it can be fixed not to load the bootsplash of the project.

**Comment by avril-gh** [comment]
i like this behavior, it does not start when editor starts.
It starts when certain project is worked on with boot image related to this project.

**Comment by char0xff** [comment]
@avril-gh What if you have a black empty boot splash because your project has its own splash screen scene? You may still want to see Godot's boot splash when you load your Godot project, instead of an empty black window.

**Comment by avril-gh** [comment]
matter of taste

**Comment by char0xff** [comment]
@avril-gh My post is clear enough, try reading it again. The user may still want Godot's editor to show its boot splash. Godot's editor is not your game.
About the "matter of taste", of course, but there should be the possibility to choose.

**Comment by williamd1k0** [comment]
> @char0xff What if you have a black empty boot splash because your project has its own splash screen scene? You may still want to see Godot's boot splash when you load your Godot project, instead of an empty black window.

Same. I want to see Godot's boot splash 😅

**Comment by avril-gh** [comment]
no, i meant... :joy_cat:  ... what should be the answer to _"i set a black screen and i dont like it ?"_ 
Perhaps i should'nt answer at all, but... i just couldnt hold it.
Please forgive my sense of humor :two_hearts:

But serious, i seen fiew topics where discussion been about that on some devices splash is gone too fast and on others its hold for long time, and yet others like to add scene as spash ect.
Could just add a black screen with small "loading..." text in corner and then it "fixes" problem with different loading times, after which if someone like to use scene as splash then its a nice continuation.

Ofcourse there could be another solutions like add setting for "minimal" time for splash in seconds, which ensure that someones logo will be visible for that long independently from device speed and other factors.

If you meant the godot logo, it is shown by default in editor and project if one not change it manualy in settings providing different splash.

**Comment by char0xff** [comment]
@avril-gh 
> "loading..." text in corner

No need for that, an option to disable the boot splash and have a black screen would be enough.

> "minimal" time for splash in seconds

That would be useful, and there already are issues proposing this.

> the godot logo, it is shown by default in editor and project if one not change it manualy

I know, this issue thread is about keeping the boot splash of Godot and the boot splash of your game two separate things, so that changing one does not change the other.

**Comment by avril-gh** [comment]
> this issue thread is about keeping the boot splash of Godot and the boot splash of your game two separate things, so that changing one does not change the other

so you want to show two splash screens, one after another and with different combination's for editor, for edited game and perhaps released game ?

...you should change issue title and make first post to be more descriptive.

**Comment by akien-mga** [comment]
The issue is clear to me, I don't know why so much discussion is needed.

But yes, steps to reproduce (as asked by the template) would help to make it crystal clear :)

Basically:
- Set a custom splash screen in your project, it's used when you play your game -> YAY
- Then notice that it's also used when you open your project in the editor -> YAY for some, NAY for others

**Comment by aaronfranke** [comment]
It would make more sense to have Godot's splash screen when you run the editor. Since the thing running is not your project, but the editor, which opens your project. It would also provide instant visual feedback that you didn't accidentally click "Run" instead of "Edit".

**Comment by KoBeWi** [comment]
> It would also provide instant visual feedback that you didn't accidentally click "Run" instead of "Edit".

On the other hand, right now you get a feedback that you didn't open wrong project. Also you can edit project by double-clicking it. Personally, I never use the Edit button.

**Comment by MewPurPur** [comment]
Additional discovery - The minimum display time of the boot splash is used too.

**Comment by CaptainOtto** [comment]
Would love for there to be a specific one for editor and another one for the game project.

Because its 2 very different things, atleast the possibility to be able to pick a different one for each.

**Comment by Dancovich** [comment]
> Would love for there to be a specific one for editor and another one for the game project.

It would be nice if all the splash screen configurations supported [feature tags](https://docs.godotengine.org/en/stable/tutorials/export/feature_tags.html). It would solve this issue (as you could leave the splash screen with default values if editor feature tag is set) and also allows us to have different splash screens for different platforms of the game.

Other project settings already support feature tags, like the rendering device.

![image](https://github.com/godotengine/godot/assets/1204296/9e3fdeb8-25d0-4e7a-aaed-1f59416cee21)

**Comment by akien-mga** [comment]
All project settings support feature tags, you can add them yourself if there's none preset.

**Comment by Calinou** [comment]
> Why then only some of these settings show in the project settings dialog without having to add them manually? Wouldn't this essentially fix this issue?

If we displayed optional overrides for every project setting, the dialog would become extremely convoluted. The vast majority of options never need platform-specific overrides.

**Comment by Dancovich** [comment]
> We don't seem to have a feature tag that's equivalent to `Engine.is_editor_hint()` to know whether actually running the editor or a game with an editor binary.

I see.

Well, at least it's a workaround as I personally don't see not having my splash when debugging being that big of an issue.

As @Calinou said, maybe we could have a new feature tag for this scenario. It would also be an alternative to `Engine.is_editor_hint()` as even if that method is convenient, I think it's a little buried (I also forget it's a static method inside Engine) and checking feature tags is an engine wide feature so it makes sense to also be there.
