### ISSUE TITLE
Unable to select overlapping tile regions in TileSet Editor

### ISSUE THREAD

**Issue by drako0812** [godotengine/godot#22077]
**Godot version:**
909c06ee0f0ab5feced1c9c99a725f7a423ff9f8 compiled with Mono support

**OS/device including version:**
Windows 10 Home 64-bit

**Issue description:**
In a large tile sheet there are situations where I need an auto-tile region to overlap either an individual tile or a tile atlas. Currently, I do not know of a way to specify which one of the overlapping regions I want to select. Clicking twice results in redefining the first region's region (bad wording, sorry).

I think the ability to shift-/control-click to cycle between overlapping regions would help. Or as a simplification, the shift-/control-click could select the closest top-left corner of some region.

**Edit:**
I forgot to mention, this is only a problem when one region completely envelopes another.

**Comment by akien-mga** [comment]
CC @MarianoGnu
