### ISSUE TITLE
Plugin description has no use

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#22072]
What is the plugin description for? I would expect for it to appear while mouse hovering the plugin name in the project settings, but in 3.0 it doesn't show up and in master you can only read it if you click _Edit plugin_.
The documentation doesn't say anything about this.

**Comment by akien-mga** [comment]
CC @willnationsdev

**Comment by willnationsdev** [comment]
@char0xff It's just not being displayed in the UI for some reason. I've added it to the "name" tooltip.
