### ISSUE TITLE
Ratio of boot splash image doesn't reflect Stretch options in project settings

### ISSUE THREAD

**Issue by andrea-calligaris** [godotengine/godot#22075]
**Godot version:**
3.0 and master

**Issue description:**
If you want your custom boot splash image to stretch the entire window, you can't do that. In fact, the boot splash image doesn't reflect the _Stretch_ options in the project settings.

**Example project:**
[boot_splash_ratio.zip](https://github.com/godotengine/godot/files/2384502/boot_splash_ratio.zip)

**Comment by char0xff** [comment]
Added an example project. The image is a 4x3 pixels wide.

**Comment by akien-mga** [comment]
See #20541.
