### ISSUE TITLE
Android in-app purchases error

### ISSUE THREAD

**Issue by SmithJohnFirst** [godotengine/godot#22082]
**Godot version:**
3.0.6 and 3.1 alpha

**OS/device including version:**
Windows

**Issue description:**
I added support for payments to my project. I used the [iap.gd script](http://docs.godotengine.org/en/3.0/tutorials/platform/android_in_app_purchases.html). On startup, I got an error:
`Failed to retrieve non-existent singleton 'GodotPayments'`

**Minimal reproduction project:**
The problem is observed in the official [demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/android_iap).

**Comment by akien-mga** [comment]
Closed by godotengine/godot-demo-projects@5b01dccc82c2da1d45c04a33884bd0d13c8a156a.
