### ISSUE TITLE
Can't add 3D animation event

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#22084]
Godot 3.1 alpha 1

I tried to add some event within a 3D animation, but there is no event button to create an event and name it , so the function name could be called in script.

Something like Unity can do for example 
https://docs.unity3d.com/uploads/Main/AnimationEditorEventLine.png

**Comment by mysticfall** [comment]
Godot has a function track which is a more flexible version of what Unity provides with animation events.

**Comment by groud** [comment]
Closing as the feature already exists as described by @mysticfall
