### ISSUE TITLE
Update documentation for recompiling Godot 3.1

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22085]
**Godot version:**
3.1 All versions

**OS/device including version:**
Should be for all devices.

**Issue description:**
Document steps for the most efficient way to recompile 3.1. Currently it takes me almost 1/2 hour. 

Please see the post and suggestions https://godotdevelopers.org/forum/discussion/20000/re-compiling-with-scons-3-1?new=1

**Comment by akien-mga** [comment]
It's documented already: http://docs.godotengine.org/en/3.0/development/compiling/introduction_to_the_buildsystem.html#platform-selection

It could be improved if you feel it's not clear enough, but documentation issues should be opened on the documentation repository: https://github.com/godotengine/godot-docs
