### ISSUE TITLE
Creating a C# script results in a crash

### ISSUE THREAD

**Issue by Christian-Pickett** [godotengine/godot#22088]
**Godot version:**

Godot_v3.0.6-stable_mono_x11_64

**OS/device including version:**

Lubuntu 18.04, x86_64 AMD CPU. Mono JIT compiler version 5.12.0.301

**Issue description:**

I had a 2dNode Greeter object with a greeter.gd script attached to it. I cleared this script because I wanted to try writing a C# script, and when I created the C# script, Godot then crashed.

**Steps to reproduce:**
select the greeter node -> select the clear script button -> select the create script button -> create a c# script

**Minimal reproduction project:**

[Hello Godot.tar.gz](https://github.com/godotengine/godot/files/2385100/Hello.Godot.tar.gz)

Here is a link to the output: https://pastebin.com/bw5QC1tp

Thanks for Godot! It's awesome!

**Comment by Christian-Pickett** [comment]
UPDATE: I apologize! This issue is due to my own error, I realized when I installed mono version 5.12.0.301, I only installed the mono-runtime package. After I installed the mono-complete package, I tried to recreate this issue and Godot did not crash.

**Comment by akien-mga** [comment]
No problem, thanks for the update :)

**Comment by aaronfranke** [comment]
Godot still shouldn't crash, instead, it should show you a warning. But that's covered by https://github.com/godotengine/godot/issues/15923
