### ISSUE TITLE
AudioStreamPlayer2D plays only in one channel

### ISSUE THREAD

**Issue by squareduck** [godotengine/godot#22093]
**Godot version:**
3.0.6.stable

**OS/device including version:**
MacOS

**Issue description:**
All imported .wav and .ogg sounds in AudioStreamPlayer2D use only right audio channel. In audio bus I can see that left channel is triggered, but just barely, so nothing is audible in it.

I have not found any settings to change or affect that in any way. Also no issues. VLC player or any other audio app plays the same sound files normally with even level on both channels.

**Steps to reproduce:**
Load a sound file in AudioStreamPlayer2D. Press "Playing" checkbox to test or trigger it from the script in game.

**Minimal reproduction project:**
In a new project this issue is not reproduced. My project is just a couple days old and there is no clear way to fix it.

**Comment by LikeLakers2** [comment]
I'm unable to replicate the issue. From what I can tell in my own testing, this is based on where the AudioStreamPlayer2D is placed in the scene relative to the center of the viewport. For example, if the AudioStreamPlayer2D is on the right half of the visible part of the viewport, then the sound will play more towards the right ear.

If you're looking to have background music, I'd suggest AudioStreamPlayer instead -- AudioStreamPlayer2D and AudioStreamPlayer3D are for positional audio.

**Comment by squareduck** [comment]
@LikeLakers2 Thanks, that was exactly my problem.

Replaced AudioStreamPlayer2D with just AudioStreamPlayer and now it's sounding good.
