### ISSUE TITLE
Editor settings are being constantly re-saved

### ISSUE THREAD

**Issue by elasota** [godotengine/godot#22097]
**Godot version:**
4547e22

**OS/device including version:**
Windows 10

**Issue description:**
Editor settings are being re-saved every UI update in the editor.

Possibly regression from https://github.com/godotengine/godot/pull/21717

Partial callstack:
`ResourceSaver::save(const String & p_path, const Ref<Resource> & p_resource, unsigned int p_flags) Line 46`
`EditorSettings::save() Line 964`
`SceneTreeDock::_update_create_root_dialog() Line 2247`
`Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1308`
`CreateDialog::_update_favorite_list() Line 583`
`Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1308`
`EditorFileSystem::update_script_classes() Line 1380`

**Steps to reproduce:**
Find editor-settings-3.tres file
Note file changed time stamp
When system clock changes, do anything that triggers a UI update
Editor settings file timestamp will change

Alternately, set a breakpoint in `ResourceSaver::save` and notice that it's firing on every UI update.

**Comment by akien-mga** [comment]
CC @willnationsdev (not 100% sure that it's related to script classes, but the stacktrace references it).

**Comment by willnationsdev** [comment]
If `EditorFileSystem::update_script_classes()` is getting called every UI update, that would mean that the script classes in the project settings file AND the icon paths in the editor settings file are both being serialized every UI update as well. That seems to be the core of the issue then, cause that shouldn't be the case, afaik. Need to find out why the UI updates are triggering that call.
