### ISSUE TITLE
Has notification (NOTIFICATION_TRANSFORM_CHANGED) stopped working?

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22098]
**Alpha 3.1 4547e22**

Was trying this out on a Node2D today, and nothing related to changing the position, scale, or rotation will fire this notification.  It seems it only happens once when it enters the scene.

Am I doing something wrong or is there any work around to this?  Thanks.

```
func _notification(what):
	
	if(what == NOTIFICATION_TRANSFORM_CHANGED):
		print("new transform")
```

**Comment by vnen** [comment]
Did you enable it with `set_notify_transform()` and/or `set_notify_local_transform()`?

**Comment by avencherus** [comment]
@vnen Thanks.  Would've never expected that, this one was in a blind spot for me.  I can see how it could be useful, but it is a rather confusing when it is off by default, and the notifications don't have some sort of standard option for turning them on and off.

I does strike me as out of place still.  Do you think it might be worthwhile to open another topic as a discussion/enhancement for notifications or at least turning these on by default?

> NOTIFICATION_TRANSFORM_CHANGED = 29  Canvas item transform has changed. _Only received if requested._

This makes sense now, but without knowing, this was a little vague and invisible.  The thought being, well I am requesting it.  X)

**Comment by vnen** [comment]
I assume it causes a significant performance overhead, so enabling by default is not a good option (especially since this notification is not commonly used).
