### ISSUE TITLE
accumulate mouse movement events

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#2209]
Many small mouse movement events from the window manager being processed by many Controls can slow down performance to seconds per frame territory.  These events need to be accumulated by the engine each frame, and the cumulative mouse movement sent to the Controls to process.  This could be made optional, as it might be desirable to know the *exact* path the mouse took through each substep during the frame.

**Comment by Kermer** [comment]
Confirmed. As long as they're visible, they cause a lot of performance drop, everything that inherits from them as well.
Adding 100, fresh Controls can easily drop your FPS to 0 if moving mouse fast enough.

**Comment by tolga9009** [comment]
I'm programming a card game and have run into the same problem. Each card (10 cards in total) and each field (9 fields in total) have their own Control node. I'm using them for point'n'click handling (maybe there are better methods to achieve this?). It's running perfectly fine with 400 FPS, if there is no mouse movement. But it crashes to around 10 FPS, as soon as I begin moving my mouse. This happens in 1.1 stable.

I've also tried the latest, unofficial Godot build from July 5 2015 (http://fixnum.org/godot/): it's not "extremely" slowing down anymore. Looks fixed for me, but I'm still wondering, which commit fixed this. Please check, if the latest build also fixed it for you.

**Comment by akien-mga** [comment]
According to #2219 most InputEvents would be affected, though it's mostly visible with mouse and joystick (and maybe touch drag?).

**Comment by reduz** [comment]
I don't think joystick or touch drag events are worth of being accumulated, they basically go nowhere unlike mouse events that go through the whole GUI. Joytick events are also kind of pointless since all platforms as far as I know just query the status once per frame
