### ISSUE TITLE
Anti alias and particle in divided view

### ISSUE THREAD

**Issue by fanatic2015** [godotengine/godot#2210]
Hello.

Especially it is seen in Navmesh Demo, divided viewport shows blurry anti alias, and too accelerated particle speed compared to single view.

https://kie.nu/2CDC
https://kie.nu/2CDD

Anti alias might be nvidia specific, though I'm not sure.
I would appreciate if you could look into this.

Thanks.

Gentoo Linux 3.18.12 64bit
Nvidia 349.16

**Comment by reduz** [comment]
ah yeah fxaa works a little weird in the editor, not completely sure why
(must be a bug)
when you run the project it should look fine

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by KoBeWi** [comment]
I inspected the issue and everything seems fine both in 3.1 and 3.0. So I guess it was resolved.
