### ISSUE TITLE
"extends" doesn't allow to create constant expressions that refer to the extended script elements

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#22106]
**Godot version:**
Godot_v3.0.5-stable_x11.64 **and** latest master, on Ubuntu

**Issue description:**
"extends" doesn't allow to create constant expressions that refer to the elements of the extended script, like enums.

**Steps to reproduce:**
_main_script.gd:_
`enum DIRECTIONS { up, right, down, left }`

_other_script.gd:_
```
extends "res://main_script.gd"

const MY_DIR = DIRECTIONS.up
```

_Compiling:_
`Expected constant expression`

**Comment by vnen** [comment]
Duplicate of #20008
