### ISSUE TITLE
Requesting improvement to GDScript Style Guide

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#22100]
**Godot version:**
Latest.

**Issue description:**
The [GDScript Style Guide](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html) should also talk about:
1) Using classes' members in place of set/get methods, or viceversa.
2) How we should name enums. Like constants?

I'm not making the changes myself because I don't know which is the correct/preferred style.

**Comment by akien-mga** [comment]
Documentation issues should be opened on the docs repository: https://github.com/godotengine/godot-docs
