### ISSUE TITLE
[EditorInterface] There is no way to retrieve the current edited scene path

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#22112]
**Godot version:**
Master

**Issue description:**
There is no way to retrieve the current edited scene path.

There is _get_open_scenes()_ to get the currently opened scenes, _get_edited_scene_root()_ to get the root node of the currently opened scene, and _get_selected_path()_ which returns the path of the current directory, but not the complete path of the edited scene.
We need either a _get_edited_scene_path()_ method or to change _get_selected_path()_ so that it returns the complete path of the scene.

And/or, _scene_changed_ signal of _EditorPlugin_ could be changed to also have the path of the scene as a parameter, like _scene_closed_ already does.

**Comment by avencherus** [comment]
I seem to be losing the context, which paths do you mean, node paths or file paths?

If you mean file path, you should be able to just access that on any node like:

`print(get_tree().edited_scene_root.filename)`

**Comment by char0xff** [comment]
@avencherus: Ah! You're right, my bad then.

**Comment by avencherus** [comment]
No problem.  ^_^
