### ISSUE TITLE
Double clicking on an unsaved signal, does not open script

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22116]
**Godot version:**
3.1

**OS/device including version:**
OS X, High Sierra

**Issue description:**
Does not open a nodes, Signal script if you double click on newly created method. You need to save the script first.

**Steps to reproduce:**

1. Add a Button to a Scene and a new Script. Save.
2. Add a a new Signal, e.g. _on_Button_pressed(), to the Button which will open the Script and show the new method.
3. Click on 2D to hide the Script
4. Now go back to the Button Signal list and double click on the newly created signal  _on_Button_pressed() name.
5. This will not open the Script and show the _on_pressed method as it should. You need to save it first it seems.

**Comment by KoBeWi** [comment]
Still valid in 3.2.2 rc2

**Comment by wyattbiker** [comment]
Not valid in 3.5 and 4.0 alpha. Should I close it.

**Comment by KoBeWi** [comment]
If it's really fixed then yes.
