### ISSUE TITLE
[3D] Graphical artefacts when Ambient Light, Omni-Light and Spot light on the same scene

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#2211]
_Bugsquad edit:_ Initially seen on 1.1-stable

When on the scene there are Ambient Light (from WorldEnviroment) and omni-light together with spotlights then depending on camera position some graphical artefacts will appear, video reference here:
http://youtu.be/JG0xGrrzBaQ
If we add on the scene also directional light the artefacts will disappear (even if energy of directional light is 0).
Here is a project that replicate this issue:
https://dl.dropboxusercontent.com/u/168251/godot/some/issues/Omni_Spot_lights_issue.7z

**Comment by reduz** [comment]
guess all this will be fixed in 3D renderer rewrite for 3.0

**Comment by reduz** [comment]
should no longer happen, everything is rendered on one pass now, closing
