### ISSUE TITLE
`export var name : Type = 'default value'` does not show the default value in the inspector

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#22124]
**Godot version:**
v3.1.dev.calinou.5df9109

**OS/device including version:**
Windows 10 Home v1803 (April 2018 update) x64

**Issue description:**
When a variable is exported with a default value and typed GDScript, but with no export hint (that is, in the format `export var var_name : Type = 'Some default value here'`), the inspector will show `Null` as the default value, rather than the specified default value.

The default value WILL show with the other forms of exporting variables:
```gdscript
# Token 1: TOKEN_HERE
export var token1 = 'TOKEN_HERE'

# Token 2: TOKEN_HERE
export (String) var token2 = 'TOKEN_HERE'

# Token 3: TOKEN_HERE
export (String) var token3 : String = 'TOKEN_HERE'
```

But again, not with this form:
```gdscript
# Token 4: Null
export var token4 : String = 'TOKEN_HERE'
```

However, despite it showing `Null` in the inspector, the default value will still be stored in that variable.

**Steps to reproduce:**
Add an exported variable with the same syntax as this example:
```gdscript
export var token : String = 'TOKEN_HERE'
```
and then check the inspector to see that it shows `Null`, instead of the default `TOKEN_HERE`.

**Minimal reproduction project:**
N/A (it would be faster to just follow the steps above)

**Comment by avencherus** [comment]
Confirmed today in 268ae71fae08587e6df5b3270b7fc4833f30e34e

**Comment by Ranoller** [comment]
This issue is still valid in Godot 3.1 compiled at 14/jan/2019
