### ISSUE TITLE
Saving while editing scripts shifts cursor focus to the node inspector

### ISSUE THREAD

**Issue by ffaristocrat** [godotengine/godot#22125]
**Godot version:**

3.1.alpha.official

**OS/device including version:**

OSX High Sierra 10.13.6 (17G65)

**Issue description:**

Ran into this while doing the tutorial.
http://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html

Saving a node's gdscript while the inspector is open for it shifts the cursor focus to the node inspector. However, it only does this if you've had the focus in the inspector already.

**Steps to reproduce:**

1. New project
2. Create a Node2D
3. Select node, attach & create a new gdscript
4. Command-S to save. Focus remains where it should
5. Select the Node2D and open a drop down, check/uncheck a box, etc to put the focus in the inspector
6. Return cursor to the script editor
7: Command-S to save. Cursor focus shifts to the inspector.

**Minimal reproduction project:**

**Comment by name-here** [comment]
I couldn't reproduce this in either 3.2.3 or master on MacOS Catalina (although current master unfocuses the main window every time you save).  I can, however, reproduce it in 3.1 alpha 1.  Looks like this was fixed already.

**Comment by ffaristocrat** [comment]
Happy to close then if it's been fixed.
