### ISSUE TITLE
Autocompletion doesn't work on constants defined below the typing area.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22121]
**Version: 4547e223**

@vnen Perhaps related to something else ongoing, but noticed that constants when place below a code block will stop appearing for the auto-completion.  I think maybe some other things here and there as well, but didn't think to isolate them at the time.  Wasn't sure of the cause, and thought maybe there were some general stability issues with code completion.  (Like this:  https://github.com/godotengine/godot/issues/21915)

# Above, working as normal.
![godot_master_2018-09-15_22-45-46](https://user-images.githubusercontent.com/13004169/45590055-1a47fd00-b939-11e8-9800-de80dfb58b02.png)

# Below, not so much.
![godot_master_2018-09-15_18-03-02](https://user-images.githubusercontent.com/13004169/45590036-dd7c0600-b938-11e8-8eed-291a2d55d662.png)

**Comment by vnen** [comment]
It's a bit of a general problem with completion that it uses the parser but when it needs completion is always when the parsing would fail. The parser tries to recover but it can easily consume the next line(s) while trying to do so.

**Comment by avencherus** [comment]
I see, apparently I'm slow to notice this, as it looks like it has been this way for quite some time.  X)

Just curious if it is a strict limitation, or might be something that is being investigated already?

**Comment by vnen** [comment]
> Just curious if it is a strict limitation, or might be something that is being investigated already?

It is a limitation of the current system. After 3.1 I'll try research a better way to do the completion that doesn't have this problem.

**Comment by avencherus** [comment]
Definitely looking forward to more of your work in these areas.  X)

**Comment by hilfazer** [comment]
Works fine in 3.1.1 

![autocompleteConstBelow](https://user-images.githubusercontent.com/29497869/58380916-ed63e380-7fb7-11e9-935c-85c808152934.png)

vnen wasn't lying whe he told he's gonna look into this after 3.1.

**Comment by KoBeWi** [comment]
Fixed around 3.2 beta1. #31843 might be related
