### ISSUE TITLE
export (ENUM) var a little verbose

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22122]
**Version: 4547e223**

Currently when an enum or const dictionary are supplied to an export var in the inspector.

Not sure if this is desirable, since the spirit of the enumerations is to shield our eyes from magic numbers.  Can get pretty messy in some cases.

![godot_master_2018-09-15_20-12-10](https://user-images.githubusercontent.com/13004169/45590123-5b8cdc80-b93a-11e8-9e3c-5e0ad7d398ce.png)

**Comment by DualMatrix** [comment]
I agree, the number should not be needed and makes it look kinda ugly.

**Comment by DeuxAlpha** [comment]
I agree as well, but is that the consensus? Specifically, should the solution to this issue be that we delete the number or have it be connected to a setting the user can change?

**Comment by neikeq** [comment]
This only happens when using the `hint_string` format that explicitly specifies the values: `elem_one:0,elem_two:1,...`.
