### ISSUE TITLE
A small bug in the script editor ('\' simbol)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#2212]
Hi. The calculation does not include padding string after the operator '\'. (wrap long lines)
This is evident in the allocation of lines debugger. Ie debugger highlights the line located above the erroneous line in the Number of characters '\' code.

**Comment by reduz** [comment]
thanks for reporting this!

**Comment by neikeq** [comment]
I suppose this is the issue that was fixed by 0e0a7c9. The commit specified a wrong id.

**Comment by vnen** [comment]
I think you're right @neikeq, thanks. I'm gonna close this as fixed.
