### ISSUE TITLE
Area with zero gravity not works correctly.

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#2213]
In 3D scene, I am trying to set zero gravity, but when the game start all rigid bodies are falling for 5 seconds very slowly and then they stop, they must start with no velocity.

**Comment by reduz** [comment]
think you could make a simple testcase and attach it?

**Comment by guilhermefelipecgs** [comment]
Here it is: https://github.com/guilhermefelipecgs/zero_gravity

**Comment by guilhermefelipecgs** [comment]
I found the problem here in this line:
https://github.com/okamstudio/godot/blob/master/servers/physics/body_sw.cpp#L385

I saw that in first step the ac variable is equal to 0 and after they change for 1, seems that the physic engine isn't getting the area in the first step.

**Comment by kubecz3k** [comment]
@guilhermefelipecgs I was testing 0 gravity in 3d. Basically for now you can workaround this easily. Just add a Timer on a scene set his parameters to one time start automatically, set a signal from him after 0.1 sec to the scene code and reset linear velocity of all physical nodes to 0,0,0 when this signal is fired.
