### ISSUE TITLE
Casting Code Completion Doesn't Detect Inherited Members

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#22130]
**Godot version:**
3.1 alpha

**OS/device including version:**
Windows 10

**Issue description:**
When casting a reference, autocompletion doesn't account for inherited members.

```
extends Node2D
class_name Space

var row:int
var col:int

func _ready():
	pass
```

![6ee26107bcc3552b56c039910dee6e15](https://user-images.githubusercontent.com/21234930/45591396-4eee9100-b906-11e8-9ce0-7ad750a5a751.png)

Note how you don't see any help for Node2D members, which Space inherits, only the members for Space itself.

**Comment by KoBeWi** [comment]
Works in 3.2
