### ISSUE TITLE
"argument is never used" warning when passing argument to base class _init() function.

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#22139]
**Godot version:**

3.1 alpha

**OS/device including version:**

Windows 7 SP1.

**Issue description:**

Variable `a` is passed from Derived `_init()` to Base `_init()` so it's being used but i'm getting this warning:

```
0:00:00:0202 - The argument 'a' is never used in the function '_init'.
----------
Type:Warning
Description: The argument 'a' is never used in the function '_init'.
Time: 0:00:00:0202
C Error: UNUSED_ARGUMENT
C Source: res://Node.gd:16
C Function: 
```

**Steps to reproduce:**
Run reproduction project and check warnings.

**Minimal reproduction project:**

https://github.com/hilfazer/Projects/tree/EngineIssues/Godot/UnusedVariableBaseConstructor

**Comment by girng** [comment]
you can disable warnings in project settings -> gdscript

**Comment by akien-mga** [comment]
> you can disable warnings in project settings -> debug -> gdscript

That's not a solution for fixing engine bugs :)

**Comment by akien-mga** [comment]
> see my other post in typed gds thread. the entire typed gds is bugged and makes developers feel terrible when coding. it's best (and a solution) to disable warnings related to it.

No it's not. If the feature is bad, it should be enhanced (or removed - but I don't think it's that bad).
