### ISSUE TITLE
Godot should automatically convert 2.x code to Godot 3.x

### ISSUE THREAD

**Issue by swdeseng** [godotengine/godot#22141]
**Godot version:**
3.x

**OS/device including version:**
n/a

**Issue description:**
code has to be converted by person, should be automatic.  Not enough documentation exists to self debug all the issues.  Time constraint.

**Steps to reproduce:**
Example 1) following a 2.x tutorial, much code conversion exists, but this isn't all.  The UI is different in cases as well. Example 2) Run your 2.x code on Godot 3.x

**Minimal reproduction project:**
Recommend having the program automatically convert the code or having a migration tool.

**Comment by avencherus** [comment]
This option at least exists in 2.1.5.

![godot 2 1 5 stable_2018-09-16_12-25-11](https://user-images.githubusercontent.com/13004169/45594913-9713bf00-b9ab-11e8-8ff5-292972e55920.png)

However, it can only do so much.  Some things have gone away entirely so there is no direct one for one conversion,  There isn't anything yet that can perfectly intuit your intentions and faithfully recreate new code based on your old code in different environments.

**Comment by girng** [comment]
better start now my friend lol

**Comment by groud** [comment]
This is not possible, the API changed a lot which makes translating code from one version to the other very difficult. Thus it cannot be made automatically.

**Comment by Chaosus** [comment]
Yeah, its changing rapidly. In 4.0 API will not be fully compatible even with 3.0. Dont know which volunteer want to write and support this titanic work from scratch..

**Comment by Chaosus** [comment]
I think its pointless to wait for someone to implement such complex thing, otherwise its already been existed. Closed.

**Comment by swdeseng** [comment]
Thanks for the feedback.  I like Godot and just trying to help improve it.
My intent here is forward thinking.  I realize it is a complex ask.  I converted the code for 7 tutorials before giving up.  I was introducing a new concept, that we start move forward by having such technologies in current times.  I was hooping to hear a counter, perhaps something like... it's a complex ask to do entirely atm; however we can improve the docs, improve the intellisense and work on a simple conversion/migration program which does some of the work via suggestion or the like.  

It's hard to find enough examples on YT for Godot 3.0 that can teach all of the techniques needed, especially for someone new to Godot.  I spent much time converting the code of a 2.x tutorial myself, the instructor is very good and I find no competing example as good for 3.0 on this particular topic.

However, by the time I reach many instanced scenes, it consumes too much time and there is just not enough information online to figure it out.

I was hoping someone would offer a solution or alternative solution.

Thanks,
I look forward to the Godot 3.1 release.

**Comment by swdeseng** [comment]
> 
> 
> This option at least exists in 2.1.5.
> 
> ![godot 2 1 5 stable_2018-09-16_12-25-11](https://user-images.githubusercontent.com/13004169/45594913-9713bf00-b9ab-11e8-8ff5-292972e55920.png)
> 
> However, it can only do so much. Some things have gone away entirely so there is no direct one for one conversion, As far as I understand it, there isn't anything yet that can perfectly intuit your intentions and faithfully recreate new code based on your old code in different environments.

I'll consider starting the tutorial over in 2.1.5 and see how well the conversion to 3.x goes.  Thanks

**Comment by swdeseng** [comment]
> 
> 
> Yeah, its changing rapidly. In 4.0 API will not be fully compatible even with 3.0. Dont know which volunteer want to write and support this titanic work from scratch..

Think big not small my friend.

**Comment by swdeseng** [comment]
> 
> 
> I think its pointless to wait for someone to implement such complex thing, otherwise its already been existed. Closed.

New ideas and inventions haven't been invented yet until we create them.

**Comment by swdeseng** [comment]
> 
> 
> This is not possible, the API changed a lot which makes translating code from one version to the other very difficult. Thus it cannot be made automatically.

I figured it wouldn't hurt to ask.  A smaller subset would be a good start.

**Comment by swdeseng** [comment]
> 
> 
> > **code has to be converted by person**, should be automatic. Not enough documentation exists to self debug all the issues. Time constraint.
> 
> better start now my friend lol

I don't have a specific project, however I would like to learn at a steady pace.  What I should have said, the conversion of code was dragging the pace down.  I started over in 2.1.5.

**Comment by swdeseng** [comment]
> 
> 
> This option at least exists in 2.1.5.
> 
> ![godot 2 1 5 stable_2018-09-16_12-25-11](https://user-images.githubusercontent.com/13004169/45594913-9713bf00-b9ab-11e8-8ff5-292972e55920.png)
> 
> However, it can only do so much. Some things have gone away entirely so there is no direct one for one conversion, As far as I understand it, there isn't anything yet that can perfectly intuit your intentions and faithfully recreate new code based on your old code in different environments.

I redid the tutorial up to the same point, Exported to 3.0 (WIP) with notes.  Unfortunately, I haven't found any changes yet, so I did the typical manual conversions. get_mouse_pos = get_mouse_position, Width = x, Height = y

Can you direct me to find the resource / documentation for converting the rest of 2.x to 3.x code?  ie. 	2.x = yield(get_node("anim"), "finished") 3.x = ?
I could use the help in finding the resources, right now I'm using internet search which are sparse and intellisense.

I appreciate any direction.

**Comment by swdeseng** [comment]
> 
> 
> I think its pointless to wait for someone to implement such complex thing, otherwise its already been existed. Closed.

FYI, the export feature in 2.1.5 shows you are working on it, right?

**Comment by vnen** [comment]
> FYI, the export feature in 2.1.5 shows you are working on it, right?

It is only a project conversion to allow you to open old scenes in the new version (while translating as much as possible). But there's no **code conversion** which was the original request in this thread. Converting code is very hard.

It's also pointless because when time passes there's less people using the 2.1.x series, so the number of users of that tool will only diminish. People with deep projects in 2.1.x probably won't take the effort to make the migration with the risk of facing new bugs and undoing the workarounds for bugs that were fixed.

So the problem is not only the amount of work, but also that it brings almost no gain.

----

For more specific guidance and help with the translation, consult some of our [community channels](https://godotengine.org/community). Unfortunately there's not much documentation about the changes.

**Comment by swdeseng** [comment]
> 
> 
> > FYI, the export feature in 2.1.5 shows you are working on it, right?
> 
> It is only a project conversion to allow you to open old scenes in the new version (while translating as much as possible). But there's no **code conversion** which was the original request in this thread. Converting code is very hard.
> 
> It's also pointless because when time passes there's less people using the 2.1.x series, so the number of users of that tool will only diminish. People with deep projects in 2.1.x probably won't take the effort to make the migration with the risk of facing new bugs and undoing the workarounds for bugs that were fixed.
> 
> So the problem is not only the amount of work, but also that it brings almost no gain.
> 
> For more specific guidance and help with the translation, consult some of our [community channels](https://godotengine.org/community). Unfortunately there's not much documentation about the changes.

Thanks for the feedback, makes sense.  Being new to coding and Godot, I am realizing some code conversion can be as simple as a search / replace, other code can be more tricky than that.  I redid the tutorial in 2.x and works fine.  I'm doing the code conversion now as more of an exercise to challenge myself in learning the code.  Maybe a bit silly since 2.x it's out of date, but it's more about using the debugger and resources at hand to find solutions to problems in front of me.

Thanks for bringing the community a great product for free.
