### ISSUE TITLE
Rename "subscene" menu item and move it

### ISSUE THREAD

**Issue by Fiona** [godotengine/godot#2214]
Okay this is a bit of a weird one, but the way I've been developing now has been to mock objects inside a scene as child nodes as tests. Inevitably, if it's all okay and the complexity necessitates it, I keep needing to upgrade them to their own scenes for instancing. This means painstakingly rebuilding the node and it's children. (Or copying the scene and deleting everything that isn't what I want.) 

I don't know what the feasability of this would be, but a way to take a node (and all it's children) and upgrade them to their own scene file would greatly help this workflow.

Also happy to get some discussion on this particular workflow and even if I'm just "doing it wrong". I don't think having hindsight is a super great answer to it though as that goes against experimentation and rapid development.

**Comment by reduz** [comment]
scene -> convert to -> subscene

**Comment by Fiona** [comment]
Shoot me. I had no idea that was there! Hahaha. Thanks - bit of a weird place for it though since most of the actions that operate on nodes are icon buttons around the tree. Which is why I couldn't find it! Perhaps move it for 1.2?

**Comment by reduz** [comment]
yes definiely has to move, just not sure where yet

**Comment by Fiona** [comment]
As an icon next to reparent would go a long way towards it being in a better place. You might be getting dangerously close to icon-hell, but I still think it would be better.

Also, this might just be me, but I suspect that "subscene" isn't the best word for it. It's not very descriptive, it implies that a subscene is a separate concept, when in reality you just have scenes and instances of scenes. Unless I'm misunderstanding?

**Comment by romulox-x** [comment]
I agree that the word subscene is confusing.  It sounded mysterious and new when I first saw it, and I wondered what a subscene was as compared to a scene.  Then it turned out it's just a regular scene.

**Comment by mamarilmanson** [comment]
childscene? 

:)

**Comment by Fiona** [comment]
click node > "Create New Scene From" button.
![godot_icon_create_new_scene](https://cloud.githubusercontent.com/assets/30786/8429333/8757f016-1f1e-11e5-92e9-886636255548.png)

@reduz would you accept this as a pull request?

**Comment by okamstudio** [comment]
sure! looks good to me

On Tue, Jun 30, 2015 at 7:53 AM, Fiona Burrows <notifications@github.com>
wrote:

> click node > "Create New Scene From" button.
> [image: godot_icon_create_new_scene]
> <https://cloud.githubusercontent.com/assets/30786/8429333/8757f016-1f1e-11e5-92e9-886636255548.png>
>
> @reduz <https://github.com/reduz> would you accept this as a pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2214#issuecomment-117123990>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment]
these menus will be rewritten in 2.1, so will wait until then

**Comment by akien-mga** [comment]
Fixed with #2928 in 2.0.
