### ISSUE TITLE
[Regression] _UnhandledInput does not receive mouse events when scene contains AnimationPlayer

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22140]
**Godot version:**
`master` / 787be50f1

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
After updating the build to 787be50f1, `Node._UnhandledInput` fails to receive events of type `InputEventMouseMotion` and also normal input actions registered for mouse wheel movements.

It seems that the problem only occurs when the scene contains an `AnimationPlayer` instance.

The last known revision I tested which does not exhibit such a symptom is db26c1205.

**Comment by akien-mga** [comment]
Works fine for me in current master branch. As always, please add precise reproduction steps and ideally an example project that reproduces it.

In my case, this works:
```gdscript
extends Node2D

func _unhandled_input(event):
	print(event.get_class())  # Properly prints `InputEventMouseMotion` when moving mouse
	print(event.is_action("scroll_up"))  # Properly prints `True` when using `scroll_up` action
```

**Comment by mysticfall** [comment]
Did more testing and it turns out that the problem only occurs when the scene contains an `AnimationPlayer` node. I updated the description accordingly.

**Comment by akien-mga** [comment]
Still can't reproduce it with an `AnimationPlayer` as child of my root node (which has the script attached).

**Comment by mysticfall** [comment]
By the way, the scene I tested had an event listening node (extends `Node` with overriding `_UnhandledInput`) as a sibling to an empty `AnimationPlayer` node.

Could you try again with moving the `AnimationPlayer` as described? If it doesn't reproduce the problem, I'll try to create a sample project in a few days.

**Comment by akien-mga** [comment]
Still works fine for me with a `Node` having the above script (with `extends Node` instead of `extends Node2D` of course) and with an `AnimationPlayer` sibling.

**Comment by mysticfall** [comment]
Ok, I'll try to upload a sample project soon, and maybe doing more tests to pinpoint the cause. Thanks.

**Comment by mysticfall** [comment]
Created a minimal project that exhibit the problem:
[EventTest.tar.gz](https://github.com/godotengine/godot/files/2392644/EventTest.tar.gz)

If you run `EventTest.tscn` and move your mouse, you can see generated events are logged in the console.

But if you run `EventTest2.tscn` which is identical with the previous scene except that there's an empty `AnimationPlayer` node in the hierarchy, nothing gets logged even when you move your mouse.

**Comment by akien-mga** [comment]
Still no bug for me after converting the script to GDScript. I'll build Mono now to see if it's C#-related somehow.

**Comment by mysticfall** [comment]
I just tested it with a GDScript version again and I had the same problem. I'll update my build to the latest revision again and see if it'd make any changes.

**Comment by mysticfall** [comment]
I think I found a way to reproduce the problem. It's quite strange, but it looks like the problem only shows when you add an `AnimationPlayer` then run it without closing the editor.

If you close and open the editor again, the same scene runs as expected. But if you delete the `AnimationPlayer` node and add it again, then the problem returns until you restart.

Note that my actual project doesn't show this intermittent behavior but constantly exhibits the symptom but it's much more complex than the sample project I attached above.

**Comment by akien-mga** [comment]
Silly question, but you're sure that it's not just because it shows the "Animation" bottom panel by default instead of the "Output" panel where your prints are echoed?

**Comment by mysticfall** [comment]
I doubt it, because with my real project, the all mouse related controls actually stop working unless I change iit to `_Input`.

**Comment by akien-mga** [comment]
I've tried with a mono build (at f148e8ee), and still can't reproduce any `_UnhandledInput` issue, even if I remove and readd an `AnimationPlayer` node. The only thing I noticed is as mentioned above, when the `AnimationPlayer` is selected in the scene tree dock, the corresponding bottom panel is shown and thus I don't see the prints (but they still work and I can see them after toggling the "Output" panel).

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by ivansla** [comment]
hi guys,

I managed to reproduce the issue in my godot studio. When you run the code the unhandled input will not work, but when you remove stage_manager.tscn from auto load in Project Setting and run the code again, the unhandled input will work. Then when you add again stage_manager.tscn into auto load it will stop working.

Screenshot of auto load window.
![image](https://user-images.githubusercontent.com/11456054/52306480-69e69e00-2998-11e9-931b-547f6d164267.png)

Screenshot when it works with input and unhandled input
![bothinputs](https://user-images.githubusercontent.com/11456054/52306365-08263400-2998-11e9-8a6b-4272d24abd6f.PNG)

Screenshot when it works only with input
![onlyinput](https://user-images.githubusercontent.com/11456054/52306366-08263400-2998-11e9-917b-9a31121e251e.PNG)

Screenshot of my godot studio version
![image](https://user-images.githubusercontent.com/11456054/52306265-b7aed680-2997-11e9-8dac-53e88fbdfc54.png)

Project that can reproduce the issue
[unhandled_input_bug.zip](https://github.com/godotengine/godot/files/2834007/unhandled_input_bug.zip)

**Comment by akien-mga** [comment]
@ivansla That seems to be a different issue, and likely not a bug. Your autoload scene is a `CanvasLayer`, which likely captures the input so you have no unhandled input.

**Comment by akien-mga** [comment]
I still can't reproduce @mysticfall's issue and there were no other reports of it happening, so I'll close.
