### ISSUE TITLE
Platform Server fails to export

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#22148]
https://github.com/godotengine/godot/commit/787be50f1760be541e97b18a371abccc9c9b1ac9
x11
https://github.com/godotengine/godot/pull/21927

`./../godot_server.server.tools.64 --path ./ --export "Linux/X11" ./../exports/test.x86_64`

```
ERROR: instance: Class 'EditorSettings' can only be instantiated by editor.
   At: core/class_db.cpp:518.
ERROR: poll: /home/alexholly/.config/godot/editor_settings-3.tres:3 - Parse Error: Can't create sub resource of type: EditorSettings
   At: scene/resources/scene_format_text.cpp:560.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:155.
ERROR: _load: Failed loading resource: /home/alexholly/.config/godot/editor_settings-3.tres
   At: core/io/resource_loader.cpp:192.
WARNING: create: Could not open config file.
   At: editor/editor_settings.cpp:846.
ERROR: vformat: Condition ' error ' is true. returned: String()
   At: core/variant.cpp:3252.

```

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by AlexHolly** [comment]
`--export` seems to be a bit broken the build works but shows errors.

```
ERROR: instance: Class 'EditorSettings' can only be instantiated by editor.
   At: core/class_db.cpp:518.
ERROR: poll: /home/alexholly/.config/godot/editor_settings-3.tres:3 - Parse Error: Can't create sub resource of type: EditorSettings
   At: scene/resources/scene_format_text.cpp:560.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:202.
ERROR: _load: Failed loading resource: /home/alexholly/.config/godot/editor_settings-3.tres
   At: core/io/resource_loader.cpp:279.
WARNING: create: Could not open config file.
   At: editor/editor_settings.cpp:876.

...

savepack: end
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:70.

```

**Comment by mikeKulasinski** [comment]
I have noticed that when using '/opt/godot/godot --export-debug Android x.apk' in command line editor_settings-3.tres get changed all settings for android are reset and export does not export android.apk at all

`export/android/adb = ""
export/android/jarsigner = ""
export/android/debug_keystore = ""`

**Comment by groug** [comment]
Hi,

Any news about this issue? I've migrated my projet from 3.0 to 3.1, and have this exact same problem on Windows and Linux. Same error, same config override. Exporting to Android from cli is now impossible since it removes important fields.

**Comment by groug** [comment]
So I've been testing different things with the "normal" build and  the headless build, and I have more info:

- If I don't give the path (I was calling the command from my project directory) or use --path: I have the error from this issue and my .tres is being re-written
  - examples:
    - `cd FULL_PATH; /opt/Godot/Godot_headless --export-debug Android /tmp/project.apk`
    - `/opt/Godot/Godot_headless --path FULL_PATh --export-debug Android /tmp/project.apk`
- If I give the path to my .godot project, it works
  - examples:
    - `cd FULL_PATH; /opt/Godot/Godot_headless project.godot --export-debug Android /tmp/project.apk`
    - `/opt/Godot/Godot_headless FULL_PATH/project.godot --export-debug Android /tmp/project.apk`

**Comment by and3rson** [comment]
I can confirm that fix by @groug works.

**Comment by akien-mga** [comment]
Seems to work fine in the current master branch (ae21664655).
It works both with a pre-existing `.import` folder and if it's missing (in the latter case, it reimports everything before exporting).

#34887 improved usability and documentation, so it should be clearer how to export from the command line now.
