### ISSUE TITLE
WorldEnvironment's Glow effect has several issues in Canvas mode

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#22152]
**Godot version**
3.0

**OS/device including version:**
Windows 10

**Issue description:**
There are several issues I'm having with the glow effect which is available for 2D projects.

So I have added a WorldEnvironment node to my main scene, added Environment resource to it and set Background Mode to Canvas. I've enabled Glow and modified few properties to my liking.

First issue I've noticed is that only horizontal lines tend to glow:

![c1](https://user-images.githubusercontent.com/26509794/45597099-18c51600-b9c7-11e8-8a06-9950153de94b.png)

here is animated version, clearly showing glow appears only when the line is horizontal:

![a1](https://user-images.githubusercontent.com/26509794/45597102-27133200-b9c7-11e8-9197-07df25a7478e.gif)

However when I zoom in close enough, the vertical line starts to glow, but not as bright as the horizontal one:

![c2](https://user-images.githubusercontent.com/26509794/45597115-6b9ecd80-b9c7-11e8-8e91-5225dda4ebbe.png)

Another issue happens when I've zoomed out far enough and am moving perpendicular to the horizontal line. The line's glow enters epileptic mode, constantly appearing and disappearing:

![a2](https://user-images.githubusercontent.com/26509794/45597132-c2a4a280-b9c7-11e8-841c-9753c8d34256.gif)

This all was done in 2D. The lines were drawn using draw_line method and line_width was set to 2.0. I recommend trying the minimal project yourself.

**Steps to reproduce:**
Add WorldEnvironment node to 2D root node.
Add new Environment resource to it.
Set Background/Mode to Canvas.
Enable Glow and modify its properties until you get the actual glow (mine are Intensity = 1.5, Strength = 1.4, Levels = (1, 3)).
Either draw some horizontal and vertical lines on screen, or add similar sprites.
Move around and zoom around to notice the effects.

**Minimal reproduction project:**
[Line glow test.zip](https://github.com/godotengine/godot/files/2386626/Line.glow.test.zip)

I have also added basic movement of a camera so you can explore the effects.

**Comment by CptPotato** [comment]
It's most likely a downsampling "issue" (or "limitation", depending on how you look at it).
Fine details might not make it through the downsampling process depending on how it is done.

I don't know how godot performs downsampling so I can't tell if it's just due to low sample count or bad sample placement (or another mistake in this area).

**Comment by clayjohn** [comment]
Superceded by https://github.com/godotengine/godot/issues/32030 as there is more conversation there. I will link here because the issue description is very good.
