### ISSUE TITLE
Add nearly equal for floats

### ISSUE THREAD

**Issue by maksloboda** [godotengine/godot#22159]
<a href="http://api.unrealengine.com/INT/BlueprintAPI/Math/Float/NearlyEqual_float/">Nearly equal</a> is a very useful tool for floats.

**Comment by Chaosus** [comment]
It was already been proposed and I did a corresponding PR, but @reduz is declined it https://github.com/godotengine/godot/pull/17975

**Comment by aaronfranke** [comment]
@akien-mga This can be closed now, I forgot to mark my PR as resolving this.
