### ISSUE TITLE
Gi probe too much bright 

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#22153]
Godot 3.1 alpha 3

Win 7 64 bits.

Custom shader code seems to no more work (lighting or color is broken, it worked before).

Left model is custom shader with color not working, right model using SpatialMaterial with color working.
https://github.com/DevMagicLord/Godot3/blob/master/bugs/shaderbug.jpg?raw=true

This is the custom shader code , that doesn't display correctly with texture assigned in the editor.
```

    shader_type spatial;
	
    uniform float tex1res = 1; 
    uniform sampler2D tex1Albedo; 

    void fragment() {
		 
		ALBEDO =  texture(tex1Albedo, UV * tex1res).rgb; 
    }

```

**Comment by DevMagicLord** [comment]
I know it works in previous Godot version.

I am just reporting the bug, because i expect 3.1 to get shaders code working back as expected.

**Comment by Chaosus** [comment]
It actually works in 3.0.6 and 3.1, that why I ask you to check

**Comment by DevMagicLord** [comment]
Sorry i'm using Godot 3.1 alpha 1.
I forgot the ".1"

**Comment by Chaosus** [comment]
Can you upload an example project ?

**Comment by DevMagicLord** [comment]
The shader is finally working on another test scene.

The issues is Gi Probe that lightens too much some models when it's activated.
I changed the issue title.

**Comment by Chaosus** [comment]
> https://github.com/DevMagicLord/Godot3/blob/master/bugs/download/shaderbug.zip

404, if your repo is closed then attach zip directly to message
