### ISSUE TITLE
Sound pitch keeping the original tempo (speed)

### ISSUE THREAD

**Issue by sethy** [godotengine/godot#2215]
Hi,
I'm trying to create a little music tracker in godot (just for fun) to create music using modern tools and touch inputs. I notice the the pitch method stretch the audio (speed) without keepeing the tempo. I found a nice opensource library that does it http://www.surina.net/soundtouch/ .Would be a nice add-on on godot.

**Comment by reduz** [comment]
this kind of algorithms (WSOLA) are very heavy on CPU, so they are not
really suitable for real time. Also, the license is LGPL so it's
incompatible with Godot

**Comment by sethy** [comment]
oh Ok. 
What about the Fourier Transform?
https://sites.google.com/site/mikescoderama/pitch-shifting
Thanks

**Comment by sethy** [comment]
other source:
http://blogs.zynaptiq.com/bernsee/pitch-shifting-using-the-ft/
realtime flash example:
http://iq12.com/old_blog/2009/08/25/real-time-pitch-shifting/

**Comment by reduz** [comment]
That is even worse and not generaly as good sounding as wsola

**Comment by sethy** [comment]
Oh gosh! all my dreams about sound manipulation washed away :(   Bu tUnity in the last version introduced a new sound system that handle pitch shifting without changing the speed, I didn't tried on mobile yet but I think will work. What kind of algorithm they use??? ...black magic :)

**Comment by reduz** [comment]
They probably licensed a library like elastique, but those still use a lot
of cpu and are not meant for many being used at the same time

**Comment by vichug** [comment]
However, i would argue that a better support for real time sound
manipulation would be very cool in Godot. Wouldn't platforms like Faust or
PureData or SuperCollider be implementable ? they are all open source, and
i know that the faust license at least is very permissive (maybe the other
one are all as well - but the faust one is designed to be as permissisve as
possible)
I agree that some real time audio algorithms are heavy on cpu, but
depending on the context it's a sacrifice someone might be willing to make
inside a game.

2015-06-30 1:36 GMT+02:00 Juan Linietsky <notifications@github.com>:

> They probably licensed a library like elastique, but those still use a lot
> of cpu and are not meant for many being used at the same time

**Comment by freemanfromgodotengine** [comment]
Yes, PureData or SuperCollider would be great.

@pitch shifting with time stretching.
Reduz, what do you thing about that: 
https://github.com/mikolalysenko/pitch-shift ?
It's MIT and should sound quite all right for sany tasks.

Also, what about http://audiokit.io/ ? It's offered under MIT. They are focused on OSX nad iOS right now, but still maybe it could be used to add more functionality to Godot?

**Comment by reduz** [comment]
2.1 will have audio system rewritten

**Comment by neikeq** [comment]
As discussed on IRC, the audio system re-write have been moved to the 2.2 milestone.

**Comment by freemanfromgodotengine** [comment]
@reduz , when working on 2.2 please check my find: [A Collection of Useful C++ Classes for Digital Signal Processing](https://github.com/vinniefalco/DSPFilters) It's under the MIT License, so I guess could be used in Godot.

I put the information here, because the author writes:

> An accompanying demonstration program...  exercises all the **functionality of the library**, including these features:
> 
> 
> -     Dynamic interface creates itself using filter introspection capabilities
> -     Audio playback with real time application of a selected filter
> -     **Live time stretching** and **amplitude modulation** without clicks or popping
> -     Charts to show magnitude, phase response and pole/zero placement
> -     Thread safety "best practices" for audio applications

but all the filters galore it bring would be helpful in Godot as well.

**Comment by bojidar-bg** [comment]
Would be actually done in 3.0/3.1 (as 2.2 was skipped), sorry for moving it yet again.

**Comment by reduz** [comment]
This is actually implemented now in 3.0, have fun

**Comment by buscon** [comment]
can you explain how is this now implemented in Supercollider?
