### ISSUE TITLE
Problems with inner classes...

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#22158]
**Godot version:**
3.0.3

**OS/device including version:**
Windows 7 64 bit
Radeon 6630M

**Issue description:**
I am having a problem porting code from Python. It has several inner classes. 

Godot borks at the Edge/QuadEdge (moving them around only changes the spot where the problem happens). It seems I can't use a class which is further down the file, at all.

For reference, with Python bindings the Python version works perfectly.

**Steps to reproduce:**
Try to run the attached project, observe an error.

**Minimal reproduction project:**
[Voronoi-test.zip](https://github.com/godotengine/godot/files/2386714/Voronoi-test.zip)

**Comment by akien-mga** [comment]
CC @vnen

**Comment by vnen** [comment]
> It seems I can't use a class which is further down the file, at all.

This is a known bug, it should be already solved in the current `master`.

**Comment by Zireael07** [comment]
Ah ok, closing then.
