### ISSUE TITLE
[Plugin] There is no way to open a script in the script editor via code

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#22166]
**Godot version:**
3.0 and master

**Issue description:**
There are already methods to get the script editor's opened scripts and signals for when the opened script changes, but there is no way to open an existing GDScript file in the script editor via a plugin.

**Comment by PetePete1984** [comment]
The ToDo list addon used to do this in Godot 2, by using `edit_resource(load(resource_path))` - is that not available anymore?

**Comment by char0xff** [comment]
@PetePete1984 Yes, it does work, thank you.
All the _EditorPlugin_ related features are quite undocumented, so sometimes I don't find what I'm looking for.
