### ISSUE TITLE
Editor 2D Button Inspector: Pressed cannot be checked unless Toggle Mode is checked as well

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22169]
**Godot version:**
3.1 Alpha
Mac OS X, High Sierra

**Issue description:**
Editor Button Inspector: Pressed cannot be checked unless Toggle Mode is checked as well.

**Steps to reproduce:**
Add a Button to the 2D Scene
On Inspector check Pressed. Does not allow
Check Toggle Mode. Try again check Pressed. Now allows.
Uncheck Toggle Mode. Pressed remains checked. If you uncheck it  you cannot recheck it.

![pressedbug 2018-09-16 17_27_01](https://user-images.githubusercontent.com/930478/45601144-259d3600-b9d6-11e8-93ae-a729029eeae5.gif)

**Comment by vnen** [comment]
This is intended. `pressed` only makes sense if it's a toggle button.

**Comment by groud** [comment]
Yeah, this is intended. A button can only stay in the pressed state if the toggle mode is activated.

**Comment by wyattbiker** [comment]
So, when you uncheck Toggle Mode, you should also uncheck Pressed.

**Comment by groud** [comment]
> So, when you uncheck Toggle Mode, you should also uncheck Pressed.

Makes sense
