### ISSUE TITLE
get_contact_local_position() wrong direction [with bullet physics, work normally with GodotPhysics]

### ISSUE THREAD

**Issue by Asoth** [godotengine/godot#22167]
**Godot version: 3.06**
**windows 10:**
**Issue description:**
hello hello,
get_contact_local_position(0) report a vector that sound to be the opposite of expected
work around is easy -> contact_point = - get_contact_local_position(0) 
**Steps to reproduce:**
create 2 rigidbodies with collision shape (make collision shape visible)
make one fall on the other
print or draw the result of  : s.get_contact_local_position(0)
do this with bullet physics and godot physics engine

I wish I could put an explicit gif of the issue but that's not really easy for me now.
cheers

**Comment by AndreaCatania** [comment]
Please next time update a sample project because I can't reproduce it.

Anyway this should fix the problem: #22257

Thanks you for the report
