### ISSUE TITLE
Condition ' ofs >= p_packet_len ' is true

### ISSUE THREAD

**Issue by Flairieve** [godotengine/godot#22175]
**Godot version:**

v3.0.6

**OS/device including version:**

OS: Windows 10
Graphics Card: Nvidia GTX 750 TI

**Issue description:**

```
0:04:13:0143 - Condition ' ofs >= p_packet_len ' is true.
----------
Type:Error
Description: 
Time: 0:04:13:0143
C Error: Condition ' ofs >= p_packet_len ' is true.
C Source: scene/main/scene_tree.cpp:1952
C Function: _network_process_packet
```

This error randomly appeared when I was working on my multiplayer game. After a few times running my game without making any changes to my code, the error stopped appearing and my game was working again.

**Steps to reproduce:**

1. Make a multiplayer game in Godot!
2. Error randomly appears?

**Comment by Flairieve** [comment]
There was no in-game errors but multiplayer wasn't working when the error was happening.

**Comment by akien-mga** [comment]
Is this still reproducible in the current 3.2 builds?

There's not much information to go by in this report, so I'm not sure what we can do to debug further.

**Comment by Faless** [comment]
I haven't seen anything like this in a long time. Closing as we can't really investigate further, and no other user seems affected.
