### ISSUE TITLE
PhysicsShapeQueryParameters.sphere_cast

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2217]
([forum discussion](http://www.godotengine.org/forum/viewtopic.php?t=2175&p=10282))

[Unity's SphereCast](http://docs.unity3d.com/ScriptReference/Physics.SphereCast.html) is quite an elementary and useful function.

To be fair, it seems it seems (I'm not sure though) is somehow possible to achieve a similar thing using the current API, but it is overly complicated and half of it isn't even documented. 

Please add a similar high-level function to godot.

**Comment by reduz** [comment]
It is possible and you can cast any shape, not just spheres using
directspacestate

**Comment by seadra** [comment]
Well, as I mentioned, 1) [the documentation is non-existent](https://github.com/okamstudio/godot/wiki/class_physicsdirectspacestate) so nobody except you knows how to do that exactly, 2) SphereCast is enough for many use cases and a nice high-level API function

**Comment by reduz** [comment]
Feel free to contribute the doc

**Comment by reduz** [comment]
You can ask for docs, ask how it works, ask for help if it doesnt work or
contribute yourself. Complaining will get you nowhere

**Comment by seadra** [comment]
Uh-oh. Sorry, but I'm not to complaining. I was requesting a feature, along with the reason why I think it is a necessary feature.

How can I contribute to doc if I don't know how it works?
Also, I would have contributed if I knew how it worked and if there was a way for ordinary users to contribute docs. I guess this system is still in the works, along with the new website.

In any case, I'm speaking/making requests from a practical point of view. I am using Unity, and now that it's coming to Linux, I am 100% happy with it (especially since I have paid the license fee). There is no practical incentive for me use godot, or get some feature implemented.
But still, I wish to see godoc succeed and I wish to use it for real work because godot is the only free engine. That's all this is about.

**Comment by reduz** [comment]
well, if you are not using something, you have no incentive to know how
something works, which explains your attitude :) Documenting functions is
really easy, just a PR on classes.xml file.

If you want to see Godot succeed, the best you can do is contribute to it,
even with feedback from a user perspective, but your current way of just
requesting stuff for the sake of it is not useful, sorry

**Comment by seadra** [comment]
I surely would have done it had I know how it worked.
But I think I can send PR for some other functions. Are these changes automatically reflected in the wiki? 

OK, so you don't think having a few higher-level functions such as SphereCast would be better, like, at all?

**Comment by reduz** [comment]
there are high level functions like that, in fact for 2D there is
test-motion which is very similar (and needs to be ported to 3D)
also yes, changes to classes.xml are automatically reflected in the wiki
and the built-in help

**Comment by seadra** [comment]
Thanks! I will definitely contribute to the documentation (as long as I know what I'm writing about).

So, for now, they way to do a SphereCast is like this, right? 
```gdscript
var shape = CapsuleShape()
shape.set_radius(2)
shape.set_height(0)

var params = PhysicsShapeQueryParameters()
params.set_shape(shape)
params.set_motion(Vector3(0,-5,0))
# param.set_exclude(???) # exclude self somehow
var res = PhysicsServer.intersect_shape(params, 1)
var normal = res["normal"]
```
I'm not sure about set_motion (is it the sweep distance?) and set_exclude (do we pass an array of objects/RIDs?) though; do you remember what they do?

**Comment by seadra** [comment]
What does `PhysicsServer.cast_motion` do?
I tried to check the [C++ code](https://github.com/okamstudio/godot/blob/89300b70e7217feaf0be15cfe395763f555bbafa/servers/physics/space_sw.cpp#L195), but I'm not sure what it is.

**Comment by reduz** [comment]
to get the same functionality in Godot as the one you mentioned in Unity,
you have to combine cast_motion with rest_info.
cast motion will return two values, the safe and the unsafe distance you
can advance in a given motion vector (safe warrants non collision and
unsafe warrants collision). If you get a collision, you can then call
rest_info with the unsafe advance to obtain collision point, normal,
collider, etc.

**Comment by seadra** [comment]
I've been tinkering about that. Would it work it I used a CapsuleShape rather than a SphereShape and set its height to max_distance?

BTW I suppose I shouldn't call set_motion (no such function exist for PhysicsShapeQueryParameters). And I think the line `params.set_transform(get_transform().translated(origin))` is definitely wrong; it should be a transformation that corresponds to the same position as the main body, but looking at to `direction` with something like this?

```gdscript
get_transform.looking_at(direction, Vector3(1,0,0)) # up shouldn't matter since capsule is axially symmetric
```

**Comment by seadra** [comment]
OK, after several hours trying to figure this out, I give up.

Could you write a SphereCast polyfill?

**Comment by seadra** [comment]
Pretty please?

**Comment by seadra** [comment]
I'm pushing it now, but well, hope springs eternal :)

**Comment by seadra** [comment]
Nobody (other than you) knows how to do it in godot (assuming that it can be done).

**Comment by reduz** [comment]
just leave this issue open and will eventually fix/add this

**Comment by bitbutter** [comment]
New Godot user here. I've been looking for how to do the equivalent of unity's spherecast too. Ideally returning collision point(s) and normal(s). It'd be great if there was a convenient method for this.

**Comment by CptPotato** [comment]
This is currently preventing me from implementing my 3D character properly. Any developments on this would be great, as I agree that it's quite an essential feature.

**Comment by Xrayez** [comment]
I think the API should more or less closely represent `RayCast(2D)` one (I envision this to be a node am I right?). See also godotengine/godot-proposals#72. As reduz suggested it doesn't have to be restricted to one particular shape type either, just assigning any shape via inspector or code should be enough.

This feature seems to be useful for people working on 3D projects. I only use 2D-related physics queries though. The proposal/issue is 5 years old so I might as well experiment with this? If I do end up implementing this for 2D specifically, I'm locked by the 3D side to be able to contribute, but might be easier done than said. 🙂

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Zireael07** [comment]
Can this please get documented somewhere?

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/pull/54803, which implements this feature in 2D.
