### ISSUE TITLE
-colonly and -colonly Meshes don't collide to each other in rig body 

### ISSUE THREAD

**Issue by bosman697** [godotengine/godot#22189]
**Godot version:**
Godot_v3.0.6-stable_win64

When 2 object have custom collision - colonly  they don't collide to each other, but when 1 object don't have custom collistion they collide 
Screen from blender I use Better colada exporter
http://oi63.tinypic.com/200xr42.jpg
Video to see the problem 
https://youtu.be/igiDPccVPu4

**Comment by Zireael07** [comment]
I think -colonly creates trimesh collisions and trimesh/trimesh don't collide?

**Comment by bosman697** [comment]
Indeed trimesh/trimesh don't collide so what to do to ?
What is the purpose of the trimesh collision.

**Comment by pouleyKetchoupp** [comment]
As documented, trimesh collision should be used for static objects only (StaticBody), while other types can be used for dynamic objects (RigidBody) to collide with other dynamic objects and static objects.

Closing.
