### ISSUE TITLE
LOD for 3D models

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#22183]
Hi,

For 3D PC games, LOD is a fundamental feature.
Godot should have one, with easy distances slider settings.

Something like this ? 
https://docs.unity3d.com/uploads/Main/InspectorLODGroup.png

**Comment by MysteryGM** [comment]
Hi, I am not a developer.

It looks like Godot has a LOD system planed but just never got around to implementing it: https://github.com/godotengine/godot/issues/6375

I have tried using the LOD system and it doesn't work. Many of the 3D parts is still incomplete.

**Comment by ZX-WT** [comment]
the old one in 2.1 used to work but it is not working after 3.0, I think #6375 addressed the issue already.

**Comment by pgruenbacher** [comment]
This is a duplicate issue. I'd just recommend tracking https://github.com/godotengine/godot/issues/6375
and https://github.com/godotengine/godot/pull/20489

**Comment by Chaosus** [comment]
Thanks, closed as duplicate.
