### ISSUE TITLE
Left shift of the control's position on the fly

### ISSUE THREAD

**Issue by r3d9u11** [godotengine/godot#22180]
**Godot version:**
3.0.5

**OS/device including version:**
Linux Mint 19 x64

**Issue description:**
Label goes beyond the right border

Original label:
![1](https://user-images.githubusercontent.com/15020827/45621925-e4b32900-ba8a-11e8-9d4e-56087f9cced9.png)

Changed at runtime:
![2](https://user-images.githubusercontent.com/15020827/45621926-e7ae1980-ba8a-11e8-964c-ede5ca68de3b.png)

Layout: Bottom Right.

How to shift Label's position to the left automatically?
Thanks.

**Comment by Calinou** [comment]
You can align a label to the right by setting the **Align** property to Right. (The same can be achieved with RichTextLabel by enclosing the text in `[right]…[/right`.)

**Comment by r3d9u11** [comment]
@Calinou well, as I understand, I should use fixed width of label and also set Align to Right?
