### ISSUE TITLE
Tool access to object's property list

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#2218]
Right now tools have a limited access to the editor (or at least the documentation isn't really descriptive about what you can do). Exports also provide a limited ability to expose functionality to the artists, so I thought what could we do to extend this in some way.

I guess the easiest way to do this would be to expose the property list directly to a script. That way programmers could create GUI elements as they please, and then retrieve the values. The only issue would be saving the property values of custom elements in a scene file - export/import callbacks maybe?

A trivial example:
I'd like to allow my artist to select properties from a set of checkboxes. I will need:
- Access to a GUI field where I could insert the checkboxes and a layout
- A way to tell Godot what is the value of my GUI fields for saving (serialization)
- A way for Godot to tell me what value is stored in a scene when loading, to properly setup the checkboxes (deserialization)

So I think simple callbacks for scripts could be easiest to integrate with the current state of things.
```
export(func, int, "_myGUISetup", "_mySerializer", "_myDeserializer") var MyPropertyBox;

func _myGUISetup(parent):
    pass # Put a layout inside of the parent, put checkboxes inside of the layout

func _mySerializer(parent):
    pass # Read checkbox state and return an int value (defined in export) representing the state of the proprty, called on scene save

func _myDeserializer(parent, serializedState):
    pass # Called after _myGUISetup with serializedState if a value is saved in a scene
```

Things to think about:
- Could animations be used with this? (I guess it depends on the implementation specifics)
- Could plugins be used with this? (defining function names in the export might be a bad idea, maybe plugins could define a custom type for the export name `export("pluginCustomField") var MyPluginProperty`)

Use examples:
- Countless really, depends on needs
- A field allowing selection of an interpolation function with factor selection and an image rendering a plot of it
- GDScript implementation of arrays of properties (Unity property lists equivalent)
- Selection of a postprocessing filter to use with a preview
- A field for file selection with a button
- Diagnostic read-only fields showing some properties like distance to the end of a map or anything else requiring runtime calculations in the scene

**Comment by reduz** [comment]
will soon be working on having better documentation on tools and how to
access the editor from it.

for a more complex serialize/deserialize behavior you can simply export a
single property and give it/take a dictionary

var mydata setget deserialize,serialize

func serialize():
   return {} # return your data in a dict

func deserialize(data):
   #get your serialized data back

**Comment by WalasPrime** [comment]
Right, so the export() could use a setget instead of directly pointing to the function name, and it would have to be required for it to work.
```
export(func, dict, _myGUIBuilder) var MyProperty setget deserialize,serialize
```
Still, even to manipulate the dictionary the GUI elements would be needed
Hopefuly the tools will allow this to happen. Will wait for documentation, then further feedback will be given.

**Comment by reduz** [comment]
to create custom editors, the EditorPlugin helper must be used , but this
is still not complete and documented, some guys were trying out stuff and
returned a lot of feedback (the current API is more like a prototype API
than anything else), so I hope to roll out docs for this in the next weeks

**Comment by akien-mga** [comment]
Is this still valid now that there is a new EditorPlugin API in the 2.1?

**Comment by WalasPrime** [comment]
I'm pretty sure this can be achieved with a 2.1 plugin, further study may at most reveal suggestions towards the new EditorPlugin interface. Thanks for the great work on this!
