### ISSUE TITLE
World Environement Canvas Glow doesn't work in WebGL 2

### ISSUE THREAD

**Issue by Nobelix** [godotengine/godot#22192]
**Godot version:**
3.1-aplha1

**OS/device including version:**
Ubuntu 18.04 - Latest Nvidia Drivers
Firefox

**Issue description:**
When having a world environment with glow enabled for 2D (canvas), the glow is not present in the HTML5 export. 

**Steps to reproduce:**
Set up some 2D scene with glow and export it to HTML5/WASM

**Comment by clayjohn** [comment]
The webgl2 backend is being abandoned, so the current best option is to use GLES2/WebGL1 and Glow works fine there. If your project is having issues with webgl2, try GLES2
