### ISSUE TITLE
Editor Script: Autocomplete does not allow scrolling list with mousewheel. 

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22196]
**Godot version:**
3.1 alpha
Mac OS X, High Sierra

**Issue description:**
Editor Script: Autocomplete does scroll long options list with mouse wheel.  Must use arrow keys. 

**Steps to reproduce:**
in a script function type `Control.` and you will see the list of class options after the ".". Scrolling with mouse wheel is not available, neither is a scrollbar.

**Comment by akien-mga** [comment]
Would likely be fixed by #21181.

**Comment by KoBeWi** [comment]
Is this system specific issue? I can't reproduce it on Windows in any version.
