### ISSUE TITLE
The unused class variable warning appears even if variable used through autoload

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#22206]
**Godot version:**
3.1

**Issue description:**
I think its not correct to warn user if autoload variable used by other scripts

![image](https://user-images.githubusercontent.com/3036176/45670663-103a2000-bb2c-11e8-8058-c91968c4d97f.png)

**Minimal reproduction project:**
[WarningBug.zip](https://github.com/godotengine/godot/files/2391576/WarningBug.zip)

**Comment by vnen** [comment]
This is not a bug. The warning is about "not used in the _script_". Usage in other scripts are not considered.

**Comment by Chaosus** [comment]
So I need to supress that warning in every autoload ?

**Comment by vnen** [comment]
> So I need to supress that warning in every autoload ?

Yes, or disable the "Unused class variable" warning.

**Comment by Chaosus** [comment]
Ok.. thanks

**Comment by vnen** [comment]
To clarify, there's no way to know if a class variable is used in other scripts, unless we scan every script in the project, which is inefficient. That's one reason I opened #19811.
