### ISSUE TITLE
AnimationPlayer keyframing is not working.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22208]
**v3.1 alpha e10ca7b82**

There is some difficulty describing what is happening so I made video.

Mainly creating keyframes on new animations doesn't show the new keyframes.  Sometimes they seem to be there,

and only appear when selecting the node.  Other times, doing things in a certain order, they aren't ever created.

![ezgif com-optimize](https://user-images.githubusercontent.com/13004169/45675289-b8091b00-bb37-11e8-920c-d5cd6555c14f.gif)

**Comment by DualMatrix** [comment]
Hmm... I couldn't reproduce this in master 1b63dd8.

**Comment by avencherus** [comment]
Appreciate the verification.  And yeah, I was doing some AnimationPlayer related things today, and thankfully I haven't been noticing it either.  Wonder what happened in the meanwhile?

I think for curiosity sake, I'm going to go kick off a rebuild of that commit and see if maybe I did a bad build a week ago.

Closing, unless otherwise it returns.

**Comment by avencherus** [comment]
Looking like 100% an error on my part with the build.  I rebuilt that commit and compared it to my archived version.  The newly built editor with this commit is fine, my old build is not.  It was very likely just a rookie git mistake on my part, and left someone's feature branch in it.
