### ISSUE TITLE
AnimationPlayer animation changed signal only fires for queued animations.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22209]
**v3.1 alpha e10ca7b82**

Not a lot to describe on this issue, the `animation_changed` signal is not doing anything.

Example project: 
[3.1 Anim Change Signal.zip](https://github.com/godotengine/godot/files/2391875/3.1.Anim.Change.Signal.zip)

**Comment by DualMatrix** [comment]
Signal worked fine for me in 2c79087. It's quirky though since it only triggers when an animation ends while another is queued up. But I think that's intended behaviour.

**Comment by DualMatrix** [comment]
So does anyone know if this is an actual bug or if it's intended?

**Comment by williamd1k0** [comment]
Duplicate of #20274

**Comment by avencherus** [comment]
I would venture that maybe it was intended, but isn't terribly intuitive given the name.

@williamd1k0 Thanks, I will close this one.
