### ISSUE TITLE
GDScript warning levels

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#22202]
This is a proposal (and mostly a reminder for myself) to add levels to the GDScript warnings. The idea is to be able to have a decent amount of warnings enabled by default and others turned off. Considering the amount of users that feel that some warnings are "too much", we could disable some in the default level.

Currently it's already possible to enable/disable specific warnings, but having default levels might be easier for users to change between the amount of warnings they desire without picking one by one. They can also serve as rough guidelines.

This also makes simpler to add as much warning types as possible without impacting users too much.

I'm accepting proposals to which levels should exist (probably 3 or 4) and what warnings would go to each level.

**Comment by vnen** [comment]
Maybe I wasn't clear what I meant by "levels" (I guess not everyone is familiar with compiler language). Warning levels are essentially a priority categorization. For instance, see [MS compiler options](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=vs-2017#remarks),

As an example: (each level includes all of its predecessors)
- Level 0: No warnings.
- Level 1: Most important warnings.
- Level 2: Significant warnings.
- Level 3: Minor warnings.
- Level 4: All warnings.

The idea is that you can just pick-up your preference (say "I want all warnings" or "I want only the most important") and it enables/disables everything based on this preference, which can also be overridden with custom picks. So we can have, say, level 2 by default and most people will be fine, while people who prefer less or more warnings can customize.

**Comment by LikeLakers2** [comment]
Yeah, I understood what you meant from the get-go. I still don't think levels are a good idea, because how do you define what's more important than everything else? Inevitably, a developer is going to disagree.

**Comment by LikeLakers2** [comment]
Yeah, I think I understood what you meant from the get-go.

Personally, I still don't know what to think about warning levels in the context of GDScript warnings. Warning levels are typically used in situations where you would be *logging*, where you would want more or less info being printed out in a given moment. In contrast, I feel the GDScript warning system feels more like a set of notifications, where you would want to customize the types of notifications you get.

I don't want to sound like I'm bashing on warning levels. But I'm not sure I'm convinced it's the right idea. Maybe they could be used as templates or presets?

Yet, when I think about warning levels like they're being suggested here, my mind thinks that the user will more likely want to customize the types of warnings they get, like notifications. It feels an awful lot like, if they're not disabling a specific warning, they might want to disable a specific category of warning entirely, more than they might want to say "I don't want minor warnings anymore". But that's just my thoughts, and I might be wrong.

**Comment by akien-mga** [comment]
> Personally, I still don't know what to think about warning levels in the context of GDScript warnings. Warning levels are typically used in situations where you would be logging, where you would want more or less info being printed out in a given moment.

That would be logging levels :)

Compiler warning levels are well established and implemented in all compilers, so it makes sense to add them for GDScript warnings. It's not about increase/decreasing verbosity, it's about the order of priority in which warnings have to be handled, if any. Having presets defined by language designers is useful, as not all users will be familiar enough with GDScript to know which warnings are hinting at a bug in their code, and which warnings are just cosmetic.

I'd go with levels similar to what @vnen suggests, with "1" being warnings which almost certainly point at a bug in the code. I don't know if we need all 4 levels or if 3 can be merged into "All warnings", it will mostly depend on how we plan to actually categorize them.

We can check GCC, Clang and MSVC default warning pools to have ideas on how to order ours.

**Comment by vnen** [comment]
> Yeah, I think I understood what you meant from the get-go, hence why I asked "How would you go about determining what errors would be higher priority than others?"

Sorry, I misunderstood the post. When I think of this, it's not a comparison between warnings, so there's not really a "this is more important than that one". Each warning is evaluated by its own merit. For instance, "unreachable code" is likely to be bug in the code, so it fits the "most important" category, independent of how any other warning is classified.

> It feels an awful lot like, if they're not disabling a specific warning, they might want to disable a specific category of warning entirely, more than they might want to say "I don't want minor warnings anymore". 

I feel it's the opposite. I see no reason to want _all_ variable warnings but _none_ of the function warnings. Also, I'm not even sure how to make the categories (there'll likely be a lot of overlap). For levels, I would classify as: 1) Likely a script bug, 2) maybe a script bug, and 3) likely not a script bug (possibly an extra level for the experimental ones).

Also, compilers use levels, not categories, and I'm not feeling like experimenting here, I would go with an established approach.

> it will mostly depend on how we plan to actually categorize them.

I'm naturally open to suggestions.

----

My idea is to disable more warnings by default than the current setting, while allowing users to easily increase or decrease the "nitpicking" level without having to tick a bunch of checkboxes.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
