### ISSUE TITLE
panel instance hidden state not saved

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#2221]
Create a scene with a Panel as its root, and hide the Panel.  Instance that scene into another scene.  Unhide the instance, save, and close editor.  Reopen, and the instance is hidden again.

Example:
https://copy.com/mw0c8PXITNGOCere

**Comment by akien-mga** [comment]
I believe this was a normal behaviour as subscene customisation was not supported back then? It should now work fine in the current master branch.
