### ISSUE TITLE
AnimationPlayer in tool script generates an error for current position.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22211]
**v3.1 alpha e10ca7b82**

When having a tool script that looks at the current animation position, I have found that it will create errors until the AnimationPlayer is either selected, or an animation is played or scrubbed.  It seems like it doesn't set its current animation in the editor, until done manually?

It may be functioning as intended, but I couldn't find any way to detect this state to prevent or flag to not call on it until its set, because `current_animation` seems to always be empty in tool script.

Example project:
[3.1 Tool Anim Error.zip](https://github.com/godotengine/godot/files/2391887/3.1.Tool.Anim.Error.zip)

**Comment by avencherus** [comment]
Considering closing this.  Not sure if this is actually an issue.  Seems to be the same thing for accessing current animation length.

While `current_animation` is always empty, I did find that tool script can use `assigned_animation == ""` to prevent calling on these properties.

**Comment by KoBeWi** [comment]
Yeah, this is not a bug. The method expects a **playing** animation (playback), which doesn't exist until the animation is played.
