### ISSUE TITLE
Gi probe grid displays on top of everything

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#22212]
Godot 3.1 alpha 1 
Win 7 64 bits

Gi probe grid displays on top of everything when selected.

**Comment by reduz** [comment]
You can change the visibility option of this in the view menu, not quite
sure if the option made it into alpha, though.

**Comment by DevMagicLord** [comment]
Right.
There is 3 states.
- Display correctly
- hide 
- display grid on to top everything (the default one) 

I think the last mode is useless, and should not be the one by default.

**Comment by DevMagicLord** [comment]
Most of the time i choose to hide the GI probe Grid, but i would like to keep Gi probe lighting the level in the editor.

Would this be possible ?
