### ISSUE TITLE
Area2D Reports Incorrect Collision Information Immediate After Calling set_pos()

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#2222]
In a function if you move an Area2D via set_pos() then call get_overlapping_areas(), Godot will report the collision iteration from the previous iteration, not the current information.

I've created an example that demonstrates this behavior at http://home.comcast.net/~hammerbro/CollisionExample.zip

If you press Left, the two Area2Ds will move to the opposite ends of the screen. If you press Right, they will move to an overlapping position in the center. If you press Space Bar, the current collision information will be printed.

When you first press Right, the Area2Ds will overlap, but within that same function call they will report that they are not overlapping. If you press Space after that they will then report that they do overlap, even though they haven't moved. When you next press Left, they will report that they do overlap, even though they're no longer close to each other. Again, Space will report accurate information, but only because some number of game loops have passed since they were moved.

**Comment by reduz** [comment]
yes, this is not immediate. All the physics/collision logic is computed in
a separate thread so this information is updated after fixed_process .

Do you really need to check this manually though? Area has signals to let
you know when something entered/exited overlap, it's rare and generally not
needed that you want to check colisions manually, as it's a lot less
efficient

**Comment by Gastronok** [comment]
I do want the ability to create my own physics engine in GDScript -- too many game engines these days are tightly coupled with their physics engines, and it introduces a subtle homogeneity that I find distasteful. To do so, I need the ability to detect and handle collisions myself. Plus the more general-purpose functionality Godot has, the more varied the games people can create.

That being said, it does seem like signals do what I'd expect them to do in this little demo, so it's possible that my immediate plans can be accomplished that way. I'd still consider this a minor bug, though perhaps it's only noticed by people with unusual inclinations (do the physics themselves). I can also understand if it's inextricably linked to the physics engine; I've been messing around with the source code trying to create some kind of force_physics_update() function, but with little success so far.

I'd say if it's not reasonable to adjust this behavior, that at least some kind of footnote should be added warning others that certain function calls may be an iteration behind.

**Comment by akien-mga** [comment]
You could set ```physicsJustChanged = false``` at the start of _fixed_process(), and then each time you move around something that would impact physics, set it to true and do _not_ try to use physics-dependent features while it's true. It will then be set to false in the following frame and you can then check for collisions...

I'm not sure if you could get something better without completly changing the way the collision logic works.

**Comment by reduz** [comment]
if you want to handle your own collisions, check the Shape2D API, it has a lot of useful methods for dealing with collision detection yourself
