### ISSUE TITLE
IMPORT:: New meshes introduced into scene lose their name

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#2223]
To test...

----------------------------
1. Export an initial set of meshes to Collada and import into Godot
2. Introduce a new set of meshes to the scene's Collada file
3. Re-import the scene using the *merge with new* option

The result:: the initial set of meshes should have their names assigned to their nodes, but all future objects will simply be called **mesh instance** with a number by them. I'm pretty sure this may be on Godot's end but I'm not sure.

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by Ace-Dragon** [comment]
Akien; the issue is still there in the Win64 Godot build done on October 30 (from the official website).

**Comment by reduz** [comment]
merge reimport will be eventually discarded in 2.1, as doing this with the new scene inheritance feature makes a lot more sense

**Comment by neikeq** [comment]
What's the progress on this? Some changes to re-import were introduced recently.

**Comment by reduz** [comment]
merge reimport now keeps materials and animations, meshes are overriden
