### ISSUE TITLE
Make exported games use system-provided certificates for TLS

### ISSUE THREAD

**Issue by uldall** [godotengine/godot#22232]
Exported games do not currently support the use of root certificates provided by the OS when establishing SSL/TLS connections.

Adding this support would provide the following benefits:
- Increase security as most OS maintainers put effort into maintaining a trustworthy root certificate list.
- Old games, that are no longer maintained, will not stop working because of an expired root certificate.
- Easier use of SSL/TLS for new Godot users as they will not be forced to mess with setting up the root certificate list.

**Comment by akien-mga** [comment]
Assigning to 3.2 milestone for now, as I think it's a very important feature to implement. Not promising anything though as currently we have no plan/leads on how to do that properly in a cross-platform manner.

**Comment by Calinou** [comment]
Are system certificates planned to be used by the editor as well?

**Comment by akien-mga** [comment]
Yes if we implement support for system certs in the runtime, we'll use it for the editor too.

**Comment by cunyx** [comment]
With version 3.1.1 and build options "builtin_certs=no" and
"system_certs_path=/path/to/distro/certs/bundle.pem" appeared an error in
the editor with a loaded project like
"Error parsing some certificates
modules/mbedtls/stream_peer_mbed_tls.cpp:343 @ _load_certs()".

Patch at
https://build.opensuse.org/package/view_file/games/godot/project_certs_fallback.patch
seems to prevent this error (message) in downstream builds.

This does not solve the whole issue but might address one aspect of it,
at least for a few packagers.

What do the experts think?

Might it be of interest to upstream?

**Comment by Faless** [comment]
Discussion moved to the proposal repository: godotengine/godot-proposals#2970
