### ISSUE TITLE
Wrong position of close popup after minimizing Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22237]
**Godot version:**
3.1 a4e4dd3

**OS/device including version:**
Windows 10

**Issue description:**
After minimizing Godot, and trying to close it, close popup shown at upper left corner instead a center of Godot.

**Steps to reproduce:**
![ezgif-1-2dd37abc87](https://user-images.githubusercontent.com/41945903/45735536-75534b80-bbe8-11e8-9463-53c9bce7269a.gif)

**Comment by marcelofg55** [comment]
This should be fixed by #24078, if you can please test it again with latest master. Thanks!

**Comment by akien-mga** [comment]
Closing as fixed by #24078 so that we don't forget, but please comment to confirm that it does work as expected. If not, we can reopen the issue.

**Comment by qarmin** [comment]
It is fixed, now close window appear at the center of Godot
