### ISSUE TITLE
AnimationNodeOneShot doesn't trigger in runtime

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22236]
**Godot version:**
`master` / f148e8e

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
When setting up an `AnimationTree` with an `AnimationBlendTree` node as its root which contains an `AnimationNodeOneShot` node, it seems that the one short node never triggers when `AnimationTree.Set("parameters/[name of the one shot node]/active", true)` is invoked in runtime.

On the other hand, the animation can be triggered from the editor, but if you click `Active` checkbox from the inspector, it does not reset to the false state as it is the case when you click it on the node itself, making every other click to be ignored (because it's already true).

Not sure if it has anything to do with the runtime behavior, though.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by reduz** [comment]
Nope, tested and it seems to work fine.
