### ISSUE TITLE
Auto restart feature in one-shot animation node does not work

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22238]
**Godot version:**
`master` / f148e8e

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
If I'm not mistaken, setting `auto_restart` parameter to `true` in `AnimationNodeOneShot` should make it trigger the specified animation repeatedly when the `active` parameter is set to `true`.

However, the animation only plays once when manually triggered in editor, regardless the value of  `auto_restart` parameter(I couldn't test in runtime due to #22236).

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?
