### ISSUE TITLE
Visual script : exported release game crash on array append/push front/push back

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#22231]
**Godot version:**
v3.1.dev.calinou.e522baf

**OS/device including version:**
windows 10 x64

**Issue description:**
In visual script: when append any value (ex: vector2D/bool..) to an array variable , the debug (or debug export) doesn't show any error ,but when export as release it crashes.
also tested with push back / push front with the same release crash.
https://drive.google.com/open?id=1JC9xjtnqLmt7KYMFoxwK8OSqZ1rrVD9B

**Steps to produce:**
create visual script >> create function >> create array variable >> drag and drop Array.Append node >> create custom variable (vector2d/bool..) >> link nodes so when call the function it append the vector2d to the array >>export to debug : no error | export to release : it crash

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by fire** [comment]
Do you have a sample project?

**Comment by sami8github** [comment]
[array_run.zip](https://github.com/godotengine/godot/files/2866738/array_run.zip)

Export release will crash
