### ISSUE TITLE
(Better Collada Exporter):: Option for automatic object splitting by material

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#2224]
As the title says. Currently, it seems that Godot does not properly support multi-material objects so we have to split them in Blender before exporting. The issue though is that you have to join them back up if you need to make further edits to the level or object in question.

The solution would be a checkbox in the _Better Collada_ exporter (along with the Godot Export manager) to automatically split objects by material during the export process, which would simplify and speed up level creation. I decided it would be a good time to request that since the focus right now is on usability.

If you can take a look, thanks.

**Comment by reduz** [comment]
I never had any issues with multi material objects. Have a testfile?

**Comment by Ace-Dragon** [comment]
The thing is though is that I often want to use shading options only found in Godot, so I make a basic material for overview in Blender and then use the material override to make a more complete one. This is likely not going to change as long as Blender does not support replacing the current GLSL code with a custom set.

In Godot anyway, I have not found anything in the UI that suggests support for multiple material indices in the same vein as Blender, so that is why I split the objects.

**Comment by marcosbitetti** [comment]
I have same doubts. The export of multiple textures work fine, but to override it on a mesh I need to split it too. Generally it is not a problem, but when I need to rework a character it is a hard work.

**Comment by akien-mga** [comment]
Should this issue be moved to the new repo? https://github.com/godotengine/collada-exporter

**Comment by Calinou** [comment]
As said by @akien-mga, issues specific to export add-ons should be created in the add-on's repository (if they're still relevant today).
