### ISSUE TITLE
Modyfing instance of CollisionShape2D, modify also base CollisionShape2D node.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22248]
**Godot version:**
3.1 a4e4dd3

**Issue description:**
When I create a CollisionShape2D with RectangleShape2D and save this scene and when I use it in other scene, any change of RectangleShape2D in instance, change value in base node.

For me, only changing base node should change instance(only if instance still is untouched), but not vice versa

**Steps to reproduce:**
https://streamable.com/0k66h

**Comment by groud** [comment]
That's an expected behavior, Shapes are resources thus globally shared. 
If you want to modify it locally, you need to mark it as local : 
![2018-09-19-175131_329x376_scrot](https://user-images.githubusercontent.com/6093119/45765246-e28cce00-bc34-11e8-9124-035e0fce32d1.png)
