### ISSUE TITLE
Expression node for visual shaders

### ISSUE THREAD

**Issue by fire** [godotengine/godot#22243]
**Issue description:**

Allow custom shader code inside of the visual shaders.

I made a mockup of what the node will look like.

![chrome_2018-09-19_14-38-17](https://user-images.githubusercontent.com/32321/45783096-ad26b700-bc19-11e8-9ae7-21bd4773ccb1.png)

Edited: mockup

**Comment by CptPotato** [comment]
The inputs could be auto-generated from uniforms in the shader code.

**Comment by fire** [comment]
This is the definition of a function. You mean scan the shader code for variables?

**Comment by CptPotato** [comment]
I meant it like adding something like `uniform vec3 Color = ...;` in the shader code and the node automatically adding an input called `Color` which is passed to the shader.

**Comment by Xrayez** [comment]
I've created a similar `Expression` node my my own noise module in:
 https://github.com/Xrayez/godot-anl/commit/facbbcc59e0666c93b4a7877ec61910491eeb0f6
https://github.com/Xrayez/godot-anl/commit/299bfc61840a6bfec7f711bc8a577f1bdfae941f

I've adapted visual shader codebase to my own needs, some structures share similarities, might be useful...

**Comment by Chaosus** [comment]
I currently began to implement it. Not sure if the resulted form will be the same, but I always trying to achieve the best result. demo screenshot -

![image](https://user-images.githubusercontent.com/3036176/57238236-9b234880-7031-11e9-883f-d293c97bb988.png)
