### ISSUE TITLE
CSGShape use_collision doesn't use collision layers and masks

### ISSUE THREAD

**Issue by YannBurrett** [godotengine/godot#22246]
**Godot version:**
3.1 alpha 1 snapshot

**OS/device including version:**
Windows 10 home 64 bit

**Issue description:**
Using collision on a CSGPolygon does not allow you to switch collision layers or masks in the inspector or in script.

**Comment by akien-mga** [comment]
Confirmed, and it affects all CSGShape-derived nodes. They behave as if they're all on layer/mask 1.

**Comment by rburing** [comment]
This was fixed in https://github.com/godotengine/godot/pull/22973 and it is still fixed in both `3.x` and `master`, so this issue can be closed.
