### ISSUE TITLE
Simple "re-route" node for visual scripting

### ISSUE THREAD

**Issue by zachThePerson** [godotengine/godot#22258]
In almost all other node editing software there is a really helpful node that does literally nothing; It just sits there and acts as a "noodle bender," so the flow of the noodles can be bent around other nodes.

Simple Photoshopped example: https://imgur.com/a/nMS6bvx

It's a really small detail, but I find when it comes to making clean and understandable node trees they are a lifesaver

**Comment by groud** [comment]
Duplicate of #11001
