### ISSUE TITLE
No style for disabled tab

### ISSUE THREAD

**Issue by ykoc** [godotengine/godot#22266]
Version 3.1 (alpha 1, any master builds up to 18.09 )
OS Windows 7

1) (not theming related) Tabs, that were disabled via Tabs.set_tab_disabled have no style by default and are shown as "Error" texture 
Probably, the same is true to tabs from TabContainer

Steps to reproduce

1. create Tabs node
2. add some tabs
3. set some tabs to disabled in script

2) (theming related) Neither Tabs Class Items nor TabContainer has a style for disabled tab. More, TabContainer Class Items styles change appearance of tabs created as Tabs node. And setting Tabs Class Items styles do nothing

**Comment by girng** [comment]
good catch haha. never noticed this either
