### ISSUE TITLE
Need to press F5/F6 twice on 3.x in release_debug

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#22265]
I see this #19576 closed, i open new one because bug not fixed.

**Godot version:**
All 3.x,  master 0de6514

**OS/device including version:**
Xubuntu 16.04.5 LTS, Nvidia GTX 750 Ti
Tested 3.x on Windows 7 on the same machine and it works.
I think is only affected x11.

**Issue description:**
Sometimes need to press F5 or F6 twice to run the project or scene with Godot 3.x.

**Steps to reproduce:**
1) Open scene.
2) Press F6 button and hold it and release after scene is run. 
3) Close windows and press F6.
4) Scene is not play, need press F6 twice.
5) Try several times it's difficult to reproduce.
 
On my machine this happens randomly not necessary to hold F6 button.

**Minimal reproduction project:**
Simple project with one 2DNode for version 3.1.
[f6.zip](https://github.com/godotengine/godot/files/2398814/f6.zip)

After compare 2.1 version with 3.x, i found what cause this behaviour on my machine.
https://github.com/godotengine/godot/blob/e20a28a7db090dbf39bc8c90487c3d7beb84cbb8/main/input_default.cpp#L266-L272

Sometimes keys_pressed.erase not reached, then **last_is_pressed == true**, and **k->set_echo(true)**
Because **BaseButton::_unhandled_input** verify if not **is_echo()**, scene not run, while key not pressed twice.. 
**New code from 3.x:**
https://github.com/godotengine/godot/blob/e20a28a7db090dbf39bc8c90487c3d7beb84cbb8/platform/x11/os_x11.cpp#L1684-L1694

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by allkhor** [comment]
Reproduced on 2d57ec2.
