### ISSUE TITLE
2D Shader does not work when first shader is visible.

### ISSUE THREAD

**Issue by TwistedTwigleg** [godotengine/godot#22264]
**Godot version:**
Godot 3.1 alpha 1

**OS/device including version:**
Windows 10, 8gb ram.
Nvidia GTX 660 Ti 2gb (latest drivers)

**Issue description:**
I made a simple shader that changes a sprite's alpha value to `0` when it is over a certain color, using `SCREEN_TEXTURE` to find the color underneath each pixel.
The shader works great if it is only detecting color on one single area. In the project provided, everything works fine in example 1.

However, the very same shader does not work in example 2. It seems to only work when example 1 is invisible, or out of the camera's view. At first I thought this was my shader causing this issue, or I set something up, but as far as I can tell it is nothing on my end.

Here's a GIF showing what is happening:

![godot_shader_error_gif](https://user-images.githubusercontent.com/25082678/45783474-d94f3180-bc33-11e8-98ce-14ad11496d73.gif)

When example 1 is invisible, the shader works like it is supposed to, but when example 1 is visible, for some reason it does not seem to work.

My guess is that the second shader is somehow getting leftover data from the first shader, but I have limited OpenGL experience so I could be completely and totally wrong.

**Steps to reproduce:**
Download the provided example project. Example 1 and the sprites within it work fine and as expected.
Example 2 only works when either example 1's `visibility` property is set to `false`, or when example 1 is completely out of view.

**Minimal reproduction project:**
[2D_Clipping_Shader_Tutorial.zip](https://github.com/godotengine/godot/files/2398822/2D_Clipping_Shader_Tutorial.zip)
(Don't mind the name. I was starting to work on a new tutorial when I discovered the error 😅 )

**Comment by eon-s** [comment]
I think that you need to use `BackBufferCopy` nodes if you want to combine more than one shader that uses screen texture.

In that example, change the 2 `Node2D` "example" nodes to `BackBufferCopy` on viewport mode and it should work as expected.

**Comment by TwistedTwigleg** [comment]
I tried using `BackBufferCopy` nodes and unfortunately it does not work.
Strangely all sprites using the shader disappear completely when parented to a `BackBufferCopy` node. The sprites disappear when using `Viewport` mode or `Rect` mode.

Maybe something is wrong with my shader? I thought what it is doing is fairly straight forward and wouldn't be causing issues, but maybe I messed something up. I have used this shader before in Godot 2.0, and I do not think it had this issue.

I'll go check the 2.0 version and then update this comment with my findings!

**Comment by TwistedTwigleg** [comment]
So, I was playing around with the shader and trying things when I discovered something. It appears that separating the examples into two different `CanvasLayer` nodes fix the issue.

![godot_shader_bug_picture_2](https://user-images.githubusercontent.com/25082678/46641609-85ec4700-cb40-11e8-9979-23a7877c4ef0.png)

I am not sure why this works though, but for my purposes this workaround will do nicely.

I was talking to a friend, and he said that perhaps the issue is a ownership or timing issue, and by using a `CanvasLayer` it resets and/or syncs everything up. Of those two possibilities, my hunch is the problem is related to ownership.

Regardless, I am happy to have found a workaround, as it means I can continue moving forward on some projects I've had on the back burner.

______

I should still keep this open, correct? What I found seems to be more of a temporary workaround rather than a fix.

**Comment by eon-s** [comment]
If this is not the intended behavior of the renderer, then is a bug and should remain open.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by TwistedTwigleg** [comment]
I haven’t tried a nightly build in awhile, so I’m not sure. I can test this weekend though.

**Comment by reduz** [comment]
This is not a bug, and it works just like expected. Adding a BackBufferCopy as suggested makes it work:
![image](https://user-images.githubusercontent.com/6265307/51765437-7cb6c400-20b6-11e9-88ea-361ab6bd7cb0.png)

I recommend reading the docs on this:
https://docs.godotengine.org/en/3.0/tutorials/shading/screen-reading_shaders.html

**Comment by TwistedTwigleg** [comment]
I had tried adding a BackBufferCopy node and I did read the docs page, both before making the issue and when it was suggested. I can assure you I did my research. 

I guess whatever was causing the issue has been fixed now. Now I can move forward and make the tutorial I was planning. Thanks for testing Reduz!
