### ISSUE TITLE
OSIphone doesn't support GLES2 as video driver yet

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#22271]
**Godot version:**
Master (e20a28a7)

**OS/device including version:**
iOS

**Issue description:**
This is likely an oversight and not the sign of any particular technical difficulty, but the current iOS platform code doesn't have the toggle for GLES2 as a video driver, so it still supports only GLES3 as in Godot 3.0:

https://github.com/godotengine/godot/blob/08f452d1a95d7f171472c33a60983d95adf1665d/platform/iphone/os_iphone.cpp#L52-L60

This should be easy to fix for any iOS contributor by copying the way other platforms initialize their video driver (see in particular 08f452d1).

**Comment by samgreen** [comment]
I can likely take this on in the next couple of weeks.

**Comment by Disputer** [comment]
> I can likely take this on in the next couple of weeks.

Hi
I can't switch to gles2 when export to iOS, am I right?

**Comment by samgreen** [comment]
I believe that is correct @Disputer

**Comment by Disputer** [comment]
> I believe that is correct @Disputer

@samgreen The game is very simple, but on iphones6/7 it heats up very fast. And iphone5 doesn't work at all. https://itunes.apple.com/app/id1409659469

**Comment by Disputer** [comment]
Guys! please help solve this issue(

**Comment by BastiaanOlij** [comment]
I really need to get myself a personal Mac so I can compile Godot for iOS again....

**Comment by Xancett** [comment]
I've got a mac but no experience with the engine itself.  I'm messing around to see if I can figure out how to fix this but I'm sure the more experienced people will have this patched before I figure it out.

**Comment by Disputer** [comment]
There is no problem with Gles2 on Android, but I can't use it for iOS( 
I started to develop with Godot 3+ and didn't know about such problem, and now I can't come back to Godot 2(
So, I'm waiting for someone who can close this task, that's all I can do( I just need to switch the game to Gles 2 for all ios devices.

**Comment by akien-mga** [comment]
It will be fixed for 3.1-stable, please give it some time.

@samgreen Would you look to have a go at this? Should be pretty easy, just doing the same changes as were needed for other platforms (see OP).

**Comment by Disputer** [comment]
> It will be fixed for 3.1-stable, please give it some time.

Is there any way to jump back from Godot 3 to 2 maybe?(( 
I need gles2 for iOS very much ((

**Comment by volzhs** [comment]
I tried it once. but it was not as easy as I thought. :(

**Comment by Disputer** [comment]
> I tried it once. but it was not as easy as I thought. :(

it's sad (
