### ISSUE TITLE
Error Spam:  editor/editor_node.cpp:3167 - Condition ' p_class.empty() ' is true.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22276]
**Godot version:**
3.1 a4e4dd3

**OS/device including version:**
Windows 10 

**Steps to reproduce:**
1. Create Node
2. Add script
3. Search Help and choose one document
4. Again Search Help, each time when you press a key, error will occur

https://streamable.com/f51ny

ERROR: get_class_icon: Condition ' p_class.empty() ' is true. returned: __null
   At: editor/editor_node.cpp:3167

**Comment by akien-mga** [comment]
Fixed by #22171.
