### ISSUE TITLE
Bodies with RayShape are unable to travel through obstacles

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#22283]
**Godot version:**
197a3b292487b57f5de4ae49ea2d61f2a6da7c7a

**OS/device including version:**
Ubuntu 18.04, GTX1060

**Issue description:**
Rigid bodies that are using a Ray collision shape are unable to travel through small obstacles. This problem was introduced between 3.0 and current main (it's working fine in 3.0).

_Current (Bad)_
![rayshape_edges_bug](https://user-images.githubusercontent.com/6129594/45816247-55e91b00-bcdb-11e8-8f30-50f8974f843a.gif)

_Godot physics engine (good)_
![rayshape_edges_right](https://user-images.githubusercontent.com/6129594/45816250-57b2de80-bcdb-11e8-8d22-240dfdb08b05.gif)

**Steps to reproduce:**
Short version:
1. Download sample project.
2. Open RayShapeEdges.tscn
3. Run it
4. Press left arrow key on the keyboard to push the body towards obstacle
5. Observe that the body is unable to move on the obstacle

Long version:
1. Create new scene
2. Create static body with a box shaped obstacle (and its visual representation - in my sample/reproduction I'm using ConcavePolygonShape imported from Blender)
3. Create RigidBody with representation in character mode
4. Attach Ray Collision shape to the RigidBody
5. Ensure collision shape is longer/higher than the obstacle height
6. Put the RigidBody near the obstacle 
7. Add a small script that will apply force to Rigid body towards the obstacle
8. Run the simulation and observe that the body is unable to move on the obstacle

**Minimal reproduction project:**
[RayShapeEdgeObstacles.zip](https://github.com/godotengine/godot/files/2401102/RayShapeEdgeObstacles.zip)

**Comment by kubecz3k** [comment]
Heyo @AndreaCatania

**Comment by AndreaCatania** [comment]
I think that it's expected, Reduz indroduced new way to use ray shape, if the obstacle is higher than ray shape it doesn't step on.

Godot physics doesn't have this feature for this reason you can't reproduce it

**Comment by kubecz3k** [comment]
@AndreaCatania That new feature sounds reasonable, but it's not the case here, the ray shape is higher than the obstacle in the presented scenario

**Comment by AndreaCatania** [comment]
oh ok, in the gif seems that the sphere touch the step. I'll check the project

**Comment by kubecz3k** [comment]
(the space between the ball and the floor is because of the #22249 - the shape comes exactly from the center of the ball and it's length is equal to ball radius)
