### ISSUE TITLE
Change location of script result adding script with empty name to "Script" Viewport

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22289]
**Godot version:**
3.1 a4e4dd3

**OS/device including version:**
Windows 10

**Issue description:**
1. When I changing location of unassigned script(e.g. Node.gd) everything seems to work well
When I assign Node.gd to script(without saving node), and I change location of script, still it work well

2. But when I save scene and then I change location of Node.gd, then bug "Another resource is loaded from path: res://new folder/Node2D.gd (possible cyclic resource inclusion)" occur and in Script Viewport is add script with empty name 

3. After save scene, I try delete script from node and without saving it, I change location of this script and script with empty name was occurred and script assign itself to node

4. When I repeat 3 point with saving scene after remove script from node, then it works well 

**Steps to reproduce:**
![jfile](https://user-images.githubusercontent.com/41945903/70703508-9235dc00-1cd0-11ea-95da-06bddeb01118.gif)

ERROR: Another resource is loaded from path: res://new folder/Node2D.gd (possible cyclic resource inclusion)
   At: core/resource.cpp:79

This is well know bug and it is not related with this issue:
ERROR: set_drag_preview: Condition ' get_viewport()->gui_is_dragging() ' is true.
   At: scene/gui/control.cpp:772

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

**Comment by KoBeWi** [comment]
Fixed in 3.4
