### ISSUE TITLE
In OSX when entering rest when resuming godot does not respond

### ISSUE THREAD

**Issue by rafael-arreola** [godotengine/godot#22288]
**Godot version:**
3.1.alpha.official

**OS/device including version:**
OSX

**Issue description:**
When you close the lid of the mac or suspend directly from the apple menu "rest",

**Steps to reproduce:**
 if godot is for example with the following 3 nodes
1 -Control
1.1 ---TextureRect
1.2 ---Node2d
and you leave Node2d selected and suspend when restarting godot no longer reacts completely:
When selecting TextureRect the Layout menu does not appear in the upper bar of the 2D screen

- If  you try to close godot when confirming it, the process does not end.
- If you prepend CMD + Q it does not close
you can only close godot with the task monitor or with Force Exit in the apple menu.
I have not verified that more features are lost ..

**Comment by Calinou** [comment]
@rafael-arreola Can you reproduce this issue in [3.2alpha3](https://godotengine.org/article/dev-snapshot-godot-3-2-alpha-3)?

**Comment by rafael-arreola** [comment]
fixed in higher versions
