### ISSUE TITLE
Crash on write 'tool' on editor

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#2229]
*Bugsquad edit:* Seen in f697ec2fe022583dde5f3ae650f49cfd7f237c33

I try to use tool mode on script, when digit 'tool' the editor crash returning this error on terminal:

   ERROR: get_token_identifier: Condition ' tk_rb[ofs].type!=TK_IDENTIFIER ' is true. returned: StringName()
   At: modules/gdscript/gd_tokenizer.cpp:975.

**Comment by volzhs** [comment]
I have same problem. :-(

**Comment by volzhs** [comment]
@reduz I guess this is a critical issue for the moment.

**Comment by AlexHolly** [comment]
+1 on July 5, 2015 build 
works with 1.1 stable

**Comment by volzhs** [comment]
No more crash on writing 'tool' on editor at revision c2e2f2e0aebf6342e6f18ae5d67b6a825590675a.
But 'tool' actually does not work.

**Comment by volzhs** [comment]
I found 'tool' works when restart editor.

**Comment by akien-mga** [comment]
According to above comments it should have been fixed.
