### ISSUE TITLE
Allow us to change the color of the viewport border

### ISSUE THREAD

**Issue by exts** [godotengine/godot#22299]
**Godot version:**
All

**OS/device including version:**
Windows 10

**Issue description:**
Currently there's no way to change the purple border that represents your window size in a scene. Depending on the color you use for the default clear color, it makes it difficult finding that border when creating your scenes.

![image](https://user-images.githubusercontent.com/16387107/45854264-d3c71980-bd0f-11e8-81f6-0931cbf1df7d.png)

You see the purple line, I want to be able to change that. Not sure what it's called.

**Comment by exts** [comment]
Yes! thanks @Chaosus

**Comment by drrrew-k** [comment]
Yes, please. I really can hardly see this border
![изображение](https://user-images.githubusercontent.com/116371652/235302547-9b2561ae-8b07-4e83-883e-2a6d6767b70d.png)
