### ISSUE TITLE
Getters/Setters not always seen by autocomplete when using typed GDScript

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#22291]
**Godot version:**
9136f1287e75a0232c54caa32a917bd146ced81b

**OS/device including version:**
Ubuntu 18.04, GTX1060

**Issue description:**
I have noticed that for some methods autocomplete does not work, even when using types in Gdscript. I have noticed that a lot of getters and setters methods are not listed in autocompletion. 

**Steps to reproduce:**
Sample1: 
1. In your script create a variable `var some : Node;`
2. Try to write `some.get_name()` and `some.set_name(`
3. Notice that there is no autocompletion for those methods

Sample 2:
1. In script create a variable: `state : PhysicsDirectBodyState;`
2. Try to write `some.get_step(`
3. Notice that there is no autocompletion for this method.

**Minimal reproduction project:**

**Comment by kubecz3k** [comment]
cc @vnen

**Comment by reduz** [comment]
This is on purpose, if there is a property, the setter/getter will not appear in the autocomplete. They do not appear in the documentation either.

It affects mostly those who come from Godot 2.x as confusing, but makes it easier for new users who dont know they exist. Maybe this could be enabled by an option in the settings for those who want it, but not sure if its worth it.

**Comment by kubecz3k** [comment]
@reduz But it's not very productive, when I'm looking at autocomplete because I want to find some property which I dont quite remember the name, I'm usually just typing 'get_' to filter out all the properties that all in the class and quickly find the one I wanted to use.

**Comment by reduz** [comment]
I know, but the setters/getters are not supposed to exist anyway and don't appear in the documentation. You know they exist because you used Godot 2.x, but new users don't. This is why I mean, that if you really want this it could be added with an option, but should never be the default as it would make matters more confusing for users who never used 2.x

**Comment by kubecz3k** [comment]
So no new setters/getters will be added for new properties?

**Comment by reduz** [comment]
they are added, but not exposed to GDScript

**Comment by kubecz3k** [comment]
Or maybe there could be another way to quickly filter out members from the classes, since currently it's really hard to find/change variable quickly. Currently there is no quick way to check properties in autocomplete...
However I still think the most natural one for people who has programming background would be to simply  expose those method, even if that would be only a option :)

**Comment by reduz** [comment]
I do agree that autocomplete should probably work in a bit more clear view, or show what everything is, with categories or even showing to which class it does belong

**Comment by kubecz3k** [comment]
closed by #23240

**Comment by chandujr** [comment]
Sorry for necroing this thread, but I wanted to ask a question: so what's the recommended method? Users who use 3.x and above are not supposed to use setters and getters?

**Comment by akien-mga** [comment]
Indeed, you're supposed to use properties directly. So not `node.set_name(new_name)` but `node.name = new_name`.

**Comment by Zireael07** [comment]
@akien-mga: What's the point of setters then if we're not supposed to use them, then?

**Comment by akien-mga** [comment]
Properties are implemented via their setter and getter. Both syntax are equivalent, properties are the recommend workflow so they're the only ones exposed in the auto completion to avoid redundancy.
