### ISSUE TITLE
New "Toggle split mode" button sometimes stops working

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#22307]
**Godot version:**
8e4b18a

**OS/device including version:**
Win10

**Issue description:**
![image](http://g.recordit.co/rVnPdBzko6.gif)

**Steps to reproduce:**
Click it several times or switch to internal folder, Im not found the pattern which causes it

**Comment by groud** [comment]
I cannot reproduce :/

**Comment by somnivore** [comment]
It seems to happen when the FileSystem panel is too small.  By putting it by itself, or by making it tall enough, it works.

![image](https://user-images.githubusercontent.com/28724859/45867455-2113ad00-bd49-11e8-8380-17afa95e5f85.png) ![image](https://user-images.githubusercontent.com/28724859/45867484-325cb980-bd49-11e8-9ac5-a30e36a211e6.png)

**Comment by Chaosus** [comment]
Found the pattern
-Create folder, switch to that folder, press the button, return to root folder - and you can observe it
![image](http://g.recordit.co/ycz5SAtE7V.gif)

**Comment by groud** [comment]
> Create folder, switch to that folder, press the button, return to root folder - and you can observe it

As @somnivore said, I think the problem comes from the fact that your FileSystem window is not high enough. The split view switches to a single panel view in which the file list is the same as the not split mode file list.

**Comment by groud** [comment]
So it's an expected behavior.

**Comment by capnm** [comment]
> So it's an expected behavior.

Is it somehow possible to disable this behavior? Which commit brought this split button?

**Comment by groud** [comment]
> Is it somehow possible to disable this behavior? Which commit brought this split button?

What do you mean ? I added this change in the recent update of the FileSystem dock.

**Comment by Chaosus** [comment]
Ah, I realized how to use the new filesystem, its really an expected behaviour. However, I think seems reasonable to simply hide this button when FileSystem is small enough and button does not work..

**Comment by groud** [comment]
> However, I think seems reasonable to simply hide this button when FileSystem is small enough and button does not work..

The problem is that the button also enables the files display in the tree view. So I cannot make it disappear when the size is too low. But Indeed, I might hide it when we are in a situation where the button seems to do nothing (in the file list, when dock height is too low)

**Comment by groud** [comment]
I don't mind, I can remove the "split-mode go to single panel mode" completely if this is wanted.

**Comment by Chaosus** [comment]
Also I think the limit of FileSystem to shrink down is too small(or high). I have a project with huge amount of nodes and I prefer to use Default layout(a new one), the problem that if I shrink Scene tab for see more items the FileSystem tab removes its split complete. 

![image](https://user-images.githubusercontent.com/3036176/45869821-17fafe00-bd92-11e8-951e-c982fbd38a90.png)

![image](https://user-images.githubusercontent.com/3036176/45869904-50024100-bd92-11e8-83c2-b0d543a2350d.png)

**Comment by capnm** [comment]
+ selecting the Favorites could list the favorites:

![image](https://user-images.githubusercontent.com/4047289/45872950-9efba680-bd91-11e8-8fe2-136155596ce6.png)

**Comment by groud** [comment]
> Selecting the Favorites could list the favorites:

Please open another issue for feature requests.

**Comment by capnm** [comment]
> Please open another issue for feature requests.

https://github.com/godotengine/godot/issues/22309
If you fix this one, please also close the PR #21499
