### ISSUE TITLE
[Mono] Add conversions between Dictionaries and self-constructors

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#22300]
**Godot version:** master / After 3.1 Alpha 1 / d9e88bccbea11189b9ea1437d4a48266b69aaf27

**OS/device including version:** Xubuntu 18.04 LTS 64-bit

**Issue description:** Godot C#'s Dictionary class currently lacks some of the features of Mono's Dictionary class. It would be nice if Godot's Dictionary could function with feature parity to Mono's Dictionaries. Specifically what came to mind is constructing by taking another Dictionary of the same type as an argument. This might not be necessary due to the [mutability](https://github.com/godotengine/godot/pull/15880#issuecomment-381409784), but it would still be nice if code written for `System.Collections.Generic.Dictionary` would work for `Godot.Dictionary` too.

Additionally, there is no way (as far as I can tell) to convert between Godot's Dictionary and Mono's Dictionary. See the last two lines in my example code.

See also: https://github.com/godotengine/godot/pull/15880 CC @neikeq 

    // This code works fine:
    var a = new System.Collections.Generic.Dictionary<int, int>();
    var b = new System.Collections.Generic.Dictionary<int, int>(a);
		
    // This code ("var d" line) doesn't compile:
    var c = new Godot.Collections.Dictionary<int, int>();
    var d = new Godot.Collections.Dictionary<int, int>(c); // Takes in Godot Dictionary
		
    // These would also be nice to have:
    var e = new Godot.Collections.Dictionary<int, int>(a); // Takes in System Dictionary
    var f = c.ToMonoDictionary(); // Returns System.Collections.Generic.Dictionary<int, int>

**Comment by neikeq** [comment]
> ``` C#
>var c = new Godot.Collections.Dictionary<int, int>();
>var d = new Godot.Collections.Dictionary<int, int>(c); // Takes in Godot Dictionary
>```

What should this do? Should it behave similar to the native copy constructor? Or should it do a copy of the elements?

> ```
var f = c.ToMonoDictionary(); // Returns System.Collections.Generic.Dictionary<int, int>
```

It's not really a "MonoDictionary" so that wouldn't be a good name, and `ToDictionary` may be confusing, so not sure what name to go with.

**Comment by aaronfranke** [comment]
It should ideally be similar to how the above lines for System.Collections.Generic.Dictionary work, assuming that functionality is in-line with the rest of Godot.Dictionary's code.

I'm not sure. "ToSystemDictionary" seems a bit generic. Or, it could just be a cast.

**Comment by NathanWarden** [comment]
I think ToSystemDictionary would be fine since it matches the namespace. That's what popped into my head right after reading neikeq's reply.

**Comment by aaronfranke** [comment]
Perhaps something like `var f = (Godot.Collections.Dictionary<int, int>)c;`

**Comment by aaronfranke** [comment]
So, it seems that this issue magically fixed itself. Feel free to re-open if anyone still has this on master.
