### ISSUE TITLE
Long error take a lot of space and overlap with text "Warnings" when editor has small width

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22302]
**Godot version:**
3.1 561a777

**OS/device including version:**
Windows 10

**Issue description:**
When I do a mistake in code(there is example when I change name move_and_slide to move_and_collide) and there is shown long error, the message overlap with text Warnings and take a lot of vertical space.

![aaaaa](https://user-images.githubusercontent.com/41945903/45863574-09531d80-bd77-11e8-861d-1669ad4885ae.png)

**Comment by mateusfccp** [comment]
Well, I made the following. I changed `status_bar` to `VBoxContainer` and added a children `HBoxContainer` to contain warning line alone. The result was the following:

![captura de tela de 2019-01-02 13-04-17](https://user-images.githubusercontent.com/4605213/50597894-1b714b80-0e90-11e9-9803-4a8ef9ff1296.png)

I didn't make a PR yet, but the changes can be seen on my fork:
https://github.com/mateusfccp/godot/commit/d181d536a825b035f45726da5c0062eb316a2da6

What do you think?

**Comment by volzhs** [comment]
looks better for me

**Comment by bojidar-bg** [comment]
Looks better, but it will probably take some of the already-limited vertical space on wider screens (16:9).

**Comment by mateusfccp** [comment]
> Looks better, but it will probably take some of the already-limited vertical space on wider screens (16:9).

Surely it takes less space than the current state... I couldn't think of anything better but I'm not much experienced on UI, do you have any idea?

**Comment by eon-s** [comment]
Even with the fixes, it makes the script editor impossible to use, is too intrusive. 

I think that the error panel should be optional and disabled by default because gives a really bad first impression of the script editor, if it stays as a static panel in that position.

**Comment by jaggygames** [comment]
I agree. Or easily dismissed. I tried clicking around and couldn't even see any code to fix the displayed error at one point! ^_^

The proposed change would at least be better on my system. Having it be a fixed size rather than dynamic would be better unless clicked on then more detail can be displayed if any of the error text is cut off.

**Comment by Paulb23** [comment]
What about putting it at the very top of the `warnings_panel`, which can then have its visibility toggled. 

Then later it can provide tooltips with a smaller message about the error similar to other IDE's like so:

![long_error_messages](https://user-images.githubusercontent.com/6584330/51790598-7f391c80-218f-11e9-943a-2b8109c75596.png)
