### ISSUE TITLE
Add clear(er) error messages for networking

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#22318]
Quoting a Discord user:
*There was a problem with an rpc call I was doing. I was using rpc to call a procedure send_player_data(playerID, playerInfo), but in the rpc call, I wasn't including either of those arguments. I don't think the error message was directly caused by the bad rpc call, but it probably triggered some chain of events that eventually caused the error to rise:*
```
ERROR: Attempt to remote call/set when networking is not connected yet in SceneTree.                                       
At: scene/main/scene_tree.cpp:1760
```

**Comment by Faless** [comment]
If it triggered a `chain of events` we should also have gotten other ERROR before that.
See:
https://github.com/godotengine/godot/blob/4547e223933d1c1b24a526b3d632a2f96cdd6c8b/core/io/multiplayer_api.cpp#L288-L297

So unless we didn't detect the call error (unlikely, but need to check), the problem wasn't that.
Can you ask the user to provide a demo project? Is the user sure that client and server were actually connected when making the RPC?

**Comment by mhilbrunner** [comment]
I'll try to debug this, but this was just one example, really. :) Its more a reminder to me to have a look at the error messages in general.
