### ISSUE TITLE
Weird behavior with kinematicbody snap when moving from floor to wall

### ISSUE THREAD

**Issue by moiman100** [godotengine/godot#22312]
Godot version  534b7ef292fa4686ae0fd7d34b6dcdcbe14045ea

**This is 3D, it is just sideview to better illustrate what is happening.**

Without snap.
![without_snap](https://user-images.githubusercontent.com/40793342/45875561-b7bf8880-bda0-11e8-9b4f-b5e6abdeac66.gif)

With snap.
![with_snap](https://user-images.githubusercontent.com/40793342/45875568-bf7f2d00-bda0-11e8-8db0-62c0c601e7c6.gif)

As you can see with snap the ball tries to snap to the corner, but then it continues to wall and realises it shouldn't.

I expected it to fly away like it does without snap.

[Minimal Project.zip](https://github.com/godotengine/godot/files/2404907/Minimal.Project.zip)

**Comment by AndreaCatania** [comment]
What's the wanted result?

**Comment by moiman100** [comment]
I would say it should not snap to a wall.
I guess someone else might want it to snap and slide down, but I don't know.

**Comment by AndreaCatania** [comment]
I didn't implement it so i'm not sure about it's correct behaviour, @reduz can you please check this?

**Comment by moiman100** [comment]
I think you are mixing this with how 2D works. In 3D up is positive so Vector3(0, 1, 0) is up vector.
If you want to move up the y axis in 2D you add velocity like Vector2(0, -1), but in 3D you add Vector3(0, 1, 0). (I haven't used 2D though so I might be wrong.)

**Comment by piratesephiroth** [comment]
oh, yeah, it's like that in 2D and works properly. I didn't know the Y coordinates were inverted in 3D.
Then it might broken indeed.

**Comment by piratesephiroth** [comment]
OK it's still not broken. You did it right the snap margin you set was too big for your speed.

**Comment by moiman100** [comment]
That doesn't fix it, it just alleviates the problem.

**Comment by piratesephiroth** [comment]
it's not a problem, snap traps the kinematicbody to the floor unless it moves fast enough to escape from it

**Comment by moiman100** [comment]
The problem is that when moving over that corner on the surface the ball will keep snapping to it even though the right side of the bump is wall because of the high angle. Then when the ball has finally gone around the corner it realises there is a wall and thus stop snapping. Snapping however doesn't (or atleast shouldn't) affect velocity so the ball flies away from wrong point.

**Comment by vnen** [comment]
Snapping was added specifically to _avoid_ the body flying on slopes, sticking to the ground. So it seems to me it's behaving correctly but it's not configured correctly for your case. The `snap` parameter is for distance not really for direction.

**Comment by reduz** [comment]
I changed the snap behavior so it will only snap to floor if whatever is snapping to is a floor. I think it makes a lot more sense this way (if you don't provide a floor vector, it will snap to anything). It should fix this issue efficiently.
