### ISSUE TITLE
Shape offset on tileset

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#2231]
![pantallazo-ventana sin titulo](https://cloud.githubusercontent.com/assets/6296184/8503195/c6c3b3f0-2191-11e5-8e47-ee9a0999bcde.png)

When using several shapes on a single tile, a single shape-offset is used for the tile. It would be cool to have a per-shape offset for the tiles.

Also when using an offset for the texture, the collision shape does not use the on-editor shape offset. Instead it uses half the size of the texture as the offset. I think the collision shape and the texture should have different offsets.

Notice that this is currently fixed by manually editing the tileset shape-offset parameter, but this change is overwritten every time the tileset is exported.
When exporting the tileset insted of using the shape offset within the sprite node (32, 32), it uses half the size of the texture (32, 40).

This is what happens on my game:
![pantallazo-ventana sin titulo-2](https://cloud.githubusercontent.com/assets/6296184/8503329/0f839586-2194-11e5-9318-d8ce199a1775.png)

**Comment by romulox-x** [comment]
I'm having a hard time understanding what's going on here.  Can you post an example project that demostrates the problem?

**Comment by FEDE0D** [comment]
I'm sorry. Here's the test project.
The offset on the right shape is wrong.

https://dl.dropboxusercontent.com/u/274954519/test-shape-tile.zip

**Comment by FEDE0D** [comment]
Still happens on 2.0  alpha build 20151030
