### ISSUE TITLE
"Create new resource" icons missing

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#22320]
**Godot version:**
3.1 ef7b38486

**OS/device including version:**
Windows 10

**Issue description:**
Icons from "Create new resource" are missing, "error" displayed.

![godot-icons-missing](https://user-images.githubusercontent.com/1224527/45889088-d719de00-bdbf-11e8-88f9-3d6ce1e7ce89.PNG)

**Steps to reproduce:**
Click "Create new resource in memory".

![godot-create-resource](https://user-images.githubusercontent.com/1224527/45889172-0cbec700-bdc0-11e8-812a-f4d2d047e2d5.PNG)

**Minimal reproduction project:**
n/a

**Comment by akien-mga** [comment]
Fixed by #22354.
