### ISSUE TITLE
captured mouse doesn't return on break

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#2232]
With mouse mode set to capture in X11, hitting a breakpoint or error should make the cursor available again.  Currently, the cursor is still hidden, so using the debugger (or, in fact, anything else on the computer) with the mouse is not possible.  Alt tabbing and killing the editor returns the cursor to normal.

**Comment by neikeq** [comment]
The same happens if the cursor is set to capture and an error occurs at runtime. In my case, killing the game (instead of the editor) is enough to restore the cursor to normal.

**Comment by okamstudio** [comment]
I'm not sure how to fix this, X11 API is very retarded and can only disable
the mouse globally (any other windowing system will return the mouse
pointer automatically if you change app). If the process is in debug break
it may be fixable though, I guess.

On Thu, Oct 15, 2015 at 4:49 AM, Ignacio Etcheverry <
notifications@github.com> wrote:

> The same happens if the cursor is set to capture and an error occurs at
> runtime. In my case, killing the game (instead of the editor) is enough to
> restore the cursor to normal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2232#issuecomment-148308086>.
>



-- 

*OkamStudio*

**Comment by neikeq** [comment]
It only happens with debug breakpoints. Exported games return the mouse fine (even if crashed), at least in my case.

**Comment by Algrin6** [comment]
I still have this issue either with a breakpoint and with an error.

**Comment by akien-mga** [comment]
Me too actually, I tried yesterday a small project that captured the mouse and when running into an error, there was no way to get the mouse back.

**Comment by akien-mga** [comment]
Here's a test project derived from another issue, that makes the bug easy to reproduce. Just run the game, and then press any mouse button to trigger a call to a non-existing function. An error will be raised in the debugger, but the mouse will still be captured.

[mouse_capture_on_error.zip](https://github.com/godotengine/godot/files/127574/mouse_capture_on_error.zip)

**Comment by Algrin6** [comment]
I want to add for fullness of description that if you switch to another window yourself (not with an error or a breakpoint), everything is ok.
