### ISSUE TITLE
'printraw' prints nothing

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#2233]
print("1")
printraw("2")
printraw("3")

This code should produce the following result:
1
23

However it produces this result instead:
1

[...]

I wish to have this option better organize through spacing the readability of my error and feedback messages. Thanks in advance for any fix.

**Comment by eska014** [comment]
`printraw` prints only to the OS output, not the editor built-in console.
As far as I know, this is because the built-in console only prints whole lines ending with newline in every singular call, so it can't fulfill the requirements of `printraw`.

**Comment by agameraaron** [comment]
Yep, I would like some kind of option to control the newlines in the editor's output. So that if I need to print later in the code, but it's all designed to list out horizontally, I can fit it without flooding new lines.

**Comment by reduz** [comment]
Yeah all the console API including debuggerand remote debugger  is based on lines, printraw will not work. This is impossible to support given that lack of EOL markers requires complex buffering schemes that never really work as one would expect. 

Having this limitation makes everything much simpler.

**Comment by agameraaron** [comment]
Oh okay. I guess I should just concatenate it all before printing it new lines then. Thanks for the info.

**Comment by larix45** [comment]
Hey, I know that it is closed issue, but solution to problem like this for someone who is trying to do this is simply use vaiadable, and print full lines normally using print(). Like that:
`var line_to_print = ""
line_to_print += "first part"
line_to_print +=" second part"
...
print(line_to_print)`
This would work in editor console output.
