### ISSUE TITLE
Enums autocomplete to dictionary methods

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#22333]
**Godot version:** 3.1 561a777

**Issue description:** Typing an enum's name dot doesn't autocomplete to the keys but rather to dictionary methods:
![aa](https://user-images.githubusercontent.com/35355161/45912199-861fdf00-bdeb-11e8-9c90-a1f852067ad7.png)

@vnen: I do think enums should be a bit more special than just constant dictionaries, at least with respect to autocomplete and gdscript errors/warnings. For example, you can call A.clear() without problem, shouldn't this at least raise a warning?

**Comment by Oranjoose** [comment]
Yes, it would be nice if enum would autocomplete to the actual enum keys.

**Comment by CngKO** [comment]
This is a regression in 3.1 as this bug did not exist in Godot version 3.0.6
