### ISSUE TITLE
Bullet Physics collision shapes larger than they should be (collision gaps)

### ISSUE THREAD

**Issue by NykolaR** [godotengine/godot#22334]
Godot Master Branch (built sept. 20th)

OS: Linux x86_64

Using bullet physics, the collision shapes seem to be expanded beyond their visible size. See below (bullet on the left, Godot physics on the right)
![bullet_phys_gaps](https://user-images.githubusercontent.com/15218653/45912512-325bc880-bde0-11e8-8e94-af62c011fc8d.png)

Steps to reproduce: Create any project with 3D bodies colliding

Minimal Project:
[min_bullet_col.zip](https://github.com/godotengine/godot/files/2407454/min_bullet_col.zip)

**Comment by AndreaCatania** [comment]
This is due to margin of 0.04 applied to each shape as default. I can absorb it in the extends of box or radius of sphere... but it seems like a bad hack...

@reduz what do you think about it?

**Comment by akien-mga** [comment]
@AndreaCatania I guess this was fixed by #23472?

**Comment by capnm** [comment]
afaict nothing changed:

![image](https://user-images.githubusercontent.com/4047289/51638273-3c443280-1f5e-11e9-89c9-027869144041.png)

**Comment by akien-mga** [comment]
Closing as fixed by #23472. The default margin can be lowered.
