### ISSUE TITLE
Error 0 - :1 (GodotSharp)

### ISSUE THREAD

**Issue by TehcJS** [godotengine/godot#22330]
**Godot version:**

Godot Engine v3.0.6.stable.mono.official.831 4054

**OS/device including version:**

OS: Windows 10
Processor: Intel Celeron Quad Core Processor N3450
Graphics Card: Intel HD Graphics (I don't think this is related)

**Issue description:**

When I was creating a new build of my game, I noticed that whenever the game finishes building and runs, the game windows freezes, and the debugger says "0 - :1". Can someone please help me?

**Steps to reproduce:**
(Unknown)

**Minimal reproduction project:**

https://drive.google.com/file/d/1ksW_9RbSO8C6RzsP4RuVXKnShKYkf4xj/view?usp=sharing

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by Herofied1180** [comment]
Do you know why it's doing this and how to fix it?

**Comment by neikeq** [comment]
The uploaded project is incomplete. It's missing `project.godot`, although `project.binary` seems to work when opening from terminal. There are many errors about missing resources when loading the editor. There is no C# solution or project, and no C# files other than `Properties/AssemblyInfo.cs`.

**Comment by KoBeWi** [comment]
@TehcJS Can you still reproduce this in Godot 3.2.2? If yes, please upload a *complete* minimal project.

**Comment by TehcJS** [comment]
I'll try to reproduce it again when I get some spare time.

**Comment by akien-mga** [comment]
Closing for now as there's no update and the attached project can't be used.
