### ISSUE TITLE
TouchScreenButton Rotation behavior

### ISSUE THREAD

**Issue by R3D9477** [godotengine/godot#22341]
**Godot version:**
3.0.5

**OS/device including version:**
Linux Mint 19 x64

**Issue description:**
Why TouchScreenButton rotates around Position instead of own center (in that time Sprite rotates around center)? Is it possible to rotate TouchScreenButton around center of it's current selected texture?

Thanks.

**Comment by r3d9u11** [comment]
_would be cool to get feature like a `rotation offset` and unify rotation behavior for all objects, who supports rotation and _

**Comment by KoBeWi** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3976
