### ISSUE TITLE
Hide 'Favorites' if there are none

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#22344]
A teeny-tiny UI tweak... I'd suggest hiding the 'Favorites'-item in the FileSystem-view, if one has not added any favorites.

**Comment by moiman100** [comment]
Then you wouldn't be able to drag files into favorites. You could still of course use context menu.

**Comment by groud** [comment]
Yeah, that would prevent you from

**Comment by Calinou** [comment]
I'll close this due to lack of support (see the above comments).

**Comment by Flavelius** [comment]
'Favorites' in general only make sense in small projects. I can imagine a poll would reveal that less than half of the users actually use it, which would warrant an option to hide it, as it's unnecessary visual noise in a panel that relies heavily on textual recognition; i personally never used it as it doesn't provide any benefit and is even disadvantageous in an organized project where it just lumps together various assets.
