### ISSUE TITLE
Add more operators to line continuation

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#22348]
This is a feature request.  Currently, it seems that only `,`  (and perhaps `()`, though I haven't tested it) allows for line continuation.  Sometimes it may be useful to have line continuation on operators such as `+ - / * %`.  This may affect parsing and/or formatting on the back end, so it may not come without issues.

**Comment by akien-mga** [comment]
You can add a line break with `\`.

**Comment by vnen** [comment]
Expressions within parentheses can be split into many lines.

**Comment by akien-mga** [comment]
I think so.
