### ISSUE TITLE
If window resize is disabled it prevents both users AND code from modifying the size.

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#2234]
If "OS.is_window_resizable()" is false (due in my case to the project settings), the user shouldn't be able to resize the window while the program is running. Which does happen.
However... it also prevents that resizability in code! For instance...

newframesize = (640,480)
OS.set_window_resizable(true)
OS.set_window_size(newframesize)

This will work!... but then the user can resize the window even if I only wanted that one size!
So we try this right after...

OS.set_window_resizable(false)

And it sadly resets the window size back to the project default! Just setting the window size alone does nothing because the resizability settings prevent it.

My use case is a setup screen that resizes when you go into the input setup submenu. I might even have it just be another scene in the entire game if I can resize the window proper & on-the-fly. Thanks in advance for any fix to this issue because it's a bit of a showstopper. I'd have to make them all separate projects or reorganize the menus if not!

**Comment by eska014** [comment]
Resizing from code with `is_window_resizable() == false` works for me on Windows.
Is this still valid?
If so, what platform are you using?

**Comment by agameraaron** [comment]
By "works" you mean you can change the window size in code after setting resizability to false for users?
I am using Linux Mint 17.1

**Comment by vnen** [comment]
This can be tested in the Window Management demo. Click "FixedSize" button, which disables the ability to resize, then click the "Resize" button, which does a resize by code. I'll try to test on Linux later.

**Comment by eska014** [comment]
Can't reproduce on Windows with the demo, so I'll label this as X11 for now.

**Comment by agameraaron** [comment]
Thanks for going through a number of my bugs by the way, eska!

**Comment by reduz** [comment]
this is fixed given all the screen API was rewritten
