### ISSUE TITLE
"Condition  '!id_map.has(p_rid.get_data()) ' is true. returned: 0" unstoppable error spam

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#22347]
**Godot version:**
29c557a

**OS/device including version:**
Win10

**Issue description:**
There is unstoppable error spam, under certain circumstanses 
Its probably related to new "Toggle split mode" button because it spam only after its pressed no matter activate or unactivate

**Steps to reproduce:**
-Click "Toggle split mode" button
-Click on Output window - After few seconds the spam will begin(or not if something wrong)

![image](http://g.recordit.co/YYtESNeRbW.gif)

**Comment by Chaosus** [comment]
cc @groud

**Comment by groud** [comment]
I can't reproduce on my side, can you try with latest master or provide a sample project ?

**Comment by groud** [comment]
Also, maybe try deleting your cache (it is in /home/username/.cache/godot on linux but I don't know on windows, sorry)

**Comment by Chaosus** [comment]
> Also, maybe try deleting your cache (it is in /home/username/.cache/godot on linux but I don't know on windows, sorry)

Yeah, deleting cache helps, bug can still happened but rarely than before. I need to observe it more precious to found the source.. (and build an example project)

**Comment by Chaosus** [comment]
Looks like its fixed, I close it for now

**Comment by Chaosus** [comment]
Nah.. its still happens. under certain circumstanses, linked to "Toggle split mode" button

**Comment by Chaosus** [comment]
Hmm.. its still not happened for a long time.. I will close it again

**Comment by kidandcat** [comment]
I'm getting the same error when:

```
        var Pixel = preload("res://Graphics/pixel.otf")

        var font = DynamicFont.new()
	font.size = 15
	font.font_data = Pixel
	draw_string(font, Vector2(20.0, 40.0), "Hello World!", "#000000")
```

E 0:00:00:0548   Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
  <C Source>     ./core/rid.h:164 @ getornull()

**Comment by kidandcat** [comment]
Ok, found it!!
https://github.com/godotengine/godot/issues/15023

**Comment by Torguen** [comment]
This error continues to occur for several versions but the problem is closed?.

![Captura](https://github.com/godotengine/godot/assets/19652075/6cbcbcd0-a9be-4379-8d99-3726b6cde597)
