### ISSUE TITLE
Tilemap editor is not being rendered properly.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#22349]
**Godot version:**
3.1 d9e88bc

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When you select a tilemap node the grid is not rendered correctly in the viewport, it doesn't follow the viewport camera and doesn't zoom in.

**Comment by CowThing** [comment]
It's happening in both GLES versions.

**Comment by Ranoller** [comment]
![tilemapbug](https://user-images.githubusercontent.com/11712737/46239614-f48c1080-c39a-11e8-9105-3202e1a61fe8.gif)

It´s only the visual representation... editor works well and tile swapping was recently fixed.... it seems like if in any place there was missing any "affine_inverse" or something like this (i try some with no results)

**Comment by 8thMage** [comment]
i fixed it in my pull request.

**Comment by akien-mga** [comment]
Fixed by f7a986641.
