### ISSUE TITLE
Fucking really? You are just going to close it? 

### ISSUE THREAD

**Issue by NaymanHohnheimer** [godotengine/godot#22358]
I try to help you people by showing you how a CoC will benefit your community and you close the issue, no questions asked?
You might think that you are protecting your little 'alt-right safe space' but your project won't survive without a CoC. You are going to get right wing scum coming in and before you know it someone will drop the n-word in the code. When that happens, I will ave my hand on the tweet button.
Remember, we always win.  In a week, or month, or year, the Contributor Covenant will be in the source, I promise you that. 
There is no compromise, you can either be on the right side of history, fighting for social justice, or you can be a fascist and have your kids spit on your grave. Your choice :woman_shrugging:

**Comment by reduz** [comment]
@NaymanHohnheimer Re-read the comments in the previous issue where you posted, all your answers are there and you missed them.

**Comment by NaymanHohnheimer** [comment]
Explain

**Comment by NaymanHohnheimer** [comment]
Explain how anything is more important at this moment other thank adding a CoC to stop nazis?

**Comment by reduz** [comment]
Go back to the previous issue and learn to read, there were two linked issues properly explaining the situation and discussion. There is no way you read them all in such a short time, so go do your homework and don't be stupid.
