### ISSUE TITLE
ItemList missing styles

### ISSUE THREAD

**Issue by ykoc** [godotengine/godot#22359]
Godot 3.1 Alpha 1 (and all master builds up to 18.09)

OS: Windows 7

In Theme editor ItemList has 6 styles - 2 for background, 2 for cursor (that seems to do nothing) and 2 for selected item. There is no editable style for non-selected item. Unlike tabs in #22266 those items are properly displayed without theme.

**Comment by KoBeWi** [comment]
The ItemList doesn't need style for non-selected items. The items are text-only with guide lines between them. So adding a dedicated style would require a change of how the list is drawn. Thus it's something for a proposal.

As for the cursor styles, they are used with multi-selection mode. The docs could explain that better.
