### ISSUE TITLE
Tooltip uses PanelContainer styles

### ISSUE THREAD

**Issue by ykoc** [godotengine/godot#22367]
Godot 3.1 Alpha 1 

OS Windows 7 

It seems that tooltip uses styles for PanelContainer. While without custom theme set they have different styles (PanelContainer is by default dark violet and Tooltip is grey), after defining theme styles for PanelContainer they start using the same texture.
On screenshot - PanelContainer with Tooltip (sorry for small cropping)
![clipboard03](https://user-images.githubusercontent.com/35262366/45925660-79ea6d80-bf22-11e8-96d9-95d1fd87d490.png)

**Comment by YeldhamDev** [comment]
`TooltipPanel` inherits from `PanelContainer`, so there isn't anything that can be done.

**Comment by Calinou** [comment]
@YeldhamDev How are the default tooltip themes defined? Couldn't we expose theme items for those in the theme editor?

**Comment by YeldhamDev** [comment]
@Calinou I think the "issue" is that setting a style to `PanelContainer` also affects tooltips, since it inherits it.

**Comment by KoBeWi** [comment]
Fixed in 4.0
In 3.x the PopupPanel uses `get_stylebox("panel")` instead of `get_stylebox("panel", "TooltipPanel")` like on master, this is why the issue still appears. Fixing it would technically break compatibility, idk.
