### ISSUE TITLE
Saving a scene apparently shows a major speed regression

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#2236]
*Bugsquad edit:* Seen in Godot 1.2 June 29 dev. build

Confirmed on a Win64 dev. build done using MingW 64bit on the 29th of June.

It seems to me that saving scenes in the latest available builds of Godot version 1.2 is a lot slower than the equivalent function in Godot 1.1. Complex scenes can take nearly ten seconds to save compared to saving almost instantly in the official release. The good news is that there's no crashing and no instances of Godot saving over the wrong data (even with multiple scene editing in play).

System; Win7 64 bit with an ATI 7xxx GPU

Anyway, it would be nice to know if this can be solvable.

**Comment by reduz** [comment]
i don't think anything changed in scene saving, so it's probably a bug.
Will check as soon as I return home

**Comment by KillerJaguar** [comment]
I've noticed this issue as well and was going to post about this as well. Before, I never noticed anything when posting Ctrl+S, but now it freezes for a second while it shows a saving bar.

**Comment by reduz** [comment]
ah i think i know what this is, there was an issue looking for resource
dependencies when saving that wa fixed, and this results in more through
searching in the scene for dependencies.
in which stage of the saving bar is frozen?

**Comment by KillerJaguar** [comment]
![](http://i.imgur.com/QXQFjkj.png)

This is the longest pause when saving

**Comment by bojidar-bg** [comment]
Can confirm. Happens especially when I change the size of a loaded image. (IK I should import it instead..)

**Comment by akien-mga** [comment]
I believe this has been fixed already, hasn't it?

**Comment by akien-mga** [comment]
I haven't seen this for a while personally, so closing.
