### ISSUE TITLE
Invalid locale: C

### ISSUE THREAD

**Issue by girng** [godotengine/godot#22365]
#### Godot Version
3.0.6 stable.
#### OS Version:
Linux Mint 19 Tara

i just downloaded linux mint, because wanted to experience linux. however, am getting
```
0:00:00:0139 - Invalid locale: C
----------
Type:Error
Description: Invalid locale: C
Time: 0:00:00:0139
C Error: Condition ' !is_locale_valid(trimmed_locale) ' is true.
C Source: core/translation.cpp:943
C Function: set_locale
```

when i run a blank scene in  a brand new project. any idea? not sure what's going on, my linux mint is up to date

**Comment by aaronfranke** [comment]
Do you have full language support installed? Ubuntu asks about this on first run, I'm not sure about Mint, but after searching I found [this](https://askubuntu.com/questions/824437/how-to-install-language-support-completely-using-command-line) which may help: `sudo apt install $(check-language-support)`

Do you have the Godot dependencies installed? I'm not sure if these are required for the pre-built binaries, but it's worth a try (this does not include [Mono](https://www.mono-project.com/download/stable/#download-lin) if you need that, or try [my script](https://github.com/aaronfranke/Linux-tools/blob/master/ubuntu-only/programs-to-install.sh)):

    sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev \
        libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libfreetype6-dev libssl-dev libudev-dev \
        libxi-dev libxrandr-dev

**Comment by akien-mga** [comment]
> Do you have the Godot dependencies installed? I'm not sure if these are required for the pre-built binaries, but it's worth a try (this does not include Mono if you need that, or try my script):

These are compilation dependencies, they're not needed to run the engine.

**Comment by akien-mga** [comment]
What is the output of `locale` on your system? As @aaronfranke mentions, your system is likely not properly setup for a given locale, it should typically be `en_US.UTF-8` or any other language/country code combination. `C` is the fallback when nothing is configured.

**Comment by akien-mga** [comment]
I'll filter out the `C` case and make it default to `en` translations though.
