### ISSUE TITLE
"No loader found for resource: res://" when selecting 'root' viewport

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#22376]
**Godot version:**

8b2eeaa724829445b1f8b65855a816003df4f2ba

**OS/device including version:**

Windows 7 SP1

**Issue description:**

Message "No loader found for resource: res://" gets spammed to Output when selecting 'root' viewport.

**Steps to reproduce:**
Create any scene and play it. Select 'root' viewport.

**Minimal reproduction project:**

**Comment by DualMatrix** [comment]
I think I know what causes this. I'll see what I can do
