### ISSUE TITLE
To romulox_x... :D

### ISSUE THREAD

**Issue by mamarilmanson** [godotengine/godot#2237]
This is the simplest way I could think about importing... DAE and Textures go to custom folders...

![screen shot 2015-07-08 at 9 23 49 am](https://cloud.githubusercontent.com/assets/3820189/8561241/1835ec32-2555-11e5-9f90-b762877612ff.png)

**Comment by reduz** [comment]
what does Textures do? Also you still have to select a destination path I
guess

**Comment by mamarilmanson** [comment]
@reduz ~ yes... for organization... some people (like me) doesn't want all the textures in one gigantic folder...

**Comment by reduz** [comment]
Textures are just copied to the same location of the scene file

**Comment by mamarilmanson** [comment]
yes... and it's messy...
