### ISSUE TITLE
Android exporting templates not working with Mono version.

### ISSUE THREAD

**Issue by Oen44** [godotengine/godot#22382]
**Godot version:**
3.0.6 mono

**OS/device including version:**
Windows 10 17134.285, 1803

**Issue description:**
Android exporting doesn't work. Installed export templates but Godot still says that export templates for Android are missing, can't export to APK.

**Steps to reproduce:**
Install Godot 3.0.6 mono, create project, create example scene, create export for Android, install export templates.

**Minimal reproduction project:**
None needed.

Tested on no-mono version and templates are working there, Export Project button is enabled and working.

**Comment by piratesephiroth** [comment]
I think mono exporting is only available for desktop at the moment

https://github.com/godotengine/godot/issues/18364#issuecomment-406222102

**Comment by vnen** [comment]
Yeah, C# it's not support on Android. See #19839 and #20267.
