### ISSUE TITLE
Sub transition does not trigger auto advance in parent animation state machine

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22389]
**Godot version:**
`master` / ef7b384861

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
I have an animation state machine that defines idle, moving, and sitting states as follows:
![image](https://user-images.githubusercontent.com/2367032/45940046-afba4f80-c011-11e8-8281-46b2f59a9d9e.png)

And the transition from `Sit` to `Idle` state has `Auto Advance` option checked, and its `Switch Mode` set to `AtEnd`. I assume this would make the state automatically switch from `Sit` to `Idle` when animation defined in `Sit` finishes playing:
![image](https://user-images.githubusercontent.com/2367032/45940151-4424b200-c012-11e8-9876-16ded47db3de.png)

This set up actually works as expected when `Sit` is a simple `AnimationNodeAnimation` node. However, I made it a nested state machine instead, as shown below:
![image](https://user-images.githubusercontent.com/2367032/45940161-4edf4700-c012-11e8-96ba-f5f04d4c81d9.png)

As the tooltip suggests, I assumed when the state changes to `Sit End` and when its animation finishes, the whole state machine would stop playing, thus triggering `Sit` to `Idle` transition defined in the parent would trigger, but it seems that it's not the case.

Rather, it looks like the state machine falls into an invalid state, and consecutive invocation to change its state would fail with the following message:
```
ERROR: process: Condition ' playback.is_null() ' is true. returned: 0.0
   At: scene/animation/animation_node_state_machine.cpp:79
```

**Comment by mysticfall** [comment]
I know we are already quite busy with remaining issues targeted for the upcoming 3.1 release, but could you consider including this issue in the milestone also?

The reason is, the problem makes it much more difficult to implement such actions like sitting down, or using items, etc. using `AnimationTree`.

Currently, one needs to resort to such workarounds like not using sub states at all (and putting everything in a single state machine which can be difficult to maintain) or adding additional function track at the end of the getting up animation or calculating the length of that animation and using a timer to get notified when the character finishes the animation then manually advance the parent state machine.

I think this issue is quite an important one for those who want to use `AnimationPlayer` to implement more complex animation system, so I wish it could be fixed sooner (hopefully with 3.1) than later.

**Comment by mysticfall** [comment]
I was finally able to test this on the latest master(89560c213) however, it seems that I still can't get it to work as intended.

With a setup described above, I can make the character enter a `Sit` state, both in the parent and child states. But if I travel to `Sit End` state in the child node, the character correctly plays the animation but the state stuck in `Sit`(parent) / `Sit End`(child) state.

Can anyone confirm this issue is really fixed?

**Comment by guilhermefelipecgs** [comment]
For me it's working fine, see
![peek 01-01-2019 20-30](https://user-images.githubusercontent.com/1387165/50576949-1bc40500-0e04-11e9-8f1e-87065e3002f6.gif)

**Comment by guilhermefelipecgs** [comment]
I'm using this code and seems to works fine. Can you provide an example that I can test it? I think this way will be easier.
```
extends AnimationTree

var playback : AnimationNodeStateMachinePlayback = $"."["parameters/playback"]
var sit_playback : AnimationNodeStateMachinePlayback = $"."["parameters/Sit/playback"]

func _input(event):
	if event is InputEventKey:
		if event.scancode == KEY_SPACE:
			playback.travel("Sit")
		else:
			sit_playback.travel("Sit End")

func _process(delta):
	print(playback.get_current_node())
```
![peek 05-01-2019 10-58](https://user-images.githubusercontent.com/1387165/50724713-f4598a80-10d8-11e9-85a1-425527af8db8.gif)
