### ISSUE TITLE
Rigidbody2d bouncing around

### ISSUE THREAD

**Issue by indiemaniac** [godotengine/godot#22386]
Using the current version on steam, 3.0.6 i think, windows 10 with latest updates.
[https://mega.nz/#!DZ8ixSBC!moDkQ8eIqZL3_aMrbt8NnT4evxMbackH4UFIDzFBHbk](url)

I created a rigidbody2d, instance it 3times on top of eachother, and they starting bouncing/vibrating randomly.
They are on top of a tilemap, but its the same if they are on top of a static body.

[platformer_slash_folder.zip](https://github.com/godotengine/godot/files/2409413/platformer_slash_folder.zip)

**Comment by groud** [comment]
I can't reproduce on master.
@AndreaCatania was this fixed already ?

**Comment by Xrayez** [comment]
I couldn't reproduce on master either, but found annoying that the character can't slide along the floor smoothly without some minor vertical bumping, perhaps RayShape2D should help.

**Comment by AndreaCatania** [comment]
I don't know, I didn't touched physics 2D

**Comment by groud** [comment]
> I don't know, I didn't touched physics 2D

Arf... indeed. Sorry for that ^^

**Comment by akien-mga** [comment]
Seems to work fine in the current master branch (or I don't understand how to use the MRP to trigger the issue - I just piled a few players on top of each other).
