### ISSUE TITLE
Can't export to windows 

### ISSUE THREAD

**Issue by draxdeveloper** [godotengine/godot#2238]
All my windows exports are resulting in crashing.
The export to Linux is working,

**Comment by reduz** [comment]
yeah users reported this, not sure why it happens though, help would be
appreciated

**Comment by draxdeveloper** [comment]
yeah... there is any solution?

**Comment by kubecz3k** [comment]
@draxdeveloper If you are asking about temporary solution... On my linux 64bit machine I can export to windows and game runs without any problems... Maybe try on virtual machine and see how it goes?

**Comment by akien-mga** [comment]
Duplicate of #2189.
