### ISSUE TITLE
How does one use a Texture Atlas in Godot 3? 

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#22391]
In Godot 2.1 you would put all your sprites in a folder outside of Godot and then when you imported them a big sprite atlas would be created automatically, this worked fairly well. But It seems like this really important feature for some reason never got transferred to Godot 3? 

Below is a Mockup of one of our Sprite Atlases (created in Texture Packer specifically for Godot 3). The problem with the texture packer plugin for Godot 3 is that it currently does not work as intended and therefore does not give the draw call reduction you would expect. 

[https://github.com/CodeAndWeb/texturepacker-godot-plugin/issues/1](https://github.com/CodeAndWeb/texturepacker-godot-plugin/issues/1)

Right now it looks like this is the only way to create and use a Sprite Atlas in Godot 3 is through a "broken" third party plugin? Or are we over looking something?

![image](https://user-images.githubusercontent.com/24936603/45940410-533b3e00-bfd9-11e8-9608-aa99b12b1352.png)

**Comment by arkology** [comment]
#13940

**Comment by arkology** [comment]
Don't know why atlas packing option is removed. In my opinion, using texture atlas the way it is implemented in Godot 3 is NOT convenient and flexible.

**Comment by piratesephiroth** [comment]
Well, you don't need the plugin at all.
You can save your AtlasTexture as a png image and load it manually.

**Comment by jesperkondrup** [comment]
@piratesephiroth Could you elaborate on this?

**Comment by piratesephiroth** [comment]
You pack the frames in a single spritesheet, divided in blocks of equal size, like this:
![example1](https://i.imgur.com/p34bNAQ.png)

Then you add it to a sprite and adjust the Animation property in the inspector
This image is divided in 16 blocks so it has 4 rows (Vframes) and 4 columns (Hframes)
![example2](https://i.imgur.com/gGpEYSi.png)
You can them animate it with an animationplayer, for example.

**Comment by jesperkondrup** [comment]
The issue is that my Sprite Atlas does not have sprites of equal size (as you can see in the example I posted).

**Comment by piratesephiroth** [comment]
In that case it isn't an animation either, you're just packing the different static images together for convenience.
Can't you just assign the same texture to the different sprites specifying different regions for each onee?

**Comment by jesperkondrup** [comment]
No we am not animating anything, and we am definitely not creating Sprite Atlases out of convenience, it would be a lot easier to have the images separately. But you need to have Sprite Atlases in order to reduce draw calls especially when making mobile games.

**Comment by piratesephiroth** [comment]
well let's hope it gets fixed soon then

**Comment by metaphoricalsasquash** [comment]
This is not an issue I have now, as my level is rather small, but something I see myself struggling with down the line as well.

**Comment by piratesephiroth** [comment]
Also reminder that this bug only happens if you use the TexturePacker plugin (or import those multiple resource files).

It works as exactly expected if you make multiple sprites use different regions from the same texture.

So you can use AtlasTextures as long as you don't use the plugin.

**Comment by Keetz** [comment]
@piratesephiroth this issue isn't tied to the TexturePacker plugin! You can see  #21506 for a issue specifically targeted to TexturePacker.

This issue is about how Godot handles spritesheet, and it just mentions TexturePacker as the only alternative right now.

And yes you are right, you can manually define regions but that is an extremely, extremely, extremely tedious task to do!

There is auto slicing, but it works pretty bad and also if you use that, you have to go to every single sprite, set the texture, perform the auto slicing and then select the region, again, very tedious!

The way it was handled in 2.x was pretty smart, maybe not the import stuff and so on, but it generated .atex files based on the .tex file, and you could just drag and drop those .atex files, very smart! very easy to use! (.tex being the atlas and .atex being kind of a reference and a region to the atlas)

TexturePacker kind of does the same, but as mentioned it is pretty broken right now (or Godot is?), and also more importantly, why should we be dependent on a third party plugin to a paid tool? Godot should be able to handle spritesheets properly itself, in my opinion.

So again to clarify, this has nothing to do with TexturePacker, it is just used as an example!

**Comment by piratesephiroth** [comment]
Yeah it is a problem with Godot loading external resources.
It reads the whole texture everytime it loads the new resource instead of caching it and reusing as many times as needed, like it does with a built-in resource.

**Comment by damianday** [comment]
I think godot should handle it similar to unity, godot 2 was close. Given how much texture atlas are used in games especially 2d why godot 3 makes you jump hurdles to use them.

**Comment by piratesephiroth** [comment]
I think I figured it out.

The plugin is intentionally denying the caching of the texture by setting the p_no_cache argument of ResourceLoader.load.

https://github.com/CodeAndWeb/texturepacker-godot-plugin/blob/e9912d574e3c624bc545aff39f8a1a0e76326c16/addons/codeandweb.texturepacker/image_loader.gd#L54

So just change that last argument to `false` (or remove it) and the plugin will work as expected.

**Comment by piratesephiroth** [comment]
Yeah that only solves the problem with TexturePacker plugin's RAM usage problem.
Godot still lacks a native feature however it makes it possible to use the atlases the way the OP wants.

**Comment by jesperkondrup** [comment]
@piratesephiroth Very nice, the fix for the Texture Packer plugin seems to work! So now we can definitely use the Texture Packer plugin.
But as both you and @Keetz mentioned the original issue is still relevant. A third party addon that you have to pay for is not optimal.

**Comment by piratesephiroth** [comment]
Today I remembered ShoeBox exists so I made this:
https://github.com/piratesephiroth/GodotTexturePackerShoeBoxConfig

Yeah it's still 3rd party but you can make excelent spritesheets and load them with the TexturePacker Imperter plugin for free.

**Comment by hedin-hiervard** [comment]
I made this tool to approach this problem:
https://github.com/hedin-hiervard/spritesheet-creator

It can be used as a standalone spritesheet creator for Godot and a drop-in replacement for TexturePacker (which is no longer needed).
I will soon upgrade it to include more options and add support for other popular engines.

**Comment by piratesephiroth** [comment]
ah yeah, later on I made this plugin too
https://github.com/piratesephiroth/shoebox-pixijs-spritesheet-plugin

However it it hasn't been reviewed yet (probably because people are busy with the wild jam)

**Comment by arkology** [comment]
Re-added in https://github.com/godotengine/godot/commit/04847ef5f98d9a20a72286c44cc26302ec82dec5, should be closed now. @akien-mga

**Comment by Calinou** [comment]
Closing, as this was implemented in https://github.com/godotengine/godot/commit/04847ef5f98d9a20a72286c44cc26302ec82dec5.

**Comment by rakkarage** [comment]
Can anyone please elaborate on this? This is in 3.2? How to setup "Image Groups" that turn sprites into atlas? Thanks

**Comment by artism90** [comment]
@rakkarage https://godotengine.org/article/atlas-support-returns-godot-3-2

It yet has to be properly documented in the docs. (https://github.com/godotengine/godot-docs/issues/4019)
