### ISSUE TITLE
Creating an inherited scene shouldn't open a new scene tab leaving an empty scene tab

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#22393]
This is a minor issue. When using this option:
![shot_180924_103515](https://user-images.githubusercontent.com/7307968/45943217-be8b0d00-bfe5-11e8-9f87-2f5b73d00f6d.png)
in the second case when no root node exists, a new scene tab is opened leaving an empty scene tab behind. In my opinion the option should use the opened empty tab instead.

Related issues: #13013 #4585

**Comment by Anutrix** [comment]
Issue not reproducible in latest master https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987.
Issue exists in 3.1.1 stable though.

**Comment by akien-mga** [comment]
Closing as fixed then.
