### ISSUE TITLE
Project won't open!

### ISSUE THREAD

**Issue by BigDC** [godotengine/godot#22390]
I was working on my project, when it just crashed. It would not reopen. I was able to track the problem to a GDSQLLite directory, "lib". Remove the "lib" directory from the project it will open, add the "lib" back and it will crash Godot and my project and not open.

Now here is where it gets really strange. I can drag that "lib" directory into any of my other projects and thay all open fine, put it back in the first project and it crashes Godot and will not open my project. I have no code written anywhere in my project that tries to load gdsqlite or use any of its functions. All I did was add the "lib" directory into my project, no code for it was written yet, nothing else.

Recap... As I have said before, add the "lib" dir and Godot will crash and my project not open, remove the "lib" and Godot and my project opens fine. Drag the "lib" into any other Godot project and all other projects open fine.

I want to use GDSQLite in this project, it works in any other project of mine. Please help?

**Comment by groud** [comment]
This is a problem from GDSQLite, not Godot itself. Please open an issue on the GDDSQLLite repository.

**Comment by akien-mga** [comment]
Note: It *may* eventually be narrowed down to an engine bug, but indeed it would be better to first debug it with the help of the GDSQLite developers, to know how their library impacts Godot in a way that can make the engine crash.
