### ISSUE TITLE
Need help with skeletal deformation in Godot3

### ISSUE THREAD

**Issue by r3d9u11** [godotengine/godot#22392]
**Godot version:**
3.0.6

**OS/device including version:**
Linux Mint 18.3 x64

**Issue description:**
I learns skeletal deformation in Godot3 by tutorial [Godot gets 2D skeletal deform  
](https://godotengine.org/article/godot-gets-2d-skeletal-deform) and manual [page](http://docs.godotengine.org/en/latest/classes/class_skeleton2d.html) of Skeleton2D.

But I can't find Skeleton2D in my Nodes tree. Where is it?
![screenshot at 2018-09-24 10-27-05](https://user-images.githubusercontent.com/15020827/45940909-699ac700-bfe4-11e8-885a-e9f26f6f54e2.png)

Or this feature isn't available in the current versions of Godot and will be added in the future?

Thanks.

**Comment by groud** [comment]
You have a menu up there in the 2D editor, that let you mark nodes as bones and create an IK chain.
![2018-09-24-104119_451x238_scrot](https://user-images.githubusercontent.com/6093119/45943391-656fa900-bfe6-11e8-8651-6cabf8032615.png)

In any case this is not the place to ask for how to use the engine, but to spot bugs or ask for new features. Please ask into the other [community channels](https://godotengine.org/community).
