### ISSUE TITLE
Godot does't recognize if is visible scene tab when closing it

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22399]
**Godot version:**
3.1 399910d

**OS/device including version:**
Windows 10

**Issue description:**
Godot should check if scenes tab are visible when closing some of it.

**Steps to reproduce:**
![jfile](https://user-images.githubusercontent.com/41945903/70703634-cc9f7900-1cd0-11ea-9aa5-7bb55f9988ea.gif)

**Comment by qarmin** [comment]
Also when I close all visible scene and there is still some hidden scene, after changing  size editor and maximize it, "Distraction Free Mode" icon has wrong position

https://streamable.com/nzqc0

**Comment by Calinou** [comment]
I can confirm this in 3.3.3.

**Comment by kitbdev** [comment]
Can't reproduce in 4.1.2
probably fixed in #56970
