### ISSUE TITLE
Project Export Patch does not work

### ISSUE THREAD

**Issue by Galileo53** [godotengine/godot#22394]
**Godot version:**
V3.0.6

**OS/device including version:**
WIN7

**Issue description:**
When trying to make a patch at the Export dialog, nothing happens

**Steps to reproduce:**
1. Export a project, using Project - Export - Export Project. This creates export.pck.
2. Do some changes, e.g. in a .gd file. Save the file.
3. Open Project - Export - Patches (Tab). Klick "Add initial export..." and select "export.pck" from previous step.
4. No more "previous patches" exist, so leave that alone.
5. Press "Make Patch". Nothing happens. Neither a patch is created, nor an error is given.

**Comment by exts** [comment]
Doesn't work with alpha 3.1 alpha3 (avoided alpha 4 for now) either using classic and mono versions (cc: @akien-mga )

**Comment by exts** [comment]
tested with 3.1 beta3 and it's still not a think

**Comment by reduz** [comment]
Sorry, this feature was never finished it seems. Will have to be kicked back yet again because we keep forgetting.

**Comment by reduz** [comment]
Maybe for now the tab could be hidden? what do you think @akien-mga ?

**Comment by akien-mga** [comment]
If the feature doesn't work at all, seems fine to hide it for now yes.

**Comment by Kiel97** [comment]
Looks like it's still not working in Godot 3.1.1 and it's visible in Export dialog box.

**Comment by akien-mga** [comment]
Hiding it for now with #34911.

**Comment by Calinou** [comment]
I'll close this issue as this unimplemented feature can no longer be accessed. Discussion on a new patch system is ongoing [here](https://github.com/godotengine/godot-proposals/issues/146).
