### ISSUE TITLE
Popup window to change language(and other similar too) should show first entry around mouse

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22404]
**Godot version:**
3.1 Alpha

**Issue description:**
When I try to change language to english, I must move mouse above because first entry is very high. It should be placed around location where we click. Try to right click at the web browser to see that first entry is at the right at the bottom of mouse cursor

Now:
![aaaa](https://user-images.githubusercontent.com/41945903/45963383-5a873980-c023-11e8-9000-3a5aefe98dc6.png)

How should it look:
![bbbb](https://user-images.githubusercontent.com/41945903/45963432-72f75400-c023-11e8-8a63-4169f45d2d98.png)

**Comment by KoBeWi** [comment]
I think this is correct. The list is just very long.

> Try to right click at the web browser to see that first entry is at the right at the bottom of mouse cursor

Try with a very long list too. It has the same behavior.

**Comment by KoBeWi** [comment]
Now the list looks like this
![image](https://user-images.githubusercontent.com/2223172/148399105-a791b267-f37d-4abc-8aee-7baf8ec7a241.png)
It's too long to appear at the cursor and this is consistent with behavior in browsers etc. so closing.
