### ISSUE TITLE
It's impossible to change body's friction when manual physics integration is in use

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#22406]
**Godot version:**
aaef640b8c3e7c7c49aae11a1c8c9e606223fefd

**OS/device including version:**
Ubuntu 18.04, GTX1060

**Issue description:**
It seems it's impossible to change body friction from the inside of the `_integrate_forces` method. This is a new problem introduced between 3.0 and current main.

**Steps to reproduce:**
Short way: 
1. Download sample project
2. Open FrictionIssue.tscn
3. Check script that is attached to `FrictionBody` node, this script will change body's friction to 1.0 after 0.75s runtime time (inside `_integrate_forces` method).
4. Run the FrictionIssue.tscn scene and notice in output tab that the friction is always equal 0.0.

Manual way:
1. Create new scene
2. Attach rigid body node to the scene
3. In RigidBody inspector set 'Custom Integrator' to true

<details>
  <summary>
4. Attach this script to the rigid body:
  </summary>

```

extends RigidBody

const STATE_NO_FRICTION = 0;
const STATE_NEED_2_CHANGE_FRICTION = 1;
const STATE_FRICTION_CHANGED = 2;

var frictionChangeState = STATE_NO_FRICTION;

func _ready():
	friction = 0.0;
	yield(get_tree().create_timer(0.75),"timeout");
	frictionChangeState = STATE_NEED_2_CHANGE_FRICTION;

func _integrate_forces(state):
	var lv : Vector3 = state.linear_velocity;
	var delta : float = state.step;
	var gravity : Vector3 = state.get_total_gravity()*delta;
	lv += gravity;
	state.linear_velocity = lv;
	
	if(frictionChangeState==STATE_NEED_2_CHANGE_FRICTION):
		friction = 1.0;
		frictionChangeState = STATE_FRICTION_CHANGED;
		print(name,  "changing friction to 1.0, right after the change: ", friction);
	
	elif(frictionChangeState==STATE_FRICTION_CHANGED):
		print(name,  "current friction: ", friction);
```
</details>

5. Run the scene and notice in output tab that friction is always equal 0.0

**Minimal reproduction project:**
[ManualIntegrationFrictionIssue.zip](https://github.com/godotengine/godot/files/2411675/ManualIntegrationFrictionIssue.zip)

**Comment by AndreaCatania** [comment]
Do you have a resource applied? if not the problem could be that.

Try to set a physics material resource and change that parameter. if this doesn't fix it let me know

**Comment by kubecz3k** [comment]
In a scenario with physic material it's working fine (when changing code to use the material). However using `friction` member directly should work as well...

**Comment by akien-mga** [comment]
`friction` and `bounce` are deprecated in 3.1, the project issues warnings about it:
```
WARNING: set_friction: The method set_friction has been deprecated and will be removed in the future, use physics material instead.
   At: scene/3d/physics_body.cpp:640.
WARNING: get_friction: The method get_friction has been deprecated and will be removed in the future, use physics material instead.
   At: scene/3d/physics_body.cpp:653.
```
They are configured not to be saved in the scene files (see the `0` here): https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/scene/3d/physics_body.cpp#L1027-L1028

However using `set_friction` (or the `friction` property) should set the friction property in the physics material normally: https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/scene/3d/physics_body.cpp#L644-L648

**Comment by akien-mga** [comment]
I'll investigate, it looks that logic I wrote isn't working.
