### ISSUE TITLE
Godot 3.1 alpha animator doesn't automatically move to a newer frame

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#22408]
Hi, I'm using an animated sprite being animated in the animationplayer node, but everytime I click on Setting up a frame as a keyframe it doesn't automatically move to a newer frame, I'm wondering why Godot devs removed this functionality if it worked like that in 2.1 and 3.0

**Comment by avencherus** [comment]
I just noticed this yesterday, wasn't sure if I was imagining it, but was trying to keyframe the frames of a spritesheet.  It used to advance the frames, so you could click it rapidly to fill the track.

Confirmed it no longer works that way at least as of:  aaef640b8c3e7c7c49aae11a1c8c9e606223fefd

It was a nice feature, though it had a bit of a bug to it if I recall.  Like it would be off by a frame if you didn't scrub the time back to 0 after the first keyframe.

Hope it returns.  X)

**Comment by metaphoricalsasquash** [comment]
Even with the bug it was a lot more user friendly than it is right now in the 3.1.alpha. As an animator, my job became 20 times more tedious because of all the additional clicks I have to do for something that took just one click in 3.0.6 like setting a keyframe for any property. Please oh please don't leave it like that for the release.

**Comment by akien-mga** [comment]
Hold your horses guys, it's just a bug...

**Comment by avencherus** [comment]
Holding them.  XD

**Comment by metaphoricalsasquash** [comment]
Yay!!

**Comment by avencherus** [comment]
@metaphoricalsasquash Unless I messed something up.  I did a rebuild to check it out, and it doesn't appear to be fully working.  The keyframe time advance was fixed, but the frame value increase part wasn't.  So it still needs some manual entry of frame numbers.

![46263014-3e4b3700-c512-11e8-80eb-05aef90e33c7](https://user-images.githubusercontent.com/13004169/46264951-968e3300-c52a-11e8-8e57-52a662837047.gif)

**Comment by akien-mga** [comment]
Reopening as per https://github.com/godotengine/godot/pull/22536#issuecomment-425754216

CC @DualMatrix

**Comment by DualMatrix** [comment]
@avencherus Do you know which properties should behave like that? Is it only the frame property of sprite? Does anyone else know?

**Comment by avencherus** [comment]
Good question, wondering the same.  I went back to look at 2.1.4, and as far as I know I think it is only Frame properties for Sprite and AnimatedSprite.  Also noticed it works this way on It also looks like Sprite3D and AnimatedSprite3D in older versions.  

There may be more though, I just haven't worked with them.

The clue at least anything I think that has this keyframe icon with a + symbol on it.

![godot 2 1 4 stable_2018-10-01_15-32-25](https://user-images.githubusercontent.com/13004169/46288690-41383d00-c58f-11e8-896c-72073d2ee3d2.png)

**Comment by DualMatrix** [comment]
@avencherus That icon is a great find, gonna try and find out all properties it is used for.

**Comment by guilhermefelipecgs** [comment]
Related #19942.
