### ISSUE TITLE
Editor crash and closes when setting script to extend itself

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#2240]
I have a script called "ghost.gd".
If I extend the same script (extends "ghost.gd") and try to save the script the editor crashes and closes.

I'm on Linux Mint 17 x32

**Comment by kubecz3k** [comment]
It's not clear to me... you are extending ghost.gd from the inside of the ghost.gd?

**Comment by FEDE0D** [comment]
Yes, by mistake. Godot shouldnt crash when doing this.

**Comment by draxdeveloper** [comment]
ok... But why you want to extend the script inside itself?

2015-07-09 13:07 GMT-03:00 Federico <notifications@github.com>:

> Yes, by mistake. Godot shouldnt crash when doing this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2240#issuecomment-120050564>.
>



-- 
David Aguiar de Aquino Paiva

**Comment by FEDE0D** [comment]
I dont. Its just that the editor should not crash.

**Comment by FEDE0D** [comment]
This still happens on 2.0 alpha 20151030.
Note: this only happens when using
```extends "script.gd"```
and not when using
```extends "res://script.gd"```

**Comment by reduz** [comment]
I can't reproduce this any longer, it says:

ERROR: GDScript::reload: Compile Error: Script not fully loaded (cyclic preload?): res://script.gd

in both cases
