### ISSUE TITLE
Script parse error -> constants with same name in differents enums not allowed.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#22416]
**Godot version:**

c432ce4ee15fc396b2bccbbe2661b5bd34b9bee1

**OS/device including version:**

Win 7

**Issue description:**

Godot compiled at 25/09/2018 doesn´t allow to have enum members with same names in diferent enumerations. Godot compiled 2 weeks ago allows that:

![parsererror](https://user-images.githubusercontent.com/11712737/45982068-950ac980-c057-11e8-9a93-eea898d2412e.png)

**Comment by vnen** [comment]
See #22293

**Comment by Ranoller** [comment]
ok, thanks, understood ..... i go... i have some code to change ...
