### ISSUE TITLE
GDScript atan2() and Vector.atan2() bug

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#2241]
I believe the Vector.atan2() function does not work as intended. Here is an example script that displays atan2 values for various unit vectors (anti-clockwise / trigonometric order) and expected values :

```python
printt("Vector", "atan2 value", "expected value") 
printt(Vector2(1,0), Vector2(1,0).atan2(), 0)
printt(Vector2(1,1), Vector2(1,1).atan2(), PI/4)
printt(Vector2(0,1), Vector2(0,1).atan2(), PI/2)
printt(Vector2(-1,1), Vector2(-1,1).atan2(), 3*PI/4)
printt(Vector2(-1,0), Vector2(-1,0).atan2(), PI)
printt(Vector2(-1,-1), Vector2(-1,-1).atan2(), -3*PI/4)
printt(Vector2(0,-1), Vector2(0,-1).atan2(), -PI/2)
printt(Vector2(1,-1), Vector2(1,-1).atan2(), -PI/4)
```
Output : 
```python
Vector	atan2 value	expected value
1,0		1.570796	0
1,1		0.785398	0.785398
0,1		0			1.570796
-1,1	-0.785398	2.356194
-1,0	-1.570796	3.141593
-1,-1	-2.356194	-2.356194
0,-1	3.141593	-1.570796
1,-1	2.356194	-0.785398
```
Obviously, atan2() method calculates value for the inverse vector (0,1) instead of (1,0), (-1,1) instead of (1,-1), and so one.

**Comment by StraToN** [comment]
I can confirm that in core/math/math_2d.cpp, Math::atan2 is called.
real_t Vector2::atan2() const {
	return Math::atan2(x,y);
}

However, in core/math/math_funcs.cpp we have :
double Math::atan2(double p_y, double p_x) {
	return ::atan2(p_y,p_x);
}

We have an inconsistency in the order of atan2() parameters. The GDScript documentation also suffer of this inconsistency where atan2(x,y) is defined instead of atan2(y,x).

**Comment by StraToN** [comment]
I created a branch on my forked repo fixing this bug (https://github.com/StraToN/godot/tree/atan2fix), but it appears that atan2() function is used in multiple locations, showing either atan2(x, y) or atan2(y, x) usages. Maybe it would be nice to define the right syntax once and for all, and correct any impacted use elsewhere in the code and Godot demos. Thanks for your advices guys.

**Comment by xodene** [comment]
I'd be very interested in what's going on with atan2(). I had code using atan2() that I was very sure was correct but didn't work properly.

**Comment by reduz** [comment]
This is solved now, the problem was in Vector2.atan2() which is gone and replaced by Vector2.angle() atan2() is not affected
