### ISSUE TITLE
Add a way to access presets of ColorPicker

### ISSUE THREAD

**Issue by merumelu** [godotengine/godot#22411]
**Godot version:**
 c432ce4 

**OS/device including version:**
Xubuntu 16.04

**Issue description:**
While looking at #22402, I found that there is apparently no way for a game to access preset colors of a ColorPicker. You can add your own with `add_preset` but that's it. You can't remove them again by code or get the list of all current presets.
It's also not possible to keep track of presets added by a player as there are no appropriate signals to know when a preset was added or removed from the UI. You _can_ work around the first one by overriding the hidden `_add_preset_pressed` method or finding the "+" button from the picker's internal child nodes at runtime and connect to its `pressed` signal but that seems quite hackish.

**Comment by lupoDharkael** [comment]
I'll try to work on this and send a PR.
