### ISSUE TITLE
Shortcuts disregard area focus

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#22429]
**Steps to reproduce:**
Set Clone Down and Duplicate Node to the same shortcut (ex Ctrl-D). Open Script Editor. Select Node in Scene Tree. Scene Tree editor area has focus, indicated by a light area outline. Use the shortcut. Both the selected node, and the line with the cursor in the Script Editor (which doesn't have focus), are duplicated.

**What was expected**
Shortcuts working in the area that has focus (excluding ones that affect global areas, like the top bar - ex Play the Project shortcut).

**Comment by Zylann** [comment]
That would be yet another to add to that list: https://github.com/godotengine/godot/issues/9069#issuecomment-398042162

**Comment by KoBeWi** [comment]
Closing as duplicate of #36205, which has a linked PR
