### ISSUE TITLE
Gdscript.round() returns "-0" when a negative number nearest to 0 is rounded.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#22439]
**Godot version:**

c432ce4ee15fc396b2bccbbe2661b5bd34b9bee1

**OS/device including version:**

Win 7

**Issue description:**

Gdscript.round() returns "-0" when a negative number nearest to 0 is rounded...
i don´t know if it is intended, but i think that this value should not be allowed... 

**Steps to reproduce:**
```
func round_to_minus_cero():
	var number = round(-0.01)
	print (number)

#prints "-0"
```

An expression like:

```
number = -0
if number == 0:
		number = abs(number)
		print (number)
```
prints 0.... so -0 and 0 are the same number
it´s fun to have -0 number but for a SimplexNoise script that i´m doing this thing is an strange extra-step (simplexnoise returns -1 to 1.... if rounded it returns -1,-0,0,1....... :) :) :) :) :) :))

**Comment by vnen** [comment]
This is a characteristic of floating-point numbers, so there's nothing really to fix. Since you're probably expecting an integer anyway, you can cast it to `int` to get rid of the negative zero.

**Comment by Ranoller** [comment]
I was thinking  that round was doing this conversion, my fault, thanks for the explanation....
