### ISSUE TITLE
Socket Error

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#22430]
**Godot version:**
3.1-alpha

**OS/device including version:**
Win 7 64 , OpenGL ES 3.0, GeForce GT 650M

**Issue description:**
 I saw this error:
![image](https://user-images.githubusercontent.com/13235119/46030846-3729c080-c0ef-11e8-9b3d-17355ca70c9c.png)

**Steps to reproduce:**
During run of a prototype

**Minimal reproduction project:**
NA

**Comment by Zireael07** [comment]
Which git commit are you on?

**Comment by fire** [comment]
https://github.com/godotengine/godot/issues/21945 Also causes the game to crash with no stack trace.

**Comment by qarmin** [comment]
@Faless I create own method to show this bug #22476

**Comment by Faless** [comment]
I see, then this is not a network error. the `Socket Error` is just a consequence of the fact that the project fails to start.
Closing.
