### ISSUE TITLE
audio sample import bugs

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#2243]
Several things are going wrong with importing audio samples.  I've got a sample imported already, but when I change the wav file that it depended on, I don't see the refesh checkbox on the top right do anything.  When I click reimport, it's not in the list.

When I reimport it myself manually, it does overwrite the sample.  The loop flag doesn't work though.  If I edit the sample, I see that the loop parameters (forward, length...) were retained from the previous version of the sample, but they don't work.  I save and reopen the project, and the loop paramters are gone.  It seems the reimport doesn't set the loop parameters (even though the box is checked), and it also doesn't refresh the loop parameters in the GUI to show that they're reset.

**Comment by sketchyfun** [comment]
Yeah, I noticed that when you import a sample to a SampleLibrary, if you update the original file the SampleLibrary sample doesn't update, even if you re-import it. I have to reopen the scene completely to get it to pick up the changes

**Comment by slapin** [comment]
Imported samples won't work for me at all, I have to set loop points to begin and end of file for it to work.

**Comment by reduz** [comment]
This seems to be working now
