### ISSUE TITLE
Cant assign textures to AnimatedTexture?

### ISSUE THREAD

**Issue by ByTheQuietLake** [godotengine/godot#22442]
**Godot version:**

 8fc92ae

**OS/device including version:**

Wind 7 , Intel HD 4000

**Issue description:**

When creating a AnimatedTexture resource or assigning it on to a sprite and then editing it, there is no means to assign textures to it?

**Steps to reproduce:**
1. Click create new resource button and select AnimatedTexture
2. Change number of frames in the inspector and notice there is no way to assign textures in the inspector
or
1.Create sprite node
2. Assign a AnimatedTexture to its texture and then try to edit it (this way is the same thing as above really)

**Minimal reproduction project:**

**Comment by ByTheQuietLake** [comment]
@groud I would actually classify it as a bug rather than an enhancement, its not working as its suppose to work, and the only instance of how its suppose to work I could find is this [twitter post](https://twitter.com/reduzio/status/1018869906840879104)

**Comment by ByTheQuietLake** [comment]
I tried assigned textures through gdscript to see if it would work and I could not get that to work too. I have made a gif of the problem I stated above:
![animatedtexture](https://user-images.githubusercontent.com/30891267/46907175-45b80a80-cf2c-11e8-9878-a0bc6ce8f08a.gif)

What I believe it should be like is shown in #20221. Without this working its not possible to test animated tiles with tilemaps at the moment,that is without using the animationplayer. @reduz could you consider looking at this. Thanks!

**Comment by ByTheQuietLake** [comment]
I was able to track the change down to cd0b82fd56bdba5a4f1a057fd2d50854c1f503ef .The setting of frames in the AnimatedTexture was made internal, any reason why it was decided to do so? Would it not be beneficial to expose the frames for editing? @akien-mga .Also  I couldn't get the setter function to work even after undoing these changes, maybe I might have made a mistake in its usage:
	texture.set_frame_texture(1,text1);
	texture.set_frame_delay(1,2)
	texture.set_frame_texture(2,text2);
	texture.set_frame_delay(2,2)
	texture.set_frame_texture(3,text3);
	texture.set_frame_delay(3,2)
would this be a correct?

**Comment by ByTheQuietLake** [comment]
AnimatedTexture works in the editor now! It can be assigned to sprites and also can be used to make animated tiles as intended. But the set_frame_texture method to assign frame textures in GDscript doesn't seem to be working, will make a separate issue for it

**Comment by akien-mga** [comment]
Indeed, this was fixed by #24886, sorry I missed it until then.
