### ISSUE TITLE
Objects do not show the drop down when debugger is paused on breakpoint.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22454]
*Godot version:**
3.1 alpha a2b6be2
Mac OS X, High Sierra

**Issue description:**
Local / Globals Objects do not show the drill-down/drop down when debugger is paused on breakpoint. Therefore it is meaningless.

See issue https://github.com/godotengine/godot/issues/22138

![screen shot 2018-09-26 at 12 16 44 pm](https://user-images.githubusercontent.com/930478/46105210-70236d00-c1a3-11e8-9afd-08f40ded862f.png)

**Comment by DualMatrix** [comment]
What types are those variables? So I can compare between 3.0 and 3.1

**Comment by wyattbiker** [comment]
> What types are those variables? So I can compare how it should look between 3.0 and 3.1

```
var btnText=self.get_text())
var scn = load("res://Scene2.tscn")
self (type Button)
```

**Comment by DualMatrix** [comment]
@wyattbiker Thanks, Ill take a look and see if I can fix this.
