### ISSUE TITLE
Scrolling a multiline text box scrolls the Inspector also

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#22459]
**Godot version:**

8fc92ae86faed72c402e7770246ed18d50b5c43b

**OS/device including version:**

Linux

**Issue description:**

When the mouse wheel is used to scroll a multiline text box, it will scroll both it and the Inspector.  Ideally it should only scroll the text box when the mouse is hovering over it.

**Comment by girng** [comment]
thanks for the report.
possibly related to #21848, same ui behavior just diff node

**Comment by KoBeWi** [comment]
Another similar issue #19562
