### ISSUE TITLE
In Mono on Executables from Godotengine.org Webclient fails to OpenRead()

### ISSUE THREAD

**Issue by Grosskopf** [godotengine/godot#22451]
Hey, i've got a Problem in Godot Mono that Monodevelop doesn't have, couldn't figure this one out, guessing it is a Bug, i used similar code in 3.0.6 where it worked but in 3.1 it doesn't work, i didn't however test this exact code in 3.0.6

**Godot version:**
3.1 Alpha Mono

**OS/device including version:**
Linux using Monodevelop

**Issue description:**
I tried to get information from the Web using C# and the WebClient and failed. It crashes on wc.OpenRead()

**Steps to reproduce:**
put this in a ready function:

        WebClient wc = new WebClient();
        using (Stream downStream = wc.OpenRead("http://www.google.de/"))
        {
            using (StreamReader sr = new StreamReader(downStream))
            {
                GD.Print(sr.ReadToEnd());
            }
        }

**Minimal reproduction project:**
[PrinterfaceCLI.zip](https://github.com/godotengine/godot/files/2420223/PrinterfaceCLI.zip)

**Comment by neikeq** [comment]
Does it crash with this exception?

```
System.Net.WebException: An exception occurred during a WebClient request. ---> System.Configuration.ConfigurationErrorsException: Error Initializing the configuration system. ---> System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
```

**Comment by Grosskopf** [comment]
yes

**Comment by Grosskopf** [comment]
Just tested on Windows in Godot 3.0.6 mono, same error

**Comment by Grosskopf** [comment]
On Linux 3.0.6 no error though

**Comment by Grosskopf** [comment]
that being said the working version is the 3.0.6 from the Archlinux user Repository

**Comment by Grosskopf** [comment]
i just tested it with master, built on my system it works, i have 5.14 on linux, with this backend it runs on 3.0.6 stable mono from aur and master selfbuilt but fails on 3.0.6 from godotengine.org and on 3.1 alpha1 from godotengine.org
on windows i tested 3.1 alpha1 from godotengine.org and 3.0.6 from godotengine.org today with mono 5.14.0.177 in the background

**Comment by akien-mga** [comment]
You must use 5.12 for official binaries (it's mentioned on the download
page normally).

**Comment by Grosskopf** [comment]
> You must use 5.12 for official binaries (it's mentioned on the download page normally).
oh.. i'm used to packages being backwards compatible a bit and i thought having the newest mono would be just fine, didn't see that part, sorry for the inconvenience. in that case i'll just work with selfbuilt versions on linux and install the older mono on windows because otherwise my package manager annoys me when i don't have the latest stuff :D
