### ISSUE TITLE
Warning after opening AssetLib "iCCP: known incorrect sRGB profile"

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22468]
**Godot version:**
3.1 8fc92ae

**OS/device including version:**
Windows 10

**Issue description:**
After creating new project and opening AssetLib, when some of the icons are loaded, this error occur:

> 
> WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
>      At: drivers/png/image_loader_png.cpp:67 
>

**Comment by groud** [comment]
The problem might come from the png itself. Might be an expected behavior.

**Comment by akien-mga** [comment]
That comes from the PNG and the warning is raised by libpng, but I thought current versions of libpng stopped issuing warnings for incorrect sRGB profiles, so it's weird.

**Comment by gdtbg** [comment]
Warning is probably legitimate, but makes Godot look buggy to new users.  Where are the images that appear in the Templates tab stored?  Who has access to modify them?
