### ISSUE TITLE
Godot doesn't recognize that main scene was deleted

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22473]
**Godot version:**
3.1 8fc92ae

**OS/device including version:**
Windows 10

**Issue description:**
When I delete main scene INSIDE EDITOR and restart editor then a popup error will occur:

![asfasfasfafasfasfa](https://user-images.githubusercontent.com/41945903/46143261-bc30e900-c259-11e8-96b6-b44605a0cb3d.png)

and error:

> ERROR: load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: scene/resources/scene_format_text.cpp:1225
ERROR: Failed loading resource: res://Node2D.tscn
   At: core/io/resource_loader.cpp:192
ERROR: remove_scene: Index p_idx=1 out of size (edited_scene.size()=1)
   At: editor/editor_data.cpp:564

**Steps to reproduce:**
1. Create scene
2. Save Scene
3. Run Project and set scene as Main/Default
4. Delete Scene (inside editor)
5. Restart Editor

run/main_scene="res://Node2D.tscn" - after remove this line from project.godot, error disappear. 
Godot should check if removed scene is main and it is then should remove this line.

**Comment by akien-mga** [comment]
Fixed by f2e7a650.
