### ISSUE TITLE
New Tileset editor, can't select a tile that's too far outside of a texture.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#22485]
**Godot version:**
3.1 8fc92ae

**OS/device including version:**
Windows 10 64bit

**Issue description:**
If a tile is too far outside of the texture it can't be selected anymore. This happened because I set up some tiles for a texture, but then decided to make the texture smaller and move some tiles to a separate texture, because the texture was made smaller I was no longer able to select the tile that's outside of the new texture.
![unselectable_tile](https://user-images.githubusercontent.com/11450875/46162677-f947ac00-c256-11e8-88ed-f42e083e0675.png)
The tile on the right side can't be selected.

**Steps to reproduce:**
Create a tileset with some tiles, then make the texture smaller.

**Comment by 8thMage** [comment]
I pushed a new pull request here https://github.com/godotengine/godot/pull/22534 that should fix the viewport and mouse overing it, i don't know if it's your problem but i think it's connected enough. please check it.

**Comment by MarianoGnu** [comment]
The tile is not just outside of the texture, it's also outside of the workspace (the control that takes the input) because of this it's not posible to select them to remove it, I started working on two new buttons (with av repag, avpag shortcuts) that circles around al tiles, subtiles, and collision shapes, this could be solution to the problem...

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

CC @guilhermefelipecgs @YeldhamDev

**Comment by akien-mga** [comment]
Ping @MarianoGnu.

**Comment by CowThing** [comment]
This can still be reproduced in 3.1 beta 8

**Comment by YeldhamDev** [comment]
A good solution would be to set the workspace's minimum size to be the farthest tile to the bottom right. I'm working on a PR that implements exactly that.
