### ISSUE TITLE
GLES 2 free_custom_shader error, particles2D

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22486]
**Godot version:**
3.1 cb5a629

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
I know that Particles2D in GLES 2 doesn't work yet, but when I open my project with Particles2D node and I close scene from scene tabs at top, this error occur:

> free_custom_shader: Condition ' !custom_code_map.has(p_code_id) ' is true.
   At: drivers/gles2/shader_gles2.cpp:673.

**Steps to reproduce:**
1. Create node Particles2D in GLES 2
2. Add to it ParticlesMaterial
3. Save it
4. Close scene 

https://streamable.com/21kw3

**Comment by eon-s** [comment]
Apart from the error which should be more clear, remember that `Particles2D` will never work on GLES2, you can only use `CPUParticles2D` there.

**Comment by akien-mga** [comment]
This fixed in the current master branch.
