### ISSUE TITLE
Hostname resolving error when no network connection is available

### ISSUE THREAD

**Issue by Garrom** [godotengine/godot#22489]
**Godot version:**
GoDot 3.0.5 Official (6a88e22)

**OS/device including version:**
Lenovo B50-80
Ubuntu 18.04 - XFce	
Intel(R) Pentium(R) CPU - Dual Core
Ram 4 Gb
Intel Broadwell GT1 - MESA drivers

**Issue description:**
Using [GoDot certificate](https://raw.githubusercontent.com/godotengine/godot/master/thirdparty/certs/ca-certificates.crt). If i call HTTPRequest.request("https://example.com") when internet disabled(disconnected from all networks), I get error below. Script does not care and finish method normaly, I even get correct result, 3 also known as RESULT_CANT_RESOLVE (which is not 0 so game tell player that it need internet connection)

```
0:00:00:0514 - getaddrinfo failed! Cannot resolve hostname.
----------
Type:Error
Description: 
Time: 0:00:00:0514
C Error: getaddrinfo failed! Cannot resolve hostname.
C Source: drivers/unix/ip_unix.cpp:108
C Function: _resolve_hostname
```
Every next call of function (function is connected to button_down signal) cause different error, error below.

```
0:00:03:0084 - Condition ' !p_host.is_valid() ' is true. returned: ERR_INVALID_PARAMETER
----------
Type:Error
Description: 
Time: 0:00:03:0084
C Error: Condition ' !p_host.is_valid() ' is true. returned: ERR_INVALID_PARAMETER
C Source: drivers/unix/stream_peer_tcp_posix.cpp:141
C Function: connect_to_host
```
There must be way to go around and don't throw error, that error is annoying, It is like I done something wrong and it shows error to tell me how useless I am. I'm sure that error can be removed or silenced (don't show it in debugger). I mean, result of HTTPRequest.request() already tell me that it can't resolve. Error message is useless and rather depressing.

**Steps to reproduce:**
-Turn off internet
-Open
-Click button as many times you want
-Check debuger for errors

**Minimal reproduction project:**
Sure pal
[hostname_minimal_test.zip](https://github.com/godotengine/godot/files/2425343/hostname_minimal_test.zip)

**Comment by Faless** [comment]
I think what you are experiencing is normal behaviour.
I think the error tells you what the problem is.
I don't see how that can be annoying.
Making an exception to that error specifically for HTTPRequest does not seem like a good idea.

**Comment by Garrom** [comment]
@Faless Yeah but I'm afraid it will alert player in some way, like showing error message or shutting down application. It runs fine from editor but I can't test build, my project is not suitable to be exported yet. In editor it can be ignored but I'm afraid about exported game.

**Comment by Faless** [comment]
> shutting down application

No, that would not (and should not!) shut down the application. It's just an error message.
And a failure DID happen, so it makes sense that it's logged. (Or you might be left wondering why some users are experiencing trouble and you have no error informations).

Also, usually you don't show the command line with the error messages to your users.
On *nix you make a shell scripts that redirect output to log files, on Windows you make a batch script that does the same (or something similar).
It might actually make sense to have that redirection to file done by Godot itself, but that's something that should probably be addresses in it's own issue and tracked here #19122 if it's not already.
