### ISSUE TITLE
Cannot open a project made in Windows on a Mac

### ISSUE THREAD

**Issue by otanistudio** [godotengine/godot#22484]
**Godot version:**
v3.0.6.stable.official.8314054

**OS/device including version:**
macOS 10.13.6 and Windows 10

**Issue description:**
Cannot open a project made in Windows on a Mac

**Steps to reproduce:**
1. Put together a 3D Godot project with some simple scripts
1. Run it
1. Zip up the whole project
1. Download on a Mac, unzip, and then try to open the project in Godot editor

Result is that the Godot editor terminates without indication about why. I was unsuccessful when searching for logs that might provide clues.

**Minimal reproduction project:**
[Sample File](https://s3.amazonaws.com/com.withme.hiring/tmp/EgoPoC.zip)

**Comment by akien-mga** [comment]
Your `project.godot` file has `config_version=4`, which means that it was made with Godot 3.1 / a nightly build, so it's not compatible with 3.0.6 that you use on the Mac.

**Comment by otanistudio** [comment]
Thanks for the quick feedback! Our team will do a better job at synchronizing versions moving forward.
