### ISSUE TITLE
Export (NodePath) has multiple issues.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22481]
**3.1 alpha 2893b5a6bee1f1185c52d4a46734b2741acbb52c**

> Sample Project: [3.1 Export Nodepath.zip](https://github.com/godotengine/godot/files/2424422/3.1.Export.Nodepath.zip)

This one is tricky to classify.  There is some conflicting behavior, loss of functionality, and an editor error all involved.

There seems to be some issues around handling `export (NodePath)` vars when they are left null.  There is an editor error and it does feel maybe as though a editor error or warning may be needed.

## Editor Error

The context to reproduce this is to create two export vars as NodePath and leave them null.

1. On one of them click the unassignment button.  (This will set it as an empty NodePath.)
2. Then click on the refresh/reset button, which will try to set it to null.

You get this error.

![errors](https://user-images.githubusercontent.com/13004169/46151658-f01b0700-c277-11e8-844c-916849247959.jpg)

## No Refreshing/Reset Option

Not clear if it is related, but at times the refresh button is not an option when you click unassign.  Sometimes it appears, other times not, but can reappear when navigating between editor tools.  When you load the sample project it is likely you won't get a refresh/reset option on these export vars.

## Confusion (Usability)

I was caught off guard by this, because I had long ago used the unassignment button on one of my NodePath export vars, and later in coding I was expecting to compare for nulls to see if they were assigned.  In this way they can either be null or a NodePath with an empty path.

An empty NodePath compares to `""`.  I found that `not my_path` should work in both cases at least.  Yet it feels like it might be worth guarding against.

Maybe disallowing null assignments in script is one way to go about it, or perhaps a warning?

**Comment by slapin** [comment]
I think also NodePath should support filtering by type, like in C++.

**Comment by QbieShay** [comment]
@avencherus you might be interested in #21556

**Comment by avencherus** [comment]
@QbieShay Thanks, had very much the same problem during this.  X)

I did some further investigation this morning.  I will close this issue and break it up a bit, since parts of this ended up being problems with export vars in general, not exclusive to NodePath.  It looks like you have the discussion part covered quite well, so I will avoid duplicating it, and just add to it.
