### ISSUE TITLE
Editor crashes when launching during a Remote Desktop session

### ISSUE THREAD

**Issue by DoubleDeez** [godotengine/godot#22499]
**Godot version:**
3.0.6 Custom Build

**OS/device including version:**
Windows 10 (GTX 1080) (connecting from a Surface Book with windows 10)

**Issue description:**
While connected via Remote desktop, the editor will fail to launch.

**Steps to reproduce:**
1. Connect via Remote Desktop to a PC that has Godot installed
2. Attempt to launch Godot
3. Notice the first popup states "Cannot get Proc Address for CreateContextAttribs"
4. Click OK
5. Notice you get a popup stating "Your system's graphic drivers seem not to support OpenGL 3.3 / OpenGL ES 3.0, sorry :("
6. Pressing OK then closes Godot

**Note:** If you first login directly to the PC, launch godot and then connect via Remote Desktop, The godot editor will work but you still will not be able to launch the game.

**Minimal reproduction project:**
No project needed

Log produced:
```
ERROR: RasterizerGLES3::initialize: Error initializing GLAD
   At: drivers\gles3\rasterizer_gles3.cpp:147
ERROR: RasterizerGLES3::initialize: Your system's graphic drivers seem not to support OpenGL 3.3 / OpenGL ES 3.0, sorry :(
Try a drivers update, buy a new GPU or try software rendering on Linux; Godot will now crash with a segmentation fault.
   At: drivers\gles3\rasterizer_gles3.cpp:157
OpenGL ES 3.0 Renderer: 
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] ???
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Comment by groud** [comment]
That's indeed expected, the message is clear. 

> Try a drivers update, buy a new GPU or try software rendering on Linux; Godot will now crash with a segmentation fault.

Closing.
