### ISSUE TITLE
Request: Syntax Highlight for TODO and FIXME comments.

### ISSUE THREAD

**Issue by ni-code** [godotengine/godot#22495]
Minor feature request. Syntax Highlighting for TODO and FIXME comments.

Screen shoot example of how it looks for rust in atom.

![todo_fixme](https://user-images.githubusercontent.com/10292929/46181826-e4533300-c2bf-11e8-938c-22e95f5dbe92.png)

**Comment by williamd1k0** [comment]
Related #6371

**Comment by ni-code** [comment]
Ups, my search-foo, isn't working as intended. Ty @williamd1k0.
Closing this as duplicate.
