### ISSUE TITLE
Changing a texture to import as an Image still prevents it from being assigned

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#22493]
Godot master 1b63dd83bdf9605affc8e80c2ac1f93f5550ada1
Windows 10 64 bits

Repro steps:
1) Have a project with a PNG file in it, which defaults to import as a texture
2) Have a node with a script on it that export a variable expecting an `Image`
3) Try assigning the PNG to the property using the inspector: notice nothing happens and the property is left empty, which is normal behavior (though a bit odd if you don't know that's how Godot handle mismatching resource type)
4) Now go to the PNG import options, and change it to `import as Image`, and click `Re-import`.
5) Go back to the node, and try to assign the property again: notice it still doesn't work, which is not expected.
6) Restart the editor
7) Try again to assign the image, and notice that it works now. But we should not have to restart the editor.

Note: that could also affect any kind of resource when its type is changed through import settings.

**Comment by KoBeWi** [comment]
In 3.2 (or maybe since 3.1) editor will explicitly ask for restart, which is even worse xd

Also another case similar to #27079
Dropping image could create an ImageTexture automatically.

**Comment by KoBeWi** [comment]
Still valid in 6c173e2

**Comment by KoBeWi** [comment]
This is actually not a bug. I mean, it was a bug and the forced restart was probably added to workaround it. It's impossible to avoid the restart, so the issue can be considered fixed. (the fix is not perfect, but that's another issue)
