### ISSUE TITLE
Editor error and unusual behavior with export vars.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22507]
**Win10 64-bit 3.1 alpha 2893b5a6bee1f1185c52d4a46734b2741acbb52c**

>  Example Project - [3.1 Export Var Reset Error.zip](https://github.com/godotengine/godot/files/2427904/3.1.Export.Var.Reset.Error.zip)

## Problem Code

```
extends Node2D

export (float, 0.1, 1.0, 0.1) var something
```

## Editor Errors

When an export var is null and uses a hint, it will throw an error whenever you try to reset them.  They can no longer be cleared back to null.

![refresh error](https://user-images.githubusercontent.com/13004169/46205050-0ed8d680-c328-11e8-888d-74368c131c76.png)

![refresh error console](https://user-images.githubusercontent.com/13004169/46205055-10a29a00-c328-11e8-80c2-4509f1976a0f.png)

## Unusual Behavior

I noticed when having a float as null, it will show the lowest value in the range of the export hint.  Though nothing is there.  This is misleading.  The output of a print reveals it to still be Null.

![as null](https://user-images.githubusercontent.com/13004169/46204817-2e233400-c327-11e8-8a8c-e4b731356976.png)

![godot_master_2018-09-28_14-05-27](https://user-images.githubusercontent.com/13004169/46204896-8f4b0780-c327-11e8-970e-ae336075ec68.png)

There are also leads to some quirks and confusion with NodePath types.  

Some related topics:
* https://github.com/godotengine/godot/issues/22481
* https://github.com/godotengine/godot/issues/21556

**Comment by DualMatrix** [comment]
I recognize that error from when I was fixing #22419. I think I know what causes this, it has to do with emitting signals with an empty variant as parameter going wrong.

**Comment by DualMatrix** [comment]
@avencherus I've always seen it referred to as the revert button but I wouldn't know if thats "official"

**Comment by avencherus** [comment]
Couldn't readily find a name for it, but good to know that's the consensus word for it.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by avencherus** [comment]
Seems not, perhaps the recent work by @vnen 👍 has fixed it.  The null types will start at the minimum value of the hint or 0 otherwise, and refreshes to these values.  Other types appear to be working cleanly as well.
