### ISSUE TITLE
Small bugs with Save Scene popup

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22509]
**Godot version:**
3.1 2e87703

**OS/device including version:**
Windows 10

**Issue description:**

I don't create 3 separate issues because they seems to be interlinked and there are (probably) easy to solve

- [ ] 1. When I create Node in folder, delete this folder and try again to save a node, location of node is assigned to non-existent folder (which I a little before delete) and any try to save result this bug:

> ERROR: save: Condition ' err ' is true. returned: ERR_CANT_OPEN
   At: scene/resources/scene_format_text.cpp:1468

I think that editor should check if location exist and if not that should choose at the res:// folder

- [ ] 2. If I write the location(not choose by file manager) in the field with res://, the name of the node disappears.

- [x] 3. When I try to save scene without extension, editor show info about non valid extension - I think that will be better if editor will add .tscn to names without extension.

**Steps to reproduce:**

![jfile](https://user-images.githubusercontent.com/41945903/70703572-af6aaa80-1cd0-11ea-86bd-00fbc4fc60ba.gif)

**Comment by spongeboburu** [comment]
https://github.com/spongeboburu/godot/commit/998ab99c8a5781571246880de13bfeabe9a4aeec

This commit does the following in editor_file_dialog.cpp:
- Line 22, I commented the //file->set_text(""); as such, I'm not sure what purpose that line serves.
- Added a yesno dialog if can_delete and not existing.
- The directory is created if confirmed _save_confirm_pressed.

**Comment by KoBeWi** [comment]
> 3. When I try to save scene without extension, editor show info about non valid extension - I think that will be better if editor will add .tscn to names without extension.

This only shows when you have "All Recognized" selected.
