### ISSUE TITLE
Export vars cannot be reset to default.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#22505]
**Godot version:**

3.1 alpha 2893b5a6bee1f1185c52d4a46734b2741acbb52c
3.2.2

**OS/device including version:**

Win10 64-bit

**Issue description:**

A tool script can prevent the revert / reset options from appearing on certain export vars.

**Steps to reproduce:**
1. Assign script as tool script.
2. Create some export vars.
3. Save and then set this scene as the project's main scene.
4. Close and re-open the project.

**Minimal reproduction project:**

The easiest to notice is the integer variable.  Changing it doesn't offer a reset.  Removing the `tool` keyword and reloading will fix the issue.

[3.1 Cannot Reset Export Vars.zip](https://github.com/godotengine/godot/files/2427873/3.1.Cannot.Reset.Export.Vars.zip)

**Comment by KoBeWi** [comment]
Might be related to #33611 somehow.

**Comment by KoBeWi** [comment]
Can't reproduce in 4.0
There an opposite issue now #62363
