### ISSUE TITLE
Editor: Debugger displays wrong class names of object variables

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22519]
You gonna hate me :)

Incorrect type (or class name) displays next to object name in debugger. See fix of issue https://github.com/godotengine/godot/issues/22454
 if it helps.

**Steps to reproduce:**
See screen shots paused on last line of  `_on_Button2_pressed()`
Please note circled red. The `allow` object is of type `Checkbox` and `self` is of type `Button`.

GLES2
![screen shot 2018-09-28 at 4 47 19 pm](https://user-images.githubusercontent.com/930478/46232819-79950c80-c33e-11e8-819a-7dd2cd69d11a.png)

Also show different objects class names when using GLES3

![screen shot 2018-09-28 at 4 53 33 pm](https://user-images.githubusercontent.com/930478/46233048-4901a280-c33f-11e8-8e83-0ec1428e9fb3.png)

Other than that seems great :)

**Comment by akien-mga** [comment]
CC @DualMatrix

**Comment by DualMatrix** [comment]
Yup that's not right, I'll fix this asap.

**Comment by wyattbiker** [comment]
I ve tested this but now shows ObjectID for all objects in both GLES2 and 3. So somehow you're not able to get the Object class and show it in the drop downs next to each name.

**Comment by DualMatrix** [comment]
@wyattbiker. I just made it go back to the previous behaviour(Just showing object). I couldn't figure out how to get the actual name, I still have a theory on how to do it but I havent tested that yet.

**Comment by wyattbiker** [comment]
Ok, could we re-open the ticket plz

**Comment by DualMatrix** [comment]
That is not how it worked in the previous versions I think.

**Comment by wyattbiker** [comment]
Sounds good. Future enhancement. Thanks
