### ISSUE TITLE
Duplication Files/Folders should work same as Nodes

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22510]
**Godot version:**
3.1 2e87703

**OS/device including version:**
Windows 10

**Issue description:**
When I try to duplicate Node I must only choose one or more and click CTRL + D.
Godot add to original name some numbers. I can duplicate as much as I want.

When I try to duplicate File or Folder in File System Dock I must choose only one(If I choose more, only last selected will duplicate) and when I click CTRL + D, I must write the proper name because by default Godot doesn't change name in this popup. When I click Duplicate button, editor lost focus on File System Dock and now point at the some Node from Scene Dock. If I wanna duplicate this file more time, I must again click at the desired file and click CTRL + D. It works a worst than in Scene Dock

**Comment by KoBeWi** [comment]
Somewhat related to #20641

**Comment by randall-fulton** [comment]
Based on @akien-mga's closing comment on #20641, is this something that should be done? That comment specifically calls out that the dialog is desired, whereas this issue would suggest removing the dialog in place of auto-incrementing names. There is a bit of a conflict between those two methodologies for the browser.

**Comment by Calinou** [comment]
Reading the last comment in #20641, it seems the feature's current behavior is intended and won't be changed, so I'll close this.
