### ISSUE TITLE
Signals cannot be added, via Node dock,  one by one

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22511]
**Godot version:**
3.1 2d87703

**OS/device including version:**
WIndows 10

**Issue description:**
When I try more than one signal from node, each time when I add signal, editor change focus from node to script and that's why Node dock is completely clear and I must again select Node to add another signal

**Steps to reproduce:**
https://streamable.com/tp3z9

**Comment by KoBeWi** [comment]
Related to #21950

**Comment by akien-mga** [comment]
Duplicate of #21950.
