### ISSUE TITLE
Saving a Resource with a Script is not (de)serializing the script properties.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#22518]
**Godot version:**
master, dacc3f3

**Issue description:**
Saving a Resource object with a Resource script on it is no longer serializing the properties into the *.tres file. I've tried manually adding a property with a value to the *.tres file (in both the \[resource\] section and \[sub_resource type="GDScript" id=1\] section, but neither of these attempts are properly deserializing the data when loading the object.

**Steps to reproduce:**
Run a scene with a Node that has the script below. Comment out the save operation as needed if tinkering with the *.tres file directly.

    extends Node
    
    class MyResource:
        extends Resource
        var check = 0
    	
    func _ready():
        var res = MyResource.new()
        print(res.check) # prints 0 (yay)
        res.check = 1
        ResourceSaver.save("res://res.tres", res) # file doesn't get this check=1 property anywhere
        res = load("res://res.tres") # if you add it in manually, the check property doesn't get loaded onto the object.
        print(res.check) # errors because 'check' is an invalid index

**Comment by pgruenbacher** [comment]
I believe the entrypoint for this issue is resource_format_binary.cpp. I find this issue to be interesting I'll take a look. Yell at me if I forget to come back to this.

**Comment by pgruenbacher** [comment]
This is an an issue with godot 3.0 too... which makes me wonder if it's not a new issue.

**Comment by willnationsdev** [comment]
@pgruenbacher Wait, what? That can't be right, can it? I know vnen has mentioned using Resource scripts for data before, and I remember testing this stuff out myself a few months ago and it was working. Weird that it'd be a problem for so long and so sporadically usable. It's such a seriously useful feature.

**Comment by pgruenbacher** [comment]
well i mean whatever 3.0 I was on...

@willnationsdev also btw, i did some more testing, I do think "resource.gd" still works. E.g. use a script that extends Resource with var

```
func _ready():
    #var res = MyResource.new()
    #print(res.check) # prints 0 (yay)
	var res = preload("resource.gd").new()
	res.check = 1
	ResourceSaver.save("res://res.tres", res) # file doesn't get this check=1 property anywhere
	res = load("res://res.tres") # if you add it in manually, the check property doesn't get loaded onto the object.
	print(res.check) # errors because '
```

resource.gd 
```

extends Resource
var check = 3
```

**Comment by willnationsdev** [comment]
@pgruenbacher Ahhhh, that's probably why I thought it worked. So it's only the subclass variant of the usage that is broken. That makes a lot more sense. I was like, "I *know* I've done this before!" lol.

**Comment by pgruenbacher** [comment]
so subclass tres output 
```
[gd_resource type="Resource" load_steps=2 format=2]

[sub_resource type="GDScript" id=1]

script/source = ""

[resource]

script = SubResource( 1 )

```

and resource.gd tres output 

```
[gd_resource type="Resource" load_steps=2 format=2]

[ext_resource path="res://resource.gd" type="Script" id=1]

[resource]

script = ExtResource( 1 )

```

**Comment by pgruenbacher** [comment]
I think subclass support just doesn't make sense intuitively or would be bad code design, since the sub class is usually dependent on the parent class, so it doesn't make sense to try to load a subclass resource (which can be loaded from outside the parent class script.) This is a main contributor question...

**Comment by willnationsdev** [comment]
Yeah, that makes a lot of sense. I guess this issue can be closed then, as it was just a misunderstanding on my part.

**Comment by pgruenbacher** [comment]
yea... I don't see an easy way to throw an error message either on a resource extended subclass, so I'll just update the godot-docs maybe where it talks about this.

@akien-mga you can close

**Comment by pgruenbacher** [comment]
@willnationsdev nvm I don't see any docs really covering this other than https://godotengine.org/qa/8139/need-help-with-exporting-a-custom-ressource-type maybe

if you get a custom gdscript resource going, maybe let's paste it as an example for custom gdscript resource? 
@Zylann has one here https://github.com/Zylann/godot_heightmap_native_plugin/blob/39005c42d647f6b1d350194d51bf552a4f7080a2/addons/zylann.hterrain/hterrain_data.gd

**Comment by willnationsdev** [comment]
@pgruenbacher I'll add a PR for a Resource script example in the docs [here](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/resources.html).
