### ISSUE TITLE
AnimationPlayer Autoplay property does nothing.

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#22525]
**Godot version:**
Godot alpha 3.1

**OS/device including version:**
Windows 10 x64

**Issue description:**
using the auto-play property on an Animation or in the editor result in nothing happening 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by vonflyhighace2** [comment]
i'm using the autoplay in the editor and also tried using it through code.can you tell me what steps you used and what version of the engine you are using.

**Comment by DualMatrix** [comment]
All I did was press the Autoplay button left of the Edit button in the AnimationPlayer editor.

**Comment by vonflyhighace2** [comment]
I see that it works if you do it in the editor….Not so much if you do it through code on the other hand.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by vnen** [comment]
When are you setting the auto-play in the code? Maybe the player is already in the tree and already did the check for auto-play, so your code is setting it too late. Might be simpler to just call `play()` directly.

**Comment by vonflyhighace2** [comment]
I call it in the ready function so before anything else updates. And yeah the only work around in code is to use play instead..just thought that putting this issue forward gets some eyes on it


________________________________

**Comment by DualMatrix** [comment]
Even _ready might be too late. I wonder why it's even exposed to GDscript seems only confusing to me.

**Comment by vnen** [comment]
> I call it in the ready function so before anything else updates.

That's my point: maybe it's already too late. If the AnimationPlayer is a child of the node where the script is, then the player will already have called `_ready()` so the auto-play was already checked before you set it.

**Comment by vnen** [comment]
> I wonder why it's even exposed to GDscript seems only confusing to me.

Yeah, autoplay is useful to avoid using code, doesn't make much sense to set it via code (when you can just call `play()` instead). OTOH the exposed property is useful if you are using a script to generate scenes, or adding AnimationPlayer nodes on-the-fly.

**Comment by DualMatrix** [comment]
@vnen Maybe we could add a warning when setting autoplay from script when it's already in the tree?
