### ISSUE TITLE
Array sort_custom should show a warning or error if the function doesn't exist.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#22523]
**Godot version:**
3.0 / 3.1

**Issue description:**
There should be a warning or error message when the `sort_custom` fails because of the function not existing, like in the example below. I had a misspelled function name and it took me a while to figure out why it wasn't sorting.

```GDScript
array.sort_custom(self, "non_existent_function")
```

**Comment by akien-mga** [comment]
Reopening as #22737 had to be reverted for now due to #22833 (which is a consequence of this patch, but due to the other bug #22838).
