### ISSUE TITLE
Possible mistake in 'draw_ring()' in StyleBox

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#22526]
**Godot version:**
 4db2db2

**Issue description:**
Inside the function `draw_ring()` in the class StyleBox, an integer named "rings" is created, giving it a value depending of the result of this: `(border_width[0] == 0 && border_width[1] == 0 && border_width[2] == 0 && border_width[3] == 0) ? 1 : 2;`. But, literally a line below, "rings" is directly set to 2. So which of these are supposed to happen?

Location of the issue: https://github.com/godotengine/godot/blob/4db2db2d6b4cf82c19f4ea96258071f5682dd592/scene/resources/style_box.cpp#L568

**Comment by akien-mga** [comment]
CC @toger5

**Comment by toger5** [comment]
Thank you for pointing that out. I guess the rings = 2; was just a temporary change when it was not fully implemented. And i forgot to remove it since it also works...

I will still make tests, to see if it does work properly with the conditional (initianal) set

**Comment by YeldhamDev** [comment]
@toger5 Any updates?

**Comment by toger5** [comment]
Not yet. If you want though, you can make a pr where its set to 2 always.
I really would like to reimplement the drawing of style boxes with shaders anyways... but there are some limitations with the current implementation of canvas items and shaders...

**Comment by YeldhamDev** [comment]
Sure thing.
