### ISSUE TITLE
Enable jarsigner from openjdk 1.7 support

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2253]
I use the following script to use jarsigner from openjdk 1.7

```shell
rm -f simple-rpg.apk simple-rpg-unaligned.apk simple-rpg-unsigned2.zip simple-rpg-unsigned2.apk
rm -Rf simple-rpg-unsigned
unzip -d simple-rpg-unsigned simple-rpg-unsigned.apk
cd simple-rpg-unsigned
rm -Rf META-INF
zip -r ../simple-rpg-unsigned2.zip *
cd ..
mv simple-rpg-unsigned2.zip simple-rpg-unsigned2.apk

jarsigner -verbose -digestalg SHA1 -sigalg MD5withRSA -keystore ~/android/release.keystore -signedjar simple-rpg-unaligned.apk simple-rpg-unsigned2.apk slapin
/home/slapin/android-sdk-linux/tools/zipalign -v 4 simple-rpg-unaligned.apk simple-rpg.apk
```

Most problems are because Godot doesn't remove signing files in templates
if these are there. You can just drop whole META-INF. Also it is easy to find on the Internet,
that jarsigner from jdk 1.7 requires the following options to work with android:
-digestalg SHA1 -sigalg MD5withRSA
digestalg also might be set to MD5.

**Comment by reduz** [comment]
as far as I've been toold, jarsigner from JDK7 now works, so closing this
