### ISSUE TITLE
Crash when deleting PhysicalBones, and crash when opening file with PhysicalBones

### ISSUE THREAD

**Issue by SneakyMax** [godotengine/godot#22538]
## Crash When Opening Editor

**Godot version:**

3.1 `master` ->  f12cb82e0f7b3348ab678322cf5e729b38861f1e

**OS/device including version:**
Windows 10 Home x64

**Issue description:**
When opening a file with `PhysicalBone`s, the editor immediately crashes.

**Steps to reproduce:**
1. Try to open this project in the editor: [physical-bones-crash.zip](https://github.com/godotengine/godot/files/2430780/physical-bones-crash.zip)

**Known working version (ish):** c6f09fb97b48903f8d9d8d3b030b3b03d0a87e19

## Crash when deleting PhysicalBones

**Godot version:**
3.1 `master` ->  f12cb82e0f7b3348ab678322cf5e729b38861f1e

**OS/device including version:**
Windows 10 Home x64

**Issue description:**
When a physical bone is deleted, and using the Bullet physics engine, a memory-related crash seems to happen. Since the time between the deletion and crash appears to be random, this seems to happen during garbage collection cycles.

**Steps to reproduce:**
1. Download [physical-bones-crash.zip](https://github.com/godotengine/godot/files/2430780/physical-bones-crash.zip)
2. Run the project, wait 5-30 seconds
3. Game window crashes, stack trace appears in editor's console.

However, this happens to me _when I compile `master` myself. I cannot reproduce this when using the [Unofficial Builds](https://hugo.pro/projects/godot-builds/). It would help a lot if someone else could reproduce it too.

Stack trace for me:

```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] btUnionFind::find (c:\dev\godot\thirdparty\bullet\bulletcollision\collisiondispatch\btunionfind.h:107)
[1] btUnionFind::find (c:\dev\godot\thirdparty\bullet\bulletcollision\collisiondispatch\btunionfind.h:107)
[2] btUnionFind::unite (c:\dev\godot\thirdparty\bullet\bulletcollision\collisiondispatch\btunionfind.h:83)
[3] btDiscreteDynamicsWorld::calculateSimulationIslands (c:\dev\godot\thirdparty\bullet\bulletdynamics\dynamics\btdiscretedynamicsworld.cpp:781)
[4] btDiscreteDynamicsWorld::internalSingleStepSimulation (c:\dev\godot\thirdparty\bullet\bulletdynamics\dynamics\btdiscretedynamicsworld.cpp:500)
[5] btSoftRigidDynamicsWorld::internalSingleStepSimulation (c:\dev\godot\thirdparty\bullet\bulletsoftbody\btsoftrigiddynamicsworld.cpp:97)
[6] btDiscreteDynamicsWorld::stepSimulation (c:\dev\godot\thirdparty\bullet\bulletdynamics\dynamics\btdiscretedynamicsworld.cpp:456)
[7] SpaceBullet::step (c:\dev\godot\modules\bullet\space_bullet.cpp:366)
[8] BulletPhysicsServer::step (c:\dev\godot\modules\bullet\bullet_physics_server.cpp:1561)
[9] Main::iteration (c:\dev\godot\main\main.cpp:1826)
[10] OS_Windows::run (c:\dev\godot\platform\windows\os_windows.cpp:2740)
[11] widechar_main (c:\dev\godot\platform\windows\godot_win.cpp:150)
[12] _main (c:\dev\godot\platform\windows\godot_win.cpp:172)
[13] main (c:\dev\godot\platform\windows\godot_win.cpp:184)
[14] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[15] BaseThreadInitThunk
-- END OF BACKTRACE --
```

Attaching a debugger just shows invalid memory access (trying to access a freed pointer).

**Minimal reproduction project:**
[physical-bones-crash.zip](https://github.com/godotengine/godot/files/2430780/physical-bones-crash.zip)

The project has one character, with physical bones generated for the Skeleton. The character is deleted (`queue_free()`) after 1 second. If the character is not deleted, the crash never happens. The crash happens eventually, but not at a reliable point in time.

**Comment by slapin** [comment]
Looks like somebody forgot to remove bodies no longer available from Bullet so you get crash on physics step. Probably they are deleted later so it is timed bug. I think you could debug it by checking physics bone implementation working with physics world.

**Comment by SneakyMax** [comment]
Thanks @slapin! I'll be trying to look into it since it's blocking our game, but somebody like @AndreaCatania could probably find the problem much faster

**Comment by slapin** [comment]
Well, with Godot unless you debug yourself and produce PR the chance for something specific to be fixed is very slim as people have their stuff to do and might not be interested in that particular thing at all. So if you would do some more investigating and provide more info that would increase chances. Crashes are easier at this as you can find exact condition when this happens and full backtrace with all function parameters.

Look at this one for example: 
https://github.com/godotengine/godot/issues/21713 even complete tooling help did not do the job, so I finally had to come along and produce PR in hope that will come to an effect. So try to make your bug more attractive to developers by providing more info.

**Comment by muiroc** [comment]
For info: I tried opening it with 0bc0baff821512ecd9391771b3abd9aa44c7c1ef and the editor crashed after the splash screen
Windows 10 x64

memdelete(joint_data) <- join_data is null

backtrace:
[0] memdelete<PhysicalBone::JointData> (c:\gd\godot\core\os\memory.h:119)
[1] PhysicalBone::set_joint_type (c:\gd\godot\scene\3d\physics_body.cpp:2330)
[2] MethodBind1<PhysicalBone,enum PhysicalBone::JointType>::call (c:\gd\godot\core\method_bind.gen.inc:815)
[3] ClassDB::set_property (c:\gd\godot\core\class_db.cpp:1021)
[4] Object::set (c:\gd\godot\core\object.cpp:422)
[5] SceneState::instance (c:\gd\godot\scene\resources\packed_scene.cpp:252)
[6] PackedScene::instance (c:\gd\godot\scene\resources\packed_scene.cpp:1685)
[7] EditorNode::load_scene (c:\gd\godot\editor\editor_node.cpp:2885)
[8] EditorNode::_sources_changed (c:\gd\godot\editor\editor_node.cpp:543)
[9] MethodBind1<EditorNode,bool>::call (c:\gd\godot\core\method_bind.gen.inc:815)
[10] Object::call (c:\gd\godot\core\object.cpp:968)
[11] Object::emit_signal (c:\gd\godot\core\object.cpp:1254)
[12] Object::emit_signal (c:\gd\godot\core\object.cpp:1311)
[13] EditorFileSystem::_notification (c:\gd\godot\editor\editor_file_system.cpp:1090)
[14] EditorFileSystem::_notificationv (c:\gd\godot\editor\editor_file_system.h:107)
[15] Object::notification (c:\gd\godot\core\object.cpp:980)
[16] SceneTree::_notify_group_pause (c:\gd\godot\scene\main\scene_tree.cpp:960)
[17] SceneTree::idle (c:\gd\godot\scene\main\scene_tree.cpp:510)
[18] Main::iteration (c:\gd\godot\main\main.cpp:1845)
[19] OS_Windows::run (c:\gd\godot\platform\windows\os_windows.cpp:2740)
[20] widechar_main (c:\gd\godot\platform\windows\godot_win.cpp:150)
[21] _main (c:\gd\godot\platform\windows\godot_win.cpp:172)
[22] main (c:\gd\godot\platform\windows\godot_win.cpp:184)
[23] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)
[24] BaseThreadInitThunk
-- END OF BACKTRACE --

**Comment by slapin** [comment]
Do anybody aware of any revision when this did not happen (after addition of physics bones)?

**Comment by muiroc** [comment]
More info: after nullchecking the memdelete, the editor (caa141a1ac630144e441f89689baa1a74bb3bae5) loads, so i run the scene and... it didnt crash! got this warning in the console:
```
WARNING: RigidBodyBullet::assert_no_constraints: A body with a joints is destroyed. Please check the implementation in order to destroy the joint before the body.
     At: modules\bullet\rigid_body_bullet.cpp:442
```
so something must still be done...

**Comment by SneakyMax** [comment]
@muiroc I've been getting those for a while but ignoring them, I didn't think they were related to the crash. It's very strange that you couldn't even launch the editor, since I was able to, and run the game (until it crashed while running).

**Comment by muiroc** [comment]
@SneakyMax no crash (after the null check): I run the scene, there is a blue character, after a while it disappears and get the 15 warnings, the scene run for about 10 minutes. tried about 3 times

The editor crash made sense but I have no idea why it didnt happen before:

the PackedScene::instance & friends eventually called
set_joint_type(JOINT_TYPE_CONE)
there, the condition
if (p_joint_type == get_joint_type())
becomes
if (JOINT_TYPE_CONE == JOINT_TYPE_NONE)
(see definition of get_joint_type(), since joint_data is null, it returns JOINT_TYPE_NONE)

so it doesnt return out of the function, it proceeds,
so it calls memdelete(joint_data)
and memdelete calls the destructor on a null joint_data
crash!

Very weird, that code looks like that since the first commit if im not mistaken...
maybe some compiler settings, dunno

**Comment by muiroc** [comment]
@SneakyMax 
compiled from "x64 Native Tools Command Prompt for VS 2017" with:
scons -j4 platform=windows target=debug tools=yes

cl version:
C/C++ Optimizing Compiler Version 19.13.26129 for x64

debug launched from VS IDE:
C:\gd\godot\bin\godot.windows.tools.64.exe --path C:/gd/bugs/physical-bones-crash/project.godot --editor

dunno, if you are still on 6cbdeed you could try placing a breakpoint in set_joint_type and launch the editor and on break check if joint_data is not null, or it is null and doesnt crash, in my case 0bc0baf the crash happened on the very first call of that method

**Comment by SneakyMax** [comment]
@muiroc  Alright soooo,

```
git clean -fdx
git fetch upstream
git checkout upstream/master
```

Runing x64 Native Tools Command Prompt for VS 2017
`scons -j6 platform=windows target=debug tools=yes vsproj=yes`

Crashes just how you describe, in the exact same spot.

_however_, when I roll back to c6f09fb97b48903f8d9d8d3b030b3b03d0a87e19 (the first working windows build after 6cbdeedf57c7383827416da19b6026e3721f2812), then it behaves how I described in the initial post. Would you mind verifying that @muiroc? I find it very suspicious that the bug I was running into has been fixed by some other commit in the last 8 days.... I'll comb through the history to see if anything pops out at me.

**Comment by SneakyMax** [comment]
It's highly possible that my bug was fixed with the warnings in 2091f204432d58f20a642bf9fab83a6d08a65084 (dealing with the `PhysicalBone` destructor) or maybe c026e3957a815199ee301cdcbaa94698ee4a3705 (`JointData` destructor) in which case, awesome!

But... now it crashes while starting the editor, haha. I'll update the issue. Thanks @muiroc!

**Comment by AndreaCatania** [comment]
The sample project that you provided on the first post is still valid? I'll try to fix it today

**Comment by SneakyMax** [comment]
Yeah @AndreaCatania I've updated the issue description and title, the same project still causes the crash. Would you like me to open a separate issue for the [warnings here](https://github.com/godotengine/godot/issues/22538#issuecomment-426801976)?

**Comment by AndreaCatania** [comment]
yes even if the solution is to remove that issue since Godot handle it safely anyway. But yes open an issue please so I can check it better

**Comment by SneakyMax** [comment]
Update: the original crash just happened for me after the bones were deleted, on f28b032490b183b51c025829a62e294181d38ba2

First time it happened after a minute or two, second time it happened right away.

```
Exception thrown: read access violation.
**btAlignedObjectArray<btElement>::operator[]**(...) returned nullptr. occurred

godot.windows.tools.64.exe!btUnionFind::find(int x) Line 107
	at c:\dev\godot\thirdparty\bullet\bulletcollision\collisiondispatch\btunionfind.h(107)
godot.windows.tools.64.exe!btUnionFind::unite(int p, int q) Line 83
	at c:\dev\godot\thirdparty\bullet\bulletcollision\collisiondispatch\btunionfind.h(83)
godot.windows.tools.64.exe!btDiscreteDynamicsWorld::calculateSimulationIslands() Line 781
	at c:\dev\godot\thirdparty\bullet\bulletdynamics\dynamics\btdiscretedynamicsworld.cpp(781)
godot.windows.tools.64.exe!btDiscreteDynamicsWorld::internalSingleStepSimulation(float timeStep) Line 500
	at c:\dev\godot\thirdparty\bullet\bulletdynamics\dynamics\btdiscretedynamicsworld.cpp(500)
godot.windows.tools.64.exe!btSoftRigidDynamicsWorld::internalSingleStepSimulation(float timeStep) Line 97
	at c:\dev\godot\thirdparty\bullet\bulletsoftbody\btsoftrigiddynamicsworld.cpp(97)
godot.windows.tools.64.exe!btDiscreteDynamicsWorld::stepSimulation(float timeStep, int maxSubSteps, float fixedTimeStep) Line 456
	at c:\dev\godot\thirdparty\bullet\bulletdynamics\dynamics\btdiscretedynamicsworld.cpp(456)
godot.windows.tools.64.exe!SpaceBullet::step(float p_delta_time) Line 366
	at c:\dev\godot\modules\bullet\space_bullet.cpp(366)
godot.windows.tools.64.exe!BulletPhysicsServer::step(float p_deltaTime) Line 1561
	at c:\dev\godot\modules\bullet\bullet_physics_server.cpp(1561)
godot.windows.tools.64.exe!Main::iteration() Line 1832
	at c:\dev\godot\main\main.cpp(1832)
godot.windows.tools.64.exe!OS_Windows::run() Line 2740
	at c:\dev\godot\platform\windows\os_windows.cpp(2740)
godot.windows.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 150
	at c:\dev\godot\platform\windows\godot_win.cpp(150)
godot.windows.tools.64.exe!_main() Line 172
	at c:\dev\godot\platform\windows\godot_win.cpp(172)
godot.windows.tools.64.exe!main(int _argc, char * * _argv) Line 184
	at c:\dev\godot\platform\windows\godot_win.cpp(184)
[External Code]
```

**Comment by SneakyMax** [comment]
#22823

**Comment by muiroc** [comment]
@SneakyMax 
Sorry, for now can only confirm that with cff89fc4e4f2ceb577b5f7a119d98cb22d41ea44 the editor crashes, same backtrace as my first post

Only difference is, in one run the editor scene view did show up (empty) for a split second, but this is most likely not that relevant

**Comment by SneakyMax** [comment]
@AndreaCatania any luck reproducing the crash happening to me? Sucks that muiroc can't reproduce it

**Comment by oisincar** [comment]
I'm still getting this sadly :/. Godot (Current commit at time of posting: c487cce6d0af608173508b10d4d3a37f8f0a9907) is crashing upon opening a scene with PhysicalBones in it. Also, as above, if I revert back to c6f09fb it works again. I'd really appreciate any ideas on how to get around it.

Stacktrace:
```
/proc/self/maps:
00400000-04267000 r-xp 00000000 103:04 3444082                           /home/oisincar/Devcrap/WizLiz/godot2/bin/godot.x11.opt.tools.64.mono
04466000-04467000 r--p 03e66000 103:04 3444082                           /home/oisincar/Devcrap/WizLiz/godot2/bin/godot.x11.opt.tools.64.mono
04467000-0447e000 rw-p 03e67000 103:04 3444082                           /home/oisincar/Devcrap/WizLiz/godot2/bin/godot.x11.opt.tools.64.mono
0447e000-04496000 rw-p 00000000 00:00 0 
0617e000-21326000 rw-p 00000000 00:00 0                                  [heap]
40068000-40109000 rw-p 00000000 00:00 0 
40bc3000-40bd3000 rwxp 00000000 00:00 0 
40eaf000-40ebf000 rwxp 00000000 00:00 0 
410cb000-41181000 rwxp 00000000 00:00 0 
412ee000-412f0000 r-xs 00000000 103:04 2623388                           /tmp/.glG9YZbL (deleted)
41448000-41458000 rwxp 00000000 00:00 0 
7f8534000000-7f8534021000 rw-p 00000000 00:00 0 
7f8534021000-7f8538000000 ---p 00000000 00:00 0 
7f8538000000-7f8538021000 rw-p 00000000 00:00 0 
7f8538021000-7f853c000000 ---p 00000000 00:00 0 
7f853c000000-7f853c021000 rw-p 00000000 00:00 0 
7f853c021000-7f8540000000 ---p 00000000 00:00 0 
7f8540000000-7f8540021000 rw-p 00000000 00:00 0 
7f8540021000-7f8544000000 ---p 00000000 00:00 0 
7f8544000000-7f8544021000 rw-p 00000000 00:00 0 
7f8544021000-7f8548000000 ---p 00000000 00:00 0 
7f8548000000-7f8548021000 rw-p 00000000 00:00 0 
7f8548021000-7f854c000000 ---p 00000000 00:00 0 
7f854c000000-7f854c021000 rw-p 00000000 00:00 0 
7f854c021000-7f8550000000 ---p 00000000 00:00 0 

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
```

**Comment by hedgehog90** [comment]
Problem still exists.
I'd really appreciate it if someone could look into this.

**Comment by AndreaCatania** [comment]
Tomorrow is holiday here. Tomorrow is fixed, promised!

**Comment by AndreaCatania** [comment]
![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/8342599/47841910-694bd380-ddbb-11e8-9b89-d692fae3f7df.gif)
FIXED! :)

**Comment by hedgehog90** [comment]
> ![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/8342599/47841910-694bd380-ddbb-11e8-9b89-d692fae3f7df.gif)
> FIXED! :)

When it hits the floor why does your ragdoll crumple but mine vibrates like crazy? :(
#19002

**Comment by AndreaCatania** [comment]
I think that you should tweak the joint to make it more stable. However I'll check to see how it can be improved

**Comment by and3rson** [comment]
I can confirm that in my model all the bones also move chaotically... Possibly caused by #24836
