### ISSUE TITLE
DDS loader not adhering to specification.

### ISSUE THREAD

**Issue by benaveld** [godotengine/godot#22530]
In v3.0.6 mono its appears that the DDS loader loads the height as width and vise versa.
In the specification: https://docs.microsoft.com/en-us/windows/desktop/direct3ddds/dds-header

The change need is in modules/dds/texture_loader_dds.cpp

I found this bug while trying to use a DDS file and it not appearing correctly. Switching the width and height fixed it.

**Comment by akien-mga** [comment]
Fixed by #22683.
