### ISSUE TITLE
Godot have problem with some characters in Windows username while exporting

### ISSUE THREAD

**Issue by Ryptun** [godotengine/godot#2254]
My Windows username is "Rafał". While exporting to Android Godot can't find template APK, but I can find this file in filesystem. Godot don't see "ł" character

**Comment by bojidar-bg** [comment]
This seems to be a long-standing problem with non-ascii characters in paths.

**Comment by reduz** [comment]
i fixed issues regarding to this many times, do they still persist?
how do you reproduce it?

**Comment by bojidar-bg** [comment]
@reduz ~ If you are asking me, I haven't seen it from a long time, but I just remember the many bug reports...

**Comment by akien-mga** [comment]
Bug confirmed by #4423.

**Comment by akien-mga** [comment]
Testing on Linux to export a game to `/home/akien/tmp/Rafał`, it worked fine even though the "ł" was not displayed in the FileDialog, likely because I haven't configured a custom font with better UTF-8 support. So it's likely an issue with the file access on Windows.

**Comment by akien-mga** [comment]
I believe this bug was fixed by 1c541a2. It was actually not a Windows issue but Android-specific, as the latter uses zip_io for exporting.

We'll soon have a 2.0.4 release which will among other things contain this fix, it would be great if you could test and confirm that the bug is fixed.
