### ISSUE TITLE
Export from command line hangs if target file exists.

### ISSUE THREAD

**Issue by murphy-slaw** [godotengine/godot#22547]
**Godot version:**
3.1.alpha.calinou.c3bb4ed

**OS/device including version:**
OS X 10.13.6
MacBook (Retina, 12-inch, 2017)

**Issue description:**
When exporting a project from the command line, the editor hangs if the target output file already exists.

**Steps to reproduce:**
(For this example, 'godot3.1' is a symlink to Godot.app/Contents/MacOS/Godot)
Using the attached project:
 * Do a CLI export to the build/ directory 
```
$ godot3.1 project.godot --export "HTML5" ./build/index.html
arguments
0: godot3.1
1: project.godot
2: --export
3: HTML5
4: ./build/index.html
Current path: /Users/kmurphy/Desktop/Export Test
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 615
$ ls build
index.html  index.js    index.pck   index.png   index.wasm
```
The project is successfully exported, and the godot editor quits when the export is complete.

* Repeat the process, leaving the existing export in place
```
$ godot3.1 project.godot --export "HTML5" ./build/index.html
arguments
0: godot3.1
1: project.godot
2: --export
3: HTML5
4: ./build/index.html
Current path: /Users/kmurphy/Desktop/Export Test
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 615
```
At this point, the editor hangs and does not exit, showing the "beachball" cursor. Ctrl-C in the terminal that launched the export successfully forces the editor to exit.

* Remove the contents of build/
```
rm build/*
```

* Try to export again.
```
godot3.1 project.godot --export "HTML5" ./build/index.html
arguments
0: godot3.1
1: project.godot
2: --export
3: HTML5
4: ./build/index.html
Current path: /Users/kmurphy/Desktop/Export Test
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 615
$ ls build
index.html  index.js    index.pck   index.png   index.wasm
```
The export succeeds.

**Minimal reproduction project:**
[Export Test.zip](https://github.com/godotengine/godot/files/2431257/Export.Test.zip)

**Comment by akien-mga** [comment]
It appears to be fixed in the current master branch.
