### ISSUE TITLE
AnimationNodeTransition doesn't work when it's controlled from code

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22550]
**Godot version:**
`master` / 0de8309b2

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
When changing `current` parameter of `AnimationNodeTransition` node from code (`parameters/[name]/current`), it only works for the first time.

**Steps to reproduce:**
Run the example project, and press any key to switch animation. The cube is supposed to change its direction each time a key is pressed, but after the first time it stops moving.

**Minimal reproduction project:**
[AnimationTest.tar.gz](https://github.com/godotengine/godot/files/2431443/AnimationTest.tar.gz)

**Comment by mysticfall** [comment]
Potentially related to #22236.

**Comment by slapin** [comment]
A problem is that there is no in-depth tutorial or explanation how to make all this stuff work, so it is mystery how it is supposed to work. Somehow it works from editor - might be worth checking what editor does for understanding...

**Comment by mysticfall** [comment]
I think I've spent enough time with `AnimationTree`'s API to understand how it's supposed to work from the user's side.

If I'm not mistaken, most of the functionalities of each animation node types are supposed to be controlled by changing their 'parameters', as nodes themselves do not expose such APIs anymore (for which I opened another issue, since I believe it's far better to have them back).

I found that `SetParameter` doesn't work (filed another issue for that), but at least invoking `AnimationTree.Set()` using the full path for parameters work for certain types (i.e. `BlendSpace2D`, `Blend`, and etc), so I believe it's supposed to work for other types like `OneShot` (which doesn't, so I opened another issue for that) and `Transition` nodes.

**Comment by mysticfall** [comment]
On a side note, I agree that we lack proper documentation on how to use the API, and more importantly, I think it's not stable enough to be used by general public.

I'm afraid we have too little time left before the upcoming 3.1 release to fix all the major issues regarding `AnimationTree`, so maybe we should warn our users that it's still an experimental feature until it becomes more usable.

**Comment by slapin** [comment]
This is fascinating how Godot community works - such a great feature added and nobody was able to make it work, not even tried.
Well, I have some success working with AnimationTree from GDScript.
I get to node from animation tree and call its APIs and not use props.
I use the following code:
```gdscript
# you get one of AnimationNodeAnimation, AnimationNodeBlendTree, AnimationNodeStateMachine
# AnimationNodeBlendSpace1D/2D, etc.
var tree_root = $AnimationTree.get_tree_root()

```
Look at tps demo code for more real life example. You CAN use nodes directly and get access to them and this is how it is supposed to work for humans. Leave property magic for animation editor.

**Comment by mysticfall** [comment]
Manipulating animation nodes without having to deal with parameters is a different matter for which I already reported an issue here: #21399

**Comment by mysticfall** [comment]
@guilhermefelipecgs You were right, and it indeed fixed the problem!

I didn't realize it's an zero based index, since everywhere in editor it's a sequence of positive integer like this:
![image](https://user-images.githubusercontent.com/2367032/50382420-f50a1e00-06e1-11e9-9534-a097e0afb315.png)
![image](https://user-images.githubusercontent.com/2367032/50382431-38648c80-06e2-11e9-9f9f-1e7c5b0a78b0.png)
It's a bit confusing, but I'm glad that I can now make a relevant part of my project working correctly. Thanks!

@akien-mga If it's indeeded how it's supposed to work, I think we can close this issue.

**Comment by reduz** [comment]
I guess the default label assignment should begin from 0..

**Comment by Adinimys** [comment]
So I was just recently testing the new AnimationTree and I got stuck on this labeling issue. I was setting parameters from code using 1 as the base of the index because of the labeling even though I was supposed to use 0.
I simply changed the labeling by changing line 843 in animation_blend_tree.cpp to remove the +1. This way the labeling starts at zero in the editor as in the code.

So my question was. Is it the desired behavior ? Simply offset the label indexing to make it match the code ?

**Comment by slapin** [comment]
I never had this issue because I never used default labels, as these are
supposed
to be renamed to something meaningful.
I agree this can be confusing to some newbies looking at AnimationTree. But
as they get used to it (like, in 30-40 minutes) that is quickly forgotten
as a problem. This issue will evntually be solved I guess as was noticed by
developers, but it is definitely not high priority
