### ISSUE TITLE
Tileset:  Expose bitmask flags (as a property?)

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#22555]
**Godot version:**
3.0, 3.1

**Issue description:**
This is a feature request.  Currently, as far as I can tell, the only way to get/set the bitmask flags for an autotile in a tileset is to manually address them by their path in the resource using get()/set().  This is a bit obscure since it's not documented and there's a possibility that compatibility breaks between versions.  

For people who wish to use the autotiling features by generating their own atlas at runtime, it would be helpful to expose the bitmask flags to the user, identifying by name or index in the tileset as an argument if it is a function, or as a key specified to a property.  The return type can be the raw array as it exists currently, but perhaps a more straightforward return type would be a Dictionary of <Vector2, int>.

Some possible syntaxes:
```gdscript
var tileset = Tileset.new()
var id = 0
tileset.create_tile(id)
#[add code to set texture and other basic boilerplate here]

var pos = Vector2(x,y)  #Might be more ideal to have separate x,y for nested loop, but...

#Func syntax
tilset.get_bitmask_flags(id)   #Returns entire data structure, or Dict:<Vector2,Int>
tilset.get_bitmask_flag(id, pos.x, pos.y)  #Returns int
tilset.set_bitmask_flags(id)   #Requires data structure in native format
tilset.set_bitmask_flag(id, pos, value)  #Returns some kind of error enum

#Property syntax
tileset.bitmask_flags[id]  #Returns entire data structure, but as Dict:<Vector2, Int>
tileset.bitmask_flags[id][pos]   #Returns int
```

**Comment by CyanideGourmet** [comment]
Is this still not implemented?

**Comment by kotelifelif** [comment]
I am beginner in Godot Engine, that is why I have a question. You write: "tilset.get_bitmask_flags(id)". I think that "tileset.autotile_get_bitmask(id)" return the same. Do I think right?

**Comment by nobuyukinyuu** [comment]
I believe it is.  Closing the issue then.
