### ISSUE TITLE
Error compiling for android ( gradle build error : no toolchains found in the NDK toolchains folder...)

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot#22569]
**Godot version:**

master
https://github.com/godotengine/godot/commit/204d39b297a71fd43827828e6bc1818284393ed9

**System information:**

OS  Linux 4.15.0-29deepin-generic amd64
Gradle 3.4.1

**Issue description:**

I tried to build the source code for android.
i've already installed all requirements besides the last NDK , and i've set SDK and NDK folders to my environements variables .
the issue stated is in the picture below: 
![gradle build](https://i.imgur.com/ce6KuY5.png)

**Comment by volzhs** [comment]
I guess you downloaded android-ndk-r18.

it's known issue for r18.
https://github.com/android-ndk/ndk/wiki/Changelog-r18#known-issues

> This version of the NDK is incompatible with the Android Gradle plugin version 3.0 or older. If you see an error like No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android, update your project file to use plugin version 3.1 or newer. You will also need to upgrade to Android Studio 3.1 or newer.

currently, godot uses gradle build 2.3.3.
so I suggest you to use older version like r16. (I'm using it)

**Comment by akien-mga** [comment]
What would it take to upgrade to the latest gradle version? Would we lose compatibility for some older toolchains?

**Comment by volzhs** [comment]
not sure. I have not researched about it.
and, IIRC, there was an error while compiling when updating to latest.

**Comment by MrZak-dev** [comment]
@volzhs i'm still getting the same error using NDK 16  i also updated gradle to the last version 4.10.2.
@akien-mga  the problem that `mips64el-linux-android` is deprecated in NDK 18 so found it in NDK v16 but still getting the same error though.

**Comment by MrZak-dev** [comment]
Error solved updating android to the last version and updating Gradle plugins besides using NDK v16

**Comment by ricardoalcantara** [comment]
How do I get NDK v16, I am having this same problem.

**Comment by ricardoalcantara** [comment]
I've found it. I guess it's still a bug because I had to download the NDK from google older packages, this at least could be documented. Just my humble opinion.

**Comment by akien-mga** [comment]
In the current *master* and *3.0* branch it should build fine with latest NDK.

**Comment by MrZak-dev** [comment]
@akien-mga i tried it but it gave me the same error so i decided to go with ndk 16 , it worked .
