### ISSUE TITLE
Time scale is incorrect in Mac

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#22564]
**Godot version:**

Master (3ee657e)
MacOSX

**Issue description:**

Time scale is incorrect in Mac

Fps: always display 1
Process: display 16.XX
![2018-09-30 11 55 16](https://user-images.githubusercontent.com/2070604/46259495-c8909c80-c50c-11e8-974f-df6fe9e2ba60.png)
(it is 60 FPS before)

and input cursor flash very quick
![2018-09-30 11 55 40](https://user-images.githubusercontent.com/2070604/46259498-cdede700-c50c-11e8-80ac-87b4b88a1143.png)

3D view movement is very quick too (Mouse Right Click + WSAD)

**Steps to reproduce:**
use master version
do movement in 3D view
or try to input in line edit

**Comment by Faless** [comment]
#22563
