### ISSUE TITLE
Moving a ClippedCamera through a StaticBody causes the editor to crash

### ISSUE THREAD

**Issue by CollinOmmen** [godotengine/godot#22577]
Commit Hash: 9c0cc0db63f61cd71a2a735519dc7816973e5b7e

The editor crashes when I perform the following steps from a new project:

1) For the new scene, select "3D Scene" as the root node.
2) Add a StaticBody as a child node to the Spatial node.
3) Add a CollisionShape as a child node to the StaticBody.
4) Set the CollisionShape's Shape to "New BoxShape".
5) Add a ClippedCamera as a child node to the Spatial node.
6) Move the ClippedCamera by dragging the directional arrows with the mouse.

I then get the following dump to the console:

`CrashHandlerException: Program crashed`
`Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues`
`[0] btCollisionWorld::objectQuerySingleInternal (c:\godot\thirdparty\bullet\bulletcollision\collisiondispatch\btcollisionworld.cpp:661)`
`[1] btCollisionWorld::objectQuerySingle (c:\godot\thirdparty\bullet\bulletcollision\collisiondispatch\btcollisionworld.cpp:614)`
`[2] btSingleSweepCallback::process (c:\godot\thirdparty\bullet\bulletcollision\collisiondispatch\btcollisionworld.cpp:1089)`
`[3] BroadphaseRayTester::Process (c:\godot\thirdparty\bullet\bulletcollision\broadphasecollision\btdbvtbroadphase.cpp:229)`
`[4] btDbvt::rayTestInternal<BroadphaseRayTester> (c:\godot\thirdparty\bullet\bulletcollision\broadphasecollision\btdbvt.h:1054)`
`[5] btDbvtBroadphase::rayTest (c:\godot\thirdparty\bullet\bulletcollision\broadphasecollision\btdbvtbroadphase.cpp:264)`
`[6] btCollisionWorld::convexSweepTest (c:\godot\thirdparty\bullet\bulletcollision\collisiondispatch\btcollisionworld.cpp:1162)`
`[7] BulletPhysicsDirectSpaceState::cast_motion (c:\godot\modules\bullet\space_bullet.cpp:180)`
`[8] ClippedCamera::_notification (c:\godot\scene\3d\camera.cpp:747)`
`[9] ClippedCamera::_notificationv (c:\godot\scene\3d\camera.h:179)`
`[10] Object::notification (c:\godot\core\object.cpp:980)`
`[11] SceneTree::_notify_group_pause (c:\godot\scene\main\scene_tree.cpp:960)`
`[12] SceneTree::iteration (c:\godot\scene\main\scene_tree.cpp:473)`
`[13] Main::iteration (c:\godot\main\main.cpp:1770)`
`[14] OS_Windows::run (c:\godot\platform\windows\os_windows.cpp:2735)`
`[15] widechar_main (c:\godot\platform\windows\godot_win.cpp:150)`
`[16] _main (c:\godot\platform\windows\godot_win.cpp:172)`
`[17] main (c:\godot\platform\windows\godot_win.cpp:184)`
`[18] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)`
`[19] BaseThreadInitThunk`
`[20] RtlValidSecurityDescriptor`
`-- END OF BACKTRACE --`

It also may be worth noting that upon opening the project, I get the following warning:

`WARNING: Control::grab_focus: This control can't grab focus. Use set_focus_mode() to allow a control to get focus.`
`     At: scene\gui\control.cpp:2067`

**Comment by muiroc** [comment]
Can't repro in current master c51caa3, maybe was fixed by #22156 ?

![repro_setup](https://user-images.githubusercontent.com/10036337/46283687-6a4bd400-c575-11e8-9502-34245dfd51bc.png)

**Comment by AndreaCatania** [comment]
@muiroc Yes it was already fixed.
I'm closing it
