### ISSUE TITLE
Automatic switch to viewport in background when playing a scene (regression)

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#22573]
**Godot version:**

Godot 3.1 3ee657e

**OS/device including version:**

Xubuntu 16.04.5 LTS, Nvidia GTX 750 Ti

**Issue description:**

Reopen of #16357, regression from 9c7e647, also not correct fix for #20075

If **any node selected** and you play a 2d or 3d scene, the editor view tab automaticaly switches to 2d or 3d viewport (respectively) no matter the viewport you're currently using (gdscript editor included!).
![autoswitch](https://user-images.githubusercontent.com/1049442/46262275-c2a4b680-c520-11e8-9bb9-bd6e4539a627.gif)

About #20075: if Node **not selected**, remote node still shows in inspector dock.
![remote](https://user-images.githubusercontent.com/1049442/46262298-465ea300-c521-11e8-8700-6e510fa67880.gif)

**Comment by akien-mga** [comment]
CC @ordigdug

**Comment by akien-mga** [comment]
Thanks for the report, I've reverted 9c7e647 for now and I'll reopen #20075.
