### ISSUE TITLE
android export dialog is so fucking broken :(

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2258]
Android export dialog reprorts random noicy errors preveting pressing export button.
Export works perfectly fine with command line, but not ffrom dialog, which reports new crap each time.
It is beyound fixing, all this errors preventing pressing export button should be disabled,
they don't help in any way, and it is better to report error during export than before it.
Most annoying thing is inability to save export.cfg with that.

**Comment by reduz** [comment]
please be more specific, this dialog works fine for a lot of people
including me so if it doesn' t for you I suggest  you write down what fails
for you

**Comment by reduz** [comment]
the export process also aborts on errors so it will not report errors
afterwards

**Comment by slapin** [comment]
1. Too many false positives with missing files, it can't find files now and
then
and disables export button. and there is no way to reset it. I had to
locally patch it to make it usable.

2. There is no direct control over export.cfg saving, and you never know if
it was saved or not, especially if it
reports missing files (which are really there.

3. With these errors, command line export works fine without problems.
Errors are reported randomly.
This is very annoying experience. Most of time it reports missing custom
debug template package,
and sometimes reports missing custom release package.

4. There is no ability to provide commandlines for tools, which forces me
to re-build .apk after Godot.

5. For some reason Godot produces invalid META-INF contents and reports
errors on verification. I signed by hand,
no problems are there. The way I export to Android can be see there:
https://github.com/okamstudio/godot/issues/2253

**Comment by slapin** [comment]
I have to use the following patch  to keep myself sane. Hope will be useful to someone else.
```patch
diff --git a/tools/editor/project_export.cpp b/tools/editor/project_export.cpp
index e38c672..596ffd5 100644
--- a/tools/editor/project_export.cpp
+++ b/tools/editor/project_export.cpp
@@ -344,7 +344,7 @@ void ProjectExportDialog::_notification(int p_what) {
 void ProjectExportDialog::_validate_platform() {
 
        get_ok()->set_disabled(true);
-       button_export->set_disabled(true);
+       button_export->set_disabled(false);
        TreeItem *selected = platforms->get_selected();
        plat_errors->hide();
        if (!selected) {
```

**Comment by silverkorn** [comment]
BTW @slapin, watch you your language. (Title) :laughing:

**Comment by akien-mga** [comment]
Please open one bug request per precise issue, this kind of rant-issue is not really helpful.

**Comment by slapin** [comment]
This issue was reported by many people; The point is that dialog should be
rewritten from scratch, it is too broken to cope with.

**Comment by akien-mga** [comment]
But that's pointless to have in an issue. How to do you expect any contributor to do a PR that will fix "android export dialog is so fucking broken :("? It's like opening an issue to say "3D performance sucks compared to UE4". Pointless.

Then if you have ideas on how to make the export dialog better, even just a visual mockup, please open a well-title issue for each with a precise description of your idea.

**Comment by slapin** [comment]
The mockup is - drop all tests and rewrite them, run tests as single batch
on export, even if tests still fail, allow still exporting.
A problem - on all my setups (GNU/Linux 64 bit, Debian 8, Fedora 23, Ubuntu
12.04) the GUI Android export doesn't work with random errors (files
missing, etc.)
The export from command line works on all installations. All the settings
are correct and double-checked. The failed tests deisable Export button
which prevents the use of
GUI exporter at all. The architecture of export GUI is messy and file
itself is "write-only". The only way is to drop and start from scratch.

**Comment by slapin** [comment]
Also, until this is fixed, you better not close it, as it puts problem
under carpet. Also, the workaround is provided in this bug, which might
help someon and reference another people with this problem
to possible solution.

**Comment by silverkorn** [comment]
@slapin 
Told you that the title was not going to help you. :wink:

**Comment by slapin** [comment]
This title shows well what I feel when I see the actual code and result of
its "work" :( It is beyond good and evil.
