### ISSUE TITLE
Issues when change size of dynamic font

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22581]
**Godot version:**
3.1 80d6bb7

**OS/device including version:**
Windows 10

**Issue description:**
When size of dynamic font is set to 0, this error occur: 

> ERROR:  _reload_cache: Condition ' cache_id.size < 1 ' is true.
   At: scene/resources/dynamic_font.cpp:680

Also when

I try to change size of this font via inspector, click at value and move mouse, then other issue was occured:
> ERROR: _bitmap_to_character: Condition ' mw > 4096 ' is true. returned: Character::not_found()
   At: scene/resources/dynamic_font.cpp:483

it also capture mouse and freeze editor which now take 1,8 GB RAM(probably because size of font is set at round 65535)

**Steps to reproduce:**
1. Open Minimal Project
2. Select Label
3. Go to Custom Fonts -> settings, click at the size and  change value by moving mouse

**Minimal reproduction project:**
[font_test.zip](https://github.com/godotengine/godot/files/2433181/font_test.zip)

**Comment by akien-mga** [comment]
Sorry, wrong issue number.

**Comment by chepulis** [comment]
Hi! I ran into a font size limit of 255 on 3.1.2. Needed 370, couldn't set it. I was advised to leave a comment here. Whoever thought that 255 is a reasonable limit missed my case :—) I'd advise limit of 1024, or even larger. Not sure what's the point in having one anyway.

In case you ask, my game is vertical mobile 1280 wide, 2D+keep-width, involves some modernist typography that sometimes overflows out of camera (i come from graphic design background, we're weird like that). I might at some point consider using font up to full-screen height.

**Comment by akien-mga** [comment]
@chepulis You can set the `size` property from a script to any value, the property hints are only restricting values set through the inspector. As you can see from the OP, setting too high values actually triggers issues (huge lag, errors), so it can't be unlimited.

Anyway, #35411 should raise the max value for the inspector to 1024.
