### ISSUE TITLE
RichTextLabel width changes on changing the window size when using the `2d` stretch mode due to font oversampling

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#22580]
**Godot version:** 3.1 80d6bb7

**Issue description:** The width of a RichTextLabel's text relative to the window changes on resizing with the following conditions:

1. The font is a DynamicFont
2. Dynamic Font Oversampling is on
3. The window stretch mode is 2D or Viewport

This does not happen with Labels! Default screen size on top, slightly resized window on the bottom. The first line is the Label, the second is the RichTextLabel: 
![image](https://user-images.githubusercontent.com/35355161/46272346-ae5fba00-c51e-11e8-9027-bde28e932b79.png)

The Label's width does change slightly, but it's much less egregious:
![image](https://user-images.githubusercontent.com/35355161/46272505-55445600-c51f-11e8-87e9-8de0823dd634.png)

I would expect the RichTextLabel text to be the same as a Label and the value reported by `font.get_string_size()`...

**Minimal reproduction project:** [FontTest.zip](https://github.com/godotengine/godot/files/2432762/FontTest.zip)

**Comment by KoBeWi** [comment]
Still valid in 3.2.2 rc4

On master the window viewport scaling doesn't seem to work, so it's not possible to test this properly.

**Comment by nihiluis** [comment]
looks especially bad with pixel fonts:

![image](https://user-images.githubusercontent.com/24858082/123659828-60915100-d833-11eb-80b2-1e4685cd9ed6.png)

has anyone found a workaround? or just not use the RichTextLabel node?

**Comment by Calinou** [comment]
> looks especially bad with pixel fonts:
> 
> ![image](https://user-images.githubusercontent.com/24858082/123659828-60915100-d833-11eb-80b2-1e4685cd9ed6.png)
> 
> has anyone found a workaround? or just not use the RichTextLabel node?

You can set **Char** spacing in the DynamicFont to 1 or 2. It should make fonts look closer to how they would in a Label.

**Comment by bitbrain** [comment]
This is also an issue for me.

**Comment by Listwon** [comment]
> This bug is likely due to RichTextLabel performing a different kind of rounding for font metrics compared to Label.

You were close, it was an issue with assigning float values to integer variables :) My [PR](https://github.com/godotengine/godot/pull/52752) fixes this issue, but I still have edge case where the last character from CJK font is not wrapped to the next line like in Label (so there is still some tiny difference in calculation).

![rich_text_label_issue2](https://user-images.githubusercontent.com/1554127/133733543-b06e71c1-db89-4e94-9c2e-9270f9c99be7.jpg)

And before the fix (Labels on the left, RichTextLabels on the right)
![rich_text_label_issue](https://user-images.githubusercontent.com/1554127/133733576-7a86dab8-be67-47ea-8e1f-d2d98634afc1.jpg)

Try switching to 1280x720 in this MRP:
[render_text_bug.zip](https://github.com/godotengine/godot/files/7183091/render_text_bug.zip)

**Comment by akien-mga** [comment]
Fixed by #52752.
