### ISSUE TITLE
Ability to set feature tags in editor 

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#22587]
Custom feature tags can be used to signify demo builds, builds for specific distribution platforms (Steam), etc. There seems to be no easy way to test feature tags short of exporting the project, which makes testing such things (ie. testing the demo build) unnecessarily time-consuming.

**I request an ability to set feature tags in editor.**

It can be kind of worked-around by wrapping `OS.has_feature(name)` in custom code, but it does not help with resource overrides.

Should there be such feature already, please interpret this request as "Add custom editor feature tags to docs".

**Comment by Calinou** [comment]
I'll close this in favor of https://github.com/godotengine/godot-proposals/issues/373, which is more detailed.
