### ISSUE TITLE
Moving file to other file cause "Error moving"

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22586]
**Godot version:**
3.1 80d6bb7

**OS/device including version:**
Windows 10

**Issue description:**
When I try to move file and by mistake I put it on another file instead folder, an error "Error moving: res://icon48.png" occurs but only on list and grid view. 

In tree view, which works as I expect, when I try to move a file on another file, only red sign is showing without any error.

**Steps to reproduce:**
1. Move one file to another in each filesystem view 

https://streamable.com/82mpt

**Comment by akien-mga** [comment]
Fixed by #22623.
