### ISSUE TITLE
Editor caret_blink_speed default setting (0.5) is much too fast

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22599]
**Godot version:**
3.1 alpha
Mac OS X, High Sierra

**Issue description:**

In editor/editor_settings.cpp

`	_initial_set("text_editor/cursor/caret_blink_speed", 0.5);`

Seems to blink 6 times a second on the Mac. Not sure if it affects Windows as well. Maybe someone could check the default rate there. 

On my system the setting that works is 6.0 which gives about a blink per second (I believe thats the default blink rates on most systems)

By way of research, in 3.0 the setting is 0.65 and blinking seems correct.

**Comment by akien-mga** [comment]
>  3.1 alpha

What's that? I'm pretty sure both this issue and #22594 are invalid and fixed already in the current master branch c2abf1a4 (and were only valid for a day or so and a handful of commits), so you can imagine that giving information on what commit you built would be useful :)

**Comment by akien-mga** [comment]
See #22564.

**Comment by wyattbiker** [comment]
I will try again. I search for caret_blink_speed and did not find an issue, but here is the version I have.

![screen shot 2018-10-01 at 5 00 50 pm](https://user-images.githubusercontent.com/930478/46315497-a2fea400-c59b-11e8-8050-eb9221250dca.png)

**Comment by wyattbiker** [comment]
I just pulled #d1a5127 from Master. Both fixed. sorry for the confusion. Please close.

**Comment by akien-mga** [comment]
No problem :) Just make sure to mention the commit hash in bug reports if you are using a nightly or self-compiled build, as many issues have a very short lifetime where they are introduced one day and fixed the next (such as this issue with the physics clock on macOS).
