### ISSUE TITLE
Android godot reports 0 surfaces for mesh data

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2259]
Android godot reports 0 surfaces for mesh data from MeshInstance.
On PC it behaves normally. Any ideas?

**Comment by okamstudio** [comment]
This is expected. OpenGL ES 2.0 does not allow retrieval of mesh data once
you gave it to the API


On Sat, Jul 11, 2015 at 1:20 AM, Sergey Lapin <notifications@github.com>
wrote:

> Android godot reports 0 surfaces for mesh data from MeshInstance.
> On PC it behaves normally. Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2259>.
>



-- 

*OkamStudio*

**Comment by slapin** [comment]
Probably a workaround is possible, as manipulation of mesh material is
useful feature,
and I think it is quite possible to get these data using Godot API instead
of GLES.

**Comment by akien-mga** [comment]
Is a workaround as mentioned by @slapin possible, or should we just close this one as wontfix?

**Comment by reduz** [comment]
no, workaround is not possible, closing. This will eventually work in GLES3 backend.
