### ISSUE TITLE
Lights with shadow enabled break in GLES2 

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#22591]
**Godot version:**
 c2abf1a

**OS/device including version:**
Manjaro GNU/Linux, Nvidia GeForce 820M, Nouveau driver

**Issue description:**
It affects both SpotLight and OmniLight, spitting this error out:
`drivers/gles2/rasterizer_gles2.cpp:111 - GL ERROR: Source: OpenGL	Type: Error	ID: 12	Severity: High	Message: GL_INVALID_VALUE in glGetUniformLocation`

- **Shadow disabled**:
![screenshot at 2018-10-01 12-48-07](https://user-images.githubusercontent.com/30739239/46299691-4a69df80-c578-11e8-951b-e590af470768.png)

- **Shadow enabled**:
![screenshot at 2018-10-01 12-44-45](https://user-images.githubusercontent.com/30739239/46299546-f101b080-c577-11e8-85a9-fff01e1b5775.png)

**Comment by avril-gh** [comment]
**can confirm on windows** 7 GT720 it looks like on image above and spams 
```
drivers\gles2\rasterizer_gles2.cpp:111 - GL ERROR: Source: OpenGL
Type: Error ID: 1281 Severity: High
Message: GL_INVALID_VALUE error generated.
Program handle does not refer to an object generated by OpenGL.
```

**Comment by YeldhamDev** [comment]
@akien-mga Nope, not fixed at all.

**Comment by volzhs** [comment]
I got the same error with @avril-gh

**Comment by akien-mga** [comment]
CC @jfmichaud31

**Comment by ippan** [comment]
have same problem:
GPU: Intel(R) UHD Graphics 617
OS: Mojave 10.14.2
Godot Version: 7d22e

in console, have a error message:
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:3178.

and I check the result in 
GLenum status = glCheckFramebufferStatus(GL_FRAMEBUFFER);

status value is 36059 (GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER)

**Comment by reduz** [comment]
I tested this on NVidia, Intel and AMD and I can't reproduce your errors.
Feel free to actually make test cases and submit them or there is nothing I can do.

**Comment by reduz** [comment]
Actually, I think this is two separate issues. The one reported by @avril-gh is a shader error, this may be fixed (please test again). There is a bug related to spotlight shadows that is not fixed, though.

**Comment by reduz** [comment]
No, nevermind, spotlight shadows seem to work fine on GLES2, and the original bug report is clearly fixed.
If you can trigger the shader compilation error again please open a new issue and a test project.
