### ISSUE TITLE
Preview Scene In Separate Tab

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#22609]
i'm pretty bad at explaining things, but tried to do a mock up in paint/photoshop. i remember reading some facebook posts last month or so of people saying their game is performing very bad when previewing a scene in the editor. since godot will open  a  new window and if you got your  huge 3d scene loaded already, i think this could be a great solution to that. it  would be totally optional too. what do u guys think?

![1231](https://user-images.githubusercontent.com/36117592/46338848-25ac5100-c5e6-11e8-81c3-6eaa0bf08d6f.png)
![12311](https://user-images.githubusercontent.com/36117592/46338849-25ac5100-c5e6-11e8-8516-7b28d3cfeda7.png)

**Comment by akien-mga** [comment]
If I'm not mistaken, what you're asking for is not simply previewing scenes, but running the whole game/main sccene (or, when using the relevant run options, the current scene or a custom scene).

That implies running a project somehow in the existing instance instead of creating a new instance, which is far from trivial.

That's what #13354 aimed to achieve, but was closed as technically infeasible:

> I will be closing this PR given time passed and the technical infeasibility to do this.
>
> Instead, I suggest the following course of action:
>
> 1. Find a way to optionally  embed the game window in the editor. This is pretty difficult to do with OpenGL, but should be considerably easier to do once we port to Vulkan, due to low level access to the swapchain and image data.
> 2. Add an option to the editor, to clone an existing 2D or 3D viewport and put the game there, so debugging and moving around the game scene is possible. This needs to be discussed well on how it would work UX wise.
> 
> This should eventually solve those who want a bit better debugging into whathever is going on in the 3D side of the game while running.

**Comment by KoBeWi** [comment]
The user deleted their account so there's low chance for response to the usual copy-paste message.

So I'm just leaving a note that we are moving proposals to [proposals repository](https://github.com/godotengine/godot-proposals/), so if someone is interested in this feature, a new proposal should be created over there.
