### ISSUE TITLE
Profiler in 3.0.6 not always working and sometimes does't update graph

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22607]
**Godot version:**
3.0.6 (it works with GLES 3 in 3.1 master)

**OS/device including version:**
Windows 10

**Issue description:**
When I run Profiler and game, sometimes profiler freeze in some frame.
Sometimes update current frame counter but graph is frozen.

**Steps to reproduce:**
1. Create node2D
2. Run this scene 
3. Run profiler

![jfile](https://user-images.githubusercontent.com/41945903/70704149-b6de8380-1cd1-11ea-83f0-424af737d086.gif)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by qarmin** [comment]
Profiler still have a lot of issues, but this seems to be fixed.
