### ISSUE TITLE
My own template does not work

### ISSUE THREAD

**Issue by dengtao49** [godotengine/godot#22608]
Recently I try to build my own custom template because of I have modified the godot engine a little bit. 
However, it seems not work and it shows error like:
![20181002041319](https://user-images.githubusercontent.com/8159513/46336684-8b560880-c5f9-11e8-9a7f-ab8adf6a549e.png)
Does anyone know what is going on, and How to fix this kind of problem. The version is 3.0.5 stable

**Comment by akien-mga** [comment]
I'm sorry but there's no way we can help you without *any* information on:
- the diff of the changes you made
- how you're compiling the engine
- the project you're running (there are obviously errors in some of your scenes referencing missing files)
- how you're running the project

Moreover, this issue tracker is for engine bugs and not user support, so please look for support on some of the other discussion community channels like the Q&A, forum, Facebook or Discord: https://godotengine.org/community
