### ISSUE TITLE
VR does not display

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#22616]
Godot 3.1 alpha 
Win 7 64 bits
HTC Vive 

I try running VR demo(Steam VR launched and VR games works)
using those lib [https://github.com/GodotVR/](url)

It doesn't launch VR, there is  only a 3D window in the desktop  is displaying the scene with a static camera.  It looks like Godot can't call SteamVR that is already launched.

The project was running fine with previous Godot versions.

**Comment by akien-mga** [comment]
> Godot 3.1 alpha

Could you be more specific?

**Comment by BastiaanOlij** [comment]
If you are using the OpenVR module you can download from the asset library to try the demo it doesn't work with Godot 3.1, only with Godot 3.0. It will tell you in the logs that you need a newer version of the module. At that point it will not be able to initialize the interface and you will indeed end up with a static camera rendering the scene.

To get OpenVR to work in Godot 3.1 you will need to compile the module from source including downloading the necessary OpenVR SDK.

Once 3.1 is officially released we will add a 3.1 version of the module in the asset library.

**Comment by DevMagicLord** [comment]
What VR Godot supports out of the box ? 

I'll wait for the official 3.1 and will download the module from the asset library.

**Comment by BastiaanOlij** [comment]
> What VR Godot supports out of the box ? Occulus, Htc Vive ?

Currently we have a driver for the Oculus SDK (Rift) and for OpenVR (anything that OpenVR supports so Rift, Vive, Windows MR, PiMax, list goes on) and OpenHMD (also various headsets)

**Comment by BastiaanOlij** [comment]
@DevMagicLord just download the binary from here:
https://github.com/GodotVR/godot_openvr/tree/master/demo/addons/godot-openvr

That should work with 3.1

**Comment by akien-mga** [comment]
Assuming that it works when using the 3.1 plugin. Please open an issue on the godot_openvr repo if there are still issues.
