### ISSUE TITLE
Function for when tree is complete

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#2261]
LIke _ready, but parents are also guaranteed to exist, because the root node is ready.

**Comment by bojidar-bg** [comment]
@romulox-x ~ Maybe you can do something similar by sending some bubbling event (IDK exactly how), and listening for it from every child?

**Comment by reduz** [comment]
you can already get this, check for:

Node.NOTIFICATION_INSTANCED

**Comment by vnen** [comment]
@reduz `NOTIFICATION_INSTANCED` is not bound for GDScript.

**Comment by vnen** [comment]
Will reopen this since `NOTIFICATION_INSTANCED` is not yet available in GDScript.
