### ISSUE TITLE
GLES2/WebGL1 scene.glsl shader linking error

### ISSUE THREAD

**Issue by muiroc** [godotengine/godot#22631]
**Godot version:**
4d693fc

**OS/device including version:**
Windows 10, Firefox 62.0.2, Chrome 69.0.3497.100 through default Angle backend (dx11 on HD4000)

**Issue description:**
SpatialMaterial/ShaderMaterial fails linking, so, scene.glsl

error:
SceneShaderGLES2: Program linking failed:
index.js:4 Uniforms with the same name but different type/precision: camera_matrix

**Notes:**
so in [vertex]
precision highp float;
precision highp int;

and in [fragment]
precision mediump float;
precision highp int;

temporarily reverting precision specifiers in index.js
```javascript
	function _glShaderSource(shader, count, string, length) {
		var source = GL.getSource(shader, count, string, length);
		var patched_source = (source
			.replace("precision mediump float", "precision highp float")
		);
		GLctx.shaderSource(GL.shaders[shader], patched_source)
	}
```
links ok

**Comment by reduz** [comment]
@eska014 I guess that means uniforms used in both places need to forcefully specify precision
