### ISSUE TITLE
TileMap Collision

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2263]
func _on_BulletColli_body_enter( body )

The body is always a TileMap, is there any way to get the real Node?

bullet hits wall -> body == wall 
AND NOT, bullet hits wall -> body == TileMap

**Comment by bojidar-bg** [comment]
@AlexHolly BTW, The body is the tilemap itself :smile: (Like if you have a staticBody with many,many colliders)

@AlexHolly You should use Tilemap.world_to_map to get the position of the tile and Tilemap.get_cell afterwards to get the (ID) of that tile.

**Comment by AlexHolly** [comment]
I need the real object and not just a name, is there any function to get the node?

body_object  = magicTileMap.get_node(id)

func _on_BulletColli_body_enter( body ):	
	if body.get_name() == "TileMap":
		var pos = body.world_to_map(get_pos())
		var id = body.get_cell(pos.x,pos.y)
		var body_name = body.get_tileset().tile_get_name(id)
		# body_object = ???
	if body_object .get_name().begins_with("BrickColli"):
		body_object .get_parent().hit(damage)

**Comment by bojidar-bg** [comment]
@AlexHolly As far as I see you did most of it! Here is that same code, with the changes outlined in the comments:
````Python
body_object = magicTileMap.get_node(id)

func _on_BulletColli_body_enter( body ):

if body.get_name() == "TileMap":
  var pos = body.world_to_map(get_pos())
  var id = body.get_cell(pos.x,pos.y)
  var body_name = body.get_tileset().tile_get_name(id)
  
  if body_name.begins_with("BrickColli"): 
    # You already have the name of the tile, it is in body_name!
    # "BrickColli" should be the name of the tile (the name of the sprite node in the tileset scene)
    body.hit(damage) # Well, you are trying to 'hit' the tilemap, right?
````

That's what you are trying to do, right?

@AlexHolly ~ BTW, you can surround your code blocks with \`\`\`\` (that's 4 \`-s), so it will look better :smile:

**Comment by AlexHolly** [comment]
This looks somehow wrong it woul'd probably work if my TileMap had a function hit, but hit is only in my Brick Node.

This is my project [HelloGodot](https://github.com/AlexHolly/HelloGodot)

**Comment by bojidar-bg** [comment]
@AlexHolly It's impossible to call the hit function of the Sprite (in the tileset), because the tilemeap _does not_ create real nodes (AFAIK)! Currently I see two solutions:

1. Move the hit function to the TileMap, and make it accept three params: x (of the tile), y (of the tile) and damage. You are perfectly capable of keeping the amount of life left for each tile in an array/dictionary.
2. (Maybe much easier to implement..) Remove the TileMap part completely! Just have a Node2D with many (instanced) children :smiley: 

Note that there is no best solution. It all depends of the use case. If you have one big tilemap (think tetris/terraria) I think that the second solution will be better. Otherwise, if you have many small tilemaps (say have many houses/spaceships/etc. made out of tilemaps) then I would go with the first solution.

**Comment by AlexHolly** [comment]
Solution 2 is already implemented if you start the game you will see it, the problem in this solution is that it is pretty hard to make changes remove a Node(Tile) or create new in the editor always ctrl+D...

The dictionary solution woul'd be hard to manage if it get more complicated.

So the same "Build a Map Editor functions" without the TileMap woul'd be great...
I think i'm not the first who's looking for such a functionality.

**Comment by bojidar-bg** [comment]
@AlexHolly ~ It is possible to make an "in-game" editor that will generate .scn files (Or even better: generate .youCustomFormat levels, that will store the position and the type of each node (nothing more will be needed to reconstruct the level)).

Also check [dynadungeons](https://github.com/akien-mga/dynadungeons).

**Comment by AlexHolly** [comment]
dynadungeons is also using the same functionality with seperate TileMaps i think it is not user friendly, you have to switch to the "Indestructable"-TileMap to remove a specific Indestructable-Tile it's like working with layers... without the function to work on all layers at once.

It is probably good for the performance to use TileMaps but for someone who doesn't care about that right now (someone who is new to godot or has enough resources) it woul'd be very nice to have such a "in-game" editor(same build functions as in TileMap with one differance, it is creating Notes and not just sprites into a selected Scene/Node).

btw. thanks, i learned a few things.

**Comment by bojidar-bg** [comment]
@AlexHolly Maybe you should close this issue and continue the discussion in IRC/HelloGodot repo?
