### ISSUE TITLE
export verts per frame value to gdscript

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2264]
Please export verts per frame vaule to gdscript, this is very helpful for production-debugging

**Comment by reduz** [comment]
what is verts per frame?

**Comment by slapin** [comment]
Number of vertices actually drawn on last frame.

**Comment by slapin** [comment]
The one which is available on performance tab

**Comment by reduz** [comment]
oh you can already do this:

VisualServer.get_render_info(VisualServer.INFO_VERTICES_IN_FRAME)
