### ISSUE TITLE
Mouse locking in viewport while dragging sprites into an AnimatedSprite 

### ISSUE THREAD

**Issue by DaRealNim** [godotengine/godot#22640]
**Similar issues**
#11893
#9890

**Godot version:**
3.0.stable.official

**OS/device including version:**
Windows 10 on an Asus laptop
CPU: Intel Core i7 Quad Core 2.20Ghz, 
GPU: Nvidia Geforce GTX 560M
RAM: 16gb

**Issue description:**
When dragging sprites imported in Godot from the filesystem panel to the AnimatedSprite frames panel, the mouse sometimes teleport to the middle of the viewport when it is supposed to enter the frames panel, and from that point, impossible to move it. Any attempts to do so result in the mouse teleporting in the middle of the screen again. It doesn't happen every time, but like every two or three sprites I try to drag and drop, which is really annoying, since the only way to fix it for me is to ALT+F4 out of Godot, and restart it...
This issue is very similar to the two ones listed at the beginning of the post, except it doesn't occur in the same circonstances.

**Steps to reproduce:**
Specified above

**Comment by whatsmynameagain** [comment]
It happens when you drag the sprite over the increase/decrease buttons next to the "Speed (FPS)" field.
![where](https://user-images.githubusercontent.com/43839098/46454140-3fcb6800-c77b-11e8-907e-6242c0b46055.jpg)

**Comment by DaRealNim** [comment]
> It happens when you drag a sprite over the increase/decrease buttons next to the "Speed (FPS)" field.
> ![where](https://user-images.githubusercontent.com/43839098/46454140-3fcb6800-c77b-11e8-907e-6242c0b46055.jpg)

Nice, thank you! That doesn't solve the problem but at least I know how not to encounter it now ^^.

**Comment by Jose-Moreno** [comment]
@DaRealNim Can confirm this. Just found this issue in Godot v3.0.6 (Steam) under Windows. I've been following a similar issue (mouse cursor locks in the middle of the screen) for a long time and that one was recently fixed, so to be sure I also tested v3.1 Alpha 4 and this issue has been fixed :tada: 
I recommend you test that version for this issue using an empty project (unless you want to convert your current projects) to confirm that it's fixed for you. :slightly_smiling_face:

**Comment by DaRealNim** [comment]
@Jose-Moreno Ah, it's nice to hear this is fixed in alpha 3.1! Thank you for the update :D. I don't have my pc right now, but as soon as I have it I'll test it and close this issue if everything is fine 👍

**Comment by AgentAvis** [comment]
@DaRealNim 
Well, did you test it?

**Comment by emptyhead** [comment]
Confirmed working in 3.1 Beta 2.
@whatsmynameagain : amazing find with what was causing that bug. I couldn't find a way to consistently reproduce and was about to give up and try another engine. Thankfully I can now continue learning with the docs and tutorials.

**Comment by akien-mga** [comment]
Thanks for the update, closing as fixed then.
