### ISSUE TITLE
[C#] Consider loosening generic guard on GetNode<T> extension method

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22658]
**Godot version:**
`master` / 0de8309b2

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
The current signature of `Node.GetNode<T>` extension method is as below which works quite well for most cases : 
```csharp
public T GetNode<T>(NodePath path) where T : Godot.Node
```
However, if your project relies heavily on abstraction, chances are high that it'd include various interfaces which would be implemented by multiple nodes. In this scenario, we can't use `GetNode<T>` to look up such a component by its interface since the method restricts its generic parameter to be a descendant of `Godot.Node`.

We can solve the problem if we could change the signature as below:
```csharp
public T GetNode<T>(NodePath path) where T : class
```
One may argue that it would damage type safety, but as long as the method blindly casts to whatever type the user provides, there's always a chance that the resulting node is not a descendant of the type `T` even with the more strict generic guard. (i.e. invoking `GetNode<RigidBody>` to return a `MeshInstance` node).

More over, it's generally considered a good practice to code around interfaces rather than implementations, and abstract classes are there to provide base implementations rather than public API contracts.

And it's not always possible to make all implementations of a service to derive from a common abstract class due to the language's limitation of not allowing multiple inheritance. (i.e. item type `A` inherits from `RigidBody` while item `B` from `Spatial`, but you can't make `B > A` even though `RigidBody` > `Spatial`).

I encountered this issue while I was migrating a code which relies on my own implementation of `GetNode<T>` to the standard one. I'm not sure if I should just rename my version as `GetComponent<T>` and keep using it or change the default implementation as suggested above, so I'd like to see how other C# users think about the issue.

**Comment by KellyThomas** [comment]
I have bumped into this limitation before and perform traditional casts to interfaces to work around it.

I support relaxing the guard type, the pragmatic advantages outweigh the loss of formal correctness.

**Comment by zochris** [comment]
Should this only apply to `GetNode` or should all getters (`GetParent`, `GetOwner`, …) be updated?

**Comment by KellyThomas** [comment]
There is a similar constraint applied with `GD.Load<T>()` that could be relaxed in a similar manner.

https://github.com/godotengine/godot/blob/master/modules/mono/glue/Managed/Files/GD.cs#L68

**Comment by neikeq** [comment]
This was changed in #22760. There was a regression (#22765) which was tackled by #22769.

**Comment by mysticfall** [comment]
Great, thanks!

**Comment by aaronfranke** [comment]
I don't understand, can someone provide a test case for which it works with `where T : class` and breaks with `where T : Node`?

**Comment by neikeq** [comment]
@aaronfranke When you have nodes that implement interfaces, you can cast `Node` to the interface type, which is what wasn't working with `GetNode<T>`:

``` C#
interface IFoo {
    void Bar();
}

class MyNode : Node, IFoo {
    void Bar() {}
}

// Non-generic and we do the cast
(MyNode)GetNode("..."); // OK
(IFoo)GetNode("..."); // OK

// Generic which takes care of casting
GetNode<MyNode>("..."); // OK
GetNode<IFoo>("..."); // Compiler error (IFoo doesn't inherit Node)
```

It was failing with the constraint `where T : Node` because `IFoo` doesn't inherit `Node`. Hence why we changed it to accept any reference type with `where T : class`.
