### ISSUE TITLE
Screen freezes in the splash screen in GLES2

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#22656]
**Godot version:**
d675d04

**OS/device including version:**
Manjaro GNU/Linux, Nvidia GeForce 820M, Nouveau driver

**Issue description:**
This started to happen somewhat recently, but when in the splash screen (both in the editor and games), the screen temporally freezes if in GLES2 mode.

**Comment by williamd1k0** [comment]
Maybe related to #21551

**Comment by OFTekk** [comment]
Same problem here with android devices. Godot version 3.1.alpha2 (official build). When used ProceduralSky in environment, android app freezes (or stay) at splash screen (Samsung Galaxy J5 and J3) or shows white screen with some artifacts (Nvidia Tegra K1 tablet).

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by YeldhamDev** [comment]
Nope. Closing it.
