### ISSUE TITLE
Mouse cursor invisible after adjusting shader uniforms via editor

### ISSUE THREAD

**Issue by Cschlaefli** [godotengine/godot#22652]
**Godot version:**

Commit 723e2e9654615fcfd858786d687d22b9fdfc1fd6

**OS/device including version:**

OS: Fedora Linux 4.18.9-200.fc28.x86_64 , Doubt it's GPU related.

**Issue description:**

What happened: Adjusting shader parameters in the editor while the shader code is updating, and the cursor is hidden to adjust the value, causes the cursor to be stuck in the hidden/unusable state until restarting the program.
Expected : Cursor should reappear if the the parameter changes while the value is being changed.

**Steps to reproduce:**
Create a shaderMaterial on a node.
Create a Shader resource.
Open shader editor, add a uniform float and a working fragment() to the shader.
Click and drag the the shader uniform in the Shader Param section of the inspector using the mouse, immediately after making changes to the shader code that update it or cause throw errors.

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/2439966/test.zip)

Side note:
Not reproducible in 3.0 because you can't have both Shader Params in the inspector and the Shader code editor open simultaneously.

**Comment by allkhor** [comment]
**Godot version:**
Godot master 89f8b84, alpha 1, 2.
**OS/device including version:**
Xubuntu 16.04.5 LTS, Nvidia GTX 750 Ti

Reproduced with DynamicFont.
![mouse_bug](https://user-images.githubusercontent.com/1049442/49478393-daaef400-f849-11e8-9881-83b3dfcb5bcd.gif)
[mouse_cursor_bug.zip](https://github.com/godotengine/godot/files/2646416/mouse_cursor_bug.zip)

**Comment by reduz** [comment]
This was fixed in master, I see the fix applied and I can no longer reproduce it so closing.
Please reopen if you can reproduce it.
