### ISSUE TITLE
Progress bar UI elements no longer accept float values (regression)

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#22655]
**Godot version:**
3.1 alpha hash dd1e38cd

**OS/device including version:**
Win10 64 bit; 32 gigs RAM; Nvidia GTX 1060 6GB GPU; Ryzen 2700X CPU.

**Issue description:**
It used to be possible for use a float to add or subtract the value in a progress bar (I was using them as a visual display for things like health). For some reason, they now only accept integer inputs so they no longer work in my project. You can't even type in a float value in the _value_ field in the inspector.

**Steps to reproduce:**
Create a progress bar and write a small script to constantly subtract a float value from it (such as 0.005). The progress texture will not move.

Is this by design? If it is, how are we supposed to use the bars now?

**Comment by spongeboburu** [comment]
Hi there Ace!

I checked the sources first thinking it might have been related to another issue, but it turns out it's simpler than that.

Looking at the source code I discovered that if "step" is > 0 then it will get rounded to the nearest step.
Setting step to zero should allow you to enter decimal values.

Perhaps zero would be a more sensible default/starting value for step.

**Comment by Ace-Dragon** [comment]
So that was the issue then. I don't know if it's a new field or not, but if there's going to be any migration notes that come with the official 3.1 release, this should be noted.

**Comment by spongeboburu** [comment]
I don't know if step is a new field or if the default value has changed. Changing the default to 0 should fix this problem.

**Comment by DualMatrix** [comment]
This was a change made in #22405 Previously `step` was just ignored sometimes.

**Comment by Ace-Dragon** [comment]
> This was a change made in #22405 Previously `step` was just ignored sometimes, which didn't make a lot of sense.

Well, it is my opinion that when the default value changes, it shouldn't change values for any node currently in the scene tree (but only apply for newly created nodes).

**Comment by akien-mga** [comment]
But the default didn't change, a bug was fixed. Controls that expect a float-based step should define not, not expect int steps not to work due to a bug :)

**Comment by aaronfranke** [comment]
> You can't even type in a float value in the value field in the inspector.

Be sure that you're not being affected by https://github.com/godotengine/godot/issues/21874 (which was fixed, but be sure to test again).

**Comment by spongeboburu** [comment]
If I'm reading DualMatrix correctly I think the "new" behaviour could have been induced by the fact that someone corrected the step rounding, the default value had nothing to do with it.
