### ISSUE TITLE
AnimationPlayer timeline snap is snapping relative to previous time values.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22663]
**alpha 3.1 45842c0**

> Sample Project: [3.1 Anim Timeline Snap Issue.zip](https://github.com/godotengine/godot/files/2440818/3.1.Anim.Timeline.Snap.Issue.zip)

Currently the AnimationPlayer snapping is basing its next snap on the previous position of the keyframe.  In previous versions of Godot (snapping/step) was relative to the entire timeline.  The time slider is at least still snapping to these values.

Unless this is a design change?  But I don't feel that's the case, since it seems to make things very difficult.

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/13004169/46393492-2defb380-c6ee-11e8-9a8a-1ba9ea5438ff.gif)

Here you can see the time slider is on a 0.25 snap, but the second keyframe at 0.20 (it's value before I changed the snap size), wants to leap over to 0.45.

**Comment by avencherus** [comment]
@groud Is there something new to the snap that I might be missing?

**Comment by groud** [comment]
> @groud Is there something new to the snap that I might be missing?

I never worked on that part of the code, sorry.

**Comment by avencherus** [comment]
No problem, it occurred to me to double check, in case there was something new.  Thanks for taking a look.  X)
