### ISSUE TITLE
Color alpha values are not preserved even when named xxx-alpha

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2268]
Color alpha values are not preserved even when named xxx-alpha. Have to edit scene evry time, which is tedious...

**Comment by romulox-x** [comment]
Some more context about what you're doing would be useful.  What color value are you editing?  Is it not importing the color's alpha correctly when you (re)import a scene?

**Comment by akien-mga** [comment]
@slapin Ping.

**Comment by slapin** [comment]
This issue still persists with current master

**Comment by akien-mga** [comment]
> This issue still persists with current master

Well my ping was about answering the question that @romulox-x asked, I guess I should have been more direct, sorry.

**Comment by slapin** [comment]
Never seen a fix for this one
