### ISSUE TITLE
Can't save script editor themes

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#22695]
**Godot version:**
Godot custom build caa141a1ac630144e441f89689baa1a74bb3bae5

**OS/device including version:**
Manjaro 64bit 

**Issue description:**
Can't save theme.
![image](https://user-images.githubusercontent.com/19930870/46436433-6b981f00-c776-11e8-92e5-44d855b85590.png)

**Steps to reproduce:**
Try to save the theme.

**Comment by Paulb23** [comment]
If you're clicking on `Save Theme` it uses the currently selected colour theme in `Editor Settings --> Text Editor --> Color Theme`as the name. By default the engine prevents you from saving them as reserved keywords, "Adaptive", "Default" and "Custom". You instead need to use `Save Theme As`.

**Comment by akien-mga** [comment]
It should probably fallback to "Save Theme As" if the current theme is derived from a reserved keyword one?
