### ISSUE TITLE
blinking hints

### ISSUE THREAD

**Issue by danilojr** [godotengine/godot#2269]
Hi!

I have noticed that sometimes the hints are flashing on the screen. I could not even track down the problem, this starts to happen after a period of time in the engine.

I did a build of git-master (mingw x64) and noticed the same problem.

I did a quick video:
https://youtu.be/eVIOTsRWEus

Godot stable release 1.1

windows 7 ultimate x64 sp1
i7, 16GB ram, nvidia gtx750 (driver 353.30)

Thanks!

**Comment by AlexHolly** [comment]
+1
windows 7

**Comment by danilojr** [comment]
The problem does not happen in recent builds.
