### ISSUE TITLE
Find results list uses a very small font

### ISSUE THREAD

**Issue by k7771911** [godotengine/godot#22692]
**Godot version:**

v3.1.alpha.custom_build.344a453

**OS/device including version:**

macOS Mojave

**Issue description:**

Search results use a very small font size compared to the rest of the interface, maybe retina display related, see below

![e1709dea-384b-4929-b21d-3dd0a80014a7](https://user-images.githubusercontent.com/38134085/46430952-280aca00-c710-11e8-84d4-b690ffaa7d80.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
CC @Calinou
