### ISSUE TITLE
High DPI Support

### ISSUE THREAD

**Issue by Felbo** [godotengine/godot#227]
I'd like to look into supporting High DPI displays, in particular "Retina" on OS X.

Does anyone at Okam have access to the original artwork for the default UI theme? It would assist with creating higher resolution assets.

**Comment by cesarizu** [comment]
Thanks for your work on this! Is it possible to expose this on the settings screen so it can be changed if not detected correctly? I'm thinking of the case of Linux where, more often than not, the screen density is not reported correctly.

**Comment by bdero** [comment]
+1 for this. Here's a screenshot of godot in gnome3 on a macbook:
![](http://i.imgur.com/a6xYiLC.png)

**Comment by reduz** [comment]
It's likely not too difficult to implement HiDPI if all the icons in
tools/editor/icons are fixed and upscaled to look nice in hd, problem is
i'm not able to test, only make it look big..

**Comment by reduz** [comment]
by test i mean detect resolution, etc. I seriously need a hidpi monitor to
test this

**Comment by reduz** [comment]
Where I live, a 4k monitor is about 1500usd

**Comment by akien-mga** [comment]
Related to #20 which seems to be Retina-focused. Not closing as a duplicate just yet as I'm not sure if general HDPI support and Retina support have the exact same solution.

**Comment by akien-mga** [comment]
See also a hi-res artwork collection for the UI here: #264

**Comment by mcanders** [comment]
As a temporary fix while we wait for full support you can at least make the text readable by generating larger .fnt font files in godot and setting the global and text editor fonts.  I've been using dejavu sans 24pt for global and dejavu sans mono 28 pt for the text editor with decent success.  The only issue this creates is that some of the text in popups goes outside of the bounds of the popup window.  But pretty much everything is still readable/usable.

**Comment by DimitriyPS** [comment]
I subscribe, it is really important.
Samsung ATIV Book 9 Plus, 13.3, 3200*1800

**Comment by calumk** [comment]
+1 for important

**Comment by adolson** [comment]
I think a hidpi setting is also useful for people using Godot on a Steam Machine-like setup (sitting on a couch, looking at a TV). I do this a lot, and for the most part, using larger fonts works well. But some parts of the UI are messed up, like when I go to make a new project for example, some buttons disappear behind text entry fields. You can see what I mean in this vid: https://dl.dropboxusercontent.com/u/17898384/godothidpi.mp4

PS: calumk?! Good to see you're around the Godot world, still!

**Comment by mcanders** [comment]
For menus that get cut off, I just tab into the obscured buttons.  In the case of the new project menu, I just hit tab a couple of times then enter.  Not an ideal solution, but a solution nonetheless.

**Comment by reduz** [comment]
We'll be getting a macboocpro soon, so we´ll be able to hack on this

**Comment by adolson** [comment]
@mcanders I know how to use Tab. That works, obviously, but it's still trial and error as the buttons are usually hidden behind other stuff, and so I can't even see which button is which. Look at the video for an example. Which button is Create, and which one is Cancel? I can tell you I have hit Cancel several times. It's not a major issue in this particular dialog, but there are others in other parts of the editor where it is a lot more of a problem, and hitting the wrong button or option blindly isn't going to be a good time.

**Comment by Hanul** [comment]
+1 plz !

**Comment by vnen** [comment]
Done by 9b1f823! :tada:

**Comment by mcanders** [comment]
Is there linux support yet or some way to force the dpi?  I just built godot and there aren't any changes as far as I can tell on my 2880x1800 retina macbook pro running arch/gnome.  However manually scaling up fonts using the recent DynamicFont additions has helped tremendously.

**Comment by adolson** [comment]
I see no code for hidpi support for anything but OSX. This issue should be
reopened, or a new one opened for non-Mac users.

**Comment by reduz** [comment]
There is Windows hidpi code, the Linux one is a PR, will be merged soon (i
thought it already was)

**Comment by reduz** [comment]
detecting DPI on linux is kind of tricky because the XRandR extensions are
not always present, so the guys are trying to figure a way to make it work
even if the functions are not there

**Comment by vnen** [comment]
The PR is #4905 (I thought it was merged already). So reopening until the Linux part is implemented :disappointed:

**Comment by mcanders** [comment]
Cool. I left my two cents.  Its definitely an interesting problem.

**Comment by vnen** [comment]
Last resort can be an editor setting and/or cli flag.

**Comment by djrm** [comment]
maybe this can be closed now

**Comment by vnen** [comment]
@djrm still waiting for #4905 to be merged.

**Comment by djrm** [comment]
oh true

**Comment by vnen** [comment]
Closing this as #4905 is merged now 🎉

**Comment by DimitriyPS** [comment]
I understand that the problem has been resolved for Linux? Someone have tested on Linux?

**Comment by afiestas** [comment]
It works mostly great on Archlinux with latest godot from git.

Opened the only issue I could find:
[https://github.com/godotengine/godot/issues/5436](url)
