### ISSUE TITLE
Cppcheck errors in 3.1

### ISSUE THREAD

**Issue by swenner** [godotengine/godot#22702]
Cppcheck version 1.76.1
Godot version 3.1 rev caa141a1ac630144e441f89689baa1a74bb3bae5

I fixed the easy ones in the PR below.

All remaining cppcheck errors in non third party code:

[core/io/logger.cpp:196]: (error) va_list 'list_copy' used before va_start() was called.
[core/io/logger.cpp:200]: (error) va_list 'list_copy' used before va_start() was called.
[core/io/logger.cpp:202]: (error) va_list 'list_copy' used before va_start() was called.
[core/io/logger.cpp:250]: (error) va_list 'list_copy' used before va_start() was called.
[core/io/logger.cpp:251]: (error) va_list 'list_copy' used before va_start() was called.
[core/io/logger.cpp:252]: (error) va_list 'list_copy' used before va_start() was called.
[core/os/memory.cpp:101]: (error) Memory leak: mem
[editor/progress_dialog.cpp:60]: (error) Uninitialized struct member: t.vb
[editor/progress_dialog.cpp:60]: (error) Uninitialized struct member: t.state
[editor/progress_dialog.cpp:121]: (error) Uninitialized variable: no_updates
[editor/progress_dialog.cpp:183]: (error) Uninitialized struct member: t.hb
[main/input_default.cpp:407]: (error) Uninitialized struct member: action.strength
[main/input_default.cpp:541]: (error) Uninitialized struct member: action.strength
[main/input_default.cpp:552]: (error) Uninitialized struct member: action.strength
[platform/iphone/os_iphone.cpp:566]: (error) Memory leak: new_ptr
[servers/physics/body_pair_sw.cpp:130]: (error) Uninitialized struct member: contact.local_shape
[servers/physics/body_pair_sw.cpp:136]: (error) Uninitialized struct member: contact.local_shape
[servers/physics/body_pair_sw.cpp:130]: (error) Uninitialized struct member: contact.collider_shape
[servers/physics/body_pair_sw.cpp:136]: (error) Uninitialized struct member: contact.collider_shape
[servers/physics/body_pair_sw.cpp:130]: (error) Uninitialized struct member: contact.active
[servers/physics/body_pair_sw.cpp:136]: (error) Uninitialized struct member: contact.active
[servers/visual/shader_language.cpp:2527]: (error) Uninitialized struct member: pos.char_idx
[servers/visual/shader_language.cpp:2527]: (error) Uninitialized struct member: pos.tk_line

Probably false positives:
[drivers/gles2/shader_gles2.h:240]: (error) Array 'values[3]' accessed at index 3, which is out of bounds.
[drivers/gles2/shader_gles2.h:256]: (error) Array 'values[3]' accessed at index 3, which is out of bounds.
[drivers/gles2/shader_gles2.h:272]: (error) Array 'values[3]' accessed at index 3, which is out of bounds.

**Comment by LinuxUserGD** [comment]
Isn't #22703 merged?

**Comment by akien-mga** [comment]
Yeah but AFAIK #22703 didn't fix the errors reported in this issue, only some others not listed here.

**Comment by swenner** [comment]
I went through all the remaining ones.

Fixed by my upcoming merge request:
[editor/progress_dialog.cpp:60]: (error) Uninitialized struct member: t.vb
[editor/progress_dialog.cpp:60]: (error) Uninitialized struct member: t.state
[editor/progress_dialog.cpp:121]: (error) Uninitialized variable: no_updates
[editor/progress_dialog.cpp:183]: (error) Uninitialized struct member: t.hb
[main/input_default.cpp:432]: (error) Uninitialized struct member: action.strength
[main/input_default.cpp:566]: (error) Uninitialized struct member: action.strength
[main/input_default.cpp:577]: (error) Uninitialized struct member: action.strength
[servers/visual/shader_language.cpp:2527]: (error) Uninitialized struct member: pos.char_idx
[servers/visual/shader_language.cpp:2527]: (error) Uninitialized struct member: pos.tk_line

False positives:
[core/io/logger.cpp:200]: (error) va_list 'list_copy' used before va_start() was called.
[core/io/logger.cpp:204]: (error) va_list 'list_copy' used before va_start() was called.
[core/io/logger.cpp:206]: (error) va_list 'list_copy' used before va_start() was called.
[core/io/logger.cpp:254]: (error) va_list 'list_copy' used before va_start() was called.
[core/io/logger.cpp:255]: (error) va_list 'list_copy' used before va_start() was called.
[core/io/logger.cpp:256]: (error) va_list 'list_copy' used before va_start() was called.
[core/os/memory.cpp:101]: (error) Memory leak: mem
[drivers/gles2/shader_gles2.h:240]: (error) Array 'values[3]' accessed at index 3, which is out of bounds.
[drivers/gles2/shader_gles2.h:256]: (error) Array 'values[3]' accessed at index 3, which is out of bounds.
[drivers/gles2/shader_gles2.h:272]: (error) Array 'values[3]' accessed at index 3, which is out of bounds.
[platform/iphone/os_iphone.cpp:566]: (error) Memory leak: new_ptr
[servers/physics/body_pair_sw.cpp:130]: (error) Uninitialized struct member: contact.local_shape
[servers/physics/body_pair_sw.cpp:136]: (error) Uninitialized struct member: contact.local_shape
[servers/physics/body_pair_sw.cpp:130]: (error) Uninitialized struct member: contact.collider_shape
[servers/physics/body_pair_sw.cpp:136]: (error) Uninitialized struct member: contact.collider_shape
[servers/physics/body_pair_sw.cpp:130]: (error) Uninitialized struct member: contact.active
[servers/physics/body_pair_sw.cpp:136]: (error) Uninitialized struct member: contact.active
