### ISSUE TITLE
"New Noise Texture" does not have an icon

### ISSUE THREAD

**Issue by swenner** [godotengine/godot#22704]
**Godot version:**
Master (3.1) caa141a1ac630144e441f89689baa1a74bb3bae5

**OS/device including version:**
Debina GNU/Linux 9

**Issue description:**
There is no icon for "New Noise Texture". See attached image.

![noise-texture-icon](https://user-images.githubusercontent.com/290658/46445394-fc6efa80-c776-11e8-87df-94b464554054.png)

**Comment by qonnop** [comment]
Some mockups for the icons:

![mockup](https://user-images.githubusercontent.com/43803874/46454928-f42fb300-c7a8-11e8-9dab-5e1a0953324d.png)![mockup](https://user-images.githubusercontent.com/43803874/46455180-2392ef80-c7aa-11e8-933b-4f195ecf6d78.png)
Some other ideas/preferences?

**Comment by akien-mga** [comment]
I prefer the third one, icons should be kept relatively low res, so that they can still be identified when scaled to 75% in VeryLoDPI mode (and so that they scale up properly in HiDPI).

**Comment by akien-mga** [comment]
Though it's true that most Texture icons seem to reuse this mountain picture, so it could be nice to keep this reference, but I feel (2) is a bit too busy.

**Comment by LikeLakers2** [comment]
I like the third one best. It's like a TV screen with static, sort of like what a NoiseTexture is.
