### ISSUE TITLE
ColorPicker: alpha can still be set in hex value if "edit alpha" is off

### ISSUE THREAD

**Issue by DeleteSystem32** [godotengine/godot#22714]
**Godot version:**

3.06 stable

**OS/device including version:**

Antergos Linux

**Issue description:**

In a ColorPicker node, after setting "edit alpha" to false, the colour's alpha value can still be set through the hex value. Not sure if this is intentional.

**Steps to reproduce:**
Add Colorpicker node. Set "edit alpha" to false. In the running project, add 00 in front of the hex value.
![peek 2018-10-04 13-44](https://user-images.githubusercontent.com/16924295/46471911-ba2bd480-c7db-11e8-9fc9-bc9581d944c8.gif)

**Comment by akien-mga** [comment]
Solution (1) seems good to me.
