### ISSUE TITLE
Tile selection outline in tileset editor temporarily offsets when creating/deleting a tile

### ISSUE THREAD

**Issue by ByTheQuietLake** [godotengine/godot#22725]
**Godot version:**

 8068d02 

**OS/device including version:**

Win 7, Intel HD 4000

**Issue description:**

Was requested to create a new issue on this rather than a comment so here it is.
When you  create a single tile and then choose to create another tile notice how the yellow outline of the last created tile offsets to the top right. This happens to all latest created tiles when you choose to create either a single tile or tile atlas or autotile. But there shouldn't be any offset at all. Note that this is temporary and doesn't affect any functionality as far as I know. This behavior as observed when trying to delete a tile and creating a new tile right after.
![45668751-96119780-bb3b-11e8-8c8e-f12a3a8d7fb5](https://user-images.githubusercontent.com/30891267/46494445-8b8c1900-c830-11e8-8991-e9c15172e988.gif)
![45668905-fa345b80-bb3b-11e8-9a77-02fc07d04b81](https://user-images.githubusercontent.com/30891267/46494448-8e870980-c830-11e8-8f80-2a98e7805e9e.gif)

**Steps to reproduce:**
1.Create a new tileset and add an image
2. Click on new single tile and draw a tile or perhaps delete any existing tile
3. Click on new single tile again 

**Minimal reproduction project:**

**Comment by capnm** [comment]
IMO this is a hack to improve the selection of overlapping tiles, it actually requires similar gizmos for the region, as e.g. the collision polygon editor has.

![image](https://user-images.githubusercontent.com/4047289/46503581-7f518d00-c82b-11e8-9c1b-6d2458aae93a.png)

![image](https://user-images.githubusercontent.com/4047289/46503457-28e44e80-c82b-11e8-8f2a-d3a854565512.png)

 
(At the moment, I think, the tile editor is generally hard to use and happy crashes all the time)
```
...

ERROR: autotile_get_spacing: Condition ' !tile_map.has(p_id) ' is true. returned: 0
   At: scene/resources/tile_set.cpp:439.
ERROR: autotile_get_size: Condition ' !tile_map.has(p_id) ' is true. returned: Size2()
   At: scene/resources/tile_set.cpp:452.
ERROR: tile_get_region: Condition ' !tile_map.has(p_id) ' is true. returned: Rect2()
   At: scene/resources/tile_set.cpp:399.
ERROR: autotile_get_spacing: Condition ' !tile_map.has(p_id) ' is true. returned: 0
   At: scene/resources/tile_set.cpp:439.
ERROR: autotile_get_size: Condition ' !tile_map.has(p_id) ' is true. returned: Size2()
   At: scene/resources/tile_set.cpp:452.
ERROR: tile_get_region: Condition ' !tile_map.has(p_id) ' is true. returned: Rect2()
   At: scene/resources/tile_set.cpp:399.
ERROR: operator[]: FATAL: Index p_index=-1 out of size (size()=0)
   At: ./core/dvector.h:505.
handle_crash: Program crashed with signal 4
```

**Comment by ByTheQuietLake** [comment]
@capnm I don't quite get what you mean? The offset occurs only when you create a new tile or delete one, I am not sure how that would help with visualization.

**Comment by capnm** [comment]
> The offset occurs only when you create a new tile or delete one, I am not sure how that would help with visualization.

IIRC if the new tile were created on the same position that the old one, you wont see it.

**Comment by capnm** [comment]
I'm not talking about use cases, but about **editing or creating tiles**. It doesn't seem to matter where the new tile placeholder appears, as long as you can understand that you should 'paint it' somewhere now. (Such a creation of new tiles seems to be useless without an enabled grid-snap anyway)

**Comment by capnm** [comment]
>If I understand it correctly, the tile that appears offsetted is actually an indicator that a tile is waiting to be placed?

At least I think @MarianoGnu did this on purpose.

**Comment by MarianoGnu** [comment]
No, it was not intentional, it is a bug. While drawing a tile i have a temp variable storing the rect, this is drawn instead of the actual region, what happens here is that there's no current selection, but the rect is drawn anyway.
The offset is because on the WORKSPACE_MARGIN, wich means i added some extra pixels to allow users to click out of the tecturw

**Comment by ByTheQuietLake** [comment]
@akien-mga  this issues is no longer present in the latest master and can be closed.
