### ISSUE TITLE
Make going into visual shader editor simpler

### ISSUE THREAD

**Issue by lentsius-bark** [godotengine/godot#22720]
At the moment if one wishes to enter the visual shader editor of a node, the process is:
**Select the node -> Click on the material -> Click on Visual shader -> Click "Open editor"**
_note: the third step is not always necessary_

I propose that instead it would be intuitive to have the editor itself check whether the node uses a visual shader and if so, the button (as can be seen in the screenshot below) to open the editor would automatically show up. Once clicked the the editor automatically loads the visual shader of the node. Hence simplifying the process into:

**Select the node -> Click "Visual Shader"**

![Visual shader editor button](https://user-images.githubusercontent.com/38346332/46487588-b494b580-c800-11e8-8e39-6cea0d786606.png)

**Comment by clayjohn** [comment]
This change would also be very welcome for regular shaders. 

A potential issue for implementing this is that nodes can contain more than one shader (e.g. MeshInstance with multiple surfaces, each with its own shader).

**Comment by fire** [comment]
How would you suggest support multiple surfaces?

Something like the animation player with different tracks feels like overkill, but I don't have any other ideas.

**Comment by lentsius-bark** [comment]
The visual shader / shader editors themselves could have tabs for multiple shaders applied to the same node.

**Comment by KoBeWi** [comment]
You can edit any shader directly by right-clicking the node in scene tree:
![image](https://user-images.githubusercontent.com/2223172/56083471-c3020080-5e25-11e9-8019-b2956226c7b5.png)

**Comment by Calinou** [comment]
This was implemented in https://github.com/godotengine/godot/pull/51356, closing.
