### ISSUE TITLE
Hardware cursor replacement is broken

### ISSUE THREAD

**Issue by her001** [godotengine/godot#2273]
As described [here](http://www.godotengine.org/forum/viewtopic.php?f=11&t=1093), hardware cursor replacement doesn't work.

The example provided by gordonfranz in the above forum post:
```gdscript
var image = Image()
image.load("res://cursor/cursor1.png")
VisualServer.cursor_set_texture(VisualServer.texture_create_from_image(image), Vector2(), 0)
```
This should replace the cursor, but it appears to do nothing.

I'm currently doing some work on bringing a point and click adventure game to godot and ideally I would use this method for adjusting the cursor.

**Comment by akien-mga** [comment]
I can confirm that the above code does not work. The VisualServer API is not much documented either so far, so it's hard to know if those commands just don't work or if the wrong arguments were used. I tried e.g. ```VisualServer.cursor_set_visible(false, 0)``` and it also has no effect, but I'm not sure of the syntax for the expected int argument.

**Comment by reduz** [comment]
This has been fixed, and there are now better methods to do this using the Input API and changing to custom cursor in project settings!

**Comment by her001** [comment]
Looks like the Vector2 hotspot setting in Input.set_custom_mouse_cursor does nothing. To ensure it wasn't me messing up the scripting, I tried using the project settings, still didn't work.


I was using something like this:
```GDScript
 Input.set_custom_mouse_cursor(base_cursor, Vector2(32,32))
```
But the hotspot was still at the top left corner (what I assume to be 0,0) of the cursor.

**Comment by puppetmaster-** [comment]
hotspot problem is in this issue https://github.com/godotengine/godot/issues/3082

for a mouse replacement you can use a separate mouse scene https://github.com/godotengine/godot/issues/3006
