### ISSUE TITLE
Visual Shader textures don't update properly

### ISSUE THREAD

**Issue by coasterspaul** [godotengine/godot#22746]
**Godot version:**
Master https://github.com/godotengine/godot/commit/8068d0217a5e74c25f83fe93fa6e077b8d0b3bf5

**OS/device including version:**
Windows 10

**Issue description:**
The Constant -> Texture node in the Visual Shader editor breaks a lot.

Loading a new texture into it doesn't change the shader immediately; running the game resulted in the old texture still displaying. If one connection is changed then moved back, the shader does update and display the correct texture after running the game.

The dropdown for selecting a texture has options to create textures including `GradientTexture`s and `NoiseTexture`s, but it seems Visual Shaders can't actually read those.  GradientTextures worked briefly for me in one previous build but no longer work. NoiseTextures stopped working for me this build. Instead of sampling, they seem to output pure white, which wasn't even a color in my gradient. (I tested this by connecting their color output directly to the Output Albedo.)

This still happened even after loading a regular texture. I had to remove the node and replace it with a new Texture node to display a texture again.

**Comment by fire** [comment]
Were you able to narrow down which changes broke the texture display? One can run git bisect on the changes. Do you remember what build worked?

**Comment by akien-mga** [comment]
Maybe related to #22721?

**Comment by fire** [comment]
Since #22721 was closed without fixing this problem, any suggestions?

**Comment by coasterspaul** [comment]
Updating the numbers in a visual shader also doesn't update the shader the next time the game is run. Again, disconnecting and reconnecting a node does.

**Comment by fire** [comment]
Can you check the latest? 

https://github.com/godotengine/godot/issues/22906 was a fix for a related issue

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by akien-mga** [comment]
No answer, assuming fixed. Please comment if you can still reproduce the issue.

**Comment by shayneoneill** [comment]
This happens to me all the time. Its not just the visual shader, its any material update you kinda have to roll a dice as to whether it'll appear in the game when you run it or not. Theres some very broken cacheing going on *somewhere*

**Comment by Calinou** [comment]
@shayneoneill Please open a new issue with a minimal reproduction project attached.
