### ISSUE TITLE
Cannot load resource which has a C# script attached to it

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#22749]
**Godot version:**

8068d0217a5e74c25f83fe93fa6e077b8d0b3bf5

**OS/device including version:**

Linux

**Issue description:**

If you try to load a resource which has a C# script attached to it, the game will silently crash when played with no errors reported in the editor console.  This will happen in GDScript using `load` or `preload`, in C# using `Load` or `Load<T>`, or exporting a Resource variable and placing the resource into that slot via the editor.

**Steps to reproduce:**
1. Create a new resource
2. Attach a C# script to it which inherits 'Resource'
3. Try to load the resource in any way

[NoCSRes.zip](https://github.com/godotengine/godot/files/2448930/NoCSRes.zip)

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by somnivore** [comment]
Tried it again with 220f50e790223c7bc63fd3d2ca3327aa6dcc5d3c

Right now, it gives this error in the terminal:
```
ERROR: _load: No loader found for resource: res://
   At: core/io/resource_loader.cpp:192.
```

And in the Debugger/Errors tab:
```
E 0:00:00:0834   System.NullReferenceException: Object reference not set to an instance of an object
  <C Source>     :0
  <Stack Trace>  :0 @ ()
                 ResourceLoader.cs:36 @ Godot.Resource Godot.ResourceLoader.Load(System.String , System.String , Boolean )()
                 ResourceLoaderExtensions.cs:7 @ Godot.SpatialMaterial Godot.ResourceLoader.Load<Godot.SpatialMaterial >(System.String )()
                 TestNode.cs:9 @ void TestNode._Ready()()

```

Using the following code:
```
using Godot;
using System;

public class TestNode : Node
{
	public override void _Ready()
	{
		var res = ResourceLoader.Load<SpatialMaterial>("res://TestRes.tres");
		GD.Print(res);
	}
}
```

TestRes.tres has a C# script attached to it:
```
using Godot;
using System;

public class MyTestRes : SpatialMaterial
{
	[Export]
	public int MyInt { get; private set; }
	[Export]
	public string MyString { get; private set; }
}
```

Trying this exact same thing on any other resource without a C# script, there's no issue:
```
	public override void _Ready()
	{
		var res = ResourceLoader.Load<SpatialMaterial>("res://SomeMaterial.tres");
		GD.Print(res);
	}
```

![image](https://user-images.githubusercontent.com/28724859/47491658-eb168c80-d810-11e8-8038-0b8272171b85.png)

Casting to `SpatialMaterial` or `MyTestRes` makes no difference for the resource with the C# script.  If the script is removed, it loads fine.

**Comment by akien-mga** [comment]
Can't reproduce the crash in 3.1 beta 6, it seems to load fine.
