### ISSUE TITLE
Tilemap Atlas Bug

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#22756]
**Godot version:**
3.1 alpha official

**OS/device including version:**
Windows 10

**Issue description:**
If you use Tilemap Atlas and remove one tile, the tiles around it will change to the tile you defined as the icon. 
Same with the Bucket Tool.

**Steps to reproduce:**
**Removing Tile:**
![godot_2018-10-05_10-32-25](https://user-images.githubusercontent.com/42905358/46525142-1ef23800-c88b-11e8-95dd-ab394e3463fb.png)
![godot_2018-10-05_10-32-35](https://user-images.githubusercontent.com/42905358/46525143-1ef23800-c88b-11e8-8308-a08e221807a3.png)

**Bucket Fill:**
![godot_2018-10-05_14-03-16](https://user-images.githubusercontent.com/42905358/46534187-a057c380-c8a7-11e8-8c01-809b231d4251.png)
![godot_2018-10-05_14-03-27](https://user-images.githubusercontent.com/42905358/46534188-a057c380-c8a7-11e8-828b-0ec0d941aff8.png)

**Edit: If you select & copy tiles, they will change to the currently selected tile inside the atlas.**
![image](https://user-images.githubusercontent.com/42905358/46533759-0f341d00-c8a6-11e8-9729-00faae59ebe1.png)

**Minimal reproduction project:**
[Atlas Bug.zip](https://github.com/godotengine/godot/files/2449583/Atlas.Bug.zip)

**Comment by ByTheQuietLake** [comment]
I think this the same issue as #22204 , The adjacent tiles of the removed tiles change into the first tile in the atlas tile set, another related issue is copying  and pasting a atlas tile seems to paste first tile of the atlas rather than the correct one, but issues are detailed in the issue I have linked

**Comment by Banduck** [comment]
Oh, yeah that's the same issue, I searched for "Tilemap" and didn't find anything.
But actually it doesn't change to the first tile in the atlas, instead it changes to the tile you defined as the icon.
And when copying it changes to the currently selected tile.
