### ISSUE TITLE
find_node not functional

### ISSUE THREAD

**Issue by fazjaxton** [godotengine/godot#2275]
find_node from GDScript does not seem to work as intended.  The first issue is that the find_node binding seems to include a copy/paste error in node.cpp:1842, binding to get_node instead of find_node.

The second issue is a little harder.  When I debug the engine in gdb while stepping over the find_node call, I can see the recursion search for and find a matching node, and return a pointer to the node.  The pointer seems valid until it is returned and assigned to the Variant type in the language binding, and then I don't know enough to continue following.  However, after the GDScript step-over is complete for the find_node call, the godot debugger shows the return of find_node as 0.

I have created an example project that demonstrates this.  To reproduce:

1. Set a breakpoint on the GDscript find_node call, test.gd:9.  Run the project.
1. Attach GDB to the child process.
1. Set a breakpoint on Node::find_node and continue GDB.
1. Press step-over in the godot debugger.
1. Once the GDB breakpoint is hit, step though the until the first recursion returns the matching node, to see that it is found.
1. Continue GDB so that the Godot debugger step can continue.
1. Examine the returned value in the editor; it is zero.

http://fazjaxton.net/files/test3.zip

**Comment by akien-mga** [comment]
Fixed by 1630f0a.
