### ISSUE TITLE
Tilemap tiles are clipped

### ISSUE THREAD

**Issue by gavriil07** [godotengine/godot#22754]
**Godot version:**
3.1 alpha 8fc92ae

**OS/device including version:**
Windows 10

**Issue description:**
![sep](https://user-images.githubusercontent.com/28069262/46521061-0122d400-c887-11e8-8a6b-f1e33169af84.gif)

**Steps to reproduce:**
Have a tilemap 30x30, quadrant size 16
Tile size: 32x32px

**Comment by groud** [comment]
Are you using an Nvidia card ?
Probably a duplicate of #9913

**Comment by gavriil07** [comment]
Yes, I have a Nvidia GTX 1070, seems like it is, this is a bummer :/

**Comment by akien-mga** [comment]
Closing as duplicate of #9913.
