### ISSUE TITLE
AnimatedSprite Bug: Cannot have the last frame duplicated

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#22763]
Godot 3.0.6, Windows (tested on two machines).

If you duplicate the last sprite frame in the AnimatedSprite node, it will constantly "switch" between the last frame and the second last frame. 

In my case I have 13 frames in my Sprite Atlas and I wanted to play frame 0-12 in the beginning of the animation and then play it backwards (frame 12-0) at the end of the animation, but apparently it's not happy about having the same Frame twice after each other, so it will switch between frame 12 and 11 many times (see image).

![image](https://user-images.githubusercontent.com/24936603/46540537-ee75c280-c8b9-11e8-8904-e76504525b94.png)

**Comment by qonnop** [comment]
This problem is caused in interpolation by casting double -> int, I'll try to fix it...

**Comment by jesperkondrup** [comment]
That was fast, nice work :)
