### ISSUE TITLE
opening scene in new tab conflict with tool keyword

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#2277]
Hi
I build the last version of Godot when I open a scene that has a script and tool , to add object with script and animate it with tween , object have problem , it is like that it is initiated twice .

**Comment by mohaalak** [comment]
it will add two object in my scene , and I add it in _ready function just once

**Comment by akien-mga** [comment]
Are you still able to reproduce this issue in the current master branch? If so, could you provide an example project that reproduces it?

**Comment by bojidar-bg** [comment]
Seems like a duplicate of #2657 (If not, tell me and I'll delete my comment :smile: )

**Comment by akien-mga** [comment]
Might actually be a duplicate of #2229, so it's not easy to understand what was meant initially.

**Comment by akien-mga** [comment]
Closing for now, feel free to reopen if your issue was different from the two linked above.
