### ISSUE TITLE
File open with read_write does not work if the file does not exist

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#2278]
openning file with write_read flag does not work ,

**Comment by reduz** [comment]
how are you opening it?

**Comment by mohaalak** [comment]
like this

var f=File.new()
f.open("user://score",3)

in this mode file does not read or write.

**Comment by guilhermefelipecgs** [comment]
I have this problem too, I can only use File.READ or File.WRITE, but not File.READ_WRITE.

**Comment by guilhermefelipecgs** [comment]
READ_WRITE work only when the file has been created.

**Comment by mohaalak** [comment]
I checked it in godot 2.0 the problem is there :-1: I think the problem lies [here](https://github.com/godotengine/godot/blob/master/core/os/file_access.cpp#L101)

**Comment by akien-mga** [comment]
Just for the reference, note that the above fix was then further fixed in 52e53d4, so you should now be able to use WRITE_READ instead of READ_WRITE for your use case.

**Comment by mohaalak** [comment]
@akien-mga thanks
