### ISSUE TITLE
Godot 3.1 AtlasTexture region editor doesn't work

### ISSUE THREAD

**Issue by deepmax** [godotengine/godot#22789]
**Godot version:**
v3.1.alpha.custom_build.f816909

**OS/device including version:**
Ubuntu 14.04

**Issue description:**
AtlasTexture editor doesn't work for atlas related region

![screenshot from 2018-10-06 11 14 46](https://user-images.githubusercontent.com/8607244/46568900-8f678a80-c959-11e8-9973-e2d849b72eda.png)

**Steps to reproduce:**
1. Put a sprite in the scene
2. Change the texture to AtlasTexture
3. Assign an image to Atlas
4. Enable region
5. Select a region in TextureRegion

However, if I store the image as a *.tres file and use it in an AtlasTexture it will work

**Minimal reproduction project:**

[test-godot.zip](https://github.com/godotengine/godot/files/2452813/test-godot.zip)

**Comment by piratesephiroth** [comment]
I don't get it. AtlasTextures are working fine.
Why did you enable region though? You want to cut a fragment of a fragment? What?

**Comment by deepmax** [comment]
> I don't get it. AtlasTextures are working fine. You just set their region on the atlas and margin and that's it.
> You won't see anything because by default everything is set to 0.
> 
> Why did you enable region as if it was a regular texture though? You want to cut a fragment of a fragment? What?
> Maybe you just wanted to use the region editor for that but that won't work. You gotta type in the values by hand.
> 
> Here's an example of it working even with region enabled:
> ![image](https://user-images.githubusercontent.com/10672233/46581110-8c77a300-ca08-11e8-8685-c7c865127ed4.png)

So, why we have to set the values by hand when we have region editor?

**Comment by piratesephiroth** [comment]
>So, why we have to set the values by hand when we have region editor?
>Moreover, why there are two region in the inspector (one for regular textures, one for AtlasTexture)?

Those are pretty good questions that I can't answer, lol.

However the region editor curiously works when we load the atlastexures as tres files, as you wrote.

**Comment by deepmax** [comment]
Everything is fine, new inspector in the 3.1 mislead me, there is two `region` is 3.0.6 too, and you can use region editor for both of them separately, first we must use the editor for atlas-region, then use the editor for sprite-region.

**Comment by deepmax** [comment]
Everything is fine in 3.0.6. We can use region editor for both atlas-region and sprite-region. However in 3.1 we can not use the editor for atlas-region.

**Comment by piratesephiroth** [comment]
you should edit the title and description of the issue now

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by piratesephiroth** [comment]
>Is this still reproducible in the current master branch?

Yes. Here's a brief description of what happens when you add a new AtlasTexture to a Sprite then add a Texture as Atlas.:

**Godot 3.0.x** 
TextureRegion editor displays the Atlas and allows you to manipulate the AtlasTexture's Region property.
The result is previewed on the bottom right corner of the editor.

**Godot 3.1**
TextureRegion editor appears to show the Atlas but it has no effect at all in the AtlasTexture's properties.
If you manually adjust the AtlasTexture's region's values and get back to the TextureRegion editor you will see that it's actually displaying the AtlasTexture (it will only refresh the displayed image when we try to use the editor).
There's no preview on the bottom right corner.

**Comment by akien-mga** [comment]
CC @MarianoGnu @YeldhamDev who changed the TextureRegionEditor in recent months.

**Comment by YeldhamDev** [comment]
When the TextureRegion editor appears when you select a Sprite node, it's editing the **Sprite**'s region. You have to edit the Atlas resource itself (by clicking in "Open Editor"), so the TextureRegion editor targets the Atlas.

**Comment by piratesephiroth** [comment]
oh, yeah, that seems to work.

It's really different from 3.0 though.

**Comment by YeldhamDev** [comment]
@akien-mga I guess this can be closed then.
