### ISSUE TITLE
There shouldn't be Errors for things that are working properly

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#22785]
**Godot version:**
Godot 3.1 nightly

**OS/device including version:**
Manjaro 64bit+Windows 64bit(yep dual boot)

**Issue description:**
I hate the fact that in Godot you get to see errors for everything, like when I am trying to write a shader and it get's compiled for every few words I type and just blasts the OUTPUT with errors for all that which is meaningless.
I don't know if it can be turned off in the Editor somewhere, I haven't found it yet.

But there are lots of such examples especially, create a TileSet using the TileMap Node and start adding stuff to it, by the time you have a couple tiles ready you OUTPUT will be filled with errors.
And it's all meaningless.

All this bombardment of errors simply decrease the value/use of Errors, I don't know why we haven't fixed this yet. But the errors should be a clear log of what went wrong only for things that actually went wrong.

If there is a use to it all yep we should keep them but we can atleast try to remove as many as we can atleast to make the OUTPUT window a more sensible place.

**Comment by groud** [comment]
Please... Those kind of issue do not help. Everybody agrees on the fact that the editor drops errors in unexpected situations and it is not good.

Please do as qarmin (if I'm not mistaking in the name) and open an issue for specific cases, in specific situation.

**Comment by swarnimarun** [comment]
@groud point noted, and I should just fix as many as I can too, should the PRs be separate or the same??

**Comment by groud** [comment]
@swarnimarun you can open one issue for each problem (with reproduction step and all). For the PR it depends, if they are related problems you can use a single one but in general it's better to have one PR for each specific fix.
