### ISSUE TITLE
Incorrect UV when exporting from Blender to Obj - internal exporter

### ISSUE THREAD

**Issue by Alastor01** [godotengine/godot#22792]
Godot version: 3.0.6

OS: Windows 10 64-bit
Blender version: 2.79b

Issue description:
- The imported mesh UV in Godot is no longer correct
- The texture does not align properly to the object anymore
 * What was expected: UV layout being the same as the one in Blender, texture aligning correctly
NOTE: The same object exported with Better Collada to Dae has correct UV and correct texture placement

Steps to reproduce:
1) Create / import static model in Blender (I just made my own low-poly barrel)
2) Correctly UV unwrap, have only one UV layer
3) Draw / bake texture corresponding to UV, test it in Blender
4) Export to Obj, internally (mtl file makes no difference)
5) Import to Godot, add Obj to MeshInstnace mesh, create new SpatialMaterial in GeometryInstance, add your texture to SpatialMaterial Albedo
6) Render / run your project (need Camera node at a minimum)
(Optional: click on MeshInstance --> Mesh --> ViewUV1)

**Comment by glaforte** [comment]
I looked at this issue and I was unable to reproduce it.
@Alastor01 Could you please provide a small Blender file that reproduces the issue?

**Comment by glaforte** [comment]
For the record, I whipped up a calibration texture quickly and did a custom UV job on a cube. Exported it in COLLADA and OBJ formats. I imported the COLLADA cube and compared with the blender to confirm that they are similar. I imported the OBJ cube and placed it besides the COLLADA cube and confirmed that they are similar.

![image](https://user-images.githubusercontent.com/2227491/48852780-1478f880-ed7c-11e8-81c5-de25dd345709.png)

**Comment by glaforte** [comment]
I've now tried to reproduce the issue in Godot 3.0.6 and with a Blender Smart Unwrap and Texture-Painting. I've had no success at reproducing the issue.

**Comment by Alastor01** [comment]
@glaforte 
I am sorry, but I also can not reproduce the issue anymore. I have just exported my barrel (which I have edited since then) to both better collada and obj (export UV option checked). In both instances, I was able to assign the texture correctly, without any artifacts.

I have not updated any software in question. Seems, something was wrong with my setup in Blender or Godot.
How do I close the issue or request it to be closed?

Just in case, these are my blend file and texture:
![barrel drum blue](https://user-images.githubusercontent.com/43552811/48855341-c845ac80-edab-11e8-87fd-27cbcad6a2b3.png)
[Barrel drum.zip](https://github.com/godotengine/godot/files/2605034/Barrel.drum.zip)

**Comment by glaforte** [comment]
@Alastor01 Thanks for providing us with this data. If you cannot reproduce it either, then I suggest we wait until someone experiences the issue again. There might have been some side-effect with a project/editor option or such..

I don't have full rights on this repository. So, I cannot close the issue, Typically, as the reporter: you should have a gray 'Close Issue' button on the left of the green 'Comment' button, at the bottom of the page. Alternatively, if you don't have this button, we can ask the project's manager...

**Comment by Alastor01** [comment]
@glaforte I understand, thank you for looking into it.
I will close the issue for now. If someone else experiences it, the issue can be re-opened
