### ISSUE TITLE
Release export crashes with segfault

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#22794]
**Godot version:**
3.1-alpha 06fa780

**OS/device including version:**
Windows 10

**Issue description:**
When running a release export:

1. Mouse location is not being reported via `get_viewport().get_mouse_position()`
2. Build crashes with segfault (access violation) after changing scene.

I believe these two to be related. In debug builds and run from editor game runs fine.

**Steps to reproduce:**
Unable to replicate with minimal project (yet). Run [0.21.4 of ΔV](https://koder.itch.io/dv-rings-of-saturn-demo) on Windows against  06fa780 compiled with `target=release tools=no` to observe that:
1. Mouse does not move on screen (sprite position is read via `get_viewport().get_mouse_position()` in `_process`)
2. New Game causes to segfault.

**Comment by lekoder** [comment]
Caused by 95131e6

**Comment by lekoder** [comment]
Isolated down to changes in [`modules/gdscript/gdscript_function.cpp`](https://github.com/godotengine/godot/commit/95131e6f23c1c5a475812afa295803c191dead7f#diff-7c06861511ac3f4b3a3aab8c1f85adaa)

**Comment by akien-mga** [comment]
Fixed by #22796.
