### ISSUE TITLE
3D KinematicBody with Raycast shape's physics stop simulating when facing certain direction

### ISSUE THREAD

**Issue by CoolOppo** [godotengine/godot#22798]
**Godot version:**
181af9b (64-bit, built 2018-10-05)

**OS/device including version:**
Windows 10

```
AMD Radeon RX 580 Series
Device ID - 67DF
Vendor ID - 1002
SubSystem ID - C580
SubSystem Vendor ID - 1682
Revision ID - E7
BIOS Version - 015.050.002.001
Driver Version - 18.9.3
```

**Issue description:**
Major performance hit when looking at the sun (or maybe just in a specific direction) while using a 3D KinematicBody with Raycast Shape collision. I can confirm that changing the second collision shape to a box fixes the issue.

###### Video:
https://youtu.be/56tFcgrX6Z0

**Steps to reproduce:**
Make a 3D KinematicBody with a Box collision shape and a Ray collision shape.

**Minimal reproduction project:**
[HELP.zip](https://github.com/godotengine/godot/files/2453029/HELP.zip)

for bonus points try and figure out what's going on in `Player.gd` ;)

**Comment by rodolforg** [comment]
I don't know if this changes the performance, but you should not scale the CollisionShape that way.
You should move the orange(?) circle only (or click on RayShape item in Inspector and adjust its property "Length")

**Comment by CoolOppo** [comment]
I was thinking about that as well. I'll try that out and let you know if that does anything.

**Comment by CoolOppo** [comment]
Just tried it, but that didn't fix the issue.

**Comment by CoolOppo** [comment]
> orange(?)

Apparently the name of the color is "Deep Blush":
![](https://dl.dropboxusercontent.com/s/ihlf6nkzgxmn70x/2018-10-07_22-01-28.png)

;)

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by akien-mga** [comment]
Seems reproducible in 3.1 beta 6, the console is spammed with thousands of:
```
ERROR: slide: Condition ' !p_normal.is_normalized() ' is true. returned: Vector3()
   At: ./core/math/vector3.h:433.
ERROR: slide: Condition ' !p_normal.is_normalized() ' is true. returned: Vector3()
   At: ./core/math/vector3.h:433.
```

**Comment by akien-mga** [comment]
Seems fixed in the current master branch. FPS stays stable when looking at the sun, and the normalization errors no longer happen.
