### ISSUE TITLE
Cannot set Color Ramp on CPUParticles2D

### ISSUE THREAD

**Issue by kiidmale** [godotengine/godot#22795]
**Godot version:**
master(3.1) f12cb82e0

**OS/device including version:**
Mac High Sierra and Windows 10

**Issue description:**
Cannot set Color Ramp on CPUParticles2D nodes.
There's no response after clicking 'New GradientTexture' at Color Ramp.
As a reminder, CPUParticles2D still not working on GLES2. #21839
![screen shot 2018-10-06 at 8 06 38 pm](https://user-images.githubusercontent.com/17870789/46570702-6835ab00-c9a3-11e8-80e4-67724a0d0b21.png)

**Comment by Calinou** [comment]
I can confirm this on https://github.com/godotengine/godot/commit/06a133bdd1d21fae01665b176f5811c3b9c22b6b.

**Comment by akien-mga** [comment]
The problem seems to be that `CPUParticles` and `CPUParticles2D` use `Ref<Gradient>` for their `color_ramp` property, while `ParticlesMaterial` uses `Ref<Texture>` (which is logical since the type hint is `GradientTexture`).

**Comment by akien-mga** [comment]
Fixed by #23646.
