### ISSUE TITLE
Load CSV in Godot

### ISSUE THREAD

**Issue by fish2091852127** [godotengine/godot#22802]
How to implement the function "load_csv()" of GMS(gamemakerstudio) in Godot and read the corresponding values in the CSV file and store in a Variable [x,y]?

get_csv_line() ：just read one line and only first line (By seek() change but too troubles)

**Comment by akien-mga** [comment]
Please ask such questions on the Godot Q&A: https://godotengine.org/qa
The answer is about two lines of script, and I'm sure someone them will provide a good example :)

This issue tracker is for engine bug reports, not general purpose questions.
