### ISSUE TITLE
"ONE" constant for Vector3/Vector2

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#22806]
The only Vector3 constant that's missing compared to Unity is `Vector3.ONE`, which is shorthand for `Vector3(1, 1, 1)`. It's something I didn't push for before #14704 was merged since I thought that PR was on pretty thin ice at the time, but now that it's in it would be nice to have it added once and for all.

The same could also be done for Vector2 (`Vector2.ONE` as a shorthand for `Vector2(1, 1)`)

**Comment by KellyThomas** [comment]
How do people feel about NEGONE now?

**Comment by akien-mga** [comment]
I don't see much use case for NEGONE (beyond the fact that it's a weird name that I wouldn't understand as `Vector3(-1, -1, -1)` instinctively), since you can simply use `-Vector3.ONE`.

**Comment by aaronfranke** [comment]
It's fine if you want to remove it. It's not critical though I do find it useful sometimes.
