### ISSUE TITLE
Error in Godot physics. "Dancing" box.

### ISSUE THREAD

**Issue by Mintormo** [godotengine/godot#22801]
**Godot version: 3.1.alpha.custom_build.8068d02**
**Win 7x64, GeForce 960 GTX, Bullet**
**Issue description:**
I maked simple scene with a box. Player push a box and it have down on the floor
and begin "to dance".
Video: https://youtu.be/Pq3F3nAK7do

**Steps to reproduce:**
1. Press F5 to start game.
2. Go to the box.
3. Push them on the floor.
4. Box begin "to dance"

Demo project:
[FPS.zip](https://github.com/godotengine/godot/files/2453096/FPS.zip)

**Comment by pwab** [comment]
I'm pretty sure this has to do with three points:
- Scaled rigidbodies
- Convex collisionshape for the floor
- Generated trimesh collisionshape for the stairs

Just the same project without scaled rigidbodies, a boxed collisionshape for the floor and a convex collisionshape for the stairs:
[FPS.zip](https://github.com/godotengine/godot/files/2453808/FPS.zip)

**Comment by Mintormo** [comment]
@pwab, you are right.
Problem is collision shape of floor and stairs. But there are problem with a box: space between box and stairs. I set simple box collision. I played with settings. Nothing. :(

**Comment by AndreaCatania** [comment]
Can you check with current master please #cff89fc ? I think that this #22759 PR fix this issue

**Comment by Mintormo** [comment]
I test latest master branch. The problem still exists.
Video: https://youtu.be/_3qeaPDnSOI
[FPS.zip](https://github.com/godotengine/godot/files/2453902/FPS.zip)

**Comment by AndreaCatania** [comment]
From the video doesn't seems that the box bounces

**Comment by capnm** [comment]
> doesn't seems that the box bounces

LGTM, checked master with Linux and that's right.

**Comment by Mintormo** [comment]
> From the video doesn't seems that the box bounces
Yes. This problem solved. But there are problem of margin collision shape. In video that seems.

**Comment by AndreaCatania** [comment]
Oh ok, Ther's another issue open for the margin so feel free to close this one

**Comment by Mintormo** [comment]
Ok. Thanks
