### ISSUE TITLE
Auto-complete doesn't detect members/methods of custom class's base classes

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#22807]
**Godot version:**
3.1-alpha ffe94ef

I don't really know how to explain this, so consider this scenario:

```python
# player.gd
extends KinematicBody2D
class_name Player

var lives : int = 3


# something_else.gd
extends Node

var mario : Player # custom class
var luigi : KinematicBody2D # built-in class

func _ready():
    mario.lives # "lives" is member of Player class, WILL appear in autocomplete
    mario.rotation # "rotation" is member of Node2D class, will NOT appear in autocomplete

    luigi.rotation # "rotation" is member of Node2D class, WILL appear in autocomplete
```

Keep in mind that this is only talking about auto-complete; all of the values above will be accessed correctly when run (assuming each variable has an instance assigned...) I'm not sure if this should be considered a bug, but it would definitely be nice to have fixed.

**Comment by scurvycapn** [comment]
I was just about to open an issue for pretty much the same thing (no autocomplete for the inherited class when instancing a node in another scene). Seeing this in 3.1.1
https://www.reddit.com/r/godot/comments/bk45wt/autocomplete_limitations_when_instancing_a_scene/
Here's a sample project if it helps.
[AutocompleteTest.zip](https://github.com/godotengine/godot/files/3143898/AutocompleteTest.zip)

**Comment by JohnMeireles** [comment]
Not sure if this is related, but I noticed that the tooltips do not show the arguments of custom classes' methods.

**Comment by akien-mga** [comment]
Seems to work fine in the current master branch.

Note that the example in OP is wrong:
```
# something_else.gd
extends Node

var mario : Player # custom class
var luigi : KinematicBody2D # built-in class

func _ready():
    mario.lives # "lives" is member of Player class, WILL appear in autocomplete
    mario.rotation # "rotation" is member of Node2D class, will NOT appear in autocomplete

    luigi.rotation # "rotation" is member of Node2D class, WILL appear in autocomplete
```

This can't work, as `mario` and `luigi` are not assigned any value (only a type, but they're `null`).

It should be:
```
var mario : Player = Player.new() # custom class
var luigi : KinematicBody2D = KinematicBody2D.new() # built-in class
```
