### ISSUE TITLE
Texture Region Obfuscates Sprite2D

### ISSUE THREAD

**Issue by Claptrapwubwub** [godotengine/godot#22813]
**Godot version:** 3.0.6

**OS/device including version:** Windows 10

**Issue description:** When using the Texture Region to define a Sprite2D's enabled Region Rect, Iv found that the sprite is obfuscated and random pixels are added to the image that dont exist in the Sprite's Texture .png resource.

**Steps to reproduce:** Unclear

**Picture of bug:**
![untitled](https://user-images.githubusercontent.com/27471194/46575855-8a630500-c972-11e8-98de-01532d6a5e94.png)

**Comment by DavidSichma** [comment]
Godot uses the outmost pixels to extend the texture. Making the region as small as possible and not contain any pixels outside the texture should fix the issue. Or add a border of transparent pixels to the image.

**Comment by Claptrapwubwub** [comment]
> 
> 
> Godot uses the outmost pixels to extend the texture. Making the region as small as possible and not contain any pixels outside the texture should fix the issue. Or add a border of transparent pixels to the image.


The image has a transparent canvas to begin with, and yes, making the region on the edge of the image fixes this but isn't ideal when using sprite-sheets and have this happen on seemingly random sprites.

**Comment by CptPotato** [comment]
There's an import option "fix alpha border" if I remember correctly.
