### ISSUE TITLE
Scene file breaking bug when not saving a GDScript resource

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#2281]
**After a while I've noticed that my disk was full, that's why the save was corrupted. Anyway GODOT tried to save and didn't report an error, so I guess this is a bug anyway. Leaving old description here just for the sake...**

So I just got my test scene wrecked by this bug, and since I didn't use GIT or anything.. RIP work :D (maybe use temp .scn files for recovery in the future?)

Anyway, tl;dr - ~~if you add a GDScript resource and not save it, but you save the scene it basically corrupts the scene [1.1stable]~~ (insufficent disk space was the cause of this, GODOT didn't notify about it)

Reporduction:
1. Create a new scene
2. Create a main node of somekind (doesn't matter which class)
3. Go to Resources tab, add a resource of type GDScript
4. Write something in the code editor, for example `extends Node`
5. Click around the editor, or wait a couple of seconds, the editor's tab name turns into `(*)` which suggests an unexpected behaviour
6. CTRL+S saves the scene instead of the GDScript file, which is counter-intuitive, anyway save the scene
7. Try to load the just-saved scene (or load another one and try to load this scene again)
8. Ooops! `Error loading scene`

~~Result: Scene file is corrupted, overwriting previous work on the scene
Binary-wise the file has a bit of junk, that's it (a few bytes maybe, truncating the scene completely).~~

What I was trying to achieve while finding this bug:
I wanted to create a GDScript that was not attached to a node right away. I've created a resource, but then I changed my mind so I removed it quickly. I couldnt close the editor's tab (another bug) so I just thought it's a little bug and decided to save the scene and reload the editor.

**EDIT: in short - GODOT doesn't detect full disk space (errors while saving a scene)**

**Comment by WalasPrime** [comment]
Appearantly it was a disk space issue. Godot never noticed that, the console didn't show up an error. Anyway I guess things noticed in the description could be useful in some things.

**Comment by WalasPrime** [comment]
Same thing goes for the script editor: if saved when disk is full there is no error notification. File is simply corrupted (trimmed to zero or few bytes)

**Comment by felipefacundes** [comment]
This is a bug for sure. I'm going through the same problem. Every time this happens, I have to create a new project and port everything there, which slows down production a lot. It gets in the way too much! And also if you try to "save as" it doesn't allow overwriting. I'm using the latest stable version of Godot 3.4.2. Please check this as it is a bug that was present in previous versions. Look at this post is from 2020 and it hasn't been fixed yet. 

In my case my problem is not with the GDScript itself, but with saving an existing scene that I had to change, when creating a node or when I am going to change the scene 

I reported this error as well 
https://godotengine.org/qa/80242/scene-not-saving

**Comment by Calinou** [comment]
@felipefacundes Please don't bump old closed issues by copy-pasting the same message. This bug is already being tracked in https://github.com/godotengine/godot/issues/40366.
