### ISSUE TITLE
Drag and drop files to editor file manager fails and throws errors.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22815]
**Win10 64-bit alpha 3.1 aad70d5**  (Seen in earlier commits as well.)

I haven't pinned down exactly what might be triggering it, but at least I got this to happen after deleting files.  Sometimes it is working fine, other times it is broken.

I recreated it at least after deleting some images in the editor first.  Afterwards a drag and drop of new images will fail and throw this error.

![godot_master_2018-10-07_01-24-32](https://user-images.githubusercontent.com/13004169/46576374-b1e8ba80-c9d0-11e8-9602-eb5f8274b718.png)

## Drag and Drop Failing

![ezgif com-optimize](https://user-images.githubusercontent.com/13004169/46576379-c0cf6d00-c9d0-11e8-9e2a-184c6444f440.gif)

**Comment by avencherus** [comment]
Still happening as of a recent build.

Happens when I drag in images, then drag an image to the canvas (making it a sprite), then try to continue dragging in additional image resources from the file system to the dock.

**Comment by KoBeWi** [comment]
Doesn't seem to happen in d711c57d7 
@avencherus Can you test again?

**Comment by avencherus** [comment]
@KoBeWi Appears resolved.  Don't see it in 3.1.1 or the master currently.  I suppose I don't very often delete things and then start importing with a drag and drop, so hadn't noticed it was fixed.  Wondering what commit it might be.
