### ISSUE TITLE
Evaluate GDScript dynamically

### ISSUE THREAD

**Issue by sancarn** [godotengine/godot#22814]
I know about #8003, but that seems to be barking up the wrong tree to be honest... 

I'm building an application in godot and I'm wanting to provide a way for users to extend the application with "addons". So for example, say I want to allow developers to add their own custom UI to my application... Well, I was hoping that I'd be able to expose GDScript directly to them, so they can simply execute GDScript, in runtime to build a custom UI.

I know this isn't exactly a traditional use case of the game engine, and I'm only really planning to use Godot due to the 3d engine which it provides... The programming language isn't super important as it is likely plausible I can build my own interprated language in GDScript anyway, but it would be somewhat nice if there were native support for running GDScript in runtime.

**Comment by vnen** [comment]
Well, you can do that already by creating a GDScript resource and setting its source code. Then you can instance it and call its functions like any other script.

**Comment by sancarn** [comment]
Huh? How do you add a random GDScript on the file system to the resources?

**Comment by pgruenbacher** [comment]
yep that looks right. There's other ways too
http://docs.godotengine.org/en/3.0/classes/class_gdscript.html?highlight=gdscript

```
var MyClass = load("myclass.gd")
var instance = MyClass.new()
assert(instance.get_script() == MyClass)
```

@sancarn please close when you can.

**Comment by pgruenbacher** [comment]
i'd also recommend you just have your users learn gdscript. I'm not sure how I'd go about sandboxing users...

**Comment by Zylann** [comment]
@pgruenbacher this works as a dynamic way to execute scripts, but `load` only works on the game's own resources AFAIK

**Comment by pgruenbacher** [comment]
good point... what we'd need to test is if load works on the User data.... my guess is load("user://myclass.gd") should still work... So I'd say yes.

as for sandboxing, I think this is mostly possible. The gdscript::init() method will inject Global variables into the scope of the script. We could maybe propose a GDScriptBox resource subclass that does not inject global variables automatically ( but still allows for manual injection). That will prevent game users from accidentally making changes to the root node or Engine.

**Comment by sancarn** [comment]
Huh? Can't you simply load from a file system path. E.G. `load("/some/file/dir")` ?

**Comment by pgruenbacher** [comment]
you can try. I haven't tested.

**Comment by sancarn** [comment]
Just tested, you can! :D

Though I have looked around a bit and I wouldn't even know how to do a directory tree in gdscript... I can understand it... It's not common practice for games to be looking at the file system in general... 

Anyway...

**Conclusions**

```
var MyClass = load("some/cool/file.gd") #this can also be a user:// or res:// path
MyClass.staticMethod()
var instance = MyClass.new()
#dostuff
```

or can also use new gdscripts

```
var script = GDScript.new()
script.source_code = "func say_hello():\n\tprint(\"Hello!\")"
script.reload()
var script_instance = script.new()
script_instance.call("say_hello")
```

Thanks both for the input!

**Comment by Fran6nd** [comment]
Hi guys, may I reopen the topic?
What about now in 2022... I now previous answers are still working but is there a way to sandbox dynamically evaluated scripts?

**Comment by Calinou** [comment]
> Hi guys, may I reopen the topic? What about now in 2022... I now previous answers are still working but is there a way to sandbox dynamically evaluated scripts?

This is being tracked in https://github.com/godotengine/godot-proposals/issues/389. There are no immediate plans to work on this for 4.0 though.

**Comment by nihiluis** [comment]
> > Hi guys, may I reopen the topic? What about now in 2022... I now previous answers are still working but is there a way to sandbox dynamically evaluated scripts?
> 
> This is being tracked in [godotengine/godot-proposals#389](https://github.com/godotengine/godot-proposals/issues/389). There are no immediate plans to work on this for 4.0 though.

does that mean that the dynamic evaluation is still working in Godot 4 or was it disabled?
