### ISSUE TITLE
test_move() asking for 3 arguments with KinematicBody2D.

### ISSUE THREAD

**Issue by 9BitStrider** [godotengine/godot#22829]
![untitled](https://user-images.githubusercontent.com/23580375/46582859-4411b280-ca13-11e8-9603-c4029fec0404.png)

I get this error when using test_move() on 3.1.0 alpha. Running on Windows 7, 32bit, GLES2

**Comment by KellyThomas** [comment]
Here is the documentation note a third paramter `infinite_inertia`

http://docs.godotengine.org/en/latest/classes/class_kinematicbody2d.html#class-kinematicbody2d-test-move

I guess we could ask if it should have a default value of `false`?

**Comment by DavidSichma** [comment]
#16757 added this new parameter to the movement related methods of KinematicBody (2D and 3D). The default values have been set to `infinite_inertia = true` in the other bindings, but not for this method.

@AndreaCatania Adding `DEFVAL(true)` should fix it. Or is there a reason why this wasn't added?
Speaking of infinite_inertia, there is an incosistency. The 3D `KinematicBody::move_and_slide` is the only method with infinite_inertia being the last argument. Could be corrected as well.
