### ISSUE TITLE
user:// in String::simplify_path() is using the wrong substr value?

### ISSUE THREAD

**Issue by exts** [godotengine/godot#22828]
**Godot version:**
Master (and probably all?)

**Issue description:**
So I was looking at the source to see if #22825 was possible and came across `String::simplify_path()` that has a user:// footprint w/ my search.  Then I noticed on line 3095, the substring value might be incorrect? Because `local:// = 8`, `res:// = 6` and `user:// = 6` ? although user is one character greater than `res://`

You can see it here https://github.com/godotengine/godot/blob/master/core/ustring.cpp#L3095

**Comment by Awalvie** [comment]
Beginner question here I just supposed to submit a PR to get it updated right ?
