### ISSUE TITLE
Suggestions are missing for overriding own methods in GDScript

### ISSUE THREAD

**Issue by TheFlamyy** [godotengine/godot#22821]
**Godot version:** f28b03249

**Issue description:**
When working in a script file which is extending another file e.g. `extends "res://path/to/script.gd"` the editor does not suggest any of the defined methods to override. (Even when starting with `_`)
The [style-guide](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html) suggests that virtual functions should be marked with an `_` thus this seems like a missing feature/bug from the editor-side.

**Steps to reproduce:**
Create script A which has a custom function `_custom_function`
Create script B which extends script A.
Try to write `func _custom_` in the script editor window. `_custom_function` is not present.

**Comment by KoBeWi** [comment]
Closing this in favor of a proposal: https://github.com/godotengine/godot-proposals/issues/393, as it's not really a bug.
