### ISSUE TITLE
Bullet warning when PhysicalBone is deleted

### ISSUE THREAD

**Issue by abrenneke** [godotengine/godot#22823]
**Godot version:**

3.1 master -> f12cb82

**OS/device including version:**

Windows 10 Home

**Issue description:**

When a PhysicalBone is deleted, a warning appears:

```
WARNING: RigidBodyBullet::assert_no_constraints: A body with a joints is destroyed. Please check the implementation in order to destroy the joint before the body.
At: modules\bullet\rigid_body_bullet.cpp:442   
```

**Steps to reproduce:**
`queue_free` a `PhysicalBone` node (or any of its parents) that is attached to a skeleton.

**Minimal reproduction project:**

[physical-bones-crash.zip](https://github.com/godotengine/godot/files/2430780/physical-bones-crash.zip)

Same project as #22538 - the warnings happen, but currently the editor crashes afterwards for me.

**Comment by akien-mga** [comment]
Is the warning still reproducible in the current master branch?

**Comment by KoBeWi** [comment]
Still happens on b7cf4c2

The reproduction project also produced some errors that appeared on 3.1 stable, but now only the warnings remains.
