### ISSUE TITLE
Support parenting setups in Collada I/O

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#2283]
Currently
-------------------------------------------
Godot will import the parent object, but discard the child object. This might be due to a lack of support of the import of object parenting setups in both the *better collada exporter* and Godot's importer.

Proposal
--------------------------------------------
Support all forms of parent/child relationships in both the exporter and the importer (and have the generated nodes resemble that setup as seen in the 3D application)

Benefits
----------------------------------------------
It will make it a lot easier to create things like unique moving platforms (made just for a certain level), make it easier to create level-specific objects and allow one to increase the amount of level building work in the 3D application

I hope adding this will be seen as useful

Thanks.

**Comment by romulox-x** [comment]
Can you give an example of when the parent child relationship isn't maintained?  I just tried importing a mesh as a child of another mesh that I exported from blender with bettercollada, and it worked fine, as far as I can tell.

**Comment by slapin** [comment]
Works for me, too

**Comment by Ace-Dragon** [comment]
The situation I saw was that parenting setups weren't imported properly when I added it to an existing collada file and a did a re-import with the *keep materials, merge with new* option.

Maybe the issue is it doesn't work with all import modes.

**Comment by slapin** [comment]
Nothing but Overwrite existing scene really works, but that is different
issue.

**Comment by akien-mga** [comment]
Can you still reproduce this issue @Ace-Dragon?

**Comment by Ace-Dragon** [comment]
Hi Akien; Yes, it seems to be working now (even though I have to completely close the scene by clicking the X and re-open it to see any changes made).

**Comment by akien-mga** [comment]
> (even though I have to completely close the scene by clicking the X and re-open it to see any changes made).

Yep, I believe that would be #2307
