### ISSUE TITLE
No way to detect button state changes within a ButtonGroup

### ISSUE THREAD

**Issue by akerudesu** [godotengine/godot#22839]
**Godot version:** 3.0.5+

**Issue description:**
Currently there doesn't seem to be a way to get state change information from a ButtonGroup:
- A button's "toggled" method/signal does not fire whenever another button in the group is toggled on (and therefore every other button's state is forced to off).
- ButtonGroup doesn't expose `ButtonGroup::get_buttons` so we can't connect to signals of each individual button without knowing in advance what buttons belong to the group.
- ButtonGroup has no signals for when a button's state within the group changes.

For some context, I'm trying to animate certain properties of a button whenever it gets toggled off.

**Comment by tom-jk** [comment]
State of issue as of Godot 3.2.3.beta1:

1. When the selected button in a button group changes, both the previous and new selected buttons send "toggled" signals.
2. ButtonGroup get_buttons() is now exposed in gdscript.
3. ButtonGroup does not have any signals still.

----

Here's a demo project: [22839.zip](https://github.com/godotengine/godot/files/4985015/22839.zip)
It demonstrates points 1 and 2. As a basic workaround for point 3, it also fakes buttongroup signals by emitting a custom "button_group_changed" signal each time one of a group's buttons is toggled.

<details><summary>minimal script and sample project output</summary>

On game start we inspect all buttons to discover button groups, and for each group connect every button's "toggled" signal to a function.

```gdscript
extends Control

signal button_group_changed(button_group)

onready var btn_groups = []

func _ready():
	self.connect("button_group_changed", self, "_on_button_group_changed")
	
	for child in get_children():
		if not child is CheckBox:
			continue
		
		var group = child.group
		if group == null or group in btn_groups:
			continue
		
		btn_groups.append(group)
		var buttons = group.get_buttons()
		for cb in buttons:
			cb.connect("toggled", self, "_on_GroupButton_toggled", [cb])

func _on_GroupButton_toggled(button_pressed, button):
	emit_signal("button_group_changed", button.group)

func _on_button_group_changed(group):
	pass
```

```
(note: connect returns 0 = OK)
Discovered button group: [ButtonGroup:1181] MyBtnGroup has 3 buttons
[CheckBox:1183]	CheckBoxA3	Option 3	connect returns: 0
[CheckBox:1182]	CheckBoxA2	Option 2	connect returns: 0
[CheckBox:1180]	CheckBoxA1	Option 1	connect returns: 0
Discovered button group: [ButtonGroup:1185] MyOtherBtnGroup has 2 buttons
[CheckBox:1184]	CheckBoxB1	Option 1	connect returns: 0
[CheckBox:1186]	CheckBoxB2	Option 2	connect returns: 0
checkbox in MyBtnGroup toggled: CheckBoxA1 is now ON
checkbox in MyBtnGroup toggled: CheckBoxA1 is now OFF
checkbox in MyBtnGroup toggled: CheckBoxA2 is now ON
checkbox in MyBtnGroup toggled: CheckBoxA2 is now OFF
checkbox in MyBtnGroup toggled: CheckBoxA3 is now ON
checkbox in MyOtherBtnGroup toggled: CheckBoxB1 is now ON
checkbox in MyOtherBtnGroup toggled: CheckBoxB1 is now OFF
checkbox in MyOtherBtnGroup toggled: CheckBoxB2 is now ON
```

</details>
