### ISSUE TITLE
Shift-Space / Ctrl-Space as shortcut for distraction free mode in text editor view

### ISSUE THREAD

**Issue by tofuhead** [godotengine/godot#22847]
**Godot version:**
current master

**OS/device including version:**
Xubuntu 18.04

**Issue description:**
assigning Ctrl-Space, or Shift-Space to toggle distraction free mode works with other viewspaces, except text editor component. would it be possible to add this back, as I remember it used to work in old Godot..?

**Comment by voithos** [comment]
Does this have to be Ctrl-Space? I think I have the default shortcut settings, and it's listed as Ctrl+Shift+F11 for me.

![screenshot from 2018-10-16 22-44-24](https://user-images.githubusercontent.com/744228/47064719-6c2cae80-d195-11e8-9e0f-36114afc0b1d.png)

Also seems to properly enable distraction free mode in the text editor:

![screenshot from 2018-10-16 22-45-38](https://user-images.githubusercontent.com/744228/47064735-79499d80-d195-11e8-9183-eb265d6ae641.png)

**Comment by tofuhead** [comment]
well.. ctrl-shift-f11 works.. but its not very handy combination imho. 
i like blenderway so i set that up on other apps where possible too.

. b

**Comment by dreamsComeTrue** [comment]
Why does have to be specifically Ctrl + Space? It's not a wise choice, as most of developers are used to "code-autocomplete" being assigned to that shortcut.

**Comment by akien-mga** [comment]
I agree that any combination with Space would likely be problematic as it conflicts with various other use cases, such as code completion as mentioned above.

As we already have a shortcut for this mode and no other user voiced support for changing it, closing.
