### ISSUE TITLE
Keyboard shortcuts for opening previously closed scene and switching between them

### ISSUE THREAD

**Issue by pshe94** [godotengine/godot#22846]
**Godot version:**
3.0.6

**OS/device including version:**
Arch Linux

**Issue description:**
Would it be possible to add a keyboard shortcuts to: 
- open previously closed scene (like `ctrl+shift+t` in Firefox) 
- switch to previous and next scene (`ctrl+tab` and `ctrl+shift+tab` in Firefox)?

**Comment by merumelu** [comment]
> switch to previous and next scene (`ctrl+tab` and `ctrl+shift+tab` in Firefox)?

Looks like these already exist but don't work because `tab` in shortcuts is broken: #8799.

**Comment by KoBeWi** [comment]
Adressed by #27952 too.
