### ISSUE TITLE
IDE has high CPU usage while idling

### ISSUE THREAD

**Issue by Bios-Marcel** [godotengine/godot#22845]
**Godot version:**
3.0.6

**OS/device including version:**
Macbook Pro mid 2014
MacOS Mojave
i5 2.8Ghz dual core
16GB RAM
500GB SSD
Intel Iris 1536MB

**Issue description:**
I have a rather small project which has like 4 tiny scenes and almost no code written.
I just have the IDE open and the game is not running, but my CPU usage is at 25% or more. Other applications don't really use CPU at all.

I am not sure if this is normal or an issue, however it seems quite weird to me.

**Steps to reproduce:**
Just open Godot.

**Minimal reproduction project:**
Just clone this: [top-down-pew-pew](github.com/Bios-Marcel/top-down-pew-pew)

**Comment by ni-code** [comment]
That seems a bit higher than usual, I've tested idleling in one of my projects, but cpu stays around 5%, with an occasional spike up to 20%.
Also had Firefox in the background with a few tabs open, and the system monitor opened as well.

Although I'm not on macos, I'm on solus linux, i5 3.4Ghz 16Gb ram, nvidia gts450.

![screenshot from 2018-10-07 23-46-21](https://user-images.githubusercontent.com/10292929/46587928-b02ffd00-ca8b-11e8-8585-aba0c11445b8.png)

**Comment by Bios-Marcel** [comment]
I usually use a desktop with solus aswel, it's quite powerful and obviously doesn't rely on a battery, so I didn't notice any problems over there. However, the problem on my macbook is that it just drains my battery.

Anyway, hardwarewise I can't even compare the desktop to the macbook.

**Comment by eon-s** [comment]
Probably a vsync issue? there are a couple of closed issues with similar subjects, like #8766

**Comment by Bios-Marcel** [comment]
I am not talking about the game, but the IDE itself.

**Comment by eon-s** [comment]
Check that and related issues, there are comments about the editor.

**Comment by exts** [comment]
wonder if it has to do with that bug where scripts are running inside the editor.

**Comment by jeremyherbert** [comment]
I also have this problem on OSX high sierra, macbook late 2013. 

All I do is open godot, import the "platformer 2D" example, and my CPU is constantly at 68-75%

**Comment by Chaosus** [comment]
> I just built godot from the latest master source, and this problem no longer appears to exist.

Ok, let's accept that it's fixed..
