### ISSUE TITLE
Owner variable is null on tree_exiting signal

### ISSUE THREAD

**Issue by pshe94** [godotengine/godot#22840]
**Godot version:**
3.0.6 and 3.1 alpha1

**OS/device including version:**
Arch Linux

**Issue description:**
Let's assume that there is a very simple instanced scene:
```
Owner
│
└── Node
```
`Node` node has script attached, that connects to the `Owner` `tree_exiting` signal. When this signal is emitted, I would like to access the `Owner` node by using `owner` variable (or `get_owner` method). Unfortunately, when this signal is emitted, this variable is already set to `null`, even though `Owner` node is still the owner of the `Node` (I can access `Owner` node by using `get_parent`).
Of course I could pass the `owner` in `binds` array in `connect` method, use `get_parent` method, store reference to the owner in a different variable, or create my own signal and method for deletion of the `Owner`. I'm just not sure if this is expected behavior, because `tree_exiting` signal is emitted before the node and its children are removed, so `owner` should still be accessible.

**Steps to reproduce:**
1. Create a node
2. Add a child to that node
3. Connect the child to the owner's `tree_exiting` signal
4. Try to access `owner` variable in a method that is called on the emission of the signal in point 3

**Minimal reproduction project:**
[Project created in version 3.1 alpha1](https://github.com/godotengine/godot/files/2454277/3.1.zip)

When playing the project, press Delete key on keyboard to delete the `Owner`. 
Look at the Output in the Editor window. Notice the `Owner: [Object:null]` (`owner` variable) and `Parent: [Spatial:XXXX]` (`get_parent` method).
All the code is in the `Child.gd` file.

**Comment by J08nY** [comment]
The issue is at https://github.com/godotengine/godot/blob/b17e71b6e5e035f49b5b3b5b55b9cdac80215d72/scene/main/node.cpp#L145

where the owner is set to `NULL` before `tree_exiting` is ever emitted, not sure what the right fix here is.

**Comment by Sslaxx** [comment]
I'd expect that behaviour of `tree_exited`, where the node has left the scene tree, but exiting is before/during, so should ownership still be a valid thing?

**Comment by groud** [comment]
The signal might be renamed indeed.
