### ISSUE TITLE
Errors when importing dae model

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22848]
**Godot version:**
3.1 b17e71b

**OS/device including version:**
Windows 10 

**Issue description:**
When I try to import dae model(only this one attached to minimal project), then a hundreds of error  is shown:

> ERROR: get_quat: Condition ' !is_rotation() ' is true. returned: Quat()
   At: core/math/matrix3.cpp:603
ERROR: orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core/math/matrix3.cpp:80

**Minimal reproduction project:**
[AA.zip](https://github.com/godotengine/godot/files/2455523/AA.zip)

**Comment by glaforte** [comment]
I'm looking into this issue, right now.
I reproduced the issue and I reviewed the COLLADA document.
The document contains animations where the animation output are transforms where the upper-left triangle is all zeroes (id-anim-65, id-anim-66, id-anim-67....)
...
I think that having a transform where the scale is zero is valid, if uncommon. But it does mean that there is no rotation information to extract from the transform. So, I propose detecting the zero scale vector during the COLLADA animation import and not extracting an orientation quaternion from the transform - to avoid spamming the user.
