### ISSUE TITLE
Godot starts with empty project manager window

### ISSUE THREAD

**Issue by Myran** [godotengine/godot#22856]
**Godot version:**
Master
0063ba92075094b7cc9d36f4551080b89e0c0e50

**OS/device including version:**

macOS 10.14

**Issue description:**

Project manager window is empty on startup

https://user-images.githubusercontent.com/867873/46627618-52f38480-cb3b-11e8-988c-4af128a085bf.png)

**Comment by Baekalfen** [comment]
As a temporary fix, try minimizing and bring the window back. Or if you have two monitors, try to move it from the one to the other. That seems to work for me.

**Comment by KoBeWi** [comment]
This sounds like a temporary issue on master branch which is likely already fixed.
