### ISSUE TITLE
Particles2D change mask submenu location

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#2285]
I think it's more intuitive to have the Particles Mask menu inside the inspector with the rest of the properties.
I've been looking for a "mask" property for an hour. I even looked inside the .xml file in the Particles2d demo project. There's where I found the Vector2Array of positions.

That's it, I think its more user friendly.

**Comment by okamstudio** [comment]
Yes this is a problem, many nodes use this kind of menu and it's not
obvious that something appears, I was wondering for a while how to make it
more obvious

On Mon, Jul 20, 2015 at 7:52 PM, Federico <notifications@github.com> wrote:

> I think it's more intuitive to have the Particles Mask menu inside the
> inspector with the rest of the properties.
> I've been looking for a "mask" property for an hour. I even looked inside
> the .xml file in the Particles2d demo project. There's where I found the
> Vector2Array of positions.
>
> That's it, I think its more user friendly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2285>.
>



-- 

*OkamStudio*

**Comment by FEDE0D** [comment]
This works fine with the new UI redesign as other tools also appear on this spot of the editor for other node types.
