### ISSUE TITLE
Customizable GooglePayment module

### ISSUE THREAD

**Issue by deepmax** [godotengine/godot#22851]
Godot has a module to implement Google In-app purchase, however for local markets which they have localized in-app purchase APIs or SDKs, this module wouldn't work.

Some markets have APIs as same as GooglePaymentV3 and Godot's payment module can be used if it was possible to change these constant strings, so we don't have to implement our own module. 

```
/*
 This file is located at: 
 godot/platform/android/java/src/org/godotengine/godot/payments/PaymentsManager.java
 Line 77-78
*/

Intent intent = new Intent("com.android.vending.billing.InAppBillingService.BIND");
intent.setPackage("com.android.vending");
```

Is it possible to set these strings as parameters somewhere in the project?

**Comment by m4gr3d** [comment]
The GooglePayment module was moved outside of core to https://github.com/godotengine/godot-google-play-billing
