### ISSUE TITLE
Display raycast in game

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#22862]
It's useful to display raycast in game to debug gameplay.

https://github.com/DevMagicLord/Godot3/blob/master/bugs/download/raycast.jpg?raw=true

**Comment by antoniotorresm** [comment]
You can do it by enabling `Debug > Visible Collision Shapes`.

**Comment by pgruenbacher** [comment]
@akien-mga can close.

**Comment by DevMagicLord** [comment]
It doesn't display in game.

Raycast visible in the editor , raycast not visible in game.
https://github.com/DevMagicLord/Godot3/blob/master/bugs/download/raycastingame.jpg?raw=true

**Comment by akien-mga** [comment]
@DevMagicLord You open many issues for things which are already supported in the engine. Please ask on [other community channels](https://godotengine.org/community) first before assuming that they need to be implemented in the engine, this issue tracker should stay focused on things that developers actually have to work on.
