### ISSUE TITLE
Editor can't select animated models

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#22860]
I'm using the tps demo.

Robots can't be selected, clicking with mouse on them always select underlying geometry.

https://github.com/DevMagicLord/Godot3/blob/master/bugs/download/norobotselect.jpg?raw=true

**Comment by Ace-Dragon** [comment]
I think Godot 3.1 alpha 1 official had a regression that prevented scene instances from being selectable while in select mode.

That has since been fixed however. You can download nightly builds at https://hugo.pro/projects/godot-builds/ to verify

**Comment by DevMagicLord** [comment]
Downloading.
