### ISSUE TITLE
Scene dock doesn't update position of rename popup when changing nodes by arrows

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22879]
**Godot version:**
3.1 c730957

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When I try to change selection in Scene dock by up and down arrows, then when I click Enter, the popup shows in wrong position

**Steps to reproduce:**
1. Open attached project
2. Open Sticky Grenade Scene
3. Click at the some of child of grenade
4. Click up or down arrow and click Enter

https://streamable.com/8t2xn

**Minimal reproduction project:**
[FPS FIRST.zip](https://github.com/godotengine/godot/files/2460076/FPS.FIRST.kopia.zip)

**Comment by KoBeWi** [comment]
Fixed in 3.2
