### ISSUE TITLE
AnimationTreePlayer mix/blend nodes also mixes original translation.

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/godot#22878]
**Godot version:**
3.1 master

**OS/device including version:**
Fedora 28, 64-bit.

**Issue description:**
Using mix/blend nodes will also mix the original translation of the node with 0,0,0.

**Steps to reproduce:**
1. Create two mesh instances to animate, translate them up to Y position 5.
2. Create an AnimationPlayer and add two animations, one for each of the two mesh instances, perhaps moving them in opposite directions over the X axis or similar.
3. Create an AnimationTreePlayer, set it up for blending the two animations in the AnimationPlayer. Mix them together using a mix (or blend node). Set amount to 0.
4. Toggle "active" so that it triggers the animation.

Expected: the second mesh should remain still at it's original translation (e.g Y position 5), while the other one moves along X.
What happens: the second mesh mixes it's translation with 0,0,0 and ends up at the center bottom of the scene.

As you increase amount of mix the Y position of the second mesh instance will approach 5.

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in 3.1 and will eventually be removed, you should use `AnimationTree` now.
