### ISSUE TITLE
Memory Leak when importing dae file from TPS demo

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22882]
**Godot version:**
3.1 c730957

**OS/device including version:**
Ubuntu 18.04 Nvidia GTX 970 396.54

**Issue description:**
When I importing TPS demo project, when Godot starts to import dae files then memory consumption drastically increase.

It is same issue as https://github.com/godotengine/tps-demo/issues/3 but I think that is a engine issue, so it should be here too.

**Steps to reproduce:**
1. Import FPS demo project and look at the system monitor

https://streamable.com/on0h3 - Leak starts at 5:28

**Minimal reproduction project:**
https://github.com/godotengine/tps-demo

**Comment by akien-mga** [comment]
If I remember correctly, when I was experiencing this issue and trying to debug briefly it seemed related to the thumbnails generation for the FileSystem dock. It has yet to be confirmed, but it's one possible suspect (CC @groud).

**Comment by groud** [comment]
Should be fixed now that #24194 is merged. If it happens again, we will probably reopen #23567 as it is more complete. So closing for now. Thanks :)
