### ISSUE TITLE
Animation tree animates too fast when multiple of the same scene are instanced.

### ISSUE THREAD

**Issue by BanjoCollie** [godotengine/godot#22887]
**Godot version: 3.1 alpha 1**

**OS/device including version: Windows 10**

**Issue description:**
If a node is animated by an AnimationTree and it is instanced multiple times, each instance runs the animation faster. Two instances seems to double animation speed, three triples, ect. 

**Steps to reproduce:**
Create a scene with an animation player and an animation. Have an animation tree within the scene run that animation. Instance multiple of the first scene within some other scene.

**Minimal reproduction project:**

[Bug Test.zip](https://github.com/godotengine/godot/files/2461249/Bug.Test.zip)

**Comment by kubecz3k** [comment]
I can confirm the issue still occurs in 72db3000a56a6f85d348c218437d1a1dfc0953bf
Gif that presents the issue and my reproduction setup (quick setup based on Platformer 3D demo):
![animtreespeed](https://user-images.githubusercontent.com/6129594/47998805-d5527280-e100-11e8-8988-eb5fed433f9e.gif)

**Comment by kubecz3k** [comment]
From my observations, it seems the issue is more complicated since in my game the player's AnimationTree speed is also directly related to the number of enemies which are instanced in the world (and enemies are not using AnimationTree at all).

**Comment by nagasawamaki** [comment]
I found that the TPS demo hasn't this issue but I also encounter the same issue.
Don't know why.
Anybody knows why TPS demo work?

**Comment by akien-mga** [comment]
See also MRP from #23529: [AnimationTree.zip](https://github.com/godotengine/godot/files/2549412/AnimationTree.zip)

**Comment by DGWana** [comment]
@nagasawamaki How is TPS working for you? If I make a scene with two instances of the robot (player or enemy) the speed increases as with any other AnimationTree scene instance
