### ISSUE TITLE
Unexpose SurfaceTool.add_to_format() or expose arrays

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#22884]
See discussion in https://github.com/godotengine/godot/pull/22872

**Comment by clayjohn** [comment]
My preference is to remove the method. Exposing the arrays would be very handy for some purposes but would add a lot of complexity to the tool and potentially introduce bugs. It would be a good idea to just remove access to the method from GDscript for the 3.1 release and then discuss expanding access to arrays for 3.2. 

The method itself seems to be as old as  the engine itself and currently unused. It was exposed to GDscript in PR #9993 without much discussion over the benefits/risks of adding it.
