### ISSUE TITLE
[Bullet] Inconsistent generation of Area body_entered/body_exited signals

### ISSUE THREAD

**Issue by muiroc** [godotengine/godot#22889]
**Godot version:**
0063ba9

EDIT:
Partially fixed by #25180  see comment below

**Issue description:**
Area entered/exited signal appears invalid, compared to GodotPhysics

StaticBody enters an Area, a body_exited is generated right after a body_entered.

KinematicBody same thing, as soon as it stops moving.

RigidBody looks like it works ok, maybe because its always moving (in the sample)

In godotphysics disabling a shape doesnt trigger body_exited

**Steps to reproduce:**
See sample project:
- move the blue "character" with arrows keys
- the button list on the right enables/disables the collision shapes
- check the console messages
- try the same with GodotPhysics

**Minimal reproduction project:**
[bug_area_exit.zip](https://github.com/godotengine/godot/files/2461203/bug_area_exit.zip)

**Note**
Other stuff observed in the sample, outside the scope of the Issue:
- I mentioned in another issue that this problem was also in godotphysics but looks like its working ok
- sometimes the initial rigidbody velocity setted in editor doesn't get applied and the ball was "stuck in air" until something interacted with it (this also happened in other projects but i can't reliably repro it)
- the character now pushes the rigidbody, even with infinite_inertia==false, but i'm pretty sure it didnt before, while creating the sample?! feel free to disregard this lol
- Made that overly complex sample... but forgot to test Area vs Area signals...

**Comment by muiroc** [comment]
Partially fixed by #25180 

Correctly, now the exited signal is not called just as soon the body stops moving, while overlapping.

The remaining issue is that when the blue character overlaps the green area, if you disable the area's collision shapes, the exited/entered signals are not called

**Comment by akien-mga** [comment]
> The remaining issue is that when the blue character overlaps the green area, if you disable the area's collision shapes, the exited/entered signals are not called (BOTH in godotphysics and bullet)

Tested in the current master branch, and it seems like the `exitered` and `entered` signals are properly called when you disable/enable the collision shapes, but only *once* the character moves, thus updating the collision checks. I'd tend to say that it's OK as is, WDYT?

**Comment by muiroc** [comment]
The current behavior is kinda unintuitive, but technically understandable

For example, sleeping rigidbodies are behaving similarly: the callbacks are not called until they wake

So we could think of a KinematicBody that is not move_and_colliding as if it was in a "sleeping" state
Nothing a little documentation can't solve

Still, Godot is about usability and intuitiveness: if I were a beginner I would expect signals to be fired,
even when my characters and movers are not moving, since I see them standing in the right spot

I guess its better to close this, and later formalize all the expected physics behaviors for the planned physics rewrite

**Comment by akien-mga** [comment]
According to @reduz this sounds like a bug more than intended design:
```
14:43 <reduz> thats odd, if collision is disabled it should trigger it almost immediately
14:44 <reduz> well, at least in the next physics iteration
```

**Comment by akien-mga** [comment]
For the reference, since it's similar I checked if #33615 fixes this issue, but it doesn't appear to.

**Comment by muiroc** [comment]
Just an hint: adding this line
```
isTransformChanged = true;
```
for example before this line
https://github.com/godotengine/godot/blob/045a5ce14a22384b236e5a4fddeeb999e1c46f41/modules/bullet/collision_object_bullet.cpp#L324

seems to fix the issue in bullet, probably something about this condition
https://github.com/godotengine/godot/blob/045a5ce14a22384b236e5a4fddeeb999e1c46f41/modules/bullet/space_bullet.cpp#L699

But I'm not sure which is the correct place to set isTransformChanged, or if it needs another dirty state flag
