### ISSUE TITLE
Shader: VIEWPORT_SIZE is only defined for SSR shaders

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22897]
Godot version:
3.1 alpha 4c1a5d9

OS/device including version:
Mac OS X High Sierra

**Issue description:**
VIEWPORT_SIZE is unknown identifier in Shader GLSL.

**Comment by Zireael07** [comment]
Are you using GLES3 or GLES2?

**Comment by Chaosus** [comment]
VIEWPORT_SIZE currently exist only for spatial type of shader. Do you use it with spatial or canvas_item(where its not defined)

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
My test also reveal VIEWPORT_SIZE doesn't give meaningful or useful values. The value of x is 0.095 for 1920 x 1080 resolution. According to tests I read GLES2 provides the actual viewport size and only GLES3 does not.

**Comment by clayjohn** [comment]
Regarding aliens comment. VIEWPORT_SIZE is defined for all Spatial shaders here 

https://github.com/godotengine/godot/blob/7d710a745e3eecbde482349fff78f0a4e14f6371/drivers/gles3/rasterizer_scene_gles3.cpp#L4177

Regarding carlgustavs comment, you are just restating the bug from https://github.com/godotengine/godot/issues/19900

Accordingly, closing in favour of https://github.com/godotengine/godot/issues/19900
