### ISSUE TITLE
Style box does not refresh changes to nodes using it in editor viewport.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22895]
**Godot version:**
3.1 alpha 4c1a5d9

**OS/device including version:**
Mac OS X High Sierra

Making changes to styles for button attributes (e.g. colors and borders widths), does not get reflected in the viewport unless you click and drag the button.

See attached GIF. Of course this maybe issue in general

![styleboxbug 2018-10-09 17_47_01](https://user-images.githubusercontent.com/930478/46700899-1469d280-cbec-11e8-9e9f-e9e09e9b71f8.gif)

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by KoBeWi** [comment]
Nope, appears to be fixed.

**Comment by groud** [comment]
Thanks for testing @KoBeWi , closing then :)
