### ISSUE TITLE
Godot over Remote Desktop crashes

### ISSUE THREAD

**Issue by Tordek** [godotengine/godot#2290]
If I try yo start a Godot session over RD, it crashes. If I open a session in the remote machine and access it over RD, it works, until I try running a scene.

As per VS Debugger: 

> Excepción no controlada en 0x7753883d en godot_win64-1.1stable.exe: 0xC0000005: Infracción de acceso al escribir en la ubicación 0x0000000000030c28.

**Comment by deasanta** [comment]
short term workaround:
If you rd to a desktop you may have issues with GL - try vnc / teamviewer / other
for server you can try to enable remotefx
http://blogs.msdn.com/b/rds/archive/2013/11/05/gpu-requirements-for-remotefx-on-windows-server-2012-r2.aspx

**Comment by reduz** [comment]
not sure if there is much to do about it, Godot must be getting a GL context, thus crashing

**Comment by reduz** [comment]
must not be, I mean

**Comment by vnen** [comment]
I will close this then as the issue seems not to be related to Godot. If my guess is proven false, then I'll reopen.
