### ISSUE TITLE
Website says something about MultiplayerAPI, but in Godot, it won't work.

### ISSUE THREAD

**Issue by Sphynxinator** [godotengine/godot#22908]
**Godot version:**
v.3.0.1

**OS/device including version:**
Windows 8.1

**Issue description:**
I tried to use MultiplayerAPI class for Godot, and I wrote some code like this:
`get_tree().multiplayer.connect("network_peer_packet", self, "_network_peer_packet")`
But when I try to run the code, it says "invalid get index 'multiplayer' (on base: 'SceneTree')."
I also tried MultiplayerAPI instead of "multiplayer" and it doesn't recognize the class.

**Steps to reproduce:**
Write `get_tree().multiplayer.connect("network_peer_packet", self, "_network_peer_packet")`,
Run,
Reproduce!

**Comment by Faless** [comment]
There is no mention to the `MultiplayerAPI` class in [3.0 docs](http://docs.godotengine.org/en/3.0/), because the `MultiplayerAPI` class was implemented in `3.1`.
You probably read the `3.1` docs and got confused.
Try that code with `3.1-alpha1` and it will work.
Closing.
