### ISSUE TITLE
Editor: Display Project name (and optionally physical path) in title bar

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22911]
**Godot version:**
ALL
Mac OS X, High Sierra

**Issue description:**
Display the Project Name (and optionally the physical path) of the project in title bar window.

By just looking at FileSystem you cannot tell where your files are. Yes I can click on Open Folder which opens window, but why not display it in title bar?  Similar to what Sublime does would be just fine. 

![screen shot 2018-10-10 at 11 04 22 am](https://user-images.githubusercontent.com/930478/46746096-53476900-cc7c-11e8-9087-8a4b95a81f1d.png)

**Comment by Calinou** [comment]
The current window title is something of the form:

```twig
Godot Engine - {{project name}} - {{file name of currently edited scene}}
```

Maybe we can make use of the currently-edited scene to display the full path?

```twig
Godot Engine - {{project name}} - {{full path to currently edited scene}}
```

**Comment by eduardohmrodrigues** [comment]
Is this update still needed? I was looking to implement it but I saw that people didn't liked the following update proposal: https://github.com/godotengine/godot/pull/32942

**Comment by Calinou** [comment]
@eduardohmrodrigues Since the pull request was closed due to lack of support (see [this comment](https://github.com/godotengine/godot/pull/32942#issuecomment-546924856)), I'll close this issue as well.
