### ISSUE TITLE
Remove GDscript access to ArrayMesh.surface_update_region

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#22912]
I think this may have been mistakenly exposed to GDscript in the push to expose more functions. 
`surface_update_region` takes an array as an argument and directly sends it to OpenGL using `glBufferSubData`. The issue with doing this is that the function expects that the array is properly formatted to be sent to the GPU already, plus Godot hasn't exposed any means for the user to determine how the array is structured internally. The result is that the user is almost guaranteed to corrupt the mesh if they call it. 

A better option is to only allow the user to update the mesh arrays, and then let the engine handle the calls to OpenGL itself. This can be accomplished by simply unexposing `surface_update_region`.

**Comment by akien-mga** [comment]
Assigning @reduz who added it in 6277e6d4.

**Comment by clayjohn** [comment]
This needs to be exposed as it can be used effectively from C# and GDNative. While it can be used from GDScript it is ineffective. 

More discussion and my attempts to document it properly here https://github.com/godotengine/godot-docs/issues/3787
