### ISSUE TITLE
No "Edit Filters" button in "Blend3" node in AnimationTree

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#22923]
**Godot version:**
Master branch

**OS/device including version:**
Windows 7

**Issue description:**
There is no "Edit Filters" button in "Blend3" node in AnimationTree

![default](https://user-images.githubusercontent.com/24987226/46779562-f8307780-cd4a-11e8-8a3b-0d6de98e7509.png)

**Comment by rcorre** [comment]
Same for `Add3`.

**Comment by akien-mga** [comment]
As discussed in #27571, it seems to be by design and it's not clear what the use case for filter on Blend3 would be, so closing.

**Comment by Dankakes** [comment]
Chances we can revisit?
