### ISSUE TITLE
OAHashMap loses items

### ISSUE THREAD

**Issue by Windfisch** [godotengine/godot#22928]
**Godot version:** commit 4c1a5d9cfe2da761bfe17d52126deabc1f1c1bd3

**OS/device including version:** Linux

**Issue description:**

When inserting a some keys into an `OAHashMap` (with a dummy value, which is ignored) and then checking back whether it can look them up, then it fails to look up some of them.

**Steps to reproduce:**

Insert these keys in this order into a `OAHashMap<int, int>`: `0x22B61E64, 0x67BF4A73, 0x4A0496D4, 0x1B5239D1, 0xC0D84817, 0x720515E1, 0xAE20C2C0, 0xA92FC88D, 0x284D5CB9, 0x5F3510C0, 0xF496DF10, 0xDCD24583, 0xE6A13083, 0xF722547C, 0x38BEB0F5, 0xAA611912, 0xD7EE2434, 0x545D4F50, 0x1E6B57EE, 0x56DCAC75`.

Then call `map.lookup(0xAA611912, dummy)`.

It will return false. It should return true.

**Comment by Windfisch** [comment]
Easier steps to reproduce:
1. check out https://github.com/Windfisch/godot/commit/15d3c96afdbb73505f128c5d3a6393ed24140c67

2. run `./bin/godot.x11.tools.64 --test oa_hash_map`

**Comment by bojidar-bg** [comment]
CC @karroffel.
