### ISSUE TITLE
why i cannot use like this : array[0] = {} 

### ISSUE THREAD

**Issue by zhangshiqian1214** [godotengine/godot#22926]
why i cannot use like this : array[0] = {} , because i want store objects in a list, but in gdscript is error

**Comment by groud** [comment]
This code works :
```
var my_array = []

func _ready():
	my_array.resize(1)
	my_array[0] = {}
```
I guess you were trying to access an inexistent index in the array (that's why you have to use resize() )

As this is not an engine issue, please use the other [community channels](https://godotengine.org/community) if you have more questions.
