### ISSUE TITLE
Probably invalid code in engine.js

### ISSUE THREAD

**Issue by janisozaur** [godotengine/godot#22937]
Please see the very first lines in `engine.js`, should I submit a PR to remove them?

https://github.com/godotengine/godot/blob/4c1a5d9cfe2da761bfe17d52126deabc1f1c1bd3/platform/javascript/engine.js#L1-L5

**Comment by Calinou** [comment]
That file appears to be included after https://github.com/godotengine/godot/blob/4c1a5d9cfe2da761bfe17d52126deabc1f1c1bd3/platform/javascript/pre.js, so while the beginning of `engine.js` may look invalid, the combination actually is valid.

**Comment by janisozaur** [comment]
Indeed, https://github.com/godotengine/godot/blob/cef310e0ea0f8e7f3621e9ba29a567f09fb51beb/platform/javascript/SCsub#L23-L25 seems to use this as a wrapper. It's probably fine then, but I would expect at least a comment suggesting such scenario and pre-empting confusion.
