### ISSUE TITLE
Godot do not initialize Android Modules singletons (Latest 3.1)

### ISSUE THREAD

**Issue by TheTrope** [godotengine/godot#22932]
Hello,

The android modules does not work when I use the latest build/templates (latest master 3.1), the modules load well (_so I guess correctly configured_), but singletons are not created

Even GodotPayment is not available, **I added a print to dislay all the current singletons in engine.cpp:** 

When using

>  Engine.get_singleton('GodotPayments')

 I get 

> Failed to retrieve non-existent singleton 'GodotPayments'

adb logcat :

> 
>     10-10 21:28:40.975 20132 20179 I godot   : Loading module: org/godotengine/godot/GodotPaymentV3
>     10-10 21:28:40.976 20132 20179 I godot   : Loading module: org/godotengine/godot/FireBase
>     10-10 21:28:40.976 20132 20179 I godot   : Loading module: org/godotengine/godot/SQLBridge
>     10-10 21:28:41.151 20132 20179 I godot   : OpenGL ES 3.0 Renderer: Mali-T830
>     10-10 21:28:43.462 20132 20179 E godot   : **ERROR**: Failed to retrieve non-existent singleton 'GodotPayments' in:JavaScript;ClassDB;Marshalls;JSON;PhysicsServer;Physics2DServer;ProjectSettings;InputMap;VisualServer;Input;AudioServer;Geometry;ResourceLoader;ResourceSaver;OS;Engine;ARVRServer;IP;TranslationServer;Performance;JavaClassWrapper;

So the only singletons available are : 

> JavaScript;ClassDB;Marshalls;JSON;PhysicsServer;Physics2DServer;ProjectSettings;InputMap;VisualServer;Input;AudioServer;Geometry;ResourceLoader;ResourceSaver;OS;Engine;ARVRServer;IP;TranslationServer;Performance;JavaClassWrapper

GodotPayments is not existing there
Do you have any idea? Thanks !

**Godot version:**
Latest master (3.1) Custom build/templates
Android live debug work, except for android modules. I correctly set the android modules path because they are loading

**OS/device including version:**
Windows 10 editor: Live debug w/ Huawei p20 lite android 8

**Comment by samuelpedrajas** [comment]
I think this is related to this one: https://github.com/godotengine/godot/issues/22859

**Comment by Chaosus** [comment]
Closed as duplicate
