### ISSUE TITLE
Support IDE

### ISSUE THREAD

**Issue by toxub23** [godotengine/godot#22935]
You could add instructions to properly configure MonoDevelop to work with Godot on the site
https://godot.readthedocs.io/en/3.0/development/cpp/configuring_an_ide.html

**Comment by StraToN** [comment]
@toxub23 The page you refer to is meant for engine development, not scripting in C#.
The page you are looking for is https://godot.readthedocs.io/en/3.0/getting_started/editor/external_editor.html

**Comment by KellyThomas** [comment]
When using the mono enabled version of godot you can select MonoDevelop as the c# editor via:  

Editor Settings > Mono > Editor > External Editor

**Comment by akien-mga** [comment]
This is not an engine issue, documentation issues should be opened on https://github.com/godotengine/godot-docs.
