### ISSUE TITLE
One way collisions are unstable -> Character falls through

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#2294]
One way collisions worked once good for me. After this commit I had problems: https://github.com/okamstudio/godot/commit/32b1b472af379b3ea3b155a38158f08aed1e92e1

Now my character falls often through the collider. I have a moving platform that can float. Once It starts moving the character falls immediately through.

I send you an email a while back with my project which had the problem. Would be great if this could be fixed again :-)

**Comment by reduz** [comment]
yeah, i think i screwed up, will give it a check

**Comment by akien-mga** [comment]
Has this been fixed in the end? Would it also be the same cause for #2345?

**Comment by ndee85** [comment]
No.. as far as I know this hasn't been fixed yet. Would be great if this works for the next release ^^

**Comment by akien-mga** [comment]
Let's close this one as a duplicate of #2345, they seem quite related.
