### ISSUE TITLE
Compiling for android throws error with 3.0 branch

### ISSUE THREAD

**Issue by theblockhouse** [godotengine/godot#22946]
Same issue as #12347 but that is closed. Building for windows works only android has this issue

**Godot version:**
3.0 branch Latest commit f16f9b2  on Aug 23

**OS/device including version:**
Windows 10

**Issue description:**
Android build fails with same error as #12347

ERROR:
b"In file included from thirdparty\\bullet\\BulletCollision\\BroadphaseCollision\\btAxisSweep3.cpp:20:\r\nIn file included from thirdparty\\bullet\\BulletCollision\\BroadphaseCollision/btAxisSweep3.h:23:\r\nIn file included from thirdparty\\bullet\\BulletCollision\\BroadphaseCollision/btOverlappingPairCache.h:24:\r\nthirdparty\\bullet\\LinearMath/btAlignedObjectArray.h:39:10: fatal error: 'new' file not found\r\n#include <new> //for placement new\r\n         ^~~~~\r\n1 error generated.\r\n"

scons: *** [thirdparty\bullet\BulletCollision\BroadphaseCollision\btAxisSweep3.android.debug.armv7.neon.o] Error 1
scons: building terminated because of errors.

**Steps to reproduce:**
build with scons p=android

**Comment by s0ra** [comment]
I got the same problem. Downgrading NDK is a workaround. The master branch seems not to have this problem.

**Comment by akien-mga** [comment]
Fixed by #23033.
