### ISSUE TITLE
Cannot filter remote scene tree

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#22949]
Godot 3.0.6

I tried to use the filter textbox to find a node in the remote scene tree (while the game runs), but it appears to not do anything. It would be nice to filter that tree as well since it's very likely to be crowded with nodes.

**Comment by menip** [comment]
Could you add screenshot showcasing issue?

**Comment by Zylann** [comment]
![image](https://user-images.githubusercontent.com/1311555/58581318-2f568900-8247-11e9-8fa9-1dcb0a1155b6.png)
