### ISSUE TITLE
Problem with HTML5 after exporting wasm from Godot 3.1 Alpha 

### ISSUE THREAD

**Issue by deleteaccount1234567890** [godotengine/godot#22951]
Only here - I can't find I have already searched it.

Godot Engine 3.1 Alpha Custom 4c1...

Linux Ubuntu 18.04 , Intel Core 7
AMD Radeon RX 480 8 GB VideoRam

It happens after exporting HTML5 seems corrupt or missing - I already tried with webassembly_release.zip

I already tried like same throw warning and missing/corrupted HTML5 from webassembly_release .zip since I have scons building...

I already read docs of Godot Build Web ( webassembly ) But it seems like missing/corrupted. I have already tried. No success.

http://docs.godotengine.org/en/3.0/development/compiling/compiling_for_web.html
![image](https://user-images.githubusercontent.com/3496136/46837152-7aa15180-cdb4-11e8-90de-2e9ed58b7fb3.png)

Do you reproduce that?

**Comment by Faless** [comment]
It works here on Ubuntu 18.04 .
You need to compile the export templates.
You need to set the custom template field to point to the right path.
**You haven't set the debug custom template**, and you are probably **trying to export the debug** version:
![debug](https://user-images.githubusercontent.com/1687918/46868107-8bd77600-ce27-11e8-9fcc-a189a3bfeff2.png)

**Comment by deleteaccount1234567890** [comment]
Thanks for explanation - I will try

**Comment by deleteaccount1234567890** [comment]
Hello I have problem with emscripten :( I don't like you miss understand - like it is Ok but for me I have biiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiig problem with HTML5 I have tried debug mode and release not working

I have already tried recompilation with emscripten but it throws error

**Comment by deleteaccount1234567890** [comment]
Please quit to ignore me! I wait longer for my problem. Why @Faless is right to force me but I have tried. I have not success / goal. :( I am very sad because I can't get chance. Please don't force me for nothing answers! I wait for nothings..... thanks! I am respectfully.

**Comment by akien-mga** [comment]
I'm sorry but this is not a support website, and @Faless has no contractual agreement with you to stay up all night to help you set up compilation environments.

Your requests should be made on other community platforms where people can help you (if they want, everyone works on their free time and as mentioned nobody is paid to support you). This GitHub issue tracker is not for user support, it's for engine bugs. @Faless could confirm that there is no engine bug, only misconfiguration on your end, so he closed the issue as invalid.

I'll advise that you account name "DELETE ACCOUNT!" doesn't really set people in the right mood to take you seriously - and your ALLCAPS shouting at people who don't answer you in the minute is also unwelcome. Please stay polite and constructive, and use this issue tracker only for actual engine bug reports. For support requests, see other channels on https://godotengine.org/community

**Comment by deleteaccount1234567890** [comment]
@akien-mga 
Oh really @Faless has not contact to me. Thanks. I will respect that.

No no I missconfigure that. I already try - It is really fresh from Godot source with emsdk 1.38.12

Because I tried to remove my Github account but I can't because I already tried like Github -> account -> Settings -> account -> Delete account. I know that. But it can't remove because red label in button seems like disabled. That is why. I am mad to Github. I don't believe because Microsoft holds my old account. That is reason. I have signed up your godot community :) My real user name is SourceSkyBoxer - Don't worry I will respect.
P.S.Please promise me! Do not share my details to Facebook and Discord sorry I am serious. And I don't like that and I am scared because Facebook is really dangerous. Thanks I will close here
