### ISSUE TITLE
OpenGL context loss is not handled on Android

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#22955]
**Godot version:**
3.0, 3.1

**OS/device including version:**
Many different Android devices, both Mali and Adreno, different generations, different Android versions (from 5.1 to 8.1).

**Issue description:**
When you switch an active app using OpenGL, its OpenGL context may (partially?) be destroyed by the system in low-resource situations. As a result, some textures or other resources are invalidated and are no longer available. We have seen it on our testing devices and have dozens of reports from our players that the game starts looking like this:
![eglcontextloss](https://user-images.githubusercontent.com/2417849/46854835-4b2e2b80-ce2c-11e8-9209-99eace035508.jpg)

Godot uses [setPreserveEGLContextOnPause(true)](https://developer.android.com/reference/android/opengl/GLSurfaceView#setPreserveEGLContextOnPause(boolean)) call, but it is not guaranteed to preserve the context - it is just a hint given to the system that we would like to preserve the context, if possible. However, the engine still needs to reload resources in the event of context loss, and Godot does not do this.

This video briefly explains the topic and how the context loss could be detected: https://www.youtube.com/watch?v=NHVtLC5QOpo

**Steps to reproduce:**
There is no 100% way to reproduce this, but this is the most likely way to see the issue:

1. Create a project with a bunch of large images and make a game that loads/displays all of them. The more (graphical) memory the game consumes, the likely this is to reproduce, as it increases the chance that the system will destroy some of the game's resources while it's in background.

2. Open the game on an Android device.

3. Switch to a different app or a number of apps that consume a lot of memory.

4. Switch back to the game.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by akien-mga** [comment]
Any update?

**Comment by RandomShaper** [comment]
Today or tomorrow I'll fix it.
