### ISSUE TITLE
get_viewport_rect() returns -nan if window minimized

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#22958]
**Godot version:**
3.1 commit  a16dc807e

**OS/device including version:**
Windows 10

**Issue description:**
`get_viewport_rect()` function returns `-nan` values when window minimized

**Steps to reproduce:**
`print(get_viewport_rect())`
output:
`(0, 0, 1280, -nan(ind))`

**Comment by KellyThomas** [comment]
See also: https://github.com/godotengine/godot/issues/20877

**Comment by kosz78** [comment]
@aaronfranke patch dont work, the behavior is the same

**Comment by marcelofg55** [comment]
This should be fixed by #24078, if you can please test it again with latest master. Thanks!

**Comment by akien-mga** [comment]
Closing as fixed by #24078 so that we don't forget, but please comment to confirm that it does work as expected. If not, we can reopen the issue.
