### ISSUE TITLE
Default values are saved into instances

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#22954]
**Godot version:**
3.1 a16dc807e535969f041667442b328232bba0cf3e

**OS/device including version:**
macOS 10.12.1

**Issue description:**
Default value of a script property is saved into the node that has the script attached. This leads to the problem that if you change the default value in the script, it is left as is in the existing nodes, even if you did not modify the value for the instance.

The behaviour was different in 3.0 - default values were not saved in the .tscn file, so if you changed them in the script, they got updated where needed.

**Steps to reproduce:**
1. Create a script that exports a property, for example
```
extends Control
export(int) var some_property = 0
```
2. Create a node and attach the script to it, save scene with the node.
3. Close the scene.
4. Modify value in the script from 0 to 42.
5. See that the value in the node was not updated.

**Comment by muiroc** [comment]
Reminds me of something in #18660, where resaving the scene would undefine the default properties in the child instances (see last 2 repro steps)

**Comment by reduz** [comment]
This sounds like a bug to me, can anyone create a simple to use testcase and do bisecting?

**Comment by endragor** [comment]
What's most annoying is that due to this issue `null` values are also saved into scene, so if you have code in `_init` that sets the values, they will turn into `null` afterwards.

**Comment by endragor** [comment]
I tried a commit from Aug 27 2017 (27c142a57b01b7bf8b097b89fc71b2462fa3c903) and some other commits in between, but the issue is still there. So either there was a brief period where it worked as expected (and I think there was...) or it actually never worked properly.

**Comment by reduz** [comment]
closed via 6e5872b70

**Comment by Zylann** [comment]
I just realized something, to raise awareness:
While I indeed like this change, it means changing default values will break compatibility.

**Comment by endragor** [comment]
Didn't it already break compatibility before? Your script could expect that calling `new` on some class sets certain defaults, so if they change, the expectation is broken.

**Comment by Zylann** [comment]
When you create objects dynamically yes, changing default value breaks that anyways. But since this issue is about scenes, I was mentionning that it breaks it here too now, where code is not always involved :p

**Comment by endragor** [comment]
True, but it was always a breaking change, so I don't think much has changed with regards to how default value changes should be approached. But yes, now they will break even more things.
