### ISSUE TITLE
Editor: GridContainer resizes children controls, does not allow clicking on them to adjust size

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22961]
Godot version:
#4c1a5d9
Mac OS X, High Sierra

**Issue description:**
Create a grid container with 2 columns and two buttons. The child buttons are not accessible from the GUI for selection, and manipulation. Only from inspector and also it is manual.

Also, if you manually adjust the size of the child buttons from inspector, and then resize the grid container, all the children are resized back.

![screen shot 2018-10-12 at 9 12 43 am](https://user-images.githubusercontent.com/930478/46871370-36876e80-cdff-11e8-8dcc-4d2e45696763.png)

**Comment by Faless** [comment]
GridContainer is a layout node. You cannot resize its child nodes. You can only use the size flags.

**Comment by aaronfranke** [comment]
This is a symptom of a larger problem, which is that Control nodes are not WYSIWYG and they allow you to make invalid changes. I can't seem to find it, but I think there's another open issue about this.

**Comment by groud** [comment]
Yes, this is expected behavior. Children of containers are not meant to be moved. See #22877 for the valid issue.
