### ISSUE TITLE
shader on ninepatchrect broken

### ISSUE THREAD

**Issue by scottkunkel** [godotengine/godot#22969]
**Godot version:**

3.0.6

**OS/device including version:**

Win 10 Intel HD 630

**Issue description:**

Shaders on NinepatchRect distort and break the ninepatch

**Steps to reproduce:**
Create ninepatchRect bigger than initial texture
apply shader:
`shader_type canvas_item;

void fragment() {
    vec4 texColor = texture(TEXTURE, UV);
    vec4 finalColor = vec4(texColor.rgb, texColor.a); 
    COLOR = finalColor;
}`

corners of ninepatchrect are distorted

**Minimal reproduction project:**

**Comment by QbieShay** [comment]
@scottkunkel  can you attach images of how it looks like? Also, what do you mean by initial texture?

**Comment by scottkunkel** [comment]
[New Game Project.zip](https://github.com/godotengine/godot/files/2476014/New.Game.Project.zip)

I attached a sample project with the normal 9patch, 9patch with shader and a workaround (albeit with wrong dimensions)

**Comment by QbieShay** [comment]
@scottkunkel What would you expect when reading from a ninepatch? Because what is happening is that UVs are mapped in the whole square (you are basically skipping the uv remapping when you make your own fragment shader)

**Comment by scottkunkel** [comment]
Sorry, if I understand this right, is 9patch a shader that I am overwriting? I am new to Godot and shaders and am trying to understand what's happening.
Let me ask you another way: What would a working shader look like?

**Comment by QbieShay** [comment]
So, what happens in Godot when you use a ninepatch is that the UV gets remapped to properly stretch/tile. The problem with using a fragment shader is that, on the engine side, what is exposed as 'UV' didn't go through this transformation, so when you access it you are accessing as if the ninepatch was a quad. Basically, ninepatch does some UV transformation that is not accessible in Godot shading language and when you use the he UV you are using the untransformed ones.
