### ISSUE TITLE
GLES2/WebGL1 ShaderMaterial link error

### ISSUE THREAD

**Issue by muiroc** [godotengine/godot#22962]
**Godot version:**
4c1a5d9 debug javascript build with a [modified index.js](https://gist.github.com/muiroc/818798d9f314a130e164c7cd7d8aa39e) minus the replace precision hack

**OS/device including version:**
Windows 10 Chrome with Angle

**Issue description:**
Shader Resources where uniforms are declared without an explicitly set precision, ultimately causes a link error

similar to #22631

ERROR: SceneShaderGLES2: Program linking failed:
Uniforms with the same name but different type/precision: m_uniformname

Sorry I didn't notice this before since it was hidden by the naive .replace("precision mediump float", "precision highp float")

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by muiroc** [comment]
@akien-mga 
with 95bd60f71c5ab0fcd2aed69a1aaa88b3235e93e4 yes

Also happens with SpatialMaterial

```
**ERROR**: SceneShaderGLES2: Program linking failed: index.js:7:49260
Uniform `m_roughness` is not linkable between attached shaders. index.js:7:49260
```
