### ISSUE TITLE
ColorPickerButton vertical drag does not change if default #000000 or #FFFFFF 

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22964]
**Godot version:**
#43c2868
Mac OS X, High Sierra

**Issue**
When the default value is #000000 or #FFFFFF, the ColorPickerButton vertical drag does not change the color. Only once any other color is changed, then it works.

![colorpickerbuttonbug 2018-10-12 12_06_45](https://user-images.githubusercontent.com/930478/46881054-642ce180-ce18-11e8-9f75-18c4e0b2424b.gif)

**Comment by Naryosha** [comment]
Hue is irrelevant in grayscale. White with hue shifted is still white.
