### ISSUE TITLE
Editor: controls, required two clicks to be in move focus

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22960]
**Godot version:**
#4c1a5d9
Mac OS X, High Sierra

**Issue description:**
Create two or more controls. Clicking between them to move requires two clicks. One to select and then another click to move. 

![extraclickcontrolbug 2018-10-12 08_53_20](https://user-images.githubusercontent.com/930478/46870696-5453d400-cdfd-11e8-9326-7d3992b63d2a.gif)

**Comment by akien-mga** [comment]
Well, that's the expected behaviour as far as I can tell. You need to select a node before you move it, otherwise clicking nodes would move them by a few pixels all the time and/or might move unexpected nodes.

**Comment by groud** [comment]
> Well, that's the expected behaviour as far as I can tell.

I don't think so, this used to work as described.
