### ISSUE TITLE
Editor crashing on Linux, and Windows editor built with Linux will crash silently.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22979]
## Problem Summary

**Ubuntu 18.04.1 LTS 64-bit and Win10 64-bit v3.1 alpha 43c2868**

**(Also seen in:  fe0db6c4797b8094c64e4ad017e29be866288628)**

The editor crashes when typing a period after a var that contains a class.  It crashes before the auto-completion appears.

The problem goes away when I remove a line from above the line that causes the crash.  I marked it with a comment in the included code below.  In this line I am using  `is` to compare with a preloaded script.

On Unbuntu it produces this stack trace:  [x11.log](https://github.com/godotengine/godot/files/2475516/x11.log)

On Windows, where I first encountered it, it will silently crash with no errors or warnings in the console.

### A period here will crash it.
![godot_master_2018-10-13_12-47-22](https://user-images.githubusercontent.com/13004169/46904001-33b37900-cee6-11e8-80c3-296ed97cc917.png)

### Take this line out and no problems.
![godot_master_2018-10-13_12-47-12](https://user-images.githubusercontent.com/13004169/46904000-301ff200-cee6-11e8-9567-1fce9610a1ce.png)

### Video
You can watch the windows version of this in action at this link -> https://streamable.com/ymr06

## Cross Compile Issue

This one might be elusive, unless it is some problem on X11 builds in general.

It does happen using a 64-bit windows editor, when the editor is built on Linux.  This doesn't happen when I do the same build from Windows using the VS 64-bit compiler.

## How to Reproduce

1. Using Ubuntu 18.04.1 LTS pull the latest the source.
2. Do an editor build with tools=yes bits=64.  (It can also be a Windows build.)
4. Go into the sample project provided below.
5. Enter the script named `error_script.gd`
6. Find the last line with `players.append(anim)`
7. Type a period at the end of `anim.` and if you have the problem it should crash a moment after that.

[3.1 Strange Crash.zip](https://github.com/godotengine/godot/files/2475315/3.1.Strange.Crash.zip)

Also including the scons log of a fresh build, there seems to be a lot of warnings lately, and maybe my builds are setup wrong.

[scons.log](https://github.com/godotengine/godot/files/2475379/scons.log)

**Comment by QbieShay** [comment]
@avencherus if you can, compile the windows version from linux with debugging symbols.

**Comment by avencherus** [comment]
@QbieShay A newbie question.  X)  How is that done?  Is it a with a scons parameter?

**Comment by QbieShay** [comment]
@avencherus should be something like target=debug. Which should be there by default o.0. Maybe you can run the program through gdb. @Calinou might help on this

**Comment by avencherus** [comment]
@QbieShay Thanks again.  I went a reread the build docs, and the flags make more sense to me now that I've learned a few things.  I got the X11 build done and edited the post to include a text file with the stack report.  I'll see what I get on Windows very shortly.

<details>

handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f2aef05af20] (??:0)
[2] CowData<Node*>::_get_size() const (??:0)
[3] CowData<Node*>::size() const (??:0)
[4] Vector<Node*>::size() const (??:0)
[5] Node::_get_node(NodePath const&) const (??:0)
[6] Node::get_node(NodePath const&) const (??:0)
[7] MethodBind1RC<Node*, NodePath const&>::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[8] /home/username/Godot/Source/bin/godot.x11.tools.64(+0xff677e) [0x55db85fb677e] (??:0)
[9] /home/username/Godot/Source/bin/godot.x11.tools.64(+0xff8bc9) [0x55db85fb8bc9] (??:0)
[10] /home/username/Godot/Source/bin/godot.x11.tools.64(+0xff5390) [0x55db85fb5390] (??:0)
[11] GDScriptLanguage::complete_code(String const&, String const&, Object*, List<String, DefaultAllocator>*, bool&, String&) (??:0)
[12] ScriptTextEditor::_code_complete_script(String const&, List<String, DefaultAllocator>*, bool&) (??:0)
[13] ScriptTextEditor::_code_complete_scripts(void*, String const&, List<String, DefaultAllocator>*, bool&) (??:0)
[14] CodeTextEditor::_complete_request() (??:0)
[15] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[16] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[17] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[18] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[19] TextEdit::query_code_comple() (??:0)
[20] CodeTextEditor::_code_complete_timer_timeout() (??:0)
[21] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[22] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[23] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[24] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[25] Timer::_notification(int) (??:0)
[26] Timer::_notificationv(int, bool) (??:0)
[27] Object::notification(int, bool) (??:0)
[28] SceneTree::_notify_group_pause(StringName const&, int) (??:0)
[29] SceneTree::idle(float) (??:0)
[30] Main::iteration() (??:0)
[31] OS_X11::run() (??:0)
[32] /home/username/Godot/Source/bin/godot.x11.tools.64(main+0xdc) [0x55db85ed9496] (??:0)
[33] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f2aef03db97] (??:0)
[34] /home/username/Godot/Source/bin/godot.x11.tools.64(_start+0x2a) [0x55db85ed92da] (??:0)
-- END OF BACKTRACE --
</details>

**Comment by QbieShay** [comment]
cc @vnen @hpvb

**Comment by avencherus** [comment]
The windows version that I rebuilt with target=debug is still silent in the console when this happens.

**Comment by capnm** [comment]
Linux fe0db6c4797b8094c64e4ad017e29be866288628

```
extends Node
# Some valid gdscript path
const p = "res://main.gd"
	
func f():
	var rsc = preload(p)
	var a
	if(a is rsc):
		var n1 = a.get_children()
		var n2 = a.get_node("xxx")
		
		var crash
		crash = n1
		crash = n2
		# Type a period (.) after nx
```

crashes in

```
Thread 1 "godot3" received signal SIGSEGV, Segmentation fault.
Vector<Node*>::size (this=0x55555d9e71b8) at ./core/vector.h:87
87		_FORCE_INLINE_ int size() const { return _cowdata->size(); }
(gdb) bt
#0  Vector<Node*>::size (this=0x55555d9e71b8) at ./core/vector.h:87
#1  Node::get_child_count (this=this@entry=0x55555d9e7090) at scene/main/node.cpp:1226
#2  0x00005555569dfd59 in Node::_get_children (this=0x55555d9e7090) at scene/main/node.cpp:2539
#3  0x0000555555977a77 in MethodBind0RC<Array>::call (this=<optimized out>, p_object=<optimized out>, p_args=<optimized out>, p_arg_count=<optimized out>, r_error=...) at ./core/method_bind.gen.inc:558
#4  0x000055555585e3b5 in _guess_expression_type (p_context=..., p_expression=p_expression@entry=0x55555f3efce0, r_type=...) at modules/gdscript/gdscript_editor.cpp:868
#5  0x0000555555862973 in _guess_identifier_type (p_context=..., p_identifier=..., r_type=...) at modules/gdscript/gdscript_editor.cpp:1197
#6  0x000055555585ca66 in _guess_expression_type (p_context=..., p_expression=0x55555f3f37f0, r_type=...) at modules/gdscript/gdscript_editor.cpp:658
#7  0x0000555555869834 in GDScriptLanguage::complete_code (this=this@entry=0x5555594fe4c0, p_code=..., p_base_path=..., p_owner=p_owner@entry=0x55555f3a7d50, r_options=r_options@entry=0x7fffffffcbd0, 
    r_forced=@0x7fffffffcbcf: false, r_call_hint=...) at modules/gdscript/gdscript_editor.cpp:2514
#8  0x000055555664dacf in ScriptTextEditor::_code_complete_script (this=0x55555e6aba40, p_code=..., r_options=0x7fffffffcbd0, r_force=@0x7fffffffcbcf: false) at editor/plugins/script_text_editor.cpp:602
#9  0x000055555664db97 in ScriptTextEditor::_code_complete_scripts (p_ud=<optimized out>, p_code=..., r_options=<optimized out>, r_force=<optimized out>) at editor/plugins/script_text_editor.cpp:591
#10 0x00005555568401cb in CodeTextEditor::_complete_request (this=0x55555e6ac000) at editor/code_editor.cpp:722
#11 0x0000555555804dba in MethodBind0::call (this=<optimized out>, p_object=<optimized out>, p_args=<optimized out>, p_arg_count=<optimized out>, r_error=...) at ./core/method_bind.gen.inc:54
#12 0x000055555799429f in Object::call (this=0x55555e6ac000, p_method=..., p_args=0x7fffffffce20, p_argcount=0, r_error=...) at core/object.cpp:968
#13 0x000055555799e00a in Object::emit_signal (this=0x55555e6d3920, p_name=..., p_args=p_args@entry=0x7fffffffce20, p_argcount=0) at core/object.cpp:1254
#14 0x000055555799ee78 in Object::emit_signal (this=this@entry=0x55555e6d3920, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1310
#15 0x0000555556c1973b in TextEdit::query_code_comple (this=0x55555e6d3920) at scene/gui/text_edit.cpp:5829
#16 0x000055555683425e in CodeTextEditor::_code_complete_timer_timeout (this=0x55555e6ac000) at editor/code_editor.cpp:712
#17 0x0000555555804dba in MethodBind0::call (this=<optimized out>, p_object=<optimized out>, p_args=<optimized out>, p_arg_count=<optimized out>, r_error=...) at ./core/method_bind.gen.inc:54
#18 0x000055555799429f in Object::call (this=0x55555e6ac000, p_method=..., p_args=0x7fffffffd160, p_argcount=0, r_error=...) at core/object.cpp:968
#19 0x000055555799e00a in Object::emit_signal (this=0x55555e6d9fa0, p_name=..., p_args=p_args@entry=0x7fffffffd160, p_argcount=0) at core/object.cpp:1254
#20 0x000055555799ee78 in Object::emit_signal (this=this@entry=0x55555e6d9fa0, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1310
#21 0x0000555556a39813 in Timer::_notification (this=this@entry=0x55555e6d9fa0, p_what=p_what@entry=25) at scene/main/timer.cpp:61
#22 0x0000555556a3c1a2 in Timer::_notificationv (this=0x55555e6d9fa0, p_notification=25, p_reversed=<optimized out>) at scene/main/timer.h:38
#23 0x0000555557990e0a in Object::notification (this=this@entry=0x55555e6d9fa0, p_notification=p_notification@entry=25, p_reversed=p_reversed@entry=false) at core/object.cpp:978
#24 0x0000555556a29b11 in SceneTree::_notify_group_pause (this=this@entry=0x5555594e6e30, p_group=..., p_notification=p_notification@entry=25) at scene/main/scene_tree.cpp:958
#25 0x0000555556a2a977 in SceneTree::idle (this=0x5555594e6e30, p_time=0.00833333377) at scene/main/scene_tree.cpp:509
#26 0x000055555578cb46 in Main::iteration () at main/main.cpp:1846
#27 0x00005555557786ba in OS_X11::run (this=0x7fffffffd500) at platform/x11/os_x11.cpp:2817
#28 0x000055555576a6d1 in main (argc=2, argv=0x7fffffffdc48) at platform/x11/godot_x11.cpp:55
```

**Comment by avencherus** [comment]
@vnen Is this related to any existing issues?

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch? I haven't seen this issue yet myself.

**Comment by avencherus** [comment]
The latest builds I've done using Unbuntu are at 0e25c32.  It's still happening.  A silent crash on the Windows version of the editor.  

I'll check it again the next time I rebuild.

**Comment by avencherus** [comment]
@akien-mga Also crashing in 1b5b274.
