### ISSUE TITLE
Odd triangle holes will appear in CSG subtraction

### ISSUE THREAD

**Issue by fire** [godotengine/godot#22988]
**Similiar Issues:**

https://github.com/godotengine/godot/issues/18476

**Godot version:**
43c2868

**OS/device including version:**
Nvidia GTX 1080 on Windows 10

**Issue description:**

![godot windows opt tools 64_2018-10-13_08-51-52](https://user-images.githubusercontent.com/32321/46907294-49647680-cec5-11e8-86c3-8d26acf4348e.png)

**Steps to reproduce:**

Create CSG nodes consisting of a plane of sufficient size and then use a cylinder to subtract. Odd triangle holes will appear.

**Minimal reproduction project:**

[epoch_packet_hidden_node.zip](https://github.com/godotengine/godot/files/2475606/epoch_packet_hidden_node.zip)

**Comment by Toshiwoz** [comment]
I have a very similar issue but with cubes.
![csg_portal_issue](https://user-images.githubusercontent.com/21297356/47118648-8dd97480-d22d-11e8-84e3-75dba09c3873.gif)

As you can see from the gif, I used 3 cubes:
- external walls
  - internal walls (subtracts)
  - entrance (subtracts)

Depending on the position of the door it shows or not the artifacts.

**Comment by dbenoy** [comment]
I get a lot of artifacts when I try to subtract one aggregate union from another in this project:

![image](https://user-images.githubusercontent.com/2285331/49482127-da880780-f7fb-11e8-804a-dee9db46b4af.png)

![image](https://user-images.githubusercontent.com/2285331/49482137-e673c980-f7fb-11e8-970a-206a9282d960.png)

[sandbox.zip](https://github.com/godotengine/godot/files/2646671/sandbox.zip)

**Comment by Francesco149** [comment]
same here, running 3.1-stable on linux x86_64 on a r9 270x with the amdgpu drivers

![](https://media.giphy.com/media/ZByjcDG8ZOK6fu41Kf/giphy.gif)

**Comment by ShyRed** [comment]
Here are the results of a debugging session using the sandbox project 😅 

In the sandbox project I see 3 holes and get exactly 3 failed polygon triangulations.

One example:

```
0.000000000,0.000000000
0.549831629,0.725973845
0.588947773,0.687405705
0.549831629,0.725973845
0.000000000,0.000000000
0.549831629,0.725973845
0.000000000,0.000000000
0.633987665,0.642996907
1.40420127,1.42415524
1.07861471,1.42415524
0.549831629,0.725973845
0.549831629,0.725973845
0.000000000,0.000000000
0.633987665,0.642996907
0.549831629,0.725973845
```

which looks like 
![image](https://user-images.githubusercontent.com/1138805/55505336-2c7a5600-5653-11e9-90cc-38f3ca68994d.png)

When putting the values into some online [delaunay triangulation](https://travellermap.com/tmp/delaunay.htm) demo, I get a working triangulation.

Just use javascript console and put in the following:

```
demo.addAt(0.000000000*100,0.000000000*100);
demo.addAt(0.549831629*100,0.725973845*100);
demo.addAt(0.588947773*100,0.687405705*100);
demo.addAt(0.549831629*100,0.725973845*100);
demo.addAt(0.000000000*100,0.000000000*100);
demo.addAt(0.549831629*100,0.725973845*100);
demo.addAt(0.000000000*100,0.000000000*100);
demo.addAt(0.633987665*100,0.642996907*100);
demo.addAt(1.40420127*100,1.42415524*100);
demo.addAt(1.07861471*100,1.42415524*100);
demo.addAt(0.549831629*100,0.725973845*100);
demo.addAt(0.549831629*100,0.725973845*100);
demo.addAt(0.000000000*100,0.000000000*100);
demo.addAt(0.633987665*100,0.642996907*100);
demo.addAt(0.549831629*100,0.725973845*100);
```

which should result in the following:

![image](https://user-images.githubusercontent.com/1138805/55506451-bd523100-5655-11e9-8891-91bf815d4daf.png)


So my current assumption is that either our triangulation is faulty *or* not tolerant enough since other implementation seem to be able to triangulate the polygon just fine?

**Comment by ShyRed** [comment]
After some more debugging and tinkering with the source code: The failed polygons do not seem to be the ones belonging to the holes / missing triangles :( I added delaunay triangulation to CSG in case polygon triangulation fails and the resulting triangles seem to belong to the shape(s) that are being subtracted with:

![image](https://user-images.githubusercontent.com/1138805/55625153-3c577e80-57a8-11e9-9f4a-5ba3153e93e2.png)

So I suspect it really is the CSG algorithm itself that is having trouble finding and closing all holes. Polygon triangulation seems fine and the invalid polygons should indeed not be triangulated (in this case).

**Comment by bojidar-bg** [comment]
Just a wild guess, but.. could it be that some vertices/edges/faces are assigned wrongly, thus creating the bad polygons and holes at once?

**Comment by nonoesimposible** [comment]
I'm seeing a similar issue, but with CSG *union*.

![Screenshot from 2019-05-04 23-11-06](https://user-images.githubusercontent.com/39754510/57189032-313a6000-6ec6-11e9-8ae4-1fd078a88ad1.png)

**Comment by duckinator** [comment]
Encountered this with 3.1.1.stable.official. Similar to what @nonoesimposible said, fudging values by ±0.1 seems to fix things.

![Screenshot_20190608_231113](https://user-images.githubusercontent.com/39698/59154609-d7d4cc00-8a43-11e9-8c27-804c35ee4e2c.png)

**Comment by ptrojahn** [comment]
I found a way to fix the holes in the example by @fire. Please retest your csg shapes. If you can please upload small example projects. Screenshots are pretty hard to debug.

**Comment by fire** [comment]
@ptrojahn There's a new approximate equal function that scales epsilon. It may be useful.

**Comment by fire** [comment]
https://github.com/godotengine/godot/blob/45be9c67ef4367b551e6c62b3f5fd246db41e825/core/math/math_funcs.h#L290

**Comment by Toshiwoz** [comment]
> 
> 
> I found a way to fix the holes in the example by @fire. Please retest your csg shapes. If you can please upload small example projects. Screenshots are pretty hard to debug.

The issue opener seems to have done that:
https://github.com/godotengine/godot/issues/22988#issue-369814700

If you want more I can provide mine.

**Comment by fire** [comment]
My original test case is solved. Please open a new issue if you have other test cases.
