### ISSUE TITLE
Improve changing values in the inspector

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#22982]
**Issue description:**
A possibility to change values quicker by continuous holding pressed arrow buttons would be useful. For example 10 steps/second.
![imgur-2018_10_13-13 31 38](https://user-images.githubusercontent.com/15695377/46904919-27cab580-ceec-11e8-8289-196484e8bd11.png)
It is possible to change value by pressing buttons already, but 1 click = 1 step.

**Comment by capnm** [comment]
> It is possible to change value by pressing buttons already, but 1 click = 1 step.

If you hold the LMB over the integer value and move the mouse pointer, you might be surprised.

**Comment by Wiadomy** [comment]
> old the LMB over the integer value and move the mouse pointer, you might be surprised.
That's right, but it's quite different from keeping pointer in place and pressing the button - less precise

**Comment by capnm** [comment]
@Wiadomy you really should fill out the the issue form. Some sliding issues have been fixed recently.

> But I just tried it on TextureRect and other some controls. it seems to not work on rect_position.x or y nor rect_size.x or y, when you try to move mouse to the right.

In fact, that seems to be broken on the current git master-tip. Please create a new issue for this (if there isn't already one).

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/41855, closing. Echo/key repeat events are supported. You can hold down modifier keys like <kbd>Alt</kbd>, <kbd>Shift</kbd> and <kbd>Ctrl</kbd> to modify the speed at which the value changes.

https://user-images.githubusercontent.com/180032/135682159-aecdc3ce-1b1d-4bc7-96f0-e9a2c79ce961.mp4
