### ISSUE TITLE
Tilemap origin BOTTOM_LEFT and CENTER displaces offset texture and I think it should not.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#22989]
**Godot version:**

451e5fd0511bc2c17a66fc73a0de9a5169109517
but this problem is a concept problem in godot from 2.1 and probably before.

**OS/device including version:**

All

**Issue description:**

Ok, this is not a short issue, this is a problem that i have experiencie from long time ago and requires a long explanation.

Resumed problem:  When you change tile origin in tilemap, not only the "origin point" (point that is used to calculate z-order and other things) is displaced... the offset of the texture is displaced. Images:

![tiletopleft](https://user-images.githubusercontent.com/11712737/46907333-36779380-cf11-11e8-9fb0-c60fe00e83f1.png)
![tilebottomleft](https://user-images.githubusercontent.com/11712737/46907337-38415700-cf11-11e8-953f-4f8242b7c537.png)
![tilecenter](https://user-images.githubusercontent.com/11712737/46907339-3aa3b100-cf11-11e8-88af-dea15039eb1f.png)

Extended problem (a.k.a. the misconception of "origin point" and the tiles that are outside the tile, personal opinion):

   Origin point allow you to know the map point of the tile, and if you are doing a "TopDown" Z Order game, allows you to make the "character behind wall or tree" effect. I´m doing a game of this type, and i did a tool to center and calculate the offset of the texture in the tilemap when origin is "BOTTON_LEFT", because this is the necessary origin point of the tile. Real problem is that, you can not use flip_v, flip_h or transpose, because BOTTOM_LEFT, become TOP_RIGHT and other strange places by using that... so you need to duplicate and duplicate tiles to do the entire map....

... and later, thinking and thinking, and looking at the commit history of tile_map.cpp i see a lot of hacks that i think goes in the wrong direction... I explain:

There is not sense to have a  off centered texture by default in tilemap, there is not good reason to have a tile out of a tile in your map... you have tile texture offset to do that. In current system  flip_h flip_v and transpose lost their sense...

Tilmap_cpp have some variables that have not value and are passed to functions by parameters (sorry about size):
![parameter-novalue](https://user-images.githubusercontent.com/11712737/46907471-2b256780-cf13-11e8-85a8-d9e0b34a1ff5.png)

There are partial fix to fixing one fix that fix other fix, and forget other fix:
![image](https://user-images.githubusercontent.com/11712737/46907495-abe46380-cf13-11e8-94ae-4a6dcd0da25b.png)
![missingoffset1](https://user-images.githubusercontent.com/11712737/46907592-2792e000-cf15-11e8-8274-8478f187e822.png)

And i think that all of this is because some programmers are misunderstanding the tile texture offset- tile origin... (Or it´s me... i don´t know).

I fix the texture offset only by commenting lines in tile_map.cpp, but there is other related problems like the shapes, the tilemap editor, etc.... I don´t know if i´m crazy with that or i´m right, i would like to read some game dev that are trying to do a 2D topdown game with z-order ocultation,  and some godot programmer opinion.

**Minimal reproduction project:**

There is the project that i use to some of the captures... but i think is not project related, it´s dessign related.
[Godot_TileMap_Test.zip](https://github.com/godotengine/godot/files/2475623/Godot_TileMap_Test.zip)

**Comment by Ranoller** [comment]
There is no option to re-up the topic but i would like to read other developers or programmers about this topic because i don't want to maintain my own version for tile_map.cpp and tile_map_editor.cpp, if there is a workaround to flip h flip v and transpose tiles in not squared maps or isometric maps, or with BOTTOM LEFT or CENTER origin without displace the texture and i didn't know about that can be very helpful to my to know that workaround.

Thanks for read.

**Comment by KoBeWi** [comment]
>  i don't want to maintain my own version for tile_map.cpp and tile_map_editor.cpp,

If you solved/can solve the issue, then you could make a PR.

**Comment by Ranoller** [comment]
I was not sure to do that. That hack only fix texture offset in tilesets made with traditional manner (with export tileset tool). Last time that i compile that hack, shapes drawn in tileset editor had bad offset.... and i don´t know well how to correct that, and do "clang style", and i don´t use git to commit to godot (don´t know all things that godot devs will start to ask me to do like squash, make the things in other way.... and for now you are the first person to see the issue... You experiment the same issue?, because that change is "breaking compatibility", if is considered a bug, godot usually don´t respect bug as feature... but is so breaking change and  if someone is using this bug as feature.... that´s why i made this "big" issue, to explain and to ask for opinions and consensus. It will be fine to know if you find current tileset offset a bug...

I feel that this is a dessign problem that should be fixed by a real aplication dessigner and real c++ programmer.

Anyway i will do that pull request, although the hack will be not merged...

**Comment by Ranoller** [comment]
Reading other time the issue... problably that empty variable (center_ofs) has any value sometime in godot history... and probably current behaviour was not in the begining of the feature. It will take  me some time to find and undestand that (c++ and headache are synonymous to me) but will try.

**Comment by Ranoller** [comment]
Well... I fix almost all problems with displace textures. Rest one problem with textures with different size that tiles and with different offset... this thing is make me a miserable... i hope the changes will be merged:
![AvancesTileMap](https://user-images.githubusercontent.com/11712737/57202778-a03cb500-6fa9-11e9-8238-764873f6d16d.png)

**Comment by Ranoller** [comment]
Well.... I think it´s done. There is much code deleted and few added... and i think it works how it is supposed. I have to adapt to a recent master, i hope there was not too much changes in tile_map.cpp and tile_map_editor_plugin.cpp... if not, i make a commit in a few days and pray for the merge in 3.2... i hope that akien, reduz, etc... can understand that we need an usable version of tilemap in 3 version, no mathers if there will be a rewrite for 4.0:

![TileMapFix](https://user-images.githubusercontent.com/11712737/57331587-3c38fe80-7119-11e9-9b3a-466ea6402a70.png)

**Comment by Lodugh** [comment]
Looks, great thanks a lot for the effort! Then I guess you also fixed #25610?

**Comment by Ranoller** [comment]
Don't know, i will test.

**Comment by Ranoller** [comment]
> Looks, great thanks a lot for the effort! Then I guess you also fixed #25610?

Well, I tested that, it´s not related. I explain in your issue report.

**Comment by Ranoller** [comment]
Demo test actualization to include navigation:
[GodotTilemapBadOffsetTest-withNavigation.zip](https://github.com/godotengine/godot/files/3184024/GodotTilemapBadOffsetTest-withNavigation.zip)
![Tilemap bug with navigation](https://user-images.githubusercontent.com/11712737/57800540-edf7b100-7751-11e9-88bb-2e12b65e6869.png)

**Comment by Ranoller** [comment]
With the last commit to maintain compatibility the result is:
![TilemapOffsetBugJun19](https://user-images.githubusercontent.com/11712737/59983754-c1259c00-9623-11e9-9350-b3b78242b248.png)
So this issue is not fully adresses and i think i should be reopened.

**Comment by Ranoller** [comment]
https://github.com/godotengine/godot/pull/30204
