### ISSUE TITLE
Right Joystick y-axis interpreted as x-axis on Linux

### ISSUE THREAD

**Issue by Dragoncraft89** [godotengine/godot#22990]
**Godot version:**
master (happens in 3.0.6 too)

**OS/device including version:**
Debian 9

**Issue description:**
When using a joypad, the right stick's x-axis is not recognized, but instead the right stick's y-axis is interpreted as the x-axis. Happens with all joypads I have ("ikarus" from "Easy Fly 3" and a LinQ joypad)

**Steps to reproduce:**
Assign axis 2 to an action or monitor axis 2 via code.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2475615/test.zip)

**Comment by aaronfranke** [comment]
Are your controllers in the [SDL Game Controller Database](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt)? Please add them if they're not.

**Comment by Dragoncraft89** [comment]
The gamepad-tool found mappings for both of them. I was able to correct the right stick x and y-axis, but the left stick x-axis sends its data to axis 0 and strangely enough axis 2, whereas the right stick x-axis sends its data only to axis 2. All other axes are fine.

However, this is definitely a kernel issue, because jstest reports these axis values as well. Therefore I'm closing this issue.
