### ISSUE TITLE
Typed gdScript, custom sigal shows incorret warning when connected via script.

### ISSUE THREAD

**Issue by ni-code** [godotengine/godot#22993]
**Godot version:**
master #22975

**Issue description:**
Connecting custom signal via gdScript Shows a 'never used warning', although I believe this is incorrect.
If I instead connect the custom signal via the inspector, the waring disappears.

![signal_warn](https://user-images.githubusercontent.com/10292929/46908273-9a518a80-cf18-11e8-9d76-7883fe04977a.png)

@vnen I guess you are the person behind typed gdScript, can you check if this a bug or if I'm doing something wrong? ty

**Comment by CptPotato** [comment]
Isn't the warning correct?According to the docs `Object.connect()` returns an `int` which you're not using here (you don't have to, obviously).

I actually don't even know the meaning of the return value. The docs don't seem to tell anything about it either.

**Comment by lupoDharkael** [comment]
Yes it is in the docs, but in the `latest` version.
https://godot.readthedocs.io/en/latest/classes/class_object.html#class-object-connect

**Comment by ni-code** [comment]
@CptPotato Got it, that makes sense. Is there a way to ignore those warnings other than check for the returned  error code?

**Comment by CptPotato** [comment]
You can disable them project-wide in the project settings.

I think there's also some kind of keyword you can write in the code itself as a one-time ignore thing but I don't know what it is exactly.

**Comment by akien-mga** [comment]
That's not a bug indeed, though it's the kind of warning that should likely be opt-in instead of opt-out, but IIRC there's another issue to discuss this.
