### ISSUE TITLE
Can't Change Label's Default Text Size

### ISSUE THREAD

**Issue by blinkakawize1** [godotengine/godot#23014]
**Godot version:**
3.06stable

**OS/device including version:**
windows 10 64/bit latest version

**Issue description:**
Can't change the label's default font text size without having to add a dynamicfont. Can only change the dynamic font's text size.

**Comment by arkology** [comment]
You can change font text size by changing label rect size, but it doesn't work when label is in container

**Comment by eligt** [comment]
I've made a pull request that would allow specifying a custom font size for each label, it's not perfect as the font is scaled but it's generally good enough if the custom font size is not much smaller or bigger than the original font size. https://github.com/godotengine/godot/pull/29762

**Comment by girng** [comment]
You can create a custom theme (if you want all node descendants to be the same font style), or as you said just create a DynamicFont

**Comment by pycbouh** [comment]
As described above, changing the font size in `3.x` involves creating a custom theme with a new set of styles for the `Label`, or using a local override for the `font` property. In `4.0` font size is its own `Theme` property and can be configured without touching the font itself. So this is addressed.
