### ISSUE TITLE
Editor: Inspector value adjust using mouse slide does nothing when sliding to the right.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#23011]
**Godot version:**
3.1 alpha #fe0db6c
Mac OS X, High Sierra

** Issue Description **
(In reference to #22982 )

In the editor inspector for a Control, sliding mouse over ( e.g. TextureRect ) `rect_position.x or y` and `rect_size.x or y` values, only changes the value sliding to the left. Sliding to the right does nothing. 

![screen shot 2018-10-14 at 11 37 21 am](https://user-images.githubusercontent.com/930478/46918874-9cadf600-cfa5-11e8-87fd-0ccb43d96e00.png)

**Comment by swarnimarun** [comment]
It seems to be the case with Vector Ints.
