### ISSUE TITLE
Expose MultiMeshInstance instance transform and ability to add collision

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#23019]
**Issue description:**
it will be very useful if someone expose the instance transform in MultiMeshInstance node
because The "Populate MultiMesh" window dialog is not very useful  .. this node is almost useless if we can't control the instance transform in Editor
and it will be an awesome thing if we have the Ability to add collision per instance ( if this possible )
i think this will be very useful to improve the engine performance

**Comment by pgruenbacher** [comment]
The way to do this is to have a script that will take a list of nodes (whether they be editor 3d gizmos, physics objects, etc.), grab the transforms of those objects, and apply to the multimesh. Multimesh is mostly meant to be interfaced with programmatically. In my game if I want to have 30 colliding instances being rendered by a multimesh, it's simple, I just use 30 rigid bodies and then I have a multimesh listen to the transformations of those 30 rigid bodies. If you want to see this in editor mode, make sure to have a "tool" at the top of your script. 

@akien-mga I consider this closeable and too open-ended of an issue. @CCODE05B I can talk to you more about this if you're facing issues.

**Comment by Toshiwoz** [comment]
This solution might be even more efficient, maybe:
https://godotengine.org/qa/52924/how-set-collisionshape-on-multimeshinstance

**Comment by Chaosus** [comment]
Closed as this is a very old abandoned enhancement issue. If the author still needs it - this should be properly re-created at [godot-proposals](https://github.com/godotengine/godot-proposals) to receive user votes and dev suggestions.
