### ISSUE TITLE
Area body_exited signal sent while body moves but remains inside

### ISSUE THREAD

**Issue by OliPerraul** [godotengine/godot#23026]
**Godot version:**

![image](https://user-images.githubusercontent.com/24371247/46930111-b2590500-d011-11e8-99b6-b7b594e052e0.png)

**OS/device including version:**
Windows

**Issue description:**
It seems that the detection for body exiting an Area (Area3d) is broken. on_body_exited is called while the body moves around the area. The expected behaviour should be for the signal to be sent once, only when the body actually leaves the area. This makes the methods `get_overlapping_bodies` `overlaps_body` and signals `body_exited` `body_shape_exited` very difficult to use.

**Steps to reproduce:**

**Minimal reproduction project:**
1. Create a scene (spatial)
2. Create a Area (3d)
3. Create a kinematicBody moving inside the area 
4. Insert code below as part of of Area3d script

````
func _ready():
	connect('body_entered', self, '_on_body_enter')
	connect('body_exited', self, '_on_body_exit')

func _on_body_enter(boyd):	
	print('BODY ENTER')

func _on_body_exit(body):
	print('BODY EXIT')

````

5. Notice `BODY ENTER`, and `BODY EXIT` intermitently while remaining in the area.

**Screen Capture:**
![image](https://user-images.githubusercontent.com/24371247/46930402-7030c300-d013-11e8-8172-a1f682acdd7e.png)

When launching the game like this, the body enter signal will be sent immediately followed by the body exit which makes  no sense. Its like the two signals are always sent together.

**Work around:**
Perform a check on current distance vs radius when exiting, to determine if it was a bad exit. 

````
func _on_body_exit(body):	
	if body.translation.distance_to(character.to_global(detection_area.translation)) < detection_area.collision_shape.shape.radius:
		 # BAD EXIT
		return
````

**Comment by AntohaRDNS** [comment]
Same problem!
Error appear randomly

I have prepared a simple project with the reproduction of error.
(Enable Debug > Visible Collision Shapes

[Area_Test.zip](https://github.com/godotengine/godot/files/2499571/Area_Test.zip)

**Comment by MrCrowley2** [comment]
can confirm. still happens in 3.1 alpha 5.
StaticBody inside an area triggers 'body_exited' signal immediately

**Comment by MrCrowley2** [comment]
doesn't have to move.
I did some further investigation.
The problem also happens with 'area_exited' and all body types.

It seems the object has to be inside of the area when the scene is loaded.
If I place a rigid body outside of the area and let gravity move it into the area, the exit signal is not triggered while it is still inside.

If the body is inside the area from the start, body_entered and body_exited are triggered immeadiately after one another, even when the body does not move.

**Comment by unSkind** [comment]
> 
> 
> I think it is just the other way round.
> As soon as a body or area inside the detection area stops moving, the exit signal is generated.


I can confirm this. I did a workaround to run the code in callbacks (on_area_entered, on_area_exited) only when the body is moving, this way it works as expected, but sometime (very rarely though) misses the event.

**Comment by reduz** [comment]
Does this only happen when using Bullet? Does the problem disappear when using Godot physics?

**Comment by winston-yallow** [comment]
This only happens with Bullet. It does not happen with Godot physics.
(tested on Windows 10 Pro 64bit and Ubuntu 18.04 64bit)

**Comment by Zireael07** [comment]
cc'ing the resident Bullet guy then: @AndreaCatania

**Comment by AndreaCatania** [comment]
Just tested this sample project https://github.com/godotengine/godot/issues/23026#issuecomment-431700071 and it works for me.

@winston-yallow can you please upload a sample project?

**Comment by MrCrowley2** [comment]
sample project does not work here either since the sphere won't stop inside the area.
I modified it so the sphere moves into the area and stops there.
When it stops the exit signal is generated.
[Area_Test.zip](https://github.com/godotengine/godot/files/2773708/Area_Test.zip)

**Comment by winston-yallow** [comment]
Here is my sample project. It has a StaticBody and an Area, both are not moving. The Area has a script attached that will print "Body entered" and "Body exited" at the moment the game is run.
[AreaTest_with_v31_beta2.zip](https://github.com/godotengine/godot/files/2775649/AreaTest_with_v31_beta2.zip)
(Godot v3.1-beta2 64bit)

**Comment by LordBrkica** [comment]
@OliPerraul  

Hi, what has happned with your problem ?

I noticed a similar bevhaiour in Godot 4.1 and TileMap Area2D collision, I get body_exited signal while the body stays within area2D.

**Comment by AThousandShips** [comment]
@LordBrkica this was closed four years ago, please open a new issue instead of reviving an old one

**Comment by laurendriscoll** [comment]
@LordBrkica did you ever find the solution? I'm running into this same problem with an Area2D node & just opened a new issue.
