### ISSUE TITLE
Copy / Paste inspector properies via Ctrl+c / Ctrl+v

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#23024]
At the moment in order to copy something, we need to a) select property, b) right click, c) select copy option, d) open another node, e) select property, f) right click, g) select paste option.

That's a lot of work. It'd be nice if we had option to copy via Ctrl+c/v.

**Comment by DiogoASTeixeira** [comment]
Will try to implement the shortcut.

**Comment by DiogoASTeixeira** [comment]
@saranvdev Could you give an example? I only see the option to copy all params, not just one

**Comment by saranvdev** [comment]
That's weird, I can't find it right now too.

Perhaps it is only possible to copy on 3.0 version and I'm using 3.1 now... I don't know honestly. But as I think now it'd be useful to be able to copy all translation/scale etc positions at once.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1504, as feature proposals are now tracked on the Godot proposals repository.
