### ISSUE TITLE
Directional light for inherited scene preview

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#23039]
When you create a new inherited scene that is some model prefab it won't have a light as child object

1 ) It's hard to figure how it looks and adjust material parameters.
2) the thumbnail when you save the inherited scene won't have lighting for better preview and thumbnail

When making an inherited scene , it needs to have a directional light option that will not save into the scene file, but it's only purpose is better preview material and get a thumbnail with lighting.

Left is inherited scene, right is the same scene with light preview
https://github.com/DevMagicLord/Godot3/blob/master/bugs/download/lightpreviewnew.jpg?raw=true

**Comment by Zylann** [comment]
Wouldn't it be just the fact that a scene has no light by default unless you actually put a Light node? (regardless of it being inherited or not)

**Comment by mrcdk** [comment]
You can already add any light node and set it to editor only. Wouldn't that be enough?

**Comment by capnm** [comment]
> You can already add any light node and set it to editor only.

Could you be be more specific? How does it work for you? Without further ado, I see no difference, the (directional) light effect is the same in the editor and in the running project ...
git 0dbe01483a902c49ecedf4fd36b74353424145a5

![image](https://user-images.githubusercontent.com/4047289/47040560-ca05ca00-d186-11e8-8dfe-c277c78a49a7.png)

**Comment by DevMagicLord** [comment]
In Unity when you make a prefab, it has a thumbnail with some sort of lighting or environment ligthing.
It's not a dark color Tumbnail.

Why Godot could not lighten up thumbnails.
It's only a improvment proposal to make thumbnails better in Godot.
(I don't care if it's not improved)

**Comment by bojidar-bg** [comment]
I think some method of setting a default editor-only directional light (maybe in the editor, maybe per-project) and using it in all scenes without a proper light might be quite useful.

Currently editor-only Light nodes are still present in the scene tree in debug, and, AFAIK, in release build exports as well.

**Comment by akien-mga** [comment]
> Currently editor-only Light nodes are still present in the scene tree in debug, and, AFAIK, in release build exports as well.

@bojidar-bg That's about to be fixed: #23256.

**Comment by DevMagicLord** [comment]
Great.

**Comment by bojidar-bg** [comment]
@akien-mga I mean, they are present in the scene tree even if not registered on the VisualServer. So, you can still get an editor-only light via `get_node` or `get_children`.

**Comment by Calinou** [comment]
@reduz suggested on IRC that we can have a default DirectionalLight as part of the Environment resource. It should be visible both in the editor and running project, but it will disappear as soon as a DirectionalLight *node* is added to the scene. This way, we can get good lighting out of the box while keeping predictable behavior between the editor and running project.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1599, as feature proposals are now tracked in the Godot proposals repository.
