### ISSUE TITLE
Add popup menu slots

### ISSUE THREAD

**Issue by rxlecky** [godotengine/godot#23034]
Hello, I was looking into how Popup menus are constructed and I noticed they are pretty much built once and the order of items/content is pretty much static from that place on. If the menu needs a new content, the menu has to be destroyed and a built anew.

I was thinking how to overcome this limitation and came up with a relatively cheap solution to this - introduce a new **flag** for popup menu items, _slots_. Any item can be flagged as slot and apart from a regular menu item function, slots would have two other functions:

- They would serve as a popup menu insertion point - any slot could be made active and all `add_item_*`-like functions would insert a new item below that slot in a menu.

- They would propagate certain actions to their "children" - If slot is removed, all items belonging in that slot are removed too.

**Advantages**

- Popup menus could be built more flexibly. If context menu contains items provided by multiple tools, menu would be only populated with slots when it's created and these would be filled by each tool in its own code.

- As editor already contains logic for extending some of its popup menus (and control over more menus is being requested too #6128), this functionality could be used to unify access to all these popup menus and could be used to enforce a unified style of custom popup menu items, i. e. they would always be inserted at the very bottom of the popup menu located below separator named _Custom Tools_.

**Additional proposed featues**

Add _hidden_ item flag. This would keep item in the menu, but it would not be rendered, nor could it be activated with its shortcut. This would allow more dynamic popup menus. For example, if file selected in the filesystem dock doesn't match desired type, options in the menu matching actions for that type would be turned hidden, rather than deleting them from the menu. In case of mentioned example of _Custom Tools_ separator, if there are no custom tools, simply hide the separator!

This would also play nicely with the propagation slot functionality - if a slot is set to hidden, all items blonging in it would be too, easily hiding all menu items associated with certain tool.

All this behaviour could be conveniently handled in the `about_to_show` signal provided by the `Popup` class.

**Let me know what you think of this.**

**Comment by akien-mga** [comment]
As discussed in https://github.com/godotengine/godot/pull/23092#issuecomment-538414834, this should be moved to the godot-proposals repo to gather some more discussion and momentum there using the new proposals template.
