### ISSUE TITLE
Rotated nodes are not snapped to grid in the 2D editor

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot#23030]
**Godot version:** 3.0.6

**OS/device including version:** Arch Linux

**Issue description:**

"Snap to grid" in the 2D editor does not work on nodes that have been rotated.

**Steps to reproduce:**

* Create a new project.
* Switch to 2D mode.
* Drag the `icon.png` into the scene editor.
* Enable "Use Snap" by pressing S.
* Drag the icon and see how it's snapped to the grid.
* Set its `rotation_degrees` to a nonzero value; 0.1 is enough.
* Drag the icon again and see how it no longer snaps.

I would expect nodes to have their origin snapped to the grid, whether or not they have been rotated. Especially if they are rotated by some multiple of 90 degrees.

**Minimal reproduction project:** n/a

**Comment by groud** [comment]
This is fixed on master, but the change cannot be easily applied to the 3.0 branch.
You'll have to wait for 3.1.
See #14497.

Closing as already solved.
