### ISSUE TITLE
Import Tab Empty

### ISSUE THREAD

**Issue by remorse107** [godotengine/godot#23041]
**Godot version: 3.1 Latest Build**

**OS/device including version: Windows 10 64bit**
NVidia GTX 950

**Issue description:**
The Import Tab no longer displays any attributes nor does it allow for me to select the "reimport" button. 
Tab does not appear to fill with any information after selecting a dae or png.

![capture](https://user-images.githubusercontent.com/7462993/46984023-cac82e80-d0a8-11e8-89ac-55117df03070.PNG)

**Comment by ni-code** [comment]
It's working for me, compiled the engine a few minutes ago (master #23029 ) haven't tested with .dae, but with other formats like .png is working for me. I'm on linux nvidia gpu, but I'm not sure if that's relevant.
![screenshot from 2018-10-16 01-32-17](https://user-images.githubusercontent.com/10292929/46985795-2237c000-d0e4-11e8-94b0-e1b383ac54d8.png)

**Comment by groud** [comment]
Seems that it comes from the view (when you doubleclick on a folder from the tree view).
Probably that it does not update the tab properly.

Anyway, this view is going to be removed so the problem will easily be fixed ;)

**Comment by user9747** [comment]
I have the same issue now. I am on linux.

**Comment by Mathitos** [comment]
this problem still occurs for me, can we reopen this?

**Comment by akien-mga** [comment]
This has been fixed 3 years ago, what you're experience is likely a different issue. So you should open a dedicated issue with proper details on what you experience now (not what someone else experienced 3 years ago).
