### ISSUE TITLE
Favorites are broken in the "Open a File" dialog

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#23048]
**Godot version:**
3.1 155652908a4284658b6c9b27640142a15fcb502c

**OS/device including version:**
macOS 10.12.1

**Issue description:**
Favorites section in the "Open a File" dialog is broken in 2 ways:

1. The displayed paths are empty.
2. When clicking on an element, it switches to it correctly, but the folder doesn't get highlighted, so if you click again on the previous folder, it won't be selected.

![image](https://user-images.githubusercontent.com/2417849/47015362-f3b6f500-d176-11e8-9547-2fd8dba8f261.png)

**Steps to reproduce:**
Add few folders from a project to Favorites, add a TextureRect to a scene, click "Load" on the "Texture" property to load a texture. Then play with the "Favorites" section in the opened dialog.

**Comment by groud** [comment]
Probably due to the fact that Favorites can now be files too.
