### ISSUE TITLE
Allow class_name to also add a description

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23047]
**Godot version:**
3.1.alpha.calinou.4c1a5d9

**OS/device including version:**
OSX High Sierra

**Issue description:**
Not really and issue just a "request"!! to my knowledge there is no way of adding a description to a class or resource when using class_name (keyword). It is possible to add an icon but no description, that would be a good (and simple, I think) addition.

**Comment by Zylann** [comment]
This could be related to #6204 and #20318 (in the sense of providing metadata to the editor for scripts and their contents)

**Comment by willnationsdev** [comment]
Yeah, I agree. This is a job for annotations (and really, the custom icon should be too, possibly even the class_name keyword itself as well).

**Comment by Xrayez** [comment]
Given the idea with annotations in GDScript 2.0 and implemented node descriptions in #31389, is this feature redundant?

**Comment by Calinou** [comment]
@Xrayez Not completely, as we'd like the description to show up in the Create New Node dialog.

**Comment by idbrii** [comment]
_Summary of solution for future searchers:_

Class doc strings are supported in Godot 4 (d1231be1c8f8f2c16fd1047adcd3c7f997a07c1f). Put the comment _after_ `class_name` + `extends`:
```
class_name DirectoryResource
extends Resource
## A resource that loads all of the files in a directory.
```

![Image](https://github.com/user-attachments/assets/d2f54fd1-f90b-4b65-a56c-2f507865c36d)

(Caveat: Changes to this doc comment often don't update until I restart the editor.)


If you put it before class_name but have other `##` comments, they might override the doc comment:
```
## Force the global rotation to stay at 100.
class_name NilRotation
extends Node2D


## Run every frame. (Oops, this becomes the class doc string.)

func _process(_dt):
    global_rotation = 0
```
