### ISSUE TITLE
Can't export from CLI, application unresponsive

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#23044]
**Godot version:**
3.1.alpha.custom_build.b95f0e6

**OS/device including version:**
Windows 10

**Issue description:**
When running a CLI export, no files are being exported. Executing with `--export`  opens up an editor window with the project. I observed both:

* window closing automatically after short delay
* window staying unresponsive indefensibly

...in subsequent executions of the export command line.

![godot-unresponsive](https://user-images.githubusercontent.com/1224527/46995313-72c91080-d118-11e8-9438-b6878ff3b5bd.PNG)

After first execution of `--export` GodotEngine lost all it's settings (reverted editor settings to defaults, empty project list). Unable to replicate this effect with subsequent executions.

**Steps to reproduce:**
```
D:\Projects\delta-v [builder-in-windows +13 ~4 -0 !]> ..\godot\godot-src\bin\godot.windows.opt.tools.64.exe --export "Windows Desktop" D:\Projects\delta-v\steam\release\windows\ .\godot\project.godot
OpenGL ES 3.0 Renderer: GeForce GTX 1070 with Max-Q Design/PCIe/SSE2
ERROR: StreamTexture::_load_data: Condition ' !f ' is true. returned: ERR_CANT_OPEN
   At: scene\resources\texture.cpp:482
ERROR: DirAccess::copy: Failed to open D:\Projects\delta-v\steam\release\windows\
   At: core\os\dir_access.cpp:309
ERROR: EditorNode::_fs_changed: Project export failed with error code 12.
   At: editor\editor_node.cpp:494
```
Directory exists and is writable:
```
D:\Projects\delta-v [builder-in-windows +13 ~4 -0 !]> ..\godot\godot-src\bin\godot.windows.opt.tools.64.exe --version
3.1.alpha.custom_build.b95f0e6
D:\Projects\delta-v [builder-in-windows +13 ~4 -0 !]> dir D:\Projects\delta-v\steam\release\

    Directory: D:\Projects\delta-v\steam\release

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       16.10.2018     07:17                windows
```
Export from GUI works fine.

Might be a duplicate of #16949, but I saw no mention of unresponsive application and lost editor settings there.

**Comment by lekoder** [comment]
Also affects 3.1.alpha.custom_build.4c863da

[Gist with verbose output from debug build.](https://gist.github.com/lekoder/f029891926fbcb38c0c2af4681d645b7)

**Comment by lekoder** [comment]
Managed to export with:
```
D:\Projects\delta-v [builder-in-windows +13 ~6 -0 !]> ..\godot\godot-src\bin\godot.windows.opt.tools.64.exe --export "Windows Desktop"
 D:\Projects\delta-v\steam\release\windows\Delta-V.exe .\godot\project.godot
```
This is probably an documentation issue, the requirement to have executable name in the export is not clear.

Still, having the editor in unresponsive state when the path is incorrect and the lost settings may warrant investigation.

**Comment by Calinou** [comment]
@lekoder Adding an extension didn't solve the issue for me, so I had to use the `timeout` command to force Godot to quit after some time (see [this Makefile](https://github.com/Calinou/game-off-2018/blob/master/Makefile)). It requires some guesswork as to not exit too early though.

**Comment by lekoder** [comment]
@Calinou There is another problem with exports, that might be unrelated: sometimes they do indeed hang, but not every time. This is somehow project-dependent, as I was unable to replicate it on test projects reliably, but it hits me when exporting 50% of the time for my game (I'm usually exporting 6 versions in batch).

**Comment by akien-mga** [comment]
Can you still reproduce this freeze in 3.2 beta 5?
If so, does #34887 improve the situation by any chance? (https://github.com/godotengine/godot/pull/34887/files#diff-b6d74ccf775245adb707953658e4defdR569-R571 might help prevent a loop)

**Comment by akien-mga** [comment]
No answer, closing.
