### ISSUE TITLE
Suggestion: Add a "default/no override" option for control nodes' default cursor

### ISSUE THREAD

**Issue by Banderi** [godotengine/godot#23053]
As per https://github.com/godotengine/godot/issues/18043 / https://github.com/godotengine/godot/pull/18093 we now have a method for setting the default cursor shape; the problem that arises still is that the shape is overridden by any Control Nodes' default cursor setting - which is good, and exactly as intended - except there could be times where you don't want that to happen. E.g. background nodes with stuff happening and changing the cursor on the foreground, or purely hierarchical nodes like a "fullscreen" parent node for UI trees.

I reckon it'd be a good thing if, in the list of cursor shape overrides for the control node, you had a "default shape" and/or "don't do anything" setting; if the cursor moves over a UI element that has this cursor setting, it simply won't change its shape.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so tha
t proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
