### ISSUE TITLE
3D issues

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2305]
3D is very hard to use until these issues are fixed:
* Color alpha values are not preserved https://github.com/okamstudio/godot/issues/2268
* ~~~exporter writes absolute paths to images into .dae even if told to copy images https://github.com/okamstudio/godot/issues/2247 (fix exists)~~~ fixed
* AnemationTreePlayer's doesn't reset non-looping animations, so they are not displayed correctly https://github.com/okamstudio/godot/issues/2199

**Comment by mamarilmanson** [comment]
and much much more...

**Comment by reduz** [comment]
Slapin: will check as soon as I have a bit of time
Mansonmamaril: It's probably time for you to start considering Unity or
Unreal seriously, you are too anxious :)

**Comment by slapin** [comment]
That will not be that easy for you, I'm going nowhere, at least :-P

**Comment by reduz** [comment]
Oh sorry, was not meant for you. I was refering to the fact that save for
bugfixes I really want to avoid doing any serious 3D work on Godot at the
moment, at least until Vulkan is out. Need to know the reach and support it
will have before deciding anything.

**Comment by slapin** [comment]
But the bugfixes are what I'm aiming for

**Comment by slapin** [comment]
Also, waiting for vulkan might be a bit long, at least a year from now.
I think bugfixing and minor improvements like skinning speedups should not
wait that long.

**Comment by PeaceSells50** [comment]
I agree that 3d Godot needs love. We need to figure out ways to help Reduz. Remember people this is not a paid gig for him. We need to figure out ways the community can be more effective. Maybe instead of just Reduz we can form a committee and created prioritized lists and goals.

**Comment by mamarilmanson** [comment]
^ @PeaceSells50 ~ :+1: looks like we'll be forming a government... XD

**Comment by mamarilmanson** [comment]
@reduz ~ I've considered Unity... and Unreal... unity is mainstream and not really free... Unreal is overkill...

**Comment by mamarilmanson** [comment]
godot is the future... only if it doesn't become too outdated...

**Comment by slapin** [comment]
Adding beurocraty never had any good results.

All that is needed is to find-out all issues to fix and have the details on what is needed to fix them.
I'm not C++ guy, but I think there are a lot of people here who could show what to check and where to look.

**Comment by mamarilmanson** [comment]
anyways... XD

was that 2nd prob same as mine? referencing to the original folder and not on the folder where godot saved it?

**Comment by slapin** [comment]
Regardless of whatever I think all that can really help are money and code
contributions.
Committees and contributions and organizations are b/s.
Not before there is constant flow of external contributions. As soon as
people managed to self-organize,
the problem is solved. The only reason for creating some organization is
ease of accepting donations,
but that is country-specific politics, in many countries you can be
individual to accept donations,
or commercial entity can accept donations.

For me, as the programmer, but far away from gamedev world, and game engine
development,
it woild be easier to just press "donate" button somewhere. That would
probably could make developers
spend a bit more time on godot. Also I can contribute when I know what I'm
doing, but with my constant
lack of time as my $$$ work consumes all time, I can't spend enough time to
learn the code base
and even distinguish area where I could help. I could check some things,
and look at some parts without
too much OO, but that all is quite unpredictable. So I beleive more that I
could be of more help with
occasional donations than with code at the moment, while I'd like more to
be useful with some code.

**Comment by slapin** [comment]
Manson, please look at original bug, there is a fix for it, it just writes
wrong paths if file already exists on the target path.

**Comment by mamarilmanson** [comment]
ok... been a long time since I checked... :+1:

**Comment by akien-mga** [comment]
Archiving as the issues described originally have been split in their own issues, and the rest of the discussion is... whatever :D

**Comment by slapin** [comment]
OK, nobody cares for the bugs anyway. Either split or added to single files
for reference.
