### ISSUE TITLE
Subscenes not re-importing properly.

### ISSUE THREAD

**Issue by PeaceSells50** [godotengine/godot#2307]
Made changes in subscene. Changes were not accurately reflected in the Project that referenced the subscene. Tried to use the Re-Import option and nothing happened. When I closed Godot and then reopened Godot everything imported corrected. This can be a nuisance to have to keep closing and opening Godot.

**Comment by bojidar-bg** [comment]
:+1: can confirm.

**Comment by reduz** [comment]
Yeah this needs to be improved.. Haven't though how to do it yet

**Comment by akien-mga** [comment]
Has this been improved by the recent work on subscenes and inheritance?

**Comment by bojidar-bg** [comment]
@akien-mga I can still confirm it, though it is now fixed by just closing and opening the scene again.

**Comment by Calinou** [comment]
There should at least be a key binding to reload the current scene.

**Comment by akien-mga** [comment]
I think it was partly addressed by 7f96f06. From my testing, I've noticed that it works on the first parenting level, but not at the second level, as I commented on Facebook:

> Regarding scene reloading, it seems to work fine at the first level, but if you have:
Scene A
-> Scene B
-> Scene C
with all scenes opened in the editor, and you change scene C, the changes will only be visible on scene B, not on scene A.
>
> See e.g. https://github.com/KOBUGE-Games/project-kumquat when you open "game.tscn", "level.tscn" and "temple.tscn" and change the scale of the temple sprite.

**Comment by reduz** [comment]
please open a new issue and close this one, as I'm that will require a different solution and eventual discussion (not sure how to make it work best)

**Comment by kubecz3k** [comment]
Opened new issue: https://github.com/godotengine/godot/issues/3201 , archiving this one.
