### ISSUE TITLE
Grid view in FileSystem dock with minimal size show only one element

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23079]
**Godot version:**
3.1 0dbe014

**OS/device including version:**
Windows 10

**Issue description:**
With minimal size grid view show only one element, but when I resize it by one pixel, then dock show two elements in row.

**Steps to reproduce:**
https://streamable.com/1dpe6

**Comment by qarmin** [comment]
I think it will be better if it will display in at least two columns, especially if this dock only needs to increase the minimum width of this element by only 1/2 pixels. 

With one column it looks quite strange.

**Comment by groud** [comment]
I would simply reduce the minimum width.
