### ISSUE TITLE
Command-line Mac OSX export inconsistent with GUI export

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#23073]
**Godot version:**
3.1.alpha.custom_build.0dbe014

**OS/device including version:**
Windows 10

**Issue description:**
The OSX export is a `.zip` file containing the application. When exporting with command line with:
```
$GODOT --export "Mac OSX" $OUTDIR/game.zip $PROJECT
```
The resulting zip file is not the mac export, but just zipped source files.

Exporting with:
```
$GODOT --export "Mac OSX" $OUTDIR/game.app $PROJECT
```
Produces correct file, but with incorrect name (should be game.zip).

**Steps to reproduce:**
```
$GODOT --export "Mac OSX" $OUTDIR/game.zip $PROJECT
```
where `GODOT` is the Godot's binary and `PROJECT` is the path to `project.godot`

I understand that Godot decides on the format based on `pkg` or `zip` extension, and it misses the point with Mac export. I suggest adding explicit `--export-format` to the CLI interface.

**Comment by Calinou** [comment]
I can confirm this on https://github.com/godotengine/godot/commit/c5656b7468e1d001658390d88ec6bb087bc51321.
