### ISSUE TITLE
Can't rename and move folder, error "Error Moving"

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23080]
**Godot version:**
3.1 0dbe014

**OS/device including version:**
Windows 10, Linux Mint 19

**Issue description:**
Just can't rename or move folder on Windows but it works in Linux Mint.

**Steps to reproduce:**
https://streamable.com/jxex1
https://streamable.com/8lr3c

**Comment by qarmin** [comment]
This is strange, now on windows 10 it works good.

**Comment by swarnimarun** [comment]
Is it working on Linux too?? @qarmin

**Comment by zhagsenkk** [comment]
i build 3.1-0dbe014 myself. And on windows 10 it works good . Could you upload your exe?

**Comment by qarmin** [comment]
This bug affects also others 3.1 builds of Godot when I discovered it, but since this day, I can't reproduce this, so it was probably Windows issue which happened only once.
