### ISSUE TITLE
Errors after delete duplicate folder from other folder with & and space before and after in its name

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23082]
**Godot version:**
3.1 0dbe014

**OS/device including version:**
Windows 10, Linux Mint 19

**Issue description:**
On linux it works fine but on Windows after duplicate folder "AAA & DDDD", I tried to delete newly created folder, and then this error was occurred:

> ERROR: Failed to get modified time for: C:/PR/GAGA/AAADDD2
   At: drivers/windows/file_access_windows.cpp:306
ERROR: Failed to get modified time for: C:/PR/GAGA/AAADDD2/default_env.tres
   At: drivers/windows/file_access_windows.cpp:306
ERROR: Failed to get modified time for: C:/PR/GAGA/AAADDD2/icon.png
   At: drivers/windows/file_access_windows.cpp:306
ERROR: load_image: Error opening file: res://AAADDD2/AA2/icon.png
   At: core/io/image_loader.cpp:56
ERROR: _reimport_file: Error importing: res://AAADDD2/AA2/icon.png
   At: editor/editor_file_system.cpp:1545
ERROR: _reimport_file: Condition ' !f ' is true.
   At: editor/editor_file_system.cpp:1551
ERROR: load_image: Error opening file: res://AAADDD2/AAA & DDDD/icon.png
   At: core/io/image_loader.cpp:56
ERROR: _reimport_file: Error importing: res://AAADDD2/AAA & DDDD/icon.png
   At: editor/editor_file_system.cpp:1545
ERROR: _reimport_file: Condition ' !f ' is true.
   At: editor/editor_file_system.cpp:1551
ERROR: load_image: Error opening file: res://AAADDD2/icon.png
   At: core/io/image_loader.cpp:56
ERROR: _reimport_file: Error importing: res://AAADDD2/icon.png
   At: editor/editor_file_system.cpp:1545
ERROR: _reimport_file: Condition ' !f ' is true.
   At: editor/editor_file_system.cpp:1551

**Steps to reproduce:**
https://streamable.com/q2usf

**Comment by zhagsenkk** [comment]
I think this is related with #23080.

**Comment by Anutrix** [comment]
Is this issue still present in latest master?

**Comment by KoBeWi** [comment]
No.
