### ISSUE TITLE
»Align selection with view« warps the selected object out of our planet in orthographic mode

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#23096]
**Godot version:**

0dbe01483a902c49ecedf4fd36b74353424145a5

**OS/device including version:**

Linux

**Issue description:**

»Align selection with view« in orthographic mode shouldn't move, only rotate the selected
object.

**Steps to reproduce:**
Switch the 3D view to orthogonal mode (numpad + 5).
Select an object in the view and select the menu entry »Align selection with view«

**Minimal reproduction project:**

![image](https://user-images.githubusercontent.com/4047289/47112100-a067a400-d255-11e8-8a08-2c681ce5a5b7.png)

![image](https://user-images.githubusercontent.com/4047289/47112138-c42aea00-d255-11e8-8049-aaafe405afa5.png)

![image](https://user-images.githubusercontent.com/4047289/47112589-11f42200-d257-11e8-8354-5da34b8e19a3.png)

**Comment by malbach** [comment]
Hi,

I see you're compiling Godot so could you test this patch ?
```diff
diff --git a/editor/plugins/spatial_editor_plugin.cpp b/editor/plugins/spatial_editor_plugin.cpp
index f57614b3b..db79bd8dd 100644
--- a/editor/plugins/spatial_editor_plugin.cpp
+++ b/editor/plugins/spatial_editor_plugin.cpp
@@ -2521,10 +2521,11 @@ void SpatialEditorViewport::_menu_option(int p_option) {
                                if (!se)
                                        continue;

-                               Transform xform = camera_transform;
-                               xform.scale_basis(sp->get_scale());
+                               //Transform xform = camera_transform;
+                               //xform.scale_basis(sp->get_scale());

-                               undo_redo->add_do_method(sp, "set_global_transform", xform);
+                               //undo_redo->add_do_method(sp, "set_global_transform", xform);
+                               undo_redo->add_do_method(sp, "set_rotation", camera_transform.basis.get_rotation());
                                undo_redo->add_undo_method(sp, "set_global_transform", sp->get_global_gizmo_transform());
                        }
                        undo_redo->commit_action();
```

**Comment by capnm** [comment]
@reduz Only the `set_transform` notifies the inspector, is that intentional? 
 https://github.com/godotengine/godot/blob/master/scene/3d/spatial.cpp#L235
