### ISSUE TITLE
Godot is not responding when it gives error.

### ISSUE THREAD

**Issue by burakyucel07** [godotengine/godot#23099]
**Godot version:**
 3.0.6

**OS/device including version:**
Windows 8.1

**Issue description:**
When my server .exe is opened, and when client .exe is giving an error, the client stops responding. When I open two windows together, one of them is the server, and one of them is the client, when I do something wrong with the client, it doesn't print the error. How do I know it gives an error? Because when I do the same thing without opening the server, it prints some error(just coding related error). You will say that shut down the server and try the reproduce the error with the client, but no. When I shut down the server, client disconnects and shuts down too. How can I see the error without opening server? Some .tscn scenes of my game doesn't check if it's disconnected or not. It's complicated, I tried to explain but I may be failed. Sorry about that. Is there any error log file that Godot writes to? 

**Steps to reproduce:**
Code your server and client.
Connect client to server.
Do something wrong with the client.
When it gives error, it will stuck.

**Comment by Calinou** [comment]
@Sphynxinator Can you share an example project to make it easier to reproduce the issue locally? Thanks in advance :slightly_smiling_face:

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Sphynxinator** [comment]
[godot-online.zip](https://github.com/godotengine/godot/files/5044935/godot-online.zip)

Sorry, I totally forgot about this when I switched to Node.js for the server. I prepared a minimal reproduction project. I added explanation to the project codes, but I want to tell how you can produce the bug.

1. First, open the both server and client projects.
2. Run the client alone. Client will give an error about a nonexistent function.
3. Close the client.
4. Run the server. If it prints some increasing numbers, and the float that is sent from the client, it works.
5. Run the client while server is running, client won't give any error.

I don't know if it's an error though.

**Comment by KoBeWi** [comment]
CC @Faless

**Comment by Faless** [comment]
Sounds really weird, are you running 2 editor instances? Can be simply
related to the fact that only one editor can debug at each time.

**Comment by KoBeWi** [comment]
Yep, it only happens with two editor instances.

**Comment by Sphynxinator** [comment]
Yeah, it also gives some debug port error before running the two instances together. Simply switching to another platform for server usage(like I switched to Node.js or Java back then) fixes the problem, but I don't know if an engine user will plan to use the Godot Engine for server too.

Is there any way other than using the two editor instances together if anybody will use Godot Engine for both as a server and as a client?

**Comment by KoBeWi** [comment]
> Is there any way other than using the two editor instances together if anybody will use Godot Engine for both as a server and as a client?

You can run the project without opening editor. Just run Godot inside the project directory (e.g. from command line).

**Comment by Sphynxinator** [comment]
I didn't know Godot also runs without opening the editor. I tried to add the Godot directory to the PATH and changed the name of the exe to "godot" and yeah, it worked.

**Comment by Faless** [comment]
Automatic port assignment for the debugger was implemented in 3.x via #37067 and 4.0 via #53241
