### ISSUE TITLE
Right-click ('freelook') does nothing useful in the orthogonal mode

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#23095]
**Godot version:**

0dbe01483a902c49ecedf4fd36b74353424145a5

**OS/device including version:**

Linux

**Issue description:**

RMB in the orthogonal 3D-view of the editor just hides and warps the mouse pointer.
It can pan the view (= shift + MMB).

**Steps to reproduce:**
Switch the 3D view to orthogonal mode (numpad + 5) and right-click anywhere in the view.

**Comment by aaronfranke** [comment]
The relevant code can be found [here](https://github.com/godotengine/godot/blob/b550f93cfd7862fdf9bf4fc838f2ad04ef89a131/editor/plugins/spatial_editor_plugin.cpp#L1912).

**Comment by capnm** [comment]
I think it could be something like:
```c++
if (orthogonal) {
	// do the same as shift + MMB
} else {
	...
```
