### ISSUE TITLE
Black bars not rendering in GLES2

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#23102]
**Godot version:**
3.1 b550f93

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Setting the black bar margins in GLES2 has no effect. But in GLES3 they work.

**Minimal reproduction project:**
```GDScript
func _ready():
    VisualServer.black_bars_set_margins(100, 100, 100, 100)
```

**Comment by akien-mga** [comment]
Fixed by ee3eadf345096b013f0fd747bf707a3aa7b87046.
