### ISSUE TITLE
Download files at runtime via HTTP

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#2310]
It is necessary to add a new HTTP load mode ...

**Comment by cjmxp** [comment]
Curl should be easy to integrate

**Comment by reduz** [comment]
godot alrady has built-in http and https, which work very well. What do you
mean with load mode?

**Comment by cjmxp** [comment]
web http Download
func _ready():
	img = load("http://www.godotengine.org/log.jpg")
        bytearray= load("http://www.godotengine.org/test.pck")

**Comment by punto-** [comment]
This would go great with some kind of standard background loading API, but
if you just use load(), you'll be blocking on that call forever, so it
doesn't really have a practical use..

**Comment by bojidar-bg** [comment]
BTW, there is a tutorial on how to do it in the wiki: http://www.godotengine.org/projects/godot-engine/wiki/HTTP_Example_of_using_the_HTTP_Client_class .
