### ISSUE TITLE
No way to set starting Camera2D offset within Drag Margin

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#23108]
**Godot version:**

3.1-alpha b550f93

**OS/device including version:**

Linux Mint 19 Cinnamon x64

**Issue description:**

When you have a Camera2D in your scene, it will always start dead-center on its parent node, regardless of whether Drag Margin H/V is enabled or not. It would be nice to be able to define the camera's starting offset from its parent node, relative to the drag margins. The only way to get this functionality now is via script:

```gdscript
func _ready():
	# disable drag margins
	$Camera2D.drag_margin_h_enabled = false
	$Camera2D.drag_margin_v_enabled = false
	
	# set drag margin offset
	$Camera2D.offset_h = 1
	$Camera2D.offset_v = 1
	
	# re-enable drag margins
	$Camera2D.drag_margin_h_enabled = true
	$Camera2D.drag_margin_v_enabled = true
```

Both `offset_h` and `offset_v` are already exposed to the inspector, but do nothing if their respective axes's drag margins are enabled (they DO shift the camera gizmos though...) It would be nice if they were to act as a starting offset in this case.

**Steps to reproduce:**
1. Add a Camera2D node as a child of a Node2D-derived node (such as Sprite)
2. Check both "Drag Margin H enabled" and "Drag Margin V Enabled" checkboxes
3. Check the "Draw Drag Margin" checkbox
4. Change both Offset values ("H" and "V") and watch as the camera rectangles shift properly (never letting the parent node outside of the drag margin rectangle)
5. Play the scene; the camera will go back to being centered on its parent node

**Comment by bojidar-bg** [comment]
Related to #20142?

**Comment by KoBeWi** [comment]
So, the camera is supposed to work that way. Offset_h/v are only used when drag margins are disabled and aren't accessed in any way if drag margins are enabled.

I guess it's more a feature request than a bug.
