### ISSUE TITLE
Godot 3.1 prevent adding linebreaks to strings.

### ISSUE THREAD

**Issue by qiqetes** [godotengine/godot#23113]
**Godot version:**
3.1.alpha.official

**Issue description:**
When I try to write in an exported String variable and add a "\n" to have a line break, godot adds "\\n" to avoid the new line. So I have to edit the scenes in an external editor to accomplish having a line break.

I suppose that's a feature, but should be easier to write the "\ \n" yourself over going to an editor to be able to write a line break.

**Comment by Zylann** [comment]
Isn't there an extended text mode where you can simply write line breaks with the `Return` key rather than putting special characters?

**Comment by akien-mga** [comment]
`export (String, MULTILINE)` works in the current git HEAD, I fixed it recently (might not work in 3.1 alpha 1 thus). Typed array hints don't work as you'd expect, but it's already tracked in other issues.
