### ISSUE TITLE
Using a JPEG-Image as both the albedo texture and the normal texture turns it yellowish

### ISSUE THREAD

**Issue by Windfisch** [godotengine/godot#23117]
**Godot version:** 5804efc6371fbfaec8fca6f237bd8478f2081086

**Issue description:**

When reusing an image for both albedo and normals (let alone if that makes sense or not), when using the image as normal map, it changes its texture import settings under _compression_ to "normal map" mode, loading the texture as RG only.

**Steps to reproduce:**
1. New project, add a MeshInstance with a CubeMesh and a SpatialMaterial
2. drag-and-drop a JPEG file from the "files" tab into the "albedo texture" slot of the SpatialMaterial
3. The mesh will be textured correctly
4. drag-and-drop the very same file onto the "normal texture" slot
5. The mesh will turn green/yellow-ish. The Texture's import settings will change as described above

This happens invisibly and is highly unintuitive. Accidentially doing this renders your texture yellow-ish forever (also when clearing the normal texture again), until you find the texture import settings tab and find the right setting to revert.
New users might well stumble upon this, as the fix is highly unobvious.

There probably should be a warning when an already-imported texture's settings are changed in such a way.

**Comment by KoBeWi** [comment]
Still valid in b740f64 (obviously doesn't apply only to JPG files)

This is not a bug though, more like we would need to add the mentioned warning.
