### ISSUE TITLE
Like blender, automatically compile every day.

### ISSUE THREAD

**Issue by allphfa** [godotengine/godot#23121]
Automatically compile the daily test version, like blender, to better test BUG.
Some bug is fixed, and it will wait until the official version is released.
In the past few months before release, the experiencer was really uncomfortable.

**Comment by QbieShay** [comment]
https://hugo.pro/projects/godot-builds/

**Comment by NathanLovato** [comment]
And http://docs.godotengine.org/en/latest/development/compiling/index.html if you want to compile by yourself
