### ISSUE TITLE
[wiki] Replace SceneTree with get_tree()

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#2313]
Was just trying to figure out how to control the spread of input events, found this:
https://github.com/okamstudio/godot/wiki/tutorial_input_events
But it uses the ``SceneTree`` class, which didn't work in my code (throws ``inexistent function in base GDNativeClass``). After half an hour figured out you have to use ``get_tree()`` to use ``set_input_as_handled()``

Suggesting replacement of ``SceneTree`` to ``get_tree()`` on that page, or annotating that you have to use it to get the instance of the tree instead of using the class

**Comment by Kermer** [comment]
I suggest reading all the basic and (depending on which type you will use) 2D or 3D tutorials.

There's something about SceneTree in 5th ([Scripting continued](https://github.com/okamstudio/godot/wiki/tutorial_scripting_2#groups)) tutorial.
You can easily see there that **get_tree() = SceneTree**

**Comment by WalasPrime** [comment]
Obviously if my code throws an error when using SceneTree and it doesn't when using get_tree() then get_tree() != SceneTree

It might be a bug with SceneTree.set_input_as_handled() not working or something. Anyway SceneTree is a class while get_tree() returns an object, so I don't that can be done unless GDScript allows returning generic classes.

Will investigate further. Will report another issue if SceneTree is supposed to work like get_tree().

**Comment by akien-mga** [comment]
Assigning to @godotengine/documentation (i.e. @StraToN as I'm busy doing triage :P).

**Comment by StraToN** [comment]
Done. http://godotengine.org/projects/godot-engine/wiki/Input_Events_and_Actions

**Comment by akien-mga** [comment]
Thanks!
