### ISSUE TITLE
Save branch as scene in remote scene inspector doesn't refresh filesystem immediately

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#23132]
**Godot version:**
6312f18f8e5022271b74368717a3dcec41bde019 (Downloaded from https://hugo.pro/projects/godot-builds/)

**OS/device including version:**
Linux (LXde) on a Lenovo thinkpad

**Issue description:**
Saving branches as scenes doesn't work in the remote scene inspector. In the local view it works though.

**Steps to reproduce:**
Create a new project, create a scene with a node, run this scene, go to remote scene view, try to save branch as scene.

**Minimal reproduction project:**
I think the default project is the minimal reproduction project :)

**Comment by Alien1993** [comment]
I've investigated a bit and noticed that as of now it only works when the running game is stopped for debugging. 
I'll work on a fix.

**Comment by samdze** [comment]
Any update on this?

I recently tried to save runtime branches as scenes but it doesn't work.
When I pause the game something gets saved but the resulting scene:
1. doesn't get imported immediately in the file system, so it is initially displayed as a generic resource
2. only has the root node of the branch I saved

**Comment by Calinou** [comment]
@silvanocerza Out of curiosity, did you ever figure out the cause for this issue?

**Comment by SilencedPerson** [comment]
actually, after further testing, it seems that the file gets created only after the game is closed.

**Comment by KoBeWi** [comment]
Tested on master and 2 of 3 issues mentioned above are fixed. The only remaining one is that filesystem dock does not refresh immediately.
