### ISSUE TITLE
setting the blend amount of AnimationNodeBlend2 in GDScript

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#23139]
**Godot version:**
master branch

**Issue description:**
I found that there is no way to set the blend amount of AnimationNodeBlend2

Say I already get the animation node of a AnimationNodeBlend2,
then I try to set:
`set_parameter("blend_amount", 0.5)`
but it does not work

So can I set the blend amount of a AnimationNodeBlend2 in gdscript?

**Comment by rszibele** [comment]
I do not know when this was added or if it was already like this when you created the issue, but it is possible to set the blend amount as follows (in 3.1-alpha2):

`$AnimationTree.set("parameters/MyBlendNode/blend_amount", 1.0)`

I have also tried getting the blend node with $AnimationTree.tree_root.get_node("MyBlendNode") and then setting the blend amount on that manually, like you would with every other node in Godot, though that doesn't seem possible at the moment.

**Comment by volzhs** [comment]
I was able to set it by `$AnimationTree.set["parameters/blend2/blend_amount"] = 0.5` with f7de2c0cb
but the `blend_amount` is not on help doc.
other AnimationNode parameters are not exposed to help doc also.
so it's very difficult to control animation with gdscript.

**Comment by Hiiamwilliam** [comment]
This issue can be closed. There are still some difficult things to find out about AnimationNodes, but this specific issue is now documented: https://docs.godotengine.org/en/3.5/tutorials/animation/animation_tree.html#controlling-from-code
