### ISSUE TITLE
Add setting to disable Godot's modification of a project's .csproj file

### ISSUE THREAD

**Issue by comfort-stereo** [godotengine/godot#23131]
**Godot version:**

Godot Mono 3.0.6

**OS/device including version:**

OS X, High Sierra

**Issue description:**

I would greatly appreciate a way of disabling Godot's modification of the .csproj file. 

Currently, Godot will insert a `<Compile Include="<path>/<file-name>.cs" />` for every C# script embedded in a currently opened scene. This makes some sense but it has caused me some problems for the following reasons:

- Not every .cs file I need to be included is inside of a scene. Many .cs files are not scripts at all. These need to be added directly to the .csproj file anyway.

- Renaming a .cs script from Godot's editor will not update/remove the associated <Compile /> element in the .csproj file, causing a compile error until you change the .csproj element manually.

- It's possible to use blobs in the .csproj file! This is actually the biggest reason for this issue. A single compile element such as `<Compile Include="**\*.cs" />` will include and compile all .cs files in the project folder. It's not necessary to write out the paths for every element. Currently, if you insert the above blob compile element into an appropriate `<ItemGroup/>` element of the .csproj file with no other `<Compile />` elements, a .csproj will generally compile fine. However, as soon as a scene with a .cs script is opened in the editor, a `<Compile/>` element for that script will be put into the .csproj file alongside the `<Compile Include="**\*.cs" />` element. This will cause compilation errors due to multiple inclusions of the same file. In this case, the auto-modification of the .csproj file causes a loss of functionality.

**Steps to reproduce:**
1. Create a new Godot Mono project and add a C# script to some node. Save the node as a scene anywhere in the project.
2. Observe the added `<Compile/>` element in the .csproj file for that script.
3. Close the tab for the scene.
4. Delete all `<Compile/>` elements in the .csproj file and replace them with a single `<Compile Include="**\*.cs" />`.
5. Compile the project.
6. Observe compilation.
7. Reopen the created scene.
8. Observe the added `<Compile/>` element in the .csproj file for that script.
9. Compile the project.
10. Observe the "item was specified more than once" error and failure to compile.

**Minimal reproduction project:**

[CSProjExample.zip](https://github.com/godotengine/godot/files/2494744/CSProjExample.zip)

**Comment by neikeq** [comment]
>It's possible to use blobs in the .csproj file! This is actually the biggest reason for this issue. A single compile element such as <Compile Include="**\*.cs" /> will include and compile all .cs files in the project folder. It's not necessary to write out the paths for every element. Currently, if you insert the above blob compile element into an appropriate <ItemGroup/> element of the .csproj file with no other <Compile /> elements, a .csproj will generally compile fine. However, as soon as a scene with a .cs script is opened in the editor, a <Compile/> element for that script will be put into the .csproj file alongside the <Compile Include="**\*.cs" /> element. This will cause compilation errors due to multiple inclusions of the same file. In this case, the auto-modification of the .csproj file causes a loss of functionality.

This should no longer be the case on latest master. Godot will not add the files if there is already a pattern that matches it (including `**`).

I have to say I still find it weird that it would cause an error. I would expect a warning...

**Comment by neikeq** [comment]
The setting was added in #23505
