### ISSUE TITLE
Editor: Provide Inspector property settings for size Sprite with pixel size

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#23145]
**Godot version:**
All

** Issue **
Provide Inspector property settings for size Sprite with pixel size in addition to scale.

![screen shot 2018-10-19 at 11 17 39 am](https://user-images.githubusercontent.com/930478/47227388-b3cb5a00-d390-11e8-9cb3-0359425fa224.png)

**Comment by akien-mga** [comment]
This does not appear to be a good idea, see discussion in #27935 and closing comment at https://github.com/godotengine/godot/pull/27935#issuecomment-501258590.
