### ISSUE TITLE
glTF 2.0 : Some meshes not loaded

### ISSUE THREAD

**Issue by damarindra** [godotengine/godot#23143]
**Godot version:**  #23138

**OS/device including version:** Win 10

**Issue description:**
I have many fbx models, since Godot is not supported FBX format, so I try to convert to glTF using https://github.com/facebookincubator/FBX2glTF and import it to Godot. The result meshes from the face is gone. Image on the right side is 3DBuilder from windows apps.
![image](https://user-images.githubusercontent.com/8519218/47225009-2e26c900-d3e7-11e8-8a87-0b93b60078b7.png)
I try blender and import the glTF, meshes are fine but armature is broken.

**Steps to reproduce:** 
Import this file [unitychan.zip](https://github.com/godotengine/godot/files/2496259/unitychan.zip)
This is UnityChan from unity, I don't know if this allowed. Tell me if not allowed, I will delete this file.

**Comment by fire** [comment]
Assuming this is the same file https://github.com/kaorun55/UnitySandbox/blob/master/ModelView/Assets/UnityChan/Models/unitychan.fbx blender is unable to open it either.

**Comment by fire** [comment]
![blender_2018-10-19_12-06-18](https://user-images.githubusercontent.com/32321/47238539-68687a00-d397-11e8-8ed4-036fde45c2ba.png)

Here is the view from blender 2.8

**Comment by fire** [comment]
Although this plugin has the same problem since it uses fbx2gltf, you might want to try it.

https://github.com/fire/com-chibifire-fbx-plugin/releases

Currently gltf anim has problems which I've done a fix for but it's 3.2 https://github.com/godotengine/godot/pull/22876.

**Comment by damarindra** [comment]
yes, you are right, that's why I need to convert it to glTF, since blender FBX import has a lot of limitation when it comes from Maya.  If you import the glTF to the Blender, it will be fine, but armature is broken.

**Comment by Kinwailo** [comment]
The model is indeed imported correctly in blender, just the face rotation and scale is incorrect. You can select those parts and clear location, rotation and scale, then scale 0.01 and rotate x 90. The face return to correct location.

![image](https://user-images.githubusercontent.com/28286958/50581792-f1238c00-0e97-11e9-9e8a-8740541cc52d.png)

![image](https://user-images.githubusercontent.com/28286958/50581818-26c87500-0e98-11e9-9fcd-616fb8fed277.png)

**Comment by clayheaton** [comment]
@bojidar-bg When I import any of the `.gltf` files from [Kenney's free Nature Kit asset pack](https://kenney.nl/assets/nature-kit), the meshes do not appear in Godot 3.1 Beta 5. I am able to import the files into Blender without a problem and then export to `.dae` to import into Godot, though. 

Here's an example of one of the files (with `.txt` appended to the file name so that I can upload it) (though I encounter the same problem with all of them):

[tree_detailed.gltf.txt](https://github.com/godotengine/godot/files/2876122/tree_detailed.gltf.txt)

The editor shows some variant of this error when I attempt import and/or changing import settings:

```
 core/os/file_access.cpp:560 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 editor/import/editor_scene_importer_gltf.cpp:510 - Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
 editor/import/editor_scene_importer_gltf.cpp:510 - Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
 editor/import/editor_scene_importer_gltf.cpp:510 - Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
 editor/import/editor_scene_importer_gltf.cpp:510 - Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
 editor/import/editor_scene_importer_gltf.cpp:510 - Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
 servers/visual_server.cpp:969 - Condition ' array_len == 0 ' is true.
 scene/resources/mesh.cpp:796 - Condition ' len == 0 ' is true.
 scene/resources/mesh.cpp:928 - Index p_idx=-1 out of size (surfaces.size()=0)
 editor/import/editor_scene_importer_gltf.cpp:510 - Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
 editor/import/editor_scene_importer_gltf.cpp:510 - Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
 editor/import/editor_scene_importer_gltf.cpp:510 - Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
 editor/import/editor_scene_importer_gltf.cpp:510 - Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
 editor/import/editor_scene_importer_gltf.cpp:510 - Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
 servers/visual_server.cpp:969 - Condition ' array_len == 0 ' is true.
 scene/resources/mesh.cpp:796 - Condition ' len == 0 ' is true.
 scene/resources/mesh.cpp:928 - Index p_idx=-1 out of size (surfaces.size()=0)
```

**Comment by capnm** [comment]
Your get such errors if you forget to copy the associated *.bin files. The internal godot filesystem seems to be broken, try to use the OS file manager to copy the gltf+bin files.

**Comment by fire** [comment]
![editor_screenshot_2020-01-09T132253-0800](https://user-images.githubusercontent.com/32321/72105860-2fd9f680-32e3-11ea-9d88-765560646dcb.png)

Appears to import correctly.

Thanks for your contribution.

**Comment by fire** [comment]
https://github.com/godotengine/godot/commit/76678b2609921f27f52c1a2e2bd62b8d2a27bb4b

The screenshot is from master for Godot Engine 3.2
