### ISSUE TITLE
MSAA support in 3D

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#2315]
Currently, it is only possible to enable FXAA (Fast approXimate Anti-Aliasing) in 3D. Drivers can request a slower but prettier anti-aliasing, that has been done for years now: Multi-Sample Anti-Aliasing.

MSAA is slower, but looks sharper and doesn't "blur" the image like FXAA does. It however does not work on transparent textures. For this, you would need SSAA (SuperSample Anti-Aliasing) which is very slow.

This should be fairly easy to do.

**Comment by reduz** [comment]
GLES2 does not support it :(

**Comment by Calinou** [comment]
> GLES2 does not support it :(

I guess this will wait for the Vulkan rewrite then.

**Comment by slapin** [comment]
It diesn't look too fundamental ant it is easy to test if it is supported,
so I think it should be easy to implement

Also it is possible to enable that in Android:
http://www.jayceooi.com/how-to-enable-4x-msaa-in-opengl-es-2-0-android-apps-games/
It is also quite easy to enable this feature, so I really don't think there
is any need to wait for Vulkan.

https://www.opengl.org/wiki/Multisampling

**Comment by slapin** [comment]
Also, for iphone:
https://nicolasgoles.com/blog/2010/07/tutorial-using-anti-aliasing-msaa-in-the-iphone/

**Comment by slapin** [comment]
And also, from what I see the MSAA is either present or not regardless of
GLES2/3 so you can't just
check OpenGL version, you need to check for it explicitly, or just have
setup option and hope for the best.

**Comment by Gibbz** [comment]
would love to see this in 3.0!

**Comment by Calinou** [comment]
This is now supported in the new renderer (up to 16× MSAA can be used):

![screenshot_20170307_113805](https://cloud.githubusercontent.com/assets/180032/23652812/8d565114-032a-11e7-92dc-1a55bceaaf96.png)
