### ISSUE TITLE
3.1 projects are listed from the 3.0 project manager

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23153]
Godot 3.0.6

I noticed projects from the next minor Godot version are being shown in the project manager.
It doesn't let you launch them anyways (and doesn't tell you why either), so would it make sense to not include them in the list?

**Comment by pgruenbacher** [comment]
listing but grey-out disable would be even better to prevent user confusion why stuff is missing too.

**Comment by Zylann** [comment]
I'd like to be able to filter them out because I'm starting to have quite a lot of projects in both versions and they are just cluttering the list

**Comment by PetePete1984** [comment]
I've been launching the nightlies with the `_sc_`/`._sc_` self-contained flag file in their folder, to prevent such mishaps. Otherwise you will get collisions in the editor's global settings files.

**Comment by KoBeWi** [comment]
Or maybe store last used Godot version in project settings and warn when trying to open with older version?

**Comment by dark-penguin** [comment]
How about this:
- Store the last used Godot version in project.godot
- In Project Manager, show projects from "wrong" versions grayed out and in the bottom of the list
- When trying to open an old project with a new Godot: warn "We'll have to convert this project, this may break it forever"
- When trying to open a new project with an old Godot: warn "We will probably not be able to open it, do you still want to try?"

**Comment by KoBeWi** [comment]
^
Actually, this is already how it works in 3.2, except for the last point. You just can't open project in older Godot version (but 3.1 and 3.2 are compatible, so it's not apparent). IMO it's fine to close this issue. Most people don't use Godot 3.0 anymore.
