### ISSUE TITLE
Allow to customize the UI of the inspector (even for builtin type)

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23156]
**Issue description:**
The inspector UI has been (is being) through changes and I wanted to know, how difficult and how receptive the community is to add the possibility to customize the UI in the node/resource inspector for a given variable (variable type... when exporting custom var types are made possible in the future).

Something in the likes of if checkbox is ticked in the inspector disable the entry of a variable.... or change the type from a string to a dropdown. Or being able to add a button that could for example trigger functions/signals for debugging purposes!

Being able to do such things are good additions to the tools Godot already presents. And once the GUI game components are the same used for making the Editor I think it wouldn't be a big change to the structure of the software!

**Comment by starry-abyss** [comment]
Didn't try 3.1 inspector yet, if this is not implemented yet, the idea sounds good to me.

**Comment by Chaosus** [comment]
Proposing global changes should be in https://github.com/godotengine/godot-proposals now. Closed.
