### ISSUE TITLE
failed init DINPUT: -2147467259

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#23165]
**Godot version:**
3.0.6, but custom build of 8ac39d8 with my module inside (gameplay code, has nothing to do with joypads or audio), VS 2017

**OS/device including version:**
Windows 7, 64 bit

**May be important:**
I compiled the engine with -j2, and had to remove the .gen.cpp file with gamepad definitions because scons complained about it...

**Issue description:**
After editor compilation, I got this crash on the first run:
![default](https://user-images.githubusercontent.com/11571820/47249977-53d1c380-d423-11e8-8d46-ed8561ec8432.png)

After some seconds the editor self-restarted, and it didn't crash then.
The first time on self-restart (but not the second time) I got also these errors:
![default](https://user-images.githubusercontent.com/11571820/47250016-22a5c300-d424-11e8-9e5f-f4ca629dae87.png)

The editor didn't crash the next several times I ran it.

**Steps to reproduce:**
Happened two times for me on first editor launch after its compilation.  I copied the editor binary to some folder before running both of times.

**Minimal reproduction project:**
No game project involved, just the project manager window of the editor.

**Comment by akien-mga** [comment]
>  I compiled the engine with -j2, and had to remove the .gen.cpp file with gamepad definitions because scons complained about it...

If it complains that means you had likely built the master branch or another older branch from the same tree previously, and had some conflicting `.gen.*` files left over. It would be worth trying a build from a clean repo.

**Comment by Calinou** [comment]
@starry-abyss Can you try building Godot from a clean copy of the repository? :slightly_smiling_face:

`git clean -dfxi` can be used to remove ignored and untracked files interactively.

**Comment by starry-abyss** [comment]
@Calinou Yes, I built a couple of times today after "scons -c", and didn't get this issue. Given that I did switch from master branch, that's probably it.

Nonetheless, can Scons be adjusted so it discards those files between different versions of Godot? I think it defeats the purpose of file caching to not be sure that only correct files are cached.

**Comment by Calinou** [comment]
> Nonetheless, can Scons be adjusted so it discards those files between different versions of Godot?

Where would we draw the line for "different versions of Godot" though? For instance, there's a lot of changes between 3.1alpha1 and 3.1alpha2, yet both share the same `3.1.alpha` identifier (e.g. for export templates).

**Comment by starry-abyss** [comment]
I believe, on file basis. To force rebuild things that have dependencies changed.

**Comment by akien-mga** [comment]
SCons does rebuild everything that has dependencies changed, to the point that some consider it not to be incremental enough :)

I'm not sure what caused your issue, but the main problem with switching branches is generated source files that are globbed (e.g. building all `*.cpp` in a folder) even if they were generated by a different version, which is why one should clean generated files when switching branches (or after any buildsystem overall that would lead to some generated files being no longer used).

**Comment by starry-abyss** [comment]
Yeah, that's outside the scope of the original issue.
Still, your explanation sounds more like "I was taught that there is an issue, how to workaround it, and to not bother to found a solution". :)

**Comment by akien-mga** [comment]
No, but the solution (listing every single C++ file that we want to compile manually) is a lot more hassle than the issue raised by using wildcards.
