### ISSUE TITLE
Renaming script causes changes to scene to be lost

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#23167]
**Godot version:**
3.0.6

**OS/device including version:**
macOS 10.13.6 (High Sierra)

**Issue description:**
If the script that's attached to a scene is renamed, then any unsaved changes in the scene tree get lost without a warning.

**Steps to reproduce:**
1. Create a new scene and attach a script to it
2. Change something in the scene (e.g. add a node, rename a node, change some values etc.)
3. Rename the script using the FileSystem pane in Godot

At this point you should notice that the scene reverts to its last saved state (except for the updated script reference) without any warning.

**Comment by KoBeWi** [comment]
Related to #18019

**Comment by KoBeWi** [comment]
Fixed in 3.2
