### ISSUE TITLE
Shader not taking effect at runtime?

### ISSUE THREAD

**Issue by 9BitStrider** [godotengine/godot#23177]
**Godot version:**
3.1 Alpha

**OS/device including version:**
Windows 7 Professional 32 Bit
Intel (R) HD Graphics 2000

**Issue description:**
When attempting to use a shader to change the colors of a sprite, the shader does not take effect at runtime. All params are set and the shader DOES work in the scene editor.

![screen3](https://user-images.githubusercontent.com/23580375/47259574-8c4bbe80-d470-11e8-882d-ac8140bd760c.png)

![screen4](https://user-images.githubusercontent.com/23580375/47259575-91107280-d470-11e8-87b6-f1c458ba1e03.png)

```
shader_type canvas_item;

//Set target colors.
uniform vec4 target_color_1 : hint_color;
uniform vec4 target_color_2 : hint_color;
uniform vec4 target_color_3 : hint_color;

//Set replacement colors.
uniform vec4 replace_color_1 : hint_color;
uniform vec4 replace_color_2 : hint_color;
uniform vec4 replace_color_3 : hint_color;

void fragment() {
	if (COLOR == target_color_1)
	{
		COLOR = replace_color_1;
	}
	if (COLOR == target_color_2)
	{
		COLOR = replace_color_2;
	}
	if (COLOR == target_color_3)
	{
		COLOR = replace_color_3;
	}
}
```

**Steps to reproduce:**
Run the app.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2498444/Test.zip)

**Comment by FlamyAT** [comment]
In your provided code snippets the `;` at the end of each statement (inside the fragment function) is missing.

**Comment by 9BitStrider** [comment]
Not sure how well this will help, but I did notice this as I was trying to get the shader functional.

When I loaded the project, I noticed that the shader no longer functioned in the scene editor.

![screen2](https://user-images.githubusercontent.com/23580375/47258622-81d6f800-d463-11e8-9d24-cfa2673c9e0b.png)

So, I clicked into the RGB values to set them to the correct numbers and they automatically set themselves, correcting the shader in the scene editor:

![screen1](https://user-images.githubusercontent.com/23580375/47258629-a206b700-d463-11e8-8157-dda3f7e83e05.png)

Doesn't fix any problems with the runtime. But, here you go.

**Comment by nobuyukinyuu** [comment]
I had a similar issue for replacing colors which seemed to have something to do with float precision.  Have you tried adding a threshold function to your shader?  This solved my issue.

I can dig up code if needed.

**Comment by 9BitStrider** [comment]
I would appreciate that. Thanks.

**Comment by nobuyukinyuu** [comment]
Sorry I took so long to respond.

Here's a basic one I used for screen-space palette shifting.  You should be able to adapt it easily by changing the sampling variables to TEXTURE, UV in the texture() function and remembering to sample the alpha component as well (I used a screen-space shader so I didn't need that).

```gdscript
shader_type canvas_item;
uniform float threshold : hint_range(0,1) = 0.01;
uniform vec4 A0:hint_color = vec4(0.0, 0.0, 0.0, 1.0);
uniform vec4 A1:hint_color = vec4(0.0, 0.0, 0.0, 1.0);
uniform vec4 A2:hint_color = vec4(0.0, 0.0, 0.0, 1.0);
uniform vec4 A3:hint_color = vec4(0.0, 0.0, 0.0, 1.0);


uniform vec4 B0:hint_color = vec4(0.0, 0.0, 1.0, 1.0);
uniform vec4 B1:hint_color = vec4(0.0, 0.0, 1.0, 1.0);
uniform vec4 B2:hint_color = vec4(0.0, 0.0, 1.0, 1.0);
uniform vec4 B3:hint_color = vec4(0.0, 0.0, 1.0, 1.0);


void fragment() {
	COLOR.rgb = texture(SCREEN_TEXTURE,SCREEN_UV).rgb;
	vec3 c = COLOR.rgb;
	
	if (abs(A0.r-c.r) <= threshold && abs(A0.g-c.g) <= threshold && abs(A0.b-c.b) <= threshold) {COLOR.rgb = B0.rgb;}
	if (abs(A1.r-c.r) <= threshold && abs(A1.g-c.g) <= threshold && abs(A1.b-c.b) <= threshold) {COLOR.rgb = B1.rgb;}
	if (abs(A2.r-c.r) <= threshold && abs(A2.g-c.g) <= threshold && abs(A2.b-c.b) <= threshold) {COLOR.rgb = B2.rgb;}
	if (abs(A3.r-c.r) <= threshold && abs(A3.g-c.g) <= threshold && abs(A3.b-c.b) <= threshold) {COLOR.rgb = B3.rgb;}

}

**Comment by 9BitStrider** [comment]
No worries. And thank you. This worked.
