### ISSUE TITLE
Lag when instancing new node with completely new material

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#23176]
**Godot version:** 3.0.6

**OS/device including version:** Android 8.0 adreno 625 GLES 3.1

**Issue description:**
This is not an issue maybe enhancement for the engine. i hope there is a way to warm up VisualServer to pre-load some material/mesh (maybe we can set some properties in script or someting) so the lag don't happened. in my case when i try to instancing new bullet to scene tree the game lag so hard in mobile. it is only happen for the first bullet tho.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
If it's only for new materials, then it's a duplicate of https://github.com/godotengine/godot/issues/13954.

**Comment by fian46** [comment]
then case close i guess. i hope this feature available soon .

cheers
