### ISSUE TITLE
GLES3 Accessing COLOR without assigning turns it white

### ISSUE THREAD

**Issue by FlamyAT** [godotengine/godot#23179]
**Godot version:** 16b0191

**Issue description:**
While debugging #23177 I came across GLES3 issue relating 2D sprites. When using the `COLOR` keyword in (either vertex or) fragment processor without assigning a value it is treated as `vec4(1.0, 1.0, 1.0, 1.0)`. Although the following two code snippets should do the same the result is different:

**White Sprite:**
```
shader_type canvas_item;
void fragment(){
    COLOR.rgb /= 2.0;
}
```

**Working Sprite:**
```
shader_type canvas_item;
void fragment(){
    COLOR = texture(TEXTURE, UV);
    COLOR.rgb /= 2.0;
}
```

**Steps to reproduce:**
Create empty project.
Add icon or any image as sprite as a node.
Attach a new shader material.
Add either code snippet.

**Comment by FlamyAT** [comment]
This sounds reasonable. Then it would be an issue GLES2 related. This behavior can't be reproduced when using it as the graphics driver.

**Comment by DavidSichma** [comment]
There is this line in GLES2 which will always be called.
https://github.com/godotengine/godot/blob/115885b1bff767a905ce98ba739fad15c5925ee0/drivers/gles2/shaders/canvas.glsl#L151

In GLES3 a similar line is surrounded by `#if !defined(COLOR_USED)`. This can be used in GLES2 as well and produces the behavior expected by @clayjohn.
However there is also some `USE_DISTANCE_FIELD`-thing in GLES3 which I do not understand. If someone knows what it is and if it should be copied to GLES2, feel free to reply.

**Comment by CptPotato** [comment]
By the lookd of it USE_DISTANCE_FIELD might be related to rendering distance field fonts.
