### ISSUE TITLE
Can't use JOYSTICK_MOTION in InputMap.action_add_event

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#2317]
I want to add analog button to InputMap for control UI with joystick

For keyboard and joystick button it work fine but joystick motion is not.
```
    InputMap.erase_action("ui_up")
    InputMap.add_action("ui_up")

    # Keyboard
    var event = InputEvent()
    event.type = InputEvent.KEY
    event.scancode = KEY_UP
    InputMap.action_add_event("ui_up", event)

    # Joystick button
    event = InputEvent()
    event.type = InputEvent.JOYSTICK_BUTTON
    event.device = 0
    event.button_index = 0
    InputMap.action_add_event("ui_up", event)

    # Joystick motion
    event = InputEvent()
    event.type = InputEvent.JOYSTICK_MOTION
    event.device = 0
    event.axis = 1
    event.value = -1
    InputMap.action_add_event("ui_up", event)
```

I resolve it by send InputEvent when want to press ation key
```
    var event = InputEvent()
    event.set_as_action("ui_down", true)
    OS.get_main_loop().input_event(event)
```

Yes, it has a condition, when stay key press it not work fine (In normal situation it will smooth shift ui).

**Comment by Kermer** [comment]
Generally adding joystick axes as Input action, with any known method, doesn't seem to be working.

**Comment by AlexHolly** [comment]
Adding the action with "Project settings -> Input Map" has the same effect.
I think it is impossible to trigger on a specific axis since all axis values are changing if you move in any direction.

So maybe adding a second value which will be the trigger line, like "Kermer" is doing here manually http://www.godotengine.org/forum/viewtopic.php?f=11&t=2505

if axes0.value > trigger_line
   action_is_pressed = true....

Is it possible to add this to the "Project settings -> Input Map" ?

**Comment by Kermer** [comment]
Just made a simple autoload script for that: https://github.com/Kermer/Godot/blob/master/joystick_motion.gd

Mind that it's not optimized yet. Adding a lot of actions might affect performance somehow.

**Comment by akien-mga** [comment]
@punto- might have an idea.

**Comment by punto-** [comment]
In my opinion this isn't something that can be solved by the input map, especially if you want to put a value to the action. Maybe an axis number can be tied to an action, like axis 0 to "character_walk_x", but doing something like "ui_up" requires interpreting a gesture (a relatively simple one, but still a gesture). It's not just saying "action ui_up pressed when the value of the axis 0 is 0.9". It's more like "action ui_up pressed when the value of axis 0 goes over 0.7, then optionally an echo pressed action every 0.2 seconds, and then wait until it goes under 0.4 for the released action, before it can be pressed again", so it's not really something that we can describe with just an input event. I think naming an axis should be fine, but for more complex stuff this is a matter for some sort of "gesture interpreter" class, that is separate from InputMap.
