### ISSUE TITLE
Array.custom_sort() argument error when giving the array a type hint.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#23183]
**Win10 64-bit alpha 3.1 115885b**

@vnen So when I apply an Array type hint to an array, I can no longer use `custom_sort()`, it complains that the object that is passed in, is not an object.  It goes away and resumes working when removing the type hint.

![godot_master_2018-10-21_00-37-17](https://user-images.githubusercontent.com/13004169/47260767-47ed0c80-d4ca-11e8-9ba4-93d680e6b057.png)
![godot_master_2018-10-21_00-37-08](https://user-images.githubusercontent.com/13004169/47260768-491e3980-d4ca-11e8-9363-3082c1af42af.png)

Example project if needed: 
[3.1 Custom Sort Error.zip](https://github.com/godotengine/godot/files/2498573/3.1.Custom.Sort.Error.zip)

**Comment by lupoDharkael** [comment]
duplicated https://github.com/godotengine/godot/issues/22888

**Comment by avencherus** [comment]
It will resolves when using this commit:  https://github.com/godotengine/godot/pull/22896
