### ISSUE TITLE
Array.custom_sort() not giving expect results.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#23184]
**Win10 64-bit alpha 3.1 115885b**

I have an array of vectors that I would like to sort by X component first, then sub sort the Y component.  This current code doesn't seem to work.  Am I missing something, or is this an instability issue on the back end?

```
extends Node2D

var array = []

func sort(a, b):
	return a.x < b.x and a.y < b.y # Is this not correct?
	
func _ready():
	
	array.append(Vector2(2, 2))
	array.append(Vector2(2, 1))
	array.append(Vector2(1, 1))
	
	array.sort_custom(self, "sort")
	print(array)
```

I have an array as [(2,2), (2,1), (1,1)], and trying to get it to sort into [(1,1), (2,1), (2,2)], however I get the following:

![chrome_2018-10-21_01-03-36](https://user-images.githubusercontent.com/13004169/47260971-08282400-d4ce-11e8-83a9-8a880b85cd7f.png)

Example Project: 
[3.1 Custom Sort Issue.zip](https://github.com/godotengine/godot/files/2498595/3.1.Custom.Sort.Issue.zip)

**Comment by Naryosha** [comment]
Given a = (2, 1), b = (2, 2)
```
a.x < b.x and a.y < b.y
 (2 < 2)  and  (1 < 2)
     true and false
         false
```
False means a > b thus a is placed after b.

You need
```
if a.x < b.x:
    return true
else:
    return a.y < b.y
```

**Comment by avencherus** [comment]
Thanks Naryosha, that is the solution, you beat me to it.  

Was a late night logic error on my part.  I slept a couple hours and woke up with this thought, "It should check for equals first..."

Wrote this version and came back to close this before someone discovered.  XD

```
static func point_sort(a, b):

	if(Lib.nearly_equal(a.point.x, b.point.x)):
		return a.point.y < b.point.y
		
	return a.point.x < b.point.x
```
