### ISSUE TITLE
Interpolated particles between frames

### ISSUE THREAD

**Issue by JustusPan** [godotengine/godot#23190]
**Potential Related Issue**
[Interpolated particles #7850](https://github.com/godotengine/godot/issues/7850)  

**Godot version:**
Godot 3.0.6 from Steam

**OS/device including version:**
Win10, x86_64
GTX1070

**Issue description:**
When I try to use particles with local_coords = false to present a "trail" effect, it just emits particles on each frame and seems “discrete”.
![demo_gif](https://raw.githubusercontent.com/JustusPan/resource/master/gif/godot_interpolated_particles.gif)   
The rotation of sword is driven by an `AnimaitonPlayer`. 

Is there any way to emit these particles smoothly but not explode on each frame?

**Steps to reproduce:**
1.open unzipped project with godot 3.0.6 
2.press f5 to run the project
3.press Space key to trigger animation

**Minimal reproduction project:**
[interpolated_particles.zip](https://github.com/godotengine/godot/files/2498965/interpolated_particles.zip)

**Comment by zhagsenkk** [comment]
"set_fractional_delta" seems not work in Particles2D, but works in CPUParticles2D.

**Comment by JustusPan** [comment]
> "set_fractional_delta" seems not work in Particles2D, but works in CPUParticles2D.

Could you please help to share any information about CPUParticles2D? Is that available on 3.0.6?

**Comment by Calinou** [comment]
> Could you please help to share any information about CPUParticles2D? Is that available on 3.0.6?

CPUParticles is already present on the `master` branch (which will become 3.1 in the future), but it is not in 3.0.6.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/47973, which has more information about the issue at hand.
