### ISSUE TITLE
HTML5 game works locally but not in browser (online)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#23191]
**Godot version:**
master

**OS/device including version:**
Arch Linux

**Issue description:**
game only runs in browser locally

**Steps to reproduce:**
use .zip as gamepack

**Minimal reproduction project:**
https://github.com/HugeGameArtGD/Solus-Stunts/releases/download/v7.0/HTML5.zip
https://hugegameartgd.github.io/HTML5/

**Comment by FlashDaggerX** [comment]
The version of this game is not in the 3.0.x branch.

This has to be done with 3.1. Could you post the commit you're on? Run `godot --version` in your shell.

**Comment by LinuxUserGD** [comment]
@FlashDaggerX I'm using Godot master.

**Comment by LinuxUserGD** [comment]
error message:
```Swift
Output:Clear

**ERROR**: Condition ' !zfile ' is true. returned: false

**ERROR**: At: core/io/file_access_zip.cpp:185:try_open_pack() - Condition ' !zfile ' is true. returned: false

**ERROR**: Condition ' !ok ' is true. returned: ERR_CANT_OPEN

**ERROR**: At: core/project_settings.cpp:312:setup() - Condition ' !ok ' is true. returned: ERR_CANT_OPEN

Error: Could not load game path '.'.

**ERROR**: Cannot read property 'forEach' of null

**ERROR**: Condition ' !_start_success ' is true. returned: false

**ERROR**: At: main/main.cpp:1258:start() - Condition ' !_start_success ' is true. returned: false

78

**ERROR**: 78


```

**Comment by eska014** [comment]
The `startGame()` function will handle `.zip` automatically, no need to call `start()` for this.
Just change `.pck` to `.zip` in the unmodified HTML shell file.

**Comment by LinuxUserGD** [comment]
@eska014 Thanks, changing `.pck` to `.zip` works but the screen remains black.

**Comment by eska014** [comment]
That issue is tracked in #22629

**Comment by eska014** [comment]
See https://github.com/godotengine/godot/issues/15983#issuecomment-359985589. Next time include what error you're getting and other console output
