### ISSUE TITLE
Editor Icons are replaced by Noise 

### ISSUE THREAD

**Issue by FlamyAT** [godotengine/godot#23198]
**Godot version:** 3ac0e8d

**OS/device including version:** Ubuntu, NVidia GTX 950M

**Issue description:**
After locking my PC and returning to it after an hour or two (I'm not really sure) I noticed that some icons inside the editor are replaced by a weird noise texture (image below) 
![screenshot from 2018-10-21 19-14-24](https://user-images.githubusercontent.com/8056898/47270008-d06cbb00-d565-11e8-86bd-2f6bfbad098d.png)
After reopening the game it was fixed.

**Steps to reproduce:**
_These steps could be total nonsense since this happened right out of thin air_
Leave the engine running while logging out.
Log back in.

P.S.: I left the game running as well and the rendering messed up as well
Messed up version:
![screenshot from 2018-10-21 19-06-31](https://user-images.githubusercontent.com/8056898/47270055-76b8c080-d566-11e8-87ee-e491cf44a6d6.png)
Normal version:
![screenshot from 2018-10-21 19-18-04](https://user-images.githubusercontent.com/8056898/47270056-77515700-d566-11e8-9b41-645e9a71583d.png)

**Comment by akien-mga** [comment]
That's a bug with Nvidia proprietary drivers on Linux, not with Godot. I have the same on Mageia 7 with latest Plasma/KWin/Qt LTS:
![screenshot_20181021_205152](https://user-images.githubusercontent.com/4701338/47270936-25fb9480-d573-11e8-9d21-4d56025b88bb.png)

**Comment by FlamyAT** [comment]
I did switch the scenes but it still didn't refresh the icons that's what made me unsure
