### ISSUE TITLE
GDScript: warns that a class variable is unused while it actually is

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23207]
Godot 3.1 alpha 1

I made a subclass in my script just to hold a few variables together, however all of them produce an "unused" warning. Of course they are not used within that subclass (because it has no functions), but I use them like "public" variables elsewhere in the enclosing script, so the warning is just adding false positive noise.

```gdscript

class Item:
    var base = null
    var length = 0

var _items = []

func _ready():
    var item = Item.new()
    item.base = get_node("X")
    item.length = 5
    _items.append(item)
    #...
```

**Comment by Zylann** [comment]
@aaronfranke yes, I read from them further down but I think the parser is unable to tell.

**Comment by vnen** [comment]
Well, this is not a bug, it's the same as #22206. It's in the same file but not in the same class (which is the purpose of the warning). I'll probably disable this by default because it doesn't make sense for classes used only as a data structure.

**Comment by Zylann** [comment]
Still happens in Godot 3.1 alpha3

**Comment by vnen** [comment]
> How would you recognize such classes?

I won't, I'll just disable the warning by default. If you think it's useful you can turn it on and disable only for some scripts.

**Comment by Zylann** [comment]
@vnen would it be possible to have it on just for variables beginning with `_`?

**Comment by Zylann** [comment]
@vnen function arguments start with `_`? I never saw that Oo

**Comment by aaronfranke** [comment]
`_process(delta)` gives a warning about unused `delta` unless you use it.

`_process(_delta)` does not.

**Comment by Zylann** [comment]
@aaronfranke yeah, I realized that. What I mean is that we just shot ourselves in the foot choosing a convention which already steps over another and prevents going further xD

**Comment by OvermindDL1** [comment]
> What I mean is that we just shot ourselves in the foot choosing a convention which already steps over another and prevents going further xD (At least if we consider not doing it because it's confusing)

Although following the rest of the industry means that variables or bindings started with and underscope means it is 'unused' after declaration, either used as an unused 'hole' in an argument list or used for documentation purposes as the unused return of some expression.  Many languages even bake the convention into the compiler itself to do precisely what is proposed here (to both signify a purposefully unused argument or to silence an 'unused return from function/expression' warning/error).

**Comment by Zylann** [comment]
So no chance to check for member vars usage then?

**Comment by OvermindDL1** [comment]
> So no chance to check for member vars usage then?

If they were private (if GDScript had a concept of private) sure, but in general I couldn't see how that would be possible.

**Comment by Zylann** [comment]
@OvermindDL1 get list of members, pick those starting with `_`, check functions and ignore occurrences that collide with arguments, unless prefixed with self? But to me the hard thing is not even the underscore, it's checking all classes inheriting it in the project to build a complete code model, depending if we are Ok walking all scripts or not.

**Comment by OvermindDL1** [comment]
@Zylann An issue with that though is that a class can have fields that are not used internally but only used externally, so you'd have to do a whole-program-analysis for it, and considering scripts can be dynamically loaded then that's impossible.  I personally use many classes as C-like structs, pure data storage and no functionality.

**Comment by Zylann** [comment]
@OvermindDL1 this is the point of the underscore. Just like the convention in unused arguments, they are a convention the parser can use. In member vars, it can be used to indicate privateness, which means the parser could ignore the case of external access.

**Comment by Calinou** [comment]
I'm getting an used member warning with the following snippet on commit https://github.com/godotengine/godot/commit/6607c3c1c7dc7e6b3e381b71c6a46dcf59d3457b:

```gdscript
onready var preloader := $ResourcePreloader as ResourcePreloader
onready var bounce_sounds := [
	preloader.get_resource("bounce.0"),
	preloader.get_resource("bounce.1"),
	preloader.get_resource("bounce.2"),
	preloader.get_resource("bounce.3"),
]
```

Is this related since I'm using it just below in another member variable?

**Comment by aaronfranke** [comment]
What's the current status of this issue? Is there a plan to deal with it?

> @vnen: I won't, I'll just disable the warning by default.

The warning is still enabled in the current master. Should the warning be disabled by default?
