### ISSUE TITLE
"Delete" key in SampleLibrary editor deleted SamplePlayer instead of highlighted sample

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2320]
As shown in the following screenshot:
![delete](https://cloud.githubusercontent.com/assets/4701338/8989535/0e1aaa2c-36ed-11e5-9c52-a9b705a583cd.jpg)

When pressing the "Delete" key of the keyboard after selecting the "respawn1" sample, it's the "SamplePlayer" from the scene menu which gets deleted, instead of the intended single sample.

Hopefully it comes back with Ctrl+Z, but still :)

**Comment by akien-mga** [comment]
@MarianoGnu @TheHX @neikeq I guess that's another case where the "Delete" key press must be marked as handled once taken by the SamplePlayer (or it might be that SamplePlayer does not know the hotkey at all, so it passes the input to the rest of the UI which deleted the selected node).

**Comment by MarianoGnu** [comment]
Looks like _input_event is not implemented at all. I'll fix asap

**Comment by MarianoGnu** [comment]
I oppened a related issue, I implemented the code, but key input events are catched by canvasiten/spatial editors

**Comment by akien-mga** [comment]
What's the status on this one?

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by bojidar-bg** [comment]
Bump?

**Comment by akien-mga** [comment]
Still up for grabs (if the bug can still be reproduced).

**Comment by MarianoGnu** [comment]
well, whatever code i wrote 8 months ago is lost for sure, i hope i can hace internet at home soon to restart helping again 😢

**Comment by reduz** [comment]
SampleLibrary is gone in 3.0

**Comment by akien-mga** [comment]
That solves it :)
