### ISSUE TITLE
Computer crashes when clicking on 'Templates'

### ISSUE THREAD

**Issue by Zeph-dev** [godotengine/godot#23202]
When I click on the 'Templates' button, my computer crashes. No clue why.

I'm using a Mac Mini (Late 2012) and Godot 3.0.2 (Stable)

Any help?

**Comment by akien-mga** [comment]
Please try Godot 3.0.6.

**Comment by Zeph-dev** [comment]
Ok

**Comment by Calinou** [comment]
@Zeph-dev Can you still reproduce this in 3.0.6 or 3.1 alpha?

**Comment by Zeph-dev** [comment]
No, not that I know of.

**Comment by akien-mga** [comment]
Thanks, closing.
