### ISSUE TITLE
Changing image outside editor cause reimport but doesn't update image size until I move it.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23217]
**Godot version:**
3.1 c1779b1

**OS/device including version:**
Windows 10

**Issue description:**
When I change image to smaller outside editor, which was use in Project, I see that image hasn't good size and have strange lines, until I move this. 

(Image should look strange because I test connecting several images into one)
![ffff](https://user-images.githubusercontent.com/41945903/47286320-73691780-d5ee-11e8-9d1f-27ecb634ddf7.png)

**Steps to reproduce:**
https://streamable.com/6407d

**Comment by akien-mga** [comment]
Duplicate of #20614.
