### ISSUE TITLE
is any plan to add official vscode extension for gdscript?

### ISSUE THREAD

**Issue by wtksana** [godotengine/godot#23214]

**Comment by qichunren** [comment]
May this help you. https://marketplace.visualstudio.com/items?itemName=geequlim.godot-tools#overview

**Comment by akien-mga** [comment]
https://marketplace.visualstudio.com/items?itemName=geequlim.godot-tools#overview is developed by @Geequlim who is a Godot contributor, so I guess it can be considered "official" :)
