### ISSUE TITLE
AudioStreamPlayer3D causing debug errors

### ISSUE THREAD

**Issue by YannBurrett** [godotengine/godot#23218]
**Godot version:**
3.06

**OS/device including version:**
Windows 10

**Issue description:**
Adding an AudioStreamPlayer3D node to a scene leads to the debug console reporting

``Condition '!is_in_tree()` is true.  returned: Transform()``

This doesn't seem to have any impact on performance, and happens for each AudioStream3D node in the scene.

**Steps to reproduce:**
Create a 3D scene, add one or more AudioStreamPlayer3D nodes.
Add a Camera node
Enable Doppler Tracking

**Comment by CakHuri** [comment]
This doesn't happen on master ( ad47ec3952c34e2cfb64b8d65f1ed5614c73222f ).

**Comment by YannBurrett** [comment]
After further investigation in 3.1 alpha-2, I've found that you need a couple more steps.  You need a current camera and to enable Doppler Tracking.  After which, the error will appear.  I've updated the original post with these steps.

**Comment by KoBeWi** [comment]
Another step seems to be running/reloading the scene.

I tested it both in 3.0 and 3.1 and it's fixed in the latter.
