### ISSUE TITLE
Ability to improve RayShape's precision

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#23226]
**Godot version:**
955a913a1fcc7551a3e03017eb2ac8edc4ee7043

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
I noticed that precision of the RayShape in Bullet Physics is lower than in old Godot physic implementation. The difference is not big but it's noticeable (ray length is around 0.3):

_Bullet:_
![bullet](https://user-images.githubusercontent.com/6129594/47304162-18531700-d626-11e8-8c92-2a2c32893532.gif)

_Godot:_
![godot](https://user-images.githubusercontent.com/6129594/47304165-1b4e0780-d626-11e8-9c98-7a5cb8182c7c.gif)

Usecase:
Enemies in my game don't have any kind of health indicator, instead when they are taking damage they are getting smaller and smaller and near the minimal possible health the precision of the RayShape is noticeable and unfortunately sometimes I can observe problem with slopes for those little guys...
![in_game_diff](https://user-images.githubusercontent.com/6129594/47304618-674d7c00-d627-11e8-99d6-0bf77ff5a4bd.png)

Not sure if it's possible to increase precision of RayShapes in every scenario, but maybe it would be possible to give some kind of option for gamedevs to increase it? (Like I remember there is collision_margin parameter, but it can't be set below 0.04)

**Steps to reproduce:**
1. Download sample project
2. Open RayShapePrecission.tscn
3. Play with the ray with right/left arrows
4. Change physics engine and notice the difference

**Minimal reproduction project:**
[RayshapePrecissionv2.zip](https://github.com/godotengine/godot/files/2502193/RayshapePrecissionv2.zip)

**Comment by kubecz3k** [comment]
cc @AndreaCatania @reduz

**Comment by AndreaCatania** [comment]
Interesting, I'll look on it

**Comment by Calinou** [comment]
@AndreaCatania Any updates on this?

**Comment by tom-jk** [comment]
MRP in 3.2.2.stable on linux mint 18.3, GeForce GTX 750 Ti, i7-6700K @ 4x4GHz:
[fast movement video comparison (length 0m33s)](https://youtu.be/akif40-1zH8)
[slow movement video comparison (length 0m41s)](https://youtu.be/CuwaBfqCl7c)

both engines look quite similar to me.

**Comment by Calinou** [comment]
@tom-jk Thanks for making video recordings :slightly_smiling_face: Closing.
