### ISSUE TITLE
Save Scene button is able to be clicked, and save, on a newly [unsaved](*) tab.

### ISSUE THREAD

**Issue by WatIsDeze** [godotengine/godot#2322]
Save Scene button is able to be clicked, and save, on a newly [unsaved](*) tab. And Open Recent should be disabled when no recent scenes have been opened.

![screen shot 2015-07-31 at 13 30 06](https://cloud.githubusercontent.com/assets/10252874/9006518/54479816-3788-11e5-8793-78b45f478875.png)
![screen shot 2015-07-31 at 13 30 11](https://cloud.githubusercontent.com/assets/10252874/9006517/5447174c-3788-11e5-9874-08852320eace.png)

**Comment by akien-mga** [comment]
And what does it *do*? Does it save the file with name ```[unsaved].scn```?
In some editors Ctrl+S on an unsaved scene would typically redirect to "Save As..."

**Comment by akien-mga** [comment]
Tried "Save Scene" on an [unsaved] scene, and it opened the dialog for "Save Scene As.." just as I expected, so I don't see any bug.
