### ISSUE TITLE
Changes made to a Resource in a nested inspector cannot be undone

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23231]
Godot 3.1 alpha 1

Reproduction steps:

1) Open a new scene
2) Create a `MeshInstance`
3) Assign a new CubeMesh to its `mesh` property
4) Click on the property: this opens a nested inspector inside the `MeshInstance` inspector
5) Modify the `X` size of the `CubeMesh`
6) Press `Ctrl`+`Z`: notice the whole mesh resource is removed, which is not expected. I expected only the modification made in 5) to be undone.

Note: if you choose to click `Edit` instead of using the nested inspector, undoing works properly.

**Comment by bojidar-bg** [comment]
Can confirm on master.
