### ISSUE TITLE
RichTextLabel clipping ignores rotation.

### ISSUE THREAD

**Issue by Jubjub** [godotengine/godot#23233]
**Godot version:**
b77a41125847633509a2af7d2e693ebdd4c35c01 (latest master)

**Issue description:**
When the text overflows in a rotated RichTextLabel, it gets clipped to an axis-aligned rect instead of a rotated rectangle.

**Steps to reproduce:**
Create RichTextLabel with enough text that it overflows, and rotate it, or its parent.
 
![screenshot from 2018-10-22 22-36-10](https://user-images.githubusercontent.com/465818/47317890-edc78500-d64a-11e8-855a-eb8bfc7306a7.png)
#

**Comment by toger5** [comment]
It si weired how the clipping works though... seems strange, that only the bottom left corner is clipped without rotation. Clipping box might be bigger...
I did changes to clipping, so i should look at it. Didn't think about rotation back than. The issue i fixed was about rendering viewports to textures.

**Comment by Jubjub** [comment]
Thanks for taking a look.
Actually if you rotate it around you'll see that the clipping box is something like this:
![image](https://user-images.githubusercontent.com/465818/47322271-ad223880-d657-11e8-9f1e-9482aa7b0d78.png)

I tried to fix it myself but only got as far as seeing that the clipping rect is set in https://github.com/godotengine/godot/blob/master/scene/gui/control.cpp#L605 but I'm not familiar enough with the internals to know how to apply the control's rotation to that.

**Comment by toger5** [comment]
Yea i think the glScissors is the issue. As u said, somewhere in the drivers/visual server file (there are two one for gles2 and one for gles3)
Don't know if the clipping can be applied before the transform?

**Comment by Jubjub** [comment]
I was researching this last night, but as far as I can see the glScissor test is just a viewport thing that can't have transforms applied to it. One way to solve it would be to check for rotation, and then use a stencil test instead, which can be any arbitrary shape.

**Comment by KoBeWi** [comment]
Related: #20671

**Comment by KoBeWi** [comment]
Still valid in a6d4484e5

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/20671.
