### ISSUE TITLE
Segmentation fault at build time for Mono [Tool] script

### ISSUE THREAD

**Issue by spookyblackbox** [godotengine/godot#23249]
**Godot version:**

b77a411

**OS/device including version:**

Ubuntu 16.04 LTS

**Issue description:**

Segmentation fault at build time for Mono [Tool] script, producing the following error:
>ERROR: _unload_scripts_domain: Mono: Domain finalization timeout
   At: modules/mono/mono_gd/gd_mono.cpp:681.

**Steps to reproduce:**
- Build the following script
- Apply the script to a spatial in a scene
- Close the scene
- Add/remove some white space
- Recompile

```
using Godot;
using System;

[Tool]
public class CrashEditorScript : Spatial {

    public override void _Ready() {

        MultiMeshInstance multiMeshInstance = new MultiMeshInstance();
        multiMeshInstance.Multimesh = new MultiMesh();
        multiMeshInstance.Multimesh.Mesh = new PlaneMesh();

        AddChild(multiMeshInstance);
    }

}
```

**Minimal reproduction project:**
[MonoToolCrash.tar.gz](https://github.com/godotengine/godot/files/2508584/MonoToolCrash.tar.gz)

@neikeq

**Comment by neikeq** [comment]
Any error in the terminal other than the one mentioned?
