### ISSUE TITLE
look_at oscillates between 2 angles with non-uniform scale

### ISSUE THREAD

**Issue by rainbowism** [godotengine/godot#23247]
**Godot version:**
ee858d0

**OS/device including version:**
Windows 7

**Issue description:**
Using `look_at` on a node with a non-uniform scale causes it to oscillate between 2 angles.

**Steps to reproduce:**
Set a sprite's scale to (x, y) where x != y. Call `look_at` in `_process`.

**Minimal reproduction project:**
[look_at_repro.zip](https://github.com/godotengine/godot/files/2508306/look_at_repro.zip)

**Comment by Jalu1** [comment]
Just to be clear, this is a Node2D right? What did you pass for target/point?
