### ISSUE TITLE
ParallaxLayer mirroring

### ISSUE THREAD

**Issue by pantomimepony** [godotengine/godot#23243]
I can't get the ParallaxLayer mirroring property to work as it is documented.  

Setting an offset to ParallaxLayer - Motion - Mirroring creates a second version of the child texture but the image is in the same orientation - not reflected. I found a workaround by manually adding another copy of the texture and flipping it with sprite offset. Also the API documentation for ParallaxLayer is worded in such a way it implies that if either Mirroring axis is set to zero no mirroring whatsoever will take place. 

Godot V3.0.6.stable.official.8314054
Windows 10 Home V 1803 build 17134.345

Intel Pentium CPU G2030 @ 3.00GHz 3.00GHz

ASUS desktop with CM6730 motherboard with onboard GPU running Intel HD Graphics drivers

screenshot shows minimal tree to reproduce the issue.

![mirror issue](https://user-images.githubusercontent.com/44399577/47366998-b1416b00-d6d6-11e8-9731-ed435c7c501c.jpg)

**Comment by bojidar-bg** [comment]
Sounds like this is a documentation issue.

Mirroring in the case of the ParallaxLayer node means the distance over which the image is repeated ("mirrored"). Maybe it should be renamed to `repetition` instead.

**Comment by FranckRJ** [comment]
@akien-mga is the renaming of the property still something that is wanted since 4.0 is already released? I mean, do you allow breaking changes like this for 4.x or will it only be allowed once (if) 5.0 release?
