### ISSUE TITLE
 boot splash: 'jarsigner' returned with error #1

### ISSUE THREAD

**Issue by jcdfc** [godotengine/godot#23251]
**Godot version:**
stable

**OS/device including version:**
debian stable

**Issue description:**
When I change the boot splash image I'm not able to compile my code for android. I got this error:
'jarsigner' returned with error #1

**Steps to reproduce:**
Project - Project setting - Application - Boot Splash - Image- res://art/fire.png

**Comment by volzhs** [comment]
are you using `fire.png` as app icon also?
check this issue #16421 to see if it's same issue.

**Comment by jcdfc** [comment]
Thank you, that was my problem, I change my icon an I'm nore able to build my apk.
