### ISSUE TITLE
More editor window flexibility

### ISSUE THREAD

**Issue by 0azizi0** [godotengine/godot#2326]
Add the possibility to dock 2d, 3d, script and help taps separately,
so we can view them at same time, especially with the new live scene editing feature.

**Comment by mamarilmanson** [comment]
:+1:

**Comment by reduz** [comment]
not happening for now, GLES2 is too limiting to allow many things to be
rendered at the same time (editor will become slow if rendering is slow).
When Vulkan rewrite happens this might become possible.

**Comment by reduz** [comment]
kicking to 3.1, but it's low priority for now as it requires considerable work

**Comment by Anutrix** [comment]
Now that 4.0 is in master, what are the thoughts/plans about this?

**Comment by akien-mga** [comment]
Fixed in 4.0.
