### ISSUE TITLE
Crash on exported Windows 32bit .exe (Mono)

### ISSUE THREAD

**Issue by bfarisdev** [godotengine/godot#23263]
Windows 10 64bit
Godot_v3.0.6-stable_mono_win64
Mono SDK 5.12.0
C#

After exporting game as Windows 32bit .exe and opening game, it crashes after 3 seconds with no error report in console and logs. Exported 64bit version works fine.

Update: log files included
[bug.zip](https://github.com/godotengine/godot/files/2512595/bug.zip)

Maybe this is the problem? From 1540420723 mono log:

AOT: image '.mono/assemblies/mscorlib.dll.dll' not found: The system cannot find the file specified.
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/x86/mscorlib.dll.dll' not found: The system cannot find the path specified.

**Comment by akien-mga** [comment]
(Assuming Mono-related for now.)

Can you provide an example project that reproduces this issue once exported?

**Comment by farisbdev** [comment]
> I would assume this is the same as #17299. Can you could paste here the backtrace?

How do I get that?

**Comment by neikeq** [comment]
Run the game from the command line and paste the output here. IINW It should include the backtrace.

**Comment by akien-mga** [comment]
Duplicate of #17299.
