### ISSUE TITLE
Collision polygon not working in an exported game

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#23277]
**Godot version:**
v3.1.alpha.calinou.bde3e88

**OS/device including version:**
Arch Linux

**Issue description:**
3D polygon collisions don't work in the exported game.
Although everything works if we run the game inside the editor. They collide and it's all right.

**Steps to reproduce:**
Create new collision polygon and some characters with normal collisions.

**Comment by akien-mga** [comment]
Are you using export templates matching your editor commit?

**Comment by saranvdev** [comment]
Oh, I think this might be the problem. I'm not sure how to check export templates' commit, tho.

**Comment by akien-mga** [comment]
You can do `exported_game.x86_64 --version`. But basically, if you didn't install the tpz from Calinou the same day that you downloaded the editor binary, it's likely that you have outdated templates.

**Comment by timoschwarzer** [comment]
@Chaosus I think this can be closed.
