### ISSUE TITLE
Inconsistent quit notification when frame limit is off

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#2327]
Mind you this apparently only works on certain hardware, possibly low-end. 

When my 'target_fps' option is turned off, the quit notification does not always trigger. Maybe 1/3 of the time it works. It does not even enter the function because it does not give a '7' for the notification when I press the close button.

It is a medium size program and I followed this tutorial to the exact: https://github.com/okamstudio/godot/wiki/tutorial_quit  so there is little need to share code. It does not get past the conditional when it doesn't work.

I had romulox look at it and it works consistently on his computer. It is possible our hardware difference (his computer is much better) is causing the difference, but I am not certain. 
romulox_x: i took out the tree.quit line so i could click the x a bunch, and it prints every time

**Comment by reduz** [comment]
Would be fantastic to know the Operating System where this bug is going on :)

**Comment by agameraaron** [comment]
Linux Mint 64bit with XFCE

**Comment by akien-mga** [comment]
Is it still reproducible in the current master branch?

**Comment by agameraaron** [comment]
I hope so, maybe I will test this someday. The tutorial link above is gone, but this seems to be the equivalent if you want to test it sooner: http://docs.godotengine.org/en/latest/tutorials/engine/handling_quit_requests.html

**Comment by agameraaron** [comment]
No, actually I should do it with that same hardware. I'll get it set up to test with latest stable again.

**Comment by bojidar-bg** [comment]
Pretty bump, aka did you manage to test it?

**Comment by agameraaron** [comment]
Oh, it's been so long, but I'll be sure to check out that part of the code when I port the utility to 3.0! 
It should work, but I'm not certain it fully does. You see, it saves all the user files on quit (as I intended it to do) without corruption of the file ever. However I believe the queue for printing stuff gets eliminated, which is the actual issue.

**Comment by PleaseBeGentle** [comment]
It appears that this issue also extends to Windows 10 as well. This is my code for testing.
![Capture](https://user-images.githubusercontent.com/52359036/63236354-04a31d80-c203-11e9-956f-e5241dd47db2.PNG)
For me, the "Closed!" text only prints about 50% of the time.

**Comment by Anutrix** [comment]
I couldn't reproduce it on Windows 10 device with latest master.

**Comment by agameraaron** [comment]
I tested this in 3.2.2 stable with similar code to Please Be Gentle's. The notification works for Alt+F4 and clicking the close button 100% of the time for me now. I am going to close this. Thanks to aaronfranke for pointing out this was still open.
