### ISSUE TITLE
Plugins: Ability to create custom EditorSpatialGizmo

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#23271]
**Godot version:**
Godot 3.1  df3fe9d78

**OS/device including version:**
Windows 10

**Issue description:**
In Godot 3.0 was possible to create custom gizmo from GDScript plugin by override [EditorPlugin.create_spatial_gizmo](https://docs.godotengine.org/en/3.0/classes/class_editorplugin.html#class-editorplugin-create-spatial-gizmo)
In the latest Godot this functionality was removed and currently no way to create custom spatial gizmo from GDScript

**Comment by JFonS** [comment]
I need to expose the new EdtiorSpatialGizmoPlugin to GDscript. I'll do that and probably add some documentation on how to define gizmos using the new system.
