### ISSUE TITLE
Editor stops refreshing itself, after running a game inside

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#23278]
**Godot version:**
v3.1.alpha.calinou.bde3e88

**OS/device including version:**
Archlinux
GeForce 840M/PCIe/SSE2
Driver: nvidia 410.57-4

**Issue description:**
The editor becomes "cut" in half, only one half of the screen is refreshing.
This happens if we run game in the editor.
After fullscreening-leaving fullscreen it's fixed. 
![imgur-2018_10_23-19 10 58](https://user-images.githubusercontent.com/15695377/47505799-1c25aa00-d86f-11e8-9094-c454ec0adbb7.png)

**Steps to reproduce:**
1. Run the game inside editor.
2. Editor becomes half-nonrefreshed until we fullscreen it. (or leave fullscreen)

**Comment by akien-mga** [comment]
I'm never seen this issue on Linux. Can you still reproduce it in the current master branch? If so could you provide a project that reproduces the issue?

**Comment by saranvdev** [comment]
I tried, but I can't reproduce it, even on the old branch. To be closed?

**Comment by akien-mga** [comment]
Thanks for testing! Closing.
