### ISSUE TITLE
GLES2 Unimplemented WorldEnvironment Properties

### ISSUE THREAD

**Issue by triverske** [godotengine/godot#23281]
**Godot version:**
72db300

**OS/device including version:**
Windows 10 64 Bit
NVIDIA GTX 960M
Driver v416.16

**Issue description:**
WorldEnvironment has several properties that currently do not work in GLES2, but are present in-editor. 

- Tonemap
- Auto Exposure
- Screen Space Reflections
- Screen Space Ambient Occlusion
- Depth of Field Far Blur
- Depth of Field Near Blur 
- Glow
- Adjustments

**Steps to reproduce:**

- Add a WorldEnvironment node and turn on any of the listed properties while in GLES2 mode.

**Minimal reproduction project:**
[GLES2_WORLDENVIRONMENT.zip](https://github.com/godotengine/godot/files/2515593/GLES2_WORLDENVIRONMENT.zip)

**Comment by NewNodeGames** [comment]
https://github.com/godotengine/godot/issues/21809
Only works panorama/procedural sky, ambient light and fog.

**Comment by NewNodeGames** [comment]
> Also worth noting, but might be worthy of a new issue: Ambient light is not affected by the color set in the picker.

Works for me. Add a mesh instance to the scene, decrease sky contribution and move the picker for appreciate the effect.

**Comment by BastiaanOlij** [comment]
I'm not sure turning off the parameters if you're on GLES2 is a good idea. Obviously it would be good to communicate these properties aren't functional. 
However for someone who is making a game supporting both GLES3 and GLES2 because they are targeting both desktop and mobile, they may not be too happy if their settings disappear just because they are running a test on GLES2.

**Comment by triverske** [comment]
I'm sure I'm not the only one trying to support GLES2/3 at the same time so something even as simple as "GLES3 ONLY" in the tooltip would be much appreciated, though obviously something a bit more visible would be much more effective.

**Comment by OBKF** [comment]
Hmm I was going to report that glow isn't working on GLES2 :/
@reduz will Glow be re-introduced later on?
