### ISSUE TITLE
java.lang.UnsatisfiedLinkError /lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libgodot_android.so"

### ISSUE THREAD

**Issue by MelihAltintas** [godotengine/godot#23280]
OS WİN8.1

I am using  v 3.1 alpha for compiling two modules. 
One of them is : https://github.com/binogure-studio/godotandroid 
Other one : https://github.com/kloder-games/godot-admob

My compile code : 
cd godot

scons -j2 CXX=g++ CC=gcc platform=android tools=no target=debug
scons -j2 CXX=g++ CC=gcc platform=android tools=no target=release

cd platform/android/java
gradlew clean
gradlew build

Compile with success There are no error and gradle build is fine. But when the app is starting, app is stuck and not working. Please give me an advise. I did not add arm64 but this app expects "arm64 libgodot_android.so" the adb logcat result : 

`10-24 21:51:19.280 32149 32149 E AndroidRuntime: FATAL EXCEPTION: main
10-24 21:51:19.280 32149 32149 E AndroidRuntime: Process: com.melihaltintas.protectcircle, PID: 32149
10-24 21:51:19.280 32149 32149 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.melihaltintas.protectcircle-1/base.apk"],nativeLibraryDirectories=[/data/app/com.melihaltintas.protectcircle-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libgodot_android.so"
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:972)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1567)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:40)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at org.godotengine.godot.Godot.initializeGodot(Godot.java:425)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at org.godotengine.godot.Godot.onCreate(Godot.java:590)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6942)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
10-24 21:51:19.280 32149 32149 E AndroidRuntime: 	at `com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)``

the generated build.gradle: 
https://paste.ee/p/x2C7j

**Comment by akien-mga** [comment]
You should specify `android_arch=arm64v8` to build the arm64 library needed for your device. If not specified, it defaults to `armv7`.

This is how official templates are built: https://notabug.org/hp/godot-scripts/src/master/build-godot.sh#L360-L394
