### ISSUE TITLE
Editor UI is resized when window is resized

### ISSUE THREAD

**Issue by FlamyAT** [godotengine/godot#23289]
**Godot version:**  eeee471

**OS/device including version:** Ubuntu

**Issue description:**
While the script editor is open, resizing the window messes around with the layout. Picture one shows the default maximized window, picture two the maximized window after making it smaller. 
![screenshot from 2018-10-25 21-46-39](https://user-images.githubusercontent.com/8056898/47526251-80606200-d89f-11e8-905a-fee941997f07.png)
![screenshot from 2018-10-25 21-46-43](https://user-images.githubusercontent.com/8056898/47526255-81918f00-d89f-11e8-9347-4663966b5ab2.png)

**Steps to reproduce:**
Create some "broader" docks. (Save the theme for faster resetting)
Unmaximize the window.

**Comment by qarmin** [comment]
Godot should have option to lock dock size

**Comment by capnm** [comment]
> Godot should have option to lock dock size

I think the dock just should behave the same way in the editor case as it currently does with the open view.

**Comment by avencherus** [comment]
On windows I've lately been noticing that the width of the file manager dock keeps changing size when I minimize or re-open the editor.  Wondering if it might be related to this.

**Comment by groud** [comment]
Note to myself: we agreed with @reduz that splitcontainer requires an "internal" offset value. So that the real offset property would reflect the preferred (via dragging or set_offset) offset.
