### ISSUE TITLE
GDScript bug ? override function _process() still call parent function

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#23286]
**Godot version:** 3.06 and 3.1 too

**OS/device including version:** ubuntu 16 64 bit

**Issue description:** override function still call parent function, but the problem only happened if the child class attached to some object in scene.
i expect only child function _process(): called not with parent _process(): too

the log i expected 
child
child
child
child
.....

the log found
parent
child
parent
child
.....

**Steps to reproduce:**
i will including the test project

**Minimal reproduction project:**
[bug_test.zip](https://github.com/godotengine/godot/files/2516120/bug_test.zip)

**Comment by Zylann** [comment]
Known issue, but I can't find the one where it was discussed...
Basically, some special functions like `_process` are called with `call_multilevel`, which calls all versions of the function through its inheritance hierarchy... which is very confusing.

**Comment by emik** [comment]
This caught me out in my current project because it is inconsistent (and undocumented?) behaviour compared to the behaviour of manually created and overridden functions. I feel like it's definitely something that should be reopened (or at the very least warned about in the editor or in some prominent documentation).

**Comment by Faless** [comment]
Note, this is partially documented (even if in a confusing way):
https://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#referencing-functions
https://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#class-constructor

**Comment by ripperdave** [comment]
It was a bad strategic decisions for default functions. It is against override mechanism. It forces hacking. I had to introduce ignore boolean flags and condition checks to _input(event) methods in super classes.

Godot is getting mature. GDScript should do the same.
Thinking about backward compatibility: What about a compiler/editor settings that could change that to industry standard behavior? The release note could clarify this so old project could work too.

From docs:
"Remember that default functions like _init, and most notifications such as _enter_tree, _exit_tree, _process, _physics_process, etc. are called in all base classes automatically. So there is only a need to call the function explicitly when overloading them in some way."

From Reduz:
"callbacks get called at all levels, back when we had Squirrel programmers
used to forget calling the parent functions all the time for callbacks they
handled different and it was kind of a mess. "

**Comment by fian46** [comment]
well it looks like this is not a bug we can close this. my bad not read full manual and just assume based on my experience from other language. but still i think this manual need to put in some special section in manual about OOP in godot if you from another language. let say "migrating from c++ to gdscript".
