### ISSUE TITLE
SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Expected end of statement after extends

### ISSUE THREAD

**Issue by DynasoulStudio** [godotengine/godot#23293]
**Godot version:**

3.1 Custom Build 81c2ed6

**OS/device including version:**

WINDOWS 10

**Issue description:**

When exporting a windows project with a GD Script the game fails to launch with error code:

SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Expected end of statement after extends

Doesn't matter what the script contains, it will fail to run when exported as a standard windows app exe (not windows app)

**Steps to reproduce:**
Create a new project, create a node, attach a new script, don't modify the script, save and export as executable, will fail to run.

**Minimal reproduction project:**

**Comment by Ashafix** [comment]
Cannot reproduce it with 3.06, but with an compile, custom 3.1 version. Export it as _Windows Desktop (Runnable)_ gives the following error message:
`SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Expected end of statement after extends
          At: res://Node.gdc:2`
`ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:771`
`ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2118`
`ERROR: _unref: Condition ' !_p ' is true.
   At: core/dictionary.cpp:171`

**Comment by bojidar-bg** [comment]
Make sure you are using export templates for the same version. Enough has changed between 3.0 and 3.1 that the GDScript bytecode format is incompatible between the two.

**Comment by Nolic0321** [comment]
I can confirm this is an issue.  If you download the templates via the Manager in the editor you get this error however if I compile my own templates using scons my games don't spit out this error.

**Comment by bojidar-bg** [comment]
It might be good to bump the version _after_ releasing, as instead of before. That way, development versions won't be able to find export templates automatically.

**Comment by akien-mga** [comment]
> It might be good to bump the version after releasing, as instead of before. That way, development versions won't be able to find export templates automatically.

We do bump version after releasing, when we do release something :) But there's no reason to bump version at every commit in the master branch.

I think I'll just remove the mirrorlist for `3.1.alpha` so that people are forced to download the corresponding tpz from alpha1, alpha2 or calinou snapshots.

**Comment by akien-mga** [comment]
> I think I'll just remove the mirrorlist for 3.1.alpha so that people are forced to download the corresponding tpz from alpha1, alpha2 or calinou snapshots.

And done.

**Comment by TypeOverride** [comment]
> I can confirm this is an issue. If you download the templates via the Manager in the editor you get this error however if I compile my own templates using scons my games don't spit out this error.

How do you build your own template? Can you give me a step by step manual? http://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html#creating-windows-export-templates
... i dont know what this is .. but how to apply the template? 
There is no template generated .. and where to put it .. and how to config Godot so he use it?
