### ISSUE TITLE
Godot 2.1: Lib libc++_shared.so include when module android_stl is disabled

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#23308]
**Godot version:**

Godot 2.1 9b7009b

**OS/device including version:**

Xubuntu 16.04.5 LTS x64

**Issue description:**

After commit 6e62a1e, libc++_shared.so added to android/java/libs/ when compiled with module android_stl=no.

**Steps to reproduce:**
Compile android template with android_stl=no.
Final apk include libc++_shared.so.

**Comment by akien-mga** [comment]
Fixed by #23309.
