### ISSUE TITLE
Expose exported script variables in tileset editor.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#23305]
**Godot version:**
3.1 bf957a4

**Issue description:**
It's not possible to edit exported script variables in the new tileset editor.

**Steps to reproduce:**
Create a tileset, open the tileset and add a script to it with an exported variable on it.

```GDScript
tool
extends TileSet

export var test = 0
```
![example](https://user-images.githubusercontent.com/11450875/47579820-1dacac00-d91b-11e8-87c8-5ff15a040aa9.png)

**Comment by xDGameStudios** [comment]
I can confirm this!! I was actually going to use this script to add metadata to each tile from within the new TilesetEditor (for example adding terrain effects). I hope this is a bug and not "just the way it was meant to be" and gets fixed soon!

Even better would be the possibility to associate (custom) resources or even scripts per tile (autotile/simple...) within the tileset. this way properties like friction could be created as a resource (floor_ice, friction=0.5) and added to the tile with the respective graphics!

**Comment by CowThing** [comment]
This issue might not be necessary anymore. I don't know when it happened but now when you open a tileset resource it opens in the inspector as expected, including the exported variables from a script. The inspector only changes to the "TilesetEditorContext" when a tile is selected in the editor. So it's now possible to edit the exported variables, and I like it this way better, only having the editor context appear when a tile is selected.

**Comment by akien-mga** [comment]
Thanks, closing then.
