### ISSUE TITLE
GLES2 Weird issue with normal map

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#23318]
**Godot version:**
Godot 3.1 commit 970b58148f579f741934f64af437d01b985df15d

**OS/device including version:**
Windows 10 Nvidia 1060 GTX

**Issue description:**
Added a normal map to a plane, weirdness ensued:
![image](https://user-images.githubusercontent.com/1945449/47596890-7ccef700-d9d5-11e8-8c68-8fa6fe331ffd.png)

**Steps to reproduce:**
Set rendering engine to GLES2, create a scene, add a directional light, add a plane, give the plan a material, assign a normal map.

Works fine in GLES3

**Minimal reproduction project:**
[gles2_normalmap_issue.zip](https://github.com/godotengine/godot/files/2521239/gles2_normalmap_issue.zip)

**Comment by CptPotato** [comment]
Looks like a cube map issue again. I think something similar was mentioned a while ago.

**Comment by avril-gh** [comment]
this one ? https://github.com/godotengine/godot/issues/21772

**Comment by NewNodeGames** [comment]
Try to decrease roughness on material parameters.

**Comment by avril-gh** [comment]
> no that didn't make a difference.

either for me

**Comment by BastiaanOlij** [comment]
It is mipmaps, turn mipmaps off and it works fine, I think mipmaps are not being generated properly for normal maps.

**Comment by BastiaanOlij** [comment]
Looks like this has been fixed in the current master: 
![image](https://user-images.githubusercontent.com/1945449/48904061-5a83a880-eeb1-11e8-991d-c6fce3659e7c.png)
