### ISSUE TITLE
Convert To Tileset doesn't keep Collisions informations

### ISSUE THREAD

**Issue by ABelliqueux** [godotengine/godot#2331]
While following [this tutorial](http://www.gamefromscratch.com/post/2015/04/28/Godot-Engine-Tutorial-Part-8-Tilemaps.aspx), I came accross the same issue the author mentions about the TileSet converter.

If you prepare tiles with collision informations, then convert the scene to a tileset and use it in a TileMap node in a new scene, collision informations are lost.
You can check that by opening the generated xml file. Here is a [sample xml file](http://pastebin.com/LUWF1kEQ).

I've tested this feature on v1.1.stable.d3b42e41b0, on Debian Jessie, 32bits and 64 bits version, and the issue remains the same.

**Comment by Raimmaster** [comment]
I've been testing the feature out, and same, it seems the collision isn't working correctly when exporting.

**Comment by SeldonSL** [comment]
I had a problem too when the collision polygons were concave. I fixed it by setting the "Build Mode" property of the CollisionPolygon2D to "Segments" (instead of "Solids")
