### ISSUE TITLE
rand_seed() returns a signed int instead of unsigned int

### ISSUE THREAD

**Issue by rainbowism** [godotengine/godot#23329]
**Godot version:**
970b581

**OS/device including version:**
Windows 10

**Issue description:**
`rand_seed` returns an `int`, which is inconsistent with `randi` returning a `uint32_t` in GDScript and VisualScript. Should it be expected to return the same value? This would break compat if changed.

**Steps to reproduce:**
```
func _ready() -> void:
	var big_seed = 1540663598 * 12047754176567800795
	seed(big_seed)
	print("randi:\t\t", randi())
	print("rand_seed:\t", rand_seed(big_seed)[0])
```
returns
```
randi:		2656076627
rand_seed:	-1638890669
```

**Comment by ignaloidas** [comment]
This has been fixed in `master`, with `rand_seed` renamed to `rand_from_seed`
