### ISSUE TITLE
Bracket closing for auto completion

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#2332]
If you want to write a function into closed brackets () you endup with something like that if you use auto completion:
(function_name()

Would be nice if it keeps the outer bracket like that:
(function_name())

**Comment by ndee85** [comment]
In addition to this issue. If you want to get a node with get_node() and you have something like this as starting point for autocompletion:
get_node("")
Now if you type in the string into the quotes and autocomplete you will end up with that:
get_node("path_to_node"")

Would be great if the extra quote gets deleted.

**Comment by StraToN** [comment]
I agree with ndee85 for the 2nd case he described ('|' character is the current editing position)
--> initial situation : get_node("|") 
after auto-completion :
--> get_node("/path/to/node"|")
This can be simple to do, I can have a look when I have some spare time.

However, I think the 1st situation is not expectable. I'd propose an automatic addition of right bracket ')' if the fist left bracket was inserted BY THE USER, that is :
--> initial situation : (|
would automatically add the extra right bracket : 
--> (|)

But in this case, what behavior is expected when the left bracket is removed by the user in this situation ?
--> var blah = (|foo(bar).with(some, stuff)).and_some(other, stuff)
-------------------^

**Comment by akien-mga** [comment]
I don't think the first case would be an improvement, as in some cases you want to do:
```
(function1_name() + function2_name())
```
So if you use autocompletion for both functions, it would add an unneeded closing bracket after ```function1_name()```.

**Comment by vnen** [comment]
I agree with @StraToN: it should complete the closing bracket when the user adds the opening one, not when the function name is autocompleted.

**Comment by StraToN** [comment]
In following examples, '|' character is cursor position.

@akien-mga 
The insertion of a left-bracket '(' should provoke the insertion of a right-bracket ')' only if there is no character right after the '(':
ie: function1_name| + '(' ==> function1_name(|)
and: |function1_name() + '(' ==> (|function1_name()

Automatically adding surrounding brackets around an aleady-existing expression should not be possible that way. One should have to add both left and right brackets by hand then.

**Comment by vnen** [comment]
Is it though? I enabled it and didn't make any difference.
