### ISSUE TITLE
Autocompletion can fail to work

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#2333]
For some objects auto completion does not work sometimes. Would be great if autocompletion would work for all referenced objects.

**Comment by BBric** [comment]
Some additional requests:
- The autocompletion should be case insensitive (example: the types TYPE_*) and should accept characters in disorder (example: int for TYPE_INT).
- The end key should not be used for navigation.
- The tooltip is too near of the text and should notably disappear when a scene is played.

**Comment by akien-mga** [comment]
Do you have an example of object for which it does not work properly?

**Comment by reduz** [comment]
This has improved a lot in the recent monrhs, I think all possible cases of objects are working now. As such, closing unless something else is reported
