### ISSUE TITLE
Auto-scroll gdscript editor when creating new lines at bottom of view

### ISSUE THREAD

**Issue by e-e** [godotengine/godot#23333]
**Godot version:**

v3.0.6.stable.official.8314054

**OS/device including version:**

Windows 10, version 1803, OS build 17134.345

**Issue description:**

When using the gdscript editor, when creating a newline that extends beyond the current scroll view, the editor does not auto-scroll, and thus the new line is not visible.
![godot](https://user-images.githubusercontent.com/5191838/47608728-0dfa9980-d9e7-11e8-82fa-5ccad2e126b1.png)

For example, see the above screenshot: Line number 44 is not fully visible, and you need to manually scroll to see that line.

**Steps to reproduce:**
  - in the gdscript editor, add enough new lines until you reach the bottom of the view
  - see the newest line is not visible

**Minimal reproduction project:**

empty project will suffice. just open the script editor

**Comment by e-e** [comment]
I would be willing to look into this if someone who is more familiar with the code base can point me in the right direction.

**Comment by lupoDharkael** [comment]
If you want to give it a try, you can find the code editor in the `editor` folder. Here is the code where the setting I mentioned before is applied:
https://github.com/godotengine/godot/blob/5536e7a8d4c82b39f85c9df52ee6a68dbf7aa0f2/editor/code_editor.cpp#L767 

It is applied in the variable `text_editor` which is a `TextEdit`. You can find the class here: https://github.com/godotengine/godot/blob/5536e7a8d4c82b39f85c9df52ee6a68dbf7aa0f2/scene/gui/text_edit.cpp

**Comment by KoBeWi** [comment]
This works ok since 3.1 and was improved in 3.2
