### ISSUE TITLE
Bug with variables. Some only work when copied

### ISSUE THREAD

**Issue by TheSymbolSystem** [godotengine/godot#23338]
**Godot version:** Godot Game Engine 3.0

**Issue description:** I had to copy the variable ‘sprite_half_width’ from the Game script to the Platform script. I wrote it correctly the first time, but it didn’t accept it. 

**Steps to reproduce:** Copy the following scripts:
[Game](https://github.com/guilhermehto/platform-jump/blob/bff9b52556fff1d2c4de17fd61aa88b88224c381/scripts/Game.gd)
[Platform](https://github.com/guilhermehto/platform-jump/blob/bff9b52556fff1d2c4de17fd61aa88b88224c381/scripts/NormalPlatform.gd)
[Player](https://github.com/guilhermehto/platform-jump/blob/bff9b52556fff1d2c4de17fd61aa88b88224c381/scripts/Player.gd)

You will likely need to have sprites.

There will be an error about the variable 'sprite_half_width'. The only way to solve this to directly copy the variable from the Game script to the Platform script. Attempting to just write it out makes an unplayable game. I consider this a bug because it took me over a week to figure the problem out and I don't find this happens when I write out variables that are already in a script.

**Minimal reproduction project:**

**Comment by swarnimarun** [comment]
You are trying to add a property to a script from another script? 
If the platform doesn't have the variable how is it supposed to fetch it?

Sorry if I am not able to understand something.

**Comment by avril-gh** [comment]
@TheSymbolSystem
variables are local to script where they are defined.
to access them from another script you must provide location where they are.
`get_node("node_where_your_variable_is_defined").your_variable`

**Comment by akien-mga** [comment]
Please use [other community platforms](https://godotengine.org/community) for support (e.g. Q&A, Discord, Forum, etc.), this issue tracker is strictly for engine bugs.

You are welcome to open an issue if you're fairly confident that it's an engine bug, but if so please provide a minimal example that reproduces the issue consistently, we can't take time to debug every user's personal game to find potential bugs.

**Comment by TheSymbolSystem** [comment]
> @TheSymbolSystem
> variables are local to script where they are defined.
> to access them from another script you must provide location where they are.
> `get_node("node_where_your_variable_is_defined").your_variable`

Thanks, but I already found the bug. I had to specifically copy a variable from one script to another one. I wrote it in the other script and that's why the game didn't work.
