### ISSUE TITLE
Animation timeline advances a step when keyframing from the inspector.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#23330]
Win10 64-bit commit: 8d75ea755cb933a5c4a0f9ec296e8b8c34ef9999

When clicking a keyframe in the inspector, it will step the time line forward.  There was some work on the past done on this, but the advancing I believe is intended only for advancing "frame" properties on Sprites and AnimatedSprites, etc.

The commit that causes this is:  5f2f1089086ad64636efc2a4096e55e4483c927a
A related commit is: 127940bd55751fa33394da2f9536c63bffe18398

I missed it earlier, since I mostly work from the toolbar keyframes, which are not affected, but found it today keyframing less common properties in the inspector.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/47608177-60ad7300-da32-11e8-979b-3395a4edb166.gif)

@DualMatrix I think these two things need to be combined in some way.  A condition to only advance steps when keyframing "frame" properties.  Advancing the timeline on the other types makes things very difficult, as you might have to keep dragging back the time slider when changing and rekeying multiple tracks with keyframes on the same time position.

**Comment by DualMatrix** [comment]
I don't really see why it would be preferable for it to only advance when animating frame properties. Could you explain why it's useful to advance for frame properties but not for others?

**Comment by bojidar-bg** [comment]
It is useful when editing frame properties, since manually moving the time marker would change the frame back to its keyframed (unincremented) value.

**Comment by avencherus** [comment]
Sure, I think there is only one, but it is very time saving.

It's useful for quickly keyframing spritesheets with a lot of frames.  Assuming the spritesheet frames go in order, a user can can pick the starting frame of an animation in the sprite frame property in the inspector.  Choose the animation, the starting time, and then just rapidly click the keyframe button without leaving the inspector.  

This will get all the frames of the spritesheet keyframed in a matter of a second or less.  Say someone has 12 frames for running animation, that's just 12 clicks in a row and they'd be done and have every frame from 0 to 11 keyframed at the time step of the animation.

For all the other properties it is trouble, and I reasonably sure this is why it was given the special + icon and its own type.

Without it, the same process starts by keyframing the first sprite frame, advance the timeline manually by one step, then go back to the inspector, bump the value up by one, keyframe again.  Repeat this several to a dozen times.

It can take much much longer, and it is easier to mess it up.

**Comment by avencherus** [comment]
In the old GIF I had, you can at least see the effect of clicking the frame property to get a fast result, though the image shows it at the point where the frame number wasn't bumping up.

![46263014-3e4b3700-c512-11e8-80eb-05aef90e33c7](https://user-images.githubusercontent.com/13004169/47788371-330a4780-dd1a-11e8-9917-c394c85b95b0.gif)

So four clicks and it should give 4 frames like 0 1 2 3 or if it was started at 5 it would go 5 6 7 8.

**Comment by DualMatrix** [comment]
Makes sense, I'll look in to fixing this as soon as I've got time

**Comment by avencherus** [comment]
Cool, thanks man.  I'll keep an eye out for it.
