### ISSUE TITLE
Allow moving Tilemap nodes by dragging

### ISSUE THREAD

**Issue by prateekamana** [godotengine/godot#23343]
**Godot version:**

Godot 3.0.6

**OS/device including version:**

**Issue description:**

I can't use the GUI to change the position of a tilemap node, I have to manually do it by changing the numbers. Please add that feature, it just keeps drawing tiles when I want to move it.

**Steps to reproduce:**
Create a tilemap
Try to change its position by the GUI move tool.

**Minimal reproduction project:**

**Comment by swarnimarun** [comment]
I think it's better this way cause changing the position of TileMap can cause problems if you are using multiple tilemaps, so it stops anyone from messing with it.
I don't see a reason so as to why there should be any need for it.

**Comment by NewNodeGames** [comment]
You can use the GUI. Move the cursor to a number, then Ctrl and mouse left click and move left and right instead of typing numbers.

**Comment by bojidar-bg** [comment]
I think allowing movement of the tilemap (and perhaps hiding the grid and to-be-placed tile) when the move tool is selected might be a useful addition.
Same for the rotate and maybe scale tools.
