### ISSUE TITLE
Godot doesn't allow me to increment a key value

### ISSUE THREAD

**Issue by NoodleSushi** [godotengine/godot#23342]
![capture](https://user-images.githubusercontent.com/34954180/47611327-19b68200-da20-11e8-9159-a13a7829065a.PNG)

**Comment by Naryosha** [comment]
Assuming track.notes.size() = 64, index[6] = 63, i = 6
```
37: index[i] += 1
-------- index[6] = 64
34: while pos >= track.notes[index[i]].time and index[i] < track.notes.size():
-------- while pos >= track.notes[64].time and 64 < 64:
                      ^~~~~~~~~~~~~~~ index error
```
Breaking out of the while loop before the next iteration should work.

**Comment by NoodleSushi** [comment]
Thank you so much @Naryosha for the advice, it works! now closing this issue ^_^
