### ISSUE TITLE
Request: possibility that Particles2D/Particles can emit scene

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#2334]
I think about:
- particle with collision
- with behaviors
- particles emitting particles node (fireworks!!)

and many more.

**Comment by reduz** [comment]
you can use as a texture a render target

**Comment by puppetmaster-** [comment]
How do i get the render targets? get_children()?

**Comment by puppetmaster-** [comment]
@reduz Can you give us some hint how we can archive this? I'll expand than the particle demo with the new one.

**Comment by GlaDOSik** [comment]
You can render a scene to render target (take a look at viewports properties) and use that rt as a particle texture. You could make a firework with this system. But I don't think you could make particles with collisions this way.
