### ISSUE TITLE
Clicking on root node icon in the main viewport crashes the editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23359]
Godot 3.1 alpha 1
Windows 10 64 bits
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

Reproduction:
1) Open the editor on a new empty scene
2) In the scene tree panel, choose "Custom node", and create an `AudioStreamPlayer3D`, or a `Camera` node.
3) The node will appear selected. Click elsewhere in the main viewport to deselect it.
4) Click on the icon of the node to select it again: Godot crashes

I tried running Godot from command line but the log didn't say anything.

**Comment by qarmin** [comment]
Can't reproduce with Linux Mint 19 aeddb30

https://streamable.com/x86hg

**Comment by bojidar-bg** [comment]
Can reproduce on alpha 1, but not on master, I guess it was fixed?

**Comment by Zylann** [comment]
Can't reproduce in master either.

**Comment by Zylann** [comment]
Ew. I'll see if I can get it at this commit

**Comment by Zylann** [comment]
I can't reproduce it either with both `debug` and `release_debug` configurations. I built with MSVC though.
