### ISSUE TITLE
Problems with exported geometry in gltf format (pc reception desk model)

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot#23356]
**Godot version:**
Godot 3.0.6

**OS/device including version:**
Windows 10/Acer Aspire E 15

**Issue description:**
Let's take a look at this PC model (.blend file):
[pc_reception.zip](https://github.com/godotengine/godot/files/2522930/pc_reception.zip)
Now let's export it into GLTF format using https://github.com/KhronosGroup/glTF-Blender-Exporter
[pc_reception_gltf.zip](https://github.com/godotengine/godot/files/2522933/pc_reception_gltf.zip)
When viewing this model online via https://gltf-viewer.donmccurdy.com/ is looks okay:
![image](https://user-images.githubusercontent.com/7196697/47618596-38d81100-daff-11e8-9d85-45a719e9c5e4.png)
But when exported to Godot, the result is very strange:
![image](https://user-images.githubusercontent.com/7196697/47618634-8bb1c880-daff-11e8-9dda-be204ed64a7b.png)

**Comment by fire** [comment]
Using apply transforms, I was able to get it to import. I also set the units to cm and baked transforms.

\<DichotomyMatt>

You can apply scale and rotation before you export the model. Just click Ctrl-A in object mode. I hope this is what you are asking for.

https://blenderartists.org/t/bake-transform-into-vertices/411086

This is 2.8 blender file.
[pc_reception.zip](https://github.com/godotengine/godot/files/2523242/pc_reception.zip)

Converted as fbx and glb (gltf).
[issue.zip](https://github.com/godotengine/godot/files/2523245/issue.zip)

**Comment by fire** [comment]
![godot windows opt tools 64_2018-10-28_14-30-34](https://user-images.githubusercontent.com/32321/47622092-0fe35c00-dabe-11e8-9816-cec52bb52cc1.png)

**Comment by fire** [comment]
The normals are also flipped, I can change the cull mode, but that's not the correct way.

**Comment by dodgyville** [comment]
If you're not wedded to gltf, perhaps try the blender-to-godot exporter:
https://github.com/godotengine/godot-blender-exporter

**Comment by Antokolos** [comment]
@dodgyville , yeah, we will probably do this, thanks.
As a matter of fact, we have all possible model formats in our project. We start with dae, because it is oldest and most stable. If we encounter any problems with dae, we are trying to use gltf or escn.
We enjoy using Godot, but all this mess with model conversion is really REALLY frustrating :(
I'm trying to share such problem models with the community, because I believe that this can help the developers to fix the bugs in the converters and/or in the Godot :)

**Comment by Antokolos** [comment]
@fire , thanks for your help, too!
My idea was: if something is looking OK in Blender, then it should be easily exported to Godot.
Hopefully, something can be done on the Godot side too, to improve this...
