### ISSUE TITLE
bug performance 

### ISSUE THREAD

**Issue by AttSee** [godotengine/godot#23357]
![untitled](https://user-images.githubusercontent.com/22094152/47618931-5e562200-dae1-11e8-9b18-2e301b06b4f9.png)

Do not say be specific
The problem exists

ignore me

But this is a fact

If you do not want to use HEX
ok Give me a good solution
Do not say use c++
It's a stupid solution

**Comment by groud** [comment]
This is not a bug, GDscript is a interpretated language, so it is slower than other ones which are compiled. So this is expected. 

Each language available in Godot has it advantages and drawbacks. GDscript is easy to use and portable, while C# is a little bit harder to master but more efficient. C++/gdnative has the best performances but must compiled per platform. 

Note that GDscript might get some performance improvements with typed instructions, but this has been discussed in other issues. 

Please document yourself before opening other issues, the documentation contains already all the information I gave you.

**Comment by NewNodeGames** [comment]
Lol, you are funny man!

**Comment by mysticfall** [comment]
Having seen such a misguided notion of binding language performance so often, I came to believe that it'd be worthwhile to add a dedicated section in the official documentation to dispell the myth.

It's so easy to assume it'd be a big trouble if a binding language A performs sever times slower than another language B, so probably we should let people know why it wouldn't translate to any meaningful FPS difference in most cases (and maybe such exceptional cases when it actually does).

**Comment by akien-mga** [comment]
@AttSee Please behave, next "irony" joke like that and I block you from opening issues on this repository. We're doing actual work here...
