### ISSUE TITLE
Solutions to performance problems

### ISSUE THREAD

**Issue by AttSee** [godotengine/godot#23350]
If you want performance, use c ++
This is the  not  good solution 
We are here because Godot is easy to use

c # is not a solution

I think the solution would be
support  GDScript for Games do not require performance (easy way)

And  add haxe language  for Games do require performance (godot Monster way)

You want a tried solution
armory3d Engine Games Using Haxe    

What is your opinion
I think the performance problem must be solved

**Comment by NewNodeGames** [comment]
> You want a tried solution
> armory3d Engine Games Using Haxe

What games are made with armory? I don't know any. Not: the templates are not games.

**Comment by Zireael07** [comment]
Armory is still in development as much as Godot is, I wouldn't call it a tried solution.

That said, I think it is a badly worded request to have Godot support Haxe?

**Comment by AttSee** [comment]
Armory It has been tested Haxe  good for now
haxe was made by game devs  
haxe compiler c++ 
 the best performance is c ++
I think Easy solution Using Haxe
C#  Sharp is not like that

I do not use the HaXe
I do not ads

**Comment by eon-s** [comment]
Is this an issue or a question?
Also if you have a performance problem, be specific because those things cannot be solved in a generic way.

**Comment by NewNodeGames** [comment]
Lol, Haxe is the most similar to C++ or C# but those languages are not a good solution for you. This is surreal xD

**Comment by NewNodeGames** [comment]
What is your performance issue? Can be more related with graphics and you are confusing, like many others different terms?

**Comment by groud** [comment]
If you have a specific issue, please fill the issue template. We don't know what performance problem you are talking about.

If this is a question, this is not the place to ask for questions. Please use the other community channels for that.

**Comment by AttSee** [comment]
> Lol, Haxe is the most similar to C++ or C# but those languages are not a good solution for you. This is surreal xD

I mean Anyone who hears about GDScript before using godot
but GDScript is Able to build

**Comment by akien-mga** [comment]
You can already build an open world. Attempt it, once you have actual performance road blocks, we can discuss.
