### ISSUE TITLE
Impossible to resize elements in Editor - console reports Edit CanvasItem

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#2335]
I have difficulties to reproduce, but when working with GraphNodes, at a certain moment it is impossible to edit any element of the scene.
A left mouse click anywhere (even in the void) in the 2D editor has no effect on selection/deselection. Output shows only "Edit CanvasItem" when clicking anywhere.
However, moving the last selected element is possible.
Handles at every corner and side of the element are not shown.
Modifying properties of elements work if they are selected from the Scene Tree.

**Comment by volzhs** [comment]
I guess you pressed 'w' key at some point.
You can only move last selected element on the scene with ``Move mode``.

You can change to ``Selection mode`` with 'q' key.

Watch carefully toolbar when this happen.

**Comment by akien-mga** [comment]
Archiving as per the above comment that seems to point out it would be a pebkac ;) Feel free to reopen though if the "inadvertent Move mode selection" is not the correct explanation.
