### ISSUE TITLE
Add a Conda environment so contributing becomes easier for newcomers

### ISSUE THREAD

**Issue by gcardozo123** [godotengine/godot#23363]
**Motivation**

When a newcomer decides to start contributing with Godot, instead of start studying the Godot's source code, he/she needs to first learn about some dependencies such as `scons`, `clang-format` and `Pywin32`, then manually install one by one, taking care to pick the correct version.
If we had a Conda environment file, all that the newcomer would need to do would be: 
* Install Python 3
* Install Miniconda 3
* Run `conda env create -f environment.yml`
* If we ever need to include other dependencies, the contributor will only need to run `conda env update`
* Activate the environment

**Advantages** 
It's easier for newcomers, prevents from messing with your root Python instalation, prevents from installing the wrong version, offers reliable community driven channels such as [Conda-Forge](https://conda-forge.org/).

**Disadvantages**
I don't see any, all contributors can keep their workflow and life would be a little easier for newcomers. ;)

I'll prepare a PR with the `environment.yml` so anyone can test it.

**Comment by Calinou** [comment]
Installing development dependencies is really easy on Windows thanks to [Scoop](https://scoop.sh/). After installing it, you can just type the following command and you can build Godot right away:

```text
scoop install python scons gcc yasm
```

Also, in my testing, pywin32 isn't required anymore. The documentation should be updated to reflect this — I have a PR ready to submit for this, but it's blocked by [this issue](https://github.com/godotengine/godot/issues/21418).

**Comment by gcardozo123** [comment]
> Installing development dependencies is really easy on Windows thanks to [Scoop](https://scoop.sh/). After installing it, you can just type the following command and you can build Godot right away:
> 
> ```
> scoop install python scons gcc yasm
> ```
> Also, in my testing, pywin32 isn't required anymore. The documentation should be updated to reflect this — I have a PR ready to submit for this, but it's blocked by [this issue](https://github.com/godotengine/godot/issues/21418).

If I want to contribute with multiple projects that may use some of the same dependencies, but with different versions, can I use Scoop to setup multiple environments?

**Comment by Calinou** [comment]
The above command doesn't install any packages from pip, so it should be fine to run as-is. SCons 3.0 and later can run on both Python 2.7 and 3.5+ (and the Python code in Godot works with both versions too).

**Comment by asheraryam** [comment]
> 
> 
> Installing development dependencies on Windows is easy thanks to [Scoop](https://scoop.sh/). After installing it, you can just enter the following command then build Godot right away:
> 
> ```
> scoop install python scons gcc yasm
> ```
> 
> `clang-format` can be installed using this command:
> 
> ```
> scoop install llvm
> ```
> 
> Also, in my testing, pywin32 isn't required anymore. The documentation should be updated to reflect this — I have a PR ready to be submitted, but it's blocked by [this issue](https://github.com/godotengine/godot/issues/21418).

Apologies for bumping an older thread, but I think build dependency management with scoop should be documented somewhere to make it more accessible, since it seems very useful (I didn't know about it before but I just tried it and building godot right now).

**Comment by akien-mga** [comment]
Closing as per https://github.com/godotengine/godot/pull/23365#issuecomment-452052754, I don't see much use for such addition for the time-being.

I'm open to reconsider eventually if there's a real value addition, but right now it just seems to add dependency on a given dependency manager to solve quite trivial dependencies.
