### ISSUE TITLE
Concave CollisionPolygon2D is split with gaps

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#2336]
![bug](https://cloud.githubusercontent.com/assets/10054853/9083799/e47a8a7c-3b9f-11e5-8c7e-5fbfa9bffd69.gif)
![bug](https://cloud.githubusercontent.com/assets/10054853/9083824/10f2fabc-3ba0-11e5-9bb1-12876597ea13.gif)

the shape will be split,but some time it will generate a gap and other collision shapes will not collide with this gap.

**Comment by reduz** [comment]
I finally got this to work, it seems the decomposer is not that good

**Comment by reduz** [comment]
er, I mean, to reproduce
