### ISSUE TITLE
File system dock scroll itself when I drag the file

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23375]
**Godot version:**
3.1 aeddb30

**OS/device including version:**
Windows 10

**Issue description:**
When I try to drag and drop file to 2d viewport then  filesystem dock scroll itself when I with dragged object are above this panel. This is very frustrating because I must again and again scroll down 

**Steps to reproduce:**
https://streamable.com/1lqd3

**Comment by Xrayez** [comment]
This is indeed annoying, I guess the new docks layout design has revealed this usability bug! I wonder where to fix this.

**Comment by groud** [comment]
> I wonder where to fix this.

I already did a PR for that:  #24654, but as it is minor compatibility breakage it will have to wait at least 3.2.

**Comment by Xrayez** [comment]
Ooh somehow I missed that, thanks!
