### ISSUE TITLE
Wrong position of dragged sprite when parent has non default scale.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23373]
**Godot version:**
3.1 aeddb30

**OS/device including version:**
Windows 10

**Issue description:**
When I drag & drop a sprite to main viewport, when parent of pasting sprite has scale different than (1,1), then pasted sprite has strange position. 

**Steps to reproduce:**
https://streamable.com/fpzge

**Comment by akien-mga** [comment]
CC @groud
