### ISSUE TITLE
Add ability to show in File System dock non-supported file type

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23372]
**Godot version:**
3.1 master

**OS/device including version:**
Windows 10

**Issue description:**
Godot should have an option to show files with non-supported file type, of course not by default, for example .kra, .odt etc.
Should be prepared special icon which will easily show to user which file type are not supported by engine.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/677, as feature proposals are now tracked on the Godot proposals repository.
