### ISSUE TITLE
ThreadedProgressDialog

### ISSUE THREAD

**Issue by fire** [godotengine/godot#23391]
**Godot version:**
master

**Issue description:**

Create a threaded progress dialog with 2 modes / 4 combinations.

1. Blocking or not blocking. Prevents the editor from being used but doesn't stop ui.
2. Background or foreground. Display in the middle of the screen or as a progress bar on the top right corner. 

@neikeq Design review?

\<neikeq> yes, i want it to block in this case

\<neikeq> reduz: what's the use of BackgroundProgress if it does not block? how is it displayed in the UI?

\<reduz> i think on the top right region a small progress is displayed

\<reduz> its for background processes, Filesystem Scan uses it

\<reduz> not very useful in general, though

\<reduz> i guess what you want is a ProgressDialog that does not block and can be used from a thread

\<reduz> maybe ThreadedProgressDialog

**Comment by neikeq** [comment]
> 2. Background or foreground. Display in the middle of the screen or as a progress bar on the top right corner. 

We already have `BackgroundProgress` for a background progress dialog that doesn't block the main thread. What's the point of one that blocks the main thread?

**Comment by fire** [comment]
Example case: converting a scene to one mesh instance.

1. Want to make the developer not be able to modify the scene
2. Want to make it not block the main thread
3. Want to make it background so that the developer can see the editor 3d window but not actually edit
4. Alternatively make it background and allow the developer to edit the scene and when the system is done replace the scene. (I have an implementation of this), but it modifies a label to display progress rather than a dialog.

**Comment by fire** [comment]
I don't see a BackgroundProgress in the latest docs on https://godot.readthedocs.io/en/latest/index.html

**Comment by fire** [comment]
Design 2

A exclusive dialog ("prevents the editor from being used"):

* do not block the main thread
* blocks user input
* Show ui in the middle of the screen.

A non-exclusive dialog ("does not prevent the editor from being used"):

* do not block the main thread
* does not block user input
* Show the same ui as BackgroundProgress as a small progress dialog in a corner

The desired implementation will take the non-exclusive dialog and make it exclusive.

**Comment by fire** [comment]
To allow threaded asset import, every instance of ProgressDialog should be replaced by the exclusive progress dialog that doesn't block the main thread.

**Comment by Calinou** [comment]
What's the status on this now that #36640 was merged?

**Comment by fire** [comment]
I have not looked into this. Feel free to take this task.

**Comment by fire** [comment]
I have forgotten about issue. I think a new issue should be opening in the proposals for it.

**Comment by akien-mga** [comment]
I think this can be considered implemented by #36640.

**Comment by neikeq** [comment]
@akien-mga This is about the progress dialog, not resource loading. I don't see the relation between with that PR, unless I'm missing something.

**Comment by akien-mga** [comment]
Then this should be moved to a proposal on https://github.com/godotengine/godot-proposals, which can now use the threaded resource loader for a proposed implementation.
