### ISSUE TITLE
Rotating 2D lights still doesn't work with normal maps?

### ISSUE THREAD

**Issue by thorlucas** [godotengine/godot#23394]
I have the same bug as #3772. According to [#19807](https://github.com/godotengine/godot/pull/19807) this is fixed. However, I'm using the latest stable release and this bug is still occurring. 

![giphy](https://user-images.githubusercontent.com/25698466/47693188-ec9bd800-dbb5-11e8-892b-6f2c03b1d8c8.gif)

**Comment by Zireael07** [comment]
Are you on GLES3 or GLES2?

**Comment by groud** [comment]
Well yeah, this was fixed on master branch, and not integrated into a stable release yet. Its normal it is not fixed on last stable.
