### ISSUE TITLE
Cursor bug while using Animation2D

### ISSUE THREAD

**Issue by prateekamana** [godotengine/godot#23398]
**Godot version:**

Godot 3.0.6

**OS/device including version:**

OS : Windows and linux 

**Issue description:**

When using working with sprites in the AnimatedSprite node, the cursor disappears in the linux version and it freezes at the middle of the screen in the windows version.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
@prateekamana Can you still reproduce it in 3.2.x? If yes, please provide more detailed steps.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
