### ISSUE TITLE
Consistent FPS drops in 2D

### ISSUE THREAD

**Issue by marcJV** [godotengine/godot#23408]
**Godot version:**
v3.1.alpha.official
Also happened in 3.0.5

**OS/device including version:**
macOS Mojave Version 10.14
OpenGL ES 3.0 Renderer: AMD Radeon Pro 560 OpenGL Engine

**Issue description:**
Seemingly consistent framedrop from 60fps to ~30fps.

Video of it in action:
[Screen Recording 2018-10-30 at 1.31.05 PM.mov.zip](https://github.com/godotengine/godot/files/2531114/Screen.Recording.2018-10-30.at.1.31.05.PM.mov.zip)

**Steps to reproduce:**
Open a new project, add a Node2D as the root. Add a label to the Node2D, update label in `_process` with the current FPS.
`$Label.text = "FPS: %f" % Engine.get_frames_per_second()`

**Minimal reproduction project:**
[somefpstester.zip](https://github.com/godotengine/godot/files/2531109/somefpstester.zip)

**Comment by Zireael07** [comment]
Is VSync in Godot set to on? What about your drivers? Do they force vsync too?

**Comment by marcJV** [comment]
VSync is on in Godot. I don't think that macOS is forcing VSync either, there are no options to turn it off or on by default at least. When I turn off Godot's VSync the FPS moves between 60 and 120fps. It did drop for a second to 40 once, but it was not consistent.

**Comment by Calzzetta** [comment]
Hi @marcJV, I downloaded your project and for me the performance was good enough. The FPS was not full time at 60 but was never lower than 56. I am on Windows with NVIDIA 1060. How long should I wait to see this framedrop?

**Comment by akien-mga** [comment]
Might be related to the weird regressions in OpenGL drivers on Mojave.

**Comment by qarmin** [comment]
On slow Intel HD 3000 on Linux Mint 19, I have almost stable 60fps (59-62fps) all the time.

**Comment by akien-mga** [comment]
So it was a bug in Mojave 10.14?

**Comment by marcJV** [comment]
It seems like it. I still get dips in my fps at those same intervals, but only down to 58 and back up to 60 again, so it isn't even noticeable.

**Comment by akien-mga** [comment]
Thanks, closing for now then.
