### ISSUE TITLE
"Attach script" does not work when a shader editor is open

### ISSUE THREAD

**Issue by Windfisch** [godotengine/godot#23402]
**Godot version:** 955a913a1fcc7551a3e03017eb2ac8edc4ee7043

**Issue description:**

When the shader editor is open, and in the Scene tree one right-clicks on a node, the pop up menu opens as usual. When selecting "Attach script" from there, nothing happens.

Workaround: left-click on the node in the scene tree. The shader editor will close. Now right-click and "Attach shader", and it works.

**Comment by volzhs** [comment]
I guess it's same issue with #19714

**Comment by akien-mga** [comment]
Duplicate of #19714.
