### ISSUE TITLE
Loss of export data when moving in another folder

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#23418]
**Godot version:**
3.1 custom b77a4112

**Issue description:**
While refactoring the project structure, some export variables were lost in the proces

**Steps to reproduce:**
Couldn't find a minimal reproduction case yet, seems to work fine with a small project. In the original projects the exported NodePath that were lost belonged to an inherited scene, didn't test that yet.

**Comment by KoBeWi** [comment]
This was inactive for almost two years, so should be fine to close. Please comment if you manage to reproduce consistently.
