### ISSUE TITLE
"Own World" Environment in Viewport isn't applied

### ISSUE THREAD

**Issue by antoniotorresm** [godotengine/godot#23412]
**Godot version:**
v.3.1.alpha.official

**OS/device including version:**
Arch Linux, nvidia driver, GeForce GTX 750

**Issue description:**
The Environment of `World` property (with `Own World` enabled) in Viewport isn't applied, resulting in a black scene.
![image](https://user-images.githubusercontent.com/17461846/47752548-0829e000-dc95-11e8-93bd-c66b9763dcc5.png)

Disabling the `Transparent Bg` option results in the cube not being rendered at all:
![image](https://user-images.githubusercontent.com/17461846/47752586-28f23580-dc95-11e8-8b63-fef77eb1b89d.png)

If you copy the Environment set in `World` to a WorldEnvironment node, it works nicely, both with and without `Transparent Bg`.
![image](https://user-images.githubusercontent.com/17461846/47752645-550db680-dc95-11e8-8a3c-494b2648cc4b.png)
![image](https://user-images.githubusercontent.com/17461846/47752656-5b9c2e00-dc95-11e8-8fb8-9eea3fd178a3.png)

**Steps to reproduce:**
1. Create a ViewportContainer containing a Viewport.
2. In that viewport, check `Own World` option and create a World.
3. Attach an Environment to that World (i.e. one with ProceduralSky). It won't be applied.

**Minimal reproduction project:**
The `Main.tscn` scene contains the example. There is a WorldEnvironment node outside the Viewport, you can move it inside the Viewport to see how it works correctly. You can also copy the Environment in WorldEnvironment to the World in Viewport to see how it does nothing.

[ViewportWorldEnvironment.zip](https://github.com/godotengine/godot/files/2531795/ViewportWorldEnvironment.zip)

**Comment by zEh-** [comment]
The fallback world also isn't used. Need this for separate physics mainly but was wondering why I couldn't get it to render anything.

**Comment by Kiotenhariyo** [comment]
Still no responses/solutions/suggestions to this? Having same results with "Own World".
