### ISSUE TITLE
Deserializing object from resource causes error `Invalid get index 'id' (on base: 'Reference')`

### ISSUE THREAD

**Issue by ShawnMcCool** [godotengine/godot#23410]
**Godot version:**
v3.1.alpha.calinou.bfd1f09

**OS/device including version:**
Windows, x86_64

**Issue description:**
I save an object into a resource, then load it again. Once it's loaded I get the error `Invalid get index 'id' (on base: 'Reference')`

I expect to simply have access to the property of the object.

**Steps to reproduce:**
encounter.gd
```
class_name Encounter

var id: String
var name: String
var player_resources: Array = []
var encounter_resources: Array = []
var win_conditions: Array = []
var lose_conditions: Array = []
var player_cards: Array = []
var encounter_cards: Array = []
```

encounter_data.gd
```
extends Resource

export(Array) var encounters: Array
```

encounter_data.tres
```
[gd_resource type="Resource" load_steps=2 format=2]

[ext_resource path="res://saves/encounter_data.gd" type="Script" id=1]

[resource]

script = ExtResource( 1 )
encounters = [ Object(Reference,"script":Resource( "res://encounters/encounter.gd" ),"id":"c49a0012-0d7d-4a48-bece-da59ee986fab","name":"aoeaoeaoe","player_resources":[  ],"encounter_resources":[  ],"win_conditions":[  ],"lose_conditions":[  ],"player_cards":[  ],"encounter_cards":[  ])
 ]
```

main script
```
var encounter_resource_path = "res://saves/encounter_data.tres"
var encounter_data: Resource

func load_encounters() -> void:
	encounter_data = load(encounter_resource_path)
	for encounter in encounter_data.encounters:
        print(encounter.id)
```

**Example project**
[godot-bug-example-project.tar.gz](https://github.com/godotengine/godot/files/2531590/godot-bug-example-project.tar.gz)

**Comment by williamd1k0** [comment]
I think this is some issue with Resource initialization, the built-in `_init()` method in Resource takes no positional arguments.

In this case, you can workaround this by using only keyword arguments:

```gdscript
func _init(id='', name='', player_resources: Array = [], encounter_resources: Array = [], win_conditions: Array = [], lose_conditions: Array = [], player_cards: Array = [], encounter_cards: Array = []):
	self.id = id
	self.name = name
	# [...]
```

**Comment by Zylann** [comment]
When you print encounters, do they have the `encounter.gd` script on them? Because what Godot does is to create `Reference` objects for each of them, on which it should put a script `encounter.gd`. You can test this with `print(encounter is preload("encounter.gd")`. If the script isn't detected, that means Godot sort of ignored that, which would explain why you can't get any property on deserialized encounters.

**Comment by williamd1k0** [comment]
> @Zylann If the script isn't detected, that means Godot sort of ignored that, which would explain why you can't get any property on deserialized encounters

It's failing to deserialize both `Reference` and `Resource` because of the `_init()` method.

>I wonder if serializing arbitrary classes like this was ever supported though?

Apparently (de)serializing `Reference` really works. This is being saved as follows:

```gdscript
[ext_resource path="res://encounter.gd" type="Script" id=2]
[...]
encounters = [ SubResource( 1 ), Object(Reference,"script":ExtResource( 2 ),"id":"id","name":"name","player_resources":[  ],"encounter_resources":[  ],"win_conditions":[  ],"lose_conditions":[  ],"player_cards":[  ],"encounter_cards":[  ])]
```

**Comment by ShawnMcCool** [comment]
> I think this is some issue with Resource/Reference initialization, the built-in `_init()` method in Resource/Reference takes no positional arguments.
> 
> In this case, you can workaround this by using only keyword arguments:
> 
> ```gdscript
> func _init(id='', name='', player_resources: Array = [], encounter_resources: Array = [], win_conditions: Array = [], lose_conditions: Array = [], player_cards: Array = [], encounter_cards: Array = []):
> 	self.id = id
> 	self.name = name
> 	# [...]
> ```

Yeah so, this completely resolved it. I assume the _init() method is somehow being a gatekeeper here preventing the instantiation because it required some arguments, where giving it default values prevents the issue.

I'm fine to close this issue unless you feel like solving for the init method is worthy of a future feature (would make sense to me).

I would very much prefer for the resource serialization to remain rich because this prevents me from having to write my own serialization.

**Comment by clayjohn** [comment]
Resolved. So I'm closing it.
