### ISSUE TITLE
Updating extents in a scene does not update them in the inspector.

### ISSUE THREAD

**Issue by telaviv** [godotengine/godot#23428]
**Godot version:**

v3.1.alpha.official

**Issue description:**

If i mutate a CollisionBox2D in the 2D scene, the extents in the inspector should be updated. 
![extents aren t updating](https://user-images.githubusercontent.com/192675/47836401-658d6200-dd65-11e8-94a2-ede6d8ce8069.gif)

**Comment by FlamyAT** [comment]
Can be reproduced on 13eaded

**Comment by groud** [comment]
Duplicate of #21367
