### ISSUE TITLE
An Object with a var with the same name of Singleton's var detects the Singleton's var as a type of the Object's var.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#23433]
**Godot version:**

aec8ea4f47af23e6acff181189bbbfaf7f3d18f5

**OS/device including version:**
Ubuntu 18.04 64bit

**Issue description:**

I created a singleton and I autoload it. This singleton have a var named level which is a Node2D.
Another object (main.tscn) contains a var named level and it is an int. If this object goes to use the singleton the level var of the singleton is detected as an int.
For example if I call 
`singleton.level.position = Vector2()
`
I get the error : Parser Error: Can't get index 'position' on base 'int'.

**Steps to reproduce:**

**Minimal reproduction project:**

[bug.zip](https://github.com/godotengine/godot/files/2538459/bug.zip)

**Comment by bojidar-bg** [comment]
CC @vnen.

**Comment by akien-mga** [comment]
Seems fixed in the current master branch (d0b736f).
