### ISSUE TITLE
Scaled physics bodies with offset CollisionShapes not working correctly

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#23448]
**Godot version:**
a3501c0

**OS/device including version:**
Happens on Ubuntu 18 and Windows 7

**Issue description:**
If you create a physics body, give it a collision shape and offset that shape from the physics body's origin, collision is detected in the correct location.

However, if you scale the physics body, the collision no longer works correctly (even though the debug shows where the shape should be). It seems like collision shape transform isn't correctly taken into account when the parent body is scaled.

Probably somewhat related to https://github.com/godotengine/godot/issues/15695

**Steps to reproduce:**

Load the attached project
**Note:** make sure debug collision is turned on so you can see the collision shapes!
Run the scene and you should see a cube travelling left. It will fail to collide with the first area (which has a scaled body + shape offset) but will collide fine with the second area (no scale, offset only)

**Minimal reproduction project:**
[scale_collision_bug.zip](https://github.com/godotengine/godot/files/2542165/scale_collision_bug.zip)

**Comment by sketchyfun** [comment]
Hope it's okay to tag you @AndreaCatania since you fixed the last issue related to this :)

**Comment by AndreaCatania** [comment]
Yes, you did right :)

**Comment by sketchyfun** [comment]
Just wondering if any progress was made on this? :)
