### ISSUE TITLE
Add ability to drag nodes between scenes

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23447]
**Godot version:**
3.1 0e27af2

**OS/device including version:**
Windows 10

**Issue description:**
Now is impossible to drag a node between scenes but it will be easier to reuse some nodes without creating new scenes.

I think that the best option will be allow to drag node over another scene tab and then should Godot open this scene to allow to drop desired node.

**Steps to reproduce:**
![ezgif-2-c67927e6786a](https://user-images.githubusercontent.com/41945903/47910690-ee0a2080-de93-11e8-9c8f-42901c6d9f74.gif)

**Comment by KoBeWi** [comment]
When you right-click a node, there's a "merge from scene" option (or something similar). While it's not as neat as ability to drag and drop between scenes, the functionality is already there.

**Comment by Flavelius** [comment]
This only works when the nodes are part of a saved scene, plus it has the downside of keeping the original file for sub resource location.
There are a variety of proposals for drag and drop support already, allowing cross-scene moving of nodes in the editor should be considered when tackling those.

**Comment by KoBeWi** [comment]
This will be probably solved by #34892

**Comment by KoBeWi** [comment]
Resolved by node copy-paste. Open a proposal if this is still desired.
