### ISSUE TITLE
[Solved] Dictionary erase in singleton

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#23440]
I have a dict in a singleton named "data", when I  want to erase some data in dict, I  must use
`data.dict.erase(str(id))`
instead of 
`data.dict.erase(id)`
ohterwise it will not erase anything

**Comment by Zylann** [comment]
Can you provide a full example code? Given your example it just looks like your dictionary ended up with string keys.

**Comment by firecloud888** [comment]
The code is a little bit complex, but I can show my data structure
```
new_note = [id, title, detail, ban, temp, pin, pause, freq, cycle, this_check, this_cycle, freeze_cycle, total_check, highscore, create_time]
	note_finish = true
	
	
func save_note():
	get_noteinfo()
	if note_finish:
		#save_note()
		data.note_dict[data.total_id] = new_note
		data.update_dict(data.NOTE_PATH, data.note_dict) 
		#update config
		data.total_id += 1
		data.config_dict["total_id"] = data.total_id
		data.update_dict(data.CONFIG_PATH, data.config_dict)
		#note list ui init
		get_node("/root/MainScreen/ListView").init_listview()
		return true#save and quit
	else:
		return false#not save and not quit
```
So my dict item is a list, it print like that:
(49:[49, hello world, this is test note, False, False, False, False, 3, 7, 0, 17837, 0, 0, 0, 17837]), (50:[50, sdfds, Detail(30 words)sdfs, False, False, False, False, 1, 7, 0, 17837, 0, 0, 0, 17837])

**Comment by firecloud888** [comment]
Today I found another strange error,:
I want to get data like that
`var notedata = data.note_dict[id]`

then I get the error: Invalid get index'52'(on base Dictionary)

So I print out the dictionary but it has a key "52" and the value, and I try to use `var notedata = data.note_dict[str(id)]`, but it still not works

**Comment by Zylann** [comment]
I am pretty sure your are inserting a string key in your dictionary at some point, I still can't tell given your code. Can you provide a simple example project?

**Comment by firecloud888** [comment]
> I am pretty sure your are inserting a string key in your dictionary at some point, I still can't tell given your code. For example maybe you tried to save a dictionary as JSON, but because the JSON standard cannot have number keys it saves them as strings, which you might get as such if you dont process them back.
> Can you provide a simple example project?
Thank you Zylann! You are right, in fact I really save them as a JSON:
static func load_dict(path, default):
	var _file = File.new()
	if _file.file_exists(path):
		_file.open(path, _file.READ)
		var _dict_data = parse_json(_file.get_as_text())
		_file.close()
		return _dict_data
	else:
		_file.open(path, _file.WRITE)
		_file.store_line(to_json(default))
		_file.close()
		return default
I still cant find out the second bugs reason, but I will change the data to array because the dict cant resort,
    Thank you.
