### ISSUE TITLE
macOS filesystems can be case insensitive, editor should also warn like Windows on case mismatch

### ISSUE THREAD

**Issue by thorlucas** [godotengine/godot#23441]
I found an irritating bug that took a long time to track down. I was able to make a minimal reproducible project. The project would work when launching in Godot but crash immediately when launching on the exported Mac app.

Suppose we have a script like this:

```gdscript
# res://base/Bar.gd

extends Node
```

and another file

```gdscript
# res://Foo.gd

extends 'res://Base/Bar.gd'
```

Notice the capitalization mistake? Neither did I. Godot, I guess, will ignore capitalization in directories. The project runs just fine. It throws no errors. But when exporting to Mac, it will not launch. Caused me a lot of frustration.

Suggestions for a fix: make Godot case-sensitive with directories. Or at least throw a warning when capitalization does not match.

Edit: these tests were done on macOS.

**Comment by akien-mga** [comment]
It's not Godot ignoring case, it's Windows (which is why our issue template asks you for your OS... please don't make us guess it).

> Or at least throw a warning when capitalization does not match.

It should already do that normally.

**Comment by thorlucas** [comment]
My bad @akien-mga. I’m on macOS. Which is why it’s so bizarre that this works when running within Godot but crashes the exported app.

I got no sort of warning in the Godot debugger about capitalization. It works flawlessly.

**Comment by akien-mga** [comment]
Yeah the warning was only implemented for Windows, as macOS is supposed to be case sensitive. Is your macOS partition configured to be case insensitive?

**Comment by thorlucas** [comment]
@akien-mga So bizarre! Been using macOS for many years and have never noticed that the default configuration for APFS is case-insensitive. What I don't understand is why this would then not work on the exported app.

Considering that this is the case, I think the warning should also be implemented on macOS to avoid this sort of confusion.

Thanks!

**Comment by thorlucas** [comment]
"APFS [...] is available in case-sensitive and case-insensitive variants on macOS, with case-insensitive being the default." According to Apple's developer website

**Comment by akien-mga** [comment]
Indeed, something similar to this should be implemented in `drivers/unix/file_access_unix.cpp` (but only for `#ifdef OSX_ENABLED`):
https://github.com/godotengine/godot/blob/b902a2f2a7438810cdcb053568ed5c27089b1e8a/drivers/windows/file_access_windows.cpp#L90-L110

**Comment by Kanabenki** [comment]
I implemented the warning, but I don't have a mac right now to check if it works properly. I will test on one this afternoon and make a PR if it works as intended.
