### ISSUE TITLE
Add a template with typed GDScript to "New Script" window

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23453]
**Godot version:**
3.1 Master

**Issue description:**
I think that in New Script window, should be able to choose a template with a typed GDScript e.g.

Default 
> extends Node
 Declare member variables here. Examples:
 var a = 2
 var b = "text"
 Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.
 Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

Default Typed
> extends Node
 Declare member typed variables here. Examples:
 var a : int = 2
 var b : String = "text"
 Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.
Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta : float) -> void:
	pass

This issue is related with #23454 because using Typed template won't show a warning and user not need to change all the time this templates.

![comments](https://user-images.githubusercontent.com/41945903/47918345-9cba5b00-deac-11e8-95d6-d3e5ab6b5a4f.png)

**Comment by Calinou** [comment]
Script templates now contain type hints if **Text Editor > Completion > Add Type Hints** is enabled in the Editor Settings, closing.

(#27074 is also very similar to this issue, by the way.)
