### ISSUE TITLE
Add a warning when using non-typed variable

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23454]
**Godot version:**
3.1 0e27af2

**Issue description:**
It would be very helpful for me if will be option to show warning when using non-typed variable(constant, returning value etc.), because it is better to use only one of programming style.

Of course this should be disabled by default because not everyone use typed GDScript.

**Comment by groud** [comment]
There's already an indicator of whether or not a line is safe or not. The line number goes from gray to green if a line is safe:
![safe-line](https://user-images.githubusercontent.com/6093119/47940641-95667200-deeb-11e8-9032-9a06d293c12d.png)

But I think it needs at least a tooltip to be easier to understand.

See https://godotengine.org/article/optional-typing-gdscript

**Comment by vnen** [comment]
> There's already an indicator of whether or not a line is safe or not.

Besides that, you can turn on warnings for unsafe lines in the Project Settings.

**Comment by aaronfranke** [comment]
> Besides that, you can turn on warnings for unsafe lines in the Project Settings.

This can probably be closed then, if there are already warnings you can enable in settings.

**Comment by akien-mga** [comment]
Yes it seems to cover the use case.
