### ISSUE TITLE
ItemList.item_rmb_selected and item_selected signals fire at the same time

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23465]
Godot 3.1 alpha2,
Godot 3.1 alpha1

ItemList has two signals for item selection:
- `item_selected`
- `item_rmb_selected`

I want to be able to pick up left and right mouse button selections separately to execute a different action. However, when I select with RMB, both signals get sent, which makes me unable to use that second signal... (and by extent, the whole control)

**Comment by KoBeWi** [comment]
There's a workaroud involving deferring the calls. Although it could be cumbersome.

So how this should be fixed? If we make a separate `item_lmb_selected` signal, we will either have 3 different signals or no common signal for selecting (which might make sense if you purposefully enable `enable_rmb_selection`). The other way is to include button index in the signal.

**Comment by Arunkumar1998BOM** [comment]
I will work on this. 
I need the following:
1.) Steps to reproduce
2.) Minimum Reproduction project
3.) The file/s I can refer (as I am new to this codebase).
4.) Similar fixes (which make use of the relevant APIs)

**Comment by KoBeWi** [comment]
@Arunkumar1998BOM Are you just copy-pasting the message? This one doesn't need repro/steps either, just make an ItemList and connect both `item_selected*` signals. You need another signal to differentiate between LMB click and RMB, which is what this issue is about. As for PRs, I don't remember any specific one, but you can just go to `item_list.cpp` and search for the signals, where are they emitted etc.

**Comment by Arunkumar1998BOM** [comment]
@KoBeWi 
Im sorry, By reproduce what i meant was that how can see observe my implemented changes, so as to help me debug, verify and validate the changes. I will look at the item_list.cpp and try for any changes.

**Comment by KoBeWi** [comment]
When you add the new signal properly, it should appear in the Signals tab in the inspector for ItemList. You should be able to connect it and test if works as expected.

**Comment by Arunkumar1998BOM** [comment]
@KoBeWi 
I am trying to understand the whole ItemList thing. 
I have an ItemList created with a bunch of entries. 
I think I have oberved the issue @Zylann is talking about. Ill explain:
When I do not select "Allow Rmb Sel" in the inspector for the ItemList, I find that I can select the items in my list only with lmb.
****Now, when I enable Rmb Sel, I can select with both rmb and lmb. 
The type of functionality what @Zylann is requiring that, when he enables Rmb Sel, He must be able to select only with the rmb and lmb must lie dead for him. 
This will require creating a new signal which will satisfy the above requirement.
Please correct me if I am wrong..

**Comment by Arunkumar1998BOM** [comment]
@KoBeWi 
I understood the codebase to editor functionality mapping now. Ill do one thing, Ill create a new option under the ItemList Property named "Allow Only Rmb Sel" and fill the relevant functionality (of letting only the rmb be used) in the backend code. 
Please let me know if I am missing something or going wrong anywhere .

**Comment by Arunkumar1998BOM** [comment]
@KoBeWi 
I got the issue fixed. I introduced a new option under ItemList Inspector, which is "Allow Only Rmb Sel", So the functionality for "Allow Rmb Sel" --->  Common signal for both rmb and lbm
and "Allow Only Rmb Sel" ----> Signal for only rmb 
I suggest changing the name from "Allow Rmb Sel" to something more sensible (for the case to allow both lmb and rmb). 
I also suggest we make these both options to be mutually exclusive, so as to further improve the quality
