### ISSUE TITLE
Error when opening the editor with a specific dock layout

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23467]
Godot 3.1 alpha2
Windows 10 64 bits

I am getting the following error:
```
ERROR: Signal 'confirmed' is already connected to given method '_confirmed' in that object.
   At: core/object.cpp:1463
```
When docks are configured this way in `editor_layout.cfg`:
```
dock_3="FileSystem"
dock_5="Scene,Import"
dock_6="Inspector,Node"
dock_filesystem_split=0
dock_split_2=0
dock_split_3=-32
dock_hsplit_1=0
dock_hsplit_2=75
dock_hsplit_3=-141
dock_hsplit_4=0
```
![image](https://user-images.githubusercontent.com/1311555/47946846-59daa080-df09-11e8-82b7-dabd6620882f.png)

It reproduces even with an empty project.

Call stack:
![image](https://user-images.githubusercontent.com/1311555/47946871-d53c5200-df09-11e8-9bfe-e163c0f72d65.png)
For some reason, the QuickOpen script dialog depends on docks even though it's a popup dialog Oo (also not sure why the connection is made in `ENTER_TREE`. It could be done in the constructor because it's a connection to self).

**Comment by akien-mga** [comment]
CC @groud
