### ISSUE TITLE
Shader uniform type mat4 is not a 4x4 matrixs in shader language!

### ISSUE THREAD

**Issue by D3ZAX** [godotengine/godot#23470]
Now shader uniform type mat4 is not a 4x4 matrix in shader and Inspector.

It can only pass by Transform instance in GDScript which is exactly 3x4 data type.

In inspector, it is showed to a 4x3 data type, and not refresh immediately after set.

It got "1, 0, 0, 0, 1, 0, 0, 0, 1 - 0, 0, 0" when print data got by get_shader_param() function. It has 12 (3x4) number not 16 (4x4) number!

**Comment by Chaosus** [comment]
I always wonder why Godot dont use 4x4 matrix for transform(as other engines) and 3x4 matrix for basis. I guess its some kind of design for simplicity or for decreasing memory consumption..

**Comment by Chaosus** [comment]
from IRC

> me: btw, reduz I have a question about matrix type - why transform is presented as 3x4 and not 4x4 matrix ?
> chaosus89: because you don't need the last row
> chaosus89: and having it would decrease performance unnecesarily since it will never be used

**Comment by Larpon** [comment]
How do we do a skew transformation?
```
.__.         __
|__|   -> /_/
```

**Comment by clayjohn** [comment]
Superceded by https://github.com/godotengine/godot-proposals/issues/258

There needs to be discussion about whether we add Matrix4 to GDScript.
