### ISSUE TITLE
Getting properties from scene drag-and-drop nodes in visualscript will report errors and functionality will not work

### ISSUE THREAD

**Issue by haizhou37** [godotengine/godot#23475]
**Godot version:**
godot3.0.6,.3.1alpha1 or alpha2(It's just the version I tried.)

**OS/device including version:**
manjaro gnome x64
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile
intel hd 3000
4g ram

**Issue description:**
![peek 2018-11-02 14-11](https://user-images.githubusercontent.com/33272474/47953693-0f662c00-dfbc-11e8-8e12-5a6608d96b54.gif)

**Steps to reproduce:**
Drag and drop a node in the scene into the visualscript, select a property in the pop-up window and report the error.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2545069/Test.zip)

**Comment by groud** [comment]
Are you sure you tested with 3.1 alpha 2 ? 
This bug was fixed in #22844, so maybe the result is not exactly the same in 3.1 alpha 2 ?

**Comment by haizhou37** [comment]
> Are you sure you tested with 3.1 alpha 2 ?
> This bug was fixed in #22844, so maybe the result is not exactly the same in 3.1 alpha 2 ?

voice
This is really alpha2.. Because the interface about the engine indicates only the alpha version, this is really hard to prove

**Comment by groud** [comment]
Ah but the error is not the same on alpha 2.
