### ISSUE TITLE
"Native mobile" VR not working

### ISSUE THREAD

**Issue by tcrass** [godotengine/godot#23487]
**Godot version:**
3.1.alpha.official

**OS/device including version:**
uname -a:
    Linux caladan 4.18.0-0.bpo.1-amd64 #1 SMP Debian 4.18.6-1~bpo9+1 (2018-09-13) x86_64 GNU/Linux
godot says:
    OpenGL ES 3.0 Renderer: Gallium 0.4 on AMD POLARIS11 (DRM 3.26.0 / 4.18.0-0.bpo.1-amd64, LLVM 3.9.1)

**Issue description:**
When running the attached MWP, the screen continuously turns black for a few seconds, as if Godot was trying to change video mode. Neither the output window nor the Godot editor react on clicking the "close" button of their corresponding window decoration. After killing Godot from the command line, the desktop becomes completely unresponsive -- not even restarting Xorg and/or the display manager did help; only rebooting returned the system to normal.
Edit: I haven't found a consistent pattern yet regarding Godot 3.1's problems with the Native mobile interface and Xorg. It's not always exactly the symptoms described above what I observe; rather, there seem to be variations. Sometimes it is possible to close Godot using the window close buttons, sometimes Xorg freezes seem to happen only after restarting Godot 3.1, sometimes restarting the display manager (sddm in my case) seems to initially work, but then KDE hangs on startup. Problems occur with both the GLES2 and GLES3 renderer.

**Expected behaviour:**
The project should start without any problems and show a stereoscopic rendering of the scene in a window, just like in Godot 3.0 (see attached MWP "vr_test_30.tar.gz").

**Steps to reproduce:**
Just run the attached MWP "vr_test_31.tar.gz"

**Minimal reproduction project:**
[vr_test_31.tar.gz](https://github.com/godotengine/godot/files/2545382/vr_test_31.tar.gz)
[vr_test-30.tar.gz](https://github.com/godotengine/godot/files/2545383/vr_test-30.tar.gz)

**Comment by BastiaanOlij** [comment]
Very strange, the native mobile driver just uses the screen as is, outputting each eye to their respective half of the screen with a lens shader. I haven't had any problems on the Windows side and unfortunately don't have a Linux setup atm to test. Hopefully someone else can have a closer look

**Comment by Liangdi** [comment]
i have tried with Fedora 29 and godot 3.1 custom build , runs ok
System Info:
Linux liangdis-x250 4.18.16-300.fc29.x86_64 #1 SMP Sat Oct 20 23:24:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)

**Comment by tcrass** [comment]
Hi,

I was just about to perform a custom build when I realized that the official 3.1alpha2 was out... No problems anymore here, so I suggest closing this bug.

Cheers --

Torsten

**Comment by akien-mga** [comment]
Thanks for testing!
