### ISSUE TITLE
Wrong directory when creating script and file is selected instead folder

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23480]
**Godot version:**
3.1 alpha 2

**OS/device including version:**
Linux Mint 19

**Issue description:**
When I try to click RMB at folder and click at the new script, then directory is set good, but when I do the same with file instead folder then "/" dissapear

**Steps to reproduce:**
https://streamable.com/uhhxu

**Comment by akien-mga** [comment]
Fixed by #23526.
