### ISSUE TITLE
Softbody position reported wrongly

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#23482]
**Godot version:**
Godot 3.1. alpha 2

**OS/device including version:**
Win 7 x64
Radeon 6630M

**Issue description:**
I parented the softbody to another node (that is moved during gameplay). The softbody doesn't follow the parent node regardless of whether it is set to ignore parent's collision. 
Fine, I thought, I'll just forcibly sync the position to the parent node's... except it doesn't work either, both get_global_transform().origin [that is, global] and get_translation() [local] report 0,0,0 in all cases. 0,0,0 is also displayed in the remote scene tree.

**Steps to reproduce:**
Parent a softbody node to some other node that is moved around.

**Minimal reproduction project:**

Tagging @AndreaCatania

**Comment by AndreaCatania** [comment]
Related to this: #21599

**Comment by AndreaCatania** [comment]
Fixed by #36048
