### ISSUE TITLE
Area2D doesn't update its overlapping areas when monitorable changes in the areas it's overlapping

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#23484]
**Godot version:**
3.1 alpha2 mono x64

**Issue description:**
An area that is monitoring will never detect that an area exited if the other area leaves while it is not monitorable and will remain in the list returned by get_overlapping_areas. Similarly  an area that is monitoring will never detect that an area entered if the other area enters while it is not monitorable and switches to monitorable while it's inside.
**Steps to reproduce:*
This can easily be reproduced with a static area switches between monitorable and not monitorable and another area that checks if get_overlapping_areas is empty

**Minimal reproduction project**
[Area2DProblem.zip](https://github.com/godotengine/godot/files/2545259/Area2DProblem.zip)

**Comment by akien-mga** [comment]
Might be a dupliate of #17330, can you confirm that issues happen only when toggling `monitorable` off, and toggling it on doesn't restore proper behaviour?

**Comment by MightyPrinny** [comment]
I think it could be the same bug just that the other issue doesn't mention that the list returned by get_overlapping_areas keeps the areas that are not monitorable even if the areas are not overlapping. I wanted to add more details but the way the areas go back to work correctly seems inconsistent.

**Comment by akien-mga** [comment]
Just a quick update since this issue hasn't got any comment in a while: there are currently two open PRs that aim at solve it (#32299 and #41698), but both are pending review from @reduz.
