### ISSUE TITLE
Adjacent one way collision tiles get deactivated 

### ISSUE THREAD

**Issue by Cevantime** [godotengine/godot#23491]
Godot 3.0

Linux Mint 19.0 GTX 1060 (driver 396.54)

Hi everyone, 
There seems to be an issue when a one way collision shape is attached a tile. When we drop a rigidbody vertically such as it touches two adjacent tiles with a one way collision shape, one of the two tiles gets deactivated and the rigidbody can pass through it.
What is expected is that *both* tiles are activated and rigidbody cannot pass through them. It is worth noting that the tile that gets deactivated seems to be the one that has the largest 'contact surface' with the rigibody.

To reproduce this bug, follow the [TileMap tutorial](https://docs.godotengine.org/en/latest/tutorials/2d/using_tilemaps.html) and just activate 'One Way Collision' to the collision shape that is attached to the second tile (from the left). Then, add a rigibody to the final scene and let it fall on the ground.

Here is a small project that meets this bug.

[TileMaps.zip](https://github.com/godotengine/godot/files/2545392/TileMaps.zip)

**Comment by Calinou** [comment]
Can you try with a build from the latest commit of `master` branch (or a [nightly build](https://hugo.pro/projects/godot-builds/)? One-way collision has received some fixes since the release of 3.0.6.

**Comment by Cevantime** [comment]
Hi Calinou. 
Thanks for your reply. The issue is still here. I compiled Godot (with Mono) from sources today (eb2dc22). And can reproduce it consistently. 
Here is my current project (using Mono this time). 
[TileMaps.zip](https://github.com/godotengine/godot/files/2568614/TileMaps.zip)

**Comment by akien-mga** [comment]
The issue seems still reproducible in 3.2.2 RC 2.

**Comment by Cevantime** [comment]
I  checked the code and the issue seems to come from the file `servers/physics_2d/body_pair_2d_sw.cpp` on line 295 : 
```cpp
	// if (!prev_collided) { // line 295
```
uncommenting this line (as well as the variable initialization on line 269) seems to solve the issue. I don't feel very confident in this fix because I don't quite understand why this condition has been commented but I guess I'll do a PR anyway.
