### ISSUE TITLE
Mono 3.0.6 crash upon creating C# script

### ISSUE THREAD

**Issue by cameron7b** [godotengine/godot#23493]
I could not find a similar bug labelled issue after searching

**Godot version:**
Godot 3.0.6 Mono

**OS/device including version:**
Windows 10 x64 1803
GTX 1070 and 416.34

**Issue description:**
Godot crashes creating a C# script(Generating C# Project), says not responding and closes the engine.

**Steps to reproduce:**
I switched to 2d mode and dropped the icon asset down added a script, a C# script and it closed

**Minimal reproduction project:**

**Comment by KellyThomas** [comment]
Which version of mono do you have installed?

**Comment by aaronfranke** [comment]
@cameron7b Does this occur on Godot 3.1.1 stable?

**Comment by akien-mga** [comment]
This was likely fixed as we don't get other reports of such crashes. We don't plan to release new Mono builds for 3.0.x, so you should upgrade to 3.1.2 or the soon-to-be-released 3.2.
