### ISSUE TITLE
ink-godot-example project crashes on start

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot#23497]
**Godot version:**
3.1 Alpha 2 Mono, 64-bit

**OS/device including version:**
Windows 10/Acer Aspire E 15

**Issue description:**
ink-godot-example project crashes on start. All worked fine on 3.1 Alpha 1 Mono.

**Steps to reproduce:**
1. Clone project from https://github.com/StStep/ink-godot-example
2. Open this project in Godot, hit Play
3. Game cannot be started. The following messages are displayed in the Output console:
Godot Engine v3.1.alpha.mono.official (c) 2007-2018 Juan Linietsky, Ariel Manzur & Godot Contributors.
 Signal 'confirmed' is already connected to given method '_confirmed' in that object.
Switch Scene Tab
 modules/mono/editor/csharp_project.cpp:170 - Parse error: Unexpected token: >
 Failed to determine namespace and class for script: res://ink-engine-runtime/InkList.cs
 modules/mono/editor/godotsharp_builds.cpp:404 - Condition ' metadata_err != OK ' is true. returned: false
 editor/editor_node.cpp:4421 - A Godot Engine build callback failed.

**Minimal reproduction project:**
https://github.com/StStep/ink-godot-example

**Comment by Zylann** [comment]
The first error looks similar to #23467, but probably isn't the source of the crash.

**Comment by akien-mga** [comment]
Same as https://github.com/godotengine/godot/issues/26167#issuecomment-466652943, this project is old and should be updated for Godot 3.1 compatibility.
