### ISSUE TITLE
Extra issues converting from 2.1.5 to 3.0.6

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23492]
I started converting my biggest 2.1 project to Godot 3.0 using the converter, and here the issues I had so far. I stripped out issues that I know are caused by design changes too big to be converted (like removal of SampleLibrary). Some of the issues might also be related to other bugs in 3.0 itself.

- Textures having the `repeat` flag don't carry over, their `repeat` import setting is disabled. This was a remaining problem in issue #9656 but it got closed anyways. I believe it can be fixed.

- The script conversion process renamed quoted strings, believing they were class names. This obviously break things, for example:
```gdscript
-	var audio = get_node("SamplePlayer2D")
+	var audio = get_node("AudioStreamPlayer2D")
```

- The script conversion breaks subclass inheritance by turning `extends` into `is`:
```gdscript
class Vec2 is Base:
```

- The script conversion renames some functions even if only a part of their name matches, which often breaks game logic. Example:
```gdscript
-func get_ride_speed(): # Why on Earth is it even renaming this, it's not even hard to avoid
+func get_ride_speed_scale():
 	return _ride_speed
```

- Fonts are not converted, even though Godot 2 knows where the import sources are (used to be TTFs in a folder outside the project). I heard the old `.fnt` format is not supported, but I would at least expect the TTFs to be copied inside the project and made dynamic fonts to replace them. I had to do this manually.

- My GUI theme contained embedded `ImageTextures` of the default theme, which Godot 2 inserted itself in the past. I didn't realize that, but the unexpected part is these images were completely dropped after conversion, preventing the theme from being opened at all in the editor:
```
ERROR: poll: res://menus/theme.tres:45 - Parse Error: Unexpected identifier: 'Image'.
   At: scene/resources/scene_format_text.cpp:523
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:149
ERROR: Failed loading resource: res://menus/theme.tres
   At: core/io/resource_loader.cpp:186
ERROR: load_resource: Condition ' !res.is_valid() ' is true. returned: ERR_CANT_OPEN
   At: editor/editor_node.cpp:557
```

- After getting rid of those embedded images (which didnt break the original theme in Godot 2), I was able to open the theme in Godot 3 but I noticed it got rendering inconsistencies:
![image](https://user-images.githubusercontent.com/1311555/47957856-ecd11480-dfb5-11e8-941a-8b10282862d4.png)
I found out the theme items have changed their names, but the conversion process did not update them and the inspector "blindly" shows the old ones as if they were normal. I had to recreate the theme from scratch to be sure to have the correct items.
![image](https://user-images.githubusercontent.com/1311555/48588334-9a391600-e92e-11e8-8138-a80f33831343.png)

- I am getting a huge amount of these errors, straight as the game start (they are the first printed) and I have no clue what they are about:
```
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:331
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:331
...
```
I think they come out as resources fail to load, but they are just adding 90% of noise in the 10% of valuable info (which I often have to look for in the console, because sometimes the editor just doesn't show anything).

- `Control.rect/rotation` was inverted in Godot3. My game had some rotated controls, but in Godot 3 they ended up rotated the other way around and I had to negate their angle.

- `AudioServer.get_stream_global_volume_scale()` doesn't exist anymore, but since audio stream players would default to the first audio bus, this could be converted to `db2linear(AudioServer.get_bus_volume_db(0))`.
The only tricky thing is, there was a volume for streams and another for samples, and I believe you now have to make two buses yourself since everything is a stream now. Perhaps the converter can create this extra bus to match?

- `is_ignoring_mouse()` could become `mouse_filter == Control.MOUSE_FILTER_IGNORE`

- `get_tree().is_editor_hint()` could become `Engine.editor_hint`

I'll paste other things if I discover more.

**Comment by KoBeWi** [comment]
Is this issue still important, almost two years after 3.0 and with 3.1 stable already released?

**Comment by akien-mga** [comment]
It's not high priority, but solving those items would still help people who want to port their older 2.1 projects to a more recent version.

**Comment by akien-mga** [comment]
At this point I don't plan to do further work on 2.1 myself to improve the conversion process.

Since nobody else seemed motivated to implement such changes either in two years, I'll close it.
