### ISSUE TITLE
Editor autosaves over filesystem changes when playing

### ISSUE THREAD

**Issue by fazjaxton** [godotengine/godot#2350]
If I work in an external editor, then switch back to Godot, the "Please Confirm..." files changed dialog appears.  However, it is possible to click "play" with the dialog box still open, which will cause the editor to play the project, saving all of the old versions of the files over the externally changed versions.

The "Please Confirm..." dialog should probably not allow any other interaction with the editor until the situation has been resolved.

**Comment by okamstudio** [comment]
yeah i thought this worked but it eventually broke, I think due to a PR,
thanks for reporting thought Will fix it before next version


On Sun, Aug 9, 2015 at 6:26 PM, Kevin Smith <notifications@github.com>
wrote:

> If I work in an external editor, then switch back to Godot, the "Please
> Confirm..." files changed dialog appears. However, it is possible to click
> "play" with the dialog box still open, which will cause the editor to play
> the project, saving all of the old versions of the files over the
> externally changed versions.
>
> The "Please Confirm..." dialog should probably not allow any other
> interaction with the editor until the situation has been resolved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2350>.
>



-- 

*OkamStudio*

**Comment by firefly2442** [comment]
Is there a way to force focus on a GUI element?  I looked into fixing this (in `tools/editor/plugins/script_editor_plugin.cpp`) but disabling the play buttons didn't seem like a proper fix to me.

**Comment by reduz** [comment]
This is fixed, and it can be customized in editor settings too, closing
