### ISSUE TITLE
[2.1] custom built templates for android - fails on android

### ISSUE THREAD

**Issue by plucian** [godotengine/godot#23507]
**Godot version:**

Commit that works: 38ed4b9a8cdea0860eb616ef23306d2ce2d9c86b from 07.28.18
Commit that does not work:  8d75ea755cb933a5c4a0f9ec296e8b8c34ef9999 from 11.04. 18

**OS/device including version:**

Android

**Issue description:**

I'm trying to build a custom android template (under Windows). Just downloaded the code, no additional modules or anything.

I get no errors when compiling either commits, but the last commit creates an android debug template that give me a fatal error on Android, basically the games doesn't start and get an error from the beginning. The older one (from the stable release) works fine.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Did you rebuild the editor to match the commit you're using for the export templates?

**Comment by plucian** [comment]
yes, I did. I used the same build to compile the editor and the android template. The editor works fine as far as I can tell.

**Comment by plucian** [comment]
I was planning on doing just that, but I was hoping someone will have a faster solution.

**Comment by plucian** [comment]
just tried this commit: 2c47116a3c2c429cbd1c66e441b9608bfba2f488, also not working but I did not build the editor with the same commit.

**Comment by allkhor** [comment]
I think you need to rebuild the editor to match the commit you're using.

**Comment by plucian** [comment]
I believe this to be the culprit:  6e62a1e4de31db7e7e14a97f02fbe2619502873c,
I don't think we need editor/template from the same build, at least not all the time. Anyway the editor was built with the latest commit and tried to build only the android template with different commits.

**Comment by allkhor** [comment]
@plucian What the NDK version you are use?

**Comment by lfdversluis** [comment]
@plucian You might want to look into the `git bisect` command. A simple test that will return with a non-zero exit code will help you pinpoint which commit introduced the bug :)

**Comment by allkhor** [comment]
Can you test fix https://github.com/godotengine/godot/pull/23727 ?

**Comment by akien-mga** [comment]
Fixed by #23727.
