### ISSUE TITLE
CanvasShaderGLES3: vertex program compilation failed

### ISSUE THREAD

**Issue by yogasadana** [godotengine/godot#23501]
**Godot version:**
Godot_v3.0.6-stable_win64

**OS/device including version:**
Windows 7 Ultimate 64-Bit/NVIDIA GeForce GT 520M

**Issue description:**

Simply can't open Godot 3.0.6
( im new here, & i dont know about programming, is this a right place to ask? )
i have try to download other version and the result is same as the picture
how to fix this ?

![godot error opening](https://user-images.githubusercontent.com/44746952/47964508-c66eb000-e06d-11e8-831f-e973373b22a9.jpg)

godot icon didn't showed too 
& nothing happen when i click on the screen

**Comment by qarmin** [comment]
For now try to use Godot 3.1 alpha2 from this link https://downloads.tuxfamily.org/godotengine/3.1/alpha2/Godot_v3.1-alpha2_x11.64.zip

Do you have updated nvidia drivers?

**Comment by Goutte** [comment]
I had the same issue ; I updated my drivers and it went away.

**Comment by yogasadana** [comment]
thank you, qarmin , Goutte
now, it works!
i updated the nvidia driver using GeForce Experience

this is the screenshot:

before
![screenshot_1](https://user-images.githubusercontent.com/44746952/47983279-63305c80-e105-11e8-8113-7d02b964c62c.jpg)

after
![screenshot_2](https://user-images.githubusercontent.com/44746952/47983293-6c212e00-e105-11e8-9e9e-1ee944d8871e.jpg)

it's works :) !
![screenshot_5](https://user-images.githubusercontent.com/44746952/47983309-7b07e080-e105-11e8-9a15-bfec21a6d2af.jpg)

![screenshot_7](https://user-images.githubusercontent.com/44746952/47983312-7e9b6780-e105-11e8-8cad-5f71b827a0cd.jpg)
