### ISSUE TITLE
MeshInstance2D  Is not visible when using GLES2

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#23517]
**Godot version:**
3.1 alpha2 mono

**OS/device including version:**
Windows 7 64-bit
Intel Celeron N2840

**Issue description:**
The mesh is not rendered when using GLES2

**Comment by akien-mga** [comment]
Could you be more explicit? There's no such thing as MeshInstance2D.

**Comment by akien-mga** [comment]
Ah indeed, sorry. I was working on the 3.0 branch when I looked it up.

**Comment by akien-mga** [comment]
Seems to work fine for me in the current master branch (on Linux, GTX 670MX).

Please comment if you can still reproduce the issue, and attach a project that exhibits it.
