### ISSUE TITLE
Tileset Atlas Not Initially Visible

### ISSUE THREAD

**Issue by CaptainKraft** [godotengine/godot#23513]
**Godot version:**
Godot 3.1 alpha 2

**OS/device including version:**
Windows 10 and Arch Linux with GeForce GTX1080

**Issue description:**
After creating a tileset with an atlas, and setting it to a tilemap, the tiles are not visible in the editor.
![tilemap01](https://user-images.githubusercontent.com/1237356/47970008-58ae8e00-e045-11e8-90c2-d11548af3ac3.PNG)

If I drag the slider to change the scale, the tiles will appear.
![tilemap02](https://user-images.githubusercontent.com/1237356/47970011-619f5f80-e045-11e8-9efa-1f56c8eed9dc.PNG)

**Steps to reproduce:**
* Add a tilemap node to the scene, and assign a tileset with a tile atlas. No tiles will be visible.
* Next, click and drag the slider to scale tiles, and the atlas will appear.

**Minimal reproduction project:**
[TilemapBug.zip](https://github.com/godotengine/godot/files/2546342/TilemapBug.zip)

EDIT: I am getting the same problem on Linux as well.

**Comment by akien-mga** [comment]
It's still reproducible in the current master branch (d0b736f).

CC @MarianoGnu @YeldhamDev @guilhermefelipecgs
