### ISSUE TITLE
RigidBody2D is moving KinematicBody2d (how to prevent?)

### ISSUE THREAD

**Issue by mcKrawll** [godotengine/godot#23516]
**Godot version:**
v3.0.6 stable
Steam Version

**Issue description:**
This is my first post everyone on GitHub so if I am doing it wrong then I am sorry.

I am making a tetris-like where I need a RigidBody2D(ball) to bounce off of KinematicBody2D(the tetromino). I need to use the KinematicBody2D for the move_and_collide() so that it stops when it runs onto other pieces or the bottom platform(StaticBody2D). I honestly don't understand why there is no toggle for this. I can do this the long and hard way but would prefer to use Godot's built-in physics as I am new to programming to begin with. 

If there is another way to approach this I am all ears but no matter how much I search for this topic I could not find an answer. 

*edit*
This is a similar issue but is not current to the v3.0 and the problem was never resolved.
https://godotengine.org/qa/8820/disable-effecting-kinematic-collisions-forces-colliding

**Comment by akien-mga** [comment]
Please ask such questions on other [community platforms](http://godotengine.org/community), such as the Q&A, Discord, forums, etc.

This issue tracker is for engine bugs, not user support. If you establish with other users that there is indeed a missing feature to solve your use case, then you can open a feature request (or bug report if it's a bug that an existing feature doesn't work as advertised).
