### ISSUE TITLE
The debugger reports the wrong line number in an else block

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23511]
Godot 3.1 alpha 2
Godot 3.0.6
Windows 10 64 bits

The given code is intentionally wrong at runtime, but the debugger doesn't point out the correct line:

```gdscript
extends Node

func _ready():
	if false:
		print("Unreachable")
	else: # The debugger points this line
		# This is a test
		get_node("Inexistent").name = "42" # But this line is where the error occurs
```

Project:
[WrongLineNumberAfterElse.zip](https://github.com/godotengine/godot/files/2546311/WrongLineNumberAfterElse.zip)

**Comment by akien-mga** [comment]
Duplicate of #20820.
