### ISSUE TITLE
Click on Node/path property in the Debug Inspector darken the editor

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#23527]
**Godot version:** 3.1 Alpha 2

**OS/device including version:** Windows 10

**Issue description:**

- **What happened**: See **Steps to reproduce** below
- **What was expected**: The node being debugged is highlighted in the `Remote` tab, which still works normally, but without a darken editor with no other way to fix than to restart the editor.

**Steps to reproduce:** See image below
1. Breakpoint and run in debug mode
2. Click on the self object in the Debugger
3. Click Node/path in the Inspector
4. Find a window flashes, probably a Node Select window
5. Find the editor is darken right after that

**Minimal reproduction project:** 
Not needed. Just enter a breakpoint in any project.

**Screenshot**: 
Darken Editor +Steps to Click

![image](https://user-images.githubusercontent.com/12462089/48002252-9989ce00-e13d-11e8-96ac-5954e1a14e91.png)

**Comment by ankitpriyarup** [comment]
Not able to reproduce the issue in Ubuntu 18.04
I applied breakpoint, clicked on self then path from inspector window but it darkens the editor only till the node select window appears right after it closes editor again becomes normal
![screenshot from 2019-01-25 22-11-54](https://user-images.githubusercontent.com/31309984/51759518-688eb900-20ee-11e9-8181-fa0cb8f8a206.png)

**Comment by DleanJeans** [comment]
Confirming it's fixed at of 3.1 Beta 1
