### ISSUE TITLE
Type hinted Dictionaries don't accept type hinted nodes as keys.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#23520]
**Win10 64-bit f84893f**

When type hinting a dictionary and a node, I get an error when I try to use the node as a key for the dictionary.

@vnen Not sure if this is related to something pending.  Or perhaps not a bug.  Though they work, maybe nodes aren't intended to be used as keys?

![image](https://user-images.githubusercontent.com/13004169/47976908-b67ebc80-e0bd-11e8-851f-dbdb466b44da.png)

![image](https://user-images.githubusercontent.com/13004169/47976904-b2eb3580-e0bd-11e8-8c71-da319b0d9d2e.png)

[3.1 Dictionary Key Issue.zip](https://github.com/godotengine/godot/files/2546856/3.1.Dictionary.Key.Issue.zip)

**Comment by vnen** [comment]
It's a bug, anything can be used as keys.

**Comment by avencherus** [comment]
Thanks for confirming.  I know you're aiming for optimizations planned around typing, so wasn't 100% sure.
