### ISSUE TITLE
Booting time too long on Android (GLES2)

### ISSUE THREAD

**Issue by Shin-NiL** [godotengine/godot#23525]
**Godot version:**
3.1-alpha2

**OS/device including version:**
Android 7.0, GPU: Mali-T860MP2

**Issue description:**
The booting time using GLES2 is taking ~15s on Android, while using GLES3 is ~1s.

**Steps to reproduce:**
Just export and run any GLES2 project on Android. 

**Minimal reproduction project:**
Any GLES2 project.

**Comment by NewNodeGames** [comment]
Try to remove the default environment. Project/Project Settings/Rendering/Environment/Default Environment

**Comment by NewNodeGames** [comment]
> Thanks @NewNodeGames, that worked! But why?

Because Godot always load the environment if there is one, even if is a 2D project.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by Shin-NiL** [comment]
I can't say about the master, because I'm unable to build it right now, but it was fixed on beta 2.
