### ISSUE TITLE
Opening audio panel from script tab breaks UI

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#23521]
**Godot version:**
Godot 3.1 a 2

**OS/device including version:**
Windows 8.1

**Issue description:**
If you open the audio panel from script tab it become like this.
![scripteditorbottomaudio](https://user-images.githubusercontent.com/8316851/47981322-fbc2de80-e0fd-11e8-894b-898e8ce09b59.JPG)
It should not break the UI, if you open the audio tab from another tab (2D or 3D) it display correctly, like this.
![bottom2daudio](https://user-images.githubusercontent.com/8316851/47981372-2f056d80-e0fe-11e8-846d-09ca18b25923.JPG)

**Steps to reproduce:**
Open a project with Godot 3.1 Alpha 2
switch to script tab
open audio panel

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Seems to work fine for me on the current master branch, on Linux.

Can you still reproduce the issue in 3.1 beta 2 or later?

**Comment by earlroxas13** [comment]
Yes it fixed!
Now i'm using beta 2 and on windows 10.

**Comment by akien-mga** [comment]
Thanks, closing then.
