### ISSUE TITLE
Creating a visual script virtual function after minimizing crashes

### ISSUE THREAD

**Issue by fire** [godotengine/godot#23536]
**Godot version:**
3cf3c4137a4e6a5e25d7950ff727ec2157e40a37

**OS/device including version:**
Windows 10, gtx 1080

**Issue description:**
Using the test case from https://github.com/godotengine/godot/issues/23495 I was able to get the editor to crash.

**Steps to reproduce:**

1. Open a scene without a script (or not a loaded, empty scene)
2. Switch to script interface
3. Open res://Tscn/MainScene.tscn file with script
4. Need https://github.com/godotengine/godot/pull/23535 patch or crash
5. Minimize and then maximize the editor
6. Click the new function button.
7. Crash

**Minimal reproduction project:**

Same as https://github.com/godotengine/godot/issues/23495

**Comment by akien-mga** [comment]
Fixed by #23537.
