### ISSUE TITLE
The ParticlesMaterial editor prevents setting particle's angular velocity higher than 360

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23533]
Godot 3.0.6
Godot 3.1 alpha2

I want my particles to rotate faster than 360 degrees per second, however the editor prevents me from writing a value beyond this limit. Perhaps it's because the inspector was hinted this is in degrees, but if it's a velocity there is no point clamping it.

![image](https://user-images.githubusercontent.com/1311555/48023900-ffbf2280-e136-11e8-9717-0ca8d1529703.png)

**Comment by Kanabenki** [comment]
So it should be similar to Initial Velocity (but also with negative values), have a slider from -1000 to 1000 with no clamping of the user input ?

**Comment by akien-mga** [comment]
Yep, though I'd suggest to use multiples of 360 for the min and max of the slider nevertheless, e.g. "-720,720,0.01,allow_lesser,allow_greater".

**Comment by Kanabenki** [comment]
Thanks, I'll make a PR.
