### ISSUE TITLE
CollisionShape.set_shape doesn't update the shape after it's added to the tree.

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/godot#23530]
**Godot version:**
3.1 master

**OS/device including version:**
Fedora 28 64 bit

**Issue description:**
Changing the shape of a CollisionShape after it has been added as a child (to a physics body) has no effect. I'm not entirely sure if this is a bug or the way the shape concept is supposed to work.

**Steps to reproduce:**
Works fine:
```
var cs = CollisionShape.new()
cs.shape = BoxShape.new()
body.add_child(cs)
```

This does seemingly nothing:
```
var cs = CollisionShape.new()
body.add_child(cs)
cs.shape = BoxShape.new()
```

```
var cs = CollisionShape.new()
cs.shape = BoxShape.new()
body.add_child(cs)
cs.shape = null # won't update the actual shape
cs.shape = PlaneShape.new() # likewise
```

**Comment by avencherus** [comment]
Not a bug.  CollisionShapes are editor helpers only.  So using them is code is only useful when making tool scripts.

You want to add the shapes to the physics body using these methods.

https://docs.godotengine.org/ko/latest/classes/class_collisionobject.html#class-collisionobject

Every PhysicsBody extends a CollisionObject, and that's where the information about its shapes are retained.

An example for 2D.

```
extends RigidBody2D


func _ready():
	
	var box_shape = RectangleShape2D.new()
	box_shape.extents = Vector2(64, 64)
	
	shape_owner_add_shape(0, box_shape)
```

**Comment by spongeboburu** [comment]
Thanks for clearing that up.

The docs state "IMPORTANT: this is an Editor-only helper to create shapes, use get_shape to get the actual shape", but the reference link doesn't really explain what owners are (other than "they are not nodes"), etc. I think your small example would be a perfect addition to the docs.
