### ISSUE TITLE
Bad normals only when material is set to transparent

### ISSUE THREAD

**Issue by dallinbeutler** [godotengine/godot#23546]
**Godot version:**
v3.0.6.stable.official.8314054

**OS/device including version:**
Windows Editor

**Issue description:**
I'm trying to use a material that has transparency.
If I set it to transparency, the depth testing gets turned off or something, And I'm left with a wrong looking model. 

**Steps to reproduce:**
1.model was exported from blender to .DAE using the Godot Better Dae exporter.
2. spacial material with transparent texture for albedo is created by hand.
3. model looks fine, normals are in order. Transparency is just black.
![oknormals](https://user-images.githubusercontent.com/9158155/48041796-20d64200-e13c-11e8-90e0-38445ba05441.PNG)

4. Flip on the flag in the material for transparency.
5. Parts that are supposed to be transparent are, but solid parts of texture have faces behind it showing through
![badnormals](https://user-images.githubusercontent.com/9158155/48041805-292e7d00-e13c-11e8-8f1f-0b4d3ec4dd85.PNG)

[transparencyerror.zip](https://github.com/godotengine/godot/files/2551528/transparencyerror.zip)

Sorry if this is a duplicate, I searched open issues best I could

**Comment by Calinou** [comment]
I'm not sure if this can be solved due to how depth sorting works in Godot. Perhaps you could use a separate transparent material for the decal, and keep the material applied to the rest of the mesh opaque.

**Comment by bojidar-bg** [comment]
Try using Parameters -> Depth Draw Mode = Opaque Pre-pass.

**Comment by dallinbeutler** [comment]
@bojidar-bg Oh this is definitely the correct behavior for transparency. I guess I assumed there was one desired depth drawing mode for transparency. Godot keeps amazing me with all it's hidden little options.

**Comment by dallinbeutler** [comment]
Thanks!
