### ISSUE TITLE
C#: Failed to determine namespace and class for script

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#23545]
**Godot version:**
3.1 alpha 2

**OS/device including version:**
Windows 10

**Issue description:**
I cannot build my project because of the following error.
![image](https://user-images.githubusercontent.com/21234930/48040582-65f37780-e12e-11e8-86d9-d628d94f6386.png)

But the class looks perfectly fine.
![image](https://user-images.githubusercontent.com/21234930/48040599-799ede00-e12e-11e8-869e-8804f8e9f803.png)

**Steps to reproduce:**
Try building the attached project.

[BeardHeroes.zip](https://github.com/godotengine/godot/files/2551526/BeardHeroes.zip)

**Comment by neikeq** [comment]
This should have been fixed by #23515. Let me know if it still happens.
