### ISSUE TITLE
Changing global settings at run time

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#23549]
**Godot version 3.0.6**
**OS All**

Changing global settings at run time.
I asked a [question](https://godotengine.org/qa/35329/how-to-change-global-settings-at-run-time). 
But probably no one knows how to do it. Or there is no such possibility.

It doesn't have to be this way. It strongly determines the performance. The user must have the ability to change the rendering parameters at runtime of the game.

**Comment by DimitriyPS** [comment]
Please give feedback on this appeal. It requires revision, documentation or it is possible right now. I am currently working on this issue and it is very important for me to have a reference point. Thanks.

**Comment by akien-mga** [comment]
What did you try so far? `ProjectSettings.get_setting()` and `ProjectSettings.set_setting()` can be used to modify project settings:
```
func _ready():
	print(ProjectSettings.get_setting("debug/settings/stdout/print_fps")) # false
	ProjectSettings.set_setting("debug/settings/stdout/print_fps", true)
	print(ProjectSettings.get_setting("debug/settings/stdout/print_fps")) # true
	# starts printing FPS to output
```

But keep in mind that most settings are read and used when creating the game window/initializing the renderer, so changing their value in the ProjectSettings at runtime might not automatically impact the game (e.g. changing `display/window/size/fullscreen` won't change the fullscreen mode, you need to use `OS` APIs for that).

**Comment by akien-mga** [comment]
See e.g. @Calinou's `godot-sponza`, it lets you change rendering settings at runtime, but this implies that you need to actually change the environment manually and not just the `ProjectSettings` config: https://github.com/Calinou/godot-sponza/blob/master/scripts/settings_gui.gd#L156-L175

**Comment by DimitriyPS** [comment]
Yes I not found this method:

`ProjectSettings.set_setting(`

That's what Me needed. And it works. Regarding the resolution switching, I implemented it long ago.
Thanks for your help. I believe this queryis not actual.

**Comment by DimitriyPS** [comment]
> See e.g. @Calinou's `godot-sponza`, it lets you change rendering settings at runtime, but this implies that you need to actually change the environment manually and not just the `ProjectSettings` config: https://github.com/Calinou/godot-sponza/blob/master/scripts/settings_gui.gd#L156-L175

akien-mga, thank you, I got the topic sorted out little. 

But I have a small question, please help me. Like you said, not all settings can be changed through ProjectSettings. It is useless to change:
`
ProjectSettings.set_setting("rendering/quality/shadow_atlas/size"`

instead, you need to change:
`
get_viewport().shadow_atlas_size=`

And what needs to change for:
`
ProjectSettings.set_setting("rendering/quality/directional_shadow/size"`

**Comment by akien-mga** [comment]
> And what needs to change for:
`ProjectSettings.set_setting("rendering/quality/directional_shadow/size"`

That doesn't seem possible, it's only used in `RasterizerSceneGLES3::initialize()` (or `*GLES2`), so you need to restart the game to take any change to this value into account.

**Comment by DimitriyPS** [comment]
> That doesn't seem possible, it's only used in `RasterizerSceneGLES3::initialize()` (or `*GLES2`), so you need to restart the game to take any change to this value into account.

If the game is not rebooted, and rebooted the scene. Is that possible?

Does it make sense to create a request for improvement? Or is it technically unrealistic?
