### ISSUE TITLE
Issues when trying to change multiple nodes in Node dock

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23553]
**Godot version:**
3.1 3cf3c41

**OS/device including version:**
Windows 10

**Issue description:**
This issues aren't so big and are dependent on each other

- [ ] I haven't option to Make Local multiple nodes
- [x] I have an option to clear script when I select multiple nodes, even if there isn't any script attached
- [x] I can't clear script from multiple nodes

https://streamable.com/a2tsq

**Comment by KoBeWi** [comment]
2 items fixed, open a [proposal](https://github.com/godotengine/godot-proposals) for the last one if it's still desired.
