### ISSUE TITLE
ResourceLoader.exists doesn't work after export

### ISSUE THREAD

**Issue by spaghiajoeojo** [godotengine/godot#23555]
**Godot version:**
Godot 3.1 alpha2 with official export templates

**OS/device including version:**
Windows 10 Ryzen 5 2400G
OpenGL ES 3.0 Renderer: AMD Radeon(TM) RX Vega 11 Graphics

**Issue description:**
In my project, I load a lot of tiny textures at runtime and I need to know before calling the load function if these images exist. This code in example works fine in the editor:
```
extends Sprite

export(String) var image_filename

var index = 0

func _ready():
	_on_Timer_timeout()
	$Timer.start(1)


func _on_Timer_timeout():
	if ResourceLoader.exists("res://images/"+image_filename+str(index)+".png"):
		self.texture = load("res://images/"+image_filename+str(index)+".png")
	else:
		$Timer.stop()
		print("Can't load")
	index += 1
```
But It doesn't work after exporting.
I'm sorry if I can't be more specific than this.

EDIT: I forgot to mention that if I call load directly it works and throw an error when it tries to load an unexistent texture, so resources are properly exported. 

**Steps to reproduce:**
Open the project in the editor and run it.
Sprite node should change texture loading 3 images, at fourth attempt it print "Can't load"
Export the project with official template and run it.
No texture is loaded and it print "Can't load" twice

**Minimal reproduction project:**
[github issue.zip](https://github.com/godotengine/godot/files/2553142/github.issue.zip)

**Comment by spaghiajoeojo** [comment]
If it is a scope problem this is a REALLY BIG issue. _on_Timer_timeout can't access a field of its class? I tried to declare a variable like this:
```
func _on_Timer_timeout():
	var file = self.image_filename
	if ResourceLoader.exists("res://images/"+file+str(index)+".png"):
		self.texture = load("res://images/"+file+str(index)+".png")
	else:
		$Timer.stop()
		print("Can't load")
	index += 1
```
And nothing change.
In this code the first argument can't be nil without an error because it's a concatenation of a constant string with a variable. 

I'm thinking on a bug in path remapping after export because in editor this run fine.

**Comment by piratesephiroth** [comment]
yeah but it's a bug with the scope after exporting and not with the actual path.

**Comment by spaghiajoeojo** [comment]
Still here on 3.1 beta 10
