### ISSUE TITLE
Breakpoint not accepted on empty lines but stops on comments

### ISSUE THREAD

**Issue by Galileo53** [godotengine/godot#23552]
**Godot version:**
V3.0.6

**OS/device including version:**
WIN7

**Issue description:**
consider this or similar code line sequence:

`var something = 1     # this is line 1;  empty line 2 follows` 
` `
`# this is line 3 containing comment only`
`# this is line 4 containing comment only`
`something += 1       # this is line 5`

When a breakpoint is set on empty line 2, the red dot is shown but it will never stop, not even on any following line
When a breakpoint is set line 3 (comment only), it will stop there, even if it contains no code
When pressing the "Step Over" button, it stops on line 4, also containing no code

I would expect that regardless where the breakpoint is set, it should stop at the next line containing code (line 5 in this example).
I would also expect that when pressing the Step-Over button it should stop at the next line containing code (line 5 in this example).

**Comment by KoBeWi** [comment]
Since 3.1, empty lines also stop on breakpoints, so it's at least consistent. Is it ok to close this?

**Comment by akien-mga** [comment]
Seems good to me, closing.
