### ISSUE TITLE
Crash at startup on macOS Mojave

### ISSUE THREAD

**Issue by k7771911** [godotengine/godot#23558]
**Godot version:**
v3.1.alpha2

**OS/device including version:**
macOS Mojave 10.14.1

**Issue description:**
Application crashes at startup, see below, running the same binary directly from a terminal works fine, 

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
../Frameworks/OpenGL.framework/OpenGL
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff5f438b86 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5f4eec50 pthread_kill + 285
2   libsystem_c.dylib             	0x00007fff5f3a21c9 abort + 127
3   org.godotengine.godot         	0x00000001037e7b80 handle_crash(int) + 1664
4   libsystem_platform.dylib      	0x00007fff5f4e3b3d _sigtramp + 29
5   ???                           	0x0000600001182d20 0 + 105553134628128
6   dyld                          	0x0000000113a9fc0d dyld::loadPhase5(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 362
7   dyld                          	0x0000000113a9fa40 dyld::loadPhase4(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 188
8   dyld                          	0x0000000113a9f78f dyld::loadPhase3(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 1393
9   dyld                          	0x0000000113a9eef2 dyld::loadPhase1(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 135
10  dyld                          	0x0000000113a98aef dyld::loadPhase0(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 496
11  dyld                          	0x0000000113a98643 dyld::load(char const*, dyld::LoadContext const&, unsigned int&) + 128
12  dyld                          	0x0000000113aa46a3 dlopen_internal + 421
13  libdyld.dylib                 	0x00007fff5f2e5833 dlopen + 200
14  org.godotengine.godot         	0x000000010405a4d7 gladLoadGL + 23
15  org.godotengine.godot         	0x0000000103f903f9 RasterizerGLES3::is_viable() + 9
16  org.godotengine.godot         	0x00000001037ec89d OS_OSX::initialize(OS::VideoMode const&, int, int) + 1133
17  org.godotengine.godot         	0x00000001038111ee Main::setup2(unsigned long long) + 78
18  org.godotengine.godot         	0x000000010380dab0 Main::setup(char const*, int, char**, bool) + 23552
19  org.godotengine.godot         	0x00000001037f4e16 main + 598
20  libdyld.dylib                 	0x00007fff5f2fa08d start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff5f4eb428 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff5f4eb428 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff5f4eb428 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff5f4eb428 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff5f4eb428 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff5f4eb428 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff5f4eb428 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff5f4348a6 read + 10
1   org.godotengine.godot         	0x00000001037f5099 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x0000000105a4b8dc _IP_ResolverPrivate::_thread_function(void*) + 60
3   org.godotengine.godot         	0x0000000103f61336 ThreadPosix::thread_callback(void*) + 54
4   libsystem_pthread.dylib       	0x00007fff5f4ec339 _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5f4ef2a7 _pthread_start + 70
6   libsystem_pthread.dylib       	0x00007fff5f4eb445 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000113b4b5c0  rcx: 0x00007ffeec413cb8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffeec413cf0  rsp: 0x00007ffeec413cb8
   r8: 0x00000000000130a8   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x0000000000000012  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff5f438b86  rfl: 0x0000000000000206  cr2: 0x00007fff92101188
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

**Comment by marcelofg55** [comment]
Try using the latest master, a recent fix was added that might help you with this.

**Comment by akien-mga** [comment]
This should indeed be fixed in the current master branch. Please comment if you can still reproduce (or open a new issue if the error logs are different).
