### ISSUE TITLE
Insufficient error reporting for shader editor when doing implicit conversions (feature discussion).

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/godot#23565]
**Godot version:**
3.1 master

**OS/device including version:**
Fedora 28 64 bit.

**Issue description:**
Implicit conversions in the shader language usually results in an indicated error (with the red line and the error message at the bottom of the editor). Example

```
int i = 1.0;
"error(lineno): Invalid assignment of float to int"
```
However, if using implicit conversion in an if-statement the gles shader will fail to compile, showing the error only in the output error log.

```
if (1.0) { }
```
The logs show ```error C7011: implicit cast from "float" to "bool"```.

What is a problem though is that if you're using clear color environment shader that will break too and turn completely white. When first running into this problem, it is confusing that you break the environment somehow even though the editor is showing no errors.

Don't know what the policy here is, but if you break the compilation of the gles shader I think it would be appropriate to not compile it and indicate an error directly in the editor, if nothing else to be consistent with how other implicit conversion errors are reported.

**Steps to reproduce:**
In vertex or fragment:

```
if (1.0) { }
```

**Comment by KoBeWi** [comment]
This is the result in 3.2.2 rc3
![image](https://user-images.githubusercontent.com/2223172/89696300-852cc380-d917-11ea-8f78-d2fd097a7592.png)
Seems resolved.
