### ISSUE TITLE
Performance considerations of PoolVector<> (hurts performance?)

### ISSUE THREAD

**Issue by simpleyo** [godotengine/godot#23560]
PoolVector<> has exponential capacity like Vector<>? I think not.

PoolVector<> has a push_back method and is used in Godot. In font.cpp for example.

I think a PoolVector<>::push_back operation allways do a realloc. I think that is not documented.

I do not know if PoolVector::push_back is going to be used extensively in Godot (now PoolVector<> is used in sites like PacketPeer::put_packet_buffer, among others, and PoolVector::resize has the same problem as push_back), but I think it's not a good idea to have a push_back method that does a realloc every time it's called.

And PoolVector<> is exposed to GDScript. PoolByteArray, for example.

I think PoolVector needs to separate the concepts of size and capacity.
That would help the performance. 

Am I missing something?

**Comment by Zylann** [comment]
Also scripts may `push_back` and `append` a lot as well.

**Comment by simpleyo** [comment]
> 
> 
> Also scripts may `push_back` and `append` a lot as well.
> But what about this? [#9727 (comment)](https://github.com/godotengine/godot/issues/9727#issuecomment-317252878)

In that comment he do not talk about PoolVector<>, but he talk about Vector<>.

Vector<> has automatic exponential capacity increase/decrease, but PoolVector<> does not.
PoolVector only handles the concept of size (not capacity).

**Comment by simpleyo** [comment]
> 
> Also scripts may `push_back` and `append` a lot as well.
> But what about this? [#9727 (comment)](https://github.com/godotengine/godot/issues/9727#issuecomment-317252878)

In that comment he talk about Vector<>, not PoolVector<>.
Vector<> has automatic exponential capacity increase/decrease, but PoolVector<> does not.
PoolVector<> only handles the concept of size, not capacity.

**Comment by CptPotato** [comment]
If `PoolVector<>` really re-allocates memory on every size change I think this can be improved. Though, afaik Godot uses it's own memory pool so it might not be as slow as it initially looks.

**Comment by slapin** [comment]
I think quick Vector constructor from PoolVector without memory copying should be enough to solve PoolVector problems. IIRC PoolVector was not intended to be changed often.

**Comment by Calinou** [comment]
This was probably fixed with the [introduction of packed arrays](https://github.com/godotengine/godot/pull/36515), closing.
