### ISSUE TITLE
No icons in Filesystem dock

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#23573]
**Godot version:**
de0d30655859a46eaf711e209fe20d9ca60a60f2

**OS/device including version:**
Ubuntu 18.04, 64bit 

**Issue description:**
I noticed there are no icons in recent builds of Godot. This must be a quite recent bug since in 72db3000a56a6f85d348c218437d1a1dfc0953bf it was working ok.
![no_icons](https://user-images.githubusercontent.com/6129594/48143146-792d5100-e2ae-11e8-99d1-0571f6bea79b.png)

**Steps to reproduce:**
1. Open any demo project
2. Check the filesystem dock

**Comment by groud** [comment]
Could you try delete godot's cache ?
On Linux, files are in the ~/.cache/godot folder.

**Comment by groud** [comment]
Forget that, I was able to reproduce the bug.
