### ISSUE TITLE
TabContainer doesn't layout its children when first added

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23570]
Godot 3.1 alpha 2

Reproduction steps:
1) Create a TabContainer, give it some default size
2) Add a TextEdit as child in order to have one page: notice the page is created, but the TextEdit is not occupying that page properly.
![image](https://user-images.githubusercontent.com/1311555/48135410-c6042e00-e294-11e8-9e1a-07e570838e0e.png)
Note: if you launch the game at this point, the page will be laid out properly, so it seems the issue only exists in the editor.
3) Try to resize the TabContainer: notice the content of the page resizes in weird ways, even disappearing sometimes
![image](https://user-images.githubusercontent.com/1311555/48135461-ee8c2800-e294-11e8-8704-8f37385e0c77.png)
4) Now add another page by adding another control child
5) In the TabContainer properties, switch from page 0 to page 1
6) Switch back to page 0: notice the TextEdit now fits the page correctly
![image](https://user-images.githubusercontent.com/1311555/48135531-1aa7a900-e295-11e8-96b7-570d265e71db.png)

**Comment by avencherus** [comment]
Have noticed this as well, but haven't had a chance to write it up.

As you say, it resolves to normal behavior when another tab is added.

**Comment by dragongling** [comment]
It also resolves to normal behavior when you reload the scene.

**Comment by BenStigsen** [comment]
Any updates on this problem?
