### ISSUE TITLE
Cannot load image texture to sprite

### ISSUE THREAD

**Issue by ssj71** [godotengine/godot#23574]
**Godot version:**
3.1 alpha 2

**OS/device including version:**
Ubuntu Linux 16.04 (using i3wm)

**Issue description:**
when trying to load an image in my resources (icon.png) into a new texture in a sprite the image property remains empty and the following error appears in the output window:
```
Set texture

 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 scene/resources/texture.cpp:191 - Condition ' p_image.is_null() ' is true.
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
 drivers/gles3/rasterizer_storage_gles3.cpp:1035 - Condition ' !texture->active ' is true. returned: Ref<Image>()
```

I can load the image into an animated sprite frame but not into a sprite. The error still occurred when I tried GLES2 as well. The expected behavior is that the image loads and shows in the sprite. I can just drag the image from the filesystem, but I'd expect this way to work as well...

This bug happens in a more complex scene as well. I'm really trying to add a sprite as a child note to a rigidbody, but found that it occurs regardless of the parent or siblings.

**Steps to reproduce:**

1. Create new project
2. add node2d as root to scene
3. add sprite as child of the root
4. in the inspector create a new ImageTexture
5. in the inspector for the new imageTexture, click load image and select any image
6. observe the error in the window.

**Minimal reproduction project:**
[godot_mwe.zip](https://github.com/godotengine/godot/files/2558192/godot_mwe.zip)

**Comment by ssj71** [comment]
Ok. Thanks, sorry for the noise. So an imagetexture cannot be used in a sprite or a local image file cannot be used in an imagetexture?

**Comment by clayjohn** [comment]
ImageTexture is more of internal class for converting between Images and Textures. You could use it through GDscript. But there is no reason to use it to assign an Image to a Sprite.

**Comment by ssj71** [comment]
I'm just wondering if it should not show in the list in sprite when you click on the texture property. Thanks for the info, should I close this issue or change it to something like "error message unclear when adding imagetexture to sprite"?

**Comment by Zylann** [comment]
You should choose to `Load` a texture from a file, because Godot can have imported that texture either as a `StreamTexture` or an `ImageTexture`. So technically, you can set an `ImageTexture`. But the inspector is quite generic and shows you all compatible texture types anyways, including those that don't work out of the box. That means you could also choose `New Texture` for example, and end up with the same problem, because textures are supposed to either be the result of an import, or created in a few steps from GDScript.

**Comment by Chaosus** [comment]
Not detectable in current master, closed by bugsquad.

**Comment by capnm** [comment]
> Not detectable in current master, closed by bugsquad.

Hey robot, are you making fun of us humans? Regarding this bug report, neither Documentation nor the behaviour of the Inspector has changed.

![image](https://user-images.githubusercontent.com/4047289/56451036-0da1e200-632a-11e9-94ac-90b7ac815fd4.png)
