### ISSUE TITLE
Changes in TextureRegion window not canceled.

### ISSUE THREAD

**Issue by DDru** [godotengine/godot#23587]
**Godot version:**
3.1 alpha 2

**OS/device including version:**
Windows 10

**Steps to reproduce:**
Set sprite region on the texture.
In the TextureRegion window, change the region rect on the texture and make undo (ctrl + z)
On the sprite, the changes will be rolled back, but not in the TextureRegion window.

**Comment by KoBeWi** [comment]
Fixed since 3.1 stable
