### ISSUE TITLE
Screen fading does not hiding after closing selection window.

### ISSUE THREAD

**Issue by DDru** [godotengine/godot#23586]
**Godot version:**
3.1 alpha 2

**OS/device including version:**
Windows 10

**Issue description:**
Screen fading don't hiding after choosing file/directory.

**Steps to reproduce:**
In the script write "export(String, DIR) var f " (without quotes), switch to 2D-view and press folder icon in "Script Variables" for directory selection.
Press ESC to cancel and close the window.
In script change DIR to FILE and again click on folder button in "script variables".
Selection window openning and immediately close. Screen fading does not hide.

Sometimes it dont triggering. I think this due to the recompilation of the script.

**Minimal reproduction project:**

**Comment by krdluzni** [comment]
Appears to occur with directory selection popups in the editor's own UI as well. Can consistently reproduce on a fresh project with the following steps:
1. Open or create a project.
2. Go to Editor > Editor Settings > Filesystem > Directories.
3. Use the folder icon to select a path for Autoscan Project Path.
4. Click the reset to default button.
5. Click the folder icon again.
6. Wait 1 second, and the popup will close itself automatically.
7. Click Close on the Editor Settings popup, and note that the fade effect remains over the editor.

**Comment by KoBeWi** [comment]
Fixed in 3.2
