### ISSUE TITLE
Merge the output panel and the debugger panel

### ISSUE THREAD

**Issue by BBric** [godotengine/godot#2358]
The output panel could be merged with the debugger panel in a tab.
The cross button could be removed and the big bottom button could be used for open/close the debugger/output panel.

**Comment by akien-mga** [comment]
IIUC correctly you don't propose to merge the contents of the output and debugger panels, but only to make them both tabs of a single panel? Could you provide a visual mockup of what you have in mind?

**Comment by BBric** [comment]
Nothing of very complicated, for example : 
![panel](http://www.pasteall.org/pic/show.php?id=95158)

**Comment by reduz** [comment]
This is a really, really, really, good idea. I'll see if I can implement it before 2.0

**Comment by akien-mga** [comment]
I believe this was implemented in 74a48a0 :-)
