### ISSUE TITLE
Godot Engine 3.1 ALPHA 2 don´t respond (resolved)

### ISSUE THREAD

**Issue by hyperJJmaster** [godotengine/godot#23585]
**Godot version:**
3.1 ALPHA 2

**OS/device including version:**
Windows 7 64x
Intel HD Graphics SandyBridge or 2nd generation

**Issue description:**
godot don´t respond when open proyect or create new proyect

![error](https://user-images.githubusercontent.com/24927155/48172486-03d17880-e2ce-11e8-8123-b887113d764d.png)

**Steps to reproduce:**
Just open proyect or create new proyect

**Comment by MightyPrinny** [comment]
Try editing the project file and delete the default environment, that seems to break gles2 projects

**Comment by hyperJJmaster** [comment]
I think that can not be done from the project manager or is it? because I can not access the editor

**Comment by Calinou** [comment]
@hyperJJmaster The `default_env.tres` file is located in the project directory, try accessing it from a file manager and remove it.

**Comment by hyperJJmaster** [comment]
OOhhh thanks

**Comment by StraToN** [comment]
If the problem is resolved, I'll close the issue. Thanks @Calinou :)
