### ISSUE TITLE
OpenGL2 ES app quit on Android with 3.1 alpha

### ISSUE THREAD

**Issue by gattila** [godotengine/godot#23580]
Godot Version 3.1 Alpha 2

Android 6.0, Xiaomi Redmini Note 3
GPU: Adreno 510

Issue description:

I tired to export my test project to android. At first, I tried with the GLES2 driver, but quitted after the splash screen. I also tried to export with GLES3 driver and it works fine, except the 3D part of the test. 

It works fine on my laptop with the GLES2 driver too.

My test project:
https://github.com/gattila/gamedemo

**Comment by akien-mga** [comment]
Try to remove [those lines](https://github.com/gattila/gamedemo/blob/master/project.godot#L27-L29) to disable the default environment which contains a `ProceduralSky` (or just remove the sky from the default env). I think `ProceduralSky` is not properly supported yet on GLES2 (at least it causes issues on Windows too).

**Comment by gattila** [comment]
Thank you, it solved the issue. Unfortunately, the 3D animation still not work, despite the fact that I removed the environment setting from camera too, but the other parts works like a charm.
