### ISSUE TITLE
Error  Condition ' !owner_valid ' is true when trying revert moving node in Scene Dock

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23594]
**Godot version:**
3.1 de0d306

**OS/device including version:**
Windows 10 

**Issue description:**
When I move a node with its child to other node and revert this(via CTRL + Z), then this error occurs:
> ERROR: set_owner: Condition ' !owner_valid ' is true.
   At: scene/main/node.cpp:1490

**Steps to reproduce:**
https://streamable.com/f7bn9

**Comment by KoBeWi** [comment]
Doesn't seem to be happening in 3.1 stable
