### ISSUE TITLE
Moving variable to parent script is not seen until closing and reopening the child script.

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#23591]
**Godot version:**
de0d3065

**OS/device including version:**
ArchLinux 4.18.16-arch1-1-ARCH

**Issue description:**
Script B inherit from script A. Script B has a variable called "my_var" and it is used in "child_function".
If the declaration of "my_var" is moved to A instead of B, the GDScript parser will consider "my_var" undeclared until the script is closed and opened again.

**Minimal reproduction project:**
[ScriptInheritance.zip](https://github.com/godotengine/godot/files/2561323/ScriptInheritance.zip)

1. Open the project
2. Open both scripts
3. Move my_var from Spatial2.gd to Spatial.gd

**Comment by QbieShay** [comment]
@akien-mga  i think it is a bug of how the editor handles inheritance: if i play the scene, everything runs fine.

**Comment by KoBeWi** [comment]
Fixed in 3.2
