### ISSUE TITLE
Editor panels messed up, 2D viewport inoperable

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#23598]
**Godot version:**

43e358205831fbcc5d6d7e8aade5131168d83651 Mono

**OS/device including version:**

Linux

**Issue description:**

According to @Calinou , appears to be a regression caused by https://github.com/godotengine/godot/commit/f2e54057aec3a4e4fbb9f9da5729915deb2f4648

![image](https://user-images.githubusercontent.com/28724859/48217951-5b172d80-e34e-11e8-8b61-e2a70fad0f34.png)
![image](https://user-images.githubusercontent.com/28724859/48217957-61a5a500-e34e-11e8-9abb-10793b634ff9.png)
![image](https://user-images.githubusercontent.com/28724859/48217967-679b8600-e34e-11e8-8da2-d9bbd0f8d695.png)

2D viewport does not scroll or update anymore.  The editor will also darken, as if to show information, but instead shows nothing.

**Comment by akien-mga** [comment]
I can't reproduce on d403b408 with a non-Mono build, on Mageia 7 x86_64.

**Comment by somnivore** [comment]
@akien-mga I cleared out my .config/godot, various .mono folders, recloned, rebuilt, and everything seems to be OK now.

**Comment by FeralBytes** [comment]
@somnivore so should this be closed? Unless you can reproduce the error.

**Comment by somnivore** [comment]
I'll assume it was just to do with differences in config files between previous Godot builds, as the problems don't seem to be coming back.
