### ISSUE TITLE
Selected control is not highlighted in the 2D viewport when inside a container

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23606]
Godot 3.1 alpha2

When I select a control node in the scene tree, it is not highlighted in any way in the main viewport. I understand I can't move it freely but I cannot see what I am selecting, or which size they take (especially when they have no visuals!).
I can't select from viewport either, it either gets the top-most container, or just nothing.

![image](https://user-images.githubusercontent.com/1311555/48234364-3ef8a800-e3b1-11e8-85d9-e0e0b30ae344.png)

**Comment by antoniotorresm** [comment]
This is truly annoying and the reason I haven't updated to alpha2 yet. #23059 seems to fix it :)

**Comment by groud** [comment]
Indeed, #23059 fixes the problem.
