### ISSUE TITLE
PhysicsBody2D still selectable as a child, when "child is not selectable" toggle is on

### ISSUE THREAD

**Issue by viniciuscsg** [godotengine/godot#23607]
If you have any type of PhysicsBody2d node as a child of another node, and the parent node has the "Makes sure the object's children are not selectable" toggle as activated, the selection box of the child do becomes invisible as expected, and only the selection box of the parent node can be seen, but clicking blindly on the area of the unselectable PhysicsBody2d child still triggers the selection of the whole node group, even if that area does not corresponds to the selection box of the parent node of the group.

Steps to reproduce: create a Position2d node, (or any other Node2d type with a selection box), then create any PhysicsBody2d node which is larger than first node, and make it a child of the first node. Click the "Makes sure the object's children are not selectable" toogle of the parent to activate it. Click outside the parent's selection box, but somewhere where the PhysicsBody2d node would be selectable.

**Comment by akien-mga** [comment]
Godot version?

**Comment by viniciuscsg** [comment]
Ops: v3.06.stable.official.8314054

**Comment by groud** [comment]
I believe this is fixed on master.

**Comment by viniciuscsg** [comment]
Should we close it?

**Comment by akien-mga** [comment]
It's still valid in the master branch, but I'm not sure if it should be changed. Making children not selectable means that they can't be selected by themselves, but they still participate in defining the region occupied by their parent node, and thus clicking them lets you select the parent.

**Comment by groud** [comment]
Ah yes indeed, I read the issue too fast. This is in fact a feature a lot of people wanted to have, it work the same way as instaciated scenes.

If you do not want the node to be selectable, simply lock the parent node too. (or the collision one with "editable children")

**Comment by viniciuscsg** [comment]
I see. In fact, the only reason I noticed this was because I was trying to bypass the large 64px selection box of  PhysicsBody2d nodes mentioned in #4255, by making the physics body a child of a smaller node. If #4255 is already solved then, I believe the use case for this would no longer be relevant, but who knows. Usually you wont have larger childs and smaller parents.

**Comment by groud** [comment]
Yes, the selection design is a lot more consistent on master. Have you tried with 3.1 alpha 2, to see if it solves the problem? (think about making a copy of your project to avoid breaking it)

**Comment by viniciuscsg** [comment]
Will try, thanks, current project is much more to learn godot than anything. Thank you very much for the attention.

**Comment by akien-mga** [comment]
Closing then as we can consider the current system as the wanted behaviour.
