### ISSUE TITLE
Ctrl+Click on image.load() opens documentation for @GDScript.load instead of Image.load

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23601]
Godot 3.1 alpha2

```gdscript
func _ready():
	var im = Image.new()
	var err = im.load(path)
```

When I use Ctrl+Click to go to the definition of `im.load()`, it opens the doc for the global `load` function instead of `Image.load`.
The same happens with this:
```gdscript
func _ready():
	var im := Image.new()
	var err = im.load(path)
```
Or this:
```gdscript
func _ready():
	var im : Image = Image.new()
	var err = im.load("res://icon.png")
```

**Comment by Kanabenki** [comment]
It seems the problem is with:
https://github.com/godotengine/godot/blob/45154be35f282e8e332f3c26e8b93ec3ae014825/modules/gdscript/gdscript_editor.cpp#L3147-L3154
which return the load function from `@GDScript`, without this block the correct definition is loaded.

**Comment by KoBeWi** [comment]
Still valid in e820a73

**Comment by Rindbee** [comment]
It cannot be reproduced in v3.5.2.stable.official [170ba337a] and v4.0.stable.official [92bee43ad].
