### ISSUE TITLE
Request for AnimationPlayer signals when animations are added / deleted / renamed.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#23613]
Nothing major, so not much detail to offer on it.  I was considering that it might be useful from time to time when making tools for AnimationPlayers, or dynamically creating animations with script, that we can know when an animation was created, renamed, or deleted.

- animation_added(animation_name : String)
- animation_deleted(animation_name : String)
- animation_renamed(current_name : String, previous_name : String)

**Comment by KoBeWi** [comment]
Looks like this gained 0 interest and OP is a ghost 👻 so closing.
