### ISSUE TITLE
Shape key animation with update method `continuous` jittering

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot#23610]
**Godot version:**

Godot 3.0 official

**OS/device including version:**

macOS 10.13

**Issue description:**

I got a shape key animation (provided by @samvila ), it looks like this:
<img width="716" alt="screen shot 2018-11-08 at 21 15 41" src="https://user-images.githubusercontent.com/19422835/48244650-aa377f80-e39b-11e8-8621-654aaa1f6a03.png">

the animation can be successfully played, but when animation update method set to `continuous`, the whole mesh would slightly moved in some frame, visually looks like 'jittering'. But when the update method set to `discrete`, everything is fine.
Here is a short video shows this problem: 
[2018-11-06 12-52-57.mp4.zip](https://github.com/godotengine/godot/files/2564700/2018-11-06.12-52-57.mp4.zip)  (provided by @samvila )

I played with it for a lot of times, the issue seems not happening in some certain frame, but randomly. Note that this scene is exported from blender using godot-exporter, so I am not sure the issue is in the scene itself or in godot side.

**Steps to reproduce:**

**Minimal reproduction project:**

[head_only.escn.zip](https://github.com/godotengine/godot/files/2564693/head_only.escn.zip)

**Comment by KoBeWi** [comment]
Fixed in 3.2
