### ISSUE TITLE
Editor settings color picker and OptionButton close themselves prematurely when the editor theme is regenerated

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#23626]
**Godot version:**

a16d9c6ab68cadb3cff07ef8b7b8c00717e98922

**OS/device including version:**

Linux

**Issue description:**

![image](https://user-images.githubusercontent.com/28724859/48297988-a9294f80-e47a-11e8-80a7-637f61847040.png)

The color picker dialogue under `Editor Settings -> Interface -> Theme` has a habit of closing itself while you're in the middle of trying to decide on a color; the moment the editor updates its color scheme, whether or not you're finished, the dialogue will close on its own, and may close itself again after a short delay when opened a second time.  This self-closing behavior seems to also happen when other editor color settings are modified, such as `Text Editor -> Highlighting`.

Picking a color, picking a hue, sometimes even just clicking in one of the RGBA number fields, can cause the dialogue to close.  Ideally it will stay open until the user clicks outside of the dialogue.

**Comment by TheBrunoMiguel** [comment]
I will be atempting to solve this issue soon

**Comment by CowThing** [comment]
This still happens in 3.1 Beta 2

**Comment by mattintriago** [comment]
Me and my software engineering group will attempt to solve this issue if hasn't been fixed yet

**Comment by volzhs** [comment]
@mattintriago welcome :smile:

**Comment by MelvinWM** [comment]
The constant `EditorSettings::NOTIFICATION_EDITOR_SETTINGS_CHANGED` and the methods `EditorSettingsDialog::_notification` and `EditorInspector::_notification` might be relevant reg. the bug.

**Comment by mattintriago** [comment]
Is this issue going to be closed?

**Comment by MelvinWM** [comment]
@mattintriago There is a pull request for fixing it in #27138 , but that has not been merged. If that pull request is merged and it is confirmed that it fixes this issue, it would then make sense to close this issue. It does not AFAICT make sense to close this issue before it has been confirmed to have been fixed.

**Comment by KoBeWi** [comment]
I identified two lines that, when removed, stop the issue from happening:
https://github.com/godotengine/godot/blob/65dce481b06dbdeda8490bbfa9d5a9c1379870b6/editor/editor_inspector.cpp#L3517
https://github.com/godotengine/godot/blob/65dce481b06dbdeda8490bbfa9d5a9c1379870b6/editor/editor_settings_dialog.cpp#L138
With #53839 we could only call them when relevant settings change.
