### ISSUE TITLE
Left and right docks get resized smaller when the editor is minimized and maximized

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23620]
Godot 3.1 alpha 2
Windows 10 64 bits

Reproduction:
1) Open a project
2) Give some large width to any of the left or right docks
3) Minimize the Godot window by clicking `[_]` or the taskbar icon
4) Maximize back the Godot window: notice docks have been resized to a much smaller width (not always the minimal width)

This reproduces with any of the modes selected (2D, 3D, Script).

It could be related to #23289 but the occurence is slightly different so I made another issue

**Comment by groud** [comment]
Duplicate of #23289

**Comment by Zylann** [comment]
Hmmm but here is the thing:

- In 3.0.6, sure #23289 reproduces... but not this.
- In 3.1 alpha 2, #23289 reproduces "as usual"... but now THIS happens too.

That's why I was inclined to not put them in the same bag, something made this extra annoyance happen recently and is less expected than the resizing behaviour (as I read in IRC that it's how docks work).

**Comment by groud** [comment]
In 3.0.6, the docks'  minimum width was higher, so basically the problem was almost invisible. 
The whether it comes from the minimization or resize, the problem simply comes from the fact the editor is resized at a point.

Both come from the exact same problem: the SplitContainer's offset property gets overridden when the container size is not large enough.

**Comment by groud** [comment]
> @groud I edited my comment, read the second part

Indeed, this is probably a side effect on window's way to resize windows. I can't tell.

**Comment by Zylann** [comment]
I'll close this one because #20748 already describes docks behavior and I created #23642 to point out the underlying issue
