### ISSUE TITLE
Custom node icons do not show in the scene tree.

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot#23637]
**Godot version:**
Godot 3.1 alpha 2

**OS/device including version:**
Windows 7, Intel HD Graphics 4400

**Issue description:**
I've learnt that as of this version(or some nightly build I'm not aware of), typing the following code in a tool enabled gdscript:

    class_name Class, "icon_path"
should have the script inside the list of nodes you can add, including a custom icon. However this only partially works for me. You see, the icon indeed appears in the list of available nodes. But it doesn't show up in the scene tree. This also applies to nodes added by an editor plugin as I have observed.

**Steps to reproduce:**
Just make a new gdscript, add the previously mentioned code, with a custom icon at hand, along with to keyword. Then attempt to add this new node. You'll see that the icon will not show.

**Comment by SIsilicon** [comment]
What did that mean exactly? You sent this issue to @willnationsdev , or your telling me I should. Just clarifying.

**Comment by willnationsdev** [comment]
@SIsilicon he has cc'd me so that it will be brought to my attention. I will have to take a look at it. I'm the one who implemented all of the editor's "script class" features, so I'm the one best positioned to diagnose and fix the problem.

**Comment by SIsilicon** [comment]
Ok thanks. :smiley:

**Comment by toiletsnakes** [comment]
I'm seeing this issue again. godot 3.1.1.stable official

the icon remains if the node is registered as an editor plugin, otherwise it does not.

and for what its worth, if I use `class_name` inside of the script for a node that is registered in an editor script, I get 2 node types.
