### ISSUE TITLE
after skeletonik‘s tip bone，bones will turn 90d 

### ISSUE THREAD

**Issue by ywaby** [godotengine/godot#23630]
**Godot version: night build

**OS/device including version: debian buster

**Issue description:**

![screenshot from 2018-11-10 20-01-04](https://user-images.githubusercontent.com/12198203/48301332-35914c00-e527-11e8-9b31-410d2d2864b0.png)

**Steps to reproduce:**

**Minimal reproduction project:[godot_ik_bug.zip](https://github.com/godotengine/godot/files/2568390/godot_ik_bug.zip)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

**Comment by ywaby** [comment]
it fix by enable "override tip basis".

**Comment by KoBeWi** [comment]
Should be fine to close as per above comment.
