### ISSUE TITLE
MeshInstance2D  ImageTexture, not working

### ISSUE THREAD

**Issue by steelxtreme** [godotengine/godot#23636]
**Godot version:**

GODO 3.1 alpha 121cead
**OS/device including version:**

Windows 10 amd Ryzen 5 VEGA 8 GPU:
**Issue description:**

ImageTextture won't load images and should load an image as a texture

**Steps to reproduce:**
Create MeshInstance2d,
Add ImageTexture in texture option
try to add new image and always be empty

**Comment by clayjohn** [comment]
When you click the "Texture" property are you then selecting "Load" or are you selecting "ImageTexture"? 

The proper way to assign a texture in Godot is using "Load". On import godot converts the image into a texture for you. So trying to do so again will cause an error. Someone had the same issue a few days ago as well, https://github.com/godotengine/godot/issues/23574.

**Comment by Chaosus** [comment]
Yeah, seems to be a none-bug.. just an incorrect usage
