### ISSUE TITLE
Tilemap seems to be broken!!

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23631]
**Godot version:**
calinou.da1f53c

**OS/device including version:**
OSX Mojave

**Issue description:**
Inside the editor everything is OK:
<img width="794" alt="captura de ecra 2018-11-10 as 13 01 05" src="https://user-images.githubusercontent.com/10358443/48301655-2f7c7a80-e4e9-11e8-8c50-9325f6e2e2b6.png">

When I run the game I get this problem with the tiles:
<img width="1017" alt="captura de ecra 2018-11-10 as 13 01 18" src="https://user-images.githubusercontent.com/10358443/48301662-428f4a80-e4e9-11e8-90d4-85d62b3f8491.png">

**Comment by Zireael07** [comment]
The same problem was reported yesterday but I can't find the issue number atm.

**Comment by bruvzg** [comment]
#23612 duplicate. Should be fixed by #23625.

**Comment by xDGameStudios** [comment]
Thank you! ...for moments I though it was a problem in my end!

**Comment by Calinou** [comment]
Closing, as this was solved by #23625.

**Comment by Aaron-Fleisher** [comment]
@xDGameStudios Can you confirm if this was the same issue you had?
https://github.com/vnen/godot-tiled-importer/issues/103

**Comment by xDGameStudios** [comment]
The problem was solved with the #23625 so I guess it was the same!

**Comment by Aaron-Fleisher** [comment]
@xDGameStudios Really? Shucks. My issue must be different then

**Comment by Aaron-Fleisher** [comment]
@jfmajor Think it might be a core issue, and not related to the official tiled addon? I might make a separate issue

**Comment by jfmajor** [comment]
Found a workaround for now.
Added "tilemap.format = 1" around line 222 of tiled_map_reader.gd after the TileMap.new()

**Comment by Aaron-Fleisher** [comment]
Thank you so much @jfmajor that seemed to fix it for now!
