### ISSUE TITLE
Project build failing with Mono when building from different drive as Godot binary

### ISSUE THREAD

**Issue by RySchmitt** [godotengine/godot#23641]
**Godot version:**
master 3e128a6 (built with mono)

**OS/device including version:**
Windows 7

**Issue description:**
Failed to build a c# project

**Steps to reproduce:**
1. Compile on the D drive
2. Create or open a project with mono
3. Attempt to run the project

The build fails with build log:
Project "GodotSharp.sln" (Build target(s)):
	Message: Building solution configuration "Release|Any CPU".
	Project "GodotSharp.csproj" (default targets):
		Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
		Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
		Touch: Touching "D:\Release\GodotSharp.csproj.CopyComplete".
		Message: GodotSharp -> C:\Users\Ryan\AppData\Roaming\Godot\mono\solutions\3209965580987625851_5_1541400865\GodotSharp\bin\Release\GodotSharp.dll
	Done building project "GodotSharp.csproj".
	Project "GodotSharpEditor.csproj" (default targets):
		ResolveAssemblyReference: Primary reference "GodotSharp".
		C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(2126,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Image is too small. [C:\Users\Ryan\AppData\Roaming\Godot\mono\solutions\3209965580987625851_5_1541400865\GodotSharpEditor\GodotSharpEditor.csproj]
		ResolveAssemblyReference:     Resolved file path is "C:\Users\Ryan\AppData\Roaming\Godot\mono\solutions\3209965580987625851_5_1541400865\GodotSharp\GodotSharp.csproj".
		ResolveAssemblyReference:     Reference found at search path location "{HintPathFromItem}".
		Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
		Csc: C:\Program Files\Mono\bin\csc.bat /noconfig /nowarn:1591,1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /doc:bin\Release\GodotSharpEditor.xml /highentropyva+ /reference:"C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll" /reference:"C:\Program Files\Mono\lib\mono\4.5\System.Core.dll" /reference:"C:\Program Files\Mono\lib\mono\4.5\System.dll" /debug:portable /optimize+ /out:\Release\GodotSharpEditor.dll /subsystemversion:6.00 /target:library /utf8output Core\EditorNativeCalls.cs ObjectType\AnimationTrackEditPlugin.cs ObjectType\EditorExportPlugin.cs ObjectType\EditorFileDialog.cs ObjectType\EditorFileSystem.cs ObjectType\EditorFileSystemDirectory.cs ObjectType\EditorImportPlugin.cs ObjectType\EditorInspector.cs ObjectType\EditorInspectorPlugin.cs ObjectType\EditorInterface.cs ObjectType\EditorPlugin.cs ObjectType\EditorProperty.cs ObjectType\EditorResourceConversionPlugin.cs ObjectType\EditorResourcePreview.cs ObjectType\EditorResourcePreviewGenerator.cs ObjectType\EditorSceneImporter.cs ObjectType\EditorScenePostImport.cs ObjectType\EditorScript.cs ObjectType\EditorSelection.cs ObjectType\EditorSettings.cs ObjectType\EditorSpatialGizmo.cs ObjectType\ScriptCreateDialog.cs ObjectType\ScriptEditor.cs ObjectType\VisualScriptEditor.cs Properties\AssemblyInfo.cs "C:\Users\Ryan\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
		ObjectType\EditorInterface.cs(11,53): error CS0246: The type or namespace name 'Node' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Ryan\AppData\Roaming\Godot\mono\solutions\3209965580987625851_5_1541400865\GodotSharpEditor\GodotSharpEditor.csproj]
		ObjectType\EditorSceneImporter.cs(8,48): error CS0246: The type or namespace name 'Reference' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Ryan\AppData\Roaming\Godot\mono\solutions\3209965580987625851_5_1541400865\GodotSharpEditor\GodotSharpEditor.csproj]
		ObjectType\EditorFileDialog.cs(8,45): error CS0246: The type or namespace name 'ConfirmationDialog' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Ryan\AppData\Roaming\Godot\mono\solutions\3209965580987625851_5_1541400865\GodotSharpEditor\GodotSharpEditor.csproj]
		ObjectType\EditorInspector.cs(8,44): error CS0246: The type or namespace name 'ScrollContainer' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Ryan\AppData\Roaming\Godot\mono\solutions\3209965580987625851_5_1541400865\GodotSharpEditor\GodotSharpEditor.csproj]

[These errors persist for the rest of the classes]

Done building project "GodotSharpEditor.csproj" -- FAILED.
Done building project "GodotSharp.sln" -- FAILED.

**Comment by RySchmitt** [comment]
I managed to find a work around. The issue arose when I compiled and ran it on the D drive. After compiling on the C drive, it ran correctly. It appears that the issue relates to what drive is used to compile.

**Comment by neikeq** [comment]
Can you reproduce this on latest master or 3.1 beta 4?

**Comment by akien-mga** [comment]
No answer, closing as stale.
