### ISSUE TITLE
Moving NavigationPolygonInstance(2D) cause Condition ' !nm.linked ' is true.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23643]
**Godot version:**
3.1 3e128a6

**OS/device including version:**
Linux Mint 19

**Issue description:**
When I try to move previously created NavigationPolygonInstance then this errors occurs:
> ERROR: _navpoly_unlink: Condition ' !nm.linked ' is true.
   At: scene/2d/navigation2d.cpp:144.

**Steps to reproduce:**
![jfile](https://user-images.githubusercontent.com/41945903/70702570-a1b42580-1cce-11ea-8409-99a38cd70309.gif)

**Comment by KoBeWi** [comment]
Seems fixed in 4.0-dev
