### ISSUE TITLE
Opacity of border, shadow and anti-aliasing in StyleBoxFlat is rendered too strong

### ISSUE THREAD

**Issue by pshe94** [godotengine/godot#23640]
**Godot version:**
3.0.6 official and 3.1 alpha2 (x64)

**OS/device including version:**
Arch Linux, GPU: NVIDIA GTX 770 (396.54.09)
Windows 10, GPU: Intel Integrated Graphics

**Issue description:**
When border, shadow or anti-aliasing is enabled in options of StyleBoxFlat, opacity of that effect is stronger than it should be.
Modifying alpha channel of `modulate` property also causes these effects to be rendered too strong.

Example of Anti-aliasing:
In both instances anti-aliasing size is set to 5. Notice the blur around Panels being 'stronger' than the main body:
![image](https://user-images.githubusercontent.com/34661843/48305063-5efca880-e524-11e8-9602-970f51de5cb7.png)

When alpha channel of the color is set to very low values, the blur is more transparent, but still bit stronger than main body:
![image](https://user-images.githubusercontent.com/34661843/48305286-25c63780-e528-11e8-8c96-6acd68e574a7.png)

Same thing happens with border and shadow. You can see that if you set the color of border or shadow to be the same value as background color (make sure that alpha channels are the same, and are < 255).
 
Sorry if issue is hard to understand, English is not my main language.

**Steps to reproduce:**
1. Create Panel
2. Create new StyleBoxFlat, and set:
2a. `Bg Color` to any color, with alpha value < 255 (for example `#80ff0000`) OR `Bg Color` to `#ffffff` AND `Modulate` in Panel to any color, with alpha value < 255 (for example `#80ff0000`)
2b. `CornerRadius` to any number > 0 (for example `50`)
2c. `Anti Aliasing` `Size` to 5, to better visualize of the problem
3. Attatch StyleBoxFlat created in 2. to Panel created in 1. (`Custom Styles -> Panel`)
4. Play the project

**Minimal reproduction project:**
[3.0.6 project](https://github.com/godotengine/godot/files/2568674/StyleBoxFlat.antialiasing.zip)

EDIT: updated issue, turns out that not only AA is rendered too strong, but also border and shadow.

**Comment by pshe94** [comment]
Same thing happens with border. Setting `border_color` to be the same as `bg_color` renders border 'stronger' than the center.

**Comment by Calinou** [comment]
@pshe94 Can you (or anyone else) still reproduce this bug in Godot 3.2.2?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
