### ISSUE TITLE
Particle2D textures have a very small scale

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#23647]
**Godot version:**
 c3023e8

**OS/device including version:**
Manjaro GNU/Linux, GeForce 820M

**Issue description:**
When giving a texture to a Particles2D node, they will be emitted at a very small scale.
In 3.0, the scale was the same as the texture.

**Comment by YeldhamDev** [comment]
So now you need to put a `CanvasItemMaterial` everytime you use a `Particles2D` with textures? Why?

**Comment by lekoder** [comment]
Got affected by this. Suddenly after engine upgrade all particles in the game seemed gone. Requirement to change all the particle systems sound like a breaking change. 

If there is additional setting required, could it either fall back to previous behaviour or be set automatically on import?

**Comment by akien-mga** [comment]
For the reference, this is likely a consequence of #22622. We should rediscuss with @reduz whether this is the wanted workflow, or if it should be reworked to fix the compatibility breakage.

**Comment by JFonS** [comment]
Yeah, I was waiting to discuss with @reduz how o handle this new workflow.

**Comment by Aaron-Fleisher** [comment]
> Got affected by this. Suddenly after engine upgrade all particles in the game seemed gone.

Yeah same here. I just noticed all my particles are very small (like infinitesimally). I have to scroll in quite a well to even see them. I figured I'd post here instead of making a new issue.

**Comment by lekoder** [comment]
@JFonS I'm afraid it's not over yet. I just tested your PR, and it seems it does not support sprite frames in the particles: [video](https://gfycat.com/pl/LiveEnormousIcefish)

**Comment by JFonS** [comment]
@lekoder Check out my last PR, I fixed the particles animation calculation.

You still need to assign a CanvasItemMaterial and enable "ParticlesAnimation" for it to work. This was the whole point of the original PR.

I know it's a breaking change but compatibility from 3.0 to 3.1 isn't supposed to be 100%

**Comment by lekoder** [comment]
@JFonS understood, I'll give it a go.
