### ISSUE TITLE
(GLES2) Resizing viewport flickers in "clear color" environment

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#23652]
**Godot version:**

c3023e8

**OS/device including version:**

Manjaro x86_64
```
OpenGL ES 2.0 Renderer: Mesa DRI Intel(R) Haswell
```

**Issue description:**

Resizing 3D viewport in GLES2 and clear color environment will cause the background to flicker.

**Steps to reproduce:**
1. Switch to GLES2
2. Set default environment to "Clear color"
3. Open 3D editor
4. Resize the viewport

![peek 2018-11-11 19-01](https://user-images.githubusercontent.com/43379543/48312748-19a0af80-e5e6-11e8-833b-fef3f74d403e.gif)

**Comment by TheBrunoMiguel** [comment]
I will be atempting to solve this issue soon

**Comment by clayjohn** [comment]
Not reproducible in 3.1.1 or current master, it must have been fixed
