### ISSUE TITLE
Particles2D not displayed

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#23662]
**Godot version:**
3.1 d16ce4a8e

**OS/device including version:**
Windows 10

**Issue description:**
Particles2D in existing project not displayed at all. Particles2D added after loading the project are one-pixel in size.

**Steps to reproduce:**
Load existing project with Particles2D.

**Minimal reproduction project:**
[Github repo](https://github.com/lekoder/godot-issue-paralax-particles)

**Comment by JFonS** [comment]
See #23647

**Comment by akien-mga** [comment]
Duplicate of #23647 indeed.
