### ISSUE TITLE
Safe lines become unsafe when organized in multiple lines

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#23667]
**Godot version:**
baa8678

**Issue description:**
A line of code considered safe:
`Class.do_stuff(arg1, arg2)`

If organized into multiple lines, the subsequent lines are identified as non safe:
```
Class.do_stuff(
	arg1, arg2)
```

@vnen, could you take a look at this?

**Comment by YeldhamDev** [comment]
@vnen, if you don't mind.

**Comment by KoBeWi** [comment]
Seems fixed in 4.0
