### ISSUE TITLE
Inspector Does Not Set Exported Variables Sometimes

### ISSUE THREAD

**Issue by selfReferentialName** [godotengine/godot#23666]
**Godot version:**
3.1 alpha 2

**OS/device including version:**
Arch Linux with i3wm, AMD processor, and nVidia graphics

**Issue description:**
Setting script variables (the stuff from GDscript export commands) with the GUI is often unreliable (often will not work at all, sometimes it works perfectly). Sometimes fiddling around (e.g. messing with what it is initialized to) will help, sometimes not. Often, if the variable has not been set before, there will be a null de-reference error. There appears to be no pattern with what kind of variables have problems. This did not happen with the 3.0 release.

**Steps to reproduce:**
Make a script that exports a variable. Set the variable with the inspector. Run.

**Minimal reproduction project:**
I'll get one ready later today.

**Comment by kubecz3k** [comment]
Would be great to have that reproduction project and more precise reproduction steps if possible

**Comment by akien-mga** [comment]
There have been various fixes for similar issues recently, and no project to test against in this report, so assuming fixed.

Please comment if you can still reproduce it in the current master branch.
