### ISSUE TITLE
Export path label should have FS browse button, also spams signal error

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#23663]
**Godot version:**
c3023e84

**OS/device including version:**
Mageia 7 x86_64

**Issue description:**
Editing the new "Export Path:" property in the `ProjectExportDialog` has two issues:
- It's a plain `Label` with no browse icon, so the path has to be typed manually. There's a type hint that can be used to get a FS browse button (see e.g. Inspector or ProjectSettings).
- It spams this error on edit:
```
ERROR: emit_signal: Error calling method from signal 'text_changed': 'ProjectExportDialog::_export_path_changed': Method not found.
   At: core/object.cpp:1241.
```

CC @marcelofg55 

**Steps to reproduce:**
- Add export preset
- Try to edit export path

**Minimal reproduction project:**
Likely does it with any project, but I saw it on the MRP from #23650.

**Comment by akien-mga** [comment]
BTW, even after editing this path manually, it's not used when clicking "Export Project".

**Comment by akien-mga** [comment]
The error spam is fixed by #23671.

Adding a browse button would still be nice, but only if the manually defined path is then used for "Export Project" as default path. Changing to enhancement.

**Comment by marcelofg55** [comment]
After #23671 the path should be used by default when clicking on "Export Project".

**Comment by akien-mga** [comment]
To get the FS browse button, usually properties are declared with `PROPERTY_HINT_GLOBAL_FILE`. This `export_path` is not registered as a proper (maybe it could be though, like the custom export templates?), but it could maybe use `EditorPropertyPath` instead of `LineEdit`.
