### ISSUE TITLE
Using stop_on_slope with move_and_slide will cause is_on_floor to return wrong results.

### ISSUE THREAD

**Issue by DualMatrix** [godotengine/godot#23675]
**Godot version:**
3.1 Alpha 2

**OS/device including version:**
Window 10

**Issue description:**
`is_on_floor` of a KinematicBody2D will be set to true too early when `stop_on_slope` is used with `move_and_slide` for a body that is falling down. This is a really annoying bug since it prevents you from using either `stop_on_slope` or 'is_on_floor' when implementing a body that is falling down.

You can see the issue here: A body was falling down until `is_on_floor` returned true and these are the results.

![stop_slope](https://user-images.githubusercontent.com/7482073/48379568-dd984800-e6d4-11e8-9111-36618fb471de.png)

You can see that the body using `stop_on_slope` stopped too early.

**Steps to reproduce:**

Create a KinematicBody2D with this script:

extends KinematicBody2D

func _physics_process(delta):
	if(not is_on_floor()):
		move_and_slide(Vector2(0,64 * 4),Vector2(0,-1), true, true)

And place a StaticBody2D a bit under it. Watch it stop before actually colliding with it.

**Minimal reproduction project:**
[StopSlope.zip](https://github.com/godotengine/godot/files/2573934/StopSlope.zip)

**Comment by kubecz3k** [comment]
related to #21595

**Comment by DualMatrix** [comment]
BTW the reproduction project doesn't work  properly anymore on current master because the order of the move_and_slide params has change so you have to remove the infinite_inertia argument to make it work.
