### ISSUE TITLE
iOS Admob crash -Multiple locks on web thread not allowed

### ISSUE THREAD

**Issue by zettyfactory** [godotengine/godot#23681]
**Godot version:**
3.0.6

**OS/device including version:**
iOS

**Issue description:**

Android / iOS admob plugin
https://github.com/kloder-games/godot-admob

Everything works well in android.
However, iOS has problems.
For example, an error occurs after Reward Video is terminated.

2018-11-13 04:30:20.350877+0900 hoonword[4062:184752] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Speaker (type: Speaker)
2018-11-13 04:30:20.374741+0900 hoonword[4062:185038] void _WebThreadLock(), 0x10c2ef040: Multiple locks on web thread not allowed! Please file a bug. Crashing now...
(lldb)

I am struggling with this problem for a few days, but I am not an iOS developer, so it is difficult. I would be very grateful if you gave me the answer.

**Comment by akien-mga** [comment]
Indeed, I prefer that it gets debugged on the godot-admob repo (there's an issue for it there: kloder-games/godot-admob#53). If it turns out to be a bug in Godot's iOS platform, this issue can then be reopened/a new issue can be opened with more specific details on what causes the error in Godot.

**Comment by zettyfactory** [comment]
I also asked the module developer, but I have not heard the answer yet. What bugs? Where should I fix it?

**Comment by zettyfactory** [comment]
I also asked the module developer, but I have not heard the answer yet. What bugs? Where should I fix it?

**Comment by akien-mga** [comment]
You just asked a few hours ago, give them some time :) I'm sure the module developer can help debug it further. Then if you identify a Godot bug together, we can move the discussion here.

**Comment by zettyfactory** [comment]
Thank you. I thought you already knew the answer to the problem. I will do my best to solve the problem.
