### ISSUE TITLE
Problem with TimeSeek blend.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#2368]
TimeSeek blend seems not working properly. 
Cause I am unable to describe this I made a repo with my test project.
https://github.com/kakoeimon/third
Press right mouse button to get in the aiming pos and then move up the mouse to see that the animation is wrong.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch? I think there were fixes made to TimeSeek around 2.0 - early 2.1 days.

**Comment by bojidar-bg** [comment]
Bump.

**Comment by KoBeWi** [comment]
I think that with the new AnimationTree in 3.1 we can assume this is definitely fixed.
