### ISSUE TITLE
Microphone usage required on iOS and macOS, requires NSMicrophoneUsageDescription to be keyed in plist

### ISSUE THREAD

**Issue by tomoprime** [godotengine/godot#23682]
Godot is attempting to access the microphone on the device when the project isn't in need of it. My setup is using MacOS High Sierra to run XCode 10.1 for iOS 12 support.

Issue tested using Godot 3.1 Alpha 2 (non mono version) with matching templates installed. I haven't tested elsewhere to see if it's a common problem on say Godot 3.0 or any mono builds yet. 

Steps are to Export a simple project to iOS and Run it live on the device from XCode. _Note you may need to add the StoreKit framework to the linker if you go through the Auto manage signing toggle loop of disabling IAP and Notifications from the Capabilities section in XCode to assign your provisioning profile._

When attempting to run Godot on Device in this case an iPhone 6, XCode will quickly report a crash as no value was set for NSMicrophoneUsageDescription was set in the PList.

`2018-11-12 22:45:28.546782-0500 YOUR-GAME [669:85574] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.`

_Note if you end up adding the key to your plist then push it to your device, removing the key again will not allow the error to persist (no privacy prompt). You will have to rename the bundle identifier (myapp2) to test microphone prompt on the same device again regardless of your answer. Even deleting the app from the device will not reset the test case history. Otherwise if you don't add the key to the plist you can test over and over._

More details may follow in the forums. 
https://godotdevelopers.org/forum/discussion/20217/bug-why-is-godot-3-1-ios-builds-requiring-the-microphone-permission-key-set-in-the-plist#latest

**Comment by bruvzg** [comment]
This is relevant for macOS Mojave as well.

All macOS exports are showing `"xxx" would like to access the microphone. [Don't Allow] [OK]` popup on the first start.

**Comment by akien-mga** [comment]
We likely need a way to make this optional (opt-in on export), and adapt the plist accordingly (as done for Android manifests).

CC @marcelofg55.

**Comment by bruvzg** [comment]
`NSMicrophoneUsageDescription` is not controlling permissions, it only defines custom message displayed in the popup. On iOS it's required on macOS it's not, but popup will be shown anyway (with default message) as soon as CoreAudio input interface is initialized (probably in [capture_init()](https://github.com/godotengine/godot/blob/master/drivers/coreaudio/audio_driver_coreaudio.cpp#L351) function).

Changing `Info.plist` on export, like #20041 do for android, won't help. Audio input code itself should be disabled if it is not used.

![min_warn](https://user-images.githubusercontent.com/7645683/48401886-ddc73080-e732-11e8-84b5-5087278acd17.png)

**Comment by bruvzg** [comment]
> Note if you end up adding the key to your plist then push it to your device, removing the key again will not allow the error to persist (no privacy prompt).

You can reset privacy settings on both iOS and macOS to test it again - [Resetting Privacy Settings in iOS and macOS
](https://developer.apple.com/library/archive/qa/qa1906/_index.html)

**Comment by tomoprime** [comment]
> You can reset privacy settings on both iOS and macOS to test it again - [Resetting Privacy Settings in iOS and macOS](https://developer.apple.com/library/archive/qa/qa1906/_index.html)

That will reset location and privacy settings for all services on your device. That is helpful but may not be desirable in all cases.

> We likely need a way to make this optional (opt-in on export), and adapt the plist accordingly (as done for Android manifests).

Why complicate the export further? GoDot is forcing microphone access on macOS and iOS devices when it may not be needed. Using the word requires twice in the title isn't very clear.

I had listed some feedback from the forum I'm sorry if it added to any confusion.
https://godotdevelopers.org/forum/discussion/20217/bug-why-is-godot-3-1-ios-builds-requiring-the-microphone-permission-key-set-in-the-plist#latest

**Comment by akien-mga** [comment]
> Why complicate the export further? GoDot is forcing microphone access on macOS and iOS devices when it may not be needed.

Well you're contradictory :) If a feature may not be needed, but may also be needed, we do need a way to configure whether the game wants it...

**Comment by marcelofg55** [comment]
I'll check if we can only initialize the Microphone code when it's really being used (when `capture_start` is called). I tried this last time I worked on CoreAudio mic code and it didn't worked but I'll give it another try.

**Comment by tomoprime** [comment]
> Well you're contradictory :) If a feature may not be needed, but may also be needed, we do need a way to configure whether the game wants it...

Apple added a feature (since iOS 10?) to alert users when privacy is being accessed. By the same token if a 3rd party library (Godot) accesses that same area it alerts the developer with a crash. So lets only use it when we need to use it gets a bit tricky.

**Comment by marcelofg55** [comment]
I've been trying but if I initialize the Microphone only when `capture_start` is called the Microphone code doesn't works on all devices.

@akien-mga @bruvzg Maybe we could implement a Feature tag for this? Like `audio_input` and only enable the Microphone code if that tag is present?

**Comment by tomoprime** [comment]
Where abouts are you initializing the capture inside the code base?

**Comment by marcelofg55** [comment]
> Where abouts are you initializing the capture inside the code base?

Capture code is initialized in `AudioDriverCoreAudio::capture_init()` which is called by `AudioDriverCoreAudio::init()`, this happens when Godot is initializing the audio code.

**Comment by BertrandBordage** [comment]
The MacOS export still requests a microphone permission, even on games without sound and where `audio/driver/enable_input` is disabled.

**Comment by akien-mga** [comment]
Please open a new issue, this was closed 6 years ago.
