### ISSUE TITLE
TabContainer title does not update when changed

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23696]
Godot 3.0.6
Godot 3.1 alpha2
Windows 10 64 bits

When I call `TabContainer.set_tab_title(index, title)`, the tab doesn't update its title, unless I click directly on it.

Reproduction steps:
1) Create a TabContainer, put a TextEdit inside it
2) Create a button with a script on it that changes the title of the first tab to a random title when clicked
3) Launch the scene, click on the button: notice the tab title doesn't change, which is unexpected.
4) Click directly on the tab title: notice it updates as you do so.

Project:
[TabContainerTitle.zip](https://github.com/godotengine/godot/files/2578734/TabContainerTitle.zip)

Edit: workaround is to call `update()`.

**Comment by KoBeWi** [comment]
Fixed in 3.2
