### ISSUE TITLE
Shader hintcolor initialization not showing in shaderparam

### ISSUE THREAD

**Issue by scottkunkel** [godotengine/godot#23698]
**Godot version:**

3.1-Alpha

**OS/device including version:**

Win10 Intel GPU

**Issue description:**

Shader hintcolor not showing in editor

**Steps to reproduce:**
shader_type canvas_item;

uniform vec4 color_1 : hint_color = vec4(255, 255, 255, 255);

Editor color is black

**Minimal reproduction project:**

**Comment by CowThing** [comment]
This was meant to be fixed in #17533
But setting a default color isn't working anymore. Setting a default value for hint_range still seems to work fine.

**Comment by akien-mga** [comment]
CC @JFonS

**Comment by JFonS** [comment]
I think I know how to fix this, will try when I get some free time.
