### ISSUE TITLE
TextEdit inside a TabContainer doesn't show the correct cursor on mouse over

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23697]
Godot 3.1 alpha 2
Windows 10 64 bits

When a TextEdit is placed inside a TabContainer, moving the mouse over it doesn't show the text edition cursor. If let alone with a simple Control parent, the correct cursor is shown.

Reproduction steps:
1) Create a TabContainer
2) Put a TextEdit inside
3) Create a TextEdit outside as sibling of the TabContainer
4) Launch the scene: move the mouse over the TextEdit inside the tab container: notice the mouse cursor doesn't change. It doesn't change either if you click it to type text.
5) Move the mouse over the TextEdit outside of the container: notice it shows the correct cursor.

Does not reproduce in 3.0.6.

Project:
[TextEditCursor.zip](https://github.com/godotengine/godot/files/2578772/TextEditCursor.zip)

**Comment by tom-jk** [comment]
Testing MRP on linux mint 18.3.

The TextEdit inside the TabContainer has mouse -> default cursor shape set to Arrow. I think this accounts for the problem.

**3.1.alpha2, 3.2.3.beta1**
The cursor correctly stays an arrow.
Setting default shape back to IBeam, the cursor correctly changes to IBeam.
Moving the node out of the TabContainer and into Control makes no difference.

**3.0.6.stable**
The cursor turns into an IBeam, ignoring the selected default cursor shape.
Moving the node out of the TabContainer and into Control makes no difference.

There might be a windows-only bug here, elsewise I guess this report was just made in error.

**Comment by akien-mga** [comment]
Closing as per above comment.
