### ISSUE TITLE
Creating Viewport Texture via new resource panel show error  Condition ' !vp ' is true. returned: 0

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23706]
**Godot version:**
3.1 37c5aa1

**OS/device including version:**
Windows 10 

**Issue description:**
When I trying to add new viewport via new resource,  this error occurs:
``` 
ERROR: get_height: Condition ' !vp ' is true. returned: 0
   At: scene/main/viewport.cpp:108
ERROR: get_width: Condition ' !vp ' is true. returned: 0
   At: scene/main/viewport.cpp:103
ERROR: get_data: Condition ' !vp ' is true. returned: Ref<Image>()
   At: scene/main/viewport.cpp:128
```

**Steps to reproduce:**
https://streamable.com/1l0ly

**Comment by clayjohn** [comment]
I don't think ViewportTextures are meant to be created this way. My understanding is that they should always come from a Viewport. In this case the error you are getting seems correct, you have created a ViewportTexture without a viewport and so the editor properly shows you errors.
