### ISSUE TITLE
MenuItem toolbar tool could use an option for radio check items.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#23700]
3.1 Alpha 2

@groud This editor for MenuItems is quite nice, but I think it is missing the option to make standard checkboxes into radio options.  `PopupMenu.add_radio_check_item()`

Maybe an additional option under "Checkable" to convert them to radio checks?

![image](https://user-images.githubusercontent.com/13004169/48462090-6e5b4a80-e7df-11e8-856d-5e7d74c6538d.png)

**Comment by avencherus** [comment]
Also, just discovered checkable separators.  XD

**Comment by KoBeWi** [comment]
This seems to exist since 3.1 stable
![image](https://user-images.githubusercontent.com/2223172/63770807-389ed280-c8d6-11e9-9cc1-c16df01a8b45.png)

**Comment by avencherus** [comment]
Oh you're right.  It looks like it was added a year and half ago bf14a6deffe4c9b74920080851f7e4e273f66116, but wasn't appearing.  Was there some other goal in mind or did he not check to see if this was working?  I wonder.

And then fixed in e4f1b995cc2989a2d039cfd2b006e93653569892.  Thanks for looking into it @akien-mga 👍
