### ISSUE TITLE
Cannot overwrite tilesets after saving over them.

### ISSUE THREAD

**Issue by Exoaria** [godotengine/godot#2370]
For some reason if you save over an existing tileset Godot remembers the previous one in its cache if it had the same name. This requires you to save a completely unique tileset every time that you want to make a change to it.

**Comment by kakoeimon** [comment]
When you Convert to => Tileset in the Export Tileset window at the bottom there is a button that says "Merge with existing" and is on by default. Turn this to off and you are done.
