### ISSUE TITLE
CanvasItem.draw_rect() culling problems

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#23711]
_bugsquad edit:_ The root of the problem was recognized in this comment: https://github.com/godotengine/godot/issues/23711#issuecomment-439017673

-------
**Godot version:**
3.1 alpha 2

**OS/device including version:**
Windows 10

**Issue description:**
Take a look at the gif below first:

![draw_rect](https://user-images.githubusercontent.com/26509794/48514256-3e9f5780-e85e-11e8-95bb-261d8f0020c6.gif)

So each box consists of 2 rectangles that are drawn using `draw_rect()`. However when I move the camera so they are positioned at either top or left edge, if one of those rects is outside, both of them disappear. The rects can even be separated, doesn't matter. This even happened at the rightmost edge of screen.

On Discord we suspected it's because of culling. But it doesn't make sense to cull anything because there are visible parts on the screen.

I've tried drawing a lot of rects and got mixed results, but I was unable to understand how exactly it works. Feel free to play around in the minimal reproduction project.

**Minimal reproduction project:**
[draw_rect invisible.zip](https://github.com/godotengine/godot/files/2582779/draw_rect.invisible.zip)

**Comment by kubecz3k** [comment]
This happens because there is no way to define a size of Node2D (it's just a point, without width or height). 
If you convert your node to for example to Control you will have correct results when you define the width and height for this control (both Node2D and Control are extending CanvasItem so you don't need to change the code).

**Comment by wingedadventurer** [comment]
@kubecz3k Will it work if I scale the Control node?

**Comment by kubecz3k** [comment]
Actually, I think maybe it is a good idea to give some way to define a size for culling inside the CanvasItem (so reopening).

**Comment by kubecz3k** [comment]
@wingedadventurer I think the scale will be taken into account, but you for sure will need to define some width and height first (if the size is 0 it will still be 0 after scaling)

**Comment by kubecz3k** [comment]
@wingedadventurer another node which you can use is Sprite (if you for some reason don't want to Control ones). Sprite will have the size of the texture that is assigned to it, plus it will take scale into account (so you can attach small transparent texture and regulate the culling with the scale).

**Comment by bojidar-bg** [comment]
This is either a bug or a misuse of Rect2.
The sample code contains this:
```gdscript
var left = Rect2(Vector2(-16, -16), Vector2(16, 32))
var right = Rect2(Vector2(16, -16), Vector2(-16, 32))
```
Note that the the `Rect2` takes `(position, size)`, and thus `right` is a Rect2 with negative size.
Printing `left.merge(right)` results in `(-16, -16, 16, 32)`, that is, it thinks that both rects together have a size of `16, 32`, which is wrong.
Printing `left.merge(right.abs())` results in `(-16, -16, 32, 32)`, which is correct, and additionally, passing `right.abs()` to `draw_rect` results in proper clipping.

So, either `Rect2.merge()` should be fixed to work with negative sizes, or the VisualServer should run rects through `abs` before merging them, or this should be documented in `draw_rect`'s documentation.

**Comment by wingedadventurer** [comment]
What @bojidar-bg says is indeed true, making Rect2's size positive doesn't result in said bug anymore. Thanks!

The reason I had negative rect size is because I was drawing a door that opens by splitting. Therefore each door wing had variable width. For consistency in the code, I drew each wing from the edges, which works fine for the first one, but gives negative rect for second one.

Glad we sorted this out. 😄

**Comment by akien-mga** [comment]
Related to #25829.
