### ISSUE TITLE
RayCast to CSGShape get_collider() return null

### ISSUE THREAD

**Issue by Kinwailo** [godotengine/godot#23712]
**Godot version:**
3.1 alpha 2

**Issue description:**
When RayCast hit a CSGShape with "Use collision", is_colliding() return true, but get_collider() return null.

**Comment by tkurby** [comment]
Confirmed with master at commit 35aa3301d760d3f548c2ee432f5e8f1977ec9c05.
Attached short test project to reproduce and with functioning static body collider to double-check.

It seems that something like this can happen when the result object of a ray intersection does not return a valid instance_id.
The condition that fails to fill the collider_id in such a case is on this line:
 https://github.com/godotengine/godot/blob/14cf450b0da4102a59d8890d931e38104266d96a/servers/physics/space_sw.cpp#L165

As I am not to familiar with the engine I am not able to easily debug further.

[raycast_on_csg_test.zip](https://github.com/godotengine/godot/files/2585781/raycast_on_csg_test.zip)
