### ISSUE TITLE
Option to compile Godot without audio

### ISSUE THREAD

**Issue by CZHeron** [godotengine/godot#23710]
There is a bug/feature in Godot audio that causes noticeable audio input latency which is not desired in real time analysis. Because life is too short to understand Godot's audio design and bend it to my needs, I decided to implement my own audio in GDNative project. However, there is a conflict between mine and Godot's implementation when I use WASAPI or ASIO driver. 

I believe that this is not the only use case for not using Godot's audio, so can we have the option to compile Godot without entire audio system?

**Comment by YeldhamDev** [comment]
Another use would be when making programs that don't need audio. Godot has already been used to make a particle editor, and even a text editor.

**Comment by marcelofg55** [comment]
Instead of compiling Godot without the audio system you could just set the project to use the Dummy audio driver.

**Comment by CZHeron** [comment]
I tried a simple RtAudio playback in C++ project, but it has the similar behavior as before. ASIO seems good, but WASAPI won't even run. At least all printed errors disappeared.

**Comment by marcelofg55** [comment]
> I tried a simple RtAudio playback in C++ project, but it has the similar behavior as before. ASIO seems good, but WASAPI won't even run. At least all printed errors disappeared.

So what's the similar behavior you mention?
If you're using a GDNative project for your RtAudio playback then Godot has nothing to do with its problems.

**Comment by CZHeron** [comment]
> So what's the similar behavior you mention?

About the audio under WASAPI that won't run.

I've finally solved it. I tried to run it on other computers and it works flawlessly. However, on my computer the audio device randomly created a "ghost device". It was solved by new firmware. 
Thank you for advice.
