### ISSUE TITLE
Label.get_total_character_count returns too high value

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot#23720]
**Godot version:** 3.0.6

**OS/device including version:** Arch Linux

**Issue description:**

The `get_total_character_count()` function on `Label` returns strange values. For the empty string, it return 1. For a string of one non-space character, it returns 3. For increasingly longer strings, it seems increasingly far off the mark.

It's not clear from the documentation why there should ever be a difference between `get_total_character_count()` ("Returns the total length of the text.") and `len(text)`. So at the very least there's a doc bug here.

**Steps to reproduce:**

Create a scene with a `Label` at the root. Attach the following script:

```
extends Label
func _ready():
	for t in ["", " ", "x", "hello", "hello world", "Hello world!", "Some longer phrase. With punctuation and stuff."]:
		text = t
		print("text = %-14s     len(text) = %2d  get_total_character_count() = %2d" %
			['"%s"' % text, len(text), get_total_character_count()])
```

Run the scene and observe the output:

```
text = ""                 len(text) =  0  get_total_character_count() =  1
text = " "                len(text) =  1  get_total_character_count() =  2
text = "x"                len(text) =  1  get_total_character_count() =  3
text = "hello"            len(text) =  5  get_total_character_count() =  7
text = "hello world"      len(text) = 11  get_total_character_count() = 12
text = "Hello world!"     len(text) = 12  get_total_character_count() = 13
text = "Some longer phrase. With punctuation and stuff."     len(text) = 47  get_total_character_count() = 43
```

**Related issues:**

#874 has @reduz saying he fixed it very hard. But that was probably back in the 2.0 days.

**Comment by akien-mga** [comment]
> Document that get_total_character_count only includes "printable" characters.

What's the use case for knowing the number of non-space characters though? i.e. when would one use the (fixed) `get_total_character_count()` instead of just `text.length()`?

**Comment by ttencate** [comment]
It's what `visible_characters` is using to animate the text appearing gradually.
