### ISSUE TITLE
Godot Snap distribution can't export to Android

### ISSUE THREAD

**Issue by Mandriausias** [godotengine/godot#23725]
**Godot version:**

Godot v3.0.6

**OS/device including version:**

Ubuntu v18.04.01
OpenJDK 8

**Issue description:**

The snap store Godot version by using Godot file explorer can't access the root folder therefore you can't access the "jarsigner" file. If you enter the path by hand it still says "OpenJDK 6 jarsigner not configured in editor settings".

The quick fix is to download the Godot from official website because that version has an access to the root folder. But it has no icon and you can't add it to favourites bar :(
 
P.S. I was trying to solve an issue but didn't fount the solution anywhere. The closest one was with Godot v3.0.5 suggesting to solve by installing 3.0.6 version and OpenJDK 8, but I've already had proper versions.

**Steps to reproduce:**
Install OpenJDK 8 > Install Godot > Try to set jarsigner path> in export options check if there is  "OpenJDK 6 jarsigner not configured in editor settings" error message.

**Minimal reproduction project:**

Install OpenJDK 8 > Install Godot > Try to set jarsigner path> in export options check if there is  "OpenJDK 6 jarsigner not configured in editor settings" error message.

**Comment by akien-mga** [comment]
Godot needs access to `/usr/bin/jarsigner` if you want to use a system-installed OpenJDK, so you should report this to the Snap package maintainers. If the snap prevents you access to `/usr` but still exposes `jarsigner` in the PATH, you could try to set only `jarsigner` as path for the option.

**Comment by akien-mga** [comment]
I'm not sure what's the proper location to report issues with a given snap in the snapcraft ecosystem. CC @popey who did the original Godot snap: https://forum.snapcraft.io/t/godot-engine-call-for-testing/4997

**Comment by michaellee8** [comment]
@popey I guess we need your help to provide the file system access of your snaps. Can you set classic confinement for it?

**Comment by michaellee8** [comment]
The snap is just unusable right now

**Comment by popey** [comment]
Thanks for the ping @michaellee8. Sorry it's not working as you'd expect, I'll take a look!

**Comment by michaellee8** [comment]
@popey it seems that there are no such permission to access /usr/lib for a snap, I tried devmode but I still didn't work, maybe you can try with classic confinement?

**Comment by akien-mga** [comment]
To provide some context on what system access Godot needs:
- To export to Android, we need OpenJDK (or Oracle JDK)'s `jarsigner`, as well as `adb` (either from the SDK or standalone packaged version). So users need to be able to access `/usr/bin/jarsigner` and `/usr/bin/adb` (they provide the path themselves in EditorSettings), or any arbitrary path where they might have those installed (e.g. `/home/foo/Dev/android-sdk/platform-tools/adb`).
- To export to Windows, users can optionally use `rcedit.exe` that they download themselves, and which, being a Windows application, needs Wine on Linux. So they'd need access to `/usr/bin/wine` and also the possibility to access a random, user-readable path (e.g. `/home/foo/Dev/rcedit.exe`). This is not a mandatory feature (it's used to embed the game icon and PE metadata in the .exe), but would be nice to have when using the snap too.

**Comment by davidholiday** [comment]
I'm experiencing this issue as well - I have both jarsigner and adb installed to /usr/bin/ and can access both from the command line. Unfortunately, even when I manually put the paths into the editor settings Godot doesn't see the files and therefore won't permit exporting to Android.

**Comment by popey** [comment]
This should now be fixed with the newer releases. We switched to classic confinement, so you'll need to `snap refresh godot --classic --stable` to get the new update as the Snap Store don't allow you to go from strict to classic without explicitly specifying.

**Comment by Elyukeyey** [comment]
Late to the party, but had the same issue. the --classic --stable version solves the issue.

**Comment by Calinou** [comment]
@Elyukeyey Thanks for confirming it :slightly_smiling_face: 

I'll close this issue, as it's not related to an official Godot distribution. Please report Snap-related issues on https://forum.snapcraft.io/t/godot-engine-call-for-testing/4997.
