### ISSUE TITLE
Structure being passed to GDScript function works fine in GDScript, but does not return with changes.

### ISSUE THREAD

**Issue by PeaceSells50** [godotengine/godot#2372]
The pseudo code is in PasteBin. http://pastebin.com/3rZbQagx
The actual problem is illustrated by the C++ function DoTask.
I would expect info.mTest to have the value set by the GDScript function call.

**Comment by akien-mga** [comment]
Probably a silly question, but did you check that ```get_script_instance()``` evaluates as ```true```?

**Comment by reduz** [comment]
This is not a bug, simply don't put objects in the stack, they need to be initialized with memnew() macro or else they won't work.

**Comment by reduz** [comment]
and deleted with memdelete(obj)
