### ISSUE TITLE
"Grabber Area" in slider theme might be badly named

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23733]
Godot 3.0.6

I spent some time wondering why the left part of my slider's background was still drawn using the default theme, even when I set the `Slider` to a background texture.
Turns out, if you also set the style for `Grabber Area`, it actually fills the left part of the slider... which has little to do with the "Grabber".

![image](https://user-images.githubusercontent.com/1311555/48589218-90b1ad00-e932-11e8-98f0-1c4b7abc0ee9.png)

**Comment by LightningAA** [comment]
Can this be closed now that it's part of #16863?
