### ISSUE TITLE
Key icon for animation and reset value icon overlap in inspector

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#23736]
**Godot version:**
3.1 (master)

**OS/device including version:**
ubuntu 18.04

**Issue description:**
When trying to animate a Camera the create key icon overlaps the reset value icon in the inspector. This makes it impossible to create animation keys.

![screenshot 2018-11-16 13 52 55](https://user-images.githubusercontent.com/13980/48595143-99909600-e9a7-11e8-93d7-f1085b39e6e3.png)

**Comment by KoBeWi** [comment]
This is already fixed.

**Comment by bojidar-bg** [comment]
Closing as per the above comment.
