### ISSUE TITLE
All keys released when any key of group released in action_is_pressed

### ISSUE THREAD

**Issue by mateusfccp** [godotengine/godot#23749]
**Godot version:**
v3.1.alpha.custom_build.37c5aa1

**OS/device including version:**
Arch Linux up-to-date
Kernel 4.18.16-arch1-1-ARCH

**Issue description:**
When checking for input press with `Input.is_action_pressed` and the action has a group of keys, if you press more than one of the key of the group, it will return `true`. However, if you release only one of them, the statement will return `false`, as if all of them has been released.

**Steps to reproduce:**
1. Open the **Minimal reproduction project** below.
2. Run the main scene.
3. Press W and keep it pressed. Both `W` and `Any` labels will be shown.
4. Press S and keep it pressed, without releasing W. `W`, `S` and `Any` labels will be visible.
5. Release W while keeping S pressed. Instead of hiding `W` label and keeping `S` and `Any` visible, all labels will be hidden, as if all keys of the group has been released.

**Minimal reproduction project:**
[Issue.zip](https://github.com/godotengine/godot/files/2589937/Issue.zip)

**Comment by Calinou** [comment]
I can reproduce this on commit https://github.com/godotengine/godot/commit/12482bf8840ce2fa84d6eea7999628be426cba8d.

**Comment by amkk** [comment]
@akien-mga 
Please Investigate this issue before 3.2.
This is a really long standing bug.
Here is a detail why this bug is critical.#31798
Thank you.

**Comment by Calinou** [comment]
@amkk Since we're very close to release, we can't afford to fix a bug that may introduce regressions in the input handling system. We can look into fixing it for a point release like 3.2.1 though.

**Comment by amkk** [comment]
OK,Thank you.

**Comment by KoBeWi** [comment]
See #30888
