### ISSUE TITLE
Viewport texture for viewport with a single Label is not displayed as intended

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot#23750]
**Godot version:**
3.0.6, 3.1

**OS/device including version:**
Windows 10/Acer Aspire E15

**Issue description:**
Label with text is not displayed correctly on Viewport texture

**Steps to reproduce:**
I wanted to create text plaque in 3D, which can be used, for example, to display some text info on the in-game PC 3D model's screen. Or maybe just some plaque with the text which can be easily changed at runtime.

To achieve this. I created the following scene:
![image](https://user-images.githubusercontent.com/7196697/48635070-52c78e00-e9f1-11e8-95ee-b6292badc385.png)
Label contains some text. Node 'plaque' is the MeshInstance with the material_override property set to the material, which Albedo texture is the Viewport texture. It works as intended in the editor:
![image](https://user-images.githubusercontent.com/7196697/48635213-c36eaa80-e9f1-11e8-9992-0de9602b1824.png)
but unfortunately, when the project is started, it does not work as intended:
![image](https://user-images.githubusercontent.com/7196697/48635266-e4cf9680-e9f1-11e8-997f-c666de43b9ad.png)
Moreover, if you close the project and re-open it, everything is broken in the editor too:
![image](https://user-images.githubusercontent.com/7196697/48635338-0e88bd80-e9f2-11e8-945e-7d8031742161.png)

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2590124/test.zip)

**Comment by Antokolos** [comment]
Oh, it seems that everything is almost correct :)
You just need to add the following script to the root node text_plaque:

extends Spatial

onready var plaque = $plaque
onready var viewport = $Viewport

func _ready():
	plaque.material_override.albedo_texture = viewport.get_texture()

When I do so, the text is displayed as intended, so the major part of this issue is gone.
There is, however, one minor issue left, when the project is reloaded, the viewport texture is shown as black color in the editor, just like on the last screenshot. When the project is started, however, all is good.
Is it really necessary to connect viewport texture programmatically in _ready?

**Comment by bojidar-bg** [comment]
Try to ensure that all resources containing the ViewportTexture as well as the ViewportTexture itself have `local_to_scene` ticked on.

**Comment by Antokolos** [comment]
@bojidar-bg , thank you very much, when I ticked local_to_scene, everything is fine now, even without connection via script!
I'll close this issue now.
