### ISSUE TITLE
Enums no longer declared in the current scope.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#23757]
**Godot version:**
Godot 3.1 e77afb8

**OS/device including version:**
Windows 10 64bit

**Issue description:**
In 3.1 alpha 2 the following script worked. But now it is saying that `TEAM_FRIENDLY` is not declared in the current scope.

```GDScript
extends Node

enum Teams {
	TEAM_FRIENDLY,
	TEAM_ENEMY,
	TEAM_NEUTRAL
}


func _ready():
	print(TEAM_FRIENDLY)

```

**Comment by merumelu** [comment]
See #23648.

**Comment by akien-mga** [comment]
That was done on purpose in #23648. Previously you could  easily have conflicts with e.g.
```
enum TeamsA {
    TEAM_FRIENDLY,
    TEAM_ENEMY,
    TEAM_NEUTRAL
}

enum TeamsB {
    TEAM_FRIENDLY
}

const TEAM_FRIENDLY = 2
```
Which is what?

Now you should simply do:
```
enum Teams {
    FRIENDLY,
    ENEMY,
    NEUTRAL
}

func _ready():
    print(Teams.FRIENDLY)
```

**Comment by CowThing** [comment]
Alright, thanks for the info.

**Comment by Seliniakolukos** [comment]
I have a similar issue, and I can't seem to fix it no matter what I try. This is the code.


extends Node2D

var noise = preload("res://Scripts/softnoise.gd")
var block = preload("res://Scripts/block.gd")


enum block_types {
	GRASS, DIRT, GRAVEL, STONE, ORE, WOOD, METAL, FLESH, PRIMARYORE  
}

var world_depth = 640
var Surface_height = 448
var chunk_width = 32

func _ready():
	var softnoise = noise.SoftNoise.new(38401823090453452341) #The Number here is the seed, remember that!
	for x in range(0,chunk_width):
		var y = floor(softnoise.openSimplex2D((get_global_transform().origin.x/32 + x)*.1,0)*Surface_height*.2)
		new_block(Vector2(x*32,y*32),GRASS) #the error is in this line
	pass
	
func new_block(pos, type):
	var new_block = block.instance()
	new_block.translate(pos)
	new_block.block_type = type
	add_child(new_block)

**Comment by akien-mga** [comment]
The answer is in my comment above. Use `block_types.GRASS`.
