### ISSUE TITLE
Freeze and errors when saving project with thousands of files

### ISSUE THREAD

**Issue by Faless** [godotengine/godot#23755]
**Godot version:**
master: 256bbd3561135c7886501a865be27cde3d26d47d

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When saving a scene in a project with thousands of files, the editor freezes in a loop.

Spamming: `Object was deleted while awaiting a callback`

And then:

```
TOTAL BYTES: 1048560
NULL count: 1
CALL : 8764
CALL _update_callback: 2
CALL _update_minimum_size: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
```

**Steps to reproduce:**
Create a project with ~4400 scenes.
Save one of them. Boom!

*NOTE*: In the game I'm testing, I only have ~900 files, but it still freezes when saving, with similar error (though it seems following other code paths). In the demo project, I usually regain control over the editor in about 15/20 seconds. In my game I waited 45 seconds with no luck.
The only way I found to workaround this is by increasing the message_queue_size_kb.
(should we increase the default? Should the editor use it's own specific setting)

**Minimal reproduction project:**
[manyfiles.tar.gz](https://github.com/godotengine/godot/files/2590799/manyfiles.tar.gz)

**Comment by akien-mga** [comment]
Should be fixed by #24194.
