### ISSUE TITLE
Errors when generating FileDialog thumbnails if GDScript files are present in the folder

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23753]
Godot 3.0.6
Godot 3.1 alpha 2
Windows 10 64 bits

I was going to set the default directory for the project manager, and I found out that the editor started showing errors like this:
```gdscript
ERROR: Failed loading resource: D:/PROJETS/INFO/GODOT/fsm_state.gd
   At: core/io/resource_loader.cpp:186
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: D:/PROJETS/INFO/GODOT/fsm_state.gd
          At: D:/PROJETS/INFO/GODOT/fsm - Copy.gd:2
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583
```
It turns out, Godot tries to load and compile GDScript files just to generate their thumbnail, even if the folder you are in is not even part of a project. I happened to have several random GDScript files here, which were just random code doodlings or whatever which are not loadable anyways.

I would suggest for Godot to not try to compile such files if the intention is just to make a thumbnail, because apparently it even succeeds generating it anyways.

Reproduction steps:
1) Pick a GDScript file which has preloads, syntax errors or incompatible code inside
2) Put that GDScript file into a folder which is not inside a Godot project
3) In the editor, open a File Dialog which usually shows thumbnails and allows to browse outside the project. Example: `FileSystem/Directories/Default Project Path`
4) Notice errors as the thumbnail gets generated

**Comment by KoBeWi** [comment]
Seems fixed in 4.0 (and possibly 3.3)

**Comment by Zylann** [comment]
Tried it again in Godot 3.4 beta3, it still happens.

**Comment by KoBeWi** [comment]
Weird. I actually tested in 4.0 first and the thumbnails generated without errors. Then in 3.3 there were no thumbnails (so no errors either).
