### ISSUE TITLE
Add support for *= operator for lvalue vec3 and rvalue mat3 in shading language

### ISSUE THREAD

**Issue by Aaron-Fleisher** [godotengine/godot#23761]
**Godot version:**
0afdc5c559520204987544d30560745dbf29a390

**OS/device including version:**
W10, 64-bit, GTX 960

**Issue description:**
I found this https://github.com/godotengine/godot/issues/10687 issue, but am not sure on its status and it was more than a year ago, so I figured I'd make a new topic.
The error code:
`invalid arguments to operator '*=' :vec3 and mat3`
when trying to multiply a `vec3` and `mat3` on line 6: (**pr *= mr;**)
```
// rays of a star
float ringRayNoise(vec3 ray,vec3 pos,float r,float size,mat3 mr,float anim){
	float b = dot(ray,pos);
	vec3 pr=ray*b-pos;
	float c=length(pr);
	pr *= mr;
	pr=normalize(pr); 
	float s=max(0.0,(1.0-size*abs(r-c)));
	float nd=noise4q(vec4(pr*1.0,-anim+c))*2.0;
	nd=pow(nd,2.0);
	float n=0.4;
	float ns=1.0;
	if (c>r) {
		n=noise4q(vec4(pr*10.0,-anim+c));
		ns=noise4q(vec4(pr*50.0,-anim*2.5+c*2.0))*2.0;
	}
	n=n*n*nd*ns;
	return pow(s,4.0)+s*s*n;
}
```

**Comment by akien-mga** [comment]
Is `vec3 *= mat3` supported in GLSL?

**Comment by Kanabenki** [comment]
According to the [specification](https://www.khronos.org/registry/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf), it seems it is (page 103 and 106).

I just tried it on a shader writing app and it works fine.
