### ISSUE TITLE
SCons: Incorrect $LIBSUFFIXES environment variable

### ISSUE THREAD

**Issue by SeleckyErik** [godotengine/godot#23769]
In `SConstruct`, both, static and dynamic libraries are set to be recognized as valid input to the linker. While this is correct on Linux, on Windows only static libraries can be linked directly - dynamic libraries are linked by linking against corresponding _Import Library_ which has a `.lib` extension - just as regular static library.

https://github.com/godotengine/godot/blob/9eb4b6d91a64661f8e2823a70f935c602f8a725a/SConstruct#L425-L431

**Comment by akien-mga** [comment]
Fixed by #23770.
