### ISSUE TITLE
Using inspector's 'instance new scene' dialog can be cumbersome in bigger projects

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#23765]
**Godot version:**
0afdc5c559520204987544d30560745dbf29a390

**OS/device including version:**
Kubuntu 18.04 

**Issue description:**
Since some time we have new 'instance scene dialog' in inspector. When user wants to instance a scene in a scene tree he will see a very similar dialog to the 'quick open scene' one. In older Godot we had 'file explorer' style dialog, with favorites and recent folders.
The way how new this behaves now makes it very hard for people who don't know perfectly how different scenes are named, especially if the project is big and couple developers are working on it. In the old scenario, each team member could favorite directories that he is using the most, check which folders he was using recently and travel through the project more naturally. 
I understand why this change was made, but I think the best way to allow such filtering would by extending the file dialog itself with search functionality.  
![newinstance](https://user-images.githubusercontent.com/6129594/48661808-45091b80-ea78-11e8-9f65-89f6038eb2ab.gif)
_my wife asked me to attach this gif :)_

**Comment by sketchyfun** [comment]
Yes, I personally can't stand this new dialog, it completely throws off my work flow. 
If we're going to keep it, we should at least have the option to go back to the regular file dialog.

**Comment by KoBeWi** [comment]
Is this still relevant with the new file system dock? It's easy to locate and drag file from there.

**Comment by KoBeWi** [comment]
Closing due to lack of update. If you feel like it's still not resolved, open a [proposal](https://github.com/godotengine/godot-proposals/).
