### ISSUE TITLE
Problem building target=release-debug tools=yes

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2376]
$ scons platform=x11 target=release-debug tools=yes
Enabling PulseAudio
scons: done reading SConscript files.
scons: Building targets ...
g++ -o tools/doc/doc_data.x11.tools.64.o -c -DFREETYPE_ENABLED -DOPENGL_ENABLED -DGLEW_ENABLED -DALSA_ENABLED -DPULSEAUDIO_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DGLES_OVER_GL -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -D_REENTRANT -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/x11 -I/usr/include/freetype2 -Itools/doc/vorbis tools/doc/doc_data.cpp
tools/doc/doc_data.cpp: In member function 'void DocData::generate(bool)':
tools/doc/doc_data.cpp:192:18: error: 'class MethodBind' has no member named 'get_return_type'
      if (m && m->get_return_type()!=StringName())
                  ^
tools/doc/doc_data.cpp:193:29: error: 'class MethodBind' has no member named 'get_return_type'
       method.return_type=m->get_return_type();
                             ^
^Cscons: *** [tools/doc/doc_data.x11.tools.64.o] Build interrupted.

**Comment by jjdicharry** [comment]
Try release_debug with an underscore:
scons platform=x11 target=release_debug tools=yes

**Comment by vnen** [comment]
Well, shouldn't it be `release_debug` (with underscore instead of dash)?

**Comment by akien-mga** [comment]
Indeed.
