### ISSUE TITLE
[Feature Request]Easy and flexible way to make sprite masks

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#23763]
**Issue description:**
Now I am making a card game. Each card has an irregular shape and a fading animation. Light2D as mask is inflexible.
Like what I find in Unity(use left two pictures to make the third one) :
![3](https://user-images.githubusercontent.com/10054853/48660659-359dc880-eaa0-11e8-826c-b5f2f5cf37d9.gif)

REF : https://docs.unity3d.com/2018.3/Documentation/Manual/class-SpriteMask.html

Feature Request:
1. Hide or reveal parts of a Sprite or group of Sprites.
2. Ensuring the mask is interacting with particular sprites. Or custom influencing range of a Sprite Mask.

**Comment by groud** [comment]
This is already possible and quite easy to do with shaders. I suggest to have a look to gdquests video about transition shaders : https://youtu.be/K9FBpJ2Ypb4

If you need any help please ask on the other community channels.

**Comment by zhagsenkk** [comment]
> This is a pretty easy effect to accomplish:
> [SpriteMask.zip](https://github.com/godotengine/godot/files/2591756/SpriteMask.zip)

Thanks for the help. But if there is a group of sprites to be cut off, how to do it?

**Comment by zhagsenkk** [comment]
"a group of sprites" means that a sprite with several children.

**Comment by groud** [comment]
Simply apply the same material to all child nodes, and compute the masking according to the screen position. But once again, ask in the [other community channels](https://godotengine.org/community), this is not the place to ask for support.

**Comment by BastiaanOlij** [comment]
What @groud said, just reuse the material. :)

**Comment by creikey** [comment]
This does not work when using different sprites with a multitude of materials @groud
