### ISSUE TITLE
Implement NodePath drag and drop in remote scene tree

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#23768]
Since the local and remote tab of the scene view are very similar I found myself wanting to drag a node path from the remote scene into my script, which of course does not work (yet).

**Comment by KoBeWi** [comment]
There's new "Copy Path" option for remote tree in 3.2, so implementing drag and drop is a combination of what local tree already does and that new option.

**Comment by Arunkumar1998BOM** [comment]
I will work on this,
I need the following:
1.) Steps to reproduce the issue
2.) References I can check to understand the drag&drop thing
3.) Files which reference the local and remote tabs (or its okay, ill figure it out myself)
4.) References I can take (if any issues addressing these files or functionality was pushed)

**Comment by KoBeWi** [comment]
Eh, I don't think you need reproduction project/steps here. Just read the OP.

As for references, here's the PR that implemented Copy Path for remote tree #28905

**Comment by Arunkumar1998BOM** [comment]
I am sorry, what I meant was, I exactly dont know how you can pull the node path and drop in remote scenetree node. I actually do not know where you can find node path and remote scenetree as I am new to the codebase as well as the editor and am learning. I can go through docs which will take lot of time. Instead, A snap of editor or steps would be useful.

**Comment by KoBeWi** [comment]
https://docs.godotengine.org/en/3.1/tutorials/debug/overview_of_debugging_tools.html#remote-in-scene-dock
This is where Remote scene tree is located. Looking at the PR I linked, the code might be in different file than the local scene tree, but drag and drop functionality should be the same. Just look for `get_drag_data` in `scene_tree_editor.cpp` and try to implement it for the other tree.
