### ISSUE TITLE
Font thumbnail is correctly shown in FileBrowser but is shown wrong when assigned to a DynamicFont

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23774]
Godot 3.1 alpha2

I added a font to my project, and the File Explorer shows a correct thumbnail for it.
I created a DynamicFont and dragged the font to it, and the inspector also shows a thumbnail on the property... however that thumbnail in particular is wrong. Aren't they supposed to use the same source of thumbnails??

![image](https://user-images.githubusercontent.com/1311555/48664890-ccb55100-ea9d-11e8-9bdb-6680ccfa887a.png)

Here is the font:
[upheavtt.zip](https://github.com/godotengine/godot/files/2592172/upheavtt.zip)

Note: I use that font for a long time and I know it's using distance field. There are open issues about this kind of font being blurry in Godot 3, but it's at least readable (it doesn't show squares like here).

**Comment by akien-mga** [comment]
See also #23123. Font previews seem to be quite broken currently.
