### ISSUE TITLE
Moving file to the same directory causes overwrite warning

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#23778]
**Godot version:**
3.1 alpha2

**Issue description:**
When you move the file to the same directory, it causes a warning to appear that the file already exists. It tends to trigger a lot when you try to click a file and accidentally drag it.

**Steps to reproduce:**
![screen_recorder_plus_video_2018_17_11_22_44_27](https://user-images.githubusercontent.com/2223172/48666075-dbf6c780-eaba-11e8-8101-1c4b2965bf45.gif)

**Comment by minilene** [comment]
Working on it.
