### ISSUE TITLE
Input.action_press() second parameter doesn´t have default value

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#23772]
**Godot version:**

9eb4b6d91a64661f8e2823a70f935c602f8a725a

**OS/device including version:**

win 7

**Issue description:**

Second parameter for Input.action_press was merged in https://github.com/godotengine/godot/commit/8c45282d21155009e5b239b8df610661409981e6
but this commit doesn´t include a default value nor a description in docs with expected values interval to pass. Actual games with action_press in code will fail because a second value is expected, and no info is provided to what to pass in there (I think that is float 0-1 but it should in the class documentation)

**Steps to reproduce:**

Use Input.action_press without pass second parameter.

**Comment by akien-mga** [comment]
CC @workless @groud

**Comment by workless** [comment]
@Ranoller @akien-mga 
Sorry, was the first commit, working on it

**Comment by groud** [comment]
> Sorry, was the first commit, working on it

I already did the PR: #23776 ^^

**Comment by workless** [comment]
@groud created https://github.com/godotengine/godot/pull/23777 :laughing:
