### ISSUE TITLE
Selecting node while moving mouse causes undoable position change

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#23779]
**Godot version:**
3.1 alpha2

**Issue description:**
When you try to select node and accidentally move mouse while doing so, the node will move for split second and stop (it's like it instantly applies cursor velocity vector to the position just after being selected). It's annoying on it's own, because you risk breaking things when trying to simply select something.
But what's worse, this movement can't be undone. Not sure how it was before alpha2, but now when you accidentally move something while selecting, it's not recorded as undo action. If you do it on freshly opened scene, the undo doesn't work at all. But when you have some undo history, trying to undo looks like undoing 2 operations (because the selection one wasn't recorded).

**Steps to reproduce:**
1. Open a scene with any node (actually I tested it only on Control nodes)
2. Try to select a node, but do so while moving mouse
3. If done correctly, the node will move slightly just after being selected
4. Happy reverting, unless you want to manually move it back

Here's a gif showing it:
![screen_recorder_plus_video_2018_17_11_23_10_55](https://user-images.githubusercontent.com/2223172/48666298-4dd11000-eabf-11e8-9b39-bd771fd92439.gif)
What I did was moving the panel, then deselecting it, then selecting again with quick-moving mouse. After I did undo (CTRL + Z), it returned to the first position, instead the second one.

**Comment by karliss** [comment]
Might be fixed in one of the beta versions. I was able to repeat what you described using 3.1 alpha 2, but in 3.1 beta5 and master the drag behavior has been changed. It is now possible to do proper drag and drop without having to click mouse twice and undo is working.

**Comment by KoBeWi** [comment]
Yeah, seems to be fixed already.
