### ISSUE TITLE
Data types in code completion

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#2378]
Sometimes I have to jump into the Help tab to know the returning data type (or property data type) and it slows me down. It would be helpful if code completion showed me data type next to the function/property name.

**Comment by firefly2442** [comment]
![screenshot_2015-10-12_10-40-01](https://cloud.githubusercontent.com/assets/531175/10432008/1818c034-70ce-11e5-8b97-9c6c1825cf81.png)

Doesn't it already have this feature (aad2bbdb6fb7c8217d7e75480b38e45f00cb3abd)?  Unless I'm misunderstanding your comment.

**Comment by GlaDOSik** [comment]
You're right. But this tooltip often gets in your way and covers the code. I thought about something like this.
![code](https://cloud.githubusercontent.com/assets/3484686/10465933/c676393a-71f1-11e5-86a7-081a8e27d4a7.jpg)

**Comment by akien-mga** [comment]
I'm not sure it would be an improvement; of course for new users it might be useful to see the types and arguments of all functions, but for non-beginners (who can still benefit for autocompletion), the main use of the list is to find what function does what (```get_accelerometer``` returns an accelerometer, ```get_joy_name``` is what you need when you want the joystick's name).
Once you know what function could fit your needs, you start typing it and get to the next level of detail with return type and arguments.

I think putting all details in the first list would mostly add clutter.

**Comment by GlaDOSik** [comment]
Yeah, you have a point. It might not be the best idea.
