### ISSUE TITLE
Add static methods for loading images

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#23782]
Right now, if you want to assign an arbitrary image as a texture, you need to do this:
```
var image = Image.new()
image.load("some/path.png")
var texture = ImageTexture.new()
texture.create_from_image(image)
$Sprite.texture = texture
```
This is a lot of code for simple operation. I know that `load` is supposed to return error code, but it can be done smarter. There could be static versions of both `load` and `create_from_image`, which return null if load fails (as simple as that). The above code could then become this:
`$Sprite.texture = ImageTexture.create_from_image(Image.load("some/path.png"))`
I know this is unsafe code, but there are people like me who don't mind unsafe code. Well, the unsafeness could be mitigated at all if trying to create from null image would result in a warning instead of error and simply return null.

There are probably more classes that would benefit from more static methods btw.

**Comment by TheCire** [comment]
I'm not sure but I think the variant system "automagically" turns an image into a texture behind the scenes. I have code like this 

```
var texture = load("path/to/image.png")
$Sprite.texture = image
```

and it works just fine like that...

**Comment by KoBeWi** [comment]
Yeah, but it works like this only if the texture is imported as a part of your project. If you want to load external texture, you need to use the code I provided.

**Comment by TheCire** [comment]
Gotcha, what about just creating your own wrapping function then?

```gdscript
func load_texture(path):
  var image = Image.new()
  image.load(path)
  var texture = ImageTexture.new()
  return texture
```

add it to a global singleton script or however you want to do it :)

Yeah, I get your point about having a built-in static function, but does that go along with the coding style and the way the engine works?

**Comment by Aaron-Fleisher** [comment]
@TheCire Power of GDScript! I love doing mini wrapper functions like that. I feel the OP's sentiments however, sometimes I wish there was an easier way to do something, but then realize you can really achieve a lot of stuff in GDS by itself

**Comment by KoBeWi** [comment]
Well, I know I can make a mini-wrapper (I actually did that). But then I have to copy it over to all projects I'd need it. Also I can't just have utility script with everything, because I don't always need all these functions and it's project-specific a lot >_>

My proposition seems logical and fixes the issue without workarounds, but maybe I'm just used to having language work that way.

**Comment by TheCire** [comment]
Looking at your code from your OP @KoBeWi , looks like Image should have a static initializer like so:

```gdscript
var image = Image.load("path/to/image.png")
```

instead of having to do:

```gdscript
var image = Image.new()
image.load("path/to/image.png")
#etc
```

**Comment by PetePete1984** [comment]
https://github.com/godotengine/godot/issues/20972
The last time this came up, reduz was in favor of removing Image.load entirely

**Comment by KoBeWi** [comment]
There seem to be little interest in this and I actually needed it in just one or two projects, so closing.

There's a slightly related proposal though https://github.com/godotengine/godot-proposals/issues/1101
