### ISSUE TITLE
Remote Debug Connection no Longer Working in 3.1

### ISSUE THREAD

**Issue by Cygon** [godotengine/godot#23780]
**Godot version:** Godot 3.1 alpha 2, custom build from git master branch, commit 9eb4b6d91a64661f8e2823a70f935c602f8a725a

**OS/device including version:**
Gentoo Linux, Kernel 4.14.63, KDE Plasma 5.13.5, GeForce GTX 1080 w/NVidia proprietary drivers 396.54

**Issue description:**
On my system, Godot 3.0.6 is able to debug scenes using the remote debugger.

Godot 3.1 however displays:

    Running: /opt/godot-git/bin/godot.x11.tools.64 --path /mnt/devel/GameDev/_/godot-ui-test/godot-demo-projects-master/viewport/gui_in_3d --remote-debug 127.0.0.1:6008 --allow_focus_steal_pid 18496 --position 2688,420 res://Gui_in_3D.tscn
    ERROR: _set_addr_storage: Condition ' !p_ip.is_ipv4() ' is true. returned: 0
       At: drivers/unix/net_socket_posix.cpp:113.
    ERROR: bind: Method/Function Failed, returning: ERR_UNAVAILABLE
       At: drivers/unix/net_socket_posix.cpp:301.
    ERROR: _get_socket_error: Socket error: 111
       At: drivers/unix/net_socket_posix.cpp:200.

I have found a suggestion to change the debug port in the QA section (https://godotengine.org/qa/20139/error-listening-on-port-6007), but this had no effect on the issue.

To obtain more info I added some debug output to the section where the error is happening:

    Error NetSocketPosix::bind(IP_Address p_addr, uint16_t p_port) {
    
            ERR_FAIL_COND_V(!is_open(), ERR_UNCONFIGURED);
            ERR_FAIL_COND_V(!_can_use_ip(p_addr, true), ERR_INVALID_PARAMETER);
    
            {
                    String ipAsString = static_cast<String>(p_addr);
                    CharString ipChars = static_cast<CharString>(ipAsString.utf8());
                    printf("Binding to %s\n", ipChars.ptr());
            }
    
            sockaddr_storage addr;
            size_t addr_size = _set_addr_storage(&addr, p_addr, p_port, _ip_type);
    
            printf("\taddr_size = %i\n", addr_size);
    
            if (::bind(_sock, (struct sockaddr *)&addr, addr_size) == SOCK_EMPTY) {
                    close();
                    ERR_FAIL_V(ERR_UNAVAILABLE);
            }
    
            return OK;
    }

The print statements result in the following output

    Binding to (null)
    addr_size = 0

My system is IPv4-only with a very simple networking configuration:

    cygon@tiamat /opt/godot-3.1 $ ifconfig 
    lan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
            inet 192.168.124.44  netmask 255.255.255.0  broadcast 192.168.124.255
            ether xx:xx:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
            RX packets 2420669  bytes 3380400972 (3.1 GiB)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 1990899  bytes 192972218 (184.0 MiB)
            TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
            device interrupt 16  memory 0xb3e00000-b3e20000  
    
    lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
            inet 127.0.0.1  netmask 255.0.0.0
            loop  txqueuelen 1000  (Local Loopback)
            RX packets 45  bytes 2336 (2.2 KiB)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 45  bytes 2336 (2.2 KiB)
            TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Steps to reproduce:**

1. Compile Godot 3.1
2. Try run any scene with the remote debugger enabled

**Comment by Faless** [comment]
This is a nasty one, thanks for spotting it. I narrowed down the issue, a fix is under way.
