### ISSUE TITLE
Clear all broken projects in manager

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#23785]
When you have a project saved in project manager and you delete/move the directory, it becomes grayed out in the manager. Now, especially when you copy over your Godot settings, you might end up with a long list of broken projects, which you need to delete. They should either be deleted automatically (probably as an option, but they are useless anyways) or there should be a clear-all button that deletes them without confirmation.

**Comment by Zireael07** [comment]
+1 to clear-all.

(Deleting all gray projects was suggested before but shot down because some people keep projects on USB sticks/external drives, which turn gray when you disconnect the drive, but then you connect the drive again and want them in the list still)

**Comment by qarmin** [comment]
I created button to clear missing project #25713

**Comment by akien-mga** [comment]
Fixed by #25713.
