### ISSUE TITLE
Select NOT exported assets

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#23784]
When exporting, you have an option to select what assets are exported. I was in a situation when I wanted to do the opposite: I had a resource directory that was supposed to be dynamic i.e. not part of a project, but loaded as external resource. For convenience it was located inside project directory for testing purposes, but each time I wanted to export the project, I had to move that directory out so it's not included.

Now, I could select assets that get imported, but it was terribly annoying, because every time I added something new to the actual project, I had to select it for export, otherwise the exported game was crashing when I forgot to do that. So there should be an option to EXCLUDE some files, I mean particular files (or directories, when this option finally gets added to 3.x), just like we have option to include only particular files.

**Comment by volzhs** [comment]
it seems similar issue for 2.1 #3646

there also was similar issue for 3.x #8461
and it's fixed by 85945e4367c6c0759f855a3dfefe5941c3c07cd3

do these help for your issue?

**Comment by KoBeWi** [comment]
OMG, the .gdignore file fixes the issue.
Good to know that something like this already exists.
