### ISSUE TITLE
Opening full 3D scenes in Godot causes error spam regarding surface arrays

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#23783]
**Godot version:**
3.1 dev build from Calinou (hash 9e85d17)

**OS/device including version:**
Win 10 Pro 64 bit; Nvidia 1060 6GB GPU; Ryzen 2700x CPU; 32 gigs RAM

**Issue description:**
For a while, opening a full 3D scene in Godot causes this error spam
![godot errors](https://user-images.githubusercontent.com/10081256/48666636-5c9dcf80-ea8b-11e8-84c3-91f7e2a4c8f0.jpg)

At one point recently, I tried to remedy this by re-importing some collada files with extraneous material indices removed, it had no effect. This has been an issue for a while and I am concerned it could affect the stability of the editor. How much spam is really dependent on the total number of nodes in the scene tree. The type of scene I use for levels is the one that inherits the imported file.

**Steps to reproduce:**
Find a complex 3D scene to open and watch the output box

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by akien-mga** [comment]
Confirmed when opening the `trucktown.tscn` scene in the current version of the Truck Town demo (git).
