### ISSUE TITLE
Crash message appears on Window when closing release export

### ISSUE THREAD

**Issue by Aaron-Fleisher** [godotengine/godot#23797]
**Godot version:**
35b421b6954c5baff4b4fd4bc56b09c85dae6ff5

**OS/device including version:**
Windows 7  64-bit, GTX 960

**Issue description:**
 - Export a game (blank scene) with *Export With Debug* **unchecked**
 - Run the .exe, then  close the window. 
 - ![image](https://user-images.githubusercontent.com/43447253/48673455-83ddb680-eaf6-11e8-8f87-f6bb0b5fd1da.png)
- If Export With Debug is checked while exporting, the Window will close gracefully

 
I'm using VS Build Tools 2017, and this cmd to compile:
> **scons platform=windows tools=no target=release disable_3d=yes**
 ```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	hi.exe
  Application Version:	3.1.0.0
  Application Timestamp:	5bf169f8
  Fault Module Name:	hi.exe
  Fault Module Version:	3.1.0.0
  Fault Module Timestamp:	5bf169f8
  Exception Code:	c0000005
  Exception Offset:	0000000000509444
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	3ef9
  Additional Information 2:	3ef9a5ec0ee3db16b07ebcc4765955a9
  Additional Information 3:	5321
  Additional Information 4:	5321c849060a6dea5864639b0a26083f
```

e: I'm going to test this on Windows 10, one sec
e2: Back, [no crash on Windows 10](https://i.gyazo.com/541ffacaeae43a3cd0e72518dd2bb9ac.gif). This seems like Windows 7 only.

**Comment by akien-mga** [comment]
Is this still reproducible with Godot 3.2 beta 2 or later?

**Comment by sporeball** [comment]
i can check if this is still reproducible in about an hour

**Comment by akien-mga** [comment]
Thanks! Closing as fixed.
