### ISSUE TITLE
Closing a scene tab makes another become "edited"

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#23791]
**Godot version:**
9eb4b6d

**Issue description:**
When closing a scene tab, the next tab that gain focus will be treated as "edited":
![peek 2018-11-18 01-44](https://user-images.githubusercontent.com/30739239/48668414-a0b4c280-ead3-11e8-9807-100a9d003581.gif)

**Comment by akien-mga** [comment]
Might be due to 9e85d17.

**Comment by YeldhamDev** [comment]
@akien-mga Yep, just tested it, doesn't happen without @reduz's commit.

**Comment by reduz** [comment]
I suppose function in UndoRedo for clearing history should have a flag to increment version (true by default) but in the case of closing a tab should pass false.. anyone wants to give it a try?

**Comment by avencherus** [comment]
Didn't find this at first, but made almost the same video of the problem.  X)

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/13004169/48734386-f90fcf80-ec4d-11e8-84ba-b6baef8403a1.gif)
