### ISSUE TITLE
OptionButton and national characters

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#2379]
When using OptionButton and national characters, the list does not work properly.
http://www.picshare.ru/view/6668736/

 	
Letters (labels) are displayed only on the button. On discharge letter list are not displayed!

**Comment by akien-mga** [comment]
I think this bug might be a consequence of #1958. Are you using a custom font to display cyrillic characters? Apparently the OptionButton does not use the font for the list items.

**Comment by DimitriyPS** [comment]
Yes, it is. I assume that the cause is identical. However, in this case this is a more significant problem. As the list of OptionButton empty. There is no information. Use OptionButton of national symbols becomes impossible.

**Comment by reduz** [comment]
There is not much you can do here, but I recommend you simply create a theme with just the default font and override it in the root of your gui, that is a much easier workaround

**Comment by reduz** [comment]
(also works for this case if you put the theme into OptionButton)
