### ISSUE TITLE
non-High DPI mode renders incorrectly on OSX

### ISSUE THREAD

**Issue by wraitii** [godotengine/godot#23796]
**Godot version:**
On 9eb4b6d91a64661f8e2823a70f935c602f8a725a

**OS/device including version:**
OSX 10.13.5 on a macbook pro.

**Issue description:**
When choosing non-high dpi mode in the project settings, it only renders to a quarter of the screen. High-dpi mode works correctly.

This seems to be caused by 30852d023789aefcdbefcacb0c81332945d3dcee because reverting that fixes it.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
I can't reproduce it on macOS 10.14.1 (18B75) and 10.13.6 (17G3025), but this line is not required on pre 10.14 macOS and can be disabled (#23801).
