### ISSUE TITLE
Generic6DOFJoint error  

### ISSUE THREAD

**Issue by Aaron-Fleisher** [godotengine/godot#23800]
**Godot version:**
35b421b6954c5baff4b4fd4bc56b09c85dae6ff5

**OS/device including version:**
Windows 10 & 7 64-bit, GTX 960

**Steps to reproduce:**
 - Create a new project
 - Add a Node2D to the scene
 - Play the project

**Issue description:**
- This error appears in Error tab console:
- ![image](https://user-images.githubusercontent.com/43447253/48673790-0f0c7b80-eafa-11e8-9f15-d4fee5f296b4.png)

```
E 0:00:00:0376   Object already has property: Generic6DOFJoint
  <C Source>     core\class_db.cpp:942 @ ClassDB::add_property()
```

**Comment by piratesephiroth** [comment]
yeah this is showing up whenever I run the editor (on the mono version)

![image](https://user-images.githubusercontent.com/10672233/48679047-70703100-eb72-11e8-9114-ddebfa0888cb.png)

**Comment by D1AS** [comment]
Godot version:35b421b

the same thing happens on a **mac os**, just add a Sprite and run the project:

E 0:00:00:0181   Object already has property: Generic6DOFJoint
  <C Source>     core/class_db.cpp:942 @ add_property()
