### ISSUE TITLE
Generated NavigationMeshes are oriented downwards

### ISSUE THREAD

**Issue by needleful** [godotengine/godot#23817]
**Godot version:**
Commit hash f769e13c5ef8b8a0df681f4febff42c05ab05009, the latest on the master branch.

**OS/device including version:**

Windows 7 Professional

**Issue description:**

Upon baking a NavigationMesh, its faces are oriented away from the specified "up" vector, rather than towards it.  This doesn't affect path-finding, but it makes the navmesh hard to see while working, and caused me a good deal of confusion when I was first trying to use it, since I didn't notice it being generated at all.

So here's what I'm seeing on the master:
![bug_1](https://user-images.githubusercontent.com/43552977/48686422-846f5f00-eb81-11e8-9664-bb93454c4bdd.png)
![bug_2](https://user-images.githubusercontent.com/43552977/48686424-85a08c00-eb81-11e8-90cd-36fac276a1e0.png)

And here's what I'm getting on my own branch after changing the orientation of the faces.
![fixed_1](https://user-images.githubusercontent.com/43552977/48686479-c4cedd00-eb81-11e8-8ac2-04c40df3701e.png)

**Steps to reproduce:**
Bake a NavigationMesh as intended, with the node path `Navigation\NavigationMeshInstance\[world geometry and colliders]`.  The navmesh should be oriented downward.

**Minimal reproduction project:**

[navmesh-orientation.zip](https://github.com/godotengine/godot/files/2593801/navmesh-orientation.zip)

**Comment by Toshiwoz** [comment]
I suggest to change the title to **Baked NavigationMeshes are oriented downwards**

Plus, I experienced the same with the demo project (with 3.1 beta) https://github.com/godotengine/godot-demo-projects/tree/master/3d/navmesh
