### ISSUE TITLE
Number of Draw Calls does not seem to be correct? 

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#23826]
Windows 10, Godot 3.0.6. 

So we are currently looking at optimizing our 2D game ( the monitor in 2D mode does, however not display Draw Calls at all no matter how many sprites you have), so for testing purposes we tried switching to 3D instead and _now_ the monitor does display Draw Calls but not the correct amount. 

If we place 4 objects or standard cubes in an empty scene with just a camera the Monitor displays 8 Draw calls - Not 4? And it does not seem to matter what settings you choose in the camera environment settings.

So.. not sure if this is a Monitor issue or something with the way Godot renders objects.

![image](https://user-images.githubusercontent.com/24936603/48713739-65b8a900-ec11-11e8-8f6c-319fa1acfefc.png)

**Comment by CptPotato** [comment]
Drawcalls are also needed for things such as post-processing, shadows, etc.
I'm not sure which of those types Godot tracks, though.

**Comment by Windfisch** [comment]
it does definitely track shadows. Multiple surfaces in one mesh also mean different draw calls. Then there's the draw call for the sky dome

**Comment by jesperkondrup** [comment]
But in this scene I have absolutely nothing but the 4 meshes. No lights, no shadows no sky dome and the material have even been set to flat shading, also my mesh is a single mesh. If I make the same scene in Unity it gives me 4 Draw Calls and that is even with 4 different materials, in the Godot scene I am using the same material.

**Comment by Zireael07** [comment]
Unity batches draw calls per material. I'm not sure if Godot does.

**Comment by jesperkondrup** [comment]
> Unity batches draw calls per material. I'm not sure if Godot does.

Yes, this is why I created 4 unique materials in Unity, so I could make sure that nothing was batched.

**Comment by CptPotato** [comment]
Again, not all drawcalls are something you see on screen and 8 is certainly not a big number. I agree that the engine should be optimized as much as possible but to test that I think larger scenes are needed.

**Comment by jesperkondrup** [comment]
I don't think you need a large scene to test the number of draw calls, on the contrary I think it's a lot easier to see whats going on in a smaller scene. I created a new image with a lot more information.

As I wrote in my initial post we don't know if this is the Monitor displaying the wrong number for some reason, if it's some obscure setting in the material/environment or if it's an actual issue with the engine. 
But currently it seems that Godot is doubling the number of Draw Calls for each model. So for 10 models in a scene it's not 10 draw calls but 20 and furthermore there's no batching of materials meaning that a scene in Godot can easily become exponentially larger than a scene in Unity (obviously depending on how you make your scene).

I used the same Obj model for both Unity and Godot and created a default material in both engines. I have tried enabling and disabling stuff in Godots default shader but no change happened.

![image](https://user-images.githubusercontent.com/24936603/48761751-b4198680-eca9-11e8-9fb8-e9580c237751.png)

**Comment by CptPotato** [comment]
iirc Godot uses a depth pre-pass for opaque rendering, that would double the amount of drawcalls.
The benefit is that this reduces overdraw and can improve the performance of costly object shaders.

**Comment by jesperkondrup** [comment]
@CptPotato You are right, I fount it. It's actually a project setting. If you disable it the draw calls are down to 1 draw call for 1 mesh. What this means in terms of performance if it's on/off I don't know, but at least the number of Draw Call now makes sense, thanks :)

**Comment by Zireael07** [comment]
What project setting you mean, @jesperkondrup?

**Comment by jesperkondrup** [comment]
Project Settings / Quality / Depth Prepass

**Comment by jurgel** [comment]
Depth prepass is ok, but no batching?
I read [here](https://github.com/godotengine/godot/issues/7844#issuecomment-280964783) and I thought Godot already batch all the mesh if using the same material.
So, it is false?

I can confirm this, as I test on Godot 3.1.beta1.official

**Comment by Windfisch** [comment]
Godot does not batch multiple meshes into one draw call. Instead, it reorders these draw calls to minimize shader/context switches (which is another metric you can see in the profiler).
While batching draw calls would definitely improve rendering speed in some situations even further, minimizing context switches alone is already very effective.

**Comment by Zireael07** [comment]
Godot still seems to report draw calls/vertices very badly in 3.3 stable, just fyi.

Compare those three screenshots:

![Screenshot_20210507_134859](https://user-images.githubusercontent.com/4525388/117445917-a02a7380-af3b-11eb-81bf-da15cfb3e8dc.jpg)
![Screenshot_20210507_134932](https://user-images.githubusercontent.com/4525388/117445927-a3bdfa80-af3b-11eb-935a-d0a52f46bd3e.jpg)
![Screenshot_20210507_135137](https://user-images.githubusercontent.com/4525388/117445937-a7ea1800-af3b-11eb-8c47-bb9011dd0a9f.jpg)

Judging by what happens when zooming in and/or opening  a new scene, it seems to be counting the grid/gizmo vertices/drawcalls, too (and I can't see an option to switch off editor grid)

**Comment by Calinou** [comment]
> (and I can't see an option to switch off editor grid)

Use the **View** menu at the top of the 3D editor.

We can't prevent gizmos from being counted in gizmos in `3.x`. Also, in GLES3, draw calls will be doubled due to the depth prepass. You can disable it in the project settings if you rarely have occluded geometry.

**Comment by Zireael07** [comment]
Fair point on gizmos, but if the information box knows it's being called from editor, it could automatically subtract the number of grid vertices at least, since it seems to be known?

**Comment by Calinou** [comment]
> Fair point on gizmos, but if the information box knows it's being called from editor, it could automatically subtract the number of grid vertices at least, since it seems to be known?

If we do this for the number of vertices but not for the number of draw calls, it could end up being misleading. I'm not sure if we can *always* predict this for all gizmos, especially as some gizmos may leave the view frustum depending on where your camera is (e.g. the Light3D icons and gizmos).

**Comment by Zireael07** [comment]
> I'm not sure if we can always predict this for all gizmos

I know, that's why I mentioned the grid only - it has the most vertices so it throws the numbers off the most (and we could also subtract the 2 drawcalls the grid uses, too)
