### ISSUE TITLE
soft body move with kinematic body will lag behind

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#23821]
**Godot version:**
3.1 `a16d9c6`

**OS/device including version:**
Windows 7

**Issue description:**
a soft body parent with kinematic body will lag behind parent when parent move

![default](https://user-images.githubusercontent.com/24987226/48695240-9a306300-ec19-11e8-8953-7efdab2923a4.png)

You can see idle in left and moving in right. The distance between the cube and the soft body is different

**Steps to reproduce:**
make a soft body as child of a kinematic body.
move the kinematic body

**Minimal reproduction project:**
[test_project.zip](https://github.com/godotengine/godot/files/2594397/test_project.zip)

**Comment by AndreaCatania** [comment]
Duplicated #21599

**Comment by Zireael07** [comment]
.. or #23482? To me it looks like the softbody just doesn't move from the spot it was instanced at, just sinks down..

**Comment by AndreaCatania** [comment]
This is hard to fix without changing the engine, I'm not sure how to fix it

**Comment by Yogoda** [comment]
Any workaround available? My character's hair are lagging behind when moving.

**Comment by Yogoda** [comment]
update: I applied fix #21599 and it works correctly

**Comment by AndreaCatania** [comment]
It still work in progress, because at that time I saw that a part of the engine must be changed in order to fix it

**Comment by baumschubser** [comment]
Is there an update on this case? 
Am I correct that at the moment it is not possible to move a soft body, e.g. by moving its parent KinematicBody or RigidBody? Is there a workaround or is it simply impossible to programmatically move SoftBodys ?

**Comment by AndreaCatania** [comment]
Move soft bodies is possible, but in godot there is a problem that makes the softbody to be updated 1 frame later. I should work on this to find a viable solution.

**Comment by AndreaCatania** [comment]
Fixed by #36048

![ezgif com-video-to-gif(14)](https://user-images.githubusercontent.com/8342599/74103405-10392680-4b4c-11ea-87c6-fe463d26816e.gif)
