### ISSUE TITLE
Performance drop when Camera gets close to mesh with OmniLight shadow contact bias > 0

### ISSUE THREAD

**Issue by dusklight0** [godotengine/godot#23838]
**Godot version:**
Godot_v3.0.6-stable_win64

**OS/device including version:**
Window10

**Issue description:**
i import obj made by blender.
after that player character close to imported mesh,
frame drop

**Steps to reproduce:**
run project and walk to wall and look around

**Minimal reproduction project:**
[FPSRPG.zip](https://github.com/godotengine/godot/files/2598518/FPSRPG.zip)

**Comment by dusklight0** [comment]
i found reason.
off shadow contact option to zero solve problem

**Comment by akien-mga** [comment]
Confirmed on the master branch (f2cc96984) with the above project, I have 60 FPS until I get close to the wall where FPS drop to 20-30.

Setting the OmniLight's `shadow_contact` to 0 in `Room1.tscn` solves it, but any non-null value incurs the performance drop (whether 1 or 8).

**Comment by nathanwfranke** [comment]
**Still a problem, almost submitted my own issue before I found this**

---

**Godot version:**
Latest stable: v3.1.1.stable.mono.official

OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 4.18.0-18-generic
GPU: GeForce GTX 960
Drivers: nvidia-driver-418

[GodotTestProject.zip](https://github.com/godotengine/godot/files/3185207/GodotTestProject.zip)

**Comment by Calinou** [comment]
Maybe we should just remove contact shadows? They're too slow/broken to be usable in my experience, even on high-end GPUs with modern drivers.

**Comment by Calinou** [comment]
I'll close this, as contact shadows are no longer available in the `master` branch (they were replaced by shadow pancaking, which does a similar job better).
