### ISSUE TITLE
Resizing a WindowPopup from top or left makes it move when minimum size is reached

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23831]
Godot 3.0.6
Godot 3.1 alpha2

This is quite a messy behaviour, when you try to resize a window using its top and/or its left edge and minimum size is reached, it starts moving instead of staying where it is. This does not happen when the window is resized from the right or bottom edges.

Reproduction steps:
1) Open the editor
2) Open the About window, or a WindowPopup that you made resizeable
3) Try to make it smaller by resizing from top-left corner: notice it will start moving instead of staying still.

Interestingly, this does not happen on the ProjectSettings, EditorSettings and FileDialogs.

**Comment by Gutierrezjdr** [comment]
@Naryosha What did you want to fix about the label overlay? Is it specifically margin and borders with other objects on the button?
