### ISSUE TITLE
Getting depth texture from viewports

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot#23847]
While you can get a viewport's texture and pass it to a shader, this can only be done with its colour. What about the *depth* buffer/texture? Right now I have several shaders and a couple of projects that would benefit from being able to retrieve a viewport's depth texture.

Getting a separate viewport depth allows to:

- mask away objects in a texture that shouldn't be there. Like in the case of planar reflections.

- composite objects in a separate viewport other the scene. Like in the case of rendering down sampled ray casting effects.

I can't really think of other cases at the moment but these two alone can already allow a lot of post-processing effects.

**Comment by CptPotato** [comment]
I could use this for some custom rendering but in 2D. However, I'm not sure if this works with how Godot does its 2D rendering.

**Comment by Bauxitedev** [comment]
This would be really useful for my [texture painter](https://github.com/Bauxitedev/godot-texture-painter). The way I'm currently doing it is:

1. Make a new Viewport
2. Put a quad into it that aligns itself with the camer and has a shader that simply outputs the contents of `DEPTH_TEXTURE`
3. Use a ViewportTexture pointing to the viewport to get the depth texture

In my case I need the depth texture to prevent drawing on occluded surfaces.

**Comment by hutty** [comment]
This would be useful for me as well. I have a separate camera/viewport for drawing outlines around my models and wanted to mask them with the depth buffer as they currently draw through everything. 

As it currently is, I'll need a more complicated approach.

**Comment by sleepcircle** [comment]
I could really use this, as well. In fact, I could really use this in 2D.

**Comment by clayjohn** [comment]
@sleepcircle in 3D: http://docs.godotengine.org/en/latest/tutorials/shading/advanced_postprocessing.html

There is no such thing as depth in 2D. The 3rd "D" in 3D is for depth.

**Comment by sleepcircle** [comment]
@clayjohn I know it's primarily for 3D. I guess what I'm saying is, it would be nice to have an arbitrary single-value shader buffer that my 2D shaders could write to, for various reasons.

**Comment by clayjohn** [comment]
This is tracked in https://github.com/godotengine/godot-proposals/issues/798

**Comment by KnightNine** [comment]
Just want to let anyone looking for a workaround for getting the depth map for screen space effects, you can use compute shaders. I found a good tutorial [here](https://youtu.be/Ov0LcLjmKX8?si=qggbbWWCYafS3pP8), And the links to his complete examples are [here](https://www.patreon.com/posts/outline-post-and-111425719?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator&utm_content=join_link). 

 (Note: he made a mistake in the video and corrected it in the complete examples)
