### ISSUE TITLE
Long values are ignored when sent from Android modules via GodotLib.calldeferred().

### ISSUE THREAD

**Issue by SimonSikstrom** [godotengine/godot#23845]
**Godot version:**
v3.0.6.stable.official.8ac39d8

**OS/device including version:**
Android: Any version

**Issue description:**

Long values are ignored when sent from Android modules via [GodotLib.calldeferred()](https://github.com/godotengine/godot/blob/173b342ca738916cf113554291bb11f7cce71043/platform/android/java/src/org/godotengine/godot/GodotLib.java#L71).

Example:

	GodotLib.calldeferred(instance_id, "_my_godot_func", new Object[]{123L});

and catching the event in a gdscript doesnt work:

	# This will not be called
	func _my_godot_func(longval):
		print("wont print :(: ", longval)

But it will call the func if I don't add the longval as parameter in gdscript:

	func _my_godot_func():
		print("this will print")

Hence the long value is ignored.	

I'm thinking a solution could be to use the same solution for Integers as used with Doubles and Floats today in java_glue, and use longValue instead of intValue?

What's happening with doubles and float today:

https://github.com/godotengine/godot/blob/173b342ca738916cf113554291bb11f7cce71043/platform/android/java_glue.cpp#L305

	if (name == "java.lang.Float" || name == "java.lang.Double") {
		jclass nclass = env->FindClass("java/lang/Number");
		jmethodID doubleValue = env->GetMethodID(nclass, "doubleValue", "()D");
		double ret = env->CallDoubleMethod(obj, doubleValue);
		return ret;
	};

What's happening with Integers:

https://github.com/godotengine/godot/blob/173b342ca738916cf113554291bb11f7cce71043/platform/android/java_glue.cpp#L271

	if (name == "java.lang.Integer") {
		jclass nclass = env->FindClass("java/lang/Number");
		jmethodID intValue = env->GetMethodID(nclass, "intValue", "()I");
		int ret = env->CallIntMethod(obj, intValue);
		return ret;
	};

Long is not present.

Possible solution.

	if (name == "java.lang.Integer" || name == "java.lang.Long") {
		jclass nclass = env->FindClass("java/lang/Number");
		jmethodID longValue = env->GetMethodID(nclass, "longValue", "()J");
		jlong ret = env->CallLongMethod(obj, longValue);
		return ret;
	};

Solution diff:
https://github.com/godotengine/godot/commit/9844731603c81b0e839c36cc3fee5908ff11ff56

Thoughts?

**Comment by akien-mga** [comment]
The proposed patch seems good to me.

**Comment by akien-mga** [comment]
Looking further down at the float/double case, should `if (name == "[L") {` be handled too for `getLongArrayRegion`?

**Comment by SimonSikstrom** [comment]
Agreed, seems like a long array would not be handled either in this case. I could add it to the same pr since its related, if you want.

**Comment by akien-mga** [comment]
Yeah a single PR/commit for both changes would be fine.
