### ISSUE TITLE
Godot doesn't scale svg file when I using the image as icon via class_name

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23849]
**Godot version:**
3.1 5738c92

**OS/device including version:**
Windows 10

**Issue description:**
When I create script with this lines
```
extends Character

class_name Enemy, "res://Characters/Enemy.svg"
```
I expect that Godot take Enemy.svg image, scale it and put to creating new node window, but it doesn't scale it and it looks terrible:
![ffff](https://user-images.githubusercontent.com/41945903/48777418-d1167f80-ecd2-11e8-9aef-ecf972997aaf.png)

Probably Godot take svg parameters from import tab, but for me should import once again this file to e.g. 32px(I don't know how big is default size)

**Comment by akien-mga** [comment]
CC @willnationsdev

**Comment by willnationsdev** [comment]
@akien-mga The default size is 16x16 I believe. I'm not sure what exactly the fix for this would be though. We'd have to somehow detect on import whether an icon was affiliated with a script class, and then enforce a 16x16 size in that case...or something? I don't know anything about the import process, nor who should be cc'd for assistance on that.

**Comment by qarmin** [comment]
Also it is visible in Scene Dock. 
When I change a canvas size in Inkscape to 16mm, then in File System dock svg files lost quality but as you can see in Scene dock this image have big resolution(in import i used scale=4)
![asfgasgasgasgasgasg](https://user-images.githubusercontent.com/41945903/48778595-f48ef980-ecd5-11e8-9689-562d3b75fa5e.png)

**Comment by willnationsdev** [comment]
Yeesh. Well, maybe it has something to do with the editor having different processes for using svg's at different scales (i.e. at which point in the process is it converting them to a rasterized format like png and using them)?
