### ISSUE TITLE
Gles2 ambient occlusion black artifacts

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#23848]
**Godot version:**
173b342ca738916cf113554291bb11f7cce71043

**OS/device including version:**
Ubuntu 18.04, GTX1060

**Issue description:**
Models with ambient occlusion material have weird, 'pixelated' dark artifacts on gles2 backend:
![bed](https://user-images.githubusercontent.com/6129594/48776496-50ef1a80-ecd0-11e8-8da2-916f7a9f6a6a.png)

This issue is a little similar to #23473, but that one was about the roughness.
On the screen/reproduction project there are also visible normal map artifacts (probably related to #21752)

**Steps to reproduce:**
1. Download reproduction project and open `Gles2BlackArtifacts.tscn` scene. 

**Minimal reproduction project:**
[Gles2OcclusionBlackArtifacts.zip](https://github.com/godotengine/godot/files/2599909/Gles2OcclusionBlackArtifacts.zip)

**Comment by DavidSichma** [comment]
Does #23971 resolve the issue?
