### ISSUE TITLE
Can't initialize enum values from other non-constant values within enum

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#23843]
**Godot version:**
3.1, 3.2, 4.0.

**Issue description:**

This is how I used to initialize some enum values before #23648 (this is actually possible in C++):
```gdscript
enum TimeFormat {
	FORMAT_HOURS   = 1 << 0,
	FORMAT_MINUTES = 1 << 1,
	FORMAT_SECONDS = 1 << 2,
	FORMAT_DEFAULT = FORMAT_HOURS | FORMAT_MINUTES | FORMAT_SECONDS
}
```

Now I can't initialize `FORMAT_DEFAULT` value:
```gdscript
FORMAT_DEFAULT = FORMAT_HOURS | FORMAT_MINUTES | FORMAT_SECONDS # error: Expected constant expression.
```

A workaround would be to initialize enum constants with numeric literals:
```gdscript
enum TimeFormat {
	FORMAT_HOURS   = 1,
	FORMAT_MINUTES = 2,
	FORMAT_SECONDS = 4,
	FORMAT_DEFAULT = 7
}
```

But I find it error prone... If this what breakscompat implies than close the issue, I can live with that :)

**Comment by bojidar-bg** [comment]
It should be possible with something like that:
```gdscript
enum TimeFormat {
	FORMAT_HOURS   = 1 << 0,
	FORMAT_MINUTES = 1 << 1,
	FORMAT_SECONDS = 1 << 2,
	FORMAT_DEFAULT = TimeFormat.FORMAT_HOURS | TimeFormat.FORMAT_MINUTES | TimeFormat.FORMAT_SECONDS
}
```
Not sure how the proposal can be implemented without too many hacks.

**Comment by Xrayez** [comment]
@bojidar-bg tested your solution, I get the same error either way.

**Comment by vnen** [comment]
@bojidar-bg this is not possible. It might be if we make the Dictionary constant earlier (as soon as they are defined). Right now the Dictionary is only set at the end of the enum.

Though it might be possible to look into the current enum for this specific use case. I don't think it require a big hack.

**Comment by Xrayez** [comment]
This is still relevant for 4.0, but now the error is different:
```
SCRIPT ERROR: Parse Error: Expected closing "}" for enum.
          at: GDScript::reload (res://Node2D.gd:4)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: GDScript::reload (modules\gdscript\gdscript.cpp:608)
```
