### ISSUE TITLE
Restore previously opened scenes automatically on "Open Project"

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2385]
Save all open scenes on "Editor/Project close" and re-open on "project start".

**Comment by reduz** [comment]
would take a while to open in some cases, but i think some people might prefer it..

**Comment by bojidar-bg** [comment]
@reduz Probably as a editor setting then ^^

**Comment by blurymind** [comment]
@reduz it could be an option in the preferences?
I would personally prefer it

**Comment by aaronfranke** [comment]
It's in the preferences now. For reference, the setting is located at Editor -> Editor Settings -> General -> Interface -> Scene Tabs -> "Restore Scenes On Load".
