### ISSUE TITLE
Onion skin changes ColorRect size at specific time

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#23858]
**Godot version:**

14cf450

**OS/device including version:**

Manjaro x86_64

**Issue description:**

![peek 2018-11-20 23-56](https://user-images.githubusercontent.com/43379543/48789707-3f356380-ed20-11e8-8f88-8f4423d9355b.gif)

ColorRect size changes if
- it is animated by rect_position
- onion skin is turned on
- animation is seeked to a specific time

The change happens continuously and doesn't mark the scene as unsaved.

**Steps to reproduce:**
1. open the scene
2. select AnimationPlayer
3. manually seek to 0.7 sec, don't press play
4. turn on Onion skin

**Minimal reproduction project:**

main.tscn
```
[gd_scene load_steps=2 format=2]

[sub_resource type="Animation" id=1]

resource_name = "New Anim"
tracks/0/type = "value"
tracks/0/path = NodePath(".:rect_position")
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/imported = false
tracks/0/enabled = true
tracks/0/keys = {
"times": PoolRealArray( 0, 1 ),
"transitions": PoolRealArray( 1, 1 ),
"update": 0,
"values": [ Vector2( 0, 0 ), Vector2( 100, 0 ) ]
}

[node name="ColorRect" type="ColorRect"]
margin_right = 40.0
margin_bottom = 40.0

[node name="AnimationPlayer" type="AnimationPlayer" parent="."]
"anims/New Anim" = SubResource( 1 )
```

**Comment by bojidar-bg** [comment]
CC @RandomShaper

**Comment by RandomShaper** [comment]
It's a feature!

No, just kidding. I'll have a look. Self-assigned.

**Comment by RandomShaper** [comment]
@Naryosha, I cannot reproduce it on the last version. Can you confirm?

**Comment by Naryosha** [comment]
463123a
Can't reproduce either, at least for the given file. However, the onion skin itself doesn't seem accurate around that animation time, but that might be another issue.
