### ISSUE TITLE
KinematicBody2d and RigidBody2d sometimes falling trhough one way platforms when another body stands on it

### ISSUE THREAD

**Issue by doquen** [godotengine/godot#23860]
Tested on Godot 3.0.6 and 3.1-alpha and 3.1-master.
Ubuntu 18.10 operative system.

When using one way collision for platforms, if a body (kinematic or rigid) stands on another body, it sometimes causes it to fall through the platform. 

Here is an example:
![oneway](https://user-images.githubusercontent.com/20048049/48790052-3d8e8000-eccd-11e8-8f48-be9db4c74c2b.gif)

I've already asked in this [issue](https://github.com/godotengine/godot/issues/9399#issuecomment-440344535), but apparently is different problem. I attached simple project to test, maybe my mistake.

Thanks
[Gunzo.zip](https://github.com/godotengine/godot/files/2600804/Gunzo.zip)

**Comment by bojidar-bg** [comment]
Would be nice to have a confirmation from 3.1 master, as there were some changes to one-way collisions in 3226b44f793ec18f92341819e11ae20d68d0193e.

**Comment by PabloF7** [comment]
I'm sorry, i meant 3.1-master. I cloned the repo and compiled master branch and still get the same behavior. I previously had tried in alpha, that's why i said alpha. I'm editing the post.

**Comment by PabloF7** [comment]
You are right, using rectangle shapes on both body does not cause this effect... I'll try what happens with custom polygon shapes.

**Comment by PabloF7** [comment]
I have the same result with polygon shapes. The problem seems to be related with not normal collisions. i mean, when the collision happens with some angle.

**Comment by PabloF7** [comment]
Hi,
Testing more, i found that it can also happen with rectangular shapes, although is more difficult for this to happen. If someone gives me some guidelines, i could try to solve it myself.

**Comment by eon-s** [comment]
@PabloF7 if you want to give a try fixing this, contact devs on IRC, godotengine-devel on freenode (wait for next week until Juan is back), I guess that reduz and randomshaper are the best on 2D physics.

**Comment by PabloF7** [comment]
Ok, I'll contact them next week in the IRC channel. Thanks!

**Comment by doquen** [comment]
Just for the record, issue still exists in master.

**Comment by reduz** [comment]
This took a ton of work to fix...

**Comment by doquen** [comment]
Great Job! i'll try after work
