### ISSUE TITLE
Exported Game exe doesn't run on other computers

### ISSUE THREAD

**Issue by Kaideu** [godotengine/godot#23866]
**Godot version:**

3.0.6 Mono Version

**OS/device including version:**

Windows 10

**Issue description:**

I exported my finished game for windows and the exe file for the game runs fine on my computer, however, when others download the exe and pck files, they get this error (Cannot Find mono in the registry)
(I'm not sure why it's so blurry, but i did not take this photo)
https://media.discordapp.net/attachments/514232464873619483/514623850756046849/unknown.png
Here is my game download:
https://kaideu.itch.io/just-another-space-shooter

Am I to assume that the person downloading needs to have something pre-installed to allow them to play this? or is this a mono export bug?

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by star-tek-mb** [comment]
Mono must be installed on system, i think

**Comment by Kaideu** [comment]
> Mono must be installed on system, i think
So, I would need to list mono as a requirement for my player base?

Has anyone else had this issue or figured out an alternative to having a mono requirement?
I tried looking into web export to not have to deal with this, but web export seemed like it wasn't ready yet or had some steps that I couldn't figure out dealing with a third party software.

**Comment by Cygon** [comment]
C# support isn't finished yet. I believe the plan is to include a Mono runtime library with exported C# projects in the end, thereby removing the requirement for players to install mono.

Also see #18364 C# status and plans towards 3.1

It states: "_2. Finish project exporting. This is almost done. It's just missing exporting the right mono runtime library for the target platform, making it work with the Export PCK/Zip(-only) option, and more testing of course._"

It may be possible to simply copy the Mono runtime library into your exported project's folder, but I don't know from the top of my head which files you need (start with `Mono.dll` maybe :)).

**Comment by Kaideu** [comment]
> C# support isn't finished yet. I believe the plan is to include a Mono runtime library with exported C# projects in the end, thereby removing the requirement for players to install mono.


What if my code doesn't use any C#?
I tried using C# but some keywords didn't work as they should so, as stated here #23609, so I just used the Godot language.
Does this mean i would need to replace the mono version with the standard version to be able to get this game to run properly?
Do you know if I am able to simply backup my project, replace my Godot version and reopen it safely for export?
I'll try this to see if I can get it to work.
