### ISSUE TITLE
How to connect to debugger signals

### ISSUE THREAD

**Issue by FeralBytes** [godotengine/godot#23865]
## Issue description:
Do not know how to connect to the signals that must be generated for the debugger. Things like warnings and errors. This would be really useful for Continuous Integration testing. It is not asking for exception checking. Just a way to hook into the same signals that are being produced for the Debugger.

**Comment by KellyThomas** [comment]
Do you mean `push_error()` and `push_warning()`?  
http://docs.godotengine.org/en/latest/classes/class_@gdscript.html#class-gdscript-push-error

**Comment by FeralBytes** [comment]
@KellyThomas I don't think so from there names, but since they are completely undocumented, I have no idea. I also doubt that these some how allow you to connect to them in order to know when a error or warning is raised to the debugger. Again I don't know, there is no documentation and I did not dive in the source yet to read about them.

**Comment by KellyThomas** [comment]
Thanks for clarifying. I think I have a better understanding of what you are looking for now.

**Comment by akien-mga** [comment]
Related to #6735.

**Comment by MikeSchulze** [comment]
I run i the same situation to need access to the errors.
I working on a unit test frame api  and needs access to errors where send by push_error() and push_warn()
If there exists a way to access this information?

Best regards
Mike

**Comment by KoBeWi** [comment]
There is no way to catch errors AFAIK, the best thing you could do is hacking EditorLog to check for new errors. Although if they appear as errors, there is probably some handler that can be exposed. Open a [proposal](https://github.com/godotengine/godot-proposals) if this is still desired.
