### ISSUE TITLE
[Question] What do mesh primitives expect?

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#23861]
So I (and some other people) have been searching the whole world wide web after an explanation of how mesh primitives work. What do they do? Which data do they expect? What is the difference between PRIMITIVE_TRIANGLES, PRIMITIVE_TRIANGLE_STRIP and PRIMITIVE_TRIANGLE_FAN?

**Comment by clayjohn** [comment]
There are a few decent resources for this online. [Here](http://www.dgp.toronto.edu/~ah/csc418/fall_2001/tut/ogl_draw.html) is one that has a nice illustration. [Here](https://learnopengl.com/Getting-started/Hello-Triangle) is another that explains the concept of a primitive more in the context of rendering. 

Essentially primitives tell the renderer how to treat vertex data. By default each group of three vertices will form a triangle (PRIMITIVE_TRIANGLES in Godot, or GL_TRIANGLES in OpenGL), but you can alter this to tell the renderer to treat the vertices as a group of, for example un-ordered points (PRIMITIVE_POINTS in Godot, or GL_POINTS in OpenGL), or a triangle strip where the first three points define a triangle and each subsequent point adds an entirely new triangle forming a strip (PRIMITIVE_TRIANGLE_STRIP in Godot).

**Comment by Illiander** [comment]
Are you saying that the mesh primitives are identical in what they expect to openGL?

No differences with vertex ordering or anything?

**Comment by clayjohn** [comment]
Yep, Godot uses OpenGL underneath the hood. 

As for vertex ordering, in OpenGL that is something you specify with `glFrontFace`, so it changes depending on the project, I think Godot uses Clockwise winding order.

**Comment by Chaosus** [comment]
The issue tracker is not a place for questions. I suggest to move the discussion to community channels.
