### ISSUE TITLE
Can't change preset if one of selected images have selected other than others presets 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23876]
**Godot version:**
3.1 f2cc969

**OS/device including version:**
Windows 10

**Issue description:**
When I have 3 images imported as Texture and 1 as image, then when I select all, I can't change Import options
 

**Steps to reproduce:**
https://streamable.com/zjiwn

**Comment by KoBeWi** [comment]
Texture2D and Image have different settings, we'd need something similar to MultiNodeEdit to support that. Open a [proposal](https://github.com/godotengine/godot-proposals) if this is desired.
