### ISSUE TITLE
Changing script font size in editor settings doesn't change Zoom

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23879]
**Godot version:**
3.1 f2cc969

**OS/device including version:**
Windows 10

**Issue description:**
Changing font size in editor settings doesn't change Zoom until size of text in script editor manually
 
**Steps to reproduce:**
https://streamable.com/agnhr

**Comment by akien-mga** [comment]
I wonder if it makes sense at all to show a "Zoom" value there, when it's just a ratio of font size to default font size? It might be better to simply show the font size.

**Comment by Kanabenki** [comment]
Maybe something like this, with both ? 
![2018-11-22-144300_197x47_scrot](https://user-images.githubusercontent.com/18357657/48906689-955fef00-ee65-11e8-8b20-a18d860f4854.png)
