### ISSUE TITLE
Editor file-picker crashes when thread model is "single-unsafe"

### ISSUE THREAD

**Issue by WriterOfAlicrow** [godotengine/godot#2387]
**EDIT:** I discovered that the crash only happen when the thread model is set to "single-unsafe".

Godot crashes if I try to add scripts to non-subscene objects. Seems to be an issue with empty paths, as I can add scripts to scene objects (which have a path for the scene file and naturally suggest an appropriately-named script file), but not for primitive objects.

Steps to reproduce:
* Set thread model to "single-unsafe"
* Add an Area node to your project
* Select the Area node in the "scene" tab
* Click the add-script icon
* click the ellipsis on the resultant dialog
* watch it crash

**Comment by akien-mga** [comment]
I tried to reproduce it but it does not crash for me in the current master branch. Can you still reproduce the issue?
