### ISSUE TITLE
Releasing mouse button without moving 2D object cause print to output "Move CanvasItem"

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23870]
**Godot version:**
3.1 f2cc969

**OS/device including version:**
Windows 10

**Issue description:**
I don't know if it is bug or not but when I select the 2d object(e.g. CollisionShape2D) by LMB and I didn't change mouse position and then I release this button then Godot print to output "Move CanvasItem".
 
It is little confusing for people which only select object but doesn't change its position.

**Steps to reproduce:**
https://streamable.com/4459v

**Comment by Grosskopf** [comment]
i can't replicate this under linux, but i get only integer values for position

**Comment by qarmin** [comment]
Seems to be fixed in master
