### ISSUE TITLE
Collision reported by rigidobydy are jittering

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#23882]
**Issue description:**
When checking collisions in _integrate_forces, if two bodies are colliding sometimes collisions are not properly reported, it looks like a jitter in the collision reported (alternating between reported and not reported)

**Steps to reproduce:**
After some bisecting, thanks to @sdfgeoff  we were able to track down the commit that introduces this problem: 42f2ff2f8d4123c35832b1d5bad85b827220aded

**Proposal:**
Have the distance value configurable in the project settings for this line of code:
`if (pt.getDistance() <= 0.0)`
https://github.com/godotengine/godot/blob/master/modules/bullet/space_bullet.cpp#L798
Having this number configurable will allow a more fine grained control for the users on the collision reporting. I am guessing that some projects might need that number set to zero and some others might need it set to 0.01 or another.

The comparison should probably be a solid < and not a <= to avoid floating point precision problems (not sure about this one)

CC @AndreaCatania

**Comment by aaronfranke** [comment]
> The comparison should probably be a solid < and not a <= to avoid floating point precision problems (not sure about this one)

I doubt this is the problem, but it may be a good idea to make it `<` anyway. Less than (and greater than) operations are preferable to less than or equal (and greater than or equal) operations.

**Comment by AndreaCatania** [comment]
Can you please check if this solve the problem: #23897 ?

**Comment by QbieShay** [comment]
I confirm that #23897 solves the issue, for both test cases that I have available.
Not only it fixes the problem, it improves the overall functioning of the physics (at least for my 2 test cases, as  going before https://github.com/godotengine/godot/commit/42f2ff2f8d4123c35832b1d5bad85b827220aded still presented some issues, while with this pull request the projects show a better (and expected) behaviour.)
