### ISSUE TITLE
str(engine_type) should return a precise type name (like 'Sprite') instead of 'GDNativeClass'

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#2388]
`str(engine_type)` should return `'engine_type'` (for example `'Sprite'`) instead of `'GDNativeClass'`.
`engine_type.get_type()` already return `'GDNativeClass'`.

A method `Object::get_class()` could be useful for obtain a reference to the native class (not only its name) from an instance.

**Comment by akien-mga** [comment]
Please use more description issue titles, "Reflection" does not say much about the contents.

**Comment by punto-** [comment]
He tried to render some reflections with Godot Engine, you won't believe
the bug he had!

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/837, as feature proposals are now tracked on the Godot proposals repository.
