### ISSUE TITLE
Script automatically deleted after attaching it to a node

### ISSUE THREAD

**Issue by Scozor** [godotengine/godot#23883]
**Godot version:**
3.0.6 Mono

**OS/device including version:**
Windows 10 x64

**Issue description:**
Hi,

I discovered a problem regarding attaching scripts to nodes and after they are automatically removed.

This problem occurs when we have an accent in the project name.

Sorry for my bad english, i'm french.

**Steps to reproduce:**
1. Create a new project with an accent in the project name.
2. Try to add script on a node.
3. Observe in the inspector that the script was not attached to the node

**Comment by KoBeWi** [comment]
This seems to have been fixed in 3.1.
