### ISSUE TITLE
"!id_map.has(p_rid.get_data())" error with YSort populating during runtime

### ISSUE THREAD

**Issue by FlamyAT** [godotengine/godot#23889]
**Godot version:** 03bd4d2

**OS/device including version:** Ubuntu

**Issue description:**
Creating and adding `Node2D`s to a `YSort` after setting up the tree, will result in a spam in the debugger with the following error:
```E 0:00:00:0793   Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
  <C Source>     ./core/rid.h:164 @ getornull()
  <Stack Trace>  Player.gd:31 @ _physics_process()
``` 
(The last line is just my debug script)

The following image should illustrate my issue/concern:
![image](https://user-images.githubusercontent.com/8056898/48861128-25009180-edc3-11e8-97eb-a4a0195b94fc.png)

**Steps to reproduce:**
Create a new scene with `YSort` as the base node.
Include `add_child(Node2D.new())` in any function which is called after the tree is initialized (e.g. not `ready`)
Look at the errors in the debugger.

**Comment by bojidar-bg** [comment]
Will look into it during the weekend (or a bit after it), sorry for the delay so far.
