### ISSUE TITLE
Godot crashes when opening directory with nativescript in it.

### ISSUE THREAD

**Issue by kimamb** [godotengine/godot#23886]
_Originally posted by @kimamb in https://github.com/godotengine/godot/issues/21095#issuecomment-440465551_

_Originally posted by @karroffel in https://github.com/godotengine/godot/issues/21095#issuecomment-440568519_

I made a simple C++ script by following a tutorial on youtube. I'm new to the Godot engine. The program just prints "Hello World".

However Godot crashes when clicking into the directory the files are located in.

**Comment by Zireael07** [comment]
Provide the details instead of just linking to someone else's comment.

**Comment by kimamb** [comment]
Yeah sorry, I'm typing out the details now.

**Comment by kimamb** [comment]
I'm using the source code 
```
#include <Godot.hpp>
#include <Reference.hpp>

using namespace godot;

class SimpleClass : public Reference {
    GODOT_CLASS(SimpleClass, Reference);
public:
    SimpleClass() { }

    /* _init must exist as it is called by Godot */
    void _init() { }

    void test_void_method() {
        Godot::print("This is test");
    }

    Variant method(Variant arg) {
        Variant ret;
        ret = arg;

        return ret;
    }

    static void _register_methods() {
        register_method("method", &SimpleClass::method);
        
        /**
         * How to register exports like gdscript
         * export var _name = "SimpleClass"
         **/
        register_property<SimpleClass, String>("base/name", &SimpleClass::_name, String("SimpleClass"));

        /* or alternatively with getter and setter methods */
        register_property<SimpleClass, int>("base/value", &SimpleClass::set_value, &SimpleClass::get_value, 0);

        /** For registering signal **/
        // register_signal<SimpleClass>("signal_name");
        // register_signal<SimpleClass>("signal_name", "string_argument", GODOT_VARIANT_TYPE_STRING)
    }
    
    String _name;
    int _value;

    void set_value(int p_value) {
        _value = p_value;
    }

    int get_value() const {
        return _value;
    }
};

/** GDNative Initialize **/
extern "C" void GDN_EXPORT godot_gdnative_init(godot_gdnative_init_options *o) {
    godot::Godot::gdnative_init(o);
}

/** GDNative Terminate **/
extern "C" void GDN_EXPORT godot_gdnative_terminate(godot_gdnative_terminate_options *o) {
    godot::Godot::gdnative_terminate(o);
}

/** NativeScript Initialize **/
extern "C" void GDN_EXPORT godot_nativescript_init(void *handle) {
    godot::Godot::nativescript_init(handle);

    godot::register_class<SimpleClass>();
}

```

from https://github.com/GodotNativeTools/godot-cpp#compiling-the-cpp-bindings-library

**Comment by akien-mga** [comment]
What's your Godot version? What OS? Please fill our issue template when reporting an issue.

CC @karroffel

**Comment by kimamb** [comment]
@akien-mga
This one:

    Operating system
    Device (including architecture, e.g. x86, x86_64, arm, etc.)
    GPU model (and driver in use if you know it)

?

OS: Kubuntu 18.04
Device: Desktop Computer x86_64
GPU: nVidia GTX 960 4GB (390.77)

**Comment by karroffel** [comment]
@kimamb you didn't state the Godot version. If you are using 3.0 then the code won't work, as NativeScript 1.1 such as you are using it requires Godot 3.1

**Comment by kimamb** [comment]
> @kimamb you didn't state the Godot version. If you are using 3.0 then the code won't work, as NativeScript 1.1 such as you are using it requires Godot 3.1

I'm so sorry, I used the Steam release, as I thought it was the most recent release.
I downloaded the 3.1 release and it doesn't crash on selecting the folder

Thank you so much, I'm sorry for having wasted your time.
