### ISSUE TITLE
Could not obtain an OpenGL 3.3 context!

### ISSUE THREAD

**Issue by ouck02** [godotengine/godot#23892]
Hello

I have OpenGL 4.5 but godot didn't start. I've updated my GPU driver to the last one, same error:

$ flatpak run org.godotengine.Godot
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERROR: initialize: Could not obtain an OpenGL 3.3 context!
   At: platform/x11/context_gl_x11.cpp:163.
ERROR: initialize: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:147.
ERROR: initialize: Your system's graphic drivers seem not to support OpenGL 3.3 / OpenGL ES 3.0, sorry :(
Try a drivers update, buy a new GPU or try software rendering on Linux; Godot will now crash with a segmentation fault.
   At: drivers/gles3/rasterizer_gles3.cpp:157.
**ERROR** OS_Unix::execute - Could not create child process while executing: xmessage
OpenGL ES 3.0 Renderer: 
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/libc.so.6() [0x35a1c32ff0] ()
-- END OF BACKTRACE --
/app/bin/godot: line 3:     4 Aborted                 (core dumped) /app/bin/godot-bin

Godot 3.0.6 (flatpak)
Linux Mint 19
AMD RX480
Driver AMDGPU-PRO 18.40.2.15
OpenGL ES profile version string: 4.5.13540 Compatibility Profile Context 18.40.2.15

**Comment by akien-mga** [comment]
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
That indicates a problem with your system, your graphics drivers setup is broken. What's the output of `glxinfo`? Do you get similar error?

Did you update your drivers right before trying to launch Godot? If so you might need a reboot.

Otherwise maybe it's flatpak's sandboxing preventing the proper use of the AMDGPU-PRO driver, but then it should be reported upstream to the flatpak distributor.

**Comment by akien-mga** [comment]
> Otherwise maybe it's flatpak's sandboxing preventing the proper use of the AMDGPU-PRO driver, but then it should be reported upstream to the flatpak distributor.

If so you should report it here: https://github.com/flathub/org.godotengine.Godot/
(provided you had your flatpak from FlatHub).

**Comment by aaronfranke** [comment]
Test if the problem occurs if you manually download Godot and run the executable, without Flatpak.

**Comment by ouck02** [comment]
Godot works without Flatpak. I will create an issue here: https://github.com/flathub/org.godotengine.Godot/
Thank's for helping !
