### ISSUE TITLE
iOS orientation: sensor mode issue on start game

### ISSUE THREAD

**Issue by etalot** [godotengine/godot#23894]
**Godot version:**
3.0.6(impossible to build iOS with 3.1alpha on this moment(22-Nov-18))

**OS/device including version:**
iOS 9.3.2/iPhone SE

**Issue description:**
Thank GOD!OT! we can easy create universal resolution game!

![godot_orientation_settings](https://user-images.githubusercontent.com/5445916/48885276-54aea880-ee5a-11e8-81b7-da345cfbfcd0.jpg)

But issue exists on iOS:

![20181122_101833](https://user-images.githubusercontent.com/5445916/48885306-727c0d80-ee5a-11e8-98df-2ffb82919920.jpg)

If Godot starts when device is in landscape(physically rotated device 90 degree left or right), Godot still thoughts he is in portrait mode(doesn't catch screen changing on start that iOS make for animation):
get_viewport().size is (640, 1136), but must be (1136, 640)

Just check **video demonstration**: https://youtu.be/UaRU-FrEOcU

Xcode 6.3.2: target iOS 8.3(5.0 same issue)

![godot_xcode_settings](https://user-images.githubusercontent.com/5445916/48885331-832c8380-ee5a-11e8-9eea-36439c70aecc.jpg)

This happen only on start. Looks like Godot doesn't catch iOS screen resolution changing on start.

Godot iOS debug log:
*********** main.m
running app main
after init super 0x14d86b030
******** screen size 640, 1136
after init gles 0x14d86b030
******** adding observer for sound routing changes
******** adding observer for keyboard show/hide
glview is 0x14d86b030
Path: /var/containers/Bundle/Application/1D2F7713-349D-4FF6-9A6C-299B2D8C26B0/test.app
godot_iphone /var/containers/Bundle/Application/1D2F7713-349D-4FF6-9A6C-299B2D8C26B0/test.app/test
cwd /private/var/containers/Bundle/Application/1D2F7713-349D-4FF6-9A6C-299B2D8C26B0/test.app
os created
setting data dir to /var/mobile/Containers/Data/Application/0310C86C-E365-4A73-930C-7E3F4E649D71/Documents from /var/mobile/Containers/Data/Application/0310C86C-E365-4A73-930C-7E3F4E649D71/Documents
setup 0
cadisaplylink: 1start animation!
 ******** screen size 640, 1136
2018-11-21 14:26:55.711 test[1842:1161392] +[CATransaction synchronize] called within transaction
2018-11-21 14:26:55.725 test[1842:1161392] +[CATransaction synchronize] called within transaction
OpenGL ES 3.0 Renderer: Apple A9 GPU
Boot splash path: res://icon.png
2018-11-21 14:26:56.264 test[1842:1161392] _BSMachError: (os/kern) invalid capability (20)
2018-11-21 14:26:56.731 test[1842:1161392] _BSMachError: (os/kern) invalid name (15)
2018-11-21 14:26:56.732 test[1842:1161392] _BSMachError: (os/kern) invalid name (15)
2018-11-21 14:26:56.734 test[1842:1161392] _BSMachError: (os/kern) invalid name (15)
**ERROR**: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6383:_render_target_allocate() - Condition ' status != 0x8CD5 ' is true.
**ERROR**: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6383:_render_target_allocate() - Condition ' status != 0x8CD5 ' is true.
get_viewport().size: (640, 1136)
OS.window_size: (640, 1136)

**Steps to reproduce:**
Use "Minimal reproduction project"(see below)

**Minimal reproduction project:**
I use Godot "Screen sizes" example with adding litle debug panel:

[Screen-sizes-example.zip](https://github.com/godotengine/godot/files/2606798/Screen-sizes-example.zip)

**Comment by samgreen** [comment]
This should be resolve with the orientation changes made in #22784

**Comment by etalot** [comment]
Thanks! I will test this few days later and will report.

**Comment by akien-mga** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
