### ISSUE TITLE
Websocket too much latency for outgoing packets.

### ISSUE THREAD

**Issue by simpleyo** [godotengine/godot#23898]
**Godot version:**
v3.1.dev.custom_build.c00edd9

**OS/device including version:**
Windows 7 Ultimate x64

**Issue description:**
Using WebSocketClient and WebSocketPeer.
If we send a packet A to the server (localhost) and the server immediately responds with another packet B. The time between the sending of packet A and the reception of packet B is of the order of tens of milliseconds. Around 30-50 ms in the tests that I have done. The expected time should be a few milliseconds, not tens.

I think this should be classified as a bug because such a large latency does not seem to be normal.

**Steps to reproduce:**
[test_websocket.zip](https://github.com/godotengine/godot/files/2608214/test_websocket.zip)

**Comment by Calinou** [comment]
The client's frame rate can have an impact on the measured/effective latency (this is not specific to Godot, I've seen this in many other games). Try disabling V-Sync to get as much FPS as possible, then measure again. (I'll try the example project when I get back home.)

**Comment by akien-mga** [comment]
CC @godotengine/network

**Comment by simpleyo** [comment]
Client's frame rate 

> 
> 
> The client's frame rate can have an impact on the measured/effective latency (this is not specific to Godot, I've seen this in many other games). Try disabling V-Sync to get as much FPS as possible, then measure again. (I'll try the example project when I get back home.)

The  client's frame rate is not the problem, I have checked it.

**Comment by CptPotato** [comment]
> I wonder if a solution to this would be to keep vsync enabled and call WebSocketClient.poll a few times on every call to _process.

Probably not since process will still be called just at the framerate of the application.

Since you're measuring the time from _process this delay is in an expected range in my opinion.
To get better latencies you'd have to run the packet handling logic at higher rates than the framerate (which is probably what other engines do, aswell), at least for the sever.

**Comment by simpleyo** [comment]
> 
> Probably not since process will still be called just at the framerate of the application.
> 
> Since you're measuring the time from _process this delay is in an expected range in my opinion.
> To get better latencies you'd have to run the packet handling logic at higher rates than the framerate (which is probably what other engines do, aswell), at least for the sever.

I've tried it and it reduces the average latency a lot. There are some peaks but in general it works. It helps a lot if _process takes a significant amount of the frame time and calls to poll can be distributed in that time.

**Comment by simpleyo** [comment]
Even with vsync disabled, the average latency is too big (order of tens of ms) when more than 60 packets are sent per second. Can that be a bug? Or has it been designed in that way?.

**Comment by simpleyo** [comment]
With vsync enabled, average latency does not stop growing steadily when more than 60 packets are sent per second. Is it a bug? or has it been designed that way?

**Comment by simpleyo** [comment]
> 
> How much data are you sending in those 60 packets?
> WebSocket uses TCP, so If the network connection can't send that much data at a given step, the leftover will be queued and sent at the next step (plus buffers will start to fill, till they get full, and then packets will be dropped, and you might get disconnected).

I am sending a few bytes (not more than 8) per packet.
