### ISSUE TITLE
OSX_ENABLED not defined for server build on OSX

### ISSUE THREAD

**Issue by 0joshuaolson1** [godotengine/godot#2390]
Error: MSG_NOSIGNAL undefined
Reason: OSX_ENABLED not defined for server build on OSX. In drivers/unix/stream_peer_tcp_posix.cpp:
# if defined(OSX_ENABLED) || defined(IPHONE_ENABLED)

```
#define MSG_NOSIGNAL    SO_NOSIGPIPE
```

...
Error StreamPeerTCPPosix::write(const uint8_t\* p_data,int p_bytes, int &r_sent, bool p_block) {
...
    while (data_to_send) {
        int sent_amount = send(sockfd, offset, data_to_send, MSG_NOSIGNAL); /////ERROR HERE

Fix:

In platform/server/detect.py, replace

env.Append(CPPFLAGS=['-DSERVER_ENABLED','-DUNIX_ENABLED'])

with

if (env["osxserver"]=="yes"):
    env.Append(CPPFLAGS=['-DSERVER_ENABLED','-DUNIX_ENABLED','-DOSX_ENABLED'])
else:
    env.Append(CPPFLAGS=['-DSERVER_ENABLED','-DUNIX_ENABLED'])

and put the following in SConstruct:

opts.Add('osxserver','Required workaround on OSX when platform=server (yes/no)','no')

and add osxserver=yes to the scons command for this case.

One could use a different platform argument instead of adding this special case kludge, and I'm sure someone knows the preferred coding style or a better approach, which is why I'd appreciate some feedback before I make a pull request.

**Comment by akien-mga** [comment]
Adding an "osxserver" argument would not be enough as like you showed in the code snippet, the argument would also be needed for the iphone platform. On the other hand I don't have much better idea for an argument name, and I'm not sure if adding an argument would be best or if we should try to autodetect the build platform.

@punto- any idea?

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
I've opened #11389 as a clearer issue regarding making the headless/server version run on macOS and Windows too.
