### ISSUE TITLE
Variable invalidation directly assigned in Visual script in the latest version of godot master

### ISSUE THREAD

**Issue by haizhou37** [godotengine/godot#23903]
**Godot version:**
the latest version of godot master（22:00, 22/11/2018）

**OS/device including version:**
manjaro gnome x64
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile
intel hd 3000

**Issue description:**
![peek 2018-11-22 22-00](https://user-images.githubusercontent.com/33272474/48908505-65384080-eea5-11e8-9b39-138ef8b39e36.gif)
![2018-11-22 22-01-13](https://user-images.githubusercontent.com/33272474/48908511-6e291200-eea5-11e8-9851-19b9c0015422.png)

In addition, if the project is restarted (It's not closing the script), the variable value is changed back to the default value (such as vector3 (0 ,0 ,0))

**Steps to reproduce:**
Open the visual script, call a node function that can set parameters, and finally run。

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2608404/Test.zip)

**Comment by henriiquecampos** [comment]
I can confirm. whenever setting the value directly, is completely ignored in run time.

![image](https://user-images.githubusercontent.com/10171059/50548289-398d4080-0c31-11e9-811f-f5e2a2a647f4.png)

![image](https://user-images.githubusercontent.com/10171059/50548292-4a3db680-0c31-11e9-8009-b11490291bda.png)

**Note nothing is printed in the output**
![image](https://user-images.githubusercontent.com/10171059/50548305-82dd9000-0c31-11e9-812b-691e9445d6c1.png)

![image](https://user-images.githubusercontent.com/10171059/50548321-a274b880-0c31-11e9-8c14-51f9769c43b5.png)

**Note `test` is printed in the output**
![image](https://user-images.githubusercontent.com/10171059/50548328-c59f6800-0c31-11e9-85c4-7cf96e0bd6be.png)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

**Comment by kreaninw** [comment]
> Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

I can't reproduce this in Godot 3.2.4 rc1 as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/106401980-1633b180-6406-11eb-9d20-e6a582d6f0dd.mp4
