### ISSUE TITLE
Pressing "Ctrl+S" to save while in script editor makes it inactive.

### ISSUE THREAD

**Issue by leiget** [godotengine/godot#23908]
**Godot version:**
8180e5e

**OS/device including version:**
Xubuntu 16.04

**Issue description:**
When I press "Ctrl+S" to save the scene while the script cursor is in the script editor window, after the saving is done the script cursor is no longer active in the script editor, and instead the last active element (whether it be a node setting, node, or anything else) is now reselected and if you were to press any keys, it would affect that element and not the script editor.

**Steps to reproduce:**

- Attach a script to a node.
- Open the script editor(F3)
- Write a few lines
- Click on any property of that node in the inspector and then press up or down a couple of times on your keyboard so that the blue outline moves across the properties. 
- Go to the script editor and make sure the script editor is active with the blinking script cursor
- Press "Ctrl+S"
- See if the script editor is still active.

**Minimal reproduction project:**
Works on any project.

**NOTES:**
I've noticed that sometimes the active element will switch back to the last active element when I leave the cursor in the script editor for a couple of seconds. The cursor will blink two times and then do the switch.

I also noticed that it happens sometimes when I move the script editor cursor with the keyboard keys. I think this bug has to do with the keyboard keys, somehow.

I've also found out that you have to do all this with the node that contains the script that is currently being edited (I've edited my steps above to reflect this).
For example, if you have an area node, and then you add a script to that node, and then if you have that script open and that node selected, this bug will occur.

**Comment by akien-mga** [comment]
This doesn't seem reproducible in Godot 3.2, assuming fixed since then.
