### ISSUE TITLE
[Script Editor] Can't zoom with "Ctrl++"

### ISSUE THREAD

**Issue by FlamyAT** [godotengine/godot#23905]
**Godot version:** da31d63

**OS/device including version:** Ubuntu

**Issue description:**
While it is possible to zoom freely with `Ctrl` + mouse wheel, only `Ctrl` + `-` works. Trying to use `Ctrl` + `+` does not effect the script editor window at all.

**Steps to reproduce:**
Open any script in the editor.
Try to zoom with `Ctrl` + `+`.

**Comment by akien-mga** [comment]
If that doesn't work on your keyboard layout, you can change the default hotkey:
![screenshot_20181122_193231](https://user-images.githubusercontent.com/4701338/48918512-5ba2de80-ee8d-11e8-92a0-d7f8e9bc5434.png)

**Comment by FlamyAT** [comment]
> What's your keyboard layout? The shortcut for zoom in is Ctrl+=, since + is not a direct access key (would be Ctrl+Shift+= to access it on QWERTY.

I didn't know that you can use `=` instead of `+`. I tried the `Ctrl`+`Shift`+`0`/`=`, it still didn't zoom in.


> Perhaps he's using the Numpad for zooming, which does not have `=` but does have `+`.
> 
> Is there an easy way that we can make both versions work?

I'm not using the numpad's `+`.

**Comment by akien-mga** [comment]
What's your keyboard layout?

**Comment by FlamyAT** [comment]
QWERTZ
The shortcut works in the browser though

**Comment by akien-mga** [comment]
Yeah for German QWERTZ you should rebind the hotkey yourself, `<kbd>+</kbd>` is directly accessible there while `<kbd>=</kbd>` isn't. I'm not sure how other toolkits do it but in Godot's there's no easy way to handle that that I know of.

**Comment by FlamyAT** [comment]
Rebound it to `+` but it still doesn't zoom in

**Comment by akien-mga** [comment]
Works for me on Linux with `setxkbmap de`:
![screenshot_20181122_220023](https://user-images.githubusercontent.com/4701338/48921729-032a0c00-eea2-11e8-8356-b9cfadaa8455.png)

**Comment by FlamyAT** [comment]
Now a new issue occurred:
Trying to change any of the zoom settings results in no change at all.
![image](https://user-images.githubusercontent.com/8056898/48921817-abd86b80-eea2-11e8-8d91-43755d2c8c29.png)
I set it to `Ctrl` + `1`/`2` for debug purposes, but it still doesn't respond. But I can still use `Ctrl` + `-` even though it's clearly unbound

**Comment by akien-mga** [comment]
You're changing the Canvas Item Editor zoom hotkey, not the Script Editor's.

**Comment by FlamyAT** [comment]
Now, I feel stupid. I'm sorry, but is there any way to detect QWERTZ keyboards automatically to change the default keybinding?
