### ISSUE TITLE
New childs of containers Should be selectable with visible but not editable occupation box. 3.1

### ISSUE THREAD

**Issue by TextusGames** [godotengine/godot#23902]
**Godot version:** 3.1
**OS/device including version:** Any

**Issue description:**
I believe disabling the selection of childs of UI containers has many drawbacks.
I was trying to work with HBoxContainer and add there several childs and i was very frustrating experience. 
Firstly I added empty child object into container i was searching it  for  some time before i realize that there just no visual marker of it (but then you are working with UI it is expected). 
Ok i added some grathic, then my object is shown but i can't selct it ( i expected to do that, becose there were no visual mark of that object is not selected). 
Then i added several combination of visible and not visible childs, and then i realized that now i cant even know which object on the screen refers to object in Scene tree ( i can select object in scene tree but since no boundary box is appearing around selected object it is hard to know which one i have selected, and i can not select objects directly in scene).
It is also hard to know how much screen space each object is occuping.
For new comers it can be very not undestandble and unclear behaviour.

Turns out disabling selection of childs of containers give much more trouble then benefit.

That is why i think some things need to be done with DIIRECT childs of containers.
1. If object occupies no screen space there anyway must be some visual representation of it in scene view if that object is selected.
2. Child objects of containers should be selectable
3. There should be a different kind of boundory box (for example with doted lines which not allows to modify control node but shows the screen space that this object is occuping)

**Steps to reproduce:** Create any UI container and add several childs to it and ty to work with them. 
**Minimal reproduction project:** Any ui with containers.

Here is example in there i cant even understand which child object of control is there and how much screen space it is occuping ( it would be even more difficult if i do not add semi transparent ColorRects):
![ui_issue](https://user-images.githubusercontent.com/34438607/48904640-12906180-ee70-11e8-9f0f-8f37cdc95bfc.PNG)

Here how it should look like. ( it is done so in unreal )
![ui_example](https://user-images.githubusercontent.com/34438607/48904762-7adf4300-ee70-11e8-8c24-1ecd7c3ba7ad.png)

**Comment by volzhs** [comment]
same issue with #23606 and it's fixed.

**Comment by akien-mga** [comment]
Which is why it's important to be explicit about the version, not just say "3.1" (which would be 3.1-stable, not released yet).
