### ISSUE TITLE
AnimationPlayer Doc + Key

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#23909]
**Godot version:**
![image](https://user-images.githubusercontent.com/13235119/48917617-9a319c80-ee7f-11e8-9f72-46e106cefab0.png)

**OS/device including version:**
Win7-64

**Issue description:**
From latest doc: https://docs.godotengine.org/en/latest/tutorials/animation/introduction_2d.html
There is a difference with current panel
![image](https://user-images.githubusercontent.com/13235119/48917589-779f8380-ee7f-11e8-8027-02fdf98cd84a.png)

I select 1 key from Inspector and I use this 
![image](https://user-images.githubusercontent.com/13235119/48918230-2ee9c980-ee83-11e8-83dc-a8d2f5acd524.png)

to add the first key, then I select another key from Inspector and I clicked again that icon. Godot ask me if I want to add the previous key - not the current selected.

Also if I delete AnimationPlayer node in the main panel remain its icons
![image](https://user-images.githubusercontent.com/13235119/48918013-c4845980-ee81-11e8-9909-d0da3262cd8f.png)

**Steps to reproduce:**
Add node AnimationPlayer to a 2d scene

**Minimal reproduction project:**
NA

**Comment by KoBeWi** [comment]
@git2013vb Could you clarify this part with more details?
> to add the first key, then I select another key from Inspector and I clicked again that icon. Godot ask me if I want to add the previous key - not the current selected.

Or at check if this still happens in 3.2.2.

Also the issue with icons is not a bug, because they are related to the Animation tab not AnimationPlayer.

**Comment by git2013vb** [comment]
I switched to Linux so I can't check if the problem still exist. Also the documentation is changed and this is a doc related issue. Ill close it.
If happen again ill open a new issue.
