### ISSUE TITLE
store_csv_line() added unnecessary double quotes to the file.

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#23900]
**Godot version:**

master commit 11d7738 

**Issue description:**

New function store_csv_line() added unnecessary double quotes to the file.

**Simple script:**
```
func _ready() -> void:
	var lang = PoolStringArray(["id", "en", "ru"])
	var file = File.new()
	file.open("res://test.csv", file.WRITE)
	file.store_csv_line(lang)
	file.close()
```
test.csv: "id","en","ru"
expected: id,en,ru

**Comment by Kanabenki** [comment]
My bad, I forgot to compare against -1 when I added the check for `\n`.
