### ISSUE TITLE
Improve Node Selection via Plugin Script

### ISSUE THREAD

**Issue by remorse107** [godotengine/godot#23913]
Currently working on a plugin that will be a Node2D type because I want the custom draw and nothing else.  I can see plugins wanting to do this, but the plug-in support for node selection from the canvas feels "second class" compared to the other built-in types.

Requesting a feature to support improved selection in the editor from within the plugin script. 

![godot](https://user-images.githubusercontent.com/7462993/48922988-305dc680-ee70-11e8-9165-d9964feba9a9.gif)

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/15599.
