### ISSUE TITLE
Image::create_from_data size mismatch ('expected data size of' error)

### ISSUE THREAD

**Issue by exts** [godotengine/godot#23911]
**Godot version:**
3.1 Alpha 1

**OS/device including version:**
Windows 10

**Issue description:**
Trying to load an image from `user://` using `File` then creating an image from buffer data is error out.

**Steps to reproduce:**
1. load image file from `user://` using `File`
2. create a new image from data and pass use mipmaps as true, format etc and pass the buffer data
3. You can stop here, but try creating an image texture from the image and a sprite from said texture then displaying the sprite to the scene

**Work around**
```
img.create(526, 890, true, Image.FORMAT_ETC)
img.load_png_from_buffer(content)
```

**Other Notes**

Looks like this was fixed with https://github.com/godotengine/godot/pull/12754 but only for the `create` method.

**Minimal reproduction project:**

[FLTest1.zip](https://github.com/godotengine/godot/files/2609093/FLTest1.zip)

**Comment by exts** [comment]
@akien-mga is it possible for this to make 3.1?

**Comment by jackwilsdon** [comment]
Here's the code from the test project for reference;

```GDScript
var file = File.new()

file.open("user://cache/1000.png", file.READ)
var content = file.get_buffer(file.get_len())
file.close()
	
var img = Image.new()
img.create_from_data(526, 890, true, Image.FORMAT_ETC, content)
```

The error you're seeing is expected, as you're trying to create an image in the format `FORMAT_ETC` using data which is not in that format (i.e. raw PNG data including headers, etc). `create_from_data` doesn't do any conversion, and just expects the image data in the format passed to it.

Your "workaround" is the correct way to do it, but you don't need to call `image.create` as `load_png_from_buffer` handles image creation;

```GDScript
var img = Image.new()
img.load_png_from_buffer(content)
```

If you want to load a PNG and convert it to something else, you can use `convert` or `compress`.

---

A simpler way of loading images from userdata is just using `Image.load`;

```GDScript
var img = Image.new()
img.load("user://cache/1000.png")
```

**Comment by exts** [comment]
Yeah you're right, just tested by converting the image to that format. I will note that you cannot call img_png_from_buffer as a static method, godot complaints with that exact error.
