### ISSUE TITLE
Inspector 'revert' button overlaps with 'add animation key' button

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#23919]
**Godot version:**

14cf450

**OS/device including version:**

Manjaro x86_64

**Issue description:**
![image](https://user-images.githubusercontent.com/43379543/48938148-df6ad280-ef42-11e8-9b34-909266e96625.png)

**Comment by reduz** [comment]
This is likely easy to fix, in editor_inspector.cpp, class EditorProperty

**Comment by akien-mga** [comment]
Fixed by #24085.
