### ISSUE TITLE
Array editor should initialise new elements contextually when increasing array size

### ISSUE THREAD

**Issue by mikica1986vee** [godotengine/godot#2391]
When increasing size of Array, type of new element should copy the type of the previous element (if it exists). Now it initializes to Nil.

**Comment by akien-mga** [comment]
I'm not sure if this would be a consensual behaviour, but it's worth discussing.

**Comment by mikica1986vee** [comment]
I think this is reasonable "default". Most times your array will hold one element type or "array" of types ([0] NodePath, [1] float, [2] NodePath, [3] float...). Defaulting to no type is, in my opinion, most user unfriendly convention. 

As a simpler solution, copying previous element is simple, but looks and feels lazy.

**Comment by akien-mga** [comment]
Copying the previous element sounds like Excel to me, and I'm not sure that's what one would expect in a real development environment. Devs are using to the fact that when you create a fixed size array, the new indexes are uninitialized or initialized to Nil.

But then I haven't played around much with the array editor, so I might be missing something here.

**Comment by mikica1986vee** [comment]
Initialize 20+ element array. :D

After that, if you are not convinced, resize it to zero and do it again element by element. :D

That's why, in my opinion, defaulting to nil is the worst case for usability.

**Comment by vnen** [comment]
I agree with @mikica1986vee. Since you have to select the type from a dropdown list, it'd be easier if it defaults to the last used type. To be initialized with `Nil` makes less sense, since rarely you would add a new element to be empty. It is indeed more common to add an element of the same type.
