### ISSUE TITLE
Resizing CSGBox using handles won't update the inspector

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#23918]
**Godot version:**

14cf450

**OS/device including version:**

Manjaro x86_64

**Issue description:**

Expected: click and drag handles (red dot) on the CSGBox would update its size in the inspector
Happened: it doesn't update. must reselect the node first.

**Steps to reproduce:**
1. New CSGCombiner and CSGBox child
2. Resize CSGBox using handle, see its `width`, `height`, and `depth` property.

**Comment by hoontee** [comment]
Not reproducible in 3.2.3 RC 6.

**Comment by akien-mga** [comment]
Assuming fixed. Please comment if still reproducible.
