### ISSUE TITLE
KinematicBody doc talks about pixels per second, which does not apply in 3D

### ISSUE THREAD

**Issue by fluxrider** [godotengine/godot#23927]
https://github.com/godotengine/godot/blob/c48027af922a7203dc53bc41435a9d9021ba3291/doc/classes/KinematicBody.xml#L92

**Comment by akien-mga** [comment]
I guess it's meant to be "distance unit per second" (which would typically be a meter unless physics are configured differently).

**Comment by aaronfranke** [comment]
How about:

> [code]linear_velocity[/code] is a value of speed. Unlike in [method move_and_collide], you should [i]not[/i] multiply it with [code]delta[/code] — the physics engine handles applying the velocity.

Simple for casual users, and for advanced users, it hints about what happens under the hood.

**Comment by fluxrider** [comment]
Building on the suggestion from @aaronfranke I'd still give an example.
"... is a value of speed (typically meters per seconds)."

**Comment by Juankz** [comment]
I would rather specify:
"is a value in pixels per second (2D) or meters per second (3D)"
