### ISSUE TITLE
Se cierra erroe GLSL2 Nvidia OpenGL driver lost connection with the display

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#23921]
**Godot version:**

El problema es que al poner gles2 en proyectos en 3D se cierra el editor y dice que el nvidia kernel graphic dejo de funcionar...
Placa de video geforce nvidia 9800 gt
dice error de open GL

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

![2018-11-23 08_32_03-greenshot](https://user-images.githubusercontent.com/12847027/48944110-369d8280-ef04-11e8-832e-8af1f33084ab.jpg)
![2018-11-23 08_37_10-c__users_ariel_desktop_tutoriales godot_godot 3 0 2_godot 3 0 estable_godot 3 1](https://user-images.githubusercontent.com/12847027/48944113-3ac9a000-ef04-11e8-9340-78052260ef6a.jpg)
![2018-11-23 08_38_14-greenshot](https://user-images.githubusercontent.com/12847027/48944119-3dc49080-ef04-11e8-896a-d5c951c1411a.jpg)

**Comment by kone9** [comment]
Lastima que no se puedan poner imagenes de referencia

**Comment by kone9** [comment]
Se rompieron todos los proyectos al poner GLSL2 en la ultima versión alpha de GODOT.....Nisiquiera puedo usar un proyecto nuevo que se cierra y salta el error the NVIDIA drivers lost connection with the display drivers due to exceeding the windows time-out limit and is unavble to continue the aplication must close

placa de video geforce 9800GT

**Comment by akien-mga** [comment]
Please write in English and fill the issue template.

**Comment by kone9** [comment]
Projects were broken when using GLSL2.
nvidia kernel graphic It stopped working
video geforce 9800 gT

**Comment by kone9** [comment]
can you put pictures here?

**Comment by kone9** [comment]
![2018-11-23 08_32_03-greenshot](https://user-images.githubusercontent.com/12847027/48944074-166dc380-ef04-11e8-9a98-12add73174f1.jpg)
![2018-11-23 08_37_10-c__users_ariel_desktop_tutoriales godot_godot 3 0 2_godot 3 0 estable_godot 3 1](https://user-images.githubusercontent.com/12847027/48944079-1b327780-ef04-11e8-887e-4026b8bd0287.jpg)
![2018-11-23 08_38_14-greenshot](https://user-images.githubusercontent.com/12847027/48944082-1f5e9500-ef04-11e8-8f9b-4a20e8013388.jpg)

**Comment by akien-mga** [comment]
There's an error in your script, see the ping "SCRIPT ERROR" message.

For the GLES2 issue, try to remove the `default_env.tres` file.

**Comment by kone9** [comment]
ok,thanks...in the end it does not work for me, yes or if I have to use glsl3 ... thanks for the answer ....

**Comment by aaronfranke** [comment]
https://www.geforce.com/hardware/desktop-gpus/geforce-9800gt/specifications

GeForce 9800 GT website says:

>Feature Support

> OpenGL 2.1

Try switching to GLES 2.0 renderer. Also, try updating GPU drivers.

**Comment by lupoDharkael** [comment]
is this issue still relevant with the current version?

**Comment by kone9** [comment]
> is this issue still relevant with the current version?
In version 3.1 of godot already works thanks

**Comment by bojidar-bg** [comment]
Closing as fixed as per the above comment.
