### ISSUE TITLE
GLES 2, strange render with transparent image in 2d mode

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#23938]
**Godot version:**

Godot 3.1 master c48027a

**OS/device including version:**

Xubuntu 16.04.5 LTS, Nvidia GTX 750 Ti, proprietary driver ver. 390.87

**Issue description:**

GLES 2, strange render with transparent image in 2d mode:
![gles2](https://user-images.githubusercontent.com/1049442/48959153-ce937e80-ef8d-11e8-9d10-426abbed6246.png)
![gles3](https://user-images.githubusercontent.com/1049442/48959154-ce937e80-ef8d-11e8-94cd-2a833c08fb59.png)
In played scene looks as expected.

**Steps to reproduce:**
Open attached project.

**Minimal reproduction project:**
[godot_3.1_gles2.zip](https://github.com/godotengine/godot/files/2611623/godot_3.1_gles2.zip)

**Comment by akien-mga** [comment]
Seems fixed in the current master branch (32fa136) on Mageia 7, GTX 670MX with drivers 410.x.

Please comment if you can still reproduce it.
