### ISSUE TITLE
Incorrect argument type in the _init method 

### ISSUE THREAD

**Issue by mineevgleb** [godotengine/godot#23947]
**Godot version:**
v3.1 alpha2

**OS/device including version:**
Windows

**Issue description:**
Here is the minimal reproduction script:

```
class_name Foo

class Bar:
	func _init(a:Foo): 
		print("test")

func _ready():
	var test = Bar.new(self)
```

I would expect this code to run ok, but in fact I'm getting an error:
 _Parse Error: At '\_init()' call, argument 1. Assigned type (Foo) doesn't match the function argument's type (Bar)_ 

Similar code works ok with a regular method:

```
# works fine
class_name Foo

class Bar:
	func do_stuff(a:Foo):
		print("stuff done")

func _ready():
	var test = Bar.new()
	test.do_stuff(self)
```

**Comment by steveday4u** [comment]
looks like the same as this one #21996

**Comment by mineevgleb** [comment]
Seems to work fine in 3.1.1
