### ISSUE TITLE
Editing Spatial Transform matrix through inspector updates translation/rotation_degrees/scale, but not vice-versa

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#23941]
Not sure if this is reported already.

**Godot version:**

8ba0d51

**OS/device including version:**

Manjaro x86_64

**Issue description:**

![image](https://user-images.githubusercontent.com/43379543/48966378-ece79180-f002-11e8-83bb-c1246ae965d4.png)
Directly editing transform matrix (lower) affects the Vector3s above. Editing the Vector3s won't update transform matrix until the node is reselected.

**Comment by aaronfranke** [comment]
Duplicate of https://github.com/godotengine/godot/issues/10574
