### ISSUE TITLE
Deprecation warnings for classes

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#23946]
**Godot version: 3+**

It would be nice to have a deprecation warning system to show messages on the debug console when using a method planned for deprecation.

This will help engine's users and contributors alike.

Example:
Scene with a CollisionShape using PlaneShape can put: `PlaneShape will be deprecated in future versions`.
Script with InstancePlaceholder.replace_by_instance: `replace_by_instance will be deprecated in future versions, use create_instance instead.`

**Comment by eon-s** [comment]
@LikeLakers2 yes, but also for scene elements (Nodes and Resources).

**Comment by DualMatrix** [comment]
I'll look into expanding it to Scene elements as soon as #23023 is approved.

**Comment by neikeq** [comment]
We already have #4397 for deprecation of method, properties and signals. I would rename this issue or create a new one to request deprecation warnings for "scene elements".

Rather than "scene elements" it should be for Object derived classes (the editor could use this information to display warning for "scene elements" of those classes).

**Comment by eon-s** [comment]
Warnings like those that appears on missing shapes or materials would be too noisy IMO, on the debugger will be enough if the loaded scene includes some deprecated nodes/resources when running it.

In that case, just the deprecated node instances may be able to throw the warning on instancing.

**Comment by eon-s** [comment]
This never had much support, and related proposals and PRs also never got too far, I'll close this one and may open a proper proposal later when GDScript 2 matures a bit.
