### ISSUE TITLE
Compiling issue on Mac OS X (no matching function for call to 'localtime')

### ISSUE THREAD

**Issue by hugocm93** [godotengine/godot#2394]
Hello. I noticed a bug (sounds like a little bug) with the installation on mac. One module is not being compiled because a function from the time.h library is not being found. Maybe the installation script is not calling it right?

```
scons: Reading SConscript files ...
sh: i586-mingw32msvc-gcc: command not found
sh: x86_64-w64-mingw32-gcc: command not found
sh: i686-w64-mingw32-gcc: command not found
scons: done reading SConscript files.
scons: Building targets ...
g++ -o drivers/unix/os_unix.osx.tools.32.o -c -g3 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -arch i386 -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DAPPLE_STYLE_KEYS -DUNIX_ENABLED -DGLES2_ENABLED -DGLEW_ENABLED -DOSX_ENABLED -DMUSEPACK_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DTHEORA_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/osx -Itools/freetype -Itools/freetype/freetype/include -Idrivers/unix/vorbis drivers/unix/os_unix.cpp
drivers/unix/os_unix.cpp:229:2: error: no matching function for call to 'localtime'
        localtime(&tv_now.tv_usec);
        ^~~~~~~~~
/usr/include/time.h:112:12: note: candidate function not viable: no known conversion from '__darwin_suseconds_t *' (aka 'int *') to 'const time_t *' (aka 'const long *') for 1st
      argument
struct tm *localtime(const time_t *);
           ^
1 error generated.
scons: *** [drivers/unix/os_unix.osx.tools.32.o] Error 1
scons: building terminated because of errors.
```

**Comment by ArgosOz** [comment]
Every Godot user on Mac OS will taste this error, I believe :)

You can open os_unix.cpp and comment out the line containing: localtime(&tv_now.tv_usec) then try to compile it again.

The function needs to return milliseconds and as far as I can see, on Mac OS, gettimeofday function returns it already in tv_now.tv_usec variable as microseconds. 

I'm not sure but I believe localtime call is required for Unix not Mac OS.

**Comment by WatIsDeze** [comment]
@ArgosOz this worries me to a certain extend, because if OsX is giving this compile error, then somewhere in the Godot source code it is probably making use of this function. 

Hope that someone finds the energy to solve continues compile errors showing up on platforms other than Windows... :P

**Comment by StianTheDark** [comment]
The developers actually run Linux most of the time, so I can assure you that they focus as much on all the platforms.

**Comment by reduz** [comment]
I got a mac mini to test/fix this stuff, but didn't have time to set it up
yet, and also been working with cross compilers.. so I hope this will be
working again soon.

**Comment by WatIsDeze** [comment]
Changing line 229 to:
localtime((const long *)&tv_now.tv_usec);

Seems to solve it for me. This is a casting issue, and it is to take notice of the fact that Apple has a separate reference for their own time.h (ala not sys/time.h) documented here:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/time.3.html

Something seems off, either this is compiler related or some ifdef has been removed. It seems more likely to be the latter case.

**Comment by Clean3d** [comment]
I tried compiling several older commits, and it seems this problem appears in 6b25e83ba73ae3321aff00d7b3192d8cd80c410c, which is a bugfix for 6f9a084ac8a820450632f17384161c6a24da86d3.

Not sure I did this correctly, but hopefully this is helpful.

**Comment by WatIsDeze** [comment]
Clean3D, I'm not sure if that solves it? The procedure I described ala changing the lines allows it to compile. It has to cast, and it actually runs fine afterwards also, on OsX that is.

Not sure about the other platforms with that fix. I suppose it'll work just fine given the description of time_t from what I've read.

I'm afraid I do not have the time at this moment to work out the entire git commit procedure. But I'd like to mention @reduz that this could be the possible solution to the problem.

**Comment by Clean3d** [comment]
WatIsDeze: I don't think the bugfix commit I mentioned was aimed at the problem we're experiencing. I built Godot with your change on MacOS, Linux, and Win8/VS 2010 all successfully, though.

**Comment by WatIsDeze** [comment]
@reduz I hope you're reading is, sadly I don't have the time just yet to pull/push myself. However, my suggested solution as mentioned by @Clean3d seems to be plausible on all desktop platforms.

**Comment by ricpelo** [comment]
What about removing the localtime() call at all in OS X? According to @ArgosOz above:

> The function needs to return milliseconds and as far as I can see, on Mac OS, gettimeofday function returns it already in tv_now.tv_usec variable as microseconds.

> I'm not sure but I believe localtime call is required for Unix not Mac OS.

**Comment by vnen** [comment]
I get the same error when compiling with osxcross on Linux. I'm using the last commit (b0aa49a) which is the one that gives support for osxcross. I'm gonna test the solutions described here.

**Comment by vnen** [comment]
I made the change that @WatIsDeze suggested and it seems to work fine. Can't test on the Mac, but it doesn't give any trouble to Linux.

**Comment by d3v0x** [comment]
Works fine on OSX as well. There is a PR by @trond https://github.com/okamstudio/godot/pull/2361 but he maybe can split it into two separate PRs. The review of a single line should be easy.

**Comment by reduz** [comment]
will work on it tomorrow

**Comment by trond** [comment]
The signature of "localtime" (from http://linux.die.net/man/3/localtime) suggests that the input value is not modified for the caller, and the return value contains the result, so I'm not sure why it was put in there in the first place, unless it modifies some global state.

Sorry about my single PR containing several unrelated fixes, I'm new to this github/pull request stuff and didn't realize how it works :)

**Comment by akien-mga** [comment]
Has this been fixed in the end?

**Comment by vnen** [comment]
This is fixed. The problematic function calls were commented out in e3e93da6b94cdf14e9a6f466cf5f50a857166928 and fad1faddae96454bbe4abfef1bf394b3d2c9c057.
