### ISSUE TITLE
No way to get which is the current main screen from EditorPlugin

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23955]
Godot 3.1 alpha2

When a plugin is activated and needs to be visible only in one of the main screens, it has to get which main screen is currently active. However there is only the `main_screen_changed` signal to know that, and this obviously doesn't trigger when you activate a plugin. So when such a plugin is activated, you are forced to switch screens back and forth to make it work.

**Comment by pycbouh** [comment]
Closing in favor of this proposal: https://github.com/godotengine/godot-proposals/issues/2081
