### ISSUE TITLE
Bad gismos visibility in bright scenes.

### ISSUE THREAD

**Issue by valdemar-const** [godotengine/godot#23952]
**Issue description:**
Need blender 2.8 like overlays or unshaded materials for gizmos may be.
![gismo](https://user-images.githubusercontent.com/34628355/48974021-c1de5b80-f05d-11e8-9694-f98f21c8da86.png)

**Minimal reproduction project:**

any bright scene

**Comment by Zylann** [comment]
Similar to https://github.com/godotengine/godot/issues/16154

**Comment by valdemar-const** [comment]
@Zylann Sorry, I really couldn't find it.
