### ISSUE TITLE
Access to OpenType features

### ISSUE THREAD

**Issue by mm-2018** [godotengine/godot#23951]
Would Godot Game Engine be eventually able to access OpenType features? I've found fonts I may want to use for projects as part of the UI, but the alternate glyphs I want to use from them can only be accessed via HTML/CSS online or by deliberately modifying the font by swapping out glyphs using FontForge. The latter option would work, but it is especially inelegant and slow for certain Latin glyphs that are ambiguous or otherwise commonly used, and have many diacritics.

For instance, a font has a single storey "a" available, but can only be typically accessed via CSS. The letter already has numerous diacritics, and depending on the font family, has numerous styles and weights as well.

Are there plans to include this, or are there any workarounds?

**Comment by Calinou** [comment]
This was implemented in https://github.com/godotengine/godot/pull/41100, closing. Variable fonts and font ligatures are also supported in 4.0.
