### ISSUE TITLE
Camera2D.make_current() doesn't work

### ISSUE THREAD

**Issue by Essojadojef** [godotengine/godot#23966]
**Godot version:** 3.1

**OS/device including version:** Ubuntu 18.04

**Issue description:**
Trying to set a camera with Camera2D.make_current() outside of _ready() doesn't work.

**Steps to reproduce:**
Add a Camera2D to a 2D scene. Add a script that calls Camera2D.make_current() outside of _ready().
The game won't show the perspective of the new camera but will keep showing the default camera's or the viewport's one.

**Minimal reproduction project:** [camera2d_demo.zip](https://github.com/godotengine/godot/files/2613309/camera2d_demo.zip)
In the scene there is a sprite to the right of a camera and to the left of another one. Pressing space should switch the current camera and change the sprite's position on screen but nothing happens.

**Comment by BrodyEller** [comment]
Calling `update_scroll` inside `make_current` does fix the issue.  Will be submitting a PR soon.

**Comment by fry-** [comment]
Hello, I have the same issue. I'm on Lubuntu 18.04.

`Camera2D.make_current()` works like expected in Godot 3.1 alpha2, but not in alpha3 or alpha4.

Here is another minimal demo project (press *arrow down* for switching camera back and forth): 
[kinematic_collision_bug.zip](https://github.com/godotengine/godot/files/2719376/kinematic_collision_bug.zip)
