### ISSUE TITLE
`get_char_size()` is exposed only by `BitmapFont` but should be exposed by `Font`

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23967]
Godot 3.1 alpha2

If you want to get the size of a single character within a string, you have to use `get_char_size()` to handle kerning. This is a function available in `Font`, however it was exposed to the script API only for `BitmapFont`, while it should have been exposed from the base class. As a result, the call fails if you use a `DynamicFont`.

**Comment by giulianob** [comment]
Yes just ran into this as well while trying to implement some custom text rendering. Would really appreciate if someone who contributes could expose this function.
