### ISSUE TITLE
[Discussion] Tabs and Scene tabs

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#2396]
The purpose of this thread is to discuss the ideas and wishes around the Scene tabs of Godot editor. Multiple subjects have to be considered here and I ask every participant to quote precisely which one they relate (eg. S1 or G2).

Feel free to propose new entries for the following lists.

Considering tabs (in General) : 
- G1/ Close button : already PR-ed ( #2380 )
- G2/ Find a way to scroll horizontally over a big number of tabs
- G3/ Close tab with middle click : already PR-ed ( #2371 )

Considering scene tabs in the editor : 
- S1/ Left align the scene tabs instead of centering them.

**Comment by StraToN** [comment]
G2 : Here is the way Firefox deals with this
![firefox-tabs-scrolling](https://cloud.githubusercontent.com/assets/1289207/9506297/8aa93b34-4c47-11e5-8529-bf70ee2f5a8b.gif)

**Comment by StraToN** [comment]
S1 : 
Rotes Buch (aka solo on IRC) asked for left-alignment like this : 
![scene_tabs1](https://cloud.githubusercontent.com/assets/1289207/9506328/db1c4cf0-4c47-11e5-815f-b87af414e682.jpg)

Left-alignment is already possible for tabs. Scene tabs are setup to be Centered. Here is what left-align displays : 
![scene_tabs2](https://cloud.githubusercontent.com/assets/1289207/9506368/001957d2-4c48-11e5-95c8-c510a7b18fc5.png)

A left margin is wished by multiple users in order to align the scene tabs with 2D/3D main panel. However, in the case where there is no left panel in the editor, I think this margin should not be present. This would look like this : 
![scene_tabs3](https://cloud.githubusercontent.com/assets/1289207/9506437/67369a9c-4c48-11e5-8881-00bd77b86fe0.png)

**Comment by mamarilmanson** [comment]
@StraToN: G2/ Find a way to scroll horizontally over a big number of tabs: 

I suggest blender style... middle mouse button then drag to a direction... if that's possible...

**Comment by StraToN** [comment]
@mamarilmanson How does it work for users who don't have a middle mouse buttons such as macbook users using only touchpad ?

**Comment by mamarilmanson** [comment]
ALT+LMB? :)

**Comment by mamarilmanson** [comment]
Blender also does this... MMB emulation...

**Comment by StraToN** [comment]
@mamarilmanson Oh, right, I forgot. Fine then. I like the idea a lot. I already worked on middle mouse button management for tabs, for closing a tab quickier. Dragging should be possible but I need to verify if moving tabs out of their positions is possible or not

**Comment by WatIsDeze** [comment]
I'd suggest implementing both, the arrows and the middle mouse button method. Some mice actually still lack this(surprisingly, but some people just do not have one, and I do not see a settings menu where one can change this button....).

**Comment by StraToN** [comment]
Actually, there is currently no way to change key shortcuts for Godot Editor. AFAIK, they are hard-coded in the source code (which we all agree to say it is ugly), but this is an enhancement that will be needed in short to mid-term.

**Comment by WatIsDeze** [comment]
Yeah, but these arrows won't do any harm, at least if it isn't too much work to implement obviously. Because the goal after all is to allow for multiple methods to get to Rome.

I'd say that loading the key shortcuts from some configuration file is already a start. Most of us could edit it by hand, no need to instantly add an editor for that on top. Possibly some food for thought.

**Comment by StraToN** [comment]
@WatIsDeze True. This is a different topic from this one here. The need will grow, and then a new topic will rise, no doubt about that.

Considering G2/ Find a way to scroll horizontally over a big number of tabs: 
I think the easiest way consists in adding the two left and right nav buttons. The middle click drag should be added later. Remember : these additions will be available for users in GDScript. We do not want an exhaustive list of functionalities, and existing ones have to be enabled or disabled on demand. That is the case for the Close Button, for example.

**Comment by DriNeo** [comment]
The middle mouse button is already used for navigation into the viewport editor. And I like how it is. 
Unintentional clicks or scrolling, because too much functions are connected to the mouse, are so annoying...

**Comment by mamarilmanson** [comment]
^ same as blender…

**Comment by hetdegon** [comment]
I vote for closing tabs with a mid-button click, it'd be really convenient, specially since there are no right-click context menus.

**Comment by StraToN** [comment]
Closing tabs with mid-button click is already developed (#2371), you can try it already, but I have no idea if it will be accepted.

**Comment by reduz** [comment]
I think all this was implemented, so it's time to close this issue! horray!

**Comment by StraToN** [comment]
Yay ! Great job @reduz 😁
