### ISSUE TITLE
How to get mousemotion in visual script

### ISSUE THREAD

**Issue by haizhou37** [godotengine/godot#23975]
**Godot version:**
the latest version of godot master（22:00, 22/11/2018）

**OS/device including version:**
manjaro gnome x64
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile
intel hd 3000

**Issue description:**
In godot, only the action node that detects keystroke events is found in Available Nodes, but the node that can get mouse movement information is not found.
This makes it impossible to use the mouse to control the rotation of the game view in a visual script

**Comment by Naryosha** [comment]
Mouse motions are passed as an argument of `_input`.
![image](https://user-images.githubusercontent.com/43379543/49128638-dbea9900-f2fe-11e8-8a0f-07e8edc8ca4b.png)
