### ISSUE TITLE
LineEdit placeholder text property doesn't properly take locale into account

### ISSUE THREAD

**Issue by creeperdeking** [godotengine/godot#23984]
**Godot version:**
commit : 11d77386221a4d911edee4fdbba5d3b9109a1c6b

**OS/device including version:**
Kubuntu 18
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
Nvidia drivers

**Issue description:**
When setting a locale with TranslationServer.set_locale("fr"), the text field of the placeholder of LineEdits is still translated in "en" language only.

**Steps to reproduce:**
1. make a lineedit with something in the text property of the placeholder
2. fill the translation of this text.
3. TranslationServer.set_locale(your_locale)
4. Enjoy

**Minimal reproduction project:**
[demo_translation_problem.zip](https://github.com/godotengine/godot/files/2615119/demo_translation_problem.zip)

you can also see this isue inside the godot editor:
![image](https://user-images.githubusercontent.com/7153077/49009577-3524c200-f171-11e8-9aa3-1c3742ab58e3.png)
--> look at "Filter properties", should be translated in french

Thank you!

**Comment by volzhs** [comment]
it can be translated.
https://github.com/godotengine/godot/blob/942855a9ee376ce6ee30a25674856ba64316b548/editor/inspector_dock.cpp#L561-L566

https://github.com/godotengine/godot/blob/942855a9ee376ce6ee30a25674856ba64316b548/editor/translations/fr.po#L3429-L3432

is it caused by `fuzzy` marked?

**Comment by akien-mga** [comment]
Indeed, the "issue" with "Filter properties" is simply that it's not translated yet for the French locale. Translating it locally makes it work just fine:
![screenshot_20181126_123320](https://user-images.githubusercontent.com/4701338/49011741-89cb3b80-f177-11e8-9129-240a2c5815d6.png)

I can however reproduce the issue with the placeholder text on the provided project. For me it's always in French on the LineEdit, regardless of the locale set with `set_locale`.
