### ISSUE TITLE
BBcode doesn't work well if the markers are closed in reverse order

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23983]
**Godot version:**
3.1 9e62826

**OS/device including version:**
Windows 10

**Issue description:**
When my BBcode in RichTextLabel is like below, everything works as I expect:
![asfasasfasf](https://user-images.githubusercontent.com/41945903/49003894-41a21e00-f163-11e8-93ec-47d7bc4d7f55.png)

```
[center][color=green]Ziemniakq[/color][/center]
```

but when I change text to this, then strange text after my text appear

![aaaaaaaa](https://user-images.githubusercontent.com/41945903/49003896-42d34b00-f163-11e8-9d33-8b9171bc9357.png)
```
[center][color=green]Ziemniakq[/center][/color]
```

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2614732/Test.zip)

**Comment by slapin** [comment]
But why do you close tags out of order?

**Comment by Zireael07** [comment]
BBcode on forums doesn't care about order, and it's an easy enough mistake to make.

**Comment by tom-jk** [comment]
State of this issue: since 3.2, the MRP with reversed close tags produces "Ziemnikq[/center]", which is a fair improvement on 3.1.

**Comment by akien-mga** [comment]
Yes that seems correct to me, unless we aim to explicitly support closing tags in random order, but I don't think it's necessary.
