### ISSUE TITLE
Weird InputEventScreenTouch Ids

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#23985]
**Godot version:**
3.0.6 stable

**OS/device including version:**
Surface Book 2
Windows 10 Professional
16 GB RAM
Intel I7 8650U
NVidia GTX 1050

**Issue description:**
The gui_input callback function on control-nodes is giving me weird touch indexes. While on android the first finger has always the id 0, on my windows 10 touchscreen device my first finger has a random touch id, which changes each time a touch event is triggered.

Here is the output of the minimal reproduction project when touching multiple times (it prints the touch ids):

> 203
> 204
> 205
> 206
> 207
> 208
> 209
> 210
> 211
> 212
> 213
> 214
> 215
> 216
> 217
> 218
> 219
> 220
> 221
> 222
> 223
> 224
> 225
> 226
> 227
> 228
> 229
> 230
> 231
> 232
> 233
> 234

 

**Steps to reproduce:**
- Create an control object and set the gui_input(ev) callback
- touch the screen and check the touch indexes of InputEventScreenTouchEvents

**Minimal reproduction project:**
[TouchIndexBug.zip](https://github.com/godotengine/godot/files/2615320/TouchIndexBug.zip)

**Comment by th1z** [comment]
The Problem still exist in the 3.1 stable version of Godot.
My device is a surface pro 6

The first touch event only registers only as a "touch down". "Touch up" is omitted.
Additional touch indices are enumerated.

**Comment by RandomShaper** [comment]
I think we have two separate things here:

@Tobi-La, Godot is not expected to give "beautiful" touch indices. It passes to the game whatever index is reported by the platform. Android gives zero-based indices; Windows doesn't.

@th1z, I think your issue is different. Could you open a separate bug report with further details on how to reproduce it, etc.?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc2](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-2) or any later release?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue, and make sure that there is an up-to-date reproduction project.
