### ISSUE TITLE
While saving, remove the extension if custom extension is not allowed.

### ISSUE THREAD

**Issue by jcs090218** [godotengine/godot#23988]
**Godot version:**
v3.0.6 stable.

**OS/device including version:**
Windows 10

**Information:**
Just suggesting that while you trying to save the scene, instead of highlighting the scene name just completely ignore/remove the extension if entering custom extension is not allowed? I think this will help the developers on UX wise and having the standard extension is prominent to a mature game engine.

**Comment by Calinou** [comment]
This is the behavior when pressing <kbd>Ctrl + Shift + S</kbd> as of Godot 3.3.3:

![image](https://user-images.githubusercontent.com/180032/132062556-38bf5d77-8d53-4227-b4be-f3b930f39a40.png)

If you replace the whole field to save a scene without a file extension, `.tscn` will be automatically appended at the end. Therefore, this seems to be implemented now :slightly_smiling_face:
