### ISSUE TITLE
Godot is being hindered on Windows by up to 500ms

### ISSUE THREAD

**Issue by Aaron-Fleisher** [godotengine/godot#23986]
There is currently a shader disk cache lock bug that affects NVIDIA drivers on Windows 7 and 10. This creates a delay of  around 200-500ms (sometimes more), when pressing F5/scene previewing.

A solution to this is modifying
https://github.com/godotengine/godot/blob/942855a9ee376ce6ee30a25674856ba64316b548/editor/editor_run.cpp#L178

and using a custom hard coded path that runs another executable. This removes the  delay and the game developer experiences instant scene previews like Linux users.

I feel like this has been normalized and people have forgot about it or just got "so used to it" it's a non-issue. But IMO, this really undermines the engine. And there are still a lot game developers that use Windows

A temporary solution is to change the `exec` path to a separate executable. A better solution would be to add a option so users can set their own custom executable path. This way,  no compilation is needed.

**Comment by Calinou** [comment]
> A better solution would be to add a option so users can set their own custom executable path.

Ideally, this should work without requiring any configuration from the user.

Would copying the executable to a temporary location before running the project work? To make this more efficient, the executable would only be copied if there is no executable in the temporary location, or if the executable already present has a different MD5 hash.

**Comment by Aaron-Fleisher** [comment]
> > A better solution would be to add a option so users can set their own custom executable path.
> 
> Ideally, this should work without requiring any configuration from the user.
> 
> Would it work if the executable is copied to a temporary location before running the project? To make this more efficient, the executable would only be copied if there is not one already present in the temporary location, or if the current executable has a different MD5 hash.

Yeah it should!    What I do after compiling is I duplicate the executable and name it godot2.exe, and use that path for `exec`.  I just figured an option in the editor  would be less intrusive cause this is only specific to Windows 7, 10 and users who have NVIDIA cards.  I've tried it on AMD cards, and Linux, it's instant

**Comment by girng** [comment]
can't reproduce the latest NVIDIA driver update **419.17**. i'm on Windows 10, GTX 950. also related #11939
they finally fixed it! wow, the previews are instant now. feelsgoodman.

**Comment by akien-mga** [comment]
@Aaron-Fleisher Can you confirm if it's fixed for you too with latest Nvidia drivers?

**Comment by Aaron-Fleisher** [comment]
@akien-mga Seems like it, the delay is gone.

**Comment by akien-mga** [comment]
Awesome, thanks!
