### ISSUE TITLE
Godot doesn't fit container to screen until I change size of window

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23995]
**Godot version:**
3.1 942855a

**OS/device including version:**
Ubuntu 18.04 and Windows 10

**Issue description:**
When I add MarginContainer to GridContainer then some nodes change self size, when I set size window manualy, then height of this containers back to normal

**Steps to reproduce:**
![jfile](https://user-images.githubusercontent.com/41945903/70705472-69174a80-1cd4-11ea-9e8d-90fa07944606.gif)

**Minimal reproduction project:**
[AA.zip](https://github.com/godotengine/godot/files/2616600/AA.zip)

**Comment by qarmin** [comment]
I created a lot of smaller minimal project.
[AA.zip](https://github.com/godotengine/godot/files/2954063/AA.zip)

The problem occurs with ```queue_free``` but not with ```call_deferred("free")``` which is strange to me, because I think that they do exactly same thing.

**Comment by qarmin** [comment]
Still happens with 4.0 5bf7c769f  - [AA.zip](https://github.com/godotengine/godot/files/4846898/AA.zip)

**Comment by KoBeWi** [comment]
Can't reproduce in 4.0 alpha7
@qarmin Can you confirm?

**Comment by qarmin** [comment]
Yes, it is fixed both in 3.x and 4.0 branch
