### ISSUE TITLE
Mono Glue generation Fails

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#24006]
**Godot version:**
c23710a

**OS/device including version:**
Windows10 / Mono 5.12

**Issue description:**
![image](https://user-images.githubusercontent.com/3036176/49061545-0155a500-f222-11e8-8abc-dbe5423a4d38.png)

**Steps to reproduce:**
`scons p=windows tools=yes module_mono_enabled=yes mono_glue=no`

**Comment by piratesephiroth** [comment]
was it some problem with this specific commit? because I built it fine hours ago (c23710a)

**Comment by neikeq** [comment]
When was the last time that `mono_glue.gen.cpp` file was created?

**Comment by Chaosus** [comment]
Damn, I've forgot that auto generated file should be deleted and recreated every time big changes is coming.. Sorry guys, false alarm

**Comment by neikeq** [comment]
No, this file doesn't need to be delete if you pass `mono_glue=no`. This flag tells scons to not compile this file, so there won't be any errors and you can re-generate it then. When was the last time you generated this file?

**Comment by Chaosus** [comment]
^^ Several months ago.. Today, after deletion its compiling perfectly

**Comment by neikeq** [comment]
That explains it then. Not too long ago I made a breaking change that intently required any old generated `mono_glue.gen.cpp` to be removed.
