### ISSUE TITLE
Visual artifacts in branching shader

### ISSUE THREAD

**Issue by devvoid** [godotengine/godot#24005]
**Godot version:**
Godot 3.1 alpha 2

**OS/device including version:**

Windows 10 Pro, 64 bit, version 1803.
NVIDIA GeForce 660 TI, driver version 417.01

The same issue also happens on Ubuntu 18.04 LTS.

**Issue description:**
When using a branching shader, severe visual artifacts result on my system.

![issue](https://user-images.githubusercontent.com/33298798/49060288-8dd87700-f1d2-11e8-8c38-653c4931e38e.png)

Shader code is as follows:

```
shader_type spatial;
render_mode unshaded;

void fragment()
{
	if (COLOR == vec4(1.0, 0.0, 0.0, 1.0))
	{
		ALBEDO = vec3(0.0, 1.0, 0.0);
	}
}
```

**Steps to reproduce:**
Create a shader using an if-else statement, and run the project.

**Minimal reproduction project:**
https://github.com/devvoid/Godot-Shader-Issue

**Comment by CptPotato** [comment]
It's generally a good idea to use a small bias when comparing float values like:
if(dot(vecB - vecA, vecB - vecA) < 0.001)

Also accessing COLOR is invalid to my knowledge.

**Comment by clayjohn** [comment]
I tested this out on Ubuntu 16.04 and had no problems. However I can confirm the bug on Windows 10 with an Nvidia 1050. 

Some notes on it:
`if( all(lessThanEqual(COLOR, vec4(1.0, 0.0, 0.0, 1.0))))`: works
However, 
`if( all(equal(COLOR, vec4(1.0, 0.0, 0.0, 1.0))))`: breaks the same way

@CptPotato COLOR is the vertex color passed from the vertex shader. I can be both read and written to in the fragment shader.

**Comment by CptPotato** [comment]
@clayjohn Thanks for the clarification. I still had the comments of #23678 on my mind but I guess it's not true.

**Comment by clayjohn** [comment]
@CptPotato The first comment in that issue is also incorrect. See my comment at the end of that thread. The issue in that case was that the user expected `COLOR` to perform an automatic texture lookup, when it fact it just represents vertex color.

**Comment by devvoid** [comment]
@clayjohn Yes, I have both on the same machine, albeit with different driver versions (have never been able to update drivers on Ubuntu without breaking my installation).

I forgot to mention in the original post. but the glitch is slightly different between Windows and Ubuntu. On Windows, the result is green with white artifacts, but on Ubuntu, the result is green with red artifacts. I'm not terribly sure why, but I thought it would be worth mentioning.

**Comment by DavidSichma** [comment]
I'm sure it's how varyings like COLOR are interpolated.
At least on some drivers smoothly interpolating between 1.0 and 1.0 will not always yield 1.0 but 0.999...

Your best bet is using a bias.

**Comment by clayjohn** [comment]
This is indeed an issue of comparing floats using ==. Accordingly, it is not something that can be fixed.
