### ISSUE TITLE
AnimationPlayer's 'capture' update mode is acting similarly to discrete mode

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#24015]
**Godot version:**
173b342ca738916cf113554291bb11f7cce71043

**OS/device including version:**
Ubuntu 18.04, 64bit

**Issue description:**
Capture update mode is a new feature of AnimationPlayer. As far as I understand the way how it should work, when playing an animation that's using this mode, the property should be fluently interpolated to match the first keyframe value of the track and then the rest of the animation should be played in the same way how continuous update mode is acting. 
Instead, it's interpolating to the first keyframe, but later it's acting just like discrete update mode:
![capture_track](https://user-images.githubusercontent.com/6129594/49096825-ae084480-f26b-11e8-9e31-c7ce885dc6f9.gif)

**Steps to reproduce:**
1. Create new scene with Sprite and AnimationPlayer children
2. Animate Sprite positions, with couple keyframes. 
3. Ensure the first keyframe of the animation is at 0.5s 
4. Modify update mode of the track to 'capture'

**Minimal reproduction project:**
[CaptureTrack.zip](https://github.com/godotengine/godot/files/2620887/CaptureTrack.zip)

**Comment by avencherus** [comment]
I do recall having some issues with it when I tried it out.  Wasn't sure if I was misusing it though, since not much information exists about it.  I also find it kind of odd that the capture mode option was stuffed there, since you then lose the other options for handling the remaining keyframes.
