### ISSUE TITLE
Can't export debug and release builds at the same time

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#24028]
**Godot version:**
3.1 b243c26

**OS/device including version:**
Windows 10

**Issue description:**
I can't export at the same time, release and debug build. I'm must choose only one. I think that better option will ability to choose which type of build we want to have in presets. 

![fafafafafafafafaf](https://user-images.githubusercontent.com/41945903/49136067-d4b89080-f2e8-11e8-9c66-ed1daed3dccd.png)

**Comment by fire** [comment]
We should be able to export multiple platforms at the same time. Not just release and debug.

**Comment by Calinou** [comment]
@fire There's an **Export All** button now, which becomes usable when all presets have a defined export path. However, it's not currently possible to select multiple presets and export them though.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1071, as feature proposals are now tracked on the Godot proposals repository.
