### ISSUE TITLE
GIProbe does not work on GLES2

### ISSUE THREAD

**Issue by lobinuxsoft** [godotengine/godot#24023]
Godot version: latest from git (3.1)

Video Sample : https://www.youtube.com/watch?v=tyiZ3LrlpEE

Hello people, I did a little test compiling godot in the latest version and GIProbe does not work correctly in GLES2, in GLES3 it works correctly but in GLES2 it looks all very bad, any solution?

**Comment by BastiaanOlij** [comment]
GIProbe requires OpenGL 3 features so I would be very surprised if support for it will be added to the GLES2 driver.

**Comment by lobinuxsoft** [comment]
It is possible that I was wrong, beyond the problem with GIProbe and had problems of other types of problems when compiling the engine in windows and trying to export to the Android platform, and I followed the documentation step by step ... but it sure is for another issue.

**Comment by akien-mga** [comment]
GLES2 and GLES3 have different feature sets, and projects need to be made for one or the other, at least in 3D. You can't take a full blown GLES3 project using all high end features and switch it to GLES2, many things won't work as seen in your video. GLES2 is not just a "low end"/"faster" fallback, it's a different backend.
