### ISSUE TITLE
Polygon Tool's icon highlights are hard to notice.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#24020]
c23710a

Just an enhancement request.

For the Polygon2D canvas toolbar, it can be a bit difficult to tell when Edit mode is selected, since the highlighted version and non-highlighted version are both blue.  The add is also a bit faint in comparison as well.

![godot_master_2018-11-28_00-09-54](https://user-images.githubusercontent.com/13004169/49115024-4faa8880-f2a2-11e8-8db5-d0ff39fb06b4.png)
![godot_master_2018-11-28_00-10-03](https://user-images.githubusercontent.com/13004169/49115035-533e0f80-f2a2-11e8-83df-85571534a59e.png)

**Comment by eon-s** [comment]
Duplicate of #18188
