### ISSUE TITLE
batch creating collision objects unnecessarily slow

### ISSUE THREAD

**Issue by pgruenbacher** [godotengine/godot#24026]
I posted to bullet as well. I think bullet3 just needs a batch create method...
https://github.com/bulletphysics/bullet3/issues/2009 

Godot 3.0.2

Ubuntu 16

Create 3,000 collision objects at once leads to > 5 seconds of delay. What bothers me is that the initial added objects take < 20-40 microsecs to create. However that addition time increases linearly to around 700 microsecs to create. I'm able to confirm by commenting the
btCollisionWorld::addCollisionObject() that the processing time is increasing within bullet itself. I couldn't find anywhere in the godot code that indicates it's querying the state between time I create a new object... I cannot find anywhere in docs about batch creating collision objects (of same filter, group, aabb collision shape).

I was able to improve performance drastically too though by moving the set_space *after* the other object set methods like set collision layer and set shape.

The below snippet is called 3000 times to allocate the physics objects.
```
void MultiPhysicsBody::add_physics_body() {
  // print_line("ADD PHYSICS BODY " + itos(body_rids.size()));
  // if (shape.is_null()) return;
  auto time = OS::get_singleton()->get_ticks_usec();
  ERR_FAIL_COND(!shape.is_valid());

  MultiPhysicsObject* obj = memnew(MultiPhysicsObject);
  obj->set_parent(this);
  obj->set_index(body_rids.size()); // not the biggest fan of this, would prefer more deliberate indexing...

  PhysicsServer::BodyMode p_mode = PhysicsServer::BODY_MODE_STATIC;
  // just a static collision, we don't use it for anything besides testing raycasts.
  PhysicsServer* ps = PhysicsServer::get_singleton();
  RID rid = ps->body_create(p_mode);
  ps->body_attach_object_instance_id(rid, obj->get_instance_id());
  // int collision_mask = _collision_mask;
  // int collision_layer = _collision_layer;
  ps->body_set_collision_mask(rid, collision_mask);
  ps->body_set_collision_layer(rid, collision_layer);
  ps->body_set_ray_pickable(rid, true);
  // ps->body_set_shape(rid, )
  // the shape will be centered on collision body.
  ps->body_add_shape(rid, shape->get_rid(), Transform());
  ps->body_set_shape_disabled(rid, 0, false);
  // make sure to set space after we set everythign else!
  // massive performance degradation if we make all these changes while arleady set in space.
  ps->body_set_space(rid, get_world()->get_space());
  body_rids.push_back(rid);
  body_objects.push_back(obj);
  print_line("ADDED " + itos(body_rids.size()) + " " +  itos(OS::get_singleton()->get_ticks_usec() - time));
  // CollisionObject(, false);
}
```

**Comment by aaronfranke** [comment]
I've noticed this with my project. I have code both for mesh colliders on my chunks and box colliders for my voxels. The mesh collider code works very quickly, while the box collider code freezes my project for several seconds while it generates.

Also, with the mesh collider approach, my project gets about 700 FPS once it's generated. With the box collider approach, my project gets about 450 FPS once generated.

**Comment by pgruenbacher** [comment]
Mind sharing snippet of your physics server api call? So I can trace the
two different ways your doing it.

**Comment by aaronfranke** [comment]
(I'm using C#) For adding the box colliders, I'm using `AddChild(c);` where `c` is a `CollisionShape` with a `BoxShape` assigned. This is called thousands of times.

For adding mesh colliders, I'm using `AddChild(c);` where `c` is a `CollisionShape` with a `ConcavePolygonShape` assigned. This is called once per chunk.

**Comment by pgruenbacher** [comment]
@aaronfranke thousands of child nodes? you're performance is fine between the chunk loading? 
anyways I'm unable to replicate in the bullet3 app browser, but I've measured the time and the delay is happening in bullet3's addCollisionObject function, so this is outside of godot.

**Comment by AndreaCatania** [comment]
Godot doesn't use Bullet3 but Bullet2. Bullet 3 is not yet complete

**Comment by pgruenbacher** [comment]
mispoke. bullet2. I was testing the addCollisionObject under thirdparty/bullet.

**Comment by pgruenbacher** [comment]
though i see b3ConvexHullContact and `You can download the Bullet Physics Library from the github repository: https://github.com/bulletphysics/bullet3/releases` under btCollisionWorld.h so I just assumed bullet3?

**Comment by pgruenbacher** [comment]
ok well temp easy fix is to do the set_space as the last operation on the body.
2nd fix to speed up is to make sure there is a TRANSFORM state set on the body before set space on it, this will halpe the broadphase addCollisionObject perform faster. 

so instead of this 
```
  PhysicsServer::BodyMode p_mode = PhysicsServer::BODY_MODE_STATIC;
  // just a static collision, we don't use it for anything besides testing raycasts.
  PhysicsServer* ps = PhysicsServer::get_singleton();
  RID rid = ps->body_create(p_mode);
  ps->body_set_space(rid, get_world()->get_space());
  ps->body_attach_object_instance_id(rid, obj->get_instance_id());
  // int collision_mask = _collision_mask;
  // int collision_layer = _collision_layer;
  ps->body_set_collision_mask(rid, collision_mask);
  ps->body_set_collision_layer(rid, collision_layer);
  ps->body_set_ray_pickable(rid, true);
  // ps->body_set_shape(rid, )
  // the shape will be centered on collision body.
  ps->body_add_shape(rid, shape->get_rid(), Transform());
  ps->body_set_shape_disabled(rid, 0, false);```

do this 
```
  PhysicsServer::BodyMode p_mode = PhysicsServer::BODY_MODE_STATIC;
  // just a static collision, we don't use it for anything besides testing raycasts.
  PhysicsServer* ps = PhysicsServer::get_singleton();
  RID rid = ps->body_create(p_mode);
  ps->body_attach_object_instance_id(rid, obj->get_instance_id());
  // int collision_mask = _collision_mask;
  // int collision_layer = _collision_layer;
  ps->body_set_collision_mask(rid, collision_mask);
  ps->body_set_collision_layer(rid, collision_layer);
  ps->body_set_ray_pickable(rid, true);
  // ps->body_set_shape(rid, )
  // the shape will be centered on collision body.
  ps->body_add_shape(rid, shape->get_rid(), Transform());
  ps->body_set_shape_disabled(rid, 0, false);
  ps->body_set_state(PhysicsServer::STATE_TRANSFORM, transform)
  ps->body_set_space(rid, get_world()->get_space());
```

**Comment by akien-mga** [comment]
Did you mean to close the issue?

**Comment by pgruenbacher** [comment]
yea my fixes are tolerably faster. I'll make separate PR or issue if I find actual issue or major boost.
