### ISSUE TITLE
Godot 3.1 Alpha 2 GLES2 crash on Nokia 7 Plus, Android 9

### ISSUE THREAD

**Issue by AlexRixhardson** [godotengine/godot#24043]
**Development Environment:**
Godot version: 3.1 Alpha 2
OS: Windows 10 64-bit

**Device where crash happens:**
OS: Android 9 (October 1, 2018 security patch)
Device: Nokia 7 plus
GPU: Adreno 512

**Issue description:**
Splash screen is displayed for a second, then the game crashes. Expected result: main scene should load instead. Problem is only reproducible if GLES2 is used. It works normally on GLES3.

**Steps to reproduce:**
Run the attached minimal reproduction project on the Nokia 7 plus phone.

**Minimal reproduction project:**
[test2.zip](https://github.com/godotengine/godot/files/2626350/test2.zip)

**ADB LOGCAT output:**
Here is the logcat output. Android app's ID is com.test.two. App was launched at 20:44:30 and crashed at ca. 20:44:34.
[logcat.txt](https://github.com/godotengine/godot/files/2626360/logcat.txt)

**Comment by lobinuxsoft** [comment]
I have a similar problem but in Android, in GLES2 the splash screen blinks and breaks, and in GLES3 only the skybox is visible.

**Comment by AlexRixhardson** [comment]
> I have a similar problem, in GLES2 the splash screen blinks and breaks, and in GLES3 only the skybox is visible.
I am experiencing the blinking splash screen symptom when running Godot's "Navmesh Demo" on Nokia 7 Plus, Android 9, GLES2.

With the minimal reproduction project that I attached, however, it just crashes. Since the minimal reproduction project is really minimal (one camera, one static body with collision shape and mesh, no scripts), I thought I'd post this bug first, because I assumed it would be easier to fix, but could also be related to the blinking splash screen symptom which requires more complex projects to reproduce.

**Comment by eon-s** [comment]
Try removing the default environment or at least the procedural sky, it seems to be causing problems on some GPU (including desktop ones).

**Comment by AlexRixhardson** [comment]
> Try removing the default environment or at least the procedural sky, it seems to be causing problems on some GPU (including desktop ones).

You are correct. Game does not crash if I remove the default environment. Removing procedural sky alone does not help.

**Comment by eon-s** [comment]
Then this may be a duplicate of #21551

**Comment by AlexRixhardson** [comment]
> Then this may be a duplicate of #21551

It probably is.

Even though removing sky from the default environment doesn't help in my case, I found out that if I delete the default environment, and then create a new environment, everything still works. Adding sky to the brand new environment causes the game to start crashing again.

So I guess removing sky from the default environment that is automatically added to the project still keeps something behind, and that causes the game to crash. Creating brand new environment without the sky however works.

**Comment by akien-mga** [comment]
Thanks, closing as duplicate of #21551 then, but I'll quote these findings there.
