### ISSUE TITLE
Can't push the "next tab" button when three tabs are in the same dock

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2404]
3 tabs in one layout spot, can't push the red marked button.

![bug](https://cloud.githubusercontent.com/assets/4741886/9564569/e92243f2-4eab-11e5-8041-d71cbbe5e5a7.PNG)

**Comment by akien-mga** [comment]
What is this red marked button? I don't see it in the editor here.

**Comment by AlexHolly** [comment]
I had this issue on Windows 7 64-bit right now I'm on Ubuntu and can't reproduce it.
I will try to check on Windows the next days.

I think the godot window was not in full screen mode and then they appeared.

**Comment by AlexHolly** [comment]
Ok I checked on Windows and I'm able to reproduce it.

![bug](https://cloud.githubusercontent.com/assets/4741886/11165673/10dcadaa-8b16-11e5-8ab7-e104229474d7.gif)

**Comment by akien-mga** [comment]
Thanks. It looks indeed like the UI scaling does not work on X11, so the issue is only reproducible on Windows (maybe Mac too).

**Comment by reduz** [comment]
I can't reproduce this, maybe it is fixed?

**Comment by vnen** [comment]
@reduz you have to check on Windows as it didn't happen on Linux.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by vnen** [comment]
I can't reproduce because I get this:

![godot windows opt tools 64_2016-07-21_10-00-53](https://cloud.githubusercontent.com/assets/5599796/17023521/178bbd98-4f2a-11e6-886e-e9d66a0989ac.png)

**Comment by RayKoopa** [comment]
This was fixed with https://github.com/godotengine/godot/pull/7600. The old logic had several issues which I rewrote. I just re-tested it, and can't reproduce it anymore.

**Comment by AlexHolly** [comment]
@RayKoopa Any update on this one?

**Comment by KoBeWi** [comment]
Seems like in 3.1 it always works. Unless there are some steps I'm missing.
