### ISSUE TITLE
Issue with detecting clicks on a plane-shaped Area

### ISSUE THREAD

**Issue by dbenoy** [godotengine/godot#24045]
**Godot version:** 3.0.6

**OS/device including version:** Ubuntu 18.04

**Issue description:**

_input_event() on an Area doesn't work as expected if it has a 'plane' shaped CollisionShape
I believe for the purposes of handling the click, it may be acting as though the plane is positioned right on top of the camera.

**Steps to reproduce:**
[godot-areaclicktest-bad.zip](https://github.com/godotengine/godot/files/2627066/godot-areaclicktest-bad.zip)

Run this project and try to click the Area, and watch the console for feedback. I've put a MeshInstance cube there to give a visual indication of where the Area is _supposed_ to be.

It seems that if you click on the left 20% of the window it will not trigger, but if you click on the right 80% it will.

You can rotate the area around and get different results, and if you go into the CollisionShape and change it to a cube (to match the MeshInstance) then it starts acting as expected, only triggering if you click the cube.

**Comment by beetbeet** [comment]
i have a BoxShape as CollisionShape and that code:

```
   func _input_event(camera, event, pos, normal, shape):
        if event is InputEventMouseButton \
        and event.button_index == BUTTON_LEFT \
        and event.is_pressed():
            self.on_click()

    func on_click():
        tileNode.click()
```

dont works in godot 3.1 but works in 3.0, any ideas why?

**Comment by pouleyKetchoupp** [comment]
Closing as plane shape is marked as obsolete and there's an easy workaround using a box shape, concave shape or convex shape.
