### ISSUE TITLE
Godot Game Doesn't Quit on Android

### ISSUE THREAD

**Issue by ZodmanPerth** [godotengine/godot#24049]
**Godot version:**
Godot 3.0.2.stable.official
Godot 3.0.6.stable.official.8314054
Godot 3.1 Alpha2

**OS/device including version**
OS: Android 8.0
Device: Huawei Mate 10 Lite (Model RNE-L21)

**Issue description:**
A call to `get_tree().quit()` on Android closes the game screen, however the game is still listed in the list of running apps, and selecting it there restarts the game from scratch.  I expected the game process to be completely terminated and no longer available on the list of running apps.

**NOTE:** This is a deliberate resurrection of a [closed issue with the same name](https://github.com/godotengine/godot/issues/7707), however more information has come to light (see below) and I feel the issue is worth revisiting.  See also the discussion that led to the resurrection of this issue [on the developer forum](https://godotdevelopers.org/forum/discussion/20259/get-tree-quit-not-closing-the-app-when-running-on-android).

I expected a call to `get_tree().quit()` to terminate the process containing the Godot game on Android. According to [this StackOverflow answer](https://stackoverflow.com/questions/3279578/close-android-application/15652384#15652384) such a termination is possible by calling `System.exit(0);`.  Discussion on the [closed Godot issue with the same name](https://github.com/godotengine/godot/issues/7707) implied that keeping apps alive is a design philosophy of Android but did not cite evidence.

I've been looking for something from Google saying "you must not kill the application on Android".  I've only found [design guidance](https://developer.android.com/training/implementing-navigation/temporal) that implies every app on Android is considered to be a service that could be called on at any time. Under such a "service" type model it makes sense for apps to not be closed, however I don't believe games fit that model.

Given no definitive evidence can be found to direct that the application must not be killed, and it's a possibility, I want to revisit the decision to completely close the app using `get_tree().quit()`.

I've looked at how a few other games on Android deal with quitting the app.  All the games I looked at provide a quit button or an "are you sure you want to quit" yes/no dialog when navigating back from their home screen. All of these apps currently have the behaviour I'm seeing; they don't actually close and restart when selected again. If the [StackOverflow answer](https://stackoverflow.com/questions/3279578/close-android-application/15652384#15652384) is correct, I find it interesting that those games don't implement quit properly.

Do we have any contacts such as a representative (or body) from the Google store who can be asked for definitive developer guidance?  Personally I would like to see Godot support the ability to actually quit the app when directed by `get_tree().quit()`, however I wouldn't want to jeopardise Godot's reputation with Google (especially in light of recent events that banned Godot apps from the store).

**Steps to reproduce:**
Call `get_tree().quit()` on Android

**Comment by akien-mga** [comment]
> Discussion on the closed Godot issue with the same name implied that keeping apps alive is a design philosophy of Android but did not cite evidence.

The StackOverflow answer you linked to does provide some evidence of it being a design decision from the Android team. The fact that virtually no app on Android *does* quit fully when you press the Back button on the home screen, or the Quit button if they have one, is also evidence of this.

It's a terrible design, and I'm always doing a two-step close for my apps going to the list of running apps to "swipe" them off - but that's what Google wants, and what users are accustomed to.

We could maybe expose a way to force a full quit, but the default behaviour of `get_tree().quit()` should be what is the norm on the given platform, and for Android it's the current behaviour.

**Comment by ZodmanPerth** [comment]
[Note: I missed adding a link to the [design guidance](https://developer.android.com/training/implementing-navigation/temporal) I found from Google in the original post.  I've gone back and added it.]

Thanks for pointing that out; I admit I had forgotten those links.  They do point to the official Android developer wiki where I would expect to find a "thou shalt not kill the process" commandment, yet I haven't found any.

If Godot were going to consider implementing a force quit, I'd suggest the following chain of events:
1. Talk to a person at Google who can definitively say whether it's allowed or not (if we can find such a person).
2. Test to see if `System.exit(0);` actually works
3. Add the new command to force quit, or extend the existing `get_tree().quit()` command.

If this were to go ahead to implementation, I think I would prefer to see a parameter added to the existing command to distinguish the current quit from a force quit, such as `get_tree().quit(true)` or `get_tree().quit(0)`, rather than a new command like `get_tree.force_quit()`.  That's my personal expectation though; if it gets implemented I'll be happy no matter how it's done.

Of course, this all depends if events 1 and 2 work out positively.  I want to really be sure Godot's reputation isn't damaged if we introduce a force quit and Google start blocking our apps in the store again (not to mention the wasted development effort if we have to go back it out again).
