### ISSUE TITLE
Resource Loading errors at Android start

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#24052]
**Godot version:**

v3.1.alpha.calinou.5b8dde4

**OS/device including version:**
Samsung Galaxy J5
Oukitel K6000 pro

**Issue description:**
When I start my app on android, I get errors that some of my textures and materials can't be loaded. Unlike my last issue, this time I have installed the correct export templates.

> 11-29 13:08:02.745  8087  8122 E godot   : **ERROR**: Failed loading resource: res://.import/parkhaeuserDaecher.png-089c4d5afc23a5cab1c7a2db1a0e3fbb.etc2.stex
> 11-29 13:08:02.745  8087  8122 E godot   :    At: core/io/resource_loader.cpp:192:_load() - Method/Function Failed, returning: RES()
> 11-29 13:08:02.746  8087  8122 E godot   : **ERROR**: Failed loading resource: res://3D_Models/textures/parkhaeuserDaecher.png

**Steps to reproduce:**
I can't upload my project,  but I could create a minimal reproduction project if it helps to investigate this issue. Just say what you need and I'll try to provide it.

**Comment by volzhs** [comment]
probably you need to use `etc` format rather than `etc2`

**Comment by Tobi-La** [comment]
> 
> 
> probably you need to use `etc` format rather than `etc2`

How can I do this? I've looked through everything configured in my export, but i haven't found anything related to etc2 or etc1

**Comment by clayjohn** [comment]
No. You need to select the proper format for the hardware you are trying to support. Godot cannot make a device support etc2 that only supports etc. 

Closing. As you were able to fix this.
