### ISSUE TITLE
Relative paths in tscn files work but godot substitutes with absolute ones on save.

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24055]
**Godot version:**
11d77386

**Issue description:**
For the purpose of code/asset reusage, having relative paths is absolutely great (as mentioned in #22019).
Godot's ability to read relative paths for tscn files(at least in the editor) is present, so why not making it as a default for resources that are in the same folder/subfolders? And if not a default, at least Godot should not edit it back to an absolute path.
I think it is generally likely for tscn files for being moved together with the folder where they live in.
If i recall correctly, it was present on 2.1

**Minimal reproduction project:**
Before opening with godot, open a text editor.
The scene called Node2D in the sub1 folder has a relative path inside.
Open godot, open the scene, save, close
Open the tscn again with the text editor and you will see that the path has changed to absolute.

[RelativePath.zip](https://github.com/godotengine/godot/files/2629718/RelativePath.zip)

**Comment by QbieShay** [comment]
Bumping @reduz based on the blame of https://github.com/godotengine/godot/blob/4a0f7837324801f405e5c87619219b8cd03c86c2/scene/resources/scene_format_text.cpp#L1474

**Comment by bojidar-bg** [comment]
Relevant past issues of note: #1694, #3244, #3842.
Relative path caused some trouble back then, so they were removed.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2327, as feature proposals are now tracked on the Godot proposals repository.
