### ISSUE TITLE
Particles-node lead to a crash on my android device

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#24058]
**Godot version:**
3.0.6 stable

**OS/device including version:**
Issue appeared on Oukitel K6000 Pro running on Android 6.0
Tested also on Samsung Galaxy J5 with Android 7

**Issue description:**
I created a test app. It's crashing on android on my K6000 Pro, but it works on my Galaxy J5
Since I don't know what to look for I created a file from logcat, I filtered all lines with "godot", hope thats enough.

[log.txt](https://github.com/godotengine/godot/files/2630335/log.txt)

**Steps to reproduce:**
Create a prticle node and run the app on my android device. Don't know on how many devices this is a problem, it's on 50% of mine (2 devices).

**Minimal reproduction project:**
[ParticlesCrash.zip](https://github.com/godotengine/godot/files/2630346/ParticlesCrash.zip)

**Comment by clayjohn** [comment]
Is this reproducible in 3.1?

**Comment by Tobi-La** [comment]
I could only test GLES2, on which the cpu particles didn't crash yet.
