### ISSUE TITLE
Variable type is overwritten by a local variable

### ISSUE THREAD

**Issue by mineevgleb** [godotengine/godot#24059]
**Godot version:**
3.1, nightly build (28 Nov)

**OS/device including version:**
Windows  #10

**Issue description:**
Minimal reproduction script (I use inner classes here, also works with regular classes):

```
class Foo:
	var some_var:Vector2 = Vector2.UP
	
class Bar:
	var some_var:float
	var foo_var:Foo
	
	func do_stuff():
		return foo_var.some_var.bounce(Vector2.DOWN) 
```

**Expected:** produce no errors
**Actual:**  _Parse Error: Method 'bounce' is not declared on base 'float'._

**Comment by girng** [comment]
@vnen is lead typed gds author, he can help here

**Comment by AlexAndDraw** [comment]
I'm not entirely sure but this may be a side effect of "can't shadow variables from parent scopes" that is Calinou's change list. I came across this issue a while ago at [#22556](https://github.com/godotengine/godot/issues/22556)
