### ISSUE TITLE
libpulse issue in exported game on linux

### ISSUE THREAD

**Issue by TierraDelFuego** [godotengine/godot#2406]
When I build godot on linux I see this and it is expected because I don't use pulseaudio.

"PulseAudio development libraries not found, disabling driver"

Godot builds fine and it runs fine. But when I export my game it get this when I try to run the game:

error while loading shared libraries: libpulse-simple.so.0: cannot open shared object file: No such file or directory

So, I can not export and run any game.

**Comment by TierraDelFuego** [comment]
If I had more info about what export does and how it does it I could attempt to provide a fix. But I looked at the source and the docs (not much) and nothing jumped out at me.  If you tell me where to look I will try again.

**Comment by okamstudio** [comment]
you can check the compilation options in platform/x11/detect.py

I'm not going to fix anything related to users that don't want Pulseaudio,
but if you figure out how to fix your problem just send a PR and I will
merge it.

On Sun, Aug 30, 2015 at 6:14 PM, TierraDelFuego <notifications@github.com>
wrote:

> If I had more info about what export does and how it does it I could
> attempt to provide a fix. But I looked at the source and the docs (not
> much) and nothing jumped out at me. If you tell me where to look I will try
> again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2406#issuecomment-136194183>.
>



-- 

*OkamStudio*

**Comment by TierraDelFuego** [comment]
I found what the problem was/is. Under ~/.godot/templates/ there are godot executables that are pre-built and came with the templates from here [templates](https://objects.dreamhost.com/godot-builds/release/export_templates-1.1stable.tpz)  To fix the problem I copied the  linux_x11_64_release aside and copied my own built godot to linux_x11_64_release.

This was really puzzling because my built godot is dynamically linked and had no libpulse.

**Comment by TierraDelFuego** [comment]
I have been playing with Godot for a few days. Until then I had never heard of it. You probably know what my problem is now based on what I said here before. But to make it clear I will point out what the problems are now.
* Instead of a statically linked exported game I have the dynamically linked one from my build of Godot.
* This dynamically linked game is probably not portable across linux distros
* When I try to statically link my Godot build it fails because I am missing some *.a static libs
* But I also opened something like Pandora's box when I investigated this issue:
"/bld/godot/drivers/unix/ip_unix.cpp:68: warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking"

Can you share the build instructions that are used to build the templates?

Also can you explain the licensing with the export templates? If you deliver the exported game as a static executable of Godot then you're distributing GPL code. What are the implications? Is the game code and assets considered a derivation and is it all included in the data.pck file?

**Comment by punto-** [comment]
Are static glibc and pulseaudio GPL? The engine is MIT.

**Comment by TierraDelFuego** [comment]
Read here for a trip down the rabbit hole. [:rabbit::cyclone:](http://stackoverflow.com/a/15165424)

**Comment by TierraDelFuego** [comment]
http://www.musl-libc.org/ may provide a solution for this libc issue.

**Comment by akien-mga** [comment]
The initial issue is fixed apparently since it was a case of using the wrong export templates.

Regarding statically linking, this is a priori not needed, though you might want to build your templates on an old distro like Ubuntu 12.04 LTS to ensure that you won't use a too recent libc ABI. Another issue might be if you compile openssl support, as Fedora and the rest of the Linux world don't use the same soname for openssl, so a binary built on a non-Fedora distro won't work on Fedora (#1391).

**Comment by TierraDelFuego** [comment]
I think saying it's not needed is not correct.  Maybe it would be more correct for you to say "I don't need it and so no one else should either."  But imagine if you put a game on Valve's Steam platform. It's really hard to say what version of linux a gamer might be on. They could be any one of so, so many that having a statically linked game would solve the issue for all linux flavors out there.

It is a very real issue to not be able to link statically on linux. Should I take the time to file an enhancement request?

**Comment by Hinsbart** [comment]
I think you're right generally, that's why the majority of 3rd party dependancies are bundled in the repo and (afaik) linked statically. 

But if it's specifically steam you're worried about then take a look at the [steam runtime](https://github.com/ValveSoftware/steam-runtime).
Programs built against this should, in theory, run on every steam equipped system ^^

**Comment by TierraDelFuego** [comment]
@Hinsbart, thanks, steam runtime sounds like the right thing to do, but it also adds a lot of complexity to the laptop environment. I will have to decide what to do I guess.
