### ISSUE TITLE
Scene snap settings are lost whe the editor is closed

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#24068]
**Godot version:**
 5b8dde4

**Issue description:**
The scene's snap settings (enable snapping, grid size, etc) are lost once the editor is closed, and the scene reopened.

**Comment by akien-mga** [comment]
Note to contributors looking into fixing this: such information should be saved in per-scene metadata files which already exist and are stored in `EditorSettings::get_singleton()->get_project_settings_dir()`. See e.g.:
```
editor/editor_node.cpp
759:    String path = EditorSettings::get_singleton()->get_project_settings_dir().plus_file(p_file.get_file() + "-editstate-" + p_file.md5_text() + ".cfg");
```

**Comment by kareed44** [comment]
I'm new to Godot but was thinking about giving this a shot. This is labeled as a "bug" so I'm assuming a scene's editor settings could be persisted at some point. I poked around and found scene/gui/graph_edit.cpp which appears to be where the settings are both toggled and consumed to alter scene graph editor behaviour. I was hoping to find a usage of is_using_snap() where a scene is saved to disk but didnt find anything. That leads me to believe this is not really a bug but new functionality. Does anyone know where in the code base a scene is saved so I can explore further?

**Comment by kareed44** [comment]
After a quick glance browsing code on my phone, it appears that the "state" of a scene that we save to disk is comprised of all the individual EditorPlugin's states. It doesnt look like the holistic state of a scene includes the graph editor's state, because the scene graph editor is not an EditorPlugin.

**Comment by kareed44** [comment]
@YeldhamDev Can you provide replication steps? I pulled down 5b8dde4b4a5a930e08da51e07ec87f43e5bd7b36 and was not able to replicate the bug. Both 2d and 3d plugins that contain state like "snap_enabled" (editor/plugins/spatial_editor_plugin.cpp) and "snap_active" (editor/plugins/canvas_item_editor_plugin.cpp) appear to save state properly.

**Comment by YeldhamDev** [comment]
Just tested with the most recent build (7ac67bf) and snap settings aren't saved.

I one scene, I toggled snapping and marked to show the grid, but when reopened, it didn't memorize those actions.

**Comment by kareed44** [comment]
I'm new to fixing bugs in this codebase, so bear with me... Just to clarify, you changed the snap settings in the 2d/3d view port using the toolbar buttons above the view port, and in addition, explicitly saved the scene before closing the editor?

**Comment by YeldhamDev** [comment]
Yes.

**Comment by kareed44** [comment]
Thanks for the confirmation. I pulled that commit and tried to rep again. I was not able to. Here is a gif of my attempt:
![gif](https://user-images.githubusercontent.com/8959452/50108068-4e65df00-0202-11e9-8517-a8bc42deb50b.gif). Notice the various snap settings, snap toggle, and view grid selections being maintained after saving, closing, and re-opening the scene. I did not close the editor but the behavior is the same in my environment regardless of that step.

**Comment by YeldhamDev** [comment]
> [...]are lost once the **editor** is closed, and the scene reopened.

**Comment by kareed44** [comment]
As I explained in my last comment, they are not lost when closing the editor and reopening. Here is a gif proving that (apologies for the poor gif quality):
![gif](https://user-images.githubusercontent.com/8959452/50111597-17e09200-020b-11e9-9093-d87e4e6faf0d.gif)

**Comment by YeldhamDev** [comment]
I did more tests, and found what's really happening: This only happens to scenes being reopened by the editor when "Restore Scenes on Load" is enabled.

**Comment by kareed44** [comment]
Nice! Thanks for getting to the bottom of it. I'll check it out and try to fix it.

**Comment by mikeepiazza** [comment]
Are there any updates for this issue? I am new to Godot and would like to fix this.

**Comment by YeldhamDev** [comment]
@mikeepiazza Go right ahead.

**Comment by mikeepiazza** [comment]
I think this bug may have been fixed; my guess would be change to the config file where they are loaded from.

I had trouble replicating this last week, and am still unable after clean install with "Restore Scenes on Load" enabled.

**Comment by YeldhamDev** [comment]
Yep, it seems that this got fixed somewhere, closing it.
