### ISSUE TITLE
AnimationPlayer treats all Animations as the same

### ISSUE THREAD

**Issue by godofgrunts** [godotengine/godot#24063]
**Godot version:
 3.1 Alpha 2**

**OS/device including version: ArchLinux
$ uname -r
4.19.4-arch1-1-ARCH**

**Issue description:
AnimationPlayer treats all Animations as the same instead of being independent animations.**

Expectation: When I create a new Animation in an AnimationPlayer, I should be able to independently change tracks without affecting the other Animations.

What Happens: Whenever a track is changed in one Animation, it changes in all Animations on that AnimationPlayer.

**Steps to reproduce:**

Create an AnimationPlayer
Create an Animation
Create a Track
Create a New Animation
Observe that the tracks are the same
Change track
Switch back to the other Animation
Observe that the tracks are the same as the other Animation.

![Bug](https://thumbs.gfycat.com/ShamefulUntidyFlyinglemur-size_restricted.gif)

**Minimal reproduction project:**

Well I was going to create a project for you, but when I tried it it was working. I then deleted the AnimationPlayer on my project you see in the Video and it worked fine as well.

So all I got is the video that is above.

**Comment by girng** [comment]
can't replicate this  :/ 

do you think it might have just been an edge case?

**Comment by avencherus** [comment]
I also wasn't able to recreate the problem with the provided steps.  (Win10 build 5b8dde4.)

**Comment by godofgrunts** [comment]
@girng @avencherus It might just have been an edge case. I'm not sure how it happened and I can't get it to do it again either.

**Comment by akien-mga** [comment]
Closing for now as it doesn't seem reproducible. Please comment if you find out how to reproduce it again and we'll reopen it.
