### ISSUE TITLE
float-to-int truncation/conversion error in HTML5 (e.g. with ProximityGroup)

### ISSUE THREAD

**Issue by puzzud** [godotengine/godot#24060]
**Godot version:**
v3.0.6-stable_x11.64

**OS/device including version:**
Kubuntu 18.04

**Issue description:**
The presence of a ProximityGroup node in a scene will result in an error when running its temporarily exported HTML5 version. In Firefox (Quantum 63.0.3 64-bit), it produces a bunch of error statements different than when opened in Chrome (70.0.3538.110 (Official Build) (64-bit)).

Output listings are provided at the end of this document.

**Steps to reproduce:**

1. Add a ProximityGroup node to a scene.
2. Press the preview HTML5 export button in upper right corner of Godot Editor (assumes HTML5 export is set up).
3. Observe errors in Output window on web page.

**Minimal reproduction project:**
NA

**Output (Firefox):**
Init OS
Init Audio
Init VS
Init Physicsserver
OpenGL ES 3.0 Renderer: Mozilla
**ERROR**: exception thrown: RuntimeError: invalid conversion to integer,__ZN14ProximityGroup13update_groupsEv@file:///home/puzzud/.cache/godot/tmp_export.js line 92 > WebAssembly.instantiate:wasm-function[14176]:0x776984
__ZN14ProximityGroup14_notificationvEib@file:///home/puzzud/.cache/godot/tmp_export.js line 92 > WebAssembly.instantiate:wasm-function[14166]:0x7763e8
__ZN6Object12notificationEib@file:///home/puzzud/.cache/godot/tmp_export.js line 92 > WebAssembly.instantiate:wasm-function[26969]:0xf191fd
__ZN9SceneTree9iterationEf@file:///home/puzzud/.cache/godot/tmp_export.js line 92 > WebAssembly.instantiate:wasm-function[9558]:0x51cda2
__ZN4Main9iterationEv@file:///home/puzzud/.cache/godot/tmp_export.js line 92 > WebAssembly.instantiate:wasm-function[574]:0x49ef0
__ZN13OS_JavaScript17main_loop_iterateEv@file:///home/puzzud/.cache/godot/tmp_export.js line 92 > WebAssembly.instantiate:wasm-function[325]:0x2e06b
__ZL9main_loopv@file:///home/puzzud/.cache/godot/tmp_export.js line 92 > WebAssembly.instantiate:wasm-function[394]:0x30103
dynCall_v@file:///home/puzzud/.cache/godot/tmp_export.js line 92 > WebAssembly.instantiate:wasm-function[32382]:0x123fd0a
RuntimeEnvironment/Module.dynCall_v@file:///home/puzzud/.cache/godot/tmp_export.js:4:315314
browserIterationFunc@file:///home/puzzud/.cache/godot/tmp_export.js:4:176274
runIter@file:///home/puzzud/.cache/godot/tmp_export.js:4:179366
Browser_mainLoop_runner@file:///home/puzzud/.cache/godot/tmp_export.js:4:177811

**Output (Chrome):**
**ERROR**: Failed loading file 'tmp_export.wasm'

**Comment by puzzud** [comment]
I don't think I need a ProximityGroup at this point, as I'm just learning Godot. I happened upon this bug on accident. I figured I'd file an issue.

**Comment by eska014** [comment]
This was fixed in #22857
