### ISSUE TITLE
Project's default font doesn't update in the editor until reload

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#24067]
**Godot version:**
3.1 alpha2 (and previous ones too)

**Issue description:**
When you change default font in Project settings -> Gui -> Theme -> Custom font, it doesn't take effect immediately. The scene preview looks the same, even if you reload the scene. When you run the game however, the font is updated correctly. You need to reload the project to fix editor.

**Steps to reproduce:**
1. Place a Label node on a scene
2. Change custom font
3. You need to reload project to update the Label
4. ...
5. No profit :(

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2631197/TestProject.zip)
Just set the new_dynamicfont.tres as custom font as described above. Bonus: when you set custom font and reload project, the label will appear glitchy until you reload scene or move the Label.

**Comment by phaitonican** [comment]
same bug here

**Comment by me2beats** [comment]
Maybe not a bug, but the warning/popup should appear at least,
like: `The editor needs to be reloaded. Reload?`

**Comment by Calinou** [comment]
The Project Settings are already configured in a way that displays such a a warning message:

https://github.com/godotengine/godot/blob/1435b2f2cb91fa73f587b539503496abff18adcc/scene/register_scene_types.cpp#L750
