### ISSUE TITLE
Can't switch between tabs by Ctrl+Tab

### ISSUE THREAD

**Issue by winterwolf** [godotengine/godot#24064]
**Godot version:** 3.0.6

**OS/device including version:** Xubuntu 18.04

**Issue description:** 

Ctrl+Tab and Ctrl+Shift+Tab doesn't work to switch between tabs. If I change keybindings and replace the Tab button to something else, it will work, but this is not a solution.

**Comment by akien-mga** [comment]
Reopening as #30721 was reverted.
