### ISSUE TITLE
Sprite3D covers editor icons disregarding depth

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#24069]
**Godot version:**
3.1 alpha2

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/49257646-2bca7c80-f433-11e8-8cc4-6c9424a4b4bc.png)
![image](https://user-images.githubusercontent.com/2223172/49257659-338a2100-f433-11e8-9056-544f6effdc4d.png)
The light is in front of Sprite3D, but the icon gets covered when you look from the front.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2631212/TestProject.zip)

**Comment by CptPotato** [comment]
Does this also happen when they are further apart? If not it's probably related to z-sorting in which case there may not be a perfect solusion.

**Comment by KoBeWi** [comment]
Seems to be happening on any distance.

**Comment by KoBeWi** [comment]
Still valid in 3.2.2

**Comment by Calinou** [comment]
If you can build Godot from source, please build the `3.2` branch and test this again now that https://github.com/godotengine/godot/pull/39867 has been merged. (That pull request also makes Sprite3D much faster to render.)

**Comment by KoBeWi** [comment]
Still not fixed, tested with the provided binary.

**Comment by KoBeWi** [comment]
Still valid in 39534a7

**Comment by Calinou** [comment]
This can likely be fixed by changing 3D editor gizmo icons' alpha mode to Opaque Prepass (or Alpha Cut, but it'll cause visible aliasing).

**Comment by Rindbee** [comment]
Still valid in in v3.5.2.stable.official [170ba337a] and v4.0.stable.official [92bee43ad].

**Comment by lorenzokerbrat** [comment]
Still valid in v4.2.beta3 [e8d57afae]
