### ISSUE TITLE
AnimationTree StateMachine abrupt transitions

### ISSUE THREAD

**Issue by DwanaG** [godotengine/godot#24071]
**Godot version:**
3.1 latest 5b8dde4b4a5a930e08da51e07ec87f43e5bd7b36

**OS/device including version:**
Windows 10 64-bits
NVIDIA GeForce GTX 660 Ti

**Issue description:**
While using AnimationTree, I want to make a transition from one animation to another. This works perfectly fine using a BlendTree as tree root and an AnimationNodeTransition like so:
![godot_transition](https://user-images.githubusercontent.com/29492561/49257037-97422900-f3f6-11e8-9070-623247f03c3b.png)

The problem comes when I try to achieve the same using a StateMachine as tree root like so:
![godot_sm](https://user-images.githubusercontent.com/29492561/49257421-e2a90700-f3f7-11e8-883c-99a07c23764d.png)

I set the crossfade time in the transition node to be the same as in the state machine transitions, but the animation done with the state machine has much more abrupt transitions. This is more evident when the transition happens in the middle of the animation's timeline.

**Steps to reproduce:**
Add an AnimationTree node
Make the tree root a AnimationNodeStateMachine
Set up two states using AnimationNodeAnimation
Make immediate transitions connecting the states both ways
Travel from one state to the other within the editor... the transitions aren't as soft as in the case of AnimationNodeTransition

**Minimal reproduction project:**
I've made a sample project where you can compare side by side the transition done with AnimationNodeTransition and transitions from AnimationNodeStateMachine

![animation](https://user-images.githubusercontent.com/29492561/49258156-14bb6880-f3fa-11e8-982e-41031bc431d0.gif)

[AnimationTree.zip](https://github.com/godotengine/godot/files/2631229/AnimationTree.zip)

**Comment by guilhermefelipecgs** [comment]
It's not a bug, in your code, the names of the state machine nodes are wrong.

chante this:
```
$SM/AnimationTree["parameters/playback"].travel("Idle")
$SM/AnimationTree["parameters/playback"].travel("Walk")
```
to this:
```
$SM/AnimationTree["parameters/playback"].travel("Idle-loop")
$SM/AnimationTree["parameters/playback"].travel("Walk-loop")
```

![Peek 23-05-2019 12-12](https://user-images.githubusercontent.com/1387165/58264379-24d25600-7d54-11e9-84fe-898eaf98657e.gif)
