### ISSUE TITLE
Duplicate resource into another directory

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#24072]
"Duplicate resource" option right now is very lacking. It just allows you to specify the new resource's name and that's it. If you want to duplicate the resource and move it somewhere else, you need to do these operations separately, triggering importing twice.

Either the duplicate resource should open a standard file explorer or Ctrl + Move resource should duplicate it on destination.

**Comment by Zylann** [comment]
I think the importer should not have to re-run a second time just because a file name changed... this is silly. For a reference, in Unity duplicating or moving a file never causes this to happen because assets are uniquely identified rather than using the filename.
