### ISSUE TITLE
3D MODE:: Frustum culling starts to glitch when far enough from scene origin

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#2408]
My specs.

---
- Win7 64bit
- 16GB RAM
- an ATI 7xxx GPU
- a third gen i7 CPU
# 

The images should explain everything, some objects become invisible depending on the camera angle and camera zoom (and it has nothing to do with the render settings in the project settings window or the clip values). The one thing that I know is quite consistent is that this never seems to be a problem if you have the camera pointed straight down or you have the camera looking out from near the center of the scene (coordinates being close to 0,0,0), but mainly if the camera starts going further from the origin and is looking at a shallower angle. I also notice that when I zoom, there seems to be a window where the objects are invisible, I can start with the objects being visible, then zoom out and see them go invisible and then visible again.
![godotbug1a](https://cloud.githubusercontent.com/assets/10081256/9569453/9fec5a8e-4f31-11e5-904e-78a071f35afd.jpg) ![godotbug1b](https://cloud.githubusercontent.com/assets/10081256/9569456/a6e677de-4f31-11e5-98b9-85b0f9edbd8c.jpg)

I am treating this as a bug because I do not think this is intentional behavior that can simply be fixed with a setting change. I hope it can be fixed.

**Comment by Ace-Dragon** [comment]
Okay, I found that this might due to a bug in Godot's culling code, because increasing the *cull margin* value for the meshes that are disappearing makes the problem appear a bit less (but not completely unless the margin is rather large).

**Comment by reduz** [comment]
can you re-test in 3.0?

**Comment by reduz** [comment]
I will close because the renderer was pretty much done from scratch, please report again if you see something similar
