### ISSUE TITLE
Add methods for getting mesh data

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#24081]
At the moment we have only `get_faces()` that returns positions of the vertices.

I wanted to get normals/colors/others but I couldn't find any method for that (for debugging purposes).

Methods like get_normals() or get_colors(), get_uvs(), etc. could be useful.

**Comment by Zylann** [comment]
If you have an `ArrayMesh` you can get this information by using `surface_get_arrays()`: https://docs.godotengine.org/en/3.0/classes/class_arraymesh.html?highlight=ArrayMesh#class-arraymesh-surface-get-arrays
Each element in the returned array will then be a PoolVector3 for positions, PoolVector2 for UVs, PoolColorArray for colors etc

**Comment by clayjohn** [comment]
@Zylann It looks like `surface_get_arrays()` has been added to `Mesh` at some point. It is in the current master, not sure which releases it is in though.

**Comment by Calinou** [comment]
This is likely addressed in 3.2 and later per the above comments, closing. If not, please open a proposal on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.
