### ISSUE TITLE
label's rect_size doesn't get updated visually or in code 

### ISSUE THREAD

**Issue by girng** [godotengine/godot#24093]
**Godot version:**
989b93d6a406d439367bf34fb39b422c0f639f17

**OS/device including version:**
Windows 10, 64-bit

**Issue description:**
rect_size doesn't get updated after it gets updated in code.

**Steps to reproduce:**
- create a label node
- attach this script to it:
```
extends Label

func _ready():
	yield(get_tree().create_timer(0.5), "timeout")
	rect_size = Vector2(0, 0)
	text = "muffhr5thr5t r hr iohtgu9 ertgh789grtehrtge 98hgret98hrne98uin rth tr "
	yield(get_tree().create_timer(0.5), "timeout")
	text = "muffh"
	#yield(get_tree().create_timer(0.1), "timeout")
	# Uncoment the above code and it works
	rect_size = Vector2(0, 0)
	print(rect_size)
	
```

`rect_size` prints `(456, 21)`, even if we resized the label to Vector2(0, 0).

back in 2.1, a good trick was to do `yield(get_tree(), "idle_frame")` instead of creating a `0.1s` timeout signal.  the `idle_frame` works, but that feels hacky IMO and in 3.1 it creates a noticeable frame delay that's visible.

## what's expected:
- when the label's rect_size is updated, it needs to update the label's size.

i also don't even know if this is related to just labels... i think it's anything that inherits `rect_size` tbh
this also makes it very hard to create dynamic tooltips. you need to do idle_frame hacks, timeout signals, etc

**Comment by bojidar-bg** [comment]
Related/Dupe: #20896?

**Comment by tom-jk** [comment]
Another test: a scene with a label with the following script attached:

```gdscript
extends Label

func _process(_delta):
	if Input.is_action_just_pressed("ui_accept"):
		text = "a longer sentence"
		yield(get_tree().create_timer(0.1), "timeout")
		text = "short"
		#yield(get_tree(), "idle_frame")
		rect_size = Vector2(0, 0)
```

run and press enter a few times. Each press the label cycles long string, short string, set size zero.

3.0.6:
after each press, the label is the smallest size that accomodates the short string.

3.1, 3.2, 3.2.2, 3.2.3.beta1:
after each odd press, the label remains the size of the long string.
after each even press, the label is the smallest size that accomodates the short string.

If you uncomment the idle frame yield, the label is small every time as expected. There is no frame delay that I can see.
You can also change the `rect_size = Vector2(0, 0)` to `set_deferred("rect_size", Vector2(0, 0)`.

**Comment by akien-mga** [comment]
Given the previous comment, I think things are behaving as expected and this was a misunderstanding. It's expected that min size gets recomputed at the end of the frame for the next frame, so when chaining such changes, you should indeed use `yield(get_tree(), "idle_frame")` if you need the next frame's value in the same code.

**Comment by avencherus** [comment]
Making deferred calls may be the better option, but can't think of a quick example to test.  Certainly with yields I have seen graphical flickering.  It gets even worse when there is a need to chain this information across many things.

I agree with the author, seems hacky.  When first encountering it, took me a few hours to figure out what was going on.

If it is intentional maybe this should become a proposal.  Would be nice if these values updated on demand, or even a function in controls to forcefully update this information.
