### ISSUE TITLE
Distorted interface [Intel HD 4000, Windows 8]

### ISSUE THREAD

**Issue by Doraflara** [godotengine/godot#24095]
**Godot version:** 3.0.6 win64

**OS/device including version:** Windows 8

**Issue description:**

I started using Godot, but a weird bug appeard. It seems that every time I maximize the GUI window the image expands, like in the image below. Also, it happens at one point when I select a node, making it impossible to work with

![erro](https://user-images.githubusercontent.com/45500641/49319092-58899d00-f4e2-11e8-9e92-55fcfd3245a9.png)

I'm thinking this can possibly be an incompatibility with some drivers (??)

**Comment by marcelofg55** [comment]
Is that using a HiDPI monitor?

**Comment by Doraflara** [comment]
No, and the GPU is the Intel HD graphics 4000
It seems that older versions of Godot are working just fine

**Comment by Doraflara** [comment]
However the older versions (anything below 3.0), have different functions and it is harder to find help online

**Comment by akien-mga** [comment]
Intel HD 4000 + Windows 8 indeed sounds like a usual suspect for "bad drivers". Can you see if you can update your drivers to a newer version and if it fixes the issue?

**Comment by Doraflara** [comment]
I did it yesterday, I purged the driver and then installed the newest version

**Comment by girng** [comment]
@Doraflara get anything in the console on launching godot?

**Comment by Doraflara** [comment]
Yeah: 
![image](https://user-images.githubusercontent.com/45500641/49616372-b8c38780-f997-11e8-8ca0-bdb7811fcdae.png)
Sorry for the delay

**Comment by girng** [comment]
i plead akien's comment above. :/

**Comment by akien-mga** [comment]
Indeed, that's a typical case of broken drivers and there's nothing we can do sadly. I'm surprised though that it does work to some extent and breaks while using it, looks like the drivers are really on the line between "working" and "buggy".

You have two possible solutions:
- Use a recent build of Godot 3.1 alpha ([3.1 alpha 2](https://godotengine.org/article/dev-snapshot-godot-3-1-alpha-2), or alpha 3 coming soon, or a [nightly build](https://hugo.pro/projects/godot-builds/)). This version supports OpenGL 2.1 (OpenGL ES 2.0), which should work fine on Intel HD 4000. You would need to set the renderer to "GLES2" in the project settings (or start Godot with the command line with `godot.exe --video-driver GLES2`).
- Dual boot Linux, as Intel HD 4000 works perfectly there with Mesa, providing support for up to OpenGL 4.2 (that's what I have :)):
```
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 18.3.0-rc6
```

**Comment by Doraflara** [comment]
Godot 3.1 alpha is presenting the same errors... I guess I'm stiking with the older versons of godot or buying a new pc (I've never used linux, maybe if I get a lot of free time I'll try that)

But thank you so much!

**Comment by Zireael07** [comment]
@Doraflara: Have you set 3.1 alpha to use GLES2? By default, it uses GLES3. GLES 2 can be set with a command line parameter, but I can't remember it now.

**Comment by Chaosus** [comment]
Ok, I guess there is nothing we can do about this problem (beside the advices of refreshing video driver or switch to GLES2). Closed.
