### ISSUE TITLE
OptionButton should allow letter jumping like ItemList

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#24099]
There's this OptionButton with dropdown menu and all, but it lacks one thing IMO. When the list is opened and you hover over it, you should be able to press letter keys to quickly jump to the next word starting with pressed letter. It's useful for long dropdowns.

Also, would be nice if it had cyclic behavior like described in #9724 (that's ninja-reopen btw >_>)

**Comment by girng** [comment]
+1, itemlist lets you do this already but it needs improvement as well.
![](https://i.gyazo.com/835dcdaf4d790756b0d25cbaebb5d0d4.gif)

for example, i'm pressing c and m. it won't let me go to chomping or chewable key. just muffin.
