### ISSUE TITLE
Editor freezing every few seconds after second time starting

### ISSUE THREAD

**Issue by mmatttheww** [godotengine/godot#24097]
**Godot version:**
v3.0.6 stable official
Occurs on both the 32 bit build and the 64 bit build.
Occurs in the 3.1 beta

**OS/device including version:**
Windows 10 Home 
Version 1803
OS Build: 17134.165
Processor: Intel Core i7-360QM CPU @ 2.40 GHz
RAM: 16.0 GB
Graphics: NVIDIA GeForce GT 650M

**Issue description:**
On every launch of the editor after the first, the editor will freeze about once every 2 seconds, for around a second. It does this even without any projects loaded. The issue gets fixed if I restart my computer, but comes back every time I close and then reopen the editor after the first time. The issue occurs in a blank project as well as all other projects. 

Here is an image of the profiler when the issue is occuring. You can see the editor behaving normally between the spikes. 
https://media.discordapp.net/attachments/477544613511692358/517934860892110858/unknown.png?width=723&height=305

**Steps to reproduce:**
Open the editor,
Close the editor,
Open the editor back up.

**Minimal reproduction project:**
Happens in any project, as well as without any projects loaded.

**Comment by mmatttheww** [comment]
update: this seems to have stopped happening after a system update? for all intents and purposes this is no longer affecting me

**Comment by akien-mga** [comment]
Good news! Closing as it's a Windows bug which we have no means to fix (but thankfully it seems fixed with recent updates).
