### ISSUE TITLE
Flipped sprites in scene don't export properly to tile-set

### ISSUE THREAD

**Issue by RadixSeven** [godotengine/godot#2410]
I had a sprite which flips its texture horizontally. This sprite was in a scene I exported to a tile set. The exported tile set does not preserve the flipping.

I am working under Linux with the stable version and have files to reproduce the bug. Mail eric_moyer@yahoo.com and I'll send you a copy. (I'd attach it but github won't let me.)

**Comment by akien-mga** [comment]
Hi @RadixSeven, could you attach the test project that you have for example on https://up1.ca?

**Comment by reduz** [comment]
You can flip tiles manually in the editor, but originally flipping of the sprite will be ignored
