### ISSUE TITLE
Name conflict in GDNative's godot_dictionary_get and new get() method

### ISSUE THREAD

**Issue by lupoDharkael** [godotengine/godot#24101]
https://github.com/godotengine/godot/pull/20627 adds a new and very useful method to obtain values from a Dictionary in a more convenient way.

After a look at the gdnative headers I realized they already contain a `godot_dictionary_get` but it is just the function to get a value just like with dict[key].
https://github.com/godotengine/godot/blob/492b4cf837ade72110d2ddbe606e8244ed15a54a/modules/gdnative/include/gdnative/dictionary.h#L84

As adding the new method breaks the naming pattern `godot_CLASS_METHOD` for the c functions. How should it be called?

**Comment by akien-mga** [comment]
CC @karroffel - should we rename `Dictionary.get` to avoid this conflict, or can we work it around somehow in GDNative?

**Comment by karroffel** [comment]
I would probably name it `godot_dictionary_get_default` or `godot_dictionary_get_with_default`. There have been many cases like this when wrapping overloaded methods, so finding a more specialized name is usually the best solution.

**Comment by Willowblade** [comment]
+1 for godot_dictionary_get_default, and one could also argue that godot_dictionary_get broke the naming pattern in the other direction?

**Comment by akien-mga** [comment]
@karroffel Would be good to have this done in 3.1.
