### ISSUE TITLE
Getting the actual texture size of TextureRect

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#24100]
TextureRect has an `expand` option and multiple settings for size, but it's missing one important thing: the ability to retrieve the actual size of the texture. I mean, you can only get the real size, but if you enable `expand` and the texture shrinks or expands or loses aspect, you need to do tricky maths to calculate the actual rendered size (which is sometimes useful).

So there should be a method, like `texture_size()`, which returns the scaled size of texture.

Here's an example image for more clarity:
![image](https://user-images.githubusercontent.com/2223172/49323844-9c9c9200-f522-11e8-8ed9-2913e52a4e5c.png)
I'd like to get the size of the big texture, which has rectangular area, enabled `expand` and `stretch_mode` set to `Keep Aspect Centered`. Having a method to avoid calculations would really help.

**Comment by KoBeWi** [comment]
Look at my example above. `rect_size` will be bigger in this case, so it's not always accurate.

**Comment by girng** [comment]
this is pretty rare to do imo. and gds is powerful enough to already get the size using mathematics

**Comment by KoBeWi** [comment]
I don't remember needing this in the past year. Also it has low support.
Closing for now.

**Comment by Wilker-uwu** [comment]
hello! :3  
what are my options for getting the absolute size to calculate into a shader's parameters?

**Comment by KoBeWi** [comment]
If you want the final texture size, you can check how size calculation is implemented and copy some parts:
https://github.com/godotengine/godot/blob/13a0d6e9b253654f5cc2a44f3d0b3cae10440443/scene/gui/texture_rect.cpp#L48-L105

**Comment by JekSun97** [comment]
we need a function that would accurately return the texture size get_rect taking into account rect_size
