### ISSUE TITLE
Drag spinboxes error (set_amount: Index p_amount out of size (1024))

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#2411]
*Bugsquad edit:* Seen in the master branch / 2.0 alpha

Problem founded in Particle2D, amount and lifetime.
If I move the mouse quickly up, it does not reach the maximum value.
and I get this error when I do this.

ERROR: set_amount: Index p_amount out of size (1024).
At: scene/2d/particles_2d.cpp:700
but the value stop in 854 for example.

Another bug, all controls that has "Range" properties, for example ProgressBar, if you change the "Min" value with this feature, godot will crash.

**Comment by okamstudio** [comment]
thanks for reporting this! will check asap

On Mon, Aug 31, 2015 at 12:39 PM, Guilherme Felipe <notifications@github.com
> wrote:

> Problem founded in Particle2D, amount and lifetime.
> If I move the mouse quickly up, it does not reach the maximum value.
> and I get this error when I do this.
>
> ERROR: set_amount: Index p_amount out of size (1024).
> At: scene/2d/particles_2d.cpp:700
> but the value stop in 854 for example.
>
> Another bug, all controls that has "Range" properties, for example
> ProgressBar, if you change the "Min" value with this feature, godot will
> crash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2411>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment]
Ah, this was actually a bug in Particles2D.. everything else seems to work now
