### ISSUE TITLE
Log.txt can't be opened while editor is running

### ISSUE THREAD

**Issue by JohnSilverLong** [godotengine/godot#24115]
I can't open log file while editor is running.  #21088
Have not been able to test this with a export.

**Comment by eon-s** [comment]
Fill the details required by the issue template (godot version and operating system), also specify the editor where you try open the file.

Cannot reproduce on 3.0.6 runing on Ubuntu, btw.

**Comment by JohnSilverLong** [comment]
Im on windows 7 using C# and don't know the current editor version its 3.1 something i build it from source with this last commit #21088.
Im a unity user and  quite new to godot so still figuring things out.

**Comment by akien-mga** [comment]
What `Log.txt` are you referring to?

Windows can't open files when another application is already writing to them, so that's expected that you can't open any file that you would be editing with Godot.

**Comment by Chaosus** [comment]
Yeah, there is not much we can do about it.. guess this can be closed
