### ISSUE TITLE
WebGL 2 game takes a long time to load on Mobile Chrome

### ISSUE THREAD

**Issue by GustavoMarciano** [godotengine/godot#24123]
Godot version:
All

OS/device including version:
Mobile Chrome Browsers

Issue description:
HTML game take a long time to load in mobile browsers ,while in desktop the game loads in 5-15 seconds the mobile versions takes 40-50 seconds to load
Edit: On firefox the loading time is normal but on Chrome takes 40-50 seconds

Minimal reproduction project:
https://dexpace.itch.io/ultra-gravity-switch

**Comment by NoSilver2018** [comment]
+Simialar with him, Mine runs fine on Firefox but not on Safari and Chrome. Plus, the performance of HTML export is very poor. Especially with sounds, there was a delay on my SFX.

**Comment by akien-mga** [comment]
See also #21957.

**Comment by GustavoMarciano** [comment]
@akien-mga Just a update, I tested on 3.1 beta 2 with webgl1 and the issue persists

**Comment by mjtorn** [comment]
Is this a problem with Chrome or Godot? I'm suffering of the same here.

**Comment by clayjohn** [comment]
Duplicate of https://github.com/godotengine/godot/issues/21957 tracking there.
