### ISSUE TITLE
interface to define custom graphics engine

### ISSUE THREAD

**Issue by cheece** [godotengine/godot#2412]
is it possible to add an interface to define custom graphics engines?

**Comment by GeorgeGkas** [comment]
What do you mean exactly by saying "Custom graphic engines". And why to define? What do you mean by that?

**Comment by cheece** [comment]
custom graphics engine: custom code for rendering
I mean defining what graphics engine to use, 
g.e. you programmed a graphics engine for rendering in godot and compiled it in form of dll maybe, then you define the library in godot as the custom graphics engine to use, by interface i mean to have a mechanism to do the integration without having to compile the entire godot engine again (some sort of plugin system)

p.s. sorry for my bad english

**Comment by punto-** [comment]
There already is an interface to provide your own graphics engine, it's
called "VisualServer", you can implement your own, using whatever graphics
driver, library or engine you want.

**Comment by draxdeveloper** [comment]
http://orig01.deviantart.net/9e63/f/2012/040/0/a/sorry_for_my_bad_english_by_ferlancer-d4cc910.jpg

2015-09-03 17:04 GMT-03:00 punto- <notifications@github.com>:

> There already is an interface to provide your own graphics engine, it's
> called "VisualServer", you can implement your own, using whatever graphics
> driver, library or engine you want.
>
> On Thu, Sep 3, 2015 at 1:58 AM, cheece <notifications@github.com> wrote:
>
> > custom graphics engine: custom code for rendering
> > I mean defining what graphics engine to use,
> > g.e. you programmed a graphics engine for rendering in godot and compiled
> > it in form of dll maybe, then you define the library in godot as the
> custom
> > graphics engine to use, by interface i mean to have a mechanism to do the
> > integration without having to compile the entire godot engine again (some
> > sort of plugin system)
> >
> > p.s. sorry for my bad english
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/2412#issuecomment-137276389
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2412#issuecomment-137559405>.
>



-- 
David Aguiar de Aquino Paiva
Dive sistemas
