### ISSUE TITLE
mouse speed not going back to zero in visual script.

### ISSUE THREAD

**Issue by haizhou37** [godotengine/godot#24127]
**Godot version:**
the latest version of godot master（9：00，3/12/2018）

**OS/device including version:**
manjaro gnome x64
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile
intel hd 3000

**Issue description:**
Through my tests, the mouse speed looks like it will keep the speed calculated in the previous frame, but when my mouse stops moving, it doesn't change to zero.
**You can ignore the error below. That's another [problem.**](https://github.com/godotengine/godot/issues/24128)

![2018-12-03 09-48-14](https://user-images.githubusercontent.com/33272474/49348861-e9c76200-f6e2-11e8-84b6-b12b731a7568.png)
![2018-12-03 09-47-35](https://user-images.githubusercontent.com/33272474/49348866-ecc25280-f6e2-11e8-960d-2dc224e0c0c3.png)
![2018-12-03 09-54-40](https://user-images.githubusercontent.com/33272474/49349927-e387b480-f6e7-11e8-8d62-8ff762c1198b.png)

**Steps to reproduce:**
Add a **_input** function to the visual script and step by step to get the properties associated with mouse movement(This is the only way I currently know how to get mouse movement information in a visual script)

**Minimal reproduction project:**
[test1.zip](https://github.com/godotengine/godot/files/2637792/test1.zip)

**Comment by groud** [comment]
That normal, if you don't move the mouse, the OS does not create MouseMotionEvents, so you have to reset the speed elsewhere (like in the process function for example, or somewhere like that)

Closing as this is not an engine bug. If you need advise on general GDscript, please ask on the [other community chanels](https://godotengine.org/community).
