### ISSUE TITLE
colorpicker's slider is hard to click

### ISSUE THREAD

**Issue by girng** [godotengine/godot#24124]
**Godot version:**
8dd00ed1762c4956b3231d709ce0d01ee9b306c8

**OS/device including version:**
win 10, 64-bit 

**Issue description:**
when trying to click on the colorpicker's slider, your mouse has to be over the tiny white ball.

example:
![](https://i.gyazo.com/956447a8b0b001eb94221bfd462d0a5b.gif)

imo it'd be a lot easier if the entire circle detected the mouse, not just the inner circle. also, visually your mind thinks it's over the entire ball (but it's not, because it has to be over the inner white circle), makes it harder to click

**Comment by Zylann** [comment]
Sounds like old closed https://github.com/godotengine/godot/issues/13845 ?

**Comment by bojidar-bg** [comment]
CC @toger5 @djrm, as they have worked on the theme.

**Comment by rogeriodec** [comment]
Also here: 
![c](https://user-images.githubusercontent.com/11199752/54833928-cfb78c80-4c9d-11e9-8cc3-7a9f00d9525e.gif)

Plese, fix this.
