### ISSUE TITLE
yield() ERROR _signal_callback

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#24122]
Win10 64-bit 5b8dde4

Minimal Project: [3.1 yield issue.zip](https://github.com/godotengine/godot/files/2637454/3.1.yield.issue.zip)

I get the following error after doing a resume() on a GD function state.

![cmd_2018-12-02_23-40-49](https://user-images.githubusercontent.com/13004169/49345436-70e9eb00-f68d-11e8-9026-fce0e4b998ef.png)

I was playing around with a way to manage the function state that comes out of a yield(), and there are a few steps to explain.  If I'm failing to describe it fully, the demo project or the code below may be the easier to follow.

The process is that I pass along the parameters I would like to use for a yield to set of helper functions that call the yield() to store the function state in a dictionary and return it to the caller.  Then what goes back can be yielded until signal "completed".

The next piece is a Cancel button, this will get the function state from the dictionary and call resume() on it.  Everything works fine, but at some later period after everything resolves that error appears.

```
extends Node2D

var cancel = false
var pending = {}


func _ready():

	var idling = managed_yield(idle(1000), "completed")
	yield(idling, "completed")

	if(cancel):
		print("Cancelling _ready()")
		return

	print("Completed Normally")


func idle(n):

	for i in range(n):

		yield(get_tree(), "idle_frame")

		if(cancel):
			print("Canceling idle()")
			break


func managed_yield(src, sig : String):

	var state = do_yield(src, sig)
	pending["abc"] = state
	return state


func do_yield(src, sig):
	yield(src, sig)



func _physics_process(delta):

	for id in pending.keys():

		var state : GDScriptFunctionState = pending[id]

		if(not state.is_valid()):
			pending.erase(id)


func _on_Button_pressed():

	cancel = true

	print(pending)

	for id in pending.keys():
		var state = pending[id]

		printt(id, state, state.is_valid())

		if(state.is_valid()):
			state.resume()

	print("AFTER BUTTON")
```

**Comment by KoBeWi** [comment]
Yield was removed in 4.0, so this is resolved.
