### ISSUE TITLE
Add UV and UV2 to Light Shader built-ins

### ISSUE THREAD

**Issue by esdinev** [godotengine/godot#24120]
**Godot version:**
3.1 alpha 2

**OS/device including version:**
Windows 10

**Issue description:**
no UV and UV2 built ins for Light shader.

I'm working on a stylized shader and I require the ability to access texture coordinates in the light shader. I've found a way to do it but it's a workaround and I'd greatly appreciate if the feature is added properly. There doesn't seem to be a technical reason behind the omission because as I said I've found a workaround and it works. So the only reason it's not there is ... the dev decided it shouldn't be there - which isn't quite rational considering it's a very basic feature.

**Comment by clayjohn** [comment]
I agree. Every built-in variable available in the fragment function should be available in the light function by default. After all the light function is called inside the fragment function.

**Comment by DiogoASTeixeira** [comment]
@esdinev I'm going to look into this. Could you show me your workaround so I can have a headstart in implementing?

**Comment by esdinev** [comment]
@DiogoASTeixeira Hello, Diogo. My work around is not at all applicable to a proper fix because I simply put the UV as a v2 in another built-in - one I knew would not be in use in my shader. 
As I said there really isn't any technical limitations which would stop you from passing a vector to the "light" shader from the "fragment" shader they are both the same shader underneath as far as I know, I'm only a tech artists so my knowledge of shader languages isn't as extensive as I'd want it to be otherwise I would've fixed this myself.

Anyway, I think the fix should be incredibly easy. Probably as easy as defining the built-in.
