### ISSUE TITLE
Zoom option for the tile selector when using tiny tiles

### ISSUE THREAD

**Issue by kamstrup** [godotengine/godot#2413]
I use 12x12 tiles for my maps and they are really hard to distinguish on a retina display. Maybe a zoom option for the tilset tiles or something else...
<img width="412" alt="screen shot 2015-09-01 at 21 29 40" src="https://cloud.githubusercontent.com/assets/201347/9614286/29dfc90e-50f1-11e5-869d-ce85412d569c.png">

**Comment by kamstrup** [comment]
Or maybe show the node name for the tile in the empty space on the left. That could be used as a workaround to make distinguishing tiles easier.

**Comment by guilhermefelipecgs** [comment]
The name of the tile was implemented in 2.0.alpha, but I agree with an option to zoom in.

**Comment by akien-mga** [comment]
+1 for that, it would be really useful. Back when I started with Godot I had a first project with 16x16 tiles that I would then render in 32x32 (but keeping them non-interpolated, so each pixel becomes 4 pixels), but the source tiles of 16x16 were a pain to use in the tile selector. In the end I chose to reimport my tiles in 32x32 to be able to work properly...
