### ISSUE TITLE
Tabbing into a field should autoselect its contents for quicker change

### ISSUE THREAD

**Issue by puzzud** [godotengine/godot#24138]
**Godot version:**
v3.0.6.stable.official.8314054

**Issue description:**
When using tab to cycle through different fields in any dialog in Godot should automatically have any existing value in that field already selected, so when typing in a new value its previous contents are overwritten, in order to greatly increase the efficiency of changing values (without having to interact with those fields with additional mouse clicks or cursor and shift key presses.

This behavior is common in UIs and game editors alike. Playcanvas does this well.

**Steps to reproduce:**
A good example that keeps reminding me of this enhancement is when I am modifying the RGB values of a color in Godot.

 - Create a material.
 - Modify its Albedo values.
 - Tab through the color value changing dialog.
 - Notice that when focus is changed to one of the color component numeric fields, the text cursor is prepended to any existing value in that field.
 - Type numbers into that field, similarly these values are prefixed to any existing value, meaning in order to replace this value, a user must take extra actions to delete existing contents.

**Comment by KoBeWi** [comment]
This was changed in 3.1 - using Tab now auto-selects the field.
