### ISSUE TITLE
Offset dragging point in PathFollow(2D) with value lesser than 1 overlap with Inspector

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#24131]
**Godot version:**
3.1 8dd00ed

**OS/device including version:**
Windows 10

**Issue description:**
When Path node with Curve and PathFollow is created, then changing offset to values lesser than 1, cause change position of dragging point to Inspector area

![dddd](https://user-images.githubusercontent.com/41945903/49363697-acfb6b00-f6e2-11e8-8023-2ea1d0c90316.png)

**Comment by bojidar-bg** [comment]
A circle for clarity:
![image](https://user-images.githubusercontent.com/5276727/49370966-8ba87800-f6fe-11e8-9ada-366ddceb1497.png)
