### ISSUE TITLE
Directory API opens "res://" on initialization, and can be used before running any explicit `open()` call

### ISSUE THREAD

**Issue by bitwes** [godotengine/godot#24149]
**Godot version:**

Godot 3.0

**OS/device including version:**

MacBook Pro (15-inch, 2016)
MacOS Sierra

**Issue description:**

I'm not 100% sure what caused the error but I tried to open a directory and got a `31` back.  Now, I should have been checking this return value but I didn't.  I then proceeded to delete everything in that directory.  Due to the error though the directory that was actually opened was "res://".  

**Steps to reproduce:**
This will make a file in `res://` and then delete it even though the directory failed to open.  This seems like dangerous behavior (as I found it was since I cleared out all the files in the root of the GUT tool).  I got them back no problem but not everybody has backups and this could mess up a project real bad just b/c they forgot to check the return value.
```
extends SceneTree

func file_touch(path):
	print('creating ', path)
	var f = File.new()
	f.open(path, f.WRITE)
	f.close()

func delete_file(directory, file):
	print('deleting ', directory, file)
	var d = Directory.new()
	var result = d.open(directory)
	d.remove(file)
	print('result = ', result)

func _init():
	file_touch('res://delete_this_guy.txt')
	delete_file('asdf://', 'delete_this_guy.txt')
	quit()
```

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
It is not that Directory opens "res://" on error. This is the default directory. You can remove this line `var result = d.open(directory)` and it will still delete the file. Failed `open` operation just means the current directory is not changed.

The correct "fix" would be not allowing any Directory operations unless you open a directory, but that sounds like "enhancement" and it's a thing for another issue.

**Comment by akien-mga** [comment]
I'm adding a mention to this "feature" in the docs with #34944.

IMO we should consider changing this behavior for 4.0 to force users to explicitly open a folder before doing any operation. This would require some refactoring of the way `DirAccess` is implemented in the different drivers.

**Comment by KoBeWi** [comment]
So #40151 basically resolved this issue (not sure why it wasn't closed).
