### ISSUE TITLE
Godot Mono C# 3.0.5

### ISSUE THREAD

**Issue by DesertLithiumFlower** [godotengine/godot#24144]

**Comment by bojidar-bg** [comment]
A reply.

---

Now, go back and add some description to your bug report/feature request, instead of leaving us in the dark, guessing what you meant. Additionally, there is an issue template, please try to follow it. :smiley:

**Comment by DesertLithiumFlower** [comment]
i cant opened, please delete this post, I can not edit it and I do not send anything, I could not delete it either, please delete this post
