### ISSUE TITLE
@bojidar-bg any idea status of this?

### ISSUE THREAD

**Issue by DesertLithiumFlower** [godotengine/godot#24150]
_Originally posted by @reduz in https://github.com/godotengine/godot/issues/17051#issuecomment-419228079_

report a similar problem, I am not a programmer and honestly I do not understand well, could you tell me if I put here what I asked and we deleted the ticket that I did or I left it like this, I do not want to do more volume of work I just want a little help, if you tell me what I do to correct it and it is in my basic knowledge or you guide me to solve it I would like to try it and so I will learn something more than what is currently

https://github.com/godotengine/godot/issues/24147

**Comment by girng** [comment]
send him a pm on discord =]

**Comment by DesertLithiumFlower** [comment]
> send him a pm on discord =]

I put the message in #help before coming here but nobody answered, I'm more in the channel #castellano, but mmmm... they are a bit strange for me, their answers are as if they saw you as an idiot because you do not know everything, one told me that if I'm not a programmer because I use a monkey, I better download a traditional version, so the only thing that stayed for me was to tell me that they asked me to do so at school and it does not have to be because I was uncool

**Comment by girng** [comment]
> I put the message in #help before coming here but nobody answered, I'm more in the channel #castellano, but mmmm... they are a bit strange for me, their answers are as if they saw you as an idiot because you do not know everything, one told me that if I'm not a programmer because I use a monkey, I better download a traditional version, so the only thing that stayed for me was to tell me that they asked me to do so at school and it does not have to be because I was uncool

yeah, just ignore em. the lead devs (if you are cordial) will be cordial back. just shoot him a pm. don't worry about the haters

**Comment by akien-mga** [comment]
If you want to add a comment to #17051, you should use the comment box at the bottom of the issue (when logged in on GitHub):
![screenshot_20181204_093144](https://user-images.githubusercontent.com/4701338/49428873-6a4f9680-f7a7-11e8-8e5a-8dd2ca0fa75b.png)

Please do not create a new issue like this one to single out a developer, especially since what you're asking for is very unclear. If you're asking for help with #24147, there's no need to do further comments for now, the issue has been filed already and will be reviewed whenever a developer has time. Same with #17051 (of which #24147 seems to be a duplicate, and might thus end up closed).

**Comment by akien-mga** [comment]
> they are a bit strange for me, their answers are as if they saw you as an idiot because you do not know everything, one told me that if I'm not a programmer because I use a monkey, I better download a traditional version, so the only thing that stayed for me was to tell me that they asked me to do so at school and it does not have to be because I was uncool

BTW I'm sorry you had a bad experience with the users on the Discord channels. Core Godot developers always do their best to be friendly and helpful, but we sadly can't control all users. Don't give up on asking for help on Discord though, the vast majority of users are very helpful and this bad experience should hopefully be an exception.

**Comment by bojidar-bg** [comment]
Just to mention it: I do check Discord's #help channel from time to time, but I can't read through all the messages that get spammed in there. For bugs it is best to use GitHub, and for suspected bugs, you might try #engine next time (though I'm not sure how many people read that one). And finally, the devs reply much faster on #godotengine-devel on IRC.
