### ISSUE TITLE
Script editor "Save As.." menu option does not recognize ".gd" file extension

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2415]
![bug2](https://cloud.githubusercontent.com/assets/4741886/9638262/07762a92-51a6-11e5-87a5-8502fd674c6a.gif)

It wants to save the Node2D, i want to save the script.

**Comment by m4nu3lf** [comment]
I have this issue too. If I save a script as .res godot creates a file, but I am unable to open it

**Comment by reduz** [comment]
hmm sucks, it's saving the scene somehow, will give it a test

**Comment by firefly2442** [comment]
I had the same problem.  If you use the inspector on the right hand side and click the save button I believe it works.

**Comment by AlexHolly** [comment]
Looks like #2459 is fixing it, but "script->file->save as" is still not working.
1. If you do "script->file->save as" after the steps you see in my first post the "script->file->save as" works.
2. If you do "script->file->save as" after opening a project without 1. "save as" is not working.
