### ISSUE TITLE
Merge from scene UI it's a bit counter intuitive

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24158]
**Godot version:**
11d7738

**Issue description:**
When opening the merge from scene dialog, there is an enormous empty space.
In the beginning, it seems like something is wrong, as if you forgot to select something that you are supposed to

**Proposal:**
Make it a 2 step UI that first asks for the scene and then asks for the nodes, since those steps can't be skipped anyway.

**Comment by girng** [comment]
i reckon it's large because the scene you select could have a lot nodes.
i agree it's too large, maybe it should expand based on the scene you select
