### ISSUE TITLE
Light2D mask switches its mask texture to the normal map texture of the Sprite it is lighting.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#24157]
Win10 64-bit 8dd00ed

Minimal Project: [3.1 Sprite Normal Map Issue.zip](https://github.com/godotengine/godot/files/2644652/3.1.Sprite.Normal.Map.Issue.zip)

The normal map applied to a Sprite node seems to override the light mask for a Light2D when they intersect with each other.

@JFonS From your recent work in this area, was curious if you might know more about what's happening?

## Current Result
The left sprite has the normal map pictured to the right, and the other sprite has no normal map texture.

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/13004169/49452623-35b0fe80-f7ea-11e8-9186-f6b7c5c00236.gif)

## Desired Result

Was expecting something like this.  (Rendered in another program.)

![diffuse_lit](https://user-images.githubusercontent.com/13004169/49467761-d7951300-f80b-11e8-95b4-aeb99e18a804.png)

It's unclear to me, but perhaps related to this: https://github.com/godotengine/godot/issues/24076

**Comment by bojidar-bg** [comment]
Not sure if it is a bug, Light2D is supposed to take normal maps into account.
Maybe a new option: "Ignore normal maps" might be added for masking usage? Or should it be the default?

**Comment by avencherus** [comment]
@bojidar-bg This is definitely not the desired result.  It may be that I'm not doing something correct, but the Light2D should not be changing its mask.

I think my title wording was a bit unclear on second reading.  Yes, it should take the normal map into account if you use one.  That is what I want.  The issue is not that it is taking normal mapping into account, the issue is that the light mask is changing entirely.

Look more closely at the center of that Light2D, that bright point is not the mask I put on the Light2D.

Below is the lightmask.  Why does it have the same hotspot as the normal map texture of that Sprite when it begins to light it?

![light_mask](https://user-images.githubusercontent.com/13004169/49465361-1a53ec80-f806-11e8-9dd3-ae09aed0de3f.png)

**Comment by avencherus** [comment]
Added an image of the desired / expected results in the original post.  Hopefully that clears the issue up.

**Comment by mrcdk** [comment]
You need to tweak the light's height to remove that. It's not changing the mask it's just that the normal map has the same effect the light at 0 height shows in your example.

**Comment by avencherus** [comment]
@mrcdk Major thanks and much appreciated for taking a look at it.  Exactly it, 0 height.  Glad it's nothing serious.

Is this conceptually a parameter for bump mapping / height maps?  Was blind to it and not thinking of it as a way to control the z-depth of a 2D light.
