### ISSUE TITLE
[2D] "CanvasLayer" versus "Z-index"

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#24153]
**Godot version:**
N/A

**OS/device including version:**
N/A

**Issue description:**
`CanvasLayer` uses `layer` to describe what layer to draw its nodes on. But nearly every other 2D node uses the terminology "Z Index" (`z_index`) to describe the same thing. This could be more consistent across them? One obvious solution could be to rename `CanvasLayer` simply `Canvas` and `layer` to `z_index` (although this would be API-breaking).

**Comment by CptPotato** [comment]
If I understand CanvasLayers correctly their `layer` property works a bit differently than what `z_index` does on 2D nodes. Naming them the same might be a little confusing, but it could be just me.

**Comment by girng** [comment]
i agree with potato. layer also implies (to me anyway) something to do with the user interface. and canvaslayer is mostly used for ui stuff. so the distinction between them makes sense

**Comment by swarnimarun** [comment]
As Pete said Z-Index and Layer values do not interact so it's both confusing and misleading to name them the same way.
We could, however, propose a better name for the layer. Like stack order/level or something like that.

**Comment by Chaosus** [comment]
@Sslaxx please recreate this post into https://github.com/godotengine/godot/issues/16863, since this is just a renaming issue I close this issue

**Comment by schaefchenaufderweide** [comment]
How is it possible, to set an object in front of a canvas layer?
