### ISSUE TITLE
Is this a debug line

### ISSUE THREAD

**Issue by w2qiao** [godotengine/godot#24152]
https://github.com/godotengine/godot/blob/e4ebe3db26588ecac670296069770a1c6dec7dc4/modules/xatlas_unwrap/register_types.cpp#L128

**Comment by akien-mga** [comment]
Maybe? Why do you want to know that?

**Comment by w2qiao** [comment]
Just curious. It looks like code not comment.

**Comment by groud** [comment]
This is not the place to ask general questions about the engine code, please use the [other community channels](https://godotengine.org/community).
