### ISSUE TITLE
Duplicate file name problem

### ISSUE THREAD

**Issue by NoSilver2018** [godotengine/godot#24167]
**Godot version:**

3.1

**OS/device including version:**

OSX, High Sierra

**Issue description:**

When you move the resource to the other folder that already exist same named file, there are no overlapping warning message. Because of that I lost my resource file.

**Comment by qarmin** [comment]
Can you write steps to reproduce this problem?
With this info I'm unable to reproduce this.

**Comment by KoBeWi** [comment]
The warning exists, but doesn't specify what file will be overwritten. Adding the filename to the dialog would be useful.

**Comment by KoBeWi** [comment]
Above comment is still valid in 3.2.3 rc1
