### ISSUE TITLE
can_move_to seems not working

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#2416]
I'm trying to check if a kinetic body can move to a determined position, can_move_to() should be the perfect choice for doing this but it seems not working properly.
I've made a test case for illustrating that. You can download from this location: 
http://www.officinepixel.com/download/godot/testcase_can_move_to.zip
when you run it you see KinematicBody trying to travel to Position3D but there is a rigid body in the between, so, when it reach the obstacle it stops. Despite this can_move_to() always returns true.

**Comment by guilhermefelipecgs** [comment]
I can't open your example.

**Comment by zoiba** [comment]
sorry, forgot to mention that the example was made with 2.0 alpha

**Comment by akien-mga** [comment]
I can confirm the issue using your test case. I've checked the code for KinematicBody::can_move_to and the second argument seems not to do anything: https://github.com/godotengine/godot/blob/2c45ee5e1ce939bcef32129ac01944f3995269f4/scene/3d/physics_body.cpp#L1095

**Comment by akien-mga** [comment]
Looked a bit more at the algorithm, it looks like this function was meant to:
- Check if the final destination is a collider (p_discrete = true)
- Check if the direct path to the final destination contains a collider (p_discrete = false), which is what you are expecting here.

But the p_discrete argument is overridden by ```if (true || p_discrete)```, so only the discrete behaviour is implemented. Now, this should mean that can_move_to() should return False on the position of the StaticBody obstacle if I understand correctly. But in the test example I did not manage to get it to work like that either :-/

**Comment by akien-mga** [comment]
So either I'm using the function wrong (which is possible as I have near to 0 experience with the 3D editor), or this call never finds collisions: https://github.com/godotengine/godot/blob/2c45ee5e1ce939bcef32129ac01944f3995269f4/scene/3d/physics_body.cpp#L1110

**Comment by akien-mga** [comment]
I managed to fix the issue of the discrete test not working with:
```
diff --git a/scene/3d/physics_body.cpp b/scene/3d/physics_body.cpp
index d61859a..2baed6d 100644
--- a/scene/3d/physics_body.cpp
+++ b/scene/3d/physics_body.cpp
@@ -1107,7 +1107,7 @@ bool KinematicBody::can_move_to(const Vector3& p_position, bool p_discrete) {
 		if (is_shape_set_as_trigger(i))
 			continue;
 
-		bool col = dss->intersect_shape(get_shape(i)->get_rid(), xform * get_shape_transform(i),0,NULL,0,exclude,get_layer_mask(),mask);
+		bool col = dss->intersect_shape(get_shape(i)->get_rid(), xform * get_shape_transform(i),0,NULL,1,exclude,get_layer_mask(),mask);
 		if (col)
 			return false;
 	}
diff --git a/servers/physics/space_sw.cpp b/servers/physics/space_sw.cpp
index ba1c737..4b59f2d 100644
--- a/servers/physics/space_sw.cpp
+++ b/servers/physics/space_sw.cpp
@@ -175,6 +175,10 @@ int PhysicsDirectSpaceStateSW::intersect_shape(const RID& p_shape, const Transfo
 		if (!CollisionSolverSW::solve_static(shape,p_xform,col_obj->get_shape(shape_idx),col_obj->get_transform() * col_obj->get_shape_transform(shape_idx), NULL,NULL,NULL,p_margin,0))
 			continue;
 
+		cc++;
+
+		if (!r_results)
+			continue;
 		r_results[cc].collider_id=col_obj->get_instance_id();
 		if (r_results[cc].collider_id!=0)
 			r_results[cc].collider=ObjectDB::get_instance(r_results[cc].collider_id);
@@ -183,8 +187,6 @@ int PhysicsDirectSpaceStateSW::intersect_shape(const RID& p_shape, const Transfo
 		r_results[cc].rid=col_obj->get_self();
 		r_results[cc].shape=shape_idx;
 
-		cc++;
-
 	}
 
 	return cc;
```
@reduz What do you think? I had to add a check on r_results in ```PhysicsDirectSpaceStateSW::intersect_shape``` since we call it with r_results=NULL but ask to give one result. Or would it be a better solution to call it with a non-null r_results even if we don't care about keeping track of the collision info?
