### ISSUE TITLE
How does PhysX becoming open source affect Godot?

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#24175]
So I was scrolling through my news feed when I saw that PhysX 4.0 is now out and it's Open Source.

If anyone doesn't know PhysX was Nvidia's proprietary Physics Engine that is found in lots of the big Games out there.
It has now been made Open Source and is licensed under BSD-3. With the caveat that on consoles like PS4, Xbox One and Nintendo Switch it still goes by the Nvidia EULA but I think as we don't officially support consoles so it shouldn't really matter.

I know that Godot currently uses Bullet and that it works fine but I really feel like it leaves a lot to be desired.

So my question is simple, can it be possible to add it to Godot as a default Physics Engine??
And if so should it be?
And what do you guys think about this topic in general??

**Comment by swarnimarun** [comment]
@reduz @akien-mga

**Comment by mafiesto4** [comment]
At this moment PhysX 4.0 is not out yet. Please pay more attention to what you read. PhysX 3.4 is now public and open-source.

**Comment by swarnimarun** [comment]
> At this moment PhysX 4.0 is not out yet. Please pay more attention to what you read. PhysX 3.4 is now public and open-source.

I know that but it's gonna be out by 20th Dec that is soon enough that it makes sense to call it already released, it's not a phone that you order and wait or wait to see a review. You can get it the day it's out. It doesn't make sense to say it's gonna be out in a week and I am waiting and all that nonsense.f

It's a thread titled about the PhysX becoming Open Source so please try to talk about the more relevant points.

**Comment by akien-mga** [comment]
Binding a physics engine is a lot of work, and Bullet seems to work fine, so why bother?

If there are strong benefits in using PhysX, it could be considered, but until then we don't have the aim to integrate all FOSS technology available under the sun. We only need what Godot games need.

**Comment by Xrayez** [comment]
If PhysX could support 2D physics natively as well, it would be worth to bind it...

**Comment by vnen** [comment]
It should work on all official platforms that Godot supports and be objectively better than Bullet. I don't think we should bind more than one physics engine, so it should replace Bullet if it's integrated. Otherwise the PhysX open source release doesn't affect Godot.

**Comment by swarnimarun** [comment]
Ok so after spending a couple hours on useless tests(got zero knowledge about Physics Engine testing), and reading the stuff about both Bullet and PhysX, it seems like PhysX has somewhat better performance and better GPU support and more accurate physics simulations.

I am not gonna give any prizes to PhysX but it's still an improvement. 

But from what I see in Godot there more of a lack of implementation of features from even Bullet library so probably it's better to just continue with Bullet and add more features like better Joints(Constraints) and Character Controllers, rather than wasting time on adding PhysX support.

**Comment by swarnimarun** [comment]
Closing it as seems like the question is answered as it won't and probably doesn't need to affect Godot in any way.

**Comment by NewNodeGames** [comment]
swarnimarun what Godot needs now is a good pathfinding system for enemy AI in 3D projects.
