### ISSUE TITLE
RichTextLabel discards BBCode text when update() is called (e.g. changing style properties or resizing window)

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#24173]
**Godot version:**

Godot 3.0.6 from the official site.

**OS/device including version:**

Windows 7

**Issue description:**

When you cause a redrawing of the text of a RichTextLabel, it will discard all changes made to the BBCode using append() and similar functions. And instead redraw using the BBCode text property data instead.

**Steps to reproduce:**
Create a RichTextLabel
Set a BBCode string, and enable BBCode parsing.
Make a script that calls clear(), then append_bbcode() some new text.
Change a property that would cause the text to be redrawn. This includes Font Colors, and Styleboxes. Either directly, or through a theme.

**Minimal reproduction project:**

[RichTextLabel.zip](https://github.com/godotengine/godot/files/2647797/RichTextLabel.zip)

**Video:**
https://streamable.com/r4btx

**Comment by girng** [comment]
```
extends Control

func _ready():
	$RichTextLabel.bbcode_text = "Hello World!"


func _on_Kill_pressed():
	$RichTextLabel.set("custom_colors/default_color", Color(1, 0, 0))


func _on_Reset_pressed():
	$RichTextLabel.set("custom_colors/default_color", null)
	$RichTextLabel.bbcode_text = "Hello World!"
```
![](https://i.gyazo.com/8c884170796b6e95f31305b3764baee3.gif)

should hold you over until a fix gets in for `append_bbcode`'s shenanigans
but yeah, append_bbcode is somehow triggering something, that makes the text reset to default when a style is changed.

**Comment by TheDuriel** [comment]
That will, unfortunately, be the solution i use. However this simply outsources the appending to a raw string i need to assemble beforehand. It also breaks the follow behavior of the RichTextLabel.

The += method does not work at all if i remember correctly. There was an issue about that.

**Comment by girng** [comment]
what do you mean "assemble beforehand"? are you building custom bbcode editor or something?

i did some more testing with `bbcode_text += "test"`

follow behavior still works for me, and the += does as well. i compiled a coupled days ago, you might need a new godot binary? not sure

**Comment by bojidar-bg** [comment]
Does this also happen on master?

**Comment by TheDuriel** [comment]
> Does this also happen on master?

As of alpha 2, yes this still happens.

**Comment by akien-mga** [comment]
See also #22203 which is likely another way to trigger this bug.
