### ISSUE TITLE
Area overlap not being detected at all (regression)

### ISSUE THREAD

**Issue by dbenoy** [godotengine/godot#24184]
**Godot version:**

89f8b84

**OS/device including version:**

Ubuntu 18.04
Radeon RX 560

**Issue description:**

Area.overlaps_area and Area.get_overlapping_areas do not see overlapping areas.

**Steps to reproduce:**
Place two overlapping areas in a scene, then call overlaps_area or get_overlapping_areas

The attached project works fine when imported into 3.0.6-stable and fails with 3.1-alpha2 and the current master.

**Minimal reproduction project:**
[area-overlap-failure.zip](https://github.com/godotengine/godot/files/2652123/area-overlap-failure.zip)

**Comment by dbenoy** [comment]
According to my testing, the regression started with 15305ec
@AndreaCatania

Testing further, I see that if I move one of the areas (which start out overlapping), it suddenly becomes detected.

[area-overlap-failure-2.zip](https://github.com/godotengine/godot/files/2656209/area-overlap-failure-2.zip)

**Comment by akien-mga** [comment]
Ping @AndreaCatania

**Comment by AndreaCatania** [comment]
Just tested and it works. Can you please try it with this: #26011

**Comment by akien-mga** [comment]
Assuming fixed by #26011. Please comment if you can still reproduce it.
