### ISSUE TITLE
CollisionShape2D Disabled Check Problem

### ISSUE THREAD

**Issue by cagdasc** [godotengine/godot#24183]
**Godot version:**

Godot master build

**OS/device including version:**

Ubuntu 18.04 / Radeon R7 250X

**Issue description:**

When I add CollisionShape2D(checked disabled feature) to RigidBody2D as a child, the RigidBody2D does not appear on play screen. If I uncheck CollisionShape2D disabled feature, it works correctly.

**Steps to reproduce:**
1. Create a new scene
2. Add RigidBody2D as a root
3. Add CollisionShape2D to RigidBody as a child
4. Check CollisionShape2D disabled feature
5. Play

**Comment by bojidar-bg** [comment]
Here is a sample reproduction project:
[24183-rigidbody-disabled.zip](https://github.com/godotengine/godot/files/2652606/24183-rigidbody-disabled.zip)

Note that it works just fine if you have no shapes, but disabled shapes seem to break things.
Additionally, made it log the transform every `_physics_process`, here are a few lines of the result:
```
Trasnform: ((1, 0), (-0, 1), (0, -100))
Trasnform: ((-nan, -nan), (nan, nan), (0, -99.972778))
Trasnform: ((-nan, -nan), (nan, nan), (0, -99.918381))
```
Changing the print to display the body's inertia shows `-nan`.

Probably, this code should check if a shape is disabled, and just not include it in inertia calculations:
https://github.com/godotengine/godot/blob/d403b4086c514647bba7620591061b7de7dfaf4b/servers/physics_2d/body_2d_sw.cpp#L60-L66

**Comment by duartencar** [comment]
I will take a look

**Comment by samdze** [comment]
Disabled CollisionShape2Ds seem to break the behaviour of a typical platform character controller with one way collisions too.
When passing through a one way collision shape, collisions with the disabled shape are somehow being reported.

**Comment by samdze** [comment]
The bug seems still present in case of a KinematicBody2D moved with `move_and_collide` in 3.1 beta 1.
