### ISSUE TITLE
Improve UX for editing non-script text files in the script editor

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#24187]
**Godot version:**
Master (a7bd9f0)

**OS/device including version:**
Any.

**Issue description:**
@Paulb23 added long-requested support for opening arbitrary text files in the script editor in #19225, and it works well.

The UX could be improved in several ways, though:
- File > Open in the script editor has the filter "All Recognized" which does not include non-Godot text extensions, so those files are not listed as valid targets. You can change the filter to "All Files (*)" to see them. IMO it's ok that the default excludes non-script text files as it would be difficult to whitelist all possible extensions (.txt, .log, .godot, .import, .cfg, .json, .yaml, etc.). But maybe we can at least rename the default filter to "All Script Formats" to make it clear that it only includes though.
- Non-script/resource text files are not shown in the FileSystem dock, so you can't double click them to open them in the text editor. So the only workflow to actually edit them is to use File > Open, change the default filter, and then select the file.

Ideas welcome on how to improve things, without introducing worse issues such as having the FileSystem dock cluttered with text-based `.import` files.

**Comment by akien-mga** [comment]
> But maybe we can at least rename the default filter to "All Script Formats" to make it clear that it only includes though.

Actually the current filter also includes resource formats (`.tres` and (!) `.res`, while it definitely can't open the latter). Might be worth reviewing the exact list of supported formats for this dialog (it also includes `.gdc` and `.gde` which are compiled IINM and likely not editable).

It could have more global filters:
- All Script Formats (.gd, .vs, [.cs], .gdns)
- All Resource Text Formats (.tres, .tres)
- Other Text Formats (.txt, .cfg, .json, .yaml)   // I wouldn't include stuff like .import, .log, or .godot which are unlikely to be edited from there
- All Files (*)

**Comment by QbieShay** [comment]
I'd let the users specify their whitelist, probably, as the user knows best what he wants to open with the script editor.

Whitelisting should also make those files appear in the file dock

**Comment by Paulb23** [comment]
Related to #21787

**Comment by aaronfranke** [comment]
Could the filter detect and allow opening all UTF-8 plain text documents that aren't on the blacklist? It'd be better than just a plain blacklist, since you don't want to try opening a binary file.

**Comment by carlixyz** [comment]
Could be included as custom script extensión “.esc” from escoria framework too?
There’re still crazies like me trying to do something with it. 😄

**Comment by uapaladin** [comment]
Just wanted to mention that it's not possible to open a textfile resource by rightclicking on it in the FileSystem tab (v 3.1.1 Windows). The Open menu item does nothing. Opening it via File/Open in the texteditor works, though.

Looks like a bug/oversight. Can it be fixed within this issue, or should I create a new?

**Comment by nicholasrobertm** [comment]
Just want to reiterate on the above, there are plenty of very good use-cases where you want to use something like a json / yaml / text file in a project. Things like storing data for loading at runtime,or something as simple as a readme for your project can be useful. Not being able to edit these in app makes godot (as an IDE) more obnoxious to use. Additionally to add to the above, json yaml and txt files aren't even showing in the project directory in godot itself, a good compromise might be a right click open option for text files that opens them in your system default text opener.

My current project use cases include:
A readme and changelog
Standardizing the game API to be modifiable via json file inclusions, this is to allow others to create add-ons to the game without touching the source code. With this the game has some default 'templates' that exist and are loaded in along with any user specified json templates.

**Comment by FroznMine** [comment]
Regarding the filesystem dock:
How about introducing a new button to the filesystem dock which toggles whether non-resource assets (*.txt, ...) are displayed. Godot internal files, like *.import, would still be hidden in this view which prevents unnecessary cluttering. I think the 'TextFile'-icon might be suitable for this. Here is a non-functional mock:
![asset_visibility_toggle_mock](https://user-images.githubusercontent.com/8106173/75995390-a3bc0800-5efc-11ea-9ed7-66fd41114a0a.png)

Another more advanced option could be using a menu button which allows toggling between e.g. the following three states:
* Only Resources (this is what the dock currently shows)
* Resources and Assets (includes non-resource assets like *.txt, *.json,..., but no internal files like the project file, *.import,...)
* All files

This could also be implemented in an extensible way such that the user can add custom filtering configurations which can be selected from the menu.

One remark independent of these ideas: I thought that the filtering of the files to display in the dock is done in the FileSystemDock class, which would have made it very easy to implement this filter toggling. However, the hidden files are already filtered while creating the representation of the file system in EditorFileSystem. Hence, displaying more files in the FileSystemDock will require modifications in EditorFileSystem. I currently do not know why the files are already filtered in this class, maybe some parts of the editor expect only Resources from there?! If this is not the case, I think moving the filtering over to the FileSystemDock as part of the UX improvement would be a good idea.

**Comment by nonunknown** [comment]
These days I was messing on gdas and found this: https://godotengine.org/asset-library/asset/423
