### ISSUE TITLE
Supported Linux CPU architectures

### ISSUE THREAD

**Issue by FedericoCeratto** [godotengine/godot#24190]
Hello,
I couldn't find an official list of supported CPU archs on Linux. Could you please clarify what I'm seeing?

Supported: amd64 arm64 armel armhf i386 ppc64el ppc64 

Not supported, leading to "Unsupported CPU" error message:
alpha hppa ia64 m68k mips mipsel riscv64 s390x sh4 sparc64 

Uncertain, failing to build: powerpc powerpcspe x32 

Logs from Debian buildbots: https://buildd.debian.org/status/package.php?p=godot

Thanks!

**Comment by akien-mga** [comment]
Officially supported arches are x86_64 (amd64) and ix86 (i386). We also aim to support armv7 (armhf) and arm64-v8 (arm64), and as far as I'm seeing for Mageia those build fine indeed (and should *run* fine, provided the devices running those have a GPU...).

We're not particularly interested in the other architectures which are not really relevant for game development as far as I know. If the engine (and especially its thirdparty dependencies) can be made to build there, it's fine for Debian to ship those for the sake of supporting all the things, but I doubt those will ever have any user.

**Comment by pkubaj** [comment]
With Raptor's Talos and Blackbird boards, amd64 finally got a competitor that's just as fast or faster (and more open). Thus could you consider supporting ppc64?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/988, as feature proposals are now tracked on the Godot proposals repository.
