### ISSUE TITLE
Huge performance regression with DRI_PRIME set

### ISSUE THREAD

**Issue by lupoDharkael** [godotengine/godot#24198]
**Godot version:**
Any after https://github.com/godotengine/godot/commit/0aad11a6a77d8ce3a8cf6096ad01cf25cb94553d

**OS/device including version:**
Fedora 28: Linux 4.19.5-200.fc28.x86_64
plasmashell 5.13.5 x11
OpenGL version string: 3.0 Mesa 18.0.5
VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller
Kernel driver in use: i915
VGA compatible controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev a1)
Subsystem: Acer Incorporated [ALI] GeForce 710M
Kernel driver in use: nouveau

**Issue description:**
I noticed a huge performance hit as my 3D project went from 60fps (limited by vsync) to 30fps. After a long session trying to find the cause (because I was using GDNative and I did a big refactor changing the bindings version to 1.1) I found it was a regression in Godot and not in my code.
After `git bisect` the cause of the problem seems to be https://github.com/godotengine/godot/commit/0aad11a6a77d8ce3a8cf6096ad01cf25cb94553d

**Comment by akien-mga** [comment]
I still think that it's not a good idea/unexpected from users that we set `DRI_PRIME=1` without telling them. As seen here it can result in actual worse performance if you have an old Nvidia GPU with bad support in nouveau, while Intel+Mesa keeps getting better on Linux all the time.

Linux users know that they can't expect the "applications decide what to use" behaviour that they experience on Windows, and they're used to setting their own `DRI_PRIME=1` or `optirun`/`primusrun` (for Bumblebee users of Optimus laptops) themselves.

**Comment by lupoDharkael** [comment]
We could use this as a reference if we take the route of runtime detection of the driver:
https://github.com/Bumblebee-Project/Bumblebee/blob/fb3d960fd8facbcfa58381701454c6853966a704/src/driver.c#L31

**Comment by hpvb** [comment]
Fixed on master
