### ISSUE TITLE
Shot a warning when working with inherited scene's children

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#24195]
**Godot version: 3.1.0 alpha 2**

**Issue description:**
Currently when you create an inherited scene you can't:

- Duplicate a child
- Rename a child

Although, imo, duplicating should be allowed, discussion open on #20802, but moving forward you can:

- Change the child index (position in the hyerarchy)
- Reparent the child
- Change the child type

All of this mess with the parent scene's logic brutally, not only imperative, i.e. in GDScript, but also declarative e.g. with animations. Since we already prevent some operations, I think that the above operations should definitely be prevented as well. Hmm, no not prevent them, but warn about the dangers of doing these operations from inside a Inherited Scene. I like the freedom of doing this, but it would be good to be warned about the dangers of doing so.

**Steps to reproduce:**

1. Create scene `A` with `B`, `C` and `D` as its children
2. Create `A1` as an `A` inherited scene
3. In `A1` reparent `C` to be `B`'s child
4. Rearrange `D` to be on index 0 and `B` to be on index 1 (or just move them around in the hierarchy)

**Comment by KoBeWi** [comment]
Changing types in inherited scenes is no longer allowed, the other issues are covered by #55789 and #23766
