### ISSUE TITLE
Editor is very laggy when "Low Processor Mode Sleep Usec" is different that default

### ISSUE THREAD

**Issue by shinyclaw** [godotengine/godot#24209]
When the value is different that default (for example 100000), after restaring the editor it is very laggy - even if "Low Processor Mode" is not checked.

![godot](https://user-images.githubusercontent.com/7187363/49637206-075b3b00-fa05-11e8-864b-dfecca10c909.png)

_Originally posted by @shinyclaw in https://github.com/godotengine/godot/issues/5332#issuecomment-445162773_

**Comment by Zylann** [comment]
I thought this delay was for the main loop when not rendering? If you set it to 100ms then yeah, it's going to be laggy.
