### ISSUE TITLE
Export dialog layout out of boundary.

### ISSUE THREAD

**Issue by qichunren** [godotengine/godot#24202]
**Godot version:**
ce3f3a9f82545b71a819c32e2c134a55d9d564f2　（Laster master）

**OS/device including version:**
Ubuntu 16.04 64bit

**Issue description:**
When select a template item in left list, right area layout out of boundary.

**Steps to reproduce:**
Client menu "Project" -> "Export" to open export dialog, and add a export template to test.

**Minimal reproduction project:**
None.

![export_layout](https://user-images.githubusercontent.com/39784/49624730-9e2bf580-fa0d-11e8-96e4-af9e039c9bef.png)

**Comment by Zylann** [comment]
It looks like the label showing errors at the bottom doesn't wrap, which means if the path + message is too long to fit the screen, the whole dialog will also be pushed to be larger than the screen.

**Comment by qichunren** [comment]
@Zylann Could you tell me how to make Label wrap? I use 'minimum_size_changed' to update Export Dialog size to fix this, is it right?

**Comment by qichunren** [comment]
@Zylann I set error label to autowap in export dialog according to your advice, layout still break in some case when dialog scaled. So `minimum_size_changed()` function need to update current dialog size when click a preset item. PR updated.

![fixed](https://user-images.githubusercontent.com/39784/49787094-b464e900-fd60-11e8-9e47-6d663a1a53f1.png)

**Comment by akien-mga** [comment]
Fixed by #24203.
