### ISSUE TITLE
Godot silently crash when assign Atlas Texture(and others) to itself

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#24213]
**Godot version:**
3.1 cca0ffe

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When I assign Atlas texture to itself, then Godot silently exit, but when I assign Proxy texture to itself then this error is shown:
```
ERROR: texture_set_proxy: Condition ' proxy == texture ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1563.
```
It happens with:
- Proxy Texture
- Atlas Texture
- Bitmap Font
- Tileset

In some situation I have also this message - Memory protection violation (memory dump)

**Steps to reproduce:**
1. Create new resource in file system panel
2. In Inspector load itself resource
3. See that editor crash

**Comment by akien-mga** [comment]
Can't reproduce it in the current master branch (6e600706e), assigning an AtlasTexture to a newly created AtlasTexture resource seems to work for me. Please comment if you can still reproduce it.

**Comment by qarmin** [comment]
It is still reproducable - https://streamable.com/cw96m

**Comment by akien-mga** [comment]
Ah, I thought you meant assigning using `New > AtlasTexture` on the newly created `AtlasTexture`.

Assigning the resource to itself will indeed mean recursive inclusion, so it should be prevented and throw an error.
