### ISSUE TITLE
Document new "infinite_inertia" parameter in KinematicBody/KinematicBody2D APIs

### ISSUE THREAD

**Issue by letsgamedev** [godotengine/godot#24229]
**Godot version:**
Nightly Alpha Build December 3. 2018

**OS/device including version:**
MacOS 10.14.1

**Issue description:**
I want to shoot a stone (KinematicBody2D) and it should stop on a collision detection. So I use 
var coll = self.move_and_collide(direction * speed * delta)
If coll is not null a collision is detected and I change the speed of the stone to 0.
This detections works well for StaticBody and KinematicBody but not for RigidBody.

The stone interacts with the RigidBody, pushing it around and so on but move_and_collide returns no Collision Object at all.

**Minimal reproduction project:**
[body_no_stop.zip](https://github.com/godotengine/godot/files/2659863/body_no_stop.zip)

**Comment by bojidar-bg** [comment]
Can confirm using the given example.

Seems like a regression from 3.0.6, as it works fine there.

**Comment by bojidar-bg** [comment]
Bisected:
```
git bisect start **{physic,object,collision}*.{cpp,h}
# good: [9bd402698cfa299b79b9144f8d7744c308a4e085] Bump version to 3.0-stable \o/
git bisect good 9bd402698cfa299b79b9144f8d7744c308a4e085
# bad: [9a8569d434107e721f5c7de0bf8ffe6471367d28] Merge pull request #24155 from akien-mga/scons-msvc-bits
git bisect bad 9a8569d434107e721f5c7de0bf8ffe6471367d28
# bad: [0010d9c82a89e89fc1bc83e806f59f34f3deb893] Added ray shape and move_and_slide with snapping on 3D. Added stop_on_slope on 2d part
git bisect bad 0010d9c82a89e89fc1bc83e806f59f34f3deb893
# bad: [dfd1331690fab7e634e2e18fd7269bab8f759b3a] Allow editing of some unbound properties when hinted (or no range hinted)
git bisect bad dfd1331690fab7e634e2e18fd7269bab8f759b3a
# bad: [e5ae9750ed011c545cf2c002159f5095a9592e7c] Fixed leak in BulletPhysicsServer
git bisect bad e5ae9750ed011c545cf2c002159f5095a9592e7c
# good: [a5688ccd90573b1700e06417b94c0c46ce5a2e9a] Improve CollisionObject/CollisionObject2D warning message
git bisect good a5688ccd90573b1700e06417b94c0c46ce5a2e9a
# bad: [39fb83630dff7b6f6c3544dcc9ed70ed459aaf43] Added forgotten infinite_inertia to bindings
git bisect bad 39fb83630dff7b6f6c3544dcc9ed70ed459aaf43
# good: [b2aeb02e7d43d98973334e39db5c39626ba9f775] Merge pull request #16530 from AndreaCatania/rays
git bisect good b2aeb02e7d43d98973334e39db5c39626ba9f775
# bad: [497a4e9e25fb8cc9d3a95bc79b605aca79603648] Merge pull request #16757 from AndreaCatania/kinpush
git bisect bad 497a4e9e25fb8cc9d3a95bc79b605aca79603648
# bad: [6ed392f47a1970f7815f6f76b7bacfd0bb51b87c] Improved kinematic body 2D and 3D, Now can move rigid body
git bisect bad 6ed392f47a1970f7815f6f76b7bacfd0bb51b87c
# first bad commit: [6ed392f47a1970f7815f6f76b7bacfd0bb51b87c] Improved kinematic body 2D and 3D, Now can move rigid body
```

Seems like it is a feature introduced with #16757. Maybe it should be optional? CC @AndreaCatania

**Comment by mrcdk** [comment]
You need to set the function parameter `inifite_inertia` to `false`

**Comment by nazgum** [comment]
> You need to set the function parameter `inifite_inertia` to `false`

sweet thank you! =)

**Comment by akien-mga** [comment]
Changed title accordingly.

**Comment by austinried** [comment]
What if I wanted to have the player (KinematicBody2D) push the enemies (RigidBody2D) around, but I also want to have collision info returned by `move_and_collide` so I can act on it in some way?  Is that not supported currently?
