### ISSUE TITLE
Progressive JPEG loading does not work

### ISSUE THREAD

**Issue by BBric** [godotengine/godot#2423]
In Gimp on Linux, when 'progressive' is checked (default value) in the export dialog's advanced options, `load("..jpg")` returns a null object.

**Comment by reduz** [comment]
the jpg library I'm using is kind of shitty, always wanted to replace it
but don't know any better

**Comment by seadra** [comment]
[libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo)?

**Comment by akien-mga** [comment]
Assuming fixed by e8fbf39.
