### ISSUE TITLE
Orphan .import files should be cleaned up

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24233]
Godot 3.0.6

I deleted some textures from the system explorer, thinking that Godot would cleanup their .import files like Unity does. Turns out it doesn't do it. I think it would help if Godot could do this, along with cleaning up the associated data in the `.import` folder.

**Comment by girng** [comment]
related to https://github.com/godotengine/godot/issues/18314 and https://github.com/godotengine/godot/issues/17733

**Comment by Calinou** [comment]
Duplicate of #17733.
