### ISSUE TITLE
Default font size of DynamicFont

### ISSUE THREAD

**Issue by ComanderKai77** [godotengine/godot#24239]
Godot version: 3.0.6 stable
OS: Windows 10 64bit

Improvement:
Set the default font size of a DynamicFont to something greater than zero.
In my opinion it is counterintuitive that you have to change the size first to see the font / text.
The default font size should be something like 15 - 20.

![Default font size](https://user-images.githubusercontent.com/10358137/49696889-00712b80-fbb1-11e8-82c2-2497ff8ecedf.PNG)

Steps to reproduce:
Add a Label to a scene.
Go to Custom Fonts and add a DynamicFont.
The default size is zero.

Expected behavior:
The size should be greater than zero.

**Comment by akien-mga** [comment]
Please edit your issue/write a comment explaining why you're closing it, otherwise there's no way we can know if this was relevant or not.

In this case it was a valid bug report, but it's fixed already by c399c41 in the master branch (#21165).

**Comment by ComanderKai77** [comment]
I forget to check wether is has been fixed already. But as you wrote, it already have been fixed.
