### ISSUE TITLE
Export  C# Project error

### ISSUE THREAD

**Issue by JohnSilverLong** [godotengine/godot#24234]
I'm using windows 7 godot version (3.1?) latest commit 5b8dde4b4a5a930e08da51e07ec87f43e5bd7b36

Despite succesfully installing the 3.1,alpha.mono template an unhandled exception is thrown when an export is started:

```
Unhandled Exception:
System.IO.FileNotFoundException: Data template directory not found
  at GodotSharpTools.Editor.GodotSharpExport._ExportBegin (System.String[] features, System.Boolean debug, System.String path, System.Int32 flags) [0x000c3] in
<71727b6fa85b499a9997012645bf816c>:0
ERROR: GodotSharpExport::_export_begin: Method/Function Failed.
   At: modules\mono\editor\godotsharp_export.cpp:161

```
Same problem goes for any project running in the editor, even bare minimum. Result of the export is an executable and a .pck file that fails to run because of a missing file: `L:\GodotExports\TestExport/data_Godot/Mono/lib\mono\4.5\mscorlib.dll`. At least from this error message it's clear what to look for and confirm the file is not there. So it seems i'm now stuck on the exception.

**Comment by neikeq** [comment]
This is explained in the docs: http://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html

SCons should have created a folder `data.mono.<platform>.<bits>.<target>`, e.g.: `data.mono.windows.64.release`. You must place this folder in the templates directory together with the Godot executable.

**Comment by JohnSilverLong** [comment]
Thanks for your reply, it did help me get further rebuilding the editor step by step from scratch and copy the data template folder into the templates directory. Now it does find the data template directory and finish exporting without errors. But when I export a simple scene with only cube, camera and a C# script the result .exe crashes upon running.

The build folder now contains:
- data_TestExport
- TestExport.exe
- TestExport.pck


Inside the editor log.txt after build some warning/error but seems unrelated to the export process so probably fine.

```
OpenGL ES 3.0 Renderer: Quadro K2200/PCIe/SSE2
**WARNING**: ObjectDB Instances still exist!
   At: core\object.cpp:2081:ObjectDB::cleanup() - ObjectDB Instances still exist!
**ERROR**: There are still MemoryPool allocs in use at exit!
   At: core\dvector.cpp:70:MemoryPool::cleanup() - Condition ' allocs_used > 0 ' is true.
 
``` 

Inside the exported project log.txt after running exe:

```
**ERROR**: The loaded API assembly is invalid
   At: modules/mono/mono_gd/gd_mono.cpp:307:initialize() - The loaded API assembly is invalid
**ERROR**: FATAL: Method/Function Failed.
   At: modules/mono/mono_gd/gd_mono.cpp:308:initialize() - FATAL: Method/Function Failed.
   
```

Inside the mono_logs.txt after running the exe:
Mono version 5.16.0.179

```
Config attempting to parse: 'L:\GodotExports\TestExport/data_TestExport/Mono/etc\mono\config'. (in domain Mono, info)
Image addref mscorlib[000000000A247830] -> .mono/assemblies/mscorlib.dll[000000000A37DF50]: 2 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (.mono/assemblies/mscorlib.dll) (in domain Mono, info)
AOT: image '.mono/assemblies/mscorlib.dll.dll' not found: Het systeem kan het opgegeven pad niet vinden.
 (in domain Mono, info)
AOT: image 'L:\GodotExports\TestExport/data_TestExport/Mono/lib/mono/aot-cache/amd64/mscorlib.dll.dll' not found: Het systeem kan het opgegeven pad niet vinden.
 (in domain Mono, info)
Assembly mscorlib[000000000A247830] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly mscorlib[000000000A247830] added to domain GodotEngine.ScriptsDomain, ref_count=2 (in domain Mono, info)
Image addref GodotSharp[000000000A247EF0] -> .mono/assemblies/GodotSharp.dll[000000000A42C520]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotSharp' (.mono/assemblies/GodotSharp.dll) (in domain Mono, info)
Assembly GodotSharp[000000000A247EF0] added to domain GodotEngine.ScriptsDomain, ref_count=1 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Config attempting to parse: ''. (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly Ref addref GodotSharp[000000000A247EF0] -> mscorlib[000000000A247830]: 3 (in domain Mono, info)

```

The reference to mscorlib.dll.dll seems a bit suspicious. Mixing the forward and backward slashes looks odd but is actually valid. And here i'm stuck again.

**Comment by Chaosus** [comment]
> Now it runs without issues

Glad, that its solved, and explained by @neikeq. Usage of nightly Godot builds for Mono is still struggling enough but much less than before..
