### ISSUE TITLE
Many class/struct member variables can be moved to initializer list

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#24242]
**Godot version:**

master branch commit 41d1dba35fc851258d5aabad819d09f6a43e324c

**Issue description:**

There are many class/struct member variables that can be moved to an initializer to avoid creating objects twice.

The performance enhancement of doing this is negligible for primitive types and for compilers that already do this optimization by default (like GCC), but a performance improvement might be noticeable on compilers that do not do this since on some cases, generally speaking, creating non-primitive objects twice could hurt performance.  

[Here's a list of the member variables that can be moved.](https://github.com/godotengine/godot/files/2660718/member_variables_that_can_be_moved.txt) This file does not include the variables I moved in #24241. It's an easy patch for anyone who'd like to contribute.

**Steps to reproduce:**
To generate attached list in linux you must have `cppcheck` installed. Then:
- cd $godot_repo
- cppcheck --enable=performance --std=posix . 2> performance_check.txt
- fgrep 'initialization list' performance_check.txt | fgrep -v '[thirdparty/'

**Comment by Cartogy** [comment]
I'd like to try this.

**Comment by Calinou** [comment]
@Cartogy Since there's refactoring going on in the `master` branch, I'd wait until it's more stable.

**Comment by Cartogy** [comment]
Understood. I will keep my eye on its progress.

**Comment by Rubonnek** [comment]
Closing in favor tracking this issue in:
- #43636
