### ISSUE TITLE
A way to block the nodes in the editor so that it is no longer possible to edit them (or edit them unintentionally, in my case)

### ISSUE THREAD

**Issue by JulioYagami** [godotengine/godot#24248]
I don't know if here is the best place to this. I have a tilemap in a project which I get quite a few clicks unintentionally, so with these clicks, I end up making some mess in it. It doesn't happens only for tilemaps, but for everyone Node2D.

**Comment by LikeLakers2** [comment]
There's already a way to do that. Select the node you want to do this with, then on the bar just below the scene tabs, click the lock icon. If you need a little help finding the lock icon, I've circled it here for you:
![image](https://user-images.githubusercontent.com/1008889/49704382-3d084b80-fbe0-11e8-9a0c-5d502ba8eaa5.png)

Locking the node prevents them from being selected in the scene view, but you can still select them by clicking on them in the scene tree.

Note that this only locks the node that you selected. If you want to lock all children nodes, click the icon just to the right of the lock icon.

**Comment by JulioYagami** [comment]
I really had not noticed that, thank you very much.

**Comment by DigitalMonkeyPa1** [comment]
@JulioYagami 
I think your problem is solved, then you can close this issue so that it's easy to focus on other unsolved issues.
