### ISSUE TITLE
Manipulate frame index of AnimatedSprite wont work

### ISSUE THREAD

**Issue by letsgamedev** [godotengine/godot#24243]
**Godot version:**
Nightly Build December 9th 2018

**OS/device including version:**
MacOS 10.14.1

**Issue description:**
This bug occurs not in the godot version you can download at
https://downloads.tuxfamily.org/godotengine/3.1/alpha1/

When a looping animation (AnimatedSprite) ends the animations finished callback is fired.
There I want to set the frame index from 0 to 2 but this is ignored by the engine.
You can print out the frame index and it will be 2, but in the next tick its 0.

**Steps to reproduce:**
Start my attached Project

**Minimal reproduction project:**
[animation_bug.zip](https://github.com/godotengine/godot/files/2660851/animation_bug.zip)

**Comment by akien-mga** [comment]
CC @groud and @zer0problem (who both changed the `animation_finished` logic recently.

**Comment by zer0problem** [comment]
I see the problem, it appears that the frame is set after the animation_finished signal is fired when the animation is looping.

**Comment by groud** [comment]
I am not sure about the problem here. When looping, the animation_finished signal is fired at the end of the loop. When it's not looping, the signal firing to early problem was fixed on master. 

I don't understand the other problem.

**Comment by letsgamedev** [comment]
This is the wanted frame order: 
0 1 2 3 4 2 3 4 2 3 4 2 3 4
so from the second loop frame 0 and 1 are skipped.
That worked on older Godot 3.1 Versions but not at the current nightly build.

**Comment by akien-mga** [comment]
What's the status on this issue?
