### ISSUE TITLE
Resizing an image with format RH or RF produces unwanted artifacts

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24244]
Godot 3.0.6

If I resize an image with the RF or RH formats to be smaller or bigger, I get unexpected dark lines, which doesn't happen with 8-bit formats. I am using this in my terrain plugin, and the result is very noticeable: https://github.com/Zylann/godot_heightmap_native_plugin/issues/38

Here with a simple resized gradient (click to see full size):
![image](https://user-images.githubusercontent.com/1311555/49701201-3af2bc80-fbe1-11e8-9f8c-c9cbb07777c9.png)

Example project:
[ImageResizing.zip](https://github.com/godotengine/godot/files/2660868/ImageResizing.zip)

**Comment by Zylann** [comment]
Actually, this doesn't reproduce in Godot 3.1 alpha2.
Maybe has been fixed by https://github.com/godotengine/godot/commit/3fd2fc1e0159e480df6c1f01eea89a66ec89e67b

**Comment by akien-mga** [comment]
Thanks, closing as fixed then. I don't think that we'll attempt to backport 3fd2fc1 however though, unless it's strongly needed.
