### ISSUE TITLE
Key echo events cause stuttering for mouse motion events

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#24245]
**Godot version:**

c9550b800aed10451273143958dfff461105d45b

**OS/device including version:**

Ubuntu 18.10

**Issue description:**

For a first person controller, code is being called to rotate the camera under `_input`; however, if any key is being held--whether it's tied to any action, event or not--these calls will stutter, as if `_input` is not being called every process frame.  This ultimately causes mouse look to stutter.

**Steps to reproduce:**
Using the following:
```
func _input(event):
	if event is InputEventMouseMotion:
		var mouseMotion: Vector2 = event.relative * lookSpeed
		targetLook.x += mouseMotion.x
		targetLook.y = clamp(targetLook.y + mouseMotion.y, -maxY, maxY)
		var curQuat = Quat(cam.global_transform.basis)
		var horQuat = Quat(Vector3.DOWN, targetLook.x)
		var verQuat = Quat(Vector3.LEFT, targetLook.y)
		curQuat = horQuat * verQuat
		cam.global_transform.basis = Basis(curQuat)
```
Observe how smoothly the camera moves without touching any keys.  Then, hold down any key on the keyboard, and observe how it hitches, and how it seems to take more mouse movement to make up for the difference compared to the previous state.

**Minimal reproduction project:**

[FPHitch.zip](https://github.com/godotengine/godot/files/2660909/FPHitch.zip)

**Comment by substract** [comment]
Hello!
I have noticed something similar:
Mouse slowdown and stutter even without holding down a button in Godot 3.1 alpha 3.

It happens using the scene of this FPS controler tutorial :
[fps tutorial](https://youtu.be/Etpq-d5af6M)

Tutorial Scene download:
[tutorial scene](https://github.com/turtletooth/GodotFirstPersonController)

The scene works correct in Godot 3.0 but you will notice a big mouse sensitivity reduction in 3.1
The Player character has a mouse sensitivity value but increasing it will expose the mouse stutter!

**Comment by akien-mga** [comment]
It seems to work the same with and without held key for me in the current master branch / latest 3.2 build on Linux. Can you check if you can still reproduce it?

**Comment by akien-mga** [comment]
Assuming fixed for now, please comment if you can still reproduce it.
