### ISSUE TITLE
Error Condition ' blocked > 0 ' is true - everytime when I click at the searched element in "Search Help"

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#24254]
**Godot version:**
3.1 bf59b732

**OS/device including version:**
Windows 10

**Issue description:**
When I try to find some class in Search Help window(is visible at the top of Script Editor) and then click at some element then this error appear:
```
ERROR: clear: Condition ' blocked > 0 ' is true.
   At: scene/gui/tree.cpp:3113
```

**Steps to reproduce:**
1. Search something in Script Editor
2. Click at some search result

https://streamable.com/as98n

**Comment by akien-mga** [comment]
CC @YeldhamDev
