### ISSUE TITLE
Indent guides not rendering correctly

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#24250]
**Godot version:**

bf59b73250b0d8e0edf191104246da50bdf16541

**OS/device including version:**

Arch Linux | AMD CAPE VERDE (DRM 2.50.0, 4.19.4-arch1-1-ARCH, LLVM 7.0.0) 

**Issue description:**

![image](https://user-images.githubusercontent.com/28724859/49716011-fa626580-fc17-11e8-9648-9940a903db36.png)

They'll break apart in different places as you scroll as well

**Comment by avencherus** [comment]
Did a build recently of 5ff403b, and noticed it too.
