### ISSUE TITLE
Exporting pck file from command line with --quit or --disable-render-loop or from a server build hangs on thumbnail generation

### ISSUE THREAD

**Issue by sdfgeoff** [godotengine/godot#24263]
**Godot version:**
Latest Master

**OS/device including version:**
Problem observed both on Archlinux and Debian, but is more a design issue/limitation, so will appear everywhere.

**Issue description:**
When running the command:
`godot  --path path/to/game --export "pck" test.pck`
Godot will freeze - but only if you've never opened the project before. If you have opened the project in the Godot editor, then it exports successfully.  If you have opened it in the editor, you can force it to happen by deleting the thumbnails from `.cache/godot`.

This problem is because the server build does not draw the display, and the thumbnailer waits for a draw to happen. As a result, it gets stuck in this loop (which is present in a couple of preview generators in `editor_preview_plugins.cpp`):

```
        preview_done = false;
	VS::get_singleton()->request_frame_drawn_callback(const_cast<EditorFontPreviewPlugin *>(this), "_preview_done", Variant());

	while (!preview_done) {
		OS::get_singleton()->delay_usec(10);
	}
```

**Minimal reproduction project:**
Any project will exhibit this, so long as you remove the thumbnail cache first.

Currently this is preventing automated-export of projects from a headless environment.

**Comment by sdfgeoff** [comment]
Here is an example project.
[texture-server-export-fail.zip](https://github.com/godotengine/godot/files/2675952/texture-server-export-fail.zip)

Do not open with the godot editor, because then it will work. If you do, you should delete `~/.cache/godot` to re-experience the bug.

Instead, inside there are four shell scripts:
```
godot --path $(dirname "$0") --export "pck" test1.pck --disable-render-loop
godot --path $(dirname "$0") --quit --export "pck" test2.pck
godot --path $(dirname "$0") --export "pck" test3.pck
godot-server --path $(dirname "$0") --export "pck" test4.pck -q
```
All of these leave godot frozen.

**Comment by QbieShay** [comment]
Seems like it does not segfault before 9cb18232c290c1876cdb6570ef11f29fa7a98ce3

**Comment by akien-mga** [comment]
Seems fixed in the current master branch, probably because @reduz fixed various issues with preview generation the past two weeks.

**Comment by sdfgeoff** [comment]
Tested today. Seems fixed to me
