### ISSUE TITLE
Can't do Gradlew Build. Probably Gradle version? errors in Android manifest? or on Java?

### ISSUE THREAD

**Issue by Blackwinter258** [godotengine/godot#24279]
D:\Arcanium\Godot\godot215ssc>scons platform=android target=release_debug
scons: Reading SConscript files ...

MSVC not detected, attempting Mingw.
- could not detect gcc.
Please, make sure a path to a Mingw /bin directory is accessible into the environment PATH.

Godot Android!!!!! (armv7) (with neon)
Using NDK unified headers
scons: done reading SConscript files.
scons: Building targets ...
[ 97%] Linking Shared Library ==> bin\libgodot.android.opt.debug.armv7.neon.so
[100%] progress_finish(["progress_finish"], [])
[100%] scons: done building targets.

D:\Arcanium\Godot\godot215ssc>cd platform

D:\Arcanium\Godot\godot215ssc\platform>cd android/java

D:\Arcanium\Godot\godot215ssc\platform\android\java>gradlew build

> Configure project :
The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
[Fatal Error] :32:6: The processing instruction target matching "[xX][mM][lL]" is not allowed.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java'.
> Exception while parsing the supplied manifest file D:\Arcanium\Godot\godot215ssc\platform\android\java\AndroidManifest.xml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by akien-mga** [comment]
The issue template asked for your Godot version and OS, please fill this information. It can be guessed by a clever reader, but shouldn't have to be.

Also, what is your NDK version?

**Comment by Blackwinter258** [comment]
Uhmm.. Its android-ndk-r18b..  Still searching about the godot version and OS

**Comment by Calinou** [comment]
I'll have to close this issue as it's about a third-party module. We don't provide support for third-party modules here; please ask the module developer instead.
