### ISSUE TITLE
get Autotile coordinates(out of tile in TileMap)

### ISSUE THREAD

**Issue by Lodugh** [godotengine/godot#24273]
Right now you can already set the Autotile coordinates with set_cell() however I could really make use of a way to read them out of a tile in a TileMap. Something like get_autotile(tile_index).
I would want to use that to transfer tiles from one TileMap to another.
I would be very glad if someone could add this!
Thanks a lot for taking notice.

**Comment by bojidar-bg** [comment]
Something like `Vector2 TileMap::get_cell_autotile(int x, int y)` might be good.
Additionally, adding `Vector2 autotile_coord` to `set_cellv` similar to `set_cell`'s would be nice.
