### ISSUE TITLE
HTML 5 export HttpRequest Blocking mode

### ISSUE THREAD

**Issue by rojekabc** [godotengine/godot#24276]
**Godot version:**
3.0.6 stable.official

**Issue description:**
I'm using HttpRequest node. This node internally uses HttpClient.
When I export my project and try to use it, I receive:
'
**ERROR**: HTTPClient blocking mode is not supported for the HTML5 platform
**ERROR**:    At: platform/javascript/http_client_javascript.cpp:205:set_blocking_mode() - Condition ' p_enable ' is true.
'
I see in documentation, that HttpClient allows to enable/disable blocking mode. Could you export some flag to HttpRequest or reference to HttpClient, which allows to manage this flag from HttpRequest level?

**Steps to reproduce:**
Create node HttpRequest, call the request. Export project to HTML5.

**Comment by rojekabc** [comment]
I've tried to get connection via HttpClient and I hit STATUS_CONNECTION_ERROR after STATUS_REQUESTING. For now, I cannot figure out where the problem is.

**Comment by akien-mga** [comment]
CC @eska014 @Faless

**Comment by rojekabc** [comment]
OK. Problem is solved. I found, that this useThreads flag automatically enables also blocking_mode. In this case it's not possible to run on HTML-5. Please, append this relation to your documentation.

**Comment by eska014** [comment]
Fixed by godotengine/godot-docs#2155
