### ISSUE TITLE
Label rect_position is not effected by its rect_pivot_offset

### ISSUE THREAD

**Issue by qichunren** [godotengine/godot#24275]
**Godot version:**
Godot 3.1 alpha2 and 3.0.6

**OS/device including version:**

Windows 10 64 bit.

**Issue description:**
I add a Label to scene, and set its rect_pivot_offset to its content center point. When I set Label rect_position to Vectory(0, 0), it should be placed to Vectory(0,0) with its anchor point, but it is placed with its left top corner to Vect2(0,0)

![image](https://user-images.githubusercontent.com/39784/49773192-0b4fcb80-fd2b-11e8-9001-807efd5ee895.png)

**Steps to reproduce:**

```
func _ready():
	$Label.rect_pivot_offset = $Label.rect_size / 2
	$Label.rect_position = Vector2()
```

**Minimal reproduction project:**
None.

If I misunderstand Label rect_position property, how to place Label to scene by its anchor point, just like Sprite did.

**Comment by mrcdk** [comment]
This is intended. `rect_pivot_offset` is only used for scale and rotation, `rect_position` will always be the position of top-left corner of the control.

https://docs.godotengine.org/en/latest/classes/class_control.html#class-control-rect-position

**Comment by girng** [comment]
you should be able to just offset the rect_position with the pivot's x and y

**Comment by qichunren** [comment]
OK, thank you.
