### ISSUE TITLE
Android export breaks string resources in resources.arsc

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#24289]
**Godot version:**

3.1-dev @ 3f9c05416

**OS/device including version:**

Linux Mint 19 exporting to Android (also tested in other Linux distros)

**Issue description:**

When exporting to Android, the strings in `resources.arsc` seems to be corrupted. The actual data seems to change from each time we export but sometimes it gets rejected by the Play Store:

![error-apk-upload](https://user-images.githubusercontent.com/5599796/49826331-d9138d80-fd6d-11e8-86d9-fdb9558b4c31.png)

Analyzing the APK with `aapt dump --values resources` I can see that the one of the translations contain a `^M` character (which is a new line):

![unicode-error-export](https://user-images.githubusercontent.com/5599796/49826368-ed578a80-fd6d-11e8-8be9-984611b70291.png)

The template reports the strings correctly.

It seem the function to [`_fix_resources()`](https://github.com/godotengine/godot/blob/37e198c32006d18c9443bf65963ba8182b7d76a6/platform/android/export/export.cpp#L1002) incorrectly parses the strings and rewrite them with weird characters.

Maybe it needs some updating like @hpvb did for the manifest.

**Steps to reproduce:**
Export a project to Android.
In particular we are using some modules with Google Play Services which are adding the offending string.

**Minimal reproduction project:**
Happens with any project.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

**Comment by vnen** [comment]
Might be tricky to reproduce this since it was an issue in a module, but now both the module and the export workflow changed.

If the code to `_fix_resources()` isn't used anymore then this is fixed. Otherwise it's likely still broken.

**Comment by m4gr3d** [comment]
While `_fix_resources()` is still used for legacy purposes, the recommend export format (and enforced starting mid 2021) is `Android App Bundle` which uses a different export logic, thus resolving this issue.
