### ISSUE TITLE
Code completion does not show function and members from inherited script

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#24284]
**Godot version:**
3.0.x and 3.1 alpha 2

**OS/device including version:**

**Issue description:**

if I have one script file named MyNode.gd extends from Node and another one named NewNode.gd extends from MyNode.gd, all functions and members of  Node  will  not be available for code  auto complete in NewNode.gd.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
I'm pretty sure we have one or more issues about the same topic, but can't find them again so keeping this one for now :)

CC @vnen.

**Comment by akien-mga** [comment]
Related: #20902

**Comment by HolonProduction** [comment]
Not reproducible in v3.6.stable.official [de2f0f147], closing as fixed
