### ISSUE TITLE
Loss of export variable when a script does not compile and then compiles again

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24280]
**Godot version:**
b7320bc02ff6753cab

**OS/device including version:**
4.19.4-arch1-1-ARCH

**Issue description:**

When editing a script with export variables, failure in compilation leads to export variables to be lost

**Conditions:**

- Script has export variables
- Scene that uses the script is open and "focused" (current selected tab)
- Script compiles

**Steps to reproduce:**

1. Open the reproduction project
2. Open the scene "main"
3. Open the script "Node2D.gd"
4. Uncomment the broken line
5. Save (SCRIPT ONLY)
6. Comment the broken line again, so that the script compiles
-> Export variable becomes null

**Minimal reproduction project:**
[LoseExport.zip](https://github.com/godotengine/godot/files/2667454/LoseExport.zip)

**Comment by somnivore** [comment]
Now that it's mentioned, I have noticed recently that my scenes are losing their exported values at regular intervals.  I can confirm that this is happening.

**Comment by akien-mga** [comment]
I've seen this too a lot on a project I use to try to reproduce bug reports, where script compilation failure often end up in my main scene losing its PackedScene export var (thus breaking the game).

**Comment by QbieShay** [comment]
I think this might be the actual cause of #23418

**Comment by N0hbdy** [comment]
I think that this was introduced in #23639 (via bisecting + fixing); I've put up a potential PR in #24707 that seems to fix the issue.
