### ISSUE TITLE
c # godot does not play main scene.////////////c# godot no reproduce escena principal.

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#24281]
**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**
They simply play and do not play, either with glsl2

**Minimal reproduction project:**

hello

**Comment by akien-mga** [comment]
I know English is difficult for you, but you should still make *some* effort to fill in the export template. Google Translate can translate it almost perfectly in Spanish.

This report has 0 details about what issue you're having, we can only assume that it's an error in your own project. But without steps to reproduce not minimal reproduction project, and even worse without information about what is the Godot version and OS used, we can't help you.
