### ISSUE TITLE
CurveTexture doesn't work on some Android devices

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#24295]
**Godot version:**
3.0, 3.1

**OS/device including version:**
Sony F3311 (Mali-T720) and ASUS Z010D (Adreno 306) and many others.

**Issue description:**
When using CurveTexture, it gets rendered as black on many Android devices.

This issue was created after PR #15774 was closed - there are more details there.

**Comment by akien-mga** [comment]
Suggested fix from @reduz in https://github.com/godotengine/godot/pull/15774#issuecomment-366939216

**Comment by akien-mga** [comment]
Fixed by #24575.
