### ISSUE TITLE
Shaking angle of view in 3D scene, model with ghosts 

### ISSUE THREAD

**Issue by haizhou37** [godotengine/godot#24297]
**Godot version:**
godot3.1 alpha3

**OS/device including version:**
manjaro gnome x64
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile
intel hd 3000

**Issue description:**
The ground model（a built-in box model in the meshinstance） has ghosts when shaking angle of view  in this scene.
Also, the ghosts  appears to have a collision volume that controls the character to move over it until it disappears and does not fall.
I tried to take a screenshot, but the picture was normal.
The following pictures show some differences from the actual effect：
![peek 2018-12-12 18-02](https://user-images.githubusercontent.com/33272474/49862496-42140780-fe39-11e8-976e-14a431cc3279.gif)
![2018-12-12 18-05-36](https://user-images.githubusercontent.com/33272474/49862508-4809e880-fe39-11e8-87c3-f9ebdf63f774.png)

**Steps to reproduce:**
Create a 3D scene, place the model, and then shaking the angle of view

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2671495/Test.zip)

**Comment by AndreaCatania** [comment]
The RigidBody is not meant to be rotated / moved manually. You should control its position with forces. Check the documentation to get more info about it

**Comment by haizhou37** [comment]
> The RigidBody is not meant to be rotated / moved manually. You should control its position with forces. Check the documentation to get more info about it

Although I would like to use torque and force to achieve role steering and movement, but they are currently unable to achieve direction control based on their own axes(Not similar to add torque or force on local )
