### ISSUE TITLE
Mono: Mac exporter includes both release & debug data folders

### ISSUE THREAD

**Issue by exts** [godotengine/godot#24299]
**Godot version:**
3.1 Alpha 3

**OS/device including version:**
Windows 10

**Issue description:**
When exporting for osx the export logs has the following:

![image](https://user-images.githubusercontent.com/16387107/49872260-2891a200-fdde-11e8-8d06-14430f28e3c1.png)

When I checked the actual zip it contains both export template's data folders

![image](https://user-images.githubusercontent.com/16387107/49872291-43641680-fdde-11e8-9292-171d9da7f026.png)

**Steps to reproduce:**

- Export for osx
- (optional add *.json to included exported filter settings, doubt this matters but that's what my setup has)
- Export with debugging off

**Comment by neikeq** [comment]
I'm not familiar with how the OSX export templates work. Why are we including both the `release` and `release_debug` folders in the zip? I read on discord that both debug and release templates are in the zip but I only see one Godot binary in it.

**Comment by hpvb** [comment]
The actual osx.zip file has both a debug and release template in it. The godot osx exporter renames the appropriate binary when recreating the zip and does not rezip the old one.

The GodotSharp exporter should do the same for the data folder. The OSX exporter has 'always' worked like that.

**Comment by akien-mga** [comment]
What's the status on this issue? Is it fixed in beta 2/3?

**Comment by akien-mga** [comment]
That's still valid as of 3.2 beta 5 Mono @neikeq.
