### ISSUE TITLE
Error Godot 3.1. Alpha3 renderer 2.0 win 32 and 64

### ISSUE THREAD

**Issue by giovanigsilva** [godotengine/godot#24304]
Erro in ES 2.0 renderer

win 32 and 64 

WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2081
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:70
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics
erasing C:\Users\Giovani\AppData\Roaming/Godot/projects/New Game Project-db903b93cbdc929593e13ea0ff8177ad/filesystem_update4

**Comment by giovanigsilva** [comment]
locked on this screen

![erro godot](https://user-images.githubusercontent.com/39173940/49882855-978bec80-fe18-11e8-9192-615b9d867e5e.png)

**Comment by giovanigsilva** [comment]
> We need more info, the issue template is there for a reason.
> 
> What is your OS? Graphics card? Is the project an empty (new) one? 2D or 3D?

ok

OS: windows 64
Graphic card: Intel HD Graphics (I always used in godot 3.0.6)
project empty or new (same problem)
3d and 2d

open normal, but when change to ES 2 dont restart, show me this problem

**Comment by giovanigsilva** [comment]
> We need more info, the issue template is there for a reason.
> 
> What is your OS? Graphics card? Is the project an empty (new) one? 2D or 3D?

"erasing C:\Users\Giovani\AppData\Roaming/Godot/projects/New Game Project-db903b93cbdc929593e13ea0ff8177ad/filesystem_update4"

"erasing C:\Users\Giovani\AppData\Roaming\Godot\projects\New Game Project-db903b93cbdc929593e13ea0ff8177ad\filesystem_update4" ??????????

**Comment by Chaosus** [comment]
Can you show a crash log here ? (You can see it if you run engine from command line)

**Comment by giovanigsilva** [comment]
> Can you show a crash log here ? (You can see it if you run engine from command line)
yes, does not enter the edit screen. stopped on this screen

![erro1](https://user-images.githubusercontent.com/39173940/50029714-dc5f8100-ffda-11e8-893d-65edc0fbe20b.png)
![erro2](https://user-images.githubusercontent.com/39173940/50029715-dc5f8100-ffda-11e8-9e47-54d06e64f998.png)

**Comment by giovanigsilva** [comment]
> Can you show a crash log here ? (You can see it if you run engine from command line)


pressing f5 to run my project  with error, showing opening screen too. as if the editor were working
![erro3](https://user-images.githubusercontent.com/39173940/50032599-3745a800-ffdc-11e8-82a1-e2e14471ada3.png)

**Comment by akien-mga** [comment]
Sounds like a duplicate of #23069.

**Comment by giovanigsilva** [comment]
> Sounds like a duplicate of #23069.


exactly. very similar. but 
I did not have this problem

**Comment by giovanigsilva** [comment]
Godot open normal. only when i try open in ES4 (CRASH)

**Comment by giovanigsilva** [comment]
![erro5](https://user-images.githubusercontent.com/39173940/50033325-382c0900-ffdf-11e8-92ea-13495477a0d5.png)

maybe this will help

**Comment by giovanigsilva** [comment]
--VERBOSE COMMAND

![erro6](https://user-images.githubusercontent.com/39173940/50038311-b2bb4f80-0004-11e9-8870-d2afe07c7bbc.png)

**Comment by giovanigsilva** [comment]
Solution

Only open the file default_env.tres in notepad

[gd_resource type="Environment" load_steps=2 format=2]

[sub_resource type="ProceduralSky" id=1]
Erase **ProceduralSky**
**[sub_resource type="" id=1]** <==============

[resource]

background_mode = 2
background_sky = SubResource( 1 )

**Comment by akien-mga** [comment]
Duplicate of #21551.
