### ISSUE TITLE
Convert To TileSet not respecting vframes/hframes

### ISSUE THREAD

**Issue by kamstrup** [godotengine/godot#2430]
I am creating a tileset like described in the tutorial (and editable scene I convert using Convert To -> TileSet) - with the variation that I do not have tiles in separate files, but in one atlas that I just load as a normal texture, but setting Vframes/Hframes and then just incrementing Frame for each tile. This is a really nice workflow.

However - when I try to use the tileset in a TileMap, I can see that the generated tileset have the entire texture as graphics for each tile, not respecting the Vframes/HFrames and Frame properties I set in the editable tileset.

**Comment by guilhermefelipecgs** [comment]
Unfortunately you can't use vframe/hframe for create tileset, you need to use region rect that is very tedious, but with this [plugin](https://github.com/vinod8990/godot_plugins/tree/master/Create_Tileset) you can do this very fast.

**Comment by reduz** [comment]
I will be working on a tool to make tileset importing less tedious soon too

**Comment by guilhermefelipecgs** [comment]
Cool :)

**Comment by bojidar-bg** [comment]
:+1:

**Comment by reduz** [comment]
oh ok I think I understand what you want with this issue
