### ISSUE TITLE
Popups don't respect canvas transform

### ISSUE THREAD

**Issue by tkurby** [godotengine/godot#24309]
**Godot version: c7cef29b00430e01faceed396dbd9def1b7cb235**

**OS/device including version: Linux 64bit, Fedora 28**

**Issue description:**
 Popups are currently getting clipped to a rectangle defined by the origin position and the window size. This means that they don't work when using a Camera2D as the camera just sets the canvas transform, which is ignored by the Popup clipping

**Steps to reproduce:**
1. Create a Popup node inside a scene.
2. When calling the popup*() functions with valid UI content it should display on screen.
3. Create a Camera2D and move it completely outside of the window rectangle.
4. When calling the popup*() functions with valid UI content they get drawn offscreen, clipped to the window rectangle.

**Minimal reproduction project:**
[popups_and_cameras.zip](https://github.com/godotengine/godot/files/2673534/popups_and_cameras.zip)
Setting camera1 as current should show popup in center of screen.
Setting camera2 as current should show nothing.

**Solution:**
Change the popup functions to apply the inverse canvas transform set by a camera, and correctly clip the popup rectangle inside the visible region of the current camera.

Git patch to commit stated above:
[camera_respecting_popups_patch.txt](https://github.com/godotengine/godot/files/2673487/camera_respecting_popups_patch.txt)

**Remark:**
This is not intended as a finished solution, but to show a way how to implement this behaviour if it is wanted. The question is if current popup behaviour is intended.

**Comment by creikey** [comment]
I think that the current popup behavior is intended because you're supposed to manually change the canvas transform by putting all GUI nodes under a CanvasLayer.

**Comment by creikey** [comment]
Here is a modified version of your example that does this: 
[popups_and_cameras.zip](https://github.com/godotengine/godot/files/2675266/popups_and_cameras.zip)

**Comment by creikey** [comment]
It's mentioned in the docs [here](https://docs.godotengine.org/en/3.0/tutorials/2d/canvas_layers.html)

**Comment by tkurby** [comment]
First of, that is in the tutorial not the the node docs, which still feels bad to me, as the documentation for a node should say what it does, while tutorials should say *how* to use them.

And secondly it is in the tutorial for canvasLayer which you don't know is relevant when using a popup or a camera, except that the Camera2D docs mention that you can make your own camera by manually setting the CanvasTransform of a viewport.

So while it is good that documentation exists (that can maybe be just referenced in the node docs), it still is hidden and requires a pretty long logical sequence for someone just wanting a popup to do what you'd think it would do (popup -> camera -> canvastransform -> canvaslayer -> canvaslayer tutorial).

**Comment by creikey** [comment]
The Camera2D moving doesn't just clip popups, it clips all canvas items, so it doesn't make sense to link that tutorial article to the popups docs. I think that the correct logical leaps would be (popup -> google gui nodes not following camera -> click on first result) as something specific like this is better suited to a Q/A response indexed by google.

**Comment by tkurby** [comment]
No I meant, putting the information or the link to the tutorial in the
canvasLayer docs. Like I said, I feel that basic functionality of a Node
should be in the Node docs, not a tutorial.
The Camera2D docs could maybe be more explicit about changing the canvas
transform, but that seems fine.

But I don't agree at all that it is ok to require a (maybe fruitless) web
search for the popup case.
You'd expect both logically and from the Node description that the Popup
always works in screenspace.
As it is right now, the stated usage of Popup is incorrect in all cases
where you have a Camera (which is probably most games).
That is not something you should need to web search, there should be a big,
obvious point in the docs about using a CanvasLayer to make it work as
expected.

**Comment by creikey** [comment]
Where in the popup node description does it say that it shows up in the viewport no matter what the canvas transform is? Basic knowledge of how canvas items work should be necessary to read the docs, which is why it's in the tutorial.

**Comment by tkurby** [comment]
My point is that it is a Popup.

The Popup node description for popup_centered, popup_centered_minsize and
popup_centered_ratio all say "Popup (show the control in modal form) in the
center of the screen [...]".
Note the word 'screen' here and again, this is about intention. When you
use a popup in any engine anywhere your intention is (pretty much) always
to have it show on screen.
The popup node does not work that way, which is absolutely
counter-intuitive and as such should be mentioned.

I don't want this to be about doc semantics or whatever, this is about user
intent:

There is a node called Popup.
If you use it normally it shows on your screen as expected.
If you add a camera it works as expected, as long as you are inside the
worldspace rect of window size.
if you leave that rect the popup gets clipped and eventually disappears
from the screen

That is *never* the user intent when using something called Popup.
So the fact that it behaves that way and the solution that makes it behave
*as expected* should be stated in the doc of the Node.

I don't see where the argument against is here if you design for the user
intent.

Needing the user to know about mathematical engine internals just to make
something behave as you want it to behave in 99.9% of all cases does not
seem to correspond to making this a powerful but user-friendly engine.


Am Fr., 14. Dez. 2018 um 11:12 Uhr schrieb Cameron Reikes <
notifications@github.com>:

**Comment by creikey** [comment]
I see your point. I think that the docs should make it clear what those `popup_*` methods actually do. It should be noted that it only centers the popup in the screen relative to the current canvas transform, not absolutely in the center of the screen.

**Comment by creikey** [comment]
I've made changes to the XML class documentation in my branch [here](https://github.com/godotengine/godot/compare/master...creikey:master)

**Comment by akien-mga** [comment]
Does #24408 satisfy the documentation changes needed to solve this issue?

**Comment by tkurby** [comment]
I still dislike that the CanvasLayer , which is the only correct method to
use popup is not mentioned.

Popups should work in screen space, talking about canvas transform is just
a technical detail which should be mentioned, but not integral to the
function description.

But apparently I am alone with that opinion so this can be closed if
everyone else is statisfied.
