### ISSUE TITLE
RichTextLabel auto-inserts newlines when changing text alignment.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#24305]
**Godot version:**
Godot 3.1 alpha 1 - 2 (both)

**Issue description:**
As mentioned in #23395, when one has text that is justified left and then they add more text that is justified right, the RichTextLabel inserts a newline rather than allowing the text to exist as two columns side-by-side. This is obstructing the implementation of a cleaner UI within the Editor.

**Steps to reproduce:**
    
    extends RichTextLabel
    
    func _ready():
        push_align(RichTextLabel.ALIGN_LEFT)
        add_text("hello")
        add_text(" world")
        push_align(RichTextLabel.ALIGN_RIGHT)
        add_text("testing")

"testing" appears on a line of its own while "hello world" appears on the same line. Haven't inserted any newlines manually yet.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta2

**Comment by KoBeWi** [comment]
Push align no longer exists.
