### ISSUE TITLE
Are AutoTile collision shapes different from other collision shapes?

### ISSUE THREAD

**Issue by ondrowan** [godotengine/godot#24300]
**Godot version:** 3.0, 3.1 alpha 3

**OS/device including version:** Windows 10, MacOS

**Issue description & steps to reproduce:**

I've tried [to ask on reddit](https://www.reddit.com/r/godot/comments/a57tyv/are_autotile_collision_shapes_different_from/) without any answer, so I'm not sure whether this is a bug or a feature. Either way, it's something that doesn't seem to be documented anywhere.

I'm working with simple sprite exported as `TileSet`. In a blank scene I'm trying to find collisions between a `TileMap` and a `RayCast2D`.

![](https://i.redd.it/u4f3w7ev1o321.png)
_Autotile and RayCast2D don't collide in this case_

From what I've tried collisions seem to behave differently when using `Autotile`. If I don't set any `CollisionShape2D` in `TileSet` scene, set `TileSet` as `Autotile`, set collisions on it via Autotiles menu and try to find collision with `RayCast2D` it works only if it intersects walls of the tile. If I move `RayCast2D` fully inside of the tile, it doesn't collide with it at all.

![](https://i.redd.it/4yz9d0ha2o321.png)
_Autotile and RayCast2D do collide in this case_

If I use the `TileSet` with static bodies and their own collison shapes, `RayCast2D` doesn't have problems with collisions even if it's fully inside of the tile.

![](https://i.redd.it/a6eqts8g2o321.png)
_TileMapStatic and RayCast2D do collide properly_

I'm using default collision layers and masks on both `TileMap`s and on `RayCast2D`, so that shouldn't be the problem. I'm confused, because even when I set collision shapes to be visible in debug menu they are in both cases shown as full rectangles, but they don't seem to behave in the same way. Are collisions on Autotiles somehow special or am I just doing something wrong?

**Minimal reproduction project:**  https://github.com/ondrowan/godot-autotile-raycast (requires 3.1 alpha)

**Comment by MarianoGnu** [comment]
Afaik, raycasts have a feature to set what type of bodyes it collides with (rigid, kinematic and/or static). By default TileMaps are of type static, but there's an option on the properties to change it's body type to Kinematic, try to play with these values and tell me if you discoversomething.

By the other hand, tileset used to support all kinds of collision shapes. For the sake of simplicity, it now supports Convex polygon shapes, maybe there's an issue betwheen this kind of shapes and Raycast2D, not directly related to TileSet itself.

**Comment by KoBeWi** [comment]
Sooo I inspected the reproduction project and the tilesets have different colliders. No idea how, the right one has RectangleShape2D, so it indeed behaves differently, but it's not TileSet-related issue. When you create a new collider using the new rectangle tool
![image](https://user-images.githubusercontent.com/2223172/85961192-14ee6200-b9a9-11ea-8a64-fdc9d24cce33.png)
it creates ConvexPolygonShape2D correctly like in the other TileSet, which works consistently with the other.

That said, you won't run into this bug when you make tilesets with the tileset editor. Also different shapes behaving differently with raycast is another issue (probably one of #39876).
