### ISSUE TITLE
Godot 3.1 alpha3 - "body_set_shape_disabled()"

### ISSUE THREAD

**Issue by shmellyorc** [godotengine/godot#24302]
Godot version: 3.1 alpha3 (from your website blog post)

OS/device including version: Windows 10 x64

Note: the function still activates, just error spam.

Issue description:
1. Created an area2d + collision shape box/circle. Make an kinematic body + collision box/circle.
2. Make the area2d have an "on body" signal to some function.
3. in that area2d "body enter" function, set the area2d collision to disabled
4. Move the kinematic inside the area2d.
5. error spam will occur

You will get this error: 
E 0:00:14:0596   Method/Function Failed.
  <C Source>     servers/physics_2d/physics_2d_server_sw.cpp:734 @ body_set_shape_disabled()
  <Stack Trace>  coin.gd:20 @ _on_body_entered()

**Comment by KoBeWi** [comment]
Doing this now (3.1 stable) shows this error, once:
```
Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead
```
Either it's fixed or I did reproduction wrong.

**Comment by akien-mga** [comment]
Indeed, this change was to fix issues such as this one.
