### ISSUE TITLE
Signal connection interface should be able to list existing functions

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24316]
**Godot version:**
11d7738

**Issue description:**
The editor interface for connecting a signal is absolutely not friendly when it comes to connecting a signal to an existing callback, since you have to remember the name and type it.

**Proposal:**
Have an interface similar to the animation player's one for the call function track, that allows to choose between a list of methods.

**Comment by vnen** [comment]
I think this interface needs a big overhaul to make it friendly.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/239, as feature proposals are now tracked on the Godot proposals repository.
