### ISSUE TITLE
ERROR: get_indent_level when creating script

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#24314]
**Godot version:**
3.1 c7cef29

**OS/device including version:**
Windows 10

**Issue description:**
When I created a script, then a lot of errors appear:
```
ERROR: get_indent_level: Index p_line=14 out of size (text.size()=13)
   At: scene/gui/text_edit.cpp:5122
```
**Steps to reproduce:**
1. Create new script
2. Go to this script

https://streamable.com/r6hhw

**Comment by creikey** [comment]
I couldn't reproduce this error. Have you tried restarting the editor and doing the same thing again?

**Comment by qarmin** [comment]
I cleared all data(without editor settings) and error still was there
When I deleted the editor's settings, the error did not appear anymore.
Here is file with editor settings with this error: [editor_settings-3.txt](https://github.com/godotengine/godot/files/2675438/editor_settings-3.txt)
and here is without it: [editor_settings-3.txt](https://github.com/godotengine/godot/files/2675435/editor_settings-3.txt)

**Comment by QbieShay** [comment]
@qarmin could not reproduce on windows 10. Anything in particular about your project? Maybe you overwrote the gdscript template by accident in godot's sources?

**Comment by qarmin** [comment]
I deleted godot folder from Roaming and started working.
For 6 hours everything worked well, but when I created the script in C#, this error appeared again.

**Comment by akien-mga** [comment]
I never saw this issue on Linux, can you still reproduce it in the current master branch?

**Comment by KoBeWi** [comment]
I can't reproduce it either, both with 3.1.1 and 3.2 beta1.
@qarmin Unless you can confirm it still happens in 3.2, this can be closed.

**Comment by qarmin** [comment]
I can't reproduce this anymore.
