### ISSUE TITLE
In game theme does'nt fit with new blueish theme

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#24326]
The default game theme is still the (in my opinion) not so nice looking gray theme, and the gray default clear color looks bad in combination with the new bluish theme. Here is how it would look if the default theme was the same in the editor and in the game, much nicer: ![2018-12-13-185309_1366x768_scrot](https://user-images.githubusercontent.com/28286961/49957510-5a068c80-ff08-11e8-94bc-9bee324b6fc0.png)

OLD TITLE: Clear color does'nt fit with new blueish theme

**Comment by Calinou** [comment]
I'm not sure if this is a good idea, since the clear color doesn't change if the user switches themes.

**Comment by Zylann** [comment]
I don't think the background of *the game itself* should account for the editor's theme, which is an editor option... The grey background was still grey when Godot was purple, and I think it's a good neutral color, even if people have a bright theme or whatever.

**Comment by KoBeWi** [comment]
If the issue changed to be about in-game GUI theme, then it's the same as #25349

**Comment by Jummit** [comment]
Closing as a duplicate.
