### ISSUE TITLE
touch support with mouse click in macOS Mojave

### ISSUE THREAD

**Issue by salvob41** [godotengine/godot#24325]
**Godot version:**
Godot3.1-alpha3

**OS/device including version:**
macOS Mojave

**Issue description:**
in order to test Touch support in development the best thing is emulate it with mouse click. But this doesn't seem to work on macOS Mojave (while it looks it works in Ubuntu and Windows computer)

**Steps to reproduce:**
Touch support in https://github.com/notapixelstudio/godot-turn-based-rpg

**Minimal reproduction project:**
Touch support in https://github.com/notapixelstudio/godot-turn-based-rpg

**Comment by salvob41** [comment]
Actually if you, as [this post](https://www.reddit.com/r/godot/comments/a63pfr/touch_support_test_on_macos/ebseh9b/) on reddit suggests, 

> enabled Input Devices → Pointing → Emulate Touch From Mouse in the Project Settings. It's disabled by default.

Although .... Why is it disabled by default?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3190, as feature proposals are now tracked on the Godot proposals repository.
