### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by michaellee8** [godotengine/godot#24339]
Version: Future

grpc is a rpc framework from google, that works with multiple languages and platforms, including c++, c#, android java and objective-c. Its support may allow developers to write game server using other languages.

I have consider 2 ways for its support, either using c++ version for GDNative, but leveraging GDNative seems hard, especially when there are generated c++ code.

Another way is to leverage its c# library, so far there are a stable version for desktop and experimental support for Unity as well. Is it possible to port that one for godot with c#?

Just some thoughts, hope that I will receive some advices.

**Comment by Faless** [comment]
I don't know about C#, but you can probably bind it using GDNative `godot_net_packet_peer`.
I don't see any real value in supporting this in the engine itself, as it seems to me it can be done via a plugin.
Can you further explain how you would like to see it integrated? What would the the added value be? Can you explain how it would be better than what we currently have? Is there any reason why using this specific framework and not another one?

> Its support may allow developers to write game server using other languages.

You can already create a game server using other languages.

**Comment by gocs** [comment]
grpc client perhaps? also examples

**Comment by Faless** [comment]
Seems like an overkill, it depends on protobuf (or other IDLs), we have an RPC system that works, and gRPC requires extra work from the developers compared to what we have.

If there's some specific need to integrate with an existing gRPC service GDNative could be used.

Closing.

**Comment by adonig** [comment]
For anyone landing here via search: a native gRPC client for Godot 4.6+ now exists https://github.com/quobox/godot-grpc
