### ISSUE TITLE
Why do you not use latest Mono version?

### ISSUE THREAD

**Issue by SourceSkyBoxer** [godotengine/godot#24336]
Hello everyone,

Godot 3.1 Alpha 3 - Please recompile with Mono latest version :(

Because I want prove you because Mono 5.12.0 is very bug cause mkbundle can't generate end of bundle executable - I already tried. No success.

Please remember that Mono 5.23.0 ( very latest version ) is very stable with mkbundle cause mkbundle generates end of bundle executable.

Please believe me! You know I have been banned from Mono Project because they don't understand what current version of Mono is buggy:

Mono.5.12 - Failed - mkbundle cannot generate executable
Mono 5.14 - Failed - mkbundle cannot generate executable
Mono 5.16 - Failed cause mkbundle forget to add header aot_module_register error
Mono 5.18 - Failed same aot_module_register error
Mono 5.19 - success - all work fine
Mono 5.20 - success - all work fine
Mono 5.21 , 5.22, 5.23 - success - all work fine.

// EDIT:
Please remember and pick up LLVM ( It should compile for x64 and x86 ) [ EDIT: LLVM is bug, We need skip llvm / clang ] Because they can't generate gen files if we use older than LLVM 8.0 version
Please remember custom mono build like ./autogen.sh --prefix=/usr --enable-large-heap=yes --enable-big-arrays
than Godot mono version
// END OF EDIT:

All OS , latest version of Godot 3.1 Alpha 1, 2, 3. and Godot 3.0.6 same 

Thanks

**Comment by SourceSkyBoxer** [comment]
@Chaosus  thanks for note with latest mono version!
And check error if I build like this:

See log:
https://gist.githubusercontent.com/SourceSkyBoxer/37c55516b83229c83fb8415f457ce01a/raw/fbfb80879132592e28aa60cb05b24e336863c9dc/godot3.1-alpha3-error.log

**Comment by Chaosus** [comment]
Im not a mono specialist - thats why I call @neikeq to help you )

**Comment by Chaosus** [comment]
Personally I use custom Godot build with mono 5.16 cuz its latest stable version

**Comment by SourceSkyBoxer** [comment]
"mono 5.16 cuz its latest stable version" it still bug with mkbundle  check out my issue! Did you check mkbundle? Make simple if you write hello.cs with static void main and Console.WriteLine("Hello, Sir"); than compile mcs/CSC's than you generate bundled executable like this mkbundle --deps --static -z -L /usr/lib/mono/4.5 yourhello.exe -o hello_bundle -v 
Than it shows for you error cause it forgets to embed aot_module_register from header file like aot_register.h

That is reason - I wait for @neikeq

**Comment by hpvb** [comment]
We're certainly not going to ship stable releases of Godot against unstable versions of Mono. 5.16 is the current stable and that's what will be used for the official downloads for 3.1. If you need a feature from an unstable Mono release you can build your own.
