### ISSUE TITLE
mouse motion is not accurate enough.It is not guaranteed that when the mouse stops, its relative and speed are zero

### ISSUE THREAD

**Issue by haizhou37** [godotengine/godot#24349]
**Godot version:**
godot3.1 alpha3

**OS/device including version:**
manjaro gnome x64
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile
intel hd 3000

**Issue description:**
![peek 2018-12-14 22-36](https://user-images.githubusercontent.com/33272474/50009026-d1175000-fff0-11e8-9ccb-ce1ae15fd5af.gif)
![2018-12-14 22-18-54](https://user-images.githubusercontent.com/33272474/50009034-d6749a80-fff0-11e8-8bb9-7a4d47ae9c3b.png)
![2018-12-14 22-19-06](https://user-images.githubusercontent.com/33272474/50009037-daa0b800-fff0-11e8-9aa8-7c1b502a56cf.png)

**Steps to reproduce:**
As shown above

**Minimal reproduction project:**
[test1.zip](https://github.com/godotengine/godot/files/2680443/test1.zip)

**Comment by Naryosha** [comment]
InputEventMouseMotion is triggered when there is a mouse motion, thus it won't fire when it's (0, 0) (not moving). The value you see is the last motion.

**Comment by groud** [comment]
Please, don't open twice the same issue. As @Naryosha just did, I already explained in #24127 that this is a normal behavior. InputEventMouseMotion are triggered when the mouse moves, not when it stops moving. The speed will never be zero, so you have to reset the value to zero by yourself, likely in the _process function.
