### ISSUE TITLE
How to avoid projects becoming too interconnected

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#24346]
It's generally not a good idea to have objects interact with one another too much in programming, but In Godot it's nearly unavoidable for me.
Where you would have a single class (for example a player), you have a tree of nodes you have to interact with. In the case of a player class I would just do `player.texture = bar`, but in Godot it would be `player.get_node("Sprite").texture = bar`, which only gets longer for larger objects like UI, large levels and complex objects. If I would change my tree just a little bit everything would break and I would have to change much of my code, which is the primary reason you avoid interconnectivity.
There may be some programming patterns which help with this problem, if you know one please let me know.

**Comment by Zireael07** [comment]
I believe this is better suited to the forum, Discord or Q&A site?

**Comment by bojidar-bg** [comment]
> In the case of a player class I would just do player.texture = bar, but in Godot it would be player.get_node("Sprite").texture = bar, which only gets longer for larger objects like UI, large levels and complex objects.

Bad example. Changing the texture should be handled by the player class directly, and outside classes should change player's state in other ways. For example:
```gdscript
# player.gd
enum State {NORMAL, HURT, POWERUP}
var state = State.NORMAL setget set_state # Better with #6491
func set_state(new_state):
    state = new_state
    $Sprite.texture = state_textures[state] # For example
# Other script
# ...
player.state = player.HURT
# ...
```

If other classes and scripts start interfering with internal player state, you are breaking encapsulation.

---

I think this might be better on the [godotengine/godot-docs](https://github.com/godotengine/godot-docs/) repository. There it might become a tutorial, instead of just a discussion.

**Comment by Jummit** [comment]
> Bad example. Changing the texture should be handled by the player class directly, and outside classes should change player's state in other ways.
Yeah, my example isn't very good. I think I wanted to demonstrate how node paths get long and hard to refactor, but the player one isn't very clear. Also, I moved this to the forum: https://godotdevelopers.org/forum/discussion/20318/how-to-avoid-long-node-paths-and-unmaintainable-interconnectiveness-in-large-projects?new=1
