### ISSUE TITLE
Reloading a project after deleting mesh preview files inside temporary directory generates an error log

### ISSUE THREAD

**Issue by Shinryuuji** [godotengine/godot#24356]
**Godot version:**

Godot 3.1 Alpha, debug build based on revision e588c241681032c616a998a9884b30215ea7d4e3. 

**OS/device including version:**

Windows 10 x86_64 Build 17134

**Issue description:**

Deleting mesh resource preview files inside "%TEMP%/Godot/" and reloading project results in the following error message on the editor console:

```
ERROR: Another resource is loaded from path: res://diamond.obj (possible cyclic resource inclusion)
   At: core\resource.cpp:79
```

I guess that preview thread and scene thread try to load the mesh resource at the same time. Does not happen if I enforce `EditorMeshPreviewPlugin::handles` to always return `false`.

**Expected behavior:**

No error message if both threads try to load the same mesh resource.

**Steps to reproduce:**

1) Create new project with a main scene
2) Add "MeshInstance" to root node
3) Import an *.obj file and attach it to that "MeshInstance"
4) Save project and close Godot
5) Delete all preview files inside "%TEMP%/Godot/"
6) Start Godot and open the project

**Minimal reproduction project:**

[SampleProject.zip](https://github.com/godotengine/godot/files/2681561/SampleProject.zip)

**Comment by KoBeWi** [comment]
The error no longer appears since 3.1 stable
