### ISSUE TITLE
Controls within GraphNode won't keep size/anchor modifications

### ISSUE THREAD

**Issue by mateusfccp** [godotengine/godot#24355]
**Godot version:**
01fa067

**OS/device including version:**
Arch Linux

**Issue description:**
When inserting any `Control` or extension as a child of a `GraphNode`, it's size is not kept. min_size works correctly, and can be used to mitigate it, but it won't work with anchors. It also has been posted [here](https://www.reddit.com/r/godot/comments/96vlc5/textedit_in_graphnode_collapses_to_0_size/) 4 months ago.

**Steps to reproduce:**
1. Create a `GraphNode`.
2. Insert any kind of `Control` as it children.
3. In the `Control` node, set its layout to "Full Rect". It will expand to the `GraphNode`.
4. Change the tab to another scene and then change to `GraphNode` scene again.
5. The `Control` will have its size collapse to its default size instead of keeping the Full Rect size and anchors.

**Comment by mateusfccp** [comment]
Well, I tested it a little more and seems to be happening with many controls, like `Control`, `Panel`, `Container`. Didn't test all the controls, though.

**Comment by mateusfccp** [comment]
I tested it with tons of `Control` nodes, and although it was not each one, by sampling I deduced that it happens to every kind of `Control` node. Also, I realized that it's not the height that is not kept. Instead, the size will collapse to the default size, the one that it had when first inserted within the `GraphNode`.

**Comment by groud** [comment]
The GraphNode control is a container, thus, it modifies it's children anchors and margins.
So this is expected behavior.

Note that now a messages is displayed when you try to move a child of a container.
