### ISSUE TITLE
Setting for default quote type

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#24351]
**Godot version:**
3.1-alpha3

**OS/device including version:**
Any

**Issue description:**
I'd love to have a setting for choosing whether Godot suggests single or double quotes for strings. I use single quotes everywhere and currently I have to type one single quote to make the suggestion use single quotes, too.

![peek 2018-12-14 18-14](https://user-images.githubusercontent.com/8849554/50017473-6fdd8580-ffcc-11e8-8120-474a48f0b85c.gif)

**Comment by mateusfccp** [comment]
I'm on it.

**Comment by mateusfccp** [comment]
I created a pull-request #24437 to solve this.

**Comment by akien-mga** [comment]
Fixed by #24437.
