### ISSUE TITLE
Disabling code completion delay results in no completion at all

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#24352]
**Godot version:**
3.1-alpha3

**OS/device including version:**
Pop!_OS 18.10 (Ubuntu 18.10) 64 bit

**Issue description:**
Disabling code completion delay in editor settings (`text_editor/completion/enable_code_completion_delay`) results in no completion showing up at all.

**Steps to reproduce:**
Disable the setting and type code.

**Comment by akien-mga** [comment]
The way it's currently implemented, that setting is indeed used to toggle code completion itself, not the delay. If that's intended, it should be renamed to `enable_code_completion`.

**Comment by akien-mga** [comment]
CC @Paulb23
