### ISSUE TITLE
[2D] Vector positions showing fluctuations.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#24369]
**Godot version:**
3.1 build 4629152

**OS/device including version:**
Ubuntu Linux 18.10 64-bit.

**Issue description:**
Testing a project with 3.0.6 and a current build of 3.1. I noticed that with 3.0 the velocity variable's y-velocity stays stable (beyond moving up and down the "ramp"). 3.1, however, has it continually fluctuate. This doesn't *appear* to be noticeable with the player character sprite.

[24369_demonstrator_videos.zip](https://github.com/godotengine/godot/files/2682560/24369_demonstrator_videos.zip) is a zip file containing videos of what I mean with both 3.0 and 3.1.

**Minimal reproduction project:**
https://github.com/Sslaxx/Godot_Sonic_Engine/ - note that the "platform" is just a collision shape, so they need to be set visible in the debugging menu.

**Comment by groud** [comment]
I cannot reproduce on master. Could you try again with a more recent version ?

**Comment by Sslaxx** [comment]
Haven't got this to reproduce since either.

**Comment by groud** [comment]
Ok, I guess it's fixed then. Please comment here if someone encounter the problem again, I'll reopen.
