### ISSUE TITLE
Possibility to deactivate a node

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#2437]
Is it possible to have option to deactivate a node?
With deactivating I mean completely invisible, no collision, no running script.

I think in special about this nodes:
- CanvasModulate
- CollisionObject

**Comment by volzhs** [comment]
how about just popping it out of scene tree without free node?

**Comment by reduz** [comment]
just remove it from the scene and keep it out

**Comment by puppetmaster-** [comment]
thx for you comments
Possible I'm doing something wrong.
When I work with light I need to add a CanvasModulate, but when I have it inside i can't set it invisible to see something.
![image](https://cloud.githubusercontent.com/assets/10463138/9743906/1ffd3d40-5669-11e5-9745-a55e053cd663.png)

We have add as workaround an huge light (edit_light). I don't know if it's a bug or work as designed.

**Comment by reduz** [comment]
Hmm I didn't think of that, but may work setting it invisible to deactivate
it.. could add it

**Comment by puppetmaster-** [comment]
perhaps light also?

**Comment by reduz** [comment]
light is not deactivated when hidden?

**Comment by puppetmaster-** [comment]
no only when enabled = off

**Comment by puppetmaster-** [comment]
:+1:  for your great work
