### ISSUE TITLE
Error while deleting a default_env.tres

### ISSUE THREAD

**Issue by gavriil07** [godotengine/godot#24377]
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10

**Issue description:**
![dsadas](https://user-images.githubusercontent.com/28069262/50045602-4db43800-009e-11e9-9f25-8b0d2ef914bb.PNG)

**Steps to reproduce:**
new project -> delete godot logo image

**Comment by Chaosus** [comment]
Note that only deleting default_env.tres is trigger that error. Still valid in 3.1
