### ISSUE TITLE
Comment in visual scripts can be used normally, but long text will report errors(out of size)

### ISSUE THREAD

**Issue by haizhou37** [godotengine/godot#24372]
**Godot version:**
godot3.1 alpha3

**OS/device including version:**
manjaro gnome x64
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile
intel hd 3000

**Issue description:**
Error reported when appear a long text comment,  and we scroll through the properties panel.But the function is normal.
![peek 2018-12-15 22-35](https://user-images.githubusercontent.com/33272474/50044220-156f2280-00bb-11e9-9985-50389768d801.gif)

**Minimal reproduction project:**
[test11.zip](https://github.com/godotengine/godot/files/2682689/test11.zip)

**Comment by KoBeWi** [comment]
No error in 3.2.2, the comment node fits size to contents.
