### ISSUE TITLE
Godot fails to load if command prompt is clicked

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#24389]
**Godot version:**
3.1 Alpha 3

**OS/device including version:**
Windows 10 x64

When opening the Godot Project Manager or a project directly, there is a Command Prompt window that appears first. If the Command Prompt window is clicked before the Project Manager or project starts loading, then Godot will fail to continue loading past the blank Command Prompt window.

Perhaps this issue would be moot if the Command Prompt loaded in the background by default on Windows. Not sure if this is a problem on other operating systems.

**Comment by bojidar-bg** [comment]
Related: #17889

**Comment by PetePete1984** [comment]
If you click a command window with anything running in it, that process is paused because you're basically telling windows "I want to select and maybe copy some text from there" - this isn't isolated to Godot. A build without the console would indeed circumvent the problem.

**Comment by Oranjoose** [comment]
>           Does the process reuse if you focus the Godot window again? If so, there's no issue indeed.

The Godot window doesn't even appear if you click the Command Prompt window such that this problem occurs.

**Comment by akien-mga** [comment]
And what if you click on another window/unfocus the cmd.exe?

**Comment by Oranjoose** [comment]
>           And what if you click on another window/unfocus the cmd.exe?

Nothing happens if you focus or unfocus the Command Prompt window. However, I've discovered that if you press enter in the Command Prompt, it will resume loading Godot.

**Comment by akien-mga** [comment]
That's indeed expected behaviour on Windows: https://superuser.com/questions/459609/what-does-it-do-exactly-if-i-click-in-the-window-of-cmd
