### ISSUE TITLE
Load/Preload classes do not work after HTML5 export.

### ISSUE THREAD

**Issue by simpleyo** [godotengine/godot#24398]
Godot version:
v3.1.dev.custom_build.c00edd9

OS/device including version:
Windows 7 Ultimate x64

Issue description:
After HTML5 export, load/preload classes do not work.

```
# File: Node2D.gd
extends Node2D

const MyClass = preload("MyClass.gd")

func _ready():
    pass
```

```
# File: MyClass.gd

var my_var # If declare a variable then load/preload do not work.

# If you do not provide _init method then load/preload do not work.
func _init():
    pass
```

**Comment by bojidar-bg** [comment]
Are you using the exact same version of the export template as the engine? Before exporting the project, Godot "compiles" GDScript files (in order to make them smaller), but in doing so loses compatibility with older export templates.

**Comment by simpleyo** [comment]
Yes, I using the exact same version of the export template as the engine.

**Comment by simpleyo** [comment]
I've been testing and I think the problem happens only with my custom build.

**Comment by Toshiwoz** [comment]
@simpleyo you mean this can be closed?

**Comment by simpleyo** [comment]
> 
> 
> @simpleyo you mean this can be closed?

Yes
