### ISSUE TITLE
Visual debug for collision, ray, navigation, path, joint and more

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#2439]
When turned on you can see in a running project this shapes and line like you were in edit mode.

Examples:
Ray: https://youtu.be/Egy40TYFut8?t=31s
Collision: https://youtu.be/SOiwArn4Bmw?t=13s

**Comment by neikeq** [comment]
This is something I would like to see.
2D Example:
https://youtu.be/DZjkSYoZECU?t=2m4s

**Comment by reduz** [comment]
working on it

**Comment by eska014** [comment]
Collision shapes, raycasts and navigation can be toggled visible at runtime since 83d9a692be648668b5b363f2424c619e15639843.
Not sure if this feature is also planned for paths and joints.
