### ISSUE TITLE
File.READ_WRITE only reads OR writes on Windows

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#24393]
Godot 3.1 alpha 3
Windows 10 x64

In the documentation for the File.READ_WRITE mode, it says "Opens the file for read **and** write operations." However, it only appears to work for read **or** write, depending on which operation happens first.

For example, consider the following read operation::
```
#read operation
var testString = file.get_line()
```

and write operation:
```
#write operation
file.store_string("this is fun text")
```

Only one of those lines will work, specifically the one that happens first. If you reverse the order, then the other one will work.

I'm not sure if this is intended behavior, but it makes me wonder what's the point of having a File.READ_WRITE, if it is not much different than just opening the file with File.READ and File.WRITE separately.

**Comment by Naryosha** [comment]
Can't reproduce. Both lines worked.

**Comment by akien-mga** [comment]
Might be Windows-specific, does it allow read+write file handles?

**Comment by Oranjoose** [comment]
[godot_file_READ_WRITE_issue.zip](https://github.com/godotengine/godot/files/2684003/godot_file_READ_WRITE_issue.zip)

I attached a minimal project showcasing the issue.

To be more verbose, consider two snippets of code:

In this snippet, the `get_line` operation works, but not the `get_line`
```
var file = File.new()
file.open("res://testfile.txt", File.READ_WRITE)

var testString = file.get_line()
print(testString)
	
file.store_string("this is fun text")
```

However, if you reverse the order, as shown below, the `store_string` operation works, but not the `get_line` operation.
```
var file = File.new()
file.open("res://testfile.txt", File.READ_WRITE)

file.store_string("this is fun text")

var testString = file.get_line()
print(testString)
```

**Comment by Naryosha** [comment]
Can reproduce with the given project. On Linux it works as expected (the second line is overwritten):
```
This is text
this is fun textxt is fun or something
```
On Windows, the write operation fails silently. (unless `seek` is called before writitng)
