### ISSUE TITLE
Radial artefacts in environment filtering (GLES3)

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#24403]
**Godot version:**

3.1-alpha3

**OS/device including version:**

Arch Linux x86-64, AMD RX 470, open source stack

GLES3 backend (@reduz )

**Issue description:**

When using a detailed environment map, a metallic material with roughness (0; 1) will show "radial" artefacts.
The same scene in the latest stable release does not suffer from those artefacts.

(latest alpha on the left, stable on the right)
![screenshot_2018-12-16_17-43-30](https://user-images.githubusercontent.com/5209613/50056272-2622a580-015a-11e9-8407-2bd80379955b.png)

This behaviour was most likely introduced by 62233423c7310a155e8c948c053701dba248dcdb

**Steps to reproduce:**

Create a scene with a `MeshInstance` using a `SphereMesh` and a `SpatialMaterial` with `Metallic` = 1 and a `Roughness` between 0.25 and 0.75.

When using a `WorldEnvironment` node with a `PanoramaSky` background (environment map should have lots of details) the artefacts can be observed.

**Minimal reproduction project:**

[cubemapfilter_alpha.zip](https://github.com/godotengine/godot/files/2683746/cubemapfilter_alpha.zip)
[cubemapfilter_stable.zip](https://github.com/godotengine/godot/files/2683747/cubemapfilter_stable.zip)

**Comment by reduz** [comment]
I think this is a non bug and expected as a result of using dual parabolloid for reflections, kicking to 3.2 since GLES3 backend will go away.

**Comment by Anutrix** [comment]
This is a GLES3 issue which is going to go away. Should it be in 4.0 milestone?

**Comment by Calinou** [comment]
@Anutrix This issue is already in the 4.0 milestone :slightly_smiling_face:

**Comment by Anutrix** [comment]
@Calinou I meant that it shouldn't in 4.0 as GLES3 issues won't matter in 4.0. Or will some parts of it stay?

> 
> 
> @Anutrix This issue is already in the 4.0 milestone 🙂

**Comment by clayjohn** [comment]
Can't reproduce in master. I checked it out when working on overhauling radiance maps.
