### ISSUE TITLE
Plugin fails to download from Godot with bad sha256 check, but works on assetlib and Github archive

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24409]
Godot 3.0.6
Godot 3.1 alpha3

From https://github.com/Zylann/godot_heightmap_plugin/issues/59
I tried downloading my plugin from Godot, but it failed with a bad sha256 check.
If I try to download it from the assetlib website, it works. It also works when downloading the archive from Github, and unzips fine. Also, if I try to unzip the asset in `C:\Users\Marc\AppData\Local\Temp\Godot\tmp_asset_231.zip`, it works fine as well.

Only Godot fails, and only that plugin so far...

Reproduction steps:
Open an empty project, and try to download this plugin from the AssetLib tab https://godotengine.org/asset-library/asset/231

![image](https://user-images.githubusercontent.com/1311555/50060644-56843700-018e-11e9-9833-8a94edfabac1.png)

Also, from 7zip none of the sha256 match what Godot is saying, in case it matters:
![image](https://user-images.githubusercontent.com/1311555/50060696-14a7c080-018f-11e9-9e75-8cb272e04488.png)

**Comment by akien-mga** [comment]
I probably just put the wrong sha256 sum (this is done manually).

**Comment by akien-mga** [comment]
Fixed.
