### ISSUE TITLE
AudioServer.add_bus_effect not working

### ISSUE THREAD

**Issue by NoodleSushi** [godotengine/godot#24400]
Godot Engine v3.0.6.stable.official

![](https://cdn.discordapp.com/attachments/477544613511692358/523823317686419497/Capture.PNG)
I've been trying to add an effect in the master audio bus yet it doesn't happen. I don't know what I did wrong, It it one of Godot's Problems?

![](https://cdn.discordapp.com/attachments/477544613511692358/523823573387706371/Capture.PNG)
Also what does this error mean?
```
0:00:02:0355 - Condition ' p_effect.is_null() ' is true.
----------
Type:Error
Description: 
Time: 0:00:02:0355
C Error: Condition ' p_effect.is_null() ' is true.
C Source: servers/audio_server.cpp:776
C Function: add_bus_effect
```
**Steps to reproduce:**
1. New Project
2. Create a Node
3. Add this script from the bottom to the created node
```
extends Node2D

var effects_in_bus_0 = 0
var bus_count = 0
func _ready():
	AudioServer.add_bus_effect(0,AudioEffectPanner)
	effects_in_bus_0 = AudioServer.get_bus_effect_count(0)
	bus_count = AudioServer.get_bus_count()
	print("effects_in_bus_0: ",effects_in_bus_0)
	print("bus_count: ",bus_count)
```
4. When scene is running, `effects_in_bus_0` should be equal to `1`

**Minimal reproduction project:**
[asdjf.zip](https://github.com/godotengine/godot/files/2683518/asdjf.zip)

**Comment by Naryosha** [comment]
```
AudioServer.add_bus_effect(0,AudioEffectPanner.new())
```

**Comment by NoodleSushi** [comment]
@Naryosha It works now, Thank you so much ^_^. (didn't realize I gotta put `.new()`)
