### ISSUE TITLE
help godot

### ISSUE THREAD

**Issue by Mansoor54** [godotengine/godot#2440]
how rebuild what the step to run c++ program in goddot i create all this code in sumator folder now how to run this haven't idea

config.py sumator.h sumator.cpp register_types.h register_types.cpp SCsub

**Comment by m4nu3lf** [comment]
Are you on a unix-like os?

**Comment by Mansoor54** [comment]
i used Ubuntu i want to used c Program in godot

**Comment by m4nu3lf** [comment]
You should use GDScript and turn to C++ only if the game does not perform well. After you have configured your C++ module you have to run this command "scons platform=x11" (no double quotes), from the directory where you put the godot source.

You should ask for help on the Forum or on facebook, this place is for requesting feature or signaling bugs.

**Comment by Mansoor54** [comment]
i create simple quiz game ask few question and give them ans also score option in gd but lot of problem occur

**Comment by randyyaj** [comment]
Hey Mansoor I helped you on reddit. If you are still having problems please reply to your reddit thread here https://www.reddit.com/r/godot/comments/3h5x28/need_help/ I can help you more there as  m4nu3lf said this site is for requesting features or signaling bugs.

**Comment by Mansoor54** [comment]
help this

**Comment by Mansoor54** [comment]
i create this game now i need to add score and timer scene for giving a
corect or wrong ans
