### ISSUE TITLE
Will there be more support for converting resources into the GPU for accelerated computing?(GPGPU)

### ISSUE THREAD

**Issue by HighCWu** [godotengine/godot#24416]
Godot version:

Godot 3 Feature Request / Discussion

Issue description:

I want to know after assigning the COLOR parameter in a shader,  if I can get a new sample2D type texture through a function and perform the next operation.  

I've searched for other shader implementations, and it seems that they don't have the function either. Imagine if I want to immediately perform another filter operation on a picture that has been shaded by a shader, what should I do in such a scene? 

In fact, I know a solution is to use viewport. Multiple viewport nesting should be able to achieve a series of processing. But this is the case, the implementation will become very troublesome. Other engines seem to be able to achieve the effect I want through the command buffer. The command buffer seems to be a better solution than viewport. Although I don't really know it very well. 

However, I found that the command buffer seems to be used not only for coloring, but also for GPGPU. And it seems that the native glsl has some parts are not used for game rendering. there are also a series of functions that can accelerate the operation on the GPU. However, such implementations should be slower than CUDA or opencl, but faster than CPU. If you want to achieve complex shading effects, several shaders or several viewports can be cumbersome, or it may be that I didn't find the right way. I know this is a game engine, but implementing this may be helpful in some areas. For example, GPU-accelerated audio processing, game AI upgrade acceleration and so on. 

Another problem is that it seems that audio is difficult to get content through gdscript. If I want to send the audio to GPU, mabe I should read the audio files directly through gdscript functions. And it seems godot doesn't have a media recorder interface ?

Maybe the features I mentioned are not very important and some can implement through the cpp native way. But to be honest, gdnative is really not very easy to use. Several issues have already mentioned this problem. And if I really want it to be compatible with multiple platforms, compiling is really a hassle.

**Comment by Calinou** [comment]
The Vulkan renderer in 4.0 will feature some kind of a compute API.

**Comment by clayjohn** [comment]
Vulkan supports compute shaders, and will support more easy access to the rendering pipeline if you want to do general purpose GPU computation.
