### ISSUE TITLE
Expose friction and bounce properties of bodies?

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#24415]
Is there a reason the `bounce` and `friction` properties of bodies are not exposed in the editor? As of now, you have to set those properties in a script, unless I am missing something.

**Comment by akien-mga** [comment]
They are part of the PhysicsMaterial now: https://docs.godotengine.org/en/latest/classes/class_physicsmaterial.html

Documentation needs to be updated though, I'll open an issue on godot-docs.

**Comment by akien-mga** [comment]
See godotengine/godot-docs#2058.
