### ISSUE TITLE
Viewport texture says node path is invalid (regression from 894163a)

### ISSUE THREAD

**Issue by GammaGames** [godotengine/godot#24412]
**Godot version:**
v3.1.alpha.official (alpha 3)

**OS/device including version:**
elementary OS 5.0 Juno

**Issue description:**
You can create a viewport texture by selecting the viewport, but when assigning it to the same viewport after the material was created the editor says ` Path to node does not point to a viewport`

**Steps to reproduce:**
![peek 2018-12-16 19-16](https://user-images.githubusercontent.com/7832163/50063052-b6b3b280-0167-11e9-8718-6a376e59c232.gif)

**Comment by GammaGames** [comment]
Darn, that's really annoying! I am using it on a mesh to make a breakable window, so a sprite probably wouldn't work

![image](https://user-images.githubusercontent.com/7832163/50065740-5fb4da00-0175-11e9-90e9-2a8cf92e7dca.png)

**Comment by JFonS** [comment]
You can workaround this by doing something similar to:

```
func _ready():
    mesh.material.albedo_texture = $GUI_Viewport.get_texture()
```

**Comment by GammaGames** [comment]
@bojidar-bg  I'm pretty sure I have `local_to_scene` enabled, it should be printing a different error if that wasn't enabled but I'll check again after work.

And thank you, I'll try that @JFonS !

**Comment by DavidSichma** [comment]
Regression from 894163a94537ceea0518095f6381aa98cf43b1cc.

When loading the ViewportTexture Godot follows the NodePath starting from the scene root. In your example it starts at "Work" and searches for a Node called "Viewport". This is the behavior you get from the first assignment.

However, reassigning the viewport does currently not work. If you select a new Viewport, Godot will instead generate a NodePath relative to the Node you are currently editing. This will be your "Glass". Godot will then search for the Viewport in the wrong place.

Right now you will have to create a new ViewportTexture every time you move the Viewport in the scene. Or just use code to avoid all headache-inducing problems like #19259. But clear the texture so the error goes away.

**Comment by GammaGames** [comment]
I ran into this thread while having the same issue, so I made a little script that assigns a material's `albedo_texture` to a viewport's path relative to the root node:

```gdscript
tool
extends Spatial

export(NodePath) var target_mesh
export(Array, int) var surfaces
export(Array, NodePath) var viewports

func _ready():
    set_textures()

func _process(_delta):
    if Engine.editor_hint:
        set_textures()

func set_textures():
    if !target_mesh.is_empty():
        var mesh = get_node(target_mesh)
        for index in surfaces.size():
            var mat = mesh.get_surface_material(surfaces[index])
            mat.albedo_texture = get_node(viewports[index]).get_texture()
```

The first export variable is the target mesh, the second is an array of surfaces (in case you want to set surface 0 and 2), and the third is an array of viewports (so you can set surface 1 to viewport1 and surface 2 to viewport2). I made it a tool script so it will update in the editor too.
