### ISSUE TITLE
Not working forum!

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#2441]
If you do not have a new working version of the site do not need to update it. There even was a working forum.
Making updates that make the situation worse than it was before this new trend?

**Comment by neikeq** [comment]
I think they are migrating it to the new site. I think it's already [accessible](http://godotengine.org). If something is not working just be patient.

**Comment by vnen** [comment]
@ret80, the new site was being set up (kinda still is), but now the forum is working fine and have the posts of the old forum.
