### ISSUE TITLE
-Wstrict-overflow in definition of 'unlikely' with GCC 4.8.x

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#24421]
**Godot version:**
Master (28b10ea)

**OS/device including version:**
Linux, GCC 4.8.x (Travis CI)

**Issue description:**
The following warning is raised when building `scons p=server tools=yes target=release_debug` on Travis CI (which uses GCC 4.8.x):
```
In file included from ./core/safe_refcount.h:35:0,
                 from ./core/string_db.h:35,
                 from modules/gdscript/gdscript_tokenizer.h:35,
                 from modules/gdscript/gdscript_tokenizer.cpp:31:
./core/cowdata.h: In member function 'void GDScriptTokenizerText::_advance()':
./core/typedefs.h:302:38: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
 #define unlikely(x) __builtin_expect(!!(x), 0)
                                      ^
./core/error_macros.h:162:7: note: in expansion of macro 'unlikely'
   if (unlikely((m_index) < 0 || (m_index) >= (m_size))) {                                                           \
       ^
./core/cowdata.h:149:3: note: in expansion of macro 'CRASH_BAD_INDEX'
   CRASH_BAD_INDEX(p_index, size());
   ^
```
Build log: https://travis-ci.org/akien-mga/godot/jobs/468953697

Not sure what to make of it, maybe you know @hpvb? Maybe GCC 4.8.x is just too old for this `__builtin_expect` feature, and we should put a version guard there?

**Comment by marxin** [comment]
> Not sure what to make of it, maybe you know @hpvb? Maybe GCC 4.8.x is just too old for this `__builtin_expect` feature, and we should put a version guard there?

Yes, please close this issues as the GCC 4.8 is really ancient.

**Comment by aaronfranke** [comment]
I'm getting this warning on the current master with GCC 7.4.0, repeated dozens of times.

```
In file included from ./core/cowdata.h:36:0,
                 from ./core/ustring.h:35,
                 from ./core/io/ip_address.h:34,
                 from ./core/io/ip.h:34,
                 from core/io/http_client.h:34,
                 from core/io/http_client.cpp:31:
./core/error_macros.h:186:3: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
   if (unlikely((m_index) < 0 || (m_index) >= (m_size))) {                                                               \
   ^
./core/cowdata.h:152:3: note: in expansion of macro 'CRASH_BAD_INDEX'
   CRASH_BAD_INDEX(p_index, size());
   ^~~~~~~~~~~~~~~
```

Maybe `cowdata.h` should be using `uint32_t` or `uint64_t` instead of `int`? I haven't actually tested this to see if it solves the problem or not, it's just an idea.

**Comment by marxin** [comment]
> Maybe `cowdata.h` should be using `uint32_t` or `uint64_t` instead of `int`? I haven't actually tested this to see if it solves the problem or not, it's just an idea.

Can you please attach a pre-processed source file (with `-E` option)? I can then take a look.
