### ISSUE TITLE
Freezing on GLES2

### ISSUE THREAD

**Issue by giovanigsilva** [godotengine/godot#24426]
**Godot version: 3.1 Alpha 3

**OS/device including version: Win64 - Intel HD Graphics

description: Freezing on change to GLES2

Steps to reproduce: Start new project and reopen in Gles2

on restart image loader godot freeze

![erro godot](https://user-images.githubusercontent.com/39173940/50101309-99372500-0209-11e9-9c91-40a6983cc75b.png)
![erro1](https://user-images.githubusercontent.com/39173940/50101310-99cfbb80-0209-11e9-8a3b-218544582d57.png)
![erro2](https://user-images.githubusercontent.com/39173940/50101312-99cfbb80-0209-11e9-8272-ad5aed682763.png)
![erro3](https://user-images.githubusercontent.com/39173940/50101314-99cfbb80-0209-11e9-85b3-ca0a1a3ae5e0.png)
![erro4](https://user-images.githubusercontent.com/39173940/50101317-9a685200-0209-11e9-888d-16f05badae51.png)
![erro5](https://user-images.githubusercontent.com/39173940/50101318-9b00e880-0209-11e9-8dcb-9380139cacb4.png)
![erro6](https://user-images.githubusercontent.com/39173940/50101320-9b00e880-0209-11e9-8f09-d506842f1ee1.png)

**Comment by Zireael07** [comment]
2D or 3D project? Try deleting ProceduralSky from the default_env.tres in your project.

**Comment by giovanigsilva** [comment]
> 2D or 3D project? Try deleting ProceduralSky from the default_env.tres in your project.

YEEEEEESSSSSSSSSSSSSSSSSSSS 

Only open the file default_env.tres in notepad 

[gd_resource type="Environment" load_steps=2 format=2]

[sub_resource type="ProceduralSky" id=1]
**[sub_resource type="" id=1]** <==============

[resource]

background_mode = 2
background_sky = SubResource( 1 )

**Comment by akien-mga** [comment]
Duplicate of #21551.
