### ISSUE TITLE
Labels no longer prints capital Cyrillic letters

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#24424]
**Godot version:**
cf07169

**OS/device including version:**
Win10

**Issue description:**
Labels cut first symbol when russian translation applied to them, it start happens recently, if you create a label and write "Привет" word it cut off it to "ривет". Buttons and other elements seems worked as before.

![image](https://user-images.githubusercontent.com/3036176/50091508-a27dbd00-021c-11e9-9f25-048e8d8b3fe2.png)

**Comment by akien-mga** [comment]
Recent `Label` change which might be involved: 922f2d613ff53d6de09e1756525226de06db6a9c
Can you check if it's reproducible in alpha 2 and alpha 3?

**Comment by Chaosus** [comment]
It was ok in alpha 3 and 2, it start happens only few commits ago - I try to find the regression commit now

**Comment by Chaosus** [comment]
Found ! This commit has a regression - https://github.com/godotengine/godot/pull/24385 CC @hpvb

**Comment by hpvb** [comment]
I'm getting different behavior on both a3 and master on Linux. But maybe I'm doing something wrong?

![image](https://user-images.githubusercontent.com/2591099/50094490-95a89b80-0213-11e9-844c-632d0dc5c3d1.png)

**Comment by Chaosus** [comment]
You forgot to add font supporting russian locale

**Comment by hpvb** [comment]
Ah yeah, I can reproduce it now. Thanks! :)

**Comment by akien-mga** [comment]
It seems not to be an issue with the first letter, but with all capital letters in Cyrillic.

See this [transliterated *Lorem Ipsum*](http://generator.lorem-ipsum.info/_russian):
![screenshot_20181217_160911](https://user-images.githubusercontent.com/4701338/50095555-1799c400-0216-11e9-906d-5c32794b2823.png)

Should be:
> Лорем ипсум долор сит амет, ин фастидии антиопам хис, ат дуо сцрипта оцурререт. Те цум яуот солута хендрерит. Нам еи модератиус интеллегебат, еу еос уллум персецути елояуентиам. Хинц перицула ратионибус сеа ад.

Ид вих оптион фабулас. Дуо еи лудус демоцритум, доминг цетеро аццумсан сит ех. Ид пробо облияуе инцоррупте яуо, еос аутем саперет ет. Яуо маиорум реферрентур ех.

**Comment by Chaosus** [comment]
Oh, that make this issue more horrible !

**Comment by hpvb** [comment]
It only happens in Labels, I've tried buttons and lineedits and everything shows up fine. There's probably a bug in Label that the more strict enforcement of wchar_t stuff that my PR did now triggers. I'll see if I can find what the problem may be.

**Comment by akien-mga** [comment]
BTW, if I enable the `uppercase` property on the label, all letters shown in the above screenshot are properly drawn as uppercase - including `Л`. The missing uppercase letters of the original string stay missing though. So it's not that it can't draw the uppercase letters per se, but it can't parse them properly.

**Comment by akien-mga** [comment]
Did some debugging, there seems to be an issue with the generate of the `WordCache *word_cache` in `Label`.
In `NOTIFICATION_DRAW`, `word_cache` is iterated over to draw chars, but at this point it's already missing the second char in this example:
```

(gdb) print text
$31 = {_cowdata = {_ptr = 0x75b9930 L"оЛорем"}}
(gdb) print xl_text
$32 = {_cowdata = {_ptr = 0x75b9930 L"оЛорем"}}
(gdb) print word_cache->char_pos
$29 = 0
(gdb) print word_cache->next->char_pos
$30 = 2
```
