### ISSUE TITLE
Automatically create instances of an object while importing 3d Scene

### ISSUE THREAD

**Issue by ArsCreativa** [godotengine/godot#2442]
When you import a full 3D scene with objects (meshes) with the same name, like "object", "object.001", "object.002", and so on, give the option to import the base object, and then instance the copies preserving position, scale and rotation of the individual instances, and not importing them as unique objects, regarding optimization.

**Comment by reduz** [comment]
This is exactly how it works, just tested it again to be sure.
If you are using Blender, keep in mind there is duplicate and duplicate linked, use the later and it will do as you described in Godot
