### ISSUE TITLE
HTML5 infinite loading (link error)

### ISSUE THREAD

**Issue by sargeantPig** [godotengine/godot#24425]
**Godot version:**
3.0.3, 3.0.6

**OS/device including version:**
Windows 10

**Issue description:**
I can export my project to html and it runs fine locally, but it does not run on my website. Instead it just shows the spiral loading screen infinitely.

On godot 3.0.2 I was able to export and get it running on my website but it would crash due to a known gridcontainer bug. 

I can link my site in a private message if needed to demonstrate (don't want to post it publicly currently).

The only error in the console of the browser is in the screenshot attached.
![linkerror](https://user-images.githubusercontent.com/16241051/50094113-4f027380-020a-11e9-8566-e9e20cbb79be.png)

**Comment by bojidar-bg** [comment]
Maybe the website crops the files somehow?

**Comment by sargeantPig** [comment]
Could be but that wouldn't explain why 3.0.2 export worked. 

The default loading bar comes up fully loads but then its just the circle loading animation forever.

**Comment by bojidar-bg** [comment]
> Could be but that wouldn't explain why 3.0.2 export worked.

Well, the 3.0.2 export might have been smaller, and thus not get cut.

Note that it is possible that the exported file wasn't fully uploaded, again getting truncated.

**Comment by eska014** [comment]
Is this still occurring? Has anyone else been able to reproduce this?

**Comment by sargeantPig** [comment]
Tried again a few days ago, seems to be working now. I have no idea what the problem was in the end.
