### ISSUE TITLE
Gray out nodes without scripts in the Connect Signal window 

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#24435]
![image](https://user-images.githubusercontent.com/15862731/50126490-18911c80-023b-11e9-8ece-8372f7ef0473.png)

It would be a nice QOL improvement, particularly for beginners if all the nodes in Connect Signal dialog window were grayed out, so as to more clearly see which nodes make any sense to select. Currently, if the user selects a node that doesn't possess a script, then an error window appears to say that this was a poor choice. Instead, those nodes shouldn't be selectable in the Connect Signal dialog.

**Comment by CowThing** [comment]
You can connect to functions that are part of the node and not part of the script, so a node doesn't need to have a script for connecting signals to it. In 3.1 alpha 3 (I don't know if it's in the stable version too), the menu will hide the "Make Function" button when you select a node without a script. So at least it's clear that you can't create a new function on the node. But maybe there could be some autocomplete or something so you know what functions are available in the node.

**Comment by akien-mga** [comment]
See also #15339 and #24316.

**Comment by KoBeWi** [comment]
Added in 3.2
