### ISSUE TITLE
GLES2 Android WorldEnvironment ProceduralSky glitch

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#24445]
**Godot version:**
Godot 3.1 master branch 1039ba9ffb8588e8b0abddaa753d270979147c23 at 2018-12-18

**OS/device including version:**
Tested on
Android 4.4.2 - MTK6592 - 1GB - GPU Mali 450 MP4 700Mhz - GL2.0
Android 4.4.2 - BCM23550 - 1GB - GPU VideoCore IV - GL2.0

GL_ARM_mali_program_binary
GL_ARM_mali_shader_binary
GL_ARM_rgba8
GL_EXT_blend_minmax
GL_EXT_debug_marker
GL_EXT_discard_framebuffer
GL_EXT_multisampled_render_to_texture
GL_EXT_robustness
GL_EXT_shader_texture_lod
GL_EXT_texture_format_BGRA8888
GL_KHR_debug
GL_OES_EGL_image
GL_OES_EGL_image_external
GL_OES_EGL_sync
GL_OES_compressed_ETC1_RGB8_texture
GL_OES_depth24
GL_OES_depth_texture
GL_OES_depth_texture_cube_map
GL_OES_get_program_binary
GL_OES_packed_depth_stencil
GL_OES_rgb8_rgba8
GL_OES_standard_derivatives
GL_OES_texture_npot
GL_OES_vertex_half_float

**Issue description:**
Seems like WorldEnvironment - ProceduralSky is glitchy.
This is observed on Android devices with real GLES2 GPU's (non GLES3)
Visible when using ProceduralSky from WorldEnvironment node.
Try also change WorldEnvironment -> RadianceSize to get different results as seen on example video

![worldenvironment_proceduralsky](https://user-images.githubusercontent.com/3224132/50152817-078ced80-02c5-11e9-84d0-75b9cbebcfef.gif)

**Example project:**
[g31-test-8.zip](https://github.com/godotengine/godot/files/2690337/g31-test-8.zip)
project used in demonstration visible on video above

Additional info for the attached project:
WorldEnvironment -> RadianceSize is set to 1024, try to change this value to get different results.
On android to look around and zoom, you can move camera with touch screen.
On pc you can look around and zoom with mouse.

**Comment by akien-mga** [comment]
See also #21551.

**Comment by avril-gh** [comment]
If you look at video in first post **untill the end** you will see there **something that looks like memory leak on bottom of skybox**

**Comment by QbieShay** [comment]
Possibly happening also in GLES3? https://github.com/godotengine/godot/issues/24442

**Comment by avril-gh** [comment]
seems fixed now.

However after this has been fixed i noticed drastic drop in FPS on android from 60 FPS to 9-10 FPS.
Anyway, closing this issue as fixed and perhaps will look at FPS in another issue.
