### ISSUE TITLE
GDScript: floating-point calculation inconsistent

### ISSUE THREAD

**Issue by tinyleolin** [godotengine/godot#24449]
**Godot version:**

Godot Engine v3.0.6.stable.official.8314054 (installed from Steam)

**OS/device including version:**

Windows 10 version 1803 (OS internal version 17134.471)

**Issue description:**

The gdcript calculation leads to inconsistent result.

**Steps to reproduce:**

**Minimal reproduction project:**

```
var v1 = Vector2(309.063385, 558.316772)
var v2 = Vector2(308.78009, 550.69281)
var v3 = Vector2(309.601715, 565.934143)
var a = Basis(
	Vector3(v1.x, v1.y, 1),
	Vector3(v2.x, v2.y, 1),
	Vector3(v3.x, v3.y, 1)
).determinant()
var b = v1.x * (v2.y - v3.y) - v2.x * (v1.y - v3.y) + v3.x * (v1.y - v2.y)
print("a: ", a, " b: ", b)
```
Output:
> a: 1.95459 b: 1.946248

Since `a` is calculated as `float`, I calculated `b` in c++ using type `float`, and it's
> b: 1.94604

So the value of `a` are wrong. Did I miss something?

**Comment by Zylann** [comment]
I calculated `b` using your script in Python and it's...
```python
>>> v1x = 309.063385
>>> v1y = 558.316772
>>> v2x = 308.78009
>>> v2y = 550.69281
>>> v3x = 309.601715
>>> v3y = 565.934143
>>> b = v1x * (v2y - v3y) - v2x * (v1y - v3y) + v3x * (v1y - v2y)
>>> b
1.9462443460151917
```

**Comment by tinyleolin** [comment]
After looking into the source code (version 3.0.6.stable), I found that real number (TYPE_REAL) is calculated as `double` (`b` in this case), while Vector2, Vector3, Basis are calculated as `float`(`a` in this case).
But `float` calculation still couldn't lead to `a`. It's off too much.

**Comment by bruvzg** [comment]
Difference is caused by swapped rows/cols in Basis class.

```c++
#include <cstdio>

int main() {

	float v1x = 309.063385;
	float v1y = 558.316772;
	float v1z = 1.0;
	float v2x = 308.780090;
	float v2y = 550.692810;
	float v2z = 1.0;
	float v3x = 309.601715;
	float v3y = 565.934143;
	float v3z = 1.0;

	//your calculation
	float det1 = v1x * (v2y * v3z - v3y * v2z) - v2x * (v1y * v3z - v3y * v1z) + v3x * (v1y * v2z - v2y * v1z);

	//what's happening inside Godot's determinant() function
	float det2 = v1x * (v2y * v3z - v2z * v3y) - v1y * (v2x * v3z - v2z * v3x) + v1z * (v2x * v3y - v2y * v3x);

	printf("%f %f\n", det1, det2);
}
```

Output (float):
```
1.946045 1.954590
```
Same code with double:
```
1.946244 1.946244
```
Excessively precise value to compare:
```
1.946244346015180135873251857346095438627549094323665457295646774582564830780029296875b0
```

Mathematically determinant should be the same, but looks like it affects `float` precision loss somehow.

**Comment by tinyleolin** [comment]
OK, thanks @bruvzg . I didn't notice that their calculation orders are different.
