### ISSUE TITLE
Copy/Cut selection inside tilemap breaks autotiles

### ISSUE THREAD

**Issue by stormi** [godotengine/godot#24440]
**Godot version:**
cf0716952db45acf7d7430552f2759c57e0d876e

**Issue description:**
In a tilemap that uses autotiles (several autotiles from the same tileset, if that matters), when I select parts of the tilemap with Ctrl + B, then Copy or Cut the selection, the result is very different from what I selected. Every tile is replaced by something else.

If I check "disable autotiles", then the outcome is a bit different (not the same tiles) but still garbled.

Screencast of the issue: https://matrix.org/_matrix/media/v1/download/matrix.org/zEjVoDNRNzJBWngxhhcCWybz

**Minimal reproduction project:**
Will try to provide one IF it proves difficult to reproduce.

**Comment by akien-mga** [comment]
CC @MarianoGnu @guilhermefelipecgs @YeldhamDev
