### ISSUE TITLE
load & preload scene path works in windows but crashes android 

### ISSUE THREAD

**Issue by NoodleSushi** [godotengine/godot#24443]
Godot Engine v3.0.6.stable.offical.8314054

Whenever I use:
```
var TabScene = load("res://SCENES/ChoiceTab.tscn")
var TabScene = preload("res://SCENES/ChoiceTab.tscn")
const TabScene = load("res://SCENES/ChoiceTab.tscn")
const TabScene = preload("res://SCENES/ChoiceTab.tscn")
```
It runs nicely on windows.
However, when running in android, it alternately switches from the black screen and splash screen then crashes and ends the app.
The path is correctly case sensitive, yet problems occur, What should I do?

**Comment by Zireael07** [comment]
From your report, I suppose the use of var vs const doesn't affect anything?

Also, can you load ChoiceTab.tscn on Android by itself? Maybe it's bugged in some way or your renderer can't handle it? (BTW what is your Android device?)

**Comment by eon-s** [comment]
First, all your files and directories are named with that style, respecting uppercase and lowercase? If not, it should not work when exporting to windows too (will work only on the editor).

You can use logcat to see why it crashes too.

**Comment by NoodleSushi** [comment]
I ran a new project and did the same thing and it seems to be working, There must be something that triggers the problem. Gonna close for now and investigate further, if problems still occur then I'll reopen the issue.

**Comment by NoodleSushi** [comment]
Problem resolved, need to add_child() the instanced child before modifying the instanced child.
