### ISSUE TITLE
Godot crashes when reimporting svg with high enough scale value

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#24455]
**Godot version:**
v3.1.alpha.calinou.0cff752

**OS/device including version:**
Linux 64 bits
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Ivybridge Mobile 

**Issue description:**
Reimporting an svg asset while setting the scale high enough crashes the engine

**Steps to reproduce:**
- Click on an svg file in the filesystem dock
- Click on the import dock
- Set the svg/scale property to a high value (in my case it was 20)
- Click on ReImport
The progress bar shows up and Godot crashes after a while

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by noidexe** [comment]
I'm at a Global Game Jam site so I can't build from source right now but it still happens with the latest build from Calinou ( 6e60070 )

I've attached the svg file I'm using. It probably fails due to trying to generate a huge texture.


```
ERROR: create: Index p_height - 1=22449 out of size (MAX_HEIGHT=16384)
   At: core/image.cpp:1457
ERROR: shrink_x2: Condition ' data.size() == 0 ' is true.
   At: core/image.cpp:1210
libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data
ERROR: _lossless_pack_png: Method/Function Failed, returning: PoolVector<uint8_t>()
   At: drivers/png/image_loader_png.cpp:308
ERROR: _lossless_unpack_png: Condition ' len < 4 ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:257
ERROR: _load_data: Condition ' img.is_null() || img->empty() ' is true. returned: ERR_FILE_CORRUPT
   At: scene/resources/texture.cpp:600
```


[drawing.zip](https://github.com/godotengine/godot/files/2799660/drawing.zip)
