### ISSUE TITLE
Graph node headers look weird in StateMachine nodes

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#24458]
**Godot version:**
3c999ae

**Issue description:**
When "Use Graph Node Headers" is enabled, the headers in StateMachine nodes look weird. They shouldn't appear in them at all.
![screenshot at 2018-12-18 16-32-27](https://user-images.githubusercontent.com/30739239/50177299-8ef45400-02f9-11e9-9524-3c0a888a61e9.png)

**Comment by mateusfccp** [comment]
@YeldhamDev What is exactly this StateMachine? I couldn't find a node with this name.

**Comment by YeldhamDev** [comment]
@mateusfccp It's a resource for the `AnimationTree` node.

**Comment by maykillmore** [comment]
Is this issue still open?

**Comment by YeldhamDev** [comment]
@maykillmore I didn't get another response from @mateusfccp, so it's likely still up for grabs.

**Comment by mateusfccp** [comment]
Sorry, I'm currently racking my brains on a issue I took, sorry about being silent. @maykillmore, feel free to take this issue!

**Comment by akien-mga** [comment]
Fixed by #24664.
