### ISSUE TITLE
Saving path should default to the currently opened folder in the filesystem dock

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24469]
**Godot version:**
11d7738

**Issue description:**
When saving a new scene, the save scene dialog defaults to the project root.
As the project grows big, it takes a lot of clicks for the user to reach the desired point of save.

**Proposal**
When saving, Godot should default to the currently opened folder in the filesystem dock as it is most likely that if you have a folder opened when creating a new scene you are working in that directory. At least, in my experience.

**Comment by KoBeWi** [comment]
You can create most of stuff directly from filesystem dock (as of 3.1), so if it's only about scenes, #26377 is related.

**Comment by KoBeWi** [comment]
With #31398 merged, you can now create scenes from FileSystem doc. Same with resources and scripts, so you can create from there pretty much everything (which means you don't ever need to open the file manager to pick a location. Ever). Is that enough to close this issue? @QbieShay

**Comment by QbieShay** [comment]
Yup, sounds good for me!
