### ISSUE TITLE
Godot should have more "Artist friendly" naming in the Particle System.

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#24468]
Godot version 3.0.6

Even though I have been working with Godot for quiet some time now, I still find my self looking for the right function to tweak in the Particle system material. I think this is due to the naming of some of the functions. For a programmer this might not be a problem but for some of us helpless artists it's not always easy to understand. And I think for newcomers it could be confusing. In Unity all the names just makes sense to me and I can .

For instance in Godot it's called: **"Angular Velocity"**
Where in Unity it's simply called **"Rotation over Lifetime"** 

In Godot you have a check mark box that says: **"Fract Delta"** with no help info?
There's also a **"Flatness"** under spread and I have no idea what it does.

And on the top of my head I wouldn't know what the difference is between Radial and Tangential acceleration.

**Comment by CptPotato** [comment]
I agree that things should be described properly but I personally prefer the more technical terms like `Angular Velocity`. They are more precise and leave less room for misinterpretation.

**Comment by TheDuriel** [comment]
See https://github.com/godotengine/godot-docs/issues/2359 and https://github.com/godotengine/godot/issues/27878

**Comment by akien-mga** [comment]
Closing as superseded by #27878.
