### ISSUE TITLE
Godot 3.1 Alpha 3 AnimationTree regression: connecting more than 2 nodes no longer works

### ISSUE THREAD

**Issue by rszibele** [godotengine/godot#24473]
**Godot version:**
Godot 3.1 Alpha 3

**OS/device including version:**
Kubuntu 18.10

**Issue description:**
Connecting more than 1 animation node to other nodes (Transition, Blend, etc.) inside an AnimationTree with an AnimationNodeBlendTree as root tree no longer works.

It used to work in Godot 3.1 Alpha 2 and Alpha 1.

![bug](https://user-images.githubusercontent.com/1387224/50221206-56ea2100-038c-11e9-87da-7ab4c1408d41.png)

**Steps to reproduce:**
I have added the minimal reproduction project below, so you don't have to do this, but here's how I set it up:

1. import object which has an animation into Godot
2. create a new inherited scene
3. add an AnimationTree node
4. set the root tree of the AnimationTree to AnimationNodeBlendTree
5. add an AnimationNode  and set the animation 
6. add another AnimationNode and set the animation to another animation
7. add a TransitionNode and set the inputs to 2
6. connect both AnimationNodes to the TransitionNode

Connecting the second AnimationNode to the TransitionNode will not work.

**Minimal reproduction project:**
The AnimationTree is in Cube.tscn, try to connect "Animation 2" (Jump) to "Transition".

[AnimationTreeTransition.zip](https://github.com/godotengine/godot/files/2694878/AnimationTreeTransition.zip)

**Comment by akien-mga** [comment]
Reopening as #24546 was reverted in #24767.

**Comment by volzhs** [comment]
changing name on Animation node is not working either.
First created Animation node works but not second one.
