### ISSUE TITLE
Godot 3.1 Alpha 3 - NetworkedMultiplayerENet Work but ( does not display a message: UDP Connection listening on port XXXXX  )

### ISSUE THREAD

**Issue by giovanigsilva** [godotengine/godot#24479]
**Godot version:**
3.1 Alpha 3

**2D and 3D**

**OS/device including version:**
Windows 64

**Issue description:**
`var host  = NetworkedMultiplayerENet.new()`
don't start a new Server Create 

**Steps to reproduce:**
```gdscript
var host    = NetworkedMultiplayerENet.new()
host.TRANSFER_MODE_UNRELIABLE_ORDERED
host.COMPRESS_FASTLZ
host.set_transfer_mode(1)
host.set_bind_ip("127.0.0.1")

err = host.create_server(3040, 50) <=========DOESN'T START THE SERVER IN 3.1 ALPHA 3
if (err!=OK):
	$Container/conexao.text += " - erro Server: " + str(err)
	return
else:
	$Container/conexao.text += " - no error server: " + str(err)
```

**Comment by AlexAndDraw** [comment]
Are you getting any error message?

**Comment by AlexAndDraw** [comment]
> host.TRANSFER_MODE_UNRELIABLE_ORDERED
> host.COMPRESS_FASTLZ

This isn't doing anything

You haven't set a network_peer, 

```
var host = NetworkedMultiplayerENet.new()
host.create_server(port, max_players)
get_tree().set_network_peer(host)
```

**Comment by AlexAndDraw** [comment]
The issue seems to be in set_bind_ip. If you're trying to connect to your own machine, maybe your IP has since changed (so 192.168.1.1 is invalid)? If you're trying to connect to your own machine, you can use 0.0.0.0 or 127.0.0.1 for localhost. I can't connect on 192.168.1.1 but I can on 192.168.0.106

(If you're using windows, load up command, type in ipconfig, and then you can check if your ipv4 address is 192.168.1.1 or something slightly different)

**Comment by giovanigsilva** [comment]
> The issue seems to be in set_bind_ip. If you're trying to connect to your own machine, maybe your IP has since changed (so 192.168.1.1 is invalid)? If you're trying to connect to your own machine, you can use 0.0.0.0 or 127.0.0.1 for localhost. I can't connect on 192.168.1.1 but I can on 192.168.0.106
> 
> (If you're using windows, load up command, type in ipconfig, and then you can check if your ipv4 address is 192.168.1.1 or something slightly different)

The same code function in 3.0.6, only reopen in 3.1 alpha 3 - GLES3 or GLES2

**Comment by giovanigsilva** [comment]
only does not display a message listening to door

**Comment by Chaosus** [comment]
I think you trying to get access to system port which is commonly closed for security reasons, try ports with bigger indexes - for example 55669

**Comment by giovanigsilva** [comment]
> Try ports with bigger indexes - for example 55669(at least it works for me, as I making game with multiplayer capabilities)
> 
> > The same code working in 3.0.6, only reopened my project in 3.1 alpha 3 - GLES3 or GLES2
> 
> Yeah, 3.1 brings a lot of changes to network subsystem..

was ok, only doesn't display message: UDP Connection listening on port XXXXX )  Thank you
