### ISSUE TITLE
Atlas Texture with margin setting cause error in editor.

### ISSUE THREAD

**Issue by harrisyu** [godotengine/godot#24470]
In 3.1 daily build, when you hover mouse on some atlas texture and with margin setting ( I using texture packer plugin),editor will print message like these:

scene/resources/bit_mask.cpp:142 - Index y=73 out of size (height=73)

after some investigations, I found out that these line may cause the problem:

https://github.com/godotengine/godot/blob/26058376aa180f70e152070b3b69272287a710a8/scene/resources/texture.cpp#L1090

I am new to godot, but here I think we don't need to add margin.position.

**Comment by akien-mga** [comment]
CC @reduz who wrote it in 34e58fd831.

**Comment by harrisyu** [comment]
I am not sure what p_x and p_y mean, if it's relative offset inside the margin area, then it will be:
	int x = p_x + region.position.x - margin.position.x;
	int y = p_y + region.position.y - margin.position.y;

**Comment by harrisyu** [comment]
This is my fix:
bool AtlasTexture::is_pixel_opaque(int p_x, int p_y) const {

	if (!atlas.is_valid())
		return true;

	int x = p_x + region.position.x - margin.position.x;
	int y = p_y + region.position.y - margin.position.y;

	// margin edge may outside of atlas
	if (x < 0 || x >= atlas->get_width() ) return false;
	if (y < 0 || y >= atlas->get_height() ) return false;

	return atlas->is_pixel_opaque(x, y);
}

Now I need to learn git ...

**Comment by akien-mga** [comment]
> Now I need to learn git ...

This may be useful: http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html
As well as http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html and https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md
