### ISSUE TITLE
Android export issue with nightly builds

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2448]
Running Windows 7 64-bit
godot version 2.0 - 32 and 64 bit
September 6, 2015 at 10:35 - UNOFFICIAL GODOT ENGINE BUILDS

lib name is "libgodot_android.so" location: /lib/armeabi/

Tested on devices:
- Samsung p-605
- Galaxy s5

![bug_android](https://cloud.githubusercontent.com/assets/4741886/9721121/e6aa025e-5595-11e5-8fac-d639c2edd5a0.PNG)

**Comment by okamstudio** [comment]
i have no idea what that is, are you exporting for arm?

On Mon, Sep 7, 2015 at 2:55 PM, AlexHolly <notifications@github.com> wrote:

> Running Windows 7 64-bit
> godot version 2.0 - 32 and 64 bit
> September 6, 2015 at 10:35 - UNOFFICIAL GODOT ENGINE BUILDS
>
> lib name is "libgodot_android.so" location: /lib/armeabi/
>
> Tested on devices:
>
>    - Samsung p-605
>    - Galaxy s5
>
> [image: bug_android]
> <https://cloud.githubusercontent.com/assets/4741886/9721121/e6aa025e-5595-11e5-8fac-d639c2edd5a0.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2448>.
>



-- 

*OkamStudio*

**Comment by AlexHolly** [comment]
yes, i think otherwise there would be a "x86" folder in lib

**Comment by AlexHolly** [comment]
I also found this 
![buggg](https://cloud.githubusercontent.com/assets/4741886/9770188/fed934cc-572e-11e5-9f75-4f892f6a92ff.PNG)

I also tried with "September 8, 2015 at 19:17- UNOFFICIAL GODOT ENGINE BUILDS"

I tried to put the "libgodot_android.so" into the root folder nothing changed.

I use Java8 - jarsigner, so when the jarsigner would be the problem i couldn't install the apk right?
Tested to export x86 and arm nothing changed.

**Comment by AlexHolly** [comment]
So right now it works with  "UNOFFICIAL GODOT ENGINE BUILDS" from 22.09

**Comment by akien-mga** [comment]
Looks like it was resolved in the end.

> I cant install the APK when i disable the "Enable Debugging" mode i think it has no function anyway.
Is it possible to hide the "Enable Debugging" mode on Android export?

The option makes it possible to use the debug template instead of the release one. If it does not work in release mode, I suspect that your release template is broken somehow.
