### ISSUE TITLE
Static type not detected with new()

### ISSUE THREAD

**Issue by mashumafi** [godotengine/godot#24493]
**Godot version:**
3.1.alpha-3

**OS/device including version:**
Android (code that works in windows does not work 

**Issue description:**
gdscript types cannot detect static types
it occurs in both member and function variables

**Steps to reproduce:**
```
File f := File.new() # fails with "Parser Error: Assigned value does not have a set type, variable type cannot be inferred."
File f : File = File.new() # works
```
Had similar issues with File, Directory, Tween, AnimationPlayer2D, SpriteFrames when using .new()

**Comment by mashumafi** [comment]
Also, if I enabled warnings as error is get the following
"Parser Error: The method '_init' is not present on the inferred type 'GDScriptNativeClass' (but may be present on a subtype). (warning treated as error)"
These errors probably go away if I disable debug settings for gdscript but if settings on it works on windows it should be same experience on android.

**Comment by ricardoalcantara** [comment]
I don't know if it is the same problem but I also had problem with `onready var`
such as:

`
onready var _tween: = Tween.new()
`

It's also break, but **only on Android** device

`
**01-15 16:25:15.329  9241  9272 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
01-15 16:25:15.329  9241  9272 E godot   :    At: core/io/resource_loader.cpp:202:load() - Condition ' err != OK ' is true. returned: RES()
01-15 16:25:15.329  9241  9272 E godot   : **ERROR**: Failed loading resource: res://Main.tscn
01-15 16:25:15.329  9241  9272 E godot   :    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
01-15 16:25:15.329  9241  9272 E godot   : **ERROR**: Failed loading scene: res://Main.tscn
01-15 16:25:15.329  9241  9272 E godot   :    At: main/main.cpp:1727:start() - Condition ' !scene ' is true. returned: false
01-15 16:25:18.953  9241  9272 E godot   : **SCRIPT ERROR**: Parse Error: Assigned value does not have a set type, variable type cannot be inferred.
01-15 16:25:18.953  9241  9272 E godot   :    At: res://Main.gdc:4:GDScript::load_byte_code() - Parse Error: Assigned value does not have a set type, variable type cannot be inferred.
01-15 16:25:18.953  9241  9272 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
01-15 16:25:18.953  9241  9272 E godot   :    At: modules/gdscript/gdscript.cpp:784:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
01-15 16:25:18.953  9241  9272 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
01-15 16:25:18.953  9241  9272 E godot   :    At: modules/gdscript/gdscript.cpp:2135:load() - Condition ' err != OK ' is true. returned: RES()
01-15 16:25:18.953  9241  9272 E godot   : **ERROR**: Failed loading resource: res://Main.gdc
01-15 16:25:18.953  9241  9272 E godot   :    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
01-15 16:25:18.953  9241  9272 E godot   : **ERROR**: res://Main.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Main.gd
01-15 16:25:18.953  9241  9272 E godot   :    At: scene/resources/scene_format_text.cpp:439:poll() - res://Main.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Main.gd**
`

**Comment by aaronfranke** [comment]
File f : File = File.new() # works

I thought you needed to start with `var` on GDScript?
