### ISSUE TITLE
Possible redundant data in NetworkedMultiplayerENet::put_packet(const uint8_t *p_buffer, int p_buffer_size)

### ISSUE THREAD

**Issue by shinyclaw** [godotengine/godot#24496]
Each ENet packet contains 12 additional bytes which maybe can be omitted (at least first 8):

```
ENetPacket *packet = enet_packet_create(NULL, p_buffer_size + 12, packet_flags);
encode_uint32(unique_id, &packet->data[0]); // Source ID
encode_uint32(target_peer, &packet->data[4]); // Dest ID
encode_uint32(packet_flags, &packet->data[8]); // Dest ID
copymem(&packet->data[12], p_buffer, p_buffer_size);
```

When we receive ENET_EVENT_TYPE_RECEIVE callback, we can get the incoming and outgoing ID from the ENet event directly like this:

event.peer->incomingPeerID and event.peer->outgoingPeerID

So maybe we can omit SourceID and Dest ID? It is only my guess... Btw. the last comment should be fixed to Flags :)

**Comment by Faless** [comment]
@shinyclaw that small header is used to allow the server from relaying messages between peers (p2p meshes are not supported yet), so in some occasions a packet will be received from peer 1 (the server), but the source ID will be another peer, and in some occasions a packet will be received by the server, but the Dest ID will not be 1. Flags too are used for relaying, and they could be removed and read from the packet info instead.
