### ISSUE TITLE
Collision Shape "Shape" properties produce error when trying to keyframe in their embedded inspector

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#24491]
**Godot version:**
master - commit f2e7a650c7c23a7ec5c9dbf43ef605885e26d60e

**OS/device including version:**
OSX

**Issue description:**
I tried to add a keyframe for the shape extents on a CollisionShape2D

**Steps to reproduce:**
1. Open minimal reproduction project and open up main.tscn
2. Select the AnimationPlayer node
3. Select the 'New Anim' animation if not already selected
4. Select the CollisionShape2D node
5. Click to open the Rectangle tab to modify its extents if not already visible
6. Click the key icon for the extents to add a keyframe to the animation player

Expected: Keyframe added for extents on the animation player
Actual: No key frame is added and I get an error in output
`core/object.cpp:1241 - Error calling method from signal 'property_keyed_with_value': 'EditorInspector::_property_keyed_with_value': Method expected 3 arguments, but called with 2.`

**Minimal reproduction project:**
[animation_player_extents.zip](https://github.com/godotengine/godot/files/2697023/animation_player_extents.zip)

Note: Interestingly enough, it is possible to add the keyframe mentioned above by doing the following:
1. Do steps 1 - 4 from the above repro
2. Click the drop down menu for the Rectangle shape and click Edit
3. Click the key icon for the extents to add a keyframe to the animation player

^ This does as expected.

**Comment by KoBeWi** [comment]
Same issue as #24690, fixed in 3.1
