### ISSUE TITLE
Quick projects setup for prototyping

### ISSUE THREAD

**Issue by shackra** [godotengine/godot#2450]
Godot is great for prototyping an idea and see how it works. I was thinking that for speeding up a little the setup of creating a new project in Godot a button should be added, and when pressed, will fill the _project path_ (my guess is to let the user configure Godot to use a predefine root path for this kind of projects) and _project name_ automatically and leave the user ready with a new project for prototyping.

**Comment by AlexHolly** [comment]
Templates would be nice 2D or 3D with a default scene setup and disabled filters on 2D.

I know that it is quickly done but a newcomer wants to press start and see the game window and not an error...

**Comment by shackra** [comment]
This issue have no labels yet, and is not implemented in master yet.

**Comment by akien-mga** [comment]
How would you fill the project name automatically? "New Project \<incremented number\>"?

**Comment by bojidar-bg** [comment]
The way Code::Blocks handles this is by prefilling a root path, then appending the project name to it.

**Comment by akien-mga** [comment]
@bojidar-bg That seems trivial yes, but the OP proposed both a default *project path* and *project name*, so the latter would need to have some scheme to be generated too. Though IMO having just the feature for a default project root path would be enough, I don't see the point in generating project names.

**Comment by vnen** [comment]
There's already a default project path on editor settings, though it's empty by default.

**Comment by aaronfranke** [comment]
We could probably set the default project path to something. I think most people would be fine with `~/Documents/GodotProjects` or similar. Then creating a test project just requires writing the name.

**Comment by KoBeWi** [comment]
Sooo, as of 3.1, we have:
- default project name
- default project directory (on Windows it's documents)
- a button to create an empty directory for the project

So we can create a new project with just 3 clicks and 0 typing, although not sure how naming conflicts are handled. But seeing how name field gets automatically focused, it's just a matter of mashing some random letters. Project presets are basically templates, so I guess that's all to close this issue.
