### ISSUE TITLE
ERROR when calling open_encrypted_with_pass()

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#24505]
Win10 64-bit e8cdbf9

Example Project: [3.1 File Error.zip](https://github.com/godotengine/godot/files/2699598/3.1.File.Error.zip)

I found that when calling `open_encrypted_with_pass()` using the wrong encryption key I get this error.  So far I haven't noticed this with any other types of file access failures.

![image](https://user-images.githubusercontent.com/13004169/50295620-22a45c80-0481-11e9-8e1d-690d90a8f27c.png)

I also wonder if it might be better if it had its own error code, rather than reporting it as corrupted file.

**Comment by Chaosus** [comment]
Yeah, more clear error message is welcome

**Comment by avencherus** [comment]
Should it error?  Other file errors only pass back error codes.

**Comment by getmorepc** [comment]
This seems like the desired outcome from using the wrong encryption key, couldn't you build an exception that writes the error to the log and call it a day?
