### ISSUE TITLE
Update Bullet physics source

### ISSUE THREAD

**Issue by OBKF** [godotengine/godot#24514]
**Godot version:**

3.1

**Issue description:**

I have a problem with the Generic6DOFJoint which is related to a [bug](https://github.com/bulletphysics/bullet3/issues/2000) in Bullet physics that was fixed in [this pull request](https://github.com/bulletphysics/bullet3/pull/1999) (Merged 26 days ago). So I am wondering if there is a possibility to update the Bullet source or at least how can I do it in my own fork.

**Comment by OBKF** [comment]
So basically it's a matter of copying the content of "src" folder from Bullet's repo to the "bullet" folder in Godot's "thirdparty" -> recompile -> make sure everything works?

**Comment by dreamsComeTrue** [comment]
> So basically it's a matter of copying the content of "src" folder from Bullet's repo to the "bullet" folder in Godot's "thirdparty" -> recompile -> make sure everything works?

Yeah, it's pretty much like that. Although - it's worth notice, to check if whole physics engine didn't collapse after upgrade - they may break public API.

**Comment by OBKF** [comment]
I am planning on doing that tonight, fingers crossed.

**Comment by OBKF** [comment]
I have updated Bullet source, and everything looks fine for now, I need to do more testing before making a PR.

**Comment by AndreaCatania** [comment]
Please tag me when you do the PR so I can review it
