### ISSUE TITLE
StyleBoxFlat on Android GLES2 not rendering

### ISSUE THREAD

**Issue by iRadEntertainment** [godotengine/godot#24515]
**Godot version:**
Godot 3.1alpha2

**OS/device including version:**
Project exported on Android 4.4.2 with export templates built on Windows7

**Issue description:**
Whatever node can use themes or styles with StyleBoxFlat, doesn't render at all

**Steps to reproduce:**
-Build Godot3.1alpha2 on Windows7
-Build export templates for android
-Create a GLES2 project with a button or a progress bar and apply a StyleBoxFlat to this node (with color and everything)
-Export and install on an Android device that uses GLES2
StyleBoxFlat works when launched in the editor, on the Android device doesn't show the fill or the border

**Comment by akien-mga** [comment]
Bump, is this reproducible in 3.1 beta 6 or later?

If so, can you attach a project that triggers the issue?

**Comment by iRadEntertainment** [comment]
*SOLVED*
With the beta6 build the issue dissolved. Just tested on my Samsung Note 2
