### ISSUE TITLE
Cyclical dependency detected where it should be fine

### ISSUE THREAD

**Issue by mashumafi** [godotengine/godot#24511]
**Godot version:**
3.1.alpha3

**OS/device including version:**
Windows but probably others

**Issue description:**
I am using class_name to create some global scripts. In a child script I have an inner class. I am able to extend that inner class but for functions that depend on the child class class_name fail to be parsed. The below code won't work unless I remove the return type from both `get_neighbor()` or remove `get_neighbor()` override from `Grid`. I think it should work fine since I am able to inherit `Cell.Parent` in `Grid`.

**Steps to reproduce:**
```
# cell.gd
extends Node
class_name Cell

class Parent:
	extends Node
	func get_neighbor(x: int, y: int)-> Cell:
		return null

# grid.gd
extends Cell.Parent
class_name Grid

func get_cell(x: int, y: int)-> Cell:
	return null
```

**Comment by Zireael07** [comment]
Duplicate/related to #21461 ?

**Comment by akien-mga** [comment]
Same issue as #21461 indeed.
