### ISSUE TITLE
No input events for rudder pedals on Linux

### ISSUE THREAD

**Issue by MrMinimal** [godotengine/godot#24526]
**Godot version:**
3.1

**OS/device including version:**
Linux

**Issue description:**
Godot does not recognize joysticks/gamepads with axis only (e.g. rudder pedals). As a result no input events reach the game logic. Happens when compiling with both `udev=yes` and `udev=no`.

**Code which produces this bug:**
https://github.com/godotengine/godot/blob/master/platform/x11/joypad_linux.cpp#L342

(reformatted with values from a gamepad vs my rudder pedals):
![cleanedeventhandling](https://user-images.githubusercontent.com/8739690/50340025-8b3f1800-0519-11e9-8c1c-ac77ae6f2c62.png)

The offending line discards any events coming from joysticks that don't have any buttons(`test1`).
**Removing the line fixed the problem for me**, but is only a temporary solution.

**Steps to reproduce:**
1. Plug in a joystick without any buttons, only axis
2. Have a GDScript with an input function like so:
```
func _input(event):
    print(event)
```
3. Move axis on joystick
4. Observe **no** InputEventJoypadMotion events occuring

**Comment by MrMinimal** [comment]
I would like to hand in a PR, but this comment is problematic:
```
//check if the device supports basic gamepad events, prevents certain keyboards from
//being detected as joypads
```
What are the edge cases the boolean logic is supposed to prevent?
I would have to rewrite the logic in that line, but how do I make sure all edge cases are still covered?

**Comment by akien-mga** [comment]
CC @Hinsbart

**Comment by groud** [comment]
Have you checked if it was detected with another software ? Something like jstest ?
To be sure the problem does not come from a lack of drivers on your side.

**Comment by MrMinimal** [comment]
@groud Yes I did, that's how I found the offending source code in the first place. I updated the issue to reflect that the issue is fixed by commenting out the linked line.
But that won't do for a PR, gotta find the edge cases to write proper handling logic.

**Comment by KingKone** [comment]
Same here: 
Godot on Windows detects my RC-controller 
Godot on Linux does not see it.
Also my controller has only axis, no buttons.
@timower nice project you got there

**Comment by supertin** [comment]
+1 on Linux. I've currently got CH rudder pedals (3 axis, 0 buttons) as /dev/js0 and a CH throttle quad (6 axis, 12 buttons) as /dev/js1. As a long time Linux user, I immediately assumed "Device 0" meant "js0", and spent about half an hour getting increasingly frustrated with why Godot was refusing to see my button presses on "Device 1" (answer - it didn't exist).

This issue would also effect things like standalone handbrake levers, higher end standalone driving pedals, custom devices for flight, train or industrial machinery simulation, etc.

**Comment by akien-mga** [comment]
CC @madmiraal, though I doubt it's easy to debug/fix without hardware to test on.

**Comment by akien-mga** [comment]
Could you test the current master branch (with #40591) or nightly builds from tomorrow or later (https://hugo.pro/projects/godot-builds/) to confirm the fix? If it didn't work as expected, this issue should be reopened.
