### ISSUE TITLE
Add key button not function collectly when using bezier curve.

### ISSUE THREAD

**Issue by harrisyu** [godotengine/godot#24523]
**Godot version:**
Godot3.1.alpha.custom_build.6cdcde7

**Issue description:**
In animation editor, if you choose "beizer curve" mode when press add key button, after then every time you click add key button, it will ask you again if you want to use "beizer curve" mode, and it will add same track again and again.

**Steps to reproduce:**

1.add a node2d node to scene.
2.add an animationPlayer node.
3.create a new animation.
4,select the node2d node, click add key button beside position.
5.choose "beizer curve" mode.

and then, if you try to add key by clicking the button, it will ask your again the question, and create key on new track.

![add key button](https://user-images.githubusercontent.com/4844464/50336403-1552a500-0549-11e9-9533-c81e3b5dba2c.gif)

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by creikey** [comment]
This is still reproducible in the current master branch in commit a46b8e1ebfa0ef97c1fba046c6f2d975973c9401

**Comment by jamis-leblanc** [comment]
still an issue ... stil a pain to add key manually

**Comment by akien-mga** [comment]
Still reproducible in the current master branch.
