### ISSUE TITLE
Godot 3.1-alpha 3 regression: Viewport size override is not working well (related with Camera2D and idle_process_internal).

### ISSUE THREAD

**Issue by simpleyo** [godotengine/godot#24525]
Godot version:
Godot 3.1 alpha 3
Godot 3.1 alpha 4

OS/device including version:
Windows 7 Ultimate x64

Issue description:
If you run the project TestViewport in version alpha 3 you get VERY different results than you get with version alpha 1. I think the correct result is the one you get with alpha 1 so alpha 3 must have a bug.

This is what happens when **set_size_override** is used, in the project TestViewport, to duplicate the size of the viewport:

![testviewport](https://user-images.githubusercontent.com/29863675/50347006-791ea300-0534-11e9-84ee-36728fb0dee6.gif)
The window above shows what happens in the alpha 1 version.
The window below shows what happens in the **alpha 3 version**.

**Minimal reproduction project:**
What is done in the project is to periodically change the size of the viewport using set_size_override.
[TestViewport.zip](https://github.com/godotengine/godot/files/2702549/TestViewport.zip)

**Comment by simpleyo** [comment]
The problem is related with the Node variable data.idle_process_internal. In the alpha 1 version that variable is true for Camera2D but in the alpha 3 version that variable is false which means that _update_scroll is not called in Camera2D :: _ notification. In my case, I've fixed it by calling the camera.force_update_transform() function after calling viewport.set_size_override. It can be verified that adding those calls to the test project the behavior of the alpha3 / 4 version is again the same as that of the alpha 1 version.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by reduz** [comment]
Nope, seems fixed on head. Closing.
