### ISSUE TITLE
Edit multiple track in animation curve editor.

### ISSUE THREAD

**Issue by harrisyu** [godotengine/godot#24520]
By now in Godot 3.1 we can only edit 1 track in the animation curve editor, it's very often that we need to tweak multiple keys on different track at the same time.
So this is a feature request for make it possible to edit multiple tracks in the curve editor.

**Comment by JustusPan** [comment]
VOTE for this feature. And I think it's one of the most important enhancements for current animation system. 
For example, tuning the easing curve of one action of your charactor is a very common manipulation for an action game. It's especially important for those charactor who was made by a 'cutout' way, like shown as below picture.  
![cutout charactor](https://raw.githubusercontent.com/JustusPan/resource/master/images/multiple_anim_track.jpg)  
Now if I want to change trend of the first keyframe interception to 'easeOut' style, there is only a editor for single keyframe left for us. Therefore we have to 'selecting one keyframe and moving curve' repeatly for many times. If the charactor becomes more sophisticated during the development, thing will become worse.  
![single curve editor](https://raw.githubusercontent.com/JustusPan/resource/master/images/easing_curve_editing.png)  

Maybe a new operation mode of animaion should be introduced here?Want more discussion about this topic.Thanks.

**Comment by henriiquecampos** [comment]
This is absolutely necessary and is actually a regression from 3.0 animation system.

![image](https://user-images.githubusercontent.com/10171059/60892162-0b6a6800-a235-11e9-9c87-6181b120a4e8.png)

**Comment by avencherus** [comment]
Also wondering why the multi-selection was dropped.

**Comment by avencherus** [comment]
As far as I can tell it goes missing at:  https://github.com/godotengine/godot/commit/b659fd6d7442701284cbb8763fb712be36d17ed0

**Comment by zhaishengfu** [comment]
I can not find this function in godot 3.5.3
