### ISSUE TITLE
Distance field for all controls.

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#2453]
For now, only label work well with distance field, if it's possible, would be nice to have this for the rest of controls like buttons, checkboxs, etc.

**Comment by volzhs** [comment]
:+1:

**Comment by neikeq** [comment]
DynamicFont was introduced by 5bb7cef. It's not distance field, but I guess it solves the issue. Can this be closed?

**Comment by akien-mga** [comment]
Assuming that yes.

**Comment by volzhs** [comment]
What I understand and vote for is scalability of controls not only label.
Anyway we got scalability for controls. So, it's solved.

**Comment by reduz** [comment]
The problem with this is that there is no perfect solution.  

1) Distance field only works for relatively large fonts, small fonts (or low dpi) look horrible.
2) DynamicFont works if you scale it yourself, but you have to do the dpi adjusting manually
3) Storing fonts as bigger resolution and drawing them smaller will also not work well (generates a lot of aliasing)

I haven't really thought of something that will work everywhere
