### ISSUE TITLE
Inspector no longer interprets Comma as decimal point in editor

### ISSUE THREAD

**Issue by splite** [godotengine/godot#24531]
**Godot version:**
3.1-alpha (2 and 3, didnt test alpha1)

**OS/device including version:**
Windows 10, non-english keyboard

**Issue description:**

Regression of issue #6028 in godot 3.1 alpha. Original issue fixed by PR #13240

In GODOT 3.0 editor you can use "," as decimal separator:

![insert_with_comma_godot305](https://user-images.githubusercontent.com/4945875/50347112-ce5ab480-0534-11e9-9455-65fefc71b82b.gif)
(comma is simply replaced by dot)

In GODOT 3.1-alpha (2 and 3, didnt test 1) everything after comma is trimmed:
![insert_with_comma_godot31_alpha](https://user-images.githubusercontent.com/4945875/50347145-ec281980-0534-11e9-84e9-113df83b2913.gif)

**Steps to reproduce:**

Same as in issue #6028

1) In editor, write "1.1" to any float box (like "rotation degrees" on Node2D) - rotation is set to "1.1"
2) In editor, write "1,1" to any float box (like "rotation degrees" on Node2D) - rotation is set to "1"

**Comment by akien-mga** [comment]
See discussion on #24532.

Simply replacing "," by "." is problematic as the `EditorSpinSlider` uses the `Expression` node to parse commands and can support functions with multiple arguments, such as `pow(2, 3)`.

A better solution would be to intercept the key event from this numpad comma separator and replace it by a `KEY_KP_PERIOD` event (only in `EditorSpinSlider`). This implies actually exposing this separator event to Godot in platform keyboard bindings.

**Comment by Calinou** [comment]
@akien-mga Is using `pow()` and other functions in the inspector common enough? If not, I think it'd be better to just replace `,` with `.` at this point.

**Comment by akien-mga** [comment]
It's important in `Expression` yes, which can parse full expressions.

That's why I said this should be handled ad-hoc in the inspector only (`EditorSpinSlider`).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1576, as feature proposals are now tracked in the Godot proposals repository.
