### ISSUE TITLE
Android GLES3: 3D Particles on GPU not showing when using scale curve

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#24538]
**Godot version:**
Reproduced on Master c23710adde23a0e415097dee7d8e6f9ba76a0970 (need 404f39422665375e62863c0247768759bb2cd0be, see note at the bottom)

**OS/device including version:**
Android, Samsung Galaxy S6

**Issue description:**
3D Particles on GPU (GLES3) don't show up on Android when using a scale curve in the particle material.

**Steps to reproduce:**
1. Add Particles node in scene
2. Set a Scale Curve (any type of curve, the issue happens with flat 1)
3. Deploy to Android device
4. Particles don't show up

**Minimal reproduction project:**
[test-particles.zip](https://github.com/godotengine/godot/files/2704322/test-particles.zip)

**Important note**
You need 404f39422665375e62863c0247768759bb2cd0be for particles to be rendered at all on Android GLES3.

**Comment by pouleyKetchoupp** [comment]
It's actually related to that issue: #24295

**Comment by akien-mga** [comment]
Fixed by #24575.
