### ISSUE TITLE
String lstrip/rstrip are not removing chars as expected

### ISSUE THREAD

**Issue by lorderb** [godotengine/godot#24533]
**Godot version:**
v3.1 Alpha 3 win64

**OS/device including version:**
Windows 10 64

**Issue description:**
lstrip and rstrip have different behavior and are not removing chars as expected:

```gdscript
var test = "AAABBBAAA"
print(test.lstrip("A"))
print(test.rstrip("A"))
```

Output:
```
AAABBBAAA
AAABBBAA
```

Expected:
```
BBBAAA
AAABBB
```

**Comment by Chaosus** [comment]
Fixed by #24823
