### ISSUE TITLE
Video player doesn't play on GLES2

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#24559]
**Issue description:**
Video player doesn't work on Linux 64 bit with GLES2 using a webm video.

**Godot version:**
Godot 3.1 Alpha 4 Linux 64 bit

**OS/device including version:**
Ubuntu 64 bit,  Intel(R) Bay Trail driver

**Steps to reproduce:**
Just have a video player node with a webm video, the project runs but the video doesn't show on the screen.

**Comment by samvila** [comment]
I get this error when running the project:

intel_do_flush_locked failed: Cannot allocate memory

I'm using an Intel stick with Linux:

https://ark.intel.com/products/86613/Intel-Compute-Stick-STCK1A8LFC

**Comment by Sslaxx** [comment]
Can confirm this is not a platform-dependent bug; does this on Win10.

On the command line:
```
ERROR: Failed loading resource '';
    At: modules\webm\video_stream.webm.cpp:56
```

**Comment by reduz** [comment]
I dont have any webm video handy nor I have a clue how to create it, can you or anyone else make a small repro project for this issue?

**Comment by samvila** [comment]
Hi Juan,

Here's a link with a sample at 1080p:

https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f3/Big_Buck_Bunny_first_23_seconds_1080p.ogv/Big_Buck_Bunny_first_23_seconds_1080p.ogv.1080p.webm

**Comment by akien-mga** [comment]
Tested with current master branch (ce363510) on Linux with Nvidia GTX 670MX (proprietary drivers), the video runs fine for me with GLES2.

> It displays a small black square in the top-left corner of the window.

The small black square is just the default size of the VideoPlayer node, you can stretch it to the expected size of your video.

About:
```
ERROR: Failed loading resource '';
    At: modules\webm\video_stream.webm.cpp:56
```
Did you set a video stream?

Here's a project with a VideoPlayer and @samvila's Webm video, works fine here.
[gles2_video.zip](https://github.com/godotengine/godot/files/2772005/gles2_video.zip)

---

For the reference, I also tried with https://upload.wikimedia.org/wikipedia/commons/c/cf/Big_Buck_Bunny_8_seconds_bird_clip.ogv (Theora), but it had some playback issues. However, VLC has some playback issues with it too (starts at time 0:15 out of 0:23 somehow, for a 8s clip), so I think this file has some invalid metadata. I also tried to convert it to webm with `ffmpeg -i <path_to_ogv> <path_to_webm>` but then I had no image, only sound (both in Godot and in VLC).

**Comment by akien-mga** [comment]
Closing as it works fine for me. If you can still reproduce the issue, please attach a project that exhibits it.
