### ISSUE TITLE
Editing an auto-tile doesn't show scrollbars until you change the zoom

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#24557]
**Godot version:** 3.0.6

**OS/device including version:** Windows 10

**Issue description:** When editing the tileset on a tilemap, even if the tileset is huge and the window is small, it doesn't show scrollbars.  In this screenshot, the red arrow shows the tiles are truncated but the scrollbars are missing.

![image](https://i.imgur.com/nGmpDKV.png)

**Steps to reproduce:**
- Find/borrow a large tileset
- Create a new tileset scene with some tiles, export as a TileSet
- Create a new tile map, and load the tileset
- Look at the editor.

Expected: the tilemap is large and extends beyond the window dimensions, so you see scrollbars.
Actual: You don't see scrollbars.

Work-around: click `(1)` or zoom in/out and the scollbars appear.

**Minimal reproduction project:** N/A. I think this bug is easy to reproduce. But if you want, you can use any commit from [my current game](https://github.com/nightblade9/eman-quest). (If so: open up Scenes > Maps > `AutoTileTilesets.tscn` and edit any tileset.

**Comment by akien-mga** [comment]
This seems fixed in the master branch:
![screenshot_20181227_084528](https://user-images.githubusercontent.com/4701338/50471171-c32fda80-09b3-11e9-9d69-c416030220b9.png)

**Comment by nightblade9** [comment]
In that case, feel free to close this.
