### ISSUE TITLE
BakedLightmap makes mesh disappear

### ISSUE THREAD

**Issue by David-Ochoa** [godotengine/godot#24550]
**Godot version:**
3.1 Alpha 3

**OS/device including version:**
Windows 10 Intel Integrated, Windows 10 Rayzen 3 Vega 8 Graphics

**Issue description:**
Adding a BakedLightMap makes some meshes to wrongly hide, and this is in whole project even after deleting the BakedLightmap and using new scenes the problem continues:

[With BakedLightmap](https://youtu.be/JPAnYIpCLZI)
[BakedLighmap removed](https://youtu.be/sKPVf8moWr8)

**Steps to reproduce:**
Open attached project and run it. The model's head will hide at wrong distance, if the model is used in other project the model renders correctly.

**Minimal reproduction project:**
[ImportDAE.zip](https://github.com/godotengine/godot/files/2705417/ImportDAE.zip)

**Comment by David-Ochoa** [comment]
I know BakedLightmap will be rewritten for 3.2, all I need is a way to stop this without creating a new project.

**Comment by bojidar-bg** [comment]
Are you sure BakedLightmap is responsible for the disappearance of the mesh (and not some wrongly configured/imported mesh)?

**Comment by David-Ochoa** [comment]
It was my best guess, let me explain why:
All was working with my model: [Working](https://www.youtube.com/watch?v=c3NEb9jbygE)
But when I was trying bakedlightmap for rendering improvements suddenly some model parts started to dissapear. I removed the lightmap but the problem persisted, as I removed the lightmap I discarded it as the problem ans proceed to remake the model (it was in my plans because the original was 65k polygons with 98 blend shapes applied to the whole body).
New model was intended to be less than 20K with fewer blend shapes and only applied to the face, before adding the blend shapes I tried the model and the problem showed again.
I removed all the .mono, mono, .import folders, all the .import files and let Godot reimport all the assests again, and the problem persisted.
Because I use a script to join the animations I tought it maybe the culprit, so I analized and changed come parts with the same result, so I decided to use the original unmodiifed model from Mixamo, and again the result was the same.
Finally I decided to post here and started creating a simple project with the model and the problem was not present. I looked at every model property, import property, scene property to not avail.
Then I remembered the bakedlightmap, added a light, baked the scene and the problem shows again at last.
Downloaded a new simple model, and created the sample project and created this issue.

That's why I said it was my best guess.

But now:

As you can see I don't like to be idle, so I decided to try something else, new test is create working project, clone it and apply bakedlightmap, remove lightmap and use a difference tool to track changes
and find a culprit. Probelm is now I can't create a working project, now in every new project the problem raises as I import the model. removed $user\AppData\Roaming\Godot contents, restarted PC and now every time the model is wrong.

Please if anyone has the slightest idea I'd appreciate it. I will continue my search because as I type new ideas are coming. Thanks.

**Comment by David-Ochoa** [comment]
I looked at the repository looking for "CULL" and found Godot culls animated meshes from original position and when moved from original position they dissapear. I applied the extra cull margin and the problem is gone.
The question is if the behaviour will remain as is or will be changed. If there are no plans to change it then I can close this issue. If changes are planned I can change the title and leave it open for reference.

**Comment by TIBI4** [comment]
So this will in 3.2?

My meshes dissapear on Android and HTML5, but in PC it's working ok.

**Comment by takhimi** [comment]
I confirmed that this happens to me too. On Android (Redmi note 2 and Asus zenfone max pro m1) but not on my pc (gtx970). If i hide the bakedlightmap node in the editor, I can see my monsters and guns on my phones. If it is visible or enabled, I wont be able to see them on my phone.

**Comment by Janders1800** [comment]
Same to me, it works OK on PC but it hides non-baked meshes (like the player) on Android.

**Comment by volzhs** [comment]
additional sample project from #32535 
https://github.com/godotengine/godot/files/3688377/LightMaps.zip

**Comment by clayjohn** [comment]
Can anyone reproduce in 3.2 beta 5?

**Comment by akien-mga** [comment]
Tested the OP on desktop with 3.2 beta 5, I could not reproduce the bug.
I also tested the project from #32535 on Android (Xiaomi Pocophone F1) with GLES2 and did not have the bug either.

So it seems fixed :)

Please comment if you can still reproduce the bug in 3.2 builds, and if so give details about your device, drivers, and project.

**Comment by Janders1800** [comment]
Tested on android Alcatel 1 GLES2, the bug still persists, no visible meshes inside area of effect of the bakedlightmap. Please @akien-mga reopen the issue.

**Comment by clayjohn** [comment]
@Janders1800 did you try with 3.2 beta5?

**Comment by Janders1800** [comment]
Yes I did, forgot to mention it.

**Comment by Janders1800** [comment]
Tested on beta 6, still the same.

**Comment by clayjohn** [comment]
I was able to reproduce using the project from  #32535 on my phone using GLES2 only. Meshes that are not included in the baking get hidden when the scene is played on android. I'll look into whats causing it but I don't think this is a bugfix that will make it into 3.2.

**Comment by Janders1800** [comment]
Still happens to me on 3.2 rc3

**Comment by clayjohn** [comment]
Did you remember to use the rc3 export templates as well?

If so, can you please post the relevant logcat output?

**Comment by Janders1800** [comment]
How do I do a log on Android?
