### ISSUE TITLE
Mono: Alpha 4 crashing on existing and new projects

### ISSUE THREAD

**Issue by exts** [godotengine/godot#24551]
**Godot version:**
3.1 Alpha 4

**OS/device including version:**
Windows 10, GTX 1060 6GB

**Issue description:**
When godot tries to rebuild the solution or create a new solution it crashes to desktop

**Steps to reproduce:**
1. Create a new empty project
2. Try adding a solution file
3. Wait for godot to crash

[1545500250.txt](https://github.com/godotengine/godot/files/2705418/1545500250.txt)

Attached crashlog

**Comment by hpvb** [comment]
A4 enabled copy_mono_root and upgraded mono to 5.16 will need to figure out what is causing this

**Comment by exts** [comment]
Workaround is to install mono 5.16 locally then renaming the `GodotSharp/Mono/lib` folder to `GodotSharp/Mono/libx` and godot will try loading mono locally from your pc. For those wanting to use latest stable

**Comment by neikeq** [comment]
I will have a look.

**Comment by exts** [comment]
So after reverting the `lib` folder to its original name and renaming the `etc` folder to something random the project builds. Here's the log file from that build.

[1545508462.txt](https://github.com/godotengine/godot/files/2705493/1545508462.txt)

**Comment by hpvb** [comment]
I copy the mono/etc directory from a Linux install of mono. I'll figure out what the difference is between it and a windows install and fix it for a5

**Comment by neikeq** [comment]
I just checked it. There is nothing wrong with the etc folder which should be portable IINW. The problem seems to be with the bundled assemblies, concretely mscorlib. Replacing it with the one on my system fixed it.

**Comment by neikeq** [comment]
I just had a quick look and it seems the Godot binary is statically linked against Mono 5.16.0.220 while the bundled mscorlib assembly is from Mono 5.12.0.226. That would explain the problem.

**Comment by exts** [comment]
![discord_2018-12-26_07-50-10](https://user-images.githubusercontent.com/16387107/50456885-3c302300-091d-11e9-9134-ad6fedfd0a99.png)

Also can we update the blog to alert people so they aren't confused and maybe point to this thread for the workaround.

**Comment by Garrom** [comment]
> It's an alpha, it's fine
Most honest and accurate segment of this year

**Comment by piratesephiroth** [comment]
Replacing mscorlib fixes it partially.
The editor still can't run regular (non-mono) projects.

**Comment by exts** [comment]
Fixed in beta1
