### ISSUE TITLE
Wrong alignment of buttons on MacOS version

### ISSUE THREAD

**Issue by ondrowan** [godotengine/godot#24554]
**Godot version:** 3.1 alpha 4

**OS/device including version:** MacOS 10.14

**Issue description:**

Buttons are by default shown aligned like this on MacOS (doesn't happen on Windows):

<img width="747" alt="image" src="https://user-images.githubusercontent.com/423776/50378236-8b303c80-062d-11e9-8c60-8e5333e803a2.png">

The lower part of these buttons isn't clickable. Resizing the window aligns the buttons properly and fixes the issue.

**Comment by akien-mga** [comment]
CC @Calinou

**Comment by Calinou** [comment]
I couldn't reproduce this on https://github.com/godotengine/godot/commit/04c8a43741656814c86923c89f2dd23646751b96 on Linux (with the editor scale set to 200%).

I don't see why this would be OS-specific, but I can't test this on macOS with a hiDPI display anyway.

**Comment by ondrowan** [comment]
@Calinou I've just tried today's nightly and it still happens on MacOS 10.14.2.

**Comment by akien-mga** [comment]
Might be fixed by #25858.

**Comment by akien-mga** [comment]
Assumed fixed by #25858, please comment if you can still reproduce it.
