### ISSUE TITLE
ViewportTexture is vertically mirrored in GLES2

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#24555]
**Godot version:**
Godot 3.1 alpha 4

**OS/device including version:**
Manjaro Linux, Radeon RX 560

**Issue description:**
ViewportTextures appear mirrored in GLES2, but look correct in GLES3. Here is a simple 3D scene captured by a camera and displayed in TextureRect:

**GLES3:**
![gles3](https://user-images.githubusercontent.com/15891496/50378339-45c13e80-0630-11e9-9934-678031cb0080.png)
**GLES2:**
![gles2](https://user-images.githubusercontent.com/15891496/50378346-5ec9ef80-0630-11e9-8059-5d7ec337957b.png)

**Minimal reproduction project:**
[ViewportTexture.zip](https://github.com/godotengine/godot/files/2705517/ViewportTexture.zip)

**Comment by volzhs** [comment]
can still reproduce it with 973b68f39

**Comment by avril-gh** [comment]
8b77dac56e375698cdd28bc6033d076c600a5a19

![inverted](https://user-images.githubusercontent.com/3224132/52659951-e2041500-2efe-11e9-8ef7-db7cbf66d22d.jpg)
