### ISSUE TITLE
Moving groups of tiles in the 2D editor

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#24567]
**Godot version:**
3.0.6

**OS/device including version:**
Windows 8.1

**Issue description:**
Hi, in the 2D editor after creating a tilemap and putting a bunch of tiles in a level of the game, it's not possible to move a selection of tiles and reallocate that in another space but you need to erase and recreate it with what you want. Any chance to add this feature in 3.1 version? Thank you.

**Steps to reproduce:**
Create a tilemap, start to make a level for your game but you will need to erase the tiles in the 2D editor every time you change your mind about the level structure.

**Minimal reproduction project:**
Any level 1 Mario games.

**Comment by Zireael07** [comment]
3.1 is right around the corner, so not likely for it to happen in 3.1., rather in 3.2.

**Comment by Arkhano** [comment]
Thanks! I will wait for sure.

**Comment by Zylann** [comment]
Actually that became an issue since 3.0 https://github.com/godotengine/godot/issues/16293

**Comment by bojidar-bg** [comment]
@Zylann Isn't #16293 fixed on master by #12489 and others?

**Comment by PelegMedia** [comment]
In 3.1beta3 selecting a group of tiles and then copy you get empty tiles.
The image comes from an atlas texture.
I had to redraw tiles manually.

**Comment by Banduck** [comment]
Besides the "Cut, Copy, Erase Selection" there should be a "Move Selection", that would be useful. But to be honest, I think the TileMap editor in general is a bit unproductive.
I wish you could move and copy the tiles around as easily as regular nodes in the editor.

**Comment by hsandt** [comment]
@AttackButton Sorry to post on an archived post, but is this issue just closed without turning it into a suggestion in godot-proposals?
 
The close reason is not clear, and as @Banduck said, the workaround requires 3 steps.

**Comment by AttackButton** [comment]
@hsandt Hmm! I think this is working since some versions ago. Isn't that working in 3.2?

**Comment by PelegMedia** [comment]
@AttackButton it is working. I am using it in 3.2.1 stable.
I think that there should be another ticket with improvement suggestions, similar to what @Banduck said.
