### ISSUE TITLE
Light2D Error/Warning when loading light texture

### ISSUE THREAD

**Issue by securas** [godotengine/godot#24562]
**Godot version:**
Godot 3.1 alpha 4

**OS/device including version:**
Windows 10, GeForce GTX 1070

**Issue description:**
Light2D gives out warning when loading a light texture.

**Steps to reproduce:**
- Start new project
- Create Node2D scene
- Add light2D node
- Load light texture

![image](https://user-images.githubusercontent.com/2881755/50380094-0d594900-06a0-11e9-8185-569e3468023e.png)

**Comment by akien-mga** [comment]
CC @DualMatrix, looks like we forgot about comma-separated type hints in #22437.

**Comment by DualMatrix** [comment]
Yup that seems to be the case, I'll see what I can do
