### ISSUE TITLE
Setting "Shadow as Outline" above 1 has no effect

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#24569]
This was already mentioned [here](https://github.com/godotengine/godot/issues/19356#issuecomment-394311347) but I found out about it on Discord so I'm opening another bug about it.

**Godot version:** 3.0.6

**OS/device including version:** Windows 10

**Issue description:** Setting the value of "Shadow as Outline" to any value above 1 has no effect; outlines all look the same.

**Steps to reproduce:**
- Create a label
- Check `Custom Colors` > `Font Color Shadow`
- Check `Custom Constraints > Shadow as Outline`
- Specify a value of 1. Run Godot, check out how it looks.
- Specify a value of 10. Re-run Godot, check out it looks.

Expected: the outline=10 should be thicker.
Actual: the outline=10 is the same thickness.

Here's a screenshot of my project; "Actions" has an outline of 8, everything else has an outline of 1
![](https://i.imgur.com/SFvhBBX.png)

**Minimal reproduction project:** N/A

**Comment by Calinou** [comment]
The outline thickness of "legacy" font outlines is determined by the X and Y shadow offsets. I know it's not very intuitive, but that's how it works :slightly_smiling_face:

**Shadow as Outline** should be turned into a checkbox (and possibly removed entirely in the long run, as it's less efficient and uglier than outlines generated by FreeType).

**Comment by nightblade9** [comment]
@Calinou that seems also broken. If I check Shadows as Outline (value=0) and set X/Y to 8, or set Shadows as Outline to a non-zero value, it looks like a regular outline. If I set all three to 8, I get ... this.

![image](https://user-images.githubusercontent.com/31222662/50386560-228da200-06b7-11e9-8e00-0926f2e247c2.png)

If I can make this request very specific: however this is supposed to work (once this issue is fixed), please disable/remove text fields from `Custom Constraints` that don't make sense. This is going to be a source of user frustration otherwise.

**Comment by Calinou** [comment]
> If I set all three to 8, I get ... this.

That's the shortcoming of legacy font shadows; they just happen to copy the original text four times with the defined X/Y offset. It's slower as it requires more draw calls and it looks worse.

**Comment by reduz** [comment]
This option is very very old and will likely be deprecated in newer Godot versions. You can set outlines on fonts themselves now in Godot 3.1

**Comment by akien-mga** [comment]
CC @godotengine/gui-nodes - to assess if that option has indeed been deprecated/removed in 4.0 already, or if it still has to be (provided that @reduz's assessment that it can be done differently is correct).

**Comment by bruvzg** [comment]
There's no `shadow_as_outline` in `4.0`, shadow is drawn a bit differently. In `3.x` it's used as a boolean value, and it's documented as such, setting it to anything above `1` should have any effect:

> Boolean value. If set to 1 ([code]true[/code]), the shadow will be displayed around the whole text as an outline.
