### ISSUE TITLE
Invalid tokens generated from GD script parser

### ISSUE THREAD

**Issue by jwijngaarde** [godotengine/godot#24564]
**Godot version:** 3.1.alpha.custom_build.0cff752

**OS/device including version:** Linux Debian Buster x86_64

**Issue description:** I was following instructions on this website in order to build a custom module https://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html?highlight=module
This is GD script i was supposed to enter which I did:
var s = Summator.new();
s.add(10);
s.add(20);
s.add(30);
print(s.get_total());
s.reset();  

It threw the message Unexpected token Identifiers:s

**Comment by AlexAndDraw** [comment]
Could you upload the files you used to create the Summator class somewhere? (include register methods).

**Comment by AlexAndDraw** [comment]
Did you put that GDScript into a function? 

```
extends Node

func new_s():
    var s = Summator.new();
    s.add(10);
```

should work, however

```
extends Node

var s = Summator.new();
s.add(10);
```

Throws an "unexpected token identifier": s

**Comment by jwijngaarde** [comment]
[summator.zip](https://github.com/godotengine/godot/files/2706155/summator.zip)

**Comment by jwijngaarde** [comment]
These are the files used to create the summator class i put them in a zip

**Comment by AlexAndDraw** [comment]
> These are the files used to create the summator class i put them in a zip

I downloaded them, they seem fine. I edited my initial post. I think you just need to put the s.add(10) into a function inside your script

**Comment by akien-mga** [comment]
Indeed, this error happens if you put a statement using an identifier outside a function.
