### ISSUE TITLE
The get property node cannot automatically change the output value to the corresponding type in the visual script

### ISSUE THREAD

**Issue by haizhou37** [godotengine/godot#24576]
**Godot version:**
   Godot3.1Alpha4

**OS/device including version:**
manjaro gnome x64
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile
intel hd 3000

**Issue description:**
The get property node will only change if I switch its value through the Funtion in the properties panel
![peek 2018-12-24 16-52](https://user-images.githubusercontent.com/33272474/50395103-f2203380-079c-11e9-9a31-f409eaab9c82.gif)

**Minimal reproduction project:**
[test1.zip](https://github.com/godotengine/godot/files/2706913/test1.zip)

**Comment by SoIAS** [comment]
This problem doesn't affect only "get property nodes", but some function call nodes as well. For example RigidBody.get_rid node which is a function call, returns Any (Variant::NIL) instead of rid (Variant::_RID) on node creation. Tested on master b16c309f82c77d606472c3c721a1857e323a09e7.

**Comment by KoBeWi** [comment]
Fixed in 3.2
