### ISSUE TITLE
Disable collision shape not working properly

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#24577]
**Godot version:**
3.1 alpha 4

**OS/device including version:**
Windows 10 and Ubuntu, probably platform independent

**Issue description:**
Using the new move_and_slide_with_snap() method with a basic platformer game.
When CollisionShape2d with Rayshape2d is disabled: Character is about to land on the ground, there is some weird behaviour where the Raycast is still processing in some way (similar to other shapes?), but not colliding like normally.
To workaround this i am manipulating the rayshape length instead, but it would be nice if disable worked properly! But the disabled collisionshape should have the same effect in this example.

**Steps to reproduce:**
Make a kinematic body 2d and attach two collision shapes. One RayShape2D and one rectangle. Disable the collisionshape2d with rayshape. 

**Minimal reproduction project:**
I dont have a minimal project to share. But here is example of a disabled ray (notice slow descend):
![disabled ray](https://user-images.githubusercontent.com/15088582/50394982-98e6de80-0761-11e9-9a21-dd3a107b5e71.gif)
Here is the shortened ray (works as intended):
![short ray](https://user-images.githubusercontent.com/15088582/50394995-a69c6400-0761-11e9-9af4-3c6acf15cdf5.gif)

**Comment by fossegutten** [comment]
Sorry. I think it was a bug in my code, probably not in godot.

**Comment by isaacremnant** [comment]
@fossegutten, I think I have a similar problem but with two collision shapes. What was the problem in your code?
