### ISSUE TITLE
Docks change size when tabbing in/out

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24572]
Godot 3.1 alpha 4

I opened an empty project, and clicked on the `Import` and `Scene` tabs alternatively, and noticed that the size of the left dock changed size as I did this. Same for the right dock, for which tabs also move as a result.
This didn't happen in 3.0.6. It keeps happening even if I change the size using the vertical split.

**Comment by girng** [comment]
possibly related to https://github.com/godotengine/godot/issues/23289

**Comment by Zylann** [comment]
@girng no, this is not about alt-tabbing, but just clicking dock tabs alternatively.

**Comment by groud** [comment]
@Zylann It is actually related, but more to the fix I made than the issue itself.
I suspect the Import and Scene dock not having the same minimum width, which could cause the split offset to be calculated differently depending on the dock.

**Comment by akien-mga** [comment]
It doesn't seem reproducible in the current master branch (at least on Import and Scene).
