### ISSUE TITLE
Relationship Lines are not being drawn in TreeNode despite width and color set

### ISSUE THREAD

**Issue by AlexAndDraw** [godotengine/godot#24579]
3.1 (I don't have the exact commit, it was the one where Calinou made the different indent lines?)

When using a TreeNode, the relationship lines aren't being drawn despite the size and color being set to non-null values. 

![ex](https://i.imgur.com/8cUoN0l.png)

[Example Project](https://github.com/AlexAndDraw/TreeExample)

**Comment by volzhs** [comment]
the `Draw relationship lines` value should have 0 or 1 (false or true)
it's not about the line thickness.
you can see the lines with `1`

it would be best to show boolean option instead int.
but it will break compatibility.
