### ISSUE TITLE
Input.is_key_pressed() behavior changed after window minimized when simulating fps limiter

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#24581]
**Godot version:** alpha 4

**OS/device including version:** ubuntu 16 64 bit 

**Issue description:**
input is key pressed is keep returning true even after physical button released for 5 second or more. this is happened after i try to minimized my window for couple second.

**Steps to reproduce:**
create a scene, attach script for check A is pressed in _process(delta) function, set fps limiter to 5 fps to simulate low fps in project setting. run the scene and press and hold A key  then observe the console, the result must be normal. try to minimize the game window for some time and go back again then try to press and hold A key for 3 second, after 10 second or so the console print false. this is causing input lag in game, i am sure this is bug.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by fian46** [comment]
It didn't happen again.

**Comment by akien-mga** [comment]
Closing then, it was probably fixed in the meantime.
