### ISSUE TITLE
[2D Editor] RichTextLabel node showing the vertical text bar in the editor and the game

### ISSUE THREAD

**Issue by Arkhano** [godotengine/godot#24584]
**Godot version:**
3.1 alpha 4

**OS/device including version:**
Windows 8.1

**Image of the issue:**
![image](https://user-images.githubusercontent.com/25422687/50406174-9f984480-07a7-11e9-83d3-aecf2131b045.png)

**Issue description:**
Maybe it is happening with another labels too. When you use the RichTextLabel node with a button and insert a text (via script or editor 2D) the "vertical text bar" appears in the label in the editor or when you run your game.

**Steps to reproduce:**
Create a TextureButton node, create a RichTextLabel node, type something in the RichTextLabel text area, you will see the "bug" in the 2D editor.

**Minimal reproduction project:**
Any game with text that needs RichTextLabels.

**Comment by volzhs** [comment]
I see a `g` or `q` in the `Text` field at the bottom.
isn't it expected result with multiple lines?

**Comment by Arkhano** [comment]
> I see a `g` or `q` in the `Text` field at the bottom.
> isn't it expected result with multiple lines?

Even with 1 line the vertical bar appears, even when the game is running.
