### ISSUE TITLE
Shadow atlas size setting does not change resolution

### ISSUE THREAD

**Issue by SavageMcCabbage** [godotengine/godot#24587]
**Godot version: 3.1 alpha 4, also appears in 3.0.6 stable**

**OS/device including version: Windows 10, GTX 1070ti, NVidia 417.35 Drivers**

**Issue description:**
Changing the shadow atlas size appears to affect the softness of the filtering, rather than increasing the resolution of the shadow.

I've tested the default project quality settings with shadow filtering set to PCF13, using shadow atlas sizes from 512 by 512 to 16384 by 16384. The scene is a cuboid and a plane, with one omni light casting a shadow. It looks like the shadow just gradually loses the effect of the filtering as the resolution increases, rather than increasing the resolution itself.

512 by 512:
![512](https://user-images.githubusercontent.com/42379432/50407731-0c760380-07d5-11e9-81ff-04a68c1cd2b5.png)

1024 by 1024:
![1024](https://user-images.githubusercontent.com/42379432/50407726-ff591480-07d4-11e9-9485-1d846d624bc6.png)

2048 by 2048:
![2048](https://user-images.githubusercontent.com/42379432/50407712-ac7f5d00-07d4-11e9-877e-7bf3f3841391.png)

4096 by 4096:
![4096](https://user-images.githubusercontent.com/42379432/50407660-ebf97980-07d3-11e9-9990-f47a0d1fb58f.png)

8192 by 8192:
![8192](https://user-images.githubusercontent.com/42379432/50407684-04699400-07d4-11e9-877b-7a245778f5b5.png)

16384 by 16384:
![16384](https://user-images.githubusercontent.com/42379432/50407701-61654a00-07d4-11e9-9463-6bcbc2753280.png)

I can't tell by eye if the resolution is actually changing as expected at the lower resolutions, but it's clear to me that the shadows are exactly the same between 4096, 8192 and 16384, aside from the higher two looking worse due to not having the edges smoothed as much. Currently, it doesn't seem worth it to turn shadows to anything other than somewhere between 2048 or 1024, as those seem to be the best balance between clarity and smooth edges.

**Steps to reproduce:**
1. Set shadow filtering to PCF13.
1. Set shadow atlas resolution to any low power of 2 in project settings, then raise until hitting the max.
1. Observe how shadow blockiness never changes (aside from being imperceptible at the lower resolutions due to excessive smoothing), but smooth filtering decreases as resolution increases.

**Minimal reproduction project:**
[Shadow Test.zip](https://github.com/godotengine/godot/files/2707801/Shadow.Test.zip)
The only setting I changed between the screenshots was shadow atlas size. It's 
currently set to max in this project. The omni light has its bias set to 0.05, but is otherwise unchanged.

**Comment by Zylann** [comment]
Note that resolution and smoothness are two different things: if the lower resolution looks blurrier, it's probably not directly intented. If you want a smoother blur, that would be a new feature to control the filtering of shadows rather than their resolution, though real shadows do present varying levels of blur the further they are from their projector.

**Comment by SavageMcCabbage** [comment]
Yeah, you're right, the smoothing doesn't seem related. I tried again with it disabled, and it's a lot clearer that it works fine up to 4096, but it seems almost as if a lower res shadow map is being used to determine where the higher res map is dark, so there's a smaller, second jagged edge along the first, more visible edge.

![jaggy](https://user-images.githubusercontent.com/42379432/50408859-089ead00-07e6-11e9-9f73-c4468120c1b4.png)

(Using 8192 for that one)
