### ISSUE TITLE
Godot Mono crashes in starting of debuging

### ISSUE THREAD

**Issue by CapsLockkk** [godotengine/godot#24580]
Godot Mono v3.1 Alpha 4 (x64)
Mono SDK v5.16.0.220 (x64)

OS: Windows 10 (x64)
Intel Core i7 7500U
NVIDIA GeForce 920MX 2Gb VRAM
8Gb RAM

When I create new C# script or start debugging of any project Godot crashes. No any logs or other details of error, its just crashes and closes. I normally use the editor and save the project, but as soon as I start debugging everything goes awry. All the files that I have kept are intact and saved, but I can not do anything because of this problem.
[Any Project.zip](https://github.com/godotengine/godot/files/2707340/Any.Project.zip)

**Comment by CapsLockkk** [comment]
Problem solved. My issue is duplicate of [This](https://github.com/godotengine/godot/issues/24551)
Problem solved by renaming folder `GodotSharp\Mono\etc` to `GodotSharp\Mono\etcxxx`

**Comment by Chaosus** [comment]
> Problem solved. My issue is duplicate

Ok, I close it then
