### ISSUE TITLE
Condition ' action_level <= 0 ' is true when changing position of node in scene dock

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#24591]
**Godot version:**
3.1 10e9221

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When I try to changing position of node in scene dock with CTRL pressed, then sometimes this error occur:
ERROR: commit_action: Condition ' action_level <= 0 ' is true.
   At: core/undo_redo.cpp:242.

**Comment by Chaosus** [comment]
Hmm.. Looks like a duplicate of #20920, but the error is different `action_level <= 0` vs `action_level > 0`

**Comment by qarmin** [comment]
Still happens with master

**Comment by akien-mga** [comment]
Do you have more explicit steps to reproduce? I can't manage to get error.

**Comment by KoBeWi** [comment]
@qarmin Can you test if this is resolved?

**Comment by qarmin** [comment]
I tried reproduce this several times, but now it works just fine
