### ISSUE TITLE
Get_Pixel Issue

### ISSUE THREAD

**Issue by BigDC** [godotengine/godot#24590]
I use Godot 3.0.6 on Windows 10 64., I am creating a game similar to "Risk" or "Diplomay" or "Civillian 3", you click on a territory of land to select it. I use a flood filled map of colors with each territory being a different color, I then use get_pixel to get the color of where I clicked and compare it to data stored in a json file to get the right territory. Ok, now here is the problem, get_pixel returns a color very similar to what is on the map but it is not exact. My game relies 100% on it being exact. The issue has been discussed and fixed for Godot 3.1 see the issue here  https://github.com/godotengine/godot/issues/19652    I know it works in 3.1 because I created a duplicate of my project and tried the duplicate in a nightly build of 3.1 and the issue is fixed, it works. But it is not been done for Godot 3.0.6 so what can I do or what should I do? What would you do it it were you?

**Comment by groud** [comment]
You use a normal array of colors instead of textures.
Using textures for storing data is in general not a good idea.

Else if you want to use that you will probably have to wait for 3.1

**Comment by Zylann** [comment]
Or you use a threshold compare rather than equality? In theory when images have integer componentd they actually can be used to store data, it's just the API that makes it hard.

**Comment by Chaosus** [comment]
You can also compile the Godot nighty build from source if you wish, the documentation have the required instructions

> Else if you want to use that you will probably have to wait for 3.1

Closed as solved.
