### ISSUE TITLE
Object rotation or moving is unpredictably when using global_rotate in Bullet

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#24598]
**Godot version:**
 3.1 alpha 3

**OS/device including version:**
 Ubuntu 16.04 64

**Issue description:**
Bullet. The cube behaves unpredictably when rotating or moving.

**Steps to reproduce:**
`get_node('player').global_rotate(Vector3(0, 1, 0), 0.1)`

**Minimal reproduction project:**
[Bullet.zip](https://github.com/godotengine/godot/files/2709296/Bullet.zip)

**Comment by DimaKiva** [comment]
3.1 beta1

**Comment by DimaKiva** [comment]
beta3

[Bullet video.zip](https://github.com/godotengine/godot/files/2801080/Bullet.video.zip)

**Comment by KoBeWi** [comment]
Tested the repro in 3.2.2 and everything seems ok.
@DimaKiva Can you confirm?

**Comment by pouleyKetchoupp** [comment]
This is fixed now compared to 3.1 version.
