### ISSUE TITLE
DynamicFont size changes when loading project

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#24604]
**Godot version:**
3.1 (alpha4)

**OS/device including version:**
Windows 10 x64

**Issue description:**
Whenever I load my project, the font I set for GUI theme changes its size to 13. When I change it back (to 26), it's ok until I close the project and load again. It's saved properly, because I can even edit font resource externally and it has correct size, but when opening project, it changes itself to 13 every time. It's now even default value and it's 13 no matter what was the size before.

I didn't try doing everything to fix it, but it's obviously a Godot bug, so reporting it. Interestingly, I managed to copy the project, remove everything except font directory and the bug still happens, so you can check it in the reproduction project. Since I deleted everything, it might be faulty project settings or something.

**Steps to reproduce:**

1. Open the minimal project directory and check the Resources/Fonts/UIFont.tres (it should have size 26)
2. Open project
3. Check the same resource in the inspector -> now its size is 13
4. Fix the font and save
5. Everything is ok until you open the project again

**Minimal reproduction project:**
[BrokenFont.zip](https://github.com/godotengine/godot/files/2710208/BrokenFont.zip)

**Comment by zyq0825** [comment]
Same. Using NotoSansSC for gui. Set size 28 but becomes 13 every time I open my project.

**Comment by akien-mga** [comment]
@volzhs Do you want to poke at this issue? :)

**Comment by volzhs** [comment]
I looked it a few days ago but didn't get a clue.

**Comment by Zylann** [comment]
I found the call stack that causes the font to be changed to size 13:

![image](https://user-images.githubusercontent.com/1311555/52130821-83f04b80-263b-11e9-9ecc-248a4c0c0c00.png)

On this code, `df_output_code` ends up being the font that was set in `theme/custom_font`. This is the only place where that happens, I'm not sure yet why.
