### ISSUE TITLE
Allow tiles in a tileset to be rearranged in new tileset editor.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#24609]
**Godot version:**
3.1 alpha 4

**OS/device including version:**
Windows 10 64bit

**Issue description:**
There should be a way to change the tile ID order in the new tileset editor. For example if I have a wall tile on ID 0 and a floor tile on ID 1 I can swap them so the floor is ID 0 and the wall is ID 1.

Not sure what the editor for this should look like. Maybe a list of all the tiles in the tileset and buttons to rearrange them?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1769, as feature proposals are now tracked on the Godot proposals repository.
