### ISSUE TITLE
Spatial material's Uv offset doesn't work

### ISSUE THREAD

**Issue by foumfo** [godotengine/godot#24601]
**Godot version:**
Godot Engine v3.0.6.stable.official.8314054

**OS/device including version:**
Windows 10

**Issue description:**
A spatial material's Uv1 offset doesn't work, even if we change it's values

**Steps to reproduce:**
Add an image file as an Albedo texture to a cube's spatial material and then try to change the Uv1 offset values

**Comment by KoBeWi** [comment]
Seems fixed since 3.1
