### ISSUE TITLE
TileMap selection tool has strange behaviors

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24606]
Godot 3.1 alpha4

Reproduction steps:
1) Create a tilemap
2) Draw some tiles in it
3) Choose the rectangular selection tool in the `Tilemap` menu 
4) Select a rectangular area: notice messy jitter of the rectangle when you start.
5) Go back to 3) and notice it reproduces sometimes

As I retry more, I notice it does not reproduce 100%. However, I found some other strange behavior:
- If you choose the selection tool and click only once on a tile, without dragging, the selected area will span whatever position the mouse was during a previous selection, to the point you just clicked, seeming very random.
- I would have expected the single tile to be selected instead, which also makes me wonder what the "select a single tile" menu is even for (and doesn't work btw).

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 3.2 builds?

**Comment by Zylann** [comment]
Yes, I could reproduce 2 of the issues:
https://youtu.be/lRYasaG-RU4

**Comment by KoBeWi** [comment]
Fixed in 4.0 with the new tile editor.
