### ISSUE TITLE
Update Spinner always spinning after opening open scene window.

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#24619]
**Godot version:**

Godot 3.1 Alpha 4

**OS/device including version:**

OS: Windows 10 64-bit

**Issue description:**

After window open scene or save scene as opened, the update spinner is starting to spin and not stopping. Maybe the editor updating something?

**Steps to reproduce:**
Open project below, and select Scene > Open Scene or Scene > Save Scene As
Notice the update spinner is spinning forever.

**Minimal reproduction project:**

[CobaAlpha.zip](https://github.com/godotengine/godot/files/2711754/CobaAlpha.zip)

**Comment by KoBeWi** [comment]
Seems to have been fixed since 3.1 stable
