### ISSUE TITLE
Add warning when variable name is being shadowed in local scope

### ISSUE THREAD

**Issue by ondrowan** [godotengine/godot#24614]
Description from TSLint:

> When a variable in a local scope and a variable in the containing scope have the same name, shadowing occurs. Shadowing makes it impossible to access the variable in the containing scope and obscures to what value an identifier actually refers.

```
var a = 0

func whatever():
    var a = "string"   # This variable shadows global `a`
```

It leads to subtle errors and it'd be helpful if it there was a possibility to report it as a warning.

**Comment by akien-mga** [comment]
CC @vnen
