### ISSUE TITLE
Need help with draw_colored_polygon with texture

### ISSUE THREAD

**Issue by tinyleolin** [godotengine/godot#24613]
**Godot version:**

Godot Engine v3.0.6.stable.official.8314054 (installed from Steam)

**OS/device including version:**

Windows 10 version 1803 (OS internal version 17134.471)

**Issue description:**

I want to draw polygon with cutting image in it. And I use draw_colored_polygon in _draw.
The image file is the same size as the viewport rect, which is 600x600.
The code is like this:
```
var points = PoolVector2Array([
  Vector2(50, 50),
  Vector2(300, 50),
  Vector2(400, 300),
  Vector2(200, 500),
  Vector2(20, 300),
])
var color = Color("#ff777777")
var texture = preload("res://xxx.png")
draw_colored_polygon(points, color, points, texture)
```
But after running the program, there is nothing drawn on the screen.

I think I was using the function incorrectly. But the doc is of no help for me:
> void draw_colored_polygon( PoolVector2Array points, Color color, PoolVector2Array uvs=PoolVector2Array(  ), Texture texture=null, Texture normal_map=null, bool antialiased=false )
Draws a colored polygon of any amount of points, convex or concave.

And I can't find any useful resources about calling this function with texture.
What's wrong with my usage?

**Comment by tinyleolin** [comment]
Maybe I miss the `normal_map` parameter. What is the normal_map for in 2D drawing?
Any suggestion would be appreciated.

**Comment by cbrooks41647** [comment]
I was struggling with this too. The piece I was missing is that you must call draw_color_polygon from withing the _draw() function.
Here is my example that draws a blue rectangle. Sorry if the code isn't very clean.

func _draw():
	var pt1 = Vector2(0,0)
	var pt2 = Vector2(100,0)
	var pt3 = Vector2(100,100)
	var pt4 = Vector2(0,100)
	var pts = [pt1,pt2,pt3,pt4]
	var box = PoolVector2Array(pts)
	draw_colored_polygon(box,Color(0,0,255,1),PoolVector2Array(),null,null,true)

**Comment by Calinou** [comment]
@tinyleolin Have you been able to solve this following @cbrooks41647' advice? (`draw_` functions must be called in a `_draw()` function).

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.

**Comment by rokasv** [comment]
Here's a [minimal project](https://github.com/godotengine/godot/files/4786986/TEMP2.zip)

this is the entirety of the code used:

```gdscript
extends Node2D

const SIZE = Vector2(1,1)*5

var polygonPositions = PoolVector2Array()
var polygonUVs = PoolVector2Array()

var enabled = true

func _init():
	polygonPositions = [
		Vector2(0, 0),
		Vector2(1, 0),
		Vector2(1, 1),
		Vector2(0, 1),
	]
	polygonUVs = [
		Vector2(0, 0),
		Vector2(1, 0),
		Vector2(1, 1),
		Vector2(0, 1),
	]
	return
	
func _ready():
	update()
	return

func _process(delta):
	return
	rotation += 1/100.0
	update()

func set_enabled(value):
	enabled = value
	z_index = float(enabled)

func _draw():
	var tex = load("res://sprites/jigsaw_square.jpg")
	var pt1 = Vector2(0,0)
	var pt2 = Vector2(100,0)
	var pt3 = Vector2(100,100)
	var pt4 = Vector2(0,100)
	var pts = [pt1,pt2,pt3,pt4]
	var box = PoolVector2Array(pts)
	draw_colored_polygon(box,Color(0,0,255,1),PoolVector2Array(),null,null,true)
```

passing in a non-null texture produces a spam of 
```
E 0:00:01.083   getornull: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
  <C++ Source>  ./core/rid.h:160 @ getornull()
```
the texture is not drawn

Godot 3.2.1 stable

**Comment by KoBeWi** [comment]
Seems like you just can't load a texture inside `_draw()`. It works fine when you move the `var tex` outside method:
```
var tex = load("res://icon.png")

func _draw():
	draw_colored_polygon(polygonPositions, Color("fff"), polygonUVs, tex)

```
