### ISSUE TITLE
Video Overview of the new features in Godot 3.1

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot#24617]
Godot 3.1 is a massive release. We need a video to highlight some of the new features to help both existing and users learn about them in a short amount of time.

As there are so many changes, this video should in my opinion highlights the main improvements that benefit the largest amount of people.

The goal is to keep it short and sweet, a 1.5 to 2mn trailer That the team can use on the official website, on Steam, etc. Akien suggested this should be voiceless, only have music and text. Which is fine by me. It should at least work well without sound, e.g. when autoplaying from steam, youtube mobile, or social networks.

We will take care of the recording and editing this time around at GDQuest but we need some help to find great projects to showcase new features.

This follows the discussion we had on #5917 with @akien-mga 

You can find the preliminary list of features I´m looking to include for now. Feedback and suggestions for projects to showcase welcome! Ideally we should showcase each feature in the context of a fleshed out game project, or at least a demo that looks appealing.

## Rendering

OpenGL ES 2 renderer

## 2d

Meshes and skeletons
KinematicBody2d snapping and raycast, sync to physics

## Animation

New anim editor with audio and anim sequencing
Blend tree
root motion
new anim tree

## 3d

CSG
Softbody and physics improvements
Improved grid and interactions
Fixed normals generation?

### GDScript

Optional static typing
class<sub>name</sub>
Find and replace in all files

### Other

Visual shader editor
Cover the progress with C#
GDNative improvements

## UI

Inspector, with editable resources
Filesystem
Tileset editor

## Web

Websockets, improved high level multiplayer and security?

## Misc

Open Simplex Noise

**Comment by starry-abyss** [comment]
Sounds great! I have some opinions on the list though:

> Fixed normals generation?
> Find and replace in all files
I think those would look a bit silly for non-users. Like: "hey look, we broke normals; hey look, now we fixed them" and "hey, we had a bad text editor, now it's finally usable for real".

Visual shader editor and open simplex noise could be moved to rendering. Yes, visual shader editor was there in older version already, and open simplex noise is not only useful in rendering, but those are things that "look cool" for non-users and should be IMHO moved from misc to some front category.

All scripting-related except visual shader editor could be merged.

Also maybe shouldn't have an explicit UI category, as half of improvements outside of it are UI-related too. Tileset editor is totally a 2D category feature.

Probably it makes sense to add audio input features (midi, microphone, etc) to highlight?

And last but not the least, the documentation is now much better, isn't it? :)

**Comment by eon-s** [comment]
Fixed things on the renderer, performance improvements, etc., are more for a detailed changelog which are interesting to professional devs.

The video is better to showcase new tools, maybe more oriented to (level, animation, art, environment) designers.

**Comment by NathanLovato** [comment]
The categories are unrelated to the video's edits - just here to help keep track of what's planned to cover in different areas of the engine.

This isn't a marketing video: it's a new features overview, it's for existing users as well as people who are interested in the engine already. The absence of a global find and replace was a pain point in 3.0 - I'm sure people would be happy to see it's there now. Pointing out the docs are better is along the same line.

**Comment by NathanLovato** [comment]
@akien-mga I started working on the trailer. There's little material to showcase the new features at this point. I don't have the time or resources to make good ones by the release. Busy schedule as you know 😄

I'm going to prepare a non-exhaustive video with the material I have and try to make it look sexy. Then as more devs start to use 3.1 we can work on an updated trailer in a few months. Sounds okay to you? If we have the budget with the KS, I'd like to work on a "new in Godot 3.1" series for the docs, which would be an opportunity to prepare more demos for a future video. It's just by the end of the month it's impossible for me to prepare all that.

**Comment by NathanLovato** [comment]
With the Kickstarter done I'm working on the video right now. I'll upload a test drive later.
I told Rémi there's a big lack of polished material/demos to record so I'm doing a simple trailer to start with, and that we can always do a new video later. As the community funded a video series dedicated to the new features in Godot 3.1, we'll also get to produce some extra videos and demos for the official docs starting next month.

**Comment by NathanLovato** [comment]
Here's a sample edit. https://youtu.be/V7vX4xS0aFk
Can you tell me if this can do the job?
The music is royalty free, by my friend https://www.youtube.com/user/Lokibdx

**Comment by akien-mga** [comment]
That looks awesome :)

**Comment by NathanLovato** [comment]
Here's the current teaser video: https://youtu.be/qr8JJ2g9EUw

I'm moving back from Japan to France on the 28th, taking 4-5 days to travel from Monday, so I won't be around to tweak the project then. I can work on changes this week-end.

I lack demos and the time to produce convincing demos for the features that aren't in the video now. And I've got to prepare our next projects now. I can't get the 2d mesh deform, CSG loft, and a few other features to work properly still on a custom build from today. And there were few demos to use from the community. So if that's fine by you, I'd like to keep this project to a teaser that should link to the release notes when they're out.

Is there anything to change or suggestions to improve the video? Also, if someone wants to take it and do a lot more work on the video from there, I'll gladly share the full Blender 3D project.

Do you have a release date set already? Can I schedule the teaser for release on GDquest on top of the Godot youtube channel?
I'll also prepare a Youtube thumbnail.

**Comment by akien-mga** [comment]
Looks great! I think it's fine in the current state with a link to the release notes yeah.

You're welcome to post it on the GDquest channel too. There's no release date set yet, we'll probably know it only at the last minute. I think we'll manage to release before the end of February, but can't really say yet what day exactly.

One thing though: the link at the end should be godotengine.org, not .com :)

**Comment by JFonS** [comment]
The video looks great :D
My only nitpick is the list of features after "and much more" goes away really fast, impossible for me to read through.

**Comment by mrcdk** [comment]
If you want, you can use this one for the new `Skeleton2D` animation: [godot_animation_test.zip](https://github.com/godotengine/godot/files/2869968/godot_animation_test.zip)

Example video: https://streamable.com/4tcy7

It's my first animation with this, learned about it today. It uses `Polygon2D` with the `Skeleton2D` and `Bone2D` and also uses some `Polygon2D` meshes to deform part of it (like the bottom half of the dress) The animation isn't perfect though but I wasted too much time on this 😅

**Comment by NathanLovato** [comment]
@mrcdk Oh so that was it! You've got to draw every polygon by hand if you use internal vertices 😯
Thanks, now I can make the Gobot work. Gonna add it now.

**Comment by NathanLovato** [comment]
The video is done! I addressed your feedback as well. Here's a link to the unlisted version: https://www.youtube.com/watch?v=9dvfvKeYbxI
@akien-mga I'm sending you the source files directly
