### ISSUE TITLE
Godot alpha crash with high memory usage

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#24618]
**Godot version:** alpha 4

**OS/device including version:** ubuntu 16 64 bit

**Issue description:** it just freeze when deleting more than 25 track in animation editor. after wait for 5 minute godot memory increase to over 3gb and just crashed. godot also crash during moving multiple keyframe from different track. i don't know where godot put the log file if someone tell me where it is,  i will attach to this issue later on. 

merry christmas

📣📣📣📣

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by akien-mga** [comment]
Could you provide an example project that allows to reproduce the crash easily?

**Comment by fian46** [comment]
[crash.zip](https://github.com/godotengine/godot/files/2900132/crash.zip)
just try to delete mote than 10 track on model/zombie.tscn and editor will hang for sometimes and crash eventually.

**Comment by hpvb** [comment]
@fian46 this is not a valid project, it's only part of a project. For the future could you please make a complete project as a repro case? It saves us a lot of time, there are a lot of bug reports to go through.

**Comment by hpvb** [comment]
We seem to be hitting some loop because of this: 
`Object was deleted while awaiting a callback`

**Comment by fian46** [comment]
yes it is just 1 scene. i am sorry i think the project is too large to upload.

**Comment by fian46** [comment]
next time i will make minimal project before upload
