### ISSUE TITLE
popupmenu id_focused does not work with mouse

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#24628]
**Godot version:**
Godot Engine v3.1.alpha.calinou.10e9221

**OS/device including version:**
Windows 10

**Issue description:**
popup menu "id_focused" does not trigger when the mouse are focusing the item, only when you focus with the arrow keys.

the signal "mouse entered" work but that one does not return the id of the item focused.

**Steps to reproduce:**
create popupmenu and connect the id_focused signal

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/2712619/example.zip)

**Comment by Norrox** [comment]
Yeah there are a signal id_pressed that does that, but i think it should be focused when the mouse are over the corresponding item, it opens the next sub menu without me clicking anything.

**Comment by Norrox** [comment]
Or maby it's possible to add some checkbox in the popup menu's node that "use mouse to focus" alternative?

**Comment by eon-s** [comment]
The "focus on hover" is something I have only seen on some linux desktop envs.

Optional "focus on mouse enter" and "lose focus on exit" could be good for some emergent menus, but is nothing that cannot be done by a small script too.

**Comment by KoBeWi** [comment]
This is not a bug actually, the documentation states that the signal is emitted on `ui_up` and `ui_down` actions. Since this is intended behavior, you [should probably fill a proposal](https://github.com/godotengine/godot-proposals) if changing it is still wanted.
