### ISSUE TITLE
System.IO.FileNotFoundException: Cannot find the MSBuild executable.

### ISSUE THREAD

**Issue by skarmiglione** [godotengine/godot#24627]
alfa 4 3.1
**Godot version:**

linuxmint 19

**OS/device including version:**

crash opening a demo skyofsteel
**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

[System.IO.FileNotFoundException: Cannot find the MSBuild executable.txt](https://github.com/godotengine/godot/files/2712479/System.IO.FileNotFoundException.Cannot.find.the.MSBuild.executable.txt)

**Comment by akien-mga** [comment]
Do you have MSBuild installed...?

**Comment by Supatier** [comment]
I'm also having this issue on LinuxMint.
It seems that godot is not finding `msbuild`. I installed mine from the mono apt repo and the binary is installed in `/usr/bin/msbuild`
Adding this line (63) in `godotsharp_build.cpp` works.
![screenshot from 2019-02-03 19-14-09](https://user-images.githubusercontent.com/19777767/52176632-ea19d180-27e7-11e9-9856-02083123fe86.png)

**Comment by neikeq** [comment]
It should also be looking for it in $PATH. Is `/usr/bin` not in $PATH?

**Comment by Supatier** [comment]
it is. I can call msbuild from the terminal.
>`/home/abc/.local/share/umake/android/android-platform-tools/platform-tools:/home/abc/.local/share/umake/bin:/home/abc/.local/bin:/home/abc/bin:/home/abc/.local/share/umake/android/android-platform-tools/platform-tools:/home/abc/.local/share/umake/bin:/home/abc/.local/bin:/home/abc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/abc/.dotnet/tools:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin/x86_64:/opt/rocm/bin:/opt/rocm/opencl/bin/x86_64:/opt/rocm/bin:/opt/rocm/opencl/bin/x86_64:/home/abc/.local/share/FlutterSDK/flutter/bin:/home/abc/.local/share/FlutterSDK/flutter/bin`

**Comment by neikeq** [comment]
@Supatier I am assuming you built from latest master and your issue is the same as #25592, which is different from this.

**Comment by akien-mga** [comment]
@skarmiglione Can you still reproduce this issue in 3.1 beta 3 or later?

**Comment by Supatier** [comment]
@neikeq Yep, that fixed it

**Comment by aaronfranke** [comment]
Fixed in #25593
