### ISSUE TITLE
RayCast2D not colliding with AutoTile collision

### ISSUE THREAD

**Issue by sicienss** [godotengine/godot#24632]
**Godot version:**
3.1 alpha 4 (downloaded from [here](https://hugo.pro/projects/godot-builds/))

**OS/device including version:**
Windows 8, Toshiba Satellite

**Issue description:**
`RayCast2Ds` colliding with `AutoTiles` exhibit strange behavior when calling `is_colliding()`.

If you start a scene with a `RayCast2D` fully inside of an `AutoTile` which has collision, calls to `is_colliding()` sometimes return `true` and sometimes return `false`.

I have not confirmed a pattern, but it seems like if the `RayCast2D` is fully outside of the collision shape on the previous run, if you then move it inside the shape and restart the scene, calls to `is_colliding()` return `false` when it should be `true`.

**Steps to reproduce:**
1. Create a `TileMap` with an `AutoTile` which has collision.
2. Place a `RayCast2D` in the scene and check the output of `is_colliding()`.
3. Start the scene with the `RayCast2D` in various places, inside and out of the `AutoTile`.
3. Eventually, calls will return `false` when the ray is fully inside the tile, which is undesirable.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2714014/TestProject.zip)

**Possibly Related:**
https://github.com/godotengine/godot/issues/9923
https://github.com/godotengine/godot/issues/13319

**Comment by vinf100** [comment]
I do not think that this is a bug. Ray casts check for intersections, so if the ray is completely inside the tile, then the ray will never intersect, thus returning "false". Are you doing a ray cast for any specific reason? Asking because I think you might be looking for another type of collision detection,

**Comment by sicienss** [comment]
The inconsistency of the output does suggest to me that something is wrong, even if the intended behavior should return false when the ray is completely ensconced.

I discovered the issue while prototyping a technique for finding gaps. In order to determine if my enemies should chase my player, I draw an imaginary line between enemy and player and raycast down at regular intervals, looking for gaps. If there's ever a raycast that doesn't collide, I know the enemy should not enter its chase state.

**Comment by vinf100** [comment]
When I tested it , I did not personally get any inconsistent results. When the ray was outside the tile, or when it was fully enclosed by the tile, it returned false, and it returned true when it was partly in the tile. 

When you say "draw an imaginary line", do you mean you did a ray cast from the enemy to the player?

**Comment by sicienss** [comment]
The imaginerary line was just a figure of speech to explain the technique. It doesn't correspond to anything in the code. The only raycasts are those that cast straight down, looking for gaps in the floor.

**Comment by sicienss** [comment]
The imaginary line was just a figure of speech to explain the technique. It doesn't correspond to anything in the code. The only raycasts are those that cast straight down, looking for gaps in the floor.

**Comment by vinf100** [comment]
Okay, I see. I think it might be better to do something like define an area where the enemy can go. So if it's on a platform, make a rectangle surrounding the platform, then just check if the player is within that area. Does this sound like something that might work for your use case?

**Comment by vinf100** [comment]
Because it sounds like doing so many ray casts would be somewhat inefficient and error prone. You could attach an Area2D node to your enemy. Area2D has signals when something enters and exits the place where your enemy is "patrolling".
