### ISSUE TITLE
KinematicBody triggers body_exited signal when intersecting with Area when both are still

### ISSUE THREAD

**Issue by torresguilherme** [godotengine/godot#24631]
**Godot version:**

3.1 alpha4

**OS/device including version:**

Linux openSUSE Tumbleweed
OpenGL ES 3.0 Renderer: AMD Radeon (TM) RX 460 Graphics (POLARIS11, DRM 3.27.0, 4.19.8-1-default, LLVM 6.0.1)

**Issue description:**

A kinematic body intersecting with an Area should trigger the body_exited signal when it exits the area, but it does so when both stop moving. 

**Steps to reproduce:**
Create a new project, leave physics as default.
Create an Area with a body_entered and a body_exited signals connected, both functions with print statements.
Create a KinematicBody with a controller, move_and_X it into the area and immediately stop moving it. You will notice that body_exited gets called. 

**Minimal reproduction project:**

[KinematicVsArea.zip](https://github.com/godotengine/godot/files/2713322/KinematicVsArea.zip)
![screenshot from 2018-12-27 18-21-29](https://user-images.githubusercontent.com/15815983/50493757-b4264800-0a06-11e9-91ba-938f6bcc7ed0.png)

**Comment by akien-mga** [comment]
The bug doesn't seem reproducible in 3.2.2 RC 2, so I assume it was fixed since the initial report.
