### ISSUE TITLE
Stuck at the opening of the project for editing.

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#2464]
It is not clear for what reason, and after some action, but sometimes the following occurs:
Start the editor. Try to open the project and application. A window opens and immediately hangs up.
If you open and close the editor again, it will be the same.
Only helps to restart your computer.

![gd_err_2015_09_12](https://cloud.githubusercontent.com/assets/233268/9830285/4ba384c0-5931-11e5-9e72-fcac078c19e3.jpg)

**Comment by Ace-Dragon** [comment]
It looks like you're using Windows 10. I don't think Godot has been well tested on that version and it's also not the only game engine that is reported to have issues on it either.

Does the frequency of occurrence depend on the project being opened or is it random?

**Comment by ret80** [comment]
Как я устал! Не оптимизирован, нужно подождать, вам не подходит. На все вопросы и сообщения о проблемах слышу только это. Хочу сказать пару русских слов. Но не буду. Мир вашему дому!

**Comment by Ace-Dragon** [comment]
I activated a plugin in Godot for the first time a couple days ago and that caused the application to self-destruct whenever a project is opened. This was Godot 1.1 on Windows 7 64 bit (deactivating the plugin solved everything).

Could this be the problem? I also have some apparent good news then in that it appeared to have been fixed in builds later than the official release.

**Comment by ret80** [comment]
If you build Windows version of Linux for the crash is lost.
While I do not understand what determines the crash. Try different options and how will the new information, I will write.

**Comment by akien-mga** [comment]
I believe some users are now successfully running Godot 2.0 alpha on Windows 10. Could you try a nightly build of 2.0 to confirm if it works?

**Comment by ret80** [comment]
Since the bug does not happen as often, and it is difficult to catch. Close ticket. We believe that fixed.
