### ISSUE TITLE
Editor FPS are halved (or more) on AMD cards when set to "Update changes"

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24644]
Godot 3.0.6
Godot 3.1 alpha4
Windows 7 64 bits
AMD Radeon HD 6670

This is an AMD variant of what I believe is another driver doing things pretty badly when an app does not always render every frame at 60 fps. The twist here, is that it happens even if the editor would have to render every frame anyways. This causes extremely noticeable lag, basically half the FPS it should have, or less.

Reproduction steps (on my current machine):
1) Create an empty scene, add a `DirectionalLight` and a `MeshInstance`
2) Put a `PlaneMesh` on the `MeshInstance` with 100x100 subdivisions
3) Set the editor to update always using the top-right update spinner
4) Look at the plane so that it fits in the screen, and pan in circles with the mouse to force the editor to redraw every frame: notice it runs smoothly at 60 fps.
5) Now, set the editor to "update changes" (which is the default), and redo the same as 4): notice the editor became laggy as if it went down to 30 fps or less. This does not go away after a while, the editor stays at this very low framerate no matter what.

And as usual, this then affects everything (since the editor can do everything), from 3D to script edition.
I even tried to put particles in the scene to force 60 fps, or put `TIME` in the shader editor, to no avail. It just doesn't want to go above 30.

I know there is a good chance that this is partially dependent on drivers, but when I see that Godot is able to render at 60 fps flawlessly on the other mode... there must be room for improvement in the way Godot actually decides to redraw, especially in cases where it actually HAS to, like shown in the steps above.

**Comment by reduz** [comment]
This is on purpose to avoid high amounts of CPU usage from the editor.

**Comment by Zylann** [comment]
I know this very well at this point... but how is that related to forcing something like 30 fps or less? Is that also really intented, especially since it doesn't repro on another hardware? Running that slowly when things actually happen in the editor can't be right.

There is some bonus though: since this is Windows 7, I tried to switch off Aero using another theme: it fixed the issue. Why don't things just work these days xD
