### ISSUE TITLE
Custom resource type appears in every resource dropdown, even if the class would mismatch

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24643]
Godot 3.1 alpha4
Windows 7 64 bits

I defined a custom resource type named `HTerrainData`, which is registered this way:
```gdscript
const HTerrainData = preload("../hterrain_data.gd")
[...]
add_custom_type("HTerrainData", "Resource", HTerrainData, get_icon("heightmap_data"))
```
However, I noticed that my resource type now shows up everywhere, sometimes multiple times, even in places where it has nothing to do:
![image](https://user-images.githubusercontent.com/1311555/50522276-5c511500-0aca-11e9-8971-0ec54c61af35.png)

Even for textures:
![image](https://user-images.githubusercontent.com/1311555/50522324-9b7f6600-0aca-11e9-889b-37db02187bac.png)

Reproduction steps:
Create an editor plugin that registers a custom resource type.

**Comment by JFonS** [comment]
Comment on note: I's fine to have ShaderMaterial in the process material slot, that's expected.

**Comment by Phischermen** [comment]
I've been working on a pull request (#34828) to solve this. It works on the 3.2 branch, but not on the 4.0 branch. I did some further testing, and I think that custom types seem to be broken in 4.0, but I haven't opened a formal issue yet.

**Comment by KoBeWi** [comment]
Looks like custom types don't appear in resource lists at all now. They are only listed in New Resource menu in FileSystem Dock, but only if the base type is Resource.

Technically the original issue is fixed, so closing. Custom types are supposed to have been deprecated by now. `class_name` custom type will work correctly.
