### ISSUE TITLE
When a script extends from a class with a custom icon, the base class icon is used instead

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#24657]
My expectation would be that when extending from a class, it would show the class icon, not the base class icon.
In a similar fashion, when extending from a class with a custom icon, and naming the new class with class_name and providing a path to new icon, no icon is used at all - I would expect the new icon path to be used in that case (always to 'topmost' one).

Usecase:
![shot_181229_163633](https://user-images.githubusercontent.com/7307968/50539927-d051f280-0b88-11e9-8414-7fb4302998a4.png)

I use custom classes for Effects and EffectComponents. EffectComponents are usually extended, with some added functionality - I then lose the benefits of custom icons (which, when they work, are awesome : )

@willnationsdev

**Comment by willnationsdev** [comment]
This is likely a matter of `EditorNode::get_object_icon` and/or `EditorNode::get_class_icon` not performing an inheritance loop check for any inherited icons in the case that one is not found.

**Comment by willnationsdev** [comment]
@PLyczkowski Was this using a CustomType or a Script Class?

**Comment by PLyczkowski** [comment]
This was using the class_name keyword, with a path to icon
