### ISSUE TITLE
Unable to declare custom signal

### ISSUE THREAD

**Issue by kamstrup** [godotengine/godot#2465]
If I read the wiki https://github.com/okamstudio/godot/wiki/gdscript correctly, custom signals are just declared like this:
```
extends Node

signal my_signal

func _ready():
    pass
```

This does not work however. I get an error "Unexpected token: Identifier: signal" no matter what I try (with or without signal args, for instance).

This is with Godot 1.1 on OSX Yosemite.

**Comment by neikeq** [comment]
The signal keyword was added after 1.1, so you will have to use the `add_user_signal` method until 2.0 is released.

**Comment by kamstrup** [comment]
Ah :-) Maybe we should note that in the wiki

**Comment by kubecz3k** [comment]
Probably a good idea would be to close this issue, since it's not real.
