### ISSUE TITLE
deg2rad comparisons don't work as expected

### ISSUE THREAD

**Issue by matthieudesprez** [godotengine/godot#24652]
(build:official), (hash:83140541dc91c29a288d7dd71044780b50b2cc4b), (major:3), (minor:0), (patch:6), (status:stable), (string:3.0.6-stable (official)), (year:2018)

the following : 
```
prints(deg2rad(180) / deg2rad(360), deg2rad(180) / deg2rad(360) == 0.5)
prints(deg2rad(337.5) / deg2rad(360), deg2rad(337.5) / deg2rad(360) == 0.9375, deg2rad(337.5) / deg2rad(360) > 0.9375)
prints(deg2rad(360), deg2rad(360) == 6.283185, deg2rad(360) > 6.283185)
```
prints : 
```
0.5 True
0.9375 False True
6.283185 False True
```
Internal values of deg2rad and their calculation results are not what they look like when printed or used in a == comparison

**Comment by isaacremnant** [comment]
This isn't a bug. `print("%.16f"%(deg2rad(337.5) / deg2rad(360)))` outputs 0.9375000000000001, which is not equal to 0.9375. 

This means that gdscript will print floats with a maximum precision and trim the trailing zeros when the format is not specified. On the other hand, you can't expect the result of floating point operations to be accurate down to machine precision, so `==` shouldn't be used for floats. Use something like `abs(value - expected) < tolerance`.

**Comment by matthieudesprez** [comment]
Thanks, I didn't think about the format syntax in print and I will stick to it for float values, though I was expecting print to actually outputs the whole value.

I use those comparisons mostly in unit tests, and I ended up rounding the value to avoid dealing with tolerance.
