### ISSUE TITLE
Godot does not support alpha in EXR images

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#24659]
**Godot version:**
3.1-alpha4

**OS/device including version:**
Ubuntu 18.10, GTX 970 (410.78)

**Issue description:**
Godot does not load/support alpha channels in EXR images.

**Steps to reproduce:**
Just create a simple image with transparency in GIMP and save it as `.exr`.

**Minimal reproduction project:**
[exr-alpha-test.zip](https://github.com/godotengine/godot/files/2716592/exr-alpha-test.zip)

**Comment by akien-mga** [comment]
At least there is code to support the alpha channel in https://github.com/godotengine/godot/blob/master/modules/tinyexr/image_loader_tinyexr.cpp, but maybe something is broken.

**Comment by timoschwarzer** [comment]
I'll take a look at this.

**Comment by akien-mga** [comment]
I found the issue.

**Comment by timoschwarzer** [comment]
Well, thanks! :)
