### ISSUE TITLE
Add an option to select assets to be imported instead of auto-import

### ISSUE THREAD

**Issue by LATRio** [godotengine/godot#24662]
I couldn't find similar suggestion, so... 
It would be great if user is given an option to select assets that don't need to be imported. Something like this would be quite user friendly:
 - Dialog shows up, which shows all files that can be imported.
 - User selects assets that need to be imported.
 - Godot imports all the selected files and adds unchecked files/folders into "res://.gdignore" file (would that mean that Godot will ignore eveything in res:// ? ).

Optionally:

In case user accidentally unchecked assets that should be imported:
 - Add an option to select files from ignored list

In case user accidentally checked assets that shouldn't be imported:
 - Add an option to right click and add file/folder into .gdignore

...sorry for bad english...

**Comment by timoschwarzer** [comment]
You can create a `.gdignore` file in directories from where assets shouldn't be imported.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/47268, closing.
