### ISSUE TITLE
Boot splash image is not showing in HTML5 export.

### ISSUE THREAD

**Issue by simpleyo** [godotengine/godot#24665]
Godot version:
Godot 3.1 alpha 3

OS/device including version:
Windows 7 Ultimate x64

Issue description:
Boot splash image is not showing in HTML5 export.

Editor shows error:
core/image.cpp:1742 - Loaded resource as image file, this will not work on export: 'res://splash.png'. Instead, import the image file as an Image resource and load it normally as a resource.

**Comment by eska014** [comment]
The default HTML page is not supposed to show the boot image. Since we also have to display a progress bar above it, we have no way to tell if it'll look acceptable.

The file is exported as a PNG file for usage in custom HTML pages.
