### ISSUE TITLE
Godot 3 Custom Drawing unusable Framerates on Android

### ISSUE THREAD

**Issue by Skyfish1** [godotengine/godot#24671]
**Godot version:**
3.0.6-stable

**OS/device including version:**
Android 8.0.0/ Samsung Galaxy S7

**Issue description:**
_Edited_
2D Game has as stable 60 FPS (with Sprites, large Textures, a lot of Stuff ) until I add just the simplest custom drawing script e.g. for drawing the outline of a Node2D. Now the framerate on my Android S7 drops dramatically to about 6 FPS with just a few instances of that Node2D + custom drawing. A custom _draw() kills fps more than anything.

**Update**: I'm not refering to the Polygon2D issue but to the slow **Custom drawing** on any Node2D. Therefore I attached a second project with only Node2D instead of Polygon2D  and edited the description to be more precise.

**Steps to reproduce:**
Example Project attached. Just hit the buttons to add Node2Ds with and without outline (custom draw) and watch the framerate drop on Android device.

**Minimal reproduction project:**
[CustomDrawingSlowOnAndroid.zip](https://github.com/godotengine/godot/files/2717474/CustomDrawingSlowOnAndroid.zip)
[CustomDrawingSlowOnAndroid_Node2D.zip](https://github.com/godotengine/godot/files/2719254/CustomDrawingSlowOnAndroid_Node2D.zip)

**Comment by Skyfish1** [comment]
@volzhs the Poly2D part yes, but the custom drawing part which is my main issue I didn't find any open issue. I have the same problem if I use just a Node2D with custom drawing instead of Polygon2D. Here is the same project without Poly2D and it has the same issues.
[CustomDrawingSlowOnAndroid_Node2D.zip](https://github.com/godotengine/godot/files/2719253/CustomDrawingSlowOnAndroid_Node2D.zip)

**Comment by volzhs** [comment]
I didn't test it recently but I had a same problem with `draw_line` while ago.
I guess it's also 3.1 issue. cc @akien-mga @reduz

**Comment by Araken** [comment]
If someone is looking for a workaround(like I did for days) for this issue try changing the buffer sizes in Project Settings > Rendering > Limits. Lowering all of them to 4kb in official Godot 3.1.1 build drastically improved FPS in my game when rendering custom shapes.

Also this issue is probably related to #25400, that's where I've found this workaround.

**Comment by ZodmanPerth** [comment]
Workaround didn't work for me.  I don't think this is a driver issue anymore, but a legit issue with Godot.

https://github.com/godotengine/godot/issues/25400#issuecomment-530345891

I'll reiterate here; I'm happy to work with someone to do what it takes to get this fixed.  At the moment it could kill my entire project.

**Comment by ZodmanPerth** [comment]
Fortunately I've been able to switch to drawing with 2D meshes and cleared myself a way to progress forward.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Skyfish1** [comment]
I tested it on the same device. Steady 60 FPS with custom drawing.  Problem is now solved on 3.2.3.
