### ISSUE TITLE
The autocomplete menu appears above the edited line (regression from #24553)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24674]
Godot 3.1 ee6f1fa3f8a7aa48ed9becb0039f39e1c7f395cc
Windows 10 64 bits

The completion proposals menu is drawn above the current line, it should be below it.

![image](https://user-images.githubusercontent.com/1311555/50553829-05ecfd80-0ca7-11e9-9eac-0e3cd72f3a9b.png)

**Comment by SoIAS** [comment]
I am on it.

**Comment by akien-mga** [comment]
It's a regression from #24553, CC @thomasruiz @Paulb23.
