### ISSUE TITLE
Headless for Godot Mono?

### ISSUE THREAD

**Issue by pbzweihander** [godotengine/godot#24675]
Are there any ways to build/export mono version of godot project in headless cli?

I want to build and deploy godot project with CircleCI, but it needs docker image of godot to do so.

**Comment by akien-mga** [comment]
Same way as for non-Mono headless binaries a priori.
```
scons p=server tools=yes target=release_debug module_mono_enabled=yes mono_glue=no
```
(provided you have generated the Mono glue already, see http://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html)
