### ISSUE TITLE
Crash on switching to inherited Scene

### ISSUE THREAD

**Issue by trommlbomml** [godotengine/godot#24672]
**Godot version:** 

3.1. Alpha 4

**OS/device including version:**

Windows 10 x64
Geforce GTX 860m

**Issue description:**

The editor crashes when I open an inherited scene from the FileSystem dock after the base scene has been changed and both of them are already available in the scene tabs. Is very simple to reproduce on my machine.

**Steps to reproduce:**

1) Open attached Project
2) Open Scene monkeys/monkey_left.tscn (inherited)
3) Open Scene monkeys/monkey_right.tscn (base scene, now active tab)
4) Edit visibility of Node monkey/Bubble.
5) Save Scene
6) Go to FileSystem dock and double click on monkey_left.tscn

**Minimal reproduction project:**
I have uploaded my whole project, because it is only 24MB in total:

[project.zip](https://github.com/godotengine/godot/files/2717546/project.zip)

You can also clone from https://github.com/trommlbomml/geometry_primitives_godot.git commit dd96cc939af647b7d8ec5f3360d594327a5e05f7.

**Comment by akien-mga** [comment]
Seems related to #24967, both involving this deferred call:
https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/editor/filesystem_dock.cpp#L812

**Comment by akien-mga** [comment]
This should have been fixed by #25076, please report if you can indeed no longer reproduce the crash, or if it still happens.

**Comment by trommlbomml** [comment]
@akien-mga I have tested the fix with godot 3.1 beta 2. I am not able to reproduce the crash, works well :)
