### ISSUE TITLE
Script editor hint text is badly drawn after changing line height

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24676]
Godot 3.1

When you start typing arguments for a function in the script editor, it shows a hint, but the text for that hint is badly drawn:
![image](https://user-images.githubusercontent.com/1311555/50554362-c9260400-0cb0-11e9-8053-8971052c92d3.png)

It started happening after I change line height from 4 to 3, and continued happening regardless of font size. I tried changing line height back to 4, which fixed it. Then back to 3... and it didn't repro.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch / latest 3.2 builds?

**Comment by Zylann** [comment]
Could not reproduce in Godot 3.2 beta 5.
