### ISSUE TITLE
Set particles in state based on time

### ISSUE THREAD

**Issue by firefly2442** [godotengine/godot#2468]
Right now you can set the lifetime of a Particles2D object and it will run for that amount of seconds.  However, in GDScript, there is no way to reset that timer back to the beginning or to an arbitrary time in the animation phase.  You have to wait for it to reach the lifetime and finish the animation.  This means if you want to change the parameters and options of an existing Particles2D object, you will get inconsistent results based on where it was in the previous state of animation.  Being able to set the time (or at least restart it) would be helpful.

**Comment by reduz** [comment]
there is a preprocess method that will preprocess the particles up to some point in time, maybe a reset() method could be added so you can use it to reset the system and seek
