### ISSUE TITLE
CSGPolygon (with Path Rotation: PathFollow) -  weird end cap of mesh

### ISSUE THREAD

**Issue by websterek** [godotengine/godot#24682]
**Godot version:**
v3.1.alpha.official
alpha 4

**OS/device including version:**
Windows 10

**Issue description:**
_CSGPolygond_ in _Mode: Path_ with _Path Rotation set to PathFollow_ generates weird end of the mesh (inverted or offsetted). Beginning of the object seems to be ok.
![capture](https://user-images.githubusercontent.com/40537787/50559471-d74b4300-0cf7-11e9-82b4-1597043097f4.PNG)

**Steps to reproduce:**

1. Create Path with some points
2. Create CSGPolygon
3. Set CSGPolygon propeties like follow:
 Mode: Path
 Path Node: Path created in point 1
 Path Rotation: PathFollow

It's not happens all the time but in many situation.
You can move randomly last point of the curve to see it.

**Minimal reproduction project:**
[CSGPolygon_Bug.zip](https://github.com/godotengine/godot/files/2718254/CSGPolygon_Bug.zip)

**Comment by akien-mga** [comment]
Fixed by #28965.
