### ISSUE TITLE
Syntax highlighting breaking in github

### ISSUE THREAD

**Issue by schweigert** [godotengine/godot#24685]
The new godot 3.0 syntax is not working in github because of a legacy repository used to generate the grammar. Can not use some godot engine's own grammar system to support github view?

![image](https://user-images.githubusercontent.com/13274722/50560565-6ac94780-0ce9-11e9-94fd-b0c9c96024dd.png)

Repositories:

https://github.com/github/linguist
https://github.com/beefsack/GDScript-sublime

**Comment by timoschwarzer** [comment]
I think this issue does not belong to this repository but to the Linguist one (or wherever the grammar needs to be updated).

**Comment by schweigert** [comment]
The error comes from the https://github.com/beefsack/GDScript-sublime repository used by github. I thought it would be possible to keep the grammar files officially by godot.

**Comment by Calinou** [comment]
Closing, as this isn't related to Godot itself but to an external repository used for syntax highlighting by GitHub.

(For the record, this is still relevant today, especially when using static typing.)
