### ISSUE TITLE
Calling get_tree().reload_current_scene() from Area2D _on_body_entered() disables all collisions between kinematic bodies (2D)

### ISSUE THREAD

**Issue by fry-** [godotengine/godot#24694]
*could not find a similar issue*

**Godot version:**
3.1 alpha 3 and alpha 4
The issue does **NOT** happen in 3.1 alpha 2

**OS/device including version:**
Lubuntu 18.04 (64 bit)
GLES 2.0 used due to old graphics chip

**Issue description:**
When triggering `get_tree().reload_current_scene()` after a KinematicBody2D enters an Area2D (with `_on_Area2D_body_entered():`), all collisions between multiple KinematicBody2D's stop to work. Collision with between KinematicBody2D and StaticBody2D / Tilemap keeps working.
Also, the collision shape of the Area2D seems to be buggy after reloading the scene (in demo project, just press *right arrow key* after scene gets reloaded through Area2D / jumping in between somehow "fixes" this problem)
Surprisingly, when reloading the scene by a *Button*, everything works as expected.

After entering the Area2D, these Debugger errors occur:
- Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead
  <C Source>     servers/physics_2d/physics_2d_server_sw.cpp:734 @ body_set_shape_disabled()
  <Stack Trace>  reload_area.gd:4 @ _on_reload_area_body_entered()
- Function blocked during in/out signal. Use set_deferred("monitorable",true/false)
  <C Source>     scene/2d/area_2d.cpp:432 @ set_monitorable()
  <Stack Trace>  reload_area.gd:4 @ _on_reload_area_body_entered()

**Steps to reproduce:**
Make an Area2D node which triggers:
`func _on_Area2D_body_entered(): get_tree().reload_current_scene()`
Make a KinematicBody2D that moves into the Area2D.

**Minimal reproduction project:**
[kinematic_collision_bug.zip](https://github.com/godotengine/godot/files/2719376/kinematic_collision_bug.zip)
Left / right arrow key: move left / right
Up arrow key: jump
down arrow key: switch camera view (included for showing another bug, which is already reported here #23966)

**Comment by ripperdave** [comment]
I experience the same in 3.1 beta 1. It is not user friendly at this point.

I am disabling the collision in the animation player.

It was ok in 3.0.6.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch or latest 3.1 builds?

**Comment by ripperdave** [comment]
I have checked it on 3.1 Beta 6 this morning. It exists.

**Comment by akien-mga** [comment]
As per #26241, this seems to happen with `change_scene` and `change_scene_to` too.

**Comment by akien-mga** [comment]
I'll try to bisect what commit caused the regression.

**Comment by akien-mga** [comment]
It's a regression from 0b1e93ccd43815d93de031b4f23fbfcd9ae7a34c (similar to #26148).
