### ISSUE TITLE
CSGCombiner - CSG Geometry disappearing

### ISSUE THREAD

**Issue by rasikrodri** [godotengine/godot#24696]
**Godot version:**
Master

**OS/device including version:**
Window 7
NVidia 680

**Issue description:**
When having a CSGContainer as a child of another CSGContainer, and the child CSGContainer has shapes in it. If you repaernt that child CSGContainer to a none csg node outside of the parent CSGContainer all the geometry seems to be gone and it is also not drawn.

**Steps to reproduce:**
-Create a Spatial node with a CSGContainer as a child node. 
-Now create a CSGContainer as a child of the first CSGContainer.
-Add whatever geometry you like as child of that second CSGContainer.
--Reparent the second CSGContainer to remove it from the first CSGContainer and make it a child of the Spatial. ***ALl the displayed geometry of the reparented CSGContainer should now desapear.

**Minimal reproduction project:**
[CSGBug.zip](https://github.com/godotengine/godot/files/2719439/CSGBug.zip)

**Comment by golddotasksquestions** [comment]
Can confirm in Godot 3.2 alpha3

**Issue description:**
CSG objects when they are children of a CSG Combiner Node disappear completely and become unclickable in the viewport when the parent Combiner is put into another CSG Combiner and the Ctrl+Z to Undo or get reparented

**Steps to reproduce:**

1. Add CSG Combiner 
2. Add CSG Objects as children
3. Add another CSG Combiner 
4. In the Scene Panel, drag and drop the former CSG Combiner node with it's children into the newly created one
5. Press Ctrl+Z or reparent the Node by dragging it elsewhere

![csg_renderbug02](https://user-images.githubusercontent.com/47016402/67642869-8359bc80-f910-11e9-906c-28e8fa8c545b.gif)
