### ISSUE TITLE
SpotLight rotation not match on android device

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#24710]
**Godot version:** 3.1 alpha.calinou.09D0909

**OS/device including version:** Android Pie 64-bit GPU adreno 625 project setting using GLES3

**Issue description:** 
this is on android :
![screenshot_20190102-141314](https://user-images.githubusercontent.com/13792627/50581998-e23dd900-0e99-11e9-9fe9-5b2f7f46f541.png)
this is i expexted :
![screenshot from 2019-01-02 14-15-55](https://user-images.githubusercontent.com/13792627/50582006-f386e580-0e99-11e9-9fd1-d76afc93beb1.png)

**Steps to reproduce:**
add spotlight and rotate it, observe the different on desktop and android.

**Comment by fian46** [comment]
you are right, this is not bug. i switch it off and it worked. but fps going under 10 fps, any solution to make it look good while keep vertex shading on ?

**Comment by fian46** [comment]
we can close this now

**Comment by volzhs** [comment]
I just avoid using spot, omni lights for mobile.
maybe asking it on community channels could help.
