### ISSUE TITLE
Godot uses its own logo for Windows .exe file

### ISSUE THREAD

**Issue by miskatonicstudio** [godotengine/godot#24718]
**Godot version:**

3.0.6

**OS/device including version:**

Linux Pop!_OS 17.10 (Artful Aardvark)

**Issue description:**

Custom logo was provided and it visible when switching applications. But the .exe file uses Godot logo instead of custom logo:
![photo_2019-01-02_15-24-10](https://user-images.githubusercontent.com/36821133/50595893-98a5bc00-0ea2-11e9-9985-251181cca41e.jpg)

**Steps to reproduce:**
* build the program
* open file manager

**Minimal reproduction project:**

**Comment by volzhs** [comment]
AFAIK, godot changes exe icon with rcedit.
did you set it on editor settings?
![screenshot_20190102_233700](https://user-images.githubusercontent.com/8281454/50596394-80a45b80-0ee7-11e9-909f-a732732dff53.png)

**Comment by miskatonicstudio** [comment]
I didn't realize there are project export settings in Editor Settings screen. I will try that and let you know of the results. Thank you for your help.

**Comment by Calinou** [comment]
See [Changing application icon for Windows](https://docs.godotengine.org/en/latest/getting_started/workflow/export/changing_application_icon_for_windows.html) in the documentation.

**Comment by miskatonicstudio** [comment]
At the moment the Windows machine is unavailable, but it seems to be a working solution (will confirm later). However, for the future, this setting might be moved somewhere closer to "project icon" setting. Looking for custom icons in Editor Settings is a bit unintuitive.

**Comment by miskatonicstudio** [comment]
Thank you for your help @Calinou @volzhs !
