### ISSUE TITLE
Drag and drop reparenting

### ISSUE THREAD

**Issue by randyyaj** [godotengine/godot#2471]
Not sure if this has already been requested. It would be cool to be able to drag and drop one node, multiple nodes, or a group of nodes into another node for re-parenting instead of clicking the re-parent button to re-parent nodes.

**Comment by okamstudio** [comment]
Editor will eventually gain wide drag & drop support, but after version 2.0



On Mon, Sep 14, 2015 at 7:39 PM, Randy Yang <notifications@github.com>
wrote:

> Not sure if this has already been requested. It would be cool to be able
> to drag and drop one node, multiple nodes, or a group of nodes into another
> node for re-parenting instead of clicking the re-parent button to re-parent
> nodes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2471>.
>



-- 

*OkamStudio*

**Comment by philiplb** [comment]
+1 :)

**Comment by kubecz3k** [comment]
Closing since it's a duplicate of https://github.com/godotengine/godot/issues/570
