### ISSUE TITLE
Weird default name for the newly created nodes

### ISSUE THREAD

**Issue by OBKF** [godotengine/godot#24714]
**Godot version:** 3.1 build 9ba6849cf4191e1c037e7416d21f28b19e0e5f43

**OS/device including version:** Xubuntu 18.04LTS

**Issue description:**

I was making a demo project for this issue #24705 and When I tried to add a new node I had this weird naming on the newly created nodes.
![00](https://user-images.githubusercontent.com/12987951/50591697-2e385000-0e91-11e9-8a94-b6aa765c480f.png)

**Minimal reproduction project:**
The same example in the mentioned issue
[AnimationTreeBug.zip](https://github.com/godotengine/godot/files/2720700/AnimationTreeBug.zip)

**Comment by timoschwarzer** [comment]
Can't reproduce by opening the reproduction project and adding `Spaital`/`Node2D` nodes.

![image](https://user-images.githubusercontent.com/8849554/50639215-f567ac00-0f60-11e9-8fb3-3da7d697e965.png)

Godot 200be0795d1fc10c2628c00eafc0d276b669301e

**Comment by Naryosha** [comment]
Godot 200be07. Can reproduce with the given project.

1. Select AnimationTree node
2. Select root node (optional)
3. Create new node

**Comment by OBKF** [comment]
Nice
