### ISSUE TITLE
Problem with Particles2D Starting On By Default?

### ISSUE THREAD

**Issue by firefly2442** [godotengine/godot#2472]
![output](https://cloud.githubusercontent.com/assets/531175/9871615/69750caa-5b5a-11e5-8d5f-835f07b3fe14.gif)

I think there's some sort of problem with Particles2D starting ON by default.  Consider the following minimal test case:

```
extends Node2D

func _ready():
	var newParticle = Particles2D.new()
	newParticle.set_pos(Vector2(200, 200))
	newParticle.set_scale(Vector2(5, 5)) #make it easier to see
	
	newParticle.set_explosiveness(0)
	#newParticle.set_emit_timeout(2) #this is also the default lifetime

	add_child(newParticle)
```

Here are the three conditions:

1) Initial code, particles appear

2) Uncomment line 10, particles disappear

3) Change explosiveness on line 9 to 0.1, particles appear again

**Comment by Hamidreza65** [comment]
Hi!
Replace with one added line:
extends Node2D

func _ready():
	var newParticle = Particles2D.new()
	newParticle.set_pos(Vector2(200, 200))
	newParticle.set_scale(Vector2(5, 5))

	newParticle.set_explosiveness(0)
	newParticle.set_lifetime(1)
	newParticle.set_emit_timeout(2) #this is also the default lifetime

	add_child(newParticle)

**Comment by firefly2442** [comment]
@Hamidreza65, thanks!  That does fix the problem, however, I still think it's a bug since the default lifetime is 2.  I'm guessing the problem is in starting the particles on by default.  If you then change the parameters like explosiveness or other things, you have to wait for the lifetime of the initialization before it actually displays anything.

**Comment by reduz** [comment]
will add a reset method in case you want to force resetting the system
