### ISSUE TITLE
HTML5 export broken

### ISSUE THREAD

**Issue by ChronoDK** [godotengine/godot#24734]
**Godot version:**
3.1 alpha5 and alpha4

**Issue description:**
Won't load simple 2d scene with a single sprite.

**Steps to reproduce:**
Create a 2d scene, switch to GLES2 and export as HTML5. Run in browser and watch the console being spammed with errors.

It worked somewhat in alpha3, you just had to make a change to the _glRenderbufferStorage function in the exported js-file:
```
function _glRenderbufferStorage(x0, x1, x2, x3) {
    x1 = GLctx.DEPTH_COMPONENT16
    GLctx["renderbufferStorage"](x0, x1, x2, x3)
}
```

**Comment by akien-mga** [comment]
What OS and browser?

**Comment by ChronoDK** [comment]
Windows 10, every browser I have - Chrome is the one I usually use.

**Comment by eska014** [comment]
There hasn't been done any work yet to make GLES2 work in HTML5 export, so this is more or less expected.
We have several WebGL 1 issues open (https://github.com/godotengine/godot/issues?q=is:issue+is:open+webgl1+in:title), so I'll close this issue unless you want to report a specific new error

**Comment by LinuxUserGD** [comment]
2d works for me with webgl1. Only 3d doesn't work.
