### ISSUE TITLE
WorldEnvironment node Enable checkbox

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#24735]
Add "enable" checkbox for "WorldEnvironment", to activate and deactivate post process in the editor.

For example i use fog in the game, but in the editor the fog is also active and hides all objects under a color.

**Comment by timoschwarzer** [comment]
![peek 2019-01-03 13-39](https://user-images.githubusercontent.com/8849554/50638161-044c5f80-0f5d-11e9-8e8f-4bd73cadb532.gif)

**Comment by akien-mga** [comment]
This is possible already as shown in above GIF.

**Comment by Flavelius** [comment]
Is this possible at runtime somehow (toggling an environment on/off)? WorldEnvironment doesn't have a Visible nor an Enabled property.

**Comment by Calinou** [comment]
> Is this possible at runtime somehow (toggling an environment on/off)? WorldEnvironment doesn't have a Visible nor an Enabled property.

Yes:

```gdscript
# Disable
var old_environment = get_viewport().get_camera().get_environment().environment
get_viewport().get_camera().get_environment().environment = null

# Restore
get_viewport().get_camera().get_environment().environment = old_environment
```
