### ISSUE TITLE
Shader Editor usability issue due to Visual Editor's focus on hover

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#2473]
I recently started to work with shaders and there was a problem that is annoying me a lot:

The canvas and spatial visual editors will always get focus on mouse hover. Since the shader editor is in the same screen (both split), I constantly lose the focus when writing shaders without even noticing it and then I am forced to manually focus it again (when I never intended to lose the focus).

It would be good to have an option to disable this behaviour (visual editor focus on mouse hover).

**Comment by reduz** [comment]
yeah it should not steal your focus if it's on a text field, for some
reason it's doing it, so it's a bug

**Comment by neikeq** [comment]
It does not steal focus when editing a property text field or typing a node name. Seems to only happen with labels (like FileSystem's path) and textedit (like shader editor).

**Comment by neikeq** [comment]
Oh, it was already fixed in this commit!: ab22203
