### ISSUE TITLE
CollisionShape radius changed during run-time not VISIBLY reflected

### ISSUE THREAD

**Issue by ErwinBr** [godotengine/godot#24742]
**Godot version:**

3.0.6 stable official 8314054

**OS/device including version:**
Mac OS 10.14 (Mojave)

**Issue description:**

When I change the radius of a CollisionShape during run-time, the change is not visibly reflected during run-time.

**Steps to reproduce:**
- I enabled "Visible Collision Shapes" in the debug options of the project.
- On a parent node, I created an Area (3D) and a child node of CollisionShape
- I create signals to detect if another object enters the Area

- I change the radius of the CollisionShape in the editor to something small, say 10
- On the parent node, I created the script to change the radius to something bigger:

`func _ready():
	$DetectionRange/CollisionShape.shape.radius = float(80)`

- When I run the game, the CollisionShape is visible, but in the small size.
- When I enter the Area with another object, the signal does emit when I'm in the radius as set in the script!

Conclusion: The radius as set in code is respected, but not visible on-screen during play testing.

**Comment by timoschwarzer** [comment]
Seems to be fixed in 3.1:
![peek 2019-01-03 16-06](https://user-images.githubusercontent.com/8849554/50644569-80e93900-0f71-11e9-8e86-4d289f898be7.gif)

**Comment by Chaosus** [comment]
Ok, Closed as fixed then
