### ISSUE TITLE
Mono: Export debug templates are named incorrectly

### ISSUE THREAD

**Issue by exts** [godotengine/godot#24752]
**Godot version:**
3.1 Alpha5

**OS/device including version:**
Windows 10

**Issue description:**
When you attempt to export to any platform in debug mode it won't create the necessary `data_[PROJECTNAME]` folder along side your project exe.

**Steps to reproduce:**
1. Export a debug version of your game
2. Watch godot bitch about a missing data folder

```
Unhandled Exception:
System.IO.FileNotFoundException: Data template directory not found
  at GodotSharpTools.Editor.GodotSharpExport._ExportBegin (System.String[] features, System.Boolean debug, System.String path, System.Int32 flags) [0x000c3] in <00cae434203444ccb523f7c5daffa0ff>:0
ERROR: _export_begin: Method/Function Failed.
   At: modules/mono/editor/godotsharp_export.cpp:161
```
**Information**
Discussed on discord with neikeq and tmm the problem boils down to the export templates being named `debug_release` but the code is looking for `debug`

![explorer_2019-01-02_11-20-42](https://user-images.githubusercontent.com/16387107/50666202-32d83380-0f79-11e9-91c0-e045511152af.png)

![image](https://user-images.githubusercontent.com/16387107/50666247-7894fc00-0f79-11e9-9aeb-450b3bebdfe2.png)

**Comment by exts** [comment]
(cc @hpvb)

**Comment by akien-mga** [comment]
Should be `debug` indeed, to be consistent with what we do for non-Mono export templates (where "debug" builds are also compiled with `release_debug`).

**Comment by hpvb** [comment]
Shouldn't the export look for release_debug instead?

**Comment by akien-mga** [comment]
`release_debug` is an engine dev technicality, it's not relevant to end users who want a "build that can provide debug information", aka "debug build". That's what the `tools=no target=release_debug` is, as it provides some optimisation but still debug info.

I'm not against changing things, but I'd prefer to refactor the whole `target` business and it's not the time for that. No need to break compatibility now.

**Comment by hpvb** [comment]
Alternatively we could ship 'debug' templates instead of 'release_debug' templates, but I don't think we've ever done that either?

**Comment by akien-mga** [comment]
> The issue is that the release_debug, release, and debug names for the data folders get created by our buildsystem. If we name them the same a release_debug build would overwrite the data folder of a debug build in bin/. We never do that for anything.

We don't ship `target=debug` templates, so it's not really a problem. It's just a matter of adapting build scripts to properly rename buildsystem-generated names to engine-expected names.

> I also don't really like just randomly renaming the output of the build system, how are other people supposed to know they need to do that? :)

That's [documented](http://docs.godotengine.org/en/latest/development/compiling/compiling_for_x11.html#building-export-templates) :) It's the same issue with non-Mono templates where you need to map `godot.x11.opt.64` to `linux_x11_64_release` and `godot.x11.opt.debug.64` to `linux_x11_64_debug`.

Again, I agree that this could be rationalized, but this is not the time to do it just before beta. If you change the expected names for Mono, you should change them for non-Mono, and do away with `linux_x11_64_debug` and other legacy names, which is a compat breakage and will break CI of many users.

**Comment by akien-mga** [comment]
To clarify, my above comments are only concerning changing the current naming of "classical" export templates and our legacy "Debug template" == `release_debug` inconsistency.

For the Mono template itself, I'm not familiar with the process but it's fine with me to change the expectations of the mono exporter to use `release_debug` for the "debug" template.
