### ISSUE TITLE
Deleting specific branch of nodes from nested YSort tree causes viewport bug

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#24755]
**Godot version:** v3.1-alpha 65a86ae
**OS:** Windows 10.0.17134
**GPU:** NVIDIA GeForce GTX 980 Ti
**NVIDIA driver version:** 23.21.13.8813

**Issue description:**
Create a node tree that looks like this:
![image](https://user-images.githubusercontent.com/27100585/50669189-e3951000-1017-11e9-8952-f52d09ee0a90.png)

Delete the "Node2D" node, which should delete its "YSort" child node. The viewport will then be filled with infinitely-stacking copies of the whole editor:
![image](https://user-images.githubusercontent.com/27100585/50669201-f1e32c00-1017-11e9-8224-5aa9245dfc10.png)

Trying to run the project in this state causes the editor to crash. This happens under both GLES2 and GLES3.

**Minimal reproduction project:**
This comes with the full tree in place. Just delete the "Node2D" node and you should see the bug.
[ysort graphics bug.zip](https://github.com/godotengine/godot/files/2725745/ysort.graphics.bug.zip)

**Comment by akien-mga** [comment]
CC @bojidar-bg

**Comment by bojidar-bg** [comment]
Uh, um, it's a feature!

**Comment by bojidar-bg** [comment]
Just for the record: I couldn't reproduce the original issue locally on a debug build. I did get an outright crash when moving more (~20+) YSort nodes around though.
