### ISSUE TITLE
Scrolling down with the mouse wheel on a scrollbar causes it to snap to the bottom

### ISSUE THREAD

**Issue by Flairieve** [godotengine/godot#24773]
**Godot version:**

v3.1.alpha.calinou.ee6f1fa

**OS/device including version:**

Windows 10

**Issue description:**

When scrolling down with the mouse wheel at the same speed, for some reason the vertical scrollbar will snap quickly to the bottom of the scrollbar. This doesn't happen when your scrolling up with the mouse wheel at the same speed.

**Steps to reproduce:**
1. Create or open a large script file
2. Scroll down quickly
3. The scrollbar will snap directly to the bottom instead of scrolling smoothly to the bottom

Here's the video showing the bug:
https://streamable.com/t8rgy

**Comment by mateusfccp** [comment]
Could reproduce on 021421e. Only happens at relatively high speeds, if scrolling slowly, won't happen.

**Comment by timoschwarzer** [comment]
Working on this.
