### ISSUE TITLE
html5 problem set_locale

### ISSUE THREAD

**Issue by gra-frogger** [godotengine/godot#2477]
I try with manjaro 64 bit and windows 8.1 64bit in Italian, and emscripten give this message in same case, I post error of linux:

http://pastebin.com/yy9aGBQA

the windows error:

http://pastebin.com/9cYeT1Sq

**Comment by sergicolladosopra** [comment]
I have same error, I also work with manjaro

**Comment by sergicollado** [comment]
I have same error  also in Manjaro :(

**Comment by reduz** [comment]
ah i think i saw the error, probably because the way to get locale is not
well defined, leave this open and i will check it out befroe 2.0

**Comment by Geaxle** [comment]
>ah i think i saw the error, probably because the way to get locale is not
>well defined, leave this open and i will check it out befroe 2.0

Using a build from November 3rd, I have the same error on windows 10 and ubuntu 15 (both mozilla and chrome).

**Comment by akien-mga** [comment]
Error confirmed on a recent build:
```
[1;31mERROR: set_locale: [0m[1mInvalid Locale: C
[0;31m   At: core/translation.cpp:508.[0m
```

**Comment by nunodonato** [comment]
@reduz can we just fallback to "en" if LANG is "C"? I can do that fix and submit a PR

**Comment by akien-mga** [comment]
@nunodonato I'd say go for it, with a comment in the code linking to this issue so that it can be reassessed post-2.0.

**Comment by nunodonato** [comment]
@akien-mga I can try, but I'm not sure if my fix actually fixes this issue's problem. I tried setting my system to an non-existent locale and in fact godot prints that error, but still functions normally.

**Comment by akien-mga** [comment]
Yeah, it's not a big issue anyway (there are more annoying problems with the HTML5 template), so I think it can wait for a proper resolution in 2.1 :)

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by jeremyjh** [comment]
@akien-mga why do you say this is not a big issue? I think it is the reason the 3dPlatformer sample (and probably others) will not run in html5 even with latest master build - at least it is the only error message printed and output stops after it.

**Comment by jeremyjh** [comment]
Ah, nevermind. I don't think this is causing the problem actually; I implemented the fix suggested here and it doesn't change anything.

**Comment by desk467** [comment]
This error still remains on 2.1 :/
