### ISSUE TITLE
Array remove function is only returning null

### ISSUE THREAD

**Issue by Flairieve** [godotengine/godot#24776]
**Godot version:**

v3.1.alpha.calinou.ee6f1fa

**OS/device including version:**

Windows 10

**Issue description:**

When I upgraded to the latest version of Godot, I noticed that the array remove function now only returns null when it should return the array with the removed index.

**Steps to reproduce:**
1. Create or open an script
2. Make an array with some stuff in it
3. Use the array remove function
4. It returns null instead of the array with the removed index

**Comment by volzhs** [comment]
I checked 3.0.5 and 3.1.alpha 5e6c6f3bb
`void remove( int position )` on both version.
