### ISSUE TITLE
Save Scene take much longer, with the progression bar stucked in 100%, using baked lightmaps.

### ISSUE THREAD

**Issue by marmitoTH** [godotengine/godot#24793]
**Godot version:**

3.0.6

**OS/device including version:**

Windows 10, Intel HD Graphics 520

**Issue description:**

So, I have a pretty simple low poly scene, around 180 tris with 5 meshs in .dae format exported from blender using the better collada exporter. The Light Baking parameter in the .dae import tab is set to Gen Lightmaps and the Texel Size is 0.1, default one I think. The BakedLightmap node parameters are default(Cell Size: 0.25, Quality: medium, Mode: ConeTrace, Propagation: 1, Energy: 1, Hdr: On, Extents: covering the hole map). After baking I get 5 lightmap textures, one per object I think, and now when I save the scene, or hit the play button, the progression bar get stuck in 100% for a few long seconds, Godot stop responding in this time. Without the lightmap textures the loading is instantaneous. If I merge the whole scene into 1 object, with 1 lightmap texture and the same parameters, the problem persist. Is it normal?

**EDIT:** Deleting the BakedLightmap node make the save progress faster again, it's related to the node, not the texture. I doubt it's normal behavior, since it stuck after the 100%.

**Comment by marmitaTH** [comment]
I noticed that after baking the lightmaps the .tscn file of my scene goes from 7kb to 161mb, this is probably what causes the delay in save scene progression. This is normal? If so, is it really necessary?

**Comment by bojidar-bg** [comment]
You probably want to save the BakedLightmapData separately.

**Comment by marmitaTH** [comment]
What data? I saved the BakedLightmap node as a scene apart, reducing the size of my main scene, but the save progress still suffers.

**Comment by Calinou** [comment]
Closing in favor of #31644, as the underlying issue is the same.

**Comment by Calinou** [comment]
> i am getting the same issue here stuck after 100% also when opening a scene that has instance of that scene takes forever also i cant test the scene

Did you save lightmap data to an external binary file -or save your scene as `.scn` instead of `.tscn`)?
