### ISSUE TITLE
Sub state machines always report true after first play.

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#24790]
**Godot version:**
5e6c6f3bb745f8d9be4df938f6cf49dfb552b761

**OS/device including version:**
4.20.0-arch1-1-ARCH

**Issue description:**
`is_playing` for sub state machines always report true after first play, even if it's not playing.

**Steps to reproduce:**
- Press space to travel to sub state machine;
![peek 05-01-2019 13-50](https://user-images.githubusercontent.com/1387165/50726203-e31c7800-10f0-11e9-9f69-8b002ce712bf.gif)
- After that, sub state machine always returns `playing` equal `true`.

**Minimal reproduction project:**
[FSM.zip](https://github.com/godotengine/godot/files/2729629/FSM.zip)

**Comment by akien-mga** [comment]
Still reproducible in the current master branch.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3
