### ISSUE TITLE
Change scene to instance

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#24795]
There are 2 "proper" ways of changing scenes right now.
`get_tree().change_scene("path_to_scene")`
and
`get_tree().change_scene_to(load("path_to_scene"))`

However, often you want to change the scene without discarding the current one or do some setup before changing scene. And this is done in really obscure and hacky way (IMO):
```
var menu = preload("res://Menu.tscn").instance()
menu.game = self
get_node("/root").add_child(menu)
get_tree().current_scene = menu 
get_node("/root").remove_child(self)
```
You need to manually add/remove from root and change the current scene. 

Compare it to this:
```
var menu = preload("res://Menu.tscn").instance()
menu.game = self
get_tree().change_scene_to_instance(menu)
```
The method I'm proposing, `change_scene_to_instance`, would change the current scene to already instanced scene, automatically adding it to root and removing the old one. Unlike the current two methods, it shouldn't free the current scene automatically. This sounds inconsistent, so maybe the name could be different.

Another possibility is a `swap_scene()` method, which would do the same, but also return the current scene. This would change above code into:
```
var menu = preload("res://Menu.tscn").instance()
menu.game = get_tree().swap_scene(menu)
```
That's pretty clean and doesn't seem inconsistent.

**Comment by KoBeWi** [comment]
That's impossible, because `change_scene()` expects a PackedScene. I'd still need my `change_scene_to()` method.

**Comment by ACatThatPrograms** [comment]
This was the closest I came while digging for the past while on this issue. It took me quite a few searches to land here as I have been researching passing parameters to a new instanced scene before loading it.

I really think this could be helpful, unless there's a better way than what @KoBeWi has suggested... Also thanks by the way too, you saved my tail. I've been really frustrated while trying to figure this out, but your method of manually doing everything works for me. I found some others explaining this method a little haphazardly, but your snippet is clear and concise.

As far as I could find the docs didn't really cover current_scene and I didn't realize it needed to be set doing it this way.

**Comment by vishtheshnu** [comment]
I had the same issue and came up with a workaround. It might help others who are also dealing with it as well, so I'm going to post it here.

The scene's _ready() function gets called when the scene is changed to it, so from there you can set the internal information you need, perhaps from a global Singleton that is set before get_tree().change_scene("...") is called.

**Comment by KoBeWi** [comment]
Closing, because we are moving proposals out of this repo.
Check the linked PR for further discussion.
