### ISSUE TITLE
Exclude "addons"-folder from search

### ISSUE THREAD

**Issue by TheFlamyy** [godotengine/godot#24794]
**Godot version:** 3.X

The project's search bar is a powerful "tool". You can search for names, extensions etc.
But it gets bloated quickly with scripts and files from your "addons" folder. A project wise option to exclude it from search results would be a good addition.

**Example:**
You want to find all of your scripts. You have downloaded a few addons. You type ".gd" into the search bar and tons of the addons' scripts appear.

**Comment by eon-s** [comment]
This for quick open scenes and scripts too.

**Comment by Jummit** [comment]
I would also like to remove addon files from the project search and the autocompletion of `preload`.

**Comment by TheFlamyy** [comment]
Issue has been moved to godotengine/godot-proposals#25
