### ISSUE TITLE
Parametric modeling

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#24802]
For later versions, like Archimatix Unity plugin a feature to create models using nodes instead of CSG.

https://www.youtube.com/watch?v=x3Wk3Ia0nYU

LOD is easy to create

https://www.youtube.com/watch?v=5mS_6TzJqu4

**Comment by timoschwarzer** [comment]
This is probably not going to land in core because it can be done though an AssetLib plugin.

**Comment by DeadlyLampshade** [comment]
@BastiaanOlij was working on something like this as a plugin, I don't know what the progress of it is now.

[Here it is!](https://www.youtube.com/watch?v=X574IIBgOko)

**Comment by Chaosus** [comment]
Its too high-level feature, its nice to get this as plugin + Im 100% sure that @reduz also say so. I suppose the issue tracker discuss only engine features and not third-party plugins. Should this to be closed @akien-mga ?

**Comment by akien-mga** [comment]
Yes, this should be done via plugins as mentioned above. If a plugin turns out to be so mainstream that 50% of users need it and it could benefit from being integrated in core, we can consider it then of course.
