### ISSUE TITLE
Creating/Editing some resources in Inspector raises UndoRedo false positive "method not found" error

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#24803]
**Godot version:**
Current master (53516d7)

**OS/device including version:**
Any.

**Issue description:**
As reported by @Chaosus in #24680:

> By checking for existing "set_edited" method I removed unnecessary error message emitted every time the user created new ShaderMaterial and assign Shader resource to it
> 
> ![image](https://user-images.githubusercontent.com/3036176/50558887-a02e5f00-0d02-11e9-9f09-f23fbe8b50cf.png)

We discussed this on IRC and the issue is deeper than what #24680 proposes as a fix. `ShaderMaterial` is a `Resource`, which inherits `Object`, so it *does* have the `set_edited` method which is an `Object` method.

This false positive error was likely introduced by #21856, which might also be the cause for #24679 (so a fix to this issue may or may not supersede the already merged #24679).

**Steps to reproduce:**
- Add a node, assign it a new ShaderMaterial resource
- Assign a new Shader resource to the ShaderMaterial, the error is shown in the debugger/console

**Comment by Chaosus** [comment]
Just discovered its not only shows for ShaderMaterial's
For example edit a Sphere mesh will also generates

`core/undo_redo.cpp:287 - Error calling method from signal 'set_edited': 'SphereMesh::set_edited': Method not found.`

**Comment by reduz** [comment]
Closed by 022284135

**Comment by Chaosus** [comment]
@akien-mga should #24679 to be reverted ?

**Comment by akien-mga** [comment]
@Chaosus I don't think so, it was likely the correct fix for its symptom. Here @reduz also fixed the symptom, the original "bug" is that we're now reporting those UndoRedo issue, while before they went unnoticed.
