### ISSUE TITLE
SurfaceTool::add_normal() doesn't normalize, while ImmediateGeometry::set_normal() does

### ISSUE THREAD

**Issue by jvanmourik** [godotengine/godot#24808]
**Godot version:**
3.1 Alpha 5

**Issue description:**
Used both SurfaceTool and ImmediateGeometry to render the same geometry. But forgot to normalize my normals. Resulting renders differ from each other in brightness, because only ImmediateGeometry normalized my given normals.

More information:
https://www.reddit.com/r/godot/comments/ad0eqe/immediategeometry_renders_differently_from_a/

**Comment by Jvanmourik** [comment]
Might be by design but inconsistencies like this one could cause a lot of confusion to unknowing users.

**Comment by bitsawer** [comment]
In my opinion neither should automatically normalize or modify any passed values (if that happens now). In customized shaders people often use normals and texture uv's to pass custom data and modifying it in any way could break things and prevent these kinds of often very useful tricks.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment]
@kleonc You mean it can be closed? If it's fixed in 3.4 then on master too most likely.

**Comment by kleonc** [comment]
@KoBeWi I guess, yes. :laughing: I mean visual bug reported here is fixed.

If the automatic normalization mentioned in https://github.com/godotengine/godot/issues/24808#issuecomment-452078435 does happen then I do dislike it too. But if that's indeed the case then a dedicated issue could be opened for that (or maybe there's already one opened).
