### ISSUE TITLE
DEBUG GDScript Can Not See The Parameter

### ISSUE THREAD

**Issue by xiaolei123** [godotengine/godot#24813]
DEBUG GDScript Can Not See The Parameter functions

**Comment by Naryosha** [comment]
![image](https://user-images.githubusercontent.com/43379543/50751372-10e1f800-127c-11e9-800d-f092c6886716.png)

**Comment by akien-mga** [comment]
Please fill the issue template, and provide more details on your issue. As it stands we have to guess your mind.

**Comment by Chaosus** [comment]
Seems, like an invalid formed issue, and yeah you can see the parameters in debug..
