### ISSUE TITLE
Godot 3.1 in beta, entering release freeze (only major bug fixes accepted)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#24822]
Starting now with bcecf56, we're entering the **beta** stage, and **release freeze** on the *master* branch to get ready for releasing Godot 3.1 stable, hopefully by late January 2019.

This means that we will only consider **major bug fixes** from now on (crash fixes, fixes to very visible bugs that will impact the workflow of most users). Enhancements or non-critical bug fixes will no longer be merged in the master branch until 3.1 is released. Don't worry though, as we will release 3.1.x maintenance releases regularly in following months, where bug fixes and enhancements can be cherry-picked.

Translations strings are also frozen from now on, i.e. no `TTR()` string should be added or modified until the release, so that translators can work towards 100% completion for 3.1.

Exception to the above rules may happen at the discretion of project or feature maintainers.

Contributors are asked to focus on fixing [bugs reported in the 3.1 milestone](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug), as well as enhancing documentation (both class reference here and feature documentation on https://github.com/godotengine/godot-docs). In the coming days, many of the 3.1 issues will be moved to another milestone if they are not considered critical for this release.

We don't have long until the end of January if we want to release 3.1 before GodotCon (and it would be *really* good to do so, as February/March are usually quite busy due to GDC preparations), so let's all focus on fixing the last blockers.

**Comment by slapin** [comment]
Shortest beta cycle ever I guess. Thanks and good luck everyone!

**Comment by Ranoller** [comment]
I would ask for an explanation in the official release notes , in the godot web page, to especify what compiler, system and flags are used to compile the official builds (included alphas and betas). (I´m unable to get a tiniest and fastest build with mscv2015 in windows no mathers the flags used, no mather link in time optimizations, and all "long time" projects eventually will need to compile the engine with the same performance level that official builds)

**Comment by akien-mga** [comment]
@Ranoller Actually @hpvb is working on something even better than documentation; he's going to provide containers (and build script to create containers yourself) that can be used to make builds in the exact same conditions (same compilers, same options) as the official builds.
I'll still add some documentation eventually for those who just want to approximate official builds without using a container, i.e. `tools=yes target=release_debug` for the editor build, etc.

**Comment by akien-mga** [comment]
Call to all core contributors:

Please review all 3.1 issues that you are assigned to, and see if they should be worked on ASAP or moved to a later milestone. We need to reduce the count of issues in the 3.1 milestone down to 0 to be ready to release, so I need your help assessing them.

If you're not sure whether an issue is critical or can wait for a later milestone, you can ask me.

On some issues you assigned yourself, on others you might have been assigned by @reduz or I because we consider that it's an area where you're competent. If we misassigned you, you are of course free to unassign yourself.

Here's how to find the issues assigned to you:
![screenshot_20190123_132351](https://user-images.githubusercontent.com/4701338/51606410-2446c180-1f12-11e9-95c8-37cf792182e4.png)
You can add a milestone filter to see only 3.1 issues:
![screenshot_20190123_132430](https://user-images.githubusercontent.com/4701338/51606440-3de80900-1f12-11e9-8630-35ad0545cbf4.png)
And labels to limit e.g. to `bug` issues in the first time, or look at e.g. all `topic:mono` issues even if you're not assigned to them.
![screenshot_20190123_132459](https://user-images.githubusercontent.com/4701338/51606468-535d3300-1f12-11e9-97aa-336c4ccf0949.png)

Or directly in the search bar: `is:open is:issue assignee:<your nick> milestone:3.1 label:bug`, e.g. https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+assignee%3Aakien-mga+milestone%3A3.1+label%3Abug

Current tally for the 3.1 milestone:
- @akien-mga: [8 bugs](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Aakien-mga)
- @AndreaCatania: [24 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+assignee%3AAndreaCatania)
- @BastiaanOlij: [5 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3ABastiaanOlij)
- @eska014: [6 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Aeska014)
- @Faless: [4 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3AFaless)
- @groud: [7 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Agroud)
- @hpvb: [22 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Ahpvb)
- @JFonS: [3 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3AJFonS)
- @karroffel: [7 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Akarroffel)
- @MarianoGnu: [6 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3AMarianoGnu)
- @neikeq: [33 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Aneikeq) + [26 topic:mono bugs not assigned to you](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+label%3Atopic%3Amono+-assignee%3Aneikeq+)
- @RandomShaper: [3 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3ARandomShaper)
- @vnen: [32 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Avnen) + [9 topic:gdscript bugs not assigned to you](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+-assignee%3Avnen++label%3Atopic%3Agdscript)
- @reduz: [44 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Areduz) + |61 topic:rendering bugs not assigned to you](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+-assignee%3Areduz+label%3Atopic%3Arendering)

And there are [183 bugs](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+no%3Aassignee+-label%3Atopic%3Arendering+-label%3Atopic%3Amono+-label%3Atopic%3Agdscript) with no assignee yet, and not one of gdscript, rendering or mono.

The aim should be to reduce all this drastically over the new few days, as we aim for a release before the end of January (I doubt we'll manage, but it would be *really* nice so we can at least try to).

So please push back anything non critical, and also check if those issues are not fixed already, as many of them are relatively old. I've gone through ~200 issues of backlog myself the last few days, starting from the oldest ones. I'm continuing to make my way up chronologically.

**Comment by akien-mga** [comment]
Note: I'm still going through the list myself and kicking stuff to 3.2, so when you click the above links you might have less issues assigned to you than I wrote (or more, if I assigned you more issues in the meantime :)).

Feel free to have a look to your issues in the 3.2 milestone to see if there's any must fix that you want to work on now.

**Comment by akien-mga** [comment]
So, it's time to wrap up the beta and move to the release candidate stage.

I need all core devs to review the current list of opened issues in the 3.1 milestone for "their area", and to decide if they want to keep them in the 3.1 milestone or move to 3.2.

Congrats to everyone BTW, the numbers have decreased a lot since my previous post :)

* @akien-mga: [4 bugs](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Aakien-mga)
* @AndreaCatania: [14 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+assignee%3AAndreaCatania)
* @BastiaanOlij: [5 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3ABastiaanOlij)
* @eska014: [2 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Aeska014)
* @Faless: [1 bug](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3AFaless)
* @groud: [1 bug](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Agroud)
* @hpvb: [12 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Ahpvb)
* @JFonS: [3 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3AJFonS)
* @karroffel: [5 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Akarroffel)
* @MarianoGnu: [9 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3AMarianoGnu)
* @neikeq: [32 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Aneikeq) + [18 topic:mono bugs not assigned to you](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+label%3Atopic%3Amono+-assignee%3Aneikeq+)
* @RandomShaper: [1 bug](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3ARandomShaper)
* @vnen: [18 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Avnen) + [0 topic:gdscript bugs not assigned to you](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+-assignee%3Avnen++label%3Atopic%3Agdscript)
* @reduz: [28 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+assignee%3Areduz) + [24 topic:rendering bugs not assigned to you](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.1+label%3Abug+-assignee%3Areduz+label%3Atopic%3Arendering)

**Comment by akien-mga** [comment]
Closing to reduce the count of pending 3.1 issues :)

**Comment by RandomShaper** [comment]
By the way, I'm working on mine. Expecting to have it ready along this week.
