### ISSUE TITLE
Editor crashes when manipulating keyframes in AnimationPlayer.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#24829]
**Godot version:**
e4b0251

**OS/device including version:**
Win10 64bit

**Issue description:**

We're in a situation where our project will randomly crash when moving keyframes around in the AnimationPlayer.  It isn't clear exactly on the cause, and I haven't been able to isolate it, and it is tricky to reproduce.  Sometimes spam clicking the keyframe does it, sometimes a less than precise drag will hang and crash.

The best I could do is get a stack trace from running in debug using VS2017.

![vlcsnap-error062](https://user-images.githubusercontent.com/13004169/50797940-2e947900-12df-11e9-83a5-10dea635fe74.jpg)

It could be possible that there might be an offending line somewhere in my tool script, but there aren't any script errors being reported.

If anyone knows what this stack trace might indicate, or have any pointers on how to debug it with VS2017, it would be much appreciated.  I'll keep dissecting the project in the meanwhile.

Most the time it crashes with nothing in the console, but on a few occasions there have been a few odd errors that have lead into these crashes.

![cmd_2019-01-07_23-55-09](https://user-images.githubusercontent.com/13004169/50798115-d0b46100-12df-11e9-8415-ba979ad25374.png)
![cmd_2019-01-08_00-15-11](https://user-images.githubusercontent.com/13004169/50798117-d1e58e00-12df-11e9-83bd-00a906b6b83a.png)

**Steps to reproduce:**
Currently unknown.  Working on it.

**Comment by QbieShay** [comment]
What type of keyframe? I reported an issue with the color picker..

**Comment by avencherus** [comment]
These were just position keyframes for the most part.  

I'm investigating an area related to the add/remove node signals in get_tree().  I have suspicions it might be something happening there, since these do spam the editor and its mostly GUI stuff.  They tend to have a lot of yields and timing stuff, so I'm wondering if something is slipping through there.

I'll hopefully know more once I rewrite most my tool scripts, or at least rule it out as the cause.

**Comment by avencherus** [comment]
With my limited knowledge in debugging the engine itself, I think I've narrowed it down to the use of the SceneTree signals dealing with `node_added` and `node_removed`.  I can't really peer much deeper than that, but my suspicion is that has to do with signal yields returning to editor GUI nodes.

Since the editor itself is in the scene tree large amounts of GUI nodes are entering and exiting the tree as contextual options, firing off this signal quite excessively.  (I reported the inconvenience of this in the past:  https://github.com/godotengine/godot/issues/22042)  If anything may be done in handling those nodes, it may be that whatever yields they might be relying on can't safely resume.

I don't think I could possibly investigate it any further.  In the meanwhile, I stripped the reliance on these signals out of all my tool code, and rewrote a less ideal method of detecting specific node changes in the tree.

So far so good, but it is a bit random to reproduce, maybe I got lucky in my testing so far.  We'll see how it goes this week, and if it is resolved, it must be in that neighborhood.  If it is, then I would probably close this and defer to my older issue, since it would probably need some considerable reworking of  what is provided to tool script.

**Comment by avencherus** [comment]
Have seen a silent crash last night when my partner wanted to show me something.  She was doing some animation moments before, and then tried to open a scene from the file dock and the editor crashed.   The editor is a debug build but nothing appeared in the CLI.

The crashes might happen once every day or two, and no idea how to reproduce it.  I still wonder if maybe the crashes I experienced are now avoided, but now what I'm seeing is one of the other open issues regarding sudden crashes.

I'll keep watching and combing for what I can.

**Comment by akien-mga** [comment]
> Have seen a silent crash last night when my partner wanted to show me something. She was doing some animation moments before, and then tried to open a scene from the file dock and the editor crashed. The editor is a debug build but nothing appeared in the CLI.

That one sounds like #23572.

**Comment by avencherus** [comment]
Thanks.  I hope so, I'll watch for resolution on that issue, and see later if I can reproduce it.

**Comment by avencherus** [comment]
Have some situation now where one scene that I save will crash the editor.  In VS2017 I got this stack.

![image](https://user-images.githubusercontent.com/13004169/51295727-9e161100-1a21-11e9-8588-87c8d309ccc8.png)

**Comment by avencherus** [comment]
Thanks.  I don't think it is related to the AnimationPlayer at this point, but I do now have a scene that can reliably reproduce the crash, so I will start chopping away tonight to see if I can isolate the point it happens, and hopefully it has some way to reproduce it.

Will test things on the latest build first, to see if anything resolves there.

**Comment by avencherus** [comment]
@reduz So, neither AnimationPlayer is to blame, nor is the latest build changing the result.  I managed to roughly locate the line of GDScript that instigates it, and it is `yield(get_tree().create_timer(2.0), "timeout")`

But it does not work alone, there seems to be a few other lines of code that can be added or removed that will affect it.

It has been highly resistant to being reproduced.  Even when I copy the project, when running the copy the crashing stops... ???

So let me try my best to explain the cobweb I've been rolling around in for the last few hours.

1. When I open this scene with a tool script yield in `_ready()` and save immediately, the editor will crash.  Remove this yield line, all works fine.
![sublime_text_2019-01-18_00-52-40](https://user-images.githubusercontent.com/13004169/51354909-e2ef8580-1abd-11e9-834a-f87f698bd8e5.png)

2. I had written a tool to inspect editor variables in the dock.  There is an `unwatch()` method in a singleton called Editor (editor_core.tscn / editor_core.gd).  Leave the yield line in and comment this method out, crashing stops.
![sublime_text_2019-01-18_00-51-19](https://user-images.githubusercontent.com/13004169/51354905-e256ef00-1abd-11e9-982b-d069ca340c84.png)

3. The editor_watch.gd script is something that is loaded by a plugin into the dock.  So I went to check it out, comment this method out.  Crashing stops.  I tried making it just `return`, but still crashes.  It gets really weird next.
![sublime_text_2019-01-18_00-51-35](https://user-images.githubusercontent.com/13004169/51354906-e256ef00-1abd-11e9-8815-12cdfea53146.png)

4. From earlier tests I had the inspector commented out...  It's not even being loaded, but doesn't seem to matter.  Bring it back, or leave it out, still crashes.
![sublime_text_2019-01-18_00-51-57](https://user-images.githubusercontent.com/13004169/51354907-e256ef00-1abd-11e9-9e47-7b035ccfbcb3.png)

Been a rather big source of woes trying to create custom tools for our projects, but I would say that maybe the work-around to this is to avoid yields() in tool code entirely.  Maybe in general too, I've have lots of hard to debug issues with them in the past when they go wrong.

Was hoping to be able to reproduce it, but since copies don't work, I can't even chop the existing project down to a minimal example.
 
So here at least is a GIF of this elusive creature in the wild.  I open testing.tscn, save immediately, crash results:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/51355480-fb609f80-1abf-11e9-8d29-cf3e0af0ae49.gif)

I'll preserve this branch of the project for the time being, and hope that the unique cosmic alignment it requires stays intact over time.

**Comment by avencherus** [comment]
@reduz Might it be the case that if it were fixed by a recent update, that some out of backend data files that editor would use (appdata) need to be flushed out?

**Comment by avencherus** [comment]
@vnen Thanks, I'll split the issue to clean it up shortly.  I also will say that yesterday we had an infinite loop of message errors when selecting and moving a large number of keyframes at once.  I'll be making a post about that too, maybe its related and there is some sort of leak or issue with what it may be connected to behind the scenes.  Wish these weren't so hard to reproduce.

**Comment by reduz** [comment]
Sorry, can' t do anything without a repro case or a tool script that does something similar. I guess same goes for @vnen. It does seem that, most likely, your tool script does something strange but that' s as much as I can see here.

**Comment by reduz** [comment]
I tried clicking keyframes to no end in multiple animations and still can't reproduce it

**Comment by reduz** [comment]
Valgrind saves the day again

**Comment by avencherus** [comment]
Nicely done.
