### ISSUE TITLE
Cannot select MeshInstance2D by clicking on it

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#24821]
**Godot version:**
3.1-alpha5

**OS/device including version:**
Any

**Steps to reproduce:**
1. Create a Sprite
2. Assign a texture
3. Sprite → Convert to 2D Mesh
4. Try to click on the newly created MeshInstance2D

**Comment by KoBeWi** [comment]
Still valid in 3.2.2
You need to click the gizmo.
