### ISSUE TITLE
Mono

### ISSUE THREAD

**Issue by PROuserR** [godotengine/godot#24825]
**Godot version:**
V3.0.6

**OS/device including version:**
OS->Windows 10
Video card->RADEON R5 M420 2GB
Mono version-> 5.16.0.179

**Issue description:**
When I was following the tutorial in the godot docs in getting started (scripting)
http://docs.godotengine.org/en/3.0/getting_started/step_by_step/scripting.html
and making a script file c# and  run the project GoDot crashes and exit with no error message or something?

**Comment by akien-mga** [comment]
You should use Mono 5.12 with Godot 3.0.6:
![screenshot_20190107_200037](https://user-images.githubusercontent.com/4701338/50787511-e9f4e780-12b6-11e9-8213-92b10e06c484.png)
