### ISSUE TITLE
Certificate file cannot be read with windows (CRLF) linebreaks

### ISSUE THREAD

**Issue by r-lodahl** [godotengine/godot#24832]
**Godot version:**
3.1 alpha 5 and 3.0.6 stable

**OS/device including version:**
Windows 10 Pro 64 Bit, Windows 10 Enterprise 64 Bit, Linux Mint 19.1 64 Bit

**Issue description:**
If the certificate file contains any CRLF linebreaks, reading the certificate file will fail giving Request Error 31. (There may be more restrictions including comments or empty lines being not allowed?). 3.0.6 this issue also printed on the console values like "readed certs: 0" or "readed certs: -11056". Using the linux ca-certificates.crt file and enforcing LF linebreaks has fixed the issue.

**Steps to reproduce:**
- Create an empty scene with some node, attach a script to it. In its ready function try to establish a ssl connection per httpclient (github api was used from me)
- In the project settings -> ssl, reference a ca-certificates.crt file using CRLF line breaks
- Run the project

**Possible solutions:**
1) Allow all types of line breaks to occur in the crt file
2) Explicitly name the need for LF linebreaks in the SSL godot tutorial.

**Comment by Calinou** [comment]
Note that SSL certificates are bundled in the editor and export templates as of 3.1 alpha, so you don't need to manually set a bundle file anymore (unless you need to add your own certificates).

**Comment by Faless** [comment]
I'm unable to reproduce with current master and a `unix2dos`-ed crt file with multiple certs, empty line-breaks, and comments.

@r-lodahl  Can you upload the offending crt file ?

**Comment by Faless** [comment]
Seems to work fine, can't reproduce in my tests, and can't investigate further without an example certificate to test against.

Closing as stale.
