### ISSUE TITLE
GLES 2 Android texture not found

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#24839]
**Godot version:** alpha 5

**OS/device including version:** Android Pie adreno 625

**Issue description:**
My app not working properly for GLES 2 rendering. it looks like Godot try to find "res://.import/bullet.png-aab1ba7821435eff2d87c5223ef99aea.etc2.stex" but not found any, but after i check "./import" folder the file do exist. i already change vram compression in setting and enable Etc but still not working.

here is some LOGCAT to help

01-08 20:40:19.648 13141 13167 I godot   : Android modules: Nothing to load, aborting
01-08 20:40:19.712 13141 13167 I godot   : OpenGL ES 2.0 Renderer: Adreno (TM) 506
01-08 20:40:20.016  1833  2014 I ActivityManager: Displayed org.godotengine.newgameproject/org.godotengine.godot.Godot: +885ms (total +6s769ms)
01-08 20:40:20.039  1833  2061 I WindowManager: Screen frozen for +766ms due to Window{ecc387f u0 Splash Screen org.godotengine.newgameproject}
01-08 20:40:20.093 13141 13167 E godot   : **ERROR**: Condition ' !f ' is true. returned: ERR_CANT_OPEN
01-08 20:40:20.093 13141 13167 E godot   :    At: scene/resources/texture.cpp:482:_load_data() - Condition ' !f ' is true. returned: ERR_CANT_OPEN
01-08 20:40:20.093 13141 13167 E godot   : **ERROR**: Failed loading resource: res://.import/bullet.png-aab1ba7821435eff2d87c5223ef99aea.etc2.stex
01-08 20:40:20.093 13141 13167 E godot   :    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
01-08 20:40:20.093 13141 13167 E godot   : **ERROR**: Failed loading resource: res://component/bullet/bullet.png
01-08 20:40:20.093 13141 13167 E godot   :    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: Can't load dependency: res://component/bullet/bullet.png
01-08 20:40:20.094 13141 13167 E godot   :    At: core/io/resource_format_binary.cpp:659:poll() - Method/Function Failed, returning: error
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
01-08 20:40:20.094 13141 13167 E godot   :    At: core/io/resource_loader.cpp:202:load() - Condition ' err != OK ' is true. returned: RES()
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: Failed loading resource: res://component/bullet/palette.material
01-08 20:40:20.094 13141 13167 E godot   :    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: Can't load dependency: res://component/bullet/palette.material
01-08 20:40:20.094 13141 13167 E godot   :    At: core/io/resource_format_binary.cpp:659:poll() - Method/Function Failed, returning: error
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
01-08 20:40:20.094 13141 13167 E godot   :    At: core/io/resource_loader.cpp:202:load() - Condition ' err != OK ' is true. returned: RES()
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: Failed loading resource: res://.import/bullet.obj-96d65c2889132aae4fb81f698d6cb06c.scn
01-08 20:40:20.094 13141 13167 E godot   :    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: Failed loading resource: res://component/bullet/bullet.obj
01-08 20:40:20.094 13141 13167 E godot   :    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: res://component/bullet/bullet_extends.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://component/bullet/bullet.obj
01-08 20:40:20.094 13141 13167 E godot   :    At: scene/resources/scene_format_text.cpp:439:poll() - res://component/bullet/bullet_extends.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://component/bullet/bullet.obj
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
01-08 20:40:20.094 13141 13167 E godot   :    At: core/io/resource_loader.cpp:202:load() - Condition ' err != OK ' is true. returned: RES()
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: Failed loading resource: res://component/bullet/bullet_extends.tscn
01-08 20:40:20.094 13141 13167 E godot   :    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: res://component/bullet/scene/bullet.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://component/bullet/bullet_extends.tscn
01-08 20:40:20.094 13141 13167 E godot   :    At: scene/resources/scene_format_text.cpp:439:poll() - res://component/bullet/scene/bullet.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://component/bullet/bullet_extends.tscn
01-08 20:40:20.094 13141 13167 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
01-08 20:40:20.094 13141 13167 E godot   :    At: core/io/resource_loader.cpp:202:load() - Condition ' err != OK ' is true. returned: RES()
01-08 20:40:20.095 13141 13167 E godot   : **ERROR**: Failed loading resource: res://component/bullet/scene/bullet.tscn
01-08 20:40:20.095 13141 13167 E godot   :    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
01-08 20:40:20.095 13141 13167 E godot   : **ERROR**: res://component/city/city.tscn:12 - Parse Error: [ext_resource] referenced nonexistent resource at: res://component/bullet/scene/bullet.tscn
01-08 20:40:20.095 13141 13167 E godot   :    At: scene/resources/scene_format_text.cpp:439:poll() - res://component/city/city.tscn:12 - Parse Error: [ext_resource] referenced nonexistent resource at: res://component/bullet/scene/bullet.tscn
01-08 20:40:20.095 13141 13167 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
01-08 20:40:20.095 13141 13167 E godot   :    At: core/io/resource_loader.cpp:202:load() - Condition ' err != OK ' is true. returned: RES()
01-08 20:40:20.096 13141 13167 E godot   : **ERROR**: Failed loading resource: res://component/city/city.tscn
01-08 20:40:20.096 13141 13167 E godot   :    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()

**Comment by volzhs** [comment]
according to `res://.import/bullet.png-aab1ba7821435eff2d87c5223ef99aea.etc2.stex`,
you are using etc2 format with gles2 which is not available format for gles2.
you need to set it at project settings > rendering > vram compression

I think it's duplicated of #23650

**Comment by akien-mga** [comment]
Indeed, same issue as what #23650 covers.

You should use the `ETC` format instead, and reimport all textures (you can delete `res://.import` to force a reimport with the updated options).
