### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by firefly2442** [godotengine/godot#2483]
Found these with cppcheck, not sure how you want to handle it.  There are cases where a return is used but there's still code after it that will never be reached.

* https://github.com/okamstudio/godot/blob/master/core/math/math_2d.cpp#L190
* https://github.com/okamstudio/godot/blob/master/tools/editor/console.cpp#L72
* https://github.com/okamstudio/godot/blob/master/tools/editor/plugins/item_list_editor_plugin.cpp#L213
* https://github.com/okamstudio/godot/blob/master/bin/tests/test_math.cpp#L120
* https://github.com/okamstudio/godot/blob/master/bin/tests/test_math.cpp#L151

**Comment by bojidar-bg** [comment]
Hm.. except in test_math, all the example lines seem to be unneeded returns... (e.g. return is preventing the function from working properly..)

**Comment by firefly2442** [comment]
Maybe they were put in for testing but someone forgot to remove them?

**Comment by akien-mga** [comment]
> https://github.com/okamstudio/godot/blob/master/tools/editor/plugins/item_list_editor_plugin.cpp#L213

This one has been added in 0378e110. Looks like it's @reduz's way of commenting out dead code :D It's not a very good practice though IMO, and there should at least be an explanatory comment + the offending code commented out (or removed completely if it's no longer relevant).
