### ISSUE TITLE
Navigation2D get_simple_path() crash on mobile with optimize=true

### ISSUE THREAD

**Issue by narunsa** [godotengine/godot#24835]
**Godot version:**
v3.0.6.stable.official.8314054

**OS/device including version:**
IOS 11, 12

**Issue description:**
My game is crash on ios but it fine when running on Godot simulator. It crash when  optimize parameter is true in getsimplepath(start, end, optimize) function

**Comment by akien-mga** [comment]
Might be related to #23917.

**Comment by akien-mga** [comment]
@leandrodreamer confirmed on #23917 that they have the same kind of crash on Android with `get_simple_path()` and `optimize=true`:

> same problem here with the 3.0.6 on a xiaomi redmi note 4 snapdragon, looks like only happen with the optimize path on true (the third parameter)

@Luraktinus's original report in #23917 also uses `optimize=true`: https://github.com/Luraktinus/EN_/blob/494a13ee3f784bf5f98c6ac722dfc665829b6836/Enemies/Enemy.gd

It was experienced on a Huawei P9 lite with Android 6 using Godot 3.1 alpha 2.

**Comment by akien-mga** [comment]
Here's the `optimize` code branch, if someone is willing to debug further:
https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/scene/2d/navigation2d.cpp#L490-L582

**Comment by leandrodreamer** [comment]
i test it on my xiaomi redmi note 4 and xiaomi redmi 5 plus, both share the same cpu and gpu, the huawei p9 lite have a diferent cpu and gpu but all of them have in common the "Cortex-A53" microarchitectures, i think that can be userfull know what model was the ios one to know exactly what is the common factor

**Comment by akien-mga** [comment]
@narunsa @leandrodreamer Could one you provide a minimal project that reproduces the issue on your hardware? So that we know that we're debugging something that is known to crash, even if we can't reproduce it on different hardware.

**Comment by reduz** [comment]
Without simple testcase, there is nothing I can do

**Comment by Luraktinus** [comment]
what about that
https://github.com/godotengine/godot/issues/23917

**Comment by akien-mga** [comment]
> what about that
#23917

I've tried again on my Samsung Galaxy S3, but couldn't get it to crash even when playing more than 5 minutes (I'm a pro at making the red dot bounce everywhere now).

**Comment by reduz** [comment]
Same here that works fine and nothing odd on valgrind while running it either

**Comment by hpvb** [comment]
I don't see anything odd with ubsan/asan either. I have no idea why this would crash on mobile.

**Comment by leandrodreamer** [comment]
i was trying to test it on my phone but it did not open, show the load screen, blink a little bit and close (using beta9, my game export and works perfect on my phone with relatively similar config)

**Comment by leandrodreamer** [comment]
[test_path.zip](https://github.com/godotengine/godot/files/2922459/test_path.zip)
ok, i make this extra minimal project and it work on my phone with the simplify on true, there is the project and an apk (with beta9), @Luraktinus can u test it on your phone?, if the character move that means it work (it don't get the target due to a lazy movement script, but it try and evade obstacles correctly)

**Comment by RandomShaper** [comment]
I've tested it too. Xiaomi MI6, Android 8. Doesn't crash. Character moves.

**Comment by capnm** [comment]
Works without issues on https://www.qualcomm.com/products/snapdragon/processors/600 :-)

**Comment by akien-mga** [comment]
`test_path.zip` works fine on my Samsung Galaxy S3 with c0e1c66e3.

> i make this extra minimal project and it work on my phone with the simplify on true

By "it work" you mean that it triggers the bug, or it doesn't?

>  edit: take in count that this problem was happening before with 3.0.6 on the same phone, looks like is fixed

So it's fixed in the master branch?

**Comment by leandrodreamer** [comment]
@akien-mga it doesn't, it work normally without freeze, before it freeze the entire game just when get_simple_path is called, so looks like (at least on android) is fixed in the master :D, gonna be good if @narunsa can confirm that if is fixed on ios
(sorry for bad englihs :b)

**Comment by narunsa** [comment]
Sorry for late response, I'll test it on my phone(IOS) with godot version 3.0.6

**Comment by narunsa** [comment]
Godot Version: v3.0.6.stable.official.8314054

@leandrodreamer I can't open "test_path" project, so i use [navigation2d demo project](https://godotengine.org/asset-library/asset/117) to test 

It work fine on simulator but it crash on iphone(7plus) and ipad(9.7inch 5thGen 2017model)

[Here is project file and recorded screen](https://drive.google.com/drive/u/0/folders/14sjJxo5rtPBM7uUKFOWjxQ0sVa3hJT3x)

**Comment by narunsa** [comment]
@leandrodreamer I create a new project with godot v3.1 beta9, it work fine on my ios device (iphone 7+ and ipad)

**Comment by akien-mga** [comment]
Thanks for the tests. So it seems like it's fixed in master, but still affects 3.0.x, so moving to 3.0 milestone.

**Comment by akien-mga** [comment]
We're about to release 3.2, so the 3.0 branch will not get advanced support (and already no longer does). Since this appears to be fixed in the 3.1 branch, I'll close this. If anyone really wants the fix in the 3.0 branch and can identify what commit(s) solve the issue, we can consider a backport for a potential maintenance 3.0.7 release.
