### ISSUE TITLE
Can't draw ImageTexture based on generated Image

### ISSUE THREAD

**Issue by Redwan13** [godotengine/godot#24834]
**Godot version:**
3.1 beta1

**OS/device including version:**
Mac OS X 10.14.2

**Issue description:**
Trying to populate image in code and then draw it on screen using ImageTexture. On call of `draw_texture` error 

```
E 0:00:00:0635   Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
  <C Source>     ./core/rid.h:164 @ getornull()
```
and instead of correct texture white rect is drawn.

**Minimal reproduction project:**

```
extends Node2D

var width = 160;
var height = 120;

func _ready():
    update()

func _draw():
    var image = Image.new()
    image.create(width,height, false, Image.FORMAT_RGB8)
    print(image.get_size())

    image.fill(Color.black);

    var texture = ImageTexture.new()
    texture.create_from_image(image)
    draw_texture(texture, Vector2(0,0))
    draw_rect(Rect2(0,0, width/2,height/2), Color.red)
```
everything drawn by `draw_rect` displays correctly.

PS tried remake example using `ImageTexture.create(...)` but `get_data` return null instead of correct Image.

**Comment by Xrayez** [comment]
The `ImageTexture` gets freed when no longer used in code (out of scope) once you draw it , try declaring it in global scope within the script:
```gdscript
var texture

func _draw():
    # ... creating image ...
    texture = ImageTexture.new()
    # ... drawing ...
```

I stumbled upon this too many times myself though!

**Comment by Redwan13** [comment]
Thanks, it works!
