### ISSUE TITLE
Cannot open project via Project Manager

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot#24847]
**Godot version:**
3.1 beta1 classical win64, 3.1 beta1 mono win64

**OS/device including version:**
Windows 10/Acer Aspire E15

**Issue description:**
I tried to open existing project created in Godot 3.0.6
The project was not opened, the following information was displayed in console
Editing project: C:/work/godot/projects/ink-godot-example (C:::work::godot::projects::ink-godot-example)
ERROR: execute: Condition ' ret == 0 ' is true. returned: ERR_CANT_FORK
   At: platform/windows/os_windows.cpp:2449
ERROR: _open_selected_projects: Condition ' err ' is true.
   At: editor/project_manager.cpp:1440
Then I tried to create new project in Godot 3.1. The project folder was created successfully, but when I tried to open it, the same error message appears in console.
Then I closed the project manager and tried to reopen it... this time the engine crashes on start with the message:
Error starting the application (0xc0000142)
I have deleted the created test project folder, but the error persists...

**Comment by Zireael07** [comment]
Are you using any addons? Ink-Godot-example is a suspicious name because it makes me think of Ink the text solution...

**Comment by Antokolos** [comment]
The same error is displayed when using classical (non-Mono) version of the 3.1 Beta for the same empty default project

**Comment by eon-s** [comment]
do you have any antivirus or something that may be preventing the project manager from launching the editor?

**Comment by Antokolos** [comment]
Yes, it seems that it was the case.
Godot somehow was added to the list of blocked applications for Comodo. After unblocking all is fine for now.
Strangely enough, Comodo did not said anything, it just silently blocked the launch of the editor.
Thank you for help, I'll close this issue.
