### ISSUE TITLE
Crashing when drag and drop files in the FileSystem 

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#24844]
**Godot version:** v3.1.beta1.official

**OS/device including version:** Solus OS Linux x64

**Issue description:**

When dragging files to a folder in the FileSystem Godot crashes. It doesn't seem very reproducible, but I've experienced this 3 times already. 

**Steps to reproduce:**
1. Create 2 or more files in the FileSystem
2. Create a new folder
3. Select multiple files
4. Drag them to the new folder

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
CC @groud

**Comment by henriiquecampos** [comment]
> @henriiquecampos Godot usually print a stacktrace when you launch it via command line, could you have it ?

As I said it is not very consistent to reproduce. I tried to recreate the setup when the crash happened, but I wasn't able to reproduce the crash.

I often execute the AppImage, no terminal, so I don't think I have a log of it :/

**Comment by groud** [comment]
This is likely fixed now, with #25076. Closing the issues.
Please comment if this happens again. :)
