### ISSUE TITLE
Export PackedScene "reset to default" throws error

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#24843]
**Godot version:** v3.1.beta1.official 

**OS/device including version:** Solus Gnome Linux 64

**Issue description:**

When trying to reset a value to default using the inspector the editor throws the following error:

`core/object.cpp:1241 - Error calling method from signal 'property_changed': 'EditorInspector::_property_changed': Method expected 2 arguments, but called with 1.`

And it doesn't reset the value to default. So we have to manually go to the drop down menu and press "clear"

**Steps to reproduce:**
1. Create a scene
2. Attach a GDScript to the root node
3. In the script declare an exported PackedScene variable `export (PackedScene) var test`
4. Create another scene and save it to a .tscn file
5. Set the `test` packed scene to be this previous scene
6. Try to reset the value to the default

![image](https://user-images.githubusercontent.com/10171059/50835344-9d082400-133d-11e9-9941-81cb9b43f13d.png)

**Minimal reproduction project:**

**Comment by timoschwarzer** [comment]
Working on it...
