### ISSUE TITLE
Export PackedScene not showing in Inherited classes' inspector

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#24845]
**Godot version:** v3.1.beta1.official

**OS/device including version:** Solus OS Linux x64

**Issue description:**

Creating an inherited class sometimes not display the exported PackedScene variable in the editor's inspector.

![bug_inheritance](https://user-images.githubusercontent.com/10171059/50843241-7652e900-134f-11e9-9599-7230eb99087f.gif)

**Steps to reproduce:**
1. Create a script
2. Export a PackedScene variable
3. Use the `class_name` keyword and name it
4. Create another script
5. In the `extends` line extend the previous script using the name you set in `class_name`
6. Look at the inspector

**Comment by jlahman** [comment]
This seems to be an issue with Editor_Inspector not updating the properties on script load or clear( it also won't get rid of the exported var if you clear the script). However If I save the scene the property shows up, but it wont get rid of the property if no script is attached and the scene is saved.

This last bit makes me wonder if it's intended to work this way. If one accidentally unloads a script from a node, the properties one assigned to it won't disappear until the scene is saved or you reload the scene by de-selecting and re-selecting the node. Then again undo and redo works for this so probably not intended.

I'll look into this and try to find a fix.

**Comment by akien-mga** [comment]
Seems related to #21136.
