### ISSUE TITLE
KinematicBody2D stop_on_slope is broken only in release builds

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#24841]
**Godot version:**
3.1 master

**OS/device including version:**
At least Linux/X11

**Issue description:**
Okay, this one is a bit strange. The `stop_on_slope` parameter in `move_and_slide` does only work in debug builds. I don't know if it's a precision error or whatever. (Maybe `-ffast-math`?)

**Demonstration**
https://youtu.be/qk1NBRa5DtI

As you can see, I output the X and Y coordinates of `lv_n + p_floor_direction`.
(Here: https://github.com/godotengine/godot/blob/master/scene/2d/physics_body_2d.cpp#L1293)
This for some reason gives (0, 0) on debug builds and something else on release_debug builds.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2736843/Test.zip)

**Comment by timoschwarzer** [comment]
Note: It does not work in 3.1-beta1, too. But if you compile https://github.com/godotengine/godot/commit/bcecf5626768c8399e9293fe12a25511eeb6c52d manually in debug mode, it works.

**Comment by hpvb** [comment]
Another -ffast-math victim probably?

**Comment by hpvb** [comment]
I'm running some benchmarks, PR with background info will follow shortly
