### ISSUE TITLE
Wrong position and size setters for Control nodes

### ISSUE THREAD

**Issue by Oleksandrigo** [godotengine/godot#24859]
**Godot version:**

3.1 alpha 5

**OS/device including version:**

Win 10

**Issue description:**

The item is not displayed correctly (see below)

**Steps to reproduce:**
1) Create root scene. (and make it main scene)
2) Create child Control
3) Make this child a external branch
4) Get into it.
5) Create a panel and repaint it
6) Create another control as the child of our control.
7) Add to new control panel
8) Create script and add his to Control Scene
9) Write in
```
extends Control

func _ready():
	$Control.rect_size = Vector2(
		1024,
		600
	)
	$Control.rect_global_position.x = -1024
```

(In the project settings the resolution is 1024*600)
8) Run Control Scene and see
9) And Run Main (root) Scene and see

You can see that when you start different scenes, the color changes. This is the Panel, whose size in the script has been changed to some ugly and increased by a couple of times.

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/2739968/Test.zip)

**Comment by Oleksandrigo** [comment]
It was like adding 1024 to the size

**Comment by Oleksandrigo** [comment]
in 6 beta, this bug still works.
the stable version 3.0.6 of the bug doesn't have

**Comment by groud** [comment]
Ah, this is quite a complex reproduction project for a quite simple bug.
What is happening is that setting the position and size of a control node that uses anchors set as full-rect does not make a lot of sense. The position and size parameters are computed from the anchors positions, which are split in that case.

What I'll probably implement is that the rect position and size are computed from the top left anchor, that would probably make more sense.

**Comment by groud** [comment]
Ok found what the problem is. 
Calling set_size in the _ready function is not safe, as it relies on the parent's rect, which is not initialized when this function is called. I'm not sure what can be done to solve this. :/

**Comment by groud** [comment]
So basically there is no solution. Setting the size should not be allowed in the ready function, as at the point the parent is not ready for it.

We decided on IRC to add a warning / error about that.

**Comment by KoBeWi** [comment]
This looks easy to solve, but what would be the best way to handle the warning? Introduce a new boolean variable and connect `ready` signal to method that sets it to true?
