### ISSUE TITLE
Game crashes when "pointing/emulate_touch_from_mouse=true" and you double click the main window's title bar to maximize it

### ISSUE THREAD

**Issue by AlexRixhardson** [godotengine/godot#24852]
**Godot version:**
3.1 Beta 1

**OS/device including version:**
OS: Windows 10, 64-bit (10.0.17134.472)
GPU: NVIDIA NVS 4200M
NVIDIA Driver version: 377.48

**Issue description:**
Game crashes when "pointing/emulate_touch_from_mouse=true" and you double click the main window's title bar to maximize it.

This is the console output after the crash:
```
OpenGL ES 3.0 Renderer: NVS 4200M/PCIe/SSE2
ERROR: get_tree: Condition ' !data.tree ' is true. returned: __null
   At: scene/main/node.h:263
ERROR: _get_socket_error: Socket error: 10054
   At: drivers/unix/net_socket_posix.cpp:190
```

Weirdly enough, if you click the "maximize" button in the right top corner of the window (next to the "close" button), then the game will not crash.

**Steps to reproduce:**
1. create a new project
2. set project's property "pointing/emulate_touch_from_mouse=true"
3. run the game, then double click the main window's title bar to resize it

**Minimal reproduction project:**
[maximizecrashtest.zip](https://github.com/godotengine/godot/files/2738618/maximizecrashtest.zip)

**Screen capture of the crash:**
![screencapture](https://user-images.githubusercontent.com/39428930/50862500-10d91980-139c-11e9-950e-1bcd7b2422db.gif)

**Comment by qarmin** [comment]
Can't reproduce this on Windows 10 Intel HD 4600

Have you up to date drivers?
I see, that on nvidia page are newer drivers(but I'm not sure that this are correct) 392.00 - https://www.nvidia.com/Download/driverResults.aspx/137614/en-us

**Comment by AlexRixhardson** [comment]
I did upgrade the drivers, unfortunately it did not help.

I also tried on Intel(R) HD Graphics 3000 graphics card (same computer) and experienced the same error, so I doubt this is related to graphics card or driver. I did however notice that the crash on Intel didn't happen when I tried to reproduce the problem on the first try. I had to maximize the window three times before the crash happened.

This is the console's output of the crash on Intel HD 3000:
```
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics 3000
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:3178
ERROR: get_tree: Condition ' !data.tree ' is true. returned: __null
   At: scene/main/node.h:263
ERROR: _get_socket_error: Socket error: 10054
   At: drivers/unix/net_socket_posix.cpp:190
```

**Comment by AlexRixhardson** [comment]
Unable to reproduce in Beta 7, therefore I am closing this issue.
