### ISSUE TITLE
PoolByteArray decompress() method empty array if second argument is omitted

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#24861]
**Godot version:**

0e25c32

**OS/device including version:**
Win10 64-bit

**Issue description:**

Was trying to compress and decompress some string data with PoolByteArray `compress()` and `decompress()`.  I did work with this a few weeks ago with no problems, but today I can't get `decompress()` to return anything.

**Steps to reproduce:**

Just use this snippet and read the output. (Or run the example project.)
For me it comes back at 0 length.

```gdscript
var data = [[100, 200, 300], [400, 500, 600]]
var x = to_json(data).to_utf8().compress(File.COMPRESSION_GZIP)
print(len(x.decompress(File.COMPRESSION_GZIP))
```

**Minimal reproduction project:**

[3.1 PoolByteArray decompression issue.zip](https://github.com/godotengine/godot/files/2740622/3.1.PoolByteArray.decompression.issue.zip)

**Comment by ibrahn** [comment]
PoolByteArray::decompress takes two arguments, the first being a buffer size.
Would probably be better if this emitted an error rather than returning an empty array though.

**Comment by avencherus** [comment]
Thanks for catching that.  I overlooked it in the docs, must have gotten it crossed up with `get_buffer(len)` for using `File.open_compressed()`.  Expecting length specifications to be on file read/write.

Maybe a warning, or a requirement on the second parameter might help catch this sort of mistake.

**Comment by akien-mga** [comment]
Reopening as enhancement request for 3.2 then, it would be worth considering making the second argument mandatory indeed.

**Comment by dkotfis** [comment]
I'll get started with this

**Comment by akien-mga** [comment]
I had misunderstood this issue, all compression methods use a default mode of 0, so removing it for `decompress` only wouldn't make sense.

We could make the compression mode mandatory for all compression methods, but that's a compatibility breakage.

In this situation the first reflex should be to check the docs for `decompress()` and see that it takes two arguments.
