### ISSUE TITLE
Viewports not working in GLES2 when using their output as a texture, but do in GLES3

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#24875]
Windows 10
Godot 3.1 beta1
GeForce GTX 1050/PCIe/SSE2

Viewport contents don't render when used a mesh texture source in GLES2 of 3.1, but do in GLES3.

Here's the scene tree:
![node](https://user-images.githubusercontent.com/13801432/50931315-e7d38a00-146a-11e9-8715-6cbdc4674c72.PNG)

Here's the gles3 output:
![gles3](https://user-images.githubusercontent.com/13801432/50931337-f4f07900-146a-11e9-9d57-68a3c4cb9b83.PNG)

Here's the gles2 output:
![gles2](https://user-images.githubusercontent.com/13801432/50931344-fc178700-146a-11e9-8191-5106060ef956.PNG)

To reproduce, run [this project](https://github.com/godotengine/godot/files/2742807/temp.zip) in both gles2, gles3 and observe the differences.

**Comment by clayjohn** [comment]
I can confirm. Project works fine in GLES3, but not in GLES2. 

Ubuntu 16.04
intel integrated graphics

I noticed an additional issue when testing it out. When you create a new ``ViewportTexture`` and initialize it from the ``Viewport`` then the path is set as "Viewport" (which is relative to the root, and it works). However if you try to set the path after creating the ``ViewportTexture`` it sets the path to "../Viewport" (which is relative to the node containing the material). When you set the path to "../Viewport" it doesn't work in either GLES3 or GLES2.
