### ISSUE TITLE
CanvasItem.draw_set_transform() not limited to draw calls after transform is set.

### ISSUE THREAD

**Issue by ratsdiov** [godotengine/godot#2487]
I'm trying to use the CanvasItem.draw* methods to render a mask into a render target viewport. I need to draw textures on the mask using different transforms for each texture. draw_set_transform() says:

*Set a custom transform for drawing. Anything drawn afterwards will be transformed by this.*

I interpret that to mean anything drawn *before* draw_set_transform() would not have the transform applied (or would use whatever was last passed to a draw_set_transform() call).  However the behavior I see in 1.1stable is that everything in the _draw() call is rendered using the transform. My draw method code:

```
func _draw():
	draw_circle(Vector2(100,100), 30, Color(1, 0, 0))
	# BUG??? this causes the circle to be transformed as well.  Uncommenting the last line
	# causes no transformation to the texture or circle.
	draw_set_transform(Vector2(50,10), 0, Vector2(1,1))
	draw_texture(texture, Vector2(10,10))
#	draw_set_transform(Vector2(10,50), 0, Vector2(1,1))	
```
Both the circle and the texture are drawn with the draw_set_transform() applied. Similarly, if I uncomment the last line, neither the circle or texture are placed using the first draw_set_transform() applied. It behaves as though whatever was last passed to draw_set_transform() is used for all the draw_* calls.

With both transform calls commented out (the drawn texture is the Documentation text box):
![image](https://cloud.githubusercontent.com/assets/4614207/9944446/5e4075ac-5d55-11e5-80d4-bc59fed684b0.png)

With just the first transform call uncommented:
![image](https://cloud.githubusercontent.com/assets/4614207/9944459/790ba51e-5d55-11e5-814b-117f3a2b08fc.png)

With both calls uncommented:
![image](https://cloud.githubusercontent.com/assets/4614207/9944472/898d86aa-5d55-11e5-97da-9984604ac8a8.png)

Is this expected behavior???    If so the doc should be clarified.  Is there any other way to *individually* orient the textures I want to draw with draw_texture?  

I can send a small project that replicates the problem but here is most of it:
![image](https://cloud.githubusercontent.com/assets/4614207/9944504/b520eaf0-5d55-11e5-839b-a532e112f052.png)

**Comment by akien-mga** [comment]
It looks indeed like either the documentation is wrong, or there is a bug in the draw_set_transform function. It would be nice if you could send your sample project yes, it makes it easier to reproduce the issue.

**Comment by ratsdiov** [comment]
Attached

Rémi Verschelde wrote:

  It looks indeed like either the documentation is wrong, or there
is a bug in the draw_set_transform function. It would be nice if you
could send your sample project yes, it makes it easier to reproduce the
issue.
  —
Reply to this email directly or view
it on GitHub.
  
  
  
  
  
  
  




__________ Information from ESET Smart Security, version of virus signature database 12541 (20151109) __________

The message was checked by ESET Smart Security.

http://www.eset.com

**Comment by akien-mga** [comment]
Any file hosting or file sharing system, and preferably one that keeps the file for a long time so that it's not a dead link e.g. in 2 weeks.

**Comment by volzhs** [comment]
@ratsdiov There is a trick for attach zip file.
You can attach it by changing zip file extension to jpg or png.
and, of course, should change it to zip file extension again after download it. :)

**Comment by Calinou** [comment]
You can use https://up1.ca/, it allows uploads up to 50 MB.

**Comment by akien-mga** [comment]
> You can use Up1, it allows uploads of any binary or text paste up to 50 MB.

Looks nice indeed. Do you know how long it keeps file available?

**Comment by ratsdiov** [comment]
https://cloud.githubusercontent.com/assets/4614207/11079257/0629ca9a-87d9-11e5-94dd-92b45570d906.png

File is actually a zip file.
