### ISSUE TITLE
"Custom Node" in empty scene is misleading

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#24870]
**Godot version:**
382f099

**Issue description:**
New to 3.1, when adding a new scene, the user is prompted to select a root node for the scene. The button reads "Custom Node", which implies to users that it would create a new type of "custom" node rather than selecting from the built-in list.

I propose this button be renamed to "Choose a Node" or "Select a Node".

<img width="276" alt="screen shot 2019-01-09 at 10 55 29 am" src="https://user-images.githubusercontent.com/3812514/50921557-31858b80-13fd-11e9-8c96-ffab6f21cdbf.png">

**Comment by Duroxxigar** [comment]
Just wanted to throw my experience in there. When I first saw this, I avoided using it for like the first 3 scenes I created because I thought exactly what @cbscribe is mentioning.

**Comment by groud** [comment]
I completely agree.

**Comment by cbscribe** [comment]
Tried it a couple of ways:

<img width="279" alt="screen shot 2019-01-09 at 12 13 42 pm" src="https://user-images.githubusercontent.com/3812514/50925779-2f74fa00-1408-11e9-9f6f-740a82290205.png"><img width="273" alt="screen shot 2019-01-09 at 12 10 46 pm" src="https://user-images.githubusercontent.com/3812514/50925780-300d9080-1408-11e9-917c-7adc75460a09.png">

The first is more explicit, but kind of redundant with the "Create Root Node" prompt right above it.

**Comment by akien-mga** [comment]
"Select a Node" seems fine to me.

Why don't you have the other three options though? (2D, 3D and Control)

**Comment by cbscribe** [comment]
They hide/show when you click the star. Are they not collapsed by default...?

Either way, those are an entirely bigger problem (much more so if they're shown by default). They imply that every 2D scene must have a Node2D as its root, which is going to lead much confusion.

**Comment by akien-mga** [comment]
They're supposed to be shown by default. The star toggles to your favourite nodes, which in your case is empty because you likely don't have favourite yet.

> Either way, those are an entirely bigger problem (much more so if they're shown by default). They imply that every 2D scene must have a Node2D as its root, which is going to lead much confusion.

Well their purpose is to give an easy start on a 2D, 3D or GUI scene. They don't mean that all scenes have to start with one of those, but it's good for discoverability of the related viewports.

**Comment by girng** [comment]
the custom node button works in relation to the other 3 (2d, 3d, and UI).  it's   different (a custom one)

**Comment by cbscribe** [comment]
> Well their purpose is to give an easy start on a 2D, 3D or GUI scene. They don't mean that all scenes have to start with one of those, but it's good for discoverability of the related viewports.

I understand the purpose. But if you click "2D Scene", you get a Node2D. If you click "UI Scene" you get a Control node. What I'm concerned with is this teaches the already prevalent misconception that you have to start with a Node2D, etc.

**Comment by Duroxxigar** [comment]
I kind of agree with @timoschwarzer - maybe it should be "Other Node"

**Comment by isaacremnant** [comment]
As @cbscribe said, I fully agree that it's misleading that "2D Scene" = "Node2D". I always expect that clicking on "2D Scene" will open the "Create New Node" dialog but only with the descendants of Node2D for example. Granted the icons are O and not + say, but it's still a name mismatch for those used to the nodes already.

Because of that, I chose to hide the default menu by clicking the star and favorited Node2D and Control (didn't even bother with others). This "fixes" the name mismatch.

**Comment by hilfazer** [comment]
3.1?
I'm asking since Godot's in beta and it's not a bug.

**Comment by akien-mga** [comment]
@hilfazer It's a trivial change impact a new 3.1 feature. People will rely on 3.1 to make documentation, so if such a visual change has to happen, it's better now than that later.

**Comment by akien-mga** [comment]
But it breaks translations, so yeah, it will have to wait.

**Comment by KoBeWi** [comment]
Well, in Polish it's already translated as "Other node" and seems fine to me.
