### ISSUE TITLE
Extending inner class from named class generates Parse Error: Could not determine inheritance

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#24882]
**Godot version:** 3.1.beta.custom_build.f7d2750

**OS/device including version:** Ubuntu 16.04 64bit

**Issue description:** I have a script which extends Node that has an inner class and that inner class also extends Node. It works fine but it crashes the editor when I close and reopen the project.

**Steps to reproduce:** Comment out the inner class of ParentAndChild.gd and the project opens fine. Uncomment it again in the editor, run the scene and it works as expected. Close and reopen the project and it will crash.

> handle_crash: Program crashed with signal 11
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [1] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f86ce0764b0] (??:0)
> [2] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x2468012] (/home/oreo/Apps/Godot/godot/./core/string_db.h:125)
> [3] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x5771d0] (/home/oreo/Apps/Godot/godot/modules/gdscript/gdscript_parser.cpp:5173 (discriminator 1))
> [4] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x5adeeb] (/home/oreo/Apps/Godot/godot/modules/gdscript/gdscript_parser.cpp:8100)
> [5] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x5ae7e4] (/home/oreo/Apps/Godot/godot/modules/gdscript/gdscript_parser.cpp:8189)
> [6] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x4da019] (/home/oreo/Apps/Godot/godot/modules/gdscript/gdscript.cpp:575)
> [7] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x4dbcf0] (/home/oreo/Apps/Godot/godot/modules/gdscript/gdscript.cpp:2146)
> [8] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x26612a4] (/home/oreo/Apps/Godot/godot/./core/cowdata.h:369)
> [9] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x26617eb] (/home/oreo/Apps/Godot/godot/./core/reference.h:260)
> [10] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x121c6f6] (/home/oreo/Apps/Godot/godot/editor/plugins/script_editor_plugin.cpp:2480 (discriminator 2))
> [11] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x121d0f0] (/home/oreo/Apps/Godot/godot/./core/reference.h:267)
> [12] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0xd0829f] (/home/oreo/Apps/Godot/godot/./core/reference.h:267)
> [13] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0xdbf888] (/home/oreo/Apps/Godot/godot/./core/reference.h:285)
> [14] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0xdc8c10] (/home/oreo/Apps/Godot/godot/editor/editor_node.cpp:308)
> [15] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x2451424] (/home/oreo/Apps/Godot/godot/core/object.cpp:957)
> [16] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x15c4f5b] (/home/oreo/Apps/Godot/godot/scene/main/node.cpp:184)
> [17] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x15c4ec5] (/home/oreo/Apps/Godot/godot/./core/cowdata.h:70 (discriminator 3))
> [18] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x15d7b01] (/home/oreo/Apps/Godot/godot/scene/main/node.cpp:2523)
> [19] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x1606388] (/home/oreo/Apps/Godot/godot/scene/main/scene_tree.cpp:457)
> [20] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x427c50] (/home/oreo/Apps/Godot/godot/platform/x11/os_x11.cpp:2973)
> [21] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64(main+0xdf) [0x41902f] (/home/oreo/Apps/Godot/godot/platform/x11/godot_x11.cpp:55)
> [22] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f86ce061830] (??:0)
> [23] /home/oreo/Apps/Godot/godot/bin/godot.x11.opt.tools.64() [0x41aee9] (??:?)
> -- END OF BACKTRACE --
> 

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2744707/Test.zip)

**Comment by akien-mga** [comment]
Still same result as in the above comment. Since it's not crashing and the scripts seem functional, I'll move it to the next milestone. The error should still be investigated.

**Comment by akien-mga** [comment]
This seems fixed in 3.4.4-stable.
