### ISSUE TITLE
Adding array through func throw error

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#24889]
**godot 3.1 beta1
(Iam not a coder)

When i do it this way.**

var Item = []

```
func _Task(task):
    Item.append(task)
    print(Item)
        
func _process(delta):
    print(Item)
```

**Somewhere on other script**
```
 
onready var n = preload("res://new_script.gd").new()

func _ready():
    n._Task(Vector2(33,33)) 

```
**It prints**  
[(33, 33)]
[]
[]
[]
[]
[]
[]
[]

**But It works this way**

```
export var Item = []
    
func _process(delta):
      print(Item)
        
```

**On the other script**

```
onready var n = load("res://new_script.gd").new()

func _ready():
	n.Item.append(99)
```

**Comment by FlamyAT** [comment]
I am using 6582968.
I can't reproduce your output. (Mine: `[(33, 33)]`)

Another problem with your output is that it's more than one line. Unless you instance your "new_script" as a child `_process` won't be fired.

**Comment by gamergamesz** [comment]
Well they both are on a node of same scene

**Comment by groud** [comment]
Please provide a reproduction project.

**Comment by FlamyAT** [comment]
I think I understand.
This project should mimic his problem: 
[issue.zip](https://github.com/godotengine/godot/files/2746942/issue.zip)

This is expected behaviour. You aren't editing the other node but a new instance.
Replace your `onready var n = preload("res://new_script.gd").new()` with `onready var n = $PATH/TO/YOUR/NODE`.

**Comment by Naryosha** [comment]
>Adding array through func **throw error**

What error?

**Comment by Naryosha** [comment]
As far as I understand, you set value in one Node but print a value of another Node, so the output being different is expected. Without project or scene tree, I don't know if it's a bug or not.

**Comment by Naryosha** [comment]
More info about why 2nd example works:
http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#exporting-arrays

>Exporting arrays works, but with an important caveat: While regular arrays are created local to every class instance, **exported arrays are shared between all instances.** This means that editing them in one instance will cause them to change in all other instances. Exported arrays can have initializers, but they must be constant expressions.

**Comment by gamergamesz** [comment]
Ok It's working on both code now, It was the indent error, i guess.
