### ISSUE TITLE
Body still collides with scale = (0, 0)

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#24885]
**Godot version:** Godot 3 Beta 1

**OS/device including version:** Windows 10 64-bit

**Issue description:**

Bodies with `scale = (0, 0)` still collides with others.

**Steps to reproduce:**
1. Create a body
2. Set its `scale = (0, 0)`

**Minimal reproduction project:** 
[Scale0Collision.zip](https://github.com/godotengine/godot/files/2745378/Scale0Collision.zip)
This is a standalone scene. Copy and open it in a project of yours.

**Comment by groud** [comment]
I think that is an expected behavior. The object becomes a "theoretical point", which IMHO, should collide.

**Comment by timoschwarzer** [comment]
Also:
> Be careful to never scale your collision shapes in the editor. The “Scale” property in the Inspector should remain (1, 1). When changing sizing the collision shape, you should always use the size handles, not the Node2D scale handles. Scaling a shape can result in unexpected collision behavior.
https://docs.godotengine.org/en/3.0/tutorials/physics/physics_introduction.html#collision-shapes

**Comment by groud** [comment]
@timoschwarzer, this is no more the case in 3.1 ;)

**Comment by timoschwarzer** [comment]
@groud Oh, didn't know that :)

**Comment by DleanJeans** [comment]
It's just that I disable my `CollisionShape2D` as the default setting for my body scene then forgot to enable it again a couple of times which wasted some bit of time.
