### ISSUE TITLE
Is encrypted scripts feature is broken in 3.1.beta1?

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#24881]
**Godot version:**

Godot 3.1.beta1 (actually commit e46f28e02)

**OS/device including version:**

MacOSX 10.13.6
Android 7.1.2

**Issue description:**

I rebuilded godot tools, android export templates with `export SCRIPT_AES256_ENCRYPTION_KEY="A9791BE777CD325BEAF0A9791BE748CDBEAF0A0DEAD33216543FEED4CEBA8901"`

I checked that file `core/script_encryption_key.gen.cpp` contains the right key:
```
#include "core/project_settings.h"
uint8_t script_encryption_key[32]={0xA9,0x79,0x1B,0xE7,0x77,0xCD,0x32,0x5B,0xEA,0xF0,0xA9,0x79,0x1B,0xE7,0x48,0xCD,0xBE,0xAF,0x0A,0x0D,0xEA,0xD3,0x32,0x16,0x54,0x3F,0xEE,0xD4,0xCE,0xBA,0x89,0x01};
```

I set up script key in export settings:
![2019-01-10 12 12 04](https://user-images.githubusercontent.com/1177068/50958111-fce30400-14d0-11e9-939f-298fd8e8ae4c.png)

When I run game on android device it fails with:
```
01-10 12:00:41.056: E/godot(31948): **ERROR**: Condition ' magic != 0x43454447 ' is true. returned: ERR_FILE_UNRECOGNIZED
01-10 12:00:41.056: E/godot(31948):    At: core/io/file_access_encrypted.cpp:65:open_and_parse() - Condition ' magic != 0x43454447 ' is true. returned: ERR_FILE_UNRECOGNIZED
01-10 12:00:41.057: E/godot(31948): **ERROR**: Condition ' err ' is true. returned: err
01-10 12:00:41.057: E/godot(31948):    At: modules/gdscript/gdscript.cpp:755:load_byte_code() - Condition ' err ' is true. returned: err
01-10 12:00:41.057: E/godot(31948): **ERROR**: Condition ' err != OK ' is true. returned: RES()
01-10 12:00:41.057: E/godot(31948):    At: modules/gdscript/gdscript.cpp:2135:load() - Condition ' err != OK ' is true. returned: RES()
01-10 12:00:41.057: E/godot(31948): **ERROR**: Failed loading resource: res://common/Log.gde
01-10 12:00:41.057: E/godot(31948):    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
01-10 12:00:41.057: E/godot(31948): **ERROR**: Can't autoload: res://common/Log.gd
01-10 12:00:41.057: E/godot(31948):    At: main/main.cpp:1537:start() - Condition ' res.is_null() ' is true. Continuing..:
01-10 12:00:41.058: E/godot(31948): **ERROR**: Condition ' magic != 0x43454447 ' is true. returned: ERR_FILE_UNRECOGNIZED
01-10 12:00:41.058: E/godot(31948):    At: core/io/file_access_encrypted.cpp:65:open_and_parse() - Condition ' magic != 0x43454447 ' is true. returned: ERR_FILE_UNRECOGNIZED
01-10 12:00:41.059: E/godot(31948): **ERROR**: Condition ' err ' is true. returned: err
01-10 12:00:41.059: E/godot(31948):    At: modules/gdscript/gdscript.cpp:755:load_byte_code() - Condition ' err ' is true. returned: err
<a lot of errors about every gd script file>
```

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by bruvzg** [comment]
I can confirm this, encryption is broken. Exported `.pck` file contains `0` size `.gde` scripts.

**Comment by bruvzg** [comment]
It's using non existing path for temporary file here: [modules/gdscript/register_types.cpp#L82](https://github.com/godotengine/godot/blob/master/modules/gdscript/register_types.cpp#L82)

Form this translates to `/Users/bruv/Library/Application Support/Godot/tmp/script.gde` and `/Users/bruv/Library/Application Support/Godot/tmp` doesn't exist and is not created during export!

**Comment by akien-mga** [comment]
It should use `EditorSettings::get_singleton()->get_cache_dir()` instead.

**Comment by Xrayez** [comment]
Yeah, It works perfectly fine on Windows that way though! I'll try to fix it now...

**Comment by Xrayez** [comment]
I guess the reason it worked for me is because I started using Godot when it was 2.1, so the `tmp` directory was there haha! I should probably clean those editor settings anew.
