### ISSUE TITLE
Exporting pck/zip fails if no export preset is configured/selected

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#24894]
**Godot version:**
3.1-beta1

**OS/device including version:**
Win 7 64 bit

**Issue description:**
I have no templates downloaded for this version, but wanted to test standalone with the editor itself as a "template" to debug another issue.

Expected: pck/zip export should work in this case
Happens: see below

**Steps to reproduce:**
Try to export pck/zip when there is no entries in the export list. Then choose where to save the target file.
Godot complains in console (but GUI-wise fails silently): 
```
editor/editor_export.cpp:1170 - Index p_idx=-1 out of size (export_presets.size()=0)
editor/project_export.cpp:891 - Condition ' current.is_null() ' is true.
```

If add a dummy Windows export, it complains in the export dialogue, but the export to pck/zip starts to work.

**Comment by akien-mga** [comment]
From what you describe, it's not so much about templates being installed, but about needing an export preset (Windows, Android, etc.) to be able to export the corresponding ZIP/PCK.

And it makes sense, as the contents of the ZIP/PCK depend on that preset's configuration (whether to include ETC, ETC2, S3TC, etc., and other platform-specific differences).

The UX could be improved though, it should not let you try to export and then fail if you don't have any preset selected.
