### ISSUE TITLE
Mono/C# - Cannot reference external library

### ISSUE THREAD

**Issue by alexfonseka** [godotengine/godot#24898]
**Godot version:**
3.0.6 Stable Mono, also same issue with 3.1 beta mono

**OS/:**
Win 10

**Issue description:**
Cannot reference external DLL in C#. My solution compiles fine but when launching from within the editor it fails to find the required runtime DLLs. Getting the following output on the console
```
Unhandled Exception:
System.DllNotFoundException: fmodstudio.dll
  at (wrapper managed-to-native) FMOD.Studio.System.FMOD_Studio_System_Create(intptr&,uint)
  at FMOD.Studio.System.create (FMOD.Studio.System& studiosystem) [0x00006] in D:\Godot Projects\g\fmod_studio.cs:597
  at Node._Ready () [0x00015] in D:\Godot Projects\g\Node.cs:16
```

I'm using Fmod library here which requires the DLLs be present during runtime. In my VS project I have the DLLs set to be copied over to the build path. And also I can't seem to add them as a reference I get this error on VS 
```
Please make sure the file is accessible, and that it is a valid assembly or COM component.
```

If not in the build path where exactly do I need to place the DLL files for them to be found?

**Comment by Kiotenhariyo** [comment]
I am having the same stress. Only reference found so far is that this cannot be done. Have to write a C++ wrapper of some sort (GDNative). I have tried that without success (do not know C++ and do not wish to struggle through it). So will be following your question closely for hints or answers as this should be possible without jumping several language hoops.

**Comment by alexfonseka** [comment]
@Kiotenhariyo I was successfully able to reference FMOD as an unmanaged lib and it's all working as intended on Godot 3.1 beta 3 🙌

The DLL/lib files must be placed either in the Godot exe directory or at the root of your project directory.  When exporting they must be present in the same directory as the executable. 
https://www.mono-project.com/docs/advanced/pinvoke/#windows-dll-search-path

So glad this issue is resolved! Writing C++ modules will still result in better performance but being able to use existing C# wrappers is incredibly useful.

**Comment by neikeq** [comment]
I guess this can be closed. Feel free to open a new issue if it's desired to have a way to tell the editor to copy these files when exporting the game.

**Comment by horseyhorsey** [comment]
> @Kiotenhariyo I was successfully able to reference FMOD as an unmanaged lib and it's all working as intended on Godot 3.1 beta 3 🙌
> 
> The DLL/lib files must be placed either in the Godot exe directory or at the root of your project directory. When exporting they must be present in the same directory as the executable. https://www.mono-project.com/docs/advanced/pinvoke/#windows-dll-search-path
> 
> So glad this issue is resolved! Writing C++ modules will still result in better performance but being able to use existing C# wrappers is incredibly useful.



> @Kiotenhariyo I was successfully able to reference FMOD as an unmanaged lib and it's all working as intended on Godot 3.1 beta 3 🙌
> 
> The DLL/lib files must be placed either in the Godot exe directory or at the root of your project directory. When exporting they must be present in the same directory as the executable. https://www.mono-project.com/docs/advanced/pinvoke/#windows-dll-search-path
> 
> So glad this issue is resolved! Writing C++ modules will still result in better performance but being able to use existing C# wrappers is incredibly useful.

I'm finding this a pain. Works when exported, but not when you run from the editor.
