### ISSUE TITLE
Custom resources don't automatically save!

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#24896]
**Godot version:**
last commit was 27d7772, master version!

**OS/device including version:**
Mojave OSX

**Issue description:**
When editing a resource (custom) it doesn't automatically saves when I press "CMD + S" or "CMD+OPT+S". I need to use the save icon in the top of the inspector. Shouldn't changes be saved automatically? they are in other engines (ex: Unity).

I also get an error when editing the resources:

<img width="886" alt="captura de ecra 2019-01-10 as 22 08 58" src="https://user-images.githubusercontent.com/10358443/51000242-6f310400-1524-11e9-8529-2afcf4d3c89b.png">

**Comment by UgisBrekis** [comment]
You need to call property_list_changed_notify() whenever any property in your resource changes. This means that you'll have to use setter functions and call that from there, but it works.

**Comment by xDGameStudios** [comment]
I used property_list_changed_notify() and setter functions and I still have this problem... I edit the resource and if I open it in a text editor it doesn't get saved.

**Comment by KoBeWi** [comment]
Isn't it related? #25832

**Comment by UgisBrekis** [comment]
Is the resource in tool mode?

**Comment by KoBeWi** [comment]
Checked in 3.4 and the resources are saved with Ctrl+S, there is even a dedicated message (appears when you have no scene opened):
![image](https://user-images.githubusercontent.com/2223172/142782608-99304c06-3f11-4ff5-b004-cc26dccbfcd6.png)
Closing.
