### ISSUE TITLE
[C#] Exported array doesn't use supplied type as type hint

### ISSUE THREAD

**Issue by Jcozman** [godotengine/godot#24891]
**Godot version:**
3.1 beta 1  Mono

**OS/device including version:**
Windows 10

**Issue description:**
Exporting an array of `PackedScene` does not use `PackedScene` as the type, requiring the user to manually set the type of the array element before being able to add a `PackedScene` as an element.

Expected behavior is that any new element in the Array should default to the `PackedScene` type.

This looks like it has been fixed for GDScript with https://github.com/godotengine/godot/issues/20004 but is a problem with C#.

Here is the view after building:
![annotation](https://user-images.githubusercontent.com/4622925/50991909-c367c400-14e3-11e9-8057-571eff95c705.png)

Here is the view after manually changing array index 0 to a `PackedScene`:
![annotation2](https://user-images.githubusercontent.com/4622925/50991934-d4183a00-14e3-11e9-96af-ae6616649dbb.png)

**Steps to reproduce:**
Using C#, export an array of `PackedScene`. Observe that you must manually change the array elements to the `PackedScene` type.

**Minimal reproduction project:**
[Example.zip](https://github.com/godotengine/godot/files/2746795/Example.zip)

**Comment by akien-mga** [comment]
Moving to 3.2 milestone as it's not critical for 3.1, but feel free to change it back @neikeq if you think otherwise.

**Comment by akien-mga** [comment]
Confirmed in 3.1 beta 7.

I tried to play around with the undocumented type hints, but I don't see any that could implement the typed array hint feature of GDScript. (I tried `[Export(PropertyHint.ResourceType, "PackedScene"]` and similar things.)
