### ISSUE TITLE
Wireframe display of 3D view in editor doesn't really work

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2489]
Wireframe display of 3D view in editor doesn't really work

![3dwireframe](https://cloud.githubusercontent.com/assets/6099/9960086/28e5a554-5e21-11e5-9ac1-ad25eacbffd4.png)

**Comment by slapin** [comment]
just enable wireframe view and try to navigate

**Comment by Calinou** [comment]
It's called a "hall of mirrors" effect and is caused by the renderer not clearing the view every frame.

**Comment by slapin** [comment]
Can be seen on git@github.com:slapin/simple-rpg.git
subdirectory godot, scene - roomctl.scn

**Comment by akien-mga** [comment]
Confirmed by @unpause on #4689.

**Comment by djrm** [comment]
this has been fixed

**Comment by slapin** [comment]
Well, it is reproducible if cubemap is active (only in editor).
Well, even if no cubemap, but WorldEnvironment, too. Can't say it is only case though.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
Assumed fixed with the new renderer engine in 3.0. Don't hesitate to comment/reopen if it's not the case.
