### ISSUE TITLE
GDNative + GDScript Memory Leak

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#24905]
This might be similar to https://github.com/godotengine/godot/issues/19676, but the repro for this one is different.

**Godot version:**
commit f2e7a650c7c23a7ec5c9dbf43ef605885e26d60e

**OS/device including version:**
OSX - Sierra 10.12.6

**Issue description:**
I created an Object in GDNative and returned it into GDScript. The object never gets deleted even though it's not being referenced after the first loop.

**Steps to reproduce:**
1. Run the godot project
2. Open up Debugging -> Monitor

Expected: The object counts stays around the same number
Actual: The object count keeps increasing and memory usage keeps increasing

**Minimal reproduction project:**
[gdnative_memory_leak.zip](https://github.com/godotengine/godot/files/2748063/gdnative_memory_leak.zip)

In case I'm simply just doing something wrong in how I create objects in GDScript, here's some code.

This runs every frame
```gdscript
extends Node2D

func _physics_process(delta):
	var b = Bug.new()
	var b2 = b.create_bug()
```

Here's the Bug class in GDNative:
```cpp
#ifndef BUG_HPP
#define BUG_HPP

#include <Godot.hpp>
#include <Reference.hpp>

namespace godot {

class Bug : public godot::Reference {
    GODOT_CLASS(Bug, Reference)
public:
    void _init() {
    }

    ~Bug() {
    }

    Ref<Bug> create_bug() {
        return Ref<Bug>(Bug::_new());
    }

    static void _register_methods() {
        register_method("create_bug", &Bug::create_bug);
    }
private:
    int* i;
};
};

#endif
```

**Comment by bruvzg** [comment]
Most likely it's a bug on the `godot-cpp` side. Same issue in `godot-cpp` repo: https://github.com/GodotNativeTools/godot-cpp/issues/215

**Comment by BastiaanOlij** [comment]
I think this is a problem in taking the wrong approach. 
Bug::new() will create a new object with reference count 1. 
Ref<Bug>(Bug *) will create a reference to the object given to it and set the reference count to 2, it's a syntax meant to create additional references to an object.
Then when the reference is destroyed the reference count goes back to 1 which is not enough. 

Try this syntax:
```
Ref<Bug> bug;
bug.instance();
return bug;
```

`Instance()` will construct the object knowing that this is the first reference to the object. Reference count will be 1. When the reference is destroyed, the reference count will hit 0 and the object will also be destroyed.

**Comment by bruvzg** [comment]
> Try this syntax

This leaks as well (but only if `Bug` is custom gdnative class, Godot classes work fine), ref count if higher by 1 then should be.

But `return = Ref<Bug>::__internal_constructor(Bug::_new());` do work.

Related to: https://github.com/GodotNativeTools/godot-cpp/issues/85 and https://github.com/GodotNativeTools/godot-cpp/pull/88 (fix for Godot classes).

**Comment by Lucrecious** [comment]
I have a main project with a leak, and I'm trying to narrow down how the memory leak happens. Right now to diagnose I use the Object counter in the Monitor on Godot.

I found this memory leak in this scenario (1):
[gdscript code](http://pasteall.org/1472320)
[gdnative code](http://pasteall.org/1472322/cpp)

Expected: Object counter stays the same
Actual: Object counter goes up in definitely


But in this scenario (2), no memory leak:
[gdscript code](http://pasteall.org/1472320)
[gdnative code](http://pasteall.org/1472325/cpp)

Expected: Object counter stays the same
Actual: As expected.

The difference from (1) to (2) is `Array arr = var.call("make_array", NULL, 0);` to `Variant arr = var.call("make_array", NULL, 0);`

There may be a memory leak with implicit conversions it seems?

Switching from the former to the latter doesn't fix my memory leak issue in my main project, but might be worth looking into in case the issue I'm having and this issue are related or even the same.

**Comment by Lucrecious** [comment]
So I figured out the bug.

It has to do with `=` operator.
This is a problem:
```cpp
void bug(Variant var) {
                 // imake_array returns an array with minimum two elements of Object type
		Variant arr = var.call("make_array", NULL, 0);
		Variant v = arr.call("pop_back", NULL, 0);
		Variant b = arr.call("pop_back", NULL, 0);
		
                 // This here is the sequence that causes the problem
		Variant c; // This is okay
		c = v; // This is okay
		c = b; // This causes the memory leak
	}
```

It seems like an issue that happens when `c` is an Object variable _replaced_ by another variant.
So these also leak:
```cpp
Variant c;
c = v;
c = Variant();
// ----
Variant c;
c = v;
c = v;
```

The issue is replacing a non-null **Object-type** Variant. This isn't an issue with Godot primitive types (int, string, bool, ...) or Godot basic types (Dictionary, Array, ...). This is an issue with objects you need to instantiate - `Reference`s included, Objects instances of `FuncRef` (tested) or user defined classes (tested) cause memory leaks if they are `v`.

The only thing that _seems_ to fix this right now is this:
```cpp
Variant c;
c = v;
c.call("unreference", NULL, 0); // Remove a reference count
c = Variant();
```
But obviously this isn't satisfactory.

This is a pretty easy way to leak do and there is no good workaround. Also, it'd be difficult to detect for many users who use libraries.

I'll take a look at the source for this when I have time, because the fix doesn't seem like it'd be too difficult, but I'll need to learn my way.

_Any pointers on where to look would be great_, otherwise I'll probably try to step through on a debugger sometime this week.

**Comment by akien-mga** [comment]
As mentioned above by @bruvzg, and confirmed by @karroffel, the issue seems to be in the `godot-cpp` bindings, not GDNative.

@Lucrecious Could you copy the relevant debug info to https://github.com/GodotNativeTools/godot-cpp/issues/215?
