### ISSUE TITLE
Control elements not responding?

### ISSUE THREAD

**Issue by Atherz97** [godotengine/godot#24902]
Godot 3.0.6 Mono Stable
Kubuntu 18.04

**Issue description:**
Probably a simple fix but for some reason none of the signals from button presses, text edit selections etc are being called on my app. I have them linked to functions within their parent, which also inherits the Control class.

![image](https://user-images.githubusercontent.com/23059413/51008209-cf21ad80-1518-11e9-815e-1ded4d38eb12.png)

![image](https://user-images.githubusercontent.com/23059413/51008309-3fc8ca00-1519-11e9-9383-aa5f2f540571.png)

**Comment by Naryosha** [comment]
>    toggled ( bool button_pressed )
>
>This signal is emitted when the button was just toggled between pressed and normal states **(only if toggle_mode is active)**. The new state is contained in the pressed argument.

Is it active? Also please attach the project.

**Comment by Atherz97** [comment]
Yes it is active. And it's much broader too, neither TextEdit, MenuButton, nor normal Buttons seem to be working.

See what you can do: https://drive.google.com/open?id=1qK-eLOOTlwrqCadCegAV-REHoLw1bS-2

**Comment by Atherz97** [comment]
Ahah! Awesome!

So Mouse Filter just in case elements get blocked, got it.

**Comment by Naryosha** [comment]
You can use Misc tab in the debugger to see which control consumed the mouse event
![image](https://user-images.githubusercontent.com/43379543/51012448-b6081380-158f-11e9-9aa9-8faa84e60f39.png)
