### ISSUE TITLE
Array of specified type should not allow change type.

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#24900]
**Godot version:**
version #27d7772 (master)

**OS/device including version:**
Mac OSX Mojave

**Issue description:**
when exporting arrays using a fixed type (for example):

`export(Array, PackedScene) var a;`

you should not be allowed to edit type (the pencil icon should be hidden).

**Comment by akien-mga** [comment]
I don't think this is a bug, this is just a type hint and not a type declaration, so you're allowed to change `a` to give it a completely different type, whether from the editor or in your script.

It's not the same as static typing, the `export()` syntax is just a helper.

**Comment by xDGameStudios** [comment]
> I don't think this is a bug, this is just a type hint and not a type declaration, so you're allowed to change `a` to give it a completely different type, whether from the editor or in your script.
> 
> It's not the same as static typing, the `export()` syntax is just a helper.

Normally if you are exporting an array of a given type it is normally a sign (for development sanity) you want that type to be kept. If you want a heterogeneous array just omit the type.
That being said! Is there a way to export a static typed variable?

**Comment by xDGameStudios** [comment]
> Would that work?
> 
> ```gdscript
> export(Array, PackedScene) var a: Array
> ```
> 
> Or by inferring the default value's type (if any):
> 
> ```gdscript
> expot(Array, PackedScene) var a := […]
> ```

What I meant is if there is a way to define the array ("subtype") that means I want to define an array and avoid designers (that work essentially in the inspector) to break things that are defined inside the code.

Array of PackedScenes should not become an array of ints... or an Array of PackedScenes should not contain a float somewhere in its elements.
