### ISSUE TITLE
Godot barely functioning on new Laptop

### ISSUE THREAD

**Issue by CuteGam3rGirl** [godotengine/godot#24906]
**Godot version:** 3.06 and 3.1 beta1 and 3.02

**OS/device including version:**
Asus Zenbook 14 flip ux461fa, Windows 10

**Issue description:**
Upon launching Godot, it will perpetually stay on the boot screen with the logo, until I click outside the window. This has to be done for any action, such as clicking cancel, or new project. Expansion of the window to fullscreen or otherwise results in a black window and often crashes. Lastly when installing or creating a new file, typing is broken, each letter typed is stuttered, meaning that if I were to press backspace once, nothing would happen, but a second press would result in the expected backspace behavior, but the second backspace would be "stored" so any button pressed afterwards would result in a backspace again.

**Steps to reproduce:**
This occurs every time on this particular laptop, I have redownloaded and tried various versions, I have tried disabling touchscreen, and updating drivers, none of which fixed the issue.

**Comment by akien-mga** [comment]
Sounds like the same issue as #23069. Downgrading Intel graphics drivers to 21.x should fix it.
