### ISSUE TITLE
Unable to assign Texture3D to Sprite

### ISSUE THREAD

**Issue by TheFlamyy** [godotengine/godot#24919]
**Godot version:** bf79924

**OS/device including version:** Ubuntu

**Issue description:**
While debugging #24872 I discovered that setting a `Sprite`'s texture to a `Texture3D` results in a `null` in the remote scene tree.
Assigning any other texture works flawlessly. 

**Steps to reproduce:**
Assign this script a Sprite.
```
extends Sprite

func _ready():
	var tex3D = TextureArray.new()
	tex3D.create(64, 64, 2, Image.FORMAT_RGBA8)
	var img1 : Image = Image.new()
	img1.load("res://icon.png")
	for i in 2:
		print(i)
		tex3D.set_layer_data(img1, i)
	texture = tex3D
	#var img2 = tex3D.get_layer_data(0)
	#img2.save_png("img.png")

	print ("ready")
```

**Comment by JFonS** [comment]
Assigning a 3D texture to a (2D) Sprite doesn't make much sense to me.

What would you expect to happen if it was possible? 

Which part of the 3D texture would be displayed?

**Comment by FlamyAT** [comment]
I thought you use it to layer multiple images into one texture. So all images should be shown but taking alpha/overlapping into account

**Comment by FlamyAT** [comment]
I also tried the same with `TextureArray`. With that in mind this also has nothing to do with alpha layers etc., does it?

**Comment by akien-mga** [comment]
I guess `Sprite` should probably raise an error when you assign a `TextureLayered` to it (note that it's already not possible to assign via the inspector, as `TextureLayered` does not inherit `Texture`.

> I also tried the same with TextureArray. With that in mind this also has nothing to do with alpha layers etc., does it?

Look up [solid texturing](https://johanneskopf.de/publications/solid/).

**Comment by TheFlamyy** [comment]
Closing due to lack of necessity.

The "wanted result" can be achieved with some work-arounds
