### ISSUE TITLE
Several minute long hitch when beginning to render 3d content with GLES3

### ISSUE THREAD

**Issue by ForLoveOfCats** [godotengine/godot#24911]
**Godot version:**
3.0.6 *and* 3.1 Beta 1

**OS/device including version:**
Manjaro Linux x86_64
Radeon R7 360 w/Mesa 18.3.1-1

**Issue description:**
When either the editor or my own game begin rendering 3d content, Godot encounters a massive several minute long hitch during which the engine completely pegs one of my four cores (shader compilation?). After a while the game or editor will continue as normal. There is also a several second hitch when unhiding a MeshInstance which had it's mesh changed while hidden. Neither apply when using the GLES2 renderer in 3.1 Beta 1. After the initial hitch all following runs do not encounter the long hitch however the unhiding hitch remains.

**Steps to reproduce:**
It seems hardware/driver related. I have a friend running the same OS (and same update level) with a similar GPU who also encounters this issue. Just running the editor reproduces the issue.

**Minimal reproduction project:**
Just running the editor reproduces the issue, however it seems to be hardware/driver related so reproduction may prove difficult.

**Comment by reduz** [comment]
Please also report this in the MESA bug tracker:
https://www.mesa3d.org/bugs.html
They will likely find a better workaround than us

**Comment by ForLoveOfCats** [comment]
Yes it appears to be a duplicate, apparently my search was not thorough enough. Apologies
