### ISSUE TITLE
Project Settings tooltips have misplaced line breaks and missing links.

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#24926]
**Godot version:**
master 1b5b27430

**OS/device including version:**
macOS 10.14.2

**Issue description:**
- Long tooltips in `Project Settings` have misplaced line breaks.
- Some `[method name]` and `[member name]` tags are not translated into links ~(links to other class documentation, `OS.*` on screenshot)~, some are ~(links to ProjectSettings docs)~.

![51060459-850ff900-15f8-11e9-9171-8300854b03ff](https://user-images.githubusercontent.com/7645683/51060579-dfa95500-15f8-11e9-8e1c-d7b56bc200d3.png)

Related issue: #20317 (border is fixed, formatting is not)

**Comment by akien-mga** [comment]
> Some [method name] and [member name] tags are not translated into links (links to other class documentation, OS.* on screenshot), some are (links to ProjectSettings docs).

That's just a human error in the XML, those `[method]` references are invalid (should likely be `[member OS.user_data_dir]`).

**Comment by akien-mga** [comment]
> > Some [method name] and [member name] tags are not translated into links (links to other class documentation, OS.* on screenshot), some are (links to ProjectSettings docs).
> 
> That's just a human error in the XML, those `[method]` references are invalid (should likely be `[member OS.user_data_dir]`).

Actually no, they're correct in the HTML docs. Not sure why they're broken here.

**Comment by bruvzg** [comment]
>Probably the line breaks happening before tokenization.

Looks like it, links to `Viewport` and `Environment` in `rendering/environment/default_clear_color` are show correctly, and all broken links have line break.

**Comment by homer666** [comment]
> Long tooltips in `Project Settings` have misplaced line breaks.

It might be worth noting that this happens with any sufficiently-long tooltip anywhere in the editor. For example, the `mix_target` property of an AudioStreamPlayer node:

![image](https://user-images.githubusercontent.com/27100585/51070277-a02f4700-1692-11e9-84e4-39a72282d4b7.png)

**Comment by smedelyan** [comment]
In 3.0.6 that does not work as well
![docs_on_hover](https://user-images.githubusercontent.com/47334605/52526136-5ce1eb80-2cc5-11e9-9b55-21d947715dc5.jpg)
