### ISSUE TITLE
Having trouble dynamically creating collision objects in runtime.

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#24929]
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10

**Issue description:**

In my code I am dynamically creating collision objects in runtime.

```
var area = Area2D.new()
var shape = RectangleShape2D.new()
var extents = Vector2(16,16)

shape.extents = extents
var shape_owner = area.create_shape_owner(area)
area.shape_owner_add_shape(shape_owner,shape)

add_child(area)
```
It doesn’t show up with visual collision shapes enabled and doesn’t function whether in the physics update or not.

**Steps to reproduce:**
Copypasta code into a 2d node and test against other 2D collision objects added via the editor. I personally used Area2D's get_overlapping_bodies() function and it always returned an empty array

**Comment by kubecz3k** [comment]
I'm not sure if I'm right but as far as I remember in 3.x you need to actually create and add Shape node as well. Try something like this:
```
	var area = Area.new()
	var collision_shape_node = CollisionShape.new();
	var sphere_shape = SphereShape.new()
	sphere_shape.radius = 1.0
	collision_shape_node.set_shape(sphere_shape);
	area.add_child(collision_shape_node)
	add_child(area)
```

**Comment by ElfEars** [comment]
Hmm... That code desn't seem to work either.
Is it working on your end?

**Comment by kubecz3k** [comment]
Yes it's, check this sample project:
[RuntimeAreaTest.zip](https://github.com/godotengine/godot/files/2752253/RuntimeAreaTest.zip)

**Comment by ElfEars** [comment]
Oops. That last one was on me (I was checking in 2d). Yeah, using CollisionShape2D worked.

This brings up another interesting question though. 
Technically the original ‘should’ work too as they’re doing the same thing under the hood. 
IIRC the CollisionShape2D node is just a proxy designed for easy access in the editor (It’s still listed as being an editor helper node in the docs as it has been before 3.0  "IMPORTANT: this is an Editor-only helper to create shapes, use get_shape() to get the actual shape.
") as all shapes need to be added in runtime.

From a quick browse of the source code, nothing in my original code seems to be flagrantly wrong. The main point of intrest is the “shape_owner” property butfrom a quick search in the source code I believe it to be used for sorting purposes only and not actually affecting anything programmatically.
I think the whole thing needs better docs but that’s for another issue.

**Comment by ElfEars** [comment]
Argh. This one was probably entirely my fault.

I guess manually adding shapes just doesn't make visible collision shapes, the main issue here is get_colliding_bodies(). 
Namely the way it updates means you can't just create a new collision object/shape and then use it. You have to wait for another physics update.
