### ISSUE TITLE
glTF textures aren't imported correctly

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#24938]
In Godot 3.1 beta 1 when exporting in glb or glTF embedded the textures aren't imported correctly, we can see that their corresponding slots are used but the textures aren't displayed correctly and the previews don't appear in the slots:

![textures not loaded](https://user-images.githubusercontent.com/30020215/51073558-ec6a8f00-1672-11e9-99ad-1c25cc20fab1.png)
When I use glTF with separated .bin and textures the textures are imported correctly. I think Godot is searching for the image in the file manager even when they are packed.

Here is a test file, it's Suzanne from Blender in .glb, it has an albedo and normal map. The orange albedo is visible when imported in Blender 2.8:
[Suzanne.zip](https://github.com/godotengine/godot/files/2752052/Suzanne.zip)

**Comment by bojidar-bg** [comment]
Would be nice to have reproduction project and operating system version. Please use the issue template next time.

**Comment by anasofgo** [comment]
I can confirm this problem, Though it works without an issue with Godot 3.0.6, Simply by dragging this 3d model to Godot 3.0.6 it automatically imports textures and materials without an issue.
With Godot 3.1 Beta 2, the mesh is imported but with black material (no textures).
3.1 Beta 2:
![godot_v3 1-beta2_win64_2019-01-20_15-01-28](https://user-images.githubusercontent.com/11005460/51439534-9aee7f80-1cc4-11e9-8e5b-27acf87bd87f.png)
3.0.6:
![godot_2019-01-20_15-00-01](https://user-images.githubusercontent.com/11005460/51439535-9aee7f80-1cc4-11e9-82d0-7877267826a0.png)

Windows 10 64 bit,
OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2 , Intel core i7
[tree.zip](https://github.com/godotengine/godot/files/2776597/tree.zip)

**Comment by anasofgo** [comment]
I think it is solved now in 3.1 !

**Comment by akien-mga** [comment]
Awesome! Closing as fixed then. Please comment if you can still reproduce it.

**Comment by Linko-3D** [comment]
The textures are now imported correctly, but if they are embedded or if we use glb (this format always packs the textures) they are imported but not updated. I have opened another issue I don't know if this is considered as duplicate: https://github.com/godotengine/godot/issues/27410
