### ISSUE TITLE
AnimationPlayer "Current Animation" is not saved

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#24940]
Godot 3.1 Beta 1
Win 7
Testing a 3D character animation.

The AnimationPlayer field "Current Animation" does not save when we change the animation.
"Current Animation" always come back to "[stop]".

**Comment by KoBeWi** [comment]
Is this really a bug? In the code, the `current_animation` is marked as editor-only. You are supposed to play animation with `play()` or by setting it as autoplay.

Actually, maybe it could be hidden in the inspector, as it basically serves no purpose there.
