### ISSUE TITLE
[Linux] Exported project icon doesn't show up in task bar until refresh

### ISSUE THREAD

**Issue by Nobelix** [godotengine/godot#24948]
**Godot version:**
Godot 3.1 -beta1

**OS/device including version:**
Ubuntu 18.04 -Gnome Shell

**Issue description:**
When an exported project is launched the icon does not show up in the task bar like this:
![capture d ecran de 2019-01-12 17-27-27](https://user-images.githubusercontent.com/30960698/51076368-d622fa00-1697-11e9-9765-644c87a0922e.png)
But as soon I launch Firefox there is some kind of refresh and the icon appears:
![capture d ecran de 2019-01-12 17-27-44](https://user-images.githubusercontent.com/30960698/51076372-ee931480-1697-11e9-8c24-0bc62f248351.png)

**Steps to reproduce:**

1. Export a project
2. Launch it
3. Launch another app

**Comment by groud** [comment]
Since it's likely related to X11, I put it in rendering. But porting make sense too I guess.

**Comment by Nobelix** [comment]
@groud I think it's a question of sending some kind of refresh request to the desktop.

**Comment by hpvb** [comment]
Yeah, we need to send a WM_NET message, I don't know which one so I just assigned it to myself. I'll figure it out.

**Comment by Nobelix** [comment]
Hii, what's the status of this issue?

**Comment by MJacred** [comment]
Hi @Nobelix,
I think I fixed this. Originally, I just wanted to fix that old issue with Cinnamon for myself (as the original issue was closed w/o fix in [#3631](https://github.com/godotengine/godot/issues/3631)).
Then I found this issue and (after understanding export templates a bit), I checked and found out this also might fix your problem (see commit [here](https://github.com/MJacred/godot/commit/454a513b120c27644e118657771c6236b998634b)). At least it worked on my old Cinnamon. Before this fix the window also didn't show in my taskbar (neither Godot Editor nor executable, except with move to different workspace...)

Can you or @hpvb test with my branch: https://github.com/MJacred/godot/commits/3.1 (I can also make a pull request to branch master and 3.1 in official godot repo...)
I have a binary, but even zipped it's too big with 87 MB for github (in a comment)...
I tested it with the suggested build setup for visual studio code as described in the [documentation](https://docs.godotengine.org/en/3.1/development/cpp/configuring_an_ide.html#visual-studio-code). So it should equal the export template "linux_x11_64_debug", I think.

**Comment by akien-mga** [comment]
@MJacred That patch seems fine, could you make a PR against the master branch? (not 3.1, we cherry-pick relevant changes there once merged in master). Note that I put a comment about a style issue on your current commit, so you'd have to fix that for the PR.

**Comment by MJacred** [comment]
Noted.
Is it OK to remove the include altogether and exchange VERSION_NAME macro usage with "Godot Engine"? We'd save an include for a value that will be overridden right afterwards anyway...

**Comment by akien-mga** [comment]
Sounds good yeah.

**Comment by akien-mga** [comment]
Fixed by #28512.
