### ISSUE TITLE
[GLES 2] Screen corruption on borders when resizing window

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#24941]
**Godot version:**
v3.1 beta 1, but has been present since before alpha 1.

**OS/device including version:**
Linux 64-bit (Ubuntu 18.10)
Nvidia 1050Ti (using *Nouveau* drivers)

**Issue description:**
When the window is "normal" size (i.e. the size of the application in question), so sans borders, everything is normal. ![screen_corruption_normal](https://user-images.githubusercontent.com/324679/51074446-39506480-1677-11e9-840a-2a67503f318c.png)

Resizing the window however (such as maximising it), produces corruption (flickering/artifacts) on the "borders" of the application. 
![screen_corruption_visible](https://user-images.githubusercontent.com/324679/51074449-5422d900-1677-11e9-8a05-8363abbfd6ae.png)

GLES 3 does not display any such corruption.

This may be a drivers issue. I haven't tested this recently with Windows 10.

**Comment by akien-mga** [comment]
Looks like #24556 indeed.
