### ISSUE TITLE
External resources and subresources are not sorted logically in 2.0 format

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2495]
Here is an example of git diff output when converting a 1.1 scene to the 2.0 format:

```
-<resource_file type="PackedScene" subresource_count="11" version="1.1" version_name="Godot Engine v1.1.stable.custom_build">
-       <ext_resource path="res://scripts/menu.gd" type="Script"></ext_resource>
-       <ext_resource path="res://background.png" type="Texture"></ext_resource>
-       <ext_resource path="res://fonts/firasans-book-32.fnt" type="Font"></ext_resource>
-       <ext_resource path="res://fonts/firasans-book-16.fnt" type="Font"></ext_resource>
-       <ext_resource path="res://scripts/controls.gd" type="Script"></ext_resource>
-       <ext_resource path="res://sprites/icons/arrow-up.png" type="Texture"></ext_resource>
-       <ext_resource path="res://sprites/icons/arrow-down.png" type="Texture"></ext_resource>
-       <ext_resource path="res://sprites/icons/arrow-left.png" type="Texture"></ext_resource>
-       <ext_resource path="res://sprites/icons/arrow-right.png" type="Texture"></ext_resource>
-       <ext_resource path="res://sprites/pickups/bomb_increase.png" type="Texture"></ext_resource>
+<resource_file type="PackedScene" subresource_count="11" version="2.0" version_name="Godot Engine v2.0.alpha.custom_build">
+       <ext_resource path="res://scripts/menu.gd" type="Script" index="0"></ext_resource>
+       <ext_resource path="res://sprites/icons/arrow-down.png" type="Texture" index="6"></ext_resource>
+       <ext_resource path="res://background.png" type="Texture" index="1"></ext_resource>
+       <ext_resource path="res://fonts/firasans-book-32.fnt" type="Font" index="2"></ext_resource>
+       <ext_resource path="res://fonts/firasans-book-16.fnt" type="Font" index="3"></ext_resource>
+       <ext_resource path="res://scripts/controls.gd" type="Script" index="4"></ext_resource>
+       <ext_resource path="res://sprites/icons/arrow-right.png" type="Texture" index="8"></ext_resource>
+       <ext_resource path="res://sprites/icons/arrow-up.png" type="Texture" index="5"></ext_resource>
+       <ext_resource path="res://sprites/icons/arrow-left.png" type="Texture" index="7"></ext_resource>
+       <ext_resource path="res://sprites/pickups/bomb_increase.png" type="Texture" index="9"></ext_resource>
```

The ext_resource index seems to be well computed, and I guess the XML scene header should list ext_resource sorted by their index too. The current order does not seem really logical.

**Comment by okamstudio** [comment]
ah.. probably have to resort them i guess

On Sat, Sep 19, 2015 at 6:17 PM, Rémi Verschelde <notifications@github.com>
wrote:

> Here is an example of git diff output when converting a 1.1 scene to the
> 2.0 format:
>
> -<resource_file type="PackedScene" subresource_count="11" version="1.1" version_name="Godot Engine v1.1.stable.custom_build">
> -       <ext_resource path="res://scripts/menu.gd" type="Script"></ext_resource>
> -       <ext_resource path="res://background.png" type="Texture"></ext_resource>
> -       <ext_resource path="res://fonts/firasans-book-32.fnt" type="Font"></ext_resource>
> -       <ext_resource path="res://fonts/firasans-book-16.fnt" type="Font"></ext_resource>
> -       <ext_resource path="res://scripts/controls.gd" type="Script"></ext_resource>
> -       <ext_resource path="res://sprites/icons/arrow-up.png" type="Texture"></ext_resource>
> -       <ext_resource path="res://sprites/icons/arrow-down.png" type="Texture"></ext_resource>
> -       <ext_resource path="res://sprites/icons/arrow-left.png" type="Texture"></ext_resource>
> -       <ext_resource path="res://sprites/icons/arrow-right.png" type="Texture"></ext_resource>
> -       <ext_resource path="res://sprites/pickups/bomb_increase.png" type="Texture"></ext_resource>
> +<resource_file type="PackedScene" subresource_count="11" version="2.0" version_name="Godot Engine v2.0.alpha.custom_build">
> +       <ext_resource path="res://scripts/menu.gd" type="Script" index="0"></ext_resource>
> +       <ext_resource path="res://sprites/icons/arrow-down.png" type="Texture" index="6"></ext_resource>
> +       <ext_resource path="res://background.png" type="Texture" index="1"></ext_resource>
> +       <ext_resource path="res://fonts/firasans-book-32.fnt" type="Font" index="2"></ext_resource>
> +       <ext_resource path="res://fonts/firasans-book-16.fnt" type="Font" index="3"></ext_resource>
> +       <ext_resource path="res://scripts/controls.gd" type="Script" index="4"></ext_resource>
> +       <ext_resource path="res://sprites/icons/arrow-right.png" type="Texture" index="8"></ext_resource>
> +       <ext_resource path="res://sprites/icons/arrow-up.png" type="Texture" index="5"></ext_resource>
> +       <ext_resource path="res://sprites/icons/arrow-left.png" type="Texture" index="7"></ext_resource>
> +       <ext_resource path="res://sprites/pickups/bomb_increase.png" type="Texture" index="9"></ext_resource>
>
> The ext_resource index seems to be well computed, and I guess the XML
> scene header should list ext_resource sorted by their index too. The
> current order does not seem really logical.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2495>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment]
This is still the case both in XML and TSCN formats. Here is an exemple from https://github.com/akien-mga/dynadungeons/blob/master/scenes/level.tscn:

```
[gd_scene load_steps=14 format=1]

[ext_resource path="res://scripts/level.gd" type="Script" id=1]
[ext_resource path="res://sprites/tileset.xml" type="TileSet" id=2]
[ext_resource path="res://sounds/explosion1.smp" type="Sample" id=6]
[ext_resource path="res://sounds/pickup.smp" type="Sample" id=8]
[ext_resource path="res://music/dynadingo.ogg" type="AudioStream" id=3]
[ext_resource path="res://sounds/explosion2.smp" type="Sample" id=7]
[ext_resource path="res://sounds/hahaha.smp" type="Sample" id=5]
[ext_resource path="res://sounds/push2.smp" type="Sample" id=10]
[ext_resource path="res://sounds/push1.smp" type="Sample" id=9]
[ext_resource path="res://sounds/iamback.smp" type="Sample" id=12]
[ext_resource path="res://sounds/bombdrop.smp" type="Sample" id=4]
[ext_resource path="res://sounds/yoohoo.smp" type="Sample" id=11]

[sub_resource type="SampleLibrary" id=1]

samples/bombdrop = { "db":0, "pitch":1, "sample":ExtResource( 4 ) }
samples/push1 = { "db":10, "pitch":1, "sample":ExtResource( 9 ) }
samples/respawn2 = { "db":-5, "pitch":1, "sample":ExtResource( 12 ) }
samples/push2 = { "db":10, "pitch":1, "sample":ExtResource( 10 ) }
samples/death = { "db":5, "pitch":1, "sample":ExtResource( 5 ) }
samples/pickup = { "db":0, "pitch":1, "sample":ExtResource( 8 ) }
samples/explosion1 = { "db":0, "pitch":1, "sample":ExtResource( 6 ) }
samples/explosion2 = { "db":0, "pitch":1, "sample":ExtResource( 7 ) }
samples/respawn1 = { "db":-3, "pitch":1, "sample":ExtResource( 11 ) }
```
