### ISSUE TITLE
Copy/Paste Animation is a reference, not a copy.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#24950]
**Godot version:**

3652442

**OS/device including version:**

Win10 64bit

**Issue description:**

I understand this is likely by design, and addressed and closed multiple times already.  However, this terminology is confusing and keeps catching me off guard still to date.  I'm in the mindset that a Copy will produce a copy, not a reference.

Is the primary use case really a reference?  It is hard to track these things as well since there isn't any obvious indicator what else it is linked with inside the project.  It is sensible and desirable when saving Animations as resources to be reused, though they're still hard to know the reach of it.

We mainly use this feature to copy an animation to quickly move tracks into other AnimationPlayers to save efforts.  Then after some modification, and potentially saving, the damage is discovered.

Not the worst if your project is version controlled, but just messing about in small projects, you can quite easily do some destructive work.

The current work flow to do this is:
1. Copy Animation
2. Paste Animation
3. Remember to Duplicate it.
4. Delete the first.
5. Rename the duplicate.

I'm not sure what language would be preferred, but perhaps it would be a usability improvement (especially for newcomers) to have two copy or two paste options.  Each with explicit language about the outcome.

Copy Animation
Copy Animation Resource
Paste

or 

Paste
Paste Animation Resource

Maybe someone else has better ideas.

**Steps to reproduce:**

Copy and Paste animation into another AnimationPlayer and modify the tracks.

![image](https://user-images.githubusercontent.com/13004169/51076218-3a48bc80-169e-11e9-9f0e-f520d7137494.png)

**Comment by eon-s** [comment]
Maybe "Paste as duplicate" for every Resource, with a keyboard shortcut too.

**Comment by samdze** [comment]
I totally agree, I've gone through several destructive situations while editing animations.

There surely is the need to display the resource path of the animation resource too when is edited in the Animation Editor to know the origin of everyone of them and be sure it is a specific one saved on the file system or built-in.

**Comment by golddotasksquestions** [comment]
Yes, please change this naming! I too have destroyed work because of it and it caught me off guard as well, so much so I would rather not use this functionality at all because it is so counter intuitive. I'd so much rather have a true "copy&paste" and also have it named as such. Same goes for "Paste/Paste Animation Resource"

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/30197, which has more information about the issue at hand.

**Comment by BloomAutist47** [comment]
would be cool to rename `Copy` into `Copy as Reference` so it will never get confused
