### ISSUE TITLE
c# - inner class - Failed to determine namespace and class for script

### ISSUE THREAD

**Issue by TypeOverride** [godotengine/godot#24958]
**Godot version:**
3.1alpha.mono.official (alpha5 mono win64)

**OS/device including version:**
Windows 7 64 bit

**Issue description:**
Compiler-Problems on:
```
public class A<T> {
    public class B {

    }
}

public class Test : A<int>.B 
{
    
}
```

> Error:
> Parse Error: Unecxpected token: .
> Failed to determine namespace and class for script: res://Test.cs

So it has a problem with:
```
.B 
```
**!!!!** but only when the outter class is a template class **!!!!**

**Minimal reproduction project:**
[csharpinnerclass.zip](https://github.com/godotengine/godot/files/2752698/csharpinnerclass.zip)

**Comment by NathanWarden** [comment]
I can also confirm this issue in Beta 1 on Linux. MonoDevelop works, msbuild works, Godot throws a build exception.

**Comment by akien-mga** [comment]
Confirmed in 3.1 beta 6 on Linux.
