### ISSUE TITLE
Failed to parse AndroidManifest.xml on custom built templates if not running gradlew clean before build

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#24966]
**Godot version:**
Godot 3.1 Beta

**OS/device including version:**
Windows 10

**Issue description:**
Error on exporting android game: 
adb: failed to install C:\Users\user\AppData\Local\Temp/Godot/tmpexport.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1980788101.tmp/base.apk: AndroidManifest.xml]

**Steps to reproduce:**
Create project, export to mobile with one click or export window

**Minimal reproduction project:**
Export new project

I use custom build template for export, i have used this command to create it:
scons -j8 p=android target=release/release_debug  tools=no disable_3d=yes
no error in scons compilation, no error for gradlew build compilation too.
In Editor settings in adroid tab i have all set correctly.

**UPDATE:** if i export to android old project for example 2d platform demo the android compilation work as expected, the problem is only with new project created with the 3.1 version

**Comment by akien-mga** [comment]
If you build custom templates, you need to build the editor too from the same commit, otherwise they might not be compatible.

**Comment by grevius5** [comment]
> If you build custom templates, you need to build the editor too from the same commit, otherwise they might not be compatible.

i build the editor as well from the same commit with:
scons p=windows

**Comment by hpvb** [comment]
Did you do a debug or a release export? If you do a release export without setting a release keychain on the export you will get an error like that when installing on an android device.

**Comment by CoreBeacon** [comment]
Have the same Error with the beta 1 and the export templates for the beta (no mono)

**Comment by hpvb** [comment]
I'm a little confused now, does this happen with the official templates as well as self-built ones or only on self-built ones?

**Comment by grevius5** [comment]
I've tryied with official beta godot edito and official templates and i have the same error. So same error with custom edito/templates and for official beta 1 editor/templates

**Comment by grevius5** [comment]
I found the error, before the gradlew build I have to do a gradlew clean in order to make my export templates to work

**Comment by akien-mga** [comment]
So IIUC, the error only happens if you built custom templates yourself, and then build them again without cleaning the build objects with `gradlew clean` beforehand?

**Comment by grevius5** [comment]
> So IIUC, the error only happens if you built custom templates yourself, and then build them again without cleaning the build objects with `gradlew clean` beforehand?

yes, I have this error only on windows, not on Linux

**Comment by akien-mga** [comment]
There hasn't been new reports about this so it seems it has been fixed.
