### ISSUE TITLE
Text rendered badly when same font resource used in Autoload.

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#24963]
**Godot version:**

Godot 3.1 Beta 1 (GLES3)

**OS/device including version:**

Windows 10 Pro

**Issue description:**
The text is rendered badly (maybe not oversampled?) when the same font resource used in the Autoload. Furthermore, if you make a new Dynamic Font with the same font file(.ttf) and size it also happen, to test it in the step 2 below instead of assigning TextTest.tscn make new DynamicFont with size = 33 and using the Fonts/Sylfaen.ttf

**Steps to reproduce:**
1. Open the project below and run it. The text rendered normally.
2. Open scene SingletonTest.tscn, assign custom_fonts/font property to font resource at res://Fonts/TextTest.tres, and save the scene.
3. Run the project again, notice that the first and second text is now rendered badly (maybe not oversampled?)

**Minimal reproduction project:**

[TextTest.zip](https://github.com/godotengine/godot/files/2752903/TextTest.zip)

**Comment by KoBeWi** [comment]
Seems fine in 3.1 stable
