### ISSUE TITLE
Godot Engine Editor  has stopped working (Switching from GLES3 to GLES2)

### ISSUE THREAD

**Issue by Vikram1323** [godotengine/godot#24962]
Godot version:
3.1 beta

OS/device including version:
Windows 7 SP1 64 bit, Dell Inspiron 1464, ATI Radeon Mobility 4300 HD.

Issue description:
After switching from GLES3 to GLES2 in a new project. 
Message box on splash screen will appear saying "Godot engine has stopped working"
"Windows is checking for a solution to the problem..."
Then debug or close program button will appear.
Click on debug will open Godot_v3.1-beta1_win64 inside Visual Studio saying atio6axx.pbd not loaded.
Click on close program closes the program.
Opening the project again does the same thing.

Steps to reproduce:
Create a new project. 
Switch from GLES3 to GLES2.
Click Save & Restart.  

Minimal reproduction project:
Create a new project.

Workaround:
Open project.godot in a text editor.
Then remove
[rendering]
quality/driver/driver_name="GLES2"
environment/default_environment="res://default_env.tres"
Save project.godot.
Open the project again.

**Comment by akien-mga** [comment]
It's the same as #21551.
