### ISSUE TITLE
Could Not Open Config File(GodotSharp)

### ISSUE THREAD

**Issue by SeaKarp** [godotengine/godot#24960]
**Godot version:**

Godot v3.0.6 stable_mono_win64

**OS/device including version:**

(I'm poor so don't judge)
Windows 10
Acer Aspire 1
Intel Celeron Quad Core Processor N3450
Intel HD Graphics
4GB DDR3 L Memory
eMMC 32GB

**Issue description:**

Whenever I open the IDE or a project this appears:
```
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 500
Mono: Initializing module...
Mono: Runtime initialized
Mono: INITIALIZED
ERROR: open: C:\Users/tehcg/AppData/Roaming/Godot/editor_settings-3.tres:1 - Parse Error:
   At: scene/resources/scene_format_text.cpp:838
ERROR: Failed loading resource: C:\Users/tehcg/AppData/Roaming/Godot/editor_settings-3.tres
   At: core/io/resource_loader.cpp:186
WARNING: create: Could not open config file.
     At: editor/editor_settings.cpp:838
ERROR: store_buffer: Condition ' fwrite(p_src, 1, p_length, f) != p_length ' is true.
   At: drivers/windows/file_access_windows.cpp:255
ERROR: store_buffer: Condition ' fwrite(p_src, 1, p_length, f) != p_length ' is true.
   At: drivers/windows/file_access_windows.cpp:255
```

**Steps to reproduce:**
I don't know if installing other console application libraries(like websocket-sharp) does that, but that error might be because of that.

**Minimal reproduction project:**

[SandGame.zip](https://github.com/godotengine/godot/files/2752770/SandGame.zip)

It looks like my default_env.tres was corrupt. For some reason the files of my project keep getting corrupt at random. I don't know why, but my default scene also was corrupt after I saved and quit Godot. Please someone tell me why it's corrupting my game.

Another error:
```
ERROR: recognize: res://default_env.tres:1 - Parse Error:
   At: scene/resources/scene_format_text.cpp:1185
```

**Comment by akien-mga** [comment]
Don't worry, we have no reason to "judge your computer". We need to know about it to see if a problem can be system-specific, not to mock people...

That being said, this kind of file corruption does look like a problem with your hardware, probably your disk showing signs of failure. I would advise making a backup of your files.

**Comment by SeaKarp** [comment]
I did before that I think all I have to do is replace the corrupted default_env.tres with the old backed up one that I have.

**Comment by SeaKarp** [comment]
Reason this was closed: Hard Drive error.

**Comment by SeaKarp** [comment]
I just realized my backup also has the corrupted default_env.tres so I need to make a new one. Does anyone know how?

**Comment by akien-mga** [comment]
You can simply delete it, it will be re-created when you need it.

**Comment by SeaKarp** [comment]
Thanks.
