### ISSUE TITLE
Gridmap mesh previews don't work due to MeshLibrary export issue

### ISSUE THREAD

**Issue by aqnuep** [godotengine/godot#24971]
**Godot version:**
Godot master 1ff170e67f0044b0a9f42fc936f09847c5ec4127

**OS/device including version:**
Win7/Radeon7870

**Issue description:**
The mesh previews aren't working when adding a MeshLibrary to a Gridmap as shown below:

![gridmappreviewwrong](https://user-images.githubusercontent.com/33791085/51089052-24eb9500-1767-11e9-95b1-9e458179ae97.jpg)

The reason for it is that the export of the MeshLibrary seem to not work correctly, as while the actual preview image data is exported:

````
[sub_resource type="Image" id=2]

data = {
"data": PoolByteArray( ... ),
"format": "RGBAHalf",
"height": 64,
"mipmaps": false,
"width": 64
}
````

The `ImageTexture` subresource has a null image reference:

````
[sub_resource type="ImageTexture" id=3]

image = null
size = Vector2( 64, 64 )
````

I've messed around in the debugger to try to root cause it and while I found what's the problem, I'm not yet familiar enough with the source code to propose a solution.

The problem seems to be that the `RES` handle referencing the `Image` object that is stored into `ResourceFormatSaverTextInstance::internal_resources` is a different one than the `RES` handle which is used to compare it against in `ResourceFormatSaverTextInstance::_write_resource`, even though the actual `Image` object they refer to is the same (the image data object of the preview).

I verified this is the only cause of the problem by manually overriding the lookup in `internal_resources` to succeed, which resulted in the correct data exported to the MeshLibrary file:

````
[sub_resource type="ImageTexture" id=3]

image = SubResource( 2 )
size = Vector2( 64, 64 )
````

And obviously then the preview image correctly shows up when I use the exported MeshLibrary in a Gridmap:

![gridmappreviewcorrect](https://user-images.githubusercontent.com/33791085/51089152-cd4e2900-1768-11e9-9b8e-16d9237fe37e.jpg)

Again, unfortunately, I didn't yet figure out how and why two `RES` references to the same `Image` object can exist, whether that's expected, and if yes, why the `internal_resources` map uses that as a key, but hopefully this is enough information for someone to figure out the underlying problem.

I've also tried exporting the MeshLibrary in binary form but that makes no difference.

**Steps to reproduce:**
1. Create a scene with at least one object
2. Convert the scene to a mesh library
3. Create a 3D scene and add a Gridmap node to it
4. Load the MeshLibrary into the Gridmap
5. Observe the lack of preview images

**Minimal reproduction project:**
[GridmapPreviewBug.zip](https://github.com/godotengine/godot/files/2753357/GridmapPreviewBug.zip)
- box.tscn - scene the MeshLibrary is exported from
- meshlibrary.tres - incorrectly exported MeshLibrary
- gridmap.tscn - scene using the MeshLibrary in a Gridmap node

**Comment by aqnuep** [comment]
Forgot to mention that the issue of not being able to match the `RES` handle with the one in `internal_resources` also results in the following error output:

````
Resource was not pre cached for the resource section, bug?
````

**Comment by Toshiwoz** [comment]
I have the same issue, I just noticed that when you create the GridMap's MeshLibrary is recently created it works fine, you can see the preview, but if I close the project and reopen, it doesn't.

**Comment by reduz** [comment]
closed via 24971

**Comment by Toshiwoz** [comment]
I just tested with latest code, now when I update the library it crashes.
As the window closes too fast, and it seems it does not log into any file I can't paste it here.

**Comment by aqnuep** [comment]
There's a small bug in the fix from @reduz, we already discussed it with him. I'll post a PR fixing it tomorrow.

**Comment by aqnuep** [comment]
PR #25335 should solve the outstanding issues with this one.
