### ISSUE TITLE
Dictonaries with named enum values as keys do not work

### ISSUE THREAD

**Issue by th1z** [godotengine/godot#24978]
**Godot version:**
master branch

**OS/device including version:**
Windows x64

**Issue description:**
Dictonaries can not be accessed with named enum values as keys
See example below

**Steps to reproduce:**

Have one class with the following:
```gdscript
class_name ClassOne

enum MY_ENUM { ONE, TWO }
const MAP_SIZE_DICT := {
	MY_ENUM.ONE: Vector2(1, 0),
	MY_ENUM.TWO : Vector2(2, 0),
}
```

In another class, try the following:
```gdscript
class_name ClassTwo

var keys = ClassOne.MY_ENUM.keys()
for key in keys:
	ClassOne.MY_ENUM.has(key) # prints "false"
```

`ClassOne.MY_ENUM[key]` and `ClassOne.MY_ENUM.get(key)` will fail as well

**Comment by bojidar-bg** [comment]
`MY_ENUM.ONE` would be `0` in this case.
`ClassOne.MY_ENUM.keys()` would be `["ONE", "TWO"]`.
You probably meant `ClassOne.MY_ENUM.values()` instead?

**Comment by th1z** [comment]
So ".keys()" returns a list of the names of the keys and not a list of their values?

**Comment by th1z** [comment]
@bojidar-bg: Yes, thank you. I was confused and did not expect the enum to behave like a dictonary. Makes sense now.
