### ISSUE TITLE
Tag for objects.

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#24973]
Have tags for objects.
Nodes could be tagged "obstacle", "floor", "water",  "character", "item" or anything.

Advantages : 
- Objects does not need a script to have a tag
- This helps game design, objects are defined at level design
- This helps game logic to recognize objects that does not have a script
- You don't need to add a tag property to each scripts

**Comment by KoBeWi** [comment]
But we already have groups...

**Comment by Ace-Dragon** [comment]
This could be partially worked towards if Godot gives us the ability to declare group names that are global for the game (ie. giving us a list of predefined groups to choose from in the group UI).

Even now though, 3.1 will allow the export of enums which can give you something similar to tags with a simple two line script. There are functions you can use to check if a given object has a property with a certain value.

**Comment by CowThing** [comment]
Yeah groups already serve this purpose I think. Although they only work on objects that derive from Node. There is also a pull request for global groups #24262 which will make it easier to keep groups organized.

**Comment by Chaosus** [comment]
Besides the groups you can also use set_meta("tag", tag) to achive same result..

**Comment by akien-mga** [comment]
What's described here is clearly groups, which offer a tag system, so I don't think anything else needs to be implemented.
