### ISSUE TITLE
Tilemap editor draws lines

### ISSUE THREAD

**Issue by martys71** [godotengine/godot#24970]
**Godot version:** 3.1 beta 1 

**OS/device including version:** Windows 10 x64

**Issue description:**

When putting a tile in the tilemap editor, the editor draws a line of tiles.

https://ibb.co/p4ZY6S4

**Steps to reproduce:**

Open a window of a different program on the side of Godot Editor. With the Tilemap Editor opened and a tile selected, click that window, then click your canvas to put the tile. 
**Minimal reproduction project:**

**Comment by Sslaxx** [comment]
Umm, this doesn't tell anyone anything. Could you please elaborate?

**Comment by martys71** [comment]
> 
> 
> Umm, this doesn't tell anyone anything. Could you please elaborate?

Sorry, pressed ENTER too early. Have to learn this interface.

**Comment by MarianoGnu** [comment]
this happens with the line tool, are you holding Shift?

**Comment by martys71** [comment]
> 
> 
> this happens with the line tool, are you holding Shift?

Nope

**Comment by bojidar-bg** [comment]
I think the problem might be comming from this piece of code:
https://github.com/godotengine/godot/blob/7c8fbd892c827abae464fad2c427ca2bd17ff3f8/editor/plugins/tile_map_editor_plugin.cpp#L1193-L1212

Can't reproduce unless I hold the mouse pressed as I Alt-Tab. Maybe it behaves differently on Windows.

I guess we should just switch away from TOOL_PAINTING if the window is unfocused.

**Comment by KoBeWi** [comment]
Still valid in 05395cb
