### ISSUE TITLE
The TextureButton stay in the "Pressed" state.

### ISSUE THREAD

**Issue by djole1973** [godotengine/godot#24983]
**Godot version:**
Godot_3.1-master(always reproducible)
Godot_v3.0.6-stable_x11.64

**OS/device including version:**
Distributor ID: LinuxMint
Description:    Linux Mint 18.3 Sylvia
Release:        18.3
Codename:       sylvia

Additional hardware specification:
Using touch device: Virtual core pointer(single finger)

Relevant project settings:
Emulate Touchescreen = TRUE
Emulate Mouse From Touche = TRUE

**Issue description:**
The TextureButton stay in the "Pressed" state.

**Steps to reproduce:**
1) It's only reproducible(but not always) when the focus changed from another application to the Godot. The TextureButton must be pressed first.
2) On the similar environment: When _evtest_ is running in background, the button does not seem to get stuck on first press

**Minimal reproduction project:**

Minimal example [code.txt](https://github.com/godotengine/godot/files/2759798/code.txt), and  $PlayButton is texture button.

Output of the [evtest.txt](https://github.com/godotengine/godot/files/2755182/evtest.txt). The log dos not reflect result of the test run(shown below), but the issue was reproduced.

Event: time 1547460005.155603, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0
**Event: time 1547460035.342150, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 1** Button stay in the pressed state.

Event: time 1547460042.871819, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 1
Event: time 1547460043.004811, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0 here is button in the correct state.

`
----------------ERROR test run-------------
_input 					InputEventMouseButton pressed= True button_index = 1 position = (1769.478516, 2091.072266)
	_on_play_button_log = button_down
_input 					InputEventScreenTouch pressed= True index = 20 position = (1769.478516, 2091.072266)
**NOTIFICATION_WM_FOCUS_OUT**
_input 					InputEventMouseButton pressed= False button_index = 1 position = (1769.478516, 2091.072266)
**_unhandled_input 		InputEventMouseButton pressed= False button_index = 1 position = (1769.478516, 2091.072266)**
_input 					InputEventScreenTouch pressed= False index = 20 position = (1769.478516, 2091.072266)
_unhandled_input 		InputEventScreenTouch pressed= False index = 20 position = (1769.478516, 2091.072266)

----------------OK test run-------------
_input 					InputEventMouseButton pressed= True button_index = 1 position = (1773.145996, 2066.603027)
	_on_play_button_log = button_down
_input 					InputEventScreenTouch pressed= True index = 22 position = (1773.145996, 2066.603027)
_input 					InputEventMouseButton pressed= False button_index = 1 position = (1773.145996, 2066.603027)
	_on_play_button_log = button_up
_input 					InputEventScreenTouch pressed= False index = 22 position = (1773.145996, 2066.603027)
_unhandled_input 		InputEventScreenTouch pressed= False index = 22 position = (1773.145996, 2066.603027)
`

**Comment by djole1973** [comment]
Analyze:
Branch: master
File: 
- scene\main\viewport.cpp , line 1836  exit function and the input event is not handled

**Comment by Calinou** [comment]
@djole1973 Can you still reproduce this on [Godot 3.2 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4)?

**Comment by djole1973** [comment]
@Calinou  I do not have environment  to check issue again. sorry.

**Comment by Calinou** [comment]
I'll close this issue as nobody else has been able to reproduce it recently. If anyone can still reproduce this bug, please comment and attach a minimal reproduction project.
