### ISSUE TITLE
Project crashes when keeping the same directory name

### ISSUE THREAD

**Issue by Bombfuse** [godotengine/godot#24989]
**Godot version:**
Mono 3.1 Beta

**OS/device including version:**
MacOS Mojave

**Issue description:**
My project crashed once due to a normal reason, now every time I build it, it crashes again. However, if I rename the directory of the project, it works properly, until it crashes due to a normal crash reason. Then I must rename the project directory again.

Example: Renaming project "Game" to "GameRenamed" causes Godot to stop crashing on build.

Native Stacktrace
![image](https://user-images.githubusercontent.com/26308406/51133031-b3542b00-17e8-11e9-9cba-20e084bef137.png)

Godot report log
[1547491005.txt](https://github.com/godotengine/godot/files/2756606/1547491005.txt)

MacOs Problem Report
[mac_os_problem_report.pdf](https://github.com/godotengine/godot/files/2756609/mac_os_problem_report.pdf)

**Steps to reproduce:**
Genuinely unsure how to reproduce, but I'll try some things and post if I can find a way.

**Comment by Bombfuse** [comment]
Project in question
[terra.zip](https://github.com/godotengine/godot/files/2756643/terra.zip)

**Comment by aaronfranke** [comment]
Try deleting `.import/`

**Comment by Bombfuse** [comment]
Deleting ```.import/``` and/or recloning the repository seems to have fixed the issue for now.
