### ISSUE TITLE
can't read s/artoolkitX for Unity Version (([0-9]+\.[0-9]+)(\.[0-9]+)?(r[0-9]+)?)/artoolkitX for Unity Version 1.0.2/: No such file or directory error

### ISSUE THREAD

**Issue by bhavin2707** [godotengine/godot#24980]
I am trying to extract package from the git file i downloaded but i am getting this weird error and really not sure what is it? Please if someone can help me to solve this error and help me extract unity package from git source of AR Unity X. Image for error [https://drive.google.com/open?id=18Bt-wCRX9gVqiP9rhVn2TYrqfPuXbM5C](url)

**Comment by groud** [comment]
Sorry, but this seems unrelated to Godot. 
This place is to request features or report bugs on the Godot game engine, not to ask questions about how to unpack unity related stuff.

**Comment by bhavin2707** [comment]
OMG! I am extremely sorry. I didn't realize that I posted it on wrong
forum.
Both the git pages of both engines were opened and maybe mistakenly I wrote
in wrong tab. I am extremely sorry. This won't happen again.

**Comment by groud** [comment]
No problem, I was quite surprised too ^^
