### ISSUE TITLE
Scroll wheel does not scroll UI controls if the mouse cursor is near the bottom of these controls.

### ISSUE THREAD

**Issue by Niriel** [godotengine/godot#2498]
I'm having that issue with Windows 8 64 bits, Godot Engine v1.1.stable.d3b42e41b0.  This happens both in game and in the editor, which is reassuring.

Scrollable areas do not react to the scroll wheel when the cursor is within 30ish pixels of the bottom of these areas.  Left or right clicks work (tested with TextEdit, Trees and all) but scrolling does not.  I circled these strange regions in red on the following screenshot.

![godot_scroll_bug](https://cloud.githubusercontent.com/assets/1502/9982890/6fcd3330-5feb-11e5-8df0-c3b9cc56e2e2.png)

**Comment by akien-mga** [comment]
It does not seem to affect Linux X11 (64bit), all editor scrollable areas seem to work fine with both Godot 1.1stable and the current master branch.

**Comment by Niriel** [comment]
Interesting.  I will try on my girlfriend's laptop when she's back.

**Comment by Niriel** [comment]
I could reproduce the problem on a Windows 10 64 bits laptop.

**Comment by akien-mga** [comment]
Could you provide a test project that exhibits this issue, so that it can be easily reproduced?
