### ISSUE TITLE
Editor is very laggy using Intel integrated card

### ISSUE THREAD

**Issue by Machalord** [godotengine/godot#24982]
**Godot version:**
3.1 alpha 1 to beta 1

**OS/device including version:**
Windows 7 64 bits 
Intel HD 3000 lastest driver from page, versión 15.28.24.4229 (9.17.10.4229) 

**Issue description:**
When the editor is redrawing the cpu goes from 0 to 25-30% and the whole editor is laggy but testing the game work fine so only the editor is affected   

**Steps to reproduce:**
Just start godot and open/create new empty project

**Comment by hpvb** [comment]
Can you try switching to the GLES2 renderer to see if that's better for your GPU?

**Comment by Machalord** [comment]
im already using GLES2 becasue i cant use GLES3 at least on windows i dont know if in others OS this card have support for GLES3

**Comment by OBKF** [comment]
I think #24705 is a part of this too. the editor lags often and CPU usage goes crazy when using some parts like the AnimationTree but the game runs great. (Using Linux here)

**Comment by Machalord** [comment]
Fixed with the lastest 3.1.1 stable.
