### ISSUE TITLE
Clarify the SRGB -> Linear conversion in shaders (currently hint_albedo)

### ISSUE THREAD

**Issue by kb173** [godotengine/godot#24992]
I have recently lost about an hour trying to figure out why my textures had incorrect colors in shaders, and I seem not to be the only one confused by this (#11381, https://godotdevelopers.org/forum/discussion/19049/custom-splatmap-shader-does-not-work-correctly-in-3-0-solved).

The solution for a correct conversion from SRGB to linear was this:

```
uniform sampler2D tex : hint_albedo;
```

This is, in my opinion, not the right place to specify this. The prefix `hint_` points as this being, well, a hint. Just something for the editor; irrelevant when only talking to the shader in GDScript.

Image import settings have several options regarding SRGB - why does it even need to be done again in the shader or material? It's not very intuitive for something that should be basic and clear to all users.
At the very least, the `hint_` prefix should be removed from hints which have more ramifications, and are even required in some cases.

**Comment by clayjohn** [comment]
Shaders perform their operations in linear space. If you want to keep your texture in sRGB then it will have to be converted to linear in the shader. In Godot, the default workflow is that albedo textures will be in sRGB while other textures will not. This is generally a good assumption, however, it requires that users specify when the texture is an albedo texture (i.e. by using a hint).

The alternative to this is that users would have to convert all their textures to linear when importing into Godot.

As for documentation, this is explained in the [Shading Reference](http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#uniforms) document under the section 'Uniforms'.

**Comment by kb173** [comment]
Oh, I didn't notice that merge until now. Thank you @rainlizard! That definitely makes it better.

I'd still suggest renaming the sampler2D `hint_`s to something else for 4.0 though. As @rainlizard mentioned, it makes it sound like an optional editor hint (which is true for others, such as `hint_color`), not something with significant visual ramifications.

**Comment by akien-mga** [comment]
Closing as the docs have been improved with https://github.com/godotengine/godot-docs/pull/2925.

> I'd still suggest renaming the sampler2D `hint_`s to something else for 4.0 though. As @rainlizard mentioned, it makes it sound like an optional editor hint (which is true for others, such as `hint_color`), not something with significant visual ramifications.

About this, @reduz says:

```
14:31 <reduz> Akien: its a hint to the engine how to treat the shader. It does not change how the shader generates code.
14:32 <reduz> Akien: you tell the engine what this uniform is supposed to be, and the engine will do stuff accordingly
```

It's similar to type hints which tell GDScript (and the Inspector for exported variables) how to handle variables. So in that sense the `hint_*` prefix is correct.

**Comment by kb173** [comment]
I see. With the similarity to GDScript's type hints, I still feel like something like this would be clearer and more consistent:

```
uniform sampler2D tex : albedo;
```

But I understand if you think keeping the `hint_` prefix is preferable, it does make sense. Thanks for taking care of it @akien-mga and @rainlizard!

**Comment by itsybitesyspider** [comment]
I also wasted over an hour due to this, today, even after the documentation updates. While in *retrospect* it might feel sensible that the term "albedo" would imply a role for color correction, I would have been properly alerted by a precise keyword such as "sRGB" "gamma" or "linear".

**Comment by Calinou** [comment]
> While in *retrospect* it might feel sensible that the term "albedo" would imply a role for color correction, I would have been properly alerted by a precise keyword such as "sRGB" "gamma" or "linear".

Changing this would break compatibility, so this needs to be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.

**Comment by rainlizard** [comment]
I will support any proposal that makes it clearer. There will inevitably be more people like myself and itsybitesyspider who fall into this trap and lose a hour or more of their time. Or they'll walk away thinking Godot is buggy because the image doesn't look right.

The word "hint" just doesn't cut it.

**Comment by kb173** [comment]
Since people are still (understandably, in my opinion) confused by this, even though the improved docs already helped, I opened up a proposal for a name change: https://github.com/godotengine/godot-proposals/issues/2323
