### ISSUE TITLE
GLES3 traffic jams waiting, GLES2 breaks the project.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#24994]
Godot_v3.1-beta1_win64.exe

ОС: Windows 7 x64
Radeon HD 3650

**Issue description:**
When I run an empty project in GLES3 mode and start working in 2D space and the script editor, everything works fast enough, and after saving and opening the project, everything is relatively normal (if you do not take into account the wrong texture color modulation), but if I try to just switch to 3D editor, the window freezes for almost 1.5 minutes, and after that it launches the empty space of the 3D editor.
Further switching between 3D and 2D space works almost instantly, until I close the editor completely. And the next time you open the project, the wait is repeated again.
If I, in 3D space of an empty scene, add some kind of 3D node, for example, if it is the simplest primitive, or even the Spatial node, then it will take about 2.5 more minutes of waiting, if I want to create a new mesh material, then make it wait 1.5 more minutes, and such a nightmare occurs with almost every new operation.
If such a project, with this scene saved and then again try to open, then waiting for the completion of this operation will require all the time spent on all previously performed operations combined.
If I try to switch to GLES2 mode. Then the editor will ask to save and reload the project, after reloading the project it is no longer possible to open under any circumstances, and there are no obvious ways to switch the mode back to GLES3.

It just kills me, what should I do?

**Comment by OBKF** [comment]
@OlexiyKravchuk  
>  Then the editor will ask to save and reload the project, after reloading the project it is no longer possible to open under any circumstances, and there are no obvious ways to switch the mode back to GLES3.
>
You can go back to the GLES3 by editing the project.godot file.
>  Yes, there is a similarity, but I'm not sure, because as far as I understand there were problems on Linux, but I have Windows 7. 
And in my case, for some reason, GLES2 refuses to work at all.
>
The GLES2 does not work well(yet) on windows in my personal experience.
> While 2.1.5 and all older versions worked well.
>
The 2.1.5 is the goto if you really need GLES2 (in my opinion).

**Comment by OlexiyKravchuk** [comment]
@OBKF

> 2.1.5 - это goto, если вам действительно нужен GLES2 (на мой взгляд).

I need not GLES2. I need the capabilities of Godot 3.1, which are missing in the previous versions, and now do not work satisfactorily in the GLES3 mode on my hardware.

**Comment by OBKF** [comment]
You need to make compromises VERY HIGH-END technology requires a VERY HIGH-END hardware.
I am sure that you can make a good looking game using Godot 3.1 with GLES2 (if you managed to make it work).
Try using an updated build from [here](https://hugo.pro/projects/godot-builds/)  (if you can't build it yourself), It gets better everyday.

**Comment by starry-abyss** [comment]
GLES2 works out of the box for me on Windows. As it's already feature-complete, it receives only bug fixes.
Freezes on GLES3 are known (#13954), but 1.5 minutes?? O_o

**Comment by avril-gh** [comment]
> As it's already feature-complete, it receives only bug fixes.

Does that meant, no bloom, glow or other stuff like this on WorldEnvironment ?

**Comment by starry-abyss** [comment]
Yes, source: https://twitter.com/reduzio/status/1044443056219607040

**Comment by clayjohn** [comment]
Is this still reproducible in master? If so, have you tried updating your GPU drivers?

**Comment by OlexiyKravchuk** [comment]
In 3.1 stable, when using GLES 3, nothing has changed. And GLES2 finally runs, but unfortunately it takes a long time when the project is launched and any scene in it for debugging.

**Comment by clayjohn** [comment]
Did you update your GPU drivers?

**Comment by OlexiyKravchuk** [comment]
of course.

**Comment by raymoo** [comment]
>You need to make compromises VERY HIGH-END technology requires a VERY HIGH-END hardware.

The GLES3 renderer doesn't require "VERY HIGH-END" graphics hardware. It runs both on my laptop with ivybridge (Intel) integrated graphics and on my desktop with a GTX 750 Ti, both a few years old and not very high-range. I believe though that Intel's Linux drivers for older integrated GPUs support more recent features than the Windows drivers.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by OlexiyKravchuk** [comment]
I now have Godot 3.2.3 when I work with GLES2 without creating a WorldEnvironment it works relatively bearable, GLES3 is still not suitable under any circumstances, both with WorldEnvironment and without it in the scene.

**Comment by clayjohn** [comment]
Thanks for the update! I'm glad to hear that 3.2.3 is working for you (even if it is slow).

I'm going to close this now that GLES2 is working much better. Unfortunately there is not much we can do. Your graphics card is 12 years old and windows 7 is no longer updated by windows. 

The GLES3 backend was not meant for such old hardware (that's why we added GLES2) so there is really no hope for anything to change to make it run better for you.
