### ISSUE TITLE
queue_free() on a node attribute removes the instance of the node and not the attribute

### ISSUE THREAD

**Issue by Nogal** [godotengine/godot#24998]
**Godot version:**

3.0.6

**OS/device including version:**

Not graphics related.
GTX 1070ti

**Issue description:**

What Occurred:
    Loaded instance of a scene with a Node 2D and two Area2Ds. Each Area2D has a signal to a script upon collision with a certain area to queue_free(), however both Area2Ds are freed rather than the target Area2D

Expected:
    Only the referenced Area2D be cleared 

**Steps to reproduce:**
Run attached Godot project, relevant scripts are level1.tscn player_ship.tscn and stage2_projectile.tscn

Acquire a blue powerup, fire at an enemy using only the left or right projectile. Both left and right projectiles are destroyed rather than only the colliding projectile.

**Minimal reproduction project:**

[spaceshooter.tar.gz](https://github.com/godotengine/godot/files/2757892/spaceshooter.tar.gz)

**Comment by Tercus** [comment]
As can be seen in the screenshot, I can make the left projectile disappear, by accessing its subnodes and disabling the parts:
https://i.imgur.com/ILLXIZQ.png

I did that by using this:
```
func deal_damage(area, projectile):
	area.get_parent().get_hurt(damage)
	projectile.get_node("Sprite").visible = false
	projectile.get_node("CollisionShape2D").disabled = true
```

I tried calling `queue_free()` on every childnode separately, but that didn't work. It still deleted both projectiles.

My current guess is that you can't use `queue_free` inside of an instance.

**Comment by Nogal** [comment]
This was due to a queue_free() also existing on a visibilitynotifier which when removed also removed the parent node. Closing. This is a me error not a you error.
