### ISSUE TITLE
Calling a Method Created by a Dictionary in a Node Returns Null

### ISSUE THREAD

**Issue by SeaKarp** [godotengine/godot#25016]
**Godot version:**

Godot v3.0.6 stable_mono_win64

**OS/device including version:**

Windows 10
Acer Aspire 1
Intel Celeron Quad Core Processor N3450
Intel HD Graphics
4GB DDR3 L Memory
eMMC 32GB

**Issue description:**

When I call the obj method for a Node inside a group which contains Sprite(or any type of node) objects that I want to save it returns null. 
Can someone help?
Code:
```js
public override void _Ready()
    {
        // Called every time the node is added to the scene.
        // Initialization here
        var nodes = GetTree().GetNodesInGroup("thing");
        foreach(Sprite node in nodes)
        {
            var nodeData = node.Call("obj");
            GD.Print(JSON.Print(nodeData));
        }
    }

    public Dictionary<object, object> obj()
    {
        return new Dictionary<object, object>
        {
            { "Name", GetName()}
        };
    }
```

An example of this is also found here in the second block of code: https://docs.godotengine.org/en/3.0/tutorials/io/saving_games.html

**P.S.** I know that the code is a bit messy. I'm a noob to C#.

**Steps to reproduce:**
Create a Dictionary<object,object>, put some variables inside of it, instance nodes that are in a group, in a foreach() loop iterate through the nodes and call the method name of the Dictionary, then see if it returns null.

**Minimal reproduction project:**

[Example.zip](https://github.com/godotengine/godot/files/2762440/Example.zip)

**Comment by akien-mga** [comment]
If you are looking for help, you should go to a support community channel like the Q&A, Discord or the Facebook group: http://godotengine.org/community

This issue tracker is for bug reports against the engine, not user support.
