### ISSUE TITLE
No signal received from AnimationPlayer with animation_finished...

### ISSUE THREAD

**Issue by Jackain** [godotengine/godot#25019]
**Godot version:**
3.1 Beta 1

**OS/device including version:**
W10 x64

**Issue description:**
Tried to connect animation_finished signal to a script with the editor and with GDscript but the function are never called when an animation finish.

**Steps to reproduce:**
Just create an AnimationPlayer with a simple animation and try to receive the animation_finished signal (animation_changed and animation_started too)

**Comment by Xrayez** [comment]
I couldn't reproduce it. The `animation_finished` signal never emits when "Animation Looping" is on though, but that's expected I guess. The `animation_started` signal works fine in loop mode.

**Comment by Jackain** [comment]
Sorry forgot to update, i made a mistake i was calling play() everyframe but now it's working fine :)
