### ISSUE TITLE
audioclips wont play in audioplayback track in animationplayer when loaded node in autoload

### ISSUE THREAD

**Issue by robertarnborg** [godotengine/godot#25020]
**Godot version:**
beta 1 3.1

**OS/device including version:**

**Issue description:**
I am trying to make a global musicplayer that can play animations with different music loops through the use of audio playback tracks. I loaded the Node2d scene, and now AudioStreamPlayer into autoload and am communicating via script to the musicplayer scene. However, the audioplayback tracks aren't playing back the streams. Plus when using regular play keyframes, instead of the new audioplayback tracks the audio starts and restarts at random instead of playing back the track.

**Steps to reproduce:**
call from script to play animation, however audiotracks not playing :(

**Minimal reproduction project:**
[MusicPlaybackBug.zip](https://github.com/godotengine/godot/files/2762671/MusicPlaybackBug.zip)

**Comment by rcorre** [comment]
I have a similar issue, though I don't think autoload matters.

1. Export a model with animations (I'm using godot-blender-exporter)
2. In the import settings, choose Animation.Storage=Files and Animation.KeepCustom=true
3. Inherit the scene
4. Add an `AudioStreamPlayer3D`
5. Add an "Audio Playback Track" to an animation
6. Set the animation to autoplay
7. Start the scene

The animation will play, but no sound will play. If I instead add a call method track to call `AudioStreamPlayer3D.play()`, it works.

[example.zip](https://github.com/godotengine/godot/files/3131151/example.zip)

Play the example, notice there is no sound. Then disable the audio track and enable the function call track and play again. The sound will play.

The sound used in the example is https://freesound.org/people/d00121058/sounds/390757/ (CC0).

**Comment by rcorre** [comment]
@robertarnborg  what do you mean by "regular play keyframes"?

**Comment by SolarLune** [comment]
Yo! 

Thank you very much, @rcorre, looks like I ran into the same issue. For me, it's when I attempt to play a sound using an Audio Playback track that the sound doesn't play. If I use the Call Method track to run `play()` on the AudioStreamPlayer, it plays the sound fine.

**Comment by rcorre** [comment]
Glad it helped, @SolarLune! It is worth noting the drawback to using the call method track is that it won't play in the editor, so you can't preview how the sound syncs with the animation.

**Comment by jitspoe** [comment]
I can't seem to get function calls or sounds to play when using an exported animation in 3.1.1.  If I add my own animation player node, they work, but that's not very helpful for syncing sounds to a character animation.

**Comment by neowoods** [comment]
Can anyone fix this bug? same problem here

**Comment by rcorre** [comment]
I just tested my scenario and it is now working in 3.2.2.
@robertarnborg I opened your example project and I noticed that your audio track started at a time before `0`. When I moved it up to `0` playing the animation in the editor played the music.

@jitspoe and @neowoods: can you elaborate on your problem? Also double-check this:

```
In the import settings, choose Animation.Storage=Files and Animation.KeepCustom=true
```

Otherwise any edits to an imported animation won't be saved.

**Comment by rcorre** [comment]
I suppose this could still be a bug, as if you pause the animation, drag the playhead to a different spot, and start it, the music will pick up at the right spot, but if the start of the stream is before 0 it will never play. Nice music BTW :)

**Comment by KoBeWi** [comment]
I checked the project from the OP and it plays fine. At least when you fix the audio clip which starts with negative time (it can't).
The second project has no stream set in the animation, so if it was imported like that, it's unrelated issue.

Looks to me like a wrong usage of audio tracks. Feel free to comment if you have a MRP with an actual engine bug.
