### ISSUE TITLE
Godot Mono does not rebuild project's .mono when out of sync

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#25047]
**Godot version:**

07e2046980c903268ef0d2f5a73caea77d511519 Mono

**OS/device including version:**

Ubuntu 18.10

**Issue description:**

When building Godot Mono, there are times when it's necessary to destroy and rebuild the project's `.mono` folder, otherwise random strange problems can occur:

https://github.com/godotengine/godot/issues/23598

In this particular instance, the editor was unable to read any of the project's folders or files, giving the impression that the project was entirely empty, while also showing these errors:

```
ERROR: flush: Condition ' flushing ' is true.
   At: core/message_queue.cpp:274.
ERROR: flush: Condition ' flushing ' is true.
   At: core/message_queue.cpp:274.
ERROR: flush: Condition ' flushing ' is true.
   At: core/message_queue.cpp:274.
ERROR: flush: Condition ' flushing ' is true.
   At: core/message_queue.cpp:274.
...
ERROR: task_step: Condition ' !tasks.has(p_task) ' is true. returned: cancelled
   At: editor/progress_dialog.cpp:204.
ERROR: end_task: Condition ' !tasks.has(p_task) ' is true.
   At: editor/progress_dialog.cpp:229.
ERROR: reload_scripts_domain: The loaded Editor API assembly is out of sync
```

Attempting to close Godot mono here would lead to a hang.

The solution, as it turns out, is to manually delete the `.mono` folder in the project, which allows Godot mono to rebuild it; after that, all problems went away.

Ideally, the editor would be able to detect when there are mismatches with the project's `.mono`, and automatically rebuild it when necessary.

**Steps to reproduce:**
1. Create a new project with Godot mono from a considerably older version of Godot mono; setup mono (create C# project etc.)
2. Try to open this project in a newer version of Godot mono; many things may go wrong, the results are seemingly random.

**Comment by neikeq** [comment]
I remember experiencing the same issue. Thankfully these recently added error messages will make debugging easier.
