### ISSUE TITLE
Fail to build Godot Sharp Solution

### ISSUE THREAD

**Issue by r-lodahl** [godotengine/godot#25043]
**Godot version:**
3.1 beta 1

**OS/device including version:**
Windows 10 64bit, Mono 5.12

**Issue description:**
When running Godot 31 Beta 1 Mono version and creating a script creation of the c# project is tried. It fails. Restarting the editor will result in another try which still fails but does not display this, creates a lot of error messages and destroys the lower UI (Output, Debugger, Audio etc).

Opening the project in alpha 5 works fine and compiles without errors.

Was a new dependency added?

**Steps to reproduce:**
Create a project, open it with Mono beta 1 and try to create a c# script file.

/edit: will try to add an minimal example project this evening.

**Comment by akien-mga** [comment]
CC @neikeq @hpvb

**Comment by r-lodahl** [comment]
**Example Project**
[CsharpBug.zip](https://github.com/godotengine/godot/files/2770091/CsharpBug.zip)

**Comment by r-lodahl** [comment]
Closed - either I was to dumb or the issue was fixed in beta 2.
