### ISSUE TITLE
Godot Crashes When using JSON.Print on a Dictionary Method

### ISSUE THREAD

**Issue by SeaKarp** [godotengine/godot#25048]
**Godot version**:
Godot v3.0.6 stable_mono_win64

**OS/device including version**:
Windows 10
Acer Aspire 1
Intel Celeron Quad Core Processor N3450
Intel HD Graphics
4GB DDR3 L Memory
eMMC 32GB

**Issue description:**

When I create a new Dictionary method, instance it, then use JSON.Print([Dictionary Method Here]); the game crashes.
Code:
```js
public Dictionary<object,object> Method()
{
    return new Dictionary<object,object>
    {
        { "ExampleString", "Example" },
        { "DummyInt", 0 }
    }
}

public override void _Ready()
{
    var instance = Method();
    JSON.Print(instance);
}
```

***Edit***: I forgot to mention that this error appears when I build the project.
Error:
![error](https://user-images.githubusercontent.com/46639237/51286217-0207ed80-19c0-11e9-9592-e1459635b3f4.PNG)

**Steps to reproduce:**
Create a new object dictionary method, add some variables to the object, instance the method, finally use JSON.Print([Instance Here]);.

**Minimal reproduction project:**

**Comment by SeaKarp** [comment]
If no one can help me make sure to explain why.

**Comment by neikeq** [comment]
Is it a `Godot.Collections.Dictionary` or `System.Collections.Generic.Dictionary`?

**Comment by akien-mga** [comment]
Seems to work fine in 3.1 beta 6 after editing a bit the example in the OP (it wouldn't compile without the added `;` and with `Dictionary`):
```
using Godot;
using System;

public class MyNode : Node
{
	public Godot.Collections.Dictionary<object,object> Method()
	{
	    return new Godot.Collections.Dictionary<object,object>
	    {
	        { "ExampleString", "Example" },
	        { "DummyInt", 0 }
	    };
	}
	
	public override void _Ready()
	{
	    var instance = Method();
	    GD.Print(JSON.Print(instance));
	}
}
```
prints:
```
{"ExampleString":"Example","DummyInt":0}
```
