### ISSUE TITLE
Not possible to create AnimationTree from scratch via gdscript

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#25056]
Sorry to bother you in busy pre-release days, happy New Year!

Well, current AnimationTree is working more or less. But when your animation assets size become huge you try to find some ways around that to still e able to manage assets. A good way to do this is via scripting, as Godot supports import scripts, also some things are useful at run time. But I found no way to create AnimationTree from scripts. Well, one can create AnimationTree node via AniationTree.new() but not root resource and subnodes. Please show me if I'm wrong, but it seems that now it is not possible to manipulate AnimationTree resources from scripts. I think that should be resolved somehow.

**Comment by groud** [comment]
It is totally possible to create everything via scripting: 
```
func _ready():
	var tree = AnimationTree.new()
	tree.tree_root =  AnimationRootNode.new()
	add_child(tree)

```

Please ask on the other [community channels](https://godotengine.org/community) beforehand when you are not sure about how to do something.

**Comment by slapin** [comment]
I hope Godot developers would be professional and not get as low as
degenerative trolling.

You can't create any useful AnimationTree which does anything via GDScript.

**Comment by groud** [comment]
> I hope Godot developers would be professional and not get as low as degenerative trolling.

I can insure you this is definitely not trolling. Please understand we have a lot of user opening issues everyday, and a lot of them need to be filtered because they are basic questions about how to use the engine.

Now, regarding your problem, you will a have to be a little bit more precise on "creat[ing] any useful AnimationTree which does anything via GDScript.". 
Animation is not meant to be made via GDscript, that's why we have an editor. Though, as I just showed you (_Note: I edited the script, there was an error there_), it is totally possible to "manipulate AnimationTree resources from scripts", which answers your initial question. You can create your own animation tree by manipulating AnimationNode resources and attach them via the several available properties.

Now, if you see any limitation there, please be a little bit more precise on your problem.

**Comment by slapin** [comment]
The long term problem is setting-up part of animation tree procedurally at run time to allow customization of animation set. I want to create procedural animation resources and add them to the tree. This way I will not need to have random animations pre-generated and will generate them at run time and add to AnimationTree.

**Comment by groud** [comment]
> Aniumation resources can e created and edited by GDScript just fine, you're wrong here.

No I am not.

Everything you describe is already possible, here is an example on how you could automatically generate a state machine, with two animations and two transitions :
```
	var tree = AnimationTree.new()
	var state_machine = AnimationNodeStateMachine.new()
	tree.tree_root = state_machine
	
	var anim_node1 = AnimationNodeAnimation.new()
	anim_node1.animation = "anim1"
	var anim_node2 = AnimationNodeAnimation.new()
	anim_node2.animation = "anim1"
	
	state_machine.add_node("anim1", anim_node1)
	state_machine.add_node("anim2", anim_node2)
	
	var transition1 = AnimationNodeStateMachineTransition.new()
	var transition2 = AnimationNodeStateMachineTransition.new()
	
	state_machine.add_transition("anim1", "anim2", transition1)
	state_machine.add_transition("anim2", "anim1", transition2)
```
You could also add blend tree nodes, but I can ensure you all you describe is already possible.

**Comment by mrcdk** [comment]
You can create an AnimationTree without any issues using GDScript (or C# I guess, I haven't tried that) only:

```
	tree = AnimationTree.new()
	add_child(tree)
	tree.anim_player = $AnimationPlayer.get_path()
	
	var root = AnimationNodeBlendSpace1D.new()
	tree.tree_root = root
	
	var anim1 = AnimationNodeAnimation.new()
	anim1.animation = "test"
	var anim2 = AnimationNodeAnimation.new()
	anim2.animation = "test2"
	
	root.add_blend_point(anim1, 0)
	root.add_blend_point(anim2, 1)
	
	tree.active = true
```

That creates an animation tree with a BlendSpace1D as its root and adds 2 animations to the BlendSpace1D then you can use `tree["parameters/blend_position"]` to modify that value like you would do normally

**Comment by slapin** [comment]
Thanks a lot for your help! You really increased my quality of life.

Could we please have the examples added to the AnimationTree doc on site?
What needs to be done for this to happen?
https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html

It is not only me who have problems like that. Thanks a lot to you people!
Have a nice day!

**Comment by groud** [comment]
> Could we please have the examples added to the AnimationTree doc on site? What needs to be done for this to happen? https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html 

You can open an issue on the [Godot docs repository](https://github.com/godotengine/godot-docs), though I am not sure this belongs to the official documentation. That being said, maybe a tutorial would be appropriate.

> Have a nice day!

So do you ;)
