### ISSUE TITLE
Sprite3D settings should be uniform; billboarding

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#25055]
**Godot version:**

07e2046980c903268ef0d2f5a73caea77d511519

**Issue description:**

Sprite3D has settings inherent just to Sprite3D, like Modulate, Opacity, Transparent, Shaded, Alpha Cut, and so forth; however, there is no option to Billboard in any capacity, necessitating the use of a SpatialMaterial override, which then overrides many of the properties inherent to Sprite3D (except for Texture, which is not overridden by albedo texture, but is affected by albedo color.)  This causes ambiguity: for example, if you wanted your Sprite3D to fade out, your first thought might be to modify the Modulate property, but if you've set a material override because you needed something Sprite3D doesn't provide on its own, then your code or animation will appear to do nothing; you would instead need to access the material override (and ensure it was made unique), then manipulate its albedo.  Worse: you've already done the work, realized you wanted your Sprite3D to billboard, and have to go back and change your implementation to compensate for it; at that point, the safest option is to just include the SpatialMaterial from the very beginning and work with that instead of the Sprite3D's inherent properties.

It begs the question: why does the Sprite3D need these properties, when a material override is likely required to make up for its lack of features--usually, to get it to billboard (and you have to admit, billboarding a Sprite3D is a pretty common need for these nodes.)  Either Sprite3D should provide what you need without necessitating a SpatialMaterial, or a SpatialMaterial should be the standard way to manipulate a Sprite3D's appearance.  In my opinion, the former should be chosen: Sprite3D should be made complete.

![image](https://user-images.githubusercontent.com/28724859/51296659-ba468d80-19e2-11e9-9402-c9556b9c65d3.png)

**Comment by ElfEars** [comment]
Can confirm there used to be a billboard option before 3.0

**Comment by KoBeWi** [comment]
Another solution would be ability to create a SpatialMaterial from already configured Sprite3D.

**Comment by tre4b** [comment]
Under flags in a Sprite3D in 3.2 there is a billboard option....
