### ISSUE TITLE
Support for unmanaged libraries with Mono/C# 

### ISSUE THREAD

**Issue by alexfonseka** [godotengine/godot#25051]
Hey there.

I've had a lot of trouble trying to get unmanaged libraries to work with the C# implementation of Godot. 
I've looked online for resources and it seems a lot of people have had success with NuGet packages and managed libs but no one has yet been able to successfully integrate a third party unmanaged lib with Godot (eg. Steamworks.NET, Fmod Studio etc.). It's relatively simple to do this with Unity and I'm pretty sure MonoGame as well. So far the only way to use these libs with Godot is through native code written with C++ and GDNative which is quite time consuming compared to using already available C# wrappers. 

What is the current situation with support for this? and has anyone been able to do it with success?

This is related to #24898 by the way but I'm creating a new one because firstly I didn't get the terminology quite clear that time and it only mentioned a single library but seems like the issue applies to all unmanaged libraries.

**Comment by SeaKarp** [comment]
I'm having the same issue. When I install a thrid-party NuGet package and I build the project Godot will fail to find the "SystemAssemblyInfo.cs" file.

**Comment by alexfonseka** [comment]
Was finally able to get this resolved with Godot 3.1 beta 3
See #24898
