### ISSUE TITLE
Project export resizes height too much when adding/opening android preset for the first time

### ISSUE THREAD

**Issue by SoIAS** [godotengine/godot#25065]
**Godot version:**
07e2046980c903268ef0d2f5a73caea77d511519

**OS/device including version:**
Win 10 Pro
Gigabyte HD 7950 - drivers 18.12.2

**Issue description:**
When android preset is added or opened for the first time in a newly opened project, the popup is resized too much (even beyond screen bounds, but that depends on a size of the Godot window)
![androidexport](https://user-images.githubusercontent.com/10081294/51326490-89606a00-1a6f-11e9-9f5b-499d6f634e9e.png)

**Steps to reproduce:**
1. Open any project (preferably a new one)
2. Open project export
3. Add android preset or open an existing android preset (you cannot have had opened any preset previously - you will need to reopen the project for this to occur again)

**Comment by akien-mga** [comment]
Indeed, I've seen that too.

**Comment by ankitpriyarup** [comment]
I Fixed it in #25163
