### ISSUE TITLE
Pivot for selected node should be always visible

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#25067]
**Godot version:** 3.1.beta.calinou.07e2046

**OS/device including version:**
64 bit linux

**Issue description:**
Godot 3.1 was changed to only show the gizmos relevant to the selected node and tool. Unfortunately, this also means that for nodes containing a pivot, such as Sprite, AnimatedSprite and Polygon2D, the pivot is only visible when having the Assign Pivot tool selected. 
Being able to see the pivot is important for positioning and animation so it should always be visible, at least for the currently selected node. Consider that nodes like Node2D and KinematicBody2D have a cross shaped gizmo serving this function rather than no gizmo at all

**Comment by williamd1k0** [comment]
Is this really an "enhancement" since it works as expected in 3.0 stable?
I'm missing this feature in 3.1, so this seems more like a bug/regression to me :/

**Comment by groud** [comment]
> Is this really an "enhancement" since it works as expected in 3.0 stable?
I'm missing this feature in 3.1, so this seems more like a bug/regression to me :/

I changed that on purpose, that's why I added the enhancement tag too.

**Comment by williamd1k0** [comment]
Ah okay.
Any specific reason to hide the pivot?

**Comment by groud** [comment]
> Any specific reason to hide the pivot?

I personally think it is annoying to have a cross in the middle of your sprite, as once the pivot is set, you usually do not have to move it again. As it is not movable in the selection mode, I think it is in general pointless to display. Also, the smart snapping allows to snap the node automatically, which limits the need to see the pivot. 

Note that the cross is visible in the pivot mode though, when you really need to see it.

**Comment by noidexe** [comment]
@groud it might not be your use case, but there's a reason every animation or image editing software shows you the pivot all the time. It's important for the artist workflow as a reference point. Smart snap only works if the pivot has something to snap and it's only useful for positioning, not for animation. Also when animating, and since godot doesn't show motion curves, the pivot movement allows you to notice if your curves are working fine. It's not that easy to see by looking at the whole image. 

Moreover, all the arguments you give for not showing the pivot could also be applied to the bounding box. I could argue that it is annoying to have a box surrounding your sprite when you're not scaling it, and you have snap to sides for positioning. However, it is actually useful to have it always visible for positioning and animation. For example if you have a frame by frame explosion the bounding box allows you to see if it'll fit on screen, if it is the right size, if it is properly framed, so on. Same goes for the pivot, it shows you the exact position of your sprite so it _is_ relevant when using the move tool.
