### ISSUE TITLE
Spot light projector don't work

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#2506]
I asked on FB group and, at least another user  had bad luck with this feature. Here a simple test case saved with 2.0 alpha:  http://ffxrunner2.ffx.it/godot_testcases/testcase_projector_lamp.zip

**Comment by procedural** [comment]
Related to https://github.com/godotengine/godot/issues/2002

**Comment by bojidar-bg** [comment]
Right, dupe of #2002
