### ISSUE TITLE
Add a build-time option to disable Google Payments for in-app purchases

### ISSUE THREAD

**Issue by j2l** [godotengine/godot#25060]
It's more than a rhetorical question, it's an ethical bug. 
I'll keep factual, please do it too.

**Godot version:**
3.1beta1

**OS/device including version:**
Android template generation on Win10Pro

**Issue description:**
Compiling a bare minimal android template (using `scons --help`), then scrutinizing it, exposes Google Payment with no options to modify it at compilation time (or in the editor AFAIK).

It was optional using `engine.cfg`

APK content:
![image](https://user-images.githubusercontent.com/65325/51319075-c07d4e00-1a64-11e9-9118-824d56ac9f1b.png)

It comes with stuff hardcoded like:
`private static final String BASE64_PUBLIC_KEY = "REPLACE THIS WITH YOUR PUBLIC KEY";`
How could you change this within Godot Editor?

Godot stands out by being transparent and modular.
It really helps staying in line with GDRP. 
Some other tools tends to force analytics package, may be to resell their customers' customers (players) data.
The game publisher is responsible for his/her customers' data.

**Steps to reproduce:**
Compile an android template with any settings.
Install any APK reader/editor/Studio app you like.
Get into your generated `android_release.apk`.

**Comment by raymoo** [comment]
What is the problem? Do those modules even do anything if you don't call any of their classes / methods? I'm having trouble seeing what GDPR problems this causes.

Hardcoded public key isn't a security problem (as long as it doesn't correspond to someone's actual key) and will just cause the program not to work when it needs to have the correct public key. If a hardcoded private key was included then that would be an issue.

**Comment by j2l** [comment]
Thank you for your reply @raymoo.
Since you don't mind having it as it is please explain:
If it doesn't do anything if not called, why is it here, just bloating all APKs?
What is the logic here?

**Comment by j2l** [comment]
Thx for pointing in the right direction.

It's in core since, at least, [2014](https://github.com/godotengine/godot/pull/464), 
It's not mandatory for Godot to run, 
It's not really documented (but your link help), 
It's [hardly configurable](https://github.com/godotengine/godot/pull/2691#commitcomment-14858954)
And it's in all and every APKs

It's definitely "something to improve".
What would be needed to turn it into a module?

**Comment by raymoo** [comment]
I don't know much about the API, maybe @volzhs (who submitted that patch) would have an idea?

**Comment by Anutrix** [comment]
Afaik, Android in-app purchases depend on Godot Payment Manager which depends on GodotPaymentV3.
An option to disable it(example for Free games) wouldn't be a bad idea but removing from Godot source isn't good idea because in-app purchases really common to have in an Android game.

**Comment by volzhs** [comment]
seems fixed 3.2.2, isn't it?

**Comment by j2l** [comment]
Great to hear. I stopped Godot because of this miscommunication

**Comment by Calinou** [comment]
@volzhs Is this now done by default? I remember GooglePayments being moved to an officially-supported Android module.

**Comment by Anutrix** [comment]
Fixed by https://github.com/godotengine/godot/pull/39745.

**Comment by volzhs** [comment]
there is no more builtin android payment after 3.2.2
Need to do additional work for it.
