### ISSUE TITLE
Color encoding inconsistancy

### ISSUE THREAD

**Issue by frankiezafe** [godotengine/godot#25063]
**Godot version:**
master, commit 96899b7ee1cb442ce9625232d558670fe7011c2c

**OS/device including version:**
linux mint 18, 64bits

**Issue description:**
When encoding **127** on the any RGB channel in the color picker, the value saved in the tscn is _0.498039_. When scene is reloaded, the color picker displays **126**. This is particularly unpleasant when trying to have precise control over shader via textures.

**Steps to reproduce:**
Encode **127** in a Gradient via color picker, close the scene and reopen it.

**Solution proposal:**
Propose an option in the editor to encode colors in float [0,1] instead of int [0,255]. just like it is in opengl and in tscn... Might be tricky for non-coders, but much more precise for devs :)

Thanks in advance,

françois z.

**Comment by akien-mga** [comment]
>  Propose an option in the editor to encode colors in float [0,1] instead of int [0,255]. just like it is in opengl and in tscn... Might be tricky for non-coders, but much more precise for devs :)

That exists already, it's what the "Raw" button gives you.

Nevertheless, it should be possible to save 127 as raw and convert it back to 127 properly, so that's a bug that needs to be fixed.
