### ISSUE TITLE
Focus switches to exported variable fields in the inspector on it's own

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#25072]
**Godot version:**
![image](https://user-images.githubusercontent.com/7307968/51342428-30ef9380-1a94-11e9-9b7c-54c767066307.png)

**OS/device including version:**
Win 64

**Issue description:**
Sometimes when working with scenes with Nodes that have exported variables, the focus starts switching randomly on it's own to their fields from the script editor. Closing and reopening scene fixes the issue.

![2019-01-17_20-10-02](https://user-images.githubusercontent.com/7307968/51342534-7e6c0080-1a94-11e9-862e-4c9b40766ff7.gif)

**Comment by bojidar-bg** [comment]
Duplicate of #24979?

**Comment by PLyczkowski** [comment]
@bojidar-bg Oops, correct. Don't know why it didn't find it when creating, sorry. Closing.
