### ISSUE TITLE
Auto Brace Complete: extra quotation mark when typing string

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#25084]
**Godot version:**
3.1-beta e033699

**OS/device including version:**
Windows 10

**Issue description:**
Adding a quotation mark at end of a string with Auto Brace Complete enabled adds an extra quotation mark, when it should "pass through" the last one and put the cursor after it:

![jk42crl](https://user-images.githubusercontent.com/27100585/51365116-e4a76080-1b32-11e9-8869-5818b8db8434.gif)

This doesn't happen if the character to the left of the cursor is whitespace; it functions correctly in that case.

**Steps to reproduce:**
1. Enable "Auto Brace Complete" (in Editor Settings, under Text Editor -> Completion)
2. Type a string

**Comment by kagonzalez** [comment]
Is this bug still being worked on?
