### ISSUE TITLE
RigidBody2D Can Sleep on Inspector is not working as expected

### ISSUE THREAD

**Issue by Calzzetta** [godotengine/godot#25099]
**Godot version:**
3.1 master (latest nightly build from Hugo)

**OS/device including version:**
Win 10
OpenGL ES 3.0 Renderer: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2

**Issue description:**
When using RigidBody2D you can mark the "Can Sleep" attribute on Inspector, but it will not affect the behavior of the body if Gravity = 0. You must put it in your code "can_sleep = true" to get the sleeping signal.

**Steps to reproduce:**
Create a RigidBody2D with:
- Linear Velocity
- Damp = 1
- Gravity Scale = 0
- Can Sleep = true

Create a StaticBody2D to interact with with rigid body

Create a script that set the can_sleep attribute of RigidBody2D

**Minimal reproduction project:**
[Demo.zip](https://github.com/godotengine/godot/files/2773146/Demo.zip)

**Comment by RedMser** [comment]
Seems like setting it in code runs `set_can_sleep`, which also updates the body's `CAN_SLEEP` state. The inspector value only updates `can_sleep` (or the body state gets reset for some reason).

Add `print(Physics2DServer.body_get_state(self.get_rid(), Physics2DServer.BODY_STATE_CAN_SLEEP))` to the `_ready` function, and you see this:

```py
#Can Sleep is ticked in the inspector

func _ready():
	print("can_sleep: ", can_sleep)
	print("BODY_STATE_CAN_SLEEP: ", Physics2DServer.body_get_state(self.get_rid(), Physics2DServer.BODY_STATE_CAN_SLEEP))

	#returns True, False
	
	can_sleep = true
	
	print("can_sleep: ", can_sleep)
	print("BODY_STATE_CAN_SLEEP: ", Physics2DServer.body_get_state(self.get_rid(), Physics2DServer.BODY_STATE_CAN_SLEEP))

	#returns True, True
```
