### ISSUE TITLE
autoload

### ISSUE THREAD

**Issue by blain1972** [godotengine/godot#25096]
**Godot version:**
v3.1.beta1.official

**OS/device including version:**
Ubuntu 18.10

**Issue description:**
I have a script which autoloads. It contains several enums intended as a list of actions for different classes.

e.g.

```
extends Node

enum input_type {HAS_TARGET, MY_HEALTH, MY_ENERGY, DISTANCE_TO}
```

This is then referenced and assigned to each class as required.

```
extends Node2D

enum my_input_type {}

onready var actions = get_node("/root/actions")

func _ready():
	print(actions.input_type)
	my_input_type = actions.input_type
```

My project currently works fine in 3.0.2, 3.0.4, 3.0.5 and 3.0.6 but when testing 3.1 beta it failed with **Parser Error: Cannot assign a new value to a constant**

I should be able to assign value to what is essential an empty enum. Or am I going about this the wrong way?

This may be similar to [#20008](https://github.com/godotengine/godot/issues/20008) but this can be reproduced on 2.1+ whereas this works in earlier versions but fails on the current beta

**Steps to reproduce:**
run relevant project in 3.1 and the other sample project in 3.0.6

**Minimal reproduction project:**
[3.1 Test.zip](https://github.com/godotengine/godot/files/2772781/3.1.Test.zip)
[same test in 3.0.6.zip](https://github.com/godotengine/godot/files/2772783/same.test.in.3.0.6.zip)

**Comment by eon-s** [comment]
The behavior seems correct, you should not be able to modify an enum, use a dictionary or array instead.

**Comment by akien-mga** [comment]
Enums are not mutable in GDScript, nor in C++. They're usually used to define constants at compile time.

If you need a mutable structure similar to an enum, you should use a Dictionary. Enums in GDScript are actually just dictionaries that declare their keys as constants.
