### ISSUE TITLE
GLES2: shader compilation error passing DEPTH_TEXTURE to a function

### ISSUE THREAD

**Issue by lupoDharkael** [godotengine/godot#25106]
**Godot version:**
3.1 beta 2

**OS/device including version:**
Fedora 29: Linux 4.19.13-300.fc29.x86_64

**Issue description:**
Passing DEPTH_TEXTURE to a function causes the viewport to render a white area:
![image](https://user-images.githubusercontent.com/14951430/51401175-71114d80-1b4a-11e9-893f-d7e2040b2382.png)

Here is the relevant output of the console:

```
drivers/gles2/shader_gles2.cpp:196 - SceneShaderGLES2: Fragment shader compilation failed:
0:849(18): error: `depth_buffer' undeclared
0:849(2): error: no matching function for call to `m_calculate_bug(error)'; candidates are:
0:849(2): error:    void m_calculate_bug(sampler2D)
```

**Steps to reproduce:**
Open Test.tscn in the minimal reproduction project

**Minimal reproduction project:**
[gles2-shader.zip](https://github.com/godotengine/godot/files/2773794/gles2-shader.zip)

**Comment by clayjohn** [comment]
It looks like reading from the depth buffer is not yet implemented in GLES2. https://github.com/godotengine/godot/blob/93d8f3cdd5f0166fcbf8456488e98bfd4d9e02bb/drivers/gles2/shaders/scene.glsl#L700

**Comment by reduz** [comment]
I guess this could be supported, but it's not portable (won't work on many older mobile devices)

**Comment by reduz** [comment]
figured out a way, so added it. Wont work on very old mobile hardware though.
