### ISSUE TITLE
enums can be modified by assignment

### ISSUE THREAD

**Issue by blain1972** [godotengine/godot#25103]
**Godot version:**
3.1 beta 1

**OS/device including version:**
Ubuntu 18.10

**Issue description:**
enums can be modified by assignment

```
extends Node2D

enum input_type {HAS_TARGET, MY_HEALTH, MY_ENERGY, DISTANCE_TO}
var my_input_type = {}

func _ready():
	my_input_type = input_type
	
	print(my_input_type)

	my_input_type.HAS_TARGET = 1 # accidental assignment

	print(my_input_type)
	
	print(input_type) # HAS_TARGET in enum has now been modified
```
result:

unintended behaviour: original enum is modified

**Steps to reproduce:**
run test project

**Minimal reproduction project:**
[3.1 Test.zip](https://github.com/godotengine/godot/files/2773551/3.1.Test.zip)

edit: added beta version

**Comment by IronicallySerious** [comment]
I am looking into this

**Comment by vnen** [comment]
This is not really a bug since enums are just a shorthand for dictionaries. Since it's only a regular dictionary, nothing stops you from changing the contents.

**Comment by IronicallySerious** [comment]
But should enums be modifiable in the first place? Comparing it to how enums are used in other languages, this sounds counter-productive

**Comment by bojidar-bg** [comment]
@IronicallySerious Well, they shouldn't be, but it is unavoidable unless we add a notion of "Constant dictionary" or something of the sorts.

**Comment by IronicallySerious** [comment]
Also, there seems to be another problem. Changing `my_input_type` as actually modifying `input_type` too. Almost as if these enum instances were assigned by reference and not by copy

**Comment by KoBeWi** [comment]
Actually, re-assigning values in enum might be useful sometimes, like when you can't provide desired value during declaration, because it depends on `onready` variable (happened to me once). What should be impossible is adding new values to enum, i.e. the key set should be immutable.

**Comment by bojidar-bg** [comment]
@KoBeWi That would break a lot of optimizations, since replacing `Enum.VALUE` with a specific value can no longer be made safely. People should use variables for this, instead of relying on modifying constants.

**Comment by vnen** [comment]
For 4.0 we can make enums more first-class. Not really much room to solve this without breaking compatibility.

**Comment by KoBeWi** [comment]
Still valid in d834789f4

**Comment by KoBeWi** [comment]
Enums are now enums in GDScript 2.0, so this is resolved.
