### ISSUE TITLE
Mono: ImmediateGeometry not drawing correctly

### ISSUE THREAD

**Issue by David-Ochoa** [godotengine/godot#25109]
**Godot version:**
Godot 3.1 beta 2

**OS/device including version:**
Windows 10,Intel Integrated HD4000, Ryzen 3 Vega 8

**Issue description:**
I was porting motion trail from asset library to C#, but the drawn geometry is all cluttered around node's origin.

**Steps to reproduce:**
Open attached project, there are two trails: one using GDScript and the other C#, the GDScript draws a trail while the C# draws a small flickering shape.

**Minimal reproduction project:**
[motion-trails-1.0.zip](https://github.com/godotengine/godot/files/2774023/motion-trails-1.0.zip)

**Comment by neikeq** [comment]
This is not a bug. There is an error in your code.

You have this line in GDScript and the equivalent in C#:

``` GDScript
var t = float(i + 1) / points.size()
```

``` C#
float t = (i + 1) / points.Count;
```

The C# code is wrong. It's making an integer division. It should be:

``` C#
float t = (float)(i + 1) / points.Count;
// or
float t = (i + 1f) / points.Count;
```
