### ISSUE TITLE
Toggling fullscreen in Ubuntu freezes computer

### ISSUE THREAD

**Issue by LuminousNutria** [godotengine/godot#25107]
**Godot version:**

version 3.0.6 stable mono x11 64

**OS/device including version:**

Ubuntu 18.04 64-bit
Geforce GTX 1080 Ti
Nvidia Driver Metapackage 415 

**Issue description:**

Toggling fullscreen while my game is running, immediately freezes the computer. Forcing a manual shutdown.

I don't know if there is currently another way to toggle fullscreen but my method is to make a global script and use this code:

    extends Node

    func _process(delta):
   
        if(Input.is_action_pressed("go_fullscreen")):
            OS.window_fullscreen = !OS.window_fullscreen

**Steps to reproduce:**
Run the game and press "alt + enter".

**Minimal reproduction project:**

I went to `Project >> Export >> Export PK/Zip` but it didn't seem to do anything but go back to the prior screen when I clicked save. So, I just zipped the files from outside of the program.
[Bandit_King.zip](https://github.com/godotengine/godot/files/2773909/Bandit_King.zip)

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
That code seems bad though. If you press and hold Space you gonna flip back and forth as long as key is pressed.

**Comment by LuminousNutria** [comment]
Then that's probably my issue. I just came back to edit my post and say that since I switched to `Input.is_action_just_pressed()` it worked. 

Sorry, I'm new to GDScript.
