### ISSUE TITLE
Mono: Incorrect error message when script's extended class doesn't match attached node type

### ISSUE THREAD

**Issue by exts** [godotengine/godot#25104]
**Godot version:**
3.1 beta2

**OS/device including version:**
Windows 10

**Issue description:**
If you attempt to attach a script to a node and the extended class doesn't match the node it'll spit out this error message:

```
ERROR: No loader found for resource: res://
   At: core/io/resource_loader.cpp:279
```

**Steps to reproduce:**
- Create a class of a mismatching node type (say KinematicBody2D)
- Attach script to node (Say Node2D)
- Run scene
- Watch godot pause application

**Minimal reproduction project:**
[BetaTwoErrors.zip](https://github.com/godotengine/godot/files/2773693/BetaTwoErrors.zip)

**Comment by neikeq** [comment]
Is this the same as #26675?

**Comment by exts** [comment]
@neikeq based on akien's post, i think it is
