### ISSUE TITLE
HTML5 export broken in 3.1 beta 2: JSEvents.lastGamepadState is undefined

### ISSUE THREAD

**Issue by eklmv** [godotengine/godot#25100]
**Godot version:** 3.1 beta 2

**OS/device including version:** Winfows 10, Firefox 64.0.2

**Issue description:**
Exported to HTML5 project throws:
`TypeError: JSEvents.lastGamepadState is undefined 
`

**Steps to reproduce:**
Just export to HTML5 any project and open in browser.

**Minimal reproduction project:**
Empty scene is enough.

**Comment by santouits** [comment]
Yeah I'm having this too. Reading https://kripken.github.io/emscripten-site/docs/api_reference/html5.h.html#c.emscripten_sample_gamepad_data , I think we have to call this function somewhere in our code before https://github.com/godotengine/godot/blob/c0fcf77b3878873704200b754cdc27d4dc88a084/platform/javascript/os_javascript.cpp#L712

but don't know where would be the best place. @eska014 or someone else. 
Also maybe https://github.com/godotengine/godot/issues/25123 is duplicate.

**Comment by TheoLeeCJ** [comment]
#25123 is for Google Chrome and the errors are different.
