### ISSUE TITLE
GDScript: 'export var script' is allowed and messes things up

### ISSUE THREAD

**Issue by santouits** [godotengine/godot#25105]
**Godot version:**
3.1beta2

**OS/device including version:**
debian stable

**Issue description:**
gdscript editor allows you use ```export var script``` without any warning

If you write ```export var script = ""``` in your script and then save a scene that was attached, the .tscn file doesn't contain the script anymore. If you open the scene again, no script will be loaded.

If you make the same script and add a ```class_name``` and then add the node to your main scene and save the main scene, and then open the .tscn file of the main scene, no script reference again.

**Comment by vnen** [comment]
The problem is that `script` is not a property of `Object` (in fact, currently `Object` has no properties at all). Because of that the GDScript parser doesn't know that it is already defined in the parent. If it did, this case would be noted as an error in the editor.
