### ISSUE TITLE
Raising script-error in editor resets inherited export-hint-properties

### ISSUE THREAD

**Issue by Th0r12356** [godotengine/godot#25121]
**Godot version:**

3.1.beta.custom_build.d8b702b

**OS/device including version:**

Linux 4.18.14-arch1-1-ARCH x86_64 GNU/Linux

**Issue description:**

Raising an error in the script editor of a baseclass like "variable x already exists" and save, properties set by export hints in inheriting scenes are lost. If 10, 20 or more lovely adjusted assets will be resetted by one scripting failure in the baseclass, it could be a little sad.
Please correct me if i'm doing something wrong or misunderstood. Sorry for the bad title.

**Minimal reproduction project:**
[issueExportInheritance.zip](https://github.com/godotengine/godot/files/2775106/issueExportInheritance.zip)
- click on Node2D in Something.tscn
- click the inspector tab, values in exporthint are set
- switch to script tab and select baseOfSomething.gd
- uncomment "#var addline" and hit ctrl+s

**Comment by akien-mga** [comment]
Sounds like #24280 which is supposed to be fixed by #24877 (and d8b702b contains that fix already). CC @neikeq

**Comment by Th0r12356** [comment]
#24280 describes the issue very well. Extending the script with an other script and saving is necessary for this issue. Export vars are working without loss when not extending to another script on compile error.
