### ISSUE TITLE
C# callbacks leak parameters (e.g. InputEvent @event)

### ISSUE THREAD

**Issue by Phin236** [godotengine/godot#25125]
**Godot version:**

godot mono 3.1 beta1

**OS/device including version:**

window10

**Issue description:**

CODE LIKE:
```
   public override void _Input(InputEvent @event)
    {

    }
```
RESULT:
the _input() function causes more and more objects in memory !!!
when I debug!
![debug](https://user-images.githubusercontent.com/34740477/51424175-5cde5680-1c05-11e9-941a-48e8aa32d750.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Phin236** [comment]
public override void _GuiInput(InputEvent @event)
{

}
has the same result!!

**Comment by neikeq** [comment]
I thought this was fixed long ago. Maybe reintroduced?

**Comment by neikeq** [comment]
Are you sure this is not just the GC not collecting these objects yet?

I just tested with the following:

``` C#
public override void _Input(InputEvent ev)
{
    if (ev is InputEventKey keyEvent && keyEvent.Scancode == (int)KeyList.C)
    {
        GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
    }
}
```

The object instance count will go up like it does in your screen, pressing C restores it to normal.

**Comment by Phin236** [comment]
Godot_v3.1-beta3_mono_win64 has the same result!

**Comment by neikeq** [comment]
As I explained above in my tests there were no memory leaks.
The GC does not necessarily have to collect these objects immediately. I forced a collection to confirm the objects were released correctly.
