### ISSUE TITLE
RichTextLabel spacing issue on small resolutions

### ISSUE THREAD

**Issue by wagnerfs** [godotengine/godot#25127]
**Godot version:**
v3.1.beta2.official

**OS/device including version:**
Windows 10 pro x64

**Issue description:**
This weird spacing skip or something only happens when the game is running, on editor it looks just fine (like on the pic).
Also the project works fine on Godot 3.0, since I'm testing it on 3.1.
I also tweaked with all possible options for both the RichTextLabel and the Dynamic font but no fix.

![image](https://user-images.githubusercontent.com/106078/51424570-bff4cc80-1bb6-11e9-9aa8-a07d466730b6.png)
![image](https://user-images.githubusercontent.com/106078/51424581-e61a6c80-1bb6-11e9-9b89-9aa30d327e7e.png) 
![image](https://user-images.githubusercontent.com/106078/51424582-ef0b3e00-1bb6-11e9-80ad-801195dd98e5.png)

**Steps to reproduce:**
Any RichTextLabel with a Dynamic font of size 16 using the file bellow.
[pixel_text.zip](https://github.com/godotengine/godot/files/2775365/pixel_text.zip)

Game resolution: 224x126
Stretch:
- Mode: Viewport
- Aspect: Ignore

**Comment by razcore-art** [comment]
I can confirm in v3.1.beta3.official too, on this small resolution, on larger resolution doesn't seem to be obvious.

**Comment by txigreman** [comment]
I have the same problem and also noticed that, if "Extra Spacing / Char" is increased, spacing is not respected after formatted text:

![image](https://user-images.githubusercontent.com/778778/55101849-5c5eb200-50c5-11e9-91a3-d861880c3842.png)

Te bbcode used in the screenshot is:
`Has conseguido el [color=red]Palo Legendario[/color]!! Legendario!!`

**Comment by txigreman** [comment]
Label seems to work fine, at least in my case:

![image](https://user-images.githubusercontent.com/778778/55102748-62ee2900-50c7-11e9-8f53-1e8c742c83ae.png)

The first is a RichTextLabel, de second a simple Label. They both are using the same DynamicFont. 

It seems like RichTextLabel is ignoring the width of the chars in the ttf file, removing the empty spaces, and only taking into account the "drawn area" of them.

As Wagnerfs said it seems to work properly in the editor, but not when running the game.
Changing from GLES2 to GLES3 does not affect at all.

**Comment by txigreman** [comment]
Demo Project: [Test.zip](https://github.com/godotengine/godot/files/3015451/Test.zip)

**Comment by Calinou** [comment]
I'll close this issue as a duplicate in favor of https://github.com/godotengine/godot/issues/24570. Thanks for confirming it :slightly_smiling_face:

**Comment by txigreman** [comment]
Ups, my [last comment](https://github.com/godotengine/godot/issues/24570#issuecomment-477528019) in the other issue was supposed to be posted here… I've edited my comments in that issue to link the demo Project attached to this one!

Thank you Calinou, and sorry for the mess.
