### ISSUE TITLE
Crash when using ReflectionProbe shadows on gles2

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#25131]
**Godot version:**
7f9209781cea7148934a5e48c5c14167ce256cc8

**OS/device including version:**
Ubuntu 18.04, 64bit, GTX1060

**Issue description:**
When clicking `Enable Shadows` in reflection probe it will cause an editor crash. 
Here is a stack trace:
```
1  RasterizerSceneGLES2::render_shadow              rasterizer_scene_gles2.cpp 3018 0x1ac9644 
2  VisualServerScene::_light_instance_update_shadow visual_server_scene.cpp    1530 0x2f4e04e 
3  VisualServerScene::_prepare_scene                visual_server_scene.cpp    2023 0x2f432db 
4  VisualServerScene::_render_reflection_probe_step visual_server_scene.cpp    2222 0x2f4483a 
5  VisualServerScene::render_probes                 visual_server_scene.cpp    3138 0x2f4a031 
6  VisualServerRaster::draw                         visual_server_raster.cpp   107  0x2f34d3a 
7  VisualServerWrapMT::draw                         visual_server_wrap_mt.cpp  102  0x2f6997c 
8  Main::iteration                                  main.cpp                   1876 0x118f4f2 
9  OS_X11::run                                      os_x11.cpp                 2986 0x1162df7 
10 main                                             godot_x11.cpp              55   0x1154013 

```

**Steps to reproduce:**
1. Download reproduction project. 
2. Open Gles2BlackArtifacts scene
3. Select Reflection probe node
4. Click toggle "Enable shadows" property of Reflection probe

**Minimal reproduction project:**
[ReflectionProbeGles2Crash.zip](https://github.com/godotengine/godot/files/2775507/ReflectionProbeGles2Crash.zip)

**Comment by akien-mga** [comment]
Confirmed on 6e60070.

**Comment by reduz** [comment]
@kubecz3k I think you zipped the wrong example project

**Comment by kubecz3k** [comment]
@reduz sorry for that, thanks for the fix! :heart:
