### ISSUE TITLE
Debugger - for loop displays wrong locals and members with same name

### ISSUE THREAD

**Issue by TomCoursow** [godotengine/godot#25133]
**Godot version:** 3.0.6 stable official 831 4054
**OS/device including version:** Windows 10 Pro

**Issue description:**
Hi I am a new Godot Engine user which does not know GDScript / Python very well yet but I know a lot of other Programming languages as I do work as a developer for a living. So I made a project just to try the first steps with Godot and GDScript.
I wrote a Loops.gd File to try how loops syntax and behaviours are in GDScript and during Debugger usage I noticed the following... (see reproduction steps...)

**Steps to reproduce:**
1. Create New Empty Project
2. Add Node to the Scene
3. Add Node Subnode to the root Node and attach a Loop.gd Script (See Screenshot 1)
4. Save the Scene
5. Debug the Game
6. Step through the Code with "Step Over" and watch Debugger Values...
Hint: **GDScript behaves correctly** but debugger displays it the wrong way

**Related Screenshots:**
![godot_debugger_bug](https://user-images.githubusercontent.com/17900090/51427356-7678a180-1bf7-11e9-9270-85300751c00e.png)
![godot_debugger_bug2](https://user-images.githubusercontent.com/17900090/51427357-7bd5ec00-1bf7-11e9-8890-03b7396ab6de.png)

**Minimal reproduction project:**
https://gitlab.com/tom.coursow/godot-pong/tree/develop

**Comment by akien-mga** [comment]
Relevant files to look into:
- `core/script_debugger_remote.cpp` (command `get_stack_frame_vars`)
- `editor/script_editor_debugger.cpp` (message `stack_frame_vars`)

The order in which the data is emitted and then processed seem consistent from a quick glance, so not sure what causes this inversion.

**Comment by TomCoursow** [comment]
**Additional Info:**
At first I tried the for loop with number with range(1, 10)
Then I thought maybe the 10 displayed in local scope has something to do with the ranged(1, 10)...
Thats why I changed it to 15 and saved the file and project.
But during the following debugging it displayed 10 again.

**Comment by TomCoursow** [comment]
I put a ```print(number)``` between ```number = 0``` and the loop now and then it displays it like this.
![debugger_bug](https://user-images.githubusercontent.com/17900090/51427647-a4131a00-1bfa-11e9-8c43-c7b86b1c063f.png)

**Comment by akien-mga** [comment]
The iterator in a for loop is always local, that's normal. In this last screenshot, you're shadowing the `number = 0` by a new local `number`, which takes values 1 to 14 and is then discarded. If you want to increment the one from the outer scope, use a `while` loop.

**Comment by KoBeWi** [comment]
Still valid in d834789f4

**Comment by KoBeWi** [comment]
Seems fixed in bb73daf
