### ISSUE TITLE
Controllers support mapping for 2in1 USB Joystick

### ISSUE THREAD

**Issue by salvob41** [godotengine/godot#25138]
When I attach the joypad 2in1 the mapping looks messed up. Godot says the the button at the bottom is actually the button up, and when I actually press the button down, it says  that is the button right. 

I guess it is something to do with the mapping in Godot ? 

**Godot version:**
Godot3.1-beta1

**Comment by aaronfranke** [comment]
Godot uses [the SDL2 game controller database](https://github.com/gabomdq/SDL_GameControllerDB) for controller mapping. Please contribute your changes there. You can create a mapping using Steam Big Picture mode.

**Comment by salvob41** [comment]
Cool, thank you.  I made a PR here. 

https://github.com/gabomdq/SDL_GameControllerDB/pull/243

Is there a way to test this on Godot without waiting for a sync ?

**Comment by aaronfranke** [comment]
Godot's copy is located [here](https://github.com/godotengine/godot/blob/master/main/gamecontrollerdb.txt), you can build the engine with your updated copy.

**Comment by salvob41** [comment]
Thank you, we can close this, then :)

**Comment by akien-mga** [comment]
Reopening as we should sync the mappings to fix it for real.

**Comment by salvob41** [comment]
This still doesn't work.

**Comment by salvob41** [comment]
https://github.com/godotengine/godot/blob/89ca15693ee81fa497d1bab24bd772a98bf56279/main/gamecontrollerdb.txt#L249
This is still messed up in different OS. And in macOSx have a different mapping. 

I will do another iteration to see what's wrong

**Comment by akien-mga** [comment]
> This still doesn't work.

In what version?

The mapping we have for Mac OSX is the one you contributed to the SDL2 repo.

**Comment by salvob41** [comment]
> In what version?
Godot3.1-beta4 
> The mapping we have for Mac OSX is the one you contributed to the SDL2 repo.
yeah, I know and it is weird. I tried also on Windows and Linux and the only one that works well is on LINUX. 
Plus, Vibration works only on the Linux platform. 

I'd reopen this, I will investigate further in the next few days

**Comment by salvob41** [comment]
Okay, I tried a few things and, at this point, I think is a mac_OSX bug and ... I need help:

The controller in question is: `2In1 USB Joystick` with GUID `030000008f0e00000300000009010000`

I tried the mapping with a `gamepad-tool`, I extract the mapping and compared with the current version of Godot's [controller database](https://github.com/godotengine/godot/blob/89ca15693ee81fa497d1bab24bd772a98bf56279/main/gamecontrollerdb.txt#L249) (and the current version in [SDL database](https://github.com/gabomdq/SDL_GameControllerDB/blob/40e3a34962e4edf6730bd941efdba89d0a95229a/gamecontrollerdb.txt#L250) . 

But when I attach the controller and used it in Godot it actually gives me different input (this happens for the buttons on the right - canonically `A,B,X,Y` if we use the XBOX Controller "standard"). 
I put up a scenes with the following code:

```
func _process(delta):
	# This is an example debug for controllers
	if Input.get_connected_joypads().size() > 0:
		 for i in range(16):
	      if Input.is_joy_button_pressed(0,i):
	        print("Button at " + str(i) + " pressed, should be button: " + Input.get_joy_button_string(i))

```

And.. this is the debug, for each button I pressed, this was the output: 
- for button down
`Button at 2 pressed, should be button: Face Button Left`
- for button left
`Button at 3 pressed, should be button: Face Button Top`
- for button up
`Button at 0 pressed, should be button: Face Button Bottom`
- for button right
`Button at 1 pressed, should be button: Face Button Right`

And if we match up with the mapping, it actually is right ... in particular:
>> a:b2,b:b1,x:b3,y:b0

Following the [mapping guide](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/data/mapping_guide.png)

So, my conclusion is that the mapping for buttons (b0,b1,b2,b3) is somehow wrong for mac_osx. Could it be?

**Comment by salvob41** [comment]
To clarify, here is a GIF in which I show the mapping from SDL (and its gamepad-tool) and the output from the above mentioned scene:
![bug_mapping_macos](https://user-images.githubusercontent.com/6097015/52863882-3397e400-3139-11e9-806f-7418c2218ac8.gif)

**Comment by nitaku** [comment]
I have a similar issue with the same controller on Ubuntu Linux. Godot sees L1 as L2 and R1 as R2. The SDL gamepad tool gets them right instead.
![bug](https://user-images.githubusercontent.com/1604569/52864047-9f7a4c80-3139-11e9-99cd-04d6e5bd6b20.gif)

**Comment by salvob41** [comment]
so, just to be sure. Is this a bug ? or something wrong with this specific controller/mapping ?

**Comment by akien-mga** [comment]
Can you check if it works fine in 3.2 beta 6 or later?
I might have fixed this with #34910.

**Comment by akien-mga** [comment]
I'll assume it fixed by #34910 for now, and if it isn't, it should be fixable by contributing the missing mappings to https://github.com/gabomdq/SDL_GameControllerDB.

Please comment if you can still reproduce the issue / need help to contribute mappings upstream if they're missing.

**Comment by salvob41** [comment]
@akien-mga sorry but I didn't have the chance to try it before. 

Sorry but it is not fixed, the problem is still the same ... In the sdl2 Gamepad tool the mapping is showing it correctly. The mapping in SDL2 database is correct. But Godot cannot import the mapping in the correct way for some reason. 
@bruvzg in #26544 found out about this problem: 

> Note that your controller mapping is not imported from SDL db, there's following error for it (and for multiple other controllers) in the default_controller_mappings.gen.cpp:
> 
> // WARNING - DISCARDED UNSUPPORTED MAPPING TYPE FROM DATABASE .../gamecontrollerdb.txt: Mac OS X 030000008f0e00000300000009010000,2In1 USB Joystick,+leftx:h0.2,+lefty:h0.4,-leftx:h0.8,-lefty:h0.1,a:b2,b:b1,back:b8,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b3,y:b0,platform:Mac OS X,
> Most likely Input.add_joy_mapping(...) doesn't accept mapping copied from gamepad-tool for the same reasons.
> 
> SDL db had some changes in 2.0.6/2.0.5/2.0.4 version. Probably some are not supported by Godot.


And I think the problem is in that "warning discarded". I could help out, but without guidance I don't know where to put my hands. 

So mother of all these issues might be: #8368 

What do you think ? We only leave that one opened ?

**Comment by akien-mga** [comment]
Thanks for the update, I misread this issue indeed.

I guess we only need to keep #8368 open, but it confirms that it's now starting to be an actual deal breaker and not just a missing feature as it used to be.

As a workaround for your controller in the meantime, it might be possible to create a mapping for it that still follows the SDL 2.0.5 style which we support, without using the half-axes feature.
