### ISSUE TITLE
Godot's Current Scene Management Problem (And How to Fix It)

### ISSUE THREAD

**Issue by Vadkline** [godotengine/godot#25145]
**Godot version:**

Godot's current scene management is currently, very lackluster,
Managing inheritance and scenes in general becomes tough if you're
going for a project that requires more than 5-10 scenes,
managing them can be seen as this: (please excuse the terrible MS Paint illustration)
    using my proposal: a Scene Tree. 
![scenetree1](https://user-images.githubusercontent.com/46850310/51431505-603c0700-1c32-11e9-97d0-5f8176fc8091.png)

You can inherit a scene simply by dragging & dropping that to the scene you want it to be inherited to. 
And more importantly - 
if you'd like to inherit the same scene more than once, you can make a clone and drag & drop that.
You can create a group, add scenes to that group, and further organize your project.
 
![scenetree2](https://user-images.githubusercontent.com/46850310/51431537-efe1b580-1c32-11e9-934b-7a248c47a05c.png)

I'm sure this Scene Tree, is a much better improvement, rather than this:

![scenetree3](https://user-images.githubusercontent.com/46850310/51431549-1869af80-1c33-11e9-9635-3cc06ad0e6f3.png)

Generally, stacking scenes horizontally is a bad idea, especially if you're going for more than 10.

![scenetree4](https://user-images.githubusercontent.com/46850310/51431562-4b13a800-1c33-11e9-9da1-e801312f9a9e.png)

Doesn't look appealing, and is harder to manage. You _can_ delete the scene but that isn't a problem
solver is it? 

If Godot's built around its majority using 5-10 scenes, that's a bad idea.
Godot won't age well, and if it's going to be used by larger companies to make games with it,
they _will_ go to the 20-50 scene area, we need a Scene Tree, and you dont have to wrap your-
head around Godot's U.I to find a new place to implement it, it can just be a new tab here: 

![scenetree5](https://user-images.githubusercontent.com/46850310/51431650-d8a3c780-1c34-11e9-9f4e-85ea2ef9c209.png)

A Scene Tree will make it faster, easier, & more convenient to manage scenes, inheritance, etc. 

I am planning on making a demo, just to show the basic idea.

**Comment by Ace-Dragon** [comment]
Is there a reason why you want to have every single scene in the game open simultaneously? I imagine having 20-50 scenes open at once would eventually eat a lot of memory if they are of a decent size.

I never run into the problem in the second to last image because I close the scenes I don't have a need to work in and find all my scenes via the file browser (that is assuming you organize your project with folders).

**Comment by Vadkline** [comment]
> Is there a reason why you want to have every single scene in the game open simultaneously? I imagine having 20-50 scenes open at once would eventually eat a lot of memory if they are of a decent size.
> 
> I never run into the problem in the second to last image because I close the scenes I don't have a need to work in and find all my scenes via the file browser (that is assuming you organize your project with folders).

not necessarily 20-50 scenes _open at the same_ they're basically replacing the folder deal with a tree, 
big deal is, you can see the instances and manage those, its supposed to make it easier to manage.
my point is, large projects are going to go in the double digits, and a scene tree would help with that
problem. ease of management and general convenience is why i came up with this idea.

**Comment by voithos** [comment]
Why would scenes need a separate tree view? Shouldn't the `FileSystem` tree already allow you to organize the scenes however you want?

**Comment by asheraryam** [comment]
I do agree that perhaps godot needs an advanced way to view scenes for scaleability eventually.

However note that there is a Quick Switch Scene feature that I always use to navigate between my 10-20 scenes, I almost never press on the horizontal tab bar anyway.

e.g. Ctrl + Shift + O for scenes and Ctrl + Alt + O for scripts.

**Comment by Calinou** [comment]
I'll close this issue as there's no clear consensus or use cases outlined.
