### ISSUE TITLE
Manipulating a large number of keyframes will stall the editor and create an infinite output of console messages.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#25144]
**Godot version:**

d8b702b

**OS/device including version:**

Win10 64bit

**Issue description:**

When selecting and dragging a large number of keyframes in the AnimationPlayer, the editor will stall and suspend, while the console will endlessly spam a message.

![godot_master_2019-01-19_21-24-43](https://user-images.githubusercontent.com/13004169/51431592-bcebf180-1c33-11e9-8c23-489efd2f340c.png)

This I think is where it goes at least: https://github.com/godotengine/godot/blob/6d8083ea656d1dce5c00257f308e464d1d8feae2/core/message_queue.cpp#L212-L216

Too hard to say for sure, but it may also be in the neighborhood of this issue:  https://github.com/godotengine/godot/issues/24829

That issue involves a sudden crash though.

**Steps to reproduce:**

Use the project below, select all keyframes and drag them about.  After a moment it should become unresponsive, this is when the messages should begin flooding in.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/51431597-cffec180-1c33-11e9-9856-54489c0f70fc.gif)

**Minimal reproduction project:**

[3.1 Keyframe Issue.zip](https://github.com/godotengine/godot/files/2775904/3.1.Keyframe.Issue.zip)

**Comment by reduz** [comment]
This should be fixed in 4a24ba6e77c7128e64dee31cf05f6960abdb8108
If there are other similar use cases generating the problem, please open a new issue.

**Comment by avencherus** [comment]
Will do, if anything related appears in the future.

Rebuilt the master, looking good now, seems stable and performs smoothly.
