### ISSUE TITLE
Yields in tool scripts can sometimes cause silent crashes.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#25143]
**Godot version:**

d8b702b5660ee4c8a072ecde0c7d6a85bf8f7337

**OS/device including version:**

Win10 64bit

**Issue description:**

Splitting out from this issue, as it appears to be different:  https://github.com/godotengine/godot/issues/24829#event-2083621005

Been having issues where `yield()` seems to combine unfavorably with things in tool script.  It isn't the complete source of the problem, so sometimes it causes an issue, sometimes not.  It seems like a very hard to reproduce timing issue.

It has been highly resistant to being reproduced.  Even when I copy the project, when running the copy the crashing stops... ???

1. When I open this scene with a tool script yield in `_ready()` and save immediately, the editor will crash.  Remove this yield line, all works fine.
![sublime_text_2019-01-18_00-52-40](https://user-images.githubusercontent.com/13004169/51354909-e2ef8580-1abd-11e9-834a-f87f698bd8e5.png)

2. I had written a tool to inspect editor variables in the dock.  There is an `unwatch()` method in a singleton called Editor (editor_core.tscn / editor_core.gd).  Leave the yield line in and comment this method out, crashing stops.
![sublime_text_2019-01-18_00-51-19](https://user-images.githubusercontent.com/13004169/51354905-e256ef00-1abd-11e9-982b-d069ca340c84.png)

3. The editor_watch.gd script is something that is loaded by a plugin into the dock.  So I went to check it out, comment this method out.  Crashing stops.  I tried making it just `return`, but still crashes.  It gets really weird next.
![sublime_text_2019-01-18_00-51-35](https://user-images.githubusercontent.com/13004169/51354906-e256ef00-1abd-11e9-8815-12cdfea53146.png)

4. From earlier tests I had the inspector commented out...  It's not even being loaded, but doesn't seem to matter.  Bring it back, or leave it out, still crashes.
![sublime_text_2019-01-18_00-51-57](https://user-images.githubusercontent.com/13004169/51354907-e256ef00-1abd-11e9-9e47-7b035ccfbcb3.png)

I will close this thread at some point in the future if things tend to be stable.  It may be tied to other editor crashing issues that have since been resolved.

Here are some of the stack traces I've gotten in the past revolving around this problem.  Though they may be related to the animation player issue referenced in this issue.

![50797940-2e947900-12df-11e9-83a5-10dea635fe74](https://user-images.githubusercontent.com/13004169/51431529-e6584d80-1c32-11e9-8f55-3fb091aa1fe0.jpg)
![51295727-9e161100-1a21-11e9-8588-87c8d309ccc8](https://user-images.githubusercontent.com/13004169/51431531-e8221100-1c32-11e9-949a-db5daccd319f.png)

**Steps to reproduce:**
Precise steps are unknown still.

In this one situation, I had it caused by opening a scene with that yield statement, then saving immediately resulted in a crash:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/51355480-fb609f80-1abf-11e9-8d29-cf3e0af0ae49.gif)

**Comment by hasahmed** [comment]
It seems to be that yield sometimes causes silent crashes even when not `tool`.

**Comment by avencherus** [comment]
I think this has since been resolved.  I haven't had this issue since the time around when it was reported.  I can't point to anything specific that fixes it, since I failed to isolate it, and can't do any comparisons.
