### ISSUE TITLE
Ability to see meshes and textures right inside gdscript editor

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [godotengine/godot#25153]
Possible ways this could work:
- when you mouse over a recognized texture or mesh you can see a small preview tooltip under the mouse cursor
- recognized textures or meshes will insert a small image preview inside the script beside or above the texture or mesh object  inline as if the image is part of the script 

The closest implementation to this I can think of is HolyC from TempleOS in which 3d objects or textures show up right inside the programming text editor.

**Comment by jonbonazza** [comment]
What value does this provide?
