### ISSUE TITLE
Rect2 calculating size incorrectly

### ISSUE THREAD

**Issue by KitleOyun** [godotengine/godot#25159]
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10

**Issue description:**
Rect2's size does not take the portion on the negative side of the x and y axes into consideration when calculating it's size.

**Steps to reproduce:**

  Code:
```
        var test_rect = Rect2(Vector2(-2000, -1), Vector2(1, 1))
	print("rect: " + str(test_rect))
	print("rect size: " + str(test_rect.size))
	print("rect area: " + str(test_rect.get_area()))
```

  Output:
```
       rect: (-2000, -1, 1, 1)
       rect size: (1, 1)
       rect area: 1
```

  Expected Output:
```
       rect: (-2000, -1, 1, 1)
       rect size: (2001, 2)
       rect area: 4002
```

**Minimal reproduction project:**
  see above code

**Comment by akien-mga** [comment]
The output you get is correct.
`Rect2`'s constructor is `Rect2(Vector2 origin, Vector2 size)`, so your rectangle is a 1x1 rectangle with origin `-2000, 1`.
