### ISSUE TITLE
CPUParticles2D unexpected behavior with tangential acceleration curve

### ISSUE THREAD

**Issue by Ploppy3** [godotengine/godot#25167]
**Godot version:**

3.1-beta.2

**OS/device including version:**

Windows 10
GTX 1060 (417.71)

**Issue description:**

When adding a _flat_ tangential acceleration curve to a CPUParticles2D, particles starts spinning when I don't expect them to spin since there shouldn't be any force applied.

From this: 
![mygif](https://user-images.githubusercontent.com/7990765/51439598-206e3180-1cbd-11e9-8a51-bb94de5ccd3a.gif)

To this:
![image](https://user-images.githubusercontent.com/7990765/51439568-bce40400-1cbc-11e9-852a-36f3bea18570.png)
![mygif](https://user-images.githubusercontent.com/7990765/51439558-9a51eb00-1cbc-11e9-9b16-e82bfbc4cf7d.gif)

**Steps to reproduce:**

- Create a CPUParticles2D
- Add flat tangential acceleration curve

**Minimal reproduction project:**

[test-particles.zip](https://github.com/godotengine/godot/files/2776614/test-particles.zip)

**Comment by clayjohn** [comment]
I ran your example scene. In it you have the curve set to 1 on either end. So, although it is flat, it is a flat 1 unit of tangential acceleration. If you want the curve to have no effect it should be set to 0.

**Comment by Ploppy3** [comment]
@clayjohn Good catch, it was quite hard to notice due to the scale of the chart.
