### ISSUE TITLE
Project settings search results should be hidden when the button is unpressed

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#25160]
**Godot version:**
3.1-beta2

**OS/device including version:**
Win 7 64-bit

**Issue description:**
After unpressing the "Search" button search mode is still active. To fix it, one needs to press "Search" again and erase the string being searched.
In my opinion, it should store the search string, but deactivate when the button is unpressed. Or for quick fix, just erase the string when the button is unpressed.

**Steps to reproduce:**
1. Go to Project settings
2. Press "Search" button
3. Type "abc" in the search field
4. Unpress the "Search" button
5. Nothing is shown in the settings

**Comment by mattintriago** [comment]
Me and my software engineering group will be working on this issue

**Comment by starry-abyss** [comment]
@mattintriago Note that #25720 aims to address it already. Didn't test it though yet, and maybe it's possible to fix it the long way, so the search string is preserved...
