### ISSUE TITLE
match does not work as expected with release export

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#25165]
**Godot version:**

3.1.beta 7f9209781

**OS/device including version:**

Kubuntu 18.10, Android 8.0

**Issue description:**

`match` key doesn't match with release export, but work with debug export.

**Steps to reproduce:**
```gdscript
extends Node2D

func _ready():
	var test_key = "test_key"
	match test_key:
		"test_key":
			printt("match key")
```

it prints "match key" with debug export but not with release export.

**Minimal reproduction project:**

**Comment by volzhs** [comment]
cc @vnen

**Comment by volzhs** [comment]
it happens recently.
it probably caused by some modification of gdscript part in recent.

**Comment by ProbDenis** [comment]
I can confirm this. Apparently "match" doesn't work at all in the exported release build, but it does work in the debug build.
