### ISSUE TITLE
Make "Export with Debug" more visible to the user

### ISSUE THREAD

**Issue by exts** [godotengine/godot#25170]
**Godot version:**
3.1 beta2

**OS/device including version:**
Windows 10 64bit

**Issue description:**
I notice this question coming up a lot "does exports always show a terminal?" Well if you look, you'll notice this text is almost invisible to the user. The color is close to the background color and the on/off button is way to the right which in theory should be obvious, but it clearly isn't obvious to the user because it's a question that constantly comes up on the discord

![image](https://user-images.githubusercontent.com/16387107/51442245-8bf5d600-1ca0-11e9-8df7-11905f6b6aab.png)

**Comment by paulloz** [comment]
That's related/duplicate to #20219.
