### ISSUE TITLE
Collision with one-way colliders prints "margin: 1" to output

### ISSUE THREAD

**Issue by sicienss** [godotengine/godot#25172]
**Godot version:**
3.1 beta downloaded from [here](https://hugo.pro/projects/godot-builds/)

**OS/device including version:**
Windows 8 / Toshiba Satellite

**Issue description:**
Whenever my player, a `KinematicBody2D`, collides with something with one-way collision (whether it's a `StaticBody2D` with a one-way `CollisionShape2D`, or a `TileMap` tile with `shape_one_way = true`), the output is flooded with "margin: 1".

I have confirmed this is a reference to the `one_way_collision_margin` property, because if I change this property, the output changes to match.

I am unsure why it's being constantly printed.

**Steps to reproduce:**
I have not yet been able to reproduce in a minimal project, but will continue to try.

**Comment by eon-s** [comment]
Is this line
https://github.com/godotengine/godot/blob/d8b702b5660ee4c8a072ecde0c7d6a85bf8f7337/servers/physics_2d/space_2d_sw.cpp#L766

And looks like was added for debugging purposes when re-adding the margin, I think it can be safely removed.
