### ISSUE TITLE
Enhancement suggestions for the filesystem dock

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2517]
That topic is of course "IMO".

When opening a Godot project in current master, the filesystem dock looks like that:
![fs1](https://cloud.githubusercontent.com/assets/4701338/10059235/25382ab2-624a-11e5-9bbf-c3419d997478.jpg)
I do believe that not so long ago, it used to also show files and not only folders. One could expand folders in the tree to access files directly with single clicks.

Now one can only double click to open folder, and then get:
![fs2](https://cloud.githubusercontent.com/assets/4701338/10059267/4f1355e6-624a-11e5-8cf4-71eb42d3ee79.jpg)
Here the interface changes completely, even the buttons at the top are different. With a bit of tweaking one can find that the tree icon on the left brings back to the first screenshot, and there again there is no obvious way to switch back to the non-tree view apart from opening a folder.

Then by clicking the "list" icon one can get the listing without preview, which is better IMO for projects with many files (that's of course subjective, so it's nice to have both possibilities).
![fs3](https://cloud.githubusercontent.com/assets/4701338/10059306/845c194a-624a-11e5-88f8-c07fae1a87d3.jpg)

So I see actually two "problems":
- Files missing from the tree is IMO a regression. Browsing the filesystem via the tree view is the most effective in my workflow.
- The fact that UI buttons differ in the tree view and in the other views is a bit confusing IMO. It would probably be better to have the same icons, and be able to switch between all three layouts using three icons.

**Comment by okamstudio** [comment]
I was thinking of adding a split mode, like Unity or Unreal.. But that
takes up more horizontal space. This view was created because the single
tree got too inefficient on large projects

**Comment by bojidar-bg** [comment]
:+1:

**Comment by akien-mga** [comment]
> This view was created because the single tree got too inefficient on large projects

I would like to have the possibility to get the old tree view with both folders and files though, for my relatively small project it was really useful. Right now it's annoying to have to double click my scenes directory first, and then either cope with big icons that I'm not fond of or click on the "list" view, before I can find another scene to open.

Previously I just had to expand the scenes folder and double click the scene in the tree.

**Comment by reduz** [comment]
remember that go go between scenes you also have the shift+ctrl+o workflow
which is pretty efficient, also for small projects you should be able to
see the scenes you are working with in the tabs above

**Comment by akien-mga** [comment]
> remember that go go between scenes you also have the shift+ctrl+o workflow which is pretty efficient

Indeed, I should learn to use it more, it should be perfect for what I need.

> also for small projects you should be able to see the scenes you are working with in the tabs above

Yes once I've opened my scenes I can easily switch using multiscene editing; on the other hand when I open my project I always have only one scene opened, so I still have to open the scene I want to look at if it's not the default one. But with shift+ctrl+o it should be just fine.

**Comment by jackmakesthings** [comment]
I'm with OP on this - I can see the merits of both views and why you might want one or the other, but the forced toggling between them is kind of frustrating, as is the inability to view files in the tree list. And the buttons randomly changing is disorienting.

A few possible improvements:
- allow the user to choose between showing only folders in tree view or showing folders and files (could be an editor settings thing, or a panel option)
- don't automatically switch into big-preview-icons mode when viewing a folder's contents - personally I'm not a fan of that view, but if people do like it, it could still be an available option. I'm thinking of how the Mac Finder handles different views (assuming there aren't per-directory preferences set, once you pick a view via icon, you stay in it until you pick a different view.)

![image](https://cloud.githubusercontent.com/assets/3606708/10144876/07b87170-65ee-11e5-979c-f84cfc810b40.png)

- If the UI bar (with the icons, current path, etc) starts to get crowded, maybe some functions could move to the bottom of the panel, as they do elsewhere?

I'd like to put together/illustrate some options for this with more detail, if there's a chance they'd be used; seems like the UI has been in a state of "don't bother, it's all going to totally change soon!" for a while, is that still the case? If so, how's it coming? For that matter - what's the best way for someone to go about contributing/proposing UI or other visual improvements? I'm sure I'm not the only designer who watches this repo... :art:

**Comment by akien-mga** [comment]
An editor setting was added in #3083 to select whether the folder view should show previews or lists, so part of this issue has been addressed.

What's left IMO is to add another editor setting and likely a button in the filesystem dock that would enable to see folder files in the tree view.

Also, the folders in the tree view should be folded by default IMO. (not sure this part would need an editor setting, it seems like a pretty sensible default to me - but if some prefer that the folders are all expanded, I guess an editor setting could be added too).

**Comment by djrm** [comment]
Now there is a better FileSystem dock (at least when it is on full height).

**Comment by akien-mga** [comment]
I'll close this issue as I made it a bit too broad, and the filesystem dock changed lately. There are still a couple things I'd like to see improved, but I'll do proper issues for each.
