### ISSUE TITLE
Camera2d parallax background and zoom behaves strange

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#25176]
it behaves strange, i have my set to ignore camera zoom,
the camera zoom adds some motion to the parallax, is this supposed to be like this ??
@akien-mga @mhilbrunner 
using 3.1 beta 2
![paralaxbug](https://user-images.githubusercontent.com/13393087/51430112-73d97480-1c16-11e9-9748-2a930d369e91.gif)

_Originally posted by @Norrox in https://github.com/godotengine/godot/issues/11555#issuecomment-455798195_

example project here:
[parallax bug.zip](https://github.com/godotengine/godot/files/2777153/parallax.bug.zip)

**Comment by Norrox** [comment]
Have anyone taken a look at this yet? ☺️

**Comment by Norrox** [comment]
Any ideas guys? , soon i celebrate 1 yr with this bug 🎉🎉😂

**Comment by akien-mga** [comment]
Still reproducible in the current `master` branch.
