### ISSUE TITLE
Exporting a game with a custom class with icon causes a crash

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#25171]
![screenshot 1](https://user-images.githubusercontent.com/15088582/51443644-6d1d3100-1cec-11e9-8dd1-6ba331d3d59f.jpg)

**Godot version:**
3.1 beta 1 and beta 2

**OS/device including version:**
Windows 10 .exe file

**Issue description:**
When making a custom class with class_name syntax, the game wont run when exported with a custom icon. Works fine when not using a custom icon. Project runs fine from within editor also.
When running the exported .exe file in Windows 10, the game crashes. Not tested for other export targets.

**Steps to reproduce:**
Run the attached project, export project and try to run it. 

**Minimal reproduction project:**
[IconBug.zip](https://github.com/godotengine/godot/files/2776932/IconBug.zip)

**Comment by akien-mga** [comment]
CC @willnationsdev @vnen. I don't think the script icon code should be used outside `TOOLS_ENABLED` at all.

**Comment by willnationsdev** [comment]
I remember when I tried to do the editor icon function refactoring, I tried to remove as many references to it as I could that seemed unnecessary. I don't even think it is really needed anymore if the only thing that was using it in the past was custom types and those should now be included in the new EditorNode methods directly.

I'll try to look at this issue today.

**Comment by akien-mga** [comment]
Just delete the obsolete `.gen.cpp` file.
