### ISSUE TITLE
Assign value to dictionary variable the same as assign reference variable

### ISSUE THREAD

**Issue by TyTYct** [godotengine/godot#25179]
**Godot version:**

3.0.6 and 3.1 beta 2

**OS/device including version:**

Windows 10 64 bit

**Issue description:**

I assign 2 variabe to a base dictionary
	Dictionary_1 = Dictionary_Base
	Dictionary_2 = Dictionary_Base

when I change 1 item in one dicitonary variable.
	Dictionary_1.Item += 1
then. 3 dictionaries are change.

It look like assign reference variable. 3 variables use one memory address and when change value at one variable then all variables use that address change also.

I can not assign dictionary variable and change that variable and keep value of base dicitonary variable
**Steps to reproduce:**
```
var Dictionary_Base = {
	"Item": 10,
	"Hit" : 100
}
var Dictionary_1
var Dictionary_2

func _ready():
	Dictionary_1 = Dictionary_Base
	Dictionary_2 = Dictionary_Base
	
	printt("before", Dictionary_1.Item, Dictionary_2.Item, Dictionary_Base.Item)
	
	Dictionary_1.Item += 1
	
	printt("After", Dictionary_1.Item, Dictionary_2.Item, Dictionary_Base.Item)
```
**Minimal reproduction project:**

**Comment by mrcdk** [comment]
Dictionaries are always passed by reference https://docs.godotengine.org/en/latest/classes/class_dictionary.html#description You'll need to `duplicate()` it

**Comment by TyTYct** [comment]
Thank you
