### ISSUE TITLE
Problem exporting PackedScene

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#25187]
**Godot version:**
Godot 3.1 Beta2

**OS/device including version:**
Mac OS Mojave and Windows 10

**Issue description:**
When I export a PackedScene it doesn't get assign!

I export a variable:
<img width="353" alt="captura de ecra 2019-01-21 as 13 09 20" src="https://user-images.githubusercontent.com/10358443/51476665-15c7a100-1d7e-11e9-8d0c-7eacbc750658.png">

I drag and drop a packed scene in the inspector:
<img width="346" alt="captura de ecra 2019-01-21 as 13 09 29" src="https://user-images.githubusercontent.com/10358443/51476688-22e49000-1d7e-11e9-9070-255b7f2bd17b.png">

Run the game and "null" is printed:
<img width="458" alt="captura de ecra 2019-01-21 as 13 09 34" src="https://user-images.githubusercontent.com/10358443/51476717-40195e80-1d7e-11e9-863f-1684b5668a3c.png">

**Comment by volzhs** [comment]
would you provide a minimum sample project?

**Comment by xDGameStudios** [comment]
> would you provide a minimum sample project?

While creating a minimum sample project I realized that:

I can access node_scene in the "_init" function it needs to be in the "_ready"!
My bad!! Can close this thread!

**Comment by volzhs** [comment]
ok then. :smile:
