### ISSUE TITLE
2D Collision broke

### ISSUE THREAD

**Issue by davismiculis** [godotengine/godot#25181]
**Godot version:**
3.1 latest master

**OS/device including version:**
macOS 10.14.2 (unrelated I think)

**Issue description:**
Hi, I think recent commits broke 2d collision:

![](https://media.giphy.com/media/7NOwbx0SH8AIoP6R9x/giphy.gif)

Perhaps this commit - https://github.com/godotengine/godot/commit/d8b702b5660ee4c8a072ecde0c7d6a85bf8f7337 ?

**Steps to reproduce:**
Fastest way is to create tilemap with collision, draw a simple layout.
Create kinematicbody2d with collision, then just move_and_slide around

**Minimal reproduction project:**
Cannot create right now. Will try later if needed.

**Comment by reduz** [comment]
Please create a test project since everything works fine for me.

**Comment by Jjony-dev** [comment]
I has same problem when create tilemap in previus version and opened with master branch, i see in tilemap  shape_one_way is checked, but no problem if creates de tilemap in master branch

**Comment by CakHuri** [comment]
I face the same problem, @reduz 
Just use https://github.com/godotengine/godot-demo-projects/tree/master/2d/platformer to test.

![collision is broken in master branch](https://user-images.githubusercontent.com/44079549/51503850-042ed980-1e10-11e9-96f8-9a6515af6886.png)

**Comment by avencherus** [comment]
Very much confirmed in: 0b0dba38c766a06f169fb492cc6f8c7c3e444de5

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/51509115-b65ea500-1e00-11e9-8730-e4c5d06501af.gif)

**Comment by reduz** [comment]
This is fixed, but note that, if you re-saved a tilemap while this bug was going on, all tiles will have one way collision turned on. You will need to edit them one by one and toggle it off (or edit the .tscn / .tres and do mass replace for occurences of "one_way")

**Comment by davismiculis** [comment]
@reduz thanks for the info!
