### ISSUE TITLE
Runtime error with self in setter and getter

### ISSUE THREAD

**Issue by FlamyAT** [godotengine/godot#25189]
**Godot version:** 769341e

**Issue description:** 
Using `self` in either the getter or setter will result in the following error:
`Parser Error: Must use 'test' instead of 'self.test' in setter.` 
(Stacktrace: `E 0:00:00:0448   Condition ' _debug_parse_err_line >= 0 ' is true. returned: __null
  <C Source>     modules/gdscript/gdscript_editor.cpp:321 @ debug_get_stack_level_instance()`)

**Steps to reproduce:**
Create a node with following script: 
```extends Node

onready var test : bool = true setget set_test, get_test

func set_test(test : bool) -> void:
	self.test = test

func get_test() -> bool:
	return self.test```

**Comment by eon-s** [comment]
The error is self explanatory, you need to access the variable directly (use a different name for the parameter).

It will do an infinite loop if self on the setter is allowed (because it triggers the setter).
