### ISSUE TITLE
Can't export to zip or pck on Ubuntu

### ISSUE THREAD

**Issue by LuminousNutria** [godotengine/godot#25191]
**Godot version:**

3.0.6 64-bit

**OS/device including version:**

Ubuntu 18.04 64-bit 

**Issue description:**

Tried to export the game to a zip or pck file, but it just went back to the prior screen without apparently doing anything.

**Steps to reproduce:**
Go to Project >> Export >> Export PCK/Zip and try to export.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Did you configure any export preset?

**Comment by starry-abyss** [comment]
Likely a #24894 duplicate

**Comment by akien-mga** [comment]
Indeed, closing as duplicate of #24894.
