### ISSUE TITLE
Script editor auto-completion for function parameters

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#2519]
The script editor completes variable names, but not function parameters. It'd nice to have that too.

---

Say I have a code like this:

```GDScript
func my_func(parameter):
	var variable
```

With the current behavior, if I start typing `varia` it'll suggest `variable` as it was previously defined. If I start typing `param` it won't suggest `parameter`.

My proposition is that `parameter` should also be suggested for autocompletion.

**Comment by akien-mga** [comment]
What do you mean exactly? For me autocompletion of function parameters seems to work fine (at least when I edit a script attached to an open scene, so that completion of scene nodes and parameters work properly).

**Comment by vnen** [comment]
Update my original post with some clarification.
