### ISSUE TITLE
Skeleton2D bones can randomly break.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#25204]
**Godot version:**

0b0dba38c766a06f169fb492cc6f8c7c3e444de5

**OS/device including version:**

Win10 64bit.

**Issue description:**

@reduz 

Was reviewing the Skeleton2D / Bone2D system, after rigging up the bones and painting weight to one, I tested moving the Polygon2D around, and the bone in the upper front arm broke and stopped functioning.

![godot_master_2019-01-22_04-00-47](https://user-images.githubusercontent.com/13004169/51507961-08e99280-1dfc-11e9-9de0-e142274f72c1.png)
![godot_master_2019-01-22_04-01-15](https://user-images.githubusercontent.com/13004169/51507967-0dae4680-1dfc-11e9-8cc6-81d37673164f.png)

**Steps to reproduce:**
With a Polygon2D that is assigned a Skeleton2D, try moving it around until it breaks.

For reference the broken bone is **shoulder_f** in the project.

![image](https://user-images.githubusercontent.com/13004169/52779010-f86db600-304f-11e9-96b7-71f36aeb88d9.png)

**Minimal reproduction project:**

[Skel2D.zip](https://github.com/godotengine/godot/files/2781036/Skel2D.zip)

**Comment by reduz** [comment]
I tried and tried and can't reproduce this, could you make a video please?

**Comment by avencherus** [comment]
Sorry, seems to be alluding me as well.  Unfortunately, I won't have the time to look into it very much more for the foreseeable future.  We had to move forward with things on our current project, so we have dropped most of our plans for 2D skeletons.

I will periodically follow the feature's progress as it happens.  If anything comes up in the meanwhile I'll try to capture it.  👍

**Comment by reduz** [comment]
I may have fixed this, can you try to see if it works now?

**Comment by reduz** [comment]
I think I most likely fixed this last week, so if you find the problem again please reopen!
