### ISSUE TITLE
ImageTexture.image Object Reference ID increments indefinitely

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot#25209]
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10

**Issue description:**
Loaded ImageTexture.image object's ID increments indefinitely. It shouldn't increment, and instead the reference should remain static.

I have confirmed that this issue exists when exported to a windows executable.

I have not been able to confirm if this actually causes a memory leak/performance hit, or if it is purely cosmetic, although I'm not 100% sure how I'd do that.

**Steps to reproduce:**
Create a simple Sprite script that loads a PNG, creates an ImageTexture from the data, and applies that ImageTexture to a sprite. Then, execute a scene with this node and observe the ImageTexture in the Inspector via the Remote tab.

You will notice the number increments indefinitely. Additionally, you can print out the object in the console and confirm the behavior.
![Video of issue](https://user-images.githubusercontent.com/911508/51514696-af667100-1dc5-11e9-894f-be252949bf4a.gif)

**Minimal reproduction project:**
[ImageTextureIssue.zip](https://github.com/godotengine/godot/files/2781435/ImageTextureIssue.zip)

**Comment by DevinPentecost** [comment]
Hi,

I have confirmed the behavior is the same on Godot 3.1.stable.official. The object reference ID climbs indefinitely.

Thanks,
-Devin

**Comment by SIsilicon** [comment]
I too can confirm that this happens in Godot 3.2.1!

**Comment by severin-lemaignan** [comment]
Hitting the same issue here with Godot 3.2.1.

My use-case is a user uploading a (base64-encoded) JPG via a websocket to the game, that should then displayed as a texture, using the following code:
```
var jpg_buffer = Marshalls.base64_to_raw(image)

var img = Image.new()
img.load_jpg_from_buffer(jpg_buffer)

tex = ImageTexture.new()
tex.create_from_image(img)
```
The RID of `tex.image` keeps increasing, and I do not seem to be able to use the texture (always appears fully black).

**Comment by Zylann** [comment]
Still happens in Godot 3.3.2.

However this is likely a behavior of the `image` property getting triggered by debugging attempts. The instance ID of Image does not increase if you don't try to access the `image` property. In other words, you're fine as long as you don't try to spam access to the `image` property.

I guess Godot is re-creating a copy of it on each access. I thought it was cached somewhere, however it would also be understandable that caching does not always occur to save unused memory space (creating a texture from an image does not always mean you'll want to keep it in RAM indefinitely since textures are used in VRAM instead).

Minimal project:
[ImageTextureRemote.zip](https://github.com/godotengine/godot/files/6749968/ImageTextureRemote.zip)

**Comment by Calinou** [comment]
I can confirm this on `master` 9d1626b4d.

Output log from holding Space a few seconds in the above MRP:

```
Image instance ID: -9223371982010055304
Image instance ID: -9223371981993278118
Image instance ID: -9223371981976500902
Image instance ID: -9223371981959723686
Image instance ID: -9223371981942946470
Image instance ID: -9223371956122811024
Image instance ID: -9223371956106033808
Image instance ID: -9223371956089256592
Image instance ID: -9223371956072479376
Image instance ID: -9223371956055702160
Image instance ID: -9223371956038924944
Image instance ID: -9223371956022147728
Image instance ID: -9223371956005370512
Image instance ID: -9223371955988593296
Image instance ID: -9223371955971816080
Image instance ID: -9223371955955038864
Image instance ID: -9223371955938261648
Image instance ID: -9223371955921484432
Image instance ID: -9223371955904707216
Image instance ID: -9223371955887930000
Image instance ID: -9223371955871152784
Image instance ID: -9223371955854375568
Image instance ID: -9223371955837598352
Image instance ID: -9223371955820821136
Image instance ID: -9223371955804043920
Image instance ID: -9223371955787266704
Image instance ID: -9223371955770489488
Image instance ID: -9223371955753712272
Image instance ID: -9223371955736935056
Image instance ID: -9223371955720157840
Image instance ID: -9223371955703380624
Image instance ID: -9223371955686603408
Image instance ID: -9223371955669826192
Image instance ID: -9223371955653048976
Image instance ID: -9223371955636271760
Image instance ID: -9223371955619494544
Image instance ID: -9223371955602717328
Image instance ID: -9223371955585940112
Image instance ID: -9223371955569162896
Image instance ID: -9223371955552385680
Image instance ID: -9223371955502054023
Image instance ID: -9223371955485276816
Image instance ID: -9223371955468499600
Image instance ID: -9223371955451722384
Image instance ID: -9223371955434945168
Image instance ID: -9223371955418167952
Image instance ID: -9223371955401390736
Image instance ID: -9223371955384613520
Image instance ID: -9223371955367836304
Image instance ID: -9223371955351059088
Image instance ID: -9223371955334281872
Image instance ID: -9223371955317504656
Image instance ID: -9223371955300727440
Image instance ID: -9223371955283950224
Image instance ID: -9223371955267173008
Image instance ID: -9223371955250395792
Image instance ID: -9223371955233618576
Image instance ID: -9223371955216841360
Image instance ID: -9223371955200064144
Image instance ID: -9223371955183286928
Image instance ID: -9223371955166509712
Image instance ID: -9223371955149732496
Image instance ID: -9223371955132955280
Image instance ID: -9223371955116178064
Image instance ID: -9223371955099400848
Image instance ID: -9223371955082623632
Image instance ID: -9223371955049069200
Image instance ID: -9223371955032291984
Image instance ID: -9223371954998737552
Image instance ID: -9223371954965183120
Image instance ID: -9223371954948405904
Image instance ID: -9223371954931628688
Image instance ID: -9223371954914851472
Image instance ID: -9223371954898074256
Image instance ID: -9223371954864519815
Image instance ID: -9223371954847742608
Image instance ID: -9223371954830965392
Image instance ID: -9223371954814188176
Image instance ID: -9223371954797410960
Image instance ID: -9223371954780633744
Image instance ID: -9223371954747079303
Image instance ID: -9223371954730302096
Image instance ID: -9223371954713524880
Image instance ID: -9223371954696747664
Image instance ID: -9223371954663193223
Image instance ID: -9223371954646416007
Image instance ID: -9223371954629638800
Image instance ID: -9223371954612861584
Image instance ID: -9223371954579307152
Image instance ID: -9223371954562529936
Image instance ID: -9223371954545752720
Image instance ID: -9223371954512198288
Image instance ID: -9223371954495421072
Image instance ID: -9223371954478643856
Image instance ID: -9223371954461866640
Image instance ID: -9223371954428312208
Image instance ID: -9223371954411534992
Image instance ID: -9223371954394757776
Image instance ID: -9223371954361203335
Image instance ID: -9223371954344426128
Image instance ID: -9223371954327648912
Image instance ID: -9223371954294094480
Image instance ID: -9223371954277317264
Image instance ID: -9223371954243762823
Image instance ID: -9223371954226985616
Image instance ID: -9223371954210208400
Image instance ID: -9223371954176653968
Image instance ID: -9223371954159876752
Image instance ID: -9223371954126322320
Image instance ID: -9223371954109545104
Image instance ID: -9223371954092767888
Image instance ID: -9223371954075990672
Image instance ID: -9223371954042436240
```

**Comment by KoBeWi** [comment]
First time I see that ImageTexture has `image` property. It's not bound and exposed in a weird way.

AFAIK `get_image()` will fetch the texture data from GPU, hence why it's a new Image each time. We should probably document that and remove the "property".
