### ISSUE TITLE
Bone2D should link to Polygon2D

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#25205]
@reduz 

Was wondering if perhaps the Bone2D should be what a Polygon2D is linked to for skeletal deforms, rather than an entire Skeleton2D.

Seems like it would make more sense.  In this case it would bring in that bone and all its children, rather than having the whole skeleton, most of which would be ignored when weight painting.

I imagine doing it that way would also allow a Skeleton2D to be there then to provide a root transform for all the bones.

Right now I'm thinking the way I would best use this is to create one skeleton per part, and having it under some Node2D that can be used for an anchor to actually get the parts to move about more widely for character animation.

**Comment by mrcdk** [comment]
No, the way it's setup right now is correct. Remember that a `Polygon2D` deformation can be affected by more than one bone so you need to set the skeleton to be able to access all the bones and paint the weights that each bone will affect to each vertice of your polygon.

**Comment by avencherus** [comment]
@mrcdk Thanks for the response.  Yeah you are correct, I definitely misstated and misunderstood some things.  Upon re-reading, I think I was meaning to convey something else about a better way to link smaller pieces and parts together as a skeleton.

Such as a situation where you have disjointed parts that may be a Polygon with one or two Bones.  This would currently be done with multiple Skeletons.  So I think the terminology made the structuring feel odd, as a body wouldn't have multiple skeletons.  X)
