### ISSUE TITLE
Material not rendering over sky when using No Depth Test and Grow

### ISSUE THREAD

**Issue by DwanaG** [godotengine/godot#25201]
**Godot version:**
Godot 3.1 6fa632b

**OS/device including version:**
Windows 10 64-bits
NVIDIA GeForce GTX 660 Ti

**Issue description:**
When using a material with 'No Depth Test'  and 'Grow' options activated, it doesn't renders over the environment sky, only over other objects. This doesn't happen when using other types of environments. I made a test with a shader that modifies the vertex position and the same happens.

![untitled](https://user-images.githubusercontent.com/29492561/51500733-c9d42680-1d94-11e9-9542-f80b89619e51.png)

**Steps to reproduce:**
Add any mesh to the scene.
Add a SpatialMaterial to the mesh
Tick on Flags/No Depth Test
Tick on Parameters/Grow

**Minimal reproduction project:**
[MaterialDisappears.zip](https://github.com/godotengine/godot/files/2780613/MaterialDisappears.zip)

**Comment by clayjohn** [comment]
Note: This bug isnt present in GLES2. In GLES3 the grow parameter seems to make the object render transparent and thus get sent down the transparent pipeline.

**Comment by reduz** [comment]
Funnily enough, what you describe is the expected behavior but it should have also happened when grow was disabled too.
