### ISSUE TITLE
Selecting Tiles in New Tile Editor is Difficult or Impossible

### ISSUE THREAD

**Issue by JosephCatrambone** [godotengine/godot#25203]
**Godot version:**
v3.1.beta-1 Official

**OS/device including version:**
Windows 10 Pro

**Issue description:**
There is no easy way to cycle between tiles when using the new tileset editor.  The source seems to suggest that one should use the region tool and click on the tile that one desires to edit, but if two tiles overlap, one is likely to either redefine the region of the tile they're editing (losing work) or not select the tile beneath the selection.

**Steps to reproduce:**
Draw two overlapping regions in the tileset editor.  Attempt to switch from the latter region to the former.  It's not possible without moving the autotile region, selecting the other, then moving the second autotile region back and redoing the work.

**Suggested fix**
Simple fix: If a tile is selected and a click is performed, selecting a new tile should take precedence over moving or defining an autotile area.

Better fix: A spinner or preview of some sort to switch between the active tile.

[GodotIssueTileMapSelect.zip](https://github.com/godotengine/godot/files/2780785/GodotIssueTileMapSelect.zip)

The zip file contains a sample project and a video of me trying to illustrate the problem.

**Comment by MarianoGnu** [comment]
Selection tool button in action:
https://gyazo.com/dcdf184fb671a39356e757f369be029b
