### ISSUE TITLE
WebGL1: texImage2D with format DEPTH_COMPONENT may be called only with target TEXTURE_2D

### ISSUE THREAD

**Issue by santouits** [godotengine/godot#25219]
Firefox console shows this error: 
```Error: WebGL warning: texImage2D: With format DEPTH_COMPONENT24, this function may only be called with target=TEXTURE_2D, data=null, and level=0.```

 I guess it is because of this?
https://github.com/godotengine/godot/blob/8cc83accd3efa109cc37b81a04f822e01deda6e2/drivers/gles2/rasterizer_scene_gles2.cpp#L3150-L3152

because WebGL1 doesn't support depth_component in texImage2D function and target anything other than TEXTURE_2D

This extension allows it only for target TEXTURE_2D:
https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture
```The error INVALID_OPERATION is generated by texImage2D if the format parameter is DEPTH_COMPONENT or DEPTH_STENCIL and the target is TEXTURE_CUBE_MAP_{POSITIVE,NEGATIVE}_{X,Y,Z}. ```

I guess it needs a different way to do that in WebGL1
https://stackoverflow.com/questions/43634998/can-gl-depth-component-be-used-as-the-format-of-cubemaps
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D

**Comment by akien-mga** [comment]
Fixed by #25222.

**Comment by santouits** [comment]
Nope, my pr didn't fix that.

**Comment by akien-mga** [comment]
My bad, I saw `DEPTH_COMPONENT24` stuff in both and assumed it was related.

**Comment by reduz** [comment]
This code will not run on platforms that don't support write to depth

**Comment by muiroc** [comment]
On 6504b88547db63d9c39d378f535742e7b2825ca1 the errors are back, most likely with fb7c526ec4bdb9e9b0946092ef78efc5c8452968
Anyway even with these errors the scene still loads fine (at least in my case)
