### ISSUE TITLE
 Condition ' name == "" ' is true when new name contains only unallowed characters

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25226]
**Godot version:**
3.1 0b0dba3

**OS/device including version:**
Windows 10

**Issue description:**
When I try to change name node to empty name "" - then popup "No name provided" appear
When I try to change name node to "nodename//" then node change name to "nodename" and show popup "Invalid node name ..."
But when I try to change name of node to name which contains only unallowed characters, then popup "Invalid node name ..." is shown and also this error:
```
scene/main/node.cpp:930 - Condition ' name == "" ' is true.
```

**Comment by akien-mga** [comment]
You're a really good QA engineer of the "[ordering -1 beers](https://twitter.com/sempf/status/514473420277694465)" kind :D

> QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.
