### ISSUE TITLE
Script editor word wrap works with very low performance and cut last letter.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25224]
**Godot version:**
3.1 0b0dba3

**OS/device including version:**
Windows 10

**Issue description:**
When I zoom in script editor with word wrap setting enabled, then editor wait 2/3 second and then wrap words, which looks horrible - https://streamable.com/qwlqm

Also with big zoom last letter is cut (it cut 's' from 'change_scene' or 't' from 'PrzyciskStart') 

![afaffaffasfasfas](https://user-images.githubusercontent.com/41945903/51537298-6ad2e800-1e4e-11e9-875c-155910ee9b2b.png)

**Comment by bojidar-bg** [comment]
CC @ianb96

**Comment by ianb96** [comment]
Hi,
I'm not sure what I can do about the performance, the editor has to go through each letter of each line to find out where to wrap, and it does it every time the window is resized or zoomed. Maybe someone can go through and optimize it in the future (I don't have the time to do it now). 
[This part](https://github.com/godotengine/godot/blob/4f4e46edd539b0c26a6b086aa19c303b10de66b1/scene/gui/text_edit.cpp#L3811) of the code deals with wrapping a line when there isn't enough space for a natural break. I can give it a closer look later to find out the exact issue.

**Comment by qarmin** [comment]
For example Atom text editor do this so fast, that I can't almost see any freezing. - https://streamable.com/6r7gw.
I know that this program is dedicated to text operations, but I think that Godot can do this almost fast as Atom.

**Comment by IronicallySerious** [comment]
I am a bit new to the Godot UI so can anyone tell me how to enable text wrap in Godot? I wanted to test this but I can't find how this feature is enabled

**Comment by qarmin** [comment]
Open editor settings at the top of engine(Editor/Editor Settings).
Go to "Text Editor"/"Line Numbers"/"Word Wrap" and turn it on
