### ISSUE TITLE
Up arrow in Modulate and Self Modulate dialog does not work

### ISSUE THREAD

**Issue by Galileo53** [godotengine/godot#25228]
**Godot version:**
V3.1beta2

**OS/device including version:**
Windows 7

**Issue description:**
In the Inspector, at CanvasItem, when changing "Modulate" or "Self Modulate", a new window pops up where R, G, B and A can be set. On the right side beneath the number value, there is an up and a down arrow.
While the down arrow works, the up arrow has no reaction.

**Comment by akien-mga** [comment]
Indeed, there was an issue in `ColorPicker`, but it has been fixed already after beta2 with #25114.
