### ISSUE TITLE
move_and_slide_with_snap ignores RayShape collision shape in 3D

### ISSUE THREAD

**Issue by MrCrowley2** [godotengine/godot#25230]
**Godot version:**
3.1 Beta 1
(can't test in Beta 2 due to [25227](https://github.com/godotengine/godot/issues/25227)

**Issue description:**
When snapping to the floor the rayshape collision of kinematicBody 3D is ignored. Object snaps into the floor until i.e. the box shape of the 2nd collider hits the floor.

**Steps to reproduce:**
- Add boxshape and rayshape to kinematic body
- rayshape has to be lower than box shape
- move kinematicbody 3D to floor with move_and_slide_with_snap
- as soon as body snaps to floor, it sinks in to the box shape, ignoring the rayshape

**Minimal reproduction project:**
- red ball has box shape
- green ball ray shape
- yellow ball box and rayshape
- yellow ball snaps into the floor. (use Beta 1! In Beta 2 the Rayshape is broken)
[RayShapeBug.zip](https://github.com/godotengine/godot/files/2783263/RayShapeBug.zip)

Another thing I noticed is that the green ball (only rayshape) does not stand still on the floor. It jumps up and down a little bit.

**Comment by akien-mga** [comment]
The issue happens with both Bullet and GodotPhysics. Still reproducible in the current master branch (88a36e20).
