### ISSUE TITLE
Json file do not work on Android Platform

### ISSUE THREAD

**Issue by homarox** [godotengine/godot#25248]
**Godot version:**

3.1 beta 2

**OS/device including version:**

Linux, Window10, Android devices

**Issue description:**

I created local json file storage game maps information.
On Linux and Window, I easily get data by json_data_file.open("res://game_json.json", File.READ)
But on Android mobile, it's not working with json_data_file.open("user://game_json.json", File.READ)

**Steps to reproduce:**
1. Create 1 json file
2. Set Read mod
3. Get data
`json_data_file = File.new()`
`json_data_file.open("res://game_json.json", File.READ)`
`var data_text = json_data_file.get_as_text()`
`var data_parse = JSON.parse(data_text)`
`json_data_file.close()`
`DataJson = data_parse.result`

**Minimal reproduction project:**

**Comment by Calinou** [comment]
You want to use `res://` on Android too, make sure to add `.json` as a non-resource export filter in the Export dialog.

**Comment by homarox** [comment]
> You want to use `res://` on Android too, make sure to add `.json` as a non-resource export filter in the Export dialog. `user://` is intended to be used for user configuration/data, it doesn't contain your project's data.

Oh, that's work after adding .json as a non-resource export filter and using `res://` (`user://` does not work, I have no idea.)
