### ISSUE TITLE
Resource paths with extraneous directory separators can't be matched to the imported asset

### ISSUE THREAD

**Issue by Rmiller5466** [godotengine/godot#25240]
Godot Version: 3.0.6 Stable

Windows 10 Home

The project works fine when running from the Godot editor, but upon exporting, I receive the error: 
ERROR: No loader found for resource: res://assets//coin.png
   At: core/io/resource_loader.cpp:186
I understand this is a topic that has been brought up many times, but I've searched and I haven't been able to find a solution yet.  I've checked file paths and made sure all scenes had the correct content.  It is confusing me cause some resources load meanwhile others don't.  
Some help debugging this would be greatly appreciated.  

Here are the complete files for the project (This project is from a Packt book on learning Godot): 
[Maze.zip](https://github.com/godotengine/godot/files/2785028/Maze.zip)

Thank you

**Comment by akien-mga** [comment]
The problem is that you're using `//` as directory separator, while it should be `/`:
> `res://assets//coin.png`

Your `coin.import` file has a reference to `source_file="res://assets/coin.png"`, which doesn't match what you define in your `items/Pickup.gd` script.

**Comment by akien-mga** [comment]
The best solution is to avoid using extraneous `/`, but it could likely be better handled at the engine level, with a recursive replacement of `//` by `/` (after having replaced the Windows `\\` by `/`).

Using multiple directory delimiters seem to be valid on Unix:
```sh
$ mkdir -p test//////hello
$ touch test//hello///////hi
$ ls test/hello/hi
test/hello/hi
```
And in URIs: https://github.com///godotengine////godot

**Comment by KoBeWi** [comment]
Works fine in 3.4
I remember there were some changes related to paths, so this was probably fixed.
