### ISSUE TITLE
"godotsharp_export - Method/Function Failed" emitted when any mono project exported

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#25246]
**Godot version:**
any 3.1

**OS/device including version:**
Win10

**Issue description:**
Even simple project emit this error to output 
![image](https://user-images.githubusercontent.com/3036176/51587008-6bbc5600-1ef0-11e9-979e-b4f33628e870.png)

**Steps to reproduce:**
Create a Mono project and try to export - even it will be successfull it will emit that error to output

**Comment by neikeq** [comment]
It should be printing an exception. Can you check the terminal?

**Comment by Chaosus** [comment]
![image](https://user-images.githubusercontent.com/3036176/51603254-52c89a80-1f1a-11e9-9f29-ca0bee0a091e.png)

**Comment by Chaosus** [comment]
I dont understand, even if I pushed it like its still emit this error

![image](https://user-images.githubusercontent.com/3036176/51603946-52c99a00-1f1c-11e9-8e16-028580b9c8ef.png)

**Comment by neikeq** [comment]
I think the debug folder name should be `data.mono.windows.64.release_debug` (instead of `.debug`). These two data directories must be placed in the Godot's templates directory next to the export templates.

**Comment by Chaosus** [comment]
Like this ?
![image](https://user-images.githubusercontent.com/3036176/51605031-e13f1b00-1f1e-11e9-91c1-18c5a7c61539.png)

**Comment by Chaosus** [comment]
Yeah, now I understand.. how to do it

**Comment by akien-mga** [comment]
The docs need to be updated though, they mention `debug` and not `release_debug`: http://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html

**Comment by neikeq** [comment]
Yes, the docs need to be updated. I will also make it fallback to `debug` if `release_debug` is not found.
