### ISSUE TITLE
many opened scene switch

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#2524]
How to switch between many opened scenes in editor?
![opened scenes bug](https://cloud.githubusercontent.com/assets/14325605/10078768/3965f074-62f3-11e5-80d7-8bd73cf10e7b.png)

**Comment by okamstudio** [comment]
this is a bug in the development version, will be fixed shortly (before
next release) :)

On Thu, Sep 24, 2015 at 1:03 PM, alabd14313 <notifications@github.com>
wrote:

> How sitch between many opened scenes in editro?
> [image: opened scenes bug]
> <https://cloud.githubusercontent.com/assets/14325605/10078734/fcfc138e-62f2-11e5-9ac8-eadfbf89a521.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2524>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment]
See #2396.
