### ISSUE TITLE
Shader vec2 parameter behaving as float in UI

### ISSUE THREAD

**Issue by ratsdiov** [godotengine/godot#2525]
I have a shader that has several vec2 parameters however 2 of them show as vec2 in the CanvasItemMaterial parameter UI but only accept a single value (left/right limit).  Note the type icon is for a vector but only a single value is editable.  These two started life as float parameters and it seems the change to being vec2 confused something.  Exiting and restarting godot did not fix it.  Running 1.1Stable on Windows 7 64 bit.

![image](https://cloud.githubusercontent.com/assets/4614207/10090079/057e9abc-62f9-11e5-93c7-fdb8dd914f65.png)

![image](https://cloud.githubusercontent.com/assets/4614207/10090082/0f3e7112-62f9-11e5-9797-6afb91d9b951.png)

They appeared like this in the scene XML:
![image](https://cloud.githubusercontent.com/assets/4614207/10090134/99cd475e-62f9-11e5-8f75-d0b2ffd61aba.png)

After manually editing the XML and reopening the scene, they show correctly and are editable:
![image](https://cloud.githubusercontent.com/assets/4614207/10090141/b494bc0c-62f9-11e5-9f35-04b7eef6519e.png)

![image](https://cloud.githubusercontent.com/assets/4614207/10090146/bd5464aa-62f9-11e5-80c8-5c062bae089d.png)

**Comment by bojidar-bg** [comment]
Ok, that seems to be a deserialization bug, when the type has changed..

**Comment by akien-mga** [comment]
Is this also valid in the current master branch/nightly builds?

**Comment by bojidar-bg** [comment]
Can't confirm on dde6396f221672d34d178c75f4080c1e87612aea

**Comment by akien-mga** [comment]
Let's assume it is fixed in master, feel free to reopen if it's not the case.
