### ISSUE TITLE
"Convert All" menu option for things like moving projects to Godot 2.0

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#2526]
Right now, I notice that when opening Godot 2.0 alpha, you have to save each scene instance individually to convert them to the new binary format (or otherwise using the new refactoring tools removes access to scene files among other things).

It would be nice to just have a *convert all* button for this case. Yes, it would take longer, but it would ensure there are no cases where something messes up due to binary versions being different from file to file (which would also apply to future upgrades beyond Godot 2.0).

I would also note, due to potentially long conversion times, you might want to give it a 'confirm' dialogue just in case it was accidentally clicked (or just disable it if the program cannot find any older binary versions within the files).

Thoughts?

**Comment by volzhs** [comment]
It would be better to save all scenes again to new 2.0 format if scene format is below 2.0 when opening project.

**Comment by bojidar-bg** [comment]
Note that a similar option would be nice for conversion to `.tscn` (#4736)

**Comment by akien-mga** [comment]
IMO this issue got superseded by #4736, so I'll close it to the profit of the latter. Feel free to comment if you don't agree though :)
