### ISSUE TITLE
Release build of my game crashes at startup

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#25261]
**Godot version:**
At b4ec37af2cc4a626aa46b9af341e6d5b9e0676ce, still present in current master

**OS/device including version:**
Win10

**Issue description:**
My game is crashed at startup when exported with mono template release build.
(Im unable to attach crash log cuz release build doesnt print anything). Its not happened at debug build.

**Steps to reproduce:**
Its not reproducable at simple project, and I dont know what in my game cause crash, but I detect that it start crashing from b4ec37af2cc4a626aa46b9af341e6d5b9e0676ce commit

**Minimal reproduction project:**
Sorry unable to give it cuz its still a private big project, and unable to reproduce it simply cuz I dont know what cause it

I will try to figure out what cause and try to fix the crash

**Comment by Chaosus** [comment]
(Still exist in 2c9536b655d006c697a3cf830ad3352f1a1ed9f2) It does not print any error to console if exported is debug, but it will print that error every time I run my project in editor
![image](https://user-images.githubusercontent.com/3036176/51615794-c4fca780-1f39-11e9-9930-6f28a062797a.png) so maybe its related...

**Comment by akien-mga** [comment]
Are you using GDScript, C# or both?

Can you check which commit of #25014 triggered the issue?

**Comment by Chaosus** [comment]
Yeah, I will check

**Comment by Chaosus** [comment]
Will check now(sorry was busy)

**Comment by Chaosus** [comment]
I think its not related to mono.. The crash caused by single #ifdef DEBUG_ENABLED at 8106 line at gdscript_parser.cpp, if I place it back to 8120 position it will not cause crashed

**Comment by Chaosus** [comment]
Yeah, I write multiple complex scripts and autoloads and something which looks and compiles correct cause this crash. Hope @vnen know how to fix it ), at least revert it back..

Commit - 573fab744736af10925490dec6387f24c26d5416

**Comment by Chaosus** [comment]
I can even give access to repo which contains the project to @vnen, if he needs it to fix this bug :)

**Comment by vnen** [comment]
Looked at the project but is difficult to check because I don't have mono setup here. But I'll undo the commit, some other stuff depends on it.

**Comment by Chaosus** [comment]
Yeah, thank you anyways !
