### ISSUE TITLE
Platformer 3D demo render glitch with GLES3

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#25267]
**Godot version:**
master (https://github.com/godotengine/godot/commit/2d57ec24609687756597cce1e47ea4712dea2666)

**OS/device including version:**
Arch Linux
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 

**Issue description:**
![platformer 3d](https://user-images.githubusercontent.com/34406967/51634614-f9319180-1f54-11e9-90ed-d8b8fa98e82a.png)

**Minimal reproduction project:**
Platformer 3D demo

**Comment by CptPotato** [comment]
Have you tried disabling depth pre-pass? Just a guess...

**Comment by LinuxUserGD** [comment]
@CptPotato I'm using 3d without effects. It doesn't happen with 3d.

**Comment by LinuxUserGD** [comment]
@eon-s Demos are from latest commit.

**Comment by LinuxUserGD** [comment]
Does also happen with the Kinematic Character demo.

**Comment by ca3games** [comment]
Can confirm on my geforce 210 sometimes the 3D meshes become black.

**Comment by somnivore** [comment]
I wonder if this is just an effect of mesa being bugged out right now

**Comment by reduz** [comment]
I am not able to reproduce this, and I tried it in a lot of hardware, did you change anything in the project by chance?

**Comment by LinuxUserGD** [comment]
@reduz Yes, I changed to 3d without effects in the project settings.

**Comment by reduz** [comment]
Oh nevermind, I misread that. Could reproduce it fine now, will work on it.
