### ISSUE TITLE
No way to save an animation from AnimationPlayer

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#2527]
I spent some time creating an animation in the player. Then I decided it'd be better to transfer it to another scene, so I save the animation... **except there's no button in the UI to do that!***

That's really disheartening, specially knowing that it was possible before.

You can create animations, duplicate, rename them and even load them from disk, but no way to save it. If there is, it's very hard to find, because I couldn't.

My workaround was to create a new one from the Inspector panel, save it, load it in the AnimationPlayer, copy the animation from the original and paste on the loaded one.

**Added some dramatic effect, as it was actually a very simple animation.*

**Comment by kubecz3k** [comment]
@vnen I assume you are using nighties? Since from what I remember in 1.1 this button is still there..?

**Comment by vnen** [comment]
In 1.1 the animation was shown both on the Inspector and on the Resources panels (in which you could save it). Now we don't have the Resources panel (and I don't miss it), but the animation is not opened in the Inspector.

I think the animation should be shown in the inspector **and** the player should have a _save_ button, since it already have a _load_ button.

**Comment by TotCac** [comment]
+1

**Comment by jackmakesthings** [comment]
+1

**Comment by akien-mga** [comment]
Fixed by 56b7567.
