### ISSUE TITLE
OptionButton item_selected signal sends an index even though IDs are defined

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#25273]
Godot 3.1 beta 2 and ab843b16984d8b62a1100d9b77d8b0dcdc4252bb (by looking at the code)

From the Q&A thread https://godotengine.org/qa/39689/optionbutton-passing-an-id-with-add_item

`OptionButton` has an `item_selected` signal, with a signature and description indicating that it "sends the ID of the item that was selected. If IDs were not used, the index is sent instead".

However, the value received is never the ID, it's always the index, which tremendously reduces the usability of IDs.

Test project:
[OptionButtonAlwaysSendsIndex.zip](https://github.com/godotengine/godot/files/2789445/OptionButtonAlwaysSendsIndex.zip)

**Comment by azagaya** [comment]
Hi, this also affects `item_focused` signal. I'm makeing a pull request to fix the docs instead to match real behaviour in order not to break compatibility with 3.0. Also ad a function `get_item_index` as suggested in irc.
