### ISSUE TITLE
3.1 Mono: Crash on project save

### ISSUE THREAD

**Issue by Bombfuse** [godotengine/godot#25288]
**Godot version:**
3.1 Beta 1

**OS/device including version:**
MacOS Mojave

**Issue description:**
Open the project, attempt to save the project, the editor crashes.

**Steps to reproduce:**
Change anything on a scene, then save.

**Minimal reproduction project:**
Project in question
[terra.zip](https://github.com/godotengine/godot/files/2792768/terra.zip)

**Error log** 
[1548349626.txt](https://github.com/godotengine/godot/files/2792771/1548349626.txt)

**Comment by Bombfuse** [comment]
![image](https://user-images.githubusercontent.com/26308406/51696291-003ebb00-1fba-11e9-9167-ab7bbe67753a.png)
native stacktrace

**Comment by Bombfuse** [comment]
Just upgraded to 3.1 Beta 2, and the bug also exists on this version.

**Comment by Bombfuse** [comment]
Bug exists on 3.1 beta 4 as well

**Comment by Bombfuse** [comment]
Can confirm this bug still exists on 3.1 beta 5

**Comment by Bombfuse** [comment]
Can confirm bug still exists on 3.1 beta 6

**Comment by MightyPrinny** [comment]
I couldn't replicate the crash, I deleted the .mono folder before opening the project, you should delete it when you update the engine to avoid issues and also make a backup of your .csproj in case it's overwritten.

**Comment by Bombfuse** [comment]
Deleted the .mono folder, problem still persists. It crashes on project save when you attempt to build the project.

**Comment by akien-mga** [comment]
I can't reproduce the crash either on Linux with 3.1 beta 6.

Could you try to temporarily rename your `~/Library/Application Support/Godot/mono` folder to see if it fixes the issue?

**Comment by Bombfuse** [comment]
Moved ```mono``` to ```mono_temp``` temporarily and the crash still exists

**Comment by neikeq** [comment]
Cannot reproduce on windows. I'll assume this is a macOS issue.

**Comment by neikeq** [comment]
Cannot reproduce on MacOS Mojave either (latest master)... If you can still reproduce it, can you give more details?

**Comment by Bombfuse** [comment]
Unfortunately, all of the information I posted is all of the information I can find. I'm starting to think that my personal Macbook Pro might have some issue causing this, as other Mac users haven't had these problems

**Comment by neikeq** [comment]
Could you check if by chance #26773 fixes this crash as well?

**Comment by akien-mga** [comment]
No answer so assuming fixed.
