### ISSUE TITLE
Question: The relationship between AutoTile.tres and AutoTile.tscn is strange .

### ISSUE THREAD

**Issue by Howld** [godotengine/godot#25285]
**Godot version: v3.0.6**
**OS/device including version: win7**

**Issue description:**
I have a scene named "AutoTile.tscn" with Sprite and resource named "AutoTile.tres" which is convert from Sprite. It's strange, if I add or remove collision in “AutoTile.tres" but the resource need convert again, otherwise the collision with others is not working. If anyone could explain why need convert again, and anyway to just save resource? Thanks! (Sorry for my poor English)

**Comment by akien-mga** [comment]
When you modify the source scene for your tileset, you should reexport it with `Scene > Convert To > TileSet`.

By default, it will try to merge the new TileSet with the existing one. If you want to erase and replace the existing TileSet resource, you can toggle off the "Merge with existing" option in the "Convert To > TileSet" dialog.

In the future, please ask questions on dedicated community channels: https://godotengine.org/community, in particular the Q&A platform: https://godotengine.org/qa

The GitHub issue tracker is only for actual bug reports, not for user support.
