### ISSUE TITLE
Nothing is rendered in a scene using WorldEnvironment in Canvas mode (regression from #25242)

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#25284]
**Godot version:**
3.1.beta cab45f2

**OS/device including version:**
OS: Windows 10 x64
GPU: NVIDIA GeForce GTX 750 Ti, driver: 417.71 WHQL

**Issue description:**
Adding a `WorldEnvironment` node to a scene and creating `Environment` with background mode set to `Canvas` causes all the nodes in the scene (viewport) to not render them:

![gif](https://user-images.githubusercontent.com/17108460/51684670-406f5f00-1ff5-11e9-8fb9-161cb71d660f.gif)

Regression from #25242.

@BastiaanOlij

**Minimal reproduction project:**
[world-enviroment-canvas-broken.zip](https://github.com/godotengine/godot/files/2792103/world-enviroment-canvas-broken.zip)

**Comment by reduz** [comment]
Reverted in #25295
