### ISSUE TITLE
3.1 NodePath inspector widget is less functional than previous 3.0 version

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#25289]
**Godot version:**
3.1 Beta 2

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
I have some usability issues with new with new NodePath inspector widget:
- [ ] There is no ability to copy the path
- [ ] It's impossible to quickly edit the path from keyboard (helpful when moving node in hierarchy, or when changing he name)
- [ ] It's impossible to link to a node that's in another scene
- [ ] It's harder to know where the NodePath actually is linking (only node name is visible, previously the last x characters from the path were visible + it was possible to make inspector wider to see more)
- [ ] It's impossible to highlight the target node to which this NodePath is linking
- [ ] It's impossible to link to a node that don't exists in editor

I think most of those issues could be solved easily by giving the ability to edit the path in old fashion way via text input field (that would allow to set any path user wants, as well as copy).

**Comment by GlaDos28** [comment]
I think notes about impossibility of editing NodePath as text are critical. This problem must be resolved as eartier as possible, because it causes a lot of inconvenience.

**Comment by akien-mga** [comment]
It's been a while since this issue was opened, it would be good to reassess whether the NodePath features in 3.5 and 4.0 are now sufficient.

**Comment by KoBeWi** [comment]
> There is no ability to copy the path

This was partially resolved with the property copy-paste, but you can't copy the path as text.

> It's impossible to quickly edit the path from keyboard (helpful when moving node in hierarchy, or when changing he name)

Irrelevant now, as paths auto-update on every operation.

> It's impossible to link to a node that's in another scene

Needs a proposal.

> It's harder to know where the NodePath actually is linking (only node name is visible, previously the last x characters from the path were visible + it was possible to make inspector wider to see more)

Full path appears in tooltip.

> It's impossible to highlight the target node to which this NodePath is linking

Proposal.

> It's impossible to link to a node that don't exists in editor

See 3)

> I think most of those issues could be solved easily by giving the ability to edit the path in old fashion way via text input field (that would allow to set any path user wants, as well as copy).

I think it would be a fine solution.
