### ISSUE TITLE
DiagonalMatrix and ReflectionMatrix

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2529]
It would be nice to have a function that creates a 3x3 (2x2) diagonal matrix from a 3D (2D) vector, and another (less popular) function that creates the [reflection matrix](https://en.wikipedia.org/wiki/Transformation_matrix#Reflection_2), given the surface normal of the reflection surface.

**Comment by reduz** [comment]
there are reflect() and slide() functions in Vector3, not sure if it's
worth much adding a linear transform for that.. what is the typical use
case? for the diagonal matrix you can already set the scale of an identity
matrix..

**Comment by seadra** [comment]
> you can already set the scale of an identity matrix

...and we can also create a matrix by hand. I had convenience matrix constructor. In fact, I should've mentioned a rotation matrix constructor too.

> there are reflect() and slide() functions in Vector3

Maybe I missed it but there is no reflect for matrices right?

An example of the use case for such matrices is in [this](http://www.godotengine.org/topics/11924?r=12183#message-12183) forum thread.

**Comment by reduz** [comment]
don't see the problem:

var diagm = Matrix32().scaled( Vector3(2,3,5) )

godot is not meant to do reflections that way, and the new renderer will
probably not allow it either (or hide it from the user)

**Comment by seadra** [comment]
So does this mean that reflection shader I linked in my previous post will no longer work in the new renderer?

**Comment by reduz** [comment]
probably not, new renderer will already come with many options to obtain
environment reflections built-in

**Comment by akien-mga** [comment]
Based on the above comments, I guess there is no intent to implement this feature.
