### ISSUE TITLE
Empty exported NodePath points to self

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#25292]
**Godot version:**
Godot 3.1 beta 2 

**OS/device including version:**
Ubuntu 18.04 64bit

**Issue description:**
In Godot 3.1 when you create exported NodePath it will for some reason act like it's containing "." path. `NodePath.is_empty()` method will return false and  `has_node()` and `get_node()` will act like NodePath is containing "."

**Steps to reproduce:**
Short way:
1. Download reproduction project and run EmptyNodePathLinks2Self scene

Manual way:
1. Create new scene and attach following script to root node:
```
extends Node

export (NodePath) var path = NodePath();

func _ready():
	if(has_node(path)):
		print(get_node(path))
		print("I have nodepath to: ", get_node(path).get_name())
		assert false

```
2. Run the scene

**Minimal reproduction project:**
[EmptyNodePathLinks2Self.zip](https://github.com/godotengine/godot/files/2793056/EmptyNodePathLinks2Self.zip)

**Comment by akien-mga** [comment]
Doesn't seem to be a compat breakage though? Your project gives the same error in 3.0.6.

**Comment by kubecz3k** [comment]
@akien-mga you are right it must be an old issue I'm also able to reproduce in stable Godot, sorry for the inconvenience, I recognized it for the first time when I was testing that beta... will double check next time

**Comment by ptrojahn** [comment]
> `NodePath.is_empty()` method will return false
I can reproduce your bug, but not this part. Are you sure that is_empty returns the wrong value for you?

**Comment by kubecz3k** [comment]
@ptrojahn I can confirm that `is_empty()` works correctly in current main

**Comment by ptrojahn** [comment]
Alright. Then my patch should fix this issue.
