### ISSUE TITLE
BT_DEBUG is not defined in debug builds

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#25301]
Godot 3.1 ab843b16984d8b62a1100d9b77d8b0dcdc4252bb

I found out that in debug builds of Godot, Bullet may be asserting with `btAssert`, except it expands to no-op, because `BT_DEBUG` is not defined.
It seems only iOS builds (so far) keep the asserts defined regardless (due to how Bullet was written rather than the SCons script).

The result is, for example, someone testing on iOS found crashes that may be happening silently in general with heightmap terrains, where parameters are sent as garbage because `set_shape_data` was not called yet. There was garbage because *like every other shape*, the heightmap one doesn't initialize any of its members in its constructor... (see https://github.com/godotengine/godot/issues/25304)

Is there a reason why BT_DEBUG was not defined?

**Comment by akien-mga** [comment]
Temporarily disabled by #25500 as it exposed bugs and we're too close to the 3.1 release to handle them :)

Will be fixed anew after 3.1, when we'll revert #25500.

**Comment by madmiraal** [comment]
While working on #34210 I noticed that this requires DEBUG to be enabled not just BT_DEBUG.
