### ISSUE TITLE
discussion： i got a idea about ik

### ISSUE THREAD

**Issue by yuyubibibobibo** [godotengine/godot#25307]
Godot version：
3.1-beta2

Description:
unity asset final ik got source code，it is damn good，aim ik，foot ik...everyik is good for 3dgame，could anyone can move it to godot？sorry about my english。

**Comment by Ace-Dragon** [comment]
Have you tried Godot's new IK feature yet?
https://godotengine.org/article/skeleton-inverse-kinematic

**Comment by yuyubibibobibo** [comment]
@Ace-Dragon i know it ，but doc about 3dskeleton is none in lasted，i donot how to use it，i just think final ik is powerful and easy to use，and it got source code。

**Comment by williamd1k0** [comment]
>unity asset final ik got source code

I don't think that Final IK has source-code available. 🤔

**Comment by yuyubibibobibo** [comment]
@williamd1k0 it got source code bro
http://www.root-motion.com/final-ik.html

**Comment by bruvzg** [comment]
> @williamd1k0 it got source code bro

Final IK includes source code, but availability of the source code is completely irrelevant, it's still proprietary software. You can't include something into Godot itself unless it's released under free permissive license.

**Comment by yuyubibibobibo** [comment]
> > @williamd1k0 it got source code bro
> 
> Final IK includes source code, but availability of the source code is completely irrelevant, it's still proprietary software. You can't include something into Godot itself unless it's released under free permissive license.

i think it can offer some info and solution to ik solver，move to godot that doesn't mean copy code，it just learn from final ik......wish you can understand what i am saying.

**Comment by aaronfranke** [comment]
Of course. If there are any specific problems that you experience with Godot's IK, or any features that it does not have that Final IK does, then you can open an issue for that and the Godot devs will fix the bug or may add the feature.

**Comment by yuyubibibobibo** [comment]
> Of course. If there are any specific problems that you experience with Godot's IK, or any features that it does not have that Final IK does, then you can open an issue for that and the Godot devs will fix the bug or may add the feature.
> 
> But I don't think that digging through the source code to look for things like that is anyone's goal.

i got tons of problem，cuz i donot know how to use godot’s skeleton，if i cannot understand how it work，i must wish i could get a easy to used solution，like final ik.

**Comment by aaronfranke** [comment]
Then the issue is simply that the documentation is lacking. Head over to https://github.com/godotengine/godot-docs/issues
