### ISSUE TITLE
Inspector dock changes size when selected

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#25317]
**Godot version:**
 5b5db08

**Issue description:**
When clicking the Inspector dock, it will change its size. It only affects this dock alone, no matter its current location:
![peek 2019-01-25 11-00](https://user-images.githubusercontent.com/30739239/51747391-428ef780-20a1-11e9-9abe-7adf98e921ba.gif)

**Comment by akien-mga** [comment]
Might be related to #25281.

**Comment by azagaya** [comment]
Im trying to fix [#25281](https://github.com/godotengine/godot/issues/25281) and i found that the problem might be related to tab_container resizeing.. in tab_container.cpp there are these lines:

```
	for (int i = 0; i < tabs.size(); i++) {

		Control *c = tabs[i];

        if (!c->is_visible_in_tree())
        	continue;

		Size2 cms = c->get_combined_minimum_size();
        ms.x = MAX(ms.x, cms.x);
		ms.y = MAX(ms.y, cms.y);
	}
```
Not skipping invisible tabs solve this for me:

```
	for (int i = 0; i < tabs.size(); i++) {

		Control *c = tabs[i];

		Size2 cms = c->get_combined_minimum_size();
        ms.x = MAX(ms.x, cms.x);
		ms.y = MAX(ms.y, cms.y);
	}
```
However, i think this only makes the symptoms go away.. i think i need some feedback to go on.

**Comment by groud** [comment]
Related, if not duplicate, to #24572

**Comment by Zylann** [comment]
Still happens in Godot 3.1 RC1
![QCsLlevr0V](https://user-images.githubusercontent.com/1311555/54076148-fa6a1400-429f-11e9-9a7d-f621605ce1b1.gif)

**Comment by azagaya** [comment]
Yes, i made a pull request with a possible fix, but i think it was kicked to 3.2

**Comment by ScepticDope** [comment]
@azagaya where is your pull, I can't find it?

**Comment by azagaya** [comment]
Here!
https://github.com/godotengine/godot/pull/25353
