### ISSUE TITLE
Game crashes on android with DAE scene

### ISSUE THREAD

**Issue by metobalano6** [godotengine/godot#25312]
**Godot version:**

Godot 3.1 beta 2

**OS/device including version:**

Ubuntu/android 4.4.2/fire os 5.3.6.4

**Issue description:**

Game crashes after splash screen on mobile

**Steps to reproduce:**
Using OpenGL 2 Export a 3d project with a .dae scene with a mesh and skeleton (i am using better collada exporter) and run on device.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Is it really Android 4.0? We don't support that version, the AndroidManifest.xml should even prevent installing the game.

**Comment by metobalano6** [comment]
I’m sorry the correct version is android 4.4.2 and I also tested on amazon Fire with fire os 5.3.6.4

**Comment by volzhs** [comment]
can you provide logs from adb logcat?

**Comment by pablomz83** [comment]
Are you using textures in your 3D model?
If so then check the Texture Import tab and look for how it is imported; in Android this configuration will be fail. try unchecking "Detect 3D"

FAIL in android.

![image](https://user-images.githubusercontent.com/22731809/51781530-4fcad700-20df-11e9-8b10-1930c63eac0a.png)

This is fine.

![image](https://user-images.githubusercontent.com/22731809/51781573-e8f9ed80-20df-11e9-919a-95986a743b2c.png)

**Comment by akien-mga** [comment]
Please provide a project that can be used to reproduce the bug, otherwise we can't possibly debug it.
