### ISSUE TITLE
WebGL 1 Compressed texture loading error

### ISSUE THREAD

**Issue by muiroc** [godotengine/godot#25321]
**Godot version:**
export 6504b88547db63d9c39d378f535742e7b2825ca1
editor 95bd60f

**OS/device including version:**
windows 10
firefox 64.0.2
chrome 71.0.3578.98
in webgl with both angle and native gl backends

**Issue description:**
Textures imported as vram/compressed do not load, BUT SOME DO, for example the default icon.png loads and is visible.
Textures imported as lossless or uncompressed loads ok.

With GLES3/WebGL2 all texture import types works ok.

EDIT: tried with a jpg, just in case, same stuff

Some messages in the console:

(x6 times)
```
Error: WebGL warning: compressedTexImage2D: Bad `internalFormat`: RGBA
```
maybe unrelated, but new (x148+ times, hits max error count)
```
WebGL warning: bufferSubData: Offset+size passes the end of the buffer.
```

**Steps to reproduce:**
import a texture as vram apply to a material and a mesh, add camera
export and run project
see repro project,
there are 4 textures, 4 materials and 4 cubes, their import settings depends on the names
- top left -> custom texture lossless -> shows up, ok
- top right -> custom texture vram -> black cube, error
- bottom left -> godot icon lossless -> shows up, ok
- bottom right -> godot icon vram -> shows up, ok

**Minimal reproduction project:**
[bug_web_compressed_texture.zip](https://github.com/godotengine/godot/files/2796492/bug_web_compressed_texture.zip)

**Comment by akien-mga** [comment]
Indeed:
```
   creating: bug_web_compressed_texture/.import/  
  inflating: bug_web_compressed_texture/.import/icon.png-487276ed1e3a0c39cad0279d744ee560.md5  
 extracting: bug_web_compressed_texture/.import/icon.png-487276ed1e3a0c39cad0279d744ee560.stex  
  inflating: bug_web_compressed_texture/.import/icon_lossless.png-cb27e314456f7ce6de25e695f05b8ba2.etc2.stex  
  inflating: bug_web_compressed_texture/.import/icon_lossless.png-cb27e314456f7ce6de25e695f05b8ba2.md5  
  inflating: bug_web_compressed_texture/.import/icon_lossless.png-cb27e314456f7ce6de25e695f05b8ba2.s3tc.stex  
  inflating: bug_web_compressed_texture/.import/icon_lossless.png-cb27e314456f7ce6de25e695f05b8ba2.stex  
  inflating: bug_web_compressed_texture/.import/icon_vram.png-f430cef6e86315f48f008b0317401a3b.etc2.stex  
  inflating: bug_web_compressed_texture/.import/icon_vram.png-f430cef6e86315f48f008b0317401a3b.md5  
  inflating: bug_web_compressed_texture/.import/icon_vram.png-f430cef6e86315f48f008b0317401a3b.s3tc.stex  
  inflating: bug_web_compressed_texture/.import/tex_lossless.png-53fd46926797100c12ca05e7823a282b.md5  
  inflating: bug_web_compressed_texture/.import/tex_lossless.png-53fd46926797100c12ca05e7823a282b.stex  
  inflating: bug_web_compressed_texture/.import/tex_uncompressed.png-34d38c247a4c2790d1ffd29aa310cfaa.md5  
  inflating: bug_web_compressed_texture/.import/tex_uncompressed.png-34d38c247a4c2790d1ffd29aa310cfaa.stex  
  inflating: bug_web_compressed_texture/.import/tex_vram.png-16cf943c85d81845cf59c309bb69dc1f.etc2.stex  
  inflating: bug_web_compressed_texture/.import/tex_vram.png-16cf943c85d81845cf59c309bb69dc1f.md5  
  inflating: bug_web_compressed_texture/.import/tex_vram.png-16cf943c85d81845cf59c309bb69dc1f.s3tc.stex
```

@muiroc You need to enable import in ETC format in the project settings and reimport everything (simplest way is to delete `.import/`).

See #23650.

**Comment by muiroc** [comment]
Just tried but got the same results

Doesn't WebGL on desktop use S3TC/DXT? the weird part is that the compressed default godot icon is visible, while the "custom" compressed texture fails

**Comment by muiroc** [comment]
Maybe related, from the Editor inspector, the default godot (icon_vram.png, loads) is DXT5 RGBA8 while the other (tex_vram.png, fails) is DXT1 RGB8 (maybe thats why it says Bad `internalFormat`: RGBA)

but in gles3/webgl2 it loads, even if the enum EXT_COMPRESSED_RGB_S3TC_DXT1_EXT is never used...
