### ISSUE TITLE
iOS error spam "500" [GLES3]

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#25324]
**Godot version:**
Commit 3b2e854f4bbcac2f5ed752c95a7d2dbcd5f5f915

**OS/device including version:**
iOS, tested on iPhone 7 - Apple A10 GPU

**Issue description:**
Error log fills up with 500 error

Traced this down to the _copy_screen function here: 
https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_scene_gles3.cpp#L4058

This call tries to invalidate the depth stencil buffer but iOS doesn't like it. Remove that or change it to the depth buffer and it's happy.

**Steps to reproduce:**
Run any project under iOS that does something with 3D. Even just rendering a cube is fine.

**Comment by BastiaanOlij** [comment]
This did not get fixed by the framebuffer fix, this is a separate issue.

**Comment by reduz** [comment]
I think it was a different one, but I am confident it should be fixed now, so closing.
