### ISSUE TITLE
iOS does not support GL_R32F

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#25325]
**Godot version:**
Current master as at 25/1/2019

**OS/device including version:**
Tested on iOS iPhone 7 - Apple A10 GPU

**Issue description:**
iOS does not support GL_R32F. There are three places where this is used. One in 2D but I think this code already skips it, once where there is already an ifdef for iPhone, and once where the main exposure buffer is allocated which results in an error in the log at startup:
rasterizer_storage_gles3.cpp:7061:_render_target_allocate() - Condition ' status != 0x8CD5' is true

The place with the ifdef that already works around this issue changes it to GL_R32F.

After talking to @reduz he would like to see a nicer solution that looks at the extensions available of the GPU and sets this accordingly, not sure how to do that one :)

**Steps to reproduce:**
Run any iPhone project.

**Comment by BastiaanOlij** [comment]
After discussing this with reduz, I could only find one app on the appstore that allowed me to list extensions, I'll if to write something if we need more info then this.

It seems like the extension in question is GL_EXT_color_buffer_half_float which is only supported for OpenGL 3.0 on the iPhone. It introduces support for framebuffers to render to GL_R16F and related types. It explicitly states GL_R32F is not part of the spec. 

How do we check for this extension so we can switch our logic?

**Comment by BastiaanOlij** [comment]
@reduz btw, it looks like the float version of that extension adds R32F support so we could check for that as well to check if a renderer support R32F framebuffers? 
https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_color_buffer_float.txt

**Comment by BastiaanOlij** [comment]
Looks like reduz' fix worked, there is currently an #ifdef in rasterizer_scene_gles3.cpp line 5170 that should be replaced by a similar fix.

**Comment by bluenote10** [comment]
I'm trying to make sense of the conversion above. Is the issue closed because image formats like `FORMAT_RF` can now be safely used on iOS (i.e., is Godot creating some sort of shim on platforms that do not have it natively?) or does it mean using anything based on `GL_R32F` now "fails properly" on iOS?

I was searching [the image format documentation](https://docs.godotengine.org/en/3.2/classes/class_image.html#enum-image-format) for such compatibility notes, but couldn't find anything.

**Comment by Calinou** [comment]
@bluenote10 Only error checks were added, not a shim: https://github.com/godotengine/godot/commit/4f72ff4f1c296b59841005b946c22d523ac9df18
