### ISSUE TITLE
Profiler should list functions in inverse order.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#25328]
**Godot version:**

Master

**OS/device including version:**

All

**Issue description:**

Profiler shows script functions in time-ascendent way. Usual propose of profiler is to know what parts of code are more expensive to the processor, so this order is nonsense, **should list functions from more expensive ones to less**. Autoscroll doesn´t help with that because allways rise the list to the top and you can´t  follow the bottom functions (the more expensives ones).... I think this change is not new functionality, not difficult to achieve and can be adressed before 3.1 launch because (not compatibility breaking or functionality change).

**Comment by Zylann** [comment]
Also mentionned in https://github.com/godotengine/godot/issues/5682

**Comment by akien-mga** [comment]
Fixed by #25354.
