### ISSUE TITLE
Pivot point of Control node works wrongly.

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#25326]
**Godot version:**

Godot 3.1.beta 00ec3e9d2

**OS/device including version:**

Kubuntu 18.10

**Issue description:**

Pivot point of Control node works wrongly.

**Steps to reproduce:**
1. add a TextureRect
2. assign a texture
3. use <kbd>v</kbd> to move pivot offset. <= pivot is located wrong position
4. zoom in/out with mouse wheel scroll. <= pivot is moving with zooming
![control_pivot](https://user-images.githubusercontent.com/8281454/51755600-6c2c3b00-2102-11e9-84aa-1f9db5b2aeba.gif)

**Minimal reproduction project:**

**Comment by volzhs** [comment]
cc @groud

**Comment by groud** [comment]
Indeed, setting the pivot is broken with Control nodes.
