### ISSUE TITLE
Crash when base and class identical

### ISSUE THREAD

**Issue by TheFlamyy** [godotengine/godot#25339]
**Godot version:** 35c1694

**OS/device including version:** Ubuntu

**Issue description:** If a script extends a given class and has the same class_name, the engine will silently crash. The project can't be reopened unless you change the "project.godot" file. It's obvious that self-inheritance will lead to problems. The engine should nonetheless not crash but print out the error.

**Steps to reproduce:**
Create a node and attach following script.
```
extends A
class_name A
```

Save the script.
Add another line and resave.

**Comment by karliss** [comment]
Might be the same problem as #9609 . If the code doesn't handle loops in inheritance there isn't much difference between loops of size 1, 2 or any other size.

**Comment by akien-mga** [comment]
I can confirm the crash in 88a36e20. It loops and crashes in `GDScript::get_instance_base_type()`.

When loading the project with such a script saved, it no longer crashes for me though, but prints:
```
ERROR: load: Resource: 'res://Control.gd' is already being loaded. Cyclic reference?
   At: core/io/resource_loader.cpp:363.
SCRIPT ERROR: GDScript::reload: Parse Error: Class 'A' could not be fully loaded (script error or cyclic dependency).
   At: res://Control.gd:1.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:579.
```

And prints this when parsing the script:
```
ERROR: _update_exports: Path extending itself in  res://Control.gd
   At: modules/gdscript/gdscript.cpp:461.
```

If you modify the script and save, it crashes.
