### ISSUE TITLE
Mono export templates extraction issue

### ISSUE THREAD

**Issue by ForLoveOfCats** [godotengine/godot#25330]
**Godot version:**
3.1 Beta 2 Mono

**OS/device including version:**
Manjaro Linux x86_64

**Issue description:**
When downloading export templates they are extracted incorrectly resulting in all contents in the topmost folder for the specified template.
![image](https://user-images.githubusercontent.com/30666851/51778448-ab8d6400-20cf-11e9-9ada-0f3824e00fce.png)

**Comment by akien-mga** [comment]
Still reproducible in 3.1 beta 6 Mono.

To be clear, the Linux and Windows binaries as well as the osx.zip files are meant to be extracted this way. I'm not sure how the rest is meant to be packaged.

**Comment by neikeq** [comment]
This is just the editor is extracting all files to the templates directory, ignoring that some should go into sub-directories.

**Comment by neikeq** [comment]
I was about to fix this by making it extract the files into the respective sub-directory, but now that I think of it, it may be better to just include the data directories as zip files instead.

**Comment by neikeq** [comment]
Ignore my last comment. We may support it as zip as well in the future, but for now fixing this is enough.
