### ISSUE TITLE
Godot fails loading compiled GDScript in release build when assigning new value to iterator

### ISSUE THREAD

**Issue by girng** [godotengine/godot#25334]
**Godot version:**
6e600706e9c0d2d08ea4cf57b7cda423de1a45fd

**OS/device including version:**
Windows 10, 64-bit

godot displayed no errors at all :/. just opened and closed. (even running in cmd and piping output to a file). so i removed every single piece of code one by one, and exported it each time, etc.. for a few hours lol. finally found it!

**Issue description:**
 - `player_id = int(player_id)`  will cause Godot to open and close without any error:
 - **Exported Godot apps only**. Only happens when Script Mode is set to **Compiled** or **Encrypted**.
 - This **does not happen** if Export To Debug is enabled, or running from the editor

```
extends Control

func _ready():
	var message = {"2": "fakedatahere"}
	for player_id in message:
		player_id = int(player_id)
```
**Minimal reproduction project:**
[New Game Project66.zip](https://github.com/godotengine/godot/files/2798725/New.Game.Project66.zip)

**Comment by girng** [comment]
Can't reproduce on Godot_v3.1-beta2's windows_64_release.exe

**Comment by Xrayez** [comment]
Yep, probably regression from #25274. Doesn't seem to be related to script encryption.

**Comment by akien-mga** [comment]
I can reproduce it on 3.1 beta 7 on Linux. Running the exported 64-bit release build gives:
```
SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Cannot assign a new value to a constant.
          At: res://Control.gdc:9
ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:784
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2148
ERROR: _load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:285
ERROR: poll: res://Control.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Control.gd
   At: scene/resources/resource_format_text.cpp:440
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208
ERROR: _load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:285
ERROR: start: Condition ' !scene ' is true. returned: false
   At: main/main.cpp:1738
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2093
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:425
```

**Comment by akien-mga** [comment]
Related to #25408.

**Comment by avencherus** [comment]
This seems to have been awhile ago, I think I may have run into the same issue, not entirely sure.

https://github.com/godotengine/godot/issues/26412

**Comment by avencherus** [comment]
The release builds are dead in the water for me at the moment.

Surprised more people haven't run into this yet, it's not terribly hard to bump into, are not many doing release builds in 3.1 as of late?

Was considering refactoring everything, since it seems to treat certain types as constants, but given the testing involves making a release export to check as I go, it'll take weeks to sort them out at this point.

Also found things like this are suspects.

```gdscript
	var a = { b = 100 }
	
	for b in a.values():
		b += 1
```
So far I've found anything that is `int`, `float`, or `String` are probably being considered constant.  Maybe there are some exceptions.
