### ISSUE TITLE
Adding PitchShifter to bus makes audio sound worse the more it's played.

### ISSUE THREAD

**Issue by Fupicat** [godotengine/godot#25332]
**Godot version:**
Godot v3.0.6 Stable

**OS/device including version:**
Windows 10 Pro version 1803

**Issue description:**
I have a function that plays a sound from an AudioStreamPlayer node:
`extends AudioStreamPlayer`
`func sound():`
`    play()`
The AudioStreamPlayer node is hooked up to the Master bus, which has a PitchShift effect added (value is 1).
I expected the sound to play normally each time the function is called, but instead, the sound gets of progressively lower quality (softer, more airy) each time it's played.

**Video**
[Here's a video of it happening.](https://streamable.com/nvbtu) Try skipping from the beginning to the end to see the difference more clearly. It gets especially noticeable around the 100th time.

**Steps to reproduce:**

1. Add a PitchShift effect to the Master bus
2. Create an AudioStreamPlayer node
3. Add a sound to it (I tested with several different sounds and they all produce a similar effect)
4. Create a function in it that plays a sound
5. Call this function continuously (I also tried the animator)
6. Every time the sound plays it gets a little more blurry

**Minimal reproduction project:**
[Audio Problem.zip](https://github.com/godotengine/godot/files/2798466/Audio.Problem.zip)

**Comment by akien-mga** [comment]
I can't reproduce it in the current master branch / 3.2 beta 6, so it might have been fixed since this was initially reported.
