### ISSUE TITLE
Better inter-process communication API

### ISSUE THREAD

**Issue by buckle2000** [godotengine/godot#25333]
**Godot version:**
3.0.6

**OS/device including version:**
Any

**Issue description:**
Godot can be the new HyperCard.
Upon reading [this](http://www.loper-os.org/?p=568), I tried to implement a calculator in Godot.
It was surprisingly simple, except that I have to rely on python to evaluate math expressions like `1/2*9`.

However, there currently is only one way to execute external command: `OS.execute`. There is no way to get stderr or status code, so I need a better API.

[Equivalent API in golang](https://godoc.org/os/exec)
I found this library: https://gitlab.com/eidheim/tiny-process-library

**Comment by Zylann** [comment]
You can evaluate math expressions using the `Expression` class.

**Comment by buckle2000** [comment]
> You can evaluate math expressions using the `Expression` class.

Thanks, but I still need to use external process to do other stuff.

How can I contribute?

**Comment by Chaosus** [comment]
At this moment, you can use C# Process class to achieve this functionality (+) its faster and have lots of features (-) it requires mono version of engine which may be undesired..

**Comment by silverkorn** [comment]
I'd also be interest to see Godot's core enabled to communicate with external processes without blocking, it would allow extending games and applications capacities by sending data back and forward to specialized technology standalones (IPC).

**Comment by jamie-pate** [comment]
The biggest missing feature (or at least the first thing to add) would be checking process status after it's launched, so far we only have `OS.kill(pid)` afaict (from gdscript)

after that, reading the stdout from a non-blocking process would be a close second.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/216, as feature proposals are now tracked in the Godot proposals repository. (Please open another proposal if you need something not tracked in that proposal.)

**Comment by silverkorn** [comment]
@Calinou , I think this request is not exactly the same as godotengine/godot-proposals#216.

Here we want an asynchronous inter-process communication which allows Godot writing data to the STDIN of the child process and reading out it's STDOUT and STDERR (And maybe custom file descriptors for more flexibility).

godotengine/godot-proposals#216 seems to only want to read the STDOUT asynchronously.

**Comment by Calinou** [comment]
@silverkorn Please open a separate proposal for that :slightly_smiling_face:
