### ISSUE TITLE
Build Platform JavaScript error

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#25344]
https://github.com/godotengine/godot/commit/b3335e943bbb321d4ea86cbf03ffc50032497aee
x11
`scons platform=javascript tools=no target=release`

```
platform/javascript/os_javascript.cpp:992:6: error: use of undeclared identifier 'emscripten_sample_gamepad_data'
        if (emscripten_sample_gamepad_data() == EMSCRIPTEN_RESULT_SUCCESS)
            ^
```

**Comment by lethiandev** [comment]
Update your Emscripten to the latest version (1.38.22 at least).

https://github.com/godotengine/godot/pull/25149
