### ISSUE TITLE
3D shadows bug

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#2535]
3D shadows seems to be buggy.
Please see this short video:
http://www.aparat.com/v/wRhIb

**Comment by Calinou** [comment]
There are plans to rewrite the 3D engine of Godot, with variance shadow mapping. Currently, none of the available shadow techniques look really good.

**Comment by okamstudio** [comment]
I know, the best shadow technique nowadays is VSM, which is too much for
GLES2

On Sat, Sep 26, 2015 at 7:19 AM, Calinou <notifications@github.com> wrote:

> There are plans to rewrite the 3D engine of Godot, with variance shadow
> mapping. Currently, none of the available shadow techniques look really
> good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2535#issuecomment-143417193>.
>



-- 

*OkamStudio*

**Comment by alabd14313** [comment]
This seems that Godot developers plan to rewrite 3D engine after vulkan api , and web export after webassembly. But pay attention that vulkan api will not replace openGL and webassembly will not replace webGL(javascript, Html5, Canavs, CSS 3D or DOM), Both of them will come to complement older techs:
http://www.qualium-systems.com/blog/useful-it-articles-and-advices/webassembly-and-javascript-improvement-or-competition/

Now:
![before1](https://cloud.githubusercontent.com/assets/14325605/10117344/7b791950-6460-11e5-9b7e-6e94b87b88ab.jpg)
![before2](https://cloud.githubusercontent.com/assets/14325605/10117346/8b9a6654-6460-11e5-8675-361b06277cea.png)

and probably in the Future:
![after](https://cloud.githubusercontent.com/assets/14325605/10117349/a9de5616-6460-11e5-84a2-e2f9545fefb1.jpg)


and for Vulkan and openGL:
http://home.seekscale.com/blog/the-future-of-graphics-programming-the-vulkan-api

https://www.khronos.org/message_boards/showthread.php/9717-Will-Vulkan-effectively-quot-replace-quot-OpenGL-or-not
wikipedia:
[...Initial specifications state that Vulkan will work on hardware that currently supports OpenGL ES 3.1 or OpenGL 4.X and up.[25] As Vulkan support will require new graphics drivers, this does not necessarily imply that every existing card that supports OpenGL ES 3.1 or OpenGL 4.X will have Vulkan drivers available.]

http://www.anandtech.com/show/9038/next-generation-opengl-becomes-vulkan-additional-details-released

http://blenderartists.org/forum/showthread.php?364510-How-will-Vulkan-replace-openGL-in-Blender-in-the-near-future

and finally I have some desires from all developers of this engine. Your users are around the world, from poor peoples:
![1](https://cloud.githubusercontent.com/assets/14325605/10117455/5c94c30a-6464-11e5-9270-9da08af174d2.png)
![2](https://cloud.githubusercontent.com/assets/14325605/10117490/944b68e8-6465-11e5-8667-cf3ddb204c97.jpg)
![32110](https://cloud.githubusercontent.com/assets/14325605/10117491/9706dad6-6465-11e5-97fc-7afc16f09ebe.jpg)
or looted:
![55498_135](https://cloud.githubusercontent.com/assets/14325605/10117494/be26ee3a-6465-11e5-9d78-605ca2b449a0.jpg)
and resister and patient:
![11](https://cloud.githubusercontent.com/assets/14325605/10117716/a5288270-646c-11e5-9090-f6317b64b686.jpg)
![111](https://cloud.githubusercontent.com/assets/14325605/10117717/a8d2497e-646c-11e5-9070-5bc74b60de6d.jpg)


.... to wealthy:
![dallas-texas](https://cloud.githubusercontent.com/assets/14325605/10117542/8a843d38-6467-11e5-8dcc-2128bf6e82c2.jpg)
![hong-kong](https://cloud.githubusercontent.com/assets/14325605/10117543/8af28c8e-6467-11e5-9d30-e74cfe75ef5d.jpg)

...or Affluent and money-fashioned:
![moneybagsphoto350](https://cloud.githubusercontent.com/assets/14325605/10117712/92385456-646c-11e5-8e6a-89e3f6a92a4e.jpg)
![rich_banker_cigar](https://cloud.githubusercontent.com/assets/14325605/10117714/9bff82fc-646c-11e5-9aff-e9ef553c6513.jpg)


Hardware vendors will not plan to produce upgradable hardwares and scientists do not create technologies that solve global warming and lack of water and...
They say buy, buy, change, do not upgrade...
Unfortunately graphics vendors means the word 'support':
[The new GeForce Game Ready 347.88 WHQL Battlefield Hardline drivers are now available to download from GeForce Experience and GeForce.com. With Game Ready optimizations for Battlefield Hardline, new SLI profiles, and support for TITAN X,...]
[Nvidia has released new game-ready drivers for The Witcher 3: Wild Hunt.]
[Nvidia GeForce Drivers Updated For 'Mad Max,' 'Metal Gear Solid V']
...

I agree with science improvements and finding optimized solutions, but please think for peoples that have not money to change their hardware day to day. We can search for solutions to stable our engine and low bind to speedy indigested technologies. In this way everyone can use this product at appropriate level.
Like:
1) GCC 5.0 balanced and moderate solution for openMP and openCL and openACC and intel-tbb and intel-cilkplus, not like Vendors' specific limit dizzying confusing grammy market solution like Nvidia CUDA or Ati-STREAM or Intel parallel :
http://www.phoronix.com/scan.php?page=news_item&px=gcc-5-coming-this-month
http://www.phoronix.com/scan.php?page=news_item&px=MTg4NTc

2) we must learn from Blend4Web project and their experiences, please pay attention carefully to this topic:
https://en.wikipedia.org/wiki/Blend4Web#Comparison_with_relevant_software
......[both engines produced similar visual quality, Unity's WebGL build had a total file size of 142 Mb (uncompressed) while the Blend4Web's exported HTML file for the same scene was only 1.8 Mb (uncompressed).]

I say again that I agree with Khronos new techs but ....

**Comment by reduz** [comment]
Don't worry, I live in a poor country too, so a GLES2 backend will be kept.

**Comment by akien-mga** [comment]
Stopped reading your post when you started posting photos... I would be glad if you could edit them away, they don't have anything to do with your post. Starving children or kids being crushed by military boots have nothing to do with the development of this engine.

**Comment by alabd14313** [comment]
Thank you @reduz because of your sympathy.
Hello @akien-mga.
How you can't see this peoples when I touch them every day? That children under your boot is not in my country, but there is not any proportionality between boot and man's face. please send your gift boot in a decorated box not kick it on children's face, or at least travel around your country with your booted legs. In this way nobody will not depressed.
I drew one way for the future of this engine and I said: [ I have some ***desires**], I didn't say I force you...

**Comment by akien-mga** [comment]
Ok, thanks for the troll, I'm out :)
