### ISSUE TITLE
\n and \t not working when fecthing translations

### ISSUE THREAD

**Issue by Necco-Z** [godotengine/godot#25361]
I'm having the same bug as #1232 on Godot 3.0.6 and Godot 3.1 beta 2. I've written a project with a simple scene to show 4 different possibilities for Labels:

1. The ´\n´ escape is inserted into the inspector.
2. The ´\n´ is present in the translation fetched by filling the Label text with the translation key.
3. The label text is filled from script, and the same tag is fetched using ´tr(KEY)´
4. The string containing ´\n´ is written directly into the script to fill the Label text, without translations.

In theory, only the first one should be unable to break the lines using ´\n´, since you can use Enter to break lines at the inspector. However, only the last label is filled correctly.

[This is a zip containing the project.](https://github.com/godotengine/godot/files/2799770/Label.test.zip)
The screenshots below show the editor and the scene running.
![clipboard02](https://user-images.githubusercontent.com/41708431/51796535-20e25d00-21d4-11e9-8338-bfb6aa30a6ac.png)
![clipboard04](https://user-images.githubusercontent.com/41708431/51796536-217af380-21d4-11e9-9f35-f997d35cc512.png)

**Comment by Calinou** [comment]
As a workaround, using a `.po` file as a translation source works:

```po
msgid ""
msgstr ""
"Project-Id-Version: Label test\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-01-27 12:00+0000\n"
"PO-Revision-Date: 2019-01-27 12:00+0000\n"
"Last-Translator: Your Name <your.name@example.com>\n"
"Language-Team: English\n"
"Language: en\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

msgid "L_TEST"
msgstr "1st line\n2nd line"
```

(Save the file as `test.po` and load it in the Project Settings instead of `test.translation`.)

![image](https://user-images.githubusercontent.com/180032/51803502-17013e00-2256-11e9-9fe9-288e5192100b.png)
