### ISSUE TITLE
Cannot compile on OSX

### ISSUE THREAD

**Issue by system-accelerator** [godotengine/godot#25360]
**Godot version:** 3.1 (commit is 1253b9c038277aebfb5a4cc11685823f2331a26)

**OS/device including version:** macOS High Sierra 10.13.4

**Scons version:** 3.0.1

**Issue description:**

When attempting to compile from source, using _scons platform=osx_ there will eventually be a compiler error with a generated .cpp file (called global_defaults.gen.cpp, located within the core directory), stating that the file global_defaults.h in platform/android/globals/ was not found.

**Steps to reproduce:**

Pull from the latest commit and compile using the above command.

**Comment by yehjaemin** [comment]
I'm sorry if it's not helpful, but I just compiled from source on macOS Mojave 10.14.2 a couple days ago. Maybe it's a system OS problem...

**Comment by Calinou** [comment]
You need to remove generated files using the following command (enter "1" to confirm deletion):

```
git clean -dfxi
```

**Comment by system-accelerator** [comment]
That did it, thank you!
