### ISSUE TITLE
Tilemap: set_cell slow when set a tile with collision on a tile without collision (FPS drop spikes)

### ISSUE THREAD

**Issue by Goutye** [godotengine/godot#25364]
Closed issues somehow linked to the current problem: #20323

**Godot version:**
3.1 Beta 2
3.0.6

**OS/device including version:**
Windows 7 64, GTX670

**Issue description:**
I was working on my game today and noticed a drop of FPS whenever I changed a tile to a tile with collision.  
After a bit of search, I was able to reproduce the drop on an empty project with just a two small tilemaps (one per player in my game) and a tileset that contains a tile with collisions.  

Is this behavior intended? Am I missing something to prevent these drops?

**Steps to reproduce:**
Either a large tilemap or two small tilemaps with a large number of collision tiles.  
At run-time, switch some non-collision tiles to collision tiles.

**Minimal reproduction project:**
Godot 3.1 beta 2: http://goutye.com/Godot/Demos/TilemapCollisionTest3.1.zip  
Godot 3.0.6: http://goutye.com/Godot/Demos/TilemapCollisionTest.zip

The setup is very simple:  

    if Input.is_action_just_pressed("click"):
		for cell in get_used_cells_by_id(1):
			set_cell(cell.x, cell.y, 2)
			return 

You will see that the delta time jumps, which leads to 40FPS~. The more you switch tiles, the lower the drop of FPS will be (30FPS~).  

    delta     (60FPS delta) 
    0.030394 (0.016667) -> 32.901111
    0.030662 (0.016667) -> 32.614023
    0.028961 (0.016667) -> 34.529595
    0.034074 (0.016667) -> 29.347514
    0.029909 (0.016667) -> 33.434752
    0.035547 (0.016667) -> 28.131687
    0.032595 (0.016667) -> 30.679242
    0.018519 (0.016667) -> 53.999994

If you start profiling, you will notice a spike (frame time) for each tile that has been switched, as in the following picture:  
https://i.gyazo.com/06d4f64c13ec4c7335912fce4559ad04.png

**Comment by Goutye** [comment]
Changing the quadrant size property fixed the problem. (for instance 4)

**Comment by akien-mga** [comment]
Can you still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

I gave it a try and didn't notice any big spikes in frame time when switching tiles (3.2.2 RC 2).

**Comment by Goutye** [comment]
@akien-mga I just tested on the latest 3.2.2-rc2, and indeed, with the default settings of quadrant size 16, there is no spikes anymore when switching tiles. Thank you very much! 👍

**Comment by akien-mga** [comment]
Great, closing as fixed then.
