### ISSUE TITLE
Phone freeze on opening Scene with imported 3D model [GLES2]

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#25365]
**Godot version:**
Godot 3.1 Beta 2 (GLES2)

**OS/device including version:**
Development:
OS: Windows 10
GPU: nVidia GeForce 520M

Test:
[Asus Zenfone 5 (2014)](https://www.gsmarena.com/asus_zenfone_5_a500cg_(2014)-5952.php)
OS: Android 
GPU: PowerVR SGX544MP2
GLES: 2.0.0

**Issue description:**

Just open project below, export, and install on android, play.
There are 3 scene in the game.
Scene C is a 3D scene with a box, plane, and environtment. This scene can be opened in my phone.
Scene A&B is the same as Scene C with addition an imported 3D model. It is a low poly model with skeletal animation. If i open this scene my phone freeze. The debugger not printing any error it just disconnected because my phone is freeze.

I also discover other issue while making this project.
1. Texture with Video RAM compress mode wont export to Android APK.
2. If you enable rim in the 3D material, the scene wont load (throw an error on remote debug)

is this expected behaviour?
If not then I'll make a separate issue.

**Steps to reproduce:**
1. Open the project below
2. Export Android
3. Play
4. Open Scene A or Scene B

**Minimal reproduction project:**

[CharacterTest.zip](https://github.com/godotengine/godot/files/2799866/CharacterTest.zip)

**Comment by akien-mga** [comment]
> Texture with Video RAM compress mode wont export to Android APK.

You need to enable `rendering/vram_compression/import_etc` (and likely disable `import_etc2`) for GLES2, then reimport the assets (you can do it by deleting the `res://.import` folder).

**Comment by earlroxas13** [comment]
@akien-mga About the rim option, is it also expected? GLES2 dont support rim?

**Comment by akien-mga** [comment]
> About the rim option, is it also expected? GLES2 dont support rim?

I guess not, but it shouldn't prevent the scene from loading, so that would be worth a bug report.

**Comment by earlroxas13** [comment]
@akien-mga Already test the rim, now the scene can be loaded and displayed with Beta 3 but the mesh not rendered instead. Check my referenced issue.

**Comment by earlroxas13** [comment]
Also reporting that this issue still reproduced with Beta 3 build.

**Comment by earlroxas13** [comment]
@reduz Unfortunately, this issue still reproduced in RC1 (haven't tried RC3 yet, will try it later), but instead of freeze my phone, it now crash the game.

**Comment by earlroxas13** [comment]
@reduz Today I tested it in Godot 3.1 stable it still crash, and if I test it several time in a row, sometimes it also freeze my phone.
