### ISSUE TITLE
Children of Nodes are rendered on top of children farther down in the scene hierarchy

### ISSUE THREAD

**Issue by sicienss** [godotengine/godot#25362]
**Godot version:**
3.1 beta 2, downloaded from [here](https://hugo.pro/projects/godot-builds/).

**OS/device including version:**
Windows 8 / Toshiba Satellite

**Issue description:**
Children of `Nodes` are rendered on top of children farther down in the scene hierarchy.

**Steps to reproduce:**
1. Create a scene with two `Sprites`.
2. Place the first `Sprite` in a `Node`.
3. Place the second `Sprite` farther down in the scene hierarchy.
4. Observe that the `Spite` child of the `Node` is rendered on top of the other `Sprite`, contrary to what you'd expect.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2799773/TestProject.zip)

**Related:**
Seems to be a new instance of issue #844.
May be related to more recent issue #23766.

**Comment by aaronfranke** [comment]
I believe you're supposed to use `Node2D` when working with non-UI 2D stuff. Why are you using `Node`?

**Comment by sicienss** [comment]
@aaronfranke, I use Nodes as containers to organize my scenes. For example, a Node containing all Enemies, a Node containing all Interactables, and so on. I believe a lot of people use Nodes this way. Node2D is not appropriate for this, since it has a position.

**Comment by girng** [comment]
Yeah, it's been like that for quite some time. For example, when using vnen's tiled plugin, and when you import a  tilemap,   the nodes  are reversed.  But good godot almighty please don't change this
