### ISSUE TITLE
Vsync broken in Godot_v3.1-beta2_x11.64

### ISSUE THREAD

**Issue by Flonka** [godotengine/godot#25377]
Issue:
Using the godot editor with a project using the default vsync enabled setting, it is not working as it is, in the current stable release (Godot_v3.0.6-stable_x11.64). 

Reproduction:
Create new project, add a new scene with a node. Enable fps output in the project settings, enable vsync (though it's already set to be enabled by default). Run the scene.

In 3.0.6 stable, output logs 60 fps.
In 3.1-beta2 ,  output logs 1000< fps

OS: Debian 8
GPU Driver info:
xserver-xorg-video-intel
X.Org X server -- Intel i8xx, i9xx display driver
2:2.99.917+git20161206-1~bpo8+1

--- 

Original notes of this issue can be found in the url referenced below.

@Flonka If your report is about vsync alone, it may be a different issue (please open another), though I am running latest Ubuntu and vsync is working fine.

_Originally posted by @reduz in https://github.com/godotengine/godot/issues/24168#issuecomment-457775100_

**Comment by reduz** [comment]
Need the following missing information from your part:

* Actual GPU model, seems integrated but you did not provide enough information.
* Window Manager and Compositor used
* OpenGL driver version in use (you can get this with glxinfo command)

Thanks!

**Comment by Flonka** [comment]
Hi! Sure, I'll try to dig out the data. Just tell me if something's not sufficient. I'm in the GNOME 3.14.1 desktop environment. I'll attach glxinfo as a text-file here. 

@reduz  On the compositor, I'm not sure if this is separate from the window manager or not.. I can't seem to find (google up) a solution to read out which one I have running. But I'm guessing you perhaps can tell me straight off... According to what i find, i should be running mutter, due to being on gnome 3.

[flonka_glxinfo.txt](https://github.com/godotengine/godot/files/2800520/flonka_glxinfo.txt)

**GPU data from lspci:**
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Grap
hics Controller (rev 09) (prog-if 00 [VGA controller])
        Subsystem: Hewlett-Packard Company Device 179b
        Flags: bus master, fast devsel, latency 0, IRQ 52
        Memory at d4000000 (64-bit, non-prefetchable) [size=4M]
        Memory at c0000000 (64-bit, prefetchable) [size=256M]
        I/O ports at 4000 [size=64]
        Expansion ROM at <unassigned> [disabled]
        Capabilities: <access denied>
        Kernel driver in use: i915

**Window Manager**: gdm3

**Comment by akien-mga** [comment]
Does it work if you enable vsync by code, as mentioned in #25399?

**Comment by Flonka** [comment]
Tried using the new beta release, Godot_v3.1-beta3_x11.64. But I still have the same issue. When setting the vsync via script, i still have the same issue. 

In 3.0 , this worked as expected, high fps disabled , 60 enabled.

--- 
Script on root node, vsync disabled in project settings:
extends Node
func _ready() -> void:
	print("1 Vsync enabled: " + str(OS.vsync_enabled))
	OS.set_use_vsync(true)
	print("2 Vsync enabled: " + str(OS.vsync_enabled))

** Debug Process Started **
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
1 Vsync enabled: False
2 Vsync enabled: True
Game FPS: 303
Game FPS: 1110
Game FPS: 1121
...

**Comment by michhhh** [comment]
Hi, I also have similiar issue, suddenly my game started to lag.
vscync is off, physics fps is 60, monitor refresh rate - 60, 144 (tried both)
60 hz monitor - it seems like it lags
144 hz monitor - it seems like there is ghosting?
OS: win 10 x64 latest
GPU: 1060
Godot: 3.1 latest master

With above example code it stops lagging.

Vsync off (lag, ghosting):
```
1 Vsync enabled: False
2 Vsync enabled: False
Game FPS: 1459
Game FPS: 2266
Game FPS: 3758
Game FPS: 3939
Game FPS: 4052
Game FPS: 4062
Game FPS: 4038
Game FPS: 4055
```

Vsync on (no lag, no ghosting):
```
1 Vsync enabled: False
2 Vsync enabled: True
Game FPS: 27
Game FPS: 60
Game FPS: 60
Game FPS: 60
Game FPS: 60
Game FPS: 60
```

**Comment by Flonka** [comment]
> Hi, I've also had similar issues with Intel driver. As it turned out I've disabled it myself long time ago in .drirc. With vblank_mode=1 vsync setting in editor works as it should. Tested on 3.0.6 and 3.1 ([919fa75](https://github.com/godotengine/godot/commit/919fa75803177d0dc8f03c16b6be1360140145e1))

I've unfortunately not added any such configuration file, and the issue i'm experiencing is that its working in stable, but not in the new 3.1beta version.

**Comment by Flonka** [comment]
Tried the new beta release, Godot_v3.1-beta4_x11.64. And now the fps is on a stable 60fps on my machine per default!
