### ISSUE TITLE
Color "stripes" when displacing SCREEN_UV, even if the whole screen has the same color (GLES3 only)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#25389]
Godot 3.0.6
Godot 3.1 beta2
Windows 10 64 bits
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

This is a very strange one that occurred when I tried to write a shader that tears the screen in stripes of a given length, by slightly displacing SCREEN_UV:

![image](https://user-images.githubusercontent.com/1311555/51805319-de686100-2263-11e9-9bba-3e7d39eed68c.png)

However, I noticed that between each stripe, there is a very noticeable line of pixels that seems to come from nowhere, which ruins the effect. I tried to figure out where they come from. And it turns out, after trying in a simpler project and simplified shader, it STILL happens even if the whole screen has the same color Oo

![image](https://user-images.githubusercontent.com/1311555/51805337-01931080-2264-11e9-9268-419484482a93.png)

Why are there such lines? Isn't the color supposed to be the same no matter where you sample the texture in this case? This is why I came reporting this as potential bug.

Test project: 
[ShaderStripesBug.zip](https://github.com/godotengine/godot/files/2800385/ShaderStripesBug.zip)

## Notes

Those stripes can't be seen if the color is white or black, or if `dir` is horizontal or vertical, and their brightness appears to follow this kind of curve:
![image](https://user-images.githubusercontent.com/1311555/51805583-289f1180-2267-11e9-8566-c239e032c0b5.png)
The bug also doesn't reproduce when applying the same shader on a texture, although there doesn't seem to be a sampling filter in action:
![image](https://user-images.githubusercontent.com/1311555/51805687-46b94180-2268-11e9-8169-729730c68e7e.png)

This bug does not reproduce with GLES2.
GLES3:
![image](https://user-images.githubusercontent.com/1311555/51805929-77e74100-226b-11e9-8478-89b312c9e3b4.png)
GLES2:
![image](https://user-images.githubusercontent.com/1311555/51805923-60a85380-226b-11e9-9832-2d9773a60c96.png)

Shader:
```glsl
shader_type canvas_item;

void fragment() {
	vec2 dir = normalize(vec2(1, 2));
	vec2 pos = SCREEN_UV / SCREEN_PIXEL_SIZE;
	float s = floor((pos.x * dir.y + pos.y * dir.x) * 0.05);
	float h = fract(s * 0.5);
	float sh = 2.0 * h - 1.0;
	vec2 displacement = (dir * SCREEN_PIXEL_SIZE) * (sh * 10.0);
	COLOR = texture(SCREEN_TEXTURE, SCREEN_UV + displacement);
}
```

**Comment by Zylann** [comment]
Forcing to use the first LOD fixed it, thanks @clayjohn :)
I wonder why mip maps have higher brightness though.

**Comment by clayjohn** [comment]
It is an bug. @reduz

**Comment by Zylann** [comment]
The last screenshot looks like the last mip has better resolution than previous ones Oo

**Comment by tiniuclx** [comment]
I believe I have found a workaround to this bug. Setting Framebuffer Allocation to "2D" within the project settings fixes the blurry artefacts showcased in clayjohn's screenshot.

Before:
![image](https://user-images.githubusercontent.com/24615474/54643230-4f6f0c80-4a8e-11e9-83a4-696e23132ca8.png)

After:
![image](https://user-images.githubusercontent.com/24615474/54643252-5c8bfb80-4a8e-11e9-84c9-867e1aacc64b.png)

My shader code is functionally identical to the example above.

However, this workaround does not work in the editor, only when the game is actually running. The editor still showcases the bug irrelevant of the selected Framebuffer Allocation.

**Comment by Clocktown** [comment]
I think I have identified the error in the source code. It can be found in
[effect_blur.glsl (gles3)](https://github.com/godotengine/godot/blob/3dc63a710f0ca845e6de9e8b4a2158a33743ad36/drivers/gles3/shaders/effect_blur.glsl) and in [effect_blur.glsl (gles2)](https://github.com/godotengine/godot/blob/3dc63a710f0ca845e6de9e8b4a2158a33743ad36/drivers/gles2/shaders/effect_blur.glsl). It is in the `#ifdef GAUSSIAN_HORIZONTAL` part. The coefficients do not add up to 1, but to 1,051581. When I tried to code something to counteract the brightness before, I used a factor of 0.95^miplevel. This rougly matches and counteracts that factor I now found in the code, so I am pretty sure that this is the error. However, I have no dev environment setup for the engine and thus I could not verify it.  

Theoretically, normalising these coefficients would be enough. But it would be better to actually think about which sigma was meant to be used here, which I do not know. It has to match the vertical blur. If we just renormalise, we might introduce a new, but way more subtle bug.

**Comment by clayjohn** [comment]
I have a feeling this is a bug introduced in 22a90e8f I have never seen a Gaussian blur where the vertical and horizontal used a different number of samples. Also it is strange that reduz would add the Glow blur and then make it the exact same as the Gaussian blur. 

@reduz Do you have any input on this?

**Comment by Clocktown** [comment]
Vertical and Horizontal dimensions are different because the first pass fills the smaller mip-level using the higher resolution mip level. But the second pass needs to work with the result of that, so it now runs on the reduced mip-level, hence less samples. It's downsampling and filtering merged together.

**Comment by clayjohn** [comment]
That makes sense. 

Here is a seven sample Gaussian blur with sigma 2.0

0.071303 | 0.131514 | 0.189879 | 0.214607 | 0.189879 | 0.131514 | 0.071303

Eerily similar to Godot's code except Godot uses 0.157305 in the 2nd and 6th samples.

**Comment by Clocktown** [comment]
Then I think it is highly likely that a 2 sigma gaussian was supposed to be used there. It adds up, because the 5 sample vertical one is a sigma of 1. It has to be half because it works on the lower resolution.

**Comment by clayjohn** [comment]
You were right! Looks great now. 

![mipbug-fixed](https://user-images.githubusercontent.com/16521339/56072414-692d0800-5d4b-11e9-9f4f-a7e8e85f6b81.png)

**Comment by Clocktown** [comment]
Nice! Thanks for fixing it.
