### ISSUE TITLE
Node2D get() for global transforms can produce errors.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#25385]
**Godot version:**

1253b9c038277aebfb5a4cc116

**OS/device including version:**

Win10 64bit

**Issue description:**

When calling these properties on a Node2D that isn't in the tree, it generates these errors.  These are the only properties that seem to do this in this condition.  Shouldn't it just return either the local transform or a default one?

![image](https://user-images.githubusercontent.com/13004169/51804020-3e5f0780-2264-11e9-8e09-0a37bec75d6c.png)

**Steps to reproduce:**

Use the following code, or the project below.

```gdscript
extends Node2D

func _ready():
	
	var n = Node2D.new()
	
	var gpos = n.get("global_position")
	var grad = n.get("global_rotation")
	var gdeg = n.get("global_rotation_degrees")
	var gscl = n.get("global_scale")
	var gxfm = n.get("global_transform")
```

**Minimal reproduction project:**

[3.1 Node2D get errors.zip](https://github.com/godotengine/godot/files/2800265/3.1.Node2D.get.errors.zip)

**Comment by clayjohn** [comment]
The global transform includes the transform of its parent node. If it has no parent then it is probably a good idea to let the user know that that they are not receiving the global transform. 

That being said, it looks like this should be a warning instead of an error. It even says that it is returning a default transform instead.

**Comment by groud** [comment]
That's an expected behavior. If your node is not in a tree, it has no global* properties. Those are computed using its parents properties.

**Comment by clayjohn** [comment]
@groud You are right. I looked into it and the error is only enabled in debug mode. When in release mode it just returns a default ``Transform2D()``. This is probably the best behaviour.

**Comment by avencherus** [comment]
@clayjohn Thanks for looking in that.  Hadn't considered it would be different in release, but if that is the case it shouldn't be an issue.
