### ISSUE TITLE
Particles2D does not work on Android

### ISSUE THREAD

**Issue by DiegoLopez21** [godotengine/godot#25386]
**Godot version:**
Godot 3.1 beta 3

**OS/device including version:**
Windows 7 Ultimate, 64 bits

**Issue description:**

Hola. Estoy probando un juego hecho en Godot directamente en un smartphone Samsung Galaxy J1 ace, Android 5.1.1.

![image](https://user-images.githubusercontent.com/29789440/51804376-f45b2f00-222d-11e9-8535-5c03e3883a49.png)

El juego funciona bien en este smartphone, excepto que no se muestra el efecto de partículas.

En el PC, cuando reproduzco el juego, las partículas sí se muestran. El juego funciona muy bien en Windows.

**Steps to reproduce:**

Así configuré el efecto de las partículas:
![image](https://user-images.githubusercontent.com/29789440/51804360-b3631a80-222d-11e9-882f-09bf6fc2b4dd.png)

La ventana de salida muestra unos errores; sin embargo el juego funciona bien en el smartphome (excepto las partículas que no se muestran. En beta 2 tampoco funcionaba):
![image](https://user-images.githubusercontent.com/29789440/51804397-574cc600-222e-11e9-92b0-8b2662855d79.png)

**Comment by qarmin** [comment]
Please use english language to describe the issue.
I had unicode error when I used text file with non utf-8 fomatting(Windows-1250), so try to convert all files which you use to utf-8 without bom(in notepad++)

**Comment by Chaosus** [comment]
Duplicate of #14951
