### ISSUE TITLE
CanvasLayers don't respect layer number when nested

### ISSUE THREAD

**Issue by razcore-rad** [godotengine/godot#25384]
**Godot version:** v3.1.beta3.official

**OS/device including version:** Ubuntu 18.10

**Issue description:**
In a tree like the one in the image both `CanvasLayer` are set to `layer` 1. I expect `DBG/Node2D/CanvasLayer/icon` (the red tinted sprite in the demo) to be drawn on top of `DBG/CanvasLayer/icon` because it's lower in the tree but this isn't the case. We observe that if we move `DBG/Node2D/CanvasLayer` to `DBG/CanvasLayer2`, just under `DBG/CanvasLayer` then it behaves properly. Check the debug project.
![image](https://user-images.githubusercontent.com/1177508/51803931-4b2f2b80-2263-11e9-9d5a-6864311f396d.png)

view at my end with unexpected behavior:
![image](https://user-images.githubusercontent.com/1177508/51803962-a3662d80-2263-11e9-9dc5-facca9369cfc.png)

**Minimal reproduction project:**
[godot-dbg.zip](https://github.com/godotengine/godot/files/2800261/godot-dbg.zip)

**Comment by akien-mga** [comment]
I tested various versions: 3.0.6 stable, 3.1 beta 3, 3.1 stable, 3.5 beta (current git).

The behavior appears to be non deterministic, running the project or the editor multiple times gives different results.

On the same version (3.5 beta 0e6a708a9) I've seen both this:
![image](https://user-images.githubusercontent.com/4701338/157314546-748c05a5-2090-4cc0-a859-11b2d20994c2.png)

and this:
![image](https://user-images.githubusercontent.com/4701338/157314707-96495f4a-2b71-4933-81d3-429fac992286.png)

**Comment by akien-mga** [comment]
On the other hand in Godot 4.0 alpha 4 it seems to work as expected consistently. The red icon is always on top, following tree order for elements at the same layer.

**Comment by farcastr** [comment]
Interesting, I see what you mean. I'll take a closer look.

**Comment by farcastr** [comment]
I have a fix for the problem as described above that will standardize to the 4.0.alpha build. Based on the milestone tag, I assume my PR should go on the 3.x branch?

Also, after some extensive testing I found that the 4.0.alpha build works much more predictably than the 3.x and lower branches. I do still see one issue - in cases where one canvas layer is nested results are consistent (layers move on changes to the scene tree and they are always rendered on project load in the correct order). However, if both layers are nested, then updates to the scene tree will not be applied until the editor is reloaded. Once the project is reloaded though, everything is rendered in the correct order. I'll keep digging for this.

**Comment by akien-mga** [comment]
This was improved by #59234 which should make the behavior more deterministic.

But as discussed in #59192 we're still not sure that it will actually make the behavior always predictable across engine runs or for different scenes. And as such the same issue likely still exists in 4.0 too (after #59234 both 4.0 and 3.5 use the same sorting by ID instead of pointer address).

On chat @reduz mentioned:

>  I have the feeling we should use age if the layer is the same
I wonder also because I thought we had some sort of keying

Not sure what "age" is exactly in this context.

**Comment by Calinou** [comment]
> Not sure what "age" is exactly in this context.

Maybe it refers to the first/last added CanvasLayer?

**Comment by akien-mga** [comment]
Fixed by #69952.
