### ISSUE TITLE
Proximity fade causes disappearing objects and potential crashes

### ISSUE THREAD

**Issue by OnomatoWombat** [godotengine/godot#25387]
**Godot version:**
v3.1.beta2.official

**OS/device including version:**
Windows 10 Pro

**Issue description:**
Proximity fade will occasionally do one of the following:
-Cause the program to crash
-Not work
-Cause screen-based dithering (has only happened in one experience)
-Cause a mesh to disappear upon opening the project until it is selected in the editor

It also appears invisible to cameras and other viewports, in my experience. However, they don't appear after the object is selected in the heirarchy.

**Steps to reproduce:**
Open the project and click the mesh instance in the scene heirarchy to make it appear. The cube is placed at 0,0,0 with a rotation of 0,0,0.

Image of before clicking in the heirarchy:
![beforeclicking](https://user-images.githubusercontent.com/47086459/51804814-4a7ea100-2233-11e9-9576-964da64a801f.png)

Image of after clicking in the heirarchy:
![afterclicking](https://user-images.githubusercontent.com/47086459/51804818-54a09f80-2233-11e9-881f-1df1733582e0.png)

**Minimal reproduction project:**
The project is called "Distance fade" despite the fact that it's a proximity fade problem.
[bug_test.zip](https://github.com/godotengine/godot/files/2800323/bug_test.zip)

**Comment by coasterspaul** [comment]
I can confirm with my own proximity fade tests.
Actually, proximity fade worked in my project for most of the 3.1 betas I tried, and I didn't realize it was broken until the 3.1 stable version. I created my own minimal project to make sure something wasn't screwy with my actual project. Here's how it looks in the editor in 3.1 RC2:
![image](https://user-images.githubusercontent.com/11203426/54385931-ca3ac080-4665-11e9-8658-2c45018bf0e0.png)

And here's how it looks in the editor in 3.1 RC3: 
![image](https://user-images.githubusercontent.com/11203426/54386336-b5aaf800-4666-11e9-9a80-55489d4ee964.png)
It's invisible on opening the scene, appears solid after clicking on it in the hierarchy, and is invisible when actually running the scene.

The same thing happens in 3.1 stable.

**Comment by supagu** [comment]
I also have this problem.

Here is a screenshot in editor - no depth fade is working but it at least shows the objects:
![editor](https://user-images.githubusercontent.com/11153232/54401829-493d0100-4719-11e9-9c3d-f3acc172878a.png)

in when I run the game:
![ingame](https://user-images.githubusercontent.com/11153232/54401836-522dd280-4719-11e9-86a4-7716ac33a1f4.png)

those boxes in the middle of the scene are a test. the red one is a normal material.
the blue cube is the wame material as my water. The white one is a new spatial material with depth fade set to enabled.

Oddly when I made a test project, the problem did not occur.
I put a cube on a plane, applied my water material and it seemed to work fine (but not in the editor).

I'm running Linux Manjaro, Godot 3.1 branch.

**Comment by supagu** [comment]
Might related to: #25535

**Comment by clayjohn** [comment]
Yes. Its the same issue.
