### ISSUE TITLE
GIProbe Doesn't Bake ShaderMaterial Albedo

### ISSUE THREAD

**Issue by DeadlyLampshade** [godotengine/godot#25396]
**Godot version:** 
Godot 3.1 Beta 2

**OS/device including version:** 
Windows 10, Nvidia GTX 1060

**Issue description:** 
For some reason, the albedo of shadermaterials is not accounted for in GIProbes.
https://cdn.discordapp.com/attachments/408555922349359105/539236548416110602/unknown.png
This is what the GIProbe bakes when a SpatialMaterial is used.
https://cdn.discordapp.com/attachments/408555922349359105/539236777773236234/unknown.png
This is that exact same material, converted into a ShaderMaterial and baked into a GIProbe

**Steps to reproduce:**
1. Create a reflective surface, spatial or shader material, it doesn't matter
2. Make sure High Quality GI is on
3. Create an object with a shader material, an easy way to do this is to simply create a new SpatialMaterial and convert it to one.
4. Make sure all objects in the scene are used in baked lighting.
5. Bake GIProbe and Observe.

**Minimal reproduction project:** 
[BugReport.zip](https://github.com/godotengine/godot/files/2801000/BugReport.zip)

**Comment by reduz** [comment]
No, it doesn't work well. This requieres significant change for GLES3 backend which won't be done now, will work on it after 3.1 is out.

**Comment by clayjohn** [comment]
This has been implemented in the Vulkan backend for 4.0 already. It will not make it into 3.2.
