### ISSUE TITLE
Tree.get_selected() always returns the last selected tree item, instead of null when no items are selected

### ISSUE THREAD

**Issue by mishapsi** [godotengine/godot#25392]
**Godot version:** 3.1 beta 2

**OS/device including version:** windows 10 x64

**Issue description:**

Tree.get_selected() will always return the last selected tree item, even when there are no tree items selected.  Expected result of null

edit: Tree.get_selected_collumn() also returns the last selected selected collumn, instead of null

**Comment by AlexHolly** [comment]
Is this related? https://github.com/godotengine/godot/issues/20548

**Comment by KoBeWi** [comment]
How do you deselect an item? By removing one?

**Comment by tom-jk** [comment]
State of this issue in 3.2.3.beta1 (testing on linux mint 18.3)

Convenience project: [25392.zip](https://github.com/godotengine/godot/files/4991193/25392.zip)


tree.get_selected() keeps previously selected treeitem after it has been deselected.
tree.get_selected() returns null when treeitem is freed.
tree.get_selected_column() keeps previously selected column after deselection or freeing.
tree.get_selected_column() will change to the new last column if tree.columns was reduced while last column was selected.

<sub>note: game crashes after removing columns then hovering with mouse (particularly in single and row select modes), maybe worth new issue?</sub>

**Comment by KoBeWi** [comment]
> note: game crashes after removing columns then hovering with mouse (particularly in single and row select modes), maybe worth new issue?

If it wasn't reported already then yes.
