### ISSUE TITLE
How to export Dictionary in 3.1 Beta 3 ?

### ISSUE THREAD

**Issue by CCODE05B** [godotengine/godot#25409]
**Godot version:**
Godot 3.1 Beta 3

**OS/device including version:**
Windows 7 x64

**Issue description:**
Sorry for my Stupid question , but how to Export Dictionaries in 3.1 ?

i was using 3.0.6 and there was a bug with Enums and they should not work like this .. right ?

![error2](https://user-images.githubusercontent.com/34812055/51830970-55980680-22f1-11e9-9be1-0a60739c6159.jpg)

so i switched my project to 3.1 Beta 3 and instead of using Enums , i use Dictionaries .. but i want to Exported but i get this error 

![error](https://user-images.githubusercontent.com/34812055/51830780-eae6cb00-22f0-11e9-98ee-b397f8b5fbee.jpg)

**Comment by akien-mga** [comment]
Exporting enums works fine. The error in your first screenshot is that you need to use `PLAYERCHIPS.C_D2` at line 101, you can no longer access elements of named enums without the enum itself (see #23648).

**Comment by CCODE05B** [comment]
@akien-mga I feel like Stupid
