### ISSUE TITLE
GLES2: Ice shader renders black in material tester (SCREEN_TEXTURE unimplemented in 3D)

### ISSUE THREAD

**Issue by Elmapul** [godotengine/godot#25405]
Godot_v3.1-beta3_x11.64  using GLES2
(also present on beta 2 and 1)

Ubuntu 14.04
Intel® Core™ i5-3317U CPU @ 1.70GHz × 4
8GB of ram (7,7 + 256 dedicated for video)

the ice shader for the material tester demo is full black.
![screenshot](https://raw.githubusercontent.com/Elmapul/daily-scripts/master/Captura%20de%20tela%20de%202019-01-28%2007%3A24%3A04.png)

project tested:
https://godotengine.org/asset-library/asset/123

similiar to this issue, except that in my case the ice is fully black.
https://github.com/godotengine/godot/issues/9508

**Comment by akien-mga** [comment]
Are you using the GLES2 or GLES3 renderer? Could you try the other one and see if it makes a difference?

**Comment by akien-mga** [comment]
I could reproduce it with GLES2 on my system. Mageia 7 x86_64, NVIDIA GTX 670MX driver 410.x.

**Comment by clayjohn** [comment]
This is a result of ``SCREEN_TEXTURE`` not being implemented in GLES2 3D right now. Reduz just implemented it in 2D in commit 7fa41f1

**Comment by hpvb** [comment]
This also happens on Linux with Radeon graphics.

GLES2
![screenshot from 2019-02-07 16-45-49](https://user-images.githubusercontent.com/2591099/52423278-155a3480-2af8-11e9-83c5-f1cded42cb40.png)

GLES3
![screenshot from 2019-02-07 16-46-18](https://user-images.githubusercontent.com/2591099/52423306-1ee39c80-2af8-11e9-9aaf-de0357cb6a5a.png)
