### ISSUE TITLE
Incorrect collision behavior in 3.1 beta 3

### ISSUE THREAD

**Issue by Nathan173AB** [godotengine/godot#25413]
**Godot version:**
3.1 beta 3, Linux 64-bit

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
I've been developing a grid-based building game on the 3.1 betas. I use an Area node to represent the build cursor, which passes a signal when another shape overlaps it to let the game know that things can't be built there.

I noticed a change in collision behavior going from beta 2 to beta 3. In the beta 3, the build cursor registers it overlapping with the game's GridMap, but I see no evidence that any of the build cursor's shapes overlap or collide with the GridMap. Running the same project in beta 2 doesn't yield this problem.

**Steps to reproduce:**
1. Run the provided project file in Godot 3.1 beta 2.
2. Click on various places of the map. A path should build.
3. Close Godot without making changes to the project.
4. Run the project again but in Godot 3.1 beta 3.
5. Repeat step 2, but paths now fail to build because the build cursor now registers as overlapping with the GridMap.

**Minimal reproduction project:**
https://drive.google.com/file/d/1au95BKQVN5XBw-8bROVVh59Wahhj_bLm/view?usp=sharing

**Comment by Nathan173AB** [comment]
Hello, I'm just letting it be known I'm still having this issue in beta 6 but, instead of the build cursor registering as overlapping with the GridMap, it doesn't register an overlap at all and things can be placed repeatedly on top of each other as a result.

**Comment by akien-mga** [comment]
It seems fixed in beta 7, at least the game behaves the same in beta 7 than it did in beta 2. I can confirm that in beta 3 it doesn't place/dig path chunks, which was likely the bug described.

For beta 6, you likely hit a temporary regression in the Area code, which has been reverted right after beta 6.

**Comment by Nathan173AB** [comment]
Yes, can confirm. I'm no longer experiencing this issue in beta 8.
