### ISSUE TITLE
Android support-core-utils:28.0.0 dependency

### ISSUE THREAD

**Issue by Shin-NiL** [godotengine/godot#25411]
**Godot version:**
3.1 beta 3

**OS/device including version:**
Android

**Issue description:**
It's just a question: is [this dependency](https://github.com/godotengine/godot/blob/b385a4b053e51a7076d87c80eb53ca451d0bdfb6/platform/android/build.gradle.template#L25) really necessary? Some users are [having trouble](https://github.com/kloder-games/godot-admob/issues/62) compiling the Admob module because it conflicts with the module dependencies
```
+--- com.google.android.gms:play-services-ads:16.0.0 
|     +--- com.android.support:support-core-utils:26.1.0
```
Removing the line everything works fine.

**Comment by akien-mga** [comment]
CC @volzhs

**Comment by volzhs** [comment]
https://github.com/godotengine/godot/blob/df7d3708c5b535c3696943322a14ec19a175e30c/platform/android/java/src/org/godotengine/godot/Godot.java#L62
https://github.com/godotengine/godot/blob/df7d3708c5b535c3696943322a14ec19a175e30c/platform/android/java/src/com/google/android/vending/expansion/downloader/impl/DownloadNotification.java#L30
these `import` requires below dependency.

https://github.com/godotengine/godot/blob/b385a4b053e51a7076d87c80eb53ca451d0bdfb6/platform/android/build.gradle.template#L25

**Comment by volzhs** [comment]
@Shin-NiL I just downloaded your admob module and successfully compiled android template with this line change.

in your `config.py`
```
env.android_add_dependency("compile ('com.google.android.gms:play-services-ads:16.0.0') { exclude group: 'com.android.support' }")
```

adding exclude group option.

**Comment by Shin-NiL** [comment]
Thank you very much @volzhs

**Comment by ramizbalayil** [comment]
Thank you @volzhs

**Comment by Valtrouble44** [comment]
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
