### ISSUE TITLE
Area3D triggers area_entered when inside a concave static body

### ISSUE THREAD

**Issue by David-Ochoa** [godotengine/godot#25419]
**Godot version:**
3.1 Beta 3

**OS/device including version:**
Windows 10

**Issue description:**
When an Area3D is inside a concave static body area_entered is triggered, this didn't happen with previous versions.

**Steps to reproduce:**
Open attached project and run it, body_entered triggers as soon as the scene is loaded

**Minimal reproduction project:**
[Area3D.zip](https://github.com/godotengine/godot/files/2803663/Area3D.zip)

**Comment by reduz** [comment]
Can you test with Godot physics?

**Comment by David-Ochoa** [comment]
> Can you test with Godot physics?

I did, it doesn't happen with Godot physics, only with bullet.
