### ISSUE TITLE
gdnative_api_struct_.gen.cpp not populating next with api_1_1

### ISSUE THREAD

**Issue by pchasco** [godotengine/godot#25425]
**Godot version:**
3.1 alpha
de0d30655859a46eaf711e209fe20d9ca60a60f2

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
gdnative_builder.py is not populating the .next member on api_struct. Below is the code generated by the builder, with my comment indicating where I believe the missing value is located:

extern const godot_gdnative_core_api_struct api_struct = {
	GDNATIVE_CORE,
	{1, 0},
	NULL,   //   should be (const godot_gdnative_api_struct *)&api_1_1
	4,
	gdnative_extensions_pointers,
	godot_color_new_rgba,
	godot_color_new_rgb,
	godot_color_get_r,
	godot_color_set_r,
	godot_color_get_g,
	godot_color_set_g,
	godot_color_get_b,

**Steps to reproduce:**
Build Godot with scons.

**Minimal reproduction project:**
None -- look at generated file

**Comment by karroffel** [comment]
Indeed, I'll take a look
