### ISSUE TITLE
when toggling between fullscreen, the screen freezes

### ISSUE THREAD

**Issue by girng** [godotengine/godot#25427]
**Godot version:**
188a711c4f08f96bccd72ecea0d7445f0c7846ca

**OS/device including version:**
Win10, 64-bit. GTX 950, nvidia driver 399.24

**Issue description:**
When toggling between fullscreen mode, the Godot app will freeze for a few seconds

**Steps to reproduce:**
- Run example project
- Click the Fullscreen button
- Now press `windows key` + `d`, alt+tab, or click it again
- You will notice a screen freeze for 2-3 seconds ( seems like the entire app locks up too, because the button doesn't get changed until a few seconds later)

**Other Information:**
- happens on exported builds as well

**Minimal reproduction project:**
[New Game Project67.zip](https://github.com/godotengine/godot/files/2804216/New.Game.Project67.zip)

**Comment by Calinou** [comment]
I can't reproduce this on Linux, but this is likely Windows-specific due to how fullscreen is implemented there.

Does the freeze occur if you enable `borderless` in the Project Settings?

**Comment by girng** [comment]
ty @Calinou 
yes, can confirm, just enabled borderless and freeze still occurs

**Comment by girng** [comment]
I've been fiddling around with this for a few hours:

Replace the example code with:
```
extends Control

var old_size = OS.window_size
var old_position = OS.window_position  

func _on_CheckButton_toggled(button_pressed):
	if button_pressed:
		OS.window_borderless = true
		OS.window_size = OS.get_screen_size() + Vector2(0, 1)
		OS.window_position = Vector2(0, 0)
	else: 
		OS.window_size = old_size
		OS.window_position = old_position
		OS.window_borderless = false
```

The app doesn't freeze. Mind is absolutely blown. Seems like whenever `window_size` is equal to the user's screen resolution (EXACT), will cause the freeze.  Hope this helps

**Comment by ByTheQuietLake** [comment]
The very first time I opened project it did take some time to load to fullscreen, but it feels very much like any other app I had to change into fullscreen and nothing felt out of place for me personally, and minimizing was quick. All other subsequent attempts at running the project and switching to fullscreen and back was instantaneous even after opening up the project from the project manager again.

**Comment by girng** [comment]
@avencherus Yeah, I  re-worded my previous posted, my bad! Basically, whenever `Vector2(0, 1)` is added to the `OS.window_size`, the freeze will **not** happen. However, the screen stretches 1 pixel too long and looks weird.

It's happening whenever the `OS.window_size` equals *exactly* the user's `get_screen_size()`. I'm on an NVIDIA card and I don't know if this is reproducible on   AMD cards.

**Comment by akien-mga** [comment]
CC @bruvzg @hpvb

**Comment by bruvzg** [comment]
Indeed, I can confirm this on Windows 10, AMD FirePro D300:

- setting `window_fullscreen` or setting `window_borderless` and `window_size` to `get_screen_size()` - screen turns off for about 2 sec (if multiple monitors connected only one with the app is turned off), after turning back button state is change and no freeze visible. On switching back all monitors turns off for the same delay.
- setting `window_size` to `get_screen_size() + Vector2(0, 1) ` - instant switch forth and back.

On macOS `get_screen_size()` and `get_screen_size() + Vector2(0, 1) ` behaves identically (instant switch), setting `window_fullscreen` plays usual macOS zoom and slide animation with no additional freeze.

No idea why that's happening.

**Comment by girng** [comment]
well then.. i can't reproduce this anymore on the recent 419.17 NVIDIA driver update.

**Comment by Anutrix** [comment]
Was here test for some other issue but found out that this is not reproducible in latest master https://github.com/godotengine/godot/commit/4ee8ecd3efee742be58c1ff191e78d0de09b57b6 on Windows 10 1903 64bit with just Integrated Graphics(Intel HD Graphics 620).

**Comment by akien-mga** [comment]
@avencherus @bruvzg Can you still reproduce it on Windows 10?

**Comment by avencherus** [comment]
@akien-mga Happens still in 393a0152e.

Not easily captured with video capture, so I'll describe it.

1. It shows a black screen with the window lingering over top for a few seconds.
2. It flickers on both of my monitors.  Seems to alternate though, as though it is jumping between them.
3. Resolves to fullscreen.

It can be jarring and messy looking, but nothing exceptionally severe.

I've also noticed that launching the game into a code that does a resize of the window seems to send that Godot logo off center.  (May be unrelated and haven't tested it very much.  But could likely impact some people's opening splash screens in a very unprofessional way.)

![godot windows tools 64_2019-09-23_12-15-16](https://user-images.githubusercontent.com/13004169/65414217-ee890e00-ddfb-11e9-9199-224a05cd52e8.png)

**Comment by bruvzg** [comment]
@akien-mga I can't reproduce it in 393a0152e, Windows 10 - 1903, AMD driver 19.9.2, same hardware and display config as before. Fullscreen switching in instant, no freeze, no flickering.

**Comment by Anutrix** [comment]
Can be closed if not reproducible.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
430.86 Nvidia GeForce 1050 Ti Windows 10 . I see a flicker when I click and move the mouse between the game and another screen  when in Godot's fullscreen (not borderless) and mouse is not trapped. 

I tried to capture it on animated gif but is too fast. 

The flicker shows up when the game loses focus and when it regains focus. It looks like completely gray window for about 200 milliseconds.

**Comment by clayjohn** [comment]
Looks like it was a driver issue.
