### ISSUE TITLE
"class_name" field of property list item is wrong for use defined classes and for at least CanvasItem.material

### ISSUE THREAD

**Issue by DerRidda** [godotengine/godot#25432]
**Godot version:**
Godot 3.1 beta 3

**OS/device including version:**
Linux 64bit ( Solus )

**Issue description:**
The property list returned by Object.get_property_list() includes a field called class_name for each entry. Said field never has the correct class name for any property that has a user defined class set as it's static type. Only the class_name of the last build-in base class is used. 
Might be related to #21789 

Further more, the class name field for the property material of the class CanvasItem has the string "ShaderMaterial,CanvasItemMaterial" whereas the actual class should simply be Material according to the docs. Possible that other classes might have similar behaviour.

In any case, class_name should be atomic and never a list.

**Steps to reproduce:**
Check get_property_list() Method on class that has members with user defined classes and CanvasItem.

**Comment by eranimo** [comment]
This is still a problem in 4.1. `get_property_list` returns an empty string in class_name for properties with types of custom classes

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/21789 (likely due to the same cause).
