### ISSUE TITLE
Debug line drawing

### ISSUE THREAD

**Issue by HuvaaKoodia** [godotengine/godot#25436]
Easily drawing world space debug lines, which are only visible in debug/editor builds, is very useful.

Unity has [Debug,DrawLine](https://docs.unity3d.com/ScriptReference/Debug.DrawLine.html) and [Debug,DrawRay](https://docs.unity3d.com/ScriptReference/Debug.DrawRay.html) for this purpose. Will Godot have something similar?

**Comment by aaronfranke** [comment]
Related: https://github.com/godotengine/godot/issues/16863#issuecomment-430469347

It might be useful to create a general-purpose "Gizmo" node for usage in the editor, which could have subnodes for types of gizmos. Lines could certainly be one of those types.

**Comment by eon-s** [comment]
Since the different nodes have many needs for drawing and the engine already offer methods to draw 2D and 3D, this could be done by a custom node, and be on the asset library (utilities for autoload, children like collision shapes).

**Comment by wyrmling** [comment]
Sorry, but is it not enough to have primitives `draw_*` and `Line2D`?
Or you want to leave them in code and switch off from project settings while building?
Will it have drawback on performance, as GDScript is not a C#?

**Comment by kaadmy** [comment]
This issue doesn't specify 2D or 3D, since 2D already supports immediate line drawing.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/112, as feature proposals are now tracked on the Godot proposals repository.
