### ISSUE TITLE
[Build][MSVC] release_debug produce debug template only

### ISSUE THREAD

**Issue by logicor-cn** [godotengine/godot#25433]
**Godot version:**

3.0.6-stable

**OS/device including version:**

Windows 10 1803
Python 3.6.4
pywin32 224
scons 3.0.1
Visual Studio 2015 14.0.25431.01 Update 3

**Issue description:**

When building `release_debug` target in MSVC environment, only debug export binary got produced.

**Steps to reproduce:**

- Clone `3.0.6-stable` from git repository
- Setup build environment as above
- Run the following command line from `VS2015 x64 Native Tools Command Prompt`
```sh
scons -j8 platform=windows tools=no target=release_debug
```
- Only produces the following files:
```
godot.windows.opt.debug.64.exe
godot.windows.opt.debug.64.exp
godot.windows.opt.debug.64.lib
```

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
That's expected, `release_debug` means "release build (optimized) with debug enabled", which is what is used for the debug export template. Use `release` for the release (optimized, no debug features) template.
