### ISSUE TITLE
Android view/sensor - orientation

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2544]
It looks like the sensor mode for the orientation is not checking which rotation is currently running it is rotating to the default rotation on game start.

**Comment by guilhermefelipecgs** [comment]
I confirm this issue, but I don't see this as a serious problem, because this occurs only when I put my android on the table.

**Comment by AlexHolly** [comment]
Project Settings->Display->Window->Handheld->Orientation->sensor
