### ISSUE TITLE
AndroidManifest.xml Appears to be Corrupted

### ISSUE THREAD

**Issue by Ed-Lang** [godotengine/godot#25445]
**3.06**

**Android :**

**Generated Manifest File Possible cooruption**

**EXPORT from 3.06

[AndroidManifest.zip](https://github.com/godotengine/godot/files/2805394/AndroidManifest.zip)

**

**Minimal reproduction project:**

 Upload failed

Your APK cannot be analyzed using aapt. Error output:

Failed to run aapt dump badging:
W/ziparchive(898794): Zip: Found duplicate entry assets/Control.gdc
W/ziparchive(898794): Zip: Error adding entry to hash table -5
W/zipro   (898794): Error opening archive /export/hda3/borglet/local_ram_fs_dirs/1.prod.play-apps-publisher-app-parser.server.play-apps-publisher-app-parser-prod.354510189015.c8564a224093156f/./local_ram_fs_dir/upload-3019355323000751126.apk: Duplicate entries in archive
ERROR: dump failed because no AndroidManifest.xml found

**Comment by KoBeWi** [comment]
@Ed-Lang Can you still reproduce this in 3.2.2? What are the exact steps?

**Comment by Ed-Lang** [comment]
No please close I reinstalled to latest version which fixed problem
thank you
