### ISSUE TITLE
Physics (2D/3D) profiler switch On/Off continuously

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#25458]
**Godot version:**
Current Master: 35bb52011a4cbcd8ca3779ab1761244f06a33127

**Issue description:**
For some reason the profiler of both 2D physics and 3D physics (Bullet and Godot) switch to on off during the execution.

![ezgif com-video-to-gif 10](https://user-images.githubusercontent.com/8342599/51900024-8b51f380-23b4-11e9-8853-eff9327e8cd7.gif)

**Steps to reproduce:**
1. Switch to Godot physics
2. Start a game
3. Start the profiler

** Side node **
If you want to try the Bullet profiler, use this branch: #24977

**Minimal reproduction project:**
[BodiesAlwaysInstancedAtPos000.zip](https://github.com/godotengine/godot/files/2807051/BodiesAlwaysInstancedAtPos000.zip)

**Comment by akien-mga** [comment]
Seems fixed in the current master branch.
