### ISSUE TITLE
Names of tiles in Tileset are overlap together

### ISSUE THREAD

**Issue by TyTYct** [godotengine/godot#25456]
**Godot version:**

3.1 beta 3

**OS/device including version:**

windows 10 64 bit
GTX 1060 6GB

**Issue description:**

Names of tiles in tileset are overlap together.
It work normal in godot 3.1 beta 2
![image](https://user-images.githubusercontent.com/8284805/51897822-2e6d3200-23e2-11e9-8831-43a08f26c6fd.png)

**Steps to reproduce:**
make many single tile, auto tile. then click display Tile names
![image](https://user-images.githubusercontent.com/8284805/51897715-f36afe80-23e1-11e9-8356-8624e3df0e84.png)

**Minimal reproduction project:**

**Comment by TyTYct** [comment]
After I open this project by godot 3.1 beta 2. This problem goes away

**Comment by Zireael07** [comment]
Looks like a regression between beta 2 and beta 3, then. @MarianoGnu can you take a look?

**Comment by akien-mga** [comment]
I don't see any relevant change between beta 2 and beta 3, so this must be something different.

**Comment by MarianoGnu** [comment]
could be related to GLESS2/3?

**Comment by wyrmling** [comment]
Yes, I'm also don't remember any regressions, there was always a problem with position of tile labels - only if you set any scale, that differs from 1:1.
