### ISSUE TITLE
Godot 3.1 failing to load amdgpu driver on linux; works fine on 3.0

### ISSUE THREAD

**Issue by nazgum** [godotengine/godot#25451]
**Godot version:**
3.1 beta 3

**OS/device including version:**
Ubuntu 18.10
Radeon™ RX Vega M GL graphics

**Issue description:**
Just bought a new Intel Hades Canyon; set it up today and tried loading my game in Godot 3.1 beta to find it fails to load the graphic drivers; when playing the game I get around 35fps (whereas I get 240fps on 3.0, which I set as the cap), and am shown this message:

```
libGL error: Different GPU, but blitImage not implemented for this driver
libGL error: failed to load driver: i965
OpenGL ES 3.0 Renderer: llvmpipe (LLVM 7.0, 256 bits)
```

I tried loading up an older version of my game with godot 3.0 it correctly detects my video card  and runs great:

```
OpenGL ES 3.0 Renderer: AMD VEGAM (DRM 3.26.0, 4.18.0-13-generic, LLVM 7.0.0)
```

This system has both an Intel Integrated GPU and the AMD GPU; for some reason the 3.1 beta seems to be trying to load the driver i965 rather than my amd one; but i965 is not even correct for my intel one, it uses i915.

Happy to provide any futher info to help get this sorted.

**Comment by nazgum** [comment]
Just a quick update, I tried disabling the intel gpu in my bios, and then tried and it worked.  Godot 3.1 can then detect my AMD Card and shows:

```
OpenGL ES 3.0 Renderer: AMD VEGAM (DRM 3.26.0, 4.18.0-13-generic, LLVM 7.0.0)
```

However, this "just worked" on Godot 3.0 with both gpu cards enabled, and it was able to use the AMD one properly there; so somehow in 3.1 this became broke.

**Comment by akien-mga** [comment]
Can you try to run beta3 with `DRI_PRIME=0` to see if it makes a difference?

If so, can you build from the current master branch (after the merge of #25391) to see if it improves the auto-detection? You can then run Godot with the `--verbose` flag to get more information about what Godot detected and decided to use.

**Comment by hpvb** [comment]
The message is expected as we try to see what GPUs exist and there's no API for that yet.
