### ISSUE TITLE
Installing projects in a folder that doesn't exist

### ISSUE THREAD

**Issue by IronicallySerious** [godotengine/godot#25454]
**Godot version:**
3.1 beta

**OS/device including version:**
GTX 1060 6GB on a Ubuntu 18.04

**Enhancement description:**
Installing projects in paths that don't exist should create the path on request. 

**Steps to reproduce:**
Install a project in a folder that doesn't exist. Godot refuses to create this folder on this own or at least ask to create it.

**Comment by IronicallySerious** [comment]
I'd like to work on this if this is a valid issue. If you have some pointers where I can start looking then it'd be of great help to me.

**Comment by not-surt** [comment]
The lack of a Create Folder button is a rather annoying usability issue with the Install Project dialog and is inconsistent with the Create New Project dialog which has it.
Prompting to create a manually entered folder if it doesn't already exist would be a nice edition to both the Create New Project and Install Project dialogs.
You can create a new folder in the Open a Directory dialog when you press the Browse button, but that isn't obvious from the Install Project dialog itself.

**Comment by IronicallySerious** [comment]
@not-surt I posted a few screenshots along with the PR the solves this (#27187). I hope it looks better with the change.
