### ISSUE TITLE
Mono: Wait for debugger not working

### ISSUE THREAD

**Issue by josh18** [godotengine/godot#25461]
**Godot version:**
3.1.beta3.mono.official

**OS/device including version:**
Windows 10

**Description:**
Godot is not waiting for the debugger to connect when playing.

**Steps to reproduce:**
Set `debugger_agent/wait_for_debugger=true`. Open Godot and press F5, game starts straight away even without the debugger connected.

**Notes**
Seems to be working fine for me if I downgrade to 3.1.beta2

**Comment by cbird** [comment]
Can confirm, same behavior for me. Beta2 seem to work just fine.
