### ISSUE TITLE
Font "jumping" when they stay in place but camera is moving.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25464]
**Godot version:**
3.1 35bb520

**OS/device including version:**
Windows 10

**Issue description:**
When I move a Player with camera, then in background I can see that names of fonts are jumping strangely.

**Steps to reproduce:**
Move player outside a camera no-move area
https://streamable.com/xhqrj

**Minimal reproduction project:**
https://github.com/qarmin/Sea-of-Ground

**Comment by Calinou** [comment]
Controls (including their fonts) are snapped to pixels by default, so this is expected. To disable this behavior, uncheck **Gui > Common > Snap Controls To Pixels** in the Project Settings. This should solve the issue, at the cost of making the UI blurrier overall.
