### ISSUE TITLE
Nonexistent signal: caches_cleared when changing scene in TPS demo

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25460]
**Godot version:**
3.1 35bb520

**OS/device including version:**
Windows 10 Intel HD 530

**Issue description:**
When I changing scenes in GLES 2 in editor, then this error is shown:
```
ERROR: Nonexistent signal: caches_cleared
   At: core\object.cpp:1533
```

https://streamable.com/lhmuh

**Minimal reproduction project:**
TPS Demo

**Comment by akien-mga** [comment]
The signal is defined in `scene/animation/animation_player.cpp`, and is handled in `scene/animation/animation_tree.cpp`:
```
$ rg caches_cleared
scene/animation/animation_tree.cpp
781:                            old_player->disconnect("caches_cleared", this, "_clear_caches");
786:                    player->connect("caches_cleared", this, "_clear_caches");
1298:                           old_player->disconnect("caches_cleared", this, "_clear_caches");

scene/animation/animation_player.cpp
1359:   emit_signal("caches_cleared");
1662:   ADD_SIGNAL(MethodInfo("caches_cleared"));

scene/animation/animation_tree.h
267:    void _caches_cleared();
```

**Comment by CowThing** [comment]
This error happens whenever an active AnimationTree node is removed from the scene tree.
