### ISSUE TITLE
Crash when editing shader

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#25479]
**Godot version:**

6e600706e9c0d2d08ea4cf57b7cda423de1a45fd Mono

**OS/device including version:**

Ubuntu 18.10 AMD ATI Radeon HD 7770/8760 

**Issue description:**

When editing a canvas shader, either via code or via visual shaders, the editor will crash with the following error:

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
```

Appears to happen when it is saved.

**Comment by Chaosus** [comment]
I could not reproduce it on 35bb520, can you post an example project ?

**Comment by somnivore** [comment]
Tried again with 35bb52011a4cbcd8ca3779ab1761244f06a33127 and all is well, must've been fixed since then.
