### ISSUE TITLE
Error when obtaining magnetometer data

### ISSUE THREAD

**Issue by Saikol** [godotengine/godot#25477]
Godot version:
Godot 3.1 Beta 3

OS/device including version:
Samsung J2 Pro (version: Android 7.1)
OpenGL ES 3.0
Procesador de GPU: Adreno TM 308

Issue description:
I'm trying to get the magnetometer data but I can not get anything.
I'm doing it through this code:
                 print(str(Input.get_magnetometer ()))
Does anyone know if the way to obtain it has changed or does not work?

**Comment by Saikol** [comment]
not that way it works for me, but in version 2.5 and 3.0.6 if it does.
Thanks anyway.

**Comment by volzhs** [comment]
sorry, I couldn't follow you.
so... is your problem still valid? or fixed?
