### ISSUE TITLE
3D models in TPS Demo with GLES 2, show crashed graphics

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25484]
**Godot version:**
3.1 35bb520

**OS/device including version:**
Windows 10

**Issue description:**
Some of the models show crashed graphics in GLES 2, when I try open TPS Demo project

**Steps to reproduce:**
Just open scene testlevel/level.tscn
https://streamable.com/k8ppr

**Minimal reproduction project:**
https://github.com/godotengine/tps-demo

**Comment by reduz** [comment]
I can't reproduce this. What is your GPU and driver version?

**Comment by qarmin** [comment]
Intel HD 530
Driver: 23.20.16.4973 - latest, Windows Update and Intel Driver and Support Assistant

Later I check if this problem exists on Ubuntu with GTX 970 and HD 3000

**Comment by qarmin** [comment]
It happens also with GTX 970 415.27? on Ubuntu 18.04.

**Steps to reproduce**
1. Check in editor options "Restore Scenes On Load"
2. Open ONLY testlevel/level.tscn and testlevel2.tscn
3. Restart Editor
4. Switch scene level.tscn <---> level2.tscn until bug appear
