### ISSUE TITLE
Editor complains about cyclic dependency even when none exists as of 3.1 beta 3

### ISSUE THREAD

**Issue by novemberisms** [godotengine/godot#25483]
**Godot version:**

Godot v3.1 beta 3

**OS/device including version:**

Any

**Issue description:**

It seems like there have been improvements to typed GDScript that now allows a script to use its given `class_name` for type hints in its own script without causing a cyclic dependency error. (Addressing part of [my previous issue](https://github.com/godotengine/godot/issues/25252))

However, if you then reference that class in another script file, the editor will complain that there is a cyclic dependency issue. If you run the project, however, no errors occur.

**Steps to reproduce:**
1. Attached is a minimal reproduction project. Open `main.gd` in the code editor and observe an error being raised. 
2. Run the project
3. Observe the program run and exit successfully without any errors, printing "Hello" to the output

**Minimal reproduction project:**

[ClassNameIssuev3.1beta3.zip](https://github.com/godotengine/godot/files/2811075/ClassNameIssuev3.1beta3.zip)

I suspect this is just the editor not being informed of the changes. I'm making an issue just in case nobody has noticed this yet. Thanks for all your hard work!

**Comment by akien-mga** [comment]
I've seen that too, it's caused by a recent commit by @reduz (probably 11642b92d1b72154268edcde76b0b53d309e22eb).

**Comment by reduz** [comment]
@vnen It is now illegal to call load() on a resource while it's being loaded. This may be a problem with optional typing so please give it a check.

**Comment by reduz** [comment]
I dont see the error myself, though

**Comment by reduz** [comment]
Kicking this for later, since itś not obvious how to best deal with this for now.

**Comment by Houkime** [comment]
Cannot observe this in Godot 197b65f on Arch Linux
(one needs to comment out _process otherwise it doesn't have enough time to print hello it seems).

**Comment by vnen** [comment]
Tested and it's working fine, no error reported. The `Hello` message is being printed for me.
