### ISSUE TITLE
Crash on 3.1 beta 3 after creating GLES2 project due to default environment

### ISSUE THREAD

**Issue by Vikram1323** [godotengine/godot#25482]
Godot Version:
3.1 beta 3

OS/device including version:
Dell Inspiron 1464, Windows 7 64 bit

Issue description:
Godot engine has stopped working after creating GLES2 (Thank you for adding options while creating a new project) project.

Steps to reproduce:
Create a new project.
Select GLES2.
Then click on create and edit. 

Minimal reproduction project:
Create a new project.

Workaround:
Remove default_env.tres from the project folder.
or 
Open project.godot (inside the project folder) in a text editor and remove:
[rendering]
environment/default_environment="res://default_env.tres"

**Comment by akien-mga** [comment]
What is your GPU model and driver?

**Comment by Vikram1323** [comment]
Graphics Chipset	ATI Mobility Radeon HD 4300 Series
Driver Packaging Version	8.97.100.11-130429a-158498C-ATI
Did I miss anything?

**Comment by Zireael07** [comment]
Same problem on Radeon 6630M and beta 3.
Drivers: https://www.dell.com/support/home/pl/pl/rc1078552/drivers/driversdetails?driverid=8v6kh

**Comment by bruvzg** [comment]
Probably irrelevant information: OS X 10.9.5 VM (VirtualBox 6.0.4 running on macOS 10.14.3 host) without hardware acceleration (using Apple Software Renderer) crashes (whole VM not just Godot) when `default_env` is present in both GLES2 and GLES3 modes. Few month ago at least GLES3 mode with `default_env` was functional, I do not remember wether I tested GLES2 or not.

**Comment by akien-mga** [comment]
Is this still reproducible in 3.1 beta 8 or later?

**Comment by Vikram1323** [comment]
Godot Version:
3.1 beta 8 (64 & 32 bit)

No crash. You can close this now. 
Thanks :):):)

**Comment by Vikram1323** [comment]
@akien-mga I realized I can close :):):):)
