### ISSUE TITLE
Cannot fold/unfold the remote inspector after unfolding/folding it

### ISSUE THREAD

**Issue by MattUV** [godotengine/godot#25487]
**Godot version:**
3.1 beta 3

**OS/device including version:**
Windows 8.1 and 10

**Issue description:**
In the remote inspector, if you fold the tree **from the root**, you cannot unfold it anymore.
It briefly unfolds before folding again.
Sometimes, it is the opposite : when you fold it, it automatically unfolds. I cannot find a rule.

![bug inspector](https://user-images.githubusercontent.com/13215043/51970635-b5201e80-2477-11e9-82d4-c544814856c2.png)

You have to restart the engine to have the unfolded view.
Note that it does not affect the folding of subnodes. Only the root node acts this way.

It may be related to #19006

**Steps to reproduce:**
1. create a scene with at least 1 node
2. launch the program and go to the remote inspector
3. try to fold/unfold the root node

**Comment by syskrank** [comment]
I can reproduce this bug on Linux Mint 19 x64 as well.
