### ISSUE TITLE
Directional spotlight in 2D, with shadows

### ISSUE THREAD

**Issue by mjtorn** [godotengine/godot#25486]
**Godot version:** 3.0/3.1 feature request

**OS/device including version:** N/A, but mainly desktops, I suppose

**Issue description:**
[Originally featured on the Q&A forum](https://godotengine.org/qa/40039/how-to-achieve-dynamic-directional-2d-lighting-and-shadows?show=40074)

It would be useful for creating modern-feeling 2D games with ambient light if spotlights weren't limited to 3D.

I'm hoping for something like [this](https://youtu.be/VDcWSEs856k?t=948) in a Unity3D tutorial video. He
doesn't go into shadows there, but it would only be natural to have some means of implementing shadows
under characters or items as well.

Bonus points for some kind of light-emitting map ;)

This is one of those feature requests where I'd be open to negotiate a bounty contract, or something, because it's pretty important.

I don't know about the implementations or spatial geometry, but it feels like you could take the `Light2D` code, give it a width angle aside the rotation, and alter it so the shadow it casts isn't infinitely long. Am I oversimplifying?

Thanks!

**Comment by groud** [comment]
Well you simply have to use a light2d texture with a cone drawn inside. If you use a 2d light occluder you can achieve the shadows too.

**Comment by groud** [comment]
Everything you describe is already possible I think.

**Comment by mrcdk** [comment]
Yeah, I don't see anything special in that tutorial that can't be done in Godot right now. I don't see any shadow per se in that tutorial either it's just normal maps.

https://streamable.com/dg0pl project (godot 3.1) [gothicvania_light.zip](https://github.com/godotengine/godot/files/2812144/gothicvania_light.zip)
I made that in about 10 minutes. It's really messy but you can get an idea on how to do it.

**Comment by mjtorn** [comment]
@groud let me demonstrate with screenshots, now that I'm at the office and can do so.

![iscw-longshadow-1](https://user-images.githubusercontent.com/78427/51978340-9d09c880-2492-11e9-95a2-4c939b8d25c3.png)

The shadow is infinitely long, which makes no sense.

![iscw-longshadow-2](https://user-images.githubusercontent.com/78427/51978377-b7dc3d00-2492-11e9-9d46-e4fac93ee4ee.png)

This doesn't really make sense either, that the infinite shadow is cast outside the cone texture.

-----

From a performance point of view, I should say what I said on the forum, that running the game with that texture completely chokes up the GPU, a fairly modern Radeon RX470 (or whatever RX470/480 according to Linux is). This also leads me to believe something else might be more performant.

@mrcdk the video looks really good! I downloaded 3.1b3 and tried it out for myself and the GPU kicked off so hard my desk started vibrating and the GPU still hasn't returned to normal minutes later. Just having the project open in the editor makes the GPU sound off.

Your Gothicvania uses a substantially smaller resolution, yet the outcome is worse, so could there be something bad in the texture-handling code? Would some kind of `SpotLight2D` without textures be faster?

Testing with GLES2, I got nothing, all's black.

Do I need to worry about my drivers? The drivers of a potential customer base?

------

And, sure, there are no shadows in that video I referred to, but I was thinking lights and shadows go so tightly together that I'd combine them in one issue. Should I open another one for a better `LightOccluder2D` or something?

I also checked the 2.1 example I got from @StraToN. It uses a drawn, brown-colored sprite-based shadow, and a `CanvasItemMaterial` with a fragment shader script. I don't know the shading language but it doesn't appear to actually react to light, so maybe the need isn't as dire for new lights as it is for new shadows.

**Comment by groud** [comment]
Well, ok the current system has limitations. We may find a way to define "émission areas" on the texture so that the shadows get blurred. But that has nothing to with the original issue.

The performance issue is another problem too, might be worth checking if an issue exists about it or open another issue.

**Comment by mrcdk** [comment]
I'm on Nvidia, yes. The project is also using more effects than light2D
like glow and tonemaping. Try removing the worldenvironment node and see if
it runs better.

Again, the unity3d tutorial you posted or my project use any shadow. They
only use normal maps. I don't think you can get any shading successfully
without them.

**Comment by avencherus** [comment]
I also feel like there is more bells and whistles that can be done to the 2D lighting system, but this only comes from experiences with seeing these effects in other games.  It is most certainly done more directly with hand tailored shading, and I wouldn't have enough rendering experience to articulate what names these effects go by.

I've tried to recreate some of these effects and can get close, but it often feels like if there were some extra parameters to control aspects of the light or shadow it could be achieved.  Though maybe it is achieved with better masks and techniques...

I suspect though that many of the nuanced effects are just small manipulations, but ones not available in the Light2D.

Off the top of my head I think of things like crepuscular rays that I see in some games, it is like a gradient and blurring effect on the light as they pass by occluders, creating glare.

A game I can last recall seeing it was in Dead Cells.

![images](https://user-images.githubusercontent.com/13004169/52029394-b440c880-251b-11e9-8dd9-29b9ee082579.jpg)

**Comment by mjtorn** [comment]
As cool as it would be to have `LightOccluder2D` and/or pure shaders do the heavy lifting, the immediate concern is fixed by https://github.com/godotengine/escoria/pull/262 - even though I expect the code to evolve a bit still.
