### ISSUE TITLE
Skeleton set_bone_ignore_animation() weird behaviour

### ISSUE THREAD

**Issue by MrCrowley2** [godotengine/godot#25498]
**Godot version:**
3.1 Beta 3

**OS/device including version:**
Kubuntu 18.04

**Issue description:**
I don't know if set_bone_ignore_animation() is working correctly in the Skeleton class.
I would expect to turn off the animation for a specific bone with this command.

- If I have an AnimationPlayer that plays a run animation and I set:
`var b = skel.find_bone("UpperArm.R")
    skel.set_bone_ignore_animation(b, true)`
The animation plays normal and the upper arm moves

- If I use AnimationTree I get random transformations on the whole model. Depending on the bone I deactivate, the model is rotated in random directions, but the specified bone still moves.

**Steps to reproduce:**
I attached an example project.
The project has a script that sets ignore_animation for the right arm.

- when loaded the AnimationTree is deactivated and the AnimationPlayer starts the walk cycle.
Both arms move normal. ignore_animation is not working.

- When you activate the AnimationTree and run the scene, the run cycle is played. the ignore animation call from the script results in a very unnatural upper body movement, not in a static upper arm

- if you change the ignored bone to "r-leg" in the script and use the tree player, the whole body rotates around the z-axis

**Minimal reproduction project:**
[ignoreAnimationBug.zip](https://github.com/godotengine/godot/files/2814640/ignoreAnimationBug.zip)

**Comment by akien-mga** [comment]
The method `set_bone_ignore_animation()` was removed in d81ddaf33ecddab1c83bc964b0bee4328b7f7b06, so this is no longer application for 3.2+.
