### ISSUE TITLE
Entering freelook in spatial editor while opening 2D project makes mouse invisible

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#25491]
**Godot version:**
3.1.beta master

**OS:**
Windows 10

**Issue description:**
Accidentally entering freelook in spatial editor while opening 2D project makes mouse invisible, while being responsive to mouse movement and other events, uncaptured.  The spatial editor is shown by default until 2D scene is loaded. Have to restart the editor to recover.

**Steps to reproduce:**
1. Prepare to open any existing 2D project with a main scene defined.
2. Open the project and be quick to enter freelook in spatial editor (clicking and holding RMB, for instance), while the project's main scene isn't loaded yet. This is easier to reproduce on medium/large sized projects when loading takes more time.
3. When the editor switches to 2D on load, the mouse remains invisible.

**Comment by Zylann** [comment]
The fact that the 3D viewport gained focus while Godot is loading the project sounds quite wrong...

**Comment by Xrayez** [comment]
Figured this one is more easily reproducible if you open a bunch of scenes and turn on `Restore Scenes On Load`. Then you'll have to restart the project, and repeat reproduction steps, loading lots of scenes should force the editor to stuck at spatial editor.
