### ISSUE TITLE
Displaying versions of projects in Project Manager

### ISSUE THREAD

**Issue by kkmzero** [godotengine/godot#25497]
Feature Request for Project Manager - Project Manager could display version information about projects. If you have many projects created on different versions of Godot, sometimes you might lose compatibility of some features, so you optimally want to finish the project (or create patches/updates) on version of Godot which is suitable for your project and/or newer if you re-import it and you know it will work. Project could have some version information line displayed next to it, just for keeping better order of your projects before you open them.

![godotpp](https://user-images.githubusercontent.com/32756443/52013373-2940dd80-24dd-11e9-85d9-09a5504f4d22.jpg)

**Comment by syskrank** [comment]
I've made a first-approach attempt to add this little feature.

However, I faced the fact that **project.godot** file contains the property **'config_version'** as a single int number. Which is a bit counter-intuitive for user to see in the GUI part. 

I don't want to make a PR yet. What are the options here besides some kind of hash table to match **config_version** against actual engine version?

**Comment by syskrank** [comment]
As far as I understand, **config_version** deals with the project.godot file format, not with the engine version itself. 
So it would be a harsh move to change that to a full-fledged engine version string or hash.

Although, Godot has similar mechanism for minor/major/patch numbers: one could locate it within **version.h** and **version_generated.gen.h**

**Comment by Zylann** [comment]
In Unity that information is available in a separate ProjectVersion.txt, which allows their project manager to show and check versions. Even if the project.godot format does not change, it may matter for users due to features they rely on or bugs in other versions.
If a TXT file is too messy, maybe we can put this in a header section of the project.godot file (so we don't need to parse it entirely), and if it's not present then we infer the version from `config_version`?

**Comment by syskrank** [comment]
I wonder if it's okay to add this functionality/version field right now. 
On the other hand, we have much of backward-incompatible features in 3.1 vs 3.0.*, so maybe it's time :)
Having a separate text file seems okay, though.

**Comment by aaronfranke** [comment]
Related: https://github.com/godotengine/godot/pull/25899

**Comment by twoco** [comment]
It's a gamble to open a project with unknown Godot version. In best case I wish the latest Godot version will convert the project or tell me: Sorry, this project comes from older unsupported Godot version (x.y.z). Just want to know that. Currently the only thing I get is when I try to open a scene: Unexpected end of file. -.-

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/237, as feature proposals are now tracked on the Godot proposals repository.
