### ISSUE TITLE
get_simple_path not working with overlapping NavigationPolygons

### ISSUE THREAD

**Issue by bretzl** [godotengine/godot#25490]
**Godot version:**
3.1 Beta 3 official

**OS/device including version:**
Linux / Debian 9

**Issue description:**
Get get_simple_path with Navigation2D does not work with overlapping NavigationPolygons. Maybe i am wrong because i am new to Godot but if i have two NavigationPolygonInstances including overlapping NavigationPolygons, the get_simple_path does not work as expected.

**Steps to reproduce:**
Create Navigation2D node with two NavigationPolygonInstances attached including ovelapping NavigationPolygons.

See sample project. 

**Minimal reproduction project:**
[OverlapNavigation.zip](https://github.com/godotengine/godot/files/2812641/OverlapNavigation.zip)

**Comment by Zireael07** [comment]
Polygons must have vertices that are exactly identical. If there are gaps/overlaps, navigation won't work. Same for 3D by the way.

**Comment by blumomatic** [comment]
Thank you for the information.  Please close the issue.

**Comment by bretzl** [comment]
Thank you for the information. Please close the issue.

**Comment by Xrayez** [comment]
Could it be that the issue can be fixed by merging polygons first? I've never got to use Navigation2D though.

**Comment by Zireael07** [comment]
@Xrayez: It probably would.

**Comment by bretzl** [comment]
I figured out that even when overlapping polygons exists inside one NavigationPolygon the get_simple_path fails: 
![navigationpoly](https://user-images.githubusercontent.com/46541699/52114201-b84c1380-260b-11e9-9498-fb30f386c1f5.png)
This will not work. Of course i can fix my code for the polygon generation but a 'merge/intersect polygon' function would be really great.

**Comment by mjtorn** [comment]
@Zireael07 
> Polygons must have vertices that are exactly identical. If there are gaps/overlaps, navigation won't work.

What does that mean in practice? That it's possible to have two `NavigationPolygonInstance`s but they must have some vertices at the exact same pixel locations?

**Comment by Zireael07** [comment]
Yes, if you have two navigation polygons, they must have two vertices at exact same pixel locations, so that they have common edges.

**Comment by mjtorn** [comment]
Thanks for telling me! What's the best way of achieving that? The editor (3.0.6 at least) makes it a bit hard, as selecting `NavigationPolygonInstance2` hides the vertices for `NavigationPolygonInstance` :(

**Comment by Zireael07** [comment]
When I tried doing that, I set all values from script. However, that was a lot of scripting for relatively little gain and lots of problems, so I just abandoned it and went back to using a single navigation polygon instance.

**Comment by mjtorn** [comment]
I missed your reply while digging into this... I found I can leverage pixel snapping, at least in this case, to enforce the vertices to the same positions.

My tests indicate snapping is sufficient, so I thank you, and hope I can figure out any future problems if they arise :)

**Comment by shayneoneill** [comment]
Polygon merging WOULD be really useful because I've spent 3 days banging my head on the wall trying to figure it out. Its just not a particularly intuitive piece of information to guess at, and I couldn't find anything in the docs about it.

Uh, not sure if Godot already has any polygon math that could be yeeted into a function to do this, I mean it must have somewhere right, its a 3D engine? 

If not https://doc.cgal.org/latest/Boolean_set_operations_2/index.html and its way beyond my dumb-brain math. 

But now I know about the adjacent vertex thing, I've finally got this thing working, so thanks <3

**Comment by Zireael07** [comment]
I think the Geometry class now has something about merging polygons?

**Comment by Xrayez** [comment]
Yes, it's `Geometry.merge_polygons`, but that only works on 1v1 polygon as the rest of operations for simplicity, but might not be enough if you need to merge multiple polygons. If you do need such a method, please describe your use cases at godotengine/godot-proposals#913.
