### ISSUE TITLE
[BUG]: 2.0 Html5 Nightly Build (09/28/15) Issues

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#2550]
While giving a test run with the HTML 5 Export, I've noticed a few things that were not working, this was from the 09/28/15 Nightly Build version:

-default_clear_color doesn't show the right background color,
-Input map from project settings doesn't receive or send any new input or accept any new custom import maps to the exported Html5 game, mostly stays on on the regular ui mapping keys.
And
-The mouse isn't captured or hidden.

**Comment by eska014** [comment]
Please submit issues that are unrelated to each other individually. It's easier to manage.

**Comment by eska014** [comment]
I split up the former two issues described into #2761 and #2766.
Mouse capturing works for me with `Lock/hide mouse pointer` on in fullscreen.
