### ISSUE TITLE
Picking a Windows icon file in the export dialogs sets a local path

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#25513]
**Godot version:**
463123a

**Issue description:**
When picking a Windows icon file (.ico) for the Windows export preset via the FileDialog, it will set it as a local path, instead of a relative one ("/home/user/project/icon.ico" instead of "res://icon.ico").

**Comment by Kanabenki** [comment]
Moreover, I noticed it allows to pick a file outside of the project directory, whereas for MacOS for example, you must choose an icon within the project.
