### ISSUE TITLE
MenuButton Label dissapears when a shortcut is set.

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#25519]
**Godot version:**
Latest from: https://hugo.pro/projects/godot-builds/ (v3.1.beta.calinou.c21ca98)

**OS/device including version:**
Windows 10

**Issue description:**
MenuButton items lose the label when a shortcut is set.

**Steps to reproduce:**
1. Create new scene with a Control node as the root
2. Add MenuButton node
3. Add this code to the root node:
```
extends Control

func _ready():
	# Add items
	$MenuButton.get_popup().add_item("I'm a regular item")
	$MenuButton.get_popup().add_item("I am not")
	
	# Create the shortcut
	var shortcut = ShortCut.new()
	var inputeventkey = InputEventKey.new()
	inputeventkey.set_scancode(KEY_Q)
	inputeventkey.control = true
	shortcut.set_shortcut(inputeventkey)
	
	# Set shortcut
	$MenuButton.get_popup().set_item_shortcut(1, shortcut, true)
```

4. Run project and check how the label on the second menu item is gone.

**Minimal reproduction project:**
[MenuButtonItemBug.zip](https://github.com/godotengine/godot/files/2818183/MenuButtonItemBug.zip)

**Comment by akien-mga** [comment]
Reopening as #25841 is being reverted.

**Comment by akien-mga** [comment]
For the reference, the fixes proposed so far (#25841, #25902) were insufficient, as it appears that the editor uses this "bug" as a feature.

See e.g. this debug output for the "Scene" popup menu:
```diff
diff --git a/scene/gui/popup_menu.cpp b/scene/gui/popup_menu.cpp
index a7c6c5cca..f13d74d96 100644
--- a/scene/gui/popup_menu.cpp
+++ b/scene/gui/popup_menu.cpp
@@ -520,6 +520,13 @@ void PopupMenu::_notification(int p_what) {
                                }
 
                                String text = items[i].shortcut.is_valid() ? String(tr(items[i].shortcut->get_name())) : items[i].xl_text;
+                               {
+                                       // debug stuff
+                                       print_line("--------");
+                                       print_line("xl_text: " + items[i].xl_text);
+                                       print_line("shortcut name: " + (items[i].shortcut.is_valid() ? tr(items[i].shortcut->get_name()) : "[No shortcut]"));
+                                       print_line("shortcut as text: " + _get_accel_text(i));
+                               }
 
                                item_ofs.x += items[i].h_ofs;
                                if (items[i].separator) {
```
```
--------
xl_text: 
shortcut name: New Scene
shortcut as text: None
--------
xl_text: 
shortcut name: New Inherited Scene...
shortcut as text: None
--------
xl_text: 
shortcut name: Open Scene...
shortcut as text: Control+O
--------
xl_text: 
shortcut name: Reopen Closed Scene
shortcut as text: Control+Shift+T
--------
xl_text: Open Recent
shortcut name: [No shortcut]
shortcut as text: 
--------
xl_text: 
shortcut name: [No shortcut]
shortcut as text: 
--------
xl_text: 
shortcut name: Save Scene
shortcut as text: Control+S
--------
xl_text: 
shortcut name: Save Scene As...
shortcut as text: Control+Shift+S
--------
xl_text: 
shortcut name: Save All Scenes
shortcut as text: Control+Shift+Alt+S
--------
xl_text: 
shortcut name: [No shortcut]
shortcut as text: 
--------
xl_text: 
shortcut name: Quick Open...
shortcut as text: Shift+Alt+O
--------
xl_text: 
shortcut name: Quick Open Scene...
shortcut as text: Control+Shift+O
--------
xl_text: 
shortcut name: Quick Open Script...
shortcut as text: Control+Alt+O
--------
xl_text: 
shortcut name: [No shortcut]
shortcut as text: 
--------
xl_text: Convert To...
shortcut name: [No shortcut]
shortcut as text: 
--------
xl_text: 
shortcut name: [No shortcut]
shortcut as text: 
--------
xl_text: 
shortcut name: Undo
shortcut as text: Control+Z
--------
xl_text: 
shortcut name: Redo
shortcut as text: Control+Shift+Z
--------
xl_text: 
shortcut name: [No shortcut]
shortcut as text: 
--------
xl_text: 
shortcut name: Revert Scene
shortcut as text: None
--------
xl_text: 
shortcut name: Close Scene
shortcut as text: Control+Shift+W
--------
xl_text: 
shortcut name: [No shortcut]
shortcut as text: 
--------
xl_text: 
shortcut name: Quit
shortcut as text: Control+Q
```
Only two of the above have a valid `xl_text`, while others rely on the shortcut name.

**Comment by arnoldochavez** [comment]
I see, with that in mind I find a workaround, assigning a resource_name to the ShortCut solves the problem and displays the label correctly

`
var mb := MenuButton.new()
var popup := mb.get_popup()
var shortcut : ShortCut
mb.text = "file"
popup.add_item("New item")
shortcut = ShortCut.new()
shortcut.resource_name = "New item"
shortcut.shortcut = InputEventKey.new()
(shortcut.shortcut as InputEventKey).scancode = KEY_N
(shortcut.shortcut as InputEventKey).control = true
popup.set_item_shortcut(0, shortcut)
add_child(mb)
`

**Comment by akien-mga** [comment]
I'm working on a proper fix so that `xl_text` is always defined (inferred from the shortcut name when relevant).

**Comment by View-my-Git-Lab-krafi** [comment]
var Shortcut = Shortcut.new()
	var inputeventkey = InputEventKey.new()
	inputeventkey.set_scancode(KEY_Q)
	inputeventkey.control = true
	Shortcut.set_shortcut(inputeventkey)
	
	$MenuButtonFile.get_popup().set_item_shortcut(4, Shortcut,  true)
	


how can i write this in gdscript 4

**Comment by View-my-Git-Lab-krafi** [comment]
$MenuButtonFile.get_popup().set_item_shortcut(4,set_shortcut(KEY_Q), true)
	
func set_shortcut(key):
	var shortcut = Shortcut.new()
	var inputeventkey = InputEventKey.new()
	inputeventkey.set_scancode(key)
	inputeventkey.control = true
	shortcut.set_shortcut(inputeventkey)
	return shortcut

godot 4.2: Invalid call. Nonexistent function 'set_scancode' in base 'InputEventKey'.
