### ISSUE TITLE
Focus is not set when switching between Vertex, Fragment, Lighting shader tabs

### ISSUE THREAD

**Issue by ratsdiov** [godotengine/godot#2551]
1.1Stable on Windows 7.  To reproduce:

1) Create a new material/shader
2) Start typing in the Vertex shader
3) Click the Fragment shader tab *without clicking in the editor window*, just click the tab
4) Start typing - the entered text goes in the Vertex shader editor pane

i.e. selecting one of the shader tabs does not set the focus to that tab's editor.

**Comment by akien-mga** [comment]
Thanks for the report. Could you try a recent nightly build of the upcoming version 2.0 to check if it is still valid? (make sure to backup your project files first if you are not using a VCS).
