### ISSUE TITLE
Dynamic GI probe bug

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#25514]
Godot 3.1 beta 1
Win 7 64 bits

Gi probe does no more work dynamically with emissive materials.
In a scene with no lights, the emissive material does not lighten the scene.

https://raw.githubusercontent.com/DevMagicLord/Godot3/master/bugs/A/giprobebug.png

Project download
https://github.com/DevMagicLord/Godot3/blob/master/bugs/A/Glow.zip

**Comment by novemberist** [comment]
Are you using CSGs in your scene? Then this might be related to https://github.com/godotengine/godot/issues/25393

GIProbes still work fine with regular MeshInstances for me though

**Comment by DevMagicLord** [comment]
No i use cube MeshInstances only.

**Comment by novemberist** [comment]
Have you enabled the "use in baked lighting" checkbox for all meshes, including your emitter?

**Comment by DevMagicLord** [comment]
With "use baked lighting", it works.
I forgot Gi Probe does not have any dynamic options, it can only be baked.
