### ISSUE TITLE
SpotLight light not working on Android when its Shadow is enabled

### ISSUE THREAD

**Issue by TIBI4** [godotengine/godot#25526]
**Godot version:**
3.1 beta 3

**OS/device including version:**
Android/Xiaomi 4A/Adreno 308

**Issue description:**
- All below in Android export.
- SpotLight is not working when Shadow is enabled (no light, no shadow), but DirectionalLight and OmniLight work as expected with or without Shadow enabled.
- SpotLight works when Shadow is disabled (only light).
- SpotLight should work when Shadow is enabled (light and shadow).

**Image from Editor info:**
_In the back: OmniLights
In the front: SpotLights
In the left: Shadow=on
In the right: Shadow=off_
![image](https://user-images.githubusercontent.com/25259582/52081620-707cac00-2579-11e9-8803-0cd025b01c33.png)
As you can see, in the Editor (runned by F5), in the left SpotLight there _is light **and** shadow_, but in the Android export, there is not _light **or** shadow_.

**Steps to reproduce:**
- Export the uploaded .zip to Android.
- Run it on Android.

**Minimal reproduction project:**
[Zipped.zip](https://github.com/godotengine/godot/files/2818851/Zipped.zip)

**Comment by volzhs** [comment]
check this #24710

**Comment by akien-mga** [comment]
> check this #24710

As per the above it seems to be expected, can you confirm that you get similar results on Android and desktop if you change the Vertex Shading option?

**Comment by norrath-hero** [comment]
Fixed by https://github.com/godotengine/godot/pull/69826

**Comment by akien-mga** [comment]
Fixed by #69826.
