### ISSUE TITLE
Event Player broken

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#2553]
Looking at Event Player (event_player.cpp) it seems to be a Mod file player. So i tried to load a free .s3m, .xm and .mod file, but is impossible to load a file without an infinite loop error on console who locks the IDE.
Looped error on console: ![Image](http://i.imgur.com/23EI54O.png)
Project with the files and event player ready to load and lock the ide: 
https://dl.dropboxusercontent.com/s/wessjzl4y93o3jb/eventplayer.zip?dl=0

**Comment by reduz** [comment]
thanks, will check

**Comment by kopias** [comment]
godot 2.0 rc1 win7x64
using example form first post

the EventPlayer is working with provided music files using Stream:"Load" but as soon as you use "Clear" option godot crashes

**Comment by akien-mga** [comment]
Please open a new issue, the cause might be related but maybe not, and this report was closed a while ago already :)
