### ISSUE TITLE
Animation Tree ignores track on/off state from AnimationPlayer

### ISSUE THREAD

**Issue by MrCrowley2** [godotengine/godot#25537]
**Godot version:**
3.1 Beta 3

**OS/device including version:**
Kubuntu 18.04

**Issue description:**
I found this while working with a 3D Armature.
When using animations with the AnimationTree, the track on/off status is ignored.
- using only the AnimationPlayer I can disable parts of the animation by setting the track to "off"
- Playing an animation with disabled tracks in the AnimationTree, the on/off status of the track is ignored. It always plays the complete animation with all tracks.

**Steps to reproduce:**
- load 3d model with animation
- play animation in animation player. You can turn off tracks with on/off button
- load animationPlayer into AnimationTree
- all tracks are playing, even the disabled ones

**Comment by akien-mga** [comment]
Confirmed in the current master branch.

**Comment by yougotwill** [comment]
This also happens on macOS and my fan starts working overtime because I can't turn off the animations in the AnimationTree without quitting Godot.

**Comment by akien-mga** [comment]
Seems still reproducible in current `3.x` and `master` branches from a quick test. I don't have time to prepare one but if someone wants to make a minimal reproduction project for both `3.x` and `master` with a simple animation model, that would be great.
