### ISSUE TITLE
Game crash after compiling Godot 3 for Android

### ISSUE THREAD

**Issue by Lucky0710** [godotengine/godot#25531]
Operating system or device - Godot version:
Windows 10. Godot 3.0.6

Issue description:
My app crashes on an Android device after compiling godot. Exporting the app works fine, and there is no errors during the build of release.apk and debug.apk.

Steps to reproduce:
- set up the buildsystem following this tutorial : http://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html#compiling-export-templates
- on the Godot code source execute 
scons platform=android target=release android_arch=armv7
scons platform=android target=release android_arch=arm64v8
scons platform=android target=release_debug android_arch=armv7
scons platform=android target=release_debug android_arch=arm64v8
- build the export templates with Gradlew
- install the resulting apks in godot and export your project for Android
- Try to run it

This is my first important project and i am trying to compile it since 4 days non-stop, i would apreciate if you give me some help ! Thanks in advance.

(sorry for my english, i'm french by the way :) )

**Comment by Lucky0710** [comment]
Sorry, Maybe i was unclear, but the app works perfectly when it is exported with the defaults templates from Godot 3.0.6. 

It is only when i compile and try to export with the new templates that the app crashes.

**Comment by volzhs** [comment]
I personally compile and use it on android with master but I am fine with it.
what adb logcat said for crash?

**Comment by Lucky0710** [comment]
I will check for adb logcat as soon as possible to send your the error message, thnak you for trying to help :)

**Comment by LinuxUserGD** [comment]
The templates should be the same version as Godot.

**Comment by Lucky0710** [comment]
I think they are, otherwise Gradlew build would have not completed

**Comment by LinuxUserGD** [comment]
But 3.0.6 is not master (3.1).

**Comment by Lucky0710** [comment]
So do i need to download an older version of master ?

**Comment by LinuxUserGD** [comment]
Yes, git reset --hard commit.

**Comment by Lucky0710** [comment]
Sorry i didn’t understand where do i need to use this command, i’m not really an expert at this :)

**Comment by LinuxUserGD** [comment]
git clone godot.git to get the source code
git pull to update to master
git reset --hard commit to move to an older commit
Git has to be installed, command s in terminal
