### ISSUE TITLE
Transparency not rendered with GLES2 (3.1 beta3)

### ISSUE THREAD

**Issue by wombatstampede** [godotengine/godot#25536]
**Godot version:**
Godot 3.1 beta3 (error did not occur in 3.1 beta2)
GLES2 only (works correctly in GLES3)

**OS/device including version:**
Windows 10, Nvidia GT610

**Issue description:**
Surfaces with transparent textures render with no transparency.
The texture background with alpha is cut off and the surface is grey at these places.

Edit:
The problem only occurs when the Materials "Depth Draw Mode" is set to "Opaque Pre-Pass"

Transparency works normal when editor is switched to GLES3 or 3.1 beta2 is used instead (GLES2).

![Screenshot](https://i.imgur.com/CtbmcOV.jpg)

**Steps to reproduce:**
Use any mesh. Add a SpatialMaterial with a texture including alpha & enable transparency. Make sure to switch editor/project to GLES2.

**Comment by QbieShay** [comment]
@wombatstampede may I ask you to upload a small example project?

**Comment by wombatstampede** [comment]
I just noticed that the problem only occurs when using Depth Draw Mode: Opaque Pre-Pass
[alphatest.zip](https://github.com/godotengine/godot/files/2821328/alphatest.zip)

**Comment by Zireael07** [comment]
Opaque means "not transparent", in other words. I vote close?

**Comment by wombatstampede** [comment]
Transparency works in beta2 and GLES3 (but not in beta3).

Read here about Depth Draw Mode:
https://docs.godotengine.org/en/latest/tutorials/3d/spatial_material.html?highlight=depth%20draw%20mode
(It is labled "Depth Pre-Pass" in the docs)

**Comment by QbieShay** [comment]
Spatial material required some configuration to be used as a sprite material. You need to use alpha cutoff and put the object in the transparent quque. (Not write to depth o think)

**Comment by wombatstampede** [comment]
Enabling Alpha Scissor actually gets the transparency back. But i doubt that this is the intended way to go. (As I said, it worked without Alpha Scissors in 3.1beta2 GLES2 or in beta3 with GLES3)

I'm unsure about "sprite material". This is a (3D) MeshInstance, not a sprite.

Thank you for your answers!

**Comment by reduz** [comment]
I dont see any problem with this, guess should be closed.

**Comment by reduz** [comment]
I also want to change how transparency is show in the spatial material to make it less confusing for 4.0

**Comment by akien-mga** [comment]
Closing then, as it appears to be the expected behaviour IIUC.

If there's a combination of options that produce unexpected results, we could add a configuration warning to notify the user about them.
