### ISSUE TITLE
Vorbis weird replay behavior

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#2554]
If you load a Vorbis file in the `StreamPlayer` and press play on the editor, it works fine. But if you stop and play again it makes a weird sound (like the samples are out of order). It becomes worse each time you stop and play again.

It can also be reproduced by this code inside a `StreamPlayer` with a loaded Vorbis stream:

```GDScript
extends StreamPlayer

func _ready():
	play()
	stop()
	play()
```

**Comment by akien-mga** [comment]
I confirm the bug. It sounds really weird :)

**Comment by xodene** [comment]
I can reproduce this issue as well.

**Comment by reduz** [comment]
this was fixed long ago, closing
