### ISSUE TITLE
VCS API for Godot projects

### ISSUE THREAD

**Issue by IronicallySerious** [godotengine/godot#25542]
**Godot version:**
3.1 beta

**Proposal description:**
I have prepared a VCS API proposal for Godot in this gist -> https://gist.github.com/IronicallySerious/44b0eb010749f6c4dc1bde6494372f16 . The devs at #godotengine-devel also helped me clean this API and I found that a VCS plugin/editor extension is actually required in Godot projects.

The main challenge was to make the API de-coupled with a specific VCS like Git so I have tried to generalize the API so as to fit a wide range of VCSs. Also both read and write functions are available in the concept.

The main idea is to treat `EditorVersionControl` as the interface for the API and its derivatives like `EditorVersionControlGit` will implement the VCS specific functionalities.

**Use cases**:
* Introducing project management from within the editor
* Creating diff and highlighting them so as to implement features like #25442 .
* Providing a singular interface for Git/SVN/Perforce/etc. through a single class.

**Comment by IronicallySerious** [comment]
Another method would be to create 1 gigantic class that handles all the VCS communications. It would have Git specific info extractions, SVN extractions, Perforce, etc. We could just define a `VCS_Mode` that if set to Git, the VCS API will enable us to use Git specific functions, and similarly for all the other VCSs

**Comment by LikeLakers2** [comment]
> I found that a VCS plugin/editor extension is actually required in Godot projects.

I get adding one for convenience, but this part confuses me -- how is a VCS plugin *required*? I just wanna make sure I'm understanding your intent correctly.

**Comment by javawag** [comment]
The initial proposal sounds fairly good.

I'm moving over from Unreal Engine and I use Perforce. For anyone that's not aware Perforce has a system where it marks files as "read-only" and then "checks them out" when you want to edit them (removes the read-only flag) - in UE4 this shows a prompt to say it's not writeable, and asks if you want to check the file out.

However as Godot isn't aware of the above fact it simply says it failed to write the file whenever you run a project, save any resource, compile scripts, etc. The only workaround is to use Perforce in "offline" mode, and overriding the read-only flags, which sort of bypasses P4's systems.

So even if there's not a comprehensive system of diffing tools, commit/pull support, etc., it would be nice for Godot to be aware of VCS's that use the read-only trick and prompt to either remove the read-only flag or check the file out (there's a simple perforce command for this). At the moment it's almost unusable with Perforce, which 90% of AAA studios use (made up statistic 🙂)

**Comment by IronicallySerious** [comment]
This can be closed now since the VCS integration was merged into master :)

The integration has some very basic functions and Perforce's locking features hasn't been addressed in it because of the integration supporting only Git for now. I will be adding more to the VCS integration in the coming months
