### ISSUE TITLE
Warning "... project ... was generated by older engine" even if project.godot is empty

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25541]
**Godot version:**
3.1 beta 3

**OS/device including version:**
Windows 10

**Issue description:**
When I create an empty project.godot and try to open it via project manager, then popup about converting project to new version is shown.

**Steps to reproduce:**
Create empty project.godot and try to import it

**Comment by groud** [comment]
Why would you create an empty project.godot ? ^^

**Comment by groud** [comment]
Why would you create an empty project.godot ? ^^
