### ISSUE TITLE
Sprite sheet frames no longer calculated correctly

### ISSUE THREAD

**Issue by Galileo53** [godotengine/godot#25553]
**Godot version:**
V3.1 Beta3

**OS/device including version:**
WIN10

**Issue description:**
When a sprite sheet reaches a certain size, Godot no longer can cut out the individual frames correctly, when using "Animation: Vframes, Hframes and Frames"

**Steps to reproduce:**
Create a spritesheet, containing 15 full-screen sprites (1920 x 1080 pixels), e.g. by using the TexturePacker tool. Add this spritesheet to a 2D scene, set Vframes and Hframes correctly, then step forward and backward using "Frames". It will work as expected. Or attach an animation player and the sprites will play correctly.

Now add a 16th sprite with same size to the spritesheet. The animation will show a cropped picture. Godot is no longer able to cut out the individual frames at 1920 x 1080, but only by some smaller value, showing a picture that spans parts of two original frames.

Sometimes, while stepping forward and backward at the "frames" field, Godot will crash completely.

**Comment by Galileo53** [comment]
Since my original project is far too large to post, I tried to create a reduced one. Just the sprites, and it turned out that probably there is a problem with the importer. I was able to import the 15-frame and the 16-frame texture, but when trying to attach the 16-frame texture to the sprite node, it said: "error loading file: Not a resource!".

I'm not sure how to post any of these large files, so maybe this can help:
1. Create a 1920 x 1080 file (e.g. in Photoshop), no matter what's in it, save it as a .PNG file.
2. Duplicate the file 15 (or 16) times
3. Create a spritesheet out of these files (e.g. with TexturePacker). The resulting sprite-sheet for 16 frames in my case is 1920 x 17280, exported as a PNG-32 (RGBA8888) file.

When Godot starts importing, I can see that it takes some time for the 15-frame variant, but the 16-frame variant is finishing immediately. Also, the size of the .stex file for 15-frame is 17.2 MB, but for the 16-frame it is only 3.45 KB

**Comment by mrcdk** [comment]
Why are you using spritesheets for that? You shouldn't use a spritesheet for that to begin with, those sizes are absurd. Most GPUs maximum texture size are: 2048~4096 (for mobile ones) or 8192~16384 (for desktop ones)

**Comment by Galileo53** [comment]
This is a desparate try to apply a "movie" with transparent elements over a varying background. I would of course take a WEBM video which is supported by Godot and it already supports alpha, but Godot does NOT support the alpha channel when writing the frames.
Unfortunately this is a key feature of this and many upcoming projects. I really don't want to change to a different game engine so I definitely need a solution for this...

**Comment by timoschwarzer** [comment]
Seems like your GPU can't handle textures of that size...

**Comment by Galileo53** [comment]
Just a question: is the import process going through the GPU ?

**Comment by timoschwarzer** [comment]
Yes, it does. That's why you currently cannot build games in CI environments without a GPU.

**Comment by Galileo53** [comment]
So I finally found the reason:
There is a limit with sprite images. The maximum height is 16384. If you are lucky (more than I was) you can find this error message:
core/image.cpp:1189 - Index p_height - 1=43199 out of size (MAX_HEIGHT=16384)
My fault was to stack all the images vertically in the sprite sheet. I don't know if there is also a horizontal limit, but I now have limited both horizontal and vertical to 16384. My resulting spritesheet for 99 frames of 1920x1080 now is 15360 x 14040 (!!). The resulting PNG file is 122MB and Godot will import it correctly!
The only disadvantage is that the .stex file is 125 MB and that it will take an enormous amount of time to import it where Godot freezes completeley and it is not clear if it has locked up or not.
Once imported and loaded, the animation will play perfectly!

Anyway, I'm sorry that I have disturbed you. From my side, you may close this issue.

**Comment by QbieShay** [comment]
@Galileo53 I think Godot should not fail silently on this. Please open an issue about the user feedback on this. Thanks!

**Comment by KoBeWi** [comment]
Seems like Godot no longer allows to import textures greater than 16384, so this can be closed.

**Comment by Calinou** [comment]
> Just a question: is the import process going through the GPU ?

To clarify, no, the importing process is done 100% on the CPU and can be done in headless mode.

[Betsy](https://godotengine.org/article/betsy-gpu-texture-compressor) will require a GPU (or a software Vulkan implementation) to run, but I believe some kind of CPU fallback will be available, especially when using GLES3 or GLES2.
