### ISSUE TITLE
A New Tilemap node

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#25555]
**Godot version:**
3.1 beta 3

**Issue description:**
It's great that the tilemap workflow has been improved in 3.1, the new editor makes creating tileset resources a lot easier, but it still complicated for a simpler use case and the current tilemap node is just too slow and a bit inconvenient since you can only use one tileset on a tilemap node.

I know my specs are bad but I've been working on a project and I noticed that before the tilemap was added the game ran up to ~430fps and after the tile map was added fps went down to ~300 in a screen without any tiles, this after I found the best quadrant size for my tile size. On a screen full of tiles fps go down to ~120, and only if the game and the editor are the only things open. When I enabled vsync and opened mono develop fps went under 60 and this is only using one tilemap and not much going on in the game itself, if I wanted to have more layers I would have to add a new tilemap node and that would probably make everything slower.

The fact that the game code is good enough to make the game reach 430fps on a low end PC makes me think that the current tile map is just too slow and that we might need a new tile map focused in performance, this would be good for games that don't need all the features of the current tilemap node and could also be used alongside the current tilemap node for thing like collision if needed. This new tilemap would have optimized drawing(at least while the game is running) and could allow us to use multiple tilesets and tile layers, a tileset would only need a tile size,offset,spacing a texture and nothing else(no collision, no per tile z index ,etc) making tileset creation very fast and easy.

I hope that this is considered for a future version of Godot(maybe for 3.2 of 3.3) or that tilemaps are optimized so this is not necessary, though I really think a new simpler tilemap would be better and easier to use for new users.

**Comment by girng** [comment]
tilemap is optimized already afaik, and it really depends on your pc specs. for example,  a game world of over 16000x16000 in size has a steady 144fps while moving a character around. that's only with a gtx 950 and a decade old cpu (i7 2600)

 multiple tile layers can be used btw, just add another tilemap node :O

**Comment by MightyPrinny** [comment]
> tilemap is optimized already afaik, and it really depends on your pc specs. for example, a game world of over 16000x16000 in size has a steady 144fps while moving a character around. that's only with a gtx 950 and a decade old cpu (i7 2600)
> 
> multiple tile layers can be used btw, just add another tilemap node :O
> i also recommend https://github.com/vnen/godot-tiled-importer

I know I can add more tilemap nodes, I mentioned that, I don't want t tond I also mentioned that I didn't have good specs, I was concerned because in my machine I have a 50% performance drop after I add a tilemap in a scene with just the player and some enemies.

**Comment by ByTheQuietLake** [comment]
@MightyPrinny Would you mind sharing your PC specs for clarity?

**Comment by MightyPrinny** [comment]
CPU: Intel(R) Celeron(R) CPU  N2840(2 cores to 2.5Ghz)
GPU: Intel® HD Graphics for Intel Atom® Processor Z3700 Series

**Comment by Zylann** [comment]
Is it slow in editor or in game? I experienced mild slowness in editor for a while now.

**Comment by mateusak** [comment]
I mean, I get where that's coming from, since I had a pretty bad PC for years, but even a bad smartphone nowadays has better specs than your PC ([here](https://versus.com/en/intel-celeron-n2840-vs-qualcomm-snapdragon-625)). If you want to write games for such low spec machines, you should be writing them directly on C++. An engine is a environment made to be as multitool as possible, and because of that it'll always bottleneck your performance.

**Comment by MightyPrinny** [comment]
@Zylann The editor is always slow for me, but I don't mind as long as the game runs well.

I don't think I will convince anybody in working on something like this and maybe what I want is too specific, sorry for the fuss, I'll hopefully be able to do the tilemap node that I want with c++ modules because I really like this engine and working with tilemaps is the only thing I don't like about it, I would like something closer tiled(but without that many features) or game maker in that regard besides better performance, but that will take some time because I have a lot to learn before I'm able to do that,.
