### ISSUE TITLE
Error in 3.1 beta 3 console after editing and running GLES2 project

### ISSUE THREAD

**Issue by Vikram1323** [godotengine/godot#25568]
Godot version:
3.1 beta 3

OS/device including version:
Dell Inspiron 1464, Window 7 64 bit, ATI Mobility Radeon HD 4300 Series

Issue description:
When I edit and create my GLES 2 project using the workaround I mentioned in the #25482 issue. I get this in my console.

Editing project: C:/Users/Vikram/Documents/GodotBeta/1 (C:::Users::Vikram::Docum
ents::GodotBeta::1)
OpenGL ES 2.0 Renderer: ATI Mobility Radeon HD 4300 Series
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:3206
fixed path: C:/Users/Vikram/Documents/GodotBeta/1/.import
unit: C:\
Running: C:\Godot_v3.1-beta3_win64.exe\Godot_v3.1-beta3_win64.exe --path C:/User
s/Vikram/Documents/GodotBeta/1 --remote-debug 127.0.0.1:6007 --allow_focus_steal
_pid 376 --position 0,0
OpenGL ES 2.0 Renderer: ATI Mobility Radeon HD 4300 Series
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:3206

I can run and play my game.
I don't know if they are the same issue maybe they have some connection.

Steps to reproduce:
Create a new GLES 2 project.
Create a save a new scene with anything.
Run that scene.

Minimal reproduction project:
GLES 2 project with a basic tscn file.

**Comment by qonnop** [comment]
Same/Similar problem on Google Nexus 7 / NVIDIA Tegra 3:
```
D/libEGL  (20580): loaded /system/lib/egl/libEGL_tegra.so                                                                                                  
D/libEGL  (20580): loaded /system/lib/egl/libGLESv1_CM_tegra.so                                                                                            
D/libEGL  (20580): loaded /system/lib/egl/libGLESv2_tegra.so                                                                                               
I/OpenGLRenderer(20580): Initialized EGL, version 1.4                                                                                                      
D/OpenGLRenderer(20580): Enabling debug mode 0                                                                                                             
V/WindowManager(  510): Adding window Window{2c2d725f u0 SurfaceView} at 4 of 12 (before Window{31e53080 u0 com.example.gles2/org.godotengine.godot.Godot})
W/GodotView(20580): Trying ConfigChooser fallback                                                                                                          
W/GodotView(20580): creating OpenGL ES 2.0 context :                                                                                                       
I/godot   (20580): OpenGL ES 2.0 Renderer: NVIDIA Tegra 3                                                                                                  
E/godot   (20580): **ERROR**: Directional shadow framebuffer status invalid                                                                                
E/godot   (20580):    At: drivers\gles2\rasterizer_scene_gles2.cpp:3332:initialize() - Directional shadow framebuffer status invalid                       
I/ActivityManager(  510): Displayed com.example.gles2/org.godotengine.godot.Godot: +1s803ms                                                                
E/godot   (20580): **WARNING**: Could not create framebuffer!!                                                                                             
E/godot   (20580):    At: drivers\gles2\rasterizer_storage_gles2.cpp:4335:_render_target_allocate() - Could not create framebuffer!!                       
```

**Comment by Vikram1323** [comment]
As I mentioned this in #25607 I am not having this problem on GNU/Linux.

Fix for Windows is to download opengl32.dll from my repo and copy it where your Godot.xyz.exe is and then click on Godot.xyz.exe

Tested with 3.1 stable, 3.0.6 stable.

https://github.com/Vikram1323/Mesa-build-for-64-bit-Windows

**Comment by Vikram1323** [comment]
My old Laptop died, So I can't test this.

**Comment by clayjohn** [comment]
Thanks for keeping us up to date! This should have been fixed by https://github.com/godotengine/godot/pull/31259
