### ISSUE TITLE
Encoding .png images to base64 produces several times more data than expected

### ISSUE THREAD

**Issue by Rriik** [godotengine/godot#25571]
**Godot version:** 3.0.6
**OS:** Windows 10 Pro

**Issue description:**
I tried encoding several image objects to base64 using `Marshalls.variant_to_base64()`, and what I found is that the encoding produces several times as as much data as it should on a blank file.

Tested it with a 91 KB image and it resulted in a 186 KB output, 2x the size of the image.
Tested it with a 134 KB image and it resulted in a 470 KB output, 3.5x the size of the image.

The images i was trying to encode are .png files, so I'm not entirely sure whether that plays a role in the file size or whether the output sizes are different for .jpg or other image files, however I ran the same .png files through an online image-to-base64 encoding website (https://www.base64-image.de/) and it produced outputs of 123 KB and 185 KB respectively, both of which corresponding to average estimates for the encoding of about 4/3 times the size of the image. I also tried to get the PoolByteArray raw data from the image object, thinking that it's perhaps encoding non-necessary information together with the image data, but it produced the exact same results.

**Steps to reproduce:**
Copy this code in a blank project GDScript, add any image you want encoded in base64 to the project and copy its path to the code.
```
var file = File.new()
var image = Image.new()
image.load("insert any image file path here for encoding")
file.open("temp-file.txt", File.WRITE)
file.store_line(Marshalls.variant_to_base64(image))
file.close()
```

**Comment by bruvzg** [comment]
This is expected. `Image.load` decodes source `.png` to the OpenGL texture and `Marshalls.variant_to_base64` encodes this texture (and other Image metadata).

If you want to encode source `.png`, load it as `File` instead of `Image`.

**Comment by Rriik** [comment]
You are right, I have updated my code to replace `Image` with `File`. To get all the data from the image i replaced the `store_line` parameter with `Marshalls.variant_to_base64(image.get_buffer(image.get_len()))` and it resulted in a 121 KB file which is exactly 4/3 of the original image size. Thanks for the help.

**Comment by LinuxUserGD** [comment]
@Rriik So it is fixed?

**Comment by Rriik** [comment]
Nevermind, I changed `file.store_line()` to `file.store_string()` and it seems to be working without error now.

**Comment by groud** [comment]
Closing as solved then :)
