### ISSUE TITLE
Mesh not rendered when its material have rim enabled [GLES2]

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#25577]
**Godot version:**

Godot 3.1 Beta 3 (GLES2)

**OS/device including version:**

Development:
OS: Windows 10
GPU: nVidia GeForce 520M

Test:
[Asus Zenfone 5 (2014)](https://www.gsmarena.com/asus_zenfone_5_a500cg_(2014)-5952.php)
OS: Android 5.0
GPU: PowerVR SGX544MP2
GLES: 2.0.0

**Issue description:**

Using one click deploy, I test my project on my Android.
The scene (ModelC.tscn) is just a plane, box, and environtment. In the box (MeshInstance) I assign SpatialMaterial and enabled the rim.
This is what I got (screenshot from my phone)
![screenshot_2019-02-02-15-10-42](https://user-images.githubusercontent.com/8316851/52174779-871a4180-27cb-11e9-8de2-7151457b68a9.jpg)
It should look like this ( screenshot from my PC)
![screenshotpc](https://user-images.githubusercontent.com/8316851/52174784-a3b67980-27cb-11e9-8221-3718011dd184.JPG)
I think in my phone the rim make Mesh not rendered. The black thing you see in the screenshot above is probably the shadow from the directional light.
Also, when the scene is running in my phone, the output in my Godot Editor printed this:
[Output.txt](https://github.com/godotengine/godot/files/2825334/Output.txt)
I think it is a shader code?
And also this is the error in the debugger:
[Debugger.txt](https://github.com/godotengine/godot/files/2825335/Debugger.txt)

**Steps to reproduce:**
Open my project below,
Open ModelC.tscn
Select MashInstance2 (Box), assign new spatial material inside the mesh, enable rim, and save the scene.
Build, and test in android phone, press ModelC button when prompted.

**Minimal reproduction project:**

[CharacterTest.zip](https://github.com/godotengine/godot/files/2799866/CharacterTest.zip)
It's the same file at my other bug report #25365

**Comment by earlroxas13** [comment]
Just reporting,
using the latest official beta build (Godot 3.1 Beta 6), now it's not even render the plane.
![screenshot_2019-02-24-11-53-55](https://user-images.githubusercontent.com/8316851/53296377-975c9400-3840-11e9-8be9-1b88ce6590bd.jpg)

**Comment by reduz** [comment]
This is working now (it wont crash or throw errors) in master.  Rim is not visible on mobile while vertex shading is enabled (default, you can switch to fragment but old or very low end phones wont like it much), but you can make a simpe shader to achieve the same effect that does 1.0-dot(-normalize(VERTEX),NORMAL) or similar.

**Comment by earlroxas13** [comment]
@reduz is the fix for this issue already included in official RC1? Today i build the apk using RC1 but it still reproduced in my phone.

**Comment by earlroxas13** [comment]
@reduz I tested it on 3.1 stable today but this issue still reproduced on my phone, also that shader code error is still showing when I run using One Click Deploy to my phone.
