### ISSUE TITLE
changing lightMask on tilemap2d not working

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#2557]
I can't explain it very well so I have included a project with 2 more bugs.
1. changing LightMask not working in tilemap. (bug 2)
2. creating a tile with a LightOccluder2D and not placing it exactly doesn't get converted right. (bug1)
3. animating a LightOccluder2D in a scene instance animates allways all instance (bug 3)

![image](https://cloud.githubusercontent.com/assets/10463138/10203947/47ee31cc-67b9-11e5-8ace-4d3eee3e672b.png)

Project: https://mega.nz/#!U4RxTYjY!kluOQuHlC4ZyqVC3dou4QVoluHrhD_CIcWcjFh4lbYQ

**Comment by puppetmaster-** [comment]
Any news about this bugs? I have them also in the 2.0 alpha version.
Should I split them up in single issue?

**Comment by akien-mga** [comment]
> Should I split them up in single issue?

That could help yes, it's a bit hard to work on several bugs in the same issue.

**Comment by reduz** [comment]
-Bug regarding tilemap lightmask being ignored is fixed
-Placing a light inside an occluder will result in no light being cast outside the occluder, this is by design
-Animating the polygon of an occluder will result in both being animated because the occluder polygon is shared by defautl, like any resuce, when you duplicate. Use the "make unique" option so they are separate

**Comment by puppetmaster-** [comment]
thanks for fixing the lightmask.

I don't get the animating of the polygon working in occluder.
Even when I'm making the occluder unique 
![image](https://cloud.githubusercontent.com/assets/10463138/12058594/e2296668-af4d-11e5-8470-7da53c276917.png)

all instanced scene (not duplicated) animate together.

**Comment by reduz** [comment]
ah this is because resources are always shared between instanced scenes.
You can do via code on _ready()

set_occluder_polygon( get_occluder_polygon().duplicate() )

and it will work

**Comment by puppetmaster-** [comment]
:ok_hand:
