### ISSUE TITLE
Scene dock lost focus when moving selection from 3d node to 2d node

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25586]
**Godot version:**
3.1 8698876

**OS/device including version:**
Ubuntu 18.04.1 GTX 970

**Issue description:**
When I move via keyboard nodes in scene dock from 3d to 2d, then 2d viewport gain focus.

https://streamable.com/n2dg8

**Comment by akien-mga** [comment]
I'm pretty sure there was already an issue about it from a year or two ago, but can't find it anymore.
