### ISSUE TITLE
Expose Delaunay2D to GDScript

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#25587]
It seems Delaunay triangulation has already been implemented in Godot ([here](https://github.com/godotengine/godot/blob/master/core/math/delaunay.h)). It's currently only used for animation related purposes. 

I propose exposing it to GDScript as to enable certain procedural generation algorithms.

**Comment by Zireael07** [comment]
I wrote delaunay triangulation for my own project in GDScript, and I know at least one other person did, too.

**Comment by mateusak** [comment]
> I wrote delaunay triangulation for my own project in GDScript, and I know at least one other person did, too.

It's about performance.

**Comment by QbieShay** [comment]
I believe this is suited to be a plugin (GDNative)

**Comment by Zylann** [comment]
Isn't there a Geometry singleton already with a triangulate() function in it?

**Comment by mateusak** [comment]
> Isn't there a Geometry singleton already with a triangulate() function in it?

It's not Delaunay. Also it doesn't work very consistently. Also when it works it doesn't include all points. Basically it's pretty shit.

**Comment by Zireael07** [comment]
@Zylann: Geometry.triangulate() only works for convex polygons, also most delaunay implementations can work with inner points unlike this.

**Comment by Xrayez** [comment]
Should it be made available in Geometry singleton as `triangulate_polygon_delaunay` alongside `triangulate_polygon`? Perhaps an enum could be created for different types of triangulation, or a simple boolean.

**Comment by mateusak** [comment]
@Xrayez I think a `triangulate_delaunay` would suffice. I mean there's just two types of triangulation, an enum would just confuse people.
