### ISSUE TITLE
[GDScript] local variable being reported as never used incorrectly

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#25583]
Quite possibly related to #23207.

**Godot version:**
3.1 beta 3.

**OS/device including version:**
N/A

**Issue description:**
In this function:
```
func roll_dice (DiceNumber: int = 1, DiceSides: int = 6, AddTo: int = 0, SubFrom: int = 0) -> int:
	var Total: int = 0	# The total of the dice rolled.
	var Count: int = 0	# Used to count the number of dice rolled.
	var DiceRolled: int = 0	# Total of the dice rolled so far.
	for Count in range (0, DiceNumber):	# Roll the dice.
		DiceRolled = randi_range (1, DiceSides)
		Total = Total + DiceRolled
		printerr ("ROLLED: ", DiceRolled, " TOTAL IS NOW: ", Total)
	Total = (Total + AddTo) - SubFrom	# Total calculated, so do any addition or subtraction needed here.
	return (Total)	# And return it.
```
Godot reports "The local variable 'Count' is declared but never used in the block" twice as a false positive. The first time with the initial declaration of the variable, the second time at the definition of the loop.

**Comment by Sslaxx** [comment]
I'm not sure why the for loop one would be intended behaviour seeing as it'd be used for running through the loop...

**Comment by Ace-Dragon** [comment]
You can silence the yellow warnings through the project settings. That is what I did with that type since it can't determine if a variable to be used later is going to be unused.

**Comment by QbieShay** [comment]
Range returns an array, meaning that you are iterating in a "foreach" fashion. So you are actively discarding the elements of that array.

**Comment by mateusak** [comment]
It is not being used though. The variable Count will not be increased because of the for loop. It will remain as 0.

I assume this is what you want:
```
func roll_dice (DiceNumber: int = 1, DiceSides: int = 6, AddTo: int = 0, SubFrom: int = 0) -> int:
		var Total: int = 0	# The total of the dice rolled.
		var Count: int = 0	# Used to count the number of dice rolled.
		var DiceRolled: int = 0	# Total of the dice rolled so far.
		for i in DiceNumber:	# Roll the dice.
			DiceRolled = randi_range (1, DiceSides)
			Total = Total + DiceRolled
			Count += 1
			printerr ("ROLLED: ", DiceRolled, " TOTAL IS NOW: ", Total)
		Total = (Total + AddTo) - SubFrom	# Total calculated, so do any addition or subtraction needed here.
		return (Total)	# And return it.
```

**Comment by akien-mga** [comment]
That's indeed expected behaviour, your local defined `Count` is indeed never used, and the iterator declared in the `for` loop (which shadows but is *not* the previously defined `Count`) is also unused.
