### ISSUE TITLE
Visual shader for particle systems

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#25580]
**Godot version:**

**OS/device including version:**

**Issue description:**

I am trying to play with game vfx in godot, but I want to have more control over the particle system such as using a texture to control when particles emit. There is no way to visually achieve this, I don't know whether coding is a way to achieve this or not. A node based editor to control the particle system allows more creative freedom. Although everything can be animated in godot, it doesn't give enough control for the particle systems.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
How would this be different from the visual shader editor that we already have?

**Comment by ZX-WT** [comment]
You cannot code any particle behaviour with the current editor.

**Comment by clayjohn** [comment]
Have you tried 3.1 yet?

**Comment by ZX-WT** [comment]
Yes I did, that's why I opened this issue. The Process material is the only thing to set the particle systems visually, besides coding your own shader. The current visual shader editor has nothing to do with particles, no nodes about life time of particles, velocity etc. If I want to emit particles according to the values of the texture, no, I cannot do it with the editor.

**Comment by clayjohn** [comment]
Everything available in the ParticlesMaterial is available in the Particles Visual Shader. And yes, that includes velocity, life time of particles, transform etc.

Here is a screenshot so you can see:
![partshad](https://user-images.githubusercontent.com/16521339/52517108-d48f1800-2bea-11e9-93b5-f1d91cd63d99.png)

Did you set the shader_type to particles? And then select vertex shader?

**Comment by ZX-WT** [comment]
If I emit particle from a mesh, it requires a particleMaterial, I cannot use this. Maybe this is not a general case but say I have a subdivided plane and I want to emit particles according to the value of a texture assigned to the plane, can I achieve this with just the visual shader editor?

**Comment by clayjohn** [comment]
Yes. You would do it the same way you would with a shader material.

**Comment by akien-mga** [comment]
Closing as it appears that the feature is there already.
