### ISSUE TITLE
Godot won't load my project any more (config_version > 3)

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#25594]
**Godot versions:**
Godot 3.0.3-stable
Godot 3.0.6-stable

**OS/device including version:**

Linux Mint 18.3

**Issue description:**
When I tried to open again a project I didn't work on for a few months, Godot would not open the Editor, but instead go back to the Project Manager.

I've run it in a terminal to see what's up. I've seen this:
```

$ ./Godot_v3.0.6-stable_x11.64 
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
OPENING: ***REDACTED***
ERROR: _load_settings_text: Condition ' config_version > 3 ' is true. returned: ERR_FILE_CANT_OPEN
   At: core/project_settings.cpp:495.
ERROR: _load_settings_text_or_binary: Couldn't load file '/***REDACTED***/project.godot', error code 12.
   At: core/project_settings.cpp:519.
```
I have them opened my  project.godot in a text editor and changed `config_version=4` to `config_version=3`. The project loaded fine, though my custom input key mappings were lost. Not a big deal. I wanted to drop this here in case others have this issue.

Unfortunately I don't know why my project had config version 4, since I used the same Godot build before to create it.

**Comment by somnivore** [comment]
This will happen if you open your project in 3.1

**Comment by eon-s** [comment]
There is a warning on 3.1 that says that you won't be able to open the project again on 3.0.
So open your 3.0 projects in a copy and/or use a VCS to restore the project.

**Comment by groud** [comment]
Yeah, there is now a warning in version 3.1 about that your project will not be compatible anymore. You can still manually change reduce the config_version to solve the problem.

I think we can consider this as fixed.
