### ISSUE TITLE
Extraordinary number of draw calls for 3d particle emitter

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#2559]
*Bugsquad edit:* Seen in 1.1 stable as well as 2.0 alpha ae3d4ac193a261c8bed28e22304ccfa2c86ccf48

The amount of draw calls for 3d particle emitter is directly related to number of particles. (300 particles == 300 draw calls). Also these draw calls are in power even if emitter is not emitting any particles (emit = false).
It's little troublesome since the only way to make explosion with 3d particle emitter is to set hight number of particles with small "emit timeout" parameter... 
Sample project: https://dl.dropboxusercontent.com/u/168251/godot/some/issues/3DParticleDrawCalls.7z

**Comment by akien-mga** [comment]
@kubecz3k Now that you had a go at porting your game to the current master branch, can you still reproduce the bug there?

**Comment by kubecz3k** [comment]
@akien-mga yes, the bug reproducible in 2.0 alpha ae3d4ac193a261c8bed28e22304ccfa2c86ccf48 commit

**Comment by reduz** [comment]
yeah there is nothing to do about it, GLES2 limitation

**Comment by kubecz3k** [comment]
@reduz so maybe it could be added an "ugly  temporary workaround" with some additional "guard" parameter something like to "force maximal number of particles"? As I said this bug is  the most disturbing when trying to make explosion effects with 3d particle emiter (you are setting 500 particles with "long" lifetime and emission time to 0.3 in hope to emit only  ~40 particles in this time)

**Comment by kubecz3k** [comment]
Since there will be complete rendering code rewrite in 3.0 anyway I will close this issue. 
Note2futureSelf: If someone is struggling with similar issues to mine (trying to create 3d explosions for example) then I would suggest to try setting a lot of particles in runtime with set_amount(),  only for very small amount of time when explosion starts together with very short Emit Timeout.
tip: it can be done via animation player.
