### ISSUE TITLE
Wiki documentation fixes

### ISSUE THREAD

**Issue by brettle** [godotengine/godot#256]
I read through the entire wiki (except the API docs) today and figured that while I was at it I'd correct the various spelling and grammar errors and make a few minor changes to improve readability. A patch (against e8f6e2e) containing my fixes can be found at:

https://gist.github.com/brettle/10007085

You can download the raw patch at:

https://gist.githubusercontent.com/brettle/10007085/raw/6a4f14d57d34af504a2e0bc4e037a91974c03000/godot.wiki-readability.patch

**Comment by akien-mga** [comment]
Too bad this issue was overlooked for so long, now that the wiki is hosted on OpenProject with a new syntax it will be harder to apply this patch... I'll see what can be done (ping @StraToN and @TheoXD too).

**Comment by StraToN** [comment]
Still interesting. I'll import this file locally and re modify it for the new Open Project wiki. And without forgetting giving credit to @brettle. Thanks to him

**Comment by akien-mga** [comment]
@her001 @StraToN If one of you has some time to check this patch and see what parts would still be relevant in the [new documentation](https://github.com/godotengine/godot-docs), that would be great! :)

**Comment by her001** [comment]
Noted, added to my todo list. I wouldn't mind if someone else beat me to it.

**Comment by djrm** [comment]
Movable to the docs repo

**Comment by akien-mga** [comment]
Moved.
