### ISSUE TITLE
Error loading Scene

### ISSUE THREAD

**Issue by Inakimalerba** [godotengine/godot#2560]
Im having this problem when I try to open files edited in another computer.

Im working with a team, I started a project, pushed it to a repo and after my coworker edited it, its permission changed but even if i add the permissions im getting this error.

Im running the latest stable version, im running under Debian 8.

**Comment by okamstudio** [comment]
more information would be appreciated

On Thu, Oct 1, 2015 at 3:14 PM, Iñaki Malerba <notifications@github.com>
wrote:

> Im having this problem when I try to open files edited in another computer.
>
> Im working with a team, I started a project, pushed it to a repo and after
> my coworker edited it, its permission changed but even if i add the
> permissions im getting this error.
>
> Im running the latest stable version, im running under Debian 8.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2560>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment]
There isn't much to work on. Please open a new issue with more information if you still experience this problem.
