### ISSUE TITLE
Instancing a preloaded scene returns a node with an empty filename in some cases

### ISSUE THREAD

**Issue by MidZik** [godotengine/godot#25604]
**Godot version:** 3.1 beta 3

**OS/device including version:** Windows 10

**Issue description:**

Normally, you would expect the root node of a scene instanced with `load` or `preload` to have its `filename` property set to the path of the scene it was instanced from. However, if a script in the preloaded scene preloads its own scene, preloads _outside_ of the scene may create instances where the filename is an empty string instead.

**Steps to reproduce:**
1. Create and save a `LoadedScene` that will be instanced elsewhere. Attach a script to a node in this scene which preloads `LoadedScene`.
2. Create a different scene `MainScene` that preloads and instances `LoadedScene` in a script.
3. Check the filename of the instanced `LoadedScene` in `MainScene`. It will be empty. (If the scene is loaded instead, or if the preload inside `LoadedScene` is removed, it will have the filename to `LoadedScene` as expected.)

See the minimal reproduction project, which was created using those steps.

**Minimal reproduction project:**

[Repro1.zip](https://github.com/godotengine/godot/files/2827585/Repro1.zip)

**Comment by KoBeWi** [comment]
The scene in the reproduction project tries to preload itself, which results in cyclic reference and error. Well, just look at the first step...
> Create and save a LoadedScene that will be instanced elsewhere. Attach a script to a node in this scene which preloads LoadedScene.

If that was causing the problem then it's not a bug, it's incorrect usage. Not sure how you were able to even run the project.
