### ISSUE TITLE
Errors in console after just running 3.1 beta 3.

### ISSUE THREAD

**Issue by Vikram1323** [godotengine/godot#25607]
Godot version:
3.1 beta 3

OS/device including version:
Dell Inspiron 1464, Window 7 64 bit, ATI Mobility Radeon HD 4300 Series

Issue description:
Getting these errors every time I run 3.1 beta 3. Maybe same as #25568

OpenGL ES 3.0 Renderer: ATI Mobility Radeon HD 4300 Series
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5001

I can create, edit and run both GLES 3 and GLES2 projects.

Steps to reproduce:
Run 3.1 beta 3 exe file.

Minimal reproduction project:
Not required.

**Comment by Zireael07** [comment]
I think this and #25608 are duplicates.

**Comment by Zireael07** [comment]
(And just so you know, same errors on both 3.0.6. and 3.1 beta 3 on a Radeon 6630M...)

**Comment by Vikram1323** [comment]
@Zireael07 #25608 is for 3.0.6 I think errors are slightly different.
We both are having same issues.
Are you also having this #25568

**Comment by qarmin** [comment]
Do you have installed latest graphic drivers? Here you can download new https://www.amd.com/en/support

**Comment by Vikram1323** [comment]
@qarmin Yes.

**Comment by Vikram1323** [comment]
@qarmin Before installing them I was unable to run 3.0.6

**Comment by Vikram1323** [comment]
@Zireael07 What is your opinion on using Linux to solve this problem?
What do you think?

**Comment by akien-mga** [comment]
These errors means that your graphics drivers is broken (yet, it reports support of OpenGL 3.3, otherwise it wouldn't let you start Godot with GLES3).

Eventually we should look into having a list of known bad GPUs and force GLES2 on those.

**Comment by qarmin** [comment]
@Vikram1323  Did you try to check if that error still exist when you use linux?

**Comment by Vikram1323** [comment]
Short Version of my agony:

I am using Linux (Solus budgie) for past few days and I'm not having any error mentioned in #25482 #25568 #25607 #24962. Even after that, I was not sure so I waited and downloaded Grim Fandango Remastered edition which requires opengl 3.3 or higher and it is also running properly. 

I then found that Solus is using Mesa drivers. So, I searched for Windows version of mesa  and then I came https://fdossena.com/?p=mesa/index.frag
Using these drivers with Godot 32 bit  fixed above mentioned errors in Windows but they are only build for 32 bit programs. So to run 64 bit version of Godot I'm trying to build mesa drivers.

Yes everything is fixed but they still are errors/issues/problems for new people (with old hardware) who will try Godot.

**Comment by qarmin** [comment]
Because you use Mesa on Windows, probably you can't ran directx games and even some OpenGL software. I recommend to use Windows drivers in Windows and Mesa on Linux, to have best "experience".

**Comment by Vikram1323** [comment]
I am using Linux but for those who want to use Mesa on Windows for few applications or games.
They can copy Mesa (opengl32.dll) where .exe of the application or game is.
After this Mesa will only work for them.

**Comment by Vikram1323** [comment]
As I mentioned this I am not having this problem on GNU/Linux. 

Fix for Windows is to download opengl32.dll from my repo and copy it where your Godot.xyz.exe is and then click on Godot.xyz.exe

Tested with 3.1 stable, 3.0.6 stable.

https://github.com/Vikram1323/Mesa-build-for-64-bit-Windows

**Comment by Vikram1323** [comment]
My old Laptop died, So I can't test this.

**Comment by akien-mga** [comment]
Thanks for the update.

Closing then as we won't be able to investigate further.
