### ISSUE TITLE
Opening a scene should focus on the root node

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#25609]
**Godot version:**
629ac20a

**Issue description:**
When opening a scene in the editor, no node is focused. I believe the root node og the scene should be focused by default.

My use case: I have different levels with different configuration parameters that are export vars of the root of the level. After adding an export var, I wanted to double check that I assigned it properly everywhere (default does not apply here). This made me click once for every scene on the root node.
If the root node was automatically focused, i wouldn't have had to click for every scene that i opened.

**Comment by breakmt** [comment]
When you open a project it's not focused on root node - look at picture. If I close and open scene again - it works like expected.
![2019-02-13_153634](https://user-images.githubusercontent.com/1552169/52712320-47aadc80-2fa5-11e9-9a4c-97dde042f026.png)

**Comment by QbieShay** [comment]
@akien-mga is my pr already merged in beta4?

**Comment by akien-mga** [comment]
Yeah, see the changes between beta3 and beta4: https://github.com/godotengine/godot/compare/a8510331c0115eeee2d6ac0a4acbeb5d4df833b3...17809ca9a907b8d48bea2fd26ea42312a9eaaca4

**Comment by QbieShay** [comment]
Thanks @akien-mga !

Can confirm on latest master. I will need to investigate. Thanks @breakmt for the report!

**Comment by breakmt** [comment]
Maybe we should re-open this? I'm not sure how it is usually done, but I'm afraid you can forget about this bug :)

**Comment by akien-mga** [comment]
It would be better to open a new issue for the remaining bug. This bug was fixed, opening a scene does focus the root node. What's not working is focusing the root node of the main scene when opening *the editor itself*.

**Comment by breakmt** [comment]
done #26006
