### ISSUE TITLE
Mesh library export to exisiting file

### ISSUE THREAD

**Issue by komodor1** [godotengine/godot#25615]
**Godot version:**

3.0.6

**OS/device including version:**

Linux Mint 19 Cinnamon, kernel 4.15.0-43-generic

**Issue description:**

When exporting scene to existing mesh library file, new save merges with older file. For ex. Old file has 4 mesh instances. I delete one mesh, and add another, then save to the same file. Result: 4 mesh instances in library. "Merge with existing" option is off ofc.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
Closing as it is the same as https://github.com/godotengine/godot/issues/25896 but https://github.com/godotengine/godot/issues/25896 provides more steps and is in 3.1
