### ISSUE TITLE
Pasting an emoji in code creates an invisible error (Parse Error: Unknown character)

### ISSUE THREAD

**Issue by GuyUnger** [godotengine/godot#25620]
**Godot version:**
3.1 beta 3

**OS/device including version:**
Windows 10

**Issue description:**
When you paste an emoji in the code editor, it looks like it didn't accept the symbol  because no character is shown. But it's there so it throws an unkown character error. It won't happen to people often but if it does happen, it could keep people clueless of what the problem is because you don't see anything wrong.

**Steps to reproduce:**
Paste an emoji in the code editor

**Comment by girng** [comment]
i think godot is trying to tell us something

**Comment by GuyUnger** [comment]
Yeah the code doesn't need support for emojis imo, but the code should either not accept the character at all or show a "missing symbol" symbol

**Comment by bruvzg** [comment]
> or show a "missing symbol" symbol

Missing char symbol is shown in other input fields (using `Noto Sans UI` font) but not in the code editor (using `Hack` font), that's probably a problem with the font.

**Comment by KoBeWi** [comment]
Still valid in 05395cb
