### ISSUE TITLE
Cannot start with optirun/primusrun

### ISSUE THREAD

**Issue by rennurb3000** [godotengine/godot#25629]
**Godot version:*master*
16d402147b9057c9f7d43ef9b46eb8654e5483cc

**OS/device including version:Linux / 4.19.14-1-MANJARO**
GPU: Nvidia 960m (with bumblebee)
CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Issue description:**
Since my last Pull ~ End of January, i cannot start Godot with optirun:
Following errors are thrown 
`XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":8"
      after 7 requests (7 known processed) with 0 events remaining.
XIO:  fatal IO error 2 (No such file or directory) on X server ":8"
      after 7 requests (7 known processed) with 0 events remaining.
`
Current Beta3 works
**Steps to reproduce:**
+ git pull 
+ scons platform=x11 -j7
+ optirun ./godot.x11.tools.64

**Comment by Naryosha** [comment]
I also have run into this issue. Nvidia 800M on Manjaro x86_64. (not at the PC right now, might add more info and findings soon)

**Comment by akien-mga** [comment]
Probably a regression from #25391.

**Comment by hpvb** [comment]
Does this still happen with DRI_PRIME=0 set ?

**Comment by hpvb** [comment]
The thing is the detection works as expected, and it ends up not setting DRI_PRIME. Unless optirun doesn't like that we try to create multiple GL contexts perhaps.
