### ISSUE TITLE
Errors during editor startup if plugin cannot be activated

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#25635]
**Godot version:**
3.1 beta 3

**OS/device including version:**
Windows 10 x64

**Issue description:**

During editor startup if there is an addon plugin active that fails to be enabled the following errors are printed:

```
ERROR: CanvasItem::get_global_transform: Condition ' !is_inside_tree() ' is true. returned: get_transform()
   At: scene\2d\canvas_item.cpp:482
ERROR: CanvasItem::get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rect2()
   At: scene\2d\canvas_item.cpp:970
ERROR: CanvasItem::get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rect2()
   At: scene\2d\canvas_item.cpp:970
ERROR: Control::show_modal: Condition ' !is_inside_tree() ' is true.
   At: scene\gui\control.cpp:2094
ERROR: CanvasItem::get_global_transform: Condition ' !is_inside_tree() ' is true. returned: get_transform()
   At: scene\2d\canvas_item.cpp:482
ERROR: CanvasItem::get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rect2()
   At: scene\2d\canvas_item.cpp:970
ERROR: Control::grab_focus: Condition ' !is_inside_tree() ' is true.
   At: scene\gui\control.cpp:2065
ERROR: Node::get_tree: Condition ' !data.tree ' is true. returned: 0
   At: scene/main/node.h:263
```

This happens because enabling of plugins at startup is done by calling `set_addon_plugin_enabled` from the `EditorNode` constructor, before it is added to the scene tree:

https://github.com/godotengine/godot/blob/16d402147b9057c9f7d43ef9b46eb8654e5483cc/editor/editor_node.cpp#L5912-L5923

If there is a problem enabling the addon plugin the editor is supposed to show a warning dialog, which does not work if it's not yet in the scene tree. In my case the warning is:

https://github.com/godotengine/godot/blob/16d402147b9057c9f7d43ef9b46eb8654e5483cc/editor/editor_node.cpp#L2606

**Steps to reproduce:**

- Create a new plugin with a GDScript script.
- Activate the plugin.
- Add a syntax error to the script to make it fail to be parsed.
- Restart the editor.

You should see the errors in the terminal and no warning dialog in the editor.
Go to the `Project Settings > Plugins` and try to activate the plugin again. You should see the warning dialog now.

**Comment by neikeq** [comment]
This should probably be moved to `NOTIFICATION_READY`.

**Comment by NomanGhiasy** [comment]
@neikeq The code has been written in C++ right?
