### ISSUE TITLE
SliderJoint, Angular Limit on wrong Axis?

### ISSUE THREAD

**Issue by wombatstampede** [godotengine/godot#25631]
**Godot version:**
3.1 beta3

**OS/device including version:**
Windows 10

**Issue description:**
I would call this not a bug, but a design flaw because this class is not working as documented. (IMHO)
The docs say about the function: "Piston kind of slider between two bodies in 3D."

But actually, the slider slides along the X-Axis ....and rotates around the X-Axis. This would allow twisting the connected piston rod but not the typical "up/down" movement. So the expected behaviour of a piston slider would be to allow the rotation either on the z- (preferred) or y-axis when sliding on the x-axis.

Here's a screen shot of a non-working SliderJoint configuration:
![sliderjoint](https://i.imgur.com/cD3Fj97.jpg)

In the foreground you see a slider joint with a linear limit (two cyan rectangles) and an angular limit (90° segment to the left) set. The indicated limits are exactly performed the way they are shown when the game runs. But as I said, the angular limit makes IMHO no sense for a piston like movement.

**Steps to reproduce:**
Add slider joint to a project, edit the linear and angular limits.

**Minimal reproduction project:**
I stepped upon this problem while creating a 3D Joint sampler/demo. I'll add this here when it is ready. But I'll add a workaround (use Generic6DOFJoint instead) to that project to get it working.

**Comment by pouleyKetchoupp** [comment]
`Generic6DOFJoint` can be used for use cases like this. Documentation needs to be updated so it only mentions slider and not piston, which is not an accurate description of this joint.
