### ISSUE TITLE
S3TC image compression fails on exported project but works in editor

### ISSUE THREAD

**Issue by Rriik** [godotengine/godot#25640]
**Godot version:** 3.0.6
**OS:** Windows 10 Pro

**Issue description:**
I'm trying to compress a viewport render image using S3TC, it works in the editor but not on the exported project, giving me this error.

![image](https://user-images.githubusercontent.com/40471819/52295535-c5a72c00-2984-11e9-932b-808ffb9abbd9.png)
![image](https://user-images.githubusercontent.com/40471819/52295759-436b3780-2985-11e9-98a1-28f3ab2ba133.png)

This is my code:
```
yield(get_tree(), "idle_frame")
yield(get_tree(), "idle_frame")
var image = render_viewport.get_texture().get_data()
image.convert(Image.FORMAT_RGBA8)
image.compress(Image.COMPRESS_S3TC, Image.COMPRESS_SOURCE_GENERIC, 1.0) # Returns OK in editor but ERR_UNAVAILABLE on export
```

**Comment by akien-mga** [comment]
S3TC compression is done via the `squish` module, and is indeed only enabled for the editor binary (`TOOLS_ENABLED`).

Previously the whole squish module was editor-only, but @eska014 exposed the decompress method in #24017. I guess the decompression stuff might also be exposed, but needs confirmation from @reduz that this would not cause issues.

**Comment by vrmaurice** [comment]
This error is happening again on Godot 4.1 Mono.

I'm trying to use the Image.Compress() method in C#, it gives this error:
`ERROR: Condition "!_image_compress_bc_func" is true. Returning: ERR_UNAVAILABLE`

I've built this for a Linux server, I run the server with the `--headless` flag.

4.1.1.stable.mono.official [bd6af8e0e]
