### ISSUE TITLE
Android app using AudioStreamMicrophone crashes

### ISSUE THREAD

**Issue by DaSlang** [godotengine/godot#25648]
**Godot version:** Godot 3.1 Beta 3

**OS/device including version:** Android 6.0.1 (armeabi-v7a)

**Issue description:** Starting an AudioStreamPlayer2D (having as Stream an AudioStreamMicrophone) on Android crashes the application.
On Windows everything works fine (the sound is correctly captured from the microphone), but when the project is exported to Android, the application crashes on startup, even if it has the permission to access the microphone.
If the Stream is setted to other types of AudioStreams (AudioStreamOGGVorbis for example) everything works as expected.

**Steps to reproduce:** Create a simple scene with a main node and add an AudioStreamPlayer2D to the tree. Set the Stream of AudioStreamPlayer2D to AudioStreamMicrophone. Enable the audio input in the project and create an Android preset that has the Record Audio permission. Run the project on Android (giving the Microphone permission to the app).

**Minimal reproduction project:** [Microphone Android Crash.zip](https://github.com/godotengine/godot/files/2834011/Microphone.Android.Crash.zip)

**Comment by samdaiya** [comment]
**Remote Debug Gives Following Output**
Android modules: Nothing to load, aborting

**Comment by marcelofg55** [comment]
Android platform doesn't have Microphone support yet. I'll see if I can add it sometime.

**Comment by akien-mga** [comment]
In the meantime, can we add a change so that it doesn't crash, even if not supported?
