### ISSUE TITLE
GDScript: Cannot use static function from inner class

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#25646]
**Godot version:**
3.0.6 stable 64b non-mono version (currently latest available stable version)

**OS/device including version:**
Kubuntu 16.04

**Issue description:**
Cannot use static function from inner class - I get an error `Invalid call. Nonexistent function 'st_fn_test' in base 'Reference ()'.`. I was expecting to be able to do so, since static functions should be available everywhere, if I understand it correctly.

**Steps to reproduce:**
```
extends Node

static func st_fn_test(x):
	print(x)

class Inner:
	func _init():
		st_fn_test("Inner._init") # doesn't work

func _ready():
	st_fn_test("_ready") # works
	Inner.new()
```

**Minimal reproduction project:**
Just add an empty Node and the script from above.

**Comment by Zylann** [comment]
Static functions indeed don't require to access an instance, but to call static functions, you need a reference to the *class* which contains them (or script). It is then expected to not be able to call it that way from your inner class, because it's a completely different class, AFAIK.
You would need something like:

```gdscript
class Inner:
	func _init():
		preload("enclosing_script.gd").st_fn_test("Inner._init")
```

However, because that would cause a cyclic reference, using `load` might work instead:
```gdscript
class Inner:
	func _init():
		load("res://path/to/enclosing_script.gd").st_fn_test("Inner._init")
```

**Comment by mnn** [comment]
That works, but is quite ugly. Why isn't static function accessible when it is in a same scope? I find it very unintuitive. This is really intended behaviour (asking if I should close this issue)?

Well, I think it's time to try C#...

**Comment by Zylann** [comment]
> Why isn't static function accessible when it is in a same scope?

That's the point, it isn't. A nested class still remains a different class, and then a different scope. I think that's the same in C#.

**Comment by mnn** [comment]
But you can surely at least reference outer class by name, not by path which is long and will break during refactoring. I also encountered other things (like missing support for multidimensional arrays, it is really pain to initialize them) and need to implement custom int Vector3 and Vector2 (that I think will be better done with C#'s structs which are passed as values).

Oh, didn't see that other issue, I am closing it then.

Thank you for quick answers :).

**Comment by mnn** [comment]
>  And another workaround would be to define your static function _before_ your inner class.

Am I missing something here? I think I have it defined before inner class.

**Comment by Zylann** [comment]
@mnn I don't know, I just read that from the existing issue. Perhaps the workaround no longer works?

**Comment by mnn** [comment]
If this is an intended functionality, I think it would be good to mention it in docs, since it doesn't seem to be very common for an inner class to not have access to outer class (in many languages it has full access to not only fields and methods, but also generic types and it is often used to not be accessible from anywhere else except the outer class, so it is extremely different in GDScript compared to mainstream languages like Java, Scala or C#). Here it works much more like a package/namespace IMO.
