### ISSUE TITLE
Make the radius property in CapsuleShape not interfere with height.

### ISSUE THREAD

**Issue by marmitoTH** [godotengine/godot#25657]
Well, in fact the height property value in Inspector still the same, but the 3d capsule itself increase in height. It's pretty annoying, did I miss something? In Unity it doesn't happen, so I have much more control over the capsule height and radius. It sounds silly, but it gets in the way a little bit to keep up with the map scale, since it's confusing to tweak and match units.

**Comment by Zylann** [comment]
Sounds easy to fix but it will break compat.

**Comment by Zylann** [comment]
I just noticed the same issue occurs with CapsuleMesh. Maybe both should have similar behavior so they are easier to match.
