### ISSUE TITLE
No code completion for instanced nodes

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#25664]
**Godot version:** both 3.0.6 and 3.1 beta 6

**OS/device including version: Windows 7**

**Issue description:**
No code completion for instanced nodes or instances of the classes that have been loaded with `preload()` (may not work for `load()` as well, I didn't test)
<details>
<summary>screencast gif</summary>

![screencast](https://user-images.githubusercontent.com/47334605/52360587-7b3db200-2a4d-11e9-814a-255fe1696947.gif)

</details>

**Minimal reproduction project:** [CodeCompletion.zip](https://github.com/godotengine/godot/files/2837428/CodeCompletion.zip)

**Comment by akien-mga** [comment]
Tested in 3.2, it's now working fine if you use `preload`:
![Screenshot_20200622_150731](https://user-images.githubusercontent.com/4701338/85290935-19db7f00-b49a-11ea-84de-f40bf72acdf9.png)

It doesn't work indeed when the PackedScene is an `export (PackedScene)` without default value, but I'm not sure that it could be made to work at all. Different scenes using that script might have different values for that export variable, so which one should be preloaded by the editor and used for completion? CC @vnen @ThakeeNathees

**Comment by smedelyan** [comment]
Having come back to this one after two years, I think there is no way for Godot to provide guaranteed completion because the value of a variable:
* is not concrete, may have different values / types, as you said
* may change dynamically (e.g. programmatically in script -- or via editor while the game is running) and lead to failures in code

The desirable behavior is possible if:
* the var is not modifiable (value is set once and cannot ever change; similar to Java's `final var` or Kotlin's `val`)
  * I don't anything like this in GDScript
* the value is set explicitly as @akien-mga showed above

Given that this now works with `preload()`, I suggest consider this one fixed now.
@akien-mga ?

**Comment by akien-mga** [comment]
Yeah in the case of exported PackedScenes I don't see a way to provide completion sadly, as the exported variable could point to any scene depending on the specific instance using that script.
