### ISSUE TITLE
Failling to send http request from HTML5 exported file 

### ISSUE THREAD

**Issue by theCanabrava** [godotengine/godot#25668]
**Godot version:**
v3.0.6 stable

**OS/device including version:**
Ubunto 16.04 LTS

**Issue description:**
When executing HTTP get request from 'postman-echo.com/get' on IDE scene runner, the program is able to successfully complete the request. However when exporting html and executing from local host, _on_HTTPRequest_request_completed is unable to complete request and returns result=4. If  'postman-echo.com/get'  is downloaded and stored locally, HTTPClient is able to complete get request.
What am I doing wrong?

**Program Execution**
Initial state:
![initial state](https://user-images.githubusercontent.com/6096553/52369429-d8c70400-2a37-11e9-8789-8224d0228875.png)

When executed on IDE:
![result from ide scene runner](https://user-images.githubusercontent.com/6096553/52369463-e67c8980-2a37-11e9-8f23-e0e6bf3c2f8c.png)

When exported and executed on Firefox:
![htmloutput](https://user-images.githubusercontent.com/6096553/52369497-fe540d80-2a37-11e9-8553-8eb0c6f9bea3.png)

Button .gd:
`export (String) var URL`

`func _on_Button_pressed():`
`	$HTTPRequest.request(URL)`
`	text = 'Loading'`

`func _on_HTTPRequest_request_completed(result, response_code, headers, body):`
`	print('URL: ' + String(URL))`
`	print('result: ' + String(result))`
`	print('response_code: ' + String(response_code))`
`	print('headers: ' + String(headers))`
`	print('body: ' + String(body))`
`	print()`
`	var json = JSON.parse(body.get_string_from_utf8())`
`	text = json.result['headers']['host']`

Debugger Output:
`Init OS`
`Init Audio`
`Init VS`
`Init Physicsserver`
`OpenGL ES 3.0 Renderer: Mozilla`
`URL: http://postman-echo.com:80/get`
`result: 4`
`response_code: 0`
`headers: []`
`body: [PoolByteArray]`
`**ERROR**: **SCRIPT ERROR**: Invalid get index 'headers' (on base: 'Nil').`
`**ERROR**:    At: res://Button.gdc:28:_on_HTTPRequest_request_completed() - Invalid get index` `'headers' (on base: 'Nil').`
`URL: http://localhost:8080/get.html`
`result: 0`
`response_code: 200`
`headers: [cache-control: max-age=3600, content-length: 567, content-type: text/html; charset=UTF-8, date: Wed, 06 Feb 2019 19:06:57 GMT, etag: W/"20981340-567-2019-02-06T16:14:09.221Z", last-modified: Wed, 06 Feb 2019 16:14:09 GMT, server: ecstatic-3.3.0]`
`body: [PoolByteArray]`

**Steps to reproduce:**
1-Export HTML5 executable,
2-Launch python's SimpleHTTPServer
3-Execute program on firefox
4-Press first button

**Minimal reproduction project:**
[minimal.zip](https://github.com/godotengine/godot/files/2838026/minimal.zip)

Thanks for the help!

**Comment by eska014** [comment]
HTTP on the web is subject to [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), so the server needs to send the response with an appropriate `Access-Control-Allow-Origin` header if requesting from a different host.

[List of web platform HTTP limitations](https://docs.godotengine.org/en/latest/getting_started/workflow/export/exporting_for_web.html#class-httpclient-and-class-httprequest)

**Comment by EdsonMSouza** [comment]
The solution to solve The solution to problems with HTTPRequest in HTML Exports may lie in the server's CORS. To do this, simply place (in PHP) the following instructions at the beginning of the API file.

if (isset($_SERVER['HTTP_ORIGIN'])) {
    header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
    header('Access-Control-Allow-Credentials: true');
    header('Access-Control-Max-Age: 8640000');    // cache for 100 days
}

if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
    if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
        header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS");
    if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
        header("Access-Control-Allow-Headers: {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");
}
