### ISSUE TITLE
Error compiling libvpx module on Windows with YASM

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#25662]
```
PS D:\git\godot> scons p=windows bits=64 target=release_debug tools=yes -j 1
scons: Reading SConscript files ...
Configuring for Windows: target=release_debug, bits=64
 Found MSVC version 14.1, arch amd64, bits=64
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 43%] yasm -Ithirdparty/libvpx/ -f win64 -D X86_64 -o thirdparty\libvpx\vp8\common\x86\copy_sse2.windows.opt.tools.64.obj thirdparty\libvpx\vp8\common\x86\copy_sse2.asm
scons: *** [thirdparty\libvpx\vp8\common\x86\copy_sse2.windows.opt.tools.64.obj] Error 309
scons: building terminated because of errors.
PS D:\git\godot>
```

**Comment by TheMadScientist1234** [comment]
It appears that you are missing DLLs.

**Comment by LinuxUserGD** [comment]
But on Linux it works fine, even with MinGW.

**Comment by Calinou** [comment]
Maybe there's a regression in how SCons uses yasm to build some files in Godot. Try removing `yasm` so that SCons doesn't attempt to use it.

**Comment by LinuxUserGD** [comment]
> 
> 
> Maybe there's a regression in how SCons uses yasm to build some libvpx-related files in Godot. Try removing yasm from your `PATH` so that SCons doesn't attempt to use it.

That worked. Thank you :+1:

**Comment by akien-mga** [comment]
What's your compiler version, and yasm version?

**Comment by akien-mga** [comment]
Assigning to @hpvb who got YASM + MinGW to work for official builds.

**Comment by hpvb** [comment]
@LinuxUserGD what version of yasm do you have?

**Comment by LinuxUserGD** [comment]
@hpvb yasm-1.3.0

**Comment by LinuxUserGD** [comment]
I can't test if the error is still there because now I'm getting:
```
scons: *** SDK version '10.0A' is not supported
File "./platform/windows\detect.py", line 146, in setup_msvc_auto
```

**Comment by akien-mga** [comment]
> scons: *** SDK version '10.0A' is not supported

That's #26485.

How did you install yasm?

**Comment by LinuxUserGD** [comment]
@akien-mga I installed yasm and scons via scoop and Visual Studio Community together with Unreal Engine (I have Unity, Unreal and Godot installed and Unreal needs C++).

**Comment by LinuxUserGD** [comment]
With 10.0A and yasm it works now.
```
[100%] progress_finish(["progress_finish"], [])
[100%] Linking Static Library ==> modules\freetype\freetype_builtin.windows.opt.tools.64.lib
[100%] Linking Static Library ==> drivers\drivers.windows.opt.tools.64.lib
audio_driver_alsa.windows.opt.tools.64.obj : warning LNK4221: Die Objektdatei definiert keine zuvor undefinierten öffentlichen Symbole. Sie wird daher von keinem Verknüpfungsvorgang verwendet, der diese Bibliothek benutzt.
thread_posix.windows.opt.tools.64.obj : warning LNK4221: Die Objektdatei definiert keine zuvor undefinierten öffentlichen Symbole. Sie wird daher von keinem Verknüpfungsvorgang verwendet, der diese Bibliothek benutzt.
[100%] Linking Static Library ==> core\core.windows.opt.tools.64.lib
[100%] Linking Program        ==> bin\godot.windows.opt.tools.64.exe
   Bibliothek "bin\godot.windows.opt.tools.64.lib" und Objekt "bin\godot.windows.opt.tools.64.exp" werden erstellt.
[100%] scons: done building targets.
PS D:\git\godot>
```

**Comment by Calinou** [comment]
I stumbled upon this same "Error 309" issue recently. For those wondering, the yasm Windows binary requires Microsoft Visual C++ Redistributable 2010 to run, but the [yasm package provided by Scoop doesn't install it automatically](https://github.com/ScoopInstaller/Main/issues/200). This causes the binary to fail to run until the dependency is installed.

**Comment by creikey** [comment]
I also encountered this error after following this doc page:

https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html

Because it says to install `yasm` with scoop. By running `scoop uninstall yasm` everything compiled correctly. Maybe this dependency should be removed from the docs?

**Comment by Calinou** [comment]
@creikey If everything works correctly, yasm should be able to compile the required assembly code. If it doesn't work, it means there's a bug in our code.

That said, we should really move video codecs out of core at some point since they've been causing so much trouble…
