### ISSUE TITLE
Template download in background

### ISSUE THREAD

**Issue by ariromano** [godotengine/godot#25678]
**Godot version:**
3.06

**OS/device including version:**
macOS 10.14.2

**Issue description:**
When downloading an export template through the editor, clicking anywhere else will not only close the window but terminate the download

**Steps to reproduce:**
fresh Godot installation.
fresh project
export, for example, for Mac
→ editor downloads 300+ MB but when clicking anywhere outside of the download window, it'll get interrupted.

→ download should run in background so user can continue working while downloading template.

**Comment by KoBeWi** [comment]
In 3.1 at least it doesn't close when you click outside.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/48902, closing.
