### ISSUE TITLE
godot macros

### ISSUE THREAD

**Issue by mokalux** [godotengine/godot#25679]
checked!

**Godot version:**

future version

**OS/device including version:**

ALL

**Issue description:**

suggestion:
Hello there wonderful godot developers.
I have an idea: wouldn't it be nice to integrate a macro recorder like in MS Excel?
So when you press the button record macro, godot remembers everything you do in the interface (example: change x position, change color, change anything really) and then when you press stop macro, godot outputs the result to a macro script (it can be a gd script).

I am a big fan of excel macros.

The plus side of it: when you don't know the code to do something, the macro can help you find the underlaying code.

That's it!

Thank you for this wonderful engine.

**Steps to reproduce:**

not yet

**Minimal reproduction project:**

not yet

**Comment by Zylann** [comment]
A pervasive feature like this one would be hard and all-over-the place for something almost nobody needs IMO. However, something like a plugin which turns a node branch into the code needed to create it could be an alternative.

**Comment by mokalux** [comment]
hello dear zylann, thank you for the feedback. It could be useful to newcomers and maybe me as well. It was just a suggestion and yes a plugin would be great.

One use cases would be: for example on a kinematic body the user click on option pickable, then change the color in modulate, and so on... that would be nice to have the gdscript automated.

This is an easy case but could be useful with more complicated ones.

I was thinking about the macro thing because I thought that would not be that difficult (for you devs I mean) and a nice addition to an already incredible engine.

Shall I close the feature proposal?

**Comment by bojidar-bg** [comment]
There is already support for this with [Editor Scripts](http://docs.godotengine.org/en/latest/classes/class_editorscript.html). They are just tool-mode scripts which inherit the EditorScript class and implement its _run method. They can then be run from the script editor and, I think, the Project or Editor menus.

It might be worth investigating adding recording capabilities to such scripts, as they are mostly unused right now (being overshadows by the more popular plugins and plain tool-mode scripts).

**Comment by mokalux** [comment]
hello bojidar-bg, I can see that whatever we do in the editor (for example if we move an rigidbody) it is reported in the output panel : "edit canvas item". So this is a kind of a macro recorder. That would be nice to have the output as gdscript commands!

**Comment by Zylann** [comment]
@mokalux this is the UndoRedo system, but I'm not sure it can easily turn into code (if that's still your use case)

**Comment by mokalux** [comment]
ok thank you for the feedback, i will have a closer look at editor scripts and see what i can do. Thank you all the devs and contributors. I hope someday I'll give back to the community. Have fun!
