### ISSUE TITLE
Blend shape does not work on GLES2 in Godot 3.1 Beta 3

### ISSUE THREAD

**Issue by MGeymer** [godotengine/godot#25697]
Godot version: 3.1 Beta 3

OS/device including version: Windows 10

Issue description: I exported the model with the shape keys from Blender with the export better collada. And I decided to open it in my project on GLES2, but for some reason the model was transparent, I launched the same project with GLES3 and reimported the model. Everything has become normal. Conclusion: blend shape does not work in GLES2.

Minimal reproduction project:
[TestProjBlendShape.zip](https://github.com/godotengine/godot/files/2844118/TestProjBlendShape.zip)

**Comment by akien-mga** [comment]
It doesn't seem to work neither in GLES2 nor GLES3 for me on Linux (Nvidia GTX 670MX) in the current master branch (a4b687b). I get these errors:
```
OpenGL ES 3.0 Renderer: GeForce GTX 670MX/PCIe/SSE2
ERROR: instance_set_blend_shape_weight: Index p_shape=0 out of size (instance->blend_values.size()=0)
   At: servers/visual/visual_server_scene.cpp:609.
ERROR: instance_set_blend_shape_weight: Index p_shape=1 out of size (instance->blend_values.size()=0)
   At: servers/visual/visual_server_scene.cpp:609.
ERROR: mesh_add_surface: Condition ' !(p_format & VisualServer::ARRAY_FORMAT_VERTEX) ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:3164.
ERROR: mesh_surface_set_material: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers/gles3/rasterizer_storage_gles3.cpp:3681.
ERROR: instance_set_blend_shape_weight: Index p_shape=0 out of size (instance->blend_values.size()=0)
   At: servers/visual/visual_server_scene.cpp:609.
ERROR: instance_set_blend_shape_weight: Index p_shape=1 out of size (instance->blend_values.size()=0)
   At: servers/visual/visual_server_scene.cpp:609.
ERROR: instance_set_surface_material: Index p_surface=0 out of size (instance->materials.size()=0)
   At: servers/visual/visual_server_scene.cpp:623.
ERROR: mesh_surface_get_primitive_type: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers/gles3/rasterizer_storage_gles3.cpp:3801.
```

**Comment by reduz** [comment]
I did some clean up blend shapes. They will not work on GLES2 (proper warning now) but also if you import them on GLES2, they will not at least work on GLES3. Some errors were also removed.
