### ISSUE TITLE
Negative scale on 3d objects has inconsistent behaviour

### ISSUE THREAD

**Issue by krdluzni** [godotengine/godot#25696]
**Godot version:** v3.1.beta3.official

**OS/device including version:** Windows 10 Home, 64 bit. GTX1080, Version: 25.21.14.1881, Game Ready: 418.81.

**Issue description:**

When negative scales are applied to 3d objects, the rendering and lighting behaviour is inconsistent.

**Steps to reproduce:**
Open the attached project.  There are 4 cubes in LightingTest.tscn. Two use the default cube mesh, but one of the nodes (GLES2_broken) is scaled by -1 on each axis. The other two are dae exports of the default cube from blender, but one of them (GLES3_broken) is scaled by -1 on each axis.

Note that the GLES3_broken cube, when in GLES3 mode, has the faces pointing away from the directional light showing as brighter than the faces pointing towards it.
Note that the GLES2_broken cube is not exhibiting the same behaviour.
See screenshot: 
![image](https://user-images.githubusercontent.com/5222656/52463875-9e985800-2b46-11e9-9db0-136267400a36.png)

Note that the GLES2_broken cube, when in GLES2 mode, displays it's inner faces, rather than outer faces. Note that the GLES3_broken cube is not exhibiting the same behaviour.
See screenshot: 
![image](https://user-images.githubusercontent.com/5222656/52463844-858fa700-2b46-11e9-92ea-4f4aa6d90d7c.png)

**Minimal reproduction project:**

[tests_3.1.zip](https://github.com/godotengine/godot/files/2844079/tests_3.1.zip)

**Comment by Chaosus** [comment]
Marked as bug, however Im not sure that its possible to fix, the light system is intended to work with correct geometry and normals

**Comment by aaronfranke** [comment]
In theory, when any amount of the scales are negative, the normals will still be pointing outwards, so it should be possible to do this.

**Comment by IronicallySerious** [comment]
@aaronfranke I would assume the normals would end up pointing inwards instead if the cube is inverted on all axes. Is there a specific reason for the normals to still be pointing outwards?

**Comment by aaronfranke** [comment]
Imagine in real life if you have a cube and you place objects next to that cube. No matter how many mirrors you look through, those objects outside the cube will continue to be outside of it.

**Comment by IronicallySerious** [comment]
Thanks! I later thought we can mathematically prove this but this method sounds more intuitive 😄

**Comment by clayjohn** [comment]
Leaving some notes for myself here:

Setting cull mode to "Back" on GLES3_broken_cube fixes its normals. That part is the same as issue https://github.com/godotengine/godot/issues/26710. 

The fix for the GLES2_broken_cube is the same as for issues https://github.com/godotengine/godot/issues/27900 https://github.com/godotengine/godot/issues/26627

**Comment by clayjohn** [comment]
Superseded by #29317
