### ISSUE TITLE
AudioStreamPlayer adds AudioStreamPlayer2D to recent and favorites

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#25699]
Godot v. 306 stable, windows 10

Add a new AudioStreamPlayer node, when you go back into the "Create new node" menu the AudioStreamPlayer is listed in the Recent section with correct icon, but it's the AudioStreamPlayer2D node in disguise, same issue if you add it to Favorites.

**Comment by DleanJeans** [comment]
This is fixed in 3.1

**Comment by groud** [comment]
Closing as fixed on master then.
