### ISSUE TITLE
Restore 2d editor's zoom behavior from 3.0.6 back to a 2x / 0.5x multiplier

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#25693]
**Godot version:**

3.1 beta 3 (and many earlier versions of 3.1)

**Issue description:**
Sometime after 3.0.6 the zoom buttons in the 2D editor have changed from doubling/halving the zoom level to changing the zoom level at a rate of 1.5x:

44.4%, 66.7%, 100%, 150%, 225%, 337.5%, 506.3%

This has the effect of making it difficult to judge a game's graphics at an even ratio, which is particularly annoying when making a game without texture filtering enabled.

![image](https://user-images.githubusercontent.com/1023003/52455229-bc4cc980-2b14-11e9-92bd-c738fe4b8652.png)

**Comment by groud** [comment]
I think changing the zoom by x2 is a too strong ratio, but I agree it should be possible to get the 200%, 400%, etc... values.

**Comment by nobuyukinyuu** [comment]
I consider this a regression.

**Comment by aaronfranke** [comment]
Perhaps the solution that would allow both integer scaling and many scaling levels is to zoom by √2 (1.414) each time instead of 1.5, such that zooming twice would zoom by 2x or 0.5x.

**Comment by Seel** [comment]
Some programs have seamless / smooth zooming, but when you get close to those 100% 200% 300% etc increments it snaps to them and sticks to them for a bit until you scroll the mousewheel a bit further before continuing smoothly zooming.
