### ISSUE TITLE
TextureProgress not showing on HTML5 GLES2

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#25698]
**Godot version:** Godot 3.1 Beta 3

**OS/device including version:** Windows 10 64-bit

**Issue description:**

TextureProgress simply not showing on HTML5 in GLES2.
It works fine in the editor and Windows export, not sure about other platforms.
With GLES3, it works normally on HTML5.

**Steps to reproduce:**
1. Export to HTML5 in GLES2 mode
2. Find no TextureProgress on screen

**Minimal reproduction project:**

[TextureProgressMissing.zip](https://github.com/godotengine/godot/files/2844221/TextureProgressMissing.zip)

**Comment by eska014** [comment]
Confirmed this is fixed in the reproduction project at 9d78274e068d4928044220c4d5c1a7baed423670
