### ISSUE TITLE
No option to run editor in "debug server" mode to debug server/headless exports

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#25702]
**Godot version:**
v3.1-beta3

**OS/device including version:**
ArchLinux & NVidia GPU

**Issue description:**
There is an option `--remote-debug` which allows app to connect to remote Godot editor instance.
However it seems like it's only used internally - there is no way to manually start Godot editor in "debug listen mode" because editor starts listening to port 6007 only when "Run scene" button is clicked. Having an option like `--debug-server <bind_address>` to start editor and listen for incoming connections would be awesome.

**Steps to reproduce:**
- Export app to Linux platform
- Deploy app to some server and run it with godot server binary.
- Observe impossibility of debugging the deployed app with local IDE.

**Minimal reproduction project:**
Any project.

**Comment by fire** [comment]
How necessary is securing this via for example a certificate? Presumably you're debugging on the public internet.

**Comment by and3rson** [comment]
Personally for me (and probably for most Linux guys out there) unsecured connection would be totally fine because this would anyway be performed in a testing environment (or even locally first.) Also the deployed app knows which host to connect to for debugging, so nobody would be able to initiate connection towards it.

**Comment by fire** [comment]
See if https://github.com/godotengine/godot/pull/28652 does the job.

**Comment by and3rson** [comment]
@fire totally! Thanks for your contribution.

**Comment by KoBeWi** [comment]
The linked PR was closed, because it was superseded. Not sure if the issue was resolved in the end.
@and3rson Is this still valid in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3)?

**Comment by Faless** [comment]
This should probably go through the proposal process.
My initial thoughts about requirements:
- Provide a button in the editor UI to start/stop the debug server (likely in the debug menu).
- Provide a `--debugger-server` as a CLI alternative (to start the debug server automatically).
- Implement some logic to check if the edited and attached projects match. (Optional?).

**Comment by Faless** [comment]
This is implemented in `3.x` via #60819 and `4.x` via #52226 (CLI options).

Further discussion around a UI for it (which I agree is needed) should go through the [proposals process](https://github.com/godotengine/godot-proposals).

**Comment by Faless** [comment]
For reference, there is a proposal about showing the option in the editor UI: https://github.com/godotengine/godot-proposals/issues/2608
