### ISSUE TITLE
Editor: TextEdit v_scroll_speed tooltip error

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#25707]
none found

**Godot version:**

3.1 beta 3

**OS/device including version:**
Windows 10

**Issue description:**
v_scroll_speed's tooltip displays wrong text
![immagine](https://user-images.githubusercontent.com/47447512/52491653-dd222700-2bc7-11e9-9f70-4791c40f7c29.png)

**Steps to reproduce:**
point mouse on V_Scroll_Speed 

**Minimal reproduction project:**
-

**Comment by bojidar-bg** [comment]
Here is the source in the documentation, maybe someone messed up a bit:
https://github.com/godotengine/godot/blob/6cdcde7114a7b12063d2d4b720583d6094d66c85/doc/classes/TextEdit.xml#L402-L406
