### ISSUE TITLE
Empty `if` block is not parsed correctly

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#2570]
Look at this nice little snippet:

```gdscript
func empty_if():
	if something:

func test():
	print("test1")

	else:

func test():
	print("test2")
```

It allows you not only to define the same function twice without giving any error but also the function is considered undefined if you try to call it (and if you _don't_ call it, the game actually runs without problems).

My guess is that the `if` statement should expect an indented block afterwards (the same way `func` works) but it's not happening somehow.

**Comment by Brickcaster** [comment]
What is the expected behavior?  Should the engine throw an error when this is detected or should it respect the empty block and indentation?

**Comment by vnen** [comment]
It should throw a parse error, the same as empty functions, so it would show as wrong in the editor. If needed, empty blocks can use the  `pass` keyword in order to not be really empty.

**Comment by Brickcaster** [comment]
I seem to have no clue what I'm doing.  I found where the problem is, I just don't really know exactly what's going on.

**Comment by Murii** [comment]
The problem is that the compiler does not check if there's something to execute that's why it lets you do this. This issue is not that hard to fix but if you want to have comments and after the instruction comes then it becomes complicated.
