### ISSUE TITLE
Glow effect is too weak on android (GLES3).

### ISSUE THREAD

**Issue by runt1m33rr0r** [godotengine/godot#25704]
**Godot version:**
3.1 beta 3 (issue persists in 3.0.6 stable)

**OS/device including version:**
Lineage OS 15.1(Android 8.1), running on OnePlus 2 with Adreno 430 GPU with the GLES3 renderer.

**Issue description:**
The glow environment effect is much weaker on android than in the editor or desktop build. I am noticing the difference when using glow with emissive materials. I have to set the glow strength to be much higher in order to notice it on android.

On Linux PC: 
<img src="https://user-images.githubusercontent.com/19938633/52480045-4a778d00-2bb3-11e9-83b6-4f96d967343c.png"  height="300" />

On Android:
<img src="https://user-images.githubusercontent.com/19938633/52480070-59f6d600-2bb3-11e9-9317-e193ef447357.png"  height="300" /> 

**Steps to reproduce:**
Enable the glow effect.

**Minimal reproduction project:**
[game.zip](https://github.com/godotengine/godot/files/2845200/game.zip)

**Comment by Calinou** [comment]
Does this occur on the Android device if you change the project's stretch mode from `viewport` to `2d`?

**Comment by runt1m33rr0r** [comment]
Yes, the issue still persists with 2d stretch mode(or any other stretch setting).

**Comment by volzhs** [comment]
I guess this depends on resolution.
does it happen with stretch viewport mode?

**Comment by runt1m33rr0r** [comment]
Yes. It does not seem to be resolution dependent. The glow effect starts being noticeable after setting the strength to 1.1 or higher with sreen blend mode(other blend modes have the issue as well), but at that value it just looks unbearable in the editor.

**Comment by timoschwarzer** [comment]
Could it be that you have HDR disabled on mobile? (Which is the default)

Project Settings > Rendering > Quality > Enable `Hdr.mobile`.

**Comment by runt1m33rr0r** [comment]
I tried your suggestion and the result is the same. I have tried all kinds of configurations. I tried enabling all disabled mobile features from the quality settings and the glow effect is still that weak. There is probably an issue with the way the glow effect is being rendered on android.

I also tried the game on another android device and noticed no difference in the result.

Is there someone who has gotten the glow effect to work on mobile without any issues?

**Comment by LionH** [comment]
Is there any workaround for this problem, I got the same issue.

**Comment by neogn95** [comment]
+1

**Comment by clayjohn** [comment]
The current workaround is to use the GLES2 renderer. Mobile had a lot of problems with GLES3 which is why we are moving to GLES2/Vulkan renderers for 4.0.

This issue won't be fixed in GLES3. So closing.
