### ISSUE TITLE
iOS purchases are not finished

### ISSUE THREAD

**Issue by alekmlynek** [godotengine/godot#25718]
**Godot version:**
3.0.6

**OS/device including version:**
All iOS platforms. Reproduced iPhone 8 / iPad Pro running iOS 12

**Issue description:**
When a consumable (and non-consumable) is purchased, the transaction is not finished. This breaks consumable in-app purchases. If a user attempts to purchase the same consumable a second time, iOS tells them that they have already purchased the product and will not repurchase it.

This is a major show stopper for commercial iOS games, and exactly the problem I'm struggling with. 

**Steps to reproduce:**
- Use Godot's iAppStore to make a consumable purchase on an iOS device
- Purchase it a second time, iOS will warn you that you've already purchased it and will not continue

In Code:
in_app_store.mm: 227 - auto_finish_transactions equals false
in_app_store.mm: 316 - auto_finish_transaction is hard-coded to false
in_app_store.mm: 320 - intent for transaction queue, unfinished?

**Minimal reproduction project:**
Due to the nature of this bug, I've provided a project and template but things like ios team ID and test appstoreconnect product will have to be added manually. NOTE: I've left out the *.a* file that is required to run the XCode project. Please link your own, GitHub won't allow the size.

[iap.zip](https://github.com/godotengine/godot/files/2847066/iap.zip)

**Comment by alekmlynek** [comment]
For this struggling with this, I've removed the conditional from the source. Until Godot has the capability to 'validate a receipt' I think the engine should automatically close transactions, state this in the documentation, and put the onus on the user to do this manually IF they require it.

Best practice states that transactions should be validated on a remote server, not in the application itself, as that will expose the Apple secret token if the application is decompiled.

For now, and until Godot has the ability to give help people validate and close a transaction, this should be automatically done.

To fix, open in_app_store.mm and comment out the conditional statements for the block on line 227. Leave in: ` [[SKPaymentQueue defaultQueue] finishTransaction:transaction];`

**Comment by wombatwingdings** [comment]
Could this be why I'm getting a "purchase" event from InAppStore.pop_pending_event() every time I start my app, not just after a successful purchase? I don't think it should be doing that.

I will try your fix. Thanks!

**Comment by wombatwingdings** [comment]
This issue is resolved in the latest Master (3.1) branch. There are two undocumented functions that finish the transaction:

```InAppStore.set_auto_finish_transaction(true)``` 
(basically does the same as your fix without changing Godot source)
or you can finish the transaction manually with:

```InAppStore.finish_transaction(PRODUCT_ID)```

This has fixed my “purchase” event happening on each invocation of the app.

I think a ticket needs to be raised to add these methods to the documentation.

**Comment by akien-mga** [comment]
Closing as per the above comment. The `InAppStore` singleton still needs better documentation, see godotengine/godot-docs#2715.
