### ISSUE TITLE
make install DESTDIR=foo

### ISSUE THREAD

**Issue by rofl0r** [godotengine/godot#25719]
the build documentation seems to be missing a section on how to install godot into a staging dir, this is a pretty standard thing needed by distros: https://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Comment by akien-mga** [comment]
There are no `make install` instructions (nor Makefile), and we also don't use the equivalent `scons install`, so a fortiori there's also no support for `DESTDIR`.

The build output is a single, portable binary, so you can put it anywhere with `install` or `cp` (including in `$DESTDIR/usr/bin`).

I looked into adding instructions for `scons install` at some point, but it was convoluted and you'd need to call them with the same arguments as your initial scons build, so at least point I prefer to just copy files manually for my Linux packages: https://src.fedoraproject.org/rpms/godot/blob/master/f/godot.spec#_218

**Comment by rofl0r** [comment]
would you mind stating that in the "how to compile" document to prevent future confusion ?
