### ISSUE TITLE
Error in every project after d3082c99

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25723]
**Godot version:**
3.1 d3082c99

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
This error appear every time when project is oppened:
```
ERROR: bind_methodfi: Class SpriteFramesEditor already has a method _gui_input
   At: core/class_db.cpp:1216.
```

**Comment by Zylann** [comment]
`_gui_input` is already registered by `HSplitContainer`, which uses it for splitter interaction
