### ISSUE TITLE
Texture alpha is not working as transparency in mesh

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#25726]
**Godot version:**

4fd579b

**OS/device including version:**

manjaro

**Issue description:**

Trying to enble alpha in texture but not working in 3.1.
Tried the same in 3.0 and it worked.
![screenshot_20190209_132622](https://user-images.githubusercontent.com/10883749/52517055-05fdf700-2c70-11e9-922c-2b47d1d7f4bb.png)
![screenshot_20190209_132642](https://user-images.githubusercontent.com/10883749/52517056-0ac2ab00-2c70-11e9-8890-afbfe28fce2e.png)

**Steps to reproduce:**
Use a texture with alpha channel and set it as a texture of a mesh. Enable the transparent flag for the 
Spatial material

**Minimal reproduction project:**

**Comment by ZX-WT** [comment]
Might be related to #25536

**Comment by kubecz3k** [comment]
On what graphic backend do you have this problem (gles3, gles2, both)?  Are you able to provide reproduction project?

**Comment by ZX-WT** [comment]
I was using gles3. Strange, I cannot reproduce the issue again...

**Comment by kubecz3k** [comment]
Thank you for the report and double checking, let us know if you encounter the issue again
