### ISSUE TITLE
Editor Crash when changing vector values of ConvexPolygonShape2D in CollisionShape2D 

### ISSUE THREAD

**Issue by Diaspater** [godotengine/godot#25729]
**Godot version:**

v3.1.beta1.official

**OS/device including version:**

Windows 10

**Issue description:**

Changing a vector value of a ConvexPolygonShape2D used by a CollisionShape2D causes the editor to crash.

**Steps to reproduce:**
Create a RigidBody2D as the root node
Create a CollisionShape2D
In CollisionShape2D, create a new ConvexPolygonShape2D in the Shape field using the Inspector
Create an Area2D
Duplicate the CollisionShape2D
Reparent one of the CollisionShape2Ds under the Area2D
Change the first Vector2 in the PoolVector2Array in the Points field using the Inspector

This does not always result in a crash, while testing some stuff I was changing the vector values back and forth. They were always valid vectors for a convex shape (just putting that out there since someone will probably ask). In my case, I was changing the x value of the first vector back and forth between 5 and 8. After a few changes, usually less then 10, the editor would crash losing any information that had not been saved up to that point.

I have reduplicated this crash on my machine at least 6 times intentionally to confirm as much as I know how to and to make sure is wan't a completely random crash.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Is this still reproducible in 3.1 beta 3?

**Comment by Diaspater** [comment]
I was only able to reproduce it once deliberately in v3.1-beta3 using the windows 64 executable. It didn't trigger until I switched to a different scene in the editor, switched back and made a change in the vector. I wasn't able to reproduce it reliably after that first deliberate time. So it seems to still be there, just triggered less frequently then in v3.1-beta1 win64.

**Comment by Diaspater** [comment]
Is there anyway for me to get a log or dump file from a crash that I post here?

**Comment by qarmin** [comment]
I can't reproduce crash on master.
I don't know if this is  fixed or I'm doing something wrong

**Comment by Diaspater** [comment]
I am updating to 3.1.2 stable and will post an update if this continues to occur.

**Comment by akien-mga** [comment]
I'll close for now as there hasn't been a new confirmation, and there's no project to test with. If you can still reproduce the issue, please upload a project that can be used to reproduce it.
