### ISSUE TITLE
export to android error with  64-bit Godot engine

### ISSUE THREAD

**Issue by catafest** [godotengine/godot#25737]
export to android with  64-bit Godot , works only 32-bit
**Godot version:**

all 64-bit Godot  version with and without mono 
the 32-bit version export well
**OS/device including version:**

Windows OS , Nvidia 740M

**Issue description:**

**Steps to reproduce:**
create a project 
try to export to android with 64-bit Godot 

**Minimal reproduction project:**

the

**Comment by akien-mga** [comment]
What is the error...?

**Comment by KoBeWi** [comment]
Works for me.

**Comment by Calinou** [comment]
@catafest Do you still experience this issue with Godot 3.1 or the `master` branch?
