### ISSUE TITLE
GPU particles not emitting in GLES2.

### ISSUE THREAD

**Issue by runt1m33rr0r** [godotengine/godot#25733]
**Godot version:**
3.1 beta 3

**OS/device including version:**
GLES2 renderer on all devices.

**Issue description:**
3D GPU particles (the spatial Particles node) does not emit particles when using the GLES2 renderer. Also the "Emitting" checkbox does not work and can not be checked.

**Comment by arkology** [comment]
Only gles3 supports gpu particles, this is normal

**Comment by Calinou** [comment]
As @arkology said, you must use CPUParticles (or CPUParticles2D) to render particles that will display in both GLES3 and GLES2 renderers.

**Comment by akien-mga** [comment]
There should be a warning in such situation, otherwise it's hard to know that one can't use this node.
