### ISSUE TITLE
Collision not aligned to tile if the sprite pivot is not centered

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#2573]
~~You can see the problem here: http://godotengine.org/topics/12370?r=12390 It would be helpful if the _Y Sort_ option in **TileMap** could work with a custom pivot.
For example, I could add a **Position2D** node to my tile sprite before converting it to a tileset. Then **TileMap** could use it instead of the sprite's pivot (just for the _Y Sort_ option, of course). If omitted then it could use the sprite pivot by default, like it does now.~~

I renamed this issue since it looks the actual problem is a different one (read comments below).

**Comment by reduz** [comment]
moving the sprite pivot is not enough?

On Mon, Oct 5, 2015 at 1:27 PM, Ignacio Etcheverry <notifications@github.com

**Comment by neikeq** [comment]
This is the result of moving the sprite pivot:
![](http://i.imgur.com/TtmxIgL.png)

It would be fine if the problem was just that the tile is not aligned to its cell, I could just make every tile the same. But the collision is also not aligned, and it's really hard to align it in the editor.

**Comment by reduz** [comment]
this does really sound like a bug. Is the collision missaligned during the
gameplay too? (just ruling out that it may be displayed incorrectly during
runtime)

On Mon, Oct 5, 2015 at 1:45 PM, Ignacio Etcheverry <notifications@github.com

**Comment by neikeq** [comment]
Yes, the screenshot is runtime with visible collision shapes and the "troll" collides with that collision shape.

Also, it may not be related to the issue, but Y Sort option is also applied to collision shapes draw order. I am not sure if it's the desired behaviour:
![](http://i.imgur.com/96YHz0T.png)

**Comment by reduz** [comment]
Ah.. Collision should have higher Z..

**Comment by neikeq** [comment]
Should I rename the issue? Since it looks like the problem is with the collision shape, the extra pivot thing is not needed if that's fixed.

**Comment by neikeq** [comment]
I am closing this issue since it resulted in 3 different issues:
- The first one (crossed) is no longer required.
- The issue about collision shape not aligned to sprite seems to be related to #2231
- I created a new issue for the last one: #2985
