### ISSUE TITLE
SplitContainers show their handles with Container children

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#25735]
**Godot version:**
 6c24332

**Issue description:**
When a `SplitContainer` has `Container` types as their children, hovering them will make the handler show up.

**Comment by groud** [comment]
How is that a problem ? 
If a container node has children it is normal that the handle is visible, even if those children containers have no children themselves.

**Comment by YeldhamDev** [comment]
Because it's a flickering mess:
![peek 2019-02-10 11-03](https://user-images.githubusercontent.com/30739239/52534053-65bdd600-2d34-11e9-8fc8-5fbb73079364.gif)

**Comment by groud** [comment]
Oh ok, I understand. 
You meant hovering the container themselves. I though you meant hovering the handles, which would have been expected.
