### ISSUE TITLE
MainLoop.NOTIFICATION_WM_FOCUS_OUT not properly triggered on Android

### ISSUE THREAD

**Issue by AlexRixhardson** [godotengine/godot#25747]
**Godot version:**
3.1 Alpha 3

**OS/device including version:**
Android 9.0/Nokia 7 plus

**Issue description:**
MainLoop.NOTIFICATION_WM_FOCUS_OUT is not called when window's focus is lost. Instead, it is called when the window's focus is returned, slightly before MainLoop.NOTIFICATION_WM_FOCUS_IN. This probably causes all sorts of negative side effects. One, that I noticed, is that if you're using audio in your game and you want that audio to mute when player switches to another app (and un-mute on first player's action, not immediately after MainLoop.NOTIFICATION_WM_FOCUS_IN), then you will notice that even though you muted your audio on MainLoop.NOTIFICATION_WM_FOCUS_OUT notification, there will still be a split second of your audio playing once the player returns back to your game.

**Steps to reproduce:**

1. Add audio to your game
2. Mute audio on MainLoop.NOTIFICATION_WM_FOCUS_OUT notification
3. Do NOT un-mute the audio on MainLoop.NOTIFICATION_WM_FOCUS_IN (let's assume you want to keep it muted)
3. Run the game on Android, switch to another app, return to your game and you will hear your audio for a split second, even though it should be muted

**Minimal reproduction project:**
[notifications.zip](https://github.com/godotengine/godot/files/2848200/notifications.zip)

**Comment by akien-mga** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce this issue as described above in Godot 3.3 or later.

**Comment by wilmer-daza** [comment]
Hi guys

I don't know if this is the right place to post this, but NOTIFICATION_WM_FOCUS_OUT is not working properly in android; is being triggered at the same time that NOTIFICATION_WM_FOCUS_IN when the application is resumed.

I'm trying to detect when the user exits the application (not by the "back" button but the "home" button)  or "minimized it"

Tested in Godot 3.3.2.stable on windows x64

Thank you

**Comment by volzhs** [comment]
it seems fixed with 3.4.beta f80b15bebc

[notification_test.zip](https://github.com/godotengine/godot/files/6615657/notification_test.zip)

**Comment by Reapetitive** [comment]
Im having the issue when running the game in Ubuntu. The game pauses on NOTIFICATION_WM_FOCUS_OUT, and doesn't unpause on NOTIFICATION_WM_FOCUS_IN. MainLoop and Node.

The code is something like:

if focus_in:
   unpause
elif focus_out:
   pause
