### ISSUE TITLE
Favorites are broken in the editor "Open a File" dialog

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#25748]
**Godot version:**

Godot master 5fa5678, also broken in Godot 3.1 betas 1-3, alphas 2-5
Works in Godot alpha 1

**OS/device including version:**

Xubuntu 16.04.5 LTS x64, 4.4.0-142-lowlatency

**Issue description:**

Favorites in editor Open file dialog not work at all. 

**Steps to reproduce:**
1) Show EditorFileDialog: press load Texture button to TextureRect node.
2) Select any folder or files and press Star button.
3) Spam error in output.
 
Errors:
```
scene/gui/item_list.cpp:248 - Index p_idx=-1 out of size (items.size()=0)
scene/gui/item_list.cpp:318 - Index p_current=-1 out of size (items.size()=0)
```

**Minimal reproduction project:**

[EditorFileDialog.zip](https://github.com/godotengine/godot/files/2848230/EditorFileDialog.zip)

**Comment by qarmin** [comment]
Can't reproduce on Linux Mint Mate with Beta 11

**Comment by groud** [comment]
No, me neither. @allkhor , could you try again with a more recent version ?

**Comment by allkhor** [comment]
Tested on e60465d, all good!
