### ISSUE TITLE
Preview not work in the editor "Open a File" dialog

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#25749]
**Godot version:**

Godot master 5fa5678, also broken in Godot 3.1 betas 1-3, alphas 3-5
Works in Godot alpha 2

**OS/device including version:**

Xubuntu 16.04.5 LTS x64, 4.4.0-142-lowlatency

**Issue description:**

Preview not work when list mode active in the editor Open file dialog.

![error](https://user-images.githubusercontent.com/1049442/52526144-9d019800-2cde-11e9-8a48-182135d38d6f.png)

**Comment by Amssat221** [comment]
We are a team working on this project for a CS class. Could we get assigned to this issue. Our uusernames are gsegovia2018,mattintriago,cniefit,amssat221
