### ISSUE TITLE
Godot 3.1 GLES2 errors

### ISSUE THREAD

**Issue by Valkia-INNOS** [godotengine/godot#25742]
**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
Hi! Could you post more information? Such as the errors you are receiving or the steps that led to those errors? Or just filling in the information it asks you to in the post would be great!

What you have currently posted is not enough for anyone to help you.

**Comment by Valkia-INNOS** [comment]
I don't know why this report went empty and strange how fast threads get closed, but anyway that is another matter.

https://www.facebook.com/groups/godotengine/permalink/1480609458742310/

I can't convert from GLES3 to GLES2 objects and even if i import objects of my projects from the beginning, i have the same issue as you can see the similar tests posted in godot fb page.

**Comment by akien-mga** [comment]
> strange how fast threads get closed

We get several dozens of bug report every day, we need to triage them efficiently if we want the relevant ones to have any chance to get fixed. If a report is not actionable, it is closed to let contributors focus on the ones where they can actually fix something.

> I can't convert from GLES3 to GLES2 objects and even if i import objects of my projects from the beginning, i have the same issue as you can see the similar tests posted in godot fb page.

Please file a specific bug report, filling the required information of the issue template.
