### ISSUE TITLE
TileMap tiledata corrupt when loaded from a PackedScene saved via ResourceSaver

### ISSUE THREAD

**Issue by bimblewizard** [godotengine/godot#25743]
,**Godot version:**
3.1 beta 3

**OS/device including version:**
Ubuntu 18.04.1 x86_64
Haswell-ULT Integrated Graphics Controller (driver: i915)

**Issue description:**
My project loads it's levels from a .JSON file and creates various Godot nodes via a GDScript. Once the level is loaded, it is saved into a .TSCN using a PackedScene, and the ResourceSaver class. This .TSCN is then used instead of the .JSON file for future loads. Unfortunately I have found that the TileMap's tile data gets garbled/corrupt/lost in the process of loading the .TSCN generated via the ResourceSaver.

Interestingly if you open the saved .TSCN file in the editor and make changes, these changes remain intact.  What I can gather from the source code is that the editor saves and loads scenes in the same way as my script, so I'm not sure what is causing the issue.

**Steps to reproduce:**
Programmatically create a TileMap.
Set various cells
Add the TileMap to a PackedScene
Save the Packed Scene via the ResourceSaver
Load the TileMap via the ResourceLoader
TileMap data no longer matches original.

**Minimal reproduction project:**
[tilemap_save_load_bug.zip](https://github.com/godotengine/godot/files/2848069/tilemap_save_load_bug.zip)

**Comment by akien-mga** [comment]
The issue appears no longer reproducible in the current master branch, I always get "100% data matches".
