### ISSUE TITLE
Button shortcut not triggered from gamepad

### ISSUE THREAD

**Issue by FlavioFS** [godotengine/godot#25741]
I've searched for this issue but could not find anything similar.  
I also apologize in advance in case this is a duplicate one.

**Godot version:**

Godot Engine v3.1.beta2.official

**OS/device including version:**

Sony VAIO SVE14A15FBW:  
 - Windows 10 x64
 - Intel(R) Core(TM) i5-2450M @ 2.5GHz (4 CPUs)
 - 6GB RAM
 - AMD Radeon HD 7600M
 - XBOX 360 wired gamepad

**Issue description:**

### HUD Button *Shortcut* does not trigger InputEventAction for InputMap action "ui_select" when input source is a gamepad.

**Steps to reproduce:**
1. Load project [Dodge the Creeps!](https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html) from Godot's documentation.  

2. Navigate to menu **Project >> Project Settings >> Input Map**.  

3. Add a shortcut to your favorite button within the section "ui_select"
![bug](https://user-images.githubusercontent.com/4502942/52521785-66cf0480-2c5b-11e9-9572-65ae9d1e7366.png)  

4. Set the shortcut for the **Start Button** in your HUD scene:  
  - **Shortcut:** New Shortcut  
 - **Shortcut:** New InputEventAction
 - **Action:** ui_select
![bug2](https://user-images.githubusercontent.com/4502942/52521878-cd085700-2c5c-11e9-8698-e49c7161cf8a.png)
5. Run the game.

### Results
- The shortcut will work for the keyboard (spacebar), but not for the gamepad.  
- I can move the character with the gamepad, no keys are broken or loose. I've tested it.  
- Gamepad functions do work from GDScript.  

**Minimal reproduction project:**

This is the original project, I apologize one more time if the bug is within it.
[Dodge the Creeps! 3.0.zip](https://github.com/godotengine/godot/files/2847883/Dodge.the.Creeps.3.0.zip)

**Comment by FlavioFS** [comment]
## Update
Here is a really tiny project reproducing the supposed bug:
### [GamepadBug.zip](https://github.com/godotengine/godot/files/2848073/GamepadBug.zip)

![image](https://user-images.githubusercontent.com/4502942/52524137-7446b780-2c78-11e9-890a-b8c5a8cd2a86.png)

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/962c14278fafecf3d047fd070fc7ab8d4dcc21da (tested on Linux with a wired Xbox One V3 controller).

**Comment by SpyrexDE** [comment]
This is an issue again in Godot 4 alpha 11.

**Comment by Calinou** [comment]
> This is an issue again in Godot 4 alpha 11.

Please open a new issue with a minimal reproduction project attached.
