### ISSUE TITLE
GDScript binary literals

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#25755]
Godot 3.1b3

I was doing some experiments in a test project involving binary masks, and I found GDScript does not have a binary literal format. It does have decimals (`12345`), it has hexadecimals (`0xfa57f00d`) but no binary: `0b00100110`. Could this be added in the language in the future? I use hex in the meantime but straight binary is easier for my head to wrap around due to the way I choose bit positions.

**Comment by aaronfranke** [comment]
Also, it seems that `ustring` has support for octals, but not GDScript, looking at the tokenizer.

**Comment by JellyWX** [comment]
+1, want something like this for bitmasking also, to interpret and read the map files im writing
