### ISSUE TITLE
Shadow line when using OmniLight at a specific angle

### ISSUE THREAD

**Issue by Alastor01** [godotengine/godot#25750]
**Godot version:** Godot 3.1 Beta 3

**OS/device including version:**
- Windows 10 64-bit
- GPU: Nvidia GTX 1050 Ti 4Gb

**Issue description:**
- When setting both Camera and OmniLight at the same point at the same angle facing X axis, a weird shadow line appears on the surface you face at runtime
(Picture attached to demonstrate
![shadow_bug](https://user-images.githubusercontent.com/43552811/52526212-55164d00-2cad-11e9-90db-b8776be1e3a8.PNG)
 the issue)

**Steps to reproduce:**
- Create new project, use default settings
- Import wall / ceiling tile with basic color or texture, convert to Meshlib and use as your tile
- Add Spatial, add GridMap as a child, set it up to use your tile
- Add Camera, OmniLight and WorldEnvironment; all as children of Spatial
- OmniLight settings: Shadows enabled, Reverse Culling enabled, Bios 0, Contact 0 (otherwise shadows look horrible)
- Make a basic plane out of ceiling / floor tiles 
- Make sure both Camera (rotation: y: -90) and OmniLight face in the same direction, X arrow
- Make sure both Camera and OmniLight are in the same position relative X and Z axises (camera can be in front of light as well)
- Run your the scene from this camera
- Observe the line right in front of you on the wall and / or ceiling, roughly in the middle

**Extra steps:**
- Move the camera towards the line (parallel to it) - it does not disappear
- Move the camera away from the line - it disappears if you are further than light origin / pivot point
- Rotate Camera - line disappears
- Rotate OmniLight - line moves with it

**Minimal reproduction project:**
- Included, please run Test.tscn
[Shadow_Bug.zip](https://github.com/godotengine/godot/files/2848263/Shadow_Bug.zip)

**Comment by clayjohn** [comment]
I can confirm using intel integrated graphics.

**Comment by eon-s** [comment]
Same for amdgpu on linux, it seems like a limitation of the omnilight, put it a bit far from the surface and the line disappears.

I remember seeing other artifacts when the light on cube mode is too close to objects.

**Comment by Alastor01** [comment]
@eon-s Ye, it would be problematic for FPS games using such light sources, as the artifact depends on exact location and rotation of camera in relation to OmniLight

**Comment by dioptryk** [comment]
I've had this problem recently on GTX 970, Godot 3.1.1-windows. I'm writing a 3d dungeon crawler game, shown from first person perspective; after adding a Camera (player) with a light (torch), I've had horrible striping artifacts, no matter the bias/shadow quality or other config options (you name it). The thing is, the OmniLight was a a child of Camera and was set at (0, 0, 0) in relation to parent. The moment I moved the light a bit (about 0.2 in all directions, simulating handling the torch in right hand, and my geometry scale is pretty small, person size < 1.0), _voila_ - all the shadows started working instantly **with no artifacts whatsoever** (even the performance got better). I think this case should be documented (Camera-Light position relation).

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3
The project is broken on master (mesh is invisible).

**Comment by clayjohn** [comment]
Fixed in 4.0. The problem here comes from using dual paraboloid shadow mapping. Godot 4 now uses cubemap shadows by default and avoids this issue
