### ISSUE TITLE
Networking client generates own ID - Possible security issue

### ISSUE THREAD

**Issue by SmiggsGDog** [godotengine/godot#25752]
**Godot version:** 3.1 Beta 3

**OS/device including version:** Win 10

**Issue description:** Looking through **networked_multiplayer_enet.cpp** it appears that the network clients are responsible for allocating their own unique IDs and sending them to the server. The server then only checks to see if the ID is 0 and reallocates it as 1 (server). The server then proceeds to send this ID to all other clients.

I think this maybe a security issue as a client could:
1. Send a conflicting ID.
2. Send the ID of the server (bad actor).

Ideally, this ID should be generated on the server, checked, and issued/sent to the clients. This would also free up the UINT32 data field sent during ENET connection for things like a Game ID or password.

Please note: I'm just learning C++ so I could be mistaken. If so, sorry!

**Steps to reproduce:**
Check **networked_multiplayer_enet.cpp**  create client and poll.

**Minimal reproduction project:** N/A

**Comment by Faless** [comment]
Hi @SmiggsGDog , thank you for reporting this issue!
You are right, on both the issue and the potential solution.
Since we are close to a release, I've added server-side checks as a temporary solution.
The multiplayer peers will receive some more love in `3.2` and having the ENet server assign the ID to clients will hopefully be part of it :)

**Comment by SmiggsGDog** [comment]
Hi @Faless  , thanks for fix, and I understand theirs a bit of work to be done to get these things happening :)

I did start to make a build with peer id that incremented on the server side and updated the client but there is a lot of back and forth required for the client to report that its ready, etc. This is when it dawned on me that there probably already a unique id generated and stored in enet_peer that could be reused for this purpose. Admittedly, I haven't checked exactly what is stored in the field connectID (yet) but it seems like a good place to look. 

Also, some digging (on a mobile screen on a train) in to how the IDs are matched to the sender of a packet and suggests there could be a bit of a security issue here too due to clients being trusted for identify themselves. If the connectID could be used as a Unique ID for each peer it could also be used to validate that a packet came from the correct client. Of course the server would always need to be trusted to be telling the truth but there is not much that can be done about this.

Hopefully this is of some help, as I previously mentioned, I'm just cutting my teeth on C++ (and GIT for that matter) so hope I can contribute some clean code at some stage in the future :)

**Comment by Faless** [comment]
> there could be a bit of a security issue here too due to clients being trusted for identify themselves

That's already checked here
https://github.com/godotengine/godot/blob/dc583a6/modules/enet/networked_multiplayer_enet.cpp#L359-L360

**Comment by SmiggsGDog** [comment]
Ah, got you. peer -> data is set during connection and is compared against the sender in the packet. Ignore me.

**Comment by Faless** [comment]
@SmiggsGDog no worries, that code is indeed hard to grasp at first :)
