### ISSUE TITLE
Modulate not working as expected with set("modulate",Color())

### ISSUE THREAD

**Issue by gra-frogger** [godotengine/godot#2575]
get_node("Sprite").set("modulate",Color("ff37ff"))

if i use this command the image was colored with mix blend
	
get_node("Sprite").set("modulate",Color(233,0,0,1))

if i use this command the image fill with color and not see the image

**Comment by volzhs** [comment]
I think you should use Color(233.0/255,0,0,1) instead of Color(233,0,0,1)

**Comment by romulox-x** [comment]
On the help page for the Color class, you'll find:
"Values are in floating point, ranging from 0 to 1."

**Comment by reduz** [comment]
Heh, I wonder why you ended up changing color this way, there are other,
simpler ways to do it such as:

sprite.set_modulate(color)

and

sprite.modulate=color

**Comment by okamstudio** [comment]
sprite["modulate"]=color will also work :P

On Tue, Oct 6, 2015 at 11:35 AM, Juan Linietsky <notifications@github.com>
wrote:

> Heh, I wonder why you ended up changing color this way, there are other,
> simpler ways to do it such as:
>
> sprite.set_modulate(color)
>
> and
>
> sprite.modulate=color
>
> On Oct 6, 2015 04:54, "romulox-x" <notifications@github.com> wrote:
>
> > On the help page for the Color class, you'll find:
> > "Values are in floating point, ranging from 0 to 1."
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/2575#issuecomment-145774763
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2575#issuecomment-145875693>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment]
So is there a bug in the end, or just a wrong usage of Color()?

**Comment by MarianoGnu** [comment]
looks like user misunderstood how to create Color(), the description is in fact as expected.
