### ISSUE TITLE
TextureProgress with Radial Fill mode not drawn correctly when center offset value is changed.

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#25757]
**Godot version:**

Godot 3.1 Beta 3
Godot 3.0.6 Stable

**OS/device including version:**

Windows 10

**Issue description:**

This is the correctly drawn texture progress, with Godot 2
![rfillgodot2](https://user-images.githubusercontent.com/8316851/52531369-d837b180-2d46-11e9-85de-6cbae2ecd032.JPG)
And I re create it with the same parameter value in godot 3.0.6 and Godot 3.1 Beta 3, and It become like this.
![rfillgodot3](https://user-images.githubusercontent.com/8316851/52531400-70ce3180-2d47-11e9-9a90-a4df0b5212fe.JPG)

Also this issue happen if you change the Center Offset value under Radian Fill.

**Steps to reproduce:**
Open the achieve below, It contain the Godot 3.1 Project and also Godot 2 project as comparison.

**Minimal reproduction project:**

[RadianFill.zip](https://github.com/godotengine/godot/files/2848653/RadianFill.zip)

**Comment by volzhs** [comment]
![texture_progress](https://user-images.githubusercontent.com/8281454/52531586-fa3b2f00-2d5a-11e9-8e17-053b86005ea2.gif)
This demonstrates how current version (3.1.beta 3736a65f2) renders wrongly.

**Comment by volzhs** [comment]
suspicious pr is #18806

**Comment by akien-mga** [comment]
CC @robfram @Calinou

**Comment by akien-mga** [comment]
#18806 was not cherry-picked into 3.0.x, but #17422 was cherry-picked into 3.0.3.

**Comment by volzhs** [comment]
then #17422 seems to be the one.
