### ISSUE TITLE
MeshInstance2D copies Line2D's default color

### ISSUE THREAD

**Issue by FlamyAT** [godotengine/godot#25760]
**Godot version:** 33b64ec3f

**OS/device including version:** Ubuntu

**Issue description:** Having a both a `Line2D` and a `MeshInstance2D` visible changes the `MeshInstance2D`'s color. It copies mixes the `Line2D`'s `default_color` with it's own.

**Steps to reproduce:**
Create a scene.
Add a `Line2D`.
Populate the line with points.
Create a `MeshInstance2D`.
Choose any mesh.
Make sure both are visible.

**Comment by edouardgr** [comment]
I'll give it a go

**Comment by edouardgr** [comment]
Looks like the issue only exists within GLES3, but when switching over to GLES2, the mesh instance 2d doesn't take the line 2d's color. Is there any difference between how GLES2 and GLES3 handle color? I'm investigating rasterizer_canvas_gles3 and rasterizer_canvas_gles2 currently.
