### ISSUE TITLE
"Dof Near Blur"  has bug

### ISSUE THREAD

**Issue by Markmsq** [godotengine/godot#25765]
**Godot version:**
Godot_v3.1-beta3_win64

**OS/device including version:**
GTX1070 , Intel i7 7700 ,  Windows10

**Issue description:**
When I enabled "Dof Near Blur" in "WorldEvirovement", all worked well. But after a while, it just worked like when it is disenabled. And what was amazing was that it worked like "Dof Far Blur" after I clicked play... And then, in the editor, it just works like "Dof Far Blur"  or like being disenabled after I changes the value...

![bug2](https://user-images.githubusercontent.com/35923883/52534966-587c0800-2d83-11e9-8c54-89b46370020b.jpg)
![bug1_li 2](https://user-images.githubusercontent.com/35923883/52534967-5a45cb80-2d83-11e9-9d03-07553ffccd50.jpg)

**Comment by bojidar-bg** [comment]
Sample project or video recording of the bug is welcome.

**Comment by kaadmy** [comment]
Is this the same as #26236?

**Comment by Chaosus** [comment]
@Markmsq can you reproduce it on beta 11 ? @reduz has recently fixed simular issue, so you should check it again

**Comment by akien-mga** [comment]
Closing as there was no answer, and not enough information to debug. We need steps to reproduce or a sample project.
