### ISSUE TITLE
Repeating images (tiling) along a Line2D does not "always" work 

### ISSUE THREAD

**Issue by enthus1ast** [godotengine/godot#25768]
**Godot version:**

3.1.beta.custom_build.1d50a6e

**Issue description:**

Tiling textures along a Line2D does not work all the time, some lines display tiled
some does not:
Editor:
![editor](https://user-images.githubusercontent.com/13794470/52535665-7a5c9700-2d51-11e9-87ae-b539205179c2.png)

In game:
![bugtiling](https://user-images.githubusercontent.com/13794470/52535669-85172c00-2d51-11e9-8e32-7fb0145ad066.png)

**Minimal reproduction project:**

See the attached example project: 
[bugTiling.zip](https://github.com/godotengine/godot/files/2849047/bugTiling.zip)

**Comment by enthus1ast** [comment]
Strange, in the example project i duplicated the lines, and the tiling option was gone. 
When i now change the tiling option again it works. (So a mistake on my side i think).
But in our current game project we have exactly this problem. 
I currently cannot reproduce it in a example project.

**Comment by enthus1ast** [comment]
if i can repoduce it in a example project i'll repopen the issue

**Comment by enthus1ast** [comment]
A screenshot from the actual issue:
![actualgame](https://user-images.githubusercontent.com/13794470/52536178-556b2280-2d57-11e9-9655-1e0380324808.png)

**Comment by fanus** [comment]
Think it's worth revisiting this issue. I'm experiencing the same on my side.

The texture wasn't tiling in the editor at all. Then I put it on another node (not a Line2D node, think it was TextureRect) then I checked the "Repeat" flag (option isn't there for Line2D). When I put it back on the Line2D, it was tiling correctly in the editor but when I run it, it stretches   ;(

![image](https://user-images.githubusercontent.com/1243998/61085315-ed039880-a3fd-11e9-8dc7-ac65e0e3e9aa.png)

Strange behaviour all around, but I hope this helps narrow things down...

**Comment by Calinou** [comment]
@fanus Does it work if you set the texture to repeat in the **Import** dock after selecting it in the **FileSystem** dock?

**Comment by fanus** [comment]
It sure does. My bad and thanks!

**Comment by SamSuleymanov** [comment]
Is it possible to have tiles randomly rotated along the line?
