### ISSUE TITLE
Program Settings->Debugger->Command Line options

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#2577]
It would be nice to be able to set command line options when launching the application from the debugger.

**Comment by reduz** [comment]
God point. If you need a little secret, godot has a command line debugger,
you can run it with -d

**Comment by captainwasabi** [comment]
I've given the command line up for Lent.

**Comment by reduz** [comment]
is this not supported already btw? can anyone check?

**Comment by reduz** [comment]
in any case, moving to 3.1 given itś a feature request

**Comment by vnen** [comment]
Should be easy to do, I think. Just a matter of adding a property in the Project Settings and using it in `EditorRun`. Tagging as junior job.

**Comment by neikeq** [comment]
I swear there was such a property in project settings before, but it looks like it's not there anymore...

**Comment by RayKoopa** [comment]
I looked into [this](https://github.com/godotengine/godot/blob/master/editor/editor_run.cpp#L39) and pushed some custom args to the array built there, but the debugged game process immediately crashes at least on my Windows PC if I pass an argument not starting with a "-" or "--".

When I tried starting godot itself with such an non-prefixed argument, like `godot.windows.tools.32.exe hi` it yields and crashes with the following, is that done on purpose?
```
Activated GL 3.3 contextOpenGL ES 3.0 Renderer: AMD Radeon (TM) R9 390 Series
GLES3: max ubo light: 4096
GLES3: max ubo reflections: 1024, ubo size: 144
ARVR: Registered interface: Native mobile
ERROR: No loader found for resource: res://hi
   At: core\io\resource_loader.cpp:184
ERROR: Failed loading scene: res://hi
   At: main\main.cpp:1596
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:1988
```

If I'd add an option letting the user specify a custom "free-form" command line passed to their game, I think they'd expect non-prefixed parameters to work aswell.

**Comment by vnen** [comment]
@RayKoopa that's expected because the argument is the name of a scene to launch, if Godot can't find the scene, there's no way to recover so it exits. I'm not sure how to solve this case, but users should be expected to use only prefixed values for their game arguments.

**Comment by RayKoopa** [comment]
Does that mean that in compiled executables / shipped games, I can tell a game to launch a different scene other than the main one?

**Comment by AlexHolly** [comment]
Currently looking into this.
I added this to the main.cpp so that any arg can be passed without any settings.

Example run
`./game.x86_64 -port=9001 -arg2=test`


https://github.com/godotengine/godot/blob/master/main/main.cpp#L682
```
else {		
	Vector<String> key_value = I->get().split("=");
	if(key_value.size()==2) {
		String key = key_value[0].right(1);
		ProjectSettings::get_singleton()->set("args/"+key,key_value[1]);
		print_line(key+"="+ProjectSettings::get_singleton()->get("args/"+key));
	}
}
```

Is there a way to check whether a property is available like has_meta(...)?
Should I simply use ProjectSettings::get_singleton()->set_meta(..)?

Is this approach fine?

>Does that mean that in compiled executables / shipped games, I can tell a game to launch a different scene other than the main one?

Looks like it I am able to launch any scene with `./game.x86_64 res://example.tscn`

**Comment by RayKoopa** [comment]
I definitely wouldn't like my shipped games to be manipulatable that much from the command line already, and I wouldn't like to implement any checks just to circumvent that :(

**Comment by starry-abyss** [comment]
I think the point is that you can read the first argument, and then interpret it the way you want? Then it's not manipulatable by players, it's under your control

**Comment by akien-mga** [comment]
As mentioned in #17162, I don't think it useful to have a Project Setting for passing command line options. If you need to update project settings to change runtime options, then you can just as well use an autoload and/or export variables to set your options. It's eventually more convenient than passing a comma-separated string in the project settings IMO.

What would be useful is a way to pass runtime options to the system command line, i.e. when you run `./godot` / `godot.exe`, such as `./godot --game-options "opt1,opt2,opt3=42"`.

**Comment by vnen** [comment]
Isn't this what the `editor/main_run_args` option is for?

![screenshot from 2018-07-04 18-36-02](https://user-images.githubusercontent.com/5599796/42294666-281d473c-7fb9-11e8-83ff-c3a1b3413ac8.png)

**Comment by akien-mga** [comment]
@vnen That one is more to pass *Godot* options to the editor, such as `--fullscreen` to force it to run in fullscreen. What this issue wants (as I understand it) is a way to pass game-specific options to the game (which could be done via `main_run_args` somehow and then parsing `OS.get_cmdline_args()`, but it's not very straightforwward).

**Comment by vnen** [comment]
Oh, I see now. But yeah, I don't see how that would be useful, there are better ways to achieve this. You can simply add a new project setting and read it in the game (which is essentially the same process, without any new feature).

**Comment by captainwasabi** [comment]
So the original intent was tht I was using command line options to specify something (it's been almost 2 years, I don't remember what it was exactly) and it worked fine.  The problem was that when I ran the app from the debugger in the IDE there was no way to specify the command line options so the code would take the same path.

**Comment by akien-mga** [comment]
@captainwasabi Ok, that part is covered by the `main_run_args` mentioned by @vnen then.

**Comment by akien-mga** [comment]
Closing as per the last comments, the intended use case is doable already.

For custom command line arguments, let's move the discussion to #8721.
