### ISSUE TITLE
Class need to be saved in a local variable for tween to work

### ISSUE THREAD

**Issue by programaths** [godotengine/godot#25771]
**Godot version:**
3.1 Beta 3 (official)

**OS/device including version:**

Label|value
|-|-|
|OS Name|Microsoft Windows 10 Pro|
|Version|10.0.17134 Build 17134|
|Processor|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz, 3600 Mhz, 8 Core(s), 8 Logical Processor(s)|
|Adapter Description|NVIDIA GeForce RTX 2080|
|Driver Version	|25.21.14.1881|

**Issue description:**
Tween not working when used with a callback method in a chil class of a script unless care is taken to create a "local" reference and use "yield". (see bellow for explanations)

**Steps to reproduce:**

Launch the "game", it should work as intended.

Line 15 and line 16 of the script contains only this:
```
var ok = CupTween.new(tween,move1A.curve,cup)
ok = 0
```
This shows there is something keeping a reference to the instance created at line 15.
Remove line 16, run it, it should continue to work.

Edit line 15 so it reads:
```
CupTween.new(tween,move1A.curve,cup)
```

It will cease to function properly.

If you go back to the original content and remove line 17 (the yield), it will break too.

So, this is related to the life of "CupTween".
Somehow, Godot is not aware that the created instance is in use.

**Minimal reproduction project:**
[game.zip](https://github.com/godotengine/godot/files/2849169/game.zip)

**Comment by programaths** [comment]
Peeking at the code, I seed that tween interract with `ObjectDB::get_instance` https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/scene/animation/tween.cpp#L486

Maybe object is simply deregistered ?

**Comment by KoBeWi** [comment]
This is not a bug. Inner classes inherit from Reference by default (you can check by doing `print(self)`), which is freed automatically when nothing is pointing to it.

For a workaround, either make your class extend an Object explicitly (but remember to free it afterwards) or add this line to init: `tween.set_meta("test", self)`
