### ISSUE TITLE
GDScript does not allow a var to be named "case"

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#25787]
Godot 3.0.6
Godot 3.1 beta 3

If you write such a variable:
```gdscript
var case = 0
```
It produces an error:
```
SCRIPT ERROR: GDScript::reload: Parse Error: Expected identifier for local variable name.
          At: built-in:4
```
Even though `case` is not highlighted and is not a keyword AFAIK.

The doc says it is reserved, as well as `switch`, but we have `match` now. Should it still be reserved?

**Comment by MCoyne1234** [comment]
It should remain a reserved word even if match exists. `switch` is in so many other languages that it's easy and accessible for people who are already familiar with other languages. It'd be nice for people to be able to come in and basically drop their preexisting logic in without having to make a bunch of edits.

**Comment by vnen** [comment]
@MCoyne1234 I don't understand, how keeping the `switch` and `case` keywords make it easier to port code? In the current state they don't do anything, so it doesn't help at all.

I don't think we will ever implement switch-case statements, `match` already can do everything it can and also is more powerful. There's no reason to maintain two implementations of a the same construct.
