### ISSUE TITLE
generate and hide root node and make it unable to be deleted

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#25784]
Can godot please automatically add and hide root node in the scene?

I am using 3.0.6 and it's very frustrating that I need to add a root node every time I make a scene.
on top of that the root node isn't even able to be saved as a object so if someone accidently adds a node 
and children of it and tries to save it as a prefab they can't because it's the root node!

the scene itself should be a root node and then the scene editor should be what is in the root node.
I don't even see what the point in having the root node is in the editor when the who scene should be a root node anyways.

this would solve problem with people needing to reparent the root since it it would be automatically generated, hidden, and non removable.

here is another example of the problem with not generating a root node
![image](https://user-images.githubusercontent.com/2453707/52540914-d6202380-2d43-11e9-895a-0b2525a20f5f.png)
![image](https://user-images.githubusercontent.com/2453707/52540916-dddfc800-2d43-11e9-974f-26858a32ed63.png)

as you can see when I open my prefab it doesn't generate root node so I can't save the modifications I do to it.

**Comment by slapin** [comment]
Well, in 3.1 this is handled in elegant way, so you could wait for 3.1 or use master branch or backport that feature.

**Comment by Shadowblitz16** [comment]
how did they do it in 3.1?

**Comment by slapin** [comment]
Just show menu of nodes on new scene with some common defaults, you
can see for yourself.

**Comment by eon-s** [comment]
All scenes have a root node, if you hide it, you would not know how to access, add scripts, etc., is the way Godot scene tree works.
That root is also the owner used for serialization, you *must* to be able to see it.

I recommend you to read the documentation to understand how the scene and node system.

**Comment by Shadowblitz16** [comment]
@slapin ok i will check it out. 
@eon-s  even if it wasn't hidden it should still be generated on every new scene as the root node.

**Comment by akien-mga** [comment]
No, the root node should not be "generated". It's something that you should choose according with what you want your scene to be. The root node can be any kind of node, and its type has a big influence on how your set up your scene and write your code.

You seem to be unfamiliar with Godot scenes and what the root node actually is, so I would advise to review the Step by Step tutorial: http://docs.godotengine.org/en/3.0/getting_started/step_by_step/scenes_and_nodes.html
