### ISSUE TITLE
Crash when Child is Removed during Connected Function

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#2578]
If you've got some child which is connected to one of your functions, and you remove that child during the course of the function call, the application crashes without gracefully returning to the editor. The simplest code demonstration would be the following Node code, to which the Button child's "pressed" is connected:

    func _on_Button_pressed():
        var button = get_node("Button")
        remove_child(button)

An example project can be found at http://www.godotengine.org/attachments/640/Example.zip

**Comment by reduz** [comment]
This will never block because the control is in use as the window root. I just changed it so instead of crashing it will throw an error to the console. The right way to do it would be something like
call_deferred("remove_child",button)

**Comment by akien-mga** [comment]
Does reverting part of the above commit in 3a3ce98 mean that this issue would no longer be fixed? Or was it an independent change?
