### ISSUE TITLE
FindNode on new child

### ISSUE THREAD

**Issue by nathanthesnooper** [godotengine/godot#25789]
**Godot version:** v3.0.6.stable.mono.official.8314054

**OS/device including version:**
Ubuntu 18.04 bionic
x86_64 Linux 4.15.0-45-generic

**Issue description:**
GetChild() Immediately works after AddChild(), but FindNode() does not

**Steps to reproduce:**
- Make a new project
- Add a script to any node in a scene
- Add this code to `_Ready()`
```
Node node = new Node();

node.Name = "foo";

AddChild(node);

GD.Print(GetChild(0));
GD.Print(FindNode(node.Name, false));
```

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2849716/Test.zip)

**Comment by bojidar-bg** [comment]
Does get_node (GetNode) work in this case?

**Comment by nathanthesnooper** [comment]
Yes

**Comment by volzhs** [comment]
I think it's not about `mono` issue

```gdscript
func _ready():
	var node = Node.new()
	node.name = "foo"
	add_child(node)
	
	print(find_node(node.name, false))  # prints [Object:null]
	print(get_node(node.name))  # prints [Node:1118]
```

**Comment by volzhs** [comment]
I found this is not a bug.
This is parameter description for `find_node`
```
Node find_node( String mask, bool recursive=true, bool owned=true ) const
```

so, in this case, the 3rd parameter should be used as `false`

```gdscript
print(find_node(node.name, false, false)) # prints correctly.
```
