### ISSUE TITLE
Elements with global fonts don't render correctly in the editor view

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#25781]
**Godot version:** 3.0.6

**OS/device including version:** Windows 10 with GeForce 9800 GT/PCIe/SSE2

**Issue description:** When I set a global font, individual controls that don't have a custom font specified (and use the global font) render in the editor with the default (12px?) font instead of the global one.

**Steps to reproduce:**
- Create a new project
- Add a label to your project
- Click on the label. Under `Custom Fonts`, create a new `DynamicFont`, set the size to something big (like 72) and load a local .TTF/.OTF file.
- Save the font by clicking the Save icon under the Inspector tab.

![image](https://user-images.githubusercontent.com/31222662/52540010-fa373100-2d52-11e9-873d-baece9e3493a.png)

- Go to Project > Project Settings > GUI > Theme > Custom Font, and load the font you just saved. Click Close.

![image](https://user-images.githubusercontent.com/31222662/52540014-01f6d580-2d53-11e9-8c1d-f087aceee659.png)

- Go back to the label and clear the font
- Add a button and specify some text

Expected: the font-size and font-face rendered in the editor are the same as the global font.
Actual: they use the default font size and font face in the editor. (When you run the game, it shows the correct font.)

![image](https://user-images.githubusercontent.com/31222662/52540034-1935c300-2d53-11e9-8156-bbe7ecdd9667.png)

![image](https://user-images.githubusercontent.com/31222662/52540046-310d4700-2d53-11e9-8b06-dcdb3735dae8.png)

**Minimal reproduction project:** Available upon request

**Comment by nightblade9** [comment]
Does anyone know a work-around for this in 3.0.6?

Editing the `.tscn` file in a text editor seems to work, but it's painful. (Make the changes to a new project/scene, save, copy/paste into current project, update IDs, pray that it actually works ...)

**Comment by Calinou** [comment]
Instead of overriding the default font on a project-wide basis, you could assign a Theme resource to the root Control node with the Default Font property set to the font of your liking.

**Comment by nightblade9** [comment]
@Calinou I'm not sure I understand what you mean by the "root Conrol node." How/where do I set this?

**Comment by KoBeWi** [comment]
The font do change (at least since 3.1), but you need to reload the project to see it. See #24067
