### ISSUE TITLE
Allow screenshotting of the game and the editor via a key

### ISSUE THREAD

**Issue by fire** [godotengine/godot#25793]
https://github.com/godotengine/godot/issues/1155

**Godot version:**
6607c3c1c7dc7e6b3e381b71c6a46dcf59d3457b

**Issue description:**
I was having trouble creating a screenshot of the editor.

There's parts to this:

1. Expose create screenshots of the editor viewport and the game viewport.
2. Bind to a ui action. (F12 was mentioned. but print screen also works)
3. Saved in user:// with a timestamp in the name (Akien)

https://github.com/godotengine/godot-demo-projects/blob/master/viewport/screen_capture/screen_capture.gd has an example for game viewports, but not the editor.

**Comment by Zylann** [comment]
I guess if you want to screenshot the editor you can use the same code as you have in game, but registered as editor plugin.

**Comment by somnivore** [comment]
There's software available to do this already, I'm not sure how much value there is in this for the editor.

**Comment by fire** [comment]
That software isn't able to the render to scale the output or stick different screens together into one.

**Comment by fire** [comment]
This is a 3.2 feature.
