### ISSUE TITLE
Selected Node in Editors Node Tree isn't deselected when filtered

### ISSUE THREAD

**Issue by wombatstampede** [godotengine/godot#25794]
**Godot version:**
3.1beta 3

**OS/device including version:**
Windows 10
(Project was using GLES2, but I doubt that this matters)

**Issue description:**
1. Select a node in the node tree of the editor.
2. Filter the node list. So the selected node isn't visible in node tree.
3. Select another node by simply clicking (no modifier keys)
4. Properties shows "Multinode Edit" because previous node stays selected -> two selected nodes.

Expected behaviour:
All other nodes should be deselected when clicking a node in the node tree (be them filtered or not).

**Steps to reproduce:**
![demonstration](https://i.imgur.com/SLtkTqJ.gif)

**Minimal reproduction project:**
(any project with more than one node in a scene should do as testing ground)

**Comment by afeener2016** [comment]
Working on it
