### ISSUE TITLE
Exporting from Linux to OSX produces a PowerPC build

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#25791]
**Godot version:**
2.1.5 (should apply to any version)

**OS/device including version:**
Linux Debian stretch

**Issue description:**
Whenver I export the game to MacOS from linux and I try to run on a MacOS machine I get the following error message:
```
Cannot open application "CityGameStudio.app", PowerPC applications are
no longer supported on your Mac
```

I tried several version of xcode (9.1, 9.2, 9.3), also tried to export using 32bits, 64bits and fat. None of it worked. It is really annoying because PowerPC is no longer supported on MacOS since 2012.

**Comment by bruvzg** [comment]
That's strange, PowerPC support was dropped in Xcode 4.0 (2010 - 2011).

**Comment by bruvzg** [comment]
Could you provide exported project sample, exports settings and build commands you used? I have tested 2.1.5 export on Linux both with official and custom export templates and didn't manage to get anything similar.

**Comment by xsellier** [comment]
@bruvzg I agree it is strange.

Those are the templates Im using to export my project from X11 (Linux) to OSX.
https://github.com/xsellier/godot-builds/releases/tag/2.1.5-OSX-CGS

You can use this repository to reproduce the issue
https://github.com/binogure-studio/chart-gd

The exported project:
[chart-gd.zip](https://github.com/godotengine/godot/files/2852097/chart-gd.zip)

**Comment by bruvzg** [comment]
With exception of broken icon (fixed in 3.1, not back-ported) and usual unsigned binary warnings, your exported project runs fine on my Mac Pro (Late 2013) running macOS Mojave 10.14.3 (18D109) and in the VirtualBox VM running OSX Mavericks 10.9.5 (13F1911).

![screenshot 2019-02-11 at 19 01 05](https://user-images.githubusercontent.com/7645683/52579770-8585f480-2e2f-11e9-9735-8b3fca5aa03a.png)

```
Mac-Pro:Downloads bruv$ lipo -info ./chart-gd.app/Contents/MacOS/chart-gd
Non-fat file: ./chart-gd.app/Contents/MacOS/chart-gd is architecture: x86_64
```

**Comment by xsellier** [comment]
Did you run the chart-gd.zip directly?

**Comment by bruvzg** [comment]
> Did you run the chart-gd.zip directly?

I have extracted it, run `chart-gd.app` from Finder and run from command line using `open chart-gd.app`, how you supposed to run .zip directly?

**Comment by xsellier** [comment]
Oh man, I miss read that tiny documentation:

> When exporting for MacOS, if you export on a MacOS computer, you’ll end up with a .dmg file, while using Linux or Windows produces a .zip. In either case, the compressed file contains a MacOS .app that you can double-click and run.

So it means, I have to extract the zip before uploading it to steam?

_source:_
https://docs.godotengine.org/en/3.0/getting_started/step_by_step/exporting.html?highlight=dmg

**Comment by bruvzg** [comment]
> So it means, I have to extract the zip before uploading it to steam?

Probably. I'm not familiar with steam deployment, but steam is downloading all macOS apps as `.app` (like `SteamApps/common/NAME/NAME.app`).

> @bruvzg If I extract the zip file from a linux computer, Im getting a folder, and not an application.

This is correct `.app` is just a normal folder (as many macOS native "file" formats are), but macOS Finder will display it as app (you can still open it as folder in Finder by right clicking on it and selecting "Show Package Contents").

**Comment by xsellier** [comment]
Ok, It might be good to add that to the documentation. Im pretty sure that Im not the only one who has been fooled with that.

Thank you for your help @bruvzg

**Comment by xsellier** [comment]
@bruvzg So, I've tried myself using a VM with OSX 10.13.2. And it is a NOGO.
I downloaded Godot Engine to be sure that the VM can run Godot:

![image](https://user-images.githubusercontent.com/6616005/52607636-fbe12180-2e44-11e9-9dd4-c672c5e8222e.png)

Godot starts without any issue
![image](https://user-images.githubusercontent.com/6616005/52607657-0a2f3d80-2e45-11e9-887b-63b43d591975.png)

chart-gd does not
![image](https://user-images.githubusercontent.com/6616005/52607642-026f9900-2e45-11e9-9260-7766f165471b.png)

**Comment by xsellier** [comment]
So I can confirm, exporting from Linux to MacOS does not work. The binary just does not start. You need to export the project using MacOS. I've just tried, and guess what, it worked.

**Comment by bruvzg** [comment]
> The file inside the MacOS folder is not flagged as executable.

Looks like it's known (and quite old) issue: #527

**Comment by xsellier** [comment]
Closing because it is a duplicate.
