### ISSUE TITLE
AnimationPlayer: Ability to convert track from BezierCurve to Regular and vice versa

### ISSUE THREAD

**Issue by drtwisted** [godotengine/godot#25801]
**Godot version:**
v3.1-beta3

**OS/device including version:**
Antergos

**Issue description:**
It would be nice if AnimationPlayer had a fiture to convert any BezierCurve track to Regular one and vice versa. In case of converting BezierCurve.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/392 and https://github.com/godotengine/godot-proposals/issues/3141, as feature proposals are now tracked on the Godot proposals repository.
