### ISSUE TITLE
Incorrect mesh deformation during animation in 3D model DAE

### ISSUE THREAD

**Issue by N8n5h** [godotengine/godot#25806]
**Godot version:**
v3.1.beta.custom_build.be98a6e

**OS/device including version:**
OS: Ubuntu 18.04.1

**Issue description:**
[Incorrect mesh deformation during animation](https://media.giphy.com/media/2hgcznzmKBHFyfCsBk/source.mp4) 
[original in Blender](https://media.giphy.com/media/lktSgLnGDBeBkfDpiz/source.mp4)
The model and the animation (from Mixamo) were imported to Blender as fbx (Default + Ignore Leaf Bones + Automatic Bone orientation), and then exported to Godot with no changes, with the better-collada-exporter and [this settings](https://i.imgur.com/zLl9FjZ.png) 

Blender version: 2.79 2018-03-22 14:10 f4dc9f9d68b
better-collada-exporter addon: build from 2019-02-11 13∶23

**Minimal reproduction project:**
[testing1.zip (Blender file)](https://github.com/godotengine/godot/files/2853746/testing1.zip)
[testing-godot-project.zip](https://github.com/godotengine/godot/files/2853747/testing-godot-project.zip)

**Comment by Juankz** [comment]
I believe this is an issue with the collada exporter. Try exporting with the resting pose.

**Comment by N8n5h** [comment]
> I believe this is an issue with the collada exporter. Try exporting with the resting pose.

I tried that but then the animation won't play, the character will stay in T-pose

**Comment by Juankz** [comment]
As a work around. Import the working animation as a separate file and then add it to the T pose exported model.

Or export to gltf, I haven't seen this issue with gltf models, only dae.

Still this is a bug that harms the workflow considerably

**Comment by N8n5h** [comment]
> As a work around. Import the working animation as a separate file and then add it to the T pose exported model.

Please, can you elaborate the steps to do that?

**Comment by Juankz** [comment]
I'm writting this from memory, hope I don't miss anything:
1. Export animated model
2. Inside Godot select the .dae and go to the import panel, search for animation and change from builtIn to Files (or external, I don't remember the exact name). This generates a new file in your file system. By default is something like `default.anim`
3. Export model with T-pose
4. Import T-pose model, select its animation player and load the animation file from step 3 using the bottom panel

**Comment by N8n5h** [comment]
I tried that but [I didn't get it working](https://i.imgur.com/d1fdIPw.png) as expected. The animation still doesn't work and the scale and the rotation is messed up.

**Comment by N8n5h** [comment]
Any progress on this? 
There are a few issues I found that I cannot report yet because they might be related to the workaround for this issue...

**Comment by fire** [comment]
I wasn't able to get dae working in blender 2.81.

However gltf2 in blender 2.81 and with https://github.com/KhronosGroup/glTF-Blender-IO/pull/857.

worked.

![editor_screenshot_2020-01-10T151316-0800](https://user-images.githubusercontent.com/32321/72192818-d7c2f300-33bb-11ea-97a8-dce4079ceb70.png)


[testing1.zip](https://github.com/godotengine/godot/files/4048568/testing1.zip)

**Comment by fire** [comment]
If you want we can close this issue, I don't know how much more work will be done to maintain the Collada importer.

**Comment by jitspoe** [comment]
If you still want to use collada, there are a couple forks of the better collada exporter that work in newer blenders.  I think they also fix the issue described in this bug (it was an exporter issue, not an engine issue).

https://github.com/HungryProton/collada-exporter-2.8
https://github.com/artellblender/collada-exporter-2.8
