### ISSUE TITLE
Re-import menu doesn't show recently added resources

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2581]
When I add a new font, it doesn't show up in the re-import menu.
It shows up after I restart godot though.

**Comment by reduz** [comment]
That menu is also being reworked

**Comment by seadra** [comment]
Cool

**Comment by neikeq** [comment]
The re-import menu was recently removed in favour of automatically re-importing, was it not?

**Comment by akien-mga** [comment]
Indeed.
