### ISSUE TITLE
Add destination directory to load_resource_pack

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#25815]
**Godot version:** 3.1.beta3.mono

Currently `bool load_resource_pack ( String pack )` loads everything and then dumps it directly in `res://`. I would like to have an option to specify to what (virtual) directory contents of pck will be loaded. It shouldn't be a breaking change, since the new parameter could be optional.

For example after running this:
```
ProjectSettings.load_resource_pack("mods/mod1.pck", "mod1")
```
contents of `mod1.pck` would be accessible in `res://mod1/`.

**Comment by mnn** [comment]
Is this a desired feature, has it potential to be merged - should I try implementing it? (Operative word *try*, since I don't know much about engine internals nor C++.)

If not, I could explore other approaches to my problem, e.g. reading files' paths from pck and rejecting (not loading) invalid mods.

**Comment by akien-mga** [comment]
Reopening as #35261 was reverted, as it's not so useful without a proper remapping of dependency paths.

**Comment by akien-mga** [comment]
This should likely be reopened as a more detailed proposal on godot-proposals, with a suggestion on how to handle remapping dependencies to the new path.

See also https://github.com/godotengine/godot-proposals/issues/2689 which is a related proposal (though it doesn't seem to cater to loading in subpaths specifically).
