### ISSUE TITLE
Registered properties changes from GDNative are not picked up by editor

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#25812]
**Godot version:**
3.1.beta3.mono.official

**OS/device including version:**
Linux 64b (Kubuntu 16.04)

**Issue description:**
I changed registered property name (same issue with adding a new registered property), compiled C++ library, returned to editor, tried deselecting&reselecting node with script (also tried reattaching script, running scene [works for C#], closing and reopening scene), but changes to registered properties are not picked up in the inspector.

I made sure it was compiled - when running a game, new behaviour from C++ code was present, but the inspector was showing an old list of props.

I was expecting to not have to close whole project in order to refresh a list of registered properties in the editor. I didn't know if the refresh should be working, but seems so according to comments in https://www.reddit.com/r/godot/comments/ap4nmv/how_to_automaticallyeasily_refresh_list_of_script/.

**Steps to reproduce:**
Prepare working GDNative with C++ environment, compile C++ library, check properties in editor (first time the refresh seems to work), change registered properties (rename/add) in C++ lib, compile C++ code, check in the editor the list of registered properties (labelled as "Script Variables" in the editor, deselect&reselect of a node with the attached GDNative script should suffice for changes to be shown in the inspector).

---

Edit: Fixed many English issues (sorry, not my native language), tried to make more clear what I am doing, some formatting.

**Comment by ricardoalcantara** [comment]
https://github.com/godotengine/godot/issues/25812

**Comment by akien-mga** [comment]
Fixed by #27320.
