### ISSUE TITLE
Atlas one way collision is not working

### ISSUE THREAD

**Issue by juancolacelli** [godotengine/godot#25817]
**Godot version:**
v3.1.beta3.official

**OS/device including version:**
macOS Mojave 10.14.3

**Issue description:**
Atlas one way collision is not working (it just works in the first tile collision), single tiles are working well.
Atlas tiles look unsorted, single tiles are hard to sort.

**Steps to reproduce:**
- Create a TileMap
- Create a TileSet
-- Add an Atlas
-- Create collisions
-- Turn on "Shape One Way" property

**Minimal reproduction project:**
[tileset_bug.zip](https://github.com/godotengine/godot/files/2855160/tileset_bug.zip)

**Comment by akien-mga** [comment]
Likely related to #25610.

**Comment by akien-mga** [comment]
Ping @MarianoGnu

**Comment by MarianoGnu** [comment]
In fact, there's no way to enable one way collision at all. How did you setled it up @juancolacelli ?

**Comment by MarianoGnu** [comment]
This does the trick:
https://gyazo.com/2ae899c2bef23feaa1e16ee8e202b04a

**Comment by juancolacelli** [comment]
Hi @MarianoGnu, I don't see that option (using beta 10):
![screen shot 2019-03-04 at 11 35 48](https://user-images.githubusercontent.com/423381/53739922-b75c0b00-3e71-11e9-85b7-f5c04dce4588.png)

I used the cell editor on TileMap inspector:
![screen shot 2019-03-04 at 11 34 16](https://user-images.githubusercontent.com/423381/53739961-cfcc2580-3e71-11e9-9a89-b07f62a37f4c.png)

**Comment by MarianoGnu** [comment]
ah yes, changing it from there it will only change the first tile, the gift is from #26599 and is still not merged, so it's not included on Beta 10

**Comment by elvisish** [comment]
I'm still having this issue, the first tile is one-way but the others are solid. This is in 3.5 RC2.
