### ISSUE TITLE
[Mono] Godot.Collections.Dictionary (and possibly Godot.Collections.Array) do not increment reference counters.

### ISSUE THREAD

**Issue by xKamuna** [godotengine/godot#25818]
Not sure if this is currently known and fixed on master or something, but here goes:

**Godot version:**
3.1 beta 3

**OS/device including version:**
Windows 10

**Issue description:**

I have not tested this on an Array yet, but Godot Dictionaries in C# refuse to increment the reference counter through an assignment.  Therefore, objects get deleted when you don't want them to.

**Steps to reproduce:**
1. Create a `Dictionary<string, Reference>` member variable in any C# script.
2. Add a Reference using something like `dict[str] = someOtherwiseUnreferencedObject;`
3. Wait a while.
4. Try to access that Reference using `dict[str].DoWhatever()`.
5. Godot will crash, error varies.

Alternative 4. Verify that the object is deleted using `GD.Print(GD.Str(dict));`
Alternative 5. The dictionary will be something like `{str: [Deleted Object]}`

The current workaround is to manually use Reference_() and Unreference() or create a wrapper that does so for you.

**Comment by neikeq** [comment]
Oh, I think I know why this is. We are probably constructing Variant from Object* instead of Ref.

**Comment by neikeq** [comment]
Can you confirm if #25890 fixes the issue?

**Comment by xKamuna** [comment]
Yeah, I'll try it when I have the time tomorrow.

**Comment by neikeq** [comment]
I merged #25890. Let me know if it didn't fix the issue so we can open again.

**Comment by xKamuna** [comment]
Finally got a chance to test it out, the issue seems to be fixed, thank you!
