### ISSUE TITLE
Problem CollisionShape2D disabled (3.1)

### ISSUE THREAD

**Issue by ilyafuu** [godotengine/godot#25816]
**Godot version:**
v3.1.beta.custom_build.33b64ec

**OS/device including version:**
Ubuntu 16.04

**Issue description:**
Godot 3.0.6 works great CollisionShape2D.disabled = bool
Godot 3.1 fix pliz =)

> E 0:00:26:0494   Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead
>   <C Source>     servers/physics_2d/physics_2d_server_sw.cpp:737 @ body_set_shape_disabled()
>   <Stack Trace>  WorldMap.gd:22 @ fsignalstairs()
>                  Area2DSignalReturn.gd:16 @ _on_Area2DSignalReturn_body_entered()

**Steps to reproduce:**
Godot 3.0.6 ===>
![3 0](https://user-images.githubusercontent.com/17591539/52622996-42be2e00-2ebc-11e9-98e7-aca82678eac3.gif)

Godot 3.1 ====>
![3 1](https://user-images.githubusercontent.com/17591539/52623003-4651b500-2ebc-11e9-93a3-aea69459c6d4.gif)

**Minimal reproduction project:**
[PsychiatricHospital2D_test.zip](https://github.com/godotengine/godot/files/2855011/PsychiatricHospital2D_test.zip)

**Comment by akien-mga** [comment]
Could you provide a minimal project that reproduces the issue?

**Comment by ilyafuu** [comment]
already posted file

**Comment by PetePete1984** [comment]
Not sure this is a bug, was probably undefined "works by accident" behaviour in 3.0 instead. The error message is very specific and clear in what you need to do, otherwise you'd end up telling the Area "While you're detecting a collision, you're no longer an active collider" in the same physics frame.

**Comment by ilyafuu** [comment]
well this is an bug that cannot be missed wall, I have come up with some other option  .set_collision_layer_bit(id, bool) works no problem, only .disabled = bool does not work
![out](https://user-images.githubusercontent.com/17591539/52642288-c5121680-2eeb-11e9-9c0b-6e3a8372485e.gif)

**Comment by capnm** [comment]
> Can't change this state while flushing queries. 
> Use call_deferred() or set_deferred() to change monitoring state instead
> WorldMap.gd:22 @ fsignalstairs()
> … only .disabled = bool does not work

This is a layer 8 problem. Just use the friendly suggested
`arrsignalstairs[i].set_deferred("disabled", true)`, etc
and it will work.

**Comment by akien-mga** [comment]
> Just use the friendly suggested
`arrsignalstairs[i].set_deferred("disabled", true)`, etc
and it will work.

Indeed, that's an expected change in 0b1e93cc to fix bugs with changing physics properties during physics callbacks. You are now expected to use `set_deferred` as advised by the error indeed.

**Comment by jordanlis** [comment]
Hello, I have the exact same issue for the same functionnity : going up and down stairs. 

I put 

`stairs_shape.set_deferred("disabled", "true")`

But that doesn't work at all. Any idea ?
