### ISSUE TITLE
Converting to CPUParticles2D sets ZIndex to zero

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#25822]
**Godot version:**

Godot 3.1.beta3 (commit 6607c3c1c)

**OS/device including version:**

MacOSX 10.13.6

**Issue description:**

When I convert a Particles2D into CPUParticles2D, convertor sets ZIndex of new object to zero. 

**Steps to reproduce:**
Make some new Particles2D node. Set it's position and ZIndex above zero. Convert Particles2D to CPUParticles2D. It's position is correct but ZIndex is not correct.

**Minimal reproduction project:**

**Comment by samH-FIT** [comment]
Working on it
