### ISSUE TITLE
Description of node is not shown

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#25820]
**Godot version:**

Godot 3.1.beta fa7329f64

**OS/device including version:**

Kubuntu 18.10

**Issue description:**

Description of node is not shown.

**Steps to reproduce:**
Captured with Godot 3.1.beta3 official
![beta3](https://user-images.githubusercontent.com/8281454/52631420-13321480-2f02-11e9-8047-0400f0065b71.gif)

Captured with Godot 3.1.beta fa7329f64
![beta_master](https://user-images.githubusercontent.com/8281454/52631425-162d0500-2f02-11e9-804e-a9e0a4d3b7aa.gif)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
I was about to mention that it could be related to #25338 (only recent change to `CreateDialog`), but it seems it was merged right before beta3.

**Comment by volzhs** [comment]
possibly https://github.com/godotengine/godot/commit/a1f955a1d#diff-d1da977380504a5977e37b7e442eeb0a

**Comment by akien-mga** [comment]
CC @groud

**Comment by groud** [comment]
It is unlikely my change caused this behavior but who knows. I'll have a look.

**Comment by akien-mga** [comment]
Seems to work fine in 3.1 beta 4 (17809ca), which is only a few commits before the reported broken version at fa7329f... I'll try a bisect.

**Comment by akien-mga** [comment]
It's a regression from 4fd7115, CC @YeldhamDev.

**Comment by YeldhamDev** [comment]
But, that commit doesn't even touch that, as far as I can see?

**Comment by groud** [comment]
You removed some signals in the search bar code, maybe it has to do with this problem?

**Comment by YeldhamDev** [comment]
@groud Yes, the search bars in the script editor and docs, nothing to do with the "New Node/Resource" dialog.

**Comment by akien-mga** [comment]
`CreateDialog` uses `EditorHelpBit`, which you changed from a `PanelContainer` to a `MarginContainer`.

**Comment by YeldhamDev** [comment]
@akien-mga Huh, I couldn't even imagined that this was part of the dialog code, fixing it right now.
