### ISSUE TITLE
SpatialSamplePlayer Looped voices get overwritten while playing

### ISSUE THREAD

**Issue by lehthanis** [godotengine/godot#2583]
I added a long sample that takes several seconds to play, and a short sample that takes about a quarter of a second to play.  If I set polyphony to 3, and play the long sample, then start playing the short sample every half a second, the third short sample kills the long sample.  By the time this short sample plays, both the previous short samples are finished playing, and those voice IDs should be available for re-use.  The fact that it overwrites the non-finished voice while there are other voices available for use sounds like a bug to me.

This problem was initially discovered while attempting to get one voice to play in a loop while other voices filled in as requested. The looped voice gets overwritten after x number of sounds have played, with x being the number of voices.

**Comment by reduz** [comment]
this is not really a bug. If you want the voices to be independent, just create another SpatialSamplePlayer for it
