### ISSUE TITLE
Label's mouse input signal (mouse_entered, mouse_exited, gui_input) not working

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#25835]
**Godot version:**
v3.1.beta.mono.custom_build.b8319e7
v3.1.beta.calinou.be98a6e

**OS/device including version:**
Last Ubuntu LTS, Intel igpu, x86

**Issue description:**
When the mouse hover on the Label node no signal are cast.

**Steps to reproduce:**
Create a new label
attach script 
```GDScript
    extends Label
    func _enter_tree():
        connect("gui_input",self,"input_e")
    func input_e(event):
        set_text(str(get_class()," ",event))
```
expected result: when the mouse hover, the Label should change its text into ownclass and even type
actual result: nope

**Minimal reproduction project:**
[testing.zip](https://github.com/godotengine/godot/files/2857588/testing.zip)

![peek 12-02-2019 21-48](https://user-images.githubusercontent.com/42388967/52667000-04eaf500-2f10-11e9-89bc-4de49099801d.gif)

**Comment by AlexHolly** [comment]
Try this
![image](https://user-images.githubusercontent.com/4741886/52669695-0d92f980-2f17-11e9-9e1b-13f6bd294c1b.png)

**Comment by alexwbc** [comment]
I knew there was something amiss; I vaguely remember something alike in old Godot. But wasn't able to recall within the new iterations.
