### ISSUE TITLE
demo no it works in gles 2.0 for platform html5

### ISSUE THREAD

**Issue by IuryBorges1993** [godotengine/godot#25834]
demo screen_capture no it works in gles 2.0 for platform html5, please fix.

**Comment by QbieShay** [comment]
@IuryBorges1993 which demo?

**Comment by IuryBorges1993** [comment]
screen_capture

**Comment by QbieShay** [comment]
Can you say a bit more? What is not working?

**Comment by IuryBorges1993** [comment]
screen black generated  click of button, print an image black it screen

**Comment by QbieShay** [comment]
Can you send a screenshot?

**Comment by akien-mga** [comment]
We can't do anything with such a report, sorry.

Please follow the issue template and provide the minimal information required for the report to be meaningful.
