### ISSUE TITLE
Anti aliasing in 3.1 GLES2 Renderer

### ISSUE THREAD

**Issue by cart** [godotengine/godot#25843]
It looks like there is no way to get 3D anti aliasing in the new GLES2 renderer. The MSAA option is still present, but it does nothing. I'm currently evaluating the GLES2 renderer for my game but no AA is a deal breaker.

**Comment by reduz** [comment]
MSAA for GLES2 is quite complicated given there are three different ways it needs to be implemented.
I honestly didn't have time to do it, so volunteers are welcome. This is a post-3.1 feature though, but I offer guidance to anyone willing to implement it.

**Comment by Calinou** [comment]
It would also be worth looking at the FXAA implementation from 2.1 to see if it can be reimplemented in 3.1.

**Comment by reduz** [comment]
Well, maybe for nowadays uses, implementing this may be enough:

https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_multisampled_render_to_texture.txt

As I don't think supporting old Tegra chipsets is worth it (they have a special extension)

**Comment by reduz** [comment]
Implementation strategy is rather simple, you need to create an extra buffer for MSAA rendering (needs to be a renderbuffer, NOT a texture, and needs it's own multisampleddepth buffer), and resolve to the main one when you need it (as in, done drawing 3D, or using the _copy_screen function used for SCREEN_TEXTURE).

**Comment by triverske** [comment]
Right now you can use shaders and viewports to have FXAA, I currently have an implementation of this and it works fine. Obviously having MSAA is one of the reasons many choose Godot so having it in gles2 would be a welcome addition.
