### ISSUE TITLE
Texture region margin does not obey pixel snap

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#25845]
Godot version: 3.1 beta 4

Texture region margin does not obey pixel snap while the region rect does.

1. create a new texture style
2. try to make a 9 slice by setting the texture region and texture margin

![image](https://user-images.githubusercontent.com/2453707/52684104-ea0d8600-2ef9-11e9-9eeb-78522e61954b.png)

**Comment by YeldhamDev** [comment]
Manjaro GNU/Linux - I honestly can't reproduce this.

**Comment by Shadowblitz16** [comment]
sorry I am using windows 7 home

**Comment by akien-mga** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Arecher** [comment]
Been running into this as well (**3.2.3.stable**). The bug can be worked around, but can lead to annoying non-pixel perfect artifacts if you're not careful.

![TexturemarginBug](https://user-images.githubusercontent.com/10502115/106630975-9da33100-657c-11eb-90d1-0dd03a66c70a.gif)
_I chose 'Tile' as stretch on purpose, so you can clearly see the half pixel offsets in the margin_


To clarify, this is only an issue with the TextureMargins (the dashed lines) that can be dragged around. They do not snap to the set grid nor pixels, depending on the chosen snap settings. It would be expected that they do.

Here is the MRP: [TextureMarginSnapMRP.zip](https://github.com/godotengine/godot/files/5912718/TextureMarginSnapMRP.zip)

**Comment by YeldhamDev** [comment]
Reproducible. Happens in both the `3.2.*` branch as well as `master`.

**Comment by YeldhamDev** [comment]
The problem is actually bigger, as the margin's snap mode is always `None` when editing `StyleBox`es, but also always `Pixel` when editing `NinePatchRect`s.
