### ISSUE TITLE
Add HSV mode to color picker

### ISSUE THREAD

**Issue by Overblob** [godotengine/godot#25859]
**Godot version:**
Godot 3.1 Beta4

**Issue description:**
Currently the ColorPicker doesn't have a HSV mode
![image](https://user-images.githubusercontent.com/31958866/52735090-117e5480-2fc7-11e9-8294-dd46ad70db74.png)

Selecting color using HSV feels a lot more natural than RGB, I think it should be added as an alternative to RGB and RAW modes

Oddly this issue #471 suggests it was already implemented before

**Comment by Amssat221** [comment]
We are a team working on this project for a CS class. Could we get assigned to this issue. Our uusernames are gsegovia2018,mattintriago,cniefit,amssat221

**Comment by Chaosus** [comment]
> Could we get assigned to this issue

Of course, however(by technical reason on Github) if you not have a contributor tag - we unable to give the assignee tag for you
