### ISSUE TITLE
Crash in OS_X11::set_context when no application name defined

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#25852]
**Godot version:**
d6a88bb

**OS/device including version:**
Mageia 7, Linux

**Issue description:**
When running a project with no `"application/config/name"` defined, `OS_X11::set_context` crashes.
The bug is caused by #25481, CC @hpvb.

**Steps to reproduce:**
```shell
mkdir ~/tmp/test
cd ~/tmp/test
touch project.godot
godot -e
// create scene, run it, crash
```

**Minimal reproduction project:**
[bug_crash_X11_context.zip](https://github.com/godotengine/godot/files/2860213/bug_crash_X11_context.zip)

**Comment by bruvzg** [comment]
`config_name = strdup((char *)((String)GLOBAL_GET("application/config/name")).utf8().ptrw());`

`.ptr()`/`.ptrw()` returns NULL for empty string (there's `.get_data()` to return empty string) and `strdup` segfaults on passing NULL.

**Comment by hpvb** [comment]
Ugh, sorry. :P
