### ISSUE TITLE
SCREEN_TEXTURE in GLES2 always has alpha 0

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#25850]
**Godot version:**
master build from 35963eb

**Issue description:**
``SCREEN_TEXTURE`` was added to GLES2 shaders recently, but for some reason the alpha is always zero when reading from it. It works just fine if you set the alpha to 1 after reading from the texture. 

@reduz you were just working on ``copy_texscreen`` could it be something in there that is causing this?

**Comment by reduz** [comment]
Are you using it for 2D or 3D?

**Comment by clayjohn** [comment]
This is for 2D

**Comment by Th0r12356** [comment]
@reduz the commit 5784caa does not changed this behavior. I build from commit edbf1d0. Setting the alpha-channel manually to 1.0 is required.
[screenTextureAlpha_issue.zip](https://github.com/godotengine/godot/files/2894201/screenTextureAlpha_issue.zip)

**Comment by capnm** [comment]
Tested the current git tip 4f697f73a5ac567c1dc22ce44a7fab98f619dfe3, now it seems to work.

**Comment by Th0r12356** [comment]
Yes it works! it seems this commit doing the trick aab8f44.
