### ISSUE TITLE
Warning dock can't be collapsed if all warnings are ignored or fixed

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#25855]
**Godot version:**

Godot v3.1.beta4.official

**OS/device including version:**

**Issue description:**

I opened the warning dock. cleared all warnings and was left with an empty dock that can't be collapsed until another warning appears.

![selection_050](https://user-images.githubusercontent.com/6707330/52716943-34e1d900-2fa0-11e9-9837-e38240e36032.png)

**Steps to reproduce:**
Click the warning icon and the dock appears. After fixing all the warnings or ignoring them the dock still stays open and can't be collapsed.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Fixed by #25814 already :)

**Comment by YeldhamDev** [comment]
Wasn't this just fixed by #25814?
