### ISSUE TITLE
Tilemap : One way collision on a tile

### ISSUE THREAD

**Issue by anatagawa** [godotengine/godot#2585]
I use a StaticBody2D with a CollisionPolygon2D to have a "one way collision" , and works fine.

Make the same thing for a tile in my tileset, and not works, tile is Solid. "One way Collision" in the StaticBody2D on my tile dont make nothing.

Possible to have the same thing ? :)

**Comment by bojidar-bg** [comment]
If this is hard/impossible to do without rewriting everything over, another option is to have whole tilemaps that have one-way collisions enabled (still better than nothing :wink: ).

**Comment by reduz** [comment]
this was requested many times. And It's probably too late at this point but
one way collision should have been a shape property :| This will hopefully
be fixed by Godot 3.0, which intends to break some little compatibility to
improve usability

**Comment by trollworkout** [comment]
I also support this.

**Comment by tavotell** [comment]
Me too.

**Comment by reduz** [comment]
This is already working
