### ISSUE TITLE
Field Modulate - change first selected field to the hex value field

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#2586]
When clicking on field Modulate the first selected field should be the hex value.
![image](https://cloud.githubusercontent.com/assets/10463138/10399830/9d7592c2-6eb5-11e5-92c5-5833b600c244.png)

**Comment by reduz** [comment]
makes sense, will add before 2.0

**Comment by puppetmaster-** [comment]
cool

**Comment by akien-mga** [comment]
@MarianoGnu I guess you're familiar with this part of the code base :)

**Comment by MarianoGnu** [comment]
You mean in the moment you open the editor right?

**Comment by MarianoGnu** [comment]
there, it mantains focus and selection every time color is changed, so you can any time press Ctrl+C
