### ISSUE TITLE
Standalone expression warning when doing a ternary operation

### ISSUE THREAD

**Issue by luizcarlos1405** [godotengine/godot#25864]
**Godot version:**
3.1 beta 4

**OS/device including version:**
Linux Ubuntu 18.04

**Issue description:**
![image](https://user-images.githubusercontent.com/15899938/52755919-624d7780-2fde-11e9-9151-23f9dce8224f.png)

I have a question. This line works, but should it? If it should, then the warning is wrong. 

**Steps to reproduce:**
Open any script and
``` Python
extends Node

func a():
	pass

func b():
	pass

func _ready():
	a() if true else b()
```

**Comment by akien-mga** [comment]
The warning is incorrect, that statement is fine.

**Comment by vnen** [comment]
Well, you **are** making an expression and ignoring the result. Doing `a() + b()` likely will trigger the same warning&mdash;it should be obvious that you are ignoring the result of the addition&mdash;though both functions will be called.

Maybe the warning just need better wording to take this case into account.

**Comment by luizcarlos1405** [comment]
Is it possible to check if the functions return `void`? It is the case for me, so the returned values are not significant. I think it should be seen just as calling a method without receiving its argument and throw `Return value discarded` warning.
