### ISSUE TITLE
Godot Preview Window Crashes

### ISSUE THREAD

**Issue by Bat-Computer** [godotengine/godot#25869]
Godot 3.06

Windows 10 64bit, GeForce 550ti

Every time a project is run that has any error, the Preview Window opens but locks up. You have then to close the task for that window, it doesn't close itself. 

Re-installed several times, but always happens.

**Comment by qarmin** [comment]
Can you try to reproduce this on godot 3.1 beta 4?

**Comment by akien-mga** [comment]
It's normal that the game pauses when there is an error, it should show you the debugger in the editor. You can close the game with the Stop button.

**Comment by Bat-Computer** [comment]
![example-error-godot](https://user-images.githubusercontent.com/40317509/52788114-de37d600-3057-11e9-9438-557fb46fac8c.png)

Forgive me if I didn't explain myself well, I think the image says all.
It is not possible to close the Window with the "X", and an error occurs when you try, you have to close the process in Windows manually.

I have recently tried the Beta 3, but not noticed this behavior.

Thanks.

**Comment by Chaosus** [comment]
> I have recently tried the Beta 3, but not noticed this behavior.

Then I suppose it's fixed in 3.1 ?

**Comment by KoBeWi** [comment]
Closing as per above comment. Please comment if you can still reproduce in 3.3.1.
