### ISSUE TITLE
Cannot set RigidBody.Transform.origin in C# the same way it is set in GdScript

### ISSUE THREAD

**Issue by georgikoemdzhiev** [godotengine/godot#25862]
**Godot version:**
Godot 3.1 Beta4

**OS/device including version:**
Windows 10/GTX 1050
**Issue description:**
There seems to be a difference between the GdScript's API and C# regarding setting the "origin" property of RigitBoby.Transform. For example, that works fine in GDScript:
![image](https://user-images.githubusercontent.com/11027608/52750012-db4ece00-2fe2-11e9-9ad8-7c2a3c3ddc6a.png)
And that seems to be a problem when using the C# API:
![image](https://user-images.githubusercontent.com/11027608/52750038-f6214280-2fe2-11e9-9a49-9afaa0d5bb1c.png)

**Steps to reproduce:**

- Add a RigidBoby and Position3D notes to a scene
- Set the RigidBody's Transform's origin to the Position3D's Transform.Origin

**Minimal reproduction project:**

[MiniGoldC#.zip](https://github.com/godotengine/godot/files/2862536/MiniGoldC.zip)

**Comment by neikeq** [comment]
This is the way it works in C#. `Transform` is a property that returns by value, not by reference.
The correct way to do it would be:

``` C#
var transform = _ball.Transform;
transform.origin = _tree.Transform.origin;
_ball.Transform = transform;
```

Your GDScript example expands to the equivalent of that as well, but it's done automatically. That's not the case in C#.

**Comment by neikeq** [comment]
C# 7 introduced ref returns, but I don't think we can use this feature because the transform setter does more than just changing the value. It also propagates a notification about the change.

**Comment by georgikoemdzhiev** [comment]
Thank you for clarifying that. Much appropriated :)
