### ISSUE TITLE
convert scene to node?

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#25867]
Godot version: 3.0.6

I was just wondering if something like this could be implemented..
https://github.com/godotengine/godot/issues/3077

or at least something similar.

I think it's as great idea and I was actually trying to look for a way to make custom controls this way.
maybe having the ability to show the child nodes in the inspector too?

![image](https://user-images.githubusercontent.com/2453707/52759637-746ced00-2fc1-11e9-961e-c223c1419ae1.png)

**Comment by groud** [comment]
This is already possible in 3.1 with the class_name keyword.

**Comment by Shadowblitz16** [comment]
awesome thankyou

**Comment by Shadowblitz16** [comment]
actually please reopen this.
I mean convert scene to node not script to node

**Comment by groud** [comment]
This is the same, to do so you need to add a script to your node, use class_name, and the attached node will act as any other built-in node.

**Comment by Shadowblitz16** [comment]
how would multiple child nodes be serialized in the inpector though?

**Comment by groud** [comment]
Honestly, it is really unclear what you mean by "converting to a node". If you need to reuse a node and its children just make a scene. If you need to have a scene looking like a built-in node, you can use class_name and even choose an icon. So basically everything is already here to  transform a scene into "a node".

> also how would multiple child nodes be serialized in the inspector?

Like any other child node in a scene I guess.

**Comment by Shadowblitz16** [comment]
I mean having something similar to a scene template but with the ability to hide and show child nodes and their properties in the inspector, and being able to add a custom icon for the scene.

**Comment by groud** [comment]
> I mean having something similar to a scene template but with the ability to hide and show child nodes and their properties in the inspector

This can be done by enabling "editable children" on the instantiated scene.

> being able to add a custom icon for the scene.

This can be done via the class_name keyword

**Comment by Shadowblitz16** [comment]
![image](https://user-images.githubusercontent.com/2453707/52809321-c60a8b80-3044-11e9-95c2-4b949d428a4d.png)
