### ISSUE TITLE
Implement navigating a TabContainer's tabs with keyboard or controller inputs

### ISSUE THREAD

**Issue by Dragoncraft89** [godotengine/godot#25877]
As far as I know, currently it is not builtin to switch tabs with keyboard/controller input.
However I think this is essential when you're developing a game that is meant to be played with a controller.

On top of that when you implement your own "hack" to enable this, you are still unable to move the focus above the tabcontainer without setting the corresponding Neighbour up for each tab.

I propose to map a shortcut for changing tabs to TAB and SHIFT-TAB (which should only happen if you're inside a tabcontainer with the focus).
It should be possible to enable the tabs to gain focus themselves, so they can be selected with `ui_select`.

My proposed key shortcut is currently used by `ui_focus_next` and `ui_focus_prev` actions by default.
I don't see a particular use case for these 2 anyway, because navigating with left,right, up and down keys is more intuitive than tabbing through all controls in order (but maybe they have their valid use cases and I just don't know them).

I would love to see this built into the engine.

**Comment by KoBeWi** [comment]
Ctrl + Tab / Ctrl + Shift + Tab is a more common shortcut for changing tabs.

**Comment by Calinou** [comment]
This should be fixed by https://github.com/godotengine/godot/pull/26597.

**Comment by Shadowblitz16** [comment]
I am having this issue too

I need to be able to navigate tabs with not just the keyboard but gamepads as well
there is no tab on gamepads and up,down,left,right is how ui is handled it console games.

**Comment by iamthegithubghost** [comment]
I'm also having this issue, can't use gamepads to navigate tabs.

**Comment by Shadowblitz16** [comment]
you can't navigate between sliders either, and scrollbars can't even be moved with keyboard

**Comment by timkrief** [comment]
Hi there, I do have this issue on Godot 4.1.3. No obvious way to use keyboard or controller to navigate tab containers.

**Comment by Calinou** [comment]
This was implemented in 4.2 by https://github.com/godotengine/godot/pull/79104, closing. This won't be backported in 4.1.x, but you can try it out in 4.2.rc1 :slightly_smiling_face:
