### ISSUE TITLE
Godot 3.1 beta 4 crash when opening editor in Windows 10 with ATI Radeon HD 4250 GLES 2

### ISSUE THREAD

**Issue by rodolforg** [godotengine/godot#25872]
**Godot version:**
Godot 3.1 beta 4 (not tested previous beta)

**OS/device including version:**
Windows 10,  ATI Radeon HD 4250

**Issue description:**
Creating a new project with GLES 3 and opening it for edition, leads to unresponsive Godot, not changing of its splash screeen.
When I create a new project with GLES 2 and open it, it crashes after a few seconds of splash screen.

Console log:
```
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4976
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5001
c:\Users\1556897\Desktop>OpenGL ES 2.0 Renderer: ATI Radeon HD 4250
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:3222
fixed path: C:/Users/1556897/Documents/New Game Project/.import
unit: C:\
```

**Comment by hpvb** [comment]
Did you install the amd drivers from AMD's website? The drivers that come with windows don't support OpenGL very well.

**Comment by rodolforg** [comment]
OK. In AMD website I discovered that it does not have Windows 10 certification, so it uses Microsoft Basic Display Driver.
However, Godot 2.1.5 runs flawlessly.

**Comment by rodolforg** [comment]
Crash doesn't happen in 3.1 stable (since RC2, I think).
Some shadow-error is printed, however.

**Comment by akien-mga** [comment]
Thanks, closing as fixed then.

Could you open a new issue for the shadow framebuffer error? Run Godot with `--verbose -e --path "C:/Users/1556897/Documents/New Game Project/"` to potentially get verbose debug info around this error.
