### ISSUE TITLE
Steam Cards

### ISSUE THREAD

**Issue by rilifon** [godotengine/godot#25871]
Steam version should have Steam Cards, so I can earn some goodies while I program. :-)

**Comment by mrcdk** [comment]
Free games/apps can't drop trading cards unless you pay first for some DLC which godot doesn't have. https://steamcommunity.com/tradingcards/faq/

**Comment by akien-mga** [comment]
Beyond the fact that it's not allowed as mentioned by @mrcdk, it would mean that we should build Steam-specific binaries with the proprietary Steam API, just for the sake of such card drops... which we definitely don't want to do.

**Comment by girng** [comment]
your goodie should be the joy of making your game! not cards!

**Comment by rilifon** [comment]
@akien-mga actually you don't need Steam API to configure Steam Cards, the only requirement is an approval from Steam moderators to enable card drops and upload art for the cards.
But yeah, this applies for games, sad to know they don't allow this for free software.

I would ask for achievements, that I think could be added even for such softwares, but indeed would require a binary build just to integrate with Steam's API.

(Still, having achievements and a godot badge on my steam profile would be rad tho)
