### ISSUE TITLE
Parameter are visible but internaly empty, and when restart, all the values are empty

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#25889]
**Godot version:**
beta 4

**OS/device including version:**
Win10 64bit

**Issue description:**
In visual script :
parameter of functions and properties are not created (the value is visible but internaly empty) even if values are visible when play values considered as empty.
and when save and restart godot and load the project again the values of all nodes are clearly empty.

![image](https://user-images.githubusercontent.com/41632592/52814618-794ea100-3094-11e9-9d8c-bad9d8c7d1dd.png)

**Steps to reproduce:**
create project >> add sprite >> add visual script >> add animation player >> create animation >> add func _physics_process >> add play animation node and enter animation name >> add position and lookat nodes and enter values >> play (it will consider parameter as empty) >> save project >> exit >> reopen godot >> load the project and check parameters (it will be empty)

**Comment by Amssat221** [comment]
We are a team working on this project for a CS class. Could we get assigned to this issue. Our uusernames are gsegovia2018,mattintriago,cniefit,amssat221

**Comment by sami8github** [comment]
same on beta 5 release

**Comment by TrickMe** [comment]
beta 6 too

**Comment by TrickMe** [comment]
issue still present in "set" nodes with index (e.g. "set position.x" or "set modulate.g") in version RC3
