### ISSUE TITLE
get_tree() code completion does not work

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#25884]
**Godot version:** 3.0.6

**OS/device including version:** Windows 7

**Steps to reproduce:**<details>
<summary>gif</summary>

![screencast](https://user-images.githubusercontent.com/47334605/52805058-caf82b00-3096-11e9-8932-cf10798a7e27.gif)

</details>

I think that would be hard to code without code completion at all=)

**Minimal reproduction project:**
Open project, open `global.gd` script and try code completion after `get_tree()`. That should not work.
[get_tree_repro.zip](https://github.com/godotengine/godot/files/2870201/get_tree_repro.zip)

**Comment by akien-mga** [comment]
You need to open a scene where this script is used for `get_tree()` to be able to resolve to anything. If no corresponding scene is open, there's no SceneTree to match against.

**Comment by smedelyan** [comment]
@akien-mga this is a global script that extends `Node` that in turn has `get_tree()` method (and it returns `SceneTree`). I expected that to be enough to at least suggest me some methods / fields that all `SceneTree`-s have. So I do not understand the reasons to match against an existing SceneTree

**Comment by girng** [comment]
the autocomplete for `get_tree()` **works** for me,   when no scene is opened. i'm on 962c14278fafecf3d047fd070fc7ab8d4dcc21da though

**Comment by smedelyan** [comment]
@girng 
the point is to try `get_tree().<cursor here>` in the script that has been created **as resource** and included in auto-load. Thus it is not attached to any node of any existing scene. Did you try with that in mind?

**Comment by smedelyan** [comment]
@akien-mga 
@girng 
I've updated the initial message with minimal reproduction project. Check it out and let me know if it works for you.

**Comment by vnen** [comment]
This should work on 3.1, since the auto-completion was extended to add types and inheritance into account. I don't see an easy way to fix in 3.0.

**Comment by smedelyan** [comment]
@vnen thanks, I'll check it out later on 3.1 and let you know the results

**Comment by smedelyan** [comment]
I've checked it out in Godot 3.1 and it works quite well! Thanks all for the help, I'm closing this issue.
