### ISSUE TITLE
Area within concave CollisionShape wrongly reports overlapping with concave CollisionShape (Bullet)

### ISSUE THREAD

**Issue by rszibele** [godotengine/godot#25883]
**Godot version:**
Godot 3.1 Beta 3

**OS/device including version:**
Kubuntu 18.10

**Issue description:**
An Area inside a concave CollisionShape reports the concave CollisionShape as an overlapping body, which is incorrect.

**Steps to reproduce:**
1. Run the minimal reproduction project and press the "test overlapping bodies" button.
2. It will report 1 overlapping body, which is incorrect.

If you change the physics engine from Bullet to the deprecated GodotPhysics and rerun steps 1-2, then it reports 0 overlapping bodies as expected.

**Minimal reproduction project:**
![image](https://user-images.githubusercontent.com/1387224/52804292-308eec00-3084-11e9-9517-4f83201ed997.png)

[godot-collision-bug.zip](https://github.com/godotengine/godot/files/2866062/godot-collision-bug.zip)

**Comment by AndreaCatania** [comment]
I would like to put this in the docs, the concave shape is void inside so it can't detect objects.

**Comment by akien-mga** [comment]
It seems fixed in the current master branch, the MRP reports 0 overlapping bodies.
Please comment and attach an updated project if you can still trigger the issue differently.
