### ISSUE TITLE
Being able to set values like 0.001 in the editor

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#25887]
**Godot version:**
Godot Beta 4

**OS/device including version:**
Ubuntu 16.04

**Feature description:**
Pretty self explanatory, for setting up materials it's really handy to have that precision.

**Comment by akien-mga** [comment]
Please be more explicit, there are several values where you can already use 0.001. Some are limited to a range of 0.01 as common values don't need to go below. If you have a use case that needs to go below, you need to be explicit about which one.

**Comment by Janders1800** [comment]
Oh, sorry.
For example, if y want to add to a material a second pass to do an outline, the 'Grow Amount' cant be set like that.

**Comment by Chaosus** [comment]
I personally want that precision for Camera near and far planes - I think it could be very useful for simulate really small environments

**Comment by akien-mga** [comment]
Related: #19242

**Comment by Janders1800** [comment]
I think this commit addresses it: #29835

**Comment by akien-mga** [comment]
And further fixed for all properties without a range by #30776.
