### ISSUE TITLE
Touch release event doesn't occur in _gui_event() when index >0.

### ISSUE THREAD

**Issue by ninetones** [godotengine/godot#25880]
**Godot version:**
3.1 beta4

**OS/device including version:**

ASUS ZenFone 4 Selfie
Android7.1.1

**Issue description:**
On android device, _gui_input() is not called when a
 finger is released which does not touch firstly.
Related issue: https://github.com/godotengine/godot/issues/16761

**Steps to reproduce:**
Open the sample project and run on an android device with remote debug mode. Touch by fingers, then _gui_input() is not called by releasing fingers when touch index is greater than 0.

**Minimal reproduction project:**

[test_touch.zip](https://github.com/godotengine/godot/files/2865686/test_touch.zip)

**Comment by akien-mga** [comment]
CC @RandomShaper @lethiandev

**Comment by lethiandev** [comment]
I encountered this as well (https://github.com/godotengine/godot/issues/16761), also i tried to "fix" this issue by implementing a multitouch focus handling on _gui_input events (https://github.com/godotengine/godot/pull/23232) but it shown up that it's intended to work only with the first touch tho, imitating single point device.

It appears that you should work with _input event handler directly or TouchScreenButton node for multitouch support.

**Comment by RandomShaper** [comment]
@lethiandev is right. GUI input is designed for a single pointer. Multitouch input is converted to mouse/single-pointer input by keeping track of the touch point that initiates the gesture.

Therefore, that's expected behavior.

**Comment by 4903000** [comment]
This should be reopened. On Linux x11, touch indices are global and shared between all applications and are only ever incremented, therefore every touch index will be above zero after the very first time you touch your screen after you turn your computer on.

For reference, my touch indices are currently sitting at around 5000. They will not lower unless I reboot, and even then I'll only get the correct behavior once.

**Comment by RandomShaper** [comment]
Touch-to-mouse emulation tracks which touch index started the gesture and considers the virtual mouse button has been unpressed when that touch index number is released. As long as that is true, the reported behavior is not a bug.

The touch handling code does not make assumptions about touch indices like they being reused so they are always zero-based.
