### ISSUE TITLE
HTML5 export: GLES2: Tiled textures doesn't work for TextureRect and TextureButton, just black rectangle

### ISSUE THREAD

**Issue by etalot** [godotengine/godot#25897]
**Godot version: 3.1 master(downloaded yesterday)** GLES2

**OS/device including version:**
HTML5 GLES2 only

**Issue description:**
HTML5 export: GLES2: Tiled textures doesn't work for TextureRect and TextureButton, just black rectangle

![capturegd](https://user-images.githubusercontent.com/5445916/52835734-4c44d180-311a-11e9-95fd-c406e1909f60.PNG)

Must be:

![image](https://user-images.githubusercontent.com/5445916/52835746-5ff03800-311a-11e9-927e-284f8d2dc1f0.png)

**Steps to reproduce:**
Just add to scene TextureRect and TextureButton, assign texture, set Expand true, and set Stratch Mode: Tile, export to HTML5 or use "Minimal reproduction project"

**Minimal reproduction project:**
[Empty.zip](https://github.com/godotengine/godot/files/2867901/Empty.zip)

**Comment by reduz** [comment]
This is not really a bug, if you want tiling to work WebGL with GLES2, the texture needs to be a power of 2 and have mipmaps, which will look pretty bad anyway. I think in Godot 2.1 we automatically resized the texture to a PO2 and added mipmaps if you register it like this, so this may be added as a solution here..

**Comment by reduz** [comment]
Added a few hacks so this still works on WebGL
