### ISSUE TITLE
Invisible labels in editor menus.

### ISSUE THREAD

**Issue by syskrank** [godotengine/godot#25900]
**Godot version:**

Godot 3.1 custom-built,  e7e4d41a29044be753d1ab1574e131b02c9df007

**OS/device including version:**
Windows 10 x64
GeForce RTX 2070

**Issue description:**
Some labels such as "Add node" or "Open scene" are totally invisible within the editor.
Seems that both GLES2 and GLES3 are affected.

[Screenshot 1](https://ibb.co/pZP5CmM)
[Screenshot 2](https://ibb.co/598jk4G)

**Steps to reproduce:**
Create new project, select GLES3 renderer, witness the issue.

Could not reproduce in the latest beta ATM ( Godot 3.1 beta 4 )

**Comment by akien-mga** [comment]
Might be a regression from #25841.

**Comment by syskrank** [comment]
> 
> 
> Might be a regression from #25841.
Might be, as the bug is not present in the latest official beta build.

**Comment by akien-mga** [comment]
Confirmed, reverting #25841 fixes it.
