### ISSUE TITLE
Glitchy editor viewport when viewing 3D scene in GLES2

### ISSUE THREAD

**Issue by finkizo** [godotengine/godot#25908]
**Godot version:**
v3.1.beta4.official

**OS/device including version:**
Ubuntu 18.10 (64-bit)
Radeon RX 560 Series (POLARIS11, DRM 3.26.0, 4.18.0-15-generic, LLVM 7.0.0)

**Issue description:**
Editor 3D viewport glitches when resizing, only when using GLES2. Does not occur in previous betas.

![peek 2019-02-15 09-35](https://user-images.githubusercontent.com/47667808/52867581-e0a53900-3106-11e9-9a94-947f49d9affe.gif)

**Comment by akien-mga** [comment]
Might be related to #25804, which has been fixed since beta 4 in the master branch.

**Comment by finkizo** [comment]
Correct, issue has been fixed. Tried nightly build from commit 89eb79a and it no longer has this unwanted behavior.
