### ISSUE TITLE
Changing Colors in ui stylebox is not reflected on the scene

### ISSUE THREAD

**Issue by mani144** [godotengine/godot#25904]
**Godot version:**

Godot v3.1 beta 4

**OS/device including version:**

RTX 2080 ti

**Issue description:**

when i try to create a new styleboxflat, a property is shown, in the property you can change the color of the stylebox, however no matter what you color you choose the scene does not show the color unless you change the scene view. this gif explain it better : 

![ezgif-5-f961576522d1](https://user-images.githubusercontent.com/17520497/52857203-82dd1500-3137-11e9-8588-b67a600e55f6.gif)

**Comment by mani144** [comment]
i just noticed that its not only the color, but everything related to UI, even changing the border ... etc

**Comment by bojidar-bg** [comment]
I also redraws if you show/hide it, and if you slightly resize it.

**Comment by mani144** [comment]
I think it should be fixed before 3.1 release, and I hope it does
