### ISSUE TITLE
Compiling Windows templates from master repository need tools flag at yes

### ISSUE THREAD

**Issue by SamiDidier** [godotengine/godot#25903]
Godot version last source code from master repository

**Steps to reproduce:**

Define these Environment Variables to speed up compilation:
set SCONS_CACHE_LIMIT=5000
set SCONS_CACHE=%source_path%\.scons_cache

REM if Pywin32 Python Extension installed Parallel build with -j%NUMBER_OF_PROCESSORS%
REM https://github.com/scons/scons/wiki/GoFastButton
set SCONS_ARG=-j%NUMBER_OF_PROCESSORS% --implicit-cache --max-drift=1

In Windows, when running these commands in my custom build batch script:
scons -j%NUMBER_OF_PROCESSORS% --implicit-cache --max-drift=1 platform=windows tools=no target=release module_mono_enabled=yes
scons -j%NUMBER_OF_PROCESSORS% --implicit-cache --max-drift=1 platform=windows tools=no target=release_debug module_mono_enabled=yes

Builds failed with these errors : 
modules\mono\mono_gd\gd_mono.cpp(159): error C2039: 'get_data_mono_bin_dir': is not a member of 'GodotSharpDirs'
d:\private\godot\godot\modules\mono\mono_gd\../godotsharp_dirs.h(36): note: see declaration of 'GodotSharpDirs'
modules\mono\mono_gd\gd_mono.cpp(159): error C3861: 'get_data_mono_bin_dir': identifier not found
modules\mono\mono_gd\gd_mono.cpp(160): error C2065: 'mono_reg_info': undeclared identifier
modules\mono\mono_gd\gd_mono.cpp(160): error C2228: left of '.bin_dir' must have class/struct/union
modules\mono\mono_gd\gd_mono.cpp(160): note: type is 'unknown-type'

Looking in the gd_mono.cpp file, we have that : 
#ifdef WINDOWS_ENABLED
	path_value += ';';

	String bundled_bin_dir = GodotSharpDirs::get_data_mono_bin_dir();
	path_value += DirAccess::exists(bundled_bin_dir) ? bundled_bin_dir : mono_reg_info.bin_dir;
#else

In the modules\mono\godotsharp_dirs.h, 
#ifdef TOOLS_ENABLED
String get_mono_solutions_dir();
String get_build_logs_dir();

String get_project_sln_path();
String get_project_csproj_path();

String get_data_mono_bin_dir();
String get_data_editor_tools_dir();
String get_data_editor_prebuilt_api_dir();
#endif

I suppose that in gd_mono.cpp, we should have #ifdef WINDOWS_ENABLED && TOOLS_ENABLED.
Or in godotsharp_dirs.h #ifdef WINDOWS_ENABLED  || TOOLS_ENABLED

Is it correct or the issue is somewhere else as scons cache ?

By the way, by clean scons cache folder before running commands, issue still occurs.

Best regards,
Samuel

**Comment by akien-mga** [comment]
I think @hpvb fixed this for 3.1 beta 4 already, but likely forgot to PR the changes.
