### ISSUE TITLE
Skeleton2D wrong deformations with multiple instances

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#25911]
**Godot version:**

Godot 3.1 master 89eb79aef1aac645358664a8245afe35b30da130

**OS/device including version:**

Windows 10

**Issue description:**

When using multiple instances of a `Skeleton2D` animation the deformations are wrong.

https://streamable.com/noqcz

**Minimal reproduction project:**

[godot_animation_test.zip](https://github.com/godotengine/godot/files/2869939/godot_animation_test.zip)

Credits:
- cloud background: https://opengameart.org/content/sky-background
- You Xin: https://github.com/DragonBones/Demos

**Comment by akien-mga** [comment]
Might be related to #25204.

**Comment by mrcdk** [comment]
A couple of observations:
- If one of the instances isn't visible the animation looks okay. The moment you make that invisiblenode visible the one at the bottom of the tree will show wrong deformations.
- Making one of them local to the scene (aka, removing the instancing) still shows the issue.
- If there's a sprite between instances the issue WON'T happen. I guess anything that draws will work but I haven't tested it.

Video: https://streamable.com/rvpsj

**Comment by mrcdk** [comment]
Okay, I think I've found the issue. In `RasterizerCanvasGLES3::_set_texture_rect_mode()` this line https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_canvas_gles3.cpp#L291 will return `true` the second time because the first time the `p_enable` was false so it won't setup everything else the second skeleton needs (or the third, forth,...) I commented it out and it fixed the problem but I don't know if that's the correct way or not. @reduz will know 😅
