### ISSUE TITLE
Issue linking external library

### ISSUE THREAD

**Issue by robot2030** [godotengine/godot#2591]
Hello guys, 
I have this error 
"Error 1 error LNK1181: cannot open input file 'KinectGodotLib.windows.tools.lib' C:\godot\LINK godot"

my library name is 'KinectGodotLib.lib' what is the reason they renamed it??? is that the error?
I'm using VS 2013, i tried godot source from the Master branch and Godot stable release 1.1 with same error
please help !!!

**Comment by vnen** [comment]
As commented on Facebook post, this is related to how Scons rename files for different platforms/targets and has been solved.
