### ISSUE TITLE
Please change the "child" and "parent" names

### ISSUE THREAD

**Issue by JoshS** [godotengine/godot#25914]
Hello, my name is Josh and I am orphan. I have never got to have parents and everytime I use godot I am reminded that I am unwanted. Please change it to something different. thank you

**Comment by Chaosus** [comment]
No. Use sjw-trolling somewhere else

**Comment by LandonPowell** [comment]
I mean, it worked for master-slave keywords. :^)

**Comment by Chaosus** [comment]
Its an obvious trolling, from random person, and it has nothing to do with "my" political investment or experience

**Comment by akien-mga** [comment]
> let someone with more Godot development experience and less political investment handle it.

I don't know who you are to judge of @Chaosus' "experience" or "political investment", but he's fully qualified for closing this issue as he did, and I back his decision. This was a bad troll attempt, not a genuine request.
