### ISSUE TITLE
Expose SHA256 HMAC for String in gdscript

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#25928]
This is an extremely important requirement for my game as it is necessary to interface with a partner's API. 

It seems that mbedTLS already supports it, so it should just be a matter of exposing it in GDScript. I will take a pass at it when I get time, but I'm super swamped with other stuff, so if someone else has more time and wants to give it a go, it would be appreciated.

At any rate, my use case is I have a message string used for authentication that needs to be encrypted using an HMAC key. Since we already have `String.sha256_as_text`, it might make sense to do something like `String.hmac_sha_256_as_bytes` and return a `PoolByteArray`. 

Thoughts?

**Comment by jonbonazza** [comment]
To add to the discussion, another, more explicit and flexible approach would be to add an `HMAC` class that has static methods for encrypting and decrypting using HMAC keys.

Additionally, being able to geberate HMAC keys is also required.

**Comment by jonbonazza** [comment]
For now, I will probably implement this as a GDNative module since I have an immediate need for it and we are currently in feature freeze (even if we weren't who knows when it would get released). I would like to keep this issue open as I think it would still be useful to have in the core engine, but I will ultimately leave this decision up to the PMs. :)

**Comment by alekmlynek** [comment]
You're in luck, I also have the same issue and have written an HMAC library. It doesn't work 100%, I should get it stable in the next few days. Hope this helps.

https://github.com/swiftroot/godot-hmac

**Comment by alekmlynek** [comment]
First release is ready and stable. 
https://github.com/swiftroot/godot-hmac/releases

**Comment by jonbonazza** [comment]
@alekmlynek ah you are the best! Just saved me a couple days of work! Thanks!

**Comment by jonbonazza** [comment]
Are you going to be adding it to the asset store?

**Comment by Calinou** [comment]
@jonbonazza It's a static C++ module (not GDNative), does it make sense to host it on the Asset Library?

**Comment by jonbonazza** [comment]
Ah I see. So ill need to compile the engine myself to use it?

**Comment by Calinou** [comment]
@jonbonazza Yes, in addition to all the export templates you wish to use.

**Comment by alekmlynek** [comment]
Indeed. Perhaps at some point, we can merge it into the engine or I can write a GDNative version. For now, I needed to get something out for my own use and unfortunately did not have enough time to learn yet another language (GDNative). Already pretty burned out traversing objective-c++ libraries for iPhone.

Anyway, while compiling is a little annoying it's not terrible, though I'm already using other static C++ modules like AdMob so its necessary for me anyway.

Alternatively, someone made this:
https://github.com/Montecri/Godot-GameAnalytics/blob/master/GameAnalytics.gd

There is an HMAC sha256 function in that code if you search. I don't know how well it works, but if you don't want to compile the engine that might be another option to explore.

**Comment by jonbonazza** [comment]
@alekmlynek I started working on this: https://github.com/summerplaygames/godot-hmac

It's not ready for prime time yet, but it's close.

**Comment by alekmlynek** [comment]
@jonbonazza Looks really good. My only suggestion would be to actually just fork my repo, wrap it and contribute via a pull request. We're not doing anyone favours having multiple HMAC repo's. Also, you've grabbed my code under MIT and stripped the copyright.

I don't mind, but credit is all we have in open-source. You've also improved on my code, which I'd love to use as well. This would save us from maintaining two code bases, I could certainly learn from what you've done.

I'm not going to complain. We are using an engine with thousands of pooled 'free' hours but food for thought. I think working together is more beneficial for us, but also the community at large.

**Comment by jonbonazza** [comment]
@alekmlynek I'm happy to contribute back. In fact, I started with a fork of your repo, but then I had the thought that since you were using a built-in module, you likely didn't want all of the GDNative stuff. If you are okay converting this project to GDNative, I'd be happy to PR the code back into your project.

**Comment by alekmlynek** [comment]
Ah, thanks for clarifying @jonbonazza. I don't know a ton about GDNative, I assumed one could have both versions. A static module and GDNative extensions if they chose? My skill in this area is lacking, will definitely dive more into it once I finish my game. 

Not sure what the right call here is. I was hoping that, if a user typed in HMAC they would go to one repo which would give them 2 options of integration. A static module or a GDNative wrapper for it. Let me know if that's possible.

**Comment by jonbonazza** [comment]
@alekmlynek so if the plugin is intended to be on the asset store, it requires a certain folder structure (as seen in my version of the repo). I suppose theoretically, for the module you could also support this folder structure, as long as the Sconstruct file knew where to look for the files. I've never built a module, but possibly there is a flag we can put in the Sconstruct file to toggle gdnative or module. 

What do you think?

**Comment by aspenforest** [comment]
I also need SHA256 HMAC functionality in GDScript. With that mentioned, why not create a separate Crypto module with support for many different encryption algorithms?

**Comment by Calinou** [comment]
@aspenforest This is being worked on in https://github.com/godotengine/godot/pull/29871, however, SHA-256 HMAC hasn't been implemented yet.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by tavurth** [comment]
https://github.com/johngirvin/godot-ncrypt
