### ISSUE TITLE
keyboard shortcut

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#25921]
**Godot version:**
3.0, 3.1

**OS/device including version:**
all

**Issue description:**
I would like an editable and saveable keyboard shortcut list, accessible through the menu toolbar (https://github.com/godotengine/godot/issues/25918) as well as through a shortcut itself, similar to that of Aseprite, with is very thorough 
![asepritekeyboadshortcuts](https://user-images.githubusercontent.com/47016402/52884388-247f5900-316e-11e9-9fe0-90bd40186efc.png)

**Comment by akien-mga** [comment]
It's in the editor settings already.
