### ISSUE TITLE
What's the current status of Godot for blind and deafblind games.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#25930]
Hi, I wanna know what's the current status of Godot for blind and deafblind gamers, since I wanna develop games for such demographics.

I do understand there seem some MIDI capabilities already on godot, but from what I know is just the MIDI input and godot lacks MIDI output right now, or some kind of output.

I wanna know if there's some timeframe planned so godot can be used for procedural audio games.

Also, I wanna know what are Godot capabilities for gamepad vibration, if Godot support it and also if Godot support a way to give diferent pressures or force strenght regarding gamepad vibration.

Many thanks for your attention.

**Comment by groud** [comment]
This is not really the place to ask general questions, but to report bugs and ask for new features. Please use the other community channels for that (the #godotengine-devel channel is the place where most developers are).
