### ISSUE TITLE
Add warnings/errors filter to the Debugger output pane 

### ISSUE THREAD

**Issue by syskrank** [godotengine/godot#25937]
**Godot version:**
3.1+

**Issue description:**
It seems that for now we got the mixed debugger reports for warnings and errors altogether. 

When it comes to debugging a single specific aspect of the whole game this approach creates unwanted struggle for the user to find the concrete debugger error message, as the pane got flooded with warning messages like 'The argument X is never used' or 'The local variable Y is declared but never used'. 

By themselves these messages are very useful but sometimes it's a pain to scroll through them.

My suggestion is that we add filter buttons so that we will be able to show/hide warnings and/or errors , like it's done in many IDEs around. For example, Qt Creator has toggle button to show warnings in the "Issues" pane, and Visual Studio does that too.

Will be really handy to have this in Godot.

**Comment by KoBeWi** [comment]
Resolved in 4.0
