### ISSUE TITLE
Inaccurate documentation for randf

### ISSUE THREAD

**Issue by marningmol** [godotengine/godot#25938]
The documentation of randf() currently says:

`Returns a random floating point value between 0 and 1.`

This wording sounds like (0.0, 1.0) - I am assuming the function _actually_ returns [0.0, 1.0), as is normal for random float generation.

I suggest someone who can verify what exactly randf() returns updates the documentation to be more precise, i.e.

`Returns a random floating point value in the range [0.0, 1.0)`

**Comment by akien-mga** [comment]
For anything resulting of floating-point operations, it doesn't make much difference whether you include or exclude the bounds. In any case, you can't rely on the fact that the method would give you a round value.

**Comment by pbrunet** [comment]
I think this issue can be closed
