### ISSUE TITLE
String value autocomplete issue when typing without qoute

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#25947]
**Godot version:**
3.1 beta 4

**Issue description:**
When you start typing string value without quote, autocomplete list dissapearing after a second.

**Steps to reproduce:**
1. Type this line: 
`if Input.is_action_pressed(`
Result: you can see a list with string values for this function
2. Start typing **focus** (without opening quotes)
Result: for a second you can see list has been filtered, but then it is replaced with other values

![bug](https://user-images.githubusercontent.com/1552169/52902602-463b1780-3224-11e9-9e3b-1949bfb5e270.gif)

**Comment by KoBeWi** [comment]
Duplicate: https://github.com/godotengine/godot/issues/24077

**Comment by breakmt** [comment]
Sorry
