### ISSUE TITLE
Amiga Port linking problem

### ISSUE THREAD

**Issue by afxgroup** [godotengine/godot#25948]
I'm compiling AmigaOS4 version of Godot. I'm in the linking phase and i get this error

**core/libcore.amigaos4.opt.tools.a(variant.amigaos4.opt.tools.o):(.got2+0x598): undefined reference to `typeinfo for Node'

core/libcore.amigaos4.opt.tools.a(variant.amigaos4.opt.tools.o):(.got2+0x5a0): undefined reference to `typeinfo for Control'**

I've see the code and i don't see nothing strange in that class. It has (most probably) the two helpers that is causing the problem. They have no virtual methods i have to implement on AmigaOS.
So where could be the problem?

**Comment by akien-mga** [comment]
I'm not sure to understand. There's no AmigaOS4 port in this repository.

Is it a port that you're making yourself? It's hard to help without having access to the code (and it's outside the scope of this repository).

**Comment by afxgroup** [comment]
I would like to push the changes into the official branch (like Haiku did) but i would to make it run at least.. The changes are very minimal because i can reuse most of the unix part (except for the platform folder of course). And however this error is not amiga related. The variant.cpp file is generic and i made no changes on it. That's why i've asked here what could be the problem
I'm using gcc 8.2.0 to compile Godot. Could be this a problem?

**Comment by hpvb** [comment]
GCC 8.2.0 is the compiler used to do official releases so that should not be a problem.

**Comment by Calinou** [comment]
Closing, as this is outside the scope of this repository. Still, feel free to join `#godotengine-devel` on freenode IRC to discuss porting efforts :slightly_smiling_face:

**Comment by ksdhans** [comment]
I know this bug is closed, but here's the likely cause: 
https://stackoverflow.com/questions/11904519/c-what-are-the-causes-of-undefined-reference-to-typeinfo-for-class-name
