### ISSUE TITLE
Disabled CollisionShape2D still interacts with one way collision shapes

### ISSUE THREAD

**Issue by samdze** [godotengine/godot#25941]
**Godot version:**
Godot 3.1 Beta 4

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
A disabled CollisionShape2D child of a KinematicBody2D makes a call to `move_and_collide` return a collision with a one way collision body even if no collision should happen.
The bug is present in 3.1 Beta 4, but **it wasn't in 3.1 Alpha 2.**

**Steps to reproduce:**
This is the player scene view:
![godot_v3 1-beta4_win64_2019-02-16_14-59-38](https://user-images.githubusercontent.com/19392104/52900829-80dc8a00-31fb-11e9-855e-33a410d85790.png)
The gray rectangle in the middle, AlternativeShape2D, is a disabled rectangle, so it shouldn't interfere with collisions. The bigger one is CollisionShape2D.
When the player jumps but doesn't reach the top of the one way platform, he lands in the air:
![godot_v3 1-beta4_win64_2019-02-16_14-37-06](https://user-images.githubusercontent.com/19392104/52900802-1a576c00-31fb-11e9-96e1-94426d9ce6fd.png)![2019-02-16_15-02-44](https://user-images.githubusercontent.com/19392104/52900861-f8aab480-31fb-11e9-969c-4f8f3c239bde.gif)
While changing AlternativeShape2D's parent node the player behaves as expected::
![godot_v3 1-beta4_win64_2019-02-16_14-38-38](https://user-images.githubusercontent.com/19392104/52900863-03654980-31fc-11e9-9cab-7b5ce1868615.png)![2019-02-16_15-04-57](https://user-images.githubusercontent.com/19392104/52900881-49221200-31fc-11e9-8245-fb98143bcecf.gif)

**Minimal reproduction project:**
[disabled_collider_test.zip](https://github.com/godotengine/godot/files/2872007/disabled_collider_test.zip)

**Comment by reduz** [comment]
I dont understand the bug by just looking at it or testing it, but I fixed what seemed to be an inconsistency.
Can you give it a try and reopen if the problem persists?

**Comment by samdze** [comment]
The bug is fixed now, thanks!
