### ISSUE TITLE
Wrong or misleading "modified" status for scenes hierarchy.

### ISSUE THREAD

**Issue by syskrank** [godotengine/godot#25942]
**Godot version:**
3.1 custom build, [962c14278](https://github.com/godotengine/godot/commit/962c14278fafecf3d047fd070fc7ab8d4dcc21da)

**OS/device including version:**
Linux Mint 19 x64

**Issue description:**
Upon hitting Ctrl+S in the script editor to save the unchanged script, all dependent scenes are marked as "modified" in editor ( "star" symbols within the tabs )  
Especially this is noticeable when using inherited scenes with instanced scenes inside their parent.
See the attached example project.

**Steps to reproduce:**
1. Create 2-3 scenes with a new script each.
2. Create a new scene and instance one of the prior scenes inside ( for example, scene 2 ).
3. Create a new inherited scene from the latter.
4. Open up scene's 2 script, do not modify it, hit Ctrl-S.
5. Witness that the scene where scene 2 was instanced was marked as "modified"
6. Notice that the inherited scene also gets that same status.

Strangely enough, git diff doesn't show that .tscn files were actually modified.

**Minimal reproduction project:**
[tabs_test.zip](https://github.com/godotengine/godot/files/2872055/tabs_test.zip)

**Comment by KoBeWi** [comment]
I noticed similar bug and it might be the same thing. When I change scene tab to some complex scene containing some instanced scenes, it will randomly trigger some background work and get marked as modified. It happens since 3.1 beta3 or beta2.

**Comment by akien-mga** [comment]
Likely related to 9e85d17. It introduced #23791 which was fixed by #23812. There might still be cases where it's still not working as it should.

CC @reduz @YeldhamDev
