### ISSUE TITLE
Popup Menu children

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#2595]
If you create a scene and make the first node a popup menu and move the menu before adding children, It will automatically click the popup menu when you try to click on the children of the node.

In godot stable 1.1

**Comment by firefly2442** [comment]
I tested this with the current development master branch (aad2bbdb6fb7c8217d7e75480b38e45f00cb3abd) and I wasn't able to click on the child node.  It did nothing.  I could click on the parent popup menu node however.

If you reverse it and have a button node as the root and then add a popup menu as the child, I wasn't able to select or move the popup menu.
