### ISSUE TITLE
Add a multi-line text editor for exported strings

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#25956]
**Godot version:**
3.1 beta 4

**Issue description:**
Editing exported strings is very uncomfortable when you want to use them as multi-line text because new lines can only be added by copying text from an external text editor.

My suggestion is to add a button to the right side of the line edit that opens a window where you can edit mult-line text.

**Comment by akien-mga** [comment]
You can already use `export(String, MULTILINE) var text` for that, see https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#exports

**Comment by MightyPrinny** [comment]
> You can already use `export(String, MULTILINE) var text` for that, see https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#exports

Is this possible in C#? this is not mentioned in https://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_differences.html#other-differences

**Comment by somnivore** [comment]
`[Export(PropertyHint.MultilineText)]` should be the C# variation

**Comment by akien-mga** [comment]
It would be good to enhance the C# docs linked accordingly, it's quite terse currently on how options are available for `[Export]`.

**Comment by MightyPrinny** [comment]
> `[Export(PropertyHint.MultilineText)]` should be the C# variation

Thank you so much.
