### ISSUE TITLE
How to register a property of type material? (GDNative with C++)

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#25951]
**Godot version:** 3.1.beta3.mono.official

**OS/device including version:** Linux 64b

**Issue description:**

I can't change a property (registered from C++ via GDNative) of type material in the inspector. It shows `[null]` and cannot be clicked on or modified in any way.

I suspect this is not a bug, I am probably just using it wrongly. I tried to find documentation for it, but didn't really find anything. "docs" in C++ bindings repo page redirects to a wiki with engine compilation (???), other than this I only found that simple example in docs and that was all...

**Steps to reproduce:**
I have a field in a class:

    Material *mat;

And this property registration:

    register_property<CPP, Material*>("mat", &CPP::mat, nullptr);

This compiles, but leads to a broken property in the inspector.

**Comment by mnn** [comment]
Looked at engine sources and tried to replicate how it is being added internally.

```cpp
  register_property<CPP, Ref<Material>>("material", &CPP::set_material, &CPP::get_material,
                                        Ref<Material>(nullptr),
                                        GODOT_METHOD_RPC_MODE_DISABLED, GODOT_PROPERTY_USAGE_DEFAULT,
                                        GODOT_PROPERTY_HINT_RESOURCE_TYPE,
                                        "SpatialMaterial,ShaderMaterial");

void CPP::set_material(Ref<Material> mat) { material = mat; }

Ref<Material> CPP::get_material() { return material; }
```
```cpp
    Ref<Material> material;
```
Unfortunately it behaves the same (code compiles, but in the editor nothing can be done with the property).

I also tried many variations (e.g. field being just `Material` = compile error, initializing to a new instance of material class = editor crash). I would appreciate some tip, example, link to relevant source file(s), anything.

PS: I am very green in C++ (didn't use it since I learned basics at school, I have been studying it for last week, but still much to cover), so I am sorry if this is some triviality...

**Comment by UgisBrekis** [comment]
I'm having the same issue with Godot 3.1 stable NativeScript 1.1
I tested int, float and NodePath and these show up correctly in the inspector, however anything that inherits Reference simply shows [null] without the ability to set it from the Inspector.

**Comment by mnn** [comment]
Try this -> https://github.com/GodotNativeTools/godot-cpp/issues/237#issuecomment-465170294 :wink:

**Comment by clayjohn** [comment]
@mnn Is your question solved by https://github.com/GodotNativeTools/godot-cpp/issues/237#issuecomment-465170294? And if so, can we close this issue?

**Comment by mnn** [comment]
Yes, it is solved. I am sorry, totally forgot to close it here. :no_mouth:
