### ISSUE TITLE
Wrong unreachable warning after returning from match's wildcard pattern

### ISSUE THREAD

**Issue by luizcarlos1405** [godotengine/godot#25955]
**Godot version:**
3.1 beta 4

**OS/device including version:**
Linux 18.04

**Issue description:**
If you use return in a `_:` pattern of a match Godot thinks code after the `match` is unreachable.

![image](https://user-images.githubusercontent.com/15899938/52905301-2a7d4480-3217-11e9-8bc4-d07938ce8c0a.png)

Output:
```
here
unreacheble?
```

**Steps to reproduce:**
A script with:

``` gdscript
extends Node

var value = "test"

func _ready():
	match value:
		"test":
			print("here")
		_:
			print('test')
			return
	
	print('unreacheble?')
```

**Minimal reproduction project:**
[False unreachable warning.zip](https://github.com/godotengine/godot/files/2872387/False.unreachable.warning.zip)

**Comment by LinuxUserGD** [comment]
I think "here" and "test" gets overwritten by "unreacheble".

**Comment by volzhs** [comment]
another example code
```gdscript
func test():
	for i in 10:
		if true:
			continue
		return 0
	return 1  # Unreachable code (statement after return) in function 'test()'.
```

**Comment by danielspaniol** [comment]
> ```gdscript
> func test():
> 	for i in 10:
> 		if true:
> 			continue
> 		return 0
> 	return 1  # Unreachable code (statement after return) in function 'test()'.
> ```

I am not sure if that needs to be supported.
I mean `if true` is a special case that could be implemented, but recognizing that such code does not return is generally undecidable. And every "real life code" will not have the constant `true` there.

**Comment by volzhs** [comment]
I just put `true` for making it simple.
that condition could be `true` in some cases.
i have same warning when i change `true` to `is_available()`
