### ISSUE TITLE
Can't Press TextureButtons with Negative Scale

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#2596]
If you have a TextureButton with a scale whose x or y contains a negative value, you can't click on it.

To demonstrate this, take an empty project, create two TextureButtons, one named "Normal" and the other named "Flipped". Set their Normal texture to whatever you'd like (I used the default icon.png for both), then add the following code to the scene:

    func _ready():
        get_node("Normal").connect("pressed", self, "button_pressed")
        get_node("Flipped").set_scale(Vector2(1, -1))
        get_node("Flipped").connect("pressed", self, "button_pressed")

    func button_pressed():
        print("A button was pressed.")

The print statement will happen for the Normal button but not for the Flipped button. This seems to happen regardless of whether the scale was set in the editor or via code, as long as at least one of the values is negative. Things work fine with arbitrary positive values.

**Comment by akien-mga** [comment]
Confirmed in the current master branch.

**Comment by reduz** [comment]
For the record, this method has been renamed to TextureButton.set_texture_scale(), as all GUI components now can have scale

**Comment by reduz** [comment]
Fixed (but referenced wrong issue in commit)

**Comment by akien-mga** [comment]
So fixed by 0c6a4b47.
