### ISSUE TITLE
KinematicBody2D issue with RayShape2D

### ISSUE THREAD

**Issue by piratesephiroth** [godotengine/godot#25968]
**Godot version:** 

3.1 beta 81e1535

**OS/device including version:** 

Windows 10 x64

**Issue description:**

1. All RayShape2Ds that belong to the same KinematicBody2D share the same length. You modify one and it affects all of them,

2. If the KinematicBody2D has multiple RayShape2Ds pointing down and 2 of them touch the floor at the same time, we get this weird effect:
![weird](https://i.imgur.com/pYka46I.gif)

3. If the KinematicBody2D has rotated RayShape2D(s) pointing up and moves upward, they sink into ceilings then slowly slide out.
![weird2](https://i.imgur.com/6Wtviis.gif)

**Steps to reproduce:**
1. Create a KinematicBody2D
2. Add two or more CollisionShape2D nodes as children of the body with the RayShape2D shape, rotating some of them to point up and modifying their properties as well.

3. Run the project

**Minimal reproduction project:**

[rayshape2dbug.zip](https://github.com/godotengine/godot/files/2872875/rayshape2dbug.zip)

**Comment by bruvzg** [comment]
> All RayShape2Ds that belong to the same KinematicBody2D share the same length. You modify one and it affects all of them

If you are duplication CollisionShape2D you have to right click on a shape and select `Make Unique` otherwise it's just reference to the original CollisionShape2D shape.

**Comment by piratesephiroth** [comment]
>If you are duplication CollisionShape2D you have to right click on a shape and select `Make Unique` otherwise it's just reference to the original CollisionShape2D shape.

I see. Weird that the other propertied are allowed to be unique though.
