### ISSUE TITLE
Area2D Collision disabled, can't be enabled inside of a signal

### ISSUE THREAD

**Issue by juancolacelli** [godotengine/godot#25973]
**Godot version:**
v3.1.beta4.official

**OS/device including version:**
macOS Mojave 10.14.3

**Issue description:**
When you disable an Area2D's collision you can't enable it inside of another node signal.

**Steps to reproduce:**
- Create an Area2D ("Goal") with CollisionShape2D
- Disable CollisionShape2D Collision
- Connect the signal body_entered and put a print inside of it
- Create another Area2D ("Toggler") with CollisionShape2D
- Connect the signal body_entered and enable the "Goal" Collision inside of it
- Create a KinematicBody2D ("Player") with CollisionShape2D
- Make the "Player" pass through the "Toggler", "Goal" will look like it's enabled but if the "Player" pass through it, it will not print anything

**Minimal reproduction project:**

[area_2d_collision_bug.zip](https://github.com/godotengine/godot/files/2873009/area_2d_collision_bug.zip)

**Comment by KoBeWi** [comment]
In 3.2, doing this results in error. You are supposed to defer setting this (e.g. `set_deferred("disabled", false)`)
