### ISSUE TITLE
Mesh and UV crease becomes visible at certain angles

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#25976]
**Godot version:**
`master` / 869887641f3d

**OS/device including version:**
Manjaro Linux 18.2

**Issue description:**
I have a character model in Blender 2.8 which consists of separate head and body meshes. I used a data transfer modifier to make sure the normals are consistent at the seam so it's looks perfectly fine in Blender and also in Substance after I export it in .obj.

However, if I export it using the Godot Blender exporter, creases between the meshes and also UV seams become visible at certain angles, especially when I zoom out the view.

This is how it looks normally:
![image](https://user-images.githubusercontent.com/2367032/52914861-b32bdb80-3310-11e9-84c8-6cc6dbb88d54.png)

And this is how it looks when zoomed out (the vertical line is an UV seam, whle the horizontal one is a crease between the meshes): 
![image](https://user-images.githubusercontent.com/2367032/52914876-d9ea1200-3310-11e9-9d6c-8c61159fc2d3.png)

I'm not too sure if it is an engine problem or a bug in the exporter code. So I'll just report it here for now.

**Comment by CptPotato** [comment]
This is probably a mipmapping related issue. It can be worked around to some degree by adding additional texture padding around the seams.

**Comment by clayjohn** [comment]
Yes. Cptpotato is correct. This is an issue with mipmapping your texture. You'll need padding around the seems.
