### ISSUE TITLE
html5 export not working

### ISSUE THREAD

**Issue by unicomp21** [godotengine/godot#25978]
**Godot version:**
godot, 3.1, beta4, windows and linux versions

**OS/device including version:**
win10, and ubuntu 18

**Issue description:**
Even after downloading, html5 template reports missing deps

**Steps to reproduce:**
menu->project->export->html5, download template deps -> template deps still missing

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Are you using the Mono build? It does not support HTML5 yet.

**Comment by unicomp21** [comment]
Thanks, I'm using the mono build.  Any idea when it'll work for html5?

**Comment by akien-mga** [comment]
See #20270. There's no ETA for it yet, the focus is on Android for now.
