### ISSUE TITLE
Custom theme doesn't show in editor unless assigned element by element

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#25987]
**Godot version:** 3.0.6 and 3.1 beta5

**OS/device including version:** Windows 8

**Issue description:**
When I create a Custom theme for my project, and have elements with no theme assigned, they show up in the editor as using the default theme. (They correctly render in-game with the custom theme applied.)

**Steps to reproduce:**
- Create a new project
- Create an element like a button, panel, or window dialog
- Add a new custom theme to it
- Change some stuff, like the default font, or panel background to an image
- Save the custom theme to disk
- Clear the custom theme from the element
- Edit your project settings and apply the custom theme

View the element in-editor. It looks like it has the default theme applied:
![image](https://user-images.githubusercontent.com/31222662/52919077-7211d800-32cc-11e9-8a5d-6a9a14effbd2.png)

Run the game. The custom theme appears correctly:
![image](https://user-images.githubusercontent.com/31222662/52919083-7a6a1300-32cc-11e9-8462-d208bb4bd6b8.png)

The editor should also render the custom theme.

MVPs:
- Godot 3.1 beta 5: [ThemeTest-3.1b5.zip](https://github.com/godotengine/godot/files/2873409/ThemeTest-3.1b5.zip)
- Godot 3.0.6: [GlobalTheme.zip](https://github.com/godotengine/godot/files/2873523/GlobalTheme.zip)

Strangely enough, restarting the editor seems to fix this.

**Comment by nightblade9** [comment]
The current work-around for this appears to be: apply the custom theme and font to every individual element. It's ugly and inefficient, but it works.

**Comment by Calinou** [comment]
Try applying the theme to the root Control node instead of setting it in the Project Settings.

**Comment by nightblade9** [comment]
@Calinou how can I do that? Can you provide some sort of instructions/screenshots/GIF/something?

**Comment by Calinou** [comment]
@nightblade9 Just select the root Control node and apply a Theme resource to it:

![Inspector](https://user-images.githubusercontent.com/180032/55267973-316f8c00-5286-11e9-9c06-a6bd8456de10.png)

**Comment by nightblade9** [comment]
@Calinou ah, I see. So then, I have to apply it scene by scene? I was hoping global themes would avoid that.

Anyway, I'm going to close this bug. It's not reproducible any more (even for me), and I suspect it was related to me not restarting Godot, which seems to be a good work-around for theme-related shenanigans. At any rate, it's for 3.0.6, and likely won't be fixed now.
