### ISSUE TITLE
No node description in 3.1 beta 5

### ISSUE THREAD

**Issue by rodolforg** [godotengine/godot#25981]
In Create New Node dialog, there is a label with text (node) "Description:", but it isn't showing description text for any node.
I saw it in 3.1 beta 5, but I don't know if it came earlier.

**Comment by eon-s** [comment]
Likely duplicate of #25820 

Remember to fill the templates when you open an issue.

**Comment by akien-mga** [comment]
Indeed, duplicate of #25820.
