### ISSUE TITLE
Error when building godot sharp solution 3.1 beta 5

### ISSUE THREAD

**Issue by MaGaRCaN** [godotengine/godot#25982]
**Godot version:**

Godot 3.1 beta 5

**OS/device including version:**

Windows 10 64 bits. GTX 1060 6GB

**Issue description:**

Godot breaks trying to build solution

**Steps to reproduce:**
Create node.
Add a new script.
Choose C#.
Godot breaks building Godot Sharp solution.

**Minimal reproduction project:**

**Comment by neikeq** [comment]
I cannot reproduce on WIndows 10 64 bits with beta 5. Can you paste here the command line output (and backtrace if it crashes)?

**Comment by MaGaRCaN** [comment]
> C:\Users\Manu\Downloads\Godot_v3.1-beta mono>Godot_v3.1-beta5_mono_win64.exe
> OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2
> Editing project: C:/Users/Manu/Documents/GODOT/sim (C:::Users::Manu::Documents::GODOT::sim)
> 
> C:\Users\Manu\Downloads\Godot_v3.1-beta mono>OpenGL ES 2.0 Renderer: GeForce GTX 1060/PCIe/SSE2
> fixed path: C:/Users/Manu/Documents/GODOT/sim/.import
> unit: C:\
> 
> [main 2019-02-20T21:29:58.085Z] update#setState idle
> ERROR: godot_icall_BuildInstance_get_MSBuildPath: Cannot find executable for 'MSBuild (Mono)'. Tried with path: msbuild.bat
>    At: modules/mono/editor/godotsharp_builds.cpp:119
> 
> Unhandled Exception:
> System.IO.FileNotFoundException: Cannot find the MSBuild executable.
>   at GodotSharpTools.Build.BuildInstance.GetMSBuildPath () [0x00013] in <4db47f98861f48088d72cf0c153a64ac>:0
>   at GodotSharpTools.Build.BuildInstance.Build (System.String loggerAssemblyPath, System.String loggerOutputDir, System.String[] customProperties) [0x0001e] in <4db47f98861f48088d72cf0c153a64ac>:0

**Comment by neikeq** [comment]
Do you have MSBuild installed (either from Visual Studio or Visual Studio Build Tools)?

**Comment by MightyPrinny** [comment]
if you installed mono try adding it to your path and change the build tool to mono in your editor settings or install visual studio build tools, after that you might get an error if you don't have at least the .net framework 4.5 targeting pack

**Comment by akien-mga** [comment]
It doesn't seem to crash, only throws an error. Apparently you indeed don't have MSBuild installed or accessible to Godot. Make sure that you have it installed from Visual Studio or Visual Studio Build Tools, and it should work.

**Comment by Mrxx99** [comment]
@akien-mga I do have the same issue as described here and I do definitively have Visual Studio installed (both Visual Studio 2015 enterprise and Visual Studio 2017 enterprise) with godot 3.1 stable (64 bit mono version) on Windows 10 (64 bit)
