### ISSUE TITLE
export setter not working

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#25991]
**Godot version:**
3.1 beta 4

**OS/device including version:**
Windows

**Issue description:**
My setter for my exported value isn't being triggered.

![image](https://user-images.githubusercontent.com/21234930/52920186-bdbd8500-32be-11e9-876d-507a6c017b8d.png)

![image](https://user-images.githubusercontent.com/21234930/52920196-ce6dfb00-32be-11e9-969a-5bad14c668a4.png)

**Comment by Zylann** [comment]
Script code will not execute in the editor by default. You need to mark the script as `tool`.

**Comment by clayjohn** [comment]
Zylann's comment is correct. Closing.
