### ISSUE TITLE
Cannot close game window when having a panel on it

### ISSUE THREAD

**Issue by AinaSG** [godotengine/godot#25993]
**Godot version:**

Can reproduce in beta5 and beta4, not happening in beta3

**OS/device including version:**

Linux Mint Debian Edition

**Issue description:**

When having a panel in a scene, closing the window using the (x) button, causes Godot to disconnect from it but not close it. Then the window remains unresponsive. 
It does not happen if you don't move the panel from it's default position

**Steps to reproduce:**
1- Create a scene with a root node (Tested with both Node and Node2D)
2- Add a Panel (Control)
3- Move the panel (for some reason, I noticed it's not happening if the panel is at it's parent position)
3- Play the scene
4- Close the window using the (x) button
Here Godot disconnects from the scene, the game does not close and stays unresponsive.

**Minimal reproduction project:**

[Panel.zip](https://github.com/godotengine/godot/files/2873592/Panel.zip)

**Comment by AinaSG** [comment]
Can't reproduce in OSX. It might be a System problem, but as it's happening in beta4 and 5 but not in beta3, I guessed something changed in between.

**Comment by bojidar-bg** [comment]
Can't reproduce, Arch Linux, KDE.

Can you try to get a backtrace using gdb (and just pressing CTRL-C after it freezes)?

**Comment by akien-mga** [comment]
Can't reproduce either with 3.1 beta 5 on Mageia 7 x86_64, KDE. Nor with a build from the master branch.

**Comment by AinaSG** [comment]
It's probably a system problem. I noticed that the only thing is that it takes about 4 minutes to close instead of not closing at all.
