### ISSUE TITLE
Light2D/LightOccluder2D broken after beta5 update

### ISSUE THREAD

**Issue by martys71** [godotengine/godot#25996]
**Godot version:**
3.1 beta5

**OS/device including version:**
Wi10 x64

**Issue description:**
After the beta5 upgrade, the shadows went crazy. Please see the picture:
https://ibb.co/34WZj0X

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by martys71** [comment]
The lshades look as if they were turned by -90 degrees.

**Comment by volzhs** [comment]
you can attach image directly on github issue though... :)

**Comment by clayjohn** [comment]
Could you provide more information about what you did to get those results? I am having trouble reproducing any issues.

**Comment by JFonS** [comment]
@martys71 Are you using a light shader to modify LIGH_VEC by any chance?

**Comment by martys71** [comment]
@clayjohn: please see this project: https://github.com/DiscoveringGodot/4_Heist_Meisters/tree/5dfb43013cad82f7b21de2b811cb5fd78f279b54  
Scenes/Levels/Level1

**Comment by JFonS** [comment]
Regression from  #25779. I now remember why I changed  `LIGHT_VEC` to not affect shadows... it makes no sense **and** it breaks with rotated lights. 

I just put together a hack to allow both rotated lights and changing shadows with `LIGHT_VEC` but I still think we should not let `LIGHT_VEC` affect shadows...
