### ISSUE TITLE
Build failure on Gentoo Linux (x86_64)

### ISSUE THREAD

**Issue by captain-graubart** [godotengine/godot#26]
godot $ scons bin/godot
scons: Reading SConscript files ...
sh: i586-mingw32msvc-gcc: command not found
Detected Platforms: ['server', 'x11']
Detected Modules: ['gridmap']
open path: platform/windows/logo.png
open path: platform/android/logo.png
open path: platform/javascript/logo.png
open path: platform/server/logo.png
open path: platform/iphone/logo.png
open path: platform/osx/logo.png
open path: platform/bb10/logo.png
open path: platform/nacl/logo.png
open path: platform/x11/logo.png

scons: warning: The Options class is deprecated; use the Variables class instead.
File "/mnt/data/development/external/godot/SConstruct", line 90, in <module>
V: no

scons: warning: Two different environments were specified for target method_bind.inc,
        but they appear to have the same action: run(target, source, env)
File "/mnt/data/development/external/godot/core/SCsub", line 28, in <module>
V: no
scons: done reading SConscript files.
scons: Building targets ...
g++ -o main/main.o -c -g2 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DOPENGL_ENABLED -DGLEW_ENABLED -DALSA_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DGLES1_ENABLED -DGLES_OVER_GL -DMUSEPACK_ENABLED -DOLD_SCENE_FORMAT_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DTHEORA_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/x11 -I/usr/include/freetype2 -Imain/vorbis main/main.cpp
In file included from ./core/io/unzip.h:55:0,
                 from ./core/io/file_access_zip.h:36,
                 from main/main.cpp:75:
./core/io/ioapi.h:126:51: error: expected initializer before 'OF'
./core/io/ioapi.h:127:51: error: expected initializer before 'OF'
./core/io/ioapi.h:128:51: error: expected initializer before 'OF'
./core/io/ioapi.h:129:51: error: expected initializer before 'OF'
./core/io/ioapi.h:130:51: error: expected initializer before 'OF'
./core/io/ioapi.h:132:51: error: expected initializer before 'OF'
./core/io/ioapi.h:133:51: error: expected initializer before 'OF'
./core/io/ioapi.h:139:5: error: 'open_file_func' does not name a type
./core/io/ioapi.h:140:5: error: 'read_file_func' does not name a type
./core/io/ioapi.h:141:5: error: 'write_file_func' does not name a type
./core/io/ioapi.h:142:5: error: 'tell_file_func' does not name a type
./core/io/ioapi.h:143:5: error: 'seek_file_func' does not name a type
./core/io/ioapi.h:144:5: error: 'close_file_func' does not name a type
./core/io/ioapi.h:145:5: error: 'testerror_file_func' does not name a type
./core/io/ioapi.h:149:51: error: expected initializer before 'OF'
./core/io/ioapi.h:150:51: error: expected initializer before 'OF'
./core/io/ioapi.h:151:51: error: expected initializer before 'OF'
./core/io/ioapi.h:155:5: error: 'open64_file_func' does not name a type
./core/io/ioapi.h:156:5: error: 'read_file_func' does not name a type
./core/io/ioapi.h:157:5: error: 'write_file_func' does not name a type
./core/io/ioapi.h:158:5: error: 'tell64_file_func' does not name a type
./core/io/ioapi.h:159:5: error: 'seek64_file_func' does not name a type
./core/io/ioapi.h:160:5: error: 'close_file_func' does not name a type
./core/io/ioapi.h:161:5: error: 'testerror_file_func' does not name a type
./core/io/ioapi.h:165:28: error: expected initializer before 'OF'
./core/io/ioapi.h:166:26: error: expected initializer before 'OF'
./core/io/ioapi.h:172:5: error: 'open_file_func' does not name a type
./core/io/ioapi.h:173:5: error: 'tell_file_func' does not name a type
./core/io/ioapi.h:174:5: error: 'seek_file_func' does not name a type
./core/io/ioapi.h:185:21: error: expected initializer before 'OF'
./core/io/ioapi.h:186:22: error: expected initializer before 'OF'
./core/io/ioapi.h:187:23: error: expected initializer before 'OF'
In file included from ./core/io/file_access_zip.h:36:0,
                 from main/main.cpp:75:
./core/io/unzip.h:153:45: error: expected initializer before 'OF'
./core/io/unzip.h:166:32: error: expected initializer before 'OF'
./core/io/unzip.h:167:34: error: expected initializer before 'OF'
./core/io/unzip.h:184:33: error: expected initializer before 'OF'
./core/io/unzip.h:191:36: error: expected initializer before 'OF'
./core/io/unzip.h:198:29: error: expected initializer before 'OF'
./core/io/unzip.h:208:37: error: expected initializer before 'OF'
./core/io/unzip.h:211:39: error: expected initializer before 'OF'
./core/io/unzip.h:219:40: error: expected initializer before 'OF'
./core/io/unzip.h:232:37: error: expected initializer before 'OF'
./core/io/unzip.h:238:36: error: expected initializer before 'OF'
./core/io/unzip.h:245:34: error: expected initializer before 'OF'
./core/io/unzip.h:291:44: error: expected initializer before 'OF'
./core/io/unzip.h:300:42: error: expected initializer before 'OF'
./core/io/unzip.h:324:55: error: expected initializer before 'OF'
./core/io/unzip.h:334:39: error: expected initializer before 'OF'
./core/io/unzip.h:340:47: error: expected initializer before 'OF'
./core/io/unzip.h:348:40: error: expected initializer before 'OF'
./core/io/unzip.h:361:40: error: expected initializer before 'OF'
./core/io/unzip.h:376:40: error: expected initializer before 'OF'
./core/io/unzip.h:382:39: error: expected initializer before 'OF'
./core/io/unzip.h:401:32: error: expected initializer before 'OF'
./core/io/unzip.h:403:35: error: expected initializer before 'OF'
./core/io/unzip.h:408:27: error: expected initializer before 'OF'
./core/io/unzip.h:413:42: error: expected initializer before 'OF'
scons: *** [main/main.o] Error 1
scons: building terminated because of errors.

- scons v2.3.0
- python v2.7.5

**Comment by Evi1M4chine** [comment]
Just as an info: Godot compiles perfectly fine on Gentoo (amd64) nowadays.
I’ve successfully done Linux, Android and Javascript* builds (debug & release).
So I don’t think this bug is needed anymore.

The integrated libraries are not welcome on Gentoo, and would have to be removed in the ebuild [Gentoo install script], for it to have a chance of becoming integrated in to the package repository. (This is already done with Mozilla software, where it can be turned on with USE flags.)

But generally, everything is fine.

\___
\* JS is of course still broken, but that’s another story. :)

**Comment by akien-mga** [comment]
This issue is old, and apparently fixed judging by the last comment, so archiving it.
