### ISSUE TITLE
Light2D in ParallaxBackground

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#2600]
I set up Light2D in ParallaxBackground.

![light_setup](https://cloud.githubusercontent.com/assets/8281454/10425167/5869e1b2-7110-11e5-9ed9-4331716f59af.jpg)

when playing, light is off before scrolling to the first place in editor.

![light_result](https://cloud.githubusercontent.com/assets/8281454/10425183/7528cd54-7110-11e5-8ca4-2adb3add107c.jpg)

Here is sample project.
https://drive.google.com/file/d/0ByuhCIzeus36andGX3NhT205eFE/view?usp=sharing

**Comment by Ovnuniarchos** [comment]
It seems that the particle system is duplicated by the mirroring of ParallaxLayer, but the Light2D isn't.

**Comment by reduz** [comment]
This is unfortunately not a bug but a design limitaton of what can be done with a 2D lighting system, I can't really see any way to fix this without incurring into performance penalties. Parallax mirroring only mirrors stuff being drawn, but not lights :(

If the light is outside the parallax layer, it should work fine with it.

I suggest these specific situations, use a sprite in additive blend mode to emulate the effect of a light, this should help you achieve the same effect

**Comment by reduz** [comment]
Oh, another way to fix it is manually duplicating the light on that layer to where it mirrors
