### ISSUE TITLE
Focusing the root node of the main scene when opening project is not working

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#26006]
**Godot version:**
3.1 beta 5

**Issue description:**
Start godot and open project

**Result**: root node is not focused 
![52712320-47aadc80-2fa5-11e9-9a4c-97dde042f026](https://user-images.githubusercontent.com/1552169/52937983-8bb92b00-3371-11e9-9c5e-7d756d76438b.png)

**Expected**: root node is focused, user can see properties in inspector

Related to #25609

**Comment by QbieShay** [comment]
@breakmt since @JFonS  plans to rework the way selection works soon, I'll be waiting for that change before debugging any further. I tried but so far I failed.

**Comment by JFonS** [comment]
@QbieShay I will self-assign this issue to keep it in mind when I finally get to do the rework.

**Comment by JFonS** [comment]
Moving to 4.0 since I won't be able to rework this before 3.2

**Comment by KoBeWi** [comment]
Still valid in 93b107a
Although this is not really a bug. No node selected is a valid state. This also happens when you open a new scene btw.

**Comment by KoBeWi** [comment]
Seems already fixed in 4.0.
