### ISSUE TITLE
Painting and erasing should be disabled on hidden tilemap

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#2601]
To prevent accidentally changing hidden tilemap, painting and erasing should be disabled when hidden.

**Comment by jackmakesthings** [comment]
+1, couldn't agree more! It'd also be cool if you could lock tilemaps (and other nodes) from accidental editing without having to hide them, particularly if you could do it from the scene tree panel, in the same way you can toggle visibility there.
