### ISSUE TITLE
No way to know who handled mouse click

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#26019]
**Godot version:**
629ac20a

**Issue description:**
When interfaces gets complex, it might happen that something is preventing the mouse click to reach a certain elements (In my case, empty control nodes, see #24083). This makes debugging your interface a blind trial and error process.

**Proposal:**
@reduz proposed to have a signal on the viewport for when an event is handled, making it possible to debug what is happening to the mouse clicks.

**Comment by volzhs** [comment]
isn't this enough for you?
![screenshot_20190219_001318](https://user-images.githubusercontent.com/8281454/52960116-64974380-33db-11e9-9368-d8f855f52da5.png)

**Comment by QbieShay** [comment]
Uhm, what is that?

**Comment by Calinou** [comment]
As @volzhs said, the Debugger panel's Misc tab has a **Clicked Control** field which is updated every time you click a Control in the running project.

**Comment by QbieShay** [comment]
Ooooh amazing, thanks!

**Comment by QbieShay** [comment]
Boop to @Zylann since you had a similar problem!
