### ISSUE TITLE
Create New Node search inaccurate

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#26010]
**Godot version:**

d9cf780a702b6776cc10eb5b9a2c943a76decd7e

**OS/device including version:**

Arch Linux

**Issue description:**

The search bar in the Create New Node dialogue has some odd predictions sometimes:

![image](https://user-images.githubusercontent.com/28724859/52945471-68718a00-3337-11e9-8b03-f7a2e748ae84.png)
Expected: DampedSpringJoint2D
Predicted: AudioStreamPlayer2D

![image](https://user-images.githubusercontent.com/28724859/52945506-7c1cf080-3337-11e9-8c7a-20ee31fe5d1d.png)
Expected: CanvasLayer
Predicted: CanvasModulate

![image](https://user-images.githubusercontent.com/28724859/52945542-91921a80-3337-11e9-8285-51bbdf6112df.png)
Expected: Button
Predicted: TouchScreenButton

![image](https://user-images.githubusercontent.com/28724859/52945674-e6359580-3337-11e9-92fd-8965ff2b19dd.png)
Expected: Tabs, or TabContainer
Predicted: VisibilityEnabler2D

![image](https://user-images.githubusercontent.com/28724859/52945784-209f3280-3338-11e9-99da-f013c90c2fe3.png)
Expected: Particles, Particles2D
Predicted: VSeparator

![image](https://user-images.githubusercontent.com/28724859/52945842-4af0f000-3338-11e9-911e-d27ae0fa6cbf.png)
Expected: NinePatchRect
Predicted: TabContainer

![image](https://user-images.githubusercontent.com/28724859/52946666-24cc4f80-333a-11e9-93df-96f2cb972d2f.png)
Expected: VisibilityNotifier/2D
Predicted: VisibilityEnabler2D

![image](https://user-images.githubusercontent.com/28724859/52947077-585ba980-333b-11e9-8c81-afd4b89d6e4f.png)
Expected: HScrollBar
Predicted: TouchScreenButton

And so on.  It's usually not a problem, but if you're going fast and not paying attention, you might accidentally get the wrong node added and have to backtrack; if you are paying attention, you wind up having to type in extra characters to get the node you're really looking for.  One would expect, when typing in a particular string, that you'd get the node whose name most closely matches it starting from the beginning, but instead the predictor seems to try to find a match anywhere in the name and returns the first thing it finds that contains all the characters provided; I also assume it favors nodes which match the root node of the scene, though it's common to combine different kinds of nodes together (such as a UI in a 2D scene.)  I think it would be better if the predictor stuck more closely to matching the search criteria from start to end before trying to find other matches.

**Comment by Zireael07** [comment]
The Button -> TouchScreenButton thing has already been reported, but this is a broader report. I suppose we should close the other one?
