### ISSUE TITLE
Android GLES3 doesn't clear depth buffer

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#26012]
**Godot version:**
Commit 4e0eb752c2bfd7aac05023af67cd368061012bab

**OS/device including version:**
Xiaomi Pocophone F1 (https://en.wikipedia.org/wiki/Xiaomi_Pocophone_F1), looks like its running an Adreno 630 GPU

**Issue description:**
Alright, surprised to find out GLES3 is working on this phone :)
Renders find until you start to move/animate 3D objects, looks like it is not clearing the depth buffer after each frame and drawing black where the object is now behind its previous position.
Haven't figured out yet how to take a screenshot on this phone...

**Steps to reproduce:**
Create a simple 3D scene, add a camera, add a cube, add some logic to rotate the cube

**Minimal reproduction project:**
[test_android.zip](https://github.com/godotengine/godot/files/2875442/test_android.zip)

**Comment by BastiaanOlij** [comment]
@akien-mga this could be a regression related to the changes we did for iOS.

**Comment by BastiaanOlij** [comment]
Note that the test project runs fine on GLES2

**Comment by volzhs** [comment]
probably it's related with #25994
because the depth prepass is off on mobile for default. so it's same condition.

**Comment by noidexe** [comment]
@BastiaanOlij does it look like this? https://streamable.com/3ijyp
This is on Android using Calinou's build from d9cf780 on a SAMSUNG SM-T825(Adreno 530). Same issue on a Motorola XT1572 ( Adreno 418). 

Works fine exporting with 3.1-beta4

**Comment by volzhs** [comment]
@noidexe looks same with #25994
you can see it on desktop too if you disable depth prepass on project setting.

**Comment by BastiaanOlij** [comment]
@noidexe that is indeed the issue :)

it makes sense it still worked in beta-4, I think this is a result from the fixes we applied iOS bringing this issue to light 

@volzhs that makes sense, part of what was fixed was the fact that on mobile GPUs depth prepass is turned off. Wonder through why iOS isn't suffering the same fate now that it also have depth prepass turned off. Or maybe it will also fail on iOS but wasn't introduced yet the last time I tested. Might give it another go tonight.

**Comment by akien-mga** [comment]
Is this fixed by 8fd2eb6?

**Comment by noidexe** [comment]
I've just tested it in the editor and on some Android devices and it seems it's fixed now.

**Comment by akien-mga** [comment]
Thanks!

**Comment by BastiaanOlij** [comment]
Works fine for me now too :)
