### ISSUE TITLE
getornull condition return __null spam console window?

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#26016]
**Godot version:**
Godot 3.1 Beta 5

**OS/device including version:**
Windows 10

i get this error when i open my project in beta 5
(This only happend one time, second time i open the project the error is gone?)

![error](https://user-images.githubusercontent.com/13393087/52955311-a0ef8300-338c-11e9-9ce9-68b573cbb1db.PNG)

**Comment by Chaosus** [comment]
Did you changed font ? - maybe its related #23123

**Comment by qarmin** [comment]
This error occurs even if scene is opened/changed, but seems to be fixed.

**Comment by akien-mga** [comment]
Seems like #23123 indeed, which is fixed. Please comment if you can still reproduce it in 3.1 beta 9 (will be published today) or later.
