### ISSUE TITLE
GDScript compiler directives

### ISSUE THREAD

**Issue by kvvojciechowski** [godotengine/godot#26021]
When I always considering to write integration library for any of third-party for my game I always stuck when it comes to write custom logic depending on compiler options.
For example, I would like to integrate my game with itch.io's sdk or gamejolt's sdk but I don't want to write some custom logic to detect whenever the game was run with itch or gamejolt.
Instead I was thinking about compiler directives (like C++ has), where you can specify custom variables before building the game and have in code if statements (or something like that) to react on these variables. Then if I want to publish my game on itch.io I will setup some if statements to enable itch.io in my game, setup compiler options, and done. On other hand, if I want to publish my game on gamejolt, only I will need to do is to setup compiler options, and done.

I think this will be nice feature to have.
But now I will use one file with configuration working as "interface" and swap it with some kind of continuous integration system.

**Comment by akien-mga** [comment]
You can use feature tags for this use case, see https://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html

**Comment by kvvojciechowski** [comment]
@akien-mga Perfect! I got lost in docs. Thanks! This is what I need!
