### ISSUE TITLE
C#: Input.GetConnectedJoypads returning array without type

### ISSUE THREAD

**Issue by avahe-kellenberger** [godotengine/godot#26029]
**Godot version:** 3.0.6-1

**Issue description:** C#: Input.GetConnectedJoypads returns a generic array, when it should be returning Array<int>. This forces the user to assume type/type cast each time an element of the array is used.

**Steps to reproduce:** Attempt assigning `Godot.Array<int> joypads = Input.GetConnectedJoypads()`

**Comment by akien-mga** [comment]
Can you check if this is still valid in 3.1 beta 5?

**Comment by neikeq** [comment]
It's still valid. The bindings generator does not generate typed arrays.
This will be addressed either on 3.2 or 4.0. The plan is to either support this in C++ or have a hard-coded list in the bindings generator.
I think there is another issue like this already. We will need a tracker issue.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by raulsntos** [comment]
It's still valid in Godot 3.2.3.

I think the issue **neikeq** may be referring to is #19342 and **bojidar-bg** left a comment in https://github.com/godotengine/godot/issues/24292#issuecomment-446564665 which lists other methods where this happens.
