### ISSUE TITLE
TextureProgress node does not have an expand option

### ISSUE THREAD

**Issue by J-Guenther** [godotengine/godot#26028]
**Godot version:**
v3.0.6.stable.official.8314054

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
The TextureProgress node does not have an "expand" option like the TextureRect node or the TextureButton node have. This causes the rect_size of the node to depend on the height and width of the chosen texture. Furthermore it prevents from stretching the texture via the node's rect_size. 

**Steps to reproduce:**
1. Add a TexutreProgress Node
2. Add a texture to "Under", "Over", or "Progress"
3. Try to make the rect_size of the node smaller than the texture size. Or generally try to stretch the texture via the rect_size of the node.

**Minimal reproduction project:**

**Comment by cart** [comment]
Relevant PR: #18581. Same problem, but I missed TextureProgress in that PR.  Think a bigger refactor is in order to prevent divergences like this (and the ones I covered in the PR) in the future. There has to be a way to share code.

**Comment by elvisish** [comment]
Is this the issue that's causing TextureProgress to not scale with it's parent control like this?
![image](https://user-images.githubusercontent.com/16231628/137962803-6232f743-e295-4a82-93a2-837899c4c0ca.png)

**Comment by Calinou** [comment]
> Hello, bump! This continues to be a problem: Why can't TextureProgress items resize like TextureRects, and have an Expand option and a stretch mode?

It can be done, but as said above, it'd require copy-pasting code which is not very elegant. Feel free to open a pull request against the `master` branch for this either way :slightly_smiling_face:

**Comment by KoBeWi** [comment]
TextureProgressBar now has `nine_patch_stretch` property. If you enable it and don't set margins, it works like expand.
