### ISSUE TITLE
Navigation Color Editor Settings Do not Work

### ISSUE THREAD

**Issue by cwook** [godotengine/godot#26024]
**Godot version:**
3.1 beta4

**OS/device including version:**
Windows 7 Pro 64bit, GTX 1060 6GB, AMD Ryzen 5 1400

**Issue description:**
The editor's Navigation Edge/Solid/Disabled settings appear to have no or very little effect, rendering them nearly white. This makes it difficult to see in bright scenes.
![image](https://user-images.githubusercontent.com/1891696/52970367-6b38a300-3368-11e9-8e0d-34881866f3e8.png)

**Comment by cwook** [comment]
Seems partially fixed in beta5. Now the navigation gets colored, but it seems to use the disabled color regardless of whether the NavigationMeshInstance is enabled, and the colors only update when a project is closed and reloaded.
![image](https://user-images.githubusercontent.com/1891696/52971195-6a554080-336b-11e9-8770-c39c39365e4b.png)

**Comment by JFonS** [comment]
The colors not updating until the project is reloaded is expected, that's how gizmos work. 

Relevant code for anyone trying to fix this is in the `NavigationMeshSpatialGizmoPlugin`: https://github.com/godotengine/godot/blob/0fa3b808509dc0a86ab986320e601c12b988c205/editor/spatial_editor_gizmos.cpp#L3586

The `"navigation_material"` strings are probably a copy-paste mistake and should be unique every time, then the posterior calls to `get_material()` need to be updated to use the correct material name.
