### ISSUE TITLE
Rich Text Label Improvments

### ISSUE THREAD

**Issue by ficoos** [godotengine/godot#2603]
Add meta_enter()/meta_exit() events.
This will allow people to show tooltips when the user hovers over text.

So when you have a label with.
[url=info://enemy/plonker]Plonkers[/url]
You could add a tool tip on hover to quickly explain what Plonkers are.

More control over [url] style. Having the underline or hand icon might not be consistent with your game's overall visual style the user should be able to change it.

**Comment by akien-mga** [comment]
Fixed by #12984.
