### ISSUE TITLE
No Auto Tile tab when selecting AUTO_TILE in v3.1

### ISSUE THREAD

**Issue by PhelixTaken** [godotengine/godot#26036]
**Godot version:**

3.1 BETA

**Issue description:**

When selecting in a tile map AUTO_TILE, there is no Auto Tile tab under in the screen next to Animation

**Steps to reproduce:**
Make a Tile Map, go to "0" tab and then Tile Mode and then select AUTO_TILE

**Minimal reproduction project:**

[Project1.zip](https://github.com/godotengine/godot/files/2877636/Project1.zip)

**Comment by akien-mga** [comment]
I'm not very familiar with the next TileSet editor, but I think that's normal? Autotiles are edited directly in the main TileSet editor now.

**Comment by PhelixTaken** [comment]
Thanks, I found it!
