### ISSUE TITLE
Can't build resource file using Mingw/MSYS2 on Windows

### ISSUE THREAD

**Issue by king-numsgil** [godotengine/godot#26032]
**Godot version:** master branch : 146be33cdecb1190a4b13cee2463a676fe7fd42d

**OS/device including version:** Windows 10 / MSYS2 64-bit / Mingw64 from MSYS2

**Issue description:** I just managed to fix Python in MSYS2 so SCons can actually run, but I keep hitting the same problem: compilation stops after an error while building `godot_res.rc`. I tried to manually compile the file myself (which works) so the object file exists for SCons but SCons deletes the file and then ends. Console output with command : 
```
$ scons -j1 p=windows bits=64 tools=yes use_lto=yes deprecated=no use_mingw=yes verbose=yes
scons: Reading SConscript files ...
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
X11 not found.. x11 disabled.
Configuring for Windows: target=debug, bits=64
Using Mingw
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] build_res_file(["platform/windows/godot_res.windows.tools.64.o"], ["platform/windows/godot_res.rc"])
scons: *** [platform/windows/godot_res.windows.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by Calinou** [comment]
@king-numsgil Is this issue still relevant in the current `master` branch?

**Comment by king-numsgil** [comment]
Didn't test it, will do later today or tomorrow

**Comment by polychromia** [comment]
I've just tried it using Windows 7 / MSYS2 64-bit / Mingw64 from MSYS2.
Most recent `master` branch - same error.

**Comment by YRTV** [comment]
Well first of all wrong python and scons see https://github.com/conan-io/conan/issues/2638.
Second scons for MinGW subshell not available via pacman.

```
pacman -Ss scons
mingw32/mingw-w64-i686-waf 2.0.12-1
    General-purpose build system modelled after Scons (mingw-w64)
mingw64/mingw-w64-x86_64-waf 2.0.12-1
    General-purpose build system modelled after Scons (mingw-w64)
msys/scons 3.1.1-1 (base-devel)
    Extensible Python-based build utility
```

You may try installing scons with pip for mingw subshell or virtualenv.

**Comment by kroppt** [comment]
I am getting this issue at latest 119bf237209414a49879fba40459f22315ab1467. I installed all of the dependencies through MSYS2, and where applicable I installed the MinGW version, e.g. `mingw/mingw-w64-x86_64-python3` instead of `msys/python`, although it appears `msys/scons` depends on `msys/python2` directly.
There's no actual error message, so no way to know what's wrong.

**Comment by king-numsgil** [comment]
So, it seems the issue building Godot on MSYS2 was due to incompatible python/scons. Using `mingw-w64-x86_64-python3`, installed scons through `mingw-w64-x86_64-python3-pip`, managed to build successfully.

But, the link time is atrocious : close to 4 hours to link modules in debug. Changed to release_debug and link time reduced to ~30 mins. Binary size with debug is 589MB versus release_debug at 221MB, which is very large.

I tried using LTO, but link godot.exe failes with : 

```
C:/Dan/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: hq2x.windows.opt.tools.64.o (symbol from plugin): warning: no symbol for section '_ZZN4Math9fast_ftoiEfE1b' found
lto-wrapper.exe: fatal error: CreateProcess: No such file or directory
compilation terminated.
C:/Dan/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
```

**Comment by kroppt** [comment]
> Using `mingw-w64-x86_64-python3`, installed scons through `mingw-w64-x86_64-python3-pip`, managed to build successfully.

I also got through the compilation error with this.

> But, the link time is atrocious

I also got this, although I didn't bother waiting that long!

**Comment by YRTV** [comment]
For multi-threaded LTO and maybe multi-threaded linking in general (not sure about that) make sure GNU make available as make command, and it's not posix make(not msys2/make).

**Comment by YRTV** [comment]
GCC 9 based MInGW is only available via MSYS2. So I started using it myself.

1. From main MSYS terminal(MSYS2 MSYS)
`pacman -S mingw-w64-x86_64-python3-pip mingw-w64-x86_64-gcc mingw-w64-x86_64-yasm mingw-w64-x86_64-lld mingw-w64-i686-python3-pip mingw-w64-i686-gcc mingw-w64-i686-yasm mingw-w64-i686-lld make
`
2 For each MSYS2 MinGW subsystem in it's own shell `pip install scons `

Done you can build godot editor like this from correct MSYS2 MinGW shell 
`scons -j6 p=windows target=release_debug use_lto=yes use_mingw=yes`

If linking is slow use lld(LLVM drop in linker replacement for ld)
`scons -j6 p=windows target=release_debug use_lto=yes use_mingw=yes CCFLAGS=-fuse-ld=lld`

**Comment by Anutrix** [comment]
I did the following MSYS-related stuff on Windows:
1. Install and update(IMPORTANT) MSYS2(follow step by step on their homepage(https://www.msys2.org/)).
2. Install gcc-toolchain by running `pacman -S mingw-w64-x86_64-toolchain` (for 64 bit)
or `pacman -S mingw-w64-i686-toolchain`(for 32 bit).
3. Add `C:\msys64\mingw64\bin`(for 64bit) to Windows Environment Variable `PATH`(or navigate from MSYS2 shell).
4. Close/Restart all Command Prompts/Shells.

5. Follow Godot Engine's compiling docs. `scons platform=windows` is probably the simplest command.
