### ISSUE TITLE
The quit dialog should add a third option to quit to project list

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#26040]
This is a UX proposal. I think there should be a third option on the current quit dialog:
![quit dialog](https://user-images.githubusercontent.com/2206700/52983494-afb95280-33eb-11e9-9849-cbac7aed08f0.PNG)

I know there is already a shortcut and an option under the menu bar to quit to the project list but I always find myself quitting and opening Godot again or quitting, pressing cancel, then searching for the quit to project list and finally clicking that. 

If your current scene has some unsaved changes the dialog is 
![saveclose](https://user-images.githubusercontent.com/2206700/52983589-176f9d80-33ec-11e9-84fe-5073b4b57b31.PNG)
For this second case adding so many new buttons can be confusing but maybe a checkbox can be added at the bottom with the option (quit to project list) which will direct you there if you pick the `Save & Close` or the `Don't Save` options. There is probably a better way for this dialog so if you have a better idea I'm all for it.

**Comment by asheraryam** [comment]
Should quitting to the project menu become the default actually?

**Comment by Keetz** [comment]
@asheraryam if by becoming the default means that every time I quit Godot it just goes to the Project list I disagree. I would find it quiet annoying that if I choose to quit Godot I have to quit it twice.

Fair enough if it is just the checkbox, suggested in the issue, that is checked as default.

**Comment by coppolaemilio** [comment]
@asheraryam I don't think it should be the default because most people would want to actually quit the program, and if that is what they want opening a popup after that would be terrible. 
@Keetz if it ends up being a checkbox I would say disabled by default but remembering the state if they change it for future closing dialogs.

**Comment by GryphonClaw** [comment]
What about just having an option in the Godot program settings itself? (not project specific) and have it be false by default?

**Comment by Calinou** [comment]
@GryphonClaw I believe this is the kind of option you choose on a case-by-case basis, so an editor setting wouldn't be a good fit for this.

**Comment by GryphonClaw** [comment]
@Calinou I was going to suggest a Project and Editor setting but I'm not sure that would make total sense.... There should be a solution to this :)

Personally, I would like to always quit to the project list (having an Editor Setting) as I'm not sure how it would always be a case-by-case basis.

**Comment by coppolaemilio** [comment]
I'm with Calinou that it should be on a case-by-case rather than an editor setting. Specially because having that option on the settings would be very impractical and worse than what we have right now which is the menu _Quit To Project List_ item there.
It is not a big deal but whenever I find myself thinking about something several times and I can't seem to adapt to the existing options I create this kind of issues because they are usually anti-patterns.

**Comment by Keetz** [comment]
In my opinion, again, it would be very annoying if the default behaviour was to quit to project list every time I want to quit the editor.

I really don't see the current state as an issue, it is easy to quit to project list if that is desired.

**Comment by meld-cp** [comment]
I like the original suggestion... Extra button on quit, and a checkbox to quit to project list on the save dialog... But the checkbox could remember the last state per project... Not sure we need another setting for this.

**Comment by akien-mga** [comment]
There's already a shortcut to quite to the project list (Shift + Control + Q), so IMO people who want to go back there can use this shortcut. I don't see much use for having an extra button or a checkbox in the quit dialog, if I want to quit, I want to quit for real 99% of the time.

**Comment by meld-cp** [comment]
Yep, I get it, if it was bugging me a bit, I'd remember the shortcuts and use them as needed.   But I guess I tend to grab the mouse and simply click the X to close... Others would use the keyboard more... The extra ui elements are a nice to have, but certainly not a necessity.

**Comment by meld-cp** [comment]
@akien-mga, I do agree though, I tend to work in one project and rarely jump between them. When I quit, it's usually time for sleep, not opening the next project... and it's not like Godot takes ages to startup again anyway.  But, if there were going to be UI changes, I think the extra button and checkbox are quite user friendly.

**Comment by coppolaemilio** [comment]
This should be in godot-proposals, but actually I don't think it is such a big deal, so I'm closing.
