### ISSUE TITLE
scons errors _ITERATOR_DEBUG_LEVEL is 2 while Godot is at 0 when using target="debug"

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#26046]
**Godot version:**

623f7b64ae7ab075fe9cc7f5b7b2c777e774f81d

**OS/device including version:**

Win10 64bit

**Issue description:**

I'm fiddling about with trying to create a module using Box2D.  Compiled the libraries and module fine initially.  The first line of code in the hello world example works fine, but once it hits the second line, I get an explosion of errors like:

``` [100%] Linking Program        ==> bin\godot.windows.tools.64.exe
[100%] box2d_debug_x86_64.lib(b2World.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
box2d_debug_x86_64.lib(b2World.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
box2d_debug_x86_64.lib(b2BroadPhase.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
box2d_debug_x86_64.lib(b2BroadPhase.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
box2d_debug_x86_64.lib(b2ContactManager.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
box2d_debug_x86_64.lib(b2ContactManager.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
box2d_debug_x86_64.lib(b2Body.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
```

And so on.  It seems to indicate that the build is release, but the command I'm using is:

```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" amd64 && scons platform=windows tools=yes target=debug vsproj=yes -j4
```
My config.py looks like

```python
def can_build(env, platform):
	return platform == "windows"

def configure(env):
	
	env.Append(CPPPATH = [

		"src/Rope",
		"src/Common",
		"src/Dynamics",
		"src/Collision"		
	])

	if(env["platform"] == "windows"):

		env.Append(LIBPATH=["#modules/box2d/lib"])

		if(env["CC"] == "cl"): # VS

			if(env["target"] == "debug" or env["target"] == "debug_release"):
				env.Append(LINKFLAGS=["box2d_debug_x86_64.lib"])

			else: # Release
				pass # TODO

		else: # GCC - Untested

			if(env["target"] == "debug" or env["target"] == "debug_release"):
				env.Append(LIBS=["box2d_debug_x86_64"])

			else: # Release
				pass # TODO
```

The library was built in VS2017 as 64-bit debug.  I've tried all combinations of them though.

Let me know if I need to include more details.

**Comment by avencherus** [comment]
Opps, meant to say "can" package it up, not "can't".  XD

Had some time to look at it again, so uploading it.  It includes the .lib file, not sure if that would be a trustworthy file, but they can be rebuilt in a few minutes if necessary, following the instructions in the Box2D repo:  https://github.com/erincatto/Box2D/blob/master/Building.md

**Comment by avencherus** [comment]
Gave it another look today, resolved it by using the release library.  Is this how it is supposed to be configured?  I was expecting something else from target=debug.

If so, than this issue can be closed, I'll leave it to someone more knowledgeable with the build configurations to assess.

As an aside, the other error seen above, if anyone else bumps into this in the future, this is resolved by changing this setting in Visual Studio 2017 when building static libraries:

![devenv_2019-02-20_12-27-35](https://user-images.githubusercontent.com/13004169/53086196-4b8eaf80-350d-11e9-9e6e-5b460dca138b.png)

**Comment by IronicallySerious** [comment]
I don't think applying an edition inside VS will help because the solution file can just be regenerated, which means that all your changes will get lost.

I do remember that this error occurs in VS2017 when Debug and Release library builds get mixed up. See https://stackoverflow.com/questions/7668200/error-lnk2038-mismatch-detected-for-iterator-debug-level-value-0-doesnt

See if a Clean build followed by a Rebuild command does anything helpful

**Comment by avencherus** [comment]
@IronicallySerious Thanks for the reference.  It's been awhile since I had time to work on this, so my memory is a bit hazy, but I do recall trying the general advice.  When I get the time to return to this (maybe late summer with luck) I'll give everything a proper review.

And also, my apologies, in re-reading I could've been more precise.  The project property change above in the screenshot is being done in a VS solution related to Box2D, and is what is being used to build the static libraries that the module will use.

It wouldn't be the godot.sln that the build could regenerate.  I assume that could be avoided as well by dropping the the `vsproj=yes` flag from any future rebuilds?

**Comment by IronicallySerious** [comment]
@avencherus Yes, you could avoid `vsproj=yes` but that would mean you are trying to run previous versions of your solution file with newer Godot code. This can bring some problems if any of the newer changes did a configuration change to Scons, or let's say, brought a new dependency to Godot, which you won't have registered at that time.

**Comment by avencherus** [comment]
Haven't encountered this one as of late.  Closing for now.  Will re-open if it appears.  It was most likely a configuration issue.
