### ISSUE TITLE
"Cannot convert argument 1 from Object to Object" on signal callback with type hint

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#26047]
**Godot version:**
3.1 beta 4

**OS/device including version:**
Windows 10

**Issue description:**
When trying to use Area2D's body entered signal, I get this error.

![image](https://user-images.githubusercontent.com/21234930/52996961-f26f3080-33d3-11e9-8fa1-5c1af57465ff.png)

This may or may not be a wider spread issue.

**Comment by avencherus** [comment]
Do you have a code example?  I haven't run into this yet myself, and can't reproduce it based on the description.

**Comment by akien-mga** [comment]
Indeed, without steps to reproduce nor a project to test with, we can't really debug nor fix anything.

**Comment by 11clock** [comment]
It is an issue with the typing system. In the connected signal function, in the parameter make sure it shows “body: PhysicsBody2D.” I am getting the error when a kinematic body overlaps the Area2D.

**Comment by akien-mga** [comment]
MRP: [typed_signal_bug.zip](https://github.com/godotengine/godot/files/2923016/typed_signal_bug.zip)
