### ISSUE TITLE
The file dialog should reset the scroll after opening a directory

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#26041]
UX proposal. (I would love to be able to add tags to the issues)

When you open a new directory on the file dialog the scroll should go back to the top, otherwise you start browsing that new dir in the same position as your preview view was. This creates confusion and it is not the expected behavior. If my explanation is vague I can include a gif with the issue.

**Comment by ankitpriyarup** [comment]
> UX proposal. (I would love to be able to add tags to the issues)
> 
> When you open a new directory on the file dialog the scroll should go back to the top, otherwise you start browsing that new dir in the same position as your preview view was. This creates confusion and it is not the expected behavior. If my explanation is vague I can include a gif with the issue.

Please include a gif if you can, I will work on this.

**Comment by akien-mga** [comment]
There's already a PR to fix it, see right above your comment.

**Comment by coppolaemilio** [comment]
This issue is still present in the latest build.
