### ISSUE TITLE
[GLES3] MeshInstances with skeletons distorted when far from scene origin

### ISSUE THREAD

**Issue by matthew1006** [godotengine/godot#26057]
**Godot version:**
3.1 Beta 5

**OS/device including version:**
Windows 7

**Issue description:**
When using GLES3, MeshInstances with skeletal deformation become distorted towards the scene origin when positioned far from the scene origin.
This doesn't happen with GLES2 (at least at the scale I tested) but the meshes do start to jiggle slightly when animating.

**Steps to reproduce:**
Make sure Godot is in GLES3 mode.
Import a mesh with skeletal animations and position it far from the scene origin. The further you move it the more distorted it becomes. This is more noticeable with complex meshes, such as characters, as the distortions can be noticed from less than 500 units from the origin. As an example I used a sphere with 2 bones at distances of 0, 1000, 10000 and 100000 units from the origin on the X axis.

Sphere at origin (the curving is because of an animation):
![sphere_at_origin](https://user-images.githubusercontent.com/7364976/53021897-1a04de00-3452-11e9-97af-f3c049e97222.PNG)

Sphere at x=100000:
![sphere_at_100000](https://user-images.githubusercontent.com/7364976/53022009-428cd800-3452-11e9-8d37-d21590d20d90.PNG)

You can see that the mesh seems to be pulled away from the bones except at the ends where the bone weight is highest.
![sphere_bone_weights](https://user-images.githubusercontent.com/7364976/53022885-08bcd100-3454-11e9-8399-948b5084565c.PNG)

**Minimal reproduction project:**
[example.zip](https://github.com/godotengine/godot/files/2880404/example.zip)

**Comment by fire** [comment]
100km distances is not expected to work with 32bit floats. See https://github.com/godotengine/godot/issues/288

**Comment by matthew1006** [comment]
100km is extreme but this distortion is noticeable after only a few hundred metres

**Comment by aaronfranke** [comment]
Does this occur with Godot 3.0.6?

**Comment by matthew1006** [comment]
It does happen in 3.0.6
I think the issue is that precision is being lost on this line:
`scene.glsl:429 mat4 bone_matrix = transpose(mat4(m[0], m[1], m[2], vec4(0.0, 0.0, 0.0, 1.0)));`
because 'm' is a high precision mat3x4 but its contents are being copied into a regular precision mat4.
The GLES2 code doesn't do this.

**Comment by aaronfranke** [comment]
What does `highp` do? High precision? The problems in OP look like they might be caused by 16-bit floats, but `float` is already 32-bit?

**Comment by matthew1006** [comment]
I thinks floats are 16 bit in shaders. `highp` makes them 32 bit and `lowp` makes them 8 bit.
@reduz fixed this by making all the relevant matrices in scene.glsl high precision.

**Comment by aaronfranke** [comment]
Quite strange, is this just the way Godot does it? 

What are the use cases for 8-bit floats? They're not an IEEE standard.

**Comment by matthew1006** [comment]
They make shaders faster when precision isn't important.
