### ISSUE TITLE
Label Autowrap invalid。

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#26050]
![default](https://user-images.githubusercontent.com/2855349/53005335-036c8000-346e-11e9-95af-0d6d13ee618a.png)

**Godot version:**
v3.1.beta branch:master

**OS/device including version:**
win10

**Issue description:**
Label Autowrap invalid。

**Comment by groud** [comment]
This is expected behavior, since you did not put any space in you number it does not get split.
Autowrap only works for words.

**Comment by volzhs** [comment]
...or CJK letter. :)
