### ISSUE TITLE
User Interface Grid "partly" invisible

### ISSUE THREAD

**Issue by Hanprogramer** [godotengine/godot#26055]
**Godot version:** 3.1 Beta 5

**OS/device including version:** *Windows 10 (Amd)*

**Issue description:** 
*the lines are not rendered correctly in the grids and making weird noises missing. I've tried changing around some theme colors the issue won't go. I think this is probably because of the new anti aliasing. But, i've tried on intel drivers and this issue don't seem to appear there*

**Steps to reproduce:** *Open the ui for 3D editor*

**Minimal reproduction project:** *(Default project)*

![godotissueamd](https://user-images.githubusercontent.com/30620423/53019936-ca241800-344d-11e9-82bd-f7b25d078f07.jpg)

**Comment by akien-mga** [comment]
What's your GPU and driver version?

> I think this is probably because of the new anti aliasing.

What "new" anti aliasing are you referring to?

**Comment by Hanprogramer** [comment]
Well its the antialiasing used in the editor ui. But, after i've restarted my pc its no longer there. The bug is gone

**Comment by Calinou** [comment]
@Hanprogramer Have you reproduced this bug on Godot 3.1.1, or can it be considered resolved?

**Comment by Calinou** [comment]
I'll close this issue as there was no response from @Hanprogramer in 30 days. Thanks for reporting it still :slightly_smiling_face:
