### ISSUE TITLE
Conditionally setting NORMALMAP or NORMALMAP_DEPTH in fragment shader (3D) causes missing NORMAL in light shader

### ISSUE THREAD

**Issue by nodefish** [godotengine/godot#26063]
**Godot version:**
3.1 beta 5

**OS/device including version:**
Win10 64 / GTX 980 Ti

**Issue description:**
In a shader, if you conditionally try to set NORMALMAP and/or NORMALMAP_DEPTH, normals are lost if the condition is false.

Fragment shader example:

```
if(use_normal_map == true) {
    NORMALMAP = texture(texture_normal,base_uv).xyz;
    NORMALMAP_DEPTH = normal_depth;
}
     
```

When `use_normal_map` is false, the default NORMAL is often not passed to the LIGHT shader. It seems to be happening on some .obj and .glb files that I import, but not others, for some reason, even though AFAIK I'm exporting normals in the same way on all of them.

I'm not sure if I'm doing something stupid here and there's some proper way to conditionally set NORMALMAP in the fragment shader.

**Comment by kaadmy** [comment]
Ensure the models are UV unwrapped, if the UV coordinates are wrong then tangent coordinates will be invalid, thus causing normalmap artifacts.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing.
