### ISSUE TITLE
Exported PoolIntArray and other Pool*Array types reset to initial value upon saving

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#26066]
**Godot version:**
3.1. beta 5

**OS/device including version:**
Win 7 x64 
Radeon 6630M

**Issue description:**
See gif
![2019-02-19_19-10-50](https://user-images.githubusercontent.com/4525388/53037373-52b8ad80-347a-11e9-94fc-c93fa35cb840.gif)

**Steps to reproduce:**
Export an array, modify it, save, watch it get reset.
For added fun, if the initial value is [], the size gets reset back to 0, too!

EDIT: Source control reveals that the modified array value is never written to the tscn.

**Minimal reproduction project:**
https://github.com/Zireael07/CyberpunkRoguelike/commit/aefd635fb2d5663cbec9a13aa798d404cfb2d184

(I could probably zip it up if necessary?)

**Comment by akien-mga** [comment]
It doesn't happen with `export (Array)`, only `PoolIntArray` (maybe other pool types).

It's not a recent regression either, same issue all the way down to alpha 1. Godot 3.0 doesn't allow editing `PoolIntArray` in the editor, so can't test there.

**Comment by Zireael07** [comment]
Unfortunately I didn't have other alphas or betas laying about, so couldn't check - and it didn't occur to me that using PoolIntArray could be the problem.

For the time being, I'll use export(Array) instead :)

As for 3.0, uh, doesn't it? It looks to me it does (3.0.3, another project but the Item code is exactly the same):
![2019-02-20_15-18-59](https://user-images.githubusercontent.com/4525388/53098030-0aa19580-3523-11e9-8136-8345798cd175.gif)

**Comment by qarmin** [comment]
Also this occurs with PoolByteArray and PoolStringArray, so it seems to be universal issue

**Comment by akien-mga** [comment]
> As for 3.0, uh, doesn't it? It looks to me it does (3.0.3, another project but the Item code is exactly the same):

Yeah but it doesn't support showing you the default value defined in the script, so it's of quite limited use in 3.0.

**Comment by Zireael07** [comment]
Works well enough for my usecase, I never noticed the default not being shown :) and I've been using it for months :)

**Comment by bojidar-bg** [comment]
The bug comes from this line in the reproduction project:
```
export(PoolIntArray) var damage = [1,6]
```
It should be:
```
export(PoolIntArray) var damage = PoolIntArray([1,6])
```

I guess it should be either converted behind-the-scenes, or made into an error.
