### ISSUE TITLE
Registering NativeScripts with ClassDB

### ISSUE THREAD

**Issue by sprucely** [godotengine/godot#26067]
I've been trying to figure out how to make a custom AudioStream (implemented via NativeScript) appear as an option in a AudioStreamPlayer node. I assume the problem is it's not a real subclass of AudioStream that is registered via `ClassDB::register_class<...>`. I've read the documentation that says NativeScripts are unable to extend the engine. Is what I'm trying to do considered extending the engine? Is there something fundamental in the design of godot that makes this difficult/impossible, or is it just a feature that hasn't been implemented?

What I'm trying to do is related to #18135. I want to create an addon that integrates csound (dynamically linked because it is LGPL). I'm able to create a custom node type, and I think I can register a callback directly with the audio server for mixing audio data from csound, but it would be better if it could be inserted earlier in godot's audio pipeline.

For those curious, I'm working with godot-rust. I had started creating my own csound wrapper using libloading. Then I found that someone had just published a new crate, https://github.com/neithanmo/csound-rs.

**Comment by Zylann** [comment]
The Godot script API in general cannot register scripts as if they were built-in classes, so is NativeScript (see https://github.com/godotengine/godot/issues/6067#issuecomment-238250383). However you should still be able to extend the engine, perhaps just differently.

IMO procedural audio effects could be exposed by the script API, this way any language (including C#) could implement some. Adding it as a GDNative-only API is another way, but it limits considerably the accessiblity of the feature, and would only be worth it if there are technical limitations to do so (such as having to use a C dynamic library alhough doable with C# P/Invoke, or exposing features that could not possibly be exposable through a scripting API, for example passing around platform-specific pointers).

**Comment by sprucely** [comment]
I meant implementing an AudioStream so that it can be used by the various types of AudioStreamPlayers. I was picturing users choosing an AudioStreamCSound within say, an AudioStreamPlayer2D node, and from there editing the various CSound options exposed by AudioStreamCSound. Now that I think about it, I wonder if I could just put the CSound options in a custom node. And when the custom node is placed as a child of an AudioStreamPlayer, the custom node can set its parent node's AudioStream property.

**Comment by sprucely** [comment]
My mental model of gdnative is finally starting to solidify, and I'm thinking I won't be able to create a custom AudioStream using gdnative. Please correct me if I'm wrong about any of this. Custom AudioStreams instantiate a custom AudioStreamPlayback which is responsible for doing the actual work of mixing audio frames. I see no calls in the cpp code to ClassDB::bind_method for any of AudioStreamPlayback's methods, which leads me to believe that there is no way to override its mix callback outside of a subclass of AudioStreamPlayback.

**Comment by Calinou** [comment]
Closing, as [GDNative is being reworked for 4.0](https://github.com/godotengine/godot/issues/35467)
.
