### ISSUE TITLE
ShaderGraphNodes Color Uniform broken.

### ISSUE THREAD

**Issue by PlanetKiller** [godotengine/godot#2606]
*Bugsquad edit:* Initially seen in 2.0 alpha 2015-10-03

 Testing material shader graphs on godot 2.0 and I noticed that the color uniform node is broken. Blue does not work and alpha cannot connect.

I'm guessing that blue and alpha channels got transposed since it acts like blue is at 255.

Changing the alpha channel does nothing.

example:
https://drive.google.com/file/d/0B3i2iHqe6FaubjNDQUNRUDdSMTg/view?usp=sharing

**Comment by PlanetKiller** [comment]
Still broken with the current 10-29 ~ 10-30 release. I have two other work arounds (like using vector uniforms or a solid-color image).

**Comment by MarianoGnu** [comment]
1 line fix yay!
