### ISSUE TITLE
AnimationPlayer overrides Import settings off AnimatedSprite sprites.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#26076]
https://www.youtube.com/watch?v=cyDZ6V9u1zA

You can see the bug in action here, is easily reproducible:

1. Make an AnimatedSprite with sprites and set their filtering to off.
2. Make a new Animation on the AnimationPlayer, it will set their filtering again to on and will change their compress mode.

**Comment by Sslaxx** [comment]
Might be worth noting this is using `AnimatedSprite3D`.

**Comment by akien-mga** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
