### ISSUE TITLE
Weird UV for quad MeshInstance in Godot 3.1

### ISSUE THREAD

**Issue by miskatonicstudio** [godotengine/godot#26074]
**Godot version:**

3.1 beta 5

**OS/device including version:**

Pop!_OS 17.10 (Artful Aardvark)

**Issue description:**

I'm working on a simple slide puzzle game. I tried to export it to HTML, but opening the `.html` file resulted in this error:

```
Init OS
Init Audio
Init VS
Init Physicsserver
OpenGL ES 3.0 Renderer: Mozilla
**ERROR**: missing function: glMapBufferRange
-1
**ERROR**: -1
```

I've decided to try 3.1 beta 5 to see if the issue is resolved and it seems that it is :wink: However, another problem emerged:

![screenshot from 2019-02-19 23-50-41](https://user-images.githubusercontent.com/36821133/53053421-9672dd80-34a1-11e9-849d-cb6e48bdac25.png)

To compare, this is how the original game looks like (3.0.6 stable):

![screenshot from 2019-02-19 23-50-32](https://user-images.githubusercontent.com/36821133/53053435-a25e9f80-34a1-11e9-80cd-18b9013ce15f.png)

I think the most important piece of code is this one, used to calculate new texture coordinates:

```
extends Spatial

export (int) var SIZE = 1

var arrays = null

func _init():
	arrays = _generate_quad_mesh_arrays(SIZE)

func _ready():
	var array_mesh = ArrayMesh.new()
	array_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLE_FAN, arrays)
	$MeshInstance.mesh = array_mesh

func _generate_quad_mesh_arrays(size=1):
	var new_quad_mesh = QuadMesh.new()
	new_quad_mesh.size = Vector2(size, size)
	return new_quad_mesh.get_mesh_arrays().duplicate()

func set_uv(index_x, index_y, size):
	index_y = size - index_y - 1 # UV starts top left
	var uv_delta = 1 / float(size)
	arrays[ArrayMesh.ARRAY_TEX_UV][0] = Vector2(uv_delta * (index_x), uv_delta * (index_y + 1))
	arrays[ArrayMesh.ARRAY_TEX_UV][1] = Vector2(uv_delta * (index_x), uv_delta * (index_y))
	arrays[ArrayMesh.ARRAY_TEX_UV][2] = Vector2(uv_delta * (index_x + 1), uv_delta * (index_y))
	arrays[ArrayMesh.ARRAY_TEX_UV][3] = Vector2(uv_delta * (index_x + 1), uv_delta * (index_y + 1))

func set_allowed_direction(direction):
	$Detectable.allowed_direction = direction
```

I just want to check if this is an error with 3.1 beta or is it a new feature and I should change the texture coord mapping in my program?

**Steps to reproduce:**
* run the program in 3.0.6 => it works, but HTML export is incorrect
* run the program in 3.1 beta 5 => it works, but UV is messed up, but HTML export works (also messed up, but the game runs in the browser)

**Minimal reproduction project:**

Source code can be found here:

https://github.com/miskatonicstudio/slide-puzzle-game

**Comment by henkz1** [comment]
QuadMesh have six vertices since 9cd1c20f6aae87e34b45471271062127d385871e, so you'll have to add uvcoords for the two remaining vertices:
 
`	arrays[ArrayMesh.ARRAY_TEX_UV][4] = Vector2(uv_delta * (index_x + 1), uv_delta * (index_y))
	arrays[ArrayMesh.ARRAY_TEX_UV][5] = Vector2(uv_delta * (index_x + 1), uv_delta * (index_y + 1))`

**Comment by akien-mga** [comment]
@JFonS Is the compat breakage in 9cd1c20 intended?

**Comment by miskatonicstudio** [comment]
@henkz1 Thank you, works like a charm :) I actually expected something like this, but I wanted to confirm what @akien-mga asked about: was this change intentional or is it actually a bug and should be fixed?

Another question: after fixing the UVs I started the game again an the Tween node doesn't seem to work:

```
	tween.interpolate_property(
		puzzle_piece, 'translation',
		Vector3(0, 0, 0), Vector3(1,1,1),
		0.2, Tween.TRANS_SINE, Tween.EASE_IN_OUT
	)
```

In this example `puzzle_piece` is of tupe `Spatial`, and this code should move it, but nothing happens. Note: `Tween.start()` is called in `_ready()`, so it's not here.

**Comment by henkz1** [comment]
@miskatonicstudio You're welcome =) However you should not use the issue tracker for general support, if you think there is a bug with tween you should open a new issue for it.
I have never used tween that way so I don't know if it used to work, calling tween.start() or tween.resume(puzzle_piece, 'translation') after tween.interpolate should fix your issue.

**Comment by JFonS** [comment]
The changes are intentional, the openGL quad primitive is considered deprecated and  moving quads to triangle meshes made them selectable from the editor viewport.

Now quads are made of 2 triangles, so 6 vertex in total.

**Comment by JFonS** [comment]
Closing, as it's an expected change.

**Comment by akien-mga** [comment]
@Calinou Could you add a mention to this in the "compat breakage" part of the changelog? Namely that quads are now made of 2 triangles, and thus use 6 vertices (instead of 4).

**Comment by Calinou** [comment]
@akien-mga Done :slightly_smiling_face:
