### ISSUE TITLE
Overdraw Mode Leaves a Shadeless Version of the Geometry Stuck to the Camera

### ISSUE THREAD

**Issue by cwook** [godotengine/godot#26070]
Godot 3.1 Beta5
Windows 7 Pro 64 bit
GTX 1060 6GB, Driver Version 417.35

Switching to the overdraw mode seems to leave a shadeless black copy of the geometry stuck to the camera. Not using any vertex shaders, this example just uses CSG geometry. Also affects non-CSG meshes. Changing mesh geometry doesn't alter the copied geometry until I switch to another display mode and then back to overdraw mode.

![image](https://user-images.githubusercontent.com/1891696/53049032-02762700-344b-11e9-9e2c-b44ef3ca6c51.png)
![image](https://user-images.githubusercontent.com/1891696/53049045-0a35cb80-344b-11e9-9a66-433bdcd2b285.png)

[Video of issue](https://i.imgur.com/8TkuLPx.gifv
)

**Comment by JFonS** [comment]
I would say the depth buffer is not being cleared when entering overdraw mode.

**Comment by bojidar-bg** [comment]
Looks similar to #25994, was it fixed in 8fd2eb6234541dfb34800f7ef4b0350c5795bb67?

**Comment by akien-mga** [comment]
Assumed fixed by 8fd2eb6, please comment if you can still reproduce it in 3.1 beta 8 or later.
