### ISSUE TITLE
Animation timeline snapping toggle disabled is still snapping.

### ISSUE THREAD

**Issue by RyanJEC** [godotengine/godot#26079]
**Godot version:**
3.1 beta 5

**OS/device including version:**
Windows 10 - GTX 1050 3GB

**Issue description:**
When disabling animation timeline snapping it still snaps with the snap value.

**Steps to reproduce:**
Disable timeline snapping

**Minimal reproduction project:**
New created project.

**Comment by karliss** [comment]
I observed that keyframe snapping got correctly enabled/disabled but cursor snapping was always enabled.

**Comment by akien-mga** [comment]
Cannot reproduce in Godot 3.2, I'll assume that it has been fixed.
