### ISSUE TITLE
Animation jumps to zero time/pos after the animation is finished

### ISSUE THREAD

**Issue by TypeOverride** [godotengine/godot#26083]
**Godot version:**
3.1 Beta 5 (previous versions dont have this bug)

**OS/device including version:**
Windows 7

**Issue description:**
The Animation jumps to zero time/pos after the animation is finished.

**Steps to reproduce:**
play an Animation by an AnimationPlayer.

(in own code this bug makes problems on my project - own code behaviour not working anymore like expected and it makes it hard to work around this problem. And i think the finished event is not throwing anymore)

Maybe its this update that leads to the problem?:
https://github.com/godotengine/godot/commit/5ec4f14a245b66b3e268f3c6cbb68a85336c7ca6

**Minimal reproduction project:**
https://i.imgur.com/8lBEWdv.gif

**Comment by akien-mga** [comment]
Regression from #25886.
#26068 will fix it.
