### ISSUE TITLE
Make generated signal methods include type hints

### ISSUE THREAD

**Issue by SeleckyErik** [godotengine/godot#26091]
**Issue description:**
I'd like to propose that auto-generated signal method signatures should include type hints. There might be reason why certain projects decided against using type hints and thus, appropriate editor option might be needed to turn this feature on and off. On the other hand, I personally see no reason why not to use type hints and having this as a default behaviour would encourage habit of using them.

**Comment by vnen** [comment]
It does already (at least it should). There's an option to enable/disable in the editor settings.

**Comment by SeleckyErik** [comment]
You are right indeed! The option that toggles this behaviour is `text_editor/completion/add_type_hints`. Does it control type hints in other situations too or is it solely for the signal methods? If it's only for the signal methods, maybe a more appropriate name should be used? Also, I'd suggest setting the editor option to true by default from the version 3.2 or 4.0. Since type hints were added quite recently, the projects using the current version might not want it on by default to avoid inconsistent code. However there should be no issue with using type hints with new projects.

**Comment by vnen** [comment]
> Does it control type hints in other situations too or is it solely for the signal methods?

It also enables in the autocompletion, in particular when overriding a parent's method (such as `_input()`).

**Comment by SeleckyErik** [comment]
I see. In that case the name is indeed appropriate and well fitting.

Anyway, closing the issue as irrelevant.
