### ISSUE TITLE
There is a problem with the layout Container

### ISSUE THREAD

**Issue by crud-boy** [godotengine/godot#26098]
### Problem a：
```
ScrollContainer
--VBoxContainer              <-  Vbox alignment center is invalid
----navbar        
```

### Problem b
```
ScrollContainer
--VBoxContainer              
----CenterContainer        <- alignment center is invalid
------navbar        
```

godot:  3.1.bate.calinou.623f7b6 (Daily compiled version)
OS:  win10 x64

The layout has no maximum or minimum size, the alignment of Vbox and hbox is invalid, CenterContainer has no left, right, top and bottom alignment options, and the layout constraint has no overflow options similar to CSS

**Comment by mrcdk** [comment]
Sorry, this issue barely explains what the problem you have or have found is. Unless you explain it in more depth or with pictures, I don't think anyone will understand what you are trying to say.

**Comment by groud** [comment]
Yes, please explain a little bit more your issue. 

But some answers to your comments:
- VBoxContainers and HBoxContainer were never meant to align content vertically/horizontally. You need to put them into another container to do so.
- "CenterContainer has no left, right, top and bottom alignment options,". Yes, it is a CENTERContainer.
You can put a CenterContainer in a HBoxContainer/VBoxContainer to align content top-center, center-left, center-right or bottom-center (with the appropriate alignment options in those containers).

**Comment by crud-boy** [comment]
![](https://github.com/crud-boy/temp_file/raw/master/2.png)
The width of VBoxContainer should be 100%. CenterContainer should inherit the width of VBoxContainer. When the viewport size is larger than the minimum size of navbar_bg, navbar_bg should be displayed in the center. When the viewport size is smaller than the minimum size of navbar_bg, the alignment mode is left to right.

**Comment by crud-boy** [comment]
![](https://github.com/crud-boy/temp_file/raw/master/1.png)
![](https://github.com/crud-boy/temp_file/raw/master/3.png)
You can only use center constraints on the outside, but VBox can't use center constraints, so how can VBox constraints align controls, just like QT layout and html, with child controls center

**Comment by Zireael07** [comment]
Pictures don't work @crud-boy

**Comment by crud-boy** [comment]
@Zireael07 ok，Forget to be public

**Comment by groud** [comment]
> The width of VBoxContainer should be 100%

It is already the case, if you look at the selection rectangle you see it takes the full screen width.

> CenterContainer should inherit the width of VBoxContainer

It already does, as the CenterContainer selection area suggests.

> When the viewport size is larger than the minimum size of navbar_bg, navbar_bg should be displayed in the center.

No it should not, the HboxContainer pads its content to the left. If you want to achieve centering you probably need to use the anchor and margin system. And put your base node top the top-center.

> You can only use center constraints on the outside, but VBox can't use center constraints, so how can VBox constraints align controls, just like QT layout and html, with child controls center

You need to put you logo in a center container I guess.

Ok, I am sorry but I that point I will assume that these issues results more in a misunderstanding on how the Container system works than real engine issues. Please use the other [community channels](https://godotengine.org/community) for help. If you still have problems after that, please open an issue for each specific problem with a specific reproduction case.
