### ISSUE TITLE
Inheriting custom class causes "Too few arguments for _init() call. Expected at least 1" regardless of number of arguments.

### ISSUE THREAD

**Issue by valentinAlkan** [godotengine/godot#26106]
**Godot version:**
3.1-custom-build 8908bdc7f2fd002d71e836ef4f9c16fdfdc69e99

**OS/device including version:**
Windows 10

**Issue description:**
Extending a custom class, and overriding _init() causes error: "Too few arguments for _init() call. Expected at least 1", regardless of how many arguments _init() actually has.

**Steps to reproduce:**
```
class Parent:
	func _init(param1):
		self.param1 = param1
		
class Child extends Parent:
	func _init(param1, param2):
		.init(param1)
		self.param2 = param2
```

**Minimal reproduction project:**
[inherited_custom_class_override_init_error.zip](https://github.com/godotengine/godot/files/2887141/inherited_custom_class_override_init_error.zip)

**Comment by eon-s** [comment]
You need to do `func _init(p1,p2).(p1):` to call the parent class constructor.

See https://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#class-constructor

**Comment by valentinAlkan** [comment]
Interesting. That seems to work, but is very unintuitive and not pythonic at all.
