### ISSUE TITLE
Unable to get tile from atlas tileset in TileMap

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#26108]
**Godot version:**
3.1 beta 5

**Issue description:**
I've been trying to copy a region of a TileMap into a texture, this was easy to do using a regular tileset, but I can't find any way of getting the right texture region of tiles from an atlas tileset made with the new editor, get_cell and get_cellv don't provide any information about the subtile and those are the only functions able to get a cell from the map.

**Comment by bojidar-bg** [comment]
Maybe you are looking for [`Tilemap::get_cell_autotile_coord`](http://docs.godotengine.org/en/latest/classes/class_tilemap.html#class-tilemap-method-get-cell-autotile-coord)?

**Comment by MightyPrinny** [comment]
> Maybe you are looking for [`Tilemap::get_cell_autotile_coord`](http://docs.godotengine.org/en/latest/classes/class_tilemap.html#class-tilemap-method-get-cell-autotile-coord)?

That was what I needed thank you, I never tried that method because it had autotile in the name.
