### ISSUE TITLE
Keep Camera2D's Drag MarginH/V Enabled off by default

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#26102]
**Godot version:**

aa5b99821b23d74eafb49f4b0d2d86fe693a903c

**Issue description:**

On more than one occasion, while assisting people in the discord server, someone will come in wondering why, no matter what they do, their camera2D simply will not move.  After going through a number of troubleshooting questions, with changing just about everything possible, with recreating the scripts and nodes and setting up signals, and questioning whether Godot is just experiencing a highly evasive bug, somehow the camera just will not move.

Then, seemingly miraculously, it works, by just letting the script run for a while; then it becomes clear: oh right, the drag margins.

In my view, these properties being on by default does more harm than good; I don't believe the typical user, when setting up their camera2D, wants these properties to be on, in fact I think it's a niche need for particular kinds of games, where other games usually just want the camera to follow as the developer dictates it.  Given the problems it causes with people coming into the engine and becoming near-immediately frustrated, and the fact that you probably don't need the drag margins on until you understand what they do, I think they should default to off; I believe this will spare a lot of headaches, and doesn't take but two clicks for those who need them on.

**Comment by KoBeWi** [comment]
1000% agree. I myself sometimes forget to turn off these and it only causes confusion.

**Comment by CptPotato** [comment]
This must have been what I experienced when trying the camera node. Since then I've been using canvas layers and custom code to write my own.

**Comment by avencherus** [comment]
@KoBeWi  Same.  On top of that, I've never ended up using them, they don't provide the effect I want for that sort of thing.  When I start working on a camera it's always just an extra step to go turn off these defaults, because I want to start the camera out as basic as possible and then add to it.

**Comment by capnm** [comment]
Nah, a typical user is more frustrated that it's still broken #23108 ;)
