### ISSUE TITLE
GCC warning: enumeral and non-enumeral type in conditional expression [-Wextra]

### ISSUE THREAD

**Issue by marxin** [godotengine/godot#26100]
The code is very suspicious:

```
drivers/gles3/rasterizer_scene_gles3.cpp: In member function 'void RasterizerSceneGLES3::initialize()':
./core/typedefs.h:124:40: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
 #define MIN(m_a, m_b) (((m_a) < (m_b)) ? (m_a) : (m_b))
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
drivers/gles3/rasterizer_scene_gles3.cpp:5042:31: note: in expansion of macro 'MIN'
   state.max_ubo_reflections = MIN(RenderList::MAX_REFLECTIONS, max_ubo_size / sizeof(ReflectionProbeDataUBO));
                               ^~~
```

**Comment by akien-mga** [comment]
That code seems correct to me. Maybe `RenderList::MAX_REFLECTIONS` needs to be cast to int to silence the warning?

The `RenderList` struct uses an enum as a shortcut to define various int constants. Could maybe be changed to define all as individual constants without using `enum` if that's not standard.

**Comment by marxin** [comment]
> That code seems correct to me. Maybe `RenderList::MAX_REFLECTIONS` needs to be cast to int to silence the warning?

Question is whether ```max_ubo_size / sizeof(ReflectionProbeDataUBO)``` expression will always match an enum value defined in the anonymous enum? If so, then casting would be fine.

> 
> The `RenderList` struct uses an enum as a shortcut to define various int constants. Could maybe be changed to define all as individual constants without using `enum` if that's not standard.

Alternative approach would be to define ```state.max_ubo_reflections``` as an integer type.
That's

**Comment by marxin** [comment]
@akien-mga What do you think?

**Comment by akien-mga** [comment]
> Question is whether `max_ubo_size / sizeof(ReflectionProbeDataUBO)` expression will always match an enum value defined in the anonymous enum? If so, then casting would be fine.

I mean, if we do `MIN((int)RenderList::MAX_REFLECTIONS, max_ubo_size / sizeof(ReflectionProbeDataUBO));` (which is the intended logic), it should work correctly I suppose?

> Alternative approach would be to define `state.max_ubo_reflections` as an integer type.

I think that makes sense. All of the `RenderList` enum should probably be moved to constants, it seems to only be used as sugar for defining constants within a common scope.

Maybe @reduz can advise on what he'd do to make this cleaner?

**Comment by marxin** [comment]
> > Question is whether `max_ubo_size / sizeof(ReflectionProbeDataUBO)` expression will always match an enum value defined in the anonymous enum? If so, then casting would be fine.
> 
> I mean, if we do `MIN((int)RenderList::MAX_REFLECTIONS, max_ubo_size / sizeof(ReflectionProbeDataUBO));` (which is the intended logic), it should work correctly I suppose?

Problem is that the enum has "holes", so e.g. value of ```999``` is not a valid enum value.

> 
> > Alternative approach would be to define `state.max_ubo_reflections` as an integer type.
> 
> I think that makes sense. All of the `RenderList` enum should probably be moved to constants, it seems to only be used as sugar for defining constants within a common scope.

Then I would do the casting into integer type.

> 
> Maybe @reduz can advise on what he'd do to make this cleaner?
