### ISSUE TITLE
Possible bug with UndoRedo's MERGE_ALL mode

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#26118]
**Godot version:**
ced77db

**Issue description:**
It seems that there's a bug with `UndoRedo`'s `MERGE_ALL` mode, in that it repeats instructions if actions are committed fast enough. In the example bellow, if pressing "ui_accept" (enter or space) with long intervals, it works fine. Short ones will make "pressed" be printed twice.

```
var undo := UndoRedo.new()

func _input(event: InputEvent) -> void:
	if not event.is_action_pressed("ui_accept"):
		return
	
	undo.create_action("action", UndoRedo.MERGE_ALL)
	undo.add_do_method(self, "test")
	undo.commit_action()

func test() -> void:
	print("pressed")
```

**Comment by groud** [comment]
Are you sure you do not receive 2 input events ?

**Comment by YeldhamDev** [comment]
@groud Nope, if you put `print("event")` after the conditional with the `return`, there will be only one "event" followed by two "pressed"s.

**Comment by YeldhamDev** [comment]
@ground Found the source of the problem:
https://github.com/godotengine/godot/blob/8fd2eb6234541dfb34800f7ef4b0350c5795bb67/core/undo_redo.cpp#L66
A lower tick gap makes the operations work correctly, but I don't how if affects everything else, or if lowering the gap is even the right approach.

**Comment by akien-mga** [comment]
Reopening as #26129 was reverted by #26280.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3

**Comment by Lucrecious** [comment]
Any simple workarounds for this?

**Comment by lincore81** [comment]
Sorry to bother, but is there something like a fix in sight? I suppose I could implement custom undo-redo functionality in the meantime.

**Comment by TheSofox** [comment]
Added a Pull Request that fixes this issue.

I had a bit of trouble understanding this system in the first place. I think some better documentation (and maybe some unit tests) are in order.

In the meantime, have this chart I quickly put together to make sure I understood what I was dealing with:
![image](https://github.com/godotengine/godot/assets/3089525/86d01a96-4b74-48cf-9145-687e95b7d39d)
