### ISSUE TITLE
Multiple HTTPRequests for different images at the same time on HTML5 returns the last image requested

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#26112]
**Godot version:** Godot 3.1 beta 5

**OS/device including version:** Windows 10 - Chrome

**Issue description:**

When requesting multiple images using multiple `HTTPRequest`s at the same time, receives the same image data from all `HTTPRequest`s which is the last image requested.
This doesn't happen on Windows platform.

Windows:
![image](https://user-images.githubusercontent.com/12462089/53162483-b1a72f80-35fe-11e9-84cf-199bca6f712a.png)

HTML5: 
![image](https://user-images.githubusercontent.com/12462089/53162468-a8b65e00-35fe-11e9-9ee5-e4d440576650.png)

**Minimal reproduction project:**

Just making sure if this is a bug or just another limitation (like threading/blocking mode) of the HTML5 platform before I create a minimal project.

**Comment by akien-mga** [comment]
CC @eska014 @Faless

**Comment by Faless** [comment]
@DleanJeans there shouldn't be any limitation like that, feel free to provide a minimum reproduction project.

**Comment by DleanJeans** [comment]
This is weird! The minimal scene I created has no problems in a standalone project but inside my current project.
Dunno what hidden settings/code might be causing this.

**Comment by Faless** [comment]
Seems stale, closing.
