### ISSUE TITLE
Loading a project brings to an empty scene

### ISSUE THREAD

**Issue by ricpelo** [godotengine/godot#2611]
Using latest HEAD (commit 52cc8e), when I open any demo project from the Project List window, Godot shows an empty scene. However, if I run the project (F5), it works OK.

**Comment by okamstudio** [comment]
checking..

On Sat, Oct 17, 2015 at 12:05 PM, Ricardo Pérez <notifications@github.com>
wrote:

> Using latest HEAD (commit 52cc8e), when I try to edit any demo scene,
> Godot shows an empty scene. However, if I run the project (F5), it works OK.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2611>.
>



-- 

*OkamStudio*

**Comment by ricpelo** [comment]
When I open a scene for editing, I can see these messages in the console:

```
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:500.
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:500.
bind toptions
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:500.
```

**Comment by ricpelo** [comment]
Very sorry: when I said "demo scene" I mean "demo project", i.e., when I open any demo project from the Project List window, Godot shows an empty scene.

**Comment by firefly2442** [comment]
I tried running git bisect to find the problem but I had to skip the ones that didn't build:

```
The first bad commit could be any of:
13d2710fedf0cc949ffe59b64f0ebd9c1874cbfb
7060eaaa1be64f45fc9f9a56ee305e040654b43b
b217e1417aff2654282fc3c75b10159683b74a50
4a6bd7844af749739d5603d2bd01ea3b267c16d4
1d800a681b0837503b4b6f5860da9e68364018a0
4a8bc25f18083c7b963ab42911c55856eededf16
0d2b28377f1257af039c088f30c11aa0d12cc695
5a14b89c32dbbba6d74ebcf55ea046e367519e74
40f8b1d2eac4d8fe4846989c9765e9e267e9f896
e1e04c1dd5f577e2bf9957d9524237f42c26d822
b411f8f732db71c5e259a19a3bbd7723d9ab6d54
1028ab9d8101fef197cfcd4cf83ef4be320dc540
1b5622fb9b4b3c40f6841b60087498741adadbe4
5cc145904a6cb38647bfb4de1fac701157375c69
9d540afd1cd3eeb7cc318d2761bae778d32218be
0e60b959cd19e6971ee19851a340c13d28f228c1
17fbd2067385aa3bcbfd676192cb57a9735596cf
1d45c9a04c4c755843a162b872e59680fcb9c94d
2a90186a8e07ef280e438788802a01c5976e57fb
32b52e80411d5bf23fc6add0a5ec67a24690c847
3c466afb68eeca60f09950680d7eec58471b6882
4210d5e4594fcf80bc121bccc916d411663d02bc
692216b86ab97db91e7ff3903ffc9ac8e37433f6
867c95223d0e972b88aa26a3d8dc40530b02f09b
930cb97c7d5e1bd4946564c97ea636ca3ed81963
afbb6c064c88d743d8a7d04b5dbfb4b0b1b2db7f
c9ff40e1400c6351c57ec3c5734bc638ee42f3b7
d9583f8a7283bbeac1dceaf0885bba297961432e
dabb9f5982c8cb413d5ae4aaf88ec65faffe01a7
e8223a90e43fe6315c8f45ce914cab0b6ae6923b
f0119c2e3c0ddb19cef1fdf6cfebb6697dabd14d
c2515d352ed9324ec017ff29882d30bc0b3a5a0d
```

**Comment by firefly2442** [comment]
After looking through those, these are the ones I would check first:

```
17fbd2067385aa3bcbfd676192cb57a9735596cf
1d45c9a04c4c755843a162b872e59680fcb9c94d
930cb97c7d5e1bd4946564c97ea636ca3ed81963
afbb6c064c88d743d8a7d04b5dbfb4b0b1b2db7f
d9583f8a7283bbeac1dceaf0885bba297961432e
```

**Comment by ricpelo** [comment]
@firefly2442 , any news about this issue? Thanks.

**Comment by ricpelo** [comment]
@StraToN , could you bring us some light about this issue? Thanks!

**Comment by StraToN** [comment]
I confirm the issue, but this doesn't happen in my branch that was merged for #2380 (https://github.com/okamstudio/godot/compare/master...StraToN:tabs-buttons). I think it is related to something else. Still investigating.

**Comment by firefly2442** [comment]
@ricpelo, No sorry, it's still broken for me.  I'm guessing it's related to that error message though.  I'll try to look more later today.

**Comment by ricpelo** [comment]
Thank you very much to all of you :)

**Comment by firefly2442** [comment]
I found more information regarding this error message (not sure if it's related to the issue but it's a good starting point):

```
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:500.
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:500.
bind toptions
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:500.
```

https://github.com/okamstudio/godot/blob/master/tools/editor/property_editor.cpp#L2355

In `property_editor.cpp`, it's calling `get_edited_scene()`which is defined straight in the `editor_node.h` file inline.  This then calls `get_edited_scene_root()` resulting in the error message.  I think that call to `get_edited_scene()` on that line in `property_editor.cpp` needs an additional check?  Or maybe `PropertyEditor::update_tree()` needs to be called later on in some initialization setup?

I'm going to guess this error message is stemming from this commit: 422929e87fbe91be1efedf1fe3a9a71d61e58b40 perhaps?

**Comment by firefly2442** [comment]
So this commit fixes the error message about `get_edited_scene_root`, but I haven't really tested it.

https://github.com/firefly2442/godot/commit/2b4d089564496354cde4cc751e3fa846e5a4c8ff

I didn't create a pull request yet because I wanted to get some input from you folks about it.  Should the check for a valid scene node be done here or someplace else?

No luck on fixing the empty scenes yet...

**Comment by akien-mga** [comment]
Ran a git bisect and found:
```
692216b86ab97db91e7ff3903ffc9ac8e37433f6 is the first bad commit
commit 692216b86ab97db91e7ff3903ffc9ac8e37433f6
Author: firefly2442 <firefly2442@gmail.com>
Date:   Wed Sep 16 15:51:19 2015 -0500

    ran cppcheck, fixed cases where array index is used before limits check

:040000 040000 1827a8aba2c41aadffd4594810d7696224b96345 d89ea5ea6ff471ec91aab0d748e14bbd9c4f4ff9 M      main
:040000 040000 bd551e1329603049322c510f2989e7af2f93c5b7 57be9100347d30ef6e50e3c9ceea043819593a51 M      scene
```

**Comment by akien-mga** [comment]
Actually the git bisect was correct, 692216b introduced at least two bugs. I'll make a PR.

**Comment by firefly2442** [comment]
@akien-mga Thank you, sorry for introducing the bug!

**Comment by akien-mga** [comment]
@firefly2442 You're welcome, you did a nice job to help narrow it down :) Note that I did not really check if my PR also addresses the ```get_edited_scene_root``` error, you might want to have a look.

**Comment by firefly2442** [comment]
@akien-mga I cherry-picked your PR and tried it against the master and unfortunately it doesn't fix the `get_edited_scene_root` problem.  I've created a separate issue for it here: #2731.

**Comment by AlexHolly** [comment]
I get this message when I open a project and go to "Scene -> open scene -> open a random scene of the project".

ERROR: set_current_tab: Index p_current out of size (get_tab_count()).
   At: scene/gui/tabs.cpp:500.
settings changed

master branch 
Ubuntu 14.04
