### ISSUE TITLE
C# macOS DMG export doesn't seem to work

### ISSUE THREAD

**Issue by Bombfuse** [godotengine/godot#26126]
**Godot version:**
3.1 Mono beta 5

**OS/device including version:**
Mac Mojave

**Issue description:**
MacOS exports fail, while windows and linux exports succeed.
<img width="898" alt="image" src="https://user-images.githubusercontent.com/26308406/53191482-c4027880-35c0-11e9-9ab3-73702c077f81.png">

**Steps to reproduce:**
Start a new project, attempt to export to MacOS.

**Minimal reproduction project:**

[bug_repro.zip](https://github.com/godotengine/godot/files/2890530/bug_repro.zip)

**Comment by akien-mga** [comment]
Are you sure that it's not just because you did not type the application name and identifier, which are likely mandatory for generating the macOS app?

That error message is misleading (I'm improving it in #26150), and the lack of preset config validation is tracked in #23172.

**Comment by Bombfuse** [comment]
It's definitely possible that could be the issue, I'll test it out today and get back to you

**Comment by Bombfuse** [comment]
Bug appears to exist even with the app name and signature + identifier
<img width="924" alt="image" src="https://user-images.githubusercontent.com/26308406/53256294-5c116800-367c-11e9-9b2d-8bf1912da6bd.png">

**Comment by Bombfuse** [comment]
Still exists on beta 6 as well

**Comment by akien-mga** [comment]
Is anything printed in a terminal?

**Comment by Bombfuse** [comment]
This is what's printed in the terminal at export
<img width="973" alt="image" src="https://user-images.githubusercontent.com/26308406/53355828-cd505580-38de-11e9-854a-b0b7ed382131.png">

**Comment by neikeq** [comment]
I cannot reproduce with beta6 nor with beta10 on macOS Mojave.

**Comment by neikeq** [comment]
Also since the error is outside the mono module, I wonder if this is actually a Godot issue in general.

**Comment by akien-mga** [comment]
@Bombfuse Does the export path configured in your preset actually exist? Can you try with a new preset, to rule out any configuration issue?

**Comment by Bombfuse** [comment]
I think there may be something wrong with my MacbookPro, I've tried multiple configs with no success.

**Comment by neikeq** [comment]
#26626 makes me think it could be the export path field who is causing thd problem. Can you clear it and see if it works?

**Comment by Bombfuse** [comment]
Where should I have the export path point to?

**Comment by Bombfuse** [comment]
Also, the windows and linux exports work with the export path set.

**Comment by neikeq** [comment]
In my test I left that field empty.

**Comment by Bombfuse** [comment]
Just tested with export path empty and it still doesn't work. I think there might just be something wrong with my laptop

**Comment by comfort-stereo** [comment]
I am having the same issue with Godot 3.1 beta 10. Filling the name, identifier and icon fields does not seem to help. Occurs with both 'Export With Debug' checked or unchecked.

**Comment by Bombfuse** [comment]
Just exported the same project i was having issues with from a Windows 10 machine to MacOS. It seems to be a problem where MacOS can't export to MacOS?

**Comment by comfort-stereo** [comment]
Just tested this in a non-mono project (still using a mono build on OSX), export fails in the same way.

**Comment by Bombfuse** [comment]
This is still occurring on the latest release of Godot Mono

**Comment by neikeq** [comment]
The error message was updated recently. This is a new screenshot from @Bombfuse 

![image](https://user-images.githubusercontent.com/7718100/56154104-0db38200-5fb8-11e9-939a-d82260869a92.png)

It would be great if the error message was more detailed, or that the details were logged in the terminal. Otherwise we can't know what's going wrong.

**Comment by fadexmusic** [comment]
I have the same issue, really frustrated by this. I have created a blank project, added a C# script and tried to export from both MacOSX Mojave and Windows 10. 

![Screenshot 2019-04-30 at 03 22 47](https://user-images.githubusercontent.com/6191873/56936413-96bdd380-6af7-11e9-89f1-0401df65bd55.png)
![Screenshot 2019-04-28 at 23 55 43](https://user-images.githubusercontent.com/6191873/56936418-9c1b1e00-6af7-11e9-9a83-fc0fb3ca65f7.png)
![Screenshot 2019-04-29 at 00 45 04](https://user-images.githubusercontent.com/6191873/56936421-a210ff00-6af7-11e9-993a-6a77ff703350.png)

**Comment by Bombfuse** [comment]
I only have issues when exporting to MacOS from MacOS. But this seems to be a pretty big issue of the exports aren't working.

**Comment by fadexmusic** [comment]
I found out that if you export to zip (when choosing the file name and either .dmg or .zip) it works.

**Comment by Bombfuse** [comment]
Just tried it and confirmed this works. Still confused as to why .zip works and .dmg doesn't though. I'll leave it up to @neikeq whether he wants to close this issue for now.

**Comment by MMichael789** [comment]
Yep same thing right now for me on OSX with 3.1.1 stable. I mean I could make my own disk image if I want anyways, but weird stuff.

**Comment by Calinou** [comment]
Can anyone still reproduce this on [Godot 3.2 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4)?

**Comment by akien-mga** [comment]
CC @G4MR who was doing some extensive testing of templates with 3.2 beta 4 - does this bug report fit your findings on macOS?

**Comment by exts** [comment]
@akien-mga I will test dmg exports, I've only tested zip exports. Give me an hour or two and I'll have the results

**Comment by exts** [comment]
<img width="653" alt="Screen Shot 2020-01-02 at 8 01 52 AM" src="https://user-images.githubusercontent.com/16387107/71670690-51147300-2d36-11ea-86d6-22ac32887ce4.png">

@akien-mga just learned you can only export dmg on mac, but anyways after testing on my macbook pro 2019 (catalina I get that error).

Another issue I get is if you select 'dmg' from the drop down, it inserts `mac osx export` into the filename field.

**Comment by exts** [comment]
Still an issue with beta5 also.

**Comment by akien-mga** [comment]
CC @bruvzg in case you have an idea about what causes this issue in the export process.

**Comment by bruvzg** [comment]
I can confirm this.

- `DMG` export is not creating mono subfolders (`/data.mono.osx.64.release/Mono/lib/`, etc) when extracting source ZIP to the temp folder and fails on extracting files in it.
- `ZIP` export is adding files to the copy of source ZIP with all files already in place.

**Comment by akien-mga** [comment]
@neikeq See above comment.
