### ISSUE TITLE
Recent area optimization commit causes massive FPS swings.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#26149]
**Godot version:**
v3.1.beta.calinou.8b231b9

**OS/device including version:**
Win10 64 bit, Ryzen 2700X processor, GTX 1060 6gb GPU.

**Issue description:**
Massive FPS swings in complex levels within this project of mine (because of physics checks).
http://www.mediafire.com/file/96cv304s5mw9w26/Collect_The_Gems%25280.13%2529.zip/file

Based on experience, it's due to physics-related stuff, so my guess is this patch merged by Akien.
https://github.com/godotengine/godot/commit/ced77db950118f2a33cab5271204cf56b39774e4

**Steps to reproduce:**
Open the project in Godot and press 'shift ~' to go to the level where the issues are most acute. This happens in builds done at commit 8b231b9. FPS sees major swings between 7 and 60.

Open the project again in a Godot build done at commit 16934c7, go to the same level. Notice how buttery smooth the FPS is, a near-constant 60.

**Minimal reproduction project:**
Already posted, sorry it's the whole game, but this type of thing can't be reproduced with simple scenes.

**Comment by slapin** [comment]
I confirm the area bug, but I tried to use movable areas and it was even worse result.

**Comment by akien-mga** [comment]
For anyone testing the upcoming 3.1 beta 6: this bug will still be valid in beta 6, which has been built from a comment prior to #26153.
