### ISSUE TITLE
Android unusable when script attached to scene

### ISSUE THREAD

**Issue by mikeKulasinski** [godotengine/godot#26143]
**Godot version:**
3.1.beta [8b231b9] master

**OS/device including version:**
Android 9.0 Pixel 2

**Issue description:**
When exporting a project with a script attached to scene android does not launch, and android logcat prints a lot of errors that resource could not be loaded

**Steps to reproduce:**
Create new project
Add Scene
Select 2D node
Attach Script 
Run on Android

**Minimal reproduction project:**
[oneSceneAndScript.zip](https://github.com/godotengine/godot/files/2892001/oneSceneAndScript.zip)

> 2019-02-22 02:21:38.187 11996-11996/? I/com.test: Late-enabling -Xcheck:jni
2019-02-22 02:21:38.392 11996-12019/? D/libEGL: loaded /vendor/lib64/egl/libEGL_adreno.so
2019-02-22 02:21:38.401 11996-11996/? W/com.test: type=1400 audit(0.0:1045): avc: denied { read } for comm=45474C20496E6974 name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16298 scontext=u:r:untrusted_app:s0:c155,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2019-02-22 02:21:38.403 11996-12019/? E/libc: Access denied finding property "vendor.debug.egl.profiler"
2019-02-22 02:21:38.404 11996-12019/? D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_adreno.so
2019-02-22 02:21:38.417 11996-12019/? D/libEGL: loaded /vendor/lib64/egl/libGLESv2_adreno.so
2019-02-22 02:21:38.514 11996-11996/? D/OpenGLRenderer: Skia GL Pipeline
2019-02-22 02:21:38.560 11996-12022/? I/Adreno: QUALCOMM build                   : 6fb5a5b, Ife855c4895
    Build Date                       : 08/21/18
    OpenGL ES Shader Compiler Version: EV031.25.00.00
    Local Branch                     : Googledrop_0815
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2019-02-22 02:21:38.560 11996-12022/? I/Adreno: Build Config                     : S L 4.0.10 AArch64
2019-02-22 02:21:38.564 11996-12022/? I/Adreno: PFP: 0x005ff110, ME: 0x005ff066
2019-02-22 02:21:38.566 11996-12022/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
2019-02-22 02:21:38.567 11996-12022/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2019-02-22 02:21:38.567 11996-12022/? I/OpenGLRenderer: Initialized EGL, version 1.4
2019-02-22 02:21:38.567 11996-12022/? D/OpenGLRenderer: Swap behavior 1
2019-02-22 02:21:38.572 11996-12021/? I/godot: Android modules: Nothing to load, aborting
2019-02-22 02:21:38.574 11996-12021/? W/GodotView: creating OpenGL ES 3.0 context :
2019-02-22 02:21:38.587 11996-12021/? I/godot: OpenGL ES 3.0 Renderer: Adreno (TM) 540
2019-02-22 02:21:38.616 11996-12021/? I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
2019-02-22 02:21:38.619 11996-12021/? W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 1772
2019-02-22 02:21:38.909 11996-12021/? E/godot: **SCRIPT ERROR**: Parse Error: Expected '(' after identifier (syntax: 'func <identifier>([arguments]):' ).
2019-02-22 02:21:38.909 11996-12021/? E/godot:    At: res://Node2D.gdc:2:GDScript::load_byte_code() - Parse Error: Expected '(' after identifier (syntax: 'func <identifier>([arguments]):' ).
2019-02-22 02:21:38.909 11996-12021/? E/godot: **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
2019-02-22 02:21:38.909 11996-12021/? E/godot:    At: modules/gdscript/gdscript.cpp:778:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
2019-02-22 02:21:38.909 11996-12021/? E/godot: **ERROR**: Condition ' err != OK ' is true. returned: RES()
2019-02-22 02:21:38.909 11996-12021/? E/godot:    At: modules/gdscript/gdscript.cpp:2142:load() - Condition ' err != OK ' is true. returned: RES()
2019-02-22 02:21:38.909 11996-12021/? E/godot: **ERROR**: Failed loading resource: res://Node2D.gdc
2019-02-22 02:21:38.909 11996-12021/? E/godot:    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
2019-02-22 02:21:38.909 11996-12021/? E/godot: **ERROR**: res://Node2D.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Node2D.gd
2019-02-22 02:21:38.909 11996-12021/? E/godot:    At: scene/resources/scene_format_text.cpp:439:poll() - res://Node2D.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Node2D.gd
2019-02-22 02:21:38.909 11996-12021/? E/godot: **ERROR**: Condition ' err != OK ' is true. returned: RES()
2019-02-22 02:21:38.909 11996-12021/? E/godot:    At: core/io/resource_loader.cpp:202:load() - Condition ' err != OK ' is true. returned: RES()
2019-02-22 02:21:38.909 11996-12021/? E/godot: **ERROR**: Failed loading resource: res://Node2D.tscn
2019-02-22 02:21:38.909 11996-12021/? E/godot:    At: core/io/resource_loader.cpp:279:_load() - Method/Function Failed, returning: RES()
2019-02-22 02:21:38.909 11996-12021/? E/godot: **ERROR**: Failed loading scene: res://Node2D.tscn

**Comment by Zireael07** [comment]
Does it work when exported to the PC? Do you have the correct (i.e. self-compiled) export templates?

**Comment by mikeKulasinski** [comment]
Yes I have compiled Android templates as well as Linux templates.

It works on Linux.

Although Android templates I compile using clang.

**Comment by mikeKulasinski** [comment]
scons platform=android tools=no target=release_debug use_llvm=yes -j 8

then i move templates to 
mv bin/android_debug.apk ~/.local/share/godot/templates/3.1.beta/android_debug.apk
mv bin/android_release.apk ~/.local/share/godot/templates/3.1.beta/android_release.apk

**Comment by mikeKulasinski** [comment]
I rebuild templates without llvm and it is the same problem

**Comment by mikeKulasinski** [comment]
I am adding log from godot ide when it exports to android and tries to run

`$ ADDING: AndroidManifest.xml
ADDING: classes.dex
ADDING: lib/arm64-v8a/libc++_shared.so
ADDING: lib/arm64-v8a/libgodot_android.so
ADDING: lib/armeabi-v7a/libc++_shared.so
ADDING: lib/armeabi-v7a/libgodot_android.so
ADDING: res/drawable-hdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-hdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-mdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-mdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-nodpi-v4/icon.png
ADDING: res/drawable-v21/notification_action_background.xml
ADDING: res/drawable-xhdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-xhdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-xxhdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable/notification_bg.xml
ADDING: res/drawable/notification_bg_low.xml
ADDING: res/drawable/notification_icon_background.xml
ADDING: res/drawable/notification_tile_bg.xml
ADDING: res/layout-v16/notification_template_custom_big.xml
ADDING: res/layout-v21/notification_action.xml
ADDING: res/layout-v21/notification_action_tombstone.xml
ADDING: res/layout-v21/notification_template_custom_big.xml
ADDING: res/layout-v21/notification_template_icon_group.xml
ADDING: res/layout/downloading_expansion.xml
ADDING: res/layout/notification_action.xml
ADDING: res/layout/notification_action_tombstone.xml
ADDING: res/layout/notification_template_icon_group.xml
ADDING: res/layout/notification_template_part_chronometer.xml
ADDING: res/layout/notification_template_part_time.xml
ADDING: res/layout/status_bar_ongoing_event_progress_bar.xml
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: no space left
ADDING: resources.arsc
0 param: --use_depth_32
1 param: --use_immersive
   adding: META-INF/MANIFEST.MF
   adding: META-INF/ANDROIDD.SF
   adding: META-INF/ANDROIDD.RSA
  signing: AndroidManifest.xml
  signing: classes.dex
  signing: lib/arm64-v8a/libc++_shared.so
  signing: lib/arm64-v8a/libgodot_android.so
  signing: lib/armeabi-v7a/libc++_shared.so
  signing: lib/armeabi-v7a/libgodot_android.so
  signing: res/drawable-hdpi-v4/notification_bg_low_normal.9.png
  signing: res/drawable-hdpi-v4/notification_bg_low_pressed.9.png
  signing: res/drawable-hdpi-v4/notification_bg_normal.9.png
  signing: res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png
  signing: res/drawable-hdpi-v4/notify_panel_notification_icon_bg.png
  signing: res/drawable-mdpi-v4/notification_bg_low_normal.9.png
  signing: res/drawable-mdpi-v4/notification_bg_low_pressed.9.png
  signing: res/drawable-mdpi-v4/notification_bg_normal.9.png
  signing: res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png
  signing: res/drawable-mdpi-v4/notify_panel_notification_icon_bg.png
  signing: res/drawable-nodpi-v4/icon.png
  signing: res/drawable-v21/notification_action_background.xml
  signing: res/drawable-xhdpi-v4/notification_bg_low_normal.9.png
  signing: res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png
  signing: res/drawable-xhdpi-v4/notification_bg_normal.9.png
  signing: res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png
  signing: res/drawable-xhdpi-v4/notify_panel_notification_icon_bg.png
  signing: res/drawable-xxhdpi-v4/notify_panel_notification_icon_bg.png
  signing: res/drawable/notification_bg.xml
  signing: res/drawable/notification_bg_low.xml
  signing: res/drawable/notification_icon_background.xml
  signing: res/drawable/notification_tile_bg.xml
  signing: res/layout-v16/notification_template_custom_big.xml
  signing: res/layout-v21/notification_action.xml
  signing: res/layout-v21/notification_action_tombstone.xml
  signing: res/layout-v21/notification_template_custom_big.xml
  signing: res/layout-v21/notification_template_icon_group.xml
  signing: res/layout/downloading_expansion.xml
  signing: res/layout/notification_action.xml
  signing: res/layout/notification_action_tombstone.xml
  signing: res/layout/notification_template_icon_group.xml
  signing: res/layout/notification_template_part_chronometer.xml
  signing: res/layout/notification_template_part_time.xml
  signing: res/layout/status_bar_ongoing_event_progress_bar.xml
  signing: resources.arsc
  signing: assets/Node2D.gdc
  signing: assets/Node2D.tscn
  signing: assets/default_env.tres
  signing: assets/.import/icon.png-487276ed1e3a0c39cad0279d744ee560.stex
  signing: assets/icon.png.import
  signing: assets/Node2D.gd.remap
  signing: assets/icon.png
  signing: assets/project.binary
  signing: assets/_cl_
jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2042-03-08) or after any future revocation date.

s k     5713 Fri Feb 22 09:38:04 CET 2019 META-INF/MANIFEST.MF
        5875 Fri Feb 22 09:38:04 CET 2019 META-INF/ANDROIDD.SF
         784 Fri Feb 22 09:38:04 CET 2019 META-INF/ANDROIDD.RSA
smk     3204 Fri Mar 22 09:37:58 CET 2019 AndroidManifest.xml
smk   1009548 Fri Mar 22 09:37:58 CET 2019 classes.dex
smk   985464 Fri Mar 22 09:38:00 CET 2019 lib/arm64-v8a/libc++_shared.so
smk   35836256 Fri Mar 22 09:38:00 CET 2019 lib/arm64-v8a/libgodot_android.so
smk   575328 Fri Mar 22 09:38:00 CET 2019 lib/armeabi-v7a/libc++_shared.so
smk   36766788 Fri Mar 22 09:38:00 CET 2019 lib/armeabi-v7a/libgodot_android.so
smk      212 Fri Mar 22 09:38:02 CET 2019 res/drawable-hdpi-v4/notification_bg_low_normal.9.png
smk      225 Fri Mar 22 09:38:02 CET 2019 res/drawable-hdpi-v4/notification_bg_low_pressed.9.png
smk      212 Fri Mar 22 09:38:02 CET 2019 res/drawable-hdpi-v4/notification_bg_normal.9.png
smk      225 Fri Mar 22 09:38:02 CET 2019 res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png
smk     1843 Fri Mar 22 09:38:02 CET 2019 res/drawable-hdpi-v4/notify_panel_notification_icon_bg.png
smk      215 Fri Mar 22 09:38:02 CET 2019 res/drawable-mdpi-v4/notification_bg_low_normal.9.png
smk      223 Fri Mar 22 09:38:02 CET 2019 res/drawable-mdpi-v4/notification_bg_low_pressed.9.png
smk      215 Fri Mar 22 09:38:02 CET 2019 res/drawable-mdpi-v4/notification_bg_normal.9.png
smk      223 Fri Mar 22 09:38:02 CET 2019 res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png
smk      718 Fri Mar 22 09:38:02 CET 2019 res/drawable-mdpi-v4/notify_panel_notification_icon_bg.png
smk     3433 Fri Mar 22 09:38:02 CET 2019 res/drawable-nodpi-v4/icon.png
smk     1180 Fri Mar 22 09:38:02 CET 2019 res/drawable-v21/notification_action_background.xml
smk      221 Fri Mar 22 09:38:02 CET 2019 res/drawable-xhdpi-v4/notification_bg_low_normal.9.png
smk      252 Fri Mar 22 09:38:02 CET 2019 res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png
smk      221 Fri Mar 22 09:38:02 CET 2019 res/drawable-xhdpi-v4/notification_bg_normal.9.png
smk      247 Fri Mar 22 09:38:02 CET 2019 res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png
smk      462 Fri Mar 22 09:38:02 CET 2019 res/drawable-xhdpi-v4/notify_panel_notification_icon_bg.png
smk     2830 Fri Mar 22 09:38:02 CET 2019 res/drawable-xxhdpi-v4/notify_panel_notification_icon_bg.png
smk      532 Fri Mar 22 09:38:02 CET 2019 res/drawable/notification_bg.xml
smk      532 Fri Mar 22 09:38:02 CET 2019 res/drawable/notification_bg_low.xml
smk      372 Fri Mar 22 09:38:02 CET 2019 res/drawable/notification_icon_background.xml
smk      304 Fri Mar 22 09:38:02 CET 2019 res/drawable/notification_tile_bg.xml
smk     3208 Fri Mar 22 09:38:02 CET 2019 res/layout-v16/notification_template_custom_big.xml
smk     1052 Fri Mar 22 09:38:02 CET 2019 res/layout-v21/notification_action.xml
smk     1228 Fri Mar 22 09:38:02 CET 2019 res/layout-v21/notification_action_tombstone.xml
smk     2456 Fri Mar 22 09:38:02 CET 2019 res/layout-v21/notification_template_custom_big.xml
smk      988 Fri Mar 22 09:38:02 CET 2019 res/layout-v21/notification_template_icon_group.xml
smk     4276 Fri Mar 22 09:38:02 CET 2019 res/layout/downloading_expansion.xml
smk     1156 Fri Mar 22 09:38:02 CET 2019 res/layout/notification_action.xml
smk     1332 Fri Mar 22 09:38:02 CET 2019 res/layout/notification_action_tombstone.xml
smk      392 Fri Mar 22 09:38:02 CET 2019 res/layout/notification_template_icon_group.xml
smk      440 Fri Mar 22 09:38:02 CET 2019 res/layout/notification_template_part_chronometer.xml
smk      440 Fri Mar 22 09:38:02 CET 2019 res/layout/notification_template_part_time.xml
smk     2612 Fri Mar 22 09:38:02 CET 2019 res/layout/status_bar_ongoing_event_progress_bar.xml
smk    42768 Fri Mar 22 09:38:02 CET 2019 resources.arsc
smk      223 Fri Mar 22 09:38:02 CET 2019 assets/Node2D.gdc
smk      154 Fri Mar 22 09:38:02 CET 2019 assets/Node2D.tscn
smk      164 Fri Mar 22 09:38:02 CET 2019 assets/default_env.tres
smk     3480 Fri Mar 22 09:38:02 CET 2019 assets/.import/icon.png-487276ed1e3a0c39cad0279d744ee560.stex
smk      605 Fri Mar 22 09:38:02 CET 2019 assets/icon.png.import
smk       33 Fri Mar 22 09:38:02 CET 2019 assets/Node2D.gd.remap
smk     3433 Fri Mar 22 09:38:02 CET 2019 assets/icon.png
smk      401 Fri Mar 22 09:38:02 CET 2019 assets/project.binary
smk       41 Fri Mar 22 09:38:02 CET 2019 assets/_cl_

  s = signature was verified 
  m = entry is listed in manifest
  k = at least one certificate was found in keystore
  i = at least one certificate was found in identity scope

jar verified.

Warning: 
This jar contains signatures that does not include a timestamp. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2042-03-08) or after any future revocation date.

Re-run with the -verbose and -certs options for more details.
Uninstalling previous version: Google Pixel 2
Success
Installing to device (please wait...): Google Pixel 2
Success
Starting: Intent { act=android.intent.action.MAIN cmp=com.test.simple.app/org.godotengine.godot.Godot }
`

**Comment by volzhs** [comment]
did you do `gradlw bulid` also?

**Comment by mikeKulasinski** [comment]
yes i did

**Comment by henkz1** [comment]
I think you also need to build the arm64 binaries, android_arch=arm64v8, then run gradle again

**Comment by mikeKulasinski** [comment]
I did that too. Also checked that Android APK has it in libs

**Comment by akien-mga** [comment]
I just tested with your project on my Samsung Galaxy S3, with both editor (Linux) and Android debug template built from 996af809, and I have no issue, the project does not crash.

The errors that you reported are very common when you do have a discrepancy between the editor version and the Android template version, so I would recommend that you triple check that you are building both from the same commit, and that you are using the correct template for export.

**Comment by mikeKulasinski** [comment]
Ok looks like i found a guilty one, reason why you didnt see it at all is that you didnt have to specify android_arch, since s3 is an old device it was using the default value. I needed arm64v8, however I spelled it like "arm64-v8" and in platform/android/detect.py you have 

`if env['android_arch'] not in ['armv7', 'armv6', 'arm64v8', 'x86', 'x86_64']:
        env['android_arch'] = 'armv7'
`

which i think it should fail the build and ask for correct in case android_arch is specified and not in the list provided, since its ultra hard to find a bug otherwise

**Comment by mikeKulasinski** [comment]
I think we should be consistent with Android naming conventions

https://developer.android.com/ndk/guides/cmake

check for arm64-v8a

**Comment by mikeKulasinski** [comment]
I would be great if you @akien-mga also could confirm if exporting to android via command line works for you. I cant get it work for last couple weeks 

I run following from the project i send here eariler

opt/godot/godot --path . --export-debug Android x.apk

and x.apk is not created

**Comment by Calinou** [comment]
@mikeKulasinski Can you reproduce this on [3.2 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4) or the `master` branch?

**Comment by mikeKulasinski** [comment]
To be honest I don't have the project anymore so I can't check

**Comment by Calinou** [comment]
I'll close this then. It seems the original issue was related to mismatched editor and export template versions.
