### ISSUE TITLE
get_viewport().get_texture() returns flipped texture

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#26141]
**Godot version:**
3.1 beta 5

**OS/device including version:**
Windows 10

**Issue description:**
`get_viewport().get_texture().` returns a flipped texture.

**Steps to reproduce:**
`get_node("Sprite").set_texture(get_viewport().get_texture())`

**Minimal reproduction project:**
just an emply project with an empty sprite and a background

**Comment by avencherus** [comment]
Not sure why it is provided that way.  Given the discussions (https://github.com/godotengine/godot/issues/15976), it seems to be something to be accounted for using `flip_y()` on the texture data.

**Comment by burstina** [comment]
Using flip_y could be a workaround for sure, until somebody will fix it... and then people will need to correct the code bacwards ;)

**Comment by Zylann** [comment]
Alternatively, there is also a flag on `Viewport` which makes it render flipped as well.
