### ISSUE TITLE
Broken position on InputEventMouse* event passed from moving child Control with MOUSE_FILTER_PASS

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot#26142]
**Godot version:**
 3.1 beta 5

**OS/device including version:**
X11 64 bits

**Issue description:**
Calculation of `global_position` and `position` in the InputEventMouse subclasses is broken when the event is passed from an offset child Control.

Note: `assert(abs((event.global_position - get_global_mouse_position()).length()) < 10)` also fails.

The problem is that event.position has the position relative to the child control that passed the event, and not to the control thats calling `_gui_event`. And it looks like global_position is being calculated from that, because the above assert is also failing.

In fact, you dont even have to click on the intersection of the two controls to trigger the error.

**Steps to reproduce:**
Open MRP, move the mouse and click on the bigger transparent white square.
[MRP.zip](https://github.com/godotengine/godot/files/2891844/MRP.zip)

**Comment by jabcross** [comment]
Note: `assert(abs((event.global_position - get_global_mouse_position()).length()) < 10)` also fails.

The problem is that event.position has the position relative to the child control that passed the event, and not to the control thats calling `_gui_event`. And it looks like global_position is being calculated from that, because the above assert is also failing.

**Comment by jahd2602** [comment]
I confirm: The assertion fails when hovering the gray square.
Godot 3.1 beta 7
Windows 10 x64

**Comment by nezvers** [comment]
3.1.1 stable
Control node blocks InputEventMouseMotion to go to _unhandled_input
+
It seems that Control node blocks handled input on HTML5 builds as the _gui_input goes before _input.

**Comment by akien-mga** [comment]
This appears to be fixed in the master branch.

Probably fixed by #31915.
