### ISSUE TITLE
WASAPI Stopped working after trying to use beta5 audio

### ISSUE THREAD

**Issue by securas** [godotengine/godot#26152]
Godot 3.1 beta 5

Windows 10, NVIDIA GTX 1070

I have been using beta 3 and made a working game with it. Audio worked fine.
Today, I tried to use beta 5 audio for the first time. After a quick squeak, audio stopped working.
Not only audio stopped working on beta 5 but also all other versions of godot, down to 2.1.5 (the earliest one I have).

Finally, **all games built with godot** also no longer have working audio on my windows machine.

I assume something broke but cannot imagine godot breaking WASAPI.

Trying to change the audio driver on the project settings crashes godot and can only be reversed by manually editing the project file.

Restarting the corresponding windows services has no effect.

Reinstalling the device driver has no effect.

Command line when starting godot is as below:
![image](https://user-images.githubusercontent.com/2881755/53238206-08366b80-36dc-11e9-861a-6fb912137103.png)

**Comment by securas** [comment]
An additional note, I have disabled the options for exclusive control of the audio device. Unfortunately to no effect.

**Comment by marcelofg55** [comment]
Hi, can you tell me a bit more about your audio setup, what's your Audio Device? What sample rate are you using? And if stereo or 3.1/5.1/7.1? (if you don't know where these settings are check this link: https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/how-to-change-sound-control-panel-settings-in/5a70718b-7ecf-4547-a64a-22efda8da0c2?auth=1)

**Comment by securas** [comment]
Do these screenshots answer your questions?
![image](https://user-images.githubusercontent.com/2881755/53248647-8c4b1c00-36f9-11e9-8e21-58ce7473acd9.png)
![image](https://user-images.githubusercontent.com/2881755/53248663-98cf7480-36f9-11e9-9040-57884a46de10.png)
![image](https://user-images.githubusercontent.com/2881755/53248675-a258dc80-36f9-11e9-8688-7162769ff7c8.png)

**Comment by marcelofg55** [comment]
Can you try setting the sample rate to 44100 Hz and then testing again godot?

**Comment by securas** [comment]
No change, unfortunately.

**Comment by marcelofg55** [comment]
Can you compile with master including the change at #26158 ? If not I can send you a binary

**Comment by securas** [comment]
Sorry... I don't know how to compile... so that binary would help :)

**Comment by marcelofg55** [comment]
Here you go: https://www.dropbox.com/s/sgbkpzymq81n6k5/godot.windows.tools.64.exe.zip?dl=0

**Comment by securas** [comment]
I'm very sorry but the problem persists. I must sleep now but should be back in 5 or 6 hours. After that, I'll be around for more testing. 
Is there any other app that I could use to diagnose WASAPI? I still think that this is not strickly a godot problem but rather some messed up configuration of my windows machine.

![image](https://user-images.githubusercontent.com/2881755/53260471-ec02f080-3714-11e9-888d-82e1e96e19de.png)

**Comment by marcelofg55** [comment]
That error code is: AUDCLNT_E_UNSUPPORTED_FORMAT, which means that your device doesn't supports the selected format, it may be improperly configured or something like that. I suggest that you try with different formats on the Advanced tag on the Device properties.

**Comment by securas** [comment]
Will any of the folks playing my games that happen to have the same
configuration problem I do be unable to listen to audio as well?

**Comment by marcelofg55** [comment]
Only if they are having the exact issue (getting the error AUDCLNT_E_UNSUPPORTED_FORMAT on the WASAPI Initialize function). Do you have any sound at all on your Windows?

**Comment by securas** [comment]
Yes. Everything else is working fine apparently. Even audacity using WASAPI
is fine.

**Comment by securas** [comment]
Are you sure about AUDCLNT_E_UNSUPPORTED_FORMAT. This seems not a failed device but rather a fail to provide exclusive mode (https://docs.microsoft.com/en-us/windows/desktop/api/audioclient/nf-audioclient-iaudioclient-isformatsupported)

Or maybe I'm looking at the wrong thing here...

**Comment by marcelofg55** [comment]
> Yes. Everything else is working fine apparently. Even audacity using WASAPI is fine.

That's strange, did you try testing with Godot other formats on the Advanced tab?

> Are you sure about AUDCLNT_E_UNSUPPORTED_FORMAT. This seems not a failed device but rather a fail to provide exclusive mode (https://docs.microsoft.com/en-us/windows/desktop/api/audioclient/nf-audioclient-iaudioclient-isformatsupported)
> Or maybe I'm looking at the wrong thing here...

We don't use exclusive mode on the driver, only shared mode, so that shouldn't be the problem.

The function we're calling is Initialize (not IsFormatSupported), so this is the page you should read: https://docs.microsoft.com/en-us/windows/desktop/api/audioclient/nf-audioclient-iaudioclient-initialize

Let me send you another build with more debug information... maybe I can figure out the problem that way

**Comment by marcelofg55** [comment]
Here you go: https://www.dropbox.com/s/39f4fpp9nr4jtz3/godot.windows.tools.64.exe_2.zip?dl=0
Let me know the output from the console with this one, thanks!

**Comment by securas** [comment]
Here you go! Thank you so much for all the support!
![image](https://user-images.githubusercontent.com/2881755/53279416-83873400-3753-11e9-8d29-7f1b54210996.png)

**Comment by marcelofg55** [comment]
Is your Audio Device configured with a 7.1 setup?

**Comment by securas** [comment]
I think it's currently disabled because I have only headphones and speakers
![image](https://user-images.githubusercontent.com/2881755/53279467-0c05d480-3754-11e9-8730-0ed38cc2e4f4.png)

**Comment by marcelofg55** [comment]
And if you try to "Configure" the device, is 7.1 selected? Here's the configure screen I mean:
![soundscreen](https://user-images.githubusercontent.com/10578225/53279502-d0d1ba00-36ef-11e9-813f-74a5784d5884.png)

**Comment by securas** [comment]
I ran the configuration wizard without full range. This is the new godot console output
![image](https://user-images.githubusercontent.com/2881755/53279570-f0e79480-3754-11e9-9fec-47b14c33062d.png)

**Comment by marcelofg55** [comment]
Can you try selecting Stereo on the configuration? the godot console should say `WASAPI: nChannels = 2`

**Comment by securas** [comment]
I don't seem to have an option for 7:1... Only stereo which is set...
![image](https://user-images.githubusercontent.com/2881755/53279938-36f22780-3758-11e9-9206-96994ea56db8.png)

**Comment by marcelofg55** [comment]
I really wonder why WASAPI reports 8 channels then...
Does this build reports anything different on the console? https://www.dropbox.com/s/6g3ah3oujaezj0t/godot.windows.tools.64.exe_3.zip?dl=0

**Comment by securas** [comment]
here's the output
![image](https://user-images.githubusercontent.com/2881755/53280031-63f30a00-3759-11e9-87e3-577cd53c5867.png)

**Comment by securas** [comment]
I disabled the alienware audio manager and got this after rebooting:
![image](https://user-images.githubusercontent.com/2881755/53280356-73278700-375c-11e9-8f82-45114d9efd33.png)
It might then be that the crappy alienware audio manager decided to enforce 7+1
Would it make sense to have godot being able to handle 7+1?

**Comment by marcelofg55** [comment]
Oh, I see, can that Alienware Audio Manager be installed anywhere? So I can reproduce the problem myself

**Comment by securas** [comment]
I have no idea... But in principle no... Would it be possible instead just to support 7+1?

**Comment by marcelofg55** [comment]
Here's one last try (at least for today :) ) that should make godot work even with the Alienware Audio Manager on (please re-enable it and try the build with it): https://www.dropbox.com/s/xhdmt6po6rjwbmz/godot.windows.tools.64.exe_4.zip?dl=0

**Comment by marcelofg55** [comment]
> I have no idea... But in principle no... Would it be possible instead just to support 7+1?
7.1 is already supported, I have a 5.1/7.1 USB Sound Card that works as expected using Godot, the problem with your Device (actually with Alienware Audio Manager as you found out) is that if fails to Initialize with the format that GetMixFormats returns.

**Comment by securas** [comment]
Seems to have a different console now... I'll make a short test project to check the audio
![image](https://user-images.githubusercontent.com/2881755/53280762-72ddba80-3761-11e9-8f80-ee4f4704bbad.png)

**Comment by securas** [comment]
It works!

**Comment by marcelofg55** [comment]
Awesome!! Thanks for the help :D

**Comment by securas** [comment]
On the contrary! I'm the one who thanks you for all the support!
