### ISSUE TITLE
AnimationPlayer keyframes hard to select at time 0.0.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#26151]
**Godot version:**

16934c7

**OS/device including version:**

Windows 10 64-bit

**Issue description:**

When a keyframe is at time 0.0 it is very troublesome to select.  It seems that the left half of is no longer available to click events, and the click event is being captured elsewhere.

Red rectangle in the screenshot indicates the deadzone.
![image](https://user-images.githubusercontent.com/13004169/53236618-6728c000-369d-11e9-8906-ef0178d7ba0a.png)

@groud Not something I noticed before, may of been missing it, but was there anything recent that might be relevant?

**Steps to reproduce:**

Make a keyframe at time 0.0, and try selecting it from the far left edge of its icon.

**Comment by groud** [comment]
> @groud Not something I noticed before, may of been missing it, but was there anything recent that might be relevant?

I don't think so, I have no clue if recent changes were made to the animation editor.

**Comment by jaswanth05rongali** [comment]
Hi!!
I could reproduce this in Ubuntu version.
I am new to godot development and I would like to work on this issue.
