### ISSUE TITLE
Language mistake in german version

### ISSUE THREAD

**Issue by sschellhoff** [godotengine/godot#26155]
There is a mistake in german language.
The button to clear a script of a node says "Leere ein Skript für das ausgewählte Node." but there are two mistakes.
There is a wrong article. It is not "das ausgewählte Node" but "den" ausgewählten Node" because Node or the german word "Knoten" is male and not neutral.
Second problem:
As far as i understand, a node can only have one script attached to it. The text suggests that you clear just one script but not the one and only script. So it should say "Leere das Skript" and not "Leere ein Skript".

So all in all it should say "Leere das Skript für den ausgewählten Node."

Version is: Godot Engine v3.0.6.stable.official.8314054

To get there, make a scene and add a node to it. Add a script to that node. At the top of your scene-view right of the filter-bar is the button to clear the script. Hover it to get the text.

**Comment by akien-mga** [comment]
You can correct this directly on https://hosted.weblate.org/projects/godot-engine/godot/

Note that translations for 3.0.x won't be updated further, the above website tracks the translations for 3.1.

**Comment by akien-mga** [comment]
Looks like this string no longer exists in the 3.1 branch.
