### ISSUE TITLE
Create shortcut keys for selecting tools from Tileset Bitmask, Occlusion etc.

### ISSUE THREAD

**Issue by nathanjwtx** [godotengine/godot#26156]
From a usability perspective it would be really useful to have shortcut keys for selecting "Select Subtile" and "Create new Polygon" toolbar buttons when creating/editing Tilesets. This would mean I could use one hand on the keyboard selecting the required buttons and the mouse hand creating the polygons without the need to "create polygon go to toolbar select region back to toolbar to create new polygon". This a pretty tedious process and I think this would speed it up.

Currently using 3.1 Beta 5

Possible relation to https://github.com/godotengine/godot/issues/21712

**Comment by not-surt** [comment]
As you say it is painfully tedious adding collision shapes to multiple tiles.

I'd like to see some ways to change the selected tile without having to switch tool so there isn't any needless back-and-forth.
eg. RMB-click on tile to select (when polygon isn't open), move tile selection with cursor keys.

Would also be nice to be able to select multiple tiles then create one collision shape which is propagated to all of them.

**Comment by Calinou** [comment]
@nathanjwtx Which shortcuts would you propose for those actions?

**Comment by nathanjwtx** [comment]
hi, sorry for delayed response. i haven't given much thought to what actual shortcuts would be good. are shortcuts contextual within Godot? Or would they need to be shortcuts not already in use?

**Comment by Calinou** [comment]
> are shortcuts contextual within Godot? Or would they need to be shortcuts not already in use?

They can be contextual, but it's better to avoid conflicts so you don't have to have the mouse focused on the TileSet editor to use them.

**Comment by SonicZentropy** [comment]
Landed here Googling how to do this.  Huge second from me on these improvements!  Tileset collisions are the first thing in Godot I've found that feel very tedious to use.  Right click to select tile and ability to copy/paste collision shapes or ability to multi-select tiles and add the same collision shape to all at once would be plenty I think

**Comment by nathanjwtx** [comment]
I haven't had the chance to fire up Godot in nearly a year due to work commitments etc. Not sure that I'm well placed to help resolve this now.

**Comment by KoBeWi** [comment]
The workflow has changed in the new TileMap and this is likely resolved or no longer relevant.
