### ISSUE TITLE
SCREEN_TEXTURE mipmap gaussian blur not working in GLES2

### ISSUE THREAD

**Issue by finkizo** [godotengine/godot#26166]
**Godot version:**
v3.1.beta6.official

**OS/device including version:**
Ubuntu 18.10 (64-bit)
Radeon RX 560 Series (POLARIS11, DRM 3.26.0, 4.18.0-15-generic, LLVM 7.0.0)

**Issue description:**
Trying to use mipmap gaussian blur in GLES2 returns standard SCREEN_TEXTURE.
![mipmap_blur](https://user-images.githubusercontent.com/47667808/53263001-ce467480-369d-11e9-9378-c8f30144c3b8.png)

**Steps to reproduce:**
Use this shader on a Polygon2D covering a viewport.
```
shader_type canvas_item;

void fragment() {
	COLOR.rgb = textureLod(SCREEN_TEXTURE, SCREEN_UV, 3.0).rgb;
}
```

**Minimal reproduction project:**
Project in GLES2, change to GLES3 and the shader works.
[mipmap_blur.zip](https://github.com/godotengine/godot/files/2895211/mipmap_blur.zip)

**Comment by clayjohn** [comment]
Mip-maps are not likely going to be added to ``SCREEN_TEXTURE`` in GLES2. Reduz has confirmed that [here](https://github.com/godotengine/godot/pull/26044).

**Comment by finkizo** [comment]
Oh, I see. Thanks for the reply, it would be a good idea to note this in the docs as you suggested in godotengine/godot-docs#2205.

**Comment by clayjohn** [comment]
Theres already a PR for it https://github.com/godotengine/godot-docs/pull/2209 :)

**Comment by finkizo** [comment]
Great! I'll go ahead and close this then.
