### ISSUE TITLE
Option for the ColorPicker to disable presets.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#26176]
**Godot version:**
3.1 +

**Issue description:**
An option to disable the presets on a ColorPicker would be useful. It should hide the presets and the button to add new presets.

Being able to disable editing presets, but still have them visible, would probably be useful too.

**Comment by AlwaysHungrie** [comment]
Hi, I am new to Godot. I would like to fix this bug.

**Comment by akien-mga** [comment]
There's already someone working on it, see the referenced pull request above your comment.

**Comment by Calinou** [comment]
This was implemented by #26252, closing.
