### ISSUE TITLE
GI broken/much too bright

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#26170]
**Godot version:**
Godot 3.1 master, commit 16e6738

**OS/device including version:**
Arch Linux, Linux 4.20.11, AMD RTX 580 with Mesa 18.3.4 

**Issue description:**
As of one of the latest commits, GIProbes in Godot seem to be broken.
Wherever used, they produce very bright, unrealistic results even at default settings. The propagation slider doesn't have any effect at all 

![gi_bug](https://user-images.githubusercontent.com/7927471/53269212-94e72680-36e8-11e9-96e4-bbfaaf6d907a.png)

**Steps to reproduce:**

set up any scene using a GI Probe

**Minimal reproduction project:**

**Comment by reduz** [comment]
Can anyone bisect this?

**Comment by novemberist** [comment]
While I don't know how to bisect, since I do build Godot quite often, I have just tested some older builds and the bug didn't occur after commit 8b231b9, but was already present after 5f5f338. So it must have been introduced somewhere in between. Don't know if this helps.

**Comment by Ace-Dragon** [comment]
This commit here made a couple of slight changes to the GI code (in a bid to fix some warnings).
https://github.com/godotengine/godot/pull/26099

Apparently, the use of **clamp** rather than **max** is needed to make sure they work properly.

**Comment by novemberist** [comment]
Unfortunately, this didn't fix it for me :(

**Comment by Ace-Dragon** [comment]
Just tested too, the commit that made changes to the GI code should be reverted.

Here's a quick and dirty example project with a 3D scene and a GI probe, the builds a few days ago and ones made just now show very different results.
[GITest.zip](https://github.com/godotengine/godot/files/2896450/GITest.zip)

**Comment by akien-mga** [comment]
There are more issues, looks like @marxin misinterpreted what `CLAMP` does (and I failed spotting the regression). Will push another fix.

**Comment by marxin** [comment]
> There are more issues, looks like @marxin misinterpreted what `CLAMP` does (and I failed spotting the regression). Will push another fix.

Ooops. Sorry for that and thanks for the fix.
