### ISSUE TITLE
Inconsistent function override behavior

### ISSUE THREAD

**Issue by theboyboy** [godotengine/godot#26179]
**Godot version:** 3.1 Beta 4

**OS/device including version:** Windows 10 Build 17134

**Issue description:** Overriding functions works differently between two GDScript files vs. a GDScript file inheriting an engine class. As an example, if I make a GDScript file that inherits from KinematicBody, then override move_and_slide and call move_and_slide_with_snap, move_and_slide_with_snap will call the original move_and_slide that exists in the engine rather than the override. if it's two GDScript files, however, it will call it from the child. So, for example, if I have a class B which inherits from a class A that contains two methods, method_one which calls method_two and then I override method_two in class B and call method_one on class B which is not overridden, it will call method_two from class B instead of class A. Both provided examples are in the reproduction project with comments in the scripts explaining what's happening on the relevant lines if anything about the way I explained it here is confusing.

I am unsure if this issue exists in other languages, I have only tested it in GDScript.

**Steps to reproduce:** Override a method from an engine class then call a method from it that would call the method you overrode

**Minimal reproduction project:** [Function Override Issue.zip](https://github.com/godotengine/godot/files/2896319/Function.Override.Issue.zip)

**Comment by Zylann** [comment]
> I make a GDScript file that inherits from KinematicBody, then override move_and_slide and call move_and_slide_with_snap, move_and_slide_with_snap will call the original move_and_slide that exists in the engine rather than the override.

This is normal, because `move_and_slide` is not a `virtual` function. The engine doesn't expect it to be overriden. `virtual` functions make calls slower for the engine to perform, so not every functions of the engine are, only some of them are designed to work that way.

**Comment by theboyboy** [comment]
Ah, I see, a misunderstanding on my part then. Thanks.
