### ISSUE TITLE
KinematicBody is_on_floor() returns false on floor collision + contact

### ISSUE THREAD

**Issue by Cygon** [godotengine/godot#26172]
**Godot version:** 3.1 beta5 (built from git 7f63b0e8cdc0ef2369d3b623c5943e2b6cd1b1ae)

**OS/device including version:** Gentoo Linux, Kernel 4.14.95, KDE5, GTX 1080 w/NVidia proprietary drivers

**Issue description:**
I'm using a `KinematicBody` and its `move_and_slide()` function to move my game character around.

To keep its physics in line with `RigidBody` nodes, it's using simple newtonian physics.

The `KinematicBody` always reports `false` when checking `is_on_floor()`, even though it has clearly collided with the floor (i.e. `move_and_slide()` broke a velocity of 5 m/s, yet `is_on_floor()` still reports `false`):

```
Movement. Intended: 0.000000,0.000000,0.000000 | Actual: 0.000000,0.000000,0.000000 | Grounded: False
Movement. Intended: 0.000000,-0.163333,0.000000 | Actual: 0.000000,-0.163333,0.000000 | Grounded: False
Movement. Intended: 0.000000,-0.326667,0.000000 | Actual: 0.000000,-0.326667,0.000000 | Grounded: False
Movement. Intended: 0.000000,-0.490000,0.000000 | Actual: 0.000000,-0.490000,0.000000 | Grounded: False
Movement. Intended: 0.000000,-0.653333,0.000000 | Actual: 0.000000,-0.653333,0.000000 | Grounded: False
Movement. Intended: 0.000000,-0.816667,0.000000 | Actual: 0.000000,-0.816667,0.000000 | Grounded: False
[...]
Movement. Intended: 0.000000,-5.226668,0.000000 | Actual: 0.000000,-5.226668,0.000000 | Grounded: False
Movement. Intended: 0.000000,-5.390002,0.000000 | Actual: 0.000000,-5.390002,0.000000 | Grounded: False
Movement. Intended: 0.000000,-5.553335,0.000000 | Actual: 0.000000,0.000000,0.000000 | Grounded: False
Movement. Intended: 0.000000,-0.163333,0.000000 | Actual: 0.000000,0.000000,0.000000 | Grounded: False
Movement. Intended: 0.000000,-0.163333,0.000000 | Actual: 0.000000,0.000000,0.000000 | Grounded: False
Movement. Intended: 0.000000,-0.163333,0.000000 | Actual: 0.000000,0.000000,0.000000 | Grounded: False
```

**Steps to reproduce:**

1. Create a scene with a `StaticBody` and a `CollisionShape`
2. Add a `KinematicBody`
3. Write script that moves the `KinematicBody` downward via `move_and_slide()`
4. Observe that the `KinematicBody`'s `is_on_floor()` method never returns true, even after hitting, and stopping at, the ground

**Minimal reproduction project:**
[KinematicBodyGroundCheck.tar.gz](https://github.com/godotengine/godot/files/2896128/KinematicBodyGroundCheck.tar.gz)

**Comment by novemberist** [comment]
I can't claim to fully understand the code in your script, but the issue here seems to be with your gravity vector. Your _most_recent_gravity_vector returns (0,-1,0), but the Vector passed to move_and_slide() should be (0,1,0) for downward movement, so is_on_floor() can work correctly.

**Comment by theboyboy** [comment]
@novemberist Why would he use a positive Y for gravity? Up is only negative in 2D, not 3D.

**Comment by novemberist** [comment]
Yeah, of course, my bad. I may have used the wrong terminology here. The second argument to move_and_slide is not the gravity direction, but the floor normal (e.g. global up direction). In his example script, he is passing his gravity vector though, which leads to is_on_floor not working correctly.

**Comment by theboyboy** [comment]
Ah yeah, I hadn't looked at the reproduction but I see what you mean now. Definitely just seems like user error

**Comment by Cygon** [comment]
Holy S...! You are correct. I carried that error all the way into my reproduction case, too.

Thanks @novemberist  and @theboyboy

Closing this right away to not further sidetrack the Godot developers on their way to 3.1 :)
