### ISSUE TITLE
Viewport with size < 2 is not drawing

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#26187]
**Godot version:**

https://github.com/godotengine/godot/commit/4f697f73a5ac567c1dc22ce44a7fab98f619dfe3

**OS/device including version:**

x11

**Issue description:**

Viewport with size < 2 is not drawing

**Steps to reproduce:**
![peek 2019-02-23 06-48](https://user-images.githubusercontent.com/4741886/53282385-19609600-3737-11e9-9b47-6b5845866822.gif)

**Minimal reproduction project:**

[viewport.zip](https://github.com/godotengine/godot/files/2896527/viewport.zip)

**Comment by Chaosus** [comment]
![image](https://user-images.githubusercontent.com/3036176/53284871-04055f00-376b-11e9-8085-adcfb5866d32.png) on Windows 10/GTX1060 

Looks like a driver or platform specific bug

**Comment by Chaosus** [comment]
Ah, detectable on Windows 10/GTX1060 too..

**Comment by AlexHolly** [comment]
On Vulkan https://github.com/godotengine/godot/commit/672bffda9c1eb9b6966060fc9ad7b95dc4c6834b
the colors always differ

![image](https://user-images.githubusercontent.com/4741886/65474364-d22cb600-de7b-11e9-83b6-c1e1fa41e355.png)
![image](https://user-images.githubusercontent.com/4741886/65474300-8da11a80-de7b-11e9-9e5d-586b1efdb1b9.png)

**Comment by KoBeWi** [comment]
Still valid in 91fd637
