### ISSUE TITLE
Error or crash when opening inherited scene after editing base scene

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#2618]
Steps to reproduce:
 1. Create new scene
 2. Add Node, save & close
 3. Create new inherited scene inheriting from just created scene
 4. Add Node within the inherited scene, save & close
 5. Reopen base scene, add another Node, save & close 
 6. Observe issue when reopening inherited scene

**Comment by reduz** [comment]
by save() you mean save with the same name as the inherited scene?

**Comment by eska014** [comment]
No, base scene and inherited scene each have their own file name.

**Comment by kubecz3k** [comment]
Closing this issue, since it looks like https://github.com/godotengine/godot/issues/2694 is now duplicating it and it have more precise informations.
