### ISSUE TITLE
inst2dict references in exported file non compatible with editor

### ISSUE THREAD

**Issue by alvaromunoz** [godotengine/godot#26188]
**Godot version:**

v3.1.beta6.official

**OS/device including version:**

MacOS Mojave 10.14.3

**Issue description:**

I used inst2dict and dict2inst to serialize some gdscript classes and save them as json. When saving in an exported build, I'm not able to use that same save file in the Godot editor.

If you serialize in the editor, it references .gd files
If you serialize in an exported build, it references .gdc files, making the save files not backwards compatible.

**Steps to reproduce:**
inst2dict a custom object and print to_json.

when saving from editor:
`[{@path:res://entities/adventurer.gd, @subpath:, _adventurer_class:0, _adventurer_name:Olfaddand}]`

when saving from exported build:
`[{@path:res://entities/adventurer.gdc, @subpath:, _adventurer_class:0, _adventurer_name:Olfaddand}]`

This crashes loading the file on the editor.

I don't know if this is by design.

**Minimal reproduction project:**

**Comment by MatiasVME** [comment]
I have a lot of problems with that, when saving data...

In fact I was going to make an issue but, I saw that this one. I made this video ->

https://youtu.be/Xqh7eId4PBo

Here's a commit in which you can test that... although it's not a minimum example, but maybe it can help.

https://github.com/MatiasVME/project-humanity/commit/736179493fc81a297ecf5bda1717ab8c6fd8565b

For the moment I solve it this way:

```
func gdc2gd(dict):
	if typeof(dict) == TYPE_DICTIONARY and dict.has("@path"):
		dict["@path"] = dict["@path"].replace('.gdc', '.gd')
		return dict
	else:
		print("Is not a dictionary: ", dict)
		return dict
```

**Comment by nhold** [comment]
This additionally has issues if you have moved the script. Serializing\Deserializing shouldn't need to know the path that the script is in.

**Comment by Xrayez** [comment]
> Serializing\Deserializing shouldn't need to know the path that the script is in.

But this is how resources are located and recognized by Godot, isn't it? What would be an alternative way to achieve this? I'm thinking that it should save the base name for the script without extension, and then try to load the script with all supported extensions for GDScript, which are `gd`, `gdc`, and `gde`. I'm almost sure that it would also fail with `.gde` files as well (encrypted GDScript).

---

Also #31045 seems to be a duplicate/related to this.
> It appears to be confused about .gd files vs .gdc files.

**Comment by Xrayez** [comment]
**Minimal project**: 
[gdscript-inst2dict-path.zip](https://github.com/godotengine/godot/files/3776221/gdscript-inst2dict-path.zip)


Some insights:

1. It does load script when created in editor and loaded with exported game (with `gd` extension).
2. It does *not* load script when created in exported game and loaded in editor (with `gdc` extension).
