### ISSUE TITLE
KinematicBody2D: move_and_slide_with_snap ignores stop_on_slope argument

### ISSUE THREAD

**Issue by piratesephiroth** [godotengine/godot#26180]
**Godot version:**
3.1 beta 513b7dd

**OS/device including version:**
Windows 10 x64

**Issue description:**
`move_and_slide_with_snap` is ignoring the `stop_on_slope` argument.
The KinematicBody2D always slides down slopes regardless of what `stop_on_slope` is set to.

`move_and_slide` still works as expected though.

**Steps to reproduce:**
In a 2d platformer setting, use `move_and_slide_with_snap` to move a KinematicBody2D over slanted terrain.

**Minimal reproduction project:**
[move_and_slide_with_snap Bug.zip](https://github.com/godotengine/godot/files/2896337/move_and_slide_with_snap.Bug.zip)

**Comment by Arkhano** [comment]
I'm having the same problem, the `move_and_slide_with_snap` is working like the `move_and_slide`, I think it's the `snap parameter`  that is not working. And I think that in godot 3.1 - beta 5 this same snap parameter if set equal to 0 make the `RayShape2D` to sink.

**Comment by piratesephiroth** [comment]
The snap parameter is working fine, at least on the latest commits.

**Comment by Arkhano** [comment]
Yeah, I test it here. In beta 6 it is working as expected.

**Comment by akien-mga** [comment]
It's unclear what works and what doesn't in the various versions you mention.

Can you report what versions are affected and by what exactly? The last change to this logic is 87b303aa9593ca7c1aa0ec2b2846b4d1fc34d0cc, which was merged right before beta 6 and is thus included in it.

**Comment by piratesephiroth** [comment]
I actually meant the build number I mentioned. I just wrote "beta" because the project is in beta stage

**Comment by akien-mga** [comment]
Yeah but @Arkhano mentioned "In beta 6 it is working as expected.", so this is confusing.

**Comment by piratesephiroth** [comment]
He's talking about the `snap`argument.
This issue is about `stop_on_slope`.

**Comment by akien-mga** [comment]
For the reference, the MRP behaves the same in beta1, beta4 and current master, so it's not a regression from a recent commit.
