### ISSUE TITLE
TileMap navigation stops working if resized

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#26186]
Godot 3.1 Beta 5

If you resize the tile's navigation after creating it, it stops working.

I think what's happening is that while creating it for the first time you can reach the maximum size of the polygon, but resizing can't reach it, therefore not connecting properly with other tiles and not forming the whole navigation.

**Comment by clayjohn** [comment]
Is this reproducible in 3.1 stable?

**Comment by DaveThornton** [comment]
I'm also having this problem in 3.1.1 stable

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by smix8** [comment]
The default buffer size value might be too low for very large NavigationPolygons. There is no real size limit for the NavigationPolygon in Godot 3.5 if the batching buffersize in the ProjectSettings is increased. There is even a new error msg for this in Godot 3.5 so this can be closed I guess.
