### ISSUE TITLE
Make Array.resize available to mono

### ISSUE THREAD

**Issue by shartte** [godotengine/godot#26195]
**Godot version:**
3.1 beta6 mono

**Issue description:**
Godot does not seem to make Array.resize available to Mono scripts, making things like building ArrayMeshes needlessly verbose.

**Expected to work:**
var surfaceArrays = new Godot.Collections.Array();
surfaceArrays.Resize((int) Godot.Mesh.ArrayType.Max);

It also seems other methods of Array are not exposed to Mono. I am unsure how to use the ArrayMesh methods without this however. (Unless I am missing something obvious)

**Comment by mnn** [comment]
Yep, those methods could be handy.

> I am unsure how to use the ArrayMesh methods without this however.

Do you mean just construction? I didn't bother cleaning it (e.g. using constants from ArrayType, exploring GC impact), because it is a code which won't be used, but this worked for me in beta 4:

```csharp
using System.Collections.Generic;
using GDArray = Godot.Collections.Array;
...
    var mesh = new ArrayMesh();

    var vertices = new List<Vector3>();
    var triangles = new List<int>();
    var uvs = new List<Vector2>();
    var normals = new List<Vector3>();
...
    // fill those lists
...
    var arrays = new GDArray {
      vertices.ToArray(),
      normals.ToArray(),
      null,
      null,
      uvs.ToArray(), //4
      null,
      null,
      null,
      triangles.ToArray() // 8
    };
    if(vertices.Count > 0) {
      mesh.AddSurfaceFromArrays(Mesh.PrimitiveType.Triangles, arrays);
    }
```

**Comment by shartte** [comment]
I tried it this way, but the vertices were corrupted somehow. However, I am now using the SurfaceTool successfully to construct the mesh instead, circumventing use of AddSurfaceFromArrays. It's less efficient, but I am only using this code in offline mesh importing scripts.

**Comment by mnn** [comment]
Strange, it is working for me without any issues :confused::

![ugb-godot-3 1 beta3_011](https://user-images.githubusercontent.com/1975567/53304976-e116a000-387b-11e9-9418-cd22d322264a.png)

I first tried the `SurfaceTool` and it was very slow, so I had to go back to `AddSurfaceFromArrays` and make that work. But I guess if you don't need it when game is running then it doesn't really matter that much :slightly_smiling_face:.

**Comment by shartte** [comment]
@neikeq  Thanks!
