### ISSUE TITLE
Creating a TextureArray with mipmaps results in a black texture

### ISSUE THREAD

**Issue by Thource** [godotengine/godot#26196]
**Godot version:**
3.1 beta 6

**OS/device including version:**
Windows 10 GTX 1070

**Issue description:**
When creating a TextureArray with the MIPMAPS flag enabled, the rendered texture is black

**Steps to reproduce:**
Download and run the MRP ( actually run the game because I couldn't find a way to create a TextureArray in the editor :( )

**Minimal reproduction project:**
[texturearray-mipmaps.zip](https://github.com/godotengine/godot/files/2896941/texturearray-mipmaps.zip)

**Comment by Thource** [comment]
I've just tried `generate_mipmaps()` which I didn't know about and the texture is still black

**Comment by Thource** [comment]
It seems that mipmaps are automatically generated for TextureArrays without needing the flag, this is either a bug or needs documenting properly, so I won't close this issue, but I'll leave the code that I found here: https://github.com/godotengine/godot/blob/16e67388a2c46e9d74d866a6cadd4351e8c57a12/drivers/gles3/rasterizer_storage_gles3.cpp#L697

**Comment by Thource** [comment]
Actually, upon further inspection, only the 1st mipmap is automatically generated and is done so with no regard to if the mipmaps flag is set, this is due to the break happening at the bottom of the loop, so there's definitely something that needs changing here :/

**Comment by Thource** [comment]
I've had a play around with this, it seems that it's fine if it makes just 1 mipmap (the first one) but if it tries to make any extra mipmaps, you just get a black texture, no errors

**Comment by akien-mga** [comment]
Fixed by #26532.
