### ISSUE TITLE
Allow the parser to continue past errors

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#26191]
From what I can tell, the parser has always stopped after hitting an error, halting any tooling until the error is solved. Prior to 3.1, this was fine, since dynamic typing made parse errors pretty uncommon.

Now with typing in 3.1, parse errors are much more common, and can greatly interfere with a workflow. For example, say I start coding something that will not fully work until I code something else. So i code it partially, then jump to the thing I need to code in order to complete it. But nope, my tooling won't work because the partially written code is throwing errors about missing variables and whatnot. So i have to make sure that no parse error is around so that I can code more comfortably elsewhere.

There is also the issue that it prevents further errors from being able to be detected until the current error is fixed. As said, this used to not be as big of a deal before, but with typing being introduced in 3.1 this calls for much better tooling.

**Comment by Calinou** [comment]
In 4.0, GDScript was rewritten to allow reporting multiple errors at the same time. The script editor was also refactored to handle
 this, closing.
