### ISSUE TITLE
CubeMesh problem with UV

### ISSUE THREAD

**Issue by DDru** [godotengine/godot#26197]
**Godot version:**
3.1 (beta 6)

**OS/device including version:**
win10, gt1030

**Issue description:**
Standard CubeMesh has a weird UV

**Steps to reproduce:**
Create standard CubeMesh and SpatialMaterial

Default state:
![default](https://user-images.githubusercontent.com/10414783/53288595-c0940a80-37d5-11e9-9866-6038d0335271.PNG)

Modified:
![2](https://user-images.githubusercontent.com/10414783/53288599-d30e4400-37d5-11e9-95d6-8c242ba878e3.PNG)

**Comment by groud** [comment]
It's not weird. In your example all faces are the same, which is not usual. I think the current UV makes a lot more sense, as it is an unfolded cube.

**Comment by Calinou** [comment]
As @groud said, this is intentional so each face can have a different texture. I guess we should make this clearer in the documentation somehow.

**Comment by DDru** [comment]
I understood. Please close.

**Comment by BastiaanOlij** [comment]
@groud , @Calinou  I think we should add images to the documentation that shows each primitive textured. For instance using a texture with numbers would quickly show how the UVs are unwrapped:
![image](https://user-images.githubusercontent.com/1945449/53292866-b269dc80-381d-11e9-937b-8f4940cd9cbd.png)
