### ISSUE TITLE
Problem trying to install Mac OS X export template under Mac OS X 10.9

### ISSUE THREAD

**Issue by arthurferrai** [godotengine/godot#262]
I tried to export a Mac OS app under Mac OS X 10.9 using the zip found on download page, but it just hangs forever. Is there a "how-to" to make my own export template, or is there another Mac OS export template anywhere?

**Comment by akien-mga** [comment]
This was more a support request than a true bug report, and one and a half year later I guess it's no longer really relevant. If you still struggle with the Mac OSX export template, please ask for support on the #godotengine IRC channel on Freenode, forums or Facebook group.
