### ISSUE TITLE
Area's signal "body_entered" is never triggered

### ISSUE THREAD

**Issue by AlexRixhardson** [godotengine/godot#26202]
**Godot version:**
3.1-beta 6

**Issue description:**
Signal "body_entered" is not triggered, when a physics body enters an area with a collision shape.

**Steps to reproduce:**
1. import attached minimal project
2. add breakpoint to the function "func _on_body_entered(body)" of "collisionShape.gd"
3. run the project

The result: function _on_body_entered will never run, because "body_entered" signal is not triggered. If you run the same project in Godot 3.1-beta 4, the "body_entered" will get properly triggered.

**Minimal reproduction project:**
[collision.zip](https://github.com/godotengine/godot/files/2897043/collision.zip)

**Comment by Zireael07** [comment]
Duplicate of #26149 (did you use the search function at all? It's clearly mentioned in the issue that beta 6 is affected)

**Comment by AlexRixhardson** [comment]
I saw #26149 (it is clearly marked as a known issue of Beta 6), but the issue reads as a bug affecting FPS in complex levels, not a complete change in how collisions work.

I have now tried the master branch, and the problem I described here cannot be reproduced anymore.
