### ISSUE TITLE
Configuration warning text not showing on editor.

### ISSUE THREAD

**Issue by luizcarlos1405** [godotengine/godot#26201]
**Godot version:**
3.1 beta 6

**OS/device including version:**
Linux Ubuntu 18.04

**Issue description:**
As title:

![image](https://user-images.githubusercontent.com/15899938/53289562-de2d8980-376d-11e9-8df9-5c09391bfc2e.png)

![image](https://user-images.githubusercontent.com/15899938/53289566-e4236a80-376d-11e9-96a1-dc704bd94470.png)

**Steps to reproduce:**
``` GDScript
extends Node

func _get_configuration_warning() -> String:
	return "Cool warning."
```

**Minimal reproduction project:**
[warning bug.zip](https://github.com/godotengine/godot/files/2897039/warning.bug.zip)

**Comment by luizcarlos1405** [comment]
The line:
``` GDScript
return get_script_instance()->call("_get_configuration_warning");
```

Returns Null here, couldn't figure out why.

https://github.com/godotengine/godot/blob/9d78274e068d4928044220c4d5c1a7baed423670/scene/main/node.cpp#L2658-L2664

**Comment by akien-mga** [comment]
You need to make this a `tool` script for it to run in the editor.

But there's an inconsistency nevertheless, as it does show a configuration warning with `Null` when it's not a `tool` script. It should either not show a configuration warning at all, or show the correct one.
