### ISSUE TITLE
Godot 3.1 beta 6 crashes on project load

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#26215]
Godot version: 3.1 Beta 6
Windows 7 home 64 bit

project seems to be crashing when I open my project that was converted from 3.0.6.

	OpenGL ES 3.0 Renderer: GeForce GTX 650/PCIe/SSE2
	Editing project: D:/Shadowblitz16/Documents/Projects/Godot Beta/ZeldaEngine (D::
	:Shadowblitz16::Documents::Projects::Godot Beta::ZeldaEngine)
	OpenGL ES 3.0 Renderer: GeForce GTX 650/PCIe/SSE2
	fixed path: D:/Shadowblitz16/Documents/Projects/Godot Beta/ZeldaEngine/.import
	unit: D:\
	ERROR: texture_set_size_override: Condition ' p_width <= 0 || p_width > 16384 '
	is true.
		 At: drivers/gles3/rasterizer_storage_gles3.cpp:1464
	ERROR: texture_get_data: Condition ' !texture->active ' is true. returned: Ref<I
	mage>()
		 At: drivers/gles3/rasterizer_storage_gles3.cpp:1047

**Comment by hpvb** [comment]
can you try deleting your .import folder and trying again?

**Comment by Shadowblitz16** [comment]
still does it but I get more errors.

	OpenGL ES 3.0 Renderer: GeForce GTX 650/PCIe/SSE2
	Editing project: D:/Shadowblitz16/Documents/Projects/Godot Beta/ZeldaEngine (D::
	:Shadowblitz16::Documents::Projects::Godot Beta::ZeldaEngine)
	OpenGL ES 3.0 Renderer: GeForce GTX 650/PCIe/SSE2
	fixed path: D:/Shadowblitz16/Documents/Projects/Godot Beta/ZeldaEngine/
	unit: D:\
	ERROR: _load_data: Condition ' !f ' is true. returned: ERR_CANT_OPEN
		 At: scene/resources/texture.cpp:502
	ERROR: Failed loading resource: res://.import/icon.png-a2b10341c27fdda667abd051a
	3b79986.stex
		 At: core/io/resource_loader.cpp:285
	ERROR: Failed loading resource: res://addons/BitmapFontCutter/icon.png
		 At: core/io/resource_loader.cpp:285
	SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res
	://addons/BitmapFontCutter/icon.png
						At: res://addons/BitmapFontCutter/main.gd:7
	ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
		 At: modules/gdscript/gdscript.cpp:579
	ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned:
	get_transform()
		 At: scene/2d/canvas_item.cpp:478
	ERROR: get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rec
	t2()
		 At: scene/2d/canvas_item.cpp:966
	ERROR: get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rec
	t2()
		 At: scene/2d/canvas_item.cpp:966
	ERROR: show_modal: Condition ' !is_inside_tree() ' is true.
		 At: scene/gui/control.cpp:2094
	ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned:
	get_transform()
		 At: scene/2d/canvas_item.cpp:478
	ERROR: get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rec
	t2()
		 At: scene/2d/canvas_item.cpp:966
	ERROR: grab_focus: Condition ' !is_inside_tree() ' is true.
		 At: scene/gui/control.cpp:2065
	ERROR: get_tree: Condition ' !data.tree ' is true. returned: __null
		 At: ./scene/main/node.h:263
	ERROR: texture_set_size_override: Condition ' p_width <= 0 || p_width > 16384 '
	is true.
		 At: drivers/gles3/rasterizer_storage_gles3.cpp:1464
	ERROR: texture_get_data: Condition ' !texture->active ' is true. returned: Ref<I
	mage>()
		 At: drivers/gles3/rasterizer_storage_gles3.cpp:1047

**Comment by akien-mga** [comment]
Can you share a project that reproduces the issue?

**Comment by Shadowblitz16** [comment]
I deleted the project and overwrote it with another attempt to convert it.
I didn't copy over the plugins that it was using and I think that was what crashed it.

however I still get this error

    At: drivers/gles3/rasterizer_storage_gles3.cpp:1464
    ERROR: texture_get_data: Condition ' !texture->active ' is true. returned: Ref<Image>()

I would upload the current project but I don't want people to steal it. 
is there a way to pm your the project?

**Comment by akien-mga** [comment]
Might be worth opening a new bug report for that other error. If you can't share the project publicly, you can send it to me: remi at godotengine · org. I won't share it further.

Closing this one as no longer reproducible.

**Comment by Shadowblitz16** [comment]
@akien-mga what is your user name? I don't see a remi user on godotdevelopers.org/forum/
the only thing close is the user remixful

**Comment by Zireael07** [comment]
He told you to mail him, the godotdevelopers forum is unofficial btw.
