### ISSUE TITLE
Area 3D node does not recognize bodies that collide with it in 3.1 B6

### ISSUE THREAD

**Issue by RodrigoMedeirosRS** [godotengine/godot#26216]
Godot version: 3.1 Beta 6 - Official Build

OS/device including version: Ubuntu 18.04, AMD opensource drivers.
The Area 3D node does not recognize bodies that collide with it. The problem occour only in 3.1B6  version, into previous version everthing works fine.

Video:
https://youtu.be/QMmiarjnyko

Steps to reproduce:
1. Create Areas with Cube-shape CollisionShape
2. Move one into another during physics_process. Maybe script them to `queue_free` when collided.
3. Observe that some of them ignore the collision entirely.

Code used: 
print(Area3D.get_overlapping_bodies().size())

**Comment by hpvb** [comment]
This has been fixed on master, it will be fixed in the next (beta) release.
