### ISSUE TITLE
GLES 2 shadow color only working on pssm 2 and 4 split not working on orthogonal mode

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#26225]
**Godot version:** 3.1  beta e30ce69

**OS/device including version:** android pie and ubuntu 18.04

**Issue description:** as stated in issue title.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by kaadmy** [comment]
Can confirm this, but it only happens with vertex lighting enabled.
