### ISSUE TITLE
How To Hide The Cmd Console？

### ISSUE THREAD

**Issue by xiaolei123** [godotengine/godot#26227]
How To Hide The Cmd Console？

**Comment by Calinou** [comment]
There is currently no built-in way to do this on Windows, see https://github.com/godotengine/godot/issues/17889.

As a workaround, you can create a shortcut to the Godot executable, right-click it and choose **Properties**, then set its default window mode to **Minimized**. This way, the console window will automatically be minimized when Godot starts (but it will still be in the task bar).

**Comment by groud** [comment]
Indeed, as #17889 stands, there is no way to do that yet.
Closing as a duplicate.

**Comment by Hzzkygcs** [comment]
I have made a simple python script/program to do so. Things you have to do is just compile this python script (you can use `auto-py-to-gui` to do so). Then you just have to put the compiled binary file **IN THE SAME DIRECTORY AS YOUR GODOT PROGRAM**. Ensure that there's no other .exe file in the directory.

```
import subprocess
import sys
from traceback import format_exc
from pathlib import Path
from glob import glob
from time import sleep
from os import chdir




def log(*args):
    with open("log.txt", "a") as f:
        Str = '\n'.join(args)
        f.write("\n\n\n==========================\n")
        f.write(Str)


def main():

    path = Path(sys.argv[0])
    this_dir = str(path.parent.absolute())
    this_filename = path.name

    chdir(this_dir)
    any_executable = glob("*.exe")

    if len(any_executable) == 0:
        print("No .exe file found")
        input("\n\nPress any key to continue...")
        exit()

    run = any_executable.pop(-1)

    while run == this_filename:  # prevent running this exe file
        if len(any_executable) == 0:
            print("No .exe file found")
            input("\n\nPress any key to continue...")
            exit()
        run = any_executable.pop(-1)    

    print(f"running {run} first found file")

    DETACHED_PROCESS = 8
    # the first argument must be always refer to its own (this program) directory
    argv = sys.argv[1:]
    subprocess.Popen([run, *argv], creationflags=DETACHED_PROCESS, close_fds=True)

    sleep(3)


if __name__ == "__main__":
    try:
        main()
    except:
        log(format_exc())
```

I have tried it and working on my windows 10, python 3.7.3.
