### ISSUE TITLE
Static GDScript Typing Variant

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#26228]
On latest static GDScript typing, there are some virtual functions that return `Variant`, and there's no way to replicate that in GDScript. What comes to mind is `Object._get` function for example. There's no way to say `func _get(property: String) -> Variant` in GDScript, "best" implementation so far is to ignore return value: `func _get(property: String)`.

We need a mechanism to return not just Object & built-in types but `Variant` as well or maybe there are other options out there too?

**Comment by neikeq** [comment]
Ignoring the return type is effectively the same as returning Variant.

**Comment by razcore-art** [comment]
Yeah but that doesn't fix the problem. What do you do with the other virtual methods that expect `Variant` as parameter? Like `_set`

**Comment by eon-s** [comment]
`Variant` is also present on the class reference as a core type, but is not exposed to GDScript.

**Comment by Calinou** [comment]
I like the idea of a generic type hint too (like TypeScript's `any` type, whose usage can be enforced using tools like TSLint). In a static typing-first workflow, this makes sure every usage of dynamic typing is carefully considered.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/605, as feature proposals are now tracked on the Godot proposals repository.

**Comment by Calinou** [comment]
For anyone stumbling upon this issue from a web search, this is now supported in `master` since the [new GDScript](https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged) was merged, closing.

![image](https://user-images.githubusercontent.com/180032/93595430-05832180-f9b8-11ea-92b0-390eb05a44f4.png)
