### ISSUE TITLE
AssetLib decsription details  

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#26231]
Some code or plugins seem not working with Godot 3.1

Please add new description details for each AssetLib plugins or code : 

1)  Godot version it was made
2)  Date it has been added to AssetLib
3) Most recent Godot version someone confirm it is working
4) Deprecated (when it is not working with latest Godot version)

**Comment by Calinou** [comment]
Closing, as this kind of information should be added to the asset library platform itself: https://github.com/godotengine/godot-asset-library

> Deprecated (when it is not working with latest Godot version)

This is implemented in the [asset library rewrite](https://github.com/Calinou/godot-asset-library-laravel/) I'm working on. An asset author (or an administrator) can mark an asset as "archived".
