### ISSUE TITLE
VisualShader problem with UI

### ISSUE THREAD

**Issue by DDru** [godotengine/godot#26230]
**Godot version:**
3.1

**OS/device including version:**
win10, gt1030

**Issue description:**
In create node menu via right-click, there are no items to scroll through. You can scroll only with the mouse wheel, which is not available to me.
![visualshader_1](https://user-images.githubusercontent.com/10414783/53299113-23db7680-3882-11e9-95dc-ed96e6632c2f.png)

Please add any buttons for scrolling. For example:
![visualshader_2](https://user-images.githubusercontent.com/10414783/53299118-2c33b180-3882-11e9-97c3-97df50843588.png)

A mouse click does not process the layer, a click is made on any node from the stack.
![visualshader_3](https://user-images.githubusercontent.com/10414783/53299124-39e93700-3882-11e9-8b67-5b661a37ffa9.png)

And in general, in Godot, working with the viewport (3d / 2d - view) takes place through the mouse wheel, which not available for many people. Please do as in Blender the "emulate middle mouse button" mode.

**Comment by Chaosus** [comment]
#26164 will fix it
