### ISSUE TITLE
DOF (Depth of Field) distance not working correctly

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#26236]
**Godot version:**
3.1 Beta 6

**OS/device including version:**
Windows 10 64, GLES 3, NVIDIA GeForce GTX 970

**Issue description:**
DOF (Depth of Field) distance not working correctly - effect is either applied to whole screen, or not at all

**Steps to reproduce:**
Create a Spatial scene with some cubes, add Environment, turn on near/far DOF, try to set it's settings so that only some cubes are blurred

**Minimal reproduction project:**
[Godot DOF test.zip](https://github.com/godotengine/godot/files/2898039/Godot.DOF.test.zip)

**Comment by hpvb** [comment]
Can you please try with beta 7?

**Comment by PLyczkowski** [comment]
Tried with beta 7, same issue.

**Comment by Waynesaurus** [comment]
Enabling SSAO does seem to make the DOF work correctly.

**Comment by kzerot** [comment]
Tried from git today, confirmed bug. 
Enabling SSAO makes the DOF work correctly, also confirmed.

**Comment by Host32** [comment]
Okay, I'm trying now to use Far Blur on mobile and I came across the same problem, blur affects the entire screen and doesn't respect the distance limits, however, in GLES2 I don't have the SSAO option available.

I realized that on the desktop with GLES2 Blur works correctly, but not on mobile, what to do in this case?

**Comment by Calinou** [comment]
> I realized that on the desktop with GLES2 Blur works correctly, but not on mobile, what to do in this case?

This is likely a driver-specific bug. Please open a new issue with a minimal reproduction project attached.

Also, since depth of field is relatively expensive, I wouldn't hold my breath on it being usable at a smooth framerate on mobile anyway.
