### ISSUE TITLE
String method to remove accents

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#26232]
Godot 3.1+

I need a way to extract names from user text but without accents (É, ê, Ô...) so I can perform accent-insensitive search and storage as keys, but I see no function to do so. Could this be added to the `String` API?

**Comment by Calinou** [comment]
You could use regular expressions to achieve this ([see an example in JavaScript](https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript)), but catching all diacritics is difficult.

**Comment by Zylann** [comment]
A regex can probably match accents, but not replacing them with their non-accent version. The example you linked uses a function not present in Godot.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3250, as feature proposals are now tracked on the Godot proposals repository.
