### ISSUE TITLE
Node2D::get_relative_transform not working as expected

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#2624]
I was trying to do something, when I was (badly) surprised by the fact that `Node2D::get_relative_transform().get_rotation()` always returned 0. Soon I found out that the problem was a bit different...

When the tree structure is like (assume all nodes are `Node2D`s):
````
common_root
  some_parent_A
    node_A
  some_parent_B
    node_B
````
`node_A.get_relative_transform(node_B)` will error at [node2d.cpp:342](https://github.com/okamstudio/godot/blob/d3eb9e8c54d4a93b2bed90a5988f9814377d409f/scene/2d/node_2d.cpp#L342), and return `node_A`'s global transform instead.

Note: This can't be reproduced like:
````
common_root
  node_A
  node_B
````
, because then the `if` at line 343 would work properly.

**Comment by reduz** [comment]
yeah, this function only works if the argument is a parent node, you can still try

(a.get_global_transform().affine_inverse() * b.get_global_transform() and it will work in all cases

Still, the function name is confusing, will rename it

**Comment by reduz** [comment]
function has been renamed, use the above mentioned method instead
