### ISSUE TITLE
The cursor in the Label/RichTextLabel text editors is hard to see and doesn't blink

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#26246]
Godot 3.1 beta6

The default settings for `TextEdit` cursors in the editor is hard to see and doesn't blink, which makes it harder to use.

Both in the inspector:
![image](https://user-images.githubusercontent.com/1311555/53303432-2037f780-3862-11e9-8e6d-73693d31a805.png)

And the popup:
![image](https://user-images.githubusercontent.com/1311555/53303421-05fe1980-3862-11e9-8fe2-b73b61b92aca.png)

Note: that's also generally the case for `TextEdit` nodes which are added by custom editor plugins.

**Comment by akien-mga** [comment]
CC @Calinou

**Comment by JohnJLight** [comment]
Couldn't it be made more visible within editor settings, where you could change the color too?

**Comment by Calinou** [comment]
@JohnJLight It should reuse the text color calculated by the editor (depending on whether the user is on a dark or light theme), or alternatively the `mono_color` (which is pure white on a dark theme, and pure black on a light theme).

**Comment by mariambukenya** [comment]
I was able to reproduce this issue and locate the program files needed to fix this issue. I am now attempting to solve this issue.
