### ISSUE TITLE
draw_set_transform Doesn't Work

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#26260]
**Version**
Godot Beta 7

**Issue**
draw_set_transform appears to be ignored completely. See below images.

![image](https://user-images.githubusercontent.com/21234930/53314188-ec64ce00-3871-11e9-80fe-87ace545ab50.png)

![pubvbhn](https://user-images.githubusercontent.com/21234930/53314170-cccda580-3871-11e9-8b23-3584cac505f3.gif)

**Comment by groud** [comment]
In fact this is the expected behavior. 
The two transforms, the one using the draw_set_transform, and the one using the normal one stack up, so it's normal your rect rotates too.

**Comment by bojidar-bg** [comment]
In addition, changing the transform does not trigger `update()`, you should call it manually.

**Comment by 11clock** [comment]
@groud But isn’t the point of draw_set_transform to be able to ignore the current node’s transform? This doesn’t sound right.

@bojidar-bg I am calling update in _process.

**Comment by groud** [comment]
> But isn’t the point of draw_set_transform to be able to ignore the current node’s transform? This doesn’t sound right.

No it is not, it simply allows drawing some specific shapes, like rotated rectangles for example, without having to rotate the node itself. 

You can achieve a global transform by using multiplying the transform you need to apply by inverse of the current node's global transform. Somehow like this :
```
	var myTransform = Transform2D(30, Vector2(10,10))
	myTransform = get_global_transform_with_canvas().affine_inverse() * myTransform 
	draw_set_transform_matrix(myTransform)
	draw_rect(Rect2(0,0,20,20), Color.aliceblue)
```
