### ISSUE TITLE
Beta 7 will not start

### ISSUE THREAD

**Issue by kingpinzs** [godotengine/godot#26262]
**Godot version:**

Godot_v3.1-beta7_win64

**OS/device including version:**

Windows 10 1809

**Issue description:**

I double click to open Godot and the console window opens then goes away and godot never opens

**Steps to reproduce:**
Download beta 7 from https://downloads.tuxfamily.org/godotengine/3.1/beta7/ extract it and try to open it

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
32-bit beta 7 or 64-bit?

**Comment by kingpinzs** [comment]
64-bit -> Godot_v3.1-beta7_**win64**

**Comment by kingpinzs** [comment]
Duplicate of #26243
