### ISSUE TITLE
Beta7 won't build the C# solution

### ISSUE THREAD

**Issue by martys71** [godotengine/godot#26264]
**Godot version:**# 3.1 beta 7 mono

**OS/device including version:** Windows 10, x64

**Issue description:**

When trying to open a C# project or attaching a new C# script to an object the editor shows the messages:

ObjectType\EditorSpatialGizmoPlugin.cs(72,31): warning CS0108: 'EditorSpatialGizmoPlugin.GetName()' hides inherited member 'Resource.GetName()'. Use the new keyword if hiding was intended. [D:\Users\msien\AppData\Roaming\Godot\mono\solutions\10766899846445281542_7_1550967167\GodotSharpEditor\GodotSharpEditor.csproj]
		ObjectType\EditorSpatialGizmo.cs(96,65): error CS1750: A value of type 'bool' cannot be used as a default parameter because there are no standard conversions to type 'RID' [D:\Users\msien\AppData\Roaming\Godot\mono\solutions\10766899846445281542_7_1550967167\GodotSharpEditor\GodotSharpEditor.csproj]

**Steps to reproduce:**
Start a new project, create a scene then try to attach a C# script to it.

**Minimal reproduction project:**

**Comment by Chaosus** [comment]
Yes, we are aware of this issue, It was fixed by #26214, but sadly the fix wasn't included in beta 7.
