### ISSUE TITLE
Mono error on beta when compiling empty project

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#26261]
**Godot version:**
Godot 3.1 beta 7

**OS/device including version:**
Linux Mint 19.1 Tessa x86_64

**Issue description:**
In trying of compilation of empty project with Mono Godot version, it throws this error:
`ObjectType/EditorSpatialGizmo.cs(96,65): error CS1750: A value of type 'bool' cannot be used as a default parameter because there are no standard conversions to type 'RID'`

**Steps to reproduce:**
1. Download and launch Godot Mono beta.
2. Create a new empty project.
3. Click "Mono" -> "Create C# Solution".
4. Receive a message about "Failed to build GodotSharp solution." and error that pointed above.

**Comment by Teashrock** [comment]
There is also a warning like this:
`ObjectType/EditorSpatialGizmoPlugin.cs(72,31): warning CS0108: 'EditorSpatialGizmoPlugin.GetName()' hides inherited member 'Resource.GetName()'. Use the new keyword if hiding was intended.`

**Comment by drako0812** [comment]
I don't know about @Teashrock but I'm getting this on Windows 10 1809 using Godot Beta 7 for Windows x64

**Comment by Chaosus** [comment]
Yes, we are aware of this issue, It was fixed by #26214, but sadly the fix wasn't included in beta 7.
