### ISSUE TITLE
Resources are not saving if scene is not opened

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#26273]
**Godot version:**
Godot 3.1 Beta 6

**OS/device including version:**
Mac OSX Mojave and Windows

**Issue description:**
As requested by @reduz I created this new issue referencing an old issue regarding resource saving in the editor (#25832). Resources are saved along side scenes. When a scene is saved the resource is also saved, so if you are editing a resource even if it is not being used by the scene it gets saved, and that works nice.

The problem is that when there is no scene open and you are just editing a bunch of resources from your game there is no obvious way of saving them, other than running your game.
Cmd-S (saves only if the scene is opened) and Cmd-Alt-S saves only the script in the script editor.
there is no quick way to save the resource other than clicking in the save icon and selecting "Save" instead of "Save as" and this is tedious. 

Another problem is that there is no obvious notification that your resource as been edited and not saved... if you try to close the project you don't get notified about unsaved resources (this led me to lose a lot of time spent in resource editing).

The current way of navigating through resources in the inspector also doesn't help... (as you just have a "back" and "forward" button) you don't know how many resources you edited and you don't have a visual cue of how many resources are actually open.

PS: sorry the shorts cuts are for OSX (I don't use windows only in VM). 

**Steps to reproduce:**
N/A

**Minimal reproduction project:**
N/A

**Comment by Zylann** [comment]
> you don't have a visual cue of how many resources are actually open.

My guess on this is, they are never actually closed until you close Godot itself. They just sit in the history forever.
