### ISSUE TITLE
KinematicBody2D: move_and_slide_with_snap won't snap to slopes

### ISSUE THREAD

**Issue by piratesephiroth** [godotengine/godot#26274]
**Godot version:**

Godot 3.1 beta 61b41d6

**OS/device including version:**
Windows 10 x64

**Issue description:**
---
EDIT: it was just that `move_and_slide_with_snap` only snaps to floors and a limit for that is defined by the `floor_max_angle` argument. The default value is lower than 45º therefore it wouldn't detect the slopes in my example as floors.
Thanks @kaadmy 
---
`move_and_slide_with_snap` only snaps to straight surfaces.
It completely ignores slopes.

All these tests use Vector2(0,16) as `snap`

Falling from a 16 pixels-tall tile onto a straight surface. Snaps fine.
![flat](https://i.imgur.com/ObaKTW3.gif)

Falling from a corner onto a slope, no snapping at all:
![slope-polygon](https://i.imgur.com/B59qTNC.gif)

![slope_tilemap](https://i.imgur.com/o0BPj9n.gif)

**Steps to reproduce:**
In a 2D Platformer setting, use `move_and_slide_with_snap` to make a KinematicBody2D slide off a ledge or corner. It will only stay on the floor if there's straight terrain inside the snap vector range.

**Minimal reproduction project:**
[move_and_slide_with_snap-slopeBug.zip](https://github.com/godotengine/godot/files/2900858/move_and_slide_with_snap-slopeBug.zip)

**Comment by kaadmy** [comment]
`move_and_slide_with_snap` will only snap to floors. The default floor angle is `0.785398` radians, which equals `44.999991` degrees. Setting the slope angle to a few degrees higher fixes this (due to floating point precision issues and margins).

**Comment by Arkhano** [comment]
I confirm this, even with higher degree angle it is not snapping properly and the `stop_on_slope` argument still not working. Please don't send this issue to 3.2, it was working a few 3.1 betas ago.

**Comment by piratesephiroth** [comment]
oh, @kaadmy is correct.
For some reason, 45 degrees is above the default angle for what `move_and_slide` considers to be a floor so it can't be snapped to.

If we change the `floor_max_angle` argument to 46º (0.802851 radians) it snaps again.
Closing this.

**Comment by Arkhano** [comment]
@piratesephiroth Yeah it is snapping but the `stop_on_slope` argument still not working and it is sliding down slowly.

**Comment by piratesephiroth** [comment]
> 
> 
> @piratesephiroth Yeah it is snapping but the `stop_on_slope` argument still not working and it is sliding down slowly.

It's working. Did you try beta7?

**Comment by svendixon** [comment]
I am using the 3.1 release with stop_on_slope = true, but my character still slides down slopes.

![2019-03-24 10-36-37](https://user-images.githubusercontent.com/14341036/54880998-aaec2200-4e21-11e9-8e72-619f85d391ee.gif)

**Comment by piratesephiroth** [comment]
you should upload a sample project then because as I wrote before, stop_on_slope is working fine here

**Comment by svendixon** [comment]
Ok. I created an sample project. Keep in mind, I'm not much of a programmer, so I apologize if it's badly written. Setting up the collision using a RayCast shape fixed the sliding issue for the most part (I thought this was only used to solve constant velocity up and down slopes?). Player sometimes comes off the slope, but that might be my bad code. But it seems using a RayCast shape causes issues with one way platforms. Maybe there is something I am missing?

![2019-03-25 02-35-03](https://user-images.githubusercontent.com/14341036/54900197-bafb1480-4ea8-11e9-9a3c-22fb887baf3c.gif)

[slippery_slope.zip](https://github.com/godotengine/godot/files/3001890/slippery_slope.zip)

**Comment by piratesephiroth** [comment]
hmmm.... your character never stops sliding because the x velocity  after your lerp calculation never results in 0 on slopes and I think `stop_on_slope` is only triggered when the body actually stops moving horizontally

As a test, try making a button set the speed to 0 as you slide down a slope and you'll see the character will stay stationary.

(unrelated but I think you should be making those movement calculations in _physics_process)

(also Vector2 has constants you can use to set basic values, like Vector2.ZERO)
![image](https://user-images.githubusercontent.com/10672233/54913073-bcd8ce00-4ed0-11e9-8104-f41a74f47bfe.png)
