### ISSUE TITLE
godot crashes on project load again (this time with example project)

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#26284]
Godot version: 3.1 beta 6
Window 7 home 64 bit

Godot crashes on project load

	OpenGL ES 3.0 Renderer: GeForce GTX 650/PCIe/SSE2
	Editing project: D:/Shadowblitz16/Documents/Projects/Godot Beta/ZeldaEngine (D::
	:Shadowblitz16::Documents::Projects::Godot Beta::ZeldaEngine)
	OpenGL ES 3.0 Renderer: GeForce GTX 650/PCIe/SSE2
	fixed path: D:/Shadowblitz16/Documents/Projects/Godot Beta/ZeldaEngine/.import
	unit: D:\
	SCRIPT ERROR: GDScript::reload: Parse Error: Identifier 'tile' is not declared i
	n the current scope.
						At: res://editor/widgets/tile.gd:21
	ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
		 At: modules/gdscript/gdscript.cpp:579
	ERROR: texture_set_size_override: Condition ' p_width <= 0 || p_width > 16384 '
	is true.
		 At: drivers/gles3/rasterizer_storage_gles3.cpp:1464
	ERROR: texture_get_data: Condition ' !texture->active ' is true. returned: Ref<I
	mage>()
		 At: drivers/gles3/rasterizer_storage_gles3.cpp:1047

[ZeldaEngine.zip](https://github.com/godotengine/godot/files/2902676/ZeldaEngine.zip)

**Comment by avencherus** [comment]
I ran the Tile.tscn and wasn't able to get this crash, only got the script errors when running it.

Win10 64-bit Builds: 88a36e2 and Beta 6.

**Comment by akien-mga** [comment]
I can reproduce the crash on Linux, Mageia 7 x86_64. `gdb` stacktrace from debug build at 8930347:
```
SCRIPT ERROR: GDScript::reload: Parse Error: Too few arguments for '_process_widget()' call. Expected at least 1.
   At: res://editor/widget.gd:23.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:579.
[Thread 0x7ffff6b74700 (LWP 16491) exited]
ERROR: texture_set_size_override: Condition ' p_width <= 0 || p_width > 16384 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1464.

Thread 7 "godot-git" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff40c0700 (LWP 16486)]
0x000000000311f1df in Image::get_rect (this=0x0, p_area=...) at core/image.cpp:1910
1910            Ref<Image> img = memnew(Image(p_area.size.x, p_area.size.y, mipmaps, format));
Missing separate debuginfos, use: debuginfo-install lib64drm2-2.4.97-2.mga7.x86_64
(gdb) bt
#0  0x000000000311f1df in Image::get_rect (this=0x0, p_area=...) at core/image.cpp:1910
#1  0x000000000205cf17 in EditorTexturePreviewPlugin::generate (this=0xaac7130, p_from=..., p_size=...) at editor/plugins/editor_preview_plugins.cpp:96
#2  0x0000000001d22ec6 in EditorResourcePreviewGenerator::generate_from_path (this=0xaac7130, p_path=..., p_size=...) at editor/editor_resource_preview.cpp:71
#3  0x0000000001d2410d in EditorResourcePreview::_generate_preview (this=0x7a6f750, r_texture=..., r_small_texture=..., p_item=..., cache_base=...)
    at editor/editor_resource_preview.cpp:153
#4  0x0000000001d24f5b in EditorResourcePreview::_thread (this=0x7a6f750) at editor/editor_resource_preview.cpp:241
#5  0x0000000001d238ee in EditorResourcePreview::_thread_func (ud=0x7a6f750) at editor/editor_resource_preview.cpp:93
#6  0x0000000001ac4df7 in ThreadPosix::thread_callback (userdata=0x775c930) at drivers/unix/thread_posix.cpp:74
#7  0x00007ffff7f6e04c in start_thread () from /lib64/libpthread.so.0
#8  0x00007ffff7d5825f in clone () from /lib64/libc.so.6
```

CC @groud @reduz
