### ISSUE TITLE
Missing files exporting godot 3 for IOS

### ISSUE THREAD

**Issue by Lucky0710** [godotengine/godot#26282]
Hello, i'm trying to export a godot 3.0.6 project on IOS.
This project works perfectly fine on an Android, with admob.
Also, the project build fine with Godot on a Mac. 
But when i try to export it for ios, after following the official documentation, i end up with only 4 files created:

- Project
- Project.pck
- Project.xcodeproj
- Project.a

Godot is not creating a .ipa file, and when i try to build the project in xcode, i get theses messages:

- Failed to create provisioning profile. The app ID "org.godotengine.iosgame" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.
- No profiles for 'org.godotengine.iosgame' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'org.godotengine.iosgame'.
- Code signing is required for product type, 'Application' in SDK 'iOS 11.4'

I precise that i've followed exactly the tutorial, i downloaded the export templates, used my Appstore Team ID, filled all the icons and launch screen needed, and i'm using Xcode 9.4.1. 
Thank you in advance for you help !

**Comment by samgreen** [comment]
You need to change the bundle id. `org.godotengine.iosgame` is already registered to the example app. Create a new one of the format `com.example.mygame`.

**Comment by Lucky0710** [comment]
Thank you very much ! Now all the files are generated, but i'm still having an error in Xcode:

- Ignoring files /Users...../Game.a, missing required architecture x86_64 in file /Users...../Game.a (3slices)
- Linker command failed with exit code 1

How can i get rid of this ?

**Comment by Lucky0710** [comment]
So everything works fine now, the project run on my iphone, but always on landscape mode, even when i choosed "portait mode" in the godot display settings... I don't get it

**Comment by tomnahooy** [comment]
Make sure you change the orientation in Xcode as well under General > Deployment info > Device orientation

**Comment by samgreen** [comment]
It will run at whatever resolution you have selected in the Godot Project settings. If you're rendering at `1280x720` that will be landscape. Try swapping your project settings and ensure you're rendering at `720x1280` or whatever the equivalent is for your existing resolution.

**Comment by Lucky0710** [comment]
It works now, thanks to tomnahooy ! 
Now i’m struggling to make admob work, but i will create a new issue if i need some help ! Thank you all !
