### ISSUE TITLE
SpriteFrame's animations don't appear when scene is run

### ISSUE THREAD

**Issue by vekkna** [godotengine/godot#26288]
**Godot version:**
3.1 beta 7

**OS/device including version:**
Windows 10 Home x64
Intel i7-4710MQ
Nvidia GeForce GTX 860M

**Issue description:**
An AnimatedSprite's SpriteFrames has many animations, all showing up in the Scene view in the editor. 
When the scene is run, however, only a few of the SpriteFrame's animation exist in the running game, as seen in the Remote view. None of the missing animations play.

**Steps to reproduce:**
Please run the attached scene and compare the animations in the editor with those a running scene.

**Minimal reproduction project:**

[player.zip](https://github.com/godotengine/godot/files/2902808/player.zip)

**Comment by akien-mga** [comment]
The attached scene can't be run, it lacks all its dependencies:
![screenshot_20190228_135649](https://user-images.githubusercontent.com/4701338/53567844-b325aa00-3b60-11e9-9546-cb4dedb0270f.png)

**Comment by akien-mga** [comment]
Closing as the reproduction project is invalid.
