### ISSUE TITLE
Shader color changes with mesh size on android

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#26297]
**Godot version:**
3.1 beta 7

**OS/device including version:**
Oukitel K6000 Pro, Android 6.0
Samsung Galaxy J5, Android 7

**Issue description:**
Hey, I am not exactly sure how to describe this issue best. But I noticed my game looks different on Android than on windows. This was because I have some meshes with the same texture. On Windows the transition between the objects is seamless, on Android, the meshes are distinguishable because the color varies slightly between the meshes,

I tried to further investigate this and it seems it has something to do with the size of the mesh. The bigger the mesh it, the brighter is the color of the object. Of course the intensity of this issue varies with the albedo and other shader parameters, but generally this seems to be true.

Here e.g. two identical meshes, one set to scale 1 and the other to scale 15
Windows:
![shaderlightbugwindows](https://user-images.githubusercontent.com/25849067/53395546-6005f880-39a2-11e9-86b3-864c7c0fe04b.PNG)

Android:
![shaderlightbugandroid](https://user-images.githubusercontent.com/25849067/53395552-6300e900-39a2-11e9-9285-4b24f1c4d590.png)

If you set the scale to 30 it looks like this:
![shaderlightbugandroid2](https://user-images.githubusercontent.com/25849067/53397369-46b37b00-39a7-11e9-9a42-3c8780eabd87.png)

**Steps to reproduce:**
Create two plane meshes and assign them the same material. Set the scale of one of the objects to be bigger than the other one. The higher the scale, the brighter the object will be.

**Minimal reproduction project:**

[LightShaderBug.zip](https://github.com/godotengine/godot/files/2904378/LightShaderBug.zip)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Zylann** [comment]
Does this still happen if `ensure_correct_normals` is checked? I think this option was added when non-uniform scale is used (was very noticeable if you flatten a sphere along one axis)

**Comment by clayjohn** [comment]
No response, so closing
