### ISSUE TITLE
Allow Mono Debugging Options on Godot Command Line

### ISSUE THREAD

**Issue by shartte** [godotengine/godot#26298]
**Godot version:**
3.1beta6

**Issue description:**
I am developing command line tools (Asset importing) using Godot C# and running them on the command line using `godot -s`. Debugging currently is a hassle because in order to debug, I have to:
- go back to the Godot editor
- enable the "Mono -> Wait for Debugger" option
- launch my script on the command line
- attach the debugger
- disable the Wait for Debugger option again

Instead it would be a lot nicer to be able to specify the mono debugging options directly on the command line of godot.exe, for example such as:

`godot.exe --mono-debugger-agent=address=Y.Y.Y.Y:34567,server=n,transport=dt_socket --mono-debug -s MyScript.cs`

**Comment by neikeq** [comment]
You can already specify the debugger agent with the `GODOT_MONO_DEBUGGER_AGENT` environment variable.
I will consider adding command line options if the cli parser PR is accepted and allows this.

**Comment by shartte** [comment]
Thanks for the info on `GODOT_MONO_DEBUGGER_AGENT`. This should probably be in the docs, I could only find a single google result for that env-variable and it was the source code itself 😁

**Comment by violinbg** [comment]
Exposing "Wait for Debugger" to the command line would be much appreciated.
I was able to quickly setup VSCode to build and run Godot but one need to manually enable and disable the "Wait for Debugger" option.

**Comment by YuriSizov** [comment]
Seems like there is some merit to this idea, but it should be put into a [proposal](https://github.com/godotengine/godot-proposals).
