### ISSUE TITLE
Export template installation allows installing files outside the templates folder (regression from #26283)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#26302]
- Open Windows startup folder to witness the fun - `Start`->`Run`->`shell:startup`
- Download and install attached "export templates" (`.tpz` inside `.zip` cause GitHub doesn't like files with unknown extensions)
- ...
- Profit!

[completely_legit_export_templates_for_windows.tpz.zip](https://github.com/godotengine/godot/files/2904958/completely_legit_export_templates_for_windows.tpz.zip)

Obviously using export templates from unknown sources is not the right thing to do, but maybe we should sanitize filenames a bit before extracting (at least remove nasty stuff like `..`).

_Originally posted by @bruvzg in https://github.com/godotengine/godot/pull/26283#issuecomment-467386288_

**Comment by akien-mga** [comment]
For the reference, `unzip` properly skips `../` and we should do the same:
```
$ cd /home/akien/tmp/godot/bug
$ mkdir -p a/b/c/d/e
$ cd a/b/c/d/e
$ unzip ../../../../../completely_legit_export_templates_for_windows.tpz
Archive:  ../../../../../completely_legit_export_templates_for_windows.tpz
   creating: templates/              
  inflating: templates/version.txt   
warning:  skipped "../" path component(s) in templates/../../../Microsoft/Windows/Start Menu/Programs/Startup/godot_locker.exe
  inflating: templates/Microsoft/Windows/Start Menu/Programs/Startup/godot_locker.exe
$ find
.
./templates
./templates/version.txt
./templates/Microsoft
./templates/Microsoft/Windows
./templates/Microsoft/Windows/Start Menu
./templates/Microsoft/Windows/Start Menu/Programs
./templates/Microsoft/Windows/Start Menu/Programs/Startup
./templates/Microsoft/Windows/Start Menu/Programs/Startup/godot_locker.exe

**Comment by bruvzg** [comment]
Similar issue happens with the asset library.

In this case it requires either fill set of `..` directory entries in addition to malformed filename or windows path separators in the filename part with `..`.

Even worse, in the second case (windows path separators) UI is NOT displaying `..` in the asset install dialog (filename is displayed) but still extracting files outside the project folder.

Test file:
[addons.zip](https://github.com/godotengine/godot/files/2905268/addons.zip)

UI:
![screenshot 2019-02-26 at 13 48 10](https://user-images.githubusercontent.com/7645683/53411036-2814aa80-39ce-11e9-9f1d-261598a06fd4.png)

Actual file content:
```
unzip -v ./addon.zip
Archive:  ./addon.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Stored        0   0% 02-26-2019 13:45 00000000  addons/
      12  Defl:N       14 -17% 02-26-2019 11:51 945935bd  addons/..\..\..\..\..\virus.exe
--------          -------  ---                            -------
      12               14 -17%                            2 files
```

**Comment by samgreen** [comment]
Issue is also present on OS X with 3.1 beta 7

**Comment by neikeq** [comment]
Is there anything else we should be careful of apart from `..`?

**Comment by akien-mga** [comment]
The issue with the export templates manager is fixed.

> Similar issue happens with the asset library.

This likely still needs a similar fix.
