### ISSUE TITLE
The "Show list of objects under mouse" button cannot be turned off

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#26307]
Godot 3.0.6
Godot 3.1 beta5

Once pressed, this button cannot be unpressed:
![image](https://user-images.githubusercontent.com/1311555/53416574-b0de1700-39cb-11e9-8acb-458695d78745.png)

**Comment by groud** [comment]
Well, you need to select another tool to unselect it, like all other tools.
We should likely add a separator between this icon and the lock one so it's more clear.

**Comment by Zylann** [comment]
I thought this button was a selection option to toggle? Is it really supposed to be a tool? I mean, you may be able to select stuff regardless of your edition mode is, right?

**Comment by groud** [comment]
> I thought this button was a selection option to toggle? Is it really supposed to be a tool? I mean, you may be able to select stuff regardless of your edition mode, right?

I think this was designed to be a tool, and that's how it work in 2D. And no, still in 2D, selection is only possible in the selection mode (and the list selection one).

**Comment by Zylann** [comment]
@groud if selection is possible only in selection mode, then here is the thing: I never, ever used (or needed) any other mode :s

**Comment by groud** [comment]
> @groud if selection is possible only in selection mode, then here is the thing: I never, ever used (or needed) any other mode :s I can select move things around in "selection mode", so I never had to use the others. To rotate and sometimes move things I used shortcuts. Hence my confusion...

Yeah, that 's expected, it's mainly for discoverability. You can use alt + left click to popup the selection list if you are not in this mode, as the popup stands. :)

Apparently, in 2D, reduz told me he used the move tool all the time. So I guess some people still use those other modes.

**Comment by groud** [comment]
Closing this issue, as the original problem is an expected behavior :)
