### ISSUE TITLE
Culling of shadows and animation?

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#26305]
I have a question, does Godot supports culling of shadows and animations as an optimization?
Example would be everything away from the cam frustum is culled.

**Comment by kaadmy** [comment]
In 2D or 3D?

I believe 3D already has light/shadow culling, and animations can have scripts/logic tied to them so I'm not sure if it'd be possible to cull them.

**Comment by Akira1San** [comment]
I see, thx.

**Comment by eon-s** [comment]
For future questions, use other community channels instead (Q&A, Discord, etc.) because this issue tracker is for bug reporting or feature requests.
