### ISSUE TITLE
[Q] Vector (and other engine specific data types) in GDNative with C++

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#26300]
**Godot version:** 3.1.beta6 64b

**OS/device including version:** Linux 64b

**Issue description:**
Docs on core data are saying that we should use Godot types, so memory tracking works. I was looking at containers and wanted to try `Vector`, but I failed to locate it in `godot_headers` and `godot-cpp`. Am I supposed to be using these classes in GDNative? It seems a bit weird using custom `String`, but not custom collections. Maybe I overlooked it? What is recommended approach?

PS: Any links describing good practices in GDNative with C++ (or even Godot generally) would be appreciated.

**Comment by bruvzg** [comment]
GDNative only provides same API as GDScript do (except [internal functions](https://docs.godotengine.org/en/latest/classes/class_@gdscript.html)) and some additional low level AR/VR/platform specific stuff.

GDScript uses only `Array`, `Dictionary` and subset of `Pool*Vector`, internal engine types like `PoolVector<*>`, `Vector`, `List`, `Set`, `Map` aren't exposed to GDScript and aren't available in GDNative either.

Simply use `std::` counterparts instead.

**Comment by mnn** [comment]
> Godot has many tools for tracking memory usage in a game, especially during debug. Because of this, the regular C and C++ library calls should not be used. Instead, a few other ones are provided.

This is what I was referring to.

> GDScript uses only...

But also in GDScript aren't any other collections except those provided  by the engine unlike in C++, right?

> Simply use `std::` counterparts instead.

Yes, I am, but I am not clear about that memory tracking - it will work, or it is not supported for GDNative? Or is it intended only for the engine itself and not "scripts"?

**Comment by sheepandshepherd** [comment]
None of the core C++ engine (like Vector) is exposed to GDNative C++ bindings, only what's in the C interface. The memory management functions you want are `godot_alloc`, `godot_realloc`, and `godot_free` in [this GDNative header](https://github.com/GodotNativeTools/godot_headers/blob/master/gdnative/gdnative.h#L276). Those are the wrappers around C `malloc`/etc. with memory usage tracking that Godot containers use.

Unfortunately creating new containers that use them would be a lot of work, so most GDNative projects probably just use the binding language's own containers and ignore loss of memory usage tracking.

I wonder if you could use `std::vector` with a [custom allocator](https://en.cppreference.com/w/cpp/named_req/Allocator) using `godot_alloc`.

**Comment by mnn** [comment]
@sheepandshepherd Thank you for detailed response.

> None of the core C++ engine (like Vector) is exposed to GDNative...

It is unfortunate that so many classes are not exposed. I think it should either be exposed or reimplemented by lang. bindings. It seems to me that GDNative or C++ bindings are a bit immature.

> Unfortunately creating new containers that use them would be a lot of work, so most GDNative projects probably just use the binding language's own containers and ignore loss of memory usage tracking.

Yeah, probably what I will do. I am sure even if I would managed to implement them (I still remember horrors of creating custom collections in Scala), their performance would be rubbish, so I would lose the main reason to use C++.

> I wonder if you could use std::vector with a custom allocator using godot_alloc.

I'll try that, if the usage of custom allocator could be abstracted away (template), this could be a good solution.

**Comment by Calinou** [comment]
GDNative is being removed in 4.0 in favor of GDExtensin, closing.
