### ISSUE TITLE
Godot 3.1 beta 7 crashing when opened

### ISSUE THREAD

**Issue by JulioYagami** [godotengine/godot#26311]
Assinatura do problema:
  Nome do Evento de Problema:	APPCRASH
  Nome do Aplicativo:	Godot_v3.1-beta7_win64.exe
  Versão do Aplicativo:	3.1.0.0
  Carimbo de Data/Hora do Aplicativo:	00000000
  Nome do Módulo de Falhas:	Godot_v3.1-beta7_win64.exe
  Versão do Módulo de Falhas:	3.1.0.0
  Carimbo de Data/Hora do Módulo de Falhas:	00000000
  Código de Exceção:	c000001d
  Deslocamento de Exceção:	000000000217b9f5
  Versão do sistema operacional:	6.1.7601.2.1.0.256.1
  Identificação da Localidade:	1046
  Informações Adicionais 1:	b2d1
  Informações Adicionais 2:	b2d155b8bcf28793ebc01c3fed245197
  Informações Adicionais 3:	f659
  Informações Adicionais 4:	f65925672894055f91100940c4f26315

**Comment by akien-mga** [comment]
Duplicate of #26243. This will be fixed in 3.1 beta 8 today.
