### ISSUE TITLE
Lights randomly hide custom PanelContainers and their parent

### ISSUE THREAD

**Issue by onionpsy** [godotengine/godot#26310]
**Godot version:**
3.1 beta7

**OS/device including version:**
Windows 10, Intel Iris 540

**Issue description:**
Disabling light mask on a PanelContainer hide it (and it's parent) from the editor/in game. Seems to happend only when the panel is a custom one (tested with a StyleBoxFlat) and when there is a Light source in the scene. Only happend on some sprites.

**Steps to reproduce:**

1. Add many sprites
2. For all of them, add a PanelContainer with custom StyleBoxFlat (default one)
3. Uncheck all light masks on the PanelContainers
4. Add a light source
5. Run the project, some sprites/panel container should be somehow hidden, or not displaying correctly

**Minimal reproduction project:**
[light_panels_bug.zip](https://github.com/godotengine/godot/files/2906066/light_panels_bug.zip)

**Comment by KoBeWi** [comment]
@onionpsy Can you still reproduce this in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3)?
(I tested the project and it looks fine)

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue, and make sure that there is an up-to-date reproduction project.
