### ISSUE TITLE
Setting a variable of another scene throws an error in tool mode

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#26319]
**Godot version:**
3.1 beta 7

**OS/device including version:**
Windows 10

**Issue description:**

When trying to set a member variable of another scene loaded with the load-function in tool mode, I get the error: 

>  Invalid set index 'test' (on base: 'Node2D (AnotherScene.gd)') with value of type 'int'.

**Steps to reproduce:**
- create a tool script
- load another scene with load()
- set a member variable of that scene

**Minimal reproduction project:**
[ToolNodeInstance.zip](https://github.com/godotengine/godot/files/2907360/ToolNodeInstance.zip)

**Comment by Zylann** [comment]
This happens because the other script doesn't have the `tool` keyword, so Godot doesn't load its script. The same kind of error would happen if you tried to call a function as well.
