### ISSUE TITLE
Screenshotting fullscreen game results in "out-of-date" screenshot

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26327]
**Godot version:**
3.1 beta8

**OS/device including version:**
Windows 10 x64, NVidia GTX 1060

**Issue description:**
When you make a screenshot (PrintScreen) of fullscreen game, the screenshot isn't... up-to-date. It results in capturing whatever the game was showing on startup. To get "up-to-date" screenshot, you need to unfocus the game and focus it again, so the captured content gets "updated". Running in borderless mode doesn't help.

**Steps to reproduce:**
1. Run a fullscreen game
2. Do something that changes stuff on the screen
3. Press PrintScreen
4. Look at your screenshot (happy being a time traveller? :v)

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2907785/TestProject.zip)
Just run it and make a screenshot after few seconds. The Godot icon should be at the far left on the screenshot.

**Comment by SradnickDev** [comment]
Same issue in Godot 3.0.6.
But also an old one https://github.com/godotengine/godot/issues/953

**Comment by sparkart** [comment]
Tested 3.1.1 stable and v3.2.dev.custom_build.a52b21af2
Running on Window 10 x64, GeForce GTX 860M/PCIe/SSE2

Works fine for me.

**Comment by KoBeWi** [comment]
I can still reproduce it in f410e7a8a.

**Comment by Calinou** [comment]
I noticed this is a common problem when using <kbd>PrintScreen</kbd> with fullscreen games on Windows in general. I'm not sure if it can be fixed.

**Comment by KoBeWi** [comment]
I tried with `fullscreen` option off, but `always on top` and `borderless` enabled and a full resolution, which makes it effectively a "non-exclusive fullscreen" and it still doesn't help. There ARE fullscreen games that can get screenshotted just fine, so there's a room for improvement there in Godot.

**Comment by Calinou** [comment]
I noticed this issue is a duplicate of https://github.com/godotengine/godot/issues/953, so I'll close this one.
