### ISSUE TITLE
Godot warns about missing resources during reimport

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26324]
**Godot version:**
3.1 beta8

**Issue description:**
When you open a project without .import directory and lots of big textures, Godot will trigger a massive reimport at startup, complaining about broken dependencies. Scenes are loaded at the same time as resources are imported, so anything that wasn't loaded yet is considered a missing dependency (when in fact it's just still importing).

**Steps to reproduce:**
1. Add some big texture to your project
2. Put it on any scene that loads on startup, so it's a dependency
3. Close Godot
4. Remove .import directory
5. Run Godot
6. This thing happens:
![image](https://user-images.githubusercontent.com/2223172/53448259-42bf4180-3a17-11e9-83c0-4962ac44961a.png)

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2907635/TestProject.zip)

**Comment by qarmin** [comment]
Can't reproduce on Ubuntu 18.04, but seems to be same when I try to import TPS Demo(https://github.com/godotengine/tps-demo) with cleared .import and project cache(e.g. /home/rafal/.config/godot/projects). When I try to load this project then Godot try to load files from not existent files in .import folder

![wqr](https://user-images.githubusercontent.com/41945903/53470193-26e08d80-3a61-11e9-8861-dc0d623d5c2b.png)

**Comment by akien-mga** [comment]
@qarmin That might have been due to #26342, fixed by f1e3bb0.

**Comment by akien-mga** [comment]
I don't reproduce the issue with the MRP in the OP with current master (36de6c1) on Linux. It might also have been fixed by f1e3bb0.

**Comment by akien-mga** [comment]
Also, do you have the editor setting "Restore Scenes On Load" enabled?

**Comment by KoBeWi** [comment]
> Also, do you have the editor setting "Restore Scenes On Load" enabled?

Yes, but this happens also when only the main scene is opened.

**Comment by akien-mga** [comment]
It might be fixed by eb2b9b8 then.

**Comment by KoBeWi** [comment]
Yeah, that indeed fixed it.
