### ISSUE TITLE
Duplicate inspector folding option in editor settings

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26323]
**Godot version:**

3.1 beta8

**Issue description:**

In editor settings, there's an option under Interface/Editor called "Disable Inspector Folding". Enabling it seems to do nothing. That is probably because under Interface/Inspector, there's a duplicate option called "Disable Folding", which works properly.

**Comment by KoBeWi** [comment]
Update: looks like it was a stray option from previous version. Godot just shows anything you have in editor settings, even if something doesn't exist in standard configuration.
![image](https://user-images.githubusercontent.com/2223172/53763855-1484aa80-3ecc-11e9-83b6-b72d8212c4d1.png)

**Comment by akien-mga** [comment]
Yeah that's on purpose, you can add your own options in the ProjectSettings for your game.

The stray option from a previous engine version is a consequence of this, and can't be fixed, unless we drop support for the aforementioned feature.
