### ISSUE TITLE
Can't right-click on empty space in file manager

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26329]
**Godot version:**
3.1 beta8

**Issue description:**
Right-clicking here
![image](https://user-images.githubusercontent.com/2223172/53451867-21af1e80-3a20-11e9-862c-71316896124d.png)
does nothing. IMO it should work the same as right-clicking res:// (and probably explicitly select the res:// directory).

**Comment by groud** [comment]
I think that would be misleading. There is no reason why an empty space would pop-up something. 
Especially when you a have a folder hierarchy, I don't think the res folder diserves a special treatment.

**Comment by neikeq** [comment]
If anything, it should unselect any file or directory that is selected.

**Comment by KoBeWi** [comment]
Well, it's useful when you create a new project and res:// is your only directory ¯\\_( •\_•)\_/¯
That's when I got the idea at least. Maybe it that right-click could count as clicking the last directory in list or last file...

**Comment by volzhs** [comment]
yes. it's pretty common action that right click on empty space on most OS.
creating a new file or directory, or changing an option for view or etc...
also I agree with this needs a discussion.

**Comment by groud** [comment]
> it's pretty common action that right click on empty space on most OS.

It is in the file list, where it makes sense since it's the empty area can correspond to the current folder.
In our tree structure, it is unclear that a click on the empty area is going to open either the res:// folder, the selected folder or the last folder in the structure.

That's why, to avoid any confusion, I would rather not have a popup menu when you click on an empty space.

**Comment by akien-mga** [comment]
IMO it's fine if a right click on empty space triggers the same dialog as a click on `res://`.

I tried in Dolphin and it works this way, even in Tree mode. (But the Tree mode is still starting from the current working directory, which is the one used to e.g. create new files/folders in. In our case it would always be `res://` as the Tree mode is always from there.)

**Comment by turtletooth** [comment]
It is common to right-click empty space to create new items in other software/platforms.  It feels very counter-intuitive to have to right click on a resource to create a new resource.
