### ISSUE TITLE
New collision layer labels not visible in previously opened node

### ISSUE THREAD

**Issue by dvdbrink** [godotengine/godot#26345]
**Godot version:** 3.1 beta8

**OS/device including version:** Windows 10 1803

**Issue description:**
Collision layer labels are not refreshed in previously opened node. Must re-open node to see newly added collision labels.

**Steps to reproduce:**
![ezgif-2-64667dbec0c1](https://user-images.githubusercontent.com/583528/53482059-b183b580-3a7e-11e9-9bdd-7f13553477b0.gif)

**Minimal reproduction project:**
Reproducible with new project from scratch.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/29991, as this is actually a bug.
