### ISSUE TITLE
GLES2 Android "Directional shadow framebuffer status invalid" on Google Nexus 7 / NVIDIA Tegra 3

### ISSUE THREAD

**Issue by qonnop** [godotengine/godot#26344]
**Godot version:**
caa42667e (includes recent 01a3dd3)

**OS/device including version:**
Google Nexus 7 (2012) with NVIDIA Tegra 3 (official 5.1.1 "nakasi" image)

**Issue description:**
Followup issue to #24952 
Godot splash is ok, black screen afterwards due to invalid directional shadow framebuffer (see relevant logcat output below)

```
D/libEGL  (20580): loaded /system/lib/egl/libEGL_tegra.so                                                                                                  
D/libEGL  (20580): loaded /system/lib/egl/libGLESv1_CM_tegra.so                                                                                            
D/libEGL  (20580): loaded /system/lib/egl/libGLESv2_tegra.so                                                                                               
I/OpenGLRenderer(20580): Initialized EGL, version 1.4                                                                                                      
D/OpenGLRenderer(20580): Enabling debug mode 0                                                                                                             
V/WindowManager(  510): Adding window Window{2c2d725f u0 SurfaceView} at 4 of 12 (before Window{31e53080 u0 com.example.gles2/org.godotengine.godot.Godot})
W/GodotView(20580): Trying ConfigChooser fallback                                                                                                          
W/GodotView(20580): creating OpenGL ES 2.0 context :                                                                                                       
I/godot   (20580): OpenGL ES 2.0 Renderer: NVIDIA Tegra 3                                                                                                  
E/godot   (20580): **ERROR**: Directional shadow framebuffer status invalid                                                                                
E/godot   (20580):    At: drivers\gles2\rasterizer_scene_gles2.cpp:3332:initialize() - Directional shadow framebuffer status invalid                       
I/ActivityManager(  510): Displayed com.example.gles2/org.godotengine.godot.Godot: +1s803ms                                                                
E/godot   (20580): **WARNING**: Could not create framebuffer!!                                                                                             
E/godot   (20580):    At: drivers\gles2\rasterizer_storage_gles2.cpp:4335:_render_target_allocate() - Could not create framebuffer!!                       
```

**Steps to reproduce:**
Open sample project and run on tablet

**Minimal reproduction project:**
Same as in #24952: [GLES2.zip](https://github.com/godotengine/godot/files/2909383/GLES2.zip)

**Comment by qonnop** [comment]
@usbhell Could you check whether your Google Nexus still shows the same issue based on current master?

**Comment by usbhell** [comment]
Still a problem, audio is playing in the background but screen is black. 

I find this line of code returns null which is not correct, but perhaps unsurprising since the screen is black.
var img = get_viewport().get_texture().get_data()

**Comment by usbhell** [comment]
btw I'm getting that "Directional shadow framebuffer status invalid error" in the console on my mac as well

**Comment by reduz** [comment]
Can you guys download this (or a similar one)
https://play.google.com/store/apps/details?id=com.realtechvr.glview&hl=en_US
And paste here the list of extensions supported by Tegra3? Evidently something is needed for 32 bit depth buffers in there.

**Comment by usbhell** [comment]
I see this is closed, heres the info anyway.

[bluetooth_content_share.txt](https://github.com/godotengine/godot/files/2912575/bluetooth_content_share.txt)

**Comment by qonnop** [comment]
It still does not work, but it definitely sets `config.depth_internalformat = GL_DEPTH_COMPONENT16; config.depth_type = GL_UNSIGNED_SHORT;` in [rasterizer_storage_gles2.cpp:4993](https://github.com/godotengine/godot/blob/057d3e874dfc3f44b2ea24d807278ee234b12bb6/drivers/gles2/rasterizer_storage_gles2.cpp#L4993) now.

The texture size seems to be irrelevant, I also tried with size 512 and 1024 (project settings).

Btw, the `storage->config.use_rgba_3d_shadows` condition evaluates to false in [rasterizer_scene_gles2.cpp:3317](https://github.com/godotengine/godot/blob/057d3e874dfc3f44b2ea24d807278ee234b12bb6/drivers/gles2/rasterizer_scene_gles2.cpp#L3317), so this cannot not be the cause.

I tried to figure out the difference compared to godot 2.1, where rendering worked, but I did not find the relevant parts yet...

**Comment by akien-mga** [comment]
> Btw, the `storage->config.use_rgba_3d_shadows` condition evaluates to false in [rasterizer_scene_gles2.cpp:3317](https://github.com/godotengine/godot/blob/057d3e874dfc3f44b2ea24d807278ee234b12bb6/drivers/gles2/rasterizer_scene_gles2.cpp#L3317), so this cannot not be the cause.

That's actually a good hint, as it means you don't support `GL_OES_depth_texture` (and judging by the logs, neither does @usbhell), so all this logic using `GL_DEPTH_COMPONENT` in `glTexImage2D` cannot work.

`glTexImage2D` in OpenGL ES 2.0 doesn't support `GL_DEPTH_COMPONENT` format initially: https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexImage2D.xml (it does in OpenGL ES 3.0: https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml)

`GL_OES_depth_texture` adds support for it in OpenGL ES 2.0: https://www.khronos.org/registry/OpenGL/extensions/OES/OES_depth_texture.txt
So for your hardware, @reduz will have to come up with an alternative.

Finally the check added in 057d3e8 for `GL_OES_depth24` is wrong (and broke rendering for me, reopening #24952), as this extension is only for *storage*, not for `glTexImage2D`: https://www.khronos.org/registry/OpenGL/extensions/OES/OES_depth24.txt

@reduz will fix it later today or tomorrow.

**Comment by reduz** [comment]
I am certain it does fix the issue, so closing unless it' s verified it happens again.

**Comment by qonnop** [comment]
Great! It works! 👍 Thx a lot!

**Comment by usbhell** [comment]
All working nicely here too, thanks.
