### ISSUE TITLE
how about script class？

### ISSUE THREAD

**Issue by yuyubibibobibo** [godotengine/godot#26341]
this class Description is A class stored as a resource.   it is like unitys scriptable object that can be serialized？

**Comment by groud** [comment]
>  it is like unitys scriptable object that can be serialized

Well, yeah scripts are like any other resource.

As your sentence is not really clear, I guess this is a question about the Script class. If you have such question please ask first on the other [community channel](https://godotengine.org/community). Guthub is to submit bug or ask for new features. :)
