### ISSUE TITLE
Previous scenes/scripts and project layout not loading up

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#26359]
**Godot version:**
 eb2b9b8

**Issue description:**
When opening up a project, it fails to load previous opened scenes/scripts, and the project's editor layout.

**Comment by akien-mga** [comment]
The project layout part may be #26349.

**Comment by YeldhamDev** [comment]
@akien-mga Please reopen this, it can still happen at random.

**Comment by akien-mga** [comment]
You already opened another issue regarding scripts, and I'm pretty sure the layouts issue was a different bug, so what is it exactly that can still happen at random? If it's only about scenes, I'd prefer a new bug report.

**Comment by YeldhamDev** [comment]
That issue is about **built-in** scripts. This is one about general scripts and the layout, albeit it stopped happening again, so I'll open a new issue if it comes back.
