### ISSUE TITLE
Unsafe multiplayer mechanics?

### ISSUE THREAD

**Issue by PonasKovas** [godotengine/godot#26365]
**Godot version:**
3.1beta8

**OS/device including version:**
ArchLinux

**Issue description:**
Recently I have been working with Godot's multiplayer mechanics, and I found that if you have two separate scripts, one for the server, and one for the client like this:

Client.gd

```

extends Node

const SERVER_IP = "localhost"
const SERVER_PORT = 22122

func _ready():
    var peer = NetworkedMultiplayerENet.new()
    peer.create_client(SERVER_IP, SERVER_PORT)
    get_tree().set_network_peer(peer)
    get_tree().set_meta("network_peer", peer)
    get_tree().connect("connected_to_server", self, "_connected_ok")

func _connected_ok():
    rpc_id(1, "some_function")

remote func some_function():
    # Some malicious code
    get_tree().quit()
    pass

```

Server.gd

```

extends Node

const SERVER_PORT = 22122
const MAX_PLAYERS = 10

func _ready():
    var peer = NetworkedMultiplayerENet.new()
    peer.create_server(SERVER_PORT, MAX_PLAYERS)
    get_tree().set_network_peer(peer)
    get_tree().set_meta("network_peer", peer)

remote func some_function():
    # Intended code
    print("Something")

```

The code specified in Client.gd for some reason will get executed at the server side, and the player can change that code to whatever he wants.

**Comment by akien-mga** [comment]
CC @Faless

**Comment by Faless** [comment]
@PonasKovas that's expected, and is what the `remote` keyword does. Call the function with that name on the remote note with that same path. No matter who is the caller.
You might want to use `master`/`puppet` keyword instead, depending on the behaviour you want.
Did you have a look at the docs [about the RPC modes](http://docs.godotengine.org/en/latest/classes/class_multiplayerapi.html#enumerations)?

**Comment by gau-veldt** [comment]
@Faless However, the server should have it's own code for the RPC method called and code in Client.gd shouldn't exist at the server.  That the server runs code it never sees is suspect here.

**Comment by gau-veldt** [comment]
I try the above example and server prints the expected "Something" message while the client does not quit (so it's some_function doesn't get run).  This means the RPC call at the client is only triggering the one on the server.

**Comment by Faless** [comment]
> I suspect the OP is expecting the client side to execute quit() and the server side to print "Something" into the output console.

Oh, I see... that can't happen.

>  so this isn't a fair test since OP is using linux

It doesn't matter, that really can't happen, code can't be passed across network in any way unless `allow_object_decoding` is enabled (and that's anyway largely untested), and that's definitely not done automatically.

Under the hood it resolve to:
- Search for caller path in tree
- Check that path exists in local tree.
- Check that function/variable with given name exists in node at path in the local tree
- Check that mode is respected
- Check the types are correct (when available)
- Call function locally.

No code passed across network.

Can @PonasKovas provide a minimum reproduction project?

**Comment by gau-veldt** [comment]
I am going to make a guess that the problem is going to be on OP's side and perhaps with a hybrid design where the same game may be a set up to be a client or a server, and, where it is incredibly easy to not have the correct script loaded at the right time to handle things correctly (so say one game running is set to be the server but somewhere the game uses one of the client role scripts unintentionally when a server role script should be loaded instead).  It may appear the client is sending the server code when in fact what is actually happening is that the server is using one of the game's own local client role scripts erroneously.
