### ISSUE TITLE
Polygon2D UV editor leads to crash in RasterizerCanvasGLES3::canvas_render_items

### ISSUE THREAD

**Issue by hellodenq** [godotengine/godot#26366]
**Godot version:**

godot 3.1 beta 8

**OS/device including version:**

Mac OS X 10.14.3

**Issue description:**

Godot crashing a lot on editing Polygon2D in Polygon2D Editor.

**Steps to reproduce:**
1. Create scene
2. Add Polygon2D
3. Assign texture in Polygon2D texture slot
4. Open Polygon 2D UV Editor
5. Press "Points"
6. Press "Create Polygon"
7. Start putting polygon points
8. Engine crashes with dump.

Link to video: https://www.dropbox.com/s/e9stykvbt09ncin/screencast1.mov?dl=0  (194M)

I have Skeleton2D and Bones in video, but in reality you don't need them to reproduce this issue, like I did in attached minimal project.

**Minimal reproduction project:**

[P2DIssue.zip](https://github.com/godotengine/godot/files/2911755/P2DIssue.zip)

**Comment by akien-mga** [comment]
CC @reduz @YeldhamDev

**Comment by YeldhamDev** [comment]
Tried to reproduce it in Manjaro GNU/Linux, but the polygon was built fine, with only printing this error:
`servers/visual/visual_server_canvas.cpp:773 - Condition ' ps % 3 != 0 ' is true.`

**Comment by hellodenq** [comment]
I have a crash dump from OSX, if it helps.

[Godot_2019-02-27-212742_Bkkpro.crash.zip](https://github.com/godotengine/godot/files/2914190/Godot_2019-02-27-212742_Bkkpro.crash.zip)

**Comment by akien-mga** [comment]
Backtrace from above crash dump:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff62a5323e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff62b09c1c pthread_kill + 285
2   libsystem_c.dylib             	0x00007fff629bc1c9 abort + 127
3   org.godotengine.godot         	0x0000000106158f72 handle_crash(int) + 2898
4   libsystem_platform.dylib      	0x00007fff62afeb3d _sigtramp + 29
5   ???                           	000000000000000000 0 + 0
6   com.apple.GeForceGLDriver     	0x00007fff3071956f 0x7fff3042c000 + 3069295
7   com.apple.GeForceGLDriver     	0x00007fff3071a767 gldBufferSubData + 218
8   GLEngine                      	0x00007fff3f85dea5 glBufferSubData_Exec + 605
9   org.godotengine.godot         	0x0000000106966e1a RasterizerCanvasGLES3::canvas_render_items(RasterizerCanvas::Item*, int, Color const&, RasterizerCanvas::Light*, Transform2D const&) + 65802
10  org.godotengine.godot         	0x0000000108171c1c VisualServerCanvas::render_canvas(VisualServerCanvas::Canvas*, Transform2D const&, RasterizerCanvas::Light*, RasterizerCanvas::Light*, Rect2 const&) + 1868
11  org.godotengine.godot         	0x00000001081aad18 VisualServerViewport::_draw_viewport(VisualServerViewport::Viewport*, ARVRInterface::Eyes) + 2904
12  org.godotengine.godot         	0x00000001081ab5ba VisualServerViewport::draw_viewports() + 714
13  org.godotengine.godot         	0x0000000108180de3 VisualServerRaster::draw(bool, double) + 323
14  org.godotengine.godot         	0x000000010618d84f Main::iteration() + 959
15  org.godotengine.godot         	0x00000001061633f7 OS_OSX::run() + 615
16  org.godotengine.godot         	0x000000010616613b main + 811
17  libdyld.dylib                 	0x00007fff62913ed9 start + 1
```

**Comment by reduz** [comment]
Tested this, but unfortunately it does not seem to be enough to reproduce the crash. Are you testing with the demo project you attached yourself? I even ran under valgrind and created plenty of polygons and did not see anything wrong. 

On the video you should a more complex rig including bones, so maybe the demo is incomplete?

**Comment by hellodenq** [comment]
Yes, I tested it. But, anyways, I can attach original project for you if it helps. I use scene sirena.tscn from this project in my video.
[Anima.zip](https://github.com/godotengine/godot/files/2922102/Anima.zip)
