### ISSUE TITLE
Changing mouse cursor during meta hover events cause debugger error

### ISSUE THREAD

**Issue by Kinsman** [godotengine/godot#26368]
**Godot version:**
Version 3.1 beta 8
**OS/device including version:**
Windows 10

**Issue description:**
If you create a RichTextLabel and attach methods to the meta_hover_started and meta_hover_ended events, which change the default mouse cursor, and then run the program in the editor, the program will freeze and then close, giving the error
drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054
Debug Process Stopped

**Minimal reproduction project:**
[Meta Link Bug.zip](https://github.com/godotengine/godot/files/2911928/Meta.Link.Bug.zip)

(Issue #20719 may be related)

**Comment by Kinsman** [comment]
I should add that this is when the Meta Underline property is set to false. If Meta Underline is turned on, the rich text label has its own cursor-changing events which work fine in the debugger.

**Comment by mo7sener** [comment]
I'm on it.
