### ISSUE TITLE
Wrong animation interpolation.

### ISSUE THREAD

**Issue by RepairUnit3k6** [godotengine/godot#26363]
**Godot version:**
Official beta 8

**OS/device including version:**
GNU/Linux Ubuntu
**Issue description:**
If I export rigged and animated model from blender to godot using [direct export plugin](https://github.com/godotengine/godot-blender-exporter). Log get spammed with errors. I had discussion with author of plugin in issue [here](https://github.com/godotengine/godot-blender-exporter/issues/142). I belive you'll see information in discusion rather usefull.
**Steps to reproduce:**
Open attached .blend file and export it into godot using [blender to godot direct exporter](https://github.com/godotengine/godot-blender-exporter). Play only available animation and get spammed with errors.

**Minimal reproduction project:**
[Cube.zip](https://github.com/godotengine/godot/files/2911616/Cube.zip)

**Comment by Jason0214** [comment]
Hey @hpvb, reduz told me to ask you could it be caused by some building flags? It is basically some float rounding error issue, quaternion becomes non-normalized after interpolation in Animation System and it happened in the last two 3.1 beta releases.

**Comment by tofuhead** [comment]
hi, I can confirm this. bunch of:
ERROR: slerp: Condition ' !is_normalized() ' is true. returned: Quat()
   At: core/math/quat.cpp:150.

if you change the  animation track interpolation mode to "Nearest", works fine.

I tried with self built Godot (which I usually use), and ofcourse with the official rc-1 version. 
On Linux.. not using any special flags for my own build. 



.b

**Comment by doyouknowaboutq** [comment]
i did 90 the max angle setting in animation import menu then animation working perfectly with linear interpolation mode on godot 3.1 official.

besides, the keyframes look exactly like on the blender.

**Comment by doyouknowaboutq** [comment]
i did 360 the max angle setting in animation import menu then animation working perfectly with linear interpolation mode on godot 3.1 official.

besides, the keyframes look exactly like on the blender.

i think it only works with "Scene Animation" export mode.

**Comment by phaitonican** [comment]
Have the same bug with Blender 2.8 and latest exporter release .
It seems (like above said) adding ANY Object Constraint in Blender to the object solves the problem for me. Now every animation get's exported without needing to set the keyframe interpolation in Godot to "nearest".
Also it doesn't matter which export mode, if it is "animations as actions" or something else (It can be anything, at least for me, what makes it work is setting any Object Constraint in Blender, for example Rotation Limiter without setting any value like above said)

**Comment by Toshiwoz** [comment]
#29583

Just for reference, I've created this pr, and it seems to be related.

**Comment by TokageItLab** [comment]
Maybe this problem does not exist anymore because slerp and optimizer have been fixed.
