### ISSUE TITLE
Only the First Shape in the Tile Set Editor is Selectable

### ISSUE THREAD

**Issue by AlmostBearded** [godotengine/godot#26369]
**Godot Version:** 
Latest 3.1 Master Branch (Commit: a5370b1b1bed3744941c90b4a05d4516aabd4c67)

**OS/device including version:** Windows 10

**Issue description:**
When creating multiple shapes with the new tileset editor the newly created shapes are not selectable. The first shape will be selected all the time. See the gif below.

![](https://thumbs.gfycat.com/JubilantDiscreteDodobird-size_restricted.gif)

Got obvious after fixing #24003.

**Steps to reproduce:**
1. Create a new tile set
2. Add any texture to it
3. Create a new tile (doesn't matter which type)
4. Click on collision and create a new poly shape
5. Create another poly shape
6. Try to select the new poly shape to edit it

**Minimal reproduction project:**
[TileSetEditor_ShapeSelectionBug.zip](https://github.com/godotengine/godot/files/2911949/TileSetEditor_ShapeSelectionBug.zip)

**Comment by AlmostBearded** [comment]
I'm currently implementing a fix for this. It already works pretty well but I need to fix some corner cases and do some more testing. Pull request should be ready in 2 days when I get the time to finish it.

**Comment by MarianoGnu** [comment]
@AlmostBearded please chech #26385, this adds a way to select shapes using a tool button or a keyboarrd shortcut (AvPag/RePag) if you want to make a PR to also allow to select shapes with the mouse you are very welcome.

**Comment by AlmostBearded** [comment]
@MarianoGnu I just uploaded my PR. I hope that our implementations are quite compatible. https://github.com/godotengine/godot/pull/26438
