### ISSUE TITLE
Changing method's name during connecting prevents Enter from confirming the signal

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26362]
**Godot version:**
3.1 beta8

**Issue description:**
When you connect signal through editor, there's this signal connection popup where you select node, method name etc.
When you don't touch anything and press Enter, your signal is correctly confirmed and window is closed.
But when you change anything (tested with changing method name), pressing Enter does nothing and you need to press Connect button manually.

**Steps to reproduce:**
1. Select a node.
2. Go to signal tab in inspector.
3. Double click any signal
![image](https://user-images.githubusercontent.com/2223172/53510755-09daa780-3abf-11e9-8e75-95ad3b346396.png)
4. Change method name
![image](https://user-images.githubusercontent.com/2223172/53510838-34c4fb80-3abf-11e9-91ad-e47202913e96.png)
5. Press Enter to confirm the signal
6. Repeat from point 5 in infinite frustration

On a side note, pressing Escape always works.

**Comment by ankitpriyarup** [comment]
The Enter button is supposed to click on the selected element which we can switch through using tab. Initially, Connect button is selected so pressing Enter hides the dialog but later when we change the method In Node to something else the text box gets selected so pressing enter won't have any effect.

It will make sense if we can click on a selected element using space only right now it's space and enter both will work and pressing enter will make the dialog close with the positive button here connect.

**Comment by ankitpriyarup** [comment]
@KoBeWi Can you verify my commit and let me know if it solves what you wanted then I'll create a PR.

**Comment by KoBeWi** [comment]
@ankitpriyarup Yeah, that works.
