### ISSUE TITLE
Create new scene from file system dock

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26377]
**Godot version:**
3.1 beta8

**Issue description:**
3.1 introduced some QoL context menu entries for creating a Script or Resource from within the file system dock (by right-clicking something there). It's so convenient that I sometimes try to create a scene this way, only to discover (yet again) that the "New scene" button is missing. IMO it should be there.

I know we can create a scene by clicking Scene -> New scene, but we can also create a script from File -> New script, and yet the New script option was added to file explorer. As a bonus, inheriting scene option could be there too.
Eh, now that I think of it, you create a scene by saving, because you need a root node, but maybe this option could create a somewhat empty scene file.

**Comment by akien-mga** [comment]
>  Eh, now that I think of it, you create a scene by saving, because you need a root node, but maybe this option could create a somewhat empty scene file.

Well that's the main issue, what would be in this "empty" scene file? If it defaults to a scene file with a "Node" root, it's probably more bother than gain, as you will need to delete and readd a root 99% of the time. If it forces you to select a root before you can save the file, the workflow is also worse UX-wise than just pressing "+" in the main viewport's tabs to create an empty scene, add a root and save it.

**Comment by KoBeWi** [comment]
Maybe there could be some dialog similar to new script dialog, where you select scene root? Or it could open a new scene tab, but modify the current path, i.e. when you press save, it would open the selected directory from file system dock. The latter sounds viable actually.
