### ISSUE TITLE
Allow for comparing variables of different types

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26375]
**Godot version:**
3.1 beta8

**Issue description:**
Right now you can't compare variables of different types. To do so, you first need to use typeof of whatever to check whether they are the same type and then compare it. The type-checking step is done anyways, as comparing variables of different types results in an error. So why not, instead of giving error, just return false?

Then we could do
`if 1 == "0":` (imagine 1 and "0" are variables not hard-coded values)
instead of
`if typeof(1) == TYPE_STRING and 1 == "0":`
which both result in false, but the former is much cleaner.

**Comment by Zylann** [comment]
In my opinion, that would open a lot of confusing bugs. Being that permissive in type coercion opens the door to many situations appearing to run fine but fail way later, while mismatching types should not have happened in the first place. Strings and numbers just are not the same thing, I would not expect them to be try-parsed just to absolutely fulfill a condition right away. If I expect a string, I parse it. If the variable **can** sometimes be a string or sometimes a number, I call this a case to take care of explicitely (which also self-documents), or a design flaw.

**Comment by KoBeWi** [comment]
> when this happens it's almost always an actual error in my code. If a variable got misassigned to a mismatching type, it's it a lot quicker to find.

Eh, then just change the error to warning, so I can disable it. (and ofc it should return false)

**Comment by Calinou** [comment]
You can shorten the type check (while making it faster) using the `is` keyword, which works with all types since 3.1:

```gdscript
if 1 is String and 1 == "0":
    # …
```

**Comment by KoBeWi** [comment]
This problem was basically gone when I started using types .-.
