### ISSUE TITLE
Errors with loading resources with the exported exe/pck file

### ISSUE THREAD

**Issue by andrekim93** [godotengine/godot#26379]
**Godot version:**

v3.1.alpha.official

**OS/device including version:**

**Issue description:**

SCRIPT ERROR: GDScript::load_byte_code: Parse Error: At 'bytes2var()' call, argument 1. Assigned type (String) doesn't match the function argument's type (PoolByteArray).
          At: res://globals/globals.gdc:71
ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:784
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2135
ERROR: Failed loading resource: res://globals/globals.gdc
   At: core/io/resource_loader.cpp:279
ERROR: poll: res://globals/globals.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://globals/globals.gd
   At: scene/resources/scene_format_text.cpp:439
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:202
ERROR: Failed loading resource: res://globals/globals.tscn
   At: core/io/resource_loader.cpp:279
ERROR: Can't autoload: res://globals/globals.tscn
   At: main/main.cpp:1537
ERROR: load_image: Error opening file: res://icon.png
   At: core/io/image_loader.cpp:56
SCRIPT ERROR: _ready: Invalid get index 'username' (on base: 'Nil').
          At: res://globals/HUD.gdc:12

I pasted above the initial errors. Seems like some scenes arent exported to the exe/pck? Not sure why only a couple of scenes are there and some arent. I have a title screen scene on startup that has a button that leads into another scene, but when I click on it, a series of errors show up and no scene change happens. I have another button that changes to a options scene that works fine, except all the buttons and sliders don't update or show anything.

SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Too many arguments for 'var2bytes()' call. Expected at most 1.
          At: res://scripts/match3/grid.gdc:118
ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:784
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2135
ERROR: Failed loading resource: res://scripts/match3/grid.gdc
   At: core/io/resource_loader.cpp:279
ERROR: poll: res://scenes/match3/match3.tscn:9 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scripts/match3/grid.gd
   At: scene/resources/scene_format_text.cpp:439
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:202
ERROR: Failed loading resource: res://scenes/match3/match3.tscn
   At: core/io/resource_loader.cpp:279
SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Can't preload resource at path: res://scenes/match3/match3.tscn
          At: res://scripts/map.gdc:8
ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:784
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2135
ERROR: Failed loading resource: res://scripts/map.gdc
   At: core/io/resource_loader.cpp:279
ERROR: poll: res://scenes/map.tscn:5 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scripts/map.gd
   At: scene/resources/scene_format_text.cpp:439
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:202
ERROR: Failed loading resource: res://scenes/map.tscn
   At: core/io/resource_loader.cpp:279

**Steps to reproduce:**
It has the same errors every startup. It worked okay on the 3.06, as in it went past the title screen so maybe its a 3.1 thing? I cant downgrade either, it wont open the project

**Minimal reproduction project:**

**Comment by LinuxUserGD** [comment]
I have the same problem on Linux on export

**Comment by andrekim93** [comment]
well nice to know its not a mess up on my end. i googled around beforehand and a case sensitive scene issue came up but all my scenes are lower case... hope theres a fix soon or a way to downgrade to 3.0

**Comment by LinuxUserGD** [comment]
Did you use Calinous godot template builds?

**Comment by andrekim93** [comment]
dont even know what that is, Godot_v3.1-alpha2_win64 is what the exe file is called

**Comment by akien-mga** [comment]
Could you try with 3.1 beta 8 or later? Alpha 2 is a very old build and not supported.

**Comment by LinuxUserGD** [comment]
@akien-mga I tried it with master .

**Comment by akien-mga** [comment]
Please provide an example project that reproduces the issue.

**Comment by LinuxUserGD** [comment]
Now I can also not reproduce this issue on master.

**Comment by andrekim93** [comment]
it seems to work okay with 3.1 beta 8, guess ill start using the newest builds from now. thanks for the help

**Comment by andrekim93** [comment]
the same issue popped up, but im not sure what causes it now. im using 3.1.1, the exported exe file works ok on the computer that has the project being worked on, but i attempted to run it off another pc, and the same issue occurred.

**Comment by clayjohn** [comment]
Closing as more up to date information is now contained in #28732
