### ISSUE TITLE
3.1b8 GLES 2: Sky emission seems to have disappeared.

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#26372]
**Godot version:**

3.1b8 GLES 2

**OS/device including version:**

Windows 7, DXDiag reports: "Intel(R) HD Graphics Family"

**Issue description:**

Game last ran in beta 3 had no directional lighting (scene has a single directional light) but got sky contribution (world had blue tinge from the sky).  In b8 things went opposite: directional light works but now world is completely black (no more blue tinge) meaning the sky contribution is gone.

Adjusting the ambient/sky ratio didn't fix.  If it's set to 100% sky as I mentioned world goes black (with directional light disabled).

**Steps to reproduce:**

Create a 3D scene.
Add a mesh (CSGBox should work in a pinch).
Add a directional light.
Add a camera and set its environment to use default_env.tres
Verify the sky is procedural, etc etc etc (the way it is in a new project's default_env.tres anyways)
Disable the light so any light in the scene has to come from the sky.
World is black (no sky tinge).

**Minimal reproduction project:**

[bugtesting.zip](https://github.com/godotengine/godot/files/2912181/bugtesting.zip)

**Comment by akien-mga** [comment]
Likely related to #25512.

**Comment by akien-mga** [comment]
Given that it's quite rare and old hardware, I'll move it to 3.2 milestone for now, but ideally we should be able to find a fix/workaround quickly and backport it to the 3.1 branch.

**Comment by kaadmy** [comment]
Example project works fine here with Godot 3.1-b10, Geforce 940MX.

**Comment by gau-veldt** [comment]
> 
> 
> Example project works fine here with Godot 3.1-b10, Geforce 940MX.

Windows 7, DXDiag reports: "Intel(R) HD Graphics Family"
Geforce isn't an Intel HD chipset

**Comment by kaadmy** [comment]
Sorry, it's an Nvidia card. Probably should have specified that.

**Comment by gau-veldt** [comment]
> 
> 
> Sorry, it's an Nvidia card. Probably should have specified that.

I specified in the issue this laptop has Intel HD chipset.  It's a chipset/GLES2 issue most likely.  Intel's are notorious for having hideously coded Windows drivers.  The chips are much more functional in linux under linux drivers.

**Comment by clayjohn** [comment]
Is this reproducible in 3.1.2?

**Comment by Calinou** [comment]
@gau-veldt Bump :slightly_smiling_face:

**Comment by gau-veldt** [comment]
Standby by on that one...  I have to make sure I test on that laptop against a 3.2 build.

**Comment by Calinou** [comment]
@gau-veldt Can you test in [Godot 3.2 rc3](https://godotengine.org/article/release-candidate-godot-3-2-rc-3) now? (Note that 3.2 rc4 is around the corner, it should be available tomorrow if all goes well.)

**Comment by Calinou** [comment]
Closing due to lack of response.

@gau-veldt I can reopen this issue if you confirm the issue is still present on 3.2.
