### ISSUE TITLE
GLES3 doesn't work on Linux (black screen)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#26378]
**Godot version:**
master (regression)

**OS/device including version:**
Arch Linux (Antergos)
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 

**Issue description:**
3d doesn't work

**Minimal reproduction project:**
Any

**Comment by clayjohn** [comment]
Is GLES2 broken or GLES3? Your title says GLES3 but the actual report says GLES2.

**Comment by LinuxUserGD** [comment]
GLES3 is broken.

**Comment by qarmin** [comment]
In Ubuntu 18.04 with GTX 970 GLES 3 and GLES 2 works

**Comment by akien-mga** [comment]
Can't reproduce on Mageia 7 x86_64 with Nvidia GTX 670MX opening the TPS demo, everything seems to work fine. Running 41708eb8.

**Comment by LinuxUserGD** [comment]
I updated to master again and now I can also not reproduce it anymore.
