### ISSUE TITLE
Writing `isnan(TANGENT)` in a shader causes rendering error but doesn't reports in the editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#26387]
Godot 3.1 beta8

Repro steps:
1) Create a mesh
1) Add a `ShaderMaterial` with a new spatial `Shader` on it
2) Write something not optimized-out which includes `isnan(TANGENT)`
3) Observe errors in the system console, but no feedback in the editor. Instead, rendering breaks.

This might not be the only expression that triggers this, it's just the one that occurred to me first.

Example project:
[IsNanTangentShaderError.zip](https://github.com/godotengine/godot/files/2913023/IsNanTangentShaderError.zip)

**Comment by Chaosus** [comment]
isnan returning a boolean vector if you pass TANGENT which is vector3. Do you except this expression to be correctly parsed ? - if(bvec3(true, false, true)) ?

**Comment by Chaosus** [comment]
For correct solving this problem use - "all" method

```
shader_type spatial;

void fragment() {
	if(all(isnan(TANGENT))) {
		ALBEDO = vec3(1.0, 0.0, 0.0);
	}
}
```

**Comment by Chaosus** [comment]
Hmm. @Zylann I read the description of this issue again and understand that you wanted that expression to report to editor in good form so for example 
if(bvec3(true, false, true)) should print "Incorrect comparsion for if flow operator" ? If im right - I could create a new one issue about it as my apologize

**Comment by akien-mga** [comment]
Yes this is issue is about properly reporting errors in the shader editor.

**Comment by Zylann** [comment]
Yes, I am aware the code is wrong, it's just not correctly reported.

**Comment by Chaosus** [comment]
@Zylann I Apologizes )

**Comment by akien-mga** [comment]
The error is now properly reported in the shader editor, with the affected line highlighted.

The only thing missing IMO is that if you don't have the shader editor open, it doesn't bring it up to show the error automatically. I'll open a new issue for that.
