### ISSUE TITLE
Template Tab Throws PNG Warnings

### ISSUE THREAD

**Issue by gdtbg** [godotengine/godot#26384]
**Godot version:**
3.1-beta8

**OS/device including version:**
Windows 10x64

**Issue description:**
Godot 3.1 beta 8 throws 2 PNG warnings when clicking on Templates tab.  Makes it look like Godot has errors immediately to new user. The template images may have incorrect profiles assigned.

**Steps to reproduce:**
Start Godot, click on Templates tab.

![profile-issues](https://user-images.githubusercontent.com/48073324/53531553-6fc82e80-3ac1-11e9-993d-a6e0cfc5bf58.PNG)

**Comment by qarmin** [comment]
Duplicate #22468
