### ISSUE TITLE
Duplicating a editor_only Light turns it dark

### ISSUE THREAD

**Issue by Windfisch** [godotengine/godot#26399]
**Godot version:** f2003b1a7e5d3fce6448bd578a15bbf8f9462183

**OS/device including version:** Linux/X11 Intel graphics

**Issue description:**

When a light with the `editor_only` property set is duplicated, then the duplicate light will not work in the editor (which is unexpected. It should shine). Unsetting the `editor_only`-property on that duplicate will turn it back on, and setting the property again will keep it on in the editor (which is expected).

**Steps to reproduce:**
1. Create a scene with only a Cube MeshInstance
2. Create an OmniLight or a DirectionalLight (or probably a SpotLight, not tested) and position it such that one face of the cube is lit.
3. Turn on its `editor_only` option. It will still light the cube in the editor.
3. Right-click the light in the` scene tree and choose "duplicate".
4. Move the newly created light so that it should light a different face of the cube. Notice that it does not light the face.
5. Uncheck and re-check `editor_only` on that second light. Now it will lights the face.

**Comment by Windfisch** [comment]
turns out that when duplicating the light, it appears that `_update_visibility` is called the last time through `NOTIFICATION_VISIBILITY_CHANGED`. This is when the `editor_ok` variable gets evaluated:
https://github.com/godotengine/godot/blob/996af809017f0e5c6f02298281fc7af835024878/scene/3d/light.cpp#L173
However, in the duplicate-case, `get_owner()` returns NULL.
On subsequent calls to `_update_visibility()` when toggling the `editor_only` or visiblility setting as described in Steps to reproduce, `get_owner()` will be set properly, which is why it works properly then.

It appears that `Node::_duplicate()` does not set `data.owner`, but only calls `Node::add_child()` to add the duplicated node to its parent; this will set `data.parent` but not `data.owner`. What is the difference between these two?
And how is `data.owner` set; I can only find calls to `set_owner` in `duplicate_and_reown()` and `_propagate_replace_owner()`.

**Comment by Windfisch** [comment]
The same bug can be triggered by reparenting such a light, just move it around in the Scene Tree

**Comment by Windfisch** [comment]
When the editor duplicates or re-parents a Node, the following happens (in that order):
1. (Remove the node from its old parent / Duplicate the node)
2. Add the node to its new parent.
2a. `NOTIFICATION_ENTER_TREE` is issued, the light checks its visibility. Because `owner` is NULL, it will not light the scene.
3. Set the node's `owner`. (Too late :( )

**Comment by Windfisch** [comment]
Hi @akien-mga, thanks for your update to #26965.

> Usually we very strongly favor ad hoc changes (possibly like the hack you implemented in Windfisch@d4b4e04) over extending the core (especially Object) API for a corner case.

While I find the solution with the notification cleaner and personally would favor it over an ad-hoc fix, I can understand your rationale for staying a way from such an intrusive change. Would you like me to file a PR for Windfisch@d4b4e04, possibly with a marker comment like `HACK` added?

**Comment by akien-mga** [comment]
> Would you like me to file a PR for Windfisch/godot@d4b4e04, possibly with a marker comment like HACK added?

Sounds good, yeah.

**Comment by Calinou** [comment]
@Windfisch  Can you (or anyone else) still reproduce this bug in [Godot 3.2.3](https://godotengine.org/article/maintenance-release-godot-3-2-3) or any later release?

Also, it might be worth checking if this is fixed in the `master` branch's Vulkan renderer.

**Comment by JestemStefan** [comment]
Reproducible in both v3.3.3.stable.official [b973f997f] and v4.0.dev.20210811.official [7188cb601]

**Comment by JestemStefan** [comment]
I feel a bit dirty for basically stealing this, but it's in a good faith 👼 I hope it's fine

**Comment by Windfisch** [comment]
THIEF!!1111 ;)
