### ISSUE TITLE
Godot Crashes when closing a scene with Mesh,Staticbodies,CollisionObjects

### ISSUE THREAD

**Issue by wombatstampede** [godotengine/godot#26393]
**Godot version:**
master branch debug build of today (28.02.2019) but happens also in ready built 3.1 betas (at least 7 and 8)
*GLES2*

**OS/device including version:**
Windows 10
NVIDIA GT610

**Issue description:**
Godot crashes when closing a scene (in GLES2) containing MeshInstances, StaticBodies, CollisionObjects (CollisionShapes have been removed in the demo project, it doesn't matter if they're there or not for the crash.)
When the project is run and then closed the same Trap happens.

> CrashHandlerException: Program crashed
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [0] RasterizerStorageGLES2::free (c:\tools\spiele\godot3\source\godot-master\drivers\gles2\rasterizer_storage_gles2.cpp:4770)
> [1] VisualServerRaster::free (c:\tools\spiele\godot3\source\godot-master\servers\visual\visual_server_raster.cpp:72)
> [2] VisualServerWrapMT::free (c:\tools\spiele\godot3\source\godot-master\servers\visual\visual_server_wrap_mt.h:580)
> [3] Material::~Material (c:\tools\spiele\godot3\source\godot-master\scene\resources\material.cpp:101)
> [4] SpatialMaterial::~SpatialMaterial (c:\tools\spiele\godot3\source\godot-master\scene\resources\material.cpp:2389)
> [5] SpatialMaterial::`scalar deleting destructor'
> [6] memdelete<Material> (c:\tools\spiele\godot3\source\godot-master\core\os\memory.h:122)
> [7] Ref<Material>::unref (c:\tools\spiele\godot3\source\godot-master\core\reference.h:271)
> [8] Ref<Material>::~Ref<Material> (c:\tools\spiele\godot3\source\godot-master\core\reference.h:285)
> [9] ArrayMesh::Surface::~Surface
> [10] ArrayMesh::Surface::`scalar deleting destructor'
> [11] CowData<ArrayMesh::Surface>::_unref (c:\tools\spiele\godot3\source\godot-master\core\cowdata.h:208)
> [12] CowData<ArrayMesh::Surface>::~CowData<ArrayMesh::Surface> (c:\tools\spiele\godot3\source\godot-master\core\cowdata.h:369)
> [13] Vector<ArrayMesh::Surface>::~Vector<ArrayMesh::Surface> (c:\tools\spiele\godot3\source\godot-master\core\vector.h:126)
> [14] ArrayMesh::~ArrayMesh (c:\tools\spiele\godot3\source\godot-master\scene\resources\mesh.cpp:1358)
> [15] ArrayMesh::`scalar deleting destructor'
> [16] memdelete<Mesh> (c:\tools\spiele\godot3\source\godot-master\core\os\memory.h:122)
> [17] Ref<Mesh>::unref (c:\tools\spiele\godot3\source\godot-master\core\reference.h:271)
> [18] Ref<Mesh>::~Ref<Mesh> (c:\tools\spiele\godot3\source\godot-master\core\reference.h:285)
> [19] MeshInstance::~MeshInstance (c:\tools\spiele\godot3\source\godot-master\scene\3d\mesh_instance.cpp:391)
> [20] MeshInstance::`scalar deleting destructor'
> [21] memdelete<Node> (c:\tools\spiele\godot3\source\godot-master\core\os\memory.h:122)
> [22] Node::_notification (c:\tools\spiele\godot3\source\godot-master\scene\main\node.cpp:163)
> [23] Node::_notificationv (c:\tools\spiele\godot3\source\godot-master\scene\main\node.h:46)
> [24] Spatial::_notificationv (c:\tools\spiele\godot3\source\godot-master\scene\3d\spatial.h:58)
> [25] Object::notification (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:955)
> [26] Object::_predelete (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:387)
> [27] predelete_handler (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:2012)
> [28] memdelete<Node> (c:\tools\spiele\godot3\source\godot-master\core\os\memory.h:117)
> [29] Node::_notification (c:\tools\spiele\godot3\source\godot-master\scene\main\node.cpp:163)
> [30] Node::_notificationv (c:\tools\spiele\godot3\source\godot-master\scene\main\node.h:46)
> [31] Spatial::_notificationv (c:\tools\spiele\godot3\source\godot-master\scene\3d\spatial.h:58)
> [32] Object::notification (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:955)
> [33] Object::_predelete (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:387)
> [34] predelete_handler (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:2012)
> [35] memdelete<Node> (c:\tools\spiele\godot3\source\godot-master\core\os\memory.h:117)
> [36] EditorData::remove_scene (c:\tools\spiele\godot3\source\godot-master\editor\editor_data.cpp:574)
> [37] EditorNode::_remove_edited_scene (c:\tools\spiele\godot3\source\godot-master\editor\editor_node.cpp:2734)
> [38] EditorNode::_remove_scene (c:\tools\spiele\godot3\source\godot-master\editor\editor_node.cpp:2744)
> [39] EditorNode::_discard_changes (c:\tools\spiele\godot3\source\godot-master\editor\editor_node.cpp:2448)
> [40] EditorNode::_scene_tab_closed (c:\tools\spiele\godot3\source\godot-master\editor\editor_node.cpp:4072)
> [41] MethodBind1<EditorNode,int>::call (c:\tools\spiele\godot3\source\godot-master\core\method_bind.gen.inc:815)
> [42] Object::call (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:943)
> [43] Object::emit_signal (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:1229)
> [44] Object::emit_signal (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:1286)
> [45] Tabs::_gui_input (c:\tools\spiele\godot3\source\godot-master\scene\gui\tabs.cpp:152)
> [46] MethodBind1<Tabs,Ref<InputEvent> const & __ptr64>::call (c:\tools\spiele\godot3\source\godot-master\core\method_bind.gen.inc:815)
> [47] Object::call_multilevel (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:777)
> [48] Object::call_multilevel (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:884)
> [49] Viewport::_gui_call_input (c:\tools\spiele\godot3\source\godot-master\scene\main\viewport.cpp:1542)
> [50] Viewport::_gui_input_event (c:\tools\spiele\godot3\source\godot-master\scene\main\viewport.cpp:1912)
> [51] Viewport::input (c:\tools\spiele\godot3\source\godot-master\scene\main\viewport.cpp:2669)
> [52] Viewport::_vp_input (c:\tools\spiele\godot3\source\godot-master\scene\main\viewport.cpp:1320)
> [53] MethodBind1<Viewport,Ref<InputEvent> const & __ptr64>::call (c:\tools\spiele\godot3\source\godot-master\core\method_bind.gen.inc:815)
> [54] Object::call (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:943)
> [55] Object::call (c:\tools\spiele\godot3\source\godot-master\core\object.cpp:867)
> [56] SceneTree::call_group_flags (c:\tools\spiele\godot3\source\godot-master\scene\main\scene_tree.cpp:262)
> [57] SceneTree::input_event (c:\tools\spiele\godot3\source\godot-master\scene\main\scene_tree.cpp:418)
> [58] InputDefault::_parse_input_event_impl (c:\tools\spiele\godot3\source\godot-master\main\input_default.cpp:440)
> [59] InputDefault::parse_input_event (c:\tools\spiele\godot3\source\godot-master\main\input_default.cpp:260)
> [60] OS_Windows::WndProc (c:\tools\spiele\godot3\source\godot-master\platform\windows\os_windows.cpp:711)
> [61] WndProc (c:\tools\spiele\godot3\source\godot-master\platform\windows\os_windows.cpp:949)
> [62] CallWindowProcW
> [63] CallWindowProcW
> [64] glDebugEntry
> [65] CallWindowProcW
> [66] DispatchMessageW
> [67] OS_Windows::process_events (c:\tools\spiele\godot3\source\godot-master\platform\windows\os_windows.cpp:2239)
> [68] OS_Windows::run (c:\tools\spiele\godot3\source\godot-master\platform\windows\os_windows.cpp:2804)
> [69] widechar_main (c:\tools\spiele\godot3\source\godot-master\platform\windows\godot_windows.cpp:151)
> [70] _main (c:\tools\spiele\godot3\source\godot-master\platform\windows\godot_windows.cpp:173)
> [71] main (c:\tools\spiele\godot3\source\godot-master\platform\windows\godot_windows.cpp:185)
> [72] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253)
> [73] BaseThreadInitThunk
> 

**Steps to reproduce:**
Open the enclosed demo project. And close the scene again. Godot should crash. (Maybe repeat opening and closing the scene.)
Or run the project and close it again.

**Minimal reproduction project:**
[crashgd.zip](https://github.com/godotengine/godot/files/2914139/crashgd.zip)

**Comment by Zireael07** [comment]
Fill out the template or this is going to get closed quick as unactionable.

**Comment by wombatstampede** [comment]
Sorry, pressed the wrong button. I now added the crash dump from the develop version and a "minimal" reproduction project. Couldn't make it simpler.

The crash does not happen when StaticBodies and CollisionObjects are removed.
The crash does not happen when all (two) materials are removed.

The crash did also happen when CollisionObjects had their shapes.

**Comment by qarmin** [comment]
I can't reproduce crash with this project, but seems that is same issue as #22619

**Comment by hpvb** [comment]
I can't reproduce with this project on Linux/x64 Radeon M either.

**Comment by wombatstampede** [comment]
Thank you! 
It now runs flawlessly (at least I tested a couple of time with no crahses)!
