### ISSUE TITLE
It's possible to create two children with the same name

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26390]
**Godot version:**
3.1 beta8

**Issue description:**
Godot normally auto-renames nodes, so that each child has an unique name. But there's a trick (which I unfortunately discovered in legit way), which allows to create two children with the same name. This leads to weird behaviors, like inability to delete one of them or that selecting one selects both.

**Steps to reproduce:**
1. Create a scene
2. Create another scene (2)
3. Add instance of scene 2 to scene 1
4. Add a child to scene 2's instance in scene 1
5. In scene 2, add a child and name it the same as the instance's child in scene 1
6. Go to scene 1 and now the instance of scene 2 has 2 children of the same name

This is how it looks after enabling editable children:
![image](https://user-images.githubusercontent.com/2223172/53538725-2b637f80-3b0f-11e9-91f0-421c0d8353f3.png)

Yeah, I know it's complicated, but as I said, I stumbled into it by accident, so it's not impossible to do unintentionally.

EDIT:
Also possible with inherited scenes.

EDIT:
Another way is to meddle with owners. See #59625

**Comment by KoBeWi** [comment]
I just found a (possible) duplicate: #14680

**Comment by santouits** [comment]
What would a suitable fix for this be? The scene 2 doesn't need to know about the scene 1, so you should be able to add there any node with any name. Then when you return to the scene 1, or open it, should the editor automaticaly delete the node you added there? Maybe automatically rename it if it in the editor? Or not load it at all if it is loaded inside a game.

**Comment by akien-mga** [comment]
See also #28133 for a slightly different way to reproduce this issue.

**Comment by akien-mga** [comment]
This is still reproducible in the current `3.x` branch.

**Comment by KoBeWi** [comment]
Seems like all cases are fixed.
