### ISSUE TITLE
queue_free is unsafe with tool scripts

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26409]
**Godot version:**
3.1 beta8

**Issue description:**
Sometimes it happens that you need to use queue_free() in a script which is a tool script. This leads to intentional or unintentional removals of nodes. I guess this should be avoided, but well, happens and is very unsafe to do. When you queue_free a node in editor, it's gone _forever_. What's worse, freeing scene root will crash the editor.

My proposal is to somehow handle queue_free in tool scripts more gently, I mean by the engine. Node removal shouldn't be so violent, maybe it could somehow register an undo action, the same way when deleting node manually from tree. Also, deleting a root node should properly set it to NULL wherever necessary ([see this](https://github.com/godotengine/godot/issues/24996#issuecomment-468356491)).

I know it probably introduces some overhead and could also apply to other tool script operations, as you can't undo any of them. But that's up to discussion.

(also it all obviously applies to free(), but queue_free() is just more commonly used)

**Comment by Zylann** [comment]
`queue_free` should do what it says. If my tool node is freeing generated children, I don't want them to pollute the undo history. If my tool deletes user nodes, it's up to the tool being able to undo its actions (there can be helpers to make this easier though, but not modifying the function itself).

**Comment by KoBeWi** [comment]
I guess this can be closed for the same reason as #35422
