### ISSUE TITLE
list click does not work (GLES 2)

### ISSUE THREAD

**Issue by ilyafuu** [godotengine/godot#26406]
**Godot version:**
3.1.beta.custom_build. 5a6bcff527efd8b7264f3d2812eb1d0a263661cd

**Issue description:**
Perspective and Orthogonal ===>

Display Normal
Display Wireframe
Display Overdraw
Display Unshaded

GLES3 =>>>
![_2019-02-28_22-21-53](https://user-images.githubusercontent.com/17591539/53592435-54375380-3ba7-11e9-8a06-c2c56d223450.png)
![_2019-02-28_22-24-39](https://user-images.githubusercontent.com/17591539/53592612-b7c18100-3ba7-11e9-9853-e9313f23edae.png)
![_2019-02-28_22-24-54](https://user-images.githubusercontent.com/17591539/53592623-bd1ecb80-3ba7-11e9-9297-1cf55b6c8321.png)

GLES2 =>>> (nothing changed)
![_2019-02-28_22-22-06](https://user-images.githubusercontent.com/17591539/53592467-64e7c980-3ba7-11e9-82ce-7c3eb9ec2164.png)

**Comment by clayjohn** [comment]
Could you be more clear about what you expected to happen and what the result was?

**Comment by Calinou** [comment]
I'll close this issue in favor of https://github.com/godotengine/godot/issues/27018, which is explained more clearly.
