### ISSUE TITLE
Running game in editor breaks system audio

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#26401]
**Godot version:**

```
3.0.6.stable.custom_build
```

**OS/device including version:**

```
Linux 4.20.11-arch2-1-ARCH
pulseaudio 12.2
nvidia 418.43-2
01:00.0 VGA compatible controller: NVIDIA Corporation GM204 [GeForce GTX 970] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GM204 High Definition Audio Controller (rev a1)
```

**Issue description:**

When I start godot and run my game before attempting to play any other
audio/video on my system, I am no longer able to play audio/video through other
programs.  Spotify says "Can't play the current song", youtube videos hang,
ect.

If I play a video/song before playing my game, I can continue doing so even
after running my game.  This only occurs when I run my game in godot _before_
trying to play audio/video through another program.  It isn't just opening
godot that causes this, but specifically running a scene in godot.

This might just be some oddity I need to figure out about my system, but I thought I'd post here in case others have a similar experience.

**Steps to reproduce:**

1. Open a godot project
2. Run your game
3. Open spotify/youtube/ect.
4. Try to play a song/video
5. Video won't play, spotify says "Can't play the current song"

**Steps that _won't_ reproduce:**

1. Open spotify/youtube/ect.
2. Try to play a song/video
3. Open a godot project
4. Run your game

or

1. Open a godot project
2. Open spotify/youtube/ect.
3. Try to play a song/video
4. Run your game

**Comment by akien-mga** [comment]
Could you test with the latest 3.1 beta build?

**Comment by marcelofg55** [comment]
@rcorre Are you sure you're actually using PulseAudio in your system? Sound to me like you're using ALSA in which audio devices can't be shared by the applications.
Can you run godot with the `--verbose` flag? That should show what audio driver is actually being used on the console.

**Comment by rcorre** [comment]
@marcelofg55 looks like you're correct!

```
[rcorre@midova ~]$ godot --verbose
Audio Driver ALSA average latency: 21ms (frame=940)
```

Turns the AUR has a separate [godot-pulse](https://aur.archlinux.org/packages/godot-pulse/) package, the plain `godot` package uses `pulseaudio=no`.

**Comment by rcorre** [comment]
Yup, that was it. Thanks!
