### ISSUE TITLE
Tons of errors when running Platformer 2D project

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#26413]
**Godot version:**
3.1 beta 8

**OS/device including version:**
Windows 7 x64

**Issue description:**
1. Download and install "Platfromer 2D" from Templates,
2. Run the game

**Result:**
Tons of error (like 10 error in a second):
```
E 0:00:01:0311   Index p_bounce=-1 out of size (colliders.size()=0)
  <C Source>     scene/2d/physics_body_2d.cpp:1411 @ _get_slide_collision()
  <Stack Trace>  Player.gd:104 @ _move()
                 Player.gd:71 @ _physics_process()
```
and it points to line:
`var get_col = get_slide_collision(get_slide_count()-1)`

I'm newbie, so I not sure if it expected and project is broken. I thought I should just report this.

![2019-02-28_210952](https://user-images.githubusercontent.com/1552169/53588100-37961e00-3b9d-11e9-98c7-8f45a04d7531.png)

**Comment by Sslaxx** [comment]
`get_slide_collision` returns a `KinematicCollision2D` object. If there's no object (or nothing to be collided with that can return that type), then `get_col` will be null. Hence the error messages.

**Comment by Tercus** [comment]
Might be because `get_slide_count()` returns `0` if there has been no collision, so it tries to access `get_slide_collision(-1)` which obviously doesn't work.

You can solve this by using:

	if get_slide_count() > 0:
		var get_get_col = get_slide_collision(get_slide_count()-1)

**Comment by KoBeWi** [comment]
This doesn't look like Godot bug, so closing.

Also the only Platformer 2D I see on Asset Lib is unofficial.
