### ISSUE TITLE
Disabling a gravity area while a body is inside leaves the body with modified total gravity

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#26410]
**Godot version:**
3.1.beta.calinou. 9ca6ffa

**OS/device including version:**
Linux 64 bits / Android

**Issue description:**
If the space override method of an area with a non-zeo gravity vector is switched from combined to disabled, any affected bodies will remain with their state.total_gravity value affected, even after exiting the area. Conversely, if the space override method is switched from disabled to combined, it'll fail to affect any bodies inside the area. 

**Steps to reproduce:**
- Open repro-project.zip and run the project
- Click and drag to move the ball in front of the fan
- The fan will stop after a few seconds and leave the ball with a modified total_gravity(displayed in the upper left), as if it were still on, even after the ball leaves the area
- If the ball reenters and leaves the area while it is in combine mode, total_gravity will be correct again.
Video: https://streamable.com/4n3sy

I'm not sure if this is a bug or just something that should be clarified in the docs. 

**Minimal reproduction project:**
[repro-project.zip](https://github.com/godotengine/godot/files/2916090/repro-project.zip)

**Comment by noidexe** [comment]
Browsing the engine code I noticed this line:
https://github.com/godotengine/godot/blob/9dfe3b6d9e94c74d70f8241763a9d010c4a6db1e/modules/bullet/rigid_body_bullet.cpp#L381
```
if (isScratchedSpaceOverrideModificator || 0 < countGravityPointSpaces) {
		isScratchedSpaceOverrideModificator = false;
		reload_space_override_modificator();
}
```
The conditions within the if are only modified when a rigidbody enters/exits an area, and if that area has space override != disabled. 
So if a rigid body leaves a an area with space override disabled reload_space_override_modificator(); will not be called. Also, if an area changes its space override mode bodies already inside it will not get notified of the change until they exit the area.

**Comment by akien-mga** [comment]
Can you still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

I tried the demo project in 3.2.2-rc2 but there doesn't seem to be any impact on `total_gravity` at all.

**Comment by noidexe** [comment]
I tried with 3.2.2-rc2 and it seems to be working fine now.

**Comment by akien-mga** [comment]
Nice, closing as fixed then.
