### ISSUE TITLE
Unable to run built-in commands using OS.execute

### ISSUE THREAD

**Issue by thebluefish** [godotengine/godot#26429]
[Sample Project](https://github.com/godotengine/godot/files/2918084/test_execute.zip)

**Godot version:**
3.0.6
8d117b214f2bcd14015532fdfbed9b3f059da0e6

**OS/device including version:**
Windows 10 x64

**Issue description:**

```
var output = []
OS.execute('echo', ['somethingyo'], true, output)
```

Produces the following:

```
'"echo"' is not recognized as an internal or external command,
operable program or batch file.
```

It appears that the `path` argument is being automatically surrounded in quotes, per [OS_Windows::execute](https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L2450).

As mentioned in [this issue](https://github.com/godotengine/godot/issues/10172), this can currently be circumvented by calling `CMD /K "<command>"` - however this is not an elegant solution as it requires launching a second process. I propose one of the following solutions which doesn't require this workaround.

Solution 1:
----------

Remove automatic quotes. This would have the downside of requiring the user to use quotes 
when necessary.

Solution 2:
----------

Enclose the path with quotes only when there is whitespace in the path.

Solution 3:
----------

Check if the command is a DOS command, and enclose the path in quotes if it is not.

**Comment by bruvzg** [comment]
> this is not an elegant solution as it requires launching a second process

AFAIK removing quotes won't help with internal commands. `cmd` is the only way to use them. Unlike Unix tools, Windows/DOS internal commands don't have separate executables and are all bundled into `cmd.exe` (or `command.com` in case of DOS) and should not spawn extra processes.

**Comment by thebluefish** [comment]
It works as long as we remove the quotes. Consider the following script: 
```swift
func _ready():
    var output = []
    var res = OS.execute('echo somethingyo', [], true, output)
    for o in output:
        print(o)
```

Currently we are using
```cpp
argss = "\"\"" + p_path + "\"";
```

which produces 
```
'"echo"' is not recognized as an internal or external command,
operable program or batch file.
```

However if I change it to 
```
argss = "\"" + p_path;
```

then we get 
![image](https://user-images.githubusercontent.com/4490910/53640304-beb8b580-3be0-11e9-9af7-e27ca13cfdac.png)

**Comment by bruvzg** [comment]
Hah, interesting, blocking/pipe version of `OS::execute` uses `_popen` call which seems to support external commands, but it have this note in the [documentation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen?view=vs-2017):

> If used in a Windows program, the `_popen` function returns an invalid file pointer that causes the program to stop responding indefinitely. `_popen` works properly in a console application.

I wonder if it is working at all in exported app or only in editor (which is console application)?

Non blocking version uses `CreateProcess` and should not work with internal commands (at least it was not in Windows 7 times).

**Comment by thebluefish** [comment]
Hm, it does concern me that it wouldn't work with non-blocking option. I suppose we can either:

- Leave the current behavior intact, and allow the user to launch `cmd /K` for builtins
 - I honestly cannot think of any scenarios where this isn't at least *acceptable*, though it's unfortunate we're basically dealing with two `cmd` processes doing so
- Figure out some sort of compatibility with CreateProcess (which I assume would involve us wrapping such commands in a `cmd /K`)
- Replace CreateProcess with `popen`
 - I'm honestly not sure why we use CreateProcess for non-blocking/no-pipe branch - from what I gather `_popen` is non-blocking and we'd be free to simply open it and move on, though I haven't yet tested this idea.
- Document somewhere that only blocking calls can directly call builtins
 - This just seems like a bad idea

**Comment by thebluefish** [comment]
I would assume it should work in an exported app, though I will test it tomorrow. If it doesn't, that's likely a larger concern since it would affect existing expected behavior.

**Comment by neikeq** [comment]
The quotes should only be added if they are needed. Would that solve the issue?

**Comment by bruvzg** [comment]
Some tests.

Non blocking `var pid = OS.execute('echo', ['somethingyo'], false)` fails with:

```
ERROR: execute: Condition ' ret == 0 ' is true. returned: ERR_CANT_FORK
At: platform/windows/os_windows.cpp:2494
```

Blocking version works in exported app, but it's opening new console window each time, even when it's starting GUI app.

Also `cmd /k` is not auto-closing console after command execution and will hang in case you are using editor executable to run project from existing command line session, it's better to use `cmd /c` instead.

**Comment by KoBeWi** [comment]
Tested in 3.2.4 beta3 and the provided code sample seems to do nothing, not even error appears.
