### ISSUE TITLE
Grid Map Editor menu contains unimplemented options

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [godotengine/godot#26426]
**Godot version:** v3.0.6

**OS/device including version:** Arch Linux

**Issue description:**

The Grid Map Editor menu (the drop-down menu that appears when you click on the text "Grid Map" in the pane that opens when a GridMap node is selected) contains several options that do not appear to be implemented.

The `_menu_option` method in "godot/modules/gridmap/grid_map_editor_plugin.cpp" does not appear to implement handlers for the following menu items:

* Create Area
* Create Exterior Connector
* Erase Area

Having menu options that don't do anything is confusing for users; it leads them into a goose chase for features that do not exist. I request that the menu options be removed, until the features they correspond to are implemented.

**Comment by KoBeWi** [comment]
Fixed in #25406
