### ISSUE TITLE
Visual Issues when Adding a CSGBox

### ISSUE THREAD

**Issue by turtletooth** [godotengine/godot#26422]
Godot 3.1 Beta 9

Windows 10

3D Scene
Add a Spatial
Add a CSG Box
The grid disappears.

**Comment by turtletooth** [comment]
The scale also doesn't update in the Inspector when the red dots are changed.

**Comment by bojidar-bg** [comment]
Cannot reproduce on master/beta 10. Looks like this on my end:
![image](https://user-images.githubusercontent.com/5276727/53755153-7ccc8f80-3ebe-11e9-91b7-708d3bc2b017.png)

Perhaps you zoomed in just the right amount as to see only the box, and it looked like the grid disappearing?

**Comment by turtletooth** [comment]
just tested on beta 10.  Same results.

![godot](https://user-images.githubusercontent.com/4576381/53760838-402e7300-3e81-11e9-822d-d10377b6b6cf.PNG)

**Comment by Calinou** [comment]
What graphics card (and driver version) are you using?

**Comment by turtletooth** [comment]
Surface Pro 2018 i7 16gb ram, Intel Iris Plus 640

**Comment by turtletooth** [comment]
Strangely, adding a light fixes this.

**Comment by clayjohn** [comment]
Looks to be a driver specific issue that was never reproduced by others. Closing for now. 

If you are still encountering this problem in recent versions, I can re-open.
