### ISSUE TITLE
Control.get_parent_area_size() method bound to wrong function

### ISSUE THREAD

**Issue by PapaFl** [godotengine/godot#26439]
**Godot version:** latest master & v3.0.6.stable

**OS/device including version:** Windows 10

**Issue description:**

https://github.com/godotengine/godot/blob/e7dd05fed80d80b328977450bc3a48f500d5cd44/scene/gui/control.cpp#L2724
In this line, `Control.get_parent_area_size()` is bound to `Control::get_size()` instead of the correct function. This causes wrong behavior when calling `get_parent_area_size()` from GDScript.

**Steps to reproduce:**
1. Create a parent Control and a child Control
2. Make sure the parent and child have a different `rect_size` to make the issue obvious
3. Add a script to the child control with the following expression in its `_ready()` function:
`print(get_parent_area_size())`
4. Run the Project.

Expected behavior: The parents `rect_size` will be printed.
Observed behavior: the childs `rect_size` is printed.

#
**Minimal reproduction project:**

[getParentAreaSize.zip](https://github.com/godotengine/godot/files/2919406/getParentAreaSize.zip)

**Comment by akien-mga** [comment]
That's a bug indeed. Do you want to provide a PR to fix it?
