### ISSUE TITLE
godot 3.1 beta 9 does not save last opening scence and last opening script

### ISSUE THREAD

**Issue by TyTYct** [godotengine/godot#26434]
**Godot version:**

v3.1 beta 9

**OS/device including version:**

windows 10 Pro, GTX 1060 6GB

**Issue description:**

Godot 3.1 beta 9 does not save last opening scence and last opening script. This issue makes me quite alot time to come back last place to working.
I try at v3.1 beta 8, is is still ok.

**Steps to reproduce:**
1. open some scene and some script.
2. restart godot.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Indeed, that's #26359 which has been fixed since then. I'll add it to the beta 9 blog post.
