### ISSUE TITLE
FileSystem Texture thumbnails resolution is too low

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#26448]
**Godot version:** Godot 3.1beta9official

**OS/device including version:** Linux x64 Solus Gnome

**Issue description:**

FileSystem Texture thumbnails have their resolution scaled down by a lot to an indistinguishable  image.

**Comment by akien-mga** [comment]
Can you be more explicit? It's indeed scaled down, but to the expected size of a thumbnail.
![screenshot_20190301_182014](https://user-images.githubusercontent.com/4701338/53654724-b72ff580-3c4e-11e9-9a7b-0267ab4b735b.png)
It can't be scaled less, unless all icons are made bigger.

**Comment by henriiquecampos** [comment]
![image](https://user-images.githubusercontent.com/10171059/53657118-fe5cbd00-3c33-11e9-9c1b-1303a586e330.png)

**Comment by groud** [comment]
I think this was already fixed. You probably have to delete the Godot thumbnail cache and see if it fixes the problem.

**Comment by henriiquecampos** [comment]
This happens with all textures tho. Also, by `cache` you mean the stuff in `.import/`?

In this image I reimported everything (deleted .import/ and let Godot auto import them)

![image](https://user-images.githubusercontent.com/10171059/53660948-e25e1900-3c3d-11e9-9e1d-e77f5be2f458.png)

**Comment by akien-mga** [comment]
He meant remove the files (or the whole folder) in `~/.cache/godot` to force regenerating the cache.

**Comment by henriiquecampos** [comment]
Ohh, yeah now they are good, thx! Closing the issue
