### ISSUE TITLE
Latest dev snapshot not keeping session state

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#26447]
**Godot version:** Godot 3.1beta9official

**OS/device including version:** Linux x64 Solus Gnome

**Issue description:**

When closing the editor and opening again it doesnt keep the layout and previously opened scripts.

**Comment by KoBeWi** [comment]
This is already fixed on master branch. The fix just didn't make it into this beta.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/26359.

**Comment by henriiquecampos** [comment]
My bad, sorry
