### ISSUE TITLE
Improve screen copying in GLES2 renderer

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#26440]
A Nice optimization in GLES2 renderer can be to use the "system" framebuffer when the viewport is attached to the screen directly (via VisualServer.viewport_attach_to_screen(), NOT via ViewportContainer). 

In that case, instead of rendering to it's own viewport framebuffer and then copying it to the screen, it could use glScissor and glViewport to render to the little screen chunk directly, no copying involved.

The goal of this is to improve performance in older phones and desktops. 

The only downside is that, if this technique is in use, using SCREEN_TEXTURE or DEPTH_TEXTURE is impossible, as there is no screen to copy from (main framebuffer can't be referenced as a texture). To avoid this this should be predetected somehow before the screen is cleared, and then a fallback via traditional way should be used. This way, the optimization can be entirely automatic.

**Comment by faculezcano** [comment]
![2019-03-02_00-57](https://user-images.githubusercontent.com/5156989/53676846-c2067c80-3c86-11e9-8f6e-69975106d012.png)
That's why this is happening to me when i use DEPTH_TEXTURE?

**Comment by clayjohn** [comment]
Closed by #28796
