### ISSUE TITLE
Add get_noise_1d() to OpenSimplexNoise

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#26457]
Godot version:  3.1 beta 8
Windows 7 home 64 bit

Please add `get_noise_1d()` to OpenSimplexNoise.
Also please give us the equivalent all the noise get functions that return 0-1 range instead of -1-1.

**Comment by psuhas77** [comment]
Hey, I want to try working on this. The simplest solution would be to create [code]get_noise_1d(float x)[/code] which simply returns [code]get_noise_2d(float x,float fixedValue)[/code]. Is there some reason why this would be problematic?

**Comment by akien-mga** [comment]
CC @JFonS

**Comment by psuhas77** [comment]
So, [this](https://media.giphy.com/media/4blY7DYbIQYXa7wosd/source.gif) is what I got after using `get_noise_2d(float x,float(1))` with default octaves,lacunarity,persistence and period. Each frame represents a different seed. It seems to behave like 1D Simplex noise should.

**Comment by Chaosus** [comment]
Yeah, its simply noise2D(x, 1.0), and its not very useful for SimplexNoises as described in https://github.com/jwagner/simplex-noise.js/issues/16 
But its a good PR training for @psuhas77 - you could easily implement this if you want :)
