### ISSUE TITLE
Array.count(var what) returns incorrect value

### ISSUE THREAD

**Issue by ellis-matthew4** [godotengine/godot#26465]
**Godot version: 3.0**

**OS/device including version: Windows 10 v10.0.17763**

**Issue description:**

I tried to create an inventory system using arrays. In my shop, it uses Array.count(var what) to determine how many of an item the player already has. It works as intended at first, but after saving and reloading it returns 0.

**Steps to reproduce:**
Have an array, save the array to JSON, then reload it, then call Array.count(var what).

**Minimal reproduction project:**

Was unable to replicate in a clean project. However, writing my own count function allowed my project to work.

**Comment by ellis-matthew4** [comment]
I think I found the issue!
The Array was originally an array of dictionaries containing metadata, so when I compared it to the static dictionary, it was most likely returning false due to the static dictionary having a different memory address after reloading. After changing to use integers, everything works.

**Comment by akien-mga** [comment]
Indeed, that's normal behaviour.
