### ISSUE TITLE
Tween should have documentation about property:component syntax

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#26466]
**Godot version:**
3.1

**Issue description:**
Its a documentation problem - I discovered that its possible to access property component eg "rotation:x" for interpolate_property function (introduced in #12284) for Tween but its not mentioned in the docs, and user may try to use unwanted complex solutions to access this.

Solution: modify https://github.com/godotengine/godot/blob/master/doc/classes/Tween.xml

**Comment by psuhas77** [comment]
Won't this be true for all the other Tween functions that operate based on some property like follow_property, targeting_property, etc.. ?

**Comment by Chaosus** [comment]
Yeah, seems like this supported in all of them : https://github.com/godotengine/godot/pull/12284/files#diff-0140f1103a5ef09309f606284dc3f3c8

**Comment by psuhas77** [comment]
I want to take this up, would it be better to just mention it once at the top of the documentation or should it be present in each of the functions which uses some property?

**Comment by Chaosus** [comment]
I think its better to be in the brief description - just mention that syntax will be supported by all of these functions

**Comment by Chaosus** [comment]
Err Did I said brief description ? - forget it - Class Description of course !

**Comment by psuhas77** [comment]
Yeah, I figured.

**Comment by psuhas77** [comment]
Is this acceptable or am I missing something?

**Comment by Chaosus** [comment]
Rename "ex: " to "eg. ", otherwise look good

**Comment by psuhas77** [comment]
Really sorry about that, I'm new to this. Hopefully this one will do.

**Comment by Chaosus** [comment]
@psuhas77 No problem, continue to contribute more and you will definitly found the right way ! Closed as fixed.
