### ISSUE TITLE
Regression, GLES 2 doesn't show a Player character in TPS demo (or DAE models in other projects)

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#26468]
**Godot version:**
3.1 e930fb9

**OS/device including version:**
Linux Mint Mate 19 HD 3000

**Issue description:**
When I run TPS Demo, then I saw that Player character is missing and unstoppable error spam:

```
ERROR: create: Condition ' p_aabb.size.z > 1e15 || p_aabb.size.z < 0.0 ' is true. returned: 0
   At: ./core/math/octree.h:806.
ERROR: create: Condition ' p_aabb.position.y > 1e15 || p_aabb.position.y < -1e15 ' is true. returned: 0
   At: ./core/math/octree.h:802.
```

![zrzut ekranu z 2019-03-02 06-00-47](https://user-images.githubusercontent.com/41945903/53677478-a021ef80-3cb0-11e9-8903-956e194de28b.png)

This regression was introduced today or yesterday

**Steps to reproduce:**
Just run TPS Demo

**Comment by akien-mga** [comment]
Confirmed on Nvidia GTX 670MX on Linux.

**Comment by ProbDenis** [comment]
I got the exact same error for my own game. Some 3D models doesn't show and I get the same error output. (Manjaro Linux, Radeon RX 560)
