### ISSUE TITLE
Please add support export Godot Game to Android AAR file for AD SDK integrate.

### ISSUE THREAD

**Issue by lefay1982** [godotengine/godot#26469]
**Godot version:**
3.1

**OS/device including version:**
Android

**Issue description:**

Please add support export Godot Game to Android AAR file.
Some custom AD SDK must done by other sdk's department, and modify frequency.
if godot cannot export to aar file, The integrate AD SDK task must be done by Game Program Engineer.
It's waste time for Game Program Engineer.

**Comment by lefay1982** [comment]
When I  program with Libgdx.
I can proguard code and export core project to a jar, named game.jar .
this jar can send to a android engineer to integrate AD SDK and export to Android APK.
They can integrate many AD SDKs, and can export to many APKs with  different market version .

**Comment by akien-mga** [comment]
@m4gr3d Did #31919 solve this issue?

**Comment by m4gr3d** [comment]
@akien-mga yes it does.

Running the following command will generate an Godot `aar` archive file in the `platform/android/java/lib/build/outputs/aar` directory:
```
cd platform/android/java
./gradlew :lib:build
```
