### ISSUE TITLE
Why Scroll Control cannot expand or shrink by children item's size changed?

### ISSUE THREAD

**Issue by lefay1982** [godotengine/godot#26471]
**Godot version:**
3.1

**OS/device including version:**
ALL

**Issue description:**
See the demo snapshot below.
![image](https://user-images.githubusercontent.com/5716884/53679869-a3979400-3d0d-11e9-9179-e3e403e7f91f.png)
I want select the sword item, the item size y add 30px, and the other item under it must move down by 30px.
but see this snapshot, it's nothing happened.
How can I do this?

[ScrollDemo.zip](https://github.com/godotengine/godot/files/2921930/ScrollDemo.zip)

**Comment by Naryosha** [comment]
You did not initialize `rect_min_size` to the control size. It's still the default (0, 0).
These lines won't work as expected:

```
self.rect_min_size = Vector2(self.rect_min_size.x,self.rect_min_size.y+30)
self.rect_size = Vector2(self.rect_size.x,self.rect_size.y+30)
```

Min size y + 30 = 0 + 30 = 30 which is still smaller than the actual control size.

Simply add `rect_min_size = rect_size` to `_ready` and it should work.

**Comment by lefay1982** [comment]
OK, thanks, can work.
