### ISSUE TITLE
AnimatedTexture doesn´t play in editor until detects UI input

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#26478]
**Godot version:**

e930fb9a6e4277ad3c4dc60a775785b294840512
(build from today 02/03/2019)

**OS/device including version:**

Win 7 64 GeForce GTX 660

**Issue description:**

Canvas Editor doesn´t play animated texture until detect Input UI. If you select the scene that contains the animated texture to the "main" scene in project, animated texture process all time, until project is restarted, and "only-play-in-input" behaviour returns.

![animatedtexturebug](https://user-images.githubusercontent.com/11712737/53681282-86e86580-3ce7-11e9-838a-af2662068500.gif)

[Godot3_1_bug_Catch.zip](https://github.com/godotengine/godot/files/2922032/Godot3_1_bug_Catch.zip)

**Comment by reduz** [comment]
Closed by 34dd772
