### ISSUE TITLE
Dark area after direction shadow range

### ISSUE THREAD

**Issue by karolgotowala** [godotengine/godot#2647]
If directional shadows range is set smaller than camera view range there is full dark area behind shadows range don't know if this solves and can't try it but i believe setting ShadowBuffer texture edge to white should solve this.

glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
float color[] = { 1.0f, 1.0f, 1.0f, 1.0f };
glTexParameterfv(GL_TEXTURE_2D, GL_TEXTURE_BORDER_COLOR, color);

![shadow_bug](https://cloud.githubusercontent.com/assets/14169202/10698978/efa50c9a-79b3-11e5-9a1e-5df71d3ff558.png)

**Comment by vnen** [comment]
Not sure if this is a bug. I believe the shadow range should be the same as the camera view range, as stated in the [shadow mapping tutorial](http://www.godotengine.org/projects/godot-engine/wiki/Shadow_Mapping#Important).

**Comment by vnen** [comment]
It's the same issue as #559, so I'll archive this.
