### ISSUE TITLE
There is no application set to open the URL /Users/***/Library/Caches/Godot/tmp_export.html.

### ISSUE THREAD

**Issue by robgraeber** [godotengine/godot#26475]
**Godot version:** 3.1 beta 9

**OS/device including version:** OS X 10.14.2

**Issue description:** When trying to quick preview via html5 on Mac, it can't find a program to open the html file. I associated html files with a browser via finder but still no change. If I follow the prompt, then I can pick a browser if I select the "All Applications" option, but it doesn't persist the next time I preview.

**Steps to reproduce:** Quick preview any html5 compatible project on latest OS X.

<img width="601" alt="screen shot 2019-03-02 at 2 18 17 am" src="https://user-images.githubusercontent.com/2387719/53680586-a7d29b80-3c92-11e9-98dd-667bc001f911.png">

**Comment by akien-mga** [comment]
What happens when you double click an .html file in Finder?

**Comment by robgraeber** [comment]
@akien-mga it gets opened by safari

**Comment by bruvzg** [comment]
I can confirm this, `shell_open` should expects URL and should begin with `file://`.

All other calls `shell_open` with local stuff seems to have it, like: [editor/editor_node.cpp#L2201](https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L2201)
JS Preview doesn't: [platform/javascript/export/export.cpp#L363](https://github.com/godotengine/godot/blob/master/platform/javascript/export/export.cpp#L363)
