### ISSUE TITLE
Export templates wrongly reported as missing for HTML5 + GLES2 if ETC not imported

### ISSUE THREAD

**Issue by robgraeber** [godotengine/godot#26476]
**Godot version:** 3.1 beta 9

**OS/device including version:** OS X 10.14.2

**Issue description:** I downloaded the latest export template but can't export for html5 and GLES2. It is saying "Export templates for this platform are missing", but it works for every other platform including html5 and GLES3. Oddly I can export for html5 and GLES2 using the quick preview button for html5.

**Steps to reproduce:** Try to export any project with html5 and GLES2.

<img width="910" alt="screen shot 2019-03-02 at 2 35 16 am" src="https://user-images.githubusercontent.com/2387719/53680763-ba4dd480-3c94-11e9-8d75-e7b77f10375f.png">

**Comment by Calinou** [comment]
Maybe the second error message is being printed erroneously (due to the first one). GLES2 only supports ETC for texture compression (a.k.a. ETC1), which you should enable in the Project Settings (you can also uncheck ETC2 from the export preset).

**Comment by akien-mga** [comment]
It's likely due to what @Calinou mentioned indeed, can you confirm that enabling ETC support in the Project Settings "VRAM compression" section fixes it?

**Comment by robgraeber** [comment]
@akien-mga Yeah enabling ETC support in project settings fixed it. Thanks.
