### ISSUE TITLE
CPUParticles2D not working on AMAZON TATE Device

### ISSUE THREAD

**Issue by usbhell** [godotengine/godot#26472]
**Godot version:**
3.1 beta (all of them)

**OS/device including version:**
2012 Amazon Kindle Fire HD 7” (GOOGLE AMAZON TATE) running CyanogenMod version 11
PowerVR SGX 540
ANDROID 4.4.2

**Issue description:**

For some reason CPUParticles2D don’t seem to work at all, I havent seen this problem on any other device I've tried so far. I know its a bit old but it works nicely with 2.15

**Minimal reproduction project:**

[OpenGL-ES Info.txt](https://github.com/godotengine/godot/files/2921937/OpenGL-ES.Info.txt)
[logcat.txt](https://github.com/godotengine/godot/files/2921938/logcat.txt)
[ParticleTest.zip](https://github.com/godotengine/godot/files/2921939/ParticleTest.zip)

**Comment by clayjohn** [comment]
The hardware is just too low-end to support the features needed for CPUParticles2D. Your device only supports a maximum of 8 Vertex attributes. It is the same problem faced in https://github.com/godotengine/godot/issues/27407

There are no plans to create a renderer that supports such low-end devices. Sorry.
