### ISSUE TITLE
Build fails on Windows 10 with latest VS 2017: SCons 3.0.4 doesn't support SDK 10.0A

### ISSUE THREAD

**Issue by joealam** [godotengine/godot#26485]
**Godot version:** e47915f7cd9336a37d08891a046a4bd778572a73

**OS/device including version:** Windows 10

**Issue description:**
When trying to build with SCons, I get the following error:
```
scons: *** SDK version '10.0A' is not supported
File "./platform/windows\detect.py", line 146, in setup_msvc_auto
```

**Additional Info:**
`scons --version` output:
```
SCons by Steven Knight et al.:
        script: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-20 22:51:36, by bdeegan on kufra
        engine: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-20 22:51:36, by bdeegan on kufra
        engine path: ['c:\\program files (x86)\\python\\python37-32\\lib\\site-packages\\scons\\SCons']
```

**Comment by hpvb** [comment]
Are you using MSVC 2017?

**Comment by joealam** [comment]
Yeah, Visual Studio 2017.

**Comment by bdbaddog** [comment]
SCons explicitly lists suported versions of MSVC and SDK. 10.0A isn't in the list.
You can try this patch to see if that is sufficient.
in SCons/Tools/MSCommon/sdk.py
line 181 change 10.0 to 10.0A

Let me know if that works.
Did you separately install SDK or as part of your MSVC install?
Also run vswhere and paste the output here.

**Comment by mwichmann** [comment]
Hmmm, it seems to me scons is working okay with a 10.0A installed, maybe it's picking a different one instead.  I have a system which has these directories in `Program Files (x86)/Microsoft SDKs/Windows`: v10.0A, V7.0A, V8.0, V8.1, v8.1A.  Possible the scons section on SDKs needs a bit of rework as the only one in that list that appears in the scons "supported" list is 7.0A (there are no 8.x's at all).  If @bdbaddog agrees maybe this should move over to the scons issue tracker?

**Comment by joealam** [comment]
Changing that line in SCons/Tools/MSCommon/sdk.py does seem to solve the issue (although I can't say for 100% certain as I now have a different error, but I'm fairly sure it's unrelated).

I installed the SDK as part of the Visual Studio 2017 installer.
I did try manually installing Windows 10 SDK separately after getting this to see if it solved the error, but it seems to have made no difference.

In `Program Files (x86)/Microsoft SDKs/Windows` I have only `v10.0A` even though in the Visual Studio Installer it lists Windows 8.1 SDK as installed. Does the new installer put them somewhere else?

Output of `vswhere`:
```
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.17.1230.42073]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: d91334f6
installDate: 15/10/2018 15:12:43
installationName: VisualStudio/15.8.7+28010.2046
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
installationVersion: 15.8.28010.2046
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
isPrerelease: 0
displayName: Visual Studio Community 2017
description: Free, fully-featured IDE for students, open-source and individual developers
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.8.7
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2018-10-15T14:12:43.7052585Z
catalog_buildBranch: d15.8
catalog_buildVersion: 15.8.28010.2046
catalog_id: VisualStudio/15.8.7+28010.2046
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.8.7
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 7
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.8.7+28010.2046
catalog_requiredEngineVersion: 1.17.1230.42073
properties_campaignId: 
properties_channelManifestId: VisualStudio.15.Release/15.8.7+28010.2046
properties_nickname: 
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe
```

**Comment by bdbaddog** [comment]
O.k. I'm guessing V10.A is installed with a VS 2017 update. 
I'll see if I can repro and fix it in master.

**Comment by mwichmann** [comment]
Looks like a fair bit has changed in the registry and the values it's looking for don't match up well with setups that never had any older versions in place.

**Comment by mikeepiazza** [comment]
> in SCons/Tools/MSCommon/sdk.py
> line 181 change 10.0 to 10.0A

Did a fresh install today and was getting the 10.0A not supported error. The above method edits enabled compilation on my system.

**Comment by SpechtMagnus** [comment]
So when can we expect this 3.0.5 update of scons? This is a critical bug affecting every up to date windows machine and I won't build the buildsystem from source because of some bad design choices on their side.

**Comment by bdbaddog** [comment]
> So when can we expect this 3.0.5 update of scons? This is a critical bug affecting every up to date windows machine and I won't build the buildsystem from source because of some bad design choices on their side.

Hopefully later today. Note there is a test build available on testpypi
pip install --index-url https://test.pypi.org/simple/ scons==3.0.5a3

**Comment by SpechtMagnus** [comment]
I tried the test build and am still getting the same error message.

`scons --version
SCons by Steven Knight et al.:
        script: v3.0.5.alpha.yyyymmdd.387e1f36f19d7a1e5f06cad4d6e87d84893c3ac2, 2019-03-15 22:17:20, by bdbaddog on Williams-MacBook-Pro
        engine: v3.0.5.alpha.yyyymmdd.387e1f36f19d7a1e5f06cad4d6e87d84893c3ac2, 2019-03-15 22:17:20, by bdbaddog on Williams-MacBook-Pro
        engine path: ['...local\\programs\\python\\python37-32\\lib\\site-packages\\scons\\SCons']
Copyright (c) 2001 - 2019 The SCons Foundation
PS D:\Portable\Godotengine\godot> scons platform=windows
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default

scons: *** SDK version '10.0A' is not supported
File "./platform/windows\detect.py", line 146, in setup_msvc_auto`

**Comment by SpechtMagnus** [comment]
With the sdk.py fix mentioned above it works perfectly

**Comment by bdbaddog** [comment]
Try again with 3.0.5a4 I didn't realize the V10.0A didn't make it into the last test package.

**Comment by SpechtMagnus** [comment]
Seems to work :+1:

**Comment by dvorontsov** [comment]
I am experiencing the same issue as OP, except I am on Win7 64-bit.  Will try recommended solutions now.

**Comment by bdbaddog** [comment]
3.0.5 was recently release and should fix this issue

**Comment by Chaosus** [comment]
Indeed it is fixed !
