### ISSUE TITLE
Problem with grid in tileset 

### ISSUE THREAD

**Issue by rakun99** [godotengine/godot#26480]
This picked cell in grid doesn't disappear no matter what I do.
![godot 3 1 bug](https://user-images.githubusercontent.com/46073558/53681457-5f06fb00-3d03-11e9-96fc-0bf12e08d507.JPG)
![godot 3 1 bug 2](https://user-images.githubusercontent.com/46073558/53681530-93c78200-3d04-11e9-94a7-5c8428988886.JPG)

**Comment by cobreen** [comment]
I had the same problem. try to remove each part of tile separatly

**Comment by akien-mga** [comment]
What Godot version? Please don't ignore the issue template, it asks for details for a reason.

**Comment by rakun99** [comment]
> 
> 
> What Godot version? Please don't ignore the issue template, it asks for details for a reason.
Version was Beta 10

**Comment by MarianoGnu** [comment]
On the screenshots there's an snap to grid button that should enable/disable the grid visibility. Does it work for you?

![image](https://user-images.githubusercontent.com/1776044/53778295-fd00ee00-3eda-11e9-8ccf-fc8fe770ba16.png)

**Comment by rakun99** [comment]
> 
> 
> On the screenshots there's an snap to grid button that should enable/disable the grid visibility. Does it work for you?
> 
> ![image](https://user-images.githubusercontent.com/1776044/53778295-fd00ee00-3eda-11e9-8ccf-fc8fe770ba16.png)

Yes, its's working.

**Comment by akien-mga** [comment]
I tried the TileSet editor a bit in the current master branch, and while usability is still not the best, I don't really understand what problem is being described in this issue.
