### ISSUE TITLE
Convert color to alpha texture import option

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#26493]
**Godot version:**
3.2+

**Feature description:**
I have a bunch of image assets with black background color (no transparency), `replace_color` method could be used to replace any background color in an asset to transparent one. This could be set as an import option in `Process` section (among `Fix Alpha Border` and other stuff).

For instance, GIMP has such method: [Color to Alpha](https://docs.gimp.org/2.8/en/plug-in-colortoalpha.html).

This doesn't have to be too sophisticated, simple color replacement would be enough.

This is also a convenient feature in the case where one forgets to turn off the background layer used for making an asset on export. 

![replace_color](https://user-images.githubusercontent.com/17108460/53684132-2f132400-3d12-11e9-967b-253b419bab19.png)

Of course it's possible to make an automated batch script that converts color to alpha in GIMP, but making such script takes time and effort, and with  Godot's multi-select-reimport feature this becomes rather easy.

See #9623.

**Comment by Calinou** [comment]
> For instance, GIMP has such method: Color to Alpha.

GIMP's color to alpha implementation handles translucency, which a simple color replacement wouldn't.

**Comment by Xrayez** [comment]
Figured this should be possible to do with a custom `EditorImportPlugin`, something like:

```gdscript
func get_import_options(i):
    return [{"name": "color_to_alpha", "default_value": Color(0,0,0,0)}]
```

And of course by overriding all other virtual methods to make it actually work!
