### ISSUE TITLE
&lt; replaced by &gt; (and vice versa) when saving a scene in xml or xscn format

### ISSUE THREAD

**Issue by Tassim** [godotengine/godot#2649]
You can reproduce the bug by creating a new scene with only a label in it, and set the text to something containing '>' or '<'. Save it to xml or xscn and launch the scene.

Maybe something to do with https://github.com/okamstudio/godot/pull/2512

It's realy important to be able to save in these formats for versioning, so as a workaround you can set texts in scripts and save them as .gd resources (don't use builtin scripts)

**Comment by reduz** [comment]
this was actually a bug in the saver I think and was fixed, but existing
scenes may still see that behavior, or does it still happen to you?

**Comment by kubecz3k** [comment]
It turns out that ">" and "<" are flipped in my old scipt now, but after correcting it works good for me, so guess it's fixed :)

**Comment by vnen** [comment]
Closing, as this seems to be solved.

**Comment by vichug** [comment]
hey, can totally still repro, on a project that was created with godot pre 2 : if i open this project with godot 2 and more, every single > in built in scripts in xml scenes will be converted to <, and vice versa. This is a bit of a problem for me, as all my scripts are built in and all my scenes xml. Reopen maybe ?

**Comment by vnen** [comment]
@vichug as per @kubecz3k comment, if you open an old project with the new Godot version it gives this problem, but the issue doesn't happen anymore on the new version.

What happens is that the unescaping was also fixed, so now it reads as it should, which was flipped in the old versions. The only way to fix this is to detect old scene versions and flip every `<` and `>` so it works with the new Godot version (this actually might be desirable if seamless upgrade is on the wishlist).

**Comment by akien-mga** [comment]
So for 2.0 we need to either implement a way to convert the "broken" XML of 1.1, or at least mention the issue in the release notes or upgrade instructions for users of 1.1 who want to migrate to 2.0.

**Comment by reduz** [comment]
I'm not really sure what to do about this, but I guess a release note will do?

**Comment by akien-mga** [comment]
I think release notes will be fine yes.

**Comment by vichug** [comment]
for me, yes, by now i corrected the things manually, so a release note will do. But it should be a big red capital WARNING, especially for users who don't build from sources but only use the stable builds (i suppose there are more of them than one could be aware ?)

**Comment by reduz** [comment]
We had a draft release notes somewhere, I think we could add it there and close this?

**Comment by akien-mga** [comment]
> We had a draft release notes somewhere, I think we could add it there and close this?

Ping @Calinou

**Comment by akien-mga** [comment]
Added to the WIP changelog (see #3355).
