### ISSUE TITLE
Plane collisionshape not colliding with raycast

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#26503]
**Godot version:**

```
3.1.beta9.official
```

**OS/device including version:**

```
Linux 4.20.13-arch1-1-ARCH 
```

**Issue description:**

I'd like to send a raycast from the camera and detect where it hits on a plane.
I had this working in 3.0.6, but it broke in 3.1-beta9.

**Steps to reproduce:**

1. Create the following hierarchy:

- Spatial
    - MeshInstance (Plane)
        - Area
            - CollisionShape (Plane)
    - Camera

2. Point the camera at the plane
3. Add this script to the camera

```
extends Camera

var mouse_pos = Vector2()

func _input(event):
	if event is InputEventMouseMotion:
		mouse_pos = event.position

func _physics_process(delta):
	var from = project_ray_origin(mouse_pos)
	var to = from + project_ray_normal(mouse_pos) * 1000
	var space_state = get_world().direct_space_state
	var result = space_state.intersect_ray(from, to)
	print('raycasting: ', result)
```

4. Run, move the mouse around, check for raycasts

For 3.0.6, I'll see raycast results print. For 3.1, I get nothing.

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/2922474/example.zip)

**Comment by rcorre** [comment]
I get raycast hits if I replace the `Area` with a `StaticBody`. Did the behavior of `Area` change somehow in 3.1?

**Comment by rcorre** [comment]
I've tried toggling `input_ray_pickable` on the `Area` to no avail.
It also isn't clear what is true/false for `input_ray_pickable`. The comment says it defaults to `true`, yet the default state seems to be unchecked, which I would assume means `false`.

**Comment by akien-mga** [comment]
Confirmed on b8112074 with both Bullet and GodotPhysics engine.

**Comment by AndreaCatania** [comment]
I don't think that remove the shape will fix the problem, these shapes are really useful to create world margins and remove it is not a nice move (is like remove a feature that the engine already has).

This kind of shape as a specific use and a solution to this problem could be name this shape in a more specific way in order to self document it, something like: InfinitePlane, WorldMarginPlane can fix the problem.

**Comment by Kequc** [comment]
I'm trying to just a collision plane that I'm using to separate layers on my map. It would be used for raycast collision. What is a suitable alternative to using a plane?

I'll just use a convex shape and populate it like a square but it seems odd.
