### ISSUE TITLE
Using Navigation2D Node with a tilemap print "LINK" and "UNLINK"

### ISSUE THREAD

**Issue by TotCac** [godotengine/godot#2650]
It seems if you use a navigation2D with a tilemap as children, and this tilemap use tile with navigationmeshinstance in it, engine print "LINK" and "UNLINK" for each tile.

Error can't be reproduced with this example https://www.youtube.com/watch?v=S-zEA_Ce1mk

Checking in repository, i can't get why happening in 2D because in:
scene/2d/navigation2d.cpp (print_line have comments)
scene/3d/navigation.cpp (print_line haven't)

**Comment by CowThing** [comment]
Same problem here. It doesn't seem to actually affect anything, the navigation is still working fine, but the console is being spammed.

**Comment by akien-mga** [comment]
> Error can't be reproduced with this example https://www.youtube.com/watch?v=S-zEA_Ce1mk

Not sure whether you initially meant that it *can* or *can't* be reproduced with the pathfinding2d demo, but I tried it and indeed I *can't** reproduce the bug.

Could you provide a test project that reproduces the issue?

**Comment by CowThing** [comment]
I just tested again with a more recent build of the engine (from November 3rd), "LINK" and "UNLINK" aren't being spammed for me anymore, while on a previous version (from September 30th), the same project had the print spam.

**Comment by TotCac** [comment]
Problem is solved in the last available build on website.
