### ISSUE TITLE
Global audio jerks when pausing game.

### ISSUE THREAD

**Issue by robertarnborg** [godotengine/godot#26504]
**Godot version:**
Beta 9 3.1

**OS/device including version:**
Windows 10

**Issue description:**
Autoloaded ogg file global audio stream hickups when pausing game.

**Steps to reproduce:**
Autoload an ogg file, play it through scenes and pause game.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Can you attach an example project, please (or at least the OGG file used)?

**Comment by girng** [comment]
What do you mean by "jerk"? Static noise, or?

**Comment by robertarnborg** [comment]
Sorry for being the jerk here was a bit non sober when opening this issue.
I'll send a file soon, am In the middle of finishing a first complete game
with the engine so sorry for being a bit testy :)

**Comment by robertarnborg** [comment]
The sound kind of bobs out and in, a little twitch with a jerk.
Its a big project im working on here where this happens so maybe other
processing might be the culprit, I need to look into it further.

**Comment by girng** [comment]
It's np @robertarnborg :). Was just a bit curious

**Comment by robertarnborg** [comment]
Allright the issue happens if you dont set the autoloaded music player to
process in pause. My bad!

**Comment by KoBeWi** [comment]
Yeah, there was a bug that caused AudioStreamPlayer not stopping when paused. It actually stopped, but only for one frame and then continued. I guess that was the "jerk".

Anyways, since the bug is fixed, the issue can be closed.

**Comment by robertarnborg** [comment]
Great job guys! You are the best. Will better my issue word selection next
time 😋
