### ISSUE TITLE
Launch Options / Arguments not working properly in Steam

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#26501]
**Godot version:**
Godot 3.1 (Steam)

**OS/device including version:**
macOS Mojave 10.14.3

**Issue description:**
Adding the launch options '/path/to/project' launches in maximized window but loads the Project Manager instead of the project.

Godot is launched with `--path $HOME -p` via Steam, which prevent it from working

**Steps to reproduce:**
In Steam > Library, right click Godot and open Properties, in General > Set Launch Options add the arguments '/path/to/project' to launch directly into the project.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2922441/Test.zip)

**Comment by Calinou** [comment]
The option you should use is `--path <directory>`, not `--p` (which is invalid, and `-p` is used to open the project manager anyway):

```text
  --path <directory>               Path to a project (<directory> must contain a 'project.godot' file).
```

**Comment by lexum0** [comment]
In Steam it doesn't work with `--path` either, nor without the flag. Running from Terminal works with `--p`, not `--path`

**Comment by akien-mga** [comment]
> In Steam it doesn't work with --path either, nor without the flag. Running from Terminal works with --p, not --path

I don't know why that would happen, but `--p` *is not* a supported parameter. If it works, it likely means that your `project.godot` file is actually in the current working directory.

Check `--help` to know options.

**Comment by lexum0** [comment]
@akien-mga the project file is in a different directory. Checked `--help` and running with `--path` does nothing. Running from Terminal with the path and no options works, but running from Steam with the path only runs the Project Manager (projects list) in maximized window, which tells me it kind of worked or detected the project.

**Comment by lexum0** [comment]
Steam is launching Godot with the arguments `--path $HOME -p` so I think the problem is it's getting two different arguments on launch and that's why it opens maximized but will go to the Project Manager instead of the project, I updated the issue description.

**Comment by lexum0** [comment]
After further testing, it's the `-p` argument preventing the project from loading. I don't know why launching from Steam has it.

**Comment by akien-mga** [comment]
Yeah this is done precisely because people put project files in the $HOME by mistake, and then they're puzzled that it always opens a project instead of the project manager. So on Steam it uses `-p` to force loading the project manager.

I haven't tested, but you might be able to override it with `-e` to force opening the editor. Otherwise you'd have to hardcode the command instead of using the Steam `%command%`, and set your custom one without `--path $HOME -p`.

**Comment by lexum0** [comment]
`-e` doesn't force the editor, `-p` wins

**Comment by Calinou** [comment]
It's no longer possible to use both `-p` and `-e` to avoid confusion, closing.

```text
❯ bin/godot.linuxbsd.tools.64.llvm --project-manager --editor                  
Error: Command line arguments implied opening both editor and project manager, which is not possible. Aborting.

❯ bin/godot.linuxbsd.tools.64.llvm --editor --project-manager --editor
Error: Command line arguments implied opening both editor and project manager, which is not possible. Aborting.
```
