### ISSUE TITLE
[TRACKER] Implement editor warnings for features not in GLES2

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#26509]
While working on the GLES2/GLES3 differences documentation, I noticed that some features display a warning when they won't work in GLES such as Particles (which shows a small yellow triangle next to the node with a warning that it doesn't do anything in GLES2). While others, such as GIProbes don't. 

It would be nice to either hide or display a warning for any nodes/properties (Like the properties in SpatialMaterial) that are not available in GLES2. 

Properties that should be hidden in GLES2:

- [x]  HDR in viewports

- [x] Contact in Lights

Nodes that need a warning in GLES2:

- [x] GIProbes

**Comment by akien-mga** [comment]
Should we close as fixed, or do you want to add more things to this tracker which may need such fixes?

**Comment by clayjohn** [comment]
I'll just open another issue if I find more.
