### ISSUE TITLE
AudioStreamPlayer does not pause when tree is paused

### ISSUE THREAD

**Issue by sicienss** [godotengine/godot#26512]
**Godot version:**
3.1 beta 10 (that is, v3.1.beta.calinou.e930fb9)

**OS/device including version:**
Windows 8.1, Toshiba Satellite

**Issue description:**
`AudioStreamPlayer` does not pause when the tree is paused. `AudioStreamPlayer2D`, however, does pause.

The intended behavior is that all audio steam players respect pause. See #14009 and #19205. Toggling `stream_paused` does not seem to affect anything.

**Steps to reproduce:**
1. Create a scene with an `AudioStreamPlayer` child, with `pause_mode = "stop"`.
2. Play the `AudioStreamPlayer` on `_ready()`.
3. Pause the tree by setting `get_tree().paused = true`.
4. Observe that the sound does not stop.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2922567/TestProject.zip)

**Comment by robertarnborg** [comment]
Yes, that is what I am experiencing too. Plus some buggy stuff going on with the animation player regarding audio clip playback. Sometime audio player stops abruptly = playing = false... sigh.

**Comment by akien-mga** [comment]
Confirmed in 4da21d1c.

In 3.0.6, both AudioStreamPlayer and AudioStreamPlayer2D don't stop, so there was a bugfix for AudioStreamPlayer2D at least.

**Comment by robertarnborg** [comment]
This occurs in animationplayer audio playback track as well. Crucial for a
Mario style moving level setpiece synced to the music, if you pause the
game and music continues but level stops kinda kills the effect. :P

**Comment by robertarnborg** [comment]
But. This pause thing can all be fixed in script, but, an easy convenience functionality regardless.
