### ISSUE TITLE
NoiseTexture "As normalmap" returns a flat normalmap

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#26516]
**Godot version:**
Godot beta 10

**Issue description:**
When setting "as normalmap" the resulting normalmap does not represent a bumpmap of the NoiseTexture. It returns a flat bumpmap. 

**Steps to reproduce:**
Create a NoiseTexture with OpenSimplexNoise. Then select "as normalmap".

**Comment by Xrayez** [comment]
Seems like the bump scale needs to be set higher to make it not so flat.
```cpp
void bumpmap_to_normalmap( float bump_scale=1.0 )

**Comment by Xrayez** [comment]
Set `bump_scale` to 10.0, looks like this now:
![noise_normalmap_scale_10](https://user-images.githubusercontent.com/17108460/53693756-5f5bd080-3dad-11e9-859e-69d33dc9ae1d.png)

@JFonS do you think this parameter needs to be exposed as noise texture property?

**Comment by JFonS** [comment]
The normalmap strength can already be modified in the SpatialMaterial properties, so I would change the `bumpmap_to_normalmap()` strength to a fixed value like `8.0` and let the users adjust it on the material. I don't want to clutter the `NoiseTexture` properties. 

On the other hand, changing this value will break existing 3.1 projects that use normalmaps from noise textures, so exposing the strength property in the noise texture might also be a good option.

**Comment by clayjohn** [comment]
We could expose the strength property, but only when "as normalmap" is selected, that way we are only cluttering up NoiseTexture when we have to.

**Comment by JFonS** [comment]
@clayjohn That would be good. 

If anyone feels like implementing this small change feel free to  open a PR, otherwise I will do it later this week.
