### ISSUE TITLE
Debug console crash when getting autoloaded node at the top of the file

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#2651]
In my project that was made in 1.1 I was sometimes fetching autoloads to the member  reference variable at the declaration line (basically almost at the top of the file, not in any function). This in Godot 2.0 Alpha (b59c86f6f953ce6957bccbcc1ec6f3ce4c55572d) is causing crash of debug console, so in the end when game crashes there is no indicator why. 
I'm unable to reproduce this in every project (on simple ones it works fine for me), but I modified platformer 3d demo in the way it's behaving like this. (In the demo there is an Autoload that causes crash because of calling funcion on null, after couple seconds from running it).

Steps:
1. Download sample project
2. Load editor with the project
3. Run it instantly.
4. Project will crash in a couple seconds and there will be no indication on why (hopefully)

Anyway here is sample project:
https://dl.dropboxusercontent.com/u/168251/godot/some/issues/platformerDebugConsoleCrash.7z

Here is one minute video from my experimentation, first part with debug console crash, second part with fix: https://youtu.be/F4t756bWS9I

Further observations:
In other project, when I was trying to pause game with breakpoint and debug (which is possible for some time before console crash) I was able to see an error that there is no such node like "/root/global" (at the time when given node should be fetchable)
Also it seems that this bug is **not easy to reproduce** and might be related to performance somehow. It's harder for me to reproduce with release_debug compilation flags... (but still possible). 
Because of that I think this bug should not be labeled as 2.0 milestone, until more people will have it.

**Comment by reduz** [comment]
I'm not sure if this is a bug, this will not work because node is not on the scene yet

var autoloaded = get_node("/root/Autoloaded")

**Comment by kubecz3k** [comment]
Closing since @reduz is right. Remember that I was using this kind of code in 1.1 but this feature is not documented and by the logic should not work just like reduz said.

**Comment by kubecz3k** [comment]
@reduz  From the other side the issue was about debug console not the game crash itself. But since the bug is really hard to reproduce I will leave it closed until I will find better way to reproduce it.
