### ISSUE TITLE
macOS dark mode on title bar

### ISSUE THREAD

**Issue by jonathanhirz** [godotengine/godot#26515]
**Godot version:**
3.0.6 and 3.1 betas

This isn't a major bug, but for those of us on macOS using the system's dark theme, it's nice to have the title bar be dark too. On this post about Aseprite (https://community.aseprite.org/t/mac-aseprite-1-2-9-theme-window-color/2027/5), the dev shows how one key (`NSRequiresAquaSystemAppearance`) added to the app's info.plist can enable this behavior. I changed it on my machine and it works just fine, but it would be awesome if it could be added to the builds.

Here's the text of the post incase it disappears. Thank you!

```
Actually it’s not related to the Aseprite theme. Is something about the Aseprite.app bundle configuration. I’ve found a “quick” fix (that we’ll release in v1.2.10), if you want to give a try, you can check with the following steps:

Open Spotlight Search (press ⌘Space) and paste /Applications/Aseprite.app/Contents and press Enter
You can open the Info.plist file with a text editor and you’ll find the following lines:
<key>NSHighResolutionCapable</key>
<true/>
Add two extra lines as in the following text and save the Info.plist file:
<key>NSHighResolutionCapable</key>
<true/>
<key>NSRequiresAquaSystemAppearance</key>
<false/>
```

**Comment by girng** [comment]
Could this be done with editing a theme, or needs added functionality?

**Comment by jonathanhirz** [comment]
Ha no worries. It's a small thing, but it'll help me from adding it myself on each release.

**Comment by bruvzg** [comment]
Proper way to fix it, is to build Godot using Xcode 10 / macOS 10.14 SDK. You do not need any extra keys in `info.plist`.

**Comment by Calinou** [comment]
@bruvzg Is that possible with OSXCross though? To my knowledge, official builds are made using OSXCross, which [cannot use SDK versions above 10.11 easily](https://github.com/tpoechtrager/osxcross/issues/103).

**Comment by bruvzg** [comment]
> Is that possible with OSXCross though? To my knowledge, official builds are compiled using OSXCross

No idea. But if it's true that's bad.

It should be possible to build it with any of 10.9+ SDKs, but Godot have some features that requires at least 10.12 SDK to works (nothing essential).

It's gonna run on macOS 10.9+ regardless of SDK used.

**Comment by bruvzg** [comment]
https://github.com/godotengine/build-containers/blob/master/Dockerfile.osx seems like Godot docker container uses 10.13 SDK

**Comment by bruvzg** [comment]
OSXCross do require some patches to work with 10.14.

I have tested toolchain (docker container) produced from SDK 10.14 (Xcode 10.1) using script from here: https://github.com/liushuyu/osxcross-extras/tree/master/osxcross-builder.

It's building Godot just fine, resulting executable have correct dark mode title bar.

**Comment by jonathanhirz** [comment]
Sorry to bump this. Everything in this fix is working great for me, I have dark title bar on the editor and when running the game through the editor. But I noticed that on export, the built game still has a light title bar when in dark mode. Also (not sure if this is the right place), the icons that are generated looks like a few get corrupted when they're shrunk down, numbers 8 and 10.
![Screen Shot 2019-05-18 at 10 42 40 PM](https://user-images.githubusercontent.com/1631578/57978258-65ca1380-79be-11e9-9fe6-5aaf4f098ebe.png)
