### ISSUE TITLE
NoiseTexture get_data() returns null

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#26520]
**Godot version:**
3.1 master 56520d7

**Issue description:**
Tried to save noise normalmap in #26516 externally:

```gdscript
var tex = preload("res://noise_texture.tres")
var image = tex.get_data()
image.save_png("noise.png")
```
The image is null here, but expected to be present:
https://github.com/godotengine/godot/blob/c0e1c66e3def1383fb373454fe98de228b153159/modules/opensimplex/noise_texture.cpp#L82-L89

**Comment by JFonS** [comment]
Noise texture are computed in a separate thread, so in this case you are trying to access the data before it has finished generating the actual texture. 

I did a quick test and this snippet works fine.

```gdscript
var tex = preload("res://noise.tres")
yield(get_tree(), "idle_frame")
var image = tex.get_data()
image.save_png("noise.png")
```

We should properly document that, I guess.

**Comment by Xrayez** [comment]
Ah yes, forgot it actually generates it in a thread. So the behavior is going to be different though for platforms and/or configuration where threads aren't used.

**Comment by Xrayez** [comment]
Perhaps a signal could be added to whenever a noise texture is populated, so that we don't have to yield to full blown `idle_frame`?

**Comment by JFonS** [comment]
@Xrayez Seems like it's already there :)

```gdscript
func _ready():
	var tex = preload("res://noise.tres")
	tex.connect("changed", self, "read_tex", [tex]);
	
func read_tex(tex):
	var image = tex.get_data()
	image.save_png("noise.png")

```

**Comment by Xrayez** [comment]
Yeah this is more clean that way. Still maybe a custom signal can be added to return the actual image generated there, so it would boil down to:
```gdscript
var tex = preload("res://noise.tres")
var image = yield(tex, "generated")
image.save_png("noise.png")
```
as the yield supports to return bound signal argument.

**Comment by Zylann** [comment]
Wait, so if a scene loads and contains dozens of NoiseTextures, we spawn dozens of threads? I'll keep that in mind but I thought they were generating on the main thread like other resources. That's redundant with interactive resource loading.
