### ISSUE TITLE
Tileset preview is stretched

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#26526]
**Godot version:**
3.1 beta 10

**OS/device including version:**
Windows 7 x64

**Issue description:**
Wierd stretched preview in Tileset editor
![2019-03-03_150739](https://user-images.githubusercontent.com/1552169/53694926-2419cb80-3dc6-11e9-99f0-5b6f47d4f65a.png)

**Steps to reproduce:**
1. Add TileMap node, 
2. New TileSet,
3. Open editor, add picture (mine is 16 x 16)

**Minimal reproduction project:**
Tilemap -> Open editor
[tilemapbug.zip](https://github.com/godotengine/godot/files/2923074/tilemapbug.zip)

**Comment by akien-mga** [comment]
Fixed by #26622.
