### ISSUE TITLE
Mouse button down event not emitted when one button is already pressed

### ISSUE THREAD

**Issue by UltyX** [godotengine/godot#26524]
**Godot version:** 3.1 beta 8 & 10 Tested 

**OS/device including version:** Linux Kubuntu 18.10

**Issue description:**
When a mouse button is pressed and held, and a second mouse button gets pressed, the button down event will not be emitted for the second event.

**Steps to reproduce:**

Press MB1 and hold it, press MB2 and notice that the event for the 2. event.is_pressed() is not called. 
Releasing MB1 and MB2 does each create the button up event as expected.
Use case: MB1 pressed triggers aim, MB2 pressed triggers fire.
 
**Minimal reproduction project:**

```
func _unhandled_input(event):	
	if( event is InputEventMouseButton ):
		print("MB: ", event.button_index, event.is_pressed() )
```

Output is: 
MB: 1True
MB: 2False
MB: 1False

Output desired: 
MB: 1True
MB: 2True
MB: 2False
MB: 1False

**Comment by akien-mga** [comment]
Confirmed in 4da21d1c. It works fine in 3.0.6.
