### ISSUE TITLE
Spinner constantly redraws when a child of Container is selected

### ISSUE THREAD

**Issue by Kromonaut** [godotengine/godot#26522]
**Godot version:** v3.1.beta10.official

**OS/device including version:** macOS Mojave Version 10.14.3
**GPU model:** Radeon Pro 460 4096 MB

**Issue description:** When I have a VBoxContainer selected in the node list the spinner is constantly redrawing making my computer super laggy.

**Steps to reproduce:** Create a Node2D, then create a child MarginContainer, then create a child VBoxContainer and have the VBoxContainer selected.

**Minimal reproduction project:** [VBoxTest.zip](https://github.com/godotengine/godot/files/2923015/VBoxTest.zip)

**Comment by groud** [comment]
The problem comes from any child of a margin container, not only VBoxContainers.

**Comment by KoBeWi** [comment]
Fixed by #29318
