### ISSUE TITLE
Allow setters/getters have default arguments

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26530]
**Godot version:**
3.1 beta10

**Issue description:**
What title says. Getters/setters are methods, and while they shouldn't be called directly, it's possible and sometimes useful. And since they usually do more than just set a property, sometimes it's useful to call them with more arguments. But it's impossible, because setter expects only one argument and getter none. So I'm proposing that they should support more arguments, but ONLY if the extraneous arguments have default values. Then getters/setters can be called normally and you can call them directly if you want to make use of the extra arguments.

**Comment by Valeryn4** [comment]
This should have been fixed long ago. 
https://github.com/godotengine/godot/issues/24895

example:
```
### set test to 10 in editor
export(int) var test = 0 setget test_set
func test_set(val, val2 = 10):
	test = val * val2
	print("test: ", test)

func _ready():
	print("post test setter = ", test)
```
ouput:
```
test: 100
post test setter = 100
```

**Comment by akien-mga** [comment]
That works fine indeed in 4da21d1:
```gdscript
extends Node

var test = 10 setget set_test,get_test

func set_test(new_test, opt_arg=1):
	print("test before setter: " + str(test))
	test = new_test * opt_arg
	print("test after setter: " + str(test))

func get_test(message=""):
	if (message != ""):
		print(message)
	return test

func _ready():
	self.test = 5
	set_test(5, 8)
	print(self.test)
	print(get_test())
	print(get_test("Hello world!"))
```
prints:
```
test before setter: 10
test after setter: 5
test before setter: 5
test after setter: 40
40
40
Hello world!
40
```
