### ISSUE TITLE
Misleading error message when trying to Export all to non-existent directory

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26539]
**Godot version:**
3.1 beta10

**Issue description:**
Since few versions, there's this "Export All" button that exports everything with a single press of a button. It uses the directory path you provide in export window. The problem is, if the path points to non-existent directory, instead of telling this Godot says that "Export templates for this platform are missing/corrupted".

**Steps to reproduce:**
1. Create a project
2. Export it into some directory
3. Delete that directory
4. Try to export again with "Export All" button
5. ~~Forget that you are reproducing issue and try to figure out what you did wrong~~

**Comment by rluders** [comment]
Just to complement the information. Before display the message " Export templates for this platform are missing/corrupted" it says "Could not write file: ...."

What should be the expected behavior? It should create the path if it doesn't exist?

**Comment by akien-mga** [comment]
>  Or just give better feedback to the user saying: "The given export path doesn't exist."

This. And it should not warn about "Export templates for this platform are missing/corrupted", which is wrong. There's a need for overall better error reporting for the export workflow, as I mentioned in #26150, but that's likely not trivial to do. For now it should be enough to just make sure it doesn't report something wrong.

**Comment by rluders** [comment]
Well... It's fixed already. I'll PR it later for review. It's being a while since I wrote a single line of code in C++.
