### ISSUE TITLE
Allow the Camera of the Spatial Editor Viewport to be Manipulated by Scripts

### ISSUE THREAD

**Issue by shartte** [godotengine/godot#26534]
Note: this applies to Mono, but exposing it to Mono via ClassDB would expose it to GDScript as well.

**Issue description:**
I want to create an EditorPlugin that allows me to set & lock the camera rotation of the spatial editor viewport, but while the Camera can be accessed in the ForwardSpatialGuiInput method, changing it's transform will break view panning, and also does not allow changing the rotation lock.

Looking at the internal implementation of the SpatialEditorPlugin, the properties I'd actually like to change are:

- `use_environment`
- `lock_rotation`
- `use_orthogonal`
- `x_rotation`
- `y_rotation`

If possible, I might also want to access `distance`.

**Use case:**
I'd like to use the Godot editor for editing an isometric game world that is using a pre-rendered 3D background in a canvas layer. This makes it mandatory to use the exact same camera transform as was used to render that background, otherwise objects placed in the editor will not align with the camera in-game.
If I was able to set the x_rotation&y_rotation in the editor, I think I'd be able to make due. But currently those values are inaccessible.

**Comment by shartte** [comment]
**Possible implementation:**

Exposing the `set_state`&`get_state` methods of `EditorPlugin` to other editor plugins might actually solve this issue and give more flexibility to interact between different plugins without adding hard code dependencies.
It's true that this essentially exposes the state-saving internals of the SpatialEditorPlugin, but it's either that or exposing the Plugin as an API, which I'd consider an even harder dependency.

**Comment by shartte** [comment]
I've opened a draft PR that adds the ability to interact with the SpatialEditorPlugin via it's get_state/set_state functions.

Using that PR I can do the following in an EditorPlugin of my own (Mono):

```
        var editorInterface = GetEditorInterface();
        var editorState = editorInterface.GetPluginState("3D"); // 3D is the name of the spatial editor plugin

        dynamic viewports = editorState["viewports"];
        dynamic viewport1 = viewports[0];
        viewport1["x_rotation"] = 0.77539754f;
        viewport1["y_rotation"] = Mathf.Deg2Rad(45);
        viewport1["use_environment"] = true;
        viewport1["lock_rotation"] = true;
        viewport1["use_orthogonal"] = true;
        editorInterface.SetPluginState("3D", editorState);
```

**Comment by FrederickDesimpel** [comment]
It could be interesting if you can get the camera to set cull mask layers too.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1302, as feature proposals are now tracked on the Godot proposals repository.
