### ISSUE TITLE
When saving a resource to a file inside a Node that was inherited from a base scene, the change to the resource_path is not saved to the scene file

### ISSUE THREAD

**Issue by atomius0** [godotengine/godot#26531]
**Godot version:**

Godot Engine v3.1.beta10.official

**OS/device including version:**

Windows 7 SP1 64 bit

**Issue description:**

I have a scene (SpriteChild.tscn in the example) that inherits from another scene (SpriteBase.tscn). When saving a resource attached to a node that was inherited from the base scene to a file, the resulting change to the resource_path does not get updated when saving the scene.
I would expect it to save this change to SpriteChild.tscn, so that the resource now gets loaded from a .tres file instead of the base scene.

**Steps to reproduce:**
0. Open the example project.

1. In SpriteChild.tscn: Select node "SpriteChild"

2. In the Inspector, open the Resource of the Material under CanvasItem, note that the resource_path points to a resource inside the base scene. ("res://scenes/SpriteBase.tscn::1")
![01_material_resource_path](https://user-images.githubusercontent.com/20699861/53697221-862afe80-3dcf-11e9-9e62-dff21152d0e6.png)

3. In the Inspector, open the Material dropdown under CanvasItem and click on Save. Save as "SpriteChildMaterial.tres". (the name doesn't matter)
![02_save_material](https://user-images.githubusercontent.com/20699861/53697224-90e59380-3dcf-11e9-96f2-99e6414fa15e.png)

4. Note that the resource_path now points to "res://scenes/SpriteChildMaterial.tres", just how it should be. But the scene is not marked as changed(!)

5. (Optional) Change the Material's Blend Mode to "Mul", just so we can immediately see a difference between the new resource and the one from the parent scene. Now the scene will be marked as changed. 
![03a_change_material](https://user-images.githubusercontent.com/20699861/53697226-98a53800-3dcf-11e9-8367-81e8498eac71.png)
![03b_scene_changed](https://user-images.githubusercontent.com/20699861/53697228-9ba02880-3dcf-11e9-9975-9821bb9adc8c.png)

6. Save by pressing Ctrl+S

7. Close and reopen Godot. (if you just reopen the scene instead, everything will still look okay.)

8. Now the material will be back to how it was in the beginning, the resource_path will point to "res://scenes/SpriteBase.tscn::1" again instead of the .tres file we saved in step 3.

Workaround: I found that when I make the material unique before doing step 3, the bug does not occur and the change to the resource_path is saved to the scene properly.
![04_workaround_make_unique](https://user-images.githubusercontent.com/20699861/53697232-aa86db00-3dcf-11e9-9400-6bba6c4bb821.png)

**Minimal reproduction project:**

[parent_resources_bug_test.zip](https://github.com/godotengine/godot/files/2923257/parent_resources_bug_test.zip)

**Comment by reduz** [comment]
The obvious way to fix this I guess is to automaticaly make it unique when saving, but detecting this scenario is not simple.
