### ISSUE TITLE
Make Node.addChild() return what it added

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#26542]
Godot version: 3.1 beta 8
Windows 7 home 64 bit

Please make the node add child functions return what they added.
this small change would allow for doing things like this..

	if (objects.has(key)):
		objects[key] = get_node("Blocks").add_child(block.instance()); 

its a one liner to create a instance add it to the Block group and then add it to the dictionary

**Comment by Zylann** [comment]
Duplicate of https://github.com/godotengine/godot/issues/6521

**Comment by reduz** [comment]
I am not a fan of this, I prefer things explicit even if you have to write more code.

**Comment by groud** [comment]
>  I prefer things explicit even if you have to write more code.

I agree.

**Comment by akien-mga** [comment]
Duplicate of #6521 indeed.
