### ISSUE TITLE
ERROR: get_edited_scene_root

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2654]
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:500.

How about opening the "Scene -> Project Settings -> main_scene" as default if there is one defined and no others are cached in "current_edited" on Project start.

Update: Godot is also not opening my recent used scenes on project start.

godot 2.0 master
OS:ubuntu

**Comment by firefly2442** [comment]
See also #2611 for my attempt at examining the issue.

**Comment by akien-mga** [comment]
Closing as duplicate of #2611.

**Comment by akien-mga** [comment]
Actually it was not really a duplicate of #2611, but it could now be considered a duplicate of #2731 which has more details and a proposed fix.
