### ISSUE TITLE
KinematicBody2D not moving when "Sync to Physics" is enabled

### ISSUE THREAD

**Issue by Bat-Computer** [godotengine/godot#26545]
**Godot 3.1 Beta 9**

**Windows 10, 64Bit**

**The Problem**
The new feature in Godot 3.1 where you are able to select the option "Sync To Physics". The article which has information about the feature in 3.1:

https://godotengine.org/article/godot-31-will-get-many-improvements-kinematicbody 

The bug was reported before and closed, but is still happening, see: 
https://github.com/godotengine/godot/issues/20230 

**What Should Happen**
A KinematicBody2D object with Sync To Physics enabled, should move as before with move_and_slide. I have also tested it with the manual method of moving. In each case the object no longer moves.

**Steps to Reproduce**
Simply create a scene with a typical node layout with a KinematicBody2D, Add a Sprite, Add a CollisionShape2D. Enable Sync To Physics option. In the script attempt to move the KinematicBody2D with move_and_slide.

**Comment by Nobelix** [comment]
Still happening in beta 10.

**Comment by Bat-Computer** [comment]
Closed, but still not working in Beta 11.

**Comment by mrcdk** [comment]
It was closed because the docs were updated. It's not a bug because `Sync to Physics` is not intented to be used at the same time as `move_and_slide()` or `move_and_collide()`

**Comment by Spartan322** [comment]
How are we expected to move the KinematicBody2D? As moving it in code with `position` does not seem to work at all, it will not allow any change to the `global_position` and the `position` value only changes to be the offset from the parent compared against the `global_position`

**Comment by piratesephiroth** [comment]
> 
> 
> How are we expected to move the KinematicBody2D in code? As moving it in code with `position` still does not seem to work at all, it will not allow any change to the `global_position` and the `position` value only changes to be the offset from the parent compared against the `global_position`

you can modify global_transform.origin
