### ISSUE TITLE
GDScript function parameters statically typed as script-defined classes can't be given a default value

### ISSUE THREAD

**Issue by MidZik** [godotengine/godot#26556]
**Godot version:** 3.1 beta 10

**Issue description:**
```
class A extends Reference:
	var a

func do_thing(parameter : A = null): # causes error
	pass

func do_different_thing(parameter : A = A.new()): # also causes error
	pass
```
The above script causes an error on line 4 (the function definition): `Value type (null) doesn't match the type of argument 'parameter' (parameter)`.

Line 7 causes a similar error.

If `parameter` is statically typed as any built-in class instead, it works fine. It's only for script-defined classes that the error appears.

**Comment by avencherus** [comment]
Would be nice to allow for this in situations where you follow with `if(parameter)` to see if one was provided, but I think that it probably has to be a variant to include null.

@vnen Currently, is there a proper way of typing an argument to a specific class, and making it optional at the same time?

**Comment by MidZik** [comment]
I don't know why I specified Reference specifically, this happens with all custom classes.

**Comment by MidZik** [comment]
I tested a bit more and realized you can't set _any_ default value, it's not limited to just null.

Updating the issue now.

**Comment by xDGameStudios** [comment]
> I tested a bit more and realized you can't set _any_ default value, it's not limited to just null.
> 
> Updating the issue now.

Can also confirm this:
```
func do_different_thing(parameter : A = A.new()): # also causes error
	pass
```

**Comment by jabcross** [comment]
Seconding this. As we don't have mandatory typing, and we'll probably never have the need for Option or something like it, I feel that this is feature is a must.

**Comment by Zylann** [comment]
Still happens in Godot 3.2 beta2
