### ISSUE TITLE
Some for loop iterator local variables are considered constant for some cases using dictionaries and arrays.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#26565]
**Godot version:**

a1e73dcc944627ab7185aec7cd4141fe4ebb97d7

**OS/device including version:**

Win10 64-bit

**Issue description:**

When iterating over some dictionaries and arrays, the key/element in the iterator now sometimes throws script errors.  I've run into it mainly in situations where I want to do `str()` or other String operations on the key of a dictionary in the local variable of the loop.

@bojidar-bg Maybe this didn't catch them all?  https://github.com/godotengine/godot/pull/26521

![godot windows tools 64_2019-03-04_07-19-30](https://user-images.githubusercontent.com/13004169/53712340-207e5700-3e4f-11e9-947c-3cddc44a6ea6.png)

**Steps to reproduce:**
Seems to be slightly unreliable to reproduce, the code here seems to trigger it.  Otherwise try the project.

```
tool
extends Node

func out(data, include_types : bool = false,
	indent_size : int = 3, depth : int = 0):


	match typeof(data):


		TYPE_DICTIONARY:

			for key in data:

				var val = data[key]
				key = str(key)
```

**Minimal reproduction project:**

[3.1 Iterator Constants Issue.zip](https://github.com/godotengine/godot/files/2924415/3.1.Iterator.Constants.Issue.zip)

**Comment by akien-mga** [comment]
Fixed by b24cb92.

**Comment by avencherus** [comment]
@akien-mga @vnen Regressions continue.  As of 49d82f2 it has gotten worse.  Simpler loops are now giving unusual errors.

![image](https://user-images.githubusercontent.com/13004169/53732050-59d1b980-3e85-11e9-8abd-09d9394ff5a5.png)
![godot windows tools 64_2019-03-04_13-54-27](https://user-images.githubusercontent.com/13004169/53732056-5fc79a80-3e85-11e9-9a77-51c341906df7.png)

[3.1 issue.zip](https://github.com/godotengine/godot/files/2926217/3.1.issue.zip)

**Comment by akien-mga** [comment]
You're outdated :) #26573

**Comment by avencherus** [comment]
Oh my.  XD  Will rebuild again.

**Comment by avencherus** [comment]
👍 Up to date now.  Everything in the loops so far checking out in the tools and release builds.
