### ISSUE TITLE
[2.0] Crash with two screens on ubuntu

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2656]
I get this message in the terminal after opening a project.
freed code id 1
BOOT SPLASH IS :

There is still something running. I don't get a Prompt.

Its crashing almost every time when I have a second screen connected(maybe because I move the open project window each time on anther location of my screen?).
Working on the main screen. No settings, trying directly from build.

After disconnecting the screen the project is always starting.

godot 2.0 master
OS:ubuntu

**Comment by phobos-tro** [comment]
Hi AlexHolly,

it looks like it is freezing. Please try the latest git master. There have been memory leak fixes for the X11 platform yesterday.

If the lastest git master is not solving your problem, please do the following:

1. `gdb bin/godot.x11.tools.64`
2. `run`
3. When you reach the point of the freeze, hit `CTRL + C` in the terminal where gdb is runnning.
4. `bt`
5. Post the backtrace (bt)

The backtrace will be helpful to find the cause of this issue.

Thanks.

**Comment by AlexHolly** [comment]
It is not crashing so much anymore but happend once.
```
[Thread 0x7ffff156b700 (LWP 3468) exited]
[Thread 0x7ffff15ac700 (LWP 3467) exited]
freed code id 1
[Thread 0x7fffeb2a2700 (LWP 3466) exited]
[Inferior 1 (process 3465) exited normally]
(gdb) BOOT SPLASH: 
BOOT SPLASH IS : 
Quit
(gdb) bt
No stack.
(gdb) 
```
I just found another bug.
It's crashing when I start Godot and drag the window to my second screen and snap it on the top to get directly a full screen ->"No stack".

**Comment by AlexHolly** [comment]
I made a driver update and now the resize works (Ubuntu 14.04)

```
sudo add-apt-repository ppa:xorg-edgers/ppa
sudo apt-get remove --purge nvidia*
sudo apt-get update
sudo apt-get install nvidia-331
sudo apt-get install nvidia-331-uvm
```
