### ISSUE TITLE
Sporadically failing to access functions

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#26564]
**Godot version:**
Godot 3.1 Beta 10 (if I remember correctly this happens since Beta 4 or 5)

**OS/device including version:**
Windows 10

**Issue description:**
It halts in two different situations sporadically; by calling `get_tree()` in `_physics_process` and by calling `Engine.get_frames_per_second()` in `_process`. I can't tell if the issue happens in C# as well.

Of course I'd be surprised if there's something wrong with these particular functions. I perceived every time it happens is when some other script is doing code on `_input`.

**Steps to reproduce:**
Create script A that uses `get_tree()` on `_physics_process` and then a script B that does something a little demanding, like instancing scenes, for each mouse click using _input. Then click a lot, very rapidly. May take a while.

**Comment by reduz** [comment]
This is too difficult to test and you can imagine there are plenty of games that do this same thing and have not reported failing, so please attach a project where you can effectively reproduce this behavior.

**Comment by reduz** [comment]
Are you doing something with threads?

**Comment by rafaelgdp** [comment]
Man, just create a simple project with the code you mentioned. The developers already have too many bugs to work on.

**Comment by mateusak** [comment]
@reduz No.

@rafaelgdp As I said, I don't know the cause. Sometimes I can reproduce sometimes I can't. If I were to guess it happens when the `_input` call lasts too long and when `_process` or `_physics_process` is called it's still going on. But I don't know the inners of the engine and that might not even be possible. However, if that's the case, I can't think of a way to create a minimal project to reproduce it.

**Comment by neikeq** [comment]
Is this a regression? Can you reproduce it older versions?

**Comment by mateusak** [comment]
@neikeq I started the project at beta, wouldn't be able to tell you... You can't convert beta projects to 3.0 can you? Anyway I know this happens since beta 4, but I think that's just because I started doing code in `_input` in that beta. Maybe the issue began earlier.

Anyway I tried doing a minimal project and failed miserably. This is all the info I have:
1. Necessarily involves `_input`. I moved my code from `_input`, since I was just using it there to debug and now it doesn't give any errors.
2. Maybe it's a C# to GDScript thing. I did code in `_input` using C# and the code that gave the error was from GDScript.
3. Gives this error: `Attempt to call function 'some_random_function' in base 'previously freed instance' on a null instance.`

If I can do besides creating a minimal project, let me know.

**Comment by akien-mga** [comment]
If it happens only on `_input`, I wonder if it's related to #26395. Maybe you receive so many events that you get race conditions?

**Comment by akien-mga** [comment]
> You can try to call Input.set_use_accumulated_input(true) and see if that fixes it.

It's now enabled by default with ecd8795, so you can test directly.

**Comment by reduz** [comment]
My feeling is that this is memory corruption related, wil let @hpvb take care of this. I am sure running godot with sanitizer enabled may do the trick.

**Comment by akien-mga** [comment]
Any update @mateusak? Is this still reproducible in the current master branch?

**Comment by mateusak** [comment]
@akien-mga Oh sorry I'm quite busy. I tried to reproduce the issue on a minimal project using different approaches but I couldn't. Anyway, I don't have much time to rigorously test it and since I don't know exactly what's happening, maybe close the issue, and hope someone else finds the exact culprit?

I can tell what I was doing, though:
I was testing pathfinding on a tower defense game, thus spawning troops on mouse click. Troops at first were KinematicBodies2D, but because of FPS issues they were converted to Areas mimicking collision. After the conversion I couldn't reproduce the bug, even without changing what you said. I can only suppose it's because of the FPS difference.

**Comment by akien-mga** [comment]
I'll close it for now as without a way to reproduce it, this will be impossible to fix.

Please comment if you can reproduce it again, and we can reopen it.
