### ISSUE TITLE
GLES2: Shadow ignores transparency unless Opaque Pre-Pass and alpha-scissors is used

### ISSUE THREAD

**Issue by wombatstampede** [godotengine/godot#26568]
**Godot version:**
Godot 3.1beta10 (also at least seen on beta 9, and on beta 8 (there may depend on view angle)).

**OS/device including version:**
Windows 10
NVIDIA GT610

**Issue description:**
Shadow (Directional Light) of MeshInstances ignores transparency. Unless Depth Mode is "Opaque Pre-Pass" and alpha-scissors is enabled.
(But: the use of alpha-scissors is not always desireable for display quality as seen in the animation below.)

**Steps to reproduce:**
Use a meshinstance with transparent texture and transparency enabled. Add a directional light.
Demonstration:
![Shadow Alpha](https://i.imgur.com/lkBc1nT.gif)

It can be seen that the use of alpha-scissors severely degrades the display quality of the mesh. That is an expected effect of alpha-scissors but not acceptable IMHO as workaround to get proper shadows.

I checked these issues but they are not completely comparable:
https://github.com/godotengine/godot/issues/19444
https://github.com/godotengine/godot/issues/25536
https://github.com/godotengine/godot/issues/19752

**Comment by wombatstampede** [comment]
Update for 3.1beta11:
- Error: **No shadows** for "Depth Draw  Mode" "**Opaque Only**" if either:
  * Transparency Flag or "Use Alpha Scissor" is enabled
- Error: **Alpha-Scissor Threshold is ignored for Texture rendering** when "Depth Draw  Mode" is "**Opaque Pre-Pass**". But in that case the Alpha-Scissor Threshold is correctly applied to the shadow (only).

It is great that transparent textures now show nice on Opaque Only (when using alpha-scissors) but sad that this is basically unusable (for now) because shadows have gone missing...

**Comment by OBKF** [comment]
I have noticed that there is some bug with depth draw too, where the meshes from the back render on front ignoring the front ones. in my project I have noticed I can see the highlights of the trees from the shades side (it supposed to look dark from the my point of view).

GLES3
![normal](https://user-images.githubusercontent.com/12987951/54070722-ca048480-4263-11e9-88e4-bc24b1b58aca.png)
![normal_2](https://user-images.githubusercontent.com/12987951/54070724-d2f55600-4263-11e9-9d06-592dba4fa1a7.png)

GLES2
![bug](https://user-images.githubusercontent.com/12987951/54070726-dd175480-4263-11e9-8512-58af79af85ee.png)
![bug_2](https://user-images.githubusercontent.com/12987951/54070728-e30d3580-4263-11e9-9115-1b86c3396b7d.png)
