### ISSUE TITLE
Engine.time_scale float equality check failed

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#26561]
**Godot version:** Godot 3.1 Beta 10

**OS/device including version:** Windows 10

**Issue description:**

This makes me question if my brain is still working.

1. Paste this in some node:
```
var slo_mo_time_scale = 0.2

func _process(delta):
	if Input.is_action_just_pressed('ui_cancel'): # Esc
		print('time_scale = ', Engine.time_scale)
		if Engine.time_scale != slo_mo_time_scale:
			Engine.time_scale = slo_mo_time_scale
		else:
			Engine.time_scale = 1
```
2. Press `Esc` multiple times to toggle (not working)
3. Output prints:
```
time_scale = 1
time_scale = 0.2
time_scale = 0.2
...
time_scale = 0.2
```
4. Works normally if `slo_mo_time_scale` is an integer, for example: 2

**Comment by Valeryn4** [comment]
Floating point operations are not always accurate.
This data should always be rounded off!
Use this:
static func compare_floats(a, b, epsilon = 0.001):
    return abs(a - b) <= epsilon

**Comment by MidZik** [comment]
Tangentially, Godot likes to format its float values to be pretty, which is why your debugging failed to spot the issue. If you add more precision to your prints, you would see the problem:
```
Engine.time_scale = 0.2
print("%.16f" % [0.2]) # prints 0.2000000000000000
print("%.16f" % [Engine.time_scale]) # prints 0.2000000029802322
```
This is why you avoid equality comparisons with floating point numbers.

**Comment by groud** [comment]
Equality between float can never been guaranteed.  You may use Math.is_equal_approx instead.
