### ISSUE TITLE
Using "range()" in for loop throws error

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#26572]
**Godot version:**
master 3.1_beta 788939b

**OS/device including version:**
Mac OSX Mojave

**Issue description:**
Below are two examples of the problem:

CODE:
`for i in range(len(p_rules) - 1, -1, -1):`
ERROR:
`Parse Error: No constructor of 'Vector3' matches the signature 'Vector3(int, int, int)'.`

CODE:
`for i in range(state.get_node_property_count(0))`
ERROR:
` Parse Error: No constructor of 'int' matches the signature 'int(int)'`

Notes: this was introduced in the last 12 hours, yesterday it worked well

**Comment by volzhs** [comment]
facing same issue.

```gdscript
func _ready():
    # Parser Error: No constructor of 'Vector2' matches the signature 'Vector2(int, int)'.
    for i in range(1, 10):
        pass
```
