### ISSUE TITLE
Implicit type conversion checking causes unrelated parser errors

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#26571]
**Godot version:**
Godot 3.1 master

**Issue description:**
Seems like #26562 has broken my project completely, do I have to do explicit type conversion now? Parser spams errors like this:

![vector2_conversion](https://user-images.githubusercontent.com/17108460/53726959-c6de5280-3e77-11e9-92ec-58f8a5d120e2.PNG)

But it doesn't even seem like it's related to type conversion, for instance I'm using godot-logger and the above error pops up at these lines which seems to be unrelated:

https://github.com/KOBUGE-Games/godot-logger/blob/856fb070ec08d2c523abba2f05a8f30f1ce8b086/logger.gd#L402-L403

I do have lots of other instances of this in my project, so maybe it's interfering with something else.

**Comment by th1z** [comment]
I encountered a similiar problem:

```
self.target_node.global_position.x = 0.0
self.target_node.global_position.y = 0.0
```
will result in the following error:
> Assigned value type (int) does not match variable type (float)

**Comment by Xrayez** [comment]
#26572 reported similar issue with `range()` which is present in `logger.gd` snippet above but with Vector3.

**Comment by xDGameStudios** [comment]
I guess now we will be needing Vector2 overloads for Vector2(int, int) and range overloads for range(int, int, int).

Just out of curiosity does this work?
`Vector2(float(value), float(value))`
