### ISSUE TITLE
Generate Visibility Rect doesn't register as undo/redo action

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26575]
**Godot version:**
3.1 beta10

**Issue description:**
I noticed a new "Particles" menu at the toolbar, which has an option called "Generate Visibility Rect". The problem is that generating the rect doesn't count as action, so you can't undo it and it doesn't even mark scene as changed.

**Steps to reproduce:**
1. Place Particles2D
2. Add some fancy effects etc.
3. Press Particles -> Generate Visibility Rect
4. Try to undo it

**Comment by xDGameStudios** [comment]
I'm giving it a shot!
