### ISSUE TITLE
[2.0] ERROR OPENING FILE: icon.png on godot start

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2658]
Is it possible to add the icon into the build?
Sometimes it shows an icon after I open a project, most of the time it's just grey.

OS:ubuntu

**Comment by akien-mga** [comment]
Probably related to #2652.

**Comment by AlexHolly** [comment]
It looks like it's fixing the project icon but not the default icon on the project list manager.

I changed the icon="icon.png" to icon="res://icon.png" manually on one of my projects.
On the first start of the project the icon is still grey when I press "Quit to project list" and start the same project again it is showing the icon. So when I reopen the project without closing the engine the icon is grey again. Some kind of a toggle method. After a few times the icon is always showing.
When I go back to the project list the icon is still there and not grey.
So there is still something buggy. Godot is also crashing sometimes on this process of trying.

**Comment by akien-mga** [comment]
#2652 has been merged, does it at least fix the issue you were having if you create new projects after this change?

**Comment by AlexHolly** [comment]
I still get "ERROR OPENING FILE: icon.png" on godot start and after opening a project the icon is still grey, after closing the project and reopen it shows the icon.

Nothing changed...

**Comment by akien-mga** [comment]
And if you create a new project?

**Comment by AlexHolly** [comment]
It is not showing the "ERROR OPENING FILE: icon.png" and also not showing the icon.

Already tried both, old project and created a new one.

**Comment by reduz** [comment]
This is an ubuntu related problem, I could never figure out how to fix it, does not happen on other WMs

**Comment by akien-mga** [comment]
I'm tempted to close this issue as old, I've not experienced this in a long time. Can you still reproduce it @AlexHolly?

**Comment by AlexHolly** [comment]
The  "ERROR OPENING FILE: icon.png" is gone but on unity I still can't see the icon in the menubar.
I just tested with XUbuntu and it works.

**Comment by akien-mga** [comment]
This is likely a different issue then, as this error about opening `icon.png` was more a filesystem issue IIRC. Could you open a new issues with details about what works on what doesn't? (i.e. if all Godot games lack icons, if the editor does too, or only some of them, etc.)

**Comment by AlexHolly** [comment]
I think there is no more need to fix this since Ubuntu 18.04 LTS will use gnome as default.
