### ISSUE TITLE
App Store: ios sdk version issue

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#26593]
Godot 2.1.5

Got this warning while trying uploading an app update on the Apple store:

> This app was built with the iOS 11.4 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.

![photo_2019-03-04_16-24-18](https://user-images.githubusercontent.com/5225262/53744898-42eb9100-3e9e-11e9-8380-5b1b09592c19.jpg)

I believe we need a new ios template

**Comment by samgreen** [comment]
Happy to take this on.

**Comment by samgreen** [comment]
@zoiba in the meantime, you should be able to resolve this in Xcode by changing the “Bask SDK” in the Xcode project settings if you’re so inclined.

**Comment by Imerion** [comment]
Hi! I'm also affected by this. @samgreen Really happy to hear you are taking this on! How would I go about to change the Base SDK? The only items I can choose there when in the Build Settings are iOS, macOS, tvOS and watchOS. Perhaps I'm looking in the wrong place?

**Comment by samgreen** [comment]
Here's the [Official Documentation](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html) on this process. If I'm understanding the error posted above, you'll need to update your Xcode to a version that provides (Base SDK) iOS 12.1 support. Then you can step your **Deployment Target** back down to the _lowest_ iOS version you'd like to support. Godot currently supports iOS 10 and above.

**Comment by Imerion** [comment]
Sorry for my basic knowledge about this. I am currently using Xcode 10.2, so I guess it comes with the latest SDK? But when I build and archive and try to upload it I get the above message, which if I have understood things right means the godot export file needs to be built with iOS SDK 12.1. Or can I change this in my project somehow by getting another SDK and setting the project to use it instead?

I really appreciate that you are helping me with this! Thanks again!

**Comment by akien-mga** [comment]
Should be fixed by 24d516c50 and GodotBuilder/godot-builds@7652fb7213e324b2b12e99c18821e881f95293e5. I'll keep it open for now until we have builds to confirm.

**Comment by Imerion** [comment]
I can confirm I no longer have this problem. Upload to AppStore using latest XCode works fine using the 2.1.6 RC1 export template.

**Comment by akien-mga** [comment]
Awesome, thanks!
