### ISSUE TITLE
Deleting Scene if root node is changed

### ISSUE THREAD

**Issue by mani144** [godotengine/godot#26596]
**Godot version:**

3.1 Beta 8

**Issue description:**

I changed the root scene and made it the child, however when i closed the scene the root was emptied.
and i`m not sure if i saved or not

**Steps to reproduce:**
Create a Scene, put multiple nodes in it, change the root node to be one o the childs.

**Comment by bojidar-bg** [comment]
Potential duplicate of #24484.

Can you retest on beta 10? It might have been potentially fixed.

A video of the reproduction would be welcome :smiley:.

**Comment by mani144** [comment]
> 
> 
> Potential duplicate of #24484.
> 
> Can you retest on beta 10? It might have been potentially fixed.
> 
> A video of the reproduction would be welcome 😃.

Beta 10 seems working thanks 👍
