### ISSUE TITLE
Play button should Restart Project if it's already running

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2659]
Why do I have to press "Stop the Scene" first to restart the project?

"Play the Project " -> "Stop the Scene" -> "Play the Project "

Why not 

"Play the Project " -> "Play the Project(restart if running) "

I always forget to close the game so I change something and press Play but it doesn't work I have to "Stop the Scene" -> "Play the Project " ....

So annoying :D are there any side effect to add this feature?

**Comment by aaschmitz** [comment]
:+1:

**Comment by bojidar-bg** [comment]
:+1:¹⁰

**Comment by akien-mga** [comment]
Fixed by #2696.
