### ISSUE TITLE
Can't create user data, config or cache paths if ~/.local, ~/.config or ~/.cache are missing

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#26598]
**Godot version:**
3.1 beta 10

**OS/device including version:**
Linux

**Issue description:**
Now when I run godot with root privileges, then I just got empty project manager and this error:
```
ERROR: create: Cannot find path for data directory!
   At: editor/editor_settings.cpp:784.
ERROR: save: Cannot save EditorSettings config, no valid path
   At: editor/editor_settings.cpp:992.
```
It can be slightly misleading for some people, who will not know what they do not see their own projects.

**Comment by hpvb** [comment]
This means that the XDG data dirs aren't being properly created. This is not a root-user specific problem.
