### ISSUE TITLE
Godot editor infinite loop when setting tilemap scale to (0,0)

### ISSUE THREAD

**Issue by Premislaus** [godotengine/godot#266]
1. Add TileMap.
2. In Inspector set scale to x = 0, y = 0.
Then the program hangs, and consumption of RAM is more than 500 MB.

**Comment by kubecz3k** [comment]
After all that time the bug seems to be valid in build bd736e5af2ec5113c23fef58523f57a0b2e11fb2
Quick video confirmation: https://youtu.be/6YgizmJgmcc

**Comment by bojidar-bg** [comment]
Seems like a problem with near-unlimited grid drawing to me. That would explain why it doesn't work in-game.

_BTW, this is a freeze/infinite loop/hang, and not a deadlock. See more info on wikipedia [about deadlocks](https://en.wikipedia.org/wiki/Deadlock) and [about hanging](https://en.wikipedia.org/wiki/Hang_(computing))._
