### ISSUE TITLE
Godot still using CPU/GPU even if the window is not visible

### ISSUE THREAD

**Issue by PabloNeirotti** [godotengine/godot#26605]
**Godot version:**
v3.1.beta8.official (also v3.0)

**OS/device including version:**
macOS Mojave (10.14.3)

**Issue description:**
Godot seems to continue rendering even if the window is opened on another desktop or it's own fullscreen desktop, while I am on another desktop. This takes a big performance hit on my machine while multitasking, and it's specially bad if I am play-testing, which means I am rendering the game twice: the Godot scene I currently have open in the editor, and the game on runtime. Ideally Godot wouldn't need to use much of the GPU nor CPU while it's not visible.

**Steps to reproduce:**
Open Godot, specially something that has an intensive graphic processing on the scene (Particles, HDR maybe), make it full screen, then switch to your regular desktop. Watch the Activity Monitor. Godot still ranking #1 in CPU and Energy consumption.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/16397 (which could be enabled automatically when the project is running).

**Comment by PabloNeirotti** [comment]
There is little consumption while minimized, the real issue is when it is fullscreen on another desktop - it’s still eating a lot of CPU time even if it can’t be seen.

It makes it a pain to work in fullscreen mode 😅

**Comment by Calinou** [comment]
I doubt it'd be easy to implement a method/signal that can be used to check whether the Godot window is covered by other windows. This is technically possible, see [Chrome which can detect this as of recently.](https://webplatform.news/issues/2019-03-27#web-pages-can-now-detect-when-chrome-s-window-is-covered-by-another-window).

**Comment by PabloNeirotti** [comment]
That’s probably for a different issue.

Most apps I use on macOS seem to know if they are not visible due to being minimized or in a different desktop. Godot only seems to check if it’s minimized, but not a different desktop.

If the same power saving could be done when Godot is on a different desktop other than the active one, then that’d be amazing.

**Comment by Calinou** [comment]
This is now addressed in the editor by https://github.com/godotengine/godot/pull/29297 (further improved by https://github.com/godotengine/godot/pull/47813). For projects, this will be addressed by https://github.com/godotengine/godot-proposals/issues/2001.

See https://github.com/godotengine/godot-proposals/issues/942 for pausing animated simulations to save resources in the editor.
