### ISSUE TITLE
radeon: Failed to deallocate virtual address for buffer

### ISSUE THREAD

**Issue by MatiasVME** [godotengine/godot#26606]
**Godot version:**
Godot.3.1.beta10.official

**PC Info:**
```
elementary OS 5.0 Juno (64 bits)
Linux 4.15.0-45-generic
GTK+ 3.22.30
```
```
matias@matias-Lenovo-ideapad-110-14ISK:/media/disco/programas$ lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 510 (rev 07)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:17.0 SATA controller: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 (rev f1)
00:1c.4 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 (rev f1)
00:1c.5 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-LP LPC Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
01:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / R7 M520] (rev 83)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL810xE PCI Express Fast Ethernet controller (rev 07)
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821AE 802.11ac PCIe Wireless Network Adapter
```

**When I open my project says (maybe can help):**
```
matias@matias-Lenovo-ideapad-110-14ISK:/media/disco/programas$ ./Godot_v3.1-beta10_x11.64 
WARNING: initialize: XOpenIM failed
   At: platform/x11/os_x11.cpp:192.
Found discrete GPU, setting DRI_PRIME=1 to use it.
Note: Set DRI_PRIME=0 in the environment to disable Godot from using the discrete GPU.
WARNING: initialize: XCreateIC couldn't create xic
   At: platform/x11/os_x11.cpp:487.
OpenGL ES 3.0 Renderer: AMD HAINAN (DRM 2.50.0, 4.15.0-45-generic, LLVM 7.0.0)
Editing project: /media/disco/git/project-humanity (::media::disco::git::project-humanity)
WARNING: initialize: XOpenIM failed
   At: platform/x11/os_x11.cpp:192.
WARNING: initialize: XCreateIC couldn't create xic
   At: platform/x11/os_x11.cpp:487.
OpenGL ES 2.0 Renderer: AMD HAINAN (DRM 2.50.0, 4.15.0-45-generic, LLVM 7.0.0)
```
**Explanation:**

I'm sorry for my bad English.

I'm making a prototype of a game, and several times a day I have an error. It causes godot to freeze and sometimes the pc (After a while).

I don't know when the error occurs, it just happens at different times, without an apparent visible cause.

**Console error:**

```radeon: Failed to deallocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    va        : 0x860000
radeon: Failed to allocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 2
radeon:    va        : 0x0000000000860000
radeon: Failed to deallocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    va        : 0x860000
radeon: Failed to allocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 2
radeon:    va        : 0x0000000000860000
radeon: Failed to deallocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    va        : 0x860000
radeon: Failed to allocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 2
radeon:    va        : 0x0000000000860000
radeon: Failed to deallocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    va        : 0x860000
radeon: Failed to allocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 2
radeon:    va        : 0x0000000000860000
radeon: Failed to deallocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    va        : 0x860000
radeon: Failed to allocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 2
radeon:    va        : 0x0000000000860000
radeon: Failed to deallocate virtual address for buffer:
radeon:    size      : 131072 bytes
radeon:    va        : 0x860000
radeon: Failed to allocate virtual address for buffer:
radeon:    size      : 131072 bytes
....
```

[full-radeon-error.txt](https://github.com/godotengine/godot/files/2927988/full-radeon-error.txt)

**Comment by akien-mga** [comment]
Running Godot with `DRI_PRIME=0 ./Godot` might work around the issue by using your Intel iGPU.
But the radeon issue should still be investigated nevertheless.

What is your Mesa version?

**Comment by MatiasVME** [comment]
I don't know how to see the version but is it any of these?

![captura de pantalla de 2019-03-04 17-22-38](https://user-images.githubusercontent.com/342117/53760653-50a31580-3ea2-11e9-9612-48aa02edca1f.png)

Thanks, I'll try the intel.

**Comment by santouits** [comment]
I get this problem in a laptop with radeon and godot just reveals the problem because it forces you to use the radeon card. The radeon card never worked good but most systems just use the integrated one for everything and you don't know it. It shouldn't be godot's place to choose which card to use and that code should be removed. 
For your problem to check if your amd driver is problematic not only for godot but for everything, open a terminal and set DRI_PRIME to 1, and then run inside the same terminal a game like this:
```
export DRI_PRIME=1
./game
```

**Comment by Calinou** [comment]
This seems to be a bug with the graphics driver, should we leave this open?

**Comment by akien-mga** [comment]
Well, the part which is Godot-specific is that we default to set `DRI_PRIME=1` to use the discrete GPU on Linux if there's one, and in some situations where the dGPU is actually bogus, this leads to the inability to use Godot.

That's why I was against defaulting to using the dGPU on Linux initially.

Still, current Mesa drivers for "recent" AMD GPUs (i.e. not from 2013 like Hainan) work very well, and the upcoming Nvidia proprietary series will finally add built-in support for Optimus (with support for `DRI_PRIME=1` as a toggle), so time is playing in favor of keeping this behavior.

There are thankfully not too many reports of users having issues with that, so I think we can close this. I'm open to re-assess if we get more reports though and a significant part of game players are affected, which is arguably more problematic than engine users who can work it around with `DRI_PRIME=0`.

**Comment by Goodymind** [comment]
This happened to me today, Godot 4 was previously working, but now it's not. The only notable changes I did to my dualboot system is i changed the sizes of the partition and linux mint's update manager did it's auto update. Everything else is working though
