### ISSUE TITLE
GodotSharp/Mono - The type or namespace name 'CLASSNAME' could not be found (are you missing a using directive or an assembly reference?)  [PROJ_NAME] 

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#26610]
**Godot version:**

3.1.10 beta (Mono)

**OS/device including version:**

Win10

**Issue description:**

Editing C# project in VSCode throws error "The type or namespace name 'CLASS_NAME' could not be found (are you missing a using directive or an assembly reference?) [PROJ_NAME]"

**Steps to reproduce:**
1. download Mono Godot 3.1.10beta
2. Create project.
3. setup VSCode editing
4. Create a `.cs` file in VSCode, (not thru the Godot engine!)
5. Intermittent build errors will occur, where Omnisharp/VSCode cannot locate your files. Then it can locate it, but it'll quickly forget and be unable to again.

**Solution**
I believe this is occurring because files are not added to the `PROJ_NAME.csproj` MSBuild configuration when added outside of the Godot Engine. If you open up that file you'll see (at the bottom):

```
<ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="src/FILE_ADDED_BY_CLICKING_IN_GODOT_EDITOR.cs"/>
    <!-- you won't see files created thru VSCode -->
  </ItemGroup>
```

To fix add `<Compile Include="*.cs"/>` in that given ItemGroup. See [here](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2017#use-wildcards-to-specify-items)

**Comment by JarLowrey** [comment]
Hmm well I thought that would work but I was still having (slightly less) intermittent issues. Loading the project in VS2017 and dragging my src/ folder in solved the problem, by adding all the .cs files to my .csproj file. Not sure what the best way to create new files is then, given that we're using VSCode as the external editor.

**Comment by akien-mga** [comment]
Is it still reproducible with the latest 3.2 builds?

**Comment by akien-mga** [comment]
I'll assume it fixed for now as Godot's C# support matured a lot since March 2019, and I haven't seen other reports for the same issue (though many are using VSCode).

Please comment if you can still reproduce it and we'll reopen.

**Comment by ThitTheThit** [comment]
> 
> 
> Is it still reproducible with the latest 3.2 builds?

Yes, just had the problem but it's an easy fix (just add the script path to the .csproj file)

**Comment by William-Owen** [comment]
> Yes, just had the problem but it's an easy fix (just add the script path to the .csproj file)

Thanks; that fixed my issue. There must be a better way to keep this updated though?
