### ISSUE TITLE
Rect2().encloses(Rect2()) with same rect is false

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#26615]
Result is false, expected true
`Rect2(0,0,1,1).encloses( Rect2(0,0,1,1) )` 
`Rect2(0,0,0,0).encloses( Rect2(0,0,0,0) )`

https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/core/math/rect2.h#L99

Compared with java

```
import java.awt.Rectangle;

class Main {
  public static void main(String[] args) {
    System.out.println(new Rectangle(0,0,1,1).contains(new Rectangle(0,0,1,1))); // true
    System.out.println(new Rectangle(0,0,0,0).contains(new Rectangle(0,0,0,0))); // false
  }
}
```

I suggest simply do <= instead of < 
https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/core/math/rect2.h#L102-#L103

It will return true in this case which differs from Java but that should be fine.
`Rect2(0,0,0,0).encloses( Rect2(0,0,0,0) )`

**Comment by aaronfranke** [comment]
I suppose the question then would be "what is the desired functionality"? Should a rectangle enclose itself? What are the game programming use cases for true vs false?

See also: https://github.com/godotengine/godot/issues/25829

**Comment by xakz** [comment]
if A is a Rect2 representing the game map area
and B is a Rect2 reprensenting the area of a building 
then
A.encloses(B) should return true because the workaround is enlarging virtually the map (not really good) or shrinking virtually the futur building (probably by 0.1 map unit) => not very elegant but its what I do because of this bug

**Comment by akien-mga** [comment]
@xakz What's your use case for `A.encloses(B)` if A is the same size as B?

**Comment by xakz** [comment]
@akien-mga Probably none but:
Rect2(0, 0, 2, 2).encloses(Rect2(1, 1, 1, 1)) returns false
and
Rect2(0, 0, 2, 2).encloses(Rect2(1, 1, 0.99999, 0.99999)) returns true

For world coordinates, it's not really a problem, but for map coordinates (TileMap) it's not what one expect. We expect a 1x1 tile fit in 2x2 tile.

Just some precisons in the doc could be enought.

**Comment by fossegutten** [comment]
Rect2.encloses method is inconsistent now. 
When it checks for >= on top and left side, but < on right and bottom sides. Agree with @AlexHolly  that it should be changed from <=.
Alternatively > and < on encloses method, and make a new "contains" method, that uses >= and <=,

**Comment by Xrayez** [comment]
Some geometry methods follow non-strict inequalities already:

https://github.com/godotengine/godot/blob/08272585e9daa3dfb4988e7f495212ffe5979bfc/doc/classes/Geometry.xml#L219-L242

I've also had to define some constant to emulate strictness (copied directly from my custom camera class to be enclosed within world limits):
```gdscript
const LIMIT_MARGIN = 1.0 # if 0.0 - strictly enclosed
```
