### ISSUE TITLE
Low frame rate using TileMap on Android

### ISSUE THREAD

**Issue by myhalibobo** [godotengine/godot#26620]
Godot version:
Godot_v3.1-beta10_win64

OS/device including version:
Honor 8 Lite

Issue description:
The effect of android running
![image](https://user-images.githubusercontent.com/8662169/53775535-ea63d480-3f2d-11e9-84a2-bae347b340b1.png)

Minimal reproduction project:
[tilemap_test.zip](https://github.com/godotengine/godot/files/2950388/tilemap_test.zip)

**Comment by volzhs** [comment]
gles2 or 3?

**Comment by myhalibobo** [comment]
@volzhs I tested it. It's all the same

**Comment by volzhs** [comment]
related #7885

**Comment by MatiasVME** [comment]
More evidence from the case.
https://youtu.be/NW5qQgb5LM8

If you need information about the android device (lenovo tab 4) tell me.

**Comment by Calinou** [comment]
Duplicate of #7885.
