### ISSUE TITLE
Serious hang on change_scene() in 3.1 betas

### ISSUE THREAD

**Issue by varkatope** [godotengine/godot#26625]
**Godot version:**
3.1.beta10.official, but also all betas I've tried

**OS/device including version:**
Windows 10 64bit, GTX 970 w latest drivers (happened with previous drivers as well), 16GB RAM, Intel 5820K @3.3 GHz

**Issue description:**
When changing scenes in 3.1 betas, it can take anywhere from 2 seconds to more than a minute to change the scene. The CPU goes from a few percent to around 10%, so it seems to be doing...something. GPU usage drops to 0%. RAM doesn't really change during that time. There are a few debug warnings ("The function 'change_scene()' returns a value, but this value is never used.") but no errors, and the external console window doesn't list anything interesting.

Same project in 3.0.6 takes maximum 2-3 seconds to change the scene every time.

**Steps to reproduce:**
In the minimal project attached, walk (WASD + mouselook) into the green light. You should be able to switch back and forth between two scenes. The amount of time that takes seems pretty random, so do that several times.

**Minimal reproduction project:**
[SwitchSceneMinimal.zip](https://github.com/godotengine/godot/files/2929776/SwitchSceneMinimal.zip)

**Comment by eon-s** [comment]
The scene file is really big due to the GI data, try saving the data on an external `.res` file and check again.

**Comment by varkatope** [comment]
@eon-s, you're a genius. Just tried that with beta 11 and it worked great. I am a little confused as to why the same scenes worked fine in 3.0.6 without this change, though. That's why I didn't suspect the GI.

Also, there's no mention of saving the GI data outside the scene in the latest docs for GI Probe. Might be a good idea to add some info, especially if not saving the data externally causes this problem to crop up.

Thanks for your help!

**Comment by eon-s** [comment]
It is a constant issue with mb sized arrays since 2.x on PackedScene resources, complex meshes can also do this, I think that resourceSaver need a smarter way to treat big data arrays.

**Comment by eon-s** [comment]
And the loading factor may not affect exported games since all resources are on binary format, but is annoying to use with the editor.

**Comment by Calinou** [comment]
> Also, there's no mention of saving the GI data outside the scene in the latest docs for GI Probe.

As a side note, this is now handled automatically in GIProbe in the `vulkan` branch. GIProbeData will always be saved to an external `.res` file.

Anyway, I'll close this in favor of #33379.
