### ISSUE TITLE
[Mono] Godot editor crashes due to exported properties on a resource pt. 2

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#26628]
**Godot version:**

80618700ca668a595fd214ca8db43a69ca2a8b67

**OS/device including version:**

Antergos

**Issue description:**

Editor crashing again (#20987) when building due to exported properties in resources.

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
```

Is what the console gives.

The crash may occur when buildling, when inspecting a resource with a C# script attached, or when the game runs.

**Steps to reproduce:**
```cs
using Godot;

public class ResA : Resource
{
    [Export]
    public ResB resB;
}
```

```cs
using Godot;

public class ResB : Resource
{
    [Export]
    public string x;
}
```

Assign these scripts to two different resources.

**Minimal reproduction project:**

[CustomResourceCrash.zip](https://github.com/godotengine/godot/files/2930115/CustomResourceCrash.zip)

**Comment by neikeq** [comment]
I just tested without the project you uploaded. I can reproduce the crash in the game but not in the editor.

**Comment by neikeq** [comment]
#26773 fixes the crash I experienced when running the game. Let me know if anything is missing.
