### ISSUE TITLE
Member variable setting will not stick on scene created from branch

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#26623]
**Godot version:**

```
3.1.beta9.official
```

**OS/device including version:**

Linux

**Issue description:**

**Steps to reproduce:**

1. Create a scene with a spatial as root
2. Add a `Particles` node as a child of root
3. Disable `Particles.emitting`
4. Select `Create scene from branch` on the Particles
5. Delete the `Particles` instance from the main scene
6. Go to the new Particles scene
7. Enable `emitting`
8. Go back to the main scene
9. Go back to the particles scene
10. `emitting` is disabled again

**Minimal reproduction project:**

![out](https://user-images.githubusercontent.com/2496231/53778761-dab3a400-3ecb-11e9-8582-36576a6a36d1.gif)
[example.zip](https://github.com/godotengine/godot/files/2929139/example.zip)

**Comment by akien-mga** [comment]
I can't seem to reproduce it in 3.2.2 RC 2, so assuming fixed. Please comment if you can still reproduce the issue.
