### ISSUE TITLE
Make signal names more consistent

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#26621]
Why are some signals the same name as methods, particularly on the same Class? Another example is `minimum_size_changed` signal and `minimum_size_changed()` method on Control nodes. I'm not even sure what the latter function even does. No documentation on it and doesn't return anything.

It seems signal names have some kind of naming patterns, like `tree_entered`,`tree_exited`, `area_entered`, `renamed`, `visibility_changed` and so on. A past-tense kind of action that has occurred. `hide` is kind of confusing as a signal name. Shouldn't it be something like `became_hidden` or `has_hidden`?

**Comment by MidZik** [comment]
I'm not able to reproduce this.
```
world_view.visible = false
print(world_view.get_children()[0].visible) # prints True
```

**Comment by groud** [comment]
Please provide a reproduction project

**Comment by Oranjoose** [comment]
Nevermind, discovered the source of the problem. Had to do with the `hide` signal of CanvasItem being the same name as the `hide()` method. Why are some signals the same name as methods? Another example is `minimum_size_changed` signal and `minimum_size_changed()` method on Control nodes. I'm not even sure what the latter function even does. No documentation on it and doesn't return anything.

**Comment by akien-mga** [comment]
The exact signals with inconsistent names should be added to #16863.
"hide" should likely be renamed to "hidden" or "was_hidden".
Not sure about "minimum_size_changed".
