### ISSUE TITLE
Shadows get clipped at runtime in orthogonal mode

### ISSUE THREAD

**Issue by xfixium** [godotengine/godot#26637]
Godot version:
Tested on all versions of 3.1 betas using GLES2 mode (May exist for GLES3 as well)

OS/device including version:
Various computers running Windows 7 and 10, shitty Intel based GPUs

Issue description:
Shadows clip out on the left and right sides of a scene when moving a 3D object around using a direction light with shadows enabled (Orthogonal, PSSM, Stable, Optimized options used, doesn't stop this bug), and an angled camera in orthogonal mode. This does not affect the 3D editor, or when using the camera view within the editor. Seems to only happen at runtime.

It looks like it clips more depending on the width of the game window. If the window is maximized, the shadows no longer clip on the left and right sides. Bare bones project provided (3.1 beta 7).

Steps to reproduce:
Load the provided project, click and drag the cube around the scene, notice how the shadow of the cube disappears when dragging it to the left or right edge. Now maximize the game window. It appears the shadow does not get clipped.

Minimal reproduction project:
base project provided
[shadow_test.zip](https://github.com/godotengine/godot/files/2931193/shadow_test.zip)

**Comment by Calinou** [comment]
@xfixium Can you reproduce this on [Godot 3.2 beta 6](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-6)?

**Comment by xfixium** [comment]
Looks like the problem still persists in 3.2 beta 6. I tried taking a crack at fixing it myself some time ago, but it takes my computer forever to compile Godot on my Window 7 machine.

There is a test project in my first post, you could use that to test? If this gets fixed, that would be great!

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/562bc1941d390f2897ef04992e2bcdfda616d7a6. When moving the cube by holding the left mouse button, the shadow disappears when moving the cube towards the left or right borders. This happens regardless of the Camera node's view distance.

**Comment by xfixium** [comment]
Thanks for that information (work around)! I'll give that a go on my actual project.
