### ISSUE TITLE
[Regression] Shader Editor is always focused breaks shortcuts on Inspector

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#26644]
x11
https://github.com/godotengine/godot/commit/45e7306b5adec09746fefda902a5414e5b53fdfa

Shader Editor is always focused breaks shortcuts on Inspector
Reproduce:
1. Open Shader editor
2. Try to duplicate or delete a Node with CTRL+D or ENTF
3. See changes applied to shader editor.

**Comment by Chaosus** [comment]
Seems related - #12916

**Comment by Paulb23** [comment]
See also #17591

**Comment by steveday4u** [comment]
I don't think it is related to an old issue. 
When a shader material is open you can not leave the editor. Soit is not possible to edit the shader parameters which makes shader materials basically unuseable. Must have happend with yesterdays commits.

Steps to reproduce:
- create a ShaderMaterial
- load a shader file
- try to edit shader parameters

**Comment by KoBeWi** [comment]
Another related issue: #21592

**Comment by akien-mga** [comment]
Likely related to 472c94ce3 or 5b77aa6be. @reduz

**Comment by steveday4u** [comment]
looks good, thanks
