### ISSUE TITLE
How to enable fxaa but not msaa in Godot 3.1

### ISSUE THREAD

**Issue by JustusPan** [godotengine/godot#26646]
**Godot version:**

Godot 3.1 beta 10

**OS/device including version:**

**Issue description:**

There are some options to enable MSAA in Project Setting, while not one related to FXAA. 
I want get a basic AA effect with "cheapest" cost. How can I enable FXAA for my whole 3D scene?  

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This is discussed in https://github.com/godotengine/godot/issues/25843 which has a similar goal. FXAA was available in Godot 2.1, but it wasn't implemented when the rendering engine was rewritten in Godot 3.0.

**Comment by OBKF** [comment]
There is a code that works ([here](https://godotengine.org/qa/13916/fxaa-broken-in-godot-2-1-2)).
You just have to add it to MeshInstance Quad that is parented to the camera and edit it for 3.x (i will give the code if you can't convert it).

**Comment by Calinou** [comment]
For FXAA shader, see also https://gist.github.com/cart/7d2da58eb28c75c0952787f29f3e562f. (It's being used in the game High Hat, which uses the GLES2 renderer.)

**Comment by marcosjouron** [comment]
https://github.com/atomius0/Godot-3.1-FXAA-Shader

Hil @Calinou and @OBKF , I just trying to use a FXAA Shader in Godot 3.1 GLES3. I checked the @OBKF link and @Calinou ones but neither works ok in GLES3. Do you have any idea?
Thx in advance

**Comment by Zireael07** [comment]
That shader is 3rd-party, you can only hope for the author of it to help.

**Comment by marcosjouron** [comment]
Thanks @Zireael07 for your answer. Do you do any FXAA test in Godot 3.1 GLES3 with good results?

**Comment by OBKF** [comment]
@marcosjouron The version provided by @Calinou  works the best and it works fine. 
What  are the issues you are facing? can you provide screenshots or something?

**Comment by marcosjouron** [comment]
Oussama sorry for the delay, i didn't (realice) and read your answer. Thx for your time. Finally I don't need that any more and I detached it from my tasks. By the way I was two weeks ago in Poznanat GodotCon were you?

**Comment by rico345100** [comment]
Using 3.1.1 still no FXAA. Very disappointing.

**Comment by Calinou** [comment]
@rico345100 You can use the shader I linked here: https://github.com/godotengine/godot/issues/26646#issuecomment-501291571

**Comment by OBKF** [comment]
@marcosjouron Glad I could help. No unfortunately I couldn't be there, maybe another time.

**Comment by Calinou** [comment]
This was implemented in `master` and Godot 3.3 by https://github.com/godotengine/godot/pull/42006, closing.
