### ISSUE TITLE
Tilemap world_to_map() && half_offset && coords < 0 does not work as expected

### ISSUE THREAD

**Issue by Brickcaster** [godotengine/godot#2665]
When half offset is set to offset x, the offset behaves unexpectedly for  y<0.  Likewise, when half offset is set to offset y, the offset behaves unexpectedly for x<0.  world_to_map() will return the wrong coordinates half of the time. This can be tested in the editor.

In the first attached screenshot, the mouse cursor is at the black arrow where the blue lines intersect, but the highlighted tile is to the right.  In the second attached screenshot, the mouse cursor moves down along the blue line and the highlighted tile now is to the left.  Half offset is set to Offset X and the mouse is in the y<0 region.

The expected behavior is that the tile the mouse cursor is inside is to be highlighted.

![image](https://cloud.githubusercontent.com/assets/13324089/10695646/c4337b50-7972-11e5-8711-1823a4e3bb23.png)

![image](https://cloud.githubusercontent.com/assets/13324089/10695830/ce182cb4-7973-11e5-9b3a-bbcd13feeae8.png)

**Comment by Brickcaster** [comment]
Some additional detail: 

For (x % cell.width)/cell.width < 0.5, y<0 and y&1, world_to_map is (1,0) higher than it needs to be.

For (x % cell.width)/cell.width < 0.5, y<0 and !y&1, world_to_map is (1,0) lower than it needs to be.

For (x % cell.width)/cell.width > 0.5, it works fine.

**Comment by akien-mga** [comment]
Fixed in #2672.
