### ISSUE TITLE
Tilemap bucket fill tool doesn't have icon

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#26653]
**Godot version:**
3.1 beta 10

**Issue description:**
Tilemap - Drop down list with tools. Bucket Fill tool doesn't have icon like others tools have. I expected to see a little bucket like in MS Paint, Paint.Net, Photoshop etc.

![2019-03-05_213335](https://user-images.githubusercontent.com/1552169/53828502-e916c400-3f8e-11e9-8d7b-b39a008bea96.png)

**Comment by bojidar-bg** [comment]
CC @groud (https://github.com/godotengine/godot-design/pull/33)

**Comment by groud** [comment]
Fixed by  #25510
