### ISSUE TITLE
Particle 3D Draw Pass Error

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#26663]
**Godot version:**
Godot 3.1 beta 11 and 3.1 Daily Builds

**OS/device including version:**
Windows 10 x64

**Issue description:**
```
ERROR: get_draw_pass_mesh: Index p_pass=3 out of size (draw_passes.size()=1)
   At: scene/3d/particles.cpp:204
```

**Steps to reproduce:**
Create a 3D particle node. add a draw pass mesh to it. then Run the project.

**Minimal reproduction project:**
increasing the pass count to > 3 seems to "fix" the issue. must be something with the way pass counts are handle? N-1 instead of N=1?

**Comment by eon-s** [comment]
Happens on linux too, and it is only shown on the terminal output, not on the editor's error panel.

**Comment by clayjohn** [comment]
I think the issue is that ``get_mesh`` is being called when the draw_mesh property is being registered.

**Comment by akien-mga** [comment]
It can be reproduced in the `3d/navmesh` demo.
Open it, save the main scene, and this is printed to stdout:
```
ERROR: get_draw_pass_mesh: Index p_pass=1 out of size (draw_passes.size()=1)
   At: scene/3d/particles.cpp:204.
ERROR: get_draw_pass_mesh: Index p_pass=2 out of size (draw_passes.size()=1)
   At: scene/3d/particles.cpp:204.
ERROR: get_draw_pass_mesh: Index p_pass=3 out of size (draw_passes.size()=1)
   At: scene/3d/particles.cpp:204.
```

These errors started appearing in 3.1 alpha 2.

**Comment by akien-mga** [comment]
> I think the issue is that get_mesh is being called when the draw_mesh property is being registered.

Most likely yes. To be clearer: `get_draw_pass_mesh` is called when the `draw_pass_[123]` properties are registered in https://github.com/godotengine/godot/blob/0fec83bc9207cfff64d5b390c94ff554210bfa25/scene/3d/particles.cpp#L373-L376
