### ISSUE TITLE
Godot gives ambiguous error when improper script assigned to UI element in C#

### ISSUE THREAD

**Issue by nuke-makes-games** [godotengine/godot#26675]
**Godot version:** 

3.1 beta 5

**OS/device including version:** 

Win 10

**Issue description:** 

Godot throws strange error if a script deriving from the incorrect class is assigned to a UI element.

**Steps to reproduce:**

This is a very easy bug to reproduce.

1. Create a new project using C# (not sure if this is a C# specific bug but i am working in C#).
2. Create a new UI element as a child of a CanvasLayer (I used a HBoxContainer).
3. Assign a new script to this element. The newly generated script will derive from HBoxContainer in this case.
4. Create a new VBoxContainer and assign the script to it.
5. Run project in debug mode. Godot will print an ambiguous error then halt.

This isn't unexpected, but i think Godot should handle this case more gracefully. Godot should delete the node with the problematic script, or remove the script from the node and print a warning about its script deriving from the wrong class.

**Comment by akien-mga** [comment]
I'm not sure what you mean by "Godot hardlocks", but on my end on Linux it doesn't freeze, but raises an error in the debugger.

There error is pretty cryptic though:
![screenshot_20190306_104644](https://user-images.githubusercontent.com/4701338/53871744-244fdc00-3ffd-11e9-9211-280d824caf8f.png)

and in the Output panel/terminal:
```
ERROR: _load: No loader found for resource: res://
   At: core/io/resource_loader.cpp:285.
```

**Comment by akien-mga** [comment]
Doing the same with GDScript, a proper error is raised:
![screenshot_20190306_104824](https://user-images.githubusercontent.com/4701338/53871896-6711b400-3ffd-11e9-9ef0-341c4e15cc4d.png)

**Comment by nuke-makes-games** [comment]
> I'm not sure what you mean by "Godot hardlocks", but on my end on Linux it doesn't freeze, but raises an error in the debugger.
> 

Ah you're right, it does give me an error in the debugger but it's the same cryptic one you got.

**Comment by Bombfuse** [comment]
I've also gotten this error before, occurred when I attached an incorrect script to a node. ex. Attached a KinematicBody2D script to a StaticBody2D

**Comment by josh18** [comment]
Thanks, I didn't realise why it was crashing until I saw this.
