### ISSUE TITLE
[Regression] GridMap editor does not appear when selecting the node

### ISSUE THREAD

**Issue by Toshiwoz** [godotengine/godot#26671]
Searched similar issues, but I think none noticed this yet, as it came out with Beta 11, released today.

**Godot version:**
Godot 3.1 Beta11

**OS/device including version:**
Windows 10

**Issue description:**
When you select the GridMap node the editor should appear immediately, as it did in all other versions.
But now it doesn't.
![gridmap_editor_not_showing_up](https://user-images.githubusercontent.com/21297356/53840991-9676e100-3f69-11e9-804e-08401f186c0d.gif)

Opening another project I see also another issue, the preview seems to be broken:
![image](https://user-images.githubusercontent.com/21297356/53841081-da69e600-3f69-11e9-9d72-2ce37eb6ba4d.png)

I'm afraid that in the end @akien-mga was right about @reduz changes after feature freeze... XD

**Steps to reproduce:**
If you have a project with GridMap just open it and select the node, update from meshlibrary, you'll see that now if you click on the node again, the editor won't show up.
Even if, after clicking randomly in the properties it appeared again.

**Minimal reproduction project:**

You can use this project eventually:
[GridMap Astar.zip](https://github.com/godotengine/godot/files/2933361/GridMap.Astar.zip)
This one also have tiles preview broken.

**Comment by CowThing** [comment]
Same with a Tilemap
Click Tilemap -> Click on the tileset to edit it -> Tilemap editor is gone
If you close the tileset resource you can select a different node, then select the Tilemap again to reopen the Tilemap editor.

**Comment by akien-mga** [comment]
> I'm afraid that in the end @akien-mga was right about @reduz changes after feature freeze... XD

Yeah, I was mostly ironic and I think the new feature is super cool, but... there is indeed a reason why we have a feature freeze...

**Comment by Toshiwoz** [comment]
It's indeed a cool feature, removing unnecessary UI elements makes things easier.
I'll test it once next version is out.
