### ISSUE TITLE
[Regression] Unrelated tabs in bottom panel closes when switching away from nodes that have editors in there

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#26676]
**Godot version:**
 2940475

**Issue description:**
With @reduz's new commit that makes editors open automatically, it also makes them close automatically, which is not a problem by itself, except that if the editor is found in the bottom panel, it will close it down even if you're in a different tab from it:
![peek 2019-03-06 00-21](https://user-images.githubusercontent.com/30739239/53853904-4591d780-3fbf-11e9-95c3-6e5de38576a3.gif)

**Comment by reduz** [comment]
Fixed by #5f079e2

**Comment by YeldhamDev** [comment]
@reduz That didn't fix anything. Request to be reopened.

**Comment by akien-mga** [comment]
Even though it's a recent regression, it's not critical so moving to 3.2 milestone. A fix can be cherry-picked for 3.1.x.
