### ISSUE TITLE
[Regression] Mac OS: mousewheel not working in editor

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#26677]
**Godot version:**
3.1.beta.custom_build.2940475
3.1beta11.official

**OS/device including version:**
Mac OS 10.12.6

**Issue description:**
Mousewheel not working in editor: 2D/3D zoom, scrolling in filesystem/Inspector docks, etc. Working fine in beta 10 and earlier.

**Comment by cbscribe** [comment]
Initial testing: the problem seems to have appeared in a1e73dc

**Comment by nicktgn** [comment]
Can confirm. Mouse wheel doesn't work in 3.1 beta11 on OSX 10.14.3 (Mojave)

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by ViktorEvil** [comment]
have to click the mouse wheel in and scroll at the same time

**Comment by bruvzg** [comment]
Regression form a1e73dc, reverting `input->accumulate_input_event(ev);` line in the `os_osx.mm` fixes mouse wheel.
