### ISSUE TITLE
[Regression] AnimationPlayer doesn't redraw when new track is added

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#26670]
**Godot version:**
88355b2719fe7a103e6da82c1f58361190f2e1f1

**OS/device including version:**
Linux 4.20.13-arch1-1-ARCH

**Issue description:**

![peek 05-03-2019 18-39](https://user-images.githubusercontent.com/1387165/53839354-1440e980-3f76-11e9-99a0-35bd2d8342b5.gif)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by etalot** [comment]
And renaming nodes in Scene tree doesn't update in tracklist of animation. I switch to other animation and go back.
