### ISSUE TITLE
Mono: Build button does nothing if no solution exists

### ISSUE THREAD

**Issue by exts** [godotengine/godot#26681]
**Godot version:**
3.1 beta11

**OS/device including version:**
Windows 10

**Issue description:**
Hitting the build button does absolutely nothing if there is no solution available

**Expected**
Before there was a mono tab where I could create an empty solution and work directly from my IDE without creating scripts in the editor first. This needs to come back.

**Steps to reproduce:**
1. Create a new project
2. Hit build
3. Watch nothing happen

**Comment by akien-mga** [comment]
The option to create the solution was moved to the Project > Tools > Mono menu in #26333. @neikeq

**Comment by neikeq** [comment]
We were discussing this on discord. We decided the best is to make the build button generate the solution if it doesn't exist.
