### ISSUE TITLE
Light2D does not work across or inside CanvasLayers.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#26684]
**Godot version:**

b63c506

**OS/device including version:**

Win10 64-bit GeForce 9600 GT

**Issue description:**

When putting a Light2D or Node2D into another CanvasLayer, there is no longer a way to use Light2D nodes.  They only operate on the default canvas layer, no matter where they're located.

This currently makes these features impossible to use together.

`Here depicts a sprite getting both lights, and the other getting neither.  Though the lights are contained in their respective canvases.`
![image](https://user-images.githubusercontent.com/13004169/53863291-822af680-3ff2-11e9-90c5-a9d8df5fc383.png)

The problem exists in GLES2 and GLES3, in game and in editor.

**Steps to reproduce:**
Add a CanvasLayer and try out combinations of nodes and lights.  You will notice the lights disregard the CanvasLayer that is their parent.

**Minimal reproduction project:**

[3.1 Light2D CanvasLayer.zip](https://github.com/godotengine/godot/files/2934996/3.1.Light2D.CanvasLayer.zip)

**Comment by mrcdk** [comment]
You need to set the `Light2D` `Min Layer` and `Max Layer` ranges correctly.

**Comment by avencherus** [comment]
Thanks, my mistake.  Misunderstood these, didn't realize they were canvas layers.

**Comment by debris** [comment]
> You need to set the `Light2D` `Min Layer` and `Max Layer` ranges correctly.

this!
