### ISSUE TITLE
Basis is missing the IDENTITY and ortho constants

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#26682]
**Godot version:** 3.1 beta 10

**OS/device including version:** All

**Issue description:**

While [Vector3](https://docs.godotengine.org/en/latest/classes/class_vector3.html) has constants such as ONE and UP, [Basis](https://docs.godotengine.org/en/latest/classes/class_basis.html#class-basis) is missing the IDENTITY constant and the otho constants. These constants are already present in C# [here](https://github.com/godotengine/godot/blob/master/modules/mono/glue/Managed/Files/Basis.cs#L14), but not in GDScript. Related PR: https://github.com/godotengine/godot/pull/14704

I will fix this later if nobody else does, but it will have to wait for 3.2. It's very non-critical.

**Comment by neikeq** [comment]
Isn't `Basis()` the same as Identity?

**Comment by aaronfranke** [comment]
@neikeq Yes, you're right, it is! Though, there should still be an IDENTITY property to avoid confusion, just as Vector3 has ZERO. Also, I noticed that in C#, there is no parameterless Basis constructor.

**Comment by neikeq** [comment]
C# doesn't allow value types to have parameterless constructors (I think CLR does allow it though).
