### ISSUE TITLE
Imported Wav File Inspector Settings Don't Save

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#26685]
**Godot version:**
3.1 beta 10

**OS/device including version:**
Windows 10

**Issue description:**
You cannot save inspector settings on imported wav files.

![image](https://user-images.githubusercontent.com/21234930/53864942-a4952380-3fa2-11e9-97b7-dd66793c2b68.png)

**Steps to reproduce:**
Add a wav file to the project and let it auto-import.
Double click on it, and in the Inspector try changing any setting (like enabling stereo).
Click the save resource button.

Note that the resource can appear as saved, but if you reopen the project, the settings will reset.

**Comment by akien-mga** [comment]
I think this can be considered fixed now.

There's a clear warning that changes may be lost:
![Screenshot_20200622_133530](https://user-images.githubusercontent.com/4701338/85283215-43da7480-b48d-11ea-9d09-0cdc84904cac.png)

And saving the resource also has a more explicit error:
![Screenshot_20200622_133606](https://user-images.githubusercontent.com/4701338/85283260-548aea80-b48d-11ea-982f-b4820b132eea.png)
