### ISSUE TITLE
Grid Map node editing broken when transform is modified

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#2668]
How to reproduce:
Open 3D platformer demo stage.xml scene.
Rotate Grid Map node.
Try to paint-edit it.

What happens: although pre-existing elements are deleted correctly new onea are added in wrong place, looks like they are added based on global not local space.

**Comment by vnen** [comment]
It happens to me in current master tip: bd736e5.

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by b2800** [comment]
As of today using 3.1.1 this is not fixed.
![bug_gridmap](https://user-images.githubusercontent.com/3956968/56851282-8f3ad680-690d-11e9-9732-75ce280e37b4.png)
