### ISSUE TITLE
Difficult to work with Area2D/PhysicsBody2D in C# due to duplicated code in Godot Engine

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#26680]
**Godot version:**

3.0.6

**Issue description:**

I have a situation where a node could be an Area2D or a PhysicsBody2D. These two classes each individually implement collision_layer and collision_mask, even though they are the only children of their direct parent, CollisionLayer2D. This is fine for GDScript, but causes issues in a compiled language like C#.

Looking at the code for [Area2D](https://github.com/godotengine/godot/blob/master/scene/2d/area_2d.cpp) and [PhysicsBody2D](https://github.com/godotengine/godot/blob/master/scene/2d/physics_body_2d.cpp), it looks like the getters/setters are pretty much identical. Can this logic be refactored out to their shared parent? Removing duplicated code would also improve the maintainability of the engine.

**Comment by JarLowrey** [comment]
Maybe could even add another parent for RayCast2D to inherit from as well (who only has a mask).

**Comment by neikeq** [comment]
Removing the `topic:mono` label as this is an issue with the Godot API. What is proposed here is for `CollisionLayer2D` to declare `collision_layer` and `collision_mask`, instead of doing that in their two derived classes.
