### ISSUE TITLE
Godot 3.1 Sprite filter doesn't turns off

### ISSUE THREAD

**Issue by rakun99** [godotengine/godot#26690]
When I try to reimport sprites into 2D Pixel with the filter off, filter turns off only in the animation frames.
I tried this in 5, 9, 10, 11 versions of Godot.

![godot bug 3](https://user-images.githubusercontent.com/46073558/53872177-08f1ca80-4017-11e9-90ae-7b97abac3e98.JPG)

**Comment by breakmt** [comment]
Hm. You have another frame in your screenshot, not anim1.png one. You should check picture that filtered.

**Comment by rakun99** [comment]
...Already solved this problem. I just deleted animations and made new with already reimported sprites.

**Comment by groud** [comment]
So is the problem solved then ?

**Comment by rakun99** [comment]
> 
> 
> Hm. You have another frame in your screenshot, not anim1.png one. You should check picture that filtered.

Well, I tried to reimport all sprites. But it looks like in 3.1 you need at start reimport sprites, and only then make animations

> 
> 
> So is the problem solved then ?

Yes, solved.

**Comment by groud** [comment]
Closing then.
