### ISSUE TITLE
Polygon 2D - editing polygon point resets UVs

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#2669]
Currently if you create your UVs for Polygon2D and you decide that you need extra point in that polygon, adding it or removing resets WHOLE UV and you have to start all over again ;)

**Comment by n-pigeon** [comment]
UPDATE:
After playing a bit with polygon2D and UVs I figured out that my workflow was destructive and that only problem is when I move UV to compensate that my polygon was drawn in different area based on pivot... and editing said pivot after setting up correcly UVs corrects everything so it's ok and non-destructive.

So this isn't huge bug but if somebody figures out how to avoid that or fix would be nice ;)

**Comment by MarianoGnu** [comment]
Polygon2D will be reimplemented at some point to be directly edited from UV editor, and many options will be added to it:

-Ability to draw polygons from UV editor
-Support Inner vertices and Edges (for correct deformation)
-Support 2D Weight Painting
-Support 2D Bone Deformation Nodes
-Generation of Polygons from Sprites (there was a lib to integrate for this..), to reduce fragment load (mostly on mobile)
-Support Polygon2Ds on TileMap (great for isometric/hex with the above feature)

**Comment by n-pigeon** [comment]
Ah I wasn't aware of those plans. Closing then :)

**Comment by MarianoGnu** [comment]
no need to close, this is an actual issue, no matter if it's planned to be fixed :P
Whatever...

**Comment by n-pigeon** [comment]
ok better to leave it opened I guess :P

**Comment by romulox-x** [comment]
MarianoGnu, are those plans documented anywhere?  I didn't see them in any Google docs I have links to.  Those features all sound awesome.  I'd like to give them my wholehearted vote.

**Comment by MarianoGnu** [comment]
It's on the list of features to be implemented if Godot gets enought donations drom the comunity :)
https://docs.google.com/document/d/1sHZPlu1dU4bHkWFugBTW-m-3t15LYqF6YT46z-OJm18/edit?ts=562bc77b

**Comment by akien-mga** [comment]
What's the status on this in the current *master* branch or Godot 3.0?

**Comment by n-pigeon** [comment]
@akien-mga 
Still valid.

@MarianoGnu 
Any more info?

**Comment by MarianoGnu** [comment]
well, i was expecting this to be worked along with the Mesh2D Node, but looks like it's a completetely different node, so it needs some love

**Comment by Calinou** [comment]
@n-pigeon Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by n-pigeon** [comment]
@Calinou 
Hi! Sorry! I was absent for a long time but now I'm back and ready to roll :)

Yes I can still reproduce this.
