### ISSUE TITLE
Geometry.segment_intersects_circle works only one way

### ISSUE THREAD

**Issue by Schroedi** [godotengine/godot#26698]
**Godot version:**
3.1 beta: 2940475c716eab517ca52957acc8714f195d32cb

**OS/device including version:**
Arch Linux

**Issue description:**
Segment circle intersection check only works if the segment goes from the outside to the inside of the circle but not the other way around.

The function name and the documentation do not state this limitation:

> float segment_intersects_circle ( Vector2 segment_from, Vector2 segment_to, Vector2 circle_position, float circle_radius )
> 
> Given the 2d segment (segment_from, segment_to), returns the position on the segment (as a number between 0 and 1) at which the segment hits the circle that is located at position circle_position and has radius circle_radius. If the segment does not intersect the circle, -1 is returned (this is also the case if the line extending the segment would intersect the circle, but the segment does not).

I guess the original code is from [here](https://www.allegro.cc/forums/thread/595918/741584#target). When I implemented the code from the post the problem is solved but new problems arise (see # 2 in the sample output). 

Implementing the last check if the second part actually intersects is mostly correct. It fails for the second "in -> out" test most likely because of floating point comparison. The first test for "out -> in" might fail due to the same reason? I will open a pull request for this solution.

Output from sample project with three different builds of godot:
```
# 1 current godot 2940475c716eab517ca52957acc8714f195d32cb
complete intersectins
Expect 0.50, got 0.50 Ok
Expect 0.50, got -1.00 ERROR
cases directly on the circle
in -> out
Expect 0.00, got -1.00 ERROR
Expect 1.00, got -1.00 ERROR
out -> in
Expect 1.00, got -1.00 ERROR
Expect 0.00, got 0.00 Ok
no intersection
outside
Expect -1.00, got -1.00 Ok
inside
Expect -1.00, got -1.00 Ok

# 2 with code from https://www.allegro.cc/forums/thread/595918/741584#target
complete intersectins
Expect 0.50, got 0.50 Ok
Expect 0.50, got 0.50 Ok
cases directly on the circle
in -> out
Expect 0.00, got 0.00 Ok
Expect 1.00, got 1.00 Ok
out -> in
Expect 1.00, got 21.00 ERROR
Expect 0.00, got 0.00 Ok
no intersection
outside
Expect -1.00, got -1.00 Ok
inside
Expect -1.00, got 19.00 ERROR

# 3 also checking the second segment -> follows in pull request
complete intersectins
Expect 0.50, got 0.50 Ok
Expect 0.50, got 0.50 Ok
cases on the circle
in -> out
Expect 0.00, got 0.00 Ok
Expect 1.00, got -1.00 ERROR
out -> in
Expect 1.00, got -1.00 ERROR
Expect 0.00, got 0.00 Ok
no intersection
outside
Expect -1.00, got -1.00 Ok
inside
Expect -1.00, got -1.00 Ok
```

**Steps to reproduce:**
Minimal sample here, more test cases in the sample project.
```
var out = Vector2(1.1, 0)
var ins = Vector2(0.9, 0)
var out_in = Geometry.segment_intersects_circle(out, ins, Vector2(0, 0), 1)
var in_out = Geometry.segment_intersects_circle(ins, out, Vector2(0, 0), 1)
print("out_in ", out_in) # 0.5 correct
print("in_out ", in_out) # -1 (no intersection) incorrect
```

**Minimal reproduction project:**
[IntersectTest.zip](https://github.com/godotengine/godot/files/2935940/IntersectTest.zip)

**Comment by akien-mga** [comment]
Fixed by #26699.
