### ISSUE TITLE
Numpad in Mac OS X not working for 3D front view, side view, orthogonal view, etc.

### ISSUE THREAD

**Issue by sdhy** [godotengine/godot#26725]
Please search existing issues for potential duplicates before filing yours:
I did.  I searched numpad, keypad, kp.

**Godot version:**
Godot 3.1 Beta 11 Classical build.

**OS/device including version:**
macOS High Sierra Version 10.13.6
GPU: AMD Radeon HD 6770M 512MB

**Issue description:**
Note: I'm assuming "kp" means numpad.

In 3D view:
I can't use the numpad to switch to front view, top view, orthgonal/persperctive, etc.
Also, alt+kp3 goes to script view instead of bottom view.
(Alt+kp2 brings it back to 3D view).

Command+kp 3 shows three views.

You can type with the numpad in Godot.

**Steps to reproduce:**
Create any new project.
Go to 3D view (already open by default for me).
Press the numpad. Nothing happens, even if you left-clicked the 3D view screen.

**Minimal reproduction project:**
Make a new project using Godot 3.1 Beta 11 on Mac OS X.

**Comment by sdhy** [comment]
Uh, I typed a bunch of stuff when submitting it. Where did it all go???

**Comment by bruvzg** [comment]
Keyboard layout specific remapping messes up with Numpad keys and `KP3` is detected as `3`.

**Comment by sdhy** [comment]
It works now in RC1, thanks!
