### ISSUE TITLE
Editor crash unexpectly in background

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#26726]
**Godot version:**
3.1 34a29cb

**OS/device including version:**
Linux Mint Mate 19 HD 3000

**Issue description:**
When I opened system file manager(caja) from file system dock and opened font resource file .tres, then editor crash in backround with this errors:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x58000a6
  Serial number of failed request:  68155
  Current serial number in output stream:  68156
```

**Comment by qarmin** [comment]
Today I had same crash
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x3e004a8
  Serial number of failed request:  25583
  Current serial number in output stream:  25586
```

**Comment by Calinou** [comment]
@qarmin Can you reproduce this on [Godot 3.2 beta6](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-6)?

**Comment by qarmin** [comment]
This happens to me a little more that month ago, so yes I still can reproduce this(with 3.2 alpha version), but this happens very very very rarely.

**Comment by qarmin** [comment]
I tested right now project https://github.com/qarmin/The-worst-Godot-test-project.git to get backtrace from another issue, and after ~15min I got crash with this error
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0xa8053cc
  Serial number of failed request:  4384
  Current serial number in output stream:  4387
```

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by qarmin** [comment]
Not really, this bug occurred really rarely and since this time I not had similar crashes(still not sure if this is really fixed)
