### ISSUE TITLE
Tilemap shows seams when zoomed in

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#26734]
**Godot version:** 3.0.6

**OS/device including version:** Windows 8.1

**Issue description:**

When I set camera zoom to anything less than 1, my tilemaps have hard seams between them:

![image](https://user-images.githubusercontent.com/31222662/53928182-32324b00-4057-11e9-917c-7f4d131acef1.png)

Everything looks fine if it's zoomed to 1x though:

![image](https://user-images.githubusercontent.com/31222662/53928198-3bbbb300-4057-11e9-9a1d-42ce043c52cc.png)

**Steps to reproduce:**
- Create a project, set Pixel Snap on
- Import an image, create a tileset, create a tilemap and draw tiles
- Add a Camera2D, set zoom to something like `(0.3, 0.3)`
- Run the scene. Note the seams.

NB: I also tried with various combinations of pixel-snap on and off, and my texture with no flags, mipmapping only, filter only, mipmapping and filter both. Same behaviour.

**Minimal reproduction project:** available upon request

**Comment by Sslaxx** [comment]
Duplicate of #26730 by the sound of it.

**Comment by Zylann** [comment]
Your zoomed tilemap looks blurry. To me, it means you have tiles which you upscaled in a image editor to look "pixel-arty", and then imported to Godot with default settings. However, default settings have `filter` enabled, and that would be where the seams come from. Do you have an example project to verify this?

**Comment by nightblade9** [comment]
I don't have an MVP project. I have a large project. I will try to cut it down to a reasonable size and deliver it to you as an MVP.

You are correct about my sprites: they're originally 16x16, and scaled up to 64x64 without aliasing.

As I mentioned, I already tried disabling `filter` (and `mipmaps`, and `pixel snap`) in various combinations, all to no avail. 

@Sslaxx I don't think they're the same: in #26730, the seams appear at 1x zoom, and when you move. Mine appear only when zoomed in, and all the time - not just when moving.

**Comment by Zylann** [comment]
> As I mentioned, I already tried disabling filter (and mipmaps, and pixel snap) in various combinations, all to no avail.

Your screenshot is blurry, still. Are you sure you disabled that filter in import settings and clicked "Reimport"? (Modifying the texture directly won't have any effect).

**Comment by clayjohn** [comment]
@nightblade9 another option is to try this out in 3.1 and see if you can reproduce it. A lot has changed between 3.0.6 and now, so your issue may very well have been fixed. Hence why its so hard to reproduce. 

@Sslaxx This bug report relates to version 3.0.6 so I dont think a PR from last week is going to be the problem. 😄

**Comment by nightblade9** [comment]
@Zylann I didn't reimport the textures. I didn't know that's necessary. I'll try that. 

I'm not clear on what blurry textures has to do with the seams. Could you explain that a bit further?

**Comment by clayjohn** [comment]
@nightblade9 I was just able to reproduce your issue. But I fixed it by turning filter off and using pixel snap. 

Filter reads the color from four pixels with each lookup and blends them together. When using a single sprite the neighbouring pixel on the edge of the sprite gets clamped to the edge so you dont get borders, but on a spritesheet you read from an empty pixel on the sheet. This pixel gets blended with the one you want to read from resulting in a slightly darker pixel on all the borders.

**Comment by nightblade9** [comment]
Thanks @clayjohn @Zylann, reimporting the PNGs with "Filter" off fixed the issue for me. For reference, I didn't even notice the warning in the Godot UI.

![image](https://user-images.githubusercontent.com/31222662/54004049-4131ff80-4122-11e9-95ac-38a663c1b99d.png)
