### ISSUE TITLE
AudioBus oddities; saving problem? loading problem?

### ISSUE THREAD

**Issue by Jimmio92** [godotengine/godot#26736]
**Godot version:**
Godot v3.1.beta10.official

**OS/device including version:**
Intel Core i7 920 (Nehalem) @ 2.67GHz (4 core/8 thread)
12GB DDR3 @ 1066MHz (CPU limited)

**Issue description:**
I created a new AudioBusLayout using the Create button. I then modified this file, and it worked perfectly in editor. When I ran the scene however, it would revert, and audio would not come through the bus it was routed to and was just working in editor. I eventually did get it working, however since I could not locate a place to set the current AudioBusLayout, I have reverted to naming it default_bus_layout.tres as it expects so it actually works, but I'm not really sure what the heck happened during this weird issue as I just tried everything to get it working until it did. 

**Steps to reproduce:**
I wish I knew precisely what the problem is, but likely, it didn't save the named AudioBusLayout I was working with, or it didn't select that as the current AudioBusLayout automatically at scene run, but did fine in the editor, or something along these lines.

**Comment by Chaosus** [comment]
Provide an example project and/or video demonstration is also welcome if you want to someone to start working on this issue.

**Comment by akien-mga** [comment]
No answer to the above comment, so closing.
