### ISSUE TITLE
Mono Shutdown Crash when Dynamic Assemblies are used

### ISSUE THREAD

**Issue by shartte** [godotengine/godot#26731]
**Godot version:**
3.1 beta11
mono 5.18

**Issue description:**
Godot crashes when trying to unload a Mono assembly with the following error:

```
ERROR: mono_log_callback: Mono: FATAL ERROR, ABORTING! Logfile: C:\Users\...\AppData\Roaming/Godot/mono/mono_logs/1551911996.txt

   At: modules\mono\mono_gd\gd_mono_log.cpp:74
```

The mono log states:
```
Unloading image data-000001FA8C482250 [000001FA8C42A010]. (in domain Mono, info)
Unloading image Microsoft.GeneratedCode [000001FA8C82D380]. (in domain Mono, info)
Unloading image Microsoft.GeneratedCode [000001FA8C8A5030]. (in domain Mono, info)
* Assertion at ..\mono\metadata\image.c:2190, condition `!image->reflection_info_unregister_classes || mono_runtime_is_shutting_down ()' not met
 (in domain , error)
```

This issue seems to occur when my Mono code causes a dynamic assembly to be created at runtime. This may occur for anything related to Reflection.Emit, XmlSerializer, Expression Trees, and many others.

The relevant line in the mono source code:
https://github.com/mono/mono/blob/master/mono/metadata/image.c#L2242

This is the stacktrace when the crash occurs:
![image](https://user-images.githubusercontent.com/1261399/53919452-59464800-406a-11e9-83c2-ab8aa2c95b0b.png)

**Minimal reproduction project:**
[MonoShutdownCrash.zip](https://github.com/godotengine/godot/files/2938634/MonoShutdownCrash.zip)

**Comment by shartte** [comment]
I believe mono does not support unloading dynamic images (or so it seems) if they have been added to the root appdomain. I am still looking for a way to figure out if an image is actually dynamic, but have not found any public Mono APIs for this so far.

**Comment by shartte** [comment]
I have been looking into fixing this issue. My first attempt would have been to simply not create a GDMonoAssembly for dynamic images. But there's a warning in the code about crashing should an Exception from such an assembly be thrown. I was unable to reproduce this, but I am still going through the code and tracing every call to `GDMonoAssembly::get_class` to figure where this could blow up in my face.

**Comment by cart** [comment]
I also hit this issue because MessagePack does some dynamic assembly stuff. Itch.io detects this failure and shows scary error messages every time the game is closed:

![image](https://user-images.githubusercontent.com/2694663/54062941-21e8b000-41be-11e9-8815-040d8a08efa4.png)

I would definitely want to fix this issue before releasing my game.

**Comment by shartte** [comment]
My current dirty workaround is just not unloading dynamic assemblies when the script domain is unloaded.
This may leak some memory, but since scripts are already not loaded into the root domain, it might actually work out without leaks.

My fix was in GDMonoAssembly::unload():

```
	// Dynamic images cannot be closed and will be cleaned up
	// when the AppDomain is unloaded
	if (!mono_image_is_dynamic(image)) {
		mono_image_close(image);
	}
```
