### ISSUE TITLE
Problem about custom post processing

### ISSUE THREAD

**Issue by bladesero** [godotengine/godot#26747]
**Godot version:
3.06stable**

**OS/device including version:
Intel core i7-4710HQ @ 2.50GHz
12GB DDR3 @ 1066MHz**

**Issue description:
I use fullscreen quad mesh with a spatial shader to make FXAA,there are two problems:
1.SCREEN_TEXTURE will automatically exclude transparent material
2.because spatial shader can't use the SCREEN_PIXEL_SIZE, instead I use the window size to fill a vec2 uniform to use, but this kind of FXAA is horrible compared with the version I write in unity3D
![issue](https://user-images.githubusercontent.com/18096279/53955810-ea71f900-4114-11e9-989b-c6c50f781c34.png)
**

**Steps to reproduce:use the shader below**

**Minimal reproduction project:
[FXAA.txt](https://github.com/godotengine/godot/files/2941131/FXAA.txt)
**

**Comment by Calinou** [comment]
@cart has managed to port an high-quality FXAA implementation to the Godot shader language (compatible with both GLES2 and GLES3 renderers): https://gist.github.com/cart/7d2da58eb28c75c0952787f29f3e562f

Is this still considered a bug?

**Comment by clayjohn** [comment]
I agree with Calinou. I don't think there should be a bug report for this. It isn't a big with the engine, it's a bug with a users implementation on FXAA
