### ISSUE TITLE
to_lower() method bug in Russian (cyrillic)

### ISSUE THREAD

**Issue by exe2k** [godotengine/godot#26744]
**Godot version:**
3.1 beta 11

**OS/device including version:**
Windows 10 x64 intel i5 10gb RAM GF 660 GTX 

**Issue description:**
`to_lower()` doesn't work for russian as it expected. It left almost half of letters in upper case. 

**Steps to reproduce:**
`	var caps  = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"
	print(caps.to_lower())
`

the result will be: 

абвгде**Ё**жзийклмнопрсту**ФХЦЧШЩЪЫЬЭЮЯ**
as you can see the letter "Ё" and from "Ф" to "Я" are yet capitalized.

**Comment by akien-mga** [comment]
The relevant code is in https://github.com/godotengine/godot/blob/master/core/ucaps.h
Might need extra entries for the Cyrillic letters which don't match a Latin letter.
