### ISSUE TITLE
visualscript InputEventMouseMotion_relative error in editor

### ISSUE THREAD

**Issue by TrickMe** [godotengine/godot#26740]
Godot beta11

LinuxMint 19.1

When executed from the editor, VisualScript nodes

get Instance InputEventMouseMotion_relative
get Instance InputEventMouseMotion_speed
get Instance InputEventScreenDrag_relative
get Instance InputEventScreenDrag_speed

return the error message "Invalid index property name." if a button is pressed (mouse or keyboard). Works fine if executed from Project Manager or an exported project.

[InputEvent rep.zip](https://github.com/godotengine/godot/files/2939620/InputEvent.rep.zip)

**Comment by sami8github** [comment]
Confirmed.
Please tell me how did you create this node:
![image](https://user-images.githubusercontent.com/41632592/53951011-6cd2cc80-40c5-11e9-816c-bbd3c26b4359.png)

a quick turn around:
![image](https://user-images.githubusercontent.com/41632592/53950927-38f7a700-40c5-11e9-9562-d3e90eb3366f.png)

**Comment by TrickMe** [comment]
> Please tell me how did you create this node:

I dragged a "get" node in the script and set it to:

Set Mode = Instance
Base Type = InputEventMouseMotion
Property = relative

**Comment by sami8github** [comment]
Thank you very much bro, I didn't know that

**Comment by t-karcher** [comment]
@TrickMe : Can this issue be closed? The changes proposed above (only evaluate the "relative" property after making sure it's indeed an InputEventMouseMotion) should fix your problem, right?
