### ISSUE TITLE
TextureLayered.new() returns null 

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#26750]
**Godot version:**
3.1 beta 11

**OS/device including version:**
windows10

**Issue description:**
TextureLayered.new() returns null value.

**Steps to reproduce:**

var lay = TextureLayered.new()

**Minimal reproduction project:**
var lay = TextureLayered.new()

**Comment by Zylann** [comment]
`TextureLayered` is a base class, I think it's not meant to be instanced. You should instance its derived classes instead, either `Texture3D` or `TextureArray`.

**Comment by burstina** [comment]
Yes, documentation is still very skeletal and I'm trying to understand more about this class.
Thanks for yout tip, I just found a message in debugger windows about TextureLayered not being instantiable. 
Perhaps I'm wrong, but I'd expect a blocking error for something like that.
