### ISSUE TITLE
Android Shader short multiplication of Vector and Matrix crashes the app

### ISSUE THREAD

**Issue by PelegMedia** [godotengine/godot#26759]
**Godot version:**
3.1 Beta 10 and Beta 11

**OS/device including version:**
Nexus 9, Android 5.0.1, 
GLES3 and GLES2 (Nvidia Tagra)

**Issue description:**
I have a Canvas_Item Shader, overwriting the Fragment function.
I got several crashes and after long debug sessions I found out that if I have a vector and a matrix, the short multiplication format crashes the app while the regular works OK.
Both of then do work on Windows, while working and running from the editor.

Short one:
```
vec2 V = vec2(....);
mat2 M = mat2(.....);

```
This one failed:
`   V *= M;`

This one works OK:
`   V = V * M;`

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Is this still reproducible in the current 3.2 builds?

**Comment by akien-mga** [comment]
Tested on two devices and it seems to work fine for me:
- Xiaomi Pocophone F1, Android 9, GLES3
- Samsung Galaxy S3, Android 7.1.2, GLES2

I'll assume it was fixed in 3.2. Please comment if you can still reproduce the issue, and attach a project that triggers it.
