### ISSUE TITLE
KinematicBody2D yields unexpected outcomes when passing negated y value with zero as x component

### ISSUE THREAD

**Issue by MrDudeIII** [godotengine/godot#26768]
**Godot version:**

e930fb9

**OS/device including version:**

Windows 8.1

**Issue description:**

KinematicBody2D.move_and_slide() breaks when I pass it a negated Vector2(0, positive_number) value. Recoil from shooting should move the character upwards when shooting downwards, but instead it moves the character downwards much more quickly than expected. All other 7 directions function as intended (including downwards diagonals).
![moveandslidebug](https://user-images.githubusercontent.com/32783268/53981570-d1e7eb80-40e0-11e9-8ca2-672c72a27806.gif)

**Minimal reproduction project:**

The movement/recoil code is in character.gd.

Charge/shoot with space, move/change directions with the arrow keys.

[MoveAndSlideBugTestProject.zip](https://github.com/godotengine/godot/files/2942834/MoveAndSlideBugTestProject.zip)

**Comment by akien-mga** [comment]
A more minimal example would be good, as it's hard to assess if the issue is with `move_and_slide` or your AnimationTree here (commenting out the last two lines of `character.gd` make that "downwards recoil" issue the same for all direction).

**Comment by MrDudeIII** [comment]
I was having an impossible time isolating the issue. all the numbers were coming back correct but the character was moving in the wrong direction. The peeps over at Godot Engine discord figured it out though. Turns out it was a silly mistake I made with colliders (forgot to change the bullet's collider layer). Thanks!
