### ISSUE TITLE
A LOT of warnings when compiling

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#26769]
**Godot version:**
3.1 beta 11

**OS/device including version:**
Mac OSX Mojave

**Issue description:**
```
./core/math/random_pcg.h:40:24: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
        uint64_t current_seed = DEFAULT_SEED; // seed with this to get the same state
```

I'm getting a lot (and I mean a LOT) of warnings when compiling. There are all equal to the one above.. almost sure it didn't happen 10 hours ago (but could be wrong) just to check

**Comment by clayjohn** [comment]
Must be a result of https://github.com/godotengine/godot/pull/26737

**Comment by akien-mga** [comment]
Weird that the CI didn't catch that one.

**Comment by MidZik** [comment]
Sorry about that. Is there a reason I wasn't seeing these warnings? Or a way to enable them on my end?

**Comment by akien-mga** [comment]
I think it might be because modern compilers assume that code is C++11 if nothing is specified, while older ones assume C++03 and thus trigger this warning.

We'll soon actually move to C++11 officially, so this one should stop being an annoyance :)
