### ISSUE TITLE
[Regression] Viewport transparent=true not working on GLES2

### ISSUE THREAD

**Issue by TIBI4** [godotengine/godot#26779]
**Godot version:**
Beta 11

**OS/device including version:**
Nvidia GTX960M Windows 10

**Issue description:**
- Viewport background should be transparent when transparent=true, but this is not working and instead of getting a transparent background, the viewport gets a black background.
- Working as expected on Android and HTML5.
- This happened after updating my Godot's version (from beta 5 to beta 11).

**Steps to reproduce:**
Create a viewport and use it as a Viewport Texture

_This is the goal. (And what I get in beta 5)_
![qf2fkyobh5](https://user-images.githubusercontent.com/25259582/53997016-5ce4d800-4119-11e9-9c2b-6f73edac01cd.gif)

_This is what I get. (When updating to beta 11)_
![mcz5dqalkf](https://user-images.githubusercontent.com/25259582/53997028-640be600-4119-11e9-9a5b-2b8df2f7d8b3.gif)

**Comment by akien-mga** [comment]
Are you using GLES2 or GLES3? Can you try intermediate betas and find which one broke the feature for you?

**Comment by TIBI4** [comment]
> Are you using GLES2 or GLES3? Can you try intermediate betas and find which one broke the feature for you?
> 
> Could you also provide an example project that reproduces the issue?

- Im using GLES2.
- Unfortunately I'm far from my computer until the next week. But I will try intermediate betas as soon as possible.

**Comment by akien-mga** [comment]
Thanks, I could confirm the bug in GLES2. It works fine in GLES3.

MRP: [viewport_transparent_gles2.zip](https://github.com/godotengine/godot/files/2948397/viewport_transparent_gles2.zip)

I'll test past betas to find where the regression happenned.

**Comment by akien-mga** [comment]
It works in 3.1 beta 6, fails in 3.1 beta 7. So the regression comes from one of those commits: https://github.com/godotengine/godot/compare/30a4723d9c974daaaf6b8af581b2d66c6b31b119...e30ce69cb44cd31933dc81700d16db2c80727015

**Comment by akien-mga** [comment]
Most likely a regression from 5784caae73. @reduz

**Comment by akien-mga** [comment]
@clayjohn Maybe that's something you'd be interested in looking at? @reduz will be quite busy this weekend, and it would be nice to have a fix asap for the next RC.

I had a quick look at 5784caa but the code changed quite a bit since then in the master branch, so not sure how to fix it. In particular, there's almost no use of `glColorMask` now.

**Comment by clayjohn** [comment]
Sure thing! Looking into it now.

**Comment by TIBI4** [comment]
I can confirm that it's working again on RC3.

**Comment by nerdnils** [comment]
I am havin this bug in 3.2.3 on GLES 3

**Comment by Calinou** [comment]
@nerdnils Are you referring to https://github.com/godotengine/godot/issues/43559? If not, please open a new issue.
