### ISSUE TITLE
Type hint in a for loop

### ISSUE THREAD

**Issue by Schroedi** [godotengine/godot#26783]
**Godot version:**
69761816381f11536980441265345ba055ad1c26

**Issue description:**
Type hinting in for loops is currently not supported.

**Steps to reproduce:**
```
var arr = [Vector2()]
for a in arr:
	a.  # no completion

for a:Vector2 in arr:  # error: 'in' expected afteridentifier
	a.normalized()
```

**Expected Behaviour:**
The second example should give no error and enable auto completion as well as error checking within the loop.

**Comment by ThakeeNathees** [comment]
what would be the expected behavior for 
```
var arr = [Vector2(), "some string"]
for a:Vector2 in arr:
	a.normalized()
```

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/632, as feature proposals are now tracked in the Godot proposals repository.

@ThakeeNathees I'd suggest posting your comment on the proposal above so it gets more visibility.
