### ISSUE TITLE
SampleLibrary page prevents tab navigation

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#2678]
#_(Not an important issue, but should be mentioned regardless)_

**How to replicate the problem:**
1. Start New Project (_optional_)
2. Create Node type "SamplePlayer".
3. In the Inspector, under "Config"->"Samples", change from _<null>_ to _New SampleLibrary_.
4. Click it again and select "Edit".

This will overlap your current page with the sample library page.
You are unable to leave this page by clicking on the tabs; 2D, 3D, Script or Help - so you are forced to finish whatever you are doing. A way I have found to leave this page (when not doing anything) it is by clicking on any node in the Scene window. 

Worth mentioning there is no indication of where you are (not counting inside the Inspector window). No title saying "Sample Library" or some other information to tell the user what "page" is he on. (Granted; most people usually know where they are and how they got there, but let us pretend the user is a dummy and create a user friendly program!)  :)

A suggestion to remedy this might be to make it _appear in a new window_ instead of replacing whatever page/tab you are currently in.

**Comment by MarianoGnu** [comment]
this is not actually an issue, the sample library editor is not a tab, it's drawn over the tab mode, to leave the editor you should click on any node of scene_tree or the left-arrow on inspector (back to SamplePlayer node)

**Comment by Tybobobo** [comment]
I know this is not important at all, but it is not natural having to select a node or click in inspector in order to close it. 
A simple X in the upper right corner, or even a "close" button near the bottom would suffice as a quick fix. People should **not** have to look for a way to close the page/overlay, as that should be a natural as opening a door handle. 

If I get time (from college), I would love to see if I can familiarize myself enough to work on this myself as a little side project :)

**Comment by MarianoGnu** [comment]
Yeah... current dialog popup implementation makes it close if you click outside of the dialog, so you can't change values on the inspector; and adding a close button to the sample panel would be confusing also, because it's already filled with unused controls... Theme editor needs to be completely moved to a separate window, including inspector...

**Comment by reduz** [comment]
There are a few editors that work like this. I know it kind of sucks, but i'm unsure about how they should behave.  Maybe a popup window instead of something that replaces the tab?

**Comment by Tybobobo** [comment]
This seem to be working well now. This now opens a new area on the bottom of the viewport that allows you to add or edit samples, and in order to "leave" the window, you just go "back" from the inspector (left arrow) or select a different node. :)

If there are no objections, I believe this issue can be closed.

**Comment by MarianoGnu** [comment]
Sure thing
