### ISSUE TITLE
Off by one error on breakpoints in combination with for loops and comments

### ISSUE THREAD

**Issue by syskrank** [godotengine/godot#26789]
**Godot version:**

Godot 3.1 b376273, debug & release_debug builds

**OS/device including version:**
Linux Mint 19 x64

**Issue description:**
When outputting messages via `print()` in nested `for` cycles, not all lines are being outputted if a breakpoint is set AFTER the corresponding output code:

![image](https://user-images.githubusercontent.com/11526664/54030210-e5b45000-41bb-11e9-98cf-d98d6f7712c6.png)

The code above with breakpoint set outputs only 5 lines of messages instead of expected 8. So it seems that the second cycle didn't finish it's whole set of iterations.

This is valid for engine output pane and command line terminal as well.
And such behavior is quite misleading and could have some deeper roots in debugger/gdscirp behavior (???).

Interesting detail, though, is that if one puts additional `print` statement before the breakpoint, all prior calls became valid, including the new one. ( See the commented `print()` before the `pass`)

Also, not only the breakpoints set on `pass` are displaying this behavior, but the ones in more complex code examples do as well.

**Steps to reproduce:**
Write two nested cycles with `print` output in each.
Set a breakpoint after the second cycle.
Run project in the debug mode.
See that not all of the expected output is present in corresponding editor pane and in the command line terminal.

**Minimal reproduction project:**
[godot_double_cycle.zip](https://github.com/godotengine/godot/files/2945894/godot_double_cycle.zip)

**Comment by bojidar-bg** [comment]
Doesn't the breakpoint just jump to the previous statement, which accidentally happens to be the second cycle's `print`?

**Comment by syskrank** [comment]
Seems this is like what exactly happens - breakpoint is being set for previous line which traps the debugger within the cycle.

**Comment by syskrank** [comment]
I've rechecked this for more complex example and it seems like the assumption is correct - debugger jumps to the prior statements.

**Comment by dramdrum** [comment]
So basically "pass" is not actually an instruction, so you can't put a breakpoint on it?

**Comment by syskrank** [comment]
No, this issue is not connected with the `pass` instruction. You can add some meaningful code to the example project attached and see it for yourself.
Actually, I've checked that once more by adding this code instead of `pass` and setting a breakpoint on the first line of this "appendix". The behaviour is the same.
```gdscript
#... code sample from the above
	var arr = [] # here we're setting the breakpoint
	var color = Color("#333333")
	arr.append(color)
```

**Comment by akien-mga** [comment]
Reproduce with this:
```gdscript
	print("start")
	for i in range(3):
		print(i)
	#print("end")
	#blabla more comment lines don't impact the bug
	print("post end")   # breakpoint here
```

It seems like the comment block introduces an off-by-one error for the breakpoint, which then ends up on `print(i)`. It happens at least with `for` and `while` loops, but apparently not with `if` blocks.
