### ISSUE TITLE
Blocky artifacts appears when a transparent mesh has overlapping regions

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#26785]
**Godot version:**
`master` / 8b231b96

**OS/device including version:**
Manjaro Linux 18.0.3 / Nvidia GTX 970

**Issue description:**
I have a hair mesh that contains overlapping plane regions. But when I setup a material, there appear blocky patterns on certain areas as shown in the below screenshot:

![artifacts](https://user-images.githubusercontent.com/2367032/54023633-c972dc00-41d8-11e9-9e2e-4858bdd5d29d.png)

The material has culling disabled, and depth draw mode is set to _'opaque pre-pass'_.

In case it's something difficult to fix, any tricks or workarounds to mitigate the problem would be appreciated also.

**Comment by akien-mga** [comment]
Can you still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by clayjohn** [comment]
To add to this, the only issue I can see is a small amount of z-fighting.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.

**Comment by Calinou** [comment]
Note that for hair rendering, you can use AlphaHash in 4.0: https://github.com/godotengine/godot/pull/40364
