### ISSUE TITLE
3d Camera Fail when rotating RigidBody

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26799]
**Godot version:**
3.1 b11

**OS/device including version:**
Windows 10 x64

**Issue description:**

As you can see in the video below, when I resize and rotate a 3d Rigid Body, the Camera is not showing the correct perspective.
I've attached the test project.

- https://drive.google.com/open?id=1lyQTDPh6ZqC9sXzZRUJHtoTSBWsWCH98

- [camera fail.zip](https://github.com/godotengine/godot/files/2947136/camera.fail.zip)

**Comment by rogeriodec** [comment]
Later I discovered that the problem here is the same as I reported at https://github.com/godotengine/godot/issues/26890, ie the parent is a RigidBody and this generates the bug.
By switching parent to KinematicBody, the problem is solved.

**Comment by clayjohn** [comment]
If it is a duplicate, can we close this one?
