### ISSUE TITLE
RayShape2D not colliding with StaticBody2D.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#26798]
**Godot version:**

60d910b

**OS/device including version:**

Win10 64-bit

**Issue description:**

Was trying to use a RayShape2D in a simple setup, and in its default setup it isn't colliding.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/54048393-55d5cc80-41e2-11e9-9c95-4d6f4b093db5.gif)

**Comment by akien-mga** [comment]
> Uploading 3.1 RayCast2D Issue.zip…

Upload didn't finish :)

**Comment by avencherus** [comment]
Seems sleep came first.  😴

Should be up now.  X)

**Comment by avencherus** [comment]
Can no longer reproduce this.  Will re-open if I run into again.
