### ISSUE TITLE
Allow users to override string casting for Objects and add an Object.to_string() method.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#26796]
I have tried every which way I can to find any existing reference to this Issue, but I can't find an Issue or PR that mentions it, despite believing I'd seen one before. If this is a duplicate, just let me know and close it. Otherwise...

**Issue description:**
It is extremely inconvenient that users cannot customize the way in which the engine stringifies Objects. Many people see `print(obj)` and then wonder, "Okay, how can I control what that prints from my Object," like many other general-purpose languages do. And while it's true that GDScript isn't a general-purpose language, the fact that this possibility isn't available is still frustrating, especially when it isn't just about printing, but perhaps logging data to our own custom logging solutions using `var2str()` with any arbitrary Variant.

The current alternative available is just to write our own utility script class:

    extends Reference
    class_name Util
    static func to_string(p_var):
        if typeof(p_var) == TYPE_OBJECT and p_var.has_method("to_string"):
            return p_var.to_string():
        return var2str(p_var)

But this then makes any code shared between projects reliant on this simple Util method. If multiple people had to do this for projects, and then also shared plugins or assets that had debug information using something like this, we'd end up with competing codebases in the global namespace when all of this stuff should really be built into the engine core itself to begin with.

In my opinion, `var2str(var)` should really do what `Util.to_string(var)` is doing already. We should also be able to access this same content with both `str(obj)` and `obj.to_string()` (for other languages' sake, even if `to_string()` is not necessarily essential for GDScript with the `str()` global method).

WDYT?

**Comment by LeonardMeagher2** [comment]
I see `var2str` as a marshalling method, not only a way to print an object
I think things like `print` or `str` should look for a `to_string()` method and script should be able to override that method. I don't think the functionality of `var2str` should change since `str2var` is meant to convert the output back into a variant. 

It seems like here
https://github.com/godotengine/godot/blob/92d317a0b08edfa42e5e2b79196b32a33d5209e8/core/variant.cpp#L1577
Is where we could get the script, see if it has a method of `to_string` and call it if it does.

**Comment by LeonardMeagher2** [comment]
I will give this a go and add this to `Object::_bind_methods`
`BIND_VMETHOD(MethodInfo(Variant::STRING, "_to_string"));`

**Comment by girng** [comment]
does `print(str(obj))` work?

**Comment by LeonardMeagher2** [comment]
@girng 
`print(obj)` will work, the modification is to an internal method of converting a variant to a string.

**Comment by LeonardMeagher2** [comment]
This new PR I've made is better than the previous one. `str(obj)` calls `obj.to_string()`, and to_string can be overridden. For languages like C# that already have `Object.ToString` they can implement how the the Godot Object turns into a string pretty easily.

you can still do `print(obj)` and it'll call your `to_string()` function also

**Comment by akien-mga** [comment]
Fixed by #27886.
