### ISSUE TITLE
Return the focus to the editor when the play scene is closed

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26795]
**Godot version:**
3.1 b11

**OS/device including version:**
Windows 10 x64

**Issue description:**
As described [here](https://godotengine.org/qa/41775/how-to-return-the-focus-to-editor-when-the-played-scene-closed), every time I press F5 (or F6) to play a scene and I close it, the focus is not automatically returned to the editor.
So I have to manually click on the editor (so the last cursor position is lost).
Also, an ESC key to close this window would be very convenient. 
I made an AutoHotkey script for that but would be better to have this behavior internally implemented.

**Comment by CrimsonPiZza** [comment]
I think I used to make something similar. I tackled the problem by looping the main app with a code that check whether the children app is running and proceed to focus the children app or if it not, then it would return the control to the main app. I'm quite new to github as well as coding, so cut me some slack. 😅

**Comment by rogeriodec** [comment]
You can get the workaround I did with Autohotkey [here](https://godotengine.org/qa/41775/how-to-return-the-focus-to-editor-when-the-played-scene-closed?show=41807#a41807), also with the ideas with `F5`, `F6 `and `ESC `keys.
I'm using it a lot to work with Godot.

**Comment by CrimsonPiZza** [comment]
Thank you so much it works like a charm.... But like you've mentioned to have this behavior internally implemented would be nice.. Is there such way to do so with the original source code?

**Comment by lupoDharkael** [comment]
The editor used to work like the behaviour you describe but it was problematic when the game crashed because of typing unwanted characters in the scripts while pressing game keys.
See: #6530

Maybe we should identify when the game crashed or closed normally and handle the focus accordingly.

**Comment by KoBeWi** [comment]
The editor still works like this (I recall there was a period when it wasn't, but it was likely a bug).
The other issue is tracked by #21812
Closing.
