### ISSUE TITLE
Enable runtime access and manual editing of Custom Types.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#26802]
**Issue description:**
The current main differences between Custom Types and Script Classes are as follows:

- Custom Types are loaded in dynamically via an EditorPlugin method. Their information is stored only in the Editor, and only in RAM.
    - This means that Custom Types' names are only accessible in the editor context, and one must define a plugin in order to even use them.
- Script Classes are extracted from script files and serialized to the ProjectSettings' `project.godot` file.
    - This means that Script Classes' names can be loaded into the engine at startup from the serialized data, enabling runtime access.

So, as far as I can tell, the only thing stopping Custom Types from *also* being runtime accessible is the matter of where we are storing their information. Why not just change where we keep the data?

**Steps to Implement**
1. Refactor Custom Types so that they are indexed by name, not by engine base type. This makes it easier to iterate over inheritance hierarchies and look up the type by its name directly.
2. Create a tab in the ProjectSettings editor specifically for custom types that works more or less like the autoloads tab (creates a global variable in GDScript for each record, sticks the data into the ProjectSettings, etc.).
3. The EditorPlugin method is edited so that all it does is update the serialized data in ProjectSettings rather than storing the data anywhere else.
4. (Optional) Enable users to register scene resources as well as scripts as "custom types"
5. (Optional) Create context menu shortcuts in the Scene dock and FileSystem dock to select a scripted-node/Script or scene-root-node/PackedScene and do a "Promote to Custom Script/Scene" option which opens a little popup to type out a name and then auto-adds the record to the ProjectSettings data.

What do you guys think?

**Comment by samdze** [comment]
It's always nice to see your dedication on this part of the engine, Will.
My perspective is explained here: https://github.com/godotengine/godot/issues/19178#issuecomment-471099148
In short, if I were to choose I would not go your way, I would aim to completely remove the old Custom Types system.

**Comment by willnationsdev** [comment]
@samdze Well, if storing the custom type information happens in the `project.godot` file or, in your version, what would be a `plugin.godot` file, the data is still about "storing the information inside the ProjectSettings" regardless. And that's exactly what this Issue is proposing, so the idea I've presented above would be something that can work within even the design you've proposed. And the `Custom Types` tab I've specified here is something that would give a complete overview of the user-defined types in the current project (both custom types and script classes - though script classes would need to be fixed, uneditable records in the table), regardless of whether the project exports itself as a game or plugin. This list would necessarily include a list of any types defined by installed and activated plugins.

So...I don't see any way in which your proposal (if it were approved) would conflict with my own.

**Comment by samdze** [comment]
Yeah your proposal could still work.
My point was to keep things consistent and clean with only a single solution.
I can't think of many use cases in which the old `add_custom_type()` system would still be necessary, what do you think they could be?

**Comment by willnationsdev** [comment]
If someone wanted to programmatically register typenames from their plugin for whatever reason?

**Comment by samdze** [comment]
An EditorPlugin can create new types with `add_custom_type()` only on editor time, right?
So, it should be the same thing as creating a script file with "class_name", saving it in the file system and letting Godot import it as a plugin resource.
Actually I would be ok with this (slightly modified) API as long as all it would do is programmatically hide/re-show some of the imported `class_name` scripts from the perspective of the containing project, even if real use cases for this feature are limited.
The remainig thing not covered would be programmatically modify names and icons for registered types, you should edit the scripts resources themselves to be able to change those, as overriding them in the project.godot sounds not lilke a good idea to me.

**Comment by avencherus** [comment]
> I can't think of many use cases in which the old `add_custom_type()` system would still be necessary, what do you think they could be?

I have one that is conditional as of 3.1.  The current `class_name` feature is not 100% stable or flexible enough in its current state for many things I'm doing, and more so in tool scripts.  Cycle errors where no cycles exist etc.  When they do exist, they still create issues with doing comparisons of types when the reference itself cannot be included because it would be considered cyclic.

Another use case related concern, is that class_name also doesn't yet have any option to exclude the class from the "Add Node" window in the editor.  When you make dozens or hundreds of Node extended classes that aren't intended to be used on their own, this quickly pollutes that list.

It does seem that much work is still ahead of it, so in a future version (one that I won't be switching to for my current projects) will have refactoring to GDScript that will sharpen it up.

For the sake of stability, I'm forced to sticking to the more verbose original way of doing this.  I use editor custom nodes for easy access in the "Add Node" menu, and `const MyClass = preload()` for script references.

That said, it probably doesn't need any additional work, because it should become obsolete when `class_name` reaches maturity.

**Comment by willnationsdev** [comment]
Well, I believe vnen intends to fix the cyclic errors bit in 3.2 (or, I had thought that was the plan - not actually sure).

Regardless, this Issue is more about determining the viability of allowing custom types to be runtime accessible, discussing whether that is a good/bad idea, and whether, if a good idea, the suggested implementation is a good idea.

**Comment by avencherus** [comment]
Good idea?  Yes.
Good implementation?  Sounds about right.
Worth doing?  Probably too late to see any benefits, given the future version it could possibly be committed into.  `class_name` is likely to replace it by then.

**Comment by willnationsdev** [comment]
@avencherus Well, something I would like to see is allowing scenes also be registered as "custom types", similar to #21187. 

One could even extrapolate it out so that any resource could be manually assigned a name, but the potential problem with that is how users could start feeling like all they want to do is give names to their resources, meaning they'd pollute the global namespace and eventually feel like they want an automated solution for all the manual work of registering them (not ideal).

As you say, script classes are probably going to usurp Custom Types, but you can't exactly use script classes to bind a scene to a script, so I'm trying to find an alternative (registering scenes to scripts, registering scenes as custom types, registering scenes with a name under some new paradigm, etc.).

**Comment by willnationsdev** [comment]
Based on the discussion in #21187, there is no need to continue working on this. Anything that can assist both the editor (can't be a module, must be in core or editor) and runtime (can't be in editor) would have to be in core, and any and all core changes that would enable a user-defined type system will not be approved by reduz. (This includes making custom types or scenes in any way accessible by name at runtime from a centralized engine core system)
