### ISSUE TITLE
3D viewport converted to sRGB despite keep_3d_linear in some cases.

### ISSUE THREAD

**Issue by toasteater** [godotengine/godot#26817]
**Godot version:** e930fb9 (3.1 beta11). Still present on 2940475 (master at the time of writing). GLES3 backend.

**OS/device including version:** Recent Arch Linux. GTX 970 w/ binary driver 418.43-4

**Issue description:** Viewport content converted to sRGB despite `keep_3d_linear`, when `transparent_bg` is on.

Bug is apparently caused by `RasterizerSceneGLES3::_post_process` disregarding `RENDER_TARGET_KEEP_3D_LINEAR` when `RENDER_TARGET_TRANSPARENT` is on or the render target is too small. Patch to illustrate the problem: https://github.com/godotengine/godot/compare/master...toasteater:fix/keep-linear

The patch fixes the bug in question for my use case, but as I'm not familiar with Godot's code base, I'm not sure if the change has any ramifications I'm not aware of, or if there is a better way to fix this problem. I would make a pull request if it's ok.

**Steps to reproduce:**
* Create GLES3 project.
* Add Node2D -> ViewportContainer -> Viewport
* Put something in Viewport. Turn on `keep_3d_linear` and `transparent_bg` for Viewport.

Expected: 3D content is in linear space.
Actual: 3D content converted to sRGB.

**Minimal reproduction project:** [keep-linear.zip](https://github.com/godotengine/godot/files/2948031/keep-linear.zip)

- - -

EDIT: Clarified graphics backend and reproduction.

**Comment by akien-mga** [comment]
That patch looks good to me, could you make a PR?

**Comment by toasteater** [comment]
@akien-mga Sure thing!
