### ISSUE TITLE
Changes to atlas region for TextureRect won't show up in a scene view

### ISSUE THREAD

**Issue by LATRio** [godotengine/godot#26815]
**Godot version:**

master 86d6a72c9745bd15e3217d63b2cc5ba73fe4ad34
both GLES3 and GLES2

**OS/device including version:**

Windows 10 64-bit
GTX 1060 6GB

**Issue description:**

TextureRect in scene view won't update when changing region of Atlas Texture.
You have to move or change visibility to make it update.
Works fine with a Sprite.

**Steps to reproduce:**
- Create TextureRect and add Atlas Texture
- Select any image as atlas
- Change region

**Comment by KoBeWi** [comment]
Seems to be fixed already, tested in d711c57d7
