### ISSUE TITLE
 How to use c++ to construct a Dynamic Font that can be used in modules ？

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#26819]
How to use c++ to construct a Dynamic Font that can be used in modules

**Comment by cjmxp** [comment]
Dynamic Font  Does it seem impossible to encapsulate extensions?

**Comment by groud** [comment]
This is not the place to ask general questions, but to report bugs and ask for new features. Please use the other [community channels](https://godotengine.org/community) to ask anything.
