### ISSUE TITLE
Reparenting on runtime trows an error if the node has an animation tree

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#26810]
**Godot version:**
3.1-RC1

**OS/device including version:**
Zorin OS Core 12.4

**Issue description:**
Reparenting on runtime trows an error if the node has an animation tree

**Steps to reproduce:**
Create a kinematicbody, add an animation tree, reparent on runtime.

**Minimal reproduction project:**
[Parent-Bug.zip](https://github.com/godotengine/godot/files/2947911/Parent-Bug.zip)

**Comment by akien-mga** [comment]
Fixed by #27895.
