### ISSUE TITLE
Autoload script silently fails to load in editor when referencing another script

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#26824]
**Godot version:**

master dev c23710adde23a0e415097dee7d8e6f9ba76a0970
(also reproduced on latest - 86d6a72c9745bd15e3217d63b2cc5ba73fe4ad34)

**OS/device including version:**
Windows 10

**Issue description:**
When setting a scene as autoload, then trying to edit it, exported variables are missing for any script that references another script.

After investigating, it looks like it's caused by autoloads being loaded before ScriptCodeCompletionCache is initialized in the editor, which prevents any preloaded script to be validated while loading the autoload.

Expected behavior: make sure scripts can be preloaded in autoloads, or display an error message to indicate it's not supported.

**Steps to reproduce:**
- Create a new scene (sceneA)
- Attach a new script (scriptA) to the root node of sceneA
- Create a script (scriptB)
- Edit scriptA and reference scriptB using `preload()`
- Add an exported variable to scriptA
- Go to project settings
- Add sceneA as an autoload
- Quit Godot and restart the project
- Open sceneA to edit it
- Any exported variable is missing in the node using scriptA

**Minimal reproduction project:**
[test-autoload.zip](https://github.com/godotengine/godot/files/2948179/test-autoload.zip)

**Comment by NeoSpark314** [comment]
I just ran into the same issue. I have an autoload (`vr_autoload.gd`) script in my oculus quest toolkit that defines a lot of enums that I am exporting in different nodes. As soon as I have a preload inside my autoload script all exported enums fail in the editor when I open the project.
But when I change sth. inside `vr_autoload.gd` it works until I restart the editor.

**Comment by akien-mga** [comment]
Confirmed in the current master branch.

Note for testers, follow the steps to reproduce thoroughly to see the issue. I initially thought that the bug was fixed since the script variables in the remote scene tree for the Autoload seemed to be exposed OK. But indeed after restarting the editor, the scene used as singleton has lost its script variables in the inspector.

**Comment by KoBeWi** [comment]
Seems fixed in 586a208

**Comment by pouleyKetchoupp** [comment]
Yes, I can confirm it's fixed on master. Closing.
