### ISSUE TITLE
Confusing behavior of keep_3d_linear regarding scene linear HDR data.

### ISSUE THREAD

**Issue by toasteater** [godotengine/godot#26821]
**Godot version:** e930fb9 (3.1 beta11). Still present on 2940475 (master at the time of writing). GLES3 backend.

**OS/device including version:** Recent Arch Linux. GTX 970 w/ binary driver 418.43-4

**Issue description:** `keep_3d_linear`'s behavior is not intuitive: setting the flag does not bypass tonemapping and/or clamping (when `transparent_bg` is off, as that branch uses CopyShaderGLES3 which doesn't do tonemapping. might be related to #26817).

Expected: As the name `keep_3d_linear` may suggest, scene linear HDR data.
Actual: Tonemapped and clamped data.

As stated above, the current behavior can be quite surprising, and limited in use, for cases like custom postprocessing/tonemapping, or using the render target as an HDR texture. It's also inconsistent with the `transparent_bg` branch which does not do tonemapping. I see several ways to deal with this:

* Change `keep_3d_linear` behavior to keep scene linear HDR data. This will break existing projects somewhat since output is no longer tonemapped and/or clamped. However, this also makes the name more intuitive.
* Add another flag (named something like `no_tonemapping`) that specifically indicates scene linear HDR data. This will not break projects, but the new flag will not be independent from the current `keep_3d_linear`, as it's only applicable when `keep_3d_linear` is true.
* Replace the flag with a colorspace enum, where users can choose from tonemapped sRGB, tonemapped linear, or scene linear options. Existing projects should be somehow converted, and `keep_3d_linear` API calls should be mapped to the tonemapped options. This should be most ideal for the end user, but will involve a complicated change (43 hits for `KEEP_3D_LINEAR` in the code).
* Add "None" as a tonemapping mode in Environment, which differs from "Linear" in that no clamping is performed. This should be less prone to regression compared to the previous one, but does break the "always outputs clamped [0;1] color" invariant for `apply_tonemapping` in `tonemap.glsl`, which will affect Glow and Adjustment effects.

**Steps to reproduce:**
* Create GLES3 project.
* Add Node2D -> ViewportContainer -> Viewport
* Add an environment in Viewport, and enable tonemapping. Choose any algorithm.
* Put something and a really bright light in Viewport. Turn on keep_3d_linear for Viewport. Keep transparent_bg off.
* Add a full screen white (1, 1, 1) ColorRect under Node2D and set blend mode to Sub.

Expected: Scene linear HDR data is preserved. Screen is not black.
Actual: Data is tonemapped and/or clamped. Screen is black.

**Minimal reproduction project:** [keep-linear-hdr.zip](https://github.com/godotengine/godot/files/2948069/keep-linear-hdr.zip)

- - -

EDIT: Add another possible change.

**Comment by CptPotato** [comment]
I just ran into this aswell. Even though HDR is enabled the values are clamped.

I'm currently working around this by using a low exposure level in the Tonemapper and multiplying it back when using the texture in a shader.

**Comment by NeoSpark314** [comment]
I also ran into this issue just now when I tried to export hdr texture data from a 3d scene rendered into a viewport texture and then saved to an .exr file. 

An alternative solution to the one proposed in the above pull request  (https://github.com/godotengine/godot/pull/30574), that would not break compatibility to previous versions, could be to introduce an additional tonemapping option called 'none' that would just copy the output instead of clamping.
