### ISSUE TITLE
Could not install to device Android

### ISSUE THREAD

**Issue by esblinuxcss** [godotengine/godot#26820]
**Godot version:**
Godot 3.1 RC

**OS/device including version:**
Android 7.1

**Issue description:**
Could not install to device Android this aperan when i compile the game to Android devices and the generat apk don't work i using Godot_v3.1-rc1_export_templates 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment]
Please be more specific. "Wont work" is not a good description.
What happens ?

**Comment by akien-mga** [comment]
Can't reproduce the issue, I exported a debug APK to my Android 9 phone and my Android 7.1.2 phone without issue.

So indeed, without more info, we can't do anything.

**Comment by esblinuxcss** [comment]
I will be more specific:
My working enviroment is Ubuntu 16.04 LTS 64bits
What happening is in Godot 3.1 Beta 11 and Godot 3.1 RC is when i compile the platformer demo to Android when it finish and godot try to install in device apperas the window "with Load error could install on device". i check if the editor config was bad but it looks Ok is the same config i have in Godot 2.1.5 and Godot 3.0.6 i have no problems with those Releases and i have the same config. here are somo screenshots i promise be more specifig in the future and thanks you for you reply i really love Godot Engine
![Android Config Godot 3 1 RC](https://user-images.githubusercontent.com/27043218/54078350-3f844b00-428c-11e9-95c1-b215a48fd4f7.png)
![Android Deploy Godot Engine 3 1 RC](https://user-images.githubusercontent.com/27043218/54078351-401ce180-428c-11e9-91a4-9cb69d89d2b6.png)
![Compiling](https://user-images.githubusercontent.com/27043218/54078352-401ce180-428c-11e9-91b6-1ae0ffbedd02.png)
![could not install to device](https://user-images.githubusercontent.com/27043218/54078353-401ce180-428c-11e9-9644-0e4b0f34b37a.png)

**Comment by akien-mga** [comment]
ADB should print errors in the terminal, can you paste them here?

**Comment by esblinuxcss** [comment]
2019-03-09 18:51:36.661 920-1025/? E/PackageInstaller: Commit of session 1328964467 failed: Package /mnt/expand/3f7cbaf6-0aba-4589-b109-176472ae748d/app/vmdl1328964467.tmp/base.apk has no certificates at entry AndroidManifest.xml
The log from ADB is weird because in the editor setting i have the same conf in godot 2.1.5, 3.0.6 and 3.1

**Comment by esblinuxcss** [comment]
i think i find the problem was my phone i just formated and complie the game and runs it well
sorry for the inconvenient
