### ISSUE TITLE
CSGMesh doesn't trigger body_entered in Area

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#26827]
**Godot version:**
3.1 rc1

**Issue description:**
A CSGMesh with use_collision will not trigger body_entered when it enters an Area.

**Steps to reproduce:**
Add a CSGMesh with use_collision turned on,add a moving Area and try to trigger body_entered.

**Comment by tom-jk** [comment]
Can reproduce in 3.2.2.stable.

Minimal reproduction project: 
[26827.zip](https://github.com/godotengine/godot/files/4944016/26827.zip)

This appears to be the intended design (or, a known limitation), as per [the docs](https://docs.godotengine.org/en/3.1/classes/class_csgshape.html):

> bool Use Collision:
> Adds a collision shape to the physics engine for our CSG shape. _This will always act like a static body_. Note that the collision shape is still active even if the CSG shape itself is hidden.

In the MRP you can move the CSGSphere with the right key, and the Area does not register entry. But if you use the left key you can move the Area, and entry is registered when it reaches where the CSGSphere is/was originally.
