### ISSUE TITLE
Windows 10 build error with Visual Studio 2015

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#2682]
I tryd building the windows platform with the new source and it results into a link error.

LINK : fatal error LNK1104: cannot open file 'libcpmt.lib'
scons: *** [bin\godot.windows.tools.exe] Error 1104
scons: building terminated because of errors.

windows 10 64bit
godot 2.0

**Comment by vnen** [comment]
@carlosmarti can you be more descriptive about this issue? What version of Visual Studio your using? What commit you're trying to build?

As a note, it's known that VS2013 compiles fine, but VS2015 gives errors. VS2012 seems to give some problems too.

**Comment by carlosmarti** [comment]
I didn't know that VS2013 worked i will download it and see if it works for me. I was using VS2015 and i have not try'd it with VS2012. I am sure what you mean by what commit i am trying to build. Is that the platform that i am tryn to build for? if so i was try'n to build for windows platform.

**Comment by vnen** [comment]
I can see you're not familiar with Git, have you downloaded a zip of the code? The commit would be what point in the code history you're currently trying to build. You may look at [this list of commits](https://github.com/godotengine/godot/commits/master) and see that the last one (as of the writing) is this: bd736e5af2ec5113c23fef58523f57a0b2e11fb2 (they are identified by a SHA hash). If you downloaded with a  `git clone` command, the hash of the last commit can be viewed with the command `git log -1`.

Try with VS2013 for now while VS2015 errors aren't solved.

**Comment by carlosmarti** [comment]
I downloaded a zip file of the code and this is the one i downloaded d123c89c5802777e02402108d9271ed2f29368fe

**Comment by vnen** [comment]
Ok. There's an open pull request that fix this (#2699). While it's not merged, use VS 2013 to compile.

**Comment by vnen** [comment]
Fixed by #2699.
