### ISSUE TITLE
Issues deploying custom builds to Android

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#26832]
**Godot version:**
Basically commit 86d6a72c9745bd15e3217d63b2cc5ba73fe4ad34
But with PR #26221 added

**OS/device including version:**
Xiaomi Pocophone f1

**Issue description:**
Unable to export to Android. Now it is possible that my changes for ARCode (which take a few shortcuts at the moment) broke the export, I have not tried this with the base master (I will tomorrow). I just know that this was working 2 or 3 days ago so there is a recent change.

Compiled both armv7 and arm64v8 release_debug builds and ran gradlew build. Then when attempting to export I get the following:
```
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.godot.testarcore
        at com.android.server.pm.Settings.isOrphaned(Settings.java:4306)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21585)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18353)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:737)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21826)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2809)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4014)
        at android.os.Binder.execTransact(Binder.java:733)
Installing to device (please wait...): Xiaomi POCOPHONE F1
adb: failed to install C:\Users\basti\AppData\Local\Temp/Godot/tmpexport.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1896101717.tmp/base.apk: AndroidManifest.xml]
Starting: Intent { act=android.intent.action.MAIN cmp=com.godot.testarcore/org.godotengine.godot.Godot }
Error type 3
Error: Activity class {com.godot.testarcore/org.godotengine.godot.Godot} does not exist.
```

The manifest has indeed been altered but I can't see if anything is out of place that would explain this:
https://github.com/BastiaanOlij/godot/blob/ARCore/platform/android/AndroidManifest.xml.template
Notice the addition of the camera ar feature and the meta data entry for ARCore.

What I also noticed is this in the logs:
```
ADDING: lib/arm64-v8a/libgodot_android.so
ADDING: lib/armeabi-v7a/libc++_shared.so
ADDING: lib/armeabi-v7a/libgodot_android.so
```
It is only adding libc++_shared for armv7, not for arm64v8, I can confirm the file is there (it is also not including the ARCore files, a separate issue).

**Steps to reproduce:**
Easiest is to just build from my ARCore branch: https://github.com/BastiaanOlij/godot/tree/ARCore
and attempt to export a run of the mill project. 

@RandomShaper , akien asked to tag you here

**Comment by akien-mga** [comment]
I built 9d36ce25e and couldn't reproduce it on either Samsung Galaxy S3 (Android 7.1.2, armv7) and the same Xiaomi Pocophone F1 (Android 9, arm64v8).

I built templates with:
```
scons p=android -j3 target=release_debug android_arch=arm64v8
scons p=android -j3 target=release_debug android_arch=armv7
cd platform/android/java
./gradlew build
```
and set `bin/android_debug.apk` as custom package in my Android export preset.

For each phone, I tried exports with one-click deploy, selecting only their respective arch in the export preset (armv7 for the S3, arm64-v8a for the Pocophone).

I do get the `libc++_shared.so` properly exported for arm64-v8a too:
```
Starting: Intent { act=android.intent.action.MAIN cmp=hello.world.pkg/org.godotengine.godot.Godot }
ADDING: AndroidManifest.xml
ADDING: classes.dex
ADDING: lib/arm64-v8a/libc++_shared.so
ADDING: lib/arm64-v8a/libgodot_android.so
```

**Comment by akien-mga** [comment]
> I just know that this was working 2 or 3 days ago so there is a recent change.

Might be worth comparing the AndroidManifest.xml for an export made on your branch from 3 days ago, and one made from the current version.

You can use the `aapt` tool in the Android SDK to extract the manifest from the compiled .apk, e.g.:
```
android-sdk-linux/build-tools/28.0.3/aapt l -a old_version.apk > old_version_manifest.txt
android-sdk-linux/build-tools/28.0.3/aapt l -a new_version.apk > new_version_manifest.txt
diff -aur old_version_manifest.txt new_version_manifest.txt
```

**Comment by BastiaanOlij** [comment]
I'll try all that, just heard from Robert he managed to compile my branch as well. I might just have to start with a clean build from scratch. Not tonight though :)

**Comment by whplh** [comment]
I used the ARCore branch from BastiaanOlij. Can compile and can export to Android
 ``` 
    scons p=android -j3 target=release_debug android_arch=arm64v8
    scons p=android -j3 target=release_debug android_arch=armv7
    cd platform/android/java
    ./gradlew build
 ```  
But when I use adb to install apk to POCOPHONE F1 with "android_arch=arm64v8", I get:
 ``` 
 INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION:
 Failed to parse /data/app/vmdl1738291031.tmp/base.apk: AndroidManifest.xml
 ``` 

using the aapt tool to extract the manifest on the debug and release apk for arm64v8 I get:
 ``` 
android-sdk-linux/build-tools/28.0.3/aapt l -a new_version.apk > new_version_manifest.txt
 ``` 
new_version_manifest.txt:
 ``` 
META-INF/MANIFEST.MF
lib/arm64-v8a/libc++_shared.so
lib/arm64-v8a/libgodot_android.so
Resource table:
Package Groups (0)
No AndroidManifest.xml found.
 ``` 
Missing manifest for debug and release

**Comment by BastiaanOlij** [comment]
@whplh owh atleast libc++_shared.so is in there. There should be two more .so files in there but for some reason they are not being copied into the apk.

And indeed, I was having the same issues with the manifest, I'm not sure what I changed in it that causes it to no longer parse...

**Comment by whplh** [comment]
Just in case some else has the same problem as me:
running:
```
gradlew clean 
```
Would probably have resolved the problem of the missing manifest after switching architectures.

**Comment by akien-mga** [comment]
This has been fixed a while ago.
