### ISSUE TITLE
Weird reflections on godot-sponza-1.0.0 projects

### ISSUE THREAD

**Issue by kruglinski** [godotengine/godot#26837]
**Godot version:**

Godot_v3.1-rc1_win64

**OS/device including version:**

OS: Microsoft Windows [版本 10.0.17134.590]
GPU: NVIDIA GeForce GTX 960
Driver: 25.21.14.1917

**Issue description:**

I don't known if this is a bug or not, just seem weird!

![image](https://user-images.githubusercontent.com/2869425/54072785-a1f44000-42ba-11e9-903d-b129f1c73038.png)
![image](https://user-images.githubusercontent.com/2869425/54072789-a91b4e00-42ba-11e9-9399-0449f0cdfc83.png)
![image](https://user-images.githubusercontent.com/2869425/54072793-afa9c580-42ba-11e9-8a68-410b1a2796db.png)
![image](https://user-images.githubusercontent.com/2869425/54072816-d962ec80-42ba-11e9-8006-b46008628b4e.png)

**Steps to reproduce:**
Open the godot-sponza-1.0.0 demo project in Godot 3.1 rc1 engine, and walk around to see the reflection near those fires

**Minimal reproduction project:**

[godot-sponza](https://github.com/Calinou/godot-sponza)

**Comment by akien-mga** [comment]
CC @Calinou

**Comment by Janders1800** [comment]
I think that is just the specular light parameter, if you turn it to 0 in the light properties it gets rid of the specular reflection of the light.

**Comment by kruglinski** [comment]
Weird thing is that specular reflection is based on lights not materials? If we want some material to have specular reflection on that orange light, and some material are not , how to do it?

**Comment by CptPotato** [comment]
@kruglinski Godot utilizes phyically based rendering so techically everything has specular reflections. You can change the specular intensity of materials to some degree in the "Metallic" category of the material.

That being said, the reflections do look a bit overkill in these screenshots. But I suspect that it's simply because of too aggressive bloom.

**Comment by Janders1800** [comment]
You can also duplicate the light and have one with an one without specular, then use masks or layers to get the desired result

**Comment by kruglinski** [comment]
Just AB testing 3.0 and 3.1 rc1, it's definitely a bug, without adjust any lights parameters, it shows different results!

in 3.0 stable
![image](https://user-images.githubusercontent.com/2869425/54073782-25fff500-42c6-11e9-8b89-5398465f97d0.png)
![image](https://user-images.githubusercontent.com/2869425/54073785-2c8e6c80-42c6-11e9-9f4e-174c092f1603.png)
![image](https://user-images.githubusercontent.com/2869425/54073789-31532080-42c6-11e9-8b95-6ee5ddc55069.png)

in 3.1 rc1
![image](https://user-images.githubusercontent.com/2869425/54073792-3912c500-42c6-11e9-99bb-27d4f84a0ebd.png)
![image](https://user-images.githubusercontent.com/2869425/54073797-3d3ee280-42c6-11e9-8a76-c9bb87a6ab59.png)
![image](https://user-images.githubusercontent.com/2869425/54073800-4def5880-42c6-11e9-94ca-d1308325c632.png)

**Comment by CptPotato** [comment]
Could you open the scene in 3.1, select the floor and show the category `Parameters`, `Roughness` and `Metallic` of the material?

**Comment by kruglinski** [comment]
> 
> 
> Could you open the scene in 3.1, select the floor and show the category `Parameters`, `Roughness` and `Metallic` of the material?

![image](https://user-images.githubusercontent.com/2869425/54074081-32398180-42c9-11e9-939a-23ad68fdc1a0.png)
![image](https://user-images.githubusercontent.com/2869425/54074084-3796cc00-42c9-11e9-87e6-5414a79fdae8.png)
![image](https://user-images.githubusercontent.com/2869425/54074086-3d8cad00-42c9-11e9-8c39-781b389df5f0.png)

**Comment by Janders1800** [comment]
Happens to me as well, Specular Mode seems to be broken, can't seem to be able to set it to SchlickGGX.

**Comment by CptPotato** [comment]
@kruglinski thanks. The specular highlight looks weird because of the material that is used. A more realistic version should be:
```
Parameters->Specular Mode: SchlickGGX
Metallic->Metallic: 0
Metallic->Specular: 0.5
```

This probably happened because this scene was created in a previous version. If you create your project in the new version these values should be default so you don't have to worry about that.

**Comment by Calinou** [comment]
I actually intentionally made the floor reflective as a "showoff" feature, but I'll revert that since it'll look closer to the original Sponza.

**Comment by clayjohn** [comment]
Is this fixed?

**Comment by Calinou** [comment]
@clayjohn This should be fixed in https://github.com/Calinou/godot-sponza/commit/00035883cce25ab6e2a5632897aefea578ddb5fb.

**Comment by clayjohn** [comment]
@Calinou Great! Closing.
