### ISSUE TITLE
Potential joypad duplication with certain joypad type emulators.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#26836]
**Godot version:**

60d910b

**OS/device including version:**

Win10 64-bit

**Issue description:**

When using an application like [DS4Windows](https://github.com/Jays2Kings/DS4Windows) to emulate an XBox controller, two controllers get registered.

![DS4Windows_2019-03-09_16-16-38](https://user-images.githubusercontent.com/13004169/54072739-b0753400-4287-11e9-8d6f-afdb09f061f3.png)

~~It's not clear to me if the problem lies within DS4 or Godot.~~

DS4Windows can generate a duplicate controller.  Meaning a malfunctioning emulator can make it difficult or impossible for Godot to map player controls for multiple joypads.

Was wondering if were possible to detect situations like this and either warn the player, know which controller to ignore, or filter duplicates out of what the API returns?

**Steps to reproduce:**
Plug in a Playstation 4 controller, startup DS4Windows, run Godot and observe the device IDs and joypad names.

**Minimal reproduction project:**
Small testing project for those on Windows and using DS4Windows.

[3.1 DS4 Input Problem.zip](https://github.com/godotengine/godot/files/2948468/3.1.DS4.Input.Problem.zip)

**Comment by homer666** [comment]
This is a long-standing issue with DS4Windows being unable to hide the PS4 controller. Godot has nothing to do with it.

You need to enable "Hide DS4 Controller" in Settings:
![image](https://user-images.githubusercontent.com/27100585/54074606-a6375200-42e8-11e9-81eb-374ca8dccd39.png)

Then you must make sure DS4Windows has started and your controllers are connected BEFORE you start your games.

With all of that taken into account, the PS4 controller should be hidden:
![image](https://user-images.githubusercontent.com/27100585/54074706-dcc19c80-42e9-11e9-861e-ffdc7f2776b6.png)

**Comment by avencherus** [comment]
@homer666 Thanks, I was wondering if I imagined not having the problem in the past.  I may of not, because of an older configuration.

@akien-mga Going to modify this to be more based on around filtering inputs to watch for this kind of misbehavior in joypad emulations.  Would you want to reclassify this?

**Comment by akien-mga** [comment]
I don't think we can do anything about this, it's the emulator's job to register the right kind of virtual device with the OS. For Godot, the OS just tells us that two devices are connected, I don't think we can know if one is actually due to thirdparty software.

**Comment by avencherus** [comment]
@akien-mga I see, thanks for the input 🥁 😄.  I suppose I was hoping there might be some kind of unique identifier to the controllers that could be used to match them in these kinds of situations.

Unless anyone has anything to add in regards to the existence of such device information, I'll be closing this.

For the time being I'm going to try writing an algorithm that partitions device IDs based on whether their input remains identical over time.  The frame that it diverges should prove its a different controller.

Then another algorithm to dynamically assign owning players based on these groupings and the order of their last known activities.

Hopefully works around both my input problems, but something like that I imagine to be too hacky and specific to be done by the engine.

**Comment by akien-mga** [comment]
> I suppose I was hoping there might be some kind of unique identifier to the controllers that could be used to match them in these kinds of situations.

Well I don't know, there might be. I'm not familiar with how this works exactly internally, my comment was more regarding the fact that we can't really make the engine support all kinds of emulators under the sun. We can (or should) only support the standard system APIs, and those emulators should strive to do their best to match them.

**Comment by jitspoe** [comment]
Just wanted to add a note here that there is a similar issue that happens on Linux with Steam games where Steam will send duplicate inputs.  This can be worked around by setting 'disable Steam input' for the game in Steam.  This is problematic in menus, because it will often skip menu items.  I think I'm going to hack around this by adding a time threshold between menu item changes.  I don't currently have a PS4 controller, so I can't delve into this too much, but thought I'd share this.
