### ISSUE TITLE
TPS Demo is pixelated with Beta 7 + above, due to depth prepass regression [macOS] 2

### ISSUE THREAD

**Issue by TheNeoGameFactory** [godotengine/godot#26846]
Don't close it, if it's not fixed!! Wait for our answers!
Godot version:
3.1 RC1

OS/device including version:
Mac OS
AMD Radeon R9 M370X

Issue description:
The TPS Demo from Godot is pixelated after start. (Not Main Menu)
Testing the same Project with Godot 3.1 beta 3 and everything works fine.
So something must be wrong with Godot 3.1. beta 7 + above

Steps to reproduce:
Just open and run the TPS Project.
Issue appears with beta 7 + above, with beta 3 it's all fine

https://github.com/godotengine/godot/issues/26258#issue-413902198

**Comment by akien-mga** [comment]
I reopened #26258 which has the relevant history.
