### ISSUE TITLE
Directory Menu listing available drives in small caps

### ISSUE THREAD

**Issue by IronicallySerious** [godotengine/godot#26844]
**Godot version:**
Godot Version 3.1 Beta 11 https://github.com/godotengine/godot/commit/d41cd57595c4f68838b8dcf27e66cb77476577ed

**OS/device including version:**
Windows 10 64 Bit Insider Build 18342

**Issue description:**
The drop-down menu for changing disc drive lists the drive names in small caps. IMO, the disk drives should be rendered in caps, which matches the way all other applications on Windows do.
![image](https://user-images.githubusercontent.com/31801364/54075603-4aa89c80-42c7-11e9-8f61-0c504499ab5a.png)

**Steps to reproduce:**
While creating a new project, look at the drop down menu that lists the disk drives.

**Comment by Rriik** [comment]
While this is brought up, this change should apply to all places where drive selection is available (such as the file browser interfaces within Godot and so on).

**Comment by kartikey0303** [comment]
I edited https://github.com/godotengine/godot/blob/master/drivers/windows/dir_access_windows.cpp#L121 
to return a capital letter. I think that should fix it for all locations drive selection is present.
