### ISSUE TITLE
Overdraw viewport not working as expected

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#26840]
**Godot version:** 3.1 beta 10

**OS/device including version:** Win10 / AMD RX580

I tried to use the overdraw viewport but it doesn't seem to work properly.

Here's a few opaque boxes:
![grafik](https://user-images.githubusercontent.com/3957610/54073840-03e98100-428c-11e9-98bb-82d0139434a6.png)

And this is what it looks like in the overdraw viewport:
![grafik](https://user-images.githubusercontent.com/3957610/54073847-1368ca00-428c-11e9-86ae-de176120ffd1.png)

I expected that at least some of the occluded parts are not receiving *all* drawcalls but it's always showing every object in the scene.

It seems like
- either the debug view shows incorrect data
- or everything is drawn as shown and there is a bug in the depth-testing process

**Comment by kaadmy** [comment]
Right now there's no occlusion culling, so if an object is in the camera frustum then it's always rendered.

**Comment by CptPotato** [comment]
Yes, but occlusion culling works on a per-object basis. What I'm talking about is a per-pixel depth test that the GPU automatically does to reject pixels that are occluded.

**Comment by Calinou** [comment]
It might just be poorly named and work exactly like it did in Godot 2.1, by making all materials transparent to check whether there's overlapping objects.

**Comment by CptPotato** [comment]
Ah okay, thanks for the clarification. The name made me think that it's meant for performance debugging.

**Comment by kb173** [comment]
Sorry for reviving this issue, but I was very confused by this as well. I was trying to use the "Overdraw" view to debug performance hits of transparent vs non-transparent objects, and it took me a while to figure out that this Overdraw view does not react to transparency at all (even though, to my understanding, that is where actual overdraw becomes a big problem since the GPU has to render many fragments for the same screen pixel). Could this debug draw mode be renamed to prevent future confusion?

**Comment by Calinou** [comment]
@kb173 Renaming the debug draw mode enum value would break compatibility, so it can't be done before 5.0.

That said, consider that depending on the rendering method used, a depth prepass isn't always used. The Mobile rendering method *never* uses a depth prepass, so the way the overdraw depth draw mode is perfectly relevant there.

Forward+ uses a depth prepass by default (unless disabled in the project settings), and Compatibility always uses a depth prepass.

Still, the overdraw debug draw mode is useful to see overlapping objects as you'll want to cull as many objects from view as possible regardless of whether your current rendering method uses a depth prepass. It's a performance win either way.

**Comment by meganlfox** [comment]
I don't know if it's more appropriate to revive this issue or start a new one, but given that we're to 4.7 now and this issue remains standing, could it be revisited?

Like I get the utility of what you're calling "overdraw" here in absolute terms, but if I'm turning to the debug vis mode called that, what I'm actually looking for is. Well. "Real" overdraw. I'm looking for the layered transparencies, and any weird opaque objects I've set up wrong such that they do cause overdraw despite depth pre-pass.

Which I guess would be a feature request both to rename this (or remove it, but whatever) and add a more normal what-the-GPU-actually-does Overdraw mode?

(on the off-chance anyone hits this while looking for a solution, RenderDoc actually has a quad overdraw view that'll probably do what you want, as a workaround for now - obviously harder to deploy casually, but it's an option, and you'll probably want RenderDoc for other optimization anyways)
