### ISSUE TITLE
 CTRL + SHIFT + UP/DOWN remapping not working in Script Text Editor

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26854]
**Godot version:**
3.1 RC1

**OS/device including version:**
Windows 10 x64

**Issue description:**
I tried to remap the keyboard shortcuts "Move Up" and "Move Down" to become similar to the "Sublime Text" editor, which would respectively be `Ctrl+Shift+Up` and `Ctrl+Shift+Down`, but these combinations are not working.

**Steps to reproduce:**

Editor -> Editor Setting -> Shortcuts

**Comment by KoBeWi** [comment]
Move up/down CAN be remapped. Script editor just doesn't take any shortcuts that use combinations of CTRL/SHIFT and arrows. But combination CTRL + SHIFT + UP/DOWN doesn't seem to do anything normally.

**Comment by akien-mga** [comment]
Confirmed in 3.2.2 RC 3 in the script text editor.

<kbd>Ctrl+Up</kbd>/<kbd>Ctrl+Down</kbd> seem to be hardcoded to scroll the active script up/down by one line, which likely conflicts with using <kbd>Shift+Ctrl+Up</kbd> for other actions (here "Move Up" rebound to <kbd>Shift+Ctrl+Up</kbd> has this same scroll-one-line behavior).

**Comment by akien-mga** [comment]
It's probably because `TextEdit` handles this directly, so combinations with <kbd>Up</kbd>/<kbd>Down</kbd> and <kbd>Ctrl</kbd> (<kbd>Cmd+Alt</kbd> on macOS) don't work:
https://github.com/godotengine/godot/blob/3c9fc891c860a385fb5461b6f07566df1b9db38e/scene/gui/text_edit.cpp#L3211-L3223

**Comment by Paulb23** [comment]
Yeah looks like another case of #29490
