### ISSUE TITLE
Light2D changes the colors no matter what (even with shaders)

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2686]
When I try a no-op shader like this:

Fragment: `COLOR = tex(TEXTURE, UV);`
Ligthing: `LIGHT = COLOR;`

I'm still getting brightened output when there is a Light2D around (Light2D has a texture of course, otherwise it has no effect).

BTW, what is SRC_COLOR?

**Comment by bojidar-bg** [comment]
Maybe you want `Unshaded` Shading Mode on your CanvasItemMaterial?

**Comment by MarianoGnu** [comment]
try setting COLOR.a=1

**Comment by seadra** [comment]
The thing is, I'm trying to implement a light model, so I do need shading enabled.
But some unknown/unwanted/unspecified light that isn't in my shader is always interfering with my light.

> try setting COLOR.a=1

Alpha isn't the problem.

**Comment by romulox-x** [comment]
I'm making a few guesses about your setup (like that lights are set to Add mode, since they default to this).  But based on those assumptions, your shader isn't a no-op shader.  It's adding light based on COLOR.  I can't quite figure out what's contained in COLOR, but if it's greater than 0, that means you're adding light to the scene.

**Comment by seadra** [comment]
Light2D has to be Add, Mix or Sub. I guess the other option is to remove it altogether.

COLOR comes from the Fragment shader, which is
```
COLOR = tex(TEXTURE, UV);
```
Can you explain why and how this is not a no-op shader?

In any case, the question is: how can I implement my own lighting model, and only my own?

**Comment by seadra** [comment]
When I say "my own lighting model", I mean something along the lines of [Blinn lighting](https://github.com/godotengine/godot/wiki/shader) in 3D; the color and light is determined by the shader, and *only* by the shader, by using textures and other parameters such as LIGHT_COLOR.

Does this make sense to you?

In my case, I'm trying to implement a variation of Gooch lighting.

**Comment by reduz** [comment]
As lighting is additive, light is applied as a two pass operation. The base color is rendered first and the light is rendered second in additive mode, like in any forward renderer.

If you don't want the contribution of the base color, you can use a CanvasModulate node and set it to pitch black, then only lighting will take place..

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
