### ISSUE TITLE
Regression of GLES2 materials in RC1 3.1.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#26860]
**Godot version:**
In version of Godot_v3.1-rc1_win64.exe, compared to Godot_v3.1-beta11_win64.exe

**OS/device including version:**
Windows 7 Radeon HD 3650

**Issue description:**
GLES2 materials in RС1 3.1, textures lose clarity, strange stripes are visible.

![image](https://user-images.githubusercontent.com/10380658/54078555-ab89a200-42d2-11e9-85a9-92da420750a6.png)

**Minimal reproduction project:**
https://www.dropbox.com/s/yb0j0yyfasw459v/3D%20mat.zip?dl=0

**Comment by clayjohn** [comment]
I can't reproduce on linux, Ubuntu 16.04, intel HD graphics

**Comment by akien-mga** [comment]
It seems to be due to showing the 3D gizmos, did you try in beta 11 with gizmos disabled maybe?

**Comment by akien-mga** [comment]
I can reproduce the blurry reflection with the provided project on Linux (Mageia 7) with Nvidia GTX 670MX.

3.1 beta 11:
![Screenshot_20190310_133402](https://user-images.githubusercontent.com/4701338/54085030-2dacb180-4339-11e9-8c08-d5bc359ac845.png)

3.1 RC1 and 59aa79f2: 
![Screenshot_20190310_133446](https://user-images.githubusercontent.com/4701338/54085043-46b56280-4339-11e9-9875-712924fc9620.png)

I don't have the issue with the gizmos leaking though.

**Comment by akien-mga** [comment]
The blurry reflection is a regression from 7141c73ae, a local revert fixes it.

**Comment by akien-mga** [comment]
The blurry reflection should be fixed by #26898.

If you can still reproduce the issue with the gizmos appearing on meshes, that would be worth reporting in a new issue.

**Comment by OlexiyKravchuk** [comment]
This is still broken, and deep regression, I tried to run on another computer, here is the result of photos, versions - (Godot_v3.1-beta11_win64.exe, Godot_v3.1-rc1_win64.exe, Godot_v3.1-rc2_win64.exe, Godot_v3. 1-rc3_win64.exe) at the last, additional errors are visible ...
![image](https://user-images.githubusercontent.com/10380658/54293633-02d09080-45b9-11e9-9cc2-8c6b1b0d1b9f.png)
![image](https://user-images.githubusercontent.com/10380658/54293676-12e87000-45b9-11e9-8130-7f4c0ca36bdc.png)
![image](https://user-images.githubusercontent.com/10380658/54293713-1f6cc880-45b9-11e9-8333-4b35801ccd6b.png)
![image](https://user-images.githubusercontent.com/10380658/54293738-2eec1180-45b9-11e9-87fd-a56bc7c711bb.png)

**Comment by clayjohn** [comment]
The error is unrelated. It must have been introduced somewhere else. 

The results in Beta11 are slightly crisper because they are used a slightly larger radiance map then they should have. To reproduce that level of detail, you should use a larger radiance map. You can set it under environment>sky.

The reason that the radiance is not the same is that it has been updated to match the results of the GLES3 backend.
