### ISSUE TITLE
Godot 3.1 AStar class Zig Zag 4 Direction Movement

### ISSUE THREAD

**Issue by MotasemZakarneh** [godotengine/godot#26866]
**Godot version: 3.1**

**Issue description:**
![1](https://user-images.githubusercontent.com/46475130/54083146-b111d700-4328-11e9-82ba-2feecf906fcc.png)

ok, so i have used the AStar Reference Object, and when using it, if i go for 4 directional movement, and in some situations, we'd end up, a lot of jagged lines(zigzag), so i thought, some sort of modification to the A_Star would be quite needed, at least, some modification that allows us to fix such issue we need. 

```
float _compute_cost ( int from_id, int to_id ) virtual
Called when computing the cost between two connected points.
```

i think, it would be really helpful, if we also get a previous point in this function (the one directly before from_id) the directly previous point in the path would be more than enough. 
because, we'd be able to compare, the previous and current point to get a direction. 
and i'd get a direction between the current and the next, and if there is a difference in direction, i can increase the cost by 1 or something.

not really sure, if this counts as an issue that deserves to open a post on, sorry if its not in an appropriate place, but i thought i'd mention it. 

or at least some sort of, built in method, that says "defavor jagged lines" or something like that, i just think it would be really helpful functionality.

**Comment by MotasemZakarneh** [comment]
ok, so a solution, with the help of others, i managed to find was
```
func _estimate_cost(from_id, to_id):
    var from = index_to_pos[from_id]
    var to = index_to_pos[to_id]
    return manhaten_dist(from,to)

func _compute_cost(from_id, to_id):
    var from = index_to_pos[from_id]
    var to = index_to_pos[to_id]
    return manhaten_dist(from,to)

func manhaten_dist(from,to):
    var dx = abs(to.x-from.x)
    var dy = abs(to.y-from.y)
    
    return dx+dy
```

basically, i'd inherit from AStar node, override these functions, and use the manhaten distance. 

**After**
![image](https://user-images.githubusercontent.com/46475130/54083992-c6403300-4333-11e9-948c-ab942df2d373.png)

so, i guess a solution, was found, for anyone interested.

**Comment by Szesan** [comment]
> ok, so a solution, with the help of others, i managed to find was

> basically, i'd inherit from AStar node, override these functions, and use the manhaten distance.

> so, i guess a solution, was found, for anyone interested.

Thank you @MotasemZakarneh! I ran into the same problem.

for those working with the mono version here is the solution in C#:

   ```
 public class CustomAStar: AStar2D
    {
        public override float _ComputeCost(int fromId, int toId)
        {
            var from = GetPointPosition(fromId);

            var to = GetPointPosition(toId);

            return ManhattanDistance(from, to);
        }

        public override float _EstimateCost(int fromId, int toId)
        {
            var from = GetPointPosition(fromId);

            var to = GetPointPosition(toId);

            return ManhattanDistance(from, to);
        }

        private float ManhattanDistance(Vector2 from, Vector2 to)
        {
            var dx = Math.Abs(to.x - from.x);

            var dy = Math.Abs(to.y - from.y);

            return dx + dy;
        }
    }
```
