### ISSUE TITLE
Autotile is broken

### ISSUE THREAD

**Issue by MustaphaRashiduddin** [godotengine/godot#26888]
**Godot version:**
Godot 3.1 rc1

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
autotile not working as expected.

**Steps to reproduce:**
I've given my example project, it has outdoor.tres, i made one Autotile called roguelikeSheet_transparent.png 0, all you have to do is go into tilemap select the only tile
available there and then try to make some tiles in the editor.
On the perimeter it'll look like the tile in the margin which you click on and in the middle it'll seemingly
place tiles randomly.

Note, in the snap options, the seperation is set to 1 for x and y. 

**Minimal reproduction project:**

[roguelike.zip](https://github.com/godotengine/godot/files/2950155/roguelike.zip)

**Comment by MatiasVME** [comment]
You need to configure the bitmask.

**Comment by MustaphaRashiduddin** [comment]
thanks very much, i didn't understand the bitmask properly before, the clarification helped alot, i hope they put in these kind of short video clips like this in the documentation for clarity.
