### ISSUE TITLE
Incorrect Material assignment and other voodoo

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#26881]
**Godot version:**

3.1 RC1 x64 Windows and Mac OS

**OS/device including version:**

Windows 7 64 bit. DxDiag: https://pastebin.com/frbLAqv9

macOS High Sierra 10.13.16 MacBook Pro (Retina, 15-inch, Mid 2014) Processor: 2.2 GHz Intel Core i7  Memory: 16 GB 1600 MHz DDR3 Graphics: Intel Iris Pro 1536 MB

**Issue description:**

When selecting certain nodes in the editor, and when adding/removing materials, under some circumstances, materials become unassigned or switch places. Additionally all material slots beyond 0 appear to ignore their assigned faces, and are applied to the whole mesh.

**Steps to reproduce:**
I honestly don't know. Demo project included.
Video of the problem in action: https://streamable.com/dicq8 With further explanation.

**Minimal reproduction project:**

[MaterialVoodo.zip](https://github.com/godotengine/godot/files/2949986/MaterialVoodo.zip)

Open the Model.tscn file.

**Comment by TheDuriel** [comment]
Update: It appears that part of the problem, materials not being assigned to the correct faces. Is in fact a problem caused by the dae format, not Godot itself. (And there is nothing Godot can to prevent this. It's just bad mesh data.)

The odd material flipping based on what you have selected in the editor _does_ appear to be separate from this however.

**Comment by IAmActuallyCthulhu** [comment]
I can now confirm exact same behavior on macOS.

In addition, there is another why to make the material flip. 

![Zoom - OUT](https://cdn.discordapp.com/attachments/540803169374961664/554449210569654276/unknown.png)

![Zoom - IN](https://cdn.discordapp.com/attachments/540803169374961664/554449269378252810/unknown.png)

- If you change the import settings with Mesh > Compress
    - `true` it will flip materials when you zoom in the editor.
    - `false` it will NOT flip materials when you zoom in the editor.
    - Both settings still has behavior of flipping material with selection change as described above and video.

**Comment by TheDuriel** [comment]
I've tracked down the problem to what appears to be a twofold cause. First: Our mesh is screwed up. Second, Godot _appears_ to have problems correctly dealing with meshes that have "several materials, that are assigned using a 'polylist'"

Godot also appears to completely refuse to load meshes that assign their materials using 'triangles'. Meaning only 'polygons' remain as a valid data structure. (This seems to be one of the problems contributing to the inability to correctly import dae files created with blenders default exporters, instead of better collada. Which uses 'polygons' to assign its materials.)

Barring further discoveries i'd say this issue can be closed, and chalked up to "user error caused by an impossible to understand asset workflow due to how different programs deal with collada 1.4.1".

**Comment by akien-mga** [comment]
Closing following the above comment, as the main issue was due to a bogus mesh.

About the lack of support for "polylists", this could likely be tracked in a separate bug report or documented as a known limitation.
