### ISSUE TITLE
Crash on C# Export with CLI

### ISSUE THREAD

**Issue by rossimo** [godotengine/godot#26884]
**Godot version:**
3.1 RC1

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When exporting a PCK preset for a C# project with the CLI, the export process randomly crashes. I can't seem to find a consistent set of steps to reproduce it. The logs are pretty long, I've attached them in a Gist. The export log and the Mono log are in the Gist.

https://gist.github.com/rossimo/6d4445ce4f06bcde53456c9775facc74

**Steps to reproduce:**
```
godot --no-window --export pck --path . Stratagem.pck
```

**Comment by akien-mga** [comment]
The stacktrace involves `EditorResourcePreview`, so this was likely fixed by #35113.
