### ISSUE TITLE
I always have to run a project twice, so that the console, debugger and compiling are working with the run

### ISSUE THREAD

**Issue by TypeOverride** [godotengine/godot#26889]
**Godot version:**
All versions! Until latest 3.1 Beta 10

**OS/device including version:**
Windows 7

**Issue description:**
I always have to run a project twice, so that the console, debugger and compiling are working with the run.

**Steps to reproduce:**
1) Run your project with F5 (or use play-button)
-> Debugger and so on NOT working
2) Stop your running project
3) Run your project with F5 (or use play-button) again
-> all fine. Debugger and so on now working

I know i come with this bug very late. And i have the feeling noone else has it than me. But i have it since i use Godot.

**Comment by Chaosus** [comment]
Is it happens in all projects ? (then its definitly a driver-level bug on your PC), or its happened in specific project (then you should provide a link to zip so other devs could reproduce it).

**Comment by Zireael07** [comment]
I have a similar problem, with all projects, and all Godot versions. The first run after installing a particular version results in the debugger not working, I have to run the project again.

**Comment by TypeOverride** [comment]
> Does it happens in all projects ? or its happened in specific project (then you should provide a link to zip so other devs could reproduce it).

Its in on every project. Doesnt matter.

**Comment by Zireael07** [comment]
In my case, it goes away later - if I download e.g. RC1, I only have the issue the first time I run RC1, all subsequent runs of RC1 are unaffected.

**Comment by akien-mga** [comment]
So it's just Windows asking you for permission to connect to the network, no? That's used by the debugger (on localhost), it's expected.

**Comment by Zireael07** [comment]
I never get any popups asking for permission from Windows or my antivirus/firewall, though. And it always works later on, with no configuration changes or the like.

**Comment by akien-mga** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
