### ISSUE TITLE
Godot crashes when justifying RichTextLabel of default size

### ISSUE THREAD

**Issue by SHARKvince** [godotengine/godot#2688]
Godot crashes when aligning text justified (or how Godot calls it, “fill”) in a RichTextLabel ~~set with a custom font~~.

1. Open a new scene
2. Add a RichTextLabel node
3. ~~Import a font (I used “Garogier”, but any should work)~~
4. Enable BBcode
5. Enter this in text:
“[fill]Last thing I remember was we were playing hide and seek. Guess they either forgot about me or gave up, huh...[/fill]”
6. ~~Set the “Normal” font to the one imported previously~~

**Bugsquad edit:** removed unneeded steps to reproduce.

**Comment by vnen** [comment]
This seems to be related to the size of the RichTextLabel. If I resize it to be larger before adding the text, it works fine. If the size is too small to contain the text, it crashes. If I insert the text first and later active the BBCode, it also crashes.

Though it's not related to the custom font, for me it crashes as soon as I insert the text.

**Comment by reduz** [comment]
i can't make it crash, but the preview looks wrong, checking out why...
