### ISSUE TITLE
ItemList looks like an item is selected even when nothing is selected

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#26895]
**Godot version:** 3.0.6

**OS/device including version:** Windows 8.1

**Issue description:**
When you select an empty space in an item list, it fires the `nothing_selected` event, but items still appear selected.

![godot-select-bug](https://user-images.githubusercontent.com/31222662/54098530-58bff100-438b-11e9-9f76-313d0195a986.gif)

**Steps to reproduce:**
- Create an item list
- Populate it with a bunch of items
- Wire up an event to `nothing_selected`
- Run it and click on an item, then click on the empty space

Expected: the ItemList doesn't look like anything is selected.
Actual: it still looks selected

**Minimal reproduction project:** 

[ItemListTest.zip](https://github.com/godotengine/godot/files/2950553/ItemListTest.zip)

**Work-around:** Add this to the `on_nothing_selected` event handler:

```
var _all_items = [] # list of all items going in the list
for i in range(len(self._all_items)):
  $ItemList.unselect(i)
```

**Comment by MidZik** [comment]
This is a missing documentation issue. The control _purposefully_ does nothing when you click on empty space. The `nothing_selected` signal exists so that other code can react to empty space being clicked on.

FYI, in 3.1 there is a one-liner to deselect everything: `$ItemList.unselect_all()`

**Comment by nightblade9** [comment]
Even if the control does nothing, the UI is misleading. It looks like the previously-selected item is still selected, when in fact, nothing is selected.

Or maybe I'm misinterpreting the event - I understood it as "there are no items that are still selected." It sounds like it really means "you didn't click on an item" (not that it unselected the existing item).

**Comment by MidZik** [comment]
You are misunderstanding. When the event fires, nothing changes (things are still selected), and this is currently intended behavior. The UI in your example is always up-to-date.

Your workaround is actually what you are currently expected to do if you want that behavior. And to reiterate, it is easier to do in 3.1: `$ItemList.unselect_all()`

**Comment by volzhs** [comment]
yes, the signal name is confusing for me too.
`nothing_selected` should be `empty_area_selected` or something.

**Comment by nightblade9** [comment]
I see - this is what you meant by "documentation is out of date." It makes sense now.

No worries - I will close this issue then. Thanks for clarifying!
