### ISSUE TITLE
GLES2: 3D scenes crash on Android (Mali T830, no OES_texture_float)

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#26902]
**Godot version:**
Godot 3.1 RC1

**OS/device including version:**
Samsung Galaxy Tab A (2016), Android 8.1.0, 

**Issue description:**
I'm getting crashes when trying to run 3D games/demos on Android in GLES2. The only debug output I'm getting is "R float texture not supported". GLES3 seems to work.

**Comment by akien-mga** [comment]
Can you share a project that reproduces it?

**Comment by akien-mga** [comment]
Are you using a CurveTexture?

**Comment by akien-mga** [comment]
Could you also enable Debug > Settings > Verbose Stdout and see if you get more details in `adb logcat`?

**Comment by ProbDenis** [comment]
I can reproduce it with the "Platformer 3D" demo. With Verbose STDout I'm getting the following output:
![debug_output](https://user-images.githubusercontent.com/15891496/54156245-232c0e00-4446-11e9-9d2f-56fd8ccc1610.png)

**Comment by ProbDenis** [comment]
Here's the report from OpenGL ES CapsViewer:
http://opengles.gpuinfo.org/displayreport.php?id=3450

**Comment by akien-mga** [comment]
Can you check `adb logcat`? There might be more details around those OpenGL errors.

It would also be useful to know the OpenGL ES extensions supported by that device, as reported by OpenGL ES CapsViewer. It doesn't seem listed yet in http://opengles.gpuinfo.org/

**Comment by akien-mga** [comment]
Could you try this patch? https://github.com/akien-mga/godot/commit/ec831398e3de3d4bc57f47a304a01d8b02cd4aeb

You'll need to build the editor binary from that commit, and here's a matching **debug** APK (only armv7 lib included, but should work on your arm64v8 device, just make sure to tick armv7 in the export preset): [Android debug APK](https://framadrop.org/r/lloqsmzmRr#nsGZ2go1nQalLQ0jWkanzp4IYX2r3TT4GskaKmkMD70=)

**Comment by akien-mga** [comment]
Could you try this patch? https://github.com/akien-mga/godot/commit/5976a524d2849fb1d0232d12fc3ae7f98b3cbcdc

You'll need to build the editor binary from that commit, and here's a matching debug APK (only armv7 lib included, but should work on your arm64v8 device, just make sure to tick armv7 in the export preset): [Android debug APK](https://framadrop.org/r/Yb-d2VK4z7#7eJ1yT33vRW+2coqCquXLCOiFpJgGrfegPjOy5mCCP0=)

**Comment by akien-mga** [comment]
Here's another debug APK for #26943 with both [armv7 and arm64v8](https://framadrop.org/r/b4WhrCHtYC#K2XNp7LlW1gCdHgGbeLSDUGKHA95Mieqeoa0FWDniOQ=).

**Comment by ProbDenis** [comment]
adb logcat is spamming the console with messages so fast that it's difficult for me to know what to look for, but I found this message:
OpenGLRenderer: Incorrectly called buildLayer on View: WorkspaceCellLayoutChildren, destroying layer...

**Comment by akien-mga** [comment]
I see that my [Samsung Galaxy S3](http://opengles.gpuinfo.org/displayreport.php?id=3407) also doesn't support OES_texture_float, I'll see if I can reproduce the issue and debug further.

**Comment by akien-mga** [comment]
Could you try https://framadrop.org/r/zpwgiaKLyL#vqtCStJXshsSLTwiBLv7IOvc3xgu6H9Edt9XwUd1g4g= ? It works well for me on the Samsung Galaxy S3. It's a `target=debug` build so it should provide a backtrace in `adb logcat` if it crashes.

Note that it might not fix all potential crashes on loading a 3D scene on that device, just the part we saw so far about R float texture not being supported.
If you're still testing with the 3D platformer, you might into another crash as described in #26943. Try also to change the physics engine to GodotPhysics, as I had a crash in Bullet on my higher end phone with that demo.

**Comment by ProbDenis** [comment]
I'm still getting crashes. This is the part of the log that might be interesting:
[log.txt](https://github.com/godotengine/godot/files/2957420/log.txt)

**Comment by akien-mga** [comment]
Yeah that's the same crash I'm getting in https://github.com/godotengine/godot/pull/26943#issuecomment-471960739

I think it's unrelated to what was fixed with #26943, so it might be worth opening a new issue about it. That new crash is specific to scenes with Skeleton.

**Comment by akien-mga** [comment]
Fixed by #26943.

I'll open another issue for the Skeleton crash.

**Comment by akien-mga** [comment]
I opened #26972 for the other crash.
