### ISSUE TITLE
Bug on OptionButton add_item (also PopupMenu)

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#26909]
**Godot version:**
Last master 3.1 RC1

**OS/device including version:**
N/A

**Issue description:**

The description for `add_item` method in `OptionButton` states the following:

`void add_item( String label, int id=-1 )`
Add an item, with text "label" and (optionally) id. If no "id" is passed, "id" becomes the item index. New items are appended at the end.

this is NOT happening, providing no id will make the item id to become "-1" and not its index

EDIT: this falls back to its parent class

**Comment by xDGameStudios** [comment]
@akien-mga it is not a documentation problem, it is a source code problem (default -1 value) is never taken care of

**Comment by akien-mga** [comment]
Well it could be the documentation which is wrong, and not the source code.

**Comment by xDGameStudios** [comment]
Who can know that?

**Comment by karliss** [comment]
There is at least one place in code that handles -1 `PopupMenu::activate_item` has `int id = items[p_item].ID >= 0 ? items[p_item].ID : p_item;`, but get_item_id doesn't.
