### ISSUE TITLE
GDscript  not support chinese variables

### ISSUE THREAD

**Issue by rjdgheart** [godotengine/godot#26917]
English script ：var bullet=9
Chinese script ：var 子弹=9
But Chinese script report errors.
Different countries, different languages,but you can use your native language in GDscript,it is so cool.
Hope it will come true.

**Comment by bojidar-bg** [comment]
Duplicate of #24785.

**Comment by harrisyu** [comment]
I personaly don't like this request as a Chinese.
Reason:
1. That's not a programer's thingking.
2. Switching IME when coding cause low efficiency.
3. Not good for reading.
4. Complex naming will slow GDscript down.
5. Will be a lots of side-effects.

**Comment by freekoy** [comment]
You can do this.
var cc = {}
cc['子弹'] = 9
