### ISSUE TITLE
RC1 C# Autoload double instance

### ISSUE THREAD

**Issue by ForLoveOfCats** [godotengine/godot#26915]
**Godot version:**
The break occurs between Godot Mono 3.1 Beta 11 -> Godot Mono 3.1 RC1 (also present in RC2)

**OS/device including version:**
Manjaro Linux x64 

**Issue description:**
After updating to 3.1 RC1 and above, autoloaded C# scripts are instanced twice.

**Steps to reproduce:**
Attached is a project which shows this. Open in Beta 11 to see the correct output.
![image](https://user-images.githubusercontent.com/30666851/54122837-8aa97580-43d4-11e9-8c1f-945fad2f0b64.png)
however in RC1 and RC2
![image](https://user-images.githubusercontent.com/30666851/54122873-a6148080-43d4-11e9-950f-3f379763eea0.png)

**Minimal reproduction project:**
[DoubleInstance.zip](https://github.com/godotengine/godot/files/2952075/DoubleInstance.zip)

**Comment by neikeq** [comment]
The first one is a temporary one used when updating exported default values. We update exports on script reload now, since f8a6a6c8a2eb704de9879727f9b975b6de7cfd19. Maybe this should be done only if running the editor?

**Comment by ForLoveOfCats** [comment]
That would be greatly appreciated

**Comment by shartte** [comment]
The entirety of the _update_exports method is in an #ifdef TOOLS_ENABLED.
I guess it could actually check whether it's in the editor or not instead.
