### ISSUE TITLE
Godot is changing my project settings

### ISSUE THREAD

**Issue by Dentrax** [godotengine/godot#26916]
**Godot version:** `3.1-rc_1.x11.64`

**OS/device including version:** `Arch Linux 5.0.0 x86_64 GNU/Linux`

**Issue description:** 

1. **What happened**

We are using git system in the project. We would like to use a common `project.godot` settings file with my friend. But Godot does not allow it. Changes the `project.godot` file to the default settings by itself by **force**. When I pulled and opened the project, the changes that made from my friend, overridden by engine to the default settings (and sometimes ignore the config file) instead of applying the changes that I pulled.

My currently temporary solution is the make it immutable using `sudo chattr +i project.godot`

But still, Godot wasn't stopping, kept insisting. :)

Godot is constantly showing up a annoying popup alert which means preventing us from working on the project.

![image](https://user-images.githubusercontent.com/16493751/54125466-20b1c000-4416-11e9-8f3c-836092232a23.png)

2. **What was expected**

1) Godot should not change the `project.godot` setting file by force without prompting us.
2) If the we set `project.godot` as an immutable attr, Godot should not try to overwrite when it asked a question like: "Are you sure to use project.godot file as an immutable file?" ...even when my answer is: "Yes, of course." Please dont try to second overwrite force wave.
3) Why Godot is changing `project.godot` as a default file when i clone the project and open it?

**Steps to reproduce:**

1. `git clone project`
2-1. Open the `project.godot` from the engine.
3-1. Now the file is overwritten by engine.
2-2. `sudo chattr +i project.godot`
3-1. Endless popup cycle

**Comment by Calinou** [comment]
> Why Godot is changing project.godot as a default file when i clone the project and open it?

What is it changing exactly? Can you paste the unmodified and modified `project.godot` here?

**Comment by Dentrax** [comment]
Unmodified:

```
; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=4

_global_script_classes=[  ]
_global_script_class_icons={

}

[application]

config/name="spaceship_orbit"
run/main_scene="res://scenes/scene_root.tscn"
config/icon="res://icon.png"

[display]

window/size/width=480
window/size/height=800
window/handheld/orientation="portrait"
window/stretch/mode="2d"
window/stretch/aspect="keep"

[input]

touch={
"deadzone": 0.5,
"events": [ Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":0,"alt":false,"shift":false,"control":false,"meta":false,"command":false,"button_mask":0,"position":Vector2( 0, 0 ),"global_position":Vector2( 0, 0 ),"factor":1.0,"button_index":1,"pressed":false,"doubleclick":false,"script":null)
 ]
}

[rendering]

quality/driver/driver_name="GLES2"
vram_compression/import_etc=true
vram_compression/import_etc2=false
environment/default_environment="res://default_env.tres"
```

Modified:

```
; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=4

_global_script_classes=[  ]
_global_script_class_icons={

}

[application]

config/name="spaceship_orbit"
run/main_scene="res://scenes/scene_root.tscn"
config/icon="res://icon.png"

[rendering]

quality/driver/driver_name="GLES2"
vram_compression/import_etc=true
vram_compression/import_etc2=false
environment/default_environment="res://default_env.tres"
```

**Comment by Calinou** [comment]
If you decided to switch the project to GLES2, you should commit the modified `project.godot` to version control :slightly_smiling_face:

**Comment by Dentrax** [comment]
> If you decided to switch the project to GLES2, you should commit the modified `project.godot` to version control

We both are using `GLES2`. What do we need to change? Can't we use different settings for both GLES2 and GLES3?

**Comment by Zylann** [comment]
So basically Godot removed the `display` and `application` sections, is that it?

**Comment by Dentrax** [comment]
@Zylann Basically yes Godot removed `display` and `input` sections because currently we only use them.

I tested your second situation, now Godot do not read the config file, i think it ignores the config file.

**Comment by Zylann** [comment]
> Godot removed display and input sections because currently we only use them.

I'm confused, Godot should not remove a section you are using... so what I understand from this is that Godot never attempts to reload project settings which were modified externally, so instead it just keeps writing back what it has loaded in memory, effectively overwriting your updated settings. This is why I asked if closing the editor before syncing was fixing it.

**Comment by Dentrax** [comment]
@Zylann 

Actually I also tested with this case:

1. Restart the PC
2. Clone the repo
3. Open the Godot and then open the project

The problem still continues. But this time it does not overwrite, it just ignores it. Godot cannot load project settings correctly. I dont't know why. Also it still gives me a error popup when I do project settings file as read-only. That means, Godot reads the config file during the runtime.

**Comment by Dentrax** [comment]
Looks like Steam version v3.1 fixed this problem on Windows 10. I don't know how.
