### ISSUE TITLE
Touchscreenbutton not working with mouse 

### ISSUE THREAD

**Issue by Plopsiskopsis** [godotengine/godot#26920]
**Godot version:**
3.1 rc2

**OS/device including version:**
Windows 10

**Issue description:**
Add a touchscreenbutton to a scene and code to print anything and try to click it with a mouse when running the scene

**Steps to reproduce:**
see above.

**Comment by volzhs** [comment]
what about enabling `Emulate Touch From Mouse` at Project Settings > General > Input Deivces > Pointing?

**Comment by akien-mga** [comment]
Indeed, just tested in 7b67c58 and it works well when `Emulate Touch From Mouse` is enabled.
