### ISSUE TITLE
3D Animated Better-Collada mesh from Blender don’t show up on Android 4.4 phone

### ISSUE THREAD

**Issue by sdhy** [godotengine/godot#26934]
Also, Export to Godot from Blender as .escn doesn’t work.

**Godot version:**
Godot 3.1. RC2

**OS/device including version:**
Made and exported game using Godot on macOS High Sierra Version 10.13.6
GPU: AMD Radeon HD 6770M 512MB

I tested and exported a game on two phones:
Phone #1) I.e. my older phone:
_A Samsung phone (I rooted it to unlock it).
Model number: SGH-I337M (Samsung Galaxy S4)
Android 4.4.2 (that's 4.4, not 4.2)
GPU: Adreno (TM) 320_

Phone #2) i.e. my newer phone:
_Game works fine on this one.
LGE LG-K210 (LG X Power)
GPU: Adreno (TM) 304_

If you need more info on phones, feel free to ask.

**Issue description:**
If I export an **animated** 3D mesh from Blender to Godot using Better Collada, it doesn't show up in the game on my old phone.

They show up and animate properly on my newer phone and iMac, though.

Exporting an animated .escn file from Blender doesn’t work.
It did in RC1, but there was no colour in Godot Editor, and the animation was messed up in-game on my new phone and iMac.
The un-animated level.escn works and has colour on both phones, but has no colour in the editor.

**Steps to reproduce:**
Open the attached Godot project.
Export to android phone 
Install and open on a phone with above specs (Samsung Galaxy S4 Android 4.4.2, That's 4.4, not 4.2)
It’s supposed to have a 3D character that plays an animation if you touch the screen.

**Minimal reproduction project:**
See attachment. Thanks for fixing issues in Godot!
[Better Collada, Animated, Doesn't Show Up on Android 4.4.zip](https://github.com/godotengine/godot/files/2954299/Better.Collada.Animated.Doesn.t.Show.Up.on.Android.4.4.zip)

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
