### ISSUE TITLE
Bone animations invisible on android

### ISSUE THREAD

**Issue by Asedi** [godotengine/godot#26933]
**Godot version:**
3.1 RC1

**OS/device including version:**
Android 4.4.4

**Issue description:**
Hello. I have got problem with my simple bone animation using AnimationPlayer, Skeleton2D and body parts as Polygons2D on my android phone. "Head" of the character and his legs are Polygons2D. Simply, animated legs are just invisible. On my windows pc it's working fine. I'm using GLES2 and my phone is  HTC DESIRE 620. I can check it on newer device if it's needed,
**Windows 7**
![Windows][1]
**Android 4.4.4**
![Android][2]

  [1]: https://i.imgur.com/ccNecGj.gif
  [2]: https://i.imgur.com/PhC52jz.gif

**Comment by vbousquet** [comment]
Hi, I can confirm the bug. Skeleton2D works fine on Windows 10, but shows nothing on Android. Additional informations:
- The bug only happens in the GLES2 renderer; switching to GLES3 solve this.
- My animation use internal vertices (same setup as the 2d deform mesh in the docs).

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 3.2 builds?

If so, can you attach a project that triggers the issue?

**Comment by Asedi** [comment]
Unfortunately my project is gone propably and I’m using IOS now so can’t help with it.

**Comment by vbousquet** [comment]
I have just made the test again on the Samsung A8 (SM-A530F):

- The bug is still there in 3.2 RC1 (i.e. not rendering in GLES2 while rendering in GLES3)
- The other bug referenced above in issue #27919 is also still there in 3.2 RC1 for GLES3 (dark rendering)

**Comment by lawnjelly** [comment]
This should be checked with 3.2.4 beta 1 onwards, as it may be fixed by 2d software skinning in unified batching.

**Comment by kyoz** [comment]
I'v the same problem with GLES2 on 3.2. GLES3 is working but get some weird color.

Godot 3.3 seem fixed this, but i got the bone rotation problem. You sound give it a try

**Comment by lawnjelly** [comment]
> Godot 3.3 seem fixed this, but i got the bone rotation problem. You sound give it a try

If you have a bone rotation problem, please post an issue with a minimum reproduction project so I can fix it. There are some differences in the methods of skinning between the hardware and software, I've tried to work through the cases.

**Comment by kyoz** [comment]
Hi @lawnjelly , i'v tried to create a minimum reproduction project but it work just correctly. Doesn't know why bone in my pj got wrong rotation. I'v tried it again and create an issue if i'v found any problem.

Thank you so much :love:

**Comment by kyoz** [comment]
This is some how relative to https://github.com/godotengine/godot/issues/48348

In Godot 3.3 `rendering/2d/use_software_skinning` is enabled by default and it help rendering correctly on android device. But turn it on will cause rotation problem with Skeleton2D Bones

**Comment by kyoz** [comment]
Tested on 3.3.1-rc2 and this issue is fixed
