### ISSUE TITLE
get_window_size and set_window_size don't work correctly with hiDPI enabled

### ISSUE THREAD

**Issue by alvaromunoz** [godotengine/godot#26947]
**Godot version:**
3.1.rc2.official

**OS/device including version:**
MacOS Mojave 10.14.13
MacBook Pro 2015 13"

**Issue description:**
I decided to save screen size and position on exit, and restore their values on start. This doesn't work when using HiDPI, since OS.get_window_size gives pixel size, and OS_set_window_size expects HiDPI values.
![Kapture 2019-03-12 at 0 09 17](https://user-images.githubusercontent.com/2722773/54171999-35647700-445b-11e9-9eee-d9f9f5fff7b0.gif)

**Steps to reproduce:**
While configuring your project with HiDPI support:
`OS.set_window_size(OS.get_window_size())
`

**Minimal reproduction project:**

[New Game Project.zip](https://github.com/godotengine/godot/files/2955015/New.Game.Project.zip)

**Comment by bruvzg** [comment]
> since OS.get_window_size gives pixel size, and OS_set_window_size expects HiDPI values

It's exactly opposite `get_window_size` return scaled value (there's `get_real_window_size` for pixel value) and `set_window_size` doesn't take scale into account, restoring from `set_window_maximized` is also broken for the same reason.

**Comment by alvaromunoz** [comment]
> > since OS.get_window_size gives pixel size, and OS_set_window_size expects HiDPI values
> 
> It's exactly opposite `get_window_size` return scaled value (there's `get_real_window_size` for pixel value

You're right, got those mixed up in the issue description, sorry!
