### ISSUE TITLE
can't use nodes on script

### ISSUE THREAD

**Issue by edmarfjr** [godotengine/godot#26948]
**Godot version:**
3.1 RC2
![erro](https://user-images.githubusercontent.com/14282718/54172431-cc7dfe80-445c-11e9-9475-3b883f5227ac.JPG)

**OS/device including version:**

**Issue description:**
can't use nodes on script on new scenes/nodes

**Steps to reproduce:**
make a new scene or node, add some children node then try to use then on script, on the image im sending ilustrate this error, sorry for the english

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Reproduction project would be really useful.

**Comment by akien-mga** [comment]
Your `anim` variable is `null`, so for some reason it's not properly assigned or it has been freed. Using `find_node` in `onready` is a bad idea, and is probably why it doesn't work, as when this scene is ready its parent scene is not yet, so `find_node` called on the root node might not succeed yet.
