### ISSUE TITLE
Can't start godot in Gles2 on recent build

### ISSUE THREAD

**Issue by Th0r12356** [godotengine/godot#26940]
**Godot version:**
3.1 rc
7452f5c

**OS/device including version:**
Linux 4.18.0-16 18.04.1-Ubuntu 64

Intel HD 3000

**Issue description:**
Starting Godot with gles2 and it is just flickering, console is spamming 1000 of lines shader code with errors, even terminating is not working. Need to kill the process.
I am building godot nearly every day, yesterday everything was working.
The error occurs in a new empty scene in gles2

![Screenshot_2019-03-11_23-58-29](https://user-images.githubusercontent.com/33563732/54164002-47461a00-445b-11e9-951a-be8b73c7ad8a.png)

console output looks like this, this are some of the lines:
`ERROR: _display_error_with_code: CubemapFilterShaderGLES2: Vertex shader compilation failed:
0:35(1): error: #extension directive is not allowed in the middle of a shader At: drivers/gles2/shader_gles2.cpp:129.
ERROR: get_current_version: Method/Function Failed, returning: __null`

`ERROR: _display_error_with_code: SceneShaderGLES2: Vertex shader compilation failed:
0:758(1): error: #extension directive is not allowed in the middle of a shader

   At: drivers/gles2/shader_gles2.cpp:129.
ERROR: get_current_version: Method/Function Failed, returning: __null
   At: drivers/gles2/shader_gles2.cpp:288.
ERROR: bind: Condition ' !version ' is true. returned: false
   At: drivers/gles2/shader_gles2.cpp:88.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.
1: #version 120
2: #define USE_GLES_OVER_GL
3: 
4: #ifdef USE_GLES_OVER_GL
5: #define lowp
6: #define mediump
7: #define highp
8: #else
9: precision highp float;
10: precision highp int;
11: #endif
12: 
13: uniform highp mat4 projection_matrix;
14: /* clang-format on */
15: 
16: 
17: vec2 select2(vec2 a, vec2 b, bvec2 c) {
18: 	vec2 ret;
19: 
20: 	ret.x = c.x ? b.x : a.x;
21: 	ret.y = c.y ? b.y : a.y;
22: 
23: 	return ret;
24: }
25: 
26: vec3 select3(vec3 a, vec3 b, bvec3 c) {
27: 	vec3 ret;
28: 
29: 	ret.x = c.x ? b.x : a.x;
30: 	ret.y = c.y ? b.y : a.y;
31: 	ret.z = c.z ? b.z : a.z;
32: 
33: 	return ret;
34: }
35: 
36: vec4 select4(vec4 a, vec4 b, bvec4 c) {
37: 	vec4 ret;
38: 
39: 	ret.x = c.x ? b.x : a.x;
40: 	ret.y = c.y ? b.y : a.y;
41: 	ret.z = c.z ? b.z : a.z;
42: 	ret.w = c.w ? b.w : a.w;
43: 
44: 	return ret;
45: }
46: 
47: highp vec4 texel2DFetch(highp sampler2D tex, ivec2 size, ivec2 coord) {
48: 	float x_coord = float(2 * coord.x + 1) / float(size.x * 2);
49: 	float y_coord = float(2 * coord.y + 1) / float(size.y * 2);
50: 
51: 	return texture2DLod(tex, vec2(x_coord, y_coord), 0.0);
52: }
53: 
54: #ifndef USE_GLES_OVER_GL
55: highp mat4 transpose(highp mat4 src) {
56: 	return mat4(
57: 			vec4(src[0].x, src[1].x, src[2].x, src[3].x),
58: 			vec4(src[0].y, src[1].y, src[2].y, src[3].y),
59: 			vec4(src[0].z, src[1].z, src[2].z, src[3].z),
60: 			vec4(src[0].w, src[1].w, src[2].w, src[3].w));
61: }
62: #endif
63: 
64: uniform highp mat4 modelview_matrix;
65: uniform highp mat4 extra_matrix;
66: attribute highp vec2 vertex; // attrib:0
67: attribute vec4 color_attrib; // attrib:3
68: attribute vec2 uv_attrib; // attrib:4
69: 
70: #ifdef USE_SKELETON
71: attribute highp vec4 bone_indices; // attrib:6
72: attribute highp vec4 bone_weights; // attrib:7
73: #endif
74: 
75: #ifdef USE_INSTANCING
76: 
77: attribute highp vec4 instance_xform0; //attrib:8
78: attribute highp vec4 instance_xform1; //attrib:9
79: attribute highp vec4 instance_xform2; //attrib:10
80: attribute highp vec4 instance_color; //attrib:11
81: 
82: #ifdef USE_INSTANCE_CUSTOM
83: attribute highp vec4 instance_custom_data; //attrib:12
84: #endif
85: 
86: #endif
87: 
88: #ifdef USE_SKELETON
89: uniform highp sampler2D skeleton_texture; // texunit:-3
90: uniform highp ivec2 skeleton_texture_size;
91: uniform highp mat4 skeleton_transform;
92: uniform highp mat4 skeleton_transform_inverse;
93: #endif
94: 
95: varying vec2 uv_interp;
96: varying vec4 color_interp;
97: 
98: uniform highp vec2 color_texpixel_size;
99: 
100: #ifdef USE_TEXTURE_RECT
101: 
102: uniform vec4 dst_rect;
103: uniform vec4 src_rect;
104: 
105: #endif
106: 
107: uniform highp float time;
108: 
109: #ifdef USE_LIGHTING
110: 
111: // light matrices
112: uniform highp mat4 light_matrix;
113: uniform highp mat4 light_matrix_inverse;
114: uniform highp mat4 light_local_matrix;
115: uniform highp mat4 shadow_matrix;
116: uniform highp vec4 light_color;
117: uniform highp vec4 light_shadow_color;
118: uniform highp vec2 light_pos;
119: uniform highp float shadowpixel_size;
120: uniform highp float shadow_gradient;
121: uniform highp float light_height;
122: uniform highp float light_outside_alpha;
123: uniform highp float shadow_distance_mult;
124: 
125: varying vec4 light_uv_interp;
126: varying vec2 transformed_light_uv;
127: varying vec4 local_rot;
128: 
129: #ifdef USE_SHADOWS
130: varying highp vec2 pos;
131: #endif
132: 
133: const bool at_light_pass = true;
134: #else
135: const bool at_light_pass = false;
136: #endif
137: 
138: /* clang-format off */
139: 
140: 
141: /* clang-format on */
142: 
143: vec2 select(vec2 a, vec2 b, bvec2 c) {
144: 	vec2 ret;
145: 
146: 	ret.x = c.x ? b.x : a.x;
147: 	ret.y = c.y ? b.y : a.y;
148: 
149: 	return ret;
150: }
151: 
152: void main() {
153: 
154: 	vec4 color = color_attrib;
155: 	vec2 uv;
156: 
157: #ifdef USE_INSTANCING
158: 	mat4 extra_matrix_instance = extra_matrix * transpose(mat4(instance_xform0, instance_xform1, instance_xform2, vec4(0.0, 0.0, 0.0, 1.0)));
159: 	color *= instance_color;
160: 	vec4 instance_custom = instance_custom_data;
161: 
162: #else
163: 	mat4 extra_matrix_instance = extra_matrix;
164: 	vec4 instance_custom = vec4(0.0);
165: #endif
166: 
167: #ifdef USE_TEXTURE_RECT
168: 
169: 	if (dst_rect.z < 0.0) { // Transpose is encoded as negative dst_rect.z
170: 		uv = src_rect.xy + abs(src_rect.zw) * vertex.yx;
171: 	} else {
172: 		uv = src_rect.xy + abs(src_rect.zw) * vertex;
173: 	}
174: 
175: 	vec4 outvec = vec4(0.0, 0.0, 0.0, 1.0);
176: 
177: 	// This is what is done in the GLES 3 bindings and should
178: 	// take care of flipped rects.
179: 	//
180: 	// But it doesn't.
181: 	// I don't know why, will need to investigate further.
182: 
183: 	outvec.xy = dst_rect.xy + abs(dst_rect.zw) * select(vertex, vec2(1.0, 1.0) - vertex, lessThan(src_rect.zw, vec2(0.0, 0.0)));
184: 
185: 	// outvec.xy = dst_rect.xy + abs(dst_rect.zw) * vertex;
186: #else
187: 	vec4 outvec = vec4(vertex.xy, 0.0, 1.0);
188: 
189: 	uv = uv_attrib;
190: #endif
191: 
192: 	{
193: 		vec2 src_vtx = outvec.xy;
194: 		/* clang-format off */
195: 
196: 
197: 		/* clang-format on */
198: 	}
199: 
200: #if !defined(SKIP_TRANSFORM_USED)
201: 	outvec = extra_matrix_instance * outvec;
202: 	outvec = modelview_matrix * outvec;
203: #endif
204: 
205: 	color_interp = color;
206: 
207: #ifdef USE_PIXEL_SNAP
208: 	outvec.xy = floor(outvec + 0.5).xy;
209: 	// precision issue on some hardware creates artifacts within texture
210: 	// offset uv by a small amount to avoid
211: 	uv += 1e-5;
212: #endif
213: 
214: #ifdef USE_SKELETON
215: 
216: 	// look up transform from the "pose texture"
217: 	if (bone_weights != vec4(0.0)) {
218: 
219: 		highp mat4 bone_transform = mat4(0.0);
220: 
221: 		for (int i = 0; i < 4; i++) {
222: 			ivec2 tex_ofs = ivec2(int(bone_indices[i]) * 2, 0);
223: 
224: 			highp mat4 b = mat4(
225: 					texel2DFetch(skeleton_texture, skeleton_texture_size, tex_ofs + ivec2(0, 0)),
226: 					texel2DFetch(skeleton_texture, skeleton_texture_size, tex_ofs + ivec2(1, 0)),
227: 					vec4(0.0, 0.0, 1.0, 0.0),
228: 					vec4(0.0, 0.0, 0.0, 1.0));
229: 
230: 			bone_transform += b * bone_weights[i];
231: 		}
232: 
233: 		mat4 bone_matrix = skeleton_transform * transpose(bone_transform) * skeleton_transform_inverse;
234: 
235: 		outvec = bone_matrix * outvec;
236: 	}
237: 
238: #endif
239: 
240: 	uv_interp = uv;
241: 	gl_Position = projection_matrix * outvec;
242: 
243: #ifdef USE_LIGHTING
244: 
245: 	light_uv_interp.xy = (light_matrix * outvec).xy;
246: 	light_uv_interp.zw = (light_local_matrix * outvec).xy;
247: 
248: 	transformed_light_uv = (mat3(light_matrix_inverse) * vec3(light_uv_interp.zw, 0.0)).xy; //for normal mapping
249: 
250: #ifdef USE_SHADOWS
251: 	pos = outvec.xy;
252: #endif
253: 
254: 	local_rot.xy = normalize((modelview_matrix * (extra_matrix_instance * vec4(1.0, 0.0, 0.0, 0.0))).xy);
255: 	local_rot.zw = normalize((modelview_matrix * (extra_matrix_instance * vec4(0.0, 1.0, 0.0, 0.0))).xy);
256: #ifdef USE_TEXTURE_RECT
257: 	local_rot.xy *= sign(src_rect.z);
258: 	local_rot.zw *= sign(src_rect.w);
259: #endif
260: 
261: #endif
262: }
263: 
264: /* clang-format off */
265: #ifndef USE_GLES_OVER_GL
266: #ifdef GL_EXT_shader_texture_lod
267: #extension GL_EXT_shader_texture_lod : enable
268: #define texture2DLod(img, coord, lod) texture2DLodEXT(img, coord, lod)
269: #define textureCubeLod(img, coord, lod) textureCubeLodEXT(img, coord, lod)
270: #endif
271: #endif // !USE_GLES_OVER_GL
272: 
273: #ifdef GL_ARB_shader_texture_lod
274: #extension GL_ARB_shader_texture_lod : enable
275: #endif
276: 
277: #if !defined(GL_EXT_shader_texture_lod) && !defined(GL_ARB_shader_texture_lod)
278: #define texture2DLod(img, coord, lod) texture2D(img, coord, lod)
279: #define textureCubeLod(img, coord, lod) textureCube(img, coord, lod)
280: #endif
281: 
282: #ifdef USE_GLES_OVER_GL
283: #define lowp
284: #define mediump
285: #define highp
286: #else
287: #if defined(USE_HIGHP_PRECISION)
288: precision highp float;
289: precision highp int;
290: #else
291: precision mediump float;
292: precision mediump int;
293: #endif
294: #endif
295: 
296: uniform sampler2D color_texture; // texunit:-1
297: /* clang-format on */
298: uniform highp vec2 color_texpixel_size;
299: uniform mediump sampler2D normal_texture; // texunit:-2
300: 
301: varying mediump vec2 uv_interp;
302: varying mediump vec4 color_interp;
303: 
304: uniform highp float time;
305: 
306: uniform vec4 final_modulate;
307: 
308: #ifdef SCREEN_TEXTURE_USED
309: 
310: uniform sampler2D screen_texture; // texunit:-4
311: 
312: #endif
313: 
314: #ifdef SCREEN_UV_USED
315: 
316: uniform vec2 screen_pixel_size;
317: 
318: #endif
319: 
320: #ifdef USE_LIGHTING
321: 
322: uniform highp mat4 light_matrix;
323: uniform highp mat4 light_local_matrix;
324: uniform highp mat4 shadow_matrix;
325: uniform highp vec4 light_color;
326: uniform highp vec4 light_shadow_color;
327: uniform highp vec2 light_pos;
328: uniform highp float shadowpixel_size;
329: uniform highp float shadow_gradient;
330: uniform highp float light_height;
331: uniform highp float light_outside_alpha;
332: uniform highp float shadow_distance_mult;
333: 
334: uniform lowp sampler2D light_texture; // texunit:-4
335: varying vec4 light_uv_interp;
336: varying vec2 transformed_light_uv;
337: 
338: varying vec4 local_rot;
339: 
340: #ifdef USE_SHADOWS
341: 
342: uniform highp sampler2D shadow_texture; // texunit:-5
343: varying highp vec2 pos;
344: 
345: #endif
346: 
347: const bool at_light_pass = true;
348: #else
349: const bool at_light_pass = false;
350: #endif
351: 
352: uniform bool use_default_normal;
353: 
354: /* clang-format off */
355: 
356: FRAGMENT_SHADER_GLOBALS
357: 
358: /* clang-format on */
359: 
360: void light_compute(
361: 		inout vec4 light,
362: 		inout vec2 light_vec,
363: 		inout float light_height,
364: 		inout vec4 light_color,
365: 		vec2 light_uv,
366: 		inout vec4 shadow_color,
367: 		vec3 normal,
368: 		vec2 uv,
369: #if defined(SCREEN_UV_USED)
370: 		vec2 screen_uv,
371: #endif
372: 		vec4 color) {
373: 
374: #if defined(USE_LIGHT_SHADER_CODE)
375: 
376: 	/* clang-format off */
377: 
378: LIGHT_SHADER_CODE
379: 
380: 	/* clang-format on */
381: 
382: #endif
383: }
384: 
385: void main() {
386: 
387: 	vec4 color = color_interp;
388: 	vec2 uv = uv_interp;
389: #ifdef USE_FORCE_REPEAT
390: 	//needs to use this to workaround GLES2/WebGL1 forcing tiling that textures that dont support it
391: 	uv = mod(uv, vec2(1.0, 1.0));
392: #endif
393: 
394: #if !defined(COLOR_USED)
395: 	//default behavior, texture by color
396: 	color *= texture2D(color_texture, uv);
397: #endif
398: 
399: #ifdef SCREEN_UV_USED
400: 	vec2 screen_uv = gl_FragCoord.xy * screen_pixel_size;
401: #endif
402: 
403: 	vec3 normal;
404: 
405: #if defined(NORMAL_USED)
406: 
407: 	bool normal_used = true;
408: #else
409: 	bool normal_used = false;
410: #endif
411: 
412: 	if (use_default_normal) {
413: 		normal.xy = texture2D(normal_texture, uv).xy * 2.0 - 1.0;
414: 		normal.z = sqrt(1.0 - dot(normal.xy, normal.xy));
415: 		normal_used = true;
416: 	} else {
417: 		normal = vec3(0.0, 0.0, 1.0);
418: 	}
419: 
420: 	{
421: 		float normal_depth = 1.0;
422: 
423: #if defined(NORMALMAP_USED)
424: 		vec3 normal_map = vec3(0.0, 0.0, 1.0);
425: 		normal_used = true;
426: #endif
427: 
428: 		/* clang-format off */
429: 
430: FRAGMENT_SHADER_CODE
431: 
432: 		/* clang-format on */
433: 
434: #if defined(NORMALMAP_USED)
435: 		normal = mix(vec3(0.0, 0.0, 1.0), normal_map * vec3(2.0, -2.0, 1.0) - vec3(1.0, -1.0, 0.0), normal_depth);
436: #endif
437: 	}
438: 	color *= final_modulate;
439: 
440: #ifdef USE_LIGHTING
441: 
442: 	vec2 light_vec = transformed_light_uv;
443: 
444: 	if (normal_used) {
445: 		normal.xy = mat2(local_rot.xy, local_rot.zw) * normal.xy;
446: 	}
447: 
448: 	float att = 1.0;
449: 
450: 	vec2 light_uv = light_uv_interp.xy;
451: 	vec4 light = texture2D(light_texture, light_uv);
452: 
453: 	if (any(lessThan(light_uv_interp.xy, vec2(0.0, 0.0))) || any(greaterThanEqual(light_uv_interp.xy, vec2(1.0, 1.0)))) {
454: 		color.a *= light_outside_alpha; //invisible
455: 
456: 	} else {
457: 		float real_light_height = light_height;
458: 		vec4 real_light_color = light_color;
459: 		vec4 real_light_shadow_color = light_shadow_color;
460: 
461: #if defined(USE_LIGHT_SHADER_CODE)
462: 		//light is written by the light shader
463: 		light_compute(
464: 				light,
465: 				light_vec,
466: 				real_light_height,
467: 				real_light_color,
468: 				light_uv,
469: 				real_light_shadow_color,
470: 				normal,
471: 				uv,
472: #if defined(SCREEN_UV_USED)
473: 				screen_uv,
474: #endif
475: 				color);
476: #endif
477: 
478: 		light *= real_light_color;
479: 
480: 		if (normal_used) {
481: 			vec3 light_normal = normalize(vec3(light_vec, -real_light_height));
482: 			light *= max(dot(-light_normal, normal), 0.0);
483: 		}
484: 
485: 		color *= light;
486: 
487: #ifdef USE_SHADOWS
488: 		// Reset light_vec to compute shadows, the shadow map is created from the light origin, so it only
489: 		// makes sense to compute shadows from there.
490: 		light_vec = light_uv_interp.zw;
491: 
492: 		float angle_to_light = -atan(light_vec.x, light_vec.y);
493: 		float PI = 3.14159265358979323846264;
494: 		/*int i = int(mod(floor((angle_to_light+7.0*PI/6.0)/(4.0*PI/6.0))+1.0, 3.0)); // +1 pq os indices estao em ordem 2,0,1 nos arrays
495: 		float ang*/
496: 
497: 		float su, sz;
498: 
499: 		float abs_angle = abs(angle_to_light);
500: 		vec2 point;
501: 		float sh;
502: 		if (abs_angle < 45.0 * PI / 180.0) {
503: 			point = light_vec;
504: 			sh = 0.0 + (1.0 / 8.0);
505: 		} else if (abs_angle > 135.0 * PI / 180.0) {
506: 			point = -light_vec;
507: 			sh = 0.5 + (1.0 / 8.0);
508: 		} else if (angle_to_light > 0.0) {
509: 
510: 			point = vec2(light_vec.y, -light_vec.x);
511: 			sh = 0.25 + (1.0 / 8.0);
512: 		} else {
513: 
514: 			point = vec2(-light_vec.y, light_vec.x);
515: 			sh = 0.75 + (1.0 / 8.0);
516: 		}
517: 
518: 		highp vec4 s = shadow_matrix * vec4(point, 0.0, 1.0);
519: 		s.xyz /= s.w;
520: 		su = s.x * 0.5 + 0.5;
521: 		sz = s.z * 0.5 + 0.5;
522: 		//sz=lightlength(light_vec);
523: 
524: 		highp float shadow_attenuation = 0.0;
525: 
526: #ifdef USE_RGBA_SHADOWS
527: 
528: #define SHADOW_DEPTH(m_tex, m_uv) dot(texture2D((m_tex), (m_uv)), vec4(1.0 / (256.0 * 256.0 * 256.0), 1.0 / (256.0 * 256.0), 1.0 / 256.0, 1.0))
529: 
530: #else
531: 
532: #define SHADOW_DEPTH(m_tex, m_uv) (texture2D((m_tex), (m_uv)).r)
533: 
534: #endif
535: 
536: #ifdef SHADOW_USE_GRADIENT
537: 
538: 		/* clang-format off */
539: 		/* GLSL es 100 doesn't support line continuation characters(backslashes) */
540: #define SHADOW_TEST(m_ofs) { highp float sd = SHADOW_DEPTH(shadow_texture, vec2(m_ofs, sh)); shadow_attenuation += 1.0 - smoothstep(sd, sd + shadow_gradient, sz); }
541: 
542: #else
543: 
544: #define SHADOW_TEST(m_ofs) { highp float sd = SHADOW_DEPTH(shadow_texture, vec2(m_ofs, sh)); shadow_attenuation += step(sz, sd); }
545: 		/* clang-format on */
546: 
547: #endif
548: 
549: #ifdef SHADOW_FILTER_NEAREST
550: 
551: 		SHADOW_TEST(su);
552: 
553: #endif
554: 
555: #ifdef SHADOW_FILTER_PCF3
556: 
557: 		SHADOW_TEST(su + shadowpixel_size);
558: 		SHADOW_TEST(su);
559: 		SHADOW_TEST(su - shadowpixel_size);
560: 		shadow_attenuation /= 3.0;
561: 
562: #endif
563: 
564: #ifdef SHADOW_FILTER_PCF5
565: 
566: 		SHADOW_TEST(su + shadowpixel_size * 2.0);
567: 		SHADOW_TEST(su + shadowpixel_size);
568: 		SHADOW_TEST(su);
569: 		SHADOW_TEST(su - shadowpixel_size);
570: 		SHADOW_TEST(su - shadowpixel_size * 2.0);
571: 		shadow_attenuation /= 5.0;
572: 
573: #endif
574: 
575: #ifdef SHADOW_FILTER_PCF7
576: 
577: 		SHADOW_TEST(su + shadowpixel_size * 3.0);
578: 		SHADOW_TEST(su + shadowpixel_size * 2.0);
579: 		SHADOW_TEST(su + shadowpixel_size);
580: 		SHADOW_TEST(su);
581: 		SHADOW_TEST(su - shadowpixel_size);
582: 		SHADOW_TEST(su - shadowpixel_size * 2.0);
583: 		SHADOW_TEST(su - shadowpixel_size * 3.0);
584: 		shadow_attenuation /= 7.0;
585: 
586: #endif
587: 
588: #ifdef SHADOW_FILTER_PCF9
589: 
590: 		SHADOW_TEST(su + shadowpixel_size * 4.0);
591: 		SHADOW_TEST(su + shadowpixel_size * 3.0);
592: 		SHADOW_TEST(su + shadowpixel_size * 2.0);
593: 		SHADOW_TEST(su + shadowpixel_size);
594: 		SHADOW_TEST(su);
595: 		SHADOW_TEST(su - shadowpixel_size);
596: 		SHADOW_TEST(su - shadowpixel_size * 2.0);
597: 		SHADOW_TEST(su - shadowpixel_size * 3.0);
598: 		SHADOW_TEST(su - shadowpixel_size * 4.0);
599: 		shadow_attenuation /= 9.0;
600: 
601: #endif
602: 
603: #ifdef SHADOW_FILTER_PCF13
604: 
605: 		SHADOW_TEST(su + shadowpixel_size * 6.0);
606: 		SHADOW_TEST(su + shadowpixel_size * 5.0);
607: 		SHADOW_TEST(su + shadowpixel_size * 4.0);
608: 		SHADOW_TEST(su + shadowpixel_size * 3.0);
609: 		SHADOW_TEST(su + shadowpixel_size * 2.0);
610: 		SHADOW_TEST(su + shadowpixel_size);
611: 		SHADOW_TEST(su);
612: 		SHADOW_TEST(su - shadowpixel_size);
613: 		SHADOW_TEST(su - shadowpixel_size * 2.0);
614: 		SHADOW_TEST(su - shadowpixel_size * 3.0);
615: 		SHADOW_TEST(su - shadowpixel_size * 4.0);
616: 		SHADOW_TEST(su - shadowpixel_size * 5.0);
617: 		SHADOW_TEST(su - shadowpixel_size * 6.0);
618: 		shadow_attenuation /= 13.0;
619: 
620: #endif
621: 
622: 		//color *= shadow_attenuation;
623: 		color = mix(real_light_shadow_color, color, shadow_attenuation);
624: //use shadows
625: #endif
626: 	}
627: 
628: //use lighting
629: #endif
630: 
631: 	gl_FragColor = color;
632: }
633: 
ERROR: _display_error_with_code: CanvasShaderGLES2: Vertex shader compilation failed:
0:274(1): error: #extension directive is not allowed in the middle of a shader

   At: drivers/gles2/shader_gles2.cpp:129.
ERROR: get_current_version: Method/Function Failed, returning: __null
   At: drivers/gles2/shader_gles2.cpp:288.
ERROR: bind: Condition ' !version ' is true. returned: false
   At: drivers/gles2/shader_gles2.cpp:88.
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254.`

**Comment by Th0r12356** [comment]
Godot was working until bc3c633, the first commit since this issue occurs.

**Comment by akien-mga** [comment]
Yeah I messed up, fixed with #26936 and 5976a524.

**Comment by Th0r12356** [comment]
That was pretty fast =) Thanks!
