### ISSUE TITLE
[New Scene system] Inherited scenes won't open in editor. 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#2694]
In current build bd736e5af2ec5113c23fef58523f57a0b2e11fb2 it's impossible to open any scene that is created with "new inherited Scene" option. Bug is with us for at least couple days since I also tested it on d123c89c5802777e02402108d9271ed2f29368fe. 
Because of this bug it's impossible to use inherited scene feature (don't know any workaround).

*Further notes:*
**I have found commit that introduced this issue:** Issue was introduced in 884d5a0f41032a9c5c793577b82998998b3f87a0 commit. In fba1842b111420d75cfabc9dc4f240965cb085fe it's working fine.
It seems the bug is during writing/saving the scenes since I'm able to open scenes saved with little older Godot versions.

*Steps to reproduce:*
1. Create new scene, name it "BaseScene.xscn", put one node inside
2. Create inherited scene with base as "BaseScene.xscn", add one node.
3. Save it as "InheritedScene.xscn"
4. Close tabs and try to reopen "InheritedScene.xscn"

*TestCase project:*
https://dl.dropboxusercontent.com/u/168251/godot/some/issues/InheritanceSceneError.7z
*Quick prof video:*
https://youtu.be/xziKXmWDFZ4

Edit:
Here is godot editor console log when trying to open inherited scene:
```
ERROR: set_current_tab: Index p_current out of size (get_tab_count()).
   At: scene/gui/tabs.cpp:500.
TextureButton: 16,-4
Label: 128,63
HBoxContainer: 59,25
ERROR: remove_scene: Index p_idx out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:475.
```

Looks like it might be related to: https://github.com/godotengine/godot/issues/2611

**Comment by eska014** [comment]
Guess this is the same as #2618. Looks like I slightly misdiagnosed the issue, editing the base scene is indeed not necessary.

**Comment by kubecz3k** [comment]
@eska014 Oh didn't seen this one, I will close my issue then, will add my notes to your issue

**Comment by kubecz3k** [comment]
From my investigation it looks like the issue was introduced in 884d5a0f41032a9c5c793577b82998998b3f87a0 commit.

**Comment by jackmakesthings** [comment]
Is there any info on this new inherited scene feature? I just noticed it in the menu but can't find any details on how it works (or is supposed to work).

**Comment by neikeq** [comment]
Did commit 7aa39b7 fix this issue?

**Comment by reduz** [comment]
I think this was fixed

On Wed, Dec 2, 2015 at 8:09 PM, Ignacio Etcheverry <notifications@github.com

**Comment by kubecz3k** [comment]
Compiled 68d3438a9351498909ffa0bfe79f51b74004e906 today. It looks like this issue is fixed. Thanks a lot!
