### ISSUE TITLE
Scene Preview thumbnails have red tint [GLES2, Win7, Intel G41]

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot#26952]
**Godot version:**

Godot rc2

**OS/device including version:**

Windows 7
GLES 2
Intel g41 express chipset(old)

**Issue description:**

The main scene:
![image](https://user-images.githubusercontent.com/47214394/54178731-c7509c00-44bc-11e9-95fb-1849d7d7cbc4.png)
The save as scene dialogue:
![image](https://user-images.githubusercontent.com/47214394/54178757-d9cad580-44bc-11e9-9e1d-e43dd09db0d9.png)
Preview from other scene:
![image](https://user-images.githubusercontent.com/47214394/54178777-ea7b4b80-44bc-11e9-871c-c7348bcd4355.png)

I have tried this on multiple projects and I am getting this on all of them. The gameplay or anything visible to a player is nice, just a editor problem.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by nikhilCad** [comment]
@akien-mga I think that this issue has gone unnoticed. Sorry for inconvenience.

**Comment by qarmin** [comment]
Can't reproduce on Ubuntu 18.04 GTX 970

**Comment by aaronfranke** [comment]
Can you test on Linux? Older Intel GPUs are known to have really bad Windows drivers.

**Comment by akien-mga** [comment]
This might work better in 3.2 as some fixes were done for low end hardware, but it's unlikely that more work will be done for chipsets such as Intel G41 on Windows 7.

This configuration is the definition of the proverbial "toaster", and not worth the effort needed to work around driver bugs, if possible at all. Sorry about that :/

As mentioned, Linux might be a relief if you want to use this device for gamedev though, as it has much better OpenGL drivers for older Intel devices than Windows does.

**Comment by nikhilCad** [comment]
It is actually fixed on Linux Mint. Thank you for the advice. Blender 2.79 is working too! I can not ditch windows though
