### ISSUE TITLE
Segfault in RasterizerSceneGLES3::_render_geometry on Adreno 530

### ISSUE THREAD

**Issue by roberthofstra** [godotengine/godot#26956]
**Godot version:**
3.1   commit  7052ddd

**OS/device including version:**

Android Asus Zenphone AR
2019-03-11 11:21:30.108 14815-14881/com.godot.game I/Adreno: QUALCOMM build                   : 8740a27, Ie4d56a70f3
    Build Date                       : 11/22/16
    OpenGL ES Shader Compiler Version: XE031.09.00.03
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2019-03-11 11:21:30.112 14815-14881/com.godot.game I/OpenGLRenderer: Initialized EGL, version 1.4
2019-03-11 11:21:30.112 14815-14881/com.godot.game D/OpenGLRenderer: Swap behavior 1
2019-03-11 11:21:30.124 14815-14880/com.godot.game W/GodotView: creating OpenGL ES 3.0 context :
2019-03-11 11:21:30.151 14815-14880/com.godot.game I/godot: OpenGL ES 3.0 Renderer: Adreno (TM) 530

**Issue description:**
Crash direct when loading scene.

**Steps to reproduce:**
At startup SEG after splash screen:
Signal: SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x44))

Stacktrace:
EsxGfxMem::UpdateTimestamp(EsxContext const*, EsxAccessType, EsxBucketIdReference*) 0x0000007fa0857488
EsxCmdMgr::GfxMemReferenced(EsxGfxMem*, EsxAccessType) 0x0000007fa0840df4
A5xProgram::GenerateShaderCBSlotState(A5xContext*, EsxCmdBufType, EsxCompiledHwShaderType, unsigned int, A5xShaderCBSlotState*) const 0x0000007fa094ca20
A5xPipeline::WriteUboState(A5xContext*, EsxCmdBufType, EsxCompiledHwShaderType, unsigned int, A5xStateBuffer*) 0x0000007fa09479f8
A5xContext::ValidateState(EsxDrawDescriptor const*) 0x0000007fa0962f74
A5xContext::HwValidateGfxState(EsxDrawDescriptor const*) 0x0000007fa0962720
EsxContext::ValidateGfxState(EsxDrawDescriptor const*) 0x0000007fa0766c4c
EsxContext::DrawElementsInstanced(EsxPrimType, unsigned int, EsxPixType, void const*, unsigned int, int) 0x0000007fa075c298
RasterizerSceneGLES3::_render_geometry(RasterizerSceneGLES3::RenderList::Element*) rasterizer_scene_gles3.cpp:1560
RasterizerSceneGLES3::_render_list(RasterizerSceneGLES3::RenderList::Element**, int, Transform const&, CameraMatrix const&, unsigned int, bool, bool, bool, bool, bool) rasterizer_scene_gles3.cpp:2251
RasterizerSceneGLES3::render_scene(Transform const&, CameraMatrix const&, bool, RasterizerScene::InstanceBase**, int, RID*, int, RID*, int, RID, RID, RID, RID, int) rasterizer_scene_gles3.cpp:4432
VisualServerScene::_render_scene(Transform, CameraMatrix const&, bool, RID, RID, RID, RID, int) visual_server_scene.cpp:2159
VisualServerScene::render_camera(RID, RID, Vector2, RID) visual_server_scene.cpp:1729
VisualServerViewport::_draw_viewport(VisualServerViewport::Viewport*, ARVRInterface::Eyes) visual_server_viewport.cpp:70
VisualServerViewport::draw_viewports() visual_server_viewport.cpp:306
VisualServerRaster::draw(bool, double) visual_server_raster.cpp:106
VisualServerWrapMT::draw(bool, double) visual_server_wrap_mt.cpp:102
Main::iteration() main.cpp:1897
OS_Android::main_loop_iterate() os_android.cpp:308
::Java_org_godotengine_godot_GodotLib_step(JNIEnv *, jobject) java_glue.cpp:997
step 0x0000007fae490910
art_quick_invoke_static_stub 0x0000007faf2b2c6c
art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*) 0x0000007faf2bf6b4
art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x0000007faf46d2e8
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007faf4662c4
bool art::interpreter::DoInvoke<(art::InvokeType)0, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007faf498eb0
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x0000007faf48c0d4
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x0000007faf440558
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x0000007faf446250
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007faf4662a8
bool art::interpreter::DoInvoke<(art::InvokeType)4, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007faf498674
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x0000007faf48c324
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x0000007faf440558
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x0000007faf446250
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007faf4662a8
bool art::interpreter::DoInvoke<(art::InvokeType)1, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007faf497b20
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x0000007faf48a5f4
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x0000007faf440558
artQuickToInterpreterBridge 0x0000007faf726324
art_quick_to_interpreter_bridge 0x0000007faf2bc0b0
art_quick_invoke_stub 0x0000007faf2b29b8
art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*) 0x0000007faf2bf684
art::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::ArgArray*, art::JValue*, char const*) 0x0000007faf606f1c
art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*) 0x0000007faf608224
art::Thread::CreateCallback(void*) 0x0000007faf6275f4
__pthread_start(void*) 0x0000007fafdcd5ec
__start_thread 0x0000007fafd82f1c

**Minimal reproduction project:**
Simple 3D with cube and camera
[simple.zip](https://github.com/godotengine/godot/files/2955681/simple.zip)

**Comment by bruno-reload** [comment]
Hey man, try to create a simple empty scene with just the environment, if your scene crashes, close those issues and wait for this issue to close https://github.com/godotengine/godot/issues/26924, this is probleme in  adreno

**Comment by roberthofstra** [comment]
I tried a simple empty scene, no crash only a black screen.

**Comment by clayjohn** [comment]
This is an issue with Adreno supporting GLES3. This is why we are moving to Vulkan for 4.0. unfortunately, that means we won't be fixing this issue.
