### ISSUE TITLE
Missing "track_get_key_indices"-methods for TYPE_AUDIO, TYPE_ANIMATION, ...

### ISSUE THREAD

**Issue by TypeOverride** [godotengine/godot#26950]
**Godot version:**
Godot 3.1 Beta 11

**OS/device including version:**
Windows 7

**Issue description:**
I was looking on the Animation class for a method to get key indices in a range for TYPE_ANIMATION. 
I tried "value_track_get_key_indices". But in C++ Engine Code i saw this:
 
```
void Animation::value_track_get_key_indices(int p_track, float p_time, float p_delta, List<int> *p_indices) const {

	ERR_FAIL_INDEX(p_track, tracks.size());
	Track *t = tracks[p_track];
	ERR_FAIL_COND(t->type != TYPE_VALUE);

        ....
```
(with ERR_FAIL_COND(t->type != TYPE_VALUE); is blocking other TYPES of Tracks)

So i can not use it for Animation Tracks.

So i guess that the methods:
**animation_track_get_key_indices
audio_track_get_key_indices**
are missing

or maybe the value_track_get_key_indices has to be opened for it!? 

**Steps to reproduce:**
Try to find via GDScript key indices you placed on an AnimationTrack.
-> you will not find a method for this

**I can implement them. Thats no problem. But devs, do you ever looked into all the Boilerplate-Code that is in the Animation classes?**

Thats horrorable.

method_track_get_key_indices and  value_track_get_key_indices are so similar like hell. Like much other code there. Why are they not more generalized? This will produce bugs in the future! Code-Update-Bugs or how you call it. I would remove all the Boilerplate-Code first. Looking for commonalities on the code to simplify it and make it less buggy on changes.

**Comment by clayjohn** [comment]
If you think you know how to improve the animation classes, then please do! We are always happy for new users to contribute back to the engine codebase if they can. 😄

**Comment by TypeOverride** [comment]
> If you think you know how to improve the animation classes, then please do! We are always happy for new users to contribute back to the engine codebase if they can.

i already did improve it. There is a big major bug as well. Animations are not seeking well when using the Editor. But there is much more bugs. Look at my replacements and code fixes in my branch.

**Comment by TypeOverride** [comment]
What is the progress on this?

**Comment by KoBeWi** [comment]
The method no longer exists.
