### ISSUE TITLE
VS Project invalid reference to GodotSharpEditor

### ISSUE THREAD

**Issue by abgenullt** [godotengine/godot#26953]
**Godot version:**
v3.1 rc2 mono win64 and VS 2017

**Issue description:**
In the created project, the reference to GodotSharpEditor is invalid or could not be found.
![GodotSharpEditorVS](https://user-images.githubusercontent.com/34768615/54179827-3cf74080-449a-11e9-8684-bc33e066bb8d.png)

**Steps to reproduce:**
Create a blank project with a C# script and open the solution with Visual Studio.

**Comment by neikeq** [comment]
If you change the solution configuration to Tools, Visual Studio will be able to find it (since it's only reference for that config).

Any ways, this will most likely change in the future and editor code will go into a different C# project.

**Comment by abgenullt** [comment]
Ah ok, I see.. that is good to hear. I missed the additional build configuration of the project. Thank you.
