### ISSUE TITLE
Godot Editor crash when re-importing .ogg song that is currently playing

### ISSUE THREAD

**Issue by Yomic** [godotengine/godot#26964]
**Godot version:**
Godot 3.1 RC2

**OS/device including version:**
Win 7 Pro 64-bit, Win 8.1 Pro 64-bit

**Issue description:**
When an ogg file is playing, if you re-import it while it's playing, it freezes Godot and crashes it upon scene saving.

**Steps to reproduce:**
Open the project in Godot 3.1 RC2, High-light the AudioStreamPlayer, check the 'Playing' button in the Inspector, Highlight the .ogg file in the Filesystem window, go to the import window and change a setting and re-import the file.  This will cause only the 'Playing' button in the inspector to become unresponsive.  Further, if you try to save the scene, Godot will crash.

**Minimal reproduction project:**
[OggMusicTest.zip](https://github.com/godotengine/godot/files/2954141/OggMusicTest.zip)

**Comment by volzhs** [comment]
can't reproduce it with 3.2-alpha 48d3458f74

**Comment by KoBeWi** [comment]
I can reproduce it with 3.2 beta4. It might not happen right away, reimport it few times also toggle playing on and off and it should eventually crash. I don't get backtrace though.

**Comment by akien-mga** [comment]
Can't reproduce it either in the current master branch (bab91bd94) on Linux.
Might be due to Windows file access locking files?

**Comment by KoBeWi** [comment]
Ok, I keep getting random crashes that seem to be related to this. It's happening with OGG files and happens randomly, but it can happen to any file, i.e. usually when I add a new music file, the editor crashes even if I didn't use the audio player. Still no backtrace.

> Might be due to Windows file access locking files?

Why would it happen only to OGG files and not other resources?

**Comment by 3koozy** [comment]
Dear gents,
I have the same issue , when I try to import a (.ogg) file in the editor , it crashes right away..
Godot version : v3.2.2 stable official
OS: Windows 10 - 64-bit

* Attached ; Project folder with a (Ogg_SoundFX.ogg) file to re-produce the crash.
[Test 4 - Sound.zip](https://github.com/godotengine/godot/files/4908393/Test.4.-.Sound.zip)

**Comment by KoBeWi** [comment]
I was FINALLY able to get a stack trace for this crash:
```
godot.windows.tools.64.exe!get8(stb_vorbis * z) Line 1326 (c:\godot_source\thirdparty\misc\stb_vorbis.c:1326)
godot.windows.tools.64.exe!vorbis_find_page(stb_vorbis * f, unsigned int * end, unsigned int * last) Line 4546 (c:\godot_source\thirdparty\misc\stb_vorbis.c:4546)
godot.windows.tools.64.exe!stb_vorbis_stream_length_in_samples(stb_vorbis * f) Line 4951 (c:\godot_source\thirdparty\misc\stb_vorbis.c:4951)
godot.windows.tools.64.exe!seek_to_sample_coarse(stb_vorbis * f, unsigned int sample_number) Line 4689 (c:\godot_source\thirdparty\misc\stb_vorbis.c:4689)
godot.windows.tools.64.exe!stb_vorbis_seek_frame(stb_vorbis * f, unsigned int sample_number) Line 4867 (c:\godot_source\thirdparty\misc\stb_vorbis.c:4867)
godot.windows.tools.64.exe!stb_vorbis_seek(stb_vorbis * f, unsigned int sample_number) Line 4901 (c:\godot_source\thirdparty\misc\stb_vorbis.c:4901)
godot.windows.tools.64.exe!AudioStreamPlaybackOGGVorbis::seek(float p_time) Line 115 (c:\godot_source\modules\stb_vorbis\audio_stream_ogg_vorbis.cpp:115)
godot.windows.tools.64.exe!AudioStreamPlaybackOGGVorbis::start(float p_from_pos) Line 84 (c:\godot_source\modules\stb_vorbis\audio_stream_ogg_vorbis.cpp:84)
godot.windows.tools.64.exe!EditorAudioStreamPreviewPlugin::generate(const Ref<Resource> & p_from, const Vector2 & p_size) Line 625 (c:\godot_source\editor\plugins\editor_preview_plugins.cpp:625)
godot.windows.tools.64.exe!EditorResourcePreviewGenerator::generate_from_path(const String & p_path, const Vector2 & p_size) Line 65 (c:\godot_source\editor\editor_resource_preview.cpp:65)
godot.windows.tools.64.exe!EditorResourcePreview::_generate_preview(Ref<ImageTexture> & r_texture, Ref<ImageTexture> & r_small_texture, const EditorResourcePreview::QueueItem & p_item, const String & cache_base) Line 160 (c:\godot_source\editor\editor_resource_preview.cpp:160)
godot.windows.tools.64.exe!EditorResourcePreview::_thread() Line 255 (c:\godot_source\editor\editor_resource_preview.cpp:255)
godot.windows.tools.64.exe!EditorResourcePreview::_thread_func(void * ud) Line 100 (c:\godot_source\editor\editor_resource_preview.cpp:100)
godot.windows.tools.64.exe!Thread::callback(Thread * p_self, const Thread::Settings & p_settings, void(*)(void *) p_callback, void * p_userdata) Line 73 (c:\godot_source\core\os\thread.cpp:73)
godot.windows.tools.64.exe!std::invoke<void (__cdecl*)(Thread *,Thread::Settings const &,void (__cdecl*)(void *),void *),Thread *,Thread::Settings,void (__cdecl*)(void *),void *>(void(*)(Thread *, const Thread::Settings &, void(*)(void *), void *) && _Obj, Thread * && _Arg1, Thread::Settings && <_Args2_0>, void(*)(void *) && <_Args2_1>, void * && <_Args2_2>) Line 1614 (c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\type_traits:1614)
godot.windows.tools.64.exe!std::thread::_Invoke<std::tuple<void (__cdecl*)(Thread *,Thread::Settings const &,void (__cdecl*)(void *),void *),Thread *,Thread::Settings,void (__cdecl*)(void *),void *>,0,1,2,3,4>(void * _RawVals) Line 44 (c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\thread:44)
godot.windows.tools.64.exe!thread_start<unsigned int (__cdecl*)(void *),1>(void * const parameter) Line 97 (c:\Users\Tomek\AppData\Local\Programs\Microsoft VS Code\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp:97)
kernel32.dll!00007ffcd43d7c24() (Unknown Source:0)
ntdll.dll!00007ffcd4bed721() (Unknown Source:0)
```
Looks like it really is caused by the audio player, but it happens even when you don't use it. I just opened project and exported an OGG from Audacity and Godot crashed upon importing it.

**Comment by vvdashdash** [comment]
Importing or replacing ogg files while the editor is open still crashes consistently in godot 3.5.1.
