### ISSUE TITLE
"Use snap" button with "snap to grid" has inverted effect

### ISSUE THREAD

**Issue by hellodenq** [godotengine/godot#26968]
**Godot version:**

Godot 3.1 RC 1

**OS/device including version:**

Mac OS X 

**Issue description:**

1. if "use snap" not pressed, then object snap on move or rotate.
2. if "use snap" is pressed, then object stop snapping.

Expected snapping then pressed and not snapping then not pressed.

**Steps to reproduce:**

1. put node node
2. enable "snap to grid"
3. disable "use snap"
4. move node in scene
5. node move snapping to grid
6. enable "use snap"
7. node moving without snapping

**Minimal reproduction project:**

**Comment by qarmin** [comment]
I can't reproduce on Linux Mint
Are you sure that you don't have pressed Control(or Command) button which changes the way the snaps work?

**Comment by hellodenq** [comment]
Yes, I don't press any keys. I can't reproduce this bug after restarting Godot.

**Comment by KoBeWi** [comment]
I just found a way to reproduce it. Hold Control to invert snapping and press Alt + Tab. When you focus Godot again, the Control will be "stuck" until you press it again, resulting in behavior described in OP. Not sure how could you do that accidentally, but well, it just happened to me.

This is related to #12592

**Comment by akien-mga** [comment]
Closing as duplicate of #12592 then, it's not directly related to snapping but only to input handling when alt-tabbing.

**Comment by ScatteredComet** [comment]
I have this issue on 4.4.1 on PopOS
