### ISSUE TITLE
Editor crash when tool script replaces a resource in a variable being inspected

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#26966]
**Godot version:**
Master dev 6d86450a8356b8930b503c8ff5cc07d9e34e6287
(also reproduced in older version c23710adde23a0e415097dee7d8e6f9ba76a0970)

**OS/device including version:**
Windows 10

**Issue description:**
Replacing a resource variable through tool scripts while the previous resource is being visualized within the inspector causes a crash in the editor.

It looks like what happens is the sub-inspector for the resource is still being updated right after the resource has been deleted.

Callstack:
```
 	[Inline Frame] godot.windows.opt.tools.64.exe!List<Pair<Variant const *,Variant>,DefaultAllocator>::size() Line 410	C++
 	[Inline Frame] godot.windows.opt.tools.64.exe!OrderedHashMap<Variant,Variant,VariantHasher,VariantComparator,3,8>::size() Line 275	C++
 	godot.windows.opt.tools.64.exe!Dictionary::empty() Line 130	C++
 	godot.windows.opt.tools.64.exe!Object::get_property_list(List<PropertyInfo,DefaultAllocator> * p_list, bool p_reversed) Line 641	C++
 	godot.windows.opt.tools.64.exe!EditorInspector::update_tree() Line 1434	C++
 	godot.windows.opt.tools.64.exe!EditorInspector::_notification(int p_what) Line 2178	C++
 	godot.windows.opt.tools.64.exe!EditorInspector::_notificationv(int p_notification, bool p_reversed) Line 251	C++
 	godot.windows.opt.tools.64.exe!Object::notification(int p_notification, bool p_reversed) Line 954	C++
 	godot.windows.opt.tools.64.exe!SceneTree::_notify_group_pause(const StringName & p_group, int p_notification) Line 958	C++
 	godot.windows.opt.tools.64.exe!SceneTree::idle(float p_time) Line 518	C++
 	godot.windows.opt.tools.64.exe!Main::iteration() Line 1885	C++
 	godot.windows.opt.tools.64.exe!OS_Windows::run() Line 2819	C++
 	godot.windows.opt.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 151	C++
 	godot.windows.opt.tools.64.exe!_main() Line 175	C++
 	godot.windows.opt.tools.64.exe!main(int _argc, char * * _argv) Line 185	C++
```

**Steps to reproduce:**
- Open the attached project
- Select the node called "Node" in the scene
- Click the resource in the inspector to visualize it
- Check the bool variable called "Change Resource" in the inspector
- Observe a crash in EditorInspector::update_tree()

**Minimal reproduction project:**
3.2 - [test-res-crash.zip](https://github.com/godotengine/godot/files/2957392/test-res-crash.zip)
4.0 - [test-res-crash-4.0.zip](https://github.com/godotengine/godot/files/5632988/test-res-crash-4.0.zip)

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3
Not sure how to make the script work on master.

**Comment by pouleyKetchoupp** [comment]
Still reproducible in master 2a0de6d88cfdc7cbd42e448fd44f1fbc438b320c, added MRP with updated gdscript.

**Comment by timothyqiu** [comment]
The MRP does not crash the editor now for current 3.x (ffea68a4e883959c6e7d153f815af980976489b7) and master (3990152f6b7fcbac39ed68f0cc0fd36131bc9e2f). Seems fixed.
