### ISSUE TITLE
Code-Editor improvement suggestions

### ISSUE THREAD

**Issue by PelegMedia** [godotengine/godot#26973]
**Godot version:**
3.x

**OS/device including version:**
Not relevant

**Issue description:**
The GODOT editor UI is still missing some features already existing in almost any modern code editor. 
The code editing is the complex part of the engine, but also the one who makes it so powerful and beyond creating simple template games as done by all the game makers tools.

The following features should help reducing editing time:

1. Please add search & replace history so we won't need to type the same search terms repeatedly.
   It should probably save the last X search/replace texts.
2. Search & replace texts should remain when switching between source files. 
Today it looks like a bug and very frustrating.
3. Search & replace - current-match is hard to see. As the editor marks all the occurrences of a search, the current match looks the same as all the other occurrences.
   Need to do something to make it stand forward, especially when there are couple of matches on the same line.
4. Search & replace texts with regular-expressions (Advanced feature)
5. Show Debug-Line-Marker. 
   It is hard to know the debugger's current line. A single click to focus on the editor moves the current line marker away from the debug line.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Please open one issue per suggestion (after checking for duplicates) so it's easier to discuss them individually :slightly_smiling_face:

**Comment by KoBeWi** [comment]
Also check this: #2982

> When we close the editor it should save the open-scenes to the project and re-open them next time we launch the project.

Editor Settings -> Interface -> Scene tabs -> Restore Scenes On Reload

**Comment by PelegMedia** [comment]
Thanks @KoBeWi , I found it in the settings and removed from the list.
Is it OFF by default for a particular reason? It looks like a good feature which should be ON by default.

**Comment by PelegMedia** [comment]
Hi @Calinou , I did a single list to have all in one place and once it will be complete and I will see that it has no duplicates I will separate it to several issues.
Thanks.

**Comment by KoBeWi** [comment]
> Is it OFF by default for a particular reason? It looks like a good feature which should be ON by default.

The reason is that if you have lots of opened scenes and they are big, it causes long startup time of editor. At least that's the reasoning from people against having it ON by default.

**Comment by Jackain** [comment]
I would love being able to open a second GDscript window on my second monitor

**Comment by PelegMedia** [comment]
> The reason is that if you have lots of opened scenes and they are big, it causes long startup time of editor. At least that's the reasoning from people against having it ON by default.
Yes that makes sense.  Thanks again for that.

**Comment by PelegMedia** [comment]
> I would love being able to open a second GDscript window on my second monitor

There is an open issue about it - #9059

**Comment by PelegMedia** [comment]
Opened issue per each item in the list.
Thanks.
