### ISSUE TITLE
FPS value in AnimatedSprite (2D) applied to wrong animation when switching to another

### ISSUE THREAD

**Issue by txigreman** [godotengine/godot#26979]
**Godot version:**
3.1-RC3

**OS/device including version:**
Windows 10

**Issue description:**
If you have 2 animations in a AnimatedSprite (2D) with the same FPS value, and you try to change the FPS of one of them, and then you click in the second one, then the FPS change is wrongly applied to second one.

If the animations do not have the same FPS value them the change is omitted/discarded and both animations preserve the original value.

**Steps to reproduce:**
1. Create a AnimatedSprited (2D).
2. Assign a new SpriteFrames.
3. Click on the SpriteFrames to open the panel.
4. Create 2 animations.
5. Click in the first one.
6. Change the FPS value. Do not press enter key.
7. Click in the other animation.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2958059/Test.zip)

**Comment by bojidar-bg** [comment]
Can confirm.
(psst, there is no need to submit the new project template as a MRP. Just say works from a blank project)

**Comment by freestraws** [comment]
Can I take this on as my first issue here?
I think I'd be tweaking [this function](https://github.com/godotengine/godot/blob/7018de8425e8c2781071595fdcf565acdfde2be4/editor/plugins/sprite_frames_editor_plugin.cpp#L461) so that before reassigning `edited_anim` to the newly selected animation, I would check if the current `edited_anim`'s FPS value has changed and call `_animation_fps_changed` with the new value if so.

**Comment by freestraws** [comment]
I could also do `anim_speed->release_focus()`, but since `_update_library` changes `anim_speed` before the `focus_exited` signal gets processed that won't work unless I defer the call to `_update_library`.
Not sure which way would be better or if it makes much of a difference in the end?

**Comment by freestraws** [comment]
I did it the first way I mentioned, without release_focus, since I wasn't sure how to defer the change of `edited_anim`, but if anyone thinks that'd work better, I can change it.
