### ISSUE TITLE
Implement scale up and down field values with MouseWheel/Up and Down keys and controls

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26975]
**Godot version:**
3.1 rc2

**OS/device including version:**
Windows 10 x64

**Issue description:**

![image](https://user-images.githubusercontent.com/11199752/54217096-c07c5600-44c9-11e9-8316-bfc436d34ac8.png)

To further facilitate the user interface, I suggest implementing additional ways of modifying values within the numeric fields of the inspector and others.
Fields that do not have a limit value (as in the case of the slider) can currently only be typed manually.
This causes slowness, especially when you want to experience dimensional variations.
I know that many of these variations can be done directly on the node image, but this would be an additional facility, interacting with the numeric fields..
This is something that is already used in various softwares as a great help.

**Steps to reproduce:**

Suggestions:

1. **MouseWheel**: When clicking on the numeric field, MouseWheel could increase or decrease a specific amount of the value (which could be configured in the Editor Settings)
2.  **Up and Down keys**: In the same way, when the focus in on the numeric field, pressing Key Up ou Key Down could also increase or decrease the values.
3. **Up and Down controls**:  
![image](https://user-images.githubusercontent.com/11199752/54217837-1e5d6d80-44cb-11e9-947b-d6efb4bb9625.png)
Like this image, when clicking on the + or - buttons.

Creating these tree ways, independently configurables in Editor Settings, you can provide more flexibilities to the developers.

**Comment by Calinou** [comment]
While this issue contains useful information, there's a similar discussion ongoing in https://github.com/godotengine/godot/issues/17371 so I'll close this one. Please continue the discussion there :slightly_smiling_face:
