### ISSUE TITLE
Please can anyone explain this

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#26981]
**Godot version:**
RC 3

**OS/device including version:**
win 10 64bit

**Issue description:**
Please can anyone explain why godot shows a list of properties instead of list of functions when drag node from Scene tab ?
(I did report but its not labled as bug)

![image](https://user-images.githubusercontent.com/41632592/54230525-78c3f180-44fe-11e9-97fa-e825831841cf.png)

**Comment by Chaosus** [comment]
No, its not a way how the issue tracker works - you cannot ask direct questions in tracker - you've create them to fix problem(if you think its a bug or it need to get enchancement) and others are trying to solve it. Seems like you've been already created the issue about this in #26717 - so keep discussion in there. Ask questions on appropriate channels - such as IRC or Discord.
