### ISSUE TITLE
First Ctrl+R and Ctrl+F not showing long name variables correctly

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26982]
**Godot version:**
3.1 rc2

**OS/device including version:**
Windows 10 x64

**Issue description:**
When trying to replace a long name variable for the first time section in GDScript editor, the cursor positioned at the end but the displayed name is shifted to the left and not appear correctly.
Pressing Ctrl+R again, it shows correctly.

**Steps to reproduce:**

1. Double click on a variable with a long name
![image](https://user-images.githubusercontent.com/11199752/54233728-4e693880-44ec-11e9-88a1-a8ba65354570.png)

2. Press Ctrl+R
![image](https://user-images.githubusercontent.com/11199752/54233756-6345cc00-44ec-11e9-9486-e977f5b12d99.png)

3. Press Ctrl+R again
![image](https://user-images.githubusercontent.com/11199752/54233839-8f614d00-44ec-11e9-9c30-ceefdd4e0fcb.png)

**Minimal reproduction project:**

[New Game Project.zip](https://github.com/godotengine/godot/files/2958674/New.Game.Project.zip)

**Comment by piyushdagar** [comment]
Also happens with Ctrl+F

**Comment by piyushdagar** [comment]
It actually got slide to the left...probably some mismatch between cursor_pos and window_pos in line_edit.cpp. I am trying to solve....
![Peek 2019-03-13 19-17](https://user-images.githubusercontent.com/30121673/54283986-2699d380-45c5-11e9-81e3-5b99a9fe368e.gif)

**Comment by Tornadowarnung** [comment]
To me it seems like `window_width` doesn't get set corretly when `LineEdit::set_cursor_position(int p_pos)` is called the first time.

This is where the variable is initially set with a smaller value than expected:
https://github.com/godotengine/godot/blob/260530f01caa8ea3e2fb7bfda04f4bd718ae14f5/scene/gui/line_edit.cpp#L1171

I'll try to find out more though ...

**Comment by Tornadowarnung** [comment]
The problem seems to occur whenever the LineEdit is resized. This happens when the search bar is initially created and when the width is resized as @piyushdagar already mentioned.

Hence I looked at this piece of code:
https://github.com/godotengine/godot/blob/90cc1d3c1d2e77ca72c5949b21a5c40738abcd81/scene/gui/line_edit.cpp#L615
Why is the window_pos only set to zero when it should expand to text length?
Always resetting window_pos seems to solve this issue
