### ISSUE TITLE
move_and_slide makes bodies overlap 

### ISSUE THREAD

**Issue by Araken** [godotengine/godot#26983]
**Godot version:**
First appeared in Godot 3.1 Beta 6, still the same on Godot 3 RC 3

**OS/device including version:**
Arch Linux

**Issue description:**
When I'm using the move_and_slide function with changing linear_velocity parameter, the body tends to go "inside" of other bodies in an unexpected manner. It never happened to me in Godot versions before Beta 6.

**Steps to reproduce:**
Use keys WSAD to control player. When the player lands on the ground press S to increase velocity.y, player should then fall a bit into the ground.

**Minimal reproduction project:**
[move_and_slide_minimal.zip](https://github.com/godotengine/godot/files/2958733/move_and_slide_minimal.zip)

**Comment by j-oh** [comment]
Also having this issue, game physics worked fine on 3.0.6 and 3.1 beta 5, doesn't work on 3.1 stable or any later beta versions. Any updates on this?

**Comment by takhimi** [comment]
Maybe related with this bug also ? Please take a look at 2D and 3D Kinematic overlapping issues here also. https://github.com/godotengine/godot/issues/27652

**Comment by akien-mga** [comment]
Doesn't seem reproducible in the current master branch, it must have been fixed since then.
