### ISSUE TITLE
Wrong type is shown in tooltip of custom not in scene tree

### ISSUE THREAD

**Issue by Redwan13** [godotengine/godot#26980]
**Godot version:**
Godot 3.1 RC3

**OS/device including version:**
MacOSX 10.14.3

**Issue description:**
In editor in scene tree if user adds registered class node, tooltip will show base class as type.

**Steps to reproduce:**

1. Create script.
2. Register it as class.
3. Add node of this class to scene.
4. Loot at the tooltip. 

**Minimal project**

```
extends Node

class_name MyCustomNode

func _ready():
    pass
```

**Comment by bojidar-bg** [comment]
Strongly related to #6067. Custom node types are just shortcuts for assigning a script to a node of the base type.

**Comment by aaronfranke** [comment]
See also: https://github.com/godotengine/godot/issues/16863#issuecomment-491421079
