### ISSUE TITLE
Add support for Previous/Next mouse buttons

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#26999]
**Godot version:**
3.1

**OS/device including version:**
no matter

**Issue description:**
The previous and next mouse buttons(Button4 / Button5) aren't recognized by Godot and cannot be added to shortcuts or used in games. I have the mouse with these buttons, and its supported in many games so I maked this request to add support for them in Godot.

**Comment by bruvzg** [comment]
At least on macOS mouse buttons 4/5 are detected by Godot as `InputEventMouseButton` with button indices `BUTTON_XBUTTON1` and `BUTTON_XBUTTON2`

**Comment by Chaosus** [comment]
huh.. then it looks like Windows only bug.. and on Linux ?

**Comment by Chaosus** [comment]
Ah.. didnt correctly checked.. its work
