### ISSUE TITLE
[Regression] Imported rigged mesh (from .escn) deforms badly

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#26997]
**Godot version:**
`master` / 4326fd5a7

**OS/device including version:**
Manjaro Linux 18.0.4

**Issue description:**
I wanted to see if there is any last minute regression before 3.1 stable gets released, so I updated from 8b231b9, and now my rigged character that is imported from .escn asset looks like this:

![image](https://user-images.githubusercontent.com/2367032/54251626-3399d100-458b-11e9-90bf-85d7936a2254.png)

I tried to delete the generated .mesh and reimported it, but the problem persists.

When the mesh also looks deformed in editor after the reimport: 

![image](https://user-images.githubusercontent.com/2367032/54251769-a3a85700-458b-11e9-8791-05a6963919c2.png)

**Comment by mysticfall** [comment]
And when I tried to export the model again and reimport it in Godot, it became this:

![image](https://user-images.githubusercontent.com/2367032/54252281-85435b00-458d-11e9-8a3a-e056d48cd3a8.png)

On a side note, I have a problem with Godot Blender exporter which produces a similar looking output with the last screenshot in the issue description:
https://github.com/godotengine/godot-blender-exporter/issues/172

But before the update, it never actually affected the exported .escn file so it looked ok in the editor and  I was able to run the game without a problem.

**Comment by mysticfall** [comment]
I have uploaded the .escn asset in question, along with the import settings here:
* https://www.dropbox.com/sh/6y8120fapth2k5r/AABV5npFk3Sh_Y5fBLr1khoOa?dl=0

**Comment by mysticfall** [comment]
My personal experience regarding the two exporters has been quite the opposite, however. Before the engine update, I didn't have any serious issues with using the Blender exporter but the Better Collada wasn't a viable option for my project.

There is an unresolved issue with the Better Collada that prevents it from exporting a model with many blend shapes, and it also doesn't support Blender 2.8. And the project hasn't been actively maintained for quite a while, so we can't expect to see these issues get resolved any time soon.

I also had some problems with the glTF exporter before, but it was a while ago so there's a chance that it has become usable by now.

But AFAIK, the Blender exporter is currently the only viable option if you have a complex model with many blend shapes, or want to use Blender 2.8.

**Comment by mysticfall** [comment]
Bisect reports that this was the first bad commit : 

> (2f32a75d2e2afc22e7e170c2506455010d063ce8) Skeletons can now choose between using local or world coords for processing, fixes #26468

**Comment by hpvb** [comment]
@mysticfall it sounds like a missing feature in the exporter if that's the first bad commit then I guess? The exporter perhaps doesn't set local or world transforms correctly?

**Comment by mysticfall** [comment]
@hpvb I suspect it could be the case. I'll try to get the attention of the devs of the exporter to this issue then.

**Comment by Jason0214** [comment]
@mysticfall 
The first two screenshots is very likely the .import cache is just invalidate and causing weird deformation.   Maybe give a try with the AABB fix? based on the third screenshots, it is very similar issue.

Besides, I checked your Character.escn on OSX, it works fine.  It reminds me of an issue related float rounding in 3.1 which cause quaternion reported as non-normalized and it happens more on Linux platform. It is also possible rounding affect bone transforms. So if there are some error log in importing the .escn, they may need some attention

**Comment by mysticfall** [comment]
Unfortunately, it seems that this issue isn't affected by the AABB fix (#27038) as I mentioned in a comment I left at the PR.

I attached a log file that I took during my test which consists of deleting existing meshes, reimporting the source .escn, changing material names (as they gets deleted), assigning them to respective mesh instances (they sometimes get cached if I don't do that), and finally run the project to see the result.

I'm not too sure if the logged messages are relevant to this issue because I believe I at least had some of them even when it worked as expected.

[out.txt](https://github.com/godotengine/godot/files/2965574/out.txt)

**Comment by fire** [comment]
Did you try toggling the boolean? 

p_skeleton->set_use_bones_in_world_transform(true);

**Comment by mysticfall** [comment]
@fire Yes, setting the property indeed fixed the problem for me! So, I assume that the exporter needs to set that property when it creates .escn file?

**Comment by Jason0214** [comment]
@mysticfall Great to know.   I will take a look at the this property afterwards to see if it can be handled in escn.

**Comment by mysticfall** [comment]
@Jason0214 Thanks much, as always :)

**Comment by Antokolos** [comment]
I can confirm that toggling this property can fix things:
![image](https://user-images.githubusercontent.com/7196697/54442717-5681dc00-4769-11e9-9cee-325fcb6b23c0.png)
![image](https://user-images.githubusercontent.com/7196697/54442734-5eda1700-4769-11e9-872e-0f5f629df3b0.png)
There is 82 escns in our project... Uh-oh, there will be a lot of monkey-work then...

**Comment by Ace-Dragon** [comment]
It looks like the exporter was fixed.
https://github.com/godotengine/godot-blender-exporter/commit/22d2f396d9b6c3384e9d4dcfd913d53ea61203c3

If you already updated some assets to get the problem, just re-import them.

**Comment by Antokolos** [comment]
Wow, great, thanks!
@Jason0214 , thank you for your work, as always! :)

**Comment by mysticfall** [comment]
Maybe we can close this issue now, as it turned out a problem with the exporter and it's confirmed to be fixed?
