### ISSUE TITLE
nvidia geforce/nforce drivers problems clash

### ISSUE THREAD

**Issue by hyperJJmaster** [godotengine/godot#26994]
**Godot version:**
godot engine 3.1 rc3

**OS/device including version:**

windows 7 x64
nividia nforce 430a/geforce 6150se

**Issue description:**
![image](https://user-images.githubusercontent.com/24927155/54249420-24c10900-450e-11e9-8930-7f8500f73a9f.png)

**Steps to reproduce:**
just import or create new proyect and edit

**Minimal reproduction project:**

**Comment by hyperJJmaster** [comment]
update: installing the oficial video card drivers of nvidia and not windows update drivers. fix the problem

**Comment by groud** [comment]
Closing then, as the problem comes from nvidia.
