### ISSUE TITLE
F3 doesn't return to the editor while inside Help (F4)

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26991]
**Godot version:**
3.1 rc2

**OS/device including version:**
Windows 10 x64

**Issue description:**
While I'm on GDScript editor and I press F4 (Help), to go back to the editor I always need to use the mouse to click on the ".gd" file name or on click on the left arrow in the upper right corner of the help.
While inside help, F3 doesn't return to the editor. 

**Steps to reproduce:**

- Press F4 (or Ctrl+Click over an instruction) to open the help
- While inside help, press F3 and it will not return to the editor

**Comment by qarmin** [comment]
For me this isn't a bug.
F4 just open a help dialog which open help page in Script Editor, so pressing F3 do nothing, because you are already in Script Editor.

**Comment by rogeriodec** [comment]
> For me this isn't a bug.
> F4 just open a help dialog which open help page in Script Editor, so pressing F3 do nothing, because you are already in Script Editor.

Still, this makes it difficult for the user, who will not have a keyboard shortcut to go back to the editor and need to use the mouse every time he queries the help.
This can be improved.

**Comment by vorabrijesh** [comment]
Doesn't  esc key get back to script editor.

**Comment by dreamsComeTrue** [comment]
After Help page is displayed in the Script Editor, you can always "CTRL+w" to close that opened page, to return where you left.

**Comment by Calinou** [comment]
I guess we can make the user go back to the tab they were previously on if they hit the shortcut associated with the tab while they're already on the tab.

**Comment by KoBeWi** [comment]
Working as intended, open a [proposal](https://github.com/godotengine/godot-proposals) if you have specific solution in mind.
