### ISSUE TITLE
Freeze the debugger variable inspector scrolling position while debugging

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26993]
**Godot version:**
3.1 rc2

**OS/device including version:**
Windows 10 x64

**Issue description:**
While debugging, I want to watch one variable that is located below the first visible variables in the inspector.
So I scroll the inspector down until it shows me the desired variable.
But if I click in the "continue" button, the variable inspector scroll back to the first variables again.
So, on each "continue", I have to scroll to the desired variable again.

**Steps to reproduce:**
- Have a code with multiple variables
- Set a breakpoint in any line
- Start debugging
- The debugger will show the first variables:
![image](https://user-images.githubusercontent.com/11199752/54247090-62c22b00-4516-11e9-8101-dc66f05e6702.png)
- But I want to follow the 'x' variable, so I scroll down:
![image](https://user-images.githubusercontent.com/11199752/54247113-7ec5cc80-4516-11e9-802b-c919a14f4c60.png)
- Now I want to continue the script, so I click on the "continue" button, and then the variable list is again on the beginning:
![image](https://user-images.githubusercontent.com/11199752/54247209-d2d0b100-4516-11e9-9db5-01ec520ab88c.png)

**Comment by rogeriodec** [comment]
@akien-mga Could you tag this issue (and some remaining issues that are not tagged yet in https://github.com/godotengine/godot/issues/created_by/rogeriodec)?

**Comment by erammos** [comment]
Hi,
Every debug action (step over, continue etc) resets/clears debugger's inspector. That causes a flickering effect also. I am investigating it.

**Comment by akien-mga** [comment]
Fixed by #28407.
