### ISSUE TITLE
Reflection probes too shiny when glow enabled on 3.1 stable after the scene is saved

### ISSUE THREAD

**Issue by yaelatletl** [godotengine/godot#26998]
**Godot version:**
RC3, 3.1 stable

**OS/device including version:**
Intel HD Graphics 520, Windows 10 

**Issue description:**
When used with glow in additive mode, reflection probes show lights like this picture:
![imagen](https://user-images.githubusercontent.com/28612272/54252901-4623f400-4512-11e9-9ace-944451472046.png)

Disabling glow will show that the light inside the probe is not what you get in game (and also monochromatic) : 
![imagen](https://user-images.githubusercontent.com/28612272/54253049-ea0d9f80-4512-11e9-945f-5eafd112a8b2.png)

In game: 
![imagen](https://user-images.githubusercontent.com/28612272/54253238-ba12cc00-4513-11e9-8b79-6d43bbf2ef68.png)

**Steps to reproduce:**
Create a scene, place some lights and a reflection probe. 
Set a world environment with additive glow. 
Save the scene, close the project and open it again. Now it shines like the sun. 

**Minimal reproduction project:**

**Comment by yaelatletl** [comment]
Additional info: Looking to these exaggaratedly illuminated areas make fps drop to 2-10 
please @akien-mga or someone, help :c

**Comment by yaelatletl** [comment]
~Additional info: Looking to these exaggaratedly illuminated areas make fps drop to 2-10~
Correction: The issue was that one of them were set to always update, that's why it dropped the frames, in other news, tested with various versions and the problem seems to vary between beta 4 and 6, in beta 5 reflections stop working at all, seems related to 
8fd2eb6

**Comment by yaelatletl** [comment]
Even more information: I was unable to replicate the issue on Linux, using latest mesa drivers. This seems to be windows only

**Comment by clayjohn** [comment]
Can you reproduce in 3.1.2 or in 3.2beta?

**Comment by clayjohn** [comment]
Closing for now. If anyone can reproduce, I can reopen.
