### ISSUE TITLE
Godot see override of `_init()` in inheriting class as this func call

### ISSUE THREAD

**Issue by jebedaia360** [godotengine/godot#27001]
**Godot version:**
Godot 3.1_rc3 and previous versions of Godot 3.1

**OS/device including version:**
Linux

**Issue description:**
When I try to override of `_init()` func in class that inherits for my other class Godot editor see it as error:
 `Parse Error: Too few arguments for '_init()' call. Expected at least 2.`
Where `2` is number of arguments.

**Steps to reproduce:**
You need 2 scripts:
```
#First script
extends Object
class_name MyObject

func _init(a, b):
  pass

#Second script
extends MyObject

func _init(a):
  ._init(a, null)
```

**Comment by MidZik** [comment]
Init syntax is different:
```
#First script
extends Object
class_name MyObject

func _init(a, b):
  pass

#Second script
extends MyObject

func _init(a).(a, null):
  pass
```
https://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#class-constructor

**Comment by jebedaia360** [comment]
Ok, thanks it is strange, but there is not bug then I will close it.
