### ISSUE TITLE
Search and replace - current-match is hard to see

### ISSUE THREAD

**Issue by PelegMedia** [godotengine/godot#27004]
**Godot version:**
3.1

**OS/device including version:**
Not relevant

**Issue description:**
Search & replace - current-match is hard to see. 
As the editor marks all the occurrences of the search, the current match looks the same as all the other occurrences.
Need to do something to make it stand forward, especially when there are couple of matches on the same line. Maybe give a different color.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by siddharth952** [comment]
I'll try to fix this.

**Comment by PelegMedia** [comment]
Thank you @siddharth952

**Comment by piyushdagar** [comment]
You can tweak in Search Result Color, Search Result Border Color and Word Highlighted Color in Editor Settings->Text Editor->Highlighting.
![Peek 2019-03-15 08-43](https://user-images.githubusercontent.com/30121673/54406174-1c7bf000-46ff-11e9-90ee-c18ea491c04c.gif)

**Comment by piyushdagar** [comment]
However the default colors should to be changed. Should I change them as in above gif?

**Comment by PelegMedia** [comment]
The about settings is better and should be the default.
Thanks
