### ISSUE TITLE
Show Debug-Line-Marker

### ISSUE THREAD

**Issue by PelegMedia** [godotengine/godot#27006]
**Godot version:**
3.1

**OS/device including version:**
Not relevant

**Issue description:**
Show Debug-Line-Marker.
It is hard to know the debugger's current line. A single click to focus on the editor moves the current line marker away from the debug line and the only place to know where you are appear in the stack call.
It requires a marking such as done for break-point which moves as you run the code, especially line by line, regardless of the current line highlight.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Paulb23** [comment]
I believe this is now fixed by #28101
