### ISSUE TITLE
Godot scale godot logo according to Editor Scale when creating new project

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#27009]
**Godot version:**
Godot 3.1 RC 3

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When I create new project, then godot create logo according to editor scale.
I use godot with editor scale 0.8, so godot create logo with size 51x51.

As I know, in some situations only textures which have resolution with size of power 2 (32,64,128) can be used, so to create simple project, godot should provide this type of texture.

I think that chosen resolution should smallest power of 2 which is greater than 64 * EDSCALE (51 -> 64, 65 -> 128, 156 -> 256 )

**Comment by mikeepiazza** [comment]
Replicated issue, working on it now.

**Comment by akien-mga** [comment]
Still reproducible in 3.2.2 RC 2 (ae59e22cdd7101d85bcb92871ce53f05c668f5c4).

**Comment by akien-mga** [comment]
IMO the editor scale shouldn't impact what `logo.png` gets generated, it should always be a fixed size. A given project can be used on different configurations with different editor scales, there's no reason for the default project files to reflect a specific creation configuration.
