### ISSUE TITLE
Module through export

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#2701]
Why do we have to recompile godot to have a module work? How about if instead of having to put the module in the modules folder and compile we can add the files in export when we want to release a game and have the module files added into the project.

**Comment by neikeq** [comment]
How would that work? If you mean dynamic linking, Juan explained that was not possible due to binary compatibility (C++ has no standard ABI). A module compiled with gcc may not be compatible with an template compiled with clang or Visual Studio.

**Comment by akien-mga** [comment]
Yeah I don't see any way to make this work without compiling both the editor and the templates against the module, as done currently.

**Comment by bojidar-bg** [comment]
Just some thoughts:
  1. Dynamic linking: wouldn't it be possible by compiling a `.so`(linux), `.dll`(windows) and `.dylib`(mac), for each non-compile-time module (probably with a bit different API), to create those modules?
  2. Child processes: if it is not possible/hard to do with dynamic linking, maybe we can compile full programs (per-platform), and then spawn them as child processes, communicating with them through `stdin` and `stdout`. Would make custom modules much slower, but for some things it would be better...
