### ISSUE TITLE
OS.get_unique_id() returns fixed string "android_id" on android devices

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#27016]
**Godot version:**
3.1 release

**OS/device including version:**
running platform Android 9.0
editor platform Windows 10

**Issue description:**
OS.get_unique_id always returns the fixed string "android_id" instead of unique device id.

**Steps to reproduce:**
var deviceID = OS.get_unique_id()

**Minimal reproduction project:**
prints(OS.get_unique_id())

**Comment by burstina** [comment]
perhaps a regression from [https://github.com/godotengine/godot/issues/3628](https://github.com/godotengine/godot/issues/3628 )?

**Comment by bojidar-bg** [comment]
This is a regression from #24145, [`b385a4b`#Godot.java:424](https://github.com/godotengine/godot/commit/b385a4b053e51a7076d87c80eb53ca451d0bdfb6#diff-9dbdf00115735810f40caab7dc2b9f3eR412), cc @volzhs.

**Comment by volzhs** [comment]
@bojidar-bg Thanks for pointing it. :smile:
