### ISSUE TITLE
Mesh Instance with texture: render glitch on Android (GLES 3)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#27012]
**Godot version:**
master

**OS/device including version:**
Android (Samsung Galaxy S6), exported from Arch Linux (Antergos)

**Issue description:**

![bug](https://user-images.githubusercontent.com/34406967/54283174-c04d8a80-459d-11e9-861a-7ef4c88466eb.png)
![expected](https://user-images.githubusercontent.com/34406967/54283175-c0e62100-459d-11e9-8739-5c2d18b51a60.png)

**Minimal reproduction project:**
.apk: https://github.com/HugeGameArtGD/Solus-Stunts/releases/download/v8.0/Solus-Stunts.zip
godot project: https://github.com/HugeGameArtGD/Solus-Stunts/releases/download/v8.0/demo.zip

**Comment by LinuxUserGD** [comment]
@akien-mga Maybe related to https://github.com/godotengine/godot/issues/26185

**Comment by LinuxUserGD** [comment]
@eska-014

**Comment by LinuxUserGD** [comment]
@eska014

**Comment by LinuxUserGD** [comment]
@BastiaanOlij

**Comment by bruvzg** [comment]
Motorola Nexus 6 running LineageOS 16.0 (Android 9.0):
* Your `.apk` - distorted image identical to first screenshot
* `.apk` exported using Godot 3.1 stable (official export templates, no changes were made to export configuration) from macOS 10.14.3 - similar to second screenshot, same result for running project on macOS.

**Comment by LinuxUserGD** [comment]
I get the same result using Godot 3.1 stable on Linux with official export templates.

**Comment by LinuxUserGD** [comment]
It works when I change the scale to another value than 1 in the project settings and set the rendering (display) to viewport.

**Comment by LinuxUserGD** [comment]
I tried it again on Linux with the official Godot 3.1 download and export templates and now it's displayed correctly. Don't know why the export templates from https://hugo.pro/projects/godot-builds/ doesn't work. Will open a seperate issue for that.

**Comment by BastiaanOlij** [comment]
Might be the issue we had with the VR drivers awhile ago where floats are parsed differently between compilers. Though that was a GDNative issue, not sure how that could influence something in engine when its all compiled with the same compiler. But just throwing it out there
