### ISSUE TITLE
Android Crash on some devices GLES 2

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#27011]
**Godot version:** 3.1 rc2

**OS/device including version:** GPU Adreno 506 OS Android miui 10 android version 6.0

**Issue description:**the apk work on android 9 but not working on android 6
here is the logcat : 
03-13 20:44:26.332 27892 27924 I godot   : OpenGL ES 2.0 Renderer: Adreno (TM) 506
03-13 20:44:26.501  1486  1542 I ActivityManager: Displayed org.godotengine.newgameproject/org.godotengine.godot.Godot: +1s81ms
03-13 20:44:26.501  1486  1542 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{9fb8196 u0 org.godotengine.newgameproject/org.godotengine.godot.Godot t22296} time:18519176
03-13 20:44:26.502  3720  3877 D PowerKeeper.Event: notifyActivityLaunchTime: org.godotengine.newgameproject/org.godotengine.godot.Godot totalTime: 1081
03-13 20:44:28.589   774   774 F DEBUG   : pid: 27892, tid: 27924, name: GLThread 3589  >>> org.godotengine.newgameproject <<<
03-13 20:44:28.693   774   774 F DEBUG   :     #14 pc 00000000007cbf84  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:28.693   774   774 F DEBUG   :     #15 pc 0000000001169054  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:28.693   774   774 F DEBUG   :     #16 pc 000000000034c1e4  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:28.693   774   774 F DEBUG   :     #17 pc 00000000016ce8b8  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:28.693   774   774 F DEBUG   :     #18 pc 00000000016c3438  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:28.693   774   774 F DEBUG   :     #19 pc 00000000016c3720  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:28.693   774   774 F DEBUG   :     #20 pc 00000000008e9914  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:28.693   774   774 F DEBUG   :     #21 pc 00000000001d9be4  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:28.693   774   774 F DEBUG   :     #22 pc 00000000001a5adc  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+168)
03-13 20:44:28.693   774   774 F DEBUG   :     #23 pc 000000000027d0a8  /data/app/org.godotengine.newgameproject-1/oat/arm64/base.odex (offset 0x147000) (void org.godotengine.godot.GodotLib.step()+124)
03-13 20:44:28.693   774   774 F DEBUG   :     #24 pc 0000000000281f80  /data/app/org.godotengine.newgameproject-1/oat/arm64/base.odex (offset 0x147000) (void org.godotengine.godot.GodotView$Renderer.onDrawFrame(javax.microedition.khronos.opengles.GL10)+84)
03-13 20:44:29.312  1486 27951 W ActivityManager:   Force finishing activity org.godotengine.newgameproject/org.godotengine.godot.Godot
03-13 20:44:29.375  1486  1707 W InputDispatcher: channel '941e6f7 org.godotengine.newgameproject/org.godotengine.godot.Godot (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-13 20:44:29.375  1486  1707 E InputDispatcher: channel '941e6f7 org.godotengine.newgameproject/org.godotengine.godot.Godot (server)' ~ Channel is unrecoverably broken and will be disposed!
03-13 20:44:29.468  1486  2327 W InputDispatcher: Attempted to unregister already unregistered input channel '941e6f7 org.godotengine.newgameproject/org.godotengine.godot.Godot (server)'
03-13 20:44:29.474  3720  3877 D PowerKeeper.Event: notifyAMProcDied pacakageName: org.godotengine.newgameproject, pid:27892
03-13 20:44:29.527  1486  3436 W WindowState: Failed to report 'resized' to the client of Window{941e6f7 u0 org.godotengine.newgameproject/org.godotengine.godot.Godot}, removing this window.
03-13 20:44:29.532  2789  3006 D GameBoosterService: onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10021, mForegroundPid=2408, mLastForegroundPackageName='org.godotengine.newgameproject', mLastForegroundUid=10110, mLastForegroundPid=27892, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
03-13 20:44:36.090  3720  3877 D PowerKeeper.Event: notifyAMProcStart processName: 10110 reason: org.godotengine.newgameproject, pid:0
03-13 20:44:36.183  2789  2799 D GameBoosterService: onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='org.godotengine.newgameproject', mForegroundUid=10110, mForegroundPid=27996, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10021, mLastForegroundPid=2408, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=1}
03-13 20:44:36.254 27996 27996 D AccessibilityManager: current package=org.godotengine.newgameproject, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=false, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
03-13 20:44:36.373 27996 28032 I godot   : OpenGL ES 2.0 Renderer: Adreno (TM) 506
03-13 20:44:36.516  1486  1542 I ActivityManager: Displayed org.godotengine.newgameproject/org.godotengine.godot.Godot: +437ms
03-13 20:44:36.517  1486  1542 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{160a9eb u0 org.godotengine.newgameproject/org.godotengine.godot.Godot t22297} time:18529191
03-13 20:44:36.517  3720  3877 D PowerKeeper.Event: notifyActivityLaunchTime: org.godotengine.newgameproject/org.godotengine.godot.Godot totalTime: 437
03-13 20:44:38.184   774   774 F DEBUG   : pid: 27996, tid: 28032, name: GLThread 3593  >>> org.godotengine.newgameproject <<<
03-13 20:44:38.225   774   774 F DEBUG   :     #14 pc 00000000007cbf84  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:38.225   774   774 F DEBUG   :     #15 pc 0000000001169054  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:38.226   774   774 F DEBUG   :     #16 pc 000000000034c1e4  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:38.226   774   774 F DEBUG   :     #17 pc 00000000016ce8b8  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:38.226   774   774 F DEBUG   :     #18 pc 00000000016c3438  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:38.226   774   774 F DEBUG   :     #19 pc 00000000016c3720  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:38.226   774   774 F DEBUG   :     #20 pc 00000000008e9914  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:38.226   774   774 F DEBUG   :     #21 pc 00000000001d9be4  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so
03-13 20:44:38.226   774   774 F DEBUG   :     #22 pc 00000000001a5adc  /data/app/org.godotengine.newgameproject-1/lib/arm64/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+168)
03-13 20:44:38.226   774   774 F DEBUG   :     #23 pc 000000000027d0a8  /data/app/org.godotengine.newgameproject-1/oat/arm64/base.odex (offset 0x147000) (void org.godotengine.godot.GodotLib.step()+124)
03-13 20:44:38.226   774   774 F DEBUG   :     #24 pc 0000000000281f80  /data/app/org.godotengine.newgameproject-1/oat/arm64/base.odex (offset 0x147000) (void org.godotengine.godot.GodotView$Renderer.onDrawFrame(javax.microedition.khronos.opengles.GL10)+84)
03-13 20:44:38.481  1486 28060 W ActivityManager:   Force finishing activity org.godotengine.newgameproject/org.godotengine.godot.Godot
03-13 20:44:38.561  3720  3877 D PowerKeeper.Event: notifyAMProcDied pacakageName: org.godotengine.newgameproject, pid:27996
03-13 20:44:38.600  1486  1830 W WindowState: Failed to report 'resized' to the client of Window{f6d0c9a u0 org.godotengine.newgameproject/org.godotengine.godot.Godot}, removing this window.
03-13 20:44:38.610  2789  3772 D GameBoosterService: onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10021, mForegroundPid=2408, mLastForegroundPackageName='org.godotengine.newgameproject', mLastForegroundUid=10110, mLastForegroundPid=27996, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}

**Steps to reproduce:** install this apk, it supposed to work on android 9, but crash on android 6

**Minimal reproduction project:** https://drive.google.com/open?id=1bUUNggFF0-0HaCBIBviQtD56IlEKDDBg

**Comment by sdhy** [comment]
Local and LAN modes don't load at all. Development mode does, but is too slow to play on my Android 6.0.1 phone. I even tried powering off and restarting my phone. Looks nice, though. More phone specs at the bottom.

After the level loads up, it just blinks very slowly. Going back and forth between different camera angles (a bird's-eye view and an unplayable zoomed-in view). It's too laggy to play.

Slows down everything, including touches, swipes, and bringing down my notifications so I can exit the game.

Is there supposed to be sound? There wasn't any for me.

Graphics are nice, though!

My phone:
_LGE LG-K210
Android 6.0.1
Machine: armv7I
ABI: armeabi-v7a
GPU: Adreno (TM) 304
OpenGL ES: 3.0 V@140.0 AU@(GIT@Ia10634f51b)

Also, if it matters, it won't install on my Android 4.4 phone. But this phone has problems with Godot 3.1 anyways._

**Comment by fian46** [comment]
it is weird because it crash on os 6 on my other devices. i dont know what the problem, i dont use fancy shader or anything experimental. local and lan will not running at all, it just for my debugging purpose on my local server. thanks for trying.

**Comment by fian46** [comment]
if it not os issue maybe this is some corner case or something.

**Comment by fian46** [comment]
i am closing this since i found the root cause for the issue. i opened new issue #27232 with more focused source of problem
