### ISSUE TITLE
Create tutorials about Path / PathFollow (3D)

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27026]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64

**Issue description:**
There is a lack of information on how to use Path / PathFollow in 3D.
Since the 2D version is quite different, most commands do not work in 3D.

**Comment by eon-s** [comment]
This should be requested on the documentation or demos repository, this one is for things related to the engine development.

**Comment by rogeriodec** [comment]
> This should be requested on the documentation or demos repository, this one is for things related to the engine development.

Done.
