### ISSUE TITLE
Improve usability of curve edition in Path 3D

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27024]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64

**Issue description:**
Unlike Path2D, Path (3D) has no curves, which forces us to draw curves manually via code using sin() and cos().

**Comment by eon-s** [comment]
Curve3D used on Path can be curved (try set in and out in code) but there are no handles to manage the in and out values of the bezier curve, it need an spatial gizmo.

Also, for precision, it may need this too #6914 but for the spatial version.

**Comment by JFonS** [comment]
The curvature can actually be edited in the 3D viewport. Holding shift while dragging a point handle will generate the curvature handles for that point.


This should be improved to be more discoverable, but it's there.

**Comment by eon-s** [comment]
Wow, I wonder since when those things were hidden there...
Still, without a proper 3D gizmo (and inspector access) are really hard to manipulate.

**Comment by rogeriodec** [comment]
> The curvature can actually be edited in the 3D viewport. Holding shift while dragging a point handle will generate the curvature handles for that point.
> 
> This should be improved to be more discoverable, but it's there.

Great. How to create the curves by GDScript?

**Comment by eon-s** [comment]
Curve3D is just a resource used by Path, create a new one and assign to a path or use without paths too, depending your needs.
https://docs.godotengine.org/en/3.1/classes/class_curve3d.html

**Comment by rcorre** [comment]
A regular 3D gizmo to translate the points would be really useful -- it seems almost impossible to get them where you want by just clicking to add points.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/527, as feature proposals are now tracked in the Godot proposals repository.
