### ISSUE TITLE
Editable Children doesn't overwrite properties some times

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#27023]
**Godot version:** 3.1.stable

**OS/device including version:** Solus 3.9999

**Issue description:**

When merging or instantiating, but especially merging, after you enable `Editable Children` and try to modify some properties of the children, when the game loads it doesn't override them.

![merging_issue](https://user-images.githubusercontent.com/10171059/54311603-b0d93c00-45b3-11e9-8ffc-4c2a45a7b8cd.gif)

**Steps to reproduce:**
1. Create a scene with some Sprites
2. Save it
3. Instance it on another scene
4. Turn on `Editable Children`
5. Change its `position`
6. Create a new scene
7. Merge the instanciated scene from step 3
8. Test the scene

**Comment by KoBeWi** [comment]
This is because `editable children` are not stored in the node but in the scene and this information is not carried when moving the node to another scene (merging). See #33790
