### ISSUE TITLE
Implement Enable / Disable existing breakpoints

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27028]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64

**Issue description:**
Currently, there is no option to bypass the existing breakpoints while debugging. 
I have to remove them manually if I want to run the entire code.

**Comment by PelegMedia** [comment]
Conditional breakpoint will also be great.
It may help as it will only stop when the required conditions are meet.

**Comment by Calinou** [comment]
> Conditional breakpoints will also be great.
It may help as the debugger will only stop when the required conditions are meet.

This can already be done this way:

```gdscript
if some_var > 5:
    breakpoint
```

**Comment by PelegMedia** [comment]
Yes. I mean the breakpoint which happen after the debugger watch variable value or even better a boolean evaluation of several watches, e.g. (a == 5 and b<0) .
It doesn't require to change the code. 
You can change it multiple times and even, add new conditional breakpoints during the same debugging session.

**Comment by PelegMedia** [comment]
I think breakpoints inspector with ability to 
1. Enable/Disable breakpoints.
2. Goto a breakpoint in the code
3. Edit breakpoints conditions
will solve all these issue including the OP request.

**Comment by Anutrix** [comment]
> 
> 
> I think breakpoints inspector with ability to
> 
>     1. Enable/Disable breakpoints.
> 
>     2. Goto a breakpoint in the code
> 
>     3. Edit breakpoints conditions
>        will solve all these issue including the OP request.

Can we make this into tracker or task-list? At least 1 seems to have PR now.

**Comment by akien-mga** [comment]
Fixed by #30982.
