### ISSUE TITLE
Text added to RichTextLabel using append_bbcode is removed if the screen is resized

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#27027]
**Godot version:**

3.1 master

**OS/device including version:**

Windows 10 Pro

**Issue description:**

adding text to a rich text label using append_bbcode and resizing the window causes the text to be deleted

**Steps to reproduce:**
this line works good:
`	Messages.bbcode_text += new_bbcode`
this line works bad
`	Messages.append_bbcode(new_bbcode)`

**Comment by TheDuriel** [comment]
probably related to #24173

**Comment by MarianoGnu** [comment]
yeah, calling update makes new text added to be discarded, the same that when window is resized

**Comment by akien-mga** [comment]
Closing as duplicate of #24173 then.

**Comment by OsakiTsukiko** [comment]
This issue is not a duplicate of #24173 as that issue was fixed yet this one still persists.  24173 uses the bbcode_text property on RichTextLabel which seems to be fixed, while this one uses the append_bbcode method which is still buggy!  I think this issue should be reopened.

**Comment by OsakiTsukiko** [comment]
Although this issue is fixed in Godot 4.0 as the whole BBCode system had major changes.

**Comment by OsakiTsukiko** [comment]
Hmm. I can not replicate this issue outside of my project for some reason. The only thing I can think of is that I'm using async functions and the append_bbcode method is called at the same time twice on the same node.

**Comment by OsakiTsukiko** [comment]
After some more testing, I managed to recreate the issue outside of my project. The issue seems to only occur when using a custom (Dynamic) font.

**Comment by OsakiTsukiko** [comment]
https://user-images.githubusercontent.com/104794884/209484429-52c7aa16-9e26-4d33-a1ad-9490c2864edc.mp4

Showcase of issue
