### ISSUE TITLE
Mono: Templates don't download from editor in 3.1 Stable

### ISSUE THREAD

**Issue by exts** [godotengine/godot#27020]
**Godot version:**
3.1 Stable

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When you click on manage templates, it brings up download list and it 404's

![image](https://user-images.githubusercontent.com/16387107/54303563-41525500-4591-11e9-914f-0609410993d8.png)

Downloading manually works though https://downloads.tuxfamily.org/godotengine/3.1/mono/

**Comment by akien-mga** [comment]
Indeed there was a typo in the mirrorlist for the Mono templates, should be fixed now.
