### ISSUE TITLE
Material proximity parameter does not work

### ISSUE THREAD

**Issue by kaadmy** [godotengine/godot#27033]
**Godot version:**
Godot v3.1-stable (GLES3)

**OS/device including version:**
```
OS: Arch Linux x86_64
Kernel: 4.19.4-arch1-1-ARCH
GPU: NVIDIA GeForce 940MX
GPU: Intel HD Graphics 620
```

**Issue description:**
Proximity depth is corrupted/incorrect.

**Steps to reproduce:**
1. Create a new project
2. Add *3D Scene*
3. Add a `MeshInstance` with a cube shape
4. Add a `MeshInstance` with a plane shape
5. Resize the plane mesh to 4x4
6. Assign the plane mesh a `SpatialMaterial` with proximity enabled.

**Minimal reproduction project:**
[proximity_material.zip](https://github.com/godotengine/godot/files/2964384/proximity_material.zip)

**Comment by kaadmy** [comment]
This is the same as https://github.com/godotengine/godot/issues/25535 but without any special shaders/use cases.

**Comment by clayjohn** [comment]
This is indeed a duplicate of #25535

**Comment by groud** [comment]
Closing as a duplicate of #25535 then
