### ISSUE TITLE
Previous scenes/scripts dissapear on project reload

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#27047]
**Godot version:**
 775e74e

**Issue description:**
Yep, it's happening a little more frequently now. When reloading your project, there's a chance that the previous scenes and scripts will not be reloaded back.

**Comment by KoBeWi** [comment]
@YeldhamDev Does it still happen? I never experienced it.

**Comment by YeldhamDev** [comment]
I haven't been noticing this bug for a while, but I also handling very few scenes/scripts at once currently. I now have more problems with previously closed scripts reopening by themselves more than anything.

I will close this for now.
