### ISSUE TITLE
Cyclic reference of Scene and its Script

### ISSUE THREAD

**Issue by GlaDos28** [godotengine/godot#27048]
**Godot version:**
3.1

**Issue description:**

Consider a scene `SomeScene.tscn` and its script `SomeScene.gd`.

In **3.0** one could write

```
const SelfScene = preload("res://SomeScene.tscn")
```

and use scene instancing in code. But now this is forbidden, and the project doesn't work.

I understand that there is real cyclic dependence, but I did not find anything on how to bypass this problem correctly according to code style guide. I don't want to use `load` instead of `preload` because it is slower, and really not needed logically. Several scenes can have the same script, but in real life almost every scene has a unique script resource, and it is convenient to be able to address to self scene in script resource using compiler abilities ( `preload`).

**Steps to reproduce:**

Create `SomeScene.tscn` and `SomeScene.gd`, attach script to scene then add line to .gd file:

```
const SelfScene = preload("res://SomeScene.tscn")
```

**Comment by Zylann** [comment]
As I understood, it was not really supposed to work in 3.0 and it was the source of other bugs which are now fixed in 3.1.
You should indeed use `load` now. Did you measure its speed? IMO it is not slower, the only difference is *when* loading will happen, but depending on how you instance this scene in your game, there might not be a difference.

**Comment by GlaDos28** [comment]
I think it is not comfortable to use. In not all cases You can replace 
```
const SelfScene = preload("res://SomeScene.tscn")
```

with 
```
var SelfScene = load("res://SomeScene.tscn")
```

What if there are static functions in script that uses instancing? Then You should write the following to work:

```
const SELF_SCENE_PATH = "res://SomeScene.tscn"

static func create_and_smth_else(params):
    var instance = load(SELF_SCENE_PATH).instance()
```

It is rather dirty, I think.

**Comment by Zylann** [comment]
If there are static functions you want to use, you can preload the script, not the whole scene.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/460, as feature proposals are now tracked on the Godot proposals repository.
