### ISSUE TITLE
Directional shadow framebuffer status invalid

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#27040]
**Godot version: 3.1**

**OS/device including version: macOS Mojave 10.14.3 / MacBookPro11,1 Mid 2014. Intel Iris 5100**

**Issue description: E 0:00:00:0076   Directional shadow framebuffer status invalid
  <C Source>     drivers/gles2/rasterizer_scene_gles2.cpp:3355 @ initialize()**

**Steps to reproduce: I have a very simple project that only uses one KinematicBody2D and a couple od StaticBody2D nodes. Also, I have one very simple GDScript for my character control. Overall, a very simple and basic project.
[Pirates RPG_Godot 3.1_macOS.zip](https://github.com/godotengine/godot/files/2965491/Pirates.RPG_Godot.3.1_macOS.zip)
**

**Minimal reproduction project:**

**Comment by bruvzg** [comment]
#26570 duplicate

**Comment by Calinou** [comment]
Duplicate of #26570.
