### ISSUE TITLE
Can't connect to asset-library if custom certificate is set in Project Settings

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#27045]
**Godot version:**

3.1 stable

**OS/device including version:**

**Issue description:**

A custom certificate might impact the ability to access the asset library.

`Can't connect to host: https://godotengine.org/asset-library/api`

```
thirdparty/mbedtls/library/ssl_tls.c:5757: x509_verify_cert() returned -9984 (-0x2700)
ERROR: _do_handshake: TLS handshake error: -9984
   At: modules/mbedtls/stream_peer_mbed_tls.cpp:105.
mbedtls error: returned -0x2700
```

**Steps to reproduce:**

- Set a custom certificate in Project Settings -> SSL
- Restart the editor
- Try and access the Asset Library

**Minimal reproduction project:**

**Comment by Keetz** [comment]
I suggest that the connection to the Asset Library should always use the internal certificate.
How does this sound?

**Comment by Keetz** [comment]
Same issue when trying to access export templates

**Comment by Faless** [comment]
Thanks for reporting, indeed this is an issue.
Fixing it properbly requires some refactoring though as for now certs are shared between all the `StreamPeerSSL`s instances.
What we can do, is have the whole editor use the internal certificates. This would ofc break any request to websites that requires custom certificates that comes from `tool` and `EditorPlugins`.
What do you think?

**Comment by Keetz** [comment]
I think there easily could be a use case where a tool script would want to use a custom certificate, so for it to be bound by the internal certificates could become a problem for some, I think.

In my current use caste it would fix everything though :smile:

Usability wise I think it would be best if everything, except the asset library and template downloads, use the custom certificate if set.
