### ISSUE TITLE
[SUGGESTION] allow `_get_property_list()` to contribute to auto complete

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#27051]
**OS/device including version:**
N/A

**Issue description:**
Normally when working with `tool` you may want to expose custom variables to the to the inspector. For example allow `_get_property_list` to retrieve entries in a Dictionary... it would be nice if the suggestion for those properties should up in the autocomplete, if the dictionary is made `const`. if it is a constant and we are working with `tool` scripts I guess it would be doable? what do you think?

```
tool
extends Object
class_name MyObject

const dict = { "size": 1, "width": 2 }

func _get_property_list():
     var ret = []
     for a_name in dict:
          ret.append({"name": a_name, "type": TYPE_INT, "usage": PROPERTY_USAGE_DEFAULT})
```

this would make it possible to:

```
var a = MyObject.new()
a.size # this would appear in the autocomplete
a.width # this would appear in the autocomplete
```

What do you think? Worth it? Doable?

**Comment by mrcdk** [comment]
Duplicate of https://github.com/godotengine/godot/issues/25097

**Comment by xDGameStudios** [comment]
Sorry for the dup @mrcdk.
