### ISSUE TITLE
Is GDNATIVE_API_INIT & GDnative wrapper lib still used ?

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#27054]
Hi,

Back in the days when GDnative were introduced, we (me and @karroffel ) designed the gdnative into two layers:
- the actual GDnative api provided as a struct of function pointers (see [godot_gdnative_init_options](https://github.com/GodotNativeTools/godot_headers/blob/a51d905c5a34a441c1d4701b57c9de6548efbea3/gdnative/gdnative.h#L242-L252) )
- a wrapper initialized by using the `GDNATIVE_API_INIT` macro (see [gdnative_wrapper](https://github.com/godotengine/godot/blob/fe8cdafbf43419d49a23a3034a198f8ae456cb37/modules/gdnative/SCsub#L35-L52) )

The idea of the wrapper was to let the user be able to call the GDnative functions directly (instead of fetching them through the GDnative api structure).
The drawback of this wrapper was it needed a static library to be compiled with the project using GDnative (hence the godot build releases contains [those static libraries](https://github.com/GodotBuilder/godot-builds/releases/tag/3.0.3-stable-ci) )

After a long pause, I'm starting again to work on godot-python ;-)
What appened since the release of GDnative:
- https://github.com/GodotBuilder/godot-builds/releases seems to be lagging behind (last version is 3.0.3 vs 3.0.6 on main godot repo), hence wrapper static lib are not updated
- https://github.com/GodotNativeTools/godot_headers seems to be the official way to include godot GDnative headers (used in the cpp, r and d bindings and the [official documentation](https://docs.godotengine.org/en/3.1/tutorials/plugins/gdnative/gdnative-c-example.html) ). This repo doesn't contains a compiled version of the wrapper static lib
- Official documentation (https://docs.godotengine.org/en/3.1/tutorials/plugins/gdnative/gdnative-c-example.html) doesn't talk about the wrapper system and directly use the api struct
- I couldn't find a single project using the wrapper system apart from Godot-Python

So the question is: is this wrapper still needed ? If not, would it be helpful to deprecate it (or at least to simplify the release system by not generating)

**Comment by karroffel** [comment]
I think so far godot-python is the only project using it, but there might be some other not-so-widely-used bindings that use it. I remember someone asking about having a simpler interface in the IRC and I pointed them to the wrapper, but I don't know anything further than that.

The wrapper has not been updated properly since there have been extensions to both GDNative core as well as NativeScript, so it is probably missing many new functions.

Since nobody else is seemingly using it, I don't mind deprecating it. It could also just be moved to the GodotNativeTools organization, as it does not really need to be part of the Godot building pipeline but can be done externally.

**Comment by akien-mga** [comment]
I'm fine with deprecating it if nobody uses it and you don't need it for godot-python anymore.

**Comment by touilleMan** [comment]
I'm currently working on a new version of Godot-Python which won't use this feature so I guess this feature could be totally removed ;-)

BTW, removing this feature means we can remove all the functions definitions from the headers files (using those functions would end up in a linking error given they are not defined without the wrapper lib) and only keep the structure definitions.
I guess it's a good thing (less code is less bug, especially when the code should be synced between the main `godotengine/godot` repo and `GodotNativeTools/godot_headers` repo) however this means doing big changes to an interface API that is supposed to change as few as possible for compatibility reason.
What do you think ?

**Comment by karroffel** [comment]
We could in theory move all the definitions from the headers into the generated .cpp file which constructs the API struct, but I think it's more maintainable to keep it in headers. I have no strong feelings about that.

**Comment by akien-mga** [comment]
Not much happened since the last comment, and we're almost ready to release 3.2, so I'd suggest that we take the opportunity for compat breakage in 4.0 to drop the wrapper then.

**Comment by touilleMan** [comment]
I agree, besides I'm keeping track of a list of things that are missing or
could be improved in gdnative so we could discuss about it during the Godot
sprint in February ;-)

Le ven. 13 déc. 2019 à 23:47, Rémi Verschelde <notifications@github.com> a
écrit :

**Comment by touilleMan** [comment]
New godot-python version 0.20 is around the corner and doesn't make use of GDNative wrapper lib \o/

**Comment by akien-mga** [comment]
4.0 development is started, so feel free to remove the relevant code. IMO it's best to drop it now, and if we ever have a use for it, we can readd/rewrite it.

**Comment by touilleMan** [comment]
here's #35778, but you should be focusing on Reduz's talk right now :trollface:

**Comment by touilleMan** [comment]
> We could in theory move all the definitions from the headers into the generated .cpp file which constructs the API struct, but I think it's more maintainable to keep it in headers. I have no strong feelings about that.

I think @karroffel is right here. Cleaning up the headers would be a lot a work for no big win, so I didn't touch this part in the PR
