### ISSUE TITLE
Socket error when trying to download project from Asset Library

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#27050]
**Godot version:**
3.2 775e74e

**OS/device including version:**
Linux Mint 19

**Issue description:**
When I try to download and install Meteorite project from Assets Store, then this error is shown:
```
ERROR: _get_socket_error: Socket error: 111
   At: drivers/unix/net_socket_posix.cpp:199.
ERROR: connect_to_host: Connection to remote host failed!
   At: drivers/unix/net_socket_posix.cpp:339.
```

**Comment by Faless** [comment]
The error is not actually when downloading the template (which worked), but when downloading the templates list.
Specifically, there is an asset with the image `godotdevelopers.org/forum/uploads/editor/qz/hqr754z65ypc.png`. Which appears to be offline.
The asset is: https://godotengine.org/asset-library/asset/edit/937 .

**Comment by Faless** [comment]
We could uncomment this line to make it explicit (I actually think it was commented out by mistake in PR #18876)
https://github.com/godotengine/godot/blob/775e74e0d41daa9cf3679c2e215f4ef46eee9cbc/editor/plugins/asset_library_editor_plugin.cpp#L821
