### ISSUE TITLE
Changing font settings in a Theme resource will also save in the Font resource.

### ISSUE THREAD

**Issue by FlashDaggerX** [godotengine/godot#27068]
**Version** *3.1.stable.custom_build* (Official Download)

**EDIT Operating System** Arch Linux, *5.0.1-arch1-1-ARCH*

**Issue**
Not sure if it's purposeful or not. I'd like to use the same font in multiple themes for my game, but changing the size in one theme will change it in **every** theme. It saves whichever setting you changed back to the font file.

**Steps**
1. Create a DynamicFont resource. Use whichever font you want. I used [this lovely font called lemon](https://github.com/fennerm/artwiz-lemon-ttf).
2. Try changing the size of said font.
3. Use it as the default font in a Theme resource.
4. Try changing the size in the Theme resource. Save it.
5. Check the DynamicFont resource. The size is the same as the theme.

[MRP_OpenBOT.zip](https://github.com/godotengine/godot/files/2968461/MRP_OpenBOT.zip)

**Comment by samgreen** [comment]
Can you make the font resource unique in the inspector?

**Comment by FlashDaggerX** [comment]
Yea, I can. Sorry about that.
