### ISSUE TITLE
LineEdit copies chunks of text erratically on Android

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot#27065]
**Godot version:**
3.1 stable

**OS/device including version:**
Asus Zenfone Max Plus (Android 7)
Xiaomi Pocophophone F1 (Android 9)

**Issue description:**
If you move the caret to the middle of the text, when you type the keyboard copies a section of the text.

If you type

`aaaaabbbbcccc|`

, move the caret inbetween the `a` and `b`

`aaaaa|bbbbcccc`

and type `d`, you get

`aaaaabbbbccccd|bbbbcccc`

instead of the expected

`aaaaad|bbbbcccc`

I suspect this has to do with synchronizing the virtual keyboard's buffer.

**Steps to reproduce:**
- Create a LineEdit
- Export to Android
- Type some text as explained above

**Minimal reproduction project:**
(This MRP is literally just a LineEdit in an otherwise empty scene.)
[MRP.zip](https://github.com/godotengine/godot/files/2968261/MRP.zip)

**Comment by jabcross** [comment]
I should specify that I move the caret by touching the LineEdit directly, and not using any sort of arrow keys.

**Comment by leakim34** [comment]
I experience same issue, and as far as I know it's relative to keyboard suggestions because if I set the keyboard without suggestion ( I do it with a android plugin I made) I do not experience this issue anymore and can add some text anywhere.

Plus, I noticed that onTextChanged() handler in godot:
 https://github.com/godotengine/godot/blob/master/platform/android/java/src/org/godotengine/godot/input/GodotTextInputWrapper.java#L103

the start parameter seems to be incorrect, it always has 0 even when we insert text in different position ... might help .. not sure.

Please if someone can look into it.

Thanks

**Comment by Anynak** [comment]
Hey. I suffer from this problem too. is there any solution

**Comment by leakim34** [comment]
Indeed I hope they gonna plan to fix it soon... Was hoping on 3.2 but
nothing has been made about this ;( its really painful to not being able to
work with any input field on Android.

**Comment by Ramh5** [comment]
Does anyone have a workaround to this issue? Is there a previous version of Godot that would work on Android in the mean time?

**Comment by leakim34** [comment]
Nothing yet maybe 2.x...
Still waiting a fix because it's kind of annoying having those inputs buggy
on my android project..
Hope they gonna fix this during 3.2.x updates ;)

**Comment by jabcross** [comment]
I think the priority should be bumped.

**Comment by ondesic** [comment]
Can this be moved to the front lines?  I am in GREAT need of this being fixed ASAP.  My entire project relies on a TextEdit control being used between an android device and a Desktop.

**Comment by Calinou** [comment]
@ondesic In community-developed projects, people work on what they want to work on. If you want to see this feature fixed faster, you'll have to do it yourself, or pay someone to do it.

**Comment by ondesic** [comment]
@Calinou This brings up a great point that I have wondered about.  I would be VERY happy to pay someone to work on this, I just don't know how to go about this.  Any ideas?

**Comment by SkyLucilfer** [comment]
I'll try to look into this issue and see if I can do something.

**Comment by ondesic** [comment]
Please PM me.  I am happy to pay you for your time.

**Comment by SkyLucilfer** [comment]
@ondesic No need to pay :) I'm working on it but I cannot guarantee anything.
