### ISSUE TITLE
godot 3.1 _input_event on BoxShape not working

### ISSUE THREAD

**Issue by beetbeet** [godotengine/godot#27060]
**Godot version: 3.1**

**OS/device including version:**
WINDOWS  10/ NVIDIA GeForce GTX 1060 6GB

**Issue description:**

i have a BoxShape as CollisionShape and that code:

```
   func _input_event(camera, event, pos, normal, shape):
        if event is InputEventMouseButton \
        and event.button_index == BUTTON_LEFT \
        and event.is_pressed():
            self.on_click()

    func on_click():
        tileNode.click()
```

dont works in godot 3.1 but works in 3.0, any ideas why? func on_click() is not executed

**Minimal reproduction project:**
[https://github.com/beetbeet/godot-3-0-input-event.git](https://github.com/beetbeet/godot-3-0-input-event.git)

**Comment by TyTYct** [comment]
[https://github.com/godotengine/godot/issues/27063#issuecomment-473531683](url)
As bojidar-bg, you need set `input_ray_pickable = true`
this problem will go away

![image](https://user-images.githubusercontent.com/8284805/54476529-0bcb9700-4831-11e9-8f21-ecb48c05c9c2.png)

**Comment by beetbeet** [comment]
thank you! it works! :)
