### ISSUE TITLE
GLES2 "Do not Receive Shadows" is not working

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#27061]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10

**Issue description:**
The spatial material has an option "Do not Receive Shadows". Shadows are rendered onto this mesh even if this option is checked. It's working as intended on GLES3.

GLES2:
![gles2](https://user-images.githubusercontent.com/25849067/54386239-cecc9c80-4698-11e9-80f5-cd2be1d87b40.PNG)

GLES3:
![gles3](https://user-images.githubusercontent.com/25849067/54386254-d55b1400-4698-11e9-9fb1-6e0fedcb62bd.PNG)

**Steps to reproduce:**
- Create a new 3D scene 
- add a light source
- add two meshes, one which is casting a shadow and one which is receiving the shadow
- check "Do not Receive Shadows" in the options of the spatial material of the receiving mesh

**Minimal reproduction project:**

[ReceiveShadowBug.zip](https://github.com/godotengine/godot/files/2968193/ReceiveShadowBug.zip)

**Comment by clayjohn** [comment]
It looks like the issue is that the "shadows_disabled" render flag hasn't been implemented in scene.glsl in GLES2. https://github.com/godotengine/godot/blob/master/drivers/gles2/shaders/scene.glsl

**Comment by SouzaGuilherme** [comment]
Hi, I'm going to try to implement this part

**Comment by SouzaGuilherme** [comment]
looking at both codes really is not implemented SHADOW_DISABLE, I entered IRC and FreeBDS works, I think bug on windows (I'm a novice and novice contributor in the engine too), but in GLES2 the functions are of SHADOW && Light, so I'm analyzing how to implement

**Comment by zqyoung1** [comment]
@SouzaGuilherme Are you still working on this issue? If you are not I'd like to pick it up.

**Comment by SouzaGuilherme** [comment]
Yes, I'm still working on that. I'm having a bad time since I have little shaders knowledge, but i think that 4 days are enough.
