### ISSUE TITLE
Implement option to disable the vertical tab line to the right of the GdScript editor

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27069]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64

![](https://media.discordapp.net/attachments/212250894228652034/555863184901144580/unknown.png)

This line would be useful if Word Wrap worked based on it.
Even so, it would be interesting to have an option to disable it

**Comment by MaciejGorczycaGD** [comment]
This is line line length guide if I see correctly on the picture you can disable it already.

**Comment by rogeriodec** [comment]
Editor > Editor Settings > Text Editor > Line Numbers > Show Line Length Guide
