### ISSUE TITLE
Weird CPUParticles rendering bug

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#27066]
**Godot version:**
Godot 3.1 RC2, RC3 and stable

**OS/device including version:**
Manjaro Linux

**Issue description:**
There's a very weird CPUParticles rendering bug in Godot 3.1. Some particle effects show a single huge particle, even when they are not emitting. Sometimes it goes away when the partcile effect is emitting for the first time. I haven't yet found out why some particle effects do this and others don't. It's difficult to tell what exactly tiggers this behaviour, but I'll try to create a simple example scene that reproduces it reliably.

I've tried the most recent versions and this bug appears to have been introduced in RC2. It doesn't happen in RC1, which was the last version I tested before the 3.1 release. Sadly the other release candidates came so fast that I didn't have a chance to test them in time.

This is what happens in my game since RC2:
![PostRC1](https://user-images.githubusercontent.com/15891496/54389466-6aadd680-46a0-11e9-8582-d52676cf7047.png)

This is what should happen:
![RC1](https://user-images.githubusercontent.com/15891496/54389438-5ec21480-46a0-11e9-8d35-56457e3f0979.png)

**Comment by eon-s** [comment]
Can you make a small example with the problem? Also add details about graphics card and driver.

**Comment by clayjohn** [comment]
I wonder if its from this commit https://github.com/godotengine/godot/commit/1edc2134c99184f3714c806b7a494026e8f029b2

**Comment by ProbDenis** [comment]
Graphics card is a Radeon RX 560, and I'm using the open source AMDGPU driver.
At first I didn't have any success making an example project, so I took the scene from my game and removed nodes from it until I could reproduce it in a tiny scene:

[CPUParticlesBug.zip](https://github.com/godotengine/godot/files/2970755/CPUParticlesBug.zip)

And yes, it looks like it has to do with invisible/inactive particle effects. The scene starts with an invisible CPUParticles node. After a second it becomes visible, and a single huge particle appears. Two seconds later, when the effect starts emitting, it disappears again.
It can even be reproduced in the editor. Load the scene, then make the particle effect visible, then start emitting.
