### ISSUE TITLE
cannot override inherited member 'AnimatedSprite.Play(string)' because it is not marked virtual, abstract, or override [ProjectC#]

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#27073]
**Godot version:**

3.1

**OS/device including version:**

win10

**Issue description:**

Cannot override an AnimatedSprite function that I would like to override

**Comment by akien-mga** [comment]
Why would you override node methods? The error is correct, this method is not marked virtual, abstract or override, so it's not meant to be overridden.

**Comment by JarLowrey** [comment]
animation_start signal is a better use for what I was doing.
