### ISSUE TITLE
Support autocomplete with types

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#27075]
Similar to #27074 , when using autocomplete for function signatures and variables in GDScript it (understandably) ignores types. As someone who uses typed gdscript exclusively now, I think it would be nice if auto completion for function signatures, for example, would automatically fill in types. for parameters and return args. For instance, when overriding `_ready` or `_process`, I would like autocomplete to create `_ready()->void` and `_process(delta : float)->void`, respectively.

This could be done with a project setting to "favor" types in GDScript.

**Comment by CowThing** [comment]
There is already an option for this
Editor Settings -> Text Editor -> Completion -> Add Type Hints

**Comment by jonbonazza** [comment]
Excellent! Thanks! I wasn't aware this existed. I will close this then.
