### ISSUE TITLE
load autocompletion is missing

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#27078]
**Godot version:**
3.1
(also current master)

**Issue description:**
Resource auto-completion for `load` seems to be missing in 3.1.

There was a bug that caused `preload` autocompletion to fail if there was an error. That bug seems to be fixed, but `load` is now broken.

**Comment by akien-mga** [comment]
Is the scene where that script is used open? AFAIK resource completion only works reliably when the scene is open, and it's been this way for years.

**Comment by KoBeWi** [comment]
Eh, seems like it's... ok actually?

Dunno why, but it, like, fixed itself. There's however a _minor_ inconsistency between `load` and `preload`.
`load`'s autocomplete starts when you type `load("`
and for preload it's `preload(`
(notice the **"** difference at the end)

Both `preload("` and `load(` don't trigger autocompletion (is that even worth making another issue?). Not sure if it was that way (probably was), but then for whatever reason I didn't notice it or it was a one-time thing.

**Comment by KoBeWi** [comment]
Ok, for whatever reason, it doesn't work again in master (afecc0b). There's also #31425, which makes it even worse.

**Comment by KoBeWi** [comment]
The problem seems to be somewhere here:
https://github.com/godotengine/godot/blob/61dd7748cafafca08b8f87183ddf42de06b58911/modules/gdscript/gdscript_editor.cpp#L2435-L2445

The completion map is correctly filled, but doesn't seem to take effect. Also "preload" is redundant here, because it takes autocompletion arguments from a different place.
