### ISSUE TITLE
Moving Polygon2D vertices along axis

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#27077]
**Godot version:**
3.1

**Issue description:**
When moving a 2D node, you can hold Shift to move it along axis, i.e. it has fixed x or x. Would be nice if polygon vertices could support it to, as right now holding Shift doesn't affect them at all. That would be useful in situations where grid snapping isn't a viable option, but you want the vertex to be aligned.

**Comment by DarknessCatt** [comment]
Hello!

While I am familiar with godot, I am new to contributing to the source code. I was thinking of starting with this issue, is there any problem with that?

I've been looking around the source to find which file I need to modify, however I can't seem to pinpoint it, but I believe canvas_item_editor_plugin.cpp handles the behavior for the 2D node.

If anyone would shed some information about this for me I would be really thankful.

**Comment by DarknessCatt** [comment]
Hey, @KoBeWi, I opened a pull request for this issue. I would be thankful if you could check if the behavior is the intended one and provide some feedback.
