### ISSUE TITLE
Drop texture on Material slot

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#27079]
**Godot version:**
3.1

**Issue description:**
Recently I got an idea that it would be really helpful to implicitly "convert" textures to materials. I mean, when we want a textured MeshInstance, we need to create a SpatialMaterial, open it and assign an albedo texture. My proposal is that dropping a texture on any (empty?) Material slot could automatically create a SpatialMaterial with this texture set as albedo.

**Comment by arkology** [comment]
Maybe it's better add presets for shaders, like GDScript presets

**Comment by freestraws** [comment]
I might take this issue on, but is there anything else I can look at that does a similar thing?  As in, adding another file type the property editor can take for a specific type and using/ converting that input to the actual resource to be used?

**Comment by coderguy1777** [comment]
Was this ever fixed or implemented

**Comment by freestraws** [comment]
@coderguy1777 I never did anything with it since I didn't know where to start exactly and never got an answer to my questions...

**Comment by KoBeWi** [comment]
> I didn't know where to start exactly and never got an answer to my questions...

Well, being a contributor isn't always easy. I rarely get my engine questions answered, but I still manage to find a way to do something. If you think you are on a right track, just keep experimenting and eventually you will either make it work or realize that the issue is too difficult to fix with your experience.

That being said, for this one you should look into `EditorPropertyResource::drop_data_fw` and related methods (especially `_is_drop_valid(p_data)`). However it seems to be accepting only one data type right now and adding a secondary type could involve either changing accepted types to array or introducing some secondary type variable. Not sure if that's fit for Junior Job though.

**Comment by hbina** [comment]
I will try to take on this issue...

**Comment by hbina** [comment]
@KoBeWi 

I planted a breakpoint there and it doesn't seem to work. I think its handled (or not handled) by something else.

**Comment by codecustard** [comment]
> I planted a breakpoint there and it doesn't seem to work. I think its handled (or not handled) by something else.

`EditorPropertyResource::drop_data_fw` isn't going to be hit because the texture doesn't match the allowed type, but that would be the method that you would implement the functionality. If you need to set a breakpoint a good place would be `EditorPropertyResource::can_drop_data_fw`
