### ISSUE TITLE
Add default script templates for typed gdscript

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#27074]
Apologies if this is already requested somewhere. I did a search, but wasn't able to find anything in the almost 5k issues (There really should be some cleanup in this regard. Are all 5k issues _really_ issues? Are they all even still valid?)

Anyway, typed GDScript is amazing, but there remains the issue that when you create a new script, the `_ready` function in the default templates is not typed (understandably, as typing is optional). There should be an option to use templates that default to typed GDScript.

This could be as simple as as separate template in the new script dialog, or something more elaborate like a project setting that makes everything favor typed gdscript.

**Comment by lupoDharkael** [comment]
You can enable type hints in the Editor Settings but it will only affect the `Default` script:

![image](https://user-images.githubusercontent.com/14951430/54699304-0b811380-4b31-11e9-800d-be5ae4e13b2c.png)

**Comment by lupoDharkael** [comment]
I've just seen someone told you about it.

About the issue, as it only affects the Default script I guess a typed version without comments could be considered.
