### ISSUE TITLE
Typed GDScript and Area's body detection with non-PhysicsBody objects (GridMap or TileMap)

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#27076]
**Godot version:**
3.1 stable

**Issue description:**
When `Area`/`Area2D` object detects a `GridMap`/`TileMap` with typed callbacks, the parameter is null, because it is not a `PhysicsBody`/`PhysicsBody2D`.

The workaround is to use the common base class which is `Spatial`/`Node2D`.
Properly solving this may be difficult because it could need a new class structure for GridMap and TileMap.

**Steps to reproduce:**
Create a body entered callback on Area/Area2D, make it typed, put it over a GridMap/TileMap, check on the body parameter while the game is running.

**Minimal reproduction project:**
On the Kinematic Character 2D demo, turn the princess `body_enter` callback into a typed one, it should throw an error when the game starts if is touching the TileMap.

**Comment by akien-mga** [comment]
This is likely due to #24739.

**Comment by eon-s** [comment]
Yes, an "easy" solution could be doing like with the detailed callback that receives an RID (`*_shape_entered`), but that breaks will break the callbacks and adds a small extra complexity to the simple callbacks.

A dirty solution could be a new signal for special (non-PhysicsBody) bodies that returns the RID.

**Comment by bojidar-bg** [comment]
Note that Area2D emits the node: https://github.com/godotengine/godot/blob/dab8f8c953cd8ca18e792cc7aa0b717b38804e01/scene/2d/area_2d.cpp#L120-L128

But the `body_*` signals are registered as emitting PhysicsBody2D:
https://github.com/godotengine/godot/blob/dab8f8c953cd8ca18e792cc7aa0b717b38804e01/scene/2d/area_2d.cpp#L661-L662

Typed GDScript picks it up and then tries to convert the TileMap to PhysicsBody2D, producing null.

Manually changing the signal handler function to `func ...(body: Node)` should work fine.
