### ISSUE TITLE
Default spatial material has too extreme parameters

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#27082]
I think that the default values of the spatial material are a bit too extreme.

Sice Godot uses PBR they should also be somewhat physically correct. Currently it uses a perfectly diffuse material (roughness 1.0) with a color that reflects *all* incoming light (albedo 1.0, 1.0, 1.0) which both are not very realistic.

I think a medium to high roughness material (0.5 to 0.8) should be used with a gray to light gray albedo (around 0.5 to 0.8 aswell).

**Comment by Calinou** [comment]
The upside of having the roughness set to 1 by default is that it works out of the box when you define a roughness texture, which isn't the case of values below 1.

**Comment by CptPotato** [comment]
I actually didn't think about how it would be annoying having to reset the color when adding textures.

I only noticed that, when blocking out a level without materials, the very bright default color tends to throw you off when adjusting new materials because "realistic" ones would look too dark in comparison.

Here's a screenshot of the current default against a photoscan material:
![grafik](https://user-images.githubusercontent.com/3957610/54423489-12fb8380-4711-11e9-8c4f-eae881ec422a.png)

And this is a bit closer to what I had in mind:
![grafik](https://user-images.githubusercontent.com/3957610/54423576-4211f500-4711-11e9-9ab0-4e45efc196e8.png)

**Comment by golddotasksquestions** [comment]
Calinou mentioned concerns that setting the Abedo texture then results in a darkened model if the default material is not white.

If the user sets an Albedo texture, in most cases the user would not want the material to have a color.

So maybe the material color could automatically be set to while when the user assigns an Albedo texture (which a checkbox somewhere to allow the user to disable this auto-behaviour)?

**Comment by golddotasksquestions** [comment]
As an unfortunate sideeffect, the darker material color seems to make the incredibly ugly and unrealistic Auto Ambient Occlusion effect even more visible. Maybe this AAO could be significantly reduced as well by default.
As soon as there is a light in the scene this AAO is the opposite of helpful. In your screenshot for instance, the area lit by the directional light should get brighter if anything due to light bouncing, but definitely not darker. This is such a dated look. :(

**Comment by Calinou** [comment]
@golddotasksquestions AO is only visible in indirect lighting by default. I guess the screenshot set the had the **Light Affect** property set above 0 (the default is 0).

**Comment by Calinou** [comment]
The default material in `master` has albedo set to `Color(0.6, 0.6, 0.6)`, roughness set to `0.8` and metallic set to `0.2`. It looks much closer to real world scenarios as a result, closing.
