### ISSUE TITLE
Unable to Reparent CollisionShape to StaticBody from GDScript tool script

### ISSUE THREAD

**Issue by TheoLeeCJ** [godotengine/godot#27089]
**Godot version:** 3.1 stable

**OS/device including version:** Windows 10 64 bit 1809

**Issue description:**
When attempting to reparent a CollisionShape to a StaticBody from within a GDScript tool script, the CollisionShape disappears from the Inspector, but is visible in the 3D Editor. The CollisionShape is not saved when the Scene is saved...

Expected Behaviour was that the CollisionShape being reparented to the StaticBody would be reflected in the Inspector, and that the CollisionShape would be saved when the Scene is saved.

**Steps to reproduce:**
1. Download the reproduction project
2. Open Scene.tscn
3. Open cooltool.gd
4. Run the cooltool.gd (Ctrl + Shift + X)
5. Observe that the CollisionShape has disappeared from the Inspector, but is still visible in the 3D Editor (try moving the StaticBody around using gizmos to see the CollisionShape clearer)

**Minimal reproduction project:**

[upload.zip](https://github.com/godotengine/godot/files/2970287/upload.zip)

**Comment by Zylann** [comment]
I think you should reset the `owner` of the node because reparenting removed it from the tree.

**Comment by Zylann** [comment]
Setting the edited scene root as owner fixed it:
```gdscript
            source2.set_owner(get_scene())
```

**Comment by TheoLeeCJ** [comment]
Ah, yes it does fix it. Thanks! Closing this issue...
