### ISSUE TITLE
get_overlapping_areas() not working properly in area_entered signal since 3.1

### ISSUE THREAD

**Issue by lainv0hndyrec** [godotengine/godot#27093]
**Godot version:**
3.1 stable

**Issue description:**

**Node to check :** Area2D

**method/signal to check:** Area Enter

Hi Sorry if i butcher this for im not that used to github.
in 3.0.6, when you have a "get_overlapping_areas()" in a area_entered signal
it gets all of the areas in that event. 

example:

```
_in the ready()
> connect("area_entered",self,"do_this")

func do_this(obj):
> var objs = get_overlapping_areas()
> print(objs)
```

so if you have 4 areas teleported to 1 location and the are all overlapping
and u have area0 detecting everything

the print report will be like this
[area1,area2,area3]

now in 3.1 it returns this
[area1]
[area1,area2,area3]

this causes a lot of problems using area2d coz if u want to affect every area it will do it first with the first contact then it will check for others which is not ideal.

for now what im doing is I put the get_overlapping_areas() function in a physics_process... which isnt optimised.

**Steps to reproduce:**
```
_in the ready()
> connect("area_entered",self,"do_this")

func do_this(obj):
> var objs = get_overlapping_areas()
> print(objs)
```

**Comment by eon-s** [comment]
I think that the way to do it, is to check in a process function, just enable a check flag on the signal, trying to get physics states during signals may not give you what you expect.

**Comment by lainv0hndyrec** [comment]
yup its just that in 3.0.6 its pretty straight forward... now in 3.1
i need to use a signal "area_entered" calls a method that just sets the physics process = true
then in the physics process it has a get_overlapping_areas() then set_physics_process = false

**Comment by bojidar-bg** [comment]
Try connecting with the `CONNECT_DEFERRED` flag. It will call the signal handler a bit later, which might be enough for the overlapping_areas array to update.

**Comment by lainv0hndyrec** [comment]
ooh we have a deferred flag for connects? oh its a 3.1 thing. ill try that.

**Comment by bojidar-bg** [comment]
@lainv0hndyrec yeah, that's pretty much what bind does. In your case, you would probably leave it to `[]`.

**Comment by lainv0hndyrec** [comment]
Thank you.. will try this today <3
