### ISSUE TITLE
Godot crashes when trying to generate lightmap for the specific model

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot#27101]
**Godot version:**
3.1 Release

**OS/device including version:**
Windows 10 / Acer Aspire E 15

**Issue description:**
Godot is crashed on project open during lightmap generation

**Steps to reproduce:**
1) Open attached project
2) Godot starts importing the model and crashes
There is a message in the log right before crash:
![image](https://user-images.githubusercontent.com/7196697/54446507-5259bc80-4771-11e9-8ace-8169d94014af.png)

If I manually change meshes/light_baking=2 to meshes/light_baking=0 in the kitchen_sink_table.dae.import file, everything goes fine. But when I try to change it back to 'Generate lightmap' in editor and reimport, Godot crashes again.
![image](https://user-images.githubusercontent.com/7196697/54446800-fb081c00-4771-11e9-96c9-3f96a729f488.png)

**Minimal reproduction project:**

[lightmap.zip](https://github.com/godotengine/godot/files/2972005/lightmap.zip)

**Comment by Akira1San** [comment]
Tested it. Yep switching to a Gen Lightmap and reimport, then crash. Its a bug!

**Comment by Antokolos** [comment]
Another cases for this bug:
https://github.com/godotengine/godot/issues/30789

**Comment by akien-mga** [comment]
Seems fixed in the master branch, it does not crash.

I can still reproduce the crash in 3.1.2, it seems the issue was fixed by updates to the thirdparty xatlas library.
