### ISSUE TITLE
Input: When a button is quickly pressed and released and the game lags it doesn't get released [Linux]

### ISSUE THREAD

**Issue by santouits** [godotengine/godot#27104]
**Godot version:**
master

**OS/device including version:**
Linux 4.19, debian stable

**Steps to reproduce:**
Update the number in the loop I made inside _process(delta), so that your game lags when you move. Then press an arrow button and release it immediately. If you succeed, the sprite will continue to move and you'll have to press and release again the same button to stop it.

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/2972828/project.zip)

**Comment by MightyPrinny** [comment]
the game doesn't have to lag I'm getting this normally when I press a key very very fast

**Comment by Calinou** [comment]
Does this occur if you call `Input.set_use_accumulated_input(false)` in a script's `_ready()` function?

**Comment by MightyPrinny** [comment]
@Calinou that seems to fix the issue thank you.

**Comment by Calinou** [comment]
For the record, accumulated input was enabled by default in projects because of https://github.com/godotengine/godot/issues/26395.

**Comment by akien-mga** [comment]
I've seen this in the TPS demo, both in game and in editor (freelook mode), sometimes the movement keys will get stuck going in one direction even when released. I then need to repress and release to stop perpetual movement.

**Comment by Zireael07** [comment]
I saw this getting stuck in my own game when I was beginning working on the sky, and therefore occasionally had very low FPS. 3.1.1. 
I was going mad thinking my car input code was to blame!

**Comment by starry-abyss** [comment]
Maybe related, or maybe I should create an other issue (I use Windows 7):

- press a key in the Godot game window;
- focus another window with mouse;
- release the key;
- focus the Godot game window;
- see character still moving as if the key wasn't released.

**Comment by Calinou** [comment]
@starry-abyss You should create another issue for this, it's not related to input accumulation.
