### ISSUE TITLE
Overlapped Nodes do not emit mouse_exit signal

### ISSUE THREAD

**Issue by UltyX** [godotengine/godot#2710]
When two Texture buttons are next to each other and overlap slightly, then the mouse exit signal will not be emitted when the mouse moves from the button that is partially covered to the button on top. 
 The same happens for Area2D when it is overlapped by a control node (Area2D does not emit mouse_exit signal when mouse moves from area2d to control node on top of it).  Both times the mouse exit signal is only emitted when the mouse finally leaves the top level control node.
Tested in 1.1 stable and 2.0 alpha 30.10.2015

**Comment by eska014** [comment]
The issue with TextureButtons appears to occur only when there are no Control nodes as direct or indirect parents. The Area2D and Control issue I can also confirm.

**Comment by reduz** [comment]
this is a known bug, but won't be fixed until 2.1 I'm afraid

**Comment by reduz** [comment]
Actually, this issue was fixed in 2.0, so closing.
