### ISSUE TITLE
request

### ISSUE THREAD

**Issue by APakrohk** [godotengine/godot#27110]
Plz, Add Euphoria technology.
___________________
Euphoria 🆚 Ragdoll 
https://m.youtube.com/watch?v=kiih_08GGp4

**Comment by eon-s** [comment]
Try to be more detailed on the title and description of your request, also why it benefits the engine and the game developers in general, also what implies the addition of that feature if you want for it to be taken seriously. 

Also read 
https://docs.godotengine.org/en/3.1/about/faq.html#i-have-a-great-idea-for-godot-how-can-i-share-it

And always have in mind this useful chart
https://twitter.com/reduzio/status/941799197774315525

**Comment by akien-mga** [comment]
Indeed, as it stands this feature request doesn't help at all.
