### ISSUE TITLE
`is` returns true when inner class names match.

### ISSUE THREAD

**Issue by bitwes** [godotengine/godot#27111]
**Godot version:**

3.1 stable

**OS/device including version:**

Mac OS Sierra 10.12.6

**Issue description:**

The `is` function is returning `true` when an instance has an Inner Class name that matches what it is being compared to even if the Outer Class names do not match.

**Steps to reproduce:**
The following script will print "I think we have a bug here."
```
extends SceneTree

class HasInnerClass1:
	class InnerClass:
		var a = 1

class HasInnerClass2:
	class InnerClass:
		var a = 2

func _init():
	var inner_of_hasInnerClass1 = HasInnerClass1.InnerClass.new()
	if(inner_of_hasInnerClass1 is HasInnerClass2.InnerClass):
		print('I think we have a bug here.')
	else:
		print('Everything checks out.')

	quit()
```

**Minimal reproduction project:**

See script in Steps to Reproduce

**Comment by bojidar-bg** [comment]
The bug is even cooler. The inner classes are actually the same:
```gdscript
class HasInnerClass1:
	class InnerClass:
		var a = 1
class HasInnerClass2:
	class InnerClass:
		var a = 2
func test():
    print(HasInnerClass1.InnerClass, HasInnerClass2.InnerClass) # [GDScript:1162][GDScript:1162]
    print(HasInnerClass1.InnerClass.new().a) # 2
