### ISSUE TITLE
3D gizmo is distorted when zoomed by bottom panel

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#27112]
**Godot version:**
3.1

**Issue description:**
Expanding the bottom panel (Output, Shader, etc) zooms the 3D viewport and gizmos become distorted (see attached images).

May be related to #19116

**Steps to reproduce:**
Select a 3D object and expand the Output panel. Raise/lower the panel using the divider.
![gizmo](https://user-images.githubusercontent.com/3812514/54471019-54bb1700-476f-11e9-861c-bead80d2da4b.gif)
![Screen Shot 2019-03-15 at 10 02 36 PM](https://user-images.githubusercontent.com/3812514/54471027-6bfa0480-476f-11e9-9397-14b1c14914ff.png)

**Comment by JFonS** [comment]
I'm pretty sure that is a result of the crazy FOV of the camera (FOV depends on aspect ratio) and trying to keep the gizmo's screen size constant.  I'm not sure if there's a good way to fix that, other than having a smaller gizmo when the FOV exceeds a certain threshold.
