### ISSUE TITLE
WebSocketClient has no support for custom HTTP headers 

### ISSUE THREAD

**Issue by heri333** [godotengine/godot#27129]
**Godot version:** 3.1

**OS/device including version:** Not relevant

**Issue description:**

The ```WebSocketClient``` does not provide an option for custom HTTP headers on ```connect_to_url```, like for example ```HTTPRequest```. This is at least relevant for the usual HTTP authorization flows to work (Basic, JWT, etc.), before even upgrading the request.

**Steps to reproduce:** See API definition.

**Minimal reproduction project:** Not relevant.

**Comment by Faless** [comment]
> **Steps to reproduce:** See API definition.

What do you mean by that?

In any case, the Javascript WebSocket API do not allow you to send custom headers, so this cannot be done in general.

The only exception is cookies, which are passed along with the GET/UPGRADE request and reflect what was previously set for that domain, so we might add that to the native version for compatibility.

**Comment by heri333** [comment]
I just meant that the ```WebSocketClient``` API does not provide an option to set HTTP headers.

The initial HTTP upgrade request allows custom headers, which are supported by several clients ([node.js](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketClient.md), [Vert.x](https://vertx.io/docs/apidocs/io/vertx/core/http/HttpClient.html#websocket-java.lang.String-io.vertx.core.MultiMap-io.vertx.core.Handler-io.vertx.core.Handler-)).

I was not aware of the restriction of Godot to the HTML5 WebSocket client. If this is a hard restriction for HTML5 export reasons I assume, then I understand that.
