### ISSUE TITLE
Condition ' !_can_call_mode(p_node, rpc_mode, p_from) ' is true.   - Better error mesage

### ISSUE THREAD

**Issue by ripperdave** [godotengine/godot#27120]
**Godot version:**
3.1

**OS/device including version:**
Windows 7 Sp1

**Issue description:**
Multiplayer game. Networking, usability, debug.

I got this error message. **This issue is about the quality of the error message.**

Condition ' !_can_call_mode(p_node, rpc_mode, p_from) ' is true.
<C Source>     core/io/multiplayer_api.cpp:286 @ _process_rpc()

It would be helpful to enhance this error message with node or method names, so users could locate the issues easily.

Thank you.

**Comment by akien-mga** [comment]
One can use `ERR_EXPLAIN` before the `ERR_FAIL_COND` to set a user-friendly error message.

**Comment by Faless** [comment]
`ERR_EXPLAIN` is already there:
https://github.com/godotengine/godot/blob/320f49f204cfbf9b480fe62aaa7718afb74920a5/core/io/multiplayer_api.cpp#L285

If it's not being printed I suspect it's because it happened in a `release` build (i.e. `DEBUG_ENABLED` is not defined), where the message is stripped for performance reasons.

**Comment by akien-mga** [comment]
@ripperdave can you confirm that it prints a proper error in a debug build?

**Comment by Flairieve** [comment]
This error is also happening for me on debug build and it's not showing me any helpful information on where the error is occurring at.

**Comment by Faless** [comment]
> This error is also happening for me on debug build and it's not showing me any helpful information on where the error is occurring at.

Confirmed in editor.

Is `ERR_EXPLAIN` broken now? o_O

**Comment by Faless** [comment]
Okay, it's a nesting problem, the error string gets re-setted inside `_can_call_mode`, more specifically in `Node::is_network_master()`:
```
#0  Node::is_network_master (this=0x878f4d0) at scene/main/node.cpp:490
#1  0x0000000003380537 in _can_call_mode (p_node=0x878f4d0, mode=MultiplayerAPI::RPC_MODE_PUPPET, p_remote_id=473811449) at core/io/multiplayer_api.cpp:83
#2  0x0000000003377cb1 in MultiplayerAPI::_process_rpc (this=0x6271730, p_node=0x878f4d0, p_name=..., p_from=473811449, p_packet=0x508a6cc "", p_packet_len=21, p_offset=12)
    at core/io/multiplayer_api.cpp:286
#3  0x00000000033770fe in MultiplayerAPI::_process_packet (this=0x6271730, p_from=473811449, p_packet=0x508a6cc "", p_packet_len=21) at core/io/multiplayer_api.cpp:211
#4  0x00000000033762c7 in MultiplayerAPI::poll (this=0x6271730) at core/io/multiplayer_api.cpp:112
#5  0x00000000024b6f60 in SceneTree::idle (this=0x5f63240, p_time=0.0166666675) at scene/main/scene_tree.cpp:508
#6  0x00000000011a6df1 in Main::iteration () at main/main.cpp:1885
#7  0x000000000117954d in OS_X11::run (this=0x7fffffffd720) at platform/x11/os_x11.cpp:3006
#8  0x000000000116a473 in main (argc=4, argv=0x7fffffffde98) at platform/x11/godot_x11.cpp:55
```

**Comment by akien-mga** [comment]
Reopening as #27655 was reverted.

**Comment by austinprog** [comment]
Would it be ok if I get a go at trying to fix this? Not sure if it is still being worked on?

**Comment by Faless** [comment]
@austinprog sorry, I had the fix a month ago, always forgot to PR it :-( . Check it out if you like.

**Comment by austinprog** [comment]
No problem! I will keep searching for open bugs. It seems this project has over 4k issues so I am sure there is one I can find that I can work on. :D Cheers!
