### ISSUE TITLE
Editor settings keep getting reset

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#27124]
**Godot version:**
3.1

**OS/device including version:**
Ubuntu 18.04 LTS

**Issue description:**
I've been using Godot 3.1 for the couple of days. I've noticed the editor settings (as opposed to project settings) keep getting reset. I set the language to English and imported several projects, and two or three launches later, it's back to system language and no projects in the list. It's happened two or three times so far. I thought it was related to restarting the system/computer, but just now it happened without a restart in the middle.

(Tell me how to get more info? Where are the editor settings stored? The cache?)

**Steps to reproduce:**

**Minimal reproduction project:**
N/A

**Comment by Chaosus** [comment]
> (Tell me how to get more info? Where are the editor settings stored? The cache?)

C:\Users\<username>\AppData\Roaming\Godot\editor_settings-3.tres

**Comment by bojidar-bg** [comment]
Godot settings live in `$XDG_CONFIG_HOME/godot/editor_settings-3.tres` or `~/.config/godot/editor_settings-3.tres`.

**Comment by Zireael07** [comment]
It just happened again, the editor settings file after the event simply does not contain the projects at the end.
btw the projects folder in .config/godot is fine, it's just the editor settings that get mysteriously wiped. Judging by the last edited date, it happens WHILE editing (projects folder last edited 21:20, editor settings last edited 21:23)

**Comment by Zireael07** [comment]
I wasn't using Godot much the last month, but today it happened again. Since the settings live in ~/.config/godot/editor_settings-3.tres, and there is only one user on the computer, I think we can exclude permissions as the source of the issue. I also have no other Godot version present, so that's out, too.

If I was to guess, I'd say it happens every three-four launches.

**Comment by bojidar-bg** [comment]
@Zireael07 Do your projects live on a mount or something of the sort?

**Comment by Zireael07** [comment]
Nope, all projects are subdirectories of my home folder. The projects themselves are fine, just the editor settings file loses the project listing at the end, and the language selection (I switch to EN because it makes it easier to find/get help, and after the settings get reset, it's back to system language :/ )

**Comment by Calinou** [comment]
As a workaround for the editor language, you can start Godot with the `-l en` commanbd-line argument (which you could write into a `.desktop` file or launcher script).

**Comment by Zireael07** [comment]
Just upgraded to 3.1.1, still happening. I am starting to suspect some sort of a race condition when reading/saving the projects list?

Unfortunately I have not got any consistent way to reproduce it - sometimes it'll happen twice in a row, but most often it takes 3-4 launches for it to happen.

**Comment by cooperra** [comment]
My project list keeps resetting too. It seemed to start after I enabled a couple plugins, then the editor crashed or something. Even after deleting and recreating that project without the plugins, the problem recurs sometimes.

3.1.1 official build on Arch Linux

**Comment by KoBeWi** [comment]
It used to happen to me too, when I jumped between 3.1 and 3.2. Now it seems stable, although I had some shortcuts removed recently :/

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch / 3.2 builds?

**Comment by Zireael07** [comment]
The disk failed and I no longer have Godot installed, so I can't check.
Most likely it was some sort of a race condition or something to do with disk speed. Closing as it was probably my computer's fault and not Godot's.

**Comment by mechPenSketch** [comment]
This happens to me, too. My current version is v3.2.2.stable.official, accessed through steam. I don't know how to replicate this issue, though, it happens randomly and I don't know how to even diagnose it. I don't think this has to do with disc space, as this happens to me specifically when from the editor, I quit to project list.

**Comment by Calinou** [comment]
@mechPenSketch Which operating system are you on? It's probably better to open a new issue at this point.

**Comment by mechPenSketch** [comment]
^ I'm using Windows 10.

**Comment by stupidinternet** [comment]
same problem

**Comment by Calinou** [comment]
> same problem

This is now being tracked in https://github.com/godotengine/godot/issues/40968. Please continue the discussion there :slightly_smiling_face:
