### ISSUE TITLE
Class fields code completion does not work

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#27133]
**Godot version:** 3.1

**OS/device including version:** Ubuntu 18.04

**Issue description:**
No code completion for fields of class. E.g., "postion", "z_index", etc. Both following do not get completed:
```gdscript
print (position)
print (self.position)
```

**Minimal reproduction project:**
[repro_field_completion.tar.gz](https://github.com/godotengine/godot/files/2974219/repro_field_completion.tar.gz)

**Comment by bojidar-bg** [comment]
Uhm. The `Node` class does not have a `position`field. Did you mean to type `Node2D` instead?

**Comment by Chaosus** [comment]
Indeed, this can be fixed by extends Node2D )
