### ISSUE TITLE
Duplicate Custom Node entry when using a plugin with class_name and registering the node

### ISSUE THREAD

**Issue by NetroScript** [godotengine/godot#27132]
**Godot version:** 3.1

**OS/device including version:** Windows 10 64-bit

**Issue description:**
Previously (before `class_name`) you had to make a plugin to add custom nodes, so when you now update a plugin with static typing which creates a custom node you will probably use `custom_name` for the auto completion.  
The problem here is, you already registered a custom node with the plugin, so now you have a duplicate entry when adding a node (because of custom_class). Which is rather unwanted (although intended).  
So your choice is either to relinquish auto completion or don't register the node in the plugin. But if you don't register the node in the plugin and use `class_name` instead, the custom node is added even when the plugin is deactivated.  

![2019-03-16_19-11-01](https://user-images.githubusercontent.com/18115780/54479657-4593a200-481f-11e9-8781-acdc40330186.png)

So I would either expect when registering a custom type, that it is also available as class / type in the auto completion (under the registered name) or that when the script file has the same custom_name + resource path as the registered custom type that it "merges" the 2 entries into just one.

**Steps to reproduce:**

1. Create a plugin which registers a custom type
2. Use `custom_class` in the script file of the type with the same name as the registered custom type
3. Click "Add Child Node" - See duplicate entry

**Minimal reproduction project:**
[Bug Example.zip](https://github.com/godotengine/godot/files/2974177/Bug.Example.zip)
(New Node is called ExampleType in this project and extends ReferenceRect)

**Comment by akien-mga** [comment]
CC @willnationsdev

**Comment by KoBeWi** [comment]
Fixed in 4.4 (and probably earlier)
