### ISSUE TITLE
RigidBodys randomly instanced sleeping on Android

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#2713]
I move my zombies and bullets with set_linear_velocity(). On PC this works perfectly. On my Android phone however, about 1/4 of both object types just are not affected by set_linear_velocity() at all.
The zombies just stay where they are and the bullets just drop to the ground. 
Even though I can see in the log that set_linear_velocity() is called on them all the time.

Has anyone experienced something similar? How are physics done differently on Android?

Edit 1: I just tried apply_impulse() instead of set_linear_velocity(). The problem stays the same.

Edit 2: I tried with 2.0 ALPHA instead of my 1.1 custom build. The problem still exists, but it's now only about 1/15 of objects that are not touched by physics.

**Comment by ScyDev** [comment]
Setting "Can Sleep" to false on the RigidBody of these objects solves this problem.

However the question remains: Why does Godot set some objects to sleeping on Android? Is it a performance thing?

**Comment by reduz** [comment]
ah.. i think this was fixed on the 2D engine, should check..

**Comment by reduz** [comment]
It seems fixed in code, it's now calling wakeup() when you set linear velocity.. do you think you could make a small test that reproduces this?

**Comment by reduz** [comment]
well, haven't heard anything since.. closing this, please reopen if you can still reproduce and make an example project
