### ISSUE TITLE
Calling Particles2D.restart() no longer turns emitting on automatically if one_shot is true

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#27146]
**Godot version:**
3.1 stable

**Issue description:**
This is a change from 3.0.6 -> 3.1.  When scripts or AnimationPlayer relies on calling restart() to begin re-emitting one-shot particles, they do not seem to trigger if the emitting state has been set to false initially unless `emitting` is also set to true.  All one-shot particle bursts in my game had this issue when upgrading project to 3.1.  Solution was to set emitting to true right after `restart()` in all cases where necessary.

possibly related to #21794

**Comment by jesperkondrup** [comment]
We are having the same issue I think. 
Working with One shot Particles that needs to activate through the AnimationPlayer is a nightmare and it feels a bit random if particles are spawning or not when you play the animation. It also seems to depend on the Life time of the particle some how.. but I am not sure what it going on.  

We tried creating a new track in the animation that calls the restart() on the particles but without any luck, so I can agree that this seems like a bug.
