### ISSUE TITLE
OS.get_power_percent_left() always returns -1

### ISSUE THREAD

**Issue by tree786** [godotengine/godot#27143]
**Godot version:**
Tested in 3.0.6 (stable) and 3.1 stable

**OS/device including version:**
Samsung Galaxy S6

**Issue description:**
Using OS.get_power_percent_left() always returns a negative value (-1), even when the phone is not fully charged. Shouldn't it return a positive fraction (e.g. 0.5 if 50% charged)?

**Steps to reproduce:**
OS.get_power_percent_left()

**Comment by williamd1k0** [comment]
Related: #8770

**Comment by akien-mga** [comment]
Power management on Android was disabled by @reduz in b5a06cecffeda556438b33807d766f4823623fee, and nobody tried to reenable it since then.

**Comment by akien-mga** [comment]
Closing as it's tracked in #8770 already.
