### ISSUE TITLE
GLES2 Sprite3D Z order Bug

### ISSUE THREAD

**Issue by GustavoMarciano** [godotengine/godot#27141]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows10

**Issue description:**
GLES2 Sprite3D Z order is broken
the depth still exists but appears to be inverted?

**Steps to reproduce:**
create a project in gles2 and create  2 sprite3d

Gles3:
![Gles3-render](https://user-images.githubusercontent.com/23220658/54482150-ade18400-481d-11e9-8363-e6cabb0d3b1d.png)

Gles2:
![Gles2-render](https://user-images.githubusercontent.com/23220658/54482156-c05bbd80-481d-11e9-89ee-006119fc8be1.png)

**Minimal reproduction project:**
[Sprite3D.zip](https://github.com/godotengine/godot/files/2974521/Sprite3D.zip)

**Comment by bojidar-bg** [comment]
Does the same occur in GLES3? A screenshot would be welcome as well.

**Comment by GustavoMarciano** [comment]
> Does the same occur in GLES3? A screenshot would be welcome as well.

done

**Comment by semirix** [comment]
I think the problem has something to do with z-ordering when transparency is enabled. Have you tried changing the material to disable transparency?

**Comment by GustavoMarciano** [comment]
> I think the problem has something to do with z-ordering when transparency is enabled. Have you tried changing the material to disable transparency?

Thanks, that was the problem, to solve it was just put **Use alpha scissor: On**

**Comment by semirix** [comment]
@GustavoMarciano Could you reopen this issue open? You may have solved the problem but this is still a bug in default behaviour. You shouldn't need to turn on Alpha Scissor to fix the z-ordering.

**Comment by faculezcano** [comment]
could be related to #26703 ?
