### ISSUE TITLE
Area2D stops working when you click on an area2d node in the inspector

### ISSUE THREAD

**Issue by Flairieve** [godotengine/godot#27142]
**Godot version:**

v3.1.stable.official

**OS/device including version:**

Windows 10

**Issue description:**

For some reason I noticed if an Area2D node is selected in the editor inspector and you run your game, the Area2D node that you clicked on will no longer work until you click off of it in the editor inspector and restart your game.

**Steps to reproduce:**
1. Click on an Area2D node.
2. Run your game.
3. Area2D node no longer works.

**Comment by eon-s** [comment]
Cannot reproduce on Ubuntu 18.04 using the coins on the platformer demo.
With inspector you refer to the scene tree?

**Comment by Flairieve** [comment]
Yea im referring to the scene tree, also i forgot to mention but the Area2d node comes from a scene.

**Comment by girng** [comment]
wait, the area2d no longer works in the game, or in the editor?

**Comment by Flairieve** [comment]
It no longer works in the game once you click on the Area2D node in the inspector.

**Comment by Flairieve** [comment]
I tested this out on v3.2.3 and I assume whatever bug that was happening was fixed, so I guess it's fixed.
