### ISSUE TITLE
Setting CanvasItemMaterial.particles_animation frames affects Particles2D.visibility_rect

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#27147]
**Godot version:**
3.1 stable

**Issue description:**
This may be a purely aesthetic issue.  When adjusting `particles_anim_h_frames` or `particles_anim_v_frames`, the visibility rectangle in the editor is affected.  I'm not sure what the intended use of the visibility rect is, other than perhaps being a visual reference for the developer to use when particles aren't being actively emitted, but if that's the case, the way the rect displays shouldn't change at all when the anim frames change, unless its intended usage is somehow coupled to the particle texture itself.

![image](https://user-images.githubusercontent.com/1023003/54483807-09b10a80-4828-11e9-8a78-9ee8f3665b1d.png)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/50515, which has more information about the issue at hand.
