### ISSUE TITLE
Heightmap collision shape fails for fast moving objects

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#27157]
**Godot version:**
I'm using commit 8627f1515b7248168f988f77b899d786c2e2d7ad that includes PR #27156 
This is based on master df7d3708c5b535c3696943322a14ec19a175e30c

You don't need the PR to test this but you'll have to create the collision shape directly on the physic server.

**OS/device including version:**
Windows 10

**Issue description:**
I'm dropping a few balls on a test heightmap to see if it works. When the balls are moving too fast they will drop through the heightmap

This is possibly an upstream bullet issue.

**Steps to reproduce:**
Create a suitable heightmap collision shape using PhysicsServer::SHAPE_HEIGHTMAP either through the aforementioned PR or directly on the physics server.

Create some other rigidbody shapes and make them fall onto the height field. If you drop them from high enough, they drop straight through.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2975001/test.zip)

**Comment by Zylann** [comment]
Isn't it classic tunnelling that CCD would usually solve? It would seem Bullet considers heightmap as a normal surface so if you end up below it, you stay below it (and that's actually a good thing if you want caves).

**Comment by BastiaanOlij** [comment]
@Zylann yup, damn forgot to respond to this all that time ago. Indeed CCD solves this.
Currently looking at it again because I am having issues right now with move_and_slide not interacting with the heightmapshape... Might be the same issue but there doesn't seem to be a CCD option here

**Comment by akien-mga** [comment]
I'll close for now as it seems the initial issue was a misunderstanding.

> Currently looking at it again because I am having issues right now with move_and_slide not interacting with the heightmapshape...

If this is still valid, might be worth opening a new issue about it.
