### ISSUE TITLE
Code completion for members/methods inherited from built-in classes does not work properly

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#27152]
**Godot version:** 3.1

**OS/device including version:** Ubuntu 18.04

**Issue description:**
Say, we have the following inheritance tree (`<---` means 'inherits' or 'extends'):
```
Node2D <--- intermediate.gd <--- script.gd <--- another_script.gd
```

Node2D's members and methods are in the completion list only for `intermediate.gd`:
```gdscript
# intermediate.gd
extends Node2D
class_name Intermediate

func _ready():
	# COMPLETION WORKS
	print (position)
	
	# COMPLETION WORKS
	rotate(1)

func custom_func():
	pass
```

Same members and methods ***are not*** listed if you edit scripts that inherit `intermediate.gd`:
```gdscript
# script.gd
extends Intermediate

func _ready():
	# NO CODE COMPLETION FOR INHERITED FIELDS
	print (position)
	
	# COMPLETION DOES NOT WORK
	rotate(1);
	
	# COMPLETION WORKS QUITE WELL
	custom_func()
```
```gdscript
# another_script.gd
extends "res://script.gd"

func _ready():
	# COMPLETION WORKS
	custom_func()
	
	# COMPLETION DOES NOT WORK
	print (position)
	
	# COMPLETION DOES NOT WORK
	rotate(1)
```

The only dirty work-around for this is to simply cast `self` to whatever class you inherit:
```gdscript
# script.gd
# ...
    # why do I have to cast to the class I already inherit to get code completion?
    (self as Node2D).rotate(1)
# ...
```

**Minimal reproduction project:**
[repro_field_completion.tar.gz](https://github.com/godotengine/godot/files/2974859/repro_field_completion.tar.gz)

**Comment by MaciejGorczycaGD** [comment]
Thanks for the reference yes my issue is identical on windows.

**Comment by aleksfadini** [comment]
This is the singe thing that breaks all my projects when going from 3.0 to 3.1.
Same bug on linux as well.
