### ISSUE TITLE
Rotated Node2D resizing cursor points unnaturally

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#27155]
**Godot version:**

3.1

**OS/device including version:**

Manjaro x86_64

**Issue description:**

Expected: up-down arrow when dragging right handle of a ~90 degrees rotated node
Happened: left-right arrow appears
![image](https://user-images.githubusercontent.com/43379543/54486776-a4105d00-48bf-11e9-9d8c-2ea677709f88.png)

Compared to LibreOffice:
![image](https://user-images.githubusercontent.com/43379543/54486818-1aad5a80-48c0-11e9-9cfa-b501c618be88.png)

**Steps to reproduce:**
1. new Node2D
2. rotate
3. grab a handle and resize

**Comment by akien-mga** [comment]
Still reproducible in the 3.2.2 RC 2.
Should be fairly easy to fix (the cursors should take the transform into account).

**Comment by SekoiaTree** [comment]
Made a fix: https://github.com/godotengine/godot/pull/41085
