### ISSUE TITLE
Steam not counting hours

### ISSUE THREAD

**Issue by UnleavenedEagle** [godotengine/godot#27158]
**Godot version:**

v3.1.stable.official

**Issue description:**

Steam is counting hours spent in Godot only if you are in the Project Manager. Meaning while you are editing a projects, hours will not get counted.

What I suspect the issue is, is that the Godot executable exits, when you select the projects and starts again. Instead you could implement it so it makes a subprocess of itself. So with this solution, I do not think Steam specific binaries would need to be implemented.

Useful tool (for Windows): Process Explorer (can be downloaded from Microsoft's website).

**Steps to reproduce:**
1. Download Godot from Steam.
2. Open Godot.
3. Open a project.

**Comment by Chaosus** [comment]
Duplicate of #18233
