### ISSUE TITLE
Tag the 3.1 release

### ISSUE THREAD

**Issue by codingHahn** [godotengine/godot#27163]
Could somebody please tag the 3.1 release? I need it for updating my distro's package. Thank you

**Comment by Calinou** [comment]
It seems to be tagged, but there's no release associated on GitHub so it's difficult to notice on the Releases tab: https://github.com/godotengine/godot/releases/tag/3.1-stable

**Comment by akien-mga** [comment]
There was indeed a tag already. Not sure why GitHub makes such a difference between tags and releases, but here we are with the release: https://github.com/godotengine/godot/releases/tag/3.1-stable

And the release date is wrong, but well...
