### ISSUE TITLE
Creating animation key for Label/RichTextLabel's font_color creates error when font_color not enabled

### ISSUE THREAD

**Issue by regakakobigman** [godotengine/godot#27165]
**Godot version:**

3.1

**OS/device including version:**

Windows 8.1 64-bit

**Issue description:**

When using an AnimationPlayer to animate the text_color property of a label, trying to create a key creates an error. This does not happen when using Bezier curves.

This can be solved by enabling the font_color property, but when using Bezier curves this is not required, leading to inconsistent behavior.

This is the error:
`core/undo_redo.cpp:291 - Error calling method from signal 'track_insert_key': 'Animation::track_insert_key': Method expected 3 arguments, but called with 2.`

The expected behavior is that animation keys can be created, but will only work if the font color property is enabled. This is what happens when animating font color with Bezier curves. Instead, they cannot be created at all and an error is printed to the console.

**Steps to reproduce:**
1. Add AnimationPlayer
2. Add Label or RichTextLabel child
3. Create new animation track for text_color (or any font color property of RichTextLabel)
4. Attempt to insert animation key

**Minimal reproduction project:**

[AnimationPlayer Label Text Color.zip](https://github.com/godotengine/godot/files/2975300/AnimationPlayer.Label.Text.Color.zip)

**Comment by moechofe** [comment]
I got the same error while try to add a Insert Key on a custom non-exported property of a script

**Comment by Itachi124** [comment]
Still reproducible in Godot 3.2.3 stable.

**Comment by KoBeWi** [comment]
Tested in 4.0 alpha7, no error.
Weird enough, the checkbox appears when you inspect animation key:
![image](https://user-images.githubusercontent.com/2223172/166340391-35fe6fa0-8212-4ad9-a924-0a8fb08e9ea2.png)
And the key has effect only when checked. But no errors when unchecked, so fixed.
