### ISSUE TITLE
Inconsistency between preview and in-game

### ISSUE THREAD

**Issue by pcmxms** [godotengine/godot#27169]
**Godot version:**
3.1-stable

**OS/device including version:**
Manjaro Linux 18.0.3

**Issue description:**
There is an inconsistency between the editor preview and the in game behaviour of poligon2d deformation using bones. 

**Steps to reproduce:**
Create a node
Create a poligon2d node
In poligon2d, add a texture
In the UV menu of poligon2d, create a poligon for the texture
Create a skeleton2d as a "brother" of poligon2d
Create a bone, son of Skeleton2d
Create another bone, son of the previous bone
Make a Rest pose for the skeleton2d
Go to poligon2d and associate the skeleton2d to the skeleton property
Synchronize bones with the poligon
Go nuts editing it.

**Minimal reproduction project:**
[Yet Another Stick Try.zip](https://github.com/godotengine/godot/files/2975443/Yet.Another.Stick.Try.zip)
Search for "PlayerNew.tscn" on player folder.

More material:
[Bug_Videos.zip](https://github.com/godotengine/godot/files/2975445/Bug_Videos.zip)
![ProjectTree](https://user-images.githubusercontent.com/19173048/54494848-5b57a480-48bd-11e9-8e33-688d1dd64309.png)

**Comment by akien-mga** [comment]
Seems fixed in the current master branch, the PlayerNew scene looks the same both in editor and in-game.
