### ISSUE TITLE
Allow continuous movement with Alt+Up / Alt+Down in script editor

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27164]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64

**Issue description:**
When I want to move a line, up and down, inside the editor, when I press, for example, Alt+Up, it moves just 1 line. 
In any other editors, if a keep it pressed, it continues to move the line.
But in the current editor, if I want to move 10 lines, I have to press Alt+Up 10 times.

**Steps to reproduce:**

Select one line, keep Alt+Up or Alt+Down pressed and it will move the line just 1 time.

**Comment by KoBeWi** [comment]
This was resolved as a side-effect of #28787
