### ISSUE TITLE
RandomPCG::seed does not properly seed PCG32

### ISSUE THREAD

**Issue by toasteater** [godotengine/godot#27166]
**Godot version:** 3.1 stable, still in df7d370 (current master)

**OS/device including version:** N/A

**Issue description:** RandomPCG::seed is different from PCG32's original seeding function. As such, the statistical performance of the original PCG32 cannot be assumed for the current implementation.

Godot's random_pcg.h:

```cpp
_FORCE_INLINE_ void seed(uint64_t p_seed) {
	current_seed = p_seed;
	pcg.state = p_seed;
	pcg32_random_r(&pcg); // Force changing internal state to avoid initial 0
}
```

Actual srandom function from PCG's C minimal implementation: https://github.com/imneme/pcg-c-basic/blob/master/pcg_basic.c

```c
// Copyright 2014 Melissa O'Neill <oneill@pcg-random.org>, Licensed under the Apache License, Version 2.0
void pcg32_srandom_r(pcg32_random_t* rng, uint64_t initstate, uint64_t initseq)
{
    rng->state = 0U;
    rng->inc = (initseq << 1u) | 1u;
    pcg32_random_r(rng);
    rng->state += initstate;
    pcg32_random_r(rng);
}
```

**Steps to reproduce:**  N/A

**Minimal reproduction project:** N/A

**Comment by Chaosus** [comment]
If you look at http://www.pcg-random.org/downloads/pcg-c-basic-0.9.zip you will see that its almost equal to current implementation -

> // pcg32_random()
> // pcg32_random_r(rng)
> //     Generate a uniformly distributed 32-bit random number
> 
> uint32_t pcg32_random_r(pcg32_random_t* rng)
> {
>     uint64_t oldstate = rng->state;
>     rng->state = oldstate * 6364136223846793005ULL + rng->inc;
>     uint32_t xorshifted = ((oldstate >> 18u) ^ oldstate) >> 27u;
>     uint32_t rot = oldstate >> 59u;
>     return (xorshifted >> rot) | (xorshifted << ((-rot) & 31));
> }

According to http://www.pcg-random.org/using-pcg-c-basic.html the `pcg32_srandom_r` is just an initializer function(heh I miss it when creating fix for https://github.com/godotengine/godot/issues/17664) for generator and it uses pcg32_random_r internally..

**Comment by Chaosus** [comment]
nvm.. you looks for seed, I understand you now
