### ISSUE TITLE
Bind CanvasItemEditor._zoom_on_position() to ClassDB

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#27179]
**Godot version:**
3.1 stable

**Issue description:**
Related to #25693.  I don't know enough about the codebase yet to implement my preferred solution (an editor setting that changes the zoom button's default ratio) as a PR and am unsure if it would be accepted anyway, so this is a simple request for cherrypicking to 3.1.x branch.   If CanvasItemEditor._zoom_on_position() was exposed to the editor, 3rd party addons could manually set the viewport's zoom in a way that plays nice with the 2d editor.  There are hacky ways to change the current scene's viewport size, but the editor seems to recognize its internal `zoom` property (also unexposed) as the canonical one and will draw guides at that zoom level only.  

I'm not sure if anything else would need to be done to make it possible for addons to change zoom level manually, but if this is all that needs to be done, it's pretty much a one-line change.

Thanks!

**Comment by Calinou** [comment]
Still relevant as of https://github.com/godotengine/godot/commit/b4b7c97d3839170180e4f3f7c2bd3179b374057a. `_zoom_on_position` is bound in TextureRegionEditor but not CanvasItemEditor.
