### ISSUE TITLE
Breakpoints change InputEventMouseButton properties when using custom signals

### ISSUE THREAD

**Issue by TicklesTheBrain** [godotengine/godot#27177]
**Godot version:** 3.1 stable

**OS/device including version:** Windows 10

**Issue description:**

When using breakpoints in a function that is called as a result of a user defined signal, the next mouse click event after hitting continue will have the same input event coordinates as the previous one. Everything works properly without using breakpoints. Everything works fine (both with and without breakpoints) if the input signal is connected directly to the breakpointed function, without the intermediate user defined signal.

I was advised in the Discord that it was perhaps related to losing focus, but since I couldn't find any similar issues, I am creating one here

**Steps to reproduce:**
1. Create node A
2. Create node B as a child of A.
3. Create a control node C as a child of B.
4. Connect _gui_input event to function in Node B.
5. In node B function make it emit a user defined signal.
6. Connect user defined signal to function in Node A.
7. Add a breakpoint somewhere in Node A's function.
8. Run, trigger gui_input in C.
9. In the debugger click continue.
10. Trigger gui_input in C again.
11. Observe - input event has the same coordinates as in the previous event. 

**Minimal reproduction project:**
1. Run the project once.
2. Observe the editor output is correct when clicking on colours.
3. Add breakpoints in line 4 of Node2D.gd
4. Run again and click on any colour.
5. In the debugger click continue.
6. Click on a different colour.
5. In the debugger click continue.
7. Observe the editor output is the same, despite having clicked a different colour.

[breakpointBug.zip](https://github.com/godotengine/godot/files/2975554/breakpointBug.zip)

**Comment by KoBeWi** [comment]
Fixed in 3.2
