### ISSUE TITLE
Allow remainder (%) operator to use floats

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27173]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64

**Issue description:**
While in Python I can have for example `2.0 % 1.01` resulting in `0.99`, in GDScript I get this error: `Invalid operands 'float' and 'float' in operator '%'`.
I know `fmod` can do this, but this suggestion is to make it more similar to Python.

**Comment by timoschwarzer** [comment]
There's `fmod(...)` for that.

**Comment by Chaosus** [comment]
Gdscript translates to C calls which are not supports such syntax sugar, by doing so we need to write a cumbersome logic for little gain

**Comment by akien-mga** [comment]
Duplicate of #10004.

This was already rejected by @reduz with:

> it's not a bug, it's a feature (tm),intended to avoids mistakes. Use fmod() for floats.

And I still think that's the right approach. Having remainder work for both floats and ints can lead to bugs which are hard to debug (like giving you a float as result for an operation where you expected an int), so it's better to be explicit.

**Comment by rogeriodec** [comment]
Ok, no problems. Closing.
