### ISSUE TITLE
Inspector dropdown boxes from exported vars close on their own while trying to change their value

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#27175]
**Godot version:**
3.1 stable official

**OS/device including version:**
Windows 64

**Issue description:**
Inspector dropdown boxes from exported vars close on their while trying to change their value, after editing script. Saving and reopening scene fixes the issue temporarily. I'm guessing the inspector steals focus from it's own exported var's dropdown menus and it's an issue related to #24979 (which was fixed with a workaround). It's just a guess though.

In this example I don't click inside the dropdown, it closes on it's own:
![2019-03-17_17-10-05](https://user-images.githubusercontent.com/7307968/54494136-84852e80-48d7-11e9-8bd0-dc5d1c6f6564.gif)
The code used was:
`export(Enums.EntityModes) var can_trigger_in_mode = Enums.EntityModes.ENTITY_MODE_FOLDED`

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch / 3.2 builds?

**Comment by KoBeWi** [comment]
Seems to be fixed
![Sf8t400JLM](https://user-images.githubusercontent.com/2223172/72444939-34a21d00-37b1-11ea-9999-8942795eca4d.gif)

**Comment by PLyczkowski** [comment]
Yeah, I haven't encountered this issue for a while now using the betas.
