### ISSUE TITLE
MIDI Note Off message never fires (on some devices)

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#27199]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10 x64;  MIDI Controller:  Keyrig 49

**Issue description:**
`_input()` receives Note Off messages as `MIDI_MESSAGE_NOTE_ON` instead.  This has the effect of doubling any event which filters out any message that isn't NOTE_ON.  

**Steps to reproduce:**
Add an AudioStreamPlayer to a scene and assign a sound.  Then use the following code:
```gdscript
func _ready():
	OS.open_midi_inputs()

func _input(event):	
	if event is InputEventMIDI:
		print (event.message)
		if event.message != MIDI_MESSAGE_NOTE_ON:  return
		
		var pitch 
		if event.pitch >= 48:
			pitch =  (event.pitch-36) / 12.0 
		else:
			pitch = event.pitch / 48.0

		$Sound.volume_db = -(1-(event.velocity/128.0)) * 15
		$Sound.pitch_scale = pitch
		$Sound.play()
```

Sound will play twice when a key is struck, once on note on and once on note off.

**Comment by bojidar-bg** [comment]
CC @marcelofg55

**Comment by marcelofg55** [comment]
I've just tested this and it works fine for me:

```
** Debug Process Started **
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 4000
9
8
9
8
9
8
9
8
** Debug Process Stopped **
```

What's the output you get on the console?

**Comment by nobuyukinyuu** [comment]
Output is a couple of 9s, one for the note on event, and another for the note off event.  There are different MIDI drivers used depending on your OS, and the issue may be related to the controller used, so it will be helpful when testing to mention those!

**Comment by nobuyukinyuu** [comment]
I tried testing for controller changes but the only events coming through were as expected, just that the note off event reports itself as a note on event.

**Comment by nobuyukinyuu** [comment]
Have just confirmed with my device that this is definitely the issue.  Some controllers will not send Note Off events, but instead will send a Note On event with 0 velocity.  Discussion on the forum thread is interesting as note off velocities would probably be helpful on some controllers (theoretically). Developers working with coding for MIDI devices are likely to be thrown off by this unexpected, but (apparently) not-uncommon behavior, however.

Should this be something covered in the future documentation for the MIDI support, or should there be an option on how to treat this behavior?  MIDI's a very old spec, so there are bound to be plenty of odd cases like this where the de facto standard doesn't always necessarily match spec.
