### ISSUE TITLE
[HTML5] ConfigFile.load returns ERR_CANT_OPEN

### ISSUE THREAD

**Issue by Rybadour** [godotengine/godot#27196]
**Godot version:**
3.1.stable.official

**OS/device including version:**
HTML5, Chrome, Windows 10

**Issue description:**
When running in a HTML5 exported game the following auto-loaded script attempts to load a Config.ini file but fails and the error is ERR_CANT_OPEN. This code works fine when I run the project locally or from a Windows executable export. Config.ini is at the root of the project. 

```
extends Node
class_name Config

var configFile: ConfigFile = ConfigFile.new();
onready var err = configFile.load("res://Config.ini");
```

I see no network requests for this file so I assume it's expected to be packaged as part of the wasm file.

Is there some additional setup I need to do for custom config files like this? Is "res://" not valid for HTML5?

Thank you!

**Comment by eska014** [comment]
To include .ini files for export, you must add `*.ini` to the list of non-resource files to export in the Resources tab of the export dialog. This must be done for every export preset individually.

**Comment by Rybadour** [comment]
This worked! Thank you.

So I guess the implication is that only standard assets like images, sounds, 3D model files, etc will be exported by default?

Perhaps this page should mention that: https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_for_web.html

**Comment by eska014** [comment]
Only files recognized as Resources by Godot will be exported with the default mode, unless manually added. This is true when exporting for any platform. https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_projects.html#export-mode

**Comment by Rybadour** [comment]
Well if that's true then there is some inconsistency. When I exported to Windows I did not have to do anything the ini file was included by default.
