### ISSUE TITLE
Godot seems to need optimization, such as batch, tailoring

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#27194]
Godot seems to need optimization, such as batch, tailoring。。。

Canvas Item, invisible outside the screen, also seems to be involved in drawing。

**Comment by girng** [comment]
have you tried the `VisibilityEnabler` node?

**Comment by cjmxp** [comment]
This does not seem to be enough for rendering clipping.

**Comment by girng** [comment]
@cjmxp if possible,    create an example project of the lag. i'm sure a developer can help isolate the optimization options
