### ISSUE TITLE
RigidBody2D set_friction(1) not working

### ISSUE THREAD

**Issue by ahervella** [godotengine/godot#27203]
**Godot version:**
3.1 Stable (March 13th release)

**Issue description:**
I've been working on my 2D platformer for a while on the 3.0 stable release and just upgraded to 3.1 stable. Everything works great except the friction for my RigidBody2D seemed a bit broken. Whenever I set the friction to 0 in the script, there was no way to set it back to 1. As long as the script sets it to 0 once, there's no going back. Am I using friction wrong in the latest version or is it a bug? Thanks~

**Steps to reproduce:**
1- add 2D static body with collider, rotate to give a slight slope
2-add 2D rigid body with collider and texture to see
3-In rigidbody script, turn friction off, then on in next line. Bug makes friction stay off regardless

**Minimal reproduction project:**
[friction-bug-tester.zip](https://github.com/godotengine/godot/files/2978187/friction-bug-tester.zip)

**Comment by bojidar-bg** [comment]
Godot 3.1 added the notion of PhysicsMaterial-s, deprecating the older friction and bounce properties. It is supposed to automatically convert the older-style friction and bounce to the newer way, though.
