### ISSUE TITLE
`2d/thread_model=2` causing memory leaks

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#27217]
**Godot version:**
v3.1-stable

**OS/device including version:**
ArchLinux rolling + NVidia GPU

**Issue description:**
Adding `2d/thread_model=2` to `[physics]` section of `project.godot` causes memory leaking (around 1-2 KB per second) with spikes up to 50 KB (which are later freed).

**Steps to reproduce:**
- Add `2d/thread_model=2` to `[physics]` section of `project.godot`

**Comment by qarmin** [comment]
I don't think that is memory leak(Valgrind shows nothing), maybe this is a queue which is cleared after some amount of time or something similar.

**Comment by akien-mga** [comment]
As per above comment, it doesn't seem to be memory leaks, just thread-specific memory.
