### ISSUE TITLE
Allow disabling of Scale handles in 2D editor

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27213]
I would like the ability to disable the scale handles on 2D nodes, like Sprite for example. My team does not use them, as we prefer absolute and precise values over those the handles return, yet occasionally miss click on a handle when selecting other nodes, causing a tiny amount of scaling to occur that can be hard to catch until you dig into the inspector to find out why things no longer align. This also goes for the extends handles for collision shapes.

**Comment by akien-mga** [comment]
CC @groud

**Comment by TheDuriel** [comment]
Closing out of lack of interest.
