### ISSUE TITLE
Editor Setting "Disable Inspector Folding" has no effect

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#27229]
**Godot version:**

3.1 stable official 64bit

**OS/device including version:**

Windows 8.1

**Issue description:**

With "Disable Inspector Folding" set to ON in Editor settings, new nodes are created with all properties collapsed. The same happens when "Disable Inspector Folding" is set to OFF.
So "Disable Inspector Folding" has no effect.
 
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Kanabenki** [comment]
This seems to be a leftover in your godot config from a previous version, I had the same. The relevant setting has been moved to Interface -> Inspector -> Disable Folding.

You can remove the "Disable Inspector Folding" wich is now useless by deleting the line with interface/editor/disable_inspector_folding from your godot config file.

**Comment by PullTheStrings** [comment]
I have found that in Editor settings: Interface-Editor AND Interface-Inspector "Disable Folding" options are set to ON then it works.

**Comment by KoBeWi** [comment]
See this issue: #26323

**Comment by akien-mga** [comment]
Can't be fixed, same reason as https://github.com/godotengine/godot/issues/26323#issuecomment-469430959
