### ISSUE TITLE
Please add support export Godot Game to Android can with resource pck file.

### ISSUE THREAD

**Issue by lefay1982** [godotengine/godot#27224]
**Godot version:**
3.1 stable

**OS/device including version:**
Android, IOS

**Issue description:**
Please add support export Godot Game to Android can with resource pck file, like windows export
```
myGame.exe
myGame.pck
```
godot can export project to pck file format , and can load pck by load_resource_pack().
Can Godot add a feature: export to Android apk with pck file one click?

**Comment by akien-mga** [comment]
To clarify, you ask for an export option that would give an .apk without the game data, and a .pck next to it that should be loaded at runtime by the APK, as done for desktop exports? I don't know if that's doable on Android given the limitations of the filesystem and installation process.

**Comment by Calinou** [comment]
What use cases do you have in mind for this? [APK Expansion](https://developer.android.com/google/play/expansion-files) makes it possible to upload large applications to Google Play.

**Comment by lefay1982** [comment]
@Calinou I want to pack my script and resource to one file. and can encrypt them. so someone hack to obtain it is very hard.

**Comment by sprite-1** [comment]
@lefay1982 you can export the PCK directly using this button

![image](https://user-images.githubusercontent.com/33685433/67268285-a5090d00-f4e6-11e9-84f1-013edac959e4.png)

**Comment by Calinou** [comment]
Closing, as exporting to Android already creates a PCK file. It just happens to be embedded inside the APK, so you don't see it on your filesystem directly.

**Comment by Filippopotamus** [comment]
This is a valid use case. We've cloned Godot source and modified the android export to allow godot to run as a view inside of an existing Android app. We compiled the godot .aar module and added it to our Android project and exported the .pck from godot to be consumed by our godot module. However, it is extremely slow to load (16 seconds to load assets), meanwhile an .apk exported directly from godot loads in 0.3 seconds. Why is that? I've decompiled the .apk and didn't see an .pck file inside, instead all of the resources were inside of the `assets` folder with `project.binary` in there.

**Comment by Calinou** [comment]
@Filippopotamus Please open a proposal on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository, as this is where feature proposals are now tracked.

**Comment by Filippopotamus** [comment]
@Calinou will do. In the meantime, off the top of your head, can you think of any reason why loading from .pck on android is so slow while on ios is basically instant?

**Comment by bruvzg** [comment]
There are opened proposals for the similar features: https://github.com/godotengine/godot-proposals/issues/946 and https://github.com/godotengine/godot-proposals/issues/947

**Comment by Calinou** [comment]
@Filippopotamus I don't know why exactly. Maybe it's extracting the PCK from the APK every time a file is loaded from its virtual filesystem? That seems quite unlikely still.

**Comment by Filippopotamus** [comment]
@thanwah sure thing. I've invited you to a `GodotTest` project repo as well as to a clone of Godot where I made some changes (which GodotTest uses)

**Comment by divshekhar** [comment]
Hi @Filippopotamus @thanwah, I also ran across the same problem. Would love to know how exactly are you able to run .pck in apk. Do you mind adding me as a contributor to your test project? Thanks!
