### ISSUE TITLE
Godot 3.1 does not start on Linux 32

### ISSUE THREAD

**Issue by Bhgt** [godotengine/godot#27226]
**Godot version:**

3.1

**OS/device including version:**

Ubuntu 18.04.2 32bit

**Issue description:**

Godot editor does not start up at all. On running through the terminal, the editors seems to crash with *signal 11*.

**Terminal output:**
XInput: Refreshing devices.
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] linux-gate.so.1(__kernel_sigreturn+0) [0xb7f39d14] (??:0)
-- END OF BACKTRACE --
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] linux-gate.so.1(__kernel_sigreturn+0) [0xb7f39d14] (??:0)
-- END OF BACKTRACE --
Only one GPU found, using default.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] linux-gate.so.1(__kernel_sigreturn+0) [0xb7f39d14] (??:0)
-- END OF BACKTRACE --
Aborted (core dumped)

**Steps to reproduce:**
Start the Godot editor on Ubuntu 18.04 32bit version.

**Comment by Zireael07** [comment]
Err, I thought Ubuntu 18.04 only had a 64 bit version?

**Comment by qarmin** [comment]
Maybe it is an update from 16.04 32bit

**Comment by Calinou** [comment]
@Bhgt What graphics card do you have? (Try running `glxinfo | grep renderer`.)

**Comment by Bhgt** [comment]
> @Bhgt What graphics card do you have? (If you don't know, try running `glxinfo | grep renderer`.)

AMD CEDAR (DRM 2.50.0 / 4.15.0-46-generic, LLVM 7.0.0)

**Comment by JeremiahLR** [comment]
Same issue here as well!

**Comment by akien-mga** [comment]
Seems the be the same issue as #27496, I'll close this one as duplicate as the other one is slightly clearer.
