### ISSUE TITLE
Exported project with utf8 chars in resource name fails to load scene, works fine in editor

### ISSUE THREAD

**Issue by AzariasB** [godotengine/godot#27225]
**Godot version:**
 3.1-stable

**OS/device including version:**
Windows 10 64 bits
Ubuntu 18.04

**Issue description:**
What happened : 
When importing a resource containg utf8 chars in it (like 'é' or 'è'), the scenes using the resources works fine when used in the editor, but when the project is exported, these scenes fail to load.
The error looks like #21524 but the cause is not the same.

What was expected:
Either the scenes fails to load in the editor so it's possible to know before exporting that there is an issue with utf8 file names,
or the scene loads in the exported binary.

**Steps to reproduce:**
- Create a godot project
- Import a resource called "carré.png"
- Add a sprite to the scene that displays the texture "carré.png"
- Launch the project on the editor (it works fine)
- Export the project for any platform
- Launch the binary (the scene fails to load)

**Comment by jdbener** [comment]
I was unable to reproduce the issue, on Arch (Kernel 4.20.15 64bit). Were you using a 3D or 2D sprite?

**Comment by volzhs** [comment]
For Android, it does not support utf8 file name for assets, buy only ascii.

**Comment by AzariasB** [comment]
That's a my bad from me.
When looking back at my projects structure :  the problem seems to be quite different. I modified the name of a file used in a tileset then exported the project.

So the issue is quite different from what i thought.
I'm closing this issue as it is no longer relevant.
