### ISSUE TITLE
Broken animations in gltf import

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#27239]
**Godot version:** 3.1 64

**Issue description:**
Exported rigged model from Blender 2.80 (latest version from their site - d47f827019f2) has broken some bones in animations after import to Godot.

**Steps to reproduce:**
Import gltf file with animation.

**Minimal reproduction project:**
Import attached file (after unpacking), try playing any animation. It is broken in editor as well as in-game.

![](https://i.imgur.com/pRpAPcX.jpg)
It's Blender 2.8**0**, it's wrong in the picture.

[anim_test2.zip](https://github.com/godotengine/godot/files/2984489/anim_test2.zip)

**Comment by goodyttoor** [comment]
I saw the same behavior on Godot and other viewers when import the gltf. Perhaps, there is a problem with the export process? 

Can you also attach original blend file? Thank you very much.

**Comment by mnn** [comment]
Here's the file: [anim_test.blend.zip](https://github.com/godotengine/godot/files/2984846/anim_test.blend.zip)

There was a bunch of options for animations, but I didn't change anything when exporting. I read Godot implementation of gltf were being developed against (or in tandem with) Blender, so I thought it should work out-of-box.

I tried few online viewers and the deformations were even worse. :neutral_face:

I am total noob when it comes to rigging and animations in Blender (I literally put together this test file while watching a tutorial), so it is possible I am missing something. I assumed if it looked correctly in Blender then I must have done it right, but that might a false assumption.

**Comment by mnn** [comment]
It seems to be an issue with Blender - https://twitter.com/donrmccurdy/status/1108057821218664448. It is still a bit weird that several gltf online viewers were rendering broken mesh in exactly same way while Godot was rendering different (less?) broken mesh.

**Comment by marstaik** [comment]
Although I cannot fix the broken mesh/blender problem (it's already been fixed!), the incorrect behavior has been fixed by #32213

Here's a side-by-side with the Windows 10 3D viewer.

![broken_mesh](https://user-images.githubusercontent.com/5601015/65482485-1d2fd480-de4e-11e9-9564-d78968255c9e.gif)
