### ISSUE TITLE
Close Find / Replace window in Text Editor with ESC

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27241]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
There is no key to close the window to Find (Ctrl+F) or Replace (Ctrl+R).
ESC is a standard key for this.

**Comment by Zylann** [comment]
Which window? In the script editor, find & replace both close fine with Esc when I try it on Windows, both in Godot 3.0.6 and 3.1.

**Comment by rogeriodec** [comment]
Sorry, that was a conflict in one Autohotkey script here, just solved. 
Thanks.
