### ISSUE TITLE
Project Manager closing issues

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#27251]
**Godot version:**
Godot 3.1 (Steam)

**OS/device including version:**
macOS Mojave 10.14

**Issue description:**
Project Manager won't close via several methods. Only way it works is clicking Exit button at bottom twice.
1) cmd + Q won't work. Same as going to Godot > Quit Godot in menu bar.
2) Clicking the red x button to close the window.
3) Clicking Exit button at bottom won't work the first time.

**Steps to reproduce:**
Launch Godot, once in Project Manager try to quit the app.

**Comment by Calinou** [comment]
I can confirm not being able to quit the project manager using <kbd>Ctrl + Q</kbd> / <kbd>Cmd + Q</kbd> on commit https://github.com/godotengine/godot/commit/a53645e726097e9020d12df886b62431cb1740b9. It was probably never implemented and nobody noticed, I guess :slightly_smiling_face:

However, I can still quit the project manager by clicking **Exit** once (on Linux).

**Comment by bruvzg** [comment]
All of mentioned closing methods works fine for me on macOS 10.14.3 (3.1 stable from http://godotengine.org, current master custom build), maybe #8653 focusing issues pops-up again? Can you reproduce it with non Steam version or it's Steam specific?

**Comment by lexum0** [comment]
Non Steam version works as expected, the issue is Steam specific.

**Comment by lexum0** [comment]
I realized in the issue https://github.com/godotengine/godot/issues/26501 that the Steam version gets launched with some arguments, if I launch the Steam version from Terminal without any arguments the issue is gone. I bet it has to do with those arguments (`--path or -p`)

**Comment by lexum0** [comment]
Found the problem, I set the path to my project in Steam Launch Options so it launches directly to the project. Since it doesn't work, it opens the Project Manager with the weird behavior. Godot is being launched with the extra arguments `--path $HOME -p path/to/project`. Removing the project's path in  Steam Launch Options makes exiting work again.
