### ISSUE TITLE
Copy transform when create convex sibling

### ISSUE THREAD

**Issue by GammaGames** [godotengine/godot#27256]
**Godot version:**
3.1-stable

**OS/device including version:**
Windows 10

**Issue description:**
Creating a collision sibling from a mesh uses the default transform. It would be handy (and probably what is wanted 90% of the time) if it copied the mesh's transform upon creation.

**Steps to reproduce:**
Here is what it looks like by default:
![image](https://user-images.githubusercontent.com/7832163/54662270-1db47080-4aa3-11e9-9b1b-ad5f50d04a3c.png)
This is what it would look like if it copied the mesh upon creation:
![image](https://user-images.githubusercontent.com/7832163/54662322-3f155c80-4aa3-11e9-9477-a1895fb598d6.png)

Note: I'm not sure if there is any issues with scaling collision shapes in 3D like there is in 2D, if there is it would probably be best to leave those as 1 1 1.

**Comment by Zylann** [comment]
As a workaround you could duplicate the collision shape and then either make the shape unique or add a new one.
