### ISSUE TITLE
Slider knob in inspector floats around

### ISSUE THREAD

**Issue by akiraKido** [godotengine/godot#27258]
**Godot version:**

3.1 stable

**OS/device including version:**

Windows 10 x64

**Issue description:**

I'm quite sure slider knobs are supposed to stay where they were.

![0005](https://user-images.githubusercontent.com/19627014/54670743-ada3fa00-4b37-11e9-8214-f6bb03acbfe1.gif)

**Steps to reproduce:**

1. Open the inspector with a slider property.
2. Hover over the slider to make the knob visible.
3. Scroll using the mouse wheel without moving the cursor.

Moving the cursor will just delete the knob.

BTW, hovering the mouse right over the knob and scrolling is fine (or is it? It just wouldn't scroll. Not a problem though).

**Comment by avencherus** [comment]
Confirmed.  Bumped into tonight, in build 4ad255a.

Can take it for a ride.  XD

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/56372894-8f015380-6208-11e9-8c1d-6ef417d02059.gif)

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987.
