### ISSUE TITLE
Memory leak when changing  QuadMesh size

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#27263]
**Godot version:**
v3.1-stable

**OS/device including version:**
ArchLinux rolling + NVidia 740MX

**Issue description:**
Changing size of QuadMesh causes memory leak after certain amount of iterations (after around 1k ticks on my machine.)
PlaneMesh also seems to be affected by this.

**Steps to reproduce:**
```gdscript
func _process(delta):
    $MeshInstance.mesh.size = Vector2(1, 1)
```

**Minimal reproduction project:**
[gdfoo.zip](https://github.com/godotengine/godot/files/2988390/gdfoo.zip)

**Comment by bruvzg** [comment]
macOS 10.14, can't detect any leak after 30000 `_process` iteration.

**Comment by qarmin** [comment]
Valgrind doesn't show any leak with Quad and Plane on Ubuntu 19.04 GTX 970 430.14
Maybe that was a driver issue?

**Comment by KoBeWi** [comment]
Windows 10 GTX 1060
No leak here either.

@and3rson Could you try it again, with newest 3.2 beta?

**Comment by KoBeWi** [comment]
Can't reproduce, no response from author. Closing.
