### ISSUE TITLE
Memory leak when changing window size in Linux

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#27265]
**Godot version:**
3.1 stable

**OS/device including version:**
Ubuntu 18.04.2

**Issue description:**
When I changing size of window with project which contains only Node2D, then I see that Godot memory increase. 
https://streamable.com/p7xh6

**Comment by slapin** [comment]
Please run valgrind with --leak-check=full and try to reproduce, then provide valgrind log.

**Comment by qarmin** [comment]
[Dokument bez nazwy.txt](https://github.com/godotengine/godot/files/2991509/Dokument.bez.nazwy.txt)

**Comment by slapin** [comment]
valgrind --leak-check=full godot >> /home/rafal/F.txt

otherwise your report is not very usable

**Comment by qarmin** [comment]
[F.txt](https://github.com/godotengine/godot/files/2995714/F.txt)

**Comment by slapin** [comment]
==27020== 32 bytes in 1 blocks are possibly lost in loss record 1,496 of 5,328
==27020==    at 0x580CB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27020==    by 0x32DDA77: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
==27020==    by 0x15D2F81: CowData<wchar_t>::resize(int) (cowdata.h:274)
==27020==    by 0x1B2440B: String::resize(int) (ustring.h:148)
==27020==    by 0x321658C: String::copy_from(char const*) (ustring.cpp:145)
==27020==    by 0x321AB1B: String::String(char const*) (ustring.cpp:1605)
==27020==    by 0x322D070: Variant::Variant(char const*) (variant.cpp:2198)
==27020==    by 0x3245800: register_variant_methods() (variant_call.cpp:1495)
==27020==    by 0x31D1BF1: register_core_types() (register_core_types.cpp:105)
==27020==    by 0x1195926: Main::setup(char const*, int, char**, bool) (main.cpp:339)
==27020==    by 0x1167145: main (godot_x11.cpp:48)
==27020==
==27020== 32 bytes in 1 blocks are possibly lost in loss record 1,497 of 5,328
==27020==    at 0x580ED2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27020==    by 0x32DDCC7: Memory::realloc_static(void*, unsigned long, bool) (memory.cpp:140)
==27020==    by 0x11D3828: CowData<StringName>::resize(int) (cowdata.h:282)
==27020==    by 0x11D2EB5: Vector<StringName>::resize(int) (vector.h:84)
==27020==    by 0x11D354D: Vector<StringName>::push_back(StringName const&) (vector.h:152)
==27020==    by 0x3274025: _VariantCall::addfunc(bool, Variant::Type, Variant::Type, bool, StringName const&, void (*)(Variant&, Variant&, Variant const**), Vector<Variant> const&, _VariantCall::Arg const&, _VariantCall::Arg const&, _VariantCall::Arg const&, _VariantCall::Arg const&, _VariantCall::Arg const&) (variant_call.cpp:172)
==27020==    by 0x3245886: register_variant_methods() (variant_call.cpp:1495)
==27020==    by 0x31D1BF1: register_core_types() (register_core_types.cpp:105)
==27020==    by 0x1195926: Main::setup(char const*, int, char**, bool) (main.cpp:339)
==27020==    by 0x1167145: main (godot_x11.cpp:48)
==27020==
==27020== 32 bytes in 1 blocks are possibly lost in loss record 1,498 of 5,328
==27020==    at 0x580ED2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27020==    by 0x32DDCC7: Memory::realloc_static(void*, unsigned long, bool) (memory.cpp:140)
==27020==    by 0x11D3828: CowData<StringName>::resize(int) (cowdata.h:282)
==27020==    by 0x11D2EB5: Vector<StringName>::resize(int) (vector.h:84)
==27020==    by 0x11D354D: Vector<StringName>::push_back(StringName const&) (vector.h:152)
==27020==    by 0x3274025: _VariantCall::addfunc(bool, Variant::Type, Variant::Type, bool, StringName const&, void (*)(Variant&, Variant&, Variant const**), Vector<Variant> const&, _VariantCall::Arg const&, _VariantCall::Arg const&, _VariantCall::Arg const&, _VariantCall::Arg const&, _VariantCall::Arg const&) (variant_call.cpp:172)
==27020==    by 0x3245A2B: register_variant_methods() (variant_call.cpp:1496)
==27020==    by 0x31D1BF1: register_core_types() (register_core_types.cpp:105)
==27020==    by 0x1195926: Main::setup(char const*, int, char**, bool) (main.cpp:339)
==27020==    by 0x1167145: main (godot_x11.cpp:48)

@akien-mga might you look in to this or I can do that early April? Sorry I'm too busy these days :(

**Comment by qarmin** [comment]
Also Valgrind show other definitely lost objects
```
432 bytes in 1 blocks are definitely lost in loss record 99 of 126
   at 0x581274F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x379A457: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x379A400: operator new(unsigned long, char const*) (memory.cpp:42)
   by 0x1E260AB: RasterizerSceneGLES3::environment_create() (rasterizer_scene_gles3.cpp:766)
   by 0x340D2CA: VisualServerRaster::environment_create() (visual_server_raster.h:496)
   by 0x344B615: VisualServerWrapMT::environment_create() (visual_server_wrap_mt.h:423)
   by 0x2FCC714: Environment::Environment() (environment.cpp:1303)
   by 0x289BC0B: Object* ClassDB::creator<Environment>() (class_db.h:146)
   by 0x35DCB17: ClassDB::instance(StringName const&) (class_db.cpp:540)
   by 0x30C27F4: ResourceInteractiveLoaderText::poll() (resource_format_text.cpp:561)
   by 0x3862F2D: ResourceFormatLoader::load(String const&, String const&, Error*) (resource_loader.cpp:197)
   by 0x3864834: ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) (resource_loader.cpp:272)

480 bytes in 1 blocks are definitely lost in loss record 100 of 126
   at 0x581274F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x999F15F: glXChooseFBConfig (in /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.430.14)
   by 0x6D23B20: glXChooseFBConfig (in /usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0)
   by 0x137E5D0: ContextGL_X11::initialize() (context_gl_x11.cpp:156)
   by 0x1380859: OS_X11::initialize(OS::VideoMode const&, int, int) (os_x11.cpp:298)
   by 0x13B3623: Main::setup2(unsigned long) (main.cpp:1098)
   by 0x13B1E4A: Main::setup(char const*, int, char**, bool) (main.cpp:1046)
   by 0x137D950: main (godot_x11.cpp:48)
```

**Comment by qarmin** [comment]
It probably can be closed, because I have only this leaks, which are probably Nvidia drivers bugs:
```
Direct leak of 6280 byte(s) in 3 object(s) allocated from:
    #0 0x7f3966d98ce6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dce6)
    #1 0x7f3957976995  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.435.21+0xe39995)

Direct leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x7f3966d98f1e in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10df1e)
    #1 0x7f395797628f  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.435.21+0xe3928f)

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7f3966d98ce6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dce6)
    #1 0x7f39667f7842 in pa_xmalloc0 (/lib/x86_64-linux-gnu/libpulse.so.0+0x3b842)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7f3966d98ae8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dae8)
    #1 0x7f39669498af in XGetWindowProperty (/lib/x86_64-linux-gnu/libX11.so.6+0x258af)
    #2 0x9f5f4ff in InputEventMIDI::get_class_ptr_static()::ptr (/usr/bin/godots+0x9f5f4ff)

Indirect leak of 72672 byte(s) in 224 object(s) allocated from:
    #0 0x7f3966d98ce6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dce6)
    #1 0x7f3957976995  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.435.21+0xe39995)

Indirect leak of 2478 byte(s) in 179 object(s) allocated from:
    #0 0x7f3966d98ae8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dae8)
    #1 0x7f3957976b5b  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.435.21+0xe39b5b)

Indirect leak of 752 byte(s) in 6 object(s) allocated from:
    #0 0x7f3966d98f1e in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10df1e)
    #1 0x7f395797628f  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.435.21+0xe3928f)
```
