### ISSUE TITLE
 Hope to achieve such tilemap

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#27267]
https://blogs.unity3d.com/2019/03/18/isometric-2d-environments-with-tilemap/?utm_source=youtube&utm_medium=social&utm_campaign=engine-global-generalpromo-2019-03-18&utm_content=video_learn-isometric

**Comment by OvermindDL1** [comment]
What issue were you having making an isometric tilemap?  Was the Godot Isometric Tilemap Example project not working and if so then how was it not working?

**Comment by cjmxp** [comment]
I mean tilemap in unity3d is more friendly ， It's not Godot that has bugs 。
![图片](https://blogs.unity3d.com/wp-content/uploads/2019/03/image4.gif)
![图片](https://user-images.githubusercontent.com/2855349/54728767-c0abde00-4bba-11e9-9c9f-71800d34ea4e.png)
![图片](https://blogs.unity3d.com/wp-content/uploads/2019/03/image5.gif)

![图片](https://blogs.unity3d.com/wp-content/uploads/2019/03/image15-1.gif)

![图片](https://blogs.unity3d.com/wp-content/uploads/2019/03/image6.gif)

![图片](https://blogs.unity3d.com/wp-content/uploads/2019/03/image7.gif)

**Comment by eon-s** [comment]
Can you be more detailed with a description of what the current tilemap editor lacks and what needs improvement?
Images alone do not explain much and nobody will be able to add the features you think TileMap needs.

**Comment by groud** [comment]
I'm closing this. Isometric tilemaps are already possible in Godot.
If you have **specific** concerns about the editor, please open an issue describing the problem, not just a link to the Unity documentation a few screenshots.
