### ISSUE TITLE
ResourceSaverPNG::save_image Editor Crash

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#27260]
**Godot version:**

dbf2f0c31e1742d361d9d591

**Issue description:**

Wasn't doing much, just had the editor running idle for a moment.  After saving a new a roughly empty and new scene, a few moments later the editor crashed with this message.

> OpenGL ES 3.0 Renderer: GeForce 9600 GT/PCIe/SSE2
> ERROR: ResourceSaverPNG::save_image: Method/Function Failed, returning: err
>    At: drivers\png\resource_saver_png.cpp:93
> ERROR: ResourceSaverPNG::save_image: Method/Function Failed, returning: err
>    At: drivers\png\resource_saver_png.cpp:93
> 

**Steps to reproduce:**
Create many nested scenes with scripts, and do various combinations of renames from the editor file panel.  Certain orders of doing this can trigger the crash.

**Update** - Seems to be related to certain situations when renaming scenes, scripts, or folders.  Can run into file locking issues.  Might be related to having text editors open with scripts outside the engine editor.

**Comment by avencherus** [comment]
@reduz Maybe it's time?  XD

	//change this
	Error err;
	FileAccess *f = FileAccess::open(p_path, FileAccess::WRITE, &err);
	if (err) {
		ERR_FAIL_V(err);
	}

**Comment by avencherus** [comment]
Some more updates.  Is not related to having a file opened with an external text editor.  I could get it happen by renaming scenes and scripts that are nested within one another.  Not sure on the exact magic combination, but sometimes it crashes immediately after the action, sometimes during the attempt to save it.  Work can certainly be lost.

I ran in --verbose mode and it seems not to crash, but throws different errors into the console.

> ERROR: Failed to get modified time for: C:/Users/.../Documents/Godot Test Project/ma.tscn
>    At: drivers\windows\file_access_windows.cpp:306
> ERROR: ResourceFormatLoaderText::load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
>    At: scene\resources\resource_format_text.cpp:1226
> ERROR: Failed loading resource: res://ma.tscn
>    At: core\io\resource_loader.cpp:285
> ERROR: ResourceFormatLoaderText::load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
>    At: scene\resources\resource_format_text.cpp:1226
> ERROR: Failed loading resource: res://ma.tscn
>    At: core\io\resource_loader.cpp:285
> ERROR: SceneState::pack: Method/Function Failed, returning: err
>    At: scene\resources\packed_scene.cpp:880
> ERROR: EditorData::check_and_update_scene: Condition ' err != OK ' is true. returned: false
>    At: editor\editor_data.cpp:640
> erasing C:/Users/.../Documents/Godot Test Project/x.tscn
> erasing C:\Users\...\AppData\Roaming/Godot/projects/Godot Test Project-5dcfe9e47e9ccd929e6a6335242455c2/filesystem_update4
> erasing C:/Users/.../Documents/Godot Test Project/b.tscn
> ERROR: Another resource is loaded from path: res://xyz.gd (possible cyclic resource inclusion)
>    At: core\resource.cpp:79

**Comment by KoBeWi** [comment]
This should've been fixed by #29459
@avencherus Can you confirm?

**Comment by avencherus** [comment]
Currently unable to reproduce, so it may be resolved.  Will re-open if I encounter it again beyond this commit.
