### ISSUE TITLE
Usage of null with static typing

### ISSUE THREAD

**Issue by akiraKido** [godotengine/godot#27261]
Currenlty, the following code will not work:

    func _ready():
        foo(null)

    func foo(bar: Vector2):
        print(bar)

This will result in a parser error:

`Parser rError: At 'foo()' call, argument 1. Assigned type (null) doesn't match the fuction argument'stype (Vector2)`

This is not completely bad; I understand having `null`s are not so good in the first place. The problem is that GDScript still has `null`, and when converting duck-typed code to staticly typed code, it's hard to replace parts of the code where there were cases where null existed.

From what I know so far, I would assume there would be 2 (nice) ways to approach this problem.

1. Add `?` at the end of the type for "nullable" values (like C# or Swift).

        func _ready():
            foo(null)

        func foo(bar: Vector2?):
            if bar != null:
                print(bar)
    By doing so, you would be able force null checks with values that could be null, resulting in safer code.

2. Try and ditch `null` with `Option(Val)`. (like Rust)

        func _ready():
            foo(null)

        func foo(bar: Option<Vector2>):
            match Option:
                Some(val):
                    print(val)
                None:
                    pass
    This will need an additional implementation of `enum` with values.

**Comment by CodeDarigan** [comment]
There was talk about #26228 having a Variant return type. Maybe at the very least we could have that if no option types?

**Comment by akiraKido** [comment]
Yeah, having an "any" equivalent should work as well.

My problem with using Variant would be that it doesn't enforce safety so much... If I'm duck typing, I would want the program "not" crash at all.

**Comment by YeldhamDev** [comment]
This is already being discussed at godotengine/godot-proposals#162.
