### ISSUE TITLE
Make selected keyframes more visually distinctive from unselected ones and easier to select.

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#27276]
**Godot version:**
3.1

Keyframes are hard to select because their "hitbox" is tiny and selected keys are visually hard to read and there is no audio feedback.

Proposal: 

- Increase the size of selected keyframes slightly (maybe +1 pixel in each direction is sufficient), 
- change the color of selected keyframes to something bright, or have a soft glow around them. 
- play a soft unintrusive short sound when selecting a keyframe, it can be hardly audible, but your body will immediately know when miss-clicked even if you where not looking.

**Comment by regakakobigman** [comment]
I don't think the editor has any sounds currently. I'd rather keep it silent, unless the rest of the interface was given optional sound cues.

I agree with the other two suggestions, though. The Poly Editor has an adjustable point grab radius in the settings. What if keyframes had an adjustable grab radius and visual size in the settings, under Editors\Animation?

**Comment by golddotasksquestions** [comment]
Sound could be entirely optional. There has to be some kind of feedback for the user when a operation is unsuccessful. Currently there is none, and not just in the AnimationPlayer. This is an issue throughout the engine. I often do something, it seems to have no effect, but I am not entirely sure, but have to proceide. And I cannot even check in the undo history log, because Godot has no history log to check. (https://github.com/godotengine/godot/issues/25919).
