### ISSUE TITLE
GraphEdit signal "node_unselected"

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#27272]
**Godot version:**
Master 3.2 and previous

**Issue description:**
`GraphEdit` node provides a signal for graphnode selection (node_selected), but no signal for the inverse operation, when a previously selected graphnode gets unselected. Managing this using `gui_input` is not so trivial, and does not actually work well since it requires 2 clicks out of the graphnode to be considered as unselected.

edit: maybe a wider scope would be to create a `changed` signal on `Object` class that gets thrown on any built-in parameter change?

**Comment by asheraryam** [comment]
On the latest 3.2 release this actually cannot be done at all with GDScript, so I just went ahead and added the new signal 😅
