### ISSUE TITLE
'View information' in GLES2 not working properly

### ISSUE THREAD

**Issue by finkizo** [godotengine/godot#27273]
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Ubuntu 18.10 (64-bit)
Radeon RX 560 Series (POLARIS11, DRM 3.26.0, 4.18.0-15-generic, LLVM 7.0.0)

**Issue description:**
Render information in 3D editor viewport in GLES2 displays zeros only.
![view_information](https://user-images.githubusercontent.com/47667808/54710088-900d6b00-4b0c-11e9-9d0a-62aff34e6f94.png)

**Comment by KidRigger** [comment]
I'll take this.
