### ISSUE TITLE
true copy and paste keyframes

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#27279]
**Issue description:**
Right now, in order to copy and paste keyframes the user has to select the keyframes (https://github.com/godotengine/godot/issues/27276), move the animation timeline cursor to the desired paste location(https://github.com/godotengine/godot/issues/27278), go back to the selected keyframe, right click and select "duplicate".

Never ever would I have figured this out by myself. I had to ask on Discord.

Duplicating keyframes from one track to another is currently also not possible. (see slightly different issue: https://github.com/godotengine/godot/issues/15029)

Proposed solution: Select keyframe(s), Ctrl+C or rightclick ->context menu ->"copy key", left click to position on desired track, Ctrl+V or rightclick ->context menu -> "paste key"

Pasting should be only possible at compatible tracks. If the clipboard data is not compatible with the paste location (for instance if the user tries to paste a key with integer value into a track with a boolean values), play a short, not so pleasant "denied" sound and display a small red cross symbol for a second at the location where the key was supposed to be pasted.

**Comment by avencherus** [comment]
A ctrl+D for duplication would also be a bump in the QoL direction.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/302, as feature proposals are now tracked in the Godot proposals repository.
