### ISSUE TITLE
fatal crash when editing tile collision box in polygon mode

### ISSUE THREAD

**Issue by alexm622** [godotengine/godot#27275]
**Godot version:**

most recent stable release

**OS/device including version:**

**Issue description:**
i was editing the collision on a tilesheet in polygon mode, hit ctrl + z to try to remove last point (the shape wasn't completed yet) and the program crashed.
the console gave the error:
"ERROR: operator[]: FATAL: Index p_index=-1 out of size (size()=0)
   At: ./core/pool_vector.h:505"

**Steps to reproduce:**
start creating a collision in polygon mode, place down a few points, and press ctrl + z

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Might be the same issue as #27360, and thus would be fixed by #27602.

**Comment by akien-mga** [comment]
Assuming that the above is correct. Please comment if you can still reproduce it when 3.1.1 is released.
