### ISSUE TITLE
Shift enter to move to next line 

### ISSUE THREAD

**Issue by kusaflow** [godotengine/godot#27286]
I am coming from a ide by intellij and they have a beautiful feature which is whenever you are in middle of a line and you press Shift+Enter you moved to next new line. However in godot editor we move to next line (not new) with the text on the right of the cursor ;
for example :
--->
Godot is a 2D and 3D(imagine my cursor here) game engine.
<----
    and when i press Shift+Enter
      This is what currently happens
---->
 Godot is a 2D and 3D
game engine .     
<-----

what i want
----->
 Godot is a 2D and 3D game engine .     

<----

**Comment by MaciejGorczycaGD** [comment]
Can you not just press end and then enter? It's exact same amount of keys being pressed?

**Comment by kusaflow** [comment]
yeah of course but just image while programming how many times you press end key and compare it with how many times you press Shift and Enter. i m not saying you are wrong ,you are right but these little things counts sometimes. 😃😃

**Comment by Calinou** [comment]
This is already possible with <kbd>Ctrl + Enter</kbd> (and <kbd>Shift + Ctrl + Enter</kbd> to add a line above the cursor), like in Visual Studio Code.
