### ISSUE TITLE
Whole computer crash on running 3D Platformer Demo

### ISSUE THREAD

**Issue by Nonoreve** [godotengine/godot#27287]
**Godot version:**

Godot_v3.1-stable_x11.64

**OS/device including version:**

Ubuntu 18.04 
Intel Core i5
GPU : Intel Corporation HD Graphics 620 (rev 02)
16GB RAM

**Issue description:**

When running 3D Platformer Demo, after a few minutes the whole system freezes and fans started to roar. I waited for a few minutes that something happens but I needed to manually force shutdown. 

**Steps to reproduce:**
Thinks its a random glitch, so, hard to reproduce. 
Can't tell anything about error message (except if there is a log file) because I couldn't do anything (including moving mouse). 
Edit : I tried to reproduce and got a few freezes but no crash. I had the system monitor beside and there was no sign of overloading nor on RAM or CPU usage. 

**Minimal reproduction project:**

**Comment by groud** [comment]
I am not sure you have the minimum requirements to run this demo. If I am not mistaking Intel HD are integrated graphics cards.

**Comment by Zireael07** [comment]
What is your version of Mesa drivers? I suppose your problem is simply overheating the laptop, Ubuntu doesn't always play ball with the fans.

@groud: Yes, this is an integrated card, but still, OpenGL 3 capable AND runs FIFA 18 at 25 fps on ultra, or GRID Autosport at 44 fps on medium. The Platformer 3D demo IIRC doesn't have any fancy effects (GI, mostly) that could be an issue.

**Comment by Nonoreve** [comment]
Informations from glxinfo :
renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.2
OpenGL core profile shading language version string: 4.50
version string: 3.0 Mesa 18.2.2
OpenGL shading language version string: 1.30
ES profile version string: OpenGL ES 3.2 Mesa 18.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by aaronfranke** [comment]
Unless you can reliably reproduce this, I don't think there's any point in keeping this issue open, since there's no way for us to debug this.

The demo works fine on my system, and it has also been updated since you opened this issue.
