### ISSUE TITLE
Provide dedicated skin and hair shaders for creating realistic human characters

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#27283]
**Godot version:**
`master` / ff318d91

**OS/device including version:**
Manjaro Linux 18.0.4

**Issue description:** _(This issue is a feature request)_
As we can expect more users would be interested in creating 3D games with a more realistic style, it'd be better if we can provide dedicated shaders to render human skin and hairs.

As I described in another issue(#26891), there are many obstacles that prevents one from creating a realistic human character in Godot and lack of such dedicated shaders is one of them.

Moreover, a human skin material within an environment with a GI probe would either look completely dry or soaked in oil, depending on how it's shadowed, thus making it practically impossible to achieve even a remotely realistic result as is described in #19561.

And if we can accept what is discussed in that issue, it's apparently an expected behaviour and we would need a dedicated skin shader to fix such a problem, so I think this would give this issue a bit more of importance than it would otherwise.

Currently, both Unity and Unreal provide their users such dedicated shaders to create a character with decent looking skin and hairs by default. In comparison, we give our users a generic spatial material with which they can spend much time to make a plastic looking skin that looks completely broken when it's shadowed, and they wouldn't find a clear remedy for the problem, unless they are well versed in writing custom shaders (that is, provided #19561 can be actually solved by writing a shader, without any engine modification).

Eventually, we may be able to provide our users something like [this](https://docs.unrealengine.com/en-us/Resources/Showcases/PhotorealisticCharacter), so they can produce photorealistic result.

But in the meanwhile, I think even a much more primitive shader that can at least mitigate such a problem like #19561 would help those who try to create games with a more realistic style with Godot for now.

**Comment by CptPotato** [comment]
I don't think customized shaders that work around this issue are the way to go. If the parameters work correctly things should work just fine if setup correctly.

About the environment light bleeding "through" objects: this is a problem for 3d engines in general. Other large engines have this problem aswell. There are some ways to work around this, like limiting limiting the environment specular intensity on dynamic objects or using specular maps to reduce it (could be a simple AO-map).

**Comment by mysticfall** [comment]
@CptPotato In that case, I think this issue can be considered more of an enhancement for those who want to create realistic characters on par with that can be achieved in other popular engines than a workaround for the problem that was mentioned in the description.

But in that case, I'd encourage you to share your insights in the discussion of #19561 to reopen the case. I seriously doubt if other engines would have a similar problem with such a severity, otherwise I simply can't imagine how anyone can create even remotely decent looking human characters with them.

I also can't see how a simple AO map could address such an issue, since it doesn't happen with any specific part of the body, like inside the nostrils or ears, but simply any skin part which is under a shadow will look extremely glossy and I certainly can't mark the whole skin as a 'dark area' in an AO map.

**Comment by CptPotato** [comment]
So I gave it a shot and I think you can get a somewhat decent look with what's currently available:

This is a medium quality 3D scan which I reduced, baked a normalmap and painted/generated albedo, roughness and AO maps.
![grafik](https://user-images.githubusercontent.com/3957610/54821608-fe843180-4ca2-11e9-997e-c2bbfe31ae67.png)

However, I noticed a few things:
- the subsurface-scattering is not very good in it's current state but it makes skin look at least a little bit better
- specular lighting seems to be broken: direct light sources have way too little specular lighting, compared to the diffuse component

I'll probably create an issue regarding the specular problems.

**Comment by mysticfall** [comment]
@CptPotato Thanks for taking your time to test this issue. By the way, did you use a GI probe in your scene? From the screenshot, I suspect either you did not use one or at least one with a skybox. 

However, the symptom which I described in #19561 can only be reproducible if you have a GI probe with a skybox. I mentioned this in one of the comments but probably it's a bit easy to miss.

Could you check if you can reproduce the issue when you have a GI probe? Thanks!

**Comment by CptPotato** [comment]
@mysticfall it looks pretty okay to me with an environment map:
![grafik](https://user-images.githubusercontent.com/3957610/54823176-4c029d80-4ca7-11e9-960c-790c383d900b.png)

I'm using a fairly rough material, though. If I decrease the roughness it almost looks like the specular is ramping up too much, but I can't tell for sure.

The problem you have is that the reflection you're seeing comes from the environment, not the directional light you're using. I'd recommend you to use a rougher material and an environment map with less extreme highlights.

**Comment by mysticfall** [comment]
> The problem you have is that the reflection you're seeing comes from the environment, not the directional light you're using - the shadow won't affect it at all.
Yes, this is exactly what I commented above and what others have been discussing in the other issue. The problem with shadow is that, the extreme glosiness may not look prominent if there is no shadow because the overall surface looks bright anyway. If you look my screenshots in the other issue, you may notice it doesn't look glossy at all when there is no shadow.

But the same material under the same environment goes under a shadow, the direct light is blocked so the surface becomes darker which leaves only the reflected light from the environmental map from the GI probe.

I can see that the environmental map you used looks much darker than mine and it's not under a shadow, so I can't really tell if that really proves my problem doesn't exist.

(For a reference, the HDRI map I used is this one: https://hdrihaven.com/hdri/?c=outdoor&h=kiara_5_noon)

And I don't think we should tell people not to choose an HDRI map that depicts a bright sunny day, because it's something they need to choose based on what they want artistically, not because they need to avoid such an issue.

**Comment by CptPotato** [comment]
> And I don't think we should tell people not to choose an HDRI map that depicts a bright sunny day, because I believe it's something they should be able to choose based on what they want artistically, not because they need to avoid such a problem.

True, but what I mean is that the maximum brightness **has to be limited**. The sky you referenced works great for renders but because it captures the full brightness of the sun it's not so great as a realtime environment map. Optimally, you'd limit the brighness to something much lower and add a directional light where the sun is supposed to be.

**Comment by mysticfall** [comment]
I already use a directional light as the Sun (otherwise, there'd be no shadow that blocks any direct light). 

Anyway, I confess that I don't have much experience with 3D art or gamedev in general, so maybe I'm asking about things that are common knowledge among game developers. But do you mean an HDRI map like this cannot be used without such a problem in video games, and I would run into the same sort of the problem if I used other popular engines?

And I thought the whole point of using HDRI map was to capture the full dynamic range of the environment. And from the amount of extreme glosiness I got with that HDRI map, I doubt I'd be able to completely avoid having such a problem if I use different textures which look slightly less brighter than that.

So, my question is, is using such an outdoor HDRI map is something not feasible in any game engine? Or if I should limit the maximum brightness as you suggested, how can I achieve this without abandoning using an HDRI map entirely?

**Comment by CptPotato** [comment]
The HDRI itself is fine. It's more about having a brightness limit option, for example in the import settings when enabling `HDR mode`.

**Comment by mysticfall** [comment]
Sorry, but I can't seem to find any relevant option in the import settings. Could you tell me where I can find the brightness limit option you mentioned?

![image](https://user-images.githubusercontent.com/2367032/54825775-afb1b880-4cf1-11e9-8f66-8ee93e12c804.png)

**Comment by CptPotato** [comment]
This was more of a feature suggestion, there's no such thing right now 😅.

**Comment by mysticfall** [comment]
Ok, I just installed Unity and created a minimal scene to see if I can reproduce it in a different engine, as suggested from others.

Please consider that my knowledge of Unity is very limited, and I certainly don't want to spend too much time creating sample project in that engine, so it looks quite horrible as it is. But I hope it's sufficient to show the difference between the two engines.

First off, this is how my character looks in Unity, with the standard shader with 0.5 roughness. And the scene contains a single directional light and the same HDRI texture I linked above as a skybox, and I used 'Progressive CPU' lightmapper to generate the GI data:

![unity](https://user-images.githubusercontent.com/2367032/54831184-3ddf6c00-4cfd-11e9-96ee-394932b02aab.png)

The shadowed area shows highlighted reflection, but I think it still falls within a reasonable range.

However, the same model looks like this in Godot, with the same HDRI map and a single directional light again. I had to use the 'sqrt' trick I mentioned in #26891 on roughness value, since it'd make the whole body literally glow with specular light if I don't do that.

![godot](https://user-images.githubusercontent.com/2367032/54831520-d2e26500-4cfd-11e9-8f74-92cdebd015f8.png)

As you can see, the lighted area doesn't look too glossy but when it's shadowed, it looks like it's soaked in oil.

I'm not exluding the possibility that I may have done something wrong while creating that scene. However, it looks pretty clear to me something is not right with how GI affects shadowed areas in my scene, and so far I have been unable to figure out how to fix that problem without effectively disabling the GI and none of the suggestions from other users seem to help.

And if it's indeed a problem on my part, I wish someone could point out what exactly am I doing wrong in Godot, and what we could do to prevent people from doing a similar mistake, since it's apparently not so easily reproduced in Unity, even when the user doesn't know much about the engine and didn't do anything special to prevent such an issue.

**Comment by CptPotato** [comment]
Again, the reflection you see is the extremely (and I really mean *extremely*) bright sun in the HDRI. Find a way to filter that out or probably look for a different environment map which works better without editing it.

I'll stop discussing this now, not trying to be rude but I think github is wrong place to discuss this and there's other things I'll have to do now, good luck.

**Comment by mysticfall** [comment]
@CptPotato // The point is, the very same HDRI image with the extremely bright sun just worked fine in Unity for me, even when I didn't do anything special to prevent such an issue.

I appreciate your efforts in trying to help, but I simply don't understand how it could be a problem with the HDRI texture itself, or something happening in every realtime engine when the same setup only causes a problem in Godot alone.

**Comment by Megalomaniak** [comment]
I think unity might be tone mapping(or doing something similar) your HDRI, as @CptPotato alluded to, that is controlling it's brightness in unity.

**Comment by mysticfall** [comment]
@Megalomaniak I could even reproduce the same symptron using a plain non-HDRI png sky image I found on internet, after getting another suggestion that my HDRI could be the culprit from a different person.

And I can confirm that tweaking SSS does not affect the problem. Actually, it's not even possible to overuse SSS in Godot as I described in my tracker issue. For now, increasing SSS only results in a blurry image and nothing more (no change in diffuse color, or transmittance), so the effect you mentioned could be from transmission effect which I'm using to compensate for the rather weak SSS features. But again, I can confirm that it doesn't have any effect on the problem at hand.

As to the tone mapping, I've already tried various different tonemappers before I settled down with ACES. I don't know if Unity has a special tonemapper that would prevent such a problem. And I have no idea what import settings I could tweak to avoid having such an issue, as HDRI texture doesn't offer too many relevant options in its import settings as you can see from the above screenshot.

At any rate, I'd appreciate if you could suggest some specific tonemapper or import setting to tweak, in case you suspect it could be what is causing such an issue in Godot.

**Comment by Megalomaniak** [comment]
I see, no wonder then, transmission like this does not work well for SSS indeed, makes things look like old hollow plastic toys that tend to "glow" like this.  

Could you perhaps provide a basic/cut down project file that showcases the issue/s? If your assets are licensed in a manner that allows you to do so, of course.

**Comment by mysticfall** [comment]
@Megalomaniak The whole project is available from this repository: https://github.com/mysticfall/AlleyCat

It could be a bit large to download though. In order to see the problem, you can run the main scene and try to walk around and see how various parts of the skin (e.g. neck or upper arm area) looks under a shadow.

**Comment by Calinou** [comment]
I think those assets would be a better fit for the [Asset Library](https://godotengine.org/asset-library), rather than a core feature. We generally try not to add features that are specific to a game genre or art style, especially if they're complex.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
