### ISSUE TITLE
Linux android build error: can't find libz.so.1

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#2728]
I am tryn to build for android and i came to a few problems but managed to fix them. Now though i get an that a libz shared file is missing form godot.

Buildfile: /home/carlos/Documents/godot-source/platform/android/java/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.4.1
 [checkenv] Installed at /opt/android-sdk-linux

-setup:
     [echo] Project Name: Godot
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.2
     [echo] Resolving Build Target for Godot...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
     [echo] ----------
     [echo] Resolving Dependencies for Godot...
[dependency] Library dependencies:
[dependency] 
[dependency] ------------------
[dependency] Ordered libraries:
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...

nodeps:

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.4.1
 [checkenv] Installed at /opt/android-sdk-linux

-setup:
     [echo] Project Name: play_licensing
  [gettype] Project Type: Android Library

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.2
     [echo] Resolving Build Target for play_licensing...
[gettarget] Project Target:   Android 4.0.3
[gettarget] API level:        15
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /home/carlos/Documents/godot-source/platform/android/libs/play_licensing/res
    [mkdir] Created dir: /home/carlos/Documents/godot-source/platform/android/libs/play_licensing/libs
    [mkdir] Created dir: /home/carlos/Documents/godot-source/platform/android/libs/play_licensing/bin
    [mkdir] Created dir: /home/carlos/Documents/godot-source/platform/android/libs/play_licensing/bin/res
    [mkdir] Created dir: /home/carlos/Documents/godot-source/platform/android/libs/play_licensing/bin/rsObj
    [mkdir] Created dir: /home/carlos/Documents/godot-source/platform/android/libs/play_licensing/bin/rsLibs
    [mkdir] Created dir: /home/carlos/Documents/godot-source/platform/android/libs/play_licensing/gen
    [mkdir] Created dir: /home/carlos/Documents/godot-source/platform/android/libs/play_licensing/bin/classes
    [mkdir] Created dir: /home/carlos/Documents/godot-source/platform/android/libs/play_licensing/bin/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for play_licensing...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------
[dependency] API<=15: Adding annotations.jar to the classpath.

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [aapt] /opt/android-sdk-linux/build-tools/23.0.2/aapt: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

BUILD FAILED
/opt/android-sdk-linux/tools/ant/build.xml:597: The following error occurred while executing this line:
/opt/android-sdk-linux/tools/ant/build.xml:649: The following error occurred while executing this line:
/opt/android-sdk-linux/tools/ant/build.xml:694: null returned: 127

**Comment by akien-mga** [comment]
I don't have much experience with building for android so I might be missing something, but why aren't you using the scons buildsystem to build for android?

**Comment by carlosmarti** [comment]
I did use the scons build system to create the .so file that ends up in the bin. I am on the last step of building for android and that requires ant to make the apk file i need.

**Comment by akien-mga** [comment]
Thanks for the clarification. Did you initialize the build with ```builtin_zlib=no```?

**Comment by carlosmarti** [comment]
No i did not, i only did this (**ant debug**) so i should try it like this (**ant debug builtin_zlib=no**)

**Comment by akien-mga** [comment]
I don't know if ant knows this option, it comes from the scons buildsystem. But by default it uses builtin_zlib=yes, which is why I'd expect it not too complain about missing libz.so.1.

**Comment by carlosmarti** [comment]
I did change something in the java folder. It is the name of a .zip folder called libs. I changed the name to lib because in the steps from the android compile documentation it says to copy the .so file into java/libs/armeabi and because the .zip folder was named libs it was not letting me create the libs folder so i changed it to lib. I don't know if that has anything to do with it or not.

**Comment by carlosmarti** [comment]
Found the problem this was my stupidity. I needed to install a package i didn't have just in case someone else is having this problem installing the package lib32z1 on ubuntu will solve this issue.
