### ISSUE TITLE
No "Emulate Touchscreen" option

### ISSUE THREAD

**Issue by ciaoSora** [godotengine/godot#27289]
**Godot version: Godot_v3.1-stable_win64** 

**OS/device including version: Windows 10** 

**Issue description:**

I was doing the same as https://docs.godotengine.org/en/3.1/getting_started/step_by_step/exporting.html. There is no *Emulate Touchscreen* option under “Display” -> “Window” -> Handheld. Only *Orientation* is available.

**Comment by volzhs** [comment]
![Screenshot_20190322_002715](https://user-images.githubusercontent.com/8281454/54763421-48d0c880-4c39-11e9-9ceb-36e801a5bbea.png)

here is while document update.

**Comment by ciaoSora** [comment]
Thanks :)

**Comment by volzhs** [comment]
opened issue at https://github.com/godotengine/godot-docs/issues/2275
