### ISSUE TITLE
Compile failed on windows

### ISSUE THREAD

**Issue by mororo250** [godotengine/godot#27291]
**Godot version**:
3.1 master branch at 9c3ddf0

**OS/device including version:**
Windows 10 64bit, MSVC 2017

**Issue description:**
Compile error as shown on command line log below

**Steps to reproduce:**
cd cd c:/godot
run Visual Studio 2017 Developer Command Prompt v15.9.9 as admin
scons platform=windows

**Minimal reproduction project:**

'C:\MinGW\bin\mingwstartup.bat' is not recognized as an internal or external command,
operable program or batch file.
g++: error: /TP: No such file or directory
g++: error: /Z7: No such file or directory
g++: error: /Od: No such file or directory
g++: error: /EHsc: No such file or directory
g++: error: /MT: No such file or directory
g++: error: /Gd: No such file or directory
g++: error: /GR: No such file or directory
g++: error: /nologo: No such file or directory
g++: error: /W3: No such file or directory
g++: error: /wd4267: No such file or directory
g++: error: /wd4244: No such file or directory
g++: error: /wd4305: No such file or directory
g++: error: /wd4018: No such file or directory
g++: error: /wd4800: No such file or directory
g++: error: /EHsc: No such file or directory
scons: *** [platform\windows\godot_windows.windows.tools.32.o] Error 1
scons: building terminated because of errors.

**Comment by mororo250** [comment]
#

**Comment by Calinou** [comment]
Try opening a standard command prompt instead of a Visual Studio command prompt — SCons should be able to detect the MSVC installation automatically (and fall back to MinGW if none are found).

**Comment by mororo250** [comment]
After install SCons 3.0.1
I got:
scons: Reading SConscript files ...
TypeError: write() argument must be str, not bytes:

**Comment by shartte** [comment]
I am actually using the x64 VS2017 command prompt successfully.
@mororo250 Can you try just typing in `cl` on the VS2017 command prompt?

That looks like this for me:
```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27025.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

**Comment by mororo250** [comment]
the same for me:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

**Comment by mororo250** [comment]
@shartte, @Calinou thank you for taking the trouble to help me. 
I had added C:\MinGW\bin\mingwstartup.bat as an autorun sometime ago. I solved the problem removing it.
