### ISSUE TITLE
State machine tutorial

### ISSUE THREAD

**Issue by MaciejGorczycaGD** [godotengine/godot#27298]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 but any

**Issue description:**
I would like to request doc tutorial on implementation of finite state machine in Godot games. I struggle to find any written guides on this subject and only found videos. I think finite state machines are such a common feature in games that the way to implement them should be described in the docs. 

**Steps to reproduce:**
N/A

**Minimal reproduction project:**
N/A

**Comment by groud** [comment]
Please open an issue in this repository instead : https://github.com/godotengine/godot-docs
:)
