### ISSUE TITLE
Billboard sprites can't be scaled.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#27295]
Not sure if this is by design, but sprites set to billboard on their material can't be properly scaled and need to be scaled in a external software like GIMP if you want to change their size.

**Comment by henkz1** [comment]
did you try setting "billboard keep scale" to true ?

**Comment by volzhs** [comment]
godot version?

**Comment by ca3games** [comment]
> did you try setting "billboard keep scale" to true ?

Not sure how to do it, but I converted the default material to a shader so I can edit it with a shader.



> godot version?

3.1

**Comment by Chaosus** [comment]
>  I converted the default material to a shader so I can edit it with a shader.

Do not convert the material to shader, if you intended to use it as billboard, unless you want to write billboarding manually in vertex shader.

> Not sure how to do it

Almost same place in material settings where you set up billboarding

![image](https://user-images.githubusercontent.com/3036176/55397135-2fd7e980-554e-11e9-97be-3f82f57e5475.png)

^^ This will fix it. Closed.
