### ISSUE TITLE
Enable panning with middle mouse button while dragging a node.

### ISSUE THREAD

**Issue by Deosperada** [godotengine/godot#27300]
**Godot version:**
3.1 Stable

In larger 2D scenes, having to drag a node large distances gets quite annoying as you must:

1. Drag the node to the edge of the screen
2. Pan to make room for more dragging
3. Repeat until you have dragged the node to the desired location

And I don't see much reason as to why this shouldn't be a thing.

**Comment by volzhs** [comment]
I think it's a similar issue with #25616

**Comment by groud** [comment]
> I think it's a similar issue with #25616

They are related, but not duplicate. It is likely a good idea to be able to scroll while dragging, it might solve the initial problem.
