### ISSUE TITLE
Shadows2D dont appear on mobile  [GLES2]

### ISSUE THREAD

**Issue by Themaker482** [godotengine/godot#27303]
**Godot version:**

3.1

**OS/device including version:**

mobile android 

**Issue description:**

I was testing the export to android with the Lights_shadows demo, when i debug this via adb, the lights work properly but the light occuler doesnt generate any shadow

**Steps to reproduce:**
my mobile is an lg-x210g, if anyone an test it with another smartphone, maybe this could discard if my mobile is the problem.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Are you using GLES2 or GLES3? Can you provide more information on your Android version and your device specifications?

**Comment by Broedy-BRX** [comment]
I can confirm, I'm having the same issue Using GLES2, with the Google Nexus 7 and Samsung SM-G900T

Google Nexus 7 (OpenGL 3.0.0, Android 4.4.2, CPU armeabi-v7a, chipset msm8960)

Samsung SM-G900T (OpenGL 3.0.0, Android 6.0.1, CPU armeabi-v7a, chipset msm8974)

I'm also having some rendering issues with the Google pixel 2 XL (OpenGL 3.0.2, Android 8.1.0, CPU arm64-v8a, chipset msm8998)

The pixel renders the shadows but they are pushed off center and seem to have 'chunks' missing from the shadows.

Setting godot to use GLES3 fixes the Pixels problems but the other two devices won't run the game at all in that mode.

**Comment by akien-mga** [comment]
Can either of you still reproduce this issue in 3.2.3 RC 1 or later?

**Comment by akien-mga** [comment]
No answer and no reproduction project to test, so closing.
