### ISSUE TITLE
I would like to translate Japanese Godot docs

### ISSUE THREAD

**Issue by JunShiozawa** [godotengine/godot#27305]
I would like to translate Japanese Godot docs.

https://github.com/godotengine/godot-docs/pull/2274

**Comment by rogeriodec** [comment]
You can create this issue directly on the Godot DOC area: https://github.com/godotengine/godot-docs/issues

**Comment by JunShiozawa** [comment]
Oh! I made a misstake.Thanks rogeriodec.
