### ISSUE TITLE
OS.execute not working

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#27318]
**Godot version:** 3.1 Official

**OS/device including version:** Windows 10 64-bit

**Issue description:**

```
func _ready():
	var output = []
	OS.execute('cd', [], true, output)
	print(output)
```

Console Output:
```
'"cd' is not recognized as an internal or external command,
operable program or batch file.
[]
```

**Comment by Calinou** [comment]
This is probably because `cd` is a built-in shell construct instead of an executable. Try executing `cmd /c "cd somedir && dir"` instead.

**Comment by DleanJeans** [comment]
Oh yeah, it's in [the docs](https://docs.godotengine.org/en/3.0/classes/class_os.html#class-os-execute) and I totally missed it.

Calling `cd`:
```
OS.execute('cmd', ['/c cd'], true, output)
```

Running python script:
```
OS.execute('cmd', ['/c %s %s' % [PYTHON_PATH, SCRIPT_FILE]], true, output)
```

**Comment by DleanJeans** [comment]
I got a script like this:

```Python
# read_results.py
with open(r'results.txt', encoding='utf-8') as txt_file:
	file_content = txt_file.read()
	print(file_content)
```
which can be called from both CMD and PowerShell with:
```
cmd /c python read_results.py
```
Yet this is what I get when I run it in Godot:
```GDScript
OS.execute('cmd /c python read_results.py', [], true, output)
```
Console Output:
```
Traceback (most recent call last):
  File "G:/Python/Confetti/python/read_results.py", line 3, in <module>
    print(file_content)
  File "C:\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 364-365: character maps to <undefined>
```
which happens in CMD or Powershell only if there's no `encoding='utf-8'` in the Python script:
```Python
# read_results.py
with open(r'results.txt') as txt_file:
	file_content = txt_file.read()
	print(file_content)
```

What's wrong here?

**Comment by DleanJeans** [comment]
Okay, so I think it has nothing to do with `OS.execute` but it's that Godot console cannot handle Python printing Unicode at all.

Workaround:
- Print in Python with `string.encode('utf-8')`
- You'd get something like this: `b'Ti\xe1\xba\xbfng Vi\xe1\xbb\x87t'`
- In Godot, somehow read and convert it to a `PoolByteArray` then call `get_string_from_utf8()` on it to get the original string
