### ISSUE TITLE
Registro de inputs y clicks de raton desfasados, en el editor de proyectos de godot 3.1 estable.

### ISSUE THREAD

**Issue by Bucham** [godotengine/godot#27311]
Hola, estoy usando godot 3.1 estable en una surface pro 6 con procesador i5. Nada mas abrir el editor de proyectos esta se queda en negro hasta que hago click en algun sitio ( esto no ocurria con la ultima release candidate de 3.1, al igual que el problema mas gordo que detallo a continuación), pero el problema mas raro, es que una vez ya en el editor de proyectos, cualquiera de los botones que pulso no funcionan hasta que de nuevo pulso en algun punto vacio de la pantalla, es mas, en la pantalla emergente de nuevo proyecto, si escribo una letra, esta no aparece hasta que pulso la siguiente y asi sucesivamente. Parece que los clicks de raton o inputs de teclado se registran pero no hacen su funcion o aparecen en la pantalla hasta que se pulsa el siguiente click o tecla. Evidentemente es una locura intentar abrir un proyecto nuevo ya que incluso al marcar checks o abrir nuevas ventanas emergentes el problema se repite. Esto parece que no ocurre una vez dentro del proyecto, aunque una vez ahi, el boton de cierre (la x) parece que sufre del mismo problema, y debo cerrarla casi siempre desde la barra de tareas. (Nada de esto ocurria como digo en la ultima release candidate). Muchas gracias y un saludo.

**Comment by volzhs** [comment]
would you write in English?

**Comment by groud** [comment]
This is an English only place, sorry. Please translate your issue before posting it here.
