### ISSUE TITLE
Godot README.md screenshot update

### ISSUE THREAD

**Issue by Toshiwoz** [godotengine/godot#27324]
Crazy idea, why not update the readme screenshot with something like this?
![image](https://user-images.githubusercontent.com/21297356/54829110-af7ad400-4c83-11e9-8e07-3b3aba4c498c.png)
Showing the new UI and the good looking FPS demo.

**Comment by Toshiwoz** [comment]
I mean, not necessarily this, but something LIKE this.

**Comment by Toshiwoz** [comment]
![image](https://user-images.githubusercontent.com/21297356/54830382-67a97c00-4c86-11e9-8e35-dd2d2ee51a7a.png)
Maybe this one is better.
I noticed that the original screenshot is located here: 
https://download.tuxfamily.org/godotengine/media/screenshots/editor_3d_fracteed.jpg
As it's not a public repo, how to upload that there?
Or it doesn't matter and we link it to the Github uploaded images?

**Comment by Toshiwoz** [comment]
I've created this pull request if the image location is not a problem:
#27325

**Comment by Toshiwoz** [comment]
![Godot-TPS-demo](https://user-images.githubusercontent.com/21297356/54835113-7fd1c900-4c8f-11e9-9037-e65d58a17c5f.png)
This one have the title bar cut off.

**Comment by Calinou** [comment]
Please use the default editor theme settings (with the blue accent color). Also, for better visuals, I would suggest taking the screenshot at a very high resolution (like 3840×2160) with the editor scale set to 200%, then downscale the image to half its original size. This way, specular aliasing will be less apparent :slightly_smiling_face:

**Comment by Toshiwoz** [comment]
I missed this comment before.

> I like the idea of showcasing the TPS demo, but please use the default editor theme settings (with the blue accent color). Also, for better visuals, I would suggest taking the screenshot at a very high resolution (like 3840×2160) with the editor scale set to 200%, then downscale the image to half its original size. This way, specular aliasing will be less apparent 🙂

I'm going to use your screenshot as my old laptop won't support higher resolutions.


> If it's to be included in the README, remember to convert it to JPEG to make it smaller.

Done

Will cause any problem to add a subfolder under `/misc`? This way it won't be located in a separate place, neither tuxfamily nor rely solely on github. I think this way we can even use relative paths...

**Comment by Calinou** [comment]
> Will cause any problem to add a subfolder under /misc? This way it won't be located in a separate place, neither tuxfamily nor rely solely on github. I think this way we can even use relative paths...

What about submitting it to [godotengine/godot-design](http://github.com/godotengine/godot-design)? This way, we don't bloat the main repository with "press" files.

**Comment by Toshiwoz** [comment]
> What about submitting it to [godotengine/godot-design](https://github.com/godotengine/godot-design)? This way, we don't bloat the main repository with large files too much.

Sure, which subfolder? And, are you going to do that or shall I clone and pull request there too?

**Comment by Calinou** [comment]
@Toshiwoz I'll submit a pull request so you can link to it :smiley:

**Comment by Toshiwoz** [comment]
> 
> 
> @Toshiwoz I'll submit a pull request very soon so you can link to it 😃

Or you do it, I don't care. 😃

**Comment by Calinou** [comment]
@Toshiwoz Done, https://github.com/godotengine/godot-design/pull/36; you can use the JPEG version once it's merged.

**Comment by SouzaGuilherme** [comment]
Hi everyone, have you done the pull request?

**Comment by Calinou** [comment]
@SouzaGuilherme The pull request in godot-design hasn't been merged yet.

**Comment by akien-mga** [comment]
Superseded by e40aea7f, but thanks for the proposal!

**Comment by Toshiwoz** [comment]
Good, I just wanted to see an up-to date and good looking image of Godot editor.
@akien-mga I just don't understand why it went to the 3.2 milestone, as it has not to do with compiled code, of course is nothing important, just curiosity.

**Comment by akien-mga** [comment]
It's merged in the master branch which will become 3.2. If you check the 3.1 branch, it still has the older screenshot. So it does have to do with Godot versions :)

**Comment by Toshiwoz** [comment]
You're right, it has to do with versions, but the image is from 3.1 version.
Sorry, I may be missing something.. :dizzy_face:
