### ISSUE TITLE
Incorrect specular lighting

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#27322]
**Godot version:** 3.1 stable

Specular reflections of **direct** lights seem to be incorrect. At medium to low roughness values, the specular blob is pretty much invisible. Even on a completely black mesh.

I suspect that it's due to faulty energy conservation or some of the parameters are off. (currently there is `material > specular` and `light > specular` which both default to 0.5)

Here's a comparison with blender (left) and godot (right):

`albedo 1.0`, `roughness 1.0`:
![grafik](https://user-images.githubusercontent.com/3957610/54827445-50808380-4cb2-11e9-9ec1-fa484f34a63c.png)

`albedo 0.5`, `roughness 1.0`:
![grafik](https://user-images.githubusercontent.com/3957610/54827453-56766480-4cb2-11e9-98f5-9e0a4af750dc.png)

`albedo 0.0 (-> specular only!)`, `roughness 0.5`:
![grafik](https://user-images.githubusercontent.com/3957610/54827505-74dc6000-4cb2-11e9-8d31-bb4c8d72e006.png)

As you can see the specular highlight is already too dark to be visible, even though the light source isn't all that dark.

**Steps to reproduce:**
Observe how specular blobs react to changes in the roughness value.

**Comment by CptPotato** [comment]
Looks like this is a regression somewhere between 3.0 and 3.1.

If I compare the two versions, 3.1 has a **much** fainter specular highlight than 3.0.

Here's what I noticed during some tests (this is only comparing **specular** lighting):
version | light > specular | material > metallic > specular | result (direct light) | result (environment light)
--- | --- | --- | --- | ---
**3.0** | `0.5` (default) | `0.5` (default) | **correct** | **correct**
**3.1** | `0.5` (default) | `0.5` (default) | way too dark | **correct**
**3.1** | `1.0` | `1.0` | **correct** | too bright

**Comment by akien-mga** [comment]
> Looks like this is a regression somewhere between 3.0 and 3.1.

Could you try some 3.1 alpha/beta/RC builds to narrow down when the regression happened? See https://downloads.tuxfamily.org/godotengine/3.1/

**Comment by akien-mga** [comment]
Is this better after #27898?

**Comment by CptPotato** [comment]
I'll give it a test later today.

**Comment by CptPotato** [comment]
Sorry for the delay. As far as I can tell it seems better. If I set the material property `Metallic > Specular` to 1 it looks very similar to the blender PBR reference.
