### ISSUE TITLE
expand/collapse code chunks in script editor

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#2732]
It might be useful to be able to expand/collapse code branches by editor.

**Comment by jackmakesthings** [comment]
+1, code folding would be awesome.

**Comment by bojidar-bg** [comment]
:+1:

**Comment by reduz** [comment]
i can't think of a way to program this that is not a mess, so contributions
welcome :D

**Comment by blurymind** [comment]
:+1:

**Comment by Cobradabest** [comment]
YES! I want this as well!

**Comment by kirilledelman** [comment]
Bump! My scripts are long and unwieldy. Code folding would be a huge boon.

**Comment by reduz** [comment]
code folding is a lot of work... but How about a function navigator for
now? (list of functions) in a sub-panel?

**Comment by nunodonato** [comment]
@reduz yes please!!! :D

**Comment by GrandFunkR** [comment]
In my opinion, list of functions in a sub - panel it is still a useful thing

**Comment by Calinou** [comment]
Yes, we can have a pane at the right of the code editor containing a list of functions and methods.

**Comment by bojidar-bg** [comment]
But please, make it hideable/configurable...

**Comment by Calinou** [comment]
> But please, make it hideable/configurable...

Indeed, it could have three states:
- Disabled
- Shown at left
- Shown at right (default, probably)

**Comment by kirilledelman** [comment]
May I make a suggestion:
![suggestion](https://cloud.githubusercontent.com/assets/6539713/13296532/981a6b72-daf3-11e5-90dc-c2ec9f9ba39a.jpg)

**Comment by akien-mga** [comment]
@kirilledelman Great proposal IMO.

**Comment by nunodonato** [comment]
Folks, please think twice before choosing how to implement this.
Most of the time you use this feature to jump to a function. You dont really need to have the info of all available functions on the screen all the time. For people like people who need to save on screen space, its really painful to have yet another side panel!

I would suggest implementing it the way others IDEs do: an horizontal combo box, that just lists the functions when you click on it, and jumps to it when you select one. Maximum utility, easy to use, and minium space occupied!

If you really want a panel, then I'd go for @kirilledelman suggestion as at least it uses horizontal space that is already occupied.

**Comment by eska014** [comment]
Most of these suggestions seem to have little benefit over `Ctrl`+`Shift`+`F` (or `Search`→`Goto Function`), but @nunodonato's IDE-like suggestion sounds okay

Wasting screen space to show a list of every script function all the time is not a good idea, and I need the space on left side list for script and help files

**Comment by blurymind** [comment]
Collapse and uncollapse code would make most sense, but it seems the
hardest to implement
On 24 Feb 2016 19:46, "eska014" <notifications@github.com> wrote:
>
> Most of these suggestions seem to have little benefit over Ctrl+Shift+F
(or Search→Goto Function), but @nunodonato's IDE-like suggestion sounds okay
>
> Wasting screen space to show a list of every script function all the time
is not a good idea, and I need the space on left side list for script and
help files

**Comment by puppetmaster-** [comment]
What do you think about this:
![image](https://cloud.githubusercontent.com/assets/10463138/13335607/34a010fe-dc12-11e5-9fd7-25d192ca0839.png)

- group for scripts and help files
- x for closing file
- collapse and uncollapse to show script function (override and new)

**Comment by blurymind** [comment]
that is pretty cool, but I will miss the icons the show what is a script and what is a help file.

**Comment by puppetmaster-** [comment]
You don't need it because is a group no more mix.

**Comment by GrandFunkR** [comment]
I think the idea of puppetmaster it is great

**Comment by therealrobster** [comment]
I'd like this but simplified.  Simply a little arrow that you can open or close (or a +  or -).
