### ISSUE TITLE
Error al mostrar Sprite en baja resolución. Sprite no se muestra correctamente.

### ISSUE THREAD

**Issue by DeybisMelendez** [godotengine/godot#27338]
**Godot version:**
Godot 3.1 estable

**OS/device including version:**
Laptop Windows 10 64 bits con R2 Graphics Radeon en modo GLES 2

**Issue description:**
Tengo un proyecto en github con un juego y el edificio no se muestra correctamente, a pesar que en el editor se ve bien. 

La resolución es 160x120. La imagen png tenía un ancho de 103 pixeles y lo reduje a 102 pixeles, eso redujo el error pero aun en resoluciones pequeñas (640x480 o menos) se ve el error.

**Steps to reproduce:**
Descarga el proyecto: [Mi proyecto](https://github.com/DeybisMelendez/megaman-2-intro-godot)
Ejecutalo, no aumentar el tamaño de la ventana.

Mi observación es que el nodo Sprite pone la imagen con medio pixel a la izquierda y medio pixel a la derecha fuera del "límite"

![Screenshot (50)](https://user-images.githubusercontent.com/40205683/54858075-449fbc00-4cc8-11e9-99ed-d449f0a0890c.png)
![Screenshot (51)](https://user-images.githubusercontent.com/40205683/54858076-45385280-4cc8-11e9-95d6-641030d98a88.png)
![Screenshot (52)](https://user-images.githubusercontent.com/40205683/54858077-45385280-4cc8-11e9-8f97-29b17c594c80.png)
![Screenshot (55)](https://user-images.githubusercontent.com/40205683/54858078-45385280-4cc8-11e9-8245-fe76dbf43f1a.png)

**Comment by eon-s** [comment]
La comunidad de Godot es internacional y muy pocos entienden español, se prefiere el inglés al reportar problemas para que todos puedan comprenderlo y te puedan asistir más rápidamente, si necesitas ayuda para ello puedes consultar en grupos y canales en español en facebook o discord.

----------------------------------------

The op says that the sprite building sprite do not show correctly at low resolutions.
To reproduce, run the project and keep the window size.

My guess is that is a subpixel problem, I will see if I can reproduce it.

**Comment by DeybisMelendez** [comment]
> 
> 
> La comunidad de Godot es internacional y muy pocos entienden español, se prefiere el inglés al reportar problemas para que todos puedan comprenderlo y te puedan asistir más rápidamente, si necesitas ayuda para ello puedes consultar en grupos y canales en español en facebook o discord.
> 
> The op says that the sprite building sprite do not show correctly at low resolutions.
> To reproduce, run the project and keep the window size.
> 
> My guess is that is a subpixel problem, I will see if I can reproduce it.

En español o en inglés, reporte es reporte. Que no hablen español no es mi problema, asi como yo uso el traductor de google, ¿Por qué ellos no?. Por comentarios como el tuyo la comunidad latina rara vez publica issues. 

No es que tenga problemas con mi proyecto, Es un error en el render del GLES 2 y solo hace falta ver las imágenes para notarlo. Por otro lado el proyecto está en inglés (sus variables y eso). El proyecto en github solo es un ejemplo que estaba haciendo, imitando el intro de Megaman 2 de NES, no es un juego completo, solo la introducción. Solo lo comparto para que vean que tiene ese pequeño fallo.

Si no quieren ver el error porque el issue está en español ya no es mi problema.

**Comment by eon-s** [comment]
No puedo reproducir Ubuntu with R5 and amdgpu.
Intenta habilitando pixel snap en ajustes del proyecto.
----------------------------------------------------
Cannot reproduce the effect on Ubuntu with R5 and amdgpu.
Try enabling pixel_snap on project settings.

pd: respecto a la respuesta, te he dicho cómo proceder para que se pueda trabajar mejor, si eso te parece malo...

**Comment by DeybisMelendez** [comment]
> 
> 
> No puedo reproducir Ubuntu with R5 and amdgpu.
> Intenta habilitando pixel snap en ajustes del proyecto.
> 
> Cannot reproduce the effect on Ubuntu with R5 and amdgpu.
> Try enabling pixel_snap on project settings.
> 
> pd: respecto a la respuesta, te he dicho cómo proceder para que se pueda trabajar mejor, si eso te parece malo...

Lo testeaste con el modo GLES 2?

**Comment by DeybisMelendez** [comment]
> 
> 
> No puedo reproducir Ubuntu with R5 and amdgpu.
> Intenta habilitando pixel snap en ajustes del proyecto.
> 
> Cannot reproduce the effect on Ubuntu with R5 and amdgpu.
> Try enabling pixel_snap on project settings.
> 
> pd: respecto a la respuesta, te he dicho cómo proceder para que se pueda trabajar mejor, si eso te parece malo...

He testado activando Pixel Snap y se arregló, gracias.

**Comment by akien-mga** [comment]
Na ja, ist ganz schön, dass Sie nur spanisch reden wollen, aber es wird nicht die Zusammenarbeit der Gemeinschaft vereinfachen. En effet, on parle tous des langues différentes et chacun doit faire un effort pour que tous puissent se comprendre. En tout cas quand il s'agit de faire un rapport de bug. Du kan godt bruge en tool til oversættelse, og det er helt ok når det ikke er et perfekt sprog (ligesom mit dansk), men vi bruger et lingua franca til at kommunikere sammen, og det er engelsk på GitHub.

**Comment by Naryosha** [comment]
@eon-s Would you mind checking if this is a duplicate? Thank you.

You can't write English or Spanish, save it as `.gd`, and expect the engine to run it.

**Comment by groud** [comment]
Je crois qu'on va pouvoir fermer cette issue sans sommation. Si l'OP est incapable de faire l'effort ne serait-ce que de traduire son issue sur Google translate, je vois pas pourquoi nous, les contributeurs, ferions l'effort de résoudre son problème...

**Comment by groud** [comment]
Closing for the same reason  commented in #27336. If anyone cares enough about this problem to open an issue in English, he is welcome to do so. :)
