### ISSUE TITLE
ProgressBar percentage visibility in editor parameters

### ISSUE THREAD

**Issue by WindWallk** [godotengine/godot#2733]
Currently there is no option to change the visibility of the percentage from the editor. The only way to do that is via code. It would be nice to have that option in the inspector

**Comment by neikeq** [comment]
After a quick check, I can confirm this property is already accessible from the Inspector:
![captura de pantalla de 2015-11-23 14 23 55](https://cloud.githubusercontent.com/assets/7718100/11337512/de824be2-91ed-11e5-89af-c1a170150eb5.png)

**Comment by akien-mga** [comment]
Fixed for 2.0 then it seems.
