### ISSUE TITLE
Scaled Editor UI makes project window freeze until moved, UI looks like a mess (see screenshot)

### ISSUE THREAD

**Issue by eetson** [godotengine/godot#27337]
**Godot version:**
3.1.stable.official - editor

**OS/device including version:**
Windows 10 Intel UHD 620

**Issue description:**
When the Editor UI is scaled, the editor project window freezes on the splashscreen (see attached screenshot, UI scaled 150%) until the window is moved, or the cursor is moved inside/outside the window. Also the load screen doesn't fill the window, and the window isn't centered.

![godotbugUI](https://user-images.githubusercontent.com/43553709/54857535-41133180-4cd6-11e9-9e9f-151726898af5.jpg)

**Expected Behavior:**
That the editor project window shows the UI once it's done loading, that the splash screen is scaled to match the UI, and that the window is centered properly on the screen, regardless of UI scale.

**Steps to reproduce:**
- Scale editor UI upwards (150%)
- Restart Godot Editor
- Don't move the cursor or the window

**Minimal reproduction project:**
Not Applicable, see screenshot.

**Comment by girng** [comment]
Do you mean scaling the UI as in a rect_scale modification, or you mean resizing just the window itself?

**Comment by eetson** [comment]
I mean the editor, as in scaling using the UI scale in the editor parameters window

**Comment by Calinou** [comment]
The one-frame delay issue on Intel graphics is already documented in https://github.com/godotengine/godot/issues/23069. Try updating your graphics driver and see if the problem persists.

As for the project manager window looking strange with scaling above 100% until it's resized, I've been able to reproduce it on Intel graphics on Linux (but not NVIDIA on Linux).

**Comment by eetson** [comment]
The delay issue seems to persist even after updating (Dell 25.20.100.6373 ,A09). The redraw too, of course.

**Comment by Calinou** [comment]
@eetson Did you download the driver directly from Intel, or from Dell? OEMs are often behind in terms of driver versions compared to the hardware manufacturer.

**Comment by Calinou** [comment]
@eetson Can you still reproduce this bug on [3.2 beta2](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-2)?

**Comment by eetson** [comment]
@Calinou would love to but I migrated that machine to Linux

**Comment by akien-mga** [comment]
Closing then as it can't be reproduced anymore.
