### ISSUE TITLE
Array PackedScene

### ISSUE THREAD

**Issue by ikicapitan** [godotengine/godot#27336]
**Godot version:**
3.1

**OS/device including version:**
Windows 7 Ultimate, GeForce GTX 1050, i7-7700

**Issue description:**
Creé via GDScript un "export" Array, al cual le agregué una escena guardada (PackedScene) para instanciar luego, pero nisiquiera pude ejecutar el programa ya que se cerraba automáticamente... aun cuando nisiquiera intenté instanciar la escena, solo la agregué a la lista de array.
Como consecuencia extra el proyecto corrompió por completo la escena puesta como referencia en el Array, no pudiendo ser abierta nuevamente nunca más y teniendo que ser eliminada por completo para reestablecer el funcionamiento del proyecto.

**Steps to reproduce:**
- Crear un Nodo
- Añadir un GDScript
- Crear un export (Array)
- Desde el Inspector darle el valor 1
- Cargar una escena guardada
- Ejecutar el Proyecto
- Llorar y putear todo lo que se pueda al programa por la pérdida.

**Minimal reproduction project:**
Ni en pedo.

**Comment by kone9** [comment]
Traductor de GOOGLE
Godot version:
3.1

OS / device including version:
Windows 7 Ultimate, GeForce GTX 1050, i7-7700

Issue description:
I created via GDScript an "export" Array, to which I added a saved scene (PackedScene) to instantiate it, but I could not even run the program because it closed automatically ... even though I did not try to instantiate the scene, I just added it to the array list.
As an extra consequence, the project completely corrupted the scene set as a reference in the Array, and can not be opened again and has to be completely eliminated in order to re-establish the functioning of the project.

Steps to play:

Create a Node
Add a GDScript
Create an export (Array)
From the Inspector give him the value 1
Load a saved scene
Execute the Project
Cry and bitch everything you can to the program for the loss.

Minimal reproduction project:
Not in fart.

**Comment by reduz** [comment]
Podés hacer un proyecto simple que contenga una escena corrupta y subirlo
acá? Sinó te cierro el issue. Gracias.

**Comment by ikicapitan** [comment]
Copio lo mismo que te dije en Facebook:
"No es mi trabajo, solo hago diferentes apreciaciones verdaderas del programa en pos de ver si las mejoran, sino vos crees que mi canal tendría mas de 200 tutoriales de Godot?. Y eso del issue tracker, además de que no me pagan por ser beta tester, quiero recordarte que el "roadmap", los que donan tienen doble voto. Adicionalmente a ésto invierto tiempo no solo perdiendo la escena, sino que haciendo un issue tracker, y me decís que queres tambien el ejemplo adjunto... honestamente no espero concordar ni en pedo con vos men, pero de corazón te lo dice alguien que se mueve con muchísima gente que usa Godot:
Arregla los fixes para Godot 2D... dejense de joder con features y con el Godot 3D si queres hagan otro que se llame Gordot, no me importa, pero si hicieran funcional Godot 2D... solo funcional con lo que ya tiene, sería mejor que Unity y yo hoy mismo, hoy mismo lo estaría recomendando... creí que lo iban a lograr hace 2 años ésta estabilidad, pero por ahora no. 
Te felicito por tu programa, indudablemente es bueno, sino no estaríamos hablando de eso, pero definitivamente tenes que recalcular tu dirección porque le están pifiando hermano, se que lo haces por diversión y como vos te da la gana, pero es una picardía, porque por uno o dos detalles de tomar una dirección concreta no se vuelve el mejor Engine 2D actualmente, no pierdas tu tren porque es muy bueno.
Un abrazo."

Cerra el issue tranquilamente si queres, me da igual, es tu página, tu engine, tu problema... vos tendrás o no decencia para con tu público y lo que ofreces.

**Comment by groud** [comment]
I don't know what is happening those days, but it seems that we have some people that do not understand that this place is supposed to be in English.

If you don't even take the time to translate the text to English yourself (even with Google translate, it is not a problem), do you think I will take the time to fix the issue ? And if your are not interested in it being solved, why even bothering opening one ?

Have a look to the number of issues opened on the repository, and please understand we are kind of tired to have people opening low quality issues, whether they lack the basic issue template or not written in English. Also remember that most people here work for free, and don't owe you or anyone anything.

I will close this issue for now, if anyone else care enough about this problem to write his problem in English, he is welcome opening another issue.

**Comment by kone9** [comment]
> Podés hacer un proyecto simple que contenga una escena corrupta y subirlo acá? Sinó te cierro el issue. Gracias. Si no querés usar Inglés al menos tené la decencia de abrir un issue como corresponde

Desde el minuto ### 1:10:40 hasta###  1:15:00 aprox reproduce el problema."en español".
https://www.youtube.com/watch?v=jcV63398hxw

From the minute ### 1:10:40 to ### 1:15:00 the problem reproduces. "In Spanish".
https://www.youtube.com/watch?v=jcV63398hxw

![Captura](https://user-images.githubusercontent.com/12847027/54867145-bb39c980-4d5b-11e9-9bb3-9bf415ddbd04.JPG)
![Captura2](https://user-images.githubusercontent.com/12847027/54867149-c3920480-4d5b-11e9-9429-cca134c65d6b.JPG)
![Captura3](https://user-images.githubusercontent.com/12847027/54867150-c42a9b00-4d5b-11e9-9bc4-0e0c8e8b0c78.JPG)
![Captura4](https://user-images.githubusercontent.com/12847027/54867185-0eac1780-4d5c-11e9-89a6-3e95813a52d0.JPG)
![Captura5](https://user-images.githubusercontent.com/12847027/54867187-0eac1780-4d5c-11e9-896f-a17120b9dcfa.JPG)

**Comment by ashandme** [comment]
Yes, I do not understand it because I'm so stupid for using the translator.
