### ISSUE TITLE
Loading an Environment resource from a separate thread blocks the main thread

### ISSUE THREAD

**Issue by needleful** [godotengine/godot#27341]
**Godot version:**

Latest master commit: hash 9c3ddf05cb9c59817d885e9daca6e8f61c89dc97

**OS/device including version:**

Fujitsu Lifebook with Intel i5, tested on Windows 7 and the latest version of Lubuntu

**Issue description:**

I'm calling `ResourceInteractiveLoader::poll` from a separate thread, and it's blocking the main thread during one poll.  I made a project to debug the issue, and had no noticeable stutter until I added a `WorldEnvironment` to the loaded scene.  After more testing, it seems loading an Environment resource blocks the main thread, regardless of what thread calls `load()`.

There are ways to work around this for my use-case (i.e. having a global WorldEnvironment and using custom logic to update its parameters during scene transitions), but I'm wondering what the underlying cause of this is and if it can be fixed.

**Steps to reproduce:**

- Load a scene from a separate thread
- If it contains a WorldEnvironment, it will block the main thread (it may not be noticeable on high-end hardware)
- Deleting the WorldEnvironment will remove the stuttering caused by blocking the main thread.  There may be other nodes which cause this behavior, however.

Alternatively, just load an Environment resource from a separate thread, but then you won't have the comparison.

**Minimal reproduction project:**

[blocking_loader.zip](https://github.com/godotengine/godot/files/2998994/blocking_loader.zip)

This project loads one relatively large model (6MB) and then an environment.  The Environment causes a noticeable stutter in the animation, while the model does not (at least not until it's inserted into the scene tree).  You can also modify the `loading_test.gd` script to load a whole scene, which stutters unless you delete the scene's WorldEnvironment.

**Comment by KoBeWi** [comment]
The old ResourceInteractive loader wasn't really good. You could split loading into multiple steps, but each step could still block your game (at least for rendering-related resources like textures).

4.0 introduced a new threaded loading functionality, which should solve this problem. AFAIK it's impossible to fix this in 3.x due to different renderer.
