### ISSUE TITLE
Support for Returning Const Object Pointers in C++ Modules?

### ISSUE THREAD

**Issue by Andrettin** [godotengine/godot#27344]
To my knowledge, at present it is not possible to return const object pointers in methods bound in _bind_methods().

For example, let's say I have two classes which derive from Object, "Civilization" and "Player".

The "Player" class contains a const Civilization *civilization member variable, with the following getter:

```
	const Civilization *get_civilization() const
	{
		return this->civilization;
	}
```

This getter is then bound via _bind_methods():

```
	ClassDB::bind_method(D_METHOD("get_civilization"), &Player::get_civilization);
```

Unfortunately, this setup causes a compile error, as only methods returning non-const pointers can be bound that way. It would be nice if const pointers could be returned as well, becoming constants in the context of gdscript.

**Comment by akien-mga** [comment]
Did you try to wrap those in `Ref<Civilization>`? Check existing code of the engine itself, that's how Objects are being passed around.

**Comment by neikeq** [comment]
GDScript const does not work the same as C++ const. Even if it was made to, there are more languages that do not support this concept of head const.

**Comment by Andrettin** [comment]
@akien-mga The object pointer in itself works fine, it's only const pointers that don't. The equivalent for references would be Ref<const T>, but that doesn't seem to be used anywhere in the Godot source code (and I'm not sure the Ref class would even support that). It seems to me that the reason is that the Variant class only has a constructor that takes "Object *", but none that takes "const Object *". I could of course use a const_cast (it's what I'm doing at the moment), but that would weaken the advantages of using a const pointer for the member variable in the first place.

@neikeq My mistake, I hadn't realized that const in GDScript can only be used for constant expressions, and that it isn't possible to have a const object.

Since GDScript's const doesn't work in the same way as in C++, it's probably better for things to remain as they are, and to not have const Object pointers be convertible to Variants. Otherwise, the object would have to be made modifiable for it to work with GDScript properly (e.g. via a const_cast), which would run against the expectations of returning a const pointer. As such, I'm closing this issue. Thanks to both of you for your responses!
