### ISSUE TITLE
AnimationTree not available when compiled with disable_3d

### ISSUE THREAD

**Issue by scottkunkel** [godotengine/godot#27343]
**Godot version:**

dbf2f0c

**OS/device including version:**

Win10

**Issue description:**

Compiling with disable_3d removes animationtree

**Steps to reproduce:**
exported project results in error
Parse Error: Can't create sub resource of type: AnimationNodeAdd2

**Minimal reproduction project:**

**Comment by nikhilCad** [comment]
Can you provide the compiled executable download link?

**Comment by scottkunkel** [comment]
sure.
build line in win 10 x64 native tools was 
call scons platform=windows target=release_debug tools=no optimize=size use_lto=yes -j8 disable_3d=yes
output attached
example project in
https://github.com/godotengine/godot/issues/27306

[godot.windows.opt.debug.64.exe.zip](https://github.com/godotengine/godot/files/2999397/godot.windows.opt.debug.64.exe.zip)
