### ISSUE TITLE
Negative alpha isn't handled correctly in shaders

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#27347]
**Godot version:**

3.1

**OS/device including version:**

NVIDIA GeForce GTX 680

**Issue description:**

Doing simple shader stuff sometimes puts the alpha < 0. If it's not manually clamped, it's 100% white.

**Steps to reproduce:**
1. Make a Sprite, throw icon.png at it to be able to have UV coordinates.
2. Make a new shader:
```
shader_type canvas_item;

void fragment()
{
	float dist = distance(UV, vec2(0.5, 0.5));
	
	dist *= 2.0;
	float sharpenedDist = pow(dist, 20.0);
	float circle = 1.0 - sharpenedDist;
	COLOR = vec4(1.0, 1.0, 1.0, 1.0) * circle;
	COLOR.a = clamp(COLOR.a, 0.0, 1.0);
}
```

Compare with and without the last line where it's clamped.

Images:
![Godot_v3 1-stable_mono_win64_2019-03-23_13-44-17](https://user-images.githubusercontent.com/5933597/54866538-5b501c80-4d75-11e9-819d-f3cb3684c507.png)
![Godot_v3 1-stable_mono_win64_2019-03-23_13-44-36](https://user-images.githubusercontent.com/5933597/54866539-5f7c3a00-4d75-11e9-8338-f9e8b1fde6d2.png)

Maybe this helps too:
https://i.imgur.com/ihtjn31.mp4

**Minimal reproduction project:**

[Shader alpha bugs example.zip](https://github.com/godotengine/godot/files/2999362/Shader.alpha.bugs.example.zip)

**Comment by toasteater** [comment]
Looks like expected behavior: The alpha blending equation is `fg.rgb * fg.a + bg.rgb * (1 - fg.a)`, so if you have a negative `fg.a`, both sides of the `+` are going to be positive. With a 20.0 exponent, that negative alpha will grow pretty quick, hence clipping white.

**Comment by Boothand** [comment]
Huh, guess I was just unaware that alpha could be negative (and still valid). That's okay then.
