### ISSUE TITLE
Regression, in the inspector dock. All texture resources have no flag fields.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#27357]
**Godot version:**
Godot_v3.1-stable_win64.exe

**Issue description:**
I tried to set up the texture flags in the inspector, but there are simply no fields there.

**Comment by Zylann** [comment]
Note, for imported textures, these flags are supposed to be set in the `Import` dock instead, those are read-only in the inspector dock. Now I wonder if their hiding was on purpose?

**Comment by OlexiyKravchuk** [comment]
It makes no sense to hide them on purpose, and before that everything was accessible, why would it have become otherwise.
These flags are necessary for editing at any time, including during execution.

**Comment by Megalomaniak** [comment]
I think it might actually make sense to merge the import tab into the inspector for 4.0 so that when you click on a texture in the file system-browser tab it would show in the inspector with the import settings visible there. One less editor window type needed that way.

**Comment by Zylann** [comment]
@Megalomaniak yeah, I was really thinking about opening a feature request  to merge the import section as a category above the usual properties for imported resources. This would reduce confusion and clicking around while still allowing to see the resulting properties, which are useful also when debugging.

**Comment by OlexiyKravchuk** [comment]
In the overwhelming majority of cases, it makes no sense to create a separate dock personally for importing textures, because their settings are elementary. And all the same for each object you will have to configure them separately and probably after making corrections many times more. And at the moment, such a function does not have a normal implementation at all, neither for a mass setting, nor for an individual one, while in 2.1.5 everything was in order.

**Comment by bojidar-bg** [comment]
The `Flags` property was hidden in 3d34df0e79d58e638ac7c94db18c8b3f6ca7b382, completely on-purpose.
Note that you can still access it on non-StreamTexture textures, e.g. an AtlasTexture:
![image](https://user-images.githubusercontent.com/5276727/60283904-f297b380-9912-11e9-9091-49fabe11d741.png)

> And all the same for each object you will have to configure them separately and probably after making corrections many times more

In 4.0, texture flags would be removed in lieu of flags on Material-s and CanvasItem-s. [source](https://twitter.com/reduzio/status/1143308859429281794)

Closing as invalid (done on purpose, only affects StreamTexture), and obsolete in the future (4.0).
