### ISSUE TITLE
Windows Export should warn if custom resources are specified but rcedit isn't

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#27353]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10 x64

**Issue description:**
When specifying application values in the Desktop target, no indication is given inside the editor itself that these resource values can't be assigned to the exported executable without setting the location to rcedit in the editor settings.  Of course, there is documentation explaining this, but the editor itself doesn't stop you from inputting these values nor does it give any indication that these values won't be applied if rcedit isn't there.

**Comment by Calinou** [comment]
I found out there's already an issue about this (https://github.com/godotengine/godot/issues/18532), so I'll close this one as a duplicate. Thanks for reporting it :slightly_smiling_face:
