### ISSUE TITLE
3.1 build failure on FreeBSD

### ISSUE THREAD

**Issue by phryk** [godotengine/godot#27358]
**Godot version:**
3.1 from git branch, commit dbf2f0c31e1742d361d9d591def2ce6e955800b0

**OS/device including version:**
FreeBSD 11.2-RELEASE-p4

**Issue description:**
I can't get godot 3.1 to successfully build on FreeBSD.

I was able to avoid an issue with enet by using `module_enet_enabled=no`
and another issue with vpx (build output complained about some function,
whose name ended with `_avx2`, not having avx2 support by using `builtin_libvpx=no`.

But now I'm stumped on an issue with zstd that seems to hit me, no matter what I set builtin_zstd to: `no member named 'minMatch' in 'ZSTD_compressionParameters'`

Traceback with builtin_zstd=yes: https://paste.xinu.at/wCNK7w/
Traceback with builtin_zstd=no: https://paste.xinu.at/0M5L4/

**Steps to reproduce:**
`scons platform=x11 module_enet_enabled=no builtin_libvpx=no -j4`

**Comment by phryk** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236731
The FreeBSD port maintainer promptly made everything work in the port.
Patched port builds, installs and seems to work fine thus far.

I think for fixing this in godot itself the new files added in the submitted
patch are probably interesting, see https://bugs.freebsd.org/bugzilla/attachment.cgi?id=203065&action=diff

**Comment by robfram** [comment]
Godot version: f20c9c25ebddcef07daaa8788d8ff33679aa2aef
OS: FreeBSD 11.2-RELEASE-p4 amd64

I suppose this is related to the zstd part:
```
$ scons -j4 platform=x11 use_llvm=yes target=debug
```

Errors:
```
In file included from thirdparty/zstd/compress/zstd_compress.c:23:
thirdparty/zstd/compress/zstd_compress_internal.h:118:5: error: unknown type
      name 'ZSTD_literalCompressionMode_e'
    ZSTD_literalCompressionMode_e literalCompressionMode;
    ^
thirdparty/zstd/compress/zstd_compress_internal.h:200:5: error: unknown type
      name 'ZSTD_literalCompressionMode_e'
    ZSTD_literalCompressionMode_e literalCompressionMode;
[...]
```

Solution, as pointed in the post before, is changing the append by a prepend. I'll send a PR.
