### ISSUE TITLE
Instanced scene is only adding the root node to the tree and ignoring its children.

### ISSUE THREAD

**Issue by rnoriega31** [godotengine/godot#27366]
**Godot version:**

3.1.stable.official

**OS/device including version:**

OSX, probably irrelevant to the issue.

**Issue description:**

I have a scene which has the following structure:
```
PanelContainer
    VBoxContainer
        Label
        ...
```
And no matter what I did, trying to access that label was making the game crash. At first I thought I was doing something wrong but then I noticed on the remote tree, the `PanelContainer` node doesn't have the "expand" button like every other node with children, it seems like only the root is being added to the tree and the children are getting ignored.

**Steps to reproduce:**
Create a scene with the node structure described above. Attach a script to the `PanelContainer` node and set it's `class_name` to whatever, in the MRP I set it to "CommandList". In any other node do (in my case)
```
var cl = CommandList.new()
add_child(cl)
```
Now look at the remote tree, only the `PanelContainer` node is in there. And if you try to access either the `VBoxContainer` or any of it's label you'll get `null`, note that the MRP WILL crash on purpose, since it tries to access one of the `Label` nodes.

**Minimal reproduction project:**

[BugTest.zip](https://github.com/godotengine/godot/files/3000043/BugTest.zip)

**Comment by hasahmed** [comment]
Scenes are not regular objects you can insatiate with `.new()` method.
They have to be loaded in using their path, with either the `load` or `preload` functions, then instanced with the `.instance()` method. Your example would look something like this
```gdscript
var packed_cl = load('res://path_to_command_list.tscn')
add_child(packed_cl.instance())
```

**Comment by rnoriega31** [comment]
@hasahmed According to [this](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/scripting_continued.html#register-scripts-as-classes), it's now possible to instance classes you set it's `class_name` with the `.new()` method. The whole point of it is to avoid using strings to access classes.

However, I did replace instancing like that to instancing with `load("path")` and it indeed worked properly, so my guess is that the issue lies with the implementation of the new `class_name` system somehow.

I guess this works as a workaround, but it seems to me like the original issue is very much a bug.

**Comment by hasahmed** [comment]
It is not a bug. You are just missing the distinction between classes and scenes.

**Comment by rnoriega31** [comment]
Ah, I see now what you mean, gotcha. Thanks for clearing that up.
