### ISSUE TITLE
Standalone Help Documentation

### ISSUE THREAD

**Issue by CodeTortoise** [godotengine/godot#2736]
The in editor Godot documentation is a the most up-to date resource for GDScript, given one has the newest build. 

Since Godot binaries are essentially an autoloading Godot image without the developer tools, it might be possible to extract the help documentation window as a standalone application.

This would be an important feature, as the help documentation is necessary and invaluable for learning to program in Godot, and it is useful to have a separate window apart from the project one is editing.

**Comment by akien-mga** [comment]
I don't think it would be worth having to recompile a separate application each time the help gets updated. The plan is to export the documentation in Textile format (for the OpenProject wiki) directly from the source code, so that we can keep the source and the wiki synchronised.

So you'll be able to have the documentation in your web browser for example while coding in the editor.

**Comment by bojidar-bg** [comment]
@akien-mga What about offline docs? Maybe we should export HTML files too?

**Comment by akien-mga** [comment]
HTML doc generated from the source would be great indeed, and way simpler than a trimmed-down binary :)

**Comment by BBric** [comment]
I have written a small [program](broquere.brice.free.fr/Godoc.zip) in java which parse the xml file generated by the engine, but there is no descriptions.

**Comment by reduz** [comment]
Use doc/base_classes.xml

**Comment by BBric** [comment]
Cool, I was looking for that since a moment, thank you (sorry for the delay).

**Comment by BBric** [comment]
[update](http://broquere.brice.free.fr/gdoc/0.3.zip) with the descriptions.

![img](http://broquere.brice.free.fr/gdoc/0.3.png)

**Comment by akien-mga** [comment]
It's looking pretty cool! Could you put it in a GitHub repo or similar? If using git, you could then even use a submodule to retrieve the doc/base/classes.xml from Godot's repo I think.

**Comment by BBric** [comment]
I don't know how Git works, I have started to read some tutorials but I find that complicated. I will try on SourceForge when my account will be opened.

**Comment by Calinou** [comment]
> I will try on SourceForge when my account will be opened.

Please don't use SourceForge, ever.

**Comment by BBric** [comment]
It's done but it will stay empty for the moment.

**Comment by BBric** [comment]
[new update](http://broquere.brice.free.fr/gdoc/0.4.zip)

![img](http://broquere.brice.free.fr/gdoc/0.4.png)

**Comment by CodeTortoise** [comment]
BBric, this is beautiful! This is way better than what was in my brain.

The tabs are well thought out and logically delineated, it is super easy to navigate and find what you need.

I would say that it is missing a search feature, but it's barely a loss. Anything is so easy to find. 

Is this closed? If this were accessible with the releases, that would be great!

**Comment by BBric** [comment]
Thanks. I had removed the repository, i have created it again for redirecting to this issue, but i am not sure to fill it now...
Otherwise maybe that I would add the search later.

**Comment by BBric** [comment]
[0.43](http://broquere.brice.free.fr/gdoc/0.43.zip) (tab and historic bars)

![img](http://broquere.brice.free.fr/gdoc/0.43.png)

**Comment by akien-mga** [comment]
It looks great! :)
Partly related, I recently found out about the Zeal initiative: https://zealdocs.org/
It would be awesome if they had Godot doc support, but for this we need to work some more in having a portable documentation I guess.

**Comment by BBric** [comment]
Not sure, there is some guidelines on this [page](https://kapeli.com/docsets#dashDocset), the existing html documentation must be placed in a `*.docset/Contents/Resources/Documents/` directory (the structure is fixed), and then the harder would be to generate the SQLite index in the Resource directory.

**Comment by reduz** [comment]
this looks pretty, we should make the built-in help more like it :P

**Comment by BBric** [comment]
[0.44](http://broquere.brice.free.fr/gdoc/0.44.zip) (folding)

![img](http://broquere.brice.free.fr/gdoc/0.44.png)

**Comment by rolfpancake** [comment]
This is **awesome**! :+1: 
Maybe there should be a link to this repo in the docs/tutorials section.

**Comment by verbalshadow** [comment]
@BBric Does this support the new godot-doc repo here on github

**Comment by BBric** [comment]
Thanks. 
I have used doc/base/classes.xml in this repository (not the new).

**Comment by neikeq** [comment]
@verbalshadow AFAIK, it's only GDScript API reference.

**Comment by toger5** [comment]
this is fairly old. So I'm doing an update:
there is now a really sweet devdocs implementation.

http://devdocs.io/godot~2.1/

**Comment by akien-mga** [comment]
There's also the official http://docs.godotengine.org/, which can even be downloaded as PDF/EPUB.

Having the docs in Zeal/Dash would also be cool if someone wants to generate a docset, but it's not a priority for us at this time.
