### ISSUE TITLE
Prevent having a function and variable with the same name in a shader

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#27363]
Some GLSL shader compilers don't allow having variables and functions with the same name, so the Godot shader language should disallow that and throw an error if there's a conflict.

**Comment by creikey** [comment]
This issue is only present for variables that shadow function names in functions, as an example:
```glsl
shader_type canvas_item;

int sum2(int a, int b) {
	float sum2 = 3.0;
	sum2 = 4.0;
	return a + b;
}

void fragment() {
	COLOR = vec4(1.0*(sin(TIME*4.0)+0.5), 0.0, 0.0, 1.0);
}
```

**Comment by creikey** [comment]
This should be tagged as a bug, as the code to check if a variable is redefined in a function is already present, but not being called.
