### ISSUE TITLE
Downloadable Docs still in Godot 2.1

### ISSUE THREAD

**Issue by lainv0hndyrec** [godotengine/godot#27368]
**Godot version:**
3.1

**Issue description:**
the downloadable docs is still in 2.1 even if the online docs are in 3.1

**Steps to reproduce:**
this is the download tab of the docs
https://readthedocs.org/projects/godot/downloads/

**Comment by clayjohn** [comment]
Usually both versions would be available, but the docs havent been built for any of the 3+ versions due to the complexity and difficulty of building them. You can still build the pdf yourself. 

A user also provides a version here https://hugo.pro/projects/godot-builds/

**Comment by lainv0hndyrec** [comment]
Thanks, ill try to create a documentation in pdf and chm and ill do a little bit of in depth to them just like how GM: Studios API Documentation does

**Comment by lainv0hndyrec** [comment]
btw, what app do they use to create the documentation? is it just web html or css?

**Comment by clayjohn** [comment]
Take a look at the godot-docs readme https://github.com/godotengine/godot-docs it explains how to build the docs yourself!

**Comment by Naryosha** [comment]
Issues related to docs should also be created in godot-docs repository.

**Comment by Chaosus** [comment]
> Issues related to docs should also be created in godot-docs repository.

Yeah, closed.
