### ISSUE TITLE
Godot not supporting typographic ligatures for code fonts

### ISSUE THREAD

**Issue by NoodleSushi** [godotengine/godot#27373]
Godot 3.1 Stable
![Capture](https://user-images.githubusercontent.com/34954180/54879311-5cb33f00-4e72-11e9-96af-6bd4c288e566.PNG)
![Capture](https://user-images.githubusercontent.com/34954180/54879324-781e4a00-4e72-11e9-9b4b-fc723e501e08.PNG)
![Capture](https://user-images.githubusercontent.com/34954180/54879333-908e6480-4e72-11e9-8ec1-e60abdbaf759.PNG)
I've tried replacing the default code font to [FiraCode-Retina.ttf](https://github.com/tonsky/FiraCode) expecting ligatures to appear, but unfortunately it didn't.

**Comment by Calinou** [comment]
This is already covered by https://github.com/godotengine/godot/issues/9961, so I'll close this one as a duplicate. Please continue the discussion there :slightly_smiling_face:
