### ISSUE TITLE
Android Lights don't work (GLES3)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#27379]
![Screenshot_20190324-145313](https://user-images.githubusercontent.com/34406967/54881854-b442b200-4e54-11e9-824f-9e8f09a84468.png)

**Godot version:**

master, 3.1 stable

**OS/device including version:**

Samsung Galaxy S6 (Android LineageOS)

**Issue description:**

Lights don't work correctly.

**Steps to reproduce:**
Download the minimal reproduction project.

**Minimal reproduction project:**

https://github.com/HugeGameArtGD/Solus-Stunts/releases (stable7)

**Comment by Calinou** [comment]
Vertex lighting is forced by default on mobile (check the Project Settings), which will impact the appearance of lights (especially if they can't reach any vertices that can be lit).

**Comment by LinuxUserGD** [comment]
It works when I enable vertex shading in the project settings.
