### ISSUE TITLE
3.1 Sprites and Textured Nodes Don't Seem To Be Extending CanvasItem (non-existent function modulate)

### ISSUE THREAD

**Issue by TwitchtvCarbs** [godotengine/godot#27370]
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
For some reason modulate and self_modulate will not work with both textured buttons or sprites even though they extend CanvasItem?

This is only happening when you use .modulate(Color(x,x,x,x))
*Using .set_modulate(Color(x,x,x,x)) Seems to work just fine.*

**Steps to reproduce:**
Try to use .modulate or .self_modulate via code on a sprite.

**Comment by CptPotato** [comment]
modulate is a variable not a method, isn't it?

So `.modulate = Color(...)` should work just fine?

**Comment by TwitchtvCarbs** [comment]
Well, I'm an idiot. Yes, this works exactly as intended. Thanks @CptPotato
