### ISSUE TITLE
Godot ignores the windows height from project settings

### ISSUE THREAD

**Issue by JordanMotta** [godotengine/godot#27374]
**Godot version:** 3.1.stable.official

**OS/device including version:** Debian stretch, Linux Kernel 4.9.0-8-amd64 x86_64

**Issue description:** Godot "ignores" screen size from project settings. I have two monitors. One is 1366x768 which is the main screen (My laptop), and the other one is 1680x1050.

If i change the window's height in project settings to 1000. Godot just ignores it and set it to 744. At the beginning i though that there is some restriction to set a size bigger than the screen or Godot, by default, takes the size of the main screen, obviously the numbers doesn't match, but i had faith :). So, i close the project, set my main screen as the biggest one, and reopen the project. But the problem persists.

I created a new project, just in case. With one scene, a node2D root, i tried to set the height bigger than 744, but Godot ignores it. I have to mention that when i set the height to a small number (300), it works.

**Steps to reproduce:** New project in GLES2, new scene in 2D(Not tested in 3D), a root node, set window height in project settings to a big number(In my case, bigger than 744), run the scene.

**Comment by Calinou** [comment]
If you disable the main screen entirely in your OS' display settings, can you make the window height larger? If so, this could mean the widnow height is restricted by the window height of the primary monitor (which is wrong).

**Comment by JordanMotta** [comment]
I set the big monitor as my main screen, which is 1680x1050. But the problem persists. Godot just takes, as maximum value, 744. And it cannot be restricted by the monitor's height, because the height of my laptop is 768.

**Comment by Calinou** [comment]
> And it cannot be restricted by the monitor's height, because the height of my laptop is 768.

It's possible that the size restriction takes the window border into account.

**Comment by JordanMotta** [comment]
Oh! That's true. 

I did what you said. I've disabled my laptop screen and now the window's height grows until 975.

**Comment by Calinou** [comment]
It turns out there's already [an issue](https://github.com/godotengine/godot/issues/22736) reporting this bug, so I'll close this one as a duplicate. Thanks for confirming it :slightly_frowning_face:
