### ISSUE TITLE
TileMap; Offset + Custom Mode freezes Editor

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#27372]
**Godot version:**
Godot 3.1-stable

**OS/device including version:**
Manjaro Linux

**Issue description:**
When having an offset other than "Disabled" selected in the TileMap, and then chose the "Custom" mode, the editor freezes.

**Steps to reproduce:**
1. Create new Project
2. Add TileMap to your scene
3. Set the offset to Offset Y or Offset X
4. Set Mode to Custom
- should freeze now.

**Minimal reproduction project:**
none, as simple as adding a node to an empty project.

**Comment by SpechtMagnus** [comment]
Probably has to do with the cell line drawing. Same happens when selecting half offset and zooming out too far or making the cells too small

**Comment by Byteron** [comment]
Yes. I was testing again and actually godot doesn't freeze completely.
It just takes like a few minutes until it does something again, and the whole viewport is orange.
I guess it just was busy drawing *a lot* of lines. So it's not crashing nor freezing, but still an issue.

**Comment by SpechtMagnus** [comment]
Yeah, the referenced Pull Request should fix this issue and some similar ones. There was already a countermeasurement in place but whoever implemented it forgot some lines of code for it to work.
