### ISSUE TITLE
RemoteTransform2D exhibits erratic behavior compared to the cutout animation tutorial

### ISSUE THREAD

**Issue by clayheaton** [godotengine/godot#27381]
**Godot version:**
3.1 official

**OS/device including version:**
MacOS Mojave

**Issue description:**
The hierarchy of `RemoteTransform2d` nodes is ignored when transforming connected elements.

![Screen Shot 2019-03-24 at 12 46 54 PM](https://user-images.githubusercontent.com/205364/54882842-91a0a100-4e34-11e9-8651-de30cf576639.png)

**Steps to reproduce:**
Open the example project (see below) and try selecting the sprites in the hierarchy and moving them. They respect the hierarchy -- that is to say that children respect the change in transform of parents. 

Select one of the `RemoteTransform2d` nodes, which are in a different hierarchy than the sprites, [as recommended in the official Cutout animation tutorial](https://docs.godotengine.org/en/3.1/tutorials/animation/cutout_animation.html#remotetransform2d-node). The movement of the sprites is erratic when controlling via the `RemoteTransform2d` nodes. In particular, try what happens when you move the pink and green `RemoteTransform2d` nodes. Moving pink seems to respect the `RemoteTransform2d` hierarchy but moving green seems to respect the `Sprite` hierarchy.

Either the tutorial is misleading in suggesting that the transform of the sprites will respect the hierarchy of the `RemoteTransform2d` nodes or the expected behavior is broken. 

Additionally, it is ambiguous how establishing bones and an IK chain should work with some sprites that are positioned with `RemoteTransform2d` nodes. 

**Minimal reproduction project:**

[order_test.zip](https://github.com/godotengine/godot/files/3000594/order_test.zip)

**Comment by Calinou** [comment]
@clayheaton Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
