### ISSUE TITLE
Editor crashes when editing a resource script: "Object was deleted while awaiting a callback"

### ISSUE THREAD

**Issue by gonsor** [godotengine/godot#27380]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 Pro x86-64
AMD Ryzen 1800X
Nvidia Geforce GTX 1060

**Issue description:**
After creating a new resource, I created a new GDScript under "Reference->Script" in the inspector and saved. Reselecting this script from the inspector makes Godot crash with _"Object was deleted while awaiting a callback"_.
I tried deleting the contents of Roaming/Godot/projects/ already, did not solve the problem.

![grafik](https://user-images.githubusercontent.com/25853148/54882352-67ada580-4e59-11e9-9b32-89ce9616a55b.png)

**Steps to reproduce:**
1) Create a new resource by right-clicking in the filesystem on the _"res://"_ folder -> _"New Resource"_.
2) Go into the resource's _"Reference"_ tab within the inspector, create a new GDScript and save.
3) Reopen the project and click again on the script within the _"Reference"_ tab

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/3000564/bug.zip)

**Comment by qarmin** [comment]
Godot freeze because try to load recursive resource
![Zrzut ekranu z 2019-03-26 21-09-31](https://user-images.githubusercontent.com/41945903/55029920-8d7aac00-500b-11e9-941b-d2ad4da2bd05.png)

**Comment by and3rson** [comment]
I can also reproduce this.
