### ISSUE TITLE
Loading an mp3 into an AudioStreamPlayer crashes Godot

### ISSUE THREAD

**Issue by Kelzorz** [godotengine/godot#27385]
**Godot version:**
3.1 Stable

**OS/device including version:**
Windows 7 Home

**Issue description:**
Loading an mp3 file into an AudioStreamPlayer causes the program to crash, an error message is expected instead.

**Steps to reproduce:**
Create an AudioStreamPlayer on a Node.  On the AudioStreamPlayer Inspector->Stream select Load.  Select file type "All Files (*)" and select a .mp3 file.

**Comment by akien-mga** [comment]
Please open a new issue with a reproduction project.

**Comment by Calinou** [comment]
> Probably a Windows10 related issue with long file names?

Unless the absolute path was longer than 260 characters, it's not related. If it's actually longer than 260 characters, see https://github.com/godotengine/godot/issues/52799.

**Comment by RicardoReyes20** [comment]
Hello, I have a similar problem.  Format not supported for WAVE file (not PCM). Save WAVE files as uncompressed PCM or IEEE float instead.
 editor/editor_file_system.cpp:1764 - Error importing 'res://Treasure Hunters/Treasure Hunters/Music/mixkit-game-level-music.wav' I don't know how to solve it, any help would be very helpful.

**Comment by AThousandShips** [comment]
Please open a new issue, this has been closed for two years
