### ISSUE TITLE
Ray Casts need something opposite to exceptions.

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#2738]
For now RayCast Node and raycast API for Camera Node can only accept exceptions which they omit when they are doing collision check.
It would be greatly useful to have there something opposite for this behaviour as well.

For example you want ray cast to find specified object or group of object ignoring the rest of the world full of potential colliders.

For now only way I found to do it, is using get_tree().get_nodes_in_group() to find objects that I want to ignore. Or by creating global array of objects I want to ignore for ray cast, that will add themselves to this array when instance is created.

**Comment by eska014** [comment]
Collision layers and masks are planned to be ported from 2D to 3D for release 2.0. See #1759.
That should resolve the problem.

**Comment by akien-mga** [comment]
Right, I was about to reopen saying that raycasts don't support collision layers, but actually they do:
- In Physics2DDirectSpaceState: ```Dictionary intersect_ray( Vector2 from, Vector2 to, Array exclude=Array(), int layer_mask=2147483647, int type_mask=15 )```
- In the Raycast2D node: ```void set_layer_mask( int mask )``` and ```void set_type_mask( int mask )```
So as @eska014 says the only missing part is support for collision layers in 3D raycasts.
