### ISSUE TITLE
extend code selection using only mouse in code editor

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#2739]
I don't known if it is a feature required or a bug.
But using mouse it is possible to select only the visible portion of code.
It is useful extend selection and scrolling when mouse it is near the upper or lower border and the left mouse button it is pressed.

**Comment by eska014** [comment]
Scrolling while selecting works for me:
![select_scroll](https://cloud.githubusercontent.com/assets/6996191/10986516/166f7bd6-842b-11e5-849a-c014eccaeabf.gif)
Does this not work for you? Or am I misunderstanding?

**Comment by akien-mga** [comment]
It works for me on X11, but it indeed feels kind of awkward:
- You need to constantly move the mouse pointer around the bottom part of the screen to get a "smooth" scrolling, as shown in the GIF above. If you don't move, it just selects a small chunk of text, and you need to move to get it go further down.
- If you start selecting text and scroll with the mouse wheel, the text selection gets stuck.

**Comment by neikeq** [comment]
I made a PR some time ago with changes on how selection works in TextEdit. It includes the ability to select text while scrolling with mouse wheel: #2364

**Comment by GrandFunkR** [comment]
I'm using latest version compiled from github.
O.S.: linux manjaro

@akien-mga:
I do not remember if I tried to constantly move the mouse pointer around the bottom part of the screen.
Now I can try , try again later.

@neikeq:
thanks, I'll try to compile tool with your changes

**Comment by GrandFunkR** [comment]
does not works for me:

http://gfycat.com/DarkHideousDarklingbeetle

**Comment by akien-mga** [comment]
I checked and indeed it doesn't work to go upwards. But did you try to go downwards?

**Comment by GrandFunkR** [comment]
going downwards works! 
but movement it is not very fluid.

Also I have downloaded neikeq patch.
It does not solve upwards bug but is very helpful for me, thank you neikeq , I hope it will be merged soon
