### ISSUE TITLE
it's not possible to edit all items of an array

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#27396]
**Godot version:3.1

**OS/device including version:**

**Issue description:**

Since there is no scrollbar, only part of an array can be edited in the inspector.

**Steps to reproduce:**

<img width="284" alt="Screen Shot 2019-03-25 at 2 04 51 PM" src="https://user-images.githubusercontent.com/1130047/54898430-44413400-4f07-11e9-8208-a5eece254989.png">

**Minimal reproduction project:**

**Comment by qarmin** [comment]
Did you try to change page value?
Page number 1 shows array values from 0-9, page 2 shows from 10-19 etc.

**Comment by alexzheng** [comment]
oh, yes,I did not notice the page.
The page control works.

**Comment by Zylann** [comment]
This is intented. There is no scrollbar because arrays can be very large, which would slow down the editor and make it harder to find specific entries. So instead, it shows a subset of the array and you can directly jump to the page you want.
If you still want to see the whole array, increase page size to be the size of the array.

**Comment by Zylann** [comment]
@akien-mga was the bug fixed? Or is page size actually hardcoded to 10? I might have misunderstood

**Comment by akien-mga** [comment]
The OP seemed to have missed the Page option, which does make it possible to edit all items of an array. If you change Page to 1, then you can edit 10 to 19, etc.
![Screenshot_20190408_200041](https://user-images.githubusercontent.com/4701338/55746036-ffee8180-5a38-11e9-9ba4-916e9bfc5b22.png)
So I don't see any bug.

The page size of 10 seems hardcoded, but I don't see any request to change that in this issue.
