### ISSUE TITLE
get/set_indexed don't support Node paths in their NodePath parameter.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#27392]
**Godot version:**
Godot 3.1

**Issue description:**
When using `Object.get_indexed` and `Object.set_indexed` on a Node, the actual node names prior to any colon (`:`) are not actually fetching the specified Node, as detailed in the [NodePath documentation](https://docs.godotengine.org/en/latest/classes/class_nodepath.html#description). I've tried using full paths to child nodes `@"Child/Grandchild:test"` in addition to dot-references for self and parent. Nothing works.

**Steps to reproduce:**
Create a Node scene with the following script:

    extends Node
    var test = "hello"
    func _ready():
        print(test) # hello
        print(get_indexed(@".:test")) # Null
        print(get_indexed(@":test")) # hello

**Comment by bojidar-bg** [comment]
Does it work with something like `./:test`?

**Comment by bojidar-bg** [comment]
It is expected: `get_indexed` is a method of Object, not of Node.
There is `get_node_and_subresource` which is close to what you want.

**Comment by willnationsdev** [comment]
@bojidar-bg If this is intentional, then the NodePath API docs should be updated since they pretty clearly allude to the possibility of using NodePaths in this manner.
