### ISSUE TITLE
Some drop-down menus are hard to notice

### ISSUE THREAD

**Issue by Fredlyb** [godotengine/godot#27402]
**Godot version:**
3.1 stable

**Issue description:**
Some drop-down menus do not look like menus. The name of the node in the inspector, the "tilemap" at the top of the tilemap bar. Those ones.
![image](https://imgur.com/AGcME0e.png)

After a year using Godot, I just now learn that these can be clicked. This is not properly shown in the design, it is flat and looks like a title, causing much confusion for anyone who doesn't know otherwise.

Other interactive elements in the editor are coloured differently, hinting at their press-able qualities. Just do that for those too. Important tools are hidden behind these invisible drop-downs.
Just like this :
![image](https://imgur.com/xOweBLj.png)
And then no more confusion, everything is clear. Just make it the same as other similar buttons.

**Comment by KoBeWi** [comment]
Resolved by #48742
