### ISSUE TITLE
Add a note to the documentation that DEPTH is only available in GLES3.

### ISSUE THREAD

**Issue by ZainlessBrombie** [godotengine/godot#27417]
Writing to it in GLES2 completely breaks rendering. Could this writing to depth buffer be ignored in GLES2, where it is unsupported, instead of breaking the renderer?

**Comment by clayjohn** [comment]
This is a good idea. Can you also open a separate issue in the godot-docs repository for the documentation issue?

**Comment by ZainlessBrombie** [comment]
https://github.com/godotengine/godot-docs/issues/2298
