### ISSUE TITLE
LineEdit and TextEdit improvements when removing text

### ISSUE THREAD

**Issue by issork** [godotengine/godot#27420]
Hello, this is a suggestion for some LineEdit improvements when removing text. The main goal is to achieve a behavior that is more common across similar controls in other programs.

As a comparison, this is what the LineEdit looks like in Godot:

https://github.com/godotengine/godot/assets/180032/24cd377e-b179-4b1b-b4e2-b1676dbe6ec9

And this is the spotify searchbar:

https://github.com/godotengine/godot/assets/180032/05f6792e-4943-4475-a1a5-802ea98e38d0

But why do I think that the behavior of the spotify searchbar is better?
- presents as much information to the user as possible, without any loss
- characters aren't either drawn or not drawn, but instead can be partially drawn, which prevents the caret from jumping around when removing text

LineEdits always bothered me because of this.

This applies to TextEdit as well.

**Comment by girng** [comment]
Yeah, I've noticed this as well just never could put it into words, thanks for creating this issue.

**Comment by TheSofox** [comment]
The images are broken.

**Comment by Calinou** [comment]
> The images are broken.

Gfycat shut down on 2023-09-01. Luckily, [Archiveteam did their thing](https://wiki.archiveteam.org/index.php/Gfycat) so I replaced the URLs in OP with reuploaded videos downloaded from Wayback Machine.
