### ISSUE TITLE
Camera with Environment gets smeared on the right side

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#2742]
If a viewport camera has an environment attached the result is a smearing of the right side of the image.

![camera_bug](https://cloud.githubusercontent.com/assets/15687516/10995980/4976e3d8-8481-11e5-8466-e6e209c06b0a.jpg)

**Comment by akien-mga** [comment]
On what platform do you experience this issue? Does it happen from the start, or only after resizing the viewport? What are your project resolution and stretch settings?

Cool graphics btw :D

**Comment by PullTheStrings** [comment]
The platform is Windows 8.1, Godot 2.0 Alpha. I am previewing the project on a 1200x1920 screen (in vertical position). The stretching does NOT appear if the preview is not stretched (in my case shrinked) to fit my monitor.

 My Settings are:

![screenshotdisplaysettings](https://cloud.githubusercontent.com/assets/15687516/10996307/37b9ca22-8484-11e5-85c7-595fffdbc60c.jpg)

Thanks.

**Comment by akien-mga** [comment]
Might be related to #1571 and #2377. There is a rebasing issue in the PR currently but maybe you could try to apply the patch directly to see if it fixes your issue?

See: https://github.com/rippledodger/godot/commit/f15bd9c8aa6ff62ed3358f4809b735a56110f3fb.patch
This requires being able to compile Godot from git of course.

**Comment by PullTheStrings** [comment]
I applied the patch (well one who knows programming did) and this was the result. Not an improvement unfortunately. The black areas is where there used to be image. Ah well, rolling back Godot.
![resultofpatch](https://cloud.githubusercontent.com/assets/15687516/10997503/eb4c561e-848d-11e5-888a-5464e8a58e9d.jpg)

**Comment by reduz** [comment]
Does it happen if you change stretch mode from viewport to 2D?

**Comment by reduz** [comment]
you most likely don't want this kind of stretching if you are doing 3D, as it is meant mostly for 2D games

**Comment by PullTheStrings** [comment]
This on screen smearing still happens when stretch mode is set to 2D.

**Comment by reduz** [comment]
Can I get a test project for this?

**Comment by reduz** [comment]
a very simple test project would be apreciated

**Comment by reduz** [comment]
this was fixed by a recent commit (tested on screenspace shaders project) , repoen if it still fails in different cases
