### ISSUE TITLE
Send multiple arguments to Tween.interpolate_method

### ISSUE THREAD

**Issue by Zizico2** [godotengine/godot#27425]
*Feature request*

I think we should be able to send more arguments to a method being interpolated by Tween.interpolate_method. Tween.interpolate_method should receive one more argument, an array, which's values would be passed into the interpolated method as arguments (other than the interpolated value, which would be passed as a standalone argument).

**Comment by Zizico2** [comment]
Closed since the Tweens are being rewritten and this is no longer a problem

**Comment by ha-kuro** [comment]
Can you interpolate multiple arguments on the new rewrite?
I've noticed you can add an array of additional arguments but from what I've seen we can only interpolate the first argument 
[Tween rewrite](https://github.com/godotengine/godot/pull/41794)
