### ISSUE TITLE
Light2D allow sensible height values in editor

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27428]
Currently the height property of Light2D nodes is limited to -100 to +100, however when changed via shaders, values from -2048 to +2048 still produce _good_ and often desirable results.

https://github.com/godotengine/godot/blob/81292665d5dcc991d3c9341245b269193329ee22/scene/2d/light_2d.cpp#L441 the code in question that would need changing.

GRIEF example at 64. (The light itself is set to that as well.)
![image](https://user-images.githubusercontent.com/44248915/54970548-cfabdb00-4f82-11e9-9b05-eec0b9ba0cd2.png)

GRIEF example at 512.
![image](https://user-images.githubusercontent.com/44248915/54970558-d9354300-4f82-11e9-88a8-9acfd97fc26e.png)

**Comment by avencherus** [comment]
Simple enough.  X)

**Comment by akien-mga** [comment]
Fixed by #27448.
