### ISSUE TITLE
LineEdit bug when removing text with align=right/center

### ISSUE THREAD

**Issue by issork** [godotengine/godot#27421]
**Godot version:**
3.1-stable

**Issue description:**
When removing text from a LineEdit that has its alignment set to "Center" or "Right" and contains more text than can be shown, the caret starts acting weird. This gif shows it:
![](https://thumbs.gfycat.com/RealNewAfricanhornbill.webp)

As you can see, the text is not being aligned properly and too few characters are drawn. With alignment set to "Center", it behaves like alignment set to "Left", then suddenly jumps back to the correct alignment when only one character remains.

**Steps to reproduce:**
Delete text from a full LineEdit with "Align" set to "Center" or "Right" by pressing backspace.

**Edit:
This is also happening with align set to "Center", the offset is wrong until theres only one remaining character.**

**Comment by samH-FIT** [comment]
Would this issue be stemming from line_edit.cpp? Or would it be coming from a more general file, like text_edit.cpp?

**Comment by MennoMax** [comment]
@samH-FIT This comes from LineEdit, TextEdit doesn't have alignment.

I'm assuming this is due to a wrong x offset in https://github.com/godotengine/godot/blob/9b691718f54e72854d137c9f7cb91b47d1e0d381/scene/gui/line_edit.cpp#L681

**Comment by KoBeWi** [comment]
I discovered that the bug comes from `window_pos`. It's not updated properly for non-left aligns.

**Comment by MennoMax** [comment]
This isn't completetly fixed yet, as seen in the video below.
The order of the columns is in text alignment order, so the right column has align=right on it for example.

https://drive.google.com/open?id=1Lw4bwEbsztbKUkn5h8hkB3f8nM1QqkOR

As you can see, when removing text, there are still not enough characters drawn for center/right alignment. There are no more than 20 characters drawn at any point, even when it gets to the chars with a smaller width, which would allow for more characters drawn.

**Comment by KoBeWi** [comment]
I can confirm the above case in a920f9727

**Comment by FeralBytes** [comment]
I still see this issue for right align and for place holder text centered in Godot 3.2.2-beta4 on Linux and Android.
