### ISSUE TITLE
Allow to drop any file into Godot

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#27426]
**Godot version:**
3.1

**Issue description:**
It's possible to drop some files onto Godot's window and they get added to the selected directory. Cool. But it seems to work only for resources that can be imported and for fonts. Anything else is just ignored. Not only it's confusing, there's no real reason why this happens (is there?). I mean, if someone drops a file into editor, that person wants it to be in the project. And even if it's accidental, deleting a file isn't a big deal.

So is it possible this can be changed?

**Comment by Calinou** [comment]
Non-resource files aren't displayed in the FileSystem dock, so this could become confusing. For instance, if you were to drag a file named `README.md`, it would be moved over but you wouldn't see it in the FileSystem dock, as it only displays resources.

**Comment by FIF15** [comment]
@Calinou When I drag a folder containing .gltf along with its .bin file, that .bin file would not be moved and there will be load error when opening the .gltf file. This is also confusing when you allow the drag of entire folder.

**Comment by KoBeWi** [comment]
What if there was a dialog saying "Some of the dropped files are not recognized by Godot and won't show in file system dock. <list of files> Continue anyway?

**Comment by KoBeWi** [comment]
Seems like it was implemented or it works due to some bug xd
There is no indication of any kind that the file was copied, but the original issue is effectively resolved, so whatevs.
