### ISSUE TITLE
Unable to use Clang-Tidy and Clazy in Qt Creator 4.90 beta 2 in most of files

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#27434]
**Godot version:**
3.2 a53645e

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
I tried to use configured from docs QT Creator 4.90 beta 2(https://docs.godotengine.org/en/3.1/development/cpp/configuring_an_ide.html?highlight=qt%20creator), to check with Clang-Tidy and Clazy(It is some kind of Clang Static Analyzer) Godot code, but most files shows error: 
```
In file included from /home/rafal/Pulpit/mojgodot/scene/gui/container.cpp:31:
In file included from /home/rafal/Pulpit/mojgodot/scene/gui/container.h:34:
In file included from /home/rafal/Pulpit/mojgodot/scene/gui/control.h:34:
In file included from /home/rafal/Pulpit/mojgodot/core/math/transform_2d.h:34:
In file included from /home/rafal/Pulpit/mojgodot/core/math/rect2.h:34:
In file included from /home/rafal/Pulpit/mojgodot/core/math/vector2.h:35:
In file included from /home/rafal/Pulpit/mojgodot/core/ustring.h:35:
In file included from /home/rafal/Pulpit/mojgodot/core/cowdata.h:34:
/home/rafal/Pulpit/mojgodot/modules/gdnative/include/gdnative/string.h:66:10: fatal error: 'gdnative/array.h' file not found
#include <gdnative/array.h>
         ^~~~~~~~~~~~~~~~~~
```
Seems that QT Creator in opposite of scons can't recognize which folder should search to find file.
The problem occurs because <gdnative/array.h> can be used from:
modules/gdnative/array.h (array.h doesn't exists) or
modules/gdnative/gdnative/array.h (array.h doesn't exists) or
modules/gdnative/include/gdnative/array.h (array.h exists here)

![Zrzut ekranu z 2019-03-26 11-55-52](https://user-images.githubusercontent.com/41945903/54991989-6ea1f880-4fbe-11e9-97bc-cde7690e5c55.png)

**Comment by neikeq** [comment]
That documentation page has it wrong. It's not enough to just add `.` to the "_project\_name_.includes" file. You have to remove all the include paths that Qt Creator auto-generated in this file, and then add the actual include paths for Godot. You can get these from the build commands.

This is what I have on Linux:

```
.
platform/x11
/usr/include/glib-2.0
/usr/lib/pkgconfig/../../include/mono-2.0
```

On Windows I have the following (versions may vary):

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\*
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\winrt
.
platform\windows
C:\Program Files\Mono\include\mono-2.0
```

I didn't take all the include paths from the build commands, so a few may be missing. Still it gave me good results so far.

**Comment by Calinou** [comment]
@qarmin Can you still reproduce this on Godot 3.2.3 or `master`?

**Comment by qarmin** [comment]
This is mostly problem in documentation about files/folders to include in QtCreator, so this is not really Godot bug
