### ISSUE TITLE
Depth texture has no resource!

### ISSUE THREAD

**Issue by sdfgeoff** [godotengine/godot#27438]
Current godot master (81292665d5dcc991d3c9341245b269193329ee22) has the depth texture completely missing.

Renderdoc screenshot:
![missing](https://user-images.githubusercontent.com/13490050/55004770-1af1d800-4fdb-11e9-8293-5e031a705a87.png)

I suspect this is the cause behind:
#27423
#27301
#25535

Possibly also solved by #27317 but I haven't tested

**OS/device including version:**
ArchLinux

**Steps to reproduce:**
Open the attached project.
A renderdoc capture is included in the zip.
[missing_depth_bug.zip](https://github.com/godotengine/godot/files/3008557/missing_depth_bug.zip)

**Comment by Nophlock** [comment]
Yeah, the depth buffer isn't working in 3.1-Stable at all. I actually moved to Godot 3.1-beta2 simple because this was last version where the depth buffer works.

**Comment by TheDuriel** [comment]
Temporary Depth buffer fix:

Add a light to the scene.
Don't enable shadows.
Set contacts to 1.

**Comment by Nophlock** [comment]
@TheDuriel 
Wow this actually works, thanks for the tip ^^

**Comment by clayjohn** [comment]
This should be fixed in master with PR #27317

**Comment by akien-mga** [comment]
Fixed by #27317.
