### ISSUE TITLE
Timer stops running or never emits the timeout signal

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#27437]
**Godot version:**

Godot 3.1-stable

**OS/device including version:**

**Issue description:**

Since I upgraded my project to godot 3.1-stable from 3.0.6-stable I have been experiencing some weird behaviour with the Timer.

Sometimes the timer stops right after I call `timer.start()`. Fx I start a timer right after I set the wait time to 5 seconds. The timer stops at 4.992424 seconds and doesn't run any more. This causes my game to "freeze" because I do, `yield(timer, "timeout")`.

I have also caught a timer with one shot being false, restarting as it should, but it doesn't emit the timeout signal, at all. It just keeps restarting when it reaches 0 but no signal.

Happens with the timer node as well as the SceneTreeTimer `yield(get_tree().create_timer(1), "timeout")`.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
I never had these problems. Could you provide any reproduction project? Or more information, since "sometimes" is not really helpful when it doesn't seem to affect everyone.

**Comment by Keetz** [comment]
I am still working on this issue, trying to figure out what is going on and trying to reproduce this on a bare minimum project, but it isn't easy.

I noticed that when it happens, if I go into the remote scene tree and change the process_mode it seems to update itself and start running again.

Sometimes I get this error when it happens, but only sometimes:

```
ERROR: add_to_group: Already in group: idle_process_internal
   At: scene/main/scene_tree.cpp:117.
```

**Comment by Keetz** [comment]
Together with @Tugsav we found what causes the problem! It isn't caused by the timer, but AudioStreamPlayer. It was in combination with a timer and a "big" project that my initial problem occured, because the AudioStreamPlayer can cause the game process to speed up and then cause the timer to have some weird behaviour, that is also why it was so hard to create a minimal reproduction project.

I will close this issue as it isn't directly related to the timer, and a PR will be up very soon to fix the AudioStreamPlayer!
