### ISSUE TITLE
Area2D/3D monitoring and monitorable are not working according to docs

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#27441]
**Godot version:**
3.1. stable

**OS/device including version:**
Win7

**Issue description:**
My character scene has an _attack_Area2D_ with a _CollisionPoligon2D_ which I animate using the _AnimationPlayer_. My destructable scene has a _hitbox_Area2D_ with a _CollisionShape2D_ and a script for `func _on_hitbox_area_entered(area)`: that is supposed to detect the overlapping _attack_Area2D_ of the character scene when the character's _Animationplayer_ turns the _attack_Area2D_ "on".

Everything is on the same collision layer and mask.

According to the docs, this should work:
 I have just `monitorable `animated on the character _attack_Area2D_, and `monitoring `on the destructable's hitbox. But it does not work. It is not detecting. Minimal Project:
https://github.com/golddotasksquestions/Collision_Detection-only_Monitorable
![only-monitoring](https://user-images.githubusercontent.com/47016402/55030034-c581ef00-500b-11e9-89c7-d9c5a2c88984.gif)
The character is modulated darkred when his attack_Area2D is "hot". Meaning this is when his attack should destroy the destructables.

By the way:
Here, I have both `monitoring `and `monitorable `animated via _AnimationPlayer_, while turned off by default. This works as intended, but I get the error `!area_in && !E` . Minimal Project:
https://github.com/golddotasksquestions/Collision_Detection-both_Monitorable_Monitoring
![both-monitoring_monitorable](https://user-images.githubusercontent.com/47016402/55030068-d5013800-500b-11e9-82be-49682b16dd42.gif)

Here, I have `monitorable `and `monitoring `everywhere on default, while the _CollisionPolygon2D_ is disabled and enabled via _AnimationPlayer_, which also does not work. It's not detecting either. Minimal Project:
https://github.com/golddotasksquestions/Collision_Detection-collpoly_disabled
![collpol_disabeled](https://user-images.githubusercontent.com/47016402/55030106-eb0ef880-500b-11e9-9d84-881b277406a7.gif)

(related to this issue? https://github.com/godotengine/godot/issues/17812)

**Comment by raphael10241024** [comment]
Maybe related to https://github.com/godotengine/godot/issues/23484

**Comment by noidexe** [comment]
I'm having exactly the same issue. I tried getting overlapping areas and it doesn't work either. 
I haven't checked the source code but it's as if areas are only checked for overlaps when their active and they move.

**Comment by kickmaniac** [comment]
I ended up manually switching monitoring/monitorable off and on to update overlapping areas array.

**Comment by svendixon** [comment]
![2019-11-06 00-22-17](https://user-images.githubusercontent.com/14341036/68270799-99602f00-002c-11ea-94cd-e80f064db926.gif)

I created another example: [OnEnter.zip](https://github.com/godotengine/godot/files/3812651/OnEnter.zip)

Both enemy and player have **monitoring** and **monitorable** set to **true**.

Move the player over the enemy and both detect each other.

However once you enter the enemy and press **Enter** which disables the player's **monitoring** and **monitorable**, and press **Enter** again to re-enable, only the player detects the enemy. 

Shouldn't the enemy detect the player now that it's **monitorable** is **true**?

By pressing **Space** it disables the **Area2D** instead of changing **monitoring** or **monitorable**. Press again to re-enable and they both detect each other.

I would expect the behavior to be the same.

**Comment by golddotasksquestions** [comment]
For anyone looking into this, CollisionShapes and CollisionPolygons are also only detected when moving: https://github.com/godotengine/godot/issues/34124

**Comment by golddotasksquestions** [comment]
I'm closing this as I don't seem to be able to replicate this issue in Godot 3.2.stable any more. (Win)
If someone else still has it please let me know and comment, to reopen it.

**Comment by golddotasksquestions** [comment]
I have to reopen this as monitorable and monitoring still don't seem to behave consistent in situations when both Areas are not moving:

u/Armanlex [on Reddit](https://www.reddit.com/r/godot/comments/ew6a90/tip_if_many_collisionshapesarea2d_seem_to_cause/) pointed out that they still need position=position to get the behaviour they wanted (exit signal not firing when monitorable is turned off):

![monitorable_behaviour1](https://user-images.githubusercontent.com/47016402/73562558-ac33a580-445b-11ea-8a93-f32c53c6defc.gif)

The monitoring behaviour also does not seem to be consistent monitorable when turned on and off while not moving:

![monitorable_monitoring_inconsist1](https://user-images.githubusercontent.com/47016402/73562707-f9177c00-445b-11ea-833d-bd8019fc79b7.gif)

Minimal Project for anyone who would like to try:
[MonitoringMonitorable_Armanlex.zip](https://github.com/godotengine/godot/files/4140729/MonitoringMonitorable_Armanlex.zip)

**Comment by MMUTFX2053** [comment]
this bug still exists in 4.1.2, i made a bullet scene from an area2d, with monitorable turned off, it doesnt detect anything

**Comment by golddotasksquestions** [comment]
@MMUTFX2053 Can you please share a minimal reproduction project?

**Comment by MMUTFX2053** [comment]
here it is, when hovering over either body or area, it should change color, but only does so when the area hovers over another area
[area2d_test.zip](https://github.com/godotengine/godot/files/12909178/area2d_test.zip)

**Comment by golddotasksquestions** [comment]
@MMUTFX2053 I tested your Minimal Reproduction Project in Godot 4.2 Beta2 and can confirm the behavior you are describing.

**Comment by gregkrsak** [comment]
Also running into this bug. Hoping for a fix in 4.3

**Comment by Calinou** [comment]
Please continue the discussion in https://github.com/godotengine/godot/issues/66468 or https://github.com/godotengine/godot/issues/74300.

**Comment by gregkrsak** [comment]
> Please continue the discussion in #66468 or #74300.

Those two issues deal specifically with Area3D nodes, while I am seeing an issue with Area2D nodes.

**Comment by AThousandShips** [comment]
No same issue, see the thread

**Comment by adadgio** [comment]
This bug still exists... in Area2D
