### ISSUE TITLE
[Mono] ResourceLoaderInteractive never stops loading

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#27449]
**Godot version:**

3.1 Mono

**OS/device including version:**

Windows 10

**Issue description:**

Godot Mono's ResourceLoaderInteractive never stops loading, causing an exception when this resource is loaded again later:

```
E 0:00:03:0088   Resource: 'res://SceneA.tscn' is already being loaded. Cyclic reference?
  <C Source>     core/io/resource_loader.cpp:487 @ load_interactive()
  <Stack Trace>  :0 @ Godot.ResourceInteractiveLoader Godot.NativeCalls.godot_icall_2_963(IntPtr , IntPtr , System.String , System.String )()
                 ResourceLoader.cs:37 @ Godot.ResourceInteractiveLoader Godot.ResourceLoader.LoadInteractive(System.String , System.String )()
                 Loader.cs:15 @ void Loader+<LoadAsync>d__1.MoveNext()()
                 :0 @ void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Loader+<LoadAsync>d__1 >(Loader+<LoadAsync>d__1& )()
                 :0 @ System.Threading.Tasks.Task Loader.LoadAsync(System.String )()
                 Loader.cs:8 @ void Loader._Input(Godot.InputEvent )()
```

However, the equivalent GDScript code does not produce any errors.

```cs
	public async Task LoadAsync(string path) {
		GD.Print("Loading...");
		var loader = ResourceLoader.LoadInteractive(path);
		Resource resource = null;
		while (resource == null) {
			var err = loader.Poll();
			if (err == Error.FileEof) {
				resource = loader.GetResource();
			}

			await ToSignal(GetTree(), "idle_frame");
		}
		
		GD.Print("Done.");
	}
```
```swift
func load_async(path):
	print("Loading...")
	var loader = ResourceLoader.load_interactive(path)
	var resource
	while not resource:
		var err = loader.poll()
		if err == ERR_FILE_EOF:
			resource = loader.get_resource()
		
		yield(get_tree(), "idle_frame")
	
	print("Done.")
```

This worked correctly previously.

**Minimal reproduction project:**

[CSResourceLoader.zip](https://github.com/godotengine/godot/files/3010992/CSResourceLoader.zip)

**Comment by NathanWarden** [comment]
I can confirm this as well. I get the same error and the variable `loader` is null as of the line:

```C#
var loader = ResourceLoader.LoadInteractive(path);
```

**Comment by NathanWarden** [comment]
I took another look at this and you need two using statements so that the resources are disposed of properly, or you'll need to call dispose manually somewhere else. The code below will load SceneA. :)

```C#
public async Task LoadAsync(string path)
{
	using (var loader = ResourceLoader.LoadInteractive(path))
	{
		Resource resource = null;

		while (resource == null)
		{
			var err = loader.Poll();

			if (err == Error.FileEof)
			{
				using (resource = loader.GetResource())
				{
					var s = resource as PackedScene;
					GetTree().GetRoot().AddChild(s.Instance());
					break;
				}
			}

			await ToSignal(GetTree(), "idle_frame");
		}

		GD.Print("Done.");
	}
}
```

**Comment by neikeq** [comment]
Looks like this is not a bug. As far as I understand, you cannot have more than one `ResourceInteractiveLoader` for the same path. If you don't dispose it once you're done loading, you're leaving that task to the garbage collector whenever it decides to collect.

Here's the same code, modified to dispose the `ResourceInteractiveLoader` once the work is done:

``` C#
public async Task LoadAsync(string path) {
	GD.Print("Loading...");
	using (var loader = ResourceLoader.LoadInteractive(path)) {
		Resource resource = null;
		while (resource == null) {
			var err = loader.Poll();
			if (err == Error.FileEof) {
				resource = loader.GetResource();
				break;
			}

			await ToSignal(GetTree(), "idle_frame");
		}
	}

	GD.Print("Done.");
}
```

**Comment by neikeq** [comment]
Also, I assume you were in the process of writing something like this, but in case someone else is reading this trying to find a final LoadAsync implementation, this could be a good example:

``` C#
public async Task<T> LoadAsync<T>(string path)
	where T : Resource
{
    using (var loader = ResourceLoader.LoadInteractive(path))
    {
        Error err;

        do
        {
            err = loader.Poll();
            await ToSignal(GetTree(), "idle_frame");
        } while (err == Error.Ok);

        if (err != Error.FileEof)
            throw new ResourceInteractiveLoaderException(err);

        return (T)loader.GetResource();
    }
}

public class ResourceInteractiveLoaderException : Exception
{
    Error err;

    public ResourceInteractiveLoaderException(Error err)
    {
        this.err = err;
    }

    public override string Message => $"ResourceInteractiveLoader failed with error: {err}";
}
```

**Comment by NathanWarden** [comment]
@neikeq I like your implementation, thanks! :)

I noticed `Resource` also derives from `IDisposable`. So in your implementation `loader.GetResource()` isn't in a using statement (which makes sense). Do we still need to call Dispose manually on the resource when we're done with it, or is this handled internally? Thanks! :)

**Comment by neikeq** [comment]
If you don't dispose it yourself, you're leaving it to the GC. I recommend disposing it manually when possible.

**Comment by jkunable** [comment]
Is it possible for someone to update [Background Loading](https://docs.godotengine.org/en/stable/tutorials/io/background_loading.html) to specify that C# users should call dispose on completion of loading because I spent days trying to figure out why I was getting this cyclic reference error
