### ISSUE TITLE
Settings tab to redefine hotkeys

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#2745]
It could be useful to redefine hotkeys . 
For example, usually I use F3 to repeat the last search. 
While pressing F3 in code editor, it opens the 3D view, I'd like to redefine this hotkey and possibly others e.g. Ctrl+A

**Comment by akien-mga** [comment]
We have many issues already about giving the possibility to redefine some hotkeys or to define new ones, but this one likely has the broadest range.

@godotengine/bugsquad: Let's use this issue as the main one regarding hotkey issues by making cross-references in the other issues (or closing as duplicates when relevant).

**Comment by akien-mga** [comment]
I think the addition of a tab in the editor settings to redefine hotkeys would be nice. Since some hotkeys are tool-dependent (2D/3D viewport, script editor, etc.) the hotkeys should probably be listed by "tool".

**Comment by bojidar-bg** [comment]
:+1: This is a nice idea! :smile:  (Why wasn't it opened before?!)

**Comment by Gfurst** [comment]
I support this feature as well, specifically I would like the ability to change the save keys: switch the save scene and save script which always mix.

**Comment by djrm** [comment]
Now godot has configurable shortcuts

**Comment by akien-mga** [comment]
Indeed, closing as fixed \o/
