### ISSUE TITLE
Godot select first file when I click at the second, third etc.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#27457]
**Godot version:**
3.1 stable

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When I search files and find two or more with same name, then when I select second, Godot select first searched file.

**Steps to reproduce:**
![jfile](https://user-images.githubusercontent.com/41945903/70702055-b93ede80-1ccd-11ea-983c-f2a9353ec110.gif)

**Comment by tom-jk** [comment]
Can reproduce in 3.1 and 3.2.3.rc3.

Only happens in split mode (ie. with inline list of files, not files under folders).
The correct file _is_ actually opened (check resource path in inspector).

**Comment by KoBeWi** [comment]
Fixed

https://github.com/user-attachments/assets/21282bbe-0d9f-4033-b768-ee4e5ccd90f0
