### ISSUE TITLE
GrooveJoint2D misbehaving?

### ISSUE THREAD

**Issue by guzzard** [godotengine/godot#27454]
**Godot version:**
3.1 stable mono

**OS/device including version:**
Arch Linux, kernel 5.0.4-1-ck

**Issue description:**
The rigid body does not stay within the constrains of the groove joint. It's possible to push the rigid body way off to the right/left, and it slides past the intended points and very very slowly returns.

![GrooveJoint2D](https://user-images.githubusercontent.com/9007314/55077785-e5132900-5098-11e9-88da-8babedb875b5.gif)

**Steps to reproduce:**
Start attached project and test using mouse.

**Minimal reproduction project:**
[GrooveJoint2D.zip](https://github.com/godotengine/godot/files/3013142/GrooveJoint2D.zip)

**Comment by avencherus** [comment]
Yep, they've been unstable for some time.  I've only gotten them to be a little useful by also attaching very stiff springs, and limiting the interaction, but as is, they won't work for doors and such.

**Comment by avencherus** [comment]
Probably releated:  https://github.com/godotengine/godot/issues/19376
