### ISSUE TITLE
Live Edit In Godot 3.1 (How to)

### ISSUE THREAD

**Issue by Brayacon** [godotengine/godot#27451]
I can't find live editing in the GD 3.0
(I'm working on an Android game and I wished it could hot reload for fast debugging) please show me how I can hot reload/ Live Edit.

**Comment by Chaosus** [comment]
https://www.youtube.com/results?search_query=godot+live+edit
https://www.youtube.com/results?search_query=godot+debugging

**Comment by Calinou** [comment]
The issue tracker is not meant to be used for support questions. There's already an [issue in the godot-docs repository](https://github.com/godotengine/godot-docs/issues/368) about improving debugging documentation (which includes live editing).
