### ISSUE TITLE
Some formatting in built-in docs is missing

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#27456]
**Godot version:**
3.1

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/55084387-61ac0480-50a5-11e9-89b9-c5fc0a4ff846.png)

The built-in docs, while are nicely formatted, have some issues that make them less readable. The most major one is that code blocks aren't formatted at all. They are displayed as plain indistinguishable text (just see above).

From minor ones, seems like things like bold text, and probably italic too, aren't supported.

**Comment by Chaosus** [comment]
Yeah italic and bold arent't supported, also I think [code]-words should have a different color

**Comment by girng** [comment]
yeah, would be amazing =].

would also be a feature for RTL as well.

**Comment by volzhs** [comment]
I saw a beautiful doc using godot.

![image](https://user-images.githubusercontent.com/8281454/55141875-bbccc880-517e-11e9-99ef-148a0a48fcd7.png)

from Rpg in a box https://www.rpginabox.com/development-update-as-of-3-28-18/

**Comment by DriNeo** [comment]
The offline doc reader Zeal displays html pages and can even apply a dark theme. The open source code may be a source of inspiration.

**Comment by Calinou** [comment]
One of the main ways to improve documentation readability would be to limit the displayed width to a reasonable value (regardless of the editor window width). Lines that are too long become difficult to read, which is especially noticeable on a 2560×1440 display at 100% scaling.

**Comment by Calinou** [comment]
To make inline code blocks (`[code]…[/code]`) stand out more, we could add a subtle background to them. However, we'd probably need to extend RichTextLabel so it supports something like a `[background=color]` tag.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3399.

As of 4.0, built-in docs now support bold, italic, [background colors for inline code/kbd/code blocks](https://github.com/godotengine/godot/pull/62710) ([with padding for code blocks](https://github.com/godotengine/godot/pull/63124)).

The line width is also limited to a reasonable value since Godot 3.2.
