### ISSUE TITLE
Bookmarks to switch scenes and code lines

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#2746]
It can be useful to define bookmarks .
For example, clicking right mouse button on the line number (in code editor) may display a context menu to toggle a bookmark on that line (and maybe breakpoint)
Then have buttons that allow you to move to the point where was defined next or previous bookmark .
Bookmarks can be placed also on the scene, so you can switch to different scenes or points of different code using bookmarks.
I hope I have made ​​it clear what I mean.

**Comment by KoBeWi** [comment]
Well, now we have function shortcuts, but bookmarks would still be useful for long functions. I often have to jump between two lines in code and it would be much more efficient if I didn't have to search them each time.

Notepad++ has bookmarks done very well.
Ctrl + F2 to toggle bookmark on current line
F2 to go to next bookmark
Shift + F2 to go to previous bookmark

Makes navigating code A LOT easier.

**Comment by rogeriodec** [comment]
I was going to suggest this too, but I found this suggestion, so I'm one more to support this idea.
Too bad the request was made almost 4 years ago and so far nothing has been done ...

**Comment by KoBeWi** [comment]
With #28218 merged, should we also add scene bookmarks (whatever they are) or is this issue done?

**Comment by akien-mga** [comment]
I think it can be considered solved. I'm not sure what scene bookmarks would be like, but if there's interest in such feature it should likely be discussed separately.

Fixed by #28218.
