### ISSUE TITLE
Fullscreen does not work on OSX when resizing is prohibited

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#27464]
**Godot version:**
2.X, 3.X

**OS/device including version:**
OSX (Hackintosh but still)

**Issue description:**
- Create a new project 
- Under Display uncheck Resizable
- Under Display check Fullscreen

**Expected behavior**
- Application starts fullscreen

**Actual behavior**
- Application starts windowed

**Comment by bruvzg** [comment]
Not sure this should be considered a bug. Making macOS full-screen window non resizeable will break systems wide means of entering/exiting full-screen (using title bar button, mission control or multi-touch gestures) and cause some strange behaviour in a split view mode.

**Comment by xsellier** [comment]
@bruvzg Fair enough. About that I think Godot should either:

1. Reset resizing value when fullscreen
2. Or add a Note to their documentation explaining that.

Side note, it works well on linux, android, windows (have not tested it on iOS). But it does not work on OSX. So, this behavior is kinda like a bug to me. Godot should behave the same on every platform.

**Comment by bruvzg** [comment]
> Reset resizing value when fullscreen

We can make it resizeable on entering full-screen and revert it after exiting it, this will allow users to exit full-screen using system wide means (but not enter), and use full-screen with non resizeable windows.

**Comment by luislodosm** [comment]
Note: You can't set fullscreen on macOS if you have `display/window/size/always_on_top` of `ProjectSettings` set to `true`

**Comment by Calinou** [comment]
@bruvzg Should we make fullscreen implicitly disable `always_on_top`? See above.

**Comment by bruvzg** [comment]
> @bruvzg Should we make fullscreen implicitly disable always_on_top (at least on macOS)? See above.

Save the state, disable it before entering full screen, and restore to previous state after exiting full screen (similar to #27490).
On macOS full screen apps run on a separate desktop, but `always_on_top` might have some effect on Linux and Windows.

**Comment by bruvzg** [comment]
Test patch for 3.x, I'll open PRs for both master and 3.x a bit later.

```diff
diff --git a/platform/osx/os_osx.mm b/platform/osx/os_osx.mm
index 325aee8ad4..b6565b0c60 100644
--- a/platform/osx/os_osx.mm
+++ b/platform/osx/os_osx.mm
@@ -322,6 +322,9 @@ static NSCursor *cursorFromSelector(SEL selector, SEL fallback = nil) {
 
 	if (!OS_OSX::singleton->resizable)
 		[OS_OSX::singleton->window_object setStyleMask:[OS_OSX::singleton->window_object styleMask] & ~NSWindowStyleMaskResizable];
+
+	if (OS_OSX::singleton->on_top)
+		[OS_OSX::singleton->window_object setLevel:NSFloatingWindowLevel];
 }
 
 - (void)windowDidChangeBackingProperties:(NSNotification *)notification {
@@ -1688,7 +1691,7 @@ Error OS_OSX::initialize(const VideoMode &p_desired, int p_video_driver, int p_a
 	}
 
 	on_top = p_desired.always_on_top;
-	if (p_desired.always_on_top) {
+	if (p_desired.always_on_top && !p_desired.fullscreen) {
 		[window_object setLevel:NSFloatingWindowLevel];
 	}
 
@@ -2539,7 +2542,7 @@ void OS_OSX::_update_window() {
 		[window_object setHidesOnDeactivate:YES];
 	} else {
 		// Reset these when our window is not a borderless window that covers up the screen
-		if (on_top) {
+		if (on_top & !zoomed) {
 			[window_object setLevel:NSFloatingWindowLevel];
 		} else {
 			[window_object setLevel:NSNormalWindowLevel];
@@ -2711,6 +2714,7 @@ void OS_OSX::set_window_fullscreen(bool p_enabled) {
 	}
 
 	if (zoomed != p_enabled) {
+		[window_object setLevel:NSNormalWindowLevel];
 		if (layered_window)
 			set_window_per_pixel_transparency_enabled(false);
 		if (!resizable)
@@ -2808,6 +2812,9 @@ void OS_OSX::set_window_always_on_top(bool p_enabled) {
 
 	on_top = p_enabled;
 
+	if (zoomed)
+		return;
+
 	if (is_window_always_on_top() == p_enabled)
 		return;
```
