### ISSUE TITLE
Editor view gets corrupted on rx vega 56

### ISSUE THREAD

**Issue by cosmos841** [godotengine/godot#27466]
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Windows 10 x64 
Radeon RX Vega 56 Driver version: 19.3.3

**Issue description:**
2d and 3d views get corrupted after a while. Same issue as described here: https://www.reddit.com/r/godot/comments/afekg2/new_to_godot_having_a_bug_happens_after_having/ Restarting the editor temporarily fixes the problem. Happens after moving something inside the editor, editing properties or simply switching between nodes.

**Steps to reproduce:**
follow the tutorial https://docs.godotengine.org/en/3.1/getting_started/step_by_step/ui_game_user_interface.html
usually happens after ~10-15 minutes

**Minimal reproduction project:**
[ui_gui_design.zip](https://github.com/godotengine/godot/files/3015056/ui_gui_design.zip)

![3d](https://user-images.githubusercontent.com/49001852/55105613-39380080-50cd-11e9-9111-d8fac55db1a8.png)
![3d2](https://user-images.githubusercontent.com/49001852/55105614-39380080-50cd-11e9-992e-4ad0ea3820b1.png)
![2d](https://user-images.githubusercontent.com/49001852/55105615-39380080-50cd-11e9-92a2-46f245e5610a.png)

**Comment by nazgulsenpai** [comment]
Windows 10 x64
AMD RX 460 Driver Version 19.3.2 

Can't reproduce using the steps you listed in 20+ mins of trying. 

I know it's not the same hardware/driver version but just adding my sample to the pool.

**Comment by cosmos841** [comment]
Found out that it only happens with the GLES3 renderer.

**Comment by Frostings** [comment]
Happens to me on Windows 10 x64, Godot 3.1 stable
Radeon RX Vega 64 Driver version 19.5.2

Reproducing it is really a matter of using the inspectors tools for long enough it seems.
