### ISSUE TITLE
TileMap fix_invalid_tiles() | set_cellv() | set_cell() does not work when TileSet has set via set_tileset()

### ISSUE THREAD

**Issue by reisraff** [godotengine/godot#27479]
Similiar to this: https://github.com/godotengine/godot/issues/5076

**Godot version: 3.1**

**OS/device including version: Ubuntu 18.04**

**Issue description: TileMap fix_invalid_tiles() | set_cellv() | set_cell() does not work when TileSet has set via set_tileset()**

**Steps to reproduce:**

```gdscript
var tile_set = TileSet.new()
tile_set.take_over_path('res://foo/bar/baz.tres')

var tile_map = get_node('TileMap')
tile_map.set_tileset(tile_set)

tile_map.set_cell(10, -5, 0) # visible area

print(tile_map.get_used_cells())
tile_map.fix_invalid_tiles()
print(tile_map.get_used_cells())
```

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
This issue is actually invalid. You should use
```
var tile_set = load('res://foo/bar/baz.tres')
```
instead of this weird take over path thing. Everything works as expected when you load the resource correctly.
