### ISSUE TITLE
automatically add new line to scripts

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27476]
https://editorconfig.org/

For better compliance and ease of use with editorconfig and git, i would like it if godot automatically added a new empty line to the end of any script that does not have it.

Some more assorted commends on why this is a good idea: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/25322168#25322168

**Comment by Zylann** [comment]
If the script editor gets auto-format feature, that could be one of the things it can do

**Comment by asmoaesl** [comment]
Until an auto-format feature, would this best be done upon script file saves?

**Comment by DarknessCatt** [comment]
Will start looking into it, shouldn't take long.

**Comment by DarknessCatt** [comment]
@TheDuriel Hey, I finished the PR. I would be thankful if you could test if it's behaving as expected.

**Comment by etse** [comment]
I guess this issue could be closed then? :)

**Comment by akien-mga** [comment]
Indeed, fixed by #29262.
