### ISSUE TITLE
Feature: Move to Selected / Focus on Selected / Show selected in the editor

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#27478]
**Godot version:** 3.1

**Issue description:**
Say, I have some hierarchy and objects inside it. I don't know precisely (or simply forgot) where one of the objects is placed in the "Scene View" (where you can drag / select / rotate objects etc) but I want to move it to somewhere else.
In Unity I would have a "Focus on Selected" menu item:
https://forum.unity.com/threads/way-to-focus-scene-view-on-selected-object.766/

Are there ways to achieve the same in Godot? Did I overlook something?

**Comment by asheraryam** [comment]
Press F to focus on selected item 😄

**Comment by smedelyan** [comment]
@asheraryam thanks:D
For those who wonder: **View** -> **Center Selection (F)**
![Screenshot_2019-03-28_21-47-28](https://user-images.githubusercontent.com/47334605/55184491-550dd600-51a3-11e9-8007-9d5a386515c3.png)
