### ISSUE TITLE
add top_level toggle to Node2D and Spatial

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27473]
It is often convenient to use set_as_top_level() to preserve tree order, and decouple nodes from the usual transform inheritance. Like a Camera operating in global space, but as a child of the Player. Or a Path2D that is used by a specific enemy.

I think it would be nice to be able to toggle Node2D and Spatial nodes to ignore the transform chain. This avoids awkwards situations in which you either: Need to add a dedicated script to the node in question, only to call set_as_top_level() in _ready(). Or have the parent to the same. (Which is not in the spirit of decoupling. The parent might want to use the nodes data, but why can't that node initialize itself?)

**Comment by KoBeWi** [comment]
You can also put a Node between nodes to discard transform inheritance.

**Comment by TheDuriel** [comment]
Adding Nodes to the tree is not free, objects are relatively heavy. Not to mention that it disrupts the tree order. :D

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/42448, closing.
