### ISSUE TITLE
HTTPRequest not working in HTML Exports

### ISSUE THREAD

**Issue by dalton5000** [godotengine/godot#27475]
**Godot version:**
3.1 stable

**Issue description:**
Demo code from HTTPRequest node with call to www.mocky.io does not get executed in HTML exports

**Steps to reproduce:**
Use this code in an empty project, text in in browser export.
 ```

func _on_Button_pressed():
    $HTTPRequest.request("http://www.mocky.io/v2/5185415ba171ea3a00704eed")
```

**Minimal reproduction project:**
[HTTPRequestTest.zip](https://github.com/godotengine/godot/files/3015607/HTTPRequestTest.zip)

**Comment by Calinou** [comment]
As outlined in https://github.com/godotengine/godot/issues/25668#issuecomment-461247504, the remote server needs to allow requests from external origins.

Compare the response headers from your URL compared to [httpbin.org/get](https://httpbin.org/get) as an example:

## mocky.io

```http
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 18
Content-Type: application/json
Date: Thu, 28 Mar 2019 14:03:48 GMT
Server: Cowboy
Via: 1.1 vegur
``

## httpbin.org/get

```http
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 178
Content-Type: application/json
Date: Thu, 28 Mar 2019 14:03:58 GMT
Server: nginx
``
