### ISSUE TITLE
Make a move to position function

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot#27487]
**Godot version:**

3.1 stable

**OS/device including version:**

Windows 7

**Issue description:**

Feature request:
Please add a move to position function that can transtion a node smoothly from its current position to a given Vector2/Vector3 over time(i.e. not instanly but gradually).
Similar to unity's Vector2.MoveTowards

I think this might be useful in many conditions and should be a one line function.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment]
This is already possible with [a tween node](https://docs.godotengine.org/en/3.0/classes/class_tween.html), else you can use the linear_interpolate function on the position to do so.

**Comment by TristanAppDev** [comment]
> 
> 
> This is already possible with [a tween node](https://docs.godotengine.org/en/3.0/classes/class_tween.html), else you can use the linear_interpolate function on the position to do so.

could you explain your answer please? how is this possible **in one line** in Godot like in Unity?

**Comment by TristanAppDev** [comment]
> 
> 
> **Godot version:**
> 
> 3.1 stable
> 
> **OS/device including version:**
> 
> Windows 7
> 
> **Issue description:**
> 
> Feature request:
> Please add a move to position function that can transtion a node smoothly from its current position to a given Vector2/Vector3 over time(i.e. not instanly but gradually).
> Similar to unity's Vector2.MoveTowards
> 
> I think this might be useful in many conditions and should be a one line function.
> 
> **Steps to reproduce:**
> 
> **Minimal reproduction project:**

I think this is a great idea. I really like how NavMesh navigation and movement is done in Unity.
This is all you need to move an object in Unity:
if (Input.GetMouseButtonDown(0))
{
      Ray ray = cam.ScreenPointToRay(Input.mousePosition);
      RaycastHit hit;
      if (Physics.Raycast(ray, out hit))
      {
        agent.SetDestination(hit.point);
      }
}
