### ISSUE TITLE
Code folding for comments 

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot#27488]
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
Could we please ability to code fold comments. Sometimes you need to add longer explanation of what part of your code does and need to include several lines of comments. While it's helpful for others on a team to familiarise self with functionality of a code, it's clutter for those who already understand. I would like ability to fold any block of comments so it can be used as reference as needed but is not taking too much space otherwise.

**Comment by vorabrijesh** [comment]
I am applying for gsoc to improve editor features. Can anyone suggest how should I approach for this problem?

**Comment by Aeogen** [comment]
+1
The XML Notation is afaik like this:
`//<editor-fold desc="absence">...  //</editor-fold> `
Without space between / and < (in comments u leave space // comment)

So for godot:
```
#<editor-fold desc="absence">
func x
#</editor-fold> 
```
It also exists the "C#-Region Notation" but it is less versaitile

**Comment by Calinou** [comment]
I think OP just wants the ability to fold comments that span more than 1 line. A syntax to define foldable comments sounds overkill to me.

**Comment by Aeogen** [comment]
I cannot estimate what's overkill. I'd like to have that ability.

Btw, I reasearched on: The "right" syntax would/should be:

```
#<editor-fold desc="absence">
# comment
func x
 something folded
#</editor-fold> 
```

**Comment by mindspyke** [comment]
This would indeed be very handy, the tech for folding already seems to be in the editor so should be do-able 👀

**Comment by nonunknown** [comment]
Add a feature like C# region to godot would be nice to maintain organization, but I was thinking about another complementation called "Tabs for scripts".
Imagine that you have a code with 1000+ lines but you want to organize it, then you could use something like:
`#tab-name`
`CODE HERE`
`#end-tab`

Then the engine would create tabs that show only this part of code.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/416.
