### ISSUE TITLE
OpenVR interface does not exist in the ARVRServer in Godot 3.1

### ISSUE THREAD

**Issue by EmeraldSlash** [godotengine/godot#27480]
**Godot version:** 3.1

**OS/device including version:** Windows 10 64-bit, HTC Vive, Nvidia RTX 2070 GeForce Game Ready Version 419.17

**Issue description:** The OpenVR interface in ARVRServer does not exist, even when SteamVR is running and the OpenVR package is installed. This issue only happens on Godot 3.1, it does not happen in 3.0 (I tested it on 3.0 with the exact same project in the same session and it worked).

**Steps to reproduce:**
- Make a new project
- Go to the asset library and download and install the OpenVR package
- Create a new scene with a ARVROrigin as the root node, and an ARVRCamera under it
- Create a script attached the ARVROrigin that initializes the OpenVR interface and sets `get_viewport().arvr` to `true` and `hdr` to `false` when ready

**Minimal reproduction project:** 

[ARVR.zip](https://github.com/godotengine/godot/files/3016600/ARVR.zip)

**Comment by BastiaanOlij** [comment]
let me have a look, it sounds like either the Godot 3.0 plugin is in there which won't load (but on discord I read you already changed that) or something is wrong with the paths and its not finding the module

**Comment by BastiaanOlij** [comment]
I had no problem on my end running your example after replacing the version of the module to the new Godot 3.1 files. Just in case I've attached to this message :)
[ARVR3.1.zip](https://github.com/godotengine/godot/files/3017607/ARVR3.1.zip)

**Comment by EmeraldSlash** [comment]
Your one worked, and I also tested with the same files (that I downloaded from the GitHub and was using last night) and they worked too. Thanks for the help ;)
