### ISSUE TITLE
Allow switching between GLES2 and GLES3 in the game (restart)

### ISSUE THREAD

**Issue by HugeGameArtGD** [godotengine/godot#27495]
**Godot version:**
master

**OS/device including version:**
Any platform

**Issue description:**
It would be nice if it's possible to switch between GLES2 and GLES3 on runtime.
Currently this is only supported through the editor.
I request this feature because I don't want to export the game two times (one time for each renderer).

**Comment by Zireael07** [comment]
Recently it was made clear that GLES 2 shouldn't be used as fallback for GLES 3...?

**Comment by HugeGameArtGD** [comment]
@Zireael07 Some computers support GLES3 but are too slow to run 3d with high fps. So if there was a switch in game they would maybe have some issues with this renderer but over all the game becomes more fluently. The only issue would be that there should be .import files for etc and etc2 when it's possible to switch between both renderers.

**Comment by clayjohn** [comment]
What Zireael is saying is that GLES2 is not just a faster, simpler version of GLES3. Its a completely different backend. It is not designed so that you can switch a GLES3 project and have it work the same on lower-end hardware. Your project should be fully designed around using one or the other. Or, if you really want both, you should have two different versions.

**Comment by Zylann** [comment]
@HugeGameArtGD if you want to expose such option to make the game faster, what you should switch is not the renderer, but the features and assets your game is using.

**Comment by ca3games** [comment]
They're completelly diferent rendering engines, and some features like particles don't have GLES 2 versions.

You need to decide if you want to use all the new features and don't care about older pcs, or you really care about older pcs or mobile phones and use the GLES 2 renderer.

**Comment by HugeGameArtGD** [comment]
Is it still supported to use globals?
https://godotengine.org/qa/21575/how-you-change-project-settings-runtime-and-have-them-persist
I get the error that identifier 'Globals' is not declared in the current scope.
Is it possible with ``ProjectSettings.set(...)`` and ``ProjectSettings.save()``?

**Comment by Calinou** [comment]
@HugeGameArtGD You can start a given project with the `--video-driver GLES2` or `--video-driver GLES3` command-line argument to force a specific renderer, but this is not officially supported (except for the editor).

**Comment by HugeGameArtGD** [comment]
@Calinou Thank you, is it possible to call this with OS.execute? I've optimized the project for both renderers and except some water material everything looks the same.

**Comment by Calinou** [comment]
@HugeGameArtGD Using a project settings override is a more portable way than `OS.execute()`. Just make sure the override file uses a path of the form `user://settings.ini` (it needs to be on `user://`, otherwise it's not guaranteed to be writable to in an exported project).

**Comment by HugeGameArtGD** [comment]
@Calinou 
```
ProjectSettings.set_setting("rendering/quality/driver/driver_name", "GLES2")
ProjectSettings.save()
```
This works for me. How can I save the setting to ``user://``. Does this work for Android?

**Comment by Zylann** [comment]
@HugeGameArtGD in exported games, project settings are baked into the executable IMO, so that technique might work in your editor project but not sure about the export.

**Comment by Calinou** [comment]
I would advise using the ConfigFile for this, as `ProjectSettings.save()` will save *all* project settings into a file (which is overkill for most purposes).

**Comment by HugeGameArtGD** [comment]
@Zylann It only worked in the export (one big file next to executable and .pck)

**Comment by HugeGameArtGD** [comment]
@Calinou Thank you, I will try it. Maybe it will also work on Android. https://docs.godotengine.org/en/latest/classes/class_configfile.html

**Comment by HugeGameArtGD** [comment]
@Calinou 
How can I load the settings so it's switching to GLES2?
My code:
```
var config = ConfigFile.new()
	var err = config.load("user://settings.cfg")
	for section in _settings.keys():
		for key in _settings[section].keys():
			config.set_value(section, key, _settings[section][key])
	config.save("user://settings.cfg")
```
and
```
var _settings = {
    "rendering/quality": {
        "driver/driver_name": ProjectSettings.get_setting("rendering/quality/driver/driver_name")
    }
}
```
The config file:
```
[rendering/quality]

driver/driver_name="GLES2"
```

**Comment by LinuxUserGD** [comment]
Doesn't work on HTML5. It would work if the config file was loaded  from user:// (enable cookies in browser).

**Comment by HugeGameArtGD** [comment]
With https://github.com/Calinou/godot-settings-manager-demo I can switch between GLES2 and GLES3 on Linux, Windows and macOS. On Android it doesn't work (I enabled Write External Storage and Read External Storage in the project settings). On HTML5 last launch and player name works but the switch between GLES2 and GLES3 works. Thanks @Calinou for the nice demo.

**Comment by boruok** [comment]
still doesn't work with android? i've tried to test GLES3 for android with fallback to GLES2 right now, its stucks on Godot logo.

**Comment by Calinou** [comment]
> still doesn't work with android? i've tried to test GLES3 for android with fallback to GLES2 right now, its stucks on Godot logo.

Please create a new issue with a minimal reproduction attached.

**Comment by Calinou** [comment]
> still doesn't work with android? i've tried to test GLES3 for android with fallback to GLES2 right now, its stucks on Godot logo.

If the engine manages to *initialize* GLES3, it won't fall back to GLES2. We need to implement https://github.com/godotengine/godot-proposals/issues/1609 to fix that.
