### ISSUE TITLE
Middle-click autoscrolling for texteditor

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot#27498]
Just that: the middle-click autoscrolling feature that you commonly see in web browsers.

A scrolling icon appears where you start the click, and the scrolling speed is proportional to the distance between the mouse's current position and the icon. Releasing the middle mouse button stops the scrolling.

Useful for browsing long text files, and for scrolling horizontally without having to look for the horizontal scrollbar.

**Comment by Larpon** [comment]
This will probably collide with #3030 on Linux.

**Comment by Paulb23** [comment]
Closing, as now tracked in the Godot proposals repository: godotengine/godot-proposals/issues/1046
