### ISSUE TITLE
Godot can't find node even though the path exists

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot#27507]
**Godot version:**

v3.1 stable

**OS/device including version:**

Windows 7

**Issue description:**

I am trying to access a node from its path. I have recheked in the remote debugger that the path is valid. Though Godot is giving Node Not Found error everytime I run the game.
Project specific:
Problem occurs in Bullet.gd $"root/Main/Player"
![image](https://user-images.githubusercontent.com/47214394/55224065-a4044b80-5235-11e9-9d04-5bd521e06fca.png)
As you can see the area2d bullet is in the same scene as player. But its giving error when I try to access it.
I have tried everything and I genuinly think that its  an engine problem.
**Steps to reproduce:**
1.Download file
2.Hit play
3. Press mouse(to fire bullets)

**Minimal reproduction project:**

[Dungeon.zip](https://github.com/godotengine/godot/files/3022009/Dungeon.zip)

**Comment by Zireael07** [comment]
I believe you're missing a / in front of "root", otherwise Godot thinks you're looking for "root", then "Main", then "Player" located BELOW the current node in hierarchy (which is obviously not the case)

**Comment by nikhilCad** [comment]
JUST figured it out myself
