### ISSUE TITLE
problem for  module compile c++, module name RSA, please help.

### ISSUE THREAD

**Issue by IuryBorges1993** [godotengine/godot#27503]
Undefined error reference to `__gmpz_mul 'and among other errors of the same category
[rsa.zip](https://github.com/godotengine/godot/files/3020705/rsa.zip)

**Comment by IuryBorges1993** [comment]
![Captura de tela de 2019-03-28 22-20-33](https://user-images.githubusercontent.com/39449626/55202808-ba63c600-51a7-11e9-870f-6b7de71a709c.png)

**Comment by nazgulsenpai** [comment]
You've provided no details on your environment, what it is that you're compiling, the steps you've taken, etc. It's helpful to use the template that's pre-populated in the New Issue box.

**Comment by IuryBorges1993** [comment]
What kinds of details?

**Comment by IuryBorges1993** [comment]
How do I solve this?

**Comment by Calinou** [comment]
The issue tracker isn't meant to be used for support questions. Please ask on [other community channels](https://godotengine.org/community) instead.
