### ISSUE TITLE
Camera: set_fov(), set_size(), set_zfar() and set_znear() methods missing

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#2750]
According to user question here : https://www.facebook.com/groups/godotengine/permalink/688262081310389/

**Comment by slapin** [comment]
You can use set_perspective()/set_orthogonal() and size is not camera parameter, but viewport parameter (see set_rect() there)

**Comment by mohaalak** [comment]
and you can always set the properties using `set(property_name,value)` like `.set('sizey',2)`

**Comment by bojidar-bg** [comment]
What's the current status of this issue?

**Comment by Chaosus** [comment]
@akien-mga Its fixed and should be closed

**Comment by akien-mga** [comment]
Indeed, fixed by d9cb00151b.

**Comment by aaronfranke** [comment]
For further discussion, see https://github.com/godotengine/godot/issues/16863#issuecomment-412810788
