### ISSUE TITLE
Cannot re-bind signals to the same function

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#27518]
**Godot version:**

3.1 Mono

**OS/device including version:**

win10

**Issue description:**

I am unable to rebind the same function to a given signal, even with different parameters. 

Example:

```
[connection signal="Died" from="LifeManager" to="." method="ExplodeParticles" binds= [ "SmallFlames.tscn" ]]
[connection signal="Died" from="LifeManager" to="." method="ExplodeParticles" binds= [ "LargeFlames.tscn" ]]
```

Instead you must create a new function each time

```
[connection signal="Died" from="LifeManager" to="." method="ExplodeParticlesLarge"]
[connection signal="Died" from="LifeManager" to="." method="ExplodeParticlesSmall"]
```

Not sure if this is a bug or an enhancement

Edit: I also cannot unbind signals in children. Doing so in the editor does not change the behavior or the tscn file. This should warrant its own issue but I thought was worth mentioning here.

**Comment by akien-mga** [comment]
As far as I know you can only bind a signal to one single function. Does this even work?
```
[connection signal="Died" from="LifeManager" to="." method="ExplodeParticlesLarge"]
[connection signal="Died" from="LifeManager" to="." method="ExplodeParticlesSmall"]
```

**Comment by JarLowrey** [comment]
Yeah that works. The way I understand the observer pattern is that binded functions are added to a queue, when the signal is emitted everything in the queue is popped and processed. So length>1 queues are definitely possible, and it works in my game. Just not adding rebinding with different parameters or editing inherited signals from a child.

**Comment by KoBeWi** [comment]
This is not a bug, binds aren't part of connection identifier. [Open a proposal](https://github.com/godotengine/godot-proposals) if you want this changed.

tbh I wanted to open one a couple of times because I had the same problem, but it's very corner-case and can be worked around by adding a proper method (which usually results in a "better" code actually).
