### ISSUE TITLE
Editor Project and Scene menu ordering

### ISSUE THREAD

**Issue by not-surt** [godotengine/godot#27519]
This is quite trivial and pedantic of me but shouldn't the Project menu most naturally precede the Scene menu in the editor menubar?

The Quit menu item is under the Scene menu, I presume just because it is the first menu in the menubar which is where a user expects to find the quit option.
But quitting is closing the open project, nothing to do with scenes, so I would think the Quit menu item belongs more naturally in the Project menu along with the related Quit to Project List menu item.

Projects are the top-level document, with scenes being subordinate components of a project.
So placing Project menu first seems most natural to me.

**Comment by bisbas** [comment]
I managed to place Popup menu first and also move Quit option from Scene menu to Project.

![project](https://user-images.githubusercontent.com/15256083/55269511-ef057980-529c-11e9-8a86-3546662d7245.png)
![scene](https://user-images.githubusercontent.com/15256083/55269512-ef9e1000-529c-11e9-922a-ff6d7fed638e.png)

**Comment by dreamsComeTrue** [comment]
Is that still relevant? Placement of menu items is a matter of taste - too many people are used to current layout - so why fix it if ain't broken? ;)

**Comment by akien-mga** [comment]
Indeed, at this point I don't think this is going to happen. If there's a strong interest in this nevertheless, please open a proposal on https://github.com/godotengine/godot-proposals/
