### ISSUE TITLE
Navigation Mesh weird behavior; Finds path to only certain points on the map.

### ISSUE THREAD

**Issue by Dragometh** [godotengine/godot#27512]
**Godot version:**
3.1.stable.mono.official

**OS/device including version:**
Windows 10.

**Expected Behavior**: The player to be able to walk to any point in the navmesh.

**Issue**: The player is only able to climb the ramp or get close to the boxes; Also, the player can only move to immediate surrounding regions.

GIF: https://imgur.com/a/kZJTlKS

**Steps to reproduce:**
Left click anywhere to move. See that you can't move anywhere, other than the ramp and the cubes.
Left click on player; The player will do a small step depending on where it is clicked. This is not intended.

**Minimal reproduction project:**
https://drive.google.com/open?id=1bnH84uPaNOCkRrRgWuXnmxsh86FJYOic

**Comment by Zireael07** [comment]
Is this a single NavMeshInstance, or are you trying to use several?

**Comment by Dragometh** [comment]
It is a single one, yeah.

![image](https://user-images.githubusercontent.com/27467821/55273831-414f9600-52af-11e9-8ce8-641a1a706f58.png)

**Comment by Dragometh** [comment]
It was just a static body missing. I'm feeling pretty dumb.
