### ISSUE TITLE
glTF importer: "root scale" parameter appears to be ignored

### ISSUE THREAD

**Issue by swetland** [godotengine/godot#27520]
**Godot version:** 3.1

**OS/device including version:** Linux, Ubuntu 18.04.2 LTS

**Issue description:** I have 3rd party assets which need to be scaled up.  Rather than manually adjusting them all post-import, the glTF "root scale" parameter seemed like a good fix (since they all need to be scaled uniformly by the same amount).  Unfortunately this parameter appears to have no affect, even after clicking "reimport", or exiting Godot, deleting the .import cache, restarting, etc.

**Steps to reproduce:**
1. Add a gltf asset
2. Select a scale factor (2 perhaps)
3. Reimport
4. Drag it into the scene
5. Note that it is not scaled.

**Minimal reproduction project:**  Here's a gltf of a simple 2x2x2 cube from blender.  I see the same issue with this as with more complex gltf assets.

[blender-2x2x2-cube.zip](https://github.com/godotengine/godot/files/3024794/blender-2x2x2-cube.zip)

**Comment by swetland** [comment]
Looks like things do work if I drag the asset into the Scene's tree view pane instead of directly into the scene itself.  Not sure if that's a known limitation?

**Comment by fire** [comment]
![editor_screenshot_2020-01-09T121921-0800](https://user-images.githubusercontent.com/32321/72101767-57789100-32da-11ea-8265-e2d212f41e45.png)

I had to click reimport and then open the scene again.

Godot Engine doesn't seem to refresh the existing scene. Dragging the scene from the filesystem doesn't work either. However, that's another bug.

Scaling the scene via import settings does work.

**Comment by fire** [comment]
See https://github.com/godotengine/godot/issues/27409 for the other bug.
