### ISSUE TITLE
Make arrays of custom types exportable

### ISSUE THREAD

**Issue by sudoman281** [godotengine/godot#27521]
**Godot version:**
3.1

**OS/device including version:**
Arch Linux - newest versions

**Issue description:**
I would like to export an array of some objects I've defined. That's not possible at the moment.

**Comment by akien-mga** [comment]
Please give more details, it's difficult to know what you're referring to in this issue and whether you're aware of the existing feature you're asking for: http://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#exporting-arrays

**Comment by sudoman281** [comment]
I mean, if I create some class, I should be able to export an array of that type. For example, if I create a class named Car, then I should be able to export an array of type Car and then I should be able to edit its public properties in the inspector.

**Comment by akien-mga** [comment]
This would require to be able to export custom classes in the first place, before considering to support them in Arrays. As such I'll close it as duplicate of #3597.
