### ISSUE TITLE
Some of the assets in AssetLib have bad hash, unable to install and bring up error

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#27524]
**Godot version:**
3.1 stable and beyond

**OS/device including version:**
Win10

**Issue description:**

![image](https://user-images.githubusercontent.com/3036176/55273618-da49d580-52de-11e9-8618-bcad9be248e7.png)

**Comment by akien-mga** [comment]
That should be reported on https://github.com/godotengine/godot-assetlib, it's not an engine issue.

**Comment by akien-mga** [comment]
Anyway, I fixed it.

**Comment by Son-Goku89** [comment]
> Anyway, I fixed it.

How?
