### ISSUE TITLE
FileSystem - Folder expands after project save

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#27525]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 7x64

**Steps to reproduce:**
1. Expand folder in FileSystem,
2. Select some file in this folder,
3. Collapse folder,
4. Press Ctrl+S

Result: folder is expanded again
Expected: folder is not expanded, cause it was collapsed 

![bug](https://user-images.githubusercontent.com/1552169/55275175-5a7a3600-52f3-11e9-9faa-2026ab258c5b.gif)

**Comment by Calinou** [comment]
I can confirm this on commit 7ca9863079c2c033e5dd550e0ab989c8593352cc.

**Comment by Xrayez** [comment]
Still relevant on 4ee8ecd.

Perhaps `ensure_cursor_is_visible` keeps expanding items used by a `Tree` (if ever used).
