### ISSUE TITLE
Cannot preload built-in gdscript scripts

### ISSUE THREAD

**Issue by cornytrace** [godotengine/godot#27535]
**Godot version:**
3.1

**OS/device including version:**

N/A

**Issue description:**

Instead of having a seperate GameObject.tscn and GameObject.gd, I use the built-in scripts option on the root node of the scene, so GameObject.gd becomes GameObject.tscn::1. I find this to be cleaner. This has worked for most things. However, when you try to preload the script in another script to reference it, you get the error 
`Can't preload resource at path: res://GameObject.tscn::1`

**Steps to reproduce:**
(in SomeRandomScript.gd)
`const GameObject = preload("res://GameObject.tscn::1")`
This fails, and the aforementioned error is thrown.
This is inconsistent with other functionality, as this resource path is the path the script editor uses to edit the built-in script.
If this is intentional, please mention so, as I will change this into a feature request.

**Minimal reproduction project:**

**Comment by girng** [comment]
gdscript preloading is transcending into levels that should not be possible

**Comment by vnen** [comment]
There's no way to load a built-in script without loading the scene that contains it, so this kind of notation doesn't really make sense.

**Comment by Zylann** [comment]
You have to preload the scene anyways, because even if `preload("res://GameObject.tscn::1")` worked, the engine would still need to parse the scene to get the script... effectively doing the same as preloading the scene. If you want to preload the script without the scene, you *have* to make them separate files.
