### ISSUE TITLE
Mesh intermittently deforms in a random manner

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#27530]
**Godot version:**
`master` / 5b00cd89

**OS/device including version:**
Manjaro Linux 18.0.4 / Nvidia GTX970

**Issue description:**
I know that the title is rather vague and it would be difficult to track down the cause, having just that much information. But I'm hard-pressed to find a better way to describe the symptom, as it's truly random and intermittent.

About 60% of the times that I run my project, I get something like these randomly:
![화면 저장_20190330_163531](https://user-images.githubusercontent.com/2367032/55277691-36941000-5346-11e9-85f4-69e80422b76d.png)
![화면 저장_20190330_152629](https://user-images.githubusercontent.com/2367032/55277695-3f84e180-5346-11e9-81ff-6cb1bda1618f.png)
![화면 저장_20190330_153354](https://user-images.githubusercontent.com/2367032/55277702-50cdee00-5346-11e9-983c-9335226bc344.png)
![image](https://user-images.githubusercontent.com/2367032/55277836-c090a880-5347-11e9-879d-e226e29e36a0.png)
![image](https://user-images.githubusercontent.com/2367032/55277843-d3a37880-5347-11e9-9bdf-b17902fcc74e.png)

I'm actually saving those screenshots for the time I'll make my own blog to show them up, so I'm not that depressed about the problem.

But still, I think this issue could affect other users as well, and it's a bit annoying when I have to run it multiple times before I can actually test the game.

I think the problem began to show up a week or two ago. It seems that the problem only occurs with a mesh which has blend shapes I animate from code (this time I checked `Local to Scene` on the mesh resource).

And sometimes something similar happens even in the editor. It doesn't look as interesting as it is in the case with the runtime, but sometimes I can't see the head mesh in the editor and it shows up again when I close the scene and reopen it.

**Comment by QbieShay** [comment]
@mysticfall two questions, please backup before you try this:
1. Does it happen if you make the mesh unique?
2. Does it happen if, in the _ready() function, you do something like `mesh = mesh.duplicate()` ?

**Comment by mysticfall** [comment]
@QbieShay Sorry for the late response. I believe 1 is to be the case, since I have blend shapes on most of the deformed meshes involved, so I made it sure _"Local on Scene"_ property was set to `true` for them.

It's a bit difficult to confirm 2, since it's already reproducible even without intentionally duplicating the mesh, and if I do so it'd not be easy to tell if it makes any difference since the symptom is quite erratic now.

I think the frequency of the problem has somehow diminished recently, but I still get it from time to time. Sometimes, everything works fine for a day but other times, I can reproduce it 3 times in a row, and so on.

I'll try to add more information as to possible conditions that seem to affect the symptom as I find them.

**Comment by Calinou** [comment]
@mysticfall Can you still reproduce this in Godot 3.2.1 or the `master` branch?

**Comment by akien-mga** [comment]
No answer, so closing.

If you can still reproduce it, please comment and ensure that a minimal reproduction project is available.
