### ISSUE TITLE
Experimenting with gravity and moving platforms, head gets stuck

### ISSUE THREAD

**Issue by ignusfast** [godotengine/godot#27537]
**Godot version:**
3.1 Stable Windows Mono

**OS/device including version:**
Windows 10

**Issue description:**
Using MoveAndSlide, I had to set the collision Safe Margin down to .05 to avoid sliding on moving platforms.  But that introduced an issue where I couldn't jump off platforms moving against gravity.  I added code that, during the first physics frame after jumping or flipping gravity, I just do a move without detection.  At all other times, I do a normal MoveAndSlide.  The issue is that when I reverse gravity, and I was floored to an object that is moving torward me, my now head gets stuck in the platform until it reverses direction.

I don't EVER want my head to do Floor detection, so I'm not sure why I'm getting stuck.

**Steps to reproduce:**
Add KinematicBody2D platforms moving up and down with a normal AnimationPlayer.  Add a KinematicBody2D player.  During initial frame after gravity change/jump, set Position instead of MoveAndSlide.  Jumping works, but gravity change gets head stuck.

**Minimal reproduction project:**
[Platform Game.zip](https://github.com/godotengine/godot/files/3025791/Platform.Game.zip)
This is my first day of playing with this, so please be kind.  I made the Sprite, but the background is placeholder from an online tutorial.

*Bugsquad edit:* MRP with gdscript: [Platform.Game.zip](https://github.com/godotengine/godot/files/6766540/Platform.Game.zip)

**Comment by girng** [comment]
did you try the community channels too? there are some intricacies to get collision stuff working smooth as butter with godot. if you did, ignore this post

**Comment by ignusfast** [comment]
Sorry, I did not - this is literally my first day of playing with it.  I did check the Godot online manuals, and did a lot of Googling, but I haven't seen anyone else really playing with gravity switching.

**Comment by ignusfast** [comment]
Talking to myself here - I did change the yChange variable over to an int, and I set it to the number of frames for which I want to just update the Position, instead of running a full physics MoveAndSlide.  It's a jury-rig I can live with for now, though I hope that the physics engine can be tweaked to better handle situations like this.

**Comment by jitspoe** [comment]
I believe this is caused by this issue here: https://github.com/godotengine/godot/issues/30481

I'm also having issues using move_and_collide() trying to collide with a moving platform.  Fundamentally, the problem seems to be that the actual body positions don't update until the end of the frame, so the platform can move, push the player up, but the player won't collide with it, because it's trying to collide with the OLD platform position, which is too far below the character to touch.
