### ISSUE TITLE
Editor in fullscreen doesn't match the mouse position

### ISSUE THREAD

**Issue by JCAPER** [godotengine/godot#27539]
**Godot version:**
Godot 3.1

**OS/device including version:**
Mac OS Mojave

**Issue description:**
When you maximize the window, the editor doesn't use the whole screen (there's a black bar at the top). Also the mouse position does not match with what the editor thinks where the mouse is. I recorded a video showing what happens.
[Screen Recording 2019-03-30 at 19.04.18.zip](https://github.com/godotengine/godot/files/3025848/Screen.Recording.2019-03-30.at.19.04.18.zip)

**Steps to reproduce:**
Open any project, maximize editor window

**Comment by WolfgangSenff** [comment]
I've had issues with this primarily when switching the editor from the main screen to an external monitor (similar to https://github.com/godotengine/godot/issues/5688). That said, I also am not reproducing exactly this on 3.1.1.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
