### ISSUE TITLE
Scale Viewport Container distorts the aspect ratio

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27534]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K
![](https://cdn.discordapp.com/attachments/477544613511692358/561593669954568212/unknown.png)

**Issue description:**
I created this structure to get 2 cameras shown in the same viewport. It works. But when I try to resize the ViewportContainer1, the aspect ratio is distorted.:

**Minimal reproduction project:**
[teste.zip](https://github.com/godotengine/godot/files/3025741/teste.zip)

**Comment by clayjohn** [comment]
Have you tried different stretch aspect settings? http://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html#stretch-aspect

**Comment by rogeriodec** [comment]
> Have you tried different stretch aspect settings? http://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html#stretch-aspect

Yes, it doesn't change anything.

**Comment by rogeriodec** [comment]
I realized that this problem only happens when you use the `Scale `button.
When using the `Select Mode` button, it shows some guides and the aspect ratio is not distorted:

![image](https://user-images.githubusercontent.com/11199752/55281736-d8503880-5317-11e9-9a3a-c15ea564ec5a.png)

**Comment by bojidar-bg** [comment]
Is this actually a bug? I would expect that scaling a Viewport container would mess up the resolution and aspect ratio, unlike proper resizing of the Control node.

**Comment by Calinou** [comment]
I think this is expected behavior. We could make it clearer in the documentation, although this kind of distortion will apply to any 2D node so it's not specific to ViewportContainer.
