### ISSUE TITLE
Add a method to retrieve the current window title

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#27536]
While we already have `OS.set_window_title()`, there's currently no way to get the window title (for example, using `OS.get_window_title()`). Once this is done, we could also expose a property of the form `OS.window_title`.

**Comment by Puthranps** [comment]
May I be assigned this issue?

**Comment by Calinou** [comment]
@Puthranps I can't assign people who aren't part of the organization, but it seems nobody has started working on it so far, so go ahead :smiley:

**Comment by Calinou** [comment]
@Puthranps Have you done any progress on this feature? If you didn't find a solution, maybe someone else could give it a try.

**Comment by Calinou** [comment]
I have a WIP branch here if anyone is interested in continuing this: https://github.com/Calinou/godot/tree/add-os-get-window-title

Keep in mind the OS code has changed in the `master` branch following the [DisplayServer refactoring](https://godotengine.org/article/core-refactoring-progress-report-2), so the code will have to be redone from scratch.

**Comment by KoBeWi** [comment]
The Window class in 4.0 has a `title` property with both setter and getter, so this is resolved.

**Comment by elvisish** [comment]
Was this ever added to 3.x?

**Comment by Calinou** [comment]
> Was this ever added to 3.x?

No, you need to keep track of the current window title in a separate variable (i.e. set its value just before calling `OS.set_window_title()`.

A PR to add `get_window_title()` to `3.x` is still welcome (feel free to use https://github.com/Calinou/godot/tree/add-os-get-window-title as a base).
