### ISSUE TITLE
Create collision from a Path2D

### ISSUE THREAD

**Issue by Errvald** [godotengine/godot#2754]
Can custom paths be used to create collisions?

How would you achieve collision on an arc?

**Comment by akien-mga** [comment]
This issue tracker is more meant to receive bug reports or feature requests than general support questions. Please try one of the other channels where you would likely get more visibility:
- Forums: http://godotengine.org/projects/godot-engine/boards
- IRC: #godotengine on the Freenode network
- Facebook: https://www.facebook.com/groups/godotengine/
