### ISSUE TITLE
Change cursor to multi-selection cursor when selecting text in Console

### ISSUE THREAD

**Issue by siradam7th** [godotengine/godot#27545]
**Godot version:**
3.1

**Issue description:**
Selecting text inside the Console in the editor doesn't change the cursor from the regular pointer to a multi-selection cursor.

**Steps to reproduce:**
select the text inside the Console that is in the editor.

**Example of expected behaviour:**
![Console-selection-cursor](https://user-images.githubusercontent.com/43510188/55282333-81ac2400-5342-11e9-9f32-4310618fceb3.png)

**Comment by KoBeWi** [comment]
Console is just a RichTextLabel, so this functionality could be added to all labels (as an option).

**Comment by Calinou** [comment]
@KoBeWi Not all RichTextLabels are selectable, and it might not make sense for all selectable RichTextLabels (where you don't need to copy text often).

**Comment by KoBeWi** [comment]
That's why I said as an option. It just shouldn't be exclusive to console.

**Comment by Calinou** [comment]
@KoBeWi There's already an option to use a different cursor when hovering the RichTextLabel :slightly_smiling_face:

Let's not add more options than we actually need, otherwise the inspector would end up showing a lot of properties most people won't change.

**Comment by KoBeWi** [comment]
Ah, I didn't know that xd
This makes the issue trivial to fix.

**Comment by fire** [comment]
@KoBeWi ping

**Comment by KoBeWi** [comment]
> ping

Why tho?

**Comment by fire** [comment]
Oh, I was checking on some old issues for a friend. I thought you wanted to work on it.

**Comment by KoBeWi** [comment]
I just said that it should be easy to do and wanted to leave it for new contributors. It's not important to fix, so it can stay for a while longer.
(also, if I wanted to work on it then, it would be fixed on the same day xd)

**Comment by mahubu** [comment]
Hello, I'm new into both GitHub & Godot contributing, and I've come with a very simple solution to this bug (see below) but I'm not sure whether or not it handles every possible case.

```
Control::CursorShape RichTextLabel::get_cursor_shape(const Point2 &p_pos) const {
       if (!underline_meta)
                return CURSOR_ARROW;
       if (selection.click)
               return CURSOR_IBEAM;
      ...
      return CURSOR_ARROW;
}
````

**Comment by fire** [comment]
Can you format your changes into a pull request and then we can code review it?

**Comment by mahubu** [comment]
Done !
