### ISSUE TITLE
Drag and drop into filesystem usability

### ISSUE THREAD

**Issue by fire** [godotengine/godot#27540]
**Godot version:**
3.1 

**Issue description:**

A friend described: Drag and drop into filesystem an unsupported file format like .blend fails silently, it's better if it shows that file format is unsupported

Edited:

One of the problems with spamming unsupported file dialogs is that you want an accept all button.

**Comment by KoBeWi** [comment]
Related: #27426

Seems like either we should accept anything (linked issue) or show unsupported dialog which lets you accept files (this issue).
The former is easier to do :P

**Comment by Calinou** [comment]
I'll close this one in favor of https://github.com/godotengine/godot/issues/27426; please continue the discussion there.
