### ISSUE TITLE
Add Script dialog doesn't support paths with spaces for base script

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#27547]
**Godot version:**
Godot stable 3.1, daily builds

**OS/device including version:**
Windows 10 x64

**Issue description:**
if there are spaces in the path name when you try to extend a script the menu will not allow you to find the file being extended.
![Screenshot (1)](https://user-images.githubusercontent.com/5633261/55282666-2bb98b00-5306-11e9-9789-6a2765763b8d.png)

**Steps to reproduce:**
try to extend a script with the Inherit from path having spaces in the path name. Also why does the path have quotations around it?

**Minimal reproduction project:**
I think issue #27307 is linked to this.

**Comment by DrNochi** [comment]
I think the quotation marks are there for 2 reasons:
1. They distinguish the path from a (built-in) class name (e.g. "Node")
2. When the script is created, the `extends "res://NAME.gd"` statement also has quotations around the path
