### ISSUE TITLE
Godot Rpc Segment Fault when client leaves the server.

### ISSUE THREAD

**Issue by shmellyorc** [godotengine/godot#27558]
Godot version: 3.1 (from your website)
+ using the godot export build on your website for headless mode

OS/device including version: Ubuntu 18.10
+ just console, nothing fancy.

Issue description: when someone leaves the server using rpc, it will cause an segment fault.

Steps to reproduce: use the sample of godot rpc. Have a client join than leave the server. you'll get a segment fault.

notes: won't do this on non-export build of headless mode.

**Comment by bojidar-bg** [comment]
A backtrace (esp. one generated by GDB) would be very helpful.

**Comment by Faless** [comment]
@shmellyorc can you provide an example project?

**Comment by akien-mga** [comment]
> use the sample of godot rpc

What sample are you referring to?

**Comment by Faless** [comment]
Probably related to #33290 . Not enough info in this issue, closing.
