### ISSUE TITLE
Sprite to CollisionPolygon2D/LightOccluder2D (like MeshInstance2D)

### ISSUE THREAD

**Issue by aombk** [godotengine/godot#27550]
hello,
it would be nice if we could convert sprites to CollisionPolygon2D/ LightOccluder2D in the same way we can now convert them to MeshInstance2D.
or even with the intermediate step, sprite>MeshInstance2D>CollisionPolygon2D/LightOccluder2D
that would work as well
thanks

**Comment by girng** [comment]
@ShyRed fastest pr i've seen in terms of code, wow! <3

**Comment by aombk** [comment]
great! thanks! :)
