### ISSUE TITLE
A button inside PopupPanel always gets stretched to fill the whole panel

### ISSUE THREAD

**Issue by fractilegames** [godotengine/godot#27555]
**Godot version:** 3.1
**OS/device including version:** Xubuntu 18.10 x86_64
**Issue description:**
A button inside PopupPanel always gets stretched to fill the whole panel. PopupDialog works as expected.

**Steps to reproduce:**
- Create a new project.
- Add a PopupPanel node and a single Button node as its child.
- Manually position and resize the button.
- Call panel's .popup() in root node's _ready() function.
- Play the project.

**Comment by akien-mga** [comment]
CC @groud

**Comment by KoBeWi** [comment]
Still valid in 6a683f8

**Comment by kleonc** [comment]
It seems like that's intended behavior, it fits in the children into the panel intentionally:
https://github.com/godotengine/godot/blob/8a21f7231f0851aec4c06abee28a549b1f8083fd/scene/gui/popup.cpp#L220-L244
([similar for `3.x`](https://github.com/godotengine/godot/blob/53843de558cb55c832d4e0b0fda908505f520c95/scene/gui/popup.cpp#L266-L285))

So `PopupPanel` seems to work like `PanelContainer`, not like `Panel`. I guess that's not a bug, just a matter of documenting it properly.
