### ISSUE TITLE
Laptop crashes and restarts on 2 occasions

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#27551]
**Godot version:**
3.1, 3.1 RC1, 3.0.6

**OS/device including version:**
Windows 10 Pro 64-bit

**Issue description:**
My friend's custom-built laptop gets black screen and restarts when using the engine. So far it happens on these 2 occasions:

1. Importing assets on new project (happened in 3.1 and 3.1 RC1; happened several times)
2. Inside Project Manager window after 2 minutes of inactivity (happened in 3.0.6)

Sadly I can't provide much info because it's not my laptop, and because my friend isn't willing to risk making her laptop crash anymore, so we're pretty limited here. Here's info I managed to get so far:

This is the crash event info (for 1st occasion mentioned above):
![event](https://user-images.githubusercontent.com/26509794/55286069-0fb1fa00-5397-11e9-98b6-5c98cf23f1e7.JPG)

These are laptop's general specs:
![diag-system](https://user-images.githubusercontent.com/26509794/55286074-1ccee900-5397-11e9-833d-861ab2fd78cd.png)

and display specs:
![diag-display-1](https://user-images.githubusercontent.com/26509794/55286077-25bfba80-5397-11e9-9fad-f9661b6415b1.png)
![diag-display-2](https://user-images.githubusercontent.com/26509794/55286078-29ebd800-5397-11e9-814b-c21708cd26c1.png)

[This is the website](https://pc-konsulten.se/barbara/) where she ordered her laptop. Though the model isn't there as it was custom-built so we can't extract any more info from here.

Laptop's model/product code: P775DM2-G

**Comment by sackondeeznuts1** [comment]
You sure this happens only when using Godot? What if her laptop overheats or there are some other hardware issues like HDD damage, because the symptoms seems to be pretty unrelated to Godot itself.

**Comment by wingedadventurer** [comment]
@sackondeeznuts1 She **never** experienced her laptop getting black screen and crashing like that until she tried using Godot. First occasion crash happens within seconds of importing assets. I'm pretty convinced these are Godot related issues.

**Comment by DegradedMind** [comment]
You sure this happens only when using Godot? What if her laptop overheats or there are some other hardware issues like hard drive damage, because the symptoms seem to be pretty unrelated with Godot itself - a restart by doing nothing with Godot within a certain amount of time pretty much shows that, because no process takes place in Godot, so no errors can occur within it.

**Comment by DegradedMind** [comment]
@wingedadventurer, also the crash during importing assets happen only sometimes. Does the crash happen only under specific circumstances? Like with specific assets?

**Comment by wingedadventurer** [comment]
@DegradedMind The way she imported assets is by dragging them into project folder, and then returning to the engine. What's supposed to appear is the loading window showing the progress for importing assets, and this is where the crash happens specifically. She tried with basic png image assets only, and few of us tried to import the same assets, and the crash doesn't happen on our ends.

**Comment by DegradedMind** [comment]
@wingedadventurer, try to reproduce the crash - if the cause is not hardware-related, then there is nothing to risk and be afraid about. Just be sure nothing important is open when trying to reproduce the crash.

**Comment by DegradedMind** [comment]
@wingedadventurer, can you provide the xml view from the event log in text?

**Comment by groud** [comment]
Godot cannot cause a system crash, it does not have the capacity to do so. What likely happens is a crash in the system drivers, you should likely try to update them.

**Comment by BastiaanOlij** [comment]
I second checking the system drivers. I had weird crashes with my laptop until I updated to the latest NVidia drivers as well. Especially on laptops with dual GPUs they tend to fight with eachother.

The other thing to check is your NVidia settings themselves, make sure that it properly recognizes Godot as an app that should run on the 1070, not on the onboard intel GPU.

**Comment by eon-s** [comment]
Search for a dump file viewer or disable the restart to see some details (on the BSOD).

**Comment by wingedadventurer** [comment]
@groud @BastiaanOlij She tried updating her drivers and she tried forcing external GPU last time and didn't help. She isn't really eager to have her laptop crash again (regardless if it's actually harmful or not) so further testing and debugging aren't really an option anymore.

I'll close the issue, thanks for the help so far.
