### ISSUE TITLE
Multimesh Bug in GLES3 [Windows]

### ISSUE THREAD

**Issue by Nophlock** [godotengine/godot#27568]
**Godot version:**
Godot 3.1.0-Stable

**OS/device including version:**
Windows 10
Radeon RX 570 (19.3.2)

**Issue description:**
I found this problem while programming on my game. I wanted to use multiple Multimesh nodes and shortly after that I wondered why it wasn't properly working (only one of the Multimesh-Nodes was visible and sometimes it completely bugged out). After I've reduced the Multimesh nodes to one in the entire project it suddenly worked, without touching any GDScript-Code. I only removed the other Multimesh nodes which shared the same script. So after some investigation I found out that this problem doesn't occur in the GLES2 renderer. So my assumption is that in GLES3 the code (or shader?) interferes with each other which can causes wrong rendering or other glitches. Anyway I provided a simple sample project which hopefully makes it more clear what I mean. In the sample project I just randomly show multiple instances of the assigned shapes and sometimes by doing so it glitches out by showing the shapes at the wrong position or other weird stuff. 

![image](https://user-images.githubusercontent.com/8605748/55296115-97d6e480-5415-11e9-9e86-98e2a124c16a.png)

Here you can see that the Prism overlaps with the Cubes which shouldn't be the case (I only change the Y-Axis in the generation so this shouldn't happen)

![image](https://user-images.githubusercontent.com/8605748/55296204-76c2c380-5416-11e9-9048-631c4bef86df.png)

Sometimes it also shows black lines instead of anything(Maybe the scaling of the Matrix bugs out in the Shader of the Multimesh?)

**Steps to reproduce:**
I think the easiest way is to just open the sample project I've provided

**Minimal reproduction project:**
[MultiMeshBug.zip](https://github.com/godotengine/godot/files/3027224/MultiMeshBug.zip)

**Comment by clayjohn** [comment]
I am not able to reproduce the described issue. Is there anything you do in addition to running the sample project to spot the issue? I ran it a bunch of time, both in GLES2 and GLES3 and I couldn't reproduce the bug. 

Linux 16.04 intel integrated graphics v3.1

**Comment by Nophlock** [comment]
@clayjohn, nothing special just running the project. Maybe this is driver related and not Godot related? I will boot up a Linux tomorrow and see if it happens there aswell

**Comment by Megalomaniak** [comment]
RX 470, Win 7 64 bit.

I see it cycle through multiple different MultiMesh generations One of which looks like your first image, did not see anything like your second image though.

**Comment by Nophlock** [comment]
Alright I gave it a go on my installed Linux as well (Fedora) and it didn't bugged out there. So I guess this is only Windows related?

@Megalomaniak 
To be fair, the black thing on the second image is pretty hard to spot since it only appears for a few ms  on my machine. I actually had to record the game window and stop it in the right position to make a screenshot of it ^^

**Comment by Zylann** [comment]
The project gave a few random layouts of items for a few seconds, and then the game crashed with no info but a typical `ERROR: _get_socket_error: Socket error: 10054`.

Windows 10 64 bits, GeForce GTX 750 Ti/PCIe/SSE2

**Comment by Megalomaniak** [comment]
@Zylann And with GLES 2 everything is fine for you too?

@Nophlock Right, I only ran it for a short period too.

**Comment by Zylann** [comment]
@Megalomaniak GLES2 behaves the same but doesn't crashes.

**Comment by Megalomaniak** [comment]
@Zylann So visually you see the following with GLES2 as well as 3 using the GeForce GTX 750Ti:

> ![image](https://user-images.githubusercontent.com/8605748/55296115-97d6e480-5415-11e9-9e86-98e2a124c16a.png)

?

**Comment by Zylann** [comment]
@Megalomaniak I see the same shapes yes.

**Comment by Megalomaniak** [comment]
OK, so there is a difference between nVidia and AMD GPUs then.

**Comment by clayjohn** [comment]
@Megalomaniak it seems that windows vs linux is also an important factor.

**Comment by Zylann** [comment]
Same behavior on another Windows computer on GLES3 with an nVidia GeForce GTX 1060 6GB/PCIe/SSE2: random shapes, some unexpected, then crash.

**Comment by MadEqua** [comment]
The example project also crashes on my Windows machine. It's a driver crash when calling `glBindBuffer(GL_ARRAY_BUFFER, <invalid buffer id>)`.

I went looking around and found this:
https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_storage_gles3.cpp#L4454-L4457

Adding `multimesh->buffer = 0;` to reset the buffer id when deleting the buffer fixes the crash. Even though I didn't dig deep enough to find out exactly why, it makes sense and I'll submit a PR for others to test.
