### ISSUE TITLE
Scrolling Control nodes don't display correctly when under a Render Target viewport

### ISSUE THREAD

**Issue by SolarMongoose** [godotengine/godot#2757]
I'm still using 1.1 but I tested this in a recent release of 2.0 and it was still an issue.

When using a Render Target viewport (such as when using `stretch_mode`, `viewport`) I've found that ScrollContainer nodes and RichTextLabel nodes have some offset not behaving or something. (There might be other types that have this issue, these are the ones I've found). I'll try to illustrate...

I put a few Control nodes under a Render Target viewport and few above it and this is what it SHOULD look like
![howitshouldlook](https://cloud.githubusercontent.com/assets/15483613/11039252/5302dbee-86cc-11e5-804b-e88e515e5411.png)

However this is what it does instead
![output](https://cloud.githubusercontent.com/assets/15483613/11039034/729ed33c-86cb-11e5-9d0d-427f6353399f.png)

The white/black squares are texture frames and are working correctly. The white ones are children of the Render Target viewport and the black ones are not but they just show that they line up as intended.

The red box, the green box with the gradient, and the second (not visible) RichTextLabel are all children of a Render Target viewport, the  blue box, the first box with the image of the gradient, and the first RichTextLabel are not. In fact, here's what the scene looks like...
![scene](https://cloud.githubusercontent.com/assets/15483613/11039466/6f5768fe-86cd-11e5-97a7-f00e67a43990.png)

I actually just used a big `draw_rect` to locate the wandering nodes. At first it appeared as though the nodes just weren't showing up at all.

Also worth mentioning that I forgot to show is that the boxes move when the window is resized. If the window is resized just a little they'll move down a little more. They move out of the window entirely before it's even twice as tall. And it's just like... the clipping rectangle that moves. For example, in the green box with the gradient image, the image and scroll bar will stay where they are, the visible area will just move so that it shows less and less of them.

**Comment by reduz** [comment]
i *think* this is fixed in head, could you verify?

**Comment by SolarMongoose** [comment]
http://www.godotengine.org/topics/13225

Well it took 3 people and almost a week, but we believe this issue is (and already was) resolved by #2572
