### ISSUE TITLE
Godot editor crashes when minimize the window. (Linux)

### ISSUE THREAD

**Issue by Prunkles** [godotengine/godot#27578]
**Godot version:**

v3.1-stable-mono_x11_64

**OS/device including version:**

OS: Linux Mint x64 / XFCE4 (and Cinnamon detected too)
GPU: NVidia Quadro NVS 135M

**Issue description:**

When switching workspaces, with a small probability, the editor crashes, when you return to the workspace with it.

**Steps to reproduce:**

The bug is considered as a floating.

1. Run Godot. Project Manager or a Project.
2. Start switching workspaces (Ctrl+Alt+Right/Left for me) until you find that Godot has closed.

**Minimal reproduction project:**

Any project.

**Stacktrace:**

[stacktrace.txt](https://github.com/godotengine/godot/files/3030844/stacktrace.txt)

**Comment by Prunkles** [comment]
Okay, I've found that the crash can also happen when I just minimize the editor window (which happens when I switch the workspace)
Stacktrace in this case: 
[stacktrace.txt](https://github.com/godotengine/godot/files/3031039/stacktrace.txt)

**Comment by pouleyKetchoupp** [comment]
I'm not able to reproduce this issue on Ubuntu 20.04.1 with Gnome or XFCE.

Can anyone still reproduce it in Godot 3.2.3 or any later release?

**Comment by akien-mga** [comment]
No answer, so closing.
