### ISSUE TITLE
Code editor must-have features

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#27579]
For some reason there's lack of must-have features all IDEs have. Here's the list of what I miss so much. I hope this one will be added to the tracker #2982. Let me know if you need a visual example of how this should work, I'll try to make a screencast from other IDEs
* fuzzy search
search files, classes, lines, commands, etc
* code snippets
* refactoring tools (e.g. rename/extract method/variable)
* navigation / go to definition
when `Ctrl + Click` on function (including user-defined) - go to that function (from ANY place, not just within the same script)
`Alt + Left` / `Alt+ Right` - navigate through *places* instead of just files
* hierarchy
hierarchy of classes, list of all function in the class (already there and that's great!), call hierarchy
* find all usages
* quick docs (on hover / hotkey)
* code completion
Sadly, current code completion is still weak in comparison with other products, but I think we need a bunch of examples how it should work or what does not work. Including intellisense
* auto-format code

**Comment by Ace-Dragon** [comment]
On code completion, the ability for this feature to work improves if you use the optional static typing (as the weaknesses in this otherwise is due to the very nature of a dynamically typed language).

As for the others, some useful ideas there, fortunately we have a history of devs. interested in providing patches.

**Comment by KoBeWi** [comment]
As for code completion, VS Code does this in an interesting way. It can auto-complete even .txt files, just by suggesting different words you used in the file in case you need one. And it actually helps.

**Comment by Calinou** [comment]
Please open one issue per bug/feature request, it's very difficult to keep track of what has been implemented otherwise. Make sure to search for potential duplicates too; many of the feature requests you mentioned already have their own issues in this repository.

**Comment by smedelyan** [comment]
@Ace-Dragon yeah, I use typing a lot and IMO code completion is still weak (compare with JetBrains IDEs - they have the most awesome completion I've ever seen)
@KoBeWi and that results in unnecessary garbage in suggestion list. More stuff is as bad as less stuff =)
@Calinou thanks, you're right, I'll open new issues later
