### ISSUE TITLE
Error when trying to drag visibility button too close to the edge

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#27580]
**Godot version:**
3.2 9c3ddf0

**OS/device including version:**
Linux Mint 19

**Issue description:**
When I drag visibility button in scene tree, too close to the edge then this error is shown:
```
ERROR: _cell_button_pressed: Condition ' !item ' is true.
   At: editor/scene_tree_editor.cpp:52.
```

**Steps to reproduce:**
https://streamable.com/4zaxv

**Comment by qarmin** [comment]
Strange and still reproducible with master 
![jfile](https://user-images.githubusercontent.com/41945903/66934122-4b15cc80-f03a-11e9-8bad-a417db7063cc.gif)

**Comment by akien-mga** [comment]
Confirmed in the current master branch.
