### ISSUE TITLE
Text fields in the GUI are hard to select and edit

### ISSUE THREAD

**Issue by mrbig033** [godotengine/godot#27588]
**Godot version:**
- 3.1.stable.official

**OS/device including version:**
- MX-Linux 18
- Window Manager: [i3](https://i3wm.org/)
- compton 0.1~beta2+20150922
- OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)

**Issue description:**

Text fields (the ones where you enter values) are buggy, I have to
click a bunch of times for them to become editable, or even
close/reopen the pane altogether multiple times.

**Steps to reproduce:**

Try to edit the dimensions of a collision shape by entering numbers
directly in the text field (happens with any field, though).

**Minimal reproduction project:**

This is a GUI issue that happens with any project.

**Comment by akien-mga** [comment]
Can't reproduce on Mageia 7 with Plasma 5/KWin.

**Comment by Calinou** [comment]
@mrbig033 Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
