### ISSUE TITLE
Game fails to run on Android: shows Godot logo, disappears, repeats

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#27583]
**Godot version:** 3.1
**OS/device including version:** Xiaomi Redmi 4
**Issue description:** When I build/run the Android version of my game, I see the following behaviour:
- Godot splash logo appears
- Logo disappears in <= 100ms
- This cycle repeats roughly 4-5x

I tried to capture `adb catlog` to a text file. I think this is the relevant part:

```
04-01 08:04:18.672  1384  1394 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=com.deengames.controlyourtongue/org.godotengine.godot.Godot} from uid 2000 on display 0
04-01 08:06:13.069  1384  1426 E PackageInstaller: Commit of session 566684875 failed: Failed to collect certificates from /data/app/vmdl566684875.tmp/base.apk: Attempt to get length of null array
```

I tried two different keystores to be sure I have the right user/password combination.

**Comment by eon-s** [comment]
GLES version?
If you see the logo it is usually related to the renderer, other errors (key or not common characters on filename) fail on install.

**Comment by nightblade9** [comment]
I tried GLES2 and GLES3. Same behaviour. These error logs are from GLES3.

**Comment by Noisefever** [comment]
I have the same problem. Both GLES2 and GLES3 too. Working with Light2D and Shadows (which produce in another game a black screen on GLES2 btw. Maybe related?).

**Comment by nightblade9** [comment]
I downgraded my (simple) project to Godot 3.0.6 to see if that's a work-around. It's not; I didn't check the catlog, but the behaviour of the application is exactly the same.

I now suspect my application code, since I was able to make Android apps work with 3.0.6 in the past. I'll experiment more and see if I can figure this out.

Can anyone suggest a work-around?

**Comment by nightblade9** [comment]
I found a partial solution. It looks like my dummy project didn't have a `Main Scene` specified in the project settings (under `Run`). Although this allowed me to run it on Windows, it crashed on Android.

Specifying a main scene fixed the problem. This applies to both 3.0.6 and 3.1.

However, my main (broken) project already has a main scene specified; this isn't the reason it's broken.

**Comment by Noisefever** [comment]
@nightblade9 no, unfortunately not. I have a Main Scene.

**Comment by nightblade9** [comment]
I debugged further and found that my issue is that I preload the same resource twice.

- Main scene preloads `Second.tscn` and `HelperScript.gd`
- Second scene also preloads `HelperScript.gd`
- This is what caused the behaviour.

I think Godot can do the following:

- Fail when I run it on PC, the same way it fails when I run it on Android. That way, as a developer, I can be confident that my game works when it works on PC, and I can find problems sooner than later.
- Output a warning or error about this problem in the Editor. I checked; there are no warnings about this.

The two work-arounds I found:

- Make `HelperScript.gd` an autoload singleton instead
- Use `load` instead of `preload`

**Comment by Noisefever** [comment]
I solved my problem with the not starting game: it was the broken "Tiled Map Importer" addon.
However: this and the other game still showing a black screen in GLES2, when Light2D is in the scene.

**Comment by Noisefever** [comment]
GLES2 and Light2D: had to change the Environment from "Canvas" to "Custom Clear Color". Obviously there was a change that I have missed. Sorry! All functional now.

**Comment by nightblade9** [comment]
I wrote a blog post about this today, and I realized that this seems like a genuine Godot bug.  Using `preload` crashes, but using `load` doesn't.

Is this expected, or is this a real issue?

**Comment by eon-s** [comment]
Can you make a sample project to reproduce the problem consistently?

**Comment by nightblade9** [comment]
It doesn't reproduce any more - not on the original project, and not in a brand-new project.

I'm going to close this issue for now. If I can find a repro case, I will come back to this again and we can investigate more.

**Comment by duybui0187** [comment]
HI, please help. 
i made a game export apk used to be on Godot 3.1 now i upgrade to 3.3. u got the right template for both. but no mater how i try to resetting it. the game only work perfectly on my Samsung galaxy s10plus. i try it on different divide and it ran fine on the selection screen but when i click start game it load a bit then crash. i try the game on Gl 51 doesn't work, then i try on s10e and still doesn't work. my brother try on galaxy s10 also doesn't work. only work on s10 plus which is mine. thanks for the help.

**Comment by Calinou** [comment]
@duybui0187 Please use other [community channels](https://godotengine.org/community/) for support questions.
