### ISSUE TITLE
Adding type information to deferred calls can cause segfault when the argument passed is freed

### ISSUE THREAD

**Issue by austinried** [godotengine/godot#27582]
**Godot version:**
Godot 3.1 stable

**OS/device including version:**
Ubuntu 18.04
Windows 10

**Issue description:**
My game crashes with the following backtrace:
```
handle_crash: Program crashed with signal 11    
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f80223faf20] (??:0)
[2] Object::get_class_name() const (/home/me/repos/godot/./core/object.h:634)
[3] GDScriptDataType::is_type(Variant const&, bool) const (/home/me/repos/godot/modules/gdscript/gdscript_function.h:81)
[4] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/me/repos/godot/modules/gdscript/gdscript_function.cpp:331 (discriminator 1))
[5] GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/me/repos/godot/modules/gdscript/gdscript.cpp:1175)
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/me/repos/godot/core/object.cpp:921 (discriminator 1))
[7] MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) (/home/me/repos/godot/core/message_queue.cpp:256)
[8] MessageQueue::flush() (/home/me/repos/godot/core/message_queue.cpp:305)
[9] Main::iteration() (/home/me/repos/godot/main/main.cpp:1888)
[10] OS_X11::run() (/home/me/repos/godot/platform/x11/os_x11.cpp:3006)
[11] /home/me/projects/mygame/godot.x11.tools.64(main+0xdc) [0x116b8e3] (/home/me/repos/godot/platform/x11/godot_x11.cpp:56)
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f80223ddb97] (??:0)
[13] /home/me/projects/mygame/godot.x11.tools.64(_start+0x2a) [0x116b74a] (??:?)
-- END OF BACKTRACE --
```
This happens when I have a number (seems to be between 8-10) of deferred calls stacked up with a function that has type information in its signature, and the argument being passed is a node that has been freed.  The error does not occur if the function signature does not have type information.

**Steps to reproduce:**
For example, I have several `KinematicBody2D`s (item pickups) inside an `Area2D` (a chunk of the world) moving toward another `Area2D` (the player).  The world chunk `Area2D` is listening to `on_entered`/`on_exited` so that it can track which items are in the area, and the player's `Area2D` is listening to `on_entered` so that it can pick up and remove items (`queue_free()` them) when they enter.  Here are the two scripts:

**Item.gd**
```swift
extends KinematicBody2D

func _physics_process(delta):
	move_and_slide(Vector2(100, 0))

func free_me():
	queue_free()
```

**WorldChunk.gd**
```swift
extends Node2D

# this does not work, crashes with the type
func do_literally_anything(to_be_freed: PhysicsBody2D):
	return

# this works just fine, without the type
#func do_literally_anything(to_be_freed):
#	return

func _on_WorldChunk_body_exited(body):
	call_deferred("do_literally_anything", body)

func _on_Player_body_entered(body):
	body.free_me()
```

If I use the version of `do_literally_anything` above that does not have type information, the error does not occur, it is only when the signature has type information that the error occurs.

Oddly, the error also only occurs when there are between 8-10 items in the scene (on my Ubuntu laptop with integrated graphics).  At lower numbers the error seems to occur more randomly, so that specific number may be dependent on your machine and due to some kind of race condition.  On my Windows 10 desktop with dedicated graphics, for example, it takes about 54 items before the error reliably occurs.

**Minimal reproduction project:**
Attached below is a minimal repro project, please remember to adjust the number of items in the WorldChunk scene (just duplicate them/delete them) if needed.

[queue_free-crash.zip](https://github.com/godotengine/godot/files/3036035/queue_free-crash.zip)

**Comment by austinried** [comment]
Ok, I now have 100% repro on this and have updated the description/name to be more accurate and detailed.  Turned out the issue lies in the new static typing system and dealing with deferred calls on freed objects.

**Comment by austinried** [comment]
Added more info about repro on a beefier Windows 10 machine.

**Comment by austinried** [comment]
I found a new issue that I think is related to this one, except it occurs with signal callbacks instead of deferred calls: #29970

**Comment by akien-mga** [comment]
Still reproducible in the current master branch (3da2160).
```
Thread 1 "godot-git" received signal SIGSEGV, Segmentation fault.
0x0000000001503157 in Object::get_class_name (this=0x6794cc0) at ./core/object.h:647
647                             return *_get_class_namev();
(gdb) bt
#0  0x0000000001503157 in Object::get_class_name (this=0x6794cc0) at ./core/object.h:647
#1  0x0000000001504501 in GDScriptDataType::is_type (this=0x679dc60, p_variant=..., p_allow_implicit_conversion=true) at modules/gdscript/gdscript_function.h:81
#2  0x00000000015497ce in GDScriptFunction::call (this=0x6787820, p_instance=0x679ee60, p_args=0x7fffffffcd20, p_argcount=1, r_err=..., p_state=0x0) at modules/gdscript/gdscript_function.cpp:337
#3  0x00000000014fb7f0 in GDScriptInstance::call (this=0x679ee60, p_method=..., p_args=0x7fffffffcd20, p_argcount=1, r_error=...) at modules/gdscript/gdscript.cpp:1173
#4  0x000000000384f9e1 in Object::call (this=0x67d0140, p_method=..., p_args=0x7fffffffcd20, p_argcount=1, r_error=...) at core/object.cpp:900
#5  0x000000000384677d in MessageQueue::_call_function (this=0x54fffe0, p_target=0x67d0140, p_func=..., p_args=0x7fffeb62a188, p_argcount=1, p_show_error=false) at core/message_queue.cpp:250
#6  0x0000000003846a39 in MessageQueue::flush (this=0x54fffe0) at core/message_queue.cpp:297
#7  0x0000000001472a80 in Main::iteration () at main/main.cpp:2010
#8  0x0000000001442dbd in OS_X11::run (this=0x7fffffffcf70) at platform/x11/os_x11.cpp:3262
#9  0x000000000143327c in main (argc=1, argv=0x7fffffffd738) at platform/x11/godot_x11.cpp:56
```
