### ISSUE TITLE
Web export fails when running in <iframe> and third-party cookies are disabled

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#2758]
[itch.io](https://itch.io) is a website that enables developers to upload, present and sell their games. The site also allows upload of HTML5 games, which are embedded in an `iframe` on the game's page. For some more information see here: http://itch.io/docs/creators/html5.

Currently, games exported to HTML5 from Godot will not start on itch.io. The only unusual error message given by the embedded output is:

```
Assertion failed: undefined
```

Chrome's console gives this additional trace:

```
Assertion failed: undefined
    Module.printErr @ index.html:1246
Uncaught abort("Assertion failed: undefined") at Error
    at jsStackTrace (http://commondatastorage.googleapis.com/itchio/html/119893/index.js:1:20729)
    at stackTrace (http://commondatastorage.googleapis.com/itchio/html/119893/index.js:1:20912)
    at abort (http://commondatastorage.googleapis.com/itchio/html/119893/index.js:30:11012)
    at assert (http://commondatastorage.googleapis.com/itchio/html/119893/index.js:1:6960)
    at http://commondatastorage.googleapis.com/itchio/html/119893/index.js:1:27634
    at done (http://commondatastorage.googleapis.com/itchio/html/119893/index.js:1:87664)
    at http://commondatastorage.googleapis.com/itchio/html/119893/index.js:1:66679
    at http://commondatastorage.googleapis.com/itchio/html/119893/index.js:1:68182
    at IDBOpenDBRequest.IDBFS.getDB.req.onerror (http://commondatastorage.googleapis.com/itchio/html/119893/index.js:1:67461)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

This occurs with both debug and release builds.
The same exported files will work when uploaded to Google Drive.
This example uses the official nightly debug build from 2015-10-30:
http://eska.itch.io/godot-engine-test?secret=tMDcL7SiZSh0Qo98RHCk4yLnDRk

**Comment by eska014** [comment]
Looks like the same error occurs when using "Run in Browser" from within the edtior with
`chromium --disable-web-security` as browser. Firefox works.

**Comment by eska014** [comment]
Appears this is a Chromium issue only. Starting from itch.io works on Firefox Dev 44. However, as stated above, starting from Google Drive works even on Chromium.

**Comment by Wend1go** [comment]
Off Topic:
How did you manage to compile a release version of your game?
Have been asking this on the forum but without any answers:
http://godotengine.org/topics/12451

**Comment by eska014** [comment]
@Wend1go The kind of release build you're looking for is not yet possible with Godot.
Currently, overhead like console, border, logo, etc. will always be included, since the same `.html` page is used for both release and debug export (`tools/html_fs/godot.html`).

Better HTML5 release export would be great, please submit an issue about it.

Not sure about this though:

> [...] compiles it whenever I open the html file.

Emscripten compiles Godot Engine to JS when compiling the templates (`godot.js`). However, games themselves are not compiled by emscripten afaik; they're just packed to `data.pck`.
In the first place, projects are never converted to LLVM bitcode, so emscripten wouldn't know what to do with them.

**Comment by Wend1go** [comment]
Thanks for clarification, I have created a new issue #2774
----
I don't know much about emscripten. When I open the html file in the browser the text next to the emscripten logo says "Downloading" and after that "Compiling". Don't know what exactly gets compiled there.
But I can confirm that both chrome/chromium have problems running the game. Only firefox works flawlessly on my side.

**Comment by eska014** [comment]
Browsers refuse IndexedDB access in iframes when third-party cookies are disabled, causing this issue
