### ISSUE TITLE
android 8.1 with adreno 506 can run GLES3 now. whereas poor performance.

### ISSUE THREAD

**Issue by jhch3** [godotengine/godot#27599]
**Godot version:**

godot 3.1 git@472c8a7ba1c7090679b6cc2da1abf02f621848e4

**OS/device including version:**

After upgrade os to android 8.1.0
Adreno 506  OpenGL ES 3.2 V@269.0 (GIT@8e3df98, Ie4790512f3)(Date:04/11/18)

**Issue description:**

Driver set as GLES3. app can run now. but poor performance. fps < 11 when light-shadow on.fps<20 when light-shadow off.

**Steps to reproduce:**
just 1 plane,
 4 static body cube, 
4 rigid body sphere,
1 directionalLight,
1 camera.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Try setting the driver to GLES2, which runs betteron mobile devices. Also, what's your device's screen resolution? You may want to set the window size to a lower resolution (such as 1280×720), set the stretch mode to `viewport` and stretch aspect to `keep` to render at a lower resolution.

**Comment by jhch3** [comment]
you are right. still GLES3, set mode as viewport,  resolution 1024 * 600, fps upgrade to 28 when shadow on, 38 when shadow off. but screen looks glitch. rough edge. need anti-alias filter.

**Comment by Calinou** [comment]
> rough edge. need anti-alias filter.

That's mainly because the upscaling uses nearest-neighbor filtering instead of linear filtering (which is more suited to non-pixel art games). Enabling MSAA would also help, but it's likely too slow on mobile devices (except on GLES2 with very simple visuals).
