### ISSUE TITLE
typo in 3.1 release notice

### ISSUE THREAD

**Issue by Hugo0** [godotengine/godot#27600]
**Godot version:**
320f49f

**Issue description:**
Small typo in description: Should be "improvements" instead of "improvemetns"

**Comment by groud** [comment]
Which release notice ? Do you have a link ?

**Comment by Calinou** [comment]
I fixed it, see https://github.com/godotengine/godot/releases/tag/3.1-stable :smiley:

**Comment by Hugo0** [comment]
Well that was quick!
