### ISSUE TITLE
Code editor improvement: quick documentation

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#27607]
Currently, we can use Lookup Symbol or Search Help to look for documentation of everything. It would be nice to have that documentation in popup rather than a separate window / tab.
See an example: [Quick Documentation in IntelliJ IDEA](https://www.jetbrains.com/help/idea/viewing-reference-information.html#inline-quick-documentation)

**Comment by Duroxxigar** [comment]
I just want to throw my voice out there for this. I actually like the way it is currently implemented more. Perhaps a toggle?

**Comment by smedelyan** [comment]
@Duroxxigar with this implemented you will still be able to read documentation exactly in the same way as you have been reading before. This is just an additional feature. Wanna see docs of a method? Ok, `Ctrl + Q` (or whatever) and it's shown in popup. No need to look through the whole doc-page with other functions and skim it for the one you looked for (it may be in the very end so the scrolling may not be precise enough). I do believe this is much more useful as it is, so to say, right in the context where you code.

**Comment by Calinou** [comment]
I agree this is would be a pretty useful feature, as it prevents a context switch when you're just looking at the documentation of a single function. It could also be enabled when hovering functions with the mouse (with a small delay).

**Comment by Duroxxigar** [comment]
@smedelyan I wasn't voting in no of it. I just wanted to voice my opinion about the current implementation.

**Comment by smedelyan** [comment]
@Duroxxigar alright=) I do love the way Godot provides its documentation as well:) That's definitely much better than, say, Unity does

**Comment by Jummit** [comment]
Could be implemented with a custom tooltip.

**Comment by echebbi** [comment]
Is there any progress on this? I have seen several GitHub issues asking for in-code documentation in GDScript (JavaDoc / Docstrings like) and appropriate support in Godot's Script Editor but it looks like nothing has changed since.

I would love to have this feature into Godot; is there anything that can be done to push it forward?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/765, as feature proposals are now tracked in the Godot proposals repository.
