### ISSUE TITLE
WorldEnvironment Node Glow works in Editor but not when running

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#27616]
**Godot version:**
3.1 stable
But I already had this issue with 3.0.6, though I could not narrow it down to this back then.

**OS/device including version:**
Win7, dedicated NVIDIA GPU

**Issue description:**
![WEglow_why1](https://user-images.githubusercontent.com/47016402/55437363-01362f00-559f-11e9-82e0-70d698cc092f.png)
The Modulate value for the Sprite is set to 2 in raw mode for all these examples. So with an Hdr Threshhold of 1 It should be glowing. It does in the Editor, but not when I run the project.

![WEglow_why2](https://user-images.githubusercontent.com/47016402/55437395-114e0e80-559f-11e9-8b50-3b0c828dac6f.png)
Changing the Strength setting and running the project. Now it suddenly does glow, but not with the same intensity and no color shift.

![WEglow_why3](https://user-images.githubusercontent.com/47016402/55437416-2034c100-559f-11e9-9942-8b416b95a7b5.png)
Changing the Strength setting and running the project.

![WEglow_why4](https://user-images.githubusercontent.com/47016402/55437427-29259280-559f-11e9-9236-a9ea46b04aa8.png)
Changing the Hdr Threshold setting below 1 and running the project creates a glow too, but again less intense. The Sprite is still on intensity 2 in raw mode.

![WEglow_why5](https://user-images.githubusercontent.com/47016402/55437454-393d7200-559f-11e9-985c-e4ae67cc52db.png)
Changing the Threshold setting to almost 0 and running the project.

![WEglow_minimal3](https://user-images.githubusercontent.com/47016402/55437527-5eca7b80-559f-11e9-87b2-fa4f396822b9.png)
I even considered maybe my Graphics hardware to be the problem, and created another minimal testproject, but it works here. Those two Sprites have a raw intensity values of 2 just like above.

After that I tried to apply the WorldEnvironment Node once again to my actual project (not depicted) and get the exactly same buggy results as above in the "WHY" screenshots.

**Steps to reproduce:**
Run the Minimal Project

**Minimal reproduction project:**
[WorldEnvironment_fail.zip](https://github.com/godotengine/godot/files/3035979/WorldEnvironment_fail.zip)

**Comment by AsherGlick** [comment]
I downloaded this example and found that the brightness was being achieved via a white modulate value of (510,510,510). While I feel in theory this should work I am guessing that it is still undefined behavior at the moment.

I attempted to recreate this effect using a default normal-white modulate value with a custom shader that does the modulation instead
![Screenshot from 2019-04-03 02-26-46](https://user-images.githubusercontent.com/603989/55457624-76622e00-55b8-11e9-9afa-3155c5a4d801.png)
The box on the left being the original modulate modification and the one on the right being a shader. When the editor is zoom is adjusted to be the same size on screen, the shader version seems to be identical between the editor and the export.

The shader I used was
```
shader_type canvas_item;

uniform float bright_amount;

void fragment() {
	vec4 c = texture(TEXTURE, UV);
	c.rgb *= vec3(bright_amount);
	COLOR = c;
}
```

with `bright_amount` set to `2` in the UI

Given that this shader effectively just does a very simplified version of what I think modulate does, this issue may be an bug with the default shader for sprites. If not then there should likely be some kind of user warning or prompt indicating that the values chosen will result in undefined behavior.

**Comment by golddotasksquestions** [comment]
Thanks for having a look AsherGlick!
Today I tried removing all AnimationPlayers and setting the modulate value in the _ready script():
```
func _ready():
	sprite.modulate = Color(2,2,2)
```
But the result is identical with the bug above.

**Comment by golddotasksquestions** [comment]
.... this is embarrassing.
I found the source in my _physics_process()
```
	if attarea.monitoring || attarea.monitorable == true:
		sprite.modulate = Color(1,0,0)
	else:
		sprite.modulate = Color(1,1,1)
```
I'm sorry for wasting your time. At least I now know what to look out for in my actual project. Sorry again.
