### ISSUE TITLE
Search feature while assigning NodePaths

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#27612]
**Godot version:**
ANY

**OS/device including version:**
ANY

**Issue description:**
As scene grow over the life of a project being able to search for a node in the tree while trying to assign one to a NodePath or any other such functions would become a wise thing to have.

**Steps to reproduce:**
just have a large scene tree and try to find a single node

**Minimal reproduction project:**

**Comment by avencherus** [comment]
Would also be good to have some kind of drag and drop assignment, or something like copy and paste, so it can nodes can be quickly assigned without leaving the workflow.

**Comment by KoBeWi** [comment]
> Would also be good to have some kind of drag and drop assignment, so it can nodes can be quickly assigned without leaving the workflow.

Related: #2505
