### ISSUE TITLE
Add RayCast support for Area2D and Area.

### ISSUE THREAD

**Issue by VAVUS7** [godotengine/godot#27617]
As I understand it, RayShape2D is used in physical bodies to repel a point. But according to my observations in Area2D RayShape behaves like SegmentShape. I think it would be nice if Area2D would produce RayCast for each CollisionShape with RayShape. This would combine a lot of Raycasts in a single object.

**Comment by TheDuriel** [comment]
You want this:

https://docs.godotengine.org/en/3.1/classes/class_raycast2d.html

(I had a stroke reading this. But he is correct about one thing. Segment and Ray are the same in Area2D.)

**Comment by akien-mga** [comment]
I have a hard time understanding what this proposal is about too.

What is needed that RayCast2D doesn't do?

**Comment by Xrayez** [comment]
I think @VAVUS7 means implementing something aking to ShapeCast(2D): godotengine/godot-proposals#72, godotengine/godot#2217.

**Comment by Zireael07** [comment]
Most likely, but the original post is indeed poorly worded.

**Comment by mhilbrunner** [comment]
I'm closing this, as there hasn't been any feedback/clarification on what exactly is requested. In case this is still something that is wanted, there is the proposal process now, please create a proposal in this repo and follow the template given:

https://github.com/godotengine/godot-proposals
