### ISSUE TITLE
Visual Scripting error when setting 0 as value

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#27611]
**Godot version:**
Godot v3.2.dev.calinou.5b00cd8

**OS/device including version:**
Windows 10 Home

**Issue description:**
If you set a float value to 0 it will be set to nil instead. Something similar happens when you create a variable from the members panel.
![nil instead of 0](https://user-images.githubusercontent.com/2206700/55421629-f4531480-5579-11e9-85ff-b6d4e147ed52.PNG)

When creating a variable from the Members list (here is `new_variable = Null`)
![vs1](https://user-images.githubusercontent.com/2206700/55421666-0cc32f00-557a-11e9-83d1-2035c694d0d1.PNG)

If you then set the value to float, int, or whatever instead of updating to `0` or `""` it will stay `Null`. The main issue is as before, if you go to the editor and set `0`
![newvar](https://user-images.githubusercontent.com/2206700/55421659-07fe7b00-557a-11e9-9d46-69c93ff7d8f4.PNG)

![set-to-0](https://user-images.githubusercontent.com/2206700/55421780-590e6f00-557a-11e9-8ff8-5f91057c5161.PNG)

it will still be Null 
![newvar](https://user-images.githubusercontent.com/2206700/55421659-07fe7b00-557a-11e9-9d46-69c93ff7d8f4.PNG)

To make it change you actually have to set it to 1 (or any other value) and the go back to 0.

To avoid this instead of setting floats to 0 from the inside a node I have to set it to 0.001 or something similar because otherwise it will be Nill.

I believe both of this issues are related to each other and it has to do with a check similar to `!=0` or something like that... but I have no clue of C++ or how to fix this particular thing.

**Comment by fire** [comment]
I think this was resolved.

Can you check on https://github.com/godotengine/godot/commit/ae6c390eb215c8c3f27f0f7a249cb2c07fcfc08a or a latest nightly?

**Comment by fire** [comment]
On a current version when you open variables list and change the type it doesn't update the ui so that the variable shows the default value.

So a easy way to recreate is to create a new variable and change the type to boolean and then change the type to float. Notice that it's still null instead of float = 0 or bool = false.

However, typing any non default value will set it.

**Comment by coppolaemilio** [comment]
It is still broken on my end.
