### ISSUE TITLE
Imported sound is shorter than actual sound, causing end "pops"

### ISSUE THREAD

**Issue by theisegeberg** [godotengine/godot#27610]
Godot version: 3.1
MacOS 10.14.3 on macbook pro

[win.wav.zip](https://github.com/godotengine/godot/files/3035055/win.wav.zip)

Steps to reproduce:
1. Add AudioStreamPlayer to root node of scene.
2. Inspect node and drag attached file to Stream to load it into the ASP
3. Play it from code or from the node inspector, hear the pop at the end
4. Notice the seconds in (0.69s) in the example under the node inspector of the ASP, it is not the same as the audio file lenght (1.12s)

Attached example project.

[game1.zip](https://github.com/godotengine/godot/files/3035070/game1.zip)

**Comment by Zylann** [comment]
In the import settings of your sound, uncheck `Trim` and click `Reimport`.
![image](https://user-images.githubusercontent.com/1311555/55428905-12247780-5582-11e9-8d0b-aa83561c0c66.png)
I sounds like trimming is a bit rough.

**Comment by theisegeberg** [comment]
Sorry, my bad, I hadn't seen that options. That clears it up :-) thank you for the near-immediate response. I guess it would be possible to add a tiny ramp on the trimming. Or snap trimming to nearest zero value. Perhaps this is where I begin contributing. :)
