### ISSUE TITLE
add tilemap editor rotation hotkeys

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27624]
**Godot version:**

3.1

rotating tiles by flipping them on the x and y axis is incredibly unintuitive. i think replacing the hotkeys for flipping, for rotating +-90° would make more sense. we can keep the old hotkeys in the config.

**Comment by Calinou** [comment]
> rotating tiles by flipping them on the x and y axis is incredibly intuitive.

I think you meant "incredibly **un**intuitive" :stuck_out_tongue:

Anyway, I can confirm there's currently no shortcuts for rotating tiles that are already placed.

What about using <kbd>A</kbd> and <kbd>S</kbd> to rotate tiles (counter-clockwise and clockwise respectively), and <kbd>Z</kbd> and <kbd>X</kbd> to flip tiles vertically and horizontally respectively? (On QWERTY, that is.)
