### ISSUE TITLE
3.1 release for Fedora

### ISSUE THREAD

**Issue by AllanDaemon** [godotengine/godot#27620]
As you can see in the link below, there isn't yet a package for 3.1 for Fedora Linux.

https://bodhi.fedoraproject.org/updates/?search=godot

I offer to help in this stuff, but as the building package scripts are already done, It's likely to need just an update change for version and source files and rebuild it.

@akien-mga

**Comment by akien-mga** [comment]
I have a WIP but not finished yet, it's a bit more involved than a simple version bump as dependencies changed. I'd also like to use LTO if Bodhi won't run out of memory, and do a better server/headless split.

**Comment by Calinou** [comment]
Fedora 31 has Godot 3.1.1: https://repology.org/project/godot/versions

**Comment by akien-mga** [comment]
For the reference, I now pushed Godot 3.1.2 to Fedora Rawhide (32), and 3.1.2 update candidates:

- Fedora 30: https://bodhi.fedoraproject.org/updates/FEDORA-2020-bf7d3dce66
- Fedora 31: https://bodhi.fedoraproject.org/updates/FEDORA-2020-908750ee0a
- EPEL 7: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-036932ab82

They're currently pending, should be available for testing within ~24 hours at most, and eventually validated within a week or two. If you can test them on one of the above platforms and report back on Bodhi, this should help speed up the QA validation process.

**Comment by AllanDaemon** [comment]
Already made to updates repository.


![image](https://user-images.githubusercontent.com/607994/71857422-3e979200-30c6-11ea-928f-b9be4a246454.png)
