### ISSUE TITLE
Sample will not loop in HTML5 export

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#2762]
A sample set to `SAMPLE_LOOP_PING_PONG` or `SAMPLE_LOOP_FORWARD` will not loop at all when played per any SamplePlayer.

**Comment by bojidar-bg** [comment]
Is this still an issue on master? There have been some changes since the last year..

**Comment by eska014** [comment]
Yeah, tested this again, still valid

**Comment by reduz** [comment]
Ping pong will likely not be supported, but loop should work

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
