### ISSUE TITLE
Add modifer key for zoom steps in 2d editor

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27622]
**Godot version:**

3.1

Zooming on a large map 16x16k pixels, a mandatory task for quick traversal from one end to the other, is very slow. Maybe we can add a speed toggle via hotkey (shift or similar), or at least an option in the scene editor to change the speed.

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot/pull/48252 (use 
<kbd>Alt + Mouse wheel</kbd>).
