### ISSUE TITLE
tileset editor can't reliably select which tile to edit

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27626]
**Godot version:**

3.1

Scenario: One file, several tiles. Some tiles use the same texture. For example i have an autotile using a 3x3 region, but want to manually be able to place these tiles as well. For that i add 9 single tiles, which overlap the autotile. This prevents me from reliably selecting the correct tile to edit.

I propose we add a list of all the tiles on the current texture, or make the names you can optionally display atm clickable.

**Comment by akien-mga** [comment]
CC @MarianoGnu @YeldhamDev @guilhermefelipecgs

**Comment by TheDuriel** [comment]
I suppose this is connected to this mess of a thread. And the specific comment. https://github.com/godotengine/godot/issues/27661#issuecomment-480414576

Perhaps we can re purpose this issue for the proposal of a tileset editor UX overhaul?

**Comment by mdelz** [comment]
How about a simple dropdown left to the 'New Single Tile' button that lets you select an existing tile, including none?

Additionally a way to unselect the current tile would be great (maybe by pressing Escape). The 1st time you open the edit mode nothing is selected and you can select a tile by clicking on it, which is very useful when the tiles are not overlapping.
