### ISSUE TITLE
Renaming scripts that are currently open creates duplicate tab in script editor

### ISSUE THREAD

**Issue by Jayman2000** [godotengine/godot#27635]
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Kubuntu 18.10 x64

**Issue description:**
If there is a script currently open in the script editor, and that script is renamed using the file system panel, then a tab with a blank name will be added to the script editor. If a scene is run while one or more of these blank tabs is open, then the engine will report errors. The errors do not seem to have any negative side effects, other than polluting the bottom panel's output tab.

I would not expect any of that to happen. I would expect renaming the script file to not add an extra tab to the script editor, and I would not expect that tab to cause errors when a scene is being run.

**Steps to reproduce:**
1. Open a scene which has at least one node with a script attached to it (Scene.tscn in minimal reproduction project).
2. Make sure the attached script (Script.gd) is open in the script editor.
3. Using the file system panel, rename the script to "Test.gd". The error "Another resource is loaded from path: res://Test.gd (possible cyclic resource inclusion)" will appear in the bottom panel's output tab.
4. There should now be two tabs open in the script editor both with the same contents. One will be called "Test.gd", and one will have a blank name. Repeating step 3 with different names for the script (e.g., "TestA.gd", "TestB.gd",
[Script Rename Bug.zip](https://github.com/godotengine/godot/files/3038442/Script.Rename.Bug.zip)
 "foobar.gd") will add more tabs with blank names.
5. Play the current scene. The error message "editor/plugins/script_editor_plugin.cpp:1427 - Condition ' base.begins_with("local://") || base == "" ' is true. Continuing..:" will appear in the bottom panel's output tab once for each blank tab that is currently open in the script editor.

**Workaround:**
Do not rename scripts that are currently open in the script editor, or simply close out of the blank tabs immediately after renaming a script.

**Minimal reproduction project:**
[Script Rename Bug.zip](https://github.com/godotengine/godot/files/3038445/Script.Rename.Bug.zip)

**Comment by Zylann** [comment]
Still happens in Godot 3.2 beta2

**Comment by Xrayez** [comment]
See my failed attempts in #40634, which does fix this issue but introduce other errors (or so it seems), perhaps you can figure out what makes it work.

**Comment by KoBeWi** [comment]
Fixed.
