### ISSUE TITLE
Crash on Android release build 'resume after yield, but class instance is gone'

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#27646]
**Godot version:**
3.1 official

**OS/device including version:**
Windows 10

**Issue description:**
Shows error, but doesn't crash in debug mode. Crashes on release build when resuming after yield. 'Resume after yield, but class instance is gone'

**Steps to reproduce:**
while condition: yield(get_tree(),'idle_frame')

**Comment by Calinou** [comment]
Does this occur when exporting the same project to Windows (in release mode)?

**Comment by akien-mga** [comment]
Follow-up of #22443 which seems still partly reproducible. CC @RandomShaper

**Comment by alexzheng** [comment]
In a game, every node that use yield may be freed at any time, so this error message is quite annoying.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 3.2 builds?

If so, could you provide a project that reproduces it?

**Comment by akien-mga** [comment]
No answer, so closing. I do believe this sort of error might still be reproducible, but without a reliable reproducer this bug report isn't really useful.
