### ISSUE TITLE
Error initializing GLAD Godot 3.1

### ISSUE THREAD

**Issue by alixvoor** [godotengine/godot#27648]
**Godot version:**
Godot 3.1 stable x64

**OS/device including version:**
Windows 10, Intel HD(R) Graphics
AND
Windows 10, Intel HD(R) Graphics 3000
(Two separate computers)

**Issue description:**
Unable to play/test game by pressing play button in project. Have it set to GLES2 but in the command line it says:
ERROR: is_viable: Error initializing GLAD
    At: drivers/gles3/rasterizer_gles3.cpp:142
ERROR: _get_socket_error: Socket error: 10054
   At: drivers/unix/net_socket_posix.cpp:190

So looks like it is still trying to use opengl 3.0 and not 2.0. Strange thing is it will run on some of our computers that have the same graphics and set up, but not others.

**Comment by ShyRed** [comment]
Did you make sure to switch to GLES2 in the game's project settings, too?

**Comment by alixvoor** [comment]
Thank you! so focused on running the game and getting into building it that I didn't realize when you first create the game it asks you to choose the renderer, and even if it says GLES2 in the top right hand of the screen when inside the project it is still trying to use the GLES3 renderer if you missed it asking you at the time you created it...Seems silly that it is in 2 places. But also "Doh!" on my end for totally missing that. Thanks again!
