### ISSUE TITLE
Input actions don't work after exporting project

### ISSUE THREAD

**Issue by N8n5h** [godotengine/godot#27651]
**Godot version:**
v3.2.dev.custom_build.40acc3e

**OS/device including version:**
Ubuntu 18.04.2 LTS

**Issue description:**
Input's actions seems not to be working after exporting [this minimal project](https://github.com/godotengine/godot/files/3040214/test_input.zip) to x11_x86_64 and Windows_x86.
The check:
```
if Input.is_action_pressed("test"):
``` 
only reports true when running the project from the editor, but after exporting it doesn't work anymore.

Notes:
*  The editor and the export templates were compiled from the same commit.
*  I could reproduce the issue in Ubuntu 18.04.2 LTS with the x11_64 export and in Wine and Windows 7 64 Native (no VM) with the Windows x86 export.
* I tested both debug and release in each version

**Comment by Calinou** [comment]
Are the editor and export templates built from the exact same commit?

**Comment by N8n5h** [comment]
> Are the editor and export templates built from the exact same commit?

Yes, they were built from the exact same commit.

**Comment by N8n5h** [comment]
I tested a bit more and added the line test_label.text = str(InputMap.get_action_list("test")).
Running in editor outputs: " [[InputEventKey:43],[InputEventMouseButton:44]] "
but after compiling (I tested release in linux only) it outputs: "[]".
It may be unbinding the action for some reason?
