### ISSUE TITLE
delete tileset editor edit button

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27661]
**Godot version:**

3.1

followup on #27625 

tool_workspacemode[WORKSPACE_EDIT] in https://github.com/godotengine/godot/blob/master/editor/plugins/tile_set_editor_plugin.cpp

Iv'e asked around on the discord and irc, nobody who responded knows what it does. and from what i can see in the source, this button does in fact do nothing.

https://github.com/godotengine/godot/blob/c2c11fc063e723c41579e6307e40fd16ac5334c4/editor/plugins/tile_set_editor_plugin.cpp#L2929

This is where it would actually do something. But it just gets set to pressed. At no point in this file does the button become unpressed. And pressing it just runs code that presses it again.

![image](https://user-images.githubusercontent.com/44248915/55517777-dc5ebc00-5671-11e9-9a30-c7948444f950.png)

**Comment by groud** [comment]
I answered on IRC to your question. This buttons allows quitting the "New Single Tile", "New Autotile" pr "New Atlas" modes, that's all.

**Comment by akien-mga** [comment]
> I answered on IRC to your question (Edit: you likely did not see my message). This button allows quitting the "New Single Tile", "New Autotile" or "New Atlas" modes, that's all. :)

That's not really obvious from the name of the button and its lack of tooltip though.

**Comment by groud** [comment]
> That's not really obvious from the name of the button and its lack of tooltip though.

I completely agree, the UI in this area needs a serious rework.

**Comment by akien-mga** [comment]
So after closing the last two issues trying to figure this button out, maybe we should open a new one about what needs to be done, or repurpose and reopen one of them?

**Comment by groud** [comment]
> maybe we should open a new one about what needs to be done, or repurpose and reopen one of them?

As you want. :) 
Or maybe we can add the suggestion to #21384 (and eventually make it a tracker) ? That might make more sense since I feel that there is quite a lot of room for improvements there.

**Comment by TheDuriel** [comment]
> I answered on IRC to your question (Edit: you likely did not see my message). This button allows quitting the "New Single Tile", "New Autotile" or "New Atlas" modes, that's all. :)

@akien-mga 

But that is not it's current behaviour. The buttons you describe only create new tiles, they do not change the editors mode. You can edit any type of tile at any time. Looking at the source, the only real effect of the editor button currently, is verifying that everything about the current texture is still in order (it's not been deleted, etc.) and then it immediately turns the button back on. (The function that runs when you press the button, is literally incapable of leaving it unpressed.)

It seems the behavior you describe might have existed during one of the 3.1 betas. But was definitely no longer present in the later alphas.

**Comment by groud** [comment]
Yes, the button should not be unpressed by itself, it works like a combobox with the other buttons. So if you click on "new atlas" for example, the edit button gets unpressed and you can create a new atlas tile. If you don't want to create a new atlas tile anymore, you can click the edit button again.

**Comment by IAmActuallyCthulhu** [comment]
@groud I have [followed your use case](https://github.com/godotengine/godot/issues/27661#issuecomment-480164835) and can confirm this button does not behave as you describe. Below is a walk-though demonstrating that it does nothing.

1. Open New Tileset
![Open New Tileset](https://user-images.githubusercontent.com/24380491/55609307-f4077480-5745-11e9-8de4-50cc9ed2cecd.png)

2. Add Spritesheet
![Add Spritesheet](https://user-images.githubusercontent.com/24380491/55609335-0a153500-5746-11e9-98c7-479538799cf5.png)

3. Click "New Atlas" Button
![Click "New Atlas" Button](https://user-images.githubusercontent.com/24380491/55609758-1cdc3980-5747-11e9-8c49-7849f68896d0.png)

4. Select Region (by using cursor)
![Select Region](https://user-images.githubusercontent.com/24380491/55609362-1b5e4180-5746-11e9-8f5b-ae25cf2a6abb.png)

:warning: **Repeatably click on edit button. Observe that nothing happens.** :warning:

5. Select a _Different_ Region (by using cursor)
![Select Different Region](https://user-images.githubusercontent.com/24380491/55609384-2d3fe480-5746-11e9-9059-1377f3ea56a4.png)

6. Click "New Atlas" Button
![Click "New Atlas" Button](https://user-images.githubusercontent.com/24380491/55609690-ef8f8b80-5746-11e9-9c44-2fcabdb728b8.png)

7. Select An Additional Region (by using cursor)
![Select An Additional Region](https://user-images.githubusercontent.com/24380491/55610321-477ac200-5748-11e9-8734-090db0ea5833.png)

**Comment by groud** [comment]
Please... I said "If you don't want to create a new atlas tile anymore, you can click the edit button again."
![Peek 05-04-2019 10-32](https://user-images.githubusercontent.com/6093119/55614827-2f2d9600-578e-11e9-84e0-7db1531236d5.gif)

So :
1) You click on "New single tile" -> Notice the edit button is not pressed anymore, and the "new signle tile is"
2) You click "Edit" -> Notice the "New single tile" is not pressed anymore, and the "Edit" button is.

Those buttons act as like "tabs", two of them cannot be pressed at once. And yes, once you have selected the region, the "Edit" button become active again since we went back automatically to the "Edit" mode. So in the end, this button looks only useful to cancel the "New [...]" actions.

**Comment by TheDuriel** [comment]
In that case.

https://streamable.com/lbmxu

Rename the button to Cancel. Move it somewhere more sensible, the top left of editors is historically where you find highly important dropdown menus. (Godot follows this convention elsewhere.) Give it the tooltip: Stop the creation a new tile, and return to edit mode. __And__ make it so the button only appears when you are actually eligible to cancel out of the creation of a new tile.

Btw. You can't actually make multiple tiles while in the "new xtile" "tabs", so the button is barely necessary.

**Comment by groud** [comment]
Well, IMHO the UI needs a full rework. We could at least replace what the button do by a right-click anywhere, or a second click on the button could cancel the action instead. That's likely a good short-term solution.

If it's ok with Akien, maybe you could update the issue comment with possible suggestions and we reopen it.

**Comment by TheDuriel** [comment]
Well then, here my redesign proposal. With descriptive labels and __tooltips__ explaining what each interface is meant to do.

[TILESETEDITOR.zip](https://github.com/godotengine/godot/files/3049530/TILESETEDITOR.zip)

**Comment by prock-fife** [comment]
> Well, IMHO the UI needs a full rework. 
> 

I agree.  IMO the tileset editor is the weakest feature in Godot.  I'm new to the engine and honestly it was quite the mystery to figure out the editor (thankfully there are some youtube videos out there) so I can see it as a hurdle for a lot of people.  After some time with it I'm able to do most everything I need to do but it can be frustrating at times.
