### ISSUE TITLE
Press close button after modifying editor setting font main size messed up the display

### ISSUE THREAD

**Issue by gsegovia2018** [godotengine/godot#27663]
Godot version 3.1

OS/device including version:
MacOs Mojave 10.14.3
McBook Air 13 (2015)

Issue description:
I tried to modify the main font size in the editor settings and when I increase it and close the settings the display  is messed up.
![Screen Shot 2019-04-04 at 12 56 47 AM](https://user-images.githubusercontent.com/46790538/55518508-91927380-5674-11e9-8ea0-0b054911ba6d.png)

Steps to reproduce:
Editor -> Editor Settings -> Interface -> Editor -> Main Font Size -> Set to 40 -> Press close

**Comment by Calinou** [comment]
The font size should be capped to a reasonable value to avoid this. The default size is 14; I think 20 is a reasonable maximum value. (The editor scale can still be customized freely, in case the default value isn't suitable for a specific display.)

**Comment by gsegovia2018** [comment]
Got it. Working on it!

**Comment by qarmin** [comment]
It should depend on editor scale, maybe (25 / EDSCALE)?
50% - max 42
100% - max 25
200% - max 12

**Comment by Calinou** [comment]
@qarmin The font size is scaled with the editor scale, and this would still make it possible to set high values by switching to a lower editor scale, setting the font size to 50, then raising the editor scale again.

**Comment by akien-mga** [comment]
IMO this should be supported. 40 on 100% scale is likely a bit extreme, but all those widgets should recalculate their size to handle a change in font size.

**Comment by KoBeWi** [comment]
Looks fixed in 4.0
![image](https://user-images.githubusercontent.com/2223172/90835324-9aa8e100-e34c-11ea-8394-aa73fca5f4c8.png)
