### ISSUE TITLE
YSort-like draw algorithm for cells of stacked tilemaps

### ISSUE THREAD

**Issue by CngKO** [godotengine/godot#27678]
Especially with isometric tilemaps, it would be immensely useful to have functionality that would draw cells of stacked tilemaps "cell at a time," as if they were cells of a single tilemap.  This would allow dynamic combination of tilesets and reduce the size of required art assets

For example, lets assume that we have 3 tilemaps stacked on top of each other; ground, wall, and object.  The new node would override default draw algorithm and draw cell [x: 0, y: 0] for all three tilemaps (ground[0,0], wall[0,0], object[0,0]) before moving on to cell [0,1], then to [1,0] and so on, drawing cell ground[n,n], wall[n,n], and object[n,n] last

A possible approach:
* A new MultilayerTileMap node that holds all tilemap properties except for the tileset property with multiple TileMapLayer nodes as children that have different tilesets.  All other settings for the TileMapLayer nodes would be inherited from the parent, MultilayerTileMap node

**Comment by bojidar-bg** [comment]
Note that Tilemaps with YSort on can be mixed with a YSort node to sort at once.
So, it should be possible to do the following:
* YSort
    * TileMap ground (ysort = true)
    * TileMap walls (ysort = true)
    * TileMap objects (ysort = true)
To get the wanted effect, or at least something similar.

(It is also possible to forgo the additional YSort node by putting one of the tilemaps in its place).

**Comment by CngKO** [comment]
@bojidar-bg, Unfortunately, the YSort method described above is not working.  Probably because the cells are not children of the tilemap node, but integral parts of the tilemap itself.

**Comment by CngKO** [comment]
Another possible way to solve this issue could be to make non-empty cells of the tilemap actual child nodes, which would allow the YSort solution to work.  Though, I don't know what the impact on performance would be as I'm not familiar with the underlying design.

**Comment by bojidar-bg** [comment]
Here is an example project showing what I mean:
[27678-ysort-tilemap.zip](https://github.com/godotengine/godot/files/3058525/27678-ysort-tilemap.zip)
Check the `world-proper.tscn` file. Try to reorder the tilemap nodes to see that the sorting works. Note that Tilemap2 and Tilemap3 both have a knife and an egg each. Note that I had to add a very small offset to the base Tilemap in order to keep it below the others, as the sort is unstable.

**Comment by CngKO** [comment]
Wow, that actually works.  Nicely done.  Thanks!

**Comment by CngKO** [comment]
By the way, is there any reason why you are using square mode for isometric tilemaps?

**Comment by bojidar-bg** [comment]
Is this issue still valid then? Or is my example doing what was wanted?

**Comment by CngKO** [comment]
@bojidar-bg, your example covers what I needed.  We can close the issue.  Cheers.
