### ISSUE TITLE
Very indented shadows

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27685]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
A simple directional light over a simple cube produces this **triangled shadows**:
![](https://cdn.discordapp.com/attachments/477544613511692358/563374743063887873/unknown.png)

**Steps to reproduce:**
Open the project and press F6.

**Minimal reproduction project:**
[shadows.zip](https://github.com/godotengine/godot/files/3044697/shadows.zip)

**Comment by Zylann** [comment]
Is this a regression? To me it just looks like the normal behavior of low-resolution shadowmap, with all the effort made to smooth its huge pixels.

**Comment by rogeriodec** [comment]
Found the solution as indicated by @mysticfall:
Increasing the "Directional Shadow" -> Size it gets much better.

![](https://cdn.discordapp.com/attachments/212250894228652034/563521415597260801/unknown.png)
