### ISSUE TITLE
C# memory leak calling GetOverlappingBodies() from Area2D node

### ISSUE THREAD

**Issue by AssimiIation** [godotengine/godot#27684]
**Godot version:**

Godot v3.1.stable.mono.official/Mono 5.18.0.240

**OS/device including version:**

Windows 10 64bit

**Issue description:**

While working on a platformer project I noticed a memory leak in the debugging monitor - static memory continually increases (albeit quite slowly). I've narrowed down the leak to an Area2D node I use at the end of a level to check for a collision with the player in order to change scenes for the next level. I've further narrowed the leak to the C# script where the following function is called:

`var bodies = GetOverlappingBodies();`

The leak does not occur if I instead use GDScript and call the equivalent function:

`var bodies = get_overlapping_bodies();`

**Steps to reproduce:**
Create a scene:
-Area2D
--Sprite
--CollisionShape2D

Attach C# script to Area2D node that looks like:

```
using Godot;
using System;

public class Area2D : Area2D
{
	public override void _PhysicsProcess(float delta)
	{
		var bodies = GetOverlappingBodies();
	}	
}
```

**Minimal reproduction project:**

[Memleak Test.zip](https://github.com/godotengine/godot/files/3044487/Memleak.Test.zip)

**Comment by akien-mga** [comment]
Still seems to be reproducible in the current master branch.

**Comment by neikeq** [comment]
I added the following at the end of the method and static memory stopped increasing:

``` C#
GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
GC.WaitForPendingFinalizers();
```

So there isn't any leak, it's just the GC isn't collecting the array yet.

If you don't want to wait for the GC, you can always dispose the array manually:

``` C#
public override void _PhysicsProcess(float delta)
{
	using (var bodies = GetOverlappingBodies())
	{
		// ...
	}
}
```

**Comment by LordBrkica** [comment]
Just a small note, in Godot 4.1, when one does this:
```
	public override void _PhysicsProcess(double delta)
	{

	using (var bodies = GetOverlappingBodies())
	{
		// ...
	}
```

One gets an exception in the Visual Studio Code editor:
`
'Array<Node2D>': type used in a using statement must be implicitly convertible to 'System.IDisposable'. `
