### ISSUE TITLE
Editor does not detect a .shader files dragged to its file system, but imports when placed directly in the project directory

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#27682]
**Godot version:**

c2fb1c9

**OS/device including version:**

Windows 7

**Issue description:**

Dragging a .shader file into the filesystem in the editor does not seem to import it. Copying it into the project directory does work however.

**Steps to reproduce:**
Drag a .shader file into the Editor

**Minimal reproduction project:**

**Comment by Calinou** [comment]
I've tested drag-and-dropping `.gdshader` files (and `.shader` in `3.x`) and it works in both `master` ffc4d62e6 and `3.x` 3e7e70138.
