### ISSUE TITLE
BitMap get_true_bit_count method returns incorrect number of true bits

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#27681]
**Godot version:**
3.1 master

**OS/device including version:**
Windows 10 x64

**Issue description:**
`BitMap` `get_true_bit_count` method returns incorrect number of true bits. Current implementation:
https://github.com/godotengine/godot/blob/8889089c1b81fc81538ede2ef097328a6f62ddf0/scene/resources/bit_map.cpp#L93-L113

**Steps to reproduce:**
1. Create a bitmap of size 16x16.
2. Fill bitmap with `set_bit_rect` entirely.
3. `get_true_bit_count()` will return 224 (expected: 256)

[bitmap-true-bit-count.zip](https://github.com/godotengine/godot/files/3044273/bitmap-true-bit-count.zip)

**Comment by Xrayez** [comment]
I've come up with this solution so far (based on [this answer](https://stackoverflow.com/questions/9949935/calculate-number-of-bits-set-in-byte/9950662#9950662)):

```cpp
for (int i = 0; i < ds; i++) {
        c += (d[i] >> 7) & 1;
        c += (d[i] >> 6) & 1;
        c += (d[i] >> 5) & 1;
        c += (d[i] >> 4) & 1;
        c += (d[i] >> 3) & 1;
        c += (d[i] >> 2) & 1;
        c += (d[i] >> 1) & 1;
        c += d[i] & 1;
}
```
It works but maybe we could make it even shorter:
```cpp
for (int i = 0; i < ds; i++) {
	for(int j = 0; j < 8; j++) {
        	c += (d[i] >> j) & 1;
	}
}
```

**Comment by toasteater** [comment]
A bit late but just want to note that:

- The longer version is not verbose. The inner loop is unrolled for performance: it's got less branches (in case of a naive compiler, at least).
- The fastest approach would most certainly be __builtin_popcount (GCC & Clang) / __popcnt (MSVC). These intrinsics compile to single instructions on modern CPUs.
