### ISSUE TITLE
When I disconnect the client from server, client doesn't know that it is disconnected from server.

### ISSUE THREAD

**Issue by Sphynxinator** [godotengine/godot#27696]
**Godot version:**
v3.0.6

**OS/device including version:**
Windows 8.1

**Issue description:**
I expected a disconnect alert but Godot doesn't give any.

**Steps to reproduce:**
1.Disconnect the Client from Server with Net.Sockets.destroy()
2.Check from Godot if Client is disconnected with StreamPeerTCP.get_status() == StreamPeerTCP.STATUS_CONNECTED
3.It will act like it is not disconnected, thus it will return StreamPeerTCP.STATUS_CONNECTED.

**Minimal reproduction project:**

`//NodeJS Server`
`var Server = function() {`
`this.net = require("net");`
`  this.netServer = new this.net.createServer();`
`  this.netServer.on("connection", function(data) {`
`    //of course i won't destroy when client connects to the server, just for reproduction purposes`
`    data.destroy();`
`  };`
`  this.netServer.listen(3001);`
`};`
`//Godot Client`
`//in _process():`
`if(tcp_connection != null and`
`	(!tcp_connection.is_connected_to_host() or`
`	tcp_connection.get_status() != StreamPeerTCP.STATUS_CONNECTED)):`
`	UIManager.open_disconnect_window()`

**Comment by Faless** [comment]
@Sphynxinator this should be fixed in `3.1`, can you check it out?

**Comment by Sphynxinator** [comment]
@Faless  Wow it fixed. Thank you. But there are a important bug in the new version. I will write it to the another issue. Please can you check it out?

**Comment by Faless** [comment]
@Sphynxinator sure. Closing as already fixed.
