### ISSUE TITLE
AnimationPlayer 3D, clone play executions of animations !!!!

### ISSUE THREAD

**Issue by esbvaGames** [godotengine/godot#27692]
AnimationPlayer share, play execution, with mote instances of same type, in robot scene!!!
1) create área 3d
2) instante a simple mesh
3) add animationPlayer
4) add emisión color to 1.5 keyframe to 0.01 keyframe, add animación
5) Save Scene

6) Create new Scene
7) instace 5 copies, of subScene, add signal
8) colisión objects, and play animación, buuggs error, animación is a clone, all objects !!!

Sample
https://esbva.itch.io/Xenauts
W,S,A,D, Q,E,  search containers !!!!

**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by slapin** [comment]
I do not understand what you consider a bug. If you say that animation is the same for all objects it is normal if you do not change animation in code

**Comment by fire** [comment]
Can you post a minimal reproduction project?

Recommended as it greatly speeds up debugging. Drag and drop a zip archive to upload it.

**Comment by esbvaGames** [comment]
I have already solved it, make it work, then alter the property, which is in the images of the folder "Solution", it would be good to include this simple project, in the examples, since more than someone will find this broth of heads, since there is not an example to explain it!

[CloneReaction.zip](https://github.com/godotengine/godot/files/3050645/CloneReaction.zip)

**Comment by groud** [comment]
Closing as the initial problem is solved :)
