### ISSUE TITLE
Vertex Color problems with Canvas Background (3D scene)

### ISSUE THREAD

**Issue by narcissawright** [godotengine/godot#27697]
**Godot version:**
3.1 stable

**OS/device:**
Windows 10
NVIDIA GeForce GTX 560 Ti

**Issue description:**
When using a dynamic (changing) canvas as the background, meshes using vertex color sometimes display incorrectly.

**Steps to reproduce:**
Create a 3D project, have canvas background altered via script using camera angle, which can be changed with mouse input. Assign vertex color to a mesh's material. Start the project and look around.

**Minimal reproduction project:**
[vertex-color-problems.zip](https://github.com/godotengine/godot/files/3047912/vertex-color-problems.zip)

**Notes**
Lots of strange behavior, adding a Label node seemed to fix it. Using a different mesh I created seemed to fix it only for that mesh...

**Comment by narcissawright** [comment]
Here is a gif showing the problem:

![problem-gif](https://user-images.githubusercontent.com/49114816/55630100-b288c080-5769-11e9-95bc-60f7c66e9a1b.gif)

**Comment by clayjohn** [comment]
Is this in GLES2 or GLES3?

**Comment by narcissawright** [comment]
GLES3

**Comment by Llcoolsouder** [comment]
Could this be related to #30275 ?
The _symptoms_ looks similar and the fact that adding a Label node affects the result only furthers my suspicion.

**Comment by clayjohn** [comment]
It does indeed look like a similar problem. It would be a good idea to test this out on master and see if its still reproducible. I have a feeling it was fixed by https://github.com/godotengine/godot/pull/31270/

**Comment by Llcoolsouder** [comment]
Sorry for the ugly gif but can confirm this is no longer an issue on the latest commit on master.

![vertex_color_probs_master_09_07_19](https://user-images.githubusercontent.com/15933766/64477407-3dcb0f80-d169-11e9-9fa9-fa9aad7b0fa4.gif)

**Comment by clayjohn** [comment]
Thank you!
