### ISSUE TITLE
exporting layer(bit mask) variables to inspector

### ISSUE THREAD

**Issue by MotasemZakarneh** [godotengine/godot#27695]
**Godot version:**
**3.1**

**Issue description:**
basically, i think it would be very useful to be able to export bitmasks (PhysicsLayers/RenderLayers) as exported variables, i also heard that in 2.1 that export hint was working.
```export(int, FLAGS) var current_flags```
but now it appears to no longer work, as it exports a simple typical int, rather than the bit mask. 

so i just thought, i'd make a ticket, as it makes sense, and pretty useful (and appearently, it was working in past, but no longer is).
apologies if this is in wrong place.

**Comment by Zylann** [comment]
This feature is mentionned in the doc: https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#exporting-bit-flags

And it looks like you *have* to specify the name of every bit, exporting all 32 togglable bits without a name does not work.

![image](https://user-images.githubusercontent.com/1311555/55663992-ee319200-581e-11e9-9b23-e5474ce1c5c7.png)

**Comment by gau-veldt** [comment]
That's not so useful for the layers/masks since now we have duplication of scripts defining names that are already in project settings under Layer Names.  There should be a specific LayerMask hint and the editor can then show the same bit toggles as a Body/Area's mask would show and, likewise, show the project-set names when the dropdown is expanded.

**Comment by Zylann** [comment]
Indeed, now that these are better identified than in Godot 2 there should be a hint for these so they can show the names defined in ProjectSettings.
But if you are just exposing a mask for other purposes using `FLAGS` with no names, that functionality is currently broken. It is described in the doc but half of it is not working.

**Comment by groud** [comment]
So, I'm not sure what to do with this issue. Is the initial problem solved or you need something specific.
If so, could you update the issue title and first comment so it is clear what you suggest should be done ?

**Comment by gau-veldt** [comment]
@ground to address OP's immediate issue, exporting flags should regain the 2.1.5 behavior allowing bit toggles in the editor and not a numeric int entry field, even when no labels are given (we just get an anonymous list of bit toggles in the inspector in that case as was the case in 2.1.5).

A more long term solution is to actually separate FLAGS, and PHYSICSMASK's as two seperate exports, the latter using the same interface in the editor used by the collider layer and mask section (which among things has a dropdown to show the layer names defined in the project settings).

A further refinement includes having the layer names available to scripts, or at least, an internal dictionary allowing things like PHYSICS_LAYERS["my_layer"]  to yield the appropriate integer value for that particular mask bit.  Magic numbers in scripts are bad.

**Comment by MotasemZakarneh** [comment]
@Ground sorry for being late, but @gau-veldt sald it, better than i could honestly did. 
i didn't know how to express it properly i guess, but, he did express whats on my mind perfectly, not sure, what to set the title to, to be honest, if you have an opinion of a better tittle please do tell about it.

**Comment by rcorre** [comment]
I believe the OP here was fixed by #29578. The additional point about script-accessible layer names should probably become a [proposal](https://github.com/godotengine/godot-proposals/issues) (I was specifically looking for that issue and had to dig a bit to find it in a comment here.

**Comment by akien-mga** [comment]
Indeed, fixed by #29578.
