### ISSUE TITLE
Incorrect conversion of string to float

### ISSUE THREAD

**Issue by dwafafiki** [godotengine/godot#27706]
**Godot version:**
v3.1.stable.official

**Issue description:**
Incorrect conversion of string to float

**Steps to reproduce:**
print(float("33.3"))
print(float("33.33"))
print(float("333.3"))
print(float("3333.3"))

**Console output:**
33.299999
33.330002
333.299988
3333.300049

Can anyone confirm this? I am worried about my computer.

**Comment by Calinou** [comment]
This is due to floating-point precision error (GDScript uses 32-bit floats); there's nothing that can be done about it, except [switching to doubles](https://github.com/godotengine/godot/issues/288) which use 64-bit precision. It'd be a fair amount of work still.

**Comment by dwafafiki** [comment]
> there's nothing that can be done about it

or just write your own function:

func string_to_float(s):
if "." in s:
var a = s.split(".", true)
return float(int(a[1]) + int(a[0]) * pow(10,a[1].length())) /
pow(10,a[1].length())
else:
return float(s)

Pozdrawiam



Maciek / Ładne Halo
studio.ladne-halo.pl


pt., 5 kwi 2019 o 20:19 Hugo Locurcio <notifications@github.com> napisał(a):
