### ISSUE TITLE
Skeleton is moving Y up a bit while using Blend2

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#27703]
**Godot version:**

Godot 3.1.1.devel 7f691e8bb

**OS/device including version:**

Kubuntu 19.04 / GTX 1070 Ti (driver version : 418.56)

**Issue description:**

Skelecton is moving Y up a bit while using `Blend2` with `AnimationTree` even though it is the same animations.

**Steps to reproduce:**
![anim_tree_blend](https://user-images.githubusercontent.com/8281454/55642801-765a6c00-580c-11e9-9eff-7e6b05748c68.gif)

**Minimal reproduction project:**

[AnimTree blend.zip](https://github.com/godotengine/godot/files/3048873/AnimTree.blend.zip)

**Comment by guilhermefelipecgs** [comment]
Also affects 3.1.stable.official.
