### ISSUE TITLE
My PC gets frozen when I shutdown Godot Engine.

### ISSUE THREAD

**Issue by Sphynxinator** [godotengine/godot#27700]
**Godot version:**
3.1

**OS/device including version:**
Windows 8.1

**Issue description:**
I use Godot normally. But when I close the engine, sometimes it gives some error and my PC gets frozen. 

**Steps to reproduce:**
1. Use Godot normally.
2. Close Godot Engine.
3. Not always, but sometimes, the console will say something like "there are some memory leak in the bla bla", "MemoryPool error" (I forgot the full error, I am so sorry, I will edit this post when I see the error again.)

**Minimal reproduction project:**
There are no reproduction project because it's Godot Engine related. This is so serious bug, because it wipes all the preferences of the Godot Engine, my Godot project, some of my other programs.

**Comment by slapin** [comment]
Wow interesting bug, what an awesome strike of luck! Maybe you need a run of AV software on your PC.
The error messages you mention are from memory pool checks and can't relate to hang. Also it is possible that your RAM is failing but as some of your programs get wiped then I guess that is not enough.

**Comment by qarmin** [comment]
Please, provide more info about PC - graphics card, processor and RAM.
Have you installed the latest available drivers to graphics card and system?
Did you try to test each part of computer? (Ram - Memtest, Disk - HDTune etc.)

**Comment by Sphynxinator** [comment]
I am formatting my PC and will download the latest drivers. I will notify you when I finish. Thanks.

**Comment by Sphynxinator** [comment]
I think it fixed by itself. I formatted my PC and downloaded the latest drivers and it doesn't occur anymore.

**Comment by Calinou** [comment]
@Sphynxinator I'll mark this issue as resolved then :slightly_smiling_face:
