### ISSUE TITLE
TileSet editor can't load more than a single AtlasTexture (tres) that point to the same texture

### ISSUE THREAD

**Issue by Drkie** [godotengine/godot#27709]
**Godot version:** 3.1 Stable

**OS/device including version:** Windows 10 1809

**Issue description:** When adding a texture to the tileset on the new TileSet editor, if you have a group of AtlasTexture TRES files that point to the same texture, it is only possible to add one of them. Attempting to add a second one will produce the message **file(s) were not added because was already on the list** [sic] (it is possible to add other atlastexture TRES files if they point to a different texture). I was unable to bypass this error by editing the tileset's TRES file manually and adding my textures.

**Steps to reproduce:**
1) New Project
2) Create two AtlasTexture tres files pointing to the same texture. I used TexturePacker and its plugin for this, as I can't find a way to do it manually.
3) Create a TileSet and go into the editor. Press the add button and attempt to add these two tres files you created.
4) You will receive the error.

**Minimal reproduction project:**
[BugReport.zip](https://github.com/godotengine/godot/files/3049585/BugReport.zip)
(try to add grass03.tres to the tileset to see the error)

Notes: this really breaks my workflow, as i can't read the original texture directly considering it has nonaligned images of different shapes and sizes. Any workarounds would be appreciated.

**Comment by Calinou** [comment]
@Drkie Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

> Notes: this really breaks my workflow, as i can't read the original texture directly considering it has nonaligned images of different shapes and sizes. Any workarounds would be appreciated.

You could make multiple copies of the original texture, I guess :no_mouth:

**Comment by Drkie** [comment]
Hi @Calinou! Sorry for the delay in replying. Yes, this issue is still present in v3.2.2. I have attached the MRP: [Issue27709.zip](https://github.com/godotengine/godot/files/5125677/Issue27709.zip)

Reproduction steps:
1) Open the project. Open **tileset.tres**.
2) Attempt to add **atlas_tex_2.tres** to the tileset.
3) Error will pop up.

As you can probably imagine from the date I posted this bug, I have since moved on to not using atlas textures at all (and my project is in such advanced stages that moving back to using them would be a nightmare), so this is no longer a blocker for me. Regardless, it should probably still be fixed.

**Comment by kleonc** [comment]
> Yes, this issue is still present in v3.2.2. I have attached the MRP: [Issue27709.zip](https://github.com/godotengine/godot/files/5125677/Issue27709.zip)
> 
> Reproduction steps:
> 
>     1. Open the project. Open **tileset.tres**.
> 
>     2. Attempt to add **atlas_tex_2.tres** to the tileset.
> 
>     3. Error will pop up.

Seems already fixed (not reproducible in `3.4.2.stable`).
