### ISSUE TITLE
Real time raytracing with valkan api

### ISSUE THREAD

**Issue by Burnsedia** [godotengine/godot#27712]
We need to use Nvidias Realtime Valkan API raytrace framwork for the Godot 4.0.x branch or 3.1.x hopfully.
**Godot version:**

4.0.x or 4.1.x

**OS/device including version:**

Linux, Mac OS, Windows GTX 1650
issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/27355.
