### ISSUE TITLE
RigidBody will not go to sleep anymore if 'set_can_sleep()' is used

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27715]
**Godot version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**OS/device including version:**
3.2 dev

**Issue description:**
If I `$RigidBody.set_can_sleep(false)` once, even after I `$RigidBody.set_can_sleep(true)`, the `$RigidBody.is_sleeping()` will always show **false** (RigidBody will not sleep anymore). 

![image](https://user-images.githubusercontent.com/11199752/55661007-a93a3b00-57df-11e9-89d6-e5897e3f3c83.png)

**Steps to reproduce:**
1) Open the attached project
2) Press F5
3) Look at the bottom left status (Is sleeping will be true automatically after some seconds)
4) Left click and hold anywhere (both statuses will be **false**)
5) Release mouse button (is_sleeping will not be true anymore)

**Minimal reproduction project:**
[sleep.zip](https://github.com/godotengine/godot/files/3049930/sleep.zip)

**Comment by avencherus** [comment]
In the past year or so of using the engine, I've never had any luck with the sleep functionality, at least for 2D.  It seems very rare and random if anything ever comes to rest or can be forced into rest.  I wonder if this flagging issue is part of the reason why.

**Comment by rogeriodec** [comment]
This could create a HUGE PERFORMANCE PROBLEM, because if there are hundreds of RigidBodies that have been changed by `set_can_sleep ()`, their physics will be processed FOREVER, even if they are still.
This correction should be a **PRIORITY**.
