### ISSUE TITLE
Bug with Custom Node Types and Exported Dictionary Variables

### ISSUE THREAD

**Issue by Takanu** [godotengine/godot#27727]
**Godot version:**

3.2.dev.calinou.4011429

**OS/device including version:**
macOS 10.14.3

**Issue description:**
When a custom node has an exported dictionary value, the following happens:
- When the node is created for the first time upon opening the project, no value is defined.
- For every successive time it's created, the Dictionary will be created with the contents of the dictionary of the first node immediately, before the script has the chance to pre-populate it.

This doesn't happen with other reference types like Arrays (an example of which is included with the dictionary in the reproduction project).

This happens on _enter_tree() and _ready(), the order in which this happens makes no difference.

**Steps to reproduce:**
- Open the test project
- View the Output and add the node SpecialSpatial.  Note how the Public Dictionary contents will be generated as none exist.
- Add a second new SpecialSpatial node - it will already have the contents of the first Public Dictionary before the code gets a chance to generate contents for it.

**Minimal reproduction project:**
[Dictionary Duplication.zip](https://github.com/godotengine/godot/files/3050534/Dictionary.Duplication.zip)

**Comment by Calinou** [comment]
@Takanu Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, and I've tried the MRP but it seems to be far from minimal. I gave it a try and fixed the variable shadowing errors, but then I'm not sure I understand what the bug is exactly.

The behavior seems to be as defined in the script, all export variables are uninitialized and get populated as defined. Maybe this was different in the past.
