### ISSUE TITLE
multi pass canvasitem materials

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27726]
**Godot version:**

3.1

**Issue description:**

Currently ShaderMaterials with a CanvasItem shader can not have additional passes. No issues about this seem to exist. Unless there is a technical limitation involved i would like to have this ability.

https://github.com/godotengine/godot/blob/master/scene/resources/material.cpp#L265

**Comment by CowThing** [comment]
If it's not possible, then maybe the "Render Priority" property should be hidden when the material is a CanvasItem. As far as I can tell that property only has an affect when there's multiple material passes.

**Comment by sparkart** [comment]
Seems to be related to this issue: #10686

**Comment by Nobelix** [comment]
This is kinda like using a frameBuffer right? It would be super useful for multi-pass when using kernels.

**Comment by clayjohn** [comment]
@Nobelix Sorry no. Its just redrawing the sprite a second time overtop of itself. 

A Viewport is a FrameBuffer though. There is a tutorial in the docs on how to use it for multi-pass effects http://docs.godotengine.org/en/latest/tutorials/viewports/custom_postprocessing.html.

**Comment by samdze** [comment]
Please let the user have multi-pass shaders for 2D too.
It can be used for other things besides redrawing the sprite a second time over itself, like writing to a buffer in the first pass and reading it in the second.

**Comment by mhilbrunner** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/496

**Comment by Masterpoda** [comment]
Just throwing my support behind this, I've currently got [this](https://www.youtube.com/watch?v=4Hf9w9KYyXc) fire simulation working, and it would be a huge benefit to computational efficiency and code simplicity if I could do some of these steps with successive passes instead of passing them around between viewports.
