### ISSUE TITLE
Unstoppable error flood freezes editor after trying to generate a Concave Collision Shape

### ISSUE THREAD

**Issue by yaelatletl** [godotengine/godot#27728]
(Done)

**Godot version:**
3.1 Stable

**OS/device including version:**
Windows 10 Intel HD graphics 520 

**Issue description:**
When you try to create a concave collision shape from this menu
![imagen](https://user-images.githubusercontent.com/28612272/55670546-1cc16400-5843-11e9-97d4-713f3aab114a.png)

You will get this error: 
ERROR: build: Condition ' O == __null ' is true. Continuing..:
   At: core/math/quick_hull.cpp:402
ERROR: build: Condition ' !F2 ' is true. Continuing..:
   At: core/math/quick_hull.cpp:428
Sometimes it will stop and will generate a concave mesh but some times it won't stop at all and you will be forced to exit godot. 
**Steps to reproduce:**
(I think this happens in objects that are made out of separated meshes)
*Create an object in some editor, import it into godot
*Select its meshinstance
*From the mesh menu select create concave staticbody
*It freezes. 

**Minimal reproduction project:**
Try to generate concave staticbodies for these: 
[objects.zip](https://github.com/godotengine/godot/files/3050552/objects.zip)

**Comment by Chaosus** [comment]
Looks like an old problem has been revived - https://github.com/godotengine/godot/issues/21141

**Comment by ScepticDope** [comment]
I have the same problem when I try this on a CapsuleMesh. Using 3.1.1 Stable Mono.

**Comment by rcorre** [comment]
Also happens with Convex collision shapes, on master (76678b260).
[example.zip](https://github.com/godotengine/godot/files/4043468/example.zip)

**Comment by rcorre** [comment]
Interestingly, mine fails on convex but is fine for trimesh.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3

**Comment by kleonc** [comment]
> Also happens with Convex collision shapes, on master ([76678b2](https://github.com/godotengine/godot/commit/76678b2609921f27f52c1a2e2bd62b8d2a27bb4b)).
> [example.zip](https://github.com/godotengine/godot/files/4043468/example.zip)

Present in `3.3.2.stable`.
Fixed in `3.4.beta3` (most likely by #48533).
Didn't check `master` (but most likely fixed by #48916).

**Comment by Calinou** [comment]
Closing per @kleonc's comment.
