### ISSUE TITLE
renaming project, short key bug

### ISSUE THREAD

**Issue by netblink-cobreen** [godotengine/godot#27722]
**Godot version:**

Godot 3.1

**OS/device including version:**

**Issue description:**

When renaming project in home and pressing "enter", project don't rename, but opens for editing.
expected renaming of project.
**Steps to reproduce:**
choose project. push rename. enter new value to input. press enter

**Comment by CJNA** [comment]
This issue has been resolved by @kbake and is pushed to master branch.

**Comment by CJNA** [comment]
Adding a link to gif that shows the correct behavior
https://i.imgur.com/mbTcaJj.gifv

**Comment by Mochnant** [comment]
Is there a target release version?  This does not appear to be fixed in 3.1.1 on Mac.

**Comment by akien-mga** [comment]
This is fixed as of Godot 3.2.3.
