### ISSUE TITLE
Texture button stretch mode only works on normal texture

### ISSUE THREAD

**Issue by arjemour** [godotengine/godot#27737]
**Godot version:**

Godot 3.1

**OS/device including version:**

**Issue description:**

When using a texture button the stretch mode only works on the normal texture

**Steps to reproduce:**
Create a new scene with a ui node
Place a texturebutton in the ui node
Set expand to on, stretch mode to keep aspect centered
Use the default icon.png as normal an focused texture and set the texturebutton size to 100 by 300
Run the scene and click on the button

**Minimal reproduction project:**

[TextureButton.zip](https://github.com/godotengine/godot/files/3050843/TextureButton.zip)

**Comment by TheDuriel** [comment]
https://github.com/godotengine/godot/pull/27088 addresses this.

**Comment by Calinou** [comment]
I'll close this issue as it has been addressed in the `master` branch (and will be fixed inthe upcoming 3.1.1).
