### ISSUE TITLE
Render Priority Ignored Under GLES2

### ISSUE THREAD

**Issue by ATryder** [godotengine/godot#27739]
**Godot Version**: 3.1 official

**OS:** Ubuntu 18.04.1

**Issue**:
In the process of converting my game from GD3.0 to GD3.1/GLES2 I discovered that the Render Priority setting does not work under GLES2.

For example the game map has a number of stars which are rendered with a sphere and a glowing billboard plane. Both the sphere and the glowing plane have the same coordinates, to ensure the sphere appears in front of the glow I assign a Render Priority of -1 to the glowing plane. Using GLES3 this works perfectly, with GLES2 it would appear that the Render Priority value is ignored.

The following screenshots will demonstrate this. The first screen shows the game running under GLES3 with Godot Engine 3.0 where you can see all of the stars rendering in front of their respective glow planes. In the second shot you can see the star on the right renders in front of it's glow plane while the other is rendering behind it.

![RenderPriority_01](https://user-images.githubusercontent.com/10942031/55674440-b69c0780-5869-11e9-8f18-4b89c04f60e8.png)
![RenderPriority_02](https://user-images.githubusercontent.com/10942031/55674441-b69c0780-5869-11e9-9450-d944fb063556.png)

Edit: It should be noted, by the way, that I am not using the built-in Spatial Material, rather I am using custom written Shader Materials.

**Comment by OBKF** [comment]
I was going to report this, also using no_depth_test option make object render behind the sky (not suppose to happen in the [docs](https://docs.godotengine.org/en/latest/tutorials/3d/spatial_material.html#no-depth-test)). and it's weird even in editor using GLES3.

**GLES2:**
Render Priority = 0
![bug](https://user-images.githubusercontent.com/12987951/55686757-18896980-595d-11e9-994b-994de6c41b7e.png)
Render Priority = -1
![bug_2](https://user-images.githubusercontent.com/12987951/55686762-250dc200-595d-11e9-8804-c8da6b23b1d0.png)
**GLES3**
Render Priority = 0 and the plane selected
![bug_3](https://user-images.githubusercontent.com/12987951/55686770-38209200-595d-11e9-9589-c397a933a223.png)
Render Priority = 0 and nothing selected
![bug_3_1](https://user-images.githubusercontent.com/12987951/55686781-55edf700-595d-11e9-81de-4f844cf7e27e.png)
Render Priority = -1
![bug_4](https://user-images.githubusercontent.com/12987951/55686782-61412280-595d-11e9-9020-f4f6edb22645.png)

**Comment by ATryder** [comment]
I whipped up a quick example project and a couple of GIFs.

**GLES3** (Expected behavior):
![RenderPriority_Bug_GLES3](https://user-images.githubusercontent.com/10942031/55687137-603cd080-591e-11e9-86c3-e6f8df67c7bc.gif)

**GLES2** (Unexpected behavior):
![RenderPriority_Bug_GLES2](https://user-images.githubusercontent.com/10942031/55687143-6f238300-591e-11e9-972c-68c272ef497a.gif)

**Example project**:
[RenderPriority_Bug.zip](https://github.com/godotengine/godot/files/3051843/RenderPriority_Bug.zip)
