### ISSUE TITLE
Allow to use Godot as a GUI frontend for python external code execution (Feature proposal).

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#27745]
Hi, I wonder if somehow godot could be used as a GUI frontend and have external calls to python code so we can use python libraries for diferent purposes, this could mean libraries like tensorflow or twitter api or whatever python library the user could set up in his system be available to the engine.

The users could even write external scripts for whatever they want.
That way we could make non game applications on godot very easily, maybe use external services like twitter, facebook, google maps api.

I would love to use this to call a tensorflow library so I can make a chatbot game and use godot GUI and art capabilities as front end.

**Comment by DleanJeans** [comment]
I've looked into this to experiment with AlphaGo-inspired game AI.

1. There's [Python for Godot](https://github.com/touilleMan/godot-python) but the [last release](https://github.com/touilleMan/godot-python/releases) was a year ago - working for 3.0.6 at least but not 3.1. We dunno or cannot expect when the next one's out. The developers here can't help much, I guess.

2. We can call a Python script from Godot with
```
var output = []
var pid = OS.execute('play.py', [], true, output)
```
which freezes the game (may be worked around with threading) with no way to send subsequent 
commands even with the PID, afaik.
[Same with opening the Python interpreter](https://godotengine.org/qa/43220/send-multiple-os-execute-commands):
```
var pid = OS.execute('python', [], true, output)
```

I believe this is where the devs here can step in.

**Comment by groud** [comment]
Yes, all of this is already possible with the python bindings.

However this is not really the place to ask question about how to use the engine, but to report bugs and ask for new features. Please ask on the other community channels if you need more advises (discord,  forum, Q&A...)

**Comment by groud** [comment]
Regarding the python binding issue, you can submit an issue on the bindings repository. Maybe the maintainers will update for 3.1
