### ISSUE TITLE
ClippedCamera does not work

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#27744]
The engine version is latest master.

ClippedCamera always display picture oriented from parent node. Changes to y value do something but not much. Can't maintain some distance. The setup is minimal - light source, a sphere as a parent and ClippedCamera. Looks like it considers itself as colliding even though there is nothing to be collided with.

**Comment by eon-s** [comment]
It does not work on stable either, that or it need some special undocumented setup to work as it is supposed to.
