### ISSUE TITLE
Can't rename Input Action

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27748]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
Can't see any option to rename an input action.

![image](https://user-images.githubusercontent.com/11199752/55676243-48763580-58a7-11e9-97d7-43a7824a2e30.png)

**Comment by CowThing** [comment]
The default `ui_*` actions won't be able to be renamed. But for custom actions it looks like there's no way to change their name without deleting and remaking them.

**Comment by rogeriodec** [comment]
> The default `ui_*` actions won't be able to be renamed. But for custom actions it looks like there's no way to change their name without deleting and remaking them.

Understood.
To rename custom actions, just double click on the name.
