### ISSUE TITLE
No exporting type working for IK structure from Blender 2.8 to Godot

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27746]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
I created this IK bone structure in Blender 2.8 and exported as `.escn` 

[![enter image description here][1]][1]

As you can see, in Blender it's working ok.
Now, how to use it in Godot?

I've tried export with:

 1. `.dae` (native)
 2. `.dae` (Better Collada)
 3. `.escn`
 4. `.glb`

None of them worked...

Is there any tutorial for using imported IK in Godot?

  [1]: https://i.stack.imgur.com/88Bku.gif

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zylann** [comment]
I once wanted to export spider legs from Blender too, where each part of the leg was an individual mesh, because I needed skeletal animation, not skinning at all. But it looks like Godot currently doesn't import that kind of stuff yet.

**Comment by rogeriodec** [comment]
Based on the example file passed by @AndreaCatania  here (https://github.com/godotengine/godot-docs/issues/2333), I discovered that actually the bones are being exported, but as Godot IK interface is still very primitive, for now I have to figure out its operation through trial and error.
