### ISSUE TITLE
HTML5: No Release Export available

### ISSUE THREAD

**Issue by Wend1go** [godotengine/godot#2774]
Currently it is only possible to export the debug version which includes the debugging console and emscripten logo inside the web page. The export option "enable debugging" doesn't do anything.

So I pledge for adding a release export template which only shows the actual game without anything else.

**Comment by reduz** [comment]
release export does release a more optimized binary that should run faster. The debug console is purely the template html. You are free to make your own html

**Comment by eska014** [comment]
The repository really should contain an HTML file that contains just the game without overhead. Everyone publishing a project on the web will want that eventually. And I don't think it's unreasonable to use it automatically when exporting in release mode (it's just a matter of packing the template, anyway).

Emscripten repo has a `shell_minimal.html` file, but it's even worse.

**Comment by reduz** [comment]
I don't have much html experience, so if anyone wants to write html
template files for Godot, that would be very welcome
