### ISSUE TITLE
String.count() method to count occurrences of substring

### ISSUE THREAD

**Issue by Mochnant** [godotengine/godot#27749]
I'd like to propose a str.count() method similar to the core Python version below.

> str.count(sub[, start[, end]])
> Return the number of non-overlapping occurrences of substring sub in the range [start, end]. Optional arguments start and end are interpreted as in slice notation.

_Source: https://docs.python.org/3/library/stdtypes.html_

**Comment by Chaosus** [comment]
https://github.com/godotengine/godot/pull/25090

**Comment by Mochnant** [comment]
Thanks, @Chaosus!  Sorry for missing that PR, glad to see it is already in progress.

**Comment by Chaosus** [comment]
Your welcome. No problem, it's a common mistake.
