### ISSUE TITLE
float and big numbers

### ISSUE THREAD

**Issue by TotallyNotAVirus** [godotengine/godot#27758]
Is this supposed to work this way? How big number I can store as float?
```
func _ready():
    var m : float
    m = pow(10, 100)
    print("1: ", m)
    m = max(0, m)
    print("2: ", m)
    m = pow(10, 50)
    print("3: ", m)
    m = float("1e50")
    print("4: ", m)
```

Output (Godot_v3.1-stable_x11.64):
```
1: 10000000000000000159028911097599180468360808563945281389781327557747838772170381060813469985856815104
2: inf
3: 100000000000000007629769841091887003294964970946560
4: inf
```

**Comment by Calinou** [comment]
In GDScript, floats are 32-bit whereas integers are 64-bit (since 3.0). There are long-term plans to allow using doubles (64-bit) in GDScript, see https://github.com/godotengine/godot/issues/288.

**Comment by TotallyNotAVirus** [comment]
> In GDScript, floats are 32-bit whereas integers are 64-bit (since 3.0). There are long-term plans to allow using doubles (64-bit precision) in GDScript, see #288.

But why then I can store numbers up to 2^1023 in float and 2^62 in int?

**Comment by toasteater** [comment]
Because floats are *float*ing point: the decimal point can move around, so you can store a larger range but with less precision.

**Comment by TotallyNotAVirus** [comment]
> Because floats are _float_ing point: the decimal point can move around, so you can store a larger range but with less precision.

I thought that numbers up to 2^1023 can't be stored in 32 bit floats, only in doubles.

**Comment by charliewhitfield** [comment]
According to docs, the output of max(), pow() and float() should all be floats. So how can 64-bit integers explain results for the example given?

(Following this closely as double-precision floats are essential for my project.)

**Comment by Zylann** [comment]
Float Variants are 64 bits: https://github.com/godotengine/godot/blob/master/core/variant.h#L144

**Comment by SeleckyErik** [comment]
Related issue: #27665

**Comment by groud** [comment]
Closing this issue, as the problem here is already covered by #288

**Comment by Zylann** [comment]
Is there a reason why Variant always uses `double` instead of `real_t`?
