### ISSUE TITLE
Add export hint for physics and render layers

### ISSUE THREAD

**Issue by theboyboy** [godotengine/godot#27753]
Something like this:
![image](https://user-images.githubusercontent.com/32691832/55678483-a1a29100-58c8-11e9-837d-fde685b5298d.png)
I know there is already a bitmask export, but being able to get an export specifically for the physics and render layers would be very useful. Example: setting up a collision mask for `intersect_ray()`

**Comment by DeadlyLampshade** [comment]
It is technically possible to add inspector elements that display Render and Physics layers, but doing so requires a tool script with a _get_property_list() override. Just saying because it would be totally easy to create an export hint that refers to these.

**Comment by jackwilsdon** [comment]
It'd be great if we could specify property hints for exports like the engine uses internally; https://docs.godotengine.org/uk/latest/classes/class_@globalscope.html#enum-globalscope-propertyhint
