### ISSUE TITLE
Display options doesn't work in GLES2

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#27757]
**Godot version:**
3.1 Stable

**OS/device including version:**
Zorin OS 12.04 core

**Issue description:**
Display options don't work on GLES2

**Steps to reproduce:**
- Fire up Godot
- Make sure is in GLES2
- Try to change the display options
- Nothing happens

![Bug](https://user-images.githubusercontent.com/27329423/55682007-60909800-592d-11e9-8080-fec8612b3bb4.jpg)

**Comment by clayjohn** [comment]
Thank you for the report. But there are already two open issues for this same bug. Please make sure to search the existing issues before submitting one. 

related: #26406, #27018

**Comment by groud** [comment]
Ah indeed, closing as a duplicate #27018
