### ISSUE TITLE
Image palette extraction and color quantization

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#27756]
**Godot version:**
3.2+

## Description

Image quantization results in a color palette being created. Such algorithms strive to build a palette that covers average colors, so extracted colors can be used to theme a game level/world/character based on an image alone, like adding specific visual effects the base colors of which need to match the overall look of a character. Some things can be done with a shader but propotional palette extraction requires clusterization which is a CPU task, so this might not even be suitable for GPU to handle via shaders. Moreover, the created (proportional) palette can be passed to shaders via uniforms to further style the game, so this can be deemed as the opposite to palette swapping.

[Color quantization wiki](https://en.wikipedia.org/wiki/Color_quantization)
[Palette wiki](https://en.wikipedia.org/wiki/Palette_(computing))

![color_palette_extraction](https://user-images.githubusercontent.com/17108460/55681441-6c7d5980-592f-11e9-83d9-369a6977d411.png)

*[This online service](https://labs.tineye.com/color/) was used to create this example.*
*The character taken from [here](https://opengameart.org/content/animated-character).*

When I load an indexed image with a palette, it seems like Godot can handle that already. Either way, I need this feature and I think will try to come up with something, either within `Image` class directly or as a separate module, so I just wonder whether people find this useful.

### Proposed interface:
```cpp
void quantize(int num_colors); // indexed

PoolColorArray get_palette();
void set_palette(const PoolColorArray &palette);
```

## Other use cases
In particular, I need an ability to reduce the number of colors in any image to <256 colors at run-time (having in-game editor for that). The use case is mainly legacy support to have cross-game compatible user-generated content, but I see there are a number of issues opened for other use cases:

#18662, #18269: color reduction, palette creation.

Marginally connected or features that need to be implemented to benefit from this feature fully:
#1315, #10751:
* color palette is a `PoolColorArray` that could be passed to shaders once retrieved from an image.

#9623: color replacement, palette swapping (**note**: use shaders instead)

## Implementations

Found [this](https://github.com/exoticorn/exoquant) MIT library for color quantization that I think would be relatively easy to integrate, but perhaps the algorithms are not that difficult to rewrite them in Godot natively? The library can handle images with alpha channel as well.

**Comment by aaronfranke** [comment]
Are you talking about [Posterization](https://imgs.xkcd.com/comics/random_number.png)?

**Comment by groud** [comment]
I don't think this should be built in. Most image editing software can do that easily and it could be done with a simple shader too.
I think it better fits a plug-in.

**Comment by Xrayez** [comment]
I'm not necessarily talking about palette swapping as it's clearly doable with a shader. Same goes for posterization. 

If Godot handles loading of indexed images, **it should also provide an interface to at least retrieve the color palette associated with it**, so these colors could be looked up and used for theming as most of the time such palette will have an average/ordered distribution of colors. For instance, one could find a dominant color in such image by fetching a first color in palette, and least dominant color by fetching last color in palette (assuming colors are ordered and constructed according to distribution).

Using image editing software doesn't allow to theme a game if assets are loaded externally by users, so this needs to be done at run-time, before a game starts. Shaders can be overkill for this because I believe colors from a palette could be applied to anything, not only sampling a texture and changing pixels in fragment shader.

Color quantization is a means to create and get such palette from a arbitrary image, which doesn't necessarily means changing the palette in the image.

**Comment by Xrayez** [comment]
Implemented as part of [ImageTools](https://github.com/Xrayez/godot-imagetools) module via `ImageIndexed` class as `generate_palette` method, GDNative module for purely image color quantization might be available at some point once I figure out the build process. Closing.
