### ISSUE TITLE
Reading project settings in a module

### ISSUE THREAD

**Issue by deepmax** [godotengine/godot#27761]
**Godot version:** 3.1

Writing a custom module in C++, everything goes OK except reading project settings. Inside the module I'm trying to read a property as below:

`ProjectSettings::get_singleton()->get("display/window/size/height")`

but the returned value is a random number.

**Comment by EIREXE** [comment]
Are you sure it's not just returning an address?

**Comment by deepmax** [comment]
Base on Godot's source code, the returning type of `get` is a `Variant`:

`Variant get(const StringName &p_name, bool *r_valid = NULL) const;`

**Comment by deepmax** [comment]
I closed this because in my tests, I executed a script file and there was no settings (however it is strange), but having a regular project then there is settings.
