### ISSUE TITLE
Running --gdnative-generate-json-api on integrated graphics doesn't search for supported OpenGL version

### ISSUE THREAD

**Issue by Shadow1Raven** [godotengine/godot#27768]
**Godot version:**
3.1

**OS/device including version:**
Linux Mint 19.1 (Tessa), Kernel 4.15.0-46
An integrated Intel graphics chip (of the P6100 processor, so it's an Ironlake GPU) with i915 as a kernel module.

**Issue description:**
Running Godot with `--gdnative-generate-json-api api.jsn`, I was expecting it to generate the json-api and dump it into `api.jsn`. Instead, a message was shown:

> Your video card driver does not support any of the supported OpenGL versions.
> Please update your drivers or if you have a very old or integrated GPU upgrade it.

However, running the program without any parameters went fine, probably because it switched to OpenGL ES2 automagically.

**Steps to reproduce:**
Perhaps anything that doesn't support OpenGL 3 won't work? Just running Godot with `--gdnative-generate-json-api <file-name>` should fail.

The problem can be fixed by manually adding `--video-driver 'GLES2'` to the command line, so perhaps the only thing necessary is to make sure the user knows that changing the video driver is possible, although it may not help everyone.

**Comment by Zylann** [comment]
I wonder why on Earth would graphics matter for Godot to generate this json file. Could Godot just not open a window at all?

**Comment by aaronfranke** [comment]
@Zylann I've also noticed that it's impossible to generate the Mono glue when building Godot with Mono support on headless Linux systems due to Godot needing to open a window. It does seem that certain operations could be done without opening a window at all, so Godot should probably be changed to check for such things before opening a window.
