### ISSUE TITLE
TextEdit font selected color not work

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#27760]
The TextEdit's theme property font_color_selected cant be setup, whether use code or edit the custom colors or edit the theme, the color just keep the font color after it's been selected, others color work fine, and the color selected in the lineEdit works too.

**Comment by groud** [comment]
There is an issue template, could you please fill it in ? We need the Godot version, and when you can a video/screenshot of the problem.

**Comment by xarrynator** [comment]
I'm still experiencing this bug on 3.2.1 on Windows 10, even though it seems fixed in the sourcecode. Granted, I didn't compile the Engine myself... Is there a possibility that the wrong files were included when compiling the Windows binary or something like that?
