### ISSUE TITLE
C# File class Open functions use int instead of enum

### ISSUE THREAD

**Issue by ForLoveOfCats** [godotengine/godot#27772]
**Godot version:**
Godot Mono 3.1 Beta 11

**Issue description:**
Currently the methods to open files with the C# version of the `Godot.File` class use an int instead of the enums (which are in the same class) for open mode and compression mode. I would like to fix this but I cannot find the source for this class in the repo. I'm assuming that this means that this class is automatically generated during the build process (when generating the glue?). Where should I start to fix this?

**Comment by ForLoveOfCats** [comment]
Dang it neikeq :laughing: I was hoping to fix this! I guess it was just easier for you to fix it instead of explain what to change and why. Glad it is being fixed!

**Comment by neikeq** [comment]
I was going to, but found a few other cases so it was quicker to just fix them directly :stuck_out_tongue:
