### ISSUE TITLE
convert xml scenes to scn at compile time

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#2778]
I would like if the scenes were created in XML and converted to automatic scn at compile time  as gd and gdc

**Comment by hetdegon** [comment]
This could be pretty convenient. Or a way to bulk export xml/xscn to scn easily.

**Comment by akien-mga** [comment]
Yes that would be a cool feature since apparently the SCN is more performant, but XSCN or the upcoming TSCN are way better for source control and for working in teams generally speaking. So it would be very nice to be able to do the conversion at the export time directly.

**Comment by volzhs** [comment]
:+1:

**Comment by reduz** [comment]
with the new renaming tool, it should be easy to modify it to do this,
specially given I really want to remove support for xml in the future

**Comment by akien-mga** [comment]
> with the new renaming tool, it should be easy to modify it to do this,
specially given I really want to remove support for xml in the future

Just to clarify, this feature request here is not just for a possibility to mass convert from XML to SCN, but to do it only when exporting the game; the source file would stay in XML, or once the TSCN and TRES format have been completed, in those formats.

**Comment by reduz** [comment]
yeah, one of the reasons about TSCN is that it should be easier to do this,
given it's easier to parse. Right now opening and saving a xml scene would
also open all the dependencies, when instead we just want a simple
converter. When the loader is written, I will write it so it can be used to
simply convert from .tscn to scn

**Comment by akien-mga** [comment]
Note that what is requested here was apparently implemented in this unmerged PR: #461.

**Comment by akien-mga** [comment]
Fixed in da113fe4. (still need to test it though, but we'll open new tickets if there are issues with the current implementation)
