### ISSUE TITLE
Line2D - Call function to insert point between points using GDScript

### ISSUE THREAD

**Issue by tree786** [godotengine/godot#27786]
**Issue description:**
Feature proposal.
It would be nice to call a GDScript function which adds a point to a Line2D at a specified index. Currently, using the **add_point(Vector2())** function appends the point to the end of the Line2D list, and it does not allow you to choose at which index to insert (forcibly appends to the end of the list). However, something like **insert_point(index, position)** would be useful. The code below hopefully illustrates the idea further:

func _ready():
  
    var updated_list=[Vector2(...),Vector2(...), etc.] #contains updated values

    for i in range(get_point_count()):
        remove_point(i) #to remove points

    for i in range(len(updated_list)):
       add_point(updated_list[i]) #to construct the Line2D using the updated points

**Comment by Zylann** [comment]
You can get the list of points with the `points` property, which returns a `PoolVector2Arrray`. You can insert stuff the way you like in it, and then set it back on the property.

```gdscript
	var updated_list = points
	updated_list.insert(1, Vector2(100, 100))
	points = updated_list
```

**Comment by tree786** [comment]
> You can get the list of points with the `points` property, which returns a `PoolVector2Arrray`. You can insert stuff the way you like in it, and then set it back on the property.
> 
> ```gdscript
> 	var updated_list = points
> 	updated_list.insert(1, Vector2(100, 100))
> 	points = updated_list
> ```
> 
> Otherwise, there could be an optional argument to `add_point` (defaulting to -1 for "append"), which could allow to specify the index. This would be consistent with the `Curve2D` API.

Thanks a lot for that, I didn't know it was possible to create using the _points_ parameter. I agree, adapting the_add_point_ function to take two arguments which allow index and position to be specified would be handy, like _add_point( int index, vec2 position)_
