### ISSUE TITLE
Selection issue in AnimationPlayer editor plugin

### ISSUE THREAD

**Issue by ZEkA10000** [godotengine/godot#27780]
Godot version: 3.1.stable.official

Windows 7 Home Premium (x86)

I can't move cursor above Animations window if I pressed for selection

![qNOGZ8ab9P](https://user-images.githubusercontent.com/25690631/55688108-a83f1000-597d-11e9-9657-ffc04f7dc166.gif)

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987 (on Linux).

Note that this bug doesn't occur if you move the cursor outside the editor window then back in (while holding the left mouse button).

**Comment by KoBeWi** [comment]
Still valid in c844cc8
