### ISSUE TITLE
"Lock edit" and "Lock selection" node icons doesn't update location right after node position is changed

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#27795]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 7 x64

**Steps to reproduce:**
1. Do "Lock edit" and "Lock child selection" for node,
2. Change node position using Inspector

**_Result_**: node position changed, but both "Lock" icons remains in the same place. They will change position only after scene redraw (ex. move mouse on scene)

**_Expected_**: "Lock" icons change their position immediately after node position was changed
![bug5](https://user-images.githubusercontent.com/1552169/55699913-a2751900-59d5-11e9-8918-01efb84fbca5.gif)

**Comment by KoBeWi** [comment]
This seems to apply to all editor gizmos. When you make a Node2D and move it this way, it won't move visually until the viewport is updated.
