### ISSUE TITLE
Sky contribution being ignored

### ISSUE THREAD

**Issue by kaadmy** [godotengine/godot#27797]
**Godot version:**
Godot v3.1-stable (GLES3)

**OS/device including version:**
```
OS: Arch Linux x86_64
Kernel: 4.19.4-arch1-1-ARCH
GPU: NVIDIA GeForce 940MX
GPU: Intel HD Graphics 620 (secondary, unused)
```

**Issue description:**
Sky contribution/energy for ambient light in a `WorldEnvironment` doesn't seem to work properly anymore (sky is still used for ambient light even with both set to zero and the color is black.)

This could be the correct behaviour, but if I remember correctly, this behaved differently in 3.0.

**Steps to reproduce:**
1. Create "3D Scene".
2. Add `MeshInstance` with a `CapsuleMesh`.
3. Add a `WorldEnvironment`.
4. Give the new `WorldEnvironment` a new `Environment`.
5. Set the background mode to "Sky", and give the background a new `ProceduralSky`.
6. Set the new `ProceduralSky`'s sky top color to bright red or something obvious.
7. Set the `WorldEnvironment`'s ambient energy and sky contribution to zero.

The capsule is still lit by the sky even though it should be totally disabled.

However, changing the sky energy affects the ambient light.

**Minimal reproduction project:**
![sky_ambient](https://user-images.githubusercontent.com/14076345/55701145-e3920c80-5986-11e9-9ccd-0ff5f5d4811c.png)
[sky_ambient.zip](https://github.com/godotengine/godot/files/3052772/sky_ambient.zip)

**Comment by clayjohn** [comment]
Thanks for the report! 

But this isn't actually a bug. This is how PBR works. What you are seeing is actually specular reflectance and not ambient light. If you dont want any specular reflectance turn specular to 0 in your SpatialMaterial. 

You'll also notice that if you turn roughness all the way down there is no ambient light, it is a pure reflection of the sky.

**Comment by kaadmy** [comment]
Ah okay, I was just curious since I remembered this working differently in 3.0.

**Comment by jknightdoeswork** [comment]
Hi there. Turning specular reflectance to 0 does not resolve this issue.
