### ISSUE TITLE
particles2d material angle property is not "initial"

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27794]
**Godot version:**

3.1

**OS/device including version:**

any

**Issue description:**

ParticleMaterials `Angle` property claims to determine the initial angle of an emitted particle. However this is not the case. https://cdn.discordapp.com/attachments/540803169374961664/564662350213283851/unknown.png

This makes many particle effects in Top Down quite difficult to achieve. For example footprints, which need to point in the direction the actor is moving.

**Steps to reproduce:**
Create a script that manually changes the angle of a ParticleMaterial (like following the rotation of its parent.) All currently active particles will copy this rotation, instead of simply deriving their initial rotation from it.

```GDScript
tool
extends Position2D

onready var right: ParticlesMaterial = $Right.process_material
onready var left: ParticlesMaterial = $Right.process_material

func _ready():
	print("hey")


func _process(delta) -> void:
	right.angle = -global_rotation_degrees
	left.angle = -global_rotation_degrees
```

![image](https://user-images.githubusercontent.com/44248915/55698429-055eb400-59c6-11e9-81aa-bf4f7ed41ade.png)

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
I guess the description should be updated. Initial in this context doesn't mean "when the particle is emitted" it means "angle before other rotations are applied". It is actually used to set "base_angle" in the ParticlesMaterial.

The line is found here:
https://github.com/godotengine/godot/blob/f52c294a748e4bc4e561fb497480560aacda2d59/scene/resources/particles_material.cpp#L467

Keep in mind that uniforms to shaders apply to all particles at once. 

I think the best way to achieve your effect is to turn local_coords off and then make your particle system a child of the thing you want it to follow, or at least set the Particles2D node's position and rotation to what you want.

**Comment by TheDuriel** [comment]
Yes, rewording the description seems apt then.

> I think the best way to achieve your effect is to turn local_coords off and then make your particle system a child of the thing you want it to follow, or at least set the Particles2D node's position and rotation to what you want.

Unfortunately this is not a viable solution for trails that need each individual particle to keep pointing in the correct direction. Particles in general do not inherit their emitters rotation. (In local coords they simply orbit their parent.)

**Comment by TheDuriel** [comment]
Lets close this in favor of https://github.com/godotengine/godot/issues/27878 and https://github.com/godotengine/godot-docs/issues/2359
