### ISSUE TITLE
Display version number on the interface at all times by default

### ISSUE THREAD

**Issue by mrbig033** [godotengine/godot#27811]
As a beginner, I'm having trouble following tutorials because subtle differences between versions create errors and uncertainty that could be easily avoided if I were able to reproduce their exact environment. This is a problem for noobs because our debugging skills are not very high yet. I [posted on Reddit](https://old.reddit.com/r/godot/comments/banp5k/suggestion_to_tutorial_makers_always_state_the/) about this and the thread got some traction. Ideally, tutorial makers should inform the version of Godot they are using, but if the version number was displayed by default the problem would be instantaneously solved.

**Comment by Calinou** [comment]
What would be a good location in the editor window to display the version number? Any mockup suggestions? :slightly_smiling_face:

**Comment by Megalomaniak** [comment]
As per #28946 The editor title.

**Comment by Calinou** [comment]
@Megalomaniak I thought about it as well, but I'm not sure if it's the best location since the window title can be hidden in many cases (e.g. if the window is made fullscreen or borderless by the user, which might be the case when people record tutorials).

**Comment by Megalomaniak** [comment]
Then perhaps in front of the renderer selection, so it would say for an example `Godot 3.2 GLES2` With GLES2 being the selector menu?

**Comment by mrbig033** [comment]
> What would be a good location in the editor window to display the version number? Any mockup suggestions?

Maybe around here:

![godot-suggestion](https://user-images.githubusercontent.com/36245777/58752078-06203d80-847f-11e9-9c0a-3b17fd5d759e.jpg)

**Comment by bojidar-bg** [comment]
What about here? (with clip_contents on, so that it won't cause size-related bugs on small screens)
![image](https://user-images.githubusercontent.com/5276727/58882143-4a604780-86e4-11e9-8d35-608f98a9c687.png)

**Comment by Calinou** [comment]
I'd like to use the top-right corner for this, as it's the same location as in Blender (so people know where to look at).

**Comment by Megalomaniak** [comment]
* So Blender users know where to look.
