### ISSUE TITLE
Onion skinning doesn't work with Skeleton2D

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot#27819]
When using 2d mesh deformation and Skeleton2D, the onion skinning feature replicates the current time step/frame in the past and in the future:

![Screenshot from 2019-04-08 19-45-44](https://user-images.githubusercontent.com/12694995/55745173-ed734880-5a36-11e9-9a59-489aafd6b077.png)

**Comment by akien-mga** [comment]
Fixed by #29109.
