### ISSUE TITLE
steam_api is not work when use lib crypto in Linux

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#2781]
I write steam api module,
When I run Godot app with Steam client open the app is terminate, message in console show:
```Segmentation fault (core dumped)```

It because importing lib crypto, I must set ```openssl=no``` when use scons compile for resolve it.

In Windows it has no problem.

**Comment by reduz** [comment]
yeah i guess this is expected to happen and openssl=no is the right solution

**Comment by akien-mga** [comment]
If you build Godot in the steam runtime directly, I guess it might work better as it would link against Steam's openssl.
