### ISSUE TITLE
packetScene BUG breaks scene

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#27829]
**Godot version:**
![2019-04-08 21_48_24-Godot Engine - FlappyBird3D - Escena_principal_lista tscn](https://user-images.githubusercontent.com/12847027/55765853-1ea84480-5a48-11e9-9a5b-dd3386b2c753.jpg)

**OS/device including version:**
windows 7, core2quad, 8gbram, geforce9800gt

**Issue description:**
The scene is broken

**Steps to reproduce:**
https://youtu.be/D-L0Y_etPoo

**Comment by groud** [comment]
Duplicate of #23705

**Comment by reduz** [comment]
We had a long thread in the Facebook group some weeks ago about how to report these issues, yet you completely dismiss and do whatever you want.

Tuvimos un una discusion muy larga en Facebook hace unas semanas respecto a como reportar bugs si no entendes ingles. Vos participaste asi que estas al tanto. Por favor hace las cosas como corresponde, llena todos los campos, inclui un proyecto que se rompe y uno con una escena rota. Escribilo en castellano y luego pega en ingles una traduccion de Google.

**Comment by kone9** [comment]
> We had a long thread in the Facebook group some weeks ago about how to report these issues, yet you completely dismiss and do whatever you want.
> 
> Tuvimos un una discusion muy larga en Facebook hace unas semanas respecto a como reportar bugs si no entendes ingles. Vos participaste asi que estas al tanto. Por favor hace las cosas como corresponde, llena todos los campos, inclui un proyecto que se rompe y uno con una escena rota. Escribilo en castellano y luego pega en ingles una traduccion de Google.

ok
