### ISSUE TITLE
Can't rename bone in imported scene

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27827]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
Renaming a bone is not working.

**Steps to reproduce:**
1) Open the attached project
2) Click "skeleton"
![image](https://user-images.githubusercontent.com/11199752/55763330-d7688680-5a3c-11e9-9c26-35f6e04a45ff.png)
3) Try to rename the first bone...
![image](https://user-images.githubusercontent.com/11199752/55763352-ef400a80-5a3c-11e9-90e7-77dc81c0c358.png)
... to any name...
![image](https://user-images.githubusercontent.com/11199752/55763368-00891700-5a3d-11e9-9323-b91fee4db52a.png)
4) Click on any other node and click again on "skeleton" node. The new name was not kept.
![image](https://user-images.githubusercontent.com/11199752/55763402-231b3000-5a3d-11e9-9e77-5319dd222ffa.png)

**Minimal reproduction project:**
[bone.zip](https://github.com/godotengine/godot/files/3056582/bone.zip)

**Comment by rogeriodec** [comment]
I don't think this is just an enhancement, but a bug...

**Comment by JohnJLight** [comment]
Looks like a bug for sure, I'll give it a shot.

**Comment by JohnJLight** [comment]
We have a partial fix, the name will update in the skeleton node interface that you showed pictures of but it will not update on the scene GUI on the left of the editor

**Comment by KoBeWi** [comment]
Fixed in 4.0
The name is no longer editable in the new bone view, so it doesn't appear bugged.
![image](https://user-images.githubusercontent.com/2223172/90827025-c7a0c800-e33b-11ea-981a-38af399f6beb.png)
(bones are nodes of inherited scene, so it's expected that you can't rename them)
