### ISSUE TITLE
debug_parse_err_line >= 0 ' is true. returned: __null

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#27824]
Using the latest Godot, 3.1, 16.04

Testing a very simple script just for the sake of testing how to implement a turn based game in Godot

```
extends Node2D

class_name TurnQueue

var active_character

func initialize():
	active_character = get_child((0)
	
func play_turn():
	yield(active_character.play_turn(), "completed")
	var new_index : int = (active_character.get_index() +1) % get_child_count()
	active_character = get_child(new_index)
```

I get

```
E 0:00:00:0206   Condition ' _debug_parse_err_line >= 0 ' is true. returned: __null
  <C Source>     modules/gdscript/gdscript_editor.cpp:321 @ debug_get_stack_level_instance()
```

![godot](https://user-images.githubusercontent.com/660142/55755013-9ed5a680-5a56-11e9-8516-20d8e2877e56.png)

**Comment by akien-mga** [comment]
Check the Output dock and the same error repeated in the script editor. You are missing a parenthesis on line 8.

**Comment by elieobeid7** [comment]
damn I'm a blind man, thank you
