### ISSUE TITLE
"Revert Scene" does nothing.

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#2782]
The Scene > Revert Scene option seems to not work anymore.
If I make a trivial change in a scene (such as hiding an element) and try to revert, it'll make no change, leaving the hidden element still hidden. There isn't much to say, no visible errors or anything, the scene just doesn't revert. 
Seems some others have encountered this problem, but since there was no open issue, better to have it here.

Using latest trunk version, on Ubuntu 15.10 64b.

**Comment by akien-mga** [comment]
I can confirm in the latest git HEAD.

**Comment by akien-mga** [comment]
I can confirm that it works now :)
