### ISSUE TITLE
CubeMap support for environment sky

### ISSUE THREAD

**Issue by GammaGames** [godotengine/godot#27835]
**Godot version:**
3.1 Stable

**Issue description:**
Considering there is already a cubemap resource (used for reflections) it would be handy if there was the option to use a cubemap resource for a WorldEnvironment's `background_sky` value.

**Comment by LinuxUserGD** [comment]
Removed in Godot 3.0 (was there in 2.1).

**Comment by Calinou** [comment]
Readding a CubeMap resource would make it possible to implement projector textures for OmniLights, as these use cubemap shadows by default.

**Comment by GammaGames** [comment]
Hm, I wonder why that was done

**Comment by Calinou** [comment]
@GammaGames I can think of two reasons:

- Reflections use a dual parabolid system, so a conversion has to be done if using a skybox.
- Cubemaps are difficult to get right due to how they are mapped/rotated across different software. Moreover, it's quite tedious having to load 6 textures instead of just one.

**Comment by GammaGames** [comment]
> Reflections use a dual parabolid system, so a conversion has to be done if using a skybox.

I expected that it would have to be converted before runtime to make it work better. I guess that would potentially cause warping or something, which is understandable.

> Cubemaps are difficult to get right due to how they are mapped/rotated across different software. 

That was actually the reason I was looking for the feature. Some users were looking to use some textures exported from spacescape and convert it with an online program but it was all messed up. It's current really tedious to convert and test, but if we had the option to easily use the separate textures it would allow users to rotate and the images to get the expected result.

**Comment by LinuxUserGD** [comment]
Aren't HDR images rendered as cubemaps in GLES2? I think Godot should be capable to do this the other direction: Convert a cubemap to HDR for GLES3.

**Comment by GammaGames** [comment]
Probably, I used [cube2sphere](https://github.com/Xyene/cube2sphere) which uses blender and python but it was [really blurry](https://gfycat.com/KindheartedBoringDipper)

**Comment by LinuxUserGD** [comment]
@GammaGames Use the standard blender cube and assign a material to each face with a seperate texture. Using cycles you can define the quality yourself (how many time it takes to render the image). You don't need an addon for that. https://youtu.be/a48PBPRO8O8

**Comment by Galaxy613** [comment]
Yeah cube2sphere is not a solution for me. Please bring cube maps back.

**Comment by clayjohn** [comment]
@Galaxy613 There are plenty of resources to convert cubemaps to equirectangular. 

You can even do it yourself in GDScript. See reddit comment here
https://www.reddit.com/r/godot/comments/baw27a/how_to_use_spacescape_skybox_in_godot/ekfvrwo?utm_medium=android_app&utm_source=share

**Comment by Galaxy613** [comment]
@danilw has added a very helpful page to their GitHub.io page: https://danilw.github.io/GLSL-howto/cubemap_to_panorama_js/cubemap_to_panorama.html (GitHub link here: https://github.com/danilw/GLSL-howto)

**Comment by danilw** [comment]
(not self promotion)
super simple javascript cube to panorama convert online [link (single html+shader)](https://danilw.github.io/GLSL-howto/cubemap_to_panorama_js/cubemap_to_panorama.html) (can save up to 4k resolution panorama)

**Comment by Calinou** [comment]
@Zireael07 Not that I know of. I don't know if this is planned for 4.0, but I doubt it as dual parabolid skies are considered the standard nowadays.

**Comment by RichardEllicott** [comment]
yeah the thing is people give out a lot of technical explanations, but some of us where working happily with assets and using this method (and i was waiting thinking it'd come back)

i particularly like how you could edit a planet into the middle of the image, and it would not require any more processing or editing (i could just use gimp).... i would suffer no corner distortion on re-editing this as long as i stayed away from the corner

making the method very flexible (i'd also have different planets to plop in the one of the 6 faces, and reuse the stars from other angles)

there is no mention of "dual parabolid skies" being standard, i don't even think most CG artists know about this (they use panoramic mostly)

so this was a technique i am fond of, and all the competition still has the option

**Comment by Calinou** [comment]
> there is no mention of "dual parabolid skies" being standard, i don't even think most CG artists know about this (they use panoramic mostly)

I think these are the same thing :slightly_smiling_face:

**Comment by RichardEllicott** [comment]
"I think these are the same thing 🙂"

nah, the "dual parabolid skies", they have two circles as their image:

http://cdn.imgtec.com/sdk-documentation/Dual+Paraboloid+Environment+Mapping.Whitepaper.pdf

so the word "dual"

**Comment by clayjohn** [comment]
Godot uses dual paraboloid internally, but it expects an equirectangular (AKA panorama) map from users. Most HDRIs come in equirectangular format nowadays. Plus they are way simpler to import. Finally, it is not a lot of work to just convert your cubemap to an equirectangular before import, there are plenty of tools out there to do it (see danilw's post above https://danilw.github.io/GLSL-howto/cubemap_to_panorama_js/cubemap_to_panorama.html)

**Comment by LinuxUserGD** [comment]
For quick equirectangular rendering in Blender (or conversion from cubemap) there is also https://github.com/EternalTrail/eeVR which uses Eevee instead of Cycles (mentioned in https://blenderartists.org/t/will-eevee-support-vr-equirectangular-rendering/699631/37 )

**Comment by mhilbrunner** [comment]
Closing as per the discussion above. Thanks for taking the time to open the issue. :)

**Comment by danilw** [comment]
look like you guys have added my "not best" converter to your docs...
il add more info about the method with link to Godot-example project with same code, to that page then...

**Comment by Shadowblitz16** [comment]
@mhilbrunner  please reopen this space backgrounds are a pain in the ass and there are no good tutorials on how to do it

**Comment by Calinou** [comment]
@Shadowblitz16 Feature proposals should now be made on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.

Also, you can very much have space backgrounds with panorama skies.

**Comment by Shadowblitz16** [comment]
thats the issue thought I don't want distortion and I don't want to have to hide anything
thats just bad design on godots end
