### ISSUE TITLE
Shader lang API in Help tab

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#2783]
It would be nice to make section for Shader lang in our Help tab, listing built-in variables, functions and maybe also datatypes.

Currently user can find info about it only on wiki.

**Comment by reduz** [comment]
let's do this in 3.0, as API will most likely change

**Comment by reduz** [comment]
kicking for 3.1, plate full..

**Comment by Chaosus** [comment]
kicking to 3.2 :(

**Comment by KoBeWi** [comment]
There's now a help menu in Shader Editor:
![image](https://user-images.githubusercontent.com/2223172/64855451-2b951980-d620-11e9-9270-7c8566817c92.png)

Does it resolve the issue? It's not offline, but it's easily accessible.

**Comment by Chaosus** [comment]
I guess the TC wants a full-featured in-bound help, similar to one for GDScript...

**Comment by clayjohn** [comment]
Implemented in https://github.com/godotengine/godot/pull/31033 so closing. :)
