### ISSUE TITLE
Make export paths relative

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#27849]
**Godot version:**
3.1

**Issue description:**
Every export preset has now an export path. However the path is absolute, which makes it useless on shared projects (and is a valid reason to add export settings to .gitignore, like it used to be). It would be probably better if the path was relative to project's path.

**Comment by SiberianCatz** [comment]
Yes, I want this to happen too. I also noticed that with shared projects.

**Comment by NathanWarden** [comment]
I agree, it's a little annoying to have to remove these lines before committing the export_presets.cfg file.

My personal preference is that these lines wouldn't be in this file at all but rather in a .config file that could simply be ignored in the ignore file. It's pretty likely that two different team members want to build to separate locations intentionally. IE. QA might want to build it to a completely separate drive, whereas I might want to just build them to the same folder.

Nevertheless, the relative path shouldn't be relative to res:// but should be relative to the project root folder. So, if it was one directory up in a bin folder it would be "../bin/export.exe"

**Comment by SonerSound** [comment]
Since I'm interested in working on this and no one seems to be updating this with progress, I'll take this on! I work full time though, so I'm expecting this to be done in around 2 weeks or so.

**Comment by avencherus** [comment]
@KoBeWi Yeah, the export templates are also absolute paths, so for that reason at least, I .gitignore the export configs.
