### ISSUE TITLE
Non-tools builds should not export

### ISSUE THREAD

**Issue by fire** [godotengine/godot#27858]
**Godot version:**
5772f60f960ee8c396574f0c6f94def18bb210c7

**OS/device including version:**
windows 10

**Issue description:**
Block non-tools builds from exporting.

During the discussion about server vs headless builds, the idea for blocking non-tool build exports was mentioned by TMM.

Non-tool build exports aren't expect to work.

**Comment by akien-mga** [comment]
Non-tools builds can't export, so not sure what should change :)
https://github.com/godotengine/godot/blob/master/main/main.cpp#L281-L283

**Comment by fire** [comment]
:D
