### ISSUE TITLE
Shortcut to open recently closed script/scene

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#27851]
**Godot version:**
3.1

**Issue description:**
When you close a script/scene, there's no way to restore the tab quickly. You need to manually open the file. There should be a shortcut to open recently closed scripts/scenes like you can do e.g. in web browsers. There's one for recently opened, but it only works when you open something, not when you load a project with already opened stuff.

**Steps to reproduce:**
1. Accidentally close something :(

**Comment by Kanabenki** [comment]
Something like Undo Close Tab above Close Tab when right clicking on a scene/script tab (similar to most web browsers) could be a good fit.

**Comment by golddotasksquestions** [comment]
Generally it would be nice to know what can be undone and cannot be undone. https://github.com/godotengine/godot/issues/25919
If we had a proper project undo log, maybe it would also make sense to have two proper undo logs, one for any project related action (changing, adding or removal of components, code assets ect) and one for all editor related actions (positioning https://github.com/godotengine/godot/issues/25920 and sizing of panels, opening and closing of panels, scripts, scenes, ect)

**Comment by KoBeWi** [comment]
Sorry, but reopening :/

This issue was about scripts too, not only scenes.
