### ISSUE TITLE
RichTextLabel is missing push_bold() and push_italic()

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#27850]
**Godot version:**
3.1

**Issue description:**
See title. RichTextLabel already has stuff like `push_color()` and even `push_underline()`, so not sure why bold and italic tags are omitted.

**Comment by bruvzg** [comment]
Bold and Italic are handled by `push_font`.

**Comment by KoBeWi** [comment]
I noticed that, but you need to provide font, which is inconvenient. If anything, `push_bold()`/italic could internally call `push_font()` with assigned bold/italic font.
