### ISSUE TITLE
C++ API vs documentation

### ISSUE THREAD

**Issue by mudlee** [godotengine/godot#27855]
I've been evaluating godot with C++ for few days now, and I have a returning problem. For example, I'd like to move a 2D character, with move_and_slide.  The parameters in the doc (https://docs.godotengine.org/en/3.1/classes/class_kinematicbody2d.html#class-kinematicbody2d-method-move-and-slide)  differs from the parameters what I read in the c++ api code (`Vector2 KinematicBody2D::move_and_slide(const Vector2 linear_velocity, const Vector2 floor_normal, const bool infinite_inertia, const double slope_stop_min_velocity, const int64_t max_bounces, const double floor_max_angle) {`)

I tried to follow the code I found in the C++ api, but the game just stops, so I may be misread something. So now I ask two questions:

1: is it the proper way to do things in C++?
2: is there any doc, how can I see stack trace using c++ when the game fails to run?

**Comment by Zylann** [comment]
1) The C++ side of Godot is very similar to the scripting API but may have some extras or differing names. Usually you can do things the same way, but because C++ is not GDScript/C# there can be some differences related to the language and the fact you *could* use more internal functionality.

2) You can see a stack trace using a normal C++ debugger, like GDB or Visual Studio debugger (or even in QtCreator with CDB backend).

3) Which "C++" are you actually writing? Are you writing a module (forking Godot) or using GDNative?

**Comment by mudlee** [comment]
Hi, thank you for the info, all clear and helpful. I'll try all of those out :)

3: I'm using GDNative

Something like this, but currently it fails:

```c++
void PlayerController::_physics_process(float delta){
    Vector2 motion = Vector2();
    motion.y += GRAVITY;

    if(Input::get_singleton()->is_action_pressed("move_right")){
        motion.x += SPEED;
    }
    else {
        motion.x = 0;
    }

    move_and_slide(motion, Vector2(0,-1), true, 0.0, 4, 0.785398);
}
```

I think the issue can be closed.

**Comment by Zylann** [comment]
Oh, I thought you were coding a module.
If you use GDNative, then the API should just be the same as the script API, with some adjustments to work with C++. If something fails, try it in GDScript, and if it also fails then perhaps the issue isn't GDNative.

**Comment by mudlee** [comment]
Well.

This is the method in the compiled KinematicBody2D.cpp:
```c++
Vector2 KinematicBody2D::move_and_slide(const Vector2 linear_velocity, const Vector2 floor_normal, const bool infinite_inertia, const double slope_stop_min_velocity, const int64_t max_bounces, const double floor_max_angle) {
	static godot_method_bind *mb = nullptr;
	if (mb == nullptr) {
		mb = godot::api->godot_method_bind_get_method("KinematicBody2D", "move_and_slide");
	}
	return ___godot_icall_Vector2_Vector2_Vector2_bool_float_int_float(mb, (const Object *) this, linear_velocity, floor_normal, infinite_inertia, slope_stop_min_velocity, max_bounces, floor_max_angle);
}
```

And this is in the GDScript documentation:
```python
Vector2 move_and_slide ( Vector2 linear_velocity, Vector2 floor_normal=Vector2( 0, 0 ), bool stop_on_slope=false, int max_slides=4, float floor_max_angle=0.785398, bool infinite_inertia=true )
```

**Comment by mudlee** [comment]
Note: I've followed this guy: https://github.com/GodotNativeTools/godot-cpp

**Comment by akien-mga** [comment]
> Note: I've followed this guy: https://github.com/GodotNativeTools/godot-cpp

Do you have the API synced with 3.1-stable from 3 days ago? It seems like your bindings are outdated, which is why your `move_and_slide` implementation doesn't match the documentation.

**Comment by mudlee** [comment]
I rebuilt a new one, and in the KinematicBody2D.hpp, the method is the same still:
```c++
Vector2 move_and_slide(const Vector2 linear_velocity, const Vector2 floor_normal = Vector2(0, 0), const bool infinite_inertia = true, const double slope_stop_min_velocity = 5, const int64_t max_bounces = 4, const double floor_max_angle = 0.785398);
```

**Comment by akien-mga** [comment]
CC @BastiaanOlij @karroffel, it looks like godot-cpp is not in sync with 3.1.

**Comment by BastiaanOlij** [comment]
@akien-mga well that is why I did all that work a few days ago building 3.1 stable from the 3.1 branch and making sure all the files are updated and in doing so finding out the api.json logic was broken. But with the fix I applied as far as I'm aware the files in godot_headers are correct.

@mudlee seeing the api.json is part of godot_headers make sure you've actually pulled in all its changes, simply doing a pull on godot-cpp won't bring in the updates on submodules, you may need to do a `git submodule update` as well. Also make sure to regenerate the bindings or you'll just end up recompiling the previous version, I would even delete the previous files from `include/gen` and `src/gen` (leave the `.gitignore` file though) before regenerating the bindings just to be safe..

**Comment by mudlee** [comment]
@BastiaanOlij I think I found the problem. I somehow referenced this as a submodule in my code: https://github.com/GodotNativeTools/godot-cpp/tree/783016677edf05faf8d5856d46f2cab931d7e3a3

**Comment by BastiaanOlij** [comment]
@mudlee I tent to make godot-cpp a submodule in my projects as well, that in itself isn't wrong however submodules aren't always the easiest to manage especially when there are additional dependencies so if you're not careful, you end up with the wrong commit
