### ISSUE TITLE
Empty space in scene tree dock menu when script editing feature is disabled

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#27866]
**Godot version:**
3.2-dev a20235a

**Issue description:**
Extra separators added if scripting feature is disabled:
![script-feature-disabled-extra-separator](https://user-images.githubusercontent.com/17108460/55828787-e111ed00-5b15-11e9-9734-11b2cceee221.png)

**Steps to reproduce:**
Disable scripting feature:
![script-disabled-reproduce](https://user-images.githubusercontent.com/17108460/55828908-1e767a80-5b16-11e9-842b-74eb71d03a76.png)

**Comment by akien-mga** [comment]
Fixed by #27931.
