### ISSUE TITLE
Rework Particle and ParticleMaterial property names and descriptions

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27878]
In combination with my rework proposal of the Particle Documentation, i would like several property names and ranges changed.

More info in the related issue on the docs: godotengine/godot-proposals#4283

Once the documentation is updated, the changes should be reflected here in concise manner:

https://github.com/godotengine/godot/blob/master/doc/classes/ParticlesMaterial.xml

**Comment by TheDuriel** [comment]
Makes: https://github.com/godotengine/godot/issues/24468 obsolete.

**Comment by akien-mga** [comment]
Consolidating this in https://github.com/godotengine/godot-proposals/issues/4283.
