### ISSUE TITLE
debug monitors for 2D rendering

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27874]
Proposal:

Expand the debug monitor to include readouts for 2D, like sprites drawn, draw calls, shader changes, etc. Basically all the things we currently get for 3D.

Our current project GRIEF is running into massive performance problems on the 2D (and 3D) side of things, and there is no way for us to debug it other than painstakingly measuring idle time after manually adding/removing scene components.

Ideally i would also like readouts of the 2D Lighting, as in GRIEF normal maps and texture size seem to make a massive impact on this. (Though i suspect the OpenGL texture size capabilities may be coming into play here as well.)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2384, as feature proposals are now tracked on the Godot proposals repository.
