### ISSUE TITLE
Godot as General Dev Environment + extensions

### ISSUE THREAD

**Issue by ArchangelZeero** [godotengine/godot#27881]
The disable editor features proposed for 3.2 could be expanded for turning Godot into an General Use Development Environment, with "downloadable extensions" or "enabled-nodes presets/cfg" that would unlock extra Nodes that could be enabled/disabled.

Then, nodes of the current build related to 2D game development would be at an 2D game development extension; It could also expand to other areas with their own specialized nodes such as web development (with nodes that compile to something like HTML/CSS/JS), animation, level design, etc.

**Comment by mhilbrunner** [comment]
This is outside the scope of Godot. There also doesn't seem to be much interest, judging by the activity in this issue. Godot aims to be a general game engine, and *may* be useful to develop some desktop applications. But I wouldn't expect it to move in the direction of "general purpose development environment, including webdev" anytime soon. :) There are better suited environments for that.

Thanks for taking the time to file an issue.
