### ISSUE TITLE
CurveTexture save/load includes PNG but doesn't support it

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27880]
**Godot version:**

3.1

**Issue description:**

When trying to save a CurveTexture resource to png, and error occurs.

It also appears to be impossible to create a CurveTexture from a png. Or load pngs into the CurveTexture property in the inspector.

**Comment by akien-mga** [comment]
CurveTexture is a float texture (`Image::FORMAT_RF`), while PNGs in Godot are likely handled as RGBA or RGB.

I'm not sure if PNG can handle RF or if it makes sense in its context. Could you be more explicit about your use case?

**Comment by TheDuriel** [comment]
![image](https://user-images.githubusercontent.com/44248915/55875654-de56dc80-5b95-11e9-83c7-1dc43a5d3bdb.png)
![image](https://user-images.githubusercontent.com/44248915/55875666-e44cbd80-5b95-11e9-96ac-ab1e309a7e9f.png)

**Comment by akien-mga** [comment]
I was not asking what is happening, I asked why do you want to save and load CurveTexture as PNG?

**Comment by TheDuriel** [comment]
Because its something the engine claims to be able to do. But when you do so, it fails. If its not meant to be possible, then the option should not be there.

**Comment by akien-mga** [comment]
Thanks, I understand now.
