### ISSUE TITLE
AnimationTreePlayer is unable to fire function from AnimationPlayer

### ISSUE THREAD

**Issue by steelxtreme** [godotengine/godot#2789]
AnimationTreePlayer is unable de call a function from Animations in AnimationPlayer.

**Comment by vnen** [comment]
I recall successfully using call func tracks while using the AnimationTreePlayer. Could you provide a small sample project that reproduces the bad behavior?

**Comment by steelxtreme** [comment]
Yeah, sure you have autoplay enabled on Animation player. There is the project example anyway.

https://drive.google.com/file/d/0By9KhpMFr-XNRkhFR2RVQ2N1WTA/view?usp=sharing
