### ISSUE TITLE
 vsCode in godot (godot addon for code is dead :( ).

### ISSUE THREAD

**Issue by BurningWood** [godotengine/godot#27893]
I try to make vsCode in godot (godot addon for code is dead :( ).
Can any one help me and tell why this code don't print any thing?

extends TextEdit
class_name ScriptEdit
"""
Adds syntax highlighting and autocomplete
for GDScript on top of TextEdit's defaults
"""

export var class_color : = Color(0.6, 0.6, 1.0)
export var member_color : = Color(0.6, 1.0, 0.6)
export var keyword_color : = Color(1.0, 0.6, 0.6)
export var quotes_color : = Color(1.0, 1.0, 0.6)
export var comments_color : = Color("959595")
export(String, FILE, "*.json") var keywords_path : = "res://ScriptEdit/keywords.json"
export var comment_sine := "# "
export(String, FILE, "*.gd") var path_to_script := "res://ScriptEdit/ScriptEdit.gd"

var autocompletes : = []
var keywords : = []

func _ready() -> void:
	add_keywords_highlighting()
	update_autocomplete()
	text = get_file_content(path_to_script)
	connect("text_changed", self, "_on_text_changed")

func get_classes() -> PoolStringArray:
	return ClassDB.get_class_list()

func get_properties(cls) -> Array:
	return ClassDB.class_get_property_list(cls)
	
func get_methods(cls) -> Array:
	return ClassDB.class_get_method_list(cls)

func get_signals(cls) -> Array:
	return ClassDB.class_get_signal_list(cls)

func add_keywords_highlighting() -> void:
	add_color_region('"', '"', quotes_color)
	add_color_region("'", "'", quotes_color)
	add_color_region(comment_sine, "\n", comments_color, true)
	
	var classes : = get_classes()
	
	for cls in classes:
		add_keyword_color(cls, class_color)
		var properties : = get_properties(cls)
		
		for property in properties:
			for key in property:
				add_keyword_color(key, member_color)
	
	var content : = get_file_content(keywords_path)
	keywords = parse_json(content)
	
	for keyword in keywords:
		add_keyword_color(keyword, keyword_color)

func get_file_content(path:String) -> String:
	var file = File.new()
	var error : int = file.open(path, file.READ)
	var content : = ""
	
	if error == OK:
		content = file.get_as_text()
		file.close()
		
	return content

func update_autocomplete():
	var classes : = get_classes()
	autocompletes.clear()
	for cls in classes:
		autocompletes.append(cls)
		
		for property in get_properties(cls):
			for key in property:
				if key in autocompletes:
					continue
				autocompletes.append(key)
				
		for method in get_methods(cls):
			for key in method:
				if key in autocompletes:
					continue
				autocompletes.append(key)
			
		for _signal in get_signals(cls):
			for key in _signal:
				if key in autocompletes:
					continue
				autocompletes.append(key)
			
		for key in keywords:
			if key in autocompletes:
					continue
			autocompletes.append(key)

	autocompletes.sort()
	

func _on_text_changed():
	add_keywords_highlighting()
#	update_autocomplete()
	var text_to_auto = get_word_under_cursor()
	
	for auto in autocompletes:
		if auto.find(text_to_auto) != -1:
			print(auto)
	
	

**Godot version:** 3.1 Official 

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment]
Sorry but this is not the place to ask questions, but to report engine bugs or ask fro new features.
Please use the [other community channels ](https://godotengine.org/community)to ask your questions.
