### ISSUE TITLE
Search not highlighting occurrence found

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27905]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
How to know what is the occurrence found in the line? 
It's not being highlighted.

![image](https://user-images.githubusercontent.com/11199752/55905743-00a62580-5ba9-11e9-8406-2c45609bdf94.png)

**Comment by KoBeWi** [comment]
Duplicate of #27004?

**Comment by rogeriodec** [comment]
Right.
