### ISSUE TITLE
.net coreclr / corefx

### ISSUE THREAD

**Issue by CharlesWoodhill** [godotengine/godot#2790]
Hi,
i wonder if u may put .net on your roadmap,
in my opinion c# would open godot to a wide range of hobby coders
and maybe some ppl will come from unity :)
afaik u havent done it yet because mono has license issues.
but have u tracked the "new" microsoft ideas, coreclr / corefx ?
these are open source and "platform independent"
also they planning "net native" (https://msdn.microsoft.com/de-de/vstudio/dotnetnative.aspx) which will be able to compile c# "like" c++
sure far from working but an intresting thing...

**Comment by n-pigeon** [comment]
Someone is working on coreclr integration, although GDScript and C++ will stay first class citizens in Godot. C# will be more for porting existing projects or libs.

For hobby coders (and not only) GDScript would be better choice imho. There are also plans for optional static types in GDS, then there will be even less need to use C#.

**Comment by CharlesWoodhill** [comment]
Oh sorry, then ive missed that in the roadmap :)

**Comment by alabd14313** [comment]
Be care!
Please learn from XNA, Objective-C (killed by swift), Visual basic (many developers are sorry because of spent time for learning), Adobe flash, ....

One admission (in th epile of admissions):
http://www.fortressofdoors.com/flash-is-dead-long-live-openfl/
You are free. Don't put in prison your freedoms.

**Comment by CharlesWoodhill** [comment]
i cant agree,
first c# is not microsoft specific, and will never run into the problems like flash or other "small isles"
second "net native" afaik compiles "like" c++ and is open source

i dont care gdscript, because if i code ill do it in c++ (if c# is no option)
but from my expirience developing in c# is 30% of time that u need in c++ 
(including testing, finding the last memory leaks,....and so on)
and im not talking about "prototype" projects where the power of c# is even greater.

look at unity: c#/java, lefthand coords,... it got rid of all "old" technology/paradigmas and provided a new updated easy to use interface to the users. their success is talking for its own.
u dont need c++ or in case of godot just another language-isle, to code (if u dont create the engine itself) if c# is supported many c# aware users would be grateful. then godot only has to change its projection matrix and provide a LH coord system, then its goin into the right direction :)
remember in RH if u go forward u go backward :P

**Comment by alabd14313** [comment]
Have C# proposals like c++ and python!
C# and Swift open structure is a policy, not freedom.

**Comment by akien-mga** [comment]
Closing as old, C# support has been implemented in 3.0 via Mono, and there are (for now) no plans for .NET Core, as it lacks support for mobile platforms we need to export to.
