### ISSUE TITLE
dragging of polygon2d (with holding shift and mouse) vertically and horizontally is not smooth

### ISSUE THREAD

**Issue by satyayelgatte** [godotengine/godot#27909]
**Godot version:**
3.1

**OS/device including version:**

windows 10

**Issue description:**

tried to drag polygon2d along vertical and horizontal axis with holding shift and mouse,but the drag is not smooth. 
below is link to video demonstrating this issue
https://www.dropbox.com/s/hvpii9378sq4fxr/Godot%20Engine%20-%20New%20Game%20Project%20-%20Node2D.tscn%20%28_%29%204_10_2019%2011_30_53%20PM.mp4?dl=0

**Comment by toger5** [comment]
This is how it should behave. it is smooth but changes to lock to the axis your mouse is closest to.

**Comment by KoBeWi** [comment]
Yeah, not sure how "fixed" behavior would look like, other than some timeout for when axis change happens.

**Comment by toger5** [comment]
A timeout would also be annoying. It would feel like godot does not react quick enough.
maybe a secondary shortcut to lock on one axis... like blender does with x,y
or pressing another key like space/alt/control will disable the automatic axis switch?
(dunno if they do something else)
@KoBeWi I like the current bahaviour though (I think we can close). If you disagree what option do you think is best?
(the only one that makes kind of sense to me is implementing axis lock shortcuts in the whole editor like in blender. for 2d/3d)

**Comment by KoBeWi** [comment]
> If you disagree what option do you think is best?

I like current behavior too. It's up to OP to defend his suggestion and gain support :P

**Comment by satyayelgatte** [comment]
@KoBeWi and @toger5 while dragging ,changing and locking to the axis which is closest to  mouse pointer is the problem. what if we fix the dragging motion of polygon depending upon the initial co-ordinates of mouse pointer until user releases the mouse key.let me explain 
lets say I is the inital point of cursor , P be the just next point of a cursor in a drag in 2D, then line IP is the line joining points I and P   and user wants to drag in X axis direction. so in this case if the angle between line IP and X axis is in between -45 to +45 degrees , we can say user is trying to drag in +x axis or -X axis direction, now if x co-ordinate of point P is more than x co-ordinate of I then we can definitely say that user is moving cursor in +X axis direction else in -X direction :)
now if angle is not in between -45 to 45, we can say user is trying drag in +Y or -Y axis direction . again if y co-ordinate of P is more than y co-ordinate of I , we can definitely say  user is trying to drag in +Y axis direction else in - Y axis direction.   
just 2D co-ordinate geometry stuff. let me know what you think
attached an example , you can verify :)
![WhatsApp Image 2019-04-13 at 2 47 49 AM](https://user-images.githubusercontent.com/40839373/56066814-a074d680-5d96-11e9-9749-e4a8731f4c2b.jpeg)

**Comment by groud** [comment]
What you describe in you schema is already what is happening. When you get close to the initial position, the mouse goes into the -45 to 45 angle you describe, which consequently moves the node horizontally.

Closing as it is expected behavior.

**Comment by toger5** [comment]
@groud @satyayelgatte I think the proposal is to use the INITIAL mouse position of the drag motion as the locked axis.
That actually could be a better work-flow when trying to move little distances on one axis. 
May favourite is still, having blender like axis locking using `x` `y` `z`
