### ISSUE TITLE
VehicleBody2D

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#27901]
**Feature request:**
It would be nice to have a VehicleBody2D node (not top-down vehicle but from side view).
Currently this is only possible with a 3d VehicleBody and linear x, angular y and angular z axis lock.
It could have the same properties like the 3d VehicleBody (brake, engine_force and steering https://docs.godotengine.org/en/latest/classes/class_vehiclebody.html ) but steering means the car rotates in the air and on ground so it is possible to do a wheelie.

Example:
https://github.com/HugeGameArtGD/Solus-Stunts/releases/download/v9.0/vehiclebody2d.zip

**Comment by toger5** [comment]
in 2d this is quiet simple to implement. No sure if it is worth having a node. but it would still be simpler. and in terms of consistency (3d vehicle) it also would make sense.

you can try: rigid body + two ray casts + apply force at ray cast collision point (for throttle + suspension... orientation calculated by (perpendicular to the) collision shape normal and ray direction) + apply torque. should be a matter of minutes to set up.

**Comment by groud** [comment]
IIRC, the plan was more to move out the vehicle3d node out to a plug-in instead of adding a 2d version

**Comment by LinuxUserGD** [comment]
[test.zip](https://github.com/godotengine/godot/files/3517131/test.zip)
Closing as it's already possible with pinjoints (see example project).
