### ISSUE TITLE
Implement scroll script editor with middle mouse button pressed

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27907]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
As a standard in many editors and browsers, when you **keep the middle mouse button pressed** and **move the mouse**, you can scroll up and down.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/27498.
