### ISSUE TITLE
Crash - if() in Shader crashes when ";" is typed after ()

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#2791]
How to reproduce:
Create project with for example TestCube (also works with Polygon2D).
Assign text based shader material.
Type this "shader" into Shader Editor:
float x=1;
if(x=1);

What happens: crash :)

**Comment by eska014** [comment]
Can reproduce with `if(x==1);`, guess it's a typo.

**Comment by n-pigeon** [comment]
ah yes == not = ^^'

**Comment by akien-mga** [comment]
Fixed by #2865.
