### ISSUE TITLE
Script Text disappear when the line spacing is set to a big number

### ISSUE THREAD

**Issue by gsegovia2018** [godotengine/godot#27912]
Godot version 3.1

OS/device including version:
MacOs Mojave 10.14.3
McBook Air 13 (2015)

Issue description: 
Script Text disappear when the line spacing is set to a big number and messed up when is set to a negative number. The line spacing should have a limit range.

**Steps to reproduce:**
Editor-> Editor Settings -> Text Editor -> Theme -> Line spacing
![Default line spacing](https://user-images.githubusercontent.com/46790538/55919794-8e106680-5bf7-11e9-91d1-f8e992f09c35.png)
Default line spacing (6)

![Negative line spacing](https://user-images.githubusercontent.com/46790538/55919827-b13b1600-5bf7-11e9-833f-e93fba082e3a.png)
Negative line spacing (-12)

![Big line spacing](https://user-images.githubusercontent.com/46790538/55919848-bf893200-5bf7-11e9-872d-008de0130315.png)
Big line spacing (1000)

**Comment by akien-mga** [comment]
Seems to work as intended :)

But yeah, limiting the default range as done in your PR seems fine.
