### ISSUE TITLE
Errors in console when open project

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#27918]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 7 x64

**Issue description:**
When I open my project I can see errors in console.
No errors in output tab.

```
OpenGL ES 3.0 Renderer: GeForce GTX 650 Ti/PCIe/SSE2
Editing project: d:/work/games/ZarechnyGodot (d:::work::games::ZarechnyGodot)
OpenGL ES 3.0 Renderer: GeForce GTX 650 Ti/PCIe/SSE2
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned:
get_transform()
   At: scene/2d/canvas_item.cpp:478
ERROR: get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rec
t2()
   At: scene/2d/canvas_item.cpp:966
ERROR: get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rec
t2()
   At: scene/2d/canvas_item.cpp:966
ERROR: show_modal: Condition ' !is_inside_tree() ' is true.
   At: scene/gui/control.cpp:2103
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned:
get_transform()
   At: scene/2d/canvas_item.cpp:478
ERROR: get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rec
t2()
   At: scene/2d/canvas_item.cpp:966
ERROR: grab_focus: Condition ' !is_inside_tree() ' is true.
   At: scene/gui/control.cpp:2074
ERROR: get_tree: Condition ' !data.tree ' is true. returned: __null
   At: ./scene/main/node.h:263
* daemon not running; starting now at tcp:5037
* daemon started successfully
```

![2019-04-11_080549](https://user-images.githubusercontent.com/1552169/55932050-a3ee4d80-5c30-11e9-83f7-e3a3ea62bc0b.png)

**Link to project: [here](https://cloud.mail.ru/public/QJ85/471jWSFth)**

**Comment by akien-mga** [comment]
I can't reproduce it on Mageia 7 (Linux) with 3.1-stable nor a build from the current master branch, opening the attached project.

Can you reproduce it all the time? Is the problem fixed if you copy your project folder somewhere else?

**Comment by breakmt** [comment]
> 
> 
> I can't reproduce it on Mageia 7 (Linux) with 3.1-stable nor a build from the current master branch, opening the attached project.
> 
> Can you reproduce it all the time? Is the problem fixed if you copy your project folder somewhere else?

Yes, this happens all the time on that PC. But now I tried on another one and it is not reproduced... Strange. I will try to move project to another location later, thanks, maybe you have more advice what can I do?

**Comment by breakmt** [comment]
@akien-mga You were right! After I copied project folder in another location and start it, errors from console are disappeared. I suppose this means that something wrong with project temp folder? I tried to copy all files from "old placed project" temp folder to new one and yes, I can see errors again in new project. I archived that folder and here it is. Maybe you could be so kind to try it and you will get more info why it could happen? [Link to archive ](https://cloud.mail.ru/public/37BT/353Pd4Rg4)

**Comment by Calinou** [comment]
@breakmt Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response (see the above comment).
