### ISSUE TITLE
Request for more Bitmap Font effects

### ISSUE THREAD

**Issue by lefay1982** [godotengine/godot#27922]
This is a request for more Bitmap Font effects in Godot 3.

![TIM](https://user-images.githubusercontent.com/5716884/55943784-cc4e6a00-5c79-11e9-81a3-14f4b376caab.png)

The Dynamic Font has Extra Spacing Char setting, can add or reduce the space of two chars.

but Bitmap Font no this effect, the space of chars can not control by setting but by origin image.

please add these effects in Bitmap Font.

**Comment by Calinou** [comment]
This was fixed by https://github.com/godotengine/godot/pull/46043, closing.
