### ISSUE TITLE
"Trim" option on importing WAV stereo audio removes half of it

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#27925]
**Godot version:**

3.2 dev 7f2ad8b

**OS/device including version:**

Debian GNU/Linux buster/sid x86_64

**Issue description:**

Expected: trim to only remove silences from the end of the audio
Happened: half the stereo music is missing (mono works as expected, silence trimmed)

**Steps to reproduce:**
1. import wav stereo music file with trim enabled (default)
2. preview in the editor, seek to the end and you'll notice that the music abruptly ends.

**Minimal reproduction project:**

You can use godot-demo-projects/audio/spectrum and convert the demo song to wav

**Comment by Naryosha** [comment]
Possibly related to #27645

**Comment by akien-mga** [comment]
CC @theisegeberg

**Comment by theisegeberg** [comment]
This probably pertains to the changes I've made to the trim code. I'm looking into it.

**Comment by akien-mga** [comment]
Fixed by #27927.
