### ISSUE TITLE
Renaming scenes doesn't update thier names in editor_layouts.cfg "open_scenes"

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#27920]
**Godot version:**
3.1

**OS/device including version:**
Windows 7 x64

**Steps to reproduce:**
1. Editor settings - Scene tabs - Restore scenes on load is ON,
2. Open project - open some scene,
3. Rename opened scene using context menu,
4. Reopen project

**_Result:_**
Alert - "can't open scene "old scene name", this file could have been moved or deleted"

**_Expected:_**
When you rename scene it also should be renamed in **editor_layout.cfg** file ([EditorNode] open_scenes=[ ... ]). When you reopen project there is no error, cause Godot is smart enough.

**Comment by DarthSett** [comment]
@akien-mga 
Sir, I am new to open source projects (and GitHub in general and would like to contribute to this project by helping you to solve this issue (this is my very first contribution to an open source project).

Honestly, this is all looking very confusing. Can you help me by showing me the strings?
