### ISSUE TITLE
.position and .global_position are not working

### ISSUE THREAD

**Issue by AaronSpeedy** [godotengine/godot#27924]
**Godot version:3.1**

In my project .position is not working, but when I open an old project with .position or .global_position it works again

![Screen Shot 2019-04-11 at 7 07 52 AM](https://user-images.githubusercontent.com/49521496/55956095-c3817800-5c28-11e9-8009-ad57d070c7f6.png)

To test that it really was a glitch I created a new project with the same circumstances and
literally copy pasted the code, and a error message showed up.
 Here's the line of code saying that its wrong.
And also the player variable.

onready var player = get_parent().get_node("Player")
func _physics_process(delta):
	if player.position.x < position.x:

**Comment by Zireael07** [comment]
It means your player is null, apparently your parent node has no "Player" node.

**Comment by KoBeWi** [comment]
This issue is useless without reproduction project (and most likely was an user error). Closing.
(You can still comment if you somehow have a project that reproduces this in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3))
