### ISSUE TITLE
Headless build fails to export and then crashes

### ISSUE THREAD

**Issue by fire** [godotengine/godot#27933]
**Godot version:**
5772f60f -- Closest version before custom patches.

**OS/device including version:**
fedora 29 on docker

**Issue description:**
Using the headless build to do CICD fails to export the project. The headless build crashes.

**Steps to reproduce:**

CICD log:

See message that is not from a live server.

**Minimal reproduction project:**
I don't have one, but it would help..

**Comment by fire** [comment]
Opps. 
[export_failure.txt](https://github.com/godotengine/godot/files/3069945/export_failure.txt)

**Comment by jamie-pate** [comment]
Maybe related? looks like it's trying to validate supported features on `DummyRasterizer` https://github.com/godotengine/godot/issues/27963

**Comment by youreperfect** [comment]
Well its not a "minimum" project but its very small - feel free to use my project to test, it is also having this issue

git clone https://gitlab.com/youreperfectstudio/catherines-quest.git
checkout 80958044b6480d87196c9fdf9f4fe0e1c18aec55

I am using Travis CI which just kicks off the run_tests.sh file in the root directory to download Godot 3.1 headless and build targets, runs GUT, then tries to do a build (but fails with error 12 - ERR_FILE_CANT_OPEN

![image](https://user-images.githubusercontent.com/49788602/56627611-2fda7f00-660c-11e9-8440-e251e90bf6c6.png)

**Comment by fire** [comment]
@youreperfect Can you test master again? I don't have an environment for this at this very moment.

**Comment by fire** [comment]
I wonder if https://github.com/godotengine/godot/pull/35113 fixes this bug.

**Comment by akien-mga** [comment]
That or my earlier PR fixing some UX issues would likely have solved it yes.

I'll close for now, please comment if you can still reproduce it in 3.2 RC 1 or later.
