### ISSUE TITLE
Inspector panel is too wide

### ISSUE THREAD

**Issue by kaadmy** [godotengine/godot#27938]
**Godot version:**
Godot v3.1-stable (GLES3)

**OS/device including version:**
```
OS: Arch Linux x86_64
Kernel: 4.19.4-arch1-1-ARCH
GPU: NVIDIA GeForce 940MX
GPU: Intel HD Graphics 620 (secondary, unused)
```

**Issue description:**
Switching between the "Inspector" panel and any other panel resizes the dock incorrectly.

The "Inspector" panel seems to be the issue here, since all other panels don't have this issue.

**Steps to reproduce:**
1. Ensure the "Inspector" panel is in the same dock as any other panel ("Node", "FileSystem", "Scene" all work)
2. Switch between the 2 (or more) panels

**Minimal reproduction project:**
This happens with the default editor configuration

**Comment by KoBeWi** [comment]
Duplicate of #25317?

**Comment by kaadmy** [comment]
Ah okay, I couldn't find any existing issues. Closing as duplicate.
