### ISSUE TITLE
draw_line() operates on global coords but accepts local coords

### ISSUE THREAD

**Issue by Brickcaster** [godotengine/godot#2793]
**Preface:**  
draw_line() and draw_polygon() and draw_circle() do not provide the prettiest. outputs and can cause aliasing.  An attempt to emulate subpixel drawing failed.

**Issue:**  
draw_line() will snap to global coordinates, but accepts local coords.  This can cause some unexpected behavior as lines snap to unexpected coordinates.

**Expected behavior:**  
draw_line() should round() inputs rather than floor() or ceil() them.  Alternatively, if draw_line() is called for width 1 at x = 0.5, two lines are drawn at x=0 and x=1 with alpha of approximately 0.5 * rgba.  (I personally found alpha of pow( 1 - (x-floor(x)), 2) and pow( 1 - (x-ceil(x)), 2) to be pleasing.)  Using alpha to provide smother draw_polygon() and draw_circle() outputs would also be desired.

**Example**:
    extends Sprite
    
   set_pos(Vector2(100.1,100)
    var x = 0.5
    draw_line( Vector2(floor(x), 0), Vector2(floor(x), 20) ) # line is drawn at x = 100
    draw_line( Vector2(ceil(x), 0), Vector2(ceil(x), 20) ) # line is drawn at x = 102

![](http://i.imgur.com/Fz1qM2I.png)
**Image explaination:**  
draw_line() is used twice for each 10% interval of the bar length with alpha scaled to represent how close the line is to the floor(x) or ceil(x).  The third line has a 1 pixel gap.

**Comment by reduz** [comment]
I'm not sure if much can be done at this point, lines are not rounded or anything and this is the default behavior of OpenGL. OpenGL ES 2.0 (current driver and what is available on mobile) lacks any kind of antialiasing, too.

**Comment by reduz** [comment]
I suggest you do what you are attempting to do with a texture and one of the draw_rect() variants
