### ISSUE TITLE
Indicate default filters in Project/Editor AssetLib UIs 

### ISSUE THREAD

**Issue by follower** [godotengine/godot#27930]
**Godot version:**
3.1

**OS/device including version:**
All

**Issue description:**

While [the AssetLib documentation](https://docs.godotengine.org/en/3.1/tutorials/assetlib/using_assetlib.html) mentions the Project Manager View and Editor View of AssetLib have different filters it's not obvious within the UI:

>  Also, you can only download Projects, Demos and Templates from the Project Manager view of the AssetLib, while Addons (tools, scripts, materials etc.) can only be downloaded from the in-project AssetLib. 

If this filtering is kept, it would be helpful to indicate within the UI that some filtered items are available and can be accessed via the other interface.

(For context, I had a couple of times used the Project Manager AssetLib view to search for Addons I knew existed and assumed that the lack of results was a bug--as I'd encountered buggy behavior with AssetLib on other occasions.

I had actually forgotten that the "AssetLib" tab in the Editor interface even existed and even if I hadn't I'm not sure I would have assumed that they would have different filters--particularly when the "Category" is specified as "All".)

In the interim it might be helpful to mention the default filtering more prominently in the documentation.

**Steps to reproduce:**

Search for a template via the Editor AssetLib UI or for an addon via the Project Manager AssetLib ("Template") UI.

**Minimal reproduction project:**
N/A

*Edit:* Semi-related issue: https://github.com/godotengine/godot/issues/5284#issuecomment-229291619

**Comment by Calinou** [comment]
Perhaps we could make this slightly more obvious in the Project Manager by renaming the "All" category to "Projects, Demos and Templates":

![image](https://user-images.githubusercontent.com/180032/61597258-9290e600-ac0e-11e9-87e4-317899bacc6c.png)

**Comment by Calinou** [comment]
This was addressed by https://github.com/godotengine/godot/pull/47632, closing.
