### ISSUE TITLE
FuncRef.call_func(data) ?

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#27943]
**Godot version:**
3.1

**OS/device including version:**
windows 10

**Issue description:**
`FuncRef.call_func(data)` gives error "Expected 0 arguments", but documantation says 
`Variant call_func( ... ) vararg` 

Should decumentation be `Variant call_func()` or is it a bug?

**Step to reproduce**
```
fref=FuncRef.new()
fref.set_function(func_string)
fref.set_instance(self)
var a =fref.call_func(data)
```

**Comment by akien-mga** [comment]
Does the function referenced by `func_string` take arguments?

**Comment by akien-mga** [comment]
Works fine for me:
```
func _ready():
	var fref = FuncRef.new()
	fref.set_function("print_words")
	fref.set_instance(self)
	fref.call_func("hello", "world")

func print_words(arg1, arg2):
	prints(arg1, arg2)
```
prints:
```
hello world
```

**Comment by burstina** [comment]
sorry , i'm a jerk
beer is bad at working
.. but it tasty for me :)
