### ISSUE TITLE
multiple class_name on same script

### ISSUE THREAD

**Issue by SoftLaunch** [godotengine/godot#27959]
**Godot version:**
3.1 flathub

**OS/device including version:**
Fedora 29

**Issue description:**
In the same script class_name can be written multiple time without triggering any warning or error

**Steps to reproduce:**
- Create a script
- write multiple class_name name

**Minimal reproduction project:**
not applicable

Script should allow only one class_name

**Comment by lupoDharkael** [comment]
Working on it!

**Comment by Jimmio92** [comment]
Isn't this removing a possible feature? Multiple names for the same class. Think Vector3 and Color... they're both the same, so why not combine them into one?

**Comment by SoftLaunch** [comment]
It's not working like that right now.
Eventually, we should have a single class_name with multiple name like:
class_name vector, color, ...
