### ISSUE TITLE
Add built-in logging classes / capabilities

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#27958]
**Godot version:** 3.1

**Issue description:**
I do use logging a lot to track things in the game and investigate bugs. But I don't believe that I do that in an efficient way (or that there's such way at all for GDScript). I believe this is a very basic feature, but I've failed to find something related to that.

**What I expect from logger**
This is a class that allows and supports:

* customizing logging format. Say, similar to `printf` special characters, for example:
  - `%t` would mean current time like `2012-01-30T10:20:30Z` or whatever
  - `%n` would mean name of the logger
  - `%t` would mean name of thread this logger is triggered from
  - etc
* log levels. The most important are:
  - ERROR
  - WARN
  - INFO
  - DEBUG
  - TRACE
* logging destinations:
  - console
  - file
  - what else?
* remove logging-related pieces of code if the game is not in "debug" mode. It would be fine to have it implemented like directives in C, say:
```GDScript
##ifdef DEBUG
logger.info("some interesting stuff here")
##endif
```
* log files rotation policy (optional, I don't believe that there would be developers with need in this)

Currently, I'm doing this with my own `Logger` class written in GDScript and handling all that levels. But even so, when I need to dig into an issue and set logging level to TRACE (i.e. I see LOTS of logs with every little detail happening in my game) I get irritating message:
```
output overflow, print less text
```
But, hell, I do need to print lots of text!

**Comment by Calinou** [comment]
You can use `push_error()` and `push_warning()` in global scope (`@GDScript`) to write error/warning messages that will appear in the Errors tab when running the project from the editor. These messages can be double-clicked to reach the code that emitted them too.

**Comment by groud** [comment]
Related #22202

**Comment by smedelyan** [comment]
@Calinou still, we lack of more detailed levels like INFO, DEBUG and TRACE. What if I want to log some tracking stuff so that I can use that info later when investigating bugs? I don't think that's a good idea to log everything with `push_error()` / `push_warning()`. So my proposal is still valid.

P. S. Thanks for those methods, I didn't know that=)

**Comment by mitchcurtis** [comment]
+1. I'm using a fork of this:

https://github.com/hedin-hiervard/godot-logger

I quite like Qt's way of doing it:

https://doc.qt.io/qt-5/qloggingcategory.html

There you can also use a conf file (INI) to enable/disable warnings.

**Comment by smedelyan** [comment]
@mitchcurtis thanks a lot, I'll take a look at that

**Comment by chrisgraf** [comment]
+1. We also currently use the above mentioned godot-logger but it is quite limited currently. Also I think this is an important basic functionality which should be provided out of the box. An integrated logging mechanism also would make it possible to dynamically change the loglevel or logging scope in the editor during runtime and thus provide an additional benefit...

**Comment by pwab** [comment]
As this is a proposal and the related PR was closed - could this issue be moved to [godotengine/godot-proposals](https://github.com/godotengine/godot-proposals) in some way?

**Comment by smedelyan** [comment]
@pwab feel free to copy-paste it there, I don't mind :)

**Comment by KoBeWi** [comment]
Since this was moved to proposals, it can be closed.
