### ISSUE TITLE
Extra newlines inserted in tres files

### ISSUE THREAD

**Issue by Vultraz** [godotengine/godot#27961]
Godot 3.1 stable on Windows 10

Just as the subject says. Here, using this font resource in a node causes this spurious newline to be inserted, making things a bit annoying for VSC users.

![image](https://user-images.githubusercontent.com/3558659/56060989-09b71280-5db4-11e9-99d6-eca1b56f4417.png)

**Comment by Vultraz** [comment]
Hm.. might not be exclusive to ends of file, since it happens here mid-file too:
![image](https://user-images.githubusercontent.com/3558659/56062071-f9ecfd80-5db6-11e9-8f46-8ef06c349d8f.png)

**Comment by Calinou** [comment]
This should be fixed in https://github.com/godotengine/godot/commit/39a5bb4fbc9977fe0ee88c547d997c3acc9650cb, which will be available in 3.1.1 and 3.2.

**Comment by Vultraz** [comment]
Ah, good to know!

**Comment by Calinou** [comment]
I'll close this issue, please comment if you can still reproduce it with a [daily build](https://hugo.pro/projects/godot-builds/) of the `master` branch :slightly_smiling_face:

**Comment by Vultraz** [comment]
Uhhh Windows actually blocked the daily build installer from running so I think I'll just wait for 3.1.1 😬
