### ISSUE TITLE
cannot install app after export release for second time

### ISSUE THREAD

**Issue by SMaiLubis** [godotengine/godot#27968]
**Godot version: 2.1.5**

**OS/device including version:android 5.1.1/xiaomi redmi note 3**

**Issue description: cannnot install app after export release second time, first time is ok, it should ok too**

first time i export release is ok, but when i update the programand export it i cannot install it again, in adb logcat i got `Installation error code: -22`.
do i need to change the keystore each time i update the program?
and what is error code 19 when i run the app? my app work ok but in adb logcat i get error code 19

**Steps to reproduce:**
i dont really know. i just export release > install > change connect button to other function > export release it again > install error

**Comment by StraToN** [comment]
Thanks for your report. Can you please provide a project for which your problem occurs?

**Comment by volzhs** [comment]
did you install through 'adb' command?

**Comment by SMaiLubis** [comment]
Thank you for your attention, the problem is solved. What i do is increase version code and version name in Android export menu, every time i export a release apk.
But i still get error code 19 in adb when try run the app. My app work perfectly fine, but still get error code in adb.

**Comment by volzhs** [comment]
I don't know the error message and code but...
if you try to install it through `adb` while phone has the same app, you could face a error.
`adb -r game.apk` will force to install even though phone has it.

**Comment by SMaiLubis** [comment]
It installed and The game running fine even when  i get error code 19 when start up the game.  I just get curious what is error code 19 mean.
