### ISSUE TITLE
Fly camera?

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#2797]
Blender and Unreal Engine has it, pretty easy to implement and way easier in orienting cameras and lights in 3D view :)

Same question was asked on [/r/godot](https://www.reddit.com/r/godot/comments/3oqd2h/can_i_fly_the_camera_to_a_desired_position/)

**Comment by reduz** [comment]
The 3D camera should definitely be fixed

**Comment by procedural** [comment]
https://github.com/procedural/quatFirstPersonCamera

:)

**Comment by nunodonato** [comment]
Adding to this: an hotkey to make the camera match the current viewport location and rotation.

**Comment by neikeq** [comment]
This issue also seems better on the 3.0 milestone, which will improve the renderer and most likely the 3D tools too.

**Comment by reduz** [comment]
yeah

On Fri, Jun 3, 2016 at 1:10 PM, Ignacio Etcheverry <notifications@github.com

**Comment by suptoasty** [comment]
@Zylann Shouldn't this be closed since your PR #8616 addressed this issue?

**Comment by reduz** [comment]
closing, as this is implemented
