### ISSUE TITLE
why many Visual Shader lacks (3.2)

### ISSUE THREAD

**Issue by ilyafuu** [godotengine/godot#27975]
**Godot version:**
b7cf4c2050dfd51521522c874676e96d2e5c4762

**Issue description:**
I did not understand why added boolean where is the connection for the visual shader?

missing list:
IF
Switch (uniform) (it looks like boolean)
Clamp
Invert (OneMinus)
Create Function

DEPTH_TEXTURE

godot 3.2 VShader interpolation disappeared

**Steps to reproduce:**
![0007](https://user-images.githubusercontent.com/17591539/56076793-a04bf980-5ddd-11e9-857e-e7116028f0d8.png)

UE4 materials screenshot:
![0004](https://user-images.githubusercontent.com/17591539/56076810-c83b5d00-5ddd-11e9-82fe-8b61bcb3187b.png)

`OneMinus (Invert)`
![0005](https://user-images.githubusercontent.com/17591539/56076831-fae55580-5ddd-11e9-99bb-c2b325cbd3b5.png)

![0001](https://user-images.githubusercontent.com/17591539/56076823-e7d28580-5ddd-11e9-9002-3bc92f3d0325.png)

`only noise for visual shader (function)`
![0006](https://user-images.githubusercontent.com/17591539/56076868-72b38000-5dde-11e9-8b63-c7e684932437.png)

`fresnel  for visual shader (function)`
![0003](https://user-images.githubusercontent.com/17591539/56076945-fd947a80-5dde-11e9-906e-fa3e64bd8df8.png)

`Only the Visual shader needs a bit more diverse function. The user will be easier to make the shader look like UE4 materials.`

**Comment by Chaosus** [comment]
> godot 3.2 VShader interpolation disappeared

its a `mix` now

`Clamp` - exist

> IF, Switch

The implementation of boolean was a first step to it

**Comment by ilyafuu** [comment]
okay

not yet added a comment for Visual shader
![0008](https://user-images.githubusercontent.com/17591539/56077483-64b52d80-5de5-11e9-8f9d-b3868485ab52.png)

for example visual script comment
![out](https://user-images.githubusercontent.com/17591539/56077518-cc6b7880-5de5-11e9-89ec-14a3b54e1d43.gif)

**Comment by Chaosus** [comment]
> why many Visual Shader lacks

Because nobody is wanted to implement it yet, or do not have the time to do it. Godot has
the almost purely volunteer-based developer team, which mostly work on what they want, and when they want. If you have a skill you can also contribute to Godot and add the functions which you want.

**Comment by ilyafuu** [comment]
@Chaosus I understand that I did not learn C++ sorry, only Python (I will probably go to study C++ in the future) :)

**Comment by Chaosus** [comment]
Yeah, thanks for notice anyways, I can look at further improvements to this system.

Also, note that Godot is not necessarily should follow UE4 (as I see in the provided screenshots) and implement whatever it's contains.

**Comment by ilyafuu** [comment]
@Chaosus perfectly lighter :+1:
![out](https://user-images.githubusercontent.com/17591539/56082844-8a165b80-5e26-11e9-8480-c2d0cec18e63.gif)

**Comment by Chaosus** [comment]
@ilyafuu Glad, that all worked fine!

Then about the other - I can easily implement OneMinus and Noise, but the Fresnel requires research how to do it correctly and what the algorithm stay behind it, while the Comment requires to write different kind of visual shader Node, simular to one in visual script. I may start to prepare a new pack of enhancement, where to include them, but not now, I want a rest and work on my projects..

**Comment by ilyafuu** [comment]
wanted to mask invert for Visual Shader
![0000](https://user-images.githubusercontent.com/17591539/56083088-5f79d200-5e29-11e9-941a-a1fcc3ba28f8.png)
![0001](https://user-images.githubusercontent.com/17591539/56083091-63a5ef80-5e29-11e9-993c-35e451c19683.png)

**Comment by ilyafuu** [comment]
okay :)

**Comment by ilyafuu** [comment]
https://www.youtube.com/watch?v=kN7TvPWtypk

http://kylehalladay.com/blog/tutorial/2014/02/18/Fresnel-Shaders-From-The-Ground-Up.html
