### ISSUE TITLE
Can not import png image as ImageTexture

### ISSUE THREAD

**Issue by tm-nihonsuki** [godotengine/godot#27989]
**Godot version: 3.1**

**OS/device including version: Nixos Linux**

**Issue description: Loaded a png image texture into a sprite.  Expected it to be imported as an ImageTexture, which I could set to repeat.  However, it was imported as a StreamTexture, which can not be set to repeat.  This need to use ImageTexture for repeat does not seem to be addressed in similar bug reports.**

**Steps to reproduce:Create sprite and load a png image into the texture, either by dropping the image on the field or by selecting Load from the drop down.**

**Minimal reproduction project:
[Tutorial2.zip](https://github.com/godotengine/godot/files/3076470/Tutorial2.zip)**

**Comment by volzhs** [comment]
stream texture can't be set to repeat?
![steam_texture_repeat](https://user-images.githubusercontent.com/8281454/56083059-235f6500-5e5b-11e9-88b9-9c4b1ceb7841.gif)

**Comment by tm-nihonsuki** [comment]
Thank you for pointing that out.  I'm following a tutorial based on an older version of Godot in which, I believe, import properties were a sub-menu of properties.  I seem to have fallen foul of GUI changes.
