### ISSUE TITLE
discussion of the future for Visual Shader

### ISSUE THREAD

**Issue by ilyafuu** [godotengine/godot#27993]
No list added:
Comment for Visual Shader
Creating Functions for Visual Shader
Save screenshot high resolve for Visual Shader

Sine (function)
>https://en.wikipedia.org/wiki/Sine

DEPTH_TEXTURE (UV)

Noise (function)
Gradient Noise (function)
Voronoi (function) (it's like noise)
Twirl (UV function)
OneMinus (Invert)
Fresnel (function)
Flipbook (UV, textures sprite animation for Particles) (function)
Vertex Painting (UV) (draw color RGB textures models and terrain) (future)

**Comment by ilyafuu** [comment]
`Flipbook`
![001](https://user-images.githubusercontent.com/17591539/56084382-0ca91600-5e3b-11e9-91d2-42859bb3ff73.png)

**Comment by ilyafuu** [comment]
`Fresnel`
![2019-04-13_23-06](https://user-images.githubusercontent.com/17591539/56084784-fb630800-5e40-11e9-8247-f0ea12d44028.png)
>http://kylehalladay.com/blog/tutorial/2014/02/18/Fresnel-Shaders-From-The-Ground-Up.html

**Comment by ilyafuu** [comment]
@Chaosus code: https://github.com/godotengine/godot/blob/master/scene/resources/visual_shader_nodes.cpp#L3047
"value" will replace "bool" the user will be clearer :)

**Comment by golddotasksquestions** [comment]
How about Visual Shader to Shader language conversion? and vice versa (though maybe that's more tricky, idk)?

**Comment by ilyafuu** [comment]
@golddotasksquestions until we know only @Chaosus  the everything is possible to do for the visual shader development gradually :)

**Comment by ilyafuu** [comment]
new Random range
![out](https://user-images.githubusercontent.com/17591539/56093342-37917980-5ed0-11e9-8fac-caf104deb431.gif)

**Comment by Chaosus** [comment]
> new Random range :)

what this - a brand new node ?

> but you need a new time to the time number 0 to 1 return 0 (without sin and cos)

As far as I could understand that sentence (made on very low english skill), you need to time limited from 0 to 1 - this you could perform via Remainder

> @Chaosus

Stop bother me in every post !

**Comment by ilyafuu** [comment]
random range it looks like lerp but we need time number 0 to 1 (min any number max the same any number)

**Comment by Chaosus** [comment]
I don't understand why you call it "random" and the lerp has already existed under Mix name in shaders

**Comment by ilyafuu** [comment]
Sorry, I didn't watch the Mix -_-
"Mix" incomprehensible name is necessary more correctly "Lerp" user will confuse the name

**Comment by Chaosus** [comment]
> "Mix" incomprehensible name

Well, it's a name accepted in GLSL language, this could be debatable, so if you want you can create a new issue about it - and other devs will say their opinions

**Comment by ilyafuu** [comment]
I know glsl but I already forgot the name Mix, I just remember Lerp ^_^
Unity engine shader graph and UE4 material name only "Lerp" 

if the user UE4/Unity transition to Godot visual shader thinks no Lerp but Mix is not familiar from GLSL it will not be clear asks the discord many users know the words Lerp :)

**Comment by ilyafuu** [comment]
![image](https://user-images.githubusercontent.com/17591539/56094541-015af680-5ede-11e9-9f34-71b0d6b580dc.png)
the user again asks DEPTH_TEXTURE should be added to the visual shader

**Comment by ilyafuu** [comment]
Is it possible to add hot keys for a visual shader?
eg:
hot key 1,2,3 will appear => constants scalar/vec/color
hot key T will appear => Texture
hot key L will appear => Mix
hot key U will appear => UV
hot key I will appear => IF
hot key B will be appear => Bool
hot key A will appear => add vec/scalar
others.....

**Comment by ilyafuu** [comment]
@Chaosus new Flipbook for 2D tilemap :doge: (not completed yet) ^_^
![out](https://user-images.githubusercontent.com/17591539/56145101-4a797c00-5fac-11e9-861e-762289f15874.gif)

**Comment by ilyafuu** [comment]
done flipbook complete
![out](https://user-images.githubusercontent.com/17591539/56150663-02f8ed00-5fb8-11e9-898f-88cf69765cd5.gif)

**Comment by AssjackGames** [comment]
Functions like these would make me actually use the visual shader, would love to see some of these rolled into the engine

**Comment by ilyafuu** [comment]
![image](https://user-images.githubusercontent.com/17591539/56567326-51604a00-65bd-11e9-961b-197991de1d6c.png)
it is simpler an array of port points

**Comment by ilyafuu** [comment]
visual shader save screenshot user easier shows a help for discord

**Comment by gamergamesz** [comment]
It would be great to have a mix node like blender which could be control with animation system as well as code for things like dynamic normal(wrinkle map) or wounds etc.
![download](https://user-images.githubusercontent.com/13883739/56569468-a78db700-65d6-11e9-8b2e-d562cf8aa7c1.jpg)

**Comment by ilyafuu** [comment]
@Chaosus hello, search is missing a lot
![image](https://user-images.githubusercontent.com/17591539/56889879-6a1aa500-6a80-11e9-9c7e-26ba6d54a475.png)

why visual shader `active` float a not bool ?
![2019-04-29_00-10](https://user-images.githubusercontent.com/17591539/56889903-79015780-6a80-11e9-93b3-67b71f0d921d.png)

**list no added "create shader node"**

> mode---------Particles--------Vertex----Input

transform
active
velocity
restart 
custom
custom_alpha
delta
lifetime
index
emission_transform

> mode---------CavasItem--------Vertex

texture_pixel_size
extra
light_pass
UV2 (fix delete)

> mode---------CavasItem--------Fragment

texture_pixel_size
screen_pixel_size
light_pass

> mode---------CavasItem--------Light

uv
alpha
color
light_vector
light_height
light_alpha
light_uv
screen_uv
shadow_color
texture_pixel_size
light (fix)
point_coord


> mode---------Spatial--------Light

pojection

**Comment by Chaosus** [comment]
^^ You should create a separate thread for this..

**Comment by ilyafuu** [comment]
ok, I'll do it now

**Comment by ilyafuu** [comment]
@Chaosus #28514 I had problems 4 commit merge 2 commit that not so should 1 commit it is impossible was update push the godot master :\

potest himself three commit merge of one commit (works) -_-

#28514 so can you copy and send it from the source code after push merge?

**Comment by Chaosus** [comment]
Yeah, I can.. A bit later probably

**Comment by Chaosus** [comment]
@ilyafuu Ok, I fixed it (in correct way) - Enjoy..

**Comment by gamergamesz** [comment]
Is there any way to keyframe Inputs in visual shader graph?

**Comment by ilyafuu** [comment]
`Fresnel`
![image](https://user-images.githubusercontent.com/17591539/57892183-c0d8fa80-7846-11e9-940c-6cac25350824.png)

`OneMinus`
![image](https://user-images.githubusercontent.com/17591539/57892192-c8000880-7846-11e9-9f25-1ae032c9f683.png)

**Comment by fire** [comment]
Are all the issues resolved?

**Comment by ilyafuu** [comment]
the screen viewing shader is very small uncomfortable, choose screen extension whatever taste users
eg
![image](https://user-images.githubusercontent.com/17591539/58196447-ffe9ce80-7cd2-11e9-8993-9f8f8bd5f036.png)

unity shader graph looks great
![image](https://user-images.githubusercontent.com/17591539/58196607-56570d00-7cd3-11e9-8382-dbee80a38ef6.png)

**Comment by arkology** [comment]
Looks like it can be closed. @Chaosus , what do you think?

**Comment by Chaosus** [comment]
Seems like a chaotic compilation of ideas, most of them are already implemented or can be implemented using new plugin system. So I guess, it is fine to be closed. @ilyafuu Please recreate them as separate feature requests if they are still important to you.
