### ISSUE TITLE
[small BUG]: Make Scene Root not making the scene root

### ISSUE THREAD

**Issue by RobertoMalatesta** [godotengine/godot#27995]
**Godot version:**

3.1 stable

**OS/device including version:**
 Linux Kubuntu 18.04 -- irrelevant

**Issue description:**
The option "make scene root" does not what it is intended for, but follows the semantic of "Make scene root IF there is no root scene already defined" ;D

**Steps to reproduce:**

1 - create a project
2 - create a scene A
3 - set it as root
4 - play --> it runs scene A
5 - create another scene B
6 set it as root
7 - press play -> it will still play scene A
 
![image](https://user-images.githubusercontent.com/11835025/56085019-f3a16480-5e3c-11e9-9a21-7d6b84bfbd34.png)

As a workaround we can still change main scene from project options:
![image](https://user-images.githubusercontent.com/11835025/56085044-3f540e00-5e3d-11e9-9d9e-228f6793a0a1.png)

It is a minor bug for this *GREAT* project.

--R

**Comment by KoBeWi** [comment]
You are probably misunderstanding what this option does. It's supposed to make selected node the root of currently edited scene.

E.g. making ChildNode the root in this case
![image](https://user-images.githubusercontent.com/2223172/56087282-f8c7d900-5e67-11e9-83ab-ad826d698841.png)
will produce this
![image](https://user-images.githubusercontent.com/2223172/56087283-01b8aa80-5e68-11e9-9131-ca12632d418d.png)

It works as intended.

**Comment by vnen** [comment]
It is a misunderstanding, but I think the root node should not have this option.

**Comment by RobertoMalatesta** [comment]
Thanks for the explanation @KoBeWi and @vnen .
Glad to see that Godot community is such a nice place !
-- R
