### ISSUE TITLE
Separate editor locale from project locale

### ISSUE THREAD

**Issue by coldblue67** [godotengine/godot#280]
For now, the strings of the gui items are translated by the global translation-server.But sometimes we need to set the locale for the project,and another for the editor.
How about to seperate the locales from the editor and the project?

**Comment by akien-mga** [comment]
The PR @marynate mentioned seems to be #287. It hasn't been merged yet.

**Comment by akien-mga** [comment]
Archiving as all those internationalization issues are now centralized in #3081.
