### ISSUE TITLE
Editor crash when using Round Scalar function in visual shader[GLES2, Win7, intel g41]

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot#28003]
**Godot version:**

v3.1 stable

**OS/device including version:**

Windows 7
Intel g41 express chipset

**Issue description:**

I was following GD quests's video https://youtu.be/sf_Dc4ew3eM
Eveything was going fine until about 7:15 in the video
Here is a GIF
![github](https://user-images.githubusercontent.com/47214394/56089061-6f85c600-5eaa-11e9-97eb-5d41bba92ad7.gif)
Sorry for the bad framerate
The following error in console appered when I clicked the eye icon of the round function

120:
121:    /* clang-format on */
122:
123: #endif
124: }
125:
126: void main() {
127:
128:    vec4 color = color_interp;
129:    vec2 uv = uv_interp;
130: #ifdef USE_FORCE_REPEAT
131:    //needs to use this to workaround GLES2/WebGL1 forcing tiling that textu
res that dont support it
132:    uv = mod(uv, vec2(1.0, 1.0));
133: #endif
134:
135: #if !defined(COLOR_USED)
136:    //default behavior, texture by color
137:    color *= texture2D(color_texture, uv);
138: #endif
139:
140: #ifdef SCREEN_UV_USED
141:    vec2 screen_uv = gl_FragCoord.xy * screen_pixel_size;
142: #endif
143:
144:    vec3 normal;
145:
146: #if defined(NORMAL_USED)
147:
148:    bool normal_used = true;
149: #else
150:    bool normal_used = false;
151: #endif
152:
153:    if (use_default_normal) {
154:            normal.xy = texture2D(normal_texture, uv).xy * 2.0 - 1.0;
155:            normal.z = sqrt(1.0 - dot(normal.xy, normal.xy));
156:            normal_used = true;
157:    } else {
158:            normal = vec3(0.0, 0.0, 1.0);
159:    }
160:
161:    {
162:            float normal_depth = 1.0;
163:
164: #if defined(NORMALMAP_USED)
165:            vec3 normal_map = vec3(0.0, 0.0, 1.0);
166:            normal_used = true;
167: #endif
168:
169:            /* clang-format off */
170: {
171:    vec3 m_n_out2p0;
172:    m_n_out2p0 = vec3(uv, 0.0);
173:    vec3 m_n_out6p0;
174:    float m_n_out6p1;
175:    vec4 m_tex_frg_6_read = texture2D(m_tex_frg_6, m_n_out2p0.xy);
176:    m_n_out6p0 = m_tex_frg_6_read.rgb;
177:    m_n_out6p1 = m_tex_frg_6_read.a;
178:    float m_n_out3p0;
179:    m_n_out3p0 = time;
180:    float m_n_out4p0;
181:    m_n_out4p0 = sin(m_n_out3p0);
182:    float m_n_out5p0;
183:    m_n_out5p0 = abs(m_n_out4p0);
184:    float m_n_out7p0;
185:    m_n_out7p0 = (dot(m_n_out6p0, vec3(0.333333,0.333333,0.333333)) - m_n_ou
t5p0);
186:    float m_n_out8p0;
187:    m_n_out8p0 = round(m_n_out7p0);
188:    color.rgb = vec3(m_n_out8p0);
189: }
190:
191:
192:            /* clang-format on */
193:
194: #if defined(NORMALMAP_USED)
195:            normal = mix(vec3(0.0, 0.0, 1.0), normal_map * vec3(2.0, -2.0, 1
.0) - vec3(1.0, -1.0, 0.0), normal_depth);
196: #endif
197:    }
198:    color *= final_modulate;
199:
200: #ifdef USE_LIGHTING
201:
202:    vec2 light_vec = transformed_light_uv;
203:
204:    if (normal_used) {
205:            normal.xy = mat2(local_rot.xy, local_rot.zw) * normal.xy;
206:    }
207:
208:    float att = 1.0;
209:
210:    vec2 light_uv = light_uv_interp.xy;
211:    vec4 light = texture2D(light_texture, light_uv);
212:
213:    if (any(lessThan(light_uv_interp.xy, vec2(0.0, 0.0))) || any(greaterThan
Equal(light_uv_interp.xy, vec2(1.0, 1.0)))) {
214:            color.a *= light_outside_alpha; //invisible
215:
216:    } else {
217:            float real_light_height = light_height;
218:            vec4 real_light_color = light_color;
219:            vec4 real_light_shadow_color = light_shadow_color;
220:
221: #if defined(USE_LIGHT_SHADER_CODE)
222:            //light is written by the light shader
223:            light_compute(
224:                            light,
225:                            light_vec,
226:                            real_light_height,
227:                            real_light_color,
228:                            light_uv,
229:                            real_light_shadow_color,
230:                            normal,
231:                            uv,
232: #if defined(SCREEN_UV_USED)
233:                            screen_uv,
234: #endif
235:                            color);
236: #endif
237:
238:            light *= real_light_color;
239:
240:            if (normal_used) {
241:                    vec3 light_normal = normalize(vec3(light_vec, -real_ligh
t_height));
242:                    light *= max(dot(-light_normal, normal), 0.0);
243:            }
244:
245:            color *= light;
246:
247: #ifdef USE_SHADOWS
248:            // Reset light_vec to compute shadows, the shadow map is created
 from the light origin, so it only
249:            // makes sense to compute shadows from there.
250:            light_vec = light_uv_interp.zw;
251:
252:            float angle_to_light = -atan(light_vec.x, light_vec.y);
253:            float PI = 3.14159265358979323846264;
254:            /*int i = int(mod(floor((angle_to_light+7.0*PI/6.0)/(4.0*PI/6.0)
)+1.0, 3.0)); // +1 pq os indices estao em ordem 2,0,1 nos arrays
255:            float ang*/
256:
257:            float su, sz;
258:
259:            float abs_angle = abs(angle_to_light);
260:            vec2 point;
261:            float sh;
262:            if (abs_angle < 45.0 * PI / 180.0) {
263:                    point = light_vec;
264:                    sh = 0.0 + (1.0 / 8.0);
265:            } else if (abs_angle > 135.0 * PI / 180.0) {
266:                    point = -light_vec;
267:                    sh = 0.5 + (1.0 / 8.0);
268:            } else if (angle_to_light > 0.0) {
269:
270:                    point = vec2(light_vec.y, -light_vec.x);
271:                    sh = 0.25 + (1.0 / 8.0);
272:            } else {
273:
274:                    point = vec2(-light_vec.y, light_vec.x);
275:                    sh = 0.75 + (1.0 / 8.0);
276:            }
277:
278:            highp vec4 s = shadow_matrix * vec4(point, 0.0, 1.0);
279:            s.xyz /= s.w;
280:            su = s.x * 0.5 + 0.5;
281:            sz = s.z * 0.5 + 0.5;
282:            //sz=lightlength(light_vec);
283:
284:            highp float shadow_attenuation = 0.0;
285:
286: #ifdef USE_RGBA_SHADOWS
287:
288: #define SHADOW_DEPTH(m_tex, m_uv) dot(texture2D((m_tex), (m_uv)), vec4(1.0
/ (256.0 * 256.0 * 256.0), 1.0 / (256.0 * 256.0), 1.0 / 256.0, 1.0))
289:
290: #else
291:
292: #define SHADOW_DEPTH(m_tex, m_uv) (texture2D((m_tex), (m_uv)).r)
293:
294: #endif
295:
296: #ifdef SHADOW_USE_GRADIENT
297:
298:            /* clang-format off */
299:            /* GLSL es 100 doesn't support line continuation characters(back
slashes) */
300: #define SHADOW_TEST(m_ofs) { highp float sd = SHADOW_DEPTH(shadow_texture,
vec2(m_ofs, sh)); shadow_attenuation += 1.0 - smoothstep(sd, sd + shadow_gradien
t, sz); }
301:
302: #else
303:
304: #define SHADOW_TEST(m_ofs) { highp float sd = SHADOW_DEPTH(shadow_texture,
vec2(m_ofs, sh)); shadow_attenuation += step(sz, sd); }
305:            /* clang-format on */
306:
307: #endif
308:
309: #ifdef SHADOW_FILTER_NEAREST
310:
311:            SHADOW_TEST(su);
312:
313: #endif
314:
315: #ifdef SHADOW_FILTER_PCF3
316:
317:            SHADOW_TEST(su + shadowpixel_size);
318:            SHADOW_TEST(su);
319:            SHADOW_TEST(su - shadowpixel_size);
320:            shadow_attenuation /= 3.0;
321:
322: #endif
323:
324: #ifdef SHADOW_FILTER_PCF5
325:
326:            SHADOW_TEST(su + shadowpixel_size * 2.0);
327:            SHADOW_TEST(su + shadowpixel_size);
328:            SHADOW_TEST(su);
329:            SHADOW_TEST(su - shadowpixel_size);
330:            SHADOW_TEST(su - shadowpixel_size * 2.0);
331:            shadow_attenuation /= 5.0;
332:
333: #endif
334:
335: #ifdef SHADOW_FILTER_PCF7
336:
337:            SHADOW_TEST(su + shadowpixel_size * 3.0);
338:            SHADOW_TEST(su + shadowpixel_size * 2.0);
339:            SHADOW_TEST(su + shadowpixel_size);
340:            SHADOW_TEST(su);
341:            SHADOW_TEST(su - shadowpixel_size);
342:            SHADOW_TEST(su - shadowpixel_size * 2.0);
343:            SHADOW_TEST(su - shadowpixel_size * 3.0);
344:            shadow_attenuation /= 7.0;
345:
346: #endif
347:
348: #ifdef SHADOW_FILTER_PCF9
349:
350:            SHADOW_TEST(su + shadowpixel_size * 4.0);
351:            SHADOW_TEST(su + shadowpixel_size * 3.0);
352:            SHADOW_TEST(su + shadowpixel_size * 2.0);
353:            SHADOW_TEST(su + shadowpixel_size);
354:            SHADOW_TEST(su);
355:            SHADOW_TEST(su - shadowpixel_size);
356:            SHADOW_TEST(su - shadowpixel_size * 2.0);
357:            SHADOW_TEST(su - shadowpixel_size * 3.0);
358:            SHADOW_TEST(su - shadowpixel_size * 4.0);
359:            shadow_attenuation /= 9.0;
360:
361: #endif
362:
363: #ifdef SHADOW_FILTER_PCF13
364:
365:            SHADOW_TEST(su + shadowpixel_size * 6.0);
366:            SHADOW_TEST(su + shadowpixel_size * 5.0);
367:            SHADOW_TEST(su + shadowpixel_size * 4.0);
368:            SHADOW_TEST(su + shadowpixel_size * 3.0);
369:            SHADOW_TEST(su + shadowpixel_size * 2.0);
370:            SHADOW_TEST(su + shadowpixel_size);
371:            SHADOW_TEST(su);
372:            SHADOW_TEST(su - shadowpixel_size);
373:            SHADOW_TEST(su - shadowpixel_size * 2.0);
374:            SHADOW_TEST(su - shadowpixel_size * 3.0);
375:            SHADOW_TEST(su - shadowpixel_size * 4.0);
376:            SHADOW_TEST(su - shadowpixel_size * 5.0);
377:            SHADOW_TEST(su - shadowpixel_size * 6.0);
378:            shadow_attenuation /= 13.0;
379:
380: #endif
381:
382:            //color *= shadow_attenuation;
383:            color = mix(real_light_shadow_color, color, shadow_attenuation);

384: //use shadows
385: #endif
386:    }
387:
388: //use lighting
389: #endif
390:
391:    gl_FragColor = color;
392: }
393:
ERROR: _display_error_with_code: CanvasShaderGLES2: Fragment shader compilation
failed:
ERROR: 8:18: 'round' : no matching overloaded function found (using implicit con
version)

   At: drivers/gles2/shader_gles2.cpp:129
ERROR: get_current_version: Method/Function Failed, returning: __null
   At: drivers/gles2/shader_gles2.cpp:364
ERROR: bind: Condition ' !version ' is true. returned: false
   At: drivers/gles2/shader_gles2.cpp:88
ERROR: _get_uniform: Condition ' !version ' is true. returned: -1
   At: drivers/gles2/shader_gles2.h:254

When I connected the output of round function to alpha of the mesh(as per the video), the editor crashed

**Steps to reproduce:**
1.You might need an old computer
2.Create a mesh instance and assign a visual shader to it
3.Follow gd quest's video
4. The error occurs for me at 7:15 in the video

**Minimal reproduction project:**

Open Spatial.tscn . The shader is assigned to meshinstance of sphere

[tuto.zip](https://github.com/godotengine/godot/files/3077067/tuto.zip)

**Comment by clayjohn** [comment]
Was GDquest using GLES2 as well? I would be surprised if he was. 

GLES2 doesnt support "round". It is documented here http://docs.godotengine.org/en/latest/tutorials/misc/gles2_gles3_differences.html and the new visual shader interface coming in 3.2 displays a warning.

**Comment by nikhilCad** [comment]
Okay, he was using GLES3. Can you suggest a workaround?

**Comment by clayjohn** [comment]
Add 0.5 then use "floor". It does the same thing, but it should work in GLES2!

**Comment by akien-mga** [comment]
> GLES2 doesnt support "round". It is documented here http://docs.godotengine.org/en/latest/tutorials/misc/gles2_gles3_differences.html and the new visual shader interface coming in 3.2 displays a warning.

I think it would be worth fixing in 3.1 though. Can't we hide features that aren't supported in GLES2 and would cause a crash?

**Comment by clayjohn** [comment]
Im not sure. The current version (3.2) specifies in the hint if a given function is available. 

@chaosus what do you think?

**Comment by Chaosus** [comment]
I would prefer to show an error message in that case and additionally mark items in the tree with a different color (red for example)
