### ISSUE TITLE
3DLabel

### ISSUE THREAD

**Issue by PiezoMnemonic** [godotengine/godot#28006]
Hi, 
    I've been trying for a day to generate labels that hover over my script generated grid landscape, I've looked into '2D to 3D' and 'GUI in 3D'.  They work but trying to shoehorn those solutions into my project isn't working.  I'd like to know why there isn't a simple '3DLabel' node that puts a plane with text on it with a make billboard checkbox so it always faces the camera if checked.

Thanks

**Comment by LinuxUserGD** [comment]
It think this should be possible with a Sprite3D node.

**Comment by Calinou** [comment]
You could also position a Label dynamically using `Camera.unproject_position()` (and fade/scale it depending on distance if needed).

**Comment by PiezoMnemonic** [comment]
I'd also like to put labels flat on the ground in game, mostly to label distances.  Yes I could just have a library of 0 to 100 sprites but i'd like to prevent the odd instance when you need sprite 101 that just doesn't exist. ( also sprites take up bytes )

**Comment by hubbyist** [comment]
You can use 9 sprites and use them when needed if distances are far enough. You can fetch them to place they are needed and set their coordinates from placeholder object that are already there.

**Comment by LinuxUserGD** [comment]
And you can look at the "GUI in 3D" demo.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3219, as feature proposals are now tracked on the Godot proposals repository.

See also the [3D waypoints](https://github.com/godotengine/godot-demo-projects/tree/master/3d/waypoints) demo for displaying controls in a 3D world without using viewports.
