### ISSUE TITLE
Crash related to python scripts

### ISSUE THREAD

**Issue by menip** [godotengine/godot#28001]
Note: Not sure if this should be reported here or at https://github.com/touilleMan/godot-python.

**Godot version:**
3.1

**OS/device including version:**
Linux

**Issue description:**
Assume you have project open utilizing python, and a node in that project with a python script attached. Clicking on script to open it causes godot to crash.
Assume you have project open utilizing python, and some node. If you try to add python script to that node, godot will crash.
Assume you have a project open utilizing python, with  some node as well as a python script. Dragging python script to that node will result in crash. 

Note in all these cases desired action is performed, just have crash. Script is created, added, opened, as is visible by opening godot again.

**Steps to reproduce:**
In fresh project, open up asset lib and install the python package. 
Create new node, proceed to add new python script to it.
Observe crash. Note that upon opening project again, you will see that the python script file is created.

**Minimal reproduction project:**

.zip added so Github not complain :woman_shrugging: 
[GodotPythonTest.7z.zip](https://github.com/godotengine/godot/files/3076901/GodotPythonTest.7z.zip)

Note that project runs fine. In uploaded one I set sprite to some middleish screen position on `_ready()` as an example.

**Comment by menip** [comment]
Update: While I can reliably reproduce this on 3.1, I have no issues on master.

**Comment by vnen** [comment]
It should be reported on the godot-python repository until it's confirmed there's something to fix in Godot itself.

**Comment by menip** [comment]
From more testing seems it is issue with godot-python.
Thanks
