### ISSUE TITLE
Wrong word in docs

### ISSUE THREAD

**Issue by rhberro** [godotengine/godot#2800]
# if/else/elif

Simple conditions are created by using the if/else/elif syntax. Parenthesis around statements is allowed, but not **requiered**. Given the nature of the tab-based indentation, elif can be used instead of else:/if: to mantain a level of indentation.

at https://github.com/godotengine/godot/wiki/gdscript

**Comment by akien-mga** [comment]
It seems to be fixed in http://www.godotengine.org/projects/godot-engine/wiki/GDScript
The GitHub wiki will soon be closed to the profit of the above-linked OpenProject one.
