### ISSUE TITLE
Connecting signal to a method window

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#28018]
**Godot version:** 3.2 ad1368a

**OS/device including version:** Win10 64bit

**Issue description:**
New window for connecting signal to a method has check box for advanced options that opens additional stuff, if you open that window, check advanced and make a connection or cancel the window (close the window), when you open it again, windows will show advanced options, but the advanced box will be unchecked, you need to click advanced again to turn it on and again to turn it off, it seems that the window starts in the previous state and then needs to be refreshed.

**Steps to reproduce:**
Open node connect window, check advanced, make connection, when you open that window again, it will show advanced options but advanced button will be unchecked. 
![Capture](https://user-images.githubusercontent.com/9384421/56095791-9fe85700-5ee0-11e9-9197-fc419f411749.PNG)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Seems fixed in the current master branch. It stays ticked as "Advanced".
