### ISSUE TITLE
HTML5 Windows Export Bad File Endings

### ISSUE THREAD

**Issue by JASGames** [godotengine/godot#2801]
There is an issue with the Html5 exporter which adds extra lines and weird characters to the end of the exported files in windows however for linux it is fine.

![Image of Issue](http://i.imgur.com/2vphIjW.png)

I believe this is code that's causing the issue because if it removed the extra lines and character aren't added.

    static void _fix_html(Vector<uint8_t>& html,const String& name,int max_memory) {

	String str;
	String strnew;
	str.parse_utf8((const char*)html.ptr(),html.size());
	Vector<String> lines=str.split("\n");
	for(int i=0;i<lines.size();i++) {

		if (lines[i].find("$GODOTTMEM")!=-1) {

			strnew+=lines[i].replace("$GODOTTMEM",itos(max_memory*1024*1024))+"\n";
		} else if (lines[i].find("$GODOTFS")!=-1) {
			strnew+=lines[i].replace("$GODOTFS",name+"fs.js")+"\n";
		} else if (lines[i].find("$GODOTMEM")!=-1) {
			strnew+=lines[i].replace("$GODOTMEM",name+".mem")+"\n";
		} else if (lines[i].find("$GODOTJS")!=-1) {
			strnew+=lines[i].replace("$GODOTJS",name+".js")+"\n";
		} else {
			strnew+=lines[i]+"\n";
		}
	}

	CharString cs = strnew.utf8();
	html.resize(cs.size());
	for(int i=9;i<cs.size();i++) {
		html[i]=cs[i];
	}
    }

The code above doesn't specifically add extra lines ie it works fine in linux, but the string class its using could be the cause.

**Comment by est31** [comment]
I think I had this too, with the linux exporter.
