### ISSUE TITLE
"Insert Animation Key" shortcut ("K") does nothing

### ISSUE THREAD

**Issue by Dentoid** [godotengine/godot#28025]
**Godot version:**
3.1 Stable

**OS/device including version:**
Windows & MacOS

**Issue description:**
The shortcut "K" for inserting a transform keyframe appears to do nothing

**Steps to reproduce:**
Create a Spatial and a connected AnimationPlayer with a new animation
Make sure Animation editor is open
Select the Spatial
Press "K"
Bask in the void of nothingness

**Minimal reproduction project:**
Not included

**Comment by EiZi233** [comment]
We still don't have a hotkey for inset Key frame, or do we?
