### ISSUE TITLE
The "Select node" dialog has wrong style

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#28029]
Godot 3.1

Steps to reproduce:
1) Create a MeshInstance
2) Click on the `Skeleton` property:

![image](https://user-images.githubusercontent.com/1311555/56099787-53fdd800-5f09-11e9-93cc-67be4795f375.png)

Notice the title bar looks strange.

**Comment by Vultraz** [comment]
Seems to be something with the style of `Tree` not meshing (no pun intended) well with `WindowDialog`.
