### ISSUE TITLE
Add a function to get the current cursor shape.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#28024]
**Godot version:**
3.1+

**OS/device including version:**
All systems

**Issue description:**
There should be a function to get the current mouse cursor shape. I assume it should be on the OS singleton, but Input also deals with setting the cursor, so it might make more sense there.

The reason I want this is because I want to create a custom cursor for my game, but I want it to have animation, resizing, and other effects. So I can't just set a custom cursor image, I need to hide the cursor and use a Sprite as a cursor substitute. I still want to use the cursor shapes from GUI nodes to change my custom cursor though, but there's no function that gets the current shape of the cursor.

**Comment by akien-mga** [comment]
CC @guilhermefelipecgs
