### ISSUE TITLE
BMP image loader fails to import images with 8, 4 and 1 bit depths

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#28020]
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:**
Try to load `.bmp` images with 8, 4 and 1 bit depth, it will fail to import them.
Loading 24 bit images works alright since #20038.

I know the bmp hate but here it is 🐛.

**Minimal reproduction project:**
[bmp-8bit-import.zip](https://github.com/godotengine/godot/files/3077681/bmp-8bit-import.zip)

**Comment by akien-mga** [comment]
CC @SaracenOne

**Comment by Xrayez** [comment]
@SaracenOne note that I'm currently working on palette support in images that could help to solve this. Actually I've made some progress already on this, but you could fix it independently of whether the feature is merged or not (#28013).

**Comment by Xrayez** [comment]
For reference, the issue with importing 8-bit bmp images was fixed in my PR using the new palette API https://github.com/godotengine/godot/pull/28013/commits/45917aca3c9cc857ccbf25c3da48330fd4c0207a, I suppose it would be relatively easy to do the same with 4-bit and 1-bit images.
