### ISSUE TITLE
Renaming editor tabs

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#28023]
**Godot version:**
3.2

**OS/device including version:**
Any

**Issue description:**
currently the editor still has Inspector and Node as tabs that are not true to the function they perform. Instead I propose renaming them to Properties/Signals/Groups for visibility and more streamlined editor experience/practice. This seems very legacy-ish [v1.0]

**Steps to reproduce:**

*Minimal reproduction project:**

**Comment by akien-mga** [comment]
Could you be more explicit? This seems pretty subjective to me.

The Inspector has not changed its function, if its name was correct in 1.0, it still is today. It's a panel which lets you inspect the properties of a node, as such its name seems accurate. For sure it could be named "Properties" instead, but I don't see much incentive to rename it just for the sake of it (and it would require updating documentation and would make all thirdparty tutorials referring to it obsolete).

The Node panel didn't exist in 1.0... And it contains two tabs named Signals and Groups. Renaming it "Signals/Groups" doesn't seem like a good idea. There's already another proposal to split it into two docks: #27629.

**Comment by Duroxxigar** [comment]
Seeing how this is marked as a discussion - I'll throw my voice in there.

I don't believe that they should be renamed. The **Inspector** tab is quite descriptive in what it does. It "inspects" the properties of a node. Or even it is an "Inspector" dock for the currently selected node. I feel like it just semantics at that point though.

Splitting the **Node** dock into two different ones that represent the sub-menu, I do think is a good idea.

**Comment by Calinou** [comment]
Closing due to lack of support. As for the Node dock, this should be discussed in #27629.
