### ISSUE TITLE
Pressing F5 sometimes opens project manager due to Windows file locking limitations

### ISSUE THREAD

**Issue by Vultraz** [godotengine/godot#28036]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10

**Issue description:**
Every so often, when I press F5 to start my project, the Project list opens instead.

**Comment by Chaosus** [comment]
Related https://github.com/godotengine/godot/issues/11391, though now it happens quite rarely

**Comment by Vultraz** [comment]
I wouldn't say rarely. I'll definitely see it more than once on any given day doing development in Godot.

**Comment by harrisyu** [comment]
Yes,  it's  rare, but I can confirm it happens.

**Comment by akien-mga** [comment]
As far as I know this happens if some process has locked your `project.godot` file (might be Godot itself by saving it before running) and Windows is sadly incapable of reading a file that it being written to.

One solution could be to enforce a delay between saving and running the project to make sure that Windows file accesses won't conflict.

**Comment by mhilbrunner** [comment]
I may be wrong, I've only started looking at this, but:

 https://github.com/godotengine/godot/blob/09e94aa087485ccf5b4318c4a619db4f6b067cc5/drivers/windows/file_access_windows.cpp#L117

We seem to use `_wfopen_s()` on Windows.

The [Windows docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-s-wfopen-s?view=vs-2019) for that state:

>Files that are opened by fopen_s and _wfopen_s are not sharable.
If you require that a file be sharable, use _fsopen, _wfsopen with the appropriate sharing mode constant—for example, _SH_DENYNO for read/write sharing.

And if you look for `_SH_DENYNO` and `fsopen()`, those seem to be used a lot in OSS code to get around similar issues.

Example: https://codereview.chromium.org/668022

>**Issue 668022: Change default fopen() on Windows from fopen_s() to fsopen(,,_SH_DENYNO)**
>Change default fopen() on Windows from fopen_s() to fsopen(,,_SH_DENYNO). fopen_s() won't let you open a file that is open by another process. This has the unfortunate property of triggering a race condition in Python exposed by running run-webkit-tests using a lot of threads and spawning off image_diff. There doesn't seem to be a good reason to disallow files that are open in other processes, so I'm changing this.

So could this be a possible fix?

**Comment by Zylann** [comment]
If the file was shareable, would it still allow to read it properly and not half-modified? I find it strange that Godot attempts to modify it while launching the game (without waiting for the project to be properly saved, that is).

**Comment by Calinou** [comment]
By default, Godot always saves the project before running. You can disable this in the Editor Settings (**Run → Auto Save → Save Before Running**). Try disabling it and see if the bug still occurs to confirm this.

**Comment by mhilbrunner** [comment]
I'm working on a PR to address the locking behaviour as per my comment above, may take some time however, file locking is icky to test.

**Comment by Brickcaster** [comment]
This is happening to me.  It seems to happen quite consistently when I edit a script and then attempt to run the project.  If I use play scene instead, I get a window with nothing but gray inside.

Using Windows 7, Godot 3.1.1

https://cdn.discordapp.com/attachments/477544613511692358/581843684916723733/unknown.png

**Comment by PolarisJunior** [comment]
happens very frequently to me, windows 10 godot 3.1.1. When it starts happening it usually continues happening unless I fiddle around with my tabs. Usually playing with scene view open instead of script editor works.

**Comment by Chaosus** [comment]
@mhilbrunner Do you have any progress?

**Comment by pgoral** [comment]
Happens very frequently to me too on latest build

**Comment by MidZik** [comment]
Never happened to me before upgrading to 3.1.2. Now it happens multiple times a day.

**Comment by TheMoye** [comment]
Hi there,

I have the same issue, and maybe it's just a coincidence, but it seems more present since 3.2.
For me it's by pressing F6.
Fun fact : if I define a main scene in the project settings, F6 (on another scene) no longer launches the project manager but the main scene. 🤷‍♂️

https://www.youtube.com/watch?v=NzuZhAc7N8I

Using Windows 10 Pro 64bits v1909 (18363.592) and Godot v3.2.stable.official / Same issue on Debian (WSL)

**Comment by NoodleSushi** [comment]
Happens to me after editing shaders or opening a singleton CanvasLayer scene in v3.2.2rc1, not even sure if it's just a coincidence or not.

**Comment by Avarobin** [comment]
On win 7, godot 3.2.3, always after editing shaders. Even if I change to another scene tab.

**Comment by Skaruts** [comment]
I've been having this problem for a long time (since 3.1, I think). I've returned to Godot from a long hiatus since yesterday, and it's been happening to me quite a lot (on 3.2.3.stable), which is why I'm here. Sometimes it does this many times in a row.

I'm on Windows 7.

**Comment by Calinou** [comment]
@NoodleSushi @Skaruts @Avarobin Does the workaround below work? I'm trying to isolate what could be the cause of the issue.

> By default, Godot always saves the project before running. You can disable this in the Editor Settings (**Run → Auto Save → Save Before Running**). Try disabling it and see if the bug still occurs to confirm this.

**Comment by akien-mga** [comment]
Can anyone still reproduce this issue on 3.2.3 or 3.3?

**Comment by Zylann** [comment]
I remember having it one or two times in the past 12 months or so. It's been incredibly rare to me, but it did happen.

**Comment by OverloadedOrama** [comment]
> Can anyone still reproduce this issue on 3.2.3 or 3.3?

@akien-mga It happened to me today when I was editing a shader, using 3.2.3-stable. The issue usually occurs when I'm editing shaders. I haven't noticed it happening any other time.

**Comment by mhilbrunner** [comment]
So, I got finally around to it :) With https://github.com/godotengine/godot/pull/51430, most cases of this should now be fixed in Godot 4.0.

Please let us know if you still run into this in the future!
