### ISSUE TITLE
Conflicting values for NOTIFICATION constants and docs out of sync

### ISSUE THREAD

**Issue by perbone** [godotengine/godot#28034]
Hi,

**Godot version:**
Master branch at this point
https://github.com/godotengine/godot/tree/42032669238bdc807bc7b8f03fff87e6cb5847f1

**Issue description:**
There are conflicting values for NOTIFICATION constants between
https://github.com/godotengine/godot/blob/master/scene/gui/control.h#L265
https://github.com/godotengine/godot/blob/master/scene/2d/canvas_item.h#L240
and
https://github.com/godotengine/godot/blob/master/scene/3d/spatial.h#L120
 
This commit 
https://github.com/godotengine/godot/commit/a18989602b00f2940befa0b780af14efc7603dd8#diff-97a2869611748b85a70fc262a8876ed4
introduced documentation errors into
https://github.com/godotengine/godot/blob/master/doc/classes/MainLoop.xml#L116

-- Perbone

**Comment by reduz** [comment]
There's not really any conflict, I'm wondering why you may be misunderstanding the notification system. Just use the constants in proper class hierarchy, they are not global numbers.

**Comment by reduz** [comment]
The notifications you see on a class are the ones this class can receive. There are not cases where a class receives a notification from a different one (unless it inherits from it).

**Comment by perbone** [comment]
Well, I thought about the possibility of not being global, yet I found it strange that only these classes had repeated values. Anyway, I think the documents should reflect the code, right?

**Comment by akien-mga** [comment]
Translations synced in 09e94aa08.
