### ISSUE TITLE
AnimatedSprite: Add from spritesheet only works on 1:1 splits

### ISSUE THREAD

**Issue by manokara** [godotengine/godot#28030]
**Godot version:**
4203266

**OS/device including version:**
Solus 4.0 (Linux 5.0)

**Issue description:**
The title says it all, but here's some gifs:

3x4
![Peek 14-04-2019 16-26](https://user-images.githubusercontent.com/3709789/56100542-67507980-5ef0-11e9-950a-97faa96d924e.gif)

4x2
![Peek 14-04-2019 20-06](https://user-images.githubusercontent.com/3709789/56100573-c8784d00-5ef0-11e9-8f51-a503d6eedf9d.gif)

3x3
![image](https://user-images.githubusercontent.com/3709789/56100744-e8107500-5ef2-11e9-8d13-533df3458003.png)

**Comment by avencherus** [comment]
@reduz
