### ISSUE TITLE
Can't name a custom resource class name the same as its filename

### ISSUE THREAD

**Issue by TheRealCatherine** [godotengine/godot#28041]
**Godot version:**
3.1-stable-win64

**OS/device including version:**
Windows 10 64bit

**Issue description:**
To get a custom resource type listed in the New Resource... list you have to(?AFAIK?) use class_name in the resource file definition. If you put the same thing in class_name as the filename then you will get errors like

> res://story/Characters/Character.gd:2 - Parse Error: Unique global class 'Character' already exists at path: res://characters/Character.gd
>  modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR

this also prevents the fields of the resource from being visible in the inspector

**Steps to reproduce:**
1) create a new script called Character.gd with the following contents:
> extends Resource
> class_name Character
> 
> export var some_number : int

2) create a new resource of this type
3) open the newly created resource - notice you cannot see the "Script Variable" section in the inspector and the error message on the console

**Comment by TheRealCatherine** [comment]
After posting this I realized the path in the error was different....
What happened was I closed every file open in the editor and used the godot file browser to move Character.gd from /story/Chararacters to /characters and then reopened it and created the resource.

Apparently the _ACTUAL_ issue is that the file manager in Godot does not deal with a moved resource definition file very well and doesn't close out the old one when the file is moved.

**Comment by slapin** [comment]
Would you mind changing the bug description so to not confuse people?

**Comment by akien-mga** [comment]
> Apparently the ACTUAL issue is that the file manager in Godot does not deal with a moved resource definition file very well and doesn't close out the old one when the file is moved.

It would be clearer if you could open a new issue for that, as it would be confusing to handle it in this issue which was about a quite different symptom.
