### ISSUE TITLE
to_json func error on Android Platform

### ISSUE THREAD

**Issue by diegoph** [godotengine/godot#28042]
**Godot version:**
Godot Engine 3.1 Stable (using  custom packages for Android compiled from master)

**OS/device including version:**
Debian/Deepin

**Issue description:**
The to_json () function does not work on Android, linux works perfectly. The same is true for ConfigFile and JSON.print () with a different error message.

04-15 03:00:06.973  6107  6150 I godot   : OpenGL ES 2.0 Renderer: Adreno (TM) 506
04-15 03:00:07.403  6107  6150 E godot   : **SCRIPT ERROR**: Invalid type in built-in function 'parse_json'. Cannot convert argument 1 from Dictionary to String.

Thanks

**Steps to reproduce:**
Run code in Android

var a = { 'a': 1, 'b': 2 }
var b = to_json(a)
print_debug(b)

**Comment by volzhs** [comment]
> using custom packages for Android compiled from master

are you using 3.1 stable editor with custom android packages from master which 3.2?

**Comment by diegoph** [comment]
> > using custom packages for Android compiled from master
> 
> are you using 3.1 stable editor with custom android packages from master which is 3.2?

Yes. sorry, I compiled the editor to 3.2 and it's working now. My bad.
