### ISSUE TITLE
Still collision after removing/freeing CollisionPolygon2D node

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#2804]
I have this structure:

```
Area2D
     -> Node2D
           -> CollisionPolygon2D
```

If I `free()` or `remove_child()` the Node2D Object or the CollisionPolygon2D there will still be collisions detected.

**Comment by reduz** [comment]
yes those nodes (CollisionPolygon and CollisionShape) are, at the moment,
just helpers. They will become the actual collision information in 2.1 or
3.0, but for now you can access collision shapes via the CollisionObject2D
API

**Comment by akien-mga** [comment]
Collision shapes and polygons will be reworked for 3.0.

**Comment by reduz** [comment]
this is solved
