### ISSUE TITLE
AnimationPlayer, bezier curve breaks the timeline

### ISSUE THREAD

**Issue by deepmax** [godotengine/godot#28048]
**Godot version:** 3.1

**OS/device including version:** Ubuntu

Putting a bezier curve track to change a property after an existing track, it doesn't follow the timeline.

**Steps to reproduce:**
1. Put a property track which changes sprite's y-position from A to B
2. Put a bezier curve track which changes sprite's y-position from B to C

Playing the animation, there is gap (not playing first track) and then it plays the second track.

(Note that, if I use normal property tracker instead of bezier, it works fine)

![Screenshot from 2019-04-15 15:55:33](https://user-images.githubusercontent.com/8607244/56129503-83f3bc80-5f97-11e9-8c78-dcb4117c636f.png)

**Minimal reproduction project:**
[anim-player.zip](https://github.com/godotengine/godot/files/3079845/anim-player.zip)

Is it working properly? How to have A -> B -> C sequence using bezier curves?

**Comment by svenfinke** [comment]
I just tried to replicate this problem in Godot 3.1 on Manjaro, and it works without any problems. Even with the bezier curves, the animation always starts from the beginning and includes the first regular property track.

![2019-04-16-083456_965x1345_scrot](https://user-images.githubusercontent.com/564499/56187357-9404ae00-6022-11e9-8962-11ee4877fe7f.png)

**Comment by deepmax** [comment]
Strange. Would you upload your working project? I tried lots of ways to make it work.

**Comment by bojidar-bg** [comment]
Note that the example project animates only the Y component of position using a regular track on `position`, and then has a bezier track on `position.y`.
Unfortunately, animation tracks update the target property even when when not between two keys, unless it is a regular track in trigger mode. Tracks are applied in a top-to-bottom order, and thus the bezier track overrides the changes of `position.y` coming from the normal track, resulting in the observed behavior.
This can be workarounded either by using multiple animations (and adding a track for setting `current_animation` or for calling `play`) or by using multiple nodes (one moving from A to B, the other from 0,0 to B-C)

**Comment by akien-mga** [comment]
Closing as it's working properly as per above comments.
