### ISSUE TITLE
Can't see an icon for Autokeyframe on the toolbar.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#28043]
**Godot version:**

f213055e11b06c02414e6e62ea719e870c140a1b

**OS/device including version:**

Win10 64bit

**Issue description:**

In a recent built, haven't been able to see the icon for this new feature.  Appears to work when clicking, but no visual indicator of when its toggled for me.

![godot windows tools 64_2019-04-15_10-27-35](https://user-images.githubusercontent.com/13004169/56117016-dfaa4f80-5f6f-11e9-9f17-a94c6fae3b89.png)

@reduz

**Comment by Calinou** [comment]
This should be fixed as of https://github.com/godotengine/godot/commit/5d65100669e8a8ece09677feb744c69b4466aa90.

![image](https://user-images.githubusercontent.com/180032/56131582-2310b800-5f88-11e9-836b-d36248953040.png)
