### ISSUE TITLE
Font oversampling doesn't work with custom viewports

### ISSUE THREAD

**Issue by IsjaslawEisenstadt** [godotengine/godot#28045]
**Godot version:**
3.1 Stable

**OS/device including version:**
Windows 7

**Issue description:**
Controls with text won't benefit from font oversampling when placed inside a Viewport and a Viewportcontainer.

**Steps to reproduce:**
Create a DynamicFont and assign it to a Label. Put the Label inside a Viewport and put the Viewport inside a Viewportcontainer. Enable Font Oversampling in the project settings and set the stretch mode to 2D and aspect to keep. The Label will get blurred upon resizing the window when running the project.
Filter and mipmaps in the DynamicFont doesn't resolve it either.

**Minimal reproduction project:**
[viewport_oversampling_mrp.zip](https://github.com/godotengine/godot/files/3079213/viewport_oversampling_mrp.zip)

**Comment by Calinou** [comment]
Font oversampling is currently a global property that scales all DynamicFonts with the same factor, so maybe we need the ability to selectively disable it for specific DynamicFont resources.

**Comment by reduz** [comment]
Font oversampling is a global setting, so it will not work on custom viewports.
I think the solution here would most likely to allow disabling it in individual fonts.

**Comment by winNixz** [comment]
Why would it be a solution to have a toggle for disabling font oversampling on individual fonts when it already doesn't work?

My problem is that I'd like to alpha mask a VBoxContainer with all of its Label children. My current solution would be to place the container inside a Viewport, but the fonts will be pixelated when I do this. Calinous solution is only a bandaid fix and doesn't look good on most resolutions.

**Comment by Calinou** [comment]
>  My current solution would be to place the container inside a Viewport, but the fonts will be pixelated when I do this.

Last time I checked, you can enable filtering on a ViewportTexture that's applied to a Sprite or TextureRect by editing it then enabling the **Filter** flag.

**Comment by TheMoye** [comment]
I don't know if it's the same issue, but I have this Warning on console with fresh 3.2 Godot release :

![godot_warning](https://user-images.githubusercontent.com/46683101/73435036-296df600-4348-11ea-82a6-8b1ef6e89c6c.jpg)

**Comment by Calinou** [comment]
@TheMoye Font oversampling doesn't make sense if you use the `disabled` or `viewport` stretch modes. There's no way you can render a font at an higher resolution and actually benefit from the increased resolution in those modes.

**Comment by TheMoye** [comment]
Hi @Calinou ,

Okay, I can understand that. But why is Godot giving me this Warning? Especially since I don't use any font. My scene tree doesn't contain any character nodes (label, richtextlabel...) 🤷‍♂️

**Comment by Calinou** [comment]
@TheMoye Disable **Rendering > Quality > Dynamic Fonts > Use Oversampling** in the Project Settings.

**Comment by kuruk-mm** [comment]
I'm having the same problem. I need to draw some texts inside a Viewport.

I have "Use Oversampling" enable, and I use `2d` strech mode.

Look this image:
![image](https://user-images.githubusercontent.com/12563266/85639383-f3b30c00-b65e-11ea-8222-e7e485be675a.png)

First image is from Viewport, and the second one is outside the Viewport (it is using the same DynamicFont)

Project structure:
![image](https://user-images.githubusercontent.com/12563266/85639495-51dfef00-b65f-11ea-836c-cb8b9b1118fa.png)

Project:
[TestViewportText.zip](https://github.com/godotengine/godot/files/4828437/TestViewportText.zip)

I already test every option in the Viewport, and I searched and tried a lot, haha.

**Comment by kuruk-mm** [comment]
Ok, I found a solution for this problem.

When the game resizes I resize the custom viewport to fit it parent, and I put a Camera2D in the custom viewport to zoom in to get the same proportion.

Here is the script (to keep_height), you can change how the zoom is calculated keep or keep_width.
```
func _ready():
	_screen_resized()
	get_tree().connect("screen_resized", self, "_screen_resized")

func _screen_resized() :
	var custom_viewport = $ViewportContainer/Viewport
	var camera_2d = $ViewportContainer/Viewport/Camera2D
	custom_viewport.size = get_tree().get_root().size
	camera_2d.zoom.x = ProjectSettings.get("display/window/size/width") / custom_viewport.size.x
	camera_2d.zoom.y = camera_2d.zoom.x
```

Result:

![image](https://user-images.githubusercontent.com/12563266/86276031-919c5e80-bbaa-11ea-9c93-0a65fb62849d.png)

Example project:
[TestViewportText.zip](https://github.com/godotengine/godot/files/4859543/TestViewportText.zip)

With this, I have had some problems with TileMaps in some resolutions (black lines between tiles), but I limited the resolutions and it's working well.

**Comment by bmolyneaux** [comment]
> @TheMoye Disable **Rendering > Quality > Dynamic Fonts > Use Oversampling** in the Project Settings.

Perhaps the error message should instead say to disable font oversampling if you are using Viewport stretch mode. It's not obvious that font oversampling is a project setting.

**Comment by Calinou** [comment]
> Perhaps the error message should instead say to disable font oversampling if you are using Viewport stretch mode. It's not obvious that font oversampling is a project setting.*

I was thinking about doing this a few days ago, but it makes the warning message quite long. I'll do it anyway.

**Comment by Calinou** [comment]
@bmolyneaux This is already the case:

https://github.com/godotengine/godot/blob/398a625a9f37fe6e45a5da075f8796d26378004d/scene/main/scene_tree.cpp#L1156

https://github.com/godotengine/godot/blob/398a625a9f37fe6e45a5da075f8796d26378004d/scene/main/scene_tree.cpp#L1239

**Comment by Calinou** [comment]
This is now addressed in two ways:

- The font oversampling factor can be set on a per-DynamicFont basis using the `oversampling` property greater than `0.0` (exclusive). In your custom Viewports that do not resize with the window, force the oversampling on the fonts used within the viewport to a value like `1.0`.
  - In 3.5.rc, this property is `override_oversampling` on DynamicFontData.
  - In 4.0.alpha, this property is `oversampling` on Font.
- In 4.0.alpha, MSDF font rendering can be used for crisp rendering at any resolution, without requiring oversampling (and therefore avoiding re-rasterization when the viewport scale changes).
