### ISSUE TITLE
Strange omni light (shadows?) artifacts

### ISSUE THREAD

**Issue by ZZZZZcode** [godotengine/godot#28047]
**Godot version:**

3.1 Stable

**OS/device including version:**

Win 7/Geforce GTX 1070

**Issue description:**

I got strange black flickering artifacts when moving camera around game object.
Here is the video of the artifacts:
https://youtu.be/Ci09nsg-v1c

I have 1 directional light (global) + 1 omnilight + shadows enabled
Omnilight placed inside the room (at the center)

**Steps to reproduce:**
Hmm...

**Minimal reproduction project:**
Sorry cannot provide that

**Comment by qarmin** [comment]
GLES 2 or GLES 3?

**Comment by ZZZZZcode** [comment]
GLES3

**Comment by clayjohn** [comment]
@ZZZZZcode Can you provide any more information or a MRP? without either one of those there is no way that anyone can do anything.

**Comment by ZZZZZcode** [comment]
I create test project and post link here.

**Comment by ZZZZZcode** [comment]
I am tried to reproduce this bug on side test project - no result for now, sorry. All shadows looks ok. I need more time to find the problem.

**Comment by clayjohn** [comment]
Okay! Closing for now. If you are able to reproduce the bug please open another issue with steps to reproduce!
