### ISSUE TITLE
Different values with similar statements.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#28055]
**Godot version:**
3.1.

**OS/device including version:**
N/A

**Issue description:**
Consider these two lines of code, where `damage` is defined as an int `var damage: int = 10`.

`damage *= 0.5`
`damage = damage * 0.5`

The first statement returns 0. The second statement returns 5.

My understanding is that the two assignment statements should be the same. If they're not supposed to be, then this is not documented anywhere.

**Comment by MunWolf** [comment]
PROGRAMMER TALK:

Probably because damage *= 0.5 is converting the 0.5 to an int which results in it becoming 0.
This is a bug in the type preference of the operation,

**Comment by Zylann** [comment]
That makes me vaguely think of https://github.com/godotengine/godot/issues/26332#issuecomment-467684334
