### ISSUE TITLE
suggest to split script files and help reference

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#2805]
I tested with commit 18e014a193840141911789aacf57b28a2e001724.
I found help tab removed and can open many help reference.
It looks good.
But, I feel not comfortable to see all opened gdscript with help reference in one list.

How about split list to show gdscript and reference separately?

![godot](https://cloud.githubusercontent.com/assets/8281454/11236681/9637874e-8e1e-11e5-803b-a705e1bd383d.jpg)

**Comment by akien-mga** [comment]
That's a very good idea IMO. I also like the ability to have several help pages open at once, but I don't like them mixed with my scripts and sorted alphabetically.

So the above suggestion would be a nice addition; an alternative could be to show help tabs first and then scripts, with a separator between them, but still in the same widget.

**Comment by reduz** [comment]
the proposed change is pretty difficult, but what could be done easily is sort the items so scripts appear first  and help pages appear last. Would that be enough?

**Comment by volzhs** [comment]
@reduz that would be enough for me :)
