### ISSUE TITLE
you guys have to change input-control-coding like unity

### ISSUE THREAD

**Issue by he-eh** [godotengine/godot#28063]
float translation = Input.GetAxis("Vertical") * speed;
        float rotation = Input.GetAxis("Horizontal") * rotationSpeed;

like this, 

look at.

how beautiful?

**Comment by novhack** [comment]
Godot handles axis control pretty well. Using action system enables devs to have all the inputs handled in the same way. https://godotengine.org/article/handling-axis-godot

**Comment by Calinou** [comment]
As @novhack said, axis handling was revised in Godot 3.1, making controller support easy to implement.
