### ISSUE TITLE
Editor Animation Tools - No Horizontal Scrolling

### ISSUE THREAD

**Issue by ScepticDope** [godotengine/godot#28077]
**Godot version:**
3.1.1 Mono 2fbc421

**Issue description:**
I'd like to be able to horizontal scroll in the Animation Tools. Now I have to move my cursor over the horizontal scrollbar and then start scrolling scroll with my regular mouse-wheel.

I'd very much like to just scroll with my horizontal mouse-wheel when inside the animation tools timeline.

**Comment by KoBeWi** [comment]
Resolved by #56756
