### ISSUE TITLE
Editor Animation Tools - Add pause button, change stop behaviour for productivity.

### ISSUE THREAD

**Issue by ScepticDope** [godotengine/godot#28078]
**Godot version:**
3.1.1 Mono 2fbc421

**Issue description:**
I'd like to suggest we add a pause button to the animation tools and change the stop behavior.

- Stop button, stops animation and moves timeline cursor back to where the cursor was when animation was started. (Still hotkey-D)
- Pause button, stops animation and places timeline cursor on current position. (Currently how stop works now) (I suggest hotkey-F, this way S, D and F will be your goto play-controls when using the animation tools.)

When working on even the simplest animation after I test it I have to move my cursor back to the wanted positon manually, which becomes very frustrating.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/167, as feature proposals are now tracked on the Godot proposals repository.
