### ISSUE TITLE
Rigidbody doesn't sleep if `can_sleep` is subsequently set to `false` and `true`

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#28076]
Godot 3.1
Bullet physics

Repro steps:
1) Create a rigid body in midair and set it to kinematic mode
2) After a short time, switch it to rigid mode, and at the same time, set its `can_sleep` property twice like this:
```
can_sleep = false
can_sleep = true
```
3) Watch it fall, and notice it never goes to sleep. I expected it to sleep since it was last allowed to sleep.

Test project: play main scene and watch.
[RigidbodyCannotSleepAnymoreIfCanSleepIsSetTwice.zip](https://github.com/godotengine/godot/files/3082619/RigidbodyCannotSleepAnymoreIfCanSleepIsSetTwice.zip)

Note: I found this behavior by testing workarounds to #28075

**Comment by rogeriodec** [comment]
Similar issue: https://github.com/godotengine/godot/issues/27715

**Comment by madmiraal** [comment]
I can confirm that this was fixed with #27730.

**Comment by akien-mga** [comment]
Fixed by #27730.
