### ISSUE TITLE
Comment shortcut for Visual Script

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28079]
In GDscript we can do Ctrl+K to comment/uncoment one or more lines. Maybe the same could be done in Visual Script, so Ctrl+K puts a comment node around the nodes you selected. Manually configuring a comments size is very tedious and could be made way easier with this.

**Comment by fire** [comment]
I also want the ability to group nodes and the comment node actually moving them as a group. #20490  #20325

**Comment by Jummit** [comment]
Closing as VisualScript isn't part of Godot anymore.
