### ISSUE TITLE
Quat(Vector3 euler) constructor is broken

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#28086]
**Godot version:** 3.1 stable

**OS/device including version:** any

**Issue description:** as stated in title. there is work around, by setting Euler "set_euler(Vector3 euler)" after create Quad using default constructor. but still it have to work right ?

**Steps to reproduce:** -

**Minimal reproduction project:** -

**Comment by aaronfranke** [comment]
Since #27792 is on the 4.0 milestone, this issue should be too.
