### ISSUE TITLE
Feature Request: Invert X- and Z-axis option for navigation in Editor 3d-view

### ISSUE THREAD

**Issue by MartinMajewski** [godotengine/godot#28082]
**Godot version:**
3.1

**OS/device including version:**
MacOS 10.14.5 beta

In addition to the already solved post where an invert Y-axis option was requested (https://github.com/godotengine/godot/issues/16926) I would like to ask for the same feature for the X- and Z-axis.

Actually, I'm wondering why this option wasn't implemented for all axis at once.
As a touchpad the only user I feel uncomfortable navigating the 3D view in Godot, especially while orbiting the scene. As I'm using Fusion 360 for many hours a day, I would love to be able to emulate the same intuitive touchpad navigation in Godot.

Best wishes,
Martin

**Comment by Calinou** [comment]
@MartinMajewski Should this impact only orbit navigation, or also panning as well? What about 2D?

**Comment by YBPN** [comment]
It would be good to have this for trackpad users. I can invert the Y axis, but I need to invert sideways movement too. This is for both orbiting and panning. 

Freelook already works as expected.

**Comment by angadmishra** [comment]
Panning in 2D already works as intended on macOS, and respects the systemwide "Scroll direction: Natural" found in System Preferences > Trackpad.

> Orbiting and panning work as desired if I disable the “Scroll direction: natural” setting in my macbook’s trackpad settings. However, it would be great to be able to do this just in Godot without affecting system-wide scrolling.

Maybe not "as desired," but as "expected," I guess. To clarify for whoever can implement this change, changing this setting in macOS system preferences doesn't alter Godot's 3D behaviour, just makes the rest of macOS work like Godot currently does (with invert Y axis disabled).

So Godot's 2D view respects system scroll direction, whereas 3D view can only be partly made to match it (that too only for orbit) with the Invert Y axis option. **Ideally, Godot could have a "Natural Trackpad Direction" option that functions exactly like Blender's does, that inverts Y and X axis for orbiting and panning in 3D view.**

**Comment by molevision** [comment]
The invert Y axis currently also inverts mouse movement (such as when fly navigating while holding down right click). This is unexpected behaviour, and the invert X axis option does not do this. Ideally this option should not invert Y for the mouse.
