### ISSUE TITLE
Suggestion: Move the profiler and monitor away from the bottom panel

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#28087]
It could be useful if the profiler and monitor were moved away from the bottom panel. The first reason is that it's nice to set `always_open_output_on_play` to true, but this makes the output tab steal focus from the debugger tab on play. You then need to open the profiler/monitor again and reclick the game. This could be fixed by introducing another flag that would keep them focused when they are I suppose. However, and second point, I sometimes want to see the game's output at the same time as the profiler/monitor.

They're too horizontal so I don't think it's a good idea to just allow them to be moved to a different dock. ~~Maybe an option would be to move them (and maybe Video Mem) to a new workspace? There shouldn't be any "usability" conflict between this new monitoring workspace and the others, unlike in the bottom panel.~~ _Not a good idea!_

Maybe the best solution is to keep them in the bottom panel, but make sure the output tab doesn't steal focus when they are already open?

**Comment by fire** [comment]
If you're able to visually imagine where it would go and make a mockup that'll help the discussion.

**Comment by isaacremnant** [comment]
@fire: Good point, I tried my best. I modified my interface a lot, but the main idea is that the new workspace would be a new dock only for the profiler/monitor/video mem, like when expanding the bottom panel. The debugger would stay where it is but only include the Debugger, Errors and Misc tab.
![image](https://user-images.githubusercontent.com/35355161/56230845-1ef99e80-604b-11e9-8be5-aafbab48b277.png)

**Comment by fire** [comment]
How do you handle the use case of seeing the 3d scene while profiling?

**Comment by TheDuriel** [comment]
Moving the monitors to the center is not really helping the issue tbh. You can also already see your output in the editors shell window (windows), or the one you launched Godot from (linux, mac).

Having the current scene open, as well as a performance monitor, is quite valuable for debugging. As you can move things around in your scene and see its impact on performance live. Especially helpful when fighting overdraw and the effects of _lighting_.

Side note: Having _any_ scene open in the editor impacts the performance of the launched game, and will result in potentially drastically worse performance.

**Comment by Zireael07** [comment]
Having the scene open in editor currently does nothing except kill performance, as the running game and editor aren't connected (except for remote scene tree)

**Comment by isaacremnant** [comment]
People didn't seem to interested in this, closing.
