### ISSUE TITLE
Cannot apply material if mesh .obj is modified.

### ISSUE THREAD

**Issue by aomimezura** [godotengine/godot#28088]
**Godot version:**

3.1

**OS/device including version:**

Ubuntu 14.04
Also using OpenGL 2 (haven't tested 3)

**Issue description:**

Cannot apply material to MeshInstance if original .obj mesh file is overwritten.

**Steps to reproduce:**
Create a MeshInstance. Add a mesh by loading a .obj file. Load a material into the MeshInstance (surfacematerial 0, not applied to the mesh itself). Tab away from the editor. Make a change to the .obj and overwrite the original. Go back to the editor. 

The mesh will be updated and will still show the original material, but the material property may or may not be empty, and when running, the material is not shown.

When you click on the material, the option to clear is not there. Try to load the material. It will not apply and just change to empty.

Clearing and reloading the mesh does not fix this. (I was not able to reproduce this in the example) In my case, the only way to fix it is to delete the MeshInstance itself and recreate it.

**Minimal reproduction project:**

Run the project, see the material is applied correctly. Now copy shape.obj from the shape1 folder, paste into the obj folder, and overwrite the shape.obj in there. In the editor, the material shows correctly, but run it and see the material is gone. Try reapplying the material (material/0) and see the material property turns blank. Running shows the material is still gone.

[MeshInstanceBug.zip](https://github.com/godotengine/godot/files/3086149/MeshInstanceBug.zip)

**Comment by KoBeWi** [comment]
Fixed in 4.0 (although still valid in 3.2.3 rc3)
