### ISSUE TITLE
Anchor property not updating position

### ISSUE THREAD

**Issue by MunWolf** [godotengine/godot#28083]
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
When changing the anchor property on Control it does not update the position, if you change the margin after changing the anchor it instead modifies any of the properties to keep it where it is relative to the anchor except the one you changed.

**Steps to reproduce:**
Create a new user control scene
Set anchor right and bottom on the root Control to 0
Observe the Control does not change in the viewport
Set margin left to 1
Observe how it set margin right and bottom to values so that the Control doesnt change.

**Comment by groud** [comment]
Note: this is fixed on master.

**Comment by MunWolf** [comment]
Nice, I will close this issue then, thanks for the good work!
