### ISSUE TITLE
Create a shortcut key to increase tab indentation

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#28096]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
On script editor, to reduce the tab indentation I press `Shift+Tab` in **any position** on the line. 
But to increase the line indentation,  I have to make at least **two moves**, ie, or go to the beginning of the line or select the line first and then press `Tab`. 
Ie, my suggestion is: one move to decrease and one move to increase indentation.
Like `Ctrl+Shift+Tab` to increase the indentation with the cursor in any position.
Just a better usability.

**Comment by Calinou** [comment]
Are there any other editors implementing this? <kbd>Ctrl + Shift + Tab</kbd> will likely be taken to cycle backwards between scene/script tabs in the future.

**Comment by cbscribe** [comment]
Is there a problem with these shortcuts?

![Screen Shot 2019-04-16 at 12 38 49 PM](https://user-images.githubusercontent.com/3812514/56238996-b8718200-6044-11e9-90e8-de88c4e049ad.png)

**Comment by rogeriodec** [comment]
Sorry, I made a question before in Discordapp.com but no one knew the answer, but now I see. Thanks.

**Comment by cbscribe** [comment]
I recommend browsing through the "Shortcuts" tab. There are lots of useful things to be found. :)

**Comment by rogeriodec** [comment]
The `indent left` and `indent right` labels are inverted, ie, it might be the opposite.
May I create an issue?
