### ISSUE TITLE
The indent left and indent right key labels are inverted

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#28098]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
The `Indent Left` and `Indent Right` key labels are inverted, ie, they are doing the opposite.

![](https://user-images.githubusercontent.com/3812514/56238996-b8718200-6044-11e9-90e8-de88c4e049ad.png)

**Comment by cbscribe** [comment]
Note: this is not the indent shortcut labels but rather the key labels. This happens when you use `[` and `]` in InputMap as well.

**Comment by rogeriodec** [comment]
Updated.
