### ISSUE TITLE
Help source font size without range becomes unreadable when set to a big number

### ISSUE THREAD

**Issue by gsegovia2018** [godotengine/godot#28105]
Godot version 3.2

OS/device including version:
MacOs Mojave 10.14.3
McBook Air 13 (2015)

Issue description:
I modified the help source font size in the editor settings and when I increase it to a big number the help text becomes unreadable. We should set a range for the help source font size.

![Screen Shot 2019-04-17 at 1 41 26 AM](https://user-images.githubusercontent.com/46790538/56251246-1c329400-60b3-11e9-94ca-40cb5ae58833.png)

Steps to reproduce:
Editor->Editor Settings-> Text_Editor -> Help -> Help Source Font Size

**Comment by akien-mga** [comment]
Fixed by #28107.
