### ISSUE TITLE
Layout menu doesn't respect scaling

### ISSUE THREAD

**Issue by Vultraz** [godotengine/godot#28108]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
If a node has scaling other than 1 (say, 0.5) and you use Layout -> Center, it will place its top-left corner as if its scale was 1. You can see this since the node will be properly centered if you set its scale back to 1.

**Comment by volzhs** [comment]
cc @groud

**Comment by KoBeWi** [comment]
Duplicate of #19068

**Comment by groud** [comment]
Indeed, closing as a duplicate
