### ISSUE TITLE
Create a shortcut key to return to the previous line on Script Editor

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#28102]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
If the cursor goes to another part of the script and I want the cursor returns to the line it was previously.
Ex: if the cursor is in line 150, I press Ctrl+Home accidentally and it goes to line 1, I want to press a key to return this line 150.

**Comment by KoBeWi** [comment]
Duplicate of #16554
