### ISSUE TITLE
HBoxContainer: The order of elements is not updated on viewport.

### ISSUE THREAD

**Issue by danilojr** [godotengine/godot#2810]
1  Put some buttons as children of a HboxContainer, 
2  Change the order of buttons in scene editor (move node up / move node down),

issue:
The order of elements is not updated on viewport.

expected:
real-time update.

ps: The elements get updated only if I use hide and unhide in scene editor.

godot 2.0 alpha

**Comment by akien-mga** [comment]
Closing as duplicate of #2809, they are almost exactly about the same thing, and the resolution will likely be the same.
