### ISSUE TITLE
Improve error log colours in the Windows terminal

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2811]
This is a follow-up to #2737 where terminal colours were improved for Unix. A similar improvement could be done for the Windows terminal, and both @ZuBsPaCe and @vnen have already been looking into it:
* https://github.com/godotengine/godot/pull/2737#issuecomment-155610141
* https://github.com/godotengine/godot/pull/2737#issuecomment-155625066

Maybe one of you two would like to handle this one directly?

**Comment by vnen** [comment]
I'll try to look into this tomorrow. Seems very easy to do and can use the same colors as the Unix version AFAIK. @ZuBsPaCe is free to get ahead of me if he have the time.

**Comment by ZuBsPaCe** [comment]
Ok, I'll take a look at it, @vnen.

**Comment by ZuBsPaCe** [comment]
Found two Visual studio compile errors due to all the other merged pull requests. Need to fix them first. Pull requests coming.
