### ISSUE TITLE
Enabling YSort property on Tilemap removes shader effect

### ISSUE THREAD

**Issue by CngKO** [godotengine/godot#28115]
**Godot version:**
3.1 official

**OS/device including version:**
Windows 10.0.17134 Build 17134

**Issue description:**
I am using the following sprite outline shader that was provided by the community:

	shader_type canvas_item;
	render_mode unshaded;
	
	uniform float width : hint_range(0.0, 16.0);
	uniform vec4 outline_color : hint_color;
	 
	void fragment()
	{
		vec2 size = vec2(width) / vec2(textureSize(TEXTURE, 0));
	
		vec4 sprite_color = texture(TEXTURE, UV);
	
		float alpha = sprite_color.a;
		alpha += texture(TEXTURE, UV + vec2(0.0, -size.y)).a;
		alpha += texture(TEXTURE, UV + vec2(size.x, -size.y)).a;
		alpha += texture(TEXTURE, UV + vec2(size.x, 0.0)).a;
		alpha += texture(TEXTURE, UV + vec2(size.x, size.y)).a;
		alpha += texture(TEXTURE, UV + vec2(0.0, size.y)).a;
		alpha += texture(TEXTURE, UV + vec2(-size.x, size.y)).a;
		alpha += texture(TEXTURE, UV + vec2(-size.x, 0.0)).a;
		alpha += texture(TEXTURE, UV + vec2(-size.x, -size.y)).a;
	
		vec3 final_color = mix(outline_color.rgb, sprite_color.rgb, sprite_color.a);
		COLOR = vec4(final_color, clamp(alpha, 0.0, 1.0));
	}

I am using it on a tilemap. When the tilemap's ysort property is enabled, the shader stops working.

From:
https://godotengine.org/qa/43740/enabling-ysort-on-tilemap-removes-shader-effect

**Steps to reproduce:**
In the project attached below:
    - disable ysort for Tilemap3
    - enable ysort for Tilemap3
    - notice that the outline shader stops working when ysort is enabled

**Minimal reproduction project:**
[ysort-tilemap3.zip](https://github.com/godotengine/godot/files/3088507/ysort-tilemap3.zip)

**Comment by bojidar-bg** [comment]
This is somehow caused by the outer YSort node -- using the tilemap with the ysort flag on by itself does not trigger the issue.
