### ISSUE TITLE
Disable Nodes

### ISSUE THREAD

**Issue by hasahmed** [godotengine/godot#28113]
It would be convenient to to be able to disable nodes (i.e. the scripts attached to the nodes) with a toggle, just like visibility.

**Comment by Zireael07** [comment]
@groud: Remember that you pause the whole tree, not individual nodes, as far as code it concerned. Yes, the toggle allows a lot of things, but if you want to pause a single node, it's very inconvenient.

**Comment by hasahmed** [comment]
Duplicate of #9029
