### ISSUE TITLE
Holding Ctrl + Alt and then resizing is different than resizing and then holding Ctrl + Alt

### ISSUE THREAD

**Issue by Jayman2000** [godotengine/godot#28118]
**Godot version:**
v3.1.stable.official

**OS/device including version:**
KDE neon User Edition 5.15 x86-64

**Issue description:**
When editing many nodes in the 2D workspace, the user is able to resize the node using handles located on the node's sides. Clicking and dragging the top center handle allows the user to change the nodes height without accidentally changing its width. The user can use the following keyboard shortcuts to have more fine grained control over how the node is resized:

1. Pressing Ctrl + Left Click makes the node resize in fixed increments.
2. Pressing Alt + Left Click makes the node resize equally from each side. 

Holding both Ctrl + Alt at the same time applies both effects at once. The order in which the shortcuts are entered does not normally matter (i.e., beginning the resize, and then holding Ctrl is the same as holding Ctrl, and then beginning the resize). When holding both Ctrl + Alt order does matter. Starting the resize, and then pressing Ctrl + Alt applies both effects to the resize. Pressing Ctrl + Alt, and then starting the resize allows the user to change the node's width even if the user is grabbing on to the top center handle. Changing the width this way is much more sensitive than changing the node's width or height normally.

I would expect that holding Ctrl + Alt before the resize starts would produce the same result and holding Ctrl + Alt after the resize starts. I would not expect that holding Ctrl + Alt would allow the user to change the node's width while the user is grabbing on to the top center handle. I would not expect Ctrl + Alt to alter the sensitivity at which the node is being resized. I would not expect the sensitivity of resizing the node's width to be different than the sensitivity of resizing the node's height.

**Steps to reproduce:**

1. Open a scene with a resizable node in the 2D workspace (Example.tscn in the minimal reproduction project).
2. Hold Ctrl + Alt, and begin to resize the node using the top center handle.
3. While resizing, move the mouse left or right.

**Minimal reproduction project:**
[Resize Bug.zip](https://github.com/godotengine/godot/files/3088838/Resize.Bug.zip)

**Comment by KoBeWi** [comment]
This is not a bug. Alt + Ctrl is shortcut for scale when select tool is active (similar to how Ctrl is rotate), while Alt (not Ctrl + Alt) is used for resizing in all directions. You can't enable the normal scale while you are already resizing, and you can't activate rotating either. The behavior is ok.
