### ISSUE TITLE
AnimationTree Transition Node Cross-Fades over Bind Pose

### ISSUE THREAD

**Issue by Cygon** [godotengine/godot#28119]
**Godot version:** 3.1 stable, official build

**OS/device including version:** Gentoo Linux 4.19.27, KDE5 Plasma, GTX 1080 w/proprietary drivers 418.43 

**Issue description:** The transition node in Godot 3.0's `AnimationTreePlayer` used the "Xfade Time" to blend between the previously active animation and the switched-to animation.

Using Godot 3.1's `AnimationTree` with an `AnimationNodeBlendTree` as root node, the transition always takes place between animation 0 and the switched-to animation:

![transition-issue](https://user-images.githubusercontent.com/3613175/56279914-56c71b80-6109-11e9-9e6c-0eec64a1457e.gif)

In the above animation, when going from animation 2 to 3 or from animation 3 to 4, the transition node does not cross-fade between the relevant animations, but between animation 0 and 3 or between animation 0 and 4 respectively.

**Comment by bojidar-bg** [comment]
Might be by design, can you try using multiple transition nodes?

**Comment by David-Ochoa** [comment]
It may not be the animation interpolating between first and other animations, but a problem when interpolating and the end frame and start frame between animations is the same, It has happened to me, but it was a light "bump up". Try removing your default and see what happens (I had to remove some frames from the animation to make it work)

**Comment by Cygon** [comment]
@bojidar-bg I can't think of a way to use multiple `Transition` nodes to avoid the issue (even if I tried to have one for each set of animations with a similar stance, it would fail when the main `Transition` node switches).

@David-Ochoa The animations should be okay. They work fine in the old `AnimationTreePlayer` and if I disable "Auto Advance" in the new `Transition` node, they loop perfectly without any hickups.


However, while checking both of your suggestions I've now discovered that it's not the first animation it's cross-fading over but the bind pose. Even if I fill the entire transition node with identical animations (or different ones minus the `Neutral` one), it will do what's shown in the above video.

The bind pose generally has the character's arms outstretched (A- or T-pose), so I can't imagine cross-fading over that would ever be useful out there.

**Comment by volzhs** [comment]
cc @guilhermefelipecgs

**Comment by Cygon** [comment]
Hrm... if "Xfade Time" is set to 0 (the default value for any new `Transition` node), then the `Auto Advance` property is ignored and the active state just loops. Set it to 0.01 and it works :thinking:

**Comment by Cygon** [comment]
Eek! Even the new "Animation State Machine" has similar bugs.

If I set up a Transition with "Switch Mode" set to "At End" and also enable "Auto Advance", it will auto advance the moment the animation starts playing, rather than at the end of it.

And the cross-fade over bind pose issue is present, too, if I set a the "Xfade Time" on any transition to a value greater than 0:

![godot3-animation-state-machine](https://user-images.githubusercontent.com/3613175/56345713-b3d1d880-61c0-11e9-9467-63b47492c8cf.png)

So cross-fade is currently broken. And if I turn off cross-fade, auto advance also stops working. :face_with_head_bandage:

**Comment by volzhs** [comment]
AFAIK, crossfade uses blend.
so, #27562 and #27562 possibly fix it.

**Comment by Cygon** [comment]
@volzhs Indeed!

I tried with the current Git master 6697fd9a05859914fc320b4b4321fd9fb6170f71 and PR #27562 and both issues are gone.

Sorry for not trying this earlier, it seemed like the official 3.1 build was still fresh but I guess it's already been a month :smile:

**Comment by volzhs** [comment]
glad to hear that! :smiley:

**Comment by ChaseAColvin** [comment]
This issue is back in the current 4.x.  Affects cross-fades in both state machines and blend trees.
