### ISSUE TITLE
Documentation VSplitContainer: Description has a copy&paste error

### ISSUE THREAD

**Issue by mrcrb** [godotengine/godot#28117]
See https://docs.godotengine.org/en/3.1/classes/class_vsplitcontainer.html

It says: Vertical split container. See SplitContainer. **This goes from left to right.**

It is the same text from https://docs.godotengine.org/en/3.1/classes/class_hsplitcontainer.html

It should say: This goes from top to bottom.

**Comment by bojidar-bg** [comment]
Kudos for opening the issue on the right repository :smiley:

**Comment by 2bit-hack** [comment]
Could I be allowed to fix this? It's just changing "left to right" to "top to bottom", right?
