### ISSUE TITLE
Uncomenting lines doesn't register as a single undo action

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#28112]
**Godot version:** cea49f0

**Issue description:** Uncomment a few lines with Ctrl+U then undo. Each line is a separate undo action. This doesn't happen when toggling comments with Ctrl+K, all lines are un-toggled at once.

(btw, I may be blind but I couldn't see Ctrl+U in the Shortcuts, is it missing as an editor property?)

**Comment by griant** [comment]
Control+U is not a registered shortcut. You can use Control+K to toggle comments.

**Comment by austinprog** [comment]
If anyone is not working on this I will give a try at fixing this bug?

**Comment by 123epsilon** [comment]
Hey, could I work on this? I'm new to the engine but I'm looking to learn by contributing here. A little push to start would be great too - thanks!

**Comment by Calinou** [comment]
@123epsilon This was already worked on in https://github.com/godotengine/godot/pull/28190, but the pull request author needs to amend it before it can be merged.
