### ISSUE TITLE
Option to move playback buttons

### ISSUE THREAD

**Issue by AfterCadaver** [godotengine/godot#28127]
**Godot version:**

**OS/device including version:**

**Issue description:**

I might find it aesthetically pleasing if I could move the scene buttons to the right or center.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Jummit** [comment]
What do you mean by right? At the right edge or at to top right?

**Comment by dreamsComeTrue** [comment]
@AfterCadaver can you provide any screenshot/paint image describing your idea?

**Comment by Calinou** [comment]
Closing due to lack of response from OP. Also, note that feature proposals must now be opened on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository.
