### ISSUE TITLE
Skeleton2D toolbar menu items. Language change proposal.

### ISSUE THREAD

**Issue by bitbutter** [godotengine/godot#28124]
The menu items under the Skeleton2D Toolbar menu currently read:

> Make rest pose (From Bones)
> Set bones to rest pose

I notice it takes me a while to figure out which I need each time I see both of these. I'd like to propose a language change I think would make them easier to parse.

**The problem**
The top operation is destructive and can mess up your rig, the lower operation much less so. But the current language makes it hard to quickly grasp this distinction.

Despite the 'Set' command being the safer of the two commands in most contexts (returning the rig to the safety of a pre-defined pose), 'Set' sounds like a (more) _destructive_ operation than 'Make' because 'Set' implies _overwriting_ a single variable in a way that 'Make' doesn't. In many contexts 'Make' adds _another_ of something, without overwriting anything. But in this case 'Make' does overwrite something.

**Proposal**
Change the order and use the following labels:

> Return to rest pose
> Overwrite rest pose

With these labels, the effect of each operation can be inferred from its first word. Which makes them faster to parse.

'Return' comes first because it's likely to be used more often. The word 'Return' is better fit with the (relative) safety of the operation than 'Set' is. ('Revert to rest' pose would also work fine).

'Overwrite' comes next. The word communicates the destructive nature of the command, signalling that a bit more caution is required. ('Set rest pose' would work too, having the advantage of making sense even before a rest pose has been set, but I believe 'Overwrite' is even clearer).

**Godot version:** 3.1

**Comment by bojidar-bg** [comment]
Wouldn't "Reset" be better than "Return"?

**Comment by bitbutter** [comment]
Reset would work too (but perhaps not if 'Set' was being used for the other command).
