### ISSUE TITLE
Tilemap Editor Changes Editor Scale on Small Screens Constantly

### ISSUE THREAD

**Issue by ssoher** [godotengine/godot#28135]
**Godot version:**
3.1 official stable

**OS/device including version:**
Windows 10 / Didn't test on any other platforms

**Issue description:**

When painting tiles in the TileMap node, if the window is small enough that not all the panels fit the screen, Godot editor scales all the panels constantly to fit the status label (the label that shows the coordinates and the tile name under the mouse cursor, check the gif below)

![tilemap_scale_bug](https://user-images.githubusercontent.com/4283979/56312932-00ce9400-615a-11e9-83e2-23bf090e9e4c.gif)
![Screenshot_5](https://user-images.githubusercontent.com/4283979/56313051-4ab77a00-615a-11e9-9356-5e0930ca297c.png)

**Steps to reproduce:**
* Create a TileMap, paint at least 2 tiles with different names
* Resize the window so it's small enough to not fit all the panels
* Hover your cursor over your tiles

**Comment by StratoSil** [comment]
![spaz](https://user-images.githubusercontent.com/31358851/64502516-761b3c80-d294-11e9-811a-ea48160cda49.gif)
Happens to me frequently as well as I like to keep the godot window half the width of my screen.
Drives me nuts.
Also using W10 and 3.1.

**Comment by akien-mga** [comment]
CC @groud @YeldhamDev

**Comment by YeldhamDev** [comment]
I wonder if the coordinates could be moved into the canvas itself instead of the top bar, which gets pretty filled up when a `TileMap` is selected.
