### ISSUE TITLE
Enhance member editor in VisualScript

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28137]
When you currently select a member you rename it, which is not very user-friendly. You should be able to edit the variable if you click on it.
![image](https://user-images.githubusercontent.com/28286961/56318426-738e3e00-615f-11e9-9c49-ec9a93f6c0b4.png)
![image](https://user-images.githubusercontent.com/28286961/56318434-7721c500-615f-11e9-9520-17e4285a61e1.png)

**Comment by Jummit** [comment]
Here is what I would do:
When you click on a function/variable/signal, it's properties get shown in the inspector, like with anything in Godot. I don't know exactly how that would, since the inspector only shows resources. With functions that is very simple, as there is already a VisualScriptFunction resource.

**Comment by DavidCambre** [comment]
> Here is what I would do:
> When you click on a function/variable/signal, it's properties get shown in the inspector, like with anything in Godot. I don't know exactly how that would, since the inspector only shows resources. With functions that is very simple, as there is already a `VisualScriptFunction` resource.
> I would also get rid of the `= var` after variables, as it is not consistent with the other members and is very confusing.

Or only edit when using Control+E and in that popup allow the user to change the name

**Comment by Jummit** [comment]
This should be a proposal, closing.
