### ISSUE TITLE
Tileset Editor scroll not appearing / working

### ISSUE THREAD

**Issue by yesitsmattharris** [godotengine/godot#28143]
**Godot version:**
3.1 stable

**OS/device including version:**
Mac 10.14.4 Mojave

**Issue description:**
Tile Editor scrollbar doesn't appear until zoom in / out has been clicked, regardless of whether there is content out of view

**Steps to reproduce:**
1. Create a tilemap and load any tileset
2. Click on the tileset to bring up the tileset editor
3. Select a / the only texture (ensure the texture is large enough to be scrollable)
4. Click on the main window of the tileset editor (click to expand if not expanded) and try to scroll - scroll doesn't work and scrollbar doesn't appear in expanded mode
5. Click on the zoom in or zoom out button - scrollbar appears and will now work (temporarily)

**Minimal reproduction project:**
[tileset.zip](https://github.com/godotengine/godot/files/3093850/tileset.zip)

1. Open scene.tscn
2. Click on Tilemap node and then on the tileset to bring up the tileset editor
3. Zoom in so the scrollbar appears
4. Click on the Node2D node and repeat steps 1 and 2.
5. Scrollbar doesn't appear or work.

**Comment by yesitsmattharris** [comment]
Doesn't seem to want to replicate on a new project, but it happens in my existing projects:

No scrollbar:
![Screenshot 2019-04-17 at 23 12 58](https://user-images.githubusercontent.com/9336959/56324380-92dc9980-6166-11e9-94e1-d4ee2631f292.png)

Scrollbar after editing zoom and returning to previous zoom level:
![Screenshot 2019-04-17 at 23 13 06](https://user-images.githubusercontent.com/9336959/56324383-94a65d00-6166-11e9-857e-71b81e59f410.png)

**Comment by clayjohn** [comment]
Please provide a minimal reproduction project so contributors can test it. 

If you can't repro from a blank project then neither will others. 

Thank you!

**Comment by yesitsmattharris** [comment]
Hi @clayjohn - I've added a minimal reproduction project and additional steps in how to reproduce the bug within it. Thanks!

**Comment by KoBeWi** [comment]
I tried reproducing it with the provided project and it doesn't seem to happen. Can someone affected confirm it?

**Comment by jbwyatt4** [comment]
Posted a video detailing the steps and what to look for.

https://www.youtube.com/watch?v=aVdYAdoVw9U

**Comment by jbwyatt4** [comment]
I am looking at possibly solving this.

Where is the code for the 'Expand Bottom Panel' button?

**Comment by akien-mga** [comment]
> Where is the code for the 'Expand Bottom Panel' button?

The simplest way to find it is to use a grepping tool:
```
$ rg "Expand Bottom Panel"
editor/editor_node.cpp
6206:   bottom_panel_raise->set_shortcut(ED_SHORTCUT("editor/bottom_panel_expand", TTR("Expand Bottom Panel"), KEY_MASK_SHIFT | KEY_F12));
```

**Comment by kojow7** [comment]
This still seems to be an issue in Godot 4.5.1
