### ISSUE TITLE
Suggestion: fly mode shortcuts changes

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#28156]
I suggest to change the shortcuts in fly mode to make it compatibly with AZERTY keyboards.
Forward: W or Z
Backward: S
Left: A or Q
Right: D
Upward: Space
Downward: Ctrl

**Comment by MissKraya** [comment]
I use Q and E for vertical movement a fair amount, I don't know how much other people do but I think this would be better as an editor option you can toggle... better yet allow for complete editor key rebinding?

**Comment by Calinou** [comment]
Duplicate of #11777.
