### ISSUE TITLE
Set RigidBody transform doesn't work when called inside area signals

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#28155]
**Godot version:**
6697fd9a05859914fc320b4b4321fd9fb6170f71

**Issue description:**
Is not possible to use set_global_transform on a RigidBody to teleport it inside a signal on area enter.

I think that the problem is due to the fact that just after signal propagation the physics server set the object positions.

**Comment by AndreaCatania** [comment]
The problem is due to the fact that when the transformation is added inside the area signal, it is overwritten just after by the physics transformation update.

This is "Fixable" in two ways.

The **first** solution is make sure to call the areas dispatcher after the rigid bodies dispatcher (inside Bullet).
The problem of this solution is that in case we want to teleport a body when it impacts with another body  we still have this problem.

The other solution is to make aware Godot when it should or shouldn't update the body transform with the physics engine transform.

Since the first solution doesn't really fix the problem entirely I prefer to not implement it, rather I prefer to implement a work around in the game.

In case we decide to implement the second solution, I'll be glad to implement it. For now I'm closing this.

**Comment by AndreBentesOliveira** [comment]
hello.
I have this same problem in my code, how can you help me apply these proposed solutions?
I'll be very thankfull.
