### ISSUE TITLE
Input Map compatible with AZERTY keyboards by default

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#28157]
I suggest to make the Input Map compatible with AZERTY by adding:
ui_up: z key
ui_left: q key

**Comment by groud** [comment]
Related #20527

**Comment by bojidar-bg** [comment]
The default `ui_up` action does not contain the <kbd>w</kbd> key either. Maybe you meant to open this issue elsewhere?

**Comment by Calinou** [comment]
Now that [physical scancodes](https://github.com/godotengine/godot/pull/18020) were added, this is now feasible. We need to figure out how to expose it from the Editor Settings, though.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/5185, as feature proposals are now tracked on the Godot proposals repository.
