### ISSUE TITLE
Networking disconnects after some time

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#28168]
From Discord:
>Does anyone else have issues where their client just gets disconnected no matter what after a few minutes?
It's happening FAR less when I don't use a rpc() call back to the client after receiving one. I can reproduce it pretty much every time when just doing that. Make rpc to server, that method makes rpc back to the client. Is there any reason why it's bad to do that?

User `ex` on Discord provided a server and client project reproducing this behaviour reliably for them. (Thanks for the effort, by the way!)

Info:
>Think I have it so it's reproduced every time. I'm not even sure if it's that the client is disconnecting. The client freezes first, it seems (not sure if that's due to a dc).
>Here's a zip of the client/server project. Don't feel like messing with github right now. Might be able to later.
>1. Start server
>2. Start client
>3. Wait. Without fail, client crashes/dcs after a few minutes (often times happens when the counter hits around 8,000 for me)
>
>(Godot 3.1 stable)
>windows 10 pro, ryzen 2700x, Intel(R) I211 Gigabit Network Connection.
over localhost (client/server on same comp)

[dc-crash-bug.zip](https://github.com/godotengine/godot/files/3096602/dc-crash-bug.zip)

**Comment by Juankz** [comment]
I have experienced this. The client returns the following error when freezing:
```
ERROR: get_unique_id: Condition ' !active ' is true. returned: 0
At: modules/enet/networked_multiplayer_enet.cpp:638.
```

**Comment by Juankz** [comment]
Update 2: It happens when using unreliable calls

**Comment by Faless** [comment]
This is going to be a nasty bug to track, thanks for reporting.
I confirm it only seems to happen when running both instances in the editor (more correctly, when one editor is listening), I think it might be a memory issue somewhere, but I'll need to investigate further.
