### ISSUE TITLE
Space key not received by _input(e) when holding S and D key together.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#28169]
**Godot version:**

4ad255a078da0e9cc2

**OS/device including version:**

Win10 64bit

**Issue description:**

Discovered today when trying to move my character about, that when holding S and D together, the Space key (jump in my case) will no longer appear as a key event from `_input(event)`.

Maybe other combinations are affected?  Most other keys I have setup worked fine.

**Steps to reproduce:**
Hold S and D key down together, then start tapping Space, and check the input events.

**Minimal reproduction project:**

[3.2 Space Key Not Working.zip](https://github.com/godotengine/godot/files/3095008/3.2.Space.Key.Not.Working.zip)

**Comment by avencherus** [comment]
Was having extreme doubts about this one, it is hard to believe it would have gone unnoticed this long given WASD + space being so common.

Testing on other platforms, it seems to be something specifically going awry with my keyboard.  O_o

**Comment by Zireael07** [comment]
Just a tip, google "keyboard ghosting" (however, for WASD + space to be affected is indeed weird)

**Comment by avencherus** [comment]
@Zireael07 Thanks, had no idea that was the term for it, that helps a lot.  I've experienced "ghosting" with lots of keys all at once, but yeah this one may be a curious defect in the wiring, or maybe a driver issue.

**Comment by avencherus** [comment]
Resolved it.  

For anyone that may stumble here, in testing this morning the keyboard issue only happened on one specific user account.  The culprit program appears to be a screenshot app called ShareX.  I have differing key bindings I believe, so it is likely consuming the input events.
