### ISSUE TITLE
Make variables not be null by default in VisualScript

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28173]
If you create a new setter node or a change the type of a member variable it will be set to null by default. If you want to set a boolean variable to false, you have to click twice for it to not be null.
Also, why is it that when you set a member variable to the `String` type for the first time that it sets displays the text as `Null`, although it should be `[Null]`?

**Comment by fire** [comment]
Is this a missing assignment to the false or 0 bit pattern value?

**Comment by fire** [comment]
This is the same bug as https://github.com/godotengine/godot/issues/27611
