### ISSUE TITLE
GLES2: Flag "Disable Ambient Light" in spatial material doesn't work

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#28171]
**Godot version:**
Godot 3.1 stable

**OS/device including version:**
Zorin OS core 12.4

**Issue description:**
The Disable Ambient Light flag in the spatial material doesn't work.

**Steps to reproduce:**
- Create a material
- Check Disable Ambient Light to true
- Nothing happens

Posible related: #27061

**Comment by clayjohn** [comment]
This can be copied directly from the GLES3 code.
