### ISSUE TITLE
Expose ScriptEditor's Active TextEdit for EditorPlugins

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#28170]
**Godot version:** 3.1-official

**Issue description:**

I'm thinking about making more EditorPlugins, especially related to the Script editor, but there is a problem, is not very easy to figure out which TextEdit is current active. So it would be really useful to have access to it via the `ScriptEditor` or `EditorInterface` classes or something on that lines.

Also this had been requested in https://github.com/godotengine/godot/issues/21417 but as a comment, so I'm making a dedicated issue request for that.

**Comment by rainlizard** [comment]
Proposal: https://github.com/godotengine/godot-proposals/issues/2278

**Comment by Paulb23** [comment]
Duplicate of godotengine/godot-proposals/issues/2278 fixed by #48605
