### ISSUE TITLE
Scene Tree relationship lines not respecting color

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot#28174]
**Version:** Godot 3.1
**OS:** Windows 10

**Issue description:**
Relationship Line Color in the docks scene tree do not get applied

**Steps to reproduce:**
Go into Editor Settings
Under the Docks dropdown - go to Scene Tree
Check the "Draw Relationship Lines" box
Change the color with the "Relationship Line Color" color picker

![GodotLineSettings](https://user-images.githubusercontent.com/16636969/56390813-ea2c4980-61fa-11e9-92f6-49ce5f6fce48.JPG)

![GodotNoColorApplied](https://user-images.githubusercontent.com/16636969/56390817-ec8ea380-61fa-11e9-8604-89198fcaf4a4.JPG)

**Comment by YeldhamDev** [comment]
The relationship line colors are now defined by the theme itself. It still appears in your editor settings because the value is still in your config file, removing it will make it go away.

**Comment by Duroxxigar** [comment]
@YeldhamDev Can you elaborate on that? There are only two color pickers that I know of that allow you to change editor colors - neither appear to actually change the relationship colors. I have tried changing both of these values to be something different - and the colors on the relationship lines do not change. Or is it stuck to being dark lines?

![EditorTheme](https://user-images.githubusercontent.com/16636969/56400245-d1cf2580-6220-11e9-99f9-3bdab79ad592.JPG)

**Comment by YeldhamDev** [comment]
The lines use `mono_color`, defined here: https://github.com/godotengine/godot/blob/4ad255a078da0e9cc2620fe714bd722aae38206f/editor/editor_themes.cpp#L324
So yeah, light in dark themes, and vice versa.
