### ISSUE TITLE
custom class: custom icon turns to basic node icon

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#28172]
**Godot version:**
3.1 

**OS/device including version:**
win  10

**Issue description:**

I create `custom_class.gd`
I put some `custom_class `node in the tree
I want to do some changes and add `prints("ciao belli") `in one or two custom_class nodes: I have to click on "_make script unique_" in node properties/script section 
Sudenly the assigned icon changes to basic node icon (sigh, I'm not able to identify `custom_node `nodes easy like before) 
I run the project and I receive error `'custom_node' already exists at path...` . WTFunky? I need to rewrite each customized custom_node only because I added a puny `prints` statement? alias: in my project analysis it is still a custom class, Godot made it not anymore. What if I need to modify `custom_node `class later?

I apologyze if my text might look a bit too ironic and not quite polite, it was just what crossed my mind at the time it happened :) 
Don't worry, I praise you, you are doing a great work on Godot engine!

**Steps to reproduce:**
mrp

**Minimal reproduction project:**
[custom_node_class_error_mrp.zip](https://github.com/godotengine/godot/files/3095381/custom_node_class_error_mrp.zip)

**Comment by Jummit** [comment]
Here is what is happening:
You create one script and make it a custom class and then instance it somewhere and make the code resource unique. This leaves you with two scripts with the same class_name. If you want to change the behavior of a class just copying and modifying it isn't the way to go. Just make your new script inherit the custom class and make the needed changes. Here is an example:
```
extends Node
class_name MyClass
func do_stuff():
    var bar = "foo"
    print(bar)
```
```
# inherits MyClass, so it copies all functionality
extends MyClass

# overrides do_stuff
func do_stuff():
    # calls the original do_stuff method
    .do_stuff()
    # behavior unique to this class
    print("Hello world!")
```
You can create the second script just by clicking `Extend Script`:
![20190418](https://user-images.githubusercontent.com/28286961/56389616-4c507300-622a-11e9-8996-0ba14d0d929c.png)

**Comment by burstina** [comment]
> 
> 
> Here is what is happening:
> You created one script and made it a custom class and then instanced it somewhere and made the code resource unique. This left you with two scripts with the same class_name.
> If you want to change the behavior of a class just copying and modifying it isn't the way to go. Just make your new script inherit the custom class and make the needed changes. Here is an example:
> 
> ```python
> extends Node
> class_name MyClass
> 
> func do_stuff():
>     var bar = "foo"
>     print(bar)
> ```
> 
> ```python
> # inherits MyClass, so it copies all functionality
> extends MyClass
> 
> # overrides do_stuff
> func do_stuff():
>     # calls the original do_stuff method
>     .do_stuff()
>     # behavior unique to this class
>     print("Hello world!")
> ```
> 
> You can create the second script just by clicking `Extend Script`:
> ![20190418](https://user-images.githubusercontent.com/28286961/56389616-4c507300-622a-11e9-8996-0ba14d0d929c.png)

that's good, thank you!

but still class_icon in the tree turns to basic node icon, that's sad.
It should keep the same icon for node extends custom class.

**Comment by Calinou** [comment]
This is expected behavior consistent with core nodes
. Child classes do **not** inherit their parent's icon automatically.
