### ISSUE TITLE
Tween.TRANS_CIRC + Tween.EASE_IN_OUT Unexpected result in browser

### ISSUE THREAD

**Issue by Tkap1** [godotengine/godot#28177]
**Godot version:**
3.1

**OS/device:**
OS: Windows 7
GPU: NVIDIA GTX 650
Happens on both GLES3 and GLES2
Happens on both Chrome and Firefox.

**Issue description:**
`Tween.TRANS_CIRC` + `Tween.EASE_IN_OUT` has a different effect in HTML than it does in desktop.

Here is the problem in action: https://gfycat.com/IndelibleFlamboyantAuk
![IndelibleFlamboyantAuk-mobile](https://user-images.githubusercontent.com/8281454/101510770-abde3200-39bd-11eb-84db-cb3e417cf371.gif)

The first example is running godot normally from the editor, the second is with "Run in browser" (Also happens when it is hosted in a GitHub Page)

**Steps to reproduce:**
Animate a position (haven't tested other properties) with `Tween.TRANS_CIRC` and `Tween.EASE_IN_OUT` and run it on Firefox/Chrome. The code looks something like this:
`tween.interpolate_property(self, "position", start_position, position + Vector2(300, 0), 1.0, Tween.TRANS_CIRC, Tween.EASE_IN_OUT)`
	
`tween.start()`

**Minimal reproduction project:**
[TweenBug.zip](https://github.com/godotengine/godot/files/3096356/TweenBug.zip)

_bugsquad edit : insert gif converted from mp4 in comment_

**Comment by Faless** [comment]
I'm sorry this went unnoticed for so long, I can confirm the issue, even in `3.2`.

It seems very weird, like some numerical problem. I'll try to further investigate.

**Comment by akien-mga** [comment]
Related to #22513.
