### ISSUE TITLE
Thekla-Atlas, *possibly* GPL'd code in one of the class

### ISSUE THREAD

**Issue by patwretchedsuspect** [godotengine/godot#28182]
**Godot versions:**
_3.0.6, 3.1-stable, master branch_ and all the ones that include Thekla-Atlas (the folder is /thirdparty/thekla_atlas).

**Issue description:**
I've opened an issue about it [here](https://github.com/castano/nvidia-mesh-tools/issues/7) in the nvidia-mesh-tools project (Thekla-Atlas is based on it), but there was no response.

The gist of it is that in the files /thirdparty/thekla_atlas/nvmath/Random[.h/.cpp] exists class Rand48 (lines 287 and 9), that has a note
> Random number implementation from the GNU Sci. Lib. (GSL).

GSL is licensed under GPL, which is obviously more restrictive than Godot's license. **I don't know** if Rand48 is a code under GNU GPL or is merely similar to one, but the comments and the naming scheme seems to be similar (see the linked issue, the code I've compared it to is [this one](https://github.com/hlsyounes/ymer/blob/master/gsl/rng/rand48.c)).

However, the class Rand48 is not used by Godot (or the other classes of Thekla-Atlas), so it can be safely removed from the files listed above.

**Comment by akien-mga** [comment]
Note: it's closed as fixed in the master branch, but I still intend to fix it in the 3.1 branch (with a cherrypick) and in the 3.0 branch (by removing the offending code).

**Comment by akien-mga** [comment]
> Note: it's closed as fixed in the master branch, but I still intend to fix it in the 3.1 branch (with a cherrypick) and in the 3.0 branch (by removing the offending code).

Done with #28197 (3.0 branch) and def0820 (3.1 branch).
