### ISSUE TITLE
Cant export project-zip when no build-schema is in export-list

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#28188]
**Godot version:**
3.1 official

**OS/device including version:**
Windows 10 PC

**Issue description:**
When i want to export a Project as zip, but i have no builds in the left list, i can click the "Export PCK/Zip" Button and choose name, click save, but no file will be exported.

As soon as i add a schema (Windows for example) and i then try to export again, it works.

**Steps to reproduce:**
- create new project
- go to project -> export
- try to export project with no buid-schemas in the left list

**Minimal reproduction project:**

[Reproduction_Project.zip](https://github.com/godotengine/godot/files/3097267/Reproduction_Project.zip)

**Comment by LinuxUserGD** [comment]
I think this is somehow expected as the settings in the Windows/Linux/OSX/Android/IPhone build apply to the exported .zip/.pck.

**Comment by Reneator** [comment]
Really? I understood that as just to export the whole project as a zip-file. Or is it made, so you can open the project and build projects with it, without having to set anything up?

But isnt that per se independent of each other? as it would be logical, that the project would just keep the build-settings it has, as its part of the project as you export it?

**Comment by starry-abyss** [comment]
Sounds like a https://github.com/godotengine/godot/issues/24894 duplicate

**Comment by Reneator** [comment]
> Sounds like a #24894 duplicate

Thanks, exactly what i meant, solution is also satisfying!
