### ISSUE TITLE
MainLoop iteration function does not effect physics

### ISSUE THREAD

**Issue by TwistedTwigleg** [godotengine/godot#28183]
**Godot version:**
Godot 3.1 Stable

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
Calling `iteration` on MainLoop does not appear to effect physics nodes within the scene, despite `_physics_process` being effected.

I was trying to help **Schorsch** on the Godot Developer forums with an simulating a Godot game and the physics within as fast as possible (right now you can find the [forum post here](https://godotdevelopers.browse-tutorials.com/discussion/20623/simulate-game-and-physics-as-fast-as-possible)). Using `idle` in the MainLoop class works as expected, but `iteration` doesn't effect the physics nodes, like RigidBody2D, at all despite `_physics_process` being effected as expected.

As far as I can tell the `iteration` function is supposed to make the physics engine process, so I would assume this is a bug?

See GIF below (my apologizes for the poor quality):

![MainLoop_Iteration_Bug](https://user-images.githubusercontent.com/25082678/56400259-faefb600-6220-11e9-89d6-83e6e4e899a0.gif)

**Steps to reproduce:**
Call `iteration` on the MainLoop class. `_physics_process` will move forward as expected, but physics objects within the scene, like RigidBody2D nodes, will not be effected.

**Minimal reproduction project:**
Please ignore the comments, as I added them when I was trying to figure out how to use MainLoop and forgot to remove them: [MainLoop_Tests.zip](https://github.com/godotengine/godot/files/3096694/MainLoop_Tests.zip)

**Comment by pouleyKetchoupp** [comment]
Closing since this function has been removed in #43260.
