### ISSUE TITLE
Thekla - incomplete/missing license

### ISSUE THREAD

**Issue by patwretchedsuspect** [godotengine/godot#28180]
**Godot versions:**
_3.0.6_, _3.1-stable_, _master branch_ and all the ones that include Thekla-Atlas (the folder is /thirdparty/thekla_atlas).

**Issue description:**
A few months back Thekla-Atlas has added a missing attribution file for "NVIDIA mesh and texture tools" that it is based on - see its issue [24](https://github.com/Thekla/thekla_atlas/issues/24) and the file [ATTRIBUTION](https://github.com/Thekla/thekla_atlas/blob/master/ATTRIBUTION).

What's missing in the Godot's version of Thekla is a MIT license with the following copyrights:

> Copyright (c) 2009-2017 Ignacio Castaño
> Copyright (c) 2007-2009 NVIDIA Corporation

Note about Thekla's ATTRIBUTION file - Godot uses the mentioned here nvidia mesh/texture tools and poshlib, but doesn't seem to use tinyobj (used in examples) so there is no need to mention the latter.

**Comment by clayjohn** [comment]
This would make a good first PR for anyone interested!

**Comment by akien-mga** [comment]
We don't use Thekla anymore in 3.1+, so I'll just drop it.

This still needs to be solved for 3.0.x though.
