### ISSUE TITLE
Area2D displays a single point

### ISSUE THREAD

**Issue by skyttedk** [godotengine/godot#28194]
**Godot version:**

v3.1.stable.official

**OS/device including version:**

Windows10 on Lenovo ThinkPad P51
NVIDIA Quadro M620

**Issue description:**

Adding an Area2D node to a scene, there's no area displayed, 
[Area2D Issue.zip](https://github.com/godotengine/godot/files/3097741/Area2D.Issue.zip)

Just a single point. Se attached screenshot. 

**Steps to reproduce:**

1. Create a new scene.
2. Add a new node.
3. Add an Area2D.

An example scene has been attached.

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
Did you give your Area2D a shape?

**Comment by groud** [comment]
As @Zireael07 suggested, you need to assign the Area2D a shape.
Closing as it's expected behavior.
