### ISSUE TITLE
Compiling module containing function with 6 arguments fails?

### ISSUE THREAD

**Issue by Gramps** [godotengine/godot#28202]
**Godot version:**
Tested in 3.1 but also present in previous version.

**OS/device including version:**
Windows 10 and Linux Ubuntu 18.04 LTS.

**Issue description:**
Attempting to compile a module that contains a function with six arguments errors and fails.   Specifically when binding the method:

`core\method_bind.gen.inc(162): note: see declaration of 'create_method_bind'`

It does not seem to error when using only five arguments.  Removing any of the six, down to five, compiles correctly; albeit short of ideal functionality.

**Steps to reproduce:**
I guess try compiling a C++ module as described above.

**Comment by akien-mga** [comment]
You have to include `core/method_bind_ext.gen.inc` if you need templates for more than 5 parameters.
