### ISSUE TITLE
tile texture displace compared to its collision(in TileMap /w origin=CENTER)

### ISSUE THREAD

**Issue by Lodugh** [godotengine/godot#28206]
**Godot version:** 3.1 x64 AppImage
**OS/device including version:** Linux Mint 19.1(Ubuntu Bionic)

**Issue description:**
Flipped tiles texture is displaced (compared to its collision). 

**Steps to reproduce:**
Creat a TileSet with a tile that has a texture and a collision, put it into a scene with a TileMap which cell_tile_origin is set to CENTER and place a flipped tile.

**Minimal reproduction project:**
[flipped_tile_texture_displacement.zip](https://github.com/godotengine/godot/files/3099046/flipped_tile_texture_displacement.zip)

Possibly related to: #22989

**Comment by Ranoller** [comment]
https://github.com/godotengine/godot/issues/22989
I refer that for info when do the commit.
