### ISSUE TITLE
OptionButton "Items" button dissapear when other editor is active (e.g. Theme or AtlasTexture)

### ISSUE THREAD

**Issue by TintaKnight** [godotengine/godot#28211]
**Godot version:**
Stable 3.1

**OS/device including version:**
Windows 10, GTX 1060 6gb

**Issue description:**
OptionButton "Items" button dissapear from scene top bar.

**Steps to reproduce:**
Create a new OptionButton node;
Go to Control/Theme on Inspector;
Create a new theme and click to edit it.

**Comment by clayjohn** [comment]
Could you provide more information please? Maybe screenshots even. I am having trouble understanding what exactly the problem is.

**Comment by TintaKnight** [comment]
> Could you provide more information please? Maybe screenshots even. I am having trouble understanding what exactly the problem is.

When you apply a theme to an OptionButton, this button disappears:
![image](https://user-images.githubusercontent.com/49794046/56447768-4749fd00-62d8-11e9-8688-c24640b4f90e.png)

Without theme:
![image](https://user-images.githubusercontent.com/49794046/56447726-14076e00-62d8-11e9-9a6f-a7a27bac5617.png)

With theme:
![image](https://user-images.githubusercontent.com/49794046/56447742-2a152e80-62d8-11e9-9b9e-fa884a592be7.png)

**Comment by akien-mga** [comment]
CC @YeldhamDev

**Comment by YeldhamDev** [comment]
Digging more into this, I don't think this is a "bug", but more of "that's how Godot works™". The editor is overriding the item editor, but if you close the `Theme` resource, the item editor comes right back, as it's the main focus now. You can see the same behaviour with things like opening a shader resource in a `Sprite`.

**Comment by volzhs** [comment]
I guess it is more like #7001

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3

**Comment by nobuyukinyuu** [comment]
recommend updating the title to reflect the wider scope of this bug

**Comment by polytect** [comment]
Still same with 3.3.
Items disappears.
And then Either you have to recreate the node or, not to use at in this way.

**Comment by KoBeWi** [comment]
While the original cause was not fixed, this particular issue was resolved when items editing was moved to inspector.
