### ISSUE TITLE
Export template for Android is broken

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#28215]
**Godot version:**
master, 3.1 stable

**OS/device including version:**
Antergos (Arch Linux)

**Issue description:**
When I compile godot from source for x11 and install the export templates from https://hugo.pro/projects/godot-builds/ I can't install the exported android package. However using the 3.1 stable download and the official export templates, it installs correctly.

**Steps to reproduce:**
Download https://godotengine.org/download/linux and install export templates. The exported .apk will install and run correctly.
Compile from master and install export templates from https://hugo.pro/projects/godot-builds/. The exported .apk will fail to install.

**Comment by clayjohn** [comment]
Thanks for the report! But from the sounds of it, you are saying that everything in Godot works fine, but @Calinou's automatic builds are broken? This is not the proper place to report issues with third party builds. 

@Calinou Care to take a look at this?

**Comment by akien-mga** [comment]
A priori you can't mix and match a self-compiled editor binary with thirdparty export templates, unless you're 100% positive that they're built from the same commit.

If you use the templates from @Calinou, please also use the editor build that goes with it.

**Comment by LinuxUserGD** [comment]
Exporting with a self compiled editor (macOS 10.14.4) and self compiled export templates results in a parser error when trying to install the .apk.
When I use the editor from the unofficial builds and install the export templates with the same commit, it works. So nothing is broken with the export templates, I was just using different commits.
