### ISSUE TITLE
APK Expansion fail to install

### ISSUE THREAD

**Issue by canvasbushi** [godotengine/godot#28214]
**Godot version:**
3.1

**OS/device including version:**
Android 5.0/Samsung Galaxy S5

**Issue description:**
APK Expansion enabled, devices report cannot locate resource.

**Steps to reproduce:**
Godot 3.1 Project on Galaxy S5.

**Minimal reproduction project:**

**Comment by LinuxUserGD** [comment]
Are you using the official export templates?

**Comment by canvasbushi** [comment]
> Are you using the official export templates?

Custom android export with admob. the apk works fine if no apk expansion(and yes i'm testing live from the playstore). the problem only happens on Galaxy S5

**Comment by volzhs** [comment]
did you enable READ_EXTERNAL_STORAGE permission?

**Comment by canvasbushi** [comment]
> did you enable READ_EXTERNAL_STORAGE permission?

I didnt add that permission, I'll try it and see if this resolves my issue.

**Comment by volzhs** [comment]
@canvasbushi any update?

**Comment by canvasbushi** [comment]
> @canvasbushi any update?

i reduced the size of the engine to get an apk under 100mb, so i haven't tried it yet.

**Comment by m4gr3d** [comment]
Closing since the issue seems to be resolved. @canvasbushi Feel free to reopen if it's not.
