### ISSUE TITLE
Can I use Godot to connect a UDP Remote Node.js Server?

### ISSUE THREAD

**Issue by Sphynxinator** [godotengine/godot#28216]
**Godot version:**
3.1

**OS/device including version:**
Windows 8.1

**Issue description:**
I expected UDP to work but it doesn't work. I am so sorry if I opened this issue to wrong place but I need to know if Godot Engine runs as client with Node.js UDP server. My server's public IP is for example 50.50.120.20, and port that server listen is 6667, I am binding it with socket.bind(6667) in node.js, and in Godot, I am calling set_dest_address("50.50.120.20", 6667), but my server doesn't connect, doesn't give any error, doesn't say anything at all. I am not sure if this is issue or something but some people said Godot UDP doesn't work with Node.js UDP but in localhost, it works. I am so sorry if I am wrong.

**Comment by clayjohn** [comment]
No need to apologize!

But could you please provide a more descriptive title so that users who know about networking can assist you. 

Thanks!

**Comment by Sphynxinator** [comment]
> No need to apologize!
> 
> But could you please provide a more descriptive title so that users who know about networking can assist you.
> 
> Thanks!

I am so sorry, I noticed I omitted the title now. Yesterday, I saw my own online game in action, so I was so excited. But it was connecting with TCP so I tried the alter it as it uses UDP.

**Comment by akien-mga** [comment]
CC @godotengine/network

**Comment by Faless** [comment]
@Sphynxinator yes, UDP **does work** with servers written in other language.
UDP is a *connectionless* protocol, so you will never get a "connection", when you `set_dest_address` you are just setting the destination of the following sent packets.
Use `put_packet` to send data to that destination after it.

**Comment by Sphynxinator** [comment]
> @Sphynxinator yes, UDP **does work** with servers written in other languages.
> UDP is a _connectionless_ protocol, so you will never get a "connection", when you `set_dest_address` you are just setting the destination of the following sent packets.
> Use `put_packet` to send data to that destination after it.

Hi. I am already sending with put_packet with Godot, but the message event of Node.js server doesn't get emitted.

**Comment by Faless** [comment]
@Sphynxinator is the server behind a firewall? Did you open the necessary ports (UDP!)?
Can you make a minimal reproduction project (and server) so I can verify it?

**Comment by Sphynxinator** [comment]
How can I know if my server is behind a firewall? Which ports do you mean? I am not sure that I can make a minimal project because you couldn't access my server. I can make it connect to localhost, and if it connects to the localhost, it doesn't give error but the situation is not that. I want to run it on my server. Can you please give me an idea how can I share minimal project without localhost? Sorry if I am a nuisance. :(

**Comment by Faless** [comment]
@Sphynxinator just attach the server and client code, I'll try it on my own server.

> How can I know if my server is behind a firewall?

Well, they usually are, it depends on your server, on linux `iptables -L` would show iptables rules for the machine, but the server might have extra protection from your service providers. You should check with them.

> Which ports do you mean?

6667 UDP

**Comment by Sphynxinator** [comment]
[UDP.zip](https://github.com/godotengine/godot/files/3100289/UDP.zip)

Sorry for the late answer. I made two projects, client with Godot, server with Node.js. 

By the way, my server is Linux, Amazon Linux 2 to be exact. I think, it's CentOS 7 or something. But I am testing on Windows 8.1.

**Comment by Sphynxinator** [comment]
Update. I am so noob. I fixed that issue now. I closed that UDP:4666 connection on Security Group. You can close the issue, it's not Godot related. Godot works the best.

**Comment by Tilican** [comment]
Hi,
[@gd-com/utils](https://www.npmjs.com/package/@gd-com/utils) is an npm pacakge who manage binary serialization / deserialization, for example to send var from godot to nodejs :)

Enjoy
