### ISSUE TITLE
Inconsistent drag and drop in VisualScript

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28226]
**Issue description:**
Dragging a member from a node into visualscript creates a new setter, holding ctrl makes it getter.

This is different from the member variables, where you hold ctrl to get a setter.

It should also be considered changing it to shift, since shift is for inverting things. Ctrl makes more sense for getting the setter node that uses an instance, since it is more technical.

**Comment by DavidCambre** [comment]
To me it feels good the way it is. By default you try to set something on a node end get some value from the script.

**Comment by Jummit** [comment]
This should be a proposal, closing.
