### ISSUE TITLE
macOS: InputEventKey's unicode property is always 0

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#28224]
**Godot version:**
3.1

**OS/device including version:**
macOS Mojave (10.14.4)

**Issue description:**
On macOS, InputEventKey's unicode is always 0 unless a built-in control that supports text input (such as LineEdit) has the focus. This is an issue when building your own keyboard input controls. On Windows, the unicode property works as expected (i.e. it's non-zero for any key combination that has a unicode representation).

**Steps to reproduce:**
1. Create a scene with a Control in it
2. Add any input handler (_input, _unhandled_input, gui_input)
3. Check the value of the unicode property when a key such as 'A' is pressed

**Minimal reproduction project:**
[KeyboardInputTest.zip](https://github.com/godotengine/godot/files/3099773/KeyboardInputTest.zip)

**Comment by ArdaE** [comment]
Try the sample project on both Windows and macOS to see the difference.

**Comment by bruvzg** [comment]
I can confirm this, `unicode` property is set only when IME input mode is activated via `OS.set_ime_active(true)`.

**Comment by ArdaE** [comment]
> ... when IME input mode is activated via `OS.set_ime_active(true)`.

Thanks for that info @bruvzg. I'll use that for now as a workaround.
