### ISSUE TITLE
Godot project fails to run with a crash on Mono 5.20

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#28225]
**Godot version:**
`master` / 7be49849

**OS/device including version:**
Manjaro Linux 18.0.4

**Issue description:**
After I upgraded Mono from 5.18 to 5.20, I'm no longer able to build the project as it failed to recognize dependent assemblies declared in `packages.config`.

As I cannot use the new `PackageReference` format due to #15386, I applied the workaround mentioned in that issue (specifying `Version` as a child element rather than an attribute), and the project was successfully built. But it immediately crashes when I run it with the following log:

[crash_log.txt](https://github.com/godotengine/godot/files/3099835/crash_log.txt)
[mono_crash.33e9d9466.0.json.txt (rename it to .json)](https://github.com/godotengine/godot/files/3099836/mono_crash.33e9d9466.0.json.txt)

**Comment by neikeq** [comment]
Looks the same as #28667. It may already be fixed on latest master. I'm awaiting confirmation.

**Comment by mysticfall** [comment]
Just tested again after upgrading Mono to 5.20 but this time the game just freezed with the following trace:
[freeze.txt](https://github.com/godotengine/godot/files/3209691/freeze.txt)

**Comment by mysticfall** [comment]
Just tested again with fa5cc1da7a on Mono 5.20 and I'm no longer able to reproduce the crash. Thanks! :)
