### ISSUE TITLE
Render slow when compared to version 3.0.6

### ISSUE THREAD

**Issue by deadcodeonly** [godotengine/godot#28221]
Test performed on a windows 10, I7, 8GB Radeon R7 M265, monitor 60HZ.

The problem was encountered during the migration of a complex 2D game in which I am working and I thought I should migrate it from version 3.0.6 to new 3.1 (the performance problem prevented me).

To reproduce the problem, a project with a button and a label is enough. So just check print FPS in project configuration. The difference between version 3.1 and 3.0.6 is clear.

But when the game is exported to HTML5 the performance is noticeably better.

There is! disabling vsync greatly improves performance in both versions.

Thanks!

**Comment by clayjohn** [comment]
V-sync syncs your framerate to your screen update time. Is it going down to 60fps by any chance?

**Comment by fire** [comment]
Please check if your error log is spamming. It may a cause.

**Comment by deadcodeonly** [comment]
60 FPS would be very good, version 3.0.6 delivers that.

Log for a scene with a label and a button in version 3.1 (changing to OpenGL ES 2.0 does not change anything):

allow_focus_steal_pid 13608 --position 448,240
OpenGL ES 3.0 Renderer: AMD Radeon R7 M265
Game FPS: 2
Game FPS: 34
Game FPS: 39
Game FPS: 40
Game FPS: 40
Game FPS: 40
Game FPS: 40

I will try to test in other environments. I hope to find some information that sheds light on this problem.

Thank you all for your attention.

**Comment by deadcodeonly** [comment]
Windows 10 apparently failed to update the Radeon r7 M265 driver. I updated the driver with the AMD software and the performance problem was corrected.
