### ISSUE TITLE
Detect if scene was launched as main

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#28230]
**Godot version:**
v3.1-stable

**Issue description:**
Sometimes it's very convenient to have different behavior for scene based on whether the scene was launched as main scene (via F6) or instantiated during runtime. An example for this is a fireball effect that has "fire" method. This method must be called during runtime by some other (Player) node, which means there is no effective way to test if this scene actually works by running it on its own. Something like this would be highly appreciated:

```gdscript
extends Spatial

func _ready() -> void:
    if is_main_scene():  # Or maybe `was_instanced`?
        # Run "demo" code for testing effect via "Run scene"
        self.fire_lazers_particles_unicorns_and_shit()
    else:
        # We have been instantiated from other scene. Don't do anything!
        self.hide()
```

One of the workarounds is to check if `get_parent() is Viewport`, but this looks somewhat error-prone. Especially when you're dealing with a lot of nested `Viewport`s.

**Steps to reproduce:**

```gdscript
func _ready() -> void:
    # Are we alone? Or are we instantiated in a different scene?
```

**Comment by akien-mga** [comment]
You can do this with:
```gdscript
if get_parent() == get_tree().root:
	print("I'm the main scene.")
else:
	print("I'm an instance in another scene.")
```
But yeah, something like `is_main_scene()` might be more readable.

**Comment by and3rson** [comment]
@akien-mga That's a good point, but it will not work properly if the scene is added to the root viewport in runtime. My belief is that is_main_scene should check if the current scene was actually passed as an argument to Godot binary *or* was specified as main scene in project settings.

**Comment by akien-mga** [comment]
If you only want to know that the scene is the one defined in ProjectSettings as the main scene, you can compare the ProjectSettings property to the scene's `filename` property.

I don't see much use case for this though. IMO the one I exemplified above is more interesting, as it lets you have different logic whether you scene is the root scene or not (e.g. when you play a scene with "Run Current Scene", where it is the "main" scene).

**Comment by and3rson** [comment]
Totally makes sense. Thanks for your input!

**Comment by Sslaxx** [comment]
Having a `is_main_scene (scene)` that'd be a shortcut for comparing the specified scene to `ProjectSettings.get_setting ("application/run/main_scene")` wouldn't go amiss.

**Comment by API-Beast** [comment]
For those landing here because they googled how to detect if the scene is the main scene:
```swift
if get_parent() == get_tree().root and ProjectSettings.get_setting("application/run/main_scene") == self.filename:
    start_demo()
```

`get_parent() == get_tree().root` so that additional copies of the scenes don't run in demo mode as well.
`ProjectSettings.get_setting("application/run/main_scene") == self.filename` so that demo mode isn't launched just from switching scenes.

**Comment by matmas** [comment]
For Godot 4.x it is:

```gdscript
if get_parent() == get_tree().root and ProjectSettings.get_setting("application/run/main_scene") == self.scene_file_path:
    start_demo()
```

**Comment by AniceM** [comment]
> For Godot 4.x it is:
> 
> if get_parent() == get_tree().root and ProjectSettings.get_setting("application/run/main_scene") == self.scene_file_path:
>     start_demo()

From Godot 4.4 this does not work anymore, since `ProjectSettings.get_setting("application/run/main_scene")` will be set to the scene's uid and not `self.scene_file_path`.

You can however make it work by manually replacing the UID by the scene_file_path in project.godot.

**Comment by jedomed** [comment]
> You can however make it work by manually replacing the UID by the scene_file_path in project.godot.

This isn't necessary, you can use [ResourceUID](https://docs.godotengine.org/en/stable/classes/class_resourceuid.html)'s id_to_text() and then get_id_path() to convert it back to a path.

**Comment by fcolecumberri** [comment]
> > For Godot 4.x it is:
> > if get_parent() == get_tree().root and ProjectSettings.get_setting("application/run/main_scene") == self.scene_file_path:
> > start_demo()
> 
> From Godot 4.4 this does not work anymore, since `ProjectSettings.get_setting("application/run/main_scene")` will be set to the scene's uid and not `self.scene_file_path`.
> 
> You can however make it work by manually replacing the UID by the scene_file_path in project.godot.

Since Godot 4.4 and 4.5 this is no longer working, maybe this issue should be re-open.

**Comment by lietu** [comment]
I have initialization logic in a global autoload script that needed to know if the game was started with "Run current scene" or normally, based on the conversation here I used this on Godot 4.5:

```gdscript
var STARTED_FROM_MAIN = false

func _ready():
  	var tree = get_tree()
	var main_scene_id = ProjectSettings.get_setting("application/run/main_scene")
	var main_scene_path = ResourceUID.uid_to_path(main_scene_id)
	var scene_path = tree.current_scene.scene_file_path
	
	if main_scene_path == scene_path:
		STARTED_FROM_MAIN = true
```

Works perfectly.
