### ISSUE TITLE
Unable to ignore GDScript warnings for addons

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#28232]
**Godot version:**
3.1+

**Issue description:**
Having the warning system to report about potential problems in code is really good and things can be fixed that way, but Godot doesn't seem to have an ability to ignore particular folders that aren't necessarily maintained by game developers themselves (addons is one example), polluting the debugger with warnings that (can't) be fixed, or rather should be fixed by third parties instead.

Some of them could even be dynamically generated GDScript's: https://github.com/bitwes/Gut/issues/129#issuecomment-534333080.

With many types of warnings being implemented recently (#28053), this really starts to render the warnings system useless for me, as I have to disable certain warnings because of that, or even disable it at all.

---

Continuation of #22108 but deserves a separate issue as suggested by Akien:

```
<Xrayez> suggestion: shouldn't warning system ignore `addons` folder? It's like a thirdparty in Godot C++ :)
<Akien> Xrayez: yes. It's mentioned in https://github.com/godotengine/godot/issues/22108 but it would be better in its own issue.
```

**Comment by Xrayez** [comment]
Not sure if I should close this since #33437 is merged, probably yes because really the original issue was about having ability to ignore `addons` folder (ignoring *any* folder could be a better implementation for this, for instance `res://addons/` could be added to exclude list by default). There could be certain plugins for which you do want to have warnings (say project-specific editor plugins).

**Comment by akien-mga** [comment]
> There could be certain plugins for which you do want to have warnings (say project-specific editor plugins).

Do you have a clear use case for that? Otherwise I'd prefer to close a 99% fixed issue than keep it open just in case.

**Comment by Xrayez** [comment]
I have some plugins which give a more appealing visual interface for editing custom resources which are project-specific, like programming game rules with nodes, just like you can edit `AnimationTree` and family of related nodes for instance.

Well I think I'll just reopen the issue or create a new one once I get to this.
