### ISSUE TITLE
Add get_inner_class_list() method to Script class.

### ISSUE THREAD

**Issue by CodeDarigan** [godotengine/godot#28233]
3.1

I have spent a few days working on a script to parse other scripts recursively in order to collect all inner classes (for my testing plugin "WAT") but this has become unnecessarily complex and is likely to cause a significant performance hit.

My suggestion is to add a .get_inner_class_list() method on the Script class similar to the .get_property_list() and .get_method_list() on the Object class. 

Currently doing this involves quite a bit of instancing and then using inst2dict to collect the sub-paths repeatedly.

Edit: I think this will help other tool makers beyond myself as well.

**Comment by Xrayez** [comment]
Yeah, I think this should also help @bitwes to improve his GUT that way.

**Comment by bitwes** [comment]
This would be very helpful with GUT.  Right now I do a simple parse to find first level inner classes.  With this GUT could easily have more levels of inner classes.  It also helps with exporting tests.  To run tests against compiled code I have to save all of the inner class info and load it.  This might allow me to treat compiled/encrypted/plain text code the same.

**Comment by CodeDarigan** [comment]
This has been more o less resolved by the new Script.get_script_constant_map() method in 3.2 so I'm going to close this.
