### ISSUE TITLE
ConfirmationDialog moves back to original position when dragged by title bar

### ISSUE THREAD

**Issue by CngKO** [godotengine/godot#28231]
**Godot version:**
3.1 official

**OS/device including version:**
Windows 10.0.17134 Build 17134

**Issue description:**
ConfirmationDialog moves back to original position when dragged by title bar.  It doesn't seem to be able to handle position change outside area covered by original camera.

**Steps to reproduce:**
In the project attached below...
  - Click on the "open dialog" button
  - Try to drag the ConfirmationDialog by its title bar
  - Notice that it disappears (because it is moved off screen to its original position)

**Minimal reproduction project:**
[dialog-disappears-on-drag.zip](https://github.com/godotengine/godot/files/3099995/dialog-disappears-on-drag.zip)

**Comment by KoBeWi** [comment]
Dialogs are completely changed in 4.0, so this seems to be fixed.

**Comment by CngKO** [comment]
Why are we not keeping this one open for the 3.2 branch?

**Comment by KoBeWi** [comment]
Is this really important though? It only happens when you move the dialog outside screen. In most cases you just use CanvasLayer to avoid camera problems.
