### ISSUE TITLE
LineEdit with editable set to false will always display all actions in the context menu

### ISSUE THREAD

**Issue by silkentrance** [godotengine/godot#28243]
**Godot version:**
3.1.stable.official

**OS/device including version:**
Mac OS High Sierra (latest)

**Issue description:**
Add a LineEdit control to a scene and set editable to false. Next, enter a default text for the control or just leave it empty.

**Steps to reproduce:**
Run the project. Now right click into the line edit.

As you can see, the options that allow the user to manipulate the content, including undo and redo, are still available.

![image](https://user-images.githubusercontent.com/6068824/56460742-f0abf400-63a7-11e9-8192-2d3902bdde2f.png)

**Comment by silkentrance** [comment]
Similar so for LineEdit with secret set to true. While it does not allow one to copy the data, which is could, it should also not provide that action at all.

**Comment by silkentrance** [comment]
I have look a little bit into this, also in order to learn about how the GUI stuff works internally.

I see that the PopupMenu is added as a child in the constructor and is also populated with all of the available items.

Would it be safe, in C++ that is, to remove all items and repopulate the child menu items on say, set_editable(), or initially on tree enter?

I see that you do a lot of the stuff in the background via the message queue and thus postpone the update or rather route it through the Control super class.

Would that then be the proper way to handle dynamic updates to the popup menu's list of items?

**Comment by YeldhamDev** [comment]
> Would it be safe, in C++ that is, to remove all items and repopulate the child menu items on say, set_editable(), or initially on tree enter?

This is how it's done on other menus in the codebase, so it's recommend to stick to that. Let me handle this.

**Comment by silkentrance** [comment]
@YeldhamDev yeah, I figure that this will require a bit of refactoring. Thanks for looking into this.
