### ISSUE TITLE
LineEdit align: Fill is without function

### ISSUE THREAD

**Issue by silkentrance** [godotengine/godot#28244]
**Godot version:**
3.1.stable.official

**OS/device including version:**
Mac OS High Sierra (latest)

**Issue description:**
Add a LineEdit control to a scene and set align to Fill. Next, enter a default text for the control or just leave it empty.

**Steps to reproduce:**
Run the project. Now enter some text with spaces and watch the line edit.

As you can see, the fill alignment will be without any function.

What I would expect it to do is to justify the text content so that it fills up all of the available space, or, if that is not a wanted behaviour, to just remove the option from the align option menu.

**Comment by Calinou** [comment]
The LineEdit **Fill** mode is now working as expected in Godot 4.0, closing.
