### ISSUE TITLE
Depth of field blur combined with transparent materials

### ISSUE THREAD

**Issue by dgoemans** [godotengine/godot#28240]
**Godot version:**
3.1

**OS/device including version:**
Windows 10, Intel CPU, RTX 2070 GPU

**Issue description:**
Transparent materials are being blurred as if affected by the DOF effect. They are within the range where they should take no blur from the DOF effect.

**Steps to reproduce:**
Create a material with transparency
Enable depth of field far blur
Note blurred material when not in blur range

![transparencyrefractiondof](https://user-images.githubusercontent.com/4238423/56469675-0e776880-643d-11e9-9ee8-2e3a232f20ac.gif)

**Minimal reproduction project:**
- Object with transparent material
- Environment with DOF enabled
[DofFail.zip](https://github.com/godotengine/godot/files/3100433/DofFail.zip)

**Comment by raphael10241024** [comment]
A hacky way to resolve this is setting SpatialMaterial->Paramters->DrawDepth->OpaquePrePass, I'm trying to solve this problem.
