### ISSUE TITLE
Particles in tps-demo are broken

### ISSUE THREAD

**Issue by hpvb** [godotengine/godot#28252]
**Godot version:**
master (anything after 24b7f088927e17d80e1e21573b16bee8d3d5d50b)

**OS/device including version:**
Linux Fedora 29 / RX580

**Issue description:**
Particles in tps-demo are stuck somewhere along the animation. After the first time they fire they work correctly

**Steps to reproduce:**

Run tps-demo and look at the enemies

**Minimal reproduction project:**
tps-demo

Bisected to: 24b7f088927e17d80e1e21573b16bee8d3d5d50b

**Comment by hpvb** [comment]
Ping @kiidmale

**Comment by kiidmale** [comment]
Does tps-demo use "CPU" particles?
I'll take a look when I get back to work machine tomorrow.
