### ISSUE TITLE
GetNode() cannot go "up"

### ISSUE THREAD

**Issue by MegaMech** [godotengine/godot#28255]
**Godot version:**

3.1 C# Project

**OS/device including version:**

W8.1 | 6.3.9600

**Issue description:**

In this structure: root/Spatial/AMeshInstance (attached ascript.cs to AMeshInstance)
Typing (Node)GetNode("..") or (Node)GetNode("root/Spatial")
does not return the Spatial node. Specifically when attaching a child node:
a = (Node)GetNode("..");
a.AddChild(anewMeshInstance);

This code runs, but the new instance does not show up under the remote scene viewer.
Changing the cast from (Node) to (Spatial) crashes the game with Socket error: 10054.

If I attach the script to Spatial instead of the MeshInstance I can successfully use "this".
But then what's the point of GetNode if it doesn't work? I can get the existing nodes that are beside or within the same directory as "AMeshInstance" but I cannot get the parent even if I use:
GetParentSpatial().

**Comment by LikeLakers2** [comment]
Have you tried [`GetParent()`](http://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-get-parent)?

**Comment by MegaMech** [comment]
> 
> 
> Have you tried using [`GetParent()`](http://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-get-parent) in place of `GetNode("..")` or `GetParentSpatial()`?

this.GetParent().AddChild(stars); //Also tried without "this."
this.GetParentSpatial().AddChild(stars);
Both do nothing and crashes the game 
 drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054

**Comment by MegaMech** [comment]
I have attached the project below if that helps with debugging this issue.
https://drive.google.com/file/d/1vKBH7GKPBi2VhSrJJ7S9LiJMPPnpNvFk/view?usp=sharing

**Comment by MegaMech** [comment]
From Reddit:
"I just tried adding a child to the parent and it gives me this message:

    Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead.

So the problem (if you're calling this function in the Ready method) is that children process the Ready function before the parent, but the parent is busy at that moment so it can't deal with it. Then the parent becomes Ready when all its children are, that's why calling the function from the parent works."

**Comment by MegaMech** [comment]
Is it possible the error I quoted above "Parent node is busy setting up children, add_node() failed..."
should be outputting in C# as well and not just in GDScript? I'm in a C# project I do not get that error.
Perhaps the "GetNode" page needs more information about its limitations and situational variants?
