### ISSUE TITLE
Transparent light occluders in 3D

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#28256]
**Godot version:**
v3.1-stable

**OS/device including version:**
ArchLinux & NVidia 740MX

**Issue description:**
This is an attempt to resurrect #3013 to bring support of transparent light occluders in 3D.

This would be super helpful for things like dynamic "fog of war" or shadowing invisible/inaccessible areas from player's sight. We are currently planning how to implement them in our top-down ARPG and lack of invisible occluders is a huge blocker.

Is there at least any workaround for this?..

**Comment by clayjohn** [comment]
I'm not sure exactly what you mean by light occluder. Do you mean something that casts a shadow? On any GeometryInstance derived node you can set "Cast Shadows" to Shadow only. This way it will not draw the object, but it will still cast a shadow.

**Comment by and3rson** [comment]
Thank you! This is just what I needed. Not sure how could I miss it.
