### ISSUE TITLE
Externalized mesh resource keeps getting embedded in an inherited scene

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#28254]
**Godot version:**
`master` / 7be49849

**OS/device including version:**
Manjaro Linux 18.0.4

**Issue description:**
I have a model exported with Godot Blender Exporter(.escn) with the import setting `Mesh > Storage` set to `Files` to save mesh data to `*.mesh` resources.

It works as intended at first, but when I restart Godot and open an inherited scene created from the source `.escn`, the contained `MeshInstance`'s `Mesh` property loses its reference to the externalized `.mesh` resource, but reverts back to the state in the source `.escn`, which embeds the whole mesh data in the scene itself.

The `.escn` in question is over 150mb in my case, and when this happens, the inherited scene (`.tscn`) becomes as large as its source, so I have to keep resetting those properties whenever I open the problematic scene.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
