### ISSUE TITLE
Config system proposal

### ISSUE THREAD

**Issue by ismslv** [godotengine/godot#28269]
![Screenshot](https://github.com/ismslv/Unity_CFG/raw/master/Screenshot.jpg)

I wrote a [config files system](https://github.com/ismslv/Unity_CFG) for Unity which I actively update. We use it with every our project for debugging and testing along with other systems, such as a [console](https://github.com/ismslv/Unity_Console), and it is really useful.

General use case is the following: developer puts as much variables as possible into the config file - such as a speed of something, a chance of generating something, sizes, colors, quantities, start values like money or health, graphic tweaks and so on. Then others can test the build changing these values. One base config file is packed into game resources, and others are exposed into the external folder (near the executable). One can create as many configs as needed (with different sets of settings) and engine finds and imports them all, rewriting base values. Then you can get these properties as simple as ```float h = CFG.F("Health_start");```.

I have already rewritten this for Godot mono, and can also adapt for gdscript. Also I've made a [VSCode extension](https://marketplace.visualstudio.com/items?itemName=FMLHT.fmcfg) to use with this system.

When I discovered Godot, I found that many of my other plugins, functions of which are not present or are not very good natively in Unity (for example, [Languages](https://github.com/ismslv/Unity_Languages), [Controls](https://github.com/ismslv/Unity_Control), and of course [Tween](https://github.com/ismslv/Unity_Tween) are already inside Godot and perfectly executed! But, I haven't seen a config system, which I find really useful.

Maybe, it is not a feature proposal, and I just have to publish something like a plugin into asset database. If so, tell me please what to do, I'm new to this coimmunity. Also, tell me please what do you think of [console system](https://github.com/ismslv/Unity_Console) and about the fact that my languages plugin can automatically download translations from Google Sheets. Should I contribute it to the Godot community or it is boring and unneeded?

Thank you for the reading.

**Comment by Zylann** [comment]
Isn't it what `ProjectSettings` is, along with `project.godot`? In addition to the existing variables in it, you can add your own and get it anytime with `ProjectSettings.get_setting(key)`.
Otherwise, I don't see why this would have to be also in the core, sounds like a system that would be perfectly fine as a plugin.

**Comment by ismslv** [comment]
> Isn't it what `ProjectSettings` is, along with `project.godot`? In addition to the existing variables in it, you can add your own and get it anytime with `ProjectSettings.get_setting(key)`.

Not quite, as I can create as many files as I want, to test different sets of configs - one is packed liek project settings, other is just for testing of gameplay, one will be exposed for players like a regular *.ini file with settings that they can change if they want... Also, there is a various functionality inside, like automatic parsing of enums.

> Otherwise, I don't see why this would have to be also in the core, sounds like a system that would be perfectly fine as a plugin.

I don't say it should be in a core, please point me in a right direction. It should be some editor plugin or what? In unity it is "asset" which I can import and place a manager object on scene.

**Comment by Zylann** [comment]
You can surely script this, and create a singleton, for example: https://docs.godotengine.org/en/3.0/getting_started/step_by_step/singletons_autoload.html

If editor integration is needed (i.e need special editor GUI, custom importer etc), you can create an `EditorPlugin`: https://docs.godotengine.org/en/3.0/tutorials/plugins/editor/index.html

Have a look here for plugins, libraries and assets other people have made: https://godotengine.org/asset-library/asset

**Comment by Calinou** [comment]
The [ConfigFile](https://docs.godotengine.org/en/latest/classes/class_configfile.html) class can likely be used to achieve what you want. It's also possible to centralize default values using a singleton or project settings, see [godot-settings-manager](http://github.com/Calinou/godot-settings-manager) for an example.
