### ISSUE TITLE
Animation State Machine Transition to not-requested State

### ISSUE THREAD

**Issue by Cygon** [godotengine/godot#28260]
**Godot version:** 3.1 (custom build from Git 6697fd9a05859914fc320b4b4321fd9fb6170f71 / Apr 17)

**OS/device including version:** Gentoo Linux 4.19.27, KDE Plasma 5.14, GTX 1080 w/proprietary drivers 418.32

**Issue description:**
When an animation state machine is given the command to go to a specific state and a valid chain of transitions leading there exists, everything works fine:

![with-transition](https://user-images.githubusercontent.com/3613175/56466762-2982b200-6416-11e9-8849-4054ea7fb265.gif)

Now, if there is no transition to the requested state, I would expect either an error or the state just becoming active immediately (and if I click on the *Neutral* state, that's what happens).

However, in the following case it seems to switch to an unrelated state to which there is no transition (in that direction) and stop there, never activating the requested state:

![without-transition](https://user-images.githubusercontent.com/3613175/56466805-e4ab4b00-6416-11e9-8cd4-97201988a939.gif)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
