### ISSUE TITLE
Areas not picking up raycast

### ISSUE THREAD

**Issue by FilipLundby** [godotengine/godot#28261]
**Godot version:**
3.1.stable.official x11.64x

**OS/device including version:**
Linux, Manjaro KDE

**Issue description:**
I'm casting a ray at an Area (3D) using `intersect_ray(...)`. Expecting the `intersect_ray(...)` to return a result, but it returns an empty object `{}`.
Meanwhile, casting a ray at Rigidbody works.

**Steps to reproduce:**
Scene tree:

- Spatial
    - Area
        - CollisionShape

1. Enable "Input Ray Pickable" on the Area
2. Set the shape on CollisionShape to BoxShape (also tested with SphereShape)
3. Cast ray at the Area using `intersect_ray` (see demo project)

**Minimal reproduction project:**
This project demonstrates raycast against an Area and a Rigidbody. I'm casting a ray from the root-Spatial (0, 0, 0) to (10, 0, 0)

[AreaRaycast.zip](https://github.com/godotengine/godot/files/3101039/AreaRaycast.zip)

**Comment by bojidar-bg** [comment]
You forgot to pass `collide_with_areas = true` to `intersect_ray()`. It can be done like this:
```gdscript
var result = space_state.intersect_ray(Vector3(0, 0, 0), Vector3(10, 0, 0), 
    [], 0x7FFFFFFF, true, true)
```

Closing, since the documentation states that the last argument is `false` by default, and thus the observed behavior is expected.

**Comment by FilipLundby** [comment]
Thanks, but now it seems the Area is pickable even when "Input Ray Pickable" is false. 

[AreaRaycast.zip](https://github.com/godotengine/godot/files/3101331/AreaRaycast.zip)

**Comment by bojidar-bg** [comment]
Well, I doubt that ray you are casting is an "Input ray"...
Anyway, if you want to have areas which can't be hit with a ray, why not use Collision Layers and Masks?

**Comment by PetePete1984** [comment]
Input Rays come from the engine and are the "last step" in default input processing if nobody else consumed an input, see also https://docs.godotengine.org/en/3.1/tutorials/inputs/inputevent.html

Casting your own rays bypasses that completely because your rays aren't part of the input system :)

**Comment by Zireael07** [comment]
Just ran into a similar issue in Godot 3.2.3. "Input ray pickable" is described as "If true, the CollisionShape's objects will respond to RayCasts".

Nothing, nada, about this not applying to your own rays.

**Comment by balloonpopper** [comment]
I'm seeing this issue in 3.3.2. I have an area with a box collision shape. Casting a ray at the area with
	var space_state = get_world().get_direct_space_state()
	var result = space_state.intersect_ray(Vector3(2.5,10,0.5), Vector3(2.5,-10,0.5),[],true,true)
Returns no results. If I change the parent object to a Staticbody and assign the collision shape to it, I get collision data. 

Happy to open a new issue if this one can't be reopened.
