### ISSUE TITLE
Closing scene tab with right-click doesn't update scenes opened on load

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#28263]
**Godot version:**
3.1 stable

**Issue description:**
When you right-click scene tab and close it, it's not stored in editor_layout.cfg when "Restore Scenes on Load" is enabled.

**Steps to reproduce:**

0. Enable "Restore Scenes on Load" in Editor Settings
1. Open a scene
2. Right-click a scene tab
3. Select "Close tab"
4. Restart editor
5. The tab opens again, while it should be closed

**Protip for junior contributors:**
The fix would be the same as in #28067. It's one of the cases missed in that PR (hopefully last one).

**Comment by akien-mga** [comment]
Fixed by #28357.
