### ISSUE TITLE
Vector2.random and Vector3.random constructors

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28264]
I (and probably many other users) use random vectors in nearly every game I make. Making a random vector is currently pretty tedious, so here is my suggestion:
```js
Vector2.random(float minX, float minY, float maxX, float maxY)
Vector2.random(Vector2 min, Vector2 max)
Vector2.random(float maxX, float maxY)
```
And the same for Vector3.

**Comment by Calinou** [comment]
I don't think this is done often enough to warrant new functions. Also, what about other types such as Color?

Currently, this can be achieved with an one-liner:

```gdscript
Vector2(rand_range(min_x, max_x), rand_range(min_y, max_y))
```

**Comment by ismslv** [comment]
Please see my proposal https://github.com/godotengine/godot/issues/28269 , I have this functionality and several similar ones with random.

**Comment by Jummit** [comment]
Closing as @Calinou pointed out that it can be written in one line.

**Comment by DamKoVosh** [comment]
> Closing as @Calinou pointed out that it can be written in one line.

These kind of explanations are just so abolutely frustrating ridiculous ... please guys read Clean Code by Robert C Martin or any other book about modern software engeneering!

Everything that makes code easier to read even if it does not really shorten the code is great. I can write pretty much everything in one line using some languages, that just doesn't mean anything at all. Its about maintainabillity and the abbility to spot bugs, every little thing that helps me to understand the code faster helps there.

Vector.from_rand()
or maybe even better rand_vector() is just cleaner.

I admit this thread might not be the most striking point, but you respond with such answeres pretty much everywhere, where people ask or try to make things easier for everyone, had to say this at some point

**Comment by Calinou** [comment]
@DamKoVosh We have a page about the engine development philosophy here: https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html

**Comment by MaaaxiKing** [comment]
> more flexible than a new built-in function

With an applied impulse on RigidBody2D it's a tiny bit complicated, my example which I really use: `apply_impulse(Vector2(rand_range(-($Sprite.texture.get_size().x) / 2, $Sprite.texture.get_size().x / 2), rand_range(-($Sprite.texture.get_size().y) / 2, $Sprite.texture.get_size().y / 2)), Vector2(rand_range(-5000, 5000), rand_range(-5000, 5000)))`.
Remember "one-liner".

**Comment by Xrayez** [comment]
This issue doesn't seem to describe concrete use cases, but they do exist.

For those stumbling upon this, [Goost](https://goostengine.github.io/) provides a [`Random2D`](https://goost.readthedocs.io/en/latest/classes/class_random2d.html) class which allows to generate unit vector *directions* and *rotation*. Just like **MaaaxiKing** describes, this could be used for impulse computation:

```gdscript
apply_central_impulse(Random2D.direction * power)
```

---

> I don't think this is done often enough to warrant new functions. Also, what about other types such as Color?

Similarly, with [`Random.color`](https://goost.readthedocs.io/en/latest/classes/class_random.html#class-random-property-color) (HSV values are used). I've find it mostly useful for visualization/debugging purposes.

**Comment by erikbgithub** [comment]
@Jummit There now exists a [proposal system](https://github.com/godotengine/godot-proposals) for feature requests and improvement suggestions. If you are still interested in this topic, maybe you can find a proposal there you can connect to?

**Comment by Jummit** [comment]
> @Jummit There now exists a [proposal system](https://github.com/godotengine/godot-proposals) for feature requests and improvement suggestions. If you are still interested in this topic, maybe you can find a proposal there you can connect to?

For now a few helper methods suffice, but I would actually like to see more utility functions for randomness since it's surprisingly hard to get right (for vectors at least).

**Comment by hawkerm** [comment]
+1 - Was just looking into this as I wanted to spread out debris...

**Comment by AThousandShips** [comment]
Do not bump issues without adding more information, especially not ones closed because the proposals have been moved, open a proposal if you want this instead of resurrecting a years old issue

**Comment by hawkerm** [comment]
@AThousandShips I did provide more information, I provided a use-case/scenario where I was looking for this that hadn't been mentioned in the thread prior. I didn't realize there was already another open proposal already, as no one came back here and linked to say one was opened there. Thank you for providing that context on this issue here now.
