### ISSUE TITLE
Creating extended scripts opens other extended scripts instead

### ISSUE THREAD

**Issue by aomimezura** [godotengine/godot#28274]
**Godot version:**

3.1

**OS/device including version:**

Ubuntu 14

**Issue description:**

Occasionally, when extending a script, if there are other scripts extended from the same one, then it opens the file for a different script. 

Example: I have a script called ModalDialog. I have an object with it's own script (built-in) that extends that. It works fine. I added another object and added another built in script by extending ModalDialog, but it opens the script of the first object instead. Closing the script doesn't fix the problem, when reopening the script of the second object, it opens the first one instead.

I used the Extend Script option in the editor to do this. Closing the editor and opening the script produces the same error as above, but clicking Extend Script works correctly afterwards.

**Steps to reproduce:**
Not sure, happens unexpectedly

**Comment by aomimezura** [comment]
Additionally, when I created the second script, it opened a file called ModalDialog.gd in the script editor (rather than what you'd expect for built-in, i.e. the xxxx.tscn::1 format).

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

(I never encountered this personally and I sometimes do a lot of script extending)

**Comment by akien-mga** [comment]
No answer, so closing.

Please comment if you can still reproduce the issue and we can reopen it. If better suited, you can also open a new issue referencing this one.
