### ISSUE TITLE
Methods available to "self" are not showing up in visual script search

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28273]
**Godot version:**
33b69340a

**Issue description:**
When searching with "Find Node Type" or by dragging out from a port methods available to "self" don't show up as they used to (I think they did). I expected to see all methods I see when dragging of a "Self" node.

**Steps to reproduce:**
Make a Visual Script, hit Ctrl+F and look for methods that are available when dragging of a "Self" node.

**Comment by clayjohn** [comment]
I can't reproduce in 3.1. 

Could you provide more information? The templates are there to be filled out. Start with version and then describe the expected behaviour and the result.

**Comment by Jummit** [comment]
@clayjohn Sorry, I wasn't very clear. I can access methods in the search, just not ones specific to the base type of the script.

**Comment by fire** [comment]
Please check again. https://github.com/godotengine/godot/pull/28447
