### ISSUE TITLE
CanvasModulate Color property doesn't have "Revert" button if scene is inherited

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#28279]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 7 x64

**Steps to reproduce:**
1. Scene 1 with CanvasModulate node,
2. Scene 2 is inherited scene from Scene 1,
3. Change Color in ColorModulate node in Scene 2

**Result:** no revert button for "Color" property
![2019-04-21_200036](https://user-images.githubusercontent.com/1552169/56473508-e0ae1600-6474-11e9-869e-1430e8be042d.png)

**Expected:** revert button is displayed, because color not equals to color in parent scene

**Minimal reproduction project:**
[21042019.zip](https://github.com/godotengine/godot/files/3101443/21042019.zip)

**Comment by KoBeWi** [comment]
I've seen this happen with other properties too, but it's seemingly random. This particular one happens when inherited scene uses default color. If Scene 1 has color different than white, the revert button correctly appears.

**Comment by KoBeWi** [comment]
Still valid in ba1109a3b

I tested again and this issue probably happens only with CanvasModulate's color. `modulate` in CanvasItems nor `color` in ColorRect/ColorPicker don't have this problem. I wonder why this property is special.

> I've seen this happen with other properties too

That could have been #33611.
