### ISSUE TITLE
Static func inside a class inside a script is not showed in function list.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#28270]
**Godot version:**

5772f60f960ee8c396574f0c6f94def18bb210c7

**OS/device including version:**

Win 7 64

**Issue description:**

With this code:

```
extends Node

class OneClass:
	func do_something() : pass
	static func do_other_thing() : pass
func _ready():
	pass 

```

static func is not showed in the function list. If you delete "static" word, the function returns.

**Comment by NilsIrl** [comment]
Working on it
