### ISSUE TITLE
TextureProgress when added a gradient texture will break the layout in the editor

### ISSUE THREAD

**Issue by silkentrance** [godotengine/godot#28282]
**Godot version:**
3.1.stable.official

**OS/device including version:**
Mac OS High Sierra (latest)

**Issue description:**
A TextureProgress (bar) will break the layout in the editor and also in the runtime, when adding a gradient texture to it, as that texture will have a default width of 2048 pixels, which will then be the default width of the TextureProgress (bar).

**Steps to reproduce:**
Load the example project in the editor and see that the layout is broken. Then switch to the progress bars tab and see it in action. (There might be other issues here...)

**Additional Notes:**
One cannot even fix the layout as the TextureProgress (bar)'s width cannot be set to a value less than 2048, everything greater than 2048 is ok, though. (I tried also setting the width of the gradient texture to a value less than 2048, and while it works, the TextureProgress (bar)'s width can still not be reduced.)

**Minimal Project:**
[simple-range-controls.zip](https://github.com/godotengine/godot/files/3101520/simple-range-controls.zip)

**Comment by KoBeWi** [comment]
Your TextureProgress is inside a Container, so the container will fit its size to the texture. If you reduce the texture width _before_ making it visible, it will appear correctly.

As for the container, when it gets too big and then you reduce the internal size, it will auto-magically retract to minimal size when you touch one of the orange edit dots (whatever they are called). This is similar behavior to what was happening in #21803 and it's still valid in master (0b6b49a897b3).

**Comment by spacemonaut** [comment]
I ran into this yesterday in **Godot 3.2.2.stable.official for Win64** while going through the [design interfaces tutorial](https://docs.godotengine.org/en/stable/getting_started/step_by_step/ui_introduction_to_the_ui_system.html) — I wasn't sure how to add a solid color fill for over, under, or progress, so I just picked GradientTexture and had this happen. Here's a screenshot of Help -> About.

![version info from help -> about](https://user-images.githubusercontent.com/4585677/86908164-07a24780-c10e-11ea-8d5a-d83a109b3ecd.png)

Here's reproduction steps to get into this mess:

1. Create a 2D Scene
2. Add a TextureGradient as a child

   ![2020-07-08_11-07-15_Godot_v3 2 2-stable_win64](https://user-images.githubusercontent.com/4585677/86906447-77630300-c10b-11ea-8fd7-d4f089e8cb03.png)

Okay, we're partway in. Let's examine the expected/actual behaviour at this stage.

**Expected:** The TextureGradient is still some reasonable size.

**Actual:** The TextureProgress has become ENORMOUS. Under Control -> Rect, the Size now has an X of 2048. It's not clear why, until we open the gradient to edit it and discover it has a width of 2048.

![2020-07-08_11-07-33_Godot_v3 2 2-stable_win64](https://user-images.githubusercontent.com/4585677/86906488-88137900-c10b-11ea-869a-f4acb7db2ba5.png)
![2020-07-08_11-15-51_Godot_v3 2 2-stable_win64](https://user-images.githubusercontent.com/4585677/86907247-a7f76c80-c10c-11ea-972c-b03014548215.png) ![2020-07-08_11-08-30_Godot_v3 2 2-stable_win64](https://user-images.githubusercontent.com/4585677/86906928-2dc6e800-c10c-11ea-82ee-9c9f2d3d1c87.png)

Right! Our gradient is enormous for some reason, but it's clear we can resize the TextureGradient to fix this, right?

3. Type in "100" into Size X and hit enter.

**Expected:** Size changes.
**Actual:** It stays at 2048.

Hmm...

4. Click the Revert button on Size X.

**Expected:** Something changes.

**Actual:** The X stays at 2048. The Y goes from 40 to 1.

![GIF of me trying to make these changes](https://user-images.githubusercontent.com/4585677/86907651-4be11800-c10d-11ea-9757-0e10d57338f8.gif)

Ok, clearly it's inheriting the size from the gradient texture. I need to change the gradient size first!

5. Scroll up to the gradient. Change Width to "100". Confirm that it sticks.
6. Scroll down to Size again. Set X to "100".

**Expected:** The size is now 100 wide.

**Actual:** The size is *still* stuck at 2048.

![GIF of me trying to do this.](https://user-images.githubusercontent.com/4585677/86907960-b6925380-c10d-11ea-978b-3bfa965a26b3.gif)

Maybe the Gradient doesn't change until I collapse it?

7. Collapse the Gradient texture so I'm no longer seeing its details.
8. Try to change the Width again. The above still happens.

At this stage I have no idea how I'm supposed to have a TextureProgres that has a gradient and less than 2048 width.

**Comment by KoBeWi** [comment]
> At this stage I have no idea how I'm supposed to have a TextureProgres that has a gradient and less than 2048 width.

After making the texture smaller, save the scene and reload it.

**Comment by spacemonaut** [comment]
@KoBeWi I confirm that works. Thank you.

**Comment by Calinou** [comment]
We should probably decrease the default GradientTexture width in 4.0 to make this less problematic. (Something like 256 should be a saner value, while also being faster to generate.)
