### ISSUE TITLE
Repeated introduction & removal of 'index="0"' in .tscn files causes version control clutter

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#28309]
**Godot version:**
3.1

**OS/device including version:**
macOS 10.14.4

**Issue description:**
When scenes are saved, Godot keeps introducing and removing an `index="0"` attribute to/from the .tscn files. Not a critical bug, but a constant nuisance for version control. The issue seems to be related to derived scenes (scenes that use an instance of another scene as their root, which is something I use often and works really well except for this nuisance).

See the following lines from version control diff:
```
-[node name="SomeNode" instance=ExtResource( 1 )]
+[node name="SomeNode" index="0" instance=ExtResource( 1 )]
```
later for the same file:
```
-[node name="SomeNode" index="0" instance=ExtResource( 1 )]
+[node name="SomeNode" instance=ExtResource( 1 )]
```

**Steps to reproduce:**
1. Create a scene and save it (any root node will do)
2. Create another scene that has an instance of the first scene as its root node
3. Make any change to the derived scene and save all; observe that the derived scene's .tscn file has an `index="0"` attribute now.
4. Make any change to the first scene and save all; observe that the derived scene's .tscn file does not have an `index="0"` any longer.
5. Repeat steps 3 & 4.

In Steps 3 & 4, make sure you either use "Save All Scenes" (via menu or keyboard) or simply Run the project each time to ensure all files are saved in one step (i.e. don't simply hit Cmd/Ctrl+S to save each scene one by one).

**Minimal reproduction project:**
[IndexIssue.zip](https://github.com/godotengine/godot/files/3104485/IndexIssue.zip)

This project already has Step 1-2 from above done. Simply open "DerivedScene.tscn" in a text editor and repeat Steps 3 and 4 from above to observe the issue.

**Related issues:**
I thought some work was done to remove resource indices from the .tscn files in v3.1, which would have solved this issue as a side affect, but I can't find that post/entry and Godot 3.1 still has this issue.

**Comment by ArdaE** [comment]
Found a related issue, #17562, that's marked as fixed, which seems to cover a wider range of causes. The remaining issue that I describe in this issue entry is for inherited scenes only, which is not fixed by #17562 apparently.

**Comment by organicpencil** [comment]
Aha, there it is! So I wasn't crazy after all. Good job narrowing that down.

**Comment by KoBeWi** [comment]
OMG, I found the cause XDDD
https://github.com/godotengine/godot/blob/36164168b5525bae3aead5d00063c6a7770bafd7/scene/resources/packed_scene.cpp#L397-L403
`get_index()` will normally return 0, unless the node is out of SceneTree. And it is out of the tree in the editor if you are on another tab. Heh.
