### ISSUE TITLE
Strange stripes on TileMap

### ISSUE THREAD

**Issue by Allespro** [godotengine/godot#28312]
**Godot version:**
v3.1.stable.official

**OS/device including version:**
OS:Arch Linux x86_64
Kernel: 5.0.4-arch1-1-ARCH
Video: Radeon HD 6990 | xf86-video-ati

**Issue description:**
Strange stripes in TileMap node, just watch video https://vimeo.com/331851892

**Comment by Wiering** [comment]
That's probably because you are scaling it by (1.98, 1.96). Try (2, 2).

**Comment by yesitsmattharris** [comment]
You can also turn on pixel snapping; it helped me with the same issue.

Project Settings > Rendering > Quality > Use Pixel Snapping

**Comment by Allespro** [comment]
Will try

**Comment by Allespro** [comment]
> You can also turn on pixel snapping; it helped me with the same issue.
> 
> Project Settings > Rendering > Quality > 2D > Use Pixel Snap

That works!
