### ISSUE TITLE
InputEventScreenDrag.relative and .speed always (0, 0) on Windows

### ISSUE THREAD

**Issue by Vultraz** [godotengine/godot#28319]
**Godot version:**
3.1 official

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
I have a touchscreen laptop. `InputEventScreenDrag` gets triggered correctly when using the touchscreen, but the `relative` field always prints `(0, 0)`. I thought this might have to do with #17131, but this happens even when both "Emulate Touch from Mouse" and "Emulate Mouse from Touch" are turned off.

EDIT: also applies to `.speed`.

**Comment by jcs224** [comment]
Yep, have this exact same issue. Maybe I should take a crack at fixing it, but my C++ skills are meh.

**Comment by Calinou** [comment]
It seems the `relative` property for InputEventScreenDrag isn't implemented on Windows. Compare the Android implementation to the Windows one:

https://github.com/godotengine/godot/blob/5cdecb8227fe6d15d5f5494334df5df9cdcbda0f/platform/android/os_android.cpp#L425-L429

https://github.com/godotengine/godot/blob/5cdecb8227fe6d15d5f5494334df5df9cdcbda0f/platform/windows/os_windows.cpp#L293-L296
