### ISSUE TITLE
UDP server receives packets from client fast, but client receives packets from server slow.

### ISSUE THREAD

**Issue by Sphynxinator** [godotengine/godot#28327]
**Godot version:**
3.1

**Node.JS version:**
10.15.3

**OS/device including version:**
Windows 8.1 (Client)
EC2 Instance - Amazon Linux 2 (Server)

**Issue description:**
I was expecting to take UDP packet from server suddenly, but it sends the message always delay with 12 packets to be exact.

**Steps to reproduce:**
1. Unzip projects.
2. Load the server to your Linux server machine.
3. Change directory to the node.js project and enter DEBUG=UDPServer:* npm start to start the server in debug mode.
4. Now server listens to the incoming packets.
5. Open the Godot project.
6. Change the set_dest_address() "host" to your server's public IP.
7. Run the Godot project.
8. You will see some numbers in both project's terminal.
9. Compare the numbers. Godot sends the numbers exact time to the server, but the server sends back the numbers before 12 packets. Observe.
10. Is there anything can we do to improve the quality of the project, or this is the UDP's natural habit? If it's because of UDP, I'm planning to find other fixes, including screen related cheats.

**Minimal reproduction project:**
[UDPProject.zip](https://github.com/godotengine/godot/files/3107174/UDPProject.zip)

**Comment by Faless** [comment]
I'm not sure I understand the problem.

Keep in mind:

UDP is expected to be unreliable and unordered (which means, some packets might not be delivered, or they might be delivered out of order).

The `_process` method is called every 17 ms .

What exactly is the problem with the project? It seems to work as expected for me.

**Comment by Sphynxinator** [comment]
Did you try the project? When the client sends a packet, it arrives at Node.js server suddenly. But when Node.js sends a packet to the client, the client takes the packets but comes from behind. I am not sure if this would be a problem for me to design my server architecture, because you have to design it as packets arrived so late. Just wanted to say, because maybe some developer could shut down some function in favor of the simplicity of Godot Engine maybe? Sorry if this is not an issue.

**Comment by Sphynxinator** [comment]
First of all, I am so sorry I am opening issues suddenly, but I fixed it up. Problem is, UDP packets are sent to the client suddenly, but 3 packets together. I take the latest packet and it fixed. Thanks and sorry to keep you busy, but you can close it now. Hope this issue will help some people.
