### ISSUE TITLE
Problematic Popup problem: Invisible title

### ISSUE THREAD

**Issue by hacker1122** [godotengine/godot#28325]
Godot version: 3.1 STABLE
OS/device including version: WINDOWS/OS

I've an issue and reported to Q&A, Discord, Udemy (i'm taking a course there) and other support sites but no one respoded me, so i'll try here.
I’m making a movable window in my game, and I’ve used the popup() function. The fact is that I want to style it like a terminal, so i’ve made a custom style (StyleBoxFlat). The problem here is that the “title part” of the popup is bemoming transparent. How I can fix this? 

![unknown](https://user-images.githubusercontent.com/13876831/56566499-1822dc80-65b3-11e9-91f3-ec72547f793d.png)

**Comment by YeldhamDev** [comment]
Dialog title bars in Godot are done via the top border with an expanded margin:
![window](https://user-images.githubusercontent.com/30739239/56585925-48c43f80-65ce-11e9-86a5-09f0f6d7f7f7.png)

**Comment by hacker1122** [comment]
> Dialog title bars in Godot are done via the top border with an expanded margin:
> ![window](https://user-images.githubusercontent.com/30739239/56585925-48c43f80-65ce-11e9-86a5-09f0f6d7f7f7.png)

Thank you soooo much!
