### ISSUE TITLE
Clicking on method names in help system no longer works

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#28329]
**Godot version:**
Latest master but I think this has been broken for a few days
04efa598681fc4903907d160f6dc80fc8537b43f

**OS/device including version:**
Windows 10, unrelated

**Issue description:**
Clicking on method names at the top of the help page:
![image](https://user-images.githubusercontent.com/1945449/56582614-02490200-661b-11e9-8002-fd2cf3fac680.png)

No longer finds the method further down where it has the description of the method.

**Steps to reproduce:**
Open up a help page in the editor, click on a method name.

**Minimal reproduction project:**
n/a

**Comment by YeldhamDev** [comment]
Duplicate of #27983.
