### ISSUE TITLE
Index out of size when trying to drag file to scripts panel

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28344]
**Godot version:**
3.2 2fc2d82

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When I try to drag to empty script panel any file differnt than godot script(with gd extension) then this error occurs:
```
ERROR: move_child: Index p_pos=-1 out of size (data.children.size() + 1=2)
   At: scene/main/node.cpp:323.
ERROR: set_current_tab: Index p_current=-1 out of size (get_tab_count()=1)
   At: scene/gui/tab_container.cpp:464.
```

**Steps to reproduce:**
Edit:
GIF
![jfile](https://user-images.githubusercontent.com/41945903/88825141-84818800-d1c7-11ea-973f-62be24de5473.gif)

**Comment by KoBeWi** [comment]
The video is dead. I can only get
```
scene\gui\tab_container.cpp:552 - Index p_current=0 out of size (get_tab_count()=0)
```
when dragging non-script file on empty script list.

**Comment by KoBeWi** [comment]
Doesn't happen anymore in 8958e1b
