### ISSUE TITLE
Replay scene/project buttons does not change icon back when closing the game

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#2834]
If you click Play Project or Play Scene they change to a "replay" icon. If you close the game it still keeps the "replay" icon. It only goes back to the "play" icon if the Stop button is pressed.

![2015-11-19_13-16-24](https://cloud.githubusercontent.com/assets/5599796/11277331/4ba4f54a-8ecd-11e5-8b2c-c81a13224741.png)

**Comment by akien-mga** [comment]
The logic was introduced here: 65258f7
Maybe @AlexHolly can help improve it.

**Comment by AlexHolly** [comment]
I thought I had all cases :D this should solve it #2837
