### ISSUE TITLE
Confusing to get out of TextureRegion editor

### ISSUE THREAD

**Issue by aomimezura** [godotengine/godot#28341]
**Godot version:**

3.1

**OS/device including version:**

Ubuntu 14

**Issue description:**

I was creating a theme. I added the panel container class, added a stylebox, added a texture to the style box, then I couldn't figure out how to get out of the TextureReigon editor back into the Style editor. I eventually figured out you had to minimize the panelcontainer in the inspector, and reload the theme to get the style editor back.

**Comment by KoBeWi** [comment]
I just encountered it in 3.2.2. This is another issue similar to #28211, the editors for theme and texture region are conflicting here.

**Comment by flodihn** [comment]
I had the exact same issue twice in 2021, expect minimizing did not work, I had to find a scene which had a control node with this theme assign to click on it there to make the theme edit show up, which makes no sense.
