### ISSUE TITLE
Add method to get list of all loaded translations/locales

### ISSUE THREAD

**Issue by MuffinManKen** [godotengine/godot#28358]
I was messing around with a UI to allow the user to choose their language and I wanted to be able to add a translation and have it automatically available in the UI. AFAIK there is no way to get a list of the locales that have a translation from the Translation server.

It's a tiny bit of code, but it doesn't seem possible from GDScript. Is this something others would find useful?

**Comment by homer666** [comment]
Looks like they already exist internally (`TranslationServer::get_all_locales()` and `TranslationServer::get_all_locale_names()`) so they just need to be exposed to GDScript. I couldn't manage it so hopefully someone more experienced can help out.

**Comment by MuffinManKen** [comment]
Those methods return the complete list of locales defined in the engine, not the ones that have a loaded translation.

**Comment by homer666** [comment]
Oh, I guess that explains why it wasn't exposed...

This seems pretty useful so I've made an attempt: #28368

**Comment by MuffinManKen** [comment]
I was going to submit a PR, but thought I'd see if people thought is was generally useful. :)

**Comment by homer666** [comment]
Oh... guess I'll close mine.

**Comment by MuffinManKen** [comment]
I didn't mean to imply that you should close yours!

**Comment by homer666** [comment]
Ah sorry, I didn't mean for it to come off that way!! I quickly slapped together the PR since I interpreted this issue as a feature request from someone who wasn't able to do it themselves, but if you have an implementation ready and everything then I'd rather leave it to you.

**Comment by MuffinManKen** [comment]
I'm an experienced coder, but an inexperienced FOSS-contributor. :)
