### ISSUE TITLE
Cannot find binary for MSBuild on Ubuntu with Godot 3.1

### ISSUE THREAD

**Issue by jejay** [godotengine/godot#28352]
**Godot version:**

Godot_v3.1-stable_mono_x11.64

**OS/device including version:**

Ubuntu 18.04.2 LTS

    ~$ whereis mono
    mono: /usr/bin/mono /usr/lib/mono /etc/mono /usr/share/mono /usr/share/man/man1/mono.1.gz

    ~$ mono --version
    Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	    TLS:           __thread
	    SIGSEGV:       altstack
	    Notifications: epoll
	    Architecture:  amd64
	    Disabled:      none
	    Misc:          softdebug 
	    LLVM:          supported, not enabled.
	    GC:            sgen

    ~$ whereis dotnet
    dotnet: /usr/share/dotnet /home/julian/dotnet/dotnet
    
    ~$ dotnet --version
    2.2.203
    
    ~$ dotnet msbuild -version
    Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
    Copyright (C) Microsoft Corporation. All rights reserved.

    16.0.450.56488

**Issue description:**
When trying to run a project with a minimal C# Script attached to it, the editor crashes with the following error.

    ERROR: godot_icall_BuildInstance_get_MSBuildPath: Cannot find binary for 'MSBuild (Mono)'
       At: modules/mono/editor/godotsharp_builds.cpp:160.

    Unhandled Exception:
    System.IO.FileNotFoundException: Cannot find the MSBuild executable.
      at GodotSharpTools.Build.BuildInstance.GetMSBuildPath () [0x00013] in <2ec1c4e0a5154cc6b5f49f178aa041fc>:0 
      at GodotSharpTools.Build.BuildInstance.Build (System.String loggerAssemblyPath, System.String loggerOutputDir, System.String[] customProperties) [0x0001a] in <2ec1c4e0a5154cc6b5f49f178aa041fc>:0 
    Stacktrace:

(Omitted the long native Stacktrace). I have to delete everything C#-ish (*.sln, *.csproj, .mono/, *.cs) to get Godot to build/run the project again.

**Steps to reproduce:**
1. Create a new project
2. Create a new Node2D
3. Attach C# script to Node2D
4. Build/Run the project

I know that there are plenty of similar issues but they are all closed/fixed and with older versions, so I decided to open up this new one.

**Comment by neikeq** [comment]
We don't use `dotnet build` as it doesn't support .NET Framework. Try the `msbuild` package.

**Comment by jejay** [comment]
Okay, I got it. I thought I had installed everything possible, but I mixed up the package sources. My mistake, thank you and sorry!

**Comment by ptlthg** [comment]
To anyone still having this issue, it's likely not Godot's fault. Check in _/usr/bin/_ and look for a "msbuild" executable file, if it's not there install it by following the steps here: https://www.mono-project.com/download/stable/#download-lin

I spent too long before I realized that I never had it and I feel dumb. Hopefully, this helps someone out.
