### ISSUE TITLE
New feature - show spaces in editor

### ISSUE THREAD

**Issue by iwek7** [godotengine/godot#28355]
Hello,

I'm requesting feature to add editor function to show spaces. Since gdscript is indentation based and spaces are allowed for indentation usage it would be actually very useful to have some visual aid in counting them. Issues with pasting code snippets with slightly off spaces count are very annoying since it is difficult to quickly tell what is wrong. Also there is already feature to show tabs. Also similar features are supported in pretty much every IDE i've ever used.

I've done example implementation of this feature. What I propose is to add new menu position in Indentation tab  'Show spaces' (default false) like so:

![godot_menu](https://user-images.githubusercontent.com/9964886/56613292-9fee0280-6616-11e9-9883-82949261f665.png)

Toggling this option on would then result in spaces being visible marked by dots like so:

![code_godot](https://user-images.githubusercontent.com/9964886/56613310-ada38800-6616-11e9-9c74-3eeedd598739.png)

I'm new to godot but proposed feature does not seem to require a lot of changes. Main logic goes into text_edit.cpp and couple of other files (mostly setters/getters). New svg for space icon had to be added and from readme in icons folder it seems that running some optimization script on this svg is needed as well as PR into some images repo. Perhaps space image could still be improved somehow(?). For comparison I include similar feature in main Java IDE Intellij - as you can see space markers there a smaller and positioned closer to the bottom of the line:

![intellij_code](https://user-images.githubusercontent.com/9964886/56613333-bac07700-6616-11e9-9871-ed9c7e729d69.png)

Please tell me if you think this feature is useful, I will gladly submit PR, as you can see I've done most of the work already.

**Comment by piratesephiroth** [comment]
yeah I like it

**Comment by Jalu1** [comment]
Looks solid to me

**Comment by Lisapple** [comment]
I would be a nice addition to only show spaces for current text selection (like Sublime Text).

**Comment by iwek7** [comment]
Sublime let's you choose if you want to show them always or in selection only (default). I think it's more common for IDEs to show whitespaces always or not at all - maybe there could be new setting added to control it - show all / none / selected. Maybe in future options 'draw spaces' and 'draw tabs' could be merged into 'draw whitespaces' which would make settings easier.
