### ISSUE TITLE
Visual Shader Alpha Dissolve

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#28364]
**Godot version:**
bc7178422e98c86c7c8c9d9e572a9c6941836d79

**Issue description:**
When doing the same as GDQuest but changing the sphere for a monkey head the effect do not work. the mesh just pops in for a split second and then are invisible the rest of the time

Is this a bug??

![5d80caffb4d57ec96b327324159ea12c](https://user-images.githubusercontent.com/13393087/56622673-5a8afe80-6631-11e9-8cc8-c3853f8dcbd0.gif)

**Comment by CowThing** [comment]
Does the mesh have UVs? I don't think the monkey head has UVs by default.

**Comment by Norrox** [comment]
> Does the mesh have UVs? I don't think the monkey head has UVs by default.

You are correct, my mistake. it worked when i applied an uv to the shape, thanks!

**Comment by Norrox** [comment]
![6146e9ef7efe7df0ea7c7db59e9eb842](https://user-images.githubusercontent.com/13393087/56768247-2721ae80-67ae-11e9-9681-1bb3439348b5.gif)
