### ISSUE TITLE
Inspector doesn't display exported properties of custom resource written in C#

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#28367]
**Godot version:**
`master` / 7be49849

**OS/device including version:**
Manjaro Linux 18.0.4

**Issue description:**
I made the following simple custom resource for a test in C#, but the inspector doesn't show its exported properties when I built the project and attached the source to a blank resource file:

```csharp
namespace AlleyCat.Morph
{
    public class RangeddMorphDefinition : Resource
    {
        [Export]
        public string Key { get; set; }

        [Export]
        public string DisplayName { get; set; }

        [Export]
        public float Default { get; set; }

        [Export]
        public bool Hidden { get; set; }
    }
}
```
How it is displayed in the inspector:
![image](https://user-images.githubusercontent.com/2367032/56623015-54b30e80-666d-11e9-8698-56c59470a2b9.png)

**Comment by neikeq** [comment]
I can't reproduce this. It does show up for me. Can you provide an example project?

**Comment by mysticfall** [comment]
@neikeq It used to work before, so there's a chance that there is something wrong on my end.

I'll try to create a minimal project soon as requested, and let you know if it's still reproducible. Thanks!

**Comment by mysticfall** [comment]
Today I tried it again with a minimal project but could not reproduce the issue. I suppose there are some specific things in my project that prevent it from working correctly.

I'll reopen the issue with more details later, if I find an actual problem on the Godot's end. Sorry for the confusion!
