### ISSUE TITLE
Noised sound when play a lot of the same AudioStreamSample

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#28379]
**Godot version:**

Godot 3.1.1.dev (4764e1797)

**OS/device including version:**

MacOSX 10.13.6

**Issue description:**

In my game many (50 - 100) objects in specific situation may start playing the same sound at one time (or with very small gap). The resulting sound is noticeable noised.

I'm going to implement the limiter in AudioStreamSample in order to bypass playing signals when many sound instances already in the air.

Is there any another method to solve this issue? Or may be there are some reasons to go to another way?

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment]
I think that's expected, when you play a lot of sound together, they might overlap and thus create interference. That's how it works for any audio system.
If you want to avoid that, you should pool you sounds and limit how many sounds can be played together.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by DrMoriarty** [comment]
@KoBeWi 
I fixed this bug (as many others) in my own branch. So I don't care ;-)
