### ISSUE TITLE
Editor File Explorer Support for `Back` and `Forward`.

### ISSUE THREAD

**Issue by ScepticDope** [godotengine/godot#28387]
**Feature Request:**
I'd really like it if the Editor's File Explorer would support `Back` and `Forward`. Backspace's `Back` is already supported but I'd like support for the `Back` and `Forward` on a mouse. And preferably if there is no folder to go back to `Back` just moves the folder selection to its parent.

**Comment by Calinou** [comment]
These buttons could also be supported in other places where it makes sense, such as the script editor.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/954, as feature proposals are now tracked on the Godot proposals repository.
