### ISSUE TITLE
Android: Meshes assigned by SurfaceTool.commit not "materializing"

### ISSUE THREAD

**Issue by tcrass** [godotengine/godot#28383]
Godot version:
Official 3.1.1-RC1

OS/device including version:

    Development:
        Hardware: OpenGL ES 2.0 Renderer: Gallium 0.4 on AMD POLARIS11 (DRM 3.27.0 / 4.19.0-0.bpo.2-amd64, LLVM 3.9.1)
        OS: Debian Stretch
        uname -a: Linux caladan 4.19.0-0.bpo.2-amd64 #1 SMP Debian 4.19.16-1~bpo9+1 (2019-02-07) x86_64 GNU/Linux

    Deployment:
        Hardware: Samsung Galaxy S9
        OS: LineageOS 15.1 (= Android 8.1)

**Issue description:**
I have a MeshInstance whose actual mesh data I manipulate using both SurfaceTool and MeshDataTool. When I finally commit the manipulated vertices back to the MeshInstance (line 30 in the Ground.gd script included in the supplied test project), the manipulated mesh shows up as expected in Godot's development output window. However, when running the project after deployment to Android, the manipulated mesh is no longer visible.
When exporting the project with line 30 being commented out, the (now, of course, unmanipulated) mesh shows up in Android as expected.
I don't believe this is just a visibility issue; rather, the committed mesh data seem to be really missing in Android. I initially encountered this issue when I was creating a collision sibling from a MeshInstance manipulated as described above and an object which was supposed to interact with the ground mesh just dropped down into negative Y nirvana...

**Steps to reproduce:**
Deploy the supplied test project to an Android device
- as is
- after commenting out line 30 in Ground.gd

**Minimal reproduction project:**
[vrtest.zip](https://github.com/godotengine/godot/files/3111350/vrtest.zip)

**Comment by tcrass** [comment]
Seems to be working in 3.2 (tried out the official alpha2) -- hence I suggest to close this bug report.

Cheers --
    Torsten

**Comment by punaukko** [comment]
Not sure if this a bad habit when a bug report is closed a long time ago.

This seem to happen on the mobile renderer on Samsung S9+ (Android 10)

I tried both Godot 4.1.2.stable and 4.2b3.

**Comment by akien-mga** [comment]
This is indeed a bad habit :) This bug was fixed 4 years ago, the one you experience is a different issue, even if the symptoms are similar. Please open a new bug report with a reproduction project.
