### ISSUE TITLE
Godot won't run / failed init dinput: -2147467259

### ISSUE THREAD

**Issue by Gavin-Williams** [godotengine/godot#28394]
**Godot version:**
Godot_v3.1-stable_mono_win64

**OS/device including version:**
Windows 10 / NVidia RTX 2060

**Issue description:**
Editor won't run, fails with message 'failed init dinput: -2147467259'

**Comment by akien-mga** [comment]
Could you run it from `cmd.exe` with the `--verbose` option?

Could you also try the non-Mono build to rule out any Mono-specific issue?

**Comment by Gavin-Williams** [comment]
The non-Mono version runs. And I got the Mono version to run by copying the folder over to my Dev drive (E) and running it from there. So it wont' run from C drive in Program Files.

**Comment by akien-mga** [comment]
CC @neikeq

I guess Windows has specific restrictions on `C:\Program Files*\`, would it break setting up?

**Comment by Gavin-Williams** [comment]
Mono installed to C drive no problem so far.

**Comment by neikeq** [comment]
Is the problem only reproducible when Godot is located somewhere in `C:\Program Files*\` and is it only reproducible with the mono builds?

**Comment by Gavin-Williams** [comment]
Yes, that's correct.

**Comment by neikeq** [comment]
Can you check if #30820 fixes this issue? If not, can you share the command line output?
