### ISSUE TITLE
randi() of RandomGenerator returns signed int instead of unsigned int

### ISSUE THREAD

**Issue by zEh-** [godotengine/godot#28393]
**Godot version:**

? - 3.1

**Issue description:**

Native randi() and GD.Randi() in C# returns uint. But RandomGenerator.Randi() returns int.
Also wrong: Docs and https://github.com/godotengine/godot/blob/master/doc/classes/RandomNumberGenerator.xml#L42

**Comment by zEh-** [comment]
See https://github.com/godotengine/godot/issues/23329 aswell

**Comment by akien-mga** [comment]
>  Also wrong: Docs and https://github.com/godotengine/godot/blob/master/doc/classes/RandomNumberGenerator.xml#L42

`Variant` only has `int` type, so this is correct.

`RandomNumberGenerator::randi()` does return an `uint32_t` in `core/math/random_number_generator.h`, so that's correct. It's the exposed to script languages as `int`, so it's a signed int with a guaranteed positive value. So from a quick look it doesn't seem to be a bug but a design choice.

CC @neikeq

**Comment by zEh-** [comment]
It states "Generates pseudo-random 32-bit unsigned integer between '0' and '4294967295', inclusive.".
These values don't fit in a signed int.

**Comment by akien-mga** [comment]
It's a 64-bit signed int.

**Comment by zEh-** [comment]
That's even worse then. A falsely returned sint32 which actually holds a uint32 could have been recovered with unchecked((uint)someInt) in C#. No way to get the actual value, when the API returns a int32 which tries to hold a sint64. Am I getting something wrong?

**Comment by akien-mga** [comment]
> That's even worse then. A falsely returned sint32 which actually holds a
uint32 could have been recovered with unchecked((uint)someInt) in C#. No
way to get the actual value, when the API returns a int32 which tries to
hold a sint64. Am I getting something wrong?

Yes, you're getting it wrong. It's a signed 64-bit int which holds the
value of a 32-bit unsigned int. I don't see any problem.

**Comment by zEh-** [comment]
C# binding: [GodotMethodAttribute("randi")] public **int** Randi();

**Comment by akien-mga** [comment]
@neikeq The Mono bindings should likely be fixed to use `sint64` for `Variant::INT`.

**Comment by neikeq** [comment]
The only reason I didn't make it use `long` for everything is because I want to make it possible for `GetTypeInfo` to differentiate between the two.

**Comment by zEh-** [comment]
Well that's a good reason. Also the C# API currently feels like it's getting somewhere with generics etc. Having long kinda everywhere would break that imo.
