### ISSUE TITLE
Add an "Apply to all" option when reimporting multiple textures

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#28403]
**Godot version:**
3.1, 3.1.1-rc1

**OS/device including version:**
Desktop Linux 64 bits

**Issue description:**
**Feature request**
When you select multiple textures and go to the import panel, if you want your changes to actually apply when you hit [Reimport] you also need to tick the checkbox on the left for every setting you want updated. 
This is unintuitive for people not used to this behavior and it also means that if you want to modify all or most settings you need to tick all the checkboxes one by one. 

I think it'd improve usability if an "Apply to all" button/checkbox was added that would clear/set all checkboxes at once. 

![image](https://user-images.githubusercontent.com/526829/56683158-5f889600-66a3-11e9-8eea-48de11ac0fc7.png)

**Comment by KoBeWi** [comment]
The checkbox gets automatically enabled for any setting you change, so this was effectively resolved.
