### ISSUE TITLE
Project manager opens instead of editor when Godot is run from the command line

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#28406]
**Godot version:**
v3.1

**OS/device including version:**
MacBook Pro
macOS 10.14.4

**Issue description:**
I cd'd to my game's project directory and ran this command:

`/Users/foo/dev/Godot/Godot.app/Contents/MacOS/Godot -e`

The project manager opened instead of the editor. The documentation says this should work:

https://docs.godotengine.org/en/3.1/getting_started/editor/command_line_tutorial.html#running-the-editor 

Using the --path argument explicitly does work:
`/Users/foo/dev/Godot/Godot.app/Contents/MacOS/Godot --path /Users/foo/dev/mygame -e`

**Comment by akien-mga** [comment]
It works on Linux, that's probably due to the .app bundle.

**Comment by bruvzg** [comment]
Bundled app change working folder to bundle's `Resources` subfolder on start. This is required for exported apps to work properly, but is not for the editor. Probably should be disabled in case of editor.

**Comment by kristinalustig** [comment]
This also happens when I press "edit" from the project manager itself. It closes the project manager, and then opens it right back up as if it's silently failed. Also on a MBP, I'm on 10.14.3. I'm unable to edit any files that I've previously saved, I'm only able to create and edit new ones.
