### ISSUE TITLE
SCONS error compiling Godot 3.0.6

### ISSUE THREAD

**Issue by Gramps** [godotengine/godot#28409]
**Godot version:**
Godot 3.0.6

**OS/device including version:**
Ubuntu Linux 19.04

**Issue description:**
Trying to compile Godot 3.0.6 but receiving this error:

```
TypeError: can_build() takes exactly 2 arguments (1 given):
  File "/home/gp/Programs/Godot/Source-306/SConstruct", line 407:
    if (config.can_build(selected_platform)):
```
Using GCC 7, 8, or 9.  I believe I am using SCONS 3.0.1 as well.

**Comment by Gramps** [comment]
Weirdly enough, if I dump something like "env" in that can_build line, it gives me this error:

```
TypeError: can_build() takes exactly 1 argument (2 given):
  File "/home/gp/Programs/Godot/Source-306/SConstruct", line 407:
    if (config.can_build(selected_platform, env)):
```
Also note, I have no such issues when compiling Godot 3.1 for whatever reason.

**Comment by akien-mga** [comment]
> Additional note, I am using a custom module.

The problem is with your module.
The `config.py` `can_build` signature for 3.0 is `can_build(platform)`, for 3.1 it's `can_build(env, platform)`.

3.1 is backward compatible with the 3.0 syntax, so if you want to support both with the same code, you can use that.

**Comment by Gramps** [comment]
Noted. The trace didn't really help much so thanks for that!
