### ISSUE TITLE
Add new QtCreator .cxxflags and .cflags files to .gitignore

### ISSUE THREAD

**Issue by youreperfect** [godotengine/godot#28408]
**Godot version:**
latest commit at time of this writing: 11bac340d

**OS/device including version:**
all

**Issue description:**
QtCreator 4.9 now adds .cxxflags and .cflags when importing Godot (in addition to the .config, .files, etc files that are already in the .gitignore so the Qt section of the .gitignore should now read (note: Qt is also mis-capitalized as QT in this section too)

```
# Qt project files
*.config
*.creator
*.creator.*
*.files
*.includes
*.cxxflags
*.cflags
```

**Steps to reproduce:**
1) clone Godot repository
2) floow the steps here: https://docs.godotengine.org/en/3.1/development/cpp/configuring_an_ide.html
3) notice git is finding .cxxflags and .cflags files and git GUIs like Github Desktop try to add them to the commit

**Comment by youreperfect** [comment]
diff --git a/.gitignore b/.gitignore
index 2697507ad..18d41aefb 100644
--- a/.gitignore
+++ b/.gitignore
@@ -40,12 +40,14 @@ gmon.out
 *.swo
 *.swp

-# QT project files
+# QtCreator project files
 *.config
 *.creator
 *.creator.*
 *.files
 *.includes
+*.cflags
+*.cxxflags

 # Eclipse CDT files
 .cproject

**Comment by akien-mga** [comment]
Feel free to make a PR for those changes.
