### ISSUE TITLE
GL Vendor not available from code

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#28404]
**Godot version:**
3.1

**OS/device including version:**
all

**Issue description:**

OS class has lots of useful methods:
```
String | get_locale ( ) const
String | get_model_name ( ) const
String | get_name ( ) const
String | get_video_driver_name(VideoDriver) const
VideoDriver | get_current_video_driver() const
```
but there's no method to get the current GL vendor (even though godot prints it on startup)

Suggest adding the following:
```
String | get_video_driver_vendor()
String | get_video_driver_version()
```

Related to #21427 but that one is about CPU info.

**Comment by gdupr** [comment]
You can find the function glGetString() in drivers\gles2\rasterizer_gles2.cpp, I think that can solve your issue for 3.1 and 3.2.

```
glGetString(GL_VERSION) 
glGetString(GL_VENDOR)
```

https://www.khronos.org/opengl/wiki/GLAPI/glGetString

As you can see there, we could use the GL_SHADING_LANGUAGE_VERSION constant to also get the shading language version.
```
String | get_shading_language_version()
```

**Comment by jamie-pate** [comment]
Yes, the code i saw was
https://github.com/godotengine/godot/blob/master/drivers/gles2/rasterizer_gles2.cpp#L262
https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_gles3.cpp#L189

Which just throws away the string after it prints to stdout..
Leading me to this workaround :face_with_head_bandage: 
`dummy.gd`
```
extends SceneTree
func _init():
     pass
```
`device_compat.gd`
```
var script_path = _extract_script('res://dummy.gd')
var output = []
OS.execute(OS.get_executable_path(), ['-s', script-path], true, output)
version = output[0]
```

**Comment by jamie-pate** [comment]
NOTE, this only works when "rendering/threads/thread_model" is set to "Single Safe" or "Single Unsafe"

Is there a way to run code on the visualserver thread from gdscript for a workaround?
