### ISSUE TITLE
Redraw needed after toggling off Editable Children

### ISSUE THREAD

**Issue by Vultraz** [godotengine/godot#28414]
**Godot version:**
3.1 official

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
If Editable Children is enabled on an instanced scene and child nodes added to said scene, those nodes will still appear in the editor window once you disable Editable Children despite them being deleted from the tree.

**Comment by KoBeWi** [comment]
I can't seem to reproduce it.
@Vultraz What are the exact steps? Does it still happen in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3)?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
