### ISSUE TITLE
vr-common wrongly downloaded with AssetLib

### ISSUE THREAD

**Issue by AkatDeen** [godotengine/godot#28420]
Godot 3.1

using Oculus VR, not Open VR

**Issue description:**
vr-common downloaded from AssetLib not retreive the correct addons from the GitHub

**Steps to reproduce:**
1. AssetLib
2. get 'vr help scenes and files'
3. Download & Install
it will only get Functions & Images folder (no materials, misc & objects folder)

and also, the functions 'Function Teleport.tscn' will give inverted teleport gizmo

**Comment by KoBeWi** [comment]
Works fine in 3.2.3 rc3
Not sure if it was AssetLib problem or with the plugin.
