### ISSUE TITLE
add .md files to resorce in export

### ISSUE THREAD

**Issue by davincif** [godotengine/godot#28424]
**Godot version:**
3.1

**OS/device including version:**
Linux Mint 19 Cinnamon x64
kernel 4.15.0-47-generic
AMD Ryzen 5 2600 Six-Core Processor × 6
NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] not graphic related, though
Google Chrome Version 73.0.3683.103 (Official Version) 64 bits

**Issue description:**
I needed to add a .md file to my exports in a game, with the purpose of fulfilling some license agreement and presenting at the game's credits.
since I saw in the docs and in for that un add "*.json" at the, which I already used and works just fine, then a tried to add "*.md" file, but it doesn't work, also tried to put the entire path to the file, relative and absolute, no success.
I'm not sure if it's a bug or if it's how it was supposed to be...

**Steps to reproduce:**
1. Create a new project, add a directory of your choice, add a .md file
2. Make a quick to read this file's content and fill the label (or a RichTextLabel), like
```gdscript
var file: File = File.new()
file.open("res://LICENSES/License_Notes.md", file.READ)
var read = file.get_as_text()
file.close()
get_node("RichTextLabel").text = read
```
3. Go to the export menu, at "Resources" tab in "Files to export ...", add ```*.md```
4. Export, run the game, and see if the file was found and the label got filled

**Comment by KoBeWi** [comment]
Works fine for me
![image](https://user-images.githubusercontent.com/2223172/58272979-012d0100-7d90-11e9-82a7-91be285c86f4.png)
Tested on Windows 10 x64

Are you sure you specified files in correct field? Does the file work when playing from editor?

**Comment by Calinou** [comment]
Make sure the path's casing matches the actual path on the filesystem (case insensitivity can cause issues to appear).

**Comment by Calinou** [comment]
@davincif Can you still reproduce this in Godot 3.2.1 or 3.2.2beta3?

**Comment by davincif** [comment]
@Calinou I'll try it out again as soon as I can.

**Comment by akien-mga** [comment]
It also works for me, so I'll assume it was a user error.
