### ISSUE TITLE
BulletPhysicsDirectBodyState has no documentation

### ISSUE THREAD

**Issue by Nophlock** [godotengine/godot#28421]
**Godot version:**
3.1.0 Stable

**OS/device including version:**
Windows 10 
Radeon RX 570

**Issue description:**
I currently want to program a little pickup system similar how it works in Portal or Half-Life when you pickup a box. Since I don't want the object the player picked up to clip through walls while holding it, I've taken a look in the "_integrate_forces" method from the rigid-body. At first I simply wanted to try out the code from the wiki https://docs.godotengine.org/en/3.1/tutorials/physics/rigid_body.html but this throws the error, that the "get_step" method is unknown. After that I've find out, that the state from the Bullet engine isn't documented anywhere. Since it seems to use other methods and variables as the one from the GodotPhysics it would be nice to know what methods can be called and which variables it have. 
 
**Steps to reproduce:**
Just open the docs in Godot and look for BulletPhysicsDirectBodyState

**Comment by Nophlock** [comment]
Okay, nevermind I've made a stupid typo ...

**Comment by akien-mga** [comment]
There's nothing to document, it's just a specialized version of http://docs.godotengine.org/en/3.1/classes/class_physicsdirectbodystate.html#class-physicsdirectbodystate which has the documentation.

**Comment by Nophlock** [comment]
Yeah, I know. In the end a stupid typo leaded to the wrong assumption :/
