### ISSUE TITLE
LineEdit scrolls all the way to the cursor when loaded from PackedScene

### ISSUE THREAD

**Issue by Enhex** [godotengine/godot#28426]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
LineEdit's text that was entered via the UI isn't being saved with PackedScene.
When setting text via code it is saved.

**Steps to reproduce:**
Set a LineEdit's text via the UI and try to save & load it with PackedScene.

**Minimal reproduction project:**
[packedscene.zip](https://github.com/godotengine/godot/files/3118539/packedscene.zip)
Note: In the project's script uncomment the line `line.text = line.text` for the text to be saved successfully.

**Comment by KoBeWi** [comment]
After some testing, I discovered that the text IS saved, but when you load LineEdit, it scrolls to cursor position. When you write text normally and save, the cursor is probably at the end, which means the text is scrolled when you load (just move cursor to the left and the text is there). Setting the text from script moves the cursor at the beginning, so this behavior isn't observed. I'll update the issue name, although it might be a duplicate then.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta2
Not sure what to do about it tbh. Maybe after scrolling the caret should be in the middle instead of at the beginning.

**Comment by KoBeWi** [comment]
Fixed in 4.0
