### ISSUE TITLE
CPUParticle rendered at incorrect size on first frame

### ISSUE THREAD

**Issue by cart** [godotengine/godot#28434]
**Godot version:**
3.1 Official

**OS/device including version:**
Arch Linux

**Issue description:**
When a ~~particle~~ CPUParticle system is first added to a scene and started for the first time a particle is rendered at the wrong size for the first frame. This results in an annoying "flash". ~~This only happens in the GLES2 renderer~~ This happens in both GLES2 and GLES3 and it only happens on the first run. Subsequent disable/enable calls behave normally. 

**Steps to reproduce:**
See the project below.

**Minimal reproduction project:**
[Repro.zip](https://github.com/godotengine/godot/files/3119222/Repro.zip)

**Comment by cart** [comment]
Interesting. It also ignores the vertex color for the first frame when the particle's material override has vertex_color_use_as_albedo set to true.

**Comment by cart** [comment]
Minor correction: This is not a GLES2 problem. It is a CPUParticle problem. The issue also occurs in GLES3 using CPUParticles

**Comment by clayjohn** [comment]
Confirmed in 3.1, but it is fixed in master by https://github.com/godotengine/godot/pull/28380!
