### ISSUE TITLE
Defaulting to integrated GPU instead of dedicted GPU

### ISSUE THREAD

**Issue by PtrMan** [godotengine/godot#28437]
**Godot version:**
3.1 (steam)

**OS/device including version:**
Ubuntu Linux, Intel® Core™ i7-4700MQ CPU (with Haswell Graphics), NVIDIA GT 740M

**Issue description:**
It was always using the Haswell GPU instead of the dedicated GPU in the Laptop.
The effect of this was a bad performance.

**Comment by YeldhamDev** [comment]
Does this only happen to Godot? NVIDIA Optimus, responsible to switch between the two GPUs in laptops, has a history of being wonky in GNU/Linux.

**Comment by Calinou** [comment]
I don't think this can be solved on our side on Linux, as @YeldhamDev pointed out (unless you disable the IGP entirely in `nvidia-settings`).

**Comment by PtrMan** [comment]
I was running the nouveau (OSS) drivers, it caused to use the IGP in other games too.
