### ISSUE TITLE
Areas do not overlap with CSGs.

### ISSUE THREAD

**Issue by breezystatic77** [godotengine/godot#28432]
**Godot version:**
3.1

**OS/device including version:**
Windows 10, 10.0.17134

**Issue description:**

Areas do not register overlapping with CSGs that have Collision enabled.

**Steps to reproduce:**
Intersect an Area's CollisionShape with a StaticBody. Note that it correctly registers the Static Body as overlapping.

Now do the same thing, but use a CSG with collision enabled instead of a StaticBody. Note that the Area does NOT recognize the CSG as overlapping at all.

This minimal preproduction project has 2 Areas, one overlapping with a StaticBody, and one overlapping with a CSG. Only the one overlapping the StaticBody fires any overlap events, or recognizes that they are overlapping in `get_overlapping_bodies()`.

**Minimal reproduction project:**

[CSG Area Bug.zip](https://github.com/godotengine/godot/files/3119005/CSG.Area.Bug.zip)

**Comment by BraindeadBZH** [comment]
Probably related, signals, like body_entered, are also not triggered between a CSG and an Area.

**Comment by TheDuriel** [comment]
Does #32031 solve this?

**Comment by tom-jk** [comment]
Running the minimum reproduction project in 3.2.2.stable, I get as output:

```
Body Entered event for AreaTest_CSG
Body Shape Entered event for AreaTest_CSG
Body Entered event for AreaTest_StaticBody
Body Shape Entered event for AreaTest_StaticBody
CSG testing Area is overlapping something.
StaticBody testing Area is overlapping something.
CSG testing Area is overlapping something.
StaticBody testing Area is overlapping something.
etc...
```
Looks fixed to me.
