### ISSUE TITLE
OS.set_clipboard(value) not including line breaks - windows 10

### ISSUE THREAD

**Issue by kikutaknight** [godotengine/godot#28439]
**Godot version:**

3.1

**OS/device including version:**

Windows 10 Enterprise
Version 1803
Dell 7440 AIO

**Issue description:**

Using OS.set_clipboard(value) on a button.
The copied string does not include line breaks when pasted into Notepad.

**Steps to reproduce:**
Just use the command in a project:
OS.set_clipboard("this\nis\na\nmultiline\nstring\n\nthank you.")

**Minimal reproduction project:**

This project includes a text edit box and a button to copy.
[SetClipboard.zip](https://github.com/godotengine/godot/files/3120124/SetClipboard.zip)

**Comment by guilhermefelipecgs** [comment]
I couldn't reproduce the issue, but I'm only tested on Linux with gedit and vscode.

I gues this could be an issue with EOL on windows.

**Comment by Calinou** [comment]
@kikutaknight Does it work if the string contains CRLF line endings?

```gdscript
OS.set_clipboard("this\r\nis\r\na\r\nmultiline\r\nstring\r\n\r\nthank you.")
```

**Comment by kikutaknight** [comment]
> @kikutaknight Does it work if the string contains CRLF line endings?
> 
> ```gdscript
> OS.set_clipboard("this\r\nis\r\na\r\nmultiline\r\nstring\r\n\r\nthank you.")
> ```
> 
> If so, I guess `OS.set_clipboard()` should convert `\n` to `\r\n` on Windows (this would also solve the issue when using multi-line strings).

That works!
But yes, the OS.set_clipboard() should be fixed. As my use case is copying text that was inputted via a TextEdit node and won't include the \r\n
