### ISSUE TITLE
Documentation for Custom resource format loaders is wrong.

### ISSUE THREAD

**Issue by Darkheron** [godotengine/godot#28449]
While writing a custom resource loader and following the directions here:
https://docs.godotengine.org/en/3.1/development/cpp/custom_resource_format_loaders.html
I have found that this documentation is very wrong and will certainly result in sigfaults/frustration :)

In particular, the documentation regarding the registration and unregistration is flawed.
New loaders/savers need to be registered as such:

```
static Ref<MyLoaderText> my_loader_text; 
void register_my_types()
{
    my_loader_text.instance();
    ResourceLoader::add_resource_format_loader(m_loader_text);
}
```

and unregistered as such:

```
void unregister_my_types()
{
    ResourceLoader::remove_resource_format_loader(my_loader_text);
    my_loader_text.unref();
}
```

But also, the definition of the loader class itself is missing the GDCLASS macro... IE: 
`GDCLASS(MyLoaderText, ResourceFormatLoader)`

There may be other errors, but these are what I have found thusfar.

**Comment by YeldhamDev** [comment]
This should have been reported at the [godot-docs](https://github.com/godotengine/godot-docs) repo.

[Moved the report there](https://github.com/godotengine/godot-docs/issues/2411).
