### ISSUE TITLE
Empty spaces highlighting in editor

### ISSUE THREAD

**Issue by iwek7** [godotengine/godot#28446]
Hello,

using Godot editor I noticed weird behavior while selecting space or tab. There is the feature that highlights every part of text identical to current selection but it also works for tabs and spaces resulting in weird highlights like this (notice top-down 'strips' of selected spaces):

![image](https://user-images.githubusercontent.com/9964886/56806799-3c89ed80-682d-11e9-8e11-4ab4f8f4ffca.png)

When selecting more than one space suggested blocks are bigger:
![image](https://user-images.githubusercontent.com/9964886/56806902-925e9580-682d-11e9-9ab6-c35a6c6ece8a.png)

It works the same way for tabs.

I do not think that this is intended behavior. Most modern IDEs have similar highlighting feature however, when selection consists only of tabs/spaces then this feature should not kick in and no highlights should happen - for instance this is the way QT Creator handles this.

Of course we want to keep feature where selecting something that isn't just white signs will result in highlighting matching parts of text.

If you think this is good idea I can try to produce PR for this.

**Comment by Calinou** [comment]
Sounds good to me, you can submit a PR for this :smiley:
