### ISSUE TITLE
GLES2, Cast Shadow=Off breaks receiving shadow, HTML5

### ISSUE THREAD

**Issue by wombatstampede** [godotengine/godot#28444]
**Godot version:**
3.1 and 3.1.1RC1, GLES2

**OS/device including version:**
HTML5 export, (on some Android devices as well)
(Tested with Firefox)

**Issue description:**
If a MeshInstance is set "Cast Shadow=Off" (Geometry Instance) it only reives completely messed up Shadows.

(Green floor is split in half, left one has Cast Shadow = On, right one has CastShadow = Off)
![Imgur](https://i.imgur.com/Fcql0is.gif)
(The odd moving of the yellow bar is due to some strange effect in the 6dof y-motor, not topic of this issue.)

**Steps to reproduce:**
Set up a directional light. Put a Meshinstance with Cast Shadow=Off and another MeshInstance (naturally with CastShadow = on) to cast shadow on the first one. Export to HTML5.

**Minimal reproduction project:**
[shadow_error.zip](https://github.com/godotengine/godot/files/3120513/shadow_error.zip)

**Comment by Toshiwoz** [comment]
Got a similar issue, GLES3 too (Godot 3.1.1)

![image](https://user-images.githubusercontent.com/21297356/57893117-5359a980-7807-11e9-9f70-7d87d1d50c7e.png)
as seen from atop
![image](https://user-images.githubusercontent.com/21297356/57893129-59e82100-7807-11e9-9ab9-ae84818094f5.png)
same scene, lower angle.

Another example project to work with.
[ShadowOccluded.zip](https://github.com/godotengine/godot/files/3189330/ShadowOccluded.zip)

**Comment by Toshiwoz** [comment]
If you enable cast shadows on the large mesh you'll see why I want it disabled, apart from the fact that without performs much faster.
If anyone can suggest a workaround in the meantime it's very welcome.

**Comment by Toshiwoz** [comment]
![issue_with_shadows_cast_off](https://user-images.githubusercontent.com/21297356/58962109-192d5900-8770-11e9-9d92-c21e6c8cae06.gif)
Here another example that may help better understand the issue.
Looks like if there's no object casting shadow behind the last one then the shadow is cut off by some invisible bounding box.

**Comment by clayjohn** [comment]
@Toshiwoz The issue you are posting about is unrelated to the original post. In your test scene turning ShadowDepthRange to stable instead of optimized fixes your issue. 

The above issue is related to turning "Cast Shadows" on and off in a GeometryInstance.

**Comment by Toshiwoz** [comment]
![image](https://user-images.githubusercontent.com/21297356/59000488-5cb7af80-87d0-11e9-879c-f459ee00c9a7.png)
Then, how do you explain the fact that when I turn on cast shadow it works? (shadow is pixelated because I'm using very large mesh)

**Comment by clayjohn** [comment]
Ah, I didn't see you mention it before. It must be related then.

**Comment by jesperkondrup** [comment]
We might have a smiliar issue: Using GLES2, tested in 3.1.1 stable and 3.2 alpha 3. This issue is present on both Linux and Windows in Chrome, Safari and Edge.

![LightingIssue](https://user-images.githubusercontent.com/24936603/67551588-977f9d00-f709-11e9-9415-96a338943d32.jpg)

Project files:
[LightingShadowIssue.zip](https://github.com/godotengine/godot/files/3770859/LightingShadowIssue.zip)
