### ISSUE TITLE
Invalid path to rcedit will break windows exports and give a misleading popup message

### ISSUE THREAD

**Issue by exts** [godotengine/godot#28456]
**Godot version:**
3.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
If you move/remove rcedit and fail to update your editor settings to reflect the path change and attempt to export your project you will get the following message:

> Failed to export the project for platform 'Windows Desktop'.
> Export templates seem to be missing or invalid

![Godot-Stable_2019-04-26_07-53-14](https://user-images.githubusercontent.com/16387107/56837750-1c642980-6841-11e9-89ba-a04c12ca0041.png)

**Steps to reproduce:**
1. Create an empty project & hit the build button to generate the solution
2. Add a scene with any node, attach a blank script to it. Can just create a generated script from the editor
3. Add rcedit 64 to your project settings, delete the exe from where ever it's located (for testing)
4. Attempt to export a Windows Desktop project and you'll see the incorrect alert message.

**Minimal reproduction project:**
[EXPORTER.zip](https://github.com/godotengine/godot/files/3123080/EXPORTER.zip)

**Other information**
It does give you the correct error in the output editor and console window, but if you're on a different tab like "Mono" build tab you won't notice this error at all.

```
** Debug Process Stopped **
 platform/windows/export/export.cpp:58 - Could not find rcedit executable at Z:/Downloads/rcedit-x64.exe, aborting.
 editor/project_export.cpp:981 - Failed to export the project for platform 'Windows Desktop'.
```

**Comment by neikeq** [comment]
Is this an issue with the mono module? Seems unrelated.

**Comment by guilhermefelipecgs** [comment]
Isn't related, I was trying to find some topic about export and I ended up clicking on the wrong topic.
