### ISSUE TITLE
bug get_rotation on Vehiclebody

### ISSUE THREAD

**Issue by alexolin** [godotengine/godot#2845]
get_rotation on VehicleBody return value only for 0 to Pi/4 (0 to 90 in deg) or for 0 to -Pi/4 (0 to -90 in deg) 
![rect2985](https://cloud.githubusercontent.com/assets/15943158/11301513/cc3a4292-8fa8-11e5-9475-9733e8bd4517.png)

**Comment by karolgotowala** [comment]
bump

**Comment by Elinvention** [comment]
Please fix this issue

**Comment by SilverLuke** [comment]
Please fix this issue

**Comment by akien-mga** [comment]
Alright, we got it, but just bumping issues like that won't fix them magically.

**Comment by akien-mga** [comment]
Also giving more information on the actual issue, steps to reproduce and maybe a test project that exhibits it would be better than just bumping. The initial report is not precise enough as it only says that the function works in a range, and "doesn't work" in another range; what does "doesn't work" mean? Does it return 0, and error, or a wrong value?

I know developers can test that by themselves, but to get a bug fixed, it's much better when the bug reporters take some time to simplify the work for developers. There are after more than 1000 issues opened for a handful of voluntary contributors.

**Comment by Elinvention** [comment]
Take the Truck Town demo, add `print("Rotation: %.1f" % rad2deg(get_rotation().y))` to `vehicle.gd`.

You will see that the returned rotation of the car will vary from -90 to 90 degrees, but 180 degrees are not enough for a full rotation, as illustrated by the image above (except that 90° are PI/2 and not PI/4 @alexolin).

e.g. if get_rotation returns 0°, is the car pointing east or west?

**Comment by akien-mga** [comment]
Thanks for the details, I tested and the fact that it concerns the Y component is pretty relevant. I believe this bug has the same cause as #1479.

**Comment by reduz** [comment]
this is kind of unavoidable with euler rotations, and I recommend not using them (there is always better ways to do the same with vector math).

That said, we should improve how euler rotations are presented to the user, and this has been noted down in the 3.0 compatibility breakage list.

**Comment by reduz** [comment]
closed, as duplicate for #1479
