### ISSUE TITLE
Add debug printing function to GDScript

### ISSUE THREAD

**Issue by codemessiah** [godotengine/godot#28458]
(Feature request)

**Issue description:**
During debugging, people create lots of `print`s doing simple debugging of values. Projects' outputs may quickly become messy if people forget to comment out or delete their `print` methods before pushing to source control. Furthermore, `printerr` is better suited for printing debug, yet most probably won't know to use it.

We should have a feature (like that recently added to Rust with [the `dbg!` macro](https://doc.rust-lang.org/std/macro.dbg.html)), where one could perform an operation similar to:
```gd
var a = 2
var b = debug(a * 2) + 1
# prints: [file_name.gd:2] a * 2 = 4
assert(b == 5)
```

The biggest reasons to use `debug` over an ordinary `print` are:
1. Prints to standard error
2. Not included in release builds (like `assert`)
3. Shows where the print originates from
4. Clearer what is happening in the expression evaluation
5. Can be inserted directly into existing code (since it returns the value as well as prints it)

I would like to hear the thoughts of others on this topic. Thanks.

**Comment by Calinou** [comment]
> Shows where the print originates from

For reference, the methods `push_error()` and `push_warning()` can already do this :slightly_smiling_face:

However, I think a method dedicated to debugging makes sense, especially if it returns the original computed value.

**Comment by asmoaesl** [comment]
And it looks like `print_debug` is already a thing. Not sure if it stays in release builds, but assuming it does, that means the only differences between that existing function and the one I'm proposing are numbers 4 and 5.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/538 and https://github.com/godotengine/godot-proposals/issues/837, as feature proposals are now tracked on the Godot proposals repository.
