### ISSUE TITLE
Cross-compiling export templates for Windows-x86 from x-11 fails

### ISSUE THREAD

**Issue by N8n5h** [godotengine/godot#28468]
**Godot version:**
Commit: 2931b4d

**OS/device including version:**
OS: Ubuntu 18.04.2

**Issue description:**
Executing: scons platform=windows tools=no target=release bits=32, produces this [log](https://github.com/godotengine/godot/files/3123998/godot-log.txt)
and terminates without finishing.

**Comment by LinuxUserGD** [comment]
My output on Antergos (Arch Linux) is different:
```Swift
[ 52%] Compiling ==> scene/resources/audio_stream_sample.cpp
scene/audio/audio_stream_player.cpp: In member function 'void AudioStreamPlayer::_mix_audio()':
scene/audio/audio_stream_player.cpp:95:23: error: 'stream_fade' was not declared in this scope
    (stream_paused && !stream_fade)) {
                       ^~~~~~~~~~~
scene/audio/audio_stream_player.cpp:95:23: note: suggested alternative: 'stream_paused'
    (stream_paused && !stream_fade)) {
                       ^~~~~~~~~~~
                       stream_paused
[ 52%] Compiling ==> scene/resources/bit_map.cpp
scons: *** [scene/audio/audio_stream_player.windows.opt.32.o] Error 1
scons: building terminated because of errors.

```

**Comment by LinuxUserGD** [comment]
But I get also errors when I try to compile for X11 so this seems to be something different.

**Comment by Calinou** [comment]
Try following the adviced outlined in [Comiling for Windows](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#troubleshooting).
