### ISSUE TITLE
2D Physics excessive collision pairs, regardless of layer/mask.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#28460]
**Godot version:**

9ef4699

**OS/device including version:**

Win10 64-bit

**Issue description:**

When profiling my characters, I found that regardless of the hit area masks I'm using, the project was generating a few thousand collision pairs.  I haven't traced this deep enough to know if these pairs are actually considered, but there seems to be at small dip in FPS with just one character with a lot of conditional hit areas when they overlap level geometry.

Hard to say yet without a bigger test, but even if they don't, doesn't seem like a good thing to create pairs when there will never be collision.  It clogs up the monitor, and would be hard to distinguish between an actual excessive pairing problem.

In the simplest form, an isolated test with two bodies on different masks and layers entirely.  The monitor reports a collision pair.

![image](https://user-images.githubusercontent.com/13004169/56846549-4cf7a200-68d9-11e9-9ec9-8f8a5c082bf6.png)

![image](https://user-images.githubusercontent.com/13004169/56846547-436e3a00-68d9-11e9-907b-762a97c45356.png)

![image](https://user-images.githubusercontent.com/13004169/56846559-6dbff780-68d9-11e9-9eb8-2eb35213fbf5.png)

Then with no layers or masks, and 30 Area2Ds, there are 435 pairs.

![image](https://user-images.githubusercontent.com/13004169/56846596-cdb69e00-68d9-11e9-92fc-9836b5e903d8.png)

![image](https://user-images.githubusercontent.com/13004169/56846605-ec1c9980-68d9-11e9-805a-f1ba5d311457.png)

**Steps to reproduce:**

Overlap bodies or areas that shouldn't mask to one another, and observe collision pairs in the monitor.

**Minimal reproduction project:**

[Collision Pairs.zip](https://github.com/godotengine/godot/files/3123637/Collision.Pairs.zip)

**Comment by PetePete1984** [comment]
Try it with an area above a (big) tilemap with colliders for even more collision pairs!

Also, could be related to https://github.com/godotengine/godot/issues/7644

**Comment by groud** [comment]
This might be expected though, since I believe the bitmask might be checked after all collisions are computed.

**Comment by Zireael07** [comment]
@groud: Even if that's the case, I believe the monitor should only show us the number of collisions that actually matter?

**Comment by groud** [comment]
Well no, not really. Because the computational cost is still there.
But another entry showing only "valid" collisions might make sense.

**Comment by avencherus** [comment]
@groud Do you mean after the pairs are calculated or after the collision tests are done?  I can't imagine why the intersections would be done on things that are flagged to never collide, but maybe there is some reason for accumulating the pairs before throwing them out?

**Comment by avencherus** [comment]
@PetePete1984 Has that had any performance impact for you?

**Comment by groud** [comment]
For now it seems like the pairs are computed before the bitmask evaluation. I don't know if it is the best solution, but if it is, it is normal that the pairs are being counted without considering the bitmask.

**Comment by avencherus** [comment]
@groud Then I like your suggestion of having another field for the contacts.

**Comment by PetePete1984** [comment]
@avencherus I don't believe so, but it was only a quick test in a pretty much empty scene after poking around in the profiler with Dean (from discord), created because his 3000x3000 tilemaps were getting slowdowns (for most likely other reasons at the time) and we noticed thousands of collision pairs.
