### ISSUE TITLE
[AnimationPlayer] Cannot change the easing of multiple keyframes at a time

### ISSUE THREAD

**Issue by Nobelix** [godotengine/godot#28477]
**Godot version:**
3.1.1

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
Basically if you select multiple key-frames at a time in the animation player, you cannot change their easing mode, thus making it a pain to batch change easing of some keyframes.
![image](https://user-images.githubusercontent.com/30960698/56854651-7563b880-693a-11e9-8d2c-a0fae8a37bc0.png)

**Steps to reproduce:**

1. Make an animation
2. Select some key-frames
3. Try to change their easing in the inspector (you wont be able because there will be nothing like on the image I posted)

**Comment by akien-mga** [comment]
Fixed by #30778.
