### ISSUE TITLE
Filename or extension too long error compiling Android

### ISSUE THREAD

**Issue by punyi23** [godotengine/godot#28474]
**Godot and Python version:**
Using Godot 3.1 stable and Python 3.7.3 (Anaconda)

**OS/device including version:**
Windows 10 Pro N version 1803

**Issue description:**
Hi everyone, I'm trying to implement GodotAdmob module for Android but when I'm compiling for Android using SCons I always get this error:

```
[Initial build] [91mLinking Static Library [95m==> [93mmodules\libmodules.android.opt.armv7.neon.a[0m
scons: *** [modules\libmodules.android.opt.armv7.neon.a] El nombre del archivo o la extensión es demasiado largo
scons: building terminated because of errors.
```

I've been finding more issues like this and indeed I find it out some but all of them closed and resolved with a commit a year or few years ago. I also have enabled LongCmdLinesOnWin32 but the compilation get stuck always on same position. Also I move all the folders involved to C:// directory but worthless.

**Steps to reproduce:**
Go to command prompt on Windows, navigate to your Godot 3.1 stable folder and enter this instruction:

`scons platform=android target=release android_arch=armv7
`

**Comment by mahfuz10** [comment]
It can be related to this issue #3443.
And @Calinou suggested to try this: [260-character limit on file path lengths](https://stackoverflow.com/questions/27680647/does-max-path-issue-still-exists-in-windows-10)

**Comment by punyi23** [comment]
> It can be related to this issue #3443.
> And @Calinou suggested to try this: [260-character limit on file path lengths](https://stackoverflow.com/questions/27680647/does-max-path-issue-still-exists-in-windows-10)

Thank you for your reply mahFuz10, but as I said, even enabling LongCmdLinesOnWin32 (260-character limit on file path lengths) the error was the same.

Any idea how to solve it on Windows?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by akien-mga** [comment]
No answer, so closing.

Please comment if you can still reproduce the issue and we can reopen it. If better suited, you can also open a new issue referencing this one.
