### ISSUE TITLE
Allow All Basic Arithmetic Operations for Vector2i with Integers

### ISSUE THREAD

**Issue by Andrettin** [godotengine/godot#28486]
During my work to port Wyrmsun to Godot, one of my objectives is to replace the "Vec2i" class in the game's C++ code with Godot's "Vector2i", since they both represent the exact same concept (a vector with x and y integer coordinates), so that it is not very sensible to keep a special class for it in Wyrmsun.

Wyrmsun's Vec2i class possesses operators for all four basic arithmetic operations, using an integer as the right-hand-side value, which is quite useful for certain use cases. Godot's Vector2i class, by contrast, supports only multiplication and division with an integer as the right-hand-side value, but not addition and substraction.

Is there interest in adding those features for Godot's Vector2i class? If so, I would gladly work on a corresponding pull request.

**Comment by aaronfranke** [comment]
This issue depends on Vector2i being exposed first, so it depends on #22205. It could also be placed on the 4.0 milestone, but if we have to push it back to a later release that's fine too.

**Comment by bojidar-bg** [comment]
Note that if this is supported, adding / subtracting with a number on the left hand side should likely work as well. Furthermore, the same behavior should be implemented for Vector3i, Vector2 and Vector3.

---

IMHO, it would be better if an explicit `Vector2i(int)` constructor exists, similar to how this is done in shader languages (`x + vec2(0.4)`). This way is a bit more verbose indeed, but is closer to the mathematical definition of a vector and can prevent subtle issues (e.g. `velocity += GRAVITY` where `GRAVITY` is a real number)

**Comment by akien-mga** [comment]
Vector2i as exposed in 4.0 should support all basic arithmetic operations now.
