### ISSUE TITLE
When exporting to iOS, scenes preloaded in a singleton are ignored

### ISSUE THREAD

**Issue by aleksfadini** [godotengine/godot#28484]
**Godot version:**
3.1.1

**OS/device including version:**
iPhone Max, running iOS 12.2

**Issue description:**
Scenes preloaded in a singleton are not being found once the project is exported for iOS.

**Steps to reproduce:**

- Create a singleton global.gd and enable it in Autload
- In the script global.gd, preload a scene (ex: var PreloadedScene = preload("res://scene.tscn")
- Anywhere else, call said var (Ex: in main.gd: var MyScene = global.PreloadedScene)
- verify that scene.tscn exists and that this works in the editor
- export to iOS
- Play on device

**What it should do**
Load the scene correctly, as it does in the editor.

**What it does instead**
The scene won't load. Xcode error:
ERROR: No loader found for resource: res://scene.tscn

**Minimal reproduction project:**
I can do it if needed

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by aleksfadini** [comment]
I cannot and would be ok it closing it. Thank you!
