### ISSUE TITLE
C# Lists lock at random if Rasterizer is set to Multi-Thread

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#28483]
**Godot version:**

3.1.1

**OS/device including version:**

Issue appears on: Windows 10, and Latest Mac, with I7 Processors

Does NOT appear on: Windows 7 Phenom ii x4

**Issue description:**

List<T> will "randomly" (we don't know why. it just does. one some machines.) become locked if the rasterizers thread model is set to multi-thread.

Physics threading appears to potentially have the same issue, but much less pronounced.

**Steps to reproduce:**
Set the rasterizers thread model to multi-safe in your project settings.

Create a list with a thousand or so entries.

Try and remove ten or so entries every frame. Using Remove or RemoveAt.

Observe that on _some_ machines the total object count will not decrease.

**Minimal reproduction project:**

**Comment by jasonswearingen** [comment]
I would venture a guess that Lists are not a problem, but rather the thread is deadlocked, so the script code isn't executed.

**Comment by TheDuriel** [comment]
No longer able to test this. Will keep an eye out for it though. Given that threading of physics and rendering is likely to change this might not even be relevant going forwards.
