### ISSUE TITLE
ConvexPolygonShape2D::set_point_cloud is empty

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2848]
As seen in the current master branch and noted by @Ovnuniarchos in 1155ac8 (btw please open a bug report when you see something like that, it's a bug):
```
void ConvexPolygonShape2D::set_point_cloud(const Vector<Vector2>& p_points) {



}

void ConvexPolygonShape2D::set_points(const Vector<Vector2>& p_points) {

	points=p_points;
	_update_shape();
}
```

https://github.com/godotengine/godot/blob/0b05739/scene/resources/convex_polygon_shape_2d.cpp#L40-L44

**Comment by reduz** [comment]
need to write a convex hull function for that :P
