### ISSUE TITLE
Godot Not Rendering More Than 8 Spatial Light Instances

### ISSUE THREAD

**Issue by NoodleSushi** [godotengine/godot#28485]
Godot Engine v3.1.stable.official
Windows 10
GLES3

Spawned 9 spatial objects with SpotLight, One doesn't emit light while the rest does
when one of the spatial objects emitting light queue_free(), one that doesn't then emits light
![2019-04-28_18-27-39](https://user-images.githubusercontent.com/34954180/56862999-64bb4d00-69e3-11e9-8727-b50bd71188a5.gif)

**Comment by Zireael07** [comment]
That's a known OpenGL limitation, and already reported at least once.

**Comment by NoodleSushi** [comment]
are there at least any workarounds for this?

**Comment by JFonS** [comment]
It's not an OpenGL limitation per se, but the way Godot renders lights. Note that the limit is on the number of lights per  object, so splitting your floor into multiple nodes would circumvent that.

**Comment by Calinou** [comment]
For the particular use case displayed on the GIF, you could also use a Sprite3D (or PlaneMesh) with additive blending. It won't look the same, but it may look good enough and will be much faster.

**Comment by Dogpot** [comment]
Forward rendering limitation, as mentioned above, 8 lights per object. Use sprites or particles with additive blending to simulate lots of small lights like that.

**Comment by NoodleSushi** [comment]
@JFonS I've split the plane and it works! Thank you everyone for replying & giving me suggestions, now closing this issue.

**Comment by rcorre** [comment]
Given this is closed, should we assume it is infeasible to fix it?

Also:

> 8 lights per object

It actually appears to be 8 lights per mesh. Here I have 16 different `MeshInstance`s, all referencing the same mesh resource:

![1560507893](https://user-images.githubusercontent.com/2496231/59503085-7a8ab180-8e6d-11e9-9ed7-c97a5da9278e.png)

**Comment by rcorre** [comment]
Ah, I guess this is a dupe of https://github.com/godotengine/godot/issues/15651 and https://github.com/godotengine/godot/issues/25945. Based on those, the answer is either:

> Kicking to 3.2, won't be solved in 3.1

or

> This probably won't be solved until 4.0
