### ISSUE TITLE
I can Get_Track_Key_Time but can't set it

### ISSUE THREAD

**Issue by nathanjwtx** [godotengine/godot#28482]
Godot 3.1.1 on Win 10 in the key of C#

Just wondering why I can't set the track time? There's a method for getting it but not setting it. Is this by design or omission? Thanks :)

Note: there isn't a GDScript equivalent either so it's not language specific

**Comment by Jummit** [comment]
get_key_time doesn't jet exist in Animation.cpp, but here is the getter:
https://github.com/godotengine/godot/blob/master/scene/resources/animation.cpp#L1248
