### ISSUE TITLE
CenterContainer doesn't reposition its child if that child changes its minimum size

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#28489]
**Godot version:**
3.1

**OS/device including version:**
macOS

**Issue description:**
Run the attached project. The popup will change its minimum size after a second, but won't be repositioned by the CenterContainer.

**Minimal reproduction project:**
[centercontainer.zip](https://github.com/godotengine/godot/files/3125088/centercontainer.zip)

**Comment by mitchcurtis** [comment]
`popup_centered()` works great, assuming the child is a Popup.

**Comment by KoBeWi** [comment]
This seems to only apply to popups. Likely related to #34026. Is this intended behavior maybe?

**Comment by KoBeWi** [comment]
Popups are no longer Controls in 4.0, so this isn't valid anymore.
