### ISSUE TITLE
Default color is invisible in Visualscript (Alpha is 0)

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28490]
**Godot version:**
3.1.1

**Issue description:**
I used a node that required a Color, and was very confused why it wasn't working until I noticed that the alpha was set to 0.

**Steps to reproduce:**
Add a `Set Local Variable` node, set its type to Color, click on the color editor and see that alpha is 0.

**Comment by Calinou** [comment]
It should probably default to `Color(1, 1, 1, 1)` (opaque white) as that's what most properties default to.

**Comment by Jummit** [comment]
Seems like [this](https://github.com/godotengine/godot/blob/dd2cd06165670bb0d78bf4aa397935be15716e76/modules/visual_script/visual_script.cpp#L84-L106) is what causes the Color to be `0, 0, 0, 0`

**Comment by hbina** [comment]
Can you provide a more descriptive way to reproduce this? I think the required changes are these default constructor but I would like to test it first...

https://github.com/godotengine/godot/blob/ee5ba3e0974caba3e3589d2a53405ef7328dc1b1/core/color.h#L206-L211

**Comment by Jummit** [comment]
So apparently this only happens in function calls:
1. Set member (for example modulate) has color 1, 1, 1, 1
2. Color constant has color 0, 0, 0, 1
3. Function call (for example draw functions) have color 0, 0, 0, 0

**Comment by hbina** [comment]
I assume it should all be constructed to `1,1,1,1`?

**Comment by hbina** [comment]
So what's the state of this issue? What is the appropriate way to resolve it? I have submitted a PR a while ago with some breaking changes.

**Comment by Arunkumar1998BOM** [comment]
I am completely new to this project. I would like to know how we can add the Set Local Variable Node in the editor, as I would like to reproduce the issue first and then pitch in any thoughts

**Comment by KoBeWi** [comment]
Tested in d332412, the default color is now **opaque** black. The original issue was that 0 alpha caused confusion, so it can be considered resolved.
