### ISSUE TITLE
Line2D Curve for Width

### ISSUE THREAD

**Issue by MunWolf** [godotengine/godot#28496]
This feature request shouldn't be too hard to finish.
it is about adding variable width to the line based on a curve, an example of this would be the LineRenderer in unity
https://docs.unity3d.com/Manual/class-LineRenderer.html

We already have the curve texture we can use for this and it would help immensely in making trails and the like.

**Comment by Vultraz** [comment]
Definitely would be a nice thing to have :D Right now we're using a `draw_polyline` call over a `Curve2D`, but this would allow us to taper it.

![image](https://user-images.githubusercontent.com/3558659/56873654-a699d100-6a7f-11e9-885f-d8013ac8abf9.png)

**Comment by akien-mga** [comment]
Isn't it what `Line2D` does? It might just need a simple option to follow a `Curve2D` instead of a fixed array of points.

**Comment by Calinou** [comment]
@akien-mga What OP wants here is a way to adjust the width of the line over its course, which currently can't be done with Line2D or Path2D (to my knowledge).

**Comment by MunWolf** [comment]
Yes what I am looking for is functionality that allows us to draw something like this.
![image](https://user-images.githubusercontent.com/3696546/56899780-3b0a3080-6a8c-11e9-9b79-ded489928b43.png)

It is kinda possible to do by providing a texture, but it doesn't look very nice and doesn't support tiling unless you do it manually in the image editing software.

**Comment by CedNaru** [comment]
Here it comes

![Example](https://user-images.githubusercontent.com/31470327/57002311-be2ba380-6bbe-11e9-9e0a-0c7df7691c00.png)

Is that what you want ?
If it's okay I can create a pull request.

**Comment by Vultraz** [comment]
Is that only for Line2D? What about Curve2D?

**Comment by CedNaru** [comment]
I have only done Line2D.
Curve2D is used internally by Path2D.  Path2D is not a node you should use for rendering but for logic processing.

**Comment by Vultraz** [comment]
Sorry, meant Path2D. But regardless, I see no other way to get a bezier curve drawn on-screen than drawing a line over said a dynamically populated Path2D.

**Comment by CedNaru** [comment]
It would be too cumbersome to add a Path2D/Curve2D to Line2D. It might be better to directly extend Path2D with GdScript

**Comment by Vultraz** [comment]
Well, that's sorta [what we do](https://github.com/wesnoth/haldric/blob/master/source/interface/draw/UnitPathDisplay.gd), but how would I make it taper?

**Comment by MunWolf** [comment]
@CedNaru Exactly what I was looking for, if you could make a PR for it that would be great. Making a Path2D renderer would be a whole separate thing.

**Comment by CedNaru** [comment]
#28565

**Comment by akien-mga** [comment]
Fixed by #28565.
