### ISSUE TITLE
Bake() Method of GIProbe has no effect on runtime

### ISSUE THREAD

**Issue by PtrMan** [godotengine/godot#28508]
**Godot version:**
3.1 release

**OS/device including version:**
Current Windows 10

**Issue description:**
My goal was to experiment with the GI capability of the engine. The experiment was if it can bake not-moving objects (with not moving light sources) at runtime (not in the editor).

*Result:*

Baking from GDScript of a dynamic scene is currently not possible.

I expected that it would at least bake it at runtime.

**Steps to reproduce:**

* add GIProbe
* add light source (with GI contribution >0.0)
* add GDScript which spawns scene objects where the "Use In Baked" attribute is enabled and calls the .Bake() method of the GIProbe in the scene

**Comment by SRugina** [comment]
I've just run into this issue, quick fix is to set the mesh instance's owner to the node that contains the script calling bake() after calling add_child() on it, e.g.

```GDScript
extends Spatial

func _ready():
	generate_plane()
	generate_gi_probe()

func generate_gi_probe():
	var gi_probe := GIProbe.new()
	gi_probe.name = "gi_probe"
	gi_probe.set_extents(Vector3(400.0, 400.0, 400.0))
	add_child(gi_probe)
	gi_probe.bake()

func generate_plane():
	var plane_mesh := PlaneMesh.new()
	plane_mesh.size = Vector2(10, 10)
	
	var mesh_instance := MeshInstance.new()
	mesh_instance.name = "plane"
	mesh_instance.mesh = plane_mesh
	mesh_instance.use_in_baked_light = true
	add_child(mesh_instance)
	mesh_instance.owner = $"."
```
