### ISSUE TITLE
translation csv files don't support ANSI format on Windows

### ISSUE THREAD

**Issue by youreperfect** [godotengine/godot#28503]
**Godot version:**
3.1.1-stable-windows

**OS/device including version:**
Windows 10 and Excel 2013

**Issue description:**
When importing .csv files exported into csv format from Excel (and maybe generally?) are giving me "Unicode error: invalid skip" even if the file contains only Latin-1 characters. Opening the file in Notepad and changing the encoding from ANSI to UTF-8 seems to solve the problem.

**Comment by aaronfranke** [comment]
Is there a way to set Excel to export UTF-8? It sounds like it's Excel's fault for not exporting UTF-8.

**Comment by youreperfect** [comment]
There may be but if Godot is going to _only_ support UTF-8 then at the very least it should give an error like "File is not in UTF-8 encoding" rather than a crypic message
