### ISSUE TITLE
Idea: add virtual modifier for func defined in GDScript

### ISSUE THREAD

**Issue by silkentrance** [godotengine/godot#28500]
This is an idea that might be useful.

However, I do not know how well this will play with natively implemented components (Object, Nodes, ...) and C#.

However, for GDScript, I would like to be able to define a base class like so

```
extends Node

virtual func _do_something(arg1: String) -> void:
  pass
```

When creating a node inheriting from the above, the editor will then provide me with a template that includes the above virtual method, e.g.

```
extends "res://DoSomething.gd"

# you should implement this
func _do_something(arg1: String) -> void:
  push_error("must implement _do_something")
```

where it basically replicates the original declaration lest the virtual modifier and then emits some code that will result in an error unless the user implements that method.

And if the user just deletes the templated method, the virtual method from the base class will be used during execution, just like what we have now, without the virtual modifier.

The rationale behind this is that I am currently prototyping some base classes from which I will derive concrete behaviours for an e.g. player character from. ATM, I always have to copy and paste the stuff I need from the base class, which is tedious at best.

Unless, of course, there is already a similar mechanism for this of which I am currently unaware of.

**Comment by Jummit** [comment]
I don't think that this is useful enough to get implemented. But that's just my opinion.

**Comment by MunWolf** [comment]
In my honest opinion I do not feel this is a useful feature and it is misleading as you can still override non virtual functions in the inherited class.
I would be all for something similar to an abstract keyword that prevents a class from being instantiated/assigned to a script and requires you to implement it or declare it abstract again in a derived class.

I don't think that feature would be important enough compared to something like Vulkan support or better Navigation for example.

**Comment by silkentrance** [comment]
@MunWolf good point. let's make this a dialog then instead and we can simply omit the language extension thing.

In the dialog you can choose which methods you want to override from the bases, ordered/grouped by the respective base classes.

And from there you can just select the ones that you want to override. Existing overrides will be disabled (selected) or just not shown.

**Comment by silkentrance** [comment]
On second thought, I think that you are both correct. Closing as this can be achieved differently and without any changes to the language.
