### ISSUE TITLE
Toggle visibility and modulate property not working when TileMap is inside YSort

### ISSUE THREAD

**Issue by NedAlex94** [godotengine/godot#28501]
**Godot version:**
3.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
Toggle visibility and modulate property not working when TileMap is inside a YSort node.

**Steps to reproduce:**

My game is structures like this:

![Capture](https://user-images.githubusercontent.com/17100058/56870017-0e610500-6a09-11e9-86f5-757859a2eb7a.PNG)
YSort

 >Tilemap1
 >Tilemap2
...

When I try to toggle the visibility of one or more TileMaps, it simply doesn't work. If i toggle the visibility of the YSort node, however, (or any other type of node inside it) it works without issues.

Same thing for the modulate property. If i want to change the opacity or colour of a TileMap inside the YSort, it does not work. 

If i move the TIleMap outside the YSort, everything works as it should.

**Comment by YeldhamDev** [comment]
CC @bojidar-bg

**Comment by bojidar-bg** [comment]
Visibility was fixed in #27843, modulate wasn't though.

**Comment by NedAlex94** [comment]
> 
> 
> Visibility was fixed in #27843, modulate wasn't though.

You guys are amazing, thank you for the amount of dedication you put in this engine!

**Comment by tabletopcrow** [comment]
I'm now having the exact same issue with the visibility. Did something happen to screw it up again? Any help on fixing it?
