### ISSUE TITLE
VectorInterp/ScalerInterp VSE nodes missing from the new UI (3.2 dev).

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#28515]
**Godot version:**
Godot 3.2 Dev.Calinou at commit https://github.com/godotengine/godot/commit/a0180fa86ec54ac4f7e1b7c8f154364f0525b76a

**OS/device including version:**
Win10 64 bit, an Nvidia 1060 GPU, AMD Ryzen 2700X CPU.

**Issue description:**
The enhanced UI does not appear to list the VectorInterp and the ScalerInterp nodes. The nodes themselves in other shaders remain in place, so it's just a case of them not being accessible.

**Steps to reproduce:**
Create a visual shader and try to find the nodes in the **Create Shader Node**  menu, the search term "interp" does not return anything and the nodes simply cannot be found.

**Comment by Chaosus** [comment]
They are use Mix term now

**Comment by Ace-Dragon** [comment]
I could've sworn I tried typing 'mix' before and not find anything, but I did find them now.

However, the name on the nodes themselves have yet to be updated (so for consistency, that needs to be done).

**Comment by Chaosus** [comment]
Well, I could rename the title, but if I renames it completly this will be serious break of the compatibility

**Comment by aaronfranke** [comment]
What else needs to be done after #28516?

**Comment by Chaosus** [comment]
I've leave it opened in case of renaming the internal node name itself for 4.0.. However in the UI perspective its already been renamed, so you right and this should be closed.
