### ISSUE TITLE
Define constants for the target platform

### ISSUE THREAD

**Issue by woubuc** [godotengine/godot#28517]
In C# attributes (e.g. `[DllImport]`), you can only use `const` values, so it's not possible to use the `OS` singleton to check which platform you're using. So it would be very useful if a platform constant was available in the builds, so we can do something like `#if WINDOWS` with preprocessor directives.

**Comment by exts** [comment]
If this does get added wouldn't it be useful to be precise on OS and bit info eg.:

- OS_WINDOWS (either 32/64)
- OS_WINDOWS_32
- OS_WINDOWS_64
- OS_LINUX
- OS_LINUX_32
- OS_LINUX_64
- OS_MAC
- OS_MAC_32
- OS_MAC_64
- OS_ANDROID
- OS_IOS

**Comment by Calinou** [comment]
@exts 32-bit macOS isn't supported anymore, so `OS_OSX` would be enough :slightly_smiling_face: (the platform is called `OSX` in the engine code).

**Comment by aaronfranke** [comment]
This should also apply to `REAL_T_IS_DOUBLE`.

**Comment by ShyRed** [comment]
Maybe we could use the existing [OS names](https://docs.godotengine.org/en/latest/classes/class_os.html#class-os-method-get-name)? This way we would not have to maintain separate lists of OS names and new OS targets get added in automatically.

Something like `"OS_" + uppercase(OS::get_singleton()->get_name()) + "_" + Bits` maybe?

The OS singleton does not provide the number for Bits, it seems.  Might want to add that in, too...

**Comment by ShyRed** [comment]
Not to forget a general "GODOT" define like suggested in #27227
