### ISSUE TITLE
Better allign for Public Methods list in API doc

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#2851]
Usually when we look for methods we tend to search them by name not their return datatype. I suggest change type of text alignment as on mock-up:
![doc_text_align](https://cloud.githubusercontent.com/assets/6152134/11312499/bfe9bf4e-8fd6-11e5-8c8f-4ffc6fba5b3c.jpg)

**Comment by reduz** [comment]
well, pretty nice idea, should add support to richtextlabel to do this..

**Comment by reduz** [comment]
guess it needs column support...

**Comment by vnen** [comment]
I like this idea. Also: the methods should be sorted in alphabetical order.

**Comment by n-pigeon** [comment]
Alphabetical order would be probably rather tricky with "set_, get_, is_, is_set_as" and so on which should be next to each other if they are in the same context like:
set_as_toplevel()
is_set_as_toplevel()

also some don't share name just context like:
hide()
show()

**Comment by reduz** [comment]
ah this is worse, it's not columned text, it's grid support... thinking
about implementing this gives me nightmares :|
guess will have to do it eventually..

**Comment by reduz** [comment]
Done! It literally gave me nightmares after the first day working on int :D

**Comment by akien-mga** [comment]
Awesome, thanks! :D

**Comment by n-pigeon** [comment]
Beautiful! Thx!
