### ISSUE TITLE
Make VisualScript search remember the last search when reopened

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#28523]
Unlike the documentation search, that remember the last active search when reopened, the VisualScript search reopens completely blank.

**Comment by DavidCambre** [comment]
Did a quick test in 3.3.0.

When using Control+F the VisualScriptPropertySelector remembers the last search just fine.
When dragging out the sequence port the same VisualScriptPropertySelector seams to resets the input value to "".
When using Control+F again it opens the the same VisualScriptPropertySelector and your last search is gone.

This is hou i would expect it to work. 
It might be a upgrade that Control+F has it own  VisualScriptPropertySelector or memory.

**Comment by KoBeWi** [comment]
I think the intention is that when you create a node, your search is no longer needed, because you already used it.
As for dragging the port, it doesn't have separate memory. This action just clears the search box. You can check by searching something after drag and then Ctrl+Fing.

**Comment by YeldhamDev** [comment]
Closing, as VisualScript is no more.
