### ISSUE TITLE
Camera preview button overlaps with type of camera button with Main Font Size set to 20

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28529]
**Godot version:**
3.1.1

**Issue description:**
Try to set Main Font Size to 20(or more) and choose then Camera node
![Zrzut ekranu z 2019-04-30 13-15-42](https://user-images.githubusercontent.com/41945903/56958497-bd592a00-6b4a-11e9-8e64-e39393ae0103.png)

**Comment by Jummit** [comment]
Can't replicate in 7018de8.
![image](https://user-images.githubusercontent.com/28286961/56993009-9d058b80-6b9b-11e9-8672-20969b88f46e.png)

**Comment by qarmin** [comment]
Oh, right.
This is caused not by editor scale but Main Font Size.
I changed issue description.

**Comment by Jummit** [comment]
Ah, that's why your font is so large! I was wondering why it was that large on the minimum display scale.

**Comment by hbina** [comment]
Am I correct to think that the fix lie in this exact line?

https://github.com/godotengine/godot/blob/d8617f237acbed21ca4b1a9e7df2d28b32e511b1/editor/plugins/spatial_editor_plugin.cpp#L3569

So the only other thing I am not sure is how to obtain the current font size, is there a singleton object somewhere?

Aside from position, the size of the box should also be readjusted automatically to fit the text?

To be fair, setting the font size to 20 will break everything...so while this might fix this particular issue, I am not entirely sure what to do with the rest...

![godot_setting_font_to_20_breaks](https://user-images.githubusercontent.com/6733660/57192333-47174780-6efd-11e9-8388-36b8bd38c1ea.png)

**Comment by bojidar-bg** [comment]
You can take the the font size from:
```cpp
EditorSettings::get_singleton()->get("interface/editor/main_font_size")
```
Alternatively, there is a shorthand macro as well:
```cpp
EDITOR_GET("interface/editor/main_font_size")
```
