### ISSUE TITLE
Resource save, doesn't save changed properties of child of packed node

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28535]
**Godot version:**
3.2.dev.custom_build. 58531a9

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When I try to save a node with changed some properties of its children to file with Resource.save, then Godot create tscn file with nodes with default settings instead save modified properties(like modulate).

![Zrzut ekranu z 2019-04-30 18-09-48](https://user-images.githubusercontent.com/41945903/56976920-4e90c680-6b74-11e9-90f4-b2eaef92b24f.png)

This is a code which save this scene to file:
```
func _ready() -> void:
	for i in 20:
		for j in 14:
			var f  = load("res://Node2D.tscn").instance()
			f.position = Vector2(i*60,j*60)
			f.name = "N" + str(i*14 + j)
			f.get_node("icon").modulate.r8 = (i+j+1)%127+127
			f.get_node("icon").modulate.g8 = (i*j*5)%127+127
			f.get_node("icon").modulate.b8 = (17 * i)%127+127
			add_child(f)
			f.set_owner(self)
			
	var packed_scene = PackedScene.new()
	packed_scene.pack(self)
	if(ResourceSaver.save("res://Save.tscn", packed_scene)):
		printerr("Nie powiodła się próba zapisu mapy")
```
**Steps to reproduce:**
1. Open project from below
2. Open and play scene "Create.tscn"
3. Open scene "Save.tscn" and see that looks different than in game

**Minimal reproduction project:**
[AA.zip](https://github.com/godotengine/godot/files/3132120/AA.zip)

**Comment by mysticfall** [comment]
Could it be related to #18293?

**Comment by qarmin** [comment]
It was a problem with PackedScene.save() which only saved nodes, which owner has been set to packed(main) node.
Now it is documented, so issue can be closed.
