### ISSUE TITLE
null pointer crash on x11 linux in set_window_position

### ISSUE THREAD

**Issue by timower** [godotengine/godot#28538]
**Godot version:**
Custom build, commit dd2cd06165670bb0d78bf4aa397935be15716e76

**OS/device including version:**
linux X11, arch linux

**Issue description:**
When starting the game from the editor it crashes on startup. Doesn't happen when starting manually from the command line. This happens because the editor specifies the window position when launching the game.

The crash happens when reading extents at this [line](https://github.com/godotengine/godot/blob/dd2cd06165670bb0d78bf4aa397935be15716e76/platform/x11/os_x11.cpp#L1196)

I think an additional check for `data != nullptr` is needed.

**Steps to reproduce:**

Launch a game from the editor on x11/linux using the I3 window manager?

**Comment by akien-mga** [comment]
Likely a regression from #26977, cc @bruzvg.

**Comment by bruvzg** [comment]
If [XGetWindowProperty](https://www.x.org/releases/X11R7.5/doc/man/man3/XGetWindowProperty.3.html) returned `Success`, data shouldn't be null. Probably we need to check returned format and item count (and free allocated data?).

@timower Try following patch (I have not testes it yet, probably will check myself tomorrow).
Also, check `OS::get_real_window_size()`, is it crashing too?

```diff
diff --git a/platform/x11/os_x11.cpp b/platform/x11/os_x11.cpp
index 267ac08a7..0f4546b0d 100644
--- a/platform/x11/os_x11.cpp
+++ b/platform/x11/os_x11.cpp
@@ -1192,9 +1192,12 @@ void OS_X11::set_window_position(const Point2 &p_position) {
 		unsigned long remaining;
 		unsigned char *data = NULL;
 		if (XGetWindowProperty(x11_display, x11_window, prop, 0, 4, False, AnyPropertyType, &type, &format, &len, &remaining, &data) == Success) {
-			long *extents = (long *)data;
-			x = extents[0];
-			y = extents[2];
+			if (format == 32 && len == 4) {
+				long *extents = (long *)data;
+				x = extents[0];
+				y = extents[2];
+			}
+			XFree(data);
 		}
 	}
 	XMoveWindow(x11_display, x11_window, p_position.x - x, p_position.y - y);
@@ -1220,9 +1223,12 @@ Size2 OS_X11::get_real_window_size() const {
 	unsigned long remaining;
 	unsigned char *data = NULL;
 	if (XGetWindowProperty(x11_display, x11_window, prop, 0, 4, False, AnyPropertyType, &type, &format, &len, &remaining, &data) == Success) {
-		long *extents = (long *)data;
-		w += extents[0] + extents[1]; // left, right
-		h += extents[2] + extents[3]; // top, bottom
+		if (format == 32 && len == 4) {
+			long *extents = (long *)data;
+			w += extents[0] + extents[1]; // left, right
+			h += extents[2] + extents[3]; // top, bottom
+		}
+		XFree(data);
 	}
 	return Size2(w, h);
 }
```

**Comment by akien-mga** [comment]
For the reference, I can't reproduce the issue on Mageia 7 with KDE Plasma 5, it's likely WM-specific.

**Comment by bruvzg** [comment]
FYI: I have done some testing: returning empty extents seems to be common behaviour for many tiling WMs, all compositing WMs I have tested return 4 * 32 extends as per [freedesktop specification](https://specifications.freedesktop.org/wm-spec/1.5/ar01s05.html), aforementioned patch seem to be OK.

Another possible issue, `XFree` usage is inconsistent, sometimes it's called only if `XGetWindowProperty` has returned `Success`, sometimes regardless of returned status.  Property data allocated in `is_window_minimized` and `read_property` (helper function used for DnD) is not freed at all.
