### ISSUE TITLE
Stable (3.1.0 - 3.1.1) Crash when to import model with 3d bones. until now?

### ISSUE THREAD

**Issue by giovanigsilva** [godotengine/godot#28546]
**Godot version:**
3.1 - 3.1.1

**OS/device including version:**
Android / Samsung S7

**Issue description:**
Animation + bones = Crash, what's the solution?

**Steps to reproduce:**
import any objects that have bone by blender

**Comment by YeldhamDev** [comment]
Could you provide a backtrace? Just run it in the a terminal, and repeat the steps that cause the crash, then copy and paste the result here.

**Comment by giovanigsilva** [comment]
> Could you provide a backtrace? Just run it in the a terminal, and repeat the steps that cause the crash, then copy and paste the result here.
> 
> Also, in what OS it happens? It states "Android" in your report, but it says it happens "while importing".

Could you provide a backtrace?
**** I do not know how to do
What's the command line to windows10?

Also, in what OS it happens? 
**** Windows10 

It states "Android" in your report, but it says it happens "while importing".
**** 
after compiling the SDK file does not open if you have (animated bears) on my S7 mobile with android.

Only animation without bears - ok opens normal

**Comment by YeldhamDev** [comment]
Sorry for the late response.

On Windows, a terminal opens with Godot when the editor is opened, correct? What is printed in it when the crash happens?

**Comment by giovanigsilva** [comment]
> Sorry for the late response.
> 
> On Windows, a terminal opens with Godot when the editor is opened, correct? What is printed in it when the crash happens?

Installing to device (please wait...): Samsung SM-G930F
Success
** DEVICE API >= 21; DEBUGGING OVER USB **
Reverse result: 0
Reverse result2: 0
Starting: Intent { act=android.intent.action.MAIN cmp=br.com.malucoo.et/org.godotengine.godot.Godot }
ERROR: _subthread_start: Condition ' err != OK ' is true.
   At: editor/fileserver/editor_file_server.cpp:115

**Comment by giovanigsilva** [comment]
> Sorry for the late response.
> 
> On Windows, a terminal opens with Godot when the editor is opened, correct? What is printed in it when the crash happens?

** Debug Process Started **
OpenGL ES 2.0 Renderer: Mali-T880
** Debug Process Stopped **
 platform/windows/os_windows.cpp:2532 - Condition ' !process_map->has(p_pid) ' is true. returned: FAILED

**Comment by giovanigsilva** [comment]
> Could you provide a backtrace? Just run it in the a terminal, and repeat the steps that cause the crash, then copy and paste the result here.
> 
> Also, in what OS it happens? It states "Android" in your report, but it says it happens "while importing".

Re-run with the -verbose and -certs options for more details.
Uninstalling previous version: Samsung SM-G930F
Success
Installing to device (please wait...): Samsung SM-G930F
Success
** DEVICE API >= 21; DEBUGGING OVER USB **
Reverse result: 0
Reverse result2: 0
Starting: Intent { act=android.intent.action.MAIN cmp=br.com.malucoo.et/org.godotengine.godot.Godot }
ERROR: _subthread_start: Condition ' err != OK ' is true.
   At: editor/fileserver/editor_file_server.cpp:115
ERROR: kill: Condition ' !process_map->has(p_pid) ' is true. returned: FAILED
   At: platform/windows/os_windows.cpp:2532

**Comment by giovanigsilva** [comment]
> Could you provide a backtrace? Just run it in the a terminal, and repeat the steps that cause the crash, then copy and paste the result here.
> 
> Also, in what OS it happens? It states "Android" in your report, but it says it happens "while importing".

Re-run with the -verbose and -certs options for more details.
Uninstalling previous version: Samsung SM-G930F
Success
Installing to device (please wait...): Samsung SM-G930F
Success
** DEVICE API >= 21; DEBUGGING OVER USB **
Reverse result: 0
Reverse result2: 0
Starting: Intent { act=android.intent.action.MAIN cmp=br.com.malucoo.et/org.godotengine.godot.Godot }
ERROR: _subthread_start: Condition ' err != OK ' is true.
   At: editor/fileserver/editor_file_server.cpp:115
ERROR: kill: Condition ' !process_map->has(p_pid) ' is true. returned: FAILED
   At: platform/windows/os_windows.cpp:2532

**Comment by MightyPrinny** [comment]
I have a similar problem, when I run the game on my android 4.4 phone it crashes if the mesh has an armature, but the game runs fine on a modern phone.

**Comment by akien-mga** [comment]
This was fixed by #29751, which should be cherry-picked for 3.1.2.
