### ISSUE TITLE
Group duplicated nodes

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#28549]
**Godot version:**
3.1 stable

**Issue description:**
Right now when duplicating multiple nodes, from this:
![image](https://user-images.githubusercontent.com/2223172/56998224-d7c2f000-6baa-11e9-9624-9f5d62051179.png)

You get this:
![image](https://user-images.githubusercontent.com/2223172/56998239-e1e4ee80-6baa-11e9-88a0-b9f3aa8589c3.png)

It would be infinitely more useful if duplicated nodes appeared like this:
![image](https://user-images.githubusercontent.com/2223172/56998255-f4f7be80-6baa-11e9-9689-970d6d7d5b32.png)

So instead of each node being placed after their respective nodes, they should be grouped after the whole selection.

**Comment by fracteed** [comment]
Yes, this is also a common frustration for me, as I often duplicate 10 or more objects and then have to manually sort them. Would especially be useful if you have an ordered number of nodes (mesh_1, mesh_2, mesh_3, etc) and you want to duplicate these and have it continue the order.

**Comment by Jummit** [comment]
I think it just iterates over every selected nodes and duplicates it, which means it places the copy underneath.

**Comment by KoBeWi** [comment]
It would be very easy to make the duplicated nodes appear after the last one selected, but then there's this
![image](https://user-images.githubusercontent.com/2223172/57022465-87da3c80-6c2f-11e9-9457-14bf00ddd423.png)
New nodes should also appear under the same parent. Either we should always disregard original parents or make this behavior optional, by introducing another duplicate option. I could make a PR for this, but not sure which behavior is desired (personally I wouldn't care about original parents).

**Comment by bojidar-bg** [comment]
I think duplicating [selected] nodes in this tree:

<details><summary>Click to expand</summary>

* Root
  * Node1
    * [Node2]
    * [Node3]
  * [Node4]
  * [Node5]

</details>

Should result in:

<details><summary>Click to expand</summary>

* Root
  * Node1
    * Node2
    * Node3
    * [Node2-duplicate]
    * [Node3-duplicate]
  * Node4
  * Node5
  * [Node4-duplicate]
  * [Node5-duplicate]

</details>

That is, groups should be preserved only inside the same parent, not across all parents.

Also, duplicating selections like this:

<details><summary>Click to expand</summary>

* [A]
* B
* [C]

</details>

Should probably **not** result in:

<details><summary>Click to expand</summary>

* A
* B
* C
* [A-duplicate]
* [C-duplicate]

</details>

That is, only consecutive nodes should be kept together, not all duplicated nodes moved to the bottom.
