### ISSUE TITLE
Compilation failing on Windows becasue - error C2660: 'vsnprintf_s' : function does not take 4 arguments

### ISSUE THREAD

**Issue by lukaszbulzacki** [godotengine/godot#28540]
**Godot version:**
master (it doesn't work)
a3617f6ca82f4c8121f75d9d2c342ef5431dd214 (last commit that work)
554c0ea90b4bc3b94d2c9a357d6f9c1db93abfe7 (probably commit that introduced bug)

**OS/device including version:**
* OS: Windows 10 (64 bit, version 1809, build 17763.437)
* ENV: Visual Studio 2017 Community
* SDK: Windows SDK 10
* CPU: AMD Ryzen 7 2700x
* GPU: Nvidia RTX 2080

**Issue description:**
Early stage of godot compilation is failing, at around 30%.
Could not compile using command "scons p=windows tools=yes module_mono_enabled=yes mono_glue=no -j16"
Few day ago everything was ok
Please look error below.

> thread_local.cpp
> bindings_generator.cpp
> [ 31%] Compiling ==> modules\mono\editor\csharp_project.cpp
> [ 31%] Compiling ==> modules\mono\editor\dotnet_solution.cpp
> csharp_project.cpp
> [ 31%] modules\mono\utils\string_utils.cpp(222): error C2660: "vsnprintf_s": funkcja nie przyjmuje 4 argumentów
> D:\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h(1623): note: zobacz deklarację „vsnprintf_s”
> modules\mono\utils\string_utils.cpp(230): error C2660: "vsnprintf_s": funkcja nie przyjmuje 4 argumentów
> D:\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h(1623): note: zobacz deklarację „vsnprintf_s”
> [ 31%] Compiling ==> modules\mono\editor\godotsharp_builds.cpp
> dotnet_solution.cpp
> [ 31%] godotsharp_builds.cpp
> Compiling ==> modules\mono\editor\godotsharp_editor.cpp
> [ 31%] godotsharp_editor.cpp
> Compiling ==> modules\mono\editor\godotsharp_export.cpp
> [ 31%] Compiling ==> modules\mono\editor\mono_bottom_panel.cpp
> godotsharp_export.cpp
> [ 32%] Compiling ==> modules\mono\editor\mono_build_info.cpp
> scons: *** [modules\mono\utils\string_utils.windows.tools.64.obj] Error 2
> mono_bottom_panel.cpp
> mono_build_info.cpp
> scons: building terminated because of errors. 

**Steps to reproduce:**
1. Download source from master
2. Execute command scons p=windows tools=yes module_mono_enabled=yes mono_glue=no -j16

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by neikeq** [comment]
Can you check if #28544 fixed the build error?

**Comment by lukaszbulzacki** [comment]
@neikeq  7a42df3626159d1d81d2b5aabf13f19ef1951976 from goshujinsama it compile fine.

**Comment by akien-mga** [comment]
Fixed by #28544.

**Comment by lukaszbulzacki** [comment]
@neikeq yea,  7a42df3626159d1d81d2b5aabf13f19ef1951976 from goshujinsama it compiles fine.
Thanks.
