### ISSUE TITLE
Vector4 is not highlighted properly in code editor

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#2855]
Vector4, unlike other Vector* class in highlighted in grey, and not in green (as other build-ins) or blue (as Object inheriting classes).

![Preview of issue](https://cloud.githubusercontent.com/assets/5276727/11318682/cefe51fa-9064-11e5-97b5-00093fac57a9.png)

**Comment by reduz** [comment]
There is no Vector4, our reality is threedimensional.

**Comment by bojidar-bg** [comment]
Ooops! I'm going to close this then. Sorry @reduz

**Comment by reduz** [comment]
hehe :D

**Comment by reduz** [comment]
when adding SSE, Vector3 will likely have 4 fields, thoughi guess it will
still be called Vector3
