### ISSUE TITLE
ItemList.unselect() should be ItemList.deselect()

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28558]
**Godot version:**
3.1.1

**Issue description:**
ItemList.unselect() is a very strange name. ItemList.deselect() is easier to find.

We have all these `deselects`:
![image](https://user-images.githubusercontent.com/28286961/57009621-f9969400-6bf7-11e9-98fa-db57328e1f79.png)

And only this `unselect`:
![image](https://user-images.githubusercontent.com/28286961/57009637-087d4680-6bf8-11e9-9b9f-8aa9200de1c8.png)

**Comment by akien-mga** [comment]
Good point. I've added it to the list in #16863.

**Comment by Jummit** [comment]
Maybe even rename `deselect_all` to match this:
![image](https://user-images.githubusercontent.com/28286961/57009842-61011380-6bf9-11e9-975d-cb42a666f50f.png)
