### ISSUE TITLE
Newly open help view tab won't scroll to the searched result

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#2856]
When choosing a result from the Search Help dialog, it should open the Help view and scroll to the result.

It works fine if this Object's Help view is already open. But if that's not the case, it will open a new tab and scroll to the bottom of the view, rather than to the searched result.

**Comment by vnen** [comment]
Just to be clear, this bug was already happening on the old help view, so it has nothing to do with the change.

**Comment by neikeq** [comment]
Title should be clearer now.

**Comment by neikeq** [comment]
For some reason _get_size()_ returns (0, 0) the first time **RichTextLabel**::_\_validate_line_caches()_ is called.
