### ISSUE TITLE
Node2D.look_at(Vector2 point) should have an additional parameter for adding an additional rotation.

### ISSUE THREAD

**Issue by K1NGM4RV** [godotengine/godot#28566]
**Godot version:**
v3.1-stable

**OS/device including version:**
Windows 10 - 1809

**Issue description:**
The function look_at(Vector2 point) rotates your sprite towards a specified point (e.g. mouse). The problem is that you might need an additional rotation (e.g. if you want to rotate the sprite bottom towards it) which has to specified after the function call. Doing so can result in unexpected behaviour (e.g. Spinning of the character in case your points match each other - sure you could work around that but it would be a great quality of life improvement. Since it took me some time to figure out a workaround while interpolating this process.)

**Steps to reproduce:**
Create a Node2D and attach a sprite on it (the godot icon should do the trick). You can take your mouse cursor as the point to rotate to. Notice that the rotation works, however what if you want to rotate the top/bottom towards the sprite?

**Minimal reproduction project:**
[Look_at_playtest.zip](https://github.com/godotengine/godot/files/3134417/Look_at_playtest.zip)

**Comment by Zylann** [comment]
The following perfectly works for me:
```gdscript
	sprite.look_at(mousepos)
	sprite.rotate(PI/2.0)
```
I don't understand what's the drawback?

**Comment by K1NGM4RV** [comment]
Well that's exactly what I have proposed in the demo. Only problem is that the character starts spinning as soon as the points overlap but I think you can define conditions for that not to happen (also proposed in the demo).

Thanks for the clarification! I thought there could have been something else that could have been done but I think defining a deadzone does the trick. Cheers! 


#Issue closed
