### ISSUE TITLE
ERROR: get_frustum: Condition ' !is_inside_world() ' is true. returned: Vector<Plane>()

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [godotengine/godot#28569]
**Godot version:**
3.1
**OS/device including version:**
Windows 10
**Issue description:**
Tonns of errors during mouse movement on scene during project edition : 

```
ERROR: get_frustum: Condition ' !is_inside_world() ' is true. returned: Vector<Plane>()
   At: scene/3d/camera.cpp:605
ERROR: get_frustum: Condition ' !is_inside_world() ' is true. returned: Vector<Plane>()
   At: scene/3d/camera.cpp:605
ERROR: get_frustum: Condition ' !is_inside_world() ' is true. returned: Vector<Plane>()
   At: scene/3d/camera.cpp:605
ERROR: get_frustum: Condition ' !is_inside_world() ' is true. returned: Vector<Plane>()
   At: scene/3d/camera.cpp:605
ERROR: get_frustum: Condition ' !is_inside_world() ' is true. returned: Vector<Plane>()
   At: scene/3d/camera.cpp:605
ERROR: get_frustum: Condition ' !is_inside_world() ' is true. returned: Vector<Plane>()
   At: scene/3d/camera.cpp:605
ERROR: get_frustum: Condition ' !is_inside_world() ' is true. returned: Vector<Plane>()
   At: scene/3d/camera.cpp:605
ERROR: get_frustum: Condition ' !is_inside_world() ' is true. returned: Vector<Plane>()
   At: scene/3d/camera.cpp:605
ERROR: get_frustum: Condition ' !is_inside_world() ' is true. returned: Vector<Plane>()
   At: scene/3d/camera.cpp:605
```
**Steps to reproduce:**
Not sure but i did following. 
1) Created Scene 3d
2) Added Meshinstance with capsule mesh
3) Added Camera 
4) moved camera by Z axis
5) highlighted(clicked) on camera in Nodes list
6) start to move mouse pointer over main scene window
got tonns of errors

**Minimal reproduction project:**
![engine_errors](https://user-images.githubusercontent.com/22169129/57017707-98cf8180-6c20-11e9-9cd5-c978e30821c8.jpg)

**Comment by jpVm5jYYRE1VIKL** [comment]
Possible workaround how-to also acceptable.

**Comment by jpVm5jYYRE1VIKL** [comment]
After full restart of Godot i cannot reproduce it anymore.

**Comment by creikey** [comment]
I was unable to reproduce this issue on latest master 22c843b0c451a0c3d79a3b3e6af900b841c51c12
