### ISSUE TITLE
Please make Text Editor Indent Spaces by default.

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [godotengine/godot#28560]
**Godot version:**
any

**OS/device including version:**
I presume any. But Windows affected.

**Issue description:**
By default Godot Editor using Tabs as Indent. But all examples in Internet and examples included with Godot itself use spaces.  Beginners can be confused in moment if they modify existing code. They get indent errors.  It is also strange why was chosen Tabs as default indention but look like nobody use it.

**Steps to reproduce:**
Fresh installation

**Minimal reproduction project:**
Just create new script using File -> New Script . it will have spaces indention.

**Comment by akien-mga** [comment]
>  Just create new script using File -> New Script . it will have spaces indention.

I can't reproduce that in a default setup:
![Screenshot_20190501_104032](https://user-images.githubusercontent.com/4701338/57010563-93147480-6bfd-11e9-9d3f-7d6ab7661e5d.png)

But you can change the Text Editor > Indent > Type setting in the Editor Settings to default to space.

**Comment by akien-mga** [comment]
The mismatch between the default tabs indent type and the spaces used on the documentation website is due to the documentation using Sphinx / Python which favors spaces.

The way to improve this situation is tracked in #19285.

**Comment by jpVm5jYYRE1VIKL** [comment]
Listen i can easy reproduce this issue on at least 3 computers.

**Comment by akien-mga** [comment]
> Listen i can easy reproduce this issue on at least 3 computers.

What can you reproduce exactly? With default config, the default template has tabs for me, both on Linux and Windows 10.

>  What sense to use Tabs as default if NOBODY use it.

Most people use tabs as default.

**Comment by jpVm5jYYRE1VIKL** [comment]
Yes. Default config after very fresh installation without touching editor options. 
by default if you create new script created it with Spaces. It is not problem for me in reality because i know exactly what to do with it. But for my child it was something new.  But it doesn`t matter in reality. Because all examples use spaces. So to avoid problems preferred style is a style which everywhere in internet. 

> Most people use tabs as default. All demos use tabs too, see e.g. https://github.com/godotengine/godot-demo-projects/blob/master/2d/platformer/player/player.gd

Well it is very speculative answer . 
**Developers Who Use Spaces Make More Money Than Those Who Use Tabs**
https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/

**400,000 GitHub repositories, 1 billion files, 14 terabytes of code: Spaces or Tabs?**
https://medium.com/@hoffa/400-000-github-repositories-1-billion-files-14-terabytes-of-code-spaces-or-tabs-7cfe0b5dd7fd

Well it is up to you.

**Comment by akien-mga** [comment]
I'm not going to follow you in a pointless discussion on tabs vs spaces, what I was saying is that most **Godot users** use tabs for GDScript, and this is what matters. All demos use tabs too. Only documentation examples use spaces due to using a Python framework, as mentioned above.

The default setting is to use tabs, and the default template includes tabs. I can't reproduce your claim that it defaults to spaces, which would be a bug. Can you confirm that your Editor Settings have "Tabs" as indent type, and show a screenshot of a newly created script?

**Comment by jpVm5jYYRE1VIKL** [comment]
Sorry that i disturb you again. But after attentive reading issue #18189 discussion. I am totally understood your position and some another Tab adepts and not see any sense to discuss it here. Good luck. Thanks for your time.

**Comment by akien-mga** [comment]
Funny that you say that, as the first ever issue I opened on this repository before becoming a contributor was #1340, specifically requesting an option to use spaces in the editor.

But indeed, I have no time to waste on pointless holy wars.
