### ISSUE TITLE
Fragment shader pass VAR1 causes a broken matrix

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#2857]
I try to pass values in VAR1 and VAR2 , but on assingn the result is:
![error](https://cloud.githubusercontent.com/assets/85936/11319032/3039ba96-9050-11e5-9f3a-206b0d1c04e2.jpg)

**Comment by reduz** [comment]
are you passig it to the lighting shader?

**Comment by marcosbitetti** [comment]
yes

**Comment by 0nepixel** [comment]
i'm not the only one with this problem, good to know

**Comment by bojidar-bg** [comment]
(assuming it doesn't happen in 3.0, but if someone can confirm it there too, he is welcome to do it.)

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Comment by Chaosus** [comment]
VAR1/VAR2 are not even exist in 3.x..
