### ISSUE TITLE
Support Enable/Disable feature for the Node

### ISSUE THREAD

**Issue by megalike** [godotengine/godot#28579]
Support Enable/Disable node with callback _on_enable && _on_disable (inside Editor too).

I think it's too complex feature, but it's open a lot of space and improve workflow for designers.
As example some of object enable only on high spec and a lot of other trick.
For programmers it's improve performance spike by easy implement Object Pool only with GDScript.

**Comment by groud** [comment]
What you are asking for is quite unclear. Please be a more specific.
What is the precise use case ?

It's already really easy to enable or disable rendering features right now, to disable physics for nodes or pause them. I see no point in adding another layer of "feature management".

**Comment by megalike** [comment]
I mean a complex node can have a lot of types such a mesh render, audio, physics, script and can have complex hierarchy. How i can easy to disable it all without delete? How about case for level design (prototyping) where you want do some test and disable some part of level which have a complex structure ? And open question about pool object, without enable/disable node i can't it do easy and natural.

I want to discuss it for understand why it's was not implemented.
For now i think it was a huge mistake to skip this functionality and maybe it's not so easy at all for now to do that.

Thanks.

**Comment by groud** [comment]
You have groups in Godot. You can easily remove a whole group from the tree depending on what you need. But in any case we probably wont ship such a system, it depends too much on the game you are making.

**Comment by megalike** [comment]
Yeah. I am understand you. Thanks for suggest to use group.
