### ISSUE TITLE
Track option PopupMenus in Animation editor have their text overlapping their icons

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#28589]
**Godot version:**
3.2-dev 46b6fb8

**OS/device including version:**
Linux Mint 19.2 Cinnamon

**Issue description:**
Possibly a regression from #27204 or #28554
![1](https://user-images.githubusercontent.com/27100585/57048538-b26fd800-6cb7-11e9-91a4-d6070bd4f899.png)
![2](https://user-images.githubusercontent.com/27100585/57048540-b3a10500-6cb7-11e9-9069-b82666b321d3.png)
![3](https://user-images.githubusercontent.com/27100585/57048543-b56ac880-6cb7-11e9-9c44-d0a7372ddfb1.png)

**Steps to reproduce:**
1. Load or create an animation in the animation editor
2. Make sure there's at least one track added
3. Click on any of the menu dropdowns on the right of each track

**Comment by bojidar-bg** [comment]
CC @YeldhamDev
