### ISSUE TITLE
Using gradle for android template to specify which java packages to use

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#2858]
I found this on forum.
http://www.godotengine.org/topics/12954?r=12959

According to these pages...

http://stackoverflow.com/questions/33788471/google-play-we-found-ad-sdks-in-your-application
https://forums.coronalabs.com/topic/60214-not-got-ads-but-google-has-detected-them/

android template apk file needs to remove Admob api.
And google will start removed the apps those are not resolved this issue from Jan 2016.
I not sure it's true, but isn't it urgent issue?

**Comment by akien-mga** [comment]
I don't think the official templates have the AdMob SDK, do they?

Aren't you using the unofficial templates by Kelinci Senja which include the AdMob module by TeamBlubee?

Also the issue title and the actual descriptions don't really fit, even though IIUC you expect a move to gradle to fix the described issue?

**Comment by volzhs** [comment]
I know official templates just have "google-play-services.jar".
but this jar has admob api and this causes problem.

I've searched a little bit and we can specify packages to use when using gradle.

**Comment by volzhs** [comment]
I sent an email to google play developer help to ask what happen if I just select "No Ads" without removing ADs SDK.
I will post what they say later.

**Comment by reduz** [comment]
and yes, we have to move to gradle. i didn't have much time so far, but
contributions are always welcome :P

**Comment by volzhs** [comment]
Google talks to me just select "No ads".
I don't think this issue is in such hurry.

**Comment by volzhs** [comment]
I think this is resolved.
