### ISSUE TITLE
Cannot copy node's path on remote scene tree

### ISSUE THREAD

**Issue by pgoral** [godotengine/godot#28585]
**Godot version:** 3.1.1
![image](https://user-images.githubusercontent.com/11059246/57038116-65f5af80-6c59-11e9-9d45-f84bc03abd60.png)

There should be menu item to allow copy node's path

**Comment by captaincrunch21** [comment]
Hey I am interested in solving this bug. I have xp in osg and cpp 
Thanks.

**Comment by KoBeWi** [comment]
@captaincrunch21 If you want a place to start, just search whole source code for "Save Branch as Scene" and "Copy Node Path". The rest is copy-paste I guess.

**Comment by hbina** [comment]
Hi, do you have a sample project that I can use to debug this?

**Comment by bojidar-bg** [comment]
> ...I can't figure out how to obtain current selection in the Remote tab.

Maybe try to find how "Save branch as scene" does it.

**Comment by Zireael07** [comment]
"Save branch as scene" works remotely? TIL.
