### ISSUE TITLE
Support hot reload tool script without open/close scene

### ISSUE THREAD

**Issue by megalike** [godotengine/godot#28580]
Currently i am face the problem of require to reload scene to properly run tool script.
I proposal to detect script change and reload it in background. End user see result as soon as possible. It's improve for rapid development and prototyping.

**Comment by Jummit** [comment]
Just bind "reload scene" to a keybind and use that, it's pretty quick.

**Comment by megalike** [comment]
Maybe you can suggest how do this ? I don't see any reload scene in the shortcut configuration...
Thanks.

**Comment by megalike** [comment]
Tool script already works fine, it was my mistake about _draw callback.

Should call self update to trigger _draw callback.

#Sampe GDScript tool

tool

extends Node2D

func _process(delta):
	self.update()
	
func _draw():
	draw_line(Vector2(50, 50), Vector2(500, 200), Color('#ff0000'), 2.0)

**Comment by evanandrewrose** [comment]
I don't understand your last comment or why you closed this issue. I would also like hot reloading of tool scripts.

**Comment by megalike** [comment]
Firstly i make incorrect assumption what tool script changes apply only after reload. The tool script work on change already, but on the first attach/detach it to the node you should reload scene. When i start to do this task i found what it's not a huge problem to reload scene when you attach a new script (or delete it), it's a workaround. I am reopen task.

**Comment by Jummit** [comment]
> More editor actions can now have shortcuts assigned (such as Revert Scene or Export).

Found in the [changelog for 3.2](https://gist.github.com/Calinou/49aefe52ce8f67ffa3f743932123d14f). I remember using this, but I can't find it anywhere now...

**Comment by oap-bram** [comment]
I would also still like hot reloading for tool scripts. I use tool script extensively for making custom components inside the editor. It takes me a lot of time to keep reloading a lot of time, and it doesn't seem to happen reliably at all.

+1 for the issue.

**Comment by justinluk** [comment]
I just ran into this issue as well. I had to close and reload the engine to get a tool script to work in 3.2.1

**Comment by jasonjmcghee** [comment]
I wanted this as well. This is how I solved it. 

Any time a resource is saved, like a `tool` script, the scene gets reloaded - that's it.

Incredibly useful for things like (e.g.) iterating on a procedural generation algorithm.

Just make an addon / plugin with:

```gdscript
@tool
extends EditorPlugin

func _enter_tree() -> void:
    resource_saved.connect(_on_resource_saved)

func _on_resource_saved(res: Resource):
    get_editor_interface().call_deferred(
        "reload_scene_from_path", 
        res.get_local_scene().scene_file_path
    )
```

`call_deferred` is needed (or the editor crashes about half the time).

https://github.com/godotengine/godot/assets/1522149/edc5ac8f-4347-40f1-9886-d347e5ddf9f5

**Comment by russmatney** [comment]
@jasonjmcghee this is nifty! `resource_saved.connect(_on_resource_saved,
CONNECT_DEFERRED)` might work too (probably the same effect as a call_deferred).

I've been doing something similar to add a 'reload' `R` button to the play/pause area:

```gdscript
var reload_scene_btn = Button.new()
var editor_interface

func _enter_tree():
	editor_interface = get_editor_interface()

	reload_scene_btn.pressed.connect(reload_scene)
	reload_scene_btn.text = "R"
	add_control_to_container(CONTAINER_TOOLBAR, reload_scene_btn)
	reload_scene_btn.get_parent().move_child(reload_scene_btn, reload_scene_btn.get_index() - 2)

func reload_scene():
	print("-------------------------------------------------")
	print("[ReloadScene] ", Time.get_time_string_from_system())
	var edited_scene = editor_interface.get_edited_scene_root()
	print("edited scene", edited_scene, ".scene_file_path", edited_scene.scene_file_path)
	editor_interface.reload_scene_from_path(edited_scene.scene_file_path)
	print("-------------------------------------------------")
```

Getting this on file-save is huge! ty for sharing!
