### ISSUE TITLE
Collisions missed in Bullet Physics but not Godot Physics

### ISSUE THREAD

**Issue by duckinator** [godotengine/godot#28592]
**Godot version:**
3.0

**OS/device including version:**
Fedora 29

**Issue description:**

With Bullet Physics, I'm able to consistently get objects to go through walls, even with CCD enabled.

Switching to Godot Physics _and_ setting Physics FPS to 120 fixes it. Either alone doesn't fix it.

**Steps to reproduce:**

Apply an impulse to a RigidBody so that it goes flying at another RigidBody at high speed.

When the speed exceeds a certain point, it simply passes through.

**Minimal reproduction project:**

https://github.com/duckinator/godot-bullet-issue-testcase

Branch `master` is the testcase, branch `fixed` is a fixed variant as described above.

**Comment by duckinator** [comment]
Opened this as suggested by @reduz: https://twitter.com/reduzio/status/1123756724299735040

**Comment by eon-s** [comment]
Cannot reproduce on 3.1 even with the bullets at 500 units of impulse, can you try it on that version?

Related to #16113 but that one is rigid against static and fails at really low speeds.

**Comment by duckinator** [comment]
I can't reproduce in 3.1, either. So nevermind I guess lol
