### ISSUE TITLE
Animation editor time markers in "FPS" snap mode are uneven and jittery

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#28594]
**Godot version:**
3.2-dev 46b6fb8

**OS/device including version:**
Linux Mint 19.1 Cinnamon

**Issue description:**
When using the Animation editor with the snap mode set to "FPS", the time markers in the timeline aren't laid out in even increments:
![image](https://user-images.githubusercontent.com/27100585/57055030-b01f7500-6cdb-11e9-9ee3-30a06e915002.png)

They also flicker when scrolling through the timeline:
![gif](https://user-images.githubusercontent.com/27100585/57055142-a2b6ba80-6cdc-11e9-8968-15047ee3e8af.gif)

Also, the "0th" frame marker never shows.

These problems seem to be exclusive to "FPS" mode; in "Seconds" mode, everything works fine.

**Steps to reproduce:**
1. Add an AnimationPlayer node to a scene
2. Add or create a new animation
3. Change the snap mode from "Seconds" to "FPS"
4. Set the snap value to something higher like 60
5. Scroll through the timeline

**Comment by avencherus** [comment]
@homer666 I noticed there has been quite a few commits for this feature lately, but haven't been following closely.  Would you happen to know a commit when it first started to happen?

**Comment by homer666** [comment]
It would've had to have been when frame snapping in the animation editor was added, in 4203266.

**Comment by akien-mga** [comment]
Seems fixed in the current master branch.
