### ISSUE TITLE
AnimationPlayer keyframe snapping is not aligning to the timeline markers.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#28597]
**Godot version:**

46b6fb83efc8e021cf60502d1e42fdd912b020eb

**OS/device including version:**

Win10 64-bit

**Issue description:**

At various levels of zoom, keyframe snapping no longer tracks with the label guide for time position.  Though the keyframes seem to correctly snap when released.  Just not during dragging.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/13004169/57058877-ee586c80-6cba-11e9-934e-5738458c2ee7.gif)

Might be related to what is causing this:  https://github.com/godotengine/godot/issues/28594

**Steps to reproduce:**
1. Create some keyframes in an AnimationPlayer track.
2. Zoom in and move further up the timeline.
3. Use an appropriate snap level and drag the keyframe around.

**Comment by homer666** [comment]
I messed with the snapping behaviour in #28361, maybe try reverting it...

**Comment by avencherus** [comment]
Thanks, I'll test that out.

**Comment by avencherus** [comment]
Unfortunately it must be somewhere else.  The problem still appears after reverting it.

![image](https://user-images.githubusercontent.com/13004169/57121230-b4509e80-6d7e-11e9-8dbf-ff89ece7172a.png)

**Comment by YeldhamDev** [comment]
Note that the problem only starts being noticeable when the keyframe is far from 0 in the timeline.
