### ISSUE TITLE
AnimationPlayer call method does not work with extended classes

### ISSUE THREAD

**Issue by StephenEdnave** [godotengine/godot#28591]
**Godot version:**

3.1

**OS/device including version:**

Windows 10

**Issue description:** 

When setting up an AnimationPlayer with a call method track on a node that uses a script that extends another script, i.e. using AnimationPlayer to call a method in class B that extends class A, class A methods are not listed, but class B methods are listed twice.

**Steps to reproduce:**
1. Make a class_name A
2. Have a new script (B) extend A
3. Set up a call method track on an AnimationPlayer that calls a method on a node with the B script
4. Insert a key on the call method track and look at the list of functions available

**Minimal reproduction project:**

[AnimationPlayerInheritedClassBug.zip](https://github.com/godotengine/godot/files/3136466/AnimationPlayerInheritedClassBug.zip)

**Comment by bojidar-bg** [comment]
Potentially related: #27152
