### ISSUE TITLE
Canvas editor selection menu shortcuts are pathological under *nix

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2860]
This issue is about #2786

Under Linux and BSDs, Alt+Right Click or Alt+Click don't even go to any app by default. These shortcuts respectively scale and move windows (handled by the window manager).

**Comment by reduz** [comment]
yeah you will have to disable that in your window manager. It's the same
story with Blender and other software.

**Comment by seadra** [comment]
Not, it's not.
In [Blender](https://www.blender.org/manual/modeling/meshes/selecting/edges.html) and other software, the norm is, you change the shortcut in the software. You *don't* tell to change your users to change their *global* X11 just for your program.

Seriously, you're asking me to change a desktop shortcut that is in use for more than 20 years. It's no different that assigning a shortcut to Alt+F4. That's just crazy.

You should either allow users change the shortcuts, or change this crazy shortcut.

**Comment by reduz** [comment]
changing shortcuts will not happen for a while, so get used to it

**Comment by seadra** [comment]
> get used to it

Are you fucking kidding me?

**Comment by reduz** [comment]
nope,  being able to customize shortcuts is not a priority until 3.0, so
you will have to be patient and live with it or use Unity, which is now
available for Linux :)

**Comment by seadra** [comment]
No, that's what I'm not talking about.
This is a one-liner change, just change this
> if (!b.pressed && tool==TOOL_SELECT && b.mod.alt) {

to
> if (!b.pressed && tool==TOOL_SELECT && b.mod.alt && b.mod.shift) {

or something similar. What are you trying to make our lives difficult. No one is going to change an established global *nix shortcut just to make some popup work in godot.

Seriously, why are you resisting to change this pathological, hard-coded shortcut?

Unity for Linux ATM is really really buggy BTW.

**Comment by reduz** [comment]
Hey, Blender was around for 10 years before they allowed shortcut
customization and no one died because of it.

So let's see what happens first then, Godot allowing customizable
shortcuts, or Unity becoming stable on Linux

**Comment by seadra** [comment]
No, for god's sake, forget about shortcut customization!

Why don't you just change the hard-coded shortcut? It hasn't appeared in any public release yet, so I'm pretty sure no one is used to Alt+RMB in godot yet.

**Comment by seadra** [comment]
Just change it to Shift+Alt+RMB or whatever and everyone (at least both Windows and Linux users) will be happy.

**Comment by reduz** [comment]
well, just change it in your version. To be honest, there are plenty of
Unix WMs and they all use different sets of hardcoded key combinations, so
I don't give two cents about complying with Unix WMs. Making a shortcut
more difficult to use in OSX and Windows because a Unix WMs choose to take
control of dozens of key combinations is a no in my book.

**Comment by reduz** [comment]
just change it yourself in your tree if it's a life or death situation for
you.
o far no one else complained. Most of us are used to dealing with Windows
and OSX besides Linux so we can live without that shortcut in the WM

**Comment by seadra** [comment]
> Unix WMs and they all use different sets of hardcoded key combinations, so I don't give two cents about complying with Unix WMs.

You're trying to paint it as if Alt+RMB is some obscure shortcut on certain WMs. It's not. It's there is every single mainline WM. Grab and install any mainsteam Linux distro, and that is what Alt+RMB will do.

Facts so far:

* This is a bug for *all* mainsteam Linux users using out-of-the-box X11/WM settings.
*  This shortcut appeared only 3 days ago in the code, and hasn't appeared in any public release. So of course 1) "so far no one else complained" is not a mystery 2) no one will miss it if you change it *now*
* The fix is a one-liner.
* You turned this trivial into a power-play
* You basically said you don't give a rat's ass about Linux users

What is resisting the change just because you can and you don't give a shit about Linux users, and because there is no reason of not making this change in your book?

**Comment by reduz** [comment]
Let linux users complain by themselves, don't speak for all of them

**Comment by seadra** [comment]
I'm not "speaking for all of them".
In case you missed, the list "Facts so far" refer to *facts*, not some interpretation or a representative speech.

Apparently, I missed a fact about your attitude. And some attitude you have.

**Comment by seadra** [comment]
On the other hand, you saying you don't give a shit about Linux users is *you* speaking about *all* of them.

**Comment by reduz** [comment]
My attitude is very clear on this matter, I don't care about being
compliant with stock Unix WMs.
There are plenty more shortcuts that don't work in stock Unix WMs because
you didn't figure they exist yet, so this is just one more. So far no one
seems to care, and you seem to be the only one worried about this
situation.
If it's so bad for you, go and change it in the source code or disable it
in the WM. There's nothing else I have to say about it.

**Comment by seadra** [comment]
> My attitude is very clear on this matter, I don't care about being compliant with stock Unix WMs.

Yeah, I think we've already established the fact that you don't give a shit about Linux/BSD users. Please write this in your documentation and front page too. 

It will help a lot to FOSS people (including  Software Freedom Conservancy) getting the wrong idead about you.

**Comment by reduz** [comment]
Users can now change the wiki on the website, so just ask for permission
and do it yourself

**Comment by seadra** [comment]
Oh, please, more gems.

As if your company will let such a change stay there.

**Comment by seadra** [comment]
I've come to realize that Unity cares a lot more than you do about Linux users.
Bye, Godot.

**Comment by reduz** [comment]
Let's get some things straight

1) Godot is no longer associated to any company, nor am I. It's part of the
SFC now.
2) You behave as if you had paid for a closed source game engine and it's
your right that it works the way you desire.

I hope you reconsider these two facts that you seem to have wrong. With
that said, i'm closing this issue.

**Comment by seadra** [comment]
> 1) Godot is no longer associated to any company, nor am I. It's part of the
SFC now.

Then why does everything need an OK from okamstudio developers? Why is it OK for them to be tyrants, causing such trouble for FOSS OS users, and refusing to work with them?

> 2) You behave as if you had paid for a closed source game engine and it's
your right that it works the way you desire.

No I'm not.

I'm already in my 40s, and most of my professional life has been spent is FOSS word. There are people like you all over treating users who are making a valid point because they don't care, they're lazy, they wanna show they're in chage, they had a bad day, or because they're just a constant ass, or whatever.

I frankly don't care which group you fall under. Just don't play the "don't act like you're paying me" card. If that was the case, you'd been fired already. No for your attitude, but for saying "I don't give a shit about FOSS OS users" just after we commited to getting into bed with the Conservancy. This is a whole world different that explaining a bug and the user-base it affects. See the difference?

**Comment by reduz** [comment]
Okam no longer exists, so there is no company behind Godot.
I never said your point wasn't valid, it is very valid. It's just that I
don't feel it's worth fixing at this point and I hope to implement shortcut
customization as soon as possible after 2.0 is out so you can change it in
a more elegant way.

Meanwhile, I don't want to make the shortcut more cumbersome for Windows
and OSX users. This is why i'm suggesting to change it yourself in the code
until shortcut customization happens.
