### ISSUE TITLE
Glue are not generating on Windows 10

### ISSUE THREAD

**Issue by lukaszbulzacki** [godotengine/godot#28604]
**Godot version:**
master

**OS/device including version:**
* OS: Windows 10 (64 bit, version 1809, build 17763.437)
* ENV: Visual Studio 2017 Community
* SDK: Windows SDK 10
* CPU: AMD Ryzen 7 2700x
* GPU: Nvidia RTX 2080

**Issue description:**
Glue are not generating.
I think command "bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue" is failing, but it is not visible.
Some error below are from next command executed after glue generation.
It's from "scons p=windows target=release_debug tools=yes module_mono_enabled=yes -j16"

> scons: Reading SConscript files ...
Configuring for Windows: target=release_debug, bits=default
Found MSVC compiler: x86_amd64
Compiled program architecture will be a 64 bit executable (forcing bits=64).
RuntimeError: Missing mono glue sources. Did you forget to generate them?:
  File "D:\apl\Godot\SConstruct", line 477:
    SConscript("modules/SCsub")
  File "d:\apl\python372\lib\site-packages\scons\SCons\Script\SConscript.py", line 667:
    return method(*args, **kw)
  File "d:\apl\python372\lib\site-packages\scons\SCons\Script\SConscript.py", line 604:
    return _SConscript(self.fs, *files, **subst_kw)
  File "d:\apl\python372\lib\site-packages\scons\SCons\Script\SConscript.py", line 285:
    call_stack[-1].globals)
  File "D:\apl\Godot\modules\SCsub", line 17:
    SConscript(x + "/SCsub")
  File "d:\apl\python372\lib\site-packages\scons\SCons\Script\SConscript.py", line 667:
    return method(*args, **kw)
  File "d:\apl\python372\lib\site-packages\scons\SCons\Script\SConscript.py", line 604:
    return _SConscript(self.fs, *files, **subst_kw)
  File "d:\apl\python372\lib\site-packages\scons\SCons\Script\SConscript.py", line 285:
    call_stack[-1].globals)
  File "D:\apl\Godot\modules\mono\SCsub", line 34:
    raise RuntimeError('Missing mono glue sources. Did you forget to generate them?')

**Steps to reproduce:**
1. Download master
2. Call command "scons p=windows tools=yes module_mono_enabled=yes mono_glue=no -j16"
3. Call command "bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue"
4. Call command "scons p=windows target=release_debug tools=yes module_mono_enabled=yes -j16"

**Note**
On Linux Debian 9 (stretch) there is no problem.

**Comment by neikeq** [comment]
What is the output when you run the `--generate-mono-glue` command?

**Comment by lukaszbulzacki** [comment]
@neikeq 
> What is the output when you run the `--generate-mono-glue` command?

Ouptut is :
> D:\apl\Godot>bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue
> OpenGL ES 3.0 Renderer: GeForce RTX 2080/PCIe/SSE2
> 
> D:\apl\Godot>

**Comment by ShyRed** [comment]
Can confirm. I have the same problem when trying to generate the mono glue with Windows 10. It seems that somehow the whole binding generator is not called as there is no output to the console window?
