### ISSUE TITLE
Have "Auto Brace Complete" editor setting enabled by default

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#28600]
As the title mentions, maybe Auto Brace Complete could be enabled by default. When I first started using Godot I was surprised it wasn't, but quickly encountered bugs with it so I felt it was justified. Now that the last of its bugs has been eliminated with #25350 I think it would be a good idea to do so now. I don't really know how people feel about it though, since it's been disabled for forever and basically nobody cares. WDYT??????

**Comment by volzhs** [comment]
hm.. well.. i prefer it's disabled..

**Comment by groud** [comment]
> hm.. well.. i prefer it's disabled..

Yes, me too...

**Comment by bojidar-bg** [comment]
I would prefer it enabled, not because I have been using it a lot, but so that Godot's editor is consistent with other editors' defaults.

**Comment by KoBeWi** [comment]
Uh, brace auto-complete is the first thing I disable when using not-yet-configured code editor. It's annoying :/

**Comment by vkubre** [comment]
I prefer it disabled. GDScript is also not like java where it might be super important.

**Comment by homer666** [comment]
Oh, didn't realise so many people found it a pain. It's probably better it stays off, then.
