### ISSUE TITLE
Inspector: clicking on a property value to change it "moves" the value to the left, obstructing productivity flow

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#28618]
**Godot version:**
3.1 stable

**OS/device including version:**
Win 7

**Issue description:**
This is seemingly a minor nuisance, but does hinder the productivity over weeks and months quite a bit:
When clicking on a property value in the inspector, the value shifts left, so even if I clicked in the perfect location to change my property, I have to search again for the right location so click, click again. This is so irritating, that it can lead to a lot more than just twice searching and clicking.
However imho worst of all is that it makes routine movements and musclememory really hard to train and automate.
I was observing myself using various methods to get to the right location of the value string:
using the mouse and LMB click+ LMB click again until I got it right (can take any number of clicks if not 1000% concentrated), LMB click drag + backspace then rewriting deleted characters, LMB click +backspace deleting everything, rewriting everything, LMB click + arrow keys to move to the correct position ...

![inspector_value_click](https://user-images.githubusercontent.com/47016402/57092855-abbf8000-6d0c-11e9-834f-5965475bc39a.gif)

Ideally, the position of the values should not change when clicking on them with the LMB.

Right now, it does not matter where I LMB click on the value, one click always selects the whole value. Imho only double click should do that. Single LMB click should bring the cursor exactly at the string location where you clicked. Single LMB click and hold does the same but if I then drag the cursor left or right I can mark any number of adjacent characters left or right from where I clicked. This is how textboxes usually work.

Currently LMB single click then rewriting everything is the most efficient, because there is no real alternative.
It is however a less efficient solution overall, 

- for one, because by clicking on the value the user already has had the opportunity to select where exactly to insert the cursor, and 
- second because the user has to remove both hands to write fast, so also the hand from the mouse clicking the value location.
- Rewriting instead of changing only the desired digits or characters bears the risk of reintroducing bugs in already working code. 
- When complete rewriting is actually desired, it is available within a double click or click-drag (Edit: or clicking in the empty area)
- Single LMB click and drag would also allow complete rewrite without loss of usability.

**Edit:** 

- GammaGames has suggested to use the empty area next to a value also as "click here to select whole value" which I also think is a great idea!
- LMB click+drag could be relocated to the property name as it is done in many if not most other professional editing Software.
![inspector_clickdrag](https://user-images.githubusercontent.com/47016402/57157043-e0e8d280-6ddf-11e9-9f5c-4aa61fb7d88d.gif)

**Comment by Calinou** [comment]
This is now fixed in the `master` branch thanks to https://github.com/godotengine/godot/pull/36231. (The fix applies both to scalar and vector fields.)

![Normal property](https://user-images.githubusercontent.com/180032/87589797-12e50c80-c6e6-11ea-8cae-de33f280f455.png)

![Editing property](https://user-images.githubusercontent.com/180032/87589764-0a8cd180-c6e6-11ea-9743-54ca891d4f65.png)
