### ISSUE TITLE
Add commit hash & scons build flags to official releases to make debugging easier

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#28617]
**Godot version:**
v3.1-stable

**Issue description:**
It takes a lot of time to find out the flags that were used for official builds. Also git tags may be ambiguous, so I suggest to add the following output to `--version`:

```sh
# Unofficial build - now
# ./godot.binary --version
3.1.stable.custom_build.320f49f

# Official build - now
# ./godot.binary --version
3.1.stable.official

# Unofficial build - suggested
# ./godot.binary --version
3.1.stable.custom_build.320f49f
Build flags: platform=x11 tools=no -j4 bits=64 target=debug

# Official build - suggested
# ./godot.binary --version
3.1.stable.official.320f49f
Build flags: platform=x11 -j4 bits=64 target=release
```

This will make it easier to reproduce issues & make builds fully deterministic.

**Comment by Calinou** [comment]
I think it would be good to extend the hash to 9 characters while we're at it, which can prevent ambiguity since the Godot repository now has over 20,000 commits.

**Comment by and3rson** [comment]
Closing as resolved!
