### ISSUE TITLE
Dragging a property from the search (control - f) will lack a self node.

### ISSUE THREAD

**Issue by fire** [godotengine/godot#28614]
**Godot version:**
0eb924a425281dfae4672ec114dc42b4067205ec

**Issue description:**
Dragging a property from the Generic Visual Search (control - f) will lack a self node.

Press control-f in an empty visual script.
![2019-05-02_08-13-47](https://user-images.githubusercontent.com/32321/57086046-476fd280-6cb2-11e9-8661-18719485cef0.png)
![2019-05-02_08-14-10](https://user-images.githubusercontent.com/32321/57086056-49399600-6cb2-11e9-88da-76fcfcef3a54.png)

**Comment by Jummit** [comment]
This could be easily fixed by making the new function node a self call.

**Comment by fire** [comment]
That sounds like a good idea It's a variable change from instance to self, want to look at it?

**Comment by Jummit** [comment]
> That sounds like a good idea It's a variable change from instance to self, want to look at it?

Will do!
