### ISSUE TITLE
Make built-in scripts show the name of the attached node in the script tab

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28615]
Sort of a revival of #14577

**Godot version:**
3.1.1

**Issue description:**
Working with many built-in scripts in the same scene is really annoying, because the names are 
not very descriptive:

![image](https://user-images.githubusercontent.com/28286961/57087335-1ae2a780-6d00-11e9-8f3b-d4058966de1f.png)

Maybe this could be solved by naming the scripts by the name of the node they are attached to.

**Steps to reproduce:**
Create a scene with a bunch of nodes and attach built-in scripts to all of them. No try to find the a script of one node.

Code responsible:
https://github.com/godotengine/godot/blob/b0931806c2a085e84ecc4d7989436edc83cd70a8/editor/plugins/script_editor_plugin.cpp#L1606

**Comment by samdze** [comment]
This could be a problem, built-in scripts are often attached to a single node but don’t have to.
They can be attached to multiple nodes just like non built-in scripts.

**Comment by Jummit** [comment]
> This could be a problem, built-in scripts are often attached to a single node but don’t have to.
> They can be attached to multiple nodes just like non built-in scripts.

How would that work? Multiple nodes referring to the same script?

**Comment by samdze** [comment]
You can copy paste the script property to different nodes.
I think something more like this #24708 would be a better solution.
