### ISSUE TITLE
Serialization of custom resources on the network

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#28622]
**Godot version:**
v3.1-stable

**OS/device including version:**
ArchLinux rolling

**Issue description:**
There does not seem to be a generic way of serializing custom Resource classes. This requires every resource to be serialized/de-serialized to/from JSON before sending them via RPC. If this is not going to be implemented, I think it would be good to add a new entry to networking documentation describing what can be serialized by Godot and what does not.

Currently documentation mentions that Godot in fact *can* serialize resources, but it does not seem to work for custom resources.

**Steps to reproduce:**
```gdscript
# foo.gd
extends Resource
class_name Foo
export (int) var answer = 42

# bar.gd
extends Node
sync func take_this_resource(resource):
    print(resource)  # Prints [Resource], but it does not have the "answer" field.

func _ready():
    some_node.rpc('take_this_resource', Foo.new())
```

This requires to implement a lot of boilerplate methods like `serialize(instance)` and `restore(data)` and call methods like this:

```gdscript
# foo.gd
extends Resource
class_name Foo
export (int) var answer = 42

func serialize():
    return {'answer': self.answer}

func restore(data):
    self.answer = data.answer
    return self

# bar.gd
extends Node
sync func take_this_resource(resource_data):
    resource = Foo.new().restore(resource_data)
    print(resource)  # Prints [Resource] with properly defined "answer" field.

func _ready():
    some_node.rpc('take_this_resource', Foo.new().serialize())
```

Are there any other out-of-the-box solutions that I'm missing here?

**Comment by and3rson** [comment]
If anybody could point where does resource serialization happen in sources, I could work on PR to implement this.

**Comment by Resonious** [comment]
I ran into this too and did some poking around. Turns out, there is an out-of-the-box solution:
```gdscript
get_tree().get_multiplayer().allow_object_decoding = true
```
Might make a docs PR pointing that out later.

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/pull/27485 for context (CC @Faless).

Though @and3rson reported this against 3.1-stable, while this fix was added in 3.1.1-stable / 3.2-stable, so not sure if it was exactly the same issue.

**Comment by pwnorbitals** [comment]
If I understand correctly, this has been documented and no further action seems to be envisioned, so this issue might no longer be relevant ?

**Comment by Faless** [comment]
Closed as this is documented in the engine reference, we might want to open an issue/PR in godot-doc if it's not mentioned in the networking tutorials.
