### ISSUE TITLE
Error when baking navmesh for very large mesh

### ISSUE THREAD

**Issue by Toshiwoz** [godotengine/godot#28624]
**Godot version:**
3.1.1 official

**OS/device including version:**
Windows 10 (x64)

**Issue description:**
When I try to bake navmesh for a very large mesh a terrain mesh made of 64x64 Quads (I mean 2 triangles) each triangle is more than 300mts (I mean godot units), I get this message:
```
ERROR: _build_recast_navigation_mesh: Condition ' !rcCreateHeightfield(&ctx, *hf, cfg.width, cfg.height, cfg.bmin, cfg.bmax, cfg.cs, cfg.ch) ' is true.
   At: modules/recast/navigation_mesh_generator.cpp:182
```
Now, if I reduce the size (not scale) of the same mesh, it works flawlessly.
I tried to change the default values, but, as I have no Idea of certain parameters, I can't tell which one I have to change and how, so I did it randomly, but the best result I could obtain was an infinite wait, that in the end leeds to have my computer almost freezins (CPU process always around 25-30%, still, sometimes Windows becomes super slow in responding, I have a 5th gen i5 CPU).

Workarounds to upscale (yes, this time using the scale value in the node transform) the small mesh does not work as my units will move far above ground, funny but not what I want.
As my terrain is massive, but still super simple, I believe there should be a way to make it work.

**Steps to reproduce:**
I have created a sample project, it has 2 meshes (that I created on another project with GDScript), one is small, one is super large.
Try to bake navmesh of the small one, it works.
Then try to bake the superlarge, nothing is generated, but the console output returns the error mentioned.

**Minimal reproduction project:**
[LargeNavMesh.zip](https://github.com/godotengine/godot/files/3139866/LargeNavMesh.zip)

**How do I feel about it 😥**
Please, help me out, this time I'm trying to come out with a full game, and I'm putting a lot of effort into it.
If I'll have to delay it to Godot 4 or later I know I'll be very sad (I won't move to Unity nor any other game engine as Godot is GREAT).

**Comment by Toshiwoz** [comment]
I also tried to simplify the mesh to a 16x16 one, and changed the parameters, usually to highest values (but not for agent), and it generated the heightfield, was eroding something something (sorry couldn't remember what it eroded, I guess slopes), and it crashed.

**Comment by Ace-Dragon** [comment]
A couple of things to try.

- Make your Navmesh in Blender and use the Better Collada Exporter with the -navmesh tag in the object name. This will import as a navmesh in Godot, the only downside is that the exporter does not create a navigation node, so you need to save the navmesh to a file in Godot and create it in your scene by way of creating a navmesh node. If your levels aren't generated dynamically this could work.
- Untested, but maybe subdivide the very large mesh so it has smaller faces?

---
Either way, Godot should at worst show an error message box if something is not meant to work, so the bug is valid.

**Comment by Toshiwoz** [comment]
The only way would be to subdivide it into smaller meshes, I'm generating on the fly the whole planet Mars, so I can't store all that data.
But I don't even know if actually I can bake navmesh from GDScript.

**Comment by Toshiwoz** [comment]
But, yeah, I'm here to report an issue with the engine, more than finding a soultion to my case.
It shouldn't crash at least.

**Comment by bojidar-bg** [comment]
The test project has a huuuge mesh, I can't even see all of it with the maximum Z-Far plane setting in the editor. Maybe you should still downscale it a bit?

That being said, I increased the navmesh's "Cell size" property to `1`, and tried to bake the mesh. Didn't manage to get a navmesh after 1 hour and a half. In the process it used needed just 18 GiB of RAM.

At 0.01 scale, it bakes under a few seconds, even with the default cell size.

I think the error you are observing might be from not having enough RAM memory to fit the whole voxel heightfield at once, which is needed to generate the navmesh.

**Comment by Toshiwoz** [comment]
Downscaling might be an option, I'll have to do it with everything tho, terrain, buildings, units.
But probably a custom A* algorithm would fit better my case I guess, I had a version that was aaalmost working with GridMap, but now I'm not using gridmap anymore and Just a mesh generated on the fly, that, by the way, improved performance a lot.


With that said, it would be nice to have a sort of warning, so that none will ever try that.

**Comment by bojidar-bg** [comment]
@Toshiwoz I just tried setting Cell size and height larger than the allowed values, and it seems to work just fine. Going to PR it in a moment :)

**Comment by Toshiwoz** [comment]
Thank you, that's great news.
So that means I can simply put greater values for larger meshes as the one in the example?
And in my particular case would be those 2 values you mention (Height and Cell size)?

**Comment by bojidar-bg** [comment]
Given that it worked when I scaled the mesh to be 100 times smaller, it should work with the unscaled mesh and cell values 100 larger. Make sure to change the Agent values so that they fit as well though.
