### ISSUE TITLE
Android in-app purchases Google Play does not see apk the problem BILLING

### ISSUE THREAD

**Issue by ilyafuu** [godotengine/godot#28623]
**Godot version:**
3.1.1.stable

**Issue description:**
https://docs.godotengine.org/en/3.1/tutorials/platform/android_in_app_purchases.html#getting-the-product-details

I tried many times all useless. BILLING does not see :(

**Steps to reproduce:**
![owbusay](https://user-images.githubusercontent.com/17591539/57105181-ce648f80-6d32-11e9-8f90-b0c67b6fc393.png)
![2019-05-02_23-07](https://user-images.githubusercontent.com/17591539/57104377-d8858e80-6d30-11e9-8ac6-7e8be11651ac.png)
![9zTIuw9](https://user-images.githubusercontent.com/17591539/57104392-e20ef680-6d30-11e9-9300-9f696bb61967.png)
![epaU6g1](https://user-images.githubusercontent.com/17591539/57104397-e63b1400-6d30-11e9-894f-40e96efb67e1.png)

Google Play replied:
Currently, this application does not sell content.
To upload content for sale through applications, add the BILLING permission to the APK file.

**Minimal reproduction project:**
demo project iap >>>
https://github.com/godotengine/godot-demo-projects/tree/master/misc/android_iap

**Comment by volzhs** [comment]
if i understand correctly what you said,
you need to add a "permission" from here.
![Screenshot_20190503_060706](https://user-images.githubusercontent.com/8281454/57107015-e1df1d00-6d69-11e9-8f1d-b7ecf2bfd2dd.png)
what you did is that your app ID is com.xxx.BILLING.
and you should not change `com.android.vending.BILLING` to another like you did.

**Comment by ilyafuu** [comment]
@volzhs It works, thanks ^_^

**Comment by ilyafuu** [comment]
I did not look down "permission"

**Comment by ricardoalcantara** [comment]
As it's always required for IAP it should be in the documentation.
