### ISSUE TITLE
Ability to select Video RAM compression formats for every image

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#28621]
**Godot version:**

Godot 3.1.2-devel

**OS/device including version:**

MacOSX 10.13.6

**Issue description:**

I make export to iOS and to Android from one project. For iOS I use GLES3 and pvrtc compression for many textures. For Android  I use GLES2 and etc1 compression but only for textures without alpha channel (because etc1 has no support of alpha channel).
So I have to switch compression mode for many textures every time I export to one platform or to another. It takes a lot of time to generate new pvrtc textures every iOS export.

The ideal solution will be to make separate alpha channel compression for etc1 (or other alphaless formats), but I think that it may be very difficult to implement.
Another way - to detect if image has the alpha channel and use some flag in project settings to skip etc1 conversion.
Another way N2 - to be able to select which video ram compressions will be applicable for this texture.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by DrMoriarty** [comment]
related #26211

**Comment by Jimmio92** [comment]
@DrMoriarty Couldn't this problem easily be solved by keeping a copy of your project for Android and one for iOS?

So that way... you develop in folder 'project'... and when it comes time to build for Android and iOS, copy everything from 'project' except the project.godot so settings don't get overwritten to 'project_android' and 'project_ios', which are "separate projects"

**Comment by DrMoriarty** [comment]
@Jimmio92 this way don't solve the issue. When I copy all files except the project.godot, I will have the same *.import files and the same textures will be vram compressed. Actually I need one texture compress by different ways during export to different platforms.
